### ISSUE TITLE
Open Source Community Job Board?

### ISSUE THREAD

**Issue by lazarofl** [frontendbr/vagas#1]
## Proposta / Iniciativa
Disponibilizar um formato padronizado de publicação de vagas para uma determinada comunidade aberta.

Plataforma open-source que utiliza **issues** em um **repositório github** como base de dados e de gerenciamento para uma determinada comunidade aberta.

 - [ ] Definir um nome para esse tipo de plataforma **:P** (github community job boards?)

## Plataforma de publicação
![image](https://cloud.githubusercontent.com/assets/913314/12789381/c7a82cc8-ca84-11e5-95c4-a4cf95243556.png)

## Milestones

Definem os _locais_ onde as vagas estão disponíveis

- [x] Remoto
- [x] São Paulo
- [x] Campinas
- [x] Recife
- [x] ...

## Labels

Define as _skills_ que a comunidade em questão utiliza para cadastrar a vaga

- [x] NodeJS
- [x] Ruby on Rails
- [x] .NET
- [x] React
- [x] Angular
- [x] MongoDB
- [x] ...

## Visualização das vagas

- A proposta independe de um site
- É acessível a toda e qualquer organização
- Vagas ficam publicamente acessíveis em **https://github.com/[nome_da_organização/comunidade]/[nome_do_repositorio]/issues/**
- Qualquer pessoa pode cadastrar uma vaga na comunidade

### Exemplo de postagem

![image](https://cloud.githubusercontent.com/assets/913314/12790408/3f903042-ca89-11e5-9637-39f5dd7f2f31.png)

### Visualização de vagas por locais

![image](https://cloud.githubusercontent.com/assets/913314/12790420/4ed19bb8-ca89-11e5-99e3-6ea54a4a9dfb.png)

### Generators

O projeto pode também disponibilizar uma **aplicação web** em __nodejs__ ou __ruby__ para fazer a leitura das **issues** via **github API**, permitindo assim que a comunidade possa disponibilizar um quadro de vagas colaborativo em um domínio diferente do github.

**Comment by PabloDinella** [comment]
É interessantes identificar também se é fulltime, clt, estágio... Talvez através de labels tbm?

**Comment by lazarofl** [comment]
o @kevinthomas-dev tinha ajudado a definir o que deveria conter na descrição da issue.
Ficou algo como:

 - Uma breve descrição da vaga
 - Nível de experiência necessária
 - Salário (o valor, ou se é a combinar) + formato (se é PJ ou CLT)
 - Contatos / Como se candidatar

Eu fiz um exemplo de como ficaria aqui https://github.com/lazarofl/lazarofl.github.io/issues/1

Ja vi algumas vagas que falam sobre a empresa antes de falar sobre a descrição da vaga também. Tendo um formato padrão documentado no readme do projeto acho que seria o suficiente para cobrir o principais dados.

**Comment by lazarofl** [comment]
Galera, achei a ideia boa demais pra ficar apenas por aqui, criei um projeto a iniciativa em https://github.com/lazarofl/Community-Job-Board-Initiative

Acho que é uma boa até mesmo para fecharmos um padrão no readme de cada projeto desse tipo.
