### ISSUE TITLE
[São Paulo] Mobile / Frontend

### ISSUE THREAD

**Issue by sibelius** [frontendbr/vagas#10]
## Descrição da Vaga

Estamos buscando um desenvolvedor​ ​para início imediato. Esperamos:
● Conhecimentos sobre desenvolvimento em Java, Python e Javascript ​(AngularJS, ReactJS, Android são bons extras)
● Vontade de programar como gente grande​e conhecer o funcionamento de uma startup desde o começo
● Consciência​ ​que ​deve-se fazer de tudo (sem “prima-donnismos” ou braço curto)

Se você não tiver conhecimentos dos primeiros pontos, mesmo assim pode entrar em contato conosco: somos super flexíveis e, quem sabe, podemos acertar algo que funcione para ambas as partes.

## Local
Anhangabau - São Paulo - SP

## O que oferecemos além de um salário
**Ambiente AAA​**: Colegas internacionais, gente com experiência em software/hardware/indústria/pesquisa/banco, aqui você vai poder trabalhar com pessoas incríveis e aprender muito com elas. Esperamos que você contribua também!
**Horário flexível​**: você escolhe quais horas do dia ou da noite quer passar aqui (desde que o prédio esteja aberto)
**Plano de carreira**​:​ nossa startup está crescendo e precisamos de mais gente no time para o longo prazo!
**Clima descontraido, democrático e, acima de tudo, divertido​**. Sua experiência será super relevante: não são “monkey-jobs”
**Grande exposição a muitas tecnologias​.** ​Aprenda as melhores práticas de front-end, back-end, dev-ops e mobile… Aqui fazemos tudo “in-house” e você poderá aprender muito com seus colegas e se desenvolver de acordo com suas vocações/talentos

## E... tem algum perk? (claro que tem!)
**Café/chá “dos bons”!**​- pode ser até café Suplicy, chás da china
**Back to nerd times**​: happy hours na sexta com CS - porque a gente é dessa época, mas se tiver alguma sugestão,
também está valendo. O que conta é a descontração, acompanhada de cerveja importada
**Seu próprio cartão de visita** ​com o título que você quiser ter. Pode ser Doutô, Darth Vader, Chapolim Colorado…
**Almoços por conta “da firma” nas sextas** ​para relaxarmos, batermos um papo e nos preparar para a sessão de counter mais tarde!

## Quem somos?
O [PontoTel](http://home.pontotel.com.br/)​ é uma empresa de automação de registros trabalhistas para funcionários. Nós somos um “SaaS de RH”adaptado para as necessidades dos consumidores residenciais.
A equipe é formada por dois engenheiros (POLI-COMP e FEI elétrica) e dois cientistas da computação do ICMC/USP.
Você trabalhará diretamente com eles e nós vamos fazer o possível para que esse seja o trabalho mais bacana (isso mesmo) que você venha a ter. Todos (inclusive os fundadores) são desenvolvedores e lutamos para construir a empresa que sempre sonhamos em trabalhar.

# Como se candidatar?
Envie um email para sibelius@pontotel.com.br

**Comment by LFeh** [comment]
A vaga foi preenchida? @sibelius

**Comment by sibelius** [comment]
sim

**Comment by LFeh** [comment]
;)

**Comment by camilatigre** [comment]
@sibelius 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

**A pessoa que preencheu a vaga foi encontrada através desta issue?**
a) Sim
b) Não
c) Não tenho certeza

**Comment by sibelius** [comment]
Não
