### ISSUE TITLE
[Florianópolis/SC] Desenvolvedor Ionic

### ISSUE THREAD

**Issue by Segware** [frontendbr/vagas#100]
## Descrição da vaga

Atividades: atuar no desenvolvimento em Java dos produtos mobile da Segware. 

## Local

Rodovia SC 401, 8600
Corporate Park - Bloco 2 - Sala 7
Santo Antônio de Lisboa, Florianópolis - SC
CEP: 88050-001

## Benefícios

- Vale alimentação/refeição (sem desconto em folha)
- 1h30 de almoço
- Lanche da tarde na empresa / espaço lounge com videogame
- Unimed e Uniodonto
- Seguro de Vida
- Ginástica Laboral
- VT ou estacionamento pago pela empresa
- Auxílio educação
- Cursos de Idiomas in company

## Requisitos

Conhecimentos necessários em: 
- Ionic / AngularJS
- HTML
- CSS (Bootstrap)

Conhecimentos desejáveis em: 
- Java
- Spring / Hibernate
- Computação em nuvem, ambiente Amazon (AWS)
- Utilização de controle de versão e metodologias ágeis. 

Inglês e/ou espanhol.
*Experiência necessária com desenvolvimento em Ionic.

## Contratação

CLT

## Nossa empresa

A Segware é uma empresa multinacional responsável pelo desenvolvimento e comercialização do sistema de monitoramento de alarmes SIGMA, software mais completo da sua categoria, com mais de 70% das contas monitoradas no Brasil. Fundada em 2001, em Florianópolis/ SC atendendo a demanda de uma empresa de serviços de segurança e hoje líder absoluta no segmento de software de monitoramento de alarme.

## Como se candidatar

Por favor envie um email para gestaorh@segware.com.br com seu CV anexado - enviar no assunto: Vaga Ionic

**Comment by LFeh** [comment]
Boa sorte ;)

**Comment by eduardojmatos** [comment]
@Segware já preencheu a vaga? Nos avise pra mantermos ou removermos da lista :)

**Comment by Segware** [comment]
Sim, a vaga ja foi preenchida :)

**Comment by eduardojmatos** [comment]
@Segware boa :)

**Comment by camilatigre** [comment]
@Segware 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by pauloanalista** [comment]
Moro no RJ e estou quase indo para Floripa, caso minha família aceite morar em outro estado, vou me candidatar a esta vaga.
