### ISSUE TITLE
[Florianópolis] Front-End Developer na McFadyen Digital

### ISSUE THREAD

**Issue by monicaschwartz** [frontendbr/vagas#1000]
## Descrição da vaga

About You

Are you an innovative person who can accelerate the growth of our nationally acclaimed project? Do you have a passion for technology and a flexible, creative approach to problem solving? Are you self-directed, confident, and able to work without requiring a great deal of structure or supervision? Are you highly self-motivated and having head full of ideas? If you answered yes to these questions, we want to talk to you.

 

Position Summary

We are looking for creative and dependable self-motivated professionals to join our team as a Junior UI Developer.

 

Responsibilities

• Create reusable and clean UI pattern framework that Application Developers can plug and play

• Handle customer expectations on challenging projects

• Adhere to code standards and ensure consistency

• Quickly convert wireframes into HTML front-end with optimal quality

• Team with our Application Developers to bridge the client side with server side code

• Ensure quality assurance on front-end code including HTML, CSS, and JavaScript

• Deliver consistency of the user interfaces across multiple platforms

• Provide production support for all implemented changes

• Work in a small, fast-paced, team-oriented environment

• Liaise closely with onsite counterparts in order to continue to drive product forward

## Local

Florianópolis, Santa Catarina

## Benefícios

- Plano de saúde
- Plano odontológico
- VR ou VA de R$ 20/dia
- VT

## Requisitos

• Proven experience in UI development and integration for web and mobile applications with  delivered projects

• Applied experience of UI development principles

• Have a good understanding of the three pillars of front end development which are HTML, CSS and JavaScript

• Generate clean, semantic HTML and CSS

• Have exceptional proficiency in writing Vanilla JavaScript (no jQuery!) from scratch, understand MVC coding model and object oriented concepts

• Know the Responsive web and have a little bit of knowledge about current UX trends.

• Have practical exposure on frameworks and APIs such as jQuery, Backbone, Handlebar, AngularJS, LESS, and Bootstrap

• Ensure cross-browser and cross-device compatibility

• Believe take actions so that disabled and visually challenged users have a right to use the web as easily as everyone else

• Exposure on e-commerce platforms is preferred and strong experience in agile methodology is a plus
## Nossa empresa

MCFADYEN DIGITAL (Previously McFadyen Solutions) is a leading digital agency with 20 years of experience helping global brands shape the future of Omni-channel commerce, marketing and service delivery. Hundreds of MCFADYEN clients achieved digital success with MCFADYEN’s advisory, creative, and technical services which often leverage Oracle software.

Our consultants work with clients to reinvent their digital strategy with collaborative interactions that forms the core of our philosophy of creating happier relationships with customers. Be it Technology Consulting or Systems Integration or Omni-Channel commerce solutions or Digital Marketing Advisory or User Experience Services, MCFADYEN DIGITAL offers 360 degree services to customers to help them win big in the market.

Headquartered in the US with offices in India and Brazil, MCFADYEN DIGITAL has several hundred professionals serving clients round the clock.

## Como se candidatar

Por favor cadastre seu currículo através do link http://smrtr.io/AxLssQ

**Comment by diogomoretti** [comment]
@monicaschwartz quais as labels?
