### ISSUE TITLE
[Brasil] Front-End Developer na [pólya] VAGA PREENCHIDA!

### ISSUE THREAD

**Issue by rafaelpolya** [frontendbr/vagas#1002]
## Descrição da vaga

Precisamos de front-end para dois projetos, com duração de 60 dias no total:

Criar site utilizando Nuxt.js
O site receberá conteúdo via API. O front-end precisará apenas criar o HTML/CSS e receber os dados da API.

Admin feito em Vue.js e Firebase
Projeto já esta em andamentos, seria necessário adicionar alguns recursos e fazer debug. O admin é todo escrito em VueJS e todas as consultas vem do Firebase.

Projeto para 60 dias, iniciando na ultima semana de Abril 
O profissional deverá estar disponível de segunda a sexta, das 9h ~ 17h (podemos combinar outros horários), utilizando o Discord da empresa.

## Local

Remoto Total

## Requisitos

Obrigatórios:
- Conhecimento intermediário em HTML/CSS/Javascript
- Conhecimento em Vue.js (desejável Nuxt.js também)
- Firebase

Diferenciais:
- React-native (para futuros projetos)
- Sentry

## Contratação
R$ 3.500,00 por mês ou R$7.000,00 no fim do projeto- PJ 

## Nossa empresa

Somos uma pequena produtora precisando de ajuda em alguns projetos. :)

## Como se candidatar

Enviar email para: vagas@polya.pro com o assunto: [Vaga] - Frontend

## Labels

- Freela
- PJ
- Pleno
- Remoto - Total

**Comment by ribeiroevandro** [comment]
Enviado

**Comment by andrebrandaoo** [comment]
Enviado
