### ISSUE TITLE
[Total Remote / California] Front-end Engineer at Cyza! California CO.

### ISSUE THREAD

**Issue by cyzainc** [frontendbr/vagas#1007]
FRONTEND DEVELOPER (REMOTE / CALIFORNIA) JavaScript, ES6, SASS/CSS3, HTML5
CYZA, INC. — LOS ANGELES, CALIFORNIA, USA

We are hiring experienced frontend developers. Positions require full-time or very close to full-time commitment.

Although we are based in California, USA, this is a remote position for candidates working from their own home/office. Only individual applicants will be considered in joining our team, therefore, outsourcing companies or existing programmer teams will NOT be considered.

Basic conversational English is enough to work with our team and you do not have to be fluent. Mic, webcam, and excellent/reliable internet connection is required for remote communication. This is not a temporary job and you should be open to a long-term engagement.

About our platform’s technology stack: back-end is developed in Golang REST API, and front-end consists of Vanilla JavaScript (ES6), spf.js, Gulp, Webpack, jQuery, SASS, and HTML5 technologies. We do not commit to any frameworks and only use libraries if needed. Our application is perhaps more hybrid between server-rendered and client-rendered. This is a large project and and will grow a lot more. Maintaining a great architecture and employing best coding practices is a top priority.

**Skills & requirements**

(1) At least 1 (one) year or solid experience with each of the following technologies:

Vanilla Javascript / EcmaScript 6+
jQuery
Gulp
Webpack
SASS
CSS3
HTML5

(2) Love to code and be a team player in a fast-paced development environment
(3) Able to work and learn independently.
(4) Able to work with existing code and architecture and have some experience of working in large projects (our platform is 80% developed).
(5) Be good at analysis of bugs, browser compatibility issues, and optimization issues.
(6) Basic conversational English is enough to work with our team and you do not need to be fluent.
(7) Excellent and reliable internet connection.
(8) Be a “DOER”.

**Company**

Cyza is the next generation mobile and web-based marketplace platform for services! Built on solid design and technologies. The company is developing an omnichannel commerce platform focusing on service sector first.

**How to apply**

We look forward to learning about you and your knowledge. Please apply by emailing to jobs@cyza.com and include the following:

(1) Attach to your email a basic resume that describes your current and past jobs including any major freelance work, education/degrees; and
(2) Mention in your email that you have read the required skills and that you have experience with each; and
(3) Mention in your email that you found this job on frontendbr/vagas/issues

**Comment by GustavoCostaW** [comment]
Não recomendo aplicar, fiz teste ano passado, gastei uma tarde inteira e não recebi NENHUM FEEDBACK, nem pra saber se passei ou não passei, isso mesmo, mandei o teste e NUNCA mais me responderam!

**Comment by LFeh** [comment]
Tenso heim...

**Comment by cyzainc** [comment]
@GustavoCostaW    Esta não é uma declaração justa para você dizer! Eu verifiquei seus registros e vi que você teve bastante tempo para entregar sua avaliação de habilidades e depois não conseguiu concluí-la a tempo. Você, então, pediu mais tempo e nós até lhe demos mais tempo e então você NOVAMENTE entregou a avaliação quase metade do tempo não feito! Nós não avaliamos algo que não foi concluído porque não é justo para os outros e mesmo se quiséssemos, não poderíamos porque faltam habilidades críticas que testamos para cada parte! E eu tenho certeza que você sabia que dar-lhe feedback sobre algo que não está completo é inútil e não se preocupou em acompanhar. Observe também que não nos importamos com bons seguidores do github e grandes currículos ou palavras, ultimamente nos preocupamos com as habilidades específicas de um candidato e, o mais importante, como um candidato confiável e decifrado é fazer parte de nossa equipe crescente e forte. Estamos à procura de membros da equipe fortes e confiáveis ​​e não achamos que você se qualificou como tal. No entanto, desejamos-lhe o melhor em futuros destinos e boa sorte.

**Comment by GustavoCostaW** [comment]
Interessante, não é o que diz meus registros aqui:

Evento para finalizar teste...

[![Screen_Shot_2018-05-03_at_23.34.27.png](https://s17.postimg.cc/nzsqa27m7/Screen_Shot_2018-05-03_at_23.34.27.png)](https://postimg.cc/image/peuays8p7/)

Confirmação do recebimento do teste...

[![Screen_Shot_2018-05-03_at_23.34.47.png](https://s17.postimg.cc/jqo07wc2n/Screen_Shot_2018-05-03_at_23.34.47.png)](https://postimg.cc/image/gwkuug9wb/)

nas mesmas datas...

Enfim, absolutamente nada contra vocês, nem sei quem vocês são, só estou dando um feedback sincero para vocês melhorarem o processo de seleção de vocês, se não fui bom o suficiente ai é outra história, mas vocês poderiam simplismente ter mandado um : 'Ok, Gustavo, Infelizmente você não passou no teste blablabla,'  e claro se puder mais ainda falar os pontos, da mesma maneira que gastei um tempo fazendo as horas, vocês poderiam ter feito o mesmo pra pelo menos dar um feedback.

Boa sorte guys.

**Comment by cyzainc** [comment]
Again, you show submission confirmation which is right but you fail to understand that your submission itself was INCOMPLETE! and can't be evaluated and is not fair to others!

**Comment by GustavoCostaW** [comment]
@cyzainc eu já entendi que para vocês meu teste não foi completo/suficiente OK, a questão é, custava vocês mandarem UM E-MAIL? Reportando que não fui aprovado? Só um 'Você não passou no teste' já seria o suficiente, enfim, vocês já entenderam, Boa sorte guys!

**Comment by cjpatoilo** [comment]
Aí, recentemente vi esse **[post no LinkedId](https://www.linkedin.com/feed/update/urn:li:activity:6397410151875244032)** que fala sobre esse ridículo comportamento de certas empresas:

> CARO RECRUTADOR: 
>
> OK, você não pode contratar todo mundo que entrevista e resolver o problema do desemprego no Brasil, mas enviar um simples email, com 1 linha que seja, pra informar aos demais candidatos que a vaga foi fechada/cancelada/congelada... É possível ou estamos pedindo demais? 
>
> Ajude os demais candidatos a continuarem suas jornadas na busca, a virarem a página, liberte-os do peso da espera inútil e eterna que causa tanto estresse e bloqueios psicológicos!
>
> Tente fazer isso, você vai ver como um simples email de consideração vai fazer tão bem, mesmo aos candidatos desclassificados.
>
> Eles estão tão desacostumados com isso que vão virar seu fã, pode acreditar!
> 
> #FeedbackNaEntrevista #EstrategiaDoQIDigital

...e faz sentindo, com certeza irá gerar um bom sentimento no candidato. Qualquer coisa é melhor do que ficar no vaco esperando uma resposta que nunca virá. 😔

**Comment by alinebastos** [comment]
Nossa, completamente desnecessário, muito feio, inclusive, fazer o feedback do candidato publicamente! Se tivesse feito isso por e-mail teria evitado todo esse constrangimento.
BTW, também não recebi feedback.
E, por favor, não quero feedback público ;)

**Comment by lbighetti** [comment]
O bom é que isso mostra bem o tipo de empresa que eles são e ilustra como é a cultura.

A única coisa boa é que essa issue está pública para os as pessoas verem como eles tratam os candidatos e como lidam com problemas.

Se você está lendo esse issue para se candidatar eu sugiro revisar como a empresa trata os candidatos (spoiler alert: como lixo).

Lamentável.

**Comment by gabrielsimas** [comment]
Existem empresas e empresas... e demos azar com esta!
Realmente foi vergonhoso o que fizeram, expuseram uma conversa privada em meio público e ainda querem reclamar do Snowden... sem comentários!

**Comment by rgazeredo** [comment]
São países e culturas diferentes, eu mesmo já apliquei para empresas americanas que ainda não me deram um feedback, outras ficaram de marcar uma entrevista e não retornaram, se você passou eles vão retornar, até aqui no Brasil quando você vai fazer uma entrevista, nem toda empresa retorna falando que você não foi selecionado. Não acho que a empresa deva ser julgada por esse motivo, pois como falei são culturas diferentes e não podemos trazer isso para nossa realidade e comparar com a nossa cultura, porém achei desnecessário esse bate-boca aqui, ambas as partes poderiam enviar um e-mail para resolver isso... Mas enfim essa é só a minha opinião.

Are different countries and cultures, I even applied to United State companies that have not given me feedback yet, others have left an appointment and have not returned, if you have gone they will return, so far in Brazil when you go to do an interview, not every company returns saying that you were not selected. I do not think that the company should be judged for this reason, because as I said are different cultures and we can not bring this to our reality and compare with our culture, but I found it unnecessary this chat here, both parties could send an email to solve this ... But anyway this is just my opinion.

**Comment by lucasfernandes** [comment]
There's no reason to expose the company like that based on a particular bad experience.. I'm sited on my chair waiting for feedbacks from local companies and nothing so far.... Should I ask my dead mom to prepare my milk, really? I'd feel tottaly in shame for that. The world needs more "professionals"

**Comment by mdamaceno** [comment]
Me deram feedback hoje de manhã. Como muitos aqui, não passei rs.

**Comment by simmythelead** [comment]
I find it *extremely unprofessional* that a company would share this about a candidate in public:

```
I see that you had plenty of time to turn in your skill evaluation and then failed to complete it on time. You then had requested more time and we even gave you additional time and then you AGAIN turned in the evaluation alsmost half not done! We do not evaluate something that has not been completed because it is not fair to others and even if we wanted to, we could not because it's missing critical skills which we test for every part! And I'm sure you knew that giving you feedback on something that is not complete is worthless anyway and didn't bother to followup. Also note that we don't care about good github followers and big resume or words, ultimatly we care about the particular skills of a candidate and most importantly how deciplined and reliable a candiate is to be part of our growing and strong team. We are looking for strong and reliable team members and we did not think you qualified as such. Nevertheless we wish you best in future endovers and good luck.
```
@cyzainc You could have resolved this with 1 private email, instead **you chose to humiliate the candidate in public.**

This tells me everything I need to know about your company indeed.

**Comment by cyzainc** [comment]
@simmythelead we feel sorry for people like you who hide behind phony new profiles to satisfy their bidder failures and useless thoughts. And it's obvious of your intelligence level when you don't read the first comment made by a candidate who chose to make his issue public. People like you never even get to out interview process and we have no interest in hiring people like you with little understanding of  professionalism. Focus on improving you skills and focus on your career, these comments won't get you anywhere in life.

**Comment by klferreira** [comment]
@cyzainc diminishing people is nothing professional either.

**Comment by alinebastos** [comment]
@cyzainc at the beginning you two were wrong, he talked about you and you talked about him. Terrible.
I even received an e-mail from you that I found very good, I replied, I understood your side.
But now you, again, are super unprofessional about it publicly, talking about a person, diminishing him.
You have to know that you, as a company, will not be affected, but him (or anyone else), as a professional will be affected by your words, professionally!
I think you should have someone controlling what you guys say because it is getting only worst.

**Comment by alinebastos** [comment]
I do not believe that the company that I applied to did something like that when I just put here my opinion!

![image](https://user-images.githubusercontent.com/387470/39666352-bc648524-5078-11e8-841d-eb0a622c0c33.png)

**Comment by GustavoCostaW** [comment]
Eu tinha decidido não postar mais aqui para não criar mais problemas desnecessários, acho que vocês já entenderam meu feedback, mas depois de acusações como:

``
 but if you look at the first comment from from Mr. Costa, he criticized us in public and recommended others not to apply as he is bidder for not being accepted. He has our email and he could have followed-up with our HR privately; but instead, Mr. Costa wanted to make a point here and we had to address it.
``

E também depois de muita gente me acusando falando que eu poderia ter resolvido isso por e-mail, é,  eu sei, mas eu tentei:

**18/07/2017** = Enviei meu teste
**11/08/2017** = Percebi que eles tinha postado a mesma vaga aqui novamente

[![Screen_Shot_2018-05-05_at_11.30.18.png](https://s9.postimg.cc/yxcor3rfz/Screen_Shot_2018-05-05_at_11.30.18.png)](https://postimg.cc/image/67psugnfv/)

LEIAM atentamente, segue meu e-mail para eles:

[![Screen_Shot_2018-05-05_at_11.30.28.png](https://s9.postimg.cc/yklakxgvz/Screen_Shot_2018-05-05_at_11.30.28.png)](https://postimg.cc/image/uo7yoxvwb/)

Ou seja, tentei resolver tudo isso por e-mail.

O objetivo do meu primeiro comentário foi apenas **alertar** outros colegas de trabalho que poderiam gastar horas como eu, e nem se quer receber um **'OK, infelizmente você não foi aprovado',** eu acho que isso independe de cultura, eu já apliquei para várias empresas de fora inclusive **AMERICANAS**, e recebi feedback, mas eles preferiram me humilhar publicamente, enfim.

**Comment by carloschneider** [comment]
O negócio virou discussão de boteco. Acho que já vimos os pontos de todos. A empresa não é obrigada a dar um feedback. Seria legal? Muito. Mas não é obrigada. Talvez percam um pouco de credibilidade por isso? Sim.

Mas acho que a galera precisa seguir em frente e superar isso. Também já apliquei para algumas vagas que nunca me responderam, é normal e é do mercado, e isso não faz da empresa o pior lugar do mundo pra se trabalhar.

Tenham pelo menos um pouco de amor próprio e sigam em frente e parem de bagunçar com a vaga da empresa, tenho certeza que para alguém essa vaga vai ser muito importante :)

@LFeh não acha que está na hora de moderar essa issue?

**Comment by alinebastos** [comment]
Não sei se tu notou, mas o assunto aqui já mudou. O cara falou da empresa, ok, não é legal. Mas a empresa HUMILHOU o candidato publicamente.
Esse é o assunto agora!
Se tu acha que isso é normal, corriqueiro, acho que tu deve rever teus conceitos.

**Comment by alinebastos** [comment]
Se a solução aqui for moderar e silenciar as pessoas, não quero nem ver!

**Comment by dericeira** [comment]
Gente, alguém pode me mostrar onde a empresa humilhou o profissional? Acho que eu perdi isso. O que aconteceu aqui foi que a empresa não deu o feedback da aplicação de emprego e isso é COMPLETAMENTE NORMAL. Ele tem razão de ficar chateado, como eu também já fiquei com isso, mas é assim que o mercado funciona. Não vejo motivos para julgar a empresa.

**Comment by alinebastos** [comment]
@dericeira tu leu tudo o que a empresa falou do profissional? Se tu acha que é ok a empresa falar de ti assim publicamente, show de bola, mas não é.

**Comment by rgazeredo** [comment]
Estou acompanhando desde o início e não vi em momento nenhum a empresa HUMILHAR ninguém nessa issue.
Os valores dos brasileiros parecem estar trocados, parecem que sempre queremos defender o lado errado (pois na MINHA opinião o errado dessa história foi o @GustavoCostaW por trazer isso publicamente).
@alinebastos Eu também li tudo que a empresa falou e NÃO ACHO que foi alguma coisa de mais, você vai falar para eu rever os meus conceitos também?

**Comment by Predoff** [comment]
@dericeira um dos significados de humilhar é "menosprezar", foi o que a empresa fez, dizendo que o profissional não merecia feedback pq o teste dele não estava "completo"

**Comment by kavalcante** [comment]
Honestamente o que eu entendi da resposta da empresa foi: "Nós te mandamos um teste, com algumas exigências, você não preencheu todas e por isso nós achamos inútil te enviar uma resposta já que seria injusto com os outros candidatos que mandaram testes completos".

Eu realmente não vi uma humilhação.

**Comment by alinebastos** [comment]
@Predoff inclusive chamou o candidato de "não confiável".
"Estamos à procura de membros da equipe fortes e confiáveis ​​e não achamos que você se qualificou como tal"
Gente, se vcs acham isso NORMAL, nossa..

**Comment by alinebastos** [comment]
@rgazeredo sim!

**Comment by rgazeredo** [comment]
Acho que a galera faltou na escola, pois não consegue interpretar um texto, em momento nenhum a empresa falou diretamente para o @GustavoCostaW que ele não merecia um feedback, e sim no geral quando um candidato manda o teste incompleto, eles não avaliam.

**Comment by carloschneider** [comment]
Para mim ficou claro que o texto foi traduzido no Google. E acredito que ele não está falando sobre o caráter do candidato e sim sobre o atraso e o teste incompleto. É necessário avaliar o contexto :)

**Comment by alinebastos** [comment]
Então tu não leu bem o que a empresa escreveu:
"Estamos à procura de membros da equipe fortes e confiáveis ​​e não achamos que você se qualificou como tal"
Isso foi geral ou foi pro candidato?

**Comment by carloschneider** [comment]
@alinebastos sim, eu li exatamente o que você leu, mas se você ler um pouco antes, ele fala a respeito da entrega do candidato.

**Comment by alinebastos** [comment]
Sim, eu li tudo, mas eu te colei essa frase. Essa frase fala diretamente com o candidato.

**Comment by carloschneider** [comment]
Já que não vamos concordar, então fique você com a sua opinião e eu com a minha.

**Comment by alinebastos** [comment]
O problema é que tem pessoas que são privilegiadas e não conseguem enxergar isso. Se alguém aqui não vê problema algum na empresa humilhar publicamente vocẽ, você não vai perder emprego, já tá com a vida ganha, ou consegue outro rapidinho, nossa, que bom pra vocẽ!
Mas vcs tem que entender que nem todos basceram privilegiados.
Uma humilhação publica assim pode prejudicar e muito uma pessoa que tem poucas chances na vida.
É tão dificil assim vcs terem um pouco de empatia?
Vcs são pessoas tb, profissionais, que são EMPREGADOS pela empresa.
Ou vcs vão ficar sempre do lado da empresa?

**Comment by Predoff** [comment]
@rgazeredo Faltei a escola? A empresa citou o cara na primeira linha do texto. 

@carloschneider  Vocês que estão tirando o foco da discussão, desmerecendo totalmente, dizendo que o problema é apenas falta de amor próprio, tipo ????? wtf???

A empresa foi deselegante sim, era só responder o cara por e-mail, simples assim.

**Comment by kavalcante** [comment]
"We are looking for strong and reliable team members", essa frase para mim é totalmente subjetiva, o que é forte e confiável para mim, pode não ser o mesmo para você e por ai vai. Tudo pode variar de acordo com os valores da empresa/pessoa.

Se fosse eu particularmente, não me sentiria ofendido. Se o que eu acredito, faço e afins não são os mesmos valores que a empresa procura, não vejo problema em ela não me qualificar com esses adjetivos.

Honestamente, acho muito difícil no nosso mercado uma empresa se preocupar especificamente com um comentário no Github. Novamente, pois a visão de ser "forte e confiável" é extremamente subjetiva.

Eu não estou do lado de ninguém. Nem acho que a empresa deveria ter dado uma resposta pública assim, só não acho que houve uma humilhação. O @GustavoCostaW não recomendou a empresa, a empresa não recomendou ele. Vida que segue.

Inclusive se eu estivesse no lugar dele também gostaria de receber feedback, embora isso não me aborreça tanto quanto parece aborrecer ele.

**Comment by kavalcante** [comment]
Se o @GustavoCostaW se sentiu ofendido a @cyzainc deveria pelo menos pedir desculpas. Ai morre o assunto e todos vamos codar felizes, né não?

**Comment by carloschneider** [comment]
@Predoff Foco da discussão, eu? WAT? Já citaram até privilégios aqui jovem kkk

**Comment by cyzainc** [comment]
@alinebastos this is not a good productive use of time for us as this is already a closed job with over 60 applications submitted, but I'm glad to see many others don't agree with you because the reaction has been puzzling to us to say the least. Let us teach you something as an employer that may help you as you will look for employment anywhere. I hope that you do not see this as criticism but more of a tip. The problem with your perception is that you think the candidate can say whatever he wants! and it will stay one sided. You need to learn that there are always two sides of a coin. One side is the candidate and the other side is the employer. You should always look to the interest of both sides. The interest of an employer is to hire a good team member and the interest of a candidate is to find a stable job to obtain financial support and other benefits. When Mr. Costa says "I do not recommend to apply"  he is 1- diminishing our interest and to us and any other reasonable employer this comment is offending and 2-will also diminish the interest of many other job seekers. This cannot be judged one sided. He made his opinion and wanted to make a point which he is entitled to and we have the right to answer that. When you expose yourself to an argument, you have to be open minded to take any criticism that may follow because there are two sides to every argument and interest. I hope you will learn this sooner than later.

**Comment by alinebastos** [comment]
@cyzainc if you read what I wrote you will see that I said YOU BOTH WERE WRONG.
And, thanks, but I do not need advice or teaching from a company who choose to discuss with candidates publicly. You already proved that you are not a reliable company.

**Comment by Predoff** [comment]
@carloschneider foi meio contraditório o meu comentário, apaguei, foi mal.

**Comment by ThiagoDallacqua** [comment]
Bom, eu ainda tenho somente 1,5 anos de experiência no mercado de desenvolvimento mas mais da metade disso é com mercado internacional, pois desde cedo havia decidido trabalhar remotamente para fora. Falta de feedback é sim uma realidade, mas isso é universal, iniclusive, eu já participei em processo seletivo para realocamento para Alemanha que foi gerido por uma grande empresa nacinal que prometeu uma entrevista com a empresa que nunca aconteceu...

Eu devo dizer que, independente de quem fez o que, não percebi uma falta grave por parte do @cyzainc, a não ser não saber escrever em português, o cara tentou se explicar extensivamente inclusive... Mas, na minha opinião, pior ainda foi a nossa comunidade extender um problema desnecessariamente.

É como foi dito aqui, o problema pode ser simplesmente diferenças culturais, e na boa, não acho que alguém deva tão facilmente se colocar tão insistentemente como vitima de algo que é super normal no mundo profissional. Acho que todos aqui deveriam olhar pra frente e tentar aprender um pouco com tudo isso, cada um na sua medida.

Vamos lembrar que aqui não é Facebook para gerar uma thread de debates desnecessários.

Bom, eu, como alguém que trabalha em um time multicultural, devo dizer que entendo o lado do @cyzainc  quanto a tentar se fazer entender para uma outra cultura, e me sinto um pouco envergonhado de isso realmente ter virado uma discussão de boteco mesmo.

....

Well, I only have 1,5 years of professional experience in web development but more than half of it is with the international market because from the beginning I've decided to work remotely for international companies. Lack of feedback is a reality indeed, but this is a universal issue, once I ran for a position in Germany that was organized by a relevant brazilian company that promised an interview with the contractors that never took place...

I should say that, independently of who did what, I didn't notice any serious issues about what @cyzainc did, besides not knowing how to write in portuguese properly, he even tried to explain himself extensively... But, in my opinion, something even worst was our community extending an issue unnecessarily. 

As it has been already mentioned here, the problem is mostly cultural differences, and to be honest, I don't think that one should place himself so insistently as a victim of a regular thing in the professional world. I think that everyone here should move forward and try to learn something about everything here, each one about his one subject.

Let us remember that this is not Facebook to open such an unnecessary discussion thread.

And finally, as I work in a multicultural team, I should say that I do understand @cyzainc side on the story, which is trying to make a point for another culture, and I do feel a little bit ashamed about this turning into a petty discussion.

**Comment by Moke-RS** [comment]
>Estamos à procura de membros da equipe fortes e confiáveis ​​e não achamos que você se qualificou como tal. 

Esse é o tipo de coisa que não se diz nunca publicamente. A empresa quer dar a sua versão em relação a acusação/alerta do candidato, eu até entendo. Agora dar a sua opinião sobre o candidato publicamente, sobre a pessoa e não o caso, é no meu ponto de vista muito errado.

Sem "caça às bruxas", acho que a empresa Cyza e os responsáveis pela comunicação da empresa devem repensar a forma como se comunicam pelo bem da imagem da empresa. Ao tentar proteger a imagem da empresa acabaram piorando.

**Comment by worldrules** [comment]
Ladies and gentlemen, I have a degree in Human Resource Management, and I am completely ashamed of my profession to see such a situation in another country, it is time to review the concepts and be more human less robot, because the day you need attitudes humans took such an attitude, something horrible.

**Comment by paulopilotti** [comment]
@ThiagoDallacqua 

>  Falta de feedback é sim uma realidade, mas isso é universal

Então seria bom começar a mudar isso não é?

Querem atitudes profissionais, um trabalho que jamais termina e uma ligação com a empresa que dura anos, mas, não são capazes de escrever um email automático dizendo **"Não foi possível dar continuidade com o processo"**?

Acho que não interessa se ocorre em todo mundo, o importante é não fazer isso de novo e mudar essa cultura.

**Comment by bernardodiasc** [comment]
Pra galera que não entendeu direito, um candidato reclamou publicamente do processo de seleção e o recrutador respondeu na defensiva e expôs o candidato de maneira inadequada. Não é o fim do mundo, mas não foi legal não.

> I hope you will learn this sooner than later.

@cyzainc I hope you also learn something, and soon enough, that you are making bad image of yourself and are demonstrating unprofessionalism.

That's my respectful opinion. Considering both sides, for the candidate perspective you demonstrated you're not really open to criticism and acts immature. Therefore I would think twice before select you to be a work partner.

This is not personal, let's try to learn together with se situation. If someone publicly diminish your business or your professionalism, deal with the person in private, resolve the issue, and then get back to the public channel with diplomacy. You are responsible for your company culture and the public image, not anyone else. And understand that candidates also have a reputation to preserve.

You told that you have +60 candidates for the vacancy, remember each one is a person, deal with that. And try not to argue, for your own sake, it will not work. :)

**Comment by gabrielsimas** [comment]
@alinebastos O que eu vejo aqui é mt gente puxando o saco da @cyzainc achando que, com isso, vai angariar alguma facilidade! A nossa profissão tá cheia de "profissionais" assim que estão sempre do lado contrário achando que vão conseguir algum tipo de migalha ou moedinhas sabe? tem medinho de assumir atitudes e responsabilidades e ainda invocam a autoridade do @LFeh como um religioso invocando o poder de uma divindade para queimar os infiéis! Triste! Mas, temos aqui um mini mundo de nossa profissão. Se não admitimos que os RHs do nosso país façam isso conosco, temos que criticar os outros sim, eles estão achando que isso aqui é o quê? Um Jardim Zoológico? uma máquina de Neo Carnival, onde eles colocam fichinhas e nos pegam como bichinhos de pelúcia??? Nós somos os melhores desenvolvedores do mundo e eles sabem disto... deveríamos usar melhor o nosso poder e a nossa competência e você me representa, assim como o @GustavoCostaW. Hoje em dia é dificil mesmo encontrar pessoas que tenham sua própria opinião em qualquer circunstância... note que só nós aqui estamos defendendo a nossa idoneidade e ética. Um colega de profissão nosso foi humilhado publicamente, deveríamos agir como as abelhas, quando uma delas é agredida, mas, a maioria prefere se colocar "em cima do muro" e puxar saco dos gringos sempre amenizando, quando são os outros claro. Sabe por quê? porque não temos a noção de "Povo", "Meu Povo"... já os estrangeiros têm e por isso fazem o que fazem e a gente abaixa a cabeça. Abaixa a cabeça para trabalhar por míseros dólares. Eu tenho 21 anos de experiência na minha profissão e quem chegou agora tem muita coisa pra aprender antes de se meter em uma discussão destas para puxar saco de empresa estrangeira, se bem que fazem isso aqui no Brasil, né? fazer isso para empresa estrangeira é fácil!

**Comment by rgazeredo** [comment]
@gabrielsimas vou explicar bem direitinho para que não tenham dúvidas, o texto que vou escrever abaixo estou falando por mim, e apenas por mim...

Em momento nenhum eu defendi ou puxei saco da @cyzainc, primeiro por que eu não apliquei e nem vou aplicar para essa vaga, ela não faz o meu perfil; segundo como já falei acima, eu já apliquei para outras empresas e não tive feedback, e conversando com alguns amigos que moram fora e trabalham fora, já me comentaram que isso é normal na cultura de algumas empresas (que inclusive tem empresa no Brasil que é assim); então eu defendi o meu ponto de vista com base no meu conhecimento, e não com objetivo de tirar alguma vantagem com isso. Eu respondi e quis defender o meu ponto de vista, pois senti vergonha dos profissionais do meu pais, por estarem entrando nesse tipo de discussão, por uma coisa tão comum (como uma falha de comunicação, que acredito não ter prejudicado ninguém).

Sobre invocar a autoridade do @LFeh não fui em quem fiz isso, mas imagino que quem o fez, não foi no sentido que você está se referindo, eu pelo menos acho que essa discussão toda foi longe demais, e fechar a issue seria uma boa pois o foco desse repositório não é esse.

Sobre a sua experiência profissional, não entendi bem o que ela pode acrescentar nessa discussão... mas eu tenho 13 anos de experiência como profissional, já trabalhei alocado, e remoto para empresas do Brazil e do exterior, não sei se isso conta para alguma coisa, mas em momento nenhum usei isso como argumento para defender as minhas idéias, mas pela sua lógica quem tem mais experiência é o dono da razão.

E para finalizar, eu não tenho nada contra ou a favor a @cyzainc como falei acima só estou defendendo o meu ponto de vista, não tenho nada a ganhar ou perder com a empresa.
Sobre o @GustavoCostaW também não tenho nada contra, pelo contrário tenho a favor, aprendi bastante com os vídeos dele sobre PhoneGap quando comecei a desenvolver para mobile com PhoneGap. Alias @GustavoCostaW parabéns e obrigado por criar o projeto **FastGap** ele me ajudou bastante com performance no meu começo com PhoneGap.

**Comment by ThiagoDallacqua** [comment]
Então @gabrielsimas, não sei qual o seu problema ou se você tem alguma mágoa reprimida para querer rebaixar quem não se doeu com a situação do colega... Eu, como o @rgazeredo não ficamos puxando saco de ninguém e não vejo problema em tentar colocar uma posição neutra, que foi o que eu tentei fazer.

Eu não apliquei pra vaga, pois já estou muito bem posicinado no mercado para o meu nível de experiência e não abaixo a cabeça para ganhar míseros dólares, eu trabalho bastante e para uma empresa que me respeita como pessoa e como funcionário. Não acho justo você sustentar seu argumento com algo tão raso e incorreto como você fez.

Eu não tenho nem metade da sua experiência, mas sei me expressar posicionando o meu argumento com fatos relevantes, como o @rgazeredo, seria ótimo ter um feedback para cada vez que nós mandassemos um currículo ou respondessemos à um teste, mas isso não acontece... E niniguém está errado por dizer o óbvio com o intúito de simplesmente ajudar um colega a aceitar a realidade, essa foi a minha intenção.

E sim @paulopilotti eu concordo contigo cara, mas sinceramente não acredito que isso venha a acontecer tão cedo...

**Comment by carloschneider** [comment]
@LFeh a minha intenção não foi de censurar ninguém ao citar você, mas sim de talvez fechar a issue e mantermos o objetivo do repositório.

> tem medinho de assumir atitudes e responsabilidades e ainda invocam a autoridade do @LFeh como um religioso invocando o poder de uma divindade para queimar os infiéis!

@gabrielsimas cara, qual o seu problema? Você precisa parar de assistir ficção. Faço as palavras do @rgazeredo e do @ThiagoDallacqua as minhas. Não apliquei e nem pretendo aplicar para a vaga.

**Comment by LFeh** [comment]
@carloschneider Tranquilo mano 😊

**Comment by gabrielsimas** [comment]
Aproveitem pra chorar na cama que é lugar quente!

**Comment by LFeh** [comment]
Bom, os argumentos começaram a cessar e daqui pra frente não vejo mais nada de bom.

Meus parabéns para todos que colocaram seus pontos e discutiram de maneira educada ;)
