### ISSUE TITLE
[São Paulo] Desenvolvedor Front-End - AMARO

### ISSUE THREAD

**Issue by cassiocardoso** [frontendbr/vagas#101]
## Descrição da vaga

Estamos em busca de um desenvolvedor front-end (pleno/sênior) para integrar o nosso time. Buscamos alguém que tenha habilidades em todas as áreas do desenvolvimento front-end como: implementar layouts responsivos; criar uma biblioteca de componentes; desenvolver componentes modulares; testar a aplicação, que saiba documentar seu trabalho e esteja disposto a aprender e compartilhar conhecimento com o time.

## Local

Rua Antonio Nagib Ibrahim, Água Branca, São Paulo/SP

## Responsabilidades

- Desenvolver novos componentes que serão integrados à nossa plataforma de e-commerce.
- Escrever CSS de forma escalável, usando a síntaxe do Sass.
- Criar componentes modulares em JavaScript, utilizando ReactJS.
- Colaborar com os times de UX e Marketing para planejar, prototipar e construir novas interfaces.

## Requisitos

**Obrigatórios:**
- Habilidade de criar layouts utilizando ferramentas modernas (Pré-processadores, frameworks JavaScript, automatizadores de tarefas).
- Habilidade para implementar interfaces responsivas criadas pelo time de UX.
- Conhecimento avançado de JavaScript nativo (consumir uma API e renderizar os dados na tela).
- Experiência com controle de versão (Git).
- Saber trabalhar em grupo.

**Desejáveis:**
- Experiência com pré-processadores de CSS (LESS, Sass, Stylus, PostCSS)
- Familiaridade para trabalhar em um ambiente \*nix.
- Familiaridade com a metodologia Scrum e desenvolvimento ágil.

**Diferenciais:**
- Experiência com frameworks JavaScript (AngularJS, Ember.js e/ou React).
- Conhecimento em TDD (Test-driven development).
- Experiência com linguagens de desenvolvimento back-end como PHP, Node.js ou Ruby.
- Inglês avançado.

## Contratação

- CLT (3k a 6k - dependendo da experiência)

### Benefícios

- VR (ou restaurante na empresa)
- VT
- Plano de saúde
- Desconto em produtos AMARO

### Nossos Diferenciais

- Futebol na sexta-feira.
- Lan-party com CS:GO.
- Happy hour com cervejas artesanais.
- Não precisa dar suporte ao IE.

## A AMARO

AMARO é uma marca online de moda feminina com sede em São Paulo. Lançamos coleções mensais com as últimas tendências de moda a preços acessíveis, entregues rapidamente, em grande estilo. Através de tecnologia de ponta, integração vertical e distribuição omni-canal, a AMARO está mudando a forma como os brasileiros consomem moda.

Todos os dias nos desafiamos para encantar nossos clientes com uma variedade de produtos sempre em renovação, com as últimas tendências da moda, a preços acessíveis. Tudo isso, entregue de forma rápida e em grande estilo.

## Como se candidatar

- Acesse nosso [repositório no GitHub](https://github.com/amaroteam/front-end-challenge) e leia as instruções do desafio.
- Resolva o desafio, preste atenção nos requisitos e nos pontos extras.
- Submeta um _pull-request_ e nós avaliaremos seu trabalho.

**Comment by LFeh** [comment]
\o, boa sorte @cassiocardoso

**Comment by cassiocardoso** [comment]
Valeu @LFeh \o/

**Comment by rodrigobacelli** [comment]
@cassiocardoso tem que atualizar os benefícios com "Não damos suporte ao IE"

**Comment by cassiocardoso** [comment]
Isso é um diferencial! hahaha

**Comment by eduardojmatos** [comment]
@cassiocardoso já preencheu a vaga? Nos avise pra mantermos ou removermos da lista :)

**Comment by cassiocardoso** [comment]
Vaga preenchida. @eduardojmatos .

**Comment by eduardojmatos** [comment]
@cassiocardoso valeu man :)

**Comment by camilatigre** [comment]
@cassiocardoso 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by cassiocardoso** [comment]
Oi @camilatigre infelizmente a vaga não foi preenchida através daqui.
