### ISSUE TITLE
[Remoto ou ES] ReactJs + ReactNative Developer na NEX Solutions

### ISSUE THREAD

**Issue by n3xsolutions** [frontendbr/vagas#1010]
## Apresentação
Somos uma empresa especializada em apps inovadores.
Estamos em busca de profissionais que gostam de desafios e com muita vontade de crescer! E nós teremos o maior prazer em proporcionar isto!

## Vaga
Front-End Developer com experiência ReactJS e ReactNative
Contratação PJ ou CLT para trabalho full-time em Vitória - ES.

## Requisitos
- Profundo conhecimento/experiência com ReactJs e ReactNative
- Redux
- Javascript
- ES6
- HTML5, CSS3
- Firebase (Real-time database, Functions etc)

## Desejável
- RESTful APIs
- Testes unitários e automatizados
- GIT
- NodeJs

## Compensação
- Salário compatível
- Programa de crescimento

## Como se candidatar

Enviar email com o curriculum para suporte@n3x.com.br

## Labels

- Presencial
- Pleno
- PJ
- CLT

**Comment by rzorzal** [comment]
Que bom ver o pessoal do ES postando vaga por aqui ;)
