### ISSUE TITLE
[Florianópolis] Front-End Developer na Sábia Experience

### ISSUE THREAD

**Issue by xandyalexandrec** [frontendbr/vagas#1011]
## O que esperamos de você:

- Pró-atividade;
- Background em design;
- Sempre buscar inovar e trazer novas tendências;
- Ter espírito de trabalho em equipe;

## Local

Sapiens Parque
Av. Luiz Boiteux Piazza, 1302 - Canasvieiras, Florianópolis - SC, 88056-000

## Benefícios

- Remuneração competitiva;
- Plano de saúde;
- Vale-Transporte;
- Vale-refeição;

#### Diferenciais

- Dress free;
- Ambiente descontraído;
- Empresa de Inovação;
- A 700m da praia;

## Requisitos

**Obrigatórios:**
- Conhecimentos sólidos de JavaScript;
- Experiência com AngularJS / VueJS;
- HTML5/CSS3;
- SASS/LESS;

**Desejáveis:**
- Competências em UX/UI;
- Experiência com Interfaces customizadas e animações;
- Figma;
- Integração de APIs ao Front-end;
- Testes unitários e automatizados;
- Mercurial (HG);

**Diferenciais:**
- Experiência com Scrum e liderança;

## Contratação

CLT

## Nossa empresa

A Sábia Experience é uma empresa de inovação atuando como EdTech, especializada em educação imersiva usando storytelling e gamificação. além de realidade virtual e aumentada.

## Como se candidatar

Por favor envie um email para alexandre.custodio@sabia.com.br com seu CV anexado - enviar no assunto: [Vaga] Front-end Developer

## Labels

- Alocado
- CLT
- Junior
- Pleno
- Sênior

**Comment by Finacio** [comment]
Não aceitam remoto?

**Comment by xandyalexandrec** [comment]
Somente presencial. Gostamos do calor humano hehe

**Comment by Murillofilho86** [comment]
Fala @xandyalexandrec, é possível se candidatar como Júnior sabendo apenas HTML, CSS e Javascript?
