### ISSUE TITLE
[São Paulo] Full-Stack Engineer na Startup Americana (Confidencial)

### ISSUE THREAD

**Issue by rbcrogerio** [frontendbr/vagas#1016]
[São Paulo] Full-Stack Engineer na Startup Americana (Confidencial)

## Descrição da vaga:

* Experiência de trabalhar em um ambiente de equipe e desenvolver aplicações web/mobile. O candidato ideal deverá resolver desafios de usabilidade, criar componentes reutilizáveis ​​e contribuir para um código estruturado e de alto desempenho. Buscamos um profissional preparado para resolver problemas que surgem com uma empresa que pretende se expandir globalmente. A empresa utiliza muitas tecnologias e métodos de ponta para lidar com sistemas distribuídos.
* Reuniões para manter a equipe em sincronia.
* Mesclando e revisando solicitações.
* Responsável por implantar seu próprio trabalho.
* Pesquisar problemas que surgem diariamente.
* Alternar entre várias tarefas.
* Análise profunda do modelo de negócios / dados.

## Local:

São Paulo - SP

## Benefícios:

- A definir

## Requisitos

**Obrigatórios:**

* Imprescindível que este profissional tenha inglês avançado/fluente.
* Confortável criação e uso de APIs REST baseadas na web.
* Experiência com Ruby on Rails (ou outros frameworks MVC).
* Expertise em React e/ou React-Native.
* Experiência com bancos de dados (MySQL/Postgres)
* Deve estar confortável trabalhando com o Git em ambientes de equipe.
* Familiaridade com o git-flow.
* Experiência com processos automatizados de software - controle de código fonte, CI / CD, documentação.
* Experiência com a AWS (Amazon Web Services).

## Contratação

R$ 13.000,00 a R$ 14.000,00 PJ

## Como se candidatar

Por favor acesse o link https://www.michaelpage.com.br/job-detail/full-stack-engineer/ref/166535?source=search e candidate-se na vaga em questão.

## Labels

- Alocado
- PJ
- Sênior

**Comment by LFeh** [comment]
@rbcrogerio Precisamos do nome da empresa pra ser publicado aqui :)
