### ISSUE TITLE
[Belo Horizonte] Front-End Developer - Meep App

### ISSUE THREAD

**Issue by ianromano** [frontendbr/vagas#102]
## Descrição da vaga

Somos uma startup. Buscamos pessoas inovadoras e empreendedoras. 

Mais informações:

https://www.facebook.com/app.meep

www.meep-app.com
## Local

Rua tentente brito de melo, 427 , Belo Horizonte, MG
## Benefícios
- Plano de Assistência Odontológica
- Plano de Assistência Médica
- Vale Transporte
- Vale Alimentação
## Requisitos

**Obrigatórios:**
- CSS
- HTML
- Javascript

**Desejáveis:**
- Angular.js
- JQuery
- Bootstrap
- REST API's
- SEO
## Contratação

CLT a combinar
## Nossa empresa

https://www.facebook.com/app.meep
www.meep-app.com
## Como se candidatar

Basta se cadastrar pela 3days no link abaixo: 
[Clique aqui!](http://3days.com.br/talents/vaga/Meep-App/Front-end-Developer/S1ChpvPt?utm_source=github_vagasfront&utm_content=vaga_meepappfront)

**Comment by YanMagale** [comment]
Show de mais @ianromano

**Comment by eduardojmatos** [comment]
@ianromano já preencheu a vaga? Nos avise pra mantermos ou removermos da lista :)

**Comment by ianromano** [comment]
@eduardojmatos ainda aberta tb :P

**Comment by eduardojmatos** [comment]
@ianromano ok, boa sorte na busca! :)

**Comment by AllanPinheiroDeLima** [comment]
Enviado
