### ISSUE TITLE
[São Paulo] Front-End Developer na Marmotex

### ISSUE THREAD

**Issue by FernandaAbreu** [frontendbr/vagas#1025]
## Descrição da vaga

O time de desenvolvimento da Marmotex está procurando por desenvolvedores "gente boa", apaixonados por desafios, comprometidos e proativos.
Que tenha paixão pelos nossos principais objetivos que é alimentar, deixar as marmotinhas felizes e uni-las através do almoço no trabalho. Afinal, a #AComidaNosUne.

## Local

Escritório, São Paulo - Vila Olímpia

## Diferenciais

- Ambiente descontraído e informal

- Uma equipe que usa tecnologia de ponta e disruptiva;

- Ambiente de startup;

- Code Review;

- Meetups internos sobre tecnologias usadas na empresa.

## Requisitos

**Obrigatórios:**
- Graduação na área de computação ou experiência equivalente.
- Javascript, HTML e CSS
- SASS ou LESS
- Git
- Desenvolvimento de Layouts responsivos
-  Ter experiência com  SPA (Angular,VueJs ou React)
- Bootstrap
- Recorte de assets
- WebPack

**Desejáveis:**
- VueJs
- firebase
- elasticsearch
- mongoDB
- Desenvolvimento de front-end no android ou IOS

**Diferenciais:**
- projetos opensource

## Contratação

 a combinar

## Como se candidatar

Por favor envie um email para fernanda@marmotex.com seu CV anexado - enviar no assunto: Vaga Front-End

**Comment by igorpinhh** [comment]
Caramba muito boa a vaga!
Me candidataria com força se eu fosse de SP ;-;
