### ISSUE TITLE
[São Paulo/SP] Node.Js Developer na Marmotex 

### ISSUE THREAD

**Issue by FernandaAbreu** [frontendbr/vagas#1026]
## Descrição da vaga

O time de desenvolvimento da Marmotex está procurando por desenvolvedores "gente boa", apaixonados por desafios, comprometidos e proativos.
Que tenha paixão pelos nossos principais objetivos que é alimentar, deixar as marmotinhas felizes e uni-las através do almoço no trabalho. Afinal, a #AComidaNosUne.

## Local

Escritório, São Paulo - Vila Olímpia

## Diferenciais

- Ambiente descontraído e informal

- Uma equipe que usa tecnologia de ponta e disruptiva;

- Ambiente de startup;

- Code Review;

- Meetups internos sobre tecnologias usadas na empresa.

## Requisitos

**Obrigatórios:**
- Graduação na área de computação ou experiência equivalente.
- Node.JS
- VueJs
- Firebase
- Elasticsearch
- MySQL ou postgresql
- MongoDB
- Git
- Redis
- Docker 

**Diferenciais:**
- projetos opensource

## Contratação

 a combinar

## Como se candidatar

Por favor envie um email para fernanda@marmotex.com seu CV anexado - enviar no assunto: Vaga NodeJS

**Comment by Carlosxell** [comment]
Meu, que vaga foda, pena que sou só front-end !!

**Comment by vinyguedess** [comment]
Mandei
