### ISSUE TITLE
[São Paulo] Front-end Developer - Atados

### ISSUE THREAD

**Issue by ianromano** [frontendbr/vagas#103]
## Descrição da vaga

**Possibilidade de Home-office :)**

Tá afim de trabalhar com gente boa e ainda engordar seu github com um projeto opensource? Dá uma olhada então.

Procuramos um dev Front-end apaixonado por tecnologia para compor nossa equipe técnica em um projeto que está se iniciando agora e será finalizado em abril de 2017, com possibilidade de prosseguimento do trabalho após finalização do projeto.

Suas responsabilidades no Atados:
- Analisar, projetar, refatorar, desenvolver e documentar funcionalidades técnicas
- Trabalhar de maneira eficiente em um ambiente ágil e flexível

## Local

R. Teçaindá, 81, São Paulo, SP

## Benefícios

-Horário Flexível

## Requisitos

**Obrigatórios:**
- Experiência com HTML5/JS/CSS3
- Experiência com preprocessadores
- Experiência com versionamento(git ou svn)

**Desejáveis:**
- Experiência com AngularJS e React
- Conhecimentos em BDD ou TDD

**Diferenciais:**
- NodeJS
- Experiência com administração de sistemas
- Experiência com AWS

## Contratação

PJ a combinar

## Nossa empresa

O Atados é uma plataforma social que conecta organizações sociais com voluntários que queiram fazer a diferença. Somos uma ONG localizada no coração de São Paulo e nosso código está no github.

Uma rede social feita para você encontrar as mais diversas oportunidades de voluntariado. Importe-se, ajude, cresça e, de quebra, divirta-se - www.atados.com.br

**Missão**
Criar conexões por meio do voluntariado, visando à ampliação do senso de comunidade e da consciência coletiva, bem como ao desenvolvimento dos diversos projetos e instituições sociais

**Specialties**
Social Good, Volunteering

## Como se candidatar

Basta aplicar pela 3days no link abaixo! ;)
[Clique Aqui!](http://3days.com.br/talents/vaga/Atados/Front-end-Dev/r1TevJnP?utm_source=github_vagasfront&utm_content=vaga_atadosfront)

**Comment by ednilsonamaral** [comment]
@ianromano, já me cadastrei pra essa vaga algumas semanas atrás e não tive feedback ainda. Não consegui visualizar no site o status do meu processo seletivo também.. :confused:

**Comment by ianromano** [comment]
Opa! Fala aí @ednilsonamaral ! Infelizmente ainda não temos a feature de poder disponibilizar o status do processo seletivo na plataforma, por enquanto é bem manual mas buscamos sempre dar o maximo de feedback possível. A vaga ainda está aberta por que nenhum candidato chegou ainda a etapa final. Te passo mais detalhes por privado :)

**Comment by marcelinhov2** [comment]
Já preencheu a vaga?

Abraços

**Comment by ianromano** [comment]
Boa Tarde Marcelo! Essa acabou de ser preenchida hoje mesmo :/

2016-08-31 16:38 GMT-03:00 Marcelo Eduardo de Andrade Jr. <
notifications@github.com>:

**Comment by camilatigre** [comment]
@ianromano 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
