### ISSUE TITLE
[JOINVILLE-SC] Front-End Developer na A2C agência

### ISSUE THREAD

**Issue by xandess** [frontendbr/vagas#1030]
Candidate-se: https://agenciaa2c.recruiterbox.com/jobs/fk016wb
Procura-se desenvolvedor Front End gênio humilde ;) Se você dá valor a qualidade das suas entregas, nós temos espaço pra você aqui.
 
# REQUISITOS
Conhecimento avançado em Javascript, HTML 5 e CSS 3;
Conhecer bem Bootstrap (últimas versões);
Ter experiência em desenvolvimento em pelo menos três tecnologias Javascript como: NodeJS, TypeScript, React, Redux, Angular, Ember, Backbone, Vue?, etc;
Conhecimento em ferramentas de automação e gerência de pacotes (Grunt, Gulp entre outras);
Possuir noções básicas de desenvolvimento Back End;
Experiência com design responsivo;
Básico de Adobe Photoshop;
Conhecimento em padrões de projeto;
Cursado Ciência da Computação, Sistemas de Informação, Engenharia de Software ou cursos relacionados;
 

# DIFERENCIAIS
Inglês intermediário.
Forte experiência em Node.js e JQuery são diferenciais;
Boas práticas de SEO;
Experiência em desenvolvimento de API RESTful.

# BENEFÍCIOS 
Plano de saúde e odontológico
Auxílio alimentação e transporte
Remuneração compatível com mercado
Apoio em eventos nacionais e internacionais
Apoio em cursos e pós-graduações
Bolsa para estudo de idiomas
Possibilidade de empreender dentro da própria agência
Convênio com Sesc
Seguro de vida
Chopp no fim no mês :D

Candidate-se: https://agenciaa2c.recruiterbox.com/jobs/fk016wb

**Comment by willianjusten** [comment]
Opa @xandess , seria alocado? Caso sim, onde seria? E o nível do profissional, qual seria?

**Comment by xandess** [comment]
Opa.
Sim seria alocado em Joinville-SC, com possibilidade de trabalho remoto 2x
por semana.
Nivel Pleno para Senior :)

2018-05-11 17:34 GMT-03:00 Willian Justen <notifications@github.com>:

**Comment by harrysbaraini** [comment]
CLT ou aceita PJ?

**Comment by harrysbaraini** [comment]
@xandess Como conversamos? Fiz o processo via site da A2C.

Meu e-mail é hello@vanderleis.me
