### ISSUE TITLE
[Rio de Janeiro - RJ] Front-End Developer na TVManager

### ISSUE THREAD

**Issue by danielcozer** [frontendbr/vagas#1033]
## Descrição da vaga

Somos uma Startup especializada em inovações em mídia, desenhadas para atender o mercado televisivo e produtores de conteúdo audiovisual. Não importa sua formação, o que importa é o talento e a vontade de fazer parte de um time para desenvolver uma plataforma extremamente inovadora para o mercado !

Perfil desejado: Alocado ou modelo híbrido - Junior / Pleno 

## Local

Rio de Janeiro, Centro da cidade

## Benefícios

• Horário de trabalho flexível 
• Um ambiente de trabalho diferente e inovador, com uma cultura que valoriza as pessoas e a entrega de resultados 
• Hierarquia horizontalizada 
• No dress code

## Requisitos

**Obrigatórios:**

• Experiência com arquitetura Front-end, usabilidade, desempenho e testabilidade 
• capacidade de traduzir layers em código 
• Fluência em Javascript 
• Fluência em HTML/CSS
• Experiência com AngularJs; Express 
• Experiência de controle de versão de código-fonte (Git)
• Conhecimento de Design e UX 
• Ajudar a construir o software ao em vez de apenas codar requisitos! participar ativamente da concepção e construção da TVManager

**Desejáveis:**

• Experiência NodeJS
• Experiência com Sistemas Web / SaaS
• Experiência em Metodologias ágeis
• Razoável conhecimento de BackEnd (para melhor iteração entre as partes)
• Testes Unitários

**Diferenciais:**

• Familiaridade com Sails framework
• Familiaridade com integração continua;

## Contratação

A combinar

## Nossa empresa

• Maiores informações em: www.TVeStore.com 
• Vídeo explicativo da Solução: https://player.vimeo.com/video/250085951

## Como se candidatar

Por favor envie um email para **daniel@tvestore.com** com o seguinte título e informações:

• Assunto [VAGA] Desenvolvedor Front-end 
• Currículo ou Linkedin
• Github e/ou Blog - Vai nos ajudar a conhecer você e seu trabalho melhor :)

## Labels

- Alocado
- Remoto - Parcial
- Júnior
- Pleno
- JavaScript
- Angular

**Comment by medger** [comment]
Tem vaga pra estágio?

**Comment by danielcozer** [comment]
Tem sim Medina

**Comment by vititu** [comment]
Somente usam Angular? Nada de React?

**Comment by danielcozer** [comment]
Isso, apenas Angular

**Comment by aantunes89** [comment]
Ola, tem vaga para estágio?

**Comment by thiagocruzrj** [comment]
Vaga de Jr. ainda disponível ?

**Comment by danielcozer** [comment]
Está sim ! Vaga disponível
