### ISSUE TITLE
[São Paulo/SP] Front-end developer na Blu365

### ISSUE THREAD

**Issue by raphaguasta** [frontendbr/vagas#1034]
## Descrição da vaga

Estamos à procura de alunos e ex-alunos em início de carreira com grande entusiasmo, vontade de aprender e crescer profissionalmente para participar junto ao time de desenvolvimento front-end e UI/UX, construindo aplicações web Client-Side (SPA), SDKs em JS, aplicações server-side, Testes A/B entre outros.

2 vagas:
- Estágio ou Desenvolvedor Júnior
- Freela Front-end

## Modelo de trabalho
Trabalhamos com o modelo de Sponsorship onde um desenvolvedor sênior padrinho é designado como padrinho de cada aprovado ficando responsável pelo seu treinamento e crescimento profissional. A cada dois meses é feita uma troca de padrinhos para que o candidato possa ser treinado por todos os profissionais do time de dev.

## Local

Vila Olimpia - À um quarteirão da estação Vila Olímpia

#### Diferenciais

- Refeitório com microondas e geladeira
- Pebolim (ou tótó)
- Violão disponível
- Área de lazer/descanso com sofá confortável

## Requisitos

**Obrigatórios:**
- Cursando ensino superior na área de ti (mínimo 3º semestre).
- Conhecimento em alguma dessas linguagens de programação: Javascript, Typescript , php/wordpress.
- Conhecimento em Linux.
- Lógica de programação e OO

## Contratação

A combinar

## Nossa empresa

Site: [Blu365.com.br](https://blu365.com.br)

Somos a BLU365, uma empresa criada em 2014 com o nome de Kitado. Oferecemos soluções que irão ajudar você, sua família e milhões de brasileiros a se manterem no azul nos 365 dias do ano :)

## Como se candidatar

Por favor envie um email para curriculos@blu365.com.br com seu CV anexado - enviar no assunto: Vaga Front-End

## Labels

- Alocado
- CLT
- Estágio
- Freela
- Júnior
- PJ

**Comment by OTTOSG** [comment]
Enviado. ☺

**Comment by manzolirch** [comment]
Vaga somente para quem está cursando a faculdade?

**Comment by GiovanniSM20** [comment]
@manzolirch Ele não especificou o tipo de aluno...hahaha

**Comment by raphaguasta** [comment]
@manzolirch @GiovanniSM20 Pessoal, vamos avaliar todos os cvs, podem enviar :D

**Comment by jsouza23** [comment]
Enviado!

**Comment by danieladuarteng** [comment]
enviado

**Comment by brunooomelo** [comment]
ainda estão aceitando?

**Comment by raphaguasta** [comment]
@brunooomelo Pode mandar!

**Comment by mbrandaocaio** [comment]
enviado.

**Comment by raphaguasta** [comment]
Pessoal, preenchemos essa vaga!

Iremos abrir mais uma vaga de Front-End, e todos podem se candidatar novamente se desejarem. :)

Muito obrigado à todos que se candidataram!
