### ISSUE TITLE
[São Paulo] Front-End Developer na F.biz

### ISSUE THREAD

**Issue by mcarneiro** [frontendbr/vagas#1038]
## Descrição da vaga

Procuramos Front-end Sênior e Pleno apaixonados por pesquisa, tecnologia e design. Que enxerguem o valor dos detalhes, independente do projeto.

Formamos um time multi-disciplinar composto por UX, Front e Back-end que acreditam no melhor que cada tecnologia tem a oferecer. Não só viabilizamos como buscamos ter papel ativo e decisivo na concepção criativa dos projetos.

**Como diferenciamos o Pleno do Sênior?** 

**Pleno:** É independente e tem capacidade de dividir e priorizar suas próprias tarefas. Tem conhecimento técnico suficiente para tocar todas as etapas de um projeto pequeno sozinho (ex.: landing pages, sites institucionais focados em conteúdo). Maturidade para priorizar, reportar problemas e pedir ajuda quando necessário.

**Sênior:** Conhecimento técnico avançado, solucionador de problemas, com capacidade liderar um projeto médio ou grande com outros perfis do time (ex.: e-commerce, grandes portais, sites experimentais, etc.). Maturidade para dar suporte, estimar e garantir a qualidade de entrega do trabalho dos pares.

Além dos conhecimentos técnicos e trabalhos, queremos saber *quem* é você pois acreditamos que cada nova pessoa adiciona algo único ao time.

Se você acha que tem o perfil para a vaga, venha tomar um café com a gente!

## Local

R. João Moura, 1144 - Pinheiros

## Benefícios

- Plano de saúde e odontológico
- Seguro de vida
- VR de R$ 31/dia
- Auxílio babá/creche
- Gympass

#### Diferenciais

- Colaborador escolhe entre PC ou MAC
- Flexibilidade com horário e trabalho remoto
- Ambiente amigável e qualidade de vida
- Festinha com comes e bebes bimestral 🍻
- Aquele prédio bonitão perto do metrô Sumaré

## Requisitos

**Obrigatórios:**

- HTML5;
- CSS box-modeling sem uso de frameworks (float, flex, display, grid, etc.);
- Pré-processadores de CSS (SASS, Stylus, PostCSS, etc.);
- JS (Vanilla e jQuery, Eventos, Ajax, etc.);
- Conhecimento íntimo entre os browsers;
- Construção de páginas responsivas;
- Detalhe para acabamento (alinhamentos, animações, etc.);
- GIT;
- Grunt, Gulp, NPM scripts, etc.
- Inglês (escrita e conversação);

**Desejáveis:**

- Debug;
- Command-line;

**Diferenciais:**
 
- Criatividade e colaboração;
- Técnicas de animação interativa via JS;
- Automação de processos;
- Diferentes paradigmas de programação (OOP, functional, event driven, etc.);
- Projetos pessoais.

## Contratação

CLT

## Nossa empresa

A F.biz é uma agência com mais de 18 anos e DNA 100% digital. Trabalhamos com grandes clientes como Unilever, Jeep, Honda, Tok&Stok, Votorantim, Rico, entre outras. Todas as contratações são CLT com benefícios de transporte, alimentação, refeição e um belo plano de saúde com cobertura odontológica. Temos plano de carreira de longo prazo e trabalhamos com processos flexíveis que nos ajudam a organizar o dia-a-dia com mais eficiência e colaboração.

## Como se candidatar

[Preencha este formulário e aguarde nosso contato.](https://fbiz.recruiterbox.com/jobs/fk01j1a?cjb_hash=O_cxCs84&apply_now=true)

## Labels

- Alocado
- CLT
- Pleno
- Sênior

**Comment by matheus-rosin** [comment]
@mcarneiro tem possibilidade de remoto 100%, outra cidade?

**Comment by mcarneiro** [comment]
Oi @matheus-rosin, a F.biz não tem política para trabalho remoto ainda em outras cidades, sorry :(

**Comment by matheus-rosin** [comment]
Tranquilo, valeu ;)

**Comment by mcarneiro** [comment]
Pessoa, fechei a vaga. Estamos nos finalmentes aqui. Se o contratado tiver vindo por aqui dou um toque.

**Comment by LFeh** [comment]
Maravilha @mcarneiro!
