### ISSUE TITLE
[Rio de Janeiro] Front-End Developer na FGV DAPP

### ISSUE THREAD

**Issue by cpmarx** [frontendbr/vagas#1039]
## Descrição da vaga

Atuar em projetos e manutenção de web sites desenvolvidos em HTML, CSS e Javascript. Eventualmente irá dar manutenção em WordPress. Se manjar um pouquinho de Python vai se dar bem :)

## Local

Remoto ou Escritório, Rio de Janeiro - Botafogo

## Benefícios

Se CLT:
- Plano de saúde
- Plano dentário
- Seguro de vida
- Alimentação em restaurante próprio da FGV
- Auxílio creche
- mais um monte de coisas que eu nem lembro...

#### Diferenciais

- Ambiente dinâmico e interdisciplinar, ideal pra quem quer se desenvolver.

## Requisitos

**Obrigatórios:**
- Manjar de CSS e Javascript mesmo, utilizando o máximo dos recursos como transições animadas, paralax, etc. Desenvolver interfaces ricas como http://dapp.fgv.br/seguranca-e-cidadania/datacrime/#crimes ou http://dapp.fgv.br/politica-na-rede/monitor/

**Diferenciais:**
- PHP / Python 🥇 
- Linux

## Contratação

a combinar: PJ ou CLT

## Nossa empresa

A DAPP produz análises de políticas públicas com uma equipe interdisciplinar e diversificada, de sólida formação em áreas como Sociologia, Ciência Política, Antropologia, Linguística, Economia, Administração Pública, Relações Internacionais, Estatística, Matemática, Filosofia e Comunicação Social, aliadas às áreas de Tecnologia da Informação e Design.

Desenvolvemos pesquisa social aplicada com o objetivo de promover a inovação para políticas públicas,
produzindo análises qualificadas e disponibilizando diversas ferramentas de visualização e análise de dados. Nossas metodologias de pesquisa reúnem métodos quantitativos e qualitativos em integração com a análise de redes sociais e interface com áreas de tecnologia e design.

## Como se candidatar

Por favor envie um email para cleiton.marques@fgv.br com seu CV anexado e/ou portfólio - enviar no assunto: Vaga Front-End

## Labels

- Alocado
- CLT
- Freela
- PJ
- Pleno
- Remoto - Parcial
- Sênior

**Comment by cotts** [comment]
Remoto somente parcial?

**Comment by medger** [comment]
Existe alguma vaga pra estágio?

**Comment by cpmarx** [comment]
Olá @medger neste momento ainda não, porque estou com algumas demandas mais urgentes, mas me encaminhe mesmo assim seu CV com o que você tem estudado pra eu considerá-lo em outra oportunidade blz?
Vlw

**Comment by cpmarx** [comment]
Pessoal, recebi vários CVs, obrigado. Estou separando alguns a medida que os job$ forem sendo liberados. Valeu galera!
