### ISSUE TITLE
[Ribeirão Preto-SP] Front-end Developer - Crave Food Services

### ISSUE THREAD

**Issue by ianromano** [frontendbr/vagas#104]
## Descrição da vaga

Are you able to understand backend developers and UX designers? Can you put their work together to make beautiful and useful applications? Then you should apply to work with us at Crave Food Services! Independently of the position we expect that everyone involved in the development process be interested in the whole stack and product – there is no part of the system that is somebody's else problem.

Crave Food Services is an innovation & technology company specialized in generating efficiency in the food service industry. Our product WhatsGood is an online marketplace that connects chefs and local food purveyors.

We currently have an office in Providence (RI – USA) and we are just opening a new office in Ribeirão Preto (SP – Brazil). This position is a local position for the Ribeirão Preto office.
## Local

R. Visc. de Inhaúma, 2111, Ribeirão Preto, SP
## Benefícios
- 20 days off per year (that's more than 30 days of vacations!)
- Subvented devices (we help you buy a new laptop by paying part of it)
- Incentives to attend conferences
- Performance based bonuses
- Relocation package
- Work on open source projects!
## Requisitos
- At Crave we use React, Redux, Webpack and other great tools available in JS world!
- Some skills we would like to see in our candidates:
- Passion for technology and high quality engineering
- Have worked with one of these frameworks before (AngularJS, BackboneJS, etc...)
- Good understanding of git
- Be able to build custom UI and animation
- Deal with cross browser compatibility
- Ability to multi-task and work under pressure
- Know about how DOM works and the good practices to work on it.
- Be able to build an app without left-pad
- Experience with working remotely
- Know about coding/designing strategies and methods (TDD, SOLID, Clean Code, etc)
- Strong skills on Unix/Linux environment
- Familiar with agile principles
- Know about automated building, deployment and testing (karma, mocha, sinon, chai, and the list goes on)
- Love JS <3!!

**Obrigatórios:**
- CSS
- HTML
- Javascript
- React.JS
## Contratação

PJ - faixa salarial - R$ 4.500,00 à R$ 9.000,00 
## Nossa empresa

We are a team of talented food service professionals with well over 100 years of combined experience as chefs, restaurateurs, farmers, and managers in the Greater New England Food System. Through collaborative, innovative, and hands-on leadership, our focus is to help build sustainable food ecosystems which help producers and procurement managers to streamline their operations, while deploying efficient technology, technique, and operational standards. Our expertise, industry insight, and cohesive team have the right ingredients necessary to elevate any food service operation’s sustainability and creative and practical development.

Our team pairs well with technology and has successfully designed software which enables food industry organizations to become truly sustainable far beyond our consultation. WHATSGOOD is an online local food marketplace which connects wholesale food purchasers, directly with local and regional producers. Our product design and development focuses on creating simple, reliable, easy-to-use utilitarian tools for chefs, food purveyors, food distributors, food vendors, restaurateurs, managers, purchasers, farmers, fishermen, and food sales representatives.

**Specialties**
Mobile, Restaurants, Food and Beverages, Food Distribution, Food Sourcing, Food Purchasing, Farm To Table, Food Sustainability, Local Ingredients, Culinary Arts, Food Service Industry, Design, Efficiency, Innovation, Food System, Sustainability, Technology, Consulting
## Como se candidatar

You can Apply through 3days ;) just click below!
[Click Here](http://3days.com.br/talents/vaga/Crave-Food-Services/Front-End-Developer/HytCKV-v?utm_source=github_vagasfront&utm_content=vaga_cravefront)

**Comment by LFeh** [comment]
Good luck ;)

**Comment by LFeh** [comment]
Hey @bernarddeluna :)

**Comment by bernarddeluna** [comment]
It's a great opportunity to join and work with a great technical team :)

é uma grande oportunidade de se juntar e trabalhar com um grande time tecnicamente :)

**Comment by eduardojmatos** [comment]
Opa @ianromano já preencheu a vaga? Nos avise pra mantermos ou removermos da lista :)

**Comment by ianromano** [comment]
@eduardojmatos ainda aberta :)

**Comment by eduardojmatos** [comment]
@ianromano blzera!
