### ISSUE TITLE
[Curitiba e Região] Front-End Developer na LojasKD

### ISSUE THREAD

**Issue by marcelabomfim** [frontendbr/vagas#1040]
## Descrição da vaga

Estamos buscando uma pessoa para atuar com Desenvolvimento Front End que curta Tecnologia, Interface e Usabilidade, que esteja antenada com as novidades, que tenha atenção à detalhes, que tenha iniciativa de buscar melhorias e soluções, que tenha disposição para projetos e metodologias ágeis.

## Local

Presencial, Pinhais - Região Metropolitana de Curitiba

## Benefícios

- Vale Refeição
- Vale Combustível/Transporte
- Bonificação mensal
- Plano de saúde com coparticipação
- Ambiente diferenciado (Você vai curtir!)
- Descontos em universidades, farmácias e outros

#### Diferenciais

- monte a sua máquina como desejar
- frutas à vontade, biscoito (ou bolacha, escolha vc) e café sempre fresquinho :P

## Requisitos

**Obrigatórios:**
- HTML5, CSS3, Javascript/jQuery;
- Pré-processador SASS;
- Automatização de tarefas com Gulp;
- Git;
- Integração com APIs;
- Atenção aos detalhes de interface e usabilidade;

**Diferenciais:**
- React;
- Webpack;
- Noção de PHP;

## Contratação

CLT

## Nossa empresa

A LojasKD é um dos principais E-Commerces de móveis do país. Uma enorme variedade de produtos inspiradas para decorar cada momento da vida do cliente. Fundada em 1997, começou com lojas físicas, mas hoje está 100% online. Somos apaixonados pelo que fazemos! Cada vez mais querendo se posicionar como uma empresa de tecnologia.

## Como se candidatar

Aplique para a vaga no link: https://lojaskd.recruiterbox.com/jobs/fk01j3v
Tip: seria legal ter o link do seu LinkedIn e Github/BitBucket também (:

## Labels

- Alocado
- CLT
- Júnior

**Comment by Murillofilho86** [comment]
Interessante essa vaga, oportunidade para pessoas de outros estados?

**Comment by marcelabomfim** [comment]
@Murillofilho86 opa tem sim, eu mesma vim do RJ direto pra cá há pouco mais de um ano, o processo de seleção foi todo online, testes, entrevistas, etc.. 
Aó foi só marcar a data de início e comprar a passagem :smile:

**Comment by Murillofilho86** [comment]
Obrigado @marcelabomfim! Era exatamente o que eu queria saber, pois também sou do rio e estou buscando algo em outros estados.
