### ISSUE TITLE
[São Paulo/SP] Front-End Developer Vue.js na NOALVO

### ISSUE THREAD

**Issue by ggondim** [frontendbr/vagas#1046]
![imagem](https://noalvo.blob.core.windows.net/outros/Vaga-FrontEnd-01.png)

Se você programa JavaScript e tá #boladão ou #chatiada com seu trampo atual, você COM CERTEZA quer trabalhar na NOALVO.

## Descrição da vaga
Desenvolvedor(a) front-end com experiência JavaScript para desenvolvimento de plataforma web com Vue.js.

## COMO SE CANDIDATAR
Acesse esse link: http://jobs.midianoalvo.com.br/vue-ghg-frontendbr

## Local
Av. Paulista, São Paulo, SP.

## Conhecimentos obrigatórios
- HTML5, CSS3 e Javascript (ES2015+)
- Vue.js e vuex
- Webpack
- Git
- Bootstrap 3

## Diferenciais
- LESS ou Sass
- AngularJS
- TypeScript
- Mocha
- Chai
- Babel

## Proposta
PJ (valor a combinar)
Full-time
In-loco

## Sobre a NOALVO
- Somos uma startup de mídia off-line com pouco mais de um ano de vida.
- Fomos acelerados pela ACE, melhor aceleradora de startups da América Latina e já recebemos dois grandes aportes de investimento.
- Temos 15 pessoas no nosso escritório aqui na Av. Paulista, dentro do coworking do ACE Campus, junto a dezenas de outras startups
- É um ambiente onde você respira conhecimento e inovação.

## NÃO ESTÁ CONVENCIDO AINDA?
- Conheça mais sobre nós no nosso BLOG DE ENGENHARIA em http://engenharia.midianoalvo.com.br
- Conheça mais sobre nossa STACK DE DESENVOLVIMENTO em http://stackshare.io/noalvo/noalvo
- Conheça nossos PROJETOS OPEN SOURCE em https://github.com/noalvo

**Comment by Carlosxell** [comment]
Vaga apenas PJ ?
