### ISSUE TITLE
[Governador Valadares-MG] Front-end Developer - Apiki

### ISSUE THREAD

**Issue by ianromano** [frontendbr/vagas#105]
## Descrição da vaga

A Apiki busca um Dev Front-End, para uma vaga CLT presencial, em Governador Valadares - MG.

Se você curte um ambiente descontraído com sinuca e cervejeira, além de 12 garrafas de café por dia, esse lugar é para você!
## Local

Praça Doutor João Paulo Pinheiro, 100, Governador Valadares, MG
## Benefícios
- Horário Flexível
- Plano de Assistência Médica
- Vale Transporte
## Requisitos

**Obrigatórios:**
- CSS
- HTML
- Javascript
## Contratação

CLT a combinar
## Nossa empresa

Temos sinuca e cervejeira na empresa. Fazemos incríveis 12 garrafas de café passado por dia. Temos um App para o pedido do pão da tarde desenvolvido pelo próprio time. Estamos concluindo a conquista de todo Brasil e partindo para o mercado internacional.
## Como se candidatar

Basta aplicar pela 3days no link abaixo ;) 
[Clique Aqui!](http://3days.com.br/talents/vaga/Apiki/Front-End-Developer/4y9mHt7Rx?utm_source=github_vagasfront&utm_content=vaga_apikifront)

**Comment by LFeh** [comment]
Pleno?

**Comment by ianromano** [comment]
@LFeh isso mesmo! obg!

**Comment by klarkc** [comment]
@ianromano tentei aplicar pelo 3days mas deu algum problema e n consegui, agora apareceu "você já aplicou para esta vaga", não sei se foi, vc pode verificar pra mim? Obrigado!

**Comment by eduardojmatos** [comment]
@ianromano cara, já preencheu essa vaga tbm? Nos avise pra mantermos ou removermos da lista :)

**Comment by ianromano** [comment]
@eduardojmatos ainda está aberta :)

**Comment by eduardojmatos** [comment]
@ianromano ok! :)
