### ISSUE TITLE
[Remoto] Front-End Developer na Ignus Digital

### ISSUE THREAD

**Issue by lunks** [frontendbr/vagas#1051]
## Descrição da vaga
Venha fazer parte do time de desenvolvimento da Ignus, uma empresa do grupo HE:labs. Nossa missão é promover inovação através de métodos, ferramentas e tecnologia em grandes empresas no Brasil e no mundo. Durante 7 anos de mercado trabalhamos em projetos de produtos digitais com empresas como Citrix, ESPN, Sony Music, GE, UOL.

## Local
Remoto com viagens eventuais.

## Benefícios
- Variam conforme regime de contratação

#### Diferenciais

- Trabalho remoto
- Ambiente que respeita a diversidade
- Retro quinzenal da empresa toda com divulgação de resultados, espaço para discutir assuntos, etc.
- Trabalho remoto, mas com uma proximidade maior que boa parte dos trabalhos presenciais

## Requisitos

**Obrigatórios:**
- Experiência *sólida* em React e componentização
- HTML/CSS
- Git
- Experiência com testes automatizados
- Conceitos básicos de FP como High-Order Functions, Currying e Closure
- Possuir comunicação fluida e objetiva, embasada em dados para dialogar com os clientes durante os projetos.
- Poder ler e escrever em inglês

**Desejáveis:**
- Webpack
- Node.JS
- Experiência com Apollo e GraphQL
- React Native
- Estar confortável para participar ativamente de reuniões em inglês.
- Experiência com métodos ágeis

**Diferenciais:**
- Colaboração na comunidade (seja blog, open source, etc.)

## Contratação

CLT ou PJ, a combinar

## Nossa empresa

Somos a vertical da HE:labs com foco na transformação digital para grandes empresas. Há 7 anos entregando resultados significativos para o negócio de todo o mundo.

Nosso escritório no Rio de Janeiro está pronto para receber nossos igniters, mas temos o suporte de ferramentas como Slack, Google Hangouts e demais de videoconferência para nos manter sempre conectados. Acreditamos que uma boa comunicação só depende de métodos, meios e disposição. 

Reuniões de planejamento do cliente com o time e retrospectivas dos projetos garantem o constante alinhamento do produto com toda a Ignus. 

## Como se candidatar

[Aplique aqui](https://ignusdigital.recruitee.com/o/javascript-developer)

## Labels

- Alocado
- CLT
- PJ
- Pleno
- Remoto - Total
- Sênior

**Comment by lffranca** [comment]
Aplicado

**Comment by thismarcoantonio** [comment]
@lunks a vaga ainda está aberta?

**Comment by oguhpereira** [comment]
Aplicado

**Comment by thismarcoantonio** [comment]
Acabei de aplicar!
