### ISSUE TITLE
[REMOTO] - Desenvolvedor Frontend Pleno na [Upnid]

### ISSUE THREAD

**Issue by lucasupnid** [frontendbr/vagas#1053]
## Descrição da vaga

Você será responsável por desenvolver os recursos mais complexos dos projetos. Para isso é necessário ter um altíssimo conhecimento em padrões de desenvolvimento e qualidade de código

## Local

Remoto ou Escritório em São Paulo

#### Diferenciais

- Bonificação extra para alto desempenho 
- Incentivo a educação (cursos, livros, eventos, etc)
- Trabalho Remoto
- Horários flexíveis (você define a sua rotina)

## Requisitos

**Obrigatórios:**
- Experiência comprovada em React.
- Conhecimento em Javascript, HTML, CSS
- Foco em qualidade de código
- Ter conhecimento em Node.JS

**Você vai se encaixar se:**

- For uma pessoa disciplinada e comprometida.
- Você  gosta de sempre ser desafiado a aprender mais.
- Você abraça novos desafios e questiona o status quo
- Aprende rápido e se adapta facilmente a mudanças
- Você se dedica a criar um produto incrível em padrões internacionais
- Busca ter uma visão macro do projeto

## Contratação

PJ/CLT

## Nossa empresa

Somos um marketplace para venda de produtos físicos e digitais. Estamos a dois anos no mercado crescendo a cada mês. Temos Executivos de grandes empresas do ecommerce brasileiro como sócios
**Nosso site**: https://conheca.upnid.com/
**Nosso Facebook**:www.facebook.com/upnid

## Como se candidatar

Por favor enviar um email para lucas@upnid.com com seu CV anexado e um link para seu perfil no GitHub com assunto: Vaga Desenvolvedor Pleno - Frontend

## Labels

- Remoto
- CLT/PJ
- Pleno

**Comment by costaleonardo** [comment]
Aplicado :)

**Comment by vinyguedess** [comment]
Aplicado

**Comment by GiovanniSM20** [comment]
Mesmo eu não me candidatando a vaga, o que seria "Experiência comprovada em React." ? Tipo, como eu comprovaria isso ? Um curso, um repositório, talvez um desafio...?

**Comment by lffranca** [comment]
Aplicado
