### ISSUE TITLE
[Faria Lima- São Paulo] Front End Developer Sênior na BRQ Digital Solutions

### ISSUE THREAD

**Issue by ReAnne123** [frontendbr/vagas#1054]
São Paulo- Front End Developer Sr na BRQ Digital Solutions

Descrição da vaga
Grande banco localizado na Faria Lima busca profissional para atuar em projetos com Angular 2 ou superior.

Local
Vagas presenciais no cliente, localizado na Faria Lima- bairro Itaim Bibi- São Paulo.

Benefícios
VR
Vale alimentação
Assistência médica
Assistência odontológica
Seguro de vida
Previdência privada

## Requisitos

**Obrigatórios:**
HTML, CSS, Angular 2 ou superior.

**Desejáveis:**
-preprocessadores, como SASS, GULP.
– Experiência com npm e gerenciamento de dependências;
– Experiência com Continuos delivery;
– Experiência com Scrum;
– Experiência com git e flows como git flow/gitlab flow;
– Visões de web como arquitetura, componentização e soluções para alta performance;

##Contratação
Contratação CLT Full.

##Nossa empresa
Fundada em 1993, a BRQ é uma das maiores empresas de serviços de TI do país. Conta com 3000 profissionais distribuídos nas filiais de São Paulo, Alphaville, Rio de Janeiro, Curitiba, Recife, Salvador, Brasília, Natal e Nova Iorque. 

## Como se candidatar

Por favor envie um e-mail para ryokota@brq.com com seu CV anexado - enviar no assunto: Vaga Angular2

## Labels
- Alocado
- CLT
- Sênior

**Comment by eduardojmatos** [comment]
Olá @ReAnne123, você precisa colocar o nome da empresa pra que essa vaga seja postada aqui. Essa é uma regra que está descrita lá no nosso [README](https://github.com/frontendbr/vagas/blob/master/README.md)

Além disso, precisa seguir nosso template de issue. Dessa forma fica confuso pra galera que já está acostumada com nosso modelo de issue.

Pra checar como é o modelo, basta abrir uma issue e copiar o template, substituindo pelas suas informações. Não precisa criar uma issue nova, pode editar essa mesmo.

**Comment by ReAnne123** [comment]
Obrigada pela orientação @eduardojmatos

**Comment by ReAnne123** [comment]
@diogomoretti , eu editei a vaga alguns dias atrás e permanece como Pendente de Informações, pode me ajudar? Estamos com essa vaga urgente aqui na BRQ...

**Comment by diogomoretti** [comment]
feito @ReAnne123
