### ISSUE TITLE
[São Paulo - Pinheiros] Desenvolvedor Front-end Sênior

### ISSUE THREAD

**Issue by valentinetwork** [frontendbr/vagas#106]
**## Descrição da vaga**

Vaga de Desenvolvedor Front-end Sênior, para atuar em nosso cliente, uma empresa especializada na segmentação de audiência online.

**## Local**

Escritório em São Paulo - Pinheiros

**## Benefícios**
- Seguro saúde Omint;
- Vale Refeição de R$ 20,00 por dia;
- Estacionamento no local ou vale transporte;
- Horário flexível.

**## Requisitos**

**Obrigatórios:**
- Curso superior completo em Ciência da Computação, Engenharia de Software, Sistema da Informação ou áreas correlatas.
- 5 anos de experiência em HTML, CSS, Javascript e aplicações Web.
- Experiência com Angular JS, Grunt, Bower, Sass.

**Desejáveis:**
- Experiência na utilização de APIs;
- conhecimentos em UX.

**## Contratação**

CLT a combinar.

**## Nossa empresa**

A Valenti Network Computing é uma consultoria de informática fundada em 1997, com foco no recrutamento e alocação de profissionais e também no desenvolvimento de projetos específicos na área de Tecnologia da Informação.

**## Como se candidatar**

Por favor, envie um email para **selecao@valenti.com.br**, com seu CV anexado e com pretensão salarial - enviar no assunto: Vaga front-end

**Comment by eduardojmatos** [comment]
@valentinetwork olá! Já preencheu a vaga? Nos avise pra mantermos ou removermos da lista :)

**Comment by valentinetwork** [comment]
Olá!

 

A vaga ainda está em aberto.

 

Obrigada.

 

assinatura

 

De: Eduardo Matos [mailto:notifications@github.com] 
Enviada em: segunda-feira, 3 de outubro de 2016 23:32
Para: frontendbr/vagas
Cc: valentinetwork; Mention
Assunto: Re: [frontendbr/vagas] [São Paulo - Pinheiros] Desenvolvedor Front-end Sênior (#106)

 

@valentinetwork <https://github.com/valentinetwork>  olá! Já preencheu a vaga? Nos avise pra mantermos ou removermos da lista :)

**Comment by eduardojmatos** [comment]
@valentinetwork ok!
