### ISSUE TITLE
[Rio de Janeiro] Front-End Developer na Beep Saúde

### ISSUE THREAD

**Issue by gutomcosta** [frontendbr/vagas#1061]
## Descrição da vaga
A [Beep Saúde](https://www.beepsaude.com.br) está procurando desenvolvedor(a) frontend para nosso time. Estamos passando por momento de organização da nossa Stack e temos a oportunidade de reorganizar toda nossa plataforma de operação e de venda. 

## Local

Escritório, Rio de Janeiro - Glória

#### Diferenciais

- Equipe multidisciplinar
- geladeira sempre cheia :P
- Ambiente descontraído
- no dress code
- pet friendly
- ótima localização, ao lado do metrô da Glória

## Requisitos

**Obrigatórios:**

- experiência em desenvolvimento web
- bons conhecimentos de javascript
- APIs REST

**Desejáveis:**

- conhecimentos em ruby on rails
- Vue.js
- Desenvolvimento orientado a testes 

**Diferenciais:**
- Interesse no back-end (tornar-se fullstack)
- Native Script 
- Ionic

## Contratação

PJ a combinar

## Nossa empresa

A Beep surge com o objetivo de descomplicar a saúde no Brasil. Sim, sabemos o tamanho desse objetivo e estamos preparados para encarar o desafio. Começamos levando médicos até a casa do pacientes e incluímos a vacinação em nossos serviços que hoje se dividem em duas modalidades: Housecall e Marketplace.

Nosso objetivo é que todos percebam a importância do cuidar e do comprometimento que isso exige. Exatamente por isso entendemos que uma das melhores formas de contribuir com a vida, com a saúde, é criar uma percepção cada vez maior que a prevenção e o cuidado são os caminhos mais eficazes para uma vida plena.

Entendemos o atendimento médico domiciliar e as vacinas como uma das formas mais eficazes de cuidar da saúde. Pois isso começa quando a vida começa. Ainda antes do parto mas algo que se estende por toda a vida. Garantir a proteção necessária na gravidez e nos primeiros anos da criança são passos fundamentais para um futuro forte e pleno.

Beep! A Nova Forma De Cuidar Da Saúde.

## Como se candidatar

Por favor envie um email para luiz@beepsaude.com.br com seu CV anexado ou link para linkedIn - enviar no assunto: Vaga Front End 

## Labels

- PJ
- Pleno

**Comment by brunokunace** [comment]
Aceita remoto?

**Comment by gutomcosta** [comment]
Oi @brunokunace, no momento estamos dando preferencia para presencial, mas pode ser que no futuro tem essa possibilidade sim.

**Comment by gutomcosta** [comment]
oi @ngustavo, vc fala estagiário? No momento estamos procurando alguém para trabalhar full time. Com relação ao nível, a gente pode conversar.

**Comment by Murillofilho86** [comment]
Enviado

**Comment by ngustavo** [comment]
Ok! Enviado.
