### ISSUE TITLE
[São Paulo] Front-End Developer (Pleno ou Sênior) na Turbi

### ISSUE THREAD

**Issue by Almanake** [frontendbr/vagas#1062]
## Descrição da vaga

Para estas vagas, procuramos profissionais com experiência nos seguintes requisitos:
* Experiência com algum dos frameworks SPA (Angular, React, Vue, Ember)
* Javascript
* HTML/CSS
* Pré-processador CSS (SASS)
* TDD
* MVC
* Consumo de API REST/SOAP
* Controle de versão (GIT)
* Google Cloud Platform /Firebase 
* Agile/Scrum
* Princípios SOLID

## Local

Local: PLUGCLXT - Rua Lisboa, 890 (Pinheiros)

#### Diferenciais

Horário Flexível
Ambiente descontraído
Oportunidade de criar algo do zero e acompanhar o desenvolvimento do produto
Stock Options (avaliar conforme crescimento e responsabilidades)

## Requisitos

**Obrigatórios:**
* Experiência com algum dos frameworks SPA (Angular, React, Vue, Ember)
* Javascript
* HTML/CSS
* Pré-processador CSS (SASS)
* TDD
* MVC
* Consumo de API REST/SOAP
* Controle de versão (GIT)

**Desejáveis:**
* Google Cloud Platform /Firebase 
* Agile/Scrum
* Princípios SOLID

**Diferenciais:**
- ter atuado ou interesse genuíno em startups de tecnologia.

## Contratação

PJ (valor mês)

## Nossa empresa

A Turbi é uma empresa de compartilhamento de veículos, focada em proporcionar uma experiência única para seus clientes, oferecendo uma frota de carros TOP.
Procuramos desenvolvedores(as) para integrar a Turbi.
Se você gosta de programar, aprender e compartilhar conhecimento esta é a oportunidade.

## Como se candidatar

Por favor envie um email para vieira@talentu.com.br com seu CV anexado ou perfil no LinkedIn.

## Labels

- PJ
- Pleno
- Sênior

**Comment by Almanake** [comment]
Edu, atualizações realizadas!
Os Labels são vocês que inserem?
Não consegui localizar por onde coloca-los.

**Comment by eduardojmatos** [comment]
Boa! :)

**Comment by xereda** [comment]
Aceitam remoto!?

**Comment by Almanake** [comment]
Olá Xereda. Hoje, infelizmente não seria possível remoto.
