### ISSUE TITLE
[Rio de Janeiro] Front-End Developer na Pareto Group

### ISSUE THREAD

**Issue by joaovcarvalho** [frontendbr/vagas#1066]
## Descrição da vaga

Procuramos desenvolvedor Frontend para trabalhar no nosso SaaS e desenvolver interfaces complexas utilizando JS e ReactJS. Possuímos um time que pratica agilidade e sempre quer evoluir. Alguns dos problemas que você possivelmente irá resolver são:

- Criação de interfaces de Dashboard, Kanban e gráficos para análise de resultados utilizando React.
- Integração com serviços existentes que agreguem valor a plataforma.
- Melhoria de desempenho do front com Webpack, Gulp.

Somos uma empresa pequena então você pode se desenvolver em toda a nossa stack e causar impacto que todo o produto. Além disso estamos abertos para novas tecnologias.

## Local

Escritório no Rio de Janeiro - Copacabana

## Benefícios

- VR de R$ 25/dia
- VT

#### Diferenciais

- Café sempre disponível
- Mesa de Ping Pong

## Requisitos

**Obrigatórios:**
- JS ES6
- HTML5
- CSS3

**Desejáveis:**
- React ou outro framework moderno como Angular ou VueJS
- Experiência com module bundlers (Webpack, Browserify, RequireJS, etc.)
- Experiência com pré-processadores CSS

**Diferenciais:**
- Styled Components
- CSS in JS
- Redux

## Contratação

CLT a combinar

## Nossa empresa

Pareto é a startup de otimização de campanhas de marketing digital e de apoio à decisão. Trabalhamos para automatizar processo repetitivos, tomar decisões automáticas baseadas em dados, desenvolver algoritmos inteligente para atuar em um mercado dinâmico. Somos Premium Partner do Google atuando fortemente com Adwords. 

Desenvolvemos o Pareto Quantic, plataforma de automatização e inteligência aplicados ao mercado de marketing digital.

## Como se candidatar

Por favor envie um email para joao.carvalho@paretogroup.com.br com seu CV anexado - enviar no assunto: Vaga Frontend

## Labels

- Alocado
- CLT
- Júnior
- Pleno

**Comment by adeonir** [comment]
Aceitam remoto?

**Comment by joaovcarvalho** [comment]
Infelizmente não @adeonir

**Comment by deglier** [comment]
Possuem vaga para estágio?

**Comment by joaovcarvalho** [comment]
Preferimos CLT, mas também temos interesse em estágio, pode mandar currículo @deglier

**Comment by costaleonardo** [comment]
Enviado :)

**Comment by thiagocruzrj** [comment]
Vaga de Jr. ainda disponível ?
