### ISSUE TITLE
[Rio de Janeiro] Front-End Developer na Working Minds

### ISSUE THREAD

**Issue by brunosantanarj** [frontendbr/vagas#1067]
## Desrição da vaga
A [Working Minds](http://www.wkm.com.br/) procura por Front-End Developer para início imediato.

## Local
Centro - Rio de Janeiro.

Vaga presencial.

## Requisitos Obrigatórios
* Experiência em desenvolvimento, manutenção e análise de sistemas e de negócio;  
* Experiência com React e todo ecossistema (Redux, Styled-components, Webpack);
* Bom conhecimento de CSS (SCSS, BEM, OOCSS).

## Requisitos Técnicos desejáveis:
* Conhecimento avançado em JavaScript (ES6+);
* Conhecimento e utilização Clean Code;
* TDD(Jest, Mocha, Jasmine);
* Conhecimentos em Design Patterns;
* Responsive/Adaptative Desgin;

## Requisitos não técnicos:
* Comprometimento; 
* Boa comunicação;  
* Capacidade de trabalhar bem em equipe;  
* Pró atividade, com foco em resultado;  
* Capacidade para assimilar novas informações, tecnologias e ferramentas;  
* Aptidão na identificação e compreensão de problemas e oportunidades;  
* Adaptabilidade a mudanças;

## Contratação
CLT

## Benefícios
* Valor da remuneração mensal: R$4.000,00 - R$5.000,00
* Sodexo refeição: R$24,30 (por dia útil)
* Sodexo alimentação: R$331,37 (mensal)
* VT: o que explicamos, desconto de até 6% do salário, dependendo do valor que você gasta de passagens
* Plano de Saúde e Odontológico Sulamerica

## Nossa empresa

Somos um time de especialistas que idealiza, desenvolve e evolui soluções digitais inovadoras.
Ao longo desses 8 anos, construímos um sólido portifólio de soluções em plataformas Web, Desktop e aplicativos Mobile. Também participamos de competições internacionais, como o [Hello Wolrd Open](http://helloworldopen.com/) e recentemente criamos o projeto open source [Realize.js](http://working-minds.github.io/realizejs/).

## Para se candidatar
Envie seu CV para [bsantana@mongeralaegon.com.br](mailto:bsantana@mongeralaegon.com.br) com o título "Front-End Developer" e realize nosso [desafio](https://github.com/brunosantanarj/mongeral-aegon-front-end-test).

## Labels

- Alocado
- CLT
- Pleno

**Comment by RenatoAreas** [comment]
Tem algum beneficio de constituível, caso queira ir de veiculo ?

**Comment by cotts** [comment]
Somente alocado?
