### ISSUE TITLE
[São Paulo] Frontend Javascript Mobile - Ionic na Intelipsot

### ISSUE THREAD

**Issue by brunoosilva** [frontendbr/vagas#1068]
## Descrição da vaga

- Inovar trazendo tecnologias recentes e de mercado para a equipe
- Planejar a arquitetura dos aplicativos mobile desenvolvidos pela empresa.
- Atuar juntamente com a equipe de frontend na adoção de novos padrões e tecnologias javascript para equipe.
- Definir e estruturar o desenvolvimento dos novos aplicativos mobile que a empresa oferece ao mercado e mapear melhorias junto ao time nos aplicativos existentes
- Criar e codificar testes automatizados
- Análise de possíveis fontes de erros e sempre corrigir os bugs de forma eficientes

## Local

Escritório, São Paulo - Vila Mariana

## Benefícios

- Remuneração competitiva + Bônus
- Assistência Médica: Amil Saúde (One Health)
- Assistência Odontológica: Metlife
- Seguro de Vida: Itaú Seguro
- Aulas de Inglês
- VT ou 50% do valor para estacionamento
- VR: 22,00 dia

## Requisitos

**Obrigatórios:**
- Experiência significativa com Node.JS, HTML5, CSS3, Ionic 3, Angular 4
- Conhecer o processo de publicação de aplicativos nas lojas Play Store (Android) e App Store (iOS) 
- Estar antenado e ligado em outros frameworks como React, Vue, Ember, Mithril, etc
- Trabalhar com gerenciadores de tasks como Gulp, Grunt
- Conhecer e estar disposto a aplicar novos conceitos como PWA, AMP, SWs e etc
- Experiência significativa com aplicações web modernas e APIs REST (json), ferramentas de testes como Jasmine, JS Mock e outras
- Experiência significativa com GIT + Métodos ágeis como Kanban ou Scrum
- Estar alinhado com conceitos de aplicações responsivas, mobile first e pixel perfect concepts

**Diferenciais:**
- projetos opensource

## Contratação

CLT

## Nossa empresa

A Intelipost é uma startup de tecnologia que está revolucionando a logística no Brasil, um mercado de R$ 300B por ano com muitas ineficiências e desafios. Temos um sistema inovador que gerencia a logística para empresas do e-commerce. Já recebemos R$11 milhões de investimento até o momento, e em pouquíssimo tempo já estamos colhendo grandes resultados: Em 2016 fomos selecionados como uma empresa Promessas Endeavor, também ganhamos a competição [IBM Smartcamp](https://www.ibm.com/blogs/robertoa/2016/11/intelipost-e-nazar-vencem-o-ibm-smartcamp-brasil-2016/) com foco de Big Data e data analysis, o que nos rendeu a [realização de um Hackathon sobre Blockchain junto a IBM](https://www.ibm.com/blogs/robertoa/2017/09/intelipost-e-ibm-realizam-o-primeiro-hackathon-de-blockchain-em-startup-do-brasil/) e em 2017 fomos selecionados pela Oracle para sermos acelerados por eles no programa Oracle Startup Cloud Accelerator.

## Como se candidatar

[Clique aqui](https://jobs.kenoby.com/intelipost/job/desenvolvedor-javascript-mobile-ionic/5ac6326518252b5f5948968a) para se candidatar

## Labels

- Alocado
- CLT
- Pleno
- Sênior

**Comment by juniorabranches** [comment]
candidatura realizada
