### ISSUE TITLE
[Alphaville - Barueri e Vila Olímpia-São Paulo] - Front End Pleno -Sênior

### ISSUE THREAD

**Issue by MJVRHSP** [frontendbr/vagas#107]
## Descrição da vaga

Atuar com AngularJS
## Local

Alocado no cliente, São Paulo - Vila Olímpia e/ ou Alphaville - Barueri
## Contratação

São Paulo (Vila Olímpia) : CLT ou PJ
Barueri (Alphaville): PJ - Projeto pontual
Horário: Comercial e Presencial
## Nossa empresa

QUEM É A MJV?

Somos uma empresa que há 18 anos se dedica a transformar negócios, no Brasil e no mundo. Nosso time é multidisciplinar, formado por mais de 300 profissionais especializados na construção de soluções inovadoras em colaboração com nossos clientes.
Nossas áreas de conhecimento, que nos distinguem no mercado, são Design Thinking, Gamificação, Big Data/Analytics, Metodologia Lean, Estratégia Digital e Internet das Coisas.

www.mjv.com.br
## Como se candidatar

Encaminhar currículo com o nome da vaga no assunto + portfólio + pretensão salarial para contratação PJ e CLT + local de trabalho de interesse para: rhsp@mjv.com.br

**Comment by eduardojmatos** [comment]
@MJVRHSP já preencheu a vaga? Nos avise pra mantermos ou removermos da lista :)

**Comment by LFeh** [comment]
@MJVRHSP Fechou por aqui? :)

**Comment by MJVRHSP** [comment]
Infelizmente não =(

**Comment by camilatigre** [comment]
@MJVRHSP 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
