### ISSUE TITLE
[Exterior] Tutor de Desenvolvimento Web Nativapps

### ISSUE THREAD

**Issue by clmadrazo** [frontendbr/vagas#1072]
## Descrição da vaga

Para você que manja de várias tecnologias no mundo do desenvolvimento web e tem vocação por dar aulas, servir como mentor e ajudar pessoas.
A Nativapps está procurando desenvolvedores brasileiros para sumar a sua equipe de tutores. 

## Local

Remoto/Home Office

## Benefícios

- Trabalho home office
- Futura participação em projetos internacionais
- Horário Flexível

## Requisitos

**Obrigatórios:**
Conhecimento e experiência de ao menos dois anos nas seguintes tecnologias:
- HTML5
- CSS3
- JavaScript
- PHP
- NodeJS
- Angular, React, React Native, Native Script
- Bootstrap, Foundation, Materialize
- WordPress
- BigData, MySQL, MongoDB
- AWS, Azure

**Diferenciais:**
- Domínio de espanhol e/ou inglês
- Já ter dado aulas, palestras ou mentorias

## Contratação

Prestação de serviços pro exterior

## Nossa empresa

Nativapps é uma empresa de TI com mais de 14 anos de experiencia fornecendo soluções de desenvolvimento de software ao mundo desde Barranquilla, Colombia. A empresa é focada em criar ferramentas que impulsem a transformação digital dos seus clientes, fazendo que os processos sejam mais efetivos e rentáveis. A empresa atualmente conta com uma grande carteira de clientes em América Latina, Estados Unidos e na Espanha.

## Como se candidatar

Por favor, envie um email até o dia 28/05/2018 para talentohumano@nativapps.com com cópia para cmadrazo@nativapps.co com seu CV anexado – enviar no assunto: Tutor X
Obs: X seria o tipo de tutor seja de desenvolvimento web ou android

## Labels

- Home Office
- Pleno
- Sênior
- Remoto - Total

**Comment by rzorzal** [comment]
enviei e-mail com o seu e-mal como cópia e somente para o seu voltou, tentei com final .com assim como o dominio do outro e-mail.

**Comment by clmadrazo** [comment]
estranho @rzorzal, os dois emails estão corretos. Enfim, se ao menos um dos emails deu certo pode ficar tranquilo!

**Comment by rzorzal** [comment]
sim, já entraram em contato comigo. Obrigado.
