### ISSUE TITLE
[Rio de Janeiro/RJ][Remoto] Front-End Developer na PEBMED

### ISSUE THREAD

**Issue by pedrogemal** [frontendbr/vagas#1076]
Vaga para desenvolvedor web PHP (Wordpress) presencial ou remoto.

**O que você vai fazer:**

- Ser responsável pela manutenção de um dos maiores portais de notícias médicas do Brasil;
- Tratar dados de interação dos usuários e correlacionar com regras de negócio.

**Local:**

- Presencial ou Remoto (a combinar), full time ou part time;
- Na Rua Voluntários da Pátria, a 10 minutos da estação de metrô de Botafogo, no Rio de Janeiro.

**Habilidades obrigatórias:**

- Conhecimento e trabalhos prévios em Wordpress (functions PHP, instalação e  atualização de plugins, templates, multi-site, Codex, ACF, integração do HTML + CSS com o Wordpress e customização da interface), boas práticas de segurança e performance;
- Noção de consumo da API do Google Analytics®;
- Capacidade de autogestão e _team work_;
- Vontade em inovar e melhorar a saúde do Brasil.

**Habilidades desejáveis:**

- Envolvimento com projetos open source/comunidade;
- Vivência em projetos utilizando metodologia ágil (Scrum) e experiência com uso do Jira;
- Experiência com GitFlow.

**Habilidades diferenciais:**

- Noções de otimização de sites (SEO);
- Noções de Python para análise de dados;
- Experiência prévia com AWS.

**Contratação:**

- PJ.  Benefícios a conversar.

**Como se candidatar:**

- Por favor, envie um email para pedro@pebmed.com.br com seu CV anexado e sua pretensão salarial. Enviar como assunto: Vaga Wordpress.

> Seja você mesmo, todos os outros já existem. 

**Labels**

- Freela
- PJ com benefícios a combinar
- Pleno
- Sênior
- Remoto - Parcial ou Total

**Comment by ngustavo** [comment]
PHP é front-end? :thinking:
