### ISSUE TITLE
[Palhoça - SC] Front-End Developer na MovTI

### ISSUE THREAD

**Issue by welligtonporto** [frontendbr/vagas#1079]
## Descrição da vaga

Estamos procurando um profissional responsável para trabalhar no desenvolvimento front-end do principal produto da empresa e eventualmente em outros projetos.

## Local

Pedra Branca - Palhoça - SC
(Próximo a Grande Florianópolis)

## Benefícios

- Salário compatível ao cargo.
- Alimentação e refeição.
- Plano de Saúde Agemed
- Capacitações e certificações Google. 
- Ambiente desafiador com alta possibilidades de crescimento.
- Empresa com cultura de inovação
- Ótimo ambiente de trabalho.

## Requisitos

**Obrigatórios:**
- Conhecimento avançado em HTML5
- Conhecimento avançado em CSS3
- Conhecimento avançado em Javascript
- Conhecimento intermediário em algum framework Javascript, tais como React, Angular ou Vue.js
- Conhecimento intermediário em conceito REST
- Conhecimento em práticas de usabilidade para criar ótimas experiências aos nossos usuários (independente do dispositivo ou resolução dos mesmos - #responsividade ^_^)
- Escrever um código escalável, limpo e bem documentado

**Desejáveis:**
- Experiência em componentização front-end
- Conhecimento intermediário em Git
- Conhecimento em práticas ágeis

**Diferenciais:**
- Conhecimento intermediário em testes unitários

## Contratação

CLT

## Nossa empresa

Sendo parceiro Google Cloud no Brasil levamos ao mercado soluções inteligentes de trabalho, para proporcionar as empresa mais inovação, aumento na produtividade das equipes e redução de custos.

Nosso time é composto por pessoas apaixonadas pelo que fazem e com conhecimentos complementares. Em nosso DNA possuímos a inovação, não focando apenas nas melhorias incrementais, mas sim em gerar valor e o máximo de impacto positivo aos negócios.

[Mais sobre a empresa](http://www.movti.com.br/) | [Sobre o nosso principal produto](http://assetify.com.br/)

## Como se candidatar

Interessados devem encaminhar seu Linkedin e/ou currículo e/ou carta de apresentação para os e-mails: romulo.simas@movti.com.br e welligton.porto@movti.com.br com assunto "Vaga Desenvolvedor Front-end Júnior/Pleno"

## Labels

- Alocado
- CLT
- Júnior
- Pleno

**Comment by matheus-rosin** [comment]
Remoto?
