### ISSUE TITLE
[São Paulo / SP] Desenvolvedor Web Front-End | BovControl

### ISSUE THREAD

**Issue by nic** [frontendbr/vagas#108]
## Desenvolvedor Web Front-End
Fala galera, tudo certo?

Tá rolando uma vaga pra front-end aqui na BovControl de São Paulo. Interessou?

Se liga aí:
👇
## Descrição da vaga

Estamos buscando os melhores brasileiros(as) para integrar a startup de pecuária de maior crescimento no mundo! É apaixonado por desenvolvimento? Você está preparado? Então chegou sua hora! Possuímos núcleos de desenvolvimento em Boston - MA, Mountain View - CA e em São Paulo - SP. Esta vaga aberta é para nosso escritório de São Paulo. 🇧🇷

Queremos desafia-lo a construir painéis de controle e landing pages!
Será você que irá entender as nerdices das desenvolvedores backend com as viagens dos designers, dando vida (e cara) a tudo isso.

## Local

Escritório, São Paulo - Berrini

## Benefícios

- Mac + monitor
- Não damos suporte para o IE
- Assistência Médica (SulAmérica Saúde)
- Assistência Odontológica (SulAmérica Odonto)
- Ambiente descontraído e informal

## Requisitos

**Obrigatórios:**
- HTML5  👀
- CSS3 (SASS)
- Google Material Design
- Photoshop (básico) para criação de páginas com base nos designs fornecidos (.PSD)

**Desejáveis:**
- Noções de programação funcional
- Single Page Application
- JavaScript (ECMAScript 6)
- Consumo de API REST
- Ambientação em Linux ou Mac
- Processos e métodos ágeis (SCRUM, Kanban)
- Sketch (básico) para criação de páginas com base nos designs fornecidos (.SKETCH)

**Diferenciais:**
- React + Redux + Saga
- Webpack / Gulp
- Controle de versão via Git
- PHP 5+ (básico)

## Contratação

CLT Full time

## Nossa empresa

BovControl é uma startup de tecnologia que está revolucionando a forma de fazer gestão da atividade pecuária em todo o mundo. É uma ferramenta de coleta e análise de dados para melhorar a performance da produção de carne, leite ou genética. www.bovcontrol.com

## Como se candidatar

Por favor envie um email para hello@bovcontrol.com com seu CV anexado - enviar no assunto:  FrontEnd SP

**Comment by LFeh** [comment]
Boa vaga heim!

**Comment by Fachiquito** [comment]
Me candidatei!

**Comment by carmona** [comment]
> Benefícios
> Não damos suporte para o IE

Melhor descrição de vaga.

**Comment by nic** [comment]
Inscrições encerradas! Muito obrigado a todos. :)

**Comment by LFeh** [comment]
\o

**Comment by camilatigre** [comment]
@nic 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by nic** [comment]
Oi @camilatigre Infelizmente não conseguimos preencher a vaga até hoje!! :(

**Comment by uselessdev** [comment]
@nic Vocês ainda estão aceitando CV?

**Comment by nic** [comment]
@uselessdev Simmm!! Envie para hello@bovcontrol.com com o assunto "Vaga Front-end BovControl SP" @Corelio

**Comment by uselessdev** [comment]
@nic Enviado :smile:
