### ISSUE TITLE
[São Paulo] Front-End Developer na Creditas

### ISSUE THREAD

**Issue by aureliosaraiva** [frontendbr/vagas#1080]
## Descrição da vaga

Você participará de discussões de produto e será responsável junto com o restante do time de propor a melhor solução técnica. Você vai trabalhar, no seu dia-a-dia, com nossas aplicações internas e ferramentas. Atuando dentro de um time multidisciplinar, a tendência é que você também execute outras tarefas além dessas, dependendo do momento. 

## Local

Escritório, São Paulo - Novo Brooklyn, ao lado da estação Vila Olimpia

## Benefícios

- Vale Refeição
- Vale Transporte ou Estacionamento
- Plano de Saúde e Odontológico para você e dependentes
- Seguro de Vida (Itaú); 
- Plano de Academia (Gym Pass);  
- Aulas de Inglês duas vezes por semana in-company sem descontos.
- Reembolso de 50% de cursos, livros, eventos.

## Requisitos

**Obrigatórios:**
Ser apaixonada(o) por desenvolvimento de software e tecnologia
Ser poliglota em linguagens de programação e plataformas;
Ter facilidade para trabalhar dentro de times multi-disciplinares;
Saber escrever código limpo e legível;
Possuir conhecimentos de integração utilizando API RESTful;
Ter conhecimento de práticas de XP (TDD, pair programming, refactoring, continuous integration, etc);
Conhecer e ter experiência com testes unitários, de aceitação, mocks, etc;
Saber trabalhar com ferramentas de controle de versão;
Conhecimentos de design de interface e experiência do usuário.

**Diferenciais:**
Ter experiência com React, React Native ou Ember.js

## Contratação

CLT - Pleno ou Sênior

## Nossa empresa

A Creditas é uma das Fintechs mais quentes do país. Sediada em São Paulo, a missão da empresa é reduzir as taxas de juros para o trabalhador brasileiro, atuando como uma plataforma de crédito digital focada em empréstimos com garantia. Ao combinar tecnologia e inteligência de dados, a Creditas conseguiu iniciar a democratização de produtos de juros baixos, revolucionando a experiência de crédito no Brasil.

## Como se candidatar

Você pode me chamar no Linkedin pra bater um papo [site](linkedin.com/in/aureliosaraiva) ou mandar um email para aurelio.saraiva@creditas.com.br

## Labels

- Alocado
- CLT
- Pleno
- Sênior

**Comment by brunooomelo** [comment]
aceitam voluntários remoto?

**Comment by vinyguedess** [comment]
Entrando em contato

**Comment by GiovanniSM20** [comment]
@brunooomelo Conseguiu entrar em contato com o mesmo ?

**Comment by aureliosaraiva** [comment]
@brunooomelo tudo bem? Infelizmente é somente presencial.

**Comment by aureliosaraiva** [comment]
Oi @brunooomelo sim, você pode fazer todo o processo remoto.
