### ISSUE TITLE
[São Paulo] Front-End Developer na [Seed TS]

### ISSUE THREAD

**Issue by MikaelaSeedts** [frontendbr/vagas#1081]
Desenvolver Front-end, integrar com APIs no Front- end, fazer validações de campos de entrada e as demais programações.
Domínio em Angular 4 ou superior.
Benefícios: Tíquete-refeição, Vale-transporte.
Regime de contratação: CLT (Efetivo) ou Prestador de serviços (PJ).
Informações adicionais: Próximo ao Shopping Morumbi.
Início imediato.

Por favor envie um email para mikaela.andrade@seedts.com com seu CV anexado - enviar no assunto: Vaga Front-end

**Comment by LFeh** [comment]
@MikaelaSeedts Para a vaga ficar aqui é necessário seguir o [template de criação](https://github.com/frontendbr/vagas/blob/master/.github/issue_template.md) no corpo da mensagem

**Comment by LFeh** [comment]
Como não houve nenhuma atualização vou fechar.
