### ISSUE TITLE
[São Paulo] Front End Developer - Pleno, Sênior e Especialista na RADAR Profissional 

### ISSUE THREAD

**Issue by RADARProfissional** [frontendbr/vagas#1084]
Front End Developer - Pleno, Sênior e Especialista na RADAR Profissional 

## Descrição da vaga

•	Atuar na criação de novos serviços e plataformas digitais;
•	Desenvolvimento das interfaces das plataformas e serviços.

## Local

São Paulo - SP - Zona Sul 

## Benefícios

VR, Plano de Saúde, Ax.creche, Plano Odontológico, entre outros.

## Requisitos

•	Superior completo em Administração, Análise de Sistemas, Ciências da Computação, Tecnologia da Informação, Engenharia da Computação ou áreas afins;
•	Experiência em desenvolvimento Front End, com CSS, JavaScript e HTML5;
•	Vivência com NodeJs, React, Redux, ES6;
•	Experiência com aplicação de técnicas TDD – Test-Driven Development (Desenvolvimento Orientado a Testes) e Behavior Driven Development (Desenvolvimento Guiado por Comportamento ou Desenvolvimento Orientado a Comportamento);
•	Experiência em metodologias ágeis de desenvolvimento (Scrum, Kanban) e conhecimento em gerenciadores de dependência e build (Maven, Gradle, npm, yarn);
•	Experiência com ferramentas como Gulp, Grunt e webpack e integração com backend via APIs REST;
•	Conhecimento em ferramentas de controle de versão (Git) e técnicas de CSS Responsivo (Mobile first);
•	Experiência com pré-processadores (sass, less, stylus, postcss) e Patterns de organização de CSS (smacs, bem);
•	Design patterns com JavaScript;
•	Experiência com programação assíncrona (Promises, Generators, Streams) e ferramentas de qualidade de código (Linters, Analise de complexidade);
•	Experiência com libs conhecidas (lodash, momentjs, etc);
•	Experiência com Grid, FlexBox, Mobile First, Noções de UX e Design de Interação;
•	Forte conhecimento do protocolo HTTP e Single Page Apps.

## Contratação

CLT

## Nossa empresa

A Radar Profissional, Consultoria de Recrutamento & Seleção e Terceirização de mão de obra, busca profissionais para atuar em um dos nossos clientes. 

## Como se candidatar

Interessados, enviar CV para cristiane@radarprofissional.com.br

## Labels
- CLT

**Comment by vinyguedess** [comment]
Zona sul onde ?

**Comment by RADARProfissional** [comment]
Vila Olímpia 

 



 

Esta mensagem pode conter informações confidenciais e/ou privilegiadas. Se você não for o destinatário ou a pessoa autorizada a recebê-la, não pode usar, copiar ou divulgar as informações nela contidas ou tomar qualquer ação baseada nelas. Se você recebeu esta mensagem por engano, por favor, avise imediatamente o remetente, e em seguida, apague-a. Comunicações pela Internet não podem ser garantidas quanto à segurança ou inexistência de erros ou de vírus. O remetente, por esta razão, não aceita responsabilidade por qualquer erro ou omissão no contexto da mensagem decorrente da transmissão via Internet. "ECONOMIZE PAPEL - PENSE ANTES DE IMPRIMIR!"

 

De: Vinicius Guedes <notifications@github.com> 
Enviada em: quarta-feira, 30 de maio de 2018 22:59
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: RADAR Profissional - Consultoria de Recrutamento & Seleção <cristiane@radarprofissional.com.br>; Author <author@noreply.github.com>
Assunto: Re: [frontendbr/vagas] SP - Front End Developer - Pleno, Sênior e Especialista na RADAR Profissional (#1084)

 

Zona sul onde ?

**Comment by diogomoretti** [comment]
@RADARProfissional essa vaga é para trabalhar na Radar ou em algum cliente de vocês?

**Comment by ortholon** [comment]
Salário?

**Comment by RADARProfissional** [comment]
A vaga é para São Paulo e estamos trabalhando com a pretensão salarial dos candidatos. 

 



 

Esta mensagem pode conter informações confidenciais e/ou privilegiadas. Se você não for o destinatário ou a pessoa autorizada a recebê-la, não pode usar, copiar ou divulgar as informações nela contidas ou tomar qualquer ação baseada nelas. Se você recebeu esta mensagem por engano, por favor, avise imediatamente o remetente, e em seguida, apague-a. Comunicações pela Internet não podem ser garantidas quanto à segurança ou inexistência de erros ou de vírus. O remetente, por esta razão, não aceita responsabilidade por qualquer erro ou omissão no contexto da mensagem decorrente da transmissão via Internet. "ECONOMIZE PAPEL - PENSE ANTES DE IMPRIMIR!"

 

De: ortholon <notifications@github.com> 
Enviada em: terça-feira, 5 de junho de 2018 14:25
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: RADAR Profissional - Consultoria de Recrutamento & Seleção <cristiane@radarprofissional.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [São Paulo] Front End Developer - Pleno, Sênior e Especialista na RADAR Profissional (#1084)

 

Salário?

**Comment by lucasfernandes** [comment]
Até onde eu sei, todas as vagas postadas nesse canal precisam vir com o salário oferecido.

**Comment by RADARProfissional** [comment]
Olá, Lucas! 

 

O Cliente pediu para trabalhamos com a pretensão salarial dos candidatos. Estamos com muitas vagas de Pleno, Sênior e Especialistas e achou melhor não definir uma faixa. 

 

Fico a disposição.

 



 

Esta mensagem pode conter informações confidenciais e/ou privilegiadas. Se você não for o destinatário ou a pessoa autorizada a recebê-la, não pode usar, copiar ou divulgar as informações nela contidas ou tomar qualquer ação baseada nelas. Se você recebeu esta mensagem por engano, por favor, avise imediatamente o remetente, e em seguida, apague-a. Comunicações pela Internet não podem ser garantidas quanto à segurança ou inexistência de erros ou de vírus. O remetente, por esta razão, não aceita responsabilidade por qualquer erro ou omissão no contexto da mensagem decorrente da transmissão via Internet. "ECONOMIZE PAPEL - PENSE ANTES DE IMPRIMIR!"

 

De: Lucas Fernandes <notifications@github.com> 
Enviada em: terça-feira, 5 de junho de 2018 15:49
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: RADAR Profissional - Consultoria de Recrutamento & Seleção <cristiane@radarprofissional.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [São Paulo] Front End Developer - Pleno, Sênior e Especialista na RADAR Profissional (#1084)

 

Até onde eu sei, todas as vagas postadas nesse canal precisam vir com o salário oferecido.

**Comment by diogomoretti** [comment]
@RADARProfissional essa vaga é para trabalhar na Radar ou para algum cliente de vocês?

O candidato será contratado pela Radar ou pelo cliente?

**Comment by RADARProfissional** [comment]
Pelo Cliente, mas a vaga é confidencial. 

 



 

Esta mensagem pode conter informações confidenciais e/ou privilegiadas. Se você não for o destinatário ou a pessoa autorizada a recebê-la, não pode usar, copiar ou divulgar as informações nela contidas ou tomar qualquer ação baseada nelas. Se você recebeu esta mensagem por engano, por favor, avise imediatamente o remetente, e em seguida, apague-a. Comunicações pela Internet não podem ser garantidas quanto à segurança ou inexistência de erros ou de vírus. O remetente, por esta razão, não aceita responsabilidade por qualquer erro ou omissão no contexto da mensagem decorrente da transmissão via Internet. "ECONOMIZE PAPEL - PENSE ANTES DE IMPRIMIR!"

 

De: Diogo Moretti <notifications@github.com> 
Enviada em: terça-feira, 5 de junho de 2018 16:47
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: RADAR Profissional - Consultoria de Recrutamento & Seleção <cristiane@radarprofissional.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [São Paulo] Front End Developer - Pleno, Sênior e Especialista na RADAR Profissional (#1084)

 

@RADARProfissional <https://github.com/RADARProfissional>  essa vaga é para trabalhar na Radar ou para algum cliente de vocês?

O candidato será contratado pela Radar ou pelo cliente?

**Comment by diogomoretti** [comment]
@RADARProfissional infelizmente temos que fechar a vaga, já que não está dentro das regras, conforme nosso [README](https://github.com/frontendbr/vagas#cadastrando-uma-vaga) onde o mesmo diz que é **OBRIGATÓRIO** apresentar o nome da empresa na qual o candidato irá trabalhar e/ou ser contratado.

Caso queira nos informar o nome da empresa, deixe aqui nos comentários que reabriremos a issue.

Obrigado.
