### ISSUE TITLE
[Franca/SP] React Native Developer na MazzaFC (MazzaTech)

### ISSUE THREAD

**Issue by brunoti** [frontendbr/vagas#1085]
## Descrição da vaga

Diversos projetos supimpas com React Native! Projetos de edução, financeiros, empresarias (internos) e etc..

Precisamos de desenvolvedores que aprendem rápido e se dedicam de maneira equivalente ao que falam que dão conta!

## Local

Preferência é alocado em Franca SP (bem no centro). Remoto é necessário organizar mas seriam necessárias diversas viagens.

Estamos organizando para colocar salas de desenvolvimento em Ribeirão e Campinas. Então vagas remotas para essas cidades são mais interessantes.

#### Diferenciais

- Horário Livre
- Salário Equivalente com a experiência
- Workshops internos
- Diversos projetos para aprender

## Requisitos

**Obrigatórios:**
- Experiência comprovada com React Native
- Passar no teste criado por nós

**Diferenciais:**
- Redux
- Experiências de builds para  iOS e toda a tristeza do xCode
- CodePush
- Fastlane
- Conhecimento e vontade de trabalhar com Backend (Python/PHP) 
- Conhecimentos de Machine Learning (temos projetos na área)

## Contratação

PJ, valor a combinar. **ENVIAR PRETENSÃO POR EMAIL**

## Nossa empresa

A MazzaFC realiza o desenvolvimento de projetos sob demanda nas tecnologias PHP, .Net, Mobile (Hibrido, Android, IOS), Java, Python, NodeJS, API.

Trabalhamos também com a sustentação de sistemas já existentes e demandas específicas para criação de aplicativos e programas.

Atuamos como fábrica de software ou com células exclusivas de desenvolvedores – das duas formas, nossa equipe, altamente especializada, age com excelência em todo o processo de desenvolvimento, gestão de testes e sustentações.

## Como se candidatar

Envie um email para bruno.oliveira@mazzafc.tech e lais.bernardes@mazzafc.tech com:
- CV
- Pretenção Salarial
- O que precisa para se mudar pra Franca (já explicando se viria sozinho ou mais familiares)
- Descreva suas habilidades e dê informações sobre você. Isso pode te ajudar a conseguir a vaga.

**Comment by brunoti** [comment]
Quem tiver um GitHub ou conseguir mostrar alguns projetos, ou testes feitos para outras em presas, não precisa de teste!

**Comment by brunoti** [comment]
Boa tarde, estamos com vaga ainda.

Estamos dando preferência pra quem mudar pra franca!

**Comment by brunoti** [comment]
Podem reabrir? Ainda há vagas!

**Comment by bernardonascimento** [comment]
Olá! As vagas são para Junior?

**Comment by brunoti** [comment]
Fala @bernardonascimento ! Para vários níveis. Estamos com alguns projetos que apareceram firmes durante a quarentena e alguns engatilhados para o pós pandemia.

Estamos pedindo um pouco de experiência, mas a gente conversa, vê o teste e vê se vale a pena pra você e pra empresa.

**Comment by THAYLLER** [comment]
@brunoti  como está? cara te pergunta como ta o status dessa vaga? e todos que mandarem curriculo consegue fazer o teste ou é feito uma triagem para quem vocês considera elegivel a fazer o teste?

**Comment by THAYLLER** [comment]
E um outro detalhe o email da lais voltou como erro ele ta certo?

**Comment by brunoti** [comment]
> E um outro detalhe o email da lais voltou como erro ele ta certo?

Cara mudanças de RH haha... **Eu atualizei o post com o email correto.**

> todos que mandarem curriculo consegue fazer o teste ou é feito uma triagem para quem vocês considera elegivel a fazer o teste?

Triagem

**Comment by THAYLLER** [comment]
Ah sim de boa normal ao menos pro seu foi é o mais importante
