### ISSUE TITLE
[São Paulo] Front-End Developer na McCANN Health

### ISSUE THREAD

**Issue by claudiobonfati** [frontendbr/vagas#1086]
## Descrição da vaga

Contratação CLT desenvolvedor(a) para vaga de Front-End.

## Local

Rua Loefgren 2527 
04040-033 - SP 
Vila Clementino  (Metro Santa Cruz)
São Paulo

## Benefícios

- Plano de saúde
- Seguro de vida
- VR
- Plano odontológico

## Requisitos

**Obrigatórios:**
- HTML5
- CSS3
- JavaScript (jQuery)

**Desejáveis:**
- conhecimentos em Git
- conhecimentos em Wordpress

**Diferenciais:**
- Angular ou Vue.Js

## Contratação

CLT

## Como se candidatar

Por favor envie um email para alvaro.silva@mccannhealth.com.br e tiago.rodrigues@mccannhealth.com.br com seu CV anexado e pretensão salarial.

## Labels

- Alocado
- CLT
- Júnior / Pleno

**Comment by danieladuarteng** [comment]
enviado
