### ISSUE TITLE
[Rio de Janeiro] Front-end Developer Junior na TUUT

### ISSUE THREAD

**Issue by vtrpldn** [frontendbr/vagas#1087]
## Descrição da vaga

TUUT procura front-end developer junior para nos ajudar a crescer, desenvolver e modernizar nossos projetos digitais.

Como um membro do time digital da TUUT você trabalhará, na maior parte do tempo, adaptando layouts Sketch+InVision para código front-end.

## Local

Escritório, Rio de Janeiro - Ipanema

## Benefícios

- Vale-transporte
- 13º salário
- Férias
- Plano de saúde após 6 meses

#### Diferenciais

- Ambiente extremamente propício à aprendizagem.
- Dress code casual.

## Requisitos

**Obrigatórios:**
- Conhecimento prático de html, css e javascript
- Experiência com git
- Conhecimento de WordPress
- Inglês técnico (pra pesquisar no stackoverflow)

**Desejáveis:**
- Experiência full-time como front-end
- Experiência com CLI
- Experiência com bundlers e automações de front-end
- Conhecimentos de UX
- Wireframing
- Familiaridade com desenvolvimento ágil

**Diferenciais:**
- Link de projetos live
- GitHub ativo
- Protótipos no CodePen
- Saber integrar front-end no WordPress

## Contratação

PJ R$ 1500-2000 dependendo da experiência

## Nossa empresa

A TUUT conduz seu negócio com inteligência emocional, pensamento criativo e entusiasmo coletivo. Primando por uma comunicação integrada, nossa plataforma de atuação é múltipla e o nosso posicionamento é multidisciplinar. Aqui, a gente executa todo projeto com estratégia, conceito, conteúdo e design. Raciocinamos em todas as mídias, viabilizando projetos para pequenas e grandes marcas, no Brasil e no exterior.

Estamos sempre aprimorando conhecimento e representamos um mix completo de especialidades: estratégia de marca, identidade visual, planejamento, design gráfico, filme e digital.

## Como se candidatar

Por favor envie um email para vitor.paladini@tuut.com.br com seu CV anexado - enviar no assunto: Vaga front-end frontendbr

## Labels

- Alocado
- Júnior
- PJ

**Comment by ldrbraga** [comment]
Enviado :)
