### ISSUE TITLE
[Porto Alegre] Frontend Developer no Dietbox

### ISSUE THREAD

**Issue by educosta** [frontendbr/vagas#1088]
Descrição da vaga

Buscamos um(a) desenvolvedor(a) Front-end capaz de construir interfaces para nosso software de nutrição, que curta aprender e codar (em JavaScript, CSS e HTML) e que goste de pensar no produto além do código.

A pessoa será responsável por pensar, contribuir no planejamento e desenvolver novas funcionalidades no Dietbox para plataforma Web, trabalhar junto com nosso time na arquitetura e definição de soluções e utilizar as melhores práticas e tecnologias para escrever código.

Local
Escritório no Menino Deus em Porto Alegre

Benefícios
A gente combina com você, tem plano de saúde, VT, VR essas coisas aí, mas se quiser colocar tudo no salário também pode

Requisitos
Obrigatórios:
Paixão em escrever código.
Vivência com desenvolvimento de aplicações Web de grande volume.
Domínio de conceitos e arquiteturas de desenvolvimento de software como OPP, DDD e etc.
Habilidade de desenvolver aplicações do seu início ao fim.
Se sentir confortável com arquiteturas de desenvolvimento, tais como, MVVM, MVC.
Vivência com desenvolvimento em ambientes e times ágeis.
Disponibilidade para trabalho em tempo integral.

Diferenciais:
Conhecimento em frameworks e bibliotecas como Knockout, Vue, Angular e Bootstrap.
Alguma experiência com tecnologias Microsoft e linguagem C#
Vivência com mais de uma linguagem de programação.
Experiência em escrever testes unitários e funcionais.
Paixão por aprender e empreender.

Contratação
PJ ou CLT

Nossa empresa
O Dietbox é uma plataforma para área de nutrição que impacta mais de 1 milhão de pessoas em todo pais e exterior, sendo o líder de mercado na área, no nosso site www.dietbox.me tem mais informações sobre nosso produto e durante o processo seletivo a gente vai tirar todas as dúvidas sobre a empresa

Como se candidatar
Se você se interessou, manda seu currículo, LinkedIn e/ou GitHub para contato@dietbox.me

**Comment by LFeh** [comment]
@educosta  Para a vaga ficar aqui é necessário seguir o [template de criação](https://github.com/frontendbr/vagas/blob/master/.github/issue_template.md) no corpo da mensagem
