### ISSUE TITLE
[São Paulo / SP] Desenvolvedor Front-End Sênior | Agência Foster

### ISSUE THREAD

**Issue by leonardosouza** [frontendbr/vagas#109]
## Descrição da vaga

Programador Front-End Sênior

## Local

Alocado na Agência Foster - Paraíso

## Benefícios

- Benefícios padrão da CLT (VR, VT, Assistência médica Sulamérica, Seguro de vida, etc)
- Banco de Horas

## Requisitos

Experiência com:
- HTML5, CSS3, Javascript, jQuery
- SASS, Gulp e/ou similares
- Git
- Command-line
- Bootstrap
- AngularJS
- NodeJS
- Parallax
- Integração com APIs (Social, Parceiros, etc)
- Orientação a objetos
- Código limpo e organizado
- Photoshop

Desejável:
- PHP
- CakePHP
- Wordpress
- MySQL

## Contratação

CLT Full

## Nossa empresa

http://www.foster.com.br/
Empresa com mais de 20 anos no mercado e integrante do grupo WPP.

## Como se candidatar

Por favor, envie seu currículo / portfolio / links de sites desenvolvidos, junto com sua pretensão salarial para marcos.falcao@foster.com.br.

**Comment by LFeh** [comment]
Boa sorte ;)

**Comment by eduardojmatos** [comment]
Oi @leonardosouza já preencheu a vaga? Nos avise pra mantermos ou removermos da lista :)

**Comment by leonardosouza** [comment]
Opa! Vaga fechada! Fechando a issue aqui! ;-)

**Comment by camilatigre** [comment]
@leonardosouza 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by leonardosouza** [comment]
@camilatigre 
c)

Sorry pelo enorme delay na resposta! :(
