### ISSUE TITLE
[Rio de Janeiro] Front-End Developer Junior na Original.io

### ISSUE THREAD

**Issue by guilhermemarconi** [frontendbr/vagas#1090]
![Original.io](https://originalmedia.vteximg.com.br/arquivos/original-io-recrutamento.png)

## Descrição da vaga

Estamos em busca de um Desenvolvedor Front-End Junior com vontade de fazer a diferença no mercado de e-commerce, atuando na empresa que tem atuado com grandes marcas como Uber, Grupo Boticário, Grupo Technos, Grupo Soma, Ambev, Renner e Nestlé, entre outras. Se você tem fome de aprendizado e se encaixa com o perfil da empresa, sinta-se à vontade para fazer o teste e vir trabalhar com a gente!

## Local

Centro, Rio de Janeiro

## Benefícios

- Plano de saúde
- VR de R$ 30,00/dia
- VT
- Folga de aniversário

#### Diferenciais

- Equipe multidisciplinar
- Ambiente descontraído
- Pingue-Pongue
- Video Game

## Requisitos

**Obrigatórios:**
- Conhecimento básico em JavaScript
- Conhecimento básico em Sass (SCSS)
- Organização (afinal, HTML é organização :wink:)

**Diferenciais:**
- APIs REST
- Vue.js e/ou React
- Testes Unitários
- Webpack
- Interesse em aprender linguagens back-end (tornar-se fullstack)
- Projetos open source
- Experiência com a plataforma VTEX

## Contratação

- Presencial
- CLT
- Junior

## Salário

R$ 1.800,00 inicial

## Nossa empresa

Transformamos sonhos e desejos em experiências digitais apaixonantes. Com soluções inteligentes e foco nas necessidades dos nossos clientes e na conversão, atuamos em diversas divisões de negócio, como B2C, B2B, marketplace, entre outras.

## Como se candidatar

- Fazer [esse teste](https://github.com/original-io/join-us), seguindo as especificações do mesmo.
- Enviar currículo para cv@original.io com o assunto **Vaga Front-End Junior** e, também, informar seu usuário daqui do Github, para que possamos mapear o seu teste no repositório. :wink:

## Labels

- Alocado
- CLT
- Junior

**Comment by xbrunosousa** [comment]
Prazo para entrega do teste?

**Comment by RodrigoWebDev** [comment]
Gostaria de saber se contrata pessoa de fora do Rio

**Comment by guilhermemarconi** [comment]
@xbrunosousa deixamos o teste sempre aberto para que qualquer pessoa interessada possa fazer e enviar seu resultado a qualquer momento, pois com as contas que estamos atendendo, a tendência é o crescimento da equipe, mas estamos com certa urgência em preencher esta vaga, portanto quanto mais rápido, melhor!

@RodrigoWebDev a vaga é presencial. Em caso de trabalho remoto, pelo menos por enquanto não estamos com vaga para Junior ou Pleno que não tenha alguns conhecimentos específicos necessários no nosso dia a dia, tendo em vista o fato de que a mentoria pode não ser tão efetiva nesse formato diante o momento atual da empresa.

**Comment by renanlimabl** [comment]
O uso do JavaScript puro é obrigatório? Ou posso utilizar Jquery e outras ferramentas que utilizam JavaScript?

**Comment by souzalarissa383** [comment]
Precisa de experiência ??

**Comment by souzalarissa383** [comment]
Precisa de experiência ??

**Comment by guilhermemarconi** [comment]
@souzalarissa383 por ser uma vaga de júnior, precisamos apenas que faça o teste, para que possamos avaliar e, de acordo com ele, definirmos se está, ou não, dentro do perfil que procuramos.

Portanto, se você considerar "experiência" como o _conhecimento mínimo para a execução do teste_, sim. Caso contrário, não.

**Comment by souzalarissa383** [comment]
@guilhermemarconi Qual o prazo para a entrega do teste  ??

**Comment by guilhermemarconi** [comment]
@souzalarissa383 conforme dito em outro comentário anterior, não temos um prazo estipulado e deixamos o teste sempre disponível, pois estamos em processo de crescimento da equipe, sendo sempre interessante ter testes prontos.
De toda forma, temos urgência nessa contratação; portanto, quanto antes melhor.
