### ISSUE TITLE
[Remote] AngularJS Developer na DreamDev

### ISSUE THREAD

**Issue by douglasaguiar** [frontendbr/vagas#1091]
## Descrição da vaga

Estamos com algumas oportunidades para AngularJS Developer, níveis mid-senior e senior.

As vagas são para trabalhar remoto aqui do Brasil para alguns clientes da Irlanda com possibilidade de patrocínio de visto dentro de um ano ou antes.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Inglês nível upper-intermediate
- 3+ anos de experiência com AngularJS
- 5+ anos de experiência com desenvolvimento de software
- Bom conhecimento das boas práticas e padrões de desenvolvimento AngularJS

**Diferenciais:**
- TDD
- Experiência com o uso de Feature Flags
- DevOps
- Kanban

## Contratação

PJ a combinar

## Nossa empresa

A empresa DreamDev foi criada recentemente focada em consultoria de desenvolvimento de software para clientes do exterior.

## Como se candidatar

Por favor envie um email para jobs@dreamdev.io com seu CV em inglês anexado - enviar no assunto: AngularJS - |seu nome|

## Labels

- PJ
- Pleno
- Sênior
- Remoto - Total

**Comment by willianjusten** [comment]
Olá @douglasaguiar , igual o amigo falou ali acima, se puder só confirmar a versão. Porque bom, pedindo 3+ anos de experiência com Angular, creio que seja o antigo AngularJS certo? Ou é sobre o Angular atual, já na versão 6?

**Comment by douglasaguiar** [comment]
@DanielLCintra e @willianjusten desculpem e atualizado. Maior parte do projeto é na primeira versão  do AngularJS. Mas as versões mais atuais são utilizadas também. Em suma, a experiência com AngularJS entra na conta.

**Comment by DanielLCintra** [comment]
Excelente, @douglasaguiar .. eu não trabalho com angular, minha pegada é mais para o Vuejs, mas tenho certeza que pra quem trabalha com angular a informação vai ajudar bastante =)

**Comment by lffranca** [comment]
Tenho muita experiencia com Angular, mas nao possuo um ingles muito bom infelizmente

**Comment by marciogurka** [comment]
CV enviado!

**Comment by gabrigcl** [comment]
Tenho muita experiencia com Angular JS antigo, mas naturalmente não trabalho mais com ele desde o lançamento do Angular 2, isso conta?

**Comment by gabrigcl** [comment]
Currículo enviado
