### ISSUE TITLE
[São Caetano do Sul/SP] Estágio Front-End na Atma-IT Solutions

### ISSUE THREAD

**Issue by ealmeidas** [frontendbr/vagas#1092]
## Descrição da vaga

Estamos à procura de um(a) profissional com grande entusiasmo, vontade de aprender e crescer profissionalmente. Responsabilidade e engajamento para solucionar problemas são características importantes.
Criatividade, espírito de equipe e muito comprometimento farão a diferença!

## Local

Alameda Terracota, 215 - CJ 1212 - 09531190 - São Caetano do Sul - SP 

## Benefícios

- Vale-transporte
- Vale-refeição
- Ambiente de trabalho descontraído e equipe colaborativa
- Snacks, puffs e PS4
- Incentivo a treinamentos e formações

## Requisitos

**Obrigatórios:**
- Conhecimento em desenvolvimento Front-end
- Conhecimento em jQuery e formato JSON
- Conhecimento na criação de layout de sites baseados em HTML5, CSS e JavaScript
- Conhecimentos de design responsivo
- Comprometimento, trabalho em equipe, ter iniciativa e boa comunicação
- Curiosidade investigativa na busca de soluções inovadoras e criativas para melhoria da UX
- Alunos a partir do 3º semestre de Ciência/Engenharia da Computação, Comunicação, Publicidade e Propaganda ou x! (o importante é gostar de programar, independente da graduação)

**Desejáveis:**
- Conhecimentos em Node.js
- Conhecimentos em Angular JS
- Conhecimento em desenvolvimento de e-mail marketing
- Conhecimentos em ASP.NET MVC5 + Razor
- Conhecimentos controle de versões (TFS / Source Control)
- Habilidade com Photoshop, Fireworks e Microsoft Visual Studio
- Familiaridade com metodologias ágeis

## Nossa empresa

https://atma-it.com/

## Como se candidatar

Por favor envie um e-mail para vagas@atma-it.com com seu CV anexado - enviar no assunto: Vaga front-end

## Labels

- Estágio

**Comment by ealmeidas** [comment]
Por favor adicionar label: Estágio

**Comment by renanmurilo** [comment]
Enviado
