### ISSUE TITLE
[Remoto] React Native Developer no Vagalume

### ISSUE THREAD

**Issue by lafraia** [frontendbr/vagas#1095]
## Descrição da vaga

Tenho uma nova oportunidade no *Vagalume* para desenvolvedores focados em React Native. O foco é o desenvolvimento dos dois apps (Vagalume e Vagalume.FM) para IOS e Android. Sendo assim, conhecimento em Java também é desejável.

## Local

100% Remoto

## Requisitos

Por se tratar de um trabalho remoto, nossa preferência é contato com pessoas que estão fora dos grandes centros e que buscam qualidade de vida, conciliando boa dedicação nas tarefas e organização.

**Obrigatórios:**
- Experiência com desenvolvimento mobile (Android e IOS)
- 1 ano de experiência com React Native

**Desejáveis:**
- conhecimentos em Java
- conhecimentos em Swift

## Contratação

PJ a combinar

## Nossa empresa

Vagalume é um dos principais sites de música do Brasil. Muito provavelmente você já acessou o site, o projeto tem alta visibildade. O site recebe mais de 30 milhões de visitantes mensais.

## Como se candidatar

Por favor envie um email para rh@vagalume.com.br com seu CV anexado - enviar no assunto: Vaga React Native

## Labels

- Freela
- PJ
- Pleno
- Remoto - Total
- Sênior

**Comment by felipemfp** [comment]
@chicobentojr

**Comment by vaporwavie** [comment]
Enviado! :smile:
