### ISSUE TITLE
[São Paulo/SP] Frontend Developer na Hypnobox

### ISSUE THREAD

**Issue by vinyvicente** [frontendbr/vagas#1099]
## Descrição da vaga

A Hynobox precisa de um Frontend Developer para integrar os projetos novos e cuidar das padronizações de uma forma autônoma e que se integre à equipe de forma à ajudar nas demandas.

## Local

Escritório, São Paulo - Pinheiros - Próximo (mas muito próximo) do Metrô Faria Lima

## Benefícios

- Á combinar

#### Diferenciais

- Horário Flexível
- IMac
- Café :P

## Requisitos

**Obrigatórios:**
- Conhecimento em algum framework SPA (React, Vue, Angular)
- SAAS, gulp
- Experiência com mongodb e integração de API Rest
- JWT
- Metologia ágil de desenvolvimento (Scrum, XP)
- Gitflow

**Desejáveis:**
- TDD, BDD (Karma, Jasmine)

**Diferenciais:**
- AWS Lambda
- Typescript

## Contratação

CLT/PJ à combinar

## Nossa empresa

O Grupo Hypnobox tem um DNA jovem e vibrante. Nosso maior objetivo é fornecer soluções únicas de produtividade para as melhores empresas do mercado imobiliário. O grupo - como parceiro estratégico dos seus clientes - conecta as pessoas, constrói sucesso, cria realidades novas e transforma o mercado através novos jeitos de fazer acontecer.

## Como se candidatar

Por favor envie um email para curriculo@hypnobox.com.br com seu CV anexado - enviar no assunto: Vaga Frontend Developer

## Labels

- Alocado
- CLT
- PJ
- Pleno
- Sênior

**Comment by lucasalmeida92** [comment]
Opa! enviei para:
`mark.gerald@hynobox.com.br`
 e recebi mensagem de erro!

**Comment by vinyvicente** [comment]
@lucasalmeida92 fixed :tada:

**Comment by vinyvicente** [comment]
up

**Comment by vinyguedess** [comment]
Enviado
