### ISSUE TITLE
[São Paulo] Freela Front-End - Presencial

### ISSUE THREAD

**Issue by neysimoes** [frontendbr/vagas#11]
## Descrição da vaga

Criação do front-end do ecommerce de empresas parceiras.
Tempo de projeto: 6 meses podendo aumentar ou virar contratado CLT.

## Local

Presencial em São Paulo, região do Jaguaré (Zona Oeste).
Próximo a estação Jaguaré (CPTM)

## Requisitos

- HTML, CSS e JavaScript
- Build system (Gulp/Grunt/Webpack)
- Pré-processadores CSS (PostCSS/Stylus/Sass/Less)
- Git
- APIs RESTful
- Técnias de otimização (Web Performance Optimization)

Diferenciais
- Arquitetura frontend
- React.js (ou qualquer outra SPA)
- Node.js
- OAuth2
- Arquitetura de microservices

## Contratação

Fulltime presencial, PJ

## Nossa empresa

Somos uma loja online de produtos de beleza. Uma rede que conecta consumidores, marcas, formadores de opinião e os melhores profissionais do mercado.

Para ajudar você a fazer as escolhas que vão atender os seus desejos de beleza, todo um time de experts está a postos. São cabeleireiros e maquiadores badalados, renomados dermatologistas e editoras de beleza que escolheram a dedo mais de 200 marcas, levando até você informações completas, dicas e truques profissionais de mais de 13 mil produtos.

Nossa preocupação em atender você com excelência levou Beleza na Web a ser escolhida, por mais de 600 mil de consumidores, **A Melhor Loja de Beleza Online do Brasil**, e ser eleita entre as Top 5 de todo o comércio eletrônico do país.

O que estão falando sobre nós: 

[TechCrunch](http://techcrunch.com/2015/06/15/belezanaweb-raises-30m-to-bring-brazils-beauty-market-online/)
[Exame](http://exame.abril.com.br/revista-exame/edicoes/1083/noticias/ele-chegou-antes)

## Como se candidatar

Envie seu CV com Github para franklin.alves@belezanaweb.com.br

**Comment by franklinjavier** [comment]
:metal:

**Comment by camilatigre** [comment]
@neysimoes 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

**A pessoa que preencheu a vaga foi encontrada através desta issue?**
a) Sim
b) Não
c) Não tenho certeza

**Comment by franklinjavier** [comment]
@camilatigre não houve contratação, está em stand by.
