### ISSUE TITLE
[São Paulo / SP] Desenvolvedor front-end pleno / Wordpress

### ISSUE THREAD

**Issue by brunomonteiro3** [frontendbr/vagas#110]
## Descrição da vaga

Vaga de desenvolvedor front-end pleno, com foco principalmente para desenvolvimento para Wordpress e Magento (themes 100% customizados). Necessário ter experiência na área.
## Local

Escritório, São Paulo - Itaim Bibi
## Benefícios
- VR;
- VT ou estacionamento;
- Plano de saúde;
- Horário flexível;
- Acesso ilimitado a todos os produtos oferecidos pela empresa.
## Requisitos

**Obrigatórios:**
- Conhecimentos sólidos em desenvolvimento front-end: HTML5, CSS3, Javascript e jQuery;
- Conhecimento em pré-processadores CSS (SASS ou LESS);
- Conhecimento de task-runners como Grunt ou Gulp;
- Conhecimento em programação PHP;
- Conhecimento sólido de desenvolvimento Wordpress (e experiência com custom fields, taxonomies, custom post types e custom queries);
- Experiência com desenvolvimento front-end para Magento;
- Experiência com design responsivo e cross-browser;
- Experiência com desempenho, otimização e web performance;

**Desejáveis:**
- Experiência em desenvolvimento de e-mail marketing (compatibilidade entre diferentes clients e boas práticas de código);
- Conhecimento em SEO e boas práticas de código semântico;
- Conhecimento em Google Analytics e Google Tag Manager;
- Experiência com Git;
- Experiência com MySQL;
- Inglês intermediário para leitura, escrita e entendimento.

**Diferenciais:**
- Portfólio online (ou algum lugar que reuna projetos já publicados).
## Contratação

CLT
## Nossa empresa

Fundada em 2009, a Empiricus Research é a primeira consultoria de investimentos independente do Brasil. Oferece conteúdo gratuito e educativo para todos os investidores.
## Como se candidatar

Por favor, envie um e-mail para **carolina.zurita@empiricus.com.br** com seu CV anexado ou link para Linkedin. 
Importante: enviar no assunto: Vaga Dev Front-end. Por favor, sinalize que encontrou a vaga através da issue no frontendbr.

**Comment by eduardojmatos** [comment]
@brunomonteiro3 opa, já preencheu a vaga? Nos avise pra mantermos ou removermos da lista :)

**Comment by brunomonteiro3** [comment]
@eduardojmatos ,
Desculpe pela demora na resposta. A vaga ainda está disponível!

**Comment by brunomonteiro3** [comment]
@eduardojmatos, finalmente a vaga foi preenchida! Obrigado pela ajuda.

**Comment by eduardojmatos** [comment]
@brunomonteiro3 boa! Conseguiu alguém por aqui mesmo?

**Comment by LFeh** [comment]
Boa @brunomonteiro3, foi por aqui?

**Comment by camilatigre** [comment]
@brunomonteiro3 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
