### ISSUE TITLE
[São José dos Campos ou São Paulo] Front-End Developer Junior no Cuponomia 

### ISSUE THREAD

**Issue by rafaelpradella** [frontendbr/vagas#1105]
## Descrição da vaga

O [Cuponomia](https://www.cuponomia.com.br) está procurando um Desenvolvedor Front-End Junior para ajudar a compor a nossa equipe de Design/Desenvolvimento Web. Trabalho local c/ Contrato CLT e horário flexível. 

Interessados mandar currículo e portfólio/link do GitHub para [`rafael@cuponomia.com.br`](mailto:rafael@cuponomia.com.br)

## Locais
- Jardim Aquárius, São José dos Campos/SP
- Escritório na Av. Eng. Luís Carlos Berrini -  São Paulo/SP. *Perto da Est. Berrini da CPTM e Est. de Transferência Água Espraiada da SPTrans*.

## Benefícios

- Plano de saúde;
- Seguro de vida;
- Vale-Refeição;
- Vale-Transporte;
- Cota para compra de cursos/palestras/livros técnicos

## Requisitos

**Obrigatórios:**
- LESS/SASS e CSS sem precisar de frameworks;
- HTML5 Semântico; 
- Estar confortável em usar ferramentas de versionamento (nós utilizamos o GitHub);
- Utilizamos jQuery, mas é importante saber o Javascript puro;
- Design Responsivo;

**Diferenciais:**
- Vue e/ou React;
- Javascript ES6;
- Customização de temas de Wordpress;
- Noções de C#;

## Nossa empresa

O Cuponomia é um site totalmente gratuito que oferece desconto através de cupons e ofertas das principais lojas online nacionais e internacionais. São mais de 20.000 cupons em 2.000 lojas disponíveis, atualizados e testados diariamente.

Nós negociamos com os melhores e-commerces e vasculhamos toda a internet para encontrar e oferecer cupons exclusivos e descontos especiais.

Trabalhamos duro para garantir que todos os cupons da internet brasileira estarão disponíveis no Cuponomia.

**Comment by sarkioja** [comment]
CV Enviado!

**Comment by rafaelpradella** [comment]
Olá @danieladuarteng, a vaga serve para os escritórios de SJC e de São Paulo/SP.

**Comment by danieladuarteng** [comment]
enviado

**Comment by evertonrbraga** [comment]
Olá, existe a possibilidade da contratação ser PJ?
