### ISSUE TITLE
[Florianópolis] Front-End Developer na Avanti

### ISSUE THREAD

**Issue by thiagoalgo** [frontendbr/vagas#1108]
## Descrição da vaga

A equipe de desenvolvimento da [Avanti](http://penseavanti.com.br) Florianópolis não para de crescer. Estamos contratando desenvolvedor front-end para atuar na programação de interfaces web, com foco em e-commerce.

## Local

Escritório, Florianópolis
[https://goo.gl/maps/8cheLEg65eJ2](https://goo.gl/maps/8cheLEg65eJ2)

## Benefícios

- Salário entre R$2850,00 e R$3350,00 (dependendo da experiência e conhecimento)
- Vale alimentação ou refeição
- Vale transporte
- Plano de saúde (após experiência)

#### Diferenciais

- Café expresso o dia todo
- Fruta da estação diariamente
- Ginástica laboral
- Morar em Floripa :)

## Requisitos

**Obrigatórios:**
- Experiência em HTML, CSS e JavaScript
- Conhecimento da biblioteca jQuery
- Conhecimento em framework Bootstrap
- Conhecimento em grid e design responsivo
- Familiaridade com sistemas de controle de versão (Git)

**Desejáveis:**
- Conhecimento em Sass ou Less
- Conhecimento em React
- Conhecimento em Grunt, Gulp e WebPack

**Diferenciais:**
- Experiência com a plataforma de e-commerce VTEX
- Utilização de padrões e boas práticas para desenvolvimento

## Contratação

CLT

## Nossa empresa

A Avanti é líder em implantação de e-commerces sobre a plataforma VTEX. A cultura da empresa é de valorização das pessoas e atualmente somos certificados Great Place To Work.

## Como se candidatar

Por favor envie um email para dev-front@penseavanti.com.br com seu CV anexado - enviar no assunto: Vaga para Desenvolvedor Front-End

## Labels
- CLT
- Pleno

**Comment by LuizGMiranda** [comment]
Olá?

Vaga ainda está aberta?
