### ISSUE TITLE
[Curitiba] Front-End Developer no Grupo Inlog

### ISSUE THREAD

**Issue by lidia-freitas** [frontendbr/vagas#1109]
### Descrição da vaga
> Buscamos um desenvolvedor que goste de novos desafios usando as linguagens HTML, CSS, Javascript.
O profissional irá atuar com metodologias ágeis e equipes autogerenciáveis.

__Necessário:__     
Boa lógica de programação e algoritmos, além de padrões e boas práticas de desenvolvimento, performance em aplicações web.

__Desejável:__  
Javascript frameworks, preprocessadores CSS.

__O que oferecemos?__
- CLT, VT, VR, Plano de saúde e odontológico
- Salário a combinar
- Empresa com ambiente descontraído
- Escritório bem no centro de Curitiba
- Frutas e snacks o dia todo
- Parcerias de desconto para graduação e pós-graduação
- Seguro de vida em grupo

__Quem somos?__  
Somos um grupo que tem a inovação como um dos nossos valores essenciais, sendo o primeiro e o maior no país a oferecer soluções completas ao mercado de controle, otimização e automação de empresas com operações de campo, nas áreas de coleta de resíduos e transporte coletivo.

__Tem o perfil que procuramos?__   
Currículos para: beinlog@inlog.com.br   
Realize um de nossos testes em [github.com/weareinlog](http://github.com/weareinlog)
e venha fazer parte do nosso time   

### Labels: 
CLT, 
Alocado, 
Júnior, Pleno ou Sênior (temos vagas para todos os níveis)

**Comment by guilhermeoa07** [comment]
Senioridade?

**Comment by danielswater** [comment]
Aceita remoto?

**Comment by guilhermeoa07** [comment]
@lidia-freitas tranquilo, as entrevistas podem ser via hangouts?

**Comment by lidia-freitas** [comment]
@guilhermeoa07 pode sim! entre em contato com beinlog@inlog.com.br

**Comment by guilhermeoa07** [comment]
Ok,obrigado, acabei de enviar.

**Comment by matheus-rosin** [comment]
@lidia-freitas vocês tem alguma previsão de dar retorno sobre os testes?

**Comment by lidia-freitas** [comment]
Oi @matheus-rosin , acabei de conversar com o responsável pelo processo. Vão entrar em contato na próxima semana.
