### ISSUE TITLE
[Blumenau/SC] Projetista Front-end - Senior Sistemas

### ISSUE THREAD

**Issue by thaiseduarte** [frontendbr/vagas#111]
## Descrição da vaga

Atribuições e responsabilidades
Este profissional irá projetar soluções, utilizando diagramas e padrões de projeto (design patterns), atendendo requisitos funcionais e não funcionais, dentro do contexto e das restrições da arquitetura (performance, escalabilidade, portabilidade, re-usabilidade, testabilidade, etc.).
## Local

Matriz da empresa em Blumenau/SC
## Benefícios
- Área de convivência integrada com:
  - sala de jogos;
  - área de descanso/leitura;
  - área de refeição/refeitório (fica disponível neste mesmo local uma Vending Machine);
-  Dia da Fruta (disponível quinzenalmente)
- Ginástica Laboral;
- Universidade Corporativa com
  - plataforma EAD disponível gratuitamente 24hrs por dia, 
  - calendário de treinamentos presenciais internos, 
  - biblioteca física 
  - apoio à certificações técnicas de mercado).

Além de:
- Vale Alimentação/Refeição;
- Auxílio Educação (50% da mensalidade);
- Auxílio Creche;
- Plano de Saúde;
- Plano Odontológico;
- Seguro de Vida;
- Vale Transporte;
- Programa de Remuneração Variável (PLR); 
- Plano de Previdência Complementar.
## Requisitos

**Obrigatórios:**
Superior em Ciências da Computação, Sistemas de Informação ou áreas afins. Vivência com programação JavaScript (especificamente AngularJS), Html5, Css3, Crossbrowser e integrações com Web Services (REST).

**Desejáveis:**
Vivência com desenvolvimento mobile nativo (iOS ou Android) e bibliotecas como Ionic, Cordova/PhoneGap e Bootstrap.

**Diferenciais:**
- Vivência com metologias ágeis.
## Contratação

CLT Full Time
## Nossa empresa

Na Senior aplicamos um modelo colaborativo de trabalho. Entendemos que nossos colaboradores precisam participar dos projetos para promover, em conjunto com as lideranças e com as equipes, a evolução da empresa. Por isso, buscamos profissionais que acreditam no que acreditamos. Queremos pessoas positivas, flexíveis, que se adaptam com rapidez a novos cenários e buscam resultados com ética, respeito e trabalho em equipe.
Quer uma prova disso? Na Senior trabalhamos com as portas abertas e com acesso livre para contatar diretores ou o presidente. Trabalhamos com o respeito mútuo e com o conceito de equipe o tempo todo.
Além disso, a empresa trabalha permanentemente com ações colaborativas, acompanhadas por pesquisas de clima e avaliações de desempenho estruturadas.

A POLÍTICA DE GESTÃO DE PESSOAS DA SENIOR.

Trabalhar na Senior é estar num ambiente inovador que, além disso, proporciona qualidade de vida, estimula o crescimento profissional e se preocupa em atender aos anseios individuais e coletivos das pessoas.
Dentro do quadro de cada região, oferecemos benefícios que contribuem para a satisfação e bem-estar dos nossos colaboradores alinhados às práticas locais da atuação dos nossos times.

QUER CRESCER PROFISSIONALMENTE?
Faça parte de um dos muitos programas de desenvolvimento de conhecimento da Senior e outras formas de incentivar negócios na Senior.  Conheça alguns desses programas:
- INOVE SENIOR
  Um programa de aceleração corporativa que oferece aporte, know-how e acesso ao mercado para até 10 startups que demonstrem potencial econômico.
- DESAFIOS DE INOVAÇÃO
  Um evento voltado para o público de Desenvolvimento e Testes que instiga equipes de desenvolvimento e tecnologia da Senior com atividades e palestras sobre o universo de TI e gestão de pessoas.
- PÁGINAS DO FUTURO
  Este programa reúne lideranças e envolve todos os colaboradores com provocações sobre futuro, no intuito de trazer demandas para a construção colaborativa do Planejamento Estratégico da Senior.
- SENIORTEC
  Este programa reúne lideranças e envolve todos os colaboradores com provocações sobre futuro, no intuito de trazer demandas para a construção colaborativa do Planejamento Estratégico da Senior.
## Como se candidatar

Por favor envie um email para recrutamento@senior.com.br com seu CV anexado - enviar no assunto: Vaga Projetista Front-end ou ainda cadastre seu currículo no site da empresa http://www.senior.com.br/senior/trabalhe-conosco/.

**Comment by eduardojmatos** [comment]
Oi @thaiseduarte já preencheu a vaga? Nos avise pra mantermos ou removermos da lista :)
