### ISSUE TITLE
Vaga Júnior

### ISSUE THREAD

**Issue by ascanteiro** [frontendbr/vagas#1114]
Olá, segue os dados:

URL: http://trite-prison.surge.sh/

Nome: Anderson da Silva Canteiro

**Comment by danieladuarteng** [comment]
Esse link leva para compra de uma sandália

**Comment by Pedro-Souza** [comment]
Eu acho que é referente á vaga da #1090

**Comment by chroda** [comment]
Totalmente em desacordo com os padrões.

@fdaciuk @diogomoretti

**Comment by brunokunace** [comment]
Se a vaga depender de conhecimento de git (acho que todas deveriam),  tenho más notícias para este rapaz

**Comment by LFeh** [comment]
As ideia
