### ISSUE TITLE
[Rio de Janeiro - ZS] Estágio Front-end Dev na Whats

### ISSUE THREAD

**Issue by gabrielalmeida** [frontendbr/vagas#1118]
![untitled](https://user-images.githubusercontent.com/310382/41541952-19c8bf76-72ea-11e8-88e7-bfe702bf4187.png)

Procuramos um(a) estagiário(a) Front-end Developer para ajudar a compor a nossa equipe. Somos uma empresa jovem que tem como missão otimizar o relacionamento de grandes marcas com seus consumidores, através de tecnologia e comunicação. Você trabalhará em componentes para clientes como: L'Oréal, Globo, Itaú, Coca-Cola e outros.

Buscamos uma pessoa que tenha uma breve experiência com as tecnologias listadas abaixo e esteja bem interessada em aprender novas soluções.

Acompanharemos e auxiliaremos o desenvolvimento de cada etapa da rotina de trabalho, mas proatividade e autonomia são características importantes que necessitamos na equipe.

As responsabilidades são:

- Trabalhar na criação de componentes web prezando fidelidade aos aspectos gráficos/funcionais
- Consumir APIs para implementação dos componentes
- Trabalhar na entrega de protótipos, POCs
- Buscar seguir boas práticas de desenvolvimento: convenções, guidelines, reviews
- Ter interesse em aprender novas tecnologias, se tornar fullstack
- Ser engajado, somos uma equipe enxuta e todos participam de tomadas de decisões

## Local

Escritório, Jardim Botânico - Rio de Janeiro
Possibilidade de home-office até 2x por semana =)

### Obrigatórios:
Muita vontade de aprender, interesse em interfaces web e em tecnologia. 
Se sentir confortável com HTML/CSS, Javascript & Git

> Be a worker… and be prepared to show it! Everyone is responsible for making awe-something, building product, owning decisions, selling something, hustling. You can’t just show up at the meetings.

### Desejáveis:
- React
- JS ES6 (Promises, Async/await, etc)
- FP
- Linux
- Se sentir confortável em usar CLIs

## Contratação
Estágio

Tipo de vaga: Estágio 4h/6h
Flexibilidade de horário
No dress code
Bolsa: de R$1.000,00 a R$1.300,00 /mês

## Como se candidatar
Envie um email com seu jabá ou CV para contato@whats.ws com assunto `[Vaga Front-end] SeuNome` :D

## Labels
- Alocado
- Estágio

**Comment by Tecoquinho** [comment]
@gabrielalmeida 
Consegue me passar o site da empresa?
Apliquei o currículo e queria dar uma lida sobre a Empresa, mas não consigo achar no Google

**Comment by souzalarissa383** [comment]
A vaga já foi preenchida ???

**Comment by gabrielalmeida** [comment]
Oi, pessoal! Peço desculpas pela demora nas respostas. Seguem:

* O site da empresa é http://whats.ws
* A vaga já foi preenchida

Boa sorte :)
