### ISSUE TITLE
[São Paulo] Desenvolvedor(a) Front-end

### ISSUE THREAD

**Issue by will-soares** [frontendbr/vagas#112]
## Descrição da vaga

Procuramos Desenvolvedor(a) com experiência em aplicações web e mobile baseadas em AngularJS.
Experiência com aplicativos nativos (Android/iOS) é um diferencial muito relevante.

## Local

Av. Paulista, 352, cj 74, Bela Vista, São Paulo, SP (metrô Brigadeiro)

## Benefícios

- Vale-refeição
- Vale-transporte
-  Convênio médico
- Horário flexível

## Requisitos

**Obrigatórios:**
- HTML5/CSS3
- AngularJS
- Pré-processadores CSS
- REST
- Cordova/Phonegap
- Gulp/Grunt
- GIT
- Sketch/Photoshop

**Desejáveis:**
- Angular Material
- Android Studio/Java
- Objective-C
- SMACSS
- BEM
- APIs de Redes Sociais

**Diferenciais:**
Experiência com aplicativos nativos (Android/iOS) é um diferencial muito relevante.

## Contratação

CLT

## Nossa empresa

A Ever é uma produtora digital fundada em 2007 com foco em novas tecnologias.
Mais detalhes: http://www.ever.com.br

## Como se candidatar

Enviar currículo através de: http://trampos.co/oportunidades/127849

**Comment by Mendrone** [comment]
@will-soares marquei como pleno baseado nos requisitos, é isso mesmo?

**Comment by will-soares** [comment]
Correto @Mendrone! Tks

**Comment by eduardojmatos** [comment]
@will-soares já preencheu a vaga? Nos avise pra mantermos ou removermos da lista :)

**Comment by will-soares** [comment]
@eduardojmatos preenchemos sim. Muito obrigado! abs

**Comment by camilatigre** [comment]
@will-soares 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by will-soares** [comment]
@camilatigre Não
