### ISSUE TITLE
[RIO DE JANEIRO] Front-End Developer na MJV Technology & Innovation

### ISSUE THREAD

**Issue by RHRJ** [frontendbr/vagas#1122]
A MJV é uma consultoria global dedicada a transformar negócios por meio da inovação e da tecnologia presente em 6 países e em busca de crescer sempre mais! 

Você pode ver mais sobre a nossa história aqui: https://vimeo.com/269521857/87217f2322

Atualmente, nós estamos com oportunidades para Front e Back End para atuar tanto em projetos quanto em contratações Full.

Requisitos:

- Conhecimento em NodeJS e experiência em Git e uso de CI/CD
- Angular 2 ou mais recente ou Vue
- HTML, Javascript, CSS
- Familiaridade na criação de APIs REST
- Framework CSS: preferencialmente Material Design (Bootstrap é aceitável)

Local: Centro/RJ

Contratação RPA, PJ ou CLT

Interessados enviar CV para rhrj@mjv.com.br

## Labels

- Alocado
- CLT
- Júnior 
- Pleno

**Comment by oliveirajunior90** [comment]
Bom dia a vaga já foi preenchida?

**Comment by CanalCurta** [comment]
Olá @oliveirajunior90. A vaga ainda não foi preenchida.

**Comment by oliveirajunior90** [comment]
Eu enviei um e-mail com CV e repositório na semana passada mas não me retornaram. Como posso me candidatar?
