### ISSUE TITLE
[REMOTO] Full Stack Developer na AVUUL WEB

### ISSUE THREAD

**Issue by ednilsonamaral** [frontendbr/vagas#1124]
## Descrição da vaga

Estou buscando um dev full stack com experiência em Node.js e Vue.js.

- Desenvolver um streaming de vídeos de câmeras de segurança, ao vivo, gravar vídeos, exibir na tela em tempo real, pausar, play, stop, etc..
- Preparar a API em Node.js para isso, para salvar o que for necessário, etc.
- Fazer o front disso em vue.js + nuxt.js

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Node
- 2 anos de experiência com mongodb e express
- 2 anos de experiência com Vue.js

**Desejáveis:**
- Experiência com streaming de vídeos
- Experiência com nuxt.js

**Diferenciais:**
- WebRTC

## Contratação

PJ

## Nossa empresa

Agência focada em desenvolvimento de soluções web e mobile sob demanda

## Como se candidatar

Por favor, envie um email para helpme@avuulweb.com com seu CV anexado e links para portfolio, GitHub e demais projetos que sejam relevantes - enviar no assunto: **Vaga Freela Node + Vue**

**Comment by Carlosxell** [comment]
Apenas PJ ?

**Comment by izanf** [comment]
Faltou a tag de freela

**Comment by vinyguedess** [comment]
Enviado
