### ISSUE TITLE
[São Paulo] Front-End Developer na Doc88

### ISSUE THREAD

**Issue by gtso86** [frontendbr/vagas#1125]
## Descrição da vaga

Desenvolvimento de Sistemas e Plataformas WEB.  Ajudar na construção do desenvolvimento de novas aplicações, desde elaboração, identificação de necessidades, desenho de soluções, priorização em backlog e apresentação para clientes. Participação de reuniões de planejamento. 

## Local

Vila Olímpia (próximo Shopping JK Iguatemi) - São Paulo

## Benefícios

- VT
- VR

## Requisitos

**Obrigatórios:**
- Conhecimentos sólidos em HTML, CSS, JavaScript
- Conhecimentos sólidos em pelo menos 1 framework JS moderno (VueJs, React, Angular, etc) 
- Bootstrap 4

**Desejáveis:**
- Desenvolvimento de SPA / PWA utilizando VueJs
- EcmaScript
- EsLint (AirBnb)
- Experiência em ferramentas de design com Photoshop, Illustrator , Adobe UX  e Sketch
- Utilização de metodologias Ágeis (SCRUM) 

**Diferenciais:**
- Criação de SPA escalável
- Temificação de aplicações (customização de temas pela interface)
- Noções de UX / UI

**Experiências prévias:**
- Experiência em desenvolvimento de plataformas e ferramentas WEB
- Experiência em lidar com todos os níveis de projetos, desde os mais táticos até o mais estratégico.

## Contratação

A combinar

## Nossa empresa

Empresa do segmento de tecnologia com foco em projetos de sistemas Web.

## Como se candidatar

Aos interessados, favor cadastrar-se através do [link](https://metabpo.selecty.com.br/vaga/1932/vaga-para-desenvolvedor-front-end-senior-em-sao-paulo-sp-brasil).

## Labels

- Alocado
- Temporário
- Pleno
- Sênior

**Comment by gtso86** [comment]
Posição ainda disponível

**Comment by gtso86** [comment]
Posição disponível para trabalho remoto

**Comment by Renato66** [comment]
Vaga ainda disponível?
