### ISSUE TITLE
[São Paulo] Front-End Developer na NeoPag

### ISSUE THREAD

**Issue by lucasNeopag** [frontendbr/vagas#1126]
## Descrição da vaga

Projeto full Vue.js

## Local

Escritório, São Paulo - Santana (Zona Norte)

#### Diferenciais

- Horario Alternativo
- Budget para montar sua estação de trabalho
- Frigobar sempre cheio
- Ps4 pra descontrair

## Requisitos

**Obrigatórios:**
- Experiência com Javascript
- Experiência com Vue.js

**Desejáveis:**
- UX e design

## Contratação

PJ a combinar

## Nossa empresa

Somos uma fintech Startup, a primeira do Brasil com a solução de cartões private label digital para lojas. Buscamos pessoas que se alinhem com a nossa cultura e que gostam de novos desafios.

## Como se candidatar

Por favor envie um email para jobs@neopag.com seu CV anexado - enviar no assunto: Vaga Vue.js

## Labels

- Alocado
- PJ
- Pleno
- Sênior

**Comment by Carlosxell** [comment]
apenas PJ ?

**Comment by lucasNeopag** [comment]
Pode ser CLT também



On 20 Jun 2018, at 15:59 , Carlos Augusto <notifications@github.com> wrote:

apenas PJ ?
