### ISSUE TITLE
[Sao Paulo] Front-end Developer na Eicon

### ISSUE THREAD

**Issue by luisfelipealvesmagro** [frontendbr/vagas#1127]
## Descrição da vaga

Desenvolvimento de Sistemas Web.  Ajudar na construção do desenvolvimento de novas aplicações, e manutenção de existentes.

## Local

São Paulo - Sacomã

## Benefícios

Seguro de Vida;        
Auxílio Creche;
Assistência Médica;  
Assist. Odontológica;  
Convênio Farmácia;  
Vale Refeição R$ 25,00 por dia útil;
Vale alimentação R$53,15 mensal sem desconto;
Vale Transporte.      

## Requisitos

**Obrigatórios:**
- Domínio de HTML5 e CSS3 semânticos;
- Pré processadores CSS (SASS / LESS / Stylus);
- Conhecimentos Sólidos em Javascript
- Conhecimentos Sólidos em Angular JS
- Experiência em consumo de API's
- Lógica de Programação
- Experiência em desenvolvimento responsivo e cross-browser;
- Experiência com versionador de código Git;
- Experiência com Gulp / Webpack / NPM
- Frameworks CSS (Bootstrap);

**Diferenciais:**
- Conhecimento em frameworks SPA (Angular 2+ ,React, Vue, Ember e etc..)
- ES6 /Typescript
- UI /UX
- TDD (Teste Unitário)
- Node Js

## Contratação
Contratação CLT

## Como se candidatar

Por favor envie um email para rh@tecnogroup.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

## Labels

- CLT
- Pleno
- Sênior

**Comment by luisfelipealvesmagro** [comment]
@LFeh pode por favor colocar essa issue como closed

**Comment by LFeh** [comment]
Boa!
