### ISSUE TITLE
[Rio de Janeiro] Front-end Developer na Avantare

### ISSUE THREAD

**Issue by dmorier** [frontendbr/vagas#1128]
Você tem habilidades de desenvolvimento PHP e Wordpress, experiência em Java Script  e procura a oportunidade de crescer criando trabalhos relevantes? Seu lugar é na Avantare!

ATIVIDADES:
- Desenvolvimento de temas em Wordpress e PHP para sites e landing pages, HTML5, CSS/CSS 3, JavaScript / JQuery, utilizando boas práticas W3C e design responsivo, através do Bootstrap;
- Codificação JavaScript para tagueamento de sites e landing pages.

PRÉ- REQUISITOS:
- Conhecimento em Wordpress, PHP, HTML5, CSS/CSS3, JavaScript / JQuery e Bootstrap;
- Cursando graduação em Sistemas de informação, Ciência da Computação ou Engenharia da Computação;
- Perfil lógico e analítico;
- Inglês avançado para leitura.

DIFERENCIAIS (OPCIONAIS): 
- Conhecimento sobre SEO, Google Analytics ou Google Tag Manager.

CARACTERÍSTICAS COMPORTAMENTAIS: 
- Organização, comprometimento, proatividade e aprendizado constante.

BENEFÍCIOS:
- Oportunidade de trabalhar diretamente com inovação;
- Ambiente descontraído;
- No dress code (pode trabalhar de bermuda, camiseta etc);
- Crescimento vinculado a resultados;
- Flexibilidade de horário (30h semanais).

Gostou? Envie seu currículo e portfolio para recursoshumanos@avantare.com.br, se possível com projetos que possam ser navegados.

**Comment by glauberm** [comment]
Qual a remuneração?

**Comment by dmorier** [comment]
Bolsa-estágio a partir de R$1.000 + VT.

Abraços,

Daniella Morier
Diretora de Marketing | avantare.com.br
Telefones: (21) 4141-3312 | (21) 97589-1985 | Skype: dmorier

[image: Avantare]
