### ISSUE TITLE
[São Paulo] Desenvolvedor(a) Front-end Pleno

### ISSUE THREAD

**Issue by allangrds** [frontendbr/vagas#113]
## Descrição da vaga
O profissional será responsável pelo front end de uma startup digital no ramo de logística.

## Local
Home office / Presencial(São Paulo,  Pompeia)

## Requisitos

**Obrigatórios:**
- HTML5
- CSS3
- Design Responsivo
- Javascript(+4 anos)
- Teste Unitário
- Teste Funcional
- Front-end package managers (Bower, NPM)
- Task Runners (Grunt ou Gulp)

**Desejáveis:**
- Conhecimentos básicos de Python (Django)
- ES6

## Contratação

PJ a combinar

## Nossa empresa

A CARGOBR é um empresa de tecnologia com foco em desenvolver soluções para a área de transportes e logística. Para saber mais sobre nós acesse https://www.youtube.com/watch?v=SYilGNoTxmM

## Como se candidatar

Enviar email para ti@cargobr.com com seu CV anexado ou portfolio ou perfil do Github - assunto: Vaga Front End.

**Comment by eduardojmatos** [comment]
@allangrds já preencheu a vaga? Nos avise pra mantermos ou removermos da lista :)

**Comment by allangrds** [comment]
Perdão @eduardojmatos. Preenchemos segunda-feira :).

**Comment by camilatigre** [comment]
@allangrds 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by allangrds** [comment]
@camilatigre 
b)
