### ISSUE TITLE
[São Caetano do Sul, SP] Front-end Developer na INSANE

### ISSUE THREAD

**Issue by kvnol** [frontendbr/vagas#1130]
## Descrição da vaga

Trabalhar em construções de sites, hotsites, landing pages e codificação de e-mails marketings para campanhas publicitárias.

## Local

Escritório, São Caetano do Sul - SP

## Requisitos

**Obrigatórios:**
- HTML
- CSS
- JavaScript
- GIT
- E-mail Marketing

**Desejáveis:**
- Senso estético para design
- SASS
- PUG
- MJML (Framework E-mail)
- Blade Template (Laravel)
- Se sentir confortável com CLIs

## Contratação

PJ a combinar

## Nossa empresa

A INSANE é um estúdio de estratégia e comunicação localizada em São Caetano do Sul, nascida através de um fusão entre três agências do ABC paulista.

## Como se candidatar

Por favor envie um email para falaai@sejainsane.com.br e c/c para andre.coimbra@sejainsane.com.br com seu CV anexado - enviar no assunto: `Vaga Front-End Developer`

## Labels

- Alocado
- Júnior
- PJ
- Pleno

**Comment by renanmurilo** [comment]
Enviado.

**Comment by renanlara** [comment]
Como é legal ver em vagas para Júnior exigindo conhecimento em Git. 
Isso me faz lembrar de uma “briga” em que eu e o @omariosouto tivemos com a administração de uma agência para implementarmos o Git nos projetos.

**Comment by kvnol** [comment]
@renanlara Git é essencial, Git é amor :heart:

**Comment by guilhermeoa07** [comment]
Entrevista pode ser via Hangouts?

**Comment by kvnol** [comment]
@guilhermeoa07 não serei eu o entrevistador, sugiro perguntar pelos e-mails.

**Comment by marioleme** [comment]
Enviado..

**Comment by kvnol** [comment]
Vaga foi preenchida, @LFeh. Pode fechar! :smile:
