### ISSUE TITLE
[São Paulo] Front-End Developer na Linx+Neemu+Chaordic

### ISSUE THREAD

**Issue by mauneemu** [frontendbr/vagas#1131]
## Descrição da vaga

Descrição da vaga
Estamos à procura de um(a) desenvolvedor(a) frontend Jr a Pleno que seja pró-ativo, goste de aprender, antenado(a) e apto(a) a manter um sistema utilizado pelas lojas físicas das grandes marcas do varejo.
Você dará suporte, integrará futuros clientes e desenvolverá novas features dos aplicativos.

Aqui estão alguns sinais de que você é um bom match...
Javascript
AngularJs
React
Node.js
Typescript
Webpack
Gulp
Bootstrap
Sass
Service-workers
Desktop e mobile
Git
Consumo de APIs
Scrum

## Local

Alocado em São Paulo - Pinheiros

Processo de seleção:
Currículuns para mauricio.gomes@linx.com.br
Apresentação e entrevistas presenciais e on-line.

Contratação CLT de R$ 4.000,00 a R$ 6.500,00 conforme o perfil + benefícios
Localização: Pinheiros

## Labels

- Alocado
- CLT
- Júnior
- PJ
- Pleno

**Comment by ArtUssuy** [comment]
Não entendi, a vaga é para prestar serviço para essas três empresas?

**Comment by mauneemu** [comment]
Boa Tarde,

A pessoa será contratada pela Linx, a Linx adiquiriu a Neemu e a Chaordic,
estamos num processo de transição de marcas e em breve essas questões de
comunicação serão reformuladas, mas no momento nossa tribo se apresenta
como Linx+Neemu+Chaordic

Admito que também estranhei quando me contrataram, no texto de apresentação
tento passar um pouco desse contexto.

2018-06-22 16:12 GMT-03:00 art <notifications@github.com>:
