### ISSUE TITLE
[Remoto][Alemanha] Senior Front-End Developer na Picter

### ISSUE THREAD

**Issue by lcsrinaldi** [frontendbr/vagas#1132]
## Descrição da vaga

Fala galera, estamos à procura de mais desenvolvedores para o nosso time. 
A vaga é para remoto e a empresa é na Alemanha. 

- [Senior Full-Stack Developer (React / Node.js)](https://picter-jobs.personio.de/job/81428)
- [Senior Node.js Developer](https://picter-jobs.personio.de/job/38640)
- [Senior React Developer](https://picter-jobs.personio.de/job/38631)

## Local

Remoto

## Como se candidatar

Escolha a posição e aplique-se:

- [Senior Full-Stack Developer (React / Node.js)](https://picter-jobs.personio.de/job/81428)
- [Senior Node.js Developer](https://picter-jobs.personio.de/job/38640)
- [Senior React Developer](https://picter-jobs.personio.de/job/38631)

## Labels

- PJ
- Remoto - Total
- Sênior

**Comment by matheus-lima92** [comment]
Tenho interesse, como faço para me candidatar?

**Comment by lcsrinaldi** [comment]
Olá @matheus-lima92 , pode se aplicar por um dos links que estão na descrição da vaga. E adicionei a seção como se candidatar novamente.

**Comment by lcsrinaldi** [comment]
Contratado.
