### ISSUE TITLE
[São Paulo] Front-End Sr Developer na BEYOND 

### ISSUE THREAD

**Issue by FrancieleMarcaDaRosa** [frontendbr/vagas#1134]
Descrição da vaga
Vaga para atuar alocado em cliente, do ramo financeiro/investimentos.

Local
São Paulo - Faria Lima (Zona Sul)

Obrigatórios:
HTML5 / SASS / LESS / CSS3 / ANGULAR 5/6 ou REACT c/ REDUX

Contratação:

CLT FULL + benefícios

Como se candidatar
Por favor envie um email para franciele@imaginebeyond.com.br seu CV anexado - enviar no assunto: Vaga Frontend Sr

**Comment by LFeh** [comment]
@FrancieleMarcaDaRosa A vaga está fora dos padrões, favor seguir [esse template](https://github.com/frontendbr/vagas/blob/master/.github/issue_template.md)
