### ISSUE TITLE
[São Paulo] GSN - Front End  Developer  

### ISSUE THREAD

**Issue by GabrielaGSN** [frontendbr/vagas#1139]
## Descrição da vaga

Estamos em busca de profissionais que realizem a concepção e implementação de telas. O objetivo é realizar o entendimento e desenvolvimento dos produtos dos nossos clientes.
Responsabilidades
Participar das cerimônias ( Sprint Planning, Daily Meeting, Sprint Review e Retrospectiva ).
Ajudar no entendimento do que deve ser desenvolvido.
Realizar uma documentação prévia das suas tarefas, garantindo o planejamento.
Realizar o desenvolvimento utilizando técnicas como TDD e BDD.
Utilizar as melhores práticas de desenvolvimento e Design Patterns.
Se preocupar com a qualidade dos entregáveis
Comprometimento com as entregas em equipe.
Ajudar no review da tarefa de outros integrantes da equipe.
Levantar os problemas encontrados durante o processo de desenvolvimento, formalizando os impedimentos.
Compartilhar o conhecimento.
Sugerir melhorias no processo de trabalho.
Tratar o cliente e o colega de trabalho com cordialidade e ética.
Participar e promover os treinamentos visando o crescimento da equipe.

## Local

Escritório, São Paulo - Paraiso

## Benefícios

- 890 ajuda de custo
- .

#### Diferenciais

Ambiente Descontraído
Treinamentos
Oportunidade de Aprendizado
Palestras e Eventos
Trabalho em Equipe
Projetos de Relevância
Escritório e Notebooks de Qualidade
Tecnologia de Ponta
Desafios
Reconhecimento
Processo de Trabalho Ágil
Equipe Internacional
Opções de Horários de Trabalho
Massagem
Lounge & Vídeo Game
Frigobar
Cozinha

## Requisitos
Experiência profissional de 2 anos com GIT
Experiência profissional de 2 anos com Javascript
Experiência profissional de 2 anos com HTML/CSS

**Obrigatórios:**
Experiência profissional de 2 anos com GIT
Experiência profissional de 2 anos com Javascript
Experiência profissional de 2 anos com HTML/CSS

**Desejáveis:**
Angular 5
EmberJS
React
NodeJS
Modelagem de Serviço ( Rest )

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para gabriela.vaccari@gsn.com.br com seu CV anexado - enviar no assunto: Vaga Front End (Paraiso)

## Labels

- PJ
- Pleno
- Sênior

**Comment by diogomoretti** [comment]
Olá @GabrielaGSN, o profissional irá trabalhar na própria GSN ou para algum cliente de vocês?

**Comment by pedrocss** [comment]
bem parecida essa vaga ae com essa daqui: https://jobs.lever.co/sciensa/e1edce42-a617-4c1c-b887-76d9ea829115

bem legal essa discussão no twitter também: https://twitter.com/mlucas1909/status/1012090962003349510

Acho que seria legal questionarmos um pouco as vagas que tão rolando aqui no forum, tem vaga que chega a ser um desrespeito com a nossa profissão.

**Comment by LFeh** [comment]
@pedrocss A gente tenta moderar pra manter a qualidade, mas de fato fica complicado em alguns casos :(

**Comment by pedrocss** [comment]
@LFeh Totalmente compreensível, moderar não deve ser uma tarefa nada fácil. O trabalho de questionar as vagas deve ser feito por toda a comunidade.

Só acho que ficou feião pra empresa esse tipo de atitude.
