### ISSUE TITLE
[São Paulo] Front-end Developer @ Pagar.me

### ISSUE THREAD

**Issue by grvcoelho** [frontendbr/vagas#114]
## Descrição da vaga

O Pagar.me é uma empresa de tecnologia que nasceu em 2013 e hoje ajuda centenas de outras empresas a receber pagamentos pela internet. Estamos em um mercado promissor que cresce 20% ao ano – nosso time está criando o que em breve será a maior empresa de pagamentos do Brasil. 

Se você quer saber um pouquinho mais sobre o que fazemos aqui no Pagar.me e como é trabalhar aqui, veja este vídeo do nosso PO (@filipedeschamps) falando sobre a empresa. Segue link: https://youtu.be/4Lldk5EdC5s!
## Local

Nosso escritório é em São Paulo capital, na Rua Dr. Geraldo Campos Moreira, 240 - Cidade Monções (5 minutos da estação Berrini).
## Benefícios

Além de todos os beneficios normais como VR, VT plano de saúde e afins, temos aqui um dos melhores times de desenvolvimento do Brasil, com uma cultura forte de tecnologia: buscamos a inovaçao, valorizando a autonomia e os desafios de cada um!

Somos uma equipe com o pé no acelerador, e temos espaço infinito para quem quer aprender e crescer com a gente :)
#### Obrigatórios:
- HTML (semântica, acessibilidade)
- CSS (preprocessadores, postcss, arquitetura, etc)
- Javascript / ES2015 (Modules, Design Patterns, Async)
- AngularJS 1.x
- Gostar **muito** de aprender
#### Diferenciais:
- Arquitetura de grandes aplicações
- Conhecimento em testes (TDD, unit, e2e)
- AngularJS e/ou Node.js;
#### Interessantes:
- Interesse por Open-source
- Interesse por UX
- Interesse por Computer Science (programação funcional, complexidade, etc)
## Contratação

CLT (full-time)
## Como se candidatar

Envie email para venhapara@pagar.me com exatamente o título `Github | Front-end Developer`, com suas informações (cv, linkedin, github, site, etc)

**Comment by grvcoelho** [comment]
labels: 
- `Alocado`, 
- `CLT`, 
- `Pleno`, 
- `Sênior`

:smile:

**Comment by felquis** [comment]
:dancer:

**Comment by vitorabner** [comment]
:dancers:

**Comment by kvnol** [comment]
Se tivesse chance para jr eu ia nessa vaga.

**Comment by grvcoelho** [comment]
@kvnol: manda email mesmo assim, vamos bater um papo :)

**Comment by filipedeschamps** [comment]
Na lista de benefícios tem que colocar "Trabalhar com o @grvcoelho " 👍  👍  👍

**Comment by marcelinhov2** [comment]
Ótima vaga

**Comment by acacioosorio** [comment]
Ótima vaga, pena que a localização é ruim pra mim
:(

**Comment by LFeh** [comment]
@felquis <3

**Comment by aleDsz** [comment]
Se eu tivesse chance, eu iria nessa vaga hahahaha

**Comment by jvcjunior** [comment]
Vaga show!!! Fosse Home-office!! Estaria dentro!!

**Comment by eduardojmatos** [comment]
@grvcoelho opa, já preencheram a vaga? Nos avise pra mantermos ou removermos da lista :)

**Comment by eduardojmatos** [comment]
@grvcoelho boa! Melhor manter então hehehe
