### ISSUE TITLE
[Sao Paulo] Front-end Developer na Raised

### ISSUE THREAD

**Issue by jribeirojr** [frontendbr/vagas#1142]
## **VAGA**

Nova Oportunidade - Desenvolvimento de Sistemas Web.  Ajudar na construção do desenvolvimento de novas aplicações, e manutenção de existentes.

## **ATIVIDADES:**

Desenvolvimento de temas em Wordpress e PHP para sites e landing pages, HTML5, CSS/CSS 3, JavaScript / JQuery, utilizando boas práticas W3C e design responsivo, através do Bootstrap;
Codificação JavaScript para tagueamento de sites e landing pages.

##  **LOCAL**

Escritório, São Paulo - Mooca

##  **BENEFÍCIOS**

- Vale Transporte
- Vale Refeição
- 

##  **REQUISITOS**

- JavaScript
- HTML5
- CSS3
- WordPress
- Lógica de Programação
- Frameworks CSS (Bootstrap)

##  **DIFERENCIAIS**

- PHP
- MYSQL
- SASS
- Git/BitBucket
- Google APIs
- SEO
- Google Analytics ou Google Tag Manager

## **CARACTERÍSTICAS COMPORTAMENTAIS:**

Organização, comprometimento, proatividade e aprendizado constante.

##  **COMO SE CANDIDATAR**

Por favor envie um email para contato@raised.com.br com seu CV anexado - enviar no assunto: Vaga Front End Developer

## Labels

- Estágio
- Júnior

**Comment by vinirossi** [comment]
vaga em aberto ainda? @jribeirojr
