### ISSUE TITLE
[Rio de Janeiro] Estágio de Front-End Developer no [CANAL CURTA!]

### ISSUE THREAD

**Issue by CanalCurta** [frontendbr/vagas#1143]
Empresa de midia dona do canal Curta! (NET / ClaroTV canal 556; OiTV canal 75), da nova plataforma de VOD  [Tamanduá](tamandua.tv.br) e varios outros portais: [Canal Curta!](canalcurta.tv.br), [Portacurtas](Portacurtas.org.br), [Curtanaescola](Curtanaescola.org.br) e [Sabertv](Sabertv.com.br) seleciona estagiário de Back-End. 

**Local**:  Rio de Janeiro, Leblon (próximo a estação metrô)

**Benefícios**:
• Bolsa estágio + VT
• Horário de trabalho flexível
• Um ambiente de trabalho diferente e inovador, com uma cultura que valoriza as pessoas e a entrega de resultados
• No dress code

**Requisitos Obrigatórios:**
HTML5, CSS, JQuery, MediaQueries, Javascript e Vue.JS.

**Requisitos Desejáveis:**
Experiência com Sistemas Web / SaaS, razoável conhecimento de Back-End (para melhor iteração entre as partes) e testes unitários

 
Envie um e-mail para contato@canalcurta.tv.br com o seguinte título e informações:
• Assunto [Estágio de Back-End] 
• Currículo e/ou LinkedIn
• GitHub e/ou Blog - Vai nos ajudar a conhecer você e seu trabalho melhor.

**Comment by mauriciolsrj** [comment]
@costaleonardo para estágio no momento não.
