### ISSUE TITLE
[Rio de Janeiro] Front-End Developer na Spot

### ISSUE THREAD

**Issue by gitsejaspot** [frontendbr/vagas#1144]
## Descrição da vaga
O Clube de Vantagens Spot está a procura de desenvolvedor para contribuir na criação e manutenção de diversos sistemas que estão sendo criados para suportar o constante crescimento da empresa.

## Local
Escritório, Botafogo - RJ

## Benefícios
* Vale Transporte
* Vale Refeição
* Plano de Saúde

## Requisitos
**Obrigatórios:**
* HTML
* CSS
* JavaScript
* Familiaridade com Angular 1

**Desejáveis:**
* SASS
* Ionic
* GIT

## Contratação
CLT

## Como se candidatar
Envie seu currículo para o e-mail vemprotime@sejaspot.com.br com ''Vaga Front-End'' no assunto.

## Labels
- Alocado
- CLT
- Júnior

**Comment by GiovanniSM20** [comment]
Aceita remoto ?

**Comment by gitsejaspot** [comment]
Não, apenas presencial mesmo.

Att,

<http://www.sejaspot.com.br/>
Rafael Kaustchr
rafael.kaustchr@sejaspot.com.br
(21) 99797-6456
*www.sejaspot.com.br* <http://www.sejaspot.com.br/>


2018-07-04 6:38 GMT-03:00 Martins Giovanni <notifications@github.com>:

**Comment by gitsejaspot** [comment]
Não, apenas presencial mesmo.

Att

**Comment by thiagocruzrj** [comment]
Currículo enviado !

**Comment by amarcelaxs** [comment]
Currículo enviado  :)
