### ISSUE TITLE
[São Paulo] Front-End Developer na LIZA

### ISSUE THREAD

**Issue by paolamunaro** [frontendbr/vagas#1146]
## Descrição da vaga
Oportunidade profissional única para desenvolvedores que tenham realmente espírito empreendedor, e que queiram construir do zero um projeto inovador e disruptivo. Se você sonha grande, quer desafios e faz a diferença, junte-se a nós.

- Construção de toda a interface do usuário com a plataforma (Iniciando pelo MVP)
- Atuar na evolução da arquitetura e dos componentes do sistema
- Compromisso em produzir código bem estruturado, testado e escalável

## Local

Remoto ou Escritório, São Paulo - Vila Madalena

## Benefícios

A negociar 

#### Diferenciais

- flexibilidade de horário
- fácil acesso ao metrô (ao lado do Fradique)
- ambiente harmonioso 

## Requisitos

**Obrigatórios:**
- HTML5, CSS, Javascript
- GitHub
- React JS

**Desejáveis:**
- HTML5, CSS, Javascript
- GitHub
- React JS

**Diferenciais:**
- Angular JS ou outros frameworks
- Experiência com design responsivo

## Contratação

PJ a combinar

## Nossa empresa

LIZA - PLATAFORMA DE CADASTRO QUE PERMITE A CONEXÃO ENTRE EMPRESAS, ALÉM DE GESTÃO E GOVERNANÇA DE INFORMAÇÕES E DOCUMENTOS.

## Como se candidatar

Por favor envie um email para paola.munaro@lizaid.com com seu CV anexado - enviar no assunto: Vaga LIZA Frontend

## Labels

- Alocado
- Júnior
- PJ
- Pleno
- Remoto - Parcial
- Sênior

**Comment by LFeh** [comment]
A vaga ficou toda cortada, titulo e descrição

**Comment by paolamunaro** [comment]
Consertei. Agora foi?

**Comment by vinyguedess** [comment]
Como funciona o remoto parcial ?

**Comment by vinyguedess** [comment]
Enviado
