### ISSUE TITLE
[São Paulo] Desenvolvedor Front-End | EcoStage

### ISSUE THREAD

**Issue by mpivaa** [frontendbr/vagas#115]
## Descrição da vaga

Buscamos desenvolvedores apaixonados por tecnologia e trabalhar com o que há de melhor, pessoas que queiram crescer e aprender com a gente.
Temos um time de alto nível, nosso stack é moderno e está sempre em constante evolução.

## Local

Pinheiros - São Paulo ou Guarulhos

## Benefícios

- Horários flexíveis e home office
- Ambiente aberto e em constante evolução
- Time de alto nível
- Valorizamos o desempenho e comprometimento da equipe

## Requisitos

- Experiência com desenvolvimento Javascript
- React / Redux
- CSS / PostCSS / CSS Modules
- TDD
- Ser comprometido com o projeto e qualidade do código.

**Desejáveis:**

- UX / UI
- Functional & Reactive Programming
- Experiência com times auto-gerenciáveis e metodologias ágeis(XP, SCRUM, Kanban, Lean).

**Diferenciais:**
- Participar da comunidade open source

## Contratação

A combinar

## Nossa empresa

A EcoStage é líder no desenvolvimento de plataformas sócio-ambientais. Nossos projetos têm grande impacto em políticas e estratégias sobre o tema.

Somos uma empresa com ambiente descontraído e horários flexíveis. Você trabalhará em uma equipe pequena, multi-disciplinar e auto-gerenciável.

[Ver mais](http://www.ecostage.com.br)

## Como se candidatar

Acha que se encaixa na nossa vaga? Envie um email para jobs@ecostage.com.br com cv / linkedin / github e o escritório com disponibilidade.

**Comment by mpivaa** [comment]
labels: Alocado, Senior, Pleno

**Comment by willianjusten** [comment]
Boa sorte =D

**Comment by LFeh** [comment]
Bela vaga ;)

Boa sorte.

**Comment by mpivaa** [comment]
Obrigado!

**Comment by camilatigre** [comment]
@mpivaa 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
