### ISSUE TITLE
[Porto Alegre] Mobile Developer (Ionic / React Native) na T-Health

### ISSUE THREAD

**Issue by kveber** [frontendbr/vagas#1150]
## Descrição da vaga
Desenvolvedor Mobile com experiência em HTML, CSS, Javascript e frameworks como Ionic, React Native, etc.

## Local
Porto Alegre - RS

## Requisitos
- HTML
- JavaScript
- CSS
- Frameworks hibridos como **Ionic** e **React Native**.

**Desejáveis:**
- processo de publicação de aplicativos na Play Store e App Store.

## Contratação
PJ ou Cooperativa.

## Nossa empresa
A T-Health é uma empresa de serviços especializados para o Segmento de Saúde, desde consultoria de processos, negócio e técnico até desenvolvimento e implantação de soluções.

## Como se candidatar
Envie um email para klaus.veber@thealth.com.br incluindo seu CV anexado - enviar no assunto: Vaga Mobile

## Labels
- Pleno
- Mobile
-  Ionic
- React Native

**Comment by GiovanniSM20** [comment]
Aceitam remoto ?

**Comment by ifragas** [comment]
Possibilidade de remoto para cidade a 100 km de POA ?

**Comment by kveber** [comment]
Não, somente inloco.

Klaus Veber
+55 (51) 99688.7982

**Comment by kveber** [comment]
Não, somente inloco.

Klaus Veber
+55 (51) 99688.7982


Klaus Veber
+55 (51) 99688.7982
