### ISSUE TITLE
[REMOTO][AUSTRALIA]: Front-End Developer na Krint (Jr, Pleno e Sr.)

### ISSUE THREAD

**Issue by cironunes** [frontendbr/vagas#1157]
## Descrição da vaga

Nos somos a Krint, uma empresa de desenvolvimento web e treinamento.
Nossa maior cliente é uma FinTech que atende as maiores empresas da Austrália em diferentes seguimentos:
- Alimentação
- Finanças
- Saúde
- Telefonia

Estamos montando um time de Frontend para atender as demandas da empresa. 
Procuramos os melhores profissionais brasileiros com possibilidade de patrocínio de visto para Austrália.

Além disso, estamos desenvolvendo nossos produtos. Nosso carro-chefe é um marketplace de treinamento focado em desenvolvimento web, baseado em gamificação.

Nós usamos principalmente VueJS e Angular, mas acreditamos que nos limitar a um framework/lib
limita a nossa criatividade. Outras tecnologias que gostamos são:
- TypeScript
- RxJS
- React
- NodeJS
- Golang

## Local

Remoto com possibilidade de patrocínio de visto para Austrália 🇦🇺

#### Diferenciais

- Trabalho remote encorajado
- Horários flexíveis
- Projetos desafiadores e inovadores
- Equipe qualificada (mentoria e treinamento de experts, oportunidade para aprender)
- Foco em qualidade de código
- Salários acima da média
**Junior:** R$2300,00 - R$3400,00
**Pleno:** R$5700,00 - R$10.000,00
**Senior:** R$11500.00 - R$15.000,00

## Requisitos

**Obrigatórios:**
- 2+ anos de experiência com HTML/CSS 
- 2+ anos de experiência com JavaScript
- 1+ anos de experiência com frameworks JS (Angular, Vue, React ou similares)
- Inglês técnico
- Git
- NodeJS
- Capacidade de trabalhar em times ágeis
- Saber implementar testes unitários e e2e
- Markdown

**Desejáveis:**

- Capacidade de trabalhar com TDD (Test-driven development)
- Saber fazer pair programming remotamente
- Conhecimento em arquiteturas serverless
- Conhecimento em Golang
- Familiaridade com Slack, Jira e Confluence

**Diferenciais:**

- Contribuições open source
- Palestras
- Treinamentos

## Contratação

Somente PJ com possibilidade de contratação

## Como se candidatar

Caso tenha interesse, favor enviar para patricia@krint.io:
- CV ou LinkedIn
- GitHub
- Twitter
- Site
- Projetos que contribuiu
- Nível (junior, pleno ou senior)
- Possível data de início

## Labels

- Alocado
- Júnior
- PJ
- Pleno
- Remoto - Parcial
- Remoto - Total
- Sênior

**Comment by danielswater** [comment]
Enviado :)

**Comment by saulocavalieri** [comment]
Enviado, Ciro.

**Comment by pineladsn** [comment]
@cironunes, enviado

**Comment by danjorge** [comment]
Enviado!

**Comment by marcelocesar** [comment]
@cironunes, enviado!

**Comment by dap1995** [comment]
@cironunes, enviado!

**Comment by randhson** [comment]
enviado.

Randson N. dos S. França +55 79 99843 9878+55 79 99138 7628 

    Em quinta-feira, 5 de julho de 2018 16:01:34 BRT, Daniel André da Silva <notifications@github.com> escreveu:  
 
 
@cironunes, enviado!

**Comment by thismarcoantonio** [comment]
Vi essa vaga no LinkedIn, achei muito muito maneiro, gostaria muito de aplicar, mas infelizmente no momento n dá :/

**Comment by EdipoNascimento** [comment]
@cironunes,

Já que não possuo experiência comprovada em desenvolvimento, tem oportunidade para Q.A?

**Comment by vinyguedess** [comment]
Enviado

**Comment by igorjsantos** [comment]
@cironunes email enviado!
Ttenho disponibilidade para início imediato.
https://www.linkedin.com/in/igorjosesantos

**Comment by wchad** [comment]
Enviado

Em qui, 5 de jul de 2018 às 02:31, Ciro Nunes <notifications@github.com>
escreveu:

**Comment by tiagocarmosantos** [comment]
Enviado!

**Comment by cironunes** [comment]
Obrigado a todos que participaram do nosso processo. Vamos fechar a issue por enquanto, já que preenchemos todas as vagas disponíveis no momento.

Quem já aplicou para vaga pode ter certeza que vai receber uma resposta por mais que demore um pouco (afinal, foram centenas de aplicações).

Em breve voltaremos com mais oportunidades.

Abraços,
Ciro 🤗
