### ISSUE TITLE
Front-End Developer na OSF Global Services

### ISSUE THREAD

**Issue by LeonardoGomesRibeiro** [frontendbr/vagas#1158]
FRONT-END DEVELOPER

**Description**
**Responsibilities:**
Build, validate and maintain web page templates from supplied PSD or wireframe layouts using clean, lightweight, semantic code that adheres to current Web Standards.
Write cross-browser HTML and CSS.
Support and enforce best practices for content layout, navigation and site architecture for a simple to complex web applications or websites.
Work closely with very qualified and motivated back-end developers, analysts, architects and managers.
Apply company tailored working procedures on daily basis
Keep up to date with the latest web technologies in the fields of web design, usability, mobile, email and social media application design.
Develop expert level knowledge about web & mobile front-end development standards and platforms, performance and user experience & share it with the team.

**Requirements:**
Working knowledge of XHTML/HTML and CSS.
Knowledge of HTML5, CSS3 and JavaScript
Proficient with Photoshop (PSD2HTML).
Working knowledge of responsive design.
Strong understanding of internet technology, web design and usability, web semantics, online advertising and related business models.
Knowledge of jQuery. Experience with any popular jQuery plug-in (jQuery UI, jQuery tools, jQuery Mobile, etc.) is a plus.
Fluency in English.
Considered to be a plus:
Knowledge of popular CSS grid systems (Bootstrap, 960gs, Skeleton, etc...).
Knowledge of CSS pre-processors (LESS, Sass)
Ability to improve, optimize, extend jQuery plugins, or write them from scratch.
Vanilla JavaScript. Any MV* framework (Backbone, Angular, Knockout, etc...);
Knowledge of version control systems.

Email to:
leonardo.ribeiro@osf-commerce.com

**Comment by costaleonardo** [comment]
Remoto ou presencial ?

**Comment by LeonardoGomesRibeiro** [comment]
Pode ser os dois casos vai depender da entrevista, por isso não coloquei essa informação.
Tem pessoas que trabalham remotamente e outras não então nao tenho como dizer isso.

**Comment by hmilena** [comment]
@LeonardoGomesRibeiro nenhuma notícia?
