### ISSUE TITLE
[CURITIBA] Front-End Pleno [EADBOX]

### ISSUE THREAD

**Issue by RafaeleEADBOX** [frontendbr/vagas#1159]
Sobre a EADBOX:

EADBOX é uma startup que cresceu 130% no último ano, e que está revolucionando o mercado da educação e treinamentos corporativos por meio de um software utilizado para criação e distribuição de cursos online. 

A empresa cresce rápido, milhares de novos alunos todos os meses, com mais de 800 clientes entre autores e grandes empresas como Ache, Totvs, Renault, WiseUp, Heineken. Num forte processo de crescimento no Brasil, México, Argentina e Colômbia.

Começamos 2018 com 108 pessoas e queremos acabar o ano com mais de 267 pessoas entusiasmadas e comprometidas com um propósito: ser uma grande empresa e transformar a eduacação global.

Buscamos desenvolvedores para atuar no desenvolvimento de aplicações web para trabalho **presencial ou remoto**

**Requisitos:**

* Facilidade de trabalhar em equipe;
* conhecimentos em controle de versão (git);
* Sólidos conhecimentos em HTML, CSS e javascript;
* Experiência no desenvolvimento de aplicações com Angular 2+;
* Experiência quanto ao consumo de Web Api;
* Experiência com o padrão JsonApi (opcional).

**Benefícios e diferenciais:**

•    Vale Transporte 
•    Vale Refeição  
•    Plano de saúde
•   Seguro de vida
•    Equipe comprometida e muito empolgada
•    Ambiente dinâmico e inovador

Interessados podem se candidatar pelo link [https://hipsters.jobs/job/2864/desenvolvedor-front-end/], dúvidas enviar para rafaele.bastian@eadbox.com

 Labels

- CLT
- Pleno
- Presencial
- Remoto - Total
- Angular

**Comment by costaleonardo** [comment]
Boa tarde. Ao entrar no link, acabo recebendo um 404.

**Comment by RafaeleEADBOX** [comment]
@costaleonardo link atualizado! obrigada por avisar :)
