### ISSUE TITLE
[São Paulo] Front-End Developer na MeZA

### ISSUE THREAD

**Issue by ticoscatena** [frontendbr/vagas#1162]
Pessoal, estamos precisando de um Front-End Developer Programador, para trabalho alocado / part-time de 1 semana na agência.

Conhecimentos em HTML5, CSS e Javascript.

A agência fica perto do Metrô Oscar Freire.

Favor enviar GitHub/Portfólio para: vagas@meza1618.com.br, com o assunto: Programador FrontEnd Freela.

**Comment by davidalves1** [comment]
Possibilidade do job ser remoto?

**Comment by ticoscatena** [comment]
Oi David,
Nos temos preferência por ser alocado, pois facilitaria o trabalho estar com a pessoa que vai coordenar o projeto.
