### ISSUE TITLE
[Porto Alegre] React developer sênior remoto (react, redux, testes unitários, HTML e CSS) na Grifo

### ISSUE THREAD

**Issue by renatho** [frontendbr/vagas#1165]
## Descrição da vaga

Oportunidade para trabalhar, totalmente remoto, em um produto bem bacana com a stack em cima de React e Redux, criando novas features e evoluindo o produto. Code review ao final de todas features, sempre buscando a evolução do projeto e do dev.

## Local

Full remoto. Se estiver em Porto Alegre ou proximidades é melhor por podermos fazer reuniões presenciais quando necessário. A sede da Grifo fica em Porto alegre.

## Benefícios

- Pagamento no PJ com $$$ bem atrativo como teto.

#### Diferenciais

- Trabalho totalmente remoto
- Faça o horário que preferir (só precisa ter responsabilidade e comprometimento)

## Requisitos

**Obrigatórios:**
- Responsabilidade
- Compromisso
- Domínio de React, Redux
- Domínio de HTML e CSS
- Domínio de Git
- Trabalhar com testes unitários (se já trabalhar com Jest, melhor)

**Desejáveis:**
- Inglês

**Diferenciais:**
- Node.js
- Devops
- Residir em Porto Alegre

## Contratação

PJ a combinar

## Nossa empresa

A Grifo é uma empresa que presta serviços de tecnologia, com foco principal em desenvolvimento front-end.

## Como se candidatar

Por favor envie um email para vagas@gri.fo com sua apresentação - enviar no assunto: [FrontendBR] Vaga React + Redux.
Enviar no e-mail materiais para avaliarmos seus skills. Caso não tenha nenhum material publicado, não tem problema. Verificamos juntos uma forma de avaliar seus skills.

## Labels

- PJ
- Remoto - Total
- Sênior

**Comment by mja-maia** [comment]
Oi @renatho , acabei de enviar o CV!

**Comment by renatho** [comment]
Legal @mja-maia! Recebemos aqui e logo mais te retornaremos!! \o/

**Comment by calebearruda** [comment]
Oi @renatho , estou enviando o CV para vocês. Abraço!

**Comment by chroda** [comment]
Ainda aberto?

**Comment by renatho** [comment]
Oi @chroda!
Ainda aberto sim ;)

**Comment by chroda** [comment]
Enviado :)
