### ISSUE TITLE
[Recife/PE] Front-End Developer Pleno/Sênior - (NodeJS, Angular/React, IA/ML) - e3 Labs

### ISSUE THREAD

**Issue by andregomesoliveira** [frontendbr/vagas#1168]
## Descrição da vaga

Vaga para dev front-end, execução de projeto de automação utilizando inteligência artificial (machine learning).

## Local

Recife/PE, com execuções inloco com a IBM em São Paulo.

#### Diferenciais

- Horário flexível
- Note fornecido pela empresa
- Operação inicial em coworking

## Requisitos

**Obrigatórios:**
- 2+ anos de experiência com desenvolvimento web frontend
- Conhecimento intermediário em NodeJS, incluindo frameworks modernos como React ou Angular
- Experiência com times de desenvolvimento
- Conhecimento nas Metodologias Ágeis
- Disponibilidade para Viagens

**Desejáveis:**
- Angular avançado
- React intermediário
- Conhecimento anterior com projetos usando Inteligência Artificial/Machine Learning como IBM Watson, MindMeld, Google AI

## Contratação

CLT, salário compatível com o mercado.

## Nossa empresa

Somos uma empresa de tecnologia focada em soluções web inovadoras relevantes para o mercado que atuamos. Nosso diferencial é o foco em automação e inteligência de negócios, do backend ao UX, com laboratórios incubados em empresas reais para validação dos nossos produtos.

## Como se candidatar

Por favor envie um email para andre.oliveira@e3labs.com.br com seu CV anexado e LinkedIn.

## Labels

- Alocado
- CLT
- Pleno
- Sênior

**Comment by dtfialho** [comment]
Ao enviar o e-mail está retornando uma mensagem dizendo que o domínio não existe.

**Comment by WandersonAlves** [comment]
Que bacana ver esse tipo de vaga para Recife!

**Comment by andregomesoliveira** [comment]
@dtfialho Favor enviar também para andre.oliveira@pneubras.com

Estamos checando o motivo do erro. Abraço!

**Comment by andregomesoliveira** [comment]
Obrigado a todos que enviaram os emails! As duas vagas já foram preenchidas!
