### ISSUE TITLE
[Belo Horizonte] Vue.js Developer na DialHost

### ISSUE THREAD

**Issue by flaviohcardoso** [frontendbr/vagas#1170]
## Descrição da vaga

Se você é um desenvolvedor faminto por desenvolver e otimizar produtos em um processo de ciclo contínuo e evolutivo, esta pode ser sua equipe.

Nós somos uma empresa que presa a evolução dos nossos produtos juntamente com um atendimento eficaz a todos os nossos clientes oferecendo soluções de datacenter que atendam suas necessidades de forma simples e transparente. Por isto estamos buscando um desenvolvedor que possua empatia e comprometimento para auxiliar nossos colaboradores e clientes discutindo e buscando as melhores opções para garantir uma experiência excepcional no atendimento ao cliente. 

Acreditamos que em nosso time, você não trabalhará sozinho e que um problema nunca é somente de um colaborador, ele é de todos da empresa.

## Local

Escritorio em Belo Horizonte, Bairro California

## Benefícios

Não ter chefe :)
Uma equipe de alto nível, comprometidas e colaborativa.
Salário compatível com o mercado.
Plano de Saúde.
Vale Refeição.
Vale Transporte.
Lanche na empresa.
Ambiente agradável.
Horário Flexível.
Estilo próprio para trabalhar.
Auxilio para pagar sua faculdade.
Diversos cursos online disponibilizados pela empresa.

## Requisitos

- HTML5, CSS3 (SASS) e JavaScript Intermediário para Avançado;
- Frameworks frontend (Vue.JS);
- Experiência com utilização do Git;
- Conhecimento basico em PHP;
- Ser focado em objetivos e resultados.
- Proatividade e dinamismo ;)
- Ter carinho e ser apaixonado pelo seu trabalho.

**Para esta vaga iremos aplicar um teste simples e prático para que você possa demonstrar suas qualidades.**

## Contratação

CLT

## Como se candidatar

http://jobs.dialhost.com.br/o/frontend-developer-belo-horizonte

## Labels

- CLT
- Estágio
- Júnior
- Pleno
- Sênior

**Comment by matheus-rosin** [comment]
remoto?

**Comment by flaviohcardoso** [comment]
@matheus-rosin só presencial

**Comment by macedojr3** [comment]
Boa tarde, @flaviohcardoso...
Haverá resposta para os que já realizaram o teste? Porque o candidato se submeter a fazer o teste e dedicar tempo nisso pra não ter nenhuma resposta é meio triste...

**Comment by flaviohcardoso** [comment]
Ola @macedojr3 , em todas as fases de nosso processo você tem um feedback.
Sabemos que o tempo é valioso tanto para você como para nós, então respeitamos os nossos candidatos que utilizam do seu valioso tempo para fazer o nosso teste.

**Comment by macedojr3** [comment]
Estranho, @flaviohcardoso... hoje faz 23 dias que lhe entreguei o teste... =)

**Comment by flaviohcardoso** [comment]
@macedojr3 então o seu teste não chegou para nós rsss... Vou lhe sugerir que envie novamente no e-mail ou senão de uma olhadinha também na caixa de SPAM de seu email para ver se não tem uma resposta, pois utilizamos o sistema do Recruitee para gerenciar a evolução de todos os candidatos e alguns e-mails acabam sendo direcionados para SPAM.

**Comment by macedojr3** [comment]
Na verdade chegou, @flaviohcardoso. 
No mesmo dia que enviei o teste (23 dias atrás), me retornaram com intenção de marcar entrevista... respondi 10 minutos depois e... até hoje nada.

Mas queria apenas deixar aqui o ocorrido para que futuros candidatos analisem bem. =)

Obrigado.

**Comment by flaviohcardoso** [comment]
Ok @macedojr3 lhe agradeço as suas considerações e se precisar de alguma coisa, você pode nos enviar um email que terei o prazer em lhe responder.

**Comment by Kateleandra** [comment]
Cheguei a mandar teste também. Não recebi feedback e não respondem e-mail. Que pena.

**Comment by xbrunosousa** [comment]
3!
Também mandei meu teste dia 22 e até hoje nada de feedback.

**Comment by flaviohcardoso** [comment]
Ola @Kateleandra eu localizei a sua candidatura e chegamos a lhe responder na epoca de sua candidatura para uma outra vaga. Fico triste por você não te recebido o seu feedback no seu e-mail e a partir das consideração aqui no grupo irei pedir ao pessoal do Recruitee que avalie melhor estes e-mails que respondemos de nossos candidatos.

**Comment by flaviohcardoso** [comment]
@xbrunosousa acredito que o seu caso é um pouquinho diferente neh. Não só lhe enviamos um feedback como também recebemos o seu retorno para um possivel agendamento de entrevista pessoalmente, pois você não é de Belo Horizonte e está trabalhando atualmente no norte do pais e dificultaria bastante este seu deslocamento.
Nós gostamos bastante do seu teste ;)
Vamos conversando através do e-mail, pois aqui não é o local ideal...
Abraço

**Comment by xbrunosousa** [comment]
Havia respondido seu email assim que recebi, @flaviohcardoso. 
Lhe mandei outro agora. Seguimos por lá. =)

**Comment by guibfo** [comment]
@macedojr3 Gostei da iniciativa de "confrontar" sobre feedback, tem inclusive uma vaga de outra empresa aberta aqui que aconteceu o mesmo comigo "te respondemos no máximo em 2 dias", e esses 2 dias tem uns 3 meses já, isso porque eu perdi meu tempo com diversas fases, não foi nem no primeiro contato, inclusive na entrevista presencial eu mencionei que acho importante receber feedback independente do resultado, e ainda concordaram comigo haha

Fiquei com receio de postar algo parecido pra não parecer muito agressivo, mas eu acho que devíamos aproveitar o que a gente tem aqui pra cobrar um pouco de respeito pelo nosso tempo, não é só a empresa que gasta o tempo dela. Eu não me importo nem com um e-mail automático padrão avisando que não fui selecionado, ficar no escuro esperando que mata
