### ISSUE TITLE
[Campinas - SP] Desenvolvedor React na Poppin

### ISSUE THREAD

**Issue by rvitorsantos** [frontendbr/vagas#1177]
Sobre o Poppin:

O Poppin é o aplicativo que conecta pessoas que irão aos mesmos eventos e lugares. Depois de passar pela ACE (maior Aceleradora de Startups da América Latina) e ser escolhida como uma das 100 startups mais Quentes do Brasil pela Pequenas Empresas Grandes Negócios, estamos aumentando nosso Time de Desenvolvimento e nos preparando para internacionalizar. Se você sempre quis fazer parte de um negócio que impacta milhares de pessoas, essa é a oportunidade perfeita!

Descrição da vaga:

Principais Atividades
- Desenvolver e manter um código estruturado e reutilizável
- Participar do planejamento de novas funcionalidades
- Identificar e propor melhores práticas para Front-End, participando da definição do projeto, revisão do código, testes e manutenção.

Local
Campinas-SP

Benefícios
- Férias remuneradas
- Flexibilidade de horários
- Ambiente descontraído
- Oportunidade de crescimento pessoal e profissional acelerado

Requisitos
- Experiência com HTML, CSS, Javascript
- Ter interesse em trabalhar numa startup e ser movimentado por desafios
- Estar cursando ou ja ter cursado Ciência da Computação, Engenharia da Computação ou curso similar

Experiência com:
- React
- HTML, CSS, Javascript
- RESTfull API's
- Ferramentas de controle de versão (Git)

Desejável conhecimento em:
- Comunicação via Socket
- Protocolo OAuth de autenticação
- ES6 /Typescript

Contratação
Estágio 25h/semana

Como se candidatar

Quer fazer parte do nosso time e crescer junto com a gente? Acesse o link: https://itspoppin.typeform.com/to/zpSFtK e preencha o formulário com suas informações. Entraremos em contato para marcar conversas e explicar os detalhes da vaga depois de fazer uma análise dos perfis.

startpoppin.com
#ItsPoppin

**Comment by guilhermeoa07** [comment]
Qual a senioridade?

**Comment by rvitorsantos** [comment]
A Vaga é pra estágio não exigimos senioridade

**Comment by juliano-nunes** [comment]
@vinirossi

**Comment by vinirossi** [comment]
Mandei @juliano-nunes obrigado pela indicação :) Se eu passar eu pago o Japa.
