### ISSUE TITLE
[Remoto] Desenvolvedor Front End (ReactJS)

### ISSUE THREAD

**Issue by diegoarcega** [frontendbr/vagas#118]
## Descrição da vaga

Quer trabalhar com IoT para uma empresa americana, com tecnologias como React e Redux? read on...

## Local

Remoto 

## Requisitos

**Obrigatórios:**
- ReactJS
- Javascript(ES6) 
- CSS/SASS
- GIT
- Experiência consumindo APIs REST.

**Desejáveis:**
- Redux
- Testes com Jest
- react-storybook
- highcharts

## Contratação

 combinar

## Nossa empresa
Focamos em simplificar a interface entre máquinas e usuários, para que organizações e pessoas possam gastar tempo nas coisas que realmente importam.

Tago é uma empresa Americana localizada em Raleigh, Carolina do Norte. Estamos no Centennial Campus da NCSU, um lugar dedicado ao desenvolvimento de tecnologias avançadas tais como sistemas inteligentes e análise de dados. Contamos com equipes locais também no Brasil e Nova Zelândia.

https://tago.io/pt/home

## Como se candidatar

Por favor envie um email para diegoarcega@gmail.com com seu CV anexado - enviar no assunto: Vaga Desenvolvedor Front End

**Comment by diegoarcega** [comment]
@LFeh troca pra pleno?  thanks

**Comment by Mendrone** [comment]
@diegoarcega feito!

**Comment by ribeiroevandro** [comment]
Curti a vaga, pena que ainda não tenho essas skills 😞

**Comment by gkal19** [comment]
Pena que eh para Pleno :(

**Comment by willianjusten** [comment]
Pow que bacana, vi que usam o Storybook e tudo. Curto pacas ele, uso na estrutura da minha [lyef](https://github.com/lyef/lyef-react-component).

Só fiquei curioso por terem optado Jest para testes, ele deu uma melhorada em bastante coisa, mas ainda peca muito usando soluções com Mock. Confesso que ainda prefiro a combinação Mocha+Chai+Enzyme <3

A vaga tá muito maneira, boa sorte =D

**Comment by camilatigre** [comment]
@diegoarcega 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by diegoarcega** [comment]
@camilatigre 
Nao cheguei a perguntar isso, mas acredito que tenha sido.
a) Sim
