### ISSUE TITLE
[São Paulo] Front-End Developer Jr. na empresa BoaConsulta

### ISSUE THREAD

**Issue by paulogr** [frontendbr/vagas#1180]
## Descrição da vaga

Seguindo a dica que o William Grasel me deu no twitter estou colocando aqui uma vaga em aberto para um(a) dev front-end Jr. em empresa BoaConsulta, temos projetos em vue, react e o site principal feito em angular. 

Maiores detalhes em
https://boaconsulta.recruiterbox.com/jobs/fk01pqz/

## Local

São Paulo - Pinheiros

## Benefícios

- Vale refeição
- Vale Transporte
- Convênio médico
- Seguro de vida
- Vale educação
- Muito café

#### Diferenciais

- Equipe pequena, muito a aprendizado, contato com diferentes tecnologias.

## Requisitos

**Obrigatórios:**
- Experiência mínima de 2 anos com javascript ou typescript
- Experiência mínima de 1 ano com Vue, React ou Angular
- Conhecimento Webpack, NPM, Yarn, gulp, grunt, etc
- Conhecimento em HTML, CSS, JavaScript, GIT

**Desejáveis:**
- Pré-processadores (Less, Sass)
- Testes de interface

**Diferenciais:**
- Ser gente fina!

## Contratação

CLT

## Como se candidatar

Aplique para essa vaga em
https://boaconsulta.recruiterbox.com/jobs/fk01pqz/

Ou responda a issue, entre em contato comigo via Twitter @paulo_gr que posso agilizar o processo ;)

Muito Obrigado!

**Comment by hectorgrecco** [comment]
Paulo, teria um e-mail para conversarmos?

**Comment by Finacio** [comment]
Não aceitam remoto?

**Comment by paulogr** [comment]
@hectorgrecco paulo.rodrigues@boaconsulta.com
@Finacio essa vaga é presencial, não aceitamos remoto não.

**Comment by leonardomso** [comment]
Boa tarde Paulo, te segui no Twitter, teria a gente conversar por DM?

**Comment by paulogr** [comment]
Sim @leonardomso, só mandar uma DM!

**Comment by leonardomso** [comment]
Não tem como mandar DM pra quem não me segue, se você puder me seguir rapidamente apenas pra gente conversar.

**Comment by Gpaula95** [comment]
Tenho um ano e meio de experiencia porem 1 ano com VueJs, poderia me candidatar a vaga para fazer o teste ?
