### ISSUE TITLE
[Alphaville] Front-End Developer na Corebiz

### ISSUE THREAD

**Issue by fabriciovieira** [frontendbr/vagas#1181]
## Descrição da vaga

CoreBiz contrata Desenvolvedor(a) Front-end com conhecimentos sólidos em HTML e CSS. 
O(a) profissional atuará em projeto de para empresa global de cosméticos.

## Local

Escritório, Barueri - Alphaville

## Benefícios

- Vale-transporte
- Vale-refeição
- Convênio médico

## Requisitos

**Obrigatórios:**
- Conhecimentos sólidos em HTML e CSS
- Bom entendimento da língua inglesa

**Desejáveis:**
- Conhecimento em Drupal

## Contratação

- CLT 

## Nossa empresa

A Corebiz é uma agência especializada em soluções de ecommerce desde o projeto de implantação, até o relacionamento com cliente, com metodologia própria e experiência aplicada em mais de 150 projetos. Temos escritórios no Brasil, Argentina e México.

## Como se candidatar

Por favor envie um email para rh@corebiz.com.br com seu CV anexado - enviar no assunto: Vaga Front-End JR.

## Labels

- Alocado
- CLT
- Júnior

**Comment by guilhermeoa07** [comment]
A entrevista pode ser remota?
