### ISSUE TITLE
[Rio de Janeiro] Front-End Developer na Carta

### ISSUE THREAD

**Issue by malvadeza** [frontendbr/vagas#1182]
## Descrição da vaga

Trabalhará em conjunto com nosso designers, gerentes de produtos e outros desenvolvedores criando um produto de qualidade. 

## Local

Rio de Janeiro - Flamengo

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ 45/dia
- Auxílio relocação

#### Diferenciais

- Escritório bem equipado (comida, snacks, bebidas).
- Vista maravilhosa para o Pão de açúcar.
- Reembolso de livros relacionado ao trabalho.

## Requisitos

**Obrigatórios:**
- Inglês fluente
- Experiência com React

**Desejáveis:**
- 2+ anos de experiência com Front-end (Pleno)
- 4+ anos de experiência com Front-end (Sênior)

**Diferenciais:**
- Python/Django

## Contratação

CLT

## Nossa empresa

- https://vimeo.com/273958418

[Carta](https://carta.com) is creating the ownership network that maps the world's assets. Check out who we are and how we work [here](https://blog.carta.com/).

Carta’s engineering team is growing rapidly, and we are looking for Front-End Developers with React experience in our Rio de Janeiro office.

You will have the opportunity to quickly contribute to and help shape fundamental aspects of the service.

Carta has a unique culture of close teamwork across Engineering, Product, and Business. Learn more about what we do [here](https://blog.carta.com/eshares-is-now-carta/).

The ideal candidate has an affinity for building spectacular products and is passionate about product development. Things change quickly in our dynamic startup, so adaptability, resilience, and ability to thrive in ambiguity are key traits in this role.

## Como se candidatar

Pleno -> https://jobs.lever.co/carta/877cc65a-a719-41ec-8991-1bb179b0439b?lever-via=gSx12_HQWK
Senior -> https://jobs.lever.co/carta/2dbc2538-6a4e-415b-8854-8d94eaf8b642?lever-via=gSx12_HQWK

## Labels

- Alocado
- CLT
- Pleno
- Sênior

**Comment by alexgmello** [comment]
Alguma chance de abrir uma vaga pra Júnior?

Grato.

**Comment by malvadeza** [comment]
Opa @alexgmello, infelizmente no momento não 😢 
Mas em breve acredito que abriremos sim, assim que abrir postarei por aqui de novo.

**Comment by alexgmello** [comment]
Ah, que pena.
Mas obrigado pela resposta. =]
