### ISSUE TITLE
[São Paulo] - Front-end Developer Html e Javascript - 2 Vagas

### ISSUE THREAD

**Issue by engaugusto** [frontendbr/vagas#1184]
## Descrição da vaga

Se você é um desenvolvedor, que gosta de desafios e resolver problemas.
Gostaríamos muito de falar com você!

Procuramos desenvolvedores com alta capacidade de aprendizagem, motivado, que seja organizado no código, nos testes e na vida. 

Seu desafio será ajudar a criar a melhor solução para o cliente de acordo com o que ele pedir, e isso nunca é tão simples :)

* Você trabalhará principalmente:
* Como alocado dentro do nosso cliente desenvolvendo projetos customizados em Javascript e HTML.
* Manutenção em códigos existentes em Html e Javascript.
* Desenvolvendo funções que possam ser reutilizadas pelo time !!

* Caso se sinta apto, a nossa prova está disponível em : http://github.com/ecomm-it/prova-quaquadrinhos-html-js

## Local

Santo André, São Paulo

## Benefícios

- Salário compatível com mercado, regime PJ/CLT/Cooperado.

#### Diferenciais

- Profissionais de alta capacidade do mercado
- Aprendizagem com certeza
- Mentoria

## Requisitos

**Obrigatórios:**
- Sólidos conhecimentos em Javascript 
- Sólidos conhecimentos em HTML
- Lógica

**Desejáveis:**
- Git
- Slack
- Algum framework de javascript.
- Noções de integração com API, Ajax, Testes unitários.

**Diferenciais:**
- projetos opensource
- portfólio no github 

## Contratação

PJ a combinar / CLT / Cooperado

# Nossa empresa

![Image of EcommIt](https://github.com/ecomm-it/brand/blob/master/IT-small.png?raw=true)

A Ecomm-IT é uma empresa madura no mercado de consultoria de tecnologia da informação principalmente no segmento financeiro, atualmente estamos expandindo nossas operações para diversos setores.

##Como se candidatar

Por favor envie um email para vagas@ecommit.com.br com seu currículo (CV) anexado / portfolio e sua pretensão salarial 

## Labels

- Alocado
- CLT
- Júnior ou Pleno
- PJ / CLT / Cooperado
- Javascript
- Html

**Comment by joabalvesdosantos** [comment]
Alguma possibilidade de remoto?

**Comment by engaugusto** [comment]
Ola @gabrieldemello, desculpe a demora !.
Maravilha, a nossa prova está na descrição do post.

**Comment by gabrieldemello** [comment]
@engaugusto como eu faço?
