### ISSUE TITLE
[Remoto] React Web e Native na MAGTAB

### ISSUE THREAD

**Issue by douglaslondrina** [frontendbr/vagas#1186]
## Descrição da vaga

Estamos criando um editor visual de conteúdo responsivo em React e app mobile em React Native para leitura. Desenvolvimento em fase avançada. Trabalhamos com agile, TDD, code-review e pair-programming pra te ajudar a dar aquele salto de produtividade e qualidade.

NO EXPERIENCE NEEDED.

## Local

100% Remoto

## Benefícios

- Bolsa CNPq com valor à partir de R$2500
- Horário flexível

## Requisitos

- Formado em Ciência da Computação ou correlata.

**Desejáveis:**

- Ter prática com ES6
- Ter prática com frameworks reativos (React, Vue, Angular)
- Já ter tido contato com Django
- Já ter tido contato com TDD

## Contratação

Você será contratado como bolsista CNPq, o que oferece vantagem curricular para iniciativas científicas.

## Nossa empresa

A MAGTAB é a maior plataforma de Digital Publishing do Brasil, estamos criando um novo produto para criação e publicação de conteúdo e somos agora uma Startup acelerada do programa StartUP Brasil. 

Venha junto conosco crescer profissionalmente e vivenciar uma Startup em acensão.

## Como se candidatar

Por favor envie um email para rh@magtab.com com seu CV anexado - enviar no assunto: Vaga React. 

## Labels

- alocação/Remoto - Total
- experiência/Júnior ou Pleno
- regime/Bolsista

**Comment by vitorlsouza** [comment]
Enviado CV.

**Comment by FelipeFSilva** [comment]
@douglaslondrina Esta vaga já está fechada?

**Comment by douglaslondrina** [comment]
Sim @FelipeFSilva , desculpe fechei no React e esqueci aqui.
