### ISSUE TITLE
[São Paulo] Front-End Developer na LaPag

### ISSUE THREAD

**Issue by MarceloPrado** [frontendbr/vagas#1187]
## Descrição da vaga

Oportunidade para desenvolvedores que queiram participar de uma empresa em alto ritmo de crescimento. Buscamos resolvedores de problemas e pessoas com muita energia para participar das decisões internas da LaPag. 

A vaga é para front-end do time de engenharia. Nosso maior desafio é escalar o produto mantendo uma qualidade excepcional para nossos usuários. Desenvolvedores que procuram espaço para criar um bom produto se darão muito bem nesta vaga. Nossos usuários são bastante exigentes 👌 

Hoje, nossa stack é React, Node e MongoDB. Usamos um pouco de C# e Python fora da aplicação principal.

## Local

Escritório, São Paulo - Itaim Bibi

## Benefícios

- A combinar, estamos acabando de montá-los

#### Diferenciais

- participe de um dos momentos mais interessantes de uma startup (escalar o modelo e ganhar tração) 🚀 
- ambiente jovem e descontraído
- muita liberdade para tomar decisões (stack, implementação, etc)
- rico ambiente de aprendizado
- liberdade para desbravar novas ideias e áreas (tem interesse em fullstack? quer testar um protótipo novo? Sem problema, vai lá e faz! ) 💥 

## Requisitos

**Obrigatórios:**
- HTML5, CSS
- <strong>Sólida</strong> experiência em JS (vanilla ou alguma framework) 
- Git

**Desejáveis:**
- React JS ✨ ou outra framework
- ECMAScript 6 (ES6)

**Diferenciais:**
- Experiência em UI/UX
- React JS
- Experiência com Redux

## Contratação

PJ

## Faixa Salarial

Júnior: R$ 2000,00 - R$ 3500,00
Pleno: R$ 4500,00 - R$ 7500,00
Sênior: R$ 7500,00 - R$ 10000,00

## Nossa empresa

A [LaPag](https://lapag.com.br) é uma fintech para salões de beleza, barbearias e studios de tattoo. Resolvemos um problema existente em todo o mercado de beleza: a informalidade desses negócios ([entenda mais](https://exame.abril.com.br/pme/ela-fez-brigadeiros-virarem-negocio-que-resolve-maior-problema-dos-saloes/)). Através da nossa maquininha de cartão e nosso software de gestão, conseguimos aumentar a lucratividade dos estabelecimentos em até 20%.

Somos uma das cinco fintechs [aceleradas pela VISA](https://conteudo.startse.com.br/startups/taina/visa-anuncia-startups-selecionadas-para-programa-de-aceleracao/). Além disso, acabamos de fazer nossa 1a captação com o <strong>fundador da 99 táxi</strong> e o fundo <strong>Canary VC</strong> ([notícia](https://startupi.com.br/2018/06/lapag-recebe-aporte-do-fundo-de-venture-capital-canary/)). 

Estamos em um momento de alto crescimento, tanto do time como do produto. Por isso, esta é uma grande oportunidade para crescer junto com a gente. Todos que estiverem no barco surfarão essa onda.

## Como se candidatar

Por favor, enviar um email para marcelo@lapag.com.br com seu CV anexado. Enviar no assunto: Vaga FrontEnd - BR

## Labels

- Alocado
- PJ
- Júnior
- Pleno
- Sênior

**Comment by yurypcf** [comment]
Enviei o currículo!

**Comment by matheus-rosin** [comment]
Aceitando remoto?
Tomara que sim :)

**Comment by filipefborba** [comment]
Enviado!

**Comment by eduardotp1** [comment]
Mandei, para Dev Junior qual a carga horária? Ou mandará por email?

**Comment by eduardotp1** [comment]
Mandei!!

**Comment by eduardotp1** [comment]
Currículo enviado

**Comment by ruhman** [comment]
Curriculo enviado!! :)

**Comment by MarceloPrado** [comment]
Obrigado a todos os interessados! A vaga foi preenchida.
