### ISSUE TITLE
[Florianópolis / Remoto] Front-End Developer na datarisk.io

### ISSUE THREAD

**Issue by gustavodgbernardo** [frontendbr/vagas#1189]
## Descrição da vaga

Vaga para desenvolvedor front-end Pleno ou Senior, sua principal função será desenvolver e dar manutenção em nossa plataforma web de machine learning. Hoje utilizamos React/Redux em conjunto com material design.

## Local

Remoto ou Escritório, Florianópolis - SC

## Requisitos

**Obrigatórios:**

- conhecimentos HTML, CSS, Javascript
- React, Redux
- Git
- Trabalho em equipe.
- vontade de aprender coisas novas

**Desejáveis (diferencial):**

- AWS
- Docker
- teste A/B
- Sistemas distribuídos
- Design System

## Benefícios

- Horário Flexível.
- Ambiente descontraído. 
- Liberdade na tomada de decisão (tecnologia, gestão de tarefas, etc)
- Ambiente para aprendizado constante (técnicas de machine learning, entre outros)    

## Contratação

PJ a combinar

## Nossa empresa

A datarisk.io é uma startup focada em otimizar análises de dados através de uma plataforma web amigavel utilizando as tecnicas mais avançadas de machine learning.  Temos como alvo instituições financeiras, nas quais temos muitos anos de experiência e todo o processo foi otimizado para esse tipo de modelagem. Se você gosta de desafios, grandes quantidades de dados, modelagem estatística, aprendizado de máquina e trabalhar com pessoas excelentes, você é bem-vindo!  E recentemente fomos aceitos no programa de aceleração da [Visa](https://revistapegn.globo.com/Startups/noticia/2018/03/5-startups-sao-selecionadas-para-programa-de-aceleracao-da-visa.html).

## Como se candidatar

Por favor envie um email para gustavo.bernardo@datarisk.io com seu CV anexado - enviar no assunto: Vaga Front-end

## Labels

- alocação/Flexível
- alocação/Presencial
- alocação/Remoto
- experiência/Pleno
- experiência/Sênior
- regime/PJ

**Comment by costaleonardo** [comment]
CV enviado :)

**Comment by vinyguedess** [comment]
Enviado

**Comment by andrebrandaoo** [comment]
Enviado

**Comment by gustavodgbernardo** [comment]
Obrigado pela participação de todos. Fechamos a vaga. 

Abs
