### ISSUE TITLE
[São Paulo] Front-end na F.biz

### ISSUE THREAD

**Issue by mcarneiro** [frontendbr/vagas#119]
## Descrição da vaga

Estamos à procura de um desenvolvedor Front-end que seja talentoso, criativo e apaixonado por pesquisa, tecnologia e design. Que enxergue o valor dos detalhes seja em um projeto "eye-candy" experimental ou um portal / e-commerce.

Somos um time multi-disciplinar composto por UX, Front e Back-end que acreditam no melhor que cada tecnologia tem a oferecer. Não só viabilizamos os projetos mas temos papel ativo e decisivo na concepção criativa dos trabalhos. Para completar, cada membro da equipe tem a opção de trabalhar com MAC ou PC.
## Local

Rua João Moura, 1144, Pinheiros, São Paulo
## Benefícios
- Transporte;
- Escolha entre trabalhar com MAC ou PC;
- Prédio mais bonito de pinheiros (e inteiro nosso!);
- Vale Refeição de R$29;
- Plano de saúde;
- Plano odontológico;
- Temos plano de carreira de longo prazo e trabalhamos com processos flexíveis que nos ajudam a organizar o dia-a-dia com mais eficiência, colaboração e menos burocracia;
## Requisitos

**Obrigatórios:**
- Experiência com HTML5, CSS;
- Pré-processadores de CSS como LESS, SASS, Stylus, PostCSS, etc;
- Conhecimento íntimo entre os browsers;
- Javascript;
- Bom acabamento;
- GIT;
- Inglês (escrita e conversação);
- Automatizadores como Grunt, Gulp, etc.

**Diferenciais:**
- Iniciativa, criatividade, colaboração;
- Acabamento visual, trabalhos "eye-candy";
- Debug;
- OOP, design patterns;
- Command-line;
- Automatização de processos;
- Projetos pessoais.
## Contratação

CLT
## Nossa empresa

A F.biz é uma agência com mais de 17 anos e DNA 100% digital. Trabalhamos com grandes clientes como Unilever, Multiplus, Claro, Honda, entre outras.
## Como se candidatar

Preencha o formulário em https://goo.gl/sXLxLx

**Comment by dsoldera** [comment]
Uma duvida: o que seria "bom acabamento"???

**Comment by LFeh** [comment]
Boa sorte @mcarneiro :)

**Comment by EdipoNascimento** [comment]
Só postam vagas para Pleno/Senior!! Como vou conseguir algo como Junior?? :(

**Comment by mcarneiro** [comment]
Oi @dsoldera, quero dizer relacionado acabamento visual, que tenha olho pra identificar um layout bom e ruim, consiga seguir com alinhamentos e definições visuais combinadas.

Outra coisa, apesar do label `pleno`, normalmente não abrimos vaga com nível definido. Pode ser júnior ou sênior também. De acordo com os candidatos que aparecem tentamos ver a melhor forma de trazer novos profissionais para compor a equipe. Focamos mais no perfil da pessoa do que no nível de conhecimento no momento da seleção :)

**Comment by mcarneiro** [comment]
@ediponascimento pode mandar pra essa vaga também :)

**Comment by EdipoNascimento** [comment]
@mcarneiro 
Show! Thanks for you'r help =;)

**Comment by dsoldera** [comment]
Obrigada @mcarneiro . =)

**Comment by idlua** [comment]
@mcarneiro que oportunidade bacana!!

**Comment by LFeh** [comment]
@mcarneiro Coloquei outras labels :)

**Comment by olegon** [comment]
@mcarneiro Mandei minhas informações e estou aguardando **ansiosamente** por um :coffee: !

**Comment by mcarneiro** [comment]
@LFeh opa, valeu Felipe!

@olegon boa, vamos nos falando :)

**Comment by brunooomelo** [comment]
CV enviado !!

**Comment by Rivail** [comment]
tenho interesse mora na Saúde SP.

**Comment by LFeh** [comment]
@mcarneiro A vaga foi fechada? :)

**Comment by mcarneiro** [comment]
Ops @LFeh, foi sim. Acabei esquecendo de fechar aqui.

**Comment by LFeh** [comment]
🌞

**Comment by camilatigre** [comment]
@mcarneiro 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by mcarneiro** [comment]
Oi @camilatigre, não fechamos com ninguém daqui.

Abraço
