### ISSUE TITLE
 [Portugal] Front-End Developer na Aubay

### ISSUE THREAD

**Issue by FernandaMorais** [frontendbr/vagas#1190]
# Descrição da vaga

Projetos diferenciados em vários setores de atividade, usando diversas tecnologias de Front End tal como NodeJS, Go entre outras

## Local

Portugal: Lisboa e Porto

## Benefícios

- Plano de saúde
- Visto de Trabalho para Portugal
- Outras

#### Diferenciais

- cultura organizacional gerida pelo nosso Hapiness Manager
- horário flexível
- almoço grátis todas as sexta-feiras
- frigobar sempre cheio 
- armário das bolachas sempre cheio
- eventos mensais com atividades diferenciadas

## Requisitos

**Obrigatórios:**
- Experiência com tecnologias de front-end
- Domínio da língua inglesa

**Desejáveis:**
- conhecimentos NodeJS
- conhecimentos em GoLang

**Diferenciais:**
- projetos internacionais que permitem contato com vários países.

## Contratação

Apoio em todo o processo para obtenção de visto de trabalho para Portugal.

## Nossa empresa

A Aubay, é uma empresa de origem francesa presente em diversos países na Europa.
Como cerca de 6000 pessoas desenvolvemos projetos nas mais diversas tecnologias.
Neste momento, temos várias vagas em aberto para várias posições.

## Como se candidatar

Por favor envie um email para fmorais@aubay.com com seu CV anexado.

**Comment by PauloRobertoM** [comment]
Enviado! \o/

**Comment by FernandaMorais** [comment]
Ola Paulo,

Você respondeu ao questionário?

Obrigado,


  [cid:image001.png@01D41EAC.DB7CE2B0] Fernanda Morais
  International Talent Recruiter

Edíficio Duque D´Ávila
Avenida Duque de Ávila, nº46 7C
1050-083 Lisboa
Tel: +351 211 928 417 - Mobile: +351 914 273 951
Skype: fmorais83


Antes de imprimir, pense no ambiente!


“Iremos utilizar informação pessoal que nos enviou, para considerar a sua candidatura à função relevante. Ao facultar-nos a sua informação por email e/ou em documentos, consente que a Aubay Portugal trate a sua informação pessoal. A sua privacidade é importante para nós. Por favor, consulte a nossa Política de Privacidade, que explica de que forma utilizaremos e armazenaremos a sua informação pessoal. Explica também os direitos que tem relativamente à sua informação e como pode contactar-nos para o esclarecimento de dúvidas ou pedidos.”

De: Paulo Roberto <notifications@github.com>
Enviada: 18 de julho de 2018 14:34
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: Fernanda MORAIS <fmorais@aubay.com>; Author <author@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [Portugal] Front-End Developer na Aubay (#1190)


Enviado! \o/

**Comment by PauloRobertoM** [comment]
Olá Fernanda!
@FernandaMorais 

Não achei o questionário para responder. Apenas enviei o CV e Portfólio para o email. Você poderia disponibilizar o questionário, por favor?

**Comment by FernandaMorais** [comment]
Ola Paulo,

Link abaixo:
http://www.aubay.pt/Home/International#

Obrigado,

  [cid:image001.png@01D41F66.CC3222B0] Fernanda Morais
  International Talent Recruiter

Edíficio Duque D´Ávila
Avenida Duque de Ávila, nº46 7C
1050-083 Lisboa
Tel: +351 211 928 417 - Mobile: +351 914 273 951
Skype: fmorais83


Antes de imprimir, pense no ambiente!


“Iremos utilizar informação pessoal que nos enviou, para considerar a sua candidatura à função relevante. Ao facultar-nos a sua informação por email e/ou em documentos, consente que a Aubay Portugal trate a sua informação pessoal. A sua privacidade é importante para nós. Por favor, consulte a nossa Política de Privacidade, que explica de que forma utilizaremos e armazenaremos a sua informação pessoal. Explica também os direitos que tem relativamente à sua informação e como pode contactar-nos para o esclarecimento de dúvidas ou pedidos.”

De: Paulo Roberto <notifications@github.com>
Enviada: 19 de julho de 2018 13:09
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: Fernanda MORAIS <fmorais@aubay.com>; Mention <mention@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [Portugal] Front-End Developer na Aubay (#1190)


Olá Fernanda!
@FernandaMorais<https://github.com/FernandaMorais>

Não achei o questionário para responder. Apenas enviei o CV e Portfólio para o email. Você poderia disponibilizar o questionário, por favor?

**Comment by randhson** [comment]
Enviado.


Randson N. dos S. França +55 79 99843 9878+55 79 99138 7628 

    Em quinta-feira, 19 de julho de 2018 09:47:24 BRT, FernandaMorais <notifications@github.com> escreveu:  
 
 Ola Paulo,

Link abaixo:
http://www.aubay.pt/Home/International#

Obrigado,

 [cid:image001.png@01D41F66.CC3222B0] Fernanda Morais
 International Talent Recruiter

Edíficio Duque D´Ávila
Avenida Duque de Ávila, nº46 7C
1050-083 Lisboa
Tel: +351 211 928 417 - Mobile: +351 914 273 951
Skype: fmorais83


Antes de imprimir, pense no ambiente!


“Iremos utilizar informação pessoal que nos enviou, para considerar a sua candidatura à função relevante. Ao facultar-nos a sua informação por email e/ou em documentos, consente que a Aubay Portugal trate a sua informação pessoal. A sua privacidade é importante para nós. Por favor, consulte a nossa Política de Privacidade, que explica de que forma utilizaremos e armazenaremos a sua informação pessoal. Explica também os direitos que tem relativamente à sua informação e como pode contactar-nos para o esclarecimento de dúvidas ou pedidos.”

De: Paulo Roberto <notifications@github.com>
Enviada: 19 de julho de 2018 13:09
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: Fernanda MORAIS <fmorais@aubay.com>; Mention <mention@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [Portugal] Front-End Developer na Aubay (#1190)


Olá Fernanda!
@FernandaMorais<https://github.com/FernandaMorais>

Não achei o questionário para responder. Apenas enviei o CV e Portfólio para o email. Você poderia disponibilizar o questionário, por favor?

**Comment by PauloRobertoM** [comment]
Questionário respondido!

**Comment by FernandaMorais** [comment]
Colocou o meu email?


  [cid:image001.png@01D41F8E.A408BC40] Fernanda Morais
  International Talent Recruiter

Edíficio Duque D´Ávila
Avenida Duque de Ávila, nº46 7C
1050-083 Lisboa
Tel: +351 211 928 417 - Mobile: +351 914 273 951
Skype: fmorais83


Antes de imprimir, pense no ambiente!


“Iremos utilizar informação pessoal que nos enviou, para considerar a sua candidatura à função relevante. Ao facultar-nos a sua informação por email e/ou em documentos, consente que a Aubay Portugal trate a sua informação pessoal. A sua privacidade é importante para nós. Por favor, consulte a nossa Política de Privacidade, que explica de que forma utilizaremos e armazenaremos a sua informação pessoal. Explica também os direitos que tem relativamente à sua informação e como pode contactar-nos para o esclarecimento de dúvidas ou pedidos.”

De: Paulo Roberto <notifications@github.com>
Enviada: 19 de julho de 2018 18:22
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: Fernanda MORAIS <fmorais@aubay.com>; Mention <mention@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [Portugal] Front-End Developer na Aubay (#1190)


Questionário respondido!
