### ISSUE TITLE
[Florianópolis / Remoto] Front-End Developer na NeoLife

### ISSUE THREAD

**Issue by alanicolasouza** [frontendbr/vagas#1191]
## Descrição da vaga

Vaga de desenvolvedor front-end pleno, com foco principalmente para desenvolvimento Wordpress e HTML (puro ou c/ bootstrap). 

## Local

Remoto ou Escritório, Floripa - Ingleses

## Oferecemos

- Ambiente super descontraído com equipe fantástica
- Liberdade na tomada de decisão (tecnologia, gestão de tarefas, etc)
- Horários flexíveis 
- Café e almoço da Rita (você vai adorar ela ♥️) 
- Vista incrível pro mar e montanhas (apenas uma quadra do mar)
- Ambiente de lazer com Nintendo até PS4.
- Estar em contato com os melhores profissionais de cada área, temos orgulho de dizer que unimos alguns dos melhores profissionais de marketing direto do Brasil no mesmo lugar, o ambiente proporciona aprendizagens diárias e crescimento tanto profissional quanto pessoal contínuo;
- Remuneração compatível com conhecimento mais bônus por resultados.
- Bônus: Temos certeza que o Max (nosso pet) vai sempre alegrar o seu dia.

## Requisitos

**Obrigatórios:**
- Conhecimentos sólidos em desenvolvimento front-end: HTML5, CSS3, Javascript e jQuery;
- Conhecimento em programação PHP;
- Conhecimento sólido de desenvolvimento Wordpress (preferimos criar nossos próprios plugins por segurança);
- Experiência com design responsivo e cross-browser;
- Compromisso com as deadlines e qualidade na entrega.

**Desejáveis:**
- Inglês intermediário para leitura, escrita e entendimento.
- Conhecimento em SEO e boas práticas de código semântico;
- Conhecimento em Google Analytics e Google Tag Manager;
- Experiência com Git (ou qualquer outro versionador);
- Experiência com MySQL;
- Experiência com Servidores (configurar, ajustar);
- Conhecimento em pré-processadores CSS (SASS ou LESS);
- Conhecimento de conexão com APIs;
- Portfólio online (ou algum lugar que reuna projetos já publicados);

**Diferenciais:**
- Inglês Avançado;
- Conhecimento básicos com adobe Photoshop ou Fireworks.

## Contratação

PJ ou CLT a combinar

## Nossa empresa

Uma startup de Marketing Direto voltada suplementos naturais com um dos maiores crescimentos do mercado brasileiro nos últimos 3 meses.

## Como se candidatar

Para fazer a aplicação para essa vaga basta preencher o seguinte formulário: https://alanicolas.typeform.com/to/mFbPSv

## Labels

- Alocado
- Remoto - Total
- CLT
- PJ
- Pleno

**Comment by highlabs** [comment]
Fui me candidatar e o Piping do nome no form está com problema. Ele printa `{{unkownpiping}}` em vez do nome. :)

**Comment by abekroenem** [comment]
Feito 😸

**Comment by costaleonardo** [comment]
Completado :)

**Comment by LeonardoGraselAlmeida** [comment]
Completado.

att,
Leonardo Almeida


Em qua, 18 de jul de 2018 às 15:00, Robson Hennes <notifications@github.com>
escreveu:

**Comment by alanicolasouza** [comment]
Obrigado a todos que estão enviando. Em breve vamos entrar em contato!

**Comment by tonino00** [comment]
Enviado :)

**Comment by flavianunes** [comment]
Enviado :+1:
