### ISSUE TITLE
[São Paulo]  Front End Developer na SysMap

### ISSUE THREAD

**Issue by neidesouza** [frontendbr/vagas#1194]
Somos a SYSMAP e estamos contratando talentos interessados em se juntar a um time colaborativo, engajado com inovação, interatividade e grandes desafios.

São 04 VAGAS - Desenvolvedor PL 
Conhecimento mandatório: ANGULAR, HTML, CSS, JavaScript, Node.js, Express, ES6, Git, Git flow, SQL e NoSQL;

Contratação PJ
Atuação na região da Paulista-SP. 
Enviar Github / LinkedIn ou CV para rh3@sysmap.com.br;

**Comment by LFeh** [comment]
@neidesouza A vaga está fora dos padrões, por favor edite [seguindo esse template](https://github.com/frontendbr/vagas/blob/master/.github/issue_template.md) para ela poder continuar aberta.
