### ISSUE TITLE
[São Paulo] - NodeJs Pleno na SysMap

### ISSUE THREAD

**Issue by neidesouza** [frontendbr/vagas#1196]
## Descrição da vaga
Projeto back end em Node.js, Express, ES6, saga, Typescript, RXJs.

## Local
Região do Brooklin-SP

## Benefícios
A combinar

#### Diferenciais
Horário flexível
- Conceitos do ambiente: Integração contínua, BDD e TDD, Micro Serviços, PWA , API, DDD, BDD, Message Broker, Arquitetura de aplicações em nuvem.

## Requisitos

**Obrigatórios:**
Experiência com Node.

**Desejáveis:**
- conhecimentos em Git, Git flow.

**Diferenciais:**
Time colaborativo, engajado com inovação, interatividade e grandes desafios.

## Contratação
PJ a combinar

## Nossa empresa
A SysMap Solutions é uma Consultoria em tecnologia da Informação especializada em oferecer ao mercado, soluções de alta de performance, estratégias personalizadas de negócios, transformação digital, serviços de terceirização e implementação de diversos conceitos.

## Como se candidatar
Por favor envie um e-mail para rh3@sysmap.com.br com seu CV anexado - enviar no assunto: Vaga NodeJS

## Labels
- PJ
- Pleno

**Comment by vinyguedess** [comment]
Aceita remoto ?
