### ISSUE TITLE
[São Paulo] Desenvolvedor IOS - RESOURCE

### ISSUE THREAD

**Issue by POLLEZI** [frontendbr/vagas#1197]
## Descrição da vaga

Projeto de transformação digital - Ecommerce

## Local

Alphaville - SP

## Benefícios

VR
VT
Convenio Médico
Convenio Odontologico
Auxilio Creche
Convenio Farmácia
Seguro de Vida

## Requisitos

IOS
XCODE 
SWIFT 
GIT
FIREBASE
CRASHLITYCS

## Contratação

CLT

## Nossa empresa
Venha fazer parte do time de Inovação Digital da Resource, uma das maiores integradoras digitais do Brasil e uma as empresas de TI que mais crescem no País. Com 25 anos no mercado, multinacional brasileira com presença global, com 21 escritórios em 5 países. 
Também está presente no Vale do Silício com um avançado Centro de Pesquisa e Inovação, o que possibilita estar cada vez mais próxima do cliente, entender melhor o seu negócio e oferecer a melhor solução.

## Como se candidatar

Por favor envie um cv para adriana.pereira@resourceit.com ou indique um amigo!!!
 - enviar no assunto: Vaga IOS

## Labels

- CLT

- Sênior
- Pleno
- IOS

**Comment by LFeh** [comment]
Essa vaga não é Front-end ;)

**Comment by guilhermeoa07** [comment]
@POLLEZI https://github.com/CocoaHeadsBrasil/vagas posta nesse

**Comment by Finacio** [comment]
Tem u só de android, vou pegar o link

**Comment by Finacio** [comment]
@POLLEZI https://github.com/androiddevbr/vagas
