### ISSUE TITLE
[Ribeirão Preto SP] Front-End Developer Sênior na iClinic

### ISSUE THREAD

**Issue by beatriz-barison** [frontendbr/vagas#1199]
## Descrição da vaga
Estamos buscando por um Front-End Developer sênior que irá nos ajudar o nosso time de Produto e Desenvolvimento a criar novas funcionalidades de acordo com o roadmap do produto, ajudará a encontrar soluções para problemas no sistema, trabalhando com com equipes multidisciplinares em um ambiente scrum e diversas pessoas brilhantes (como você) tendo uma troca de conhecimento muito bacana. 

## Local

Escritório iClinic - Ribeirão Preto, Av. Presidente Vargas, 1265

## Benefícios

Plano de saúde (UNIMED Isento)
Vale alimentação (R$385,00 mês)
Plano de Participação dos Resultados

#### Diferenciais

Ambiente jovem, descontraído, escritório confortável, videogame, puffs para descanso
Sem dress code. Trabalhe de calça, bermuda, chinelo, pantufa ou de qualquer outro jeito que achar confortável
Flexibilidade de horário
O sagrado cafezinho, além de capuccino, mocaccino, chocolate quente e chás, todos FREE
Rango open: café da manhã, frutas ao longo do dia e copa para refeições
Relacionamento próximo aos fundadores e diretores da empresa
Possibilidade de rápido crescimento na carreira

## Requisitos

**Obrigatórios:**
- Ter experiência sólida de pelo menos 3 anos em JavaScript
- Saber fazer manipulação do DOM sem jQuery
- Conhecer as APIs dos objetos JavaScript: Object, String, Number, Array, Regex, etc...
- Saber o básico das principais APIs do HTML5
- Conhecimento das principais features do ES6
- Orientação a Objetos, Design Patterns e boas práticas
- **Ter experiência com React, Flux e Redux (e seu ecossistema)**
- HTML5 e semântica das tags
- CSS3 e conhecimentos de algum pré-processador (usamos Sass)
- Task Runners (Grunt, Gulp e NPM Scripts)
- Alguma experiência com Webpack ou similares

**Desejáveis:**
Trabalhar com testes em JavaScript (Enzyme, Jest)
Conhecimentos básicos de NodeJS
Conhecimentos de Programação Funcional
TDD, Docker e CI

**Diferenciais:**
Conhecimento em metodologias ágeis
Experiências de liderança 

## Contratação

CLT - Fulltime

## Nossa empresa

A iClinic é uma das scale-ups de saúde que mais crescem no país e o nosso grande sonho é **Descomplicar a Saúde no Brasil**.
Fazemos isso levando tecnologia de ponta para o mercado de saúde, através do nosso sistema, melhorando a experiência de médicos, recepcionistas e pacientes.
Para suportar esse crescimento acelerado, estamos em busca de pessoas talentosas e dispostas à ir além para superar seus desafios e realmente causar impacto na saúde brasileira. 

## Como se candidatar

Se candidate através do link: https://iclinic.workable.com/jobs/611597
Você pode ver as nossas vagas nesse site também: https://vagas.iclinic.com.br/

## Labels
- Alocado
- CLT
- Sênior

**Comment by esl-douglas** [comment]
Mandei, não responderam.

Tava interessado na vaga, comecei a estudar React+Redux.
