### ISSUE TITLE
Use an issue template for Jobs

### ISSUE THREAD

**Issue by sibeliusseraphini** [frontendbr/vagas#12]
@LFeh - https://github.com/samccone/issue-and-pr-templates

**Comment by vitorbritto** [comment]
:top:  Acabo de ver essa _feature_. Vou implementar a solução.

Cc: @frontendbr/admins

**Comment by eduardojmatos** [comment]
Vi agora tbm! Agora sim! :)

**Comment by fdaciuk** [comment]
Muuuuito bom! :dancer: :dancer: :+1:

**Comment by vitorbritto** [comment]
Aguardando _merge_

**Comment by diogomoretti** [comment]
Feito!
