### ISSUE TITLE
DevOps

### ISSUE THREAD

**Issue by 21051307** [frontendbr/vagas#120]
Plans, develops, installs, troubleshoots, maintains and supports an operating system and associated server hardware, software and databases ensuring optimum system integrity, security, backup and performance.

RESPONSIBILITIES
- dentify problems, according to approved quality testing scripts, procedures and processes.
- Accepting responsibility for the processes, procedures and operational management associated with system.
- Security and disaster recovery planning.
- Liaising with security vendors, suppliers, service providers and external resources; analyzing, recommending.
- Installing and maintaining software security applications; and monitoring contractual obligations, performance delivery and service level agreements.
- Troubleshooting and providing service support in diagnosing, resolving and repairing server-related hardware and software malfunctions, encompassing workstations and communication infrastructure.
- Preparing and maintaining documentation, policies and instructions, and recording and detailing operational procedures and system logs.
- Ensuring that the design of computer sites allows all components to fit together and work properly, and monitoring and adjusting the performance of networks.
- Continually surveying the current computer site to determine future network needs and making recommendations for enhancements in the implementation of future servers and networks.

REQUIREMENTS
- Backup and Recovery.
- Client Server Technology (Request-Response, Inter Process Communication).
- Computer networks ( TCP/IP, Network Services).
- Cloud computing ( AWS ).
- Root Cause Analysis ( RCA ).
- Web Services ( Apache, NGINX ).
- Linux Operational System.
- Configuration Management Tool (Puppet, Ansible, Terraform).
- Systems Programming (Java, Shell Script).
- Web security ( DOS, DDOS, HTTPS ).
- Continuous Integration and Deployment ( Travis, Jenkins, GitFlow, BlueGreen Deployment ).
- Container Service ( Docker ).
- Data Encryption( Security Certificates,  Encryption Algorithm, Hash Algorithm).
- Distributed Systems ( DFS, GFS, HA).
- Information Systems security (VPN, SSL, Firewall).
- Database (Postgres).

BENEFITS
- A different work environment and innovative, with a culture that values people and the delivery of results;
- Autonomy and flexibility;
- Lunches, plus kitchen’s always stocked with unlimited snacks;
- Compatible salary, above the market average;
- R$ 400,00 meal tickets;
- Financial Aid for extented education and graduate;
- Financial Aid for learning english;
- Affiliation with pharmacies;
- Full health plan and Full dental plan without a discount on your paycheck;
- Financial Aid for physical activities and yoga class;
- A team that has our values in their DNAs
- Living in one of the best cities to live in Brazil;
- Access to books and other materials;
- Transportation vouchers;
- Great challenges and constant learning;
- Events and courses that push you closer to the best on the market.

Vamos participar do processo seletivo?! O primeiro passo é o cadastro na vaga (DevOps) através do site: https://contaazul.com/carreiras/vagas#vagas-abertas

Abraços!

**Comment by nic** [comment]
Favor seguir o padrão de formatação, tanto para título quando para descricão da vaga.
Segue o exemplo:
https://github.com/frontendbr/vagas/blob/master/.github/issue_template.md

**Comment by marcelinhov2** [comment]
tbm to achando que é bot... não foi ninguém da Conta Azul que inseriu essa vaga

**Comment by LFeh** [comment]
Estranho, vou remover.
