### ISSUE TITLE
[São Paulo] Front-End Developer na 🍏 OneMarket

### ISSUE THREAD

**Issue by dehbmarques** [frontendbr/vagas#1200]
# Descrição da vaga

A posição é para um Front-End Júnior/Pleno na [OneMarket](https://www.onemarket.com.br) para atuar diretamente com o produto principal.

Nosso produto é um e-commerce feita 100% in-house. Trabalhamos com uma stack moderna (React, GraphQL, css-in-js, SSR) e seguindo as melhores práticas de desenvolvimento atuais (padrões de código, unit/integration tests, CI/CD, etc.).

Temos como objetivo sermos a plataforma de e-commerce de alimentação mais completa do Brasil. A empresa está em uma fase de escalar o produto e essa vaga é para alguém que irá trabalhar diretamente com o nosso Front-End Lead para fazer isso acontecer. Apesar de sermos um "e-commerce" estamos construindo um produto que traga inovação para a compra de comida online. Veja mais informações sobre a empresa abaixo.

# Local
Presencial em São Paulo, região da Barra Funda (Zona Oeste).
Perto da estação Barra Funda (Metrô/CPTM)

# Requisitos
- Experiência em aplicações de Front-End com projetos já realizados.
- Conhecimento pleno ou avançado em CSS e JS.
- Vontade de aprender e autonomia para garantir uma entrega de qualidade.

Diferenciais:

- Experiência com React e seu ecossistema
- Experiência com GraphQL
- Experiência com Server Side Rendering
- Técnicas de otimização para web

# Contratação
Fulltime, PJ

# Nossa empresa
A [OneMarket](https://www.onemarket.com.br) é um ecommerce de alimentação saudável e também está por trás de alguns clubes de assinatura como a GlutenFree Box e a Vegana Box. A nossa missão é revolucionar o mercado de alimentação saudável através de um produto digital focado na experiência do usuário ao comprar comida online.

Temos dois anos de existência e estamos em uma fase de evolução de produto e de escalar operação. Contamos com investimento de anjos e fundos de VC para garantir o combustível necessário para isso. O produto digital é parte fundamental da nossa estratégia e uma das principais áreas de investimento da empresa. Temos um sonho grande e energia necessária para fazer isso acontecer, se você quer um desafio aqui você temos um prato cheio :)

# Como se candidatar
Envie para andre[at]onemarket.com.br um email com seus dados (CV, projetos realizados, github, linkedin, etc.)

# Labels
- Alocado
- PJ
- Júnior
- Pleno

**Comment by renatorib** [comment]
![image](https://user-images.githubusercontent.com/3277185/42973850-510c89cc-8b8b-11e8-99cb-7231f020ab3a.png)

In **OneMarket** 🍏 we trust ❤️  

A equipe é muito boa, a stack é muito boa, o ambiente muito bom. Quem vier não irá se arrepender. Fica aqui minha recomendação hahaha.

**Comment by ArtUssuy** [comment]
O e-mail está com um "[at]" no lugar do @? Fiquei na dúvida na hora de mandar, hehe.

**Comment by vncscoelho** [comment]
@ArtUssuy "at" é como a gente chama o arroba em inglês, só substituir

**Comment by pedronauck** [comment]
In 🍏 OneMarket we trust ❤️
Quem quiser trocar uma idéia sobre o stack que nós usamos no Front e como as coisas rolam na OneMarket pode me dar um toque também 🙏

**Comment by ArtUssuy** [comment]
@vncscoelho, ah, entendi. Valeu, mano!
