### ISSUE TITLE
[São Paulo] Front-End Developer JR na One Digital

### ISSUE THREAD

**Issue by Leocardoso94** [frontendbr/vagas#1202]
## Descrição da vaga

Aqui na [One Digital](https://one.com.br/) formamos um time multi-disciplinar composto por Designers e Programadores que acreditam no melhor que cada tecnologia tem a oferecer. Não só viabilizamos como buscamos ter papel ativo e decisivo na concepção criativa dos projetos.

Então buscamos uma pessoa que esteja disposta a aprender e ajudar bastante nessa nova jornada.

## Local

Av. Brasil, 2016 - São Paulo, SP

## Benefícios

- Vale-transporte
- Vale-refeição
- Assistência médica
- Assistência odontológica
- Auxílio creche

## Requisitos

**Obrigatórios:**
- Experiência com HTML e CSS
- Conhecimento básico em JavaScript
- Conhecimento íntimo entre os browsers
- Construção de páginas responsivas
- GIT
- Básico de command-line

**Desejáveis:**
- Criatividade e colaboração
- Debug
- Automação de processos
- Projetos pessoais
- Formação acadêmica em Análise e Desenvolvimento de Sistemas, Ciência da computação, Design Digital, Sistemas para Internet, Sistemas de Informação, etc.

## Contratação

CLT

## Nossa empresa

[One Digital](https://one.com.br/) é uma agência com 15 anos e DNA 100% digital. Trabalhamos com grandes clientes como Bradesco, Shopfácil, Autoline, Paraná Banco, Hydro, entre outros. Todas as contratações são CLT com benefícios de transporte, refeição, plano de saúde com cobertura odontológica. Trabalhamos com processos flexíveis que nos ajudam a organizar o dia-a-dia com mais eficiência e colaboração. 

## Como se candidatar

Basta [clicar aqui](https://trampos.co/oportunidades/140509) e se candidatar.

## Labels

- Alocado
- CLT
- Júnior

**Comment by juliano-nunes** [comment]
@viniciusrossi

**Comment by juliano-nunes** [comment]
@vinirossi

**Comment by vinirossi** [comment]
Mandei @juliano-nunes  mais uma vez obrigado por lembrar :)

**Comment by JhonataMorais** [comment]
Encerrada ? Tentei acessar e deu trampo indisponível :/

**Comment by Leocardoso94** [comment]
Fala @JhonataMorais , nós recebemos um número muito grande de aplicações e optamos por fechar novas candidaturas no momento.
