### ISSUE TITLE
[São Paulo] Front-End Developer na empresa Harlio

### ISSUE THREAD

**Issue by grobelr** [frontendbr/vagas#1205]
## Descrição da vaga

Vaga de Front-End Developer para ajudar na criação de uma nova plataforma e manutenção em alguns portais whitelabels já criados. O trabalho é parcialmente remoto e totalmente flexível em relação a horário.

## Local

Remoto Parcial - São Paulo - Vila Leopoldina (2x por semana no escritório)

## Requisitos

**Obrigatórios:**
- Conhecimento em JavaScript, ReactJS e SCSS
- Vontade de aprender! =D

**Desejáveis:**
- Conhecimento em GIT, GULP

**Diferenciais:**
- Conhecimento backend NodeJS, Python, Go
- Conhecimento AngularJS, VueJS
- MongoDB
- Cloud (AWS, GCP)

## Contratação

PJ a combinar

## Nossa empresa

A Harlio é um startup de criação de chatbots customizados para empresas. Trabalhando desde a concepção da idéia até a melhoria de bots!
Equipe pequena com ambiente aberto a novas idéias, criação e participação efetiva nos rumos da startup, bora aprender com a gente?

## Como se candidatar

Só enviar um email para ricardo.grobel@harlio.com com seu CV anexado, com o assunto: Vaga FrontEnd

## Labels

- Pleno
- Sênior
- PJ
- Remoto - Parcial

**Comment by felipepatricio** [comment]
Olá, sou de Fortaleza. Tem possibilidade de ser Full Remoto?
