### ISSUE TITLE
[São Paulo] Desenvolvedor Javascript Pleno

### ISSUE THREAD

**Issue by matmarsiglio** [frontendbr/vagas#121]
## Descrição da vaga

Projeto em NodeJS com React, com um ótimo desafio técnico, numa equipe nova e cheia de motivação para desenvolver coisas incríveis.

## Local

Evino - São Paulo, Consolação.

## Benefícios

- Frutas e bolachas a vontade;
- Wine Fridays (toda sexta degustação de vinhos por nossa conta! Aliás, precisamos conhecer com o que trabalhamos, não? 😅 );
- VR;
- VT;
- Plano de saúde;
- Plano odontológico.

## Requisitos

**Obrigatórios:**
- Tenha alguma experiência com SPA's
- Já tenha trabalhado em algum projeto com NodeJS

**Desejáveis:**
- Conhecimento básico de programação funcional;
- Já tenha trabalhado com projetos React

**Diferenciais:**
- Projetos opensource
- Ativo de alguma forma na comunidade de desenvolvimento

## Contratação

CLT

## Nossa empresa

A Evino é um e-commerce de vinhos, que está com foco em estar atualizada no mercado de tecnologia, com aplicação de novas tecnologias, investimento em comunidade e querendo se tornar uma das melhores empresas para se trabalhar em 2017. O crescimento mensal da empresa fez com que investíssemos numa equipe focada nesse projeto novo para construir uma nova plataforma desafiadora que exige um time com nível alto profissional em diversos sentidos.

## Como se candidatar

Por favor envie um email para matheus.marsiglio@evino.com.br com seu CV anexado, sua pretensão salarial, perfil do LinkedIn e perfil do GitHub, com o assunto: [JAVASCRIPT DEVELOPER] - {seu nome}.

**Comment by eduardojmatos** [comment]
Excelente vaga! 

*degustação de vinhos ❤️

**Comment by MarcoBrunoBR** [comment]
Vinho é amor :-)

**Comment by LFeh** [comment]
<3

**Comment by camilatigre** [comment]
@matmarsiglio 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by matmarsiglio** [comment]
@camilatigre b) não. 👍  😄
