### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor Front-End na Intercase

### ISSUE THREAD

**Issue by rafalcao** [frontendbr/vagas#1210]
## Descrição da vaga

Trabalhar com Magento 1 e 2 (melhores práticas), aplicações Web e Mobile (React e React native).

## Local

Presencial em Rio de Janeiro, RJ - Barra da Tijuca

## Benefícios

- Vale alimentação
- Vale transporte

#### Diferenciais

- Informal
- Horários flexíveis
- Aberta a novas idéias e sugestões

## Requisitos

**Obrigatórios:**
- HTML5
- CSS3 / Pré processador (Sass, Stylus ou Less)
- JavaScript (React, React Native)
- Conhecimentos em Git
- Disponibilidade para viagens

**Desejáveis:**
- BEM, SMACSS, OOCSS
- Boas práticas de SEO e Acessibilidade
- Conhecimento básico de PHP e XML
- Scrum
- Linux / OSX

**Diferenciais:**
- Algum framework JavaScript (React, Angular ou Vue)
- Docker
- Experiência com E-Commerce (Magento)

## Contratação

CLT ou PJ a combinar

## Nossa empresa

A Intercase é uma empresa focada em e-commerce. Desenvolvemos e-commerces inovadores, seguros e com alto padrão de qualidade, além de oferecer diferenciais competitivos aos nossos clientes, através de estratégias e soluções alinhadas às peculiaridades de cada negócio.

## Como se candidatar

Por favor envie um email para rafael.falcao@intercase.com.br com seu CV anexado - enviar no assunto: Vaga Frontend

## Labels

- Alocado
- Pleno
- CLT
- PJ

**Comment by thiagocruzrj** [comment]
CV enviado !
