### ISSUE TITLE
[São Paulo] Estagiário Front end UI na Beetech

### ISSUE THREAD

**Issue by lucasdaiki** [frontendbr/vagas#1211]
## Descrição da vaga

Olá! Procuramos Fronts para atuarem junto à área de Marketing/Design auxiliando na criação de Landing Pages, email marketings e na manutenção do [Bee Pollen](https://github.com/BeeTech-global/bee-pollen), nosso doce Design System 🍯.

## Local

Escritório, São Paulo - Faria Lima

## Benefícios

 - Bolsa-auxílio: R$1.500,00 + VT R$440,00

### Diferenciais

- Aprendizado contínuo
- Grupos de estudo
- Tech talks e tech days internos
- Um monte de dev da hora para te ajudar nessa jornada

**Requisitos**

* Necessário cursar graduação em TI ou áreas relacionadas (pode até ser Design o/) e disponibilidade para estagiar 30 horas semanais de segunda a sexta.

**Desejáveis:**
* HTML
* CSS
* JavaScript/jQuery
* Noções de UX

**Atribuições**

* Evolução técnica constante o/ _(💖 mostraremos o caminho 💖)_
* Criação/Manutenção de Landing Pages no HubSpot
* Criação/Manutenção de emails marketings e transacionais
* Manutenção de blogs em WordPress _(apenas HTML/CSS)_

### Habilidades que você aprenderá 🎓

* SASS
* Bootstrap
* GIT
* WordPress - basicão
* SEO
* +JavaScript/jQuery
* React

## Contratação

Estágio

## Nossa empresa

A BeeTech Global é uma holding com a missão de conectar pessoas a serviços financeiros com processos simples, transparentes e focados no usuário. Nossos rebentos incluem:

* [BeeCâmbio](https://www.beecambio.com.br) - Primeira correspondente cambial brasileira totalmente online 🥇
* [Remessa Online](https://www.remessaonline.com.br/) - Plataforma de transferências internacionais :left_right_arrow:

## Como se candidatar

Se, ANTES DE TUDO, seu coração palpitou com a nossa missão e cultura _(vide [Bee a Member](https://github.com/BeeTech-global/bee-a-member))_ e você curtiu o desafio, acesse este [Link](https://signup.kenoby.com/#/candidatos/me?position=5b52442d0a547a1a356f6708&tenant=5ac5085bd3a98b2b12beabff&jobsite=beetech&positionName=Est%C3%A1gio%20em%20Front-End%20/%20UI&applicantSource=&utm_source=) e inicie o processo o/

_*#LetPeopleBeeGlobal*_

## Labels

- Alocado
- Estágio

**Comment by marnescassule** [comment]
Oii.... Boa Tarde!!!
Está vaga ainda está disponível?

**Comment by lucasdaiki** [comment]
Oi, @marnescassule . Está sim :)

**Comment by ViniciusGularteMartin** [comment]
Estagio somente alocado sem possibilidade de remoto ?
