### ISSUE TITLE
[Remoto] Full-stack Developer na Rocketseat

### ISSUE THREAD

**Issue by cleitonsouza** [frontendbr/vagas#1212]
Para que possamos ajudar ainda mais na evolução dos nossos alunos estamos buscando um dev fullstack para se juntar ao time :rocket:️

Você vai trabalhar no desenvolvimento de ferramentas internas como o nosso sistema de back office e no desenvolvimento da nossa plataforma de educação: o Station. Você vai utilizar tecnologias como Traefik, GraphQL, Apollo, NextJS, Strapi, React Native, Docker, AdonisJS entre outras.

## Local

Remoto ou Escritório, Rio do Sul / Santa Catarina

## Requisitos

**Obrigatórios:**
- NodeJS
- ReactJS
- Git

**Desejáveis:**
- SQL

**Diferenciais:**
- Docker
- Adonis

## Contratação

Imediata no regime PJ, salário inicial é de R$ 4.500 a R$ 6.000.

## Nossa empresa

A Rocketseat além de uma comunidade de programadores, é uma plataforma de educação online que entende que em um mundo onde a informação fica obsoleta cada vez mais rápido, velocidade de aprendizado é a chave para o sucesso.

Por isso oferecemos através de uma plataforma inteligente e metodologia prática, além de comunidade, eventos, conteúdo e conexão com o mercado de trabalho, todas as ferramentas que os devs precisam para masterizar no menor tempo possível as tecnologias mais modernas de desenvolvimento web e mobile, e dessa forma avançar para o próximo nível como programador.

## Como se candidatar

Envie um e-mail para cleiton@rocketseat.com.br com o assunto "DEV", contando um pouco sobre você, sua experiência, projetos que você já participou, seus objetivos como programador, e perguntando o que você quiser saber sobre a gente :wink:

**Comment by luizfelipehh** [comment]
Enviado
