### ISSUE TITLE
[São Paulo/SP] Front End Developer na MJV Technology & Innovation

### ISSUE THREAD

**Issue by RHRJ** [frontendbr/vagas#1213]
MJV Technology & Innovation, consultoria dedicada a transformar negócios e solucionar desafios complexos para levar ao mercado soluções inovadoras em produtos e serviços, está busca de alguns Back - End para atuar em cliente no ramo financeiro!

A nossa matriz é carioca mas estamos presentes em São Paulo, Curitiba e em unidades internacionais nos EUA, França, Inglaterra, Itália e Portugal.

A MJV acredita que uma equipe colaborativa enriquece a qualidade do nosso trabalho e produz resultados transformadores.

### **Requisitos:**

- HTML5/ CSS3 (Pré processadores SASS / LESS)

- Javascript (ES6+)

- Typescript

- SPA (Vue.js/Angular)

- Webpack

- NPM

- UX

- Ferramentas de controle de versão (TFS / GIT)

### **Diferencial:**

- Conhecimento no mercado financeiro

**Contrato**: CLT + benefícios padrões.

**Local de atuação**: Vila Olímpia - SP

_Interessou? Envie seu CV para marla.mello@mjv.com.br com o título "front end SP"_

### Labels
CLT
Alocado
Pleno
Sênior

**Comment by eduardojmatos** [comment]
A contratação é pra MJV ou pra uma empresa terceira?

**Comment by eduardojmatos** [comment]
Hum, saquei. Então vocês são uma consultoria outsourcing ou fazem hunting pra empresas?

**Comment by RHRJ** [comment]
Somos uma consultoria de TI & Inovação e fazemos outsourcing para os nossos clientes.
