### ISSUE TITLE
[São Paulo] Front-End Developer Vuejs na Bliive

### ISSUE THREAD

**Issue by tisciencia** [frontendbr/vagas#1214]
## Descrição da vaga

Vaga para Front-End Developer Vuejs na Bliive

## Local

Remoto ou Escritório, São Paulo

## Responsabilidades

- Participar desde a ideação e concepção de produtos e serviços, até sua entrega e sustentação
- Fazer escolhas e/ou discussões das tecnologias que serão empregadas em cada projetos
- Assegurar a excelência técnica e boas práticas nos projetos
- Participar e contribuir com projetos utilizando metodologias de entrega ágil, integração contínua e desenvolvimento guiado por testes (TDD), técnicas de modelagem e pair programming
- Dar suporte para a expansão da nossa comunidade global de usuários e também atender projetos desafiadores com clientes

## Requisitos

- Experiência com práticas ágeis como Scrum, Kanban e XP
- HTML semântico
- Arquitetura CSS escalável e modular, conhecimento de padrões como SMACSS, BEM, etc
- Experiência em como lidar com problemas de cross browsers
- Conhecimento em boas práticas de otimização para Web
- Conhecimento em SEO
- Saber como implementar testes em JS
- Experiência com Vuejs ou React
- Conhecimento em como gerenciar estados de aplicações complexas no front-end
- Saber como projetar um aplicativo para que seja fácil de alterar
- Git

## Contratação

PJ a combinar

## Nossa empresa

A Bliive é uma startup brasileira referência mundial em economia colaborativa. Nossa plataforma de troca de tempo conta com mais de 140.000 usuários em todo o mundo. Recentemente lançamos nossa nova plataforma (um marketplace - Peer to Peer) e, com ela, vários desafios para 2018 que serão assumidos pelo desenvolvedor junto ao time da Bliive.
Acreditamos que a tecnologia é a chave para inovação, mas são as pessoas o nosso maior ativo.

## Como se candidatar

Por favor envie um email para tiago@bliive.com com seu CV anexado - enviar no assunto: Vaga Front-end Developer

## Labels

- PJ
- Remoto - Parcial
- Pleno
- Sênior

**Comment by malacela** [comment]
CV enviado.

**Comment by denisibanez** [comment]
Enviado!
