### ISSUE TITLE
[Remoto] Front-End Developer na Citar.tech

### ISSUE THREAD

**Issue by meneguite** [frontendbr/vagas#1215]
![Citar.tech](https://s3-sa-east-1.amazonaws.com/citar.tech/assets/developers/dev-citar-tech.png)

### O que nós buscamos
- Responsável por desenvolver, testar e documentar rotinas;
- Atuar em implementações, melhorias de performance e integrações; 
- Desenvolver códigos bem estruturados utilizando boas práticas de programação;
- Realizar revisão por pares dos artefatos de programação; 
- Interagir com todo o time Scrum de forma construtiva na busca por resultados que agreguem valor aos clientes; 
- Construir código com testes automatizados/unitários para garantir a qualidade.

## Local
Remoto

## Requisitos:
- HTML, CSS, SASS;
- Javascript ES6;
-  ~Angular 2+ ou~ VueJs 2;
- Consumo de Rest APIs;
- Noções básicas de scrum e metodologias ágeis;
- Domínio do Git para versionamento de projetos;

## Diferenciais:
- Experiência com testes unitários usando Jest ou Mocha;
- Experiência na utilização do docker;

## Contratação

CLT ou PJ

## Como se candidatar

Por favor envie um email para rh.dev@grupocitar.com.br com seu CV anexado ou link do linkedin - enviar no assunto: Vaga Frontend

## Labels

- Remoto - Total
- CLT ou PJ
- Pleno
- Sênior

**Comment by brunokunace** [comment]
enviado =)

**Comment by ribeiroevandro** [comment]
Enviado.

**Comment by meneguite** [comment]
@fafa1 de inicio decidimos remover o desafio que normalmente era um requisito, hoje tendemos a tentar aproveitar algo que o usuário já tenha previamente se envolvido como projetos open source por exemplo, assim apenas caso não seja possível identificar a proficiência pelo que o usuário nos passa como referência, solicitamos um teste simples complementar para nos auxiliar no processo de decisão.

**Comment by flavianunes** [comment]
Enviado :heart:

**Comment by wesleymreng7** [comment]
Enviado!

**Comment by abelclopes** [comment]
enviado!

**Comment by AlexandreRStos** [comment]
@fafa1 tem algo para iniciante como eu? [curriculum](https://alexandrerstos.github.io/about.html)

**Comment by meneguite** [comment]
Boa noite Srs.. venho agradecer a todos que se inscreveram em nosso processo seletivo. Tivemos acesso a ótimos desenvolvedores e conseguimos completar nossa equipe por hora. É bem provável que em um futuro próximo precisemos de novos devs.. mas por hora nosso processo seletivo está pausado.

**Comment by adeonir** [comment]
Oi @meneguite , enviei email e não tive feedback...
