### ISSUE TITLE
[Remoto] Vaga React Native Developer na startup Americana Citifyd

### ISSUE THREAD

**Issue by gaprl** [frontendbr/vagas#1217]
## Descrição da vaga

A Citifyd.com tem sede em Portland, OR e estamos tentando solucionar vários problemas no mercado de urban mobility, com um foco especial em serviços de estacionamento. Estamos aumentando nossa equipe de desenvolvedores Brasileiros para trabalhar no nosso front-end em React Native.

Mais informações sobre nossa empresa: www.citifyd.com

## Local

Completamente remoto! 👨‍💻 

## Benefícios

- 💰 Excelent remuneração.
- 🕐 Horas flexíveis.
- 📈 Oportunidade de entrar na equipe de uma startup pequena, e crescer junto com a empresa.

## Requisitos

**Obrigatórios:**
- 🇺🇸 Excelente Inglês, dado que boa parte de nossas comunicações são em Inglês
- 👨‍🏫 Conhecimento sólido em Javascript, e você tá sempre ligado com as boas práticas do mercado.
- 📱 Experiência prévia com React Native.
- 🌎 Habilidade de participar de uma equipe internacional, diversa, e em um ambiente extremamente dinâmico (nós somos uma startup!).

**Desejáveis:**
- 🧠 Familiaridade com Git, Agile, RESTful APIs, GraphQL, Redux, recompose, testes.
- 👨‍🎨 Uma ótima atenção ao detalhe, e paixão por criar boas experiências e interfaces para o usuário. 

## Contratação

PJ

## Como se candidatar

Por favor envie um email para hackers@citifyd.com com seu CV anexado - enviar no assunto: Vaga React Native. Por favor inclua qualquer projetinho em React Native que você já trabalhou. 😄 

## Labels

- PJ
- Pleno
- Remoto - Total
- Sênior

**Comment by calebearruda** [comment]
olá @gaprl ainda estão selecionando?

**Comment by gaprl** [comment]
Opa @calebearruda estamos sim. Pode mandar o CV (em inglês por favor!).

**Comment by zeucxb** [comment]
@gaprl já contrataram?

**Comment by erivaldodantas** [comment]
@gaprl Boa noite, ainda estão contratando? Tenho quase 8 anos de experiência e quase 3 anos com React Native, tenho também experiência com Android Nativo. Porém meu inglês não é avançado, teria chance? Se sim, enviarei meu currículo. 

Grato.

**Comment by gaprl** [comment]
Vaga preenchida. Obrigado a todos que aplicaram! Postarei mais vagas aqui se tivermos aberturas no futuro.
