### ISSUE TITLE
[Curitiba] Front-end React Native na MEGA SISTEMAS

### ISSUE THREAD

**Issue by adrianetq** [frontendbr/vagas#1219]
## Descrição da vaga

Estamos a procura de front-end developer com experiência em React Native para um freela de mais ou menos 3 meses alocado fulltime em CURITIBA.

O foco é desenvolver a interface de aplicativos de acordo com as definições de design e usabilidade definidas pelo nosso time de UX, construindo sistemas front-end eficientes para escalar.

Você irá trabalhar junto com outros desenvolvedores do nosso time que dominam a regra de negócio e utilizando metodologia Scrum.

## Local

Esta vaga é somente para trabalho alocado aqui no escritório.
Av Sete de Setembro, 4476, Batel, Curitiba - PR

## Requisitos

**Obrigatórios:**
- HTML/CSS/Javascript
- Mobile first
- Experiência em desenvolver interfaces mobile com framework React Native e JavaScript
- Disposição para trabalhar em ambiente colaborativo

**Desejáveis:**
- Conhecimento de arquitetura de aplicações de grande porte

## Contratação

Freela a combinar
Alocado fulltime
Tempo aproximado de 3 meses

## Nossa empresa

A Mega Sistemas (www.mega.com.br) é uma produtora de software ERP para gestão empresarial. Estamos com desafios de reinventar nossas soluções através de aplicativos que promovam uma ótima experiência do usuário. Se você gosta de quebrar paradigmas, irá somar muito bem nosso time.

## Como se candidatar

Por favor envie um e-mail para adriane.quintas@mega.com.br com seu perfil do Linkedin e Portfolio
Enviar no assunto: Quero esse freela de React-Native

## Labels

- Alocado
- Freela
- Pleno ou Sênior

**Comment by marcelobarbosaO** [comment]
rola um remoto não?

**Comment by adrianetq** [comment]
oi @marcelobarbosaO, estamos buscando preferencialmente alocado no escritório, mas podemos conversar. vc pode me passar seu linkedin e portfolio para meu e-mail: adriane.quintas@mega.com.br?

obrigada!

**Comment by adrianetq** [comment]
Vaga preenchida por fora. Obrigada.
