### ISSUE TITLE
[Curitiba] Designer / Frontend / Client Side Developer

### ISSUE THREAD

**Issue by raloliver** [frontendbr/vagas#122]
O dev/designer vai trabalhar numa plataforma web com clientes em todo o Brasil.
Não vai virar noites trabalhando, nem ficar fazendo banco de horas!
O ambiente é bacana, somos "a família do amor", mas nosso trabalho é nosso trabalho, não nossa casa.
## Informações essenciais
- Projetar, construir e otimizar interfaces web e mobile _(Responsivo e Mobile First)_. 
- Designer UX/UI atuando na implementação técnica _(HTML, CSS, JS)_. 
- Papel ativo na aplicação da identidade visual, usabilidade e ergonomia _(no que diz respeito a interface web e mobile_).
- Não vai atuar implementando regras de negócio _(Escrever HTML para telas do lado do clientes, mas muito JS rodando junto do lado do cliente)_.
## Local

Nossa empresa fica em Curitiba - PR no Parque De Software
## Benefícios
- Horário flexível ( 8 horas entre as 08:00 e 20:00 )
- As melhores máquinas sempre são dos devs
- Frigobar sempre cheio :P
- Estar rodeado de pessoas que pensam da mesma maneira
- Oportunidade de crescimento num ambiente em constante mudança
## Requisitos técnicos necessários

**Obrigatórios (Soft Skills):** _O que faz as pessoas felizes?_
1. Gostar do que faz
2. Colaboração
3. Transparência
4. Compartilhamento
5. A Comunicação Deve Funcionar
6. Respeito Mútuo (relacionamento)
7. Confiança no Time
8. Objetivo Compartilhado
9. Filosofia Startup (erre rápido e erre barato)
10. "Be the water my friend"

**Nível de conhecimento de 1 a 5 (Hard Skills)** _Vamos falar de código!_
- Javascript (4)
- AngujarJS (4)
- HTML5 (3)
- CSS3 (3)
- GIT (2)
- NPM e Bower (2)

**Diferenciais:**
- Material Design e Angular Material
- Noções de UX/UI
- Automatização de tarefas (Gulp, Grunt)
- Pré-processadores (SASS, LESS)
- Testes unitários (Karma e Protactor)
- SCRUM e Métodos Ágeis

**Diferenciais Extra:** _Você assistiu pelo menos um desses filmes?_
- [x] Matrix (1999)
- [x] Clube da Luta (1999)
- [x] Prenda-me Se For Capaz (2002)
- [x] O Poderoso Chefão (1972)
- [x] Jerry Maguire (1996)
- [x] Os Suspeitos (1996)
- [x] Batman - O Cavaleiro das Trevas (2008)
## Contratação

PJ a combinar (Alocado, PJ, Pleno)
## Nossa empresa

Depois de aprender muito em várias startups e sem reter clientes ou mesmo gerar leads, decidimos aprender a vender de verdade. O Marketing Digital abriu caminho para conexões incríveis, e escalar nosso negócio em direção ao sucesso ficou mais claro. No decorrer do caminho, descobrimos o que deveríamos fazer, não apenas pensando em números, mas em ajudar muitas pessoas a vender mais, com amor. 

**Nossa Missão** 
Facilitar e automatizar os processos de quem busca empreender de forma digital, através de plataformas que contém serviços integrados em constante inovação.

**Nossos Valores**
- Amor
- Comunicação
- Honestidade
- Liberdade
- Integração
- Inovação

**Não Toleramos**
- Procrastinação
- Falta de comprometimento
- Mentira
- Desrespeito
- Negligência
- Mi Mi Mi
## Como se candidatar

_(Se quiser ser direto, manda email para rh@leadlovers.com)_

_Deixe nos comentários algumas respostas:_
1. Como você gosta de trabalhar?
2. Como você imagina um ambiente ideal de trabalho?
3. O que você está estudando?
4. Vai a eventos? Qual foi o último que foi?
5. Escreve? Tem blog? Vídeos? Produz conteúdo de forma independente?
6. Sabe o que é conversão (ROI)? Entende de Teste A/B? Já capturou algum lead hoje?
7. Diga o que acha deste vídeo: https://vimeo.com/183691821

> Os primeiros 5 que responderem a todas as perguntas e enviarem por email, vão conversar comigo via skype para mais informações sobre a vaga.

**Comment by CiroMotta** [comment]
1. Digamos que as vezes sou até viciado em trabalho e estudo, minhas férias da faculdade eu sempre aproveitei para fazer cursos
2. Que tenha sempre respeito, com o cliente e com o colaborador
3. No momento estou elaborando o TCC do meu tecnólogo em análise e desenvolvimento de sistemas (Positivo)
4. Não costumo ir a eventos
5. eu gosto de ajudar no GIT, mas não tenho tido muito tempo
6. Como meu foco sempre foi a programação, eu não procuro entrar no marketing de mineração mas sim no tratamento a clientes.
7. A musica e as imagens são agradáveis, mas não tem muita informação do que se trata, se não tivesse procurado sobre não saberia o que estava visualizando.

**Comment by raloliver** [comment]
A vaga continua aberta ;)

**Comment by LFeh** [comment]
Vou compartilhar.

**Comment by Cleysonlb** [comment]
Gostei mt da parte "nivel de conhecimento" essa ideia de "1 a 5" é mt eficiente 💃

**Comment by LFeh** [comment]
Também gosto.

**Comment by suissa** [comment]
Mais html q css e js??

Eh mta acessibilidade e semântica hein eeehheheheh

**Comment by Hanor** [comment]
Olá, encaminhei meu currículo para o email indicado, quanto as respostas das perguntas feitas, aqui estão:

1 - Trabalho com desenvolvimento a mais ou menos 4 anos, possuo sólidos conhecimentos em: Javascript/HTML/css/Jquery, three.js, d3.js, bootstrap, websocket, RPC, NODE.js, mongodb. Com estes conhecimentos já fui capaz de criar: Chat em tempo real(com websocket, node.js, javascript/HTML/Css e afins), criei um sistema de BPMN onde o diferencial era o design de workflows no próprio browser e a robusta execução deste workflow(com Node.js, Java, Javascript/Html(Jquery, bootstrap, D3.js) e MongoDB), criei um sistema que gerenciava componentes de configuração de rede(no ultimo emprego que era uma empresa de telecomunicações) e era capaz de desenhar o mapa e os relacionamentos entre os componentes de rede(com Node.js(websocket para um chat que havia no sistema), javascript/Html(jquery, Bootstrap, D3.js e outras libs do javascript), mongoDB), estou desenvolvendo for fun um game denominado vaders onde você controla uma nave e seu objetivo é destruir as outras naves e vencer a partida(com mongodb, node.js, javascript/html(THREE.js - canvas, webgl, jquery e afins). Resumidamente, estes foram meus principais desenvolvimentos nos últimos anos,  atualmente para a faculdade estou desenvolvimento uma ferramenta de processamento de imagens feita com javascript/html(canvas, jquery, bootstrap e outras), até meu TCC foi feito em Javascript hahhahaha inclusive, está aqui no github em meu repositório. Em outras palavras, eu sou quem estão procurando simplesmente pelo fato de ser um estudioso e adorar inovação e pela descrição de vocês, trabalhar ai seria uma troca equivalente, ou seja, iriamos evoluir JUNTOS.

2 - Dos filmes ali citados, já assisti a quase todos hahshshd "Morra héroi ou viva o suficiente para ver você mesmo se tornando o vilão" - Cavaleiro branco de gotham no filme: Batma, o cavaleiro das trevas.

3 -
 HTML5 - meu conhecimento é 4.999, pois, nem sempre sabemos de tudo sobre algo.
Javascript - meu conhecimento é 4.999, pois, nem sempre sabemos de tudo sobre algo.
CSS3  - meu conhecimento é 4.
AngujarJS  - meu conhecimento é 3
GIT - meu conhecimento é 4.999, pois, nem sempre sabemos de tudo sobre algo.
NPM - meu conhecimento é 4.999, pois, nem sempre sabemos de tudo sobre algo.
Bower - 1

4 - Os valores me agradam, pois, sigo os mesmoss

Perguntas:

1. Como você gosta de trabalhar?

Em um ambiente onde eu possua desafios e amigos, pois, os amigos nos ajudam a relaxar e os desafios nos ajudam a evoluir.

2. Como você imagina um ambiente ideal de trabalho?

Com bons colegas de trabalho e muitos desafios a serem solucionados de forma sistêmica

3. O que você está estudando?

Estou cursando Ciência da Computação e além do que há em meu curso, procuro sempre estar por dentro das novas tecnologias e aprofundando meus conhecimentos no que já sei, pois, o que sabemos sobre algo nunca é tudo.

4. Vai a eventos? Qual foi o último que foi?

Antigamente ia bastante a eventos diversos, desde seminários e palestras até jogos de futebol e eventos que envolvam alguns jogos que jogo. Atualmente, somente á palestras na faculdade. A ultima palestra que assisti se chamava: A internet das coisas, era uma palestra ofertada pela Microsoft que visava nos situar em como o arduino, netduino, raspberry e afins, podem tornar até mesmo uma planta um hotspot ou um mecanismo que amplie a condição humana.

5. Escreve? Tem blog? Vídeos? Produz conteúdo de forma independente?

Tai, não. Agora eu me pergunto: Porque não ? hahahaa

6. Sabe o que é conversão (ROI)? Entende de Teste A/B? Já capturou algum lead hoje?

Nunca ouvi falar. Poderia ir no google e perguntar, porém, estaria mentindo ao responder as questões uma vez que meus conhecimentos iriam surgir após a pesquisa hahahaha.


7. Diga o que acha deste vídeo: https://vimeo.com/183691826

A natureza é linda, perfeita e a vida nos ensina que a união é a força.

**Comment by ribeiroevandro** [comment]
O vídeo informado não está mais disponível... 
![screen shot 2016-10-20 at 06 19 37](https://cloud.githubusercontent.com/assets/943553/19552115/3e6715ac-968d-11e6-994e-2dc82a6e2f3a.png)

**Comment by raloliver** [comment]
Vlw por informar vou colocar no drive hj.

**Comment by paulo101977** [comment]
A url do vídeo é https://vimeo.com/183691821 e não https://vimeo.com/183691826

**Comment by Hanor** [comment]
Eu sei, ao digitar coloquei errado. Irei corrigir ali.
