### ISSUE TITLE
[São Paulo] Front-End Developer na Influu

### ISSUE THREAD

**Issue by ValdirNp** [frontendbr/vagas#1221]
## Descrição da vaga
A http://influu.me está procurando um WebDesigner/Front-end

- Criação de layouts
- Bootstrap, HTML 5, CSS3 e Javascript são fundamentais

## Local
Próximo ao metrô Faria Lima, São Paulo

#### Diferenciais
- Ambiente descontraído
- Atividades de lazer uma vez por mês
- Ambientes de descanso e lazer
- Mentorias
- Participação em eventos
- Lanchinhos

## Contratação
CLT ou PJ, a depender do valor solicitado pelo profissional.

## Nossa empresa
A influu é um ecossistema de influenciadores digitais que tem como objetivo principal a profissionalização dos mesmos por meio de eventos e campanhas de publicidade.

## Como se candidatar
Envie um email com PORTFÓLIO e PRETENSÃO para henrique@influu.me e valdir@mobocity.com

## Labels
- Alocado
- CLT
- PJ
- Júnior
- Pleno

**Comment by ValdirNp** [comment]
Gente, obrigado!
Recebemos vários currículos, e encontramos uma pessoa para suprir nossa necessidade.

Caso haja mais alguma novidade ou oportunidade, entraremos em contato.

**Comment by adeonir** [comment]
@ValdirNp possibilidade de ser remoto?

**Comment by ValdirNp** [comment]
@adeonir Não, procuramos alguém pra ficar alocado mesmo.
