### ISSUE TITLE
[Portugal] Frontend Developer na Aubay

### ISSUE THREAD

**Issue by monicantunes** [frontendbr/vagas#1225]
## Descrição da vaga

Projetos em vários setores de atividade, usando diversas tecnologias de Front End tal como Jquery, Angular entre outras

## Local

Portugal: Lisboa e Porto

## Benefícios

• Plano de saúde
• Visto de Trabalho para Portugal
• Outras

#### Diferenciais

• Formações técnicas e comportamentais 
• Prémios de referências de recrutamento
• Eventos team Building
• Convívio mensal
• Oferta de aniversário

## Requisitos

**Obrigatórios:**
• Experiência profissional na área web
• Bons conhecimentos de Javascript, HTML, CSS
• Experiência na framework Angular
• Fluência na língua Inglesa

**Desejáveis:**
• Experiência em Node.js/React

**Diferenciais:**
• Experiência internacional

## Contratação

Apoio em todo o processo para obtenção de visto de trabalho para Portugal.

## Nossa empresa

A Aubay, é uma empresa de origem francesa presente em diversos países na Europa.
Como cerca de 6000 pessoas desenvolvemos projetos nas mais diversas tecnologias.
Neste momento, temos várias vagas em aberto para várias posições.

## Como se candidatar

Por favor envie um email para mantunessilvestre@aubay.com com seu CV anexado.

**Comment by malacela** [comment]
CV enviado.

**Comment by marcelobarbosaO** [comment]
pode ser remoto?
