### ISSUE TITLE
[Portugal] Front End Developer - ReactJS e React Native - Aubay

### ISSUE THREAD

**Issue by FernandaMorais** [frontendbr/vagas#1227]
Projetos Internacionais a partir de Portugal (Lisboa/Porto)
## Local

Lisboa/Porto

## Benefícios

- Plano de saúde
- Suporte ao processo de visto
- fridge benefits em vigor na Aubay

#### Diferenciais

- monthly meet ups com bebida e comida
- frigobar sempre cheio :P

## Requisitos

**Obrigatórios:**
-  Experiência com ReactJs e/ou React Native

**Desejáveis:**
- conhecimentos em ruby on rails
- conhecimentos em Angular
- conhecimentos em GO

## Contratação

A combinar

## Nossa empresa

www.aubay.pt 

## Como se candidatar

Por favor envie um email para fmorais@gmail.com com seu CV anexado - enviar no assunto: Vaga React

**Comment by patriciob00** [comment]
Essa vaga ainda está disponivel ?

**Comment by FernandaMorais** [comment]
Ola bom dia,

Esta disponível sim.

Obrigado,


  [cid:image001.png@01D43088.433A3280] Fernanda Morais
  International Talent Recruiter

Edíficio Duque D´Ávila
Avenida Duque de Ávila, nº46 7C
1050-083 Lisboa
Tel: +351 211 928 417 - Mobile: +351 914 273 951
Skype: fmorais83


Antes de imprimir, pense no ambiente!


“Iremos utilizar informação pessoal que nos enviou, para considerar a sua candidatura à função relevante. Ao facultar-nos a sua informação por email e/ou em documentos, consente que a Aubay Portugal trate a sua informação pessoal. A sua privacidade é importante para nós. Por favor, consulte a nossa Política de Privacidade, que explica de que forma utilizaremos e armazenaremos a sua informação pessoal. Explica também os direitos que tem relativamente à sua informação e como pode contactar-nos para o esclarecimento de dúvidas ou pedidos.”

De: Patricio Bruno <notifications@github.com>
Enviada: 10 de agosto de 2018 01:10
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: Fernanda MORAIS <fmorais@aubay.com>; Author <author@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [Portugal] Front End Developer - ReactJS e React Native - Aubay (#1227)


Essa vaga ainda está disponivel ?

**Comment by FernandaMorais** [comment]
Ola Bom dia,

As vagas ainda se encontram em aberto sim.
Temos mais de 15 vagas neste momento em aberto na Aubay.

Obrigado,


  [cid:image001.png@01D4308F.12798F40] Fernanda Morais
  International Talent Recruiter

Edíficio Duque D´Ávila
Avenida Duque de Ávila, nº46 7C
1050-083 Lisboa
Tel: +351 211 928 417 - Mobile: +351 914 273 951
Skype: fmorais83


Antes de imprimir, pense no ambiente!


“Iremos utilizar informação pessoal que nos enviou, para considerar a sua candidatura à função relevante. Ao facultar-nos a sua informação por email e/ou em documentos, consente que a Aubay Portugal trate a sua informação pessoal. A sua privacidade é importante para nós. Por favor, consulte a nossa Política de Privacidade, que explica de que forma utilizaremos e armazenaremos a sua informação pessoal. Explica também os direitos que tem relativamente à sua informação e como pode contactar-nos para o esclarecimento de dúvidas ou pedidos.”

De: Patricio Bruno <notifications@github.com>
Enviada: 10 de agosto de 2018 01:10
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: Fernanda MORAIS <fmorais@aubay.com>; Author <author@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [Portugal] Front End Developer - ReactJS e React Native - Aubay (#1227)


Essa vaga ainda está disponivel ?

**Comment by luizfelipehh** [comment]
Bom dia,

Tem mais vagas disponíveis ? Se sim, quais?

**Comment by FernandaMorais** [comment]
Temos vagas para:

JAVA Developer
NodeJS Developer
AngularJS

São principalmente estas.

A Aubay ajudará em todo o processo de visto.

Obrigado,

  [cid:image001.png@01D430B2.B80208C0] Fernanda Morais
  International Talent Recruiter

Edíficio Duque D´Ávila
Avenida Duque de Ávila, nº46 7C
1050-083 Lisboa
Tel: +351 211 928 417 - Mobile: +351 914 273 951
Skype: fmorais83


Antes de imprimir, pense no ambiente!


“Iremos utilizar informação pessoal que nos enviou, para considerar a sua candidatura à função relevante. Ao facultar-nos a sua informação por email e/ou em documentos, consente que a Aubay Portugal trate a sua informação pessoal. A sua privacidade é importante para nós. Por favor, consulte a nossa Política de Privacidade, que explica de que forma utilizaremos e armazenaremos a sua informação pessoal. Explica também os direitos que tem relativamente à sua informação e como pode contactar-nos para o esclarecimento de dúvidas ou pedidos.”

De: luizfelipehh <notifications@github.com>
Enviada: 10 de agosto de 2018 12:41
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: Fernanda MORAIS <fmorais@aubay.com>; Author <author@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [Portugal] Front End Developer - ReactJS e React Native - Aubay (#1227)


Bom dia,

Tem mais vagas disponíveis ? Se sim, quais?
