### ISSUE TITLE
[Campinas] Front-end Developer na UPX Technologies

### ISSUE THREAD

**Issue by xthiago** [frontendbr/vagas#1232]
## Nossa empresa

A [UPX Technologies](https://www.upx.com/) é especialista em performance e segurança digital há 15 anos, conta com uma rede global em constante expansão e tecnologias disruptivas para a proteção da internet e de seus usuários. Responsável pela proteção de mais de 4 bilhões de dados, a UPX identifica vulnerabilidades e age em tempo real para combater ações maliciosas e prevenir incidentes de segurança digital por meio de SOC (Security Operation Center), NOC (Network Operation Center) e Scrubbing Centers, além de contar com desenvolvimento de tecnologia própria.

## Algumas tecnologias que usamos

- React, Redux, Jest, Storybook, Gatsby, Docker, GitHub, etc.
- e no back-end: PHP 7, MongoDB, Golang, etc.

## Oferecemos

- Horário de trabalho flexível.
- Time apaixonado por tecnologia e engajado com os objetivos de negócio.
- Ambiente que estimula o trabalho em equipe e troca de conhecimento - programação em par, dojos, code review, objetivos coletivos.
- Sem busca por culpados! Cultura que foca no aprendizado adquirido na resolução dos problemas.
- Incentivo à participação em eventos da área.
- Incentivo para estudos e inovação - tempo semanal para dedicar-se ao estudo de novas tecnologias e melhorias.
- Equipamento de ponta - MacBook Pro com monitor externo de 23"
- Apoio para comunidades de tecnologia - sediando e patrocinando eventos.
- Ambiente descontraído - Playstation 4, Tênis de mesa (ping-pong), Happy Hour toda sexta, etc.
- Quitutes periódicos
- Confraternizações trimestrais por conta da empresa.

## Responsabilidades

Possuímos um time de desenvolvimento chamado LABS com profissionais de front-end, back-end, design e operações, e estamos buscando mais desenvolvedores front-end para trabalhar no desenvolvimento destes projetos. Sua função como desenvolvedor front-end será:

- Ajudar a desenhar a arquitetura da aplicação.
- Garantir alta performance do front-end.
- Garantir baixo acoplamento e facilidade de refatoração.
- Escrever código limpo que é referência para os demais desenvolvedores.
- Escrever testes automatizados em JavaScript (unidade, aceitação, etc).
- Seguir as recomendações dos guias de código e ajudar a aprimorá-los.
- Revisar o código dos colegas de trabalho (code review), submeter seu próprio código para apreciação e compartilhar conhecimento com o time.
- Ajudar a aprimorar processos de integração contínua (CI) e deploy (CD).

Em resumo você atuará em uma equipe que possui uma metodologia de trabalho ágil/lean com foco na melhoria contínua, seu papel será integrar o time de front-end e ajudar a desenvolver os produtos da empresa.

## Local de trabalho

Presencial no escritório da UPX.
Rua Guapuruvu, 200 - Lot. Alphaville Campinas, Campinas - SP, 13098-322
https://goo.gl/maps/J748K2SUGaQ2

## Regime de contratação
PJ.

### Obrigatórios:
- Mais de 4 anos de experiência desenvolvendo aplicações web utilizando HTML, CSS e JavaScript (ES6+).
- Experiência com algum framework JavaScript moderno (React, Vue, Angular ou Polymer).
- Experiência com algum pré-processadores de CSS (SASS, LESS ou Stylus).
- Experiência com escrita de testes automatizados em JavaScript (Jest, Jasmine, Mocha, etc).
- Experiência com Single Page Applications (SPA).
- Capacidade para trabalhar com independência, definindo prioridades e com supervisão mínima em um time com autonomia.
- Capacidade de ler e escrever em inglês.

### Desejáveis:
- Contribuições para software livre e atuação em comunidades de desenvolvedores.
- Capacidade para conversar em inglês;
- Experiência de trabalho em equipes de desenvolvimento ágil.
- Experiência de trabalho em equipes com cultura DevOps.
- Experiência com git.
- Experiência com Docker.
- Familiaridade com tecnologias do lado do servidor (PHP, Golang, etc).

## Como se candidatar

Para se candidatar a vaga envie um email para labs@upx.com com o assunto: _Vaga Desenvolvedor Front-end Sênior_.

Na mensagem inclua a URL para seu Linkedin e/ou seu currículo em anexo. Se você possuir algum outro conteúdo relevante para a vaga, também inclua estes links. Exemplos: portfólio, GitHub, site, blog/vlog técnico e etc.

## Labels

- Alocado
- PJ
- Sênior

**Comment by xthiago** [comment]
@LFeh a label é `Sênior` - não pleno :)

**Comment by LFeh** [comment]
Sorry

**Comment by fernandosimoes** [comment]
Enviado =)

**Comment by xthiago** [comment]
@LFeh por que fechou?

Sempre estamos contratando.
