### ISSUE TITLE
[Vitória - Espírito Santo] Front-End Developer Pleno/Senior na Ginga.One

### ISSUE THREAD

**Issue by otaviomendesginga** [frontendbr/vagas#1234]
## Local

Escritório, Vitória - Espírito Santo - Enseada do Suá

## Requisitos

**Obrigatórios:**
- JavaScript
- CSS
- React
- Vue

## Contratação

PJ

## Nossa empresa

NÓS CRIAMOS OPORTUNIDADES E RESOLVEMOS PROBLEMAS ATRAVÉS DA TECNOLOGIA.
NÓS SOMOS A GINGA ONE.

## Como se candidatar

Enviar email para vagas@gingaone.com com o assunto **Front-End Developer Vitória**.

## Labels

- Alocado
- PJ
- Pleno
- Sênior

**Comment by rzorzal** [comment]
Vaga para VIX publicada aqui :+1: , espero que outras empresas façam o mesmo. Boa sorte na contratação.
