### ISSUE TITLE
[São Paulo] Front-End Developer Pleno/Senior na Ginga.One

### ISSUE THREAD

**Issue by otaviomendesginga** [frontendbr/vagas#1235]
## Local

Escritório, São Paulo - Av. Engenheiro Luís Carlos Berrini

## Requisitos

**Obrigatórios:**
- JavaScript
- CSS
- React
- Vue

## Contratação

PJ

## Nossa empresa

NÓS CRIAMOS OPORTUNIDADES E RESOLVEMOS PROBLEMAS ATRAVÉS DA TECNOLOGIA.
NÓS SOMOS A GINGA ONE.

## Como se candidatar

Enviar email para vagas@gingaone.com com o assunto **Front-End Developer São Paulo**.

## Labels

- Alocado
- PJ
- Pleno
- Sênior

**Comment by malacela** [comment]
CV enviado.
