### ISSUE TITLE
[São Paulo] Front-End React Home Office na [Exactworks]

### ISSUE THREAD

**Issue by kvilela** [frontendbr/vagas#1239]
## Descrição da vaga
Desenvolvedores Front React end Sênior
Ter disponibilidade para trabalhar em horário comercial, por mais que seja remoto

## Local
Remoto com reuniões presenciais semanais em São Paulo - Avenida Paulista

## Benefícios

- Plano de saúde
- VR 
- Infra para trabalhar remoto

## Requisitos

**Obrigatórios:**
Experiência com React, Bootstrap, HTML5 e Javascript

## Contratação

CLT / A-Combinar 

## Como se candidatar

Por favor envie um e-mail para contato@focoemvoce.com.br com seu CV anexado - enviar no assunto: Vaga React Native Remoto
Informar a pretensão salarial.

**Comment by greevin** [comment]
Só rola pra sênior? :/

**Comment by kvilela** [comment]
@greevin  não, a oportunidade é para todos os Desenvolvedores que se encaixe no escopo da vaga, se você tem experiência com React, HTML5, Javscript e Bootstrap envie o seu currículo.

Apesar da oportunidade ser remoto é necessário comparecer em reuniões semanais no cliente em São Paulo, por esse motivo o cliente solicita que o candidato seja residente de SP.
