### ISSUE TITLE
[Remoto] Front-End Developer na [Ello Político]

### ISSUE THREAD

**Issue by morais90** [frontendbr/vagas#1240]
Startup de consultoria política que se baseia na análise de dados legislativos procura
desenvolvedor front-end pleno para integrar equipe.

**Responsabilidades:**
- Dar manutenção e criar novas aplicações web para os produtos.
- Revisão de Pull Requests.
- Participar no planejamento e definições das aplicações.
- Se sentir dono e responsável pela evolução das aplicações.

**Requisitos:**
- Conhecimento em integração com API.
- VueJS / ReactJS (e seu ecossistema).
- Webpack.
- ES6.
- Bootstrap 4.
- Git.
- Testes automatizados.
- Compromisso com as entregas e proatividade.

**Sobre a equipe de trabalho:**
Um time de profissionais com altíssima qualificação, entusiastas e com foco na inovação e pesquisa.
Consultoria estratégica com vínculo a grupos de pesquisa da USP.
Rigor acadêmico na construção das análises e indicadores.
Não fazemos lobby, nem indicamos quem faça.
Os resultados gerados têm fundamentos científico, ou seja, não arredondamos análises nem dados para satisfazer clientes.

**Oferecemos:**
Trabalho remoto.
Flexibilidade de horário.
Contamos com apoio de estatístico (acadêmico) para auxiliar na construção de partes do sistema.
Remuneração (PJ) a combinar.

Ficou interessado? Envie seu currículo para selecao@ellopolitico.com.br com o título “Vaga Front-end Pleno <meu nome>”.

## Labels

- PJ
- Pleno
- Remoto - Total

**Comment by danielswater** [comment]
Enviado
