### ISSUE TITLE
[São Paulo] VB.NET/ASP.NET Developer Júnior na ROBERT HALF - PROJETO

### ISSUE THREAD

**Issue by RaquelTavaresL** [frontendbr/vagas#1241]
## Descrição da vaga

Suporte backend e frontend, manutenção em códigos do sistema legado em VB6.
Conhecimento necessári em VB.NET/ASP.NET. e SQL Server.

## Local

Escritório na região da Faria Lima (Pinheiros)

## Benefícios

- Plano de saúde e Odontológico Care Plus 100% sem custo e individual .
- Seguro de vida
- VR de R$ 550,00/mês
- VT ou reembolso de despesas (limite até 200,00)

## Requisitos

**Obrigatórios:**
- Experiência com manutenção e suporte a sistemas em VB.NET e ASP.NET
- Atuação com bano de dados SQL Server.

**Desejáveis:**
- conhecimento em VB6.

## Contratação
CLT Full - Projeto com possibilidade de internalização

## Como se candidatar

Por favor envie um email para raquel.lourenco@roberthalf.com.br com seu CV anexado.

**Comment by mtmr0x** [comment]
@RaquelTavaresL a vaga postada é para um cargo de back end, o que vai contra o propósito e regras do repositório. Mais informações aqui: https://github.com/frontendbr/vagas/blob/master/README.md

**Comment by LFeh** [comment]
Posta no @backendbr
