### ISSUE TITLE
[São Paulo] Front-End Developer na Wunderman 

### ISSUE THREAD

**Issue by Jonadersonmoura** [frontendbr/vagas#1242]
## Descrição da vaga

Vaga para front end junior na Wunderman Brasil

## Local

Escritório, São Paulo - Morumbi (próximo ao shopping market place)

## Benefícios

- Plano de saúde
- Plano odontológico
- Seguro de vida
- VR de R$ 33/dia
- VT
- PLR
- Fruta 2x ao dia

## Requisitos
- Html5
- Css3
- Jquery
- Javascript
- Git
- Gulp
- Responsivo
- Recortes de layout em photoshop e sketch

**Diferenciais:**
- CMS
- SPA
- ES6

## Contratação

CLT

## Nossa empresa

Wunderman brasil, uma das maiores agência de publicidade do brasil e faz parte do grupo WPP o maior grupo de publicidade do mundo, aqui, vc irá trabalhar direto para o cliente VIVO fazendo manutenções e criação de novas páginas.

## Como se candidatar

Por favor envie um email para juliana.molina@wunderman.com com seu CV anexado - enviar no assunto: Vaga Front End Junior

## Labels

- Alocado
- CLT
- Júnior
- Pleno

**Comment by victorcapelini** [comment]
Enviado.

**Comment by Jonadersonmoura** [comment]
valeu mano, esqueci de dizer que o início é imediato.
mas acho que a galera lê os comentários né.

**Comment by GHrenrique** [comment]
Enviado, com disponibilidade imediata.
