### ISSUE TITLE
[Curitiba] Front-End Developer na Locaweb

### ISSUE THREAD

**Issue by gguimaraesbr** [frontendbr/vagas#1243]
## Descrição da vaga

Buscamos pessoas apaixonadas por tecnologia que queiram se juntar ao nosso time
em Curitiba para trabalhar no desenvolvimento de um de nossos produtos digitais.

## Local

Escritório: Rua Conselheiro Dantas, 286 - Prado Velho (mudaremos no final de
Agosto para a Rua Nunes Machado, 68 – Centro)

## Benefícios

- Plano de Saúde e Odontológico SulAmérica
- Seguro de Vida em Grupo
- Vale-Refeição ou Vale-Alimentação no valor de R$ 18,56/dia
- Vale-Transporte
- Auxílio-Creche

## Requisitos

**Obrigatórios:**

- Escrever código de qualidade
- Comprometimento com resultados
- Organização e disciplina para trabalhar remotamente
- HTML5, CSS3, JS e ES6
- Frameworks JS (Vue, Angular, React ou similar)
- Pré-processadores CSS (Sass, Less ou similar)
- APIs REST
- Git (utilizamos o GitLab)

**Desejáveis:**

- Testes automatizados (Jasmine, Mocha ou similar)
- GraphQL
- Docker
- Ferramentas de build (Webpack, Brunch ou similar)

**Diferenciais:**

- Experiência com desenvolvimento de Single-Page Applications
- Padrões de CSS/HTML (OOCSS, BEM, Atomic ou similar)

## Contratação

CLT

## Nossa empresa

Na Locaweb, desenvolver vai muito além da tecnologia. Nosso propósito é ajudar
empreendedores do Brasil inteiro a prosperarem. Somos movidos pela paixão!
Viramos referência quando o assunto é internet, porque somos motivados pelo que
fazemos: desenvolver.

Somos a casa da internet no Brasil: temos um dos maiores data centers da América
Latina. Nossos serviços atendem milhões de usuários e nosso time de tecnologia
trabalha muito para manter tudo isso funcionando.

## Como se candidatar

- Envie um email para daniele.barbosa@locaweb.com.br com o assunto "[Curitiba]
  Vaga Front-End GH"
- Anexe seu CV e informe LinkedIn, GitHub e/ou site pessoal

## Labels

- Alocado
- CLT
- Pleno
- Sênior

**Comment by raloliver** [comment]
Enviei e-mail semana passada, mas ainda não tive resposta. A vaga ainda está aberta?

**Comment by gguimaraesbr** [comment]
@raloliver , fechamos esta vaga hoje com uma pessoa que aplicou através deste grupo.

Ainda temos uma oportunidade em São Paulo, caso lhe interesse: https://github.com/frontendbr/vagas/issues/1266

**Comment by LFeh** [comment]
Bacana @gguimaraesbr, felizes em ajudar :)
