### ISSUE TITLE
[Florianópolis] Front-End Developer na EXACT SALES

### ISSUE THREAD

**Issue by fromanexact** [frontendbr/vagas#1244]
## Descrição da vaga

Vaga para desenvolvedor ReactJS em uma das [100 startups to watch](https://revistapegn.globo.com/Startups/noticia/2018/04/100-startups-brasileiras-para-ficar-de-olho.html): [Exact Sales](https://www.exactsales.com.br). Início imediato.

## Local

Florianópolis, SC. Parque Tecnológico Alfa

## Benefícios

- Plano de saúde
- Seguro de vida
- VR
- VA
- VT
- Vale Combustível
(na verdade oferecemos R$877 em benefícios e você escolhe como usufruir)

#### Diferenciais

- Horário flexível
- Ambiente agradável
- Equipe em desenvolvimento - precisamos de você como um líder técnico
- Empresa muito saudável
- Produto (Exact Spotter) com alto engajamento
- Novas funcionalidades o tempo todo. Roadmap infinito!

## Requisitos

**Obrigatórios:**
* Javascript (es6/7+)
* [ReactJS](https://reactjs.org/) (component lifecycle, setState, setState callback, props, immutability)
* [Redux](https://redux.js.org/basics/usagewithreact)	
* [Async Programming](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Statements/funcoes_assincronas)
* [Flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)
* [GIT](https://git-scm.com/) (commit, push, branch)

**Desejáveis:**
* [Material-ui](https://material-ui.com/) (v0/v1)
* Testes Unitários ([`jest`](https://jestjs.io/))

**Diferenciais:**
* Conhecimentos em C#
* SQL Server

## Contratação

CLT

## Nossa empresa

A Exact é líder entre as plataformas de gestão de Pré-Vendas (SDR) nacional. Estamos em crescimento acelerado e vamos ao mercado internacional nos próximos meses, quando a equipe será novamente ampliada. Isso se traduz em muitas **oportunidades**. A empresa é financeiramente saudável (startup que já gera lucro), transparente e os gestores totalmente acessíveis.

## Como se candidatar

Envie e-mail para froman@exactsales.com.br com seu currículo + pretensão.

## Labels

- CLT
- Pleno
- Sênior
- Presencial

**Comment by fromanexact** [comment]
A vaga continua aberta! :)

**Comment by gabrielferreiraa** [comment]
Possibilidade de home office?
