### ISSUE TITLE
Front-End Developer

### ISSUE THREAD

**Issue by robertakoche** [frontendbr/vagas#1247]
![desenvolvedor](https://user-images.githubusercontent.com/38670812/43729025-4ff6d218-997d-11e8-8d4a-8f8745a2b9b9.png)

## Descrição da vaga

Buscamos desenvolvedor com experiência em projetos digitais e tecnologias como React Native ou React, Redux e Firebase. Queremos alguém que seja detalhista, versátil na utilização de tecnologias, autodidata e consciente da importância do trabalho em equipe. Nosso requisito é que você seja muito bom no seu trabalho e ame cada segundo dele.

## Local

Escritório, Porto Alegre - RS.

## Oferecemos

• Salário e benefícios compatíveis com a função
• Horário de trabalho flexível
• Trabalho remoto
• Ambiente descontraído.
• Cultura horizontal e colaborativa.
• Lareira para os dias frios.
• Playstation e snooker.
• Empresa pet friendly.
• Churrascos sem justificativas.

## Nossa empresa

A Trinca é uma empresa de tecnologia focada na experiência do usuário. Planejamos, criamos e desenvolvemos produtos digitais, conectando design, estratégia de negócio e desenvolvimento de software.

Conheça um pouco mais: 
http://trin.ca/
https://www.instagram.com/trinca137/

## Como se candidatar

Ficou interessado? Envie seu currículo e portfólio, GitHub ou versionador de código (se houver) para o e-mail jobs@trin.ca com o assunto “Desenvolvedor”.

## Labels
-react
-react native
-redux
-firebase

**Comment by lsgoulart** [comment]
Atualizado #1248
