### ISSUE TITLE
[São Paulo] Pessoa desenvolvedora Front-end Senior na Octadesk

### ISSUE THREAD

**Issue by houstondapaz** [frontendbr/vagas#1249]
## Descrição da vaga

O Octadesk é uma startup de atendimento que está crescendo muito nos últimos anos.
300% em 2017 e com a mesma meta para 2018!

E com isso precisamos de mais pessoas para dar conta de toda essa evolução.
Em dois anos mudamos nosso front de "monólito" em angularjs, para uma arquitetura mais voltada para micro-fronts em vue, angular eee por enquanto só, mas não nos apegamos a frameworks.

Estamos evoluindo o produto com foco nessa arquitetura e precisamos de pessoas que estejam afim de encarar esse desafio.

Se vc quer sempre ter uns desafios maneiros, ter a liberdade de buscar sempre a melhor maneira de implementar algo novo em um nível de entrega alta, cola com nois!

A gente paga bem e quando batemos a meta sempre tem um a mais, ano passado fomos para Disney (a empresa toda) e esse ano vamos para o Vale do Silício.

## Local

Escritório, São Paulo - Chácara Santo Antonio

## Benefícios

- Depende do seu modo de contratação (eu não manjo dessa parte)

#### Diferenciais

- Pagamos bem
- Bônus por meta

## Requisitos

- CSS
- HTML
- JAVASCRIPT

## Contratação

PJ ou CLT

## Como se candidatar

https://octadesk.revelo.com.br/openings/desenvolvedor-front-end-sr?locale=pt-BR

## Labels

- Alocado
- CLT
- PJ
- Sênior

**Comment by guibfo** [comment]
Possibilidade de remoto?

**Comment by houstondapaz** [comment]
@guibfo Algumas pessoas trabalham remoto, é uma possibilidade, mas não é regra

**Comment by Gabriel10Velloso** [comment]
Olá, acredito que não tenha competência ainda para preencher a vaga, mas me interessei pelo estilo da empresa e acredito que possa contribuir com a empresa através de um estágio não remunerado (remoto). 
Caso existe este tipo de espaço na empresa, gostaria de participar.
Att. Gabriel.

**Comment by houstondapaz** [comment]
@Gabriel10Velloso não se limite cara!
Estagio não remunerado não rola, ainda mais remoto.
Mas entra em contato, vai que rola um estagio remunerado

**Comment by Gabriel10Velloso** [comment]
Boa tarde @houstondapaz 
Eu mandei o meu curriculum para suporte .... e me cadastrei https://octadesk.revelo....
esse foi o ultimo trabalho que fiz em angular.

https://www.spiderlinq.com/download

Abraço.
