### ISSUE TITLE
[Sugestão] Divulgação automática das oportunidades

### ISSUE THREAD

**Issue by ftonato** [frontendbr/vagas#125]
Estava no Twitter, quando percebi esse [tweet](https://twitter.com/LFeh/status/775725694760448000) do @LFeh.
Tweet esse que me fez pensar em automatizar esse processo...

**Minha sugestão de como proceder:**
Usando o [IFTTT](https://ifttt.com/recipes/415582-any-new-issues-tweet-it) e o Twitter do [Front-End BR](https://twitter.com/frontendbr), poderíamos automatizar esse tipo de postagem.

Não sei se há como configurar no _IFTTT_ p/ quando for adicionado uma _label_ especifica ele disparar a _trigger_ como o título da _issue_ e o link da mesma, mas penso que seria uma opção legal, assim teríamos uma divulgação automática.

**Comment by LFeh** [comment]
@frontendbr/admins

**Comment by fdaciuk** [comment]
Acho bem válido, inclusive fazer para os eventos, se rolar =)

**Comment by diogomoretti** [comment]
IFTT é muito legal. Penso que dá para fazer sim!

**Comment by LFeh** [comment]
Como podemos tocar isso? Precisa de um Twitter para a org?

**Comment by ftonato** [comment]
O Twitter sugerido não é de vosso controle?

**Comment by LFeh** [comment]
Pior que não, mas ele parece estar abandonado. Podemos tentar que liberem pra gente :)

**Comment by ftonato** [comment]
Pode ser, ou então criar um novo...

**Comment by LFeh** [comment]
Consegue tocar isso @diogomoretti ?

**Comment by eduardojmatos** [comment]
Podemos criar um twitter @frontendbr_vagas mesmo e já fazer essa integração

**Comment by LFeh** [comment]
@eduardojmatos Show!

Consegue tocar isso?

**Comment by eduardojmatos** [comment]
Galera, feito! Agora qualquer issue que for criada aqui no repositório vai ser postada lá no Twitter do @frontendbrvagas. Não dá pra fazer por label, por isso, quando outra issue for criada sobre outro assunto também vai pra lá. 

Por hora resolve nosso problema, e podemos deletar o tweet não relacionado lá na conta sem problemas!

💃 💃 💃

**Comment by eduardojmatos** [comment]
Obrigado pela excelente sugestão @ftonato e @diogomoretti pelo toque do IFTTT!

@fdaciuk seria uma boa mesmo pro Eventos :) :) :)

**Comment by LFeh** [comment]
Sem problemas @eduardojmatos , até porque, eu vacilei de pedir pro @ftonato abrir essa issue aqui. Era pra ter aberto no Sugestões, hahahaha.

Não vai ter mais casos assim :p

**Comment by ftonato** [comment]
@eduardojmatos @LFeh valeu <3
Mas de toda forma, esperamos que outros tópicos não sejam abertos aqui, focando assim todos os tweets em vagas =)
