### ISSUE TITLE
[Portugal] JAVA Developer na Aubay 

### ISSUE THREAD

**Issue by monicantunes** [frontendbr/vagas#1250]
## Descrição da vaga

Projetos em vários setores de atividade, usando diversas tecnologias de Java.

## Local

Portugal: Lisboa e Porto

## Benefícios

• Plano de saúde
• Visto de Trabalho para Portugal
• Outras

#### Diferenciais

• Formações técnicas e comportamentais 
• Prémios de referências de recrutamento
• Eventos team Building
• Convívio mensal
• Oferta de aniversário

## Requisitos

**Obrigatórios:**
• Experiência em funções de desenvolvimento de projetos na área de Java;
• Sólidos conhecimentos de algumas das seguintes tecnologias: J2EE/J2SE, Hibernate, Struts, EJB’s, Spring, JPA, JSP;
• Fluência na língua Inglesa

**Desejáveis:**
• Experiência em Angular

**Diferenciais:**
• Experiência internacional

## Contratação

Apoio em todo o processo para obtenção de visto de trabalho para Portugal.

## Nossa empresa

A Aubay, é uma empresa de origem francesa presente em diversos países na Europa.
Como cerca de 6000 pessoas desenvolvemos projetos nas mais diversas tecnologias.
Neste momento, temos várias vagas em aberto para várias posições.

## Como se candidatar

Por favor envie um email para mantunessilvestre@aubay.com com seu CV anexado.

**Comment by mtmr0x** [comment]
@monicantunes a vaga postada é para um cargo de back end, o que vai contra o propósito e regras do repositório. Mais informações aqui: https://github.com/frontendbr/vagas/blob/master/README.md

Recomendo postar a mesma no https://github.com/backend-br/vagas
