### ISSUE TITLE
[São Paulo] Front-End Developer na Onebox

### ISSUE THREAD

**Issue by jumrsouza** [frontendbr/vagas#1254]
## Descrição da vaga

Gostaria de impactar e melhorar a vida milhões de estudantes utilizando tecnologia e dados?

A Onebox é uma startup de tecnologia focada em produtos para o público jovem e estudantil. Nós estamos com um super desafio para o Documento Nacional do Estudante e buscamos reforços para o nosso time de Tecnologia. Não estamos procurando apenas um bom Dev, mas alguém responsável pelo crescimento de uma cultura técnica de excelência!

Nossa Stack de Front-end atual inclui React, React Native, Redux, PWA e está sendo escrito em ES6.

Você se identifica com equipes ágeis e tem foco em resultado?
Dá uma olhada nos requisitos da vaga e vem trocar uma ideia!

## Local

Escritório no Itaim Bibi, São Paulo

## Benefícios

- Vale-transporte
- Vale-refeição
- Horário flexível
- Video game e mesa oficial de poker
- Escritório legal e em ótima localização
- Assistência médica Amil
- Vestiário e espaço para bicicleta
- Seguro de vida
- Dress code que respeita sua individualidade
- Frutas free

## Requisitos

**Obrigatórios:**
- Domínio em JavaScript, HMTL e CSS
- Conhecimentos em React, Boostrap, versionamento (Git/Bitbucket)
- Perfil analítico, orientado a resultado e desempenho

**Desejáveis:**

- Inglês intermediário a avançado
- Vivência com metodologias ágeis

**Diferenciais:**
- Será diferencial um Github mais verde que o encontro do Arqueiro e do Lanterna num jogo do Palmeiras

## Contratação

CLT

## Como se candidatar

Candidate-se através do nosso anúncio no Trampos: https://dne.vc/1cdxrq3

## Labels

- Alocado
- CLT
- Estágio
- Freela
- Júnior
- Pleno

**Comment by vinirossi** [comment]
vaga em aberto ainda? @jumrsouza

**Comment by MrS4w** [comment]
Acho que já pode fechar, o anúncio não existe.
