### ISSUE TITLE
[Campinas] Front-End Developer APPITO

### ISSUE THREAD

**Issue by talentreplacement** [frontendbr/vagas#1255]
## Descrição da vaga

- Desenvolver as funcionalidades de contato com o usuário;
 - Garantir a viabilidade técnica dos designs de UI/UX produzidos;
 - Otimizar a aplicação para melhor velocidade e escalabilidade; 
- Garantir a validação dos dados fornecidos pelos usuários antes de enviá-los ao Back-End;
 - Criar código e bibliotecas reutilizáveis para uso futuro;
 - Colaborar com outros membros da equipe e com o cliente; 

## Local
Campinas, SP

## Benefícios
VT+VR+ plano medico

## Requisitos

-Proficiência em HTML5 e CSS3;
- Proficiência em JavaScript e frameworks como jQuery; 
- Bons conhecimentos em manipulação de chamadas assíncronas, atualizações parciais de páginas e AJAX;
- Bons conhecimentos em AngularJS e Angular 4; 
- Conhecimentos básicos de ferramentas gráficas para cortes, redimensionamentos ou pequenos ajustes em imagens. Familiaridade com ferramentas como Photoshop / Fireworks é um diferencial; 
- Entendimento proficiente em compatibilidade cross-browser; 

## Contratação

Cooperado (atraves de uma cooperativa, com minimos descontos)

## Nossa empresa

Nós vamos revolucionar o esporte amador no mundo. Para isso, contamos com um elenco apaixonado por fazer parte dessa revolução e que é movido por cada partida e amizade gerada através do aplicativo.

## Como se candidatar

Enviar cv com pretensao salarial para recrutamento@talentreplacement.com.br

**Comment by mtmr0x** [comment]
@talentreplacement para essa vaga estão procurando que nivel? Junior, pleno, senior?

**Comment by talentreplacement** [comment]
@mtmr0x pleno!

**Comment by mtmr0x** [comment]
👍
