### ISSUE TITLE
[Curitiba] Front-End Sr | React na [MadeiraMadeira]

### ISSUE THREAD

**Issue by rafaelrac** [frontendbr/vagas#1256]
## Descrição da vaga

Adaptar-se rapidamente ao ambiente startup, trabalhar em um time de alta performance, disruptivo e qualificado, entregando o melhor em tecnologia e experiência do usuário.

## Local

Curitiba - PR - Centro

## Benefícios

- Vale Refeição;
- Vale Alimentação;
- Vale Transporte;
- Plano de Saúde;
- Plano Odontológico;

#### Diferenciais

- GymPass;
- Quitanda com frutas fresquinhas;
- Estacionamento para bikes;
- Desconto em restaurantes locais;
- Assistencia Psicológica, Jurídica e Financeira;
- Convênio com diversas universidades e parcerias com cursos;
- Local de descanso com videogame, pebolim e redes ;D E MUITO MAIS!

## Requisitos

**Obrigatórios:**

- Ter experiência em desenvolvimento de aplicações com Javascript/Typescript.
- Ter conhecimento das stacks de desenvolvimento de front end moderna (WebPack, Babel, Yarn, NPM e etc);
- Ter bom conhecimento de ES6, JSX e Node.
- Compreensão dos princípios do REST e exposição a APIs de back-end.
- Ter conhecimento dos problemas de compatibilidade entre navegadores e formas de contorná-los.
- Ter compromisso em produzir código bem estruturado, testado e escalável.

**Desejáveis:**
- Estar antenado às recentes evoluções da linguagem Javascript (ECMA6+).
- Ter experiência no desenvolvimento, lançamento e manutenção de aplicativos React.js ou React Native.
- Flux, Redux ou MobX.
- GIT

## Contratação

CLT

## Nossa empresa

[https://www.madeiramadeira.com.br/sobre](https://www.madeiramadeira.com.br/sobre)

## Como se candidatar

[Candidate-se aqui](https://signup.kenoby.com/#/candidatos/me?position=5b610fa95e2545286db7ac58&tenant=5aabe058c740f7051814e3ee&jobsite=madeiramadeira&positionName=Desenvolvedor%20React%20%7C%20Front%20End%20Sr&applicantSource=linkedin&utm_source=linkedin)

## Labels

- React
- Sênior
- Curitiba
- Startup

**Comment by mtmr0x** [comment]
@rafaelrac o "A combinar" na contratação está passivo de ser CLT ou PJ ou é apenas um deles?

**Comment by matheus-rosin** [comment]
@rafaelrac tem algum email para eu dar uma conversada contigo sobre a vaga?

Se for ruim disponibilizar publicamente aqui, posso passar o meu e daí você me manda primeiro :)

**Comment by rafaelrac** [comment]
@mtmr0x CLT apenas, corrigi a informação

**Comment by rafaelrac** [comment]
@matheus-rosin rafael.correa@madeiramadeira.com.br e sergio@madeiramadeira.com.br

**Comment by RicardoWEBSiTE** [comment]
Excelente vaga, e-mail enviado 👍

**Comment by rafaelrac** [comment]
@RicardoWEBSiTE Obrigado pelo interesse Ricardo, nosso CTO irá avaliar seu perfil.
