### ISSUE TITLE
[SANTO ANDRÉ - SP] Front-End Developer na [ROBERT HALF]

### ISSUE THREAD

**Issue by RaquelTavaresL** [frontendbr/vagas#1257]
## Descrição da vaga

Projeto de 3 meses para atuar no Desenvolvimento de novas aplicações Web em sistemas já existentes na empresa utilizando HTML, Javascript e CSS.

## Local

Atuará no escritório de Santo André (presencial)

## Benefícios

- Plano de saúde Care Plus (Individual)
- Seguro de vida
- VR de R$ 440,00/mês
- Vale Transporte ou Reembolso de Despesas.

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Desenvolvimento Web
- Atuação com HTML, Javascript e CSS.

## Contratação

Contrato CLT.

## Como se candidatar

Por favor envie um email para raquel.lourenco@roberthalf.com.br com seu CV anexado.

**Comment by vinirossi** [comment]
Aceitaria estágio?

**Comment by X-X-Xavito** [comment]
Vaga ainda está em aberto?
