### ISSUE TITLE
[São Paulo] Front-End Developer Angular na [CONFITEC]

### ISSUE THREAD

**Issue by JulianaSoave2018** [frontendbr/vagas#1259]
## Descrição da vaga

Fará parte da equipe de desenvolvimento de produtos/sistemas web e mobile voltados ao mercado de Seguros.

## Local

No escritório de São Paulo - Zona Sul- próximo ao Morumbi Shopping. 

## Benefícios

- Assistência Médica
- Assistência odontológica
- VT
- VR de R$ 24,30/dia
- Auxílio creche
- PLR

#### Diferenciais

- Comitê de treinamentos
- Campeonatos (futebol, games, pocker)
- Café da manhã toda sexta-feira
- Ginástica laboral às quartas-feiras 

## Requisitos

**Obrigatórios:**
- Ensino superior completo;
- Vivência com Javascript, CSS, HTML5, Bootstrap, Angular (JS ou 2+). 

**Diferenciais:**
- Diferencial: conhecimento em ​design, UX e mobile. ​ 

## Contratação

- CLT Full

## Nossa empresa

- A Confitec é uma empresa de TI especialista em atender o mercado de Seguros. 

## Como se candidatar

Por favor envie um email para curriculos@confitec.com.br com seu CV anexado - enviar no assunto: Vaga "Front End Angular".
Envie também sua pretensão salarial (CLT).

**Comment by mtmr0x** [comment]
@JulianaSoave2018 qual seria o nivel desejado do profissional que procuram nessa vaga aqui tambem? (junior, pleno e/ou senior)

**Comment by mtmr0x** [comment]
Issue fechada por demora na resposta para adicionar informações, de acordo com responsabilidades do autor da postagem que pode ser encontrada aqui: https://github.com/frontendbr/vagas/blob/master/README.md
