### ISSUE TITLE
[São Paulo] Front-end Developer / React

### ISSUE THREAD

**Issue by raymonsanches** [frontendbr/vagas#126]
## Descrição da vaga

Projetos utilizando tecnologias como PHP e Java no backend com uma arquitetura de micro-serviços. Muitos projetos e muita inovação ainda pra rolar.

## Local

Escritório, Rua Castro Verde, 98 - Santo Amaro, São Paulo

## Benefícios

- Horário flexível
- Possibilidade de home office

## Requisitos

**Obrigatórios:**
- HTML5 
- CSS3 ( RESPONSIVE LESS SASS ) 
- TWITTER BOOTSTRAP 
- JAVASCRIPT 
- JAVASCRIPT LIBS ( JQUERY, underscore/lodash ) 
- CONTROLE DE VERSAO ( GIT ) 
- API ( JSON ) 
- TERMINAL COMMAND LINE ( LINUX ) 
- GRUNT 
- Experiência com algum framework JS MV* 

**Desejáveis:**
- PERFORMANCE TUNING 

**Diferenciais:**
- React.js 
- Webpack 
- Flux (ou alguma implementação alternativa) 
- Desenvolvimento de proxies e stubs de backend com Node.js 
- Conhecimento dos principais novos recursos de ES6 

## Contratação

CLT 

## Como se candidatar

Por favor envie um e-mail para recrutamento@arizona.global com seu Linkedin e Github com o título Vaga Frontend

**Comment by brunoravanhani** [comment]
Opa!! trampar com @raymonsanches

**Comment by raymonsanches** [comment]
opa, é noix! hahaha

**Comment by raymonsanches** [comment]
Fechamos! =)

**Comment by camilatigre** [comment]
@raymonsanches você acha que vale a pena reabrir ou abrir outra issue? tem vaga pra jr também ainda. E tem os outros times.

**Comment by raymonsanches** [comment]
Acho que vale a pena abrir outra @camilatigre. Vai ficar maio estranha, essa com data de outubro, hahaha

**Comment by camilatigre** [comment]
Verdade!

Em 9 de jan de 2017 11:56, "Ramon Sanches" <notifications@github.com>
escreveu:
