### ISSUE TITLE
[São Paulo] React Developer [CONFITEC]

### ISSUE THREAD

**Issue by JulianaSoave2018** [frontendbr/vagas#1260]
## Descrição da vaga

Integrará uma equipe de desenvolvedores em projeto de migração de sistema de uma grande seguradora, participando de um projeto tecnologicamente inovador neste cenário!

## Local

No Escritório de São Paulo - ao lado do Morumbi Shopping. 

## Benefícios

- Assistência Médica
- Assistência Odonto
- VR de R$ 24,30/dia
- VT
- PLR
- Auxílio creche

#### Diferenciais

- Café da manhã toda sexta-feira
- Ginástica laboral às quartas
- Campeonatos (Pocker, Futebol, Games, etc)

## Requisitos

**Obrigatórios:**
- Sólidos conhecimentos em Javascript (utilizando a biblioteca React JS ou React Native).
- Vivência com bibliotecas para criação de componentes reusáveis, preferencialmente React.
- Criação e consumo de API’s.
- Atuação com ferramentas de versionamento de código, preferencialmente Git. 

**Desejáveis:**
- Desejável experiência em projetos com BackEnd em C#, Node JS. Conhecimento em Angular.

## Contratação

CLT Full

## Nossa empresa

A Confitec é uma empresa de TI especializada no mercado de Seguros. 

## Como se candidatar

Por favor envie um email para curriculos@confitec.com.br com seu CV anexado - enviar no assunto: Vaga React
- Por favor, envie também sua pretensão salarial CLT.

**Comment by Buul** [comment]
Bom dia!

Tem opção de trabalho remoto?

**Comment by JulianaSoave2018** [comment]
Não há possibilidade de trabalho remoto.

**Comment by mtmr0x** [comment]
@JulianaSoave2018 poderia nos informar para qual nível profissional a vaga é? (junior, pleno e/ou senior)

**Comment by JulianaSoave2018** [comment]
Pleno.
