### ISSUE TITLE
[São Paulo] Front-End Developer na [Foco em você]

### ISSUE THREAD

**Issue by kvilela** [frontendbr/vagas#1261]
## Local

Alocado, São Paulo - Faria Lima

## Benefícios

Possibilidade de Home Office de 2 a 3 vezes na semana

## Requisitos
                - Experiência na criação de páginas responsivas, web e mobile
                - Experiência em desenvolvimento de aplicações web utilizando Javascript avançado (OO, herança, prototipação, design pattern, jQuery, ES6).
                - Experiência em CSS Avançado (SASS e LESS) e CSS3
                - Experiência em suporte a browsers antigos (graceful degradation)
                - Conhecimentos de Regex
                - Domínio de protocolo (HTTP, HTTPS, cross domain)
                - Conhecimentos de arquitetura backend (servidor web, estático, BFF)
                - Conhecimento de React, Vue

**Diferenciais:**
                  Conhecimentos relacionados a performance (gzip, minify, quantidade de requests)
                - Testes automatizados 
                - Conhecimento em Apache Velocity
                - Conhecimento de virtualização  (Docker, Mesos)

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um e-mail para contato@focoemvoce,com.br com seu CV anexado - enviar no assunto: Vaga Engenheiro FRONT-END

## Labels

- Alocado
- PJ
- Pleno
- Remoto - Parcial

**Comment by mtmr0x** [comment]
@kvilela a fim de colocarmos as labels adequadamente aqui, o que facilitaria de desenvolvedores analisarem se são um bom fit, precisamos que nos informe também qual o nível do profissional desejado (junior, pleno e/ou senior)

**Comment by kvilela** [comment]
@mtmr0x nível Pleno
