### ISSUE TITLE
[São Paulo] Front-End Developer na Webedia

### ISSUE THREAD

**Issue by nandosangenetto** [frontendbr/vagas#1265]
![alt text](http://jobs.webedia.group/webedia-companies.png "Webedia")

## 🎉🎉 Sobre a vaga 🎉🎉
Você vai trabalhar na equipe que desenvolve projetos internos como Minha Vida, Hypeness, Versus IGN, Reverb, entre outros projetos. Nosso time gosta de muito aprendizado e oportunidades para usar novas tecnologias para gerar melhores resultados.

Quer saber um pouco mais da nossa empresa ao redor do mundo? Se liga nesse [vídeo](https://youtu.be/hsVSaUlVYXU).

## Local
🔥 Vila Olímpia, SP

## Benefícios

- 🥗🍲 VR de R$ 25/dia
- 🚌🚊 Vale Transporte
- 🏥🚑 Plano de saúde e odontológico
- 📈📊 Oportunidade de crescimento. Você será acompanhado através de programas de desenvolvimento de carreira.
- 🎉🎊 Festinhas da empresa com frequência: Promovemos integrações com outras equipes na empresa com festinhas e outras atividades. Olha o último festão com nossa sede de SP e RJ juntas neste [vídeo](https://vimeo.com/257192408).

## Requisitos

**Obrigatórios:**
- 🎓 Gostar de aprender coisas novas: estamos sempre em busca de melhorias em nossos produtos;
- 👤 Ser analítico e detalhista: ​Prezamos pela melhor experiência possível para nossos usuários (usuário sempre acima);
- 💻 Já ter tocado algum projeto web: ​se sente seguro com HTML, CSS e JavaScript?
- 📱 Conhecimento em design responsivo (mobile-first) 
- ✅ Conhecimento em sistemas de versionamento, preferencialmente Git;
- 🇺🇸🇬🇧 Inglês intermediário (leitura e escrita);

**Desejável:**
- Experiência com ⚛️ React
- Experiência com GraphQL

**Diferenciais:**
- Experiência com ​Node

## Contratação
CLT com horário parcialmente flexível (com banco de horas)

## Nossa empresa
A Webedia é um grupo de mídia digital de origem francesa presente em mais de dez países, com verticais que totalizam 177 milhões de usuários únicos por mês, dos quais 47,3 milhões estão no Brasil, a maior audiência do grupo. O sucesso se deve ao controle de sites líderes em segmentos estratégicos: TudoGostoso (comida), AdoroCinema (entretenimento), IGN (jogos), Versus (e-sports), PurePeople e Purebreak (glamour/celebridades), Minha Vida (saúde e bem-estar), Hypeness (inovação e criatividade), entre outros. Por meio da divisão de Brand Publishing, a Webedia oferece ainda expertise em audiência para clientes como Niely, Johnson & Johnson, Oral-B, Gillette, L'Oréal, Maybelline, La Roche Posay, Leroy Merlin, entre outros.

## Como se candidatar
- Mande seu CV por e-mail com o assunto "[Vaga Front] São Paulo" em cópia para: 
✉️ nando.sangenetto@webedia-group.com
- Se quiser, sinta-se livre pra mandar algo que você se orgulhe de ter feito, sua história de vida, GitHub, LinkedIn, portfólio ou qualquer outra coisa que ache interessante compartilhar com a gente 🙃

## Labels
- Alocado
- CLT
- Estágio
- Júnior
- Pleno

**Comment by adeonir** [comment]
Opa, como funciona esse horário parcialmente flexível com banco de horas? Aceitam remoto?

**Comment by nandosangenetto** [comment]
@adeonir trabalhamos com banco de horas :)

**Comment by GuiRamos7** [comment]
Mandei pra ontem :)

**Comment by VitorLuizC** [comment]
Qual o salário?

**Comment by nandosangenetto** [comment]
@VitorLuizC envie-nos sua pretensão por e-mail. O salário é variável com o nível do candidato, além de termos vagas desde estágio até pleno.

**Comment by nandosangenetto** [comment]
Pessoal, estamos entrando em contato com todos nessa semana. Prezamos pela transparência, por isso postamos aqui como um feedback para todos que nos enviaram o currículo para que saibam que não ignoramos ninguém.

Recebemos uma chuva de e-mails de vocês, pois divulgamos exclusivamente aqui nos repositórios do GitHub. Recebemos quase mais de 80 aplicações 😍

**Comment by LFeh** [comment]
@nandosangenetto caraleo! que foda saber disso 😄

**Comment by nandosangenetto** [comment]
@LFeh depois vou fazer uma postagem no forum falando um pouco dos nossos processos.

Da última vez que fizemos um processo, no Rio de Janeiro, mais de 50% veio do GitHub e na última fase a grande maioria eram profissionais vindo daqui. Foi um sucesso. Queria ter te falado isso no frontinsampa, mas acabou que esqueci.

**Comment by LFeh** [comment]
Demais mano!

Adoraria ler esse seu post. 

De fato não temos ideia do tamanho disso que estamos criando aqui 💜

**Comment by gabrielferreiraa** [comment]
@nandosangenetto tem possibilidade de remoto? Abç.

**Comment by nandosangenetto** [comment]
@LFeh vou preparar assim que tiver um tempo.

@gabrielferreiraa neste momento não, mas temos previsões de algumas vagas no futuro.

**Comment by stearruda** [comment]
@nandosangenetto Que pena não ter remoto. Vou aguardar ansiosamente por esse futuro ai. :smiley:

**Comment by nandosangenetto** [comment]
@stearruda no momento estamos consolidando nossa equipe de tecnologia em São Paulo. Em breve isso será possível. Fique no aguardo :)
