### ISSUE TITLE
[Portugal] Front-End Developer - Javascript/Angular na Aubay

### ISSUE THREAD

**Issue by silviapedrosa** [frontendbr/vagas#1267]
### **Descrição da vaga**
Projetos em vários setores de atividade, usando diversas tecnologias de Front End tal como Angular e React, entre outras.

### **Local**
Portugal: Lisboa e Porto

### **Benefícios**
• Plano de saúde
• Visto de Trabalho para Portugal
• Outras

### **Diferenciais**
• Formações técnicas e comportamentais
• Prémios de referências de recrutamento
• Eventos team Building
• Convívio mensal
• Oferta de aniversário

### **Requisitos**
**Obrigatórios:**
• Experiência profissional na área web
• Bons conhecimentos de Javascript, HTML, CSS
• Experiência na framework Angular
• Fluência na língua Inglesa

**Desejáveis:**
• Experiência em Node.js/React

**Diferenciais:**
• Experiência internacional

### **Contratação**
Apoio em todo o processo para obtenção de visto de trabalho para Portugal.

### **Nossa empresa**
A Aubay, é uma empresa de origem francesa presente em diversos países na Europa.
Como cerca de 6000 pessoas desenvolvemos projetos nas mais diversas tecnologias.
Neste momento, temos várias vagas em aberto para várias posições.

### **Como se candidatar**
Por favor envie um email para spedrosa@aubay.com com seu CV anexado.

**Comment by malacela** [comment]
CV enviado.

**Comment by silviapedrosa** [comment]
Bom dia André,

Pode anexar o seu CV por favor?

Obrigada.

[Descrição: 721313813@16102008-18F2]  Sílvia Pedrosa
  International Talent Recruiter

Edifício Duque d’Ávila,
Avenida Duque d’Ávila nº 46, 7ºC – 1050-083 Lisboa
Tel: +351 2<tel:%2B351%20211%20928%20417>11 928 417 - Mobile: +351 914 053 987
Fax: +351 211 928 230<tel:%2B351%20211%20928%20230>
Skype: smarinapedrosa_1

[cid:image002.png@01D1126F.FAEB9CF0]<http://www.aubay.com/>  [cid:image003.png@01D1126F.FAEB9CF0] <http://www.facebook.com/aubayportugal>   [cid:image004.png@01D1126F.FAEB9CF0] <https://twitter.com/groupeaubay>   [cid:image005.png@01D1126F.FAEB9CF0] <https://www.youtube.com/user/aubaytv>

Antes de imprimir, pense no ambiente!
“Iremos utilizar informação pessoal que nos enviou, para considerar a sua candidatura à função relevante. Ao facultar-nos a sua informação por email e/ou em documentos, consente que a Aubay Portugal trate a sua informação pessoal. A sua privacidade é importante para nós. Por favor, consulte a nossa Política de Privacidade, que explica de que forma utilizaremos e armazenaremos a sua informação pessoal. Explica também os direitos que tem relativamente à sua informação e como pode contactar-nos para o esclarecimento de dúvidas ou pedidos.”

De: Andre Antunes <notifications@github.com>
Enviada: 12 de agosto de 2018 22:34
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: Silvia PEDROSA <spedrosa@aubay.com>; Author <author@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [Portugal] Front-End Developer - Javascript/Angular na Aubay (#1267)


CV enviado.

**Comment by jorgelimafeitosa** [comment]
Olá Sílvia,

Acho que por engano você redirecionou este e-mail para mim, sou o Jorge
Luís de Lima Feitosa, estou me candidatando ao cargo de desenvolvedor Java
com Node.

Abraços,
Jorge.

Em 13 de agosto de 2018 06:06, silviapedrosa <notifications@github.com>
escreveu:

**Comment by silviapedrosa** [comment]
Olá Jorge!

Peço desculpa pelo lapso.

Obrigada.

[Descrição: 721313813@16102008-18F2]  Sílvia Pedrosa
  International Talent Recruiter

Edifício Duque d’Ávila,
Avenida Duque d’Ávila nº 46, 7ºC – 1050-083 Lisboa
Tel: +351 2<tel:%2B351%20211%20928%20417>11 928 417 - Mobile: +351 914 053 987
Fax: +351 211 928 230<tel:%2B351%20211%20928%20230>
Skype: smarinapedrosa_1

[cid:image002.png@01D1126F.FAEB9CF0]<http://www.aubay.com/>  [cid:image003.png@01D1126F.FAEB9CF0] <http://www.facebook.com/aubayportugal>   [cid:image004.png@01D1126F.FAEB9CF0] <https://twitter.com/groupeaubay>   [cid:image005.png@01D1126F.FAEB9CF0] <https://www.youtube.com/user/aubaytv>

Antes de imprimir, pense no ambiente!
“Iremos utilizar informação pessoal que nos enviou, para considerar a sua candidatura à função relevante. Ao facultar-nos a sua informação por email e/ou em documentos, consente que a Aubay Portugal trate a sua informação pessoal. A sua privacidade é importante para nós. Por favor, consulte a nossa Política de Privacidade, que explica de que forma utilizaremos e armazenaremos a sua informação pessoal. Explica também os direitos que tem relativamente à sua informação e como pode contactar-nos para o esclarecimento de dúvidas ou pedidos.”

De: jorgelimafeitosa <notifications@github.com>
Enviada: 13 de agosto de 2018 10:44
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: Silvia PEDROSA <spedrosa@aubay.com>; Author <author@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [Portugal] Front-End Developer - Javascript/Angular na Aubay (#1267)

Olá Sílvia,

Acho que por engano você redirecionou este e-mail para mim, sou o Jorge
Luís de Lima Feitosa, estou me candidatando ao cargo de desenvolvedor Java
com Node.

Abraços,
Jorge.

Em 13 de agosto de 2018 06:06, silviapedrosa <notifications@github.com>
escreveu:
