### ISSUE TITLE
[São Paulo] Front-End Developer na Guni

### ISSUE THREAD

**Issue by megandavulpi** [frontendbr/vagas#1271]
## Descrição da vaga

Temos uma vaga aberta para desenvolvedor FrontEnd no Guni, uma startup criada em 2015 por universitários. Existimos para tornar a vida universitária mais fácil e completa, trazendo informações de forma mais organizada e acessível. 

## Local

Escritório, São Paulo.

## Benefícios

- Salário compatível com o mercado;
- VR
- Ambiente de startup; 
- Clima descontraído.

## Desafios

- Programar, codificar e testar os projetos criados;
- Liderar a equipe de desenvolvimento composta por ele e mais 2 pessoas ( um júnior e um estagiário). 

## Requisitos

- Experiência Angular e Ionic;
- Pró-atividade;
- Liderança;
- Trabalho em equipe;
- Responsabilidade;
- Profissionalismo.

## Contratação

CLT - Faixa salarial: R$3500.00 - R$5500.00

## Nossa empresa

Lançado em 2016, a rede social Guni permite que os usuários compartilhem informações e eventos relacionados à sua faculdade de maneira colaborativa. Nosso objetivo é abranger todas as esferas da vida universitária, sociais e acadêmicas. Além disso, oferecemos diversas soluções para organizadores de eventos e empresas que queiram se comunicar com esse público, sempre gerando valor ao universitário. Se você não conhece, dá uma olhada nas app stores!

## Como se candidatar

Basta se cadastrar no link a seguir: http://bit.ly/2KTHqVF

## Labels

- Alocado
- CLT
- Júnior
- Pleno

**Comment by juliano-nunes** [comment]
Me candidatei :)

**Comment by megandavulpi** [comment]
Que bacana Juliano! 
Te desejo toda sorte do mundo =)

**Comment by AlexandreRStos** [comment]
@megandavulpi voces tem vaga para iniciante como eu!kk https://alexandrerstos.github.io

**Comment by megandavulpi** [comment]
Oi @AlexandreRStos!
Temos várias vagas de senioridade Júnior em nosso portal: https://app.vulpi.com.br/jobs
Espero que você encontre alguma com o seu perfil! =)
Se tiver qualquer dúvida, estou à disposição pra ajudar! tmj 👊
