### ISSUE TITLE
[Florianópolis] JavaScript Developer de todos níveis na TutorMundi

### ISSUE THREAD

**Issue by namenotrequired** [frontendbr/vagas#1273]
## Descrição da vaga

Estamos buscando desenvolvedores full stack JavaScript com foco em Front End para uma startup que acabou de receber investimento. Temos 4 pessoas trabalhando em Florianópolis, mas queremos abrir um escritório em São Paulo. Então talvez no futuro haja possibilidade para ambos lugares. A startup no entanto, foi fundada em Silicon Valley e o desenvolvedor terá ações dessa empresa matriz. 

Esses desenvolvedores não precisam ter experiência, mas precisam ser motivados por trabalhar numa startup. Aprendizado rápido é tudo.

Nós acreditamos que é a hora certa para entrar na empresa, pois ainda somos muito pequenos e já temos usuários pagantes que amam nosso produto.

## Local

Florianópolis, SC

## Benefícios

Ações da empresa em Silicon Valley

#### Diferenciais

- Horário flexível
- Equipe pequena e empolgada
- Empresa que realmente investe nas pessoas

## Requisitos

**Obrigatórios:**
- JavaScript
- HTML
- CSS

**Desejáveis:**
- React ou Vue
- Node.js
- Meteor / Cordova
- MongoDB

## Contratação

CLT

## Nossa empresa

O sistema funciona como WhatsApp para educação. Alunos do ensino médio com uma dúvida simplesmente tiram uma foto da questão. Em menos de 5 minutos um universitário das melhores universidades aparece e começa a ensinar via chat e imagens como se fosse um WhatsApp. 

Temos centenas usuários pagantes, dos quais muitos acessam o aplicativo semanalmente. No último mês esclarecemos quase 3 mil dúvidas de alunos. Já temos parcerias com 10 escolas.

A empresa realmente investe nas pessoas, por exemplo, eu sou holandês e a empresa arrumou um visto de trabalho para mim. Também apoiou nosso designer a passar 6 meses estudando em Stanford.

Para aqueles que gostam de ver os perfis dos futuros colegas de trabalho, hoje somos 4:

https://www.linkedin.com/in/raphaelrrc/
https://www.linkedin.com/in/thaisrscapini/
https://www.linkedin.com/in/bart-sturm-26694990/
https://www.linkedin.com/in/thomaspmach/

## Como se candidatar

Por favor envie um email para contact@tutormundi.com com CV e/ou motivação em anexo e o local no assunto.

## Labels

- Presencial
- CLT
- Estágio
- Júnior
- Pleno
- Sênior

**Comment by Finacio** [comment]
@namenotrequired em qual lugar de SP?

**Comment by fernandosimoes** [comment]
Aceita remoto?

**Comment by namenotrequired** [comment]
@Finacio: desculpe, na capital (ainda não decidimos o bairro). Atualizei a vaga para ser mais claro. Obrigado!

@fernandosimoes: Não, presencial só.

**Comment by spam-man** [comment]
currículo enviado
