### ISSUE TITLE
[Belo Horizonte] Front-End Developer na Pavarotti

### ISSUE THREAD

**Issue by megandavulpi** [frontendbr/vagas#1275]
## Descrição da vaga

**Porque o desenvolvedor Front-End é importante para nós?** Como membro da equipe da Pavarotti, você será responsável pela elaboração e construção de novas startups desde a etapa da sua concepção, projeto, construção e entrega - lidando com diversas áreas de conhecimento como: DevOps, Bancos de Dados, APIs, Front-End e Mobile. Nós valorizamos os profissionais que estão abertos a aprender novas tecnologias, independente da zonas de conforto pré-existentes.

## Local

Escritório, Belo Horizonte.

## Benefícios

- Salário compatível com o mercado;
- Lanche na empresa;
- No dress code (pode trabalhar de bermuda, chinelo, etc);
- Clima descontraído;
- Horário flexível :)

#### Desafios

- Contribuir com a tomada de decisões de todos os processos de desenvolvimento, desde a escolha das tecnologias até o processo de build/deploy;
- Auxiliar a manter um "espírito" ágil e de melhoria contínua; 
- Construir serviços e plataformas escaláveis em diversos nichos de mercado;
- Desenvolvimento baseado em testes;
- Assegurar a melhor qualidade de experiência para nossos clientes;

## O que buscamos?

Buscamos profissionais que buscam ser protagonistas e que queiram modelar novas arquiteturas, processos e cultura enquanto trabalha com tecnologias de ponta. Acreditamos na boa química da equipe, no entusiasmo em construir e na capacidade de aprender coisas novas quando nos mantemos humildes e de mente aberta. 

## Contratação

PJ - Faixa salarial: R$6000.00 - R$7000.00

## Experiências relevantes de front-end:

- 3 anos de experiência em desenvolvimento front-end em uma das linguagens (Angular Js, React ou Ember);
- Conhecimento em princípios fundamentais de arquitetura para aplicações escaláveis;
- Conhecimento em design de APIs RESTful e arquitetura de serviços modularizados;
- Conhecimento em message brokers (RabbitMQ, Resque ou Sidekiq);
- Conhecimento em bancos de dados SQL / NoSQL (como MySQL, Redis ou PostgreSQL);
- Conhecimento e vontade em implementar testes automatizados (unidade, funcionais e de integração);
- Conhecimento em Amazon Web Services, Azure ou Google Cloud;
- Conhecimentos em frameworks modernos (como Django, Rails, Sinatra, Ring ou Express)
- Capacidade de priorizar o seu próprio trabalho a partir das linhas gerais definidas pela equipe e a partir de feedbacks recebidos dos usuários finais;
- Ser flexível, independente e responsável;
- Ser curioso, com muita vontade de experimentar e aprender coisas novas;
- Conhecer os conceitos de startup.

## Nossa empresa

Que tal fazer parte de uma empresa em que você tenha ao mesmo tempo oportunidade de crescimento e voz ativa para estimular o seu desenvolvimento profissional? E se essa empresa te habilitar a criar não só códigos, sites e aplicativos, mas novos negócios e novas formas de interagir com o mundo? Se curtiu essa ideia, venha fazer parte do nosso time! :)

## Como se candidatar

Basta se cadastrar no link a seguir: http://bit.ly/2MLJGA7

## Labels

- Alocado
- PJ
- Pleno

**Comment by L-Lutece** [comment]
:(
