### ISSUE TITLE
[Contagem] Front-End Developer na Infornet

### ISSUE THREAD

**Issue by megandavulpi** [frontendbr/vagas#1276]
## Descrição da Vaga

Programar, codificar e testar os projetos criados. Planejar interface das telas e trabalhar com banco de dados. Eventualmente atender clientes.

## Local

Escritório em Contagem - MG.

## Benefícios

- Vale Transporte ou Auxilio Combustível;
- Vale Refeição;
- Lanche na empresa;
- Plano de Saúde (coparticipativo - Unimed);
- Programa de Remuneração Variável (Participação nos Resultados de acordo com o desempenho).

## Aptidões e qualidades:

- Proatividade;
- Trabalho em equipe;
- Atualização tecnológica;
- Organização.

## Contratação

CLT - Faixa salarial: R$1500.00 - R$2000.00

## Nossa empresa

Fundada em 2008, a Infornet desenvolve softwares e aplicações específicas para as necessidades do seu negócio. Nosso diferencial é desenhar soluções customizadas, de acordo com os requisitos do sistema e com a realidade de sua empresa. Como resultado, oferecemos uma experiência única em desenvolvimento de software web. Nossos profissionais acompanham todas as etapas do processo, desde o levantamento de requisitos à implantação final, passando por testes, acompanhamento e treinamento. Contamos com casos de sucesso e experiência acumulada em projetos para diversas empresas.

## Como se candidatar

Basta se cadastrar no link a seguir: http://bit.ly/2KSXbft

## Informações complementares

- Residir em Contagem ou proximidades.

## Desejável: 

Conhecimento em metodologias ágeis (scrum), Git, Back End PHP.

## Labels

- Alocado
- CLT
- Júnior

**Comment by GabrielOliveira321** [comment]
[Gabriel_Raitz-1.pdf](https://github.com/user-attachments/files/17821601/Gabriel_Raitz-1.pdf)

**Comment by idalinosou** [comment]
olá! o link não esta funcionando
