### ISSUE TITLE
[Remoto] Front-End Developer (Sênior/Pleno) na oneRhino (Estados Unidos)

### ISSUE THREAD

**Issue by juliovedovatto** [frontendbr/vagas#1277]
## Descrição da vaga

A empresa que trabalho está procurando desenvolvedor frontend , de perfil sênior ou pleno para trabalho remoto. Serviço demandará conhecimentos sólidos em HTML/CSS/Javascript/Responsivo/Mobile.

Horário é flexível, tendo demanda para ser um trabalho fixo.

Inglês nível intermediário é necessário.

## Local

Remoto

#### Diferenciais

- Horários flexíveis de trabalho (desde que consiga manter a constante de horário).
- Pagamentos Quinzenais, em dólar.

## Requisitos

**Obrigatórios:**
- Conhecimentos sólidos em HTML/CSS/Javascript, responsivo e mobile web (PWA, Offline, etc)
- Inglês nível intermediário.

**Desejáveis:**

- conhecimentos em PHP/Node/Ruby

## Contratação

~~Vínculo informal, mas é confiável 100%.~~
EDIT: Trabalho a ser faturado por PJ ou pelos sites Freelancer, UpWork ou Workana.

## Nossa empresa

oneRhino é uma empresa situada em Crozed, VA. Atende demandas de desenvolvimento web em geral (planejamento e desenvolvimento), trabalhando terceirizado para clientes.

## Como se candidatar

Envie CV em inglês, um texto de introdução (contado como trabalha, formação, etc) e alguns exemplos de sites (se disponível). Linked In/Github são opcionais.

j.vedovatto@onerhino.com, com o assunto *Front-End Developer*

## Labels

- Freela
- Pleno
- Remoto - Parcial
- Remoto - Total
- Sênior

**Comment by allancarlos123** [comment]
Tenho um ótimo nível para ler/escrever e-mails em Inglês, serve?

**Comment by luiguild** [comment]
Vínculo informal, mas é confiável 100% 🤔

**Comment by nandosangenetto** [comment]
Vínculo informal, mas é confiável 100% 🤔

**Comment by juliovedovatto** [comment]
Obrigado pelo feedback pessoal, editei a vaga para melhorar o entendimento.

**Comment by nandosangenetto** [comment]
Valeu @juliovedovatto ficou bem mais claro assim 👍

**Comment by costaleonardo** [comment]
Sent my resume yesterday, best of luck with your recruiting.
