### ISSUE TITLE
[São Paulo] Front-End Developer na [RoadPass Payments]

### ISSUE THREAD

**Issue by fpcandido** [frontendbr/vagas#1278]
## Descrição da vaga

Projeto Conta Digital com APP Mobile, Angular, JavaScript, Vue, React, HTML5, CSS, etc.

## Local

Escritório, São Paulo - Tatuapé

## Benefícios

- Plano de saúde
- Vale Transporte
- Seguro de vida
- VR de R$ 17,50/dia
- Auxílio creche
- Participação nos Lucros (PLR)

#### Diferenciais

- Ambiente descolado
- Copa para refeição no Local
- Frigobar sempre cheio :P
- Sala de descompressão (jogos)
- Cabines para telefonemas particulares
- Ambiente Industrial

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Angular 
- 2 anos de experiência com JavaScritp
- Experiência com React, Vue, mongodb (diferencial), CSS, Html5, etc

**Desejáveis:**
- conhecimentos em ruby on rails
- conhecimentos em C#

**Diferenciais:**
- projetos opensource
- Amazon 
- Azure
- BigData

## Contratação

CLT a combinar

## Nossa empresa

Somos uma Startup de Conta Digital e Plataforma de Pagamentos, buscamos profissionais Jovens em espirito, para empreender conosco e para participar do desenvolvimento de tecnologias disruptivas para o mercado de pagamentos. Somos uma empresa com tecnologias também para IoT, M2M, Machine Learning e AI e oferecemos um ambiente muito bom com integração constante entre outras empresas do Grupo. 

## Como se candidatar

Por favor envie um email para daisyleite@roadpass.com.br com seu CV anexado - enviar no assunto: Vaga DEV-Front-End e seu telefone de contato, ou entre em contato pelo tefefone, 11 3938-6740.

## Labels

- CLT
- Junior
- Pleno

**Comment by LFeh** [comment]
@fpcandido Coloca as labels corretas [seguindo nossos padrões](https://github.com/frontendbr/vagas/blob/master/.github/issue_template.md) :)

**Comment by vinyguedess** [comment]
Aceita remoto ?

**Comment by fpcandido** [comment]
Contatos, somente pelos meios descritos na vaga. A Vaga é apenas para trabalhar nas dependëncias da Empresa.
