### ISSUE TITLE
[Teresópolis RJ ou Remoto] Desenvolvedor React na Indeva Tecnologia

### ISSUE THREAD

**Issue by Cleysonlb** [frontendbr/vagas#1283]
![vaga front](https://user-images.githubusercontent.com/7593949/44147768-d30d691a-a06b-11e8-9bc4-1d7f5d38bae0.jpg)

## Descrição da vaga

Buscamos alguém que tenha interesse nas necessidades dos nossos clientes e que se identifique com o nosso negócio: ajudar profissionais do varejo de todo o Brasil a potencializar seus resultados.

## Local

Remoto ou Escritório, Teresópolis - RJ

## Benefícios

A combinar

#### Diferenciais

- Trabalhar em uma startup em constante crescimento
- Poder impactar positivamente no varejo Brasileiro por meio da tecnologia
- Vaga Remota

## Requisitos

**Obrigatórios:**
 - Experiencia com desenvolvimento em react utilizando suas técnicas e patterns
 - Ter dominio na trindade HTML, CSS e Javascript (es6/7+)
 - Redux
 - Programação assíncrona
 - Webpack
 - Compreensão dos princípios de REST e no consumo de APIs
 - Testes Unitários

**Desejáveis:**
- Programação funcional

## Contratação

 Remoto sendo PJ
 Presencial sendo CLT
 Salário a combinar

## Nossa empresa

Assumimos, com muita vontade, a missão de criar uma plataforma que transforma o varejo físico brasileiro, aumentando a produtividade e potencializando os seus resultados.

Conquistamos a confiança de +100 marcas do Varejo nacional, como: Clube Melissa, Mr Cat, Chilli Beans, Santa Lolla, Outer Shoes, Pandora, Grupo Technos, The Body Shop, AD, Rommanel, Cellairis, Taco entre outras...

nosso site: https://indeva.com.br/

## Como se candidatar

Preencha o formulario neste link: https://app.pipefy.com/public/form/aypdImFJ

## Labels

- alocação/Flexível
- alocação/Presencial
- alocação/Remoto
- experiência/Pleno
- experiência/Sênior
- regime/A-Combinar
- regime/CLT
- regime/PJ

**Comment by dcfranco** [comment]
Aplicado :)

**Comment by ribeiroevandro** [comment]
Aplicado!
