### ISSUE TITLE
[Curitiba PR] Front-End Developer na Celero

### ISSUE THREAD

**Issue by felipericieri** [frontendbr/vagas#1284]
## Descrição da vaga

Buscamos um Front-End Developer para juntar-se ao nosso time. Você irá participar do planejamento, desenvolver e implementar novas funcionalidades em nossa plataforma. Temos um grande caminho pela frente e você terá bastante liberdade para desenvolver. Você trabalhará com Bootstrap, Angular 5 e Typescript no desenvolvimento de aplicações em um ambiente que valoriza as boas práticas de programação (ex. testes automatizados, unitários, code review, etc) e metodologias de desenvolvimento ágil.

## Local

Remoto ou Onsite em:
Rua Padre Anchieta 2050 sala 1412, Bigorrilho, Curitiba/PR

## Benefícios

- VT
- VR de R$ 16/dia

## Requisitos

**Obrigatórios:**
- 1+ anos de experiência de mercado com Bootstrap, Angular 5 e Trypescript;
- Ter autonomia e pró-atividade;
- Conhecimentos em HTML5, CSS3 e Javascript;
- Experiência anterior com API's RESTful com resposta em JSON;
- Experiência com Git para versionamento de código;
- Inglês básico (leitura e escrita);

**Diferenciais:**
- Cursando ou formação em Ciências da Computação ou equivalente (não é obrigatório);
- Ter espírito empreendedor;
- Ser autodidata;
- Conhecer o ambiente de start-ups;
- Morar em Curitiba ou ter disponibilidade para se mudar para a cidade;
- Experiência na área de gestão financeira;

## Contratação

CLT

## Nossa empresa

Somos uma Fintech especializada em simplificar os processos financeiros.
Nosso propósito é facilitar a vida de empresas, revolucionando a maneira de gerir suas finanças.
Como nós fazemos isso? Aliando tecnologia de ponta e a expertise de nosso time de especialistas!
Procuramos pessoas com atitude para fazer parte de nosso time. A experiência é importante, mas o principal é a vontade de fazer a diferença!

## Como se candidatar

Por favor envie um email para rh@celero.com.br com seu CV anexado - enviar no assunto: Vaga Front-End Developer - Github/FrontendBR

## Labels

- Alocado
- CLT
- Júnior
- Pleno
- Remoto - Total

**Comment by jass2125** [comment]
Remoto total mas ter disponibilidade para se mudar para Curitiba? Isso tá certo?

**Comment by felipericieri** [comment]
@jass2125 sim, está. Para as 2 vagas abertas é indiferente. Suportam tanto onsite quanto remoto.

**Comment by jass2125** [comment]
Tá certo, obrigado @felipericieri
