### ISSUE TITLE
[São Paulo] Front-End Developer no WESTWING

### ISSUE THREAD

**Issue by westwingbr** [frontendbr/vagas#1286]
## Descrição da vaga

Estamos em busca de Desenvolvedor Front-end para a nossa equipe de TI.

Se você gosta de desafios, ambiente descontraído, dinamismo, liberdade de expor suas ideias e busca aprendizado:  venha fazer parte da equipe de TI do Westwing!

Você será responsável por:
- Manter e atualizar o front-end do site.
- Utilizar boas práticas de front-end.
- Assegurar boa performance das nossas páginas.

## Local

Escritório - Vila Leopoldina - São Paulo - Em frente a estação Villa Lobos do Metro.

## Benefícios

- Plano de saúde/odontológico com co-participação
- VR de R$ 21/dia
- VT

#### Diferenciais

- Toda segunda e quarta frutas

## Requisitos

**Obrigatórios:**
- Ter trabalhado com JS/CSS/HTML.
- Ter conhecimento de banco de dados.
- Ter trabalhado com Gulp/Grunt/Webpack.
- Escrever código legível, facilmente testável e modificável.
- Usar controle de versão.
- Ter trabalhado num time que usa metodologias ágeis.
- Ter trabalhado com metodologia ágeis.

**Diferenciais:**
- Ter inglês fluente.
- Ter conhecimento de frameworks javascript(React, Angular, Vuejs).

## Contratação

CLT (PJ a combinar)

## Nossa empresa

O Westwing está no mercado há 7 anos e somos uma multinacional alemã presente em 14 países.  

A missão Westwing é Inspirar e transformar todas as casas em um lugar mais bonito. 

Diariamente buscamos ser o líder mundial em e-commerce de casa e decoração e o oferecer para o cliente a experiência mais inspiradora e uma marca completamente apaixonante.

## Como se candidatar

Por favor envie um email para recrutamento@westwing.com.br com seu CV anexado - enviar no assunto: Vaga - Front-End Developer

## Labels

- CLT
- Pleno
- Alocado

**Comment by ribeiroevandro** [comment]
Existe a chance de Home Office full ou parcial?
