### ISSUE TITLE
Araraquara, SP - Job opportunity @S2IT - Senior Front-End Developer - Angular & English - Advanced

### ISSUE THREAD

**Issue by fagner28** [frontendbr/vagas#1288]
Quer participar de um projeto bastante legal, com tecnologias novas, interação com um time super-star e, dar um up no Inglês?

Se sim, conheça a S2IT, empresa de Desenvolvimento de Software e, junte-se a nós! No mundo dos códigos!

www.s2it.com.br

**## Descrição da vaga**

Projeto internacional com um cliente no Segmento de Seguros, em Angular +2 e, outros framerworks.

**## Local**

Escritório: Araraquara, SP

**## Benefícios**

- Plano de saúde
- Seguro de vida
- VR de R$ 385,00 / mensal
- PLR
- Vale Transporte
- Auxílio creche
- Convênio Médico

**#### Diferenciais**

- 2 horas de almoço;
- Máquina de Snacks & Sala de Descompressão, jogos, video-game, etc.
- frigobar sempre cheio :P

**## Requisitos**

Atividades: Liderança técnica; Desenvolver código da documentação e histórias de usuário; Corrigir defeitos; Automatizar e executar testes (unitários, BDD);
Ser um profissional com perfil T (conhecimento profundo em front-end, porém desejável no mínimo abertura para conhecer outras áreas de conhecimento).

Formação: Superior concluído na área de Tecnologia da Informação ou áreas afins.

### Competências Técnicas/Requisitos:

Experiência como desenvolvedor front-end com as tecnologias: HTML, CSS e JavaScript;
Ter experiência com desenvolvimento de aplicações web (Single Page Apps) com Angular(2+), TypeScript e RxJS;
Experiência com pré-processadores e pós-processadores CSS (SASS e Postcss);
Experiência com testes unitários e E2E (Jasmine, Karma, Protractor ou Selenium);
Experiência com os versionadores Git e SVN;
Contato com metodologias ágeis como Kanban, Scrum, XP, etc e práticas como TDD, BDD e Pair Programming;

Inglês Avançado - obrigatório;

**Desejável:**

Conhecimento em padrões de organização de CSS (SMACS, BEM);
Conhecimento em padrões JavaScript;
Conhecimento em criação de aplicações usando SSR (Server-Side Rendering, Angular Universal);
Conhecimento em criação de aplicações usando os conceitos de PWA (Progressive Web App);
Conhecimento em utilizar as ferramentas de debugger como o Chrome Dev Tools;
Conhecimento em gerenciadores de dependência/pacotes (npm, Yarn; Maven e Gradle é um plus);
Conhecimento em automatizadores de tarefas ou bundle generators como o Gulp ou Webpack;
Conhecimento em ferramenta de Continous Integration (Jenkins);
Conhecimento em serviços REST API, WEB Standards e AJAX (protocolos, verbos e respostas HTTP, certificados, URI's, etc);
Conhecimento em configuração de servidores WEB como Apache ou NGINX;
Conhecimento em aplicações PHP (Symfony2, Laravel);
Conhecimento básico em SQL;
Noções de UX e Design de Interação;

## Contratação: CLT FULL

Interessados, cadastrar CV no site abaixo e ou via e-mail: vagas@s2it.com.br

https://jobs.kenoby.com/s2it/job/desenvolvedor-front-end-senior-angular-e-ingles/5b3f8bda7f94af54802cb137

**Comment by mtmr0x** [comment]
@fagner28 consigo extrair as informações da vaga, mas só para nos ajudar e ajudar a integrações presentes e futuras, poderia ao fim do post colocar as labels de acordo com as opções de labels igual tem no modelo de uma issue, por favor? O Modelo pode ser encontrado aqui: https://github.com/frontendbr/vagas/blob/master/.github/issue_template.md

**Comment by mtmr0x** [comment]
@fagner28 dado as regras para resposta em caso de a vaga estar fora do modelo da issue, estou fechando essa e pode ser reaberta caso entre no modelo que comentei no meu ultimo comentario aqui
