### ISSUE TITLE
[Rio de Janeiro] Front-end Developer / React

### ISSUE THREAD

**Issue by moura** [frontendbr/vagas#129]
## Descrição da vaga

As atribuições desse papel compreendem o discovery, design, arquitetura, implementação, publicação e manutenção de aplicações e bibliotecas para dispositivos móveis. Você participará de discussões de produto e será responsável junto com o restante do time de propor a melhor solução técnica para o problema em questão. Você vai trabalhar, no seu dia-a-dia, com o desenvolvimento de aplicações e ferramentas para melhoria do processo de desenvolvimento, sempre buscando a alta disponibilidade e qualidade. Atuando dentro de um time multidisciplinar, a tendência é que você também execute outras tarefas além dessas, dependendo do momento de cada projeto.

Esta vaga é para o nosso novo escritório no Rio de Janeiro/RJ. Pessoas de qualquer parte do Brasil são muito bem-vindas - a globo.com tem uma grande quantidade de profissionais de diversos estados. Temos um pacote especial de benefícos para a mudança de pessoas de fora da cidade.
## Local

Alocado, Rio de Janeiro - Barra da Tijuca
## Benefícios

Assistência Médica,
Assistência Odontológica,
Tíquete-refeição
## Requisitos

**Obrigatórios:**
Ser apaixonada(o) por desenvolvimento de software e tecnologia
Ser poliglota em linguagens de programação e plataformas;
Ter facilidade para trabalhar dentro de times multi-disciplinares;
Saber escrever código limpo e legível;
Ter experiência com React;
Possuir conhecimentos de integração utilizando API RESTful;
Ter conhecimento de práticas de XP (TDD, pair programming, refactoring, continuous integration, etc);
Conhecer e ter experiência com testes unitários, de aceitação, mocks, etc;
Saber trabalhar com ferramentas de controle de versão;
Conhecimentos de design de interface e experiência do usuário.
fluência em inglês (leitura: avançado, escrita: intermediário, fala: intermediário)

**Desejáveis:**
Ter experiência com React Native;

**Diferenciais:**
Conhecimentos de desenvolvimento WEB (HTML, CSS, Javascript, jQuery, etc);
Ter experiência com Android;
Ter experiência com Objective C e/ou Swift;
Conhecimentos de automação de publicação de aplicações (fabric, etc);
Experiência com métodos ágeis (Scrum, Kanban, Lean, etc);
Experiência de trabalho com times geograficamente distribuidos;
Experiência em mentoring/coaching de pares e team members menos experientes.
## Contratação

CLT - Júnior, Plano ou Sênior
## Nossa empresa

A Globo.com é o ramo da Internet do Grupo Globo, o maior conglomerado de mídia na América Latina, com escritórios no Rio de Janeiro, São Paulo e Porto Alegre.
Ela agrega os maiores portais do Brasil, sobre Notícias (G1) , Esportes (globoesporte.com), vídeos (Globo Play) e Entretenimento (Gshow).
Tem a excelência na distribuição web de alto volume e é responsável pelas maiores audiências de streaming de vídeo simultâneas no país.
## Como se candidatar

Favor enviar curriculum através do nosso [site](https://talentos.globo.com/#/oportunidades/desenvolvedor-a-react-native/mp0mu5i)

**Comment by camilatigre** [comment]
@moura 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by moura** [comment]
@camilatigre 
A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
