### ISSUE TITLE
FRONT-END DEVELOPER - OPAH IT CONSULTING

### ISSUE THREAD

**Issue by Pharcon** [frontendbr/vagas#1290]
POR FAVOR, SÓ POSTE SE A VAGA FOR PARA FRONT-END!

Não faça distinção de gênero no título da vaga.
Desenvolvedor Front-End

Sólidos conhecimentos em:

 Javascript e seus frameworks (jquery, angular, node, etc)

CSS 3 e HTML 5

integrações REST e SOAP

Diferencial para vaga conhecer:
Java

SOA

Web e API

**Comment by Pharcon** [comment]
Desenvolvedor Front-End

Sólidos conhecimentos em:

 Javascript e seus frameworks (jquery, angular, node, etc)

CSS 3 e HTML 5

integrações REST e SOAP

Diferencial para vaga conhecer:
Java

SOA

Web e API

**Comment by ngustavo** [comment]
Em qual local?

**Comment by Pharcon** [comment]
Zona Sul de SP

Em sex, 17 de ago de 2018 21:38, Gustavo N. <notifications@github.com>
escreveu:

**Comment by mtmr0x** [comment]
@Pharcon poderia seguir o modelo da issue para postar a vaga? Ao criar a issue, o modelo já vem montado, é só substituir os valores ou então seguir esse modelo aqui para editar essa aqui https://github.com/frontendbr/vagas/blob/master/.github/issue_template.md

Essa vaga estando nos padrões, reabrimos a issue
