### ISSUE TITLE
[Rio de Janeiro] Front-End Developer na WOOZA

### ISSUE THREAD

**Issue by brunoromeiro** [frontendbr/vagas#1291]
## Descrição da vaga

- Dar suporte na manutenção às páginas HTMLs existentes de média/alta complexidade;
- Estudar as melhores práticas para desenvolvimento de páginas HTMLs;
- Codificar layouts padrão pixel-perfect e boas interações de usuário;
- Implementar projetos dentro do padrão GIT Flow;
- Investir na aprendizagem para o domínio do Angular, TDD (desenvolvimento baseado em testes)
- ES6 e Javascript avançado;

Que tecnologias utilizamos:
- JavaScript (ES6, Node)
- Angular, Sass, Jasmine, Jest
- Webpack, Gulp

## Local

Escritório, Downtown Barra da Tijuca

## Benefícios

- Plano de saúde Bradesco
- Plano dental Amil
- Seguro de vida
- VR de R$ 26/dia
- Convênio com faculdades
- Palestras internas (Desenvolvimento, Agile, Workshops)
- Reuniões de melhoria e levantamento de novas tecnologias
- Times Unidos 💪

#### Diferenciais

- Louge
- Fliperama Retrô 👾
- Frutas durante o dia
- Ambiente bem amigável e tranquilo para se trabalhar

## Requisitos

**Obrigatórios:**

- Inglês técnico;
- Domínimo de versionamento com Git
- Excelente conhecimento em HTML, CSS (SASS/LESS) e JavaScript
- Grande conhecimento em Angular

**Diferenciais:**
- Conhecimento em desenvolvimento de testes com Jasmine ou Jest
- Automatização de tarefas e bundling, preferencialmente com Webpack
- Conhecimentos de React

## Contratação

CLT

## Nossa empresa

Uma empresa de marketing e vendas de serviços digitais  não é feita apenas por números, soluções e relatórios. Para garantir uma performance superior e eficaz, nos cercamos de gente inspirada, inquieta, curiosa e competente. Nossa gente é movida por sonhos e desafios, apaixonada pelo que faz e tem garra para fazer acontecer tudo dentro de elevados padrões éticos e se superar a cada dia.

## Como se candidatar

Para fazer parte deste time você só precisa enviar o seu currículo para raquel.silva@wooza.com.br - enviar no assunto Front-End Developer.

## Labels

- Alocado
- CLT
- Pleno
- Sênior

**Comment by juansaintclair** [comment]
Recomendo fortemente. Excelente empresa para se trabalhar!
