### ISSUE TITLE
[São Paulo - SP] Front-end Developer Pleno na WeJam

### ISSUE THREAD

**Issue by crispossa** [frontendbr/vagas#1293]
## Descrição da vaga

Vaga para desenvolvedor Front-end Pleno.
Utilizar boas práticas de desenvolvimento HTML/CSS/JS.
Metodologia de trabalho SCRUM.

## Local

A vaga é para trabalho remoto dedicado, com compromisso de entregas.

## Requisitos

**Obrigatórios:**
- Experiência comprovada com projetos realizados
- Experiência com HTML/CSS/JS
- LESS/SASS
- Automatizadores como gulp ou webpack

**Desejáveis:**
- Experiência com integrações com Wordpress
- Otimização/Performance front-end

## Contratação

- Remoto
- PJ (Pode ser MEI)
- Início imediato

## Nossa empresa

Somos uma agência com DNA digital que desenvolve projetos de alta qualidade e com grande impacto em negócios, desde sites institucionais até plataformas de treinamento e gamification.

Somos uma agência com uma proposta diferente. Não apenas executamos jobs, mas criamos envolvimento com nossos clientes e projetos.

Participamos desde a concepção do projeto até sua publicação numa filosofia ponta-a-ponta, onde planejamos, construímos e desenvolvemos ideias incríveis.

Venha fazer parte da nossa equipe!

We Ad! We Rock! We Jam!

## Como se candidatar

Envie um e-mail para queroserdev@wejam.email com seu currículo e links para projetos desenvolvidos.

## Labels

- Remoto
- PJ
- Pleno

**Comment by laugustofrontend** [comment]
Enviado
