### ISSUE TITLE
Frontend Developer 

### ISSUE THREAD

**Issue by patyandreolli** [frontendbr/vagas#1298]
Frontend Developer

Skill Set:
•	Good experience with HTML/CSS/Java Script;
•	Must be able to generate HTML from PSD;
•	Must have experience with Angular 2+ development;
•	Fluency in Portuguese and English.

CLT + Attractive salaries ( Bonus Program, Career path Plan
HR Buddy/Mentorship program, International Company, Health and Dental Plan (100% paid by the company), Education Benefits, Sport Benefits, Sponsored English classes, Sponsored Certifications
Location: Fortaleza

=> recrutamento@infovagas.com

**Comment by mtmr0x** [comment]
@patyandreolli poderia seguir o modelo da issue para postar a vaga? Ao criar a issue, o modelo já vem montado, é só substituir os valores ou então seguir esse modelo aqui para editar essa aqui https://github.com/frontendbr/vagas/blob/master/.github/issue_template.md

Essa vaga estando nos padrões, reabrimos a issue
