### ISSUE TITLE
[São José dos Campos] Front-End Developer na mLabs

### ISSUE THREAD

**Issue by safirelauene** [frontendbr/vagas#1299]
## Descrição da vaga

Atuar na plataforma da mLabs juntamente com outras pessoas do time de frontend, trabalhando principalmente com Ember.js. Não precisa necessariamente de experiência com Ember, mas é essencial entender as bases e essência do JavaScript.

## Local

Escritório: Av. Cassiano Ricardo, 601 - Ed. The One - 9.andar, São José dos Campos - Jd. Aquárius

## Benefícios

- DayOff (tire 1 dia de descanso no mês do seu aniversário)
- Convênio médico e odontológico (50% para a pessoa e dependentes)
- Subsídio para estudos e eventos técnicos
- VT
- VR

#### Diferenciais

- Festa de aniversariantes toda última sexta-feira do mês com bebida a vontade
- Open fruta, todynho e coca-cola
- Ambiente descontraído e com pessoas legais

## Requisitos

**Obrigatórios:**
- HTML5;
- CSS3;
- Javascript;
- Experiência com algum Framework JS;
- Experiência com Design Responsivo.

**Desejáveis:**
- Conhecimento de Git;
- Domínio de Semântica HTML.

**Diferenciais:**
- Experiência com Ember.js;
- Experiência com Pré-Processador CSS.

## Contratação

CLT

## Nossa empresa

A mLabs nasceu para fazer a inclusão digital de micro, pequenas e médias empresas nas redes sociais e ajudá-las a terem sucesso através de uma plataforma inteligente e facilitadora de gestão das mídias sociais.
Nosso produto é uma plataforma de gestão de redes sociais onde você pode agendar posts para Facebook, Instagram, Instagram Stories, Pinterest, LinkedIn, Twitter e YouTube, ter relatórios exclusivos e ilimitados, usuários ilimitados, workflow de aprovação de conteúdo, gerenciamento de comunidade, gerenciamento de inbox, feed, e muito mais.
A nossa missão é ser a melhor plataforma de custo-benefício do mercado, focada em ter um algoritmo inteligente de recomendação, baseado em Inteligência Artificial, para tonar mais eficaz as ações em redes sociais e, consequentemente, aumentar os resultados dos nossos clientes.

## Como se candidatar

Por favor envie um email para safire.silva@mlabs.com.br com seu CV anexado - enviar no assunto: Vaga Front-End

## Labels

- Alocado
- CLT
- Júnior
- Pleno

**Comment by lzhudson** [comment]
Possibilidade para remoto?

**Comment by safirelauene** [comment]
Pior que não, somente alocado :/

**Comment by ferreirabh** [comment]
Boa tarde, não estou conseguindo enviar meu CV.

**Comment by ribeiroevandro** [comment]
Enviado!

**Comment by monteirocamis** [comment]
Olá, tem possibilidade de parte em remoto? Sou de São josé dos campos mas moro em São paulo.Estou semanalmente em São José pela familia =)

**Comment by denis1206** [comment]
a vaga ja foi preenchida?
