### ISSUE TITLE
[São Paulo] Front end Developer 

### ISSUE THREAD

**Issue by DanielaGomes1** [frontendbr/vagas#130]
## Descrição da vaga

Procuramos programadores com perfil dinâmico, proativo que tenham bom nível de energia. Deve apresentar capacidade de trabalho em equipe, com boa relação interpessoal e auto-gestão de projetos. 
Perfil lógico e hábil na resolução de problemas complexos, possuir sede por conhecimento, com aprendizado rápido e capacidade de entender diferentes ambientes profissionais e suas regras de negócios.
## Local

Próximo a Avenida Paulista (metrô Brigadeiro)
## Benefícios
- Café da manhã
- Freezer gelato "diletto"
- Monitor extra para o seu bem estar
- Parceria com escolas de inglês, agência de turismo, programa de incentivo "indique e ganhe"
## Requisitos

**Obrigatórios:**

• Atenção aos detalhes;
• HTML, CSS e JavaScript;
• Habilidade para escrever código semântico e legível; 
• Experiência com design responsivo;
• Versionamento de código (git, gitflow);
• Teste crossbrowser (IE9+);
• Automatizadores de tarefa (Gulp, webpack, grunt);
• Noções básicas de Photoshop / Sketch;
• Inglês técnico (afinal, você provavelmente irá precisar em uma interpretação de código e ou pesquisa de erros e soluções);
• Atuação em desenvolvimento de projetos, utilizando metodologias ágeis (SCRUM, XP);
• Experiência com Javascript frameworks;

**Desejáveis:**

• Atuação em projetos com Drupal; 
•  Atuação em projetos com angular.js;
• Noções de UX/UI;
• SCRUM;
• Conhecimento em PHP;
• Que tenha trabalhado em projetos diferenciados, temos interesse em conhecer o seu portfólio;
## Contratação

PJ
## Nossa empresa

Uma empresa de desenvolvimento? Uma consultoria de tecnologia? Uma agência digital? Também não temos resposta pronta para isso. A Vorttex é uma empresa de Code-Switching e nosso propósito é observar cenários, problemas, públicos e necessidades; identificar oportunidades; gerar Insight e ideias; codificar as soluções; entender como a solução foi recebida e recodificar se necessário.
## Como se candidatar

Por favor envie um email para daniela.gomes@vorttex.com.br com seu CV anexado e portfólios - enviar no assunto: Front end Developer

**Comment by LFeh** [comment]
Pleno ou Senior?

**Comment by brncamara** [comment]
Para esta vaga é Sênior.

**Comment by DanielaGomes1** [comment]
Olá, esta posição é para um perfil sênior.
