### ISSUE TITLE
[Rio de Janeiro] Full stack Developer na DCLICK

### ISSUE THREAD

**Issue by mbraz** [frontendbr/vagas#1300]
## Descrição da vaga

Developer com facilidade em aprender novas tecnologias!

## Local

Rio de Janeiro

## Benefícios

- Plano de saúde
- Ticket

## Requisitos

**Obrigatórios:**
- Facilidade em aprender novas tecnologias
- Javascript
- HTML5

**Desejáveis:**
- NodeJS
- MongoDB
- React
- Redux

## Nossa empresa

www.dclick.com.br

## Como se candidatar

Por favor envie um email para marcelo.braz@dclick.com.br com seu CV anexado - enviar no assunto: Vaga FULL STACK DEVELOPER

## Labels

- Alocado
- Pleno
- Safo

**Comment by mtmr0x** [comment]
@mbraz poderia editar a parte de `labels` com o tipo de contratação esperada (CLT ou PJ), por favor?

**Comment by RaphaAmericano** [comment]
Apenas nível pleno?
