### ISSUE TITLE
[Portugal] Front-End Developer (React) na Aubay

### ISSUE THREAD

**Issue by monicantunes** [frontendbr/vagas#1303]
## Descrição da vaga

Projeto nearshore para um web site internacional na área do turismo (restauração, alojamento local e hotéis).

## Local

Lisboa

## Benefícios

• Plano de saúde
• Apoio jurídico para obtenção de visto de trabalho
• Outras

#### Diferenciais

• Formações técnicas e comportamentais
• Prémios de referências de recrutamento
• Eventos team Building
• Convívio mensal
• Oferta de aniversário

## Requisitos

**Obrigatórios:**
• Experiência em React
• Nível de inglês fluente 

**Desejáveis:**
• Licenciatura em engenharia informática ou de computadores
• Experiência em Start ups
• Conhecimentos em Redux

## Contratação

Apoio em todo o processo para obtenção de visto de trabalho para Portugal.

## Nossa empresa

A Aubay, é uma empresa de origem francesa presente em diversos países na Europa.
Como cerca de 6000 pessoas desenvolvemos projetos nas mais diversas tecnologias.
Neste momento, temos várias vagas em aberto para várias posições.

## Como se candidatar

Por favor envie um email para mantunessilvestre@aubay.com com seu CV anexado.

## Labels

- Alocado
- Javascript
- React
- Front-End
- Inglês fluente

**Comment by mtmr0x** [comment]
@monicantunes no modelo da issue (https://github.com/frontendbr/vagas/blob/master/.github/issue_template.md) tem uma última parte com o título *Labels*. Elas servem para ajudar a caracterizar a vaga para o tipo de candidato. Poderia só adicionar as que fazem sentido para essa vaga nela, por favor?
