### ISSUE TITLE
[São Paulo] Full stack Developer na Juros Baixos

### ISSUE THREAD

**Issue by rscoutinho** [frontendbr/vagas#1308]
## Descrição da vaga

Se você está interessado em obter uma experiência maneira, se desenvolver como programador e ainda trabalhar num ambiente super empreendedor, o Juros Baixos pode te proporcionar tudo isso. A vaga aberta tem o foco em ajudar a desenvolver o nosso novo portal de simulação de serviços financeiros, integrando APIs ao nosso backend e também ajudando na implementação dos nossos novos layouts.

## Local

São Paulo - Bela Vista

## Benefícios

- Plano de saúde (50% para a pessoa)
- VR
- VT
- Gympass

#### Diferenciais

- Ambiente descontraído, super dinâmico
- Horário flexível
- Possibilidade de home-office
- Geral de bermuda e chinelo =)
- Plano de carreira
- Equipes autônomas 

## Requisitos

**Obrigatórios:**
- Node.js
- Angular.js
- React
- Vue.js
- Css/Javascript/Html

**Desejáveis:**

- Experiência em consumir APIs REST e SOAP
- Wordpress
- Metodologia ágil (Scrum)

## Contratação

PJ a combinar

## Nossa empresa

Somos um orientador de crédito e financiamentos, e temos a missão de facilitar a vida de quem quer um empréstimo.

Em nossa página, o cidadão comum pode simular empréstimos em diversos bancos, financeiras e fintechs de crédito online, conseguindo inclusive contratar empréstimos em parceiros diretamente por nós. Visamos inovar no mercado financeiro promovendo a transparência e a concorrência no mercado de crédito, além de mostrar conteúdos ricos, relevantes e gratuitos sobre crédito e finanças para nossos usuários.

Queremos descomplicar os bancos.

Além de servir como ferramenta de comparação e transparência nos empréstimos pessoais, apoiamos iniciativas de educação financeira, juntando gente boa que quer impactar a consciência financeira dos brasileiros.

Dá uma olhada no nosso site (Eu sei, tá precisando ser reformulado, e com certeza você vai ajudar a gente nisso =)) -https://jurosbaixos.com.br/

Se liga também no nosso canal do youtube - 

https://www.youtube.com/channel/UCB5ESZO4m45pJ72PsVjZC2g 

## Como se candidatar

Por favor envie um email para rscoutinho@live.com com seu CV anexado - enviar no assunto: Vaga Programador SP -JB

## Labels

- Alocado
- Júnior
- PJ
- Pleno
- Remoto - Parcial

**Comment by fafa1** [comment]
Boa noite, a vaga é apenas para pessoas residentes em são paulo?

**Comment by Buul** [comment]
Aceita full remoto ?
