### ISSUE TITLE
[São Paulo] - Frontend

### ISSUE THREAD

**Issue by highlabs** [frontendbr/vagas#131]
## Descrição da vaga

Procuramos front-end Pleno+ para trabalhar em projetos aqui na @labCorp.
Você será responsável por planejar o stack de front, criar layouts a partir do PSD e trabalhar junto com a equipe de backend.

## Local

Presencial. São Paulo, Av. Prof. Franscisco Morato... butantã!

## Requisitos

**Obrigatórios:**

- CSS/HTML
- VanillaJS / ES6
- jQuery
- Gulp
- Saber criar layout a partir do PSD (aqui usamos o Avocode https://avocode.com/)

**Desejáveis:**

- VueJS
- Python/Django (pelo menos as templates tags)
- SSH/Linux

## Contratação, Benefícios e Salário

- TBD

## Nossa empresa

Somos uma empresa feita por estrategistas, publicitários, ciativos e desenvolvedores, pronta para atender às necessidades do mundo digital.

## Como se candidatar

Por favor envie um email para dev@labcorp.com.br com seu CV anexado / Github/ Site - enviar no assunto: Vaga Frontend

**Comment by highlabs** [comment]
Tags: Alocado, PJ, Pleno

**Comment by LFeh** [comment]
Rolou?

**Comment by highlabs** [comment]
Ainda não, porém não tenho mais acesso ao processo seletivo.
Então prefiro fechar a issue do que não ter acesso a maiores informações e deixar a galera mandando CV a toa. :/

**Comment by LFeh** [comment]
Beleza!

**Comment by camilatigre** [comment]
@highlabs 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
