### ISSUE TITLE
[São Paulo] Front-End Developer / React no Mercado Livre

### ISSUE THREAD

**Issue by RicardoJunior** [frontendbr/vagas#1319]
## Descrição da vaga

Temos vagas para o nosso time de Core Marketplace / Supply aqui no Mercado Livre.
Alguns dos fronts do Time: 
Eu (@ricardojunior), Felizola  (@gfelizola), Iram (@iramlg), Gigi (@GillMacedo), Leandro (@leandroffaria) e Léo (@lesoaresml).

## Local

[Melicidade](https://www.youtube.com/watch?v=9mB5ohJPsgE), São Paulo - Osasco ([Mapa](https://goo.gl/maps/bAZcJc5m43u))

## Benefícios

- Refeitório / Cafeteria
- Vale alimentação de R$ 500,00 (Mercado)
- MeliBus / Estacionamento / Vale transporte / Fretado / Vale combustível (R$ 700,00)
- Sala de jogos (ping pong / tótó / playstation / xbox / quadra poliesportiva )
- Academia sem custo (Bio Ritmo)
- Massagem semanal sem custo
- Bonificação anual de até 3 salários
- Benefícios GOIntegro
- [Bynd](https://bynd.com.br/)
- Assistência Médica
- Assistência Odontológica
- Convênio Farmácia
- Seguro de vida
- Previdência Privada (até 4% do salário de desconto + 100% do valor pago pelo @mercadolibre)
- Auxílio Creche
- Auxílio Farmácia (e-pharma)

#### Diferenciais

- Salário competitivo
- Happy Hour Mensal
- Horário muito flexível
- Home Office Semanal (1 dia) após 3 meses
- Monte a sua máquina como desejar (Mac ftw)
- Bonificação anual de até 3 salários
- Professores de inglês e espanhol na firma
- Liberdade na tomada de decisão (tecnologia, gestão de tarefas, etc)
- Aprendizado constante

## Requisitos

**Obrigatórios:**
- Experiencia a nível pleno com Node
- Experiência mínima de conceito com React
- Experiência a nível sênior em Front-End (html, css, javascript, pre-processadores, task-runners)

- Git
- Metodologias Ágeis

**Diferenciais:**
- projetos opensource
- ter trabalhado com e-commerce
- Redux
- GraphQL
- Testes unitários e E2E

## Contratação

CLT (salário a combinar)

## Nossa empresa

No Mercado Livre estamos democratizando o comércio e os pagamentos na América Latina.

Tecnologia é a essência de nosso produto. Equipes integradas de desenvolvedores, arquitetos, especialistas em banco de dados, experiência do usuário, inteligência de negócios, co-criam e são responsáveis pela principal plataforma para e-commerce da América Latina e um dos lugares de maior tráfego em todo o mundo. Em uma indústria que se reinventa diariamente, os profissionais de TI do Mercado Livre são reconhecidos por sua visão e liderança. De aplicações móveis a aprendizagem de máquina, a nossa inovação tem um foco claro: facilitar a vida do usuário, de modo que se possa comprar e vender com a melhor experiência. Temos mais de 2000 desenvolvedores, todos focados em criar as melhores experiências para nossos clientes. Fomos eleitos no ano passado como 3ª melhor empresa para trabalhar pelo Great Place to Work.

## Como se candidatar

Por favor envie um email para ricardo.junior@mercadolivre.com com o assunto: 
"Vaga Front-End (github/frontendbr)"

**Comment by RicardoJunior** [comment]
## Labels

- Alocado
- CLT
- Pleno
- Sênior

**Comment by kerenarielle** [comment]
Top a vaga @RicardoJunior , pena que eu não tenho muito conhecimento em node ainda!!

**Comment by davidalves1** [comment]
Que vaga lindona!

**Comment by matheus-rosin** [comment]
@RicardoJunior o que deve ser entendido por "experiência a nível pleno de Node"?
