### ISSUE TITLE
[São Paulo - SP - PJ - Alocado] Frontend Developer Pleno

### ISSUE THREAD

**Issue by robsonlb** [frontendbr/vagas#1321]
Estamos contratando Frontend Developer Pleno
Obrigatórios:
Domínio de HTML, CSS, JS, Jquery;
Style guides;
Padrões de Projeto;
Conhecimento de sistema de GRIDs;
Experiência com versionamento GIT/SVN, preferencialmente GIT;
Experiencia com Design Responsivo (mobile first);

SEO;
Tagueamento de sites;
Photoshop - para recortar as imagens

Diferenciais:
Experiência em Metodologias ágeis;
Conhecimento de BackEnd (para melhor iteração entre as partes);
Noção de áreas de TI (servidor, banco de dados, redes, etc.);

Contratação
PJ
Alocado
Valor R$ 6.000,00

Local
São Paulo - Vila Madalena

Como se candidatar
Por favor envie um email para robson@purplecow.com.br com seu CV anexado - enviar no assunto: Frontend Developer

**Comment by mtmr0x** [comment]
@robsonlb ao criar uma issue aqui com uma vaga, seu modelo precisaria seguir o modelo da issue, conforme está escrito no nosso README.md na raiz do repositório, o modelo se encontra aqui: https://github.com/frontendbr/vagas/blob/master/.github/issue_template.md

Eu preciso invalidar essa vaga por não seguir o modelo e podemos reabrir a issue quando estiver de acordo.
