### ISSUE TITLE
[Diversos] Vaga Alocado Front-end Codeminer 42

### ISSUE THREAD

**Issue by abnersajr** [frontendbr/vagas#1323]
## Descrição da vaga

Buscamos Front-end developers para atuar nos diversos projetos, inclusive projetos internacionais com clientes estrangeiros. Temos diversos projetos, com diversos frameworks e tecnologias, então entre em contato.
Estamos procurando pessoas de todo os níveis para fazer parte de nosso time, sem diferenças nem preferências. Todos são bem vindos.
## Local

A Codeminer42 está presente atualmente em 10 estados do país. 
Temos vagas para todos eles. 
- São Paulo
- Campinas
- Sorocaba
- Batatais
- Guarapuava
- Novo Hamburgo
- Anápolis
- Goiânia
- Teresina
- Natal
- Santa Maria
- Florianópolis
- Belo Horizonte

OBS: Presencialmente apenas

## Benefícios
1. Plano de saúde e dental;
2. Auxílio transporte;
3. Vale-refeição;
4. Ambiente de trabalho descontraído;
5. Acesso a cursos e portais de educação como Front-end Masters e egghead.io;
6. Curso de inglês para aperfeiçoamento.

#### Diferenciais

- Horário flexível
- Oportunidade de trabalhar em projetos nacionais e internacionais 

## Requisitos

**Obrigatórios:**
- Experiência com React
- Ou React Native
- Ou VueJS
- Ou todos eles
- Testes Unitários
- Inglês Intermediário, temos clientes internacionais, logo o candidato tendo um nível de compreensão e conversação legal podera estar entrando em um projeto internacional. Lembrando que o inglês não precisa ser 100%. Por isso fazemos uma entrevista para ver como você se sai.

**Desejáveis:**
- conhecimentos em ruby on rails
- conhecimentos em NodeJS

## Contratação

CLT, valores depende do seu nível

## Nossa empresa

A Codeminer 42 é uma butique de software brasileira focada em entregar o melhor valor a seus clientes. Nós começamos a operar em Setembro de 2011 e até agora expandimos para 10 cidades diferentes no Brasil com os melhores profissionais do Brasil.

Nossa especialidade é desenvolvimento web com Ruby on Rails e seu ecossistema satélite - que inclui as melhores tecnologias de ponta -, nós temos muita experiência em todos os tipos de produtos de tecnologia como e-commerces, e-learning, redes sociais, gerenciamento de conteúdo, automação de processos.

Trabalhamos para empresas pequenas ou grandes, temos diversos tipos de serviços que vão de ciclo de vida de desenvolvimento de projetos do zero, resgate de projetos legados, terceirização e assim por diante.

Se quiser ter não somente uma boa aplicação web em produção mas também melhorar seus processos de software, garantia de qualidade, podemos ajudar.

## Como se candidatar

Por favor envie um email para become@codeminer42.com com seu CV anexado, github, site pessoal e demais infos.
No Assunto coloque [CIDADE] Vaga para Front-end .
Maiores dúvidas, podem usar a issue ou enviar para abner.alves@codeminer42.com

## Labels
* CLT
* Alocado
* Estágio
* Júnior
* Pleno
* Sênior

**Comment by mtmr0x** [comment]
@abnersajr no final de cada modelo de issue tem as labels para nos ajudar a coloca-las aqui para candidatos melhor filtrarem suas vagas e para ficar padronizado na leitura por conexões que fazemos com outras ferramentas. O modelo da issue está aqui: https://github.com/frontendbr/vagas/blob/master/.github/issue_template.md

poderia só adicionar todas as labels que fazem sentido com sua vaga, por favor?

**Comment by abnersajr** [comment]
Done @mtmr0x :+1:

**Comment by abnersajr** [comment]
Adicionar Estágio Por favor @LFeh ou @mtmr0x

**Comment by abnersajr** [comment]
Fala galera, continuamos com vagas abertas e querendo novos colegas de equipe! Quem quiser mais infos fala que respondo :)
