### ISSUE TITLE
[São Paulo] Desenvolvedor(a) Front-end  na Evnts

### ISSUE THREAD

**Issue by GuilhermeBorges** [frontendbr/vagas#1324]
## Sobre a Evnts 

A Evnts é a empresa líder na América Latina em reserva de hotéis para eventos (Feiras e Congressos e Entretenimento). Temos entre outras centenas de clientes Rock in Rio, Lollapalooza (T4F) e Reed Exhibitions, além de grande parte das principais feiras e congressos em todo o Brasil. Somos líderes também em eventos de tecnologia, como BrazilJS, ReactConf, TheDevConf e vários outros.  (yes, we have free tickets \o/). 
 
Todos os dias quebramos barreiras e reinventamos a maneira de se fazer turismo no Brasil, voltado para o segmento corporativo (B2B), e procuramos pessoas que sonham em fazer isso com a gente, criando o futuro de como será este mercado. 

Somos um time enxuto, transparente e 100% focados em um objetivo comum. 

## Descrição das vagas

Na Evnts, o Desenvolvedor Front End é responsável pelo desenvolvimento dos produtos que irão moldar diversas tecnologias inovadoras que estão sendo usadas para reinventar a forma como se faz turismo corporativo no Brasil, criando novas features, se atendo à melhoria contínua e evolutiva, sendo sempre incentivado a criticar e melhorar a forma como as ferramentas são feitas durante todo o processo, até a entrega. 

Você irá atuar com uma equipe qualificada e empolgada a fazer melhor todos os dias, sendo parte de um ambiente colaborativo e que inspira inovação.  

Estamos a procura de mais de um desenvolvedor(a).

## Local

Nosso escritório fica na Av. Paulista, 1374 (WeWork Paulista), em São Paulo, bem em frente a Estação de Metrô Trianon Masp. 

## Benefícios

  - Horário flexível;
  - Home office;
  - Não há dress code (você pode usar o que quiser, sempre);
  - Liberdade e autonomia;
  - Vale alimentação ou refeição;
  - Vale transporte;
  - Plano de saúde;
  - Plano odontológico;
  - Plano de carreira;
  - Ambiente de trabalho da WeWork, com vários "perks" como café, leite, chá e chopp (!!) disponíveis o tempo todo, além de várias outras coisas bacanas no ambiente compartilhado 

## Diferenciais

  - Flexibilidade de horário (mesmo!);
  - Flexibilidade para trabalhar remoto sempre que quiser;
  - Não há dress code (liberdade para vestir o que quiser);
  - Elegibilidade ao plano de stock options da Evnts;
  - VT não descontado do salário;
  - Influência direta nas decisões de produto;
  - Ambiente de trabalho qualificado e descontraído;

## Requisitos

- Obrigatórios:
  - Experiência com desenvolvimento Web;
  - HTML (semântica, acessibilidade);
  - JavaScript (ES2015 / Design Patterns);
  - CSS (pré-processadores / arquitetura);
  - Gostar muito de aprender e compartilhar;

- Desejáveis:
  - React;
  - Experiência com grandes aplicações;
  - Conhecimento em testes de JavaScript (TDD / BDD);
  - Ter trabalhado com metodologia ágil;

- Diferenciais:
  - Projetos opensource;
  - Gestão de equipes;
  - Metodologias scrum;

## Contratação

CLT ou PJ, o que voce preferir 

## Como se candidatar

Envie um email para vagas@evnts.com.br com (fique a vontade para adicionar Github, Linkedin, CV, ou outros se quiser) 

Colocar no assunto: ``` `Vaga Front-end Developer - [${seuNome}]` ```

## Labels

  - Alocação/Flexível
  - Alocação/Remoto
  - Experiência/Pleno
  - Experiência/Sênior
  - Regime/A-Combinar
  - Regime/CLT
  - Regime/PJ

**Comment by kvnol** [comment]
Vagona! Enviei.
