### ISSUE TITLE
[São Paulo] Desenvolvedor Front-End/ Web Designer Jr.

### ISSUE THREAD

**Issue by nayarahilton** [frontendbr/vagas#133]
## Local

RINO COM (Agência de Publicidade), São Paulo - Jardim Paulista
## Descrição da vaga

Atuará na área de criação e desenvolvimento.

Criação:
Layouts, banners, peças de mídia, e-mail marketing, posts para facebook, hotsites e landing pages.

Desenvolvimento:
E-mail marketing, hotsites e landing pages.
## Requisitos
- Photoshop
- Illustrator
- HTML/CSS
- Animate (Flash)
## Diferenciais
- Desenvolvimento responsivo de e-mail marketing.
- Se interessar pela parte de criação e desenvolvimento e ter facilidade de transitar entre as duas.
## Contratação

PJ 
## Salário

R$2.500
## Benefícios
- A combinar
## Como se candidatar

Por favor envie um e-mail para nayara@rinocom.com.br com cópia para narciso@rinocom.com.br com seu portfólio e CV em anexo - enviar no assunto: Vaga Web Designer Jr.

**Comment by torto** [comment]
Estou vivo ainda para ver vagas que pedem flash como requisito, obrigado Inês Brasil por me permitir ver isso :heart: :dancers:

**Comment by nayarahilton** [comment]
Animate (Flash) apenas para desenvolvimento de algumas peças de mídia (banner animado em HTML5) ;)

**Comment by nayarocha** [comment]
A vaga ainda esta aberta?

**Comment by HaluDeCassia** [comment]
@LFeh verifique essas vagas ainda abertas mas de muito tempo, por favor

**Comment by LFeh** [comment]
Pois é, precisamos mesmo...
