### ISSUE TITLE
Backend Developer- Zona oeste, sp

### ISSUE THREAD

**Issue by Deboralopes2019** [frontendbr/vagas#1336]
Desenvolvedor Backend pleno e sênior com experiência em RUBY / RAILS,GIT / GITFLOW,REST,CLOUD
TDD / RESPEC,DEPLOY

CVs enviar para debora.lopes@drltalents.com.br

contratação pj mais benefícios

**Comment by rafaelblink** [comment]
Acho melhor postar aqui.

https://github.com/backend-br/vagas/issues

**Comment by eduardojmatos** [comment]
Esse repositório é somente para vagas front-end
