### ISSUE TITLE
[São Paulo - Capital] Desenvolvedor Front End Pleno na Attiva

### ISSUE THREAD

**Issue by helenmatos** [frontendbr/vagas#1338]
## Descrição da vaga
Desenvolvimento de um projeto novo, para cliente de grande porte. Após a conclusão do projeto os profissionais atuaram na manutenção deste e também em Desenvolvimento de novos projetos para outros clientes

## Local

Escritório, São Paulo - Vila Olímpia

Benefícios
- 13°
- Férias de 30 dias remuneradas
- VR e VT.

## Requisitos

**Obrigatórios:**
Experiência de 3 a 4 anos com desenvolvimento;
Node JS; React JS; Javascript ES6 / TypeScript;

**Desejáveis:**
ASP.NET MVC; jQuery; SQL Server; MongoDB; Git;

## Contratação

PJ a combinar

## Nossa empresa
Acaba de ser reconhecida também como uma das Melhores Empresas para se Trabalhar em São Paulo

## Como se candidatar

Enviar CV para Helen.matos@5aattiva.com.br
Acredito ter uma oportunidade que esteja dentro dos seus objetivos profissionais.

## Labels

- Alocado
- Pleno
- Sênior

**Comment by diogomoretti** [comment]
Olá @helenmatos o candidato vai trabalhar na própria 5A ou nos clientes de vocês?

**Comment by mtmr0x** [comment]
Fechando essa vaga por conta de inatividade da pessoa autora da postagem
