### ISSUE TITLE
[São Paulo] Front e/ou Back no Celebryt's

### ISSUE THREAD

**Issue by stavarengo** [frontendbr/vagas#134]
## Descrição da vaga

Estamos em busca de desenvolvedores FODAS para trabalhar em nossa Startup. Não importa a formação, o que importa é o talento e a vontade de fazer parte de um time para desenvolver uma plataforma super inovadora para o mercado. Estamos desenvolvendo uma plataforma completa para agências e grandes anunciantes encontrarem e contratarem influenciadores. Hoje, entre os nossos leads, estão as principais agências do Brasil, além de termos saído em grandes veículos da área, como meio&mensagem, mundo do marketing, globo news, etc.

Estamos crescendo e acabamos de levantar uma rodada de investimento para montar um time muito foda de tecnologia.

Veja mais sobre a startup: www.celebryts.com
## Local

Rua Maria Carolina, 495 - Jardim Paulistano - SP
## Benefícios
- Almoço na casa/office! Tem dias com churrasco, hamburger... além das comidas maravilhosas do nosso Chef
- Linux, PC ou MAC, é só escolher ;)
- Café da tarde todos os dias
- Em alguns casos, você pode entrar no modelo de stock option da empresa
- A nossa casa/office, é da hora!
## Requisitos

Temos vagas para trabalhar `front`, no `back` NodeJS e para nossa `API RESTful` feito em PHP + ZF2. Abaixo segue os requisitos.

**Obrigatórios:**
- Para vaga front:
  - 6 meses de experiência com ReactJS
- Para vaga back feito em NodeJS:
  - 6 meses de experiência com ReactJS
  - 6 meses de experiência com NodeJS e Redux.
- Para vaga em nossa API RESTful:
  - 1 ano de experiência com ZF2

**Diferenciais:**
- Que já tenha feito projetos bacanas, queremos ver portfólio, projetos...
## Contratação

CLT ou PJ (você escolhe)
## Nossa empresa

O Celebryt's é uma plataforma que ajuda as empresas/agências a encontrar influenciadores (Youtubers, instagrammers, snaps...) para suas campanhas de marketing. Tudo é "self service", o cliente faz as buscas, os planos e a contratação. Utilizamos tecnologia de IA para conseguir encontrar os melhores influenciadores, entregando relatórios muito mais completos do que as redes socais onde os influenciadores atuam.
## Como se candidatar

Por favor envie um email para rafael@celebryts.com com seu CV anexado - enviar no assunto: `Vaga front-end`, `Vaga NodeJS back-end` ou `Vaga PHP` (dependendo do seu foco)

**Comment by ygorlazaro** [comment]
Pena ser alocado, mas vou dar uma divulgada 😄

**Comment by stavarengo** [comment]
@ygorlazaro de onde vc é? Vamos bater um papo.
Me manda um email com seu skype.

**Comment by stavarengo** [comment]
@LFeh adiciona a tag para remoto tbm por favor :)

**Comment by LFeh** [comment]
Muito bom @stavarengo :)

**Comment by ygorlazaro** [comment]
Legal @stavarengo ! Eu sou do RJ, meu skype é ygorlazaro mesmo 👍

**Comment by paulo101977** [comment]
Mandei curriculum para o e-mail informado, porém sem resposta ainda :(

**Comment by stavarengo** [comment]
Oi @paulo101977. Eu vi seu email. Você se candidatou ao front-end. Analisando o seu currículo não encontrei nenhuma experiência com as tecnologias que pedimos para front, por isso não dei continuidade na conversa.
Será que interpretei as informações do seu linkedin? Você tem experiencia com React?
