### ISSUE TITLE
[São Paulo] Front-End Developer na Foco em você

### ISSUE THREAD

**Issue by kvilela** [frontendbr/vagas#1340]
## Descrição da vaga

Se você:
- É comprometido com entregas de qualidade e melhores práticas;
- Pensa responsivamente e é bem afiado, disposto a evoluir a cada pull request;
- Tem espírito de dono e é proativo, gosta de inovar e não tem medo de desafios;
- Gosta de viver a cultura ágil de uma startup e pensa fora da caixa;
   Então, seu lugar é com a gente!

## Local
Escritório, São Paulo - Itaim Bibi

## Benefícios
•	Remuneração compatível com o mercado;
•	Plano de saúde;
•	Vale-refeição;
•	Vale-transporte;
•	Vale-alimentação ou vale-combustível;
•	Ambiente de trabalho divertido (mas muito sério), onde aprendemos o tempo todo

## Requisitos
**Obrigatórios:**
Experiência prévia / conhecimentos em:
•	Javascript/HTML/CSS;
•	Experiência com Angular ou React;

**Desejáveis:**
•	GIT;
•	Pré-processador de CSS (SASS, LESS, STYLUS);
•	Ferramenta de Build (WEBPACK, NPM);
•	Mobile First;
•	UX
•	React-Native

## Contratação
CLT a combinar

## Nossa empresa
Nosso cliente tem uma solução completa de processamento de meios de pagamento 100% SaaS. Com a missão de tornar-se a principal infraestrutura de tecnologia em meios de pagamento no mundo. Para isso, contamos com um time bem diversificado e cheio de experts que vão adorar receber suas ideias.

## Como se candidatar

Por favor envie um e-mail para contato@focoemvoce.com.br com seu CV anexado - enviar no assunto: Vaga Front-End Developer (github/frontendbr)

## Labels
- Alocado
- CLT
- Junior
- Pleno
- Sênior

**Comment by kvilela** [comment]
Pessoal, ainda estamos recebendo CV/ Indicações/ Linkedin ... 
Startup para quem gosta de desafios!

**Comment by kvilela** [comment]
Pessoal, abriu uma vaga Jr/Pleno.

**Comment by RobertaMelo** [comment]
@kvilela Apenas presencial?

**Comment by kvilela** [comment]
@RobertaMelo Oi, boa tarde! Somente presencial.
