### ISSUE TITLE
[São Paulo] Front-end Developer C# Pleno at Wtime

### ISSUE THREAD

**Issue by AnieliFernanda** [frontendbr/vagas#1344]
Wtime contrata para atuar em cliente: 

 > # Desenvolvedor C# .NET 

Conhecimentos em Front-end e backend;
•	CSS e Javascript. HTML5;
•	JS;
•	CSS3;
•	VUE.js;
•	Sass;
Banco de dados: SQL Server.

 ## Local de trabalho:

Alphaville/SP ou Jundiai/SP 
Atuará home office e dois dias por semana alocado na nossa fabrica de software.
 
 ## Modalidade de contratação:

PJ 

## Projeto Indeterminado 

**Interessados enviar currículo com pretensão salarial para anieli.fernanda@wtime.com.br**

**Comment by mtmr0x** [comment]
@AnieliFernanda ao criar uma issue, ela tem um padrão a ser seguido, onde essas regras sobre o padrão se encontra na primeira página desse repositório. Estou fechando essa vaga para que ela possa se adequar e depois reabrimos
