### ISSUE TITLE
[Belo Horizonte/MG] Front-End Developer na Aduana Web 

### ISSUE THREAD

**Issue by avssouza** [frontendbr/vagas#1345]
![logo-capa](https://user-images.githubusercontent.com/38570320/39070705-bdcf2e92-44ba-11e8-9ba5-66e4018f4144.png)

## Descrição da vaga

Desenvolvimento Frontend da Plataforma Aduana Web, com ênfase na utilização do framework Angular 5 do Google. 

**Início imediato.**

## Como se candidatar

Favor cadastrar currículo através de < https://app.vulpi.com.br/aduana-web-s-a-/875 >

## Local

Remoto ou Escritório, Bairro Santa Efigênia - Belo Horizonte

## Benefícios

- VR e VT
- Regime de contratação CLT ou PJ
- 8h diárias flexíveis
- Possibilidade de trabalho remoto (após a estabilização no cargo)

## Requisitos

**Obrigatórios:**
- Formação Acadêmica: graduando/graduado em algum curso na área de ciências da computação.
- Ter no mínimo 1 ano de experiência com desenvolvimento Javascript, necessário que já tenha atuado com o Framework Angular.

**Desejáveis:**
- Formação Acadêmica: Graduação em Ciências da Computação, Sistemas de informação ou Matemática Computacional
- Ter 1 ou 2 anos de experiência com desenvolvimento no framework Angular do Google.
- Conhecimentos em Scaffold.

**Diferenciais:**
- Pessoa focada, rápida no desenvolvimento, afim de aprender e desenvolver novas estratégias de organização do tempo.

## Contratação

- CLT ou PJ

## Labels

- Alocado
- Remoto - Total
- CLT
- PJ
- Júnior
- Pleno

**Comment by Pedro-Souza** [comment]
@avssouza a graduação é indispensável ?

**Comment by avssouza** [comment]
> @avssouza a graduação é indispensável ?

Conforme consta na descrição da vaga, no mínimo em graduação.

**Comment by dbomfim** [comment]
@Pedro-Souza, no Brasil tem essa coisa com graduação... como se front-end se aprendesse na universidade. Procura vagas na Europa que é muito mais tranquilo e pagam 3x mais.

**Comment by gutocosta** [comment]
Enviado!

**Comment by Kateleandra** [comment]
Vaga esta em aberto ainda? me candidatei.
