### ISSUE TITLE
[REMOTO] Front-End Developer na VoceAzul.com

### ISSUE THREAD

**Issue by tuliovargas** [frontendbr/vagas#1348]
## Descrição da vaga
Buscamos desenvolvedor front-end com experiência em VueJs.

## Local
Remoto

## Requisitos

**Obrigatórios:**
- 1 ano de experiência com Vue

**Desejáveis:**
- conhecimentos em Laravel

## Contratação
PJ a combinar

## Nossa empresa
Somos uma Fintech

## Como se candidatar
Por favor envie um email para contato@voceazul.com.br com seu CV anexado - enviar no assunto: Vaga VUEjs - [Seu_Nome]

## Labels
- Freela
- PJ
- Pleno
- Sênior
- Remoto - Total

**Comment by DanielLCintra** [comment]
Cv enviado!

**Comment by rsornellas** [comment]
Ainda aceitando?

**Comment by caiocutrim** [comment]
Cv enviado <3


*Caio Cutrim - Fullstack DeveloperPhones: +55 (98) 98750-9155, +55 (98)
3225-0786*

*“The mind that opens up to a new idea never returns to its original size.”
– Albert Einstein*



Em sex, 14 de set de 2018 às 23:34, Raphael Ornellas <
notifications@github.com> escreveu:

**Comment by JeanPaulll** [comment]
Ainda aceitando ?

**Comment by LFeh** [comment]
A vaga está aberta?
