### ISSUE TITLE
[Freela / Remoto] Front-End Developer no WebQuarto

### ISSUE THREAD

**Issue by dyegonery** [frontendbr/vagas#1349]
## Descrição da vaga

Precisamos de alguém para customizar e escrever todo o css para a Central de Ajuda do WebQuarto. Criamos a central de ajuda com o HelpScout (helpscout.com), e agora precisamos de alguém que possa tornar personalizar todo a estilização da Central de Ajuda de acordo com a nova interface do WebQuarto (https://www.webquarto.com.br). Já temos praticamente todos os artigos da Central de Ajuda prontos, então a vaga é para trabalhar apenas na estilização da plataforma mesmo.

## Local

100% Remoto

## Requisitos

**Desejáveis:**
- Experiência em desenvolvimento de interfaces
- Experiência em CSS 3

## Contratação

PJ a combinar

## Nossa empresa

O WebQuarto é um dos maiores sites brasileiros que trabalha ajudando estudantes e jovens profissionais a encontrar moradias compartilhadas em todo o Brasil. Com o WebQuarto, você pode encontrar roommates buscando moradias compartilhadas, e também diversos anúncios de quartos para alugar, repúblicas de estudantes, apartamentos divididos, etc.

## Como se candidatar

Por favor, envie um email para dyego@3nw.com.br com seu portfolio e o seguinte assunto: FrontEnd Developer WebQuarto

## Labels

- Freela
- Júnior
- PJ
- Remoto - Total
- Sênior

**Comment by ribeiroevandro** [comment]
Enviado.

**Comment by carolvasc** [comment]
Aplicado

**Comment by victorvinci** [comment]
Enviado!

**Comment by mvrudi** [comment]
Enviado!
