### ISSUE TITLE
[São Paulo] Desenvolvedor Frontend (Jr/Pleno) na Printi

### ISSUE THREAD

**Issue by rubenmarcus** [frontendbr/vagas#135]
## Descrição da vaga

Principais atividades:
- Desenvolver e otimizar as interfaces de um projeto web
- Desenvolver novas funcionalidades, seguindo boas práticas de desenvolvimento
- Manutenção e refatoração de código já existente
## Local

 Av. Cardeal Santiago Luís Copello, 201, Vila Ribeiro de Barros - São Paulo, SP
próximo à estação Imperatriz Leopoldina (CPTM).
## Benefícios
-  Vale-transporte
-  Restaurante no local e sem custo
-  Assistência médica
- Inglês
-  Convênios com parceiros em diversas áreas de atuação
-  Fruta do dia
## Requisitos

**Obrigatórios:**
- HTML
- CSS
- JavaScript
- Desenvolvimento de Single Page Applications
- Responsive Design
- Conhecer algum framework JavaScript
- Workflow moderno e automação de processos, utilizando tecnologias como Gulp ou Grunt
- Utilizar algum software de edição de imagens (recortes, cores, fontes)
- Desenvolver código limpo e bem documentado
- Seguir padrões da WEB
- Mensurar/melhorar performance no client-side
- Utilização de técnicas de SEO
- Disciplina e comprometimento para trabalho com metodologias ágeis em uma equipe distribuída
- Paixão por tecnologia em geral
- Comprometimento, organização, ética, foco e trabalho em equipe

**Desejáveis:**
- AngularJS

**Diferenciais:**
- Conhecimentos básicos de PHP (não obrigatório)
## Contratação

CLT
## Nossa empresa

A Printi é um modelo inovador de gráfica online no mercado brasileiro, com impressões de alta qualidade a preços acessíveis. Utilizamos as mais modernas ferramentas do setor de Web2Print para simplificar e agilizar o complexo processo de encomenda de impressos personalizados.
Fundada a partir de conceitos adquiridos em 25 anos de experiência na indústria gráfica brasileira, a Printi oferece mais de 6.000 combinações diferentes de produtos impressos. Todas essas combinações são acessíveis através de nossa revolucionária matriz de customização, que dá ao usuário o total controle de seu produto, e calcula, em tempo real, o custo final do orçamento. É essa funcionalidade que traz completa transparência ao processo de compra e que separa a Printi de seus concorrentes no mercado gráfico.

https://www.printi.com.br
## Como se candidatar

Encaminhar e-mail com curriculo e portfólio  para recrutamento@printi.com.br, contendo no assunto do e-mail o 'Vaga Desenvolvedor Frontend'.

**Comment by NicholasPedroso** [comment]
@rubenmarcus tenho a impressão de que emails como "vagas@, recrutamento@, rh@, cv@ ..." nunca são lidos hehehehehe

Porém, **email enviado** ✋👊

**Comment by danguilherme** [comment]
@NicholasPedroso "tenho a impressão" foi um trocadilho pela empresa ser uma gráfica? 😆

**Comment by rubenmarcus** [comment]
@NicholasPedroso , Sim o pessoal olha sim, vou dar um toque aqui, valeu o contato e boa sorte!

**Comment by NicholasPedroso** [comment]
@danguilherme impressao sua =D

@rubenmarcus Beleza, Obrigado cara 🙌

**Comment by lucasalmeida92** [comment]
Enviado ;]

**Comment by rubenmarcus** [comment]
@lucasalmeida92  a vaga é presencial, você é de  SP ou está?

**Comment by lucasalmeida92** [comment]
@rubenmarcus Sou de Fortaleza e moro aqui. Mas não tenho problema em me mudar pra SP. 
Abraço!

**Comment by Rivail** [comment]
Tenho interesse, sou de SP.
