### ISSUE TITLE
[Remoto] Front-end Developer na D3.do

### ISSUE THREAD

**Issue by diogomoretti** [frontendbr/vagas#1350]
Nós estamos buscando um(a) **Front-end Developer Júnior** que combine Design + Programação. Nós acreditamos no auto-gerenciamento, na mentalidade empreendedora e paixão para desenvolver **produtos digitais incríveis** =]

## O que esperamos de você?
* Curioso pelo universo digital
* Pró-ativo
* Alguém que se compromete com qualidade e com prazos
* Alguém que gosta de trabalhar em equipe
* Alguém que gosta do que faz
* Alguém bacana :)

## Requisitos
* Experiência com Front-end
* Entendimento básico de todo processo web (design, desenvolvimento e deploy)
* Git / Git Flow
* HTML / CSS
* JavaScript
* Frameworks/Libs JS (React / Vuejs / Angular)

## Local
Remoto

## Benefícios
* Plano de Saúde Bradesco
* Auxílio Academia
* Horário Flexível

## Sobre a D3
A D3 está há 16 anos no mercado contruindo produtos digitais para grandes empresas como Twitter, Fiat e Google. Acreditamos que tecnologia e design podem criar produtos digitais de uma forma incrível ;)

## Contratação
CLT ou PJ

## Como se candidatar
Topa o desafio? https://vem.d3.do

**Comment by ribeiroevandro** [comment]
Aplicado

**Comment by maxarouca** [comment]
Aplicado também!

**Comment by andrebrandaoo** [comment]
Aplicado

**Comment by Roger-Melo** [comment]
Apliquei! :smiley:

**Comment by AlexandreRStos** [comment]
[Aplicado](https://alexandre.cf)

**Comment by danielswater** [comment]
Aplicado

**Comment by gugutz** [comment]
Aplicado

**Comment by adeonir** [comment]
Aplicado

**Comment by laugustofrontend** [comment]
Aplicado

**Comment by glauberfc** [comment]
Essa vaga ainda está aberta?
