### ISSUE TITLE
São Paulo Front-End Engineer na INNO GROUP

### ISSUE THREAD

**Issue by gcaraciolo** [frontendbr/vagas#1351]
## Desenvolvedor Front-End

A Inno Group está a procura de um desenvolvedor front-end, que seja apaixonado por construir aplicações web. Você vai trabalhar com produtos no ramo de seguros com rápido crescimento de usuários.

### O que você vai fazer

- Desenvolvimento de aplicações web usando Angular
- Trabalhar em projetos da concepção à produção, trabalhando próximo ao time de negócios
- Colaborar com outros desenvolvedores e designers para construir e melhorar serviços com foco na necessidade dos clientes

### O que estamos procurando

- Alguém que assuma os problemas do começo ao fim e esteja disposto a aprender o que for preciso para realizar o trabalho
- Uma pessoa detalhista mas que saiba quando é necessário cortar caminhos para entregar no prazo
- Independente, dedicado e capaz de entregar código pronto para produção com o mínimo de orientação.
- Excelente capacidade de comunicação e abertura para dar e receber feedback

### Seria bom ter

- Graduação em ciências da computação ou áreas relacionadas
- Experiência em escrever testes
- Ter trabalhado com metodologias SCRUM ou XP
- Ter trabalhado com projetos SaaS

 
### Sobre o INNO Group
 
Nós nascemos da união de jovens empreendedores com sonho grande, associados com um forte grupo econômico de mais de 40 anos de experiência. Em apenas 7 meses de vida, emitimos mais de 1500 apólices de seguro e ganhamos um prêmio de inovação da Revista Apólice, um dos prêmio mais relevantes do mercado de seguros nacional.

Se você que fazer parte dessa equipe e ajudar a construir o futuro de uma startup, mande um e-mail para code@innogroup.com.br com LinkedIn/Currículo nos contando um pouco sobre sua jornada como desenvolvedor.

----------------------------------------------------------------------

INNO is seeking a Front End Engineer that is passionate about building desktop web applications. You’ll working with Insurance related products with constant growing in users and features.

### What you will do
- Build solutions using Angular
- Drive a project from concept to production, working closely with business people
- Collaborate with other developers to build and improve customer facing features
 

### What we are looking for

- Own problems end-to-end, and are willing to pick up whatever knowledge you're missing to get the job done
- Are detail oriented, and like to get the system working but know when to cut corners versus get it exactly right
- Independent, dedicated, and able to deliver production ready code with minimal guidance
- Have communications skills and open to giving and receiving feedback
 

### Nice to have

- Graduated in computer science or related areas
- Experience with writing tests
- Did work with XP or Scrum methodologies
- Did work in SaaS projects
 

### About INNO Group
We’ve born from the union of young entrepreneurs with big dreams associated with an economic group with more than 40 years of activity.
With only 7 months, we have emitted more than 1.5 thousand insurance policies and we also won an award from the Apólice magazine, one of the biggest awards in the insurance market.

If you’re want to help construct a startup from the beginning come and join us.
Send an email to code@innogroup.com.br with your LinkedIn/curriculum. Please, write a description about your career.

### Labels
CLT
PJ
Júnior
Pleno
Alocado
Remoto - Total
Remoto - Parcial

**Comment by mtmr0x** [comment]
@gcaraciolo poderia conferir sua postagem com o modelo de postagem de vagas que está aqui: https://github.com/frontendbr/vagas/blob/master/.github/issue_template.md, por favor? O que mais precisamos são as labels (última parte) para adicionar as labels aqui e ajudar os candidatos a filtrarem

**Comment by gcaraciolo** [comment]
@mtmr0x obrigado por lembrar! coloquei as labels.

**Comment by danielswater** [comment]
Enviado

**Comment by pedrocss** [comment]
enviado!
