### ISSUE TITLE
[São Paulo] Front-End Developer na Ciclic

### ISSUE THREAD

**Issue by le17i** [frontendbr/vagas#1353]
## Descrição da vaga

Buscamos pessoas que queiram fazer parte do nosso time, que sejam apaixonados por construir interfaces e tenham genuína preocupação com nossos usuários!

Não esperamos um expert nesta área, mas fazemos questão de pessoas mão na massa e que gostem de desafios!

## Local

Escritório, São Paulo - Vila Olímpia

## Benefícios

- Vale Alimentação
- Vale Refeição
- Plano de Saúde
- Plano Odontológico
- Previdência Privada
- Bônus
- Gympass

#### Diferenciais

- Horário flexível
- Home office 1 vez por semana
- Day Off de aniversário

## Requisitos

**Obrigatórios:**
- Conhecimento em HTML, CSS e JavaScript

**Desejáveis:**
- Conhecer HTTP, HTTP/2 e APIs Rest
- Trabalhar com metodologias ágeis
- Criação de código limpo, legível, cross-browser e cross-device
- Saber utilizar Git
- Entender como o Browser funciona

## Contratação

CLT a combinar

## A Ciclic

A [Ciclic](https://www.ciclic.com.br/) é uma plataforma financeira 100% digital que tem como objetivo ajudar você a realizar seus sonhos a partir de um plano de investimento. Nosso principal produto é o plano de previdência VGBL, com diferenciais vantajosos no mercado.

Acreditamos que com pequenas mudanças de hábitos e uma fonte confiável de informações (nós!) nossos clientes estarão cada vez mais próximo do seu sonho.

## Como se candidatar

Por favor envie um [email para vagasfront+ghjr@ciclic.com.br com seu CV anexado - enviar no assunto: Vaga FrontEnd Developer Júnior](mailto:vagasfront+ghjr@ciclic.com.br?subject=FrontEnd%20Developer%20J%C3%BAnior) ou candidatar-se pelo [LinkedIn](https://www.linkedin.com/jobs/view/desenvolvedor-a-de-front-end-j%C3%BAnior-at-ciclic-850154319/)

## Labels

- Alocado
- CLT
- Júnior
- Remoto - Parcial

**Comment by adeonir** [comment]
@le17i Alguma possibilidade de remoto total?

**Comment by le17i** [comment]
@adeonir Não. No momento apenas presencial :)

**Comment by le17i** [comment]
Estamos procurando ainda pessoal :)

**Comment by DavidMeloJunior** [comment]
Enviei e-mail! Valeu!

**Comment by le17i** [comment]
Galera, fechamos a vaga com um candidato vindo daqui :rocket: :rocket: :rocket:

**Comment by le17i** [comment]
Galera, fechamos a vaga com um candidato vindo daqui :rocket: :rocket: :rocket:
