### ISSUE TITLE
[REMOTO] Front End Developer Junior no Catarse

### ISSUE THREAD

**Issue by thiagocatarse** [frontendbr/vagas#1355]
## Descrição da vaga

Estamos à procura de um(a) desenvolvedor(a) front-end motivado(a) em combinar a arte do design com a arte da programação. Você será responsável por construir a interface e a experiência dos usuários do Catarse. Você trabalhará no time de Produto do Catarse, formado hoje por 1 Designer, 3 Desenvolvedores Full-stack e 1 Desenvolvedor Front-end, e estará focado(a) na construção de todo client-side logic. 

No momento estamos passando por um grande projeto de renovação tecnológica e você terá, desde o início a oportunidade de participar desse projeto. No front-end, estamos migrando nosso SPA para Elm. Se você já conhece a linguagem, esse conhecimento será super bem-vindo. Se não conhece, tudo bem: o aprendizado vai fazer parte do seu onboarding no nosso time.
 
[Saiba mais sobre o Catarse aqui ;)](https://crowdfunding.catarse.me/quem-somos)

## Local

Remoto

## Benefícios

- Somos 100% remotos, portanto, seu local de trabalho é onde você decidir e você terá flexibilidade para definir horários.

#### Diferenciais

- Trabalho remoto total
- Flexibilidade de horário

## Requisitos

**Desejáveis:**
- Forte compreensão do JavaScript, suas peculiaridades e soluções alternativas
- Compreensão de web markup, incluindo HTML5 e CSS3
- Alguma experiência na construção de Single-Page Applications
- Compreensão dos problemas de compatibilidade entre navegadores e formas de contornar esses problemas
- Familiaridade com ferramentas contemporâneas de construção de front-end, como webpack
- Familiaridade com ferramentas de controle de versão de código, como Git
- Bom entendimento do comportamento e desempenho da renderização do navegador
- Inglês intermediário (leitura e escrita)
- Experiência com microsserviços.

## Contratação

PJ. Salário entre R$2.000 e R$2.200 (Part time)

## Nossa empresa

Somos a maior plataforma de financiamento coletivo do Brasil. Mais de 500.000 pessoas já apoiaram ao menos um projeto no Catarse, contribuindo juntas com mais de R$86 milhões para milhares de projetos. Desde nossa fundação, em 2011, seguimos independentes, sem investidores, com uma cultura de trabalho remoto forte e com uma estratégia de desenvolvimento de produto no centro de nosso negócio. Ao se juntar ao barquinho do Catarse, você irá construir conosco uma nova maneira de tirar projetos do papel e dar força a um movimento que permite que mais pessoas viabilizem suas ideias no Brasil ;)

## Como se candidatar

Por favor, [acesse essa página](https://catarse.freshteam.com/jobs/Z3RP4JMmaaqI/front-end-developer-junior) e envie sua aplicação por lá!

## Labels

- Júnior
- PJ
- Remoto - Total

**Comment by neriGabriel** [comment]
Aplicado !

**Comment by Roger-Melo** [comment]
Apliquei! 🎉

**Comment by thalesf** [comment]
Aplicado!

**Comment by Pedro-Souza** [comment]
Apenas PJ?

**Comment by thiagocatarse** [comment]
Isso mesmo @Pedro-Souza . Apenas PJ!

**Comment by izamglima** [comment]
Apliquei :)

**Comment by ribeiroevandro** [comment]
Essa vaga ainda está aberta?

**Comment by heliomsolivas** [comment]
enviado! 👍

**Comment by adeonir** [comment]
Olá @thiagocatarse, também apliquei mas ainda não recebi retorno.
