### ISSUE TITLE
[Belo Horizonte] Desenvolvedor Web Full Stack na Rede Odonto

### ISSUE THREAD

**Issue by megandavulpi** [frontendbr/vagas#1358]
**Sobre a empresa: Rede Odonto**

A Rede Odonto Empresas é responsável pelo atendimento aos beneficiários de planos odontológicos, comercializados com diferentes marcas de clientes e parceiros. 
É administrada pela diretoria de Odontologia da Caixa Seguradora.
São mais de 20 anos de experiência, com profissionais qualificados para cuidar da saúde bucal dos beneficiários pela Rede Odonto Empresas.
Além do mercado Odontológico, a Rede Odonto integra um grupo de empresas com atuação em diversas áreas além da saúde como, financeira, mídia gráfica e outras.

**Ocupações do cargo**

Idealizar, desenvolver, sustentar e evoluir aplicações em sua totalidade levando em consideração as dependências tecnológicas e a experiencia do usuário.
Atuará em todas as camadas da pilha.
Contribuir nos projetos e propor as melhores práticas em desenvolvimento.
Desenvolver e testar aplicações Web em NodeJS.

**Benefícios**

Ticket Refeição
Vale Transporte
Aptidões e qualidades

**Aptidão para liderança**

Trabalhar em equipe
Organização
Auto-gestão

**Conhecimentos Essenciais**

Experiência em Javascript / Node
Experiência em Controle de Versionamento (Git)
Experiência com banco de dados MongoDB e Firebase
Experiência com React, HTML e CSS
Experiência em ExpressJS
Experiência em AWS (Amazon Web Services)
Métodos de desenvolvimento ágeis
Inglês em nível intermediário.
Organização, excelente comunicação e relacionamento interpessoal.  
Sistema Operacional Linux.

**Informações complementares**

Essa vaga é especialmente para quem está em busca de um desafio, o profissional será responsável pelo projeto JobDo, que consiste em um gestor de tarefas, fluxos e projetos. A ideia é que a equipe cresça a partir dele e ele lidere e coordene o projeto.

**Nível de experiência:**

Sênior

Link para cadastrar na vaga: http://bit.ly/2oHtPrN

**Comment by diogomoretti** [comment]
A descrição está fora do nosso [padrão de template](https://github.com/frontendbr/vagas/blob/master/.github/issue_template.md).

Por esse motivo estaremos fechando a issue, conforme [nossas regras](https://github.com/frontendbr/vagas#importante). Assim que ajustado, reabriremos!
