### ISSUE TITLE
[São Paulo] Desenvolvedor Fullstack Node ou Ruby - 5 era

### ISSUE THREAD

**Issue by highlabs** [frontendbr/vagas#136]
## Descrição da vaga

Precisamos de Desenvolvedor Fullstack Node.js que tenha experiência em criação de API e integração com API de terceiros.
Você irá trabalhar criando aplicações device agnostic e nos ajudando a migrar nosso stack antigo para uma nova plataforma. (Para o futuro e avante! o/)

## Local

Alocado - R. Estela, 96, Vila Mariana - São Paulo, SP

## Benefícios

- Vale-transporte
- Vale-refeição
- Horário flexível
- Muito café (temos maquina de espresso! \o/)
- Sexta-feira saímos mais cedo. :)

## Requisitos

**Obrigatórios:**

- Experiência com Node
- Experiência em MongoDB
- Linux (SSH, criar maquinas no AWS/Digital Ocean, etc)
- Git
- Javascript ES6

**Desejáveis:**
- Hapi, Express, Sails ou KeystoneJS
- MySQL / Postgress
- VueJs

**Diferenciais:**
- Noções de Python/Java

## Contratação

R$ 3000 ~ R$ 3500 PJ

## Nossa empresa

[5era](http://5era.com)
Estamos interrompendo a sua navegação para transportá-lo para um novo universo!

## Como se candidatar

Por favor envie um email para developer@5era.com - com link/CV em anexo.
Enviar no assunto: [Vaga Node -  seuNome]

**Comment by highlabs** [comment]
Selos: Alocado / PJ / Junior / Pleno

**Comment by LFeh** [comment]
@highlabs Só uma dica, não esquece de colocar a [Cidade] no título, para tuitar certo :p 

https://twitter.com/frontendbrvagas/status/782954226292887552

**Comment by highlabs** [comment]
Conseguimos contratar! :) Valeu! :D

**Comment by camilatigre** [comment]
@highlabs 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
