### ISSUE TITLE
[Remoto] Front-End Developer no Enjoei

### ISSUE THREAD

**Issue by mssantos** [frontendbr/vagas#1360]
## Descrição da vaga

- Desenvolver novas funcionalidades para o nosso site;
- Aprimorar nossas ferramentas internas;
- Corrigir bugs.

## Local

Remoto! O escritório da empresa fica em SP, mas o time de engenharia é totalmente remoto.

## Benefícios

- Plano de saúde;
- Vale-alimentação/refeição - você escolhe!;
- Auxílio para internet.

## Requisitos

**Obrigatórios:**

- Domínio de HTML, CSS e pré-processadores CSS (usamos SASS);
- Domínio de JavaScript / jQuery (temos código legado que usa CoffeeScript e jQuery, mas para novos projetos usamos ES6+);
- Capacidade de construir bons layouts a partir do Sketch / PSD;
- Git / Github;

**Desejáveis:**

- Experiência em desenvolver aplicações consumindo APIs REST;
- Experiência em grandes projetos;
- Experiência com Rails;
- Conhecimento sobre testes de software;
- Conhecimentos em performance client-side;
- Inglês técnico.

**Diferenciais:**

- Muita vontade de ensinar e aprender!
- Boa comunicação [1] - como o time de engenharia é remoto, é muito importante conseguirmos nos comunicar bem para que tenhamos o menor número de gargalos possível;
- Boa comunicação [2] - somos muito abertos para discussões sobre novas tecnologias e em como poderíamos adiciona-las em nossos projetos. Se gosta disso, vem comigo!

---

## Contratação

CLT.

#### o enjoei?

somos uma startup brasileira. arroz com feijão. 

- [nosso site!](https://www.enjoei.com.br)
- marketplace com foco em moda 
- investidores nacionais e internacionais 
- equipe distribuida em diversos estados e países 
- polos de tecnologia em boston e franca

#### e o que mais?

começamos como um blog em 2009 e viramos site em 2012. de lá pra cá a gente segue se transformando todos os dias. não sabemos se somos um site ou se somos um app, mas estamos em terapia.

já somos mais de 4 milhões de enjoados em todo o Brasil e vendemos mais de 3.5 milhões de enjoos.

#### the engenharia!

https://www.youtube.com/watch?v=YWewJ-39Ux8
https://www.youtube.com/watch?v=diNO_BOvYrw

## Como se candidatar

Envie seu currículo através desse link: https://jobs.kenoby.com/enjoei/job/desenvolvedor-front-end/5b3bc615db6d6b7e17b45711

## Labels

- Remoto - Total
- CLT
- Júnior
- Pleno 
- Sênior

**Comment by Roger-Melo** [comment]
enviei :smiley:

**Comment by rafaelangical** [comment]
Enviado !

**Comment by ngustavo** [comment]
Aceita PJ?

**Comment by mssantos** [comment]
@ngustavo infelizmente não

**Comment by gabrielferreiraa** [comment]
Aplicado :)

**Comment by mvrudi** [comment]
Enviado!

**Comment by lzhudson** [comment]
Enviado

**Comment by ribeiroevandro** [comment]
Enviado

**Comment by kvnol** [comment]
enviado

**Comment by mart2222** [comment]
Enviei o projeto e não recebi o retorno se receberam, gostaria que entrassem em contato pelo email djeison.zanette@gmail.com e me encaminhassem um email para onde eu possa enviar o projeto.

**Comment by Roger-Melo** [comment]
Digo o mesmo. Enviei o teste e não houve feedback ou mesmo uma confirmação de recebimento.

**Comment by theus** [comment]
Qual teste? Pelo link só vi para enviar o currículo.

**Comment by MatheusMCuba** [comment]
Entraram em contato, pediram para realizar um teste em 36 horas, e depois que eu entreguei o teste (em prazo), não tive mais retorno

**Comment by lzhudson** [comment]
@mssantos, e quem não recebeu a resposta mesmo enviando o CV?

**Comment by vncscoelho** [comment]
@mssantos entrei na sala da entrevista no horário combinado e ninguém apareceu, tem algum contato direto que eu possa fazer?

**Comment by mssantos** [comment]
Pessoal, vou fechar o anúncio. O time está analisando os testes enviados (foram **muitos**) e todos vão receber o feedback ao longo dos próximos dias.

Valeu!

**Comment by adeonir** [comment]
@mssantos ainda dá tempo de enviar o teste?

**Comment by gabrielferreiraa** [comment]
Mandei o teste a mais de 25 dias e não obtive nenhum feedback.

**Comment by pachecovit** [comment]
> Mandei o teste a mais de 25 dias e não obtive nenhum feedback.

Eu também enviei e nem um 'ok, recebido' obtive. Engraçado que isso acontece com 99,9% das vagas que postam aqui. Enviei para outras também e nenhum retorno. Triste.
