### ISSUE TITLE
[Viana - Espírito Santo] [Estágio/Júnior] Front-end e Suporte na Máximus Soluções

### ISSUE THREAD

**Issue by rzorzal** [frontendbr/vagas#1367]
## Descrição da vaga

O profissional atuará principalmente com Suporte ao usuário tanto por telefone/Whatsapp/e-mail quanto in loco (indo até o cliente). O projeto está crescendo no mercado capixaba e agora chegou a hora de aumentar a equipe pois estamos em um momento de crescimento da empresa. Qualquer dúvida pode nós procurar através do e-mail citado nesta vaga.

## Local

Canaã, Viana, Espírito Santo (NÃO ACEITAMOS REMOTO POR ENQUANTO)

## Requisitos

**Obrigatórios:**
- Gostar de estudar
- Curtir atendimento e programação

**Desejáveis:**
- HTML
- CSS
- JS

**Diferenciais:**
- projetos opensource
- ter veículo (não é necessário, mas se tiver será melhor)

## Contratação

PJ a combinar

## Nossa empresa

A Máximus Soluções é uma empresa nova, e é a primeiro do seu ramo no mercado capixaba, sendo assim, por sermos pioneiros, estamos no meio de um processo de crescimento. Estamos iniciando o processo de montar uma equipe de Suporte e Desenvolvimento.

## Como se candidatar

Por favor envie um email para ricardozorzaldavila@gmail.com com seu CV anexado - enviar no assunto: Vaga Suporte e Front-end

## Labels

- Alocado
- Estágio
- Júnior
- PJ

**Comment by fagnerpelicioni** [comment]
Minha cidade? Não é possível rs

**Comment by rzorzal** [comment]
Por hora vamos fechar a issue pois recebemos uma quantidade boa de inscrições. Se houver a necessidade, reabrirei. Obrigado.

**Comment by LFeh** [comment]
@rzorzal Da hora, espero que de certo!

**Comment by Artorys** [comment]
Olá,a vaga ainda está de pé?
