### ISSUE TITLE
[Florianópolis] Lead Front-End Developer na McFadyen Digital

### ISSUE THREAD

**Issue by monicaschwartz** [frontendbr/vagas#1368]
About You

Are you an innovative person who can accelerate the growth of our nationally acclaimed project? Do you have a passion for technology and a flexible, creative approach to problem solving? Are you self-directed, confident, and able to work without requiring a great deal of structure or supervision? Are you highly self-motivated and having head full of ideas? If you answered yes to these questions, we want to talk to you.

Position Summary

We are looking for creative and dependable self-motivated professionals to join our team as Lead UI Developer, helping us drive a team of awesome Front-End people.

 
Responsibilities

•      Create reusable and clean UI pattern framework that Application Developers can plug and play

•      Handle customer expectations on challenging projects

•      Adhere to code standards and ensure consistency

•      Quickly convert wireframes into HTML front-end with optimal quality

•      Team with our Application Developers to bridge the client side with server side code

•      Ensure quality assurance on front-end code including HTML, CSS, and JavaScript

•      Deliver consistency of the user interfaces across multiple platforms

•      Provide production support for all implemented changes

•      Work in a small, fast-paced, team-oriented environment

•      Liaise closely with onsite counterparts in order to continue to drive product forward

•      Help implement good UI practices

•      Provide training and leadership to UI new joiners

Qualifications

•      Proven experience in UI development and integration for web and mobile applications with  delivered projects

•      Applied experience of UI development principles

•      Have a good understanding of the three pillars of front end development which are HTML, CSS and JavaScript

•      Generate clean, semantic HTML and CSS

•      Have exceptional proficiency in writing Vanilla JavaScript (no jQuery!) from scratch, understand MVC coding model and object oriented concepts

•      Know the Responsive web and have a little bit of knowledge about current UX trends.

•      Have practical exposure on frameworks and APIs such as AngularJS, LESS, and Bootstrap

•      Ensure cross-browser and cross-device compatibility

•      Exposure on e-commerce platforms is preferred and strong experience in agile methodology is a plus

•      Experience in working with Node.js

•      Experience in mentoring other team members

ADVANCED ENGLISH SKILLS AND AVAILABILITY TO MOVE TO FLORIANOPOLIS/SC IS MANDATORY

**Comment by diogomoretti** [comment]
@monicaschwartz vamos fechar a issue até ela entrar no [nosso template](https://github.com/frontendbr/vagas/blob/master/.github/issue_template.md) conforme [nossas regras](https://github.com/frontendbr/vagas#importante)
