### ISSUE TITLE
[São Paulo] Desenvolvedor Front-end (WordPress) Pleno

### ISSUE THREAD

**Issue by alinemorelli** [frontendbr/vagas#137]
## Descrição da vaga

Estamos buscando desenvolvedores front-end com conhecimentos sólidos em HTML, CSS e na plataforma Wordpress.
Também é necessário o bom entendimento do funcionamento de um banco de dados e boas práticas de SEO. Trabalhará com a manutenção e implementação do site da empresa.
## Local

Escritório, São Paulo - Pinheiros
## Benefícios
- Vale-transporte
- Vale-refeição
- Plano de saúde
## Requisitos

**Obrigatórios:**
- HTML avançado
- CSS avançado
- PHP básico/intermediário
- Conhecimento da plataforma Wordpress 
- Conhecimento Intermediário de Photoshop
- Controle de versão (GIT)
- Crossbrowser e Mobile
- Conhecimento de estrutura banco de dados
- Inglês técnico
- SFTP/SSH
- SEO

**Desejáveis:**
- Woocommerce
- Software Filemaker Pro
- AWS

**Diferenciais:**
-  Google Analytics / Adwords
## Contratação

CLT
## Nossa empresa

Criada na cidade de São Paulo por um casal francês, Matthieu e Bénédicte, a Futon Company é líder no mercado brasileiro do futon contemporâneo e afins. O grupo Futon Company, que tem sede em São Paulo (Pinheiros), é presente em São Paulo e no Rio de Janeiro com quatro lojas e três marcas: Futon Company, Futon Company Basics e Futon Company Outlet. Conta ainda com algumas representações em outras capitais brasileiras.
https://futon-company.com.br/
## Como se candidatar

Por favor envie um email para webmaster.fco@futoncompany.com.br com seu CV/Linkedin, portfólio caso possua e pretensão salarial - enviar no assunto: Vaga Dev

**Comment by gusribeiro** [comment]
enviado! estou querendo me mudar para SP :)
