### ISSUE TITLE
[Rio de Janeiro] Front-End Developer na [Platypus Brasil]

### ISSUE THREAD

**Issue by luannavaranda** [frontendbr/vagas#1371]
**Descrição da vaga**
Projeto Takealook em Phalcon.

**Local**
Escritório, Rio de Janeiro.

**Benefícios**
Passagem
VR de R$25,00

**Requisitos Obrigatórios:**
HTML5, CSS3 e SASS

**Desejáveis**
Conhecimento em JavaScript.

**Diferenciais**
Experiência com Angular 2 e posterior.
Entender de chamadas assíncronas utilizando JSON como formato de transporte e REST.
Versionamento de código.
Experiência com frameworks de teste unitário Javascript, por exemplo, Jasmine e E2E.

**Contratação**
PJ a combinar

**Nossa empresa**
A PLATYPUSBRASIL oferece soluções de engenharia através de captação de imagens e vídeos aéreos de alta qualidade.

**Como se candidatar**
Por favor envie um email para luanna.varanda@platypusbrasil.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Developer

**Labels**
Alocado
PJ
Pleno
Remoto - Parcial

**Comment by igorpinhh** [comment]
Gostei da vaga, mas não tem nenhuma vaga pra Jr?
