### ISSUE TITLE
[MG - Belo Horizonte] Full-Stack Developer na Task Internet

### ISSUE THREAD

**Issue by megandavulpi** [frontendbr/vagas#1372]
**Sobre a empresa: Task Internet**

Com mais de 20 anos de mercado, a Task é líder em hospedagem de sites em Belo Horizonte. Conta com uma equipe altamente qualificada, focada em qualidade e atendimento diferenciado. Para nos conhecer melhor, acesse nosso site.

**Descrição:** 

**Ocupações do cargo**

Desenvolvimento e manutenção de sistemas internos, criação de sites para clientes e atualização de páginas web da empresa.

**Benefícios**

VT (o que for necessário)
VR (R$20,60/dia)
Plano de Saúde Unimed após 3 meses de contratação;

**Aptidões e qualidades**

Trabalhar em equipe
Propor ideias
Cumprir prazos
Planejar tarefas.
Conhecimento em Laravel

**Informações da empresa**

Líder em hospedagem de sites em Belo Horizonte, a Task iniciou suas operações em 1994 na área de desenvolvimento de software e comunicação de dados, passando a prestar serviços de telecomunicações e Internet em 1996.

Atualmente, nosso foco principal é voltado para hospedagem de sites, servidores e e-mails. Contamos com uma equipe qualificada e uma estrutura de alta qualidade para atender bem o cliente e garantir o bem-estar dos nossos funcionários.

**Informações complementares**

A Task possui uma equipe jovem e divertida. Procuramos profissionais com muita energia para cresce junto e vestir a camisa da empresa.

**Senioridade:**

Junior

**Acesse o link para se cadastrar: http://bit.ly/2O6c6p9**

**Comment by diogomoretti** [comment]
@megandavulpi dois pontos que estão fora das nossas regras:

- Verificar se realmente a vaga é para Front-end. Se precisar postar em outros canais que não seja de Front-end, você pode encontrar eles [aqui](https://github.com/frontendbr/vagas#outros-reposit%C3%B3rios-de-vagas)
- A descrição está fora do nosso [padrão de template](https://github.com/frontendbr/vagas/blob/master/.github/issue_template.md).

Repense esses pontos antes de postar alguma vaga aqui 😉

Por esse motivo estaremos fechando a issue, conforme [nossas regras](https://github.com/frontendbr/vagas#importante).
