### ISSUE TITLE
[São Paulo] Front End Developer na Sysmap Solutions

### ISSUE THREAD

**Issue by Molladri1** [frontendbr/vagas#1373]
SKill: Front End Developer

Estamos contratando novos talentos para atuação em nosso time de inovação e transformação digital, ambiente colaborativo com foco em novas tendências.

Importante ter Conhecimento: Angular, HTML, CSS, JavaScript, Bootstrap, Material UI. 
Conhecimento desejável: RXJs, Saga, Webpack, Babel, ESLint, FlexBox, Linux básico, Node.js, Express, ES6, Git, Git flow.
Conceitos do ambiente: Integração contínua, BDD e TDD, Micro Serviços, PWA , API, DDD, BDD, Message Broker, Arquitetura de aplicações em nuvem.

Projeto para atuação em nossa Fábrica de Software localizada na região da Av. Paulista.

Por favor envie um email para rh3@sysmap.com.br com seu CV anexado - enviar no assunto: Vaga Front End

- CLT ou PJ
- Nível Pleno

**Comment by diogomoretti** [comment]
A descrição está fora do nosso [padrão de template](https://github.com/frontendbr/vagas/blob/master/.github/issue_template.md).

Por esse motivo estaremos fechando a issue, conforme [nossas regras](https://github.com/frontendbr/vagas#importante). Assim que ajustado, reabriremos!
