### ISSUE TITLE
[MG - Belo Horizonte] Full-Stack Java Developer na Maxtrack

### ISSUE THREAD

**Issue by megandavulpi** [frontendbr/vagas#1374]
**Sobre a empresa: Maxtrack**

A Maxtrack é líder em tecnologia de rastreamento e telemetria no Brasil há mais de 18 anos. Com um portfólio diversificado e moderno, desafia os limites em busca de inovação contínua.
 
Além do segmento automotivo, a Maxtrack oferece soluções para monitoramento de carga, containers, pessoas, animais, ativos fixos e móveis, entre outras possibilidades. A tecnologia ideal para qualquer acompanhamento ou gerenciamento em tempo real.

**Descrição:
Ocupações do cargo:**

Programar, codificar e testar os projetos criados;
Metodologias ágeis de desenvolvimento como Scrum;
Análise, especificação e prototipação;

**Benefícios:**

Ambiente descontraído
Flexibilidade de horário;
Frutas e pães para lanches;
Vale-transporte ou estacionamento;*
Plano de saúde;*
Seguro de vida;
PLR de até 3 salários.
*desconto simbólico em folha.

**Aptidões e qualidades:**

Pró-atividade;
Saber trabalhar em equipe;
Auto-didata.

**Tecnologias:**

Java;
Spring
Hibernate 
WebSockets
Oauth
Maven  
HTML5
CSS3
Bootstrap
JQuery
Javascript
Angular 
SQL
JSON
Linux 

**Tecnologias desejáveis:** 

C/C++ 
Python
MongoDB
Redis

**Informações da empresa:**

Empresa com 20 anos de mercado, maior da América latina em seu segmento, pioneira em desenvolver novos produtos e plataforma de Internet das Coisas. Com frequentes lançamentos de novas tecnologias, atualmente a única em oferecer alternativas de comunicação em LoRa (tecnologia de rádio frequência que permite comunicação a longas distâncias). Empresa com grande case de sucessos com Analytics para predição de furto e roubo.

**Senioridade:** 

Pleno

**Acesse o link para se cadastrar: http://bit.ly/2NuYzdM**

**Comment by diogomoretti** [comment]
@megandavulpi dois pontos que estão fora das nossas regras:

- Verificar se realmente a vaga é para Front-end. Se precisar postar em outros canais que não seja de Front-end, você pode encontrar eles [aqui](https://github.com/frontendbr/vagas#outros-reposit%C3%B3rios-de-vagas)
- A descrição está fora do nosso [padrão de template](https://github.com/frontendbr/vagas/blob/master/.github/issue_template.md).

Repense esses pontos antes de postar alguma vaga aqui 😉

Por esse motivo estaremos fechando a issue, conforme [nossas regras](https://github.com/frontendbr/vagas#importante).
