### ISSUE TITLE
[São Paulo] Front-End Developer na Ciclic

### ISSUE THREAD

**Issue by le17i** [frontendbr/vagas#1376]
## Descrição da vaga

Buscamos pessoas que queiram fazer parte do nosso time, que sejam apaixonados por construir interfaces e tenham genuína preocupação com nossos usuários.

Se você gosta de desafios, apreender e ensinar, veja abaixo os detalhes da vaga.

## Local

Escritório, São Paulo - Vila Olímpia

## Benefícios

- Vale Alimentação
- Vale Refeição
- Plano de Saúde
- Plano Odontológico
- Previdência Privada
- Bônus
- Gympass

#### Diferenciais

- Horário flexível
- Home office 1 vez por semana
- Day Off de aniversário

## Requisitos

**Obrigatórios:**
- 2 anos de experiência
- Domínio em HTML, CSS e JavaScript
- Entender como o Browser funciona
- Conhecer HTTP, HTTP/2 e APIs Rest
- Saber utilizar Git
- Criação de código limpo, legível, cross-browser e cross-device

**Desejáveis:**
- Metodologias CSS (BEM, Atomic, OOCSS, ...)
- Pré-processadores CSS (Sass, PostCSS, Less, ...)
- Experiência com SPA
- Experiência em Vue e Vuex
- Webpack
- Performance
- Testes automatizados (Jest, Jasmine, Selenium)
- Design pattern em javascript
- SEO;
- Acessibilidade;
- ES6 / ES7;
- Trabalhar com metodologias ágeis

## Contratação

CLT a combinar

## A Ciclic

A [Ciclic](https://www.ciclic.com.br/) é uma plataforma financeira 100% digital que tem como objetivo ajudar você a realizar seus sonhos a partir de um plano de investimento. Nosso principal produto é o plano de previdência VGBL, com diferenciais vantajosos no mercado.

Acreditamos que com pequenas mudanças de hábitos e uma fonte confiável de informações (nós!) nossos clientes estarão cada vez mais próximo do seu sonho.

## Como se candidatar

Por favor envie um [email para vagasfront+ghpl@ciclic.com.br com seu CV anexado - enviar no assunto: Vaga FrontEnd Developer Pleno](mailto:vagasfront+ghpl@ciclic.com.br?subject=FrontEnd%20Developer%20Pleno)

## Labels

- Alocado
- CLT
- Pleno
- Remoto - Parcial

**Comment by le17i** [comment]
Estamos procurando ainda pessoal :)

**Comment by ribeiroevandro** [comment]
Enviado.

**Comment by gabrielferreiraa** [comment]
Se fosse full remote :(

**Comment by le17i** [comment]
Galera, fechamos a vaga :facepunch:
