### ISSUE TITLE
[Remoto ou Brasília] Front-End Developer (React) no Startaê

### ISSUE THREAD

**Issue by sales** [frontendbr/vagas#1377]
## Sobre a vaga
Procuramos um talentoso **Front-End Developer Experiente/Jedi** para trabalhar em projetos irados de startups Gringas e do Brasil com o [Startaê](https://startae.com/). O trabalho é **freela, full-time por projeto** e pode ser REMOTO ou em nosso office em Brasília.

As vagas são para início imediato e sua agilidade conta pontos.

Conheça nosso stack de tecnologia: http://stackshare.io/startae/startae/

## Local
Qualquer galáxia 👨‍🚀👩‍🚀🌌, tendo uma conexão de internet pra gente se comunicar, tá valendo.
Ou seja, **Trabalho Remoto FTW**, somos os criadores do movimento [Officeless](https://www.officeless.cc/).

## Benefícios
A combinar.

**Diferenciais**

* Nossa cultura de relacionamento é baseada na autonomia, propósito e confiança.
* Remote Works.
* Flexibilidade de horário. Cada um sabe a hora que é mais produtivo.
* Projetos Irados e Desafiadores.
* Tecnologias de Ponta.
* Ótima remuneração.
* Não fazemos time-tracking.
* Não trabalhamos com escopos fechados e sim priorizáveis.
* 6 Week Cycles. Ciclos de desenvolvimento de 6 semanas.

## Requisitos
**Obrigatórios:**

* Domínio em Javascript
* Domínio em React
* Git (utilizamos o Github)
* Saca muito de HTML e CSS
* Escreve seu código forma modular, utiliza das melhores práticas, convenções e processos
* Está confortável com metodologia ágil com ciclos de feedback constantes e interativos
* Escreve e se comunica bem
* Consegue assumir projetos do início ao fim
* É maker, você vai lá e faz!

**Desejáveis:**

* Inglês fluente
* Experiência em [Gatsby](https://www.gatsbyjs.org/) e/ou outros frameworks Javascript
* GraphQL
* Metodologias de teste dedicados ao mundo frontend
* Ama design e coisas bem feitas. É detalhista e se preocupa com a perfeição na implementação do frontend
* É fluente com transições CSS, SVG e Responsive Webdesign
* Paixão por User Experience e criar produtos que encantam as pessoas

**Diferenciais:**

* Ativo em comunidades e projetos open source.

## Contratação
PJ a combinar.

## Nossa empresa
O [Startaê](https://startae.com/) é um Studio de Produtos Digitais nascido em Brasília, mas com pessoas e clientes de todo o mundo. O nosso propósito é impactar positivamente a vida das pessoas. Somos empreendedores, designers, makers. Além de ajudar startups do Brasil e do Vale do Silício a criarem experiências fantásticas para seus produtos, criamos e desenvolvemos nossas próprias startups. Nossos parceiros já foram investidos pela Intel, 500 Startups, Monashees, Project A, Trinity, Shasta e Nike.

Acreditamos no poder das grandes idéias de melhorar vidas e tornar nosso mundo mais humano, mais simples, criativo e encantador. Estamos aqui para fazer esse potencial acontecer.

Além de ajudar outras startups, também criamos nossos próprios produtos como o [Officeless](https://www.officeless.cc/), [Cuckoo](https://cuckoo.team/), [Superquadra](http://www.superquadra.co/) e [Yummmy](https://yummmy.com.br/).

## Como se candidatar
Só mandar bala nesse form → **http://makerstribe.startae.com/**

## Labels
* Freela
* PJ
* Pleno
* Remoto - Total
* Sênior

**Comment by eduardoborges** [comment]
Opa! To querendo mudar pra Brasília. Vamos nessa.

**Comment by ribeiroevandro** [comment]
Preenchido o form, agora os dedos estão cruzados...

**Comment by sales** [comment]
Galera, muito obrigado pelas aplicações. Fechamos essa vaga, mas sempre surgem projetos muito legais por aqui. Assim que tiver novidades, posto novamente outras vagas!

**Comment by eduardoborges** [comment]
Mas já? :0

**Comment by renatocarvalho** [comment]
@eduardoborges Vamos abrir outra. Peparando um PR agora :)
