### ISSUE TITLE
[BA - Camaçari] Front-End Developer na Tivia

### ISSUE THREAD

**Issue by megandavulpi** [frontendbr/vagas#1378]
**Sobre a empresa: Tivia**

Somos uma Startup, temos há 8 anos uma plataforma web em produção para gerenciamento de pequenos/médios provedores desenvolvida em (RoR, html,css, js), emissão de boletos, carnês, integração com gateways de pagamentos e roteadores MikroTik, e também atuamos como provedor de internet. Nos últimos 2 anos estamos trabalhando em uma nova plataforma seguindo novas tecnologias (RoR, Angular6) que será lançada no próximo mês.

**Descrição: Ocupações do cargo**

O profissional será responsável por trabalhar com o time desenvolvendo, fazendo manutenção de Layouts do sistema que já estão desenvolvidos, além de desenvolver novos Layouts.

Esse profissional deve possuir conhecimento e experiência nas seguintes habilidades:

JavaScript
Angular 6 (PWA, Mobile)
HTML/CSS (Bootstrap e Material Design)
GIT
CI (Bitbucket/Jira)
Linux
Scrum/Kanban

**Benefícios**

Os benefícios que será agregado para esse profissional serão os seguintes:

Vale Refeição;
Assistência Médica;
Vale Transporte;
Aux. Moradia 1 mês;
Aux. (passagem p/ mudança).

**Aptidões e qualidades**

As principais aptidões e qualidades que o profissional deve ter serão as seguintes:

Adorar área de tecnologia;
Ser comunicativo;
Gostar trabalhar em equipe.

**Informações complementares**

Estamos desenvolvendo uma plataforma totalmente inovadora, pretendemos em um curto prazo dominar o mercado nesse segmento, participando das principais feiras/eventos que ocorre regionalmente e nacionalmente no segmento, levando a melhor experiencia para nossos usuários. Estamos recrutando um bom profissional "Front-Pleno" para juntar-se, crescer e ser valorizado junto ao nosso time.

**Senioridade:** 

Pleno

**Link para cadastrar na vaga: http://bit.ly/2MlBoxR**

**Comment by diogomoretti** [comment]
A descrição está fora do nosso [padrão de template](https://github.com/frontendbr/vagas/blob/master/.github/issue_template.md).

Por esse motivo estaremos fechando a issue, conforme [nossas regras](https://github.com/frontendbr/vagas#importante). Assim que ajustado, reabriremos!
