### ISSUE TITLE
[MG - Belo Horizonte] Full-Stack Developer na Grupo Mult

### ISSUE THREAD

**Issue by megandavulpi** [frontendbr/vagas#1379]
**Sobre a empresa: Grupo Mult**

O Grupo Mult é um provedor de conhecimento em tecnologia da informação desde 1998 no mercado. Nossa especialização em processos de negócio e integração de dados nos posiciona como um parceiro estratégico para implantação de arquiteturas de tecnologias de missão crítica.
 Enxergamos a ruptura do Digital como um desafio a ser cumprido sem esquecer dos atuais ativos.

**Descrição: Ocupações do cargo**

Propor, analisar e desenvolver sistemas e projetos Web (Backend/Frontend) e Mobile nas Plataformas Microsoft .NET;
Interagir com as equipes de desenvolvimento, testes, arquitetura e negócio para o desenvolvimento de projetos e sistemas; 
Apoiar os analistas de testes e usuários do negócio nas homologações;
Criar especificações técnicas, diagramas de classes, componentes e sequência em UML, codificar testes de unidade, testes de UI e integração;
Realizar pesquisas periódicas de melhores técnicas e evoluções tecnológicas na Plataforma Técnica;
Seguir os ritos de práticas ágeis (Scrum);

**Benefícios**

Vale alimentação ou Refeição. 
Plano de saúde da Unimed - Unipar/co-participativo (a empresa paga 50% da mensalidade e o profissional paga 50%, mais as taxas de coparticipação)
Plano odontológico. 
Participação nos lucros, conforme convenção coletiva. 
Seguro de vida coletivo. 

**Aptidões e qualidades**

Dinamismo
Transparência
Trabalho em Equipe
Boa Comunicação
Concentração
Pró-Atividade
Vontade de aprender
Boa adaptabilidade

**Informações da complementares**
 
Conhecimentos sólidos:

Programação orientada a objetos com C#;
ASP.Net Core;
Dos princípios SOLID;
Principais padrões de projetos;
IDE - Visual Studio;
Cloud Developer com Microsoft Azure, utilizando os serviços PaaS: App Services, Storage Tables, Service Bus, SQL e AAD;
TDD / BDD com xUnit e Specflow;
DDD – Modelagem, camadas lógicas, padrões: Repository, Fabric, Services, Specification, Agregator e afins;
Desenvolvimento com os estilos arquiteturais Microservices, CQRS e Event Sourcing;
Tecnologias frontend Angular, Angular Material, CSS3, HTML5, PWA;
Frameworks Javascript Karma, Protractor ou similares para testes de unidade e integração;
Participado de projetos que utilizam métodos ágeis, como o Scrum ou XP;
Gerenciamento de código fonte com Git;

**Desejável:**

Utilização do Visual Studio Team Services em projetos;
Práticas DevOps - Integração e entrega continua – CI / CD;
Ferramenta Zeplin – Interface Design / Desenvolvedor;
Azure Api Management, Cosmos DB, DocumentDB e AKS;
Docker e Kubernetes;

**Senioridade:**

Senior

**Link para cadastrar na vaga: http://bit.ly/2Mm2Xaf**

**Comment by diogomoretti** [comment]
@megandavulpi dois pontos que estão fora das nossas regras:

- Verificar se realmente a vaga é para Front-end. Se precisar postar em outros canais que não seja de Front-end, você pode encontrar eles [aqui](https://github.com/frontendbr/vagas#outros-reposit%C3%B3rios-de-vagas)
- A descrição está fora do nosso [padrão de template](https://github.com/frontendbr/vagas/blob/master/.github/issue_template.md).

Repense esses pontos antes de postar alguma vaga aqui 😉

Por esse motivo estaremos fechando a issue, conforme [nossas regras](https://github.com/frontendbr/vagas#importante).
