### ISSUE TITLE
[MG - Belo Horizonte] Front-End Developer na Grupo Mult

### ISSUE THREAD

**Issue by megandavulpi** [frontendbr/vagas#1380]
**Sobre a empresa: Grupo Mult**

O Grupo Mult é um provedor de conhecimento em tecnologia da informação desde 1998 no mercado. Nossa especialização em processos de negócio e integração de dados nos posiciona como um parceiro estratégico para implantação de arquiteturas de tecnologias de missão crítica.
 Enxergamos a ruptura do Digital como um desafio a ser cumprido sem esquecer dos atuais ativos.

**Descrição: Ocupações do cargo**

Propor, analisar e desenvolver sistemas e projetos Web (Frontend) e Mobile nas Plataformas Microsoft .NET;
Interagir com as equipes de desenvolvimento, testes, arquitetura e negócio para o desenvolvimento de projetos e sistemas; 
Apoiar os analistas de testes e usuários do negócio nas homologações;
Criar especificações técnicas, diagramas de classes, componentes e sequência em UML, codificar testes de unidade, testes de UI e integração;
Realizar pesquisas periódicas de melhores técnicas e evoluções tecnológicas na Plataforma Técnica;
Seguir os ritos de práticas ágeis (Scrum);

**Benefícios**

Vale alimentação ou Refeição. 
Plano de saúde da Unimed - Unipar/co-participativo (a empresa paga 50% da mensalidade e o profissional paga 50%, mais as taxas de coparticipação)
Plano odontológico. 
Participação nos lucros, conforme convenção coletiva. 
Seguro de vida coletivo. 

**Aptidões e qualidades**

Dinamismo
Transparência
Trabalho em Equipe
Boa Comunicação
Concentração
Pró-Atividade
Vontade de aprender
Boa adaptabilidade

**Informações complementares**

Conhecimentos sólidos:

Programação orientada a objetos;
Dos princípios SOLID;
Style Guide do site oficial angular.io;
JavaScript Vanilla ECMAScript 2015+;
CSS3 + HTML5;
Angular Material;
Services Works - PWA;
Testes de unidade com Karma ou similar;
Testes end-to-end com Protractor;
Participado de projetos que utilizam métodos ágeis, como o Scrum ou XP;
Gerenciamento de código fonte com Git;

**Desejável:**

Conhecimentos do Visual Studio Team Services;
Práticas DevOps - Integração e entrega continua – CI / CD;
Ferramenta Zeplin – Interface Design / Desenvolvedor;
Desenvolvimento backend com ASP.Net Core com C#;
Desenvolvimento com os recursos da Microsoft Azure

**Senioridade:**

Senior

**Link para cadastrar na vaga: http://bit.ly/2MkVngh**

**Comment by diogomoretti** [comment]
A descrição está fora do nosso [padrão de template](https://github.com/frontendbr/vagas/blob/master/.github/issue_template.md).

Por esse motivo estaremos fechando a issue, conforme [nossas regras](https://github.com/frontendbr/vagas#importante). Assim que ajustado, reabriremos!
