### ISSUE TITLE
[MG - Belo Horizonte] Full-Stack PHP Developer na Dowbis

### ISSUE THREAD

**Issue by megandavulpi** [frontendbr/vagas#1381]
**Sobre a empresa: Dowbis**

Nosso negócio é vender seu produto ou serviço.
 
Muitas empresas têm produtos e serviços de qualidade, uma boa aceitação no mercado e a capacidade de gerar leads, no entanto na hora de comercializar esses produtos ou serviços, essas corporações, encontram dificuldades comerciais significativas. Nesse contexto, surge a DOWBIS, atuando desde a captação do lead ao fechamento da venda, entendendo que este processo se dá desde a emissão do pedido ao recebimento do produto adquirido.

**Descrição:  Ocupações do cargo**

- Desenvolvimento de Sites e/ou Landing Pages, Sistemas de Gestão, criação de Formulários, Plugins, Módulos, para Sites e Wordpress e Loja Virtual;
- Integração e/ou Criação de API’s e Web Services;
- Manuais (tutoriais) para Sistemas e/ou Integrações;
- Diagnosticar problemas de acesso (sessão);
- HTML - CSS - Javascript - PHP - Codeigniter (Framework);

**Benefícios:**

- Vale Transporte pago em dinheiro.
- Alimentação na empresa.

**Aptidões e qualidades:**

- Comunicação verbal e escrita;
- Ser guiado por uma intuição criativa,
- Conhecimento de mídias sociais;
- Organização;
- Estar sempre antenado às constantes mudanças do marketing digital e desenvolvimento;
- Agilidade de reação à tendências e oportunidades;
- Forte capacidade organizacional para lidar com múltiplas tarefas dentro das limitações de cronogramas e orçamentos com perspicácia de negócios;
- Capacidade de trabalhar e prosperar em um ambiente acelerado, aprender rapidamente e dominar diversas tecnologias e técnicas da web.

**Informações da empresa:**

O Grupo ALFAMART é uma empresa que gerencia faculdades e institutos educacionais pelo Brasil. O Profissional que entrar no time precisará desembolar na programação e trabalhar em equipe com o comercial da empresa. Ele ficará na aba do MKT (Dowbis) da empresa que conta com 20 pessoas de diversas áreas, como por exemplo, inbound, criação, social media, midia de perfomance, redação e a programação. Os produtos do grupo são: Instituto Cotemar, Instituto Graduarte, Instituto Graduarte, Faculdade Fama, Alfa, Famart e vários outros.

**Senioridade:**

Junior

**Link para cadastrar na vaga: http://bit.ly/2MmuTea**

**Comment by diogomoretti** [comment]
@megandavulpi dois pontos que estão fora das nossas regras:

- Verificar se realmente a vaga é para Front-end. Se precisar postar em outros canais que não seja de Front-end, você pode encontrar eles [aqui](https://github.com/frontendbr/vagas#outros-reposit%C3%B3rios-de-vagas)
- A descrição está fora do nosso [padrão de template](https://github.com/frontendbr/vagas/blob/master/.github/issue_template.md).

Repense esses pontos antes de postar alguma vaga aqui 😉

Por esse motivo estaremos fechando a issue, conforme [nossas regras](https://github.com/frontendbr/vagas#importante).
