### ISSUE TITLE
[São Paulo - SP] Front-end Developer no Campus Code

### ISSUE THREAD

**Issue by erikacamposdesign** [frontendbr/vagas#1382]
## Descrição da vaga

Procuramos uma pessoa desenvolvedora de software front-end capaz de ajudar nossa equipe de back-end a entregar projetos com melhor usabilidade e mais acessíveis aos usuários finais.

Esperamos que você ‘suje as mãos’ em nossos projetos atuais, faça experiências e proponha soluções completas de front-end em conjunto com o restante do time de desenvolvimento.

## Local

São Paulo, próximo ao Metrô Trianon-Masp

## Requisitos

- Experiência de desenvolvimento em React e/ou Vue.js conectando aplicações via API REST; 

- Usar Git e Github/Gitlab/Bitbucket como parte do seu processo de trabalho;

- Saber Javascript pra valer a ponto de propor mudanças no nosso stack de tecnologias com embasamento;

- Facilidade de atuar em projetos de escopo diversificado, tanto internos como de nossos parceiros;

- Saber utilizar testes automatizados (TDD/BDD) e integração contínua a favor dos projetos e do time de desenvolvimento;

- Conhecimentos em inglês suficientes para ler/consultar documentações técnicas de projetos, linguagens e ferramentas utilizadas nos projetos.

**Desejável:**

- Saber Docker é algo positivo mas não essencial, o mesmo se aplica para Ruby on Rails.

## Contratação

PJ a combinar

- Ajuda de custos com cursos e eventos
- Horário flexível de verdade
- Possibilidade de Home Office (definido com o time)

## Nossa empresa

Somos uma empresa jovem criada por devs muito experientes que orientam os projetos e garantem que o foco deve ser sempre na produção de software de qualidade. Então, você pode esperar uma boa infraestrutura, discussões técnicas com frequência e liberdade para opinar mesmo em projetos que você não participa. Code Review, Pair Programming e retrospectivas constantes são o nosso dia a dia.

Levamos a sério métodos ágeis de desenvolvimento e temos a preocupação de entender o escopo, as necessidades e a cultura do time de tecnologia de nossos parceiros para que a entrega seja efetivamente de valor para o negócio. Atuamos em projetos críticos de empresas de diferentes portes. Ajudamos desde startups em consolidação até empresas com mais de um milhão de clientes.

**Porque é legal trabalhar aqui segundo nossos devs:**

- A troca de conhecimento é valiosa
- A variedade de projetos e rotatividade é desafiadora
- O incentivo à melhoria contínua e aprendizado é genuína
- Feedbacks acompanhados de mentoria agregam a carreira
- As tecnologias utilizadas no dia a dia são atuais
- Existe preocupação com o código de qualidade e não só com o produto final
- Temos discussão de código, levantamento de problemas e soluções em grupo
- Liberdade para perguntar o que quiser, sem julgamentos ou preconceitos
- Talks e palestras internas

## Salário

Faixa salarial: De R$ 5.000,00 a R$ 8.000,00 (de acordo com avaliação da nossa equipe)

## Como se candidatar

Envie seu CV com portfólio de projetos para [vagas@campuscode.com.br](vagas@campuscode.com.br)

## Labels

- PJ
- Pleno
- Sênior

**Comment by erikacamposdesign** [comment]
Continuamos em busca de uma pessoa desenvolvedora front-end.

**Comment by ribeiroevandro** [comment]
Enviado
