### ISSUE TITLE
[Pinheiros - São Paulo - SP] Full Stack Rails na Worldpackers

### ISSUE THREAD

**Issue by joaomm** [frontendbr/vagas#1385]
## Descrição da vaga

A Worldpackers torna possível experiências incríveis de viagem que cabem no bolso. Somos uma comunidade de mais de 1.200.000 de viajantes e anfitriões trocando habilidades por acomodação ao redor do mundo. Imagine mochilar pela América do Sul ajudando hostels com recepção ou social media, voluntariar pelo Sudeste Asiático em ONGs & projetos sociais ou aprender sobre sustentabilidade em ecovilas & projetos ecológicos.

Temos um time de tecnologia enxuto e bem experiente para tornar a parte técnica na “parte fácil” e nos focar em melhorar, testar & crescer nosso produto & negócio. Procuramos alguém para trabalhar com nossa aplicação Web & API Rails em ambiente ágil e paixão por código limpo.

## Local

Presencial: Pinheiros - São Paulo

## Requisitos

**Essa vaga é perfeita para você, se você tecnicamente:**

- Não pára de aprender
- Ama fazer muitos deploys por dia
- Pira quando vê uma enorme bateria de testes automatizados verdes
- Respira código limpo
- Quer fazer/saber de tudo um pouco (front, back, APIs,  infra, etc)
- Já trabalhou com desenvolvimento Ruby / Rails

**Também é perfeita para você, você pessoalmente:**

- É apaixonadx pela ideia de usar tecnologia para impactar a vida de milhões de pessoas ao redor do mundo
- Se sente motivadx em um ambiente de startup global em constante mudança, testes e novas oportunidades
- Trabalha com autonomia & responsabilidade, participando ativamente das decisões do produto
- Toma decisões baseadas em dados e feedback de usuários
- Tem um mindset de melhoria contínua, sempre desenvolvendo seus skills e entendimento do mercado & negócio
- Quer trabalhar com propósito com gente realmente boa!

## Contratação

PJ/CLT a combinar

## Como se candidatar

Preencha o seguinte form: https://goo.gl/forms/RSGkW7b6lABmqsCe2

## Labels

- Presencial
- CLT
- PJ
- Startup

**Comment by vinirossi** [comment]
@joaomm  Bom dia, vocês por acaso estão com vagas para estágio front-end ou vaga de dev júnior?

**Comment by joaomm** [comment]
> @joaomm Bom dia, vocês por acaso estão com vagas para estágio front-end ou vaga de dev júnior?

Valeu pela pergunta @vinirossi! No momento, estamos procurando por quem tenha pelo menos um pouco de experiência com Rails e full-time : )
