### ISSUE TITLE
[Sorocaba - SP] Front-End Developer na Tegra

### ISSUE THREAD

**Issue by Vitormdias** [frontendbr/vagas#1386]
## Descrição da vaga

Irá trabalhar em projetos React, React-Native ou Vue geralmente, com a possibilidade de ajudar no Back End caso queira.

## Local

Escritório em Sorocaba

## Benefícios

- Flexibilidade de horário
- Plano de saúde SulAmérica
- Cursos do Alura e Egghead
- PLR
- VR/VT
- Possibilidade de contrato PJ

#### Diferenciais

- Frigobar e armário sempre cheio
- Ambiente favorável a aprendizagem

## Requisitos

*Desejáveis*
- Boas noções de OO
- JS (ES6 ou TypeScript)
- React, Angular ou Vue (pelo menos 1)
- Sass

*Diferenciais*
- RxJs
- Redux
- Webpack
- React Native
- Padrões de projeto
- Noções de UX

## Contratação

PJ ou CLT a combinar

## Nossa empresa

A Tegra é uma empresa jovem com ambiente informal e descontraído.
Com sede em Sorocaba e escritório em Pinheiros/SP atendemos os mais diversos tipos de clientes e entregamos sempre soluções de grandes impactos dentro de cada negócio.  

## Como se candidatar

Por favor envie um email para vitor.manfre@tegra.com.br com seu CV anexado - enviar no assunto: Vaga Front End

**Comment by vinirossi** [comment]
Olá @Vitormdias vocês aceitam estágio ou Júnior?

**Comment by DanielLCintra** [comment]
É possível trabalhar remoto?

**Comment by Vitormdias** [comment]
Estamos entrevistando Júnior também @vinirossi  , mas infelizmente não é possível trabalhar remoto @DanielLCintra

**Comment by ribeiroevandro** [comment]
Enviado

**Comment by naaataliaazevedo** [comment]
Enviado. :woman:
