### ISSUE TITLE
[São Caetano do Sul] Estagiário(a) Front-end

### ISSUE THREAD

**Issue by luansmr** [frontendbr/vagas#139]
## Descrição da vaga

Estamos à procura de um profissional com grande entusiasmo, vontade de aprender e crescer profissionalmente. Responsabilidade e engajamento para solucionar problemas são características importantes.

Criatividade, espírito de equipe e muito comprometimento farão a diferença!
## Local

Escritório, São Caetano do Sul - Espaço Cerâmica
## Benefícios
- Vale-transporte
- Vale-refeição
- Ambiente de trabalho descontraído e equipe colaborativa
- Incentivo a treinamentos e formações
- Snacks
- Puffs
- PS4
## Requisitos

**Obrigatórios:**
- Conhecimento em desenvolvimento front-end
- Conhecimento na criação de layout de sites baseados em HTML5, CSS, JS
- Conhecimento em jQuery
- Conhecimentos de design responsivo
- Comprometimento, trabalho em equipe, ter iniciativa e boa comunicação
- Curiosidade investigativa na busca de soluções inovadoras e criativas para melhoria da UX
- Trabalho em equipe seguindo o desenvolvimento de acordo com padrões pré-definidos, capacidade de desenvolver a interface de acordo com mockups e wireframes

**Desejáveis:**
- Conhecimentos de SEO (Search Engine Optimization)
- Conhecimento em Json
- Alunos a partir do 3º semestre de Ciência/Engenharia da Computação, Comunicação, Publicidade e Propaganda ou X! (o importante é gostar de programar, independente da graduação)

**Diferenciais:**
- Conhecimentos de controle de versões (TFS / Source Control / Git)
- Habilidade com Photoshop, Fireworks e Microsoft Visual Studio
- Conhecimentos em padrões MVC (razor)
- Portfólio para avaliação ou link do Git
## Contratação

Estágio
## Nossa empresa

Somos uma empresa de consultoria e serviços em informática, com forte atuação no desenvolvimento de aplicações Web, comércio eletrônico, aplicativos mobile e gerenciamento de projetos em TI.

Especializados em prover soluções de inteligência de negócios, entregamos produtos e serviços customizados de tecnologia, alinhados à estratégia de negócios do cliente. Agregamos valor e velocidade aos processos informatizados, principalmente em áreas estratégicas da empresa, ou em departamentos específicos.
## Como se candidatar

Por favor envie um email para lsommerhauzer@atma-it.com e ealmeida@atma-it.com com seu CV anexado.

**Comment by matheusdelima** [comment]
Apenas presencial?

**Comment by gabrielrunescape** [comment]
Há possiblidades de se fazer remoto?

**Comment by Rivail** [comment]
enviei meu currículo, moro perto.

**Comment by LFeh** [comment]
@luansmr A vaga continua aberta?

**Comment by luansmr** [comment]
Sim, a vaga ainda esta aberta.

Atenciosamente,
*Luan Sommerhauzer*
*=========================*


2016-11-14 11:11 GMT-02:00 Felipe Fialho <notifications@github.com>:
