### ISSUE TITLE
 [Alphaville / Barueri] Front-End Developer Pleno ou Sênior na Talentify

### ISSUE THREAD

**Issue by dreanmer** [frontendbr/vagas#1390]
## Detalhes da Vaga

Localização: **Barueri, SP**
Contratação: **CLT**
Remuneração **R$4.000,00 - R$6.000,00/mês**

### Benefícios:

- Plano de Saúde (Amil);
- VA R$200;
- VR R$26 / dia;
- VT, fretado, ou estacionamento;
- Seguro de Vida;
- Horário Flexível;

### Responsabilidades da vaga

- Desenvolver novos componentes e telas para o nosso sistema de recrutamento
- Refatoração de telas prontas

### Experiência Requerida:

- Design Responsivo
- Javascript Vanilla / jQuery
- Vue.js (ou algum framework mvvm)
- Pré processadores
- Bundlers

### Experiência Desejável (100% opcionais):

- Testes Automatizados de Front;
- Experiencia com Php;
- Phalcon (framework php);

## Sobre Talentify

Acreditamos que a combinação Marketing + Tecnologia + Pessoas é a base do R&S do Futuro! E que todas as partes envolvidas em um processo seletivo podem ter uma experiência inteligente, ágil e descomplicada.

## Sobre a Equipe

Somos uma equipe enxuta de 6 desenvolvedores (backend) sênior, além de um designer e um frontend. Gostamos de sempre discutir a melhor implementação de uma task e contamos com a opinião de todos, para se dar bem aqui tem que saber defender bem sua idéia, mas também ouvir o colega e sempre tirar o melhor das conversas. Em unanimidade usamos linux + phpstorm e docker como environment, mas vc estará livre para usar o ambiente que lhe melhor lhe convir.

Inscrição rápida por aqui: https://goo.gl/E73tuR

Dúvidas? alexandre@talentifyhr.com

## Labels

- Vue.js
- Pleno
- Sênior
- CLT
- Presencial

**Comment by dreanmer** [comment]
update link de inscrição. A vaga ainda esta aberta!

**Comment by mikejavier** [comment]
@dreanmer, possibilidade de remoto?

**Comment by dreanmer** [comment]
@mikejavier remoto não, aqui até fazemos um pouco de home office, mas nada oficial...

**Comment by joaoprado** [comment]
Que pena. A vaga é muito bacana, mas seria perfeito se pudesse ser remoto
