### ISSUE TITLE
[BA - Camaçari] Front-End Developer na Tivia

### ISSUE THREAD

**Issue by megandavulpi** [frontendbr/vagas#1391]
## Descrição da vaga

O profissional será responsável por trabalhar com o time desenvolvendo, fazendo manutenção de Layouts do sistema que já estão desenvolvidos, além de desenvolver novos Layouts.

Esse profissional deve possuir conhecimento e experiência nas seguintes habilidades:

JavaScript
Angular 6 (PWA, Mobile)
HTML/CSS (Bootstrap e Material Design)
GIT
CI (Bitbucket/Jira)
Linux
Scrum/Kanban

## Local

BA - Camaçari

## Benefícios

- Vale Refeição;
- Assistência Médica;
- Vale Transporte;
- Aux. Moradia 1 mês;
- Aux. (passagem p/ mudança).

## Nossa empresa

Somos uma Startup, temos há 8 anos uma plataforma web em produção para gerenciamento de pequenos/médios provedores desenvolvida em (RoR, html,css, js), emissão de boletos, carnês, integração com gateways de pagamentos e roteadores MikroTik, e também atuamos como provedor de internet. Nos últimos 2 anos estamos trabalhando em uma nova plataforma seguindo novas tecnologias (RoR, Angular6) que será lançada no próximo mês.

## Como se candidatar

Acesse o link da vaga: http://bit.ly/2MlBoxR

## Labels

- CLT
- Pleno
- Alocado

### Informações complementares

Estamos desenvolvendo uma plataforma totalmente inovadora, pretendemos em um curto prazo dominar o mercado nesse segmento, participando das principais feiras/eventos que ocorre regionalmente e nacionalmente no segmento, levando a melhor experiencia para nossos usuários. Estamos recrutando um bom profissional "Front-Pleno" para juntar-se, crescer e ser valorizado junto ao nosso time.

**Comment by mtmr0x** [comment]
@megandavulpi Nas labels poderia adicionar sobre se é alocado, remoto total e/ou remoto parcial, por favor?

**Comment by megandavulpi** [comment]
> @megandavulpi Nas labels poderia adicionar sobre se é alocado, remoto total e/ou remoto parcial, por favor?

@mtmr0x Done!
