### ISSUE TITLE
[São Paulo] Front-End Developer na [PRINTASTICO]

### ISSUE THREAD

**Issue by rafaelaugustoferreira** [frontendbr/vagas#1392]
## Descrição da vaga

HEY FREELAS!
Nós da Printástico estamos com uma vaga, no modo freela para início imediato. O(a) freela irá atuar majoritariamente em nossa ferramenta de criação de foto-produtos para impressão, além de conexões da ferramenta com o site e com a equipe de impressão.

Será necessário o conhecimento e experiência em Front-end, Javascript, HTML5, CSS, Framework React e Redux. Conhecimentos em Git, Redux-saga, Normalizer, Glue Spritesheets, Node.js, Webpack, Babel, Cross-env, Flash (consulta de código legado), Bash e Scrum são diferenciais importantíssimos.

Nosso escritório esta localizado na Avenida Paulista, bem próximo do metrô Consolação, Center 3 e Starbucks (ainda bem :D)!!! 
O horário é flexível e o trabalho é alocado (inicialmente).

## Local

Remoto ou Escritório, São Paulo - Bela Vista.

## Benefícios

- Horário flexível
- Possibilidade de trabalho remoto

## Requisitos

**Obrigatórios:**
- Front-end
- Javascript
- Html5
- Css
- Framework react e redux

**Desejáveis:**
- Git
- Redux-saga
- Normalizer
- Glue spritesheets
- Node.js
- Webpack
- Babel
- Cross-env
- Flash (consulta de código legado)
- Bash
- Scrum

## Contratação

PJ a combinar

## Nossa empresa

A Printástico é uma empresa brasileira especializada em FotoProdutos e impressões digitais, que segue os mais altos padrões internacionais de tecnologia e qualidade. Nossa missão é oferecer aos nossos clientes um ambiente seguro e aplicações que garantam a criação de projetos personalizados de maneira rápida, fácil e divertida.

## Como se candidatar

Por favor envie um email para rf@printastico.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

## Labels

- PJ
- Freela
- Alocado (Inicialmente)
- Front-end

**Comment by mtmr0x** [comment]
@rafaelaugustoferreira poderia adicionar na label que é freela, além de especificar também sobre ser alocado e/ou remoto de acordo com as labels de exemplo no https://github.com/frontendbr/vagas/blob/master/.github/issue_template.md que aparece já com moldes quando vai criar uma postagem aqui, por favor?
