### ISSUE TITLE
[são paulo - vl olimpia] Front-end JR na Renner

### ISSUE THREAD

**Issue by jureis** [frontendbr/vagas#1394]
## Descrição da vaga

Projeto bazinga em NodeJS, etc.

## Local
Vila Olímpia, SP
Vaga efetiva, para trabalhar alocado (não pode ser homeoffice)

## Benefícios
- Plano de saúde - para assistentes, apenas depois de 24 meses de casa
- Refeição em restaurante conveniado, come a vontade + bebida
- VT e PPR (se atingir as metas)
- ...

#### Diferenciais
escritório novo, crescendo muito, tem muitas chances de aprender e crescer aqui.

## Requisitos
Esta pessoa sera um ‘braço do TI’ dentro do Marketing, a serviço de negócio - Somos o e-commerce da Renner.

- A rotina é programar banners e campanhas para o site na plataforma da Oracle (iremos ensinar a ferramenta)
- irá programar hotsites, landing pages especiais (desk e mobile) - são paginas simples, com efeitos básicos de carrossel, videos embedados, efeito de hover etc
- possíveis manutenções simples no site (cabeçalho, rodapé, alguma página especifica) é tudo front ou ferramenta oracle
- linguagens que precisa saber: HTML, CSS e JS

**Obrigatórios:**
experiencias anteriores como programador.

**Desejáveis:**
- vivencia em e commerce ou varejo
- photoshop (se não souber OK!)

## Contratação
CLT

## Como se candidatar
Por favor envie um e-mail para j.reis@lojasrenner.com.br com seu CV anexado - enviar no assunto: Vaga FrontEnd JR

**Comment by AlbericoD** [comment]
bem legal essa vaga pra quem ta começando

**Comment by mtmr0x** [comment]
@jureis poderia ajustar essa vaga com o template da issue, por favor? De acordo com as politicas do repositório, vou fechar a vaga e reabrimos quando estiver ok.

O racional por trás disso é manter um padrão e poder ter informações concisas entre esse repositorio, o site e nosso Twitter
