### ISSUE TITLE
[São Paulo] Desenvolvedor Front-end (2 vagas)

### ISSUE THREAD

**Issue by neysimoes** [frontendbr/vagas#14]
## Descrição da vaga

Temos duas vagas para front-end aqui na Beleza na Web.

Estamos formando a melhor equipe de TI do Brasil e para isso estamos contratando profissionais de alto nível para trabalhar com as mais avançadas tecnologias! Esqueça código legado, nós vamos jogar no LIXO tudo que é antigo e refazer do zero!

O mais importante para essa vaga é ter proatividade e muita vontade de aprender. Temos projetos com AngularJS, ReactJS, NodeJS,  stylus, PostCSS e tudo que há de melhor no mercado.

## Local

Presencial em São Paulo, região do Jaguaré (Zona Oeste).
Próximo a estação Jaguaré (CPTM)

## Requisitos

- HTML, CSS e JavaScript
- Build system (Gulp/Grunt/Webpack)
- Pré-processadores CSS (PostCSS/Stylus/Sass/Less)
- Git
- APIs RESTful
- Técnias de otimização (Web Performance Optimization)

Diferenciais
- Arquitetura frontend
- React.js (ou qualquer outra SPA)
- Node.js
- OAuth2
- Arquitetura de microservices
- Testes (Karma, Jasmine...)

## Contratação

Fulltime, CLT.

## Benefícios
- Plano de saúde
- Seguro de vida
- Vale alimentação
- Vale transporte

## Nossa empresa

Somos uma loja online de produtos de beleza. Uma rede que conecta consumidores, marcas, formadores de opinião e os melhores profissionais do mercado.

Para ajudar você a fazer as escolhas que vão atender os seus desejos de beleza, todo um time de experts está a postos. São cabeleireiros e maquiadores badalados, renomados dermatologistas e editoras de beleza que escolheram a dedo mais de 200 marcas, levando até você informações completas, dicas e truques profissionais de mais de 13 mil produtos.

Nossa preocupação em atender você com excelência levou Beleza na Web a ser escolhida, por mais de 600 mil de consumidores, **A Melhor Loja de Beleza Online do Brasil**, e ser eleita entre as Top 5 de todo o comércio eletrônico do país.

O que estão falando sobre nós: 

[TechCrunch](http://techcrunch.com/2015/06/15/belezanaweb-raises-30m-to-bring-brazils-beauty-market-online/)
[Exame](http://exame.abril.com.br/revista-exame/edicoes/1083/noticias/ele-chegou-antes)

## Como se candidatar

Envie seu CV com Github para franklin.alves@belezanaweb.com.br

**Comment by rubenmarcus** [comment]
Muito boa a vaga pena eu ter algumas qualificacoes nao todas,  e morar a 20m do Jaguare =/

**Comment by neysimoes** [comment]
As duas vagas já foram preenchidas, por isso estou fechando a issue.

**Comment by LFeh** [comment]
\o/

**Comment by renatogalvones** [comment]
Pô, foi bem rápido hein @neysimoes?!  Animal!

**Comment by willianjusten** [comment]
=D

**Comment by camilatigre** [comment]
@neysimoes 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

**A pessoa que preencheu a vaga foi encontrada através desta issue?**
a) Sim
b) Não
c) Não tenho certeza

**Comment by franklinjavier** [comment]
b)
