### ISSUE TITLE
[REMOTO] Front-End Developer [CSS] e [Styled-components] na Rocketlab

### ISSUE THREAD

**Issue by nativedone** [frontendbr/vagas#1400]
![2th vaga](https://user-images.githubusercontent.com/20998754/45579729-80973600-b8cd-11e8-82e7-de33eeac32e5.png)

## Descrição da vaga

Oi pessoal,

Tem uma `2a vaga` de senior frontend do meu team aqui de Sydney/AU.

Como eh um projeto com deadline apertada precisa ser alguem com bastante experiencia.

Basicamente, espera-se alguem que tabalhe bem remoto e que possa garantir que a UI seja fiel ao design usando: `Styled-Components`.

O time possui devs very very experientes em reactJS, mas nao tao seniors em `CSS` pra resolver aqueles detalhes que garantem o famoso *pixel perfect*.

## Local

Totalmente Remoto

#### Diferenciais

- Flexibilidade de horarios
- Pagamento em $AUD
- Contrato: `full-time`, `part-time` ou `freelance`
- Selecao sem enrolacao: 

1. Envie um codigo seu usando styled-components
2. Call curta de 15 min em portugues
3. Test em real-time de 50 min em ingles (compartilhando a tela)
4. Contratacao ou feedback em `ateh 2 dias`  

## Requisitos

**Obrigatórios:**
- Top em CSS 
- Experiência em Styled-components
- Falar ingles (Nao precisa muita fluencia. O foco total eh comunicacao! Somos uma empresa de software. Pode falar ingles com erros? Pode! Mas, tem que falar. Tem que comunicar a sua idea e o seu trabalho.)

**Diferenciais:**
- Material UI.
- GraphQL

## Contratação

A combinar.

## Nossa empresa

https://www.rocketlab.com.au/

## Como se candidatar

- Me envie uma messagem privada em https://twitter.com/nativedone 

## Labels

- Remoto - Total
- Sênior

**Comment by mrangel-jr** [comment]
A vaga ainda está aberta ? 🥇
