### ISSUE TITLE
[Salvador, BA] Desenvolvedor(a) Frontend CLT na Cubos Tecnologia

### ISSUE THREAD

**Issue by lbguilherme** [frontendbr/vagas#1402]
## Descrição da vaga:
Somos uma desenvolvedora de softwares e, nos nossos projetos, utilizamos metodologias ágeis. Vamos muito além do desenvolvimento para fazer a diferença na vida das pessoas. Oferecemos um ambiente colaborativo, com uma galera massa trabalhando em busca da evolução contínua e prezando por fazer entregas foda. Buscamos pessoas fantásticas que se identifiquem com a nossa cultura e, principalmente, que queiram fazer e ser parte da nossa história.

Nossa stack:
• Typescript
• React
• Sass / styled-components
• Webpack
• Babel

## Local:
Alameda Salvador, n. 1057, Torre América, sala 1008
Salvador, BA
Estamos de mudança. Localização do novo escritório ainda não definida.

## Benefícios:
• Vale refeição ou alimentação
• Plano de saúde e odontológico
• Vale transporte
• Aulas semanais multidisciplinares

## Requisitos:
Obrigatório:
• Conhecimento em versionamento com Git;
• Conhecimento em HTML e CSS;
• Conhecimento em Javascript (ES6+);
• Experiência fazendo interfaces de usuário complexas para a Web;
• Experiência com bibliotecas ou frameworks de UI (React, Angular, Vue, etc).

Diferenciais:
• Leitura na língua inglesa;
• Experiência com testes automatizados no frontend;
• Experiência com React;
• Experiência com GraphQL;
• Conhecimento em Typescript;
• Conhecimento em acessibilidade e SEO;
• Experiência com back-end, Node em especial;
• Apresentação de portfólio, Github ou similares;
• Habilidades em padrões de design de interface e experiência de usuário;
• Conhecimento em pré-processadores de CSS (Sass, Stylus, Less, etc) ou CSS in JS (styled-components, emotion, etc).

## Contratação:
CLT - salário será discutido na entrevista.

## Nossa empresa:
O que acreditamos:
• Somos uma empresa focada no desenvolvimento das pessoas;
• Queremos ver os cúbicos crescendo e evoluindo sempre;
• Aprender e compartilhar é o nosso valor mais intenso;
• Nos importamos verdadeiramente com nossas entregas.

## Como se candidatar:
Se inscreve em jobs.cubos.io

**Comment by ferreirabh** [comment]
Existe a possibilidade de trabalho remoto?

**Comment by mtmr0x** [comment]
@lbguilherme poderia colocar as labels de acordo com o modelo de criação de issue, por favor? Ajustando isso podemos reabrir a vaga
