### ISSUE TITLE
[São Paulo] Software Engineer na Liv Up

### ISSUE THREAD

**Issue by rstraat** [frontendbr/vagas#1405]
## Descrição da vaga e da empresa

A Liv Up é uma startup de alimentação fundada em março de 2016 que tem crescido em um ritmo muito acelerado (+15% ao mês), tendo recebido investimento da Kaszek Ventures, um dos principais investidores em startups na América Latina. Parte fundamental da nossa estratégia é ter um time forte de tecnologia, responsável por otimizar a experiência do usuário e desenvolver sistemas com as tecnologias mais recentes para modelar, automatizar e acelerar todos os nossos processos, desde a produção até a logística e envio das nossas refeições.

Nosso stack é em Node.js, React.js e MongoDB, com código bem organizado, testes automatizados e o time é enxuto e ágil. 
Nos organizamos em squads que têm como objetivo desde desenvolver soluções para os nossos processos produtivos, trazendo nossa operação para a Indústria 4.0, até trabalhar com os times de produto e growth, voltados à experiência do cliente em nosso PWA. Isso significa participar ativamente das diversas equipes da empresa, entender ou criar os processos das áreas e desenvolver junto com elas soluções buscando aumentar nosso nível de serviço e possibilitar que entreguemos refeições saudáveis e saborosas para cada vez mais pessoas.

## Local

Escritório em Pinheiros, São Paulo (5min das estações Pinheiros e Faria Lima)

## Benefícios

• Vale refeição
• 40% off nos produtos Liv Up (e refeições gratuitas para comer no escritório conforme disponibilidade)
• Vale transporte
• Auxílio a esportes (GymPass)
• Acesso à rede de descontos “Colaboradores” 
• Livros, cursos online, workshops internos e incentivo a eventos externos
• Ambiente informal, descontraído e acelerado
• Happy hours mensais

#### Diferenciais

• Startup em alto crescimento com gestão horizontal e ambiente cooperativo. Não só valorizamos sua opinião como esperamos que você construa a empresa com a gente!
• Autonomia & Responsabilidade
• Projeto de alto impacto em toda a cadeia de alimentos, dos clientes aos agricultores familiares parceiros
• Aprendizado rápido

## Requisitos

**Obrigatórios:**
- Motivação por grandes desafios
- Experiência com tecnologias web modernas
- Experiência com metodologias ágeis

**Desejáveis:**
- Conhecimentos em Node.js, React.js, MongoDB
- Perfil analítico

**Diferenciais:**
- Experiência prévia em startup
- PWA
- Server-side Rendering

## Como se candidatar

[Clique aqui para se candidatar](https://www.recrutasimples.com.br/vaga/software-engineer/sao-paulo-sp/-LM4tfblwRziMloQetS9)

## Labels

- Alocado
- CLT
- Pleno
- Sênior

**Comment by renatorib** [comment]
Tem outra maneira de se candidatar que não seja esse recrutasimples?

**Comment by renatorib** [comment]
A versão mobile dele é impraticável.

**Comment by andre0799** [comment]
Oi @renatorib, sou um dos co fundadores do Recruta Simples. A ideia é que esse fluxo nosso mobile ajudasse e não deixasse impraticável. Te mandei um email agora pra conseguirmos entender melhor. Obrigado!

**Comment by renatorib** [comment]
Opa @andre0799, 
Será um prazer poder dar meu feedback e poder ajudar vocês de alguma forma.
