### ISSUE TITLE
[Guaratinguetá] Front-End Developer na Romasoft Tecnologia

### ISSUE THREAD

**Issue by Raissafm** [frontendbr/vagas#1407]
## Descrição da vaga e da empresa

Somos uma empresa jovem que desenvolve soluções nas áreas jurídica e de RH. Prezamos por um bom ambiente de trabalho, onde nossos valores são: honestidade e liberdade! 
Estamos em busca de um programador front-end para desenvolver projetos e trabalhar em sistemas que já possuímos. 

## Local

Guaratinguetá - São Paulo

## Benefícios

- Plano de saúde nacional
- Plano odontologico
- Seguro coletivo por morte e invalidez
- Vale Refeição ou Alimentação
- Folga no dia do aniversário

## Requisitos

**Obrigatórios:**
- Bons conhecimentos em HTML5; CSS; JavaScript; JQuery

**Diferenciais:**
- Conhecimento em Angular JS
- Experiencia prévia

## Contratação

CLT

## Como se candidatar

Por favor envie um email para talent@romasofttecnologia.com.br com seu CV anexado - enviar no assunto: Vaga Programador Front-end

## Labels

- Alocado
- CLT
- Junior
- Pleno

**Comment by mtmr0x** [comment]
@Raissafm vocês estão procurando alguem com quais níveis de conhecimento? Coloque na área **Labels** se procuram *Júnior*, *Pleno* e/ou *Sênior* developers

**Comment by Raissafm** [comment]
ok

**Comment by heliomsolivas** [comment]
Enviado.

**Comment by gutocosta** [comment]
Enviado!

**Comment by Raissafm** [comment]
Vaga fechada! Encontrado fora do github.

**Comment by LFeh** [comment]
Valeu!
