### ISSUE TITLE
Front-End Developer Jr - São Paulo/SP

### ISSUE THREAD

**Issue by pablosoares** [frontendbr/vagas#1409]
## Descrição da vaga

Programar, desenvolver e implantar sistemas de JavaScript. Realizar correções em sistemas para atender às necessidades dos usuários e projetos. Desenvolver trabalhos de montagem, depuração, integrações e teste de programas. Suporte Técnico a Clientes. Ministrar treinamento e demonstração do produto. Pré-Venda.

## Local

Próximo ao Shopping Morumbi e Market Place – Zona Sul – São Paulo/SP

## Benefícios

- Plano de saúde
- Vale refeição
- Vale transporte

## Requisitos

Experiência com Javascript, HTML, e CSS, Frameworks e processos ERP. 
Conhecimentos: metodologias ágeis de desenvolvimento, banco de dados (SQL ou NoSQL), Base Unix (Linux ou Mac OS). Ensino Superior.

## Contratação

CLT

## Como se candidatar

Por favor envie um email para bruna.oliveira@pppro.com.br com seu CV anexado - enviar no assunto: Indicação - Pablo Soares - Desenvolvedor Front-End Jr

## Labels

- Alocado
- CLT
- Júnior

**Comment by mtmr0x** [comment]
@pablosoares poderia colocar nas labels os níveis de conhecimento? Coloque na área Labels se procuram Júnior, Pleno e/ou Sênior developers. Reabrimos assim que estiver atualizado. Só mandar um ok aqui pra mim que qualquer um dos admins vai ver

**Comment by pablosoares** [comment]
Opa! Prontinho :)

**Comment by biancamrqs** [comment]
Enviado.
