### ISSUE TITLE
[Poços de Caldas - MG] - Front-End Developer no ATELIÊ DE SOFTWARE

### ISSUE THREAD

**Issue by highlabs** [frontendbr/vagas#1412]
## Descrição da vaga

Estamos procurando pessoas desenvolvedoras de front-end para fazer parte do nosso time. Somos uma empresa de desenvolvimento web e nosso stack é basicamente React e Ruby on Rails. Não exigimos conhecimento avançado em nenhuma dessas tecnologias, basta querer aprender e será bem vindo. :) 

## Local

Poços de Caldas - MG (presencial apenas)

## Benefícios

- Plano de saúde (Unimed ou Climepe);
- Plano odontológico (Uniodonto ou Climepe);
- Seguro de vida;
- Vale refeição e/ou alimentação (+ou- R$ 400,00);
- Vale transporte (se necessário);
- Participação nos lucros e resultados de forma diferenciada;
- Horário e local de trabalho flexíveis (alinhado com a equipe);
- Liberdade para programar suas férias (alinhado com a equipe);
- Cartão do programa Descubra Descontos dos Poços CVB;
- SESC - 50% de desconto em hospedagem e diversas atividades;
- Ajuda de custo para participação em eventos (alinhado com a equipe);
- Ajuda de custo para cursos e compras de livros  (alinhado com a equipe);

## Diferenciais

- Happy hour com os coleguinhas
- Guloseimas sempre disponíveis
- Ambiente descontraído
- Gestão horizontal (todas as decisões são tomadas pela equipe, aqui ninguém é chefe de ninguém xD)
- Somos adeptos a métodos ágeis (XP, Pair Programming, Agile)

## Requisitos

**Obrigatórios:**
- HTML/CSS
- JavaScript

**Desejáveis:**
- React.js 
- JavaScript / ES6 / Webpack, etc..
- Ruby on Rails
- TDD

**Diferenciais:**
- Vivência em ambiente ágeis
- Boa comunicação (aqui conversamos muito entre nós e com o cliente)

## Contratação

CLT - Salário a partir de R$1859,00

O salário será definido pela equipe na contratação, dependendo do conhecimento do candidato. Como temos gestão horizontal, o seu salário sempre poderá ser negociável com a própria equipe (e não com um gestor que nunca te vê trabalhando xD).

## Nossa empresa

O Ateliê de Software faz parte do grupo Webgoal e atua no mercado brasileiro de software desde 2011. O nosso propósito é desenvolver software com alta qualidade técnica e rápido retorno sobre o investimento para os nossos clientes. Para isso, usamos Scrum para fazer a gestão ágil de projetos, práticas ágeis de engenharia de software da eXtreme Programming e Kanban para visualização e controle do fluxo de trabalho. Também utilizamos técnicas de Lean UX,  Design Thinking e Customer Development para criar produtos e novos negócios. Muito além da programação, também ajudamos nossos clientes na criação de estratégias de negócios e sua execução através da implementação de produtos digitais.

Conheça a gente:
[Instagram](https://www.instagram.com/atelie.software/)

## Como se candidatar

Basta preencher o formulário: http://atelie.software/vagas

## Labels

- Alocado
- CLT
- Júnior
- Pleno
- Sênior

**Comment by highlabs** [comment]
Pessoal, ainda temos vagas para front. Porém para não deixar uma vaga por muito tempo, vou fechar a issue. o/

**Comment by thedannyreis** [comment]
Tenho interesse! Como faço para participar?


Daniele Reis

Telefone: (71)982014718.

E-mail: reis-daniele@hotmail.com



________________________________
De: Daniel GrandeCastelo <notifications@github.com>
Enviado: segunda-feira, 1 de outubro de 2018 12:40
Para: frontendbr/vagas
Cc: Subscribed
Assunto: Re: [frontendbr/vagas] [Poços de Caldas - MG] - Front-End Developer no ATELIÊ DE SOFTWARE (#1412)


Pessoal, ainda temos vagas para front. Porém para não deixar uma vaga por muito tempo, vou fechar a issue. o/

**Comment by highlabs** [comment]
@thedannyreis A vaga é somente presencial, aqui em Poços de Caldas. Caso tenha interesse, basta usar o link disponível na descrição da vaga.

**Comment by analeticiasandy** [comment]
Olá!

A página para preencher o formulário não está disponível. A vaga ainda está disponível?
