### ISSUE TITLE
[São Paulo] Desenvolvedor Full Stack na [Resource]

### ISSUE THREAD

**Issue by POLLEZI** [frontendbr/vagas#1413]
Desenvolvedor Full Stack

## Empresa
Venha fazer parte do time de Inovação Digital da Resource, uma das maiores integradoras digitais do Brasil e uma as empresas de TI que mais crescem no País. Com 25 anos no mercado, multinacional brasileira com presença global, com 21 escritórios em 5 países.  

## Descrição da vaga:   
Experiência em ferramentas de versionamento , devops e virturalização (TFS, Git, Jenkins).Desenvolvimento e manipulação de APIs, frameworks de desenvolvimento mobile e/ou web, padrões de arquitetura, metodologias ágeis (frameworks, práticas, eventos e artefatos), Java, HTML 5 , CSS , JavaScript, TypeScript, Angular 2 e/ou 4, node JS, Webservice Rest / Soup, .NET, Git e gitflow. Conhecimento em práticas DevOps(ferramentas), Itil , WebServices(REST) e Micro serviços

## Contratação 
CLT FULL

## Benefícios
VR, VT, Convenio Médico, Convenio Odontológico, Auxilio Creche, Convenio Farmácia, Seguro de Vida

## Local: 
 Santo André -SP

## Como aplicar: 
Envie seu cv com pretensão salarial para adriana.pereira@resourceit.com ou indique um amigo!!!

## Labels

- Alocado
- CLT 
- Pleno
- Presencial
- Sênior

**Comment by diogomoretti** [comment]
@POLLEZI ficou zuado o markdown... favor arrumar.

**Comment by POLLEZI** [comment]
acho que agora deu certo :) tks!!!
