### ISSUE TITLE
FrontEnd Developer Senior  

### ISSUE THREAD

**Issue by Nathaliarba** [frontendbr/vagas#1414]
Responsibilities:

Develop new features for the e-commerce website and other solutions, such as:
Create new visual component
Production, modification, and maintenance of websites and web application user interfaces
Creating tools that enhance how users see and interact with your site in any browser
Consulting on SEO best practices
Testing the site during development for usability and fixing any bugs
Read and understand business and technical specifications to develop appropriate software solutions
Collaborate with the development team and other areas to enhance the software solutions and user experience

Our Technology Stack (in progress!):

PHP 7+
JavaScript (ES2015+)
Node.js
React (and Redux)
REST APIs and GraphQL
Docker
AWS platform (EC2, ECS, RDS, S3, SNS, SQS, Lambda, API Gateway, ElastiCache, CloudFront, Route53, ELB/ALB, Auto Scaling, Fargate, DynamoDB)
Microservices
Design Systems with Atomic Design
GIT
Continuous Integration (with Jenkins)
Atlassian platform (Jira, BitBucket)

Requirements:

Strong knowledge of JavaScript (ES2015+)
Solid knowledge of React (and Redux)
HTML5 and CSS
Webpack automations
Solid version-control knowledge (GIT), with pull requests and code review.
Good listening and written English skills

Nice to Have:

Knowledge of Node.js and Server Side Rendering approach
UX/UI best practices
Command-line Linux tools and unix server management (SSH, Crontab)
Continuous integration / delivery

Benefits:

Competitive salary with periodical performance reviews
Flexible working hours
Potential to work home office for a certain number of days per week
Opportunity to develop a career within a fast-growing company that is part of a large multinational group and with a very strong technical team
Access to the latest software technologies and cutting-edge tools
Opportunity to develop some software systems from the ground up

**Comment by diogomoretti** [comment]
@Nathaliarba Favor colocar no [nosso template](https://github.com/frontendbr/vagas/blob/master/.github/issue_template.md) e também informar o nome da empresa para que possamos reabrir a issue.
