### ISSUE TITLE
[FREELA] Front-End Developer (+Web Designer) na [BTCBolsa]

### ISSUE THREAD

**Issue by btcbolsa** [frontendbr/vagas#1415]
## Descrição da vaga

Precisamos de um front-end developer com experiência em web design, pois precisamos criar o layout do zero(iremos enviar páginas a serem copiadas) e integrar a API.

## Local

Freela remoto.

#### Diferenciais

- Probabilidade de contratação após término do trabalho

## Requisitos

**Obrigatórios:**
- Experiência com react
- Experiência com web design
- Capacidade de desenhar layouts através de conceitos
- Conhecimento sobre criptomoedas
- Boa comunicação (precisamos acompanhar o trabalho 2x no dia);

## Contratação

Freelancer / PJ

## Nossa empresa

A BTCBolsa é uma exchange que nasceu com o objetivo de facilitar a compra e venda de criptomoedas no Brasil.

## Como se candidatar

Por favor envie um email para trabalhe-conosco@btcbolsa.com com seu CV anexado - enviar no assunto: Vaga Front-end Developer

## Labels

- Freela
- Júnior
- PJ
- Pleno
- Remoto - Total
- Sênior

**Comment by btcbolsa** [comment]
Claro! O conhecimento sobre criptomoedas é essencial para que o dev entenda os fluxos da interface. Mas é necessário somente o básico: conhecimento sobre o que são pares, hashes, transferências etc.

**Comment by allancarlos123** [comment]
Tenho muito interesse e preencho os requisitos, só não tenho CNPJ pra trabalhar como PJ. Poderíamos pular essa burocracia e o pagamento ser feito em BTC? :)

**Comment by laugustofrontend** [comment]
enviado
