### ISSUE TITLE
[São Paulo] Dev Mobile para App Híbrido

### ISSUE THREAD

**Issue by rafaelcunha123** [frontendbr/vagas#142]
## Descrição da vaga

Desenvolvimento de app mobile híbrido utilizando Cordova (ou Phone Gap, ou Ionic, ou Meteor, etc). Desenvolverá o front-end do app utilizando um template em Angular. Dependendo da experiência do dev, poderá ser contratado para fazer a integração com a API também.
## Local

Remoto ou Alocado, São Paulo - Vila Mariana
(estar em São Paulo é diferencial)
## Benefícios
- Freela, pagamento por tela entregue e validada do app.
- Possibilidade de oferta para se juntar ao time fundador no fim do projeto.
## Requisitos

**Obrigatórios:**
- Desenvolvedor front-end sênior
- Experiência em HTML, CSS, Angular
- Experiência com LESS, SASS, Grunt e Gulp
- Facilidade no aprendizado de diferentes libs
- Experiência de integração de login com Auth0 (email, facebook e google)
- Experiência em captura de dados do device (geo-localização, utilização de features do teclado)

**Desejáveis:**
- Experiência com integrações com RESTful APIs
- Conhecimentos de Node.js
- Experiência com Redux
## Contratação

Freela, com pagamento por tela entregue e validada. Valor a combinar.
Dependendo de como o trabalho evoluir, possibilidade de oferta para se juntar ao time fundador da nossa empresa.
## Nossa empresa

Somos uma startup com o objetivo de revolucionar o mercado de saúde brasileiro.
## Como se candidatar

Por favor envie um email para rafael.cunha@edocsaude.com com:
1 - CV anexado
2 - Exemplos de apps live que tenha desenvolvido
3 - Contato de duas pessoas com quem já tenha trabalhado como freela anteriormente
4 - Enviar no assunto: Vaga Dev Front Mobile

**Comment by camilatigre** [comment]
@rafaelcunha123 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
