### ISSUE TITLE
[São Paulo] Front-End Developer Pleno/Senior in Printi

### ISSUE THREAD

**Issue by ericvasconcelos** [frontendbr/vagas#1421]
## Job description
- Develop new features for the e-commerce website and other solutions, such as:
Create new visual component
- Production, modification, and maintenance of websites and web application user interfaces
- Creating tools that enhance how users see and interact with your site in any browser
- Consulting on SEO best practices
- Testing the site during development for usability and fixing any bugs
- Read and understand business and technical specifications to develop appropriate software solutions
- Collaborate with the development team and other areas to enhance the software solutions and user experience

## Site
Pinheiros, SP 

## Benefits
- Competitive salary with periodical performance reviews
- Flexible working hours
- Potential to work home office for a certain number of days per week
- Opportunity to develop a career within a fast-growing company that is part of a large multinational group and with a very strong technical team
- Access to the latest software technologies and cutting-edge tools
- Opportunity to develop some software systems from the ground 

## Requirements
**Must to have:**
- Strong knowledge of JavaScript (ES2015+)
- Solid knowledge of React (and Redux)
- HTML5 and CSS
- Webpack automations
- Solid version-control knowledge (GIT), with pull requests and code review.
- Good listening and written English skills

**Nice to Have:**
- Knowledge of Node.js and Server Side Rendering approach
- UX/UI best practices
- Command-line Linux tools and unix server management (SSH, Crontab)
- Continuous integration / delivery

## Contract Type
CLT

## About Printi
Watch the video below to meet our company better =)
https://drive.google.com/file/d/1aZ8LtNAAlrtPV6xRMof6SfMeVzXQD6Y0/view?usp=sharing   

## How to apply
Please if you are interested send an email for nathalia.augusto@printi.com.br

## Labels
- Alocado
- CLT
- Pleno
- Sênior

**Comment by diogomoretti** [comment]
Favor colocar no nosso [modelo de template](https://github.com/frontendbr/vagas/blob/master/.github/issue_template.md) para que possamos reabrir a issue.

**Comment by ericvasconcelos** [comment]
@diogomoretti Prontinho meu amigo!
