### ISSUE TITLE
[São Paulo] Front-End Developer na LaPag

### ISSUE THREAD

**Issue by MarceloPrado** [frontendbr/vagas#1423]
## Descrição da vaga

Oportunidade para desenvolvedores que queiram participar de uma empresa em alto ritmo de crescimento. Buscamos resolvedores de problemas e pessoas com muita energia para participar das decisões internas da LaPag.

A vaga é para front-end do time de engenharia. Nosso maior desafio é escalar o produto mantendo uma qualidade excepcional para os usuários. Desenvolvedores que procuram espaço para criar um bom produto se darão muito bem nesta vaga. Nossos usuários são bastante exigentes 👌.  

Nossa **stack é React, Node.JS e MongoDB**, com um código bem organizado, testes automatizados e um time enxuto e ágil.

## Local

São Paulo - Brooklyn (escritório na Berrini, do lado da estação de trem)

## Benefícios

- A combinar com o candidato

#### Diferenciais

- participe de um dos momentos mais interessantes de uma startup (escalar o modelo e ganhar tração) 🚀
- ambiente jovem e descontraído
- muita liberdade para tomar decisões (stack, implementação, etc)
- rico ambiente de aprendizado
- liberdade para desbravar novas ideias e áreas (tem interesse em fullstack? quer testar um protótipo novo? Sem problema, vai lá e faz! ) 💥

## Requisitos

**Obrigatórios:**
- Sólida experiência em JS, HTML e CSS

**Desejáveis:**
- React JS ✨ ou outra framework
- ECMAScript 6 (ES6)

**Diferenciais:**
- Experiência em Redux
- React JS

## Contratação

PJ

## Nossa empresa

A [LaPag](https://www.lapag.com.br/) é uma fintech para salões de beleza, barbearias e studios de tattoo. Resolvemos um problema existente em todo o mercado de beleza: a informalidade desses negócios ([entenda mais](https://exame.abril.com.br/pme/ela-fez-brigadeiros-virarem-negocio-que-resolve-maior-problema-dos-saloes/)). Através da nossa maquininha de cartão e nosso software de gestão, conseguimos aumentar a lucratividade dos estabelecimentos em até 20%.

Fomos uma das cinco fintechs aceleradas pela [VISA](https://conteudo.startse.com.br/startups/taina/visa-anuncia-startups-selecionadas-para-programa-de-aceleracao/). Além disso, fomos **investidos pelo fundador da 99 táxi e o fundo Canary VC** ([notícia](https://startupi.com.br/2018/06/lapag-recebe-aporte-do-fundo-de-venture-capital-canary/)).

Estamos em um momento de crescimento muito acelerado, tanto do time como do produto. Por isso, esta é uma grande oportunidade para crescer junto com a gente. Todos que estiverem no barco surfarão nossa onda.

## Como se candidatar

Por favor, envie um email para marcelo@lapag.com.br com seu CV anexado e uma breve descrição (quem é você, o que gosta de fazer, por que se interessou pela vaga?)

## Labels

- Alocado
- PJ
- Pleno

**Comment by hugosoftdev** [comment]
Mandei meu Curriculum!!

**Comment by eduardotp1** [comment]
Enviado!

**Comment by ruhman** [comment]
Enviado!

**Comment by Lightclawjl** [comment]
Enviado!
