### ISSUE TITLE
São Paulo  - Front end Developer Senior na Consultoria Wtime

### ISSUE THREAD

**Issue by joycecarvalho25** [frontendbr/vagas#1429]
## Descrição da vaga
	Já ter trabalhado com:
	GitHub
	React / Redux / React Native
	ES6
	Angular / Angular JS
	Web Pack
	NPM
	Bootstrap
	Material Design
	AMP
	PWA
	Conhecer muito JavaScript, Typescript, HTML, CSS e SASS;
	Gostar de trabalhar com Agile, testes A/B, Single Page Applications e Selenium;
	Ter vontade de se atualizar o tempo todo e ajudar o time a fazer coisas novas.

## Local

Escritório, São Paulo - Campos Eliseos. 

**Diferenciais:**
- Ter atuado em projeto e-commerce 

## Contratação

PJ a combinar

## Nossa empresa

Aqui na Corporação ACME somos líderes em...

## Como se candidatar

Por favor envie um email para joyce.carvalho@wtime.com.br com seu CV anexado - enviar no assunto: Vaga Front end Developer

## Labels

![desenvolvedor front end](https://user-images.githubusercontent.com/37672921/46034492-25d4ba00-c0d7-11e8-989d-f18fa2a5bcc4.png)

**Comment by mtmr0x** [comment]
@joycecarvalho25 poderia adequar a vaga com o modelo da issue que aparece na própria issue ao criá-la? As labels são bem importantes de estarem aqui
