### ISSUE TITLE
[São Paulo] Full Stack Developer Junior na Gama Academy

### ISSUE THREAD

**Issue by VitorSavedra** [frontendbr/vagas#1432]
## Descrição da vaga

Nossos desafios hoje estão em garantir que cada indivíduo impactado por nós seja multiplicador dos valores que acreditamos, e através da tecnologia expandir nosso alcance para 1 milhões de pessoas.

Para alcançarmos esses objetivos, estamos a procura de Full Stack Developer Junior que tenha garra, fome de aprendizado e paixão por high tech.

Se você se considera um(a) fast learner e quer trabalhar com o que tem de mais novo no mercado de tecnologia, essa vaga é para você!

## Local

Escritório (com flexibilidade de horários) em Pinheiros - SP. 

## Benefícios

- Benefício mensal adicional de R$ 700 (VR+VT);
- Bônus anual equivalente a um mês de remuneração;
- Ajuda de custo para participação em cursos e eventos (R$600/por trimestre).

#### Diferenciais

- Flexibilidade para escolher a configuração da sua estação de trabalho;
- Local de trabalho pertinho do metrô Sumaré;
- Plano de crescimento e mentoria;
- Flexibilidade de horários.

## Requisitos

Inglês para leitura de documentações e cursos;

**Obrigatórios:**
- Flexibilidade para atuar em desenvolvimento back-end e front-end;
- Conhecimentos em NodeJS e Javascript (ES6);
- Conhecimentos em HTML5 e CSS3;
- Conhecimentos em SQL;
- Vivência em desenvolvimento ágil (Scrum);
- Cultura de melhoria iterativa e incremental.

**Diferenciais:**
- Conhecimentos em Ruby;
- Conhecimentos em TDD:
- Noções sobre Integração e Implantação Contínua;
- Noções sobre microsserviços;
- Noções sobre conteinerização;

## Contratação
- Regime de contratação PJ;
- Remuneração mensal no valor de R$ 2.300,00.

## Nossa empresa

A Gama Academy é uma empresa de tecnologia que utiliza a educação para formar e empregar talentos no mercado digital. Utilizamos nossa metodologia de ensino para atrair, selecionar e treinar profissionais nas áreas de desenvolvimento, design, marketing e vendas, conectando esses talentos a oportunidades de trabalho no mercado digital. A nossa missão é impactar 1 milhão de pessoas por meio da educação. 

## Como se candidatar

Basta preencher este form: http://bit.ly/vaga-gama-dev. \o

## Labels

- Alocado
- Júnior
- PJ

**Comment by praganavictor** [comment]
Enviado :)
