### ISSUE TITLE
[São Paulo] Front-End Developer na [OtimizeMe]

### ISSUE THREAD

**Issue by Ventuinha** [frontendbr/vagas#1433]
## Descrição da vaga

Estamos em busca de devs para fazer parte do nosso time imediatamente! A todo gás em um novo projeto e queremos você na equipe. Trabalhamos em um clima informal com foco em produtividade das tarefas, que em alguns casos são recompensadas com bônus $$$.

## Local

Escritório 
01243-002, Consolação - São Paulo, SP

## Requisitos

**Obrigatórios:**

- Grande conhecimento em HTML5, CSS3 e SASS
- Desenvolvimento com JavaScript Vanilla ES6+
- Conhecimentos sobre frameworks populares do mercado como React, Vue ou Angular
- Ter paciência de documentar o próprio código
- Boa vontade de compartilhar o que sabe

**Desejáveis:**

- Experiência com UX/UI
- Saber trabalhar com uso de boas práticas
- Conhecimento de Node.js
- Implementação de UI envolvam animação baseada em dados, SVG e Canvas

**Diferenciais:**

- Conhecimento em testes unitários com Jest, Mocha, Jasmine ou similares
- Possuir projetos pessoais

## Contratação

PJ a combinar

## Nossa empresa

Somos uma agência que atua em São Paulo e Rio de Janeiro. Trabalhamos com desenvolvimento de soluções ecommerce customizadas, marketing digital e também treinamentos.

## Como se candidatar

Por favor envie um email para contato@otimize.me com assunto: Vaga Frontend.
Anexe seu CV e opcionalmente, envie-nos seu perfil em sites que lhe apresentem(ex: trampos),  propriamente seu perfil no GitHub.

## Labels

- Alocado
- PJ
- Pleno
- Remoto - Parcial
- Sênior

**Comment by ribeiroevandro** [comment]
Enviado
