### ISSUE TITLE
[Remoto ou Rio de Janeiro]: Senior Front-End Developer no Personare

### ISSUE THREAD

**Issue by cauealvesbraz** [frontendbr/vagas#1439]
## Descrição da vaga

```javascript
Se você >>
    É uma pessoa, acima de tudo!
    É engajado(a) por Qualidade de Software
    Ama CODAR
    Curte a cultura de Ownership
    Compartilha conhecimento
    Ama CODAR
    Curte aprender, através de (treinamentos && cursos && eventos && livros)
    For receptivo(a) à feedbacks contínuos
    Ama CODAR
    Curte a cultura de DevOps
    Prefere metodologias ágeis
    Ama CODAR
>> Continue lendo...
```

Estamos começando a expandir os nossos times e precisamos de pessoas que realmente gostam de estar à frente do mercado, aquelas que curtem experimentar novas tecnologias e que estão sempre antenadas ao cenário atual do desenvolvimento front-end. A nossa missão é de criar equipes de ponta, que estejam engajadas em superar seus próprios desafios.

Um pouco das atribuições desse papel:
- Participar de times multidisciplinares
- Codificar :P 
- Participar de discussões sobre a evolução do time
- Participar de discussões de produto
- Decisões de arquitetura
- Definições de workflow

E se você se interessa em participar da migração de uma arquitetura monolítica para Headless ou no desenvolvimento de um novo produto, venha fazer parte do nosso time \o/

## Local

Alocado no escritório: Shopping Downtown - Barra da Tijuca - Rio de Janeiro - RJ

Ou Remoto - Parcial (a cada 3 meses você ficará 2 semanas na nossa sede no Rio de Janeiro)

*OBS: Se for 'Remoto - Parcial' os custos de passagem/hospedagem das viagens é por conta da empresa.*

## Benefícios

- Vale Refeição ou Vale Alimentação (cê que escolhe) de R$30,00/dia útil;
- Participação nos Lucros (Anual);
- Seguro de vida;
- Acesso às análises, cursos, jogos e serviços do Personare;

#### Diferenciais

- Cultura de Qualidade no workflow de desenvolvimento (TDD, DDD, Pair Programming, Code Review);
- Treinamentos com especialistas (internos ou externos);
- Material de suporte aos estudos (cursos, livros, etc);
- Incenvito à participação de eventos;
- Ciclo de feedback contínuo (Avaliação 360º, 1:1 meetings);

## Requisitos

**Obrigatórios:**
- Conhecimento em HTML5, CSS3 e JavaScript consolidado
- Curtir trabalhar em equipe
- Organização do CSS através de BEM, ITCSS ou SMACSS
- Interesse pelas temáticas do Personare
- JavaScript Design Patterns (Creational, Structural, Behavioral, Concurrency, Architectural)
- Semântica bem estruturada e código limpo
- Ser curioso(a) e estar sempre atento(a) às inovações da área
- React, React Router e Redux.
- Experiência com testes (Jest, Mocha, Chai)
- Pré-processador Stylus
- Experiência com Webpack
- Workflow do GitHub

**Desejáveis:**
- Experiência em aplicações de grande escala utilizando React com Server Side Rendering
- Conhecimento de operações básicas no Docker (run, stop, rm, kill, pull e push)

**Diferenciais:**
- Experiência com arquitetura Headless
- Técnicas de performance (code splitting, tree shaking)

## Contratação

CLT

## O Personare

<p align="center">
  <a href="https://www.personare.com.br/" target="_blank">
    <img src="https://user-images.githubusercontent.com/7065285/46258596-e249c980-c4a3-11e8-894c-14381df00fad.png" alt="Pesonare" width="70%">
  </a>
</p> 

O Personare é resultado do trabalho de jovens profissionais de diferentes especialidades, mas com uma mesma motivação: incentivar as pessoas a viverem suas vidas da melhor forma possível. Para isso, oferecemos conteúdos e serviços focados em qualidade de vida e autoconhecimento como: Astrologia, Tarot, Yoga, Meditação, Feng Shui e muitos outros.

Veja alguns bons motivos para se juntar a nós:

1. Influenciamos positivamente a vida de mais de um milhão e meio de pessoas que acessam o Personare todos os meses.

2. Aqui todos têm voz: prezamos que todas as opiniões e ideias sejam ouvidas. Até mesmo (e principalmente) as dos estagiários.

3. Nosso design e comunicação são feitos internamente. Você nunca vai ficar entediado trabalhando em uma empresa que é uma agência ao mesmo tempo.

4. Motivamos a amizade e a colaboração entre a equipe. Isso significa que todos têm boa vontade em explicar, ensinar, compartilhar tarefas e celebrar conquistas.

5. Agimos para que o bem-viver e o autoconhecimento não sejam um discurso somente. Praticamos o que pregamos: possuímos programas que incentivam que nossa equipe melhore sua própria qualidade de vida.

## Como se candidatar

Por favor me mande um sinal de fumaça através do email: queroserdev@personare.com.br com qualquer coisa (GitHub, Código, Projeto, se quiser marcar um café ou uma call)! \o/

OBS: Coloque o subject da seguinte forma **Senior Front-End Developer**

## Labels

- Alocado
- Remoto - Parcial
- Sênior
- CLT

**Comment by kivervinicius** [comment]
Quando for necessário ir para o Rio será custeado pela empresa? Caso for remoto

**Comment by ceasbz** [comment]
@kivervinicius Os custos de passagem/hospedagem são totais da empresa!

**Comment by dtfialho** [comment]
Enviado!

**Comment by ribeiroevandro** [comment]
Enviado, mesmo não sendo tão sênior como a vaga pede, ler o **Feedback 360** fez meus olhos brilharem e vai que rola... <3
