### ISSUE TITLE
[Rio Claro-SP ou Home Office] Desenvolvedor React / React Native

### ISSUE THREAD

**Issue by luxfactaTI** [frontendbr/vagas#144]
### Descrição da vaga

Temos vagas para Desenvolvedor Javascript - React/React Native. Necessária experiência profissional com desenvolvimento JavaScript, ECMAScript 6, REST APIs e habilidade para se adaptar a novas linguagens e tecnologias. Conhecimentos: React Native, Flux/Reflux/Redux, GraphQL, Immutable.js, Babel, Node.js, Programação Funcional, JSON, Promises. _Caso não tenha experiência com React, mas possua experiência com JavaScript e tenha interesse em aprender, candidate-se!_ Inglês avançado é um requisito (projetos internacionais).
## Local

Vagas presenciais (para início imediato) em Rio Claro - SP ou _Home Office_ para Seniores,
## Benefícios
- Assitência Médica (30%)
- Assistência Odontológica
- Vale Transporte
- Seguro de Vida Coletivo
- Vale Refeição (365,00$/mês)
## Requisitos

**Obrigatórios:**
- Experiência com React ou JavaScript avançado
- Interesse em aprender React
- Inglês avançado

**Desejáveis:**
- experiência com React Native
## Contratação

CLT
## Como se candidatar

Por favor envie um email para contatorh@luxfacta.com com seu CV anexado, resumo das experiências e pretensão salarial - enviar no assunto: Vaga ReactJS

**Comment by webofbits** [comment]
https://www.visualcv.com/ggixvyl0l88/pdf

**Comment by horaciosystem** [comment]
Olá, enviei email para vocês e não tive nenhum feedback.

**Comment by luxfactaTI** [comment]
Horácio, bom dia!

Desculpe não retornarmos, a vaga para React foi cancelada. Caso tenha interesse, deixe seu CV conosco, pois qualquer oportunidade podemos retornar contato.


Boa semana!


Atenciosamente,

Departamento de Recursos Humanos

 Luxfacta Soluções de TI - Brasil

 +55 11 3186-8341 R 6035 / 6037

 +55 19 3532-5340 R 6035 / 6037
www.luxfacta.com<http://www.luxfacta.com/>

Aviso legal: Esta mensagem, associada a quaisquer anexos, contendo informações da Luxfacta Soluções de TI e/ou suas subsidiárias, que pode ser propriedade confidencial e protegida legalmente. Sua intenção é apenas para o uso do indivíduo ou entidade endereçados nesta mensagem. Se você não for o destinatário desta mensagem, qualquer divulgação, copia, distribuição, ou ação tomada em relação a esta informação é estritamente proibida. Por favor nos notifique e destrua esta mensagem.

Aviso legal: Este mensaje de correo electrónico, junto con los archivos adjuntos, contiene información de Luxfacta Soluções de TI y/o sus filiales. Está destinado exclusivamente para el uso de la persona o entidad mencionada en este mensaje. Si usted no es el destinatario y ha recibido este mensaje por error, por favor notifique inmediatamente por correo electrónico de respuesta y luego bórrelo de su sistema.

Legal notice: This e-mail message, together with any attachments, contains information of Luxfacta Soluções de TI and/or its affiliates that may be confidential, proprietary copyrighted and/or legally privileged. It is intended solely for the use of the individual or entity named on this message. If you are not the intended recipient and have received this message by mistake, please notify us immediately by e-mail reply and then delete it from your system.



________________________________
De: Horacio Alexandre Fernandes <notifications@github.com>
Enviado: sexta-feira, 16 de junho de 2017 11:04
Para: frontendbr/vagas
Cc: Contato RH; State change
Assunto: Re: [frontendbr/vagas] [Rio Claro-SP ou Home Office] Desenvolvedor React / React Native (#144)


Olá, enviei email para vocês e não tive nenhum feedback.

**Comment by ygorlazaro** [comment]
@luxfactati bom dia! Essa vaga é somente para CLT? Eu tenho buscado vagas em PJ

**Comment by luxfactaTI** [comment]
Ygor, boa tarde!


As vagas de React no momento não estão abertas. Caso tenhamos oportunidades, voltamos a falar!


Atenciosamente,

Departamento de Recursos Humanos

 Luxfacta Soluções de TI - Brasil

 +55 11 3186-8341 R 6035 / 6037

 +55 19 3532-5340 R 6035 / 6037
www.luxfacta.com<http://www.luxfacta.com/>

Aviso legal: Esta mensagem, associada a quaisquer anexos, contendo informações da Luxfacta Soluções de TI e/ou suas subsidiárias, que pode ser propriedade confidencial e protegida legalmente. Sua intenção é apenas para o uso do indivíduo ou entidade endereçados nesta mensagem. Se você não for o destinatário desta mensagem, qualquer divulgação, copia, distribuição, ou ação tomada em relação a esta informação é estritamente proibida. Por favor nos notifique e destrua esta mensagem.

Aviso legal: Este mensaje de correo electrónico, junto con los archivos adjuntos, contiene información de Luxfacta Soluções de TI y/o sus filiales. Está destinado exclusivamente para el uso de la persona o entidad mencionada en este mensaje. Si usted no es el destinatario y ha recibido este mensaje por error, por favor notifique inmediatamente por correo electrónico de respuesta y luego bórrelo de su sistema.

Legal notice: This e-mail message, together with any attachments, contains information of Luxfacta Soluções de TI and/or its affiliates that may be confidential, proprietary copyrighted and/or legally privileged. It is intended solely for the use of the individual or entity named on this message. If you are not the intended recipient and have received this message by mistake, please notify us immediately by e-mail reply and then delete it from your system.



________________________________
De: Ygor Lazaro <notifications@github.com>
Enviado: segunda-feira, 19 de junho de 2017 12:14
Para: frontendbr/vagas
Cc: Contato RH; Mention
Assunto: Re: [frontendbr/vagas] [Rio Claro-SP ou Home Office] Desenvolvedor React / React Native (#144)


@luxfactaTI<https://github.com/luxfactati> bom dia! Essa vaga é somente para CLT? Eu tenho buscado vagas em PJ

**Comment by netojose** [comment]
Então fechem a issue :)
