### ISSUE TITLE
[São Paulo] Front-End Developer Júnior na Superare

### ISSUE THREAD

**Issue by superarelucas** [frontendbr/vagas#1440]
## Descrição da vaga

Estamos buscando Front-End Developers para atuarem em conjunto com a equipe, trazendo melhores resultados para grandes clientes como Claro / NET / Embratel.

Desenvolvemos diversos projetos, desde simples *landing pages*, até todo um fluxo para bots conversacionais, dashboards e etc.

## Local

Rua Francisco de Morais, 209 - Chácara Sto. Antônio, São Paulo / SP

## Benefícios

- VT
- VR de R$ 20,00/dia

## Requisitos

**Obrigatórios:**
- HTML5
- CSS3
- JavaScript / jQuery
- Bootstrap
- Adobe Photoshop

**Desejáveis:**
- Mínimo 1 ano de experiência como Front-End Developer
- Wordpress
- Gulp / Grunt

**Diferenciais:**
- Projetos open-source

## Contratação

**Modelo:** CLT
**Horário:** 9h30 às 18h30

## Nossa empresa

A Superare sempre olhou para o futuro com uma metodologia de trabalho bem definida: aqui, todo o processo é baseado em
resultados, sem achismos. Isso quer dizer que em tudo tem Analytics. Nada é planejado, criado e produzido sem que os resultados
sejam analisados em todas as etapas.

O retorno é o melhor que poderíamos ter: em pouco tempo de atuação, deixamos de ser apenas uma empresa de tecnologia para
atuarmos como agência digital, além de sermos uma das primeiras parceiras do Facebook (inclusive, fizemos o bot deles) e uma
das principais parceiras de gigantes mundiais como Google, Microsoft e Newspace.

Como conseguimos ir além em apenas 6 anos? Fazendo um constante esforço de inovação, criando produtos e estratégias focados
em resultados e usando a tecnologia para fazer a diferença na vida das empresas e das pessoas.

## Como se candidatar

Por favor envie um email para joao.romao@superare.co com seu CV anexado - enviar no assunto: [frontendbr] Front-End Developer - Superare

## Labels

- Alocado
- CLT
- Júnior

**Comment by renanssantos1** [comment]
Ola, a vaga ainda esta aberta?
