### ISSUE TITLE
[São Paulo] Front-End Developer Pleno na Superare

### ISSUE THREAD

**Issue by superarelucas** [frontendbr/vagas#1441]
## Descrição da vaga

Estamos buscando Front-End Developers para atuarem em conjunto com a equipe, trazendo melhores resultados para grandes clientes como Claro / NET / Embratel.

Desenvolvemos diversos projetos, desde simples *landing pages*, até todo um fluxo para bots conversacionais, dashboards e etc.

## Local

Rua Francisco de Morais, 209 - Chácara Sto. Antônio, São Paulo / SP

## Benefícios

- VT
- VR de R$ 20,00/dia

## Requisitos

**Obrigatórios:**
- HTML5
- SCSS / Sass
- JavaScript / jQuery (Vanilla é imprescindível)
- Consumo de REST API's
- Bootstrap
- Wordpress
- Algum pré-processador ou bundler (Ex.: Gulp ou Webpack)
- Adobe Photoshop

**Desejáveis:**
- Mínimo de 2 anos de experiência como Front-End Developer
- Conhecimento básico em algum framework como Angular, Vue ou React.
- Conhecimento básico em Node.js ou PHP

**Diferenciais:**
- Ter criado algum projeto utilizando Node + Express;
- Ter criado algum chatbot utilizando Dialogflow, LUIS ou Watson;
- Ter bibliotecas open-source ou publicadas no NPM.

## Contratação

**Modelo:** CLT
**Horário:** 9h30 às 18h30

## Nossa empresa

A Superare sempre olhou para o futuro com uma metodologia de trabalho bem definida: aqui, todo o processo é baseado em
resultados, sem achismos. Isso quer dizer que em tudo tem Analytics. Nada é planejado, criado e produzido sem que os resultados
sejam analisados em todas as etapas.

O retorno é o melhor que poderíamos ter: em pouco tempo de atuação, deixamos de ser apenas uma empresa de tecnologia para
atuarmos como agência digital, além de sermos uma das primeiras parceiras do Facebook (inclusive, fizemos o bot deles) e uma
das principais parceiras de gigantes mundiais como Google, Microsoft e Newspace.

Como conseguimos ir além em apenas 6 anos? Fazendo um constante esforço de inovação, criando produtos e estratégias focados
em resultados e usando a tecnologia para fazer a diferença na vida das empresas e das pessoas.

## Como se candidatar

Por favor envie um email para joao.romao@superare.co com seu CV anexado - enviar no assunto: [frontendbr] Front-End Developer Pleno - Superare

## Labels

- Alocado
- CLT
- Pleno

**Comment by matheus-rosin** [comment]
Remotooo
