### ISSUE TITLE
[Florianópolis] Front-End Developer na Exact Sales

### ISSUE THREAD

**Issue by pcfmello** [frontendbr/vagas#1445]
## Descrição da vaga

Desenvolver o Frontend de novas funcionalidades em ReactJS;
Manutenção em telas já existes;
Desenvolvimento de novas funcionalidades (muitas!).

## Local

Escritório, Florianópolis/SC - João Paulo

## Benefícios

- Pacote benefício de R$877 (sem desconto) que pode ser divididos em VR, VA, VT, plano de saúde, auxílio combustível etc;

#### Diferenciais
- Horário flexível;
- Bicicletário;
- Estacionamento;
- Chuveiros para banho pós pedal/academia etc;
- Banco de horas; 
- Sala de jogos e de descanso;
- Happy hour em quase todos os finais de semana

## Requisitos

**Obrigatórios:**
- Javascript (es6/7+);
- ReactJS (component lifecycle, setState, setState callback, props, immutability);
- Redux;
- Async Programming;
- Flexbox;
- GIT.

**Desejáveis:**
- Graduação/Pós Graduação ou cursos na área.
- Material UI
- Testes Unitários

**Diferenciais:**
- Conhecimentos em C#
- SQL Server
- Entity Framework

## Contratação

- 8 horas diárias / De segunda a sexta feira.
- CLT a combinar

## Nossa empresa

A Exact Sales oferece soluções para aceleração de vendas complexas B2B e redução de CAC, com metodologia própria e SaaS inovadores.

## Como se candidatar

Acesse o link https://exactsales.com.br/vaga/desenvolvedor-frontend e preencha o formulário que a equipe entrará em contato.

## Labels

- CLT
- Júnior
- Pleno
- Sênior

**Comment by Pedro-Souza** [comment]
Alocado?

**Comment by pcfmello** [comment]
Sim, presencial!

Em ter, 2 de out de 2018 14:44, Pedro Souza <notifications@github.com>
escreveu:
