### ISSUE TITLE
[São Paulo] Front-End Developer na VAGAS.COM

### ISSUE THREAD

**Issue by LucasdeCastro** [frontendbr/vagas#1446]
## Descrição da vaga

Projeto do Vagas.com em React

## Local

Escritório, São Paulo - Brooklin Novo 

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ 28/dia
- Auxílio creche
- Gympass
- Cesta de natal
- Convênio odontológico - MetLife

#### Diferenciais

- Café da Manhã
- Lanche da tarde
- Remoto Parcial
- Horário flexível
- Sala de jogos
- No dress code
- Ginástica laboral, quick massage e assessoria esportiva

## Requisitos

**Obrigatórios:**
 Reproduzir layouts com fidelidade;
- Ser proativo;

 **Vivência com:** 
- HTML, CSS, bibliotecas Javascript (heavy user);
- Frameworks Javascript MV*;
- Design responsivo;
- Frameworks de CSS;
- Algum CMS;
- Softwares de criação e edição de layouts;
- SEO, cross-browser e acessibilidade;
- Chamadas API Rest;
- GIT.

**Diferenciais:**
- projetos opensource

## Contratação

CLT a combinar

## Nossa empresa

Há 19 anos buscamos contribuir para que pessoas escolham melhor as empresas e empresas escolham melhor as pessoas, impactando positivamente no objetivo de cada um. Como? Através da tecnologia!

Como resultado, temos um sistema de currículos com aproximadamente 13 milhões de currículos, 74 das 100 maiores empresas do país contratando através das nossas soluções tecnológicas, além de inovações que auxiliam os candidatos ao longo de sua trajetória profissional, como o Mapa VAGAS de Carreiras, e um banco de dados do tamanho de 5 teras. Toda a conquista é feita através da vivência do modelo de gestão horizontal, que possibilita a liberdade, autonomia e responsabilidade no negócio, mas todos têm tudo a ver com isso.

## Como se candidatar

Por favor acesse aqui ou envie um email para [selecao@vagas.com.br](mailto:selecao@vagas.com.br) com seu CV anexado - enviar no assunto: Vaga Front-end Developer

## Labels

- Alocado
- CLT
- Júnior
- Pleno
- Remoto Parcial
- Sênior

**Comment by baltazarparra** [comment]
Em pleno 2018, ler isso na plataforma de vocês mesmos, é triste.


> A empresa requer o campo nível de escolaridade mínimo Formação superior (cursando)

**Comment by LucasdeCastro** [comment]
> Em pleno 2018, ler isso na plataforma de vocês mesmos, é triste.
> 
> > A empresa requer o campo nível de escolaridade mínimo Formação superior (cursando)

Cara, foi erro nosso, para você participar do nosso processo basta fazer esse teste

[Teste front-end vagas](https://static.vagas.com.br/RH/teste-de-front-end-VAGAS-v2.pdf)

**Comment by danielGalvao** [comment]
@adeonir Infelizmente ainda não, mas temos Home Office permitido alguns dias sim

**Comment by ribeiroevandro** [comment]
Farei o teste, apesar de mudar pra São Paulo não ser minha prioridade, o Home Office alguns dias se tornou bem interessante.

**Comment by baltazarparra** [comment]
> > Em pleno 2018, ler isso na plataforma de vocês mesmos, é triste.
> > > A empresa requer o campo nível de escolaridade mínimo Formação superior (cursando)
> 
> Cara, foi erro nosso, para você participar do nosso processo basta fazer esse teste
> 
> [Teste front-end vagas](https://static.vagas.com.br/RH/teste-de-front-end-VAGAS-v2.pdf)

Ah saquei, legal. Mas tinha pensando que era remoto total, uma pena também ser parcial.
Boa sorte no processo.
