### ISSUE TITLE
[Remoto] Front-End Developer na VAGALUME

### ISSUE THREAD

**Issue by lafraia** [frontendbr/vagas#1449]
## Descrição da vaga

Estou buscando profissionais que possam fazer parte de uma equipe remota para vários projetos no Vagalume. Já temos alguns projetos bem interessantes prontos para iniciar o desenvolvimento. O foco é encontrar pessoas **bem** proativas, autodidatas, auto-motivadas e que possam executar as tarefas com bastante paixão, rapidez e com qualidade técnica.

## Local

Totalmente REMOTO via Slack

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Javascript / jQuery (avançado)
- 3 anos de experiência com HTML5 e CSS3 (avançado)

**Desejáveis:**
- conhecimentos de SEO
- experiência anterior com trabalho remoto

## Contratação

PJ a combinar

## Nossa empresa

Você já deve ter buscado uma letra de música no Vagalume, chegou a hora de poder contribuir com o projeto ;-)

## Como se candidatar

Por favor envie um email para rh@vagalume.com.br com seu CV anexado - enviar no assunto: Vaga Front-End

## Labels

- Remoto - Total
- Freela
- PJ
- Pleno
- Sênior

**Comment by rodineicosta** [comment]
Enviado!

**Comment by lafraia** [comment]
@fabiosilvaacs Estou procurando pessoas confiáveis para trabalhar em vários projetos. ;-) Este específico de agora são dois meses, mas tenho vários outros projetos. Assim que encontrar as pessoas certas, teremos trabalhos constantes. É uma relação de confiança focado em projeto.

**Comment by RobertaMelo** [comment]
@lafraia Tem alguma vaga pra quem não atente o tempo de experiência?

**Comment by RobertaMelo** [comment]
@lafraia Que pena! Caso tenham interesse em passar coisas pequenas, até pra aprendizado eu tenho disponibilidade pra isso, não me importaria tanto com valores, apenas com aprendizado. De qualquer forma obrigada. =)

**Comment by lafraia** [comment]
@RobertaMelo Manda o CV para rh@vagalume.com.br, por favor

**Comment by RobertaMelo** [comment]
@lafraia mandei lá! Obrigada =)

**Comment by ribeiroevandro** [comment]
Enviado!

**Comment by laugustofrontend** [comment]
Enviado

**Comment by lafraia** [comment]
Para quem tiver interesse, abrimos novamente uma disponibilidade. Ver issue #2152. Obrigado! 🙏
