### ISSUE TITLE
[São Paulo] Senior Front-End Developer [Ali Crédito] 

### ISSUE THREAD

**Issue by Paulogrupe** [frontendbr/vagas#1452]
## Descrição da vaga
Construir do zero toda as plataformas (websites) onde nossos clientes, parceiros e time interno poderão ter contato com a plataforma de crédito da Ali Crédito. Serão desafios de todos os tipos: arquitetura, performance, segurança, usabilidade, etc. 

## Local: 
Escritório - São Paulo - Jardim Paulistano

## Benefícios:
Vale Transporte ou Estacionamento; 
Vale refeição de R$ 24,50/dia útil;
Aparelho celular e linha telefônica corporativa, para uso profissional;
Laptop

## Requisitos
Sólida experiência com o desenvolvimento de websites utilizando as tecnologias ReactJS, HTML, CSS e Javascript;
Sólidos conhecimentos com utilização de grids para diagramação de conteúdo (como, por exemplo, o Bootstrap);
Construção de websites responsivos para diversos tipos de device (desktop, celulares, tablets, etc.);

### Desejável/diferenciais:
Conhecimentos nas tecnologias React Native;

##Contratação
CLT

## Nossa empresa

Ali Crédito foi criada para fazer com que o cliente aproveite o crédito da melhor maneira: para realizar sonhos ou quitar dívidas do passado, com menor custo possível, sempre em linha com o momento da vida do cliente.

## Como se candidatar

Por favor envie um email para pg@individuals.io com seu CV anexado - enviar no assunto: Front-End

## Labels
Alocado
CLT
Senior

**Comment by mtmr0x** [comment]
@Paulogrupe poderia adequar a postagem com nosso modelo de issue apresentado na criação de uma issue, por favor?

https://github.com/frontendbr/vagas/blob/master/.github/issue_template.md

**Comment by Paulogrupe** [comment]
Olá Matheus


Fiz as alterações.

Você poderia me informar como faço (se é possível) publicar outras vagas que não seja de front-end.  Quando estava publicando minha vaga, havia alguns links para anunciar outros perfis. Você poderia me orientar como fazer isso.

A vaga que tenho agora é para desenvolvedor/programador.


abraços


Paulo


________________________________
De: Matheus Marsiglio <notifications@github.com>
Enviado: quinta-feira, 4 de outubro de 2018 07:29
Para: frontendbr/vagas
Cc: Paulogrupe; Mention
Assunto: Re: [frontendbr/vagas] [São Paulo] Senior Front-End Developer [Ali Crédito] (#1452)


@Paulogrupe<https://github.com/Paulogrupe> poderia adequar a postagem com nosso modelo de issue apresentado na criação de uma issue, por favor?

https://github.com/frontendbr/vagas/blob/master/.github/issue_template.md

**Comment by MateusGabi** [comment]
Bom dia, temos repositórios para Android, Backend, iOS/OSX e outros.

Você pode clicar no link abaixo, nele há uma lista.

link: https://github.com/frontendbr/vagas#outros-reposit%C3%B3rios-de-vagas

**Comment by mtmr0x** [comment]
@Paulogrupe as alterações não foram aplicadas ou não estão de acordo com o modelo.

**Comment by Paulogrupe** [comment]
Bom dia


Veja se agora está ok.


Paulo


________________________________
De: Matheus Marsiglio <notifications@github.com>
Enviado: sexta-feira, 5 de outubro de 2018 17:57
Para: frontendbr/vagas
Cc: Paulogrupe; Mention
Assunto: Re: [frontendbr/vagas] [São Paulo] Senior Front-End Developer [Ali Crédito] (#1452)


@Paulogrupe<https://github.com/Paulogrupe> as alterações não foram aplicadas ou não estão de acordo com o modelo.

**Comment by mtmr0x** [comment]
@Paulogrupe fiz uns ajustes de formatação entre título e corpo para facilitar leitura apenas e tá tudo certo. Reabri a issue. Obrigado pelos ajustes! :tada:

**Comment by Paulogrupe** [comment]
Ok, obrigado


________________________________
De: Matheus Marsiglio <notifications@github.com>
Enviado: segunda-feira, 8 de outubro de 2018 08:53
Para: frontendbr/vagas
Cc: Paulogrupe; Mention
Assunto: Re: [frontendbr/vagas] [São Paulo] Senior Front-End Developer [Ali Crédito] (#1452)


@Paulogrupe<https://github.com/Paulogrupe> fiz uns ajustes de formatação entre título e corpo para facilitar leitura apenas e tá tudo certo. Reabri a issue. Obrigado pelos ajustes! 🎉

**Comment by Paulogrupe** [comment]
Mateus


Tenho uma vaga de programador .Net Core. Onde eu posso divulgá-la, pois na lista não consta tal linguagem.


abraços


Paulo


________________________________
De: Mateus Gabi <notifications@github.com>
Enviado: sexta-feira, 5 de outubro de 2018 08:04
Para: frontendbr/vagas
Cc: Paulogrupe; Mention
Assunto: Re: [frontendbr/vagas] [São Paulo] Senior Front-End Developer [Ali Crédito] (#1452)


Bom dia, temos repositórios para Android, Backend, iOS/OSX e outros.

Você pode clicar no link abaixo, nele há uma lista.

link: https://github.com/frontendbr/vagas#outros-reposit%C3%B3rios-de-vagas

[https://avatars0.githubusercontent.com/u/16963863?s=400&v=4]<https://github.com/frontendbr/vagas#outros-reposit%C3%B3rios-de-vagas>

GitHub - frontendbr/vagas: Espaço para divulgação de vagas ...<https://github.com/frontendbr/vagas#outros-reposit%C3%B3rios-de-vagas>
github.com
1- Para evitar que possíveis candidatos enviem cvs para vagas já preenchidas, dê manutenção à sua issue, a cada 14 dias (2 semanas) coloque um comentário que continua procurando para a vaga ou feche a mesma comentando se a pessoa foi contratada através do nosso grupo ou por fora. Caso a ...
