### ISSUE TITLE
[São Paulo] Front-end Developer e mais vagas na Phurshell

### ISSUE THREAD

**Issue by clmadrazo** [frontendbr/vagas#1456]
## Vagas

Contrato mínimo de um ano, que pode ser renovável. Perfil sênior para todas as vagas. 
- Product Owner 
- Designer UI/UX 
- Desenvolvedor iOS 
- Analista QA 
- Desenvolvedor front-end (3 vagas) 
- 1 BI 
-  1 DBM

## Local

Escritório, São Paulo - Alphaville

## Contratação

PJ a combinar

## Nossa empresa

Somos uma agência especializada em desenvolvimento de aplicativos móveis e plataformas web.

## Como se candidatar

Por favor envie um email para gustavo@phurshell.com com seu CV anexado.

## Labels

- Alocado
- PJ
- Sênior

**Comment by gebittar** [comment]
Boaaa
