### ISSUE TITLE
[FLORIANÓPOLIS-SC] Desenvolvedor Front end na Sumá 

### ISSUE THREAD

**Issue by ferlintec** [frontendbr/vagas#1460]
##Descrição da vaga

Se você é aquele desenvolvedor que se interessa não só pelas linguagens da sua área, mas busca constantemente melhorar e ampliar seu leque de capacidades, extremamente preocupado com a melhor experiência do usuário, tanto em visual quanto em performance, então é você que procuramos!
Desenvolvimento de uma plataforma para gestão e comercialização(marketplace) de alimentos. A plataforma é disponibilizada para ambientes web e mobile.

##Aqui estão alguns itens para termos um bom alinhamento:
ReactJs
SCSS

##Outros pontos que seriam um diferencial:
-VueJS ou AngularJS
-ExpressJs
-NodeJS
-MongoDB

Contratação
Contrato como PJ
Remuneração a combinar
Carga horária 35 horas/semana

##Alocação

Trabalho home-office. Temos flexibilidade de horários, porém necessário estar presencialmente na sede em alguns dias da semana, a combinar.
Necessário o candidato residir em localidades próximas, devido aos encontros presenciais semanais.

##Nossa empresa
Sumá (www.appsuma.com.br) nasceu de um desejo de mudar e melhorar o equilíbrio de troca entre quem produz e quem consome alimentos originados diretamente do pequeno agricultor familiar. Buscamos, através de qualificação e comercialização justa e transparente por meio da tecnologia, trazer o reconhecimento e dignidade do trabalho no campo, de famílias que dedicam gerações ao cultivo no solo. Se você busca um ambiente extremamente motivado, desafiador, complexo, que está repensando o status quo do modelo de comercialização de alimentos, e com um propósito muito claro, junte-se a nós!

##Como se candidatar
Por favor envie um email para tec@appsuma.com.br com seu CV anexado - enviar no assunto: Vaga Front end

## Labels

- Alocado
- Júnior
- PJ
- Pleno
- Remoto - Parcial

**Comment by gustalimame** [comment]
Enviado
