### ISSUE TITLE
[REMOTO] Front-End Developer na Santa I/O

### ISSUE THREAD

**Issue by scarpelini** [frontendbr/vagas#1462]
## Descrição da vaga

We're looking for Front-end Developers for a Remote Freelance(long-term) position at SOLID. The developer needs to have strong experience with CSS3 and deep knowledge with Javascript. With that, you can create any custom experience for web and mobile. If you're this person, please, send to us your information and let's talk.

PS: YOU NEED TO BE PASSIONATE ABOUT DESIGN, UX AND MOTION.

## Local
Remote Position

## Requisitos

**Obrigatórios:**
- 4+ years of experience with Javascript
- Advanced HTML & CSS3
- Webpack
- Git

**Desejáveis:**
- Advanced Javascript
- ReactJS
- React Native
- SEO Knowledge
- English Intermediate/Advanced

**Diferenciais:**
- PASSIONATE ABOUT DESIGN, UX AND MOTION.
- Keep studying and improving skills 
- Pro-active and self-management person

## Contratação
Position for initially **3 months** with the possibility of a long-term relationship for new projects.
PJ R$5.000,00-6.000,00 (it depends on the level experience).

## Nossa empresa
**Santa I/O** - https://www.santa.io is a design and tech company focused on creating digital experiences by crafting custom solutions. We're part of **SOLID** - https://www.solidsolutions.io, a global design, and tech consultancy company. We love great and beautiful experiences.

## Como se candidatar
Please, fill this form: https://goo.gl/forms/ezDI2BGXNJBPgR6I3

## Labels
- Freela
- PJ
- Pleno
- Remoto - Total
- Sênior

**Comment by laugustofrontend** [comment]
enviado

**Comment by RicardoWEBSiTE** [comment]
Enviado

**Comment by anjumdar7864** [comment]
interested.
