### ISSUE TITLE
[SÃO PAULO] Front-end Developer JR na WeJam

### ISSUE THREAD

**Issue by crispossa** [frontendbr/vagas#1463]
### Descrição da vaga
Você vai ser responsável por corrigir bugs de layout e compatibilidade em projetos que já estão online e desenvolver novas interfaces do zero utilizando HTML e CSS.
Os seus entregáveis serão sempre em HTML/CSS e em alguns casos, integrados diretamente no Laravel e Wordpress.
Além disso, vc vai fazer checagens cross-browser e garantir a qualidade do produto final.
Trabalhamos com layouts complexos e desafiantes, por isso vc precisa ter pensamento "fora da caixa" para resolver problemas complexos com soluções simples e criativas.

### Requisitos

- 1 ano de experiência comprovada com HTML/CSS
- Pre-processadores CSS LESS ou SASS
- Domínio de codificação HTML semântica
- Experiência com GIT
- Conseguir usar o Google/StackOverflow para encontrar soluções para problemas simples por conta própria

### Desejáveis

- Conhecimento em JS básico
- Experiência com integração com Wordpress e Laravel
- Bom gosto para User Experience e User Interface

### Contratação
PJ a combinar

### Sobre a WeJam

Somos uma agência com uma proposta diferente. Não apenas executamos jobs, mas criamos envolvimento com nossos clientes e projetos.
Participamos desde a concepção do projeto até sua publicação numa filosofia ponta-a-ponta, onde planejamos, construímos e desenvolvemos ideias incríveis.
Desenvolvemos sistemas únicos e realmente desafiantes, além de campanhas publicitárias inteiras que impactam clientes finais em diversas mídias.
Venha fazer parte da nossa equipe!
We Ad! We Rock! We Jam!

### Localização

Rua Raposo Tavares, 116 - Jardim das Acácias - São Paulo

### Como se candidatar

Envie para o e-mail queroserdev@wejam.email as seguintes informações:

- Seu CV.
- Link do Github se tiver.
- Uma breve descritivo dos últimos projetos que vc participou e qual a sua participação.
- Os desafios que vc encontrou recentemente e como os resolveu.
- Sua pretensão salarial.

**Comment by MayaraRMA** [comment]
Aceita Remoto?

**Comment by crispossa** [comment]
> Aceita Remoto?

Envie seu CV. Essa vaga é presencial, mas temos vagas para remoto também.

**Comment by gabrigcl** [comment]
Enviarei meu currículo, com pretensão para vaga remota também

**Comment by lzhudson** [comment]
Enviei o e-mail para vaga remota

**Comment by renanfgs** [comment]
Ainda está aberta?
