### ISSUE TITLE
[Porto Alegre - RS] Front-End Developer HTML/CSS/JS na BODE

### ISSUE THREAD

**Issue by pbridi** [frontendbr/vagas#1466]
A Bode é uma empresa de desenvolvimento de software que está tocando o terror desde 2013. Somos especialistas em criar Sites, Sistemas, Aplicativos e Dashboards. 
Estamos buscando uma pessoa desenvolvedora Front-end! Se você manja de HTML, CSS, Javascript e curte tecnologias web em geral: chama a gente :)

## Local
Porto Alegre - Av. Cel Lucas de Oliveira, 894 - Area 51

## O que levamos em conta?

- Se você discute velocidade de processador, discute cor de computador nem tente aplicar;
- Se você curte discussões intermináveis, não rola;
- Se você gosta de coca-cola, vem!
- Ser tamo junto (impossível explicar sem uma conversa olho no olho).

## O que prometemos?

- Ser sempre transparentes e diretos. Isso faz parte e é bom pra todo mundo;
- Ambiente no melhor conjunto de empresas de Porto Alegre;
- Oportunidade de crescimento junto com a empresa;
- Frigobar sempre cheio;

## Requisitos:

- CSS
- HTML
- JS
- jQuery
- Bootstrap
- Layout Responsivo
- GIT

## Desejáveis:

- SEO e Open Graph
- Python 
- Django

## Contratação:
CLT, com salário a combinar

## Como se candidatar?
Envie um email para contato@bode.io com:
- Seu CV anexado
- (Opcional, mas ganha estrelinha)Vídeo de até 2 minutos contando um pouquinho mais sobre você 
- Pretensão salarial
- Enviar no assunto: Vaga Front End na Bode

## Labels
- Alocado
- CLT
- Pleno
- Sênior

**Comment by DouglasRenato** [comment]
Bora de remoto?

**Comment by pbridi** [comment]
> Bora de remoto?

Falaaaa Douglas! Remoto fica um pooouco mais difícil no momento. Estamos priorizando alocado por enquanto :) 
Quando rolar alguma vaga remota, pode deixar que a gente avisa!
