### ISSUE TITLE
[Remoto Freelancer] Front-End Developer na Individuals

### ISSUE THREAD

**Issue by Andreia-Marques** [frontendbr/vagas#1467]
## Descrição da vaga
      Buscamos desenvolvedores Front-end para trabalhar como freelancers em diferentes projetos e com uma equipe de desenvolvedores globalizada, para trabalhar no desenvolvimentos de aplicações web e móveis.

## Local
Remoto 

#### Diferenciais
       - Metodologia de desenvolvimento que permite fracionar os projetos em pequenos entregáveis e que se ajusta a disponibilidade de cada desenvolvedor;
      
## Requisitos
         - Sólida experiência (mínimo de 3 anos) com o desenvolvimento de websites utilizando as tecnologias ReactJS, HTML, CSS e Javascript;
	- Sólidos conhecimentos com utilização de grids para diagramação de conteúdo (como, por exemplo, o Bootstrap);
	- Construção de websites responsivos para diversos tipos de device (desktop, celulares, tablets, etc.);

**Desejáveis:**
	- Conhecimentos nas tecnologias React Native;

**Diferenciais:**
         - Que respire o mundo de tecnologia e estude continuamente
         - Pessoa auto-gerenciável e pró-ativa
         - Que busque o incrível como resultado de seu trabalho

## Contratação

PJ a combinar

## Nossa empresa

Em cada novo projeto, processo de desenvolvimento de software e a engenharia de sistemas deveriam ser completamente diferentes: com diferentes restrições de investimento, estágios de maturidade do negócio e metas de mercado. Entendemos isso porque somos ex-CTOs, consultores e investidores de muitas startups. Então, criamos a Individuals para ter uma resposta final para os problemas de cada cliente. 
Nossa metodologia se aprofunda nas necessidades do negócio de cada empresa, antes de começarmos a codificar. Dessa forma obtemos uma compreensão empática sobre os problemas enfrentados antes de resolvê-lo que, somada a uma documentação técnica de qualidade, promove a formulação de uma solução inovadora.

## Como se candidatar

Por favor envie um email para am@individuals.io  com seu CV anexado - enviar no assunto: [Remoto Freelancer] Front-End Developer na Individuals

## Labels

- Remoto
- PJ
- Freela
- Pleno
- Sênior

**Comment by ribeiroevandro** [comment]
Enviado!

**Comment by SunTzu92** [comment]
Enviado
