### ISSUE TITLE
[Londrina] Front-End Developer na [DROOPI]

### ISSUE THREAD

**Issue by agenciadroopi** [frontendbr/vagas#1468]
## Descrição da vaga

Necessário ter domínio de suas ferramentas:
JS, CSS, HTML5, Bootstrap.
Conhecimento em Magento é desejável;
Contrato por projeto.

## Local

Remoto ou Escritório, Londrina, Gleba Palhano

## Benefícios

- Pagamento por projeto.
- Horário flexível

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com JS, HTML, CSS

**Desejáveis:**
- conhecimentos na estrutura do Magento, apenas front, e JS

**Diferenciais:**
- projetos opensource

## Contratação

Por projeto ou PJ a combinar

## Nossa empresa

Agência digital com 6 anos de mercado em Londrina PR, atendendo projetos de todo o BR

## Como se candidatar

Por favor envie um email para rh@droopi.com.br com seu CV anexado - enviar no assunto: Vaga Front

## Labels

- Alocado
- CLT
- Estágio
- Freela
- PJ
- Pleno
- Remoto
- Sênior

**Comment by raloliver** [comment]
Enviado.

**Comment by vitroz** [comment]
Enviado.

**Comment by lzhudson** [comment]
Enviado

**Comment by ribeiroevandro** [comment]
Enviado.

**Comment by laugustofrontend** [comment]
Enviado

**Comment by alessandroprudencio** [comment]
que vença o melhor
