### ISSUE TITLE
[São Paulo] Desenvolvedor Front End

### ISSUE THREAD

**Issue by aldo-jr** [frontendbr/vagas#147]
## Descrição da vaga

Vaga para PJ. Trabalhar com um sistema único, front-end com Angular.js
## Local

Escritório, São Paulo - Vila Olímpia
## Benefícios
- horário flexível
## Requisitos

**Obrigatórios:**
- Experiência com HTML
- Experiência com CSS
- Experiência com JavaScript
- Experiência com Angular.js

**Desejáveis:**
- Conhecimento em Node.js
- Conhecimento em Grunt e/ou Gulp
- Conhecimento de pré-processadores de CSS
## Contratação

PJ a combinar
## Nossa empresa

Empresa com um produto para suporte, sistema feito em angular.js consumind uma API em Java.
## Como se candidatar

Por favor envie um email para ajunior@inext.com.br com seu CV anexado - enviar no assunto: Vaga AngularJs

**Comment by LFeh** [comment]
Junior, Pleno ou Senior?
