### ISSUE TITLE
[Recife] Front-End Developer na Arpotalent

### ISSUE THREAD

**Issue by Andreia-Marques** [frontendbr/vagas#1470]
## Descrição da vaga

Buscamos profissionais com mobilidade, para empresa multinacional de grande porte em Recife-PE

## Local

Local

## Benefícios

- Pacote de contratação Atrativo

#### Diferenciais
- Conhecimentos em HTML, CSS e JavaScript
- Experiência com Angular, React ou Vue.js
- Integração com REST APIs
Boas práticas de otimização de mecanismo de busca (SEO)
## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para  com seu CV ou LinkedIn para luciana.polli@arpotalent.com.br - enviar no assunto: Desenvolvedor Front-End, com Pretensão Salarial

## Labels

- Alocado
- CLT
- Júnior
- Pleno
- Sênior

**Comment by mouraggui** [comment]
Olá! Quando tento enviar um email paracontado@arpotalent.com.br recebo uma mensagem informando que o email não existe ou não pode receber mensagens.

**Comment by twtreact** [comment]
Boa tarde! Quando tento enviar um email para contado@arpotalent.com.br, sou informado que o email não existe ou não está disponível para receber mensagens.

**Comment by fejaum** [comment]
> Boa tarde! Quando tento enviar um email para [contado@arpotalent.com.br](mailto:contado@arpotalent.com.br), sou informado que o email não existe ou não está disponível para receber mensagens.

Deve ser contato@arpotalent.com.br

**Comment by Andreia-Marques** [comment]
luciana.polli@arpotalent.com.br
