### ISSUE TITLE
[São Paulo] Front-end Developer (REACT) em [Uma das maiores Startups do Brasil]

### ISSUE THREAD

**Issue by rbcrogerio** [frontendbr/vagas#1472]
[São Paulo] Front-end Developer (REACT) em [Uma das maiores Startups do Brasil]

Imprescindível ampla experiência em análise e desenvolvimento com React/Redux
Imprescindível ampla experiência em outras linguagens de frontend.

## Sobre nosso cliente:

Uma das maiores startups do Brasil que já recebeu diversos investimentos além de um grande crescimento nos últimos anos.

## Descrição do cargo:

*Colaborar com todo o processo de desenvolvimento de software: desenvolvendo, revisando e mantendo código eficiente, e buscando a mais alta qualidade;
*Resolver desafios de usabilidade, criar componentes reutilizáveis e contribuir para um código bem estruturado e de alto desempenho.
*Evoluir o modelo de desenvolvimento de software para um modelo de novas tecnologias e métodos de ponta para lidar com sistemas distribuídos e integrados.

## Local:

São Paulo - SP

## Requisitos:

**Obrigatórios:**

- React.js

**Desejáveis:**

- Javascript
- Redux
- Node.js
- HTML
- CSS
- PWA
- React Native

## Remuneração e Benefícios:

de R$ 8.000,00 a R$ 12.000,00 CLT + beneficios de praxe

## Como se candidatar:

Por favor acesse o link https://www.pagepersonnel.com.br/job-detail/front-end-developer-react/ref/169915 e candidate-se na vaga em questão ou envie um email para rogeriocouto@pagepersonnel.com.br com os seus contatos.

## Labels:

Alocado
CLT
Sênior
React
Frontend

**Comment by diogomoretti** [comment]
Olá @rbcrogerio, favor colocar o nome da empresa no titulo para que possamos reabrir a issue!
