### ISSUE TITLE
[REMOTO] VUEjs Developer na VoceAzul.com

### ISSUE THREAD

**Issue by tuliovargas** [frontendbr/vagas#1473]
## Descrição da vaga
Buscamos desenvolvedor front-end com experiência em VueJs.

## Local
Remoto

## Contratação
PJ a combinar

## Como se candidatar
Por favor envie um email para **contato@voceazul.com.br**
Assunto: [Vaga VUEjs] - Seu_Nome

Informar no Corpo do email
::.VueJS
- Quantos projetos e anos de experiência;
- Vue CLI;
- Vue 2;
- Vue Router;
- Vuex e SPA(Single Page Application);
- Redux;

::.Valor Hora: 
::.Quantas horas semanais disponíveis: 
::.Portifólio ou Git: 
::. WhatsApp:  

## Labels
- Freela
- PJ
- Pleno
- Sênior
- Remoto - Total

**Comment by ferreirabh** [comment]
Currículo enviado.

**Comment by brunokunace** [comment]
@tuliovargas Esta vaga ainda está disponível?
