### ISSUE TITLE
[São Paulo] Desenvolvedor Full Stack/Front-end

### ISSUE THREAD

**Issue by danjesus** [frontendbr/vagas#148]
## Descrição da vaga

Densevolvedor Full Stack com foco em frontend.
## Local

O escritório fica em pinheiros próximo a praça Benedito Calixto, São Paulo, Capital.
## Remuneração e Benefícios
- Remuneração em linha com o mercado.
- Os benefícios de praxe (transporte alimentação) estão incluídos
- Ambiente é realmente bem legal, temos uma série de eventos internos, como palestras de pessoas de renome no mercado, sessões de informação sobre alguns temas lideradas pelos próprios colaboradores entre outras.
## O que oferecemos
- Espaço, estímulo e suporte para se desenvolver e crescer de forma meteórica
- Aprendizado constante
- Interação com outras startups (Bee Cambio, Singu, Easycarros, ChoppUP) da venture builder eGenius (grupo do qual fazemos parte)
- Contato direto com grandes empreendedores
- Oportunidade de contribuir efetivamente para a evolução de uma start-up em crescimento acelerado (aqui, suas ações e opiniões podem causar grandes impactos)
- Ambiente descontraído e dinâmico
## Requisitos
- Sólidos conhecimentos de lógica de programação, orientação a objetos e design patterns
- Sólidos conhecimentos em HTML/CSS e boas práticas como SMACSS, BEM, OOCSS, de pré-processadores como SASS, LESS e Stylus;
- Conhecimento em aplicações web mobile usando layouts adaptativos/responsivos
- Experiência na utilização de frameworks JavaScript MVC (AngularJS, ReactJS, VueJS)
- Experiência com API Rest
- Conhecimento de boas práticas de SEO

**Desejáveis**
- Experiência com testes unitários em js (Mocha, Protractor, Jasmine...)
- Conhecimentos com ferramentas automação de tarefas ( gulp, grunt, webpack…)

**Diferenciais:**
- Ter projetos opensource publicados
- Sólidos conhecimentos em OO, Funcional, TDD
- Profundos conhecimentos de GIT
- Conhecer bem bancos de dados relacionais (MySQL, Postgres)
## Contratação

PJ à combinar
## Sobre a F(x)

A F(x) é uma empresa jovem, fundada em 2015 para resolver o problema de crédito de  empresas médias e grandes no Brasil. Usamos a experiência de 10+ anos no setor financeiro e de mais 10+ em desenvolvimentos de produtos e de construção de empresas baseadas em internet e marketplaces.

Oferecemos às empresas clientes o acesso diferenciado a uma rede de financiadores alternativos para busca de crédito estruturado, além de ferramentas que otimizam as condições dos créditos liberados, trazendo benefício imediato tanto às empresas quanto aos financiadores.

   Queremos encontrar uma desenvolvedor que, assim como a gente, tenham um perfil ousado e empreendedor: gente ligada em tecnologia, com brilho nos olhos e que goste de evoluir com novas experiências, que queira construir produtos e soluções incríveis. Uma pessoa que seja antenada no mercado de fintechs.

   Para isso temos um nível de exigência alto com qualidade e buscamos um FullStack capaz de construir uma plataforma robusta e escalável para sustentar o crescimento da empresa.
## Sobre a eGenius Founders

Participamos ativamente de todas as etapas do processo de criação e desenvolvimento de novos negócios, envolvendo concepção, estruturação do modelo de negócios, processos operacionais, captação de recursos, vendas e desenvolvimento de produtos / tecnologia.
Nossa equipe é formada por Fundadores e CEOs de grandes startups do mercado brasileiro como Easy Taxi, Zocprint, Helpling; forte experiência no setor financeiro e de consultoria em empresas de renome como McKinsey, JP Morgan, Credit Suisse, M Square; vindos das melhores universidades no Brasil e no Exterior como Wharton Business School, University of Chicago, Stanford, USP, Unicamp e UFSC.
Acreditamos que valor é criado através de inteligência, pró-atividade, espírito empreendedor, capacidade de execução e meritocracia pura. Contratamos apenas pessoas com potencial para serem nossos sócios e que estejam dispostos a integrar um time que visa trabalhar junto no longo prazo e atingir grandes realizações.
## Como se candidatar

Mande seu CV para ti@fdex.com.br, com o título “Vaga para FullStack na F(x) - FrontEndBr”.

**Comment by danjesus** [comment]
Pessoal, ainda estamos com a vaga em aberto, a F(x) é um lugar sensacional para se trabalhar, nós estamos construindo coisas bem legais, então quem tiver afim de trabalhar numa startup bacana, e em um time com um excelente nível só mandar o currículo 😄

**Comment by Marlysson** [comment]
Uma vaga dessa ainda não teve selecionados?

**Comment by LFeh** [comment]
Vagona mesmo.

**Comment by JCMais** [comment]
Não há nenhuma possibilidade de remoto?

**Comment by danjesus** [comment]
Pessoal a vaga é pra trabalho aqui local, mas mandem os currículos pra darmos uma olhada.
Ainda não fechamos a vaga, temos pelo menos 3 vagas em aberto só aqui na F(x).

**Comment by niltoncsr** [comment]
Que pena não ter remoto, e respeito a posição da empresa porém acho que a
administração poderia pensar daqui pra frente nessa possibilidade... Já
teriam fechado a vaga há tempos, tenho certeza :)
Boa sorte no processo! :D





*Nilton*


Em 24 de janeiro de 2017 18:09, Dan Jesus <notifications@github.com>
escreveu:

**Comment by danjesus** [comment]
Pessoal vaga preenchida!  E preechemos mais uma vaga com outro canditado que veio daqui do frontendbr. Muito bom! Agradeço a todos!

**Comment by LFeh** [comment]
Aee carario.

Muito bom @danjesus!

**Comment by eduardojmatos** [comment]
@danjesus WOW! Que maravilha!!
