### ISSUE TITLE
VAGA INVALIDA

### ISSUE THREAD

**Issue by fsrocha-dev** [frontendbr/vagas#1482]
REMOVIDA A PEDIDO DO AUTOR

**Comment by ribeiroevandro** [comment]
Irão usar o Weex?

**Comment by fsrocha-dev** [comment]
Quasar Framework

**Comment by baltazarparra** [comment]
**_Salário inicial R$ 1500,00_**

esse valor está correto?

**Comment by sdq-sts** [comment]
> **_Salário inicial R$ 1500,00_**
> 
> esse valor está correto?

E isso sendo 1500 sem nenhum "benefício" da CLT, o pessoal tenta fugir da mão do governo e cai em uma armadilha dessa, uma pena.

**Comment by fsrocha-dev** [comment]
Esse valor é inicial! até pq a vaga é para Júnior. E o regime de contratação é PJ

**Comment by DanielLCintra** [comment]
@fsrocha-dev com todo respeito, não estou aqui pra ofender ninguém. Já vi vagas para nível Júnior pagando R$3000 CLT. Então concordo com os meus amigos que reclamaram, isso ai é prostituir a nossa profissão. Acho que o mínimo nesse caso seria o contrato ser de meio período, para que a pessoa que for contratada possa trabalhar em outro projeto simultaneamente e conseguir ganhar um valor razoável, isso ai tá perto de um salário mínimo, que sub-empregos oferecem. (Nada contra quem trabalha em sub-empregos, o que eu quis dizer é que sub-emprego não exige especialização, um trabalho de desenvolvedor exige, por mais que seja nível Júnior, o profissional não vai chegar 100% crú).

**Comment by Pedro-Souza** [comment]
Júnior com 3 anos de xp?

**Comment by JeanGoncalves** [comment]
> Esse valor é inicial! até pq a vaga é para Júnior. E o regime de contratação é PJ

Legal né, mas vamos lá aos cálculos **por alto** (_Pode ser que não estejam corretos_):

_Alimentação (± R$ 15,00/dia)_    R$ -300,00
_Plano de saúde_                  R$ -300,00
_MEI_                             R$ -52,60
_Depreciação do Maquinário_       R$ -200,00
_Salário_                         R$+1500,00
---------------------------------------------
_Total_                           R$ 647,40

**Comment by fsrocha-dev** [comment]
Galera, só estou compartilhando a pedido da empresa! sou apenas funcionário! não estou dizendo que concordo, mas estou a serviço da empresa. Sei que o valor é baixo realmente.

**Comment by fernandoocf** [comment]
Repassa pra pessoa da sua empresa essa informação:

**Júnior**: cargo com complexidade menor de tarefas, sem tantas exigências de competências profissionais e normalmente sem autonomia para decisões;

**Pleno**: complexidade maior de tarefas, maior maturidade profissional e capacidade ampla de tomada de decisões;

**Sênior**: ampla complexidade de tarefas, exigência de maturidade profissional e emocional, poder de decisão e capacidade para assumir funções de liderança.

Fonte: https://www.vagas.com.br/profissoes/acontece/no-mercado/voce-e-junior-pleno-ou-senior/

**Comment by ribeiroevandro** [comment]
> Quasar Framework
Fora o que já foi citado em termos de valores acima, o **Quasar** pra mim é o mesmo que Ionic ou similares, não vejo tantos benefícios nele... Na linha de apps híbridas, prefiro React Native ou Weex que é o equivalente para VueJS, enfim, boa sorte.

**Comment by thismarcoantonio** [comment]
Pq nas labels está Pleno??

**Comment by fsrocha-dev** [comment]
Galera, sem querer ofender ninguém e nem defender empresa! mas quem tiver afim manda o CV que não quiser não manda.   ; (

**Comment by fernandoocf** [comment]
Longe de ofender @fsrocha-dev .... mas falando por mim, eu fico indignado com esse tipo de vaga, sabe? Porque ela é a representação exata da prostituição da nossa profissão:

Exige um conhecimento acima do nível dos padrões de mercado exigido pra esse tipo de profissional, no caso JR, e pagando pouquíssimo.

Eu no seu caso sinceramente me recusaria a compartilhar esse tipo de vaga =(

**Comment by fsrocha-dev** [comment]
Entendo @fernandoocf , mas foi a pedido do próprio CEO.

**Comment by kavalcante** [comment]
@fernandoocf Eu entendo sua indignação. Porém a realidade do Brasil nem sempre é o que queremos. Pode ser que existam pessoas dispostas a trabalhar por esse valor, por mais que ele seja considerado baixo. A empresa receberá currículo somente de pessoas que de fato se interessaram pela vaga. Cabe a ela com o que ela recebeu, julgar se algum deles cumpre aos requisitos citados.

Esse lance da "prostituição" é bem complicado mensurar, porque não dá pra saber a realidade de todo mundo. O que é prostituição para você, pode não ser necessariamente para outra pessoa.

E não estou defendendo a vaga, até pq nem sei quem é a pessoa que postou e muito menos a empresa. Só que apenas mostrar revolta pela vaga, não muda o fato de podem existir pessoas que precisam e querem uma oportunidade como essa, por mais que você possa achar ela ruim (e eu concordo).

**Comment by fsrocha-dev** [comment]
Pois é @kavalcante , você chegou no ponto certo! velho eu conheço pessoas que moram em regiões do País onde é escasso o trabalho! não se tem vagas para Devs, as vagas estão concentradas no Sul do País! infelizmente.

**Comment by fsrocha-dev** [comment]
@mikaelhadler cara não seja tão insensível! tem muita gente que precisa cara. Não quero aqui julgar os méritos, mas sei que tem gente precisando dessa vaga, a prova disso é que vários devs se candidataram.

**Comment by mikaelhadler** [comment]
Estou sendo sensato! Pessoas precisando de trabalho sempre terá, infelizmente assim como já vimos na área de suporte e manutenção de hardware, mais do mesmo se repete. 

Sempre vai ter o severino que formata por R$ 30,00..

Fico triste de acreditar que existem pessoas que necessitam deste tipo de proposta, but, it's it

**Comment by fsrocha-dev** [comment]
@mikaelhadler , velho você precisa ir no Nordeste! ai você vai entender o porque as pessoas aqui precisam dessas vagas! claro que não estou descartando que as empresas se aproveitam da muita oferta e pouca demanda para abaixar salários!

**Comment by fsrocha-dev** [comment]
Não vou citar nomes aqui, mas uma empresa grande de SP, abriu um escritório em Salvador, sabe qual foi o resultado ? a vaga de desenvolvedor Java anunciada em SP com salário de 5000.00, a mesma vaga com os mesmos requisitos no mesmo site, só que para Salvador-BA com salário de 2000.00, e quer saber da verdade! sobrou foi desenvolvedor querendo a vaga.

**Comment by antoniotex** [comment]
O que me deixa feliz é que o cara com 3 anos de JS e 2 de Vue, já tem conhecimento e experiência suficiente pra não cair nessas furadas. E no final das contas vão contratar alguém precisando pegar experiência e aceitando qualquer coisa, como já foi o caso de muitos aqui :)

**Comment by victorazv** [comment]
> Não vou citar nomes aqui, mas uma empresa grande de SP, abriu um escritório em Salvador, sabe qual foi o resultado ? a vaga de desenvolvedor Java anunciada em SP com salário de 5000.00, a mesma vaga com os mesmos requisitos no mesmo site, só que para Salvador-BA com salário de 2000.00, e quer saber da verdade! sobrou foi desenvolvedor querendo a vaga.

Moro em Salvador. Vá achando que com 2k, você acha algum Dev bom. Achar, acha, como em qualquer lugar. Mas será uma pessoa iniciante ou mentindo que sabe.

**Comment by fsrocha-dev** [comment]
@victorazv achar a empresa achou! e tenho certeza que o cara não é iniciante e nem mentindo que sabe, pq o processo para entrar nessa empresa é rigoroso! isso te garanto.

**Comment by victorhsantiago** [comment]
A vaga é ruim, isso já foi admitido até por quem criou. É triste, mas acontece, vamos torcer para quem aceitar oportunidade encontre logo uma melhor e mais justa. 

Agora, vamos parar de medir quem mija mais longe?
