### ISSUE TITLE
[Rio de Janeiro] Front-End Developer na Mutual

### ISSUE THREAD

**Issue by brunosantanarj** [frontendbr/vagas#1489]
## Descrição da vaga

Como desenvolvedor front-end você vai ter a oportunidade de trabalhar com React Native e Expo.io, com sprints de duas semanas, inserido em um time comprometido com entregas de qualidade, eficiência na automatização de processos, robustez, escalabilidade e performance dos nossos sistemas.

Procuramos pessoas engajadas, apaixonadas por tecnologia e que, principalmente, acreditem em nosso propósito disruptivo!

## Local

Centro - Rio de Janeiro (pertinho de duas estações de metrô)

#### Diferenciais

Salário competitivo,
Remuneração variável,
Stock Options,
Home office 3~4 vezes na semana,,
Flexibilidade de horário,
Ambiente informal,
Possibilidade de crescimento,

## Requisitos

**Obrigatórios:**
- JavaScript
- React
- Redux

**Desejáveis:**
- React-native
- Expo
- Ramda

## Contratação

PJ a combinar

## Nossa empresa

A Mutual é uma Fintech que surgiu para revolucionar a forma de realizar investimentos e empréstimos no Brasil, utilizando tecnologia, simplificando a circulação de dinheiro entre pessoas, com maior rentabilidade ao investidor e juros menores ao tomador.

Aqui trabalhamos com tecnologia de vanguarda, em ambiente horizontal e colaborativo, com autonomia e foco nas entregas, sem burocracia e enrolação!

## Como se candidatar

Por favor envie um email para bruno.santana@mutual.club ou fabiana.mansur@mutual.club com seu CV anexado - enviar no assunto: Vaga Front-end Developer[Github]

## Labels

- PJ
- Pleno
- Remoto
- Sênior

**Comment by thismarcoantonio** [comment]
Para candidatar a vaga é necessário morar no rio, visto que é remoto 4-5 dias por semana, correto?

**Comment by brunosantanarj** [comment]
@thismarcoantonio é ideal que more no Rio, porém, não obrigatório desde que compareça ao escritório quando necessário.
