### ISSUE TITLE
[São Paulo] Front end Developer

### ISSUE THREAD

**Issue by cubomentoring** [frontendbr/vagas#149]
## Descrição da vaga

PRINCIPAIS ATIVIDADES E RESPONSABILIDADES

Desenvolver funcionalidades alinhadas com a área de negócio sempre buscando agregar valor para os diferentes públicos que se relacionam com a empresa.

Responsável, juntamente com a sua célula de desenvolvimento, pela arquitetura, implementação e entrega das funcionalidades. No nosso processo de desenvolvimento é esperado que tenha um código semântico, faça code review de pares e interaja com a equipe para cumprir as metas e entregar um produto de qualidade. 

COMPETÊNCIAS TÉCNICAS
Automotivado, gostar de se manter atualizado, comunicativo e procura compartilhar conhecimento com os seus pares. Também é esperado que tenha experiência com as seguintes ferramentas ou conceitos:
- Linguagens (Javascript)
- Frameworks JavaScript (jQuery, RequireJS, Backbone, Underscore, AngularJS 1 e 2)
- Front end workflow (Bower, Grunt, SASS)
- WebServer (Apache)
- DevOps (Linux, Chef, Vagrant, Virtualbox)
- Git
## Local

Morumbi - São Paulo - SP 
## Diferencial

Especialização ou cursos de extensão na área de TI.
Inglês no nível avançado.
## Como se candidatar

Por favor envie um email para rh@cubotecnologia.com.br com seu CV anexado - enviar no assunto: Front end Developer

**Comment by eduardojmatos** [comment]
@cubomentoring ainda falta avisar se é PJ ou CLT, pode atualizar a descrição com essa informação?

**Comment by eduardojmatos** [comment]
@cubomentoring consegue nos avisar sobre ser PJ ou CLT? Só pra removermos a label "Pendente de Informações"

**Comment by cubomentoring** [comment]
boa tarde!
A oportunidade é PJ.
