### ISSUE TITLE
[Ribeirão Preto] JavaScript Developer (React) @ Crave Food Systems

### ISSUE THREAD

**Issue by alcferreira** [frontendbr/vagas#1498]
## Descrição da vaga

Projeto bazinga em NodeJS, etc.

## Local

Escritório, Ribeirão Preto - SP

## Benefícios

- Curso de inglês
- Verba para usar em eventos/cursos
- Bônus trimestrais
- 20 dias úteis de férias/ano

## Requisitos

**Obrigatórios:**
- Experiência com React & Redux

## Contratação

PJ
Junior: R$ 2000,00 to R$ 4000,00
Pleno: R$ 5000 to R$ 7000,00
Senior: R$8000 to R$10000,00

## Como se candidatar
https://crave.workable.com/jobs/740996

## Labels

- Alocado
- Júnior
- PJ
- Pleno
- Sênior

**Comment by esl-douglas** [comment]
Mandei, ficaram de marcar a entrevista mas não responderam mais.

Tava mega interessado na vaga, até comecei a estudar React+Redux.
