### ISSUE TITLE
[São José dos Campos] Desenvolvedor Front-End

### ISSUE THREAD

**Issue by luizfelipejr** [frontendbr/vagas#15]
## Descrição da vaga

**O que procuramos:**

- Procuramos um desenvolvedor que se qualifique tecnicamente entre pleno e senior, que esteja confortável trabalhando com javascript e frontend. Portanto, experiência a nível avançado com Javascript é necessário.

**Nosso backend:**

- Node.js(es6), Mongodb, RabbitMQ, Heroku

**Nosso frontend:**
- backbone.js/marionette.js, require.js, karma, jasmine, gulp, sass, css3

## Local

Presencial em São José dos Campos - São Paulo

## Requisitos

**Obrigatórios:**
- Single Page Applications
- HTML5, CSS3/SASS, Design Responsivo
- Git
- Habilidade de escrever códigos eficientes e modulares para otimização dos componentes de front-end
- Desenvolvimento cross plataform/browser compatibility(IE, Firefox, Chrome)
- Interesse em explorar as novas tendências web
- Clean code, TDD e boas práticas
- Experiência com utilização de API RESTful
- Vivência em times com desenvolvimento ágil
- Saiba trabalhar em equipe e tenha uma boa relação interpessoal

**Diferenciais:**
- Angular.js/Backbone.js
- Tenha projetos publicados no GitHub ou participe ativamente de um projeto
- Participe de eventos da comunidade open-source.

## Contratação

Projeto por tempo indeterminado.

## Como se candidatar

Por favor envie um email para luiz.felipe@gsw.com.br com seu CV anexado - enviar no assunto: Desenvolvedor Front-End

**Comment by eduardojmatos** [comment]
@luizfelipejr sabe dizer se é CLT ou PJ?

**Comment by luizfelipejr** [comment]
@eduardojmatos, acredito ser negociável... a empresa possui pessoal CLT e PJ.

**Comment by eduardojmatos** [comment]
@luizfelipejr blz, adicionei as duas labels então

**Comment by eduardojmatos** [comment]
@luizfelipejr fiz uns ajustes de formatação, blz?

**Comment by luizfelipejr** [comment]
@eduardojmatos muito obrigado!

**Comment by eduardojmatos** [comment]
@luizfelipejr :+1:

**Comment by LFeh** [comment]
A vaga foi preenchida?

**Comment by LFeh** [comment]
Como não houve respostas, vou fechar a issue.

Avise se precisar @luizfelipejr

**Comment by camilatigre** [comment]
@luizfelipejr 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

**A pessoa que preencheu a vaga foi encontrada através desta issue?**
a) Sim
b) Não
c) Não tenho certeza
