### ISSUE TITLE
CLOSE | [São Paulo] Front end Developer 

### ISSUE THREAD

**Issue by amadre-nelson** [frontendbr/vagas#150]
## Descrição da vaga

O candidato será responsável por toda a parte de frontend desenvolvido, HTML5, CSS e JS.
## Local

**Exclusivo para São Paulo/SP**
ALOCAÇÃO, São Paulo/SP - Vila Olímpia
## Benefícios
- A combinar
- Ótimo ambiente
## Requisitos

**Perfil:**
- Sênior/Pleno

**Obrigatórios:**
- Fluência em JS

**Desejáveis:**
- Gulp, Grunt e Node.
## Informações Extras
- 1 hora de almoço
- Maquina de café
- Maquina de Junky Foods
## Contratação

PJ a combinar
## Nossa empresa

http://amad.re/
## Como se candidatar

Por favor envie um email para nelson.secco@amad.re com seu CV anexado - enviar no assunto: [São Paulo] Front end Developer

**Comment by eduardojmatos** [comment]
@amadre-nelson opa, sabe dizer qual o perfil da vaga? Júnior, pleno ou sênior?

**Comment by amadre-nelson** [comment]
Boa tarde @eduardojmatos, estamos analisando perfis pleno/senior. Obrigado por sua pergunta e para facilitar para todos os outros amigos atualizei com esta informação.

**Comment by ismaelsantana** [comment]
Olá, tem como mandar uma prova teste? para ver se meu conhecimento é compatível com a vaga, valeu

**Comment by amadre-nelson** [comment]
Bom dia @ismaelsantana tudo bem? Por favor nos encaminha seu currículo verificando seus conhecimentos listado já conseguimos avaliar se você esta dentro ou não do perfil caso esteja seguimos com o processo seletivo. Muito obrigado pelo seu interesse em ser nosso parceiro.

**Comment by leonardoelias** [comment]
Porque 1 hora de almoço seria um benefícios ?

obs. pergunta sem maldade :)

**Comment by amadre-nelson** [comment]
Bom dia @leonardoelias muito obrigado pelo seu feedback, já foi corrigido.
