### ISSUE TITLE
[Teixeira de Freitas] Front-End Developer na [Inovatto Sstemas]

### ISSUE THREAD

**Issue by Gildarth** [frontendbr/vagas#1500]
## Descrição da vaga
Estamos com vagas abertas no time de Desenvolvimento! Buscamos pessoas que tem grandes ideias e vontade de construir algo incrível.

Se você é um desenvolvedor Front-end acima da média ou conhece alguém, essa é a oportunidade!

## Local
Escritório Teixeira de Freitas - Extremo Sul da Bahia (Possibilidade ser via Remoto.)

## Requisitos
 Vue.js 2.0
 Quasar Framework
 HTML5/CSS3
 ECMAScript 6 (ES6)
 Consumo de APIs (RESTfull)
 Conhecimento com Git

## Contratação
A combinar

## Nossa empresa
Somos uma Startup inovadora pronta para oferecer uma nova experiência ao mercado que mais cresce no mundo. Conectamos: Gente boa + Empatia + Novas ideias + Design + Tecnologia.

Para que possamos implementar soluções disruptivas e diferenciadas para simplificar e gerar valor na gestão do negócio de Beleza e Bem-estar utilizamos como base o Project Thinking, Gestão Visual, Agilidade, Neurociência Aplicada e PESSOAS!

Somos o novo, mas com experiência de gente grande, nasce em 2017 a inovatto sistemas, com o apoio e a experiência da consolidada ECosmetics International Salon presente no Brasil, além da América do Norte, Europa, África e Emirados Árabes e a HSB Hair School Business, premiada com o título de Melhor Escola do Mundo para Cabeleireiros no Hairworld Global Awards em Paris.

## Como se candidatar
Aplique-se pelo link e envie seu currículo para nós: http://www.inovattosistemas.com/carreira/ - Enviar no assunto: Vaga Desenvolvedor Front-end

## Labels
- Alocado
- CLT
- PJ
- Pleno
- Remoto
- Sênior

**Comment by Gildarth** [comment]
Vaga persiste em aberto

**Comment by LFeh** [comment]
Boa, vou abrir :)
