### ISSUE TITLE
[Remoto] Front-End Developer na Stone Pagamentos

### ISSUE THREAD

**Issue by FidelisClayton** [frontendbr/vagas#1509]
## Descrição da vaga
Estamos criando uma nova área dentro da vertical de Inovação da Stone, com o objetivo de revolucionar a forma como as operações bancárias ocorrem no nível de pessoas jurídicas no Brasil.

Se você gosta de trabalhar com o que há de mais moderno em termos de tecnologia, tem interesse em produtos digitais, gosta do mercado financeiro e tem vontade de trabalhar com um time extremamente fora da curva, o time de Banking é o seu lugar!

Estamos buscando um(a) **Desenvolvedor(a) Front-End** que queira encarar junto conosco o desafio de evoluir e estruturar novas soluções DO ZERO, sendo responsável pelas decisões técnicas e seus impactos no produto no médio/longo prazo, e que queira ter bastante interação com o time de UX/UI para desenvolvimento das aplicações.

## Local
Remoto ou Escritório, Rio de Janeiro - Centro, São Paulo - Vila Olímpia

## Benefícios
- Vale alimentação e refeição
- Vale transporte
- Gympass
- Plano de Saúde + Plano Dental
- Seguro de vida
- Auxílio creche

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento Front-End
- Experiência em JavaScript e integração via REST;

**Desejáveis:**
- Contribuições em projetos open source
- Experiência com algum Framework/Lib de Javascript como **React**, **Vue**, Angular

**Diferenciais:**
- Experiência com programação funcional
- **Experiência com Elm**

## Contratação
A contratação será em regime CLT, remoto ou presencial no RJ.

## Nossa empresa
A Stone é uma empresa de tecnologia que desenvolve soluções para que lojistas recebam o valor de suas vendas realizadas por meio de pagamento eletrônico, seja no mundo físico ou no digital.

Nascemos em 2012. Já fomos uma startup. Hoje, somos a maior adquirente independente do Brasil e uma companhia de mais de 3000 pessoas, unidas por um único sonho: mudar este mercado, trazendo melhores tecnologias, produtos inovadores e um serviço de qualidade para nossos clientes. Nosso propósito é ajudar o empreendedor a empreender no Brasil.

Nosso dia a dia? Ultrapassar limites, aprender muito e transformar potencial em potência. O seu, o da Stone e o dos nossos Clientes.

## Como se candidatar
Cadastre-se neste link:
https://jobs.kenoby.com/enter.stone/job/desenvolvedora-front-end-inovacao/5ae1ebd88e39de605607efef

## Labels
- Remoto
- Alocado
- CLT
- Pleno
- Sênior

**Comment by rodineicosta** [comment]
Aplicado.

**Comment by joaovertelo** [comment]
Enviado

**Comment by joaovertelo** [comment]
Aplicado.
