### ISSUE TITLE
[Ribeirão Preto - SP] Senior Frontend Developer

### ISSUE THREAD

**Issue by rougeth** [frontendbr/vagas#151]
Crave Food Services is an innovation & technology company specialized in generating efficiency in the food service industry. Our product [WhatsGood](http://sourcewhatsgood.com/) is an online marketplace that connects chefs and local food purveyors.

Purveyors find at WhatsGood a place to showcase and offer their products to purchasers, while efficiently managing their ordering process.

Purchasers find at WhatsGood a place to connect with purveyors and organize their local purchasing.

We currently have an office in Providence (RI – USA) and we are just opening a new office in Ribeirão Preto (SP – Brazil). This position is a local position for the Ribeirão Preto only.

Are you able to understand backend developers and UX designers? Can you put their work together to make beautiful and useful applications? Then you should apply to work with us! Independently of the position we expect that everyone involved in the development process be interested in the whole stack and product – there is no part of the system that is somebody's else problem.
### Requirements

At Crave we use React, Redux, Webpack and other great tools available in JS world!  

Some skills we would like to see in our candidates:
- Passion for technology and high quality engineering
- Have worked with one of these frameworks before (AngularJS, BackboneJS, etc...)
- Good understanding of git
- Be able to build custom UI and animation
- Deal with cross browser compatibility
- Ability to multi-task and work under pressure
- Know about how DOM works and the good practices to work on it.
- Be able to build an app without left-pad
- Experience with working remotely
- Know about coding/designing strategies and methods (TDD, SOLID, Clean Code, etc)
- Strong skills on Unix/Linux environment
- Familiar with agile principles
- Know about automated building, deployment and testing (karma, mocha, sinon, chai, and the list goes on)
- Love JS <3!!
### Benefits

Here you will have the opportunity to work with a great team and more:
- Flexible time (Just be on time to our daily meetings at 10:00am(UTC-3))
- Work on open source projects
- Good salary
- Relocation package
- ... and the most important learn and share!
### How to apply

http://crave.workable.com/

**Comment by LFeh** [comment]
Clt or PJ?

**Comment by rougeth** [comment]
@LFeh PJ apenas

**Comment by rougeth** [comment]
@mtmr0x a vaga continua aberta, pode reabrir a issue por favor?

**Comment by rougeth** [comment]
vou abrir outra, pode deixar, valeu.

**Comment by mtmr0x** [comment]
@rougeth a gente pode reabrir essa, tranquilo

**Comment by mtmr0x** [comment]
@rougeth eu vi que abriu a nova la, de boa! Entao vamos se basear na nova.

Valeu
