### ISSUE TITLE
[Belo Horizonte - MG] Front-End Developer na MAPA DO CARRO

### ISSUE THREAD

**Issue by megandavulpi** [frontendbr/vagas#1515]
### Sobre a empresa: Mapa do Carro

A MapadoCarro.com é uma plataforma virtual de negociação de carros que viabiliza a venda de usados ou seminovos em até 1 hora. Isso mesmo, 60 minutos! Com um processo rápido, moderno e seguro, entregamos com excelência a melhor solução para quem busca vender seu carro de maneira rápida e fácil.

### Descrição: Ocupações do cargo

Programação de páginas para o nosso site e plataforma administrativa;
Participar e propor novas soluções;
Proporcionar a melhor experiência para o usuário;

### Benefícios

Vale Alimentação;
Vale Transporte;
Para nós é fundamental que os nossos profissionais estejam sempre evoluindo, viabilizamos diversos cursos e apoiamos o seu crescimento;
Ambiente descontraído;

### Aptidões e qualidades

Boa comunicação;
Trabalho em equipe;
Pró-atividade;

### Informações complementares

Somos uma empresa fundamentalmente tecnológica, pois nosso produto funciona de forma totalmente virtual. Visamos oferecer uma solução inovadora, tecnológica e segura para sanar a dor de se vender um carro no mercado tradicional. Sendo assim temos muito espaço para crescimento e aprendizado que será revertido na constante otimização de nossa plataforma.

### Labels

CLT
Alocado
Junior

**Comment by arturbani** [comment]
Oi, @megandavulpi, o link está quebrado. A vaga ainda está em aberto?

**Comment by megandavulpi** [comment]
> Oi, @megandavulpi, o link está quebrado. A vaga ainda está em aberto?

Olá, @arturbani .

Infelizmente essa vaga está pausada no momento, mas temos diversas outras Front-End em nosso job board, o que acha de dar uma olhada lá? https://app.vulpi.com.br/jobs

Abraços =D
