### ISSUE TITLE
[Remote] Front end Developer

### ISSUE THREAD

**Issue by pedivo** [frontendbr/vagas#152]
## Descrição da vaga

Atuará no desenvolvimento de uma ferramenta SaaS para a área de saúde. 
## Local

Remoto
## Benefícios
- Horário flexível
## Requisitos

**Obrigatórios:**
- Experiência com AngularJS/Ionic
- Experiência com HTML 5
- Experiência com Gulp/Grunt
- Experiência com Sass
- GIT
- Proficiência em Giphy

**Desejáveis:**
- Conhecimentos em ReactJS
- Falar um segundo idioma (Preferêncialmente Alemão ou Italiano)

**Diferenciais:**
- Experiência com desenvolvimento em soluções de SaaS
- Conhecimento de arquitetura de micro serviços
- Estar disposto a utilizar o lolcommits ;)
## Contratação

PJ a combinar
## Nossa empresa

A Meplis é uma empresa que trabalha com desenvolvimento de soluções inteligentes e adaptáveis para ajudar a resolver problemas específicos na área de saúde, com sede em dois países e usuários presentes em todos os continentes.
## Como se candidatar

Envie um e-mail para pmachado [at] meplis.com com seu CV anexado. Enviar no assunto: Vaga Frontend

**Comment by pedivo** [comment]
Opa! Tem algum label para fulltime?

abs

**Comment by LFeh** [comment]
Fulltime é fulltime, haha. 

Se nao a gente considera freela, haha.

**Comment by pedivo** [comment]
Pergunto isso, pois recebi alguns emails para freela.

Vlw ai.

**Comment by LFeh** [comment]
hahaha, sacanagi

**Comment by thulioph** [comment]
Que engraçado.. Trabalhei numa startup de saúde e lembro que a meplis foi citada pelo pessoal hehe.

> só uma observação mesmo

**Comment by pedivo** [comment]
Vaga preenchida

**Comment by camilatigre** [comment]
@pedivo 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by pedivo** [comment]
Fechei através de outro canal.
