### ISSUE TITLE
[São Paulo] Front-End Developer na Pasqualisolution 

### ISSUE THREAD

**Issue by pablosoares** [frontendbr/vagas#1522]
## Local

São Paulo - Paulista

## Requisitos

- Javascript (ReactJS, Redux, ES6)
- HTML5 e HTML APIs
- CSS (SASS) e StyleSheet Frameworks
- Conhecimentos em programação Orientada a Objetos, programação Funcional e programação Reativa.
- Conhecimento/Experiência com PWA e SPA
- Integração com APIs REST e GraphQL
- Experiência com testes automatizados Javascript, TDD/BDD
- Conhecimento/Experiência com metodologias ágeis (XP, SCRUM e afins)
- Comprometimento com qualidade de código e planejamento.
- Experiência com a ferramenta de versionamento de código GIT

## Contratação

PJ a combinar

## Valor
6 à 7k

## Como se candidatar

Por favor envie um email para edgar.silva@pasqualisolution.com.br com seu CV anexado

## Labels

- Alocado
- PJ
- Pleno

**Comment by LFeh** [comment]
@pablosoares A pessoa vai ser contratada pela propria Pasqualisolution?

**Comment by pablosoares** [comment]
A Pasqualisolution vai ser responsável pelo recrutamento, o nome da empresa que o front-end vai trabalhar não foi divulgado.

**Comment by LFeh** [comment]
@pablosoares Não aceitamos vagas sem o nome da empresa contratante.

```
Atenção: Não aceitaremos vagas sem o nome da empresa contratante.
```

Por conta disso vou ter que fechar :)
