### ISSUE TITLE
[GRAMADO] Desenvolvedor(a) Fullstack Jr na KW Recursos Humanos

### ISSUE THREAD

**Issue by aaamenezes** [frontendbr/vagas#1523]
## Descrição da vaga

- Participação em projetos de implementação e manutenção de sistemas
- Codificação e realização de testes
- Elaborar documentação e manuais de operação de sistemas

## Local

Escritório em Gramado/RS

## Benefícios

- Vale Alimentação de R$ 20,00 por dia útil
- Unimed
- Seguro de Vida
- Farmácia
- Ajuda Combustível

## Requisitos

- HTML
- CSS
- JavaScript
- AngularJS
- C# JSON
- Webservice 
- Banco de dados SQL Server

## Contratação

- CLT

## Nossa empresa

Empresa de Turismo localizada em Gramado

## Como se candidatar

Por favor envie um email para daiani.souza@wkrh.com.br com seu CV anexado. Ou pelo link https://www.wkrh.com.br/job/desenvolvedor-fullstack-a0f1i000004vur1uag/

## Labels

- CLT
- Jr

**Comment by marlonmleite** [comment]
Gramado ❤️

**Comment by aaamenezes** [comment]
;P

**Comment by LFeh** [comment]
@aaamenezes Qual o nivel da vaga?

**Comment by aaamenezes** [comment]
Olá, desculpe, esqueci dessa parte.

É Jr.
