### ISSUE TITLE
[Remoto] ELM Front-End Developer no Cálculo Jurídico

### ISSUE THREAD

**Issue by giovannibonetti** [frontendbr/vagas#1526]
## Descrição da vaga

Aqui no Cálculo Jurídico nós desenvolvemos sistemas para ajudar os advogados a fazerem cálculos de aposentadoria para seus clientes. Estamos expandindo para outras áreas de direito e precisamos de você para nos ajudar a dar conta desse trabalho. A empresa é 100% remota, e nos comunicamos via Slack, Hangout e Google Docs.

Nesta postagem estamos divulgando uma vaga disponível para **desenvolvedor(a) front-end Elm**. 
Estamos buscando alguém para ser o(a) principal desenvolvedor(a) de um projeto novo que está sendo escrito _do zero_ com [Elm e Webpack](https://github.com/CalculoJuridico/create-elm-app).

Requisitos: experiência em desenvolvimento front-end e conhecimentos básicos de Elm.
Processo seletivo 100% online incluindo prova teórica e prática de Elm seguidos de entrevista via Hangouts.

## Local

Remoto

## Contratação

PJ _full time_ com remuneração entre R$ 7 e 10 mil, dependendo da experiência do(a) candidato(a) e do resultado nas provas do processo seletivo.

## Requisitos

**Obrigatórios:**
- Experiência profissional em desenvolvimento de front-end web com HTML, CSS e JS
- Conhecimento teórico de programação funcional
- Conhecimento básico de Elm - basta ter [completado o tutorial](https://guide.elm-lang.org/)
- Inglês avançado

Obs.: todos os requisitos tem uma prova online correspondente no processo seletivo

**Desejáveis:**
- Experiência de trabalho com programação funcional
- Experiência de trabalho com Elm
- Experiência com Webpack

**Diferenciais:**
- Conhecimentos de Linux e Docker

## Como se candidatar

Inscrições abertas até segunda-feira (05/11) via Linkedin.
https://www.linkedin.com/jobs/cap/view/950636092/

Assim que as inscrições se encerrarem você vai receber um email nosso explicando como iniciar o processo seletivo.

## Empresa

Apesar de ser uma empresa nova (cerca de 2 anos), o Cálculo Jurídico já é uma empresa lucrativa e, portanto, não precisa de investimento externo. Aqui a gente trabalha para fazer o melhor produto pro cliente, não para entregar as funcionalidades que o investidor pede.

Somos uma equipe pequena (cerca de 10 pessoas) mas bem organizada. Você pode observar isso pela organização do processo seletivo com várias etapas, sendo tudo realizado por nós mesmos (não terceirizamos recrutamento pra nenhuma empresa de RH).

Do ponto de vista tecnológico, hoje temos um sistema feito em Ruby on Rails hospedado no Google App Engine / Google Cloud Platform com containers Docker. Estamos montando nossa API agora que vai ser usada pelas novas partes do front-end, que já foi todo desenhado no Figma e está sendo implementado agora.

#### Diferenciais da empresa

- empresa 100% remota;
- trabalho com projeto escrito do zero em Elm. Nada de legado de JS para manter;
- alta produtividade - você vai poder focar no trabalho sem muitas interrupções. Há raríssimas reuniões (normalmente só uma por semana), pois quase todas a comunicação ocorre de forma assíncrona via documentos do Google Docs, desenhos da interface no Figma, emails etc.

**Comment by Selhar** [comment]
Oi. Não uso linkedin, há outro método de inscrição?

**Comment by giovannibonetti** [comment]
@matheus-rosin seria só reading/writing.

@Selhar nós usamos o LinkedIn só pra coletar o e-mail e o CV. Acho que neste processo seletivo não vou conseguir mudar isso.

Por outro lado bastaria você gastar alguns minutos pra se cadastrar no LinkedIn e daí você pode fazer upload do seu CV na candidatura da vaga.

Nós simplificamos bastante o processo seletivo, garanto que você vai gastar bem menos tempo com ele do que o normal, já que o processo seletivo é todo online e a maioria das fases são provas que você faz quando quiser.

**Comment by matheus-rosin** [comment]
@giovannibonetti legal, aí é mais tranquilo :) vou aplicar, obrigado pela informação!

**Comment by giovannibonetti** [comment]
Estamos tendo uns problemas com o LinkedIn. Vamos tentar reestabelecer a vaga agora de manhã e já aviso aqui no grupo quando estiver no ar de volta.

**Comment by giovannibonetti** [comment]
Atualizei o link do LinkedIn, agora está funcionando de volta.

**Comment by gabrielmedina** [comment]
@giovannibonetti Mestre, aqui continua com o erro reportado `Esta vaga não aceita mais candidaturas`. Inscrições encerradas?

**Comment by giovannibonetti** [comment]
Ah, sim, o prazo pra inscrição era só até ontem mesmo.
Obrigado pelo esforço, de qualquer forma.

**Comment by giovannibonetti** [comment]
A vaga foi preenchida! 😀 
Obrigado a todos que participaram do processo seletivo!

Semestre que vem devemos ter uma nova vaga, fiquem de olho! 📋👀
