### ISSUE TITLE
[São Paulo] Front-End Developer na Webbing Brasil

### ISSUE THREAD

**Issue by essejose** [frontendbr/vagas#1529]
## Descrição da vaga

Somos um time enxuto, procuramos alguém apaixonado por desenvolvimento, que busca desafios.
Seu papel será  na manutenção de aplicações web, peças de mídia (HTML de Email Marketing e Banners) e  Aplicativos Híbridos.

## Local

Escritório, São Paulo
R. Ten. Gomes Ribeiro,  Vila Clementino

## Benefícios 

- Vale refeição
- Vale transporte
 

#### Diferenciais

- Horário flexível
- Ao lado da estação Santa Cruz
- Muito cafe 

## Requisitos

**Obrigatórios:**
-  HTML5/CSS3
- Ajax/API REST
- ES5/ES6
- Git
 

**Desejáveis:**
- conhecimentos em ReactJS/ React Native
- conhecimentos em Angular
- conhecimentos em PHP

## Contratação
CLT

## Nossa empresa

Com mais de 8 anos de experiência, a Webbing Brasil é especialista em atuar em parceria com Agências e Consultorias para desenvolvimento de projetos Web e Mobile.

## Como se candidatar

Por favor envie um email para contato@webbingbrasil.com.br com seu CV anexado - enviar no assunto: Vaga [ Front-End Developer júnior ]

## Labels

- Alocado
- CLT
- Júnior

**Comment by kvnol** [comment]
Enviado!

**Comment by andreluisverde123** [comment]
Há alguma possibilidade ser remoto?

**Comment by armenio2** [comment]
Done..

**Comment by essejose** [comment]
> Há alguma possibilidade ser remoto?
 
opa, desculpa somente presencial
