### ISSUE TITLE
[Campinas] Front End Developer

### ISSUE THREAD

**Issue by fmoliveira** [frontendbr/vagas#153]
## Descrição da vaga

Atuar com desenvolvimento Frontend utilizando tecnologias de ponta.
## Local

Escritório próximo ao Shopping Iguatemi em Campinas, SP
## Benefícios
- Assistência Médica (UNIMED)
- Plano Odontológico (UNIODONTO)
- Seguro de Vida em Grupo
- Vale Transporte
- Vale Refeição
- Auxílio Educação
- Auxílio para cursos preparatórios de certificações
- PPR (Programa de Participação nos Resultados)
## Requisitos

**Obrigatórios:**
- Experiência com HTML, JavaScript e CSS3.
- Experiência com Twitter Bootstrap.
- Conhecimento em algum framework MVVM para Web.
- Conhecimento em Git e GitHub/Bitbucket.
- Experiência com metodologia Scrum.

**Desejáveis:**
- Experiência com Angular 1 e/ou 2.
- Conhecimento em TypeScript.
- Integração contínua (Jenkins, AppVeyor).

**Diferenciais:**
- Microsoft SQL Server.
- .NET Entity Framework, APIs RESTful, WebAPI.
## Contratação

CLT
## Nossa empresa

A HBSIS desenvolve softwares de soluções de logística há mais de 26 anos para grandes empresas do Brasil inteiro. 
## Como se candidatar

Envie seu currículo com pretensão salarial para luciana.corbini@hbsis.com.br.

**Comment by fmoliveira** [comment]
@LFeh parece que eu não tenho permissão para adicionar tags, vc prefere adicioná-las ou me dar permissão? Muito obrigado!

**Comment by LFeh** [comment]
Certa essas?

**Comment by fmoliveira** [comment]
Perfeito @LFeh , obrigado! 👍

**Comment by gstvribs** [comment]
Olá,

A vaga está em aberto, ainda ?
