### ISSUE TITLE
[Berlin] Front-End Vanilla.JS Developer Senior na [castLabs]

### ISSUE THREAD

**Issue by chambs** [frontendbr/vagas#1532]
## Descrição da vaga

Dev para desenvolvimento de um web player capaz de reproduzir DASH, Smooth Streaming e HLS, clear ou protected content.
A empresa patrocina o visto de trabalho, se for necessario.

## Local

Berlin, no escritorio, mas com liberdade para trabalhar remoto quando quiser. Porem, precisa estar em Berlin

## Benefícios

- O default de startups: bebidas, comidas, stock options, mesa de pebolim, etc.

#### Diferenciais

- Livre pra trabalhar de casa sem aviso previo

## Requisitos

**Obrigatórios:**
- Ter bastante experiencia com Vanilla.JS, webpack, npm, etc

**Desejáveis:**
- conhecimentos em desenvolvimento com web players
- conhecimentos DASH, Smooth ou HLS
- conhecimento (ainda que bem basico) de DRM
- estar habituado com Jira, Confluence, Jenkins...

**Diferenciais:**
- Ter experiencia com Shaka Player
- Ter nocoes de ABR

## Contratação

Contrato default na Alemanha: 6 meses de experiencia, seguidos de contrato permanente (como se fosse CLT no Brasil).

## Nossa empresa

A castLabs oferece players capazes de reproduzir DASH, Smooth e HLS em todas as plataformas (Android, iOS e browsers) e em oferecer servicos de DRM nos sistemas mais populares: Widevine, Playready e Fairplay.

## Como se candidatar

Por favor envie um email para willian.carvalho@castlabs.com com seu CV anexado em ingles - enviar no assunto: Javascript Developer position

## Labels

- Berlin
- Player
- Video Streaming
- Vanilla JS

**Comment by chambs** [comment]
@LFeh poderia adicionar a label "Senior", por favor?

**Comment by malacela** [comment]
CV enviado.

**Comment by chambs** [comment]
A equipe d RH da empresa disse que ja tem uma pequena lista de CVs selecionados e nao pretendem analisar mais curriculos.
Agradeco a todos que enviaram os CVs e aos que foram contactados pelo RH, boa sorte!
