### ISSUE TITLE
[São Paulo] Front-End Developer Pleno / Senior na Superare

### ISSUE THREAD

**Issue by w3solution** [frontendbr/vagas#1539]
## Descrição da vaga

Front-End Developer na Superare.co

## Local

Remoto ou Escritório, São Paulo - Chacara Sto Antonio

## Requisitos

**Obrigatórios:**
- JavaScript ( ser TOPzera ) 
- O bom e velho HTML
- Deixar uma lindeza via CSS
- Pré-Processador CSS (SASS)
- Taskrunner (Gulp,Grunt)
- ES6
- webpack
- Frameworks de mercado
- Ser um adepto a boas praticas e conceitos do mercado
- Versionamento de código (Git, Gitflow)
- Material Designer
- Architecture components
- Experiência com REST APIs
- Teste Unitários

**Desejáveis:**
- NodeJS
- PHP

## Contratação

PJ a combinar

## Nossa empresa
A Superare sempre olhou para o futuro com uma metodologia de trabalho bem definida: aqui, todo o processo é baseado em 
resultados, sem achismos. Isso quer dizer que em tudo tem Analytics. Nada é planejado, criado e produzido sem que os resultados 
sejam analisados em todas as etapas.

O retorno é o melhor que poderíamos ter: em pouco tempo de atuação, deixamos de ser apenas uma empresa de tecnologia para 
atuarmos como agência digital, além de sermos uma das primeiras parceiras do Facebook (inclusive, fizemos o bot deles) e uma 
das principais parceiras de gigantes mundiais como Google, Microsoft e Newspace.

Como conseguimos ir além em apenas 6 anos? Fazendo um constante esforço de inovação, criando produtos e estratégias focados 
em resultados e usando a tecnologia para fazer a diferença na vida das empresas e das pessoas.
Aqui na Corporação ACME somos líderes em...

## Como se candidatar

Por favor envie um email para eric@superare.co com seu CV anexado - enviar no assunto: [Front-End]

## Labels

- Alocado
- PJ
- Pleno
- Sênior

**Comment by alessandroprudencio** [comment]
Qual o salario?
