### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor iOs PL [inChurch]

### ISSUE THREAD

**Issue by LuanaMoreira** [frontendbr/vagas#1541]
E aí, tem interesse em trabalhar com uma galera maneira em uma Startup que é referência na construção de aplicativos para o terceiro setor na América Latina?! Chegou ao lugar certo! 

Nós da inChurch fazemos parte do inRadar Group, uma marca de soluções para grupos e organizações. Desenvolvemos Apps, Portais Web, Totens Interativos e tudo que for importante para entregar conveniência para os nossos usuários.

Fazemos tudo isso aqui na Barra da Tijuca-RJ em um ambiente super descontraído com direito a área de games e um lounge pra dar aquela relaxada!

Vem crescer com a gente! 

**Desenvolvedor IOs Júnior** 

**Suas Habilidades Técnicas:** 

Graduação em Ciência da Computação, Engenharia de Software, Análise e Desenvolvimento de Sistemas ou correlata; 
Conhecimento da Guideline de Design e Desenvolvimento Apple;  
Familiaridade com integração APIs REST; 
Experiência em versionamento de projetos com Git; 
Familiaridade com storyboards, xibs e auto layout; 
Domínio da linguagem Swift e conhecimento de Objective-C. 

**Sua Missão:** 

Desenvolver funcionalidades e dar manutenção no nosso aplicativo IOs; 
Criar variantes do layout original de uma aplicação whitelabel; 
Migrar aplicação do Objective-C para o Swift.

**Adoraríamos se você tivesse também:** 

Conhecimento do padrão MVVM e MVP; 
Experiência com Targets; 
Gerenciamento de dependências de projeto (CocoaPods, Carthage). 

**Nossos Benefícios:** 
- VR; 
- VT; 
- Oportunidade de crescimento; 
- Acesso a um ambiente com academia, piscina e até SAUNA, meus amigos! \o/

Para participar da nossa seleção basta nos enviar um e-mail com o assunto “Desenvolvedor IOs PL ”, anexando o seu currículo ou enviando a URL do seu Linkedin (Atualizado, hein?!) com pretensão salarial para rh@inchurch.com.br

**Comment by eduardojmatos** [comment]
@LuanaMoreira obrigado por postar, mas esse repositório é para vagas front-end. 

Existe um repositório específico para vagas iOS: https://github.com/CocoaHeadsBrasil/vagas
