### ISSUE TITLE
[Rio de Janeiro] Front-end Developer na Project Engine

### ISSUE THREAD

**Issue by marks5** [frontendbr/vagas#1542]
## Descrição da vaga

A pessoa ficará trabalhando em projetos relacionados ao Detran PA.

## Local

Escritório, Rio de Janeiro - Centro

## Benefícios

- A combinar

## Requisitos

**Desejáveis:**
- ES6
- Angular 4 ou superior
- Webpack
- HTML 5 e CSS 3
- SASS/LESS

**Diferenciais:**
- Conhecimento em Node js
- Conhecimentos em integração contínua
- Conhecimento em cordova/ionic/react/react native/quasar/vue
- Conhecimentos em Docker
- Conhecimento AWS
- Conhecimento Openshift

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um email para gabriel.marques@consorciosigtrans.com seu CV anexado - enviar no assunto: Vaga Frontend Jr

## Labels

- CLT
- Júnior

**Comment by fabiomirandaa** [comment]
Possibilidade de remoto?
