### ISSUE TITLE
[Belo Horizonte | Manaus] Front-End Developer na Méliuz

### ISSUE THREAD

**Issue by gustavoteodoro** [frontendbr/vagas#1543]
## Descrição da vaga

O time de Produto do Méliuz está em busca de um(a) Desenvolvedor(a) Front-end que mande muito bem em React.

O nosso universo nos permite assumir desafios e lidar com tecnologias de ponta.

Estamos procurando por você que tem toda disposição em fazer parte da nossa grande família!

## Local

Vaga disponível para atuar no escritório em Manaus - AM ou Belo Horizonte -MG.

## Benefícios

- Vale Transporte;
- Vale Refeição ou Alimentação;
- Plano de Saúde;
- Plano Odontológico;
- Gympass;
- Double cashback online;
- E ainda, horário flexível! ;)

## Requisitos e qualificações

- Experiência React para Web;
- Sólidos conhecimentos em JavaScript e HTML5;
- Experiência com frameworks modernos de JS (React, Angular, Ember, etc.);
- Design patterns com JavaScript;
- Conhecimento avançado de CSS, patterns e seus pré/pós processadores;
- Experiência com Node.js, React, Redux, ES2015, SSR;
- Aplicação de técnicas TDD e BDD;
- Experiência em metodologias ágeis de desenvolvimento (Scrum, Kanban);
- Conhecimento em gerenciadores de dependência e build (Maven, Gradle, npm, yarn e etc);
- Experiência com ferramentas como Gulp, Grunt e webpack;
- Integração com backend via APIs REST;
- Conhecimento em ferramentas de controle de versão (Git);
- Ter facilidade para trabalhar dentro de times multi-disciplinares;
- Capacidade para escrever código consistente, eficiente e reutilizável (princípios OOP e de programação funcional);
- Desenvolver código semanticamente correto e otimizado para SEO;
- Experiência com programação assíncrona (Promises, Generators, Streams);
- Noções de UX e Design de Interação;
- Forte conhecimento do protocolo HTTP.

**Diferenciais:**
- React Native

## Contratação

CLT - salário a combinar

## Nossa empresa

Hoje, somos o maior site de cashback e descontos do Brasil, porém queremos aumentar nossa presença por aqui e, ao mesmo tempo, expandir para o resto do mundo. Queremos que toda vez que alguém pensar em comprar algo, saiba que irá economizar mais usando o Méliuz.

Geramos mais de um milhão de reais em vendas por dia para as lojas e continuamos crescendo. Para alcançar nossas metas precisamos de mais pessoas talentosas para reforçar nossa equipe e agilizar nosso crescimento.

Somos uma equipe jovem, sedenta por alcançar metas que pessoas normais consideram impossíveis. O que nos motiva são os desafios. Boa parte das pessoas que estão aqui hoje saíram de outras empresas por não se sentirem desafiadas o suficiente. Cada pessoa aqui dentro é comprometida com os seus objetivos, mas também está sempre buscando ajudar os seus colegas.

Oferecemos suporte para que todos se qualifiquem cada vez mais, dêem sugestões de como melhorar processos e fluxos de trabalho, ambiente de trabalho e até mesmo a forma como são avaliados. Tudo aqui está em constante mudança, assim como o nosso mercado. Temos que agir rápido à estas mudanças e estar sempre à frente. Somos aqueles cujo nossos concorrentes se inspiram na hora de criar um novo site de cashback, e iremos nos manter assim.

Queremos pessoas legais, engajadas e animadas. Gente que não tem medo de arriscar, busca objetivos enormes e sabe que nada é impossível.

## Como se candidatar

Candidatar através [deste link](https://meliuz.gupy.io/jobs/20936)

## Labels

- Alocado
- CLT
- Pleno

**Comment by morenopereira** [comment]
👏🏻👏🏻

**Comment by pdf13** [comment]
Para quem quiser conversar mais sobre como é o trabalho aqui no Méliuz fiquem a vontade para perguntar aqui na issue ou em `pdf [at] meliuz.com.br`. Vou ter o maior prazer em responder todas as dúvidas que eu puder!
😉

**Comment by MendoncaGabriel** [comment]
Gostaria me candidatar a vaga, porem o link esta quebrado "Candidatar através [deste link](https://meliuz.gupy.io/jobs/20936)"
