### ISSUE TITLE
[Rio De Janeiro] Estágio Front-End na SuperCommerce

### ISSUE THREAD

**Issue by bersuc** [frontendbr/vagas#1545]
## Descrição da vaga

Estamos em busca de uma pessoa disposta a crescer, atenta e com boa capacidade analítica para resolução de problemas. Precisa ter visão macro e entender o projeto como um todo, boa comunicação e agilidade para integrar nossa equipe.

Oferecemos um ambiente de bastante aprendizado, com oportunidade de crescimento e horário flexível.

## Local

Escritório no centro do Rio de Janeiro

## Benefícios

- Bolsa auxílio
- Vale Refeição
- Vale Transporte
- 13º
- PL anual
- Possibilidade de efetivação

#### Diferenciais

- Experiência prévia com e-commerce
- Saber o que é o Magento
- Saber o que é UX
- Noções Photoshop
- Noções de Git Flow
- Noções de Jquery

## Requisitos

**Obrigatórios:**
- Estar matriculado em instituição de ensino superior (nas áreas de design, informática ou relacionadas)
- HTML
- CSS
- Javascript

## Sobre a SuperCommerce

A SuperCommerce é uma empresa de E-commerce voltada para profissionais.
Somos uma empresa de comércio eletrônico focada na venda de equipamentos para profissionais (e consumidores exigentes, claro).
Operamos desde 2012 e controlamos as lojas ImpressorAjato.com, SegurancAjato.com, OfficeTotalShop.com e Impressora.com. Somos hoje uma das 3 maiores revendas nas principais marcas que representamos, além de atendermos mais de 55.000 clientes em todo o Brasil com altíssimo índice de satisfação. Temos 2 centros de distribuição estrategicamente localizados em nosso país, tudo isso para oferecer sempre a melhor experiência para empresas e profissionais liberais que desejam adquirir equipamentos para suas atividades.

## Como se candidatar

Por favor envie um email para vagas@supercommerce.com.br com seu CV anexado - enviar no assunto: Vaga estágio Front-End

## Labels

- Alocado
- Estágio

**Comment by antoniotex** [comment]
Ótima oportunidade!
