### ISSUE TITLE
[São Paulo] Front-End Developer na BAND

### ISSUE THREAD

**Issue by portaldaband** [frontendbr/vagas#1546]
## Descrição da vaga
Buscamos alguém  que goste de trabalhar em equipe, tenha capacidade de pensar fora da caixa e solucionar problemas de forma simples e rápida. Alguém que preze pela excelência de um código limpo, mas que tenha noção de que nem sempre é possível alcançá-lo - e o deadline é o mais importante.

**Principais responsabilidades:**
Desenvolver sites focados em performance;
Desenvolver sistemas para uso da redação (Angular).

## Local
Escritório em São Paulo - Morumbi

## Benefícios
- Plano de saúde
- Vale refeição
- Vale transporte

#### Diferenciais
- Flexibilidade no horário
- Talks com palestrantes da Comunidade de DEV de SP

## Requisitos

**Obrigatórios:**
- HTML, CSS e SaSS
- JavaScript, JQuery, AngularJS e Angular
- Integração com API;
- Controle de versão (Git)

**Desejáveis:**
Conhecimentos em TypeScript e Ionic

**Diferenciais:**
Conhecimento em NodeJS

## Contratação
CLT

## Nossa empresa
Equipe de desenvolvimento (web e sistemas) do Grupo Bandeirantes de Comunicação.

## Como se candidatar
Por favor envie um e-mail para selecao@band.com.br com seu CV anexado - enviar no assunto: [Vaga Frontend]

## Labels
- Alocado
- CLT
- Senior

**Comment by eduardolimasoares** [comment]
Te K Ju ut m
Ter çu
RT.! Itu BB
Enviado pelo meu Windows Phone
________________________________
De: band.com.br<mailto:notifications@github.com>
Enviada em: ‎08/‎11/‎2018 14:22
Para: frontendbr/vagas<mailto:vagas@noreply.github.com>
Cc: Subscribed<mailto:subscribed@noreply.github.com>
Assunto: [frontendbr/vagas] [São Paulo] Front-End Developer na BAND (#1546)

Descrição da vaga

Buscamos alguém que goste de trabalhar em equipe, tenha capacidade de pensar fora da caixa e solucionar problemas de forma simples e rápida. Alguém que preze pela excelência de um código limpo, mas que tenha noção de que nem sempre é possível alcançá-lo - e o deadline é o mais importante.

Principais responsabilidades:
Desenvolver sites focados em performance;
Desenvolver sistemas para uso da redação (Angular).

Local

Escritório em São Paulo - Morumbi

Benefícios

  *   Plano de saúde
  *   Vale refeição
  *   Vale transporte

Diferenciais

  *   Flexibilidade no horário
  *   Talks com palestrantes da Comunidade de DEV de SP

Requisitos

Obrigatórios:

  *   HTML, CSS e SaSS
  *   JavaScript, JQuery, AngularJS e Angular
  *   Integração com API;
  *   Controle de versão (Git)

Desejáveis:
Conhecimentos em TypeScript e Ionic

Diferenciais:
Conhecimento em NodeJS

Contratação

CLT

Nossa empresa

Equipe de desenvolvimento (web e sistemas) do Grupo Bandeirantes de Comunicação.

Como se candidatar

Por favor envie um e-mail para selecao@band.com.br<mailto:selecao@band.com.br> com seu CV anexado - enviar no assunto: [Vaga Frontend]

Labels

  *   Alocado
  *   CLT
  *   Pleno

**Comment by fabiomirandaa** [comment]
Alguma possibilidade de Remoto?
