### ISSUE TITLE
[São Paulo] Front End Developer - PJ BeeTech Global

### ISSUE THREAD

**Issue by MariliaLeocadio** [frontendbr/vagas#1549]
## Descrição da vaga
Estamos em busca de desenvolvedores que, assim como a gente, tenham um perfil ousado e empreendedor: gente ligada em tecnologia, que gostem de evoluir com novas experiências, e principalmente queiram construir produtos e soluções incríveis. 
Para isso temos um nível de exigência alto com qualidade e buscamos um front-end que tenha atenção aos mínimos detalhes, que se preocupa com cada pixel que está no lugar errado, com a animação que não está tão smooth, enfim, que ama o que faz.

## Local

São Paulo - Faria Lima prox Largo da Batata

## Requisitos
Desenvolver projetos em React/Redux
Sólidos conhecimentos em HTML/CSS/JavaScript 
Aplicar Design Patterns de Clean Code
Aplicar técnicas de TDD e BDD
Trabalhar em conjunto com a área de UX para desenvolver features
Manter e evoluir os projetos da BeeTech
Vivência com metodologias ágeis ( XP, Kanban, Scrum…) 

## Contratação
PJ 

## Nossa empresa
Somos a BeeTech, uma fintech brasileira que tem como principal missão facilitar o acesso a serviços financeiros globais de forma segura, democrática, fácil e transparente. 
Ajudamos pessoas e empresas a se tornarem cidadãos do mundo!

## Como se candidatar
Envie um email diretamente para mim: marilia.leocadio@beetech.global

## Labels
- PJ
- Pleno
- Sênior

**Comment by kvnol** [comment]
CV enviado.

**Comment by malacela** [comment]
CV enviado.

**Comment by MariliaLeocadio** [comment]
Pessoal - fechamos as vagas de Front Hoje.
Gostaríamos de agradecer todos que se candidataram!
