### ISSUE TITLE
[Recife/PE] Front-End Developer Pleno/Sênior - (NodeJS, React, IA/ML) - e3 Labs

### ISSUE THREAD

**Issue by andregomesoliveira** [frontendbr/vagas#1553]
## Descrição da vaga

Vaga para dev front-end (perfil fullstack), execução de projeto de automação utilizando inteligência artificial (machine learning e outras APIs).

## Local

Recife/PE

#### Diferenciais

- Horário flexível
- Note fornecido pela empresa
- Envolvimento no propósito do projeto e não somente codar um escopo pré-definido

## Requisitos

**Obrigatórios:**
- 2+ anos de experiência com desenvolvimento web/mobile frontend
- Conhecimento intermediário em NodeJS e/ou React Native/ReactJS
- Experiência com times de desenvolvimento
- Conhecimento nas Metodologias Ágeis

**Desejáveis:**
- React avançado
- NodeJS avançado
- Experiência com desenvolvimento em ambientes Cloud (Kubernetes, Docker, arquitetura de microserviços)
- Conhecimento em Banco de Dados não-relacionais (MongoDB)
- Experiência anterior com projetos usando Inteligência Artificial/Machine Learning como IBM Watson, MindMeld, Google AI

## Contratação

CLT, salário compatível com o mercado.

## Nossa empresa

Somos uma empresa de tecnologia focada em soluções web inovadoras relevantes para o mercado que atuamos. Nosso diferencial é o foco em automação e inteligência de negócios, do backend ao UX, com laboratórios incubados em empresas reais para validação dos nossos produtos. 

## Como se candidatar

Por favor envie um email para andre.oliveira@e3labs.com.br com seu CV anexado e LinkedIn.

## Labels

- Alocado
- CLT
- Pleno
- Sênior

**Comment by WandersonAlves** [comment]
A empresa é massa galera, cola ai!

**Comment by JohnnysMartins** [comment]
Aplicado!
