### ISSUE TITLE
[Belo Horizonte - MG] Front End Developer na NATA.HOUSE

### ISSUE THREAD

**Issue by megandavulpi** [frontendbr/vagas#1554]
### Sobre a empresa: nata.house

Somos uma fábrica de software com foco em sistemas web e aplicativos multiplataforma. Contamos com profissionais especializados em experiência do usuário e tecnologias de ponta que garantem estabilidade, escalabilidade e redução de custos, do início do planejamento até após a entrega.

### Descrição:

Quer saber o que você fará aqui conosco?

Aqui você irá desenvolver funcionalidades, botar a mão da massa e codificar bastante. Mais que isso, você irá testar e analisar o que estamos desenvolvendo, afinal, não é só escrever um monte de código, certo? No seu dia-a-dia você irá trocar experiência com profissionais de diversas senioridades. Vai ser show.

### Por que você deveria se juntar a nós?

Somos uma fábrica de software que tem crescido muito e estamos disponibilizando essa estrutura para você crescer conosco. Você terá um ambiente sensacional para trabalhar. 

### Benefícios

Vale-transporte (esse nem é benefício, é obrigação) mas podemos colocar o auxílio-combustível, melhorou?
Vale-refeição
Lanche na empresa
Plano de progressão com critérios objetivos e revisões semestrais
Subsídio para cursos e eventos
Possibilidade de organizar e ministrar meetups e cursos abertos
Contato com clientes internacionais
Carga horária de 30 ou 40h semanais

Ou seja, nós temos tudo para você querer ficar conosco.

### E sabe o que você precisa saber?

Estamos falando de front-end e não tem como passar despercebido o conhecimento na trinca famosa:

Javascritp
HTML
CSS

E mais que isso, precisamos que você entenda de lógica de programação, boas práticas e algumas coisinhas de Git.

### Agora, seria show se você soubesse...

React
React Native
Node.Js
Scrum
Plataformas de Gerenciamento de Projetos

Pois assim você avança algumas casa na disputa.

### E sabe como você conquista a gente?

Com proatividade, comprometimento, espírito de equipe e uma automotivação para o aprendizado. E você se sairá muito bem se for flexível e se adaptar.

### Labels:

Alocado
Junior

### Candidatar: http://bit.ly/natahouse_github

**Comment by YuriBispo** [comment]
A vaga ainda está em aberto?

**Comment by megandavulpi** [comment]
> A vaga ainda está em aberto?

Olá @YuriBispo, a vaga está em aberto sim!

**Comment by YuriBispo** [comment]
Ok, apliquei pra vaga!

**Comment by megandavulpi** [comment]
> Ok, apliquei pra vaga!

👏👏
