### ISSUE TITLE
[Rio de Janeiro/RJ] Desenvolvedor PHP Pleno

### ISSUE THREAD

**Issue by felipefernandestouch** [frontendbr/vagas#156]
## Descrição da vaga

Estamos buscando um novo membro para nossa equipe que colabore na implementação de novos projetos para nossos clientes e também dar eventual manutenção em projetos antigos. 

## Local

Alocado, Rio de Janeiro - Botafogo

## Benefícios

- Vale transporte
- 2 monitores e um mac bacana!
- Temos copa para almoçar no local
- TV e Videogame

## Requisitos

**Obrigatórios:**
- Conceitos do padrão MVC bem definidos
- Conceitos de OOD bem definidos
- Experiência com modelagem de banco de dados
- PHP 5 (avançado)
- CakePHP 2 (avançado)
- Laravel 5 (avançado)
- WordPress (intermediário)
- Composer
- Git
- Git flow
- MySQL
- MariaDB
- SQL avançado
- Familiaridade com configuração de ambientes Linux

**Desejáveis:**
- HTML (intermediário)
- CSS (intermediário)
- SASS ou LESS
- Familiaridade com Bootstrap
- JavaScript (intermediário)
- jQuery (intermediário)
- VueJS 
- AngularJS
- React
- Bower
- GruntJS
- GulpJS

**Diferenciais:**
- Inglês
- projetos opensource
- experiências com projetos ágeis

## Contratação

CLT ou PJ a combinar

## Nossa empresa

A Touch é uma Agência Criativa especializada em Design, Tecnologia e Comunicação Digital localizada no Rio de Janeiro que atende clientes nacionais e internacionais.

## Como se candidatar

Por favor envie um email para trabalhe@estudiotouch.com com seu CV anexado - enviar no assunto: Quero ser PHP Pleno na Touch!

**Comment by hugodutra** [comment]
Já trabalhei na Touch e recomendo!

O ambiente é muito bacana e os sócios são gente boa demais!

**Comment by LFeh** [comment]
Valeu pela vaga @felipefernandestouch, mas optamos por fechar para nao fugir muito do tema do repositorio :)

**Comment by felipefernandestouch** [comment]
Poxa, depois que eu publiquei que percebi que era apenas de front. Foi mal. Obrigado!

**Comment by eduardojmatos** [comment]
@felipefernandestouch parece que tem um repo de PHP de vagas, forkado daqui: https://github.com/phpdevbr/vagas
