### ISSUE TITLE
[São Paulo] Front-End Developer na Webhub

### ISSUE THREAD

**Issue by niltos** [frontendbr/vagas#1562]
## Descrição da vaga

A Webhub está em busca de devs front-end com criatividade e paixão pelo que fazem para integrar parte de seu time de desenvolvimento. A pessoa ideal para esta oportunidade deverá ser capaz de desenvolver interfaces de usuário para aplicações web e mobile, trabalhando em conjunto com devs back-end e integrantes do time de UI/UX, e será responsável por:

- Desenvolver e implementar novas funcionalidades e interfaces de usuário no front-end de aplicativos web e mobile
- Criar protótipos do front-end para novos produtos
- Identificar e atuar na solução de gargalos de performance do front-end
- Colaborar com equipes de produto, back-end e arquitetura da informação para o desenvolvimento de novos projetos

## Local

Escritório, Liberdade - São Paulo (3 minutos do metrô)

## Benefícios

- Horário Flexível
- Incentivo para participação em eventos
- Auxílio para cursos

#### Diferenciais

- 1 PS4 com jogos na área de descanso
- Happy friday no escritório com refrigerente, cerveja e coxinhas

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento de interfaces utilizando HTML e CSS, incluindo media queries, acessibilidade e compatibilidade cross-browser.
- Experiência com desenvolvimento utilizando JavaScript, incluindo programação funcional, programação assíncrona e ES6
- Conhecimentos em otimização para performance de front-end
- Experiência com uso de SASS e ferramentas de pré-processamento como Gulp e Webpack
- Habilidade de descobrir soluções performáticas para problemas complexos
- Habilidade de comunicação e de trabalho em time

**Desejáveis:**
- Experiência com BDD e testes unitários
- Conhecimentos em orientação a objetos no JavaScript
- Experiência com VueJS / ReactJS ou Angular 4
- Experiência com CSS flexbox e grid

**Diferenciais:**
- Noções de SEO
- Noções de UI e UX

## Contratação

PJ a combinar

## Nossa empresa

A Webhub é uma empresa nova, mas que já nasceu com grandes responsabilidades. Uma delas é gerar grande valor para clientes que são grandes em seus segmentos, através do desenvolvimento de soluções digitais com alto uso da tecnologia e de visão de negócios. Tudo isso comprometido com o sucesso do cliente e não apenas com a entrega de um sistema. Além disso, queremos sempre gerar valor para os nossos colaboradores e sociedade, com uma atuação focada na ética e transparência. 

Acreditamos no poder da mistura trabalho duro e inteligente, skill técnico fod..., bom relacionamento, atitude, humor e no resultado que isso gera para todo o grupo.

## Como se candidatar

O primeiro passo é preencher o formulário disponível [neste link](http://careers.webhub.com.br/jobs/front-end).

## Labels

- Alocado
- PJ
- Pleno
- Sênior

**Comment by ahlechandre** [comment]
tive um ataque epilético com o background cor-de-rosa e não consegui concluir o formulário

**Comment by LeticiaLCavalcanti** [comment]
Quero! vou preencher <3

**Comment by VictorHCord** [comment]
Preenchi

**Comment by thaisfalbo** [comment]
Preenchido :)

**Comment by niltos** [comment]
Vaga ainda aberta!

**Comment by niltos** [comment]
Ainda temos uma vaga em aberto.

**Comment by oniltos** [comment]
Estamos com a vaga em aberto novamente.

**Comment by halkliff** [comment]
@oniltos Há a possibilidade de trabalho remoto?
