### ISSUE TITLE
[São José dos Campos] React Developer na Sistema Pallas

### ISSUE THREAD

**Issue by hugofialho** [frontendbr/vagas#1563]
## Local

São José dos Campos, Jardim das Indústrias, remoto até 3 dias da semana, vai depender da nossa sinergia.

## Benefícios

- VT
- VR
- Horário flexível

## Requisitos

**Obrigatórios:**
- Experiência sólida com React JS
- Git

**Diferenciais:**
- experiência com Material-UI
- experiência com arquitetura serverless, especialmente Firebase

## Contratação

CLT

## Como se candidatar

Por favor envie perfil do Github e currículo para vagas@sispallas.com.br

## Labels

- Alocado
- Remoto
- CLT
- Júnior
- Pleno

**Comment by ribeiroevandro** [comment]
Enviado

**Comment by hugofialho** [comment]
@ribeiroevandro recebi seu email, mas não contém anexo

**Comment by vinirossi** [comment]
Quais são os requisitos para Júnior?

**Comment by hugofialho** [comment]
@vinirossi obrigatório conhecimento em react apenas

**Comment by GabrielReis94** [comment]
Ainda tem Vagas para Junior ? é totalmente remoto ? obrigado att
