### ISSUE TITLE
[Curitiba/PR] Desenvolvedor Front-End - Pleno/Sênior - Freelancer

### ISSUE THREAD

**Issue by mateusmachado** [frontendbr/vagas#1564]
Desenvolvedor Front-End - Freelancer- Curitiba/PR

Principais responsabilidades/atividades: Desenvolvimento Front-end de interfaces fundamentadas em conceitos de UX/UI para o sistema. Projeto de impacto no setor de meteorologia, com o objetivo final de ser disponibilizado a nível internacional após ser finalizado.

Requisitos: 

Javascript
HTML
JQuery
Ajax
Bootstrap
Experiência no desenvolvimento de interfaces fundamentadas em UX/UI.

Vai trabalhar remoto mas terá que comparecer em algumas reuniões em Curitiba com o time. 

Interessados encaminhar CV para rh@jointecnologia.com.br

**Comment by danielswater** [comment]
Home Office?

**Comment by soutothales** [comment]
tbm gostaria de saber se é home office

**Comment by LFeh** [comment]
@mateusmachado Consegue preencher mais informações?

Nível? Alocado ou Remoto?

**Comment by danielswater** [comment]
Mandei meu CV, mas infelizmente, fica difícil p mim ir a Curitiba, mesmo esporadicamente :(

**Comment by fejaum** [comment]
Se fosse Full Remoto até mandava, não tenho como ir pra CWB.

**Comment by pachecovit** [comment]
Enviei o meu, consigo comparecer em ctba conforme solicitado. :)
