### ISSUE TITLE
[Curitiba/PR] Front-End Developer na MJV Technology & Innovation

### ISSUE THREAD

**Issue by frichardben** [frontendbr/vagas#1566]
## Local

Local de atuação: bairro Hauer 

## Benefícios

- Plano de saúde
- Plano Odontologico 
- VR 

## Requisitos

**Obrigatórios:**

•  HTML5
•  CSS3
•  JavaScript e jQuery
•  Bootstrap
•  Mobile First

**Desejáveis:**
•  Experiência com algum CMS (Ex.: Wordpress)
•  Experiência com versionador de código (SVN ou Git)

## Contratação

CLT 

## Nossa empresa

MJV Technology & Innovation, consultoria dedicada a transformar negócios e solucionar desafios complexos para levar ao mercado soluções inovadoras em produtos e serviços, está busca de alguns Back - End para atuar em cliente no ramo financeiro!

A nossa matriz é carioca mas estamos presentes em São Paulo, Curitiba e em unidades internacionais nos EUA, França, Inglaterra, Itália e Portugal.

A MJV acredita que uma equipe colaborativa enriquece a qualidade do nosso trabalho e produz resultados transformadores.

## Como se candidatar

Envie seu currículo para: rhcuritiba@mjv.com.br

## Labels

- Alocado
- CLT
- Júnior
- Pleno

**Comment by victorhsantiago** [comment]
Seria possível trabalhar em São Paulo?
