### ISSUE TITLE
[Amsterdam] Senior FrontEnd Developer na Endouble

### ISSUE THREAD

**Issue by renancouto** [frontendbr/vagas#1568]
## [Descrição da vaga](https://workingatendouble.com/vacancies/senior-frontend-developer-product-development-endouble-amsterdam-2/)

As our new Senior Front-end Developer, you will:

- Improve the existing Career Site Builder (CSB) framework
- Add reusable features
- Automate tests (e2e-, unit-, snapshot and integration tests)
- Assist and educate the teams that work with the framework.

You will do this in close cooperation with the team’s manager, PO, the DevOps team and our design department.

**All EU-citizens are welcome to apply as long as you’re a true pro and have a good command of the English language. For developers from outside the EU-zone you are required to have a working permit for the EU, we will help you with that.**

*This job is located in the Netherlands, so please only apply if you are a resident in the Netherlands or willing to move here.

## Local

Amsterdam

## Benefícios

- A salary between €4000 and €4600
- An education budget of 4% of your yearly salary.
- Thorough peer reviews to improve your hard and soft skills.
- International projects in multinational teams.
- A place in an informal, innovative and fast growing company (FD Gazelle Award 2013, 2014 & 2015).
- Top 10 Best Employer New Heroes (NRC Career).

#### Diferenciais

- A standing desk for enhanced ergonomics.
- Free (good) coffee and tea, soft drinks, sodas and a daily lunch.
- Gadgets like a PS4, a pinball machine and a foosball table for the more nostalgic among us 😉

## Requisitos

The ideal candidate for the Senior Frontend Developer position should meet the following job requirements:

- At least three years of front-end development experience
- Extensive knowledge of and proficiency in JS. Specifically: ES6
- Proficient in working with React v16.0
- Ability to write (unit) tests (Jest, Karma, Mocha); mocking, spying, async
- Basic understanding of what accessibility (WCAG) is, what the common pitfalls are and how to implement it properly
- Experienced in performance optimisations
- Working knowledge of Webpack
- Working knowledge of, and proficiency in, CSS3/4 and latest additions like grid layouts
- Proficient in working on the command line
- Mobile-first development approach
- Experienced in debugging javascript applications
- Knowledge of modular architectures

## Contratação

32-40 hours

## Sobre a empresa

Endouble specialises in the creation and optimisation of career platforms, or ‘Talent Acquisition Platforms’ as we call them. So what’s a specialist in career platforms without it’s own? Exactly! You are at the right place to find out more about us.

[More here](https://workingatendouble.com/get-to-know-us/)

## Como se candidatar

[Apply here](https://workingatendouble.com/apply/?post_id=984&vacancy_id=97621b0f-06d3-454e-b04a-497fdecdd913)

## Labels

- Alocado
- Sênior
- Relocação

## Vagas relacionadas

Há mais vagas (inclusive para FrontEnd developers de outros níveis) em nosso site:
https://workingatendouble.com/vacancies/

**Comment by malbernaz** [comment]
link doesn't work : (
