### ISSUE TITLE
[São Paulo] Front-End / React na XP Investimentos

### ISSUE THREAD

**Issue by luansmr** [frontendbr/vagas#1575]
## Descrição da vaga

Buscamos Front-End Developer, com experiência, entusiasmo e energia para trazer soluções inovadoras focadas em usuários do mercado financeiro.

Procuramos pessoas com alto nível de comprometimento, foco na solução de problemas e interesse em atuar em projetos de grande porte. Precisamos de desenvolvedores com iniciativa, facilidade de aprendizado, e que estejam disposto a crescer junto com a gente.

Aqui você vai ter muita voz e responsabilidade logo de cara! Nossos desafios crescem no ritmo do nosso crescimento e isso faz com que a gente seja um time muito unido e cooperativo, sempre aprendendo, empreendendo e crescendo juntos!

## Local

Nossa empresa esta localizada em São Paulo na Av. Chedid Jafet, 75 - Torre Sul - Vila Olimpia a frente do Shopping JK Iguatemi.

## Benefícios

- Plano de saúde
- Seguro de vida
- Auxílio creche
- PRL
- VR
- VA
- VT

#### Diferenciais

- Ambiente descontraído e informal
- Cesta de Frutas
- Flexibilidade de horário

## Requisitos

**Obrigatórios:**
- React
- Redux
- HTML
- SASS

**Desejáveis:**
- Clean Code
- Webpack
- VSTS
- Jest

**Diferenciais:**
- Package manager (NPM / Yarn)
- React Native
- SonarQube

## Contratação

CLT

## Nossa empresa

A XP Investimentos é uma corretora de valores brasileira, considerada uma das maiores corretoras independentes do Brasil. A companhia também formalizou a compra do Infomoney e em 2012,  a união de forças com a Prime Corretora. Ja em julho de 2014, anunciou a compra da Clear Corretora por R$90 milhões, e mais recentemente adquiriu a Rico Corretora.

## Como se candidatar

Envie um email para laercio.patricio@xpi.com.br com seu CV anexado e Linkedin.
Assunto: Vaga Front-end - Squad Institucional

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: laercio.patricio@xpi.com.br

## Labels

- Alocado
- CLT
- Pleno
- Sênior

**Comment by gamoridev** [comment]
Enviado!

**Comment by thaisfalbo** [comment]
Enviado! :)

**Comment by ribeiroevandro** [comment]
Enviado!

**Comment by leonardomarcao** [comment]
A XP tem interesse em abrir um API p/ desenvolvedores?
