### ISSUE TITLE
[Rio de janeiro] - Front-End Developer na Working Minds

### ISSUE THREAD

**Issue by katiavidal** [frontendbr/vagas#1578]
Front-End Developer na Working Minds

Qtde vagas: 02, Rio de Janeiro/RJ

O que nós buscamos / Descrição:

Somos um time de especialistas que idealiza, desenvolve e evolui soluções digitais inovadoras. Se você se identifica com esse perfil e gostaria, também, de fazer parte desse super time, então aproveite a oportunidade!

Para desenvolvê-la, é importante possuir experiência em:
Angular 6
Typescript;
Ferramental NPM (Node Package Manager)
Webpack;
HTML5 e CSS3;

## Benefícios

- Contratação CLT
- Vale Refeição e Vale Alimentação
- Vale transporte
- Plano de saúde e Plano Odontológico
- Excelente localização, Centro-RJ

## Requisitos

Formação: Graduação em andamento ou concluída em Ciências da Computação, Tecnologia da Informação, Analise e Desenvolvimento de Sistemas e Correlatas.

Para nós também seria muito interessante ter nesse perfil, um profissional com:
- Conhecimento em React
- Teste unitário utilizando Jest

Um pouco sobre a nossa empresa 
Nós iniciamos a nossa trajetória em 2008 com objetivo de proporcionar aos nossos clientes todo o apoio tecnológico necessário para o desenvolvimento de soluções digitais inovadoras e transformar a maneira de oferecer serviços e se relacionar com o seu público.
 Ao longo desses 8 anos, construímos um sólido portifólio de soluções em plataformas Web, Desktop e aplicativos Mobile. Também participamos de competições internacionais, como o Hello Wolrd Open

## Como se candidatar
O candidato deverá preencher o formulário abaixo, para submeter sua candidatura: http://bit.ly/2PunDTQ

**Comment by vitorregisrr** [comment]
Hey! Por que se faz necessário um curso superior completo? Um programador que domina os requisitos e mais um pouco não bastaria? Grato!

**Comment by katiavidal** [comment]
Vitor, boa noite

Realmente você tem razão.
