### ISSUE TITLE
[São Paulo] Front-End Developer na [Boutique Pool]

### ISSUE THREAD

**Issue by PtkFerraro** [frontendbr/vagas#1579]
## Descrição da vaga

Projeto em ReactJS

## Local

Escritório - Coworking na Av. 9 de Julho

#### Diferenciais

- ambiente descontraído
- horário flexível
- Possibilidade de remoto

## Requisitos

**Obrigatórios:**
-  Bom conhecimento em ReactJS
-  Muito bom em transformar psd em html

**Desejáveis:**
- conhecimentos em .Net Core 2 & C#

## Contratação

PJ a combinar

## Nossa empresa

Startup que vai mudar a forma como grandes marcas contratam agências

## Como se candidatar

Email para patrick@boutique-pool.com

## Labels

- Alocado
- Freela
- PJ
- Pleno
- Sênior

**Comment by ribeiroevandro** [comment]
Enviado
