### ISSUE TITLE
[São Paulo] Front-End Developer na amparo saúde

### ISSUE THREAD

**Issue by vitorabner** [frontendbr/vagas#1582]
## Descrição da vaga

Estamos procurando uma pessoa com conhecimentos mínimos em javascript, html e css com no máximo um ano de experiência.

Não é necessário ter experiência no mercado de trabalho, se tiver algum projeto pessoal ou projeto de faculdade bem legal está valendo. Você terá tempo e apoio para aprender essas tecnologias na empresa.

Tecnologias usadas: vuejs e nodejs.

## Local

Rua Paes Leme, 40 próximo ao metrô Faria Lima / estação Pinheiros da CPTM.

## Contratação

R$ 4000 (PJ), valor inicial. Ajudamos na abertura da empresa.

## Nossa empresa

A Amparo Saúde é uma health tech que iniciou as atividades esse ano, a proposta da empresa é cuidar das pessoas ao longo de suas vidas através de médicos de família e várias outras especialidades. Os dois pilares da empresa são saúde e tecnologia.

O desafio de tecnologia é bem massa: desde desenvolver ferramentas de suporte para enfermeiras, médicos, apis para comunicação com operadoras até trabalhar com grande massa de dados para gerar indicadores e métricas.

O time está iniciando agora então você vai participar de várias discussões e decisões, desde de técnicas até de negócios.

## Como se candidatar

Pode enviar um email direto para mim: vitorabner@ampa.ro enviando curriculum, texto de apresentação, github, linkedin ou qualquer outra coisa que você ache interessante.  

## Labels

- Alocado
- Júnior
- PJ

**Comment by Roger-Melo** [comment]
Que descrição bacana! Uma pena eu não morar em SP :sob:

**Comment by victorhsantiago** [comment]
Gostei muito da proposta! E veio numa boa hora! Enviado!!

**Comment by Possilvio** [comment]
Excelente oportunidade. Enviado! :)

**Comment by rbastiansch** [comment]
Eu vi que colocou alocado, mas não rola remoto em nenhuma hipótese? Haha

**Comment by rodriigovieira** [comment]
Também fiquei na dúvida, remoto em nenhuma hipótese? :(

**Comment by MrS4w** [comment]
Enviado!

**Comment by bianavic** [comment]
Enviei.

**Comment by thaisfalbo** [comment]
Enviado!

**Comment by HidemitsuHashimoto** [comment]
Enviado.

**Comment by LeticiaLCavalcanti** [comment]
Perfeita pra mim!
