### ISSUE TITLE
[REMOTO] Desenvolvedor(a) Sênior na Crawly

### ISSUE THREAD

**Issue by naroga** [frontendbr/vagas#1588]
# Desenvolvedor(a) Sênior

Estamos à procura de um desenvolvedor sênior. Não importa qual seu stack de preferência, se você é um bom desenvolvedor, queremos trabalhar com você!

## Sobre a Crawly

Website: [https://www.crawly.com.br](https://www.crawly.com.br)

Somos uma empresa jovem, com menos de 2 anos de idade. Nossa equipe é pequena, mas nossa tecnologia é gigante! Já somos responsáveis por sistemas com **dezenas de milhões de acessos diários**. Nos orgulhamos de nossa capacidade de desenvolver software de altíssima performance e de montar estruturas na nuvem capazes de entregar resultados com precisão, qualidade, performance, segurança, estabilidade e resiliência!

Atuamos nos setores de `data mining` e de `machine learning`, desenvolvendo robôs que varrem a internet buscando e consolidando informação, para que possamos extrair inteligência dos dados coletados e ajudar nossos clientes a transformar informação em ação.

Estamos sempre trabalhando com o que há de mais robusto em tecnologia, sem medo de experimentar novas tecnologias e inovar na solução de problemas.

**Nossa equipe é 100% sênior.**

## Sobre o trabalho

Procuramos alguém para nos ajudar a:

* Desenvolver um produto próprio, envolvendo mineração de dados em centenas de sistemas ao redor do país;
* Evoluir nossos processos de desenvolvimento, integração contínua e deploy contínuo;
* Fazer peer review de código desenvolvido in-house;
* Desenvolver e dar manutenção em robôs de coleta de dados de nossos clientes;
* Sugerir melhorias nas técnicas de desenvolvimento, operação e testes;
* Tornar nosso ambiente de trabalho mais divertido e descontraído;

## Requisitos

* Ser bom desenvolvedor, não importando a linguagem;
* Dominar as nuances do protocolo HTTP(s), conhecendo os métodos, headers e para que servem;
* Compreender os paradigmas de desenvolvimento para WEB, mesmo que em alto nível (o que são AJAX, CORS, o que é o DOM, como funciona o modelo cliente-servidor, as principais diferenças entre os principais modelos de desenvolvimento em diferentes linguagens backend, etc);
* Conhecimento básico de modelagem de infraestrutura na nuvem (é importante manter alguns princípios básicos de arquitetura em mente, ao desenvolver as aplicações, mesmo que infraestrutura não seja sua área);
* Ter muita vontade de aprender, mexer com aplicações diferentes (não fazemos programa de padaria aqui) e gostar de desafios;
* Ter hardware próprio para trabalhar (trabalho remoto!);
* Ter uma boa conexão com a internet (vamos pagar sua conta de internet, não se preocupe!);

## O que oferecemos

* **FINAL DE SEMANA DE TRÊS DIAS: É isso mesmo. Você não precisa trabalhar às sextas-feiras (ou às segundas, se preferir).**
* Trabalho remoto! Trabalhe da sua casa, de um coworking, da praia, da boate. Encontre o seu ambiente, conecte-se à internet, entre no slack e vamos; Pode trabalhar até de pijama :slightly_smiling_face:
* Vale-internet: como exigimos uma conexão de qualidade razoável com a internet, nós assumimos esse custo. Coloque um link de internet legal aí que nós assumimos essa conta;
* Salários bem competitivos, com reajustes periódicos! Nada de chefe ganhando bem enquanto a equipe passa dificuldade. Somos um time e crescemos como tal!
* Possibilidade de gratificações, de acordo com o rendimento anual da empresa;
* Autonomia e independência - equipe sênior não precisa de microgerenciamento, né?
* Horas flexíveis;
* Time descontraído, bem humorado e sempre disposto a ajudar;
* Possibilidade de treinamentos, comparecimento a eventos/conferências, material didático (livros, cursos online, etc) custeados pela empresa;
* Possibilidade de stock na empresa;

## Regime da contratação

PJ ou CLT.

## Compensação proposta

Valor a combinar + vale-internet + o lindíssimo final-de-semana de três dias, além do que já foi listado acima.

## Como aplico?

Só preencher seus dados [aqui](https://crawly.recruitee.com/#/).

**Comment by matheus-rosin** [comment]
@naroga pode passar algum email seu para eu falar contigo?

**Comment by rodineicosta** [comment]
Aplicado.

**Comment by mart2222** [comment]
Muito Show!!!

**Comment by LFeh** [comment]
Passando para elogiar a vaga, parabéns pela mentalidade @naroga :)

**Comment by rodrigo-fonseca** [comment]
Passando apenas para parabenizar pela vaga :)

Em qua, 28 de nov de 2018 às 09:55, Pedro Cordeiro <notifications@github.com>
escreveu:

**Comment by ViniciusGularte** [comment]
Por mais vagas assim no grupo :smile:

**Comment by felipepatricio** [comment]
Isso é que é vaga! hehe :clap: :clap: :clap:

**Comment by viniciusromero** [comment]
Top a vaga! Deu vontade largar tudo aqui haha. Parabéns!

**Comment by kivervinicius** [comment]
enviado

**Comment by thiagog3** [comment]
Aplicado! 🤘

**Comment by JeanPaulll** [comment]
### Aplicado!
