### ISSUE TITLE
[Rio de Janeiro] Front-End Developer na [TOTVS]

### ISSUE THREAD

**Issue by ricardo-mello** [frontendbr/vagas#1589]
## Descrição da vaga

Estamos criando um produto do zero com novas tecnologias.
A nossa equipe está sendo montada para juntos criarmos um projeto muito ambicioso dos pontos de vista de negócio e desenvolvimento!
Já dominamos o mercado com um produto antigo em desktop e agora queremos lançar essa nova aplicação Web integrada a apps que também serão desenvolvidos, oferecendo a melhor experiência aos nossos clientes.
O mercado do ramo que atuamos aqui no Brasil já é dominado pela TOTVS, agora estamos querendo dominar o mundo. O projeto já está nascendo internacionalizado, muitos desafios técnicos, qualidade e performance é o que buscamos!

## Local

Escritório, Centro - Rio de Janeiro

## Benefícios

Plano de saúde
Plano odontológico
Seguro de vida
VR + VA
Vale transporte

#### Diferenciais

- Lounges com café, chocolate e outras bebidas FREE
- Sala de Jogos
- PDI(Plano de Desenvolvimento Individual)
- Equipe unida
- Palestras, meetups e estamos abertos sempre a novas idéias para o time crescer

## Requisitos

**Obrigatórios:**
- Saber escrever código limpo e legível
- Experiência com Javascript
- Forte base em programação orientada a objeto
- Pré-processadores CSS
- Inglês técnico (pois nosso código é feito em inglês)
- Conhecer o básico de versionamento com GIT
- Saber como funciona o protocolo HTTP e o padrão REST
- Conhecimento em alguma biblioteca ou framework JS (React, Angular ou Vue.js)

**Desejáveis:**
- Amar Javascript
- Experiência no desenvolvimento de componentes reutilizáveis
- Ter sede de aprender e trocar conhecimento com a equipe
 
**Diferenciais:**
- Contribuição em projetos open source
- Experiência com Angular ou Ionic e Typescript

## Contratação

CLT - à combinar

## Nossa empresa

A TOTVS é uma empresa brasileira de software, serviços, plataforma e consultoria. É líder absoluta no Brasil e na América Latina e está entre as maiores desenvolvedoras de sistemas de gestão integrada do mundo.

## Como se candidatar

Por favor envie um email para ricardo.franca@totvscmnet.com.br com seu CV anexado e com o link do seu linkedin - Enviar no assunto: Vaga Front-End na TOTVS

## Labels

- Alocado
- CLT
- Pleno

**Comment by yashin5** [comment]
Perdão, sei que está descrito que é para pleno, mas teria alguma vaga para front jr?
Abraços
