### ISSUE TITLE
[São Paulo] Desenvolvedor Front-end Sr/Pl

### ISSUE THREAD

**Issue by evansantos** [frontendbr/vagas#159]
## Descrição da vaga

Atuar com desenvolvimento Frontend utilizando tecnologias de ponta em uma Fintech
## Local

O escritório fica em pinheiros próximo à praça Benedito Calixto, São Paulo, Capital.
## Benefícios
- Remuneração em linha com o mercado
- Ambiente é realmente bem legal, temos uma série de eventos internos, como palestras de pessoas de renome no mercado, sessões de informação sobre alguns temas lideradas pelos próprios colaboradores entre outras.
## O que oferecemos
- Espaço, estímulo e suporte para se desenvolver e crescer de forma meteórica
  Aprendizado constante
- Interação com outras startups (F(x), Easycarros, Choppup, Singu) da venture builder eGenius (grupo com o qual temos uma joint venture)
- Contato direto com grandes empreendedores
- Oportunidade de contribuir efetivamente para a evolução de uma startup em crescimento acelerado (aqui, suas ações e opiniões podem causar grandes impactos)
- Ambiente descontraído e dinâmico
## Requisitos

**Obrigatórios:**
- Domínio em lógica de programação, orientação a objetos e design patterns
- Ter trabalhado com framework AngularJS 
- Sólidos conhecimentos em HTML/CSS/Javascript
- Experiência com pré-processadores (less, sass, stylus…)
- Experiência com ferramentas automação de tarefas (Gulp, Grunt, Webpack…)
- Experiência na construção de aplicações responsivos
- Conhecimento de framework de testes (Karma, Mocha, Jasmine…)

**Diferenciais:**
- Ter trabalhado com template engines (Handlebars, MustacheJS…)
- Conhecimento em alguma linguagem para backend (NodeJS, PHP, Python, etc…)
- Vivência com métodos ágeis de desenvolvimento como XP, Scrum, Kanban ou variações do Lean
## Contratação

PJ a combinar
## Sobre a BeeTech

A BeeTech é uma empresa de fintech (tecnologia aplicada a serviços financeiros) que atua no mercado de câmbio por meio de duas plataformas:
[www.beecambio.com.br](www.beecambio.com.br): primeira correspondente cambial totalmente online e com capacidade para operar venda de 15 moedas estrangeiras em 40+ cidades espalhadas por todo o território nacional. 
[www.remessaonline.com.br](www.remessaonline.com.br): primeira plataforma independente para envios de valores para o exterior

Nossa visão é ser um dos maiores e o mais rentável player do mercado de câmbio brasileiro. Para tanto, precisamos de um time que reúna as competências necessárias, que tenha ambição e determinação suficientes para se juntar a nós e fazer parte deste sonho. Não buscamos apenas bons profissionais, mas sim pessoas inteligentes, que amam o que fazem e tenham vontade de fazer coisa grande. 
Estamos buscando um desenvolvedor que, assim como a gente, tenha um perfil ousado e empreendedor: gente ligada em tecnologia, com brilho nos olhos e que goste de evoluir com novas experiências, que queira construir produtos e soluções incríveis. 
Para isso temos um nível de exigência alto com qualidade e buscamos um front-end que tenha atenção aos mínimos detalhes, que se preocupa com o pixel que está no lugar errado, com a animação que não está tão smooth, enfim, que ama o que faz.
## Como se candidatar

Envie e-mail para marcio@egenius.com.br e vagas@beecambio.com.br. Assunto “Vaga FrontEndBR - BeeCâmbio – SEUNOME ”.

**Comment by evansantos** [comment]
Achamos um frontend Senior, mas abriu vaga para outro senior dai estou abrindo outra issue! =)

**Comment by camilatigre** [comment]
@evansantos 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by evansantos** [comment]
Não, @camilatigre desculpa a demora a responder
