### ISSUE TITLE
[São Paulo] Front-End Developer na GUNI

### ISSUE THREAD

**Issue by megandavulpi** [frontendbr/vagas#1590]
### Sobre a empresa: Guni

Lançado em 2016, a rede social Guni permite que os usuários compartilhem informações e eventos relacionados à sua faculdade de maneira colaborativa. Nosso objetivo é abranger todas as esferas da vida universitária, sociais e acadêmicas. Além disso, oferecemos diversas soluções para organizadores de eventos e empresas que queiram se comunicar com esse público, sempre gerando valor ao universitário. Se você não conhece, dá uma olhada nas app stores!

### Descrição: Requisitos:

Experiência Angular e Ionic;
Pró-atividade
Trabalho em equipe
Responsabilidade
Profissionalismo

### Diferenciais:

Experiência com UX

### Oferecemos:

Salário compatível com o mercado;
VR (R$500,00)
Ambiente de startup; 
Clima descontraído;
Fazer parte de uma equipe foda composta de 5 profissionais e que só tem a crescer. :)

### Seus desafios serão:

Programar, codificar e testar os projetos criados. 
Ajudar a idealizar novos projetos.
Acompanhamento de entregas.

### O que buscamos?

Estamos buscando alguém que será liderado mas que também tenha voz para participar e ajudar a idealizar novos projetos, trabalhe em conjunto com a equipe e que seja mais uma peça chave para o crescimento do Guni.

### Labels:

CLT
Pleno 
Alocado

### Candidatar: http://bit.ly/gunifront_github

**Comment by LFeh** [comment]
Qual a forma de contratação?

**Comment by megandavulpi** [comment]
> Qual a forma de contratação?

Olá, Felipe! 
A forma de contratação é CLT.

**Comment by LFeh** [comment]
Vlw!
