### ISSUE TITLE
[Remoto] Front-End Developer (HTML, CSS, JS)

### ISSUE THREAD

**Issue by hmaesta** [frontendbr/vagas#1591]
Busco developer para codificar página de vendas (landing page) já desenhada. 

É necessário que a página seja entregue responsiva e totalmente funcional – em HTML, CSS e JS (pode usar jQuery). É obrigatório que o desenvolvimento seja feito por você, sem uso de "editores visuais" como Visual Composer, Elementor e similares. (Pode usar frameworks como Bootstrap, Bulma, etc.)

As páginas são feitas por designer com experiência em desenvolvimento, mas que no momento não consegue atender a demanda de codificar. Dessa forma, o risco de "impedimento técnico" é minimizado (mas ainda assim há flexibilidade quando surgir esse problema).

As páginas são entregues em imagem e/ou arquivo Sketch ou Zeplin. Os assets também já serão entregues prontos (ícones, imagens usadas na página, fontes, etc).

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento web
- Portfólio com pelo menos 3 trabalhos
- Saber usar [Flexbox do CSS](https://origamid.com/projetos/flexbox-guia-completo/) 
- Ser atencioso com detalhes e honrar prazos
- Git básico (commitar projeto pro Github)

**Desejáveis:**
- Experiência com landing pages
- Experiência com lojas online e técnicas de conversão
- [SCSS](https://sass-lang.com/)

## Como se candidatar

Envie um email para hmaesta+vfd@gmail.com com seu **portfólio**.
Título do e-mail: `Freela: Front-End Developer (HTML, CSS, JS)`

Irei enviar mais informações por e-mail e assim você poderá passar uma estimativa de preço e prazo.

⚠️ **E-mails sem portfólio não serão respondidos** e enviar CV é indiferente.

## Labels

- Remoto
- Freela

**Comment by RicardoWEBSiTE** [comment]
Aplicado

Em qui, 29 de nov de 2018 às 07:59, Hugo Maestá <notifications@github.com>
escreveu:

**Comment by leandroatallah** [comment]
Enviado!
