### ISSUE TITLE
[Belo Horizonte - MG] Front-End Developer na SEMINOVOS BH

### ISSUE THREAD

**Issue by megandavulpi** [frontendbr/vagas#1592]
### Sobre a empresa: SEMINOVOS BH

O maior portal de anúncio de veículos de Belo Horizonte.

### Descrição: Ocupações do cargo

O profissional será responsável pelo desenvolvimento Front End da aplicação da SemiNovos BH. Ele irá desenvolver e manter aplicativos hibridos com o framework Ionic

Dar manutenção no front de alguns sites, como usabilidade e interface.

### Requisitos

Javascript
HTML 5
CSS 3
Web Components
Bootstrap
Git

### Diferenciais

Ionic
Node.js
SASS
Webpack
PHP
Docker
Experiência com UX
Git Flow

### Benefícios

O profissional será contratado com o regime de contratação CLT, com isso terá os seguintes benefícios.

Plano de saúde coparticipativo;
Transporte;
Alimentação.

### Aptidões e qualidades

O profissional deve ser proativo, autodidata, saber tomar decisões baseadas em dados, aptidão para liderança, saber trabalhar em equipe e ser organizado

### Labels: 

CLT
Alocado
Pleno

**Comment by robzone** [comment]
https://anuncicarbh.com
