### ISSUE TITLE
[São Paulo/SP]  Front End Developer na Programmer's

### ISSUE THREAD

**Issue by ProgrammersRecrutamento** [frontendbr/vagas#1598]
## Descrição da vaga

•	-C# Development 
•	-General Web Development Concepts & Architecture 
•	-MVC with C# High HTML & CSS 
•	-Javascript 
•	-TypeScript
•	-AngularJS or similar 
•	-Dependency Injection 
•	-Git 
Desejável:
•	-Azure General Knowledge 
•	-Theoretical Knowledge about Tests and its Concepts Desirable Unit Tests development w/ C# 
•	-UI Tests with Selenium or similar 

## Local

 São Paulo - SP

## Benefícios

- Plano de saúde
- Seguro de vida
- VR 
- VA
-Auxílio Combustível
-GymPass
_ PPR
- Auxílio creche

## Requisitos

**Obrigatórios:**
•	-C# Development 
•	-General Web Development Concepts & Architecture 
•	-MVC with C# High HTML & CSS 
•	-Javascript 
•	-TypeScript
•	-AngularJS or similar 
•	-Dependency Injection 
•	-Git 
Desejável:
•	-Azure General Knowledge 
•	-Theoretical Knowledge about Tests and its Concepts Desirable Unit Tests development w/ C# 
•	-UI Tests with Selenium or similar 

## Contratação

CLT

## Como se candidatar

Por favor envie um email para ana.fraga@programmers.com.br com seu CV anexado - enviar no assunto: Vaga Front End

**Comment by ReactGirl** [comment]
Front End development.
Obrigatorio: C#.

**Comment by LFeh** [comment]
@ProgrammersRecrutamento Verdade, essa vaga é Fullstack
