### ISSUE TITLE
[São Paulo] Front-end Engineer

### ISSUE THREAD

**Issue by eduardojmatos** [frontendbr/vagas#16]
## Descrição da vaga

BankFacil is hiring front-end developers to expand our team and to face the new business challenges. We're rewriting a complex application with Ember.js, EcmaScript 2016, Babel.js, among others new cool technologies with good practices.

## Local

Office, at São Paulo - Itaim Bibi (near Berrini or Vila Olimpia train).

## Benefícios

- Competitive compensation package;
- Transportation support;
- Meals support;
- Health plan;
- Gym plan;
- English classes;
- A powerful machine or BYOD (bring your own device);
- Shower and changing room for people who come by bike;
- Sundeck and barbecue grill;
- Strong community friendly, supporting events and meetups;
- Open source collaboration;

## Requisitos

**Required:**
- Semantic HTML;
- Scalable and modular CSS architecture, knowing good patterns like SMACSS;
- Modular Javascript development, with design patterns (for example: Mediator and Pubsub), with or without MV* frameworks;
- DOM manipulation without having needs of libs such as jQuery or Zepto;
- Knowledge of cross browsers problems and how to solve them;
- Good practices in how to optimize web pages to make the user experience sweeter;
- Knowing how to implement tests in JS;

**Plus:**
- Experience with Ember.js or another single-page application framework will be a plus;

## Contratação

- CLT

## Nossa empresa

- We value individual and team effort, we expect high performance of every everyone in the team;
- We have a relaxed environment and at the same time, extremely productive;
- We want to be happy at our work environment and also in our personal lives;
- We want to grow both as individuals and as professionals;
- We constantly share knowledge related and unrelated to our individual tasks;
- We thrive for knowledge and we love you to get out from your comfort zone, always!;
- We believe and contribute to the engineering community;
- We celebrate every single victory;
- You need to love what you do! 

## Como se candidatar

Follow the Recruiterbox link to apply for this position: https://bankfacil.recruiterbox.com/jobs/fk0h1mc/

**Comment by LFeh** [comment]
Linda vaga :)

**Comment by eduardojmatos** [comment]
@LFeh :smile:

**Comment by elvisdetona** [comment]
What skills the front-end developer needs to have?
UI, Designer or Engineer?

**Comment by geovanerocha** [comment]
Boa vaga!

**Comment by eduardojmatos** [comment]
@elvisdetona it's more a Engineer developer :)

**Comment by eduardojmatos** [comment]
@geovanerocha se inscreve lá! :)

**Comment by LFeh** [comment]
A vaga foi preenchida?

**Comment by camilatigre** [comment]
@eduardojmatos 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

**A pessoa que preencheu a vaga foi encontrada através desta issue?**
a) Sim
b) Não
c) Não tenho certeza

**Comment by eduardojmatos** [comment]
b)

Excelente ideia :)
