### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor Front-End - MundiPagg

### ISSUE THREAD

**Issue by charlescarrari** [frontendbr/vagas#160]
<img src="http://checkoutstaging.mundipaggone.com/HotSite/V1/img/meetmundi.png" alt="MundiPagg" width="120" align="right" vspace="15" hspace="0"/>

## Descrição da vaga

Se você é desenvolvedor Front-End, _manja dos paranauês_ do JavaScript / Angular.JS, é loucamente apaixonado por tecnologia e adora desafios incríveis, é você que procuramos.

Abaixo listamos alguns dos conhecimentos que esperamos de você. Ah, esperamos que você também seja uma pessoa bem legal e descontraída. 😄 
## Local

[Escritório, Centro - Rio de Janeiro](https://www.google.com.br/maps/place/MundiPagg/@-22.9072867,-43.1709332,17z/data=!4m12!1m6!3m5!1s0x9981e7223da871:0x4f382a5312ba5fe3!2sMundiPagg!8m2!3d-22.9072867!4d-43.1687445!3m4!1s0x9981e7223da871:0x4f382a5312ba5fe3!8m2!3d-22.9072867!4d-43.1687445)
## Benefícios
- Vale refeição/alimentação;
- Vale transporte;
- Plano de saúde;
- Horário flexível;
- Ambiente de de trabalho descontraído;
- Snackbar dentro do escritório;
- Entretenimento: Vídeo games, sinuca, mesa de poker, etc;
## Conhecimento Técnico
- Ninja dos JavaScripts;
- AngularJS;
- Web Components;
- Node.JS;
- HTML 5 / CSS / LESS / SASS;
- GIT;
- Scrum;
- API / RESTful;
## Um pouco sobre a MundiPagg
- [Nosso Site](https://www.mundipagg.com/)
- [Documentação](http://docs.mundipagg.com/)
- [Blog: Ambiente de Trabalho](http://blog.mundipagg.com/um-ambiente-agradavel-de-trabalho-aumenta-a-produtividade/)
## Como se candidatar

Envie um e-mail para **tbarradas@mundipagg.com** com seu CV anexado - enviar no assunto: `#FRONT_END ${SEU_NOME}`## Descrição da vaga

**Comment by LFeh** [comment]
CLT?

Pleno? Senior?

**Comment by charlescarrari** [comment]
Opa foi mal @LFeh. CLT, Junior, Pleno e Senior. ;)

**Comment by lucianobarauna** [comment]
eu enviei um currículo semana passada 
@charlescarrari a vaga ainda está aberta ?

**Comment by charlescarrari** [comment]
Estamos avaliando possíveis candidatos ainda @lucianobarauna mais fica tranquilo que entraremos em contato. Abraços. ;)

**Comment by camilatigre** [comment]
@charlescarrari 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by charlescarrari** [comment]
@camilatigre Resposta: b) Não

;)
