### ISSUE TITLE
[Remoto] Frontend developer na Foton

### ISSUE THREAD

**Issue by jaburcodes** [frontendbr/vagas#1600]
HIRING] [REMOTE] [REACTNATIVE] [JUNIOR/PLENO]

Estou contratando na Foton para construir Mobile apps direto do Silicon Valley!!

Estamos fazendo coisas super bacanas como por exemplo: Face Recognition e muito Blockchain(EOS). Sempre com ReactNative.

Trabalhamos com as tecnologias mais atuais do mercado e proporcionamos o melhor ambiente remoto que um dev possa querer, compro todos os cursos que você consiga consumir e estamos nos organizando para nossa primeira coding House!!!

Hoje estou com uma vaga bem bacana pra trabalhar direto comigo, se você quer evoluir rápido prometo transformar você em um monstro do Mobile, faça o teste e me manda:
https://github.com/FotonTech/Challenge-RN-ReduxSaga

Requisitos.
1. ReactNative
2. Redux
3. CSS
4. Se comunicar em inglês, mesmo que básico.
5. Ter um Mac(pode ser Hackintosh), sei que isso torna as coisas mais complicadas, mas a maioria dos nossos apps são para IOS.

Prometo que o trabalho é super legal e cheio de experiências desafiadoras, obrigado por ter lido até aqui :heart:

**Comment by marcelorubim** [comment]
Qual a forma de contratação? E a faixa salarial?

**Comment by JeanPaulll** [comment]
Qual a forma de contratação? E a faixa salarial?

**Comment by andersonms1** [comment]
Boa noite!
Qual é a data de entrega do teste? @jaburcodes
