### ISSUE TITLE
[Munich] Frontend Developer na Personio

### ISSUE THREAD

**Issue by rafaelmotta** [frontendbr/vagas#1602]
## Description
We seek a creative problem solver with strong experience in the latest frontend technologies.

* Profound experience with React.js or similar frameworks (Angular, Backbone, Vue)
* Experience with bundlers like Webpack
* Experience implementing and consuming RESTful clients
* Knowledge and understanding of best practices in CSS / SASS
* Understanding of distributed version control systems such as Git
* Strong written and spoken English
* Willing to relocate to Munich permanently

Nice to have:
* Good UI/UX sense;
* Knowledge of package managers like NPM, Yarn, Bower
* Microservices
* AWS

## Local
Munich - Germany (near Central Station)

## Benefits
* Relocation support to Munich (2500 euro)
* Unu electric scooter of your choice as "company car" (see www.unumotors.com) or an additional payment for a yearly public transportation ticket
* Regular team events, including office dinners, skiing trips, and parties
* 1.500 EUR of development budget per year for attending conferences, courses, buying books
* High-end hardware (Macbook Pro i7), noise-canceling headphones (Bose wireless)
* 26 paid vacation days, and 2 days of home office per month
* Weekly German language courses
* Office in the heart of Munich
* Direct impact on the daily work of several thousand users
* A creative environment with talented and ambitious team members

#### Company
Personio is a Market-proven, well-funded and fast growing company ($14.3M funding acquired to the date). Join our ambitious product and engineering team and take an active role in shaping the future of our product. You will be responsible for leveling up our UX by improving existing features as well as participating in the specification and implementation of new ones.
* Frontend development is driven by customer feedback
* Help us with the migration of existing application features to React.js

## Labels

- Alocado
- Sênior

## How to apply
mail me: rafaelmotta021@gmail.com / rafael.motta@personio.de
Me enviem um email que posso explicar mais detalhes da vaga, processo de realocação, vida em munique, etc.

**Comment by glaubermagal** [comment]
EU citizenship required?

**Comment by rafaelmotta** [comment]
No, but you must have a bachelor or similar, as it’s a requirement for getting the Blue Card (the visa).

**Comment by forethoughtde** [comment]
I would like to know if you have any openings in junior frontend role? Thanks.

**Comment by rafaelmotta** [comment]
Now the company is considering junior level developers. But you should have good communication in English.

**Comment by rubenmarcus** [comment]
and if no degree, still possible?

**Comment by forethoughtde** [comment]
@rafaelmotta Can I have the email address which I can send my CV?

**Comment by danilosilvadev** [comment]
@rafaelmotta i also want to know if without a degree is possible. I know Germany has others VISA options. Could your company considerate them too?

**Comment by rafaelmotta** [comment]
@rubenmarcus @danilosilvadev Now the company accepts candidates without a degree, but as the process is long, they're not considering for junior level developers.

@forethoughtde rafaelmotta021@gmail.com / rafael.motta@personio.de

**Comment by danilosilvadev** [comment]
@rafaelmotta ah ok, I'm not a junior. So i will apply too, thanks.

**Comment by rafaelmotta** [comment]
@danilosilvadev please send your cv for me before :)

**Comment by danilosilvadev** [comment]
@rafaelmotta I sent to you.

**Comment by rubenmarcus** [comment]
@rafaelmotta sent.

**Comment by tiagosatur** [comment]
Hey @rafaelmotta, how are you? CV sent

**Comment by rafaelmotta** [comment]
Thanks. We still have 14 open positions.
