### ISSUE TITLE
[São Paulo] Front-End Developer [ATG Consulting]

### ISSUE THREAD

**Issue by ATGConsulting** [frontendbr/vagas#1605]
Escritório, São Paulo - Vila Olímpia

salário + participação acionária na empresa

Requisitos

**Obrigatórios:**
- Nível Sênior, com mais de 3 anos experiência na atividade
- Conhecimento e experiencia em desenvolvimento Front-end 
- Programação:  em .Net , Angular,  banco de dados SQL Server 
- Skill soluções mobile e soluções em nuvem 
- Capacidade de trabalho em grupo e colaboração
- Facilidade de comunicação com equipe de desenvolvimento

**Desejáveis:**

-Python 
- Conhecimento da área de saúde 

## Contratação

PJ a combinar

## Nossa empresa

Somos uma startup focada na gestão dos recebíveis dos médicos. Auxiliamos os médicos no aumento da receita e redução de perdas, que são muito comuns e de alto valor financeiro dada a diversidade de regras das fontes pagadoras.
Desenvolvemos uma solução de tecnologia que controla a produção e realiza a conciliação de procedimentos cirúrgicos, consultas e glosas.  Uma solução inovadora que combina mobilidade e IA para tornar simples e facial a gestão e identificação de divergências, aumentando a receita e reduzindo as perdas dos médicos.

## Como se candidatar

Por favor envie um email para vagas@atgconsulting.com.br com seu CV anexado - enviar no assunto: VagaFront-End Developer

**Comment by LFeh** [comment]
A pessoa vai ter o vinculo de trabalho com a propria ATG Consulting?
