### ISSUE TITLE
[São Paulo ] Front End Engineer Senior na Creditas

### ISSUE THREAD

**Issue by alexkawaharada** [frontendbr/vagas#1606]
## Descrição da vaga

Você tem foco em desenvolver códigos de alta qualidade? Gosta de resolver problemas complexos de negócios? Ser Software Engineer (Frontend) na Creditas é desenvolver soluções para escalar o negócio, garantir a eficiência operacional e melhorar a experiência dos clientes, gerando ainda mais valor para o nosso propósito.

Hoje, nós temos mais de 18 squads e pode ter certeza que você fará parte de uma equipe super estratégica, com muitos desafios, aprendizados diários e pessoas incríveis e motivadas!

Como será o seu dia a dia:
- Garantir que todas as soluções técnicas estejam alinhadas a estratégia do negócio;
- Desenvolver garantindo funcionalidade, manutenibilidade e velocidade;
- Garantir práticas de teste e qualidade;
- Trabalhar em um ambiente colaborativo, em que práticas de pareamento, feedbacks e motivação para se desenvolver são comuns a todos os squads.

*O que você vai encontrar na nossa tripulação

- Ambiente que valoriza feedback e 1:1;
- Ambiente dinâmico e com crescimento exponencial;
- Background anterior também é importante, não vamos anular o que você já vivenciou. E compartilhando algumas curiosidades, apresento a Monique, responsável pela área de talentos e cientista física molecular e o Thomas da área de Analytics, formado em engenharia florestal;
- Jogamos para ganhar e queremos que nossa tripulação sempre inove e busque por novos conhecimentos, e para isso temos auxílio educação / estudo e Aulas de Inglês in company (sem descontos);

## Local

São Paulo - Vila Olímpia

## Benefícios

-  VR R$ 25/dia
- Auxílio creche
- Gympass ( Plano Platinum R$ 75,00)
- Plano de saúde
- Plano Odontológico
- Estacionamento / Fretado / Bicicletário;

## Requisitos

- Experiência sólida em Javascript, a linguagem pura, independente de frameworks;
- Experiência em (ou vontade de aprender) ferramentas da nossa stack: EmberJS, React, React Native e Jekyll;
- Habilidade e preocupação com a excelência técnica e boas práticas de desenvolvimento;
Familiaridade com agilidade;
- Experiência com escrita e manutenção de testes (unitários e integrados);
- Participação ativa em comunidades de Tecnologia (palestras, meetups, eventos, tech talks) é um diferencial.

*Valorizamos quem gosta de navegar em outras especialidades: Backend, DevOps, etc

## Contratação

CLT

## Nossa empresa

Nosso propósito é garantir um crédito de qualidade que ajude os brasileiros a usarem seus bens como alavancas do seu progresso financeiro e pessoal. Combater as más dívidas e ajudar a realizar projetos de vida é o que nos dá orgulho e nos motiva a trabalhar. 

Para trazer inovação ao mercado de empréstimos, nós apostamos em tecnologia. É com ela que escalamos o negócio, otimizamos processos e melhoramos a experiência dos clientes. Nossa plataforma foi criada dentro de casa utilizando tecnologia open source, seguindo a filosofia agile e suas práticas. Mas nosso negócio mesmo são as pessoas: não abrimos mão do atendimento personalizado, prestando consultoria e oferecendo educação financeira para empoderar o cliente a tomar a melhor decisão.

## Como se candidatar

Caso se indentificou com a nossa proposta se inscreva na link da vaga 
  ( https://jobs.kenoby.com/creditas/job/software-engineer-frontend/5be4b05979bbcb76f8649057 )

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 4 dias após cada processo.
E-mail para contato em caso de não haver resposta: alex.kawaharada@creditas.com.br

**Comment by LFeh** [comment]
Qual o nivel da vaga?

**Comment by alexkawaharada** [comment]
> Qual o nivel da vaga?

Olá, a vaga é de Senior
