### ISSUE TITLE
[REMOTO] Desenvolvedor Wordpress FrontEnd + JS [SSX Digital]

### ISSUE THREAD

**Issue by guireisbh** [frontendbr/vagas#1608]
## Descrição da vaga
Procuramos Profissionais Experientes, com conhecimentos em desenvolvimento de sites e temas em Wordpress e, acima de tudo, dispostos a enfrentar desafios e problemas.

## Formação e Experiência

Não é necessário curso superior.
Boa leitura em inglês.
Experiência mínima de 2 anos atuando como desenvolvedor.

## Local

A vaga é para trabalho remoto. Mas é de 40h semanais. Dedicação Exclusiva.
O regime de contratação é PJ.
Bateu as metas? Temos bônus de produtividade

## Habilidades

Muito PHP e JS
Wordpress e Woocommerce
Testes são bem-vindos.
Bom raciocínio lógico.
Inteligência emocional e disposição para resolver problemas.
Os requisitos mudam, os códigos também, esteja disposto a mudanças.

## Diferenciais

Experiência com Magento e OpenCart, Desenvolvimento de Plugins.
Experiência com Azure e AWS.

## Atribuições:

Planejar e discutir soluções de implementação com a equipe.
Estudar e aprender bastante sobre novas tecnologias

## Como e Quando?
A contratação é imediata.
Interessado? Envie seu currículo para vagas@ssxdigital.com.br com a remuneração desejada.

## Labels

- Remoto
- PJ
- Freela
- Pleno
- Sênior

**Comment by ribeiroevandro** [comment]
Enviado

**Comment by rodineicosta** [comment]
Enviado.

**Comment by JeanPaulll** [comment]
Qual a forma de contratação? E a faixa salarial?

**Comment by ribeiroevandro** [comment]
@JeanPaulll a forma de contratação, parece ser **PJ** como descrito nas Labels, mas sobre o salário a pergunta é bem interessante...
