### ISSUE TITLE
[São Paulo] Desenvolvedor FrontEnd Linked Gourmet 

### ISSUE THREAD

**Issue by WILLYTV** [frontendbr/vagas#1609]
Descrição da vaga
Estamos com vagas abertas no time de Desenvolvimento! Buscamos pessoas que tem grandes ideias e vontade de construir algo incrível.

Se você é um desenvolvedor Front-end acima da média ou conhece alguém, essa é a oportunidade!

Nossa vaga requer um conhecimento também em backend porém, não é o principal foco. A maioria do trabalho está mais concentrado em front end. Mas conseguir debulhar uma API já ajuda muito no dia a dia. Então eh muito importante ter vontade de aprender para ampliar conhecimentos cada vez mais.

Local
Rua Gomes de Carvalho 1609

Requisitos
Front
HTML5/CSS3
ECMAScript 6 (ES6)
Consumo de APIs (RESTfull)
Conhecimento com Git
Diferencial
Experiência com algum framework front end atual (VUE / Angular preferencialmente)
Backend
Web API (C# e ou NodeJS)
Modelagem REst
ASP.Net MVC

Banco de dados
SQL server (Azure)
Diferencial
Experiência em Azure

Contratação
CLT

Remuneração
R$ 5.000,00 a R$ 6.000,00  mês

Benefícios
GymPass
Plano de saúde
VR/VA 
13 salário
Alura empresa
Local para descompressão e almoço

Nossa empresa
Somos uma Startup inovadora pronta para oferecer uma nova experiência ao mercado de food service. Conectamos: Gente boa + Empatia + Novas ideias + Design + Tecnologia.

Somos o novo, mas com experiência de gente grande, nasce em meados de 2010 o que viria a se tornar a atual Linked Gourmet.

Como se candidatar
Envie seu currículo para nós: willy.viana@linkedgourmet.com.br - Enviar no assunto: Vaga Desenvolvedor FrontEnd

**Comment by LFeh** [comment]
Qual o nivel da vaga?
