### ISSUE TITLE
[São Paulo] Front End Developer Pleno/Sênior

### ISSUE THREAD

**Issue by luisfontes** [frontendbr/vagas#161]
## Descrição da vaga

A posição é para um Front-End Pleno/Sênior na OneMarket para atuar diretamente com o produto principal.

Nosso produto é uma plataforma de clube de assinatura e e-commerce feita 100% in-house. Trabalhamos com uma stack moderna (React, Redux, Webpack, SSR) e seguindo as melhores práticas de desenvolvimento atuais (padrões de código, unit/integration tests, CI/CD, etc.).

Temos como objetivo sermos a plataforma de e-commerce de alimentação mais completa do Brasil. A empresa está em uma fase de escalar o produto e essa vaga é para alguém que irá trabalhar diretamente com o nosso FE Lead para fazer isso acontecer. Apesar de sermos um "e-commerce" estamos construindo um produto que traga inovação para a compra de comida online. Veja mais informações sobre a empresa abaixo.

## Local

Presencial em São Paulo, região da Barra Funda (Zona Oeste).
Walking distance da estação Barra Funda (Metrô/CPTM)

## Requisitos

* Experiência em aplicações de FE com projetos já realizados.
* Conhecimento pleno ou avançado em CSS e JS.
* Vontade de aprender e autonomia para garantir uma entrega de qualidade.

Diferenciais:

* Experiência com React e seu ecossistema
* Técnicas de otimização para web

## Contratação

Fulltime, PJ

## Nossa empresa

A OneMarket é o nome por trás da [GlutenFree Box](https://www.glutenfreebox.com.br) e da [LacFree Box](https://www.lacfreebox.com.br), dois clubes de assinatura de alimentos. A nossa missão é revolucionar o mercado de alimentação saudável através de um produto digital focado na experiência do usuário ao comprar comida online.

Temos dois anos de existência e estamos em uma fase de evolução de produto e de escalar operação. Contamos com investimento de anjos e fundos de VC para garantir o combustível necessário para isso. O produto digital é parte fundamental da nossa estratégia e uma das principais áreas de investimento da empresa. Temos um sonho grande e energia necessária para fazer isso acontecer, se você quer um desafio aqui você temos um prato cheio :)

## Como se candidatar

Envie para luis[at]onemarket.com.br um email com seus dados (CV, projetos realizados, github, linkedin, etc.)

**Comment by luisfontes** [comment]
Labels: Alocado, PJ, Pleno

Obrigado!

**Comment by luisfontes** [comment]
@LFeh fiz umas mudanças na vaga e se puder adicione a tag de "Sênior" também por favor, tks!

**Comment by LFeh** [comment]
Feito! 😄

**Comment by luisfontes** [comment]
Vaga preenchida por alguém que achou ela por aqui, valeu!
