### ISSUE TITLE
[São Paulo] Front-end Developer na Rede Globo - G1 (Infografia)

### ISSUE THREAD

**Issue by robanquieri** [frontendbr/vagas#1612]
## Descrição da vaga

Estamos à procura de um desenvolvedor Front-end para fazer parte do nosso time em São Paulo.

Você será responsável pelo desenvolvimento de aplicações que exigem soluções inovadoras. Deverá compreender as necessidades do núcleo de jornalistas, recomendar e implementar soluções que seguem as melhores práticas.

Você vai trabalhar em colaboração com a nossa equipe de design e colaborar com os nossos jornalistas em projetos que afetam a vida de milhões de pessoas no Brasil. Se você é uma pessoa que gosta de desafios, se você sonha em fazer parte de uma grande empresa, este emprego pode ser para você .

## Local

Presencial, São Paulo - Vila Cordeiro

## Requisitos

**Obrigatórios:**
- Graduação completa em área de TI e/ou afins
- Domínio em JavaScript, HTML e CSS
- Conhecimento em um ou mais frameworks JavaScript (React, Angular, Vue, etc.)
- Inglês avançado

**Desejáveis:**
- Conhecimentos em Node JS

## Contratação

CLT

## Como se candidatar

Se candidate pelo Linkedin, https://www.linkedin.com/jobs/view/front-end-developer-infografia-at-rede-globo-990381821/

**Comment by thaisfalbo** [comment]
Enviado! 😄

**Comment by robanquieri** [comment]
> Enviado! 😄

Show! Boa sorte @thaisfalbo :)

**Comment by robanquieri** [comment]
@LFeh Pode remover a label de estágio por gentileza? :)
