### ISSUE TITLE
[São Paulo] Front-End Developer na VAGAS.com

### ISSUE THREAD

**Issue by hjdesigner** [frontendbr/vagas#1614]
## Descrição da vaga

A nossa equipe tem grandes desafios na VAGAS. Vivendo a experiência de um modelo de gestão horizontal (sem chefes), conseguimos ter muita autonomia para conduzir testes e inovações!

Oferecemos tecnologia para Recrutamento e Seleção há mais de 19 anos. E com isso, temos um histórico que nos orgulha muito, mas que ao mesmo tempo, necessita passar por constantes transformações e se manter sempre novo. E é aí que entra um dos nossos principais desafios: como transformar o nosso legado em algo legendário?

#### Como será o seu dia a dia:

- desenvolvimento de interfaces que se adaptam a diversos dispositivos e tamanhos de tela;
- em parceria com Designers e UXs, entregar valor para o usuário, garantindo melhor usabilidade e fidelidade do layout;
- trabalhar com requisições HTTP utilizando API Rest;
- participar de equipes multifuncionais interagindo com os profissionais de todas as áreas de conhecimento;
- participar de todo o ciclo de desenvolvimento de produto, passando pelas fases de concepção e análise de mercado, por exemplo, não apenas produção;
- gestão compartilhada de sua equipe e negócio.

## Local

Brooklin Novo (Zona Sul - São Paulo/SP).

## Benefícios

- auxílio desenvolvimento p/ cursos;
- auxílio creche (crianças até 5 anos);
- convênio médico - Porto Seguro;
- convênio odontológico - MetLife;
- VT, fretado ou auxílio estacionamento;
- VR de R$32,00/dia;
- cesta de natal;
- seguro de vida.

#### Nosso diferenciais

- Great Place To Work - TI (2014,2015,2016);
- ambiente informal;
- horário flexível;
- possibilidade de fazer home-office alguns dias;
- café da manhã e da tarde + fruta;
- ginástica laboral, quick massage e assessoria esportiva;
- parceria com a Gympass;
- videogame, revistas & jornais;
- parabéns com coxinha e bolo todo mês;
- festas e eventos ao longo do ano;
- troca de conhecimento através de palestras e workshops internos;
- wi-fi aberto para dispositivos pessoais;
- parcerias com universidades e escolas de idiomas;
- fácil acesso de carro, trem ou fretado;

## Requisitos

**Desejáveis:**
- reproduzir layouts com fidelidade;
- HTML, CSS, bibliotecas Javascript (heavy user);
- frameworks Javascript MV*;
- design responsivo;
- frameworks de CSS;
- algum CMS;
- softwares de criação e edição de layouts;
- SEO, cross-browser e acessibilidade;
- chamadas API Rest;
- sistemas de versionamento de código;
- ser proativo;

**Diferenciais:**
- ter trabalhado com metodologias ágeis;
- experiência com a biblioteca React;
- experiência com desenvolvimento orientado por testes (TDD).

## Contratação

CLT
Alocado

## Nossa empresa

Há 19 anos buscamos contribuir para que pessoas escolham melhor as empresas e empresas escolham melhor as pessoas, impactando positivamente no objetivo de cada um. Como? Através da tecnologia!

Como resultado, temos um sistema de currículos com aproximadamente 13 milhões de currículos, 74 das 100 maiores empresas do país contratando através das nossas soluções tecnológicas, além de inovações que auxiliam os candidatos ao longo de sua trajetória profissional, como o Mapa VAGAS de Carreiras, e um banco de dados do tamanho de 5 teras. Toda a conquista é feita através da vivência do modelo de gestão horizontal, que possibilita a liberdade, autonomia e responsabilidade no negócio, mas todos têm tudo a ver com isso.

Quer conhecer mais nosso modelo de gestão? [Olha o que estão falando por aí.](http://projetodraft.com/vagas/)

## Como se candidatar

Se você tem o perfil para trabalhar neste ambiente desafiador onde todos fazem o que querem e todo mundo tem tudo a ver com isso, inscreva-se.

[https://challenges.vagas.com.br/](https://challenges.vagas.com.br/)

## Labels

- Alocado
- CLT
- Remoto - Parcial
- Sênior
- Pleno

**Comment by tfalbo** [comment]
Oi! Não consegui acessar a vaga. Parece que não está mais disponível.

**Comment by israelcena** [comment]
Não encontramos vagas :(

**Comment by nandomoreirame** [comment]
a vagas.com anuncia uma vaga no site vagas.com mas ela não existe
procuremos essa vaga em outro site que anuncia vagas talvez lá eles tenham cadastrado direito lá kkkk

**Comment by nandomoreirame** [comment]
ah não eles não cadastraram, o site é o https://github.com/frontendbr/vagas/ 👎

**Comment by hjdesigner** [comment]
> Oi! Não consegui acessar a vaga. Parece que não está mais disponível.

Vou verificar o que aconteceu, obrigado pelo feedback.
Enquanto isso você pode acessar nosso teste através do link https://challenges.vagas.com.br/.

**Comment by hjdesigner** [comment]
> Não encontramos vagas :(

Vou verificar o que aconteceu, obrigado pelo feedback.
Enquanto isso você pode acessar nosso teste através do link https://challenges.vagas.com.br/.

**Comment by hjdesigner** [comment]
> a vagas.com anuncia uma vaga no site vagas.com mas ela não existe
> procuremos essa vaga em outro site que anuncia vagas talvez lá eles tenham cadastrado direito lá kkkk

Belo ponto de vista kkkkkk
Vou verificar porque não a vaga foi excluída, enquanto isso você pode acessar nosso desafio através do link https://challenges.vagas.com.br/.
