### ISSUE TITLE
[São Paulo] Back End Developer

### ISSUE THREAD

**Issue by luisfontes** [frontendbr/vagas#162]
## Descrição da vaga

A posição é para um Back-End Pleno na OneMarket para atuar com o produto principal.

Nosso produto é uma plataforma de clube de assinatura e e-commerce feita 100% in-house. Todo back atual é em Node em uma arquitetura de micro serviços.

Temos como objetivo sermos a plataforma de e-commerce de alimentação mais completa do Brasil. A empresa está em uma fase de escalar o produto e essa vaga é para alguém que irá trabalhar diretamente com o nosso BE Lead para fazer isso acontecer. Fundamental ter muita vontade de aprender e autonomia para garantir uma entrega de qualidade.

## Local

Presencial em São Paulo, região da Barra Funda (Zona Oeste).
Walking distance da estação Barra Funda (Metrô/CPTM)

## Requisitos

* Experiência em node com projetos já realizados.
* Domínio em JavaScript.
* Preocupação com código de qualidade.
* Saber trabalhar com controle de versão. (Git)
* Inglês técnico.
* Gostar (muito) de aprender.

Diferenciais:

* Experiência com micro serviços.
* Conhecimento em Postgres, Elastic ou RabbitMQ
* Hapi.js e seu ecossistema
* Docker

## Contratação

Fulltime, PJ

## Nossa empresa

A OneMarket é uma empresa de clubes de assinatura que possui atualmente duas marcas: GlutenFree Box e LacFree Box. A empresa tem 2 anos de existência e possui investimento de anjos e fundos de venture capital. Sua missão é revolucionar o mercado de alimentação saudável online.

Os clubes de assinatura são um primeiro passo para esse objetivo. O próximo passo é construir uma plataforma que atenda por completo quem queira se alimentar de uma maneira mais saudável. O produto digital é parte fundamental dessa estratégia e uma das principais áreas de investimento da empresa. Temos um sonho grande e energia necessária para fazer isso acontecer, se você quer um desafio aqui você vai ter um prato cheio :)

## Como se candidatar

Envie para luis[at]onemarket.com.br um email com seus dados (CV, projetos realizados, github, linkedin, etc.)

**Comment by luisfontes** [comment]
Labels: Alocado, PJ, Pleno

**Comment by LFeh** [comment]
Opa @luisfontes, agora estamos mantendo só Vagas focadas em Front-End aqui ;)

**Comment by luisfontes** [comment]
Opa my bad então @LFeh
