### ISSUE TITLE
[Remoto] Frontend Developer na BriteCore

### ISSUE THREAD

**Issue by wguldin** [frontendbr/vagas#1620]
We are a fully remote company, with several people on our team already who are from Brazil! 

We have a couple of different frontend positions open right now, including both mid-level and architect-level positions. See our [hiring site to apply](https://engineering-application.britecore.com/br)

--- 
## Mid-Level Frontend Developer Job Description

We are hiring for a mid-level frontend developer who can work alongside our designers and full stack developers to create an well structured and visually consistent design system for our app.

This position would be in our product development division, which is building out several new products for our main app, BriteCore. We are interested in building a team of frontend experts who could assist our fullstack developers in working with our design system.

### The kind of work we do
BriteCore is essentially a CMS for insurance companies. They use it to manage all aspects of their business, including tracking policies, managing contacts and handling claims.

This means our users typically see our app more as a business tool like Microsoft Word or Google Sheets than a website (even though it is completely a web-based app). They also are using BriteCore for several hours every day, and are concerned with doing things quickly and efficiently. This, along with the complicated nature of insurance, means we deal with some complex workflows, and try to set ourselves apart from our competitors with a smooth UX that helps them navigate these tough processes.

### What you might be doing
Traditionally at BriteCore, full stack developers have done almost all of the development work. We haven’t been specialized into frontend or backend roles. This means our full stack developers are all working together to build out a vue.js-based frontend and design system, but we’d like to have a team of mid-level frontend developers who can help create components, document standards, and continue to improve this design system as these products grow.

**As a mid-level frontend developer, you could be doing the following:**
Help draft standards around JS conventions
Create a new layout framework in CSS Grid
Work with a designer to implement new components
Improve our utilization of Vuex
Architect and implement highly reusable, configurable Vue components
Improve our testing framework to ensure components can be safely and predictably modified
Create easier ways for our clients to add UI customizations and theming

### What it is like to work here
BriteCore is a remote-first company — even employees who live in our home city of Springfield, MO usually work from home! And most of the people you will work with are scattered across the US and the globe. This means that remote team members are just as much part of the company as local employees. We also allow a lot of flexibility in terms of time off. In return, we expect all of our employees to be productive and accountable, which means you'll work alongside a great, dedicated team.

### Responsibilities & Requirements
- Several years of experience in the field is preferred
- Vue.js experience highly preferred, frontend JS framework experience required
- Review code and PRs, and provide constructive feedback to team members
- Communicate clearly and effectively over chat and video conference
- Welcome feedback and collaboration
- Be friendly, confident, and patient with others
- Ship code on time
- Self-direct
- Stay familiar with the latest web development trends

### Technologies We Use
- JavaScript (ES6)
- Vue.js
- Node.js
- Webpack
- HTML5
- SCSS
- Python
- Django and Django REST Framework
- GraphQL
- MySQL
- GitHub
- Linux (Command line knowledge such as BASH, ZSH, or FISH)
- Docker
- Amazon Web Services

### Benefits and Compensation
- US$50k-70k annual salary, highly based on experience and proven performance
- Benefit from working alongside and observing a team of world-class engineers and designers
- Comprehensive health insurance coverage including medical, dental, and vision
- Flexible schedule
- Relaxed work environment
- Remote work
- Flexible learning time — explore your ideas and new technologies on the clock

### More about the company
At BriteCore, we build gorgeous, scalable, and usable cloud-based insurance software. This is a company founded by, and run by software engineers. We have created a team of top performers developing modern systems for the insurance industry. Our team enjoys working together, and takes tremendous pride and ownership in our platform. We promote a high quality of life for our employees by allowing them to choose their own schedule and location. Bring creativity, focus, and productivity to your job, and enjoy 40 hour work weeks, flexible paid time off, and remote work.

**Comment by allancarlos123** [comment]
Precisa ser fluente?

**Comment by wguldin** [comment]
Good question @allancarlos123! English fluency is required for all team members. 

I'm using google translate, so sorry if this is rough, but: 
A fluência em inglês é necessária

**Comment by claudiovicar** [comment]
Hi, @wguldin! Is there a deadline for submitting of project? Thanks in advance!

**Comment by wguldin** [comment]
@mrangel-jr We use vue.js as our frontend framework, but we value engineering skills more than framework familiarity, as long as you're able to pick it up and know JS fundamentals. 

@claudiovicar Hi! No, there is no deadline, take enough time to do a job that you are proud of! We'll probably be collecting applicants and projects for a few weeks.

**Comment by joelxr** [comment]
Hi @wguldin, I just applied for the position following all the instructions.

**Comment by marcelorubim** [comment]
HI! I had to generate a new link to the last task instructions and now Vue.js is listed as a requirement not as bonus anymore. :(

**Comment by wguldin** [comment]
After a few non-vue projects came in, the dev team felt that it was harder to accurately assess what we were looking for, so we've updated the requirements to reflect that. Sorry for any confusion.

However, for anyone who's done the project already, we won't require updates, we'll honor the submission and do our best to review!

**Comment by malbernaz** [comment]
@wguldin was the job removed? I'm not being able to submit my resume.

**Comment by wguldin** [comment]
I'll send you a link, @malbernaz.

**Comment by joelxr** [comment]
Hi @wguldin,

I just sent my application again for the 2nd time because I received an email telling me that I did it by the main hiring site and that's not the required way.

Anyway, that's just to keep you posted about it, the 1st time that I sent my application was Dec 12h.

[]s

**Comment by Errec** [comment]
Same thing happened to me @wguldin, I had to reapply yesterday. Can you double check if the my application is all right now? 
Cheers

**Comment by glaubermagal** [comment]
Hi @wguldin, I've sent some questions to product-hires@britecore.com a few days ago.

**Comment by wguldin** [comment]
@glaubermagal I just sent you some answers, thanks! I was off for Christmas for a few days. 

@joelxr @Errec our hiring coordinator followed up yesterday with all the folks who seemed to not include links to both the repo and project, as we're in the review process now. However I think they may not have been looking in the right spot for this information. I'll follow up with them. Both of your submissions look correct, and we'll be in touch. Thanks for all the hard work!

**Comment by nordlunda** [comment]
@wguldin When do you expect to start interviewing candidates who submitted their project?

**Comment by wguldin** [comment]
@nordlunda, We've started the interview process, but haven't sent out any notices to folks who won't be making it to the next stage of the process. We like to give people concrete feedback on projects, and that does take time to put together.

Either way, we'll keep you posted on the next steps!

**Comment by Errec** [comment]
Sorry @wguldin I didn't get it: all candidate should be knowing by now if they are in the interview pipeline process?  Or are guys you still selecting people for interviews?

**Comment by vcpablo** [comment]
@Errec What I think that @wguldin said is that the interview phase has started but, those who haven't pass through the first step were not warned.
They just contacted those who passed.
Is this right @wguldin ?

**Comment by wguldin** [comment]
@Errec @vcpablo Sorry, I missed the original ping here! We've started sending out notices to folks who haven't made it through the process. We try and send out tailored feedback for every project we received, so that's why it takes us a little time, but we want to respect the investment you've made. 

We're also still accepting and reviewing projects, in case anyone is still working on it. Thanks!

-Will

**Comment by IgorVieira** [comment]
Hey @wguldin I sent yesterday my application I don't know if this offer it's open but ... I did everything 😅 so... anyway thank you for your time and congrats I really liked the challenge!
