### ISSUE TITLE
[Belo Horizonte/MG] Front-End Developer na STRIDER

### ISSUE THREAD

**Issue by megandavulpi** [frontendbr/vagas#1622]
### Sobre a empresa: Strider

A Strider nasceu em 2013 com a missão de levar a tecnologia digital ao campo, aumentando a produtividade da lavoura para alimentar cada vez mais pessoas em todo o planeta. 

Ou seja, viemos revolucionar uma indústria!
 
Somos uma das AgTechs mais inovadoras do mundo, segundo a revista Forbes, e líder de mercado de tecnologia para a agricultura no Brasil! Oferecemos soluções de software e hardware focadas em tornar a tomada de decisão do produtor rural mais rápida e assertiva.

### Descrição:

**O que você irá fazer?**

Implementar aplicações web client-side, rápidas e fáceis de usar;
Desenvolver expertise nos softwares que compõem a plataforma Strider;
Desenvolver a compreensão do contexto dos clientes e do uso dos nossos produtos;
Criar interfaces internacionalizadas, uma vez que temos presença em diversos países;
Ser capaz de desenvolver habilidades em novas tecnologias para cumprir os objetivos do produto;

### As habilidades necessárias:

JavaScript;
HTML5;
CSS3;
Angular.js;
Experiência em desenvolvimento de webapp;

### Diferenciais:

React.js;
Experiência em desenvolvimento de produtos;
Experiências de recursos para desenvolvimento web, como NPM/Webpack/Bower;
Desenvolvimento de software de alta complexidade técnica;

### Beneficios:

Vale Refeição ou Alimentação;
Vale Transporte;
Seguro de Vida e Acidentes Pessoais;
Plano de Carreira;

### Você gostará de trabalhar aqui se:

É normalmente inconformado(a) com coisas que não funcionam e gosta de mudar o jogo;
Gosta de interagir com a galera do trabalho;
Acredita que aprender mais sobre tecnologia e soft skills vão fazer de você um(a) profissional melhor;
Entende que o planejamento e o auto gerenciamento é imprescindível para o seu trabalho;
Tem sangue nos olhos e foco na missão;
Horários flexíveis e um ambiente muito legal de se trabalhar! :)

**Um pouco mais sobre a gente e como estamos conquistando o mundo!**

Hoje, a empresa acompanha o dia a dia de mais de 3.000 fazendas em vários países, no total de 4 milhões de hectares!

Temos clientes espalhados pelo mundo! Brasil, EUA, Bolívia, México, Colômbia, Moçambique, Paraguai e Argentina.

Estamos crescendo bem rápido - e contamos com você para que possamos crescer ainda mais, juntos!

### Labels:

Alocado
CLT
Pleno/Senior

**Comment by ReactGirl** [comment]
É normalmente inconformado(a) com coisas que não funcionam e gosta de mudar o jogo;
