### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor Frontend - Junior ou Pleno - LEO Learning

### ISSUE THREAD

**Issue by josephfelix** [frontendbr/vagas#1623]
## Descrição da vaga

Somos uma empresa que trabalha desenvolvendo plataformas de ensino à distância e treinamentos corporativos.
Trabalhamos sob a plataforma Moodle, que é usada em diversas universidades e reconhecido no mundo inteiro como um dos melhores LMS da atualidade.
Busca-se desenvolvedor para atuar com frontend, desenvolvendo as telas seguindo a especificação do designer e da compatibilidade com todos os browsers da atualidade.
Experiência desejada em CSS (Sass/Less), Mustache/HTML e Ionic.
Saber PHP e Moodle será um diferencial.

## Local

Barra da Tijuca - Rio de Janeiro/RJ

## Benefícios
- Horário flexível
- 13° para PJ
- Férias para PJ
- Ser autogerenciável

## Requisitos

**Obrigatórios:**
- Português (Nativo), Inglês (Intermediário)
- Experiência entre 1 e 3 anos
- Programação: CSS (Sass/Less), HTML (Mustache), JavaScript (requirejs/jQuery)

**Desejáveis:**
- Experiência desejada em PHP e Ionic.

**Diferenciais:**
Ter experiência com o Moodle é um diferencial!

## Contratação
PJ a combinar (salário a combinar)

## Nossa empresa

Somos uma empresa que atuamos há 6 anos no mercado e trabalhamos com o desenvolvimento de ensino à distância e treinamento corporativo.

## Como se candidatar

Por favor envie um e-mail para **plataforma@leolearning.com** colocando seu CV anexado e o link para seu portfólio - enviar no assunto: "Vaga Front-end"

## Labels

- Alocado
- Freela
- Júnior
- PJ
- Pleno

**Comment by igorpinhh** [comment]
Rola vaga pra estágio?

**Comment by josephfelix** [comment]
OI @igorpinhh, infelizmente não, a qualificação mínima necessária é júnior e precisamos de uma pessoa em tempo integral.

**Comment by Pedro-Souza** [comment]
Tem a possibilidade de ser remoto?

**Comment by josephfelix** [comment]
@Pedro-Souza não, somente alocado.

**Comment by thallesmarchetti** [comment]
currículo enviado!
