### ISSUE TITLE
[Recife] Front-End Developer na JUSTA PAGAMENTOS

### ISSUE THREAD

**Issue by felipebonezi** [frontendbr/vagas#1624]
## Descrição da vaga

Somos uma Fintech localizada em São Paulo e Recife com tecnologias que ajudam nossos clientes e revendedores a capturarem vendas em Cartões de Crédito / Débito.

## Local

Recife - Pina

## Benefícios

- Plano de saúde
- VR de R$ 30,00/dia

#### Diferenciais

- Você é o gestor do seu tempo
- Hierarquia horizontal
- Frigobar sempre cheio de cerveja :P
- Sala de jogos
- Varanda com vista para o Mar
- Computadores fornecido pela empresa
- Múltiplas telas
- Gente descolada, nerd e tabacuda
- Não temos Dress code (Só não vale vir pelado)
- Temos chuveiro para quem gosta de se exercitar (Por enquanto só temos sedentários, venha ser o primeiro a usar)

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com JavaScript
- 2 anos de experiência com HTML / CSS
- 1 ano de experiência com algum SPA Framework/Lib - e.g. Angular 2+, React ou VUE

**Desejáveis:**
- conhecimento em metodologias ágeis - e.g. SCRUM
- boa leitura, escrita e fala em inglês ou espanhol
- conhecimento em PWA

**Diferenciais:**
- conhecimentos em Java ou Scala
- conhecimentos em Android ou iOS
- conhecimentos em PostgreSQL
- conhecimentos em arquitetura reativa

## Contratação

PJ a combinar

## Nossa empresa

**Muito prazer, somos a JUSTA**
Cuidamos do início, do meio e do fim em pagamentos.
Oferecemos uma solução completa para o seu negócio! 

Início: entender a necessidade do cliente e oferecer uma plataforma simples de contratar e fácil de instalar.

Meio: Sugerir a tecnologia mais adequada de acordo com o perfil do cliente com apoio e suporte dos JUSTOS.

Fim: Fornecer ferramentas para que o cliente acompanhe toda a jornada de venda de ponta a ponta.

## Como se candidatar

Por favor envie um email para it@justa.com.vc com seu CV anexado ou LinkeIn - enviar no assunto: Vaga Front-End Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: it@justa.com.vc

## Labels

- Alocado
- Estágio
- Júnior
- PJ
- Pleno

**Comment by raisiqueira** [comment]
Só vem, galera!!!!

**Comment by felipebonezi** [comment]
Oi Pedro, por enquanto não. ☹️

**Comment by raisiqueira** [comment]
@LFeh altera o flag para Recife 😄

**Comment by LFeh** [comment]
Sorry ahhaha

**Comment by igorsfreitas** [comment]
@felipebonezi A vaga ainda está disponível ? Já enviei email para o endereço informado !

**Comment by raisiqueira** [comment]
@igorsfreitas manda um email para _it@justa.com.vc_ ou pra mim, _rai.siqueira@justa.com.vc_.

#tamoJusto 😎

**Comment by felipebonezi** [comment]
@igorsfreitas não recebi nada, manda pro que o @raisiqueira comentou por favor.

**Comment by igorsfreitas** [comment]
Acabei de enviar novamente @felipebonezi @raisiqueira ! Verifiquem se receberam agora por favor !
