### ISSUE TITLE
[Arujá/SP] Front-End Developer na RH Software

### ISSUE THREAD

**Issue by marcosgugs** [frontendbr/vagas#1626]
## Sobre a RH Software

Há 20 anos no mercado, com excelência em programas para gerenciamento de consultórios e clínicas, a RH Software possui hoje milhares de clientes no Brasil e no exterior.  
Trabalhamos para oferecer produtos excelentes com pós-venda excepcional.  

Saiba mais sobre a empresa no site http://www.rhsoftware.com.br

## Sobre a Vaga

Buscamos um profissional que seja comprometido com a qualidade do seu trabalho. Que saiba trabalhar em equipe e esteja sempre interessado em aprender mais.
O desenvolvedor fará parte da equipe de desenvolvimento do [Dental Office](http://www.dentaloffice.com.br), melhor software de gestão de clínicas odontológicas do Brasil, de acordo com o Cloudia. ([Os 3 melhores softwares odontológicos para a gestão de clínicas e agendamentos](https://www.cloudia.com.br/melhores-softwares-odontologicos/))

## Esperamos que você domine:
- HTML5, CSS3
- Javascript
- Responsivo
- Git

## Sería incrível se você conhecesse:
- AngularJS
- NPM / Gulp / Bower

## Nível Mestre Jedi:
- UX
- Design
- Sketch / Photoshop

## O que oferecemos:

- Salário competitivo
- Ambiente descontraído
- Passaporte para eventos
- Alimentação
- Transporte
- Convênio Médico
- Participação nos lucros

Caso este seja o seu perfil, venha bater um papo com a gente aqui na RH Software. Estamos localizados em Arujá/SP, próximo a Guarulhos, Suzano, Mogi das Cruzes, etc. 
Envie seu currículo ou LinkedIn para o e-mail careers@rhsoftware.com.br para agendar a visita.

## Labels
- Alocado
- CLT
- Pleno
- Senior
- Junior

**Comment by HidemitsuHashimoto** [comment]
Tentei enviar mas o e-mail retorna dizendo que não existe.

**Comment by marcosgugs** [comment]
@HidemitsuHadhimoto escrevi errado o email. Desculpe. Editei la

**Comment by HidemitsuHashimoto** [comment]
> @HidemitsuHashimoto escrevi errado o email. Desculpe. Editei la

Ok. Obrigado.
