### ISSUE TITLE
[São Paulo] Desenvolvedor Front-End Pleno

### ISSUE THREAD

**Issue by raphaguasta** [frontendbr/vagas#163]
![front-pleno](https://cloud.githubusercontent.com/assets/6708227/19974819/f0540ed4-a1d0-11e6-9305-b1db9355f5e9.jpg)

## Descrição da vaga

Atuar com desenvolvimento Frontend responsivo e mobile, com moderno ambiente de desenvolvimento e ferramentas.

## Local

Escritório na Av. Faria Lima, São Paulo - Pinheiros

## Requisitos

**Obrigatórios:**
- Conhecimento de HTML5/CSS3/JS puro
- Pré-processadores CSS
- Experiência com algum framework JS para SPA

**Desejáveis:**
- React/Redux
- ES6
- Cordova / Phonegap
 - Ambiente de desenvolvimento Node (Gulp, Grunt, Webpack, npm...)

## Contratação

À combinar

## Nossa empresa

Startup de mobile marketing.

## Como se candidatar

Por favor envie um email para cv@uolet.com com seu CV anexado - enviar no assunto: Vaga Frontend Pleno

**Comment by camilatigre** [comment]
@raphaguasta 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by raphaguasta** [comment]
b) Não

Obrigado,


*Raphael Guastaferro*WEB/Mobile Developer
*https://br.linkedin.com/in/raphaguasta
<https://br.linkedin.com/in/raphaguasta>*

Em 7 de janeiro de 2017 09:22, Camila Tigre <notifications@github.com>
escreveu:
