### ISSUE TITLE
[REMOTO] Frontend Developer na Divisio.com.br

### ISSUE THREAD

**Issue by luizeduard0** [frontendbr/vagas#1631]
#
## Descrição da vaga
Ingressar uma de nossas equipes e atuar no desenvolvimento de projetos para diversos tipos de negócios. Trabalhamos com projetos muito interessantes (desde a idéia até stacks e desafios).

## Local
Remoto

## Benefícios
- Bônus e gratificações por desempenho
- Disponibilizamos cursos para aprendizado/aperfeiçoamento
- Você pode utilizar parte do seu tempo para estudos
- Se você tiver alguma gap, nossos devs vão te ensinar e colaborar p/ sua carreira.

#### Diferenciais
- Chefia horizontal, todos tem voz na empresa.
- Te valorizamos pelo seu resultado e não pelo tempo trabalho. Há muito espaço p/ crescer
- Trabalhamos com as tecnologias mais atuais
- Horário flexível
- Você pode trabalhar de qualquer lugar que quiser

## Requisitos

**Obrigatórios:**
- Base sólida de JS
- ReactJS
- React Native
- FlexBox
- Completar nosso [desafio](https://github.com/divisioinc/vagas)

**Desejáveis:**
- Redux
- Webpack
- NodeJS
- NodeJS

**Diferenciais:**
- Visão empreendedora
- Se comunicar bem em inglês
- Ambiente MacOS
- GraphQL
- Apollo
- MongoDB

## Contratação

PJ a combinar

## Nossa empresa
Conhece mais sobre a gente no nosso [site](http://www.divisio.com.br).

## Como se candidatar

Por favor envie um email para ola@divisio.com.br com seu CV anexado - enviar no assunto: [VAGA FRONTEND] SEU_NOME

OBS: Se você tiver um Github relevante, este pode dispensar a necessidade do teste. Caso contrário, só aceitamos candidaturas com o desafio realizado.

## Tempo médio de feedbacks
Uma vez enviado todas as informações (desafio incluso) damos um retorno em 5 dias úteis.

E-mail para contato em caso de não haver resposta: ola@divisio.com.br

**Comment by marcosabb** [comment]
@luizeduard0 qual o nível vocês estão buscando nessa vaga?

**Comment by luizeduard0** [comment]
> @luizeduard0 qual o nível vocês estão buscando nessa vaga?

Pleno!

**Comment by matheusnascgomes** [comment]
Qual o prazo para candidatura?

**Comment by luizeduard0** [comment]
> Qual o prazo para candidatura?

Vamos receber currículos para esta vaga até no dia 21. Possivelmente serão duas vagas.

**Comment by LeoRedin** [comment]
Boa tarde! Me interessei nessa vaga, mas só vi ela agora. Vão aceitar candidaturas apenas até amanhã, dia 21 mesmo?

**Comment by luizeduard0** [comment]
@LeoRedin Nós vamos levar em consideração para estas vagas os currículos recebidos até amanhã.
Caso você precise de mais tempo pra fazer o teste, envia seu currículo e combinamos um prazo pro teste.  Abs

**Comment by mrangel-jr** [comment]
@luizeduard0 , mandei ontem o CV. Se tiver valendo ainda, dê uma olhada e me dê um feedback. Vlw !

**Comment by thiagofrancisquete** [comment]
@luizeduard0 no momento não estou procurando vagas, mas dei um _fork_ no teste pra testar meus conhecimentos em React, espero que não se importe :relaxed:

abs
