### ISSUE TITLE
[REMOTO] Full Stack Developer na INDECX

### ISSUE THREAD

**Issue by megandavulpi** [frontendbr/vagas#1634]
### Sobre a empresa: IndeCx

A IndeCX faz parte do Grupo Quest Inteligência que está no mercado de pesquisas há 9 anos. A especialidade da Quest é pesquisas para o setor automobilístico. A IndeCX é uma startup dentro da empresa que atua com pesquisa de satisfação, NPS, monitoramento da lealdade em tempo real para qualquer segmento. Somos uma plataforma SaaS.

### Descrição: Ocupações do cargo

Você será responsável por ajustar toda nossa lista de bugs do sistema atual, bem como sugerir e implementar melhorias no sistema.

### Benefícios

O regime de contratação será negociado diretamente com a empresa mas ambos contam com os seguintes benefícios:

Vale Alimentação;
Vale Refeição;
Plano de saúde;
Programas de bonificação.

### Aptidões e qualidades

Java e Javascript;
Configuração de servidores de aplicação tomcat
Banco de dados mysql
Integrações API's e webservices

### Perfil ideal

Como estamos falando de um trabalho remoto, é indispensável que você seja uma pessoa totalmente proativa e que saiba se auto liderar e se comunicar de forma assertiva.

### Labels:

REMOTO
Pleno

### Candidatar: http://bit.ly/indecx_github

**Comment by ifragas** [comment]
Essa vaga ta mais pra full stack

**Comment by Leonardofreua** [comment]
Enviado.

**Comment by megandavulpi** [comment]
> Essa vaga ta mais pra full stack

Realmente @ifragas , você não é a primeira pessoa que me diz isso... passei esse feedback para a empresa responsável, ok? =)

**Comment by LFeh** [comment]
@megandavulpi Lembrando que não é um problema cadastrar vaga Fullstack aqui, mas precisa se basear na stack Node.js 😄

**Comment by megandavulpi** [comment]
> @megandavulpi Lembrando que não é um problema cadastrar vaga Fullstack aqui, mas precisa se basear na stack Node.js 😄

Beleza! @LFeh =)

**Comment by ifragas** [comment]
So comentei por que acho que deveria especificar no anuncio da vaga o fullstack.
Abraço !

**Comment by LFeh** [comment]
Concordo @ifragas 

Posso trocar @megandavulpi ?
