### ISSUE TITLE
[Rio de Janeiro - RJ] Front-End Developer na TVManager / REACT

### ISSUE THREAD

**Issue by danielcozer** [frontendbr/vagas#1635]
## Descrição da vaga

Somos uma Startup especializada em inovações em mídia, desenhadas para atender o mercado televisivo e produtores de conteúdo audiovisual. Não importa sua formação, o que importa é o talento e a vontade de fazer parte de um time para desenvolver uma plataforma extremamente inovadora para o mercado ! Conheça nossa plataforma: http://tvmanager.io/

Perfil desejado: Alocado - Estagiário / Junior e Pleno

## Local

Rio de Janeiro, Centro da cidade

## Benefícios

• Horário de trabalho flexível 
• Um ambiente de trabalho diferente e inovador, com uma cultura que valoriza as pessoas e a entrega de resultados 
• Hierarquia horizontalizada 
• No dress code

## Requisitos

**Obrigatórios:**

• Experiência com arquitetura Front-end, usabilidade, desempenho e testabilidade 
• capacidade de traduzir layers em código 
• Fluência em Javascript 
• Fluência em HTML/CSS
• Experiência com REACT; Express 
• Experiência de controle de versão de código-fonte (Git)
• Conhecimento de Design e UX 
• Ajudar a construir o software ao invés de apenas codar requisitos! participar ativamente da concepção e construção da TVManager

**Desejáveis:**

• Experiência NodeJS
• Experiência com Sistemas Web / SaaS
• Razoável conhecimento de BackEnd (para melhor iteração entre as partes)
• Experiência com Testes

## Contratação

A combinar

## Nossa empresa

• Maiores informações em: http://tvmanager.io/
• Vídeo explicativo da Solução: https://player.vimeo.com/video/250085951

## Como se candidatar

Por favor envie um email para **daniel@tvestore.com** com o seguinte título e informações:

• Assunto [VAGA] Desenvolvedor Front-end 
• Currículo ou Linkedin
• Github e/ou Blog - Vai nos ajudar a conhecer você e seu trabalho melhor :)

## Labels

- Alocado
- Júnior
- Pleno
- JavaScript
- React

**Comment by RenatoAreas** [comment]
Enviado! :)
