### ISSUE TITLE
[São Paulo] Front-End Developer na [Matchbox Brasil]

### ISSUE THREAD

**Issue by daniloras** [frontendbr/vagas#1636]
## Habilidades

- Sólidos conhecimentos em HTML, CSS e JavaScript
- Experiência com Angular, React ou Vue.js
- Integração com REST APIs

## O que nós buscamos

- Desenvolver e implementar novas funcionalidades e interfaces de usuário no front-end
- Criar protótipos do front-end para novos produtos
- Identificar e atuar na solução da performance do front-end
- Colaborar com equipes de produto, back-end e arquitetura da informação para o desenvolvimento de novos projetos

## Principais responsabilidades | Obrigatórios:

- Experiência com desenvolvimento de interfaces
- Experiência com desenvolvimento
- Conhecimentos em otimização para performance de front-end
- Experiência com uso de SASS e ferramentas de pré-processamento como Gulp
- Habilidade de descobrir soluções performáticas para problemas complexos
- Habilidade de comunicação e de trabalho em time
- Familiaridade com ferramentas gráficas (Sketch, Illustrator, Photoshop)

## Desejáveis:

- Experiência com testes unitários
- Experiência com VueJS / ReactJS ou Angular
- Experiência com Git
- Experiência com metodologias agéis

## Diferenciais:

- Noções de SEO
- Noções de UI e UX

## Como se candidatar

Por favor envie um e-mail para produto@matchboxbrasil.com com seu CV / LinkedIn - com o assunto: Vaga Front-End

## Labels

- Alocado
- CLT
- Júnior
- Pleno

**Comment by julianamokrejs** [comment]
Enviado!
