### ISSUE TITLE
[São Paulo] Front-End Developer Jr na WEBD7 

### ISSUE THREAD

**Issue by sistemaweb** [frontendbr/vagas#1639]
## Descrição da vaga

Trabalhamos no desenvolvimento de um ERP para uma empresa privada.

## Local

2 dias (por semana) Remoto e 3 dias (por semana) no Escritório, São Paulo - República

## Requisitos

**Obrigatórios:**
- 1 ano de experiência com programação

**Desejáveis:**
- conhecimentos em PHP
- conhecimentos em Laravel
- conhecimentos em React

## Contratação

R$ 2400,00 - PJ

## Nossa empresa

A Web D7 desenvolve sistemas, sites e lojas virtuais

## Como se candidatar

Por favor envie um email para contato@webd7.com com seu CV anexado - enviar no assunto: Vaga Dev Jr

## Labels

- Alocado
- Júnior
- PJ
- Remoto

**Comment by Pedro-Souza** [comment]
Tem a possibilidade de ser 100% remoto?

**Comment by sistemaweb** [comment]
Pode ser negociado CLT, dependendo da entrevista, manda seu currículo ai,
por favor.



*Att,**Adriano Nascimento*


Em ter, 18 de dez de 2018 às 11:26, Victor Λntonio <notifications@github.com>
escreveu:

**Comment by MrS4w** [comment]
Enviado!

**Comment by HidemitsuHashimoto** [comment]
Enviado.

**Comment by aleffelipe96** [comment]
Enviado !
