### ISSUE TITLE
[Freela Remote] Dev Front-end

### ISSUE THREAD

**Issue by kavalcante** [frontendbr/vagas#164]
## Descrição da vaga

Precisamos de um Desenvolvedor Front-end para finalizar a nova versão do sistema. Não são muitas telas e ele precisa obrigatoriamente conhecer VueJS. Pode ser remoto ou se preferir presencialmente.

## Local

Remoto ou Escritório, São Paulo - Pinheiros (a alguns metros do metro Fradique Coutinho)

## Benefícios

- Pagamento por tela validada
- Novas demandas (a ideia é servir como um contato mesmo e quem sabe se juntar ao time)

## Requisitos

**Obrigatórios:**
- Experiência com VueJS e SPA
- Ninja de Vanilla (Se não for: https://github.com/fdaciuk/curso-javascript-ninja)
- CSS Puro
- HTML Semântico

**Desejáveis:**
- Gulp ou Grunt
- conhecimentos em Node
- conhecimentos em Mongo

**Diferenciais:**
- projetos opensource

## Contratação

Freela, com pagamento por tela entregue e validada. Valor a combinar.

## Nossa empresa

A Cotabox é uma startup de cotações online onde fornecedores e compradores se encontram.

## Como se candidatar

Por favor envie um email para contato@kavalcante.com com cópia para giuseppe@cotabox.com.br com seu LinkedIn (ou CV) e ***GitHub*** - enviar no assunto: Freela Front

**Comment by klarkc** [comment]
Poxa se n fosse o VueJS eu me candidatava XD

**Comment by mauricionr** [comment]
@kavalcante valeeu, ainda hoje envio email

**Comment by Carlosxell** [comment]
Vaga animal !!

**Comment by LFeh** [comment]
@fdaciuk 😄

**Comment by sputinyk** [comment]
Ainda sou padawan no vue.JS (se fosse React eu entraria nessa barca)

**Comment by ygorlazaro** [comment]
Acabei de mandar meu e-mail :) :+1:

**Comment by kavalcante** [comment]
Pessoal, neste primeiro momento eu apenas estou tendo uma média de quanto ficaria o serviço completo para não estourar nossa cota, se você por exemplo prefere cobrar por hora, envie do mesmo jeito. Os detalhes do projeto será tratado diretamente com o outro desenvolvedor e depois que você souber os detalhes, pode reajustar se sentir necessidade :)

**Comment by ygorlazaro** [comment]
É uma pena que vocês conversam com o desenvolvedor, não passam detalhes da demanda, ficam confirmando o budget o tempo inteiro, não enviam ou atualizam o freelancer quando ele pede os arquivos e negocia as alterações e não dão respondem a qualquer pergunta feita por e-mail ou whatsapp depois de duas semanas de silêncio...

Fora isso, deve ser uma boa empresa :disappointed:

**Comment by camilatigre** [comment]
@kavalcante 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
