### ISSUE TITLE
[Rio de Janeiro] Frontend developer Júnior na Cyberlabs

### ISSUE THREAD

**Issue by luiguild** [frontendbr/vagas#1640]
## Descrição da vaga

Tá afim de trampar com Javascript moderno e Machine Learning no front? Mas tipo, Machine Learning real, treta séria! Trabalhamos com tecnologia de ponta para criar aplicações reais de inteligência artificial para navegadores e clouds próprias com GPU aqui no Rio! 

Tenho uma vaga aberta para Front-end Junior que esteja afim de aprender e se aprofundar no mundo do desenvolvimento web comigo mesmo. A vaga é simples e exige apenas que o candidato tenha um conhecimento médio/avançado em HTML e CSS, saiba o básico/intermediário de Javascript (ES6), tenha feito algo mínimo com Vue ou React e que conheça o conceito de componentes e componentização. Também é importante que o candidato tenha algum portfólio aberto e publicado no Github e que tenha tido alguma experiência prévia em alguma outra empresa/startup. 

É uma vaga de Front-end, então tenha em mente que amar CSS e HTML é um requisito obrigatório. Da mesma forma, saber os conceitos de responsividade, semântica, estruturação mínima de projeto e como fazer uma landing page ou um dashboard com gráficos e animações mínimas do zero, sem frameworks. Você não precisará criar ou pensar nos layouts das aplicações, mas terá de lidar com o time de UI/UX para implementar os layouts que forem passados por eles.
Não é necessário estar cursando faculdade na área ou ser formado. 

A vaga não compreende trabalho remoto e é pra uma pessoa alocada aqui no Rio de Janeiro, mais precisamente no nosso QG em Botafogo porém com a possibilidade de fazer Home Office. O regime de contratação é exclusivamente PJ, temos férias, 13º, somos bem flexíveis e abertos pra te ouvir e ensinar o que for necessário.

Temos um objetivo de manter um ambiente seguro, inclusivo e diversificado, então essa vaga priorizará candidatas mulheres, pessoas que se identificam como negras, transexuais, homoafetivas e outras minorias, mas está aberta à todos.

## Local

Escritório, Rio de Janeiro - Botafogo

#### Diferenciais

- Ambiente seguro, que preza pela diversidade e inclusão
- Desafios reais de inovação de software
- Ambiente completamente descontraído
- Geladeira sempre cheia (real) :P
- Ótima localização do escritório, pertinho do metrô
- Biblioteca virtual de livros internos da empresa à sua disposição
- Nivelamento de conhecimento periódico dos colaboradores
- Workshops e hackathons internas
- Possibilidade de participação em eventos

## Requisitos

**Obrigatórios:**
- Amor por CSS ❤️ (aquele de verdade mesmo, não CSS-in-JS)
- Amor por HTML ❤️ (pode ser PUG também ❤️)
- Conhecimento médio/avançado de HTML5 e CSS3
- Conhecimento básico/médio de Javascript (ES6 puro ou jQuery)
- Ter produzido algo mínimo com Vue (preferencialmente) ou React (e ter isso publicado em qualquer lugar para que possamos ver)
- Ter tido no mínimo uma experiência prévia com desenvolvimento de front, SPA's ou não
- Portfólio público

**Desejáveis:**
- Saber os conceitos de responsividade e semântica
- Saber montar uma estruturação mínima de projeto
- Saber fazer uma Landing Page ou um dashboard com gráficos e animações mínimas do zero, sem frameworks
- Saber o que é um AJAX e o que acontece quando fazemos um

**Diferenciais:**
- Projetos Open Source ❤️
- Github com projetinhos mínimos
- Não ser dependente do Bootstrap pra produzir nada bonitinho 😄 
- Conhecer SASS, Scss, LESS ou PUG
- Ter algum conhecimento sobre Canvas

## Contratação

PJ, com férias e 13º

## Nossa empresa

Se você curte inovação, a Cyberlabs com certeza vai te proporcionar um ambiente gigante de aprendizado. Já somos 14+ pessoas em constante evolução e crescimento, espalhadas pelo Brasil com integrantes no Rio, Brasília e Floripa e já temos projetos grandes de AI no Brasil pra você participar.

Acessa o site da Cyberlabs aí e vê melhor tudo que a gente faz (deixo a dica pra olhar a demo, fui eu que fiz :P) > www.cyberlabs.ai

## Como se candidatar

Se você tá afim de aprender muito, mas aprender muito mesmo e trabalhar com projetos grandes, construindo um mundo novo com inteligência artificial no front, vem conversar comigo no privado no telegram ou twitter (@luiguild) ou me manda um e-mail: luigui@cyberlabs.ai.

Se você não estiver apto a atender todos os requisitos mas atende a maioria, ou sente de vir conversar sobre a vaga, sinta-se a vontade.

## Labels

- Alocado
- Júnior
- PJ

**Comment by gabrielsouza1** [comment]
;-; adoraria manda meu mandar meu cv mas sou de São Paulo </3

**Comment by rodineicosta** [comment]
Sou do RJ e atualmente residindo no Pará, @luiguild. Estou me aprofundando em Ciência de Dados, Python, R, React JS e React Native. Além de não parar de estudar outras coisas (JavaScript, SAAS, Laravel, CodeIgniter, Ionic, MogoDB, GIT...). Não rola 100% remoto nessa vaga?

**Comment by luiguild** [comment]
Infelizmente não.

**Comment by luiguild** [comment]
Infelizmente não @rodineicosta

**Comment by luizbaldur** [comment]
Alo Luigi, curriculo enviado!

**Comment by NetoEduardo** [comment]
Parabéns pelo Demo, ficou bem bacana.

Se algum dia pintar uma vaga pra estágio, avisa pls.

Parece um ótimo lugar para aprender mais.

**Comment by thaisfalbo** [comment]
Enviado! =)

**Comment by luiguild** [comment]
@LFeh não é São Paulo, é Rio :)
