### ISSUE TITLE
[São Paulo e/ou remoto] Front-End Developer [D3]

### ISSUE THREAD

**Issue by teteti** [frontendbr/vagas#1642]
> A D3 é um lugar para entusiastas apaixonadxs por tecnologia, design, pessoas e trocas.
> Nós vemos o trabalho como uma plataforma de desenvolvimento e criação, por aqui prezamos pela qualidade de vida através do trabalho remoto, da flexibilidade de horários e da constante evolução. E isso exige auto responsabilidade, organização e autogerenciamento, além da capacidade de lidar com incertezas e desafios.
> Trabalhamos em squads multidisciplinares integrando pessoas diferentes e complexas que gostam muito de compartilhar conhecimentos, trocar ideias e experiências, e fazer sempre melhor.
> O que mais valorizamos é também o que mais nos motiva: pessoas incríveis, projetos incríveis, de um jeito incrível. Estamos todos conectados pelo propósito de gerar impacto positivo através da transformação digital.
> Se você compartilha desses mesmos sentimentos e dessa vontade de fazer, manda uma mensagem pra gente e vamos conversar! Você pode enviar um email para teteti@d3.do ✉️

### **Perfil**
Inteligência emocional e empatia são características essenciais para se trabalhar em equipe. Pessoas que trabalham de forma remota necessitam responsabilidade, senso de dono, organização e desenvolvem a capacidade de se autogerenciar. Para criar um processo de transformação digital é preciso ter a capacidade de lidar com incertezas, gostar de desafios e sempre procurar fazer melhor.

### **Competência**
Competência e habilidade estão relacionados. A habilidade é conseguir pôr em prática as teorias e conceitos que foram adquiridos, enquanto a competência é mais ampla e consiste na junção e coordenação de conhecimentos, atitudes e habilidades.
Buscamos pessoas competentes, capazes de modificar o meio e de se adaptar às necessidades, com iniciativa para desenvolver seus potenciais através da constante evolução e da experimentação.

### **Engajamento**
Entusiastas são pessoas apaixonadas pelo que fazem, engajadas e com iniciativa própria para se desenvolver e fazer sempre melhor que antes. Ter um propósito nos faz alcançar de forma mais eficiente aquilo que almejamos e essa motivação é o que gera perspectiva de evolução. Portanto, não basta ser muito bom se não há engajamento em ser sempre melhor.

### **Front End Jr. ou Pleno(a)**
O desenvolvedor ideal para D3 tem potencial de crescimento aliado ao conjunto de experiências que teve, sejam elas profissionais ou experimentais.
Esse potencial de crescimento se dá pela paixão pelo que faz, quando a pessoa se engaja com o propósito de evoluir a prática acontece mesmo que não seja um compromisso profissional. A curiosidade e o gosto pela experimentação fazem com que essa pessoa goste de aprender e conforme domina a técnica se torna cada vez mais rápido.
Buscamos pessoas que tenha experiência com versionamento de código, integração contínua, testes integrados, e que saibam resolver problemas. Pessoas que perguntam, interagem, se organizem, se comuniquem. Queremos entusiastas e não pessoas que estão aprendendo para trabalhar.

**Ferramentas** e tecnologias que utilizamos, mas que não delimitam nossa busca:
Python / Django
Ruby on Rails
React / React Native
Objective-C / Java for Android
GitHub
Docker
AWS / Google Cloud / Azure

**Comment by Jessycanoronha** [comment]
Só de ler gostei bastante da empresa de vcs!Vou mandar meu currículo!
