### ISSUE TITLE
[São Paulo] Front-End Developer com Angular atuar na [5A Attiva] 

### ISSUE THREAD

**Issue by helenmatos** [frontendbr/vagas#1645]
## Descrição da vaga
A 5A Attiva busca profissionais de Front end com Angular para atuar em um grande projeto, fazendo parte de um time diferenciado, com profissionais antenados que se preocupam com o desenvolvimento de soluções dentro dos melhores padrões de mercado. 

## Local
Atuar em Escritório, Alphaville 

## Requisitos

**Obrigatórios:**

Experiencia com HTML, CSS, SASS, Javascript, jQuery e GIT, Photoshop e Zeplin para recorte
jobs de interface programados em AngularJS e C# com MVC e Gulp. 

**Diferenciais:**
Conhecimentos em Angular 2

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um e-mail para Talita.rodrigues@5aattiva.com.br  com seu CV anexado - enviar no assunto: Front-End Developer / Angular

## Labels
- PJ
- Pleno
- Sênior

**Comment by LFeh** [comment]
A contratação vai ser pela 5aattiva?

**Comment by helenmatos** [comment]
Isso mesmo
