### ISSUE TITLE
[São Paulo] Fullstack Developer no Cubo 💙

### ISSUE THREAD

**Issue by LFeh** [frontendbr/vagas#1646]
## Descrição da vaga

Temos uma plataforma que tem como propósito entregar o mesmo valor que o Cubo Itaú oferece aos residentes de maneira expandida "digitalmente" a outras startups do mercado. 

Seu maior desafio será desenvolver e manter as features em parceria com as demais pessoas do time: desenvolvedores, designers e product owner. 

Precisamos de alguém que vá **além de código** e entenda que desenvolvemos sistemas para pessoas usarem. Sendo assim, você estará livre para propor melhorias, ter ideias e participar ativamente de todas as partes da concepção do produto.

#### Nossa stack atual

- Angular
- Node.js
- Arquitetura Serverless
- DynamoDB

## Local

[Escritório, São Paulo - Vila Olímpia](https://www.google.com/maps/@-23.5968692,-46.6869093,18.4z)

## Benefícios

- Vale refeição
- Vale alimentação 
- Plano de saúde (opcional)
- Plano odontológico (opcional)
- Participação nos lucros

#### Diferenciais
 
- Chopp liberado todos os dias (18:00 - 20:00)
- Salão de jogos
- Sem _dress code_

### Obrigatórios:

- Se aplicar através da [nossa plataforma de vagas](https://cubo.network/jobs/06690850-0304-11e9-9aa8-a3aa8c4bd450)
- Concluir o [teste que está em nosso GitHub](https://github.com/cubonetwork/fullstack-challenge);
- Superior Completo;
- JavaScript
- CSS
- HTML
 
### Diferenciais:

- Projetos open-source
- Conhecimentos de AWS (Gateway API, Functions Lambda, SNS, S3) 
- Arquitetura Serverless

## Contratação

CLT a combinar

## Nossa empresa

O Cubo Itaú – o maior e mais relevante centro de empreendedorismo tecnológico da América Latina – foi idealizado pelo Itaú Unibanco, em parceria com a Redpoint eventures. Nosso objetivo desde 2015 é conectar em um só lugar empreendedores, grandes empresas, investidores e universidades para discutir sobre tecnologia, inovação, novos modelos de negócios e novas formas de trabalhar.

No meio do ano mudamos para um prédio 4 vezes maior.

#### Laje no nosso novo prédio 🌆 

<img width="450" src="https://user-images.githubusercontent.com/3603793/50183750-25287a00-02fa-11e9-9dd5-112a558b40d1.png">

#### Chopeira 🍻

<img width="450" src="https://user-images.githubusercontent.com/3603793/50183847-78023180-02fa-11e9-8530-1032850696fa.png">
 
#### Time do Cubo Digital ❤️ 

<img width="450" src="https://user-images.githubusercontent.com/3603793/50183202-818a9a00-02f8-11e9-92cb-ad96d42df729.png">
  
## Como se candidatar 

Se [aplique na vaga através da nossa plataforma de vagas](https://cubo.network/jobs/06690850-0304-11e9-9aa8-a3aa8c4bd450) e faça o [teste que está em nosso GitHub](https://github.com/cubonetwork/fullstack-challenge).

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: dev@cubo.network

**Comment by Pedro-Souza** [comment]
Não tem a possibilidade de ser remoto?

**Comment by LFeh** [comment]
Só alocado :)

**Comment by baltazarparra** [comment]
Superior Completo obrigatório em 2018?

**Comment by LFeh** [comment]
Sim @baltazarparra, também não concordo com esse ponto,  mas é uma exigência da vaga.

**Comment by vitorfreitas** [comment]
Uma pergunta: No teste, é necessário q os dados sejam salvos em algum banco?

**Comment by muriloamendola** [comment]
@vitorfreitas ficaríamos bem felizes se você utilizar um banco de dados para persistir as informações, ainda mais se for um banco de dados NoSql. 
Apenas a título informativo nós utilizamos DynamoDB.
Mas, fique tranquilo caso queira apenas mockar os dados. Nossa avaliação levará outros pontos em consideração ;)

**Comment by israelcena** [comment]
Superior completo em marketing é válido ?

**Comment by muriloamendola** [comment]
é válido sim @israelcena!

**Comment by LFeh** [comment]
@israelcena É valido sim  😊

**Comment by robennelson** [comment]
AngularJS ou Angular (TypeScript)?

**Comment by muriloamendola** [comment]
Angular 7

**Comment by LFeh** [comment]
Feedbacks serão dados nas próximas semanas :)
