### ISSUE TITLE
[Santo André] Desenvolvedor Front-End

### ISSUE THREAD

**Issue by mariosmello** [frontendbr/vagas#165]
## Descrição da vaga

Atuar com desenvolvimento Front-end responsivo.

## Local

Rua Bernardino de campos, 31
Santo André - SP
Próximo a estação de trem / terminal de ônibus

## Benefícios

- Vale-transporte
- Vale-refeição
- Convênio médico Amil
- Convênio odontológico Amil 

## Requisitos

**Obrigatórios:**
- HTML/HTML5
- CSS/CSS3
- Habilidade para montagem responsiva
- Utilização de técnicas de SEO
- Familiaridade com JavaScript puro
- jQuery (programação e uso de plugins)
- Photoshop (recorte de layouts)
- Illustrator (recorte de layouts)

**Desejáveis:**
- SASS
- Workflow moderno e automação de processos, utilizando tecnologias como Gulp ou Grunt
- Habilidade com vagrant + virtualbox
- Familiaridade com bootstrap para interfaces de sistemas web
- WAI Aria
- Microdata
- Conhecimento em montagem/adaptação de templates para WordPress

**Diferenciais:**
- Conhecimento em AngularJS

## Contratação

**CLT Full**
de R$ 2.000,00 à R$ 3.000,00

## Nossa empresa

Localizados no ABC paulista somos um estúdio de programação web e mobile voltado ao atendimento de agências de publicidade

## Como se candidatar

Por favor envie um email para vagas@dindigital.com com seu CV anexado
enviar no assunto: Vaga Front-End

**Comment by gabrielrunescape** [comment]
Remoto ou presencial?

**Comment by camilatigre** [comment]
@mariosmello 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by camilatigre** [comment]
@mariosmello 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
