### ISSUE TITLE
### [Porto Alegre] Desenvolvedor(a) Android Sr -  Deliver IT

### ISSUE THREAD

**Issue by Melissatrevisan1** [frontendbr/vagas#1650]
### Descrição da vaga
Somos uma empresa jovem, dinâmica, apaixonada por desenvolver soluções inovadoras para nossos clientes entregando valor. Se você também adora tecnologia e quer fazer parte dessa construção, vem fazer parte do nosso time de talentos.

### Local
Porto Alegre - RS

### Posição
Sênior

### Benefícios
Assistência médica
Assistência odontológica
VT
VR ou VA
Gympass
Convênio com instituições de ensino
Bônus de aniversário de empresa
Bônus de campanha de indicação premiada
Ações para desenvolvimento na área de TI

### Obrigatórios

•	Experiência no desenvolvimento de aplicações Android
•	Integrações com serviços web internos e externos (APIs, RESTful e SOAP)
•	Conhecimentos em controle de versão no Git e gerenciamento de dependências (Gradle)
•	Publicação de versões na Play Store
•	Apoiar a área de desenvolvimento e participar da resolução de problemas
•	Experiência em metodologias ágeis (SCRUM e Kanban)
•	Ter facilidade para trabalhar dentro de times multi-disciplinares
•	Controle de versão (GIT, GIT Flow). 
•	Implantação de melhorias. 
•	Correção de bugs.
•	Envio de Push Notifications
•	Integração com redes sociais.
•	Processo de publicação na Play Store. 

### DESEJÁVEIS

•	Conhecimento em arquitetura MVP e Android Architecture Components.
•	Conhecimentos em testes automatizados (unitários e de interfaces).
•	Injeção de dependências.
•	Ferramentas de tracking (GA).
•	Conhecimento em Java e Kotlin.

### Contratação
CLT 

### Como se candidatar
Por favor envie um email para sejadeliver@deliverit.com.br com seu CV anexado - enviar no assunto: Vaga Android Sr
https://www.linkedin.com/company/deliver-it-servi%C3%A7os-de-tecnologia/

**Comment by LFeh** [comment]
Olá @Melissatrevisan1, essa vaga é para desenvolvedores Android e foge do universo Front-end :)

**Comment by Melissatrevisan1** [comment]
Entendi errado, entao felipe, entendi que as vagas de desenvolvimento para
aplicações usuário em android poderiam ser divulgadas nesta lista, me
desculpe.

*Cel: 051 99902.9756*

*Atenciosamente, **Melissa Trevisan*


Em sex, 21 de dez de 2018 às 11:14, Felipe Fialho <notifications@github.com>
escreveu:

**Comment by LFeh** [comment]
Sem problemas!
