### ISSUE TITLE
[São Paulo] Front-End Developer na Juntos Somos +

### ISSUE THREAD

**Issue by dbfarias** [frontendbr/vagas#1651]
## Descrição da vaga

Estamos em busca de um Front-End Developer para atuar em um projeto muito desafiador e com grande impacto social. Somos o maior programa nacional de fidelidade do varejo de material de construção e temos o propósito de modernizar e desenvolver o setor através de inovação e colaboração.

## Local

Estamos em um co-working (Cow) na Vila Olímpia

## Benefícios

- Remuneração variável
- Home-Office (não sempre)
- _Dress Free_
- Plano de saúde
- Plano Odontológico
- Seguro de vida
- VR

## Requisitos

**Obrigatórios:**
- Ter pelo menos 5 anos de experiência com desenvolvimento de software;
- Domínio de Javascript;
- Conhecimento em HTML, CSS e JavaScript com testes unitários (por exemplo Jasmine, Jest, Mocha, Chai, etc.);
- Ter trabalhado com pelo menos um dos frameworks: Vue.js, Angular, React, Ember, etc.;
- Experiência com RESTful APIs;
- Conhecer SASS, LESS, Grunt, Gulp, Webpack;

**Desejáveis:**
- Familiaridade com Sketch;
- Ter atuado em times ágeis (Kanban, Scrum) e gostar de atuar com time multi-funcional;
- Conhecer técnicas e gostar de discutir interface/usabilidade de produto;

**Diferenciais:**
- Ter experiência com desenvolvimento de apps (iOS e Android) usando React Native;

## Contratação

CLT Full

## Nossa empresa

Juntos Somos +  é o maior programa nacional de fidelidade do varejo de material de construção e funciona como um plano de benefícios para as lojas, vendedores e profissionais da construção civil. 
Com o propósito de modernizar e desenvolver o setor, iniciamos uma jornada de inovação e colaboração, que conta com um time inspirado e pronto para o desafio. 

Além das acionistas Votorantim Cimentos, Gerdau e Tigre, participam também o Banco Santander, Linx, Vedacit, Eternit, Suvinil, Stam, Bosch, Ciser, Ourolux e Cozimax.

## Como se candidatar

Por favor envie um email para danny.farias@juntossomosmais.com.br com seu CV anexado - enviar no assunto: Vaga Front-End Developer.

## Labels

- CLT
- Pleno
- Sênior

**Comment by ReactGirl** [comment]
Dress Free é beneficio? Alguma empresa ainda pede dress code?

**Comment by MaryCaroline** [comment]
Sim, várias infelizmente.

> Dress Free é beneficio? Alguma empresa ainda pede dress code?
