### ISSUE TITLE
[São Paulo] Iteris Consultoria - .NET Core Developer

### ISSUE THREAD

**Issue by rhiteris** [frontendbr/vagas#1658]
**Sobre a Iteris:**

A Iteris é parceira das maiores fornecedoras de tecnologia do mundo e especialista no desenvolvimento de soluções web, mobile, colaboração e BI.

Somos comprometidos com os desafios da TI dos nossos clientes e nossa missão é prestar serviços de TI com excelência na qualidade e atendimento diferenciado, buscando construir laços reais e duradouros com nossos clientes, colaboradores e parceiros.

Procuramos pessoas que gostem de desafios, se interessem verdadeiramente em transformar a TI em diferencial para os negócios das empresas e sejam apaixonadas por tecnologia.

 
**Missão do cargo:**

Compreender o negócio e a necessidade do cliente, de forma a desenvolver a aplicação que melhor atenda aos seus desafios, dentro do prazo estipulado.

**Nível:** Sênior.

**Que tipo de habilidades buscamos?**

- Ser criativo e cheio de ideias;
- Ser comunicativo e curtir trocar experiências;
- Gostar de compartilhar e absorver conhecimento;
- Ser questionador naquilo que faça sentido;
- Se preocupar com o cliente que está utilizando aquilo o que desenvolvemos;
- Mantem-se atualizado e sempre está por dentro de novas tecnologias;
- Sentimento de dono no que atua;
- Procura ser organizado e opinar em soluções;
- Técnicas e práticas ágeis para os ciclos de desenvolvimento tornam suas entregas mais efetivas e fica motivado com o resultado agregado a cada sprint.

**O que você precisa fazer?**

- Experiência nas etapas de análise conceitual e desenvolvimento de aplicações de negócio utilizando .NET Framework 4.0, Workflow Foundation, Communication Foundation, LINQ e JQuery.

**Extras que podem ajudar ainda mais na sua contratação:**

- Conhecimentos em SharePoint, conceitos de SOA;
- Experiência em desenvolvimento de sistemas web-based (em resumo, HTML 5, CSS 3 e Javascript,  jQuery, Backbone, AngularJS e React);
- Experiência com banco de dados (SQL Server e/ou ORACLE);
- Certificações MCTS e MCPD.

**O que oferecemos?**

- Pacote atraente de remuneração;
- Time altamente capacitado, focado em meritocracia, colaboração e constante atualização tecnológica;
- Ambiente descontraído e horário flexível;
- Cesta de benefícios flexível para distribuir livremente entre VR, VA e VT.

**Comment by LFeh** [comment]
Duas coisas:

- A vaga postada não é Front, recomendo que poste no @backend-br
- Você está abrindo vagas seguidas e fechando

**Comment by rhiteris** [comment]
> Duas coisas:
> 
> * A vaga postada não é Front, recomendo que poste no @backend-br
> * Você está abrindo vagas seguidas e fechando

Os labels são adicionados por vcs ou por mim?

**Comment by LFeh** [comment]
São adicionadas por nós, mas precisamos que a vaga esteja dentro das regras
