### ISSUE TITLE
[Belo Horizonte] Sympla - Desenvolvedor Frontend Pleno/Sênior.

### ISSUE THREAD

**Issue by naroga** [frontendbr/vagas#166]
## Descrição da vaga

Como membro da equipe de Produto, você será responsável pela elaboração de novas ferramentas, manutenção das ferramentas existentes e pela tomada de decisões relacionadas à arquitetura das aplicações e dos microsserviços que compõem o ecossistema da Sympla.

## Funções desta posição:
* Contribuir com tomada de decisões de todos os processos de desenvolvimento, passando desde a escolha das tecnologias utilizadas até os processos de build/deploy;
* Nos ajudar a manter um espírito ágil;
* Ter orgulho de colocar em produção código que é usado por milhões de pessoas Brasil afora. Para isso, qualidade deverá ser sua obsessão;
* Assegurar a melhor qualidade de experiência para nossos usuários.
* Desenvolver, claro.

## Local

Presencial, R. Fernandes Tourinho, 147, Savassi, Belo Horizonte

## Benefícios
* Ambiente criativo, inovador e estimulante;
* Regime de contratação CLT;
* Salário compatível com o mercado;
* Vale transporte (ônibus ou gasolina);
* Vale refeição ou Vale-alimentação;
* No dress code (pode trabalhar de bermuda, chinelo, etc);
* Clima descontraído;
* Café, bebidas variadas e snacks;
* Horário Flexível;
* Plano de saúde e odontológico, desconto em farmácias;

## Requisitos

**Obrigatórios:**

* Esperamos que você seja proativo trazendo sempre novas ideias para resolvermos nossos desafios;
* Buscamos alguém que tenha um excelente conhecimento em tecnologias de desenvolvimento front-end, em geral; Que esteja atento às tendências do mercado e que seja capaz de se adaptar rapidamente a novas tecnologias.
* Que tenha um amplo conhecimento das ferramentas do ecossistema de front-end, em geral: Gulp, Grunt, npm, etc;
* Capacidade de conciliar demandas e prazos comerciais com qualidade de engenharia;
* Conhecimentos avançados em Javascript!
* Conhecimento em HTML5 e CSS3.

**Desejáveis:**
* Experiência com alguns frameworks modernos: AngularJS, ReactJS, etc.
* Profunda compreensão do DOM e suas propriedades;
* Inglês e/ou espanhol intermediário.

## Contratação

CLT, salário a combinar.

## Nossa empresa

A Sympla é uma startup sediada em Belo Horizonte que, em menos de três anos de existência, se tornou a plataforma de eventos mais utilizada no Brasil e possui o site com o maior número de eventos à venda no país. 

Com o objetivo de simplificar e otimizar a criação e gestão de eventos para produtores e melhorar a experiência da compra de ingressos online pelos participantes, oferecemos diversas ferramentas eficazes e soluções inteligentes para todas as etapas de um evento. Aqui, você poderá participar da expansão de uma startup jovem e que já é referência no mercado online ticketing no país. 

Encara o desafio?

## Como se candidatar

Envie seu currículo pelo nosso link 'trabalhe conosco': http://www.sympla.com.br/trabalhe-conosco#job-9502

![Our team](http://d1gkntzr8mxq7s.cloudfront.net/57b5d36738797.png)

**Comment by cmpereirasi** [comment]
Essa vaga é Top! Será que é a impressão minha?! Primeira vaga para BH aqui no Issues!
