### ISSUE TITLE
[São Paulo] Dev ionic [Keycar]

### ISSUE THREAD

**Issue by paullonorato** [frontendbr/vagas#1662]
Estamos com 3 posições em aberto para Dev Ionic aqui na Keycar, tem interesse?
Projeto na área de mobilidade urbana, com duração entre 3 e 4 meses alocado em Vitória/ES, sendo hospedagem, alimentação e transporte por conta da empresa.

Requisitos 
Experiência em projetos com metodologia ágil;
Nível pleno, entre 2 a 3 anos de experiência em desenvolvimento de projetos utilizando Ionic/React Native;
Experiência com padrões e arquitetura de HTML5 (W3C), CSS (BEM ou OOCSS) e JS (ECMA6);
Experiência com pre-processador SASS;
Experiência com integração de API Restful;
Experiência com as melhores práticas de versionamento de projeto utilizando GIT ou similares;

Desejável 
Graduação completa ou em andamento nas áreas de engenharia de sistemas, análise e desenvolvimento ou similares;
Noção básica das linguagens Swift, Objective-C e/ou Android SDK;
Conhecimento da guideline dos sistemas iOS e Android;

Tipo de contratação
Contratação no modelo PJ (5 a 7k), tendo a possibilidade de participar de outros projetos do grupo após o término deste.

Enviar cv com pretensão salarial para rh@keycar.com.br

**Comment by Mendrone** [comment]
@paullonorato Fala sumido! Consegue formatar a vaga corretamente (seguindo o template sugerido) pra ajudar a gente? Valeu!

**Comment by paullonorato** [comment]
@Mendrone, meu lindhu, desculpa!!! Eu juro que esqueci dessa publicação, tava tão na correria que passou despercebido, desculpa mesmo =/

**Comment by felipefialho** [comment]
Tranquilo Paullo, se precisar abre de novo depois 😄
