### ISSUE TITLE
[São Paulo] Full-Stack Developer na [OtimizeMe]

### ISSUE THREAD

**Issue by Allansrod** [frontendbr/vagas#1665]
## Descrição da vaga

Estamos em busca de desenvolvedores(as) para fazer parte do nosso time imediatamente! Nosso escritório é em Paraíso - São Paulo, trabalhamos em um clima informal com foco em produtividade das tarefas, que em alguns casos são recompensadas com bônus $$$. 

Nesse momento temos um bônus para um projeto que será concluído neste primeiro trimestre. 
É importante você já ter experiência em desenvolvimento utilizando frameworks.

## Local

R. Carlos Steinen, 412 - ParaísoSão Paulo - SP

## Benefícios

- Bônus de conclusão de projetos

## Requisitos

**Obrigatórios:**
- Inglês intermediário
- Experiência em desenvolvimento utilizando frameworks
- Php, mysql e estruturação de banco de dados
- Conhecimentos em laravel e/ou outro mvc
- Noção de php design patterns
- Capacidade de documentar o próprio código
- Proatividade para o planejamento antes de executar a tarefa
- Boa vontade de compartilhar o que sabe

**Desejáveis:**
- Html, css, javascript, jquery e vue2
- Saber trabalhar com uso de boas práticas
- Familiaridade com bootstrap 4, angular e / ou react
- Conhecimento de node.js
- Consumo e criação de api rest

## Contratação

PJ a combinar

## Nossa empresa

Somos uma Agência focada em marketing digital de performance, nosso objetivo é a entrega resultados para nossos clientes. Se você se encaixa nesse objetivo, teremos prazer em recebe-lo no nosso time.

Trabalhamos com desenvolvimento de soluções e-commerce customizadas, marketing digital e também treinamentos.

## Como se candidatar

Usando o formulário no link: https://otimize.me/vagas/#Devphp
Ou nos envie um email para contato@otimize.me com seu CV anexado - enviar no assunto: Vaga  Font-end SP

PS: enviar pretenção salarial

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dia após cada processo.

## Labels

- PJ
- Pleno

**Comment by ReactGirl** [comment]
Vaga de Front-end.
Conhecimentos obrigatorios: Php, mysql e estruturação de banco de dados
Desaejaveis: Html, css, javascript, jquery e vue2

Ta tudo certo ai.

**Comment by Allansrod** [comment]
> Vaga de Front-end.
> Conhecimentos obrigatorios: Php, mysql e estruturação de banco de dados
> Desaejaveis: Html, css, javascript, jquery e vue2
> 
> Ta tudo certo ai.

Full stack mas não deixa de trabalhar com front né..então...

**Comment by victorhsantiago** [comment]
Então a vaga é para full stack, não apenas front end como anunciado

Por gentileza, corrija essas informações

**Comment by Allansrod** [comment]
> Então a vaga é para full stack, não apenas front end como anunciado
> 
> Por gentileza, corrija essas informações

As regras de postagem pedem pra usar Front-end no titulo
