### ISSUE TITLE
[Florianópolis] Front-End Developer na Sábia Experience

### ISSUE THREAD

**Issue by xandyalexandrec** [frontendbr/vagas#1667]
## O que esperamos de você:

- Pró-atividade;
- Background em design;
- Sempre buscar inovar e trazer novas tendências;
- Ter espírito de trabalho em equipe;

## Local

Sapiens Parque
Av. Luiz Boiteux Piazza, 1302 - Canasvieiras, Florianópolis - SC, 88056-000

## Benefícios

- Remuneração competitiva;
- Plano de saúde;
- Vale-Transporte;
- Vale-refeição;

#### Diferenciais

- Dress free;
- Ambiente descontraído;
- Mesa de Ping Pong;
- Empresa de Inovação na área de Educação;
- A 700m da praia;

## Requisitos

**Obrigatórios:**
- Conhecimentos sólidos de JavaScript;
- Experiência com AngularJS / VueJS;
- HTML5/CSS3;
- SASS/LESS;

**Desejáveis:**
- Competências em UX/UI;
- Experiência com Interfaces customizadas e animações;
- Figma;
- Integração de APIs ao Front-end;
- Testes unitários e automatizados;

**Diferenciais:**
- Fará muita diferença ter experiência com direta com design

## Contratação

CLT

## Nossa empresa

A Sábia Experience é uma empresa de inovação atuando como EdTech, especializada em educação imersiva usando storytelling e gamificação. além de realidade virtual e aumentada.

## Como se candidatar

Por favor envie um email para alexandre.custodio@sabia.com.br com seu CV anexado - enviar no assunto: [Vaga] Front-end Developer

## Labels

- Alocado
- CLT
- PJ
- Pleno
- Sênior

**Comment by desenvolvedorIcotrade** [comment]
Olá sou de Joinville, Estou em Busca de  Oportunidade Melhores! $ com Crescimento ...
