### ISSUE TITLE
[Remoto ou Vitória-ES] Knockout.js Developer na N3X Solutions 

### ISSUE THREAD

**Issue by n3xsolutions** [frontendbr/vagas#1668]
## Apresentação
Somos uma empresa especializada em apps inovadores.
Estamos em busca de profissionais que gostam de desafios e com muita vontade de crescer! E nós teremos o maior prazer em proporcionar isto!

## Vaga
Front-End Developer com experiência em Knockout.JS
Remoto ou presencial em Vitória - ES.

## Requisitos
- Profundo conhecimento/experiência Knockout.js
- Javascript
- ES6
- HTML5, CSS3

## Desejável
- RESTful APIs
- Testes unitários e automatizados
- GIT
- NodeJs

## Compensação
- Salário compatível
- Programa de crescimento

## Como se candidatar

Enviar email com o curriculum para suporte@n3x.com.br

## Labels

- Remoto
- Pleno
- PJ

**Comment by hnrqsss** [comment]
Ainda está disponível?

**Comment by n3xsolutions** [comment]
Boa Tarde,

Conseguimos preencher ontem.
Obrigado!
Sds.
