### ISSUE TITLE
[Rio de Janeiro] Vaga temporária p/ Front-End e Backend @ TV Globo #backend #frontend #temporário 

### ISSUE THREAD

**Issue by ridjohansen** [frontendbr/vagas#167]
## Descrição da vaga
Ao todo são 6 vagas temporárias abertas.
Contrato temporário de 6 meses, com possibilidade de contratação.

### Front-end:
Desenvolvimento utilizando as tecnologias abaixo:
- HTML5/CSS
- AngularJS
- Javascript
- Git/GitFlow/Gitlab

### Back-end:
Desenvolvimento utilizando as tecnologias abaixo:
- Node.JS
- AWS (BeanStalk, EC2, Cloudfront, S3)
- Git/GitFlow/Gitlab
- DB (MySQL, NoSQL)

## Local

Estúdios Globo (PROJAC) - Jacarepaguá - Rio de Janeiro/RJ 

## Contratação

Contrato temporário de 6 meses, com possibilidade de contratação

## Como se candidatar

Por favor envie um email para richard.johansen@tvglobo.com.br com seu CV anexado - enviar no assunto: Vaga PROJAC [Backend/Frontend]

**Comment by gkal19** [comment]
Tem alguma chance de remoto?

**Comment by chicojunior** [comment]
A vaga é pra Full-Stack ou separado?

**Comment by lucasalmeida92** [comment]
Enviado! ;]

**Comment by saulojmc** [comment]
Foi preenchido?
