### ISSUE TITLE
[São Paulo] Pessoa desenvolvedora Front-end [AutoSeg]

### ISSUE THREAD

**Issue by doglasbatista** [frontendbr/vagas#1671]
## Descrição da vaga

Estamos buscando pessoas que almejam crescimento pessoal e profissional, junto à empresa. Seguimos uma cultura ágil: gostamos de fazer pair programming, testes, code reviews e troca de conhecimentos.

### Sobre a vaga 

Seu dia-a-dia consistirá na manutenção dos nossos sistemas e desenvolvimento de novas funcionalidades.
Estamos contratando pessoas de todos os níveis.

## Local

Estamos localizados no Edifício Itália, República

## Benefícios

- Vale-transporte;
- Vale-refeição;
- Plano médico Amil Blue 600;
- Plano Odontológico Amil.

#### Diferenciais

- Participação em comunidades de TI 
- Somos abertos a novas tecnologias e plataformas.
- Gostamos de inovação e pensamos em soluções com o time e o projeto;
- Hack morning/evening (Tech talks)
- Open Source Day 
- Ambiente agradável e sem dress code (venha como se sentir à vontade ;D)

## Requisitos

**Obrigatórios:**
- Javascript;
- HTML5/CSS3;
- API RESTFUL.

**Desejáveis:**
- SASS, LESS, STYLUS, POSTCSS;
- Algum framework (Vue, Angular, React). Usamos Vue :p.
- Alguma linguagem back-end. Preferência por Ruby
- TDD

**Diferenciais:**
- Docker
- Programação funcional

## Contratação

CLT

## Como se candidatar

Usando o link: https://trampos.co/oportunidades/144338

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dia após cada processo.

## Labels

- Alocado
- CLT
- Júnior
- Pleno
- Sênior

**Comment by nb4rs0tt1** [comment]
Oi Doglas! Como faço para me candidatar?

**Comment by doglasbatista** [comment]
@nb4rs0tt1 Já atualizei o anuncio, acabei esquecendo de colocar o link da primeira vez. Foi mal

**Comment by MrS4w** [comment]
Aplicado!

**Comment by HidemitsuHashimoto** [comment]
Aplicado.
