### ISSUE TITLE
[Rio de Janeiro] Front-End Developer na ODGO

### ISSUE THREAD

**Issue by megandavulpi** [frontendbr/vagas#1673]
### Sobre a empresa: ODGO

Somos uma empresa jovem e muito nova também, criada no ano de 2018. Somos uma consultoria de viagens para Portugal. Ainda estamos estruturando nosso time de programadores e precisamos de um funcionário motivado e muito enérgico, que saiba lidar com a liberdade e a autonomia que a empresa proporciona.

### Descrição: 

**O que você irá fazer?**

Realizar testes de experiência com usuários;
Implementar interfaces web;
Integrar aplicação com banco de dados. 

### As habilidades necessárias:

JavaScript;
HTML;
CSS.

### Diferenciais:

Node.Js;
React;
Cultura scrum.

### Benefícios:

Gympass;
Plano de Saúde e Odontológico.

### Você gostará de trabalhar aqui se:

Trabalhar com sangue nos olhos e com sentimento de propriedade da empresa;
Ser pró ativo e ter muita iniciativa;
Buscar por possibilidade concreta de crescimento.

### Informações complementares:

Você irá trabalhar 8 horas diárias. O horário de trabalho é flexível;
Ambiente de trabalho descontraído;
No dress code;
Estamos localizados no Botafogo.

### Labels:

Alocado
Junior

### Candidatar: http://bit.ly/odgo_github

**Comment by allancarlos123** [comment]
Somente alocado? :/

**Comment by megandavulpi** [comment]
> Somente alocado? :/

Sim =/

**Comment by Matheus12000** [comment]
Boa tarde, tenho conhecimento em Html, Css e estou fazendo um curso de JS. Gostaria de saber se o nível de conhecimento em JS é básico ou alto. Obrigado.
