### ISSUE TITLE
[Ribeirão Preto - SP ou Remoto] Desenvolvedor Frontend React @ ZeroSoft

### ISSUE THREAD

**Issue by nihey** [frontendbr/vagas#1674]
## A Empresa

Nascida no final de 2017, a Zerosoft Tecnologia está em constante crescimento! Possui alguns clientes chave no fornecimento de outsourcing, além de estar almejar diversos projetos inovadores! O foco dos produtos é análise, visualização e inteligência de dados.

## As Vagas

* Estagiário (30h a 40h semanais)
* Desenvolvedor Frontend Junior (30h a 40h semanais)
* Desenvolvedores Frontend Pleno (30h a 40h semanais)

## Requisitos

É esperado de todos os cargos vontade de crescer e aprender mais. Todos os dias temos novos desafios!

- Requisitos
  - JavaScript/Node.js (preferencialmente com ES6)
  - React/React Native
  - Redux
  - Git
  - REST

* Diferenciais
  * Ser autodidata
  * Gostar de desafios tecnológicos
  * Possuir bons conhecimentos de Linux
  * Ter capacidade de assimilar conhecimento rapidamente

## Contratação

- Local
  - Presencial (preferencialmente)
  - Remoto

* Regime CLT ou PJ

## Como se candidatar

Interessado? Envie um email para hireme@zerosoft.com.br com o seu curriculo ou link do linkedin. Adicione também seu perfil do github, link de algum projeto que desenvolveu, etc.

**Comment by allisonsampaio** [comment]
Currículo enviado!

**Comment by ThalesAlonso** [comment]
Currículo enviado!

**Comment by LuanCassiano** [comment]
Currículo enviado.

**Comment by Pedro-Souza** [comment]
Enviado.

**Comment by Unpierrez** [comment]
Enviado.

**Comment by GiovanniSM20** [comment]
Currículo anexado ;)

**Comment by ReactGirl** [comment]
Qual a medida utilizada no critério "Ter capacidade de assimilar conhecimento rapidamente".
Exemplo:
Adquirir rating fide do xadrez de 1200 a 1800 em um mes.
Ou coisas do tipo?

**Comment by nihey** [comment]
@ReactGirl é um critério um pouco subjetivo, então não existe uma métrica, mas seria relativo à capacidade de se adaptar à diferentes situações e desafios técnicos de programação de maneira rápida.
