### ISSUE TITLE
[Belo Horizonte/MG] Front-End Developer na TORO INVESTIMENTOS

### ISSUE THREAD

**Issue by megandavulpi** [frontendbr/vagas#1675]
### Sobre a empresa: Toro Investimentos

A Toro é uma das maiores fintechs de investimento do mundo. Desde 2010, ajudamos mais de 800.000 pessoas a melhorar seus investimentos, nos 27 estados do país. Hoje temos um tráfego de mais de 15 milhões de acessos por ano no nosso site e contamos com um time de mais de 200 funcionários.

### Descrição: O que você irá fazer?

O profissional será responsável pela concepção e desenvolvimento front-end de produtos mobile e desktop, propondo melhorias e participando de maneira colaborativa de todo o ciclo de desenvolvimento do produto visando construir a melhor experiência digital de investimentos do mundo.

### Nossos benefícios:

Além de ter a oportunidade de trabalhar em uma das maiores fintechs de investimentos do mundo, você também irá trabalhar em uma empresa com uma cultura viva e atenta para as questões de diversidade e que valoriza bastante as pessoas que nela trabalham. **Dentre nossos benefícios estão**:

Programas de bonificações anuais;
Vale Transporte com desconto de 3% sobre o salário base;
Vale Refeição/Alimentação: R$ 31,70 reais (22 dias Fixos);
Plano de Saúde sem co-participação;
Plano de odontológico - OdontoPrev: Sem co participação de R$ 13,00 reais mensais;
Convênio farmácia Good Card – É disponibilizado um saldo relativo à 10% do salário bruto e, ao utilizar esse saldo, o valor das compras será descontado na sua folha de pagamento. Além de desconto de até 60% na compra de medicamentos em farmácias credenciadas;
Gympass;

**E você que não é de BH, se interessou por essa oportunidade? Ótimo!**

Temos benefícios especiais para pessoas vindas de outros estados que queiram vir trabalhar conosco :)

### O que você precisa saber/ter?

Conhecimento avançado dos fundamentos da Ciência da Computação, incluindo design orientado a objetos, estruturas de dados, design de algoritmos, resolução de problemas e análise de complexidade;
Conhecimento avançado de trabalho desenvolvendo experiências receptivas para uma variedade de navegadores, sistemas operacionais e tamanhos de tela;
Conhecimento avançado em linguagens como JavaScript (ES6) e Typescript;
Conhecimentos avançados em linguagens como HTML e CSS (SASS);
Conhecimento de testes unitários (teste de códigos)
Experiência com a plataforma RESTFUL API;
Experiência no desenvolvimento de interfaces responsivas;
Desenvolvimento de arquiteturas front-end em grande escala;
Familiaridade com metodologias ágeis, Scrum ou Kanban;
Controle de versão usando Git (versionador de arquivos).
Compreensão avançada de padrões web e melhores práticas, incluindo SEO e acessibilidade;
Compreensão aprofundada de problemas de desenvolvimento de cross-browser e front-end.

### O que você precisa ser?

Entendemos sim a importância da capacidade técnica nas pessoas, porém aqui priorizamos muito o fit cultural com nossa empresa. Para fazer parte do nosso time é preciso que você tenha brilho nos olhos, determinação e vontade de fazer acontecer! Buscamos pessoas que saibam trabalhar em equipe e em um ambiente onde a diversidade esta presente e que também gostem de mover com agilidade e inspirarem pelo exemplo. Estamos crescendo e queremos pessoas queiram crescer ainda mais conosco! 

### Labels:

Alocado
Senior
CLT

### Candidatar: http://bit.ly/toro_github

**Comment by Mendrone** [comment]
@megandavulpi A vaga é CLT ou PJ? Pra nos ajudar, pode atualizar a descrição com essa informação, por favor?

**Comment by megandavulpi** [comment]
> ### Sobre a empresa: Toro Investimentos
> A Toro é uma das maiores fintechs de investimento do mundo. Desde 2010, ajudamos mais de 800.000 pessoas a melhorar seus investimentos, nos 27 estados do país. Hoje temos um tráfego de mais de 15 milhões de acessos por ano no nosso site e contamos com um time de mais de 200 funcionários.
> 
> ### Descrição: O que você irá fazer?
> O profissional será responsável pela concepção e desenvolvimento front-end de produtos mobile e desktop, propondo melhorias e participando de maneira colaborativa de todo o ciclo de desenvolvimento do produto visando construir a melhor experiência digital de investimentos do mundo.
> 
> ### Nossos benefícios:
> Além de ter a oportunidade de trabalhar em uma das maiores fintechs de investimentos do mundo, você também irá trabalhar em uma empresa com uma cultura viva e atenta para as questões de diversidade e que valoriza bastante as pessoas que nela trabalham. **Dentre nossos benefícios estão**:
> 
> Programas de bonificações anuais;
> Vale Transporte com desconto de 3% sobre o salário base;
> Vale Refeição/Alimentação: R$ 31,70 reais (22 dias Fixos);
> Plano de Saúde sem co-participação;
> Plano de odontológico - OdontoPrev: Sem co participação de R$ 13,00 reais mensais;
> Convênio farmácia Good Card – É disponibilizado um saldo relativo à 10% do salário bruto e, ao utilizar esse saldo, o valor das compras será descontado na sua folha de pagamento. Além de desconto de até 60% na compra de medicamentos em farmácias credenciadas;
> Gympass;
> 
> **E você que não é de BH, se interessou por essa oportunidade? Ótimo!**
> 
> Temos benefícios especiais para pessoas vindas de outros estados que queiram vir trabalhar conosco :)
> 
> ### O que você precisa saber/ter?
> Conhecimento avançado dos fundamentos da Ciência da Computação, incluindo design orientado a objetos, estruturas de dados, design de algoritmos, resolução de problemas e análise de complexidade;
> Conhecimento avançado de trabalho desenvolvendo experiências receptivas para uma variedade de navegadores, sistemas operacionais e tamanhos de tela;
> Conhecimento avançado em linguagens como JavaScript (ES6) e Typescript;
> Conhecimentos avançados em linguagens como HTML e CSS (SASS);
> Conhecimento de testes unitários (teste de códigos)
> Experiência com a plataforma RESTFUL API;
> Experiência no desenvolvimento de interfaces responsivas;
> Desenvolvimento de arquiteturas front-end em grande escala;
> Familiaridade com metodologias ágeis, Scrum ou Kanban;
> Controle de versão usando Git (versionador de arquivos).
> Compreensão avançada de padrões web e melhores práticas, incluindo SEO e acessibilidade;
> Compreensão aprofundada de problemas de desenvolvimento de cross-browser e front-end.
> 
> ### O que você precisa ser?
> Entendemos sim a importância da capacidade técnica nas pessoas, porém aqui priorizamos muito o fit cultural com nossa empresa. Para fazer parte do nosso time é preciso que você tenha brilho nos olhos, determinação e vontade de fazer acontecer! Buscamos pessoas que saibam trabalhar em equipe e em um ambiente onde a diversidade esta presente e que também gostem de mover com agilidade e inspirarem pelo exemplo. Estamos crescendo e queremos pessoas queiram crescer ainda mais conosco!
> 
> ### Labels:
> Alocado
> Senior
> 
> Candidatar: http://bit.ly/toro_github

**Comment by megandavulpi** [comment]
> @megandavulpi A vaga é CLT ou PJ? Pra nos ajudar, pode atualizar a descrição com essa informação, por favor?

Done! =)
