### ISSUE TITLE
[Rio de Janeiro/RJ] Estágio em desenvolvimento FullStack na COOBO SPEND MANAGEMENT

### ISSUE THREAD

**Issue by VIMGAS** [frontendbr/vagas#1679]
## Descrição da vaga

Vaga de Estágio em Desenvolvimento FullStack (Back e Front) na COOBO SPEND MANAGEMENT.

## Local

COOBO Spend Management
Escritório na Torre do Rio Sul
Bairro: Botafogo
Cidade: Rio de Janeiro
Modelo de Trabalho: Presencial

## Benefícios

- Bolsa-auxílio
- Benefícios compatíveis com o mercado

#### Diferenciais

- Grande possibilidade de efetivação

## Atividades e competências a serem desenvolvidas

- Participar das reuniões de definição, estruturação e concepção de novos produtos
- Arquitetar e desenvolver aplicações escaláveis
- Implementar interfaces web utilizando React
- Construir RESTful APIs e microservices em Node.js, Python e outras linguagens
- Modelar e gerenciar bancos de dados NoSQL (MongoDB) e SQL (MySQL)
- Atuar no dia a dia utilizando métodos ágeis como Agile e Kanban
- Utilizar Docker e Containers
- Git e Github

## Requisitos

**Obrigatórios:**
- Estar matriculado em um curso técnico ou de graduação em ciência da computação, engenharia de software, sistema de informação, engenharia de produção ou equivalentes, com previsão de formatura a partir de 2020.1
- Conhecimentos básicos de HTML, CSS e Javascript

**Desejáveis:**
- Ser humilde para reconhecer o que não sabe ou o que não consegue fazer
- Ser faminto por coisas novas e ter aptidão para aprendê-las de forma independente
- Pensar fora da caixa
- Proatividade
- Ter foco e energia para fazer acontecer

**Diferenciais:**
- Conhecimento em Node.js
- Conhecimento em Python
- Conhecimento em MongoDB
- Conhecimento em React
- Conhecimento em Docker
- Conhecimento em Github

## Contratação

Contrato de estágio remunerado

## Nossa empresa

[COOBO SPEND MANAGEMENT](https://www.coobo.com.br/)
```
Em função do aumento da importância da gestão de compras de forma mais estratégica e da complexidade que este processo demanda, o fundador Fabiano Coutinho, decidiu, em 2011, criar uma empresa especializada na otimização da gestão dos gastos.​

Em 2013, O BTG Pactual tornou-se investidor da empresa, com o propósito de promover as boas práticas de Compras Colaborativas junto às suas investidas e otimizar a eficiência operacional, buscando maximizar o retorno do seu investimento.
​
Em 2016, Paulo Esteves, ex-VP Global Procurement da Anheuser-Busch InBev (Leuven, Belgium e New York, USA), adquire a participação do BTG Pactual na COOBO.

Durante 16 anos, Paulo liderou as atividades de Procurement no Grupo AmBev, participando da implementação da integração de M&A da AmBev (1999), InBev (2004) e AB-InBev (2008). Recentemente como consultor da 3G-Capital, Paulo trabalhou no projeto de Procurement Transformation na H.J.Heinz Company.

Nossa atuação está voltada para uma gestão ágil, colaborativa, tecnológica e inovadora para a área de compras, buscando adaptar novos conceitos de mercado às necessidades que identificamos em nossos clientes.

Reduzir custos é vital!

Fabiano Coutinho
CEO e  Sócio fundador.
```

## Como se candidatar

Por favor envie um email para luana.mendonca@coobo.com.br com seu CV anexado - enviar no assunto: Vaga Estágio de TI

## Labels

- Alocado
- Estágio
- Rio de Janeiro

**Comment by VIMGAS** [comment]
Ainda estamos procurando candidatos para esta vaga.

**Comment by developer-sp** [comment]
Acho dificil de conseguir um fullstack pra estagiar alocado, geralmente eles possuem grande experiencia, e tem o melhor salário, as vezes é melhor dar uma pesquisada o que é um fullstack, ou como se tornar um fullstack, antes de oferecer uma bolsa auxílio ou estágio remunerado.

**Comment by VIMGAS** [comment]
@delevoper-sp eu sou um desenvolvedor fullstack... A intenção dessa vaga de estágio é desenvolver alguém com pouca experiência e conhecimento para ser um desenvolvedor fullstack no período de 1 a 2 anos.

Por isso que os requisitos obrigatórios para a vaga são somente o básico do básico.

**Comment by developer-sp** [comment]
Ok, boa sorte!!!

**Comment by raphaelanjos1** [comment]
Oi @VIMGAS, bom dia. Encaminhei um e-mail para luana.mendonca@coobo.com.br no dia 11/01 com meu CV anexado. Mas não obtive nenhum tipo de retorno até o momento, seja ele positivo ou negativo.

**Comment by VIMGAS** [comment]
@raphaelanjos1 e @lfgtavora obrigado por terem enviado seus cvs! Infelizmente não sou eu o responsável pela seleção, estou apenas ajudando a empresa a divulgar a vaga.

Mas acredito que ainda estejam reunindo os currículos e que não tenham começado a filtrar os candidatos!
