### ISSUE TITLE
[Remoto || Rio de Janeiro] Desenvolvedor JavaScript para editor de texto do Blogo

### ISSUE THREAD

**Issue by reprotector** [frontendbr/vagas#168]
### Você irá trabalhar no coração do produto: O Editor de texto

O Editor de texto é a parte mais importante do Blogo. O desafio é grande: nosso editor de texto é universal e compatível com nossas versões macOS, iPhone e iPad e pensados para suportar Android e Windows no futuro.

Nosso editor suporta edição em Markdown e Rich Text, além de receber e converter conteúdo das platformas WordPress, Blogger e Medium. Você irá trabalhar diretamente com content-editable, manipulação de DOM, Selection API e Range API.

### O que você irá aprender?

- Você irá trabalhar com um time que utiliza as melhores práticas, as melhores ferramentas e que entrega o que existe de mais novo em tecnologia
- Você participará de reuniões com a Apple, Evernote, Ghost, Digital Ocean, GettyImages e dezenas de outras grandes empresas que são parceiras e acreditam no Blogo  
- Você irá aprender muito sobre a criação de um produto B2C global
- Você fará parte de um projeto de impacto real

### Qual perfil estamos procurando?

Procuramos pessoas que acreditem na cultura startup, em foco no produto e que pensem grande. Valorizamos profissionais que lidem bem com pessoas, que tenham habilidade emocional e que tragam energia positiva para o nosso ambiente.

Valorizamos mais o lado humano e a capacidade de resolver problemas do que conhecimento técnico específico.

## Aonde você irá trabalhar?

De qualquer lugar. Nosso HQ fica no Rio de Janeiro mas acreditamos em times remotos e em qualidade de vida. Gostamos de marcar encontros do time para renovar as energias e visão. :)

## Requisitos

**O que esperamos:**
- 2+ anos de experiência profissional em desenvolvimento JavasScript.
- Git
- Fluência em inglês. Toda a equipe lida diretamente com nossos usuários.

**Experiências recomendadas:**
- Content-editable e manipulação do DOM
- Node.js
- SASS
- Webpack
- Ecmascript 6

**Bonus:**
- Ruby on Rails
- DevOps
- Deploy em AWS
- Gostar de escrever e ter publicado posts
- Já ter trabalhado em alguma startup 

## Contratação

PJ a combinar

## Nossa empresa

**Blogo é uma forma simples e completa de escrever e gerenciar seus blogs.**

**Temos orgulho de ser uma startup brasileira que conquistou o mundo. Nosso produto é usado por milhares de usuários em mais de 90 países.**

Fomos destaque mundial nas App Stores mais de 5 vezes e eleito como uma das melhores startups de 2014 pelo Evernote Platform Awards lá no Vale do Silício. Blogo é o primeiro aplicativo e a primeira startup Brasileira a conseguir ficar em destaque mundial na Mac App Store e na App Store ao mesmo tempo.

Ajudamos milhares de produtores de conteúdo ao redor do mundo a publicarem suas histórias, tornando o processo de escrever mais agradável e intuitivo.

## Com quem você irá trabalhar?

Você irá trabalhar com um time de fundadores com bagagem de sucesso, que já criarem e venderam empresas no passado e com visão de sucesso global.

**Amure Pinho** é CEO do Blogo e Presidente da ABStartups. Como investidor anjo, vendeu uma de suas empresas para o grupo B2W, dona das marcas Americanas e Submarino. Criou o 1o Startup Weekend em uma favela no mundo, foi curador da Campus Party e é mentor em programas de aceleração como Wayra, Startup Farm e Founders Institute Chile. Palestrante em eventos no Brasil e no Mundo como SXSW, TechCrunch e Global Technology Symposium.
 
**Renan Protector** é CTO do Blogo. Desenvolvedor com larga experiência em ambiente mobile e back-end. Responsável pelo desenvolvimento de projetos de sucesso para empresas como Globo, Estadão, Ingresso.com, Bohemia e Governo Federal. Participa ativamente das comunidade de desenvolvedores além de ser palestrante em eventos como Campus Party, Cocoa Heads e DevBeer. 
 
**Ivan Neto** é o CPO do Blogo. Foi o criador da primeira versão do Blogo em 2008. Premiado diretor de arte, é especialista em design de interfaces com forte background em criação de produtos. Foi o criador da primeira empresa de desenvolvimento mobile do Brasil, a Brainjuice, onde obteve destaque pela Apple, Mashable, MacBreak Weekly e Macworld, entre outros.

**Paulo Cesar** é desenvolvedor iOS e macOS do Blogo. Tem perfil misto, com graduação em Ciência da Computação e especialização em Design de Interação. Possui ampla experiência em mobile e web, focando sempre no desenvolvimento de interfaces. Também já atuou como designer de interação para o C.E.S.A.R. e criou um dos aplicativos mais baixados da App Store brasileira, o Lumiè.

**Haruan Justino** é desenvolvedor iOS do Blogo. Com ampla experiência em desenvolvimento para iOS e Android. Já ministrou diversos cursos de desenvolvimento iOS e está sempre em busca de compartilhar seu conhecimento.

## Como se candidatar

Estamos utilizando o StackOverflow para nossa vaga, basta acessar o link e se candidatar: http://stackoverflow.com/jobs/128542/desenvolvedor-javascript-blogo

**Comment by LFeh** [comment]
Show heim!

**Comment by lucasalmeida92** [comment]
Enviado! ;]

**Comment by LFeh** [comment]
@reprotector Fechou a vaga? :)

**Comment by reprotector** [comment]
Sim, fechada! @LFeh

**Comment by LFeh** [comment]
Foi com alguem daqui? o/

**Comment by reprotector** [comment]
@LFeh SIM! :)
