### ISSUE TITLE
[REMOTO] VUEjs 2019 FontEnd 

### ISSUE THREAD

**Issue by tuliovargas** [frontendbr/vagas#1683]
## Descrição da vaga
Buscamos desenvolvedor front-end com experiência em VueJs.

**Comment by vcpablo** [comment]
Enviado

**Comment by alessandroprudencio** [comment]
@vcpablo e @IgorVieira mano não entra nessa...

**Comment by alessandroprudencio** [comment]
olha só quantas vezes anunciaram a mesma vaga... [https://github.com/frontendbr/vagas/issues?utf8=%E2%9C%93&q=voceazul](url) ninguém aguenta ficar la...

**Comment by alessandroprudencio** [comment]
Olha só esse link guando comentei para vocês https://uploaddeimagens.com.br/imagens/antes-jpg-4f621312-dc6d-4189-8728-2aec13c0baca
agora veja depois que eles viram meu comentario...
https://uploaddeimagens.com.br/imagens/depois-jpg-6898b050-fba5-49c7-8ae2-4e722f2e610f

**Comment by IgorVieira** [comment]
@Mendrone você pode intermediar aqui? É que a vaga não contém mais a descrição e está havendo uma certa divergência entre as partes.

**Comment by ednilsonamaral** [comment]
@LFeh, você pode intermediar também? Eu também já trabalhei nesse projeto, e, é realmente isso que o @alessandroprudencio citou acima que aconteceu conosco.

**Comment by alessandroprudencio** [comment]
> @LFeh, você pode intermediar também? Eu também já trabalhei nesse projeto, e, é realmente isso que o @alessandroprudencio citou acima que aconteceu conosco.

Mais um enganado...

**Comment by LFeh** [comment]
Complicado heim?

E está totalmente fora do template. 

Vou deixar fechado e acompanhar :)
