### ISSUE TITLE
[Sao Paulo] Front-end Developer - Próximo a Berrini @Colmeia

### ISSUE THREAD

**Issue by josecaodaglio** [frontendbr/vagas#1685]
## Local

Presencial, escritório, São Paulo - Brooklin

#### Diferenciais

- Startup já com rodada de investimentos realizados
- Expansão da equipe para atender contratos, em execução piloto.
- Nossa plataforma é mágica, nosso stack moderno (Angular, node com Typescript, Redis, rabbitmq, google datastore, cloudstorage, bigquery e cloud SQL)
- Ambiente Colaborativo

## Requisitos

**Obrigatórios:**
- Lógica apurada, algoritmos, programação funcional
- Javascript ES6+, Promise, async, await
- CSS3 e HTML5 

**Desejáveis:**
- experiência em SPA, Service Workers e PWA
- algum framework JS, preferencialmente Angular
- SASS (ou outro pré-compilador de css)

**Diferenciais:**
- Typescript

## Contratação

PJ a combinar

## Nossa empresa

- Startup já com rodada de investimentos realizados
- Expansão da equipe para atender contratos, em execução piloto.
- Nossa plataforma é mágica, nosso stack moderno (Angular, node com Typescript, Redis, rabbitmq, google datastore, cloudstorage, bigquery e cloud SQL)
- Ambiente Colaborativo

## Como se candidatar

Por favor envie um email para jose.caodaglio@colmeia.me com seu CV anexado - enviar no assunto: Vaga front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dias após cada processo.
E-mail para contato em caso de não haver resposta: jose.caodaglio@colmeia.me

## Labels

- Alocado
- PJ
- Pleno
- Sênior

**Comment by ReactGirl** [comment]
Promise, async, await

**Comment by StdInOut** [comment]
> Promise, async, await

Olá, sim faz parte do skill
