### ISSUE TITLE
[São Paulo] Front-End Developer na Turbi

### ISSUE THREAD

**Issue by marciopedrozo** [frontendbr/vagas#1686]
## Descrição da vaga

Buscamos desenvolvedor em Angular, JavaScript, HTML5 e CSS3.

## Local

Remoto/Rua Lisboa, 890, São Paulo - Pinheiros

## Nossa empresa

Turbi é uma empresa de tecnologia com produto de car sharing, com experiência inovadora, tecnologias novas e ambiente de startup.
www.turbi.com.br

## Como se candidatar

Envie e-mail para hiring.it@turbi.com.br
Assunto: [Vaga Front-end] Seu nome

Detalhe no texto do e-mail

Sua experiência (projetos, atuação e tempo) em :
HTML
CSS
JS
Angular

detalhe outros conhecimentos relacionados que tenha (NodeJS, Express, React, Vue....)

Valor hora
Linkedind
Seu portfólio (GIT/GITLAB/Bitbucket)

Contatos
(email, telefone/whatsapp)

Anexar CV

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias

## Labels

- Júnior
- PJ
- Pleno
- Remoto
- Freela
- Alocado

**Comment by danielswater** [comment]
Enviado

**Comment by felipebazza** [comment]
Enviado! o/

**Comment by desenvolvedorIcotrade** [comment]
up!

**Comment by victorvinci** [comment]
A vaga está aberta ainda? Já enviei o email, mas não tive nenhum retorno.
