### ISSUE TITLE
[Porto Alegre] - Fullstack developer na PLING

### ISSUE THREAD

**Issue by felipekm** [frontendbr/vagas#1688]
A [PLING](https://pling.net.br/) é uma startup focada em desenvolver produtos digitais para mercados específicos e em renovar e/ou desenvolver identidades visuais, agrupando últimas tendências de tecnologia e design.

## Descrição da vaga

Vaga para Fullstack developer com atuação em diversos projetos que utilizam diversas tecnologias, tais como:

* Go Microservices
* NodeJS
* AWS Services
* MongoDB
* PWA
* ReactJS
* Docker
* Elasticsearch
* Redis
* Git/Github

## Benefícios

- Jornada flexível;
- Plano de saúde (médico e odontológico);
- VR de R$ 23,00/dia;
- VA de R$ 150,00/mês;
- Day off no dia do aniversário do profissional;

## Requisitos

**Obrigatórios:**

- Experiência em HTML, CSS e JavaScript;
- Mínimo de 3 anos de experiência com desenvolvimento de softwares;
- Experiência com algum framework javascript como: `ReactJS, AngularJS, VueJS`;
- Experiência com arquitetura e modularização de sistemas;

**Requisitos desejáveis:**

- Conhecimento de REST APIs utilizando NodeJS;
- Conhecimentos em MongoDB, Redis, RabbitMQ, Elasticsearch;
- Conhecimento em Linux/MacOSX;

## Contratação

- CLT;
- PJ;

#### Mercados em que a PLING atua:

* [Psicologia](https://psicologia.pling.net.br)
* [Medicina](https://medicina.pling.net.br)
* [Nutrição](https://nutricao.pling.net.br)
* [Arquitetura](https://arquitetura.pling.net.br)
* [Odontologia](https://odontologia.pling.net.br)
* [Contabilidade](https://contabilidade.pling.net.br)
* [PRONID - Programa nacional de inclusão digital](https://pronid.pling.net.br)

Todas essas aplicações acima foram desenvolvidas com ReactJS e NextJS, venha se divertir conosco!

## Como se candidatar

**Envie um email para**: recrutamento@pling.net.br com seu CV anexado.
**Enviar no assunto**: Vaga Fullstack.

⚠️ **É importante o profissional residir próximo a Porto Alegre/RS ou arredores pois as primeiras entrevistas são presenciais!** ⚠️ 

⚠️ **É importante o profissional possuir equipamento próprio para desempenhar suas funções, mas caso não haja fornecemos equipamento!** ⚠️ 

Tempo de resposta: `48h`

## Labels

- CLT / PJ
- Home office full
- Pleno
- Sênior

**Comment by Mendrone** [comment]
@felipekm A vaga é remota ou presencial? Pelos labels achei que era remota mas na descrição me pareceu presencial
