### ISSUE TITLE
[Remoto] Desenvolvedor Front-End Pleno/Sênior

### ISSUE THREAD

**Issue by daniellins** [frontendbr/vagas#169]
## Descrição da vaga

Buscamos desenvolvedor front-end para contribuir na criação de ferramentas computacionais para a Web. Você irá trabalhar em projetos com foco na gestão de dados científicos, em áreas como biologia, oceonografia e ecologia. 

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência em desenvolvimento Javascript
- Experiência com HTML5/CSS3
- Ferramentas de automação de tarefas (Gulp, Grunt, ...)
- Consumo de REST APIs
- GIT

**Desejáveis:**
- Experiência em frameworks JS (AngularJs, ReactJs, ...)
- Conhecimento de bibliotecas JS de mapas (Leaflet, OpenLayers, ...) e gráficos (D3, GoogleCharts, ...)	

## Contratação

PJ a combinar.

## Nossa empresa

A SkyMarket é uma empresa de soluções para a gestão de dados científicos, sua qualificação e análise para diferentes processos de tomada de decisão. Com mais de 10 anos de atuação, é a primeira empresa brasileira especializada em informática para biodiversidade. 

## Como se candidatar

Por favor envie um email para contato@skymarket.com.br com seu currículo, portfólio e pretensão salarial. Enviar no assunto: Vaga Front-End Developer.

**Comment by donnes** [comment]
Enviado :D

**Comment by JoaoAntonioMaruti** [comment]
Enviado

**Comment by daniellins** [comment]
Obrigado @donnes e @JoaoAntonioMaruti.

**Comment by renatorib** [comment]
Enviado :tada:

**Comment by andrebrandaoo** [comment]
Enviado

**Comment by alsfurlan** [comment]
@daniellins ainda precisando?

**Comment by uselessdev** [comment]
faço da pergunta do @alsfurlan a minha :smile:

**Comment by TiagoSilvaPereira** [comment]
+1 a vaga ainda está em aberto?
