### ISSUE TITLE
[São Paulo] Front-End Developer no CEPID NeuroMat (R$ 7.372,40)

### ISSUE THREAD

**Issue by carlosribas** [frontendbr/vagas#1690]
## Descrição da vaga

Buscamos uma pessoa para trabalhar com o desenvolvimento de novas interfaces, criação de identidade visual e manutenção de sites e sistemas (web e mobile).

## Local

Instituto de Matemática e Estatística da USP, Cidade Universitária, São Paulo.

#### Diferenciais

- Horário flexível
- Frequentar aulas e palestras do IME-USP 

## Requisitos

**Obrigatórios:**
- Título de doutorado **OU** 5 anos de experiência após a graduação em qualquer área da TI (exigência da FAPESP - http://www.fapesp.br/3098).
- HTML, CSS, JS

**Desejáveis:**
- Bootstrap, fundamentos de usabilidade e design de interfaces, ferramentas de edição de imagens (GIMP, Photoshop) e Git
- Conhecimentos em Python/Django

**Diferenciais:**
- projetos opensource

## Contratação

Bolsa TT5 da FAPESP no valor de R$ 7.372,40 (http://www.fapesp.br/3162), para uma dedicação de 40 horas semanais.

## Nosso projeto

O CEPID NeuroMat, financiado pela FAPESP e sediado na USP, tem como objetivo integrar modelagem matemática e computacional com pesquisa básica e aplicada na fronteira da neurociência.

## Como se candidatar

Por favor envie um email para vagas-ti@numec.prp.usp.br com seu CV anexado - enviar no assunto: Vaga Front-End

## Labels

- Alocado
- Pleno
- Sênior

**Comment by ReactGirl** [comment]
Doutorado pra HTML, CSS, JS. Tendi.

**Comment by carlosribas** [comment]
> Doutorado pra HTML, CSS, JS. Tendi.

Sinto muito, são regras que devo seguir. Suponho que você tenha visto aquele "ou" no requisito...

**Comment by rlage** [comment]
http://www.fapesp.br/3096

**Comment by carlosribas** [comment]
> http://www.fapesp.br/3096

Aproveito para informar que as pessoas que se encaixam em outros tipos de bolsa TT também podem se candidatar. Contudo, nas demais bolsas o salário é menor (http://www.fapesp.br/3162).

**Comment by greevin** [comment]
Existe a possibilidade de remoto? Atualmente estou morando em Campinas.

**Comment by carlosribas** [comment]
> Existe a possibilidade de remoto? Atualmente estou morando em Campinas.

Olá. Isso facilitaria um pouco minha vida, mas infelizmente não é possível. Abraço.

**Comment by carlosribas** [comment]
Vaga preenchida. A pessoa selecionada encontrou a vaga por meio deste grupo. Obrigado!

**Comment by LFeh** [comment]
Fantastico!
