### ISSUE TITLE
[Curitiba-PR] Front-End Developer na Commcepta

### ISSUE THREAD

**Issue by commcepta** [frontendbr/vagas#1691]
## Descrição da vaga

Estamos buscando um desenvolvedor web, que além de ser agilizad@, goste de trabalhar em equipe e tope encarar um desafio por dia. Esteja disposto a estar sempre se atualizando, afinal a tecnologia está em constante mudança. Se tiver uma base de inglês, melhor ainda.

Qual o desafio que propomos? 
- Enfrentar códigos "cabeludos" e transformar em códigos perfeitos 
- Não vai deixar escapar um ponto e vírgula além de manter o padrão de indentação 
- Ser minucioso com os detalhes 
- Compartilhar conhecimentos com a equipe 
- Estar sempre em busca de novos desafios e tecnologias

## Local

Escritório, Curitiba - Centro

## Benefícios

- VR de R$ 17,50/dia

#### Diferenciais

- Empresa com premiação internacional
- Equipe de talentos
- Investimento em cursos
- Sexta-feira traga sua cerveja :) 

## Requisitos

**Obrigatórios:**

- Experiência com HTML5, CSS3 (Sass), fluência com frameworks de Front-end (AngularJS, Vue.js ou ReactJS)
- Customização em WordPress
- Ter fluência em convenções e padrões de experiência de usuário (UX), responsive design
- Ter inglês intermediário
- Ambiente MacOS
- Conhecimento em terminal (bash) e git

**Desejáveis:**
- Conhecimentos em React Native

## Contratação

CLT

## Nossa empresa

Desde 2000, desenvolvemos projetos locais e globais, como: sites, intranets, aplicativos, dashboards e protótipos digitais com soluções de inteligência de design que proporcionam autenticidade e excelência. Estamos continuamente aprimorando nossas metodologias e processos para apoiar o crescimento dos nossos clientes e do nosso time.

## Como se candidatar

Por favor envie um email para vagas@commcepta.com.br com seu CV anexado - enviar no assunto: Vaga Front-End Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: vagas@commcepta.com.br

## Labels

- CLT 
- PJ
- Presencial
- Pleno
- Sênior

**Comment by ivosoares** [comment]
enviado
