### ISSUE TITLE
[Florianópólis] Front-End Developer na SumOne

### ISSUE THREAD

**Issue by LuisSola** [frontendbr/vagas#1692]
## Descrição da vaga

Como estagiário de desenvolvimento você fará parte da nosso time de Produto e será responsável por construir soluções que irão revolucionar negócios com presença local. Estamos em busca de um profissional apaixonado por desenvolvimento de software e que tenha grandes aspirações em se tornar cada vez melhor no que faz, e melhor que isso, que não apenas queira, mas que esteja disposto a se manter em constante estado de aprendizado e adaptação.

Nosso blog técnico: https://tech.sumone.com.br/

## Local

Avenida Madre Benvenuta 1313

## Benefícios

Bolsa de R$ 1.400,00;

Auxílio alimentação de R$ 150,00;

Auxílio transporte de R$ 100,00;

Autonomia e flexibilidade;

Ambiente de trabalho descontraído e divertido;

No dress code;

Muitos desafios e aprendizados;

Time fera e super disposto a ajudar sempre!

## Requisitos

**Obrigatórios:**
Estar cursando Sistemas da Informação, Ciências da Computação ou cursos afins;

Ter interesse pela área de desenvolvimento de aplicações web.

Ser proativo e ter vontade de aprender;

Ser atento aos detalhes e focado na qualidade;

Ter disponibilidade para estagiar 30 horas semanais.

**Desejáveis:**
Ter tido algum contato com Ruby e/ou Javascript, de preferência utilizando algum framework (ex: React, Angular).

## Nossa empresa

Estamos crescendo rápido e em busca de mais um SumOner para o nosso time!

Ser um SumOner é estar em constante busca pela melhor versão de você mesmos. É crescer pensando do avesso, é desafiar limites e não se contentar em fazer como sempre se fez. Por aqui, crescer é um verbo no coletivo, aprendendo e dividindo sempre, cada SumOner melhorando o outro. 

Nosso sonho é ser líder mundial em soluções tecnológicas para os negócios locais, estamos levando as melhores tecnologias de marketing do mundo digital para o mundo físico.

## Como se candidatar
Achou essa oportunidade a sua cara? Então se candidata, estamos ansiosos para conhecer você!
https://jobs.kenoby.com/sumone/job/desenvolvedor-fullstack-estagio/5c33531687657b5ac164e273

**Comment by LuanCassiano** [comment]
Uma pena não ser remoto rs
