### ISSUE TITLE
[Rio Grande do Sul - São Leopoldo] Software Engineer na [Wedy]

### ISSUE THREAD

**Issue by danieltamiosso** [frontendbr/vagas#1695]
## Descrição da vaga

Procuramos uma pessoa talentosa e com potencial - que seja apaixonada por criar experiências memoráveis aos clientes através de uma contínua entrega de valor. Tenha disposição para construir uma nova cultura dentro de uma startup e se tornar uma liderança. Buscamos paixão por aprender acima de conhecimento "consolidado".

## Local

Escritório, São Leopoldo (Unisinos)

## Benefícios

- Alimentação/transporte/convênio médico sem descontos
- Pacote de remuneração competitivo
- 30 dias de férias (PJ)
- Day-off no aniversário
- Sem "horas extras"

#### Diferenciais

- Participações em eventos e incentivos financeiros a leitura e desenvolvimento pessoal
- Snacks
- Games, roda de violão, massagens, biblioteca e filmes
- WedyTalks
- Ambiente divertido, colaborativo e rápido - com uma equipe de pessoas inteligentes e ambiciosas
- Oportunidade de crescimento rápido
- Confiança e liberdade
- Sessões de shiatsu

## Requisitos

**Desejáveis:**
- +2 anos de experiência em Ruby ou Node,js
- Conhecimentos específicos em Vue.js
- Escrever código limpo e legível para pessoas
- Princípios SOLID
- Conhecimentos de práticas de XP (TDD , pair programming, refactoring, continuous integration, etc)
- Conhecimentos de testes unitários, aceitação, mocks, etc
- Conhecimentos em Cloud Computing
- Experiência integrando com 3rd party APIs
- Princípios de design orientado a objetos
- HTML5/CSS3
- Domínio de bancos de dados relacionais (Postgres, MySQL, etc) e familiaridade com noSQL databases (Redis, Elastic, etc.)

## Contratação
PJ a combinar

## Nossa empresa

A plataforma digital Wedy é composta por diversos micro-serviços, envolvendo tecnologias on the edge de desenvolvimento web e mobile, algoritmos e soluções de Inteligência Artificial e Aprendizado de Máquina. Com um roadmap de produto ambicioso e uma cultura ágil a equipe de engenharia é peça-chave para a entrega contínua de valor à milhões de pessoas impactadas anualmente pela Wedy.

Por que você deveria conhecer e fazer parte da Wedy? Esta é uma oportunidade que envolverá acima de tudo aprendizado e o desafio de consolidar e evoluir uma plataforma que cresce dia-a-dia. Você como engenheiro de software, encontrará um ambiente de muitos desafios e oportunidades, espaço de muita criatividade e pró-atividade. E a oportunidade de escalarmos juntos um negócio visionário.

Trabalhe em pequenos squads, realizando tomadas de decisões rápidas e criando novos produtos de alto-impacto. Tenha oportunidade de trabalhar em outras funções, de design, growth, negócios e ciência de dados.

Faça parte de um ambiente informal, orientado a resultados e com uma hierarquia horizontal

## Como se candidatar

Por favor envie um email para daniel@wedy.com com seu CV/Linkedin - enviar no assunto: Vaga Software Engineer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 uma semana após cada processo.
E-mail para contato em caso de não haver resposta: daniel@wedy.com

## Labels

- alocação/Presencial
- experiência/Júnior
- experiência/Pleno
- regime/PJ

**Comment by ReactGirl** [comment]
Sem horas extras...
PJ...

**Comment by ReactGirl** [comment]
Beneficios:
Sem horas extras

Ai depois:
Contratacao: 
PJ.

Ah ta.
