### ISSUE TITLE
[São Paulo] Front- End Developer MJV

### ISSUE THREAD

**Issue by leticiapaivamjv** [frontendbr/vagas#1696]
## Descrição da vaga

MJV procura um candidato colaborativo, adaptável, flexível, resolutivo, proativo, resiliente e que tem um relacionamento interpessoal.
O papel de um Desenvolvedor na MJV exige um bom senso de urgência e flexibilidade para trabalhar com diversas tecnologias.
Valorizamos mentes novas, otimistas e com “garra”.
 Somos uma empresa global estabelecida com a atitude local de start up.

## Local

São Paulo - SP

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de 23,89
- Auxílio creche
- Assistência Odontológica
- VT/Fretado

## Requisitos

**Obrigatórios:**
- Experiência  com Angular 2+
- Noções de SPA( Single Page Aplication)
- Git

**Diferenciais:**
- Controle de versão 
- Conhecimento em Devops

## Contratação

CLT Full

## Nossa empresa
Somos uma consultoria global em inovação e tecnologia. 
Unimos a tecnologia aos nossos conhecimentos em Design Thinking, Gamificação, Big Data/Analytics, Metodologia Lean e Estratégia Digital para levar ao mercado soluções inovadoras em produtos e serviços, acreditamos que pessoas transformam negócios.

## Como se candidatar

Por favor envie um email para leticia.paiva@mjv.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

## Labels

- Alocado
- CLT
- Júnior
- Pleno
- Sênior
- Angular
- React

**Comment by antoniotex** [comment]
Enviado!
