### ISSUE TITLE
[São Paulo] Desenvolvedor Pleno/Sênior Ruby on Rails na One Choice Consulting

### ISSUE THREAD

**Issue by MatheusOneChoice** [frontendbr/vagas#1698]
Estamos procurando um Desenvolvedor Ruby on Rails (Pleno)

Requisito:

3 anos de experiência com Ruby.

Diferencial:

Experiência com Java.

Local: Região da Vila Olímpia / Vila Nova conceição.

Regime de contratação: CLT + Benefícios.

Interessados por gentileza encaminhar o currículo para matheuspaiva@onechoice.com.br

**Comment by Mendrone** [comment]
@MatheusOneChoice Vagas para backend sugiro que você poste no Back-endBR https://github.com/backend-br/vagas
