### ISSUE TITLE
DESENVOLVEDOR(A) DE SISTEMAS FULL STACK

### ISSUE THREAD

**Issue by leandrodasler** [frontendbr/vagas#1699]
## Descrição da empresa

A Forma Turismo é a maior empresa de turismo especializada em viagens de formatura do Brasil. Com 21 anos de experiência e mais de 20 destinos.

## Local

Moema, São Paulo - Vila Olímpia

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ 30/dia

#### Atividades e Responsabilidades

-DESENVOLVER NOVOS SISTEMAS A PARTIR DA NOVA PLATAFORMA DE DESENVOLVIMENTO, EFETUAR CORREÇÕES NO SISTEMA LEGADO, PARTICIPAR DE REUNIÕES DE PLANEJAMENTO DE SPRINTS SCRUM, AVALIAR PEDIDOS DE CORREÇÕES, RISCOS E IMPACTOS.

- Desenvolver novos sistemas a partir da nova plataforma de desenvolvimento 
- Efetuar correções no sistema legado 
- Participar de reuniões de planejamento de Sprints Scrum 
- Avaliar pedidos de correções, riscos e impactos 
- Sugerir melhorias que promovam a estabilidade, segurança e facilidade de manutenção 
- Trabalhar em coisas para sentir orgulho em contar para os amigos que foi você quem fez

## Requisitos

SER CAPAZ DE CODIFICAR SEGUINDO O PADRÃO DE DESENVOLVIMENTO DEFINIDO PELA IMPLEMENTAÇÃO DE REFERÊNCIA, DISPOSIÇÃO PARA CODIFICAÇÃO DE TESTES UNITÁRIOS, SUGERIR MELHORIAS QUE PROMOVAM A ESTABILIDADE, SEGURANÇA E FACILIDADE DE MANUTENÇÃO.

**Obrigatórios:**
- Experiência prévia com subversion ou git
- Experiência prévia com angularjs
- Experiência prévia com node.js
- Noções básicas de sql

**Desejáveis:**
- Capacidade de codificar seguindo o padrão de desenvolvimento definido pela implementação de referência
- Disposição para codificação de testes unitários
- Experiência prévia com hapi ou express

## Contratação

CLT FULL

## Como se candidatar

Por favor envie um email para leandro@formaturismo.com.br com seu CV anexado - enviar no assunto: Vaga NodeJS

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 01 dias após cada processo.

**Comment by LFeh** [comment]
@leandrodasler Altera o titulo para seguir o padrão do repositório :)
