### ISSUE TITLE
[Curitiba] Desenvolvedor Front-end Fulltime

### ISSUE THREAD

**Issue by nerijunior** [frontendbr/vagas#17]
## Descrição da vaga

O dev vai trabalhar tanto em sistemas legados quanto em novos projetos.
**Não vai virar noites trabalhando, nem ficar fazendo banco de horas!**
O ambiente é bacana, somos quase uma família, mas nosso trabalho é nosso trabalho, não nossa casa.

## Local

Nossa empresa fica em Curitiba - PR no Uberaba

## Benefícios

- Vale refeição/alimentação
- Vale Transporte
- Plano de saúde
- Horário flexível ( 8 horas entre as 08:00 e 18:30 )

## Requisitos

**Obrigatórios:**
- HTML - Saber diferenciar `<span>` de `<div>`
- CSS ( LESS ou SCSS )
- AngularJS
- Git
- Entender que Javascript não é jQuery!
- Usar o terminal

**Desejáveis:**
- Básico de NodeJs
- Básico de PHP ( provavelmente terá um pouco de código no meio )
- Não gostar de trabalhar no Windows

**Diferenciais:**
- Participar de alguma comunidade ( Angular Brasil, BrazilJS, Laravel Brasil, etc)
- Participar de projetos open source

## Contratação

CLT ou PJ, a combinar

## Nossa empresa

A LS Technologies é uma empresa especializada em sistemas para gestão comercial, temos outro setor que trabalha com web, criamos e-commerces integrados com o nosso ERP, possuímos outros sistemas customizados feitos em PHP, Angular, Node.js, etc.

## Como se candidatar

Enviar e-mail para `neri@lstech.com.br` com seu CV anexado e pretensão salarial - enviar no assunto: Vaga Dev Front-end

**Comment by LFeh** [comment]
Bem legal heim

-------
**Desejáveis:**

- Não gostar de trabalhar no Windows

------

Porra, eu gosto =(, haha

**Comment by ribeiroevandro** [comment]
Curti essa de não trabalhar no Windows, embora com Vagrant hoje até daria para trabalhar com ele, pena que é alocado

**Comment by urameshibr** [comment]
Teria vaga para estagiário e home office? Não sou bom em criar mas tendo layout pronto em PSD eu monto o site bem certinho...

**Comment by danguilherme** [comment]
> Não gostar de trabalhar no Windows

Produtividade 1000 com Windows :(

**Comment by ribeiroevandro** [comment]
@danguilherme o problema nele começa por não ter um terminal nativo e decente, mas da pra contornar isso de boa...

**Comment by nerijunior** [comment]
@ribeiroevandro @danguilherme O atributo está em Desejáveis, mas não somos preconceituosos, fiquem em paz e mandem o CV.

@urameshibr mande teu CV que eu dou uma analisada.

**Comment by ribeiroevandro** [comment]
Eu não tenho preconceito @nerijunior, só não uso mais vai fazer 5 anos :P mas não tenho como ir para Curitiba agora, mas boa sorte na busca por um profissional

**Comment by urameshibr** [comment]
@nerijunior Desculpe a demora, as notificações do github estavam desativadas no gmail, enviei o currículo para o seu email.

**Comment by gsantiago** [comment]
A vaga é massa mesmo.
Mas qual o endereço da empresa?

**Comment by rkb81** [comment]
A vaga achei legal, pena ainda não poder me arriscar no Angular e nada que envolva muita lógica rs.
@gsantiago segue o endereço: Rua Arthur Staude 189. Uberaba - CURITIBA - PR-  81550190, fica depois da Coca-cola.

Eu morei no Jardim das Américas, seria show poder ir de bike se a vaga fosse em 1999 rs.

**Comment by nerijunior** [comment]
Estamos recebendo CVs ainda, vamos entrar em contato com todos ainda essa semana com uma resposta para entrevista, lembrando que a vaga é para alocados, infelizmente ainda não temos oportunidades para Home-office, mas agradeço o interesse de todos, seus CVs ficarão guardados caso essa oportunidade apareça.

**Comment by nerijunior** [comment]
Todos os candidatos receberam algum tipo de resposta, ainda estamos analisando.

PS: Informo que não temos vaga para o setor de RH, mas agradeço os CVs enviados. ;)

**Comment by herus02** [comment]
Pode mandar ainda?

**Comment by LFeh** [comment]
> PS: Informo que não temos vaga para o setor de RH, mas agradeço os CVs enviados. ;)

Como assim @nerijunior ? huahaha

**Comment by nerijunior** [comment]
@herus02 te respondi lá! 

@LFeh recebi diversos CVs pra trabalhar no RH :smiley:

**Comment by LFeh** [comment]
@nerijunior Carario, ri pra carario agora, que loucura é essa? hahaha

**Comment by gsantiago** [comment]
@nerijunior a vaga ainda está aberta?

**Comment by LFeh** [comment]
A vaga foi preenchida? @nerijunior

**Comment by nerijunior** [comment]
@LFeh já foi sim!

**Comment by camilatigre** [comment]
@nerijunior 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

**A pessoa que preencheu a vaga foi encontrada através desta issue?**
a) Sim
b) Não
c) Não tenho certeza
