### ISSUE TITLE
[NOVO HAMBURGO/RS] Desenvolvedor Front-end

### ISSUE THREAD

**Issue by wplaymkt** [frontendbr/vagas#170]
# Descrição da vaga

Desenvolver aplicações web, com foco no front-end, dar suporte à serviços já desenvolvidos e criar novos projetos.

## Local

Novo Hamburgo - RS (alocado somente)

## Benefícios
- Vale refeição (caso preciso)
- Vale transporte (caso preciso)

## Requisitos
- HTML5 e CSS3
- jQuery
- AngularJS
- Frameworks de CSS, tais como UIkit, Foundation e Bootstrap

## Diferenciais
- Conhecimentos em SEO
- Ferramentas de automação (Gulp)
- Versionamento (Git)
- Noções básicas de Design

## Contratação
CLT a combinar

## Como se candidatar
Por favor envie um email para selecao@wplay.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

**Comment by LFeh** [comment]
Estão certas as labels?
_____

Desculpa, mas eu tiraria 1h de almoço como beneficio. Pega mal.

**Comment by wplaymkt** [comment]
Estão certas sim, obrigada. Já retirei o item conforme comentaste.

**Comment by gabrielrunescape** [comment]
Remoto ou presencial?

**Comment by carloschneider** [comment]
@gabrielrunescape 

> Novo Hamburgo - RS (alocado somente)

**Comment by wplaymkt** [comment]
É presencial.

 

Atenciosamente,


 <http://www.wplay.com.br/> WPlay marketing Interativo


Jaíne Röhsig


Gerente de Projetos


 


Rua João Pessoa, 135
Pátria Nova - Novo Hamburgo - RS
Fone: (51) 3035.2829

Skype: projetos.wplay
www.wplay.com.br 


 



 <http://facebook.com/wplaymkt> http://img.wplay.com.br/img/wplay/assinatura/fb.jpg

 <http://instagram.com/wplaymkt> http://img.wplay.com.br/img/wplay/assinatura/insta.jpg

 

 

De: Gabriel Filipe de Souza Prado [mailto:notifications@github.com] 
Enviada em: quinta-feira, 17 de novembro de 2016 10:17
Para: frontendbr/vagas
Cc: wplaymkt; Author
Assunto: Re: [frontendbr/vagas] [NOVO HAMBURGO/RS] Desenvolvedor Front-end (#170)

 

Remoto ou presencial?
