### ISSUE TITLE
[São Paulo] Front-End Developer na NerdMonster Digital Retail

### ISSUE THREAD

**Issue by lavorato** [frontendbr/vagas#1701]
## Descrição da vaga
O time de desenvolvimento da [NerdMonster](https://nerdmonster.com/) está procurando um programador frontend apaixonado por desafios envolvendo programação e que está sempre atualizado com as evoluções das tecnologias do mercado.

## Local
[Escritório, Vila Mariana / Paraíso - São Paulo (ao lado do metrô Ana Rosa)](https://www.google.com.br/maps/place/NerdMonster+Digital+Retail/@-23.581608,-46.637762,15z/data=!4m5!3m4!1s0x0:0x8e407a7bb020c0ed!8m2!3d-23.581608!4d-46.637762)

## O que você vai fazer?
- Implementar interfaces web;
- Implementar dashboards e manutenção de plataforma;
- Criação e manutenção de landing pages;
- Testes de responsividade em sites.

## Diferenciais
- Horário flexível;
- Equipe unida e time enxuto;
- Liberdade para incorporar novas ferramentas e tecnologias;
- Ótima localização do escritório, ao lado do metrô;
- Conhecer técnicas e gostar de discutir interface/usabilidade de produto;
- Contato direto com a equipe em todos os níveis da empresa, todos tem voz na empresa;
- Dress Free.

## Requisitos
**Obrigatórios:**
- Conhecimento médio/avançado de HTML5 e CSS3
- JavaScript (jQuery como framework);
- UX (conhecimentos básicos);
- Layout Responsivo;
- Adobe Photoshop (para exportação, corte de imagens, etc.);
- Habilidade de comunicação e de trabalho em time.

**Diferenciais:**
- Node.js;
- Ter trabalhado com pelo menos um dos frameworks: Vue.js, Angular, React, etc.;
- Experiência com RESTful APIs;
- Código limpo e organizado;
- Noções de SEO;
- Noções de UI e UX;
- Proatividade para resolução de problemas;
- Cultura Scrum.

## Contratação
- Regime PJ a combinar (favor enviar pretenção salarial junto com o envio de seu seu CV/Portfólio)
- Início imediato

## Nossa empresa
Nós somos uma empresa com uma missão bastante clara: Empoderar varejistas a terem o controle de sua multipresença digital e centralizar o marketing digital em um único lugar. A NerdMonster é líder em seu segmento e já conta com mais de 30 mil estabelecimentos físicos usando sua plataforma.

Buscamos ativamente desenvolvedores capazes, motivados a procura de novos desafios através da programação focada sempre em tecnologias de ponta com Machine Learning, BigData e Inteligência Artificial.

## Como se candidatar
Por favor envie um email para marcos.lavorato@nerdmonster.com com seu CV/Portfólio anexado - enviar no assunto: Front-End Developer na NerdMonster Digital Retail

## Tempo médio de feedbacks
- Costumamos enviar feedbacks em até 05 dias após cada processo.

## Labels
- Alocado
- PJ
- Júnior
- Pleno

**Comment by Roger-Melo** [comment]
somente alocado? :confused:

**Comment by lavorato** [comment]
Olá! Sim Roger, somente em nosso escritório. =)

**Comment by developer-sp** [comment]
Enviado @lavorato

**Comment by laurobs8** [comment]
Acabei de enviar @lavorato
