### ISSUE TITLE
[Nova Zelândia - Remoto - Freelancer] (Senior/Pleno) Front-End Developer na Navigate Travel

### ISSUE THREAD

**Issue by lucashfreitas** [frontendbr/vagas#1704]
Fala galera, beleza?

A empresa em que trabalho na Nova Zelandia està procurando algum dev frontend com experiencia (**pleno** ou **senior**) em React e bons skills com design em geral (CSS,HTML,etc) para pegar algumas demandas que surgiram na empresa.

O trabalho não serà complexo. A empresa tem 3 sites todos feitos em React e frequentemente precisam de fazer algumas modificações/incrementos no site. Algumas dessas modificações são referentes a design, por isso demanda-se bons skills em design.

Acredito que poucas horas por semana serão suficientes pra fazer as tarefas. Como os sites jà estão prontos e a qualidade do codigo està boa, nao serà algo muito complexo!

A pessoa que se candidatar deve ter experiencia e algum portifólio/projeto/referências para mostrar.

Uma empresa terceirizada aqui da nova zelandia estava desenvolvendo os sites, e como os mesmos vao ser entregues esse mês, a empresa precisarà de alguem com disponibilidade de algumas horas por semana para dar manutenção e fazer mudança.

Toda vez que trabalharam com brasileiros (alguns freelas) eles gostaram bastante e tem muita boa impressao sobre o nosso trabalho, devido a isso eles estao procurando alguem no br para executar esses pequenos ajustes.

O ideal tambem è que a pessoa tenha um nivel de ingles razoavel, pois ele irà se comunicar em ingles para pegar as demandas, mas eu consigo ajudar nessa parte.

Enfim, a empresa não è uma empresa de T.I, mas è uma empresa super bacana e com um pessoal muito gente boa. No momento sou o unico dev que estou desenvolvendo todos os sistemas e administrando toda a parte de T.I da empresa, então vai ficar um pouco corrido para eu fazer esses ajustes no site. 

Caso alguem se interessar e tiver disponibilidade de algumas poucas horas por semana entre em contato comigo: lucashfreitas1@gmail.com pra gente discutir mais detalhes, como valor por hora, metodo de pagamento, etc etc.

Muito obrigado desde ja e um òtimo dia!

**Comment by nandomoreirame** [comment]
Nice! 🎉

**Comment by igorsfreitas** [comment]
Enviado !

**Comment by ronaiza-cardoso** [comment]
Enviado!

**Comment by MarcosGray** [comment]
Enviado.
