### ISSUE TITLE
[São Paulo] Fullstack Developer no Cotafios - Primeira plataforma de cotação de fios texteis

### ISSUE THREAD

**Issue by rafaelnasser** [frontendbr/vagas#1705]
## Descrição da vaga

Buscamos um Desenvolvedor Fullstack que consiga avançar o projeto.  Os maiores requisitos são frontend mas é desejável um pouco de back (node).  Projeto em NodeJS + JS.  Tem que ter conhecimento de Firebase, React, Riot, jquery, moment.js.  Buscamos pessoa energética com vontade de aprender, crescer e criar a melhor plataforma de fios têxteis!  Com potencial de crescimento na empresa.

## Local

Remoto ou Escritório, São Paulo - Santa Cecilia (em frente ao metro marechal deodoro)

## Benefícios

CLT (com todos beneficios) ou PJ.

#### Diferenciais

- Escritorio é uma central de startups então a vibe é leve e divertida
- Café da manhã sempre servido de manhã na empresa

## Requisitos

**Obrigatórios:**
- experiência com NodeJS
- experiencia com JS

**Desejáveis:**
- Firebase
- React
- Riot
- Jquery
- Moment.js

## Contratação

CLT ou PJ (a combinar)

## Nossa empresa

Projeto Cotafios, a primeira plataforma de cotação de fios têxteis do Brasil.  Temos objetivos muitos grandes com essa empresa.

## Como se candidatar

Por favor envie um email para rafael@cotafios.com.br com seu CV anexado - enviar no assunto: Vaga Dev Cotafios 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 horas após o recebimento.  Por favor deixe seu celular no e-mail também.

## Labels

- CLT
- Estágio
- Freela
- Júnior
- PJ
- Pleno
- Remoto
- Sênior
- Fullstack
- NodeJS
- JS

**Comment by felipebazza** [comment]
Enviado ! =)

**Comment by igorsfreitas** [comment]
Enviado !

**Comment by MarcosGray** [comment]
Enviado.
