### ISSUE TITLE
[Remoto] Vue.js Developer na Inter Telecom

### ISSUE THREAD

**Issue by vegbrasil** [frontendbr/vagas#1706]
## Descrição da vaga

Atuará no desenvolvimento de ferramentas internas da empresa, similares a um ERP + CRM. 

O candidato irá liderar o projeto de front-end e terá autonomia para moldá-lo, em sintonia com os desenvolvedores backend e com os requisitos do projeto. Necessitamos que o código seja limpo, bem documentado e com boa cobertura de testes. 

Apreciamos códigos leves, simples e com poucas dependências. 

Não há necessidade de comprometimento em tempo integral. O projeto é de longa duração (12+ meses) e faremos as entregas por módulos de 3 a 4 semanas cada.

## Local

Remoto

## Requisitos

**Obrigatórios:**
* Capacidade de desenvolver interfaces com base nos requisitos dos projetos;
* Conhecimento em HTML5, CSS e JavaScript (ECMAScript 5+);
* Conhecimento em framework de construção de interfaces (Vue.js);
* Capacidade para desenvolver códigos testáveis e conhecimento para automação de testes unitários, funcionais e de integração;
* Conhecimento em Bootstrap 4;
* Experiência com trabalho em equipe com controle de versão (Git);
* Bônus: experiência com GitLab CI.

## Contratação

PJ a combinar

## Nossa empresa

A Inter Telecom trabalha com serviços de telecomunicações com um modelo de negócios único no país e busca fomentar seu crescimento acelerado com o desenvolvimento de ferramentas próprias.

## Como se candidatar

Por favor envie um email para recrutamento.dev@intertelecom.net.br com CV ou portfólio.

## Labels

- Freela
- PJ
- Remoto
- Sênior

**Comment by nandomoreirame** [comment]
nice! 🎉

**Comment by rafaelkendrik** [comment]
Enviado @vegbrasil :)
