### ISSUE TITLE
[Remoto]Front-End Developer na BEMIND

### ISSUE THREAD

**Issue by verovargas77** [frontendbr/vagas#1708]
## Descrição da vaga

A Bemind Tecnologia está procurando desenvolvedor pleno/sênior para trabalhar no seu time de desenvolvimento Web.
Nosso time é composto por pessoas criativas, responsáveis, amigáveis, desenroladas, produtivas e que buscam a excelência. Se você se identifica com esse perfil, não deixe de se cadastrar para conhecermos você!

Transforme ideias em soluções digitais, trabalhando em um ambiente ágil e de comunicação aberta.

## Local

Remoto

## Requisitos

**Tem que ter:**

- Formação em Ciência da Computação ou similares
- Capacidade de autogerenciar suas atividades, focado em gerar valor para o cliente
- Habilidades de debugging e resolução de problemas, incluindo debugging em ambientes de produção
- Excelente comunicação verbal e escrita em inglês, com capacidade de interagir com equipes remotas
- Facilidade com lógica de programação
- Fundamentos sólidos de OO
- Experiência sólida em AngularJS/Angular
- Capacidade de realizar consultas complexas com SQL

**Desejável:**
- Experiência com npm, webpack, Jasmine, TypeScript
- Experiência com automação de testes e test-driven development

## Contratação

CLT

## Nossa empresa

A Bemind tem foco em oferecer produtos digitais nas áreas de design, tecnologia e educação, implementados sob medida para clientes com as mais diferentes necessidades.

Somos um time apaixonado pelos desenvolvimento de produtos digitais focados na melhor experiência do usuário e tecnologias mobile e web.

## Como se candidatar

Para saber mais detalhes sobre a vaga e se candidatar, acessa o link: http://bit.ly/devnabemind

## Labels

- CLT
- Pleno
- Sênior

**Comment by MaryCaroline** [comment]
O que a empresa oferece?
