### ISSUE TITLE
[São Paulo] Front-End Developer JR na Lojas Renner (ecom)

### ISSUE THREAD

**Issue by jureis** [frontendbr/vagas#1709]
## Descrição da vaga
front end jr - para e-commerce da lojas Renner

## Local
Escritório, São Paulo - Vila Olímpia

## Benefícios
- Plano de saúde (depois de 24 meses de casa)
- Restaurante conveniado (nao tem VR)
- VT
- PPR anual de até 1 salario (se a cia atingir as metas)

## Requisitos
**Obrigatórios:**
Conhecimentos básicos em HTML, CSS, JavaScript

**Desejáveis:**
Noções de usabilidade, plataforma oracle e photoshop (não obrigatório)

## Contratação
CLT

## Nossa empresa
Somos o e-commerce da Renner -  A maior varejista de moda do Brasil.
Estamos alocados em SP vila olímpia desde 2017 (a sede fica em Porto Alegre) 

buscamos uma pessoa que ficará com a gente na equipe de criação, ira nos auxiliar com as subidas e programações dos banners do site através da nossa ferramenta da oracle, e sazonalmente programar algumas landing pages temáticas (simples) – além de prestar todo o suporte para mudança de links e menus do site.

Trabalhamos num E-Commerce de moda, então é imprescindível que esta pessoa seja bem dinâmica, rápida, organizada, responsável e comprometida com prazos e horários. 

## Como se candidatar
Por favor envie um e-mail para j.reis@lojasrenner.com.br com seu CV anexado + portfólio se tiver - com sua PRETENSAO SALARIAL 
enviar no assunto: Vaga Front-End JR 

## Labels
- Alocado
- CLT
- Júnior

**Comment by allexaraujo** [comment]
Sério, 24 MESES pra ter acesso ao plano de saúde? Caramba ein.

**Comment by prosaka** [comment]
Primeira vez que vejo ter que esperar 24 meses pra ter plano de saude, queria ver o salario da vaga

**Comment by yoneshinzato** [comment]
enviado!

**Comment by yuritoledo** [comment]
Caraca. 24 meses.

**Comment by viniciusdocanto** [comment]
Deve ser 24 meses porque ninguém deve aguentar ficar mais de 2 anos lá! 😆

**Comment by yuritoledo** [comment]
aushuahsuahsu

**Comment by developer-sp** [comment]
Enviado.
