### ISSUE TITLE
[Rio de Janeiro] [Full-time] - Sênior Software Engineer at VTEX

### ISSUE THREAD

**Issue by amoreira** [frontendbr/vagas#171]
## Descrição da vaga

_Esta vaga não tem limite de contratações ou data para expirar._

TL;DR: Aqui nós **trabalhamos sem hierarquia**, com as **melhores e mais pragmáticas tecnologias**, construindo o futuro do **e-commerce global**. Venha fazer a diferença.

A VTEX é uma empresa global de tecnologia focada em produtos para e-commerce que impacta diariamente o trabalho de milhares de pessoas ao redor do mundo. Através dos seus produtos e serviços, oferece aos lojistas uma plataforma coesa para executar todo o seu negócio e proporcionar aos seus clientes sempre a melhor experiência de compra.

Na VTEX, uma ideia com a capacidade de mudar a trajetória da empresa pode vir de qualquer lugar. Nossa equipe se organiza numa estrutura verdadeiramente horizontal que remove barreiras e dá liberdade para que as pessoas atinjam seu potencial completo. Por aqui não existem chefes dizendo a você o que fazer: é sua responsabilidade abraçar proativamente os problemas e resolvê-los da melhor forma que conseguir. Nós somos pioneiros na implementação e divulgação de tecnologias organizacionais como auto-gerenciamento, plenitude e propósito evolucionário.

Nós não acreditamos em títulos, mas usamos o termo **Senior Software Engineer** para comunicar o nível de maturidade esperado para essa vaga. Como parte de uma equipe altamente motivada, você vai resolver problemas de verdade, criando e mantendo aplicações distribuídas de larga escala e alta disponibilidade.Além de trabalhar em conjunto com os times de design e atendimento, você vai ser o protagonista de decisões que vão impactar a próxima geração de tecnologias de e-commerce do mundo.

**Responsabilidades**

Como membro na nossa equipe você vai ter autonomia para:

+ Construir a próxima geração de serviços e ferramentas que serão consumidas por milhares de desenvolvedores ao redor do mundo;
+ Analisar e melhorar a eficiência, escalabilidade, estabilidade e segurança de sistemas com impacto na economia global;
+ Gerenciar cenários de crise e instabilidade com velocidade e controle;
+ Auto-gerenciamento e proatividade para lidar com demandas e prioridades num ambiente ágil e com muito contato com clientes

Além disso, esperamos que todos os membros da nossa equipe sejam agentes ativos na evolução da nossa cultura:

+ Experimentando e melhorando ferramentas e o processo de desenvolvimento;
+ Mentorando e colaborando com estagiários e desenvolvedores menos experientes;
+ Participando, coordenando e auxiliando atividades como workshops, comitês e hackathons;
+ Participando no processo de contratação de novos engenheiros

**Habilidades relevantes para Frontend**

+ Experiência construindo single page applications, especialmente usando tecnologias como React, Redux, GraphQL, Angular;
+ Desenvoltura com JavaScript moderno e seu toolchain (sem fadiga!);
+ Experiência com data visualization;
+ Entendimento dos trade-offs envolvidos com testes automatizados e capacidade de utilizá-los quando necessário

## Local

Rio de Janeiro - Praia de Botafogo 306 - Botafogo (Presencial)

## Benefícios

+ Horário flexível;
+ Contratação CLT com salário competitivo;
+ Vale refeição, Plano de saúde e Gympass (acesso a mais de 2700 academias);
+ Participação nos lucros;
+ Frete grátis nas +800 lojas VTEX;
+ Xbox One disponível;
+ Dress code informal (bermudas e etc 😄 );
+ Desafios de verdade

## Requisitos
+ Formação em Ciências da Computação ou áreas relacionadas;
+ Inglês fluente;
+ Experiência em criação de produtos web escaláveis e distribuídos;
+ Pensamento sistêmico para projetar soluções simples para problemas complexos;
+ Facilidade de aprendizado e adaptação: nós mudamos junto com o mundo;
+ Ter o impulso de questionar e descobrir alternativas para paradigmas pré-existentes;
+ Interesse e facilidade para, se necessário, aprender novas linguagens de programação

## Como se candidatar

https://vtex.workable.com/jobs/376877

**Comment by amoreira** [comment]
Vídeo sobre o nosso processo de trabalho https://www.youtube.com/watch?v=uliCWdJ4Bx4

**Comment by LFeh** [comment]
Show!
