### ISSUE TITLE
[São Paulo] Fullstack Developer na GAVETEIRO

### ISSUE THREAD

**Issue by espudaro** [frontendbr/vagas#1710]
## Descrição da vaga

Buscamos Fullstack Developer com alguma experiência com Ruby on Rails. 
Será responsável pelo desenvolvimento de novas funcionalidades e manutenção das plataformas da Gaveteiro; resolução de bugs e suporte à equipe de atendimento; integração entre sistemas interno e externo, através de APIs, entre outras atividades.

## Local

Estamos localizados na região da Barra Funda em São Paulo.

## Requisitos

- Conhecimento HTML 5, CSS 3 e Javascript;
- Domínio em Ruby, Rails e Orientação a Objetos;
- Práticas básicas TDD/BDD;
- Experiência com modelagem de banco de dados relacionais e linguagem SQL;
- Conhecimento em sistemas de controle de versão (Git);
- Habilidades interpessoais de escrita e de comunicação verbal

**Desejáveis:**

- Tenha atitude positiva;
- Tenha sede por conhecimento;
- Seja um excelente team player;
- Tenha sólidos conhecimentos e habilidades em algoritmos e estruturas de dados;
- Tenha domínio de engenharia de software, princípios, boas práticas e padrões de arquitetura;
- Goste de programar em todos os níveis do stack tecnológico;
- Tenha experiência com alguma linguagem de programação (Javascript, Ruby, Python);
- Tenha experiência com métodos ágeis e práticas de engenharia ágil, como TDD;
- Tenha conhecimento de ferramentas de versionamento (como git, svn, etc.);
- Tenha conhecimento de APIs REST.

**Atividades e Responsabilidades**

- Desenvolvimento de novas funcionalidades e manutenção das plataformas da Gaveteiro;
- Empregar as melhores práticas de desenvolvimento para entregar código limpo e de qualidade;
- Resolução de bugs e suporte para a equipe de atendimento;
- Integração entre sistemas internos e externos, através de APIs;
- Planejamento e priorização de tarefas usando metodologias ágeis;
- Aprender novas tecnologias e técnicas para a melhoria contínua de nossos sistemas;

**Diferenciais**

- StartUp de e-commerce B2B com 5 anos de mercado
- Vivência em comércio eletrônico/meios de pagamento/marketplace.
- Ambiente descontraído
- Home office em alguns dias

## Contratação

PJ ou CLT (a combinar)

## Nossa empresa

A Gaveteiro é o distribuidor online com o mais amplo mix de produtos para empresas, de escritório a indústria. Atuamos no segmento B2B, atendendo todas as empresas do Brasil e estamos trabalhando para transformar esse mercado através da mais completa plataforma de compras online. Aqui é um lugar único onde os nossos clientes encontram tudo o que precisam.

## Como se candidatar

Por favor envie um email para priscila.franze@gaveteiro.com.br com pretensão salarial e seu CV anexado - enviar no assunto: [Vaga Frontend] - **SEU NOME**

## Labels

- Alocado
- CLT
- PJ
- Júnior
- Pleno
- Ruby on Rails

**Comment by MrS4w** [comment]
Domínio em Ruby?
Experiência com SQL?

**Comment by LFeh** [comment]
Essa vaga ta muito mais para Fullstack Developer hein...

**Comment by espudaro** [comment]
Oi @MrS4w, buscamos uma pessoa com algum conhecimento em Ruby e SQL, não precisa ser expert, já temos nossos especialistas! 😃

**Comment by espudaro** [comment]
> Essa vaga ta muito mais para Fullstack Developer hein...

Não curto muito o termo "Fullstack", pq sempre tende mais para um lado, ou para front ou para back. No nosso caso, precisamos mais de frontend.

mas... blz, Fullstack!

**Comment by LFeh** [comment]
Mas é por conta da própria descrição da vaga, a pessoa vai atuar nas duas frentes:

>Domínio em Ruby, Rails e Orientação a Objetos; 
Experiência com modelagem de banco de dados relacionais e linguagem SQL;

Qualquer vaga que exige domínio em Back-end e Front-end, está buscando um Fullstack.
