### ISSUE TITLE
[REMOTO] Front-End Developer na UPNID

### ISSUE THREAD

**Issue by megandavulpi** [frontendbr/vagas#1711]
### Sobre a empresa: Upnid

Nós somos a Upnid. Nós construímos ferramentas que facilitam o processo de vendas online. Nosso principal produto é o checkout, uma página de pagamento que permite, em menos de 5 minutos, que nossos clientes consigam vender através da internet. Nossa missão é simplificar a maneira como pequenos e médios empreendedores recebem pagamentos através da internet.

### Descrição: O que você irá fazer?

Você será responsável por interagir diretamente com a nossa designer e participar da criação de novas telas e componentes.

### Nossos diferenciais:

Liberdade. Na Upnid você escolhe onde e quando trabalhar. Nosso time é remoto e você tem liberdade para escolher seus horários.
Desenvolvimento de novas habilidades. Oferecemos uma ajuda mensal de R$ 100,00 para compra de livros, cursos e qualquer tipo de material educativo. (Também investimos em cursos mais caros - iremos analisar a viabilidade primeiro.)
Alimentação e Transporte. Cuidamos de suas despesas de alimentação e transporte nos dias em que você optar por trabalhar do nosso escritório.
Crescimento. Você estará fazendo parte de um time jovem e dinâmico, em um projeto em pleno crescimento. Participará ativamente em decisões estratégicas.

### O que você precisa saber?

Conhecimentos sólidos em Javascript, HTML e CSS;
Conhecimentos ou desejo em aprender React;
Noções de "UI"

### Labels:

PJ
Pleno

### Candidatar: http://bit.ly/upnidfront_github

**Comment by rodineicosta** [comment]
Aplicado.

**Comment by cdbm** [comment]
Enviado.

**Comment by MarcosGray** [comment]
Aplicado.

**Comment by adeonir** [comment]
Aplicado

**Comment by psilva21** [comment]
Aplicado!

**Comment by victorvinci** [comment]
a vaga ainda está aberta?

**Comment by victorvinci** [comment]
Aplicado

**Comment by israelcena** [comment]
Aplicado

**Comment by ribeiroevandro** [comment]
Aplicado!

**Comment by megandavulpi** [comment]
> a vaga ainda está aberta?

Sim! =D

**Comment by adeonir** [comment]
oi @megandavulpi eu apliquei através da plataforma, mas não tive feedback

**Comment by rbezerra** [comment]
eu tbm :/

**Comment by megandavulpi** [comment]
> oi @megandavulpi eu apliquei através da plataforma, mas não tive feedback
Oi, @adeonir 

Peço desculpas pelo transtorno, vou verificar internamente o que está ocorrendo e te dou um retorno, ok?

**Comment by megandavulpi** [comment]
> eu tbm :/

Oi, @rbezerra 

Também peço desculpas pelo ocorrido, vou verificar o que está ocorrendo e te dou um retorno, ok?

**Comment by italomlp** [comment]
Oi @megandavulpi, também estou na mesma situação de não ter recebido feedback.

**Comment by rafaelrf** [comment]
Olá @megandavulpi, também não recebi feedback.
