### ISSUE TITLE
[Irlanda/Dublin] Node.JS / React Developer com sponsor

### ISSUE THREAD

**Issue by rxluz** [frontendbr/vagas#1712]
## Descrição da vaga

Work with Node.JS/Express/React/Redux/Webpack

## Local

Inicialmente remoto com possibilidade de sponsor

## Benefícios

- Visto de trabalho para Europa

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Node
- 2 anos de experiência com Mongodb e Express
- 2 anos de experiência com React e Redux
- 4+ anos de experiencia com Javascript

**Desejáveis:**
- conhecimentos em cordova
- conhecimentos em aws
- conhecimentos em ferramentas de automacao de testes

**Diferenciais:**
- projetos opensource
- textos escritos no medium
- palestras

## Contratação

PJ a combinar

## Nossa empresa

Loylap.com

## Como se candidatar

Por favor envie um email para ricardo@loylap.com com seu CV/Linkedin/GitHub - enviar no assunto: Vaga NodeJS/React

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 14 dias após cada processo.
E-mail para contato em caso de não haver resposta: ricardo@loylap.com

## Labels

- Internacional
- Pleno
- Remoto
- Sênior

**Comment by vinyguedess** [comment]
Enviei e-mail

**Comment by IgorVieira** [comment]
Enviado!
