### ISSUE TITLE
[São Paulo] Fullstack Developer na CE7P Digital - Estágio

### ISSUE THREAD

**Issue by ce7p** [frontendbr/vagas#1713]
## Descrição da vaga

Somos uma empresa que fornece serviços digitais para o ramo imobiliário.
Temos plataformas onde usuários podem anunciar bens imobiliários ou procurar bens imobiliários para aluguel/compra.
Busca-se estagiário programador para atuar com desenvolvimento de 2 projetos principais da empresa: aplicativo e website.
Experiência desejada em Angular, Nodejs, Ionic.
Python (crawlers) e será um diferencial.
Conhecimento em APIs RESTfull

## Local

Escritório - Av Mutinga, Pirituba, São Paulo/SP

## Benefícios

- VT
- VR
- Assistência médica (à partir de Janeiro/Fevereiro)

## Requisitos

Escolaridade Mínima: Cursando Ensino Superior
Português (Nativo), Inglês (Intermediário)
Experiência: desejável 1 ano ou mais
Programação: CSS, HTML, JavaScript, jQuery, Python

**Desejáveis:**
- Experiência desejada em PHP, Nodejs, Ionic.
- Conhecimento em APIs RESTfull

**Diferenciais:**
- Python (crawlers) será um diferencial.

## Contratação

Estágio

## Nossa empresa

Somos uma empresa que fornece serviços digitais para o ramo imobiliário.
Temos plataformas onde usuários podem anunciar bens imobiliários ou procurar bens imobiliários para aluguel/compra.

## Como se candidatar

Por favor envie um email para alexandrece7p@gmail.com colocando seu CV anexado - enviar no assunto: "Vaga Fullstack Developer - Estágio"

## Labels

- Alocado

**Comment by Mendrone** [comment]
@ce7p Não entendi, é uma vaga pra estágio ou é CLT/PJ? são formatos diferentes de contratos. Consegue me confirmar pra eu ajustar as labels?

**Comment by ce7p** [comment]
Tudo bem Mendrone?
Acabamos de corrigir aqui. A vaga é para estágio.
