### ISSUE TITLE
[ Remoto] Desenvolvedor  REACT.JS na Sumá

### ISSUE THREAD

**Issue by ferlintec** [frontendbr/vagas#1716]
##Descrição da vaga

Procuramos um desenvolvedor  Front-end com experiência comercial de no mínimo 2 anos 
especificamente com React.JS, que domine o ambiente ao redor de React.(coisas como Redux, Redux Saga,  Webpack, Flexbox  SASS etc..).
Boa noção prática de testes e não se assuste com termos como Jest, Enzime, Mocha, Chai etc…
Conhecimento mínimo de como acontece o deploy de uma App React para produção após desenvolvida.
Que entenda  a “magia”  que acontece por de trás do React,  através do domínio do Javascript moderno (ES6/7/8).
O Candidato selecionado estará atuando em nossa plataforma para gestão e comercialização de alimentos (um Marketplace B2B).
Um ambiente com bastante trabalho,  mas extremamente propício para aprender bastante e crescer profissionalmente.
(No futuro estaremos implantando coisas legais como GraphQL, Apollo, Serverless, AWS Lambda etc)

##Requisitos
Obrigatórios:
* Experiência de pelo menos 2 anos com  ReactJS,;
* Redux
* HTML, CSS
* SASS
* Javascript  moderno (ES6/7/8)
* Flexbox
* Webpack
* Git/GitHub ou BitBucket
* Desenvolver código limpo, de fácil compreensão e manutenção;
* Interesse por novas tecnologias e padrões de arquitetura "fora da caixa";
* Noção de Testes
* Fetch.api, Axios etc…

Desejáveis:

* Alt.JS
* Redux Saga
* Conhecimento em Testes Jest, Enzime.
* conhecimentos em GraphQL, Apollo
* AWS S3, CloudFront, CI/CD

Diferenciais:
* Testes automatizados;
* Conhecimentos em bancos de dados não relacionais;
* Conhecimento de estrutura de infraestrutura em AWS;
* Scrum, Kanban
* React Native

##Alocação
Remota ou Presencial

##Contratação
Contrato como PJ
Remuneração a combinar
Carga horária 35 horas/semana
Local: Florianópolis-SC/Balneário Camboriú

##Nossa empresa

Sumá nasceu de um desejo de mudar e melhorar o equilíbrio de troca entre quem produz e quem consome alimentos originados diretamente do pequeno agricultor familiar. Buscamos, através de qualificação e comercialização justa e transparente por meio da tecnologia, trazer o reconhecimento e dignidade do trabalho no campo, de famílias que dedicam gerações ao cultivo no solo. Se você busca um ambiente extremamente motivado, desafiador, complexo, que está repensando o status quo do modelo de comercialização de alimentos, e com um propósito muito claro, junte-se a nós!
Mais informações em www.appsuma.com.br.

###Como se candidatar
Interessados(as) enviar currículo para tec@appsuma.com.br com assunto "Vaga Dev React.JS"
Telefone: 48 99941-2220

## Labels

- PJ
- Pleno
- Remoto
- Sênior

**Comment by IgorVieira** [comment]
Enviado!
