### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor(a) Front-End Pleno

### ISSUE THREAD

**Issue by ceasbz** [frontendbr/vagas#172]
## Descrição da vaga

Estamos começando a expandir o nosso time e precisamos de pessoas que realmente gostam de estar à frente do mercado, aquelas que curtem experimentar novas tecnologias e que estão sempre antenadas ao cenário atual do desenvolvimento front-end.

A nossa missão é de, simplesmente criar uma equipe de ponta, que esteja engajada com a comunidade e que se sinta confortável com o desconfortável e que curta encarar desafios.

### Local

Escritório - Avenida das Américas, 500 - Barra da Tijuca (Shopping Downtown) - Rio de Janeiro

Ou Remoto

### Benefícios

- Horário flexível;
- Vale refeição ou alimentação (Pode escolher);
- Vale transporte;
- Ambiente descontraído;
- Roupa informal (pode bermuda);

### Requisitos

- Especializado em JavaScript, HTML e CSS;
- Entendimento das melhores práticas de SEO;
- Experiência com sistemas de controle de versão (GIT);
- Conhecimento de desenvolvimento cross platform/browser;
- Conhecimento de Test Driven Development;
- Experiência com pré-processadores;
- Entendimento dos conceitos de Integração Contínua;
- Design responsivo;
- Familiaridade com metodologias ágeis (Extreme Programming e SCRUM);

### Gostaríamos de ver

- +3 anos de experiência em desenvolvimento front-end com aplicações web;
- Aderência aos padrões web e às melhores práticas de acessibilidade (W3C);
- Ter tido experiência com tecnologias, do tipo: React, Polymer ou AngularJS;
- Excelente capacidade de comunicação oral/escrita;
- Escrever código escalável e reutilizável;
- Capacidade de gerir o próprio tempo;
- Paixão pela área;

### Contratação

CLT

### Como se candidatar 

Enviar email para recrutamento-ti@personare.com.br com o subject: `Desenvolvedor Front-End Pleno`

Booa sooorte ❤️

**Comment by lucasalmeida92** [comment]
Enviado! ;]

**Comment by ceasbz** [comment]
@mtmr0x Continuamos com a vaga em aberto :}

**Comment by ceasbz** [comment]
@LFeh Irei fechar essa issue para reformular algumas coisas da vaga;

Irei abrir outra mais tarde.
