### ISSUE TITLE
[São Paulo] Front-End Developer na CargoX

### ISSUE THREAD

**Issue by keitoliveira** [frontendbr/vagas#1720]
## Descrição da vaga

Estamos desenvolvendo nosso sistema de gestão de transportes, que engloba desde o relacionamento com os clientes, pricing, propostas, busca e contratação de caminhoneiros, gerenciamento de risco, seguro, emissão de documentação de transporte, até o pagamento, pedágios, rotas e tracking dos nossos caminhoneiros.

**O que você irá fazer:**

- Construir soluções de software para garantir nosso propósito: trazer eficiência operacional para os caminhoneiros, aumentando seus rendimentos e reduzindo seus riscos, além de conferir agilidade aos embarcadores na realização de seus fretes;
- Desenvolver e integrar sistemas Web escaláveis e de alta disponibilidade;
- Aplicar técnicas de desenvolvimento orientado a testes, como TDD e BDD, automação de testes;
- Trabalhar com os outros times para definir e implantar os padrões arquiteturais adequados para os sistemas da empresa;
- Valorizar e defender soluções simples e objetivas para o design e manutenção dos sistemas da CargoX, sempre com o olhar crítico de valor para o produto/negócio da empresa;
- Pesquisar e trazer para empresa novidades e alternativas aos processos e ferramentas existentes, buscando sempre a adoção de tecnologias de ponta ideais para nossos desafios de negócio.

## Local

Cubo, São Paulo - Vila Olímpia, em frente ao Shopping Vila Olímpia.

## Benefícios

- Plano de saúde
- Plano odontológico
- VR de R$ 26,00/dia
- VT
- Gympass

#### Diferenciais

- Horário Flexível, de verdade;
- Home Office;
- Video Game;
- Ambiente tranquilo e descontraído;
- Estamos no Cubo, então temos chopp das 18h às 20h todos os dias, áreas de descompressão, mesas ao ar livre, e etc..

## Requisitos

**Obrigatórios:**
- Proficiência com HTML (HTML5), CSS (SASS/SCSS);
- Proficiência com Javascript;
- Domínio em algum framework de UI (VueJS, Ember, React, outros);
- Experiência com Cross-Browser;
- Experiência com REST;
- Domínio em ferramentas de debugging (Chrome Inspector, Firebug);
- Experiência em modelagem, arquitetura e componentização;
- Experiência com testes automatizados em JS (Jest, Karma, Mocha, Nightwatch, Jasmine, outros);
- Experiência com ferramentas de build (Webpack, Gulp, Grunt).

**Desejáveis:**
- Conhecimento do State Management pattern;
- Conhecimento de modelos alternativos de troca de dados (GraphQL, Falcor, Relay, outros);
- Trabalhar com versões precompiladas do HTML (Pug, Jade, HAML, etc.).

**Diferenciais:**
- Ser ativo na comunidade OpenSource.

## Contratação
CLT à combinar.

## Nossa empresa
A CargoX tem como missão transformar o mercado de transportes do Brasil.

Somos uma empresa de alta tecnologia que oferece serviços de transporte de cargas lotação para empresas. Permitimos que mais de 250 mil motoristas autônomos utilizem toda a sua capacidade e evitem viagens de retorno ociosas.

Como resultado, isso diminui o volume de emissões de carbono e a quantidade de caminhões vazios circulando nas estradas. Além disso, nossos motoristas aumentam sua lucratividade enquanto nossos clientes ganham eficiência e escalabilidade.

## Como se candidatar
Entre em nossa página na Kenoby para [Sênior](https://jobs.kenoby.com/cargox/job/front-end-developer-pl/5bf87e82788270678100d501) ou [Pleno](https://jobs.kenoby.com/cargox/job/front-end-developer-sr/5c34e3eec7ea3465cb43f049) e participe de nosso processo!

## Labels

- Alocado
- CLT
- Pleno
- Remoto
- Sênior

**Comment by LFeh** [comment]
Cubo ❤️ 

Quem entrar nessa vaga, me chama pra tomar um chopp na laje 😄

**Comment by keitoliveira** [comment]
Fecha não, estamos contratando ainda 😛

**Comment by MrS4w** [comment]
@keitoliveira são até 14 dias sem movimentação na issue :sweat_smile: 
Dá uma olhada [aqui](https://github.com/frontendbr/vagas#importante).

**Comment by felipefialho** [comment]
@keitoliveira prefere abrir outra ou manter essa?

**Comment by keitoliveira** [comment]
@felipefialho acho que vou abrir outra, para ir para o topo da lista de novo 😛

**Comment by felipefialho** [comment]
demorou, tenho fechado issues antigas
