### ISSUE TITLE
[Jaú/SP - Semipresencial] Pleno Front-End Developer na Alboom

### ISSUE THREAD

**Issue by welingtonsampaio** [frontendbr/vagas#1722]
## Descrição da vaga

Você irá trabalhar no coreteam de desenvolvimento do nosso principal produto, o Alboom Pro Site. Uma plataforma de criação de sites focado na facilidade da criação e atualização de um website profissional. O Pro Site é voltado para profissionais independentes e tem a missão de ser a plataforma de sites mais fácil de atualizar. Pela sua natureza, impõe desafios indispensáveis para a evolução de um front-end developer, como uso de APIs avançadas dos browsers, performance para milhares de elementos simultaneamente e sincronia de dados real-time. Você fará parte e será responsável pela nova fase do produto com uma funcionalidade indispensável para seu crescimento, melhorias no funcionamento atual e correção de bugs.

## Local

Jaú/SP Alocado ou Semipresencial.

## Benefícios

- Auxílio transporte
- Seguro de vida
- VA ou VR de R$ 350/mês

#### Diferenciais

- Horário flexível
- Incentivo e auxilio para eventos
- Sala de jogos e descanso
- Ambiente descontraído
- Happy hours frequentes

## Requisitos

**Obrigatórios:**
- Disponibilidade para trabalhar pelo menos **1 semana por mês alocado**
- Ser apaixonada(o) por desenvolvimento de software e tecnologia
- Ter facilidade para trabalhar dentro de times multi-disciplinares
- Saber escrever codigo limpo e legível por humanos
- Experiência com HTML5, CSS3, JavaScript
- 3 anos de experiência com Node
- 2 anos de experiência com React e Redux
- Conhecimentos de consumo de APIs REST

**Desejáveis:**
- Conhecimentos em Ruby on Rails
- Experiência com métodos ágeis (Scrum, Kanban, Lean, etc)
- Conhecimentos em AWS

**Diferenciais:**
- Conhecimento sólido de ECMAScript 6 e Web APIs
- Experiência com testes unitários, de aceitação, mocks, etc
- Experiência com mentoring/coaching de pares e team members menos experientes

## Contratação

CLT ou PJ, a combinar

## Nossa empresa

A Alboom é hoje a maior plataforma de serviços digitais para fotógrafos e artistas visuais da América Latina. Com mais de 24 mil usuários e em mais de 40 países a Alboom engloba a maior diversidade de produtos e serviços para fotógrafos, contando com sites profissionais, aprovação de fotos, aprovação de álbum, criação de galerias, CRM, diagramação de álbuns e muito mais. Além disso temos como missão ser uma plataforma multi aplicação que trás uma camada gigantesca de micro-serviços que fazem com que a plataforma funcione e entregue a melhor experiência para nossos usuários.

## Como se candidatar

Por favor envie um email para recruit@alboompro.com com seu CV anexado - enviar no assunto: [React] Vaga Front-End

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 4 dias após cada processo.

## Labels

- Alocado
- CLT
- PJ
- Pleno
- Remoto

**Comment by ReactGirl** [comment]
Saber escrever codigo limpo e legível por humanos
