### ISSUE TITLE
[Remoto] Freelance para o site https://podentender.com

### ISSUE THREAD

**Issue by nawarian** [frontendbr/vagas#1724]
## [Remoto] Freelance para o site https://podentender.com

Atualmente o site https://podentender.com está na plataforma wordpress. E utilizamos um layout comprado.
Estou realizando a migração da plataforma para utilizarmos o Jigsaw (similar ao jekyll) por questões de custo e qualidade. Pretendo portanto rescrever o front-end para que fique mais apresentável e menos pesado ao mesmo tempo.
Preciso de um developer que possa escrever os principais templates de forma clara e limpa, utilizando BEM e sass.
O layout é basicamente o mesmo, precisamos porém fazer do zero e mobile-first. O carrossel da home pode ser removido, eu quero um template 100% html + css. Sem JS. Eu também de uma interface para o player que eu irei desenvolver em JS posteriormente.
Então em resumo:

- Mobile-first
- Sass + bem, 100% html e css, sem JS
- Não utilizar frameworks como bootstrap, jquery, react, vue...
- Script de build
- [Opcional] utilizar fontes padrão do sistema

A desenvolver:
- Home page (remover o carrossel)
- Página de episódio
-- Criar uma interface html+css com um player
- Página de categoria
- Página de contato

## Local

Remoto

## Requisitos

**Obrigatórios:**
- SASS
- BEM
- Components

**Desejáveis:**
- Build com travis-ci
- Utilizar tags semânticas em vez de `div`s para tudo

## Contratação

Infelizmente não posso oferecer contratos e nem faço questão de emissão de notas fiscais.

O valor será discutido durante a troca de especificações. Seria interessante podermos negociar um pacote de horas para que possamos ambos prever o investimento necessário para este job.

## Nossa empresa

O PODEntender é um projeto que visa divulgar a ciência brasileira para o grande público de forma divertida e descomplicada. O projeto já tem cerca de 3 anos de idade e é um esforço conjunto de uma galera muito massa que acredita que um dos meios para melhorar a educação e produção científica no Brasil é justamente conscientizar a população brasileira.

## Como se candidatar

Por favor envie um email para nickolas@phpsp.org.br com seu CV OU portfolio anexados - enviar no assunto: [Freelance PODentender] <seu nome aqui>. Por exemplo, [Freelance PODEntender] Níckolas Da Silva.

## Tempo médio de feedbacks

Infelizmente eu não fico muito disponível durante a semana, porém imagino que entre 4 a 5 dias eu possa lhes retornar com um feedback.
E-mail para contato em caso de não haver resposta: nickolas@phpsp.org.br

## Labels

- Freela
- Pleno
- Remoto

**Comment by RenatoAreas** [comment]
Enviado :)
