### ISSUE TITLE
[Remoto] Frontend Developer na Instruct

### ISSUE THREAD

**Issue by iassia** [frontendbr/vagas#1727]
Estamos buscando frontend developer que consiga trabalhar em um time multidisciplinar, que tenha bons conhecimentos em desenvolvimento web, tanto front-end (não só Bootstrap, mas desenvolvimento de interfaces complexas) quanto backend.

Você fará parte de uma equipe que desenvolve soluções de automação de alto impacto na operação de TI de nossos clientes.

Sua maior responsabilidade será desenvolver interfaces desde o desenho, passando pela implementação do HTML, CSS e JavaScript e integrações com back-end

É fundamental saber aprender novas tecnologias e que você goste de compartilhar o seu conhecimento com outras pessoas. Ser curioso e autodidata são características bem-vindas e importantes.

Precisamos que você conheça HTML, CSS e Javascript e tenha noções de back-end, principalmente para integração das interfaces. Conhecimento em linguagens como PHP e Python e uso de aplicações visuais como: Figma, Sketch, Illustrator, etc são um diferencial.

O trabalho poderá ser realizado totalmente remoto, com ocasionais viagens a São Paulo, Brasília, Campinas e Rio de Janeiro para encontros com a equipe ou clientes, custeados pela empresa. Portanto, é fundamental ter disponibilidade para viajar.

Nós não perguntamos pretensão salarial. Se identificarmos que você é a pessoa que queremos ter em nossa equipe, faremos uma proposta financeira condizente.

**Benefícios**

- Regime de contratação CLT;
- Salário inicial entre R$ 2.500,00 e R$ 3.500,00;
- Plano de saúde e odontológico Bradesco Nacional Top para o titular e mais um dependente totalmente custeados pela empresa;
- Vale refeição de R$ 400,00;
- Vale alimentação de R$ 600,00;
- Seguro de vida corporativo custeado pela empresa;
- Verba semestral de R$ 1250,00 garantida para investimento em treinamentos e educação;
- Bolsas de estudo custeadas pela empresa;
- Acesso aos treinamentos da empresa sem custos;

**Por que trabalhar na Instruct?**

- Ambiente de trabalho amigável, inclusivo e seguro;
- Resolvemos problemas desafiadores e em larga escala para nossos clientes;
- Trabalhar na empresa referência de mercado em infraestrutura como código no Brasil;
- Empresa premiada como "Melhor Parceira Mundial" da Puppet em 2016;
- Acesso gratuito aos treinamentos oficiais Puppet e GitLab ministrados pela Instruct;
- Incentivos para participação em eventos, cursos e palestras;
- Empresa fundamentada nos princípios DevOps, Infra as Code e Agile;
- Usamos ferramentas e métodos inteligentes e inovadores para interagir com nosso time;
- Cultura blameless;
- Café de qualidade!

**O que esperamos de você?**

- Esperamos que nos ajude a melhorar a performance dos nossos clientes;
- Esperamos que você consiga se relacionar bem com o seu time de trabalho, que saiba fazer parte do time, respeitar o time, dividir e compartilhar responsabilidades, acertos e aprendizados;
- Esperamos que você possa ir além, propondo, criando, mudando, construindo, crescendo e evoluindo junto conosco;
- Queremos que você agregue valor ao nosso time e a nossa organização, e queremos que a nossa organização agregue valor a você;

**Conhecimentos técnicos**
Estes são os conhecimentos fundamentais para trabalhar conosco:

- HTML;
- CSS (Flexbox e Grid);
- Javascript (ES6+, NodeJs);
- Pré-processadores: Sass ou outros;
- Uso de Git para versionamento de seu código;
- Noções de UI/UX e bom senso estético;
- Inglês técnico competente;

**Diferenciais**
Não são obrigatórios, mas serão devidamente considerados:

- Desenvolvimento de algum projeto Front-end sem a utilização de libraries ou frameworks;
- Automatizadores e Bundlers: Gulp, Webpack, etc;
- NodeJS;
- VueJS;
- Ferramentas de testes JS: Jasmine, Jest ou Mocha;
- Nível superior;

**Tecnologias e métodos**
Estas são tecnologias, métodos e conceitos que utilizamos em nossos projetos, o conhecimento destes será um diferencial apreciado:

- Fundamentos de modelos ágeis como Kanban e Scrum;
- Fundamentos do conceito testes unitários;
- Fundamentos do conceito testes de aceitação;
- Docker e containers;
- NodeJS;
- VueJS;
- Jenkins/GitLab CI;
- Participação em projetos Open Source;
- Mattermost.

Se você acha que tem as características necessárias para participar de nossos projetos e de nosso time, entre em contato!

Enviar um e-mail com CV para jobs@instruct.com.br
com assunto "Frontend Developer Junior".

## Labels

- Remoto
- CLT
- Júnior

**Comment by fsassiv** [comment]
Enviado.

**Comment by randhson** [comment]
Enviado.
Randson N. dos S. França +55 79 99843 9878+55 79 99138 7628 

    Em segunda-feira, 28 de janeiro de 2019 14:50:11 GMT, FLAVIO SANTOS DE ANDRADE <notifications@github.com> escreveu:  
 
 
Enviado.

**Comment by rodineicosta** [comment]
Enviado!

**Comment by marcoswca** [comment]
Enviado!

**Comment by Pagelkopf5** [comment]
Enviado!

**Comment by Yagasakii** [comment]
Enviado!

**Comment by YuriBrunetto** [comment]
Enviado :D

**Comment by felipebazza** [comment]
Enviado o/

**Comment by brunooomelo** [comment]
Enviado!

**Comment by pedrormonteiro** [comment]
Enviado!

**Comment by daniro-san** [comment]
Enviado!

**Comment by allisonsampaio** [comment]
Enviado!

**Comment by heliomsolivas** [comment]
Já fechou essa vaga? Pessoal que mandou obteve resposta?

**Comment by manoelangelo** [comment]
A vaga já fechou?

**Comment by brunooomelo** [comment]
@heliomsolivas não recebi nenhuma resposta.

**Comment by netojose** [comment]
Vish, se o cara que enviou no dia que abriu, não recebeu... Imagina agora 👅

**Comment by iassia** [comment]
Pessoal, os currículos foram recebidos e avaliados!
O envio do cv foi confirmado automaticamente para todos via e-mail.
As pessoas selecionados já estão passando pelo processo.
