### ISSUE TITLE
[Poços de Caldas - MG] - Desenvolvedoras(es) JavaScript no Ateliê de Software

### ISSUE THREAD

**Issue by highlabs** [frontendbr/vagas#1728]
## Descrição da vaga

Estamos procurando desenvolvedoras(es) JavaScript com experiência. Para trabalhar na nossa empresa em Poços de Caldas.

## Local

Escritório - Poços de Caldas - MG

## Benefícios

- Plano de saúde (Unimed ou Climepe);
- Plano odontológico (Uniodonto ou Climepe);
- Seguro de vida;
- Vale refeição e/ou alimentação (R$21,35 /dia);
- Vale transporte (se necessário);
- Participação nos lucros e resultados de forma diferenciada;
- Horário e local de trabalho flexíveis (alinhado com a equipe);
- Liberdade para programar suas férias (alinhado com a equipe);
- Cartão do programa Descubra Descontos dos Poços CVB;
- SESC - 50% de desconto em hospedagem e diversas atividades;
- Ajuda de custo para participação em eventos (alinhado com a equipe);
- Ajuda de custo para cursos e compras de livros (alinhado com a equipe);

#### Diferenciais

- Happy hour com os coleguinhas;
- Guloseimas sempre disponíveis;
- Ambiente descontraído;
- Gestão horizontal (todas as decisões são tomadas pela equipe, aqui ninguém é chefe de ninguém.);
- Somos adeptos a métodos ágeis;

## Requisitos

**Obrigatórios:**
- HTML5/CSS3;
- JavaScript (ES6/Babel);
- Webpack;
- React / Redux;

**Desejáveis:**
- TypeScript;
- TDD;
- Ruby on Rails ;
- Experiência em projetos open-source;
- Vivência em ambiente ágeis (Scrum, Kanban, XP, etc);

**Diferenciais:**
- projetos open-source;
- Boa comunicação (aqui conversamos muito entre nós e com o cliente);

## Contratação

CLT

## Nossa empresa

O Ateliê de Software faz parte do grupo Webgoal e atua no mercado brasileiro de software desde 2011. O nosso propósito é desenvolver software com alta qualidade técnica e rápido retorno sobre o investimento para os nossos clientes. Para isso, usamos Scrum para fazer a gestão ágil de projetos, práticas ágeis de engenharia de software da eXtreme Programming e Kanban para visualização e controle do fluxo de trabalho. Também utilizamos técnicas de Lean UX, Design Thinking e Customer Development para criar produtos e novos negócios. Muito além da programação, também ajudamos nossos clientes na criação de estratégias de negócios e sua execução através da implementação de produtos digitais.

## Como se candidatar

Para se candidatas, decifre o código abaixo:

`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXByZXNhIjoiQXRlbGnDqiBkZSBTb2Z0d2FyZSIsInZhZ2FfcGFyYSI6IkZyb250LWVuZC9FbmdlbmhlaXJvIEphdmFTY3JpcHQiLCJ0ZXN0ZSI6Imh0dHBzOi8vcGFzdGViaW4uY29tL3ozRUY2anMxIn0.7TWgFBPk77RZ9QqNf2EOBBsRTSmC6mzOf86KAGLP1vg`

Dica: 
```
{
  "alg": "HS256",
  "typ": "JWT"
}
```
## Tempo médio de feedbacks

Estamos selecionando candidatos para projetos futuros, por isso nosso processo de contratação só iniciará durante o mês de Fevereiro (2019).

## Labels

- Alocado
- CLT
- PJ
- Pleno
- Sênior

**Comment by MayaraRMA** [comment]
Muito legal o desafio para se candidatar :)
Pode ser remoto?

**Comment by ReactGirl** [comment]
{
 "empresa": "Ateliê de Software",
 "vaga_para": "Front-end/Engenheiro JavaScript",
 "teste": "https://pastebin.com/z3EF6js1"
}

**Comment by highlabs** [comment]
Olá @ReactGirl , você acabou de estragar nosso teste. :)

De qualquer forma vou fechar a issue e vamos seguir com o processo de seleção de candidatos...

**Comment by renan-barreiro** [comment]
Sinceramente não entendo o propósito de alguém que fica entrando em várias issues\vagas pra cornetar e até atrapalhar o teste, como foi o caso nessa vaga aqui...

Se não acha a vaga legal, é só não se candidatar. Vai acabar espantando quem quer postar vaga e atrapalhar a comunidade toda.

**Comment by antoniotex** [comment]
Pior que teve vezes que ela tinha razão em reclamar.

Na outra grande maioria foi só corneta mesmo. Nesse aqui então, pisou feio na bola rs

Ótimo teste Ateliê do Software, faz prestar atenção nas coisas.

**Comment by danielkmx** [comment]
Eu voto por Ban nesse @ReactGirl , só fica dando resposta de troll

Em seg, 4 de fev de 2019 às 17:40, Antonio Carlos <notifications@github.com>
escreveu:

**Comment by ReactGirl** [comment]
Isso era um teste? Desculpe-me. Achei que fosse uma pegadinha.
