### ISSUE TITLE
[São Paulo] Desenvolvedor(a) Front-End Estágio / Junior

### ISSUE THREAD

**Issue by mangar** [frontendbr/vagas#173]
## Descrição da vaga

Olá!

somos uma agencia de publicidade jovem e estamos procurando novos programadores (Estágio ou Junior) que possamos ter uma colaboração mútua.

Temos vários projetos bastante interessantes, alguns deles locais, aqui no Brasil, outros projetos são para clientes de fora do Brasil

Utilizamos ferramentas que nos proporcione velocidade na comunicação e desenvolvimento (Slack, Jira, Browserstack).
Geralmente nossos programadores utilizam um Mac e você escolhe as ferramentas (Atom, Sublime, TextMate, etc...)

Se você acha que pode nos ajudar, mande um email e vamos bater um papo.

## Local

Nosso escritório fica na zona sul, São Paulo.
O programador deverá ficar alocado no nosso escritório.

## Benefícios

- iMac
- frigobar sempre cheio :P

## Requisitos

**Obrigatórios:**
- Alguma experiencia em desenvolvimento frontend.
- Javascript (estamos utilizando AngularJS, mas Reactive e Angular2 estão nos nossos planos)

**Desejáveis:**
- conhecimentos em ruby on rails
- conhecimentos em Docker

**Diferenciais:**
Importante que você tenha vontade de aprender. Todos aqui no time tem a mesma vibe, ninguem sabe de tudo e todos estamos prontos a aprender.

## Contratação

CLT ou PJ

## Nossa empresa

Somos uma agencia de publicidade jovem aqui na zona sul de São Paulo. Temos projetos bem interessantes interno e externo.

## Como se candidatar

Por favor envie um email para jarvis@starkand.co com seu CV anexado - enviar no assunto: Vaga Front Estagio ou Junior

**Comment by lucasalmeida92** [comment]
Enviado! ;]

**Comment by danlaurent** [comment]
Enviado!

**Comment by gabrielrunescape** [comment]
Enviado! :grimacing:

**Comment by brunooomelo** [comment]
Enviado e no aguardo :>

**Comment by marcusberger** [comment]
Vaga aberta ainda?

**Comment by gabriel-brito** [comment]
Enviado !

**Comment by leonard9** [comment]
Vaga ainda aberta?

**Comment by nayarocha** [comment]
a vaga ainda esta aberta?

**Comment by LFeh** [comment]
@mangar A vaga já foi preenchida?

**Comment by vinirossi** [comment]
@mangar Vaga aberta ainda?

**Comment by willrsousa94** [comment]
@mangar Ainda estão contratando?
