### ISSUE TITLE
[São Paulo] FullStack Developer - Programmer's

### ISSUE THREAD

**Issue by ProgrammersRecrutamento** [frontendbr/vagas#1733]
Requisitos: 
• Sólidos conhecimentos com HTML5, CSS3, C #, MSSQL, WebAPI, React / Redux, Bootstrap;
• Tradução de mock-ups e wireframes de designer para o código front-end da web;
• Experiência em desenvolvimento para aplicativos móveis e de desktop. 
• Experiência em criar APIs e uso de notificações push.
• Compreensão e implementação de segurança e proteção de dados.
• Conhecimento prático de ferramentas de controle de versão de código, como DevOps do TFS / VSTS / Azure.
Desejável:
• Experiência com conectividade SAP ERP (SAP PI e / ou NCO);
• Preferir a experiência com metodologias ágeis / devop;
• Prefiro Windows Forms, Crystal Reports, ClickOnce.
Processos:
• Manter a qualidade e garanta a capacidade de resposta dos aplicativos.
• Colaborar com o restante da equipe para projetar e lançar novos recursos.
• Manter a integridade e organização do código.

## Local

São Paulo, Campinas, Araraquara ou Matão. 

## Benefícios

- Plano de saúde
- Plano Odontológico 
- Seguro de vida
- VR
- Auxílio creche
- PPR
- Gympass

**Obrigatórios:**
 Sólida experiência com React e Redux,

## Contratação

CLT

## Nossa empresa

A Programmer´s® está presente no mercado de soluções de Tecnologia da Informação desde 1989, construindo uma relação de confiança e credibilidade com seus clientes, nos diversos segmentos do mercado empresarial. Sua missão é alavancar os negócios de seus clientes através da utilização das melhores tecnologias e metodologias disponíveis no âmbito das soluções em plataforma Microsoft. 
Com sede em São Paulo a Programmer’s possui fábricas de software em Campinas e Matão-SP, além de presença no Rio de Janeiro e subsidiária na Philadelphia, USA.
Possuimos certificação Gold Certified Partner, o nível de parceria mais alto da Microsoft, a qual atesta a qualidade dos serviços prestados aos seus clientes.

## Como se candidatar

Por favor envie um email para ana.fraga@programmers.com.br com seu CV anexado - enviar no assunto: Vaga Front end

**Comment by Mendrone** [comment]
@ProgrammersRecrutamento Coloquei os labels baseado na descrição da vaga. Peço, por favor, atenção em seguir o template proposto pra facilitar o nosso trabalho e manter o repositório organizado e util para empresas e candidatos.
