### ISSUE TITLE
[Rio de Janeiro] Front-end developer (Pleno/Senior) na Profite

### ISSUE THREAD

**Issue by helioricardo** [frontendbr/vagas#1735]
## Descrição da vaga

Você conhece a Profite? Nós somos a maior agência implantadora de e-commerce do Brasil. Temos como clientes grandes nomes, tais como: O Boticário, Tim, C&A, Shopfácil, Electrolux, Havaianas, Mizuno entre outros.

Estamos procurando um(a) Desenvolvedor(a) Front-end Pleno, com sólidos conhecimentos em HTML, CSS e Javascript para projetar interfaces e entregar a melhor experiência para os consumidores visando sempre a otimização do código e agilidade no desenvolvimento.

O perfil que procuramos é de uma pessoa que seja atenta aos detalhes e capaz de desenvolver soluções escaláveis. De fácil relacionamento, organizado(a) e comprometido(a) com prazos e qualidade das entregas. Confira abaixo mais informações da vaga.

## Local

Escritório, Rio de Janeiro - Centro

## Benefícios

- Vale-transporte;
- Vale-refeição;
- Vale-alimentação;
- Plano de saúde e odontológico;

#### Diferenciais

- Folga de aniversário
- Chopp grátis, Nerfs, Ping Pong, Totó, TGIM e a estrutura irada do WeWork com vista para a Marina da Glória
- Plano de Carreira
- Cursos (Udemy e outros)

## Requisitos

**Obrigatórios:**
- Html5;
- Javascript, jquery;
- Git;
- Grunt, Gulp e/ou webpack;
- Css/Sass;
- Sites responsivos;
- Cross-browser (IE11+);
- Iniciativa, criatividade e colaboração;
- Boas práticas: reutilização de código, semântica, organização, performance.
- Experiência com CMS e/ou Plataformas de e-commerce (Wordpress, Drupal, Joomla, Magento, Tray Commerce, etc)

**Desejáveis:**
- Conhecimento/Experiência em Vtex
- React

**Diferenciais:**
- Projetos opensource
- NodeJS

## Contratação

CLT

## Como se candidatar

Via Trampos - https://trampos.co/oportunidades/144854

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.

## Labels

- CLT
- Pleno
- Sênior
- RJ

**Comment by helioricardo** [comment]
Salve,

Tiver grande proeficiencia em JS, qualquer CMS e pixel perfect, podemos conversar.


Abs
Em 30 de jan de 2019 5:30 AM -0200, renanlbl <notifications@github.com> escreveu:

**Comment by fernandoperigolo** [comment]
Oi, @helioricardo. Tem alguém de Petrópolis trabalhando aí com vocês?

**Comment by helioricardo** [comment]
Salve. Tem sim, mas mora no Rio e só vai esporadicamente a Petro...

Em qua, 30 de jan de 2019 às 21:39, Luiz Fernando de Souza Filho <
notifications@github.com> escreveu:

**Comment by fernandoperigolo** [comment]
@helioricardo , entendi. Tem uma turma de Petrópolis que vai trabalhar no Rio todos os dias, por isso perguntei, só sondando aqui hhehehe
