### ISSUE TITLE
[Curitiba PR] Front-End Developer na Celero

### ISSUE THREAD

**Issue by kyviacarvalho** [frontendbr/vagas#1736]
## Descrição da vaga

Buscamos um Front-End Developer para nosso time!
Você irá participar do planejamento, desenvolver e implementar novas funcionalidades em nossa plataforma. Temos um grande caminho pela frente e você terá bastante liberdade para desenvolver. Você trabalhará com Bootstrap, Angular 7 e Typescript no desenvolvimento de aplicações em um ambiente que valoriza as boas práticas de programação (ex. testes automatizados, unitários, code review, etc) e metodologias de desenvolvimento ágil.

## Local

Remoto ou Escritório, Curitiba - Bigorrilho

## Benefícios

- Vale Transporte ou Vale Combustível, caso trabalhe no escritório
- Ajuda de custo, caso trabalhe remoto
- VR de R$20 ao dia

## Requisitos

**Obrigatórios:**

2+ anos de experiência de mercado com Bootstrap, Angular 2+ e Typescript;
Ter autonomia e pró-atividade;
Conhecimentos em HTML5, CSS3 e Javascript;
Experiência anterior com API's RESTful com resposta em JSON;
Experiência com Git para versionamento de código;
Inglês básico (leitura e escrita);

**Diferenciais:**

Cursando ou formação em Ciências da Computação ou equivalente;
Ter espírito empreendedor;
Ser autodidata;
Conhecer o ambiente de start-ups;
Experiência na área de gestão financeira;

## Contratação

CLT

## Nossa empresa

Somos uma Fintech especializada em simplificar os processos financeiros.
Nosso propósito é facilitar a vida de empresas, revolucionando a maneira de gerir suas finanças.
Como nós fazemos isso? Aliando tecnologia de ponta e a expertise de nosso time de especialistas!
Procuramos pessoas com atitude para fazer parte de nosso time. A experiência é importante, mas o principal é a vontade de fazer a diferença!

## Como se candidatar

Por favor envie um e-mail para kyvia.carvalho@celero.com.br com seu CV anexado e pretensão salarial - enviar no assunto: Vaga Front-End Developer - Github/FrontendBR

## Tempo médio de feedbacks

Enviamos feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: kyvia.carvalho@celero.com.br

## Labels

- Alocado
- CLT
- Pleno
- Sênior
- Remoto

**Comment by kyviacarvalho** [comment]
> @kyviacarvalho a senioridade é imprescindivel? 😔

Oi @thiagofrancisquete, nesta vaga em específico sim, precisamos de alguém com o tempo de experiência descrito. Mas se não for o seu caso e quiser enviar seu cv para futuras vagas pode ficar a vontade.

**Comment by thiagofrancisquete** [comment]
Pode deixar @kyviacarvalho, obrigado, quando tiver vagas para jr estou a disposição :wink: :relieved:

**Comment by danielswater** [comment]
Enviado

**Comment by kyviacarvalho** [comment]
**Vaga preenchida!**

Obrigada a todos que enviaram currículo! A vaga em questão foi preenchida hoje.
Os currículos enviados continuarão em nosso banco.
