### ISSUE TITLE
[Uberlândia/MG] Front-End Developer - Softbox

### ISSUE THREAD

**Issue by milagloria** [frontendbr/vagas#1738]
Descrição das atividades:
Atuar na codificação front-end do sistema conforme arquitetura e padrão de desenvolvimento definidos.

Formação necessária:
Superior Completo dos cursos de Sistemas de Informação, Ciências da Computação ou afins.

Requisitos:
Conhecimento em Xhtml, CSS, Javascript e Jquery.

Local: Softbox - Soluções Inteligentes em TI - Uberlândia/MG

Tipo de Contrato: CLT

Como se candidatar
acesse o link: [https://softbox.com.br/job/desenvolvedor-front-end/](url)

Labels

- Alocado

- CLT

**Comment by Mendrone** [comment]
@milagloria Poderia ajustar o conteúdo, por favor?

- incluir as labels
- ajustar o títulos
- incluir nome da empresa
- incluir tipo de contrato (CLT, PJ, estágio) 

Vou manter a vaga fechada até que os ajustes sejam feitos
