### ISSUE TITLE
[São Paulo] Desenvolvedor(a) Front-End - TV Globo - G1

### ISSUE THREAD

**Issue by robanquieri** [frontendbr/vagas#174]
## Descrição da vaga

Estamos à procura de um desenvolvedor Front-End para fazer parte do nosso time em São Paulo.

Você será responsável pelo desenvolvimento de sistemas que exigem soluções inovadoras. Deverá compreender as necessidades do núcleo de jornalistas, recomendar e implementar soluções que seguem as melhores práticas.

Você vai trabalhar em colaboração com a nossa equipe de design e colaborar com os nossos jornalistas em projetos que afetam a vida de milhões de pessoas no Brasil. Se você é uma pessoa que gosta de desafios, se você sonha em fazer parte de uma grande empresa, este emprego pode ser para você.

Buscamos um profissional com Formação Superior em Informática, TI, Ciências da Computação, Engenharia da Computação, Análise de Sistemas ou áreas afim. Conhecimentos do Pacote Adobe, Photoshop dentre outros softwares é importante.

## Local
Presencial, São Paulo (Zona sul)

## Requisitos

**Obrigatórios:**
- Domínio em JavaScript, HTML e CSS
- Capacidade de escrever código eficiente, escalável e reutilizável
- Conhecimento em um ou mais frameworks JavaScript (React, Angular, etc.)
- Conhecimento em APIs Rest
- Conhecimento dos princípios de design ágil e adaptativo, traduzindo-se em modelos fluídos e responsivos
- Conhecimento em desenvolvimento multi-plataforma (Chrome, Firefox, Safari, IE, etc.)
- Conhecimento de melhores práticas de SEO
- Experiência em pré-processadores CSS (Sass, Less, Stylus)
- Aderência aos padrões web e boas práticas para a redução do tempo de carregamento e acessibilidade
- Experiência em controle de versão, como Git, Bitbucket
- Foco no usuário final, por meio de código acessível e eficiente
- Habilidades de comunicação verbal e escrita, capacidade de interagir com um grupo diversificado de pessoas
- Habilidades de gestão de tempo em projeto
- Habilidade para definir prazo de entrega

**Desejáveis:**
- Conhecimento básico em PHP ou NodeJS.

## Contratação

CLT

## Nossa empresa

Fazer parte da vida das pessoas. Estar com elas onde quer que elas estejam. Informar. Surpreender. Comunicar. Ouvir para conectar. Interagir e conversar com a audiência. Apurar e investigar para compartilhar. Entreter para encantar. Educar para desenvolver. Inovar. Esses são alguns dos compromissos que escrevem a história da Globo. 

Com a estrutura de cinco emissoras próprias e 119 afiliadas, a emissora renova esse desafio diário desde 1965, com padrões de qualidade e de criatividade reconhecidos no Brasil e no exterior. São mais de 12 mil funcionários diretos e milhares de indiretos, produzindo por ano 3.000 horas de jornalismo e 2.500 horas de entretenimento – como se fossem feitos 1.250 filmes de longa-metragem todos os anos. Tudo isso proporciona à Globo o título de uma das maiores redes de televisão do mundo e uma coleção de prêmios internacionais. Ao todo, a Globo já recebeu 14 prêmios Emmy®, entre eles, os de Melhor Telenovela (Caminho das Índias, Laços de Sangue, O Astro, Lado a Lado, Joia Rara e Império), Melhor Série de Humor (A Mulher Invisível), Melhor Atriz (Fernanda Montenegro, por Dona Picucha, no especial ‘Doce de Mãe’), Melhor Reportagem (Jornal Nacional) e Melhor Comédia (Doce de Mãe) 

Os programas da Globo são assistidos em 190 países, e o canal internacional distribuído por diversas operadoras ao redor do mundo. Com participação na audiência em cerca de 40% (no horário das 7h às 24h), a Globo é líder no mercado brasileiro, e também na Internet, com seus portais de notícias (G1), esportes (Globoesporte.com) e entretenimento. Atenta às evoluções tecnológicas e de comportamento, tem investido em soluções que a aproximam cada vez mais do público – como o Globo Play, a plataforma de vídeo on demand que disponibiliza a sua programação em múltiplos devices.

## Como se candidatar

Por favor envie um email para rogerio.banquieri@tvglobo.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

**Comment by JoaoAntonioMaruti** [comment]
Enviado

**Comment by LFeh** [comment]
@robanquieri Qual o nivel pra eu botar a label. 

:)

**Comment by robanquieri** [comment]
@LFeh O nível é pleno. Obrigado :)

**Comment by LFeh** [comment]
Fechou @robanquieri ?

**Comment by robanquieri** [comment]
Fechamos sim @LFeh

**Comment by LFeh** [comment]
Aeee, foi por aqui?

**Comment by robanquieri** [comment]
Não, mas um dos finalistas veio daqui.
