### ISSUE TITLE
[São Paulo, SP] Front End Developer JS / CSS na TutorMundi

### ISSUE THREAD

**Issue by namenotrequired** [frontendbr/vagas#1742]
## Descrição da vaga

Estamos buscando desenvolvedores Front End para uma startup que acabou de receber R$1 milhão Seed Investment. Acabamos de nos mudar de Florianópolis para um lindo escritório em Vila Olímpia, São Paulo. A startup no entanto, foi fundada em Silicon Valley e o desenvolvedor terá ações dessa empresa matriz. 

Esses desenvolvedores não precisam ter muita experiência, mas precisam ser motivados por trabalhar numa startup. Aprendizado rápido é tudo.

Nós acreditamos que é a hora certa para entrar na empresa, pois ainda somos muito pequenos e já temos usuários pagantes que amam nosso produto.

Para aqueles que gostam de ver os perfis dos futuros colegas de trabalho, hoje somos 6:

https://www.linkedin.com/in/raphaelrrc/
https://www.linkedin.com/in/otsukajulia/
https://www.linkedin.com/in/bart-sturm-26694990/
https://www.linkedin.com/in/ericchinen/
https://www.linkedin.com/in/thomaspmach/
https://www.linkedin.com/in/matheusmonteiromourao/

## Local

São Paulo, SP (bairro: Vila Olímpia)

## Benefícios

Ações da empresa em Silicon Valley

#### Diferenciais

- Horário flexível
- Equipe pequena e empolgada
- Empresa que realmente investe nas pessoas

## Requisitos

**Obrigatórios:**
- JavaScript
- HTML
- CSS

**Desejáveis:**
- Design UI / UX
- SCSS
- React ou Vue
- Meteor ou Cordova

## Contratação

CLT

## Nossa empresa

https://www.tutormundi.com/

O sistema funciona como WhatsApp para educação. Alunos do ensino médio com uma dúvida simplesmente tiram uma foto da questão. Em menos de 5 minutos um universitário das melhores universidades aparece e começa a ensinar via chat e imagens como se fosse um WhatsApp. 

Temos centenas usuários pagantes, dos quais muitos acessam o aplicativo semanalmente. No último mês esclarecemos quase 3 mil dúvidas de alunos. Já temos parcerias com 10 escolas.

A empresa realmente investe nas pessoas, por exemplo, eu sou holandês e a empresa arrumou um visto de trabalho para mim. Também apoiou nosso designer a passar 6 meses estudando em Stanford.

## Como se candidatar

Por favor envie um email para bart@tutormundi.com com CV e motivação em anexo.

## Labels

- Presencial
- CLT
- Júnior
- Pleno
- Sênior

**Comment by igorqueiros** [comment]
@namenotrequired Ainda tem vagas abertas para Júnior?

**Comment by Lftho** [comment]
Continua com vagas aberta, para desenvolver junior  ? @namenotrequired
