### ISSUE TITLE
K2 Partnering - dev frontend (JR, PL e SR)

### ISSUE THREAD

**Issue by natashacosta** [frontendbr/vagas#1743]
Bom dia, pessoal!
Tudo bem? 👍 

Sou recrutadora na K2, multinacional britânica - tudo começou em 97, mais de 20 anos!! - que hj já está em 19 países, englobando todos os continentes. Nossa prioridade é atender nossos consultores e clientes com excelência.

Temos muitas vagas de frontend, seja em clientes de grande porte, quanto startups com ideias inovadoras.  Todas, em projeto bem legais que exigem perfis diferenciados! =D

Ficou interessado? Me procura!!

E se tiver amigos devs que buscam novos desafios, pode compartilhar meu contato com todos! rs

**Natasha Costa**
ncosta@k2partner1ng
19 98208-1234 (whatsapp)
https://www.linkedin.com/in/natashacosta/
![k2 partnering](https://user-images.githubusercontent.com/29047673/52051845-e7934f80-253b-11e9-93f1-23d7f6913142.jpg)

**Comment by Mendrone** [comment]
@natashacosta Pra manter o repositório relevante e util pra empresas e candidatos nos pedimos a todos que respeitem o template proposto, o título deve indicar o local da vaga, as labels são necessárias, o modelo de contratação também (PJ, CLT, estágio).

Manterei a vaga fechada até que o template seja atualizado.
