### ISSUE TITLE
[São Paulo - SP, Campinas - SP, Maringá - PR] Front End na MATERA

### ISSUE THREAD

**Issue by gss-patricia** [frontendbr/vagas#1744]
## Descrição da vaga

Precisamos de front-end developers Pl / Sr para a MATERA Systems, para atuar com análise e desenvolvimento de Front-end em projetos para clientes internos e externos.

## Local

Campinas - SP e região.
São Paulo - SP e região.
Maringá - PR e região

## Benefícios

- Horário de trabalho flexível (40 h semanais);
- Pacote de Benefícios Flexíveis + PLR (Plano de participação nos lucros e resultados).e

## Requisitos

**Obrigatórios:**
- Conhecimento em pelo menos um dos frameworks: Angular, React ou Vue; 
- Experiência com XML/HTML/CSS/JavaScript; 
- Flexibilidade para se adaptar a novas tecnologias; 
- Disponibilidade para atuar 40 horas semanais; 
- Disponibilidade para eventuais viagens (nacionais e internacionais).

**Desejáveis:**
- NodeJS, Testes Unitários; 
- Familiaridade com SVN, Git e com ferramentas como Jira e Stash; 
- Conhecimento em Scrum

## Contratação

CLT full.

## Nossa empresa

A MATERA Systems, desde 1987, atua como fornecedora de soluções e serviços de TI para o mercado financeiro e corporativo, além de realizar o desenvolvimento de aplicativos e projetos. São marcas registradas da empresa investir constantemente em inovação e capacitação de seus profissionais e aliar a excelência técnica ao conhecimento de negócios. Possui mais de 400 profissionais e desde 2008 está no ranking da GPTW. Sedes: Campinas­ - SP, São Paulo - ­SP, Niterói - ­RJ e Maringá­ - PR

## Como se candidatar

Por favor envie um email para aline.miron@matera.com com seu CV anexado - enviar no assunto: Vaga Front-End.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: aline.miron@matera.com

## Labels

- Alocado
- CLT
- Pleno
- Sênior

**Comment by Yagasakii** [comment]
Enviado!
