### ISSUE TITLE
[Belo Horizonte/MG] Front-End Developer na CADOMA

### ISSUE THREAD

**Issue by megandavulpi** [frontendbr/vagas#1745]
### Sobre a empresa: Cadoma

Somos uma empresa do ramo da piscicultura. A nossa missão é automatizar a criação de peixes deixando-a mais tecnológica e viável. Para isso, prestamos consultoria e desenvolvemos produtos inéditos no mercado da aquicultura.

### Descrição: O que você fará na Cadoma?

Estamos crescendo, saindo da etapa de projeto e indo pro mercado com muita força. Precisamos de alguém que tenha essa gana de conquistar um mercado cheio de possibilidades. Você irá implementar soluções para nosso produto carro chefe. É uma aventura com muitas possibilidade. Você conviverá em um ambiente rodeado de tecnologias, impressoras 3D trabalhando a todo vapor, experimentos em Machine Learning e uma equipe para te mostrar um pouco mais do mundo do BackEnd. Quer um mundo melhor que esse? Não tem.

### Requisitos que você precisa atender:

Experiência com JavaScript, Html, CSS;
Ser Pró-ativo;
Ter Sangue nos olhos;
Ter maturidade em entregas e trabalho em equipe;
Ter sede por conhecimento.

### Diferenciais que vão contar pontos para você:

Criar pequenas soluções, telas e funcionalidades em REACT;
Saber ANGULAR, temos um sistema que precisa de atenção e manutenção;
Ter conhecimento sobre Scrum;
Querer estudar e aprender!

### Oferecemos um tudo para você crescer:

Salário compatível com o mercado;
Clima descontraído;
No dress code;
Possibilidade de HomeOffice 2 ou 3 vezes por semana.
Fazer parte de uma equipe foda e com grande possibilidade de crescimento e conhecimento.

### Seus desafios serão:

Programar, codificar e testar os projetos criados;
Ajudar a idealizar novos projetos;
Acompanhamento de entregas;
Auxiliar na criação de uma equipe de alta performance.

### Labels:

Alocado
Senior

### Candidatar: http://bit.ly/cadomafront_github

**Comment by mja-maia** [comment]
Enviado!

**Comment by ReactGirl** [comment]
Gostaria de saber o que significaria o requisito "Ter Sangue nos olhos". Ou seja, é preciso gostar de fumar uma erva ou coisa do tipo?
