### ISSUE TITLE
[Remoto] React Native Engineer na Passfolio

### ISSUE THREAD

**Issue by vnvs** [frontendbr/vagas#1749]
## Descrição da vaga

Join Passfolio to help expand the global economy by using blockchain technology to connect 2 billion un(der)banked people that have a cell phone to the global economy and facilitate nearly instant international trade and commerce that was previously impossible.

We are looking for an experienced React Native (plus for Firebase experience) engineer to join our mobile app development team. You will have significant responsibility and ability to shape the Passfolio mobile app and products.

You will work very closely with the team in defining the development roadmap and making it a reality.

You will play a key role in architecting the Firebase data schema, designing the in-app data flow (Redux + Redux Saga), test code setup, continuous integration infrastructure with automated app builds and deployment, key/certificate management, and app deployment process.

## Requisitos

**Obrigatórios:**
- React Native, Redux.
- English fluency

**Desejáveis:**
- Firebase.

## Nossa empresa

We are a small team that moves very quickly. There is no bureaucracy. Good ideas get vetted and implemented quickly. We are data driven but not dictated - sometimes the data is incorrect or does not show everything. We iterate quickly to find the best solution and generally move fast and are ok with breaking things.

## Como se candidatar

Send an e-mail with your resume in english to careers@passfolioapp.com

## Labels

- Remoto
- Sênior

**Comment by MacgyverMartins** [comment]
@vnvs  Is this position still available?

**Comment by vnvs** [comment]
It is, Yes!
