### ISSUE TITLE
[São Paulo] Desenvolvedor(a) Front-End - Emprego Ligado

### ISSUE THREAD

**Issue by efreesen** [frontendbr/vagas#175]
## Descrição da vaga

A **Emprego Ligado** utiliza a tecnologia para melhorar a forma como as pessoas e as empresas se conectam e estabelecem relações duradouras no mercado de trabalho. Esta vaga é para trabalhar como **Frontend Developer** em um produto existente e evoluindo.

Buscamos profissionais apaixonados por desenvolvimento Frontend, que se orgulham do código que produzem, lidem bem com pessoas, e que tragam energia positiva para a nossa equipe.

## Local

São Paulo - Vila Madalena

## Benefícios

- VT/VR
- Plano de Saúde Sul América
- Gympass
- Frutas a vontade

## Requisitos

**Obrigatórios:**
  - Ser apaixonado por desenvolvimento e tecnologia;
  - Ter facilidade de trabalhar dentro de times multi-disciplinares; 
  - Ter boa capacidade de abstração;
  - Precisa desde o começo se preocupar com clean code (código simples, estruturado, não macarrônico, com testes unitários e melhoria contínua);
  - Oh, I almost forgot, you will read and write english a lot, then you do not need to be fluent, but your code, Pull Requests and other discussions should be done in english;

**Desejáveis:**
  - ES6, React, Redux, SASS, Webpack; 
  - Ter experiência com interfaces responsivas;
  - Ter boas noções de UX;
  - Conhecimentos de práticas de XP (TDD, Pair-Programming, Refactoring, Continuous Integration, etc);

**Diferenciais:**
  - Vivência em times com desenvolvimento ágil (Scrum, Kanban);
  - Ter experiência com SPA;
  - React, Redux;
  - Experiência com documentação de código (JSDoc ou similar);

## Contratação

CLT

## Nossa empresa

A Emprego Ligado preza por um ambiente agradável, com mesa repleta de frutas, puffs, Gympass, sem contar que estamos no coração da Vila Madalena 😄 . Somos pessoas comprometidas com a qualidade e o resultado final. Gostamos de ver nosso produto sendo um diferencial na conquista de emprego, produtividade e qualidade de vida de nossos clientes.

## Como se candidatar

Caso tenha se interessado pela vaga, entre em contato através do email vagas@empregoligado.com.br, nos envie seu perfil do LinkedIn e do GitHub que vamos marcar um dia para você vir aqui tomar um café conosco e nos conhecer!

**Comment by rafaeljesus** [comment]
@LFeh vc poderia colocar o label de Senior e Junior tbm? Um abraço, ahh eu trabalho com o @efreesen 😉

**Comment by LFeh** [comment]
Done!

**Comment by Rogerfm** [comment]
Email enviado :)

**Comment by brunooomelo** [comment]
Email enviado com sucesso !

**Comment by fredericksilva** [comment]
Mestre @LFeh, pode adicionar a label Remote?

**Comment by HaluDeCassia** [comment]
Ótima vaga! Espero que consiga. E-mail enviado 😊

**Comment by HaluDeCassia** [comment]
Ótima vaga! Espero que consiga. E-mail enviado 😊

**Comment by lucasaugustofrontend** [comment]
Email enviado
