### ISSUE TITLE
[São Paulo] Front-End Developer na [iBabysite]

### ISSUE THREAD

**Issue by e-ribeiro** [frontendbr/vagas#1750]
## Descrição da vaga

Precisamos de um(x) Front-End que ama programar, tenha vontade de aprender e ensinar, nosso produto é incrível e tem diversas possibilidades de expansão. Gostamos de tecnologia, hype ou não nosso negócio é entregar o melhor para nossos clientes.

Se você é gente boa e gosta de uma boa conversa, venha tomar um café.

O que usamos aqui:
- Angular 6x
- Sass
- Html
- Golang
- Mongodb
- AWS como infra

## Local

Escritório, São Paulo - Na região da Av. Luis Carlos Berrini

## Benefícios

- 13 salário
- férias remunerada

#### Diferenciais

- Ambiente agradável
- Aqui você tem voz
- Processo flexível

## Requisitos

**Obrigatórios:**
- 4 anos de experiência como front-end
- Sólido conhecimento em mobile first
- Sólido conhecimento em Angular > 2.0

**Desejáveis:**
- Conhecimentos em CD e CI
- Que tenha lido Clean Code

**Diferenciais:**
- projetos opensource

## Contratação

PJ a combinar

## Nossa empresa

Aqui na iBabysite somos focados em resolver problemas que envolvem organização de eventos, desde presentes repetidos a contratação de DJ. Hoje trabalhamos focados nas mamães grávidas e crianças aniversariantes.

## Como se candidatar

Por favor envie um email para eder@ibabysite.com com seu CV anexado - enviar no assunto: Vaga Front-Ender

## Labels

- Alocado
- PJ
- Pleno
- Possibilidade de remoto
- Angular
- Sass

**Comment by ReactGirl** [comment]
Sobre o requisito, "Que tenha lido Clean Code", seria indispensável mesmo, uma vez que ele é Java Oriented? Nao seria mais interessantes literaturas como You Dont Know Js, The Pragmatic Programmer, Javascript the Good Parts, Eloquent Javascript, Secrets of the Javascript Ninja ou entao uma literatura mais classica como Design Patterns: Elements of Reusable Object-Oriented Software mais indicado para posicao?

**Comment by e-ribeiro** [comment]
Oi @ReactGirl obrigado pela sugestão!

Só pra esclarecer que não é um Must to Have e sim Nice to Have, uma vez que o interesse pelos estudos e conhecimento não deveriam ter barreiras de linguagem exemplo.

Como estamos sempre aprendendo, seria legal se você tiver interesse, claro, se candidatar e nos ajudar nessa jornada.

Obrigado mais uma vez!
