### ISSUE TITLE
[Joinville/SC] Front-End Developer na iTFLEX Tecnologia

### ISSUE THREAD

**Issue by rudineirk** [frontendbr/vagas#1751]
## Descrição da vaga

Nós trabalhamos com softwares de gerenciamento de infra-estrutura, com foco em firewalls e servidores de telefonia (PABX). A área de atuação da vaga é para o desenvolvimento das interfaces web do nosso produto, como dashboards, relatórios, gráficos e gerenciamento de serviços.

## Local

Alocado em Joinville/SC - Bairro América

## Benefícios

* Plano de saúde
* Ticket refeição
* Auxílio faculdade / Pós Graduação
* Incentivos a treinamentos, certificações e participação em eventos técnicos
* Sala de descompressão

### Perfil

- Gostar muito desenvolvimento de software e tecnologia
- Ser participativo na construção do produto, contribuindo com ideias para o negócio
- Ser dinâmico e inquieto, questionando dogmas e premissas, sempre procurando inovação
- Ter facilidade de trabalhar dentro de times multi-disciplinares
- Ter iniciativa para estudos
- Acompanhar tendências e inovações que surgem no mercado
- Escrever código limpo e legível
- Ter profunda preocupação com qualidade e performance
- Compreender a importância e praticar versionamento de código

### Requisitos

- Curso superior em Sistemas de Informação, Ciências da Computação ou Engenharia da computação
  - Curso superior em andamento para se candidatar a Analista de Desevolvimento Júnior
  - Curso superior concluído: requisito mínimo para se canditar a Analista de Desenvolvimento Pleno
- Ter experiência com programação em Javascript (VanillaJS)
- Domínio em html5 e css3
- Experiência em sites responsivos
- Entender o funcionamento do protocolo HTTP
- Desenvolvimento de aplicações javascript consultando APIs REST

### Diferenciais

- Conhecimentos de UX
- Conhecimentos de Web Design (utilizando Material Design)
- Conhecimento de ferramentas de criação de protótipos
- Conhecimento de ferramentas de edição de imagens
- Experiência com frameworks SPA (single page applications)
- Já ter utilizado/estar utilizando o framework VueJS
- Experiência em utilização do Git
- Experiência com métodologias ágeis
- Conhecimento de ferramentas de TDD de javascript (Jasmine, Mocha, etc)
- Usar/conhecer Linux

## Contratação

CLT

## Nossa empresa

A iTFLEX é experiente, ao mesmo tempo jovem e empreendedora, amamos o sistema Linux, mantemos pesquisas constantes em inovação para garantir a qualidade e flexibilidade de nossas soluções e serviços. Empresa com 13 Anos e mais de 1000 Projetos!

Acreditamos que juntos somos melhores, adoramos facilitar o dia a dia de nossos clientes, buscamos sempre fazer bem feito, com muito respeito ao nosso próximo. Nossos colaboradores tratam suas atividades como tarefas dadas a serem cumpridas e garantem o seu trabalho.

Estes são os nossos valores!

## Como se candidatar

Para se candidatar a vaga, deve ser respondido [este questionário](https://goo.gl/forms/xLrFI37TC4aRnMpj1) e enviar seu [currículo por meio deste link](https://www.itflex.com.br/vaga/desenvolvedor-front-end/).

## Labels

- Alocado
- CLT
- Júnior
- Pleno

**Comment by ReactGirl** [comment]
A descricao nao bate com o titulo:
Curso superior em andamento para se candidatar a Analista de Desevolvimento Júnior
Curso superior concluído: requisito mínimo para se canditar a Analista de Desenvolvimento Pleno

é para analista ou pra desenvolvedor front-end?
