### ISSUE TITLE
[São Paulo] Front-End Sr Developer na [BEYOND SOLUÇÕES]

### ISSUE THREAD

**Issue by FrancieleRosa** [frontendbr/vagas#1752]
## Front-End Sr Developer

Vagas para atuar como desenvolvedor em grandes instituições financeiras.

## São Paulo - SP

Escritório, São Paulo - Vila Olímpia
Escritório, São Paulo - Consolação
Escritório, São Paulo - Itaim Bibi

## Benefícios

- Plano de saúde / Plano Odontológico
- Seguro de vida
- VR de R$ 500,00/mês
- Vale Transporte ou Auxílio Mobilidade

## Requisitos
- HTML5
- CSS
- SASS
- LESS
- Angular 4

## Contratação

CLT + benefícios

## Nossa empresa
"Se fosse para abrir mais uma consultoria de outsourcing, era melhor a gente ficar em casa."​

Foi a partir deste pensamento que nós criamos a Beyond. Mais do que reduzir custos e diminuir a burocracia na contratação de profissionais de T.I. para empresas do setor financeiro, nós selecionamos, recrutamos e preparamos profissionais únicos.

Nosso maior diferencial é que não enxergamos profissionais como meros recursos, e sim, como pessoas reais, com sonhos, ambições e vontade de fazer o seu melhor. É com muita técnica, tecnologia e diálogo que nós entregamos talentos que fazem toda a diferença nos negócios dos nossos clientes. 

Em breve, teremos outras novidades para apresentar. Para ficar por dentro, acompanhe nossos posts no Linkedin ou entre em contato com a gente.

## Como se candidatar

Por favor envie um email para franciele@imaginebeyond.com.br com seu CV anexado - enviar no assunto: Vaga Frontend Sr - Angular

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: franciele@imaginebeyond.com.br

## Labels
- Alocado
- CLT
- Estágio
-Frontend
- Sênior

**Comment by ReactGirl** [comment]
Requisitos SASS e LESS.

**Comment by igorqueiros** [comment]
@FrancieleRosa tem vaga para Júnior? Tenho interesse
