### ISSUE TITLE
[Remoto] Front-End Developer Wordpress na Parceiro Programador

### ISSUE THREAD

**Issue by lincolnlemos** [frontendbr/vagas#1755]
## Descrição da vaga

Estou procurando um desenvolvedor WordPress de nível intermediário ou avançado com foco na criação de temas do zero, não é necessário PHP avançado. Se tu consegue criar um tema do zero, entende de responsivo, domina ACF e acredita que é bom no que faz, manda um alô com o que você achar que precisamos saber de você no vagas@partnerprogrammer.com

## Local

100% Remoto

## Benefícios

- Horários flexíveis
- Bônus por resultados

## Requisitos

**Obrigatórios:**
- Confiança em si mesmo

## Contratação

PJ, salário compatível com nível de experiência (1.8k~3k + bônus de resultados).

## Como se candidatar

Manda um alô com o que você achar que precisamos saber de você no vagas@partnerprogrammer.com

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

## Labels

- PJ
- Remoto

**Comment by rodineicosta** [comment]
Enviado.

**Comment by lincolnlemos** [comment]
Pessoal, agradecemos todos os interessados. 
Aos que aplicaram, iremos entrar em contato.
