### ISSUE TITLE
[São Carlos - SP] Front-End Developer @ Arquivei

### ISSUE THREAD

**Issue by toruticas** [frontendbr/vagas#1758]
# About Arquivei

Arquivei, a Brazilian startup, is looking for a Front-end Developer. Arquivei is an online platform that empowers companies with smart data from fiscal documents to fetch & analysis, offering process optimization through different company areas, customized reports, and Brazilian law compliance. Founded in São Carlos, the Brazilian capital of Technology, Arquivei uses the valuable data available in fiscal documents to deliver reliable information to its clients at low costs.

## Allocation City

São Carlos, São Paulo, Brazil

# Job Description

CLT, Full Time, Allocated

## You will be:

- Working with product team trying to understand business needs and provide a client with great user experience;
- Working with state-machine concepts to build reactive user interfaces;
- Migrating legacy platform to isomorphic/universal architecture.

## Desired Skills and Experience

- Be a true Developer
- 2 years+ of experience in Front-End
- Availability to work in São Carlos [Allocated]
- Have the spirit to work on a Startup

### Hard Skills:

- Data Structure
- Algorithm Time Complexity
- Javascript (ECMA next generation)
- HTML5 & CSS3
- ReactJS
- Unit Test
- Algorithm Design
- Clean Code Knowledge

### Soft Skills

- Advanced English 
- Critical Thinking
- Analytic Vision
- Have a curious and always learning mindset
- Be a team player, we foster a culture of collaboration and sharing
- Ready to rock-n-roll

## Our Stack / Differentials:

- ReactJS, Redux, ImmutableJS
- Jest, Eslint
- Webpack, Babel 7
- NodeJS, ExpressJS, NextJS
- Docker, Kubernetes, AWS, GCP
- Design System, Accessibility
- Code Pipeline (Bitbucket-Pipeline, CircleCI)
- Shell Script, Makefile, Linux

## We Provide

- Fun, laid-back environment in a fast-paced Startup.
- Competitive compensation based on your experience.
- Higher compensation for VR (and or) VA
- Career Path
- Feedback and brainstorming directly with the founders. No bureaucracy. No bullshit.
- Choice of tools
- Open-bar kitchen with coffee, fruits, coffee, candy (paçoca) and coffee. Breakfast at the office every day. Did we mention coffee?
- Medical and Dental Agreement
- Yoga
- Gympass
- Sports Consultancy
- Music Class
- Portuguese Writing Class

# How to Apply

https://arquivei.applytojob.com/apply/aPdUU3AxZl/FrontEnd-Developer

# Labels

- Alocado
- CLT
- Junior
- Pleno

**Comment by yuritoledo** [comment]
Ótimos benefícios, caraca. Parabéns.
