### ISSUE TITLE
[São Paulo] Desenvolvedor(a) Front-End Sênior - HomeRefill

### ISSUE THREAD

**Issue by keitoliveira** [frontendbr/vagas#176]
## Descrição da vaga
Procuramos por um desenvolvedor Front-End manjador dos paranauês para trabalhar nos principais projetos da HomeRefill onde participará do desenvolvimento de novas features assim como ajudará na melhoria das que já estão implementadas.

## Local
Vila Olímpia. Fácil acesso através da estação Vila Olímpia.

#### Obrigatórios:

- Sólidos conhecimentos em **HTML**; semântica e acessibilidade; template engine.
- Sólidos conhecimentos em **CSS** e pre-processador **SASS**; desenvolvimento de componentes reutilizáveis, boas práticas e confortável no desenvolvimento com metodologias **BEM** e **Atomic Design**; **Foundation**.
- Sólidos conhecimentos em **JavaScript**; lógica de programação, orientação a objeto, design patterns; Saber desenvolver componentes reutilizáveis; **jQuery**.
- Sólidos conhecimentos em **Git**.

#### Desejáveis:

- Conhecimento/experiência em **Twig**.
- Conhecimento/experiência em **PHP**.
- Inglês intermediário; documentação.

#### Outros:

- Saber trabalhar em equipe; na HomeRefill todos somos uma grande equipe, todo mundo é importante e tem algo a ensinar.
- Comprometimento; a HomeRefill é uma start-up e precisa do amor e comprometimento de seus colaboradores para que se torne a próxima maior empresa do mundo.
- Bom humor; será preciso para quando for atingido por munição de nerf.

## Contratação:
PJ

## Sobre a HomeRefill

A HomeRefill é um serviço inteligente de reabastecimento para o lar das pessoas, onde é possível fazer uma lista de compras, programar datas de entrega mensais ou individuais e ter o controle sobre tudo o que entra em seus lares. Com a tecnologia a nosso favor, constante inovação e grandes ideias em conjunto com entusiastas de empresas como Google, AWS e Apple, o serviço oferecido pela HomeRefill é novo no mundo e com pouco tempo de existência, já está sendo expandido para outros continentes e logo, o mundo.

## Como se candidatar?
Entre em contato pelo e-mail [vagas@homerefill.com.br](mailto:vagas@homerefill.com.br) com o seu Linkedin e GitHub e vamos conversar (-;

**Comment by LFeh** [comment]
Boa sorte @keitoliveira 👯
