### ISSUE TITLE
[Florianópolis] Estágio como Front-End Developer na NeoLife

### ISSUE THREAD

**Issue by alanicolasouza** [frontendbr/vagas#1763]
## Descrição da vaga

Vaga para estágio como front-end developer. 

## Local

Escritório em Gaivotas,  Bairro Ingleses (Norte da Ilha), Cidade Florianópolis

## Benefícios

- Ambiente super descontraído com equipe fantástica
- Liberdade na tomada de decisão (tecnologia, gestão de tarefas, etc)
- Horários flexíveis 
- Muitos desafios e aprendizados
- Ar puro e vista incrível (entre as montanhas e o mar)
- Ambiente de lazer com alguns vídeo games e muitos livros 
- No dress code
- Bônus: Temos certeza que o Max (nosso pet) vai sempre alegrar o seu dia.

## Requisitos

**Obrigatórios:**
- jQuery (Básico de JavaScript)
- HTML5
- CSS3

**Desejáveis:**
- Inglês intermediário para leitura, escrita e entendimento.
- Conhecimento em SEO e boas práticas de código semântico;
- Experiência com Git (ou qualquer outro versionador);
- Conhecimento em pré-processadores CSS (SASS ou LESS);
- Conhecimento de conexão com APIs;
- Portfólio online (ou algum lugar que reuna projetos já publicados);
- Conhecimento em desenvolvimento Wordpress (preferimos criar nossos próprios plugins por segurança);

**Diferenciais:**
- Inglês Intermediário/Avançado;
- Conhecimento básicos com adobe Photoshop ou Fireworks.

## Contratação

Estágio de 6h pelo CIEE (necessário estar estudando em curso técnico ou faculdade)
Bolsa R$ 1.000 + Benefícios + MUITO aprendizado

## Nossa empresa

Uma startup de Marketing Direto voltada suplementos naturais com um dos maiores crescimentos do mercado brasileiro nos últimos 6 meses.

## Como se candidatar

Para fazer a aplicação para essa vaga basta preencher o seguinte formulário: http://bit.ly/neolifefrontend

## Labels

- Alocado
- Estágio

**Comment by Mendrone** [comment]
Fala @alanicolasouza O inicio da descrição da vaga pede um profissional pleno, o titulo um estagiário e as labels incluem júnior, consegue ajustar pra gente poder colocar as labels? Valeu!

**Comment by alanicolasouza** [comment]
> Fala @alanicolasouza O inicio da descrição da vaga pede um profissional pleno, o titulo um estagiário e as labels incluem júnior, consegue ajustar pra gente poder colocar as labels? Valeu!

Obrigado por avisar @Mendrone
