### ISSUE TITLE
[Portugal] Front-End Developer Sénior na [AUBAY]

### ISSUE THREAD

**Issue by festaca** [frontendbr/vagas#1769]
### **A nossa empresa**
A Aubay, é uma empresa de origem francesa presente em diversos países na Europa.
Como cerca de 6000 pessoas desenvolvemos projetos nas mais diversas tecnologias.
Neste momento, temos várias vagas em aberto para várias posições.

### **Benefícios**
Plano de saúde
Visto de Trabalho para Portugal
Bilhete de avião para Portugal
Pagamento do alojamento nas primeiras semanas
Cultura organizacional gerida pelo nosso Hapiness Manager
Horário flexível
Almoço grátis todas as sexta-feiras
Frigobar e café grátis
Eventos mensais com atividades diferenciadas
Apoio financeiro

### **Descrição da vaga**
Projetos diferenciados em vários setores de atividade utilizando tecnologias de desenvolvimento frontend em projetos Web e/ou Mobile para projetos nacionais e internacionais

### **Requisitos Obrigatórios**
3 anos de experiência em desenvolvimento Front-end com Javascript, Vue.js, React.js, Node.js, Angular
Conhecimentos em programação orientada a objetos (Java, .NET)
Nível de inglês avançado

### **Diferenciais**
Projetos internacionais web ou mobile que permitem contato com vários países
Experiência biliotecas e frameworks diferenciadas de javascript

### **Como se candidatar**
Por favor envie um email para [fpiedade@aubay.com](mailto:fpiedade@aubay.com) com seu CV anexado

#Labels
PJ
Javascript
React
Angular
Inglês
Internacional

**Comment by felipelssilva** [comment]
enviado!
