### ISSUE TITLE
[São Paulo] Senior Front-end Developer

### ISSUE THREAD

**Issue by joselialcosta** [frontendbr/vagas#177]
## Job description

We're looking for frontend developers willing to solve problems and learn new technologies throughout the whole software development process. You will be part of a lean, multicultural team based in São Paulo and San Francisco.
You will have the chance to work in an agile environment with cutting-edge technology all over the software stack. The technologies we use include Scala, Java, Akka, Play, Spring, Typescript, AngularJS, Bootstrap, Docker, AWS, Redis, Elasticsearch, among others.

## Local

Vila Olímpia - SP

## Benefits

•    Procurement regime: CLT
•    Meal allowance (VR) 
•    Public transportation allowance (VT) 
•    Health and Dental Insurance
•    Life insurance
•    Cool environment (with videogames)
•    Fresh fruits everyday

## Requirements

•    Prototype and build Single-page Applications (SPA)
•    Pro-actively look for ways to improve product
•    Rapidly solve problems and fix bugs

**Must Have**
•    Experience in web development (HTML5/JS/CSS/Angular/Bootstrap)
•    Passion for delivering great user experience and usability
•    Building Web SPA in AngularJS
•    Experience building web integrated software and applications
•    Advanced english skills
•    Clean code and Git
•    Willing to learn
•    Ready to work in a fast-paced, ever-changing environment
•    Team work
•    Education: BS Computer Engineering/Science or equivalent

**Nice to Have**
•    Contributes to open source and has sample links
•    Visual design skills
•    Build Tools (Grunt/Gulp)
•    Great written communication and documentation abilities
•    Data-informed product development: analytics, A/B testing, etc.

## Procurement regime

CLT

## About us

Vamo is a rapidly growing Internet technology provider reinventing the way online consumers discover and attend events all from mobile phone.

## How to apply

https://goo.gl/forms/gMc20YbXLd76Xheo1

**Comment by joselialcosta** [comment]
@LFeh nós mudamos o perfil dessa vaga, vc se importaria e fechar a issue? Dessa forma eu poderia abrir uma nova issue com tudo correto e mudado :)
Obrigada!

**Comment by LFeh** [comment]
Claro! :D
