### ISSUE TITLE
[Rio de Janeiro] Front-end Developer na PUC-RIO 

### ISSUE THREAD

**Issue by gabrielvalle** [frontendbr/vagas#1772]
## Descrição da vaga

Estamos precisando de dois desenvolvedores front-end.

Salário inicial: R$ 6500,00 + benefícios

Requisitos necessários:

HTML5
CSS
Javascript (ES6)
React/Angular 2+
Git
Noções de UX

## Local

Escritório, Gávea - Rio de Janeiro

## Benefícios

- Plano de saúde
- Plano odontológico
- Seguro de vida
- Vale Alimentação de R$ 240,00
- Auxílio creche (Para Mulheres)
- Um ponto importante que vale ressaltar é o benefício, após 3 meses na empresa, de uma bolsa de 100% para fazer a graduação aqui na PUC-Rio. 
- Após 1 ano, esse benefícios se estende aos dependentes.

#### Desejáveis:
Typescript
SASS
Testes automatizados
Ter trabalhado com alguma metodologia ágil
Ter contribuído para projetos SPA

## Requisitos

**Obrigatórios:**
- Ensino Superior Completo
- 5+ anos de experiência em desenvolvimento (não necessariamente  na área de front-end)

**Diferenciais:**
- Conhecimentos em C#

## Contratação

CLT + Benefícios

## Nossa empresa

Grupo de Tecnologia e Engenharia de Petróleo - PUC - RIO.

## Como se candidatar

Interessados, favor enviar currículo, portfólio/github (caso tenham) para gtep@puc-rio.br

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias.

## Labels

- CLT
- Pleno
- Sênior

**Comment by JonasEmanuel** [comment]
A vaga está aberta ainda? O e-mail parece estar incorreto, tentei enviar mas voltou. Tenho interesse.
