### ISSUE TITLE
[São Paulo] Front-End Developer na Purple Cow

### ISSUE THREAD

**Issue by esdrastavares** [frontendbr/vagas#1774]
## Descrição da vaga

Estamos precisando de um Front-End developer apaixonado por tecnologia, confere a vaga abaixo ;)

## Local

Escritório, São Paulo - Vila Madalena

## Benefícios

- Plano de saúde
- VR
- VT

#### Diferenciais

- 2 horas de almoço

## Requisitos

**Obrigatórios:**
- Experiência anterior com desenvolvimento web/site, utilizando html5, css3, javascript, jquery, git
- Imprescindível proficiência em javascript
- Familiaridade com pré-processadores: sass, less
- Familiaridade com package manager: npm e/ou yarn
- Tagueamento de sites
- Html5
- Css3
- SEO

**Desejáveis:**
- Php
- Nodejs
- React
- Vuejs
- Javascript es6
- Webpack
- Jira

## Contratação

PJ a combinar

## Nossa empresa

Somos uma agência que nasceu de parto digital. Começamos a nossa atividade especialistas em Mídias Sociais, o que nos deu um know-how de como engajar o consumidor muito importante para as outras criações em todos os canais Digitais, além de agilidade para aproveitar todas as oportunidades. Com uma equipe de especialistas na relação entre marcas, pessoas e tecnologia estamos prontos para solucionar problemas, transformando uma imensidão de dados em estratégia e poderosas ideias criativas.

## Como se candidatar

Por favor envie um email para esdras.tavares@purplecow.com.br com seu CV anexado - enviar no assunto: Vaga Front-End Developer

## Labels

- Alocado
- PJ
- Pleno
- Sênior

**Comment by fabiolima** [comment]
Não pode ser remoto? :(

**Comment by esdrastavares** [comment]
> Não pode ser remoto? :(

Poxa, estamos montando um time interno por enquanto, mas mande o seu cv, sempre estamos precisando de monstros.
