### ISSUE TITLE
[São Paulo] Full-Stack Developer na BR Media Group

### ISSUE THREAD

**Issue by thiagovinhote** [frontendbr/vagas#1775]
## Descrição da vaga

A BR Media Group é uma empresa líder em digital influencers marketing, desenvolvemos plataformas e tecnologias para grandes marcas do mercado.
Estamos à procura de um talento que tenha vontade de aprender e crescer profissionalmente. Deve-se saber trabalhar com autonomia e proatividade. Comunicação e espírito de equipe fazem a diferença.

## Local

Escritório, São Paulo - Morumbi

## Requisitos

**Obrigatórios:**
- Ser comunicativo, comprometido e trabalhar em equipe
- Ter curiosidade investigativa na busca de soluções
- Node.js
- PWA (SPA)
- Linux
- Vue.js
- JavaScript (ES6)
- Node.js
- Python
- jQuery
- CSS/SASS
- Web Components
- Estrutura Flux
- Pré-processadores (ex.: Webpack, Gulp)
- Git

**Desejáveis:**
- VueJs, ReactJs, Angular
- AdonisJs, Django
- SQL, NoSQL

**Diferenciais:**
- Já ter trabalhado com influenciadores
- Babel
- Social Media API (ex.:  Facebook, Youtube, Twitter)
- GraphQL
- Teste Unitário
- AWS (EC2, S3)
- Estrutura em Cloud

## Contratação

PJ com faixa salarial de R$8.000,00 à R$9.000,00

## Como se candidatar

Por favor envie um email para suporte@br-mediagroup.com com seu CV anexado - enviar no assunto: Front-End Developer

## Labels

- Alocado
- Pleno
- Senior
- PJ

**Comment by ReactGirl** [comment]
Parabens a empresa por fornecer a faixa salarial. Que sirva de exemplo.
