### ISSUE TITLE
[São Paulo] Front-End Developer na McCann Health 

### ISSUE THREAD

**Issue by tiagords** [frontendbr/vagas#1780]
## Descrição da vaga

Contratação PJ/CLT desenvolvedor(a) para vaga de Front-End.

## Local

Av. Chedid Jafet, 75 - Vila Olimpia
São Paulo - SP
04551-010

## Requisitos

**Obrigatórios:**
- HTML5
- CSS3
- JavaScript

**Desejáveis:**
- Bootstrap
- Conhecimentos em Git

**Diferenciais:**
- WordPress
- VisualAid (VA)

## Contratação

PJ/CLT a combinar

## Como se candidatar

Por favor envie um email para tiago.rodrigues@mccannhealth.com.br com seu CV em anexo, portfólio (se houver) e pretensão salarial.

## Labels

- PJ
- CLT
- Júnior
- Pleno

**Comment by julianamokrejs** [comment]
Enviado!

**Comment by alessandroprudencio** [comment]
Só presencial?

**Comment by brunopoc** [comment]
Enviado,

**Comment by ReactGirl** [comment]
Estranho uma vaga onde voce envia sua pretensão salarial. Especialmente para uma vaga claramente de Junior, onde para ser inserido no mercado de trabalho, alguns trabalhariam até de graça.

Nao seria o contrario da empresa fornecer essa informação?

**Comment by developer-sp** [comment]
Enviado.

**Comment by VictorCardoso22** [comment]
Aceita remoto?

**Comment by psilva21** [comment]
Enviado.
