### ISSUE TITLE
[São Paulo] Front-End Developer na [Flatbox]

### ISSUE THREAD

**Issue by FMSGiganti** [frontendbr/vagas#1781]
Estamos com duas vagas para desenvolvedores Front-End para fazerem parte do time da Flat! Se você manja muito de desenvolvimento de sites, sistemas web e mobile, ou conhece alguém perfeito para a vaga que esteja a procura de um trampo, envie seu CV pra gente pelo link abaixo ou marque os amigos ;)

Acesse o link e confira mais detalhes sobre a vaga: https://bit.ly/2TJRBlb

**Comment by Mendrone** [comment]
@FMSGiganti Poderia por favor incluir os detalhes da vaga aqui conforme o template proposto? Pra nós essas informações são importantes pra manter o repositório util para empresas e candidatos. 

Vou manter o anúncio fechado até a atualização. Obrigado!

**Comment by FMSGiganti** [comment]
> @FMSGiganti Poderia por favor incluir os detalhes da vaga aqui conforme o template proposto? Pra nós essas informações são importantes pra manter o repositório util para empresas e candidatos.
> 
> Vou manter o anúncio fechado até a atualização. Obrigado!

Claro, farei agora.

**Comment by FMSGiganti** [comment]
> > @FMSGiganti Poderia por favor incluir os detalhes da vaga aqui conforme o template proposto? Pra nós essas informações são importantes pra manter o repositório util para empresas e candidatos.
> > Vou manter o anúncio fechado até a atualização. Obrigado!
> 
> Claro, farei agora.

Feito

**Comment by FMSGiganti** [comment]
@Mendrone, bom dia, tudo bem? Fiz as alterações, acho que está dentro dos padrões, pode liberar a vaga pra nós? obrigado
