### ISSUE TITLE
[Brasília ou Remoto] Front-End Developer (React Native) na Yi Mobile

### ISSUE THREAD

**Issue by ianzitow** [frontendbr/vagas#1786]
## Descrição da vaga

Estamos à procura de developer de React Native para nosso escritório da Yi Mobile em Brasília ou **Remoto**. Início imediato!

## Local

Escritório no Setor Comercial Sul, Brasília, DF ou Remoto

## Benefícios

- Ambiente com puffs, Xbox, café & snacks
- Internet padrão Campus Party™
- Possibilidade de trabalho remoto;

## Requisitos

**Obrigatórios:**
- Domínio comprovado de Javascript
- Experiência com React Native
- Graduação completa em área de TI e/ou afins
- Inglês avançado

**Desejáveis:**
- Ser um membro proativo em nosso time usando metodologia ágil de desenvolvimento;
- Codificação de software com testes unitários e de integração;
- Ajudar o time a priorizar e encontrar jeitos inovadores de alcançar objetivos;
- Ter capacidade de trabalhar independentemente.

**Diferenciais:**
- Conhecimento de outros frameworks de frontend, como React
- Portfólio de projetos

## Contratação

Bolsa de R$ 3000,00.

## Nossa empresa

Somos uma empresa especializada no desenvolvimento de aplicativos para iOS e Android. Queremos unir a beleza de um bom design com a eficiência de códigos-fontes de alta qualidade. Temos experiência no desenvolvimento de web sites, design e apps móveis. Atuamos em todos os ramos de negócio, desde restaurantes a salões de beleza.

## Como se candidatar

Por favor, enviar currículo em https://goo.gl/forms/SDSbity0GGhd9WT63.

**Comment by italomlp** [comment]
Enviado!
