### ISSUE TITLE
[São Paulo] Front-End Engineer na Xerpa

### ISSUE THREAD

**Issue by Leocardoso94** [frontendbr/vagas#1787]
## Descrição da vaga

Estamos em busca pessoas para trabalhar conosco aqui na Xerpa. Seu trabalho aqui vai ser atuar lado lado com designers e engenheirxs para construir um produto que impacta a vida de diversas pessoas.

Aqui na Xerpa nossa principal aplicação é feita em ClojureScript, mas não se preocupe **não é requisito saber CLJS é apenas um diferencial**, nossa busca é por pessoas que estão afim de aprender e ensinar durante o dia-a-dia.

## Local

Av. Brg. Faria Lima, 1912 - Jardim America, São Paulo - SP, 05402-600

## Benefícios

- Academia/Gympass
- Seguro de Vida
- Plano de Saúde
- VT/VR

## Requisitos

**Desejáveis:**
- Experiência em JavaScript, incluindo conceitos como programação assíncrona.
- Experiência em HTML / CSS, incluindo conceitos como layout, especificidade, e compatibilidade entre navegadores.
- Experiência com APIs de navegadores
- Você tem interesse em programação funcional.
- Você adora trabalhar em um ambiente em que você constantemente experimenta e interage rapidamente.

**Diferenciais:**
- Experiência com React e Clojurescript é um bônus
- Experiência com API's em GraphQL

## Contratação

CLT a combinar

## Nossa empresa

E se você acordasse para trabalhar todos os dias sabendo que suas habilidades estão melhorando a vida de milhares de pessoas criando experiências de trabalho incríveis ? Isto é ser Xerpa. Nós somos a transformação que o Brasil precisa, com muita tecnologia e propósito!

## Como se candidatar

Por favor envie um email para lsilva@xerpa.com.br e lsousa@xerpa.com.br com seu CV e/ou Linkedin - enviar no assunto: Vaga Front-End

## Labels

- Alocado
- CLT
- Júnior
- Pleno
- Sênior

**Comment by brunopoc** [comment]
Enviado!

**Comment by agnezi** [comment]
Enviado

**Comment by mariana-cunha** [comment]
olá! o email lsousa@xerpa.com.br está retornando, acredito que tenha chegado certinho pra lsilva@xerpa.com.br

**Comment by Leocardoso94** [comment]
Obrigado por avisar!
