### ISSUE TITLE
[Campinas/SP] Front-End Developer na Benu GmbH

### ISSUE THREAD

**Issue by bbonfim** [frontendbr/vagas#1791]
## Descrição da vaga

A Benu GmbH (Sede em Vienna, na Austria), esta procurando front-end developers para se juntarem ao time de Campinas. 

## Local

Swiss Park Office. Av. Antônio Artioli, 570 - Swiss Park, Campinas - SP, 13049-900

#### Diferenciais

- Possibilidade de Home Office 4 dias por mes
- Laptops de alta performance (~12k reais)
- Interação direta com time Austríaco (em Inglês)
- Viajem para Vienna uma vez ao ano

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com React
- proficiencia em consumo de API's Rest
- proficiencia em HTML5
- boas noções de UX

**Desejáveis:**
- experiencia com docker
- conhecimento de frameworks para testes automatizados
- Inglês intermediario

**Diferenciais:**
- projetos opensource
- conhecimento em cloud native apps (kubernetes, google cloud, AWS)
- conhecimentos em java
- conhecimentos em UX Design
- Alemão ou Inglês fluente

## Contratação

PJ ou CLT (aberto para propostas)
Salario: 9 ~ 10k (dependendo da experiencia do candidato)

## Nossa empresa

A Benu GmbH é uma startup Austríaca que esta buscando trazer a industria funeraria para o seculo 21. Nossa meta pretende trazer modernizacao nos processos de organizacao de funerais bem como o gerenciamento entre os diversos provedores de servicos do setor. Com apenas alguns meses de existencia, ja arrecadamos mais de 1 milhao de reais em investimentos privados e governamentais. Nosso time de "Angel Investors" é composto por emprendedores de sucesso no mercado Austríaco e global.

## Como se candidatar

Por favor envie um email para bruno@benu.at com seu CV anexado - enviar no assunto: React Dev

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dia após cada processo.

## Labels

- React
- Javascript
- CLT
- PJ
- Pleno
- Sênior

**Comment by iamfelipemattos** [comment]
Oportunidade é valida para alguem que nao conhece React mas sim Angular 6?

**Comment by bbonfim** [comment]
@iamfelipemattos se estiver disposto a estudar usar react, sim :)

**Comment by bbonfim** [comment]
Adicionando Salario conforme solicitado por alguns candidatos.
