### ISSUE TITLE
[São Paulo] Front-End Developer no [BANCO DAYCOVAL S.A.]

### ISSUE THREAD

**Issue by julianodaycoval** [frontendbr/vagas#1792]
O Banco Daycoval contrata para sua área de Marketing e Comunicação 1 (um) desenvolvedor Front End.
Início Imediato.

Requisitos Básicos:
a.    HTML
b.    CSS, CSS3
c.    Lógica de programação
d.    Javascript – Intermediário +
e.    JQuery – Intermediário +
f.    Manuseio do Pacote Adobe 

Desejável
a.       Conhecimentos em Angular
b.      React e Vue 

O Banco Daycoval oferece salário compatível com a função em companhia financeira de médio porte, sistema de contratação CLT, Convênio Médico e Odontológico de Primeira Linha, VR, VA, VT, Programa de Participação nos Lucros (PLR) e Programa de Participação nos Resultados (PPR).

O local de trabalho será na Avenida Paulista, ao lado do Parque Trianon e a 3 minutos a pé do Metrô Consolação.

O profissional ficará alocado na área de Marketing, uma house dentro do Banco. 

Importante reforçar que o Banco Daycoval foi eleito em 2018 como uma das melhores empresas para se trabalhar.

Favor enviar currículos e portfólio para juliano.capato@bancodaycoval.com.br 
Início Imediato.

**Comment by fernando-Jesus** [comment]
Tem vaga para Sênior?

**Comment by agnezi** [comment]
Enviado.

**Comment by israelcena** [comment]
Como assim Lógica de programação ? Noções ?

**Comment by developer-sp** [comment]
Enviado.
