### ISSUE TITLE
[Barueri/SP] Front-End Developer na Fingerprint

### ISSUE THREAD

**Issue by deizepi** [frontendbr/vagas#1795]
## Descrição da vaga

Desenvolver aplicativos com o Framework Ionic 3+, fazendo comunicação com API através de OAUTH2.

## Local

Remoto ou Escritório, Barueri/SP - Alphaville

## Benefícios

- Plano de saúde
- Seguro de vida
- Restaurante no local
- VT
- VA (no valor de R$ 80,00/mês)
- PLR

## Requisitos

**Obrigatórios:**
- 1 ano de experiência com Ionic
- Conhecimento em HTML, CSS e Angular
- Conhecimento em plugins Cordova (Card.io, SQLite, Phone, etc)

**Desejáveis:**
- Conhecimento em OAUTH2

**Diferenciais:**
- Conhecimento em criptografia (AES-256-CBC)
- Experiência com API
- Experiência com meios de pagamento

## Contratação

CLT para presencial
PJ para remoto

## Nossa empresa

A Fingerprint é uma gráfica de dados variáveis (boletos, faturas, extratos, mensagens personalizadas, etc.) há 25 anos no mercado, nos últimos 5 anos decidimos inovar os meios de pagamento, ingressamos no setor com uma ferramenta completa para ONGs, hospitais, igrejas, etc. e não paramos por aí, estamos constantemente trabalhando para entregar a melhor solução em meios de pagamento para os demais setores.

## Como se candidatar

Por favor envie um email para laraujo@fingerprint.com.br com seu CV anexado - enviar no assunto: GIT - Ionic Developer

### Alocação:
- Presencial
- Remoto (apenas para PJ)

### Contratação:
- CLT
- PJ

### Experiência
- Júnior
- Pleno
- Sênior

**Comment by deizepi** [comment]
A vaga continua em aberto.

**Comment by mart2222** [comment]
Enviei um email logo que foi anunciado a vaga e até o momento não tive um feedback ou um "sinal de fuça".

**Comment by deizepi** [comment]
Boa tarde, pode encaminhar esse email para a Lilian (laraujo@fingerprint.com.br) com seu currículo em anexo.
Estávamos com problemas no email alguns dias atrás, não devemos ter recebido por conta disso.

Pedimos desculpas e agradecemos a compreensão.



Sent via the Samsung Galaxy S8, an AT&T 4G LTE smartphone


-------- Mensagem original --------
De: Djeison Zanette <notifications@github.com>
Data: 06/03/19 08:22 (GMT-03:00)
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: David Deizepi <david_deizepi@hotmail.com>, Author <author@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [Barueri/SP] Front-End Developer na Fingerprint (#1795)


Enviei um email logo que foi anunciado a vaga e até o momento não tive um feedback ou um "sinal de fuça".

**Comment by mart2222** [comment]
Email reenviado, agradeço e fico no aguardo. `=)`

**Comment by mart2222** [comment]
Ainda estou aguardando um retorno.

**Comment by deizepi** [comment]
A vaga continua em aberto.

**Comment by deizepi** [comment]
A vaga continua em aberto.
