### ISSUE TITLE
[São Paulo - SP] Front-end Developer - Tegra

### ISSUE THREAD

**Issue by JessicaSoos** [frontendbr/vagas#1796]
## Descrição da vaga

● Mais de dois anos de experiência com Vue.js, React and Redux.
● Você escreve código limpo, reutilizável, bem testado e documentado.
● Cinco anos de experiência com JavaScript, outras linguagens e plataformas (Ruby, Rails, CSS, HTML, SCSS, etc...)

## Local

Mooca - SP

## Contratação

PJ a combinar

## Nossa empresa

A Tegra
Desenvolvemos soluções digitais sob medida para o seu negócio.

Nosso expertise técnico e conhecimento de negócio nos permite proporcionar uma excelente experiência no desenvolvimento de projetos de software.

Nossa metodologia de trabalho tem sua base na Experiência do Usuário (UX) e o Design Thinking para a concepção de soluções, desenvolvimento pautado nas metodologias ágeis com entregáveis recorrentes resultando em soluções robustas, de alta performance, escaláveis e compliance com requisitos de segurança.

## Como se candidatar

Por favor envie um email para email jessica.moreira@email.com.br com seu CV anexado - enviar no assunto: Vaga React

## Labels

- PJ
- Sênior

**Comment by nandomoreirame** [comment]
jessica.moreira@email.com.br?
email.com.br?
