### ISSUE TITLE
[Curitiba/São Paulo] Front-End Developer na FH Consultoria

### ISSUE THREAD

**Issue by felipelssilva** [frontendbr/vagas#1798]
### Vem ser um Red!
Estamos com vagas abertas para Frontend.

## Local

Curitiba e São Paulo!

## Benefícios

- Plano de saúde
- Plano odontológico
- VR / VA
- VT
- Auxílio creche
- Vale Gasolina
- Seguro de Vida
- GymPass

#### Diferenciais

- Puffs
- Empresa descontraida
- Ambiente agradável

## Requisitos

**Obrigatórios:**
- Experiência em desenvolvimento frontend com habilidades em HTML 5, CSS 3, SASS, LESS e Javascript;
- Experiência em Node.js, NPM, GRUNT e GULP
- Experiência com Bootstrap;
- Experiência com Semantic Web (W3C), Responsive Web, Progressive Enhancement;
- Conhecimento em ferramentas de versionamento (Bitbucket, Github);
- Conhecimento básico em ferramentas gráficas como Adobe Photoshop e Sketch ou similares;
- Domínio das melhores práticas de desenvolvimento, Design Patterns e Metodologias Ágeis;
- Cultura de reaproveitamento de código, componentização e qualidade embarcada ao longo do desenvolvimento;
- Cursado ou cursando Engenharia da Computação, Ciência da Computação, Sistemas de Informação, Análise e Desenvolvimento de Sistemas, Gestão em Tecnologia da Informação

**Desejáveis:**
- Experiência em desenvolvimento de e-commerce;
- Entendimento das melhores práticas SEO, UX e performance
- Autogestão, aprendizado rápido e boa comunicação;
- Pós-graduação ou especialização na área de TI

## Contratação

CLT

## Nossa empresa

A FH é uma empresa de tecnologia especializada em processos de negócios e software. Desde 1999 no mercado, a companhia possui atuação global, com projetos realizados em mais de 30 países nos mais variados segmentos da indústria.

Conta com uma estrutura robusta, que possui mais de 600 colaboradores, a FH preza pela entrega de projetos personalizados para seus clientes, e, por este motivo, atua de forma regional, com oito sedes localizadas em: Curitiba, São Paulo, Porto Alegre, Joinville, Rio de Janeiro, Brasília, Stuttgart e Madri.

## Como se candidatar

Favor encaminhar seu currículo para ane.balmant@fh.com.br

## Labels

- Alocado
- CLT
- Júnior
- Pleno

**Comment by nandomoreirame** [comment]
nice!

**Comment by psilva21** [comment]
Enviado!
