### ISSUE TITLE
[Florianópolis - Santa Catarina] Desenvolvedor(a) Front-end - Grupo Neolife

### ISSUE THREAD

**Issue by patriciaantunes** [frontendbr/vagas#1799]
Vaga de desenvolvedor front-end pleno, com foco principalmente para desenvolvimento Wordpress e HTML (puro ou c/ bootstrap).
==================================================
* Ambiente super descontraído com equipe fantástica
* Liberdade na tomada de decisão (tecnologia, gestão de tarefas, etc)
* Horários flexíveis
* Café e almoço da Rita (você vai adorar ela hearts)
* Vista incrível pro mar e montanhas (apenas uma quadra do mar)
* Ambiente de lazer com Nintendo até PS4.
* Estar em contato com os melhores profissionais de cada área, temos orgulho de dizer que unimos alguns dos melhores profissionais de marketing direto do Brasil no mesmo lugar, o ambiente proporciona aprendizagens diárias e crescimento tanto profissional quanto pessoal contínuo;
* Remuneração compatível com conhecimento mais bônus por resultados.
* Bônus: Temos certeza que o Max (nosso pet) vai sempre alegrar o seu dia.
==================================================
-->

## Descrição da vaga

**Obrigatórios:**

* Conhecimentos sólidos em desenvolvimento front-end: HTML5, CSS3, Javascript e jQuery;
* Conhecimento em programação PHP;
* Conhecimento sólido de desenvolvimento Wordpress (preferimos criar nossos próprios plugins por segurança);
* Experiência com design responsivo e cross-browser;
* Compromisso com as deadlines e qualidade na entrega.

**Desejáveis:**

* Inglês intermediário para leitura, escrita e entendimento.
* Conhecimento em SEO e boas práticas de código semântico;
* Conhecimento em Google Analytics e Google Tag Manager;
* Experiência com Git (ou qualquer outro versionador);
* Experiência com MySQL;
* Experiência com Servidores (configurar, ajustar);
* Conhecimento em pré-processadores CSS (SASS ou LESS);
* Conhecimento de conexão com APIs;
* Portfólio online (ou algum lugar que reuna projetos já publicados);

**Diferenciais:**

* Inglês Avançado;
* Conhecimento básicos com adobe Photoshop ou Fireworks.

## Local

Remoto ou Escritório, Floripa - Ingleses

## Contratação

PJ ou CLT a combinar

## Nossa empresa

Uma startup de Marketing Direto voltada suplementos naturais com um dos maiores crescimentos do mercado brasileiro nos últimos 3 meses.

## Como se candidatar

Por favor envie um email para contato@rmaish.com.br com seu CV anexado e pretensão salarial - enviar no assunto: Vaga Desenvolvedor

## Labels
* Alocado
* Remoto - Total
* CLT
* PJ
* Pleno

**Comment by Mendrone** [comment]
@patriciaantunes Poderia por favor incluir o nome da empresa? Para manter o padrão da comunidade, vou manter a vaga fechada até a atualização.

**Comment by patriciaantunes** [comment]
Ajustado! Obrigada

**Comment by patriciaantunes** [comment]
> @patriciaantunes Poderia por favor incluir o nome da empresa? Para manter o padrão da comunidade, vou manter a vaga fechada até a atualização. Também peço que edite o título pra ficar no padrão abaixo:
> 
> [Cidade - Estado] Vaga - Nome da Empresa

Ajustado! Obrigada

**Comment by pachecovit** [comment]
@patriciaantunes Enviei, sou de Florianópolis, se não me engano, eu já havia enviado para essa vaga a um tempo atrás, mas não obtive resposta. Se conseguirem dar um feedback também. Obrigado! :)

**Comment by thiagorowof** [comment]
@patriciaantunes também estou sem resposta...!

**Comment by patriciaantunes** [comment]
> @patriciaantunes Enviei, sou de Florianópolis, se não me engano, eu já havia enviado para essa vaga a um tempo atrás, mas não obtive resposta. Se conseguirem dar um feedback também. Obrigado! :)

Olá! Obrigada pelo envio.
Sou consultoria e iniciei meu contrato com a Neolife a pouco tempo. Por isso, peço desculpas e não tenho conhecimento dos processos anteriores.
Para esta posição em questão, entrei em contato apenas com os candidatos selecionados.

Obrigada!

**Comment by patriciaantunes** [comment]
> @patriciaantunes também estou sem resposta...!

Olá! Obrigada pelo envio.
Sou consultoria e iniciei meu contrato com a Neolife a pouco tempo. Por isso, peço desculpas e não tenho conhecimento dos processos anteriores.
Para esta posição em questão, entrei em contato apenas com os candidatos selecionados.

Obrigada!

**Comment by adeonir** [comment]
@patriciaantunes É interessante avisar a todos os candidatos, mesmo que não selecionados.

**Comment by patriciaantunes** [comment]
> @patriciaantunes É interessante avisar a todos os candidatos, mesmo que não selecionados.
Gostaríamos muito que isto fosse possível. Porém, a quantidade de candidatos por vaga inviabiliza isto.

Abraços
