### ISSUE TITLE
[Remoto ou São Paulo] - Estágio Front End Development - Bleeding Edge Tech

### ISSUE THREAD

**Issue by rturk** [frontendbr/vagas#18]
## Descrição da vaga

Migrar o nosso portal web (http://brandlovers.com) usando bleeding edge technologies tais como React, GraphQL, Redux, Relay.

Objetivo é reconstruir o site sem vícios com o passado, então a ideia não é gastar tempo com código legado. 

O Backend já existe e está rodando em Koa, com MongoDB.

## Local

Remoto ou Escritório, São Paulo 

## Benefícios

- Work from home

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com Javascript
- 1 ano experiência com Node

**Desejáveis:**
- conhecimentos em React, GraphQL, Relay 

**Diferenciais:**
- Estamos usando o que existe de mais moderno em tecnologia web. Esperamos que o candidato(a) a esta vaga gaste bom tempo pesquisando novas tecnologias, teste inovações e realmente use coisas interessantes
## Contratação

PJ a combinar

## Nossa empresa

Brand Lovers é uma startup fundada por ex-funcionários da Amazon.com e Nivea. Finalista do Inovativa Brasil entre outros prêmios no Brasil e Exterior.

## Como se candidatar

https://brandlovers.recruiterbox.com/jobs/fk066kh

**Comment by victormiguez** [comment]
Muito bacana a vaga, porém não vejo como isso se aplicaria para um estágio.
Na minha opinião se um cara tem 3 anos de experiência ele já não se enquadra mais como estagiário, outro ponto é a possibilidade de trabalho remoto, não é importante que o estagiário tenha contato direto com o resto do time?

**Comment by LFeh** [comment]
Então @rturk, marquei a label como estágio, mas também fiquei confuso.

Essas qualificações parecem aplicadas a um desenvolvedor pleno, não?

Até mesmo o fato de trabalhar remoto, não vejo aplicável a um estagiário.

**Comment by nighto** [comment]
Estagiário com 2 anos de experiência e home office, parece legítimo, só que não.

**Comment by nighto** [comment]
Enfim, parece que colocaram erroneamente como estágio, até porque o modo de contratação é PJ.

**Comment by eduardojmatos** [comment]
@rturk pode nos ajudar a entender a posição? Estágio aqui realmente não se encaixa nas responsabilidades e tempo de experiência do desenvolvedor, ainda mais lidando com as tecnologias que você citou: React, GraphQL, Redux, Relay.

Se puder nos responder o mais breve possível podemos manter a vaga por aqui :)

**Comment by diessica** [comment]
Bizarro...

**Comment by LFeh** [comment]
@rturk Consegue esclarecer essas questões?

**Comment by Belline** [comment]
Desconfio que o estágio é apenas fachada para a pessoa poder receber o dinheiro sem pagar imposto.... de fato é mais vantajoso que PJ (que precisa emitir notas fiscais), isso é claro se você pensar somente no lado financeiro da coisa... mas com certeza nao deve ser salario de estagiario nao

**Comment by cmpereirasi** [comment]
Pessoal no texto acima em Diferenciais fala que é Contratação, pelo meu entender não é estágio!

**Comment by LFeh** [comment]
@rturk Encontrou alguém?

**Comment by camilatigre** [comment]
@rturk 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by rturk** [comment]
@camilatigre C. Não tenho certeza, mas os leeds daqui foram ótimos. Vamos continuar usando

**Comment by ThadeuConstantino** [comment]
Programador Mobile
Experiência em alguma Cross-Platform Javascript para desenvolvimento mobile.
Disponibilidade para fazer manutenção em aplicativos feitos em Adobe Animate CC utilizando AIR para mobile.
Vaga para atuação Presencial e/ou Home Office.
CVs para: thadeu.constantino@playlearn.com.br
