### ISSUE TITLE
[Brasil] - Estagiário de frontend homeoffice

### ISSUE THREAD

**Issue by igorcouto** [frontendbr/vagas#180]
## Descrição da vaga

Você pode esperar um trabalho intenso em projetos HTML5/CSS3 com o framework React, do facebook, e boas práticas em Redux, um mecanismo de gerenciamento de estado de aplicações, além de diversos componentes javascript.

## Local

Remoto. Sala de vídeo no appear.in e slack :)

## Benefícios

- Equipe ideológica e engajada em transformação social
- Tecnologias avançadas (além do React estamos testando o Vue.js) e migrando as APIs para Golang/GraphQL e Firebase

## Requisitos

Avaliação técnica do desafio.

## Contratação

Bolsa de estário, R$ 1.000,00 por 06 horas/dia. Horário Flexível.

## Nossa empresa

A 1STi é uma consultoria em tecnologias digitais emergentes que tem a missão de aproximar a tecnologia das reais necessidades sociais. Nós enxergamos a tecnologia como um presente à humanidade dado pela expressão de nosso próprio intelecto, realizando uma síntese entre arte, humanidade e ciência.

Nosso modelo de negócios combina projetos de valor compartilhado com consultoria nas tecnologias mais avançadas. Esse desafio é uma oportunidade para fazer parte do nosso time em uma jornada de aprendizado e desenvolvimento de interfaces web!

## Como se candidatar

Faça o nosso desafio em https://github.com/1STi/desafio-frontend

**Comment by LFeh** [comment]
Cara... remoto e estágio funciona? 

Curiosidade mesmo.

**Comment by igorcouto** [comment]
Opa, tem funcionado sim. As ferramentas ajudam muito (appear, slack e livecoding).
E comunicação o tempo todo.

**Comment by igorcouto** [comment]
Obrigado pelos labels! :+1:

**Comment by LFeh** [comment]
Lega, boa sorte ai ;)

**Comment by ribeiroevandro** [comment]
Estagiário que manje de React e Redux?

**Comment by igorcouto** [comment]
Não não, vai aprender com a gente. A equipe é bem sênior.

**Comment by JoaoAntonioMaruti** [comment]
Só tem vagas de estágio ?

**Comment by igorcouto** [comment]
Estamos com estratégia de formar devs nesse stack a médio prazo, então a preferência é por quem está começando. Mas não somos quadrados, se quiser participar, você pode fazer o desafio e marcar uma conversa com nosso diretor de valor compartilhado. Te passo o contato no slack do desafio.

**Comment by JoaoAntonioMaruti** [comment]
Show, vou te chamar no Slack

**Comment by igorcouto** [comment]
Enviei um convite no seu email para o slack do desafio. Falamos por lá. Abs,

**Comment by Josue23** [comment]
Boa tarde Igor,

Eu vi agora no horário de almoço, me envia o convite do Slack do desafio,
por favor.

Abraços

2016-11-28 13:54 GMT-02:00 Igor Couto <notifications@github.com>:

**Comment by julianorafael** [comment]
Eu gostaria de receber o convite do Slack para o desafio também.

**Comment by saulojmc** [comment]
Olá, gostaria de receber o convite também do desafio.


*Atenciosamente*

*Saulo Melo*
21-988585479

2016-11-28 16:37 GMT-02:00 Juliano Rafael <notifications@github.com>:

**Comment by marcoswca** [comment]
Olá, gostaria de receber o convite do slack. 

Att, Marcos Williams Cavalcanti de Arruda
marcoswca1@gmail.com
(83) 9-9990-0395

**Comment by gkal19** [comment]
Olá, gostaria de receber o convite do slack.

gabrielsilva1956@gmail.com
(91) 9-8828-6793

NOTA: Ja enviei meu PR

Att, Gabriel Kalani Peniche da Silva

**Comment by igorcouto** [comment]
Convite enviado. Seu PR está em revisão Gabriel! :)

**Comment by brunooomelo** [comment]
@igorcouto 
gostaria de receber o convite no slack tambem.
utibmelo@gmail.com
(11) 99888-1910

**Comment by jadir-junior** [comment]
boa tarde Igor,
vocês tem alguma vaga freela?

https://www.linkedin.com/in/jadir-j-silva-junior-645a3139

jadirjsjunior@gmail.com

**Comment by thallesmarchetti** [comment]
Gostaria de participar.

linkmarchetti@gmail.com

**Comment by gabrielferreiraa** [comment]
Gostaria de receber o convite do Slack também, vou realizar o desafio ! :)

gabrielferreira.95@hotmail.com

**Comment by rofrnnds** [comment]
Aceitam formados?
Se sim, gostaria de participar.

rodrigodeoliveira.ti@gmail.com

**Comment by ronal2do** [comment]
É uma ótima oportunidade para aprender e ainda receber por isso

**Comment by abraaoduarte** [comment]
Gostariam de participar.
abraao.n.duarte@gmail.com

**Comment by andersoonweb** [comment]
Gostaria participar. 

andersomxp@gmail.com

**Comment by ribeiroevandro** [comment]
Boa, gostaria de participar... React e Redux são duas tecnologias que me interessam muito, meu email do Slack é `ribeiroevandro@live.com`, me envie um convite por favor...

**Comment by igorcouto** [comment]
Pessoal.

Vaga concluída. Aos que prestaram o desafio, em breve teremos outra e vocês já estão automaticamente incluídos.

Obrigado ao pessoal do grupo.

**Comment by LFeh** [comment]
Foi daqui @igorcouto ?

**Comment by igorcouto** [comment]
Foi sim!

2016-12-21 17:45 GMT-02:00 Felipe Fialho <notifications@github.com>:
