### ISSUE TITLE
[Belo Horizonte] Desenvolvedor Frontend Vue.js [DON ADVICE]

### ISSUE THREAD

**Issue by pmagalhaesa** [frontendbr/vagas#1800]
**Conhecimentos**
- HTML, CSS e JavaScript
- Vue.js (obrigatório)
- Experiencia com integrações API REST
- Materialize
- Noções de UX

**Diferenciais**
- Banco de Dados MYSQL
- GIT  
- Linux

**Aptidões e qualidades**
Comprometimento com prazos e metas
Vontade de aprender 
Proatividade
Trabalho em equipe

**Formação** 
Curso superior relacionado a Tecnologia da Informação (Ciência da Computação, Sistemas de Informação e afins) - concluído ou em andamento

**Horário**
De segunda a sexta, de 9 ás 18h 

**Local**
Belo Horizonte-MG

Se você atende aos requisitos, venha fazer parte da nossa equipe!!
Envie seu curriculo por email para  [paula@donadvice.com](mailto:paula@donadvice.com) com o assunto VAGA FRONTEND

**Comment by vcpablo** [comment]
Aceita remoto?

**Comment by pmagalhaesa** [comment]
> Aceita remoto?

Não :(

**Comment by isrmic** [comment]
Tem estágio ?

**Comment by isrmic** [comment]
Teria possibilidade de flexibilidade de horário ? Pois eu curso Ciência da Computação na parte da manhã.

**Comment by pmagalhaesa** [comment]
> Teria possibilidade de flexibilidade de horário ? Pois eu curso Ciência da Computação na parte da manhã.
