### ISSUE TITLE
[São Paulo - SP] Sr Front-End Developer - Wyser

### ISSUE THREAD

**Issue by ronirhwyser2017** [frontendbr/vagas#1802]
2 Vagas (Presenciais ou Remotas) para uma das principais fintechs S/A do mercado, em franco crescimento com ambiente arrojado e digital.
Uma das 25 startups mais desejadas no Brasil segundo o Linkedin Top Startups 2018

Nosso candidato ideal:
Entende a importância de proporcionar uma experiência de usuário de primeira classe e que as soluções mais bonitas são muitas vezes as mais simples;
É altamente proficiente em melhores práticas de desenvolvimento web, técnicas de usabilidade;
Conhece a fundo as capacidades e limitações técnicas da web;
Dá valor a código limpo, conciso e reutilizável;
Gosta de trabalhar duro e, o mais importante, de se divertir;
Tem fortes habilidades de debug em todos os principais navegadores.
Conhecimento avançado de Javascript, HTML5, CSS3, JSON;
Experiência com frameworks do lado do cliente e do lado servidor, como Backbone, Marionette e Reactjs e Angular, etc.

CLT + Benefícios (Assistência Médica + VR de R$ 27/dia + VT + PLR de até 2 salários)

Zona oeste de SP.

**Comment by hnrqsss** [comment]
Tem que sabe de todos estes frameworks js ou apenas um deles?

**Comment by ronirhwyser2017** [comment]
Olá!

Dominar mais o React.

Att,

Roni Martins
Consultant
[Descrição: http://gigroup.com.br/assinaturas/gigroup/Wyser.jpg]
------------------------------------
Rua Doutor Fernandes Coelho, 85, 4º andar – Pinheiros - São Paulo-SP
CEP: 05423-040
Email: roni.martins@wyser.com.br<mailto:roni.martins@wyser.com.br>
Site: http://www.wyser.com.br<http://www.wyser.com.br/>
Celular: +55 (11) 9.7660-9608
Fixo: +55 (11) 3135-5461
Skype: roni.martins.rh
Ramal: 461
[http://assinatura.gigroup.com.br/gigroup/Linkdin.png]<https://www.linkedin.com/company/3118347?trk=tyah&trkInfo=clickedVertical%3Acompany%2CentityType%3AentityHistoryName%2CclickedEntityId%3Acompany_company_company_company_company_company_company_3118347%2Cidx%3A0>[http://assinatura.gigroup.com.br/gigroup/youtube-icon-block-png-17.png]<http://www.youtube.com/channel/UCpxlwy-zfxsQ1tRPguKhXVA>
------------------------------------
[cid:image004.jpg@01D4150D.505A2470]
Esta informação é particular e confidencial e está endereçada unicamente ao seu destinatário. Se você não for o destinatário ou a pessoa responsável pela entrega ao destinatário, por favor informe por e-mail ao remetente e imediatamente apague a mensagem e seus anexos sem copiar ou divulgar seu conteúdo. O não cumprimento, poderá ser considerado como uma ação ilegal.

---------------------------

This information is private and confidential and intended for the recipient only. If you are not the addressee or the person responsible for delivering it to the intended addressee, please notify the sender by e-mail and immediately delete the message and any attachments without copying or disclosing its contents. To do so is prohibited and may be unlawful.

De: Henrique Assunção <notifications@github.com>
Enviada em: quinta-feira, 14 de fevereiro de 2019 15:23
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: Roni Martins (WYSER-SP) <Roni.Martins@wyser.com.br>; Author <author@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [São Paulo - SP] Sr Front-End Developer - Wyser (#1802)


Tem que sabe de todos estes frameworks js ou apenas um deles?

**Comment by hnrqsss** [comment]
Como aplicar pra esta vaga?

**Comment by ronirhwyser2017** [comment]
Me envia o seu CV e github.

Abraços,

Roni Martins
Consultant
[Descrição: http://gigroup.com.br/assinaturas/gigroup/Wyser.jpg]
------------------------------------
Rua Doutor Fernandes Coelho, 85, 4º andar – Pinheiros - São Paulo-SP
CEP: 05423-040
Email: roni.martins@wyser.com.br<mailto:roni.martins@wyser.com.br>
Site: http://www.wyser.com.br<http://www.wyser.com.br/>
Celular: +55 (11) 9.7660-9608
Fixo: +55 (11) 3135-5461
Skype: roni.martins.rh
Ramal: 461
[http://assinatura.gigroup.com.br/gigroup/Linkdin.png]<https://www.linkedin.com/company/3118347?trk=tyah&trkInfo=clickedVertical%3Acompany%2CentityType%3AentityHistoryName%2CclickedEntityId%3Acompany_company_company_company_company_company_company_3118347%2Cidx%3A0>[http://assinatura.gigroup.com.br/gigroup/youtube-icon-block-png-17.png]<http://www.youtube.com/channel/UCpxlwy-zfxsQ1tRPguKhXVA>
------------------------------------
[cid:image004.jpg@01D4150D.505A2470]
Esta informação é particular e confidencial e está endereçada unicamente ao seu destinatário. Se você não for o destinatário ou a pessoa responsável pela entrega ao destinatário, por favor informe por e-mail ao remetente e imediatamente apague a mensagem e seus anexos sem copiar ou divulgar seu conteúdo. O não cumprimento, poderá ser considerado como uma ação ilegal.

---------------------------

This information is private and confidential and intended for the recipient only. If you are not the addressee or the person responsible for delivering it to the intended addressee, please notify the sender by e-mail and immediately delete the message and any attachments without copying or disclosing its contents. To do so is prohibited and may be unlawful.

De: Henrique Assunção <notifications@github.com>
Enviada em: quinta-feira, 14 de fevereiro de 2019 15:31
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: Roni Martins (WYSER-SP) <Roni.Martins@wyser.com.br>; Author <author@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [São Paulo - SP] Sr Front-End Developer - Wyser (#1802)


Como aplicar pra esta vaga?

**Comment by juulhao** [comment]
Qual email para contato?

**Comment by ronirhwyser2017** [comment]
roni.martins@wyser.com.br<mailto:roni.martins@wyser.com.br>


Roni Martins
Consultant
[Descrição: http://gigroup.com.br/assinaturas/gigroup/Wyser.jpg]
------------------------------------
Rua Doutor Fernandes Coelho, 85, 4º andar – Pinheiros - São Paulo-SP
CEP: 05423-040
Email: roni.martins@wyser.com.br<mailto:roni.martins@wyser.com.br>
Site: http://www.wyser.com.br<http://www.wyser.com.br/>
Celular: +55 (11) 9.7660-9608
Fixo: +55 (11) 3135-5461
Skype: roni.martins.rh
Ramal: 461
[http://assinatura.gigroup.com.br/gigroup/Linkdin.png]<https://www.linkedin.com/company/3118347?trk=tyah&trkInfo=clickedVertical%3Acompany%2CentityType%3AentityHistoryName%2CclickedEntityId%3Acompany_company_company_company_company_company_company_3118347%2Cidx%3A0>[http://assinatura.gigroup.com.br/gigroup/youtube-icon-block-png-17.png]<http://www.youtube.com/channel/UCpxlwy-zfxsQ1tRPguKhXVA>
------------------------------------
[cid:image004.jpg@01D4150D.505A2470]
Esta informação é particular e confidencial e está endereçada unicamente ao seu destinatário. Se você não for o destinatário ou a pessoa responsável pela entrega ao destinatário, por favor informe por e-mail ao remetente e imediatamente apague a mensagem e seus anexos sem copiar ou divulgar seu conteúdo. O não cumprimento, poderá ser considerado como uma ação ilegal.

---------------------------

This information is private and confidential and intended for the recipient only. If you are not the addressee or the person responsible for delivering it to the intended addressee, please notify the sender by e-mail and immediately delete the message and any attachments without copying or disclosing its contents. To do so is prohibited and may be unlawful.

De: Julio Rodrigues <notifications@github.com>
Enviada em: quinta-feira, 14 de fevereiro de 2019 15:54
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: Roni Martins (WYSER-SP) <Roni.Martins@wyser.com.br>; Author <author@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [São Paulo - SP] Sr Front-End Developer - Wyser (#1802)


Qual email para contato?

**Comment by juulhao** [comment]
@ronirhwyser2017 encaminhado.
