### ISSUE TITLE
[São Paulo] Tech Lead (Javascript) - Wyser

### ISSUE THREAD

**Issue by ronirhwyser2017** [frontendbr/vagas#1803]
Líder Técnico (Front-End)

Nosso candidato ideal:
Domina múltiplos frameworks (Javascript) do lado do cliente e do lado servidor, como React, Angular, Backbone, Marionette, etc;
Tem experiência como Líder Técnico de times ágeis;
Manja como dar mentoring técnico;
É referência em Javascript;
Trabalha diretamente com outras squads de engenharia para entregar o código de front-end;
Ajuda a implementar o código de front-end em layouts e modelos no server-side;
Identifica padrões de interface e implementa componentes de UI reutilizáveis;
Trabalha em estreita colaboração com os UX designers e PO’s.

Qualificações requeridas:
Conhecimento avançado de Javascript, HTML5, CSS3, JSON
Padrões web e compatibilidades entre navegadores
Experiência em testes unitários, desenvolvimento orientado a testes e BDD
Experiência com testes de JS
Experimente trabalhar com o Git em um ambiente CI / CD
Experiência com bibliotecas e pré-processadores como Bootstrap, jQuery, SASS / SCSS;
Experiência com práticas e processos ágeis de desenvolvimento: programação em pares, revisão de código, testes automatizados, Scrum, etc

CLT + Benefícios (Assistência Médica + VR de R$ 27/dia + VT + Bônus de até 4 salários/ano + Stock Options após 1 ano)
 
Local: Zona oeste de SP

CVS para roni.martins@wyser.com.br

**Comment by ReactGirl** [comment]
Pra vagar tem que manjar de React, Angular, Backbone  e  Marionette?
