### ISSUE TITLE
[São Paulo] Analista Desenvolvedor(a) Java Sr [CCEE]

### ISSUE THREAD

**Issue by aline-navarro** [frontendbr/vagas#1804]
## Descrição da vaga

Realiza as fases de elaboração de requisitos e da programação de sistemas Java, desenvolve, testa e implementa. Conhece tecnicamente as fases das atividades, identifica e orienta na solução de problemas. Elabora, coordena e orienta atividades de correção e manutenção dos programas. Codifica e realiza os testes, prepara documentação e produz manuais de operação. Realiza a implementação e a manutenção de novos sistemas.

## Local

São Paulo - Paulista (no local)

## Requisitos
* Conhecimentos avançados em: JavaEE, REST, SpringBoot, Spring framework, Web / REST Services / MVC, micro serviços, maven, jenkins, Git, OO, Hibernate, JUNIT, Oracle 
* Checkstyle, findbugs, Websphere 9 
 * Gestão de configuração de artefatos de software utilizando git e svn 

**Diferenciais:**
* Angular 2+, Bootstrap, Node.JS, HTML5, JS, CSS3 
* UML, Archimate 3, TOGAF, Enterprise Architect, Jira, Componentização, Ionic, Apache Cordova, Desenv. Mobile 

## Contratação

PJ a combinar

## Nossa empresa

[A Câmara de Comercialização de Energia Elétrica – CCEE] viabiliza as atividades de compra e venda de energia em todo o País. Promove discussões voltadas à evolução do mercado, sempre orientada pelos pilares da isonomia, transparência e confiabilidade

## Como se candidatar

Interessados (as) enviar CV para aline.navarro@keepsimple.com.br - enviar no assunto: Vaga Desenvolvedor Java

## Labels

- PJ
- Alocado
- São Paulo
- Sênior

**Comment by juulhao** [comment]
E de front, vocês não tem vaga?

**Comment by LFeh** [comment]
Essa vaga é backend, por favor publique no @backend-br ;)
