### ISSUE TITLE
[São Paulo] Analista Desenvolvedor(a) Java [B2W]

### ISSUE THREAD

**Issue by aline-navarro** [frontendbr/vagas#1805]
## Descrição da vaga

Participar ativamente do time para desenvolver, evoluir e manter sistemas de alta escalabilidade, disponibilidade e performance, resilientes e orientados a eventos, atuando diretamente em modelagem e manutenção dos repositórios de dados (SQL/no-SQL) criação e manutenção de serviços REST em JAVA com regras de negócio (CRUD). 
Colaborar com ideias que possam melhorar nossos sistemas e a vida dos nossos usuários;
Estar disposto a aprender e a ensinar;
Ser responsável pela nossa plataforma;
Estar sempre atento a oportunidades para melhorar o código e nossos processos.

## Local

 São Paulo, Vila Olímpia (no local)

## Requisitos

* Graduação em Ciência da Computação ou áreas relacionadas ou experiência profissional equivalente;
* Forte base em programação orientada a objeto: modelagem, desenvolvimento e testes de aplicações Java;
* Mínimo 3 anos de experiência.
* Análise de requisitos técnicos e funcionais;
* Desenvolvimento de APIs REST e micro-serviços;
* Spring Boot/Data/Cloud, JPA, Hibernate;
* Ferramentas de controle de código GIT;
* Banco de dados relacionais;
* Desenvolvimento em docker.
* Ambiente Linux;
* Gerenciador de dependências e build (Maven, Gradle, etc).
* Inglês intermediário: Ser apto a ler documentações, debater soluções em fóruns técnicos e escrever o código-fonte dos sistemas.

## Contratação

CLT

## Como se candidatar

Interessados (as) enviar CV para aline.navarro@keepsimple.com.br - enviar no assunto: Vaga Desenvolvedor Java

## Labels

- Alocado
- CLT

**Comment by LFeh** [comment]
Essa vaga é backend, por favor publique no @backend-br ;)
