### ISSUE TITLE
[Belo Horizonte/MG] Front-End Developer na QUEIMA DIÁRIA

### ISSUE THREAD

**Issue by megandavulpi** [frontendbr/vagas#1807]
### Sobre a empresa: Queima Diária

Maior Startup de Home Fitness da América Latina!

### Descrição: Ocupações do cargo

Programar e executar projetos do início, assim como participar da melhoria dos projetos que já estão em operação.

### Benefícios

- Vale Refeição ou alimentação; R$21,35/dia - Lanche Diário
- Vale Transporte; 
- Plano de Saúde;( Unimed Enfermaria) Descontando somente a coparticipação.
- Plano odontológico; Sem desconto algum 
- Politica de ensino de línguas (inglês) na própria empresa onde o profissional terá uma ajuda de custo de 50%.
- Acesso à plataforma
-Horário flexível (chegada até as 10h)
- No DressCode
- Flexibilidade do horário de almoço 1h até 2h.

### Aptidões e qualidades

Buscamos um profissional flexível e proativo que saiba atuar com autonomia e responsabilidade. Precisa saber trabalhar em equipe, ter um perfil atuante e pró-ativo. É necessário alguém com um perfil brilhante e impar, com capacidade e vontade de se tornar uma referencia na área. Alguém fera!

### Informações da empresa

A Queima Diária é uma Startup em constante crescimento, que desde o seu inicio em meados 2015 vem crescendo e ganhando cada vez mais espaço em seu mercado. Sua proposta é promover o bem estar das pessoas, criando um espaço de conhecimento e valorização da vida saudável e nutrição. Tudo isso através de uma plataforma interativa e intuitiva que fornece diferentes programas e treinos para públicos de diversos perfis. Uma empresa inovadora, busca profissionais inovadores, criativos e que pensem fora da caixa para compor sua equipe.

### Labels

Alocado
Pleno/Junior

### Candidatar: http://bit.ly/queimafront_github

**Comment by ReactGirl** [comment]
> É necessário alguém com um perfil brilhante e impar,

Quando contratarem o Einsten, me passem o github dele para eu ver esses projetos magnificos
