### ISSUE TITLE
[São Paulo/SP] Frontend-Developer | BettrAds

### ISSUE THREAD

**Issue by luizeduard0** [frontendbr/vagas#1809]
#
## Descrição da vaga
Participar ativamente no desenvolvimento de um produto disruptivo voltando para segmento de Adtechs. Estamos procurando pessoas que realmente queiram fazer a diferença e estejam procurando crescimento na carreira.

Procuramos um perfil pleno ou senior.

## Local
São Paulo/SP

#### Diferenciais
- Chefia horizontal, todos tem voz na empresa.
- Te valorizamos pelo seu resultado e não pelo tempo trabalho. Há muito espaço p/ crescer
- Trabalhamos com as tecnologias mais atuais
- Horário flexível
- Você pode trabalhar de qualquer lugar que quiser

## Requisitos

**Obrigatórios:**
- Base sólida de JS
- ReactJS

**Desejáveis:**
- Redux
- Webpack
- NodeJS

**Diferenciais:**
- Visão empreendedora
- Se comunicar bem em inglês
- GraphQL
- Apollo

## Contratação
PJ a combinar

## Nossa empresa
Somos uma startup AdTech com investimento realizado e estamos construindo o futuro do marketing digital.

## Como se candidatar

Por favor envie um email para luiz@bettrads.com com seu CV anexado - enviar no assunto: [VAGA FRONTEND] SEU_NOME

OBS: Se você tiver um Github relevante, este pode dispensar a necessidade do teste. Caso contrário, só aceitamos candidaturas com o desafio realizado.

## Tempo médio de feedbacks
Uma vez enviado todas as informações (desafio incluso) damos um retorno em 5 dias úteis.

**Comment by rbuzatto** [comment]
@luizeduard0 eu tenho a impressão que faltou o link para realização do desafio?

**Comment by pedromuraki** [comment]
@luizeduard0 a vaga está aberta ainda? Faltou o link do teste.
