### ISSUE TITLE
[São Paulo/SP] Front-End Developer na Skore

### ISSUE THREAD

**Issue by caiofsouza** [frontendbr/vagas#1810]
## Descrição da vaga

Estamos expandindo nosso time de produto e de desenvolvimento para dar suporte ao nosso crescimento e à nossa recente expansão internacional. 

## Local

Ficamos localizados no Google Campus, São Paulo, SP, próximo a estação Brigadeiro do metrô. É um lugar incrível onde você ainda vai poder interagir com diversas outras startups, participar de eventos, etc.  

## Requisitos

**Obrigatórios:**
- Que você tenha paixão por construir coisas incríveis e não esteja procurando apenas mais um trabalho para ganhar um pouco melhor. 
- Que seu drive seja o de entender e se envolver com o negócio. Não queremos robôs.
- Que você seja consistente, organizado, que entregue o que combina e que seja pontual nas reuniões que marcar com seu time
- Que você seja humilde para saber que tem muito o que aprender e generoso pra saber que sempre pode ensinar. 
- Que você seja um desenvolvedor excepcional, comprometido com a qualidade e segurança do seu próprio código. 
- Gostar de boas discussões sobre produto, layout e negócio para tornar a equipe cada vez mais experiente.
- Ter um entendimento legal de HTML5, CSS3 e Javascript (ES6+) para criar interfaces responsivas e modernas.
- Saber manipular o DOM sem o uso de libs e frameworks.
- Já ter trabalhado com Vue.js e conhecer sua estrutura e pelo menos o básico de Vuex
- Conhecer Webapck e afins, com pelo menos o básico pra configurar.
- Já ter trabalhado com Git.

**Desejáveis:**
- Conhecer a estrutura e arquitetura do Nuxt.
- Git flow no dia-a-dia.
- CSS3 flexbox.
- Já ter trabalhando com AWS.
- Docker.
- Eslint, Babel e Stylelint.

## Contratação

PJ a combinar

## Nossa empresa

Skore é uma startup que está mudando a forma como times inovadores aprendem. 

Você pode pensar na gente como se fossemos o AWS da educação digital. Explicando melhor: a maior parte das plataformas de learning que existem aprisiona seus usuários em um conceito engessado e pre-determinado de como eles deveriam aprender. 

A gente faz diferente. O Skore é uma plataforma de micro-serviços que pode ser utilizada de formas diferentes por clientes com culturas diferentes. Por exemplo: 

- Startups inovadoras como o Nubank, Dr Consulta, Creditas conectam nosso produto com as ferramentas que já usam no seu dia-a-dia como Slack e Google Drive. Desta forma, a gente os ajuda a organizar o conhecimento do jeito que eles já estão acostumados a trabalhar.
- Empresas consolidadas como o Itaú usam nosso produto para entregar programas de capacitação altamente escaláveis para seus times espalhados em centenas de agências.
- Times extremamente distribuidos, como os 40.000 vendedores da Via Varejo acessam conhecimento diariamente no nosso produto via um chatbot. 

Todos estes produtos são construídos com a nossa plataforma. Esta é a nossa proposta de valor que ninguém no mundo replicou. 

Além disso, nosso stack é usado na construção do Paperbot, um bot para Slack que usa inteligencia artificial para sugerir conteúdos similares aos discutidos. Este produto gratuito é usado em mais de 6.000 empresas mundo afora. 

## Como se candidatar

Acesse https://careers.skore.io/o/frontend-engineer

## Labels

- Alocado
- PJ
- Júnior
- Pleno

**Comment by ReactGirl** [comment]
> * Que você tenha paixão por construir coisas incríveis e não esteja procurando apenas mais um trabalho para ganhar um pouco melhor.

Facil falar isso quando voce é CEO com 2 milhoes na conta, agora se voce mal consegue pagar o aluguel e tem familia, parece soar mal querer ganhar mais E construir coisas incriveis.

**Comment by brunopoc** [comment]
Querer ganhar mais é algo ruim? Não seria isso um dos maiores motivos para qualquer ser humano querer ser um profissional melhor?
