### ISSUE TITLE
[Campinas/SP] Front-End Developer na inGaia

### ISSUE THREAD

**Issue by conradoramalho** [frontendbr/vagas#1811]
## Descrição da vaga

Estamos à procura de um Front-End Developer para juntar-se à nossa equipe de TI.
Você será inicialmente responsável pela manutenção e desenvolvimento front-end de novas funcionalidades, utilizando a tecnologia React/Redux.

## Local

Av. José de Souza Campos, 1549 - Cambuí, Campinas - SP, 

## Benefícios

- Plano de saúde
- Seguro de vida
- Vale Refeição
- Vale Transporte
- Mesa de Sinuca
-  Lanches e festas de aniversário.
- Apoio Pass (Suporte Pessoal).

## Requisitos

**Obrigatórios:**
- Dominio de Javascript, HTML e CSS;
- Experiência em React (Redux, Redux Saga, Styled Components, etc);
- Desenvolvimento de páginas responsivas;
- Domínio em algum pré-processador de CSS (Sass, Less, etc)
- Experiência na integração de front-end e back-end através de REST APIs;
- Experiência com Git.

**Diferenciais:**
- Experiência com metodologias ágeis (SCRUM, Kanban, Lean, etc);
- Experiência com testes automatizados;
- Conhecimento em ferramentas de desenvolvimento (Webpack, Gulp, Npm, Babel, etc);
- Desenvolvimento básico de back-end (Node.js)

## Contratação

CLT

## Nossa empresa

-  **Somos a inGaia:**  A maior empresa de tecnologia do setor imobiliário, com uma plataforma de soluções completa para os profissionais deste mercado. Ajudamos mais de 3 milhões de proprietários, compradores e imobiliárias a fecharem negócios.
- **Nós nascemos para construir um novo mercado imobiliário:** Com soluções que geram mais valor e ajudam os corretores de imóveis a trabalharem de forma mais profissional e eficiente.
- **Nosso time:** Performances individuais são sempre valorizadas, mas não toleramos individualismo e falta de ética. Trabalhamos juntos e somos positivos em todas as nossas atitudes, o mi-mi-mi não faz parte da nossa cultura.

## Como se candidatar

Por favor envie um email para [stefano.baldo@ingaia.com.br](mailto:stefano.baldo@ingaia.com.br) com seu CV anexado. Enviar no assunto:  Front-End Developer - GitHub
 
## Labels

- Alocado
- CLT
- Júnior
- Pleno
- Sênior

**Comment by AlbericoD** [comment]
Apenas vale transporte? ou tem vale combustível? sou de americana-sp

**Comment by conradoramalho** [comment]
@AlbericoD no momento apena Vale Transporte, creio que esse ano a empresa disponibilize vale combustível. Já foi sugerido 😄
