### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor(a) JavaScript no ESTUDIO CRU

### ISSUE THREAD

**Issue by ESTUDIOCRU** [frontendbr/vagas#1814]
## Descrição da vaga

Somos um estúdio de design. Buscamos uma pessoa desenvolvedora javascript com foco em aplicação web e uso de APIs para atender clientes de diversos ramos com ênfase em aplicações visuais e interatividades.

## Local

Gávea — Rio de Janeiro

## Requisitos

**Obrigatórios:**
- React / Vue / Angular
- REST APIs
- ES6
- GIT
- SASS

**Desejáveis:**
- Experiência com Rest API do Wordpress
- Webpack
- Typescript
- Node.js
- Headless CMS (Prismic, Contentful, etc…)
- AWS/Google Cloud

**Diferenciais:**
- Manjar de sistemas de design é **o diferencial**

## Contratação

PJ a combinar

## O ESTUDIO CRU

Somos um estúdio de design. Trabalhamos com marcas e pessoas desenvolvendo ideias e transformando conceitos em aplicações visuais.

## Como se candidatar

Por favor envie um email para contato@estudiocru.com com seu CV anexado e portfólio de projetos JS desenvolvidos com título *Vaga Desenvolvedor(a) JavaScript*

## Labels

- Alocado
- PJ
- Pleno

**Comment by thiagorowof** [comment]
Possibilidade de remoto

**Comment by ESTUDIOCRU** [comment]
Somente local.

**Comment by ESTUDIOCRU** [comment]
Ainda estamos recebendo contatos pra vaga ;)

**Comment by ESTUDIOCRU** [comment]
Ainda aberta

**Comment by renan-ramos** [comment]
Bom dia, tenho conhecimentos básicos nos 3 frameworks e conhecimento em todos os outros itens obrigatórios, conhecimento em webpack, typescript e Node.Js e atualmente estou desenvolvendo o Design System da Diretoria de Análise de políticas públicas da FGV. O nível de conhecimento dos frameworks é "eliminatório" ou não?

**Comment by ESTUDIOCRU** [comment]
@renan-ramos não, manda um email pra gente ;)

**Comment by renan-ramos** [comment]
Blz, envio hoje de noite
