### ISSUE TITLE
[Fortaleza] Front-End Developer no Grupo Casa Magalhães

### ISSUE THREAD

**Issue by joelxr** [frontendbr/vagas#1816]
## Descrição da vaga

O Grupo Casa Magalhães está a procura de desenvolvedores Front-End.
Venha fazer parte da nossa equipe!

## Local

Alocado no escritório em Fortaleza, Ceará.

## Benefícios

- Plano de saúde;
- Restaurante e estacionamento internos;
- Auxílio transporte ou combustível (sem descontos na folha de pagamento)

#### Diferenciais

- Espaço físico composto de áreas de convivência, lazer e descanso;
- Programa de Qualidade e Vida;
- Ações Preventivas de saúde;
- Programa de Desenvolvimento Profissional;
- Gestão de Carreira;
- Ambiente desafiador, aprendizado constante, convívio com excelentes profissionais e clima organizacional diferenciado.

## Requisitos

**Obrigatórios:**

- JavaScript Moderno (ES6);
- HTML5,
- CSS3 e SCSS;
- Compreensão de: reatividade, componentização com ou sem estado e reusabilidade.
- Fluência no versionamento de código com Git.
- Experiência com algum dos frameworks:
  - Vue,
  - Angular ou
  - React

**Desejáveis:**
- NPM (ou Yarn),
- Gulp,
- Webpack e
- Babel;

**Diferenciais:**
- Experiência com React Native.
- Experiência com GraphQL.
- Design skills ou forte senso de experiência do usuário.
- Projetos _Open Source_.

## Contratação

CLT ou PJ a combinar.

## Nossa empresa

O Grupo Casa Magalhães atua na indústria de TI, possuímos operações em todos os Estados do Brasil. Somos especialistas no desenvolvimento de software de frente de loja, gestão empresarial e aplicativos para dispositivos móveis, focados para o varejo. Inovação, ética, foco no cliente, excelência em serviços e compromisso com os resultados são valores presentes na nossa cultura organizacional, por isso estamos entre as 100 melhores empresas para se trabalhar do Brasil, no segmento de TI, segundo o Great Place to Work.

## Como se candidatar

Os interessados deverão enviar o currículo para o e-mail vagas@casamagalhaes.com.br com o CV anexado e, se desejar, telefone para contato. Colocar no assunto: __Vaga Desenvolvedor Front End.__

## Labels

- CLT
- PJ
- Pleno
- Sênior
- Presencial

**Comment by vcpablo** [comment]
Aceita remoto?

**Comment by joelxr** [comment]
Boa noite @vcpablo, trabalhar remoto não é uma opção.
A vaga é presencial.

**Comment by ojaguar27** [comment]
Aceitam candidatos do Rio de Janeiro?

**Comment by joelxr** [comment]
Oi @ojaguar27! Sim, a seleção pode acontecer pelo Skype, mas o escritório é localizado em Fortaleza/CE e a vaga é presencial.

**Comment by ojaguar27** [comment]
Curriculo enviado o/

**Comment by joelxr** [comment]
Vaga ainda não foi preenchida. :)

**Comment by EzequielBrilhante** [comment]
Bom dia, a vaga ainda está aberta ?

**Comment by joelxr** [comment]
@EzequielBrilhante sim está!

**Comment by AdoniasLemos** [comment]
Eu enviei o currículo para o email indicado... Mas até o momento não recebi nenhum retorno @joelxr
