### ISSUE TITLE
Front-end Developer: React Native

### ISSUE THREAD

**Issue by RNiero** [frontendbr/vagas#1818]
O Grupo GBI busca profissionais com o perfil abaixo para compor o seu time:

Oportunidades para perfis Jr, Pl e Sr

- Experiência com desenvolvimento Android, IOS, Geolocation APIs
- Conhecimento de algum framework como AngularJS, Vue/Fue Native, Ionic
- Contratação inicial: 3 meses

Local de trabalho: Aeroporto de Congonhas | Vila Mariana | Alphaville
Enviar CV com pretensão salarial CLT e PJ para rrodrigues@grupogbi.com

**Comment by DEXTERNATAN** [comment]
@RNiero Existe a possibilidade de trabalho remoto ...

**Comment by eduardojmatos** [comment]
@RNiero a vaga está fora do padrão que usamos nas issues. Se puder, reabra uma nova ou edite essa  até o fim do dia pra mantermos aqui

**Comment by Mendrone** [comment]
@RNiero vou manter a vaga fechada até a atualização da issue conforme a template proposta, ok?
