### ISSUE TITLE
[São Paulo] Front-End Developer na Magnetis

### ISSUE THREAD

**Issue by luisfmsouza** [frontendbr/vagas#1820]
## Descrição da vaga

Você gosta de trabalhar com autonomia, responsabilidade e ver o real impacto do seu trabalho no dia a dia das pessoas?

Tem paixão por tecnologia, inovação e sabe trabalhar em um ambiente dinâmico?

Valoriza relações duradouras e transparentes no trabalho, com um time unido?

Seu lugar pode ser na Magnetis!

#### O que você irá fazer:
- Manutenção e desenvolvimento de sistemas usando JavaScript, desde novas funcionalidades para clientes finais e até integrações entre sistemas internos e externos
- Colaborar na definição da arquitetura dos nossos sistemas internos, para permitir que novos produtos e funcionalidades sejam desenvolvidos dentro do nosso ecossistema de apps
- Trocar experiências e conhecimentos com demais pessoas e times de desenvolvimento através de Pull Requests, discussões técnicas e palestras internas
- Participar da melhoria contínua dos processos e práticas dos times de engenharia e produto

## Local

Remoto ou Escritório, São Paulo - Pinheiros

## Benefícios

- Plano de saúde e Odontológico
- Vale-refeição / vale-alimentação
- Vale-transporte
- Oportunidade de ganhar stock options (participação na empresa)
- Verba educacional, para participação em cursos e eventos
- Flexibilidade para trabalho remoto ou no nosso escritório próximo a estação Faria Lima do metrô
- Para remotos fora da cidade São Paulo: ajuda de custo para você montar o seu ambiente ideal de trabalho

## Requisitos

**Obrigatórios:**
- Pelo menos 3 anos de experiência desenvolvendo sistemas web/mobile usando JavaScript, preferencialmente React/React-Native ou similares;
- Valorizar qualidade, testabilidade e manutenabilidade do código;
- Familiaridade com uso de Git no dia a dia;
- Familiaridade com práticas de processos ágeis e gestão de projetos;
- Interesse em trabalhar em ambiente de desenvolvimento de produtos, com autonomia e mudanças constantes;
- Boas habilidades de comunicação e escrita, tanto em português quanto inglês;
- Boas noções de arquitetura e design de sistemas utilizando programação funcional;

**Diferenciais:**
- Interesse pela área de investimentos e finanças pessoais
- Experiência profissional com Redux e princípios de programação funcional
- Experiência com release de aplicativos para lojas virtuais
- Preocupação com experiência dos usuários (UX)

## Contratação

CLT

## Nossa empresa

A Magnetis é uma fintech e gestora de investimentos digital que desde 2015 tem a missão de ajudar as pessoas a investir no que importa.

Nosso time diverso e multidisciplinar é apaixonado por tecnologia e inovação. Somos guiados por dados, sempre colocando a missão de impactar positivamente a vida financeira dos nossos clientes em primeiro lugar.

Estamos buscando pessoas desenvolvedoras para trabalhar na evolução dos nossos sistemas e aplicações escritas em Ruby, Elixir e JavaScript. Nossos times são responsáveis por desenvolver funcionalidades e integrações entre aplicações internas e externas, buscando prover a melhor experiência de investimento para os nossos clientes sem deixar de lado a qualidade e escalabilidade do que é colocado em produção.

Valorizamos transparência, autonomia e integridade, e o nosso time é remoto por todo o Brasil.

## Como se candidatar

Por favor, use o Workable para se candidatar a vaga: https://magnetis.workable.com/j/69DAAA9A41

Mencione que chegou até nós pelo Front-End Brasil 💚

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: souza@magnetis.com.br

## Labels

- CLT
- Pleno
- Remoto

**Comment by rios0rios0** [comment]
Olá!
Existem vagas similares a esta, para FullStack, BackEnd ou Engineer?

**Comment by luisfmsouza** [comment]
Temos sim @rios0rios0 !
Dá uma olhadinha no workable, talvez alguma te agrade: https://magnetis.workable.com/

**Comment by esl-douglas** [comment]
Mandei!

**Comment by LopesAlysson** [comment]
Já submeti!
