### ISSUE TITLE
[RIBEIRÃO PRETO] Desenvolvedor Front-End (React) - Pleno - [BEBLUE]

### ISSUE THREAD

**Issue by KevinMarcelOriginal** [frontendbr/vagas#1821]
Desenvolvedor Front-End (React) - Pleno

A Beblue está procurando por profissionais inovadores e apaixonados por tecnologia para se juntar a nós e nos ajudar na incrível e desafiadora caminhada de inovação nas indústrias de pagamentos e recompensas no Brasil. Na Beblue você terá a oportunidade de aplicar os seus talentos e energia criativa para entregar soluções de alta performance em uma das mais promissoras e crescentes Startups do Brasil. Temos múltiplas áreas de especialização disponíveis como: 

Micro-serviços Java/Kotlin com Spring Boot/Cloud;

Micro-serviços C# .Net Core;

Mobile Android Java/Kotlin;

Mobile iOs Swift;

Web React e Redux;

DevOps Terraform e AWS;

Requisitos e Responsabilidades:

Como um desenvolvedor Front-End Pleno você será responsável por:

Mindset empreendedor, ter postura de dono e ser responsável pela entrega dos projetos; 

Ser adaptável, aprender rápido, entender o contexto da "big picture", e conseguir aplicar abordagens “out of the box” para atingir seus objetivos;

Participar do projeto e implementar soluções de software além de acompanhar os desenvolvedores menos experientes durante o desenvolvimento do produto;

Colaborar na arquitetura das soluções focando em requisitos não funcionais como disponibilidade, escalabilidade e performance;

Desenvolver com alto padrão focado em entregas de software de qualidade com cobertura de código, testes automatizados, integração contínua, etc…;

Desenvolver e executar planos de testes para validação de aplicações e revisar o resultado dos testes;

Trabalhar em conjunto com o time de design, no projeto de interfaces e UX do produto, seguindo fielmente as especificações;

Utilizar API’s RESTFul e abstrair componentes para a criação de aplicações Híbridas ou SPA’s;

Utilizar ferramentas para inspeção e monitoramento do comportamento do sistema.

Educação e Experiência:

3+ anos de experiência com Programação Javascript para Front-End utilizando algum framework ou biblioteca como React e Redux e seu ecossistema;

1+ anos de experiência com ciclo de desenvolvimento Agile;

Formação de ensino superior em Ciência da Computação ou equivalente;

Desejável conhecimento em alguma linguagem de programação Back-End.

Conhecimentos e Habilidades:

Excelente comunicação oral;

Habilidades de escrita clara e direta;

Fluência em Português;

Inglês Técnico para Leitura e Escrita;

Experiência com cultura Agile;

Experiência com O.S. Linux/Unix;

Experiência com o ecossistema Web (Task Runners, Yarn/NPM, Webpack, Pré-processadores  como SAAS e Babel);

Fluência em JavaScript, HTML5, CSS3;

Fluência em React e Redux e seu ecossistema;

Experiência com GIT e GITFlow; 

Experiência com o desenvolvimento de interfaces responsivas;

Conhecimento sobre os princípios de TDD e BDD;

Conhecimento sobre Integração Contínua e Entrega Contínua (Jenkins, Drone.io, CircleCI, etc...);

Conhecimento sobre ferramentas de monitoramento (NewRelic, Sentry, Datadog, etc...);

Conhecimento sobre AWS (Cloudfront, S3, API Gateway, Route53, ECS, etc...);

Conhecimento sobre Aplicações conteinerizadas com Docker.
LINK DE CANDIDATURA: https://jobs.kenoby.com/beblue/job/desenvolvedor-front-end-react-pleno-5-vagas/5c3c4fb97ac8dc5608b377a7

**Comment by felipefialho** [comment]
A vaga vai ficar fechada até se adequar ao nosso template :)
