### ISSUE TITLE
[Rio de Janeiro] Front-End Developer / React no ProEnem

### ISSUE THREAD

**Issue by aroff** [frontendbr/vagas#1825]
## Descrição da vaga

*ProEnem* é uma das startups de ensino à distância que mais cresce no Brasil e está contratando desenvolvedores para atuar em projetos baseados em React JS/Native e Node.

## Local

Remoto ou Presencial no Rio de Janeiro - Zona Oeste

#### Diferenciais

- Horário flexível
- Você escolhe o seu equipamento de trabalho

## Requisitos

**Obrigatórios:**
- Pelo menos 2 anos de experiência real com React / Redux
- Fluência em HTML/CSS
- Styled Components

**Desejáveis:**
- Typescript
- NodeJs
- Experiência React Native será um diferencial

## Contratação

PJ a combinar. 

## Nossa empresa

Nós somos cerca de 100 colaboradores e nosso escritório fica no Centro Metropolitano, próximo ao Shopping Metropolitano (Rua Abelardo Bueno), com uma infra-estrutura super moderna!
Referências: www.proenem.com.br e https://www.youtube.com/user/ProENEMOficial

## Como se candidatar

Por favor envie um email para reactdev@proenem.com.br com seu CV anexado - enviar no assunto: "Vaga React". 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias úteis.

## Labels

- Alocado
- PJ
- Pleno
- Remoto
- Sênior

**Comment by renanlbl** [comment]
O e-mail diz que está com problemas e não consegue receber e-mails
