### ISSUE TITLE
[São Paulo] Desenvolvedor Front - Reamp

### ISSUE THREAD

**Issue by Brunier** [frontendbr/vagas#183]
## Descrição da vaga

Pessoal, estamos precisando de profissionais que esteja interessado em aprender novas tecnologias Javascript (Node, react c/ redux, mocha, enzyme e outras tecnologias que pertecem a stack javascript) para desenvolver interfaces para aplicações de Big Data.

## Local

Escritório, São Paulo - Paulista

## Benefícios
- Vale-transporte
- Vale-refeição
- Assistência médica e odontológica 
- Aulas de inglês duas vezes por semana
- Cerveja no office às sextas-feiras

## Requisitos

**Obrigatórios:**
- Conhecimentos geral em javascript e algum framework

**Diferenciais:**
- Saber React

## Contratação
CLT ou estagiário.

## Nossa empresa
A Reamp é uma empresa do campo de publicidade online com diversos produtos para atender as seguintes áreas:
- Adserving 
- Business Intelligence 
- Ad Operations 
- Media Operations

Nossos produtos usam tecnologias modernas e muitos são de missão crítica, com SLA de até 99.98%. Trabalhamos com ferramentas de Bigdata, busca e frameworks modernos no front-end (onde também entram decisões de Data Visualization).

## Como se candidatar
Envie um e-mail para bruno.arcelino@reamp.com.br

**Comment by brunooomelo** [comment]
Junior, pleno ou senior?

**Comment by Brunier** [comment]
Estamos contratando estágio e junior principalmente (talvez role uma vaga de pleno, mas agora precisamos desses 2)

**Comment by Brunier** [comment]
Júnior

Em 2 de dez de 2016 5:38 PM, "Bruno Melo" <notifications@github.com>
escreveu:

**Comment by LFeh** [comment]
Done!

**Comment by JoaoAntonioMaruti** [comment]
Enviado

**Comment by Brunier** [comment]
Obrigado @LFeh, recebemos vários perfis incríveis vindo daqui!
Na próxima vaga que abrir, vou postar aqui com certeza.
Vlw!

**Comment by LFeh** [comment]
Boa @Brunier, contrataram por aqui?

**Comment by camilatigre** [comment]
@Brunier 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by Patrick-Isidoro** [comment]
A Vaga ainda tá aberta, ou abriram novas vagas Jr ou Estágio?!
