### ISSUE TITLE
[São Paulo] Front-End Developer na [BR MENDES CONSULTORIA]

### ISSUE THREAD

**Issue by mendesbruna** [frontendbr/vagas#1830]
## Descrição da vaga

Projeto REACT e GraphQL.

## Local

Escritório, São Paulo - Pinheiros

## Requisitos

**Obrigatórios:**
- acima de 1 ano de experiência com React
- acima de 1 ano de experiência com GrapQL

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para recrutamento@brmendesconsultoria.com.br com seu CV anexado - enviar no assunto: Vaga Front-end React

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.

## Labels

- Alocado
- PJ

**Comment by felipefialho** [comment]
Qual o nivel da vaga?

**Comment by mendesbruna** [comment]
Bom dia.

Vaga nível Pleno a Sênior.

Att.,

Bruna Mendes 
Recrutamento & Seleção | Recursos Humanos
Especializada em Gente. 
Gente especializada para sua empresa.
(11) 2281-8263 / (11) 98754-4824 - Whatsapp
www.brmendesconsultoria.com.br [http://www.brmendesconsultoria.com.br/]
Em 25/02/2019 19:39:57, Felipe Fialho <notifications@github.com> escreveu:
Qual o nivel da vaga?

**Comment by washingtondeveloper** [comment]
Bom dia.

Qual o local de Pinheiros (próximo da estação ou um ponto de referência...) ?

**Comment by mendesbruna** [comment]
Bom dia,

Próximo a estação fradique coutinho.

Att.,

Bruna Mendes 
Recrutamento & Seleção | Recursos Humanos
Especializada em Gente. 
Gente especializada para sua empresa.
(11) 2281-8263 / (11) 98754-4824 - Whatsapp
www.brmendesconsultoria.com.br [http://www.brmendesconsultoria.com.br/]
Em 26/02/2019 10:23:48, Washington Martins Silva <notifications@github.com> escreveu:
Bom dia.
Qual o local de Pinheiros (próximo da estação ou um ponto de referência...) ?
