### ISSUE TITLE
[Ipatinga/MG] Web Designer [Pleno] na CAST GROUP

### ISSUE THREAD

**Issue by RecrutamentoCastgroup** [frontendbr/vagas#1831]
Descrição da vaga
Estamos buscando um(a) profissional que possua experiência com JQuery, Css, Html5, Bootstrap, Mobile First, Ajax, Single Page, UX, usabilidade e metodologia ágil. Além dos conhecimentos técnicos, buscamos uma pessoa que tenha facilidade e goste de trabalhar em equipe, que seja engajada e que dê tudo de si nos projetos. 
Local
Alocado no cliente – Ipatinga/MG.
Benefícios
•	Plano de saúde 
•	Plano odontológico
•	Seguro de vida
•	VR ou VA
•	VT
Diferenciais
•	Plano de carreira
•	Oportunidade de trabalhar com uma equipe grande e diversificada
Requisitos
Obrigatórios:
•	2 anos de experiência como Web Designer.
•	Experiência em desenvolvimento front-end.
•	Graduação na área de TI completa. 
Desejáveis:
•	Facilidade em trabalho em equipe
Contratação
CLT com salário a combinar.
Nossa empresa
Com 28 anos de mercado, a Cast group é uma empresa nacional de Tecnologia da Informação e automação com larga experiência em grandes projetos para as áreas privada e pública, que atua com consultoria e soluções de TI e TA.
Hoje, a Cast group é reconhecida por seus mais de 320 clientes, especialmente nas áreas de finanças, indústrias e serviços, como, Banco do Brasil, Cielo, Datasus, Vale, Cemig, Gerdau, EDP, Eletrobrás, Grupo Petrópolis, Atento, Renault, Randon, Bosh, Ipiranga Agroindustrial, DrogaRaia e Banco Central do Brasil.
Como se candidatar
Por favor, envie um email para ana.jardim@castgroup.com.br com seu CV anexado - enviar no assunto: Web Designer Pleno.
Tempo médio de feedbacks
Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: ana.jardim@castgroup.com.br.
Labels
•	Alocado
•	CLT
•	Pleno 
•	Designer
•	Front-end
•	UX

**Comment by felipefialho** [comment]
Vaga fechada até se adaptar ao template.
