### ISSUE TITLE
[São Paulo] Front-End Developer na Sallve

### ISSUE THREAD

**Issue by Calzzetta** [frontendbr/vagas#1832]
## Descrição da vaga

Buscamos por uma pessoa muito fera para desenvolver e manter nosso front-end que se sinta confortável em nos ajudar a encontrar ótimas soluções para melhorar a experiência do usuário.

## Local

Nosso escritório fica na WeWork - Rua Pequetita, 111 - São Paulo

## Benefícios
- Plano de Saúde
- Vale Transporte
- Vale Refeição

#### Diferenciais
- Ambiente Informal
- Horários flexíveis
- Aberta a novas ideias e sugestões

## Requisitos

**Obrigatórios:**
- Ser apaixonada(o) por desenvolvimento de software e tecnologia;
- Desenvolvimento em Wordpress (criação e customização da nossa interface);
- Conhecimentos em desenvolvimento web (HTML5, CSS, JS, PHP);
- Ter facilidade para trabalhar dentro de times multidisciplinares;
- Design responsivo

**Desejáveis:**
- Saber trabalhar com ferramentas de controle de versão, gostamos do GIT;
- Conhecer boas práticas de UX

**Diferenciais:**
- Conhecer AngularJS, ReactJS ou VueJS;
- Experiência com softwares de edição de imagem

## Contratação
- CLT

## Nossa empresa
Saiba mais sobre a Sallve no nosso site: https://www.sallve.com.br/sobre

## Como se candidatar
Nos envie um e-mail com o seu currículo para douglas@sallve.com com o assunto "Vaga Front-End Developer - Seu Nome"

## Labels

- CLT
- Júnior
- Pleno

**Comment by otaviogui** [comment]
Somente presêncial ou consegue um remoto?

**Comment by adeonir** [comment]
Remoto viria bem!

**Comment by fa-sousa** [comment]
E-mail enviado !

**Comment by acamilass** [comment]
Enviado!

**Comment by Calzzetta** [comment]
Sallve @otaviogui e @adeonir. Obrigado pelo interesse! Nesse momento buscamos por alguém que possa estar perto da gente. Abraço!

**Comment by leandrosouza0786** [comment]
Enviado =]'

**Comment by KarinaQueiroz** [comment]
Enviado :))

**Comment by mariana-cunha** [comment]
Enviado! :)

**Comment by 9imeio** [comment]
Olá, vocês aceitam candidatos de outro estado? Estou procurando me realocar e me encaixo no Junior :)

**Comment by Calzzetta** [comment]
Sallve @9imeio, claro! Conversamos via hangouts 👍
