### ISSUE TITLE
[São Caetano do Sul - SP] Fullstack Developer (PL|SR) - Pixeon

### ISSUE THREAD

**Issue by looslidias** [frontendbr/vagas#1833]
# Our company

[Pixeon](https://www.pixeon.com/) was born with the mission of providing health care solutions in an easy and intuitive that people don't even realize it.
Our innovative solutions are the most advanced software for hospitals and laboratories. We are proud of our amazing and challenging working environment.

Excited about enhancing thousand of health care clients? Join us!

Pixeon office in Sao Caetano do Sul (the best Brazilian city to live according [Exame magazine](https://exame.abril.com.br/brasil/as-50-melhores-cidades-do-brasil-para-se-viver-segundo-onu/) is now hiring for the position of **Fullstack Developer**!

## Job description

Maintenance and refactor of [LIS](https://www.pixeon.com/solucoes/para-laboratorios/) solutions using ASP.NET along with webforms.
In order the support the growing client demands, the long-term chalenge is migrating to a microservices architecture.

## Place

[Sao Caetano do Sul - BR](https://goo.gl/maps/aQQJhoFZxrE2)

## Benefits

- Near train station
- Relaxed place with snacks
- Periodic tech presentations
- Opportunity to hands-on backend, frontend and mobile as well

## Requirements

Required knowledge

- 4+ years of front-end (or fullstack) experience
- Web framework (Vue.js, Angular, Polymer, React.js or others)
- Standard MVC, Clean Architecture and derivatives
- MVC framework (ASP.NET, Spring MVC, Django, Ruby on Rails, Hapi.js or others)
- SQL and NoSQL databases (SQLServer, PostgreSQL, Mongo or others)
- Microservices architecture

Desirable knowledge

- 6+ years of front-end (or fullstack) experience
- Progressive Web Apps
- ASP.NET Webforms (C# with ASP.NET is a plus)
- Monitoring tools (New Relic, Azure App Insights, Google Analytics or others)
- RESTful API development
- Message brokers (RabbitMQ, Automatic Kue, Amazon SQS, Google Pub/Sub, Google Tasks or others)
- Caching tools (Redis, Memcached, Hazelcast or others) 

Expert knowledge

  - Containers (Docker)
  - .NET Core
  - Amazon EC2, Amazon S3, Amazon Lambda
  - Azure
  - React Native development

## Hiring

CLT

## How to Apply

Please send an email to [rafael.dias@pixeon.com](mailto:rafael.dias@pixeon.com) with your attached resume (subject: **Front-end Developer**).

## Labels

- Alocado
- CLT
- Pleno
- Sênior

**Comment by PedroAbdalla** [comment]
Essa vaga seria pra front-end ou fullstack? Pela vaga parece ser fullstack.

**Comment by looslidias** [comment]
@PedroAbdalla 
De fato, é esperado que o candidato detenha conhecimento tanto em front-end quando em backend (fullstack).
Caso avalie que este não seria um canal ideal para o contexto, podemos fechar a issue.
