### ISSUE TITLE
[São Paulo ou Curitiba] Vagas Desenvolvedor(a) Front-end

### ISSUE THREAD

**Issue by penelopevitoria** [frontendbr/vagas#1836]
Pessoal, bom dia.

Tudo certinho?

Já estive aqui outras vezes, representando a GeekHunter. 

Para que não conhece, a Geek é uma comunidade e marketplace de profissionais de TI, em especial Desenvolvedores Front-end, Back-end e Full Stack (CLT ou PJ). Nós conectamos
empresas em crescimento acelerado a profissionais de TI.  O custo para candidatos é 0!

Amazon, Mercado Livre, Peixe Urbano, Hostgator, GuiaBolso e Contabilizei também contratam com a GeekHunter. 

Ah, algumas das nossas vagas abertas:

**[Keep Simple - IT Solution] Desenvolvedor(a) Front-end**
2-4 anos de experiência // CLT ou PJ
Salário: R$ 6.5k até R$ 8.7k
São Paulo - SP
----------------------------
**[Qulture.Rocks] Desenvolvedor(a) Front-end React Sênior**
Salário: R$ 9k até R$ 11k // CLT
São Paulo - SP
----------------------------
**[Bornlogic Tecnologia] Desenvolvedor(a) Front-end**
Salário: R$ 7k até R$ 12k // CLT
Curitiba - PR
----------------------------

**"Tá, mas por que eu deveria me aplicar pela GeekHunter, ao invés de fazer direto pela empresa?"**

1. Se contratado(a), a GeekHunter te presenteia com 10% do seu salário;
2. Indicados pela GeekHunter tem uma prioridade bem maior em processos seletivos;
3. Você pode receber várias propostas ao mesmo tempo, sem gastar tempo nenhum procurando;

----------------------------

**"Quero ter um perfil na GeekHunter. Como eu faço?"**

1. Entre na plataforma por aqui: http://bit.ly/2X3jXsv
2. Preenche seu perfil completo
3. Faça o teste de programação. Atingiu 120 pontos? Está pronto(a) para receber propostas!
4. Seja contratado(a)!

[IMPORTANTE] Ao aplicar-se, você poderá receber propostas como as postadas acima, ou até mesmo
ser selecionado(a) para alguma delas.

Dúvidas? Manda para cá. Boa sorte a todos e todas :)

**Comment by antoniotex** [comment]
Então @penelopevitoria, como dito anteriormente, o FrontendBR não é o local correto para fazer o comercial da GeekHunter. Pelo menos não aqui na issues. Se você gastar alguns minutos do seu tempo, irá perceber que existem algumas regras por aqui.

**Comment by penelopevitoria** [comment]
> Então @penelopevitoria, como dito anteriormente, o FrontendBR não é o local correto para fazer o comercial da GeekHunter. Pelo menos não aqui na issues. Se você gastar alguns minutos do seu tempo, irá perceber que existem algumas regras por aqui.

Então @antoniotex, você pode dizer exatamente que regras estamos infringindo? Porque nosso marketplace tem 0 custos para o candidato e temos muitas vagas abertas. E sim, nós já lemos as regras, só não entendi quais delas estão sendo feridas. 

Abraços!

**Comment by antoniotex** [comment]
> > Então @penelopevitoria, como dito anteriormente, o FrontendBR não é o local correto para fazer o comercial da GeekHunter. Pelo menos não aqui na issues. Se você gastar alguns minutos do seu tempo, irá perceber que existem algumas regras por aqui.
> 
> Então @antoniotex, você pode dizer exatamente que regras estamos infringindo? Porque nosso marketplace tem 0 custos para o candidato e temos muitas vagas abertas. E sim, nós já lemos as regras, só não entendi quais delas estão sendo feridas.
> 
> Abraços!

Já começa pelo título, pois a vaga não é para trabalhar na GeekHunter.
Esse parte do título acho até má intenção da parte de vocês, pois leva a crer que estão com vagas abertas e na verdade só estão fazendo seu "merchan".

Outro fato, que pode ter passado despercebido na hora de vocês lerem as regras, é que os anúncios de vagas devem seguir este template: https://github.com/frontendbr/vagas/blob/master/.github/issue_template.md

**Comment by cyranowebdev** [comment]
Talvez seja o caso de aproveitar esse "atrito" que está rolando para discutir a possibilidade de intermediários, como a GeekHunter, divulgarem suas plataformas aqui, seguindo um template próprio para esse tipo de divulgação. A começar, naturalmente, pelo título, que deve indicar claramente que se trata de um intermediário.

**Comment by penelopevitoria** [comment]
> Talvez seja o caso de aproveitar esse "atrito" que está rolando para discutir a possibilidade de intermediários, como a GeekHunter, divulgarem suas plataformas aqui, seguindo um template próprio para esse tipo de divulgação. A começar, naturalmente, pelo título, que deve indicar claramente que se trata de um intermediário.

Grata pelo feedback. Realmente não havíamos pensado nisso. Obrigada, @cyranowebdev!

**Comment by penelopevitoria** [comment]
> > > Então @penelopevitoria, como dito anteriormente, o FrontendBR não é o local correto para fazer o comercial da GeekHunter. Pelo menos não aqui na issues. Se você gastar alguns minutos do seu tempo, irá perceber que existem algumas regras por aqui.
> > 
> > 
> > Então @antoniotex, você pode dizer exatamente que regras estamos infringindo? Porque nosso marketplace tem 0 custos para o candidato e temos muitas vagas abertas. E sim, nós já lemos as regras, só não entendi quais delas estão sendo feridas.
> > Abraços!
> 
> Já começa pelo título, pois a vaga não é para trabalhar na GeekHunter.
> Esse parte do título acho até má intenção da parte de vocês, pois leva a crer que estão com vagas abertas e na verdade só estão fazendo seu "merchan".
> 
> Outro fato, que pode ter passado despercebido na hora de vocês lerem as regras, é que os anúncios de vagas devem seguir este template: https://github.com/frontendbr/vagas/blob/master/.github/issue_template.md

@antoniotex, o nosso modelo de trabalho é diferente. Não somos um job slot, somos um marketplace. Nós qualificados os candidatos e fazemos um match entre perfis de profissional x empresa. Sendo assim, não é possível divulgar a vaga para a aplicação. Ficou claro?

Sobre ser "uma má intenção": uma pena você pensar assim. A GeekHunter não está tentando vender nada.  Nós oferecemos oportunidades aos desenvolvedores e o custo é 0. Inclusive, profissionais que vieram daqui, estão neste momento recebendo propostas. 

Já que levantou o problema, consegue apontar uma solução para continuarmos postando nossas oportunidades?

Grata. Um abraço!

**Comment by antoniotex** [comment]
> > > > Então @penelopevitoria, como dito anteriormente, o FrontendBR não é o local correto para fazer o comercial da GeekHunter. Pelo menos não aqui na issues. Se você gastar alguns minutos do seu tempo, irá perceber que existem algumas regras por aqui.
> > > 
> > > 
> > > Então @antoniotex, você pode dizer exatamente que regras estamos infringindo? Porque nosso marketplace tem 0 custos para o candidato e temos muitas vagas abertas. E sim, nós já lemos as regras, só não entendi quais delas estão sendo feridas.
> > > Abraços!
> > 
> > 
> > Já começa pelo título, pois a vaga não é para trabalhar na GeekHunter.
> > Esse parte do título acho até má intenção da parte de vocês, pois leva a crer que estão com vagas abertas e na verdade só estão fazendo seu "merchan".
> > Outro fato, que pode ter passado despercebido na hora de vocês lerem as regras, é que os anúncios de vagas devem seguir este template: https://github.com/frontendbr/vagas/blob/master/.github/issue_template.md
> 
> @antoniotex, o nosso modelo de trabalho é diferente. Não somos um job slot, somos um marketplace. Nós qualificamos os candidatos e fazemos um match entre perfis de profissional x empresa. Sendo assim, não é possível divulgar a vaga para a aplicação. Ficou claro?
> 
> Sobre ser "uma má intenção": uma pena você pensar assim. A GeekHunter não está tentando vender nada. Nós oferecemos oportunidades aos desenvolvedores e o custo é 0. Inclusive, profissionais que vieram daqui, estão neste momento recebendo propostas. Realmente o título não estava coerente, nós já alteramos.
> 
> Já que levantou o problema, consegue apontar uma solução para continuarmos postando nossas oportunidades?
> 
> Grata. Um abraço!

Uma solução legal, na minha opinião, seria fazer como a Vulpi faz. Faz o anúncio da vaga seguindo as regras do template, adicionando labels, etc. E postando vaga por vaga, e na parte de "Como se candidatar" colocar um link direto para vaga na plataforma da GeekHunter.

Não tenho nada contra a GeekHunter, pelo contrário, é uma ótima plataforma. Mas todos os posts deverão seguir as regras, senão acaba bagunçando uma das melhores iniciativas para devs front-end no Brasil.

**Comment by felipefialho** [comment]
Olá @penelopevitoria, tudo bem?

Primeiramente, gosto da GeekHunter, que inclusive chegou a patrocinar o Meetup CSS.

Mas como foi levantado pelo @antoniotex, a proposta desse repositório obriga que todas as vagas [sigam nossa template](https://github.com/frontendbr/vagas/blob/master/.github/issue_template.md).

Caso tenham vagas de interesse da galera na plataforma de vocês e garantam que haja um acompanhamento dos responsáveis na issue, principalmente por conta dos feedbacks, podem postar sem problemas. 

Mas postem as vagas individualmente e seguindo o template, se não vamos perder o controle das coisas aqui.

Obrigado!
