### ISSUE TITLE
[São Paulo] Fullstack Developer na ResourceIT

### ISSUE THREAD

**Issue by POLLEZI** [frontendbr/vagas#1837]
DESENVOLVEDOR FULLSTACK

## Descrição da vaga

Desenvolvedor fullstack Java com Angular								
				
## Tipo de contratação
CLT

## Requisitos	
									
- Linguagens: Java - Banco de Dados: Oracle - Servidor de Aplicação: JBOSS, Tomcat, WebSphere; - Frameworks de Backend: JPA (Hibernate), EJB e Spring; - Conhecimentos em JavaScript, Angular, Nodejs, templates, CSS3, HTML5 (Full Stack Developer)

## Benefícios
VR, VT, Convenio Médico, Convenio Odontológico, Auxilio Creche, Convenio Farmácia, Seguro de 
Vida

## Local
Ed Rochaverá ? Berrini /SP Interlagos / SP AV PAULISTA / SP

•	Como aplicar: Envie seu cv com pretensão salarial para adriana.pereira@resourceit.com ou indique um amigo!!!

## Labels

- Alocado
- CLT
- Pleno
- Sênior

**Comment by felipefialho** [comment]
@POLLEZI tudo bem?

Corrigi o titulo da vaga dessa vez, mas na próxima vez use titulo e descrição da vaga que não tenham distinção de genero, como: 

- Fullstack Developer
- Pessoa Desenvolvedora Fullstack
- Desenvolvedor(a) Fullstack

Outra coisa, a vaga é para trabalhar com a contratação feita pela propria ResourceIT?

Obrigado

**Comment by POLLEZI** [comment]
Obrigada, pode deixar que das proximas vezes ficarei mais atenda a isso.
Sim, o profissional será contratado pela Resource e ficara alocado em um dos nossos clientes
