### ISSUE TITLE
[São Paulo] Desenvolvedor full stack no UOL

### ISSUE THREAD

**Issue by helenmatos** [frontendbr/vagas#184]
## Descrição da vaga 
Atuar em uma empresa de grande porte, projeto por tempo indeterminado com possibilidades de crescimento profissional. 

## Local 
Escritório, São Paulo - Brigadeiro Faria Lima

## Requisitos
**Obrigatórios:**
- Desenvolvimento em front-end em sistemas Web (HTML5, CSS e Javascript); experiência na plataforma Java EE e frameworks de mercado (Spring) para desenvolvimento de sistemas Web.
integração de serviços RESTful; Sólidos conhecimentos em design patterns e paradigmas de programação.
Experiência com automação; controle de versionamento com Git.
Experiência com frameworks como Angular, Vue, Ember, React, etc.
Conhecimento em ferramentas de edição de imagens

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um e-mail para Helen.matos@5a.com.br  com seu CV anexado - enviar no assunto:  Vaga Desenvolvedor full stack. 
Indicações são bem vindas. :)

**Comment by LFeh** [comment]
@helenmatos Qual é a empresa?

**Comment by helenmatos** [comment]
@LFeh a vaga em questão é para a UOL.

**Comment by LFeh** [comment]
Show, vou reabrir :)

**Comment by helenmatos** [comment]
Vaga Fechada :)

**Comment by LFeh** [comment]
Boa!
