### ISSUE TITLE
[São Paulo] React and React Native Developer na FCamara

### ISSUE THREAD

**Issue by jakeliny** [frontendbr/vagas#1841]
## Vagas
Para você que gosta de desafios, estou buscando Desenvolvedor React e Desenvolvedor React Native, CLT ou PJ

## Como se candidatar
Interessados ou indicações, enviar CV para [jakeliny.pereira@fcamara.com.br](mailto:jakeliny.pereira@fcamara.com.br)

## Nossa empresa
A FCamara Formação e Consultoria iniciou suas atividades em 2008 com o objetivo de servir com excelência as demandas de verificação de desempenho de aplicações e organização de times de desenvolvimento. Hoje, somos referência em transformação digital através de um método próprio, o High Performance Team, que ajuda empresas a desenvolver projetos e ideias de negócio de forma mais eficiente. Inovação, tecnologia e empreendedorismo fazem parte de quem somos. Queremos ser uma empresa útil e funcional. Útil porque possuímos serviços e produtos necessários. Funcional porque nossos serviços e produtos realmente solucionam e representam valor agregado ao Cliente.

Venha fazer parte do #SangueLaranja. Seja um de nossos clientes ou consultores. Aqui suas ideias tem valor!

## Labels
-CLT
-PJ
-Senior
-Pleno

**Comment by rios0rios0** [comment]
@jakeliny Full Remote?

**Comment by jakeliny** [comment]
@rios0rios0 presencial :)
