### ISSUE TITLE
[Sâo Paulo] Front-End Developer / React na Centauro

### ISSUE THREAD

**Issue by MatheusBordin** [frontendbr/vagas#1842]
## Descrição da vaga

Estamos à procura de pessoas para integrar nosso time que sejam focadas em resultado, que busquem sempre se superar, e que tenham comprometimento com a excelência. Vaga full-time para trabalhar em nosso escritório na Lapa, São Paulo.

#### O dia-a-dia de um Analista Front-End aqui no time:

- Entender os requisitos e botar a mão na massa;
- Realizar os alinhamentos necessários com o time para que todo o trabalho esteja alinhado;
- Trabalhar para melhorar as soluções existentes e dar suporte aos diferentes sistemas do nosso e-commerce;
- Aprender e aplicar novas tecnologias para otimizar nossos processos e produtos.

#### Nosso Princípios:

- Colocamos o cliente no centro de tudo
- Nunca paramos de aprender
- Agimos com inteligência
- Construímos os melhores times
- Confiamos e apoiamos uns aos outros
- Trabalhamos juntos pelo bem comum

#### Procuramos pessoas que possuam:

- Mindset ágil
- Aceitar feedbacks sem #mimimi
- Sentimento de dono
- Inconformismo
- Vontade de fazer a diferença

## Local

Escritório, São Paulo - Lapa.
**Obs: próximo à estação de trem lapa**

## Benefícios

- Restaurante grátis nas dependências da empresa
- Ambiente de trabalho descontraído e equipe colaborativa

## Requisitos

**Obrigatórios:**
- Js na veia
- Css
- React
- Engine de store para react (mobx/redux)
- Eslint
- Webpack (conhecimento básico)
- Css-in-js
- Testes unitários para front
- Protocolo http
- Cdn

**Desejáveis:**
- Google analytics
- Googletagmanager
- Conhecimentos de e-commerce

## Contratação

PJ a combinar.

## Como se candidatar

Por favor envie um email para vagadev@atma-it.com com seu CV anexado - enviar no assunto: Vaga Front-End React

## Labels
- Alocado
- PJ
- Pleno
- [São Paulo]

**Comment by rmasouza** [comment]
a vaga inda está disponível?
