### ISSUE TITLE
[São Paulo] Front-end Developer na Mandarin

### ISSUE THREAD

**Issue by AgenciaMandarin** [frontendbr/vagas#1844]
## Descrição da Vaga

Projeto bazinga em NodeJS, etc.

## Local

Profissional com experiência em desenvolvimento de materiais digitais, com conhecimentos em softwares gráficos, programação HTML, UX e UI.

## Benefícios

- Vale Alimentação
- Vale Transporte

## Requisitos

**Obrigatórios:**
- Ter trabalhado com design de sites e programação HTML/CSS/JS;
- Ter conhecimentos em Bootstrap e outros frameworks;

**Desejáveis:**
- Ser criativo, pró-ativo, organizado e bem humorado;
- Ter garra e vontade para crescer profissionalmente;
- Ter comprometimento com o trabalho e com a empresa;
- Ter boa comunicação e relacionamento;
- Ter atenção concentrada;
- Ser pontual e responsável;
- Ser prestativo e atencioso.

**Diferenciais:**
- Ter conhecimentos nos programas Adobe relacionados a área de design digita (Photoshop, XD) e em outros softwares relacionados à UX;

## Contratação

CLT a combinar

## Nossa empresa

A tecnologia transforma o mundo e as relações humanas em uma velocidade desafiadora.
As informações se multiplicam, as possibilidades de interação com marcas e produtos se ampliam a cada dia e compreender os processos de decisão de compra e os pontos de contato com o shopper está cada vez mais complexo.

Nosso diferencial consiste em uma metodologia própria que tem o shopper como centro de tudo o que fazemos. Utilizamos dados, estratégia, criatividade, conteúdo relevante e nosso grande expertise nos diversos tipos de ponto de venda para influenciar de forma positiva a decisão do shopper.

We design for shopper.

## Como se candidatar

Por favor acesse o link http://bit.ly/MandarinProgramador e se inscreva

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 30 dias após cada processo.
E-mail para contato em caso de não haver resposta: vagas@mandarin.com.br

## Labels

- HTML
- CLT
- Front-end
- Css
- JavaScript
- UX
-UI

**Comment by agnezi** [comment]
Inscrito.

**Comment by danielswater** [comment]
Remoto?

**Comment by adeonir** [comment]
Inscrito

**Comment by AgenciaMandarin** [comment]
> Remoto?

Não. Presencial.

**Comment by acamilass** [comment]
Para todos os níveis?
