### ISSUE TITLE
[São Paulo - SP] Full-Stacker Developer na Alpar Consultoria

### ISSUE THREAD

**Issue by pyymenta** [frontendbr/vagas#1846]
## Descrição da vaga

Atuar com o desenvolvimento de soluções e customização da ferramenta serviceNow nas maiores empresas brasileiras.

## Local

Escritório, São Paulo - Bela Aliança

## Diferenciais

-  2 dias de homeoffice semanal.

## Requisitos

* Java
* JavaScript
* Angular
* CSS
* HTML

## Contratação

PJ a combinar

## Como se candidatar

Interessados aplicar em:

marcos.gianoni@alparservice.com.br

## Labels

- Alocado
- Júnior
- PJ
- Pleno
- Sênior

**Comment by pyymenta** [comment]
Caso seja necessário mais informações, posso solicitar com o contratante. Obrigado!

**Comment by fafa1** [comment]
olá, esqueceu da label, juníor!

**Comment by pyymenta** [comment]
não recebi mais notícias do contratante, vou fechar essa issue. Obrigado pelo espaço galera!
