### ISSUE TITLE
[Barueri/SP] Front-End Developer na Quod

### ISSUE THREAD

**Issue by kvilela** [frontendbr/vagas#1847]
## Descrição da vaga
Desenvolvimento de interfaces Web e/ou Mobile dos produtos da empresa, com áreas logadas e não-logadas utilizando tecnologias como HTML5, CSS3 LESS, SASS, Angular, Bootstrap, Gulp e PWA. 

Domínio de conceitos como CD/CI, Testes AB, microsserviços em nuvem AWS e ferramentas como Git, Sonarqube e Nexus.

## Local
Escritório, São Paulo - Barueri

## Benefícios
- Plano de saúde
- Seguro de vida
- VR 
- VT

## Requisitos
**Obrigatórios:**
HTML5, CSS3 LESS, SASS, Angular, Bootstrap, Gulp e PWA
Domínio de Conceitos como CD/CI, Testes AB, 
microsserviços em nuvem AWS e ferramentas como Git, SonarQube e Nexus

## Contratação
CLT a combinar

##Nosso Cliente
Fintech startup de gerenciamento de dados criada pelos cinco maiores bancos do Brasil: Banco do Brasil, Bradesco, Caixa Econômica Federal, Itaú Unibanco e Santander.

A empresa foi constituída formalmente em junho de 2017, atendendo clientes em todos os setores da economia, incluindo instituições financeiras, seguradoras, varejistas, operadoras de telecomunicações e pequenas e médias empresas, entre outros.

Ambiente colaborativo com uma equipe bem unida e dinâmica

## Como se candidatar
Por favor envie um e-mail para karina.vilela@focoemvoce.com.br com seu CV anexado - enviar no assunto: Front-End Quod

## Labels
- Alocado
- CLT
- Pleno
- Sênior
- SonarQube 
- AWS
- PWA

**Comment by felipefialho** [comment]
A vaga é para trabalhar em qual empresa?

**Comment by deizepi** [comment]
Boa tarde, a vaga é para trabalhar na Fingerprint. Somos uma gráfica de dados variáveis (boletos, extratos, qualquer coisa que vá personalizada para o cliente final) há 25 anos no mercado. Nos últimos 5 anos, decidimos expandir nossos horizontes, indo para meios de pagamento (débito em conta, cartões de crédito e débito, boleto e até registro de pagamento em dinheiro).
Já lançamos um produto para o 3o setor (ONGs, Igrejas, instituições de caridade, etc) para gerir todo o processo de arrecadações (desde a captação de novos colaboradores até o processo de retorno de doações daqueles que não doam há algum tempo).
Temos um projeto em andamento para o varejo (lojas, construções, condomínios, etc) para auxiliar também nos pagamentos e na inadimplência.

Se tiver alguma dúvida, fico à disposição.

Caso possua interesse na vaga, por favor encaminhe esse mesmo email para a Lilian (laraujo@fingerprint.com.br) com o currículo em anexo para que possamos agendar uma entrevista.

Muito obrigado.

Sent via the Samsung Galaxy S8, an AT&T 4G LTE smartphone


-------- Mensagem original --------
De: Felipe Fialho <notifications@github.com>
Data: 06/03/19 17:27 (GMT-03:00)
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [Barueri/SP] Front-End Developer (#1847)


A vaga é para trabalhar em qual empresa?

**Comment by kvilela** [comment]
@felipefialho acho que houve um equivoco do @deizepi a vaga que estou divulgando não é para essa empresa (sequer a conheço) --- a vaga é para a empresa Quod

**Comment by felipefialho** [comment]
Me confundi, foi mal, hahaha

**Comment by kvilela** [comment]
Pessoal, reabrimos a vaga.

**Comment by felipefialho** [comment]
@kvilela prefere manter nessa ou abrir outra?
