### ISSUE TITLE
Vaga: Front-End Developer

### ISSUE THREAD

**Issue by CapitaniIT** [frontendbr/vagas#1848]
Vaga: Front-End Developer

Fintech startup de gerenciamento de dados criada pelos cinco maiores bancos do Brasil: Banco do Brasil, Bradesco, Caixa Econômica Federal, Itaú Unibanco e Santander.

Função: 
Desenvolvimento de interfaces Web e/ou Mobile dos produtos da empresa, com áreas
logadas e não-logadas.

Requisitos: 
HTML5, CSS3 LESS, SASS, Angular, Bootstrap, Gulp e PWA. Domínio de conceitos como CD/CI, Testes AB, microserviços em nuvem AWS e ferramentas como Git, Sonarqube e Nexus.

Local: Alphaville / Barueri
Contratação: CLT Full
Currículo para: x

**Comment by felipefialho** [comment]
Totalmente fora do padrão, fechado até que siga o template.

**Comment by CapitaniIT** [comment]
Correções feitas!


😉


[cid:ad29ecde-524c-43d6-90a8-5b64e1280940]

________________________________
De: Felipe Fialho <notifications@github.com>
Enviado: quinta-feira, 7 de março de 2019 10:44:36
Para: frontendbr/vagas
Cc: Fabio Coelho; Author
Assunto: Re: [frontendbr/vagas] Vaga: Front-End Developer (#1848)


Closed #1848<https://github.com/frontendbr/vagas/issues/1848>.
