### ISSUE TITLE
Coordenador de TI

### ISSUE THREAD

**Issue by ConsultoriaContato** [frontendbr/vagas#185]
## Descrição da vaga

Coordenador de TI para atuar em uma empresa de Tecnologia Educacional (EAD). 

Atividades: administração de softwares de gestão de projetos (controle de usuários e atividades), elaboração de manuais e tutoriais, capacitações de equipe, suporte aos colaboradores internos e externos. 

Conhecimentos: softwares - pacote office, sharepoint, moodle. 

Necessária experiência com administração de softwares de gestão de projetos e plataforma moodle.

## Local

Florianópolis

## Contratação

CLT a combinar

## Como se candidatar

Cadastre-se no site: http://www.selecaodevagas.com.br/

**Comment by LFeh** [comment]
Só vagas de Front-End aqui ;)
