### ISSUE TITLE
[São Paulo] Full-Stack Developer na Forma Turismo

### ISSUE THREAD

**Issue by MrS4w** [frontendbr/vagas#1850]
## Descrição da vaga

- DESENVOLVER NOVOS SISTEMAS A PARTIR DA NOVA PLATAFORMA DE DESENVOLVIMENTO, EFETUAR CORREÇÕES NO SISTEMA LEGADO, PARTICIPAR DE REUNIÕES DE PLANEJAMENTO DE SPRINTS SCRUM, AVALIAR PEDIDOS DE CORREÇÕES, RISCOS E IMPACTOS.

- Desenvolver novos sistemas a partir da nova plataforma de desenvolvimento
- Efetuar correções no sistema legado
- Participar de reuniões de planejamento de Sprints Scrum
- Avaliar pedidos de correções, riscos e impactos
- Sugerir melhorias que promovam a estabilidade, segurança e facilidade de manutenção
- Trabalhar em coisas para sentir orgulho em contar para os amigos que foi você quem fez

## Local

Moema, São Paulo - Vila Olímpia

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ 30/dia
- VT

## Requisitos

**Obrigatórios:**
- Experiência prévia com subversion ou GIT
- Experiência prévia com AngularJS
- Experiência prévia com NodeJS
- Noções básicas de SQL

**Desejáveis:**
- Capacidade de codificar seguindo o padrão de desenvolvimento definido pela implementação de referência
- Disposição para codificação de testes unitários
- Experiência prévia com hapi ou express

## Contratação

CLT FULL

## Nossa empresa

A Forma Turismo é a maior empresa de turismo especializada em viagens de formatura do Brasil. Com 21 anos de experiência e mais de 20 destinos.

## Como se candidatar

Por favor envie um email para leandro@formaturismo.com.br com seu CV anexado - enviar no assunto: Vaga NodeJS

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.

## Labels

- Alocado
- CLT
- Júnior
- Pleno
- Sênior

**Comment by EduardoRFS** [comment]
Tem alguma noção de faixas salariais, para dev pleno/senior? Tenho todos obrigatórios e desejáveis, me senti interessado pela vaga.

**Comment by MrS4w** [comment]
Olá @EduardoRFS favor entrar em contato com o email acima :smile:

**Comment by felipefialho** [comment]
Da hora @MrS4w :)

**Comment by MrS4w** [comment]
@felipefialho pode fechar a #1699 :)

**Comment by brunooomelo** [comment]
essa empresa muito boa, já fiz entrevista com o Leandro. Eu Recomendo!!
