### ISSUE TITLE
[Barueri/SP] Front-End Developer na Capitani IT

### ISSUE THREAD

**Issue by CapitaniIT** [frontendbr/vagas#1851]
Front-End Developer

## Descrição da vaga
Desenvolvimento de interfaces Web e/ou Mobile dos produtos da empresa, com áreas
logadas e não-logadas utilizando tecnologias como HTML5, CSS3 LESS, SASS, Angular,
Bootstrap, Gulp e PWA. Domínio de conceitos como CD/CI, Testes AB, microserviços em
nuvem AWS e ferramentas como Git, Sonarqube e Nexus.

## Local

Presencial, Alphaville / Barueri

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ 18/dia
- Auxílio creche
- Convênio Odontológico

## Requisitos

**Obrigatórios:**
HTML5, CSS3 LESS, SASS, Angular,
Bootstrap, Gulp e PWA. Domínio de conceitos como CD/CI, Testes AB, microserviços em
nuvem AWS e ferramentas como Git, Sonarqube e Nexus.

## Contratação

CLT

## Capitani IT

Fintech startup de gerenciamento de dados criada pelos cinco maiores bancos do Brasil: Banco do Brasil, Bradesco, Caixa Econômica Federal, Itaú Unibanco e Santander.

## Como se candidatar

Por favor envie um email para fabio.coelho@capitani.com.br com seu CV anexado - enviar no assunto: Vaga Front-End Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: fabio.coelho@capitani.com.br

## Labels

- CLT
- Sênior

**Comment by CapitaniIT** [comment]
Obrigado Victor!


😊


[cid:6faad2fb-6ccb-47e7-9c20-584637887a49]

“Excelência em Fornecer Inovação e Tecnologia”   capitani.com.br

+5511 3522-1941


________________________________
De: Victor Λntonio <notifications@github.com>
Enviado: sexta-feira, 7 de junho de 2019 17:54:08
Para: frontendbr/vagas
Cc: Fabio Coelho; Author
Assunto: Re: [frontendbr/vagas] [Barueri/SP] Front-End Developer na Capitani IT (#1851)


Closed #1851<https://github.com/frontendbr/vagas/issues/1851>.

**Comment by MrS4w** [comment]
Disponha @CapitaniIT :smile:
