### ISSUE TITLE
[São Paulo - SP] UX/UI Front-End Developer no NIC.br

### ISSUE THREAD

**Issue by EpicEric** [frontendbr/vagas#1852]
## Descrição da vaga

Como __Desenvolvedor Frontend com foco em UX/UI__, você terá um papel ativo no desenho e desenvolvimento de produtos, desde a concepção em alto nível, passando pelo design da experiência do usuário e o design de interfaces e chegando até a implementação do produto em conjunto com nosso time _fullstack_. Para isto deverá criar arquiteturas de informação e fluxos de navegação, _wireframes_ e protótipos para devices desktop e mobile. Você criará experiências de uso específicas tanto para produtos de consumidor quanto produtos usados em um contexto corporativo. Na implementação do frontend você liderará nossa equipe _fullstack_ na adoção de conceitos e técnicas frontend modernas.

## Local

São Paulo - Brooklin (a 500 metros da estação Berrini)

## Benefícios

- Plano de saúde
- Seguro de vida
- Vale Refeição
- Vale Transporte

## Requisitos

**Obrigatórios:**
- Graduação em Tecnologia da Informação, Design Digital, Ciência da Computação ou cursos afins.
- Capacidade de transformar ideias em proposta de interfaces simples e eficazes.
- Experiência com UX e design de UI.
- Experiência com arquitetura Frontend: Frameworks e modelos de programação Javascript, gerência de estado no cliente, integração REST e GraphQL.
- Experiência com abordagens CSS modernas.
- Experiência com ferramentas Javascript: Webpack, Typescript e correlatos.
- Inglês intermediário, leitura e escrita.

**Diferenciais:**
- Experiência com concepção de produtos e elicitação de requisitos (ex. Design Sprints).
- Experiência com User Centered Design (UDD).
- Experiência com testes de usabilidade e A/B.
- Experiência com frontend performance e Google Analytics.
- Experiência com ferramentas de design (sketch, illustrator ou ferramenta correlata).
- Experiência com CI/CD.

## Contratação

CLT

## Nossa empresa

O __NIC.br__ é uma empresa sem fins lucrativos, com a missão de implementar as decisões do Comitê Gestor da Internet no Brasil - CGI.br e trabalhar pela melhoria da Internet Brasileira. Com sede em São Paulo e infraestrutura em todo país, a empresa desempenha um papel crítico na evolução da Internet Brasileira. Você fará parte do nosso projeto de medição da qualidade Internet, SIMET.

## Como se candidatar

Envie um e-mail para vagas@simet.nic.br com seu CV anexado - enviar no assunto: `Desenvolvedor Frontend com foco em UX/UI - frontendbr`

## Labels

- Alocado
- CLT
- Pleno
- Sênior

**Comment by EpicEric** [comment]
Para a vaga __Desenvolvedor Full Stack__ no NIC.br, ver #1826

**Comment by rubenmarcus** [comment]
Tenho a maioria dos requisitos, menos a graduação.
Pode se candidatar mesmo assim?

**Comment by EpicEric** [comment]
Olá, @rubenmarcus.

Infelizmente, não. Todos os candidatos devem ter o ensino superior completo.

Agradecemos o seu interesse na vaga e lhe desejamos uma boa sorte.
