### ISSUE TITLE
[São Paulo] Front-End Developer na Raizs

### ISSUE THREAD

**Issue by bielmorales** [frontendbr/vagas#1854]
## Descrição da vaga

Projeto e-commerce em Node.

## Local

Escritório - R. Dep. Lacerda Franco, 462 - Pinheiros, São Paulo - SP, 05418-001

## Benefícios

- Férias remuneradas

#### Diferenciais

- horário 100% flexível
- próximo da vila madalena e do metrô faria lima
- startup já consolidada, em período de expansão rápida

## Requisitos

**Obrigatórios:**
- Experiência com Node e React no passado
- Experiência com SQL - PostGreSQL, principalmente

**Desejáveis:**
- conhecimentos em python
- domínio de css/lifecicle

**Diferenciais:**
- experiência com e-commerce
- experiência com AWS

## Contratação

PJ a combinar

## Nossa empresa

A Raízs é um e-commerce de produtos orgânicos que fortalece o laço entre o pequeno produtor de orgânicos e o consumidor consciente. Com tecnologia e inovação, geramos mais visibilidade para o campo e mais acessibilidade para a cidade, incentivando uma alimentação saudável, um consumo sustentável e um comércio justo.

## Como se candidatar

Enviar CV para gabriel@raizs.com.br

## Tempo médio de feedbacks

Contratação urgente 

## Labels

- Alocado
- Júnior
- PJ

**Comment by fabiolima** [comment]
Poxa, gostei muito do projeto, nao aceita remoto?

**Comment by guilhermeoa07** [comment]
Entrevista pode ser remota?
