### ISSUE TITLE
[São Paulo] Front-end Developer na Cave

### ISSUE THREAD

**Issue by andressabertolini** [frontendbr/vagas#1857]
## Descrição da vaga

Buscamos alguém com experiência em Front-end para sites, e-mails e aplicativos mobile para compor a nossa equipe. Para esta vaga é necessário ter experiência comprovada em HTML, CSS e Javascript.
Tão importante quanto os conhecimentos técnicos, para nós da CAVE, é ter alta capacidade de adaptação, senso de empreendedorismo e comprometimento com qualidade e prazo.

## Local

Rua Fradique Coutinho, 212, Pinheiros - São Paulo, SP

## Benefícios

- Vale-transporte
- Vale-refeição
- Plano de Saúde
- Plano Odontológico
- Seguro de Vida

## Requisitos

**Requisitos:**
- HTML5, CSS3
- Javascript e jQuery
- Bootstrap
- AngularJS

**Desejáveis:**
- Recorte de layouts em Photoshop e Illustrator
- ASP .NET MVC
- Experiência em Wordpress

## Contratação

CLT

## Nossa empresa

Existem as agências, as consultorias, as aceleradoras, as incubadoras, os venture capitals, as fábricas de software...

Temos muito de todas, mas não somos nenhuma delas.

Somos realizadores. O que isso significa?

Nossa especialidade é fortalecer a comunicação, transformando ideias e sonhos viáveis, em negócios prósperos.

## Como se candidatar

Para se inscrever na vaga clique no link: https://trampos.co/oportunidades/146110?tr=cave

## Labels

- Alocado
- CLT
- Júnior
- Pleno

**Comment by VictorCardoso22** [comment]
Olá, teria a possibilidade de remoto?

**Comment by felipefialho** [comment]
Olá @andressabertolini, tudo bem?
 
Corrigi o titulo da vaga, mas na próxima vez tente usar um titulo e descrição que não tenham distinção de genero, como:

- Frontend Developer
- Pessoa Desenvolvedora Frontend
- Desenvolvedor(a) Frontend

Obrigado 😊

**Comment by andressabertolini** [comment]
> Olá, teria a possibilidade de remoto?

Apenas presencial mesmo

**Comment by andressabertolini** [comment]
> Olá, teria a possibilidade de remoto?

Somente presencial mesmo
