### ISSUE TITLE
Programador Front End Senior

### ISSUE THREAD

**Issue by etnrlz** [frontendbr/vagas#186]
## Descrição da vaga

Projeto internacional em angular2 

## Local

Escritório, São Paulo - Alameda Santos, 122 - Paraíso

## Benefícios

- Convênio Médico
- VR ou VA
- Garagem no prédio

## Requisitos

**Obrigatórios:**
- Jquery, Bootstrap 3+, Angular
- Inglês Técnico

**Desejáveis:**
- conhecimentos em angular2
- Inglês Fluente

**Diferenciais:**
- já ter trabalhado em outros projetos em angular2

## Contratação

CLT, R$ 8.000,00
+ Bonus por desempenho

## Nossa empresa

Somos uma empresa multinacional, atuando em 8 mercados e referencia em Marketing Digital

## Como se candidatar

Por favor envie um email para co@advantagemedia.com.br com seu CV anexado - enviar no assunto: Vaga FrontEnd

**Comment by owebmaster** [comment]
Já estudei Angular (1&2) mas nunca trabalhei nada em produção. Porém tenho projetos rodando em React, React Native, ClojureScript, que usam stacks similares em JS. Acha que é compatível com a vaga?

De qualquer forma, enviei o CV (alan@engarte.com) :)
