### ISSUE TITLE
[Remoto] Front-End React Developer no ChefsClub

### ISSUE THREAD

**Issue by felipetio** [frontendbr/vagas#1862]
## Descrição da oportunidade

Nosso web app foi construído com React.js e o que há de melhor em padrões de desenvolvimento web: Um projeto de storybook com toda a UI com componentes responsivos e uma arquitetura de CSS organizada e escalável. E em outro projeto, a aplicação organizada em multi-camadas com componentes de lógica, Redux e um Backend for Frontend (BFF) em Node.js para se comunicar com nossa API Rest.

Você pode ver mais sobre as tecnologias que usamos em https://stackshare.io/felipetio2/chefsclub. Porém muito mais importante do que ser experiente com tecnologias que usamos, é se comportar como uma mente curiosa, gostar de aprender coisas novas rapidamente e entender os principais conceitos por trás das bibliotecas e dos frameworks que você já domina.

Entendemos que o tempo gasto no escritório não equivale à produtividade. Por isso, nossa equipe está livre para trabalhar remotamente e toda a comunicação é feita rigorosamente no Slack.

O quê mais? Em fevereiro de 2018, o ChefsClub e Grubster anunciaram uma fusão e este ainda é um grande desafio tecnológico no qual você provavelmente estará trabalhando. A cada trimestre definimos OKRs e criamos um backlog para trabalhar. Usamos Scrum e Kanban, incluindo reuniões diárias, planejamento e retrospectivas quinzenais. Isso tudo fica documentado no Trello.

## Local

Remoto ou Escritório

- São Paulo - Vila Mariana
- Rio de Janeiro - Barra/Centro

## Contratação

R$72.000 à R$143.000 por ano

## Nossa empresa

Comer fora começa aqui! O ChefsClub é o principal clube de gastronomia do Brasil, um serviço de assinatura que oferece descontos de até 50% em dias e horários específicos em mais de 2.500 restaurantes em 25 cidades (forte presença em São Paulo, Rio de Janeiro e outras capitais como Belo Horizonte, Recife, Brasília, etc.)

Somos uma startup que e proporcionamos experiências incríveis para os amantes da boa comida, além de ajudar os restaurantes a terem um negócio lucrativo e sustentável.

A nossa obsessão em fornecer um excelente serviço ao cliente é uma das nossas vantagens competitivas, assim como os nossos produtos simples de usar. Faça o download do ChefsClub na Apple Store ou no Google Play e dê uma olhada nos nossos principais restaurantes: Pobre Juan, Fogo de Chão, PF Changs, Serafina, Paris 6, L'Entrecôte de Paris, The Fifties e General Prime Burger. Também somos parceiros oficiais de grandes marcas como Claro-clube, Nextel, Tudo Azul e Google.

Em 2015, fomos considerados uma das empresas mais inovadoras do Brasil pela Revista Exame. Em 2017 e 2018, recebemos o prêmio Great Place to Work, sendo considerada uma das Melhores Empresas para se trabalhar.

Nossa equipe é composta por 33 membros: 7 engenheiros de softwares, 7 c-levels e outros colegas incríveis distribuídos nas equipes de trade, customer service, marketing, operação e administração. Todo membro da equipe é elegível para o nosso plano de opção de ações.

Nossa equipe de investidores tem nomes impressionantes das indústrias de internet e restaurantes. Dê uma olhada em www.linkedin.com/company/chefsclub/people.

Somos uma empresa lucrativa e nossos KPIs estão crescendo ano após ano. Duplicamos nossa receita, sentamos milhões de consumidores em 2018 e estamos buscando uma rodada de investimentos para marketing e o desenvolvimento de produtos principalmente. É por isso que precisamos que você se junte a nós!

Finalmente, nosso CEO escreveu uma nota sobre a cultura de nossa companhia:

> "Você será o seu próprio chefe, ou seja, terá líderes que ajudarão no seu desenvolvimento e superação de desafios, mas é fundamental pensar como dono do negócio. Damos autonomia e liberdade, mas isso precisa vir acompanhado de muita responsabilidade e autogestão. Erramos bastante, mas fazemos questão de aprender com estes erros para não repeti-los. Amamos, respeitamos e promovemos a diversidade por aqui. Acreditamos que devemos fazer a coisa certa SEMPRE e que uma comunicação clara e transparente é o principal ingrediente para o trabalho em equipe. Somos apaixonados por restaurantes, fissurados por serviço e completamente loucos pelos nossos clientes. Fazemos o possível e o impossível para garantir a eles a melhor experiência."

-- Guilherme Mynssen, CEO & Founder

## Como se candidatar

Animado para sacudir o mercado de comer fora de casa com a gente? Inscreva-se e vamos falar.

https://podio.com/webforms/15229618/1020915

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: felipe@chefsclub.com.br

## Labels

- CLT
- PJ
- Pleno
- Sênior
- Alocado
- Remoto

**Comment by mart2222** [comment]
Enviado!

**Comment by luanribeiros** [comment]
Enviado.

**Comment by ahlechandre** [comment]
enviado!

**Comment by vimaciel** [comment]
Enviado.

**Comment by willhoffmann** [comment]
Enviado!

**Comment by victorvinci** [comment]
Enviado!

**Comment by LucasHiago** [comment]
Enviado com sucesso!

**Comment by PuenteVinicius** [comment]
Enviado :)

**Comment by flaugabriel** [comment]
Enviado
