### ISSUE TITLE
[Belo Horizonte] Front-End Developer na nata.house

### ISSUE THREAD

**Issue by albertotimoteo** [frontendbr/vagas#1863]
## Descrição da vaga

A nata.house é uma fábrica de software especializada nas tecnologias React e React Native. A vaga em aberto no momento é para desenvolvimento em React em um projeto internacional. É necessário que o candidato tenha pelo menos 6 meses de experiência especificamente com React e tenha experiência de pelo menos 1 ano com javascript. Além disso, é desejável um bom conhecimento em estrutura de projeto e em desenvolvimento ágil (SCRUM). 

## Local

Escritório no centro de Belo Horizonte. Somente presencial. 

## Benefícios

- Vale-Refeição ou Vale-Alimentação
- Vale-Combustível ou Vale Transporte
- Horário flexível
- 30h ou 40h semanais
- Aula de inglês
- Lanche na empresa
- Happy Hour mensal pago pela empresa 

#### Diferenciais

- Empresa transparente com o funcionário
- Equipe diversa, unida e colaborativa
- Estrutura de projetos organizada
- Oportunidade para o funcionário de empregar algumas horas semanais em projetos pessoais

## Requisitos

**Obrigatórios:**
- 6 meses de experiência com React
- 1 ano de experiência com javascript

**Desejáveis:**
- Conhecimento em GIT e Scrum.

## Contratação

CLT 6h ou 8h

## Nossa empresa

Você já conhece a nata.house? 
Somos uma empresa de criação de soluções que tem como objetivo resolver problemas por meio da tecnologia, ou seja, uma fábrica de softwares. Trabalhamos com foco em desenvolvimento ágil e tecnologias modernas, e cuidamos sempre para que a empresa tenha um ambiente de trabalho descontraído, flexível e que proporcione aprendizado constante.

## Como se candidatar

Enviar CV para o e-mail vagas@natahouse.com

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dia após a primeira parte do processo e até 7 dias após a segunda parte do processo.

## Labels

- CLT
- Pleno

**Comment by henryqrm** [comment]
Enviado. :)

**Comment by IgorVieira** [comment]
Enviado!
