### ISSUE TITLE
[Florianópolis] Estágio Front-End no Biologia Total

### ISSUE THREAD

**Issue by lciceris** [frontendbr/vagas#1864]
## Descrição da vaga

Estamos contratando um(a) estagiário(a) que atue no desenvolvimento de projetos para a plataforma do Biologia Total, utilizando HTML, CSS e Javascript. Oportunidade de trabalhar em projetos utilizando tecnologias como React, Node, Mongo, pré-processador SASS e AWS.

## Local

- Escritório - Santa Mônica, Florianópolis (próximo da UFSC).

## Benefícios

- Flexibilidade de horário
- Bolsa: de R$ 1300,00/mês
- Vale transporte de R$ 80,00/mês

## Requisitos

**Obrigatórios:**
- Ensino superior cursando em Ciência da Computação ou áreas relacionadas.
- Aquele básico de HTML + CSS + JS
- Muita vontade de aprender

**Diferenciais:**
- Querer se aprofundar no Desenvolvimento Full Stack

## Contratação

- Tipo de vaga: Estágio 6h

## Como se candidatar

Por favor envie um email para eduardo@biologiatotal.com.br com seu CV anexado - enviar no assunto: Estágio Front-End

## Labels

- Alocado
- Estágio

**Comment by ptklorran** [comment]
Tem possibilidade de ser remoto?

**Comment by rivajunior** [comment]
@ptklorran até onde eu me lembro, a lei de estágio não permite que se faça trabalho remoto. Então você não conseguiria que a instituição de ensino assinasse o contrato.

**Comment by lciceris** [comment]
Fala @ptklorran a vaga é somente alocado mesmo, por motivos legais como o @rivajunior falou.
Legal do estagiário presente é que fica mais fácil de ensinar/passar as paradas.

**Comment by CeloGarcia** [comment]
A vaga ainda está aberta?

**Comment by lciceris** [comment]
@CeloGarcia está sim!

**Comment by lciceris** [comment]
Vaga fechada.
