### ISSUE TITLE
[São Paulo] Front-end Developer - Red Ventures

### ISSUE THREAD

**Issue by elvisdetona** [frontendbr/vagas#1867]
## Sobre a Red Ventures
 
 O time de Front-end é responsavel por desenvolver e manter aplicações complexas, mobile-first e com alta performance com outros times de engenharia da Red Ventures. Esta posição tem alta visibilidade e potencial para impactar a organização, participando diretamente para contruir e entregar soluções para nossos parceiros.

Nossa cultura é baseada em liberdade, você será livre para executar, testar e aprender e você terá a responsabilidade de se auto gerenciar num ambiente colaborativo e ágil.

Você terá a oportunidade de se desafiar e crescer. Você poderia pensar no melhor dos dois mundos: trabalhar em um ambiente de start-up dinâmico no Brasil e, ao mesmo tempo, ser apoiado por uma empresa de tecnologia global líder em um ambiente de carreira disruptivo, empreendedor e acelerado.

## Descrição da vaga
Você será responsável por planejar e construir aplicações escaláveis usando algumas das mais modernas ferramentas e linguagens de programação disponíveis do mercado. Você irá contruir aplicações complexas que funcionarão em vários dispositivos e palavras como performance e mobile first serão parte de sua rotina.

Nós esperamos que você construa aplicações do zero e implemente novas features em projetos já construídos além de identificar e  propor soluções para problemas repetidos.

Você trabalhará com designers, analistas, engenheiros e outros desenvolvedores em um ambiente onde você pode ver o impacto de suas idéias.

A Red Ventures lhe dará a oportunidade de inovar e tomar decisões significativas à medida que você continua a desenvolver suas habilidades.

## Requisitos
-	Demonstrar compromisso para aprendizado e melhoria continua.
-   Ter familiaridade com design responsivo, sempre procurando por breakpoints que possam melhorar a UI para chegar a uma melhor experiência para o usuário final.
-   Você prioriza animações e interação de UI nos projetos.
-	Ter familiaridade com arquiteturas CSS populares, como BEM e rscss.
-   Ter alguma experiência com programação funcional.
-	Ter experiência em formatar dados retornados de uma API performaticamente manipulando o DOM.
-	Experiência  com automatização de tarefas e processos usando ferramentas modernas como Webpack em multiplos ambientes.
-	Como você irá trabalhar com designers e desenvolvedores de todo o mundo, você precisa se sentir confortável para se comunicar em inglês.
-	Suas responsabilidades também incluem: Planejar, Desenhar e Construir soluções para algumas das maiores marcas do mundo.
-	Colaborar com todo o time não só criando aplicativos simples e eficientes, mas também dando idéias e identificando melhorias nas soluções desenvolvidas.
-   Habilidade para articular conceitos técnicos e soluções não técnicas com as partes interessadas (stakeholders).
-	Criar e evangelizar padrões de código, bibliotecas e componentes de UI para uso interno (incluindo facilitar code review, documentar padrões e exemplos de código e ajudar novos desenvolvedores a crescerem profissionalmente).

#### Plus
-	Familiaridade com React e  Recompose.
-	Ter alguma experiência com programação funtional.
-   Experiência com ferramentas e técnicas para debugar.

## O que mais você precisa saber sobre a RV
-	Plano de carreira estruturado com sessões de feedback recorrentes.
-	Ambiente de trabalho informal, transparente e que preza pela colaboração e respeito às pessoas de diversas origens, escolhas e culturas.
-   Incentivo educação: valor anual pra você utilizar da maneira que quiser e buscar mais conhecimentos.
-	Liberdade para ajudar a melhorar a cultura de desenvolvimento todos os dias.
-	Exposição direta ao time de engenharia global da Red Ventures em Charlotte.
-	Nós incentivamos a prática de atividade física: organizamos caminhadas/corridas entre os times e também temos uma parceria com o Gympass.
-	Red Adventure - de tempos em tempos, reunimos todo o time da RV em uma atividade fora do escritório (já teve Kart, Arco e Flecha, Escape 60).
-	Liberdade para ajudar a construir uma cultura de desenvolvimento cada vez melhor.
-	Convênio de saúde acima do mercado.
-	Bônus financeiro anual por performance.

## Como se candidatar
Candidate-se: https://grnh.se/20d14bd01

**Comment by matheusggds** [comment]
@elvisdetona Como é melhor mandar as informações, em Português ou Inglês?

**Comment by elvisdetona** [comment]
@matheusggds  Como você preferir 😃
