### ISSUE TITLE
[São Paulo] Senior Front-End Developer na SCCON

### ISSUE THREAD

**Issue by LuanaTOliveira** [frontendbr/vagas#1868]
## Descrição da vaga

Projeto de desenvolvimento em React /Redux para aplicação com dashboards, mapas e dados geoespaciais.
Buscamos um profissional sênior em React.

## Local

Escritório, Campo Belo - São Paulo-SP

## Requisitos

Experiência miníma com desenvolvimento front-end de 3 anos;
Experiência mínima de 18 meses só com desenvolvimento em REACT;
Demonstrar pró-atividade, foco e boa capacidade de trabalho em equipe;
Conhecimento Básico em AngularJS;

 

**Itens Técnicos Obrigatórios (Proficiência)**
Desenvolvimento HTML5;
Desenvolvimento CSS (SaSS/Less);
Javascript Nativo (Vanilla JS), com manipulação de DOM (ES5 e ES6);
Arquitetura de Microserviços REST; 
React Versão 15;

 
**Diferenciais**
Familiaridade com Orientação a Objetos e Design Patterns; 
Preocupação com compatibilidade de códigos entre diferentes navegadores e plataformas;
Experiência com automatizadores de tarefas como Webpack ou Gulp, e seus Plugins;
Familiaridade com geotecnologia (openlayers, leaflet)

## Contratação

PJ a combinar

## Nossa empresa
A SCCON desenvolve Soluções de GeoTI para seus clientes, usando a mais completa tecnologia geoespacial do mercado, assegurando a eficiência dos seus projetos, processos técnicos e de negócios que estão relacionados à execução de suas tarefas de aquisição, armazenamento, acesso, integração, análise e distribuição de dados e informações geoespaciais

## Como se candidatar

Por favor envie um email para luana.oliveira@sccon.com.br com seu CV anexado - enviar no assunto: Vaga Front-End (React)

## Labels

- Alocado
- PJ
- Pleno
- Sênior
- React
- Remuneração 8-10K

**Comment by ReactGirl** [comment]
Por que o requisito de manipulacao de DOM é obrigatorio a proficiencia se a vaga é pra React (programacao declarativa)? Ao menos que o sistema seja hibrido, com a conjectura dos dois, retornando falso no shouldComponentUpdate por exemplo.

**Comment by LuanaTOliveira** [comment]
> Por que o requisito de manipulacao de DOM é obrigatorio a proficiencia se a vaga é pra React (programacao declarativa)? Ao menos que o sistema seja hibrido, com a conjectura dos dois, retornando falso no shouldComponentUpdate ou usando refs. Seria esse o caso?

Olá ReactGirl, tudo bem? Acreditamos ser importante o conhecimento na manipulação DOM como complemento e base para os desafios do da vaga em questão, apesar do projeto no primeiro momento, ser em React.

**Comment by ReactGirl** [comment]
Lembrando que manipulacao de DOM nao é algoritmos e estrtutura de dados. Pra vaga de React esse conhecimento é inutil.
