### ISSUE TITLE
[São Paulo] Programador Front-end no GetNinjas

### ISSUE THREAD

**Issue by eduardojmatos** [frontendbr/vagas#187]
## Descrição da vaga

Você! Quer trabalhar com uma pequena equipe de desenvolvimento porém forte? Ser responsável por contribuir para todos os aspectos de definição, construção e manutenção do site do GetNinjas e seus serviços? Mudar a maneira como as pessoas buscam prestadores de serviço é o nosso ramo!

## Local

Escritório, São Paulo - Pinheiros
Fica a 100 metros do Metrô Fradique Coutinho - linha amarela. É muito perto do metrô. Mesmo!

## Benefícios

* Remuneração competitiva;
* Plano de saúde;
* Vale-Transporte;
* Vale-refeição;
* Gympass;
* Possibilidade de um enorme impacto positivo na maneira como as pessoas usam a internet;
* Os NINJAS amam: Lanches e frutas gratuitas, ambiente de trabalho descontraído, divertido e descolado, NERFS, chinelo, bermuda, churrascos, cesta de basquete, Puffs, Tech Talks e NINJA Tech Day;

## Requisitos

**Obrigatórios:**
* Ter experiência com desenvolvimento de Web;
* Ter grande habilidade com desenvolvimento de software;
* Grande habilidade e facilidade com comunicação;
* CSS (usamos o pré-processador Sass);
* HTML (semântica e acessibildiade);
* JavaScript - conhecimento da linguagem além dos frameworks;
* Ter experiência com Mobile First;
* Git;
* Arrumar soluções para a melhor experiência pro usuário, pensando na qualidade de serviço como um todo;
* Aprendizado contínuo e disseminação do conhecimento adquirido;

**Desejáveis:**
* conhecimento de Ruby / Rails;
* Testes de JavaScript (TDD / BDD) com Jasmine, Mocha, Sinon, etc..

**Diferenciais:**
* Ter trabalhado com alguma arquitetura e/ou metodologia de CSS (ITCSS, BEM, SMACSS, etc.);

## Contratação

CLT

## Nossa empresa

**O GETNINJAS**

Com mais de 120 mil profissionais cadastrados em todo o Brasil, divididos em mais de 100 subcategorias, e uma média de 100 mil cotações por mês no site, o GetNinjas.com.br já captou mais de R$ 47 milhões de investimento da Tiger, Monashees Capital, Kaszek Ventures e Otto Capital.

Atualmente, o GetNinjas proporciona uma renda de aproximadamente 14 milhões de reais aos nosso usuários por meio da nossa plataforma e por esse e outros motivos que acreditamos que podemos trabalhar para mudar o Mundo!

## Como se candidatar

Para se candidatar, basta aplicar para a vaga no site [https://getninjas.workable.com/jobs/252164](https://getninjas.workable.com/jobs/252164) (se possível, diga que viu a vaga aqui no frontendbr/vagas =D).

**Comment by eduardojmatos** [comment]
Vamos reabrir o processo e vaga

**Comment by brunooomelo** [comment]
getJuniors?
