### ISSUE TITLE
[Remoto ou Ribeirão Preto] Desenvolvedor iOS Pleno e Sênior [Beblue]

### ISSUE THREAD

**Issue by TatianeBeblue** [frontendbr/vagas#1874]
iOS - Pleno e Sênior (Home Office ou Presencial)

Você tem ou conhece alguém com experiência com programação iOS (Objective C/Swift), TDD, BDD e DDD e desenvolvimento Agile?

No link abaixo você pode se candidatar ou compartilhar a vaga com a sua rede? 

*Sênior - x
*Pleno - x

💙 Venham vestir a camisa Beblue e fazer parte da Startup mais azul do Brasil.

#Beblue
#frontend
#react
#vemserblue

**Comment by juulhao** [comment]
Acho que essa vaga não faz muito o perfil deste grupo que é focado em Front.
Existe algo Pra React nesta vaga?

**Comment by TatianeBeblue** [comment]
@juulhao Boa Tarde! 

Na verdade também tenho vagas para react. Caso tenha interesse, por gentileza acessar o link a seguir: https://jobs.kenoby.com/beblue/job/sre-engenheiro-de-sistema-pleno-e-senior-2-vagas/5c86af59479e3c043485ec00

**Comment by MrS4w** [comment]
Siga os padrões de issue e coloque apenas vaga de front ou full-stack, por favor. :smile:

**Comment by felipefialho** [comment]
Vaga inválida e fora dos padrões.

Labeei no automatico, my bad, hahaha.
