### ISSUE TITLE
[Remoto Full Time] Frontend Developer na Angular e-Commerce

### ISSUE THREAD

**Issue by reichert** [frontendbr/vagas#1875]
## Vaga preenchida
- Pessoal, agradeço a todos que enviaram os seus CVs, já fizemos a contratação.

## Descrição da vaga
Quer programar de pijama? :)
Vaga para desenvolvedor frontend com experiência em Angular 2+.
A vaga é remota para trabalhar de casa e o regime de contratação é CLT. Apesar de remota, a vaga não é para freela - o candidato se tornará colaborador da empresa por tempo indeterminado.

## Local
Remoto, das 8h30 as 17h30

## Requisitos

**Obrigatórios:**
- 1 ano de experiência com Angular 2+;
- Senso de responsabilidade com entrega (prazos, qualidade)
- Comunicação: saber se expressar, verbalmente e por escrito, com clareza, paciência e educação (não vale ficar bravo com o coleguinha)

**Recomendáveis:**
- conhecimentos em Angular-cli, Material2, Flex Layout, In Memory API, SASS, HTML 5
- formulários reactive forms do angular
- padrões de SASS: `Variables`, `Nesting`, `Partials`, `Import`, `Extend/Inheritance`, `Operators`, `Function` & `Mixin` 

**Desejáveis:**
- senso artístico para fazer telas bonitas (a equipe de design fornece o PSD)

## Contratação
CLT - Valor a combinar

## Nossa empresa
A Angular e-Commerce é uma empresa especializada em plataforma de gestão de academias & e-commerce. Somos os fornecedores de empresas como studiovelocity.com.br e ridestate.com (uma parte do nosso sistema É o website do cliente)

## Como se candidatar
Por favor envie um email para rh@angular-ecommerce.com com seu CV anexado - enviar no assunto: Vaga Angular 2+
Após se candidatar solicitaremos que faça um teste de conhecimento - disponível aqui: https://gitlab.com/amarkes/teste-frontend/tree/master

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 2 dias após cada processo.

## Labels
- Remoto
- CLT
- Júnior
- Pleno
- Remoto
- Angular
- JS

**Comment by vinculuzX** [comment]
aceita pj?

**Comment by kassiacatarine** [comment]
Assim que enviar o currículo já faz o teste ou precisa esperar a resposta de vocês?

**Comment by jass2125** [comment]
Enviado!

**Comment by jass2125** [comment]
Você recebeu algum feedback @kassiacatarine ?

**Comment by kassiacatarine** [comment]
Ainda não recebi nenhum feedback @jass2125
