### ISSUE TITLE
[São Paulo] Front end Developer  React no Hubster

### ISSUE THREAD

**Issue by AndreAffonso** [frontendbr/vagas#1876]
## Descrição da vaga

Estamos construindo uma plataforma de gestão para food services com intuito de ajudar 
os restaurantes a administrarem seus pedidos, controle de estoque, financeiro, etc. Para isso, estamos realizando a integração com os principais aplicativos de delivery(iFood, Rappi e Uber Eats). 
 

## Local

Escritório em São Paulo, Rua James Watt, 84 - Berrini

## Benefícios

- Almoço pago em restaurantes parceiros. 

#### Diferenciais

- Horário Flexível
- Ambiente Descontraído

## Requisitos

**Obrigatórios:**
- Conhecimento sólido de Javascript, HTML e CSS
- Conhecimento sobre protocolo HTTP e experiência com api's rest
- Experiência com desenvolvimento em React

**Desejáveis:**
- Experiência com Redux
- Experiências com desenvolvimento de PWAs

**Diferenciais:**
- Experiência com React Native.
- Experiência com testes(unit tests, integration, e2e)
- Experiências em ambientes de integração contínua. 

## Contratação

PJ a combinar

## Nossa empresa

O Hubster é um sistema de gestão  com foco em  food services. Com ele, você tem fácil acesso à emissão de notas fiscais e integração com cupom SAT, integração com canais de delivery e todas outras funcionalidades de um ERP, através de uma interface completamente intuitiva e atual. 

Nossos fundadores tem menos de 35 anos, já venderam uma startup com 30 e agora estão em busca de um passo ainda maior. Que tal nos ajudar a fazer parte dessa história?

## Como se candidatar

Por favor envie um email para andre.melo@hubster.com.br me falando um pouco de você e de seus projetos mais relevantes. 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: andre.melo@hubster.com.br

## Labels

- Alocado
- PJ
- Pleno
- Junior

**Comment by juulhao** [comment]
Qual salário pra Pleno?
