### ISSUE TITLE
[Belo Horizonte] Front-End Developer na Midhaz

### ISSUE THREAD

**Issue by RHMidhaz** [frontendbr/vagas#1877]
**Sobre nós:** 
Aqui na Midhaz temos o propósito de incentivar a cultura empreendedora através da possibilidade de qualquer pessoa conseguir ter uma loja virtual mesmo sem ter estoque. Tudo isso com uma equipe extremamente focada em proporcionar a melhor experiência ao nosso cliente e aos seus compradores.
 
Você irá realizar o desenvolvimento front-end de sistemas novos ou existentes a fim de proporcionar à essas pessoas um ambiente estável e funcional. Além de ter a oportunidade de trabalhar com uma equipe foda em um ambiente totalmente descontraído.
 
Para essa oportunidade buscamos alguém que tenha **experiência** com:
* Javascript  
* ES6
* HTML
* CSS 
* React JS (Mínimo 2 anos)
* Noções de UI/UX, será um diferencial! 🙂

**Nível de experiência:**
* Pleno-Sênior
 
**Tipo de emprego:**
* CLT
 
**Benefícios:**
* No Dress Code
* Horário flexível
* Vaga no Estacionamento
* Vale refeição
* Vale transporte
* Seguro de vida

**Comment by luqezman** [comment]
Contato para envio de candidatura?

**Comment by RHMidhaz** [comment]
> Contato para envio de candidatura?

Olá, boa tarde! Pode encaminhar para rh@midhaz.com

**Comment by LopesAlysson** [comment]
Alocado ou Remoto?

**Comment by RHMidhaz** [comment]
> Alocado ou Remoto?

Olá, alocado! :)
