### ISSUE TITLE
[São Paulo] Front-End Developer Sênior (Vuejs) no Casar.com

### ISSUE THREAD

**Issue by rodrigocarlospires** [frontendbr/vagas#1878]
## Descrição da vaga

Desenvolver e suportar aplicações Vuejs

## Local

Escritório, São Paulo - Pinheiros

## Benefícios

- Salário compatível
- Vale refeição
- Vale transporte
- Vale alimentação / Plano de saúde
- Bônus

#### Diferenciais

- Horário flexível (o que importa são as entregas)

## Requisitos (Quem queremos contratar)

**Obrigatórios:**
- Quem tenha experiência em desenvolvimento de software utilizando frameworks em Javascript, principalmente Vuejs;
- Quem tenha conhecimentos sólidos em arquiteturas de HTML e CSS, usando as melhores práticas e ferramentas, assim como Stylus, SASS, SCSS, PostCSS, etc;
- Quem conheça muito bem testes unitários e metodologias de testes;
- Quem utilize Git para controlar o versionamento de seu código;
- Quem tenha prática profissional significativa usando APIs e Web Services;
- Quem domine as melhores práticas de desenvolvimento, como Design Patterns;
- Quem tenha experiência de pelo menos 2 anos com desenvolvimento de aplicações SPA;
- Quem se sinta motivado e desafiado diante de problemas complexos;
- Quem tenha experiência com aplicações mobile first;
- Quem seja criativa, curiosa e aberta às mudanças tecnológicas;
- Quem atue com leveza e bom humor para tornar a equipe sempre melhor.

**Desejáveis:**
- Já tiver trabalhado como líder de equipe e/ou orientando outros devs;
- Tiver entendimento e/ou experiência com metodologia Scrum;
- Possuir noções de docker/containers;
- Tiver noções básicas de serviços AWS.

## Contratação

CLT

## Nossa empresa

Nascemos com o propósito de tornar a jornada do casamento a melhor, mais fácil e encantadora experiência para os noivos. Nós acreditamos no casamento: é um momento compartilhado com a família, os amigos e a comunidade. Todos os dias nos perguntamos como estamos tornando a vida dos casais mais fácil, divertida e fascinante. Fazemos tudo isso de forma humana, com prazer e empolgação.

## Como se candidatar

Por favor envie um email para rodrigo@casar.com com seu CV anexado - enviar no assunto: Vaga Vuejs

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: rodrigo@casar.com

## Labels

- Alocado
- Sênior
- São Paulo

**Comment by alessandroprudencio** [comment]
Só presencial?

**Comment by rodrigocarlospires** [comment]
Vaga preenchida pelo Linkedin. Obrigado a todos que enviaram currículo.
