### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor Back-End na Mongeral Aegon

### ISSUE THREAD

**Issue by alanhr** [frontendbr/vagas#188]
## Desenvolvedor Back-End PHP na Mongeral Aegon

Fala, pessoal!

Tá tendo duas vagas pra back-end na área de novos negócios digitais da Mongeral Aegon aqui no Rio.

Apesar da idade da empresa (180 anos!!!!), nossa equipe é uma equipe ​˜xovem˜​ e ​˜descolada˜​. Temos tentado aplicar várias coisas novas por aqui e você vai ter abertura para propor e entregar projetos bacanas.

Curtimos muito metodologias ágeis, fazemos tech talks às sextas-feiras e temos uma cestinha de basquete pra você praticar caso desista de ser programador.

Temos vários projetos de diferentes segmentos, desde imobiliárias à um instituto de longevidade e, claro, projetos relacionados a seguradora.

**Coisas não tããão legais:**
- Precisa usar roupa social ou camisa polo da empresa.
- Não rola ser home office.
## Local

Rio de Janeiro - Centro
## Benefícios
- Vale Transporte
- Vale Refeição 
- Vale Alimentação 
- Auxílio café da manhã em uma padaria perto do trabalho
- Plano de saúde e dental
- Participação nos lucros
- Fundo Multipatrocinado (previdência)
## Requisitos (Júnior)

**O que você PRECISA saber:**
- Versionar seu código (usamos GIT)
- Saber trabalhar com Linux
- Ter trabalhado com algum framework de mercado (Ex. Zend / Symfony / Laravel / CodeIgniter / Cake).
- Desejável experiência em aplicações Web utilizando MVC, AJAX, OOP, PDO, JSON e XML
- TDD
- Inglês técnico
- Conhecimento em Modelagem de dados

**Aquele famoso ​˜plus a mais˜​:**
- Algum framework Javascript (Angular, Ember e etc…)
- Design Patterns e SOLID
- Interesse por outras linguagens Python, Node e etc
- Conhecimentos em DEVOPS será um diferencial (DOCKER e VAGRANT)
- Conhecimento em aplicações back office (Ex. CMS/Dashboard) e E-commerce
- Participar da comunidade, ir a eventos e tal
- Ter interesse por novos negócios

## Contratação

CLT
## Como se candidatar

Manda também um currículo/Linkedin com pretenção pra nós. aserafim@mongeralaegon.com.br

**Comment by alanhr** [comment]
Olá @LFeh  poderia colocar as tags  jr e clt  por favor.

**Comment by LFeh** [comment]
Puts, agora que vi que a vaga é BackEnd, estamos mantendo só vagas de Front por aqui :(

**Comment by alanhr** [comment]
A saquei sem problemas, então pode deletar essa issu.
