### ISSUE TITLE
[São Paulo] Desenvolvedor(a) Front-end na Forma Turismo

### ISSUE THREAD

**Issue by leandrodasler** [frontendbr/vagas#1880]
## Descrição da vaga

A Forma aumentou o tamanho da sua equipe de desenvolvimento! E agora precisamos de alguém que manje de Desenvolvimento Web pra dar aquela força! Se você está pronto para esse desafio, quer trabalhar com uma metodologia dinâmica e fazer coisas legais, veja o que precisamos:

## Local

Moema, São Paulo - Somente Alocado

## Requisitos
- Noções de: Angular, HTML5, CSS (SASS/LESS), Javascript, JQuery, PHP (WordPress), REST, Gulp, GIT.
- Saber fazer coisas legais, bonitas e bacanudas seguindo o padrão web 3.0
- Manjar de photoshop (não precisa criar nada, mas saber usar o que receber)
- Estar disposto a fazer coisas pra você contar aos amigos que "foi você quem fez"

## Desejável
- Estar disposto a aprender sempre
- Aguentar a zoeira sem limites ;)

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ 30/dia
- VT

## Contratação

CLT

## Nossa empresa

A Forma Turismo é a maior empresa de turismo especializada em viagens de formatura do Brasil. Com 21 anos de experiência e mais de 20 destinos.

## Como se candidatar

Os interessados podem encaminhar seus CVs para oportunidades@formaturismo.com.br

## Labels

- Alocado
- CLT
- Júnior
- Pleno
- Sênior

**Comment by thayllachristine** [comment]
A vaga ainda está em aberto?
