### ISSUE TITLE
[Joinville] Front-End Developer Sênior na ProJuris

### ISSUE THREAD

**Issue by hunter-douglas** [frontendbr/vagas#1881]
## Descrição da vaga

Como programador front-end na Projuris, você terá grandes desafios na área de desenvolvimento de software. Desenvolver interfaces de acordo com as especificações técnicas pensando sempre na usabilidade e na simplicidade para o usuário final. Sua responsabilidade será em desenvolver um código manutenível e bem estruturado. Tudo isso em um ambiente colaborativo e com grandes oportunidades de crescimento profissional e com um time de grande performance.
## Local

Remoto ou Escritório, Joinville - América

## Benefícios

- Participação nos Resultados - PPR
- Plano odontológico
- Plano de saúde
- Vale alimentação
- Horário flexível
- Vale transporte
- Ginástica Laboral
- Ambiente trabalho dinâmico com pessoas engajadas com os valores da empresa
- Bolsas de Estudos
- Happy hour
- Seguro de Vida
- Disponibilidade de frutas

## Requisitos

**Obrigatórios:**
- Angular/ReactJS
- Javascript
- CSS
- HTML5
- Git
- Bootstrap
- Scrum
- Nível superior na área de sistemas ou afins em andamento ou concluído

**Diferenciais:**
- Java 8
- Spring Boot
- AWS

## Contratação

CLT ou PJ

## Nossa empresa

O DUO Tecnologia desenvolve o ProJuris, sendo o principal protagonista da evolução do mercado tecnológico jurídico, tendo sido o primeiro software jurídico online e o primeiro chatbot com inteligência artificial do Brasil.
Descobrimos que a ineficiência é o principal obstáculo do advogado corporativo, portanto, oferecemos uma experiência jurídica mais eficiente, segura e descomplicada.
Diariamente milhares de profissionais em todo o Brasil que acreditam no poder da realização deste sonho. E mesmo com a crise, crescemos 35% nos últimos 3 anos.
Diante do desafio desse crescimento, estamos evoluindo também nosso time técnico e procuramos por um profissional diferenciado, que acredite e exerça qualidade nas suas atividades, seja dinâmico e tenha muita vontade. Vamos sonhar juntos?

## Como se candidatar

Acesse: https://vagas.hunterco.com.br/job/5c8be0dcaef434000f12b9d0?r=rltd

## Tempo médio de feedbacks

Sempre damos retorno dos posicionamentos da empresa contratante e cobramos quando não ocorrer.
E-mail para contato em caso de não haver resposta: falecom@hunterco.com.br

## Labels

- Alocado
- CLT
- PJ
- Remoto
- Sênior

**Comment by danielswater** [comment]
Enviado

**Comment by ReactGirl** [comment]
As vagas do Brasil pra desenvolvedor ainda tao exigindo nivel superior?

**Comment by andreferraro** [comment]
> As vagas do Brasil pra desenvolvedor ainda tao exigindo nivel superior?

Não só no Brasil. Portugal, Espanha, Irlanda, muitas aí nos EUA tbm exigem. Normal. Pra mim é o mesmo que pedir ensino médio.

**Comment by ReactGirl** [comment]
So se for empresa bem ruizinha. A google, a Apple e a Amazon nao pedem. hoje em dia fazer faculdade é jogar dinheiro no lixo.
