### ISSUE TITLE
[Cascavel] Front-End Developer no Focus Concursos

### ISSUE THREAD

**Issue by lc-brito** [frontendbr/vagas#1882]
# Descrição da vaga
Desenvolvimento de soluções para a área de educação, em PHP (Laravel) e JavaScript (Vue).

# Local
Remoto ou Cascavel/PR.

# Requisitos
**Obrigatórios**
- Experiência com HTML5, CSS3 e pré-processadores.
- Experiência no desenvolvimento com javascript [ES5, ES6].
- Experiência com aplicações SPA.
- Experiência com APIs Restful.
- Experiência em algum Framework baseado em componentes (Vuejs, React, Angular).
- Experiência com Git.
- Experiência com Vue.
- Capacidade de trabalhar em equipe (pró-ativo).

**Diferencial**
- Conhecimento em PWA.
-  Conhecimento prático sobre SOLID, clean code, refactoring e testes automatizados.
-  Conhecimentos básicos de Laravel 5 ou outro framework PHP MVC.
-  Conhecimentos em UX.

# Contratação
PJ a combinar.

# Como se candidatar
Envie seu LinkedIn, GitHub, CV, Contato, Email para luis@grupofocus.com.br com o assunto Vaga Front-End.

# Tempo médio de feedbacks
Costumamos entrar em contato em até 01 dia após receber seu contato.

**Comment by MrS4w** [comment]
- PHP
- API
- Vue
- SPA
As labels acima não são necessárias.

**Comment by lc-brito** [comment]
Considerei a sugestão @MrS4w

**Comment by nandomoreirame** [comment]
> Envie seu LinkedIn, GitHub, CV, Contato, Email para luis@grupofocus.com.br com o assunto Vaga Back-End.

Vaga é para Front-end ou Back-end? 🤔

**Comment by lc-brito** [comment]
> > Envie seu LinkedIn, GitHub, CV, Contato, Email para [luis@grupofocus.com.br](mailto:luis@grupofocus.com.br) com o assunto Vaga Back-End.
> 
> Vaga é para Front-end ou Back-end?

A vaga é para Front-End. Obrigado por informar a inconsistência.
