### ISSUE TITLE
[REMOTO] Front-End Developer na MUFASA

### ISSUE THREAD

**Issue by danilowm** [frontendbr/vagas#1885]
## Descrição da vaga

- Ajustes e criação de sites em WordPress
- Criação de landing pages e hotsites
- Desenvolvimento de sites

## Local

Araçatuba/SP ou Remoto

## Requisitos

**Obrigatórios:**
- Bootstrap
- PHP
- Gulp
- Git

**Desejáveis:**
- conhecimentos em PHP
- conhecimentos em WordPress
- conhecimentos em WooCommerce

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para danilo@mufasa.com.br com seu CV anexado - enviar no assunto: Vaga Front-End Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.

## Labels

- Alocado
- PJ
- Remoto

**Comment by juulhao** [comment]
Qual o salário para esta oportunidade?

**Comment by danilowm** [comment]
Favor enviar o CV para danilo@mufasa.com.br e a pretensão. Estamos abertos a negociação.

**Comment by danilowm** [comment]
Editei a vaga pois estamos com mais uma oportunidade na mufasa 👍

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
