### ISSUE TITLE
[Teresópolis/RJ e Nova Friburgo/RJ] Front-End Developer para Alterdata Software

### ISSUE THREAD

**Issue by recursoshumanosalterdata** [frontendbr/vagas#1886]
Front-End Developer 

Quer ser Alterdatano e fazer parte de uma das maiores empresas de tecnologia 100% nacional?

A Alterdata é uma empresa que tem como objetivo melhorar a vida das pessoas, fornecendo soluções empresariais através de softwares e serviços.

Você integrará nosso time de especialistas, desenvolvendo produtos da área contábil, utilizando as mais diversas tecnologias disponíveis no mercado.

Temos somente uma regra! Nunca ficamos parados, pois inovação é o que nos inspira a cada dia.

Gosta de aprender e ser desafiado? Esse é o lugar! 

Vagas para Matriz(Teresópolis) ou Polo de DSN de Software de Nova Friburgo/RJ (Não é home office).

Benefícios:

- Plano de saúde
- Plano odonto
- Gym pass
- VR ou VA de R$ 25,31/dia
- Cargos e Salários
- VT

* Sala de jogos com Xbox e Sinuca, sala de relaxamento, refeitórios, intervalo para lanches e open café.

Requisitos:

**Obrigatórios:**

- Superior completo ou cursando. 
- JavaScript, Angular e AngularJS
- Material Design
- HTML/HTML5 e CSS
- Pré processadores (sass e less)
- Desenvolvimento web responsivo
- Gostar de desafios e de trabalhar em equipe 

**Desejáveis:**

- Bootstrap
- Design de interfaces
- Desenvolvimento mobile hibrido(Cordova ou similar)
- Métodos Ageis
- Atenção aos detalhes
- Boa comunicação e capacidade de autoaprendizado

**Diferenciais:**
- React Native
- Conhecimento em Backend;
- Experiência com Teste A/B
- Conhecimentos em TDD e BDD

Contratação:
CLT (Full time)

Nossa empresa:

https://www.youtube.com/watch?v=fEmWlVka-H4&t=3s
https://www.alterdata.com.br

Como se candidatar?

Por favor envie um email para greyce.rh@alterdata.com.br com seu CV anexado - enviar no assunto: Vaga Front-End Developer

Tempo médio de feedback's?

Costumamos enviar feedbacks em até 07 dias após cada processo.

E-mail para contato em caso de não haver resposta: greyce.rh@alterdata.com.br

## Labels

- Alocado
- CLT
- Estágio
- Júnior
- Pleno
- Sênior

**Comment by nandosangenetto** [comment]
Nossa, meu sonho era trabalhar em Teresópolis há alguns anos! Boa sorte na procura, empresa legal e em um lugar incrível.

**Comment by recursoshumanosalterdata** [comment]
@nandosangenetto envia seu CV ou indicações. ficamos muito felizes pelo seu feedback! um grande abraço e sucesso!!!

**Comment by lucianobarauna** [comment]
Realmente teresópolis é um lugar irado... empresa legal também :-)

**Comment by recursoshumanosalterdata** [comment]
Vem para Tere @lucianobarauna!!! Um abraço e sucesso amigo!!!

**Comment by kavalcante** [comment]
@recursoshumanosalterdata Acredito que vocês fecharam a vaga sem querer, dessa forma ela não será vista facilmente...

**Comment by recursoshumanosalterdata** [comment]
@kavalcante muito obrigado por nos alertar...realmente foi sem querer. 

Um grande abraço!

**Comment by kavalcante** [comment]
@recursoshumanosalterdata Imagina! Sucesso na busca pelos candidatos.

**Comment by alessandrocode09** [comment]
Com tantas pessoas falando bem da cidade e da empresa, irei enviar meu currículo sim. Tem possibilidade do processo seletivo ser Remoto ? Não moro nem no estado do Rio de Janeiro

**Comment by recursoshumanosalterdata** [comment]
@alessandrocode09 o processo pode ser feito remoto sim, em caso de aprovação vamos precisar que o candidato tenha disponibilidade de residir em Teresópolis ou Nova friburgo/RJ.

**Comment by felipenoka** [comment]
@recursoshumanosalterdata tem vaga para estágio?  Meu sonho trabalhar em terê!! Do ladinho de casa :D
