### ISSUE TITLE
[São Paulo] Front-End Developer na Weef

### ISSUE THREAD

**Issue by diegoapolinario** [frontendbr/vagas#1888]
## Descrição da vaga

Somos uma produtora web reconhecida como parceira preferencial de algumas das mais renomadas agências do país. Estamos contratando profissional para ampliar nosso time e agregar novas competências. O(a) programador(a) será responsável pelo desenvolvimento de aplicações web e mobile.

## Local

Presencial na Rua Azevedo Macedo - Vila Mariana (Ao lado do metrô Ana Rosa)

## Benefícios

- VR
- VT

## Requisitos

**Obrigatórios:**
- Experiência comprovada em web (apresentar portfólio)
- Experiência em desenvolvimento mobile ou muita disposição para aprender
- HTML5, CSS3, SASS
- JavaScript
- Bootstrap e jQuery

**Desejáveis:**
- PHP
- WordPress
- Node.js
- Angular / TypeScript
- Ionic / Cordova
- Outras linguagens back-end
- Outros frameworks JS
- Banco de dados SQL e NoSQL

**Diferenciais:**
- Liderança de equipe
- Inglês intermediário

## Contratação
CLT / PJ

## Nossa empresa
Somos a Weef, uma produtora digital independente, especializada na criação e desenvolvimento de sites, aplicativos e projetos especiais  com alto nível de exigência.

Temos um amplo portfólio de projetos feitos em parceria com algumas das mais prestigiadas agências e marcas do país.

Nosso time reúne designers, arquitetos e desenvolvedores altamente especializados e apaixonados por desafios, que estarão ao seu lado em todas as etapas do projeto, da concepção à entrega final.

## Como se candidatar

Por favor preencha o formulário no Google Forms com suas informações de contato e habilidades: https://goo.gl/forms/3JkUN9Q5Wiy4Kftr2

## Labels

- Alocado
- CLT
- Pleno
- Sênior

**Comment by MrS4w** [comment]
Vaga fechada pelo seguinte motivo: **Período de 3 meses sem manutenção.**
