### ISSUE TITLE
[Portugal] Frontend Developer na Aubay

### ISSUE THREAD

**Issue by Margarida86** [frontendbr/vagas#1889]
Projetos em vários setores de atividade, usando diversas tecnologias de Frontend tais como Jquery, Angular entre outras

Local
Portugal: Lisboa e Porto

Benefícios
• Plano de saúde
• Visto de Trabalho para Portugal
• Outras

Diferenciais
• Formações técnicas, comportamentais e de idiomas
• Prémios de referências de recrutamento
• Eventos Team Building
• Convívio mensal
• Oferta de aniversário

Requisitos
Obrigatórios:
• Experiência profissional na área web
• Bons conhecimentos de Javascript, HTML, CSS
• Experiência em Angular
• Fluência na língua Inglesa

Desejáveis:
• Experiência em Node.js/React

Diferenciais:
• Experiência internacional

Contratação
Apoio em todo o processo para obtenção de visto de trabalho para Portugal.

Nossa empresa
A Aubay, é uma empresa de origem francesa presente em diversos países na Europa.
Como cerca de 7000 pessoas desenvolvemos projetos nas mais diversas tecnologias.
Neste momento, temos várias vagas em aberto para várias posições.

Como se candidatar
Por favor envie um email para mtavares@aubay.com com seu CV em Inglês anexado e o assunto FD_19.

**Comment by MrS4w** [comment]
Vaga fechada pelo seguinte motivo: **Período de 3 meses sem manutenção.**
