### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor Front-End na Mongeral Aegon

### ISSUE THREAD

**Issue by RSPereira** [frontendbr/vagas#189]
## Desenvolvedor Front-End na Mongeral Aegon

Fala, pessoal!

Estamos com vagas pra front-end na área de novos negócios digitais da Mongeral Aegon aqui no Rio.

Apesar da idade da empresa (182 anos!!!!), nossa equipe é ~~xovem~~ e ~~descolada~~. Temos tentado aplicar várias coisas novas por aqui e você vai ter abertura para propor e entregar projetos bacanas.

Curtimos muito metodologias ágeis, fazemos tech talks às sextas-feiras e temos uma cestinha de basquete e nerf pra você praticar caso desista de ser programador.

Temos vários projetos de diferentes segmentos, desde imobiliárias à um instituto de longevidade e, claro, projetos relacionados a seguradora.

**Coisas não tããão legais:**

- Precisa usar roupa social ou camisa polo da empresa.
- Não rola ser home office.

## Local

Rio de Janeiro - Centro

### Benefícios

- Vale Transporte
- Vale Refeição (R$ 27,46 ao dia)
- Vale Alimentação (R$ 469,85)
- Auxílio café da manhã em uma padaria perto do trabalho
- Plano de saúde e dental
- Participação nos lucros
- Fundo Multipatrocinado (previdência)

## Requisitos (Estagiário)

**O que você PRECISA saber:**

- HTML5
- CSS3 (Melhor se usar algum pré-processador)
- Javascript (Básico)

## Requisitos (Júnior)

**O que você PRECISA saber:**

- Requisitos anteriores
- Javascript
- Algum task runner/bundler
- Versionar seu código (usamos GIT)

## Requisitos (Pleno)

**O que você PRECISA saber:**

- Requisitos anteriores
- ES6
- Algum framework Javascript (usamos ReactJS)

**Aquele famoso ​~~plus a mais~~​:**

- Saber trabalhar com Linux
- Participar da comunidade, ir a eventos e tal
- Ter interesse por novos negócios
- Saber usar o Git Flow
- Flow (Type checker)
- Metodologias Ágeis

## Contratação

CLT

## Como se candidatar

Se tu curtiu e tá afim de trabaio dê um fork no nesse respositório e faça o nosso teste
https://github.com/MongeralAegonDigital/front-end-trabalhe-na-mad

Manda também um currículo/Linkedin com pretenção pra nós. rspereira@mongeralaegon.com.br

Se você tiver um portfólio maneiro ou Github pode mandar junto.

**Comment by RSPereira** [comment]
@LFeh pode adicionar as tags pra mim? estag, jr, pleno e clt

**Comment by LFeh** [comment]
Boa vaga!

**Comment by RSPereira** [comment]
Trocou junior por pj rs... pode arrumar? :)

**Comment by freeboxd** [comment]
Eu tinha conversado com o Hugo Dutra sobre a vaga Júnior há um tempo. Fiz o teste e tudo mais mas parece que não dava pra aceitar porque estava completando o Ensino Médio.
Vocês tem o interesse de reavaliar? Também aprendi algumas coisas novas pra pesar.

**Comment by RSPereira** [comment]
Fala @freeboxd, vimos aqui realmente que você chegou a fazer o teste e tal mas realmente aqui não podemos contratar no Ensino Médio. Como está sua situação atual? Pra concorrer a essa vaga, você precisa ter terminado o Ensino Médio e estar disposto a entrar na faculdade assim que entrar aqui.

**Comment by freeboxd** [comment]
Então... depende mais da urgência da vaga. Eu já finalizei o Ensino Médio... é só questão do tempo da colação de grau e pegar diploma mesmo.

Como é o lance da faculdade? Eu já prestei vestibular e estou esperando resultado. Eu preciso entrar e já ter vaga na faculdade garantida?

**Comment by saulojmc** [comment]
Vou participar do processo! Obrigado pela oportunidade.
Estou fazendo computação pela UFF e tenho disponibilidade de manhã e de
tarde pro estágio.
Vou encaminhar também o meu currículo para o email

*Atenciosamente*

*Saulo Melo*
*2.O.M. -  Marinha do Brasil*
*Engenheiro Mecânico - CEFET/RJ*
*"Marinha do Brasil, irrigadora de recursos na economia do País"*

Em 8 de dezembro de 2016 14:35, Guilherme Nunes <notifications@github.com>
escreveu:

**Comment by lucianobarauna** [comment]
Participando da seleção.
Mandei minha proposta para vocês.
Abrcs

**Comment by LFeh** [comment]
@RSPereira Fechou a vaga por aqui?

**Comment by camilatigre** [comment]
@RSPereira 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by RSPereira** [comment]
@LFeh e @camilatigre desculpem a demora.

Dessa vez não fechamos a vaga por candidatos que vieram daqui.

**Comment by antoniotex** [comment]
Essa vaga era espetacular. Será que estão precisando de novos estagiários?!
