### ISSUE TITLE
[Uberlândia MG] Front-End Developer na ZupIT

### ISSUE THREAD

**Issue by pedropnaves** [frontendbr/vagas#1890]
## Descrição da vaga

Projeto de um grande banco internacional para trabalhar com Node.js

## Local

Escritório, Uberlândia - Uberlandia Business Tower

## Benefícios

- Plano de saúde
- Plano Odontológico
- Seguro de vida
- VR de R$ 453,20
- Verba anual de treinamento
- PLR
- Plano de celular

#### Diferenciais

- Ambiente colaborativo
- Sala de jogos

## Requisitos

**Obrigatórios:**
- Experiência com JavaScript
- Experiência com Node.js
- Bom relacionamento
- Vontade de aprender e de ensinar

**Desejáveis:**
- GIT

## Contratação

CLT

## Nossa empresa

Nosso escritório em Uberlândia (MG)! Dá uma olhadinha:
![33903261-fcc60b28-df5e-11e7-9eaa-9d813a906ec2](https://user-images.githubusercontent.com/6892513/54756127-55680900-4bc6-11e9-8748-88aec681a76e.jpg)
![33903262-fce9d6ca-df5e-11e7-8587-05bc41c7c34f](https://user-images.githubusercontent.com/6892513/54756174-6add3300-4bc6-11e9-892c-228e056d482f.jpg)

## Como se candidatar

Por favor envie um email para pedro.naves@zup.com.br com seu CV anexado - enviar no assunto: Vaga NodeJS

## Labels

- CLT
- Júnior
- Pleno

**Comment by guilhermeoa07** [comment]
Olá, tenho interesse na vaga, mas sou de outro estado, é possível fazer o processo seletivo remotamente?

**Comment by pedropnaves** [comment]
> Olá, tenho interesse na vaga, mas sou de outro estado, é possível fazer o processo seletivo remotamente?

Opa, é sim :)
