### ISSUE TITLE
[Goiânia/GO] Fullstack Developer na Rancho Soluções

### ISSUE THREAD

**Issue by vitorlc** [frontendbr/vagas#1891]
## Descrição da vaga

Estamos buscando desenvolvedores Fullstack Javascript para fazer parte da nossa equipe.

## Local

Escritório, Goiânia - Goiás

## Requisitos

**Obrigatórios:**
- Base sólida em Javascript 
- Integração e consumo de API REST
- Git

**Desejáveis:**
- conhecimentos em VueJS
- conhecimentos em NodeJS

## Contratação

PJ a combinar

## Nossa empresa

Inovação continua e excelência operacional para a pecuária mundial. 

A Rancho nasceu a partir de uma dor sentida por muitos pecuaristas que desejam conhecer melhor o seu negócio através do uso da tecnologia.

Nossa missão é criar e oferecer soluções de tecnologia que aumentem a produtividade e a rentabilidade do produtor e, ao mesmo tempo, tornem a sua vida mais fácil.

## Como se candidatar

Por favor envie um email para marcelo[arroba]irancho[pontoo]com[pontoo]br com seu CV anexado

## Labels

- Estágio
- Júnior
- PJ
- Pleno

**Comment by robertov8** [comment]
Remoto?

**Comment by lpaivareis** [comment]
Ainda Aberto?

**Comment by robertov8** [comment]
Enviado! =D
