### ISSUE TITLE
[SAO PAULO] Front-End Developer React Pleno na iDev Solucoes

### ISSUE THREAD

**Issue by pfrancezi** [frontendbr/vagas#1892]
## Descrição da vaga

Realizar os alinhamentos necessários com o time para que todo o trabalho esteja definido
Analise, desenvolvimento e suporte de aplicativos utilizando React.js

## Local

Atuar em Tatuapé - São Paulo - SP
Possibilidade de 2 dias(por semana) remotos após período de experiência

## Requisitos
Experiência com HTML5, CSS3 e pré-processadores.
Experiência no desenvolvimento com javascript [ES5, ES6].
Experiência com aplicações SPA.
Experiência com APIs Restful.
Experiência em React.js.
Experiência em Redux.
Experiência em Bootstrap.
Experiência com Git.
Capacidade de trabalhar em equipe (pró-ativo).

Procuramos pessoas:
Mindset ágil, Aceitar feedbacks sem mimimi, Sentimento de dono.

**Obrigatórios:**
1 ano de experiência com React.js

**Desejáveis:**
Experiência com Angular

**Diferenciais:**
projetos opensource

## Contratação

PJ a combinar

## Como se candidatar

Enviar currículo ou link do perfil para recrutamento@idev.com.br indicando pretensão de ganho PJ com o assunto Front-End Developer React

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias. 

## Labels

- PJ
- Pleno
- Sao Paulo
- Tatuape

**Comment by manzolirch** [comment]
**Aceitar feedbacks sem mimimi, Sentimento de dono.**
