### ISSUE TITLE
[Rio de Janeiro] Front-End Developer na [STAYS]

### ISSUE THREAD

**Issue by fsilvaco** [frontendbr/vagas#1893]
## Descrição da vaga

Você tem interesse de ajudar pequenos Grupos e indivíduos a melhorar sua presença online? Você tem afinidade para novas tecnologias e possui experiência básica ou avançada em desenvolvimento Front-end? **HTML, CSS, Javascript, Bootstrap e jQuery** estão na sua base de
conhecimento?

Tem facilidade em se comunicar e ajudar?

Quer fazer parte de uma equipe internacional com uma vibe de startup?

Junte-se à Equipe [Stays™](http://stays.net/)!

## Local

Escritório, Rio de Janeiro - Copacabana

## Benefícios

- Flexibilidade de horário
- R$ 900,00 + Vale transporte
- Carga horária semanal de 30 horas

## Requisitos

**Obrigatórios:**
- Ensino superior cursando em Ciência da Computação ou áreas relacionadas.
- Conhecimentos em HTML, CSS, Javascript (Bootstrap e jQuery);
- Facilidade em aprender e ajudar; 
- Inglês intermediário 

**Diferenciais:**
- Se comunicar bem em Inglês e Espanhol 

## Contratação

Estágio 6h

## Nossa empresa

[Stays™](http://stays.net/) é um sistema online com design intuitivo e extremamente adaptável para todos o modelos de negócio de aluguel de temporada. Nele, é possível gerir e automatizar tarefas de vendas, marketing, CRM, gestão de canais, faxina, manutenção, check-in / check-out, inspeção da propriedade, gestão de inventário, comunicação interna, gestão de tarefas da equipe, finanças, controladoria, preços, promoções, ferramentas de marketing e administração em geral.

## Como se candidatar

Por favor envie um email para design@stays.com.br com seu CV anexado - enviar no assunto: Vaga - Estagiário Front-end

## Labels

- Alocado
- Estágio

**Comment by igorpinhh** [comment]
a partir de qual período da faculdade?

**Comment by fsilvaco** [comment]
Estamos bem flexíveis em relação à isso

**Comment by Josemaralves** [comment]
Enviado =)
