### ISSUE TITLE
[Florianópolis/SC] Front-End Developer Pleno (React) na iTER

### ISSUE THREAD

**Issue by pedronauck** [frontendbr/vagas#1894]
## Descrição da vaga

Buscamos um desenvolvedor frontend de nível pleno, que já tenho um bom background em criação de aplicações Javascript e boa familiaridade com ReactJS. Este desenvolvedor irá atuar diretamente no desenvolvimento da nossa plataforma de rastreamento e ajudando a criar soluções na área de IOT e Telemetria.

## Local

Escritório no bairro Kobrasol, São José, SC
*(cidade no lado continente da grande Florianópolis Florianópolis)*

## Benefícios

- PJ com benefícios diferenciados. 
- Pagamento mensal, sem desconto de feriados. 
- Férias coletivas no final do ano sem descontos.
- Raramente são necessárias horas extras e quando há necessidade, elas são obviamente remuneradas. Nada de pizza em troca de código 😉.

#### Diferenciais

- Empresa com foco **REAL** em tecnologia, sempre optando por inovação e trabalhar com tecnologias novas, dando liberdade para estudo e aplicação nos produtos internos.
- Flexibilidade de horários
- Ganha um monitor ultra-wide de 25" da LG para trabalhar
- Ambiente livre onde cada um sabe das suas responsabilidades com horários flexíveis.
- Frigobar sempre cheio de Redbull
- Café moído na hora e frutas pra dar aquele up.

*ps: Não temos escorregador de bolinhas nem pebolim.*

## Requisitos

**Obrigatórios:**
– Conhecimento sólido em Javascript, HTML e CSS
– Familiaridade com APIs RESTful
– Experiência com ReactJS

**Diferenciais:**
– Testes unitarios com Jest
– Conhecimento com UI e UX para web

## Contratação

- PJ a combinar in-loco.
- Range de salário entre 4-6k.

## Nossa empresa

A iTER desenvolve produtos na área de rastreamento, telemetria e IoT. 
Se você se interessa em dinamismo, novas tecnologias, possibilidade de criação e participação real no desenvolvimento dos produtos, esse é o lugar certo. 

## Como se candidatar

- Por favor envie um email para **queroserfrontna@iter.sc** com seu CV anexado
- Enviar no assunto: Vaga FrontEnd

## Labels

- Alocado
- PJ
- Pleno

**Comment by ReactGirl** [comment]
Excelente job description!
