### ISSUE TITLE
[Salvador] Front-End Developer / Estágio Front-End na Cronapp

### ISSUE THREAD

**Issue by lucazweb** [frontendbr/vagas#1895]
## Descrição da vaga

Se você tem paixão pelo universo Front-End, muita vontade de evoluir, é capaz de montar layouts de maneira ágil e trabalhar em equipe, essa vaga é para você!

## Local

Escritório, Salvador - Itaigara

## Benefícios

- Plano de saúde
- Vale alimentação ou refeição
- Vale transporte
- Conta Cronapp

#### Diferenciais

- Conta Cronapp
- Videogame
- Horário flexível

## Requisitos

**Obrigatórios:**
- Mínimo de 2 anos com HTML5 / CSS / Bootstrap / Javascript 
- Ser capaz de montar um layout responsivo
- Angular JS / REST API
- GIT

**Desejáveis:**
- Flexbox e/ou Grid Layout
- React / Angular 2+

**Diferenciais:**
- Vivência em metodologias ágeis 

## Contratação

CLT  - Salário a combinar

## Nossa empresa

**Sobre a Cronapp**
Somos uma startup que nasceu no Brasil e que deseja transformar a experiência do desenvolvimento de softwares. Nossa plataforma na nuvem Cronapp dá a liberdade para desenvolver de forma ágil, fácil e produtiva.  Conheça mais acessando: [https://www.cronapp.io](https://www.cronapp.io)

## Como se candidatar

Por favor envie um email para **lucas.santos@cronapp.io** com seu CV anexado - enviar no assunto: Vaga Front-End Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após envio do e-mail.

## Labels

- Alocado
- CLT
- Estágio
- Júnior
- Pleno

**Comment by danielswater** [comment]
Se puder ser senior, remoto aceito :)

**Comment by JoaoMarcosSiCar** [comment]
tenho interesse no estágio =), seleções abertas ainda?
