### ISSUE TITLE
[Remoto] Desenvolvedor Front-End na Laborit (React, Tests, Pleno)

### ISSUE THREAD

**Issue by fidelisrafael** [frontendbr/vagas#1896]
## Descrição da vaga

![Laborit Logo](https://i.imgur.com/CnRKimm.png)

Estamos procurando um desenvolvedor front-end experiente que possa nos ajudar a construir os melhores produtos do Brasil, e do mundo!

A pessoa para essa vaga poderá também trabalhar em projetos já existentes, porém estamos buscando também profissionais para iniciarmos mais alguns projetos durante o ano, incluindo uma startup que estamos construindo atualmente.  

#### Atenção:

Por favor, pedimos que você leia esse [Job Description + Teste para a vaga](https://gitlab.com/snippets/1837383). 

Essa postagem aqui é apenas para divulgar a vaga, as demais informações e as instruções de como aplicar-se para o teste encontram-se no snippet do Gitlab acima.

## Local

- Trabalho 100% Remoto
- Temos escritório em São Paulo, na We Work Berrini para eventuais reuniões.

## Forma de trabalho

O nosso modelo de contratação é PJ, porém um dos beneficios é que temos uma operação 100% remota. Nossa cultura de trabalho é focada não apenas na tecnologia e nos resultados, mas também nas pessoas, presamos por um ambiente amigável, colaborativo e aberto a novas idéias e propenso para o crescimento profissional e pessoal.

Utilizamos uma ferramenta chamada "Sococo" para mantermos todo o time conectado durante o dia. Assim podemos conversar por voz/audio e fazer pair-programmings juntos compartilhando multiplas telas ao mesmo tempo ;)

![laborit-sococo](https://user-images.githubusercontent.com/1542608/54921486-a472ae80-4ee4-11e9-90d4-cf55db969a44.png)

## Requisitos

**Obrigatórios:**

- Javascript/ES6
- ReactJS (component's life-cycle, props, state, VirtualDOM, etc)
- Testes de software (unit e integration tests)

**Desejáveis:**

- Bons conhecimentos de WebAPIs como: `DOM`, `Storage`, `XMLHTTPRequest`, `WebSocket`, etc.
- Conhecimentos de Node.js

**Diferenciais:**

- Entender o `Event Loop` do Javascript/Node.js
- Projetos Open-Source
- Conhecimentos de outras linguagens(Ruby, C#, Python)
- Acessibilidade

### Teste

O teste para essa vaga pode ser encontrado no nosso [Job Description + Teste para a vaga](https://gitlab.com/snippets/1837383). 

Você deverá construir um sisteminha baseado no seguinte mockup:

![Laborit Front-end test](https://i.imgur.com/OLmA6ik.png)

## Contratação

Nosso modelo de contratação é PJ.

## Nossa empresa

Laborit é uma consultoria de produtos baseada em São Paulo. Nós desenvolvemos produtos creativos que solucionam problemas e ajudam nossos clientes crescerem. Nós nos importamos profundamente sobre user-experience, e sobre como entregar soluções de engenharia que sejam simples, porém efetivas.

## Como se candidatar

Por favor envie um email para `recrutamento@laborit.com.br` com seu CV anexado - enviar no assunto: "Vaga front-end React"

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após cada processo.
E-mail para contato em caso de não haver resposta:  `recrutamento@laborit.com.br`

## Labels

- React
- Pleno
- Remoto

**Comment by ReactGirl** [comment]
Legal esse "sisteminha" que voces pediram pra trabalhar de graça sem nem olhar o github dos candidatos.

**Comment by ReactGirl** [comment]
Caso seja feito o "sisteminha", e voces considerem que nao é o suficiente. Voces forneceriam algum tipo de comentario tecnico a respeito da razao do decline?

**Comment by pedromuraki** [comment]
@fidelisrafael a vaga ainda está aberta?

**Comment by fidelisrafael** [comment]
@pedromuraki Opa cara! Finalizamos esse processo nesse momento, mas se tiver interesse em ficar no nosso banco de dados pode enviar um e-mail para `recrutamento@laborit.com.br`

Valeu, e vou fechar aqui! Há braços o/
