### ISSUE TITLE
[Uberlândia - MG] Front-End Developer na SOFTBOX

### ISSUE THREAD

**Issue by evellyncastro** [frontendbr/vagas#1897]
## Descrição da vaga

Atuar na codificação do sistema na tecnologia NodeJs conforme arquitetura e padrão de desenvolvimento definidos.

## Local

Uberlândia -MG (alocado)

## Benefícios

- Plano de saúde
- Plano Odontológico
- Seguro de vida
- Vale refeição
- Auxilio combustível
- Auxílio creche

#### Diferenciais

- 1h30 horas de almoço
- Hora Soft Mensal (Happy Hour)
- Ted Box (Compartilhamento de conhecimento)
- Sala de jogos
- Horário Flexível

## Requisitos

**Obrigatórios:**
- Proficiência em NodeJS, GIT, Javascript e Docker;
- Conhecimentos sólidos em Design Patterns; 
- Automatização de builds/ tooling (NPM, Webpack);
- Experiência com testes automatizado e unitários; 
- Conhecimentos práticos em banco de dados NoSQL e no ambiente AWS.

**Desejáveis:**
- Experiência com desenvolvimento utilizando TDD e BDD;
- Conhecimentos em utilização de Node.js em Cluster;
- Conhecimentos em Gitflow;
- Experiência em criação de ambientes de desenvolvimento utilizando docker compose.

**Diferenciais:**
- Projetos Magalu

## Contratação

CLT

## Nossa empresa

A 13 anos no mercado a Softbox foi constituída para atender as demandas de consultoria e realização de projetos de TI.

Atualmente a empresa oferece produtos de alta tecnologia bem como consultoria e desenvolvimento de soluções de TI para grande empresas. Com atuação nacional, a Softbox está situada em Uberlândia/MG e São Paulo/SP.

Recentemente o Luiza Labs adquiriu a Softbox por conta do nosso know-how para o mercado varejista e isso nos trouxe um grande desafio de digitalizar o Brasil.     

## Como se candidatar

Por favor envie um e-mail para talentoshumanos@softbox.com.br ou pelo nosso site https://softbox.com.br/oportunidades/ , colocar no assunto: Vaga NodeJS

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após recebimento dos perfis.

## Labels

- Alocado
- CLT
- Pleno
- Sênior

**Comment by alessandrocode09** [comment]
A vaga seria para Back end não ? Esta área é somente para vagas front end.

**Comment by marlonmleite** [comment]
@alessandrocode09 acaba que o pessoal atua em Node e também pode atuar no Front. Mas existem também vagas de front e caso o pessoal verifique a tendência de front ele segue o processo como front também.

**Comment by alessandrocode09** [comment]
@marlonmleite ah sim, falando desse jeito faz todo sentindo mesmo. Ta certo, mas é pq quando vejo vaga de front aqui, tem sempre os frameworks de front e nessa não tem nada, então pensei mais que seria back mesmo

**Comment by MrS4w** [comment]
> @alessandrocode09 acaba que o pessoal atua em Node e também pode atuar no Front. Mas existem também vagas de front e caso o pessoal verifique a tendência de front ele segue o processo como front também.
<br>
Então @alessandrocode09 favor colocar no título Full-stack Developer :wink:

**Comment by alessandrocode09** [comment]
@MrS4w exatamente!!!!
