### ISSUE TITLE
[Joinville/SC ou Remoto] Full-Stack Developer na Coderockr

### ISSUE THREAD

**Issue by RaonyMarcondes** [frontendbr/vagas#1898]
## Descrição da vaga

O candidato(a) fará parte de uma equipe multidisciplinar. Onde todos colaboram com postura entusiasta, paixão por tecnologia e inovação, e ampla experiência em desenvolvimento Web e Mobile.

### Esperamos que você:

- Seja pró-ativo(a), analisando e compreendendo os impactos e reais necessidades por trás das suas entregas;
- Tenha responsabilidade pelo que você produz e entrega. (Ownership mindset);
- Acredite que pode obter melhores resultados trabalhando em equipe;
- Saiba se comunicar abertamente, participando de debates saudáveis, trazendo ideias que contribuam para o seu sucesso, e o da equipe;
- Tenha capacidade de entender Produto & Negócios. Nosso objetivo maior sempre é a entrega de valor, indo muito além de apenas criar um código bonito;
- Seja versátil: Você entende como todas as peças se conectam (front-end, back-end, database, camadas de rede, etc) e como isso impacta a performance do seu código/aplicação);
- Seja capaz avaliar e aprender sobre novas tecnologias e ferramentas.

## Local

Av Henrique Meyer, 40, Centro, Joinville - Santa Catarina / **Remoto**

## Benefícios / Diferenciais
- **Plano de Saúde:** Unimed Nacional 100% de um plano de 50% de co-participação;
- **Seguro: 50%** de um seguro de vida, caso optado;
- **Horário flexível:** 40 horas semanais, com flexibilidade perante acordo prévio entre a equipe;
- **Plano de Carreira:** publico e transparente;
- **Bônus Anual:** Baseado no impacto de suas contribuições;
- **Aprendizado:** Evento interno trimestral para apresentação de palestras, hackathons e ações sociais;
- **Cultura:** Eventos internos de confraternização;
- **Budget para Educação:** R$ 2.000/ano para serem usados em cursos, palestras, ou livros.

## Requisitos

**Obrigatórios:**
- Utilizar conceitos do GitHub, branching, issues, pull-requests, etc;
- Javascript / CSS / HTML;
- PHP orientado a objetos;
- Noções de GO;
- Noções de React e/ou React Native;
- Modelagem em bancos de dados SQL / NoSQL / Redis;
- Conhecimento em TDD, Clean Code e Design Patterns;
- Capacidade de criar Micro-serviços escalonáveis horizontalmente, baseados em técnicas de programação funcional e arquitetura hexagonal.

**Desejáveis:**
- Noções de Bash script;
- Noções de virtualização e containers (Docker);
- Conhecimento em aplicações orientadas a componentes;
- Conhecimento em Single Page Apps integrados com API RESTful;
- Experiência com serviços AWS (EC2, S3);
- Ser familiarizado com o terminal e aplicações em linha de comando.

**Diferenciais:**
- Projetos OpenSource

## Contratação

CLT a combinar, com base em nosso plano de carreiras: https://github.com/Coderockr/carreira

## Nossa empresa

A Coderockr acredita que o desenvolvimento de sistemas e aplicativos é uma arte, que deve ser feita com paixão e dedicação. Bons programadores são únicos, assim como estrelas no mundo do rock, e é nesse ritmo que fazemos aplicações Web e Mobile.

Saiba mais: www.coderockr.com

## Como se candidatar

Por favor candidate-se pela plataforma: http://smrtr.io/-Wx6

Dica para elaborar seu Currículo: https://blog.coderockr.com/posts/2017/como-montar-um-bom-curriculo-para-desenvolvedores-e-designers/

## Tempo médio de feedbacks

Costumamos enviar feedbacks em no máximo 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: jobs@coderockr.com

## Labels

- Alocado
- CLT
- Pleno
- Remoto
- [Santa Catarina]

**Comment by adeonir** [comment]
@RaonyMarcondes alguma oportunidade para junior?
