### ISSUE TITLE
[Salvador] Estágio Front-End

### ISSUE THREAD

**Issue by cbfranca** [frontendbr/vagas#19]
## Descrição da vaga

Você se considera uma pessoa inovadora e empreendedora? Nosso Programa de desenvolvimento de talentos foi feito para jovens questionadores, com energia e ambição por construir. Se você sonha em fazer parte de uma empresa de tecnologia, em que o futuro é imprevisível e cheio de realizações, nossa proposta de desenvolvimento é para você.
## Local

Escritório, Salvador,  Bahia.
## Benefícios
- Bolsa auxílio inicial de R$1000,00
- Auxílio transporte
- Ambiente descontraído
- Dress code informal
- `while(true) { cooffe++; }`

## Requisitos

**Obrigatórios:**
- Conhecimentos sólidos de HTML, CSS e JS 
- Capacidade analítica
- Apaixonado(a) por internet, curioso e que seja atento a detalhes.
- Ler em inglês

**Desejáveis:**
- Noções de orientação a objetos

**Diferenciais:**
- projetos opensource
-  Polymer
- Pré-processadores de CSS (LESS, SASS, STYLUS)
- GIT
- Task runners (Grunt/Gulp)
- Jogar fifa 
- Tocar um instrumento  =)

## Contratação

Estágio
## Everest TI

A Everest TI é uma `fintech` que surgiu no final de 2012 com a missão de Mudar a forma com que o mercado financeiro utiliza tecnologia. Desenvolvemos soluções B2C tendo como pilares dos nossos produtos, `Desempenho`, `Qualidade` , `Usabilidade` e a `Experiência do usuário`.
## Como se candidatar

Envie um e-mail para `mateus.lopes@everestti.com.br` informando `estágio front end` no assunto do e-mail e com as informações necessárias para te conhecermos melhor (currículo, Linkedin, portfolio, site pessoal, Github, Stackoverflow, Codepen, Twitter, Facebook, Google Plus...)

**Comment by urameshibr** [comment]
Oi Cleidison, tudo bem? Tem vaga pra remoto também? Me qualifico pra
vaga.Estou em Olímpia/SP.

Em 26 de fevereiro de 2016 14:47, Cleidson França <notifications@github.com>
escreveu:

> Descrição da vaga
>
> Você se considera uma pessoa inovadora e empreendedora? Nosso Programa de
> desenvolvimento de talentos foi feito para jovens questionadores, com
> energia e ambição por construir. Se você sonha em fazer parte de uma
> empresa de tecnologia, em que o futuro é imprevisível e cheio de
> realizações, nossa proposta de desenvolvimento é para você.
> Local
>
> Escritório, Salvador, Bahia.
> Benefícios
>
>    - Bolsa auxílio inicial de R$800,00
>    - Plano de carreira
>    - Auxílio transporte
>    - Ticket refeição
>    - Ambiente descontraído
>    - Dress code informal
>    - while(true) { cooffe++; }
>
> Requisitos
>
> *Obrigatórios:*
>
>    - Conhecimentos sólidos de HTML, CSS e JS-
>    - Autonomia
>    - Capacidade analítica
>    - Apaixonado(a) por internet, curioso e que seja atento a detalhes.
>    - Ler em inglês
>
> *Desejáveis:*
>
>    - Noções de orientação a objetos
>    - Noções de C# ou Java
>
> *Diferenciais:*
>
>    - projetos opensource
>    - Angular JS
>    - Pré-processadores de CSS (LESS, SASS, STYLUS)
>    - GIT
>    - Task runners (Grunt/Gulp)
>    - Jogar fifa
>    - Tocar um instrumento =)
>
> Contratação
>
> Estágio
> Nossa empresa
>
> [image: Azimut IT]
> <https://camo.githubusercontent.com/c91f14fcd6980cb0b56a32c7fce7a0c0a29c357f/687474703a2f2f66756e64732e617a696d757469742e636f6d2f4173736574732f696d672f6c6f676f5f617a696d757469742e706e67>
> Azimut
>
> A Azimut é uma das 5 maiores gestoras de recursos da Europa. Com mais de
> R$ 116 bilhões em ativos sob gestão, a empresa é listada na Bolsa de
> Valores de Milão desde 2004 e possui um valor de mercado de R$ 11 bilhões.
> Conheça mais sobre a Azimut Internacional
> <https://www.youtube.com/watch?v=MLcJ0Mt8ujY> e sobre a Azimut Brasil
> <https://www.youtube.com/watch?v=3Uerl9Bzmxo>.
> Azimut IT
>
> A Azimut IT é a área de tecnologia responsável pelo desenvolvimento de
> toda base tecnológica utilizada pela Azimut no Brasil.
> Como se candidatar
>
> Envie um e-mail para cleidson.franca@azfuturainvest.com.br informando estágio
> front end no assunto do e-mail e com as informações necessárias para te
> conhecermos melhor (currículo, Linkedin, portfolio, site pessoal, Github,
> Stackoverflow, Codepen, Twitter, Facebook, Google Plus...)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frontendbr/vagas/issues/19>.
>



-- 
Lucas Rodrigues
*Analista de Suporte Técnico e **Desenvolvedor de Software*
*Titan Sistemas de Automação Comercial*

Claro: (17) 9-9224-0632
Skype: lucas.opensource@hotmail.com

**Comment by cbfranca** [comment]
Olá @urameshibr, infelizmente ainda não estamos funcionando com trabalho 100% remoto.

**Comment by urameshibr** [comment]
Tudo bem Cleidson, obrigado pelo feedback.

2016-02-26 16:47 GMT-03:00 Cleidson França <notifications@github.com>:

> Olá @urameshibr <https://github.com/urameshibr>, infelizmente ainda não
> estamos funcionando com trabalho 100% remoto.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frontendbr/vagas/issues/19#issuecomment-189450394>.
>



-- 
Lucas Rodrigues
*Analista de Suporte Técnico e **Desenvolvedor de Software*
*Titan Sistemas de Automação Comercial*

Claro: (17) 9-9224-0632
Skype: lucas.opensource@hotmail.com

**Comment by LFeh** [comment]
A vaga foi preenchida? @cbfranca

**Comment by cbfranca** [comment]
Ainda não @LFeh

**Comment by LFeh** [comment]
Tranquilo,vou dar mais uma divulgada.

**Comment by ytalobessa** [comment]
Se fizer trabalho remoto eu tenho interesse.

Eu toco violão, baixo e bateria ;) rsrsrsrs

**Comment by brncavalcante** [comment]
Remoto também tenho interesse.

Sou o melhor jogador de FIFA que conheço :) e humilde, como dá pra perceber.

**Comment by victorferreira** [comment]
Essa vaga ainda está aberta?

**Comment by cbfranca** [comment]
@victorferreira não, já está fechada. Porém é possível que tenha em breve outra vaga, pra outra empresa que faço parte. Fica ligado aqui.

**Comment by victorferreira** [comment]
@cbfranca Obrigado. 😄

**Comment by cbfranca** [comment]
@victorferreira ainda está interessado na vaga?

**Comment by RafaelLee** [comment]
Eu tenho interesse.
:D

**Comment by klarkc** [comment]
Se aparecer vagar pra junior ou pleno me avisa

**Comment by cbfranca** [comment]
@RafaelLee manda seu currículo.

**Comment by GregoryGoncalves** [comment]
Gostaria de saber mais sobre a vaga (caso ainda esteja aberta). Posso usar o e-mail `mateus.lopes@everestti.com.br` mesmo?

**Comment by cbfranca** [comment]
Olá @GregoryGoncalves. No momento a vaga já está preenchida. Vou guardar seu contato pra futuras oportunidades. Abs.
