### ISSUE TITLE
[Recife] Desenvolvedor(a) full-stack 

### ISSUE THREAD

**Issue by robnff** [frontendbr/vagas#190]
## Descrição da vaga

Projetos com clientes internacionais usando Python e Javascript. Oportunidade de resolver projetos desafiadores usando Django, React e SASS. Assim como trabalhar com grande incentivo para contribuir com comunidades OpenSource.

## Local

Escritório, Ilha do Leite, Recife - Pernamabuco

## Benefícios

- Divisão nos lucros da empresa
- Seguro Saúde
- Plano Odontológico
- Vale transporte/estacionamento
- Ticket Alimentação
- Café/Chá infinito

## Requisitos

**Obrigatórios:**
- Python
- Javascript
- Inglês fluente
- Presencial

**Desejáveis:**
- Contribuições OpenSource
- Experiência em gerenciamento de projetos
- HTML/SASS

**Diferenciais:**
- React JS
- Django

## Contratação

R$5000,00 a R$7000,00, dependendo do nível profissional

## Nossa empresa

Nós da Vinta somos um time habilidoso de amantes da tecnologia, voltados a oferecer consultoria nível CTO para projetos envolvendo Django. Nós oferecemos serviços tanto para Frontend quanto para Backend, trabalhando com todos os estágios de desenvolvimento de produto. Desde criar um produto do zero com nosso cliente até ajudar times de TI já existentes. Muitos de nós temos background em Startups e somos especialistas em APIs, com palestras em várias conferências de Python/Django.

## Como se candidatar

Envie GITHUB e currículo para jobs+2017@vinta.com.br  - enviar no assunto: Vaga Dev JS

**Comment by LFeh** [comment]
Quais as labels @robnff ?
