### ISSUE TITLE
[Belo Horizonte] Front-End Developer Angular na [SYS10]

### ISSUE THREAD

**Issue by chgsantos** [frontendbr/vagas#1901]
### Descrição
Trabalhar no desenvolvimento de sistemas em Angular com APIs REST.
Atualmente estamos trabalhando em uma plataforma de marketplace e em um grande sistema para a área educacional.

### Requisitos
Angular ou React
HTML / SASS
Git

### Diferencial
R / SAS
Sql Server / PostgreSQL
iOS / Android / React Native
.NET / PHP
Adobe XD

### Benefícios
VT
VR
Plano de saúde Bradesco Nacional
Horário flexível
Ambiente descontraído
Lanches

### Modalidade
CLT ou PJ
Júnior ou Pleno

### Local
SYS10 - Av Antônio Abrahão Caram 664, Sala 104
Pampulha - Belo Horizonte
https://goo.gl/maps/rj3aaboApcm

### Como candidatar
Enviar o CV para rh@sys10.com.br

### Labels
Angular, React, HTML, SASS, REST

**Comment by danielswater** [comment]
Aceita remoto?

**Comment by alessandrocode09** [comment]
Enviado!

**Comment by chgsantos** [comment]
> Aceita remoto?

Sim. Me manda seu currículo e onde está localizado que a gente conversa.

**Comment by chgsantos** [comment]
Vaga ainda aberta.

**Comment by chgsantos** [comment]
Vaga suspensa por enquanto, temos uma boa quantidade de currículos recebidos por aqui.
