### ISSUE TITLE
[Florianópolis] Desenvolvedor React na RedeVistorias

### ISSUE THREAD

**Issue by duylecampos** [frontendbr/vagas#1902]
## Descrição da vaga

Estamos em busca de um dev front-end React. Trabalhamos sempre com as versões mais recentes e nos forçamos a utilizar todo o potencial da ferramenta. Você precisa ter conhecimento de JS, CSS, HTML, design responsivo, e por último, mas não menos importante, estar sempre atualizado.

## Local

Matriz da Rede Vistorias em Florianópolis / SC – Itacorubi

## Benefícios

- VR
- Plano de saúde
- Flexibilidade de horário
- Frutas todas as semanas
- Ambiente de trabalho informal

## Requisitos

**Obrigatórios:**
- React, Redux
- JavaScript
- HTML5
- CSS3
- Consumo de APIs REST
- Git

**Diferenciais:**
- Conhecimento em PWA
- Conhecimento em Docker
- Vontade de aprender e atuar em outras tecnologias

## Contratação
CLT

## Nossa empresa

Somos uma startup com pouco mais de 2 anos de existência, possuímos unidades em mais de 40 cidades por todo o Brasil resolvendo problemas de milhares de pessoas mensalmente. Nosso core business é resolver o maior problema de muitas pessoas que alugam imóveis, a bendita vistoria, para isso contamos com vistoriadores qualificados por todo o Brasil e utilizamos a tecnologia para desenvolver soluções que auxiliem e facilitem a vida de todas pessoas envolvidas nesse processo.

## Nossa equipe

Nossa equipe é formada por desenvolvedores Backend, Frontend e Mobile. Prezamos muito pela autonomia do desenvolvedor e por inovação, estamos sempre estudando/experimentando novas tecnologias e o desenvolvedor é importantíssimo no desenvolvimento dos nossos produtos, sempre possuindo uma grande atuação na especificação das tecnologias e funcionamento.

## Nossa stack

Trabalhamos sempre com microservices possuindo dezenas deles na nuvem, nosso provider de serviço principal é a AWS, utilizamos diversos serviços deles como EC2, S3 e RDS. Possuímos uma stack bem variada, com algumas coisas que estamos diminuindo o uso e outras aumentando. As principais tecnologias que utilizamos aqui são: Python, Kotlin, PHP, ReactJS, ObjectiveC, Swift, Docker. No frontend, utilizamos React, Redux, Router, MaterialUI, HTML5 e CSS3, tentamos sempre utilizar a última versão estável do React.

## Como se candidatar

Para se candidatar envie seu curriculo pela nossa pagina de carreiras https://jobs.kenoby.com/oportunidadesrvexterno/

## Labels

- Alocado
- CLT
- Júnior
- Pleno

**Comment by leonardorpr** [comment]
Opa, tudo bem? Há possibilidade de trabalho remoto full-time?

**Comment by duylecampos** [comment]
> Opa, tudo bem? Há possibilidade de trabalho remoto full-time?

Infelizmente não.
