### ISSUE TITLE
[São Paulo/SP] Developer Front-End/PHP PL/SR na Royalpixel

### ISSUE THREAD

**Issue by amanda-royalpixel** [frontendbr/vagas#1904]
A Royal é uma empresa voltada para a criação e desenvolvimento de conteúdo digital. Combinamos storytelling e tecnologia no desenvolvimento de projetos para algumas das maiores marcas do país (Nike, Coca-Cola, Guaraná Antarctica, Siemens, LG, Motorola). 
Nossa equipe está em busca de um(a) programador(a) PHP/Front-End, pleno(a) ou sênior, especializado(a) em PHP Laravel, com experiência significativa comprovada na área.
O que esperamos do(a) candidato(a):
- Compromisso com prazos e qualidade;
- Capacidade de propor soluções aos desafios do dia a dia;
- Estar disponível para resolver problemas, bugs e questões de compatibilidade de forma ágil;
- Capacidade de autodesenvolvimento;
- Facilidade de aprendizado;
- Planejar, organizar e reportar atividades.

Requisitos
- Bom domínio php laravel
- Domínio de wordpress
- Desenvolvimento web
- Conhecimento de web standards (tableless, html, css, semântica, crossbrowser, etc.)
- Conhecimento em javascript e animações em jquery
- Conhecimento de bancos de dados
- Conhecimento em aws, linux e infraestrutura de servidores
- Controle de versão git
- Experiência significativa comprovada na área

Desejável
- Ruby on rails
- Inglês intermediário

Benefícios
- 20 dias úteis de férias remuneradas (após 1 ano de contrato)
- 3 dias úteis de folga por ano

A vaga é presencial. O regime de contratação é PJ. A faixa salarial é de R$ 7 mil a 8 mil. Interessados devem enviar currículo com portfólio para vagas@royalpixel.tv

**Comment by LucasHiago** [comment]
Existe a possibilidade de ser remoto?

Em qua, 27 de mar de 2019 às 11:02, amanda-royalpixel <
notifications@github.com> escreveu:

**Comment by amanda-royalpixel** [comment]
Oi, Lucas! Obrigada por responder. Infelizmente essa vaga é presencial.
