### ISSUE TITLE
[Blumenau/SC] Front-End Developer na Serasa Consumidor

### ISSUE THREAD

**Issue by SelecaoSerasaConsumidor** [frontendbr/vagas#1906]
**Você quer trabalhar em um ambiente com tecnologia de ponta e uma equipe altamente capacitada para mudar a vida financeira do consumidor brasileiro?**

Já somos uma das maiores empresas digitais do mercado financeiro e estamos desenvolvendo produtos e serviços que vão mudar a forma como o brasileiro se relaciona com o dinheiro.

Somos um time com brilhos nos olhos, multidisciplinar e com autonomia para propor ideias. Se você é apaixonado pelas transformações do mundo digital, não tem medo de assumir riscos e quer sentir-se “dono do negócio”, vem trabalhar com a gente!

### O que buscamos?

É imprescindível experiência com Javascript (ECMAScript 2015+), HTML, CSS, REST APIs, React, Angular e Testes (Jasmine, Jest, Mocha, Chai ou outros). Experiência avançada em versionamento de código. Vivência com Design Responsivo e Mobile First. Atuação com produtos 100% digitais. Inglês técnico.

### O que pode diferenciar você?

Experiência com MarkoJS. Atuação em ambiente de startup e ambiente 100% digital. Experiência com arquitetura e desenvolvimento Cloud (AWS, Google Cloud). Experiência profissional em ambiente ágil.

### Oferecemos:

- Produtos com a possibilidade de fazer história e deixar legado!
- Ambiente desafiador e High Performance
- Times multidisciplinares e Multiculturais
- Pacote salarial atrativo;
- Pacote de benefícios;
- PLR anual; 
- Previdência privada;

**Comment by acamilass** [comment]
É para todos os níveis?

**Comment by luqezman** [comment]
Aceitam tech lead e ou senior?

**Comment by luqezman** [comment]
Remote?

**Comment by Mendrone** [comment]
@SelecaoSerasaConsumidor Preciso que vocês incluam quais labels eu devo utilizar na vaga pra facilitar a navegação e filtro dos usuários. Além de nos ajudar a manter o repositório organizado. 

A vaga é presencial ou remoto? CLT ou PJ? Junior, pleno e/ou sênior?

**Comment by fabiomirandaa** [comment]
E entra em contato por onde?

**Comment by SelecaoSerasaConsumidor** [comment]
Boa Tarde Pessoal!

@acamilass, respondendo ao seu questionamento, entraremos em contato contigo através do LinkedIn. Muito obrigado pelo interesse.

@luqezman aceitamos sim Tech Lead, porém a vaga se trata de React Developer, então vai por a mão na massa. A vaga é presencial em Blumenau-SC

@fabiomirandaa iremos entrar em contato contigo através do LinkedIn, muito obrigado pelo interesse.

Contato coordenador da vaga: https://www.linkedin.com/in/alexandre-verardo-dedinho-csm%C2%AE-01406169/

**Comment by SelecaoSerasaConsumidor** [comment]
> @SelecaoSerasaConsumidor Preciso que vocês incluam quais labels eu devo utilizar na vaga pra facilitar a navegação e filtro dos usuários. Além de nos ajudar a manter o repositório organizado.
> 
> A vaga é presencial ou remoto? CLT ou PJ? Junior, pleno e/ou sênior? Chutei pleno e sênior baseado nos requisitos.

- A vaga é presencial;
- CLT;
- Pleno e Sênior;

**Comment by patrick-narciso** [comment]
Como faço para me candidatar?

**Comment by SelecaoSerasaConsumidor** [comment]
@patrick-narciso já aceitei sua solicitação via linkedIn. Muito obrigado pelo interesse.

**Comment by SelecaoSerasaConsumidor** [comment]
> @SelecaoSerasaConsumidor Preciso que vocês incluam quais labels eu devo utilizar na vaga pra facilitar a navegação e filtro dos usuários. Além de nos ajudar a manter o repositório organizado.
> 
> A vaga é presencial ou remoto? CLT ou PJ? Junior, pleno e/ou sênior? Chutei pleno e sênior baseado nos requisitos.

@Mendrone poderia colocar também as seguintes labels [Alocado], [CLT], [Santa Catarina]?

**Comment by SelecaoSerasaConsumidor** [comment]
Gostaríamos de agradecer muito ao canal e a todos os participantes e também reportar que os dois escolhidos para as vagas foram provenientes desse canal. Nosso muito obrigado ao frontendbr/vagas

**Comment by felipefialho** [comment]
Que foda!
