### ISSUE TITLE
[Remoto ou Fortaleza] Frontend Developer (React Native) na Agenda Edu

### ISSUE THREAD

**Issue by gurgelrenan** [frontendbr/vagas#1909]
## Descrição da vaga

Buscamos por um desenvolvedor(a) frontend, nível pleno, que tenha um bom conhecimento de Javascript e boa familiaridade com React Native. Você irá atuar na reformulação de nosso app, bem como ajudar na evolução de nossa arquitetura. Nosso app, é a solução de comunicação de mais de um milhão de usuários que acompanham diariamente a rotina escolar por meio dele. Assim, você estará impactando diretamente na jornada educacional de escolas, alunos, famílias e educadores. Venha fazer parte dessa revolução!

## Local

Remoto ou Escritório, Fortaleza - Dionísio Torres 

## Benefícios
* P.J com benefícios diferenciados
* Pagamento mensal, sem desconto de feriados
* Férias coletivas no final do ano sem descontos

#### Diferenciais
* Flexibilidade combinada de horários
* Ambiente informal onde cada um sabe das suas responsabilidades

## Requisitos

**Obrigatórios:**
- Conhecimento sólido em JavaScript, HTML5 e CSS3
- Experiência na criação de apps utilizando React/React Native
- Forte conhecimento em padrões e consumo de APIs REST
- Experiência com metodologias de desenvolvimento como TDD e/ou BDD
- Experiência com CI/CD.

**Diferenciais:**
- Conhecimento em diferentes linguagens, como TypeScript, Kotlin, Swift, Scala e etc
- Forte conhecimento em Javascript ES6
- Forte conhecimento em desenvolvimento de aplicações nativas
- Forte portfólio de código aberto com foco nas tecnologia utilizadas (Github, Bitbucket, NPM, etc.)
- Formação em Ciência da Computação ou similar
- Experiência com ferramentas de desenvolvimento de front-end como Babel, Webpack, NPM, etc

## Contratação

P.J a combinar

## Nossa empresa

Surgimos em 2014 para ajudar a resolver o problema de um pai, mas vimos que poderíamos ir além e nos tornamos a solução de milhares de responsáveis. Conseguimos, assim, construir juntos uma comunicação escolar simples, rápida e eficiente que ajuda diariamente mais de meio milhão de pessoas.

Nosso propósito é ajudar, é estar lado a lado na jornada educacional, construindo uma rede inteligente para troca de ideias e experiências. Aproximamos famílias e escolas com interações que geram valor e fortalecem laços.

Conquistamos amigos, parceiros e estamos presentes em mais de 1.500 escolas em todo o Brasil e com mais de 500.000 de usuários. Temos o apoio do programa Promessas da Endeavor e da Fundação Lemann, uma das maiores fundações educacionais do país, além de sermos a solução oficial da empresa líder mundial em educação. Também somos reconhecidos pela inovação através de prêmios como Santander Universidades, Desafio Brasil, Você Empreendedor e Campus Party.

Nossa missão é engajar, tornar alunos e responsáveis participantes ativos da rotina escolar e, juntos, prepararmos para dar o próximo passo na construção de um saber plural e globalizado.

## Como se candidatar

* Por favor envie um email para renan@agendaedu.com com seu CV anexado 
* Enviar no assunto: Vaga Frontend Developer (React Native)

## Labels

- PJ
- CLT
- Pleno
- Remoto
- Alocado
- Ceará

**Comment by gamoridev** [comment]
Enviado!

**Comment by mensonones** [comment]
tem vaga para Júnior?

**Comment by gurgelrenan** [comment]
> tem vaga para Júnior?

@mensonones no momento não

**Comment by LucasHiago** [comment]
vocês pedem conhecimento técnico? se não, seria interessante.

**Comment by geekdoagrest** [comment]
hehehe Ceara ganhando força!!! como fico feliz em ver as startups da minha terra crescendo!

**Comment by gurgelrenan** [comment]
@LucasHiago destacamos isso na parte de `Requisitos obrigatórios` :)

**Comment by gurgelrenan** [comment]
@MacgyverMartins estamos entrevistando os candidatos, manda ai!

**Comment by gurgelrenan** [comment]
> hehehe Ceara ganhando força!!! como fico feliz em ver as startups da minha terra crescendo!

@geekdoagrest Opa, com certeza! Sempre bom nossa terrinha ganhando força! ps: Adorei o teu username :)
