### ISSUE TITLE
[Fortaleza] Desenvolvedor Front-end na Agenda Kids

### ISSUE THREAD

**Issue by cjpatoilo** [frontendbr/vagas#191]
## Descrição da vaga

A [Agenda Kids](https://agendakidsdigital.com/) está à procura de um(a) Front-end que seja apaixonado(a) pela experiência do usuário e está animado(a) sobre a criação de aplicações web e mobile. 

## Local

Escritório, Ceará - Fortaleza
<br>Rua Joaquim Nabuco, 2829, Cobertura, Dionísio Torres.

## Benefícios

- Vale alimentação
- Plano de saúde
- Plano odontológico
- Incentivo para eventos
- No dress code

## Requisitos

**Responsabilidades:**

- Construir guias de estilos
- Criar interfaces agradáveis e acessíveis
- Implementar recursos usando tecnologias avançadas de front-end
- impulsionar novas alterações do produto através de testes A / B
- Trabalhar com outros desenvolvedores para avançar as estruturas de UI.
- Ajudar a melhorar nossa aplicação Mobile (ANDROID / IOS)

**Obrigatórios:**

- Conhecimento especializado de JavaScript, HTML5 e CSS3
- Conhecimento com IONIC framework
- Experiência em pelo menos um framework moderno de UI (por exemplo, AngularJS, ReactJS, Backbone.js, etc)
- Compreensão das tecnologias da web, como REST, HTTP, JSON
- Experiência com TDD
- Capacidade de aprender e adaptar-se num ambiente de ritmo rápido

**Diferenciais:**

- Experiência com animações complexas de JavaScript e CSS
- Experiência com ES6
- Experimente a criação de web-apps utilizando ReactJS
- Familiarizado com os conceitos de PWA

## Contratação

CLT

## Sobre a empresa

[Agenda Kids](https://agendakidsdigital.com/) é uma solução de comunicação escolar que funciona como um elo, unindo pais, alunos e escolas. Muito mais que uma agenda digital, a ferramenta facilita a comunicação entre escolas, alunos e responsáveis, auxiliando esses na organização da vida escolar de seus filhos e ajudando as instituições educacionais a gerenciar seus profissionais e otimizar o processo de comunicação.

O objetivo da plataforma é que a escola possa ter uma comunicação rápida, eficiente e direta com alunos e responsáveis. As informações estão sempre disponíveis a qualquer hora, em qualquer lugar, através do aplicativo celular ou pelo acesso a plataforma web. Facilitando assim, a organização das atividades dos alunos e melhorando o engajamento dos responsáveis com a escola.

Atualmente estamos presentes em mais de 600 escolas em todo o Brasil, com mais de 100.000 usuários impactados. Temos grandes desafios em 2017 e precisamos de você.

## Como se candidatar

Para se candidatar, basta aplicar enviar um email para `contato@agendakidsdigital.com` com o assunto `[VAGA] Desenvolvedor Front-end` com as informações:

- Currículo ou Linkedin
- Pretensão salarial
- GitHub e/ou Blog - Vai nos ajudar a conhecer você e seu trabalho melhor :)
- Por que está interessado em trabalhar conosco?

 (se possível, diga que viu a vaga aqui no frontendbr/vagas =D).

**Comment by cjpatoilo** [comment]
cc/ @carlosalan @vitormalencar @gurgelrenan

**Comment by LFeh** [comment]
Bela vaga @cjpatoilo !

Qual o perfil dela?

**Comment by cjpatoilo** [comment]
@LFeh [SENIOR]

**Comment by cjpatoilo** [comment]
Olá @LFeh. A @agendakids conseguiu o que desejava. Grato pelo trabalho incrível que vocês vem fazendo para a comunidade. Muito obrigado. 🙏

**Comment by LFeh** [comment]
Aeeeee, tamo junto grande @cjpatoilo 😃

**Comment by camilatigre** [comment]
@cjpatoilo 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by vitormalencar** [comment]
@camilatigre
No caso dessa vaga não foi por essa issue.
