### ISSUE TITLE
[Itupeva/SP ou Remoto] [Freelancer] Front-end Developer na Startup Brewing

### ISSUE THREAD

**Issue by rcolossi** [frontendbr/vagas#1911]
## Descrição da vaga

Desenvolvimento de Apps em Angular 6/7 para o ecossistema de cervejarias artesanais.

## Local

Remoto ou na Fábrica em Itupeva/SP

#### Diferenciais

- Se estiver trabalhando no local, conhecerá novas cervejas toda a semana ;)

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com Node
- 2 anos de experiência com Angular
- Conhecimento sólido em JavaScript, HTML5 e CSS3
- Forte conhecimento em padrões e consumo de APIs REST
- Experiência com CI/CD.
- Dominio do uso do Bitbucket
- Dominio do uso do VS Code

**Desejáveis:**
- conhecimentos em PHP

**Diferenciais:**
- projetos opensource

## Contratação

PJ a combinar

## Nossa empresa

A StartUp Brewing é mais que uma cervejaria, como indica seu nome “StartUp” é uma aceleradora que nasce para investir em cervejarias ciganas, dar apoio consultivo em toda a cadeia desde elaboração de receitas, desenvolvimento de produtos, rótulos, marketing, financeiro, tributário, distribuição, etc. 
Entre nossos objetivos, está a criação de condições para que outras cervejarias possam crescer e competir de igual para igual com grandes marcas, desde a aquisição de insumos mais baratos, passando por um processo produtivo mais eficiente e controle de qualidade rigoroso.
Além disso, temos como objetivo a criação de um ecossistema que padronize todas as etapas e ferramentas da produção, com um aplicativo criado para gerenciar todas as fases da elaboração da cerveja, permetindo acompanhar diariamente, e em tempo integral, cada estágio.
Estamos montando uma fábrica modelo e única, a primeira fábrica 4.0 de pequeno porte do Brasil onde a tecnologia será nossa aliada para melhoria continua de processos, melhor padronização das cervejas produzidas e controle de tudo o que acontece na fábrica, além de produzirmos um produto com qualidade sem igual.

## Como se candidatar

Por favor envie um email para rodrigo@startupbrewing.co com seu CV anexado - enviar no assunto: Vaga Freela Angular

## Labels

- Freela
- PJ
- Pleno
- Remoto
- Sênior

**Comment by danielswater** [comment]
Enviado

**Comment by MrS4w** [comment]
Favor @rcolossi adicionar `Full-stack Developer` ao invés de `Front-end Developer` :smile:

**Comment by rcolossi** [comment]
Blz

Rodrigo Colossi
rodrigo@colossi.net

**Comment by joseaugustoneto** [comment]
@MrS4w mandei o e-mail com o assunto de `Vaga Freela Angular` no sábado, precisa manda com assunto diferente?

**Comment by MrS4w** [comment]
@joseaugustoneto não entendi, como assim?

**Comment by joseaugustoneto** [comment]
@MrS4w desculpa, viajei demais nesse comentário e achei que deveria enviar o e-mail com outro assunto.

> Favor @rcolossi adicionar `Full-stack Developer` ao invés de `Front-end Developer`

Desconsidere por favor.

**Comment by MrS4w** [comment]
@joseaugustoneto tudo bem :smile:
