### ISSUE TITLE
[Salvador] Front-End Developer [SANAR]

### ISSUE THREAD

**Issue by PedrodaIntera** [frontendbr/vagas#1913]
## Descrição da vaga

O Desenvolvedor Front-End da Sanar irá assumir a usabilidade das novas plataformas e compor o time de tecnologia da empresa, adquirindo responsabilidades de forma autônoma  e entregando valor nos seus resultados. 

Ao crescer aceleradamente nos últimos anos e impulsionar a carreira de milhares de profissionais da área de saúde, a Sanar está passando por um momento de transformação, em que a palavra chave é tecnologia.

Se você se contenta com o médio, não curte sair da sua zona de conforto e aprender todo dia, nem vale a pena rolar para baixo…

Mas, se você quer fazer parte de um time em que a sua régua aumenta todos os dias, continua aqui que temos uma oportunidade para você.

## Local

Efetivo CLT (presencial flexível) – 44h semanais
Endereço de trabalho: R. Alceu Amoroso Lima, 172, Caminho das Árvores – Salvador, BA

Auxilio deslocamento:
Caso não seja de Salvador, a Sanar está disposta a trazer você para cá e a auxiliar no seu deslocamento!

Existe a possibilidade de trabalho remoto 🙂

## Benefícios

- Remuneração de R$4.000 a R$8.000 - a depender da senioridade
- Vale transporte
- Vale alimentação
- Plano de saúde

#### Diferenciais

- Empresa jovem e em crescimento acelerado
- Autonomia
- Possibilidade de trabalho remoto ou de auxílio com o deslocamento 

## Requisitos

Conhecimentos técnicos necessários
Pelo menos 3 anos trabalhando como desenvolvedor JavaScript, CSS3 e HTML5
Familiarização com frameworks atuais como React, Redux, ES2015+, Webpack, React Native e Vue
Escrever código limpo e legível para outros(as) desenvolvedores(as)
Testes unitários, de aceitação, mocks, integração e BDD
CI ou CD e com source control tools como Gitlab, GitHub, etc
Conhecimento em PWA (progressive web app) e sites responsivos

**Obrigatórios:**
- Querer aprender sempre e serem curiosas afinal conhecimento nunca é demais
- Amar trabalhar em um ambiente ágil
- Ser analítico(a) e ter habilidades para resolver problemas com soluções simples e criativas
- Fazer mentoring/coaching de pares e team members menos experientes
- Ter atitude positiva e colaborativa diante dos problemas e desafios
- Ser obcecado(a) por entregas de valor e resultados
- Comunicar suas necessidades e serem críticos em relação aos problemas do time
- Se comunicar de forma natural em Inglês

## Contratação

Efetivo CLT

## Nossa empresa

Somos uma empresa comprometida em ajudar o estudante da área de Saúde a atingir todos os seus objetivos profissionais e acadêmicos. Para tanto, formamos um time composto por mais de 100 professores das principais Universidades do país que assinam a autoria das nossas obras e cursos. Acreditamos que apenas com materiais didáticos customizados conseguiremos atender aos propósitos dos nossos clientes. Customização do produto e relacionamento com cliente, ao nosso ver, compõe a essência do que a Sanar pode oferecer de melhor.

## Como se candidatar

Candidatura e mais informações através do link: http://bit.ly/2U9JbaJ

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: pedro@byintera.com

## Labels

- CLT
- Pleno
- Sênior
- AuxílioDeslocamento
- OuRemoto

**Comment by JIFerreira** [comment]
precisa ser graduado?

**Comment by PedrodaIntera** [comment]
A vaga requer senioridade e experiência, @JIFerreira, mas não necessariamente isso diz respeito a uma graduação. Se você acredita que tem os requisitos pedidos e a experiência, não hesite em se escrever.
