### ISSUE TITLE
[São Paulo] Front-end Developer react e react native Pleno na Mirae Asset

### ISSUE THREAD

**Issue by marcobfv** [frontendbr/vagas#1916]
## Descrição da vaga

Trabalhar numa arquitetura bem bacana com React, então tem que enteder bem de JS. Será responsável pela manutenção e evoluções de nosso Mobile e Portal do cliente.

**Link para nosso teste:**
[Github](https://github.com/marcobfv/desafio-mirae-react)

## Local

  Escritório localizado em São Paulo - Vila Olímpia; proximo ao metrô 

## Benefícios

- Pacote competitivo com mercado (mais detalhes na entrevista)

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com JS, seja node, angular ou principalmente React
- Redux
- Webpack
- TDD

**Desejáveis:**
- conhecimentos em Scrum 
- AWS

**Diferenciais:**
- conhecimento sobre mercado financeiro
- Inglês bom para conversação 

## Contratação

CLT ou PJ

## Nossa empresa

A Mirae Asset é uma corretora de valores e tem sua origem na Coréia do Sul, sendo a lider de mercado na Ásia inteira e possui presença em 15 países, aqui você será um dos responsáveis pela renovação digital da empresa no Brasil tendo chance de participar de coisa incríveis.

Precisa trabalhar de social devido ao ambiente venha na estica, a não ser que seja sexta-feira \o/ 

## Como se candidatar

Por favor envie um email para marco.vasconcellos@miraeinvest.com.br com seu CV anexado - enviar no assunto: Vaga Front

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

## Labels

- Alocado
- CLT
- PJ
- Pleno
- React
- Redux
- Webpack
- JS
- Ecma

**Comment by marcobfv** [comment]
Criamos um teste para esta vaga:
https://github.com/marcobfv/desafio-mirae-rest

**Comment by felipefialho** [comment]
@marcobfv Pode adicionar no [frontend-challenges](https://github.com/felipefialho/frontend-challenges)?

**Comment by marcobfv** [comment]
> @marcobfv Pode adicionar no [frontend-challenges](https://github.com/felipefialho/frontend-challenges)?

PR enviado
