### ISSUE TITLE
[Rio de Janeiro] PROGRAMADOR  - Ionic Android + IOS

### ISSUE THREAD

**Issue by BCockpit** [frontendbr/vagas#192]
## Procuramos 
Programador Pleno/Sênior fará novo App em substituição ao atual basicamente do zero
Casos de sucesso em mysql e Ionic 
Android + IOS App
Comprometido e perfil  empreendedor
80% remoto. Reuniões presenciais em Copacabana, quando necessário. 

## Local

Remoto, cidade do Rio de Janeiro, MUITO IMPORTANTE!

## Projeto

Início: Imediato
Fim: Indeterminado , dependerá do resultado
Dedicação semanal:  20-30 horas
Local: Rio de Janeiro

## Oferecemos

Start-up em fase de lançamento. Web pronto.
Potencial efetivação
Flexibilidade de horário
Ambiente dinâmico e empreendedor 

## Contratação

PF a combinar

## Nossa empresa

BCockpit, Gerenciador de contatos com georeferenciamento, integrado com GMail, redes sociais, CRMs e ferramentas de e-mail marketing. Start-up que será “the next big thing” da Internet mundial.  

## Como se candidatar

Por favor envie um email para octavio@bcockpit.com com seu CV anexado - enviar no assunto: Vaga PROGRAMADOR  - Ionic Android + IOS

## Próximos passos

Perfil LinkedIn c/Portfólio de casos Ionic
Avaliação de CV e Portfólio
Entrevista por Skype (id por favor)
Entrevista pessoal 
Contratação

![ionic](https://cloud.githubusercontent.com/assets/24566413/21186509/0bb45d50-c1fc-11e6-8db7-097ee4666946.jpg)

**Comment by danielGalvao** [comment]
Contratação PF? Ou PJ? E qual o nível da vaga para o pessoal colocar as labels. Jr, Pleno ou Sênior? 100% remoto?

**Comment by BCockpit** [comment]
Tanto faz PF ou PJ. Nível Pleno/Sênior. Sim, 100% remoto mas poderemos ter eventuais reuniões presenciais no local da empresa em Copacabana.

**Comment by BCockpit** [comment]
Essa é a minha 1a postagem. Obrigado por colocar as labels mas quero modificá-las. Como faço isso por favor?

**Comment by lucianopf** [comment]
@BCockpit 
Isso é apenas para colaboradores do repositório, diga aí o que vc quer colocar que a galera verá se é plausível com o padrão do repositório.

**Comment by BCockpit** [comment]
ah ok. vejamos entao
contrato PF (não CLT), PJ, Pleno, Senior, 80% remoto, Rio de Janeiro, Ionic, AngularJS, React, nodejs, Android, IOS, mysql
pode ser?

**Comment by LFeh** [comment]
@BCockpit Isso é o melhor que posso fazer, rs

**Comment by BCockpit** [comment]
muito obrigado

**Comment by LFeh** [comment]
Não temos :)

**Comment by marcoribeirojr** [comment]
Vaga ainda disponível?

**Comment by BCockpit** [comment]
se estiver baseado no Rio, SIM!

**Comment by marcoribeirojr** [comment]
Beleza, vou enviar um email.

**Comment by BCockpit** [comment]
Olá @marcoribeirojr. chegou a enviar?

**Comment by marcoribeirojr** [comment]
Não, vou te enviar hoje.

**Comment by marcoribeirojr** [comment]
@BCockpit enviado!
