### ISSUE TITLE
[São Paulo, Remoto] Front-End Developer na [ReclameAQUI]

### ISSUE THREAD

**Issue by diegoscampos** [frontendbr/vagas#1923]
## Descrição da vaga

O que você vai fazer:

- Desenvolver automação de implantação e operação com mindset Devops 
- Estudar e sugerir mudanças frequentes para manter o Software vivo e alinhado com os padrões atuais de mercado 
- Implementar software adequado para Cloud, alta audiência e alta disponibilidade.

## Local

Remoto ou Escritório, São Paulo - Berrini

## Benefícios

- Plano de saúde
- VR
- VA
- VT

#### Diferenciais

- Ambiente nos times de engenharia: colaborativo, inovador e desafiador
- Ambiente na empresa: descontraído e preocupado com seu bem-estar
- Salários compatíveis com o mercado de São Paulo

## Requisitos

**Obrigatórios:**

- Implementação de software focado na camada de apresentação 
- Implementação de aplicações responsivas e adaptativas usando Sass ou similar 
- Implementação da camada de negócio usando patterns atuais (Spa, Components, WPA etc) usando as frameworks Angular, React, Vue ou similar 
- Implementar integração com APIs públicas e privadas fazendo uso de modelos diversos de autenticação (Basic, Oauth, Session based, cookie based, Token based, etc..) 

**Diferenciais:**

- Implementar testes unitários 
- Implementar configuração de task management para automação de empacotamento (webpack,Gulp, Grunt, etc) 
- Implementar automação de implantação (salt, ansible, docker, kubernetes, etc)

## Contratação

CLT ou PJ, a combinar

## Nossa empresa

O ReclameAQUI é uma das maiores plataformas reputacionais do mundo, e um dos 10 sites mais acessados do Brasil. O ReclameAQUI ao longo de seus 18 anos de existência, mudou a forma como clientes e empresas se relacionam, sendo protagonista de uma revolução na forma como se atende cliente no Brasil. Nosso sonho é transportar essa revolução para outros países, através de uma plataforma global. Você pode fazer parte disso! Bora?

## Como se candidatar

Por favor envie um email para  leticia.prieto@reclameaqui.com.br com seu CV anexado - enviar no assunto: Vaga Frontend

## Labels

- CLT
- PJ
- Pleno
- Sênior
- São Paulo
- Remoto

**Comment by ferreirabh** [comment]
CV enviado.
