### ISSUE TITLE
Coordenador de Suporte 

### ISSUE THREAD

**Issue by ConsultoriaContato** [frontendbr/vagas#193]
## Descrição da vaga

Coordenador de suporte para atuar em uma empresa de Tecnologia Educacional (EAD). 

Atividades: administração de softwares de gestão de projetos (controle de usuários e atividades), elaboração de manuais e tutoriais, capacitações de equipe, suporte aos colaboradores internos e externos. 

Conhecimentos: softwares - pacote office, sharepoint, moodle. 

Necessária experiência com administração de softwares de gestão de projetos e plataforma moodle.

## Local

Florianópolis - SC

## Contratação

CLT

## Como se candidatar

Para se aplicar a vaga cadastre seu currículo em nosso site http://www.consultoriacontato.com/

**Comment by danielGalvao** [comment]
Amigo, aqui só vagas de Front-end... existem outros locais para postar essa vaga. Trampos.co, apinfo, LinkedIn etc...

**Comment by LFeh** [comment]
Porra, essa foi foda.
