### ISSUE TITLE
[Encerrada] [Rio de Janeiro] Front-End Developer JR [Nova Aliança Imóveis]

### ISSUE THREAD

**Issue by rafaelso86** [frontendbr/vagas#1934]
## Descrição da vaga

Tá procurando Job?

A gente tá buscando um(a) desenvolvedor(a) front-end, que tenha pelo menos um ano de experiência, para somar à nossa equipe! Essa pessoa vai trabalhar no desenvolvimento de aplicações web progressivas (PWA), landing pages, hotsites e e-mail marketings.

Estamos focados em um projeto especial e trabalhamos em um ambiente leve, criativo e direcionado para resultados. Temos a possibilidade de home office programado.

## Local

Ficamos no centro da cidade do Rio de Janeiro.

## Requisitos
01. Criar hotsites, landing pages, e-mail marketings (via Mail Chimp e similares) e PWA;
02. Codificar com as melhores práticas de SEO;
03. Desenvolver sites e aplicações responsivas;
04. Estudar novos recursos para aplicar às necessidades da equipe;
05. Se comunicar bem com colegas e parceiros de usabilidade, interface e back-end;

**Desejáveis:**
01. Inglês intermediário ou fluente;
02. Experiência anterior em Scrum ou outro método ágil;
03. Alta fidelidade visual da aplicação desenvolvida

**Diferenciais:**
01. Inglês intermediário ou fluente;
02. Experiência anterior em Scrum ou outro método ágil;
03. Alta fidelidade visual da aplicação desenvolvida;

## Contratação

CLT 

## Benefícios
- 13° salário;
- Férias;
- Vale transporte;
- Vale refeição;
- Após o período de experiência, plano de saúde integral;
- Possibilidade de home office planejado;

## Nossa empresa

Somos uma corretora de imóveis jovem e dinâmica criada em 1995 com a missão de atender compradores, proprietários e incorporadores de imóveis da Zona Sul ao centro da cidade.

Aqui na Nova Aliança Imóveis, nossos clientes contam com profissionais atentos e dedicados prontos para atendê-los com os seguintes serviços de apoio aos negócios:

- Divulgação nos principais veículos de comunicação     
- Avaliação gratuita do preço de venda     
- Assessoria Jurídica     
- Serviços de Despachantes     
- Pós-vendas (registros e transferências)

## Como se candidatar

Mande seu currículo e portfólio para leandrobulkool@novaaliancaimoveis.com.br - lembre-se de colocar a vaga no assunto.

**Comment by FerBiani** [comment]
Existe a possibilidade de ser remoto?

**Comment by hevertonsb** [comment]
Vaga ainda aberta?
