### ISSUE TITLE
[Vitória] Front-end Developer na Dupay

### ISSUE THREAD

**Issue by philipedornelas** [frontendbr/vagas#1935]
## Descrição da vaga

Desenvolver software no segmento financeiro. 
Estudar e sugerir mudanças frequentes para manter o Software vivo e alinhado com os padrões atuais de mercado
Implementar software adequado para Cloud, alta audiência e alta disponibilidade.

## Local

Remoto ou Escritório, Vitória - Espírito Santo

#### Diferenciais

- 2 horas de almoço
- Ambiente colaborativo, inovador e desafiador
- Ambiente na empresa: descontraído e preocupado com seu bem-estar

## Requisitos

**Obrigatórios:**
- Experiência sólida com JS
- Experiência com Framework Vue.js

Implementação de software focado na camada de apresentação
Implementação de aplicações responsivas e adaptativas usando Sass ou similar
Implementação da camada de negócio usando patterns atuais (Spa, Components, WPA etc) usando o frameworks Vue.js
Implementar integração com APIs públicas e privadas fazendo uso de modelos diversos de autenticação (Basic, Oauth, Session based, cookie based, Token based, etc..)

**Diferenciais:**

Implementar testes unitários
Implementar configuração de task management para automação de empacotamento (webpack,Gulp, Grunt, etc)
Implementar automação de implantação (salt, ansible, docker, kubernetes, etc)

## Contratação

PJ a combinar

## Nossa empresa
http://dupay.com.br

Fintech focada em gestão de recebimentos com boletos e cartões de crédito, ambiente colaborativo e desafiador. 

## Como se candidatar

Por favor envie um email para philipe.dornelas@dupay.com.br com seu CV anexado - enviar no assunto: Vaga FrontEnd

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

## Labels

- Alocado
- PJ
- Pleno
- Remoto
 - Vitória
 - Espírito Santo

**Comment by mikaelhadler** [comment]
Apply

**Comment by philipedornelas** [comment]
Vaga Preenchida. Obrigado aos candidatos.
