### ISSUE TITLE
[Campinas] Front-End Developer na ICTS

### ISSUE THREAD

**Issue by Paulogrupe** [frontendbr/vagas#1936]
Descrição da vaga

Somos uma empresa de pesquisa, desenvolvimento e provimento de soluções tecnológicas para automação e acessibilidade.
Procuramos pessoas que se identifiquem com nossos valores empresariais, os quais levamos aos nossos clientes através de produtos e serviços.
Se seus desafios estão na pesquisa e desenvolvimento de soluções para automação e acessibilidade, oferecemos um aficionado time de profissionais altamente gabaritados e desafios que exigem dedicação e empenho, para garantir e elevar a qualidade e a confiabilidade de nossos produtos e serviços. 

Local: Campinas/SP

Escritório, Campinas/SP

Benefícios

Seguro Saúde
Plano Odontológico
Ticket Alimentação

Requisitos Técnicos Essenciais:
Experiência em programação utilizando metodologias ágeis, desenvolvimento, implementação e testes de software e relacionamento com clientes.
Desenvolvimento de aplicações Frontend Angular2 e posteriores;
Integração de serviços REST a interfaces gráficas;
Bibliotecas de gráficos (Chart.js, amcharts, HighCharts);
Versionamento de software (Git);
Conhecimentos básicos (HTML5, CSS3, SASS); UX.

Requisitos Técnicos Adicionais/Desejáveis:
Experiência com bancos de dado relacional (MariaDB, MySQL, ORACLE);
Conhecimento em programação para Backend (Spring Boot) e teste unitário Javascript (Jasmine, Karma).

Contratação

CLT

## Nossa empresa

Nossa missão é pesquisar, desenvolver e comercializar soluções para automação e acessibilidade, prover mão de obra técnica especializada em automação e realizar projetos de P&D com competência, eficiência e qualidade, para atender às necessidades dos nossos clientes e melhorar os seus processos e sistemas.

## Como se candidatar

Por favor envie um email para pg@individuals.io com seu CV anexado e pretensão salarial - enviar no assunto: Vaga Front-End Developer

## Labels

- Alocado
- CLT
- Pleno

**Comment by MrS4w** [comment]
@Paulogrupe qual empresa?
Favor colocar no título da vaga

**Comment by felipefialho** [comment]
@MrS4w Se não tiver até o fim do dia pode fechar ;)

**Comment by MrS4w** [comment]
OK :smile:

**Comment by Paulogrupe** [comment]
tks

________________________________
De: Victor Λntonio <notifications@github.com>
Enviado: quarta-feira, 10 de abril de 2019 15:25
Para: frontendbr/vagas
Cc: Paulogrupe; Mention
Assunto: Re: [frontendbr/vagas] [Campinas] Front-End Developer (#1936)


OK 😄

**Comment by Paulogrupe** [comment]
Desculpe. Coloquei o nome da empresa. Por favor pode reabrir esta vaga

**Comment by Paulogrupe** [comment]
> @MrS4w Se não tiver até o fim do dia pode fechar ;)

Coloquei. Pode reabrir?

**Comment by Paulogrupe** [comment]
obrigado

________________________________
De: Victor Λntonio <notifications@github.com>
Enviado: quinta-feira, 11 de abril de 2019 09:17
Para: frontendbr/vagas
Cc: Paulogrupe; Mention
Assunto: Re: [frontendbr/vagas] [Campinas] Front-End Developer na ICTS (#1936)


Reopened #1936<https://github.com/frontendbr/vagas/issues/1936>.
