### ISSUE TITLE
[São Paulo] Front-End Developer na Petlove

### ISSUE THREAD

**Issue by mauricionr** [frontendbr/vagas#1939]
## Descrição da vaga

Vaga para o time de desenvolvimento da Petlove.

Se você é uma pessoa analítica, com um forte background em VueJS , React , HTML5 e NodeJS temos uma ótima oportunidade para você:

Procuramos um profissional experiente para contribuir no desenvolvimento da nossa plataforma de produtos.

## Nossa empresa

A Petlove é o e-commerce líder no mercado, investido pelos melhores fundos de Venture Capital do Brasil. Nascemos em 1999 a partir do sonho visionário de um médico veterinário que foi pioneiro em apostar na venda online de produtos pet em uma época em que a internet no país ainda era uma incerteza. Hoje, são mais de 15 mil produtos vendidos através do nosso site e aplicativo e entregues em todo o território nacional. Somos mais de 280 petlovers que acreditam no investimento em tecnologia e amor pelos pets para continuarmos oferecendo os melhores serviços, produtos e conteúdos pet para nossos clientes: os peludos e suas famílias.

![Petlove Image](https://www.petlove.com.br/static/uploads/images/petcool.png)

### Presença

Distribuição em todo território nacional

mais de 1 milhão de clientes

### Conquistas e Premiações

[Melhores Apps 2017 na Apple Store](https://www.petlove.com.br/dicas/aplicativo-petlove-e-eleito-como-um-dos-melhores-ano-pela-app-store)

Primeiro pet shop Diamante Ebit

[Loja mais querida Ebit 2017](https://www.ebit.com.br/premio-ebit/2017)

[Loja mais querida Ebit 2018](https://www.ebit.com.br/premio-ebit/2018)

[RA1000 no Reclame Aqui](https://www.reclameaqui.com.br/empresa/petlove-petsupermarket/)

[Case de site mobile - Google 2018](https://www.youtube.com/watch?v=PsgW-0M67TQ&feature=youtu.be&t=17m17s)

## Local

[São Paulo - Berrini](https://goo.gl/maps/HarDqbMRWCL2)

## Benefícios

- Assistência médica
- Odontológica
- Seguro de vida
- Bicicletário no prédio
- VR/VA

#### Diferenciais

- Sala de descompressão com vídeo-game, mesa de ping-pong e pebolim;
- Crédito em nosso refeitório autônomo com uma variedade de Snacks =)
- Pet Friendly, pets são muito bem vindos no escritório =)
- Sala de jogos
- PLR anual
- Desconto em produtos no site
- Day-off de aniversário;
- Parcerias com descontos;

## Requisitos

**Obrigatórios:**
 - VueJs ou React
 - Git
 - Javascript (Vanilla)
 - Gulp ou Webpack
 - HTML5/CSS3/Sass
- NodeJS
- APIs / REST
- Testes Automatizados
- Cloud (AWS ou Google Cloud)
- Ecmascript 6 +

**Desejáveis:**
- projetos opensource
- Elastic Search
- PWA/Service Workers
- Kubernetes
- Docker
- Elixir
- GraphQL
- Websockets
- Ruby on Rails
- Serveless
- OOP e Desing Patterns
- Python
- NoSQL
- ShellScript
- MySQL ou Postgres

## Contratação

CLT

## Como se candidatar

[Front-End Developer Pleno](https://petlove.gupy.io/jobs/38387)
[Front-End Developer Senior](https://petlove.gupy.io/jobs/38382)
## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: [email](mailto:mauricio.reis@petlove.com.br)

## Labels

- CLT
- Pleno
- Sênior

**Comment by mauricionr** [comment]
+1

**Comment by DayaneVeronez** [comment]
A Vaga ainda está aberta!!! :)

**Comment by mauricionr** [comment]
vi que abriu outra issue, valeuu 🚀
