### ISSUE TITLE
[Salvador / BA] Desenvolvedor Front-End Estágio

### ISSUE THREAD

**Issue by marcosalberto** [frontendbr/vagas#194]
## Descrição da vaga

Aqui você terá a oportunidade de trabalhar em projetos de grande acessos, alta disponibilidade e aprender bastante no processo de desenvolvimento deles.

## Local

Escritório, Itaigara - Salvador, BA

## Benefícios

- Ambiente de trabalho descontraído
- Oportunidade de crescimento e contratação
- Trabalhar de bermuda, afinal, é Salvador.

## Requisitos

**Obrigatórios:**
- HTML
- CSS
- Javascript / jQuery

**Desejáveis:**
- Web Semântica
- Conhecimento de Arquitetura MVC
- GIT
- Conhecimento de alguma Template Engine
- Conhecimento de algum pré-processador CSS

## Contratação

- 6 horas/dia
- Manhã ou Tarde
- R$ 900,00

## Nossa empresa

A Convergence Works, que chamamos de CW, é uma empresa de TI especializada em transformar ideias e projetos de interatividade em negócios reais.

## Como se candidatar

Por favor envie um email para kellyene.coelho@convergenceworks.com.br com seu CV anexado - enviar no assunto: CW - FRONT-END - < Nome do Candidato >

**Comment by brunooomelo** [comment]
aceita HomeOffice?

**Comment by david27alves** [comment]
Aceita home office?

**Comment by marcosalberto** [comment]
@mtmr0x pode reabrir esta issue? Obrigado

**Comment by aislanmaia** [comment]
está disponível Home Office? Tô topando.

**Comment by marcosalberto** [comment]
@aislanmaia infezlimente não.

**Comment by Daniel-Reis01** [comment]
Tenho interesse
