### ISSUE TITLE
[São Paulo] Senior Software Engineer na Locaweb

### ISSUE THREAD

**Issue by gguimaraesbr** [frontendbr/vagas#1942]
## Quem somos:

// Nascemos em 1998, fruto da paixão pela tecnologia e do impulso empreendedor de nossos fundadores. Com a sabedoria que só quem é a página inicial da internet no Brasil pode ter, acreditamos que todos podem se desenvolver. Por isso, oferecemos um portfólio completo de serviços de internet, atendimento especializado e muito conteúdo.

Mais de 280 mil clientes e 15 mil desenvolvedores parceiros estão com a gente. Somos uma empresa que possui diferentes unidades de negócio, cada qual com um conjunto de soluções específicas: serviços de internet, e-commerce, marketing de relacionamento digital e projetos corporativos, mas com algo em comum: paixão por desenvolver. Porque, aqui na Locaweb, desenvolver vai muito além da tecnologia. :)

## Como será seu dia a dia:

- Trabalhar em times multidisciplinares (Product Owner, UX, Marketing e SysAdmin) com mindset ágil, desenvolvendo soluções que encantem nossos clientes;
- Garantir a qualidade e a manutenibilidade de todo código produzido por você e seus pares;
- Enfrentar desafios envolvendo diferentes linguagens e tecnologias;
- Ensinar e aprender constantemente em um ambiente colaborativo;
- Avaliar e adotar novas tecnologias, ferramentas e práticas que resultem em melhores soluções para nossos clientes;

## E para tirar de letra, você precisa de:

- Experiência profissional em desenvolvimento de software;
- Sólidos conhecimentos de HTML, CSS e JavaScript;
- Experiência em (ou interesse em aprender) pelo menos uma das ferramentas da nossa stack: Vue, React ou Ember.js;
- Experiência com escrita e manutenção de testes unitários e de integração.

## E se tiver isso também, melhor ainda:

- Experiência com microserviços;
- Participação em comunidades de tecnologia;
- Contribuição com projetos open source.

## Só quem é Locaweber tem:

- Convênio Médico;
- Convênio Odontológico;
- Vale-Transporte ou Estacionamento gratuito;
- Serviço gratuito de vans do terminal João Dias para a Locaweb;
- Vale Refeição:
- Seguro de Vida;
- Máquinas de café à vontade;
- Massagem e ginástica laboral in company;
- Sala de Relax com TV, mesa de bilhar, carteado, tênis de mesa, videogames e puffs;
- Salão de beleza in company (cabelereiro, depilação, manicure e estética corporal);
- Academia e aula de Yoga in company.
- Programa de Qualidade de Vida e bem-estar;
- Parceiras com diversos estabelecimentos na área de saúde, lazer e entretenimento;
- Oferta de cortesias dos produtos LOCAWEB.

## Onde estamos:

- Ficamos num lugar incrível com muita natureza e pertinho do metrô Giovanni Gronchi e Terminal João Dias (Rua Itapaiúna, 2434 – Vila Andrade - São Paulo/SP).

## Como se candidatar:

Acesse esta vaga no [Kenoby](https://jobs.kenoby.com/locaweb/job/senior-software-engineer-frontend/5cafb398c36a230432c0740c) e participe do processo!

## Labels

- Alocado
- CLT
- Sênior

**Comment by marnescassule** [comment]
Ainda está em Pé essa vaga?

**Comment by gguimaraesbr** [comment]
Está sim @marnescassule

Acesse https://jobs.kenoby.com/locaweb/job/senior-software-engineer-frontend/5cafb398c36a230432c0740c
