### ISSUE TITLE
[Remoto] Front-End Developer na Citar.tech

### ISSUE THREAD

**Issue by meneguite** [frontendbr/vagas#1944]
![Citar.tech](https://s3-sa-east-1.amazonaws.com/citar.tech/assets/developers/dev-citar-tech.png)

### O que nós buscamos
* Responsável por desenvolver, testar e documentar rotinas;
* Atuar em implementações, melhorias de performance e integrações; 
* Desenvolver códigos bem estruturados utilizando boas práticas de programação;
* Realizar revisão por pares dos artefatos de programação; 
* Interagir com todo o time Scrum de forma construtiva na busca por resultados que agreguem valor aos clientes; 
* Construir código com testes automatizados/unitários para garantir a qualidade.

## Local
Remoto

## Requisitos:
* VueJs 2;
* HTML, CSS, SASS;
* Javascript ES6;
* Consumo de Rest APIs;
* Noções básicas de scrum e metodologias ágeis;
* Domínio do Git para versionamento de projetos;

## Diferenciais:
* Experiência com testes unitários usando Mocha;
* Experiência na utilização do docker;

## Contratação
PJ

## Como se candidatar

Após a execução do teste disponível em https://github.com/citartech/job-vacancies/blob/master/frontend-vue.md envie um email para rh.dev@grupocitar.com.br com seu CV anexado ou link do linkedin - enviar no assunto: Vaga Front-End

## Outras vagas abertas

Além dessa vaga de backend temos mais duas vagas uma de full stack e uma de backend, caso tenham interesse podem visualizar mais detalhes nos repositórios abaixo:

> Backend: https://github.com/citartech/job-vacancies/blob/master/backend-node.md
> Fullstack: https://github.com/citartech/job-vacancies/blob/master/fullstack-js.md

## Labels

- Remoto - Total
- PJ
- Pleno
- Sênior

**Comment by alessandroprudencio** [comment]
ainda esta aberta?

**Comment by meneguite** [comment]
Está sim @alessandroprudencio

**Comment by PuenteVinicius** [comment]
Ainda está aberta?

**Comment by meneguite** [comment]
Está sim @PuenteVinicius !

**Comment by dersonsena** [comment]
@meneguite a vaga ainda está aberta ?

**Comment by meneguite** [comment]
Está sim @dersonsena .. temos algumas vagas, então não se preocupem, fecho a issue quando não estivermos mais vagas disponíveis.

**Comment by pdrgds** [comment]
@meneguite a de back-end ainda está aberta?

**Comment by DanielFelizardoDev** [comment]
@meneguite tem vaga para Full Stack Júnior?

**Comment by meneguite** [comment]
@pdrgds tem sim -> https://github.com/backend-br/vagas/issues/976
@DanielFelizardoDev Fullstack trabalhamos apenas com Pleno ou Sênior.

**Comment by meneguite** [comment]
Obrigado a todos que fizeram a submissão para a vaga, ainda que tenhamos algumas vagas em aberto, em respeito aos que já enviaram vou fechar a issue para que consigamos colocar as submissões já enviadas em dia.
