### ISSUE TITLE
[Pará] Front-End Developer com especialidade em Angular na Super

### ISSUE THREAD

**Issue by appsuper** [frontendbr/vagas#1947]
## Descrição da vaga

Nós estamos procurando por desenvolvedor Front-end com experiências em Angular e Ionic, para executar seus serviços de forma remota, através de contrato PJ. Espera-se que o candidato tenha boas experiências como desenvolvedor na criação de produtos e recursos de software, prototipagem durante o ciclo de projeto e criação de recursos prontos para produção. Buscamos um candidato que possua pensamento inovador, criatividade em design e alcance dos resultados esperados. 

## Local

Remoto, empresa localizada em Belem - Pará

## Requisitos

**Obrigatórios:**
- Deve ter no mínimo 4+ anos provados de experiência como desenvolvedor Front-end.
- Experiente em HTML, HTML5, JavaScript, CSS, pre-processadores CSS como Sass e LESS
- Experiente em Angular 2+ e Typescript.

**Desejáveis:**
- Experiente em criação de aplicativos híbridos utilizando o framework Ionic/Cordova.
- Utilizar ferramentas de versionamento como GIT.

**Diferenciais:**
- Colaborar em projetos opensource

## Contratação

PJ a combinar

## Nossa empresa

Super é uma startup focada em inovações e no desenvolvimento de aplicativo de vendas onde o foco é trazer praticidade para o dia a dia de seus clientes. 

## Como se candidatar

Por favor envie um email para tecnico@appsuper.com.br com seu CV anexado ou Linkedin - enviar no assunto: Vaga Front-end Developer Angular

## Labels

- Remoto
- PJ
- Pleno
- Remoto

**Comment by juniorabranches** [comment]
CV Enviado

**Comment by danielswater** [comment]
Enviado

**Comment by danielswater** [comment]
@appsuper como está esse processo?
Obrigado
