### ISSUE TITLE
[São Paulo] Desenvolvedor Front-End na Magnetis

### ISSUE THREAD

**Issue by luisfmsouza** [frontendbr/vagas#195]
## Descrição da vaga

Are you motivated to solve real problems for real customers, instead of trying to catch up with all the latest, shiny technologies?

Do you really care about your craft, making sure you communicate your ideas well through maintainable code?

If so, Magnetis might just be the place for you.

Magnetis is an online investment advisory revolutionising how we plan our future through smarter investments. We were recommended by the press as one of the best investment apps in Brazil.

As a Front-end Engineer at Magnetis, you will help us ship value to our users in the fastest pace possible while maintaining product quality and security. You will be primarily responsible for the development and maintenance of our main web application, as well as building new web and mobile apps. Our main stack is based on Ruby, Elixir and Javascript and we employ a domain-driven architecture. Expect to work closely with the CTO and the rest of the engineering team and to tackle new challenges every week.

## Local

Remote work or Pinheiros, São Paulo

## Benefícios

In addition to joining a fun and innovative company and working in flexible workplace, you’ll enjoy:
- remote work
- competitive salary (CLT)
- health insurance, "vale-refeição", "vale-transporte"
- opportunity to earn stock options
- stipend for conferences and online courses
- company sponsored tech talks and happy hours
- endless hipster coffee

## Requisitos

**Obrigatórios:**
- has 2+ years of professional experience in crafting web applications
- has a component oriented architecture mindset
- knows the benefits of a visual styleguide for developers, designers and for the company.
- knows that TDD/BDD is essential for the healthy of the company.
- has exposure to architectural patterns of a large, high-scale web applications
- displays excellent writing and communication skills both in Portuguese and English
- displays a passion for consumer technology and startups
- is entrepreneurial, self-led and thrives in constantly changing environment

**Desejáveis:**
- have a computer engineering degree, but we’re more interested in your experience, life story and skills.
- have experience with back-end

## Contratação

CLT

## Como se candidatar

Workable: https://magnetis.workable.com/jobs/121441

**Comment by luisfmsouza** [comment]
@LFeh por favor coloca as labels `CLT`, `Alocado`, `Remoto`, `Junior` e `Pleno`. Ah, tudo bem a descrição estar em inglês?

**Comment by LFeh** [comment]
Sem problemas o/

Ps: Estou esperando a liberação no serviço de vocês, haha

**Comment by idlua** [comment]
@luisfmsouza queria te mandar um email pro endereço que tá no seu perfil sobre essa vaga? Tem algum problema?

**Comment by freeboxd** [comment]
@luisfmsouza, os 2 anos de experiência valem pra vaga júnior também?

**Comment by luisfmsouza** [comment]
@idlua manda bala!
@freeboxd o que a gente dá valor mesmo são as experiências. :) Jr ou Pleno são apenas formalidades.

**Comment by niltoncsr** [comment]
Enviado e com gosto :D


*Nilton*


2016-12-15 16:26 GMT-03:00 Luís Felipe Souza <notifications@github.com>:

**Comment by luisfmsouza** [comment]
Vaga fechada!

O @idlua (o primeiro que se candidatou ali em cima) começou hoje a trabalhar com a gente. 

Thanks Front-end BR! o/

**Comment by LFeh** [comment]
Aeee, olha ai @camilatigre
