### ISSUE TITLE
[Remoto] Pessoa Desenvolvedora Front-end React na Ignus

### ISSUE THREAD

**Issue by gneutzling** [frontendbr/vagas#1954]
## Descrição da vaga
Estamos procurando pessoas com vontade de assumir os desafios de desenvolvimento junto ao nosso time técnico.

## Local
Remoto

## Benefícios
- Variam conforme regime de contratação

## Requisitos
**Obrigatórios:**
- JavaScript;
- React;
- Styled-components;
- GIT;
- HTML e CSS.

**Desejáveis:**
- Experiência com Apollo e GraphQL;
- Conceitos básicos de programação funcional como High-Order Functions, Currying e Closure;
- Colaboração na comunidade (seja blog, open source, etc.).
- Testes unitários.

## Contratação
CLT ou PJ.

## Nossa empresa
Somos uma consultoria focada na construção de produtos digitais que impactam positivamente a vida das pessoas.

Nosso time trabalha de forma 100% remota e estamos espalhados pelo Brasil e pelo mundo. Temos o suporte de diversas ferramentas que nos mantém sempre conectados e próximos de nossos clientes e acreditamos que uma boa comunicação só depende de métodos, meios e disposição. É importante frisar que não somos freelancers.

Nossa cultura não é só trabalhar remoto. Valorizamos muito todas as práticas aderentes ao que chamam de “futuro do trabalho”. Para nós não é futuro, é presente!

## Como se candidatar
[Aplique aqui](https://ignusdigital.recruitee.com/o/pessoa-desenvolvedora-frontend-react)

## Labels
- CLT
- PJ
- Pleno
- Remoto
- Sênior

**Comment by YuriBrunetto** [comment]
Enviado!

**Comment by leonardorpr** [comment]
Enviado (:

**Comment by thalesf** [comment]
Tem que ter quantos anos de experiência no mínimo ?

**Comment by gneutzling** [comment]
@thalesf é interessante ter conhecimento com react, mas não tem um tempo de experiência mínima. Faça a aplicação que iremos avaliar por aqui. Qualquer dúvida da um ping 👍

**Comment by andremargarin** [comment]
Enviado!

**Comment by brunooomelo** [comment]
Enviado!

**Comment by guilouro** [comment]
Aplicado!

**Comment by vimaciel** [comment]
Enviado 😁

**Comment by phellipeandrade** [comment]
a Vaga ainda está disponível?

**Comment by ribeiroevandro** [comment]
No site não existe nenhuma vaga em aberto, como proceder?

**Comment by gneutzling** [comment]
@phellipeandrade @ribeiroevandro a vaga já está fechada.
