### ISSUE TITLE
[Tubarão - SC] Arquiteto Front-end na TRIER

### ISSUE THREAD

**Issue by penelopevitoria** [frontendbr/vagas#1956]
### **Descrição da vaga**

Buscamos alguém que queira: 

- Fazer acontecer
- Tenha criatividade
- Raciocínio Lógico Rápido
- Apaixonado(a) por tecnologia
- Levante alternativas e proponha soluções

### **Que tenha os seguintes interesses e conhecimentos:** 

- Pesquisar e validar novas tecnologias
- Realizar estudos de viabilidade técnica e econômica
- Propor e documentar soluções de softwares
- Modelar soluções de software
- Criar e desenvolver interfaces e sistemas frontend
- -Definir personas e jornadas de usuário
- Prototipar soluções
- Criar padrões e stlyle guide
- Desenvolver tecnicamente a equipe 
- Sólido conhecimento em Angular 4+
- Desenvolvimento Front end (HTML e CSS)
- Ferramentas para tomada de decisão e Testes A/B
- Automação de Testes (Jasmine, Karma)
- Vivência com ambientes cloud (AWS, Azure, Google Cloud)
- Metodologias aplicadas ao desenvolvimento de software como Scrum, XP, 
- Safe ou Lean 

### **Local**
 Av. José Acácio Moreira, 1631 - Centro, Tubarão - SC, 88704-001

### **Benefícios**

- Vale alimentação
- Plano de saúde
- Plano odontológico
- Outros

### **Tecnologias obrigatórias**
CSS, HTML

**### Tecnologias desejáveis**
AWS, Azure, AWS CloudFront, Google Cloud

### **Contratação**
CLT

### **Tempo médio de feedbacks**
Costumamos enviar feedbacks em até 1 mês após uma entrevista.

### **Como se candidatar?**

Cadastre-se na GeekHunter para concorrer à vaga: http://bit.ly/2Zfef81

**Comment by MrS4w** [comment]
@penelopevitoria qual o nível da vaga?
