### ISSUE TITLE
[Goiânia] Desenvolvedor JavaScript na CodeMiner42

### ISSUE THREAD

**Issue by fabricionaweb** [frontendbr/vagas#196]
## Descrição da vaga

A CodeMiner42 conta com escritórios por todo país, e agora vamos abrir mais um aqui na terra do pequi!
Buscamos desenvolvedores Júnior, Pleno ou Sênior para tornar isso possível.

## Local

Presencial em Goiânia.
Como estamos abrindo o escritório ainda, os primeiros meses devem ser home-office.

## Benefícios

- Vale transporte
- Vale refeição ou alimentação (Sodexo)
- Plano de saúde & dental
- Investimento de carreira (livros, cursos, codeschool, egghead, curso de ingles, etc)
- Contato com mais de 60 desenvolvedores ninjas e divertidos

## Requisitos

- Conhecimento dos frameworks da atualidade (React, Angular, Vue, Ember, etc)
- Toda aquela bagagem do frontend moderno (es6, webpack, node, gulp, processadores, etc)

**Seria interessante**

- Conhecimentos em Ruby on Rails
- Inglês em dias

## Contratação

CLT

## Como se candidatar

Por favor envie um email para fabricio.augusto@codeminer42.com com seu currículo anexado, LinkedIn, GitHub e pretensão salarial

**Comment by fabricionaweb** [comment]
@LFeh tags `CLT`, `PJ`, `Presencial`, `Junior`, `Pleno`, `Senior`, por gentileza

**Comment by danielfnz** [comment]
Irei me candidatar!
Estou concluindo minha graduação em 02/2017 por conta das greves.

**Comment by fabricionaweb** [comment]
@LFeh se puder remover o label `PJ` por favor.

**Comment by LFeh** [comment]
Done

**Comment by felipem1511** [comment]
Os mesmos requisitos para Junior?

**Comment by fabricionaweb** [comment]
@felipem1511 Bom dia;

Bom, mais ou menos... Temos um teste, se tiver interesse em aplicar, manda um email que vamos conversar.

**Comment by iGerley** [comment]
Boa tarde @fabricionaweb, 

A CodeMiner42 está contratando no momento?

**Comment by fabricionaweb** [comment]
@iGerley Sim, vc poderia mandar o email para become@codeminer42.com
