### ISSUE TITLE
[Diversos] Vagas para Front-end na Codeminer42

### ISSUE THREAD

**Issue by abnersajr** [frontendbr/vagas#1967]
## Descrição da vaga

Buscamos Front-end developers para atuar  em diversos projetos, inclusive projetos internacionais com clientes estrangeiros. Temos diversos projetos, com diversos frameworks e tecnologias, então entre em contato.
Estamos procurando pessoas de todo os níveis para fazer parte de nosso time, sem diferenças nem preferências. Todos são bem vindos.
## Local

A Codeminer42 está presente atualmente em mais de 10 estados do país. 
Temos vagas para todos eles. 
- São Paulo
- Campinas
- Sorocaba
- Batatais
- Guarapuava
- Novo Hamburgo
- Anápolis
- Goiânia
- Teresina
- Natal
- Santa Maria
- Florianópolis
- Poços de Caldas

**Remoto** é uma possibilidade apenas para pleno e sênior. Fazemos questão que estagiários e juniores tenham contato diariamente com a galera mais experiente e com o ambiente da empresa.

## Benefícios
1. Plano de saúde e dental;
2. Auxílio transporte;
3. Vale-refeição;
4. Ambiente de trabalho descontraído;
5. Acesso a cursos e portais de educação como Front-end Masters e egghead.io;
6. Curso de inglês para aperfeiçoamento.

#### Diferenciais

- Horário flexível
- Oportunidade de trabalhar em projetos nacionais e internacionais

## Requisitos

**Obrigatórios:**
- Experiência com um dos UI frameworks a seguir: **React**, **VueJS**, **React Native** ou **Angular**. Experiência com algum outro não listado é analisado individualmente. Mas não deixe de entrar em contato.
- Inglês avançado, temos clientes internacionais, logo o candidato tendo um nível de compreensão e conversação legal podera estar entrando em um projeto internacional. Lembrando que o inglês não precisa ser 100%. Por isso fazemos uma entrevista para ver como você se sai.

**Desejáveis:**
- conhecimentos em ruby on rails
- conhecimentos em NodeJS
- conhecimentos de infra-estreutura, AWS e Heroku são amplamente usados.
- Design Patterns
- Programação funcional
- TypeScript

## Contratação

CLT, sobre valores cada caso é avaliado individualmente sobre diversos aspectos, mas podemos garantir que os valores são atraentes

## Nossa empresa

A Codeminer 42 é uma butique de software brasileira focada em entregar o melhor valor a seus clientes. Nós começamos a operar em Setembro de 2011 e até agora expandimos para 10 cidades diferentes no Brasil com os melhores profissionais do Brasil.

Nossa especialidade é desenvolvimento web com Ruby on Rails e seu ecossistema satélite - que inclui as melhores tecnologias de ponta -, nós temos muita experiência em todos os tipos de produtos de tecnologia como e-commerces, e-learning, redes sociais, gerenciamento de conteúdo, automação de processos.

Trabalhamos com empresas pequenas ou grandes, temos diversos tipos de serviços que vão de ciclo de vida de desenvolvimento de projetos do zero, resgate de projetos legados, terceirização e assim por diante.

Se quiser ter não somente uma boa aplicação web em produção mas também melhorar seus processos de software, garantia de qualidade, podemos ajudar.

## Como se candidatar

Por favor envie um email para become@codeminer42.com com seu CV anexado, github, site pessoal e demais infos.
No Assunto coloque [CIDADE] Vaga para Front-end .
Maiores dúvidas, podem usar a issue ou enviar para abner.alves@codeminer42.com

PS: Temos vagas para Back-end também: 🔗[Vaga Back-end](https://github.com/backend-br/vagas/issues/1024)

## Labels
* CLT
* Alocado
* Remoto
* Estágio
* Júnior
* Pleno
* Sênior

**Comment by Math2SystemsDev** [comment]
Legal ! Eu quero o estágio. Vou mandar o currículo.

**Comment by gabrigcl** [comment]
Muito bom! Uma dúvida, no assunto ( [CIDADE] Vaga para Front-end) eu devo colocar a cidade onde eu pretendo concorrer à vaga não é? Mas e no caso de trabalho Remoto, devo colocar mesmo assim?

**Comment by abnersajr** [comment]
Olá Gabriel. Isso pode colocar sim. Facilita pra nós identificarmos 👌

**Comment by abnersajr** [comment]
@Math2SystemsDev isso ai não pensa duas vezes ;)

**Comment by danielfelizardo2017** [comment]
Enviado!

Em qua, 17 de abr de 2019 às 10:54, Abner Soares Alves Junior <
notifications@github.com> escreveu:

**Comment by danielfelizardo2017** [comment]
Enviado para a vaga Remoto!

**Comment by abnersajr** [comment]
❤️ Obrigado a todos que entraram em contato e se interessaram no processo. Por hora preenchemos todas as vagas. Mas em breve estaremos abrindo novas vagas. Obrigado pessoal.
