### ISSUE TITLE
[São Paulo] Desenvolvedor Front End Sênior  

### ISSUE THREAD

**Issue by helenmatos** [frontendbr/vagas#197]
## A 5A Gestão de Talentos busca profissionais Front End para atuar em um cliente de grande porte e fazer parte de um time diferenciado, com profissionais antenados que se preocupam com o desenvolvimento de soluções dentro dos melhores padrões de mercado. 
O profissional ficará responsável por definir e manter padrões de HTML e CSS para todos os projetos corporativos, dar suporte para equipe em implementações de design do front-end. Criação de protótipos de interface.

## Local
Escritório, São Paulo - Morumbi

## Requisitos
Dominar tecnologias da web (HTML5 + CSS3); Experiência com desenvolvimento de aplicações WEB de Front end; JavaScript, jQuery, Ajax, Bootstrap, Angular. 
 Conhecimento em controle de versão SVN e/ou Git;

**Obrigatórios:**
- 5 anos de experiência HTML; CSS
- Experiência com Angular

**Desejáveis:**
- Noções de UX para definir padrões para sistemas web internos e externos 
- Conhecimento em semântica, usabilidade e acessibilidade
- Photoshop, Illustrator, Design Mobile

## Contratação
PJ a combinar

## Nossa empresa
A 5A Gestão de Talentos atua fortemente no mercado Corporativo de TI, com destaque em Terceirização de Profissionais de Desenvolvimento, Gestão de Projetos e Soluções em Sistemas. 

## Como se candidatar
Por favor envie um email para Helen.matos@5A.com.br  com seu CV anexado - enviar no assunto: Vaga Front End - Sênior

**Comment by danielGalvao** [comment]
PJ Senior e Alocado ou Remoto?

**Comment by LFeh** [comment]
@helenmatos Precisamos do nome da empresa. :)

**Comment by helenmatos** [comment]
@LFeh :(  É confidencial.  Por este quesito não vou conseguir deixar a vaga cadastrada né?

**Comment by LFeh** [comment]
Não :(

Estamos desencorajando essa pratica.
