### ISSUE TITLE
[Rio de Janeiro] Front-End Developer na Stone Pagamentos

### ISSUE THREAD

**Issue by vtrpldn** [frontendbr/vagas#1970]
### TIME

Temos alguns times de desenvolvimento com diversos desafios para elevar o desempenho dos nossos processos e escalar nossa operação. Acreditamos que criar produtos e conhecimentos que simplifiquem a vida do empreendedor, dará a ele o poder de transformar o seu potencial em resultado.

### DESAFIO

O time com vaga disponível é o *Mamba SDK*.

Desafios:

Desenvolver e manter um SDK, usando o Svelte (um framework JavaScript similar a React e Vue) para facilitar o desenvolvimento de aplicativos web dentro do POS, nossa maquininha de cartão.

Você também será responsável pelo desenvolvimento de novos apps usando essa mesma ferramenta!

Nosso projeto é open source e pode ser acessado nos repositórios:

SDK: https://github.com/stone-payments/pos-mamba-sdk
Template de apps: https://github.com/stone-payments/pos-mamba-app-template

Se você é focado em alto desempenho, gosta de trabalhar no limite da memória de uma aplicação, otimizar o código de forma que performe da melhor maneira possível este é o desafio para você!

Trabalhe em um ambiente embarcado e encare limitações de hardware, transformando pouco recurso em um produto altamente performático.

## Local

Escritório, Rio de Janeiro - Centro

## Benefícios

- Vale transporte
- Vale refeição/Vale alimentação
- Plano de saúde Bradesco Premium
- Plano odontológico Bradesco Premium
- Auxilo creche
- Seguro de vida
- Gympass
- PLR anual

## Requisitos

**Obrigatórios:**
- Sangue nos olhos
- Conhecer tecnologias WEB: HTML, CSS, Javascript
- Experiência com versionamento (Git, SVN)

**Desejáveis:**
- Experiência com module bundlers (Webpack, Gulp, Grunt)
- Experiência com pré-processadores SASS, SCSS, PostCSS
- Experiência desenvolvendo com: React, Preact, ES6
- Experiência com testes em JavaScript

**Diferenciais:**
- Experiência com APIs
- Experiência com C++
- Ter trabalhado com desenvolvimento de lib/framework
- Experiência com a cultura DevOps, CI/CD
- Experiência com Linux

## Contratação

CLT

## Nossa empresa

A Stone é uma empresa de tecnologia que desenvolve produtos para que lojistas recebam o valor das vendas feitas por meio de pagamento eletrônico, seja no mundo físico ou no digital.

Nascemos em 2012. Já fomos uma startup. Hoje, somos uma companhia de mais de 3000 pessoas, unidas por um único sonho: mudar este mercado, trazendo melhores tecnologias, produtos inovadores e um serviço de qualidade para nossos clientes. Nosso propósito é ajudar o empreendedor a empreender no Brasil.

Nosso dia a dia? Ultrapassar limites, aprender muito e transformar potencial em potência. O seu, o da Stone e o dos nossos Clientes.

## Como se candidatar

Por favor, comente nesse issue e envie um email para **vitor.paladini@stone.com.br** com seu CV anexado - enviar no assunto: **Vaga Mamba SDK - Front-end**

## Labels

- Alocado
- CLT
- Júnior
- Pleno
- Sênior

**Comment by raphaelanjos1** [comment]
Oi @vtrpldn, beleza? Estou tentando enviar o CV para o e-mail citado na descrição da vaga, mas algo está errado:

![image](https://user-images.githubusercontent.com/26941113/56463154-d290c480-63a4-11e9-96a4-094581f5d619.png)

Pode me ajudar? Fico no aguardo para encaminhar o CV. 😄

**Comment by ulissestb** [comment]
Opa @vtrpldn , tentei enviar meu CV também. Tive o mesmo problema que o @raphaelanjos1 .

**Comment by vtrpldn** [comment]
@raphaelanjos1 @ulissestb Oi pessoal, boa noite! Corrigi o email, ficou faltando o `.br`.

**Comment by raphaelanjos1** [comment]
Show @vtrpldn! CV enviado. Abs.

**Comment by ymello** [comment]
Enviado :]

**Comment by thallesmarchetti** [comment]
Enviado!

**Comment by vtrpldn** [comment]
Boa tarde, pessoal. Obrigado pelos envios, estamos seguindo com o processo seletivo dos candidatos que entraram em contato.
