### ISSUE TITLE
[São Paulo] Frontend Developer na Legaltech Digesto

### ISSUE THREAD

**Issue by ricardocabral** [frontendbr/vagas#1973]
## Descrição

Estamos crescendo nossa equipe e buscamos desenvolvedores para integrar o time e construir novos produtos focados em dados. Temos vagas de frontend e fullstack para a criação de produtos novos que permitam nossos clientes a extrair mais valor de nossas bases de dados massivas.

## Requisitos

- Angular e AngularJS
- CSS
- Javascript
- Tempo de experiência: 2-4 anos

## Diferenciais

- Plataformas de CD/CI
- Testes unitários web/E2E com Selenium/PhantomJS/Protractor
- Gulp

## Benefícios

- Remuneração acima da média do mercado
- Plano de saúde
- Plano odontológico
- Vale transporte
- Vale refeição
- Ambiente descontraído e ágil

## Outras informações

- Modalidade de trabalho: presencial, em horário comercial
- Local: Pinheiros - São Paulo - SP
- Forma de contratação: CLT

## Como se candidatar

Basta enviar CV e Github/LinkedIn para [nosso formulário](https://docs.google.com/forms/d/e/1FAIpQLSf0UtVEQMxif0L87AmpmLawPe4bddfLqZEYb7BDkNUEWgBJYQ/viewform?usp=sf_link).

## Labels

- CLT
- Júnior
- Pleno
- Sênior
- Angular

**Comment by ReactGirl** [comment]
Vaga de Front end.
Requisitos:
Python.

<img width="155" alt="Screenshot 2019-05-04 at 23 45 27" src="https://user-images.githubusercontent.com/29104515/57185608-b9206a00-6ec6-11e9-84a9-ae244b4cd275.png">
