### ISSUE TITLE
[Remoto] Front-End Developer no [Clube Fii]

### ISSUE THREAD

**Issue by felchs** [frontendbr/vagas#1976]
## Descrição da vaga

Front-End Developer Full-time no Clube Fii https://www.clubefii.com.br
Ofereceremos uma faixa salarial entre R$ 5.000,00 e R$ 8.000,00, dependendo da experiência.

## Local

Remoto 

#### Diferenciais

- monte seu horário com muita flexibilidade

## Requisitos

**Obrigatórios:**
- Dominio de CSS
- Dominio de HTML5
- Dominio de SVG
- Domínio de Javascript / Jquery

**Desejáveis:**
- Domínio de Design Responsível e Cross-Browsing
- Domínio de animação via código
- Domínio de SEO

**Diferenciais:**
- Noções de ASPX
- Noções de Design e de como transferir corretamente o design para o produto final mantendo alinhamentos, tamanhos, distâncias, colunas, tipografia, cores, e elementos no Sketch.
- Desejável que tenha alguma noção do funcionamento do mercado financeiro e de Fundos Imobiliários

## Contratação

PJ a combinar

## Nossa empresa

O Clube FII é o maior site de Fundos Imobiliários do Brasil.  
Precisamos alguém que tenha paixão em design e tem interesse em trabalhar full-time remotamente criando e mantendo o Design System da plataforma assim como todas as suas páginas.

## Como se candidatar

Por favor envie um email para leoehrlich@gmail.com com seu CV anexado - enviar no assunto: Vaga Clube Fii

## Labels

- PJ
- Pleno
- Remoto
- Sênior
- Full Time

**Comment by danielswater** [comment]
Enviado :)
