### ISSUE TITLE
[Remoto] Front-End Developer na MOBDOC

### ISSUE THREAD

**Issue by nilocoelhojunior** [frontendbr/vagas#1978]
## Descrição da vaga

2 vagas para React na Startup MOBDOC  https://mobdoc.com.br/

## Local

Remoto

## Requisitos

**Desejáveis:**
- React Navigation
- Axio
- Next.js
- Redux Saga

**Diferenciais:**
- React-Native

## Contratação

PJ a combinar

## Nossa empresa

A MobDoc é uma central de agendamento de consultas, exames e odontologia que disponibiliza serviços em saúde a preços acessíveis em uma rede credenciada de qualidade.

Chegamos ao mercado de assistência à saúde trazendo mais agilidade, qualidade e transparência no atendimento e marcação de consultas e exames. Somados a uma forte e experiente rede credenciada, já realizamos mais de XXXX procedimentos, oportunizando o acesso a saúde de qualidade a mais de 45 mil pessoas.

## Como se candidatar

Por favor envie um email para curriculo@mobdoc.com.br com seu CV anexado - enviar no assunto: Vaga React

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: daniel@mobdoc.com.br

## Labels

- PJ
- Pleno
- Remoto
- Sênior

**Comment by brunooomelo** [comment]
Enviado!

**Comment by adeonir** [comment]
@nilocoelhojunior alguma oportunidade para junior?

**Comment by nilocoelhojunior** [comment]
@adeonir no momento não

**Comment by dersonsena** [comment]
@nilocoelhojunior a vaga ainda está em aberto ?
