### ISSUE TITLE
[Rio de Janeiro] Front-End Developer no Ministério Público do RJ

### ISSUE THREAD

**Issue by nighto** [frontendbr/vagas#1982]
## Descrição da vaga

Moçada, pintou uma vaga para trabalhar no @MinisterioPublicoRJ no time do [MP em Mapas](http://apps.mprj.mp.br/sistema/cadg). Somos um time multidisciplinar dividido em geografia, estatística, data science e TI para criar soluções utilizadas não só por promotores de justiça mas também pelos governantes e pela população em geral.

Para o backend costumamos usar Python, R e Java (nessa ordem de preferência), e para as soluções de front costumamos usar React, "VanillaJS" e eventualmente Ionic/Angular, e algumas bibliotecas específicas como Leaflet.js, Vis.js e afins.

Precisamos de alguém safo em CSS, acostumado a utilizar Sass ou Less, e claro JavaScript, que se considere pleno para sênior. Seria interessante experiência em testes.

Temos um objetivo de manter um ambiente seguro, inclusivo e diversificado, então essa vaga priorizará candidatas mulheres, pessoas que se identificam como negras, transexuais, homoafetivas e outras minorias, mas está aberta à todos.

## Local

Centro do Rio de Janeiro, mais especificamente: Av. Marechal Câmara, 370 - Castelo - Centro - Rio de Janeiro.

## Benefícios

- R$ 7k bruto, (desconto em folha de IRPF mas não de FGTS);
- ~1200 de auxílio alimentação em $;
- 950 de auxílio saúde em $, após comprovação;
- ~360 de auxílio locomoção em $;
- ~1000 de auxílio educação por filho.

#### Diferenciais

- Regime de trabalho de 8h por dia, contando com a 1h de almoço (na prática, 7h de trabalho);
- Prédio com bicicletário e vestiário. Mas por ser prédio público, não é possível trabalhar de bermuda.

## Requisitos

**Obrigatórios:**
- experiência com JavaScript e React;
- compreender o que acontece quando fazemos uma requisição AJAX;
- ter vontade de fazer sistemas governamentais em código aberto.

**Desejáveis:**
- experiência com testes;
- repositório no Github (acho que todos aqui teriam, né? 😃).

**Diferenciais:**
- participar de comunidades;
- participar de projetos opensource;
- experiência com Vis.js, Leaflet, OpenStreetMap, Canvas.

## Contratação

Vaga fixa, sem tempo determinado, no poder público. Mais detalhes em contato privado.

## Como se candidatar

Por favor envie uma mensagem para [@arlindopereira no Telegram](https://t.me/arlindopereira) com CV e/ou LinkedIn e link do seu GitHub.

## Tempo médio de feedbacks

Vamos analisar as propostas durante a semana entre os dias 29/04 e 03/05 de 2019, e responder todos os contatos até o dia 06/05.

## Labels

- Alocado
- Pleno
- Sênior

**Comment by RenatoAreas** [comment]
Aceita um Jr

**Comment by nighto** [comment]
> Aceita um Jr ??

Infelizmente no momento não.

**Comment by vinculuzX** [comment]
existe algum email para q eu possa mandar o curriculo?

**Comment by nighto** [comment]
> existe algum email para q eu possa mandar o curriculo?

Verifique a seção Como se candidatar.
