### ISSUE TITLE
[Remoto ou São Paulo] Front-end Developer na Atados

### ISSUE THREAD

**Issue by meselfiap** [frontendbr/vagas#1983]
## Descrição da vaga

O Atados é uma plataforma social online que conecta pessoas à oportunidades de voluntariado em causas sociais.

Como funcionamos?
Organizações, movimentos e coletivos sociais anunciam vagas de voluntariado para uma rede de milhares de pessoas interessadas em fortalecer suas ações.

Como existimos?
O Atados tem o propósito de mobilizar pessoas, articular soluções e recursos para impulsionar transformações e fortalecer a atuação de organizações em diversas causas sociais.

O Atados também promove cursos e encontros sobre o universo do Terceiro Setor e realiza ações e eventos de voluntariado.

Para disponibilizar suas ferramentas gratuitamente à rede de voluntários e organizações sociais, o Atados oferece serviços de voluntariado empresarial, gestão e consultoria em responsabilidade social.

Onde atuamos?
Presencialmente, o Atados atua na região metropolitana de São Paulo (SP), Grande Rio de Janeiro (RJ), Brasília (DF) e Grande Florianópolis (SC). E no Brasil inteiro com vagas de trabalho voluntário remoto.

## Local

Remoto ou Escritório, São Paulo - Pinheiros

## Requisitos

**Obrigatórios:**
- React.js
- Redux
- Node.js
- Express
- Stylus (ou algum outro pré-processador CSS)
- ECMA Script 6
- Babel e WebPack

**Diferenciais:**
- projetos opensource
- python

## Contratação

PJ a combinar

## Como se candidatar

Entre [aqui](http://www.frontjobs.com.br/job/90) e se cadastre.

## Labels

- CLT
- Estágio
- Júnior
- PJ
- Pleno
- Remoto
- Sênior

**Comment by danielfelizardo2017** [comment]
Tem vaga remoto para Júnior?

**Comment by meselfiap** [comment]
Sim!

**Comment by juulhao** [comment]
Mandei :)

**Comment by YuriBrunetto** [comment]
Enviado 😄

**Comment by ribeiroevandro** [comment]
Enviado

**Comment by andersonms1** [comment]
Até que dia posso me candidatar? @meselfiap

**Comment by jrquadros** [comment]
Enviado

**Comment by guilouro** [comment]
Enviado

**Comment by brunooomelo** [comment]
vaga backend remoto?

**Comment by brpadilha** [comment]
Opa, ainda tem vaga para estágio remoto?
