### ISSUE TITLE
[São Paulo/SP] Front-End Developer @ Arizona

### ISSUE THREAD

**Issue by raymonsanches** [frontendbr/vagas#1984]
## Descrição da vaga

Responsável pelo desenvolvimento e integração de uma plataforma SPA para organização e evolução de todos os processos de marketing. Trabalhar em conjunto com o backend para entrega da melhor solução e resolução do problema e tendo sempre em mente uma UI fluída e funcional para o usuário.

## Nosso time

Trabalhamos em um time focado em comunicação (síncrona e assíncrona) e estamos sempre experimentando metodologias e feramentas que nos permitam ser sempre mais produtivos e eficazes nas nossas entregas.

Acreditamos em uma cultura de responsabilidade com mais foco nas pessoas e menos nos processos.
Work-life balance. 

## Local

[Escritório na Granja Julieta, São Paulo](https://goo.gl/maps/mewX6ndXLSJ9mb4p6)

## Benefícios

- VR/VA/VT
- Convênio Médico
- Convênio Odontológico
- Horário flexível
- Gympass
- Parceria com SESC
- Seguro de Vida

## Requisitos

- HTML5 
- CSS3
- Material Design, Bootstrap
- Flexbox
- JavaScript (Vanilla)
- React.js 
- Webpack
- Redux
- Versionamento (git) 
- Consumo de API

## Desejável

- Jest
- Chai
- Immer JS
- React i18next
- Redux Observable
- Redux Reselect
- Storybook

## Contratação

CLT 
PJ

## Como se candidatar

Me manda um e-mail para ramon.sanches@arizona.global com seu perfil do Linkedin e "Vaga Front-end" no título e bora trocar uma idéia ;)

## Labels

- PJ
- CLT
- Pleno
- Senior
- São Paulo
- Alocado

**Comment by ribeiroevandro** [comment]
Enviado.
