### ISSUE TITLE
[São Paulo] Desenvolvedor Front-end na AppSimples

### ISSUE THREAD

**Issue by fernandalaghi** [frontendbr/vagas#1986]
## Descrição da vaga

Estamos em busca de um Desenvolvedor Frontend React com pelo menos 2 anos de experiência para atuar em Pinheiros, São Paulo.

O profissional será responsável por realizar tarefas e entregar funcionalidades e telas de forma autônoma, integrando com APIs externas bem como as desenvolver internamente na empresa. Trabalhará em uma equipe multidisciplinar de maneira colaborativa, seguindo metodologias ágeis (Scrum) de forma a entregar produtos de alta qualidade com eficiência.

## Local

O trabalho será desempenhado presencialmente, em nosso escritório, que fica na Rua Butantã, 461 - Pinheiros - São Paulo, SP.

## Benefícios

- VR de R$ 17,50 por dia
- Vale Transporte
- Reembolso de Estacionamento

#### Diferenciais

- Snack's a vontade
- Ambiente descontraído
- Jogos diversos (fazemos pelo menos 1 vez no mês o evento Games & Pizza)
- Gostamos bastante de Confraternizações

## Requisitos

**Obrigatórios:**
- 2 anos de experiência de desenvolvimento com React (Web ou Native)

**Desejáveis:**
- Experiência com React Native
- Experiência com Typescript
- Experiência com serviços da AWS
- Experiência com serviços Google Cloud

## Principais Atividades

- Desenvolvimento de funcionalidades completas React Web
- Desenvolvimento de funcionalidades completas React Native 
- Desenvolvimento com metodologia Scrum, participação de cerimônias

## Contratação

CLT ou PJ (a combinar)

## Nossa empresa

Somos uma Startup focada em desenvolvimento de software e consultoria em inovação. Nossa especialidade é a criação de soluções utilizando aplicativos mobile (híbridos e nativos), aplicativos web e backend.
Para mais informações, acesse nosso site: https://www.appsimples.com.br/

## Como se candidatar

Por favor envie um email para fernanda.laghi@appsimples.com.br com seu CV anexado - enviar no assunto: Vaga Dev Front-end React

## Labels

- Presencial
- CLT
- PJ
- Júnior
- Pleno

**Comment by ribeiroevandro** [comment]
Enviado!
