### ISSUE TITLE
[Curitiba] FullStack Developer Pleno na Zimobi

### ISSUE THREAD

**Issue by douglara** [frontendbr/vagas#1988]
## Sobre nós 

Somos uma startup no mercado imobiliário, uma alternativa para a locação de imóveis sem mobiliaria mas com segurança e transparência.

## Descrição da vaga

Manter e evoluir nossa aplicação que utiliza no back Ruby on Rails e de front React
Implementação de novas features e participar de todo o ciclo de desenvolvimento de produto

## Requisitos

- TDD
- Docker
- React + Redux
- Rails
- TypeScript
- RESTful
- Redis

## Local

Presencial em Curitiba no Centro Cívico.

## Como se candidatar

Por favor envie um email para douglas@zimobi.com.br com seus dados, colocar no assunto: Vaga FullStack Pleno

## Labels

- Alocado
- PJ
- Pleno

**Comment by luqezman** [comment]
Senior aceitam?

**Comment by douglara** [comment]
Fala @luqezman boa tarde, me manda um email com mais detalhes e contato que conversamos sim!
Abss.

**Comment by luqezman** [comment]
Remote? :P

**Comment by douglara** [comment]
Estamos atrás só de presencias por agora :/

**Comment by mikaelhadler** [comment]
Que stack linda, pena que não manjo de rails e redis :/
