### ISSUE TITLE
[São Paulo] Front-End Developer na [MOG Design]

### ISSUE THREAD

**Issue by gabsoft** [frontendbr/vagas#1989]
## Descrição da vaga

Estamos procurando profissionais que estão em busca do primeiro emprego, o primeiro grande desafio para engatar sua carreira profissional da melhor maneira. Venha trabalhar em um ambiente que permite que o futuro programador possa extrair o melhor de si, e contribuir com grandes projetos que impactam clientes na América Latina inteira, vendo o fruto do seu trabalho impactar milhões de clientes distribuídos pelo continente.

## Local

Escritório, São Paulo - Campo Belo

## Benefícios

- VT

## Requisitos

**Obrigatórios:**
- Estar estudando algum curso relacionado a área de tecnologia 
- Conhecimentos básicos de HTML, CSS, Javascript e Jquery
- Noções teóricas de frameworks de JS (Node, Angular)
- Noções teóricas de programação orientada a objetos

**Diferenciais:**
- Caso você ja tenha algum projeto feito em GitHub ou TFS, será considerado como um diferencial.

## Contratação

Estágio

## Nossa empresa

O estúdio Mog existe desde 1997 em São Paulo, nosso foco sempre foi atender o cliente nas áreas de design e campanhas publicitárias.
Alguns anos depois, desenvolvemos nosso próprio software de conteúdo para digital signage (DS): o Communiquè.
Ele surgiu da necessidade do mercado por uma solução de comunicação integrada em sinalização digital; eliminando o alto custo de impressão e a demora logística de materiais físicos.

## Como se candidatar

Por favor envie um email para gabrielalmeida@mrocket.com.br com seu CV anexado - enviar no assunto: Estágio Front-End Developer

## Labels
- Estágio

**Comment by ericcoutinho** [comment]
Valor da bolsa de estágio?

Em ter, 30 de abr de 2019 17:58, gabsoft <notifications@github.com>
escreveu:

**Comment by MrRosario** [comment]
Tem vaga pra programador Junior?

**Comment by dmchiodini** [comment]
Olá, qual o valor da bolsa?

**Comment by gabsoft** [comment]
> Tem vaga pra programador Junior?

No momento apenas Estágio mesmo.

**Comment by gabsoft** [comment]
> Olá, qual o valor da bolsa?

Valor negociável, caso tenha interesse de participar do processo nos mande seu Curriculo.
