### ISSUE TITLE
[Curitiba] Front-End Developer PL / SR na [commcepta]

### ISSUE THREAD

**Issue by commcepta** [frontendbr/vagas#1991]
** // Atividades e Responsabilidades**
Consideramos trabalhar com tecnologia um grande desafio. A tecnologia está em constante mudança e nós também. Estamos buscando pessoas que amem o que fazem. 
Trabalhar em equipe também é importante, afinal troca de ideias é fundamental para projetos inovadores.

**// Qual o desafio que propomos?** 
- Estar sempre em busca de novos desafios e tecnologias 
- Compartilhar conhecimentos com a equipe 
- Ser minucioso com os detalhes 
- Enfrentar códigos "cabeludos" e transformar em códigos perfeitos 
- Não vai deixar escapar um ponto e vírgula além de manter o padrão de indentação

** // Requisitos**
Vaga exclusiva para profissionais especializados e focados em Front-End.
Experiência com HTML5, CSS3 (Sass), fluência com frameworks de Front-end (AngularJS, Vue.js ou ReactJS) e customização em WordPress. 
Ter fluência em convenções e padrões de experiência de usuário (UX), responsive design e base de inglês. Trabalhamos com ambiente MacOS.

** // O que nós oferecemos**
- Vale Refeição

Café à vontade 
Equipe talentosa e divertida 
Sextas à partir das 17:00 tá liberado sua cerveja!

**Comment by felipefialho** [comment]
Posta no @backend-br :)

**Comment by commcepta** [comment]
Desculpe, é Front-end mesmo. Chamada corrigida. Obrigada.

**Comment by mikaelhadler** [comment]
Pelo amor de deus, deveriam ter vergonha de postar uma vaga destas.

**Requisitos**
Vaga exclusiva para profissionais especializados e focados em Front-End.
Experiência com HTML5, CSS3 (Sass), fluência com frameworks de Front-end (AngularJS, Vue.js ou ReactJS) e customização em WordPress.
Ter fluência em convenções e padrões de experiência de usuário (UX), responsive design e base de inglês. Trabalhamos com ambiente MacOS.

**O que nós oferecemos**
 - Vale Refeição

Sinceramente falando, o mínimo esperado para um de benefícios para um pleno Pleno ou Sênior
- **Plano de saúde**
- **Vale alimentação**
- **Vale transporte**

Em pleno 2019 temos que ver vagas como esta, se ta loco...
