### ISSUE TITLE
[Belo Horizonte] Front-End Developer na StudioSol

### ISSUE THREAD

**Issue by laryssamagalhaes** [frontendbr/vagas#1992]
## Descrição da vaga
Buscamos profissionais de todos os níveis: Junior, Pleno, Sênior e Estágio. 

Procuramos pessoas focadas, bem humoradas, que conseguem aprender rápido e estejam por dentro das tendências de tecnologia.

Construir interfaces rápidas e responsivas com foco em performance e experiência do usuário. React, Sass, Typescript, GraphQL, APIs REST, CSS Modules são alguns recursos utilizados.

## Local

Presencial, Belo Horizonte - Savassi

## Benefícios

**Estágio e CLT:** vale-transporte | **CLT:** VR de R$ 26,00 / dia + Unimed após 3° mês.

## Requisitos

**Obrigatórios:**
- Boa lógica de programação;

- Organização e proatividade;

- Estar por dentro das tendências de tecnologia;

- Ter muita disposição para aprender;

- Inglês técnico;

**Desejáveis:**
- React 
- Sass
- Typescript
- GraphQL
- APIs REST, 
- CSS Modules

## Contratação

 **Estágio:** manhã ou tarde | **CLT:** 8h às 17h, de segunda a sexta;

**Salário:** Estágio: bolsa a partir de R$ 1.000,00 para 25h semanais ou a partir de R$ 1.200,00 para 30h semanais | CLT: a combinar;

## Nossa empresa

Fundada em Belo Horizonte, em 2000, por Sam Vignoli e Gabriel Fernandes, a Studio Sol é proprietária do Cifra Club, Palco MP3 e Letras.mus.br. 
Também faz o Guitar Battle, Fórum Cifra Club e Forme Sua Banda.

Somos a empresa brasileira líder em download de aplicativos e Top Developer na Google Play.

## Como se candidatar

Por favor acesse o link https://www.studiosol.com.br/desenvolvedores/, realize o cadastro inicial e a prova online.

## Labels

- Alocado
- CLT
- Estágio
- Júnior
- Pleno
- Sênior

**Comment by gustavoborboleta** [comment]
Currículo enviado, no texto informei sobre morar no Rio, mas estarei em BH na próxima segunda.

**Comment by HaluDeCassia** [comment]
@laryssamagalhaes não existe nenhuma possibilidade de trabalhar full remoto? A vaga é muito bacana, mas abrindo essa possibilidade acredito que haverá bem mais possíveis candidatos (eu mesma, por exemplo)

**Comment by laryssamagalhaes** [comment]
Ei @HaluDeCassia, no momento nossas vagas são apenas presenciais. Quem sabe no futuro não abrimos vagas remotas :)

**Comment by HaluDeCassia** [comment]
@laryssamagalhaes que pena. Fica pra outra oportunidade. Muito obrigada.
