### ISSUE TITLE
[Faria Lima - SP] React Native para Produto por 5 meses 

### ISSUE THREAD

**Issue by oVerde** [frontendbr/vagas#1993]
## Descrição da vaga

Estamos precisando de quatro Desenvolvedores para um novo produto em React Native, para Android e iOS. Já possuímos todo layout das telas e fluxos bem definidos.
Trata-se de um aplicativo/plataforma de assinatura mensal (para os pais) onde é possível gerenciar e agendar cerca de 200 atividades (com diversos parceiros) para as crianças, de maneira prática, simples e segura.
Os profissionais poderão trabalhar juntos dividindo tarefas entre UI, Firebase e NodeJS.

Site do projeto:
https://kiddlepass.com.br/
Vídeo Institucional do projeto: 
https://drive.google.com/file/d/1L_cPSmSiQgyoFflTlGPH8LuPd04_ieho

## Local

Presencial das 10h as 19h, Pinheiros ao lado do Metrô Faria Lima.

#### Diferenciais

- Você trabalhará no escritório da CROWD, local totalmente tranquilo e sem estresse

## Requisitos

**Obrigatórios:**
- React native
- Firebase
- Nodejs

**Desejáveis:**
- Conhecimentos em NoSQL e SQL para migrar uma base de dados
- Comprometimento

## Contratação

PJ através da plataforma CROWD, precisa emitir nota.

## Propósito da Kiddle Pass

Integrar crianças às atividades culturais, físicas, educacionais e de lazer, de modo a prover um universo de possibilidades, onde se pode aperfeiçoar habilidades, descobrir talentos e identificar novas paixões. Para uma vida mais ativa, com mais motivação, conhecimento e diversão.

## Como se candidatar

Por favor envie um email para natalia@crowd.br.com e verde@crowd.br.com com seu CV e projetos anteriores anexados - enviar no assunto: Vaga Kiddle Pass

## Tempo médio de feedbacks

Enviaremos feedbacks em até uma semana.

## Labels

- Alocado
- Freela
- PJ
- Pleno
- Sênior

**Comment by gabrielsimas** [comment]
Que Projeto rapaz! Que Projeto!

**Comment by MrS4w** [comment]
Vaga não atende aos requisitos do repositório.

**Comment by oVerde** [comment]
> Vaga não atende aos requisitos do repositório.

Era o nome da empresa no título?

**Comment by MrS4w** [comment]
@oVerde como você pode ler [aqui](https://github.com/frontendbr/vagas#vagas-somente-vagas-de-front-end), a vaga se encaixa como desenvolvedor mobile.
