### ISSUE TITLE
[São Paulo] Front-end Developer na CrediHome

### ISSUE THREAD

**Issue by Andreia-Marques** [frontendbr/vagas#1995]
**Descrição da vaga**
Estamos com uma oportunidade para Desenvolvedor React JS na Credihome, uma startup de crédito imobiliário que esta em um mercado de R$ 60 bi, um dos maiores do Brasil.
O ambiente é bem dinâmico com várias Startups, além de dividir muro com o Parque Ibirapuera.

**Local**
Escritório, São Paulo - Moema

**Benefícios**
 - Não

**Diferenciais**
- Próximo ao Parque Ibirapuera

**Requisitos**

**Obrigatórios:**
- Javascript
- ReactJS
- CSS

**Diferenciais:**
- Conhecimentos em SASS e Redux

**Contratação**
- PJ de R$4 a R$6 (dependendo da experiência)

**Nossa empresa**
Credihome, uma startup de crédito imobiliário que esta em um mercado de R$ 60 bi, um dos maiores do Brasil.

**Como se candidatar**
Por favor envie um email para am@individuals.io com seu CV anexado - enviar no assunto: Vaga React JS Developer na CrediHome (Jr/Pleno)

**Labels**
alocação/Presencial
experiência/Júnior
experiência/Pleno
regime/PJ
remuneração/4k-10k

**Comment by ReactGirl** [comment]
Benefícios: Não

**Comment by HaluDeCassia** [comment]
Existe possibilidade de full remoto?
