### ISSUE TITLE
[Rio de Janeiro/São Paulo] Front-end Engineer Somos Educação

### ISSUE THREAD

**Issue by keppelen** [frontendbr/vagas#1998]
## Descrição da Vaga
Nós nos preocupamos com o que você entrega e não como você se veste. Pessoas criativas, ambiente dinâmico, horário flexível... Dá uma olhada aqui como é trabalhar na [Somos Educação](https://www.linkedin.com/company/somoseducacao/), uma empresa [comprada](https://www1.folha.uol.com.br/mercado/2018/10/kroton-conclui-compra-do-controle-da-somos-educacao.shtml) pela [kroton](https://www.linkedin.com/company/kroton-educacional-s-a/life/) :)

Estamos procurando engenheiro(as) front-end apaixonado(a)s para nos ajudar a melhorar a educação no Brasil.

A somos tem vários produtos, mas a vaga é para trabalhar no time digital, especificamente no produto Plurall
- https://www.linkedin.com/company/plurall
- https://www.instagram.com/digitalsomos

Com grandes poderes vêm grandes responsabilidades e para se juntar ao nosso time, você vai lidar com essas coisas no dia a dia:

- Programação Front-end (SPA) que comunicam com API (Rest e GraphQL) 
- Metodologias de desenvolvimento ágil
- Mobile First
- Componetização da Biblioteca de Design Sytem (React + Emoction + NPM/Yarn) (9 aplicações usando os componentes)

Valorizamos muito a capacidade de aprendizado, mas precisamos de alguém que já tenha uma certa experiencia com essas coisinhas abaixo:

- JavaScript (vanilla)
- React
- HTML e CSS
- NPM (usamos para pacotes internos privados/públicos)
- Ter opinião na hora de planejar/arquitetar features/soluções

Estas aqui são nice to have:
- Noções de UX/UI
- Angular *(as vezes temos que resolver algo no sistema de account)*

### Local
A vaga é presencial, podendo ser no escritório do Rio de Janeiro (Preferencial) ou de São Paulo

- [Rio de Janeiro (Rua Visconde de Pirajá, 142 - Grupo 304 - Ipanema)](https://goo.gl/maps/6A3cKfKas8391drz5)
- [São Paulo (Av. das Nações Unidas, 7221 - 2º Andar - Setor B - Pinheiros)](https://goo.gl/maps/w9DCfEYN6bz43AZW8)

### Beneficios
- Salário compatível com mercado;
- Vale Refeição (R$ 27/dia);
- Vale transporte;
- Plano de Saúde;
- Plano Odontológico opcional;
- Home Office;
- Ambiente de trabalho descontraído e confortável;

**OBS: Incentivamos e temos rotatividades em projetos diferentes para disseminar o conhecimento do time.**

## Para se candidatar
https://epartner.vagas.com.br/PagVagaDirSS.asp?v=1889613&pp=https%3A//epartner.vagas.com.br/GoHome.asp%3Fv%3D1889613%26j%3Dt%26sslon%3D1&wiw=1628

**Comment by JonasEmanuel** [comment]
Enviado

**Comment by JonasEmanuel** [comment]
Estão aceitando Pleno?

**Comment by keppelen** [comment]
@JonasEmanuel estamos buscando pessoas boas independente do nivel tecnico. Se a pessoa tiver um pouco do que queremos e gostarmos do perfil, a gente pode/quer treinar a também a pessoa :)

**Comment by JonasEmanuel** [comment]
Mandei meu currículo.

**Comment by Joaovsa7** [comment]
Enviado! sou Júnior, e gostei deste comentário haha

> @JonasEmanuel estamos buscando pessoas boas independente do nivel tecnico. Se a pessoa tiver um pouco do que queremos e gostarmos do perfil, a gente pode/quer treinar a também a pessoa :)

**Comment by renatolinsjr** [comment]
Enviei meu currículo!

**Comment by keppelen** [comment]
Boa, recebi vários aqui :) - Na próxima semana irei olhar e entrar em contato com vocês para os próximos passos. 

ps: quem se interessou e não mandou, podem continuar a mandar, vou olhar todos 👊

**Comment by adeonir** [comment]
Gostei da vaga, pena que é só presencial.

**Comment by danielsidev** [comment]
Enviado!

**Comment by guibfo** [comment]
@keppelen já que vocês também estão querendo treinar alguém, será que rolaria uma vaga de estágio pra alguém com conhecimento básico de HTML/CSS/Javascript?

**Comment by keppelen** [comment]
opa, @guibfo infelizmente no momento para estágio não temos. Mas assim que souber de algum eu posto aqui blz?

**Comment by 9imeio** [comment]
@keppelen ainda estou em graduação, mas procuro vagas com foco em Jr. Estarei te mandando um e-mail. Gostei da empresa :)

**Comment by felipenoka** [comment]
Enviado! 😄 
> @JonasEmanuel estamos buscando pessoas boas independente do nivel tecnico. Se a pessoa tiver um pouco do que queremos e gostarmos do perfil, a gente pode/quer treinar a também a pessoa :)

**Comment by emanuelgsouza** [comment]
Olá! A vaga ainda está aberta?
