### ISSUE TITLE
[São Paulo] FullStack Developer na AGÊNCIA DIGI

### ISSUE THREAD

**Issue by flaviomacias18** [frontendbr/vagas#1999]
## Sobre a Agência Digi

Parte do Grupo Digi, a Agência Digi é reconhecida em seu mercado pelos grandes e exigentes clientes que a procuram para criar, planejar, desenvolver e manter seus canais de comunicação internos e externos baseados em tecnologia e inovação.

## Descrição da vaga

Buscamos um profissional pró-ativo, dinâmico, com espirito de equipe e comprometido com prazos e datas de entregas.

## Requisitos

- VueJs 2
- Javascript ES6;
- Consumo de Rest APIs;
- Experiência mínima de 2 anos com algum framework como: Vue, Angular, React, Ionic;
- WEBPACK
- HTML, CSS, SASS;
- Git;
- Ter desenvolvido projetos com integração via API

## Diferenciais

- C#
- SQL Server
- Node.Js;
- Conhecimentos em Vuex

## Local

Av. Brigadeiro Faria Lima, Pinheiros - São Paulo/SP

## Contratação

PJ (salário a combinar)

## Como se candidatar

Por favor envie um email para flavio@digi.ag com seu CV anexado - enviar no assunto: Vaga Vue.js

## Labels

- pj
- pleno
- senior
- home office

**Comment by luqezman** [comment]
Qual a faixa salarial média?
