### ISSUE TITLE
[São Paulo] Desenvolvedor Front-End Sênior

### ISSUE THREAD

**Issue by luisfontes** [frontendbr/vagas#20]
## Descrição da vaga

A posição é para um Front-End Lead na GlutenFree Box, responsável direto pelo desenvolvimento do produto.

Estamos construindo um produto que acreditamos ser a evolução de um clube de assinatura e de um ecommerce. Essa posição é de alguém que irá encabeçar o desenvolvimento desse produto, trabalhando em conjunto com o resto da equipe para garantir a melhor UX/UI ao nosso consumidor.

Trabalhamos com uma stack moderna (no front: Angular 1.5 c/ ES6, postcss c/ SUITCSS e webpack) e seguimos as melhores práticas em desenvolvimento (padrões de código, styleguides, testes, CI/CD, etc.) e há liberdade para explorar e testar novas tecnologias. Fundamental ter muita vontade de aprender e autonomia para garantir uma entrega de qualidade.

## Local

Presencial em São Paulo, região da Barra Funda (Zona Oeste).
Walking distance da estação Barra Funda (Metrô/CPTM)

## Requisitos

- Experiência com SPA (Angular ou React) com projetos já realizados.
- Domínio em CSS (pré-processadores, cross-browsing, flexbox, animações)
- Preocupação com código limpo, bem escrito e documentado.

Diferenciais:
- Testes (Karma, Jasmine, Mocha + chai, protractor)
- Técnicas de otimização para web
- Conhecimento de APIs RESTful
- Tracking de eventos

## Contratação

Fulltime, CLT (ou PJ caso preferir)

## Benefícios

- Vale refeição
- Horário flexível
- Snacks sem glúten à vontade :stuck_out_tongue: 

## Nossa empresa

Somos a GlutenFree Box, um clube de assinatura de alimentos sem glúten e o maior clube de assinaturas de alimentos do Brasil. Estamos com 1,5 anos de existência e recentemente recebemos um aporte de um fundo de venture capital para construir uma nova empresa que irá revolucionar o mercado de alimentação saudável.

Na parte digital vamos construir um novo produto que é a evolução do modelo de clube de assinatura: uma plataforma de "ecommerce" com recorrência. Onde você pode escolher todos os produtos que você gostaria de receber na sua casa todo mês de acordo com suas restrições ou preferências alimentares. É algo inovador, não tendo nenhuma empresa no Brasil ou no mundo que faça algo do tipo.

Queremos ser a melhor solução para aqueles que querem se alimentar melhor e de uma maneira mais prática. A GlutenFree Box foi o começo e muito mais está por vir.

## Como se candidatar

Envie seu CV com github ou materiais de suporte para [luis@glutenfreebox.com.br](mailto:luis@glutenfreebox.com.br)

**Comment by eduardojmatos** [comment]
@luisfontes coloquei Sênior como label, está correto?

**Comment by luisfontes** [comment]
Sim @eduardojmatos, obrigado!

**Comment by luisfontes** [comment]
Vaga preenchida por alguém que achou ela por aqui, obrigado!

**Comment by LFeh** [comment]
\o/, sensacional

**Comment by camilatigre** [comment]
@luisfontes 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by luisfontes** [comment]
A

**Comment by camilatigre** [comment]
Aee! Que legal. Obrigada por responder e ajudar.

Em 24 de nov de 2016 10:04, "Luis Fontes" <notifications@github.com>
escreveu:
