### ISSUE TITLE
[São Paulo] Desenvolvedor Front-end na Arizona

### ISSUE THREAD

**Issue by airtonzanon** [frontendbr/vagas#200]
## Descrição da vaga

- Desenvolver Single Page Applications 
- Desenvolver um sistema interativo e com qualidade. 
- Escrever um código limpo e que funcione em todos os browsers. 
- Seguir todas as recomendações dos guias de código. 
- Desenvolvimento voltado a usabilidade. 
- Garantir que o sistema tenha alto desempenho. 
- Criar as funcionalidades de acordo com as requisições do cliente. 
- Estimar o tempo para entregar um determinado trabalho.  
- Desenvolver teste unitários (desejável)

## Local

Escritório - Rua Castro Verde - 98 - Chácara Santo Antônio - São Paulo/SP

## Benefícios

- Van do Carrefour Granja Julieta ao trabalho
- VA / VR / VT

## Requisitos

 **Desejáveis:**
- HTML5 
- CSS3 ( RESPONSIVE LESS SASS ) 
- TWITTER BOOTSTRAP 
- JAVASCRIPT 
- JAVASCRIPT LIBS - JQUERY 
- CONTROLE DE VERSAO ( GIT ) 
- REST API ( JSON ) 
- Experiência com algum framework JS MV* 

**Diferenciais:**
- PERFORMANCE TUNING 
- Design/UX

## Contratação

CLT a combinar

## Nossa empresa

Conheça mais sobre a empresa no vídeo institucional - https://www.youtube.com/watch?v=QYuvvCYoJO4

## Como se candidatar

Por favor envie um email para ivan.rosolen@arizona.global com seu CV e Github anexado - enviar no assunto: Vaga Front-End Pleno ou Vaga Font-End Junior

**Comment by airtonzanon** [comment]
Poderiam adicionar as Labels - [Pleno] Pleno / [Junior] Junior / [CLT] CLT fazendo favor?

**Comment by airtonzanon** [comment]
[Pleno]

**Comment by LFeh** [comment]
Maneiro. As labels estão certas?

**Comment by airtonzanon** [comment]
Opa, bom dia @LFeh no caso seria Pleno e Junior, do resto está certinho \o/

**Comment by jcdourado** [comment]
Enviado 😄

**Comment by worldvini** [comment]
Olha que top, estou começando a fazer testes unitários agora, tanto em paginas web como em aplicativos híbridos. 

Mas ainda preciso cumprir 2 meses de estágio para a faculdade liberar, se não fosse isso =)!

**Comment by airtonzanon** [comment]
Pessoal, to fechando esta vaga pois precisaremos de um Sênior agora.

**Comment by LFeh** [comment]
Só abrir :)
