### ISSUE TITLE
[Joinville] Front-End Developer Junior na Gofind

### ISSUE THREAD

**Issue by lohmann** [frontendbr/vagas#2004]
## Descrição da vaga

Buscamos desenvolvedores que queiram inovar de verdade. Pessoas com espírito de desafio e força necessários para nos ajudar a crescer em ritmo acelerado.

A arquitetura da nossa aplicação é baseada em Serverless, e utilizamos extensivamente serviços e ferramentas da AWS e Google Cloud. Nosso front-end foi desenvolvido em REACT e AngularJS.

Na **Gofind** você terá oportunidade de trabalhar com:
- Progressive Web Applications
- Inteligência artificial e Machine Learning
- Integração com API's de terceiros (Facebook, Google, etc)
- etc

## Benefícios

- Salário compatível com o cargo e sua experiência
- Plano de Saúde
- Vale Alimentação
- Vale Transporte
- Convênio com farmácia
- Reembolso de Medicamentos

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento web
- Bom conhecimento de JavaScript e CSS
- Conhecimento básico de REACT

**Desejáveis:**
- Experiencia com Node.js
- Conhecimento básico de Linux
- Conhecimento básico de Git e ferramentas de CI/CD

**Diferenciais:**
- Conhecimento básico sobre arquitetura Serverless
- Projetos publicados no GitHub

## Contratação

Full-time, CLT

## Local

Joinville/SC (presencial)

## Como se candidatar

Enviar um email para recruta@gofind.online - assunto: Vaga Front-End

**Comment by pdrgds** [comment]
Rola remotamente?
