### ISSUE TITLE
[São Paulo, Floripa, Joinville] Fullstack Engineer na Resultados Digitais

### ISSUE THREAD

**Issue by kaiofelipejs** [frontendbr/vagas#2006]
## Descrição da vaga

Trabalhar num projeto novo e muito desafiador: criar uma ferramenta interna de _behavior tracking_ que substitua o Google Analytics dentro do nosso principal produto, o [RD Station Marketing](https://www.youtube.com/watch?v=p4nMHdhlFcQ).
_(A gente avisou que era desafiador!)_ 
Isso será feito pela coleta de informações do comportamento dos usuários, e vai exigir muito conhecimento de desenvolvimento web, JavaScript (React e Node) e das particularidades dos diferentes browsers que existem no mercado, usados em diferentes plataformas.

#### Com quem você irá trabalhar:
Esse é um time novo e que, a princípio, será formado por duas pessoas bastante experientes. Essa squad está dentro da estrutura de “Data” do RD Station, e tem muita proximidade com a equipe de [BI e Data Visualization](https://www.rdstation.com/relatorios-personalizados/).
Em geral, os times aqui têm uma pessoa team leader, que é responsável por acompanhar entregas e direcionar o desenvolvimento de carreira das pessoas; e um(a) PM, que passa as demandas para desenvolvimento conforme a estratégia macro dos produtos. Todas essas pessoas têm background técnico!

Além disso, utilizamos métodos ágeis como Scrum, Kanban e XP. Somos adeptos a TDD (test-driven development) e usamos Circle CI para integração contínua (com 95% de coverage!) tudo integrado via Slack. Todo PR (pull request) passa por code review e também fazemos pair programming para compartilhar conhecimentos e melhores práticas. Se você quiser conhecer toda a nossa stack e saber tudo o que usamos, veja o nosso [stackshare](https://stackshare.io/resultados-digitais/rd-station).

## Local

- São Paulo - Vila Olímpia
- Florianópolis - Monte Verde
- Joinville - Centro

**Você que escolhe!** 

## Benefícios
- RDiscount - rede de descontos em diferentes lojas, cinemas e restaurantes;
- Gympass;
- Plano Odontológico;
- Plano de Saúde - sem nenhum custo pra você e dependentes;
- VA ou VR - R$513,00 mensais

#### Diferenciais
- Home office alguns dias na semana;
- Cultura de feedback e desenvolvimento 
- Sala de jogos;
- Snacks todo dia no office;
- Fazer parte de uma das [Linkedin Top Companies](http://bit.ly/RDehtop) - uma das 25 empresas em que os brasileiros mais sonham em trabalhar;
- Aprender e trabalhar diariamente com profissionais referência no mercado;
- Cursos e certificações da RD University (nossa universidade corporativa) para você explorar.

## Requisitos

**Obrigatórios:**
- Boa experiência com desenvolvimento web e amplo conhecimento sobre as particularidades de diferentes navegadores (Chrome, Firefox, Safari, Opera, etc.) de diversas plataformas.
- Conhecer bastante de JavaScript e seus frameworks/libs mais populares como React, Node.
- Transitar bem entre arquitetura e desenvolvimento e curtir fazer coisas completamente novas e diferentes.

**Diferenciais:**
- Já ter trabalhado com feature/produto de behavior tracking

## Contratação

CLT a combinar

## Nossa empresa

A RD nasceu no Brasil, em 2011, com o objetivo de ajudar empresas de todos os portes e segmentos a entender e a aproveitar os benefícios do marketing digital, conquistando resultados reais e efetivos para seus negócios.
- Já são mais de 12k clientes em quase 30 países
- Somos um dos principais cases de SaaS B2B no Brasil
- Temos escritórios na América Latina e Europa
- GPTW: são 4 anos consecutivos como uma das melhores empresas para se trabalhar no Brasil
- Criamos o [RD Summit](https://rdsummit.com.br/), maior evento de Marketing Digital e Vendas da América Latina
- Já somos +650 pessoas (RDoers)!
No nosso [Culture Code](https://resultadosdigitais.com.br/blog/culture-code-rd/) você pode checar os nossos valores e no [blog](https://medium.com/rd-shipit) como trabalhamos no dia a dia.

## Como se candidatar

Entre em https://grnh.se/73ebcf9c2 e dale! :)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada etapa. Se tivermos algum problema e for atrasar, iremos lhe avisar! 
E-mail para contato em caso de não haver resposta: tech-hiring@resultadosdigitais.com.br

## Labels

- Alocado
- CLT
- Sênior

**Comment by HaluDeCassia** [comment]
@kaiofelipejs não rola full-remoto? Teria pra pleno? Essa vaga é muito bacana.
