### ISSUE TITLE
[São Paulo] Front-End Developer na Media Trade

### ISSUE THREAD

**Issue by RHMediaTrade** [frontendbr/vagas#2009]
![analista-de-front-nova-data](https://user-images.githubusercontent.com/50459172/60191001-fab7fc00-9809-11e9-9022-82da68397089.jpg)

Estamos com uma oportunidade para Analista de TI - Front-end, desenvolvimento web.

## Descrição da vaga

**Atividades:**

-  Criação de novos módulos e aplicação de regras de negócio;
-  Manutenção e aperfeiçoamento dos módulos VueJS existentes;
-  Integrações REST API;
-  Integrações com PLUGINS de terceiros.

## Local

 Rua Claudio Soares, 72 - Faria Lima – São Paulo/SP (ao lado da estação Faria Lima de metrô). 

## Requisitos

**Obrigatórios:**

- Cursando o último semestre de ensino técnico ou superior, ou que já tenha concluído (cursos de TI
- JSON, HTML 5, CSS 3, SASS, JavaScript e jQuery;
- Controladores de versão (Git, SVN, BitBucket)

**Desejáveis:**

-  VueJS;
-  Habilidade/facilidade para criação de interfaces e layouts amigáveis.

**Idiomas:**
-  Inglês (nível básico)

## Contratação

PJ a combinar

## Nossa empresa

A Media Trade é uma Startup Brasileira fundada para desenvolver soluções em tecnologia para Publicidade e Propaganda, criando ferramentas modernas e práticas para compra e venda de mídia, além de inúmeros serviços inerentes aos processos fundamentais no setor.

Ajudamos Anunciantes a terem suas campanhas divulgadas nos lugares certos para o seu público alvo com precisão, através das melhores mídias, formatos e da maneira mais econômica do mercado.

Aos Veículos de mídia oferecemos clientes e negócios de alta qualidade, do Brasil e também internacionalmente através de uma parceria prática, transparente e duradoura.

As plataformas Canal do Anúncio (Anunciantes) e Canal do Mídia (Agências) reúnem todos os meios de comunicação em um único sistema, são ambientes online que permitem Busca, Plano, Compra e Execução de mídia otimizando ao máximo tempo e dinheiro, ativos essenciais para todas empresas. Nossas interfaces permitem também uma gestão simples, mas detalhada de todas as operações, garantindo controle e visibilidade necessários para boas práticas de Marketing e Compliance.

A equipe Media Trade está organizada em áreas como Sucesso do Cliente, Portfolio de Mídia, Marketing, TI (Suporte, Web Dev e KDD), Administrativo, Recursos Humanos, Financeiro, Jurídico e Desenvolvimento de Negócios, contando com profissionais de primeira linha para oferecermos o melhor serviço possível.

## Como se candidatar

Pode se candidatar pelo nosso Site institucional: https://themediatrade.com/trabalhe-conosco ou envie um email para rh@canaldoanuncio.com com seu CV anexado - enviar no assunto: Vaga Front End

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@canaldoanuncio.com

## Labels

- Alocado
- PJ
- Pleno

**Comment by HaluDeCassia** [comment]
@RHMediaTrade não existe possibilidade de ser full remoto? A vaga é bem bacana, e acredito que com contrato PJ é uma boa abertura para mais candidatos (eu mesma me candidataria para a vaga se houver essa chance)

**Comment by RHMediaTrade** [comment]
@HaluDeCassia até temos a possibilidade de trabalho remoto, porém não full... contrato PJ é uma possibilidade sim, mas não podemos abrir como full remoto neste momento
