### ISSUE TITLE
[Florianópolis/SC] UI Architect 

### ISSUE THREAD

**Issue by VanessaAlbuquerque** [frontendbr/vagas#2012]
## Job Description
(experienced in headless commerce architecture)

Deep understanding of web service technologies (HTTP, REST, JSON) and design principles.
Knowledge in JavaScript Design & Architectural Patterns.
Familiarity with consuming service-oriented architecture layers and APIs.
Experience with highly scalable applications.
Proficiency in integration with Web Application systems and technologies (like Maven,  Eclipse/NetBeans/IntelliJ, Spring/Guice, JPA/Hibernate).
Ability to research and adopt new technologies quickly in a very dynamic working environment; Familiarity with OWASP security; Experience of headless commerce implementation
Projeto bazinga em NodeJS, etc.

## Local

Escritório Florianópolis

## Benefícios

- Plano de saúde
- Plano Odontológico
- VR e VT
- Ambiente incrível para trabalhar

## Qualifications

Experience on the following core languages: JavaScript, HTML 5 & CSS.
Strong skills in programming structures, algorithms, design patterns, standard (W3C) Web UI APIs.
Oriented to details and software best practices & patterns.
Knowledge in the following types of frameworks/libraries/languages:
Web Application Platforms
UI Component libraries React, ReactUI, JQuery,
ES6+.
TypeScript.
Dependency Injection patterns.
Async Module Definition (like AMD, requireJS, commonJS).
Stylesheet languages (like SASS, LESS).
Application state management (like Redux).
Reactive Programming (like RxJS)
Minification, Aggregation, and Fingerprinting (Gulp/Grunt)
Node (NPM)
Server-Side Rendering (like Express)
UI development using Swagger
Platforms:
NoSQL (MongoDB, Cassandra, Redis).
Running Java Application Servers (Oracle WebLogic, JBoss, Tomcat).
Testing frameworks (Jasmine, Karma, Protractor).
Docker & Kubernetes
 
Other:
Cross-browser techniques.
Debugging with tools like (Chrome Dev Tools, Web Inspector).
Responsive design implementation across devices, platforms, screens, etc.
Browser performance auditing and tuning.
Demonstrated skills using distributed code repositories (Git, Perforce, BitBucket) with code reviews.
Experience working within Scrum / Kanban.
Web Accessibility

## Contratação

CLT

## Company Description

McFadyen Digital is a global Digital Commerce Agency with a 30-year history of innovation for more than 250 of the world’s top brands. We deliver digital commerce, marketplace, digital marketing, and user experience services from our offices in North America, South America, and India. Across all practices, we help our clients reach their goals by ensuring that technology is implemented strategically and adopted in a way that meets their business objectives. 

Learn more about us at our website: www.mcfadyen.com

## Como se candidatar

http://smrtr.io/384YN

## Tempo médio de feedbacks

Less than a week

## Labels

- CLT
- Sênior

**Comment by mikaelhadler** [comment]
Essa misturada de PT - EN :s, por que não tudo em inglês ou tudo em português ?!
