### ISSUE TITLE
[PORTUGAL] Front-End / Full-Stack 

### ISSUE THREAD

**Issue by CassiusHorvath** [frontendbr/vagas#2013]
Recebi uma avalanche de emails os quais já encaminhei para o RH. Vou aguardar a resolução destes e depois posto mais informações.

Obrigado

**Comment by CassiusHorvath** [comment]
Pessoal, obrigado por mandarem seus CV's. Vou torcer por vocês. Vou aguardar o resultado desse pessoal que me mandou agora.
Boa sorte a todos.

**Comment by raloliver** [comment]
Wow! Vlw... recebi uma ligação hoje <3
