### ISSUE TITLE
[Porto Alegre, RS] Brasil Front-End Developer na Todo Cartões

### ISSUE THREAD

**Issue by thomashs** [frontendbr/vagas#2016]
Vaga para profissionais de PORTO ALEGRE, RS
(com possibilidade de trabalho remoto)

**Detalhes da Vaga**
Estamos contratando Frontender Sênior para fazer parte do nosso crescente time de Porto Alegre - RS. 

Nosso stack de desenvolvimento atual inclui:
- Angular JS (na maioria do nosso frontend);
- Ruby on Rails;
- PostgreSQL;
- Redis e Sidekiq;
- Python e Django;
(entre outros)

Buscamos um(a) profissional capaz de transitar entre as habilidades de frontend/design/ux e o desenvolvimento de código para o frontend com as tecnologias acima, consumindo API’s de backend para viabilizar a entrega de uma solução completa.

**Metodologia**
Prezamos por executar uma metodologia ágil, com certas adaptações para nossa realidade atual. Nossas sprints tipicamente duram 2 semanas e montamos ao menos 2 squads (times) de 2 ou 3 indivíduos dedicados a resolver um problema muito claro.

**Sobre a Todo**
A Todo Cartões cria e opera programas de Gift Card digitais para grandes varejistas de todo o Brasil. Nossas plataformas ajudam a fidelizar clientes e gerar mais valor para a marca, com grande representatividade no aumento vendas, rastreabilidade e conhecimento de marca.

Nosso trabalho pode ser visto em grandes marcas como: Outback Steakhouse, Applebee’s, Lojas Leader, Riachuelo, TNG, Grupo RiHappy, Electrolux, Pizza Hut, TGI Friday’s, entre muitos outros.

**Desejáveis**
- React
- Redux
- Bancos de dados / SQL
- Experiência com trabalho remoto
- Experiência com agilidade
- Docker

**Local de Trabalho**
Podemos avaliar trabalhos remotos, mas daremos prioridade para profissionais que possam trabalhar presencialmente em Porto Alegre de 1 a 3x por semana.

**Como se candidatar?**
Link: https://bit.ly/2VZCvfL

**Comment by thomashs** [comment]
Olá @MrS4w que informações estão faltando?

**Comment by HaluDeCassia** [comment]
@MrS4w acredito que sejam as labels. E também não identifiquei os requisitos obrigatórios

**Comment by MrS4w** [comment]
@thomashs exatamente o que a @HaluDeCassia  disse.

**Comment by thomashs** [comment]
Oi @HaluDeCassia obrigado pela ajuda! @MrS4w já corrigi e publiquei de novo na #2020
