### ISSUE TITLE
São Paulo - Desenvolvedor Backend (Pleno e Senior) - Studo+

### ISSUE THREAD

**Issue by thiagonetorh** [frontendbr/vagas#202]
Estamos em busca de desenvolvedores Java, com experiência em desenvolvimento de APIs RESTfull.
Você ajudará a desenvolver novas funcionalidades, manter e melhorar funcionalidades
existentes, além de lidar com desafios técnicos, trazendo ideias e soluções.

Local: Metrô Santa Cruz - São Paulo
Escritório

Benefícios

Assistência médica Omint - sem desconto
VR
PLR
Máquina de snacks grátis

## Requisitos

**Obrigatórios:**
- Experiência em desenvolvimento java.
- Conhecimento prático sobre design patterns, refactoring e TDD.
- Experiência prática em desenvolvimento e consumo de APIS restfull.
- Experiência com metodologias ágeis de desenvolvimento.

## Contratação

CLT

## Nossa empresa
Studo+ é uma startup com foco em inovação da área educacional. 
Trabalhamos com metodologia ágil, focada em testes (TDD) e muito trabalho em
equipe.

## Como se candidatar

Por favor envie um email para thiagonetorh@gmail.com.br com seu CV anexado - enviar no assunto: Vaga Backend - Studo+

**Comment by LFeh** [comment]
Como está bem claro na descrição do repositório, aqui é um espaço para vagas FRONT-END ;)

**Comment by thiagonetorh** [comment]
Desculpe, confundi os grupos.

**Comment by LFeh** [comment]
De boas :)
