### ISSUE TITLE
[Rio de Janeiro] Product Owner @ Lemoney

### ISSUE THREAD

**Issue by lemoneyhiring** [frontendbr/vagas#2022]
## Missão da Vaga

Atuar como dono de todo o processo de Sprint, desde a organização do BackLog até a especificação e delegação de tarefas para o time de Desenvolvimento. 

## Pré Requisitos

- Inglês Avançado;
- Perfil Hands On, Proativo e Organizado
- Conhecimento prévio em metodologias ágeis;
- Desejável experiência com empresas de tecnologia;
- Conhecimento em programação é um plus;

## Principais Responsabilidades

- Interface com as diversas áreas do negócio;
- Filtrar as principais demandas, priorizar, organizar, especificar e delegar para o time de desenvolvimento e UX;
- Acompanhamento do BackLog para avaliar possíveis gargalos ou dificuldades;
- Participação da planning semanal junto com o Product Manager, time de UX e desenvolvimento;
- Atualização, organização e revisão contínua do Trello com todas as demandas e atividades discutidas na planning e demais demandas que surgem durante a semana;
 
## Local

Nosso Escritório fica em um dos pontos mais atrativos do Rio de Janiero, à 200m da Praia de Ipanema, ao lado do metrô. Temos também, um co working space em Downtown Miami.

## Nosso modo de ser

- Temos um time pequeno, mas de ouro! Todos engajados e extremamente produtivos;
- Política agressiva de bonificação por metas batidas;
- Gostamos que todos estejam envolvidos nas principais decisões da empresa;
- Abominamos burocracia! Queremos resolver problemas de maneira ágil;
- Você trabalhará diretamente com o mercado americano, onde a excelência é default.
- Nosso ambiente é informal e dinâmico, com amplo espaço para criatividade e inovação.
- Gostamos muito de trocar conhecimento através de palestras e workshops internos;

## Contratação

Consideramos PJ ou CLT

## Sobre Nós

A [Lemoney](https://www.lemoney.com/) é uma empresa americana de Cash Back construída por Brasileiros!
 Trabalhamos diretamente com o Mercado de Afiliados, um dos mercados com maior crescimento no mundo digital. Apesar da nossa operação estar no Rio de Janeiro, nosso foco é no mercado ameriano. Você terá a oportunidade de aprender sobre a cultura e hábitos de consumo do país referência de mercado.

Aqui na **Lemoney**, damos muita importância à pensamentos fora da caixa. Buscamos pessoas apaixonadas pelo que fazem, que pensam grande e não se contentam apenas com o “bom”. Pessoas criativas, que gostam de resolver problemas na hora que eles aparecem, de maneira inovadora e eficiente.
**Excelência é o nosso lema!**

## Application

Se identificou? Envie seu Linkedin ou currículo e seu portfólio para careers@lemoney.com e boa sorte!! :)

**Comment by highlabs** [comment]
Creio que essa vaga está no local errado. Esse repositório é para vagas para desenvolvedoras(es) front-end.
