### ISSUE TITLE
[Remoto] Desenvolvedora Front-End React na iMusics

### ISSUE THREAD

**Issue by monteirobrena** [frontendbr/vagas#2025]
**Atenção: Esta é uma vaga exclusiva para mulheres.**

Dizem que trabalhar com música é muito bom, e podemos afirmar que realmente é f… de bom! Parafraseando alguém famoso, aqui acreditamos que a vida sem música seria um erro.

**O que buscamos?**

Estamos com vaga para desenvolvedora de software, mas pra trabalhar com a gente você precisa, primeiramente, se identificar com nossos valores e com nossos compromissos junto ao mercado. Somos feitos de pessoas acima da média que adoram trabalhar e serem desafiados, questionadores, que não têm medo das idéias criativas e desafiadoras e que vêem significado naquilo que fazemos e proporcionamos a nossos usuários.

Buscamos uma dev front-end com conhecimento em React para ser responsável pelo desenvolvimento de interfaces responsivas integradas com API RESTful, bem como a criação e manutenção dos projetos já desenvolvidos.

Procuramos alguém multitasking, que não tenha medo de perguntar e de dar opinião, e que saiba principalmente a hora de ouvir. Que tenha um pensamento crítico e que vá além do código para avaliar, opinar e nos ajudar a construir produtos e serviços úteis, funcionais e sensacionais.

**Você precisa conhecer e ter experiência com:**

- React
- JavaScript
- HTML
- CSS

**Será ótimo se você também conhecer:**

- Ruby on Rails
- Angular JS
- SASS/SCSS

**E perfeito se você tiver experiência com:**

- Componentização
- Integração entre APIs

**Nível:**

- Júnior

**Oferecemos:**

- Home office
- Ajuda para cursos de especialização
- Possibilidades de prêmios financeiros

**Forma de contratação:**

- PJ

**Como se candidatar:**
Envie um email para **code@imusics.com** contando um pouco da sua experiência como dev, o que você tem estudado e desenvolvido nos últimos anos e seu currículo.

Somos uma empresa sem distinção de raça, cor, religião, gênero e identidade de gênero, nacionalidade, deficiência, orientação sexual, ascendência ou idade. Profissionais LGBTQI+ são super bem-vindos.

**Labels**

- Júnior
- Remoto
- PJ

**Comment by HaluDeCassia** [comment]
@monteirobrena essa vaga é muito bacana mesmo. Me identifiquei bastante com a política da empresa. Mas pedir experiência em uma vaga Junior não é um pouco contraditório? Ou será que foi o caso de faltar uma label de Pleno na descrição da vaga?

**Comment by monteirobrena** [comment]
@HaluDeCassia exato, a gente não está pedindo experiência profissional mesmo sabendo que tem pessoas com perfil júnior mas que já atuaram em alguma empresa. O essencial é  já possuir conhecimento em React de forma que consiga criar projetos, implementar integrações e dar manutenção nos projetos existentes.

**Comment by monteirobrena** [comment]
Agradecemos a todas que se candidataram.

Agora vamos para a segunda fase do processo!
