### ISSUE TITLE
[São Paulo] Front-End Developer na Ali Crédito

### ISSUE THREAD

**Issue by alicredito** [frontendbr/vagas#2026]
**Descrição da Vaga**

Trabalhar na Ali é estar todos os dias criando soluções para reduzir o custo de crédito e meios de pagamentos mais eficientes para as pessoas.

Neste caminho, buscamos hoje um Engenheiro de Frontend Senior que nos ajude na construção das interfaces de nossos produtos dos quais nosso time interno, parceiros e milhares de clientes utilizarão. Serão desafios de todos os tipos: arquitetura, performance, segurança, usabilidade, etc.

**Pré-requisitos**

 - Sólida experiência (mínimo de 3 anos) com o desenvolvimento de websites utilizando as tecnologias ReactJS, HTML, CSS e Javascript;
 - Sólidos conhecimentos com utilização de grids para diagramação de conteúdo (como, por exemplo, o Bootstrap);
 - Construção de websites responsivos para diversos tipos de device (desktop, celulares, tablets, etc.);

**Desejável/diferenciais**

 - Conhecimentos nas tecnologias React Native;

**Responsabilidades:**

Você será responsável por desenvolver, testar e acompanhar o desempenho das interfaces de nossos produtos para garantir a melhor experiência possível para nossos clientes, parceiros e time interno. Você fará parte de um time de altíssima qualidade técnica e que segue metodologia ágil para os sprints.

**Em resumo:**
Participar ativamente das etapas de ideação, planejamento e desenvolvimento dos produtos;
Participar das discussões de tecnologias que serão utilizadas nos produtos;
Desenvolvimento de aplicações web responsivas com React.js, consumindo nossas APIs internas e externas, baseadas em layouts feitos por nossos designers;
Ser curioso e estar disposto a pesquisar e validar novas tecnologias;
Disposição para ajudar e compartilhar conhecimento;
Entregar projetos bem testados e sustentáveis, aplicando melhores práticas de testes unitários;
Construir e garantir a atualização da documentação do código;

---

**Sobre a Ali Crédito**

Trabalhar na Ali é estar todos os dias criando soluções para reduzir o custo de crédito e meios de pagamentos mais eficientes para as pessoas. Parece simples, mas é nosso foco: crédito justo para as pessoas e empresas. Para isso, investimos muito em pessoas, no desenvolvimento dos times e em tecnologias que melhorem a experiencia e sejam mais eficientes em melhorar a vida financeira das pessoas. É um grande desafio, e para isto, focamos em construir um grande time.

**Nosso time e nosso dia-a-dia**

Nosso jeito de construir e trabalhar na Ali é divertido, mas muito focado em resolver problemas e dar resultados aos nossos clientes. Nossa cultura é focada no equilíbrio entre liberdade e eficiência, que conseguimos através de alinhamento constante entre os times. Nosso compromisso é “missão dada é missão cumprida”. Nosso time tem muita energia, é diverso e focado em construir serviços e a melhor experiencia para nossos clientes.

**Nosso escritório**

Ficamos em um incrível prédio, muito moderno, em Pinheiros. Bem perto do Metro.

**Comment by praganavictor** [comment]
Como faz para se candidatar?
