### ISSUE TITLE
[São Paulo] Engenheiro de Software Frontend

### ISSUE THREAD

**Issue by camilaibs** [frontendbr/vagas#203]
## Descrição da vaga

Engenheiro de Software Frontend (Pleno/Sênior).

## Local

Escritório, Avenida Queiroz Filho, 1700, C803, Vila Hamburguesa, São Paulo, SP 05319-000 Brasil.

## Benefícios

- Vale Refeição (valor de R$ 25,00 por dia, sempre comprado pelos dias úteis);
- Vale Transporte (comprado perante a necessidade do empregado, desconto de 6% em folha limitado ao valor da compra);
- Assistência odontológica (há 3 planos, cada um com um tipo de cobertura e valores, e é descontado em folha);
- Assistência médica, ambos pela Notredame e apartamento, segue abaixo:
1. Advance 700 (para empregados CLT de auxiliar até analista, desconto de R$ 190,46 para dependentes em folha)
2. Premium 800.1 (para empregados líder, coordenadores, supervisor, etc..., desconto de R$ 218,48 para dependentes em folha)
3. Premium 900.1 (para empregados com o salário acima de R$ 10.000,00)
4. Premium 900.3 (para empregados com cargo de gerencia, com o salário acima de R$ 10.000,00)
- Seguro de vida;
- Parceria com o SESC.

## Requisitos

Procuramos um profissional proativo, capaz de trabalhar e interagir com uma equipe multidisciplinar (backend, frontend, gerente de produto e designers), alinhado às práticas do nosso time, com foco em resultados, testes e criação de produtos referência no mercado.

Nosso stack frontend básico se baseia em: Angular, TypeScript, Gulp, Sass, Git.

**Desejáveis:**
- Forte experiência com Javascript;
- Experiência com ferramentas de monitoramento de performance;
- Experiência com ferramentas de monitoramento de erros (Ex: TrackJS);
- Experiência com Google Tag Manager para gestão de Tags e implementação de Analytics. 

**Diferenciais:**
- Experiência com desenvolvimento backend (Python/Flask ou outras linguagens, API's REST).

## Contratação

CLT a combinar.

## Nossa empresa

 A Lendico, plataforma online de empréstimos pessoais, está com desafios técnicos para manter seu forte crescimento. Em pouco mais de 1 ano e meio após o lançamento do produto, já emprestamos mais de 45 milhões de reais aos nossos clientes do Brasil.
 
A Lendico, que pertence ao grupo Rocket Internet, foi fundada na Alemanha, em 2013, e possui operação em cinco países. A empresa chegou ao Brasil em julho de 2015 para mudar o mercado de crédito nacional, recebendo solicitações de mais de 450 cidades de todo o Brasil.

## Como se candidatar

Por favor envie um email para camila.belo@lendico.com.br com seu CV anexado - enviar no assunto: Vaga Engenheiro de Software Frontend (Pleno/Sênior).

**Comment by LFeh** [comment]
Rolou?

**Comment by camilaibs** [comment]
Rolou sim @LFeh , obrigada!!

**Comment by LFeh** [comment]
Aee, foi daqui?
