### ISSUE TITLE
[Remoto] Desenvolvedor Front End - JavaScript Sênior na iClinic

### ISSUE THREAD

**Issue by pauloedurezende** [frontendbr/vagas#2032]
## Descrição
Com o propósito de **Descomplicar a Saúde no Brasil**, através de um sistema que entregue soluções incríveis para os nossos usuários, a iClinic é uma plataforma SaaS líder de mercado no país.

Estamos crescendo e desenvolvendo nosso produto constantemente, como parte disso, estamos aumentando a nossa equipe de tecnologia, de forma a garantir que a nossa ferramenta continue entregando valor aos nossos clientes.

Como desenvolvedor(a) Front End, você tem que manter o equilíbrio entre criatividade e produtividade em projetos inovadores.

## Quais os próximos passos?
Primeiro leia a vaga, veja se você se identifica, faça a sua candidatura e ao final como requisito do nosso processo, você terá um primeiro desafio. E aí topa?

Boa sorte no seu desenvolvimento, e precisando, conte com a gente! :)

## Requerimentos
<h3>O que você vai fazer?</h3>

- Irá ajudar a desenvolver novas funcionalidades de acordo com o roadmap do produto;
- Ajudará a encontrar soluções para problemas no sistema;
- Você irá trabalhar com equipes multidisciplinares em um ambiente ágil;
- Trabalhará com diversas pessoas brilhantes (como você) tendo uma troca de conhecimento muito bacana;

<h3>O que esperamos de você:</h3>

- Estar sempre em busca de novos conhecimentos, lendo artigos, newsletters, participando de grupos;
- Demonstrar proatividade com as tarefas, projetos, ideias, e contribuir com resultados;
- Saber trabalhar em equipe, compartilhando seus conhecimentos, estar aberto a dar e receber feedbacks;
- Se importar com arquitetura de projetos, Design Patterns e boas práticas de código;
- Alta capacidade de auxiliar os outros membros do time a se desenvolverem;
- Otimizar o dia a dia e processos do time (automatizações, ajudar a definir escopos de entregas, definir padrões)
- Metodologias de testes
- Arquitetura de projetos, design patterns e boas práticas de código
- Alta capacidade para resolução de problemas: Entende o problema e consegue implementar a solução do início ao fim;
- Lidar com servidores caso haja problemas em produção por exemplo
- Inteligência emocional: resolver as situações-problemas de uma maneira ágil e assertiva.

<h3>O que você precisa ter?</h3>

- HTML: Api's, semântica, SEO;
- CSS: Ferramentas(pré e pós processadores), padrões, boas práticas de responsivo;
- React (V-dom's), gerenciamento de estado de aplicações, componentização, lidar com recursos e bibliotecas assíncronas;
- HTTP request's;
- Git de forma geral (branchs, pull requests e etc..);
- Ambientes Node.JS e CLI (comand line);
- Fluxo de trabalho com ambientes ágeis (CI, CD, Métodos agile);
- Noções clean code, noções de imutabilidade e funcional(Manipulação de estrutura de dados, Redux Saga) e arquitetura de projetos;
- Webpack e similar;
- React Native ;
- Entender Renderização (Lifecycle do browser, render, re-render, repaint, reflow);
- Experiência com Node.JS;
- Progressive Web App's;

<h3>Nice to have:</h3>

- Autodidata;
- Participar de comunidade;

---

<h3>Local</h3>

**Remoto** ou Escritório, em Ribeirão Preto, SP - Av. Presidente Vargas

<h3>Benefícios</h3>

- Possibilidade de trabalho remoto;
- Plano de saúde;
- Vale alimentação;
- Plano de Participação dos Resultados;
- Trabalhe com os melhores computadores da apple;
- Ambiente jovem, descontraído, escritório confortável, videogame, puffs para descanso;
- Sem dress code. Trabalhe de calça, bermuda, chinelo, pantufa ou de qualquer outro jeito que achar confortável;
- Rango open: café da manhã, frutas ao longo do dia e copa para refeições. Além do sagrado cafezinho moído na hora;
- Relacionamento próximo aos fundadores e diretores da empresa;
- Possibilidade de rápido crescimento na carreira.

<h3>Como se candidatar</h3>

Você pode aplicar [aqui](https://iclinic.workable.com/j/E9D1879DFA)

## Labels

- CLT
- Alocado
- Remote
- Senior

**Comment by mrangel-jr** [comment]
@pauloedurezende , a vaga já foi preenchida ?

**Comment by pauloedurezende** [comment]
Olá @mrangel-jr, foi preenchida sim...
