### ISSUE TITLE
[RJ/Glória] Desenvolvedor(a) Java Script/React  -nível Sr

### ISSUE THREAD

**Issue by parizotto123** [frontendbr/vagas#2033]
Empresa de Grande porte busca desenvolvedores no perfil abaixo:

Analista Desenvolvedor JavaScript Senior 

Requisitos Mandatórios:
•	Desenvolvimento de Dashboards em JavaScript;
•	Experiência no Framework REACT;
•	Conhecimentos em Metodologia AGILE;
•	Inglês avançado ou Fluente.

Prazo: 3 meses, podendo ser prorrogado
Local: Rio de Janeiro - Glória
 Interessados, enviem cv para flaparizotto@hotmail.com e colocar no campo assunto: JavaScript
ou envie watsap para 11 994600773 para mais detalhes

**Comment by felipefialho** [comment]
@parizotto123 Precisamos do nome da empresa.
