### ISSUE TITLE
[Faria Lima/SP] Engenheiro Front End

### ISSUE THREAD

**Issue by parizotto123** [frontendbr/vagas#2034]
Empresa de Grande porte do segmento de Meios de Pagamentos, busca candidatos para atuarem nos requisitos abaixo:

Engenheiro Front End Sr.
Requisitos:
Experiência na criação de páginas responsivas, web e mobile
Experiência em desenvolvimento de aplicações web utilizando Javascript avançado (OO, herança, prototipação, design pattern, jQuery, ES6).
Experiência em CSS Avançado (SASS e LESS) e CSS3
Experiência em suporte a browsers antigos (graceful degradation)
Conhecimentos de Regex
Domínio de protocolo (HTTP, HTTPS, cross domain)
Conhecimentos de arquitetura backend (servidor web, estático, BFF)
Conhecimento de React, Vue

Desejáveis:
Conhecimentos relacionados a performance (gzip, minify, quantidade de requests)
Testes automatizados
Conhecimento em Apache Velocity
Conhecimento de virtualização (Docker, Mesos)

Local de Trabalho: Faria Lima –SP.
Contratação: PJ
Período: Indeterminado

Interessados, enviem cv para flavia.parizotto@domvs.com.br e no campo assunto preencher o código: Eng Front

**Comment by felipefialho** [comment]
@parizotto123 Qual o nome da empresa?
