### ISSUE TITLE
[Porto Alegre] Front-End Developer na Warren Brasil

### ISSUE THREAD

**Issue by nicolaspeixoto** [frontendbr/vagas#2037]
## Descrição da vaga

Procuramos uma pessoa Front-End Developer para se juntar ao time! Buscamos alguém para atuar em um ambiente criativo e super descontraído, trabalhando com autonomia em várias aplicações web. Seu desafio será cuidar do desenvolvimento e manutenção da nossa plataforma de cadastro e primeiro depósito, garantindo uma experiência incrível de entrada do usuário na plataforma!

Você vai participar e atuar, junto com a equipe de design e desenvolvimento mobile, na manutenção e criação de novas funcionalidades para versão web da Warren, analisando, compreendendo e discutindo os aspectos funcionais e técnicos;
Seu trabalho ajudará a oferecer e fomentar uma experiência de uso fantástica já conhecida por nossos usuários e propor melhorias para manter a qualidade do código.

## Local

Osvaldo Aranha, 720 - Porto Alegre.

## Requisitos

**Obrigatórios:**
-    Ter motivação para fazer os projetos saírem do papel;
-    Ter boa comunicação com os colegas;
-    Vontade de compartilhar ideias;
-    Participar na priorização de funcionalidades;
-    Codificar aplicações utilizando melhores práticas de testes (integração, unitário…);
-    Utilizar ferramentas de versionamento;
-    Acompanhar entregas do time;
-    Ser responsável pelo deploy de web na área de cadastro e primeiro depósito.

**Desejáveis:**
-    Portfólio com algum projeto criado do zero ou github com contribuições relevantes. 
-    Queremos entender seus métodos de trabalho!
-    Bom conhecimento em HTML, CSS e Javascript
-    Cuidado com UX/UI e guidelines da plataforma.
-    Conhecimento em Angular, VueJS ou Typescript.
-    Bom conhecimento em ES6.
-    Inglês suficiente para leitura de materiais, códigos, etc.

**Diferenciais:**
- 	Conhecimentos em NodeJS
- Familiarização com ferramentas de prototipagem UI (ex.: figma, sketch)

## Contratação

PJ a combinar

## Nossa empresa
Somos uma fintech localizada em Porto Alegre, que tem como principal objetivo descomplicar o obscuro mundo dos investimentos e convencer as pessoas de que cuidar de suas finanças pessoais pode ser algo leve, simples e até divertido. Somos uma plataforma online que incentiva o usuário a criar objetivos e investir neles, mostrando que seu primeiro milhão ou viagem ao redor do mundo podem estar mais próximos do que imagina.

Existimos para facilitar a vida de quem quer investir bem o seu dinheiro, sem o blá-blá-blá, gravatas e taxas que os bancos oferecem. Nossa proposta envolve um investimento com transparência, agilidade e empatia. Já são mais de 10 mil pessoas que confiam seus sonhos e metas ao Warren e é por isso que precisamos estar disponíveis em todas as plataformas. Queremos que todos tenham acesso ao Warren e que possam acompanhar seus investimentos onde quer que estejam.

## Como se candidatar

Mande seu curriculo para para staff@warrenbrasil.com

## Labels

- PJ
- Pleno
- Sênior

**Comment by halkliff** [comment]
Olá,

Estão aceitando desenvolvedores remotos também?

**Comment by HaluDeCassia** [comment]
Também gostaria de saber. Já que o contrato é PJ, essa forma facilita tanto pra ter mais opções de quanto para os próprios candidatos.

**Comment by nicolaspeixoto** [comment]
Oi pessoal. Infelizmente estamos priorizando pessoas alocadas neste momento.
