### ISSUE TITLE
[São Paulo] Front-end Developer na Murilhas Comunicação

### ISSUE THREAD

**Issue by ricardogouveia3** [frontendbr/vagas#2039]
## Descrição da vaga
Estamos em busca de uma pessoa desenvolvedora front-end para atuar na ZS de São Paulo.
As atribuições se baseiam em implementação de sites de landing pages, email marketing, e por vezes design de seções de páginas com o Ilustrator.
A stack é aberta, mas em geral utilizamos HTML ou Pug, SASS (scss) e javascript (vanilla ou jQuery ou Vue). O professional precisa ter boas habilidade de gerenciamento de prazo e decisão de ferramentas.
 
## Local
Trabalho presencial em nosso escritório: metrô Santa Cruz, ZS.
 
## Benefícios
VR de R$ 30 por dia
Vale Transporte
 
### Obrigatórios:

- HTML
- CSS/SASS
- Javascript
- Noções de design de interfaces
- HTML para e-mail marketing (table based)
- Git (usamos bitbucket)

 
### Desejáveis:

- jQuery
- Vue.js
- Experiência com Sistema macOS
- Wordpress (construção de temas em PHP)
- Utilização de APIs públicas e privadas
- Automatizadores de tarefas (gulp/webpack)

 
### Diferenciais:

- Conhecimento básico em back-end PHP
- Boa comunicação escrita

 
## Principais Atividades:

- Desenvolvimento de sites completos e LPs
- Otimização de sites e aplicações web com métricas do lighthouse (sem pwa)
- Decisão de tecnologias para novos projetos, quando de escopo aberto

 
## Contratação

- PJ

 
## Nossa empresa
Somos uma agência de comunicação moderna, com 23 anos de história, com clientes de todos os portes e focada em resultados. Prezamos pela inovação nos produtos, agilidade de entrega e trabalho em equipe. Em web, estamos em busca de experiências que balanceiem a política PixelPerfect com a usabilidade, a acessibilidade, a manutenabilidade e a adaptabilidade do produto aos objetivos e expectativas do cliente e do mercado.
 
## Como se candidatar
Envie um e-mail com seu currículo, pretensão salarial, portfólio, LinkedIn e Github para ricardo@murilhas.com.br

## Labels

- Alocado
- Júnior
- PJ

**Comment by praganavictor** [comment]
Enviado, muito boa a vaga!
