### ISSUE TITLE
[São Paulo] Desenvolvedor(a) front-end na Bio Ritmo/Smart Fit

### ISSUE THREAD

**Issue by shadowmaru** [frontendbr/vagas#204]
A Empresa
========

O Grupo Bio Ritmo detém as marcas Smart Fit e Bio Ritmo, que juntas têm mais de 300 unidades no Brasil 🇧🇷, México 🇲🇽, Chile 🇨🇱, República Dominicana 🇩🇴, Colômbia 🇨🇴 e Peru 🇵🇪 e mais de 1 milhão de clientes. Somos a empresa com maior crescimento no segmento de fitness da América Latina (em torno de 50% ao ano).

O departamento de desenvolvimento de software é peça chave dentro do grupo, que enxerga na tecnologia a simplificação de seus processos e maximização da eficiência de seus colaboradores. Nos esforçamos para manter um ambiente descontraído, onde a opinião de todos reflete nas decisões da equipe. Estamos em constante evolução e sempre abertos a novas tendências e tecnologias.

Perfil
====

Você dará manutenção aos nossos sites, sistemas internos e também trabalhará em novos projetos do zero.

A vaga é exclusivamente presencial em nosso escritório localizado na Avenida Paulista (período integral, porém com horário flexível).

A Vaga
=====

Precisamos de alguém que saiba:

- HTML5
- CSS3
- Pré-processadores (usamos SASS/SCSS)
- JavaScript (usamos ES5 e alguma coisa de ES6)
- Git
- Se virar no Photoshop e/ou no Sketch
- Responsive Web Design
- REST para integração com as nossas APIs

E que também:

- Não tenha preconceitos. Usamos jQuery (sim), Bootstrap (sim), Haml, ReactJS, VueJS, asset pipeline do Rails no lugar de Grunt/Gulp/Webpack/Browserify e muito código legado que precisará de manutenção.
- Tenha vontade de aprender e seja pragmático(a). Usar a melhor solução para cada problema.

Diferenciais:

- Tenha trabalhado em equipes ágeis
- Espanhol ou inglês (para comunicação com as equipes da América Latina)
- UX
- Ruby on Rails
- Flexbox
- Testes automatizados (Karma, Jasmine, etc.)
- Conhecer programação reativa

Benefícios:

- Vale Refeição de R$ 20,35/dia;
- Vale Alimentação;
- Seguro de vida;
- Seguro Saúde Caixa;
- Acesso gratuito a qualquer academia do grupo;
- Sua escolha entre Mac, Linux ou Windows (vai que)
- Bicicletário no prédio;

Remuneração
==========

R$5000 a R$7000 (CLT)

Vamos conversar?
==============

Mande um email para `vagas-dev@bioritmo.com.br` com o seu currículo e apresentação

**Comment by danlaurent** [comment]
Enviado. :)

**Comment by G18siqueira** [comment]
tem vaga para estágio?

**Comment by gusribeiro** [comment]
enviado

**Comment by danielGalvao** [comment]
Boa Ricardo!! Só para colocar as tags na vaga... Pleno / Sênior? CLT Alocado?

**Comment by shadowmaru** [comment]
@danielGalvao é isso que o @LFeh adicionou. Valeu!

@G18siqueira por enquanto não temos para estágio

**Comment by chavesdiego** [comment]
Enviado

**Comment by shadowmaru** [comment]
Pessoal, processo encerrado. Obrigado por todos os currículos, houve uma ótima resposta 😄
