### ISSUE TITLE
[São Paulo] React Native Developer na Hupper

### ISSUE THREAD

**Issue by raffaelmarfara** [frontendbr/vagas#2040]
## Descrição da vaga

Estamos buscando um desenvolvedor pleno ou júnior para fazer parte do time de tecnologia da Hupper, que vai trabalhar com o desenvolvimento e gestão de uma aplicação híbrida, desenvolvida em React Native. Buscamos alguém com vontade de trabalhar, aprender, liderar e crescer junto com a empresa.

## Local

WeWork Faria Lima

## Benefícios / Diferenciais

- Horário flexível
- ☕ Free coffe
- 🍻 Free beer
- Stock-option

## Requisitos

**Obrigatórios:**
- React Native

**Desejáveis**
- Typescript
- macOS

## Contratação

PJ a combinar

## Nossa empresa

A Hupper é uma startup fundada por dois ex-alunos do Insper que tem o objetivo de incentivar e melhorar a saúde e bem-estar dos colaboradores das empresas com uma plataforma de saúde gamificada, que utiliza inteligência artificial para engajar os colaboradores na adoção de hábitos saudáveis. 

## Como se candidatar

Para se candidatar, enviar um e-mail com CV ou Linkedin e pretensão salarial para r.marfara@hupper.life com o assunto “GITHUB - RECT NATIVE DEVELOPER HUPPER"

## Labels

- Alocado
- Júnior
- PJ
- Pleno

**Comment by brunooomelo** [comment]
@MrS4w  não entendi o motivo de fechar a vaga.

**Comment by raffaelmarfara** [comment]
@MrS4w por que fechou a vaga?

**Comment by MrS4w** [comment]
@brunooomelo , @raffaelmarfara este repositório é somente vagas front-end, existe um apenas para vagas como essa bem [aqui](https://github.com/react-brasil/vagas)

**Comment by brunooomelo** [comment]
creio que React e RN se qualifica como frontend tambem.

**Comment by carlosafw** [comment]
@MrS4w powertrip, classifica sim @brunooomelo.
