### ISSUE TITLE
[Remoto, São Paulo] Front-End Developer na Somar Meteorologia

### ISSUE THREAD

**Issue by iamgbayer** [frontendbr/vagas#2041]
## Descrição da vaga
Estamos procurando por um(a) Frontend Developer para nos ajudar a construir a próxima geração de ferramentas digitais para previsões de curto e longo prazo e informações em tempo real (forecast, nowcast, climatology).

Você fará parte de uma equipe altamente qualificada, abrangendo tecnologias espaciais abertas emergentes e novas formas de consumir dados meteorológicos.

## Local
A vaga aceita tanto remoto quanto no escritório da Somar, que fica localizado na Vila Leopoldina, São Paulo, SP.

## Requisitos
**Mandatórios:**
- Javascript (Vanilla)
- HTML5
- CSS3
- React
- Consumo de APIs REST
- Webpack
- GIT

**Desejáveis:**
- Vivência com React
- Pipeline de deploy em ambientes Cloud
- Ferramentas de controle de tarefas Jira
- Metodologias Lean/Agile
- Contato com opensource.

## Contratação
PJ a combinar

## Sobre a empresa
Junte-se a Somar Meteorologia, uma das principais empresas privadas do setor de meteorologia do país atuando desde 1995 atuando em diversos segmentos.

## Como se candidatar
**Desafio técnico**

É de grande interesse que você consiga realizar nosso desafio técnico para que possamos ter uma breve noção técnica relacionada a boas práticas, testes, organização, solução do problema proposto e outros. É claro que a avaliação técnica é apenas uma parte dentre outras que serão avaliadas.

[https://github.com/somarmeteorologia/challenge](https://github.com/somarmeteorologia/challenge)

## Mais detalhes
[Aqui](https://www.notion.so/somarmeteorologia/Frontend-Developer-a09e0ec3d02a4dda9a7ec7b33cd89b3d) você encontra mais detalhes sobre a vaga.

## Labels

- Júnior
- PJ
- Pleno
- Remoto
- Alocado

**Comment by eugeniucarvalho** [comment]
Boa noite como funciona o remoto? Enviei um e-mail solicitando o token de acesso. Abraço

**Comment by jonathanguilhermesouza** [comment]
@iamgbayer a vaga está aberta?
