### ISSUE TITLE
[Lisboa-Portugal] React/Angular Developer - Aubay

### ISSUE THREAD

**Issue by alexandregvale** [frontendbr/vagas#2045]
Projetos em vários setores de atividade, usando diversas tecnologias de Frontend tais como React ou Angular, sempre internacionais!

Local
Portugal: Lisboa

Benefícios
• Plano de saúde
• Visto de Trabalho para Portugal
• Outras

Diferenciais
• Formações técnicas, comportamentais e de idiomas
• Prémios de referências de recrutamento
• Eventos Team Building
• Convívio mensal
• Oferta de aniversário

Requisitos
Obrigatórios:
• Experiência profissional na área web
• Bons conhecimentos de Javascript, HTML, CSS
• Experiência em Angular ou React.
• Fluência na língua Inglesa

Diferenciais:
• Experiência internacional

Contratação
Apoio em todo o processo para obtenção de visto de trabalho para Portugal.

Nossa empresa
A Aubay, é uma empresa de origem francesa presente em diversos países na Europa.
Como cerca de 7000 pessoas desenvolvemos projetos nas mais diversas tecnologias.
Neste momento, temos várias vagas em aberto para várias posições.

Como se candidatar
Por favor envie um email para avale@aubay.com com seu CV em Inglês anexado e o assunto R/A_19.

**Comment by JeanGoncalves** [comment]
Se não fosse não necessária a fluência no inglês, com certeza me candidataria.

**Comment by alexandregvale** [comment]
Mas consegues comunicar-te em inglês Jean?


Com os melhores cumprimentos,

[721313813@16102008-18F2]  Alexandre VALE
  Talent Recruiter

Av. Duque de Ávila 46, 7C, 1050-083 Lisboa
Tel: +351 211 928 417 - Mobile: +351 910 519 462
Fax: +351 211 928 230
Skype: alexandregvale
youtu.be/baDb1n4_zPA<https://youtu.be/baDb1n4_zPA> - Porquê a Aubay? Porque é A AUBAY!
www.aubay.pt<http://www.aubay.pt/>
“Iremos utilizar informação pessoal que nos enviou, para considerar a sua candidatura à função relevante. Ao facultar-nos a sua informação por email e/ou em documentos, consente que a Aubay Portugal trate a sua informação pessoal. A sua privacidade é importante para nós. Por favor, consulte a nossa Política de Privacidade<http://www.aubay.pt/>, que explica de que forma utilizaremos e armazenaremos a sua informação pessoal. Explica também os direitos que tem relativamente à sua informação e como pode contactar-nos para o esclarecimento de dúvidas ou pedidos.”


De: Jean Gonçalves <notifications@github.com>
Enviada: 23 de maio de 2019 16:24
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: Alexandre VALE <avale@aubay.com>; Author <author@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [Lisboa-Portugal] React/Angular Developer - Aubay (#2045)


Se não fosse não necessária a fluência no inglês, com certeza me candidataria.

**Comment by JeanGoncalves** [comment]
@alexandregvale hoje Não me sinto confortável em realizar uma entrevista em inglês.

**Comment by andreantunees** [comment]
Apply.

**Comment by halkliff** [comment]
Applying! 😊

**Comment by krivax** [comment]
Se n fosse a fluência tbm me candidataria

**Comment by rmasouza** [comment]
Existe a possibilidade de trabalho remoto?

**Comment by alexandregvale** [comment]
Bom dia. Não, teria que ser presencial em Portugal.


Com os melhores cumprimentos,

[721313813@16102008-18F2]  Alexandre VALE
  Talent Recruiter

Av. Duque de Ávila 46, 7C, 1050-083 Lisboa
Tel: +351 211 928 417 - Mobile: +351 910 519 462
Fax: +351 211 928 230
Skype: alexandregvale
youtu.be/baDb1n4_zPA<https://youtu.be/baDb1n4_zPA> - Porquê a Aubay? Porque é A AUBAY!
www.aubay.pt<http://www.aubay.pt/>
“Iremos utilizar informação pessoal que nos enviou, para considerar a sua candidatura à função relevante. Ao facultar-nos a sua informação por email e/ou em documentos, consente que a Aubay Portugal trate a sua informação pessoal. A sua privacidade é importante para nós. Por favor, consulte a nossa Política de Privacidade<http://www.aubay.pt/>, que explica de que forma utilizaremos e armazenaremos a sua informação pessoal. Explica também os direitos que tem relativamente à sua informação e como pode contactar-nos para o esclarecimento de dúvidas ou pedidos.”


De: Romulo Messias <notifications@github.com>
Enviada: 12 de junho de 2019 09:51
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: Alexandre VALE <avale@aubay.com>; Mention <mention@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [Lisboa-Portugal] React/Angular Developer - Aubay (#2045)


Existe a possibilidade de trabalho remoto?
