### ISSUE TITLE
[Balneário Camboriú] Front-end na Leosoft

### ISSUE THREAD

**Issue by leocampos333** [frontendbr/vagas#2046]
## Descrição da vaga

Buscamos pessoas comprometidas, apaixonados por tecnologia e com vasto conhecimento em front-end: React, React-Native, Node, HTML5, CSS
Usamos principalmente Ruby on Rails no back-end tudo via API json
A vaga é para fazer parte de uma pequena equipe de elite, principalmente para trabalhar em novos projetos
Oportunidade para trabalhar diretamente com o founder da empresa em vários novos projetos
Apesar do trabalho poder ser feito Home-Office será necessário 1 ou 2  reuniões semanais com o diretor da empresa para alinhamento das tarefas.

## Local

Balneário Camboriú - SC
Qualidade de Vida - Uma das melhores cidades para se viver com custo de vida menor que Florianópolis

## Benefícios

- Stock-Option
- Belas Praias
- Horário Flexível
- Ótimo Salario

## Requisitos

**Obrigatórios:**
- Trabalho em equipe
- 3 anos de experiência com front-end
- HTML, CSS / SASS e JavaScript
- UX
- Mobile first
- Git
- Debug

**Desejáveis:**
- conhecimentos em ruby on rails
- Formação Acadêmica
- Participação em projetos open source

## Contratação

CLT ou PJ

## Nossa empresa

A LEOSOFT atua a mais de 20 anos no mercado de software. Tendo a inovação em seu DNA criou ou co-criou várias start-ups como Agecel, Segfy S.A., Buscacred.net, seguroi.com.br entre outros projetos desafiadores.
Atualmente está focada em Fintechs, bancos, cooperativas de crédito e outras Instituições Financeiras reguladas pelo Banco Central.
Empresa tem Escritórios em Florianópolis - SC, Balneário Camboriú - SC e Francisco Beltrão - PR

## Como se candidatar

Por favor envie um email para leonir@leosoft.com.br com seu CV e pretensão salarial - enviar no assunto: GITHUB - Front-End Developer - Nome

## Labels

- CLT
- Freela
- PJ
- Pleno
- Remoto
- Sênior

**Comment by rnsilva-amcom** [comment]
A vaga ainda está aberta?

**Comment by leocampos333** [comment]
Agradecemos todos os contatos. Vaga fechada.
