### ISSUE TITLE
[São Paulo] Front-End Developer na [Avec Brasil]

### ISSUE THREAD

**Issue by 20072013** [frontendbr/vagas#2047]
## Descrição da vaga

Desenvolver produtos web utilizados por consumidores e clientes internos
Participar da concepção de APIs (API Design)
Integração com o backend
Componentização  

## Local

 Escritório, São Paulo - Paulista

## Diferenciais

Benefícios como Gympass, descontos em salões parceiros, descontos no em cabeleleiros, barbearia;
Ambiente dinâmico e com crescimento exponencial;
Muitos desafios e aprendizados;
Cultura de feedback e 1:1;
No dress code;
Sala de “descompressão” com mesa de ping-pong (adoramos organizar campeonatos!) e puffs para dar aquela relaxada após o almoço ;)
- ...

- ...

## Requisitos

**Obrigatórios:**
Ampla experiência em Javascript (ES5, ES6), HTML e CSS
Experiência de 2+ anos com React & Redux e Styled Components
Conhecimento em TypeScript
Controle de versão (Git)
Experiência com testes automatizados, unitários e comportamentais
Vivência com desenvolvimento em ambientes e times ágeis.
Inglês intermediário 

**Desejáveis:**
- conhecimentos em ruby on rails
- conhecimentos em C#

**Diferenciais:**
Automatização de builds / tooling (Npm, Webpack) também sera considerado um diferencial
Experiência com Node será considerado diferencial

## Contratação

PJ a combinar

## Nossa empresa

Atualmente a Avec possui diversos produtos como um sistema de gestão (PHP/Laravel), um marketplace (React Native), aplicativos personalizados (Angular/Ionic), soluções de pagamento, entre outros. Estamos em busca de um Desenvolvedor Front End que tenha uma visão de negócios para planejar novos produtos, melhorar os atuais e propor novas tecnologias e arquiteturas
## Como se candidatar

Por favor envie um email para jacqueline.mello@avecbrasil.com.br com seu CV anexado - enviar no assunto: Vaga Front End/Rect

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: jacqueline.mello@avecbrasil.com.br

**Comment by viniarruda** [comment]
Enviado
