### ISSUE TITLE
[Florianópolis/SC] Desenvolvedor Front End Pleno

### ISSUE THREAD

**Issue by carloschneider** [frontendbr/vagas#205]
## Descrição da vaga

Desenvolvimento de interfaces web para e-commerce.

## Local

Escritório, Florianópolis/SC - Itacorubi

## Benefícios

- Vale alimentação ou refeição
- Vale transporte
- Plano de saúde (após experiência)
- Frutas frescas
- Café expresso

## Requisitos

**Obrigatórios:**
- Experiência com HTML, CSS e Javascript
- Conhecimento da biblioteca jQuery
- Conhecimento do framework Bootstrap
- Ter noções de grid e design responsivo

**Desejáveis:**
- Conhecimento de Sass ou Less
- Familiaridade com sistemas de controle de versão (SVN e GIT)
- Conhecimento da plataforma de e-commerce VTEX

## Contratação

CLT a combinar

## Como se candidatar

Currículos para dev-front@penseavanti.com.br

**Comment by diogomoretti** [comment]
Conheço a empresa! Boa sorte @carloschneider =]

**Comment by thallesmarchetti** [comment]
Teria alguma vaga de jr??

**Comment by carloschneider** [comment]
@thallesmarchetti Cara, não se prenda ao "Pleno" e envia seu curriculo! :D

**Comment by thallesmarchetti** [comment]
@carloschneider enviei o currículo pra vocês!

**Comment by carloschneider** [comment]
@thallesmarchetti Boa!

**Comment by luanhinkel** [comment]
@carloschneider currículo enviado!

**Comment by romuloinnocencio** [comment]
Enviado também =)

**Comment by calaca** [comment]
Enviado! :)

**Comment by AlexsandroSA** [comment]
Me too!! :)

**Comment by luizangelomedeiros** [comment]
Galera, abriu outra vaga de Front aqui na [Avanti!](http://penseavanti.com.br/) :tada:

bora mandar currículo galera! :email: :mailbox:

**Comment by diegocandido** [comment]
Empresa show! 

Pena não ter a flag remoto! ;) 

Boa sorte para quem se candidatou!

**Comment by joaoguibune** [comment]
Enviado :)

**Comment by thenewbiemaster** [comment]
enviado!
