### ISSUE TITLE
[São Paulo] Frontend Developer [Petlove]

### ISSUE THREAD

**Issue by DayaneVeronez** [frontendbr/vagas#2051]
## Descrição da vaga

Na equipe o Front-End Developer é responsável pela criação e manutenção das interfaces do website mobile e desktop da Petlove, certificando-se sempre em manter um padrão de qualidade e performance. É responsável por criar testes automatizados que assegurem o correto funcionamento dos produtos. Também é seu dever monitorar e corrigir eventuais bugs e falhas que possam ocorrer. Participa de um squad de produto, atuando em conjunto com PO, designers e demais desenvolvedores a fim de entregar sempre a melhor experiência para nossos clientes.

Buscamos pessoas apaixonadas e talentosas, que nos ajudem a concretizar novas ideias e contribuam para o desenvolvimento da nossa plataforma de produtos digitais. Estamos crescendo a todo vapor e criando novos produtos, sempre com a meta de fazer os pets mais felizes e saudáveis. Se você é um(a) profissional analítico(a), com experiência em desenvolvimento Front-end e forte background em JavaScript, temos a oportunidade perfeita pra você.

**Como Front End Developer os seus desafios serão:**

• Trabalhar em equipe multidisciplinar, usando metodologia ágil para criação e evolução 
de produtos;
• Escrever código limpo, reutilizável e de fácil manutenção;
• Ajudar a definir e manter padrões de design e arquitetura dos sistemas;
• Deployment, code review, documentação e monitoramento dos sistemas;
• Tomar decisões técnicas quando for preciso, envolvendo e alinhando equipe, clientes e stakeholders;
• Atuar como mentor, colaborando com o aprendizado dos Desenvolvedores Jr.

## Local

Escritório - [São Paulo - Berrini](https://goo.gl/maps/HarDqbMRWCL2)

## Benefícios

- Assistência médica e odontológica 100% custeada pela empresa; 
- Vale Refeição (podendo dividir com Vale Alimentação; 
- Crédito para Snacks; - Bicicletário no prédio; 
- Sala de descompressão com vídeo-game, mesa de ping-pong e pebolim; 
- Day-off de aniversário; 
- Ambiente descontraído e dinâmico; 
- Parcerias com descontos; 
- Desconto em produtos no site; 
- PLR - Atrelado a metas; 
- E claro, Pet Friendly, pets são muito bem vindos no escritório!! 

![Petlove Image](https://www.petlove.com.br/static/uploads/images/petcool.png)

## Requisitos

**O que esperamos de você:**

• GIT;
• JavaScript (ES6+);
• Vue.js ou React;
• Node.js;
• Express.js;
• HTML5;
• CSS3;
• Sass;
• WebPack ou Gulp;
• APIs REST.
• Testes automatizados

**Diferenciais:**

- Otimização SEO;
- Cache e performance;
- Service Worker;
- PWA e AMP;
- GraphQL;
- WebSocket;
- Patterns de CSS (ex: BEM);
- Infraestrutura (ex: Docker, Kubernetes, CI, Google Cloud, AWS);
- Outras linguagens (ex: PHP, Ruby, Python, Elixir);
- Experiência com e-commerce.

## Contratação

CLT

## Nossa empresa

A Petlove é o maior petshop online do Brasil. Nascemos em 1999 com a proposta pioneira de vender produtos pet pela internet e, hoje, são 20 anos entregando alegria na casa de milhares de famílias.

## Como se candidatar

Por favor envie um email para vagasti@petlove.com.br com seu CV anexado - enviar no assunto: Vaga Frontend
ou cadastre em nossa página de carreiras: https://petlove.gupy.io

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: dayane.cruz@petlove.com.br

## Labels

- CLT
- Pleno
- Sênior
- Presencial

### Conquistas e Premiações

[Melhores Apps 2017 na Apple Store](https://www.petlove.com.br/dicas/aplicativo-petlove-e-eleito-como-um-dos-melhores-ano-pela-app-store)

Primeiro pet shop Diamante Ebit

[Loja mais querida Ebit 2017](https://www.ebit.com.br/premio-ebit/2017)

[Loja mais querida Ebit 2018](https://www.ebit.com.br/premio-ebit/2018)

[RA1000 no Reclame Aqui](https://www.reclameaqui.com.br/empresa/petlove-petsupermarket/)

[Case de site mobile - Google 2018](https://www.youtube.com/watch?v=PsgW-0M67TQ&feature=youtu.be&t=17m17s)

**Comment by willycamargo** [comment]
Parabéns pela vaga.
Mas as obrigações se assemelham bastante com backend.
Também ficou confuso a parte de "Nossa Empresa".

Boa sorte na contratação.

**Comment by DayaneVeronez** [comment]
Olá!

Eu tinha apertado no botão errado e não tinha ido o perfil correto. rs
Agora a vaga está certinha! :)

**Comment by DayaneVeronez** [comment]
A vaga continua em aberto!!!
