### ISSUE TITLE
[São Paulo] Front End Developer na influu

### ISSUE THREAD

**Issue by OInternetico** [frontendbr/vagas#2052]
## Descrição da vaga

Estamos com 3 vagas para estágio/treinee para programação WEB e Mobile, os selecionados irão atuar dentro de projetos de nossa agência em um ambiente descolado;

## Local

Rua Teodoro Sampaio - Pinheiros

## Requisitos

**Obrigatórios:**

- JavaScript
- LinuxOS
- Lógica

**Desejáveis:**
- Git
- Vue
- React
- PHP

## Contratação

- Estágio

## Bolsa Auxílio
- R$1500,00 

## Nossa empresa

Somos uma agência de influenciadores digitais. Atuamos na conexão entre marcas e influencers e, além disso, trabalhamos para o desenvolvimento da carreira desses profissionais da internet. Presente nas redes sociais, em blog e website, a Influu é o lugar ideal para a prática do marketing de influência.

## Como se candidatar

Para se candidatar, enviar um e-mail com CV ou Linkedin para hernani@influu.me com o assunto “[TRAINEE_2019] Developer - {YourName}"

## Tempo médio de feedbacks

3 Dias

## Labels

- Alocado
- Estágio
- Júnior

**Comment by Luis-Souza** [comment]
aceita remoto?

Em sex, 24 de mai de 2019 às 14:28, OInternetico <notifications@github.com>
escreveu:

**Comment by developer-sp** [comment]
Currículo enviado.

**Comment by praganavictor** [comment]
Eu queria um feedback mas infelizmente não tive...
