### ISSUE TITLE
[Porto Alegre] Desenvolvedor Front-End

### ISSUE THREAD

**Issue by lsgoulart** [frontendbr/vagas#206]
## Descrição da vaga
Buscamos desevolvedor Front-end para integrar a equipe e contribuir em projetos desafiadores.

## Local

Escritório, Porto Alegre

## Oferecemos

- Salário compatível + VT + VR
- Liberdade para experimentação, inovações e crescimento
- Ambiente amigável e informal

## Perfil

- Dinâmico, organizado com prazos, orientado à qualidade e atento aos detalhes.
- Boa comunicação e senso estético.
- Ligado às novas tecnologias e tendências na sua área de atuação.
- Disponibilidade para início imediato.

## Requisitos

**Obrigatórios:**
- HTML5 (semântica)
- Pré-processadores (SASS/SCSS)
- Javascript (ES5/ES6)
- GIT/SVN
- Experiência com Design Responsivo
- Experiência com algum Task Runner (Gulp, Grunt, etc) 

**Desejáveis:**
- Conhecimento em PHP (Laravel, CodeIgniter)
- Experiência com alguma arquitetura/metodologia CSS (ITCSS, BEM, SMACSS, etc)

**Diferenciais:**
- Conhecimento em algum framework JS (Angular, VueJS) 
- Experiência com Google Tag Manager e implementação de Analytics

## Contratação

CLT

## Como se candidatar

Por favor envie um email para rh@dexdigital.com.br com seu CV anexado

**Comment by Edmundo92** [comment]
Boa noite. Tem vaga para estágio home office...? 
Eu sou de Santa Catarina / Criciuma

**Comment by romuloinnocencio** [comment]
Parece legal essa vaga =;)
