### ISSUE TITLE
[São Paulo] Fullstack Developer na Sioux Group

### ISSUE THREAD

**Issue by felipe-venturini** [frontendbr/vagas#2065]
## Missão do cargo

- Criar e manter websites, landing pages, hotsites, blogs ou aplicações web otimizadas e responsivas;
- Realizar a manutenção e melhoria em sistemas existentes;
- Garantir que a aplicação funcione em diferentes navegadores e dispositivos;
- Consumir dados de API disponibilizados pelo full-stack/back-end e dispor em um design responsivo;
- Trabalhar juntamente com desenvolvedores Back-end e Web Designers para garantir os melhores visuais e funcionabilidade;
- Manter integrações de CRM/Analytics/GTM;

## Principais responsabilidades

- Arquitetar e desenvolver novas aplicações web e integrações (50%)
- Corrigir, modificar e desenvolver novas funcionalidades das aplicações web existentes (30%)
- Testar e documentar tecnicamente a arquitetura e os softwares desenvolvidos (10%)
- Implantar em produção novas versões (10%)

## Experiência

3 anos ou +

## Conhecimento e habilidades necessárias

- HTML, CSS, JAVASCRIPT, Desenvolvimento SPA, ASP.NET/.NET CORE

## Conhecimento e habilidades desejáveis

- NodeJS, Java Springboot, noção básica de API e experiência em outras linguagens de programação/frameworks.

## Atividades e comportamentos necessários

- Pró-atividade, flexibilidade, cooperação, organização, disciplina, senso crítico e que goste de aprender e estudar

## Como se candidatar

Por favor envie um email para rh@sioux.com.br com seu CV anexado.

## Labels

- Alocado
- CLT
- PJ
- Pleno
- Sênior

**Comment by leandrosouza0786** [comment]
Só uma dúvida, se exige "ASP.NET/.NET CORE" a vaga seria para fullstack certo?
