### ISSUE TITLE
[NOVO HAMBURGO] Estágio como Front-end Developer na Codeminer42

### ISSUE THREAD

**Issue by abnersajr** [frontendbr/vagas#2066]
## Sobre a Codeminer

A Codeminer42 é uma butique de software brasileira focada em entregar o melhor valor a seus clientes. Começando suas operações em Setembro de 2011, já expandimos para 12 cidades diferentes no Brasil com os melhores profissionais e desenvolvedores do Brasil.

## Nossos desafios

Nós somos miners.

Entregar valor em qualquer projeto é um processo difícil. Como desenvolvedores de software nos esforçamos para entregar não somente código bem escrito, mas código que entrega valor real a cada cliente.

Não é bom o suficiente se preocupar apenas com código pelo código, mas entregar código que resolve problemas reais e entregam valor real. E essa é a missão que nós, como miners, vamos continuar cavando fundo para cumprir.

## Os seus desafios

Na Codeminer42 você terá a oportunidade de trabalhar com os mais diversos tipos de projetos, com tecnologias variadas e um time de pessoas incríveis que estarão sempre prontas a te ajudar no que você precisar. Na Codeminer42 incentivamos o diálogo e o compartilhamento de conhecimento e apoiamos o desenvolvimento open-source.

Alguns desafios farão parte dessa trajetória:

- Trabalhar juntamente com times diversificados;
- Buscar novos conhecimentos e tecnologias;
- Não ter medo de se adaptar. Buscamos e incentivamos o aprendizado;
- Saber se comunicar é de extrema importância.

## Os requisitos

- Conhecimento da base do Javascript e suas novas features (ES6 e afins).
- Conhecimento em algum dos UI Frameworks: React, VueJS, React Native ou Angular. Experiência com algum outro não listado é analisado individualmente. Mas não deixe de entrar em contato.
- **Inglês intermediário. O inglês é de extrema importância, você terá incentivo para aperfeiçoar seu inglês.**

Algumas habilidades técnicas que são pontos extras:

- Conhecimentos em NodeJs
- Conhecimentos em Ruby e Ruby on Rails
- Conhecimentos de infra-estrutura. Heroku e AWS são amplamente utilizados no dia a dia.

## Os benefícios

1. Auxílio transporte;
2. Vale-refeição;
3. Ambiente de trabalho descontraído;
4. Acesso a cursos e portais de educação como Front-end Masters e egghead.io;

### Diferenciais

- Horário flexível
- Oportunidade de trabalhar em projetos de grande impacto nacionais e internacionais

## Como se candidatar

Envie um e-mail para abner.alves@codeminer42.com com seu currículo anexado, LinkedIn, Github e demais informações que achar interessante para nós.

Maiores dúvidas não deixe de perguntar.

Temos também vaga de estágio para Back-end com NodeJs e Ruby. Caso tenha interesse pode entrar em contato pelo mesmo e-mail.

## Labels

- Alocado
- CLT
- Estágio

**Comment by felipenoka** [comment]
@abnersajr existe a possibilidade de estágio remoto? :)

**Comment by abnersajr** [comment]
@felipenoka obrigado por perguntar, como tem nas labels, o estágio é alocado apenas.
É extremamente importante e saudável, no processo de estágio estar no mesmo ambiente da galera.

**Comment by abnersajr** [comment]
Ainda estamos em busca de uma pessoa para fazer parte do nosso time. Se alguém tiver alguma dúvida não deixe de perguntar.
