### ISSUE TITLE
[Florianópolis/SC] Front-end Developer na Mettzer

### ISSUE THREAD

**Issue by sergiofm** [frontendbr/vagas#2069]
## Descrição da vaga

Curte pesquisa científica, academia, ciência? Então a Mettzer é o lugar ideal pra você!
Somos uma Startup que nasceu com o objetivo de democratizar a pesquisa científica mundial. 
Venha fazer parte do nosso time e ajude a desenvolver a nossa plataforma de gestão e desenvolvimento de pesquisa científica.

## Local

Presencial com possibilidade de Remoto. Nosso escritório fica na Acate, SC-401

#### Diferenciais

Ambiente descontraído, sem muitas formalidades e horário flexível.

## Requisitos

**Obrigatórios:**
- Experiência com React.js

**Diferenciais:**
- Experiência em projeto com colaboração real-time é um puta diferencial!
- Experiência com Slate.js é um grande diferencial!
- Experiência com desenvolvimento back-end e MongoDB ajuda.

## Contratação

CLT

## Como se candidatar

Envie um email para sergio@mettzer.com com seu github, linkedin e/ou CV, colocando no assunto: Vaga Front-End Developer

## Labels

- Alocado
- Remoto
- CLT
- Pleno
- Sênior
- Florianópolis

**Comment by rsornellas** [comment]
Empresa top, recomendo!

**Comment by emanuelgsouza** [comment]
Olá! A vaga ainda está aberta?
