### ISSUE TITLE
[Blumenau/SC] Front-End Developer na Serasa Consumidor

### ISSUE THREAD

**Issue by SelecaoSerasaConsumidor** [frontendbr/vagas#2070]
**Voltamos**
Se você não sabe, as últimas duas vagas abertas de Front-End aqui no Serasa Consumidor foram preenchidas através deste canal. https://github.com/frontendbr/vagas/issues/1906#issuecomment-487436726

**Agora voltamos com mais uma oportunidade**

**Você quer trabalhar em um ambiente com tecnologia de ponta e uma equipe altamente capacitada para mudar a vida financeira do consumidor brasileiro?**

Já somos uma das maiores empresas digitais do mercado financeiro e estamos desenvolvendo produtos e serviços que vão mudar a forma como o brasileiro se relaciona com o dinheiro.

Somos um time com brilhos nos olhos, multidisciplinar e com autonomia para propor ideias. Se você é apaixonado pelas transformações do mundo digital, não tem medo de assumir riscos e quer sentir-se “dono do negócio”, vem trabalhar com a gente!

### O que buscamos?

É imprescindível experiência com Javascript (ECMAScript 2015+), HTML, CSS, REST APIs, React, Angular e Testes (Jasmine, Jest, Mocha, Chai ou outros). Experiência avançada em versionamento de código. Vivência com Design Responsivo e Mobile First. Atuação com produtos 100% digitais. Inglês técnico.

### O que pode diferenciar você?

 Atuação em ambiente de startup e ambiente 100% digital. Experiência com arquitetura e desenvolvimento Cloud (AWS, Google Cloud). Experiência profissional em ambiente ágil.

### Oferecemos:

- Produtos com a possibilidade de fazer história e deixar legado!
- Ambiente desafiador e High Performance
- Times multidisciplinares e Multiculturais
- Pacote salarial atrativo;
- Pacote de benefícios;
- PLR anual; 
- Previdência privada;

Contato: robson.cardoso@br.experian.com ou https://www.linkedin.com/in/robsonscheffer/

**Comment by nandomoreirame** [comment]
não posso entrar nessa empresa ai não... to com o cpf negativado.
