### ISSUE TITLE
[Jardins - São Paulo/SP] Front-End Developer na Mobi

### ISSUE THREAD

**Issue by rhuzianjr** [frontendbr/vagas#2071]
Projetos em Laravel, Ionic e React

Nivel Pleno - PJ - Remoto ou Escritório, São Paulo - Jardins

PJ a combinar

## Nossa empresa

A Mobi é uma empresa especializada em desenvolvimento de Soluções Digitais.

Atender os desafios das soluções digitais de nossos clientes, buscando excelência no uso das melhores ferramentas e plataformas disponíveis na internet com o objetivo de alcançar níveis superiores de produtividade e resultados.

## Como se candidatar

Por favor envie um email para ricardo@mobiaplicativos.com.br com seu CV anexado - enviar no assunto: Vaga Front-End.

**Comment by gabrielsouza1** [comment]
Não consigo manda e-mail para vocês

**Comment by rhuzianjr** [comment]
Ola Anderson...tente no meu pessoal Ricardo.huzian@gmail.com 

 

De: Anderson Gabriel de Souza <notifications@github.com>
Responder para: frontendbr/vagas <reply@reply.github.com>
Data: segunda-feira, 3 de junho de 2019 11:52
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: rhuzianjr <ricardo@mobiaplicativos.com.br>, Author <author@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [Jardins - São Paulo/SP] Front-End Developer na Mobi (#2071)

 

Não consigo manda e-mail para vocês

**Comment by rhuzianjr** [comment]
Agradeço a todos os candidatos que se interessaram pela vaga, mas o processo foi finalizado.
