### ISSUE TITLE
[São Paulo] Front-End Developer na EVNTS

### ISSUE THREAD

**Issue by evnts-dev** [frontendbr/vagas#2072]
## Descrição da vaga

Atuação com Desenvolvimento Web utilizando React, sendo responsável pelas boas práticas de Javascript/React, performance e usabilidade. Possibilidade de atuar com back-end

## Local

WeWork Paulista (em frente à estação de metrô Trianon - MASP) 
Endereço: Avenida Paulista, 1374

## Benefícios

- Vale-alimentação
- Vale-refeição
- Vale-transporte

#### Diferenciais

- Flexibilidade de horários e possibilidade de trabalho remoto 
- Ambiente informal e descontraído

## Requisitos

**Obrigatórios:**
- Habilidade analítica e realização de trabalho em equipe
- Experiência com Javascript (com orientação a objetos)
- Experiência com React ou Angular (framework javascript)
- Conhecimento em HTML e CSS

**Desejáveis:**
- Gestão/cursos de metodologia ágil (SCRUM, XP entre outros)
- Arquitetura frontend
- Conhecimento de backend (node)

## Contratação

CLT/PJ (a combinar)

## Nossa empresa

A Evnts é a empresa líder no mercado brasileiro em reserva de hotéis para grandes eventos. Entre milhares de parceiros trabalhamos com Rock in Rio, Lollapalooza, HSM, Salão do Automóvel, TDC, QCon e muitos outros. E é claro, visitamos e nos divertimos em alguns deles também :) 
Com 03 anos de mercado, conquistamos +70% do market share de eventos de médio e grande porte no Brasil. Estamos a procura de profissionais para nos ajudar a dar os próximos grandes passos no segmento, como internacionalização e a criação de um novo produto. Esse produto consiste em mudar a forma como o mercado se comporta em relação a eventos corporativos. Estamos revolucionando a maneira como as empresas organizam seus eventos, viagens e reuniões e precisamos de você para nos ajudar nesta jornada!  

## Como se candidatar

Por favor envie um email para vagas@evnts.com.br com seu CV anexado - enviar no assunto: Vaga Front-Ent Developer - [SEU NOME]

## Labels

- Alocado
- CLT
- PJ
- Pleno
- Remoto

**Comment by brect** [comment]
Bom dia, tudo bom?


Segue anexo o meu currículo.

Obrigado.

At.te,
Bruno Lima
(11) 96415-0140

Em qui, 30 de mai de 2019 às 19:46, evnts-dev <notifications@github.com>
escreveu:
