### ISSUE TITLE
[Belo Horizonte] Desenvolvedor FrontEnd Angular na SYS10

### ISSUE THREAD

**Issue by megandavulpi** [frontendbr/vagas#2081]
### Sobre a empresa: SYS10

A SYS10 é uma empresa com espírito jovem, formada por uma equipe multidisciplinar. Acreditamos que a diversidade e as diferentes perspectivas constroem soluções mais criativas e inovadoras. 

Criamos experiências digitais a partir de uma visão holística do projeto, sem perder o foco do usuário final. Unimos o raciocínio analítico, conhecimento tecnológico e empatia para criar produtos eficientes e que atendam as reais necessidades dos nossos clientes.

### Descrição: Ocupações do cargo:

**Estamos em busca de uma pessoa Desenvolvedora Front end.**

### Conhecimentos obrigatórios:

Vue.js;
React;
Angular;

### Conhecimentos desejáveis:

Jquery;
SQL;
Node.
MVC;
Lavarel;
.net.

### Benefícios:

Vale refeição (R$21.35 - sem desconto);
Plano de saúde (Bradesco Nacional -sem coparticipação);
Vale Transporte (sem desconto);
PPLR (do sindicato);
13°.

### Aptidões e qualidades:

Boa capacidade de aprendizagem para absorver o conhecimento;
Pessoa pró-ativa;
Pessoa referência técnica.

### Candidatar: http://bit.ly/sys10_front

**Comment by danielswater** [comment]
Remoto?

**Comment by megandavulpi** [comment]
> Remoto?

Presencial =)
