### ISSUE TITLE
[REMOTE][FREELANCER][FINTECH] Desenvolvedor VUE.JS

### ISSUE THREAD

**Issue by walterjrp** [frontendbr/vagas#2085]
## Descrição da vaga

Estamos em busca de um desenvolvedor front-end com experiência em Vue.JS para fazer parte do desenvolvimento da plataforma web de uma Fintech. 
O desenvolvedor será responsável por dar manutenção nas funcionalidades existentes e criar novas funcionalidades com base em nossa REST API desenvolvida em Laravel + Mongo.

## Local

Remoto.

## Nossa empresa

A vaga é confidencial e você receberá maiores informações sobre a empresa após análise.
Se tiver projetos mostrando suas skills, ótimo.

## Contratação

Inicialmente o desenvolvedor será freelancer, recebendo por hora trabalhada.
É interessante informar quantas horas diárias em média você teria disponível para fazer parte do desenvolvimento.
Como o trabalho será pago por hora, existe uma certa flexibilidade, você pode trabalhar 5, 6, 8 horas e tudo será acordado de acordo as horas trabalhadas.

## Como se candidatar

Por favor envie um email para walter.jrp@live.com com seu CV anexado - enviar no assunto: Vaga Desenvolvedor VUE.JS

## Labels

- Remoto
- VUE.JS
- Fintech

**Comment by MrS4w** [comment]
Vaga confidencial?
