### ISSUE TITLE
[Niterói] Front-End Developer na [Internit]

### ISSUE THREAD

**Issue by Fredpeixoto** [frontendbr/vagas#2086]
## Descrição da vaga

Saca de HTML e CSS? É fera em implementar sites em Wordpress? É responsa com prazos? Então leia mais sobre a vaga:

A Internit é uma desenvolvedora web em Niterói com 22 anos de mercado e mais de 1.500 projetos entregues. Estamos abrindo 1 vaga para front-ends. O trabalho será o trabalho de front-end para criação e atualização de sites, portais, lojas virtuais, sistemas, aplicativos e outros.

## Local

Escritório em Niterói

## Benefícios

- Salário
- VT
- VR 

#### Diferenciais

Estamos situados em uma rua calma com vaga para estacionar carro. Temos espaço para quem vem trabalhar de bicicleta. A empresa fica bem perto de Icaraí, ao lado do La Salle e Abel. Local com fácil acesso a transporte público para todas as principais regiões de Niterói como Icaraí, Centro, RO, Pendotiba, Fonseca entre outras. Após um tempo na empresa, avaliaremos as suas entregas e para alguns funcionários, disponibilizamos a possibilidade de até 2 dias de trabalho home Office. Como estamos em uma casa, possuímos estrutura para o caso de você quiser fazer as refeições dentro da empresa, se você preferir. Somos mais de 20 colaboradores e devido ao ótimo ambiente de trabalho e boa relação com a direção da empresa, os bons colaboradores costumam ficar anos trabalhando conosco. Nosso ecossistema estimula o desenvolvimento técnico e ao empreendedorismo.

## Requisitos
Requisitos obrigatórios: Conhecimento avançado em HTML5, CSS3, JavaScript com Jquery, Design responsivo e implantação de sites em WordPress. Pode ser formado ou estar cursando faculdade na área. Mas tem que tem experiência na função. 

**Desejáveis:**
Diferenciais: Conhecimento em React, Twig (Symfony3) implementação de projetos em Magento.

## Contratação

PJ ou CLT

## Nossa empresa

Aqui na Corporação ACME somos líderes em...

## Como se candidatar

Se cadastrar no nosso site
https://www.internit.com.br/curriculo

## Tempo médio de feedbacks

15 dias até 1 mês

## Labels

- CLT
- Junior
- PJ
- Pleno

**Comment by evertonnppp** [comment]
ola amigo me chama no whats app whtasapp 21992433897

**Comment by evertonnppp** [comment]
Responde direito nao entendir

Em sexta-feira, 6 de setembro de 2019, Victor Λntonio <
notifications@github.com> escreveu:

**Comment by evertonnppp** [comment]
Hi frontendbr,

Join me in sharing and discovering books on Goodreads!

https://www.goodreads.com/friend/i?e=reply%2BAKVPOXECAB4YKH3C5QRTHLV3P7D3ZEVBNHHBWAC6SA%40reply.github.com&invite_token=NzQ2ZjA4ZjEtNzY0Mi00MTAxLTk5MWUtOGNiNmVmN2JlZTYx&n=frontendbr&utm_medium=email&utm_source=invite

- Everton
(evertonasdfgh@gmail.com)

Goodreads is a community for book lovers. It's a great way to get book recommendations from your friends and others. You can keep a list of books to read, join book clubs, and even take the never-ending book trivia quiz.


_____________________________


This email was sent by request to reply@reply.github.com.
To opt-out of future invites to Goodreads please follow this link: https://www.goodreads.com/user/block_email?email_to_block=c25GdmxIcFh2WmlYc1NQVkE2OGh1bGVlcGE1RHlwNGdWVk0wT3JZZVRvZTNRakhiZ1dKZ2F6TGZFNXVUdmt1SHRpcGxIdldaaWVHdHl2RVNEbXlWaVZsR0Q2WE1lWUQ5RUdnMUJPdHVDdms9LS02NVJ1TDhWQjVDU2svb3Q4UU9SYUR3PT0%3D--5c7d6a277949267a783eb83e79d94921c4ed89e2&utm_medium=email&utm_source=invite

(c) 2020 Goodreads, Inc.
188 Spear Street, Suite 250, San Francisco, CA 94105


Privacy policy:
https://www.goodreads.com/about/privacy?utm_content=_privacy&utm_medium=email&utm_source=invite
