### ISSUE TITLE
[Rio de Janeiro] Front-end Developer na Volanty

### ISSUE THREAD

**Issue by leonardodavila** [frontendbr/vagas#2089]
## Descrição da vaga

Você fará parte do time de produto da Volanty, que é composto por Desenvolvedores e UXers e a nossa missão é criar a melhor experiência para os clientes Volanty utilizando as melhores tecnologias.

Se você é um entusiasta de tecnologias novas, gosta de aprender e ensinar, e desenvolver produtos. Então tem o perfil que queremos para o nosso time, vem ser um Volanty!

## Local

Botafogo - RJ

## Benefícios

- Plano de saúde
- VR de R$ 30/dia
-  VT
-  Desconto de funcionário para compra de seminovos na Volanty

#### Diferenciais

- Ambiente de trabalho descontraído e dinâmico
- Somos uma startup, respiramos inovação
- Não desenvolvemos apenas software, também desenvolvemos pessoas 😄
- Work from home - possibilidade de trabalhar de casa durante alguns dias da semana

## Requisitos

**Obrigatórios:**
- Sólidos Conhecimentos de JavaScript, HTML5, CSS3;
- Git
- Conhecimento de algum framework js (React / Vue.js)

**Desejáveis:**
- NodeJS
- RESTFul Apis
- Testes (Unitários, Snapshot, integração...)

**Diferenciais:**

- Conhecimentos sobre PWA
- Amazon AWS
- Docker
- CI / CD
- Conhecimentos de UI/UX
- Conhecimentos de alguma linguagem de back-end (NodeJS, Java, Python...)

## Contratação

CLT - a combinar

## Nossa empresa

A Volanty é uma startup marketplace de carros seminovos.
A missão da Volanty é mudar o jeito que as pessoas compram e vendem carro no Brasil e na América Latina. Nossa meta no curto prazo é transacionar milhares de veículos por mês e se tornar líder desse mercado.
Na Volanty,  trabalhamos com muita autonomia e criatividade. O ambiente de trabalho é um espaço informal, descontraído e integrador, porém com muito compromisso com a qualidade da experiência e do produto, onde há muita oportunidade para se arriscar e aprender fazendo.
Estamos em um momento de muito crescimento! Buscamos pessoas dinâmicas, proativas, motivadas, ambiciosas, divertidas e do bem, pra virem junto com a gente.

## Como se candidatar

Por favor envie um email para jessica@volanty.com com seu CV anexado - enviar no assunto: Vaga Front-end Developer [Nível desejado JR, PLENO, SENIOR]

## Labels

- Alocado
- CLT
- Júnior
- Pleno
- Sênior

**Comment by leonardodavila** [comment]
Pessoal, só para esclarecer a dúvida que eu possa ter gerado. A vaga é presencial, um diferencial é que podemos trabalhar de casa durante alguns dias da semana. Mas é necessário que o desenvolvedor esteja no Rio de Janeiro.

Desculpa por algum possível inconveniente.

**Comment by evertonnppp** [comment]
ola amigo me chama no whats app whtasapp 21992433897

**Comment by leonardodavila** [comment]
UP! Galera, ainda estamos em busca de desenvolvedores front-end!

**Comment by antoniotex** [comment]
Opa, enviando! =)

**Comment by LucasHiago** [comment]
triste notícia, moro no meio do mato =( https://lucashiago.github.io/admin/dashboard
