### ISSUE TITLE
[Rio de Janeiro] Angular JS Developer na Resource

### ISSUE THREAD

**Issue by fabianodeoliveiraesouza** [frontendbr/vagas#2091]
## Descrição da vaga

Profissional para atuar em projeto de melhoria contínua com Angular JS.

## Local

Botafogo, Rio de Janeiro

## Benefícios

- Plano de saúde Sulamerica Exato Apto com cooparticipação
- Convênio Odontológico - Porto Seguro
- Seguro de vida
- VR de R$ 440,00
- Auxílio creche
- Convenio Farmácia

#### Diferenciais

Uma Tech Partner focada na entrega de transformação digital! #ResourceTransforma #TemosVagas

## Requisitos

**Desejáveis:**
- Conhecimento front-end Angular JS

**Diferenciais:**
- Webpack, Sass, CSS3, EcmaScript 6, git flow  

## Contratação

CLT Full

## Como se candidatar

Por favor envie um email para fabiano.souza@resourceit.com com seu CV anexado e pretensão salarial - enviar no assunto: Vaga Angular Rio de Janeiro

## Labels

- alocação/Presencial
- experiência/Junior
- experiência/Pleno
- experiência/Sênior
- regime/CLT

**Comment by evertonnppp** [comment]
meu whats app me chame por favor
992433897
