### ISSUE TITLE
[Maringá/PR ou Remoto] Front-End Developer na DB1 Global Software

### ISSUE THREAD

**Issue by cristianeabe** [frontendbr/vagas#2093]
## Descrição da vaga

Procuramos alguém que seja especialista em desenvolvimento front-end, para atuar em projeto com VueJS

## Local

Maringá-PR ou Remoto

## Benefícios

- Cesta de benefícios personalizada, com opções como:
- Vale Alimentação
- Vale Refeição
- Plano de Saúde
- Plano odontológico
- Auxílio Creche
- Auxílio Educação

#### Diferenciais

- Horário Flexível
- Dress Code casual

## Requisitos

**Obrigatórios:**

- Experiência com VueJS
- CSS3 / HTML5
- Sass/Less/Stylus
- Testes Unitários

**Desejáveis:**
-  Experiência em Arquitetura CSS: B.E.M. e/ou SMACSS e/ou OOCSS​

## Contratação

CLT

## Nossa empresa

A DB1 Global Software é uma empresa especializada em Fábrica de software, com atuação no Brasil e exterior, certificada no CMMI Nível 3. 
Buscamos pessoas talentosas que queiram fazer parte deste time de Feras, que são responsáveis e tem influência em tudo o que ocorre à sua volta, que investem no crescimento profissional e humano, que AMAM tecnologia e desafios, que são e promovem LUZ na vida de outras pessoas através do desenvolvimento de softwares de qualidade. 

## Como se candidatar

Por favor envie um email para cristiane.abe@db1.com.br com seu CV anexado - enviar no assunto: Vaga VueJS

## Labels

- Remoto
- Maringá/PR
- CLT
- Pleno
- Sênior

**Comment by emanuelgsouza** [comment]
Olá! A vaga ainda está aberta?
