### ISSUE TITLE
[São Paulo] Front-End Developer na [OSBR]

### ISSUE THREAD

**Issue by VagasOSBR** [frontendbr/vagas#2095]
## Descrição da vaga

Desenvolvedor Front-End React/React Native

## Local

- Ambiente de trabalho inovador (We Work São Paulo)
- Fácil acesso pelo Metrô Trianon-MASP

## Benefícios

- Assistência Médica diferenciada
- Auxilio Alimentação
- Férias

#### Diferenciais

- Chopp :P
- Sala de jogos

## Requisitos

**Obrigatórios:**
- Experiência mínima de 3 anos em:
- React
- Redux
- GraphQL
- HTML
- CSS/SASS
- Javascript
- Jquery
- Design responsivo e noções de UX/UI

**Desejáveis:**
- .Net C#
- .Net Core
- SQL Server e/ou Oracle
- MongoDB
- Conhecimento de arquitetura Front e Back

**Diferenciais:**
- PWA
- Desenvolvimento mobile Objective-C e Java Android

## Contratação

PJ a combinar com prazo indeterminado

## Nossa empresa

OSBR#REACT

Somos a OSBR - Optimus Serviços do Brasil, utilizamos as melhores e atuais tecnologias do mercado, transformamos dados em informações e insights para tomada de decisão, respeitando o momento e a cultura das empresas, visando a melhoria de desempenho na gestão do negócio, balizando a tomada de decisão através de indicadores. 
Otimizamos o processo de nossos clientes através de workflows, sistemas customizados, apps, sites e intranets.

Venha! Junte-se a nós!

## Como se candidatar

Por favor envie um email para paulo.bispo@osbr.com.br com seu CV anexado.
Enviar no assunto: Vaga OSBR#REACT

## Labels

- 🏢 Presencial
- 👴 Sênior
- ⚖️ PJ
- 💰 São Paulo

**Comment by lucasrz** [comment]
É possivel ser remoto?

**Comment by VagasOSBR** [comment]
Boa tarde!

Lucas,

Essa vaga é presencial .

Grato e a disposição,

[cid:image008.png@01D44C4A.90FABF70]
Paulo Bispo
(011) 4780-3785
(011) 94187-5490
Optimus Serviços do Brasil
www.osbr.com.br<http://www.osbr.com.br/>


De: lucasrz <notifications@github.com>
Enviada em: terça-feira, 11 de junho de 2019 14:18
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: Paulo Bispo - OSBR <paulo.bispo@osbr.com.br>; Author <author@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [São Paulo] Front-End Developer na [OSBR] (#2095)


É possivel ser remoto?
