### ISSUE TITLE
[Volta Redonda - RJ] Front-End Developer na COUT

### ISSUE THREAD

**Issue by lincolnlemos** [frontendbr/vagas#2097]
## Descrição da vaga

Desenvolvedor front-end/full-stack com habilidades de liderança para coordenar nosso projeto. Temos budget de até R$ 5.000/mês para remuneração + % em equity conforme experiência do candidato. 

Nossa stack atual é angular/laravel, mas estamos abertos para novas idéias. 

## Local

Volta Redonda - RJ

## Benefícios

- Flexibilidade

#### Diferenciais

- Equity

## Requisitos

**Obrigatórios:**
- Domínio em JS
- Atitude 

**Diferenciais:**
- Histórico de empreendedorismo e liderança 

## Contratação

A combinar

## Nossa empresa

Somos uma startup pequena com foco inicial em gestão de escalas, mas o roadmap é ser uma plataforma profissional completa. A vaga é presencial em Volta Redonda - RJ até final de 2020. Depois existe a possibilidade de tocarmos o projeto remotamente.

## Como se candidatar

Enviar um email para vagas@cout.app dizendo o porque você acredita ser um candidato ideal para essa vaga. 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dia após cada processo.

## Labels

- Alocado
- CLT
- Pleno
- Remoto
- Sênior

**Comment by gabrigcl** [comment]
Olá, gostaria de saber se é necessário que o candidato seja full-stack.

**Comment by marcio133** [comment]
Se vaga é presencial não deveria estar com a tag de remoto.

**Comment by lincolnlemos** [comment]
@gabrigcl não. O único requisito obrigatório técnico é domínio em javascript.

@marcio133 Sorry. Achei que valesse o tag pois existe a possibilidade real do time ser todo remoto após um tempo.

**Comment by evertonnppp** [comment]
ola amigo me chama no whats app whtasapp 21992433897

**Comment by caiquesandrade** [comment]
Ta aberto a vaga ainda ? Sou de Volta Redonda.
