### ISSUE TITLE
[Berlim - Alemanha] Senior Frontend Engineer

### ISSUE THREAD

**Issue by elvisdetona** [frontendbr/vagas#21]
## Descrição da vaga

Para desenvolver um novo produto, estamos à procura de um desenvolvedor javascript sênior (homem ou mulher), com muita experiência e uma paixão por melhores práticas de desenvolvimento..

## Local

Precisa trabalhar alocado, em Berlim, na Alemanha (não pode ser remoto, precisa mudar para lá).

## Benefícios

- Interesting and challenging work on market-proven products that already positively affect the future career decisions of tens of thousands of professionals in various countries;
- Nice, down-to-earth and experienced colleagues who have big ambitions to make a dent in the recruiting universe;
- Working in a nice and bright office in the middle of Berlin-Kreuzberg and all the latest equipment you need to be super productive;
- A competitive salary of around 50-60k, depending on experience;
- Several perks & benefits, such as free drinks and food in the office, Telekom hotspots, monthly travel pass (BVG ticket), regular team events (from basketball matches to TEDx conferences), lots of free (or heavily discounted) vouchers, leisure activities, etc;
- And finally, after probation period, every team member can participate in our stock ownership programme.

## Requisitos

- Minimum 5 years of experience with JavaScript in production settings;
- Minimum 2 years of experience with single page applications using Angular/React/Backbone or especially Ember.js;
- Strong experience with automated testing and TDD;
- Experience with Node.js, cross-browser support (incl. mobile), HTML5, ES6, CommonJS, Git;
- Good knowledge of agile processes (Scrum, XP, Kanban);
- Ideally, you also have experience with vagrant, WebRTC, WebSockets / Socket.IO, and microservice architectures;
- A good feel for great user experience and design;
- Very good communication skills and business fluent English (German is not required, but would be an advantage);
- Finally, we appreciate great team spirit, a sound business understanding and the motivation to build fantastic products.

## Contratação

Registro Formal

## Nossa empresa

https://www.viasto.com/

## Como se candidatar

Por aqui - https://viasto.softgarden.io/job/361208/Senior-Frontend-Engineer
** Se quiser indicação, candidate-se e depois me avise que faço a indicação **

**Comment by LFeh** [comment]
Elvis, sabe se a vaga foi preenchida?

**Comment by elvisdetona** [comment]
Foi sim, na primeira semana @LFeh

**Comment by camilatigre** [comment]
@elvisdetona 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by elvisdetona** [comment]
b)

**Comment by camilatigre** [comment]
Blz obrigada por responder

Em 24 de nov de 2016 13:59, "Elvis Detona" <notifications@github.com>
escreveu:
