### ISSUE TITLE
[São Bernardo do Campo] Desenvolvedor Full-stack na Blue Fit

### ISSUE THREAD

**Issue by thiagomarinheiro89** [frontendbr/vagas#2100]
Sobre a empresa: Blue Fit
Somos uma das rede de academias que mais cresce do Brasil, contamos atualmente com 60 unidades e expectativa de crescimento para 2020 de até 90.

Sobre a vaga:
CLT / Presencial

Descrição: O que você irá fazer?
O profissional irá atuar junto a nossa equipe de desenvolvimento, atuando em toda parte de gestão, além de realizar implantação e integração com novas funcionalidades.

Requisitos:
PHP (orientado a objeto);
JavaScript;
HTML;
CSS;
Bootstrap;
jQuery.
Conhecimento em Cordova e desenvolvimento mobile é plus.

Aptidões e qualidades
Profissional com boa comunicação e convivência, além de bons conhecimentos em lógica, que faça um ótimo café (isso é quase que essencial).

Informações complementares
Localização: SBC
Horário: Segunda à Sexta das 9h00 as 18:48

Para se candidatar:
Enviar CV + Pretensão Salarial para thiago.marinheiro@bluefitacademia.com.br

**Comment by tvmota** [comment]
@thiagomarinheiro89 mandei email mas voltou, teria outro email?
