### ISSUE TITLE
[São Paulo] Front-End Developer na DEX

### ISSUE THREAD

**Issue by raoferreira** [frontendbr/vagas#2101]
## Descrição da vaga

Somos a Dex, uma empresa focada em melhorar a produtividade de grande empresas utilizando metodologias de startup e desenvolvimento ágil. Uma software house com vontade de deixar o mundo mais rápido e transparente. Estamos buscando desenvolvedores com conhecimento de React.Js para nos ajudar a construir esse mundo.

## Local

Estamos em Alphaville (Barueri, SP) hoje mas como aqui não tem nada de legal, então em julho estamos mudando para a região de Pinheiros em SP, bem perto de algum metrô. Stay tuned.

## Benefícios

- VR
- VT

#### Diferenciais

- horários flexíveis
- acreditamos que quanto mais conhecimento, melhor, então queremos que vc estude!
- cultura sempre em construção (nos ajude a construir uma cultura inclusiva e motivadora)
- tem café a vonts

## Requisitos

**Obrigatórios:**
- conhecimento em React.Js.

**Desejáveis:**
- já ouviu falar de Mongo.DB?

**Diferenciais:**
- se você já trabalhou com isso antes e gostou, aposto que vai ser incrível

## Contratação

CLT

## Nossa empresa

Realmente acreditamos que nossa equipe pode mudar o mundo e para isso sempre trabalhamos com muita energia. Somos bem novos (dez17), então obviamente tem muito mais risco do que uma empresa consolidada, mas tentamos criar um ambiente tranquilo, amigável onde você pode aprender muito com todo mundo em volta. Queremos que as pessoas que estão na empresa ajudem a moldar nossa cultura da melhor forma possível. Caso tenha dúvidas, ficaremos contentes em te conectar com nosso líder técnico ou qualquer colaborador para te ajudar a esclarecê-las.

## Como se candidatar

Por favor envie um email para dex@dex.company com seu CV anexado. 

## Tempo médio de feedbacks

Costumamos responder na mesma hora mas tentamos valorizar a vida fora do escritório, então já já te respondo =)
E-mail para contato em caso de não haver resposta: rao@dex.company.

## Labels

- CLT
- Júnior

**Comment by TrindadeThiago** [comment]
Boa tarde, o endereço para se candidatar a vaga está retornando como não reconhecido.

**Comment by raoferreira** [comment]
@TrindadeThiago email ajustado! Obrigado!

**Comment by GustavoPrizon** [comment]
Enviado!
