### ISSUE TITLE
[São Paulo/SP] Front-End Developer na TLO

### ISSUE THREAD

**Issue by cdcaetano** [frontendbr/vagas#2103]
## Descrição da vaga

Nós todos, em algum momento de nossas vidas, iniciamos o processo de aprendizagem nessa área tão difícil, que exige muito de nosso tempo. E todos nós, independente do nível em que estamos, continuamos aprendendo diariamente.

Também passei por isso. E, no meu caso em específico, existia um problema extra: a necessidade de uma renda. Para consegui-la eu só tinha duas opções: sacrificar tempo dos meus estudos em algo que eu já era apaixonado, indo trabalhar em outra área, ou iniciar minha carreira como desenvolvedor.

A segunda opção era a perfeita, obviamente. Exceto por um pequeno problema; a minha pouca experiência. Apesar de estar estudando já há quase 1 ano, eu não conseguia encontrar uma vaga de emprego em que eu me encaixasse. Eu precisava comprovar experiência anterior, na maioria delas, e as que não exigiam isso, pediam estar cursando, na faculdade, alguma área da programação. 

Que época triste! Eu tinha a vontade de aprender e trabalhar nessa área, mas não tinha os meios. Pois… Sem desistência e dormindo 4 horas por dia, consegui seguir alguns meses na primeira opção, então, e ainda continuar com meus estudos.

Documentações e mais documentações, projetos e mais projetos gratuitos, consegui meu primeiro serviço como freelancer. E, após isso, finalmente, consegui entrar na área que tanto gostava.

Pensando em membros da comunidade de desenvolvimento e colegas de estudo que estão passando pela mesma situação que um dia passei, abro essa vaga.

Não é necessário conhecimentos avançados ou intermediários. O mais importante é que você tenha vontade de aprender e saiba utilizar o Google para isso. Durante os projetos, você terá auxílio e ajuda de desenvolvedores experientes.

Se você está procurando por uma maneira de adquirir mais experiência e ter uma renda na época de seus estudos, venha conversar conosco. Nos conte sua história!

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência com Git
- Vontade de aprender
- HTML5
- JavaScript

## Tecnologias que utilizamos na TLO
- Laravel
- WordPress e WooCommerce
- NodeJS
- Ionic
- Banco de Dados SQL

## Contratação

Freelance com possibilidade de efetivação

## Nossa empresa

O nosso foco na TLO é ajudar. Ajudar nossos programadores e nossos clientes. Um ambiente leve que tenta, ao máximo, eliminar a pressão psicológica estabelecida na sociedade atual. Nosso objetivo é que você desenvolva com felicidade e tranquilidade e repasse esse espírito ao projeto em que está trabalhando.

## Como se candidatar

Por favor envie um email para tlodcaetano@gmail.com - enviar no assunto: Vaga Front-End - GitHub

## Labels
- Remoto
- Freelance com possibilidade de efetivação
- Sem Experiência Prévia

**Comment by guibfo** [comment]
Você não merece Palmas, merece o Tocantins inteiro

Piada velha a parte, sensacional sua iniciativa, por mais pessoas assim na área e no mundo, já indiquei para uma pessoa dar olhada

**Comment by yanzmtbr** [comment]
> Você não merece Palmas, merece o Tocantins inteiro
> 
> Piada velha a parte, sensacional sua iniciativa, por mais pessoas assim na área e no mundo, já indiquei para uma pessoa dar olhada

Hahaha! Excelente, @guibfo. Sejamos a mudança que queremos ver no mundo. ;)

**Comment by dmchiodini** [comment]
Olá, em qual lugar de São Paulo vocês estão localizados? 

Desde já parabenizo pela atitude. Que isso sirva de exemplo para outras empresas.

Um grande abraço!

**Comment by cdcaetano** [comment]
> Olá, em qual lugar de São Paulo vocês estão localizados?
> 
> Desde já parabenizo pela atitude. Que isso sirva de exemplo para outras empresas.
> 
> Um grande abraço!

Opa, @dmchiodini. Nós estamos na região do Brooklin Novo. Mas o trabalho, por enquanto, é remoto. Sinta-se livre para entrar em contato via e-mail!

**Comment by OfficialMarinho** [comment]
Massa! Uma oportunidade e tanto.

**Comment by pissulin** [comment]
Você está de parabéns amigo desejo que vc receba tudo em dobro o bem que está fazendo para nós todos . Eu já mandei o email e espero poder conversar pessoalmente nem que seja somente para conhecer-lo .

**Comment by anaposcidonio** [comment]
Obrigada por essa oportunidade! Enviei meu email :)

**Comment by margotpaon** [comment]
Bom dia Carlos, tudo bem? Como vai funcionar o processo seletivo?
Achei incrível a empatia que a empresa tem para quem tá começando ou
procurando uma nova oportunidade para começar!
#pormaisempresasassim

Em seg, 17 de jun de 2019 às 10:00, Carlos <notifications@github.com>
escreveu:

**Comment by luluanacarla** [comment]
Que coisa linda! Por mais empresas assim :)

**Comment by FerBiani** [comment]
Parabéns pela iniciativa! Muito legal! Já enviei um email.

**Comment by cdcaetano** [comment]
> Bom dia Carlos, tudo bem? Como vai funcionar o processo seletivo? Quando recebemos feedback? Achei incrível a empatia que a empresa tem para quem tá começando ou procurando uma nova oportunidade para começar! Mandei um Curriculum vamos conversar?

Opa, @margotpaon. Entraremos em contato com você em breve!

**Comment by cdcaetano** [comment]
Obrigado a todos, recebemos muitos e-mails, uma quantia suficiente para iniciar nosso processo de seleção. Por esse motivo, a vaga está sendo fechada. Mas é por enquanto! Em breve traremos novas oportunidades.

Aos que já entraram em contato: retornaremos com mais informações ao seu e-mail entre os próximos dias.

Com esperanças,
Carlos Caetano
