### ISSUE TITLE
[Rio de Janeiro] Frontend Developer na Storm Security

### ISSUE THREAD

**Issue by luanstorm** [frontendbr/vagas#2105]
### Descrição da vaga
Você acha que pode ajudar uma empresa de tecnologia a se tornar referência em seu mercado com suas habilidades técnicas?

Então, continue lendo esse texto, precisamos de você. A Storm Security é uma empresa que existe há mais de 11 anos no mercado de tecnologia. Nossa missão é criar produtos que sejam bem desenhados, simples de usar, amigável aos usuários e principalmente inovador.

Com sede no Rio de janeiro, Barra da Tijuca, atuamos com em desenvolvimento de aplicativos e software para todos os devices, além de possuir grandes parcerias de desenvolvimento com clientes de grande porte no mercado web brasileiro.

### Local

- Rio de Janeiro - Barra da Tijuca

### Benefícios

- Plano de saúde
- Vale Transporte
- VR de R$ 27/dia
- VA

### Obrigatórios:

- Experiencia com Reactjs + Redux
- Experiencia com API Restfull
- Noções com uma dessas linguagens Python, C# Net ou Java
- Consumo de API's;
- Desenvolvimento responsivo e cross-browser;
- Versionador de código Git;
- Gulp / Webpack / NPM;
- Domínio de HTML5 e CSS3 semânticos;
- Pré processadores CSS (SASS);
- Conhecimentos Sólidos em Javascript;
- Lógica de Programação.

### Diferenciais:

- Desenvolvimento de apps híbridos (React Native ou Flutter)

### Contratação
- CLT a combinar

### Como se candidatar
Por favor envie um email para luan.garcia@stormsec.com.br com seu CV anexado - enviar no assunto: Vaga Frontend Developer

### Tempo médio de feedbacks
Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@stormsec.com.br

### Labels

- Alocado
- CLT
- Pleno

**Comment by evertonnppp** [comment]
ola amigo me chama no whats app whtasapp 21992433897
