### ISSUE TITLE
[Joinville/SC] FRONT-END Developer na VOLTS DIGITAL

### ISSUE THREAD

**Issue by eversonjp** [frontendbr/vagas#2106]
## DESCRIÇÃO DO JOB

O candidato fará parte de uma equipe multidisciplinar, onde todos participam de projetos dos  clientes da casa, ajudando e resolvendo problemas, otimizando e melhorando os processos de desenvolvimento.

## LOCAL / FORMATO

Preferencialmente em escritório, Joinville/SC ou fulltime remoto.

## BENEFÍCIOS

- Ambiente descontraído e bacanudo
- Oportunidade de trabalho com profissionais capacitados e experientes
- Auxílio refeição pago em dinheiro
- VT (ônibus)
- Subsídio para cursos
- Aquisição de livros sob demanda
- Salário compatível com a experiência
- Oportunidade para inovar e trazer novidades no fluxo de trabalho da equipe
- Fluxo organizado, ágil e cadenciado de trabalho
- Equipe unida em resolver desafios
- Mesa de sinuca
- Plataforma Mac
- Café infinito
- Confraternizações de aniversário sem custo ao aniversariante

## REQUISITOS

**Obrigatórios:**

- Domínio avançado das linguagens HTML, CSS, JavaScript e da biblioteca jQuery;
- Domínio avançado de algum pré-processador CSS (preferência por SASS);
- Domínio intermediário de algum framework JavaScript (preferência por Vue.js e/ou React);
- Domínio básico das linguagens PHP e SQL;
- Um ótimo conhecimento em WordPress;
- Manjar bem de Photoshop, Sketch ou XD, para transformá-lo em um lindo código;
- Dominar o GIT para versionamento de código e trabalho em equipe;
- Conhecer e praticar conceitos como KISS, DRY, Design Pattern e TDD;

**Desejáveis:**
- Muito atento aos detalhes do projeto
- Olhar apurado para alinhamentos e espaçamentos
- Noções com testes automatizados para web
- Experiência com APIs e integrações
- Noções básicas de design e arquitetura de informação
- Possuir um entendimento intermediário de técnicas de SEO
- Perfil analítico e detalhista
- Ter bom humor e perfil extrovertido
- Ser heavy-user de novas tecnologias
- Ser organizado, responsável e capaz de trabalhar em equipe
- Empatia com os projetos, ter pró-atividade e muita vontade de crescer profissionalmente
- Vontade inextinguível de aprender
- Ter a capacidade de aprimorar o último trabalho realizado

## CONTRATAÇÃO

PJ, via contrato.

## SOBRE A VOLTS DIGITAL

Somos uma agência orientada a resultados, que busca energizar negócios e fortalecer a presença de marca dos seus clientes, usando como base o entendimento e a análise de dados para tomada de decisões.

## CULTURA DE EMPRESA

Veja mais aqui: **http://voltsdigital.com.br/trabalhe-conosco**

## COMO SE CANDIDATAR

Você pode mandar um e-mail para **vagas@voltsdigital.com.br** com seu GIT ou portfolio para que possamos analisar seus trabalhos ou então diretamente através do nossos site: **https://voltsdigital.com.br/vagas/front-end-developer/**

## Labels

- Alocado
- PJ
- Pleno
- Remoto

**Comment by baltazarparra** [comment]
É desejável que o candidato tenha um transtorno? ou eu entendi errado?

> TOC por detalhes

**Comment by eversonjp** [comment]
> É desejável que o candidato tenha um transtorno? ou eu entendi errado?
> 
> > TOC por detalhes

É uma força de expressão, @baltazarparra. Mas ok, agradeço pelo seu comentário produtivo.

**Comment by filipecsweb** [comment]
> É desejável que o candidato tenha um transtorno? ou eu entendi errado?
> 
> > TOC por detalhes

@baltazarparra fyi, você entendeu errado mesmo. Não seja tão literal.

**Comment by filipecsweb** [comment]
@MrS4w poderia remover o label Sênior, por favor? =]

**Comment by baltazarparra** [comment]
> Muito atento aos detalhes do projeto
👏 👏
