### ISSUE TITLE
[Porto Alegre ou REMOTO] Full-stack Developer na SUPERPLAYER

### ISSUE THREAD

**Issue by MartinaCarvalho** [frontendbr/vagas#2107]
## Descrição da vaga

Buscamos um (a) profissional que seja apaixonado(a) por aprender, codar e que goste de pensar no produto além das linhas de código.

Assumindo esta posição, você será responsável por pensar, contribuir no planejamento e desenvolver novas funcionalidades nos diversos serviços, componentes e aplicações que compõem o backend e frontend dos produtos da Superplayer. Para tal, você trabalhará junto ao time de engenheiros na arquitetura e definição de soluções de alta escala e alta disponibilidade. Além disso, queremos que você utilize as melhores práticas e tecnologias para escrever um código que se orgulhará de ler amanhã. 🙂

## Principais responsabilidade

- Pensar, contribuir no planejamento e desenvolver novas funcionalidades para as aplicações e serviços que compõem os produtos desenvolvidos pela Superplayer & Co.
- Utilizar as melhores práticas e tecnologias para escrever código em JavaScript (Node.js) ou C# (.NET).
- Trabalhar junto com nosso time de engenheiros na arquitetura e definição de soluções de alta escala e alta disponibilidade.
- Resolver problemas e defeitos em nossos produtos e cuidar para que eles nunca cheguem em ambiente de produção.
- Definir, junto com o time do Superplayer, os caminhos de nossos produtos e nosso processo de desenvolvimento.

## Local

Remoto ou Escritório, Porto Alegre - RS

## Benefícios

- Plano de saúde
- VR/VA de R$ 22/dia
- Vale-transporte

## Requisitos

**Obrigatórios:**

- Paixão em escrever código, principalmente para a plataforma Node.js.
- Formação ou cursando alguma faculdade de informática: engenharia de software, ciências da computação, sistemas de informação, processamento de dados, análise de sistemas ou qualquer outra que ensine que 1 + 1 é 0 e vai 1.
- Vivência com desenvolvimento de aplicações web.
- Domínio de conceitos de OOP e conhecimento em conceitos de Functional Programming.
- ♡ Git.
- Capacidade de planejar e desenvolver seu trabalho focando os objetivos estabelecidos em conjunto.
- Vivência com desenvolvimento em ambientes e times ágeis.
- Disponibilidade para trabalho em tempo integral.

**Desejáveis:**

- Vivência com mais de uma linguagem de programação (de preferência em diferentes plataformas).
- Gostar de resolver as coisas direto no Terminal.
- Conhecer ou ter vivência profissional com serviços de Cloud Computing como AWS, Google Cloud Platform ou Windows Azure.
- Experiência em escrever testes unitários, de integração e funcionais.
- Alguma vivência ou já ter "brincado" com Docker e/ou Kubernetes.
- Saber o que é Lean Startup e porque isso é importante mesmo sendo um desenvolvedor.
- Paixão por aprender e empreender.

**Diferenciais:**

- Tocar algum instrumento ou cantar como um rouxinol. 🐦

## Contratação

CLT a combinar

## Nossa empresa

Ajudamos marcas a inovar através de música e tecnologia! 🤘

### O Superplayer
Com larga experiência na operação de serviços de streaming de música, no desenvolvimento de produtos digitais e relacionamento com as maiores gravadoras e editoras do mercado musical, nós ajudamos marcas a criar experiências inovadoras através de música e tecnologia.
Atuamos em três frentes: plataformas de streaming de música, serviços de sonorização para estabelecimentos comerciais e o desenvolvimento de projetos customizados de música digital. Trabalhamos junto as maiores empresas de telecomunicações, instituições financeiras, companhias aéreas e redes de varejo do Brasil, tendo mais de 5 milhões de downloads em nossos aplicativos e impactando mais de 2 milhões de pessoas por mês.
Fomos acelerados globalmente pelo Google e, atualmente, somos parte do Grupo Movile, a maior empresa de serviços móveis da América Latina, dona de aplicativos como iFood, Sympla, PlayKids, entre outros.
Nossa missão é inspirar mais de 100 milhões de pessoas com a trilha sonora perfeita para cada momento das suas vidas!

### Nossa cultura
A melhor forma de descrever o Superplayer é pelos seus valores: RISE (Resultados, Inovação, Simplicidade e Empreendedorismo). Somos empreendedores e não temos problemas em meter a mão na massa. Temos garra e determinação para fazer as coisas acontecerem. Somos orientados por fatos e dados, sem esquecer da importância do bom senso e da intuição.
Sabemos que as pessoas trabalham melhor de maneiras diferentes, por isso respeitamos a individualidade de cada um e damos flexibilidade para as pessoas trabalharem da forma como produzem melhor. Para que isto funcione, entendemos que é necessário confiança nas pessoas, porém exigimos responsabilidade de todos.
Acreditamos que a inovação e a criatividade florescem com a diversidade de estilos, conhecimentos e pensamentos. Incentivamos o trabalho em equipe, a cooperação e a participação de todos.
Acreditamos em ter uma empresa enxuta, com alta produtividade individual. Por isso, tentamos prover o ambiente e recursos que estimulem cada um a atingir o seu melhor.

Hoje, somos 16 Superplayers, apaixonados por música e tecnologia, baseadas em nossos escritórios em Porto Alegre e São Paulo ou remotamente no Rio de Janeiro, Goiânia e Londres.

## Como se candidatar

Se você se interessou, manda seu currículo, LinkedIn e/ou GitHub para jointheband@superplayer.co com o assunto Full-stack Developer.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: jointheband@superplayer.co

## Labels

- Alocado
- CLT
- Júnior
- Pleno
- Remoto

**Comment by SamuelSousa1984** [comment]
Na boa, se vocês estivessem aqui no Rio de Janeiro, eu ia trabalhar de graça pra vocês rs. Adorei a oferta!

**Comment by MartinaCarvalho** [comment]
Oi Samuel, 

Não precisa trabalhar de graça, não! 

Você viu que a vaga pode ser remota? Envia seu currículo para gente :)

Abraço,
Martina

**Comment by SamuelSousa1984** [comment]
Okey, Martina. Enviei "D

**Comment by guilhermeoa07** [comment]
Ainda está em aberto?

**Comment by MartinaCarvalho** [comment]
Yes :)

**Comment by andersonms1** [comment]
Até que dia posso enviar?

**Comment by wizarion** [comment]
Enviado! =D

**Comment by LucasHiago** [comment]
Me candidatei pelo remoto

**Comment by pedroffd** [comment]
Submetido!
