### ISSUE TITLE
[Rio de Janeiro] Frontend Developer na Liber

### ISSUE THREAD

**Issue by libereducacao** [frontendbr/vagas#2110]
## Descrição da vaga

Buscamos profissionais (perfil Júnior) proativos e engajados, focados em desenvolvimento frontend mobile e web (React Native e React com TypeScript) para compor nossa equipe em uma etapa de aceleração e ganho de escala da empresa.

## Local

Botafogo, Rio de Janeiro - RJ

## Diferenciais

- Ambiente altamente inovador
- Horário flexível
- Contato próximo e constante com grandes players do mercado educacional

## Requisitos

**Obrigatórios:**
- Javascript (ES6+)
- React Native
- Git
- Testes automatizados (Jest)

**Desejáveis:**
- Conhecimentos em React
- Typescript
- Metodologias Ágeis (Scrum)

## Contratação

PJ a combinar.

## Nossa empresa

Somos uma EdTech que nasceu em 2018 a partir de um projeto universitário. Selecionamos e treinamos talentos universitários de faculdades de ponta para darem aulas particulares presenciais no dia, horário e local que nossos clientes precisarem; levando uma experiência de aprendizado horizontal, focada em resultados e com acompanhamento personalizado voltado para as necessidades de cada família ou aluno.

## Como se candidatar

Por favor envie um email com o Assunto **Vaga Frontend Developer** para developers@liberedu.com com seu CV anexado.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.
E-mail para contato em caso de não haver resposta: developers@liberedu.com

## Labels

- Alocado
- Estágio
- Júnior
- PJ
- Remoto

**Comment by pedroffd** [comment]
Submetido
