### ISSUE TITLE
[SP - Pinheiros] Front-End Developer na Berghem

### ISSUE THREAD

**Issue by RaphaSchneider** [frontendbr/vagas#2111]
## Descrição da vaga

Desenvolvedor Front-End Angular 1.6/ Angular 7

## Local

São Paulo - Pinheiros (Próximo às estaçōes Pinheiros e Faria Lima da linha 4 amarela do metrô)

## Benefícios

- Plano de saúde Sulamerica
- VR 
- VT

#### Diferenciais

- Flexibilidade no horário de trabalho
- Participaçao na tomada de decisōes relacionados aos projetos
- Proximidade entre os líderes técnicos, clientes e idealizadores com a equipe 
- Ótima localização

## Requisitos

**Obrigatórios:**
- Conhecimento de AngularJS 1.6 E OU 7
- Usar GitFlow e conhecimentos básicos com git (labs/hub)
- Kanban e Scrum
- Saber trabalhar com frameworks de mercado
- Saber uso básico de npm
- Conhecimentos básicos sobre arquitetura de APIs (consumir)

**Desejáveis:**
- Conhecimentos básicos ou teóricos com automação de testes
- Conhecimentos básicos de UX

## Contratação

CLT ou PJ a combinar + Beneficios

## Nossa empresa

A Berghem é uma empresa nova que surgiu à partir de uma equipe com forte atuação na prática de Ethical Hacking Test (EHT) e em seus 3 anos de existência vem se tornando cada vez mais forte e influente nas áreas de EHT e desenvolvimento com foco no mercado financeiro.

## Como se candidatar

Interessados enviar currículo para devteams@berghem.com.br com o assunto sendo "[Vaga(Jr/Pl)] - [AngularJS] - [Candidato]" contendo curriculo com a vaga desejada, pretenção salarial e regime de contrato.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@berghem.com.br

## Labels

- Alocado
- CLT
- PJ
- Júnior
- Pleno
- Frontend
- Front-End
- Angular
- UX

**Comment by glaucoder** [comment]
A empresa não da oportunidades para quem está começando? no caso estagiário.

**Comment by RaphaSchneider** [comment]
Boa tarde Glauber

Podemos avaliar, por que não ? Poderia mandar seu cv ?

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: glaucoder <notifications@github.com>
Enviado: quarta-feira, junho 19, 2019 3:33 PM
Para: frontendbr/vagas
Cc: Raphael Schneider; Author
Assunto: Re: [frontendbr/vagas] [SP - Pinheiros] Front-End Developer na Berghem (#2111)


A empresa não da oportunidades para quem está começando? no caso estagiário.
