### ISSUE TITLE
[REMOTO] Front End Developer na CHECKPLANT

### ISSUE THREAD

**Issue by megandavulpi** [frontendbr/vagas#2115]
### Sobre a empresa: Checkplant Sistemas

Desde 2003, a Checkplant desenvolve soluções de software e tecnologias para o setor agrícola​, sempre levando em conta como as pessoas terão suas vidas impactadas, de forma que tais mudanças sejam recebidas por todos como uma oportunidade de desenvolvimento pessoal e profissional, seja um colaborador nosso, de um fornecedor ou de nossos clientes.

### Descrição:

Startups de tecnologia estão transformando cadeias inteiras, como educação, saúde, finanças, jurídico, e a agricultura é hoje um dos principais setores que estão aproveitando a capacidade tecnológica para se reinventar.

Aqui na Checkplant, o profissional de tecnologia irá mergulhar no mundo de desafios e tecnologias que já são realidade dentro da porteira, como inteligência artificial, interoperabilidade entre sistemas, telemetria, meteorologia, internet das coisas, geoprocessamento e muitos outros, sempre aplicados a interfaces simples e muito aderentes à realidade dos produtores rurais.

Aqui o profissional tem a oportunidade de evoluir tecnicamente e ainda ver o seu trabalho tendo resultado diretamente lá na ponta.

### Precisamos que o profissional tenha experiência em:

- Desenvolvimento Front-End para Web;
- JavaScript; React; HTML e CSS.

### Ficaríamos muito contentes se o profissional tiver:

- Experiência em trabalhar com Mobile;
- Conhecimento de Angular;
- Proatividade.

### Benefícios que oferecemos:

- Plano de Saúde Unimed integral;
- VT;
- VR;
- Regime de contratação: o profissional poderá optar por CLT ou PJ.

IMPORTANTE: Essa vaga pode ser remota, mas nessa modalidade de trabalho precisamos de um profissional que tenha disponibilidade para trabalhar com dedicação exclusiva.

### Candidatar: http://bit.ly/checkplant_frontend

**Comment by laugustofrontend** [comment]
enviado

**Comment by YuriBrunetto** [comment]
Enviado! 😄

**Comment by EzequielBrilhante** [comment]
Enviado!

Em qua, 19 de jun de 2019 às 17:08, Megan da Vulpi <notifications@github.com>
escreveu:

**Comment by AdoniasLemos** [comment]
Submetido

**Comment by wizarion** [comment]
Submetido. =D

**Comment by pedroffd** [comment]
Enviado.
