### ISSUE TITLE
[Remoto / Viana - ES] Full-Stack Developer na Máximus Soluções

### ISSUE THREAD

**Issue by rzorzal** [frontendbr/vagas#2118]
## Descrição da vaga

O profissional atuará principalmente com Desenvolvimento Full-Stack e o que achamos ser o mais interessante é que somos PART REMOTE, são 2 dias no escritório e 3 remotos. Utilizamos Node.js, Express, Sendgrid, Heroku, Postgres, PM2, Sequelize, MongoDB, Sentry, Git e etc. Mas buscamos pessoas que querem aprender. Nenhuma tecnologia é requisito, somente a vontade de aprender. Se você conhece alguma ferramenta que citamos na vaga, será um diferencial. Qualquer dúvida é só entrar em contato conosco!

## Local

Remoto e Escritório, Canaã, Viana - Espírito Santo

## Benefícios

- Vale Transporte

#### Diferenciais

- 2 dias no escritório e 3 dias remoto
- Equipe pequena e produto novo, possibilidade de escolher as tecnologias e debater sobre os processos.

## Requisitos

**Obrigatórios:**
- Vontade de Aprender e crescer com a empresa
- Conhecimentos em javascript, html, css
- Conhecimentos em bancos de dados SQL

**Desejáveis:**
- Conhecimento em ORM ou ODM

**Diferenciais:**
- Conhecimento em Firebase
- Conhecimento em MongoDB
- Conhecimento em PWA

## Contratação

PJ a combinar

## Nossa empresa

A Máximus Soluções é uma empresa nova, e é a primeira do seu ramo no mercado capixaba, sendo assim, por sermos pioneiros, estamos no meio de um processo de crescimento. Estamos iniciando o processo de montar uma equipe de Desenvolvimento. Buscamos pessoas para integrar nossa equipe de Desenvolvimento e que buscam, acima de tudo, aprender.

Somos uma empresa Remote First e visamos a produtivade e responsabilidade dos nossos colaboradores, com isso conseguimos evoluir nosso modelo de trabalho que hoje é de dificil implementação em algumas empresas, mas não para nós, sabemos onde queremos chegar e nossos desenvolvedores são nosso principal ativo :)

## Como se candidatar

Siga as instruções do processo de seleção no link https://github.com/rzorzal/selecao-maximus

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: ricardozorzaldavila@gmail.com

## Labels

- Alocado
- Remoto
- Júnior
- PJ
- Pleno

**Comment by SamuelSousa1984** [comment]
Conheço boa parte das tecnologias citadas, mas moro no Rio de Janeiro, fica inviável dois dias presentes =\ (eu acho)...

**Comment by mrangel-jr** [comment]
@rzorzal , Há a possibilidade de ser 100% remoto ?

**Comment by rzorzal** [comment]
Obrigado pelos comentários, mas hoje não conseguimos fazer 100% remoto. Mas estamos migrando para isso. Assim que tivermos vagas Full remoto vamos divulgar.

**Comment by rzorzal** [comment]
Estamos fechando a issue pois tivemos algumas pessoas interessadas e estamos continuando o processo de seleção. Obrigado a todos.
