### ISSUE TITLE
[São Paulo] Desenvolvedor Fullstack

### ISSUE THREAD

**Issue by rittersport3** [frontendbr/vagas#212]
## Descrição das vagas

Estamos buscando um desenvolvedor para início imediato. Esperamos:
Conhecimentos sobre desenvolvimento Python - Flask, NoSQL Mongo, py.test, testes unitários, git...
Vontade de programar como gente grande e conhecer o funcionamento de uma startup desde o começo
Consciência que deve-se fazer de tudo (sem “prima-donnismos” ou braço curto)

Se você não tiver conhecimentos dos primeiros pontos, mesmo assim pode entrar em contato conosco: somos super flexíveis e, quem sabe, podemos acertar algo que funcione para ambas as partes.  

## Local

São Paulo, no centro da cidade, do lado (literalmente) do metrô

## Benefícios

O que oferecemos além de um salário?
- Ambiente AAA: Estamos em um escritório próprio super-cool, no centro de São Paulo, super perto de onde você mora
- Horário flexível: você escolhe quais horas do dia ou da noite quer passar aqui  - desde que o prédio esteja aberto ;-) 
- Aprendizado técnico: temos aplicações de visão computacional, docker, deep-learning, Angular, Android… o quiser aprender tem alguém aqui que já mexe
- Plano de carreira: nossa startup está crescendo e precisamos de mais gente no time para o longo prazo!)
- Clima descontraido, democrático e, acima de tudo, divertido. Sua experiência será super relevante: não são “monkey-jobs”
- Almoço de sexta por conta da firma! Levamos o time todo para um restaurante (pizza, hamburguer,  ceviche, baião-de-dois…)
- Café/chá “dos bons”! - pode ser até café Suplicy
- Back to nerd times: happy hours na sexta com CS - porque a gente é dessa época, mas se tiver alguma sugestão, também está valendo. O que conta é a descontração, acompanhada de cerveja importada
- Seu próprio cartão de visita com o título que você quiser ter. Pode ser Doutô, Darth Vader, Chapolim Colorado…
## Requisitos

**Obrigatórios:**
- Ao menos 2 anos de experiência com Python (Django, Flask, Pyramid)
- Conhecimento de testes unitários

**Desejáveis:**
- conhecimentos de MongoDB
- conhecimentos de Docker
- Py.Test
- Experiência em escrever e utilizar APIs REST
- Angular.js

**Diferenciais:**
- projetos opensource

## Contratação
CLT

## Nossa empresa

O PONTOTEL é uma empresa de automação de registros trabalhistas para funcionários.Nós somos um “SaaS de RH” adaptado para as necessidades dos consumidores residenciais.
A equipe de 12 pessoas é formada pelos dois sócios-engenheiros (POLI-COMP e FEI elétrica), 3 desenvolvedores, 1 designer, um marketing e 4 pessoas de suporte/comercial. Você trabalhará diretamente com os sócios e nós vamos fazer o possível para que esse seja o trabalho mais bacana (isso mesmo) que você venha a ter. Nós todos somos desenvolvedores e lutamos para construir a empresa que sempre sonhamos em trabalhar.

## Como se candidatar

Por favor envie um email para dev@pontotel.com.br com seu CV anexado - enviar no assunto: Vaga Python

**Comment by viniciusdocanto** [comment]
@rittersport3 Aqui só se posta vaga de **Frontend**

**Comment by rittersport3** [comment]
@vinicius, não tem problema então.

**Comment by vinicius** [comment]
Mandaram para o Vinicius errado.

Att.,
Vinicius Pinheiro

2017-01-10 16:52 GMT-02:00 Felipe Fialho <notifications@github.com>:

**Comment by rogeriomarques** [comment]
Alguém sabe de algum repo como este aqui mas para backend/full stack? Gostaria muito de saber...
