### ISSUE TITLE
[São Paulo] FullStack Developer Senior na Mazzatech

### ISSUE THREAD

**Issue by taianeuchoa** [frontendbr/vagas#2120]
## Descrição da vaga
Atuará alocado na em uma FINTECH que atua com investimentos, braço de um grande grupo bancário, integrando a equipe de desenvolvimento.

## Local

Atuação no escritório da empresa, na Berrini (SP).

## Benefícios

- 13º salario
- 15 dias de férias remuneradas

#### Diferenciais

- ambiente startup
- no dress code

## Requisitos

**Obrigatórios:**
-  Forte Atuação com Desenvolvimento nos Frameworks como Angular.js, Node.js, Vue.js ou React.js.
- Conhecimento da Cultura DevOps (planejamento, codificação, construção, teste, implantação, operação e manutenção);
- Foco nas tecnologias: Front-End: Javascript, CSS e HTML.

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para taiane@mazza.tech com seu CV anexado - enviar no assunto: Desenvolvedor FullStack - Berrini

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: taiane@mazza.tech

## Labels

- Alocado
- PJ
- Pleno
- Sênior

**Comment by MrS4w** [comment]
Nome da empresa?

**Comment by felipefialho** [comment]
@taianeuchoa nenhuma vaga pode ser mantida sem nome da empresa

**Comment by taianeuchoa** [comment]
Ola! É para atuar na Mazzatech, alocado em uma empresa de Investimentos. Obrigada!

**Comment by felipefialho** [comment]
A contratação será feita pela própria Mazzatech?

**Comment by taianeuchoa** [comment]
isso mesmo Felipe!
