### ISSUE TITLE
[São Paulo] Front-end Developer - Closeup International

### ISSUE THREAD

**Issue by taianeuchoa** [frontendbr/vagas#2123]
## Descrição da vaga

Oportunidade para atuar no time de FrontEnd da CloseUp International.

## Local

Atuação no escritório da empresa, que fica na região da Chácara Santo Antonio (prox. Shopping Morumbi).

## Benefícios

Contratação PJ.

## Requisitos

**Obrigatórios:**
Atuação na área de desenvolvimento de projetos de software;
Conhecimentos em construção de UI / UX;
Desenvolvimento usando arquiteturas baseadas em micro serviços;
Conhecimentos específicos:
CSS, Javascript, Bootstrap;
Angular;
React/Redux;
Banco de dados relacionais (Oracle, SQL Server, Postgree, MySQL);
Banco de dados NoSQL (ArangoDB, MongoDB);
Transact SQL ou PL SQL;
Java (Spring / Play);
Node.js;
RestAPI;
Docker;
Kubernetes;

**Desejáveis:**
Habilidades com algum software de produção de imagens para construção de web sites será um diferencial;
Conhecimentos em desenvolvimento de back-end é desejável;
Conhecimentos de DevOps será um diferencial;

## Contratação

PJ alocado na Closeup.

## Nossa empresa

A Mazzatech é uma consultoria de TI que atua há mais de  anos no mercado de TI.

## Como se candidatar

Por favor envie um email para taiane@mazza.tech com seu CV anexado - enviar no assunto: Vaga FrontEnd Sr.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: taiane@mazza.tech

## Labels

- Alocado
- PJ
- Pleno
- Sênior

**Comment by felipefialho** [comment]
@taianeuchoa Por favor, mantém o padrão de titulo usando "Desenvolvedor(a) ou Developer" :)
