### ISSUE TITLE
[Florianópolis] Front-end Developer na SBTUR Viagens

### ISSUE THREAD

**Issue by fabdjr** [frontendbr/vagas#2127]
## Descrição da vaga

Estamos buscando Dev Front-end (React) para integrar o time de produto da SBTUR. Acreditamos que viajar faz bem, que todos os brasileiros merecem viajar e que a tecnologia pode ser a maior propulsora deste propósito. Trabalhamos em um ambiente de construção, leve e descontraído.

Procuramos uma pessoa com perfil colaborativo, proativo, inovador, que se preocupa com a qualidade das entregas e que busca fazer o seu melhor todos os dias.

## Local

Escritório, Florianópolis - Centro

## Benefícios

- Plano de saúde
- Vale transporte
- Vale alimentação

#### Diferenciais

- Massagem
- Laboral
- No dress code
- Acesso aos cursos da plataforma Alura
- Cafezinho da Morena <3 (e as vezes rola uma french press)
- Relacionamento próximo aos fundadores e diretores da empresa.

## Requisitos

**Obrigatórios:**
- **Sólido conhecimento em HTML5 e CSS3;**
- **Proficiência em JavaScript**;
- **Compreensão de React.js e seus princípios fundamentais**;
- Compreensão do uso da biblioteca Next.js.
- Compreensão dos conceitos de server side render.
- Compreensão da criação de testes.
- Compreensão da criação/uso do Storybook.
- Conhecimento sobre código limpo (clean code) e padrões de design;
- Familiaridade com APIs RESTful;
- Familiaridade com testes de navegador e depuração;
- Ser autodidata;
- Estar atualizado com as últimas notícias e tecnologias sobre desenvolvimento; 
- Boa capacidade de comunicação;
- Experiência com o GitHub;
- Inglês técnico.

**Diferenciais:**
- Conhecimento em UI e UX;
- Familiaridade com Design Systems;
- Métodos de desenvolvimento ágeis;

## Contratação

CLT, horários flexíveis, remoto quando necessário

## Nossa empresa

Nós amamos viajar e trabalhamos por um mundo em que todo Brasileiro possa viajar também. Queremos que as pessoas conheçam novos lugares, interajam com diferentes culturas e vivam grandes experiências. 

Trabalhamos com muita descontração, em um ambiente que vive a diversidade e promove a colaboração e a amizade. Não acreditamos que a roupa impacte no trabalho de cada um, gostamos da transparência, dos feedbacks, das falas olho-no-olho.

Acreditamos na constante troca de conhecimento. Gostamos de escutar suas opiniões e, sempre que possível, colocá-las em prática e, por isso, fomos considerados umas das 10 melhores empresas para se trabalhar de Santa Catarina por 2 anos consecutivos.

## Como se candidatar

Por favor envie um email para rh@sbtur.com com seu LinkedIn ou CV anexado - enviar no assunto: Dev Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.
E-mail para contato em caso de não haver resposta: adriano.silveira@sbtur.com

## Labels

- CLT
- PJ
- Pleno
- Remoto

**Comment by mrangel-jr** [comment]
A vaga é parcialmente remoto ou pode ser 100% remoto ?

**Comment by fabdjr** [comment]
@mrangel-jr Pode ser 100% remoto

**Comment by felipenoka** [comment]
Estágio pode ser 100% remoto tbm?

**Comment by fabdjr** [comment]
@felipenoka No momento estamos buscando apenas profissionais pleno. Eu vi que deixei a tag de estágio sem querer, my bad. @MrS4w pode atualizar as tags?

**Comment by mrangel-jr** [comment]
@fabdjr , Enviado !

**Comment by jpmsegurado** [comment]
Enviado

**Comment by andreMCD** [comment]
Enviado.

**Comment by LucasHiago** [comment]
Enviado
