### ISSUE TITLE
[São Paulo] Desenvolvedor Front-End

### ISSUE THREAD

**Issue by jbaladao** [frontendbr/vagas#213]
## Descrição da vaga

Projeto SuperAgendador.com em AngularJS 1 e NodeJS.

## Local

Próximo ao metro Jabaquara, São Paulo - SP

## Benefícios

- 1 hora de almoço
- café da manhã, bebidas no frigobar
- PS3 liberado com vários jogos para descontrair

## Requisitos

**Obrigatórios:**
- 1~2 anos de experiência com AngularJS ou React
- ~1 ano de experiência com NodeJS

**Desejáveis:**
- conhecimentos em manipulação de API Restful
- conhecimentos em Cordova/Phonegap
- conhecimentos em HTML/CSS
- conhecimentos em PHP

**Diferenciais:**
- autodidata apaixonado por tecnologia

## Contratação

PJ a combinar

## Nossa empresa
O SuperAgendador.com é um dos maiores sistemas de gestão para Prestadores de Serviços do Brasil, nossos clientes movimentaram juntos aproximadamente 25 milhões de reais em dezembro de 2016. A empresa já foi acelerada em 2016 no evento InvestorsDay da CampusParty (anjos via Broota) e agora em 2017 recebeu um novo investimento do grupo Bossa Nova (pré-seed).
Estamos naquela fase incrível onde uma pequena startup pode evoluir rapidamente para um empresa com mais de 200 funcionários. Esse é o sonho, se quiser participar dele, venha trabalhar conosco. Vivenciar o nascimento e transformação de uma Startup é incrível e as oportunidades de crescimento e aprendizado são muitas!

## Como se candidatar

Por favor envie um email para jbaladao@superagendador.com com seu CV anexado - enviar no assunto: Vaga Front-End

## Outras vagas

Também estamos procurando por um Webdesigner com perfil PIXEL PERFECT e com alguma experiência em UX. Além de um desenvolvedor PHP Senior! Toda indicação será super bem vinda...

Muito obrigado!

**Comment by eduardojmatos** [comment]
@jbaladao pode descrever o nível da vaga, se júnior, pleno ou sênior?

**Comment by jbaladao** [comment]
Não consegui adicional labels... a vaga é para os perfis Pleno ou Senior.

**Comment by jbaladao** [comment]
Vaga preenchida! Obrigado a todos que encaminharam seus currículos, vamos mantê-los em nossa base para futuras vagas.

**Comment by jbaladao** [comment]
[CLOSE]
