### ISSUE TITLE
[Rio de Janeiro / Remote] Front-End Developer @ Lemoney

### ISSUE THREAD

**Issue by lemoneyhiring** [frontendbr/vagas#2136]
## Missao da Vaga

Colocar em prática todas as estratégias e layout pensados para [nosso site](https://www.lemoney.com), levando sempre em consideração a melhor funcionalidade para nosso cliente e os objetivos da empresa. Fazer as implementações e testes necessários referentes ao Front End.

## Local

Nosso Escritório fica em um dos pontos mais atrativos do Rio de Janiero, próximo à Praia de Ipanema, ao lado do metrô. Temos também um co working space em Downtown Miami.
Estamos buscando profissionais para ficarem alocados em nosso escritório do Rio ou em modelo Full Remoto.

## Diferenciais

- Temos um time pequeno, mas de ouro! Todos engajados e extremamente produtivos;
- Política agressiva de bonificação por metas batidas;
- Gostamos que todos estejam envolvidos nas principais decisões da empresa;
- Abominamos burocracia! Queremos resolver problemas de maneira ágil;
- Você trabalhará diretamente com o mercado americano, onde a excelência é default;
- Nosso ambiente é informal e dinâmico, com amplo espaço para criatividade e inovação.

## Pre Requisitos

- Inglês Avançado;
- Experiência anterior com Rails, Sass ou algum Framework MVC.
- Experiência com JS Framework (Client Side Developer);
- Superior Completo em áreas correlativas (Engenharia da Computacao, Ciência da computação, etc... );

Consideramos profissionais de todos os níveis (Jr, Pleno e Sênior).

## Contratação

PJ

## Sobre Nós

Somos uma startup americana de Cash Back. Trabalhamos diretamente com o Mercado de Afiliados, um dos mercados com maior crescimento no mundo digital. Apesar da nossa operação estar no Rio de Janeiro, nosso foco é no mercado ameriano. Você terá a oportunidade de aprender sobre a cultura e hábitos de consumo do país referência de mercado.

Aqui na Lemoney, damos muita importância à pensamentos fora da caixa. Buscamos pessoas apaixonadas pelo que fazem, que pensam grande e não se contentam apenas com o “bom”. Pessoas criativas, que gostam de resolver problemas na hora que eles aparecem, de maneira inovadora e eficiente.
**Excelência é o nosso lema!**

## Application

Se identificou com a Lemoney? Envie seu Linkedin ou currículo para odara.menezes@lemoney.com e boa sorte!! :)

## Labels

- PJ
- Pleno
- Remoto
- Alocado
- Javascript

**Comment by wizarion** [comment]
Enviado! =D

**Comment by flaugabriel** [comment]
Enviado!☘
