### ISSUE TITLE
[São Paulo/Remoto] Front-end Developer PL/SR na Numenu

### ISSUE THREAD

**Issue by fmlopes** [frontendbr/vagas#2138]
## Descrição da vaga

@Devs beleza?

Sou Felipe e sou CTO da Numenu, startup que ajuda motoristas de Uber a ganharem mais dinheiro através de venda de snacks (Trident, Halls, Club social, etc) para passageiros dentro dos carros. Já estamos em mais de 1.300 motoristas em São Paulo e já realizamos mais de 60k vendas. Ainda somos bem pequenos, mas estamos precisando aumentar o time, então preciso de gente part-time ou full-time pra ajudar nas sprints, freela mesmo por enquanto. O objetivo é contratar full-time todos no médio prazo e montar um time que vai dar orgulho para as nossas mães.

É remoto e procuro plenos e seniors, ok? Tem preferência quem tiver o horário comercial disponível. 

Estamos com o stack abaixo, mandem currículo/linkedIn/github para minis@numenu.store. Não esqueçam de mandar o valor/hora também. 

Developer JS

- Node.JS;
- Sequelize;
- MySQL;
- React e Redux;
- React Native;
- ES6;
- Webpack;
- Bootstrap;
- Docker;
- Docker Swarm;
- Git;
- TDD;

Não precisa saber tudo, vamos te treinar no que faltar e esperar que você também traga conhecimento pro time.

## Local

Remoto, mas ficamos em São Paulo - SP.

## Contratação

PJ/Freela

## Labels

- Freela
- PJ
- Pleno
- Remoto
- Sênior

**Comment by mrangel-jr** [comment]
@fmlopes ,  Enviado !

**Comment by mrangel-jr** [comment]
@fmlopes , ainda está aberta a vaga ?

**Comment by martinsbicudo** [comment]
A vaga ainda está aberta? Enviei o meu currículo no dia 01/06, mas ainda não recebi nenhum retorno.
