### ISSUE TITLE
[Barueri] Front-End Developer na Digistarts

### ISSUE THREAD

**Issue by Digistarts** [frontendbr/vagas#2139]
## Descrição da vaga

Analista Desenvolvedor Jr - Perfil Full Stack

## Local

Escritório, Alameda Rio Negro, 585 - Alphaville - Barueri

## Benefícios

-Negociável

#### Diferenciais

- Liberdade para participar de treinamentos durante o expediente
- Sempre aprendendo novas tecnologias
- Foco em inovação e desenvolvimento com qualidade
- Ambiente descontraído 
- Frigobar e sala de descompressão 
- Empresa tem equipe de PubG e Campeonato de Poker

## Requisitos

**Obrigatórios:**
- Experiência com ambiente cloud AWS ou Google

**Desejáveis:**
- Experiência com desenvolvimento mobile
- Conhecimento em desenvolvimento web (Javascript, Phyton ou React)
- Conhecimento de metodologia ágil
- Experiência em trabalhar com Git

## Contratação

PJ ou CLT a combinar

## Nossa empresa

SOMOS UMA CONSULTORIA DE TECNOLOGIA FOCADA EM ENTREGAR INOVAÇÃO PARA NOSSOS CLIENTES

A Digistarts tem sua origem como empresa atuando na operacionalização de novas startups digitais, e temos orgulho de carregar e fomentar essa cultura ate os dias de hoje.

Nossa visão é que a simplicidade de uma inovação tecnológica pode trazer resultados diferenciados e extraordinários para as empresas que buscam transformações digitais.

## Como se candidatar

Por favor envie um email para contato@digistarts.com com seu CV anexado - enviar no assunto: Analista Desenvolvedor Jr - Perfil Full Stack

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.
E-mail para contato em caso de não haver resposta: helcio@digistarts.com

## Labels

- Fixo CLT ou PJ
- Júnior
- Mobile
- Web
- Javascript
- AWS ou Google Cloud

**Comment by mmss1304** [comment]
Enviado!

**Comment by developer-sp** [comment]
Enviado!!!
