### ISSUE TITLE
[São Paulo] Front-end Developer Jr

### ISSUE THREAD

**Issue by camilatigre** [frontendbr/vagas#214]
## Descrição da vaga

O front vai trabalhar na parte de processos BPMN nas seguintes atividades:
- Desenvolver formulários customizados.
- Desenvolver componentes Javascript para atender as funcionalidades necessárias.
- Criar as funcionalidades de acordo com as requisições do cliente.

## Local

Escritório, Rua Castro Verde, 98 - Santo Amaro, São Paulo

## Benefícios

- Horário flexível

## Requisitos

- HTML e CSS
- Javascript. Bom conhecimento sobre os fundamentos e de novos padrões da linguagem.
- Versionamento de código com Git.

## Contratação

CLT Full

## Como se candidatar

Por favor envie um e-mail para recrutamento@arizona.global e cópia para camila.tigre@arizona.global com seu Linkedin e Github com o título Vaga Frontend Jr

**Comment by raulfdm** [comment]
@camilatigre é full time?

**Comment by camilatigre** [comment]
@raulfdm  sim

**Comment by felipem1511** [comment]
Enviado com certeza

**Comment by Carlosxell** [comment]
Enviado com a maior segurança e vontade de ser chamado 🤙

**Comment by amadre-nelson** [comment]
Poutz é para JR.

Eu ia me candidatar but rs... deixa meu contato ai...
http://nelsonseccofilho.hol.es/

bjs e boa sorte.

Se pintar uma de SR me liga.

**Comment by randhson** [comment]
Enviado, e aguardando contato.

**Comment by tigurio** [comment]
Não moro em São Paulo mas tenho interesse na vaga. Disponibilidade para mudança.
Espero que isso não seja problema para a participação na seleção à vaga.

**Comment by camilatigre** [comment]
@tigurio e outras pessoas de fora de SP. Eu também sou de fora de SP mas eu já morava aqui quando comecei o processo. 

Acho que a empresa vai dar prioridade pra quem já está aqui, até por que uma das etapas é presencial.

**Comment by LFeh** [comment]
Boa sorte @tigurio

**Comment by tigurio** [comment]
Bom, de qualquer forma agradeço o contato, embora acredito que tenham
formas de fazer o processo online também para aqueles que não estão em SP.
Fico no aguardo.

Atc,
*Thiago Santos*
www.tigurio.com.br
Resume: https://tigurio.github.io

71 9 9200-1869 / 9 9917-1869
_________________________

GTalk: tigurio@gmail.com
Twitter: twitter.com/tigurio
Skype: tigurio
Facebook: http://www.facebook.com/tigurio
FanPage:  http://www.facebook.com/fanpageTigurio
Linked In: http://br.linkedin.com/in/tigurio
<http://br.linkedin.com/in/tigurio/pt>
________________________________________

2017-01-17 13:47 GMT-03:00 Felipe Fialho <notifications@github.com>:

**Comment by tigurio** [comment]
Obrigado @Felipe Fialho

Atc,
*Thiago Santos*
www.tigurio.com.br
Resume: https://tigurio.github.io

71 9 9200-1869 / 9 9917-1869
_________________________

GTalk: tigurio@gmail.com
Twitter: twitter.com/tigurio
Skype: tigurio
Facebook: http://www.facebook.com/tigurio
FanPage:  http://www.facebook.com/fanpageTigurio
Linked In: http://br.linkedin.com/in/tigurio
<http://br.linkedin.com/in/tigurio/pt>
________________________________________

2017-01-17 13:47 GMT-03:00 Felipe Fialho <notifications@github.com>:

**Comment by gabrielferreiraa** [comment]
A vaga está em aberto ainda?

**Comment by jvcjunior** [comment]
Mandei hoje!! Também queria saber!!

**Comment by gasfu** [comment]
Enviado !

**Comment by camilatigre** [comment]
Acredito que apenas uma vaga foi preenchida. Acho que ainda temos 2 ((: @gabrielferreiraa  @jvcjunior

**Comment by jvcjunior** [comment]
Eu enviei @camilatigre. Não recebi foi resposta.. hahaha

**Comment by tigurio** [comment]
Olá Camila.

Enviei também, porém a empresa pode ter me eliminado por eu não estar
residindo em SP no momento ( o que não é vejo problema para candidatura).
Talvez se a empresa abrisse mais sua visão e fizesse como outras grandes
empresas que não contratam um profissional pela sua proximidade, mas sim
pela sua capacidade, as vagas seriam preenchidas!

Atc,
*Thiago Santos*
www.tigurio.com.br
Resume: https://tigurio.github.io

71 9 9200-1869 / 9 9917-1869
_________________________

GTalk: tigurio@gmail.com
Twitter: twitter.com/tigurio
Skype: tigurio
Facebook: http://www.facebook.com/tigurio
FanPage:  http://www.facebook.com/fanpageTigurio
Linked In: http://br.linkedin.com/in/tigurio
<http://br.linkedin.com/in/tigurio/pt>
________________________________________

2017-01-31 22:27 GMT-03:00 Camila Tigre <notifications@github.com>:

**Comment by fernandofleury** [comment]
Ainda tem vaga? Queria indicar pra um amigo meu que tá iniciando.

**Comment by camilatigre** [comment]
Sim. Mais uma

Em 14 de mar de 2017 3:17 PM, "Fleury" <notifications@github.com> escreveu:

**Comment by thallesmarchetti** [comment]
Estou no mesma situação do amigo acima morando fora de SP, mas tenho possibilidades de me mudar pra SP com facilidade pela família residir em SP. Tem como participar do processo?

**Comment by camilatigre** [comment]
Acredito que não. Eu até tirei da descrição por que os dois últimos
contratados não foram no formato home-office. Não sei se vai continuar o
benefício.

Em 14 de mar de 2017 19:38, "Thalles Marchetti" <notifications@github.com>
escreveu:

Estou no mesma situação do amigo acima morando fora de SP, mas tenho
possibilidades de me mudar pra SP com facilidade pela família residir em
SP. Tem como participar do processo?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/frontendbr/vagas/issues/214#issuecomment-286583685>,
or mute
the thread

**Comment by camilatigre** [comment]
Vagas preenchidas. As pessoas encontradas não vieram do repo. ):
