### ISSUE TITLE
[Campinas] Front-end Developer na I.Systems S.A.

### ISSUE THREAD

**Issue by HigorGomes93** [frontendbr/vagas#2143]
## Descrição da vaga

Procuramos um(a) profissional com experiência em desenvolvimento front-end para se juntar à nossa equipe. Para isso, precisamos que ele(a) seja capaz de traduzir protótipos em plataformas funcionais e atraentes, que tenha qualidade e prazos de entrega, criar aplicações inovadoras, responsivas e com foco na experiência do usuário, e que dê suporte a outros membros do time. Queremos profissionais engajados(as) às novidades da área, curiosos(as) e responsáveis, comunicativos(as), que trabalhe em equipe e unindo usabilidade com estética.

## Local

Escritório, Campinas - Taquaral

## Benefícios

- Plano de Saúde (UNIMED Campinas)
- Plano Odontológico (Uniodonto)
- Seguro de Vida (Porto Seguro)
- Vale Refeição ou Alimentação
- Vale Transporte
- Programa de Participação nos Lucros e Resultados
- Gympass
- Auxílio em aulas de Inglês
- 4 horas semanais para estudos (pós, cursos, entre outros)

#### Diferenciais

- Horário flexível
- Possibilidade de home office
- No dress code
- Ambiente horizontal, relacionamento próximo aos fundadores e diretores da empresa
- Pets no ambiente de trabalho
- Ginástica laboral
- Open frutas e café

## Requisitos

**Obrigatórios:**
- Domínio de HTML, CSS, JavaScript e JQuery;
- Conhecimentos em linguagens como TypeScript;
- Conhecimentos em Git;
- Experiência com frameworks como Angular v1.x e React;
- Experiência com testes unitários;
- Habilidades para lidar com tarefas de diferentes projetos e trabalho em equipe;
- Graduação na área (Ciência da Computação, Análise e Desenvolvimento de Sistemas, Engenharia da Computação, etc.) ou experiência similar.

## Contratação

CLT, horários flexíveis, home office quando necessário

## Nossa empresa

Somos a Startup líder na aplicação de inteligência artificial para processos industriais. Atuamos no desenvolvimento de softwares de automação, inseridos no contexto da indústria 4.0.

Sendo uma das 100 Startups mais promissoras do Brasil, segundo a STW (Startup to Watch) em 2018, estamos crescendo de maneira sólida e rápida.

Através do nosso propósito, “tornar o mundo mais eficiente”, inspiramos e empoderamos nossos colaboradores a serem agentes na construção de soluções inovadoras e inteligentes!

Temos um ambiente colaborativo e dinâmico, onde apoiamos a diversidades e vivenciamos diariamente nossos 5 valores:

Transparência, Trabalho em Equipe, Empoderamento, Pertencimento e Orientado a Resultados.

## Como se candidatar

Por favor envie um email para higor.gomes@i.systems.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.
E-mail para contato em caso de não haver resposta: naiara.tesser@i.systems.com.br

## Labels

- Pleno
- CLT
- Alocado
- Remoto
- [São Paulo]

**Comment by danielswater** [comment]
Home full não aceita?

**Comment by HigorGomes93** [comment]
Apenas parcial para o nível Pleno.

**Comment by danielswater** [comment]
> Apenas parcial para o nível Pleno.

Sou Senior, existe a possibilidade?

**Comment by HigorGomes93** [comment]
Conferir os requisitos aqui: https://github.com/frontendbr/vagas/issues/2142
Enviar e-mail com CV para o endereço descrito na vaga!
