### ISSUE TITLE
[São Paulo] Front-End Developer PL na Uello

### ISSUE THREAD

**Issue by jmarcelocjr** [frontendbr/vagas#2145]
## Descrição da vaga

Estamos procurando Front-end developers. para fazer parte do nosso time.

## Local

Escritório, São Paulo - Vila Leopoldina

## Benefícios

- VT
- VR

#### Diferenciais

- Horários flexiveis
- Possibilidade de Home Office (alguns dias da semana)

## Requisitos

**Obrigatórios:**
- HTML
- CSS
- Javascript (ES6)
- NPM
- GIT
- Experiência com frameworks JS

**Desejáveis:**
- Vue.js
- GULP
- SASS
- Scrum

**Diferenciais:**
- Facilidade em aprender e utilizar qualquer tipo de framework
- Conhecimentos com docker
- Node
- NoSQL

## Contratação

CLT/PJ a combinar

## Nossa empresa

A Uello é uma startup de entregas e fretes urbanos focada em pequenos e médios negócios. Utilizamos tecnologia e otimização de ponta para viabilizar serviços com alto grau de customização, acessível e de grande conveniência para nosso clientes.

## Como se candidatar

Por favor envie um email para marcelo.cerqueira@uello.com.br com seu CV anexado.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: it@uello.com.br

## Labels

- Alocado
- CLT
- PJ
- Pleno
- Remoto - Parcial

**Comment by RaquelOliveira0** [comment]
Ainda está aberta a vaga?

**Comment by jmarcelocjr** [comment]
Olá Raquel, tudo bem?

Está sim, continuamos a procura de uma pessoa Front-end Dev.

**Comment by jmarcelocjr** [comment]
> Ainda está aberta a vaga?

 Olá Raquel, tudo bem?

Está sim, continuamos a procura de uma pessoa Front-end Dev.
