### ISSUE TITLE
[Belo Horizonte] Front-end Developer Sênior (React Native)

### ISSUE THREAD

**Issue by tallesl** [frontendbr/vagas#2147]
## Descrição da vaga

- Ensino superior completo em Engenharia, Ciência da computação, ou áreas afins.
- Necessário no minimo 04 anos de experiencia.
- Experiência sólida com desenvolvimento em React Native para criação de aplicativos para iOS e Android
- Proficiente em NodeJS
- Proficiente em HTML, CSS e JavaScript
- Conhecimento e experiência em desenvolvimento de aplicativos web usando React.
- Conhecimento em ES6 funcionalidades, como por exemplo "arrow functions”
- Paixão por desenvolver UI incríveis, intuitiva e fáceis de serem utilizadas.
- Conhecimento em REST API e banco de dados.
- Experiência com metodologias Ágeis.

## Local

Remoto ou Escritório, Belo Horizonte - MG

## Contratação

CTL ou PJ. A combinar.

## Nossa empresa

https://www.linkedin.com/company/loovibrasil/about

## Como se candidatar

Entre em contato pelo LinkedIn: https://www.linkedin.com/jobs/view/1323923563

## Labels

- Alocado
- CLT
- PJ
- Remoto
- Sênior

**Comment by mja-maia** [comment]
Acho que pode ser encerrada. No linkedin já foi fechada a vaga!
