### ISSUE TITLE
[Curitiba] Desenvolvedor FrontEnd na DRIVEN

### ISSUE THREAD

**Issue by megandavulpi** [frontendbr/vagas#2149]
### Sobre a empresa: Driven

Somos a Driven CX, um grupo formado pelas empresas TopperMinds, Profite e BlueFoot, juntos somos o maior grupo consultivo digital do segmento e a única nativa digital. A metodologia Driven CX integra a modelagem do negócio à construção da jornada ideal, sem perder o foco na recomposição da margem financeira e na extensão do ciclo de vida dos clientes. Além de explorar o que há de melhor em análise de dados e automação de esforços de marketing digital de alta performance.
 
Somos 180 especialistas, atendemos 120 clientes, temos a previsão de faturamento de R$ 26 milhões em 2019 e meta de crescimento de 20% para 2020. Sediada em São Paulo, Rio de Janeiro e Curitiba, a DrivenCX realiza consultoria digital para 30 das 500 maiores empresas brasileiras.
 
Atuando em células multidisciplinares, atendemos uma carteira de clientes com projetos para quase todos os segmentos da indústria e do varejo, como Volkswagen, Movida, 3 Corações, Bancoob, Swift, Tramontina, Bradesco Cartões, Tok&Stok, Drogaria Araujo, Havaianas entre tantos outros expoentes nacionais do varejo e indústria.

### Descrição: O que você irá fazer?

Se você é apaixonado por desenvolvimento web e consegue resolver problemas lógicos de maneira ágil e inteligente, como front-end developer aqui na Driven você vai ter a oportunidade de desenvolver aplicações para um dos mais parrudos ecossistemas de e-commerce da América Latina.

### As habilidades necessárias:

Sólidos conhecimentos de Vanilla JS (es6+);
Experiencia avançada com React e Webpack;
Você consegue documentar seu código e seu colega vai entender tudo sem precisar te consultar;
Você domina HTML e CSS, afinal é o básico do desenvolvedor front-end;
Experiência com Git ou outras formas de versionamento;
Testes Unitários;

### Beneficios:

Além de fazer parte de uma empresa e time muito legal, com um ambiente descontraído com sala de jogos, biblioteca compartilhada e pizzada todo mês, você terá:

Vale Refeição;
Vale Transporte;
Plano de Saúde coparticipativo;

### Você gostará de trabalhar aqui se:

É normalmente inconformado(a) com coisas que não funcionam e gosta de mudar o jogo;
Gosta de interagir com a galera do trabalho;
Acredita que aprender mais sobre tecnologia e soft skills vão fazer de você um(a) profissional melhor;
Entende que o planejamento e o auto gerenciamento é imprescindível para o seu trabalho;
Gosta de participar ativamente e contribuir no produto com soluções realmente efetivas;
Gosta de um modelo de gestão horizontal e um ambiente muito legal de se trabalhar :);

### Candidatar: http://bit.ly/driven_front

**Comment by mandelaloko** [comment]
Enviado!
