### ISSUE TITLE
[São Paulo] Desenvolvedor Front-End/React (Júnior/Pleno)

### ISSUE THREAD

**Issue by weslleyss12** [frontendbr/vagas#215]
## Descrição da vaga

Tem experiência em React? Estamos em busca de 2 desenvolvedore Front-End Júnior\Pleno que sejam geek, curiosos, apaixonados por tecnologia e por fazer acontecer,
que queiram trabalhar em projetos sensacionais, colaborar, aprender, ensinar e que goste de trabalhar em grupo e com métodos ágeis.

## Local

Escritório, Av. das Nações Unidas, 18.801 - Próximo a estação Santo Amaro

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento front-end em geral (JavaScript, HTML, SASS e CSS)
- Experiência com React e Redux.

**Desejáveis:**
- Conhecimento em Boostrap
- Experiência com Desenvolvimento responsivo
- Experiência com Controle de Versão (SVN ou GIT)
- Experiência com React Native
- CSS3 (SMACSS, BEM ou OOCSS);
- AngularJS

**Diferenciais:**
- Conhecimento de animação de interface
- Boas noções de UX
- Conhecimento em alguma linguagem de Back-end
- Wordpress
- Gostar de aprender
- Boa comunicação e gostar de trabalhar em equipe
- Fazer um bom café =D

## Contratação

PJ a combinar

## Nossa empresa

Somos uma empresa de tecnologia\software house\produtora\startup inovadora com ambiente descontraído, uma equipe jovem, comprometida e muito fera! Além disso temos: sinuca, XBox com Kinect e muito happy hour, férias remuneradas, horário flexível, no dress code e um ambiente sensacional para crescer!

## Como se candidatar

Envie currículo com pretensão salarial para: atendimento@giganti.com.br

**Comment by eduardojmatos** [comment]
@weslleyss12 consegue descrever se a vaga é pra CLT ou PJ e qual o nível que vocês estão procurando (júnior, pleno, sênior)?

**Comment by weslleyss12** [comment]
@eduardojmatos informações atualizadas.
