### ISSUE TITLE
[REMOTO] Front-end developer no site Vagalume

### ISSUE THREAD

**Issue by lafraia** [frontendbr/vagas#2152]
## Descrição da vaga

Estou buscando profissionais que possam fazer parte de uma equipe remota para vários projetos no [Vagalume](https://www.vagalume.com.br/). Já temos algumas tarefas bem interessantes prontas para iniciar o desenvolvimento, mas boa parte do trabalho neste início é refatoração, otimização e ganho de confiança (qualidade, prazo e tempo de execução). Teremos melhorias no CMS interno, otimização de carregamento do site, automação, criação de testes, desenvolvimento do app e muitas outras coisas.

O foco é encontrar pessoas **bem** proativas, experientes, autodidatas, auto-motivadas e que possam executar as tarefas com bastante paixão, rapidez e com qualidade técnica. 💪

Estamos em um momento de muita mudança na forma de trabalho 100% remoto e, inclusive, sem exigência de horário definidos com comunicação de forma assíncrona (Gitlab e Slack). Combinação ideal para **nômades digitais**! 😃 Cada tarefa possui uma data esperada de entrega e um tempo negociado de execução.

## Local

100% Remoto! 🙏

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com HTML5 e CSS3 (avançado)
- 3 anos de experiência com Javascript
- 2 anos de experiência com SEO
- Experiência anterior com trabalho remoto
- Foco em qualidade do resultado final
- Experiência com sites responsivos

**Desejáveis:**
- conhecimentos sólidos na [semântica do html5](https://www.semrush.com/blog/semantic-html5-guide/) (leia também [este artigo](http://html5doctor.com/avoiding-common-html5-mistakes/))
- conhecimentos AWS e Docker
- experiência anterior com Jekyll

## Contratação

PJ ou MEI

Nosso acerto seria por hora no final do mês, utilizando o [HubStaff](https://hubstaff.com) para reportar o tempo gasto nas tarefas (no final do mês, basta gerar um relatório). Assim, é necessário informar qual o seu valor por hora para trabalhar neste modelo.

## Nossa empresa

Você já deve ter buscado uma letra de música no Vagalume, chegou a hora de poder contribuir com o projeto ;-)

## Como se candidatar

Por favor envie um email para rh@vagalume.com.br com seu CV anexado - enviar no assunto: **Vaga Frontend** e responder as perguntas abaixo:

* Quanto tempo você tem disponível por semana?
* Qual é o melhor horário do dia que você tem a disponibilidade?
* Qual experiência anterior com trabalho remoto?
* O que você busca no seu desenvolvimento profissional?
* Qual sua experiência com (favor elaborar a resposta):
    * AWS (quais serviços usou?)
    * Javascript
    * Jekyll
    * Sites responsivos
    * PHP
* Por que você acha que deve ser escolhido?
* Como é o seu ambiente de desenvolvimento? SO, conexão, ambiente calmo, etc?
* Qual é o valor por hora que você acha justo trabalharmos neste modelo?

Se achar interessante compartilhar outras informações, pode mandar.

## Labels

- Remoto
- Freela
- PJ
- Pleno
- Sênior

**Comment by evertonnppp** [comment]
quanto vocês estão disposto a pagar pela hora

**Comment by ngustavo** [comment]
Enviei e não recebi resposta...

**Comment by evertonnppp** [comment]
Me chama no whats app estou me candidatando a vaga

**Comment by JulioVMelo** [comment]
Aguardando um feedback.

**Comment by evertonnppp** [comment]
21 992433897 whats app
