### ISSUE TITLE
[São Paulo] Front-end Developer na Blumpa

### ISSUE THREAD

**Issue by Zapiano** [frontendbr/vagas#2153]
## Descrição da vaga

Estamos a procura de um profissional para fazer parte do time de tecnologia do Blumpa com foco na área de Front-End. Nós trabalhamos com um web service com REST API, Back-end com Ruby on Rails, Front-end com REACT e app com REACT Native.

## Local

Escritório, São Paulo - Faria Lima (próximo ao Metrô Faria Lima)

## Benefícios

- A combinar

## Requisitos

**Obrigatórios:**
- React
- Git
- Mínimo 2 anos de experiência

**Diferenciais:**
- Ruby on Rails
- React native
- REST API

## Contratação

PJ.

## Nossa empresa

O Blumpa é uma empresa de tecnologia pioneira no Brasil que atua para facilitar a contratação de serviços de limpeza e passadoria de roupas pela internet, de forma rápida, simples e segura, por meio do website na internet e aplicativo para celular. Com nosso sistema, conectamos e auxiliamos os contratantes (usuários finais do serviço) e as profissionais autônomas credenciadas na plataforma do Blumpa (diaristas) que são responsáveis pela realização dos serviço de limpeza e passadoria.

## Como se candidatar

Preencha [este formulário](https://forms.gle/9rC9tV6p8yUduNMg7) que está disponível no nosso site de vaga: [https://blumpa.github.io/](https://blumpa.github.io/)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: pedro@blumpa.com.br

## Labels

- Alocado
- PJ
- Pleno

**Comment by jhonyskywalker** [comment]
Preenchido
