### ISSUE TITLE
[Remoto] Front-End Developer na Ruptiva (React/React Native)

### ISSUE THREAD

**Issue by maikelfb** [frontendbr/vagas#2158]
# Sobre a Ruptiva
Somos uma empresa de Santa Catarina que atua no desenvolvimento de aplicativos e Sistemas Web.

Nosso desafio é entregar soluções para problemas reais das empresas, promovendo a otimização de processos, trazendo mais informações para a tomada de decisão e contribuindo para resultados mais efetivos. Tudo isso através de aplicativos desenvolvidos com alta tecnologia, design focado no usuário e construção guiada por reais necessidades.

Buscamos por profissionais que gostem de desenvolvimento de software e tecnologia em geral, que estejam atentos às novidades e em constante evolução, que tenham capacidade de inovar e propor soluções, bem como facilidade de trabalhar em grupo.

Em nosso ambiente de trabalho cultivamos bons laços de relacionamento e amizade - prezamos muito pela harmonia e bem-estar de nossa equipe.

## Modalidade
Remota

## Tipo de contratação
PJ

## Remuneração
Salário a combinar (compatível com o mercado)

## Atividades
Você será responsável por:
- Construir interfaces suaves e perfeitas em ambos Android e iOS;
- Transformar designs e wireframes em código de qualidade;
- Construir componentes reutilizáveis;
- Manter o código e escrever testes automatizados para garantir a qualidade;
- Participar ativamente de decisões de tecnologias.

## Requisitos
- Experiência com React e/ou React Native;
- Typescript;
- Ter familiaridade com as especificações mais recentes do ES6/ES7;
- Saber consumir APIs de forma otimizada (GraphQL é um diferencial);
- Saber aplicar testes automatizados em aplicativos mobile;
- Ter conhecimentos de design de interface e experiência do usuário;
- Saber versionar código e interagir com GIT;
- É um diferencial ter experiencia com métodos ágeis;
- Ser curioso e estudioso. 

## Como se candidatar
Por favor, envie um email para maikel@ruptiva.com com seu CV anexado, pretensão salarial e demais informações.

## Labels
- PJ
- Pleno
- Remoto

**Comment by ribeiroevandro** [comment]
Enviado.
