### ISSUE TITLE
[São Paulo] React Native Developer na HONDANA

### ISSUE THREAD

**Issue by lazarofl** [frontendbr/vagas#2159]
## Descrição da vaga

Estamos buscando mais pessoas incríveis para os próximos desafios em nossa área de tecnologia utilizando **React Native**.

Você irá criar um aplicativo móvel para iOS e Android para a nossa plataforma, sendo responsável por desenvolver esse aplicativo juntamente com nossa equipe de tecnologia e produto.

## Local 

Escritório: CUBO Itaú - Alameda Vicente Pinzon, 54 - Vila Olímpia - São Paulo
🏢 Flexível

## Diferenciais

- No coração da Vila Olímpia
- Time de tecnologia experiente
- Escritório compartilhado com comunidade de mais de 200 startups
- Sala de jogos e churrasqueira no prédio
- Happy Hour todos os dias após as 18h com 🍺 free 👀 
- Slack

## Requisitos

**Obrigatórios:**
- Imprescindível ter trabalhado em ao menos um projeto utilizando React Native, e que esteja disponível nas lojas da Apple e Google

**Desejáveis:**
- Experiência com REST APIs
- Sólidos conhecimentos em JavaScript, incluindo sintaxe ES6+
- Familiaridade com XCode e Gradle
- Conhecimentos para publicação de aplicativo nas lojas

**Diferenciais:**
- Projetos opensource
- Testes automatizados
- Automatização de deploy

## Contratação

PJ a combinar
Stock Options após o primeiro ano conosco

## Nossa empresa

A Hondana existe para que as pessoas realizem seus potenciais!
Somos uma startup em ritmo de crescimento, acelerada pelo Google e Endeavor.
Somos uma **plataforma B2B** de capacitação e comunicação, que usa um aplicativo para levar o conhecimento certo, para a pessoa certa, para que ela possa trabalhar melhor.

SKY, Gympass, Heinekken e Grupo Pão de Açúcar são apenas alguns dos nossos clientes.
Com todo este sucesso, crescemos mais que 10x no último ano.

## Como se candidatar

Por favor acesse o endereço https://cubo.network/jobs/cb4952f0-9d9c-11e9-96a7-716e01729e16 para se candidatar.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 24 horas após cada processo.
E-mail para contato em caso de não haver resposta: lazaro@hondana.com.br

## Labels

- Júnior
- Pleno
- PJ

**Comment by felipefialho** [comment]
Cubo ❤️

**Comment by ribeiroevandro** [comment]
O link pra vaga, consta como **Encerrada**

**Comment by lazarofl** [comment]
A vaga ainda esta aberta, vou checar com a galera o que ocorreu, deve ter um timing de close ;)

**Comment by ribeiroevandro** [comment]
@lazarofl show man, mas te mandei email mesmo assim... ;)

**Comment by lazarofl** [comment]
Atualizado o link pessoal!
@ribeiroevandro eu já pedi para a Erika ligar para você, ela faz o primeiro contato te explicando sobre a Hondana e tudo mais, aí depois a gente se fala num screening de 15 min e avança nas etapas 🙂
Obrigado!
