### ISSUE TITLE
[Remoto e Alocado] Front-End Developer na Telnyx

### ISSUE THREAD

**Issue by hugobessaa** [frontendbr/vagas#2160]
## Descrição da vaga

Nós estamos procurando por Front-End Developers com experiência para construir webapps intuitivos e robustos para nossa suíte de produtos que possibilitam serviços de comunicação críticos para nossos clientes. Para esta vaga, você deve se importar bastante com performance, manutenabilidade e acessibilidade na web e deve desenvolver sistemas eficientes, modulares e acessíveis.

## Local

Remoto ou Escritório, São Paulo - Av. Paulista

## Benefícios

- Compensação competitiva e opções de ação
- Fundo de desenvolvimento profissional (conferências, cursos, livros)
- Férias e dias de folga livres
- Ambiente de trabalho flexível
- Computadores de alta-qualidade, e acessórios (fitness tracker, fones)

#### Diferenciais

- Startup em crescimento, com modelo de negócio estabelecido
- Empresa ágil, com foco em crescimento
- Objetivos e plano de carreira transparentes
- Empresa americana, com três escritórios nos EUA e Europa e com time remoto em diversos países no mundo

## Requisitos

**Obrigatórios:**
- 4 anos de experiência com JavaScript, HTML e CSS
- 2 anos de experiência com um framework JavaScript moderno.
- Inglês intermediário para escrita e comunicação (oferecemos curso para aprimoramento).

**Desejáveis:**
- Inglês avançado para escrita e comunicação.

- Você entende procura aplicar padrões de experiência de usuário e princípios de design de UIs.
- Você tem grande conhecimento em HTML5 & CSS3 e em manter compatibilidade com diversos browsers.
- Fluência em APIs da web e em integração com bibliotecas JS de terceiros.
- Familiaridade com frameworks e metodologia back-end em JavaScript, como Express.js e server-side rendering.
- Desejo de analisar e tirar proveito das melhores tecnologias front-end.

**Diferenciais:**
- Você utilizou React em um projeto de trabalho para entregar experiências para usuários finais.

## Contratação

PJ a combinar (Independent Contractor) ou CLT

## Nossa empresa

At Telnyx, we build voice, messaging, data and wireless services that facilitate high-fidelity, secure and modern modes of communication. As engineers, we develop globally distributed services that empower developers to create applications capable of real-time communication. We have nearly one hundred employees (70% engineers) between our remote team members, Chicago, USA office and Dublin, Ireland office.

## Como se candidatar

Cadastre-se neste link https://hire.withgoogle.com/public/jobs/telnyxcom/view/P_AAAAAACAAKcKaNOVVsZXMJ

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: hugo@telnyx.com

## Labels

- Remoto
- Alocado
- CLT
- PJ
- Pleno
- Sênior

**Comment by fabriciofrontarolli** [comment]
Sent :)

**Comment by jhonyskywalker** [comment]
Sent 👍

**Comment by LucasHiago** [comment]
[
![Uploading image.png…]()
](url)

**Comment by LucasHiago** [comment]
[https://lucashiago.github.io/catalogo/](url)

**Comment by jpmsegurado** [comment]
Essa vaga agora se tornou apenas alocada em SP?

**Comment by hugobessaa** [comment]
No momento, sim
