### ISSUE TITLE
[São Paulo/SP] Front-end Developer Webdesigner na GENDO

### ISSUE THREAD

**Issue by jbaladao** [frontendbr/vagas#2164]
#  Descrição da vaga

A startup [Gendo](https://www.gendo.com.br) (antes SuperAgendador) é um SaaS para prestadores de serviços. Procuramos um profissional com pelo menos 1 ano de experiência com criação webdesign e usabilidade de sistemas web/mobile!

## Local

Próximo ao metro Jabaquara, GreenWork Boulevard na Zona Sul de São Paulo - SP

## Benefícios

- 1 dia de home-office por semana a combinar;
- Vale Refeição;
- Café da manhã, bebidas no frigobar, entre outros mimos;
- PS4 liberado com vários jogos para descontrair;
- Pagamentos de bonus mensais confomre metas batidas.

## Obrigatórios:

- 1 ano de experiência em empresa de tecnologia de qualquer porte;
- 2 anos de experiência com Photoshop, Gimp ou similar;
- conhecimentos avançados em usabilidade (UX) de sistemas web/mobile;
- conhecimentos em criação e edição vetorial, Corel, Inkscape, ou similar;
- alguma noção de HTML e CSS;

## Desejáveis:

- ter trabalhado com algum sistema online no modelo SaaS;
- alguma experiência com metodologias ágeis de desenvolvimento.

## Contratação

PJ a combinar

# Nossa empresa

A startup [Gendo](https://www.gendo.com.br) (antes SuperAgendador) já está entre os maiores sistemas de gestão para Prestadores de Serviços do Brasil, nossos clientes movimentaram juntos aproximadamente 36 milhões de reais em dezembro de 2018. A empresa já foi acelerada em 2016 no evento InvestorsDay da CampusParty (anjos via Broota) e, no ano de 2017 recebeu um novo investimento do grupo Bossa Nova (pré-seed).
Estamos naquela fase incrível onde uma pequena startup pode evoluir rapidamente para uma empresa de grande porte. Este é o nosso sonho, se quiser participar dele venha trabalhar conosco. Vivenciar o nascimento e transformação de uma Startup é incrível e as oportunidades de crescimento e aprendizado são muitas!

# Como se candidatar

Por favor, envie um email para [jbaladao@gendo.com.br](mailto:jbaladao@gendo.com.br) com seu CV anexado - enviar no assunto: "Vaga Webdesigner"

# Outras vagas

Também estamos sempre com vagas abertas para Dev. Front-end!

Muito obrigado!

**Comment by ThiagoCarvalhoAds** [comment]
Encaminhei com CV. 
Sucesso!!
