### ISSUE TITLE
[São Paulo/SP] Front-end Developer na Pontaltech

### ISSUE THREAD

**Issue by viebig** [frontendbr/vagas#2165]
# Inscreva-se em

[https://pontal.gupy.io/jobs/49399](https://pontal.gupy.io/jobs/49399)

# O que você irá fazer?

Trabalhar em time, utilizando metodologias ágeis para resolver problemas do mundo real;

Desenvolver aplicações e serviços web utilizando as melhores metodologias e padrões de projetos;

Integrar sistemas utilizando Angular e React;

Monitorar e ajustar aplicações pensando na performance;

Parear com desenvolvedores backend e gerentes de produto;

# O que esperamos de você?

- HTML
- CSS
- Linux 
- Javascript
- Webpack
- Angular
- React
- Testes automatizados

# Porque trabalhar na Pontal?
Somos uma empresa de tecnologia que atua no mercado de comunicação digital e contatamos mais de 50 milhões de brasileiros todos os meses. 

Somos uma empresa jovem e dinâmica, possui em seu DNA a modernidade e inovação.

Buscamos os melhores para fazer parte dessa história de sucesso!

#  Nossos benefícios

- Vale refeição
- Vale transporte ou auxilio estacionamento
- Assistência médica e odontológica
- Inglês in company
- Convênio farmácia
- Convênio com diversas faculdades e cursos profissionalizantes
- Ambiente descontraído e divertidos eventos internos

## Venha fazer parte do nosso time!

**Comment by ThiagoCarvalhoAds** [comment]
E ae, @viebig, blz? 
Não consegui acessar o link.

**Comment by viebig** [comment]
Opa... http://pontal.gupy.io

Vê se consegue e me avisa

Em ter, 2 de jul de 2019 12:57, Thiago Carvalho <notifications@github.com>
escreveu:

**Comment by ThiagoCarvalhoAds** [comment]
Consegui acessar, vou me cadastrar.
Obrigado! 🙏

**Comment by stochiconrado** [comment]
Como faço para me candidatar?

Em ter, 2 de jul de 2019 12:10, Guilherme Viebig <notifications@github.com>
escreveu:
