### ISSUE TITLE
[São Paulo / SP] Front-End Developer (React) na Blue Digital

### ISSUE THREAD

**Issue by bellthoven** [frontendbr/vagas#2166]
# Sobre a empresa

A [Blue Digital](http://bluedigital.com.br/) possui dois sócios, o [Fábio Trentini](https://www.linkedin.com/in/trentas/) (ex CIO/board da Bionexo) e o [Marco Moreira](https://www.linkedin.com/in/marcoluciomoreira/) (ex VP Sênior de Operações da Walmart.com Brasil e CTO Latam). Nosso objetivo é melhorar as relações entre humanos e o digital através dos serviços que prestamos. Entre eles estão a Transformação Digital, Diligência Prévia Digital e também a formação de times e alocação de pessoas altamente especializadas em vagas estratégias das nossas empresas parceiras.

# A vaga

A vaga destina-se a Front-End Developers (Pleno e/ou Senior) com experiência em React, que irão trabalhar em cima de um conjunto de APIs escrito em Go junto de uma FINTECH / Banco Digital. Mais informações sobre a vaga podem ser encontrados [neste endereço](https://carreiras.bluedigital.com.br/senior-front-end-developer), onde também consta o link para o formulário de submissão do interesse.

## Labels

- Alocado
- React
- PJ
- Pleno
- Sênior

**Comment by jhonyskywalker** [comment]
Enviado!
