### ISSUE TITLE
[REMOTO ou São Paulo] Front-end Developer na Simbiose

### ISSUE THREAD

**Issue by gmenegatti** [frontendbr/vagas#2170]
Olá, pessoal,

Estamos em busca de pessoas que tenham interesse em trabalhar (remotamente) na área de desenvolvimento front-end da Simbiose, qualquer que seja sua linguagem e nível de conhecimento atual. Temos oportunidades para todos os níveis.

Para se candidatar, basta seguir os passos indicados no link abaixo:
https://www.simbioseventures.com/trabalhar-na-simbiose/como-trabalhar-na-simbiose

**Carga horária:**
Opções de 4 ou 6 horas diárias.

**Remuneração:**
De acordo com seu nível de conhecimento e maturidade (pessoal e profissional).

**Forma de contratação:**
CLT ou PJ

**Local de trabalho:**
Opções de trabalho remoto OU no nosso escritório em São Paulo (Av. Dr. Chucri Zaidan, 1550).

**Benefícios:**
- Horário de trabalho realmente flexível
- Participação significativa nos lucros e sucesso da empresa, veja:
https://www.simbioseventures.com/sobre-a-simbiose/compartilhamento-de-sucesso

**Candidatar:**
Para se candidatar, basta seguir os passos indicados no link abaixo:
https://www.simbioseventures.com/trabalhar-na-simbiose/como-trabalhar-na-simbiose

**Comment by pissulin** [comment]
Boa tarde, o inglês é um requisito obrigatório?

**Comment by gmenegatti** [comment]
Olá, Anderson,

Sim, buscamos pessoas que tenham inglês avançado.

**Comment by luicesar** [comment]
Atualmente sou programador .NET Core e com conhecimento intermediário em Ionic 3 Framework.
Estou fazendo um curso pela empresa Rockeseat nas tecnologias em Node.js, ReactJS e React Native.

Só que meu inglês é técnico e meu conhecimento em ReactJS é júnior.

**Comment by saaddalida** [comment]
Olá,
Estou preenchendo o formulário de inscrição e não tem uma opção de desenvolvedor front-end quando questionado qual processo de seleção estou me candidatando. Qual deveria marcar? 
Obrigada

**Comment by gmenegatti** [comment]
Olá, Luis,

De tudo o que você descreveu o maior problema é juntamente o inglês, que
para nós é imprescindível ser avançado.

Sobre as tecnologias, para nós não importa muito, pois o que você não
souber fazer ainda, nós compramos cursos/livros e você aprende. :-)

**Comment by gmenegatti** [comment]
Desculpe pelo erro, saaddalida.

Pronto, agora já tem a opção "Desenvolvimento Front-end" no formulário.

**Comment by pmapelli** [comment]
Sobre o inglês. Mesmo para a leitura eu necessito da ajuda de um dicionário pois tenho vocabulário limitado. Isso é o suficiente para a vaga? Pergunto por que na resposta indicou inglês avançado, e no site diz algo entre intermediário e avançado sem deixar explicito se esta se referindo a leitura ou escrita.

Desde já agradeço.

**Comment by gmenegatti** [comment]
Olá, Pedro,

Precisamos de inglês avançado para ambos, leitura e escrita.

Infelizmente todos os nossos nossos materiais de estudo e documentações
estão em inglês, além do nosso próprio produto e mercado de atuação também
serem em inglês.

Obrigado

**Comment by pmapelli** [comment]
Obrigado! De qualquer forma estudar sobre a empresa e o material disponibilizado já foi de grande ajuda.

**Comment by HidemitsuHashimoto** [comment]
Boa noite. Com relação ao inglês, a empresa não abre oportunidade para também evoluir essa hard skill? Pergunto isso pois em minha trajetória de estudos utilizo tanto materiais em português quanto em inglês, e o que não consigo entender eu utilizo o google tradutor.

**Comment by gmenegatti** [comment]
Obrigado você pelo feedback. :-)

Caso tenha interesse, recentemente anunciamos o lançamento da Universidade
Simbiose, que visa ensinar programação (do básico ao super avançado)
totalmente sem custo.

Mais detalhes no link abaixo:
https://www.simbioseventures.com/universidade-simbiose/nossa-universidade

**Comment by gmenegatti** [comment]
Olá, Hidemitsu,

Sim, temos essa abertura sim, mas precisa ter um nível mínimo de inglês, um
nível intermediário quase avançado, do contrário a pessoa fica realmente
muito improdutiva.

Nós estamos com um "problema" exatamente assim nesse momento. A pessoa até
sabe programar bem, mas quando passamos alguns livros de Kafka, ZooKeeper,
etc. para que ela possa aprender mais sobre algums serviços que utilizamos,
ela simplesmente travou e não conseguiu evoluir nada. Aí temos que tirar
alguém da equipe para poder ensinar em PTBR o que já está disponível em
inglês.

Eu sei que o inglês ainda é uma grande barreira aqui no Brasil e que
perdemos excelentes profissionais por conta disso, mas como utilizamos o
que existe de mais avançado de tecnologia e a documentação é complexa e
toda em inglês, um profissional sem inglês aqui dentro da empresa realmente
vai "patinar" muito até ser produtivo.

Desculpa. :-(

**Comment by felipenoka** [comment]
Olá, @gmenegatti 

Alguma oportunidade para quem está começando a carreira no front ?

abs.,

**Comment by HidemitsuHashimoto** [comment]
Sem desculpas, eu que agradeço a atenção e resposta. Ainda não tenho o nível necessário de inglês, mas no futuro vou com certeza me candidatar. Uma ótima noite.

**Comment by gmenegatti** [comment]
Definitivamente sim, @felipenoka.

Nós temos oportunidades para todos os níveis de conhecimento, até para quem ainda sequer saber programar. :-)

**Comment by gmenegatti** [comment]
@HidemitsuHashimoto, quer saber, que tal tentar?

Pode fazer esses dois testes abaixo? Vai gastar uns 30-40 minutos para fazer e, se não der certo, pelo menos eu te dou um feedback (por email) sobre o seu perfil. :-)

- Teste de Inglês:
https://docs.google.com/forms/d/e/1FAIpQLSdayN9p7YR4Qs-JmkXdiTw4fyUoOVbvnEaFVVR_gDVACAYAFA/viewform

-Análise de Perfil Comportamental
https://docs.google.com/forms/d/e/1FAIpQLScTtGmCX3-ifEB8g1TlTZisGp_25e_wlBkpf9Z04UUQyfZXPg/viewform

Fica extremamente à vontade para realizar ou não os testes.

**Comment by HidemitsuHashimoto** [comment]
Ok vou tentar. Muito obrigado.

**Comment by HidemitsuHashimoto** [comment]
Prezado @gmenegatti.

Acabei de realizar os testes mencionados.

Muito obrigado pela oportunidade.

Tenha uma ótima noite.

**Comment by gmenegatti** [comment]
Acabei de olhar o resultado do seu teste @HidemitsuHashimoto.

Vou te retornar por email para que fique privado.

**Comment by 1TATO** [comment]
Me interessei muito pela oportunidade, principalmente eu que estou no início do curso de ADS e estou querendo entrar no mercado de trabalho. Vou fazer os testes e esperar o retorno.

**Comment by halkliff** [comment]
Estou extremamente feliz com essa oportunidade! Já fiz os testes e enviei o formulário, estou aguardando ansiosamente a resposta!

**Comment by AnakinRibeiro** [comment]
Realizei os testes porém ainda não enviei o formulário por quero tirar um tempo para assistir com calma o vídeo presente na ultima etapa do formulário. 

Algum problema em enviar apenas o formulário hoje no período da tarde?

**Comment by gmenegatti** [comment]
Sem problemas, @AnakinRibeiro. Não temos prazo limite pra inscrição.

**Comment by Ruttmann** [comment]
Já fiz os testes de inglês, matemática e perfil, mas ainda não consegui tempo pra preencher o último formulário.

**Comment by juliomerisio** [comment]
All committed. 
The journey through the forms has been an inspiring experiênce. I want to thank you for offering this opportunity to all community.

**Comment by MorenaNobre** [comment]
Prezado @gmenegatti.
Vi em mensagens anteriores que vocês oferecem vagas até mesmo para quem ainda não sabe programar.
Estou começando na área de programação e ainda estou no processo de aprendizagem, porém possuo inglês avançado, morei dois anos e meio nos Estados Unidos.
Tenho chances para uma vaga?

**Comment by gmenegatti** [comment]
Olá, @juliomerisio,

Muito obrigado pelas palavras gentis. :-)

Olá, @MorenaNobre,

Claro, com certeza tem chances. O que vale para nós é 99% atitude e comportamento, o resto é "fácil" de aprender.

**Comment by alissonb13** [comment]
Olá, @gmenegatti ! O inglês é somente para escrita e leitura?

**Comment by gmenegatti** [comment]
Olá, @alissonb13, sim, leitura e escrita, não precisa ter conversação fluente.

**Comment by halkliff** [comment]
@gmenegatti quanto tempo para obter uma resposta? Enviei todos os formulários há 5 dias mas nada até agora...

**Comment by gmenegatti** [comment]
Olá, @halkliff, 

Peço desculpas pela demora. Realmente foram muitos inscritos.

Até amanhã todos receberão um retorno, positivo ou negativo.

**Comment by VinixGonzalez** [comment]
Boa noite, a vaga já foi preenchida ? Att,

**Comment by gmenegatti** [comment]
Olá, @VinixGonzalez, ainda temos diversas vagas.

**Comment by VinixGonzalez** [comment]
@gmenegatti o que é preciso para a vaga? Somente realizar os testes ?

**Comment by gmenegatti** [comment]
Sim, @VinixGonzalez, só precisa seguir todos os passos indicados no link abaixo:

https://www.simbioseventures.com/trabalhar-na-simbiose/como-trabalhar-na-simbiose

**Comment by alissonb13** [comment]
Quanto tempo demora pra dar a resposta?

**Comment by gkal19** [comment]
@gmenegatti Eu lhe mandei um e-mail agora a pouco. Pode dar uma olhada?
E sim, tem a ver com a vaga e a empresa.

**Comment by gmenegatti** [comment]
Olá, @gkal19, vi e acabei de responder.

@diogomoretti, estamos correndo ao máximo para que quem se inscreveu tenha uma resposta até o final dessa semana. Peço desculpas pela demora, mas pode ter certeza que analisamos cuidadosamente cada uma das respostas de todos que se inscrevem.

**Comment by VinixGonzalez** [comment]
@gmenegatti Boa noite, acabei de responder os formulários. 
Aguarto contato, Att.

**Comment by baciotti** [comment]
Oi @gmenegatti, bom dia!
Respondi os formulários! Comecei ontem à noite e terminei hoje! Muito obrigado!

**Comment by felipenoka** [comment]
Olá @gmenegatti, acabei de responder os formulários!
Fico no aguardo do retorno e agradeço a atenção nas issues.
abs

**Comment by FranciscoWBarros** [comment]
> Olá, pessoal,
> 
> Estamos em busca de pessoas que tenham interesse em trabalhar (remotamente) na área de desenvolvimento front-end da Simbiose, qualquer que seja sua linguagem e nível de conhecimento atual. Temos oportunidades para todos os níveis.
> 
> Para se candidatar, basta seguir os passos indicados no link abaixo:
> https://www.simbioseventures.com/trabalhar-na-simbiose/como-trabalhar-na-simbiose
> 
> **Carga horária:**
> Opções de 4 ou 6 horas diárias.
> 
> **Remuneração:**
> De acordo com seu nível de conhecimento e maturidade (pessoal e profissional).
> 
> **Forma de contratação:**
> CLT ou PJ
> 
> **Local de trabalho:**
> Opções de trabalho remoto OU no nosso escritório em São Paulo (Av. Dr. Chucri Zaidan, 1550).
> 
> **Benefícios:**
> 
> * Horário de trabalho realmente flexível
> * Participação significativa nos lucros e sucesso da empresa, veja:
>   https://www.simbioseventures.com/sobre-a-simbiose/compartilhamento-de-sucesso
> 
> **Candidatar:**
> Para se candidatar, basta seguir os passos indicados no link abaixo:
> https://www.simbioseventures.com/trabalhar-na-simbiose/como-trabalhar-na-simbiose

Boa tarde @gmenegatti, respondi os formulários.
Ficarei no aguardo para feedback.
Obrigado.

**Comment by VinixGonzalez** [comment]
@gmenegatti, demora quanto tempo para avaliar os questionários?

**Comment by felipebazza** [comment]
Gostaria de deixar escrito aqui, independente de ser selecionado ou não, um grande parabéns para a empresa pelo processo de inscrição para a vaga. Nos passa uma imagem realmente grandiosa. 
Ótimo trabalho a todos na Simbiose!

**Comment by pedroffd** [comment]
I think it's great you guys encouraging people to practice English on a daily basis for the job, I've been trying to comment on github / youtube in English and I've changed the language of my smartphone and my pc to get closer to being considered fluent , I completed the registration process and look forward to get your feedback

**Comment by gmenegatti** [comment]
Olá, @FranciscoWBarros, obrigado.

Olá, @VinixGonzalez, acabamos agora de avaliar todos que se inscreveram até a última sexta. Dentror de algumas horas enviaremos um retorno para quem não foi aprovado.

Olá, @felipebazza, agradeço profundamente por sua palavras gentis e de incentivo.

Olá, @pedroffd, realmente o inglês é fundamental na nossa área. É desafiador, mas é uma realidade. Sempre perdemos pessoas boas pela questão do idioma.

**Comment by FranciscoWBarros** [comment]
Ok @gmenegatti, no aguardo. Tenho uma dúvida, mesmo quem não for aprovado terá acesso ao material de estudo da Universidade? Porque de qualquer forma gostaria de poder estudar sobre Machine learning e técnicas de aprendizagem, além de ajudar na comunidade da universidade, gostei do conceito.   :)

Obrigado pela resposta.

**Comment by EzequielBrilhante** [comment]
Bom dia, @gmenegatti , a vaga ainda está disponível ?

**Comment by YaakovDantas** [comment]
Me interesso bastante por esta empresa, mas ainda não posso me aplicar, posso me submeter a vaga a qualquer momento ?

**Comment by gmenegatti** [comment]
Olá, @FranciscoWBarros, infelizmente não, nesse momento apenas os aprovados tem acesso ao material.

Olá, @EzequielBrilhante, está sim. Continuamos selecionado.

Olá, @YaakovDantas, claro. Selecionamos pessoas continuamente, o ano inteiro.

**Comment by gmenegatti** [comment]
Pessoal, acabei de enviar um email com o feedback para todos que se inscreveram e infelizmente não foram selecionados dessa vez.

Agradeço profundamente a participação de todos.

IMPORTANTE: O processo de seleção continua aberto e selecionando pessoas.

**Comment by FranciscoWBarros** [comment]
Ok, acessei o link do feedback e foi o melhor que já recebi, isso mostra o zelo e atenção que vocês tem com os colaboradores. Quem sabe no futuro possamos trabalhar juntos.

Muito obrigado.

**Comment by baciotti** [comment]
Boa noite @gmenegatti, as pessoas selecionadas também receberam contato?

Me inscrevi há alguns dias e não recebi nada até o momento,

Muito obrigado,

**Comment by EzequielBrilhante** [comment]
Obrigado, @gmenegatti , irei me candidatar à vaga!

**Comment by gmenegatti** [comment]
Olá, @baciotti, sim, sempre enviamos algum feedback, seja ele positivo ou negativo. Mas ainda temos diversas pessoas para avaliar. Se não recebeu nada ainda, pode aguardar que irá receber.

Olá, @FranciscoWBarros, muito obrigao pelas palavras gentis e de incentivo. Para trabalharmos juntos, depende 99% de você e apena 1% de nós. :-)

Olá, @EzequielBrilhante, legal, obrigado. 👍

**Comment by thejoaov** [comment]
@gmenegatti tenho inglês avançado pra fluente, porém estou começando agora, com react e node (futuramente react native também). A vaga ainda está disponível?

**Comment by gmenegatti** [comment]
Olá, @thejoaov, a vaga ainda está disponível sim, o processo continua aberto para inscrições.

**Comment by baciotti** [comment]
Bom dia a todos!

@gmenegatti , o processo ainda está em andamento? Fiz o cadastro dia 11/julho e ainda não recebi um retorno, será que chegou tudo certo aí para vocês?

Muito obrigado :)

**Comment by renantbastos** [comment]
@gmenegatti fiz os testes. Pode me dar um feedback por favor?

**Comment by allanplobo** [comment]
Já tive inglês avançado e parei de praticar... Mas, por exemplo, ler documentações em inglês não tenho dificuldade!
Li logo acima que poderiamos fazer o teste e você daria o feedback, ainda está aberta essa oportunidade? =)
Ah, e claro, eu tô iniciando agora de fato a estudar Front-End, teria espaço para esse nível no time? (Estagiário, por exemplo)

**Comment by MaikonTT** [comment]
Não sei se ainda estão à procura, mas estou muito animado só pelo anúncio de incentivarem ao aprendizado!

**Comment by YaakovDantas** [comment]
Mandei formulário de inscrição para a universidade simbiose, já faz um mês, não tive nenhum tipo de retorno ainda.

**Comment by cerberushades** [comment]
Já faz mais de um mês que me inscrevi no processo seletivo da Simbiose, tendo respondido todas as perguntas com bastante parcimônia e inclusive assistido ao vídeo que foi solicitado. Até o momento não recebi nenhuma resposta.

**Comment by YaakovDantas** [comment]
Não deve tá perto de seleção, devem voltar a ver quando abrir novas vagas
