### ISSUE TITLE
[Curitiba] Front-End Developer na [Glow]

### ISSUE THREAD

**Issue by martinsthiago** [frontendbr/vagas#2174]
Estamos procurando desenvolvedores que queiram revolucionar um mercado que movimenta anualmente mais de 40 Bilhões de Reais. Sua missão será, junto com a gente, ajudar esse Mercado a se profissionalizar, criar ferramentas que geram novos negócios para nossos clientes e facilitar a vida dos clientes dos nossos clientes. Oferecemos uma solução completa. Um potente ERP aliado a um CRM que nasceram com a ambição de se tornarem líderes de Mercado.
Gosta de desafios? Vem com a gente!

## Curitiba

Remoto ou Escritório, Curitiba - Centro

#### Diferenciais

• Ritmo sustentável de trabalho.
• O melhor ferramental é nossa responsabilidade para que você seja produtivo. Ninguém merece máquinas travando.
• Abertura para discutir com os sócios. Suas ideias têm valor para nós.
• Ambiente de muita autonomia, aprendizado e desafios.
• Avaliação de desempenho transparente e constante. Sua evolução vai nos levar muito mais longe.
• Escritório novinho e bem localizado. 

## Requisitos

**Obrigatórios:**
• Ferramenta de Versionamento de código. ( Git )
• Desenvolvimento Web (HTML, CSS)
• Conhecimento de Design
• Frameworks Javascript (Vue)
• TypeScript
• Javascript (ES6)

**Desejáveis:**
• Vivência com testes automatizados
• Apollo GraphQL
• Firebase
• Metricas ( Analitycs, Mixpanel, etc )
• React

## Contratação

PJ a combinar - você não vai se arrepender!

## Nossa empresa

Nascemos com um objetivo claro. Assumir a liderança de mercado!

## Como se candidatar

Por favor envie um email para thiagomartins.ufpr@gmail.com com seu CV anexado.
Enviar perfil do Linkedin e perfil do Github

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dia após cada processo.

## Labels

- Alocado
- Remoto
- Pleno
- PJ
- Remoto
- Sênior

**Comment by evertonnppp** [comment]
oi me chama no whats app 21992433897 , para me entrevista a vaga e remoto

**Comment by LucasHiago** [comment]
lucashiago.dsf@gmail.com enviou o e-mail interessado na vaga (remoto)
