### ISSUE TITLE
[São Paulo] Desenvolvedor Front-End & UI

### ISSUE THREAD

**Issue by danarcoverde** [frontendbr/vagas#218]
## Descrição da vaga

Buscamos um desenvolvedor front-end com boas habilidades em design de interfaces para se juntar ao nosso time de produto. O objetivo do profissional é dar agilidade ao processo de criação e melhoria nas interfaces de produto, landing pages, newsletters, além de gerenciar testes de usabilidade e analisar comportamento de navegação dos usuários.

## Local

Escritório em São Paulo-SP (Rua Itapeva, 378, cj. 131, Bela Vista)

## Benefícios

- Bônus trimestral
- Ambiente Flexível

## Requisitos

**Obrigatórios:**
- 2 ou 3 anos de experiência na área
- Domínio em JavaScript, HTML e CSS
- Noções de design UX/UI para sistemas web internos e externos
- Capacidade de escrever código eficiente, escalável e reutilizável
- Conhecimento dos princípios de design ágil e adaptativo, traduzindo-se em modelos fluídos e responsivos
- Experiência em design de layouts ou landing pages multi-plataforma
- Experiência em pré-processadores CSS (Sass, Less, Stylus)
- Experiência em controle de versão, como Git, Bitbucket
- Design de Interfaces (Photoshop, Illustrator, Design Mobile)
- Conhecimento de Testes A/B 

**Desejáveis:**
- Conhecimento de Ruby / Rails;
- Conhecimento em um ou mais frameworks JavaScript (React, Angular, etc.)
- Conhecimento de SEO
- Conhecimento em semântica, usabilidade e acessibilidade

## Contratação

PJ a combinar

## Nossa empresa

O Netshow.me é uma startup que oferece soluções em transmissões ao vivo de ponta a ponta (CDN, SaaS e Produção) e possui clientes como Esporte Interativo, Globo e Saraiva. Fundada no final de 2013, a empresa já ganhou diversos prêmios nacionais e internacionais como IBM Smartcamp, Prêmio Startups Lide Futuro, Set Expo, Sebrae Like a Boss e outros. Seus fundadores, Daniel Arcoverde e Rafael Belmonte, foram eleitos pela revista Forbes dentre os 30 jovens com menos de 30 anos mais inovadores do país. Venha trabalhar em uma startup de destaque, ambiente informal e elevado potencial de aprendizado e crescimento!

## Como se candidatar

Basta acessar o link: http://netshow-me.gupy.io/candidates/vacancy/58794afcf9a0e140277fcd03/
e clicar em "Canditar-se para esta vaga".

**Comment by LFeh** [comment]
Qual o nivel @danarcoverde?

**Comment by danarcoverde** [comment]
@LFeh a idéia é já ter pelo menos 2 ou 3 anos de experiência de trabalho na área e cumprir os requisitos solicitados!
