### ISSUE TITLE
[Belo Horizonte] Front-end Developer na Mercatório

### ISSUE THREAD

**Issue by danfaiole** [frontendbr/vagas#2180]
## Descrição da vaga
Espera-se do desenvolvedor contratado as seguintes atividades: 

 - Manutenções e inovações pontuais em sistema legado 
 - Desenvolver novas plataformas para empresa utilizando Angular 2+
 - Desenvolver formulários para sistema de consultas 
 - Desenvolver telas responsivas utilizando Material Design 
 - Criação de componentes reutilizáveis no novo sistema 
 - Integração da plataforma com APIs 
 - Propor melhorias e novas funcionalidades
 - Cooperar com o compartilhamento de conhecimento com os desenvolvedores Junior da equipe.

## Local

Escritório em Belo Horizonte, Bairro Bandeirantes, próximo ao parque Guanabara.

## Benefícios

 - VT/VR 
 - Plano de saúde 
 - Plano odontológico 

#### Diferenciais

 - No Dress Code 
 - Horário Flexível 
 - Café da tarde 
 - Ambiente descontraído
 - Sala de descanso com arcade e puffs

## Requisitos

**Obrigatórios:**

 - Experiência de pelo menos 3 anos com Angular 2+ 
 - Experiência em sistemas modulares no Angular 
 - Experiência com CSS e técnicas responsivas de desenvolvimento 
 - Git/Gitflow 
 - Ser responsável na execução de tarefas

**Desejáveis:**
- Facilidade para repassar o conhecimento e liderança de equipe
- Experiência com time Scrum 

**Diferenciais:**
 - Conhecimento em algum framework de API (Bônus para Ruby on Rails)
 - Desejável experiência em interações com serviços da Amazon (S3,
   Cloudfront)
 - Experiência com UX

## Contratação

CLT (De R$3000 a R$4000 dependendo da experiência)

## Nossa empresa

A Mercatório é uma startup mineira fundada em 2016, que acredita que o  mercado jurídico-financeiro precisa se tornar mais moderno e eficiente  com a incorporação de novas tecnologias. Para fazer isso, mapeamos e  analisamos processos judiciais de tribunais de todo o Brasil, fornecendo  informações qualificadas e estruturadas para o mercado. Ajudamos,  assim, pessoas e fundos de investimentos a tomarem decisões com maior  agilidade e assertividade, gerando bons negócios para ambas as partes.

## Como se candidatar

Por favor envie um email para daniel.faiole@mercatorio.com.br com seu CV anexado - enviar no assunto: Vaga Angular

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: daniel.faiole@mercatorio.com.br

## Labels

- Alocado
- CLT
- Pleno

**Comment by mateusduraes** [comment]
Enviado.

**Comment by danfaiole** [comment]
Fechando a vaga. Contratamos através do grupo!

**Comment by danfaiole** [comment]
Estou reabrindo a vaga para o mesmo cargo.
