### ISSUE TITLE
[São Paulo] Front-End Developer na Ame Digital

### ISSUE THREAD

**Issue by gdias1012** [frontendbr/vagas#2182]
## Descrição da vaga

Como Front-end da Ame, você vai usar seus conhecimentos para:

- Desenvolver e manter sistemas web (desktop e mobile)
- Criar bibliotecas/códigos (reutilizáveis)
- Colaborar com o time de back end de UX/UI, garantindo a viabilidade técnica de todas as features
- Otimizar app/web para máxima velocidade e escalabilidade
- Acompanhar cobertura de testes
- Desenvolver processo de deploy / automação de deploy
- Garantir a qualidade e consistência da marca
- Manter-se atualizado sobre novas tecnologias

Participar ativamente com o time de tecnologia para o desenvolvimento de produtos da nossa plataforma digital - desde a concepção até o acompanhamento em produção. 

Será referência dentro do time para questões técnicas.

## Local

Escritório, São Paulo - Vila Olímpia

## Benefícios

 - Plano de Saúde Bradesco
 - Seguro de vida
 - VR de R$ 18/dia
 - Auxílio creche
 - Descontos nos produtos vendidos pela americanas.com, submarino.com e shoptime.com.

#### Diferenciais

- Sala de jogos
- Dresscode Liberado

## Requisitos

**Obrigatórios:**
 - 3 anos de experiência React 
 - Formação Superior
 - CSS (responsivo), Javascript e HTML5
 - Integração com backend via APIs REST (protocolo HTTP)
 - Libs conhecidas (lodash, momentjs, etc)
 - Ferramentas de controle de versão (GIT)
 - Desenvolvimento otimizado para SEO
 - Single page APPs
 - Programação assíncrona (Promises, Generators, Streams)
 - Flexbox
 - Grid CSS

**Desejáveis:**
- NodeJS, Angular, Redux e/ou ES6

**Diferenciais:**
 - Metodologias ágeis de desenvolvimento (Scrum, Kanban)
 - JAVA
 - Noções de UX e Design de Interação

## Contratação

CLT

## Nossa empresa

A Ame é uma fintech criada para simplificar e revolucionar a maneira com que as pessoas se relacionam com o dinheiro!
Nascemos como uma conta digital, mas estamos crescendo para nos tornar uma plataforma financeira essencial nas vidas das pessoas.

Nossos números impressionam!
Com apenas 9 meses de operações, nosso app já tem mais de 1.8 milhão de downloads e é super bem avaliado nas lojas! Além disso, somos um dos meios de pagamento das lojas online Americanas.com, Submarino e Shoptime e aceitos em mais de 500 Lojas Americanas.

E é só o começo!

Nosso desafio é acelerar ainda mais - e, para isso, precisamos de um time com vontade de crescer e que esteja disposto a trabalhar em constante mudança.

Trabalhamos em squads, com times multifuncionais e multifacetados. 

Aqui todo mundo é o "dono do negócio".

## Como se candidatar

Para se candidatar só entrar [aqui](https://amedigital.gupy.io/jobs/57092) e terá os passos para se inscrever!

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo. 

E-mail para contato em caso de não haver resposta: recrutamento@amedigital.com

## Labels

- Alocado
- CLT
- Sênior

**Comment by brunohendias** [comment]
remoto?

**Comment by gdias1012** [comment]
> remoto?

não @brunohendias, é no nosso escritório mesmo
