### ISSUE TITLE
[Araçatuba] Front-End Developer no Grupo Acert

### ISSUE THREAD

**Issue by dougcavalheiro** [frontendbr/vagas#2186]
## Descrição da vaga

**Requisitos necessários:**
- JavaScript / ES6
- ReactJS / Redux (Sagas / Thunk)
- Webpack
- CSS
- APIs REST

**Hábito com as metodologias ágeis
Inglês técnico
Desejo de aprender**

**Será um diferencial já conhecer:** 
- Typescript
- Ferramentas de teste: Jest, Enzyme, React-Testing-Library, Cypress
- Material Design

## Contratação

PJ a combinar

## Como se candidatar

Envie seu CV para o e-mail: trabalhe.conosco@grupoacert.com.br com o assunto FRONT-END

## Labels

- PJ
- Remoto

**Comment by mgkaefer** [comment]
Sent!

**Comment by geniton** [comment]
Mandei!

**Comment by pedroffd** [comment]
Sent!!
