### ISSUE TITLE
[São Paulo] Front-End Developer na FIAP

### ISSUE THREAD

**Issue by Amandanickel2019** [frontendbr/vagas#2187]
## Quer desenvolver para uma empresa disruptiva e inovadora?

 

A FIAP é reconhecida por sua excelência educacional e pela qualidade da formação de seus alunos, que têm destaque no cenário empresarial. A soma de todas as suas qualificações a consagra como referência no ensino de graduação e MBA, nas áreas de tecnologia e gestão.

## Local

Escritório, São Paulo - Aclimação

## Benefícios

VR / VA / VT / Convênio Médio/ Convênio Odontológico e direito a 2 (duas) bolsas para estudar na melhor faculdade de tecnologia - FIAP. 

## O que pedimos:

·      Experiência em desenvolvimento de sites responsivos e versão mobile;
·      Animação em CSS3 e Javascript;
·      Desenvolvimento de sites com interações em Javascript;
·      Conhecimentos em Wordpress;
·      Conhecimentos em Sass e Git.

## Requisitos

**Obrigatórios:**
·      Javascript ES6+;
·      HTML5;
·      CSS3;
·      Sass;
·      Git;
·      SVG;

**Desejáveis:**
·      PHP;
·      Gulp;
·      Photoshop;
·      Greensock;
·      Node.JS;
·      Vue.JS;

**Qual será o seu desafio?**

·      Desenvolvimento de Sites;
·      Confecção de Banners HTML5 e E-mails Marketing;
·      Animação de SVGs em HTML5 e javascript;
·      Aplicação de conceitos de UX e UI;
·      Versionamento de conteúdos utilizando o Git.

## Contratação

CLT - A combinar

## Como se candidatar

Por favor envie um e-mail para: amanda.pereira@fiap.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor Front-End 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.

## Labels

- Alocado
- CLT
- Júnior
- Pleno
- Sênior

**Comment by jorginhodev** [comment]
CV enviado

**Comment by wallanpereira** [comment]
CV enviado

**Comment by agnezi** [comment]
Cv enviado

**Comment by GustavoPrizon** [comment]
Cv enviado
