### ISSUE TITLE
[Florianópolis] Desenvolvedor C++ / Sênior / CLT

### ISSUE THREAD

**Issue by RecrutamentoAudaces** [frontendbr/vagas#219]
## Descrição da vaga

A Audaces está com um projeto super inovador e precisamos de alguém que domine C++ moderno, computação gráfica e bibliotecas de renderização! 
Como Desenvolvedor C++ você irá usar tecnologias de computação gráfica de ponta para entregar aos estilistas a ferramenta mais fantástica que eles já viram: o **4Dalize**! 

O Audaces Idea 4D é uma ferramenta única desenhada com base em um _mix_ de _**digital sculping**_ e técnicas de simulações físicas. Sua principal função é acelerar o desenvolvimento de produtos da área da moda, reduzindo o investimento de tempo na prototipagem e melhorando a eficiência da comunicação da equipe (estilistas, modelistas...).

Esse produto é o resultado de anos de pesquisa e desenvolvimento com o apoio de universidades locais. Agora estamos focados em desenvolver ferramentas de desenho inovadoras e fáceis de usar, o que os estilistas irão amar!

Gostou? Dê uma olhada neste vídeo: [http://conteudo.audaces.com/4dalize](url)

## Local

Rodovia SC 401, km 1, nº 867, bairro Saco Grande, Florianópolis/SC, Brasil

## Benefícios

- Seguro de vida
- Plano de saúde sem coparticipação
- Convênio farmácia e odontológico
- Vale transporte
- Refeitório no local que serve café da manhã, almoço e café da tarde!
- Vista ímpar da ilha!
- Banco de horas
- Ginástica laboral
- Parceria com academias, instituições de ensino e escolas de idiomas

## Requisitos

**Obrigatórios:**

- Domínio teórico **e** prático de C++ moderno, computação gráfica e OpenGl (ou outra biblioteca de renderização)
- Facilidade para escrever códigos
- Facilidade com matemática :)
- Paixão por programar! 

**Desejáveis:**
- Git
- CMake
- Refactoring de código e testes de código
- Build contínuo
- Design Patterns, 
- Arquitetura de software (DI, IoC, MVP, MVC, Plugins, Presentation Model)
- Agile Principles (SRP, KISS, OCP, DRY, LSP), inglês.

**Diferenciais:**

- Poder trabalhar em um projeto único, inovador e desafiador
- Possibilidade de _fazer a diferença_
- Trabalhar em time
- Abertura para trazer novas ideias, ferramentas, etc.
- Possibilidade de trabalhar em uma empresa que é líder do seu segmento na América Latina e está presente em mais de 70 países!

## Contratação

CLT, faixa salarial entre R$4000,00 e R$5000,00

## Nossa empresa

A **Audaces** é referência mundial em inovação tecnológica para a moda. Nossos produtos são sinônimo de precisão, velocidade e economia. São produtos de sucesso e somos focados na satisfação de nossos clientes e na realização de ideias com engajamento, design e resultado. Isso tudo só é possível com a paixão e comprometimento de nossos colaboradores! Venha fazer parte deste time de sucesso!

## Como se candidatar

Envie seu currículo para recrutamento@audaces.com, com o assunto: Desenvolvedor C++

**Comment by LFeh** [comment]
O nosso repositório é para DESENVOLVEDORES FRONT-END.

O minimo que esperamos de um profissional, é ler a descrição antes de sair postando.

**Comment by RecrutamentoAudaces** [comment]
ok, pedimos desculpas...

**Comment by eduardojmatos** [comment]
Sem crise! Sugiro que você faça um fork do projeto para esse nicho de desenvolvimento, o que acha?
