### ISSUE TITLE
[Barueri]  React developer

### ISSUE THREAD

**Issue by SPMRB** [frontendbr/vagas#2190]
## Descrição da vaga

Ter experiência nas seguintes tecnologias:
React Native
GraphQL
Java
Node
Spring

Diferencial ser oriundo do segmento de operadora de saúde.

## Local

Ficará alocado em um dos nossos clientes em Alphaville/ Barueri 

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ 25,00/dia
- Auxílio creche

## Requisitos

**Obrigatórios:**
React Native
GraphQL

**Desejáveis:**
Java
Node
Spring

**Diferenciais:**
Diferencial ser oriundo do segmento de operadora de saúde.

## Contratação
CLT

## Como se candidatar

Por favor envie um e-mail para vagas@informaker.com.br  com seu CV anexado e pretensão salarial CLT - enviar no assunto: Vaga REACT

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: vagas@informaker.com.br

## Labels

- CLT

**Comment by felipefialho** [comment]
@SPMRB Favor deixar titulo conforme os padrões do repositório, obrigado
