### ISSUE TITLE
[São Paulo - Remoto] Front-End Developer na [App7Sistemas]

### ISSUE THREAD

**Issue by brunofgabriel** [frontendbr/vagas#2191]
## Descrição da vaga
A App7 Sistemas esta contratando desenvolvedores front-end e full stack para trabalhar Home Office no desenvolvimento e manutenção de sistemas web, usando HTML5, Bootstrap e Angular.

## Local
Remoto (Home office)

## Requisitos:
Necessário conhecimento em desenvolvimento front-end com HTML5, Javascript, CSS, Bootstrap, Jquery e Angular
Desejavel conhecimento em Transact-SQL (Microsoft SQL Server)
Desejavel conhecimento em API's RestFull para integração de sistemas
Desejavel conhecimento na linguagem Microsoft .Net C#

## Candidato:
Comprometimento e responsabilidade com seus deveres e prazos
Desejo de crescer junto com a empresa, sempre se atualizando e aprendendo novas tecnologias
Não é necessário ter ensino superior ou estar cursando cursos de T.I., apenas ter o conhecimento que procuramos
Pro atividade para sugerir e pesquisar melhorias em nossos sistemas

## Contratação
A vaga é para trabalhar Home Office em qualquer lugar do Brasil. Inicialmente por um período de experiencia de 3 meses (remunerados). Após isso, forma de contratação a combinar.

## Como se candidatar
Por favor envie um email para bruno@app7sistemas.com com seu CV anexado - enviar no assunto: Vaga Fron End

## Labels
- Home Office
- Front End
- AngularJS

**Comment by ribas14** [comment]
React ou Vue serve não?

**Comment by pedrincandido** [comment]
Futuramente vai ter possibilidade de angular2+?

**Comment by brunofgabriel** [comment]
> React ou Vue serve não?

Bom Dia, nosso sistema foi desenvolvido em Angular, no momento não pensamos em substitui-lo.

Att,

**Comment by brunofgabriel** [comment]
> Futuramente vai ter possibilidade de angular2+?

Se houver necessidade e for vantajoso, sim.

**Comment by danielswater** [comment]
Enviado

**Comment by isadaora** [comment]
unsubscribe


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by brunofgabriel** [comment]
Senhores, agradeço a todos que nos enviaram seu currículo. Estamos finalizando o processo de seleção.

Abraços e boa sorte.
