### ISSUE TITLE
[Lisboa] Front-End Developer na Aubay

### ISSUE THREAD

**Issue by ritasrosa** [frontendbr/vagas#2193]
Projetos em vários setores de atividade, usando diversas tecnologias de Frontend tais como React ou Angular, sempre internacionais!

Local
Portugal: Lisboa

Benefícios
• Plano de saúde
• Visto de Trabalho para Portugal
• Outras

Diferenciais
• Formações técnicas, comportamentais e de idiomas
• Prémios de referências de recrutamento
• Eventos Team Building
• Convívio mensal
• Oferta de aniversário

Requisitos
Obrigatórios:
• Experiência profissional na área web
• Bons conhecimentos de Javascript, HTML, CSS
• Experiência em Angular ou React.
• Fluência na língua Inglesa
•Mais de 3 anos de experiência 

Diferenciais:
• Experiência internacional

Contratação
Apoio em todo o processo para obtenção de visto de trabalho para Portugal.

Nossa empresa
A Aubay, é uma empresa de origem francesa presente em diversos países na Europa.
Como cerca de 7000 pessoas desenvolvemos projetos nas mais diversas tecnologias.
Neste momento, temos várias vagas em aberto para várias posições.

Como se candidatar
Por favor envie um email para rrosa@aubay.com com seu CV em Inglês anexado e o assunto Front-End.

**Comment by viniarruda** [comment]
Boa tarde. O nível requerido de inglês é avançado?
