### ISSUE TITLE
[Los Angeles/Remote] Senior React developer na AvantStay.com

### ISSUE THREAD

**Issue by wellguimaraes** [frontendbr/vagas#2194]
## Descrição da vaga

Currently, we have a position available for a senior front-end engineer. As a growing, late-stage startup, we look for self-starters who thrive in a fast-paced, agile environment which means wearing many hats, being able to change direction quickly, and showing an eagerness to learn new technologies as the need arises. In this role, you'll work with a small, collaborative team of engineers, product managers, and designers so excellent interpersonal and communication skills are also a must. Most importantly, we look for people who can prioritize, multi-task, and deliver because it’s a lot more fun to get things done.

## Local

A empresa fica em Los Angeles, mas a vaga é para trabalho remoto. Já temos outros brasileiros no time.

## Remuneração

- Pagamento a cada duas semanas
- Salário de $90k a $120k (anual, USD)

## Requisitos

- Proficiency with HTML5, CSS3 and JavaScript
- Experience with React and Node in high-volume, production systems
- Experience with Webpack
- Experience with SSR, Redux or Mobx
- Continual learning of emerging technologies/industry trends
- Excellent communication skills and experience in collaborative environments
- Experience building mobile applications that utilize web-services (either HTTP based, XML-RPC, JSON or other services) and experience with Agile software development is a plus

**Big bonus:**
- **A keen eye for UI/UX details**
- Open source projects

## Contratação

PJ

## Nossa empresa

Collectively, we’ve traveled to over 80 countries and know what matters most - creating an authentic experience. We believe the best travel accommodations are all about delivering an exceptional, unique stay and far too often property managers and hosts fall short on delivering a first-class short-term rental experience. AvantStay is here to change that by setting the new standard for short-term rental experiences.

Our team is incredibly passionate about real estate, technology and the arts. We came together to build a revolutionary hospitality brand through the power of virtual tech automation in the short-term rental market. With offices in San Francisco and Los Angeles, we currently operate in 7 markets across the United States. Our proprietary tech algorithm and data experts identify partnership opportunities and automate operations through our virtual management system to maximize efficiencies and improve the overall guest experience.

## Como se candidatar

Por favor envie um email para wguimaraes@avantstay.com com seu CV anexado

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 30 dias após cada processo.

## Labels

- React
- Remoto
- PJ
- Sênior

**Comment by fabriciofrontarolli** [comment]
Valeu por compartilhar a vaga!
Me candidatei :)

**Comment by eduardocorreas** [comment]
Obrigado por compartilhar !!
