### ISSUE TITLE
[São Paulo] Pessoa Dev. Front End na Promo de Bolso

### ISSUE THREAD

**Issue by evertoncastro** [frontendbr/vagas#2199]
Procuramos pessoas desenvolvedoras Front End que amam e sejam realmente bons no que fazem, encontrando soluções para os mais variados problemas técnicos.
----

**Sobre a vaga:**

- Presencial
- Cidade - São Paulo
- Nível - Júnior/Pleno
- Faixa salarial entre R$ 3.000 e R$ 6.000 (PJ)

**Quais skills esperamos de você:**

- Além do planejamento em equipe, auto-gestão das próprias atividades, saber lidar com dificuldades técnicas e identificar oportunidades de melhoria
- Automatização de processos evitando executar tarefas repetidas de forma manual
- Seguir boas práticas das linguagens e ferramentas utilizadas
- Pró atividade e interesse em entender e aprender as regras de negócio para propor soluções e agregar valor aos projetos e produtos
- Inglês intermediário/avançado para entender e criar documentações e se comunicar
- Experiência mínima de 1 ano com desenvolvimento WEB

**Conhecimentos técnicos:**
- Experiência com integração de aplicações WEB e APIs
- Conhecimento da linguagem Javascript
- Conhecer pelo menos uma das bibliotecas Angular, React, Vue.Js ou JQuery
- Conhecimento de Bootstrap ou Materialize
- Integrações entre front-end e back-end: formulários e validações; requisições HTTP e roteamento de páginas; consumo de APIs
- Otimização de performance de aplicações Web (Minificação e Otimização de Imagens, etc.)
- Ferramentas para automatização de tarefas
- SEO, Google Tag Manager e Google Analytics

**Responsabilidades:**

- Criar, acompanhar e manter aplicações web
- Defender as boas práticas de desenvolvimento.
- Participar das decisões de tecnologia
- Soluções para garantir a melhor experiência para o usuário

**O que os as pessoas + gostam na Promo:**
- O clima, o aprendizado de diversas tecnologias e o desafio diário
- Reconhecimento financeiro a cada projeto/etapa
- Transparência em processos e decisões da empresa

É pertinho do metrô Fradique, em um espaço muito legal!

**Contato:**
Email: rh@promodebolso.com.br
Site: https://promodebolso.site
Telefone: 11 3455-7547

**Labels**
Presencial
Perfil Júnior/Pleno
PJ
Front End
Javascript
São Paulo

**Comment by azabraao** [comment]
Ainda estão buscando um dev?

**Comment by evertoncastro** [comment]
> Ainda estão buscando um dev?
Sim azabraao, envie um CV para rh@promodebolso.com.br. Obrigado pelo interesse.

**Comment by azabraao** [comment]
Enviei ontem! haha. Aguardando ansiosamente :D
