### ISSUE TITLE
[São Paulo] Front-end Freelancer

### ISSUE THREAD

**Issue by MayogaX** [frontendbr/vagas#22]
## Descrição da vaga

Precisamos de um freelancer para terminar um projeto feito com angular-js e que usa um template. O site irá se comunicar com uma api que está sendo feita em paralelo.

## Local

Remoto - Com algumas reuniões em São Paulo, na Faria Lima

## Benefícios

-Será somente a remuneração, a combinar 

## Requisitos

**Obrigatórios:**
-Experiência com angular js
-saber fazer código limpo
-saber mexer com Saas

**Desejáveis:**
- Saber mexer com a api do Here Maps
- Saber mexer com git

**Diferenciais:**
- projetos no github 

## Contratação

PJ a combinar

## Nossa empresa

A FieldCorp reúne os melhores engenheiros de software e produção, matemáticos e administradores de empresas para criar soluções de ponta capazes de proporcionar à sua empresa níveis de produtividade e visibilidade operacional sem paralelo no mercado.

## Como se candidatar

Por favor, enviar um e-mail a priscila.sato@fieldcorp.com.br com cv/github/portifólio com o assunto "Front-end"

**Comment by MayogaX** [comment]
Já achamos, obrigada a todos

**Comment by LFeh** [comment]
\o, rápido.

**Comment by renatogalvones** [comment]
Caramba! Negócio tá ficando ágil aqui!

**Comment by camilatigre** [comment]
@MayogaX 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by MayogaX** [comment]
@camilatigre 

Não. Infelizmente
