### ISSUE TITLE
[São Paulo] Front-End Developer na Fanatee

### ISSUE THREAD

**Issue by laizeamon** [frontendbr/vagas#2200]
**Sobre a vaga**
O time de desenvolvimento da Fanatee é responsável por planejar, escrever e manter o código de programação dos nossos jogos. Como membro desta equipe você vai trabalhar com programadores experientes, além de interagir com times de produto, design e BI.
 
**Como Software Engineer, estas serão suas principais atividades:**
Trabalhar na programação dos jogos, seja no desenvolvimento de protótipos, em novos jogos ou na manutenção dos jogos existentes;
Atuar na otimização e na solução de bugs nos jogos e sistemas relacionados;
Pesquisar soluções para problemas e desafios técnicos;
Interagir com os times de produto em reuniões de briefing e acompanhamento.
 
**Requisitos**
Possuir base sólida em engenharia de software;
Domínio pleno em duas ou mais linguagens de programação;
Experiência prévia em desenvolvimento de aplicativos mobile ou sistemas de backend;
Ser pró-ativo para buscar soluções e ter muita vontade de se desenvolver profissionalmente;
Ser apaixonado por jogos.
 

**Não são requisitos, mas serão considerados diferenciais:**
Experiência com Unity 3D;
Experiência com Swift ou Java/Android;
Experiência em desenvolvimento de jogos ou interfaces interativas.
 
**O que oferecemos**  
Remuneração competitiva.
VR + VT.
Assistência Médica e Odontológica.
Ambiente (e Dress Code) descontraído.
Uma sala para necessários momentos de descanso, cheia de snacks, frutas e bebidas
 

**Sobre a Fanatee**
Somos uma startup fundada em 2013 e, desde então, nos dedicamos para que as pessoas possam jogar games a qualquer hora e em qualquer lugar. Somos perfeccionistas, guiados por dados e nosso talento consiste em transformar ideias em business: não à toa temos títulos de sucesso em nossa história, incluindo os aplicativos Stop e CodyCross, que juntos contam com mais de 35 milhões de downloads feitos ao redor do mundo. 

O mundo digital nos permitiu realizar nosso sonho: passar o dia todo em volta de pessoas talentosas, criando produtos que levam diversão e conteúdo à muitas pessoas ao redor do mundo!

Se identificou com a nossa cultura e objetivo? Então se candidate e venha fazer parte do time Fanatee!

**Link para candidatura:** https://fanatee.com/#op-232606-senior-software-engineer

**Comment by ediposantos** [comment]
Alguma oportunidade para Q.A sênior?

**Comment by laizeamon** [comment]
> Alguma oportunidade para Q.A sênior?

Olá, não, apenas uma vaga de estágio para QA. 
https://fanatee.com/#op-282693-estagirio-quality-assurance-qa

Abs,

**Comment by mrangel-jr** [comment]
Aceita remoto ?

**Comment by laizeamon** [comment]
> Aceita remoto ?

Somente presencial. Vaga para São Paulo.
