### ISSUE TITLE
[Curitiba] Front End Developer na HeroSpark

### ISSUE THREAD

**Issue by jeanmalves** [frontendbr/vagas#2205]
## Descrição da vaga

Estamos buscando por um Desenvolvedor Front End Pleno para integrar nosso time. Temos projetos desenvolvidos e em andamento com as tecnologias Angular e VueJS.
Como desenvolvedor, irá atuar em novas features, além de realizar manutenções corretivas em nosso code base.

## Local

Remoto ou Escritório, Curitiba - Centro

## Benefícios

- Vale transporte;
- Vale refeição;
- Treinamentos e workshops (internos e externos);
- Seguro de vida;
- Parcerias com estabelecimentos da região;
- Computador;
- Assistência médica;

## Requisitos

**Obrigatórios:**
- Boa comunicação
- Espírito de equipe
- Ampla experiência como front-end (Prototipação de layout, flex layout, CSS, SASS, Bootstrap ou Material Design)
- Amplo conhecimento em Javascript
- Experiência no desenvolvimento de aplicações SPA em VueJS ou Angular
- Experiência no consumo de web APIs
- Ampla experiência com GIT
- Experiência com testes Jest ou Jasmine

**Desejáveis:**
- Conhecimentos em Vuex
- Experiẽncia com AWS S3
- Inglês avançado/fluente
- Noções de design

**Diferenciais:**
- projetos opensource

## Contratação

CLT a combinar

## Nossa empresa

Somos uma plataforma de empreendedorismo digital que já impactou mais de 6 milhões de alunos e gerou 90 milhões de reais em vendas aos nossos empreendedores heróis.

Nosso time é ágil e focado em entregar a melhor experiência para quem importa: nossos clientes e seus alunos. Usamos Scrum e Kanban na nuvem.

Desenvolvemos especialmente em Ruby on Rails, mas temos sistemas e componentes em Elixir, Node.Js, no front usamos Angular e Vue.Js, no App utilizamos Kotlin e Swift.

Utilizamos fortemente infraestruturas como Amazon, Heroku e Google Cloud, Sendgrid para email, Kubernets/Docker em infra, além de MongoDB, Postgresql e Redis.  No desenvolvimento, utilizamos Github, GitLab, TrackJS e Pingdom/AppSignal para análises e Circle CI para integração contínua - realizamos vários deploys diariamente!

## Como se candidatar

Por favor acesse o [link da oportunidade](https://herospark.abler.com.br/vagas/desenvolvedor-front-end-pl-81366)  e clique em "candidatar-se".

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.

## Labels

- Alocado
- Remoto
- CLT
- Pleno
- Paraná

**Comment by brunohendias** [comment]
fiz o processo de cadastro porém não me permite candidatar a vaga pela minha localidade, mas a vaga está marcada como remoto.. teria um e-mail ou algo para enviar as informações?

**Comment by jeanmalves** [comment]
@brunohendias vou verificar e já comento aqui. Obrigado pelo interesse.

**Comment by jeanmalves** [comment]
@brunohendias veja se consegue se candidatar, é pra conseguir agora.

**Comment by brunohendias** [comment]
deu certo, candidatado

**Comment by GabrielOliveira321** [comment]
[CV Gabriel - Google - 10112022 (2) (4).pdf](https://github.com/frontendbr/vagas/files/12653196/CV.Gabriel.-.Google.-.10112022.2.4.pdf)
