### ISSUE TITLE
[Itapema - SC] Desenvolvedor FrontEnd na DWV

### ISSUE THREAD

**Issue by megandavulpi** [frontendbr/vagas#2213]
### Sobre a empresa: DWV

Somos uma plataforma que reúne os imóveis dos principais consultores do litoral caterinense e fazemos isso de maneira gratuíta. Buscamos por crescimento contínuo e valorizamos muito o time que somos hoje. 

Você curte trabalhar em equipe e ama solucionar problemas de forma rápida? Então vem fazer parte da DWV!

### Descrição: Principal função:

Desenvolver e dar manutenção as funcionalidades da nossa plataforma.

### Requisitos necessários:

Experiência com Javascript,
Angular,
Typescript,
Html
CSS

### Seria legal se:

Experiência com Ionic,
React,
Node

### Candidatar: http://bit.ly/dwv_front

**Comment by danielswater** [comment]
Remoto?

**Comment by rodrigopluz** [comment]
A vaga já foi preenchida ?
