### ISSUE TITLE
[Rio de Janeiro ou Remoto] Front-End Developer ReactJS no Proenem

### ISSUE THREAD

**Issue by wrettich** [frontendbr/vagas#2217]
## Descrição da vaga

ProEnem é uma das startups de ensino à distância que mais cresce no Brasil e está contratando desenvolvedores para atuar em projetos baseados em React JS/Native e Node.

## Local

Remoto ou Escritório, Rio de Janeiro - Centro Metropolitano

## Benefícios

- Salário e benefícios compatíveis com o mercado
- Possibilidade de afetar positivamente a vida de milhares de usuários.
- Espaço e autonomia pra você deixar a sua marca.
- Ambiente descontraído e um time incrível formado por pessoas apaixonadas pelo que fazem e referências em suas áreas de atuação.

#### Diferenciais
- ambiente super descontraído
- frigobar sempre cheio :P
- sala de jogos

## Responsabilidades
- Construção de web aplicações ricas usando ReactJS
- Desenvolvimento Front-end
- Desenvolver testes unitários e corrigir bugs
- Somos um time ágil com contato direto com cliente. Fazemos reuniões de planning, daily, review e retro.

## Requisitos

**Obrigatórios:**
- Proficiência em HTML5/CSS3/JavaScript
- Proficiência em Git
- Experiência com ReactJS (1 ou mais anos para Senior)
- Experiência com SEO
- Conhecimento de Pre-processadores de CSS e Framework server-side
- Styled Components
- Experiência com Typescript
- Redux

**Diferenciais:**
- Domínio de melhores práticas de desenvolvimento
- Familiaridade com testes
- CI/CD

## Contratação

PJ a combinar

## Nossa empresa

Nós somos cerca de 100 colaboradores e nosso escritório fica no Centro Metropolitano, próximo ao Shopping Metropolitano (Rua Abelardo Bueno), com uma infra-estrutura super moderna!
Referências: www.proenem.com.br e https://www.youtube.com/user/ProENEMOficial

## Como se candidatar

Envie seu currículo para vagas@proenem.com.br

## Labels
- Alocado
- PJ
- Pleno
- Remoto
- Sênior

**Comment by lucianaribeiro** [comment]
@wrettich há vagas para pessoas que estão perto de formar mas que atende aos requisitos?
