### ISSUE TITLE
[São Paulo] Assistente UX / Front-End Junior

### ISSUE THREAD

**Issue by leandrodasler** [frontendbr/vagas#222]
## Descrição da vaga

A Forma aumentou o tamanho da sua equipe de desenvolvimento! E agora precisamos de alguém que manje de HTML/CSS pra dar aquela força!

Você pode nos ajudar a fazer a #melhorviagemdavida dos nossos passageiros. Se você está pronto para esse desafio, quer trabalhar sobre uma metodologia dinâmica e fazer coisas legais veja o que precisamos:

## Local

APENAS Alocado , São Paulo - Moema

## Requisitos

**Obrigatórios:**
- Noções de HTML e JS - Precisa saber como funciona.
- Curtir prototipar telas e compreender UX

**Desejáveis:**
- Conhecer alguma ferramenta de Prototipagem

## Contratação

CLT Full + VR + VT + Plano de Saúde e Odontológico

## Nossa empresa

A maior operadora de Turismo estudantil do Brasil! Hoje, temos 17 lojas da Forma, em 9 estados do Brasil e mais de 40.000 alunos viajam com a gente todos os anos. E esses números continuam crescendo, crescendo a cada ano e fazendo a gente acreditar cada vez mais que realmente a gente nasceu pra isso.

## Como se candidatar

Por favor envie um email para leandro@formaturismo.com.br com seu CV anexado - enviar no assunto: Vaga UX

**Comment by LFeh** [comment]
Bacana!

**Comment by leandrodasler** [comment]
Fala Felipe, beleza?

sou gerente de TI aqui da empresa. Conheci o repositório através de
indicação de amigos.

parabéns pela iniciativa.

Abs!

2017-01-17 11:20 GMT-02:00 Felipe Fialho <notifications@github.com>:

**Comment by Marcelosilva10** [comment]
gostei muito

**Comment by alexislds** [comment]
Opa, enviado.

**Comment by leandrodasler** [comment]
Pessoal, vaga preenchida. 

Recebi excelentes contatos. ainda estou com outra vaga em aberto, porém para desenvolvimento em AngularJs: https://github.com/frontendbr/vagas/issues/217

Obrigado.

**Comment by LFeh** [comment]
Tamo junto!

Foi com alguem daqui?

**Comment by Lftho** [comment]
Terá abertura dessa vaga ainda para 2019 ?

**Comment by Lftho** [comment]
>           sim!
Quando abrir poderia me passar as informações sobre a vaga ou melhor me mandar por email - lft.thomaz@gmail.com - Obrigado pela ajuda !
