### ISSUE TITLE
[São Paulo] Front-End Developer na FERRERI

### ISSUE THREAD

**Issue by phillfer** [frontendbr/vagas#2226]
## Descrição da vaga

A Ferreri está em busca de desenvolvedores front-end apaixonados por programação, curiosos que busquem novas tecnologias, gostem de experimentar, testar e que tenham potencial de evolução técnica aliado ao conjunto de experiências que possuem, sejam elas profissionais e/ou experimentais.

## Local

A maioria da equipe está em São Paulo (próximo a Av Paulista), mas toda equipe está espalhada pelo Brasil. Todos trabalhamos remoto.

## Benefícios

- Trabalho remoto
- Horário de trabalho flexível
- Compensação e pacote de benefícios em linha com o padrão de mercado para esta posição
- Trabalhar com tecnologia de ponta

## Requisitos

Buscamos pessoas que tenham experiência com versionamento de código, integração contínua, testes integrados, e que saibam resolver problemas. Que sejam organizadas, saibam gerenciar seu tempo, perguntem, interajam e se comuniquem. É imprescíndivel que compreendam e se envolvam no processo de desenvolvimento web (design, desenvolvimento e implantação).
Buscamos alguém que:
- Tenha familiaridade com código, preferencialmente, mas não exclusivamente (com um ou mais):  JavaScript, Objective-C, Swift, Java.
- Tenha experiência com HTML, CSS.
- Saiba usar os padrões atuais para compatibilidade entre plataformas e navegadores.
- Tenha capacidade de usar os arquivos do adobe creative suite e sketch e dar vida a eles como uma experiência unificada e funcional em plataformas da web e móveis.
- Tenha conhecimento especializado das melhores práticas de experiência do usuário e capacidade de implementar soluções com base em necessidades exclusivas de usuários específicos.
- Trabalhe em colaboração com equipes internas de desenvolvimento e design para garantir a integração perfeita com tecnologia de back-end e uma excelente experiência do usuário.
- Tenha atenção aos detalhes e capacidade de priorizar demandas concorrentes.
- Desenvoltura, boa comunicação e disposição para buscar informações e sanar dúvidas.
- Tenha como valores: independência, ownership e auto gerenciamento.

## Contratação

PJ (a combinar)

## Nossa empresa

A Ferreri é uma empresa há 4 anos no mercado. Especializada em desenvolvimento web e mobile. https://ferreri.co/

## Como se candidatar

Nosso processo de recrutamento conta com 2 etapas: entrevista pessoal e teste prático. Para iniciar o processo pedimos um teste que não deve tomar muito do teu tempo e nos dará uma perspectiva da tua forma de trabalhar. Queremos entender teu nível de habilidade em todas as áreas envolvidas na construção de um projeto: front e back. Você não precisa entregar ambos, mas qualquer adicional às suas habilidades específicas é interessante. Por favor, leia com atenção o desafio a seguir:

Este https://medium.freecodecamp.org/every-time-you-build-a-to-do-list-app-a-puppy-dies-505b54637a5d traz vários exemplos de pequenos apps interessantes.

Escolha um app dessa lista e implemente, colocando o código em alguma plataforma de versionamento.

Sinta-se confortável para focar nas áreas que você tem mais habilidade (e desenvolver na linguagem que preferir). Analisaremos teu código, estrutura de projeto, envios dos commits e projeto rodando em produção.

Sobre a entrega:

Antes de iniciar o projeto, nos envie um email para contato@ferreri.co com a descrição no assunto "Vaga Front-End" falando que tem interesse na vaga e que irá iniciar um desses projetos e, caso possua algum CV, envie anexo. Envie também pretensão salarial, caso tenha alguma em mente.
Teu código deve estar disponível em um repositório git;
Você pode utilizar plataformas como Heroku ou Google Cloud Plataform (ou qualquer outra que preferir) para nos mostrar a aplicação funcionando em produção;
Quando estiver pronto envie o link do repositório e do projeto em produção respondendo o próprio email que enviou para contato@ferreri.co.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: phillipe@ferreri.co

## Labels

- PJ
- Pleno
- Sênior
- Remoto

**Comment by flaugabriel** [comment]
Enviado!

**Comment by thalisonwilker** [comment]
eu tenho um projeto bem similar a um dos exemplos sugeridos, o Project #28. No meu caso eu fiz algo parecedo com trello. Preciso criar um dos exemplos sugeridos, obrigatoriamente?

**Comment by phillfer** [comment]
@thalisonwilker Pode nos enviar esse projeto citado para contato@ferreri.co

**Comment by phillfer** [comment]
@felipefialho Poderia atualizar as labels por favor?

**Comment by jass2125** [comment]
@phillfer já encerrou o processo?

**Comment by phillfer** [comment]
@jass2125 Ainda está aberto.

**Comment by walteralleyz** [comment]
Aceita freelancer ou só PJ?

**Comment by souzasmatheus** [comment]
@phillfer Olá! O processo ainda está aberto?

**Comment by phillfer** [comment]
VAGAS PREENCHIDAS!
Em breve surgirão mais vagas e então voltaremos a anunciar por aqui.

(Agradeço a esse grupo. Tem sido o melhor canal de anúncio de vagas de tecnologia).
