### ISSUE TITLE
[São Paulo] Front-End Developer na idwall

### ISSUE THREAD

**Issue by obst900** [frontendbr/vagas#2240]
## Descrição da vaga

Sr./Pl./Jr. Frontend Developer @ idwall (React)

Buscamos Desenvolvedoras(es) Frontend apaixonados por tecnologia, inovação e desenvolvimento frontend. Alguém que compreenda nossas soluções e seja capaz de desenvolver e evoluir nossos produtos, ferramentas e dashboards. 

Vai descendo que tem mais info 👇

## Local

Escritório, São Paulo - Região da Paulista, ao lado do metrô consolação

## Benefícios

- Plano de saúde
- Plano odontológico
- Seguro de vida
- VR de R$ 32/dia
- VA de R$ 300/mês
- Auxílio creche

#### Diferenciais

- Horário flexível
- Monte a sua máquina como desejar
- Área de descompressão, massagem e frutas
- Plano de desenvolvimento individual
- Remuneração competitiva

## Requisitos

**Obrigatórios:**

- Total domínio dos conceitos de HTML e CSS
- Mais de 2 anos de experiência com desenvolvimento de produtos digitais utilizando frameworks JS, preferencialmente: **React** 
- Mentalidade de qualidade, segurança, desempenho, escalabilidade e seus impactos nos releases
- Experiência com testes automatizados - unitários, integrados, funcionais
- Domínio de ferramentas de versionamento - Git
- Conhecimentos sobre integração com APIs REST em JSON

**Desejáveis:**
- Familiaridade com ferramentas de protótipos de aplicações web
- Conhecimentos sobre integração com APIs RESTful em JSON
- Conhecimento em bancos de dados relacionais ou NoSQL
- Conhecimento sobre Docker e Kubernetes
- Conhecimento de ambientes em nuvem: AWS ou Google Cloud
- Conhecimento dos conceitos de CI/CD
- Vivência de desenvolvimento utilizando metodologias ágeis - Kanban, Scrum
- Possuir Cultura DevOps

## Contratação
CLT

## Nossa empresa

A **idwall** é uma empresa de tecnologia que ajuda outras empresas a evitarem fraudes de identidade em suas plataformas. 

Como a gente faz isso? **Tecnologia**. 

`Tecnologia é nosso produto final`

Respiramos e vivemos tecnologia para garantir que nossos clientes evitem riscos para seus negócios. 

**Great Place to Work**
Somos uma das melhoras empresas para se trabalhar no BRASIL!
Estamos no ranking mais recente da GPTW na categoria PME.

**Nossos clientes**  
99, ifood, Yellow, Banco Neon, Banco Original, Zazcar, Movida ... entre outros.

**Nossa Cultura**

Trabalhamos em um ambiente onde as oportunidades de inovar e os desafios são constantes. Aqui somos instigados a dar o nosso melhor, colaborando nas discussões e propondo ideais que vão nos levar a um futuro com menos fraudes e mais tecnologia.

Autoliderança e a vontade de conhecer e aprender são elementos fundamentais que compõem a nossa cultura.

Na **idwall**, nós não apenas aceitamos a diferença, mas também a celebramos e valorizamos as visões diferentes de nossos funcionários, a fim de beneficiar nossos produtos e a comunidade. 

Nos orgulhamos em ser uma empresa que oferece um ambiente de oportunidades iguais, independente de gênero, orientação sexual, cor, religião, deficiência e qualquer tipo de status.

## Como se candidatar

É fácil. Só se candidatar por esse link: https://idwall.gupy.io/jobs/29665

## Labels
- Alocado
- Júnior
- Pleno
- Sênior
- CLT

**Comment by phnsousa** [comment]
Olá, gostaria de saber se a experiência é exigida no caso de ser desenvolvedor Júnior? Obrigado ;)

**Comment by obst900** [comment]
@phnsousa A experiência de 2 anos é exigida para os perfis Pl. e Sr.
Para perfis Jr. é desejável pelo menos 1 ano de experiência prática com produtos digitais.
