### ISSUE TITLE
[São Paulo] Programa Jovens Talentos 2019 [Grupo Votorantim]

### ISSUE THREAD

**Issue by camilaintera** [frontendbr/vagas#2245]
# Descrição da vaga
O programa Jovens Talentos do grupo Votorantim fará a seleção de 6 candidatos para vivenciar a incrível experiência de trabalhar em projetos tecnológicos super desafiadores com o objetivo de levar a transformação digital às organizações. Os participantes terão um excelente programa de mentoria e de desenvolvimento de habilidades, assim como a chance de se conectarem com a rede de talento de todas as empresas que fazem parte do grupo!

A Votorantim está em busca de jovens apaixonados por tecnologia e que querem muito fazer a diferença a partir da transformação digital.

## Local

São Paulo, com a possibilidade de importar talentos de qualquer outro lugar do Brasil

## Benefícios

- Remuneração: R$6.000,00 (CLT)
- Assistência médica Bradesco Saúde
- Seguro de vida
- Previdência privada
- Reembolso creche (mulheres)
- Assistência odontológica (livre adesão)
- Bônus atrelados ao atingimento de objetivos
- Vale transporte
- Vale refeição
- GymPass

## Requisitos

**Obrigatórios:**
- Graduação COMPLETA entre os anos de 2016 a 2018;
- Disponibilidade para trabalhar em São Paulo a partir de outubro de 2019;
- Domínio de inglês como diferencial

## Como se candidatar

Segue link para inscrição e maiores informações: http://bit.ly/2yjQzD8

Caso haja interesse em participar dessa oportunidade, estou à disposição através do endereço de e-mail camila.tanure@byintera.com para maiores informações ou para conversarmos melhor sobre essa proposta.

## Labels

- CLT
- Júnior
- Pleno

**Comment by pedroch4610** [comment]
Ola! Graduação em Licenciatura em Computação serve para a vaga?

**Comment by MaikonTT** [comment]
Encerrou...
