### ISSUE TITLE
[São Paulo | Remoto] Desenvolvimento Front-End no SciELO

### ISSUE THREAD

**Issue by gustavofonseca** [frontendbr/vagas#2246]
## Descrição da vaga
O projeto SciELO está procurando pessoas que queiram integrar o time de desenvolvimento, contribuindo com experiências técnicas e pessoais.

Você trabalhará desenvolvendo produtos Open-Source para suportar o fluxo de publicação científica dos principais periódicos acadêmicos em acesso aberto do Brasil e de mais 15 países.

Há vagas para trabalhar em 2 projetos:

* **Markup:** Uma ferramenta para a identificação de estruturas e metadados de um artigo científico, a fim de produzir uma representação do mesmo em XML.
* **Texture:** Um editor de textos orientado para a redação e processos editoriais de artigos científicos. O Texture é desenvolvido por um consórcio internacional composto por instituições de renome na área da publicação científica em Acesso Aberto.

## Local
Remoto ou escritório, São Paulo - Vila Clementino

## Requisitos

- Curso superior em Ciência da Computação ou similar;
- Atitude positiva;
- Goste de trabalhar em equipe;
- Goste de compartilhar conhecimento;
- Entenda a importância das práticas de engenharia de software (controle de versão, testes automatizados, revisão de código, programação em pares, design, arquitetura etc);
- Inglês avançado;
- Tenha experiência em linguagens de programação.

## Contratação

A modalidade de contratação será discutida e acordada entre as partes.

## Nossa empresa

Scientific Electronic Library Online - SciELO é uma biblioteca eletrônica que abrange uma coleção selecionada de periódicos científicos brasileiros.

O SciELO é o resultado de um projeto de pesquisa da FAPESP - Fundação de Amparo à Pesquisa do Estado de São Paulo, em parceria com a BIREME - Centro Latino-Americano e do Caribe de Informação em Ciências da Saúde. A partir de 2002, o Projeto conta com o apoio do CNPq - Conselho Nacional de Desenvolvimento Científico e Tecnológico.

O Projeto tem por objetivo o desenvolvimento de uma metodologia comum para a preparação, armazenamento, disseminação e avaliação da produção científica em formato eletrônico.

Para saber mais sobre o projeto SciELO sugiro a leitura dos capítulos iniciais do livro "SciELO - 15 Anos de Acesso Aberto: um estudo analítico sobre Acesso Aberto e comunicação científica", disponível em http://dx.doi.org/10.7476/9789237012376

## Como se candidatar

Envie o link do seu perfil nas redes de *social coding* (Github, Bitbucket etc),  
seu CV e referências de trabalhos anteriores para  `vagasti [at] scielo [dot] org`

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após a candidatura.

## Labels

- Alocado
- CLT
- Freela
- PJ
- Pleno
- Sênior

**Comment by pedroch4610** [comment]
Curso superior é um requisito obrigatório?

**Comment by gustavofonseca** [comment]
> Curso superior é um requisito obrigatório?

Olá @pedroch4610, grato pelo interesse. Ambos os projetos demandam profissionais qualificados e experiêntes. Penso que o eventual não cumprimento do requisito em questão pode ser compensado por 10 anos de experiência.

**Comment by pedroch4610** [comment]
Bom dia! Graduação em Licenciatura em Computação serve para a vaga?

**Comment by gustavofonseca** [comment]
Vou fechar a oferta temporariamente até que consiga avaliar todas as aplicações. Agradeço o interesse de todos.
