### ISSUE TITLE
[Remoto] Full Stack Developer na bxblue

### ISSUE THREAD

**Issue by nuk** [frontendbr/vagas#2248]
## Descrição da vaga

Essa é uma vaga para integrar o time de desenvolvimento do produto na bxblue.com.br . É uma vaga remota, sem pre-requisitos ou preconceitos. O que buscamos são pessoas com pontos de vista diferentes, aptas a desenvolver soluções web e dispostas a resolver problemas em equipe. Interessados basta entrar em http://bit.ly/bxdev2019 e deixar seus dados.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Saber se comunicar em Inglês e Português
- Se sentir a vontade no desenvolvimento, manutenção e deploy de aplicações web
- Ter disponibilidade para trabalhar em período integral

**Não Precisa:**
- Morar perto da gente (somos remotos)
- Fazer parte de qualquer grupo (seja por idade, genética, geografia, escolha pessoal ou acaso do destino)
- Ser fluente na nossa Stack de Desenvolvimento

## Nossa empresa

A bxblue é uma fintech com a missão de ajudar as pessoas a terem acesso ao crédito pessoal mais barato do país. Fomos investidos por grandes nomes do cenário nacional e internacional. Dentre eles a Y Combinator (Aceleradora responsável por empresas como AirBnB, Dropbox, Heroku, Docker e Twitch). Também tivemos a honra de sermos selecionados pelo Banco do Brasil para co-criarmos juntos a primeira API de Empréstimo do Brasil. Hoje estamos na lista das 100 Startups para ficar de olho em 2019.

## Como se candidatar

Interessados basta entrar em http://bit.ly/bxdev2019 e deixar seus dados.

**Comment by MoraesGil** [comment]
Qual a stack que vocês trabalham??

**Comment by nuk** [comment]
@MoraesGil A stack é bem extensa. Mas o aplicação principal é em RoR, Mongo e Heroku com bastante integrações com outros sistemas e produtos internos e externos.

**Comment by krivax** [comment]
@nuk acabei de me candidatar

**Comment by halkliff** [comment]
@nuk mandei esse formulário já há alguns dias, e ainda não obtive resposta. Quanto tempo para feedback?

**Comment by nuk** [comment]
@halkliff Peço desculpas pela demora, o processo de análise pode demorar até 10 dias. Isso por que lemos todas as respostas com calma. Posso garantir que a sua entrada está em análise =]
