### ISSUE TITLE
[São Paulo] Front-End Developer Pleno na Netpoint

### ISSUE THREAD

**Issue by marciano-netpoint** [frontendbr/vagas#2250]
## Descrição da vaga

A Netpoint é uma empresa de tecnologia com foco em transmissão ao vivo e plataformas de EAD.
Nós estamos buscando um(a) Desenvolvedor(a) Front-End para participar ativamente do desenvolvimento e manutenção dessas plataformas.
Se você se sente à vontade em trabalhar em equipe, gosta do que faz e topa enfrentar desafios. Gostaríamos de te conhecer 😊

**Principais responsabilidades**

- Desenvolvimento de interfaces que se adaptam a diversos dispositivos e tamanhos de tela;
- Em parceria com um(a) designer, entregar valor para o usuário, garantindo melhor usabilidade e fidelidade do layout;
- Trabalhar com requisições HTTP utilizando API Rest;
- Participar de uma equipe multifuncional interagindo com os profissionais de todas as áreas de conhecimento;
- Participar de todo o ciclo de desenvolvimento de produto, passando pelas fases de concepção, implementação e validação.
- Testar, testar, testar.

## Local

Avenida Angélica, 1761 - Higienópolis - SP

## Benefícios

**PJ**
 - Horário flexível;
 - Trabalho remoto;
 - Incentivo ao estudo;

**CLT**
- Benefícios acima e:
- Vale refeição;
- Vale transporte ou grana para estacionamento;
- Seguro de Vida;

## Requisitos

**Obrigatórios:**
- Proativa(o) e organizada(o)
- HTML5
- CSS3
- Bootstrap
- Javascript Vanilla
- jQuery
- Conhecimento em consumir API Rest
- Experiência com cross-plataform e testes cross-browser
- Experiência com design responsivo para web e mobile;
- Experiência com suporte a browsers antigos (graceful degradation), vulgo IE 11
- Não se importar em fazer café no coador ☕

**Desejáveis:**
- Experiência com HTML semântico, uso de Web Markup e boas práticas WCAG visando acessibilidade;
- Noções em SEO (metatags, opengraphs, tracking codes);
- Noções de Wordpress (instalação, atualização de temas e plugins);

**Diferenciais:**
- CSS modular e escalável com metodologias de arquitetura CSS como BEM ou Atomic Design;
- Noções em Git (versionamento);
- Você tem um Behance? Github? Snippets de código no Codepen? Textos no Medium? Blog? Outras iniciativas que você acha interessante? Mande pra nós, queremos saber de tudo 😁

## Contratação
- PJ: R$ 3.500,00 à R$ 4.500,00.
- CLT: à combinar.

## Nossa empresa

A Netpoint é uma empresa que nasceu com a vocação para tecnologia e que iniciou suas atividades juntamente com a chegada da internet no Brasil, em 1995. Desde então, vem aperfeiçoando seus produtos, investindo em novos serviços e tecnologia.

Hoje somos especializados em transmitir e gerenciar eventos ao vivo online para diversas plataformas, além de fornecer opções de publicação e gerenciamento para os vídeos gravados. Ao ouvir as demandas de seus clientes, a Netpoint foi ao longo desses anos, aprimorando sua equipe e serviços para atender os mais diferentes perfis e necessidades.

https://netpoint.live/

## Como se candidatar

- 👉👉Fazendo nosso teste técnico: [Clicando aqui](https://github.com/marciano-netpoint/Teste-Front-end) 👈👈

## Tempo médio de feedbacks

A estimativa é que o processo de contratação dure até 26/08.
Após o envio do [teste técnico](https://github.com/marciano-netpoint/Teste-Front-end) nós responderemos confirmando o recebimento e precisaremos de um tempinho para avaliar 😉
E-mail para contato em caso de não haver resposta: trampos@corp.netpoint.com.br

## Labels

- Alocado
- CLT
- PJ
- Pleno

**Comment by adeonir** [comment]
@marciano-netpoint no PJ é 100% remoto?

**Comment by marciano-netpoint** [comment]
> @marciano-netpoint no PJ é 100% remoto?

@adeonir , não é. Após você pegar a rotina do dia-a-dia você pode conversar pra fazer até três dias de home-office. Isso é discutido entre você, a equipe e o CEO :)
