### ISSUE TITLE
[Remoto] Front-End Developer na AlphaSights 

### ISSUE THREAD

**Issue by jcfigueiredo** [frontendbr/vagas#2253]
Olá, 

Estamos em busca de pessoas que tenham interesse em trabalhar (remotamente) em desevolvimento front-end na [AlphaSights](https://www.alphasights.com/careers/alphatech)

**Local**
Remoto - New York, London

**Benefícios**
- Salários acima de $20,000.00
- Visitas aos nossos escritórios de NYC/London 4 vezes ao ano

**Diferenciais**
- Nada de trabalho fora de hora!
- Equipamento top de linha fornecido pela empresa
- [Cultura super legal](https://www.youtube.com/watch?v=QcSieDMulhM) e já adaptada para trabalho remoto com o Brasil

**Requisitos Obrigatórios:**
- 6+ anos desenvolvendo Software
- 3+ anos desenvolvend front-end
- Inglês técnico e conversacional

**Desejáveis:**
- conhecimento de React
- conhecimentos de EmberJS

**Diferenciais:**
- projetos opensource
- Agile, scrum, ou similar
- Pair Programming
- TDD,  Pair Programming, XP (extreme programming), DDD
- conhecimentos desenvolvimento back-end

**Contratação**
PJ

**Como se candidatar**
Preencha o formulário aqui ([https://grnh.se/c037a82e1](https://grnh.se/c037a82e1)) e nosso time de recrutamento entrará em contato!

1. A descrição não contém requisitos para front-end pois esse link é para todas as vagas de Engenharia remoto
2. Temos várias vagas em aberto e vagas especiais para Times! Chame os amigos que queira trabalhar junto - front-end ou back end também!

## Labels

- PJ
- Pleno
- Remoto
- Sênior

**Comment by jcfigueiredo** [comment]
Para mais visibilidade, o salário é de mais de R$20.000,00 ao mês.

**Comment by italomlp** [comment]
@jcfigueiredo há vagas para pessoas com menos experiencia?

**Comment by jcfigueiredo** [comment]
@italomlp infelizmente não nesse momento.

**Comment by italomlp** [comment]
Ok, obrigado. Ficarei acompanhando vocês enquanto amadureço em experiência. Até mais! 😁

**Comment by itelo** [comment]
@jcfigueiredo sabe dizer o tempo medio de respota?

**Comment by EduhCosta** [comment]
Qual a avaliação do inglês?

**Comment by jcfigueiredo** [comment]
@itelo devido ao número de aplicações pode ser que leve alguns dias mas deve ser essa semana.

**Comment by KelvinFSoares** [comment]
@jcfigueiredo Faço parte de um time de devs de alto niveis, ja trabalhamos juntos para a Lenovo US remotamente e ficamos bastante interessados na AlphaSights. Como não achei a opção no form acima, gostaria de saber se é possível aplicar todos os perfis e o time.

Abraço.

**Comment by jcfigueiredo** [comment]
@EduhCosta a avaliação do inglês acontece como parte do processo de entrevista que será somente nessa língua.

**Comment by wagner94** [comment]
seria muito legal fazer parte desta equipe

**Comment by netojose** [comment]
@jcfigueiredo  , se eu morasse no Brasil, me apliacaria sem titubiar. Boa sorte aí, vou passar o link para uns amigos

**Comment by jcfigueiredo** [comment]
Obrigado @netojose !

**Comment by marciogurka** [comment]
@jcfigueiredo ainda tem vagas em aberto??

**Comment by jcfigueiredo** [comment]
@marciogurka temos sim!

**Comment by halkliff** [comment]
@jcfigueiredo faço programas desde meus 12 anos de idade, mas efetivamente só tenho 4 anos de mercado. Posso me aplicar à essa vaga também?

**Comment by israelcena** [comment]
can't find that page :(
