### ISSUE TITLE
[São Paulo] UI/UX Designer na Pontaltech

### ISSUE THREAD

**Issue by viebig** [frontendbr/vagas#2257]
Veja [https://pontal.gupy.io/jobs/64678](https://pontal.gupy.io/jobs/64678)

##  Descrição da vaga

Procuramos com um profissional UX/UI.

##  O que você irá fazer:

- Construir do início ao fim o processo de UX/UI, desde pensar no fluxo que o usuário pode percorrer até desenhar a interface final que será desenvolvida;
- Criar e rever interfaces para diversos produtos SaaS;
- Criação e manutenção de design system;
- Auxiliar decisões pautadas em dados e utilizar métodos, teorias e ferramentas de design como apoio.

## O que esperamos de você?

- Experiência anterior em design e UX;
- Compreender métricas de navegação (analytics, heatmaps) e fazer sugestões com base em dados.
- Domínio de ferramentas de prototipação como Sketch, Figma e Adobe XD;
- Conhecimento de pesquisas com usuários (qualitativa e quantitativa);
- Planejamento e condução de testes de usabilidade;
- Facilitar sessões de co-criação com stakeholders;
- Ter trabalhado com design de aplicações web;
- Possuir portfólio que demonstre suas ultimas experiências.

## Porque trabalhar na Pontal?
Somos uma empresa de tecnologia jovem e dinâmica que conecta pessoas, empresas e tecnologia, promovendo experiências completas em comunicação digital.

Buscamos os melhores para fazer parte dessa história de sucesso! Vem fazer a diferença com a Pontaltech!

## Nossos benefícios

Vale refeição, vale transporte ou auxilio estacionamento, assistência médica e odontológica, inglês in company, convênio farmácia, convênio com diversas faculdades e cursos profissionalizantes, ambiente descontraído e divertidos eventos internos!

## Local de trabalho

Centro de SP

**Comment by kvnol** [comment]
@viebig o github tem um portal exclusivo para vagas de ui/ux designer: https://github.com/uxbrasil/vagas

**Comment by viebig** [comment]
Obrigado @kvnol, vou postar lá !
