### ISSUE TITLE
[São Paulo] Front-End Developer na [T4W Tecnologia]

### ISSUE THREAD

**Issue by GeracaoTalento** [frontendbr/vagas#2265]
Somos a Geração Talento - Consultoria em RH e estamos apoiando o nosso cliente nesta oportunidade.

Front-End Developer na T4W

Convidamos você à trabalhar em uma equipe colaborativa e dentro de uma empresa tecnológica que valoriza o crescimento e desenvolvimento profissional.

Será responsável pelo Desenvolvimento (frontend) e por Integrações entre Sistemas (internos e externos), dos clientes.

Requisitos necessários:

- AngularJS 2 e 4.
- Bootstrap.
- Npm.
- TFS.

Requisitos desejáveis:

- VUE.JS.
- C#.
- Web-API.

Diferenciais:

- Ter trabalhado com integrações entre sistemas.
- Ter convivência com o mercado de Turismo.
- Inglês técnico.

Desejável : Formação Superior em Ciências da Computação, Sistemas da Informação ou área relacionada.

Contratação CLT + benefícios (VT, VR R$ 715,00 por mês, VA R$ 400,00 por mês, Plano Médico da Allianz). 

Local: Região da Vila Olímpia - SP (próximo à estação de trem). 

Enviar o CV com a pretensão salarial para o Marcelo no e-mail (marcelo@geracaotalento.com.br).

**Comment by danielswater** [comment]
Aceita remoto?

**Comment by GeracaoTalento** [comment]
Boa tarde! Apenas presencial mesmo.
