### ISSUE TITLE
[São Paulo] Front-End Developer na McCann Health

### ISSUE THREAD

**Issue by tiagords** [frontendbr/vagas#2266]
## Descrição da vaga

Contratação PJ/CLT desenvolvedor(a) para vaga de Front-End.

## Local

Av. Chedid Jafet, 75 - Vila Olimpia
São Paulo - SP
04551-010

## Requisitos

**Obrigatórios:**
- HTML5
- CSS3
- JavaScript

**Desejáveis:**
- Bootstrap
- Conhecimentos em Git

**Diferenciais:**
- WordPress
- VisualAid (VA)

## Contratação

PJ/CLT a combinar

## Como se candidatar

Por favor envie um email para tiago.rodrigues@mccannhealth.com.br com seu CV em anexo, portfólio (se houver) e pretensão salarial.

## Labels

- PJ
- CLT
- Júnior
- Pleno

**Comment by danielswater** [comment]
Aceita remoto?

**Comment by tiagords** [comment]
> Aceita remoto?
Não, somente presencial.
