### ISSUE TITLE
[Remoto] Full-stack Developer na Agência Bein

### ISSUE THREAD

**Issue by lucas-agenciabein** [frontendbr/vagas#2267]
## Descrição da vaga

A **Agência Bein** acaba de abrir oportunidades de trabalho para desenvolvedores, com conhecimento em **Laravel** e **ReactNative**, que queiram trabalhar com a gente de forma autônoma.

See you soon...
Agência Bein

## Local

Remoto

## Benefícios

1. Comunicação com desenvolvedores experientes
2. Quem sabe uma continha premium em seus sites favoritos? Deezer, Spotify, Netflix, Scribd, etc

#### Diferenciais

- Trabalhe no horário que quiser. Nós focamos apenas em resultados.

## Requisitos

**Desejáveis:**
- conhecimentos em laravel
- conhecimentos em reactnative

**Diferenciais:**
- ter desenvolvido projetos nessas tecnologias

## Contratação

Freelancer, a combinar. Não é necessário PJ.

## Nossa empresa

Aqui na Agência Bein, nós não desenvolvemos simples sites e aplicativos. Nós desenvolvemos coisas que mudam vidas, de pessoas e empresas.

## Como se candidatar

1. Envie um e-mail para [interno@agenciabein.com](mailto:interno@agenciabein.com) com seu CV anexado - enviar no assunto: Vaga Full-stack

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dia após cada processo.
E-mail para contato em caso de não haver resposta: lucas@agenciabein.com

## Labels

- Remoto
- PF
- Estágio
- Freela
- Júnior

**Comment by THAYLLER** [comment]
Email enviado =)

**Comment by emersonbrs** [comment]
Enviado. ;D

**Comment by ingliths** [comment]
Enviado. ; D

**Comment by fabiodaemon** [comment]
era necessário CV em inglês? Enviei em português porque o meu inglês está desatualizado e preciso de tempo pra fazer isso porém queria ter enviado já agora meu CV. desculpe!
