### ISSUE TITLE
[São Paulo] Front-End Developer na Agência WeJam

### ISSUE THREAD

**Issue by willianpossa** [frontendbr/vagas#2268]
## Descrição da vaga

Estamos procurando por um Desenvolvedor Front-End para trabalho alocado aonde terá como principais responsabilidades desenvolver/integrar e dar manutenção em sites e interfaces de aplicações web.

**Responsabilidades**
- Converter layout em código seguindo boas práticas de mercado.
- Sugerir melhorias em UX/UI para os projetos.
- Trazer melhorias técnicas para o time. ( aqui ninguém melhora sozinho, nós crescemos juntos! )
- Realizar integrações entre front-end e back-end utilizando APIs.

## Local

Alocado, São Paulo - Brooklin Paulista (a 5 min da estação)

#### Diferenciais

- Fliperama
- Poofs

## Requisitos

**Obrigatórios:**
- 1+ anos de experiência com desenvolvimento Front-end
- Bom entendimento de HTML, de forma que consiga escrever código semântico.
- Conhecimento básico de algum dos dois pré-processadores CSS a seguir ( LESS ou SASS )
- Experiência prévia com algum dos seguintes libs/framework JS (React, VueJS) e seus respectivos ecossistemas.
- Entendimento básico de como funcionam requisições HTTP.
- Experiência com jQuery.
- Experiência com o versionamento de código com GIT.
- Conhecimento de princípios de SEO e como aplica los.

**Diferenciais:**
- Conhecimentos básicos de Laravel Blade Templates ( suficiente para efetuar uma integração ).
- Conhecimentos em desenvolvimento de Temas Wordpress.
- Conhecimentos intermediários de UX/UI.

## Contratação

PJ a combinar

## Nossa empresa

Somos uma agência digital que desenvolve soluções para seus clientes. Entendemos o que o cliente precisa para o seu projeto e trabalhamos em cima disso para entregar a melhor solução possível. Nosso time é composto por pessoas que buscam fazer a diferença no mundo utilizando a tecnologia como meio. Se você se identificou conosco, dá um apply na vaga e vamos bater um papo. ;)

## Como se candidatar

Por favor envie um email para willian.wejam@gmail.com com seu CV/Linkedin anexado - enviar no assunto: Vaga Front-End Developer FrontEndBR

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.

## Labels

- Alocado
- PJ
- Júnior
- Pleno

**Comment by JulioVMelo** [comment]
Alguma possibilidade de remoto Willian?


Em ter, 6 de ago de 2019 às 00:53, Willian Possa <notifications@github.com>
escreveu:

**Comment by willianpossa** [comment]
Bom dia @JulioVMelo , beleza?

Essa vaga é 100% alocado. 
Mas envia seu CV mesmo assim, que se aparecer alguma vaga remoto, já deixo ele salvo. o/

Abs.
