### ISSUE TITLE
[Curitiba]Desenvolvedor Front-end

### ISSUE THREAD

**Issue by klassetech** [frontendbr/vagas#227]
## Descrição da vaga

A Klasse! Tech Talents, atendendo ao OmniChat, está a sua procura!

Buscamos profissional que estejam alinhados ao ritmo de uma start up, motivados pelo desafio e engajados com o crescimento do negócio. 

## Local

 OmniChat - Curitiba/PR

## Requisitos

**Obrigatórios:**
- Experiência em HTML 5 e CSS 3.
- Conhecimento em Javascrip. 
- Vivência com tecnologia Angular.JS

## Contratação

CLT 

## Nossa empresa

A Omnichat é uma startup em crescimento que busca profissionais comprometidos . 

## Como se candidatar

Por favor envie um email para janaina@klasse.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor Front-end

**Comment by LFeh** [comment]
Opa, faltou descrição, aahaha

**Comment by klassetech** [comment]
DESENVOLVEDOR FRONT END
A Klasse! Tech Talents, atendendo ao OmniChat, está a sua procura!

Buscamos profissional que estejam alinhados ao ritmo de uma start up, motivados pelo desafio e engajados com o crescimento do negócio. 

Paixão por Angular.js, HTML 5, CSS3 Animation e desenvolvimento Mobile . Vivência nos frameworks Material Design ou Bootstrap.

**Comment by LFeh** [comment]
Pleno e Junior?

**Comment by klassetech** [comment]
Por se tratar de uma start up, este profissional será o único dá empresa, atendendo todas as demandas de desenvolvedor.

**Comment by raloliver** [comment]
Essa vaga foi preenchida?

**Comment by thenewbiemaster** [comment]
Enviado!
