### ISSUE TITLE
[São Paulo] Front-End Developer na [Agência Agile]

### ISSUE THREAD

**Issue by vinirossi** [frontendbr/vagas#2270]
## Descrição da vaga

A Agência Agile está procurando pessoas que queiram se desenvolver e aprender e crescer junto com a empresa. Portanto a contratação de Front End Developer Jr.

## Local

Escritório, São Paulo - Mooca

## Requisitos
- Conhecimentos em HTML5, CSS3 e JavaScript/jQuery;
- Conhecimentos em PHP 5.6 +;
- Conhecimentos básicos em MySQL + Linguagem SQL;
- Conhecimentos em programação de temas para o WordPress (do zero) e no uso de plugins como Contact Form 7, ACF, CPT UI, Woocommerce e etc;

**Desejáveis:**
- Noções de SASS/LESS/Stylus;
- Noções de Git/BitBucketNoções de Grunt/Gulp;

## Contratação

PJ a combinar

## Nossa empresa

A Agile é uma Agência de Marketing Online e Comunicação Visual focada em resultados. Temos a solução certa para aumentar suas vendas e aproximar sua empresa dos clientes que estão a sua procura.

## Como se candidatar

Eu Vinicius estou apenas repassando a vaga, por favor envie um email para guilherme@agenciaagile.com.br com seu CV anexado - enviar no assunto: Vaga Front End Developer Jr. Qualquer outra dúvida, manda no e-mail.

## Labels

- Alocado
- Freela
- Júnior
- PJ

**Comment by gabok2** [comment]
Vcs querem um full stack

**Comment by vinirossi** [comment]
@gabok2 

Eu Vinicius estou apenas repassando a vaga, por favor envie um email para guilherme@agenciaagile.com.br com seu CV anexado - enviar no assunto: Vaga Front End Developer Jr. Qualquer outra dúvida, manda no e-mail.
