### ISSUE TITLE
[Curitiba] - Front-End Developer e WordPress na Tesis

### ISSUE THREAD

**Issue by iperacchi** [frontendbr/vagas#2275]
## Descrição da vaga

Você será o responsável pelo desenvolvimento de uma aplicação utilizando o WordPress com o ACF.

## Local

Escritório, Curitiba - Rua João Domachoski, 132

#### Diferenciais

- Equipamento Mac

## Requisitos

- Bootstrap 3,4
- HTML5
- CSS3
- JavaScript
- WordPress intermediário

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para dev@tesis.digital com seu CV anexado - enviar no assunto: Vaga PHP Wordpress

### Alocação:
- Presencial

### Contratação:
- PJ

### Experiência
- Estágio
- Júnior
- Pleno

**Comment by hmilena** [comment]
Pode ser freela? =)
