### ISSUE TITLE
[São Caetano do Sul] Front-End Developer (2 vagas)

### ISSUE THREAD

**Issue by wesleypimentel** [frontendbr/vagas#228]
## Descrição da vaga

O BomControle está com 2 ótimas oportunidades para Front-End Developer.
Estamos à procura de profissionais comprometidos e motivados a vencer desafios, para agregar nosso time e crescerem juntos com este grande projeto.

## Local

Escritório, Centro de São Caetano do Sul / SP
_Próximo à estação de trem_

## Benefícios

- Horário de almoço flexível (1h a 2h)
- Área de Jogos e entretenimento _(XBOX, Bilhar, Ping-pong, violão)_
- Frigobar sempre cheio _(Breja, Refri)_
- Área para descanso e estudo

## Requisitos

**Obrigatórios:**
- **Angular JS** _(Indispensável)_
- JavaScript
- HTML5
- CSS3 / Pré-processadores (LESS)
- API / RESTFul

**Desejáveis:**
- Conhecimentos em Task Runners (Gulp)
- Conhecimentos em GIT

**Diferenciais:**
- Noções de sistemas ERP, SIG
- Noções sobre rotina financeira, estoque, CRM e help-desk

**Níveis**
- Pleno
- Sênior

## Contratação

PJ a combinar (Enviar pretensão salarial)

## Nossa empresa

O BomControle é um sistema ERP Online, composto por diversos módulos gerenciais integrados, ou seja, soluções para diversas finalidades, mas que compartilham dados e informações entre si.

Dentre estas soluções, estão o módulo de Gestão Financeira, Controle de Estoque, CRM para gestão de clientes, vendas e negócios, o ServiceDesk para suporte e atendimento ao cliente, BPM para criação e organização de processos internos e, por fim, a Universidade BomControle, módulo especial para você aprender sozinho todas as ferramentas do sistema.

Site oficial: [bomcontrole.com.br](http://bomcontrole.com.br)

## Como se candidatar

Por favor envie um email para rh@bomcontrole.com.br seu CV anexado e pretensão salarial.
Enviar no assunto: Vaga Front-End

**Comment by LFeh** [comment]
Pleno?

**Comment by wesleypimentel** [comment]
E/Ou Sênior

**Comment by wesleypimentel** [comment]
Olá! Estou fechando esta issue pois a vaga já foi preenchida.
**O candidato aprovado ficou sabendo dela por aqui!** \o/
_PS: Divulguei inicialmente "2 vagas", mas a empresa me disse que optaram em manter apenas 1. Sendo assim, surgindo uma nova oportunidade abrimos outra._
Obrigado @LFeh pelo espaço e pela iniciativa! Forte abraço ;)

**Comment by LFeh** [comment]
Aeeee o/
