### ISSUE TITLE
[Remote] Front-End Developer at Neat

### ISSUE THREAD

**Issue by hugw** [frontendbr/vagas#2282]
## Descrição da vaga

The front end engineer at Neat will be responsible for helping build exciting new functionality on top of Neat's new React/Node-based web application backed by a Mongo database.

The position will report to the technical lead, but will frequently engage with other members of the development/QA staff, as well as with product and UX teams, to help scope, design, and estimate features and enhancements being considered for prioritization.

### Responsibilities

- Develop new features and user experiences in our next-generation web application, working closely with QA to ensure a quality end-user experience.
- Coordinate with Product and UX teams to help scope, design, and estimate features and enhancements being considered.
- Ensure clean coding practices and patterns are used through collaborative code design and review.
- Monitor crash reporting and performance/analytics services to identify trends or spikes of importance or concern.

### Qualifications

- 3+ years of development experience on JavaScript applications using any modern framework (React, Angular, Backbone, etc.) with emphasis on the latest ECMAScript standards.
- 2+ year of experience with React in a production setting (experience with Redux and/or Electron is a plus).
- Experience working with REST APIs and debugging API responses (Sockets is a plus)
- Experience with Node.js and maintaining NPM packages.
- Experience with SASS, and LESS preprocessors (CSS Modules is a plus).
- Knowledge of the latest HTML and CSS standards and patterns.
- Write unit/snapshot tests using Jest.
- Some experience with Express.js (Mongoose ODM is a plus)
- Familiarity with development/build tools such as Webpack, Babel, Lerna, etc.
- Ability to work well in a distributed team.
- Strong writing and communications skills.
- Good at time management and multi-tasking.
- Proactive mindset with a passion for making things better.
- Willingness to learn new technologies.

## Local

Remoto. Início o quanto antes.

## Faixa salarial

__$ 45 - 65 mil dólares por ano__. Dependendo do perfil podemos negociar.

## Requisito

- Inglês avançado.
- Preferencialmente na timezone ET(GMT -4) ou próximo. Estamos situados na Philadelphia - US.

## Contratação

Contrato via PJ ou PF, não faz diferença para nós.

## Como se candidatar

Por favor envie um email para hcorrea@neat.com com o link do seu Github e Linkedin.
Enviar no assunto: _Vaga FE_
Se possível coloque sua pretensão salarial e disponibilidade para começar.

**Comment by brenoos** [comment]
enviado

**Comment by hugw** [comment]
Galera, obrigado a todos os que enviaram seu currículo.

A vaga foi preenchida e todos que eu não puder responder pessoalmente, desejo sucesso. Fiquem de olho pois mais vagas irão abrir em breve.

Abraços!

**Comment by fabiomirandaa** [comment]
@felipefialho essa aqui está fechada.
