### ISSUE TITLE
[Rio de Janeiro] Fullstack Developer na Vigia de Preço

### ISSUE THREAD

**Issue by gislainy** [frontendbr/vagas#2286]
## Descrição da vaga

Atuar em correções, melhorias nos projetos já existentes e novos projetos do grupo Vigia de Preço, com atenção especial na qualidade do código. Buscamos um profissional com brilho nos olhos e que esteja disposto aprender e compartilhar conhecimento e experiência conosco, participando desde o processo de arquitetura, análise, evolução até a produção das nossas soluções. 

Se você adora desafios, tem fome por aprendizado e gosta de ambientes descontraídos com foco em evolução constante, venha trabalhar conosco! Ensino Superior cursando ou completo em Sistema da Informação e áreas afins será muito bem-vindo. 

Conhecimento e experiência com Javascript, ES6, NodeJS, MongoDB, VueJS, sendo desejável ter conhecimento em NuxtJS e Redis. Vale ressaltar que o Vigia de Preço oferece excelentes oportunidades para crescimento dentro da empresa...Gostou? Então venha logo, pois estamos te esperando 😉.

## Local

Escritório, Rio de Janeiro - Barra da Tijuca

## Benefícios

- Plano de saúde
- VR de R$ 40/dia
- Vale Transporte

- Férias Remuneradas de 15 dias (final do ano)

#### Diferenciais

- Horário flexível
- Frigobar sempre cheio :P
- Ingressos do jogo do Botafogo (ou qualquer outro jogo no Estádio Nilton Santos)

## Requisitos

*Obrigatórios:*
- Experiência com Javascript, ES6+
- Experiência com NodeJS, MongoDB
- Experiência com VueJS 

*Desejáveis:*
- Conhecimento em NuxtJS
- Conhecimentos em Redis

*Diferenciais:*
- Projetos aberto nos github 

## Contratação

PJ (exceto MEI)  

Salário => R$ 6.500,00 + Benefícios

## Nossa empresa

O Grupo Vigia de Preço oferece uma série de soluções em tecnologia, com foco em performance para diversos segmentos.  O grupo conta com uma gama de produtos variados: um whitelabel de site de cupons; whitelabel de extensão Assistente de Compras para Google Chrome e Firefox; uma base de Push e parceria com grandes portais, disparadores de email, entre outras fontes de tráfego. Para saber mais sobre a empresa veja nossa [apresentação](https://vigiadepreco.com.br/index/img/apresentacao.pdf)

## Como se candidatar

Por favor envie um email para itamar.ribeiro@vigiadepreco.com.br com seu CV anexado - enviar no assunto: Vaga Fullstack

Caso possa enviar o link do github/afins com os projetos abertos

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.

## Labels

- Alocado
- PJ
- Pleno
- Sênior

**Comment by evertonnppp** [comment]
ola gostaria de conversa  com o reposavel pela vaga 
meu whats app e 21 992433897
