### ISSUE TITLE
[Barcelona, Espanha] Senior Front-End Software Engineer

### ISSUE THREAD

**Issue by raphaklaus** [frontendbr/vagas#2287]
# Sobre a empresa
SafeBoda é uma empresa que está revolucionando o mercado leste Africano de mobilidade. Realmente um trabalho incrível, dá uma olhada: https://safeboda.com/ug/

---

Bom, depois dessa pequena introdução... A empresa que trabalho aqui em Barcelona tá precisando escalar rapidamente e precisa de ótimos devs. :)

Obrigatório:

* Ótimo conhecimento em JavaScript
* VueJS
* Vuex
* CSS/SASS
* Vuetify/Vue Material ou outros design frameworks
* WebPack
* Testing (TDD, BDD, end-to-end e unit), nós valorizamos muito esse ponto.
* Inglês fluente

Benefícios:

* Sponsorship de visto :+1:
* 35k ~ 50k EUR/ano
* Pacote de realocação
* Alocado (não rola remoto)
* Horário flexivel, equipe incrível!
* Possibilidade de viajar (ou morar, se você quiser!) pra África para conhecer a sede da empresa
* Trabalhar na cidade mais foda da Europa :eyes:
* Escritório à poucos metros da praia :sunglasses: 

Mais informações aqui: https://www.linkedin.com/feed/update/activity:6531509359162200064/

Labels:
- Senior
- JavaScript
- VueJS
- Vuex
- Testing
- Visa Sponsorship
- Full Time
- Inglês fluente
- Alocado

**Comment by fafa1** [comment]
Parabéns pelo trabalho!
