### ISSUE TITLE
[Vila Mariana / São Paulo] Frontend Senior Developer 

### ISSUE THREAD

**Issue by klaygomes** [frontendbr/vagas#229]
## Descrição da vaga

Desafio: Criar a arquitetura front para um grande projeto SAAS web. Desenvolver front de novas features. Garantir a qualidade de código da equipe segundo os padrões que você definir. Monitorar terceiros que poderão colaborar no projeto (equipe complementar).

Necessário conhecimentos no desenvolvimento WEB avançado, (Angular||React||Vue) && Javascript avançado && HTML5 && CSS3. Desejável: Comprometimento em desenvolver código testável e de fácil manutenção (TDD, SOLID, Padrões de projeto, Angular 2 etc).

## Local

Vila Mariana / SP ficamos próximo das estações Vila Mariana e Ana Rosa.

## Benefícios

- 2 horas de almoço;
- Máquina de café expresso (café moído);

## Requisitos

**Obrigatórios:**
- Ter perfil de liderança;
- Pelo menos 7 anos de experiência em desenvolvimento web;
- Saber pelo menos uma framework de desenvolvimento moderna (Angular || Reac || Vue e etc);
- Ter excelente conhecimento de Javascript;
- TDD, SOLID, Padrões de projeto;

**Desejáveis:**
- Conhecimentos em C# e ASP.NET MVC  (não é obrigatório, mas ajudaria);
- API Management

**Diferenciais:**
- Projetos opensource;
- Participação ativa na comunidade

## Contratação

PJ (até R$10.000,00) ou CLT

## Nossa empresa

A ANAPRO é uma empresa de tecnologia e serviços com mais de 15 anos focada no mercado imobiliário, oferecendo soluções para gestão comercial de empreendimentos, atendendo mais de 120 incorporadoras em todo Brasil (Odebrecht, OAS, Tishman Speyer, VITACON, Direcional, Carvalho Hosken, Ilha Pura, Patrimônio, Colmeia, Manhattan, Engeco, Grupo Paz Mendonça, Exto, Niss, Bueno Neto, Emplavi, Vilela e Carvalho, Attos, EBM, Bairro Novo e muitas outras, grandes, pequenas e médias), Já participamos de mais de 1100 lançamentos imobiliários, operacionalizando mais de R$ 38 bilhões em VGV, com mais de 38 mil usuários cadastrados. 

## Como se candidatar

Por favor envie um email para cleiton@anapro.com.br e fabricio@anapro.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor Frontend Senior

**Comment by klaygomes** [comment]
Profissional já foi contratado.

**Comment by LFeh** [comment]
Boa!

Alguém daqui?

**Comment by klaygomes** [comment]
Indicação de um usuário do facebook
