### ISSUE TITLE
[Remoto] Front End Developer na CodeLeap UK

### ISSUE THREAD

**Issue by vrgimael** [frontendbr/vagas#2290]
## Descrição da vaga

👔 Vaga: Desenvolvedor Front-End
💼 Empresa: CodeLeap UK
📍 Localização: Onde quiser (remoto)
🌎 Idioma necessário: Inglês fluente

## Local

Remoto - Escritório central em Londres, Reino Unido

## Benefícios

💵 Remuneração: R$5000 a R$8000 por mês

#### Diferenciais

- Sem horário ou local de trabalho, o que importa é fazer acontecer!
- Equipe flexível, espaço para crescimento na empresa

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com desenvolvimento em React e JavaScript

**Desejáveis:**
- conhecimentos em React-Native
- conhecimentos em Python

## Contratação

PJ a combinar

## Nossa empresa

👉 Interessado? Veja: https://codeleap.co.uk/careers/frontend

## Como se candidatar

✉️ Mande seu CV para: apply@codeleap.co.uk

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👨 Pleno
- ⚖️ A-Combinar
- ⚖️ PJ
- 💰 5k-10k

**Comment by JIFerreira** [comment]
8mil por uma vaga internacional? Ta certo esse salário?

**Comment by vrgimael** [comment]
@JIFerreira sim, dependendo da experiencia

**Comment by willycamargo** [comment]
Não é a inteção tumultuar a thread, então desculpa caso isso aconteça.

> 8mil por uma vaga internacional? Ta certo esse salário?

Acho comum salários assim para empresas contratando remoto.

1. As empresas acabam atingindo as pessoas que preferem morar em cidades mais afastadas (e consequentemente com menos oportunidades).
2. É uma boa porta de entrada para quem ainda não tem experiência com trabalho remoto.
3. Após algum tempo a pessoa percebe que é um pagamento abaixo para a atividade e renegocia ou então arruma outro trabalho remoto para quem pague mais.*

*Empresas que possuem esse salário como entrada e não renegociam o salário acabam tendo uma rotatividade bem alta. Já presenciei algumas experiências.

**Comment by viniciusoliveira01** [comment]
> Não é a inteção tumultuar a thread, então desculpa caso isso aconteça.
> 
> > 8mil por uma vaga internacional? Ta certo esse salário?
> 
> Acho comum salários assim para empresas contratando remoto.
> 
> 1. As empresas acabam atingindo as pessoas que preferem morar em cidades mais afastadas (e consequentemente com menos oportunidades).
> 2. É uma boa porta de entrada para quem ainda não tem experiência com trabalho remoto.
> 3. Após algum tempo a pessoa percebe que é um pagamento abaixo para a atividade e renegocia ou então arruma outro trabalho remoto para quem pague mais.*
> 
> *Acredito que empresas que possuem esse salário como entrada e não renegociam o salário acabam tendo uma rotatividade bem alta. Presenciei em algumas experiências.

Concordo com todos os pontos, porém a dificuldade é a mesma para entrar em uma vaga remota trabalhando para fora e ganhando mais que o dobro. Só compensaria se fosse realmente fácil de entrar para a pessoa pegar confiança e ir para uma remota pagando mais que o dobro com inglês, nesse caso gerando alta rotatividade igual você mencionou.

**Comment by JIFerreira** [comment]
> Não é a inteção tumultuar a thread, então desculpa caso isso aconteça.
> 
> > 8mil por uma vaga internacional? Ta certo esse salário?
> 
> Acho comum salários assim para empresas contratando remoto.
> 
> 1. As empresas acabam atingindo as pessoas que preferem morar em cidades mais afastadas (e consequentemente com menos oportunidades).
> 2. É uma boa porta de entrada para quem ainda não tem experiência com trabalho remoto.
> 3. Após algum tempo a pessoa percebe que é um pagamento abaixo para a atividade e renegocia ou então arruma outro trabalho remoto para quem pague mais.*
> 
> *Acredito que empresas que possuem esse salário como entrada e não renegociam o salário acabam tendo uma rotatividade bem alta. Presenciei em algumas experiências.

1) Então, na verdade esse não é o intuito do trabalho remoto amigo, está totalmente distorcida essa informação!

2/3) Para ter experiencia com trabalho remoto é só fazer freela que a pessoa já sentirá na pele, não precisa ficar alimentando essas empresas que pagam pouco cara, essa é uma vaga internacional cara, a pessoa precisa do inglês e não é tão fácil assim ser fluente, é outra língua, é outro modo de pensar. O esforço/dedicação é alto.

Não é fácil encontrar empresas que pagam bem, com tanta gente aceitando salário baixo, por que você acha que as empresas perguntam os seus salários anteriores? É comum a empresa sempre se basear no salário da vaga estimando o seu ultimo salário!

**Comment by willycamargo** [comment]
Gente. Aqui não é Fórum de discussão.
Como trabalho há alguns anos remotamente e inclusive tive experiência com time internacional, acabei achando valido deixar um comentário opinativo e agora percebi que não deveria ter feito isso.

Caso queiram discutir sobre isso, acho válido criar uma thread sobre "trabalho remoto, experiências, remuneração etc." No frontendbr/forum. Estou a disposição para discutir sobre isso lá.

Ressalto que acho que a vaga é totalmente válida. Tem muito profissional ótimo procurando por oportunidades desse tipo. Sucesso no processo seletivo!

**Comment by felipefialho** [comment]
@willycamargo @viniciusoliveira01 curto a ideia dessa issue, até tem outras sobre trabalho remoto mas não lembro de nenhuma envolvendo remuneração ;)

**Comment by viniciusoliveira01** [comment]
> @willycamargo @viniciusoliveira01 curto a ideia dessa issue, até tem outras sobre trabalho remoto mas não lembro de nenhuma envolvendo remuneração ;)

Bora pensar em algo pra ajudar a comunidade que queira trabalhar remoto, seria top!

**Comment by vrgimael** [comment]
Sinceramente, esperava melhor compreensão da comunidade aqui! Pq duas negativadas?

Nossa empresa CodeLeap foi fundada recentemente, estamos procurando pessoas para se juntarem à equipe e crescer com a gente. Entendo que desenvolvedores com bastante experiencia, que falem inglês e morem em grandes cidades brasileiras ganhem mais, mas nossa oferta está perfeitamente dentro dos padrões do mercado - aliás, esses salários são excelentes para quem trabalha no interior, por exemplo, e quer uma oportunidade para conhecer trabalho remoto.

Se a vaga não preenche seus requisitos, por favor, procure outra, mas tenho certeza as oportunidades que trazemos serão muito bem vindas.

Obrigado!

**Comment by henriquegibi** [comment]
Eu estava resistindo em comentar mas terei de fazê-lo. E me desculpa tumultuar.

Acho que a vaga está muito boa e a empresa está de parabéns. Não é uma vaga internacional, é uma vaga remoto. Quem quer ganhar £ 55K anuais que tire a documentação por conta e vá procurar um emprego em Londres. Se eu atendesse os requisitos eu tava dentro, mas pela falta de experiência eu prefiro esperar uma oportunidade Júnior alocado junto com outros devs mais experientes.

Uma vez mais parabéns à empresa e quem não gostou não atrapalha quem está afim, se não os caras fecham a vaga aqui, abrem lá na Índia pagando metade do valor e os caras lá aceitam calados!!

**Comment by kivervinicius** [comment]
@vrgimael alguma chance para inglês não fluente, ainda?

**Comment by klisostom** [comment]
Parabéns à empresa pela vaga aberta!! Só não me candidato porque estou começando agora a aprender React.

**Comment by vrgimael** [comment]
> @vrgimael alguma chance para inglês não fluente, ainda?

@kivervinicius infelizmente como parte da equipe trabalha em diversos países, todos precisam falar inglês como idioma comum e toda a comunicação interna acontece em Inglês. 

Se falar suficiente pra se comunicar bem pode aplicar, a entrevista será toda em Inglês também com um sócio estrangeiro.

Obrigado pelo interesse!

**Comment by geekdoagrest** [comment]
Lembrar pra galera que prestação de serviço no brasil para empresa de capital no exterior tem isenção de vários impostos... fazendo uma conta aqui de cabeça, o que sobra fora os impostos de 8k para uma empresa de fora é mais que 10k para uma empresa no brasil...

**Comment by thismarcoantonio** [comment]
@vrgimael queria trocar uma ideia contigo antes de pensar em aplicar para a vaga, se você puder, é claro. Te mandei solicitação no linkedin.

**Comment by klisostom** [comment]
Opa!
Boa tarde!

Topo sim trocar uma ideia. Mas não recebi nenhum convite ou mensagem no linkedin até o momento. Como fazemos?

Cordialmente, Klisóstom.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Em Sexta-feira, 16 de Agosto de 2019 às 12:45, Marco Antônio <notifications@github.com> escreveu:

**Comment by thismarcoantonio** [comment]
Enviado!

**Comment by LucasMallmann** [comment]
Enviado! @vrgimael te mandei um convite no Linkedin! Agradeço se puder aceitar para conversarmos melhor sobre a vaga ;)

**Comment by raphaelssampaio** [comment]
Gostei da vaga! Enviei aqui!
