### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor Front-End (2 Vagas)

### ISSUE THREAD

**Issue by andrevvalle** [frontendbr/vagas#23]
## Descrição da vaga
Estamos procurando Desenvolvedores Front-end Junior e Pleno com bom conhecimento prático para integrar nossa equipe no Rio de Janeiro.

## Rio de Janeiro.
Escritório, Rio de Janeiro - Botafogo.

## Requisitos
- HTML5
- CSS
- Ferramentas de controle de versão (Usamos git)
- Javascript
- Atenção para detalhes (Pixel perfect)

**Desejáveis:**
- Pré-compiladores (Sass, Less, etc.)
- Task runners (Gulp, Grunt, etc.).
- Frameworks e Libs (React, Reflux, Redux, lodash, etc.)
- Node.js

## Contratação
CLT

## Como se candidatar
Caso tenha interesse, envie seu CV/Linkedin para:
felipe.rodrigues@vmlbrasil.com / luisa.haddad@vmlbrasil.com .

**Comment by LFeh** [comment]
Legal a vaga. Boa sorte ;)

**Comment by willianjusten** [comment]
=D

**Comment by LFeh** [comment]
@andrevvalle Conseguiram achar?

**Comment by andrevvalle** [comment]
Sim @LFeh. :laughing:

**Comment by LFeh** [comment]
\o

**Comment by camilatigre** [comment]
@andrevvalle 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
