### ISSUE TITLE
[SP - Berrini/Vila Olímpia] FrontEnd Engineer | Creditas

### ISSUE THREAD

**Issue by leoandreucci** [frontendbr/vagas#230]
## About Creditas

Creditas (formerly known as BankFacil) is one of the hottest Fintech Startups in Brazil. Headquartered in São Paulo, Creditas is a digital lending platform on a mission to lower the interest rates for the Brazilian population. By offering secured loans, using cutting edge technology with data driven mindset, we are reinventing the credit experience in Brazil.

Check out our team page to know more about what drives us:
[https://www.youtube.com/watch?v=ssGXFs8cI4c](https://www.youtube.com/watch?v=ssGXFs8cI4c)

Creditas (shown as BankFacil) is part of Google´s Launchpad Accelerator Program: [https://developers.googleblog.com/2016/05/introducing-second-class-of-launchpad.html](https://developers.googleblog.com/2016/05/introducing-second-class-of-launchpad.html)

Creditas (shown as BankFacil) was recently featured in GloboNews´ Mundo SA: [https://goo.gl/qhh3Y2](https://goo.gl/qhh3Y2)
## Requirements
- Semantic HTML;
- Scalable and modular CSS architecture, knowing good patterns like SMACSS;
- Modular Javascript development, with design patterns (for example: Mediator and Pubsub), with or without MV* frameworks;
- DOM manipulation without having needs of libs such as jQuery or Zepto;
- Knowledge of cross browsers problems and how to solve them;
- Good practices on how to optimize web pages to make the user experience sweeter;
- Knowing how to implement tests in JS
- Experience with Ember.js or another single-page application framework
## You will fit here
- We value individual and team effort, we expect high performance of everyone in the team
- We have a relaxed and extremely productive environment
- We want to be happy at our work environment and also in our personal lives
- We want to grow both as individuals and as professionals
- We constantly share knowledge related and unrelated to our individual tasks
- We thrive for knowledge and we love to get out of our comfort zones
- We believe and contribute to the engineering community
- We celebrate every single victory
- We love what we do! 
## What we offer
- Competitive compensation package;
- Transportation support;
- Meals support;
- Health plan;
- Gym plan;
- English classes;
- Shower and changing room for people who come by bike;
## Address
Av Eng Luis Carlos Berrini, 105 - presential position only
## Hiring Model
CLT
## How to apply

Please apply via this link: [https://creditas.recruiterbox.com/jobs/fk0h1mc/](https://creditas.recruiterbox.com/jobs/fk0h1mc/)

**Comment by leoandreucci** [comment]
@LFeh buscamos perfis plenos e juniors também - pode adicionar nos labels por favor?

**Comment by LFeh** [comment]
Claro! 😎

**Comment by brunooomelo** [comment]
Enviado!
