### ISSUE TITLE
[São Paulo] Front-End Developer - Angular 2+ na OSF GLOBAL SERVICES

### ISSUE THREAD

**Issue by carolina-brand** [frontendbr/vagas#2302]
## Descrição da vaga

Projeto em Angular 2+;

## Local

Escritório, São Paulo - na região central, próximo a estação da Luz, Glicerio. 

## Benefícios

- Bradesco Saúde (pago 100% pela empresa)
- Seguro de vida
- VR de R$ 27,00/dia
- Bônus Educação de R$150,00/mês
- Bônus Esporte de R$40,00/mês
- Programa de mentoring
- Certificações pagas pela empresa
- Plano de carreira bem delineado (avaliação de performance de 4 em 4 meses)

#### Diferenciais

- Empresa global presente em mais de 19 países

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com angular 2+
- Experiência com GIT

## Contratação

CLT + Benefícios (citados acima)

## Nossa empresa

OSF Global Services is a trusted technology consultant and technology integrator enabling companies to succeed over the greatest challenges in the world’s rapidly changing business environment. With expertise in cloud and mobile application development, enterprise CRM solutions, leading ecommerce platforms and integrated content management solutions.

## Como se candidatar

Por favor envie um email para carolina.brand@osf-global.com com seu CV anexado - enviar no assunto: Vaga Angular 2+

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: carolina.brand@osf-global.com

## Labels

- Alocado
- CLT
- Pleno
- Senior
- Angular

**Comment by carolina-brand** [comment]
Olá! Ainda temos posições abertas de Desenvolvedor(a) Angular 2+! :)

**Comment by halkliff** [comment]
@carolina-brand estão aceitando candidatos pra trabalho remoto?

**Comment by carolina-brand** [comment]
Olá, para essa oportunidade não, é preciso trabalhar on-site. Best Regards!
