### ISSUE TITLE
[São Paulo] Front-End Developer - React JS na OSF GLOBAL SERVICES 

### ISSUE THREAD

**Issue by carolina-brand** [frontendbr/vagas#2303]
## Descrição da vaga

Projeto em React JS;

## Local

Escritório, São Paulo - Vila Olimpia.

## Benefícios

- Bradesco Saúde (pago 100% pela empresa)
- Seguro de vida
- VR de R$ 27,00/dia
- Bônus Educação de R$150,00/mês
- Bônus Esporte de R$40,00/mês
- Programa de mentoring
- Certificações pagas pela empresa
- Plano de carreira bem delineado (avaliação de performance de 4 em 4 meses)

#### Diferenciais

- Empresa global presente em mais de 19 países

## Requisitos

**Obrigatórios:**
- Sólida experiência com HTML 5, CSS 3 e Javascript (ES6+)
- Experiência com React JS
- Experiência com Redux
- Experiência com Jest

## Contratação

CLT + Benefícios (citados acima)

## Nossa empresa

OSF Global Services is a trusted technology consultant and technology integrator enabling companies to succeed over the greatest challenges in the world’s rapidly changing business environment. With expertise in cloud and mobile application development, enterprise CRM solutions, leading ecommerce platforms and integrated content management solutions.

## Como se candidatar

Por favor envie um email para carolina.brand@osf-global.com com seu CV anexado - enviar no assunto: Vaga React

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: carolina.brand@osf-global.com

## Labels

- Alocado
- CLT
- Pleno
- Senior
- React JS
- Javascript

**Comment by halkliff** [comment]
Boa noite, há a possibilidade de remoto?

**Comment by carolina-brand** [comment]
Olá! Ainda temos posições abertas de Desenvolvedor(a) React JS! :)

**Comment by halkliff** [comment]
E aí, tem possibilidade de remoto?
