### ISSUE TITLE
[Campinas] Front-End Developer na [Superlógica]

### ISSUE THREAD

**Issue by deppbrazil** [frontendbr/vagas#2307]
## Descrição da vaga

Estamos procurando por desenvolvedores(as) Front-end que nos ajudará a construir e dar manutenção em nossas landing pages, websites, Design System e aplicações web, onde você irá trabalhar dentro de um time de Design e terá também interação e muito contato com outros times nas frentes de  back-end, mobile e devOps e negócio.

## Local

Escritório, Campinas - Vila Teixeira

## Benefícios

- Salário: a combinar
- Seguro de vida 
- Plano de saúde
- Plano odontológico 
- Estacionamento ou VT (sem desconto)
- Restaurante interno
- Auxílio creche

#### Diferenciais

- Escolha seu setup (Windows, Linux, MacOS)
- Happy hour todas as sextas-feiras dentro da empresa com chopp na faixa 
- Atuar em uma empresa que cresce + de 300% ao ano
- Biblioteca com mais de 280 títulos 
- Flexibilidade de horário 

## Requisitos

**Obrigatórios:**
- Experiência com tecnologias web abertas: HTML, CSS e Javascript
- Conhecimentos em Mobile First
- Conhecimentos em design responsivo
- Noções de design
- PHP Básico

**Desejáveis:**
- ReactJS
- Redux
- ES6
- Typescript
- CSS in JS
- Noções de UX

**Diferenciais:**
- Ter atuado em projetos open-source 
- Ter um blog ativo ou canal sobre tecnologia 

## Contratação

CLT

## Nossa empresa

Aqui na Superlógica somos líderes em recorrência em software para gestão de condomínios, anualmente organizamos diversos eventos grandes que impactam significativamente o mercado, como o [Xperience](https://xperience.superlogica.com/) que é o maior evento de recorrência da América Latina dentre outros.

Nossa cultura está em nosso DNA e isso tem nos ajudado muito no crescimento exponencial da empresa nos últimos semestres.

A Superlógica lhe dará a oportunidade de você expor suas idéias e desenvolver novas habilidades diariamente dentro de um modelo de gestão ágil e sem muitas burocracia.  

## Como se candidatar

Por favor envie um email para design@superlogica.com com seu CV anexado e LinkedIn.
Enviar no assunto: Vaga Front-end Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até uma semana.
E-mail para contato em caso de não haver resposta: rh@superlogica.com

## Labels

- Alocado
- CLT
- Júnior
- Pleno

**Comment by alessandrodias** [comment]
@deppbrazil somente presencial?

**Comment by deppbrazil** [comment]
@alessandrodias sim mano, apenas presencial.

**Comment by GustavoPrizon** [comment]
Cv enviado

**Comment by deppbrazil** [comment]
Encerramos nosso processo, agradecemos a todos que se candidataram e participaram, conseguimos um(a) candidato(a) que começa agora dia 01/10/2019 que se candidatou por aqui! :) 

Então vou fechar a issue! 

### Um carinho enorme por essa comunidade <3

**Comment by felipefialho** [comment]
Aeee, que legal @deppbrazil, sempre fico feliz quando chega nessas noticias.

Qual o nome dela? 😄

**Comment by deppbrazil** [comment]
A comunidade tem ajudado muito mano, 
o nome dela é @thayna-oliveira 
# 😃  #

**Comment by felipefialho** [comment]
Sensacional mano. Parabéns a empresa e a @thayna-oliveira 😄
