### ISSUE TITLE
[Belo Horizonte/MG] Desenvolvedor Front-End

### ISSUE THREAD

**Issue by carlosgpn** [frontendbr/vagas#231]
# Desenvolvedor Front End na Strider
**http://strider.ag**

Quer revolucionar a agricultura criando produtos de última geração junto com uma equipe extremamente talentosa? Como desenvolvedor Front End na Strider sua missão será criar interfaces elegantes para webapps, utilizando as últimas tecnologias do mercado. 

Estamos na vanguarda das companhias de AgTech no mundo e nossa missão é criar produtos e interações sem precedentes no mercado, gerando valor real na vertical de agricultura.
## Responsabilidades
Implementar aplicações web client-side, rápidas e fáceis de usar.
Desenvolver expertise nos softwares que compõem a plataforma Strider.
Desenvolver a compreensão do contexto dos clientes e do uso dos nossos produtos.
Criar interfaces internacionalizadas, uma vez que temos presença em diversos países.
Ser capaz de desenvolver habilidades em novas tecnologias para cumprir os objetivos do produto.
## Qualificações
Mínimas:
Experiência trabalhando com HTML5, CSS3 e JavaScript.
Experiência em desenvolvimento de webapps.

Desejável:
Conhecimento de tecnologias de desenvolvimento Front End, como AngularJS ou ReactJS.
Experiência em desenvolvimento de produtos.
Experiências de recursos para desenvolvimento web, como NPM/Webpack/Bower.
Desenvolvimento de software de alta complexidade técnica.

## About us
Strider is an AgTech startup that uses cutting-edge technology to enable farms to produce higher yields, using less resources, and consequently increasing profit in a way that is sustainable.
We make producers see their operations from an angle they had never seen before. In just 2 ½ years of operation, we are the agriculture industry leaders in the Brazil. We have 2,471,053 Acres being monitored in Brazil, Bolivia, Mexico, Australia, and USA, growing 20% per month and generating real savings in defensive Agro-Chemical costs for our customers.
Prepare to be part of a lean team (we are 40 people strong), who wants to revolutionize the way farms are managed, and help create the sustainable agriculture of the future.
## We are looking for people who
Are passionate about development and are ready and willing to meddle with any development challenge that crosses their path.
Have curiosity and have the willingness to learn… a lot, and fast!
Experiment with new technologies while maintaining alignment with emerging and existing architectures.
Develop effective, quality source code that satisfies customer needs with an exceptional experience
Code, test and deliver iterative minimally viable product features towards target customer and business outcomes
Work within modern architectures and frameworks while experimenting with newer technologies and tools which better enable your teams.
Solve problems together with experienced developers, product owners to truly satisfy customers.
Do not mind eating pizza and drinking beer one Friday a month with the entire team :D
## Reasons to join
Strider is backed by some of the finest VCs in Brazil: Monashees and Qualcomm, investors of 99Taxi, ContaAzul and VivaReal. Stability on the long-run.
Tech/product founders that value software quality and really understand technical debt. Zero tolerance for trash code.
Strong (100% product based) revenue stream and a fast growing business (20% month-over-month for the last 2 years). Strider is the leader on its market.
Using really cool technology and managing a large user base spread on many countries.
Zero-bullshit environment, no pointless meetings, straight communication, no clueless managers, office politics does not pay off.
Team of high-skilled and committed engineers you can learn a lot from.
Opportunity to influence the future direction of the products and systems used across the business and to move up in the organization.

**Comment by LFeh** [comment]
Alocado? CLT? PJ?

**Comment by carlosgpn** [comment]
@LFeh Isso!

**Comment by carlosgpn** [comment]
Vaga preenchida!
