### ISSUE TITLE
[Remote] Front-End Developer na [WIRE5]

### ISSUE THREAD

**Issue by lucasalbuquerque** [frontendbr/vagas#2312]
## Descrição da vaga

Vaga para você que manja muito de HTML e CSS e tem facilidade em transformar qualquer layout PSD em código.

Nós nos apegamos muito aos layouts de nossos clientes, seguimos a risca o que foi desenhado, esperamos isso de você.

## Local

Remoto

## Benefícios

- Bonus
- Auxilio com manutenção de ambiente de trabalho

#### Diferenciais

- Vaga 100% remota
- Horário flexível (o importante é cumprir os prazos)

## Requisitos

**Obrigatórios:**
- Possuir portfólio
- Conseguir transformar PSD em HTML e CSS Responsivo - PIXEL PERFECT

**Desejáveis:**
- conhecimentos básicos em JS
- conhecimentos em Jquery

**Diferenciais:**
- Wordpress

## Contratação

PJ a combinar

## Nossa empresa

Aqui na wire5 nós desenvolvemos Ecommerce, Sites, Landing Pages e Softwares sob encomenda, somos especializados em entregar soluções que realmente impactam no dia a dia dos nossos clientes.

## Como se candidatar

Por favor envie um email para projetos@wire5.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Developer - PIXEL PERFECT

## Tempo médio de feedbacks

Costumamos enviar feedbacks no mesmo dia após cada processo.
E-mail para contato em caso de não haver resposta: lucas@wire5.com.br

## Labels

- Remoto
- PJ
- Pixel Perfect
- PSD to HTML + CSS

**Comment by danielswater** [comment]
Eu acho que já mandei um email, acho que vc colocou essa mesma vaga no Facebook

**Comment by pedroffd** [comment]
Enviado!

**Comment by rodineicosta** [comment]
Enviado.

**Comment by hmilena** [comment]
Pode ser freela?

**Comment by fafa1** [comment]
Queria saber mais sobre a empresa, qual o site ?

**Comment by fafa1** [comment]
Queria saber mais sobre a empresa, qual o site ?

**Comment by EzequielBrilhante** [comment]
Enviado!

**Comment by luisfelipe-dev** [comment]
Enviado!
