### ISSUE TITLE
[Los Gatos/CA] Front-end Engineer na PayCertify

### ISSUE THREAD

**Issue by villander** [frontendbr/vagas#2317]
## SUMMARY:
Reporting to the Director of Engineering. This position was created to be part of our Engineering Team and help PayCertify create solutions to our systems so our company and clients can easily navigate - https://paycertify.com/

## QUALIFICATIONS:
 - 4+ years of experience designing and developing web applications with a solid understanding of HTML, CSS/SASS, JavaScript, REST and Web Sockets

- Speak English (You will be part of meetings with non portuguese speakers)

- Experience with EmberJS (preferred) 

- Experience with other JS Frameworks (Angular, React, Vue, etc.)

- Strong skills with object-oriented programming and test-driven development 

- Initiative and a passion for all things web and a willingness to learn new skills and technologies

- Thorough knowledge of best responsive development practices

- Awareness of cross-browser compatibility issues and client-side performance considerations

- Experience working in iterative, agile development environments

## ORGANIZATION STRUCTURE & POSITION:
- The Software Engineer will work remotely

- The Software Engineer reports to the Head of Quality

- Full Time position (w/ 90-day probation period)

- Semi-monthly payroll (paid on the 1st& 15th of each month)

- Competitive Salary/Bonus/Commission structures

- Benefits Program

- Remote capabilities

## HOW APPLY
To apply, email your CV, linkedin and github link for this role to michael@paycertify.com

## ABOUT PAYCERTIFY:

**A healthy environment**: We are proud of everything we create, including our working environment. Our culture is built on values ​​that reinforce our commitment to respecting differences, creating a safe and reliable environment.

**Multidisciplinary team**: PayCertify's team is made by professionals from many different areas, such as Engineering, Data Specialists, Developers, Marketers and Designers that create a unique place for sharing information that leads to professional and personal development.

**Diversity as a trademark**: We care about each other. At the end of the day, that's what really makes the difference in our lives - respect, trust, and reliability. In a diverse environment, everyone plays a unique role that contributes to personal growth.

**Support as a rule**: Regardless of the position held in PayCertify, everyone shares the same commitment - assisting in the development of the skills of every colleague, creating a support network.

**Comment by villander** [comment]
O trabalho é remoto @MrS4w ; )

**Comment by diegoarcega** [comment]
Alguem sabe se tem que dar suporte a sistema em ember? Na descrição parece que sim  mas podem estar com projetos novos e etc... 

Também alguem sabe com quais frameworks atualmente eles trabalham?

**Comment by villander** [comment]
@diegoarcega Nós usamos Ember.js como stack principal mas também usamos outros frameworks quando necessário (temos projetos em Vue e React por exemplo), essa vaga é pra trabalhar especificamente com Ember. E como todo produto já existente ele precisa ser mantido, corrigido e aperfeiçoado, que é a basicamente *Reliability*. Mas também há novas features para ser desenvolvida.

**Comment by LukasTsunami** [comment]
Não sei pq o pessoal tem medo de Ember... É o framework com melhor documentação no mercado

**Comment by pedroch4610** [comment]
Olá! Eu ainda estou no inicio do aprendizado do inglês, mas eu poderia fazer o teste apenas como forma experiência?

**Comment by diegoarcega** [comment]
@villander obrigado pela resposta. No meu ponto de vista acho dificil manter em uma empresa diferentes frameworks, existem boas praticas especificas que sao dificeis manter across projects, nao quero convencer ninguem, soh desabafando. :)

**Comment by villander** [comment]
Exatamente @diegoarcega, para manter 3 projetos com diferentes frameworks é sempre bom ter um expert em cada uma das tecnologias, mas isso não impede do seu atual time se tornar expert em 2 ou mais frameworks basta treina-lo.

Nosso maior intuito é em trazer engineers bons, isto é que tenha um bom background do ecossistema front-end (ser muito bom em JS, html e css) e que esteja confortável em escrever código testado,  que seja referência em projetos open source e domine muito bem arquitetura de software. 

Tecnologia é só uma parte da coisa, um bom engenheiro de software é bom em qualquer lugar. Basta dar tempo pra ele aprender a tecnologia, que é um obstaculo pequeno dentro do mundo da engenharia de software (Automated tests, separation of concerns, scalability, clean code, design patterns, relationship, performance and etc).

Nós seguimos a mesma cultura de contratação que as grandes como Apple, Netlix e Linkedin: Onde as skills técnicas e de comportamento pessoal valem muito mais que um conhecimento especifico em framework A ou B.

**Comment by fernandamaiait** [comment]
Nossa, agora vc falou bonito @villander ... e falou tudo!

Faz mais de 15 anos que eu programo e se tem uma coisa que eu aprendi é: o cara que é bom em uma linguagem de programação será bom em todas as outras! 
O que escreve código porco, é preguiçoso, descomprometido e reclamão, vai ser assim em todas as linguagens e em todas as empresas que estiver, e talvez pra sempre...

Não contratem o cara que sabe programar naquela linguagem, contratem o bom programador, animado, com brilho nos olhos, curioso, auto-didata. Esse é o cara! 

Fico aliviada que tem gente no mercado brasileiro já pensando assim! =)

**Comment by diegoarcega** [comment]
@villander entendo este ponto de vista, eh legitimo e se aplica em determinados casos sem problema. 


Gostaria de comentar sobre um outro lado. Em uma empresa, no entanto, se faz necessario balancear o custo beneficio dos seus recursos de forma inteligente. A PayCertify certamente tem budget para pagar um desenvolvedor deste nivel que voce comentou, porem, nao eh o caso da maior parte das empresas. Um perfil como voce mencionou acredito que o salario esta cerca de quase ou mais de 100K USD. Este perfil de desenvolvedor que voce comentou tambem eh significantemente mais dificil de encontrar no mercado e mesmo que encontre nao eh garantido que nao vao fazer bagunca ou que vao aplicar as boas praticas, na maior parte do tempo nao ha como esses super devs aplicarem boas praticas desde o inicio, por isso vejo como arriscado essa aposta no super dev, o processo seletivo deve ser bem criterioso para evitar esses problemas comuns.


O dev pode ter a capacidade de trabalhar com diferentes tecnologias, porem, acho muito dificil seguir o que ha de mais novo e seguir todas as boas praticas daquela tecnologia, especialmente falando em javascript, existem muitos detalhes muito relevantes. 

Sobre a vaga em especifico acredito que pelo fato de ja existirem varios frameworks (3) na empresa, se faz necessario um dev com esse perfil mais dinamico, mas se for para projeto novos recomendo um especialista com mais experiencia.  "just my two cents..."

**Comment by halkliff** [comment]
CV enviado! Acredito que me encaixo no perfil.

**Comment by villander** [comment]
> Olá! Eu ainda estou no inicio do aprendizado do inglês, mas eu poderia fazer o teste apenas como forma experiência?

Pode sim @pedroch4610

**Comment by felipefialho** [comment]
> Exatamente @diegoarcega, para manter 3 projetos com diferentes frameworks é sempre bom ter um expert em cada uma das tecnologias, mas isso não impede do seu atual time se tornar expert em 2 ou mais frameworks basta treina-lo.
> 
> Nosso maior intuito é em trazer engineers bons, isto é que tenha um bom background do ecossistema front-end (ser muito bom em JS, html e css) e que esteja confortável em escrever código testado, que seja referência em projetos open source e domine muito bem arquitetura de software.
> 
> Tecnologia é só uma parte da coisa, um bom engenheiro de software é bom em qualquer lugar. Basta dar tempo pra ele aprender a tecnologia, que é um obstaculo pequeno dentro do mundo da engenharia de software (Automated tests, separation of concerns, scalability, clean code, design patterns, relationship, performance and etc).
> 
> Nós seguimos a mesma cultura de contratação que as grandes como Apple, Netflix e Linkedin: Onde as skills técnicas e de comportamento pessoal valem muito mais que um conhecimento especifico em framework A ou B.

Quero deixar minhas 👏👏👏👏👏 pra vocês

**Comment by villander** [comment]
Já contratamos a pessoa desejada!

mas estou abrindo novamente nosso processo seletivo, a demanda na empresa aumentou ; )

**Comment by bconfortin** [comment]
@villander As reviews da PayCertify são bem ruins no Glassdoor. A nota é 2.1 e parece que ninguém gosta do CEO. Qual é a sua visão, já que você trabalha lá? É isso mesmo ou é um ambiente legal para se trabalhar?

**Comment by halkliff** [comment]
@villander eu já havia enviado um currículo, mas não obtive resposta, estou re-enviando.

**Comment by mrangel-jr** [comment]
@villander , Está aberto ainda ? Eu mandei meu CV mas não tive retorno.

**Comment by gabriel-brito** [comment]
Aguardando resposta! :D

**Comment by villander** [comment]
Mandamos feedback pra todos, desculpa a demora pessoal. Recebemos uma quantidade de aplicações inesperadas ; )
