### ISSUE TITLE
[São Paulo] Pessoa desenvolvedora Front-End

### ISSUE THREAD

**Issue by oPorks** [frontendbr/vagas#232]
## Descrição da vaga

Características:
Corajosa;
Não resistente a realizar testes;
Curiosa e gosta de aprender;

Perfis que desejamos:
Perfil Devops: manja de Linux e de configurar ambientes de desenvolvimento; ou
Perfil UX: manja das heurísticas de Nielsen e se interessa pelo assunto; ou
Perfil Tester: manja planejar e executar um bom teste;

Para:
O desenvolvimento do produto com o cliente ainda está para começar, criamos um protótipo com Design Thinking e agora vamos trabalhar com Scrum para implementar. O produto será desenvolvido em AngularJS 2 e não abrimos mão da qualidade.

## Local

Escritório, São Paulo - Interlagos

## Requisitos

**Obrigatórios:**
- AngularJS: mínimo de um ano de experiência;
- Git;
- HTML5;
- CSS3;

**Desejáveis:**
- Vivência em ambiente ágil

**Diferenciais:**
- Práticas de eXtreme Programming: Pair Programming, Code Review, Clean Code, Refatoração, BDD, TDD, Design Patterns;
- Jasmine;
- Jenkins;
- SOLID;
- NPM / Bower;
- Grunt / Gulp;

## Contratação

CLT a combinar

## Nossa empresa

MJV Inovação e Tecnologia - Pioneira em Design Thinking no Brasil.

## Como se candidatar

Por favor envie um email para rafael.queiroz@mjv.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

**Comment by oPorks** [comment]
Temos vaga para Junior, Pleno e Senior

**Comment by jvcjunior** [comment]
Vaga muito  interessante. Nenhuma possibilidade de remoto @oPorks ?

**Comment by oPorks** [comment]
@jvcjunior infelizmente, não :/
