### ISSUE TITLE
[São Paulo - Presencial] Front-end Developer na SOLFÁCIL

### ISSUE THREAD

**Issue by johann-sothen** [frontendbr/vagas#2327]
## Qual é o desfaio?
Precisamos de um profissional para reforçar a arquitetura da nossa plataforma fintech de energia solar de uma forma modular com alto nível de manutenção e baixo custo de desenvolvimento. 

Nos próximos meses iremos executar novas features como automatizações de processos (APIs com sistemas terceiros), otimização de um modelo próprio de análise de crédito, implementação de modelos de dashboards/relatórios, aplicações de iOT com hardwares próprios da empresa e monitoramento dos sistemas de energia solar financiados, etc.

## Quem estamos buscando?
Estamos buscando um profissional comprometido, autônomo e autodidata para ser o principal desenvolvedor front-end. Ainda estamos em um estágio de evolução na parte de front, então sugestões de frameworks ainda são bem-vindas! 

Nosso maior foco hoje será no desenvolvimento da plataforma web estilo marketplace onde empresas instaladoras de placas solares parceiras podem fazer demandas de financiamentos de sistemas solares e acompanhar suas ofertas de orçamento e o andamento de seus projetos.

## Quais são os requisitos?
- Excelente conhecimento de Javascript e/ou CSS3 e/ou HTML5.
- Domínio de engenharia de software, princípios, boas práticas e padrões de arquitetura
- Gostar de programar
- Interesse por aprender novas linguagens e tecnologias
- Paixão por desenvolvimento de produto
- Vontade de trabalhar em ambiente de rápida evolução
- Formação em Engenharia da Computação, Ciência da Computação ou demonstrar conhecimento equivalente
- Experiência com frameworks modernos de front-end como React, Angular ou Vue (ou mais antigos como Bootstrap) é muito bem vinda.

## Diferenciais
- Participar do estágio inicial de uma empresa de crescimento exponencial
- Escrever código que impactará a vida de milhares de pessoas
- Trabalhar com desenvolvimento de software em metodologia agile
- Pensar e propor soluções para o produto 

## Quem somos?
A Solfácil é a primeira FinTech brasileira que nasceu com o objetivo de democratizar o acesso à fonte de energia solar fotovoltaica, facilitando o financiamento de sistemas solares para lares e empresas de todo o país. Estamos revolucionando o ramo de energia solar no Brasil (que tem um potencial multi-bilionário) e passando por um momento de crescimento bastante acelerado! Precisamos de pessoas boas para atingir nossos objetivos ambiciosos!

## Local
Escritório em São Paulo - Vila Leopoldina

## Como se candidatar

Por favor envie um email para johann.sothen@solfacil.com.br com seu CV anexado e outros conteúdos relevantes (portfólio, GitHub, etc.) - enviar no assunto: Vaga Front-end

## Labels
- Presencial
- CLT
- PJ
- Pleno

**Comment by halkliff** [comment]
@johan-sothen Achei bem interessante o perfil da vaga, mas no momento eu só posso me candidatar caso aceitem remoto, estão aceitando?

**Comment by ribeiroevandro** [comment]
Email enviado!
