### ISSUE TITLE
[São Paulo - Berrini] Web Design (PL ou SR) - K2 Partnering

### ISSUE THREAD

**Issue by natashacosta** [frontendbr/vagas#2328]
Oi, pessoal!
Tudo bem? 

Sou Tech Recruiter na **K2 Partnering**, consultoria de recrutamento e seleção britânica, presente em 19 países, há mais de 20 anos. 

Temos uma vaga de **Web Design PL ou SR** para atuar num cliente, na Berrini. Este cliente é uma instituição máxima de organização do setor industrial brasileiro. A parceria seria PJ, com a K2, 2 meses + renovação. Por ser PJ, a renovação vai acontecendo, levando em consideração o trabalho árduo de não perdemos nossos melhores consultores. E sempre buscamos os melhores! :)

**Pré-requisitos:**

- Experiência com HTML, CSS, Javascript, Angular ou React, Node.js
- Experiência com metodologia ágil;
- Portfólio comprovado em digital;
- Domínio de softwares gráficos e de edição de imagens, de animação e apoio à qualquer etapa de desenvolvimento dos produtos;
- Domínio em arquitetura de informação, implementações de acessibilidade e comportamento online do usuário.
- Conhecimento em UX e UI.

**Atividades:**

- Responsável pela programação visual dos sistemas e aplicações criando layouts e templates reutilizáveis, observando os princípios de usabilidade, responsividade e a identidade visual, entre outros.

Tem interesse? Me procura!!

ncosta@k2partnering.com

**Comment by ribeiroevandro** [comment]
Email enviado!
