### ISSUE TITLE
[Campo Bom/RS] Analista Front-end

### ISSUE THREAD

**Issue by andersonaguiar** [frontendbr/vagas#233]
Fala galera, tudo certo?

Seguinte, a AREZZO&CO está com uma vaga aberta para Analista Front-end para trabalhar aqui em
Campo Bom/RS nos e-commerces de SCHUTZ(https://schutz.com.br), AREZZO(https://arezzo.com.br) e 
Anacapri(https://anacapri.com.br).

Skills para a vaga:

- Dominar Javascript sem libs/frameworks (conhecimento da linguagem)
- ES6
- CSS3 + pré-processadores SASS/Stylus / responsive design
- HTML5
- Require.js/webpack

Plus:

- React.js
- Backbone.js

Quem tiver interesse, ou souber de alguém que se encaixaria no perfil, pode me encaminhar o currículo
através do email anderson.aguiar@arezzo.com.br ou pode me chamar via inbox.

Obs: O salário está acima do oferecido no mercado e o horário é BEM flexível (:

**Comment by JoaoPauloCMarra** [comment]
Olha só, aceitam remoto(ou com disponibilidade de mudança)? (Goiânia-GO)

**Comment by andersonaguiar** [comment]
A vaga é alocado. Aceitamos mudança sim.

**Comment by LFeh** [comment]
PJ? Alocado? Qual nivel?

**Comment by andersonaguiar** [comment]
Alocado. CLT. Técnico e/ou Faculdade(pode ser formado ou em andamento). O importante é mostrar que domina JS (:

**Comment by andersonaguiar** [comment]
@LFeh no mínimo pleno. A vaga é pleno/sênior

**Comment by diogomoretti** [comment]
@LFeh arrumei as labels =]

**Comment by Finacio** [comment]
@andersonaguiar Estou interessado na vaga, mas sou de são paulo, tem algum problema? estou disposto a me mudar!

**Comment by andersonaguiar** [comment]
@Finacio, problema algum. Pode mandar seu CV se tiver interesse. :)

**Comment by gabrielferreiraa** [comment]
Pode ser Remoto?

**Comment by andersonaguiar** [comment]
Não. Alocado.
