### ISSUE TITLE
[Brasília - DF] Desenvolvedor Fullstack Django VueJS

### ISSUE THREAD

**Issue by wagnerjs** [frontendbr/vagas#2330]
# Descrição da vaga

- Desenvolver e testar aplicações single page application usando VueJS
- Desenvolver e testar Web API usando Django Rest Framework
- Trabalhar em atividades de operação das aplicações (CI/CD)
- Realizar revisão de código e pareamentos
- Seguir boas práticas de desenvolvimento Ágil com Scrum

# Local 

Brasília - DF

# Requisitos

- Experiência com Django/Django Rest Framework
- Linguagem de programação Javascript
- Experiência com Framework (Javascript Single Page Application) ou outros
- Conhecimento de Padrão de Gerenciamento de Estado (State Management Pattern)
- Conhecimento nos padrões do ES6
- Consumo de APIs REST

# Diferencial

- Pré processador de estilos SASS
- Conhecimentos em bibliotecas de Data Visualization
- JEST
- Elasticsearch

# O que oferecemos

Remuneração competitiva, Bônus por desempenho, Ambiente inovador e de entretenimento. Plano de Saúde e Dental. Vale Alimentação/Refeição, convênio com instituição de idiomas, academia e o SESC. Horário flexível.

# Como se candidatar

Envie o seu currículo para o e-mail rhtalentos221@gmail.com no campo assunto informar: DEV FULLSTACK e informe pretensão salarial.

**Comment by luizfpinheiro** [comment]
@wagnerjs Essa vaga ainda está aberta? Tenho interesse!
