### ISSUE TITLE
[BARUERI/ALPHAVILLLE] Front-end Developer na DRY COMPANY do BRASIL

### ISSUE THREAD

**Issue by caiosalim** [frontendbr/vagas#2336]
## Descrição da vaga

DRY COMPANY BRASIL contrata Desenvolvedor(a) Front-end com conhecimentos sólidos em HTML, CSS E JS.
O Profissional irá atualizar em framework próprio baseado no bootstrap, utilizando muito jQuery, Phonegap e HTML e CSS

## Local

Barueri Alphaville - Alameda Araguaia, 2044, Alphaville, Barueri, SP

## Benefícios

- Estou ainda levantando os benefícios com o RH. Como a vaga é PJ 

## Requisitos

**Obrigatórios:**
- Saber bem javascript e jQuery, trabalhar com Promises, ajax, etc. 
- ter alguma experiência com Node 

**Desejáveis:**
- Phonegap, processo de publicação em loja, etc.
- Que tenha alguma facilidade com ux/ui e webdesign

## Contratação

PJ a combinar

## Nossa empresa

Dry Company do Brasil é uma empresa nova e está entrando no ramo de telecom.
A proposta é trabalhar os webapps, sites e sistemas que permeiam este meio.

## Como se candidatar
Por favor envie um email para caio.salim@gmail.com com seu CV anexado - enviar no assunto: Vaga DRY COMPANY BRASIL

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 ou 3 dias após cada processo.

## Labels

- Alocado
- PJ
- WebApp

**Comment by klisostom** [comment]
Pode ser remoto ou só presencial mesmo? De quanto vai ser o valor da contratação?

**Comment by caiosalim** [comment]
Bastante presencial.
Preciso que a pessoa crie sinergia com a empresa e produtos!
