### ISSUE TITLE
[São Paulo - SP] Front-end Developer na Foco em Você

### ISSUE THREAD

**Issue by kvilela** [frontendbr/vagas#2344]
A Foco em Você está auxiliando um cliente na busca por Front-end Developer.

O profissional irá desenvolver softwares para seguradora e planos de saúde, irá atuar (futuramente) com desenvolvimento e implantação da LGPDP - Lei Geral de Proteção de Dados Pessoais.

Venha ser protagonista da sua carreira!

**Local**
São Paulo - Vila Gertrudes (Morumbi Shopping) 

**Benefícios**
Convênio Médico e Odontológico Porto Seguro
Vale Refeição R$ 33,00/dia
Vale Transporte e Seguro de vida
Cursos Alura 

**Requisitos
Obrigatórios:**

Experiência em desenvolvimento Front End (HTML, CSS, JS)
WEBPACK
Versionamento com GIT
API

**Contratação**
CLT

Por favor envie um e-mail para karina.vilela@focoemvoce.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Developer

Labels
CLT
Junior
Pleno

**Comment by GustavoPrizon** [comment]
Cv enviado!
