### ISSUE TITLE
[Brasília] Front-end Developer na MONEY CLOUD TECNOLOGIA LTDA. 

### ISSUE THREAD

**Issue by Alopes-web** [frontendbr/vagas#2348]
## Descrição da vaga

O que você precisa saber:
Vue.js;
REST;
Git;
CSS3 (BEM; Layouts - floats, positioning, display, box model, grid, flex box; Media queries);
HTML5 (Semantic, SEO, accessibility);
Javascript (DOM; Fetch/Ajax/XHR; modular construction);
Linux (terminal - commands and tools);

O que seria legal você saber:
ReactJS;
Redux/Saga;
SASS;
Javascript (ES6+; Hoisting; Event Bubbling; Scope Prototype; Shadow DOM; strict; DNS; HTTP);
SPA;
Package managers (yarn/npm);
Linters e formatters (eslint/prettier);
Tests (unit, integration, functional);
Design patterns; KISS; DRY; YAGNI; SOC; SOLID;

Competências necessárias:
Solucionador de problemas; comprometido com prazos;
Orientado a resultados;
Adaptável.

## Local

Brasília - DF

## Requisitos

- Experiência prévia comprovada. 

**Desejáveis:**
- conhecimentos em ruby on rails
- conhecimentos em C#

## Contratação

PJ a combinar

## Como se candidatar:

Por favor, envie um email para alopes@moneycloud.com.brr com seu CV anexado - enviar no assunto: Vaga FRONT-END

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.

**Comment by rodrigorhas** [comment]
Enviado. Requisitos bem definidos.
