### ISSUE TITLE
[São Paulo] Desenvolvedor Front-end @ AMARO

### ISSUE THREAD

**Issue by cassiocardoso** [frontendbr/vagas#235]
# Descrição da vaga

Estamos em busca de um desenvolvedor front-end (júnior/pleno/sênior) para integrar o nosso time. Buscamos alguém que já trabalhe na área e possua conhecimentos em desenvolver sites responsivos e e-mail marketing. E que queira aprender novas tecnologias como React e Redux que são a base da nossa nova plataforma de e-commerce.

# Local

Rua Antonio Nagib Ibrahim, Água Branca, São Paulo/SP

 # Responsabilidades

- Trabalhar junto ao time criativo para criar e implementar novos layouts para e-mail marketing.
- Desenvolver novos componentes que serão integrados à nossa plataforma de e-commerce.
- Colaborar com os times de UX e Marketing para planejar, prototipar e construir novas interfaces.

# Requisitos

## Obrigatórios:

- Habilidade de criar layouts utilizando ferramentas modernas (Pré-processadores, frameworks JavaScript, automatizadores de tarefas).
- Bom conhecimento de JavaScript nativo (consumir uma API e renderizar os dados na tela).
- Experiência com Git.
- Saber trabalhar em grupo.

## Diferenciais:

- Experiência com React (já ter feito algum projeto open-source ou ter usado no ambiente de trabalho).
- Conhecimento em TDD (Test-driven development).
- Experiência em um ambiente de desenvolvimento ágil.

## Contratação

- CLT (3k a 6k - dependendo da experiência)

## Benefícios

- VR (ou restaurante na empresa)
- VT
- Plano de saúde
- Gympass
- Desconto em produtos AMARO

## Nossos Diferenciais

- Futebol na sexta-feira.
- Happy hour com cervejas artesanais.
- Não precisa dar suporte ao IE.

## A AMARO

AMARO é uma marca online de moda feminina com sede em São Paulo. Lançamos coleções mensais com as últimas tendências de moda a preços acessíveis, entregues rapidamente, em grande estilo. Através de tecnologia de ponta, integração vertical e distribuição omni-canal, a AMARO está mudando a forma como os brasileiros consomem moda.

Todos os dias nos desafiamos para encantar nossos clientes com uma variedade de produtos sempre em renovação, com as últimas tendências da moda, a preços acessíveis. Tudo isso, entregue de forma rápida e em grande estilo.

## Como se candidatar

- Acesse nosso [repositório no GitHub](https://github.com/amarofashion/front-end-challenge) e leia as instruções do desafio.
- Resolva o desafio, preste atenção nos requisitos e nos pontos extras.
- Submeta um pull-request e nós avaliaremos seu trabalho.

**Comment by cassiocardoso** [comment]
Pessoal, estamos com mais uma vaga aberta para desenvolvedor front-end na AMARO. A vaga é presencial. E avaliaremos candidatos de nível júnior a sênior para integrar nosso time.

**Comment by LFeh** [comment]
Boa vaga @cassiocardoso, boa sorte!

**Comment by felipem1511** [comment]
Bela vaga, bem justa.

Gostei da atitude no teste, kkkk Separando os homens das crianças
> This is a challenge, not a college test, so there's multiple correct answers.

Gostaria de me aplicar, mas estou com dificuldade de me mudar para São Paulo. Mas o desafio vou ficar de experiência.

Boa sorte!

**Comment by rubenmarcus** [comment]
Não precisa dar suporte ao IE.  :ok_hand: :ok_hand:

**Comment by LFeh** [comment]
Alias, curto muito vaga nessa pegada. Tem o teste lá, a pessoa pode aplicar antes de até mesmo entrar em contato com a empresa.

**Comment by cassiocardoso** [comment]
Obrigado galera.

A idéia do teste é essa, assim a pessoa já tem uma noção melhor do que vai trabalhar no dia a dia aqui com a gente e podemos analisar como ela resolve problemas. Já é uma boa maneira de ambos os lados verem se faz sentido seguir no processo ou não.

**Comment by gabrielferreiraa** [comment]
Vagona!

**Comment by uselessdev** [comment]
Essa vaga é sensasional :heart:

**Comment by siqueiradg** [comment]
Adorei a vaga!

**Comment by Felipesdeveloper** [comment]
Parabéns em, Gostei bastante da Vaga, principalmente da parte "Não precisa dar suporte ao IE." hahahaha

**Comment by cassiocardoso** [comment]
Apenas um update aqui:
- Vamos aceitar os PR's até o dia **10/02** pois queremos que o novo dev comece aqui no início de março.
