### ISSUE TITLE
[São Paulo] Front-End Developer na SUPERARE

### ISSUE THREAD

**Issue by w3solution** [frontendbr/vagas#2353]
## Descrição da vaga

Estamos contratando desenvolvedores front-end para fazer parte de nossa equipe. O profissional precisa ser comprometido, empenhado, dedicado e ser lunático por tecnologia. 

## Local

Escritório, São Paulo - Chácara Santo Antonio 

#### Diferenciais

- Ambiente descontraído

## Requisitos

**Obrigatórios:**
- HTML
- CSS
- Javascript
- Bootstrap
- SASS / LESS
- Experiência em "algum" framework de mercado ( Angular, React & VueJs )
- Wordpress
- Photoshop
- API integration ( REST ) 
- GIT

**Desejáveis:**
- PHP 
- NodeJS
- GraphQL
- Conhecimentos em Linux

## Contratação

a combinar

## Nossa empresa

A Superare sempre olhou para o futuro com uma metodologia de trabalho bem definida: aqui, todo o processo é baseado em 
resultados, sem achismos. Isso quer dizer que em tudo tem Analytics. Nada é planejado, criado e produzido sem que os resultados 
sejam analisados em todas as etapas.

O retorno é o melhor que poderíamos ter: em pouco tempo de atuação, deixamos de ser apenas uma empresa de tecnologia para 
atuarmos como agência digital, além de sermos uma das primeiras parceiras do Facebook (inclusive, fizemos o bot deles) e uma 
das principais parceiras de gigantes mundiais como Google, Microsoft e Newspace.

Como conseguimos ir além em apenas 6 anos? Fazendo um constante esforço de inovação, criando produtos e estratégias focados 
em resultados e usando a tecnologia para fazer a diferença na vida das empresas e das pessoas.

## Como se candidatar

Por favor envie um email para eric@superare.co com seu CV anexado + LinkedIn - enviar no assunto: Vaga: Front-End Developer

## Labels

- Alocado
- Júnior
- Pleno

**Comment by GustavoPrizon** [comment]
Cv enviado

**Comment by stochiconrado** [comment]
A vaga ainda está disponível?

Em qui., 12 de set. de 2019 às 09:28, N3R00 <notifications@github.com>
escreveu:
