### ISSUE TITLE
[Joinville/SC, Florianópolis/SC ou REMOTO] Front-end Developer na Codenation

### ISSUE THREAD

**Issue by eminetto** [frontendbr/vagas#2359]
## Descrição da vaga

Front-end Developer na Codenation

## Local

Joinville/SC, Florianópolis/SC ou remoto

## Benefícios

- VR (ou VA, vc escolhe) no valor de R$ 25,00/dia
- VT
- Plano de saúde (desconto de mensalidade de acordo com faixa etária, sem coparticipação)
- Uniodonto

## Requisitos

**Obrigatórios:**
- Conhecimentos avançados em JavaScript
- Conhecimentos básicos em frameworks como React, Angular ou Vue
- Conhecimento prático em HTML5 e CSS3 Responsivo
- Conhecimentos em Git (branches, Pull Requests)
- Experiência de trabalho com APIs, ou integrar uma API de terceiros 
- Conhecer pré-processadores CSS como Less, Sass e Stylus;
- Experiência com sistemas de build (Bash, Grunt, Make, webpack)

**Desejáveis:**
- Inglês técnico, pelo menos para leitura
- Interesse em aprender novas tecnologias, linguagens de programação e ambientes de desenvolvimento

## Perfil esperado

- Disciplina e organização é fundamental;
- Sedento por conhecimento;
- Traz críticas em relação a ferramentas utilizadas, com o objetivo de melhorar o desenvolvimento;
- Pesquisador, trazendo novidades que podem ser realmente aplicadas nos projetos;
- Senso crítico;
- Engajamento com a equipe, para crescimento sustentável de todos.

## Contratação

CLT

## Nossa empresa

[Sobre a Codenation e nossa tecnologia](https://speakerdeck.com/eminetto/sobre-a-codenation)

## Como se candidatar

Por favor envie um email para tech@codenation.dev com seu CV anexado - enviar no assunto: Vaga Front-end Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 semanas após cada processo.
E-mail para contato em caso de não haver resposta: elton.minetto@codenation.dev

## Labels

- CLT
- Remoto

**Comment by alessandrodias** [comment]
O email para envio do CV não seria:

> tech@codenation.dev

**Comment by MoraesGil** [comment]
tem opção de candidatar via linkedin ?

**Comment by eminetto** [comment]
> tem opção de candidatar via linkedin ?

@MoraesGil por enquanto estamos aceitando apenas por email. Se puder mandar mensagem com seus dados fica mais fácil para nós
Vou organizar para que as próximas vagas aceitem esse formato de submissão. Obrigado pela sugestão
