### ISSUE TITLE
[remoto] Vaga AngularJS/Ionic 1 Junior/Pleno

### ISSUE THREAD

**Issue by rxluz** [frontendbr/vagas#236]
## Descrição da vaga

A Appock é uma fabrica de apps localizada em São Paulo que possui 7 prêmios de inovação e empreendedorismo nos últimos 18 meses, nos estamos procurando dois frontends junior/pleno que tenha um bom conhecimento em html/css/sass/responsividade e ionic 1 e angularjs 1

## Local

Remoto

## Benefícios

- Horário e dias de trabalho totalmente flexível

## Requisitos

**Obrigatórios:**
- 6 meses de experiência com Ionic (ou ter algum projeto bacana pra mostrar)
- Conhecimentos sólidos em HTML/CSS/SASS
- nível pelo menos intermediário de inglês

**Desejáveis:**
- conhecimentos em angular 2
- conhecimentos em ionic 2

**Diferenciais:**
- projetos opensource

## Contratação

PJ

## Como se candidatar

Por favor envie um email para rx@appock.co com seu CV anexado - enviar no assunto: Vaga Ionic/Angular

**Comment by LFeh** [comment]
Fechou?

**Comment by paulovitorwd** [comment]
Enviei, mas não tive resposta.

**Comment by rxluz** [comment]
Oi pessoal, já contratei os devs para essas vagas, obrigado quem enviou o CV, havendo uma nova leva de contratação eu entro em contato, abcs
