### ISSUE TITLE
[São Paulo] Front-End Developer no Grupo Netshoes

### ISSUE THREAD

**Issue by tonimota** [frontendbr/vagas#2360]
## Descrição da vaga

Estamos a procura de um profissional que #rompapadrões, que tenha **#foco** no resultado e que tenha **#tesãoporfazer**  sempre o melhor! Tá afim? :-)
Então dê uma olhada no perfil abaixo e venha fazer parte de um dos maiores e-commerces da América Latina!  \o/

Aqui você vai:

- Trabalhar em times ágeis e autônomos, participar das cerimônias e discutir soluções técnicas;
- Desenvolver aplicações e resolver problemas com foco na melhor solução para o cliente;
- Zelar pela qualidade dos produtos por meio da criação de testes automatizados e revisão de código e subir o produto em ambiente de produção por meio de integração contínua.

## Local

Ficamos localizados na Rua Vergueiro, 943, próximo ao metrô Vergueiro!

## Benefícios

- Vale Refeição :-)
- Vale Alimentação
- Assistência Médica: Notredame Intermédica.
- Assistência Odontológica: BBDental.
- Vale Transporte
- Day Off, descanso merecido no dia do seu aniversário \o/
- Horário Flexível! 
- Participação nos Lucros e Resultados;
- Desconto em Produtos;
- Previdência Privada;
- Parceria com Gympass, mexa-se!
- Parceria  com o Cartão Funcional;
- Parceria com Faculdades, você sendo protagonista do seu conhecimento!

## Requisitos

- Superior Completo;
- Conhecimento em HTML;
- CSS3;
- SASS;
- JAVASCRIPT (ES6);
- Nodejs;
- Webpack;
- Gulp;
- Angular/React/Vue
- Mocha/Jest

## Contratação

CLT Full

## Como se candidatar

E aí? Gostou?! Então que tal juntar-se ao nosso time?! ;-)
Envie um e-mail com link do github e do seu linkedin para **marcelo.paparelli@netshoes.com**

## Labels

- Presencial
- CLT
- Pleno

**Comment by dezzasalmeida** [comment]
Opa @tonimota, tenho interesse na vaga :)

**Comment by maxarouca** [comment]
Opa @tonimota, somente presencial ou aceitam remoto?

**Comment by tonimota** [comment]
> Opa @tonimota, somente presencial ou aceitam remoto?

Fala @maxarouca, no momento, apenas presencial ;)
