### ISSUE TITLE
[São Paulo] Desenvolvedor(a) FrontEnd na Zup Innovation

### ISSUE THREAD

**Issue by pedroferreirazup** [frontendbr/vagas#2363]
## Empresa
 A Zup desenvolve produtos digitais disruptivos que impactam a vida de milhares de usuários. Acreditamos em ambientes ágeis, autogerenciáveis e flexíveis. Por isso, contratamos somente os melhores profissionais. Crescemos mais de 30 vezes nos últimos cinco anos, já somos mais de 850 zuppers e estamos em seis cidades.

**Importante:** acreditamos que profissionais fora da curva estão em todos os lugares. Por isso, todas as nossas vagas são abertas a qualquer pessoa, independente de cor, gênero, orientação sexual, identidade de gênero e/ou pessoas com deficiências.

## Quem é você?

Uma pessoa que gosta de ser desafiada e quer fazer parte de projetos que estabelecem um novo curso para a história das maiores empresas do Brasil. Gosta de trabalhar com autonomia, sabe se adaptar a qualquer ambiente e nunca desiste. Aqui na Zup, também valorizamos profissionais que disseminem conhecimento e trabalhem bem em equipe.

## Descrição da vaga
- Possuir disponibilidade de atuação em projetos vários
- Possuir foco em disseminar o conhecimento
- Ser organizado tendo vistas o trabalho em equipe
- Ser atento a pequenos detalhes
- Facilidade de relacionamento

## O que você fará na Zup:

Desenvolvimento dos produtos mais inovadores do mercado atuando no desenvolvimento de softwares de alta performance, além de trazer críticas, novas ideias e ferramentas, com o objetivo de melhorar o desenvolvimento e experiência do usuário.Realização de code reviews. Identificar e trabalhar na escalabilidade, reusabilidade, performance e segurança das aplicações.

Importante: acreditamos que profissionais fora da curva estão em todos os lugares. Por isso, todas as nossas vagas são abertas a qualquer pessoa, independente de cor, gênero, orientação sexual, identidade de gênero e/ou pessoas com deficiências.

## Requisitos

- Angular 2+
- TypeScript
- SASS
- HTML / CSS
- JavaScript
- NPM ou yarn (para gerenciamento de pacotes/bibliotecas javascript)
- Repositórios: GIT (Hub/Lab/Flow); e/ou TFS/ VSTS

## Como me destaco para esta vaga?

- AngularJs 1.5
- NGRX (Redux para Angular 5+)
- Experiência com RESTful services;
- APIs documentation (Swagger e/ou Spring REST docs)
- TDD / BDD;
- Frameworks de interface (ex: bootstrap);
- Webpack;
- Gulp ou Grunt (para automatizar processos);
- Redis (como noções de performance);
- RabbitMQ (como noções de performance);
- ElasticSearch (como noções de performance);
- NodeJS.
- Continuos Integration e Continuos Deployment utilizando GIT ou TFS/VSTS, Jenkins, Sonar e Docker
- Ter noção de UX/UI para poder opinar sobre wireframes criados pelo time responsável

## Posição
Todos os níveis de senioridade 

## Tipo de contratação
CLT

## Benefícios

- Salário compatível com mercado
- Vale transporte
- Vale Refeição/Alimentação
- Seguro saúde
- Plano odontológico
- Gympass
- Auxílio Creche
- Seguro de vida
- Auxílio plano telefônico
- PLR
- Nossos escritórios também contam com frutas, lanches e happy hours ocasionalmente

## Como aplicar
envie seu currículo para o e-mail pedro.ferreira@zup.com.br com descrição [Vaga Angular - Zup]

## Outras Informações
Ajudamos com Auxilio Moradia
Possibilidades de moradia:  Uberlândia, São Paulo, Belo Horizonte.

## Labels
CLT
Todos níveis
Angular
Presencial

**Comment by dyego1912** [comment]
A label Angular não aparece no anúncio. Por quê?

**Comment by pedroferreirazup** [comment]
Foi adicionado
