### ISSUE TITLE
[Remoto] Mobile Developer na JOYJET

### ISSUE THREAD

**Issue by PachecoRaphael** [frontendbr/vagas#2364]
## Descrição da vaga

Procurando um mobile developer pra iOS o Android em uma agência digital baseada na França. Projectos diversios em todas as areas (BtoB é BtoC)

https://joyjet.com/

## Local

Remoto em todo ou Brazil ou na europa.

## Como se candidatar

Por favor envie um email para jobs@joyjet.com com seu CV em anexo
Completando esse teste

iOS: https://bitbucket.org/lixao/tech-interview/src/master/ios/
or
Android: https://bitbucket.org/lixao/tech-interview/src/master/android/

## Benefícios

- Plano de saúde (Proximo mes)
- Salario dependente da experiencia
- Curso pago pela empresa
- Your english will get better

## Requisitos

**Obrigatórios:**

- 2 anos de experiência desinvolvendo aplicativos iOS
or
- 2 anos de experiência desinvolvendo aplicativos Android

## Contratação

PJ a combinar

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: raphael.pacheco@joyjet.com

## Labels

- Júnior
- PJ
- Remoto
- Sênior
- iOS
- Android

**Comment by mrangel-jr** [comment]
@PachecoRaphael , Não pode ser realizado em React Native ?

**Comment by PachecoRaphael** [comment]
> @PachecoRaphael , Não pode ser realizado em React Native ?

SIm pode !

**Comment by halkliff** [comment]
@PachecoRaphael pode ser realizado em Flutter ou React Native?

**Comment by PachecoRaphael** [comment]
> @PachecoRaphael pode ser realizado em Flutter ou React Native?

Pode usar qualquer um

**Comment by andersonms1** [comment]
Tá com label junior mas um dos requisitos obrigatórios é ter mais de 2 anos de experiência. Acho que a partir de 2 já é pleno. 

É necessário mesmo ter 2 anos de experiência?

**Comment by PachecoRaphael** [comment]
> Tá com label junior mas um dos requisitos obrigatórios é ter mais de 2 anos de experiência. Acho que a partir de 2 já é pleno.
> 
> É necessário mesmo ter 2 anos de experiência?

Everyone have his own perception of Junior and Senior, and no it could be less than 2 years of experience too. We review a lot on the tests given by the candidates.

**Comment by emersonbrs** [comment]
Estarei começando agora o projeto para me candidatar. Ainda está em aberto a vaga?

**Comment by PachecoRaphael** [comment]
> Estarei começando agora o projeto para me candidatar. Ainda está em aberto a vaga?
> Pode ser enviado pelo gitHub?

Sim ta aberta ainda
