### ISSUE TITLE
[Belo Horizonte] Front-end Developer na NataHouse

### ISSUE THREAD

**Issue by megandavulpi** [frontendbr/vagas#2367]
## Descrição:

Somos uma fábrica de software com foco em sistemas web e aplicativos multiplataforma. Contamos com profissionais especializados em experiência do usuário e tecnologias de ponta que garantem estabilidade, escalabilidade e redução de custos, do início do planejamento até após a entrega.

## Responsabilidades:

Aqui você irá desenvolver funcionalidades, botar a mão da massa e codificar bastante. Mais que isso, você irá participar de reuniões estratégicas da empresa e ter muito autonomia nos nossos projetos. Você irá participar do desenvolvimento de softwares diversos, do início ao fim, o que poderá contribuir bastante para a sua carreira.

## Benefícios:

Vale-transporte ou auxílio combustível (R$120);
Vale-refeição ou vale alimentação (R$21,35);
Lanche na empresa;
Plano de progressão com critérios objetivos e revisões semestrais;
Subsídio para cursos e eventos;
Possibilidade de organizar e ministrar meetups e cursos abertos;
Contato com clientes internacionais;
Carga horária de 30 ou 40h semanais.
Requisitos:

## Desejável:

Javascript;
React;
HTML/CSS.

## Você vai amar trabalhar aqui se:

Estiver em busca de um ambiente de trabalho colaborativo;
Não for acomodado e estar sempre em busca de conhecimento;
Prezar por uma cultura horizontal;
Desenvolver seguindo as melhores práticas com foco em qualidade;
Estiver em busca de crescimento. Temos um plano de carreiras estruturado e a cada 6 meses você poderá subir de de cargo e salário.
Informações complementares:

Estamos localizados no Coworking Semear Innovation no bairro Funcionários em BH;
Horário de trabalho flexível.
Estamos com algumas instabilidades. Caso não consiga se cadastrar por aqui, envie seu currículo com o assunto "vaga/nome da empresa" para paula.lanza@vulpi.com.br :)

**Comment by felipefialho** [comment]
@megandavulpi da próxima vez tenta seguir o [template](https://github.com/frontendbr/vagas/blob/master/.github/ISSUE_TEMPLATE/adicionar-nova-vaga.md) de criação de vagas :)
