### ISSUE TITLE
Adicionar link para repositórios de Angola e Portugal

### ISSUE THREAD

**Issue by guibranco** [frontendbr/vagas#2368]
Solicito adicionar no **readme.md** os links dos repositórios de **Angola** e **Portugual**:

[Frontend Angola](https://github.com/frontend-ao)
[Backend Angola](https://github.com/backend-ao)

[Frontend Portugal](https://github.com/frontend-pt)
[Backend Portugal](https://github.com/backend-pt)

**Comment by felipefialho** [comment]
@guibranco Abre um PR com as alterações?
