### ISSUE TITLE
[São Paulo] Front-end Developer na Unbox

### ISSUE THREAD

**Issue by glunbox** [frontendbr/vagas#2371]
Oi, somos a Unbox uma startup que está mudando o mercado de e-commerce no Brasil :)
Estamos buscando um(a) Desenvolvedor(a) Front com experiência em NodeJs e React para nos ajudar a acelerar o roadmap de desenvolvimento do nosso produto.
Somos uma empresa 100% remota com um time incrível de pessoas inquietas e ansiosas para crescer !

Caso tenha se identificado com a gente o link abaixo tem mais detalhes ou pode mandar um e-mail para inquietos@unbox.plus e agendamos um bate papo.

https://www.linkedin.com/jobs/view/1418651407

Psiu: também vale indicar aquelx amigx que tem a cara dessa vaga.

**Comment by lucas-moraes** [comment]
Email enviado ! tenho um contraproposta para vocês !
