### ISSUE TITLE
[Rio de Janeiro] Front-end Developer na Globo.com (Globoplay)

### ISSUE THREAD

**Issue by rafaelrmagalhaes** [frontendbr/vagas#2372]
## Descrição da vaga

Quem estamos procurando?

Alguém que ajude no desenvolvimento do aplicativo para SmartTV do Globoplay, faça interface com outras áreas para integração de serviços, organize e gerencie as atividades e que tenha capacidade de estimar prazos para executar funções. Além disso, que tenha Paixão por desenvolver e muito comprometimento.

## Local

Esta vaga é para o nosso escritório no Rio de Janeiro, Barra da Tijuca, porém submissões de todo o Brasil são aceitas. A globo.com entende as dificuldades de mudança de cidade, e nós oferecemos um pacote de benefícios especial para pessoas de fora do estado. 

## Benefícios

- Salário e benefícios compatíveis com o mercado.
- Possibilidade de afetar positivamente a vida de milhares de usuários.
- Espaço e autonomia pra você deixar a sua marca.
- Ambiente descontraído e um time incrível formado por pessoas apaixonadas pelo que fazem e referências em suas áreas de atuação. 

#### Diferenciais

- Horário flexível
- Sala de descompressão com video game e totó

## Requisitos

**Obrigatórios:**
- Sólidos conhecimentos em HTML5, CSS3 (SASS) e Javascript (ES6).
- Excelente conhecimento em React.
- Experiência em integração de REST APIs.
- Experiência em desenvolvimento de layout responsivo.
- Experiência com boas praticas para performance WEB (Javascript, CSS, HTML)
- Ter profunda preocupação com qualidade.
- Experiência com GIT (GitFlow)
- Escrever código limpo e legível.

**Diferenciais:**
- Experiência com GraphQL/Apollo.
- Experiência com Typescript.
- Desenvolvido em canvas (HTML5)

## Contratação

CLT Full a combinar

## Nossa empresa

A Globo.com é uma empresa de soluções digitais para o Grupo Globo, maior grupo de mídia da América Latina. Nossas marcas digitais estão entre as maiores do Brasil, reconhecidas pela qualidade e liderança de audiência em seus segmentos. G1, Globoesporte.com, Gshow, Cartola, Globoplay, Globosatplay, são exemplos de um portfólio diverso presente na vida de milhões de pessoas que buscam informação, diversão e cultura.

Com foco no desenvolvimento de produtos, visando a melhor experiência de consumo, interação e relacionamento com os nossos usuários, contamos com um time de referência no mercado de Tecnologia.

Possuímos uma das mais modernas infraestruturas de distribuição de conteúdo do Brasil. Todas as nossas opiniões, decisões e ações se sustentam em nossos valores. Nossa Essência é composta por: Paixão por Comunicação | Brasilidade | Atitude Otimista | Talento e Liderança | Respeito à Diversidade | Qualidade e Inovação | Estética | Crescer Juntos.

Temos escritórios no Rio de Janeiro, Porto Alegre e um núcleo de Tecnologia em São Paulo. Aqui ideias, competência e inovação fazem toda a diferença. Valorizamos a diversidade e o desenvolvimento pessoal e profissional. Junte-se a nós e traga o seu talento!

## Como se candidatar

Acesse [https://talentos.globo.com/#/oportunidades/desenvolvedor-a-smart-tv/mp0jbb5](https://talentos.globo.com/#/oportunidades/desenvolvedor-a-smart-tv/mp0jbb5) e se candidate!

## Labels

- Alocado
- CLT
- Pleno
- Sênior

**Comment by eduardoborges** [comment]
Enviado! ;D
