### ISSUE TITLE
[São Paulo - SP] Front-end Developer na Jurema

### ISSUE THREAD

**Issue by etruta** [frontendbr/vagas#2373]
## Descrição da vaga

Fazer parte de uma equipe que está construindo um novo serviço web com o front-end em Angular7 e em um ecossistema com as melhores práticas de desenvolvimento.

## Local

Remoto ou Escritório, São Paulo - Vergueiro

## Requisitos

**Obrigatórios:**
- Bons conhecimentos em Angular7
- Proficiência em Javascript ES6 e TypeScript, HTML5 e CSS3
- Experiência com os frameworks Jest, Jasmine, Protractor
- Bom entendimento de programação assíncrona, suas peculiaridades e alternativas
- Testes automatizados (BDD e TDD)
- Controle de versão de código-fonte em Git (Gitflow)

**Desejáveis:**
- Familiaridade com o conceito de Integração contínua e entrega contínua (CI/CD)
- Familiaridade com ambiente Linux
- Familiaridade com scrum
- 3 anos de experiência prévia no área

**Diferenciais:**
- Participação em projetos opensource

## Contratação

PJ a combinar

## Nossa empresa

Desde 2010, a Jurema busca criar soluções que tornem o dia a dia das pessoas mais simples ou divertido. Combinando design e desenvolvimento de software concebe produtos e serviços que rompem os limites entre a web e o mundo físico, ajudando junto com seus parceiros - empreendedores, empresas e agências - a criar o futuro da web.

## Como se candidatar

Por favor envie um email para jobs+frontend@jurema.la com seu CV anexado - enviar no assunto: Vaga FrontEnd Angular

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 4 dias após cada processo.
E-mail para contato em caso de não haver resposta: ping@jurema.la

## Labels
- PJ
- Pleno
- Remoto
- Alocado

**Comment by fabiomirandaa** [comment]
Enviado.
