### ISSUE TITLE
[São Paulo] Front-end Developer na Athos

### ISSUE THREAD

**Issue by Rodocyber** [frontendbr/vagas#2376]
**Descrição da vaga**

Profissional com sólidos conhecimentos em desenvolvimento Front-end, utilizando JavaScript e frameworks JS, para desenvolvimento de aplicações. Atuar como parte da equipe ágil, desenvolver, implantar e operar serviços na cultura DevOps. Garantir a total viabilidade técnica dos protótipos de UI/UX. Buscamos um profissional colaborativo, criativo, curioso e com senso de equipe.

**Local**
Rua Tamandaré, 796 - Liberdade - São Paulo - SP

**Benefícios**
Benefícios a combinar (dependente do modelo de contratação desejado)

**Requisitos**
Domínio avançado de HTML5 e CSS3;
Conhecimentos de pré-processadores CSS (SASS, LESS, STYLUS);
Conhecimento avançado de javascript;
Experiência com algum framework JS (Vue Js, Angular, React);
Conhecimentos de Nodejs, express;
Git flow;
Clean code e SOLID principles;
Visa performance (análise de algoritmos);
Integrar API’S;
Documentar implementações.

**Desejáveis**
Conhecimento de GraphQL (ou que queira aprender);
TDD;
Hybrid mobile (IONIC, React);
Conhecimento de Message Broker Async (ex, over MQTT);
Criar mock’s de api’s.

**Contratação**
Modelo a combinar dada a preferência

**Nossa empresa**
Somos uma empresa líder em aplicações para o mercado condominial. Estamos em busca de profissionais para integrar o time de inovação.

**Como se candidatar**
Enviar um e-mail para rh@athos.com.br com seu CV e Github anexados e pretensão salarial - enviar no assunto: Vaga Front-End Developer

**Comment by halkliff** [comment]
Há a possibilidade de trabalho remoto?
