### ISSUE TITLE
[São Paulo - Berrini] Front-end Developer na K2 Partnering

### ISSUE THREAD

**Issue by natashacosta** [frontendbr/vagas#2377]
Oi, pessoal!
Tudo bem?

Sou Tech Recruiter na K2 Partnering, consultoria de recrutamento e seleção britânica, presente em 19 países, há mais de 20 anos.

Temos duas vagas de **Front-end Developer** para atuar num cliente, na Berrini. Este cliente é uma instituição máxima de organização do setor industrial brasileiro. A parceria seria PJ, com a K2, 2 meses + renovação. Por ser PJ, a renovação vai acontecendo, levando em consideração o trabalho árduo de não perdemos nossos melhores consultores. E sempre buscamos os melhores! :)

Cargo: Front-end Developer
Localidade: Brooklin Novo, São Paulo - SP, 04571-050
Data de Inicio: Setembro/2019
Data de término: 2 meses + renovação até final do ano, com possibilidade de estender. No entanto, a K2 se antecederia a isto, abrindo um leque de oportunidades
Sobre valores, Parceria é PJ (168 horas no mês) e estamos avaliando profissionais nível SR.

Conhecimento(s) Técnico(s)
- Forte domínio de Javascript, HTML5, CSS,
- Sólida experiência algum dos frameworks React, Angular, Node.js, Vue. 
- É diferencial conhecimento avançado em React Native, Ionic, Flutter, Bootstrap, Material Design.

Tem interesse? Me procura!!

ncosta@k2partnering.com

**Comment by halkliff** [comment]
@natashacosta estaria aberta a possibilidade de trabalho remoto?
