### ISSUE TITLE
[SP | Presencial ou Remoto] Front-end Engineer na Linte

### ISSUE THREAD

**Issue by carolinamedrado** [frontendbr/vagas#2378]
## Um típico dia de trabalho:

- Mentorar desenvolvedores juniores e ser capaz de ensinar e transmitir o conhecimento que você tem sobre tecnologias front-end;
- Codar componentes e bibliotecas front-end reutilizáveis ​​para uso futuro;
- Trazer vida a incríveis telas de interface do usuário, que se transformam em código de alta qualidade e pixels perfeitos;
- Produzir código limpo e eficiente e testes automatizados baseados em especificações;
- Ter capacidade de compreender histórias de usuários ágeis e traduzi-las em requisitos técnicos;
- Criar documentação técnica do seu trabalho e código;

## Local

A Linte está disposta a auxiliar na mudança, mas há a opção de remoto também!
Cubo, Alameda Vicente Pinzon, 54, Vila Olímpia, São Paulo – SP

## Benefícios

- Remuneração competitiva
- Vale refeição
- Vale transporte
- Home office
- Assistência médica
- Assistência odontológica
- Personal day (5 dias para usar quando precisar)
- Linte day

## Requisitos

**Obrigatórios:**
- Proficiência em JavaScript/ES6, manipulação de DOM e Typescript
- React com Redux
- GraphQL/Apollo
- Karma ou Jest
- Base de programação funcional
- Conhecer Legaltech

**Desejáveis:**
- Estar ativo em comunidades
- Ter trabalhado em projetos open source

**Diferenciais:**
- Isomorphic React
- CICD, BDD
- Docker e/ou Kubernetes
- Fluência em Inglês.

## Contratação e faixa salarial

Entre R$7.500 à R$12.000
CLT ou PJ a combinar

## Nossa empresa

A Linte está no começo do desenvolvimento de um novo produto, usando javascript, react e conteinerização. Se você é fera em funcional e em novos produtos, quer auxiliar na rapidez da programação, trabalhar em um produto de escala e fazer parte da sua construção utilizando o seu código,  a Linte é o lugar ideal para você. 

## Como se candidatar

Acesse o link abaixo para se inscrever e conhecer mais sobre a vaga, o processo seletivo e a empresa:
http://bit.ly/2zwp6P4

## Tempo médio de feedbacks

O processo é constituido de três etapas através da Intera Talent Hacking e uma etapa com a Linte. As etapas são:
1. Inscrição através do formulário no site
2. Preenchimento do Match Maker: um chat com o bot da Intera
3. Entrevista via telefone ou hangouts com a Intera
4. Entrevista com a Linte

A partir da etapa de entrevista com a Intera, o feedback é enviado numa média de 3 dias. As demais etapas são avaliadas diariamente, então quanto antes você conseguir concluir as etapas, mais ágil é o processo :) 

## Labels

- CLT
- Sênior
- PJ
- Remoto
- Auxílio Mudança

**Comment by felipefialho** [comment]
Cubo ❤️
