### ISSUE TITLE
[Remote] Full-stack Developer na Radish Lab

### ISSUE THREAD

**Issue by edwerd** [frontendbr/vagas#2379]
[Radish Lab](https://radishlab.com)  is looking for a talented full-stack developer(s) to join our growing team full time. Your work will be centered around designing, planning, and implementing our large scale development projects. You should have experience building backend data systems, custom solutions using the CMS WordPress, and understanding and writing frontend application code. If you’re an all-around generalist when it comes to writing code, and you’re comfortable on any end of a tech stack, then you’re a perfect fit. While this is a full-time developer position, for the right candidate, this could transition into a larger role within the company with the possibility of helping us build a team in your local community. We’re interested in applicants that have an entrepreneurial drive and excitement around helping grow a Radish Lab office in their own country.

#### Location
- Remote - Must be in the Americas

#### Candidate Description
- A self-starter who seeks out opportunities to learn new methods and technologies
- Committed problem-solver
- Ability to meet concurrent deadlines and work under pressure
- Excellent communication skills in both verbal and written English
- Good sense of humor
- A team player
- Capable of juggling multiple projects at once
- Interested in social change, and engaged with causes
- Ideally based in a time zone close to New York City
- Self-starter who is interested in not only building great projects but leading a development team 

#### Required Experience
- 5 years of backend development using languages like PHP (especially), Ruby, Python, Perl, etc.
- 2 years of frontend development, using HTML, CSS/SASS, JavaScript and modern JS frameworks like Vue, React or Angular.
- Ability to build and test web applications end-to-end, and have a thorough understanding of HTTP requests, RESTful APIs, authorization systems and comfort with using third-party solutions to solve problems.
- Excellent problem-solving skills, and great patience in dealing with technical problems.
- Experience and familiarity with the MVC architectural pattern (Laravel, CakePHP, CodeIgniter, etc.)
- Have a background in working with fast-paced environments like a creative agency.

#### Responsibilities
- Write backend application code for WordPress-based and other types of websites.
- Assist with and direct frontend development as necessary, particularly in regards to the intersection between front and back end application design.
- Managing Node dependencies and other libraries related to projects, as well as the configuration of those libraries.
- Assist with light DevOps operations, such as code deployments and build script configurations.
- Work with project managers to answer technical questions from clients about project budgets.
- Estimate scopes of work, and help to manage those scopes using GitHub and other technologies.
- Complete ongoing maintenance tasks within regular sprint cycles, and direct the testing and documentation around those tasks.
- Offer feedback to designers and product stakeholders during the early strategic phases of projects.

#### Nice to Have
- Familiarity with cloud-based infrastructure, for example with AWS, GCS or Azure.
- Expertise in writing frontend build scripts, for example using Webpack.
- Experience or understanding of Ruby on Rails.
- Experience with container-based applications, particularly using Docker.
- Comfort with the terminal, running command-line based utilities, knowledge of shell scripting (e.g. Bash).

#### Compensation
- Salary between $40k - $65K / annual USD depending on the candidate.

### About Company
Radish Lab is a full-service interactive creative agency that focuses on people and projects that create impact in our world. We’re headquartered in Brooklyn, New York with an office in Berlin, Germany. We build innovative websites, applications, data visualizations, and interactive experiences for non-profits, cultural institutions, universities, advocacy organizations, health, and science-based organizations, as well as social businesses. We’re looking to have an impact on the world using design and technology. 

### How to apply
Interested candidates should include an awesome (seriously) cover letter, resume, Linkedin and Github accounts in their application. [Apply here](https://www.fitzii.com/apply/43090?s=c15)

**Important:** All applicants who ignore the instructions above will not be considered. 
No recruiters or calls, please. 

Radish Lab provides equal employment opportunities to all applicants without regard to race, color, religion, gender, sexual orientation, gender identity, national origin, age, disability, genetic information, marital status, amnesty or status as a covered veteran.  

#### Labels 
- PJ
- Remoto
- Sênior

**Comment by rodineicosta** [comment]
Applied!
