### ISSUE TITLE
[São Paulo] Desenvolvedor Front-End Angular.js

### ISSUE THREAD

**Issue by gustavopessoa** [frontendbr/vagas#238]
## Descrição da vaga

A Kitado busca um profissional de tecnologia que goste de aprender e aprenda rápido. Precisamos de gente que se adapta às novas linguagens, é curiosa, trabalha em equipe e responde às necessidades de um negócio extremamente desafiador. Aqui, é para aprender, superar limites e atuar com qualidade e agilidade. Nosso front é em Angular 2.0 e estamos sempre empurrando a barreira da tecnologia junto aos nossos clientes. 

## Local

CUBO, São Paulo - Vila Olímpia

## Benefícios

- VR
- VT
- Plano de saúde
- Acesso como residente ao CUBO

## Requisitos

**Obrigatórios:**
- Você aprende muito rápido a aplicar novas tecnologias; 
- Você é adaptável às mudanças que ocorrem ao decorrer do caminho;
- Você é curioso, autodidata e gosta de inovar; 
- Você responde rapidamente à evolução das necessidades de negócio e implantação de funcionalidades em pequenos incrementos em vez de uma abordagem big bang;
- Você é experiente em engenharia de interfaces, em modernos web frameworks, tendo escrito ou consumido REST APIs e desenvolvido SPAs;
- Você tem um profundo conhecimento sobre HTML5 e CSS e pode fazer as escolhas certas ao criar aplicativos UI responsivo;
- Você é quase um expert em Javascript com Node.js, ou algum outro framework como Angularjs 2, ReactJS, Backbone;
- Você entende escopo e herança de protótipos do JS;
- Você tem experiência com frameworks de testes de frontend como Mocha, Chai, Sinon ou equivalentes;
- Você conhece e busca de aplicar práticas que buscam a qualidade do código como, XP, TDD, BDD, Testes de integração e Integração contínua;
- Você conhece práticas ágeis e tem maturidade com o processo de desenvolvimento de software, equilibrando bem débitos técnicos e agilidade, agile refactoring, pair programming, XP, etc…;
Você preferencialmente tem trabalhado com projetos de código aberto.

**Desejáveis:**
- Ter experiência com desenvolvimento de aplicações orientadas para a AWS utilizando serviços como SQS, SNS, Lambda, API Gateway, Kinesis, etc…;
- Ter experiência em aplicação de boas práticas de UX, tanto na concepção de produtos/fluxos quanto no desenvolvimento de interfaces.

## Contratação

CLT

## Como se candidatar

Por favor envie um email para talentos@kitado.com.br com seu CV anexado - enviar no assunto: Desenvolvedor  #Front-End

**Comment by jvcjunior** [comment]
owwww como eu queria que um vaga desse fosse remoto!!! \o

**Comment by acacioosorio** [comment]
parece uma boa vaga mesmo, pena ser locald
 de difícil acesso
