### ISSUE TITLE
[Remoto] Web-designer na JOYJET 

### ISSUE THREAD

**Issue by PachecoRaphael** [frontendbr/vagas#2381]
## Descrição da vaga

Procurando um web designer em uma agência digital baseada na França. Projectos diversios em todas as areas (BtoB é BtoC)

https://joyjet.com/

Test for all new candidates: https://bitbucket.org/lixao/tech-interview/src/master/webdesign/

## Local

Remoto em todo ou Brazil ou na europa.

## Benefícios

Plano de saúde (Proximo mes)
Salario dependente da experiencia
Curso pago pela empresa
Vai melhorar bastante seu inglês

## Requisitos

**Obrigatórios:**
- HTML/CSS
- git
- Java-script
- Able to read and communicate in English

**Desejáveis:**
- Conhecimentos em react
- Conhecimentos em C#

## Contratação

PJ a combinar

## Nossa empresa

Mais de 15 anos atrás, Marcio Marinho, criou a Joyjet, uma agencia digital com 15 pesoas trabalhando juntos pra projetos do mundo inteiro. O time esta baseado na Europa, Brazil e nos Estados Unidos.

## Como se candidatar

Por favor envie um email para jobs@joyjet.com com seu CV em anexo
Completando esse teste

https://bitbucket.org/lixao/tech-interview/src/master/webdesign/

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: raphael.pacheco@joyjet.com

## Labels

- Júnior
- PJ
- Pleno
- Remoto
- Sênior
- Web-developper
- Tech-designer

**Comment by iansilva6** [comment]
Até quando posso enviar o teste?

**Comment by PachecoRaphael** [comment]
> Até quando posso enviar o teste?

Até segunda (16/09)

**Comment by thiagofrancisquete** [comment]
Qual seria o range salarial?

**Comment by Henriquepb22** [comment]
Aceita quem tem pouca experiencia e ta começando agora?

**Comment by JosielLima** [comment]
Horário comercial? Quantas horas por semana?

**Comment by lucas-moraes** [comment]
Enviado !
