### ISSUE TITLE
[Remoto] Pessoa Desenvolvedora Front-end Senior na Magnetis Investimentos

### ISSUE THREAD

**Issue by rrrcompagnoni** [frontendbr/vagas#2382]
## Descrição da vaga
Como uma pessoa desenvolvedora, você irá nos ajudar a construir um produto cada vez melhor, participando do ciclo de concepção de novas funcionalidades, tomando decisões e mantendo o código produzido. Nos organizamos em times multidisciplinares, então você poderá envolver-se na fase de planejamento, testes com o usuário, acompanhamento de métricas e resultados da implementação em produção.

Você irá se ambientar no produto e tecnologia de forma imersiva. Não se preocupe, vamos te ajudar! Valorizamos o compartilhamento de conhecimento e pair programming. É bem possível que em sua primeira semana você já veja seu código em produção!

Nós acreditamos que, para desenvolver um bom produto, precisamos de um time forte e colaborativo, composto por pessoas de diferentes identidades e experiências. Por isso, nos comprometemos a construir um ambiente inclusivo, apoiando as pessoas a fazerem o seu melhor.

A posição inclui trabalho remoto, mas você também terá acesso ao nosso escritório em São Paulo, caso queira trabalhar presencialmente. Temos mais de 25 pessoas remotas e somos livres para trabalhar de onde quisermos, sempre com autonomia e responsabilidade. Confiamos no nosso time: valorizamos a qualidade das entregas e não a quantidade de tempo dedicado.

Nós valorizamos pessoas que reconhecem as próprias falhas e falam abertamente sobre elas. Errar não é um tabu dentro do time. Nós queremos construir relações duradouras e transparentes no trabalho, uma vez que dar e receber feedbacks faz parte da nossa cultura.

Esses são exemplos do dia a dia de uma pessoa desenvolvedora Front-end na Magnetis:

   - Desenvolvimento de novas funcionalidades, manutenção e interação com APIs e sistemas mistos.
   - Participação em reuniões estratégicas para o time, como planning, retro, daily e refinamento de demandas para desenvolvimento
   - Trocar experiências e conhecimentos com demais pessoas e times de desenvolvimento através de Pull Requests, discussões técnicas e palestras internas
   - Participar da melhoria contínua dos processos e práticas dos times de engenharia e produto

## Local

Remoto ou Escritório, São Paulo - Pinheiros

## Benefícios

Na Magnetis você terá a oportunidade trabalhar em ambiente diverso, flexível e inovador. Alguns dos nossos benefícios são:

- Plano de saúde e Odontológico
- Vale-refeição / vale-alimentação
- Vale-transporte
- Oportunidade de ganhar stock options (participação na empresa)
- Verba educacional, para participação em cursos e eventos
- Flexibilidade para trabalho remoto ou no nosso escritório próximo a estação Faria Lima do metrô
 - Para remotos fora da cidade São Paulo: ajuda de custo para você montar o seu ambiente ideal de trabalho

## Requisitos

Estamos buscando uma pessoa que se comunique bem em português (na fala e na escrita), e que tenha interesse em trabalhar em ambiente de desenvolvimento de produtos, com autonomia e mudanças constantes. Os nossos requisitos técnicos são:

  - Habilidade para atuar como facilitador para o time, atuação em eventuais bloqueios enfrentados pelas pessoas, planejamento de itens de trabalho em tamanhos adequados e identificação de comunicação não clara afim de esclarecê-la para as demais pessoas.
   - Experiência em construção de SPAs em React, Redux e CSS.
   - Habilidade na escrita de testes automatizados utilizando os conceitos da Pirâmide de testes.
   -  Habilidade em design de aplicações pensando em boas práticas de integração, performance e segurança.
   -  Conhecimento em versionamento de código utilizando Git e habilidades em se comunicar de forma eficiente em revisão de código de outras pessoas.
   -  Conhecimento do método Kanban como praticante.

## Contratação
CLT
## Nossa empresa
A Magnetis é uma fintech e gestora de investimentos digital que desde 2015 tem a missão de ajudar as pessoas a investir no que importa. Dentro do nosso ambiente de trabalho, isso não poderia ser diferente: investimos nas pessoas que trabalham com a gente e temos um compromisso com diversidade e inclusão.

## Como se candidatar
https://magnetis.workable.com/j/4A73B63AAA

## Labels

- CLT
- Remoto
- Sênior

**Comment by jonathanguilhermesouza** [comment]
@rrrcompagnoni seria apenas nível senior?

**Comment by rrrcompagnoni** [comment]
@jonathanguilhermesouza nesse momento sim.
