### ISSUE TITLE
[São Paulo] Front-end Developer na Sallve

### ISSUE THREAD

**Issue by mariacarolbarge** [frontendbr/vagas#2383]
## Descrição da vaga

Buscamos por uma pessoa muito fera para desenvolver e manter nosso front-end que se sinta confortável em nos ajudar a encontrar ótimas soluções para melhorar a experiência do usuário.

## Local

Nosso escritório fica na Rua Cônego Eugênio Leite, 767 - Pinheiros.

## Benefícios

- Plano de Saúde
- Vale Transporte
- Vale Refeição

#### Diferenciais

- Ambiente Informal
- Horários flexíveis
- Aberta a novas ideias e sugestões

## Requisitos

**Obrigatórios:**
- Ser apaixonada(o) por desenvolvimento de software e tecnologia;
- Conhecimentos em desenvolvimento web (HTML5, CSS, JS);
- Ter facilidade para trabalhar dentro de times multidisciplinares;
- Design responsivo

**Desejáveis:**
- Saber trabalhar com ferramentas de controle de versão, gostamos do GIT;
- Conhecer boas práticas de UX

**Diferenciais:**
- Conhecer AngularJS, ReactJS ou VueJS;
- Experiência com softwares de edição de imagem

## Contratação

CLT

## Nossa empresa

A Sallve é um lugar acolhedor que conecta pessoas, ideias e conteúdo sobre beleza. É assim que, entre conversas sinceras e pesquisas cuidadosas, estamos desenvolvendo fórmulas incríveis inspiradas por necessidades reais.
Saiba mais sobre a Sallve no nosso site: https://www.sallve.com.br/sobre

## Como se candidatar

Nos envie um e-mail com o seu currículo para vagas@sallve.com com o assunto "Vaga Front-End Developer - Seu Nome"

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo. E-mail para contato em caso de não haver resposta: vagas@sallve.com.

## Labels
- CLT
- Júnior
- Pleno
- Sênior

**Comment by nandosangenetto** [comment]
Ótima vaga e ótima empresa!

**Comment by EdipoNascimento** [comment]
Sendo Q.A. Posso participar do processo?

**Comment by GustavoPrizon** [comment]
Cv enviado

**Comment by julianamokrejs** [comment]
enviado :)

**Comment by stochiconrado** [comment]
A vaga está disponível?

Em seg., 30 de set. de 2019 às 15:50, Juliana Mokrejs <
notifications@github.com> escreveu:
