### ISSUE TITLE
[São Paulo] QA Software no Sua Música

### ISSUE THREAD

**Issue by carolinazalc** [frontendbr/vagas#2386]
**Descrição da vaga**
Planejar e executar testes exploratórios e automáticos para garantir a qualidade do produto;
Criar plano de testes e caso de testes detalhados, compreensivos e bem estruturados;
Desenvolver e criar scripts de testes usando ferramentas tais como Amazon (Device Farm) e Firebase (Test Lab) ;
Realizar testes de regressão quando bugs/defeitos forem corrigidos;
Elaborar modelos para a geração dos casos de testes das funcionalidades e bugs dos sistemas, evidenciando como serão tratados os vários cenários a serem avaliados.
Auxiliar na criação / execução de script de testes automatizados.
Apoiar na modelagem de casos de testes.
Auxiliar na execução manual de testes funcionais

**Local**
Rua Viradouro 63, Itaim Bibi - SP

**Benefícios**
VR + VT + 

**Requisitos**
**Desejáveis**

Conhecimento de metodologias (Agile, Kanban e Scrum), processos e ferramentas de qualidade;
Teste caixa branca e caixa preta;
Testes de aplicações WEB (desktop, site mobile) e apps (Android e IOS);
Conhecimento de Ferramentas de Bug Track.
Nível de inglês básico é essencial
Perfil
Proatividade
Perfil analítico
Boa organização de raciocínio e trabalho
Sistemático
Saiba de expressar de forma clara e objetiva por escrita

**Contratação**
Estágio - 6 horas de Seg à Sex

**Nossa empresa**
O Sua Música é a maior plataforma de conteúdo de música brasileira, onde artistas lançam seu repertório grátis para milhões de fãs, que também se conectam e engajam através do nosso site, aplicativo e redes sociais.

Ambiente de muito aprendizado;
Aplicativo com mais de 10M+ de downloads e nota 4.3+ no Google Play;
3M de usuários únicos no Android por mês;
240M+ downloads e 300M+ plays mensalmente em nossa plataforma;
Temos uma comunidade apaixonada pelo Sua Música, principalmente por sua representatividade com artistas independentes.

Nossos valores:

Acreditamos no poder da música e buscamos nos especializar nos gêneros musicais que atuamos.
Somos ágeis, proativos e pioneiros.
Sonhamos grande.
Somos colaborativos em busca dos objetivos da empresa.
Não toleramos qualquer forma de discriminação ou preconceito.
Respeitamos compromissos.
Incentivamos o desenvolvimento das pessoas e promovemos a meritocracia.
Quebramos barreiras.
Como se candidatar

Por favor envie um e-mail para **jobs@suamusica.com.br** com seu CV anexado - enviar no assunto: Vaga QA STAG

**Comment by felipefialho** [comment]
Essa vaga é de QA, sem relação com o repositório
