### ISSUE TITLE
[Rio de Janeiro] Front-end Developer Jr na LEO Learning

### ISSUE THREAD

**Issue by josephfelix** [frontendbr/vagas#2389]
Somos uma empresa que trabalha desenvolvendo plataformas de ensino à distância e treinamentos corporativos.
Trabalhamos sob a plataforma Moodle, que é usada em diversas universidades e reconhecido no mundo inteiro como um dos melhores LMS da atualidade.
Busca-se desenvolvedor para atuar com front end, desenvolvendo as telas seguindo a especificação do designer e da compatibilidade com todos os browsers da atualidade.

Local:
Vaga presencial na Barra da Tijuca - Rio de Janeiro/RJ

Requisito:
CSS (Sass/Less), HTML (Mustache), JavaScript (jQuery)

Nível da vaga: Júnior

Diferenciais:
PHP, Ionic e Moodle.

Contratação:
Salário a combinar

Como se candidatar:
Por favor envie um e-mail para plataforma@leolearning.com com o link do seu portfólio ou CV.

**Comment by re-andrade1987** [comment]
A vaga é clt ou pj ?
