### ISSUE TITLE
[Joinville/SC] Desenvolvedor Front-end @ iTFLEX

### ISSUE THREAD

**Issue by rudineirk** [frontendbr/vagas#239]
## Descrição da vaga

Esta é uma oportunidade para uma vaga de desenvolvedor Front-end, que irá atuar na especificação, design e desenvolvimento de uma interface de administração e geração de relatórios de servidores linux de telefonia IP, firewall e email.

## Local

Joinville - Santa Catarina, Bairro América

## Benefícios

- Sala de jogos
- Auxílio faculdade / pós-graduação
- Plano de carreira
- Plano de saúde

## Perfil
- Gostar muito desenvolvimento de software e tecnologia
- Ser participativo na construção do produto, contribuindo com ideias para o negócio
- Ter facilidade de trabalhar dentro de times multi-disciplinares
- Ter iniciativa para estudos
- Acompanhar tendências e inovações que surgem no mercado
- Escrever código limpo e legível
- Ter profunda preocupação com qualidade e performance
- Compreender a importância e praticar versionamento de código

## Requisitos
- Curso superior em Sistemas de Informação, Ciências da Computação ou Engenharia da computação
- Curso superior em andamento para se candidatar a Analista de Desevolvimento Júnior
- Curso superior concluído: requisito mínimo para se canditar a Analista de Desenvolvimento Pleno
- Ter experiência com programação em Javascript (VanillaJS)
- Domínio em html5 e css3
- Experiência em sites responsivos
- Entender o funcionamento do protocolo HTTP
- Desenvolvimento de aplicações javascript consultando APIs REST

## Diferenciais
- Conhecimentos de UX
- Conhecimentos de Web Design (utilizando Material Design)
- Conhecimento de ferramentas de criação de protótipos
- Conhecimento de ferramentas de edição de imagens
- Experiência com frameworks SPA (single page applications)
- Já ter utilizado/estar utilizando o framework VueJS
- Experiência com Task runners (grunt ou gulp)
- Experiência em utilização do Git
- Experiência com metodologias ágeis
- Conhecimento de ferramentas de TDD de javascript (Jasmine, Mocha, etc)
- Usar/conhecer Linux

Tratamos todas as nossas aplicações como sistemas de missão crítica.
Usamos software livre na grande maioria das aplicações e ferramentas por traz da aplicação.

## Contratação

CLT a combinar, trabalho presencial em Joinville / SC

## Nossa empresa

Empresa com 12 anos de mercado, contato com novas tecnologias, oferece possibilidade de crescimento profissional.

Localizada em Joinville, a maior cidade de Santa Catarina (500 mil habitantes), próximo a diversas praias (até 100Km), e também a capital Florianópolis (180Km) e a capital do Paraná, Curitiba (130Km).

## Como se candidatar

Mais detalhes neste link: https://www.itflex.com.br/vaga/desenvolvedor-front-end/

**Comment by LFeh** [comment]
Qual o nivel?

**Comment by rudineirk** [comment]
Júnior / Pleno

**Comment by siqueiradg** [comment]
Algum problema em se candidatar sendo de outro estado?

**Comment by rudineirk** [comment]
Não tem problema, estamos avaliando candidados de outros estados.
