### ISSUE TITLE
[São Paulo] Front-End Developer React (JR/PL) na Proprietário Direto

### ISSUE THREAD

**Issue by leticiamrosa** [frontendbr/vagas#2391]
## Descrição da vaga

O Front-end Developer é parte fundamental do time de desenvolvimento da Proprietário Direto. Trabalhando em nosso time, você será responsável pela manutenção e desenvolvimento de novos códigos que produzem a mágica de nossa solução.
Como Front-end Developer na Proprietário Direto você vai criar um impacto no mundo real criando um produto e serviço inovador. Você vai trabalhar num time pequeno e ao mesmo tempo multidisciplinar, capaz de produz códigos novos para nossa plataforma e usuários o mais rápido possível mantendo simultaneamente uma alta qualidade.

## Local

Escritório, São Paulo - Morumbi

## Requisitos

**Obrigatórios:**
- 1/2 anos de experiência com ReactJS
- JavaScript / CSS3 / HTML5
- Noções de Laravel
- Familiaridade com Redis/ Mongo/ Mysql

**Desejáveis:**
- NodeJs
- VueJs
- React Native
- Python

**Soft Skills:**
- Atenção aos detalhes e funcionamento das features desenvolvidas;
- Ser uma pessoa de AÇÃO. Você acredita que velocidade e qualidade podem ser alcançadas ao mesmo tempo;
- Ownership mindset! Atitude empreendedora e de responsabilidade pelo que você produz e entrega;
- Versatilidade: Você entende como todas as peças se conectam (front-end, back-end, database, camadas de rede etc) e como isso impacta a performance do seu código/aplicação);
- Excelente trabalho em equipe (respeito, gentileza, empatia, gratitude e generosidade);
- Team Player. Você acredita que pode obter mais trabalhando em time.

## Contratação

PJ a combinar

## Nossa empresa

A Proprietário Direto é uma startup que traz uma tecnologia disruptiva para o mercado de Real State brasileiro. A tecnologia da Proprietário Direto oferece a seus clientes o match perfeito entre quem quer comprar e quem quer vender seu imóvel. Com isso, vendedor e comprador negociam diretamente, de forma simples, rápida e trazendo muita economia com a desintermediação.

Nossa equipe é jovem, engajada, conectada com a tecnologia, comprometida em transformar o mercado imobiliário e apaixonada pelo o que faz.
Se você é uma pessoa proativa, criativa, tem espírito empreendedor, gosta de desafios, é apaixonado por novas tecnologias, quer fazer história no mercado de internet brasileiro, causando um grande impacto na vida das pessoas, permitindo que elas escapem de um sistema antigo, ineficiente, lento, caro e sem transparência esse é seu lugar! Faça parte da empresa que está revolucionando o mercado imobiliário e venha fazer algo pioneiro.

## Como se candidatar

Se vc acredita que é essa pessoa, encaminhe-nos seu currículo: vagas@proprietariodireto.com.br

## Labels

- 🏢 Flexível
- 🏢 Presencial
- 👦 Júnior
- 👨 Pleno
- ⚖️ A-Combinar
- ⚖️ PJ

**Comment by maxarouca** [comment]
Aceitam remoto? Sou de Salvador-BA.

**Comment by halkliff** [comment]
Aceitam remoto (+1)? Sou de Goiânia / GO, e me encaixo bem com o perfil que procuram
