### ISSUE TITLE
[Belo Horizonte] Front-end Developer na DialHost Internet

### ISSUE THREAD

**Issue by DionathaRodrigues** [frontendbr/vagas#2392]
## Descrição da vaga

- Desenvolver código limpo, testável e de fácil manutenção, implementando as melhores práticas de código e design patterns, orientação a objetos e otimização de performance;
- Promover melhorias e ajustes em nossos sites, dashboards e sistemas;
- Discutir e planejar sobre aprimoramentos das ferramentas da empresa, juntamente com a equipe de desenvolvimento;
- Manter e integrar o Front-end em atualizações dos nossos sistemas com sistemas de terceiros;
- Aplicar melhores práticas de documentação de código desenvolvido;

## Local

DialHost Internet - B. Califórnia, Belo Horizonte

## Benefícios

- Regime de contratação CLT;
- Vale refeição;
- Vale transporte;
- Plano de Saúde;
- Lanche na empresa
- Flexibilidade de horário;
- No dress code (pode trabalhar de bermuda, camiseta, etc, afinal o que importa é seu resultado!);
- Acesso a todos os cursos da Alura;

## Requisitos

**Obrigatórios:**
- HTML, CSS, Sass e JavaScript;
- Laravel;
- Saber trabalhar com a estrutura Blade do Laravel;
- WebPack para automação na compilação de assets;
- Git;

**Desejáveis:**
- Inglês Intermediário;
- Noções de otimização de performance web;
- Otimização de código para SEO;
- Vue.js;
- PHP;

## Contratação

CLT

## Nossa empresa

Trabalhando há mais de 17 anos para fazer do serviço de hospedagem de sites cada dia melhor. Contamos com uma estrutura própria de Data Center com servidores no Brasil.
Iniciamos nossa trajetória em 2002, e, desde o início, decidimos proporcionar um serviço de hospedagem de sites voltado 100% na Experiência e Sucesso do Cliente, prezando a qualidade, transparência e segurança.

## Como se candidatar

[Cadastre-se em nosso site](https://www.dialhost.com.br/trabalhe-conosco/vaga/desenvolvedor-front-end-jr/)

## Labels

- CLT
- Júnior
- Pleno

**Comment by maxarouca** [comment]
Aceitam remoto? Sou de Salvador-BA.

**Comment by adeonir** [comment]
@DionathaRodrigues aceitam remoto? +1

**Comment by DionathaRodrigues** [comment]
@adeonir @maxarouca por hora, o foco da vaga é para presencial, caso mude atualizo na vaga.

**Comment by Ogunn** [comment]
Faz sentido ter Laravel como requisito obrigatório e PHP como requisito desejável? Isso deu um nó na minha cabeça. 🤔
