### ISSUE TITLE
[São Paulo] Programa de Formação de Desenvolvedores Júniores Zup

### ISSUE THREAD

**Issue by pedroferreirazup** [frontendbr/vagas#2399]
## Empresa
Quem somos?

A Zup desenvolve produtos digitais disruptivos que impactam a vida de milhares de usuários. Acreditamos em ambientes ágeis, autogerenciáveis e flexíveis. Por isso, contratamos somente os melhores profissionais. Crescemos mais de 30 vezes nos últimos cinco anos, já somos mais de 850 zuppers e estamos em seis cidades.

## Quem é você?

Uma pessoa recém-graduada ou que esteja se formando em 2019.2, que gostaria de iniciar sua carreira na área de desenvolvimento para mobile, back-end ou front-end com disponibilidade de atuação na cidade de São Paulo.

## O que você fará na Zup:

Participar de uma capacitação com referências no mercado nas áreas de mobile, back-end e front-end;
Entregar projetos onde possa exercitar os aprendizados;
No final do ciclo de aprendizado, ser inserido em times de alta performance formado por outros profissionais plenos e seniores.
Importante: Acreditamos que profissionais fora da curva estão em todos os lugares. Por isso, todas as nossas vagas são abertas a qualquer pessoa, independente de cor, gênero, orientação sexual, identidade de gênero e/ou deficiências.

## Requisitos
* Essa oportunidade é para profissionais em início de carreira com interesse em seguir nas áreas de frontend Angular, backend Java e mobile (iOS/Android).

## Qual perfil buscamos?

Unir a complexidade dos desafios técnicos com uma boa postura profissional é o que o Programa de Formação de Júniors na Zup tem de essência. Nosso objetivo é capacitar os profissionais nas tecnologias atuais do mercado e dos nossos clientes, e provocar situações da vida real para formar soft skills. O Programa consiste em três etapas complementares:

## Nivelamento técnico nas trilhas de conhecimento;

- Da concepção ao desenvolvimento da resolução de um problema interno;
- Período de experiência e prática dos aprendizados no cliente.
- Benefits
- Salário compatível com mercado;
- Vale transporte;
- Vale Refeição/Alimentação;
- Seguro saúde;
- Plano odontológico;
- Gympass;
- Auxílio Creche;
- Seguro de vida;
- Auxílio plano telefônico;
- PLR;
- Nossos escritórios também contam com frutas, lanches e happy hours ocasionalmente.

## Como aplicar
envie seu currículo para o e-mail pedro.ferreira@zup.com.br com descrição [Vaga Formação Dev - Zup]

## Labels
- Presencial
- Júnior

**Comment by GustavoPrizon** [comment]
Cv enviado!

**Comment by pedroferreirazup** [comment]
Vaga fechada

**Comment by LEOBLACKGOSPEL** [comment]
Enviado

**Comment by pedroferreirazup** [comment]
@LEOBLACKGOSPEL  obrigado por enviar Leo, mas a vaga está fechada no momento, vou redirecionar o seu cv para o banco de talentos ok?

**Comment by stochiconrado** [comment]
A vaga está disponível?

Em qua., 11 de set. de 2019 às 07:30, pedroferreirazup <
notifications@github.com> escreveu:
