### ISSUE TITLE
[Remoto] Desenvolvedor Front-End 

### ISSUE THREAD

**Issue by mateusnb** [frontendbr/vagas#24]
## Descrição da vaga

Sou Mateus, CEO do GoDoctor (fb.com/godoctor.me), um projeto inovador na area de Saude com alto potencial de alavancagem. Nosso time é formado por pessoas de mercado, medicos, academicos e tech devs. Somos hoje 12 em um time com pessoas de mercado, ios-android -web devs e medicina, todos dedicando o tempo livre. Estamos ja conversando com investidores e anjos. Estamos em fase de pré-launch com medicos do Sirio libanes para iniciar o piloto.

**GoDoctor (fb.com/godoctor.me)**

Estou buscando um FrontEnd dev pra liderar a parte de dev Web/mobile q acredite no projeto, comprometido e queiram ser co-founders com uma porcentagem acionaria no modelo de vesting ate recebermos investimento. Ou seja, é trabalhar no horario livre e ser sócio.

## Requisitos

**Remoto, par time / São Paulo**

- Dominio Senior de desenvolvimento FrontEnd 

- HTML5  CSS  Javascript
- Ferramentas de controle de versão (Usamos Bitbucket)
- Atenção para detalhes (Pixel perfect)
- 5 anos de experiência com dev Web e Mobile
- Dev Responsive e melhores praticas.

## Contratação

- Equity de açoes
- Sociedade como coFounder

Se voce tiver confortavel com este cenario e mande seu melhor horario e marcamos um skype.
Envie um email para godoctor@godoctor.me com seu CV / portfolio anexado. 
enviar no assunto: Vaga Frontend

**Comment by LFeh** [comment]
Boa sorte @mateusnb  ;)

**Comment by jadir-junior** [comment]
já foi preenchida a vaga?

**Comment by mateusnb** [comment]
Fala Jadir!
Vamos nos falar. 

Me mande seus contatos em mateusnb@gmail.com
Skype. Mateusnb

**Comment by Carlosxell** [comment]
@mateusnb te mandei uma solicitação no skype

**Comment by mateusnb** [comment]
Carlos, nao recebi seu invite no Skype
Por favor mande seus dados de contato pra mateusnb@gmail.com

**Comment by agyrafa** [comment]
@mateusnb te mandei invite no skype :)

**Comment by hevertoncastro** [comment]
Enviei email @mateusnb 
Abraço!

**Comment by LFeh** [comment]
A vaga foi preenchida? @mateusnb

**Comment by mateusnb** [comment]
Sim Felipe
Valeu!
Em 15/06/2016 12:25, "Felipe Fialho" <notifications@github.com> escreveu:

**Comment by camilatigre** [comment]
@mateusnb 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
