### ISSUE TITLE
[São Paulo] Front-end pl/senior na Vamo!

### ISSUE THREAD

**Issue by joselialcosta** [frontendbr/vagas#240]
Descrição da vaga
----

Estamos em busca de uma pessoa desenvolvedora front-end PL/SR para integrar o nosso time. Procuramos alguém experiente para alavancar a equipe de front-end trazendo boas práticas de arquitetura e performance, e que - acima de tudo - curta resolver problemas de uma forma coesa usando JavaScript, CSS bem escrito e HTML.

Nossa stack:

**Front**
- Angular 1.5.x
- TypeScript 1.X
- Pré processadores CSS (Less e Sass)
- Gulp, Grunt e Webpack

**Back**
- Scala (Akka e Play)
- Java(Spring boot e Java8)
- Deploy automatizado com Docker e AWS
- Apps nativos (iOS e Android)

Local
---

Vila Olimpia - SP
(Próximo à estação de trem e do Shopping Vila Olimpia)

Contratação
---

CLT Full, presencial

Benefícios
---
- VR (R$506 por mês)
- VT ou estacionamento para carros e bikes :bike:
- Plano de saúde One Health e odontológico Amil
- Seguro de Vida
- Convênio com SESC

Nenhum desses benefícios é descontado do salário :tada:

Requisitos
---
**O que você precisa saber:**
- Vanilla JS
- Web SPA com Angular ou outros
- Inglês para se comunicar (temos gringos no time!)
- Vontade de aprender e não ter preconceitos
- Código limpo
- Noções de usabilidade

**Será legal se você tiver:**
- Contribuições OpenSource
- Conhecimento sobre Task Runners
- Conhecimento ES6/ES7
- Formação: Bacharel em Engenharia/Ciência da Computação ou equivalente.

Nosso Ambiente
---

- Snacks, frutas e bolos!
- Video games
- Ping-Pong
- Festa de aniversário todo mês :cake:
- Horário flexível
- Sem dress code (pode vir de pijama!)

Sobre Nós
---

Somos uma startup norte-americana comprometida a reinventar a maneira como as pessoas descobrem eventos e compram ingressos online usando seus smartphones. Também trabalhamos em uma série de outros projetos tão legais quanto esse.

Saiba mais em: https://vamoapp.com/

Como se candidatar
---

Preencha este formulário e informe que você viu a vaga no FrontendBR. 😃 
http://bit.ly/2jXWRSN

**Comment by LFeh** [comment]
Ótima vaga.

Botei fé.

**Comment by joselialcosta** [comment]
Gente, conseguimos contratar uma pessoa graças a esse anúncio! Começa dia 20/02! 🎉 

Muito obrigada a todas as pessoas que se interessaram e enviaram as submissões! Tivemos um retorno muito positivo com inscrições de alto nível!

@LFeh acho que pode fechar a issue! Tks!!

**Comment by LFeh** [comment]
Aeeee, foda @joselialcosta 🥇 

Boa sorte para todos.
