### ISSUE TITLE
[REMOTO ou ALOCADO AUSTRALIA] Front-End Developer [CSS] e [Atomic design] na Rocketlab

### ISSUE THREAD

**Issue by nativedone** [frontendbr/vagas#2402]
![VAGA](https://user-images.githubusercontent.com/20998754/64808938-94a66e00-d5db-11e9-8503-2a39dd884e67.png)

## Descrição da vaga

Oi pessoal,

Tem uma `1 vaga` de senior frontend do meu team aqui de Sydney/AU.

Basicamente, espera-se alguem que chegue e seja responsavel pela criacao e manutencao de components reutilizaveis usando principios de `atomic design`, `React` e `storybook`.

O time possui devs very very experientes em ReactJS, mas nao tao seniors em `CSS` pra resolver aqueles detalhes que garantem o famoso *pixel perfect*. Entao, essa vaga eh sua se `CSS` estah no seu coracao :)

## Local

Totalmente Remoto ou alocado com possibilidade patrocionio (sponsorship de visto)

#### Diferenciais

- Flexibilidade de horarios
- Pagamento em $AUD
- Contrato: `full-time`, `part-time` ou `freelance`
- Sponsorship e ajuda de custo pra realocacao

- Selecao sem enrolacao: 

1. Envie um codigo seu usando React
2. Call curta de 15 min em portugues
3. Test em real-time de 50 min em ingles (compartilhando a tela)
4. Contratacao ou feedback em `ateh 2 dias`  

## Requisitos

**Obrigatórios:**
- Top em CSS
- Experiência em Atomic design
- Experiência em React
- Experiencia em storybook
- Falar ingles (Nao precisa muita fluencia. O foco total eh comunicacao! Somos uma empresa de software. Pode falar ingles com erros? Pode! Mas, tem que falar. Tem que comunicar a sua idea e o seu trabalho.)

**Diferenciais:**
- Styled components.
- GraphQL

## Contratação

A combinar.

## Nossa empresa

https://www.rocketlab.com.au/

## Como se candidatar

- Me envie uma messagem privada em https://twitter.com/nativedone 

## Labels
- Alocado
- Remoto - Total
- Sênior

**Comment by TecladistaProd** [comment]
Muito legal ver uma vaga no exterior que não se importa com English perfect, apenas conseguir se comunicar. Conheço ReactJS mas não sou fera em css e atomic design kkkkk. Se fosse react sem precisar ser expert em design eu me inscreveria.

**Comment by felipefialho** [comment]
Boa vaga @nativedone ;)

**Comment by lucasfloriani** [comment]
Por questão de curiosidade, o quão avançado vocês gostariam que o candidato seja em CSS? Realização de animações avançadas e utilização das features mais novas? Se tiverem um design para demonstrar o que este profissional necessitará desenvolver durante o dia a dia seria uma boa.

Alias parabéns pela proposta da vaga, muito interessante mesmo.

**Comment by nativedone** [comment]
> Por questão de curiosidade, o quão avançado vocês gostariam que o candidato seja em CSS? Realização de animações avançadas e utilização das features mais novas? Se tiverem um design para demonstrar o que este profissional necessitará desenvolver durante o dia a dia seria uma boa.
> 
> Alias parabéns pela proposta da vaga, muito interessante mesmo.

@lucasfloriani Obrigado!

Nao temos nenhum design especifico que podemos compartilhar. Mas, somos uma agencia digital entao aparece projeto de todo o tipo. Animacao eh apenas um dos itens no escopo dos projetos. 

O nosso desafio atual eh ter alguem que seja responsavel por `criar components reutilizaveis` para cada projeto e garantir que o CSS deles rendenrize perfeitamente cross browsers. Idealmente, depois de 2 ou 3 projetos, essa pessoa vai ser responsavel por criar uma lib de components que vamos poder reutizar entre projetos, reduzindo custos e aumentando a confianca de que o que eh entregue para os clientes funciona e eh `pixel perfect` em qualquer browser ou dispositivo.

Com o surgimento de React e outros frameworks, temos hoje no mercado bastante frontend devs que se especializaram em React (por exemplo) sem ter conhecimento dos fundamentos basicos de CSS. Eu, me incluo nessa lista porque comecei direto com React Native depois de 15 anos trabalhando com C++. Quando a gente passa pra analisar quem trabalha com React e tem um nivel avancado de CSS, a lista diminui ainda mais. A definicao de avancado por ser um pouco abstrata e relativa, mas se vc consegue analisar qq codigo CSS e explicar o porque aquilo esta sendo usado ou o porque aquilo nao deveria esta sendo usado, se vc revisa codigo de devs juniors e ajuda eles a evitar problemas com CSS... Na minha opnicao, esses sao indicadores de que alguem tem conhecimento avancado em uma determinada area. Entao, eu utilizaria o mesmo pra CSS.

**Comment by vncscoelho** [comment]
Até quando posso enviar? Não obtive resposta no Twitter. Obrigado.

**Comment by nativedone** [comment]
> Até quando posso enviar? Não obtive resposta no Twitter. Obrigado.

Opa @vncscoelho Acabei de voltar pra Australia. Vou precisar de no minimo uns 2 dias pra me organizar novamente. Semana que vem vou entrar em contato com todo mundo que mandou msn pelo twitter.

**Comment by rzorzal** [comment]
A vaga ainda está aberta ?

**Comment by mrangel-jr** [comment]
@nativedone , a vaga ainda está aberta ? Eu não tive retorno algum de meu projeto.
