### ISSUE TITLE
[Belo Horizonte] Front-End Developer Estágio na ASSOWEB

### ISSUE THREAD

**Issue by megandavulpi** [frontendbr/vagas#2407]
### Sobre a empresa: Agência Assoweb

Somos uma agência de Comunicação e Marketing Digital orientados à Performance Criativa. Nosso propósito: "Gerar valor, transformação e impacto em pequenas, médias e grandes empresas, fazendo do meio digital uma grande fonte de aquisição de clientes. Sempre de maneira autêntica e respeitando nossos valores. "

### Descrição:

Estamos com algumas instabilidades. Caso não consiga se cadastrar por aqui, envie seu currículo com o assunto "vaga/nome da empresa" para bruna.valerio@vulpi.com.br :)

### As habilidades necessárias:

JavaScript;
PHP;
HTML e CSS;

### O que brilharia os nossos olhos?

Wordpress;
Beneficios:

### Além de um ambiente bem descontraído, horários flexíveis e muito aprendizado, aqui você terá:

Vale Refeição;
Vale Transporte;
Incentivo aos estudos com cursos Allura;

### Você gostará de trabalhar aqui se:

Acredita que aprender mais sobre tecnologia e soft skills vão fazer de você um(a) profissional melhor;
Gosta de interagir com a galera do trabalho;
É normalmente inconformado(a) com coisas que não funcionam e gosta de mudar o jogo;
Quer entrar para o Desenvolvimento ou sair da zona de "Iniciante" para "Júnior";
Gosta de compartilhar conhecimento;

### Informações complementares:

A contratação é CLT;
Vaga 100% presencial;
Estamos localizados no bairro Vila Ermelinda - Belo Horizonte, MG. (Spoiler: Estaremos em breve de casa nova! 🤫🤩);

Tipo de contrato:
Estágio

Nível de experiência:
Junior Iniciante 

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/assoweb_estágio

**Comment by eriktos** [comment]
Tenho interesse!
