### ISSUE TITLE
[São Paulo] Desenvolvedor Front End

### ISSUE THREAD

**Issue by raphaguasta** [frontendbr/vagas#241]
## Local

Av. Faria Lima, São Paulo - Pinheiros

## Requisitos

- HTML5
- CSS3
- Javascript
- Desenvolvimento Responsivo
- React
- Redux

## Contratação

A combinar

## Nossa empresa

A Startup que está mudando o varejo

## Como se candidatar

Por favor envie um email para cv@uolet.com com seu CV anexado - enviar no assunto: Vaga para desenvolvedor Front End

![front](https://cloud.githubusercontent.com/assets/6708227/22519771/d10bc422-e898-11e6-83fb-c992e353a60a.jpg)

**Comment by LFeh** [comment]
Opa, qual nivel?

**Comment by raphaguasta** [comment]
Pleno e/ou Sênior
