### ISSUE TITLE
[Casa Forte - Recife] Front-end developer na Guava

### ISSUE THREAD

**Issue by acmh** [frontendbr/vagas#2411]
## Descrição da vaga

Se você é uma pessoa desenvolvedora de front-end que ama desenvolver aplicações rápidas, acessíveis e bem feitas, gosta de um ambiente de trabalho leve, repleto de colaboração, discussões profundas (mas respeitosas), e memes, vem fazer parte da Guava! (-:

## Local

Escritório, Recife - Casa Forte

## Benefícios
- Plano de saúde SulAmérica (50%)
- Seguro de vida
- Auxílio alimentação (R$ 500/mês)

**Diferenciais**

- Custeio de viagem para até duas conferências por ano⁣⁣
- Open bar de bebidas e lanches
- Macbook Pro + Monitor 27” + teclado e mouse
## Requisitos

**Obrigatórios:**

- Proficiência em JavaScript/ES6⁣⁣
- Pelo menos dois anos de experiência com front-end⁣⁣
- Experiência com Vue.js, React ou Angular⁣⁣
- Inglês intermediário⁣⁣

**Diferenciais:**

- React Native⁣⁣
- APIs (REST/GraphQL)⁣⁣
- PWAs⁣⁣
- Otimização de front-end⁣⁣
- Tecnologias de back-end⁣⁣
- Testes automatizados⁣⁣
- Gostar de HTML, CSS e design de interação⁣⁣
- Curso superior na área de tecnologia⁣⁣
## Contratação

CLT com salário entre R$ 5,7k a 7,7k

## Nossa empresa

Somos um estúdio de software ousado, que nasceu com a missão de unir sistemas sólidos a interfaces fluidas. Nosso objetivo é resolver problemas reais através de software útil, cativante e de alta qualidade. Estamos há mais de oito anos no mercado e neste período construímos produtos que vão desde MVPs para startups até softwares de alta demanda. Com clientes no Brasil e nos EUA, já atuamos em áreas tão diversas como engenharia elétrica, saúde e até *e-commerce* de lingerie. Saiba mais sobre a Guava em https://guava.software/about.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo. E-mail para contato em caso de não haver resposta: hello@guava.software

## Como se candidatar

É só mandar seu currículo, portfólio, Github, LinkedIn e/ou o que mais você achar relevante para vagas@guava.software (vaga aberta até 23/09).

## Labels
- 🏢 Flexível
- 🏢 Presencial
- 👨 Pleno
- ⚖️ CLT
- 💰 5,7k a 7,7k

**Comment by pedroch4610** [comment]
Ótima vaga! Uma dúvida... o range do salário vai de 5,7k a 7,7k ou de 5k a 10k?

**Comment by iansilva6** [comment]
Enviado!

**Comment by acmh** [comment]
@pedroch4610 o range vai de `5,7k a 7,7k` conforme a descrição. Ao cadastrar a vaga vi esses labels já definidos, acho que é só para indicar um intervalo. Obrigado!

**Comment by felipefialho** [comment]
Editei pra evitar confusão
