### ISSUE TITLE
[remoto] Front-end Developer na Eureca

### ISSUE THREAD

**Issue by carolinabigonha** [frontendbr/vagas#2412]
## Descrição da vaga

Procuramos uma pessoa para trabalhar em equipe no desenho, desenvolvimento e manutenção front-end da plataforma de educação e seleção da Eureca. A pessoa irá atuar diretamente na construção de uma plataforma web feita em ReactJS. 

## Local

- **Trabalho remoto**: a Eureca é uma empresa gerida e operada em um modelo virtual e não presencial. Isso significa que você pode ser de qualquer do lugar do Brasil e do mundo e isso não te impedirá de trabalhar com a gente. Quanto mais gente de lugares diferentes, melhor. 
- **Imersões mensais do time Eureca e imersões anuais do Grupo Anga**: normalmente no estado de São Paulo, esses são momentos de encontro de todo o time para promover conexão, alinhamentos de estratégia e celebração. 

## Benefícios

- **Acordo de férias flexível**. Você tira férias quando e como quiser, combinando com o seu time e avisando com antecedência. 
- **Sistema de Zelo Anga**. O Sistema de Zelo Anga tem como objetivo promover o autocuidado de todos os membros do Grupo, através de oportunidades, parcerias e apoio financeiro. Você recebe um valor mensal para investir em saúde e bem estar, experiência de trabalho, desenvolvimento humano ou cultura. Você escolhe a melhor forma de usar o dinheiro. 

#### Nosso jeito de trabalhar

- **Eureca faz parte do Grupo Anga**. [Conheça aqui um pouco mais da nossa cultura.](http://www.grupoanga.com/cultura/) Colaboramos de forma consciente, buscando coerência entre quem somos e o que fazemos. São esses os princípios que servem como guia para manter essa coerência. Eles são a base para qualquer decisão que tomamos. São o norte para como buscamos nos comportar todos os dias, seja individual ou coletivamente.
- **Acreditamos em um jeito diferente de trabalhar e criamos o AngaOS.** Foi criado a partir da inspiração por diversos sistemas de autogestão desenvolvidos ao longo do tempo, especialmente a Sociocracia 3.0 e a [Holacracia](https://www.holacracy.org/). Inspirado, também, por práticas de organizações que admiramos, desenvolvemos nosso jeito de gerir, de forma a distribuir poder e confiança de forma pró-ativa. 
- **Somos #officeless**. Para nós, trabalho não é apenas um lugar ou um horário: é um estado no qual estamos abertos a deixar fluir nosso propósito e nossa energia, realizando mudanças positivas para a nossa realidade. Nós trabalhamos com autonomia porque confiamos uns nos outros e praticamos a autogestão porque respeitamos o que é melhor para cada um. É por isso que, para nós, seja em São Paulo, Nova York ou Lisboa, às 8 da manhã ou às 7 da noite, na segunda ou na quinta-feira, o trabalho pode acontecer em qualquer lugar, a qualquer tempo. São os nossos acordos que definirão nossa rotina e como iremos colaborar juntos para transformar intenção em ação. E assim, conseguiremos construir uma organização em que cada um contribui com a sua melhor versão todos os dias.

## Requisitos

**Obrigatórios:**
- Formação em Ciência da Computação, cursos correlatos ou experiência prática equivalente
- Experiência na construção de soluções em ReactJS
- Comunicação interna e externa feita com clareza

**Desejáveis:**
- Demonstrar experiência com testes
- Experiência na construção de APIs / GraphQL
- Demonstrar experiência em trabalho com metodologias ágeis
- Experiência com diversos tipos de desafios de negócio/produto

**Diferenciais:**
- Domínio de tecnologias na nuvem, em especial AWS
- Experiência construindo soluções em Python

## Contratação

- PJ a combinar
- Remuneração compatível com o mercado de acordo com a experiência da pessoa. 

## Nossa empresa

A Eureca é uma empresa de educação e seleção focada no público jovem! Queremos promover a melhor experiência de primeiro emprego para os líderes do futuro, por isso, os ajudamos a encontrar a melhor oportunidade de estágio ou trainee naquela empresa dos sonhos. Quando o jovem se candidata para uma oportunidade pela Eureca, ele não só passa por uma seleção: ele também passa por módulos educativos, treinamentos e desafios que o qualificam e o preparam melhor para o mercado de trabalho, mesmo que ele não tenha sido bem sucedido no processo seletivo em si.

### Time de Produto
O time de Produto na Eureca é responsável por descobrir, criar e manter as soluções tecnológicas que sustentam a proposta de valor da Eureca. Hoje a plataforma é utilizada por jovens do Brasil e do mundo, por consultores internos e por nossos clientes. Somos um time de pessoas de Produto, Design e Engenharia que trabalha lado a lado testando e implementando novas soluções alinhadas com a nossa visão e de forma guiada a dados. Nossa inspiração é alcançar jovens de cada canto do Brasil e do mundo promovendo oportunidades de desenvolvimento pessoal e profissional. :)

## Como se candidatar

Por favor se inscreva no link [https://bit.ly/quero-trabalhar-na-eureca](https://bit.ly/quero-trabalhar-na-eureca) e escolha a vaga Front End. 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: timedeproduto@eureca.me

## Labels
- ReactJS
- PJ
- Remoto
- Pleno

**Comment by halkliff** [comment]
Enviado! Aguardando retorno.
