### ISSUE TITLE
[Londrina] Front-end Developer na XBrain

### ISSUE THREAD

**Issue by TBRANDAO** [frontendbr/vagas#2413]
## FRONT-END
Projeto bazinga em NodeJS, etc.

## LONDRINA - PR

EMPRESA - LONDRINA P- PR

## Benefícios

- Plano de saúde 100% custeado pela empresa
- VR de R$16,60/dia
- Auxílio estudo 150,00
-confraternizações mensais
- ...

#### Diferenciais

-1:30  de almoço
- frutas, café, bolacha
- Intervalo 0:10 de manhã e á tarde
- sala de jogos, piscina, liberação do espaço para confraternização familiar.
- ...

## Requisitos

**Obrigatórios:**
- experiência com Node
-experiência com mongodb e express

**Desejáveis:**
- conhecimentos em ruby on rails
- conhecimentos em C#

**Diferenciais:**
- projetos opensource

## Nossa empresa

Aqui na XBRAIN somos certificado pelo GPTW(melhores empresa para se trabalhar)...

## Como se candidatar

Por favor envie um email para thiagobrandao@xbrain.com.br com seu CV anexado - enviar no assunto: Vaga NodeJS

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até XX dias após cada processo.
E-mail para contato em caso de não haver resposta: feedbacks@empresasuperlegal.com.br

## Labels

- CLT
- Júnior
- Pleno
- Sênior

**Comment by clautercarlos** [comment]
Espero que o diferencial do horário de almoço seja uma falha e o correto seja  bullet list e não que as pessoas tenham hora de almoço negativa. :)

**Comment by thejohnpg** [comment]
Enviado =)

**Comment by stochiconrado** [comment]
A vaga está disponível?

Em seg., 16 de set. de 2019 às 08:45, TBRANDAO <notifications@github.com>
escreveu:

**Comment by TBRANDAO** [comment]
sim temos uma vaga em aberto ainda.



Em qui., 7 de nov. de 2019 às 17:41, Conrado Stochi <
notifications@github.com> escreveu:
