### ISSUE TITLE
[Rio de Janeiro] Sr. Frontend Developer  (Intelie/Rio) 

### ISSUE THREAD

**Issue by jlbfalcao** [frontendbr/vagas#242]
# Descrição da vaga

A Intelie é uma empresa focada em transformar dados em resultados para seus clientes. Para isso, contamos com um time multidisciplinar de especialistas, desde desenvolvedores e analistas de negócio a engenheiros de software e designers que fazem nossos produtos terem uma cara única.
 
Nossa equipe de produto está crescendo e precisamos desenvolvedores de software, com experiência em frontend, para trabalhar no desenvolvimento de nossos produtos. Caso você esteja em busca de um ambiente com constantes desafios e o perfil descrito abaixo, nos envie o seu currículo. Vamos conversar!
 
## No dia a dia, será sua responsabilidade:
* Trabalhar com equipe de produto, no desenvolvimento de novas features e extensões para nosso produto: o Intelie Live;
* Discutir com equipe melhores abordagens o frontend (arquitetura, interatividade e integração com o backend)
* Garantir a qualidade do software, através de reviews e testes automatizados;
* Avaliar uso de novas soluções dentro do nosso stack;
* Garantir performance e qualidade das Interfaces;
* Trabalhar junto com equipe de UX, melhorando a experiência de nossos produtos

## De nós, espere:

* Ambiente dinâmico
* Salário compatível com o mercado
* Benefícios (VT, VA, VR e planos médico e odontológico)
* Fomento a aprimoração profissional

## Requisitos
* Proficiente em JavaScript, inslusive ES6, JSX, flow
* Experiência em React, Redux
* Conhecer babel, webpack
* Desenvolvimento de testes em JS (hoje usamos o Jest)
* Conhecimentos avançados de CSS (experiência em SCSS necessária)
* Conhecimento no eco-sistema Java (ferramentas, build, etc) e no protocolo HTTP
* Desenvolvimento web para dispositivos móveis (design responsivo, otimização de carregamento, etc)
* [bonus] Desenvolvimento de visualizações com D3 ou outra ferramenta semelhante

## Por fim, é essencial:

* Ser comunicativo (para se posicionar, entender e debater com diversos times)
* Ter flexibilidade (para se adaptar e estar disposto a sugerir mudanças)
* Ter resiliência (nosso projeto é um tanto complexo)
* Ter espírito de equipe (afinal, somos um só)

http://carreiras.intelie.com.br/o/sr-frontend-developer?source=frontendbr

**Comment by jlbfalcao** [comment]
Coloquei errado. Era Rio coloquei SP (sorry)

**Comment by LFeh** [comment]
PJ ou CLT?

**Comment by jlbfalcao** [comment]
CLT
