### ISSUE TITLE
[São Paulo] Front-end Developer na Agêcia E-Plus - Vtex

### ISSUE THREAD

**Issue by rodrigoEplus** [frontendbr/vagas#2423]
## Oportunidade:

A Agência e-Plus está em busca de um desenvolvedor front-end para trabalhar com projetos VTEX. Trabalhará em conjunto com designers, desenvolvedores e analistas para juntos desenvolverem uma excelente experiência para os usuários.

## Requisitos:

- Capacidade para escrever código consistente, eficiente, minimalista, reutilizável e escalável
- Desenvolver código semanticamente correto, otimizado para SEO e com boa performance (tempo de carregamento)
- JavaScript, HTML5 e CSS3
- Integração de Sistemas com API
- Controle de versão (Git)
- Experiência com bibliotecas de Javascript, como jQuery
- Experiência com Sites Responsivos
- Familiaridade com Photoshop
- Facilidade de trabalho em equipe
- Proatividade
- Qualidade na entrega de projetos

## Desejáveis:

- Portfólio

## Diferenciais:

- Conhecimento avançado em javascript (sem plugins ou bibliotecas);
- Experiência em construção de e-commerce na plataforma VTEX;
- SASS e/ou LESS;
- Boas noções de usabilidade;
- Task runners (Grunt / Gulp);
- React e PHP

## Salário:

- À negociar;

## Oferecemos:

- Regime CLT;
- Assistência Médica;
- Seguro de Vida;
- Vale Refeição;
- Vale Transporte;
- PLR;
- Carga horária abaixo do mercado, 7 horas diárias;
- Frutas e Café a vontade;
- Day-Off no dia de seu aniversário;
- Um ótimo ambiente de trabalho;

Local de trabalho: Vila Mariana - Zona Sul/SP - Próximo ao Metrô Santa Cruz

## Como se candidatar?

Para se candidatar, favor fazer o challenge https://github.com/rodrigoEplus/challenge seguindo os passos do mesmo e boa sorte =D

## Labels

- CLT
- Júnior
- Pleno

**Comment by victorhsantiago** [comment]
Uma dúvida, para realizar o desafio pode usar algum framework?

**Comment by rodrigoEplus** [comment]
Bom dia, Victor!
Tudo bem?

Sim, pode ser usado framework.

Em sáb, 21 de set de 2019 às 19:16, Victor Santiago <
notifications@github.com> escreveu:
