### ISSUE TITLE
[Santo André, SP] Front-end Developer na Din Digital

### ISSUE THREAD

**Issue by kvnol** [frontendbr/vagas#2426]
## Descrição da vaga

Buscamos o/a profissional capacitado a atuar na montagem de layouts em HTML, CSS, JavaScript, integração de temas Wordpress.
O conhecimento em construção de SPAs utilizando Angular, React ou Vue é um diferencial.

Importante ter uma boa comunicação e proatividade.
Nosso formato de trabalho permite que cada integrante do time tenha uma maior autonomia sobre suas atividades fazendo autogestão e sugestões embasadas.

Acreditamos ser imprescindível gostar do que faz para ter bons resultados e vencer desafios. Nesse sentido incentivamos o conhecimento do time disponibilizando acesso a video aulas e treinamentos, à disposição de seu interesse.

Responsabilidades e atribuições:
- Conhecer sobre o workflow do Front-end, como pré-processadores, compiladores, montagem responsiva, preocupação com SEO, velocidade de carregamento, metodologia BEM e SMACSS;
- Trabalhar com projetos Wordpress, fazendo a integração da montagem estática com o CMS Wordpress, criando post types personalizados;
- Integração com serviços externos como redes sociais e APIs em geral. O conhecimento para trabalhar com requisições assíncronas é fundamental.

## Local

Escritório em Santo André, SP

## Benefícios

- Vale-transporte;
- Vale-refeição;
- Horário Flexível.

## Requisitos

- Git;
- HTML5, CSS3, SCSS;
- Montagem responsiva;
- Javascript, jQuery;
- NPM, Webpack, Gulp;
- Metodologia SMACSS, BEM;
- Experiência com integração REST;
- Experiência com SEO (técnico);
- Wordpress.

## Contratação

PJ ou CLT, a combinar

## Sobre a DIN DIGITAL

Somos apaixonados por boas ideias e especialistas em desenvolvimento web e mobile. Nossa missão é ser o melhor estúdio de programação para agências de publicidade e startups. Para isso, buscamos unir programação de alta qualidade, agilidade e comprometimento.

## Como se candidatar

Candidate-se pelo Trampos: https://trampos.co/oportunidades/151470

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: mario@dindigital.com

## Labels

- Alocado
- CLT
- PJ
- Pleno
- Sênior

**Comment by renanmurilo** [comment]
@kvnol Enviado

**Comment by kvnol** [comment]
Vaga fechada.
