### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor Front-End

### ISSUE THREAD

**Issue by stoque** [frontendbr/vagas#243]
## Local

Presencial em Rio de Janeiro, RJ - Barra da Tijuca

## Benefícios

- Plano de saúde
- Vale alimentação
- Vale transporte

## Requisitos

**Obrigatórios:**
- HTML5
- CSS3 / Pré processador (Sass, Stylus ou Less)
- JavaScript (Vanilla)
- Conhecimentos em Git
- Gulp
- Linux

**Desejáveis:**
- BEM, SMACSS, OOCSS
- Boas práticas de SEO e Acessibilidade
- Conhecimento básico de PHP e XML
- Scrum

**Diferenciais:**
- Algum framework JavaScript (React, Angular ou Vue)
- Docker
- Experiência com E-Commerce (Magento)
- Node

## Contratação

CLT

## Como se candidatar

Por favor envie um email para falecom@intercase.com.br com seu CV anexado - enviar no assunto: VAGA FRONT-END

**Comment by stoque** [comment]
Nível Junior / Pleno

**Comment by thallesmarchetti** [comment]
Enviado!
