### ISSUE TITLE
[Rio de Janeiro] Front-end React Developer na Total Commit

### ISSUE THREAD

**Issue by dekionbr** [frontendbr/vagas#2430]
## Descrição da vaga

Dev nível Pleno(ou superior) com dois anos de experiência com JavaScript. Ter a experiência de já ter participado de pelo menos dois projeto com React. 
Disponibilidade imediata.

## Local

Escritório, Rio de Janeiro - Barra da Tijuca

## Benefícios
- VR R$ 500,00

#### Diferenciais

- Horário Flexível (entrada até as 11hs - 8hs por dia) .
- Guloseimas e frutas a vontade.
- 1 dia de Home Office por Semana.
- Sala de jogos

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com projetos javascript (ECMAScript)
- Ter trabalhado em pelo monos 2 projetos em REACT.

**Diferenciais:**
- conhecimentos em NodeJS (back-end)
- conhecimentos em Ruby on Rails
- conhecimentos em C#
- projetos opensource
- Inglês

## Contratação

PJ R$7.000,0

## Nossa empresa

Trabalhamos focados em oferecer outsourcing a nossos clientes, o que dá ao profissional uma maior tranquilidade de se trabalhar, ao mesmo tempo, que garante maior envolvimento do cliente com seu projeto.

## Como se candidatar

Por favor envie um email para Julio Silveira <julio.silveira@totalcommit.com> com seu CV anexado - enviar no assunto: Vaga React

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: Consultoria RH <consultoriarh@fulllab.com.br>

## Labels

- Alocado
- PJ
- Pleno
- Sênior

**Comment by evertonProgramadorCriativo** [comment]
7.000 reais e  muito pouco para PJ
