### ISSUE TITLE
[Belo Horizonte] Front-end Developer na PELANDO

### ISSUE THREAD

**Issue by megandavulpi** [frontendbr/vagas#2434]
### Sobre a empresa: Pelando

Pelando A maior comunidade de promoções do Brasil Pelando é uma comunidade de caçadores de promoções, nossos caçadores encontram promoções de verdade e compartilham com a comunidade. Comece a caçar promoções você também!

### Ocupações do cargo

Será de responsabilidade desde profissional, criar novas funcionalidades, procurar novas soluções tecnologicas .

### Benefícios

Aqui você encontra um ambiente 100% coloborativo, focado em transformar a história da caça a promoções.

Além de desfrutar de uma empresa com foco 200% na experiência do usúario e sua individualidade. 

### Aqui você terá:

Horário Flexivel ( Flexivel mesmo!)
Vale Alimentação (Sem desconto no salário!)
Vale Transporte (Sem desconto no salário!)
Plano de saúde cobertura nacional, Amil (Sem desconto no salário!)

### Aptidões e qualidades

Para tornar-se parte desse time, é preciso que você, seja fera em:

● Experiência com integração de aplicações WEB e APIs;
● Mande bem em React
● Conhecimento em CSS, Sass, Less, Flexbox, Webpack;
● Integrações entre front-end e back-end;
● Performance e métricas WEB, como SEO, Analytics;
● Conhecimento em versionamento de código.

### Informações da empresa

A Pelando é uma empresa internacional, que vem crescendo cada dia mais.

Hoje está iniciando um processo de transformação tecnologico desenvolvendo um braço do produto 100% brasileiro.

Com a intenção de alcançar o amplamente o mercado e atender todos os perfis e suas individualidades.

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/pelando_frontend

**Comment by allancarlos123** [comment]
Boa noite!
Há chance de ser remoto?

**Comment by BrenoRyan-dev** [comment]
Número encontra sem wpp
