### ISSUE TITLE
[São Paulo] Front-end Developer na OSF Global

### ISSUE THREAD

**Issue by alessandra-abreu** [frontendbr/vagas#2436]
## Descrição da vaga

Projeto em Angular 2+;

## Local

Escritório, São Paulo - na região central, próximo a estação da Luz, Glicerio.

## Benefícios

- Bradesco Saúde (pago 100% pela empresa)
- Seguro de vida
- VR de R$ 27,00/dia
- Bônus Educação de R$150,00/mês
- Bônus Esporte de R$40,00/mês
- Programa de mentoring
- Certificações pagas pela empresa
- Plano de carreira bem delineado (avaliação de performance de 4 em 4 meses)

#### Diferenciais

- Empresa global presente em mais de 19 países

## Requisitos

**Obrigatórios:**

- 2 anos de experiência com angular 2+
- Experiência com GIT

## Contratação

CLT + Benefícios (citados acima)

## Nossa empresa

OSF Global Services is a trusted technology consultant and technology integrator enabling companies to succeed over the greatest challenges in the world’s rapidly changing business environment. With expertise in cloud and mobile application development, enterprise CRM solutions, leading ecommerce platforms and integrated content management solutions.

## Como se candidatar

Por favor envie um email para alessandra.abreu@osf-global.com com seu CV anexado - enviar no assunto: Vaga Angular 2+

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias úteis após cada processo.
E-mail para contato em caso de não haver resposta: alessandra.abreu@osf-global.com

## Labels

- Alocado
- CLT
- Pleno
- Senior
- Angular

**Comment by lucasferreiralimax** [comment]
Feedback e resposta de contato super rápido
Esclarecimento e alinhamento sobre as expectativas da vaga e benefícios super claro e transparente.

Obrigado pelo o retorno inicial e o feedback @alessandra-abreu 

## Parabéns

**Comment by felipefialho** [comment]
Legal a resposta do @lucasferreiralimax. Parabéns @alessandra-abreu 🍻
