### ISSUE TITLE
[REMOTO] Desenvolver Angular + Ionic na Nth.work

### ISSUE THREAD

**Issue by fmoura-ehab** [frontendbr/vagas#2437]
## Descrição da vaga
Aplicativo educacional. 
Freelancer, ao menos 80 horas / mês (Temos demanda para mais horas, as 80 é o mínimo)

Front-End Developer Angular + Ionic + JS/Typescript + dominar HTML5 + CSS3 + Desejável experiência com mapas, jogos ou aplicativos com interface super customizada.

## Local
REMOTO

Diferenciais
Freelancer 80 horas mensais (ou mais)

Requisitos
Obrigatórios:

- 2 anos de experiência com desenvolvimento com Angular e Ionic.
- Sólidos conhecimentos de HTML5, CSS3, design responsivo. Capaz de aplicar, com perfeição, interfaces à partir do trabalho de um designer.
- Preocupado com a experiência do usuário, e não apenas com o código.
- Altamente responsável e com muita iniciativa.
- Profissional, versátil e acostumado à metodologias ágeis.

Diferenciais:
- Espaço para aprender muita coisa!
- Equipe pequena, multidisciplinar e internacional

Contratação
Freelancer

Nossa empresa
Nth.work - Great design, cutting edge technology and product excellence. The solutions of tomorrow, today. Our team of specialists can help you reshape your business and create innovative products.

We’re an international group of creative technologists and business folks. From ideation, to development and launch of unique products, we nail it!
https://nth.work ("Nth o quê?" Em caso de dúvida: https://www.nth.work/what-nth/ )

Como se candidatar
Por favor envie um email para info@nth.work com seu CV anexado, link para o LinkedIn, link para GitHub ou outros projetos anteriores - enviar no assunto: Vaga FrontendBr Angular + Ionic + Design

Tempo médio de feedbacks
- Costumamos enviar feedbacks em até 2 dias após cada processo.
- E-mail para contato em caso de não haver resposta: info@nth.work

Labels
Remoto
Freelancer
Angular
Ionic
HTML5
CSS3

**Comment by juulhao** [comment]
encaminhado :)
