### ISSUE TITLE
[São Paulo] Front-end Developer na Docket 

### ISSUE THREAD

**Issue by carolinaleaodocket** [frontendbr/vagas#2438]
**FRONT END DEVELOPER** 

A Docket é uma startup de tecnologia que esta reiventando a forma como as grandes empresas lidam com a obtenção de documentos e certidões. Através do uso intensivo de tecnologia, dados e inteligência artificial tornamos o dia a dia de nossos clientes mais ágil, transparente e eficiente. Mas queremos alcançar muito mais! E para isso estamos buscando profissionais que estejam alinhados com a nossa cultura e nosso propósito. \o/

**Aqui na Docket você irá:**
- Irá atuar com desenvolvimento e manutenção da Plataforma Web B2B

**Requisitos obrigatórios**
- Estiver cursando ou ser formado em algum curso na área da tecnologia da informação como Ciências da Computação, Sistemas de Informação ou áreas afins
- Conhecimentos em HTML 5, CSS 3, JavaScript, JQuery, Ajax
- Experiência de pelo menos 1 ano na área.
- Ter participado de algum projeto de desenvolvimento Web relevante

**Será um diferencial**
- Se você conhecer algum framework como AngularJS, ReactJS

**O que oferecemos**
- Salário compatível com o mercado + VT + VR ou VA + Plano de saúde e odontológico + Seguro de vida + Improve Yoursel (auxílio estudo / lazer)
- Ambiente descontraído, criativo e oportunidade de crescimento acelerado. =)
- Local: Pinheiros
- Horário: 44 horas semanais

**Se candidate diretamente através da nossa página de carreiras:** https://docket.gupy.io/jobs/82404?jobBoardSource=gupy_public_page

**Comment by natalino1234** [comment]
Mandei o currículo =)
