### ISSUE TITLE
[São Paulo] Front-end Developer na meuDNA

### ISSUE THREAD

**Issue by darleisantossoares** [frontendbr/vagas#2439]
## Descrição da vaga
Buscamos uma pessoa desenvolvedora que tenha experiência com Angular e que tenha muita vontade de transformar a vida das pessoas para melhor. 

## Local

Presencial, avenida paulista, metrô brigadeiro.

## Benefícios

- Vale Refeição;
- Vale Alimentação;
- Vale Transporte ou Combustível;
- Plano de Saúde;
- Plano Odontologico opcional;

#### Diferenciais

- Gympass com reembolso para incentivo;
- Café da manhã fresquinho todos os dias;
- Programa de qualidade de vida (Nutricionista, Quick massage, Frutas);
- Parcerias com farmácias, SESC e outros locais para desconto;

## Requisitos

**Obrigatórios:**
- Experiência com frontend
- Experiência com CSS e HTML
- Experiência com PWA
- Experiência com pelo menos um framework de front (angular, react, vue e etc)
- Teste unitário/Teste integrado

**Desejáveis:**
- Conhecimentos em IONIC

**Diferenciais:**
- Conhecimentos em firebase
- Conhecimento de Google Cloud

## Contratação

CLT

## Nossa empresa

Estamos criando uma startup para mudar a forma como as pessoas vivem e tomam conta de sua saúde. No DNA de cada um de nós está codificado quem somos e como nosso corpo funciona. Nosso objetivo é democratizar o acesso a essa informações e empoderar as pessoas com ações que podem melhorar seu estilo de vida. Nossa startup vai utilizar a tecnologia da Mendelics - o laboratório genético com a maior capacidade de sequenciamento de DNA da America Latina.

## Como se candidatar

Por favor envie um email para darlei.soares@meudna.com com seu CV anexado - enviar no assunto: Vaga Angular

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

## Labels

- Alocado
- CLT

**Comment by victorhsantiago** [comment]
Olá, qual o nível de senioridade que estão buscando?

**Comment by darleisantossoares** [comment]
> Olá, qual o nível de senioridade que estão buscando?

Por enquanto
