### ISSUE TITLE
[São Paulo] Front-end Junior/Pleno

### ISSUE THREAD

**Issue by padil** [frontendbr/vagas#244]
## Descrição da vaga

Você vai cuidar da agência inteira na área de tecnologia (área de front-end), desde idéias em projetos grandes, até contratar um freelance de tecnologia em uma área específica.

## Local

Escritório, São Paulo - Jardins - Consolação

## Benefícios

- 2 horas de almoço
- VR + VT
- Salário compatível com o mercado

## Requisitos

**Obrigatórios:**
- Vontade de aprender sempre e inovar também.
- html, css, javascript.
- photoshop para recortes de layout.

**Desejáveis:**
- Jquery.
- Angularjs 1.5x.
- animações com greensock e com jquery.

**Diferenciais:**
- Portfólio
- projetos open source.

## Contratação

PJ a combinar

## Nossa empresa

Aqui na Dim&Canzian somos bem abertos e também você vai ter contato direto com o presidente e também com os Diretores de Criação.

## Como se candidatar

Por favor envie um email para lucas.padilha@dimcanzian.com.br/luana.trentin@dimcanzian.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

**Comment by brunooomelo** [comment]
Enviado!

**Comment by brunnolammyn** [comment]
Boa noite!! Gostaria de saber se avaga já foi preenchida.

**Comment by padil** [comment]
Vaga preenchida, thanks 👍

**Comment by LFeh** [comment]
Boa!
