### ISSUE TITLE
[Belo Horizonte] Front-end Developer Angular 8.2 Sênior no Bume

### ISSUE THREAD

**Issue by laiscurys** [frontendbr/vagas#2441]
O time de desenvolvimento é o coração do Bume. Por causa dele, conseguimos entregar aos nossos clientes uma ferramenta incrível para gestão e crescimento do perfil no Instagram, utilizando o que há de mais inovador entre as tecnologias do mercado. 

No Bume, você encontrará:

Desafios relacionados a desenvolvimento de produtos;
Oportunidade de trabalhar com algumas das tecnologias atuais do mercado;
Oportunidade de participar de novos projetos de longo prazo com ambição de alcance internacional;
Um time de profissionais empreendedores em um ambiente dinâmico e em crescimento constante;
Um ambiente flexível e informal.

Buscamos uma pessoa que:
Tenha conhecimento em versionamento de código (GIT);
Tenha senso crítico e se preocupa com UI;
Seja proativo trazendo sempre novas ideias para resolvermos nossos desafios;
Siga as tendências do mercado e que seja capaz de se adaptar rapidamente a novas tecnologias;
Tenha boa comunicação, trabalho em equipe, senso de organização, atenção a detalhes e foco.

Ter experiência  com AngularJS;
Ter experiência com Bootstrap
Ter experiência com CSS
Ter experiência com Typescript

Será considerado diferencial:
Já tenha trabalhado em uma equipe ágil.
Construção de testes de integração e unitários
Ter experiência com Angular
Ter experiência com SASS
Ter experiência com NGRX
Ter experiência com Gitflow
Escrever código limpo e coeso

Benefícios:
Vale transporte.
Vale refeição ou alimentação.
Plano de saúde Unimed.
Plano odontológico Unimed.
Unimed aéreo.
Frutas  à vontade no lanche.
PLR
Uma conta do Bume todinha sua.
Aulas de inglês parcialmente pagas pelo Bume.
Flexibilidade de horário.
No dress-code.

Você pode se candidatar por esse link: https://bume.recruitee.com/o/desenvolvedora-frontend-angularjs-senior-belo-horizonte
Se precisar de alguma informação adicional pode me procurar no cinthia.nebenzahl@bume.io

Detalhes da vaga:
Local de atuação: We Work - Savassi, Belo Horizonte;
40h semanais, com 8 horas diárias de segunda a sexta;

**Comment by fabiomirandaa** [comment]
Alguma possibilidade de remoto?
