### ISSUE TITLE
[Rio de Janeiro] Front-end Developer Jr na Fattoria

### ISSUE THREAD

**Issue by andreyBento** [frontendbr/vagas#2446]
## Descrição da vaga

Desejamos contratar alguém que tenha muita vontade de aprender e se desenvolver conosco. Neste cargo você trabalhará com os nossos Analistas de Sistemas, Designers e Gerentes de Projetos para desenvolver portais de grande porte, landing pages e muitos outros projetos web.

## Local

Escritório, Rio de Janeiro - Carioca

## Benefícios

- Vale Transporte
- Vale Refeição
- Seguro de Vida em grupo
- Plano de Saúde e odontológico Golden Cross

## Requisitos

**Obrigatórios:**
- HTML
- CSS
- Javascript (Básico)
- JQuery (Básico)
- Muita vontade de aprender

**Desejáveis:**
- Git
- Javascript (intermediário)
- SASS (Básico)
- Adobe XD ou Sketch (Básico)

## Contratação

CLT padrão

## Nossa empresa

A Fattoria é uma empresa com conhecimento sólido do mercado digital.
Atuamos da criação da marca, planejamento da campanha de marketing digital , outsourcing até o desenvolvimento de sistemas escaláveis e aplicativos mobile.

## Como se candidatar

Interessados enviar o currículo com a pretensão salarial para rh@fattoriaweb.com.br

## Labels

- CLT
- Júnior

**Comment by igorpinhh** [comment]
enviado.

**Comment by gabok2** [comment]
enviei tb

**Comment by GustavoPrizon** [comment]
Aceita pessoas de outra cidade?

**Comment by andreyBento** [comment]
> Aceita pessoas de outra cidade?

O Trabalho é alocado na empresa, 
então só podemos aceitar residentes do Rio de Janeiro, desculpe.

**Comment by Willjunger** [comment]
Que iraado! Já mandei :)

**Comment by MatheusRGuedes** [comment]
Serva para quem está cursando faculdade ?

**Comment by andreyBento** [comment]
> Serve para quem está cursando ainda faculdade ?

Sim.

**Comment by gabok2** [comment]
enviei o meu tem 1 semana n recebi nenhum feedback

**Comment by Marco-oli** [comment]
Que maneiro, currículo enviado!! :D

**Comment by andreyBento** [comment]
> enviei o meu tem 1 semana n recebi nenhum feedback

Contatei o RH e me disseram que vão entrar em contato com você. possivelmente ainda hoje.

**Comment by Marco-oli** [comment]
> > enviei o meu tem 1 semana n recebi nenhum feedback
> 
> Contatei o RH e me disseram que vão entrar em contato com você. possivelmente ainda hoje.

Vou receber um feedback tambem? rs

**Comment by andreyBento** [comment]
Vaga preenchida
