### ISSUE TITLE
[São Paulo] Front-end Developer na SUPPLYLABS

### ISSUE THREAD

**Issue by godois** [frontendbr/vagas#2448]
## Descrição da vaga

Estamos à procura de uma pessoa que será a referência em desenvolvimento frontend em nosso time.

Você será responsável por:

Ajudar na prototipação de produto.
Participar de discussões para levantamento de hipóteses de solução, nos ajudando a pensar novos produtos e novos módulos.
Codificar os aplicativos e colocá-los em produção, garantindo a qualidade de cada entrega.
Participar ativamente de decisões de tecnologias, infraestrutura, etc.

## Local

Rua do Paraíso, 347 - à 200m da estação paraíso do metrô. - São Paulo

#### Diferenciais

- Possibilidade de Home-office
- Happy-hour com o time

## Requisitos

**Obrigatórios:**
- Ter trabalhado em ao menos um projeto utilizando ReactJS, e que seja um produto digital. Isso é imprescindível!
- Ser fluente com tecnologias como HTML, CSS e Javascript.
- Saiba consumir APIs REST de forma otimizada. 
- Saiba versionar código e interagir com GIT.
- Que tenha noções de testes automatizados em aplicativos web.
- Gostar de trabalhar em grupo, ter empatia e humildade para liderar discussões.
- Ser curioso e estudioso.

**Diferenciais:**
- Ter atuado em outras startups é um diferencial.
- GraphQL

## Contratação

PJ a combinar

## Nossa empresa

A SupplyLabs foi criada com o propósito de entregar uma experiência 100% para gestão de cadeia de suprimentos. 
Nossa plataforma é responsável por toda gestão de compliance e sustentabilidade de uma cadeia de fornecimento.

## Como se candidatar

Por favor envie um email para marcio@supplylabs.com.br com seu CV anexado - enviar no assunto: Vaga ReactJS

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

## Labels

- Júnior
- PJ
- ReactJS

**Comment by GustavoPrizon** [comment]
CV enviado!

**Comment by gabrielrab** [comment]
Candidatura enviada!

**Comment by edn9** [comment]
Enviado!

**Comment by rlocatelli9** [comment]
Olá!
Ainda existe vaga em aberto para Jr.?
