### ISSUE TITLE
[São Paulo] Front-end Developer na iCasei

### ISSUE THREAD

**Issue by gustaum** [frontendbr/vagas#2449]
## Local

Av. Chucri Zaidan 1550, 31º andar - São Paulo - CEP:04711-130 - Próximo ao Shopping Morumbi

## Benefícios

- Vale-refeição no valor de R$ 28,00 por dia;
- Vale-transporte;
- Participação nos lucros (**até 2 salários baseados em metas**);
- Seguro saúde (Omint);
- Ajuda de custo para cursos, livros e palestras (**Até R$500,00 mês**);
- Horário Flexivel;
- Excelente localização;
- Ambiente de trabalho sensacional (**http://bit.ly/escritorio-icasei**);
- Massagem todas as segundas e quartas;
- Frutas na mesa;
- Gympass;

## Requisitos

**Obrigatórios:**
- Sólidos conhecimentos em HTML5, CSS3 (SASS/SCSS) e Javascript (ES6).
- Escrever código limpo e legível.
- Ter profunda preocupação com qualidade.
- Conhecimento em integração de REST APIs.
- Conhecimento em desenvolvimento de layout responsivo.
- Conhecimento com boas praticas para performance WEB (Javascript, CSS, HTML).
- Conhecimento de mercado desenvolvendo aplicação em AngularJS ou frameworks relacionados.
- Conhecimento com GIT (GitFlow).
- Inglês (técnico).

**Desejáveis:**
- Conhecimento de boas práticas de UX.
- Conhecimento em algum Framework JS.

## Contratação

CLT
**Faixa de Salário R$4.000,00 a R$5.000,00**

## Nossa empresa

iCasei Presentes e Intermediação de Negócios LTDA

## Como se candidatar

> Por favor preencher o formulário: **https://forms.gle/QoAjFsasqyKXe1Bw9**

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: frontend@icasei.com.br

## Labels

- Alocado
- CLT
- Júnior

**Comment by jimenez539** [comment]
CV enviado

**Comment by gustaum** [comment]
Vaga encerrada
