### ISSUE TITLE
[Alphaville, SP] Front-end Developer na MangoBits

### ISSUE THREAD

**Issue by thatigonc** [frontendbr/vagas#2451]
## Descrição da vaga

Programação Front End na equipe de desenvolvimento. 

## Local

Escritório, Alphaville - São Paulo

## Benefícios

- VR de R$ 18/dia
- VT

## Requisitos

**Obrigatórios:**

Necessário alguma experiência (cursos, projetos) com desenvolvimento web e com JavaScript e Angular.

## Contratação

CLT R$3.600,00 

## Nossa empresa

Empresa trabalha com as melhores soluções para desenvolvimento de aplicativos.

## Como se candidatar

Por favor envie um email para tatiane.goncalves@ taking.com com seu CV anexado.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

## Labels

- CLT
- Júnior

**Comment by GustavoPrizon** [comment]
CV enviado!

**Comment by GustavoPrizon** [comment]
o e-mail retornou

**Comment by thatigonc** [comment]
> o e-mail retornou

**Comment by thatigonc** [comment]
> o e-mail retornou

Gustavo, me envie no tatiane.goncalves@taking.com.br ou se preferir me envie via whatsapp: 1198530-4520.
