### ISSUE TITLE
[São Paulo - SP] Front-end Developer na Luiza Labs

### ISSUE THREAD

**Issue by Tautorn** [frontendbr/vagas#2452]
## Descrição da vaga
Buscamos Desenvolvedor (a) Front end  para compor o time na Tribo de Experiência Online do Magalu em São Paulo - SP.

Somos responsáveis por toda a experiência Online do APP e do nosso site, temos squads dedicadas para cada uma dessas experiências desde catálogo, busca, navegação até o checkout.

## Local
São Paulo - Zona Norte

## Benefícios
Temos todos os benefícios padrão de contratação CLT e outros como frutas, seguros de vida, massagem, previdência privada, descontos para compras no Magalu e Netshoes, entre outros.

## Requisitos
Obrigatórios:
- HTML5, CSS3, JS, ES6;
- Frameworks JS de templating/events, principalmente React;
- Experiência com SPA's
- Pré-processadores CSS (SASS, Less, PostCSS);
- Experiência com alguma metodologia atual de padrões de CSS/HTML (BEM, Atomic, outros);
- Git (usamos Github), NPM, yarn
- Webpack
- Criação de código limpo, legível e cross-browser (IE8+)

## Diferenciais:
Experiência com desenvolvimento de sites responsivos;
- Testes Automatizados (mochajs, jasmine, jest);
- Redux
- ES7

## Contratação
CLT - Pleno ou Sênior

## Nossa empresa

Utilizar a tecnologia para oferecer uma experiência diferenciada ao cliente. Este é o objetivo do LuizaLabs, o laboratório de **Tecnologia e Inovação do Magazine Luiza**. Aqui, nós somos responsáveis pela digitalização do varejo brasileiro através de autonomia e metodologias ágeis para inovar e encantar o nosso cliente. Somos ousados e não temos medo de errar. Você tem liberdade para fazer de forma simples e criativa. **O Magalu faz parte das melhores companhias para se trabalhar do Instituto Great Place to Work, por 19 anos seguidos**. Venha compartilhar conhecimento e impactar a vida de milhares de clientes no Brasil.

## Como se candidatar

Favor enviar curriculum ou LinkedIn com os contatos para o e-mail **riane.silva@luizalabs.com**

**Comment by lucasferreiralimax** [comment]
Sem nenhum retorno com um feedback ou resposta no e-mail.
Frustante o contato e candidatura nessa vaga 👎🏽

**Comment by Tautorn** [comment]
> Sem nenhum retorno com um feedback ou resposta no e-mail.
> Frustante o contato e candidatura nessa vaga 👎🏽

Olá @lucasferreiralimax , como são muitos candidatos podem demorar um pouco, mas todos estão sendo respondidos.

**Comment by lucasferreiralimax** [comment]
> > Sem nenhum retorno com um feedback ou resposta no e-mail.
> > Frustante o contato e candidatura nessa vaga 👎🏽
> 
> Olá @lucasferreiralimax , como são muitos candidatos podem demorar um pouco, mas todos estão sendo respondidos.

Olá @Tautorn 

Depois que comentei aqui recebi um e-mail de resposta.
Descobri que o processo já esta finalizado e nem tinham avaliado meu cv.

Frustante a avaliação e feedback do processo.
Perdi o interesse na vaga e no processo de vocês

Apenas minha opinião, tratado apenas como um número a ser preenchido.
