### ISSUE TITLE
[REMOTO] Front-end Developer na Vesti

### ISSUE THREAD

**Issue by andressavazpinto** [frontendbr/vagas#2453]
**Descrição da vaga:**
A Vesti está procurando um profissional PJ aplicado, para manter as aplicações e criar novas funcionalidades.

**Requisitos:**
- 2+ anos de experiência com Angular/Typescript
- Sólidos conhecimentos de HTML5, CSS3, design responsivo. Capaz de aplicar, com perfeição, interfaces à partir do trabalho de um designer.
- Preocupado com a experiência do usuário, e não apenas com o código.
- Altamente responsável e com muita iniciativa.
- Profissional, versátil e acostumado à metodologias ágeis.

**Diferencial:**
- Conhecimentos em Node.js
- Conhecimentos de deploy automatizado de projetos estáticos em ambient Amazon (S3, Cloudfront)
- Projetos Open source
- TDD
- Experiência com trabalho remoto 

**Vesti**
A Vesti está no mercado há 4 anos, oferecendo soluções para aumentar a produtividade das vendas no setor de vestuário atacado. (vesti.mobi)

**Processo**
Enviar currículo para andressa@vesti.mobi, com o assunto "[REMOTO] Front-end web (pleno/sênior) + seu nome" e o currículo em anexo. Envie também o valor/hora e disponibilidade para trabalhar conosco.

**Comment by danielswater** [comment]
Enviado
