### ISSUE TITLE
[Belo Horizonte] Fullstack Developer Pleno na nata.house

### ISSUE THREAD

**Issue by maryarossellini** [frontendbr/vagas#2455]
## Descrição da vaga

Vaga para Desenvolvedor(a) Fullstack Pleno. Trabalhamos com React, React Native e NodeJS. Nosso foco é a produção de aplicativos e sistemas web utilizando a linguagem JavaScript como sua principal ferramenta. 

## Local

Escritório, Belo Horizonte - Funcionários

## Benefícios

- Salário: entre 5000 a 7000 reais
- Vale Transporte ou Auxílio Combustível 
- Vale Alimentação ou Refeição de R$21,35/dia
- No dress code
- Happy hour mensal pago pela empresa
- Aula de inglês paga pela empresa 

## Requisitos

**Obrigatórios:**
- 3 anos (mínimo) de experiência como desenvolvedor
- 6 meses (mínimo) de experiência com React

**Desejáveis:**
- Ensino superior completo (graduado em 2017 ou antes)

## Nossa empresa

A nata.house é uma fábrica de software fundada em Belo Horizonte no ano de 2017. O seu foco é a produção de aplicativos e sistemas web utilizando a linguagem JavaScript como sua principal ferramenta. Com forte crescimento nestes dois anos de existência, a empresa se preocupa desde o início em atrair pessoas talentosas e com fit com a cultura e os objetivos da empresa, e pensa constantemente em maneiras de engajar, motivar e desenvolver os colaboradores para que seu crescimento acompanhe o da empresa. Para isso, estamos procurando por um(a) Desenvolvedor(a) Fullstack Pleno.

## Como se candidatar

Por favor envie um email para vaga@natahouse.com com seu CV anexado - enviar no assunto: Vaga Desenvolvedor(a) Fullstack Pleno

## Labels

- CLT
- Pleno

**Comment by imortalout** [comment]
Olá, tenho interesse.
Um otimo resumo do meu currículo está no meu curso que lancei na Udemy.
https://www.udemy.com/course/mouse-labs-aprendendo-a-aprender-design-vol-1
