### ISSUE TITLE
[Morumbi-SP] Front-end Developer JR na JUST DIGITAL

### ISSUE THREAD

**Issue by alicesrossi** [frontendbr/vagas#2456]
### Job description

Quem é a Just? Da uma olhada aqui:

Acreditamos no Design para criar experiências memoráveis em tudo o que fazemos e na engenharia de software para tornar isso possível.

Quando falamos em experiência para impactar pessoas, vemos isso nos produtos e serviços que entregamos, na relação com nossos clientes enquanto trabalham com a gente, quando os os clientes dos nossos clientes usam nossos produtos.
Queremos mostrar ao mundo que entregar resultado para hoje e amanhã pode ser mais simples do que se imagina, mais divertido do que se espera, e inesquecível para gerar laços e conexões duradouras entre pessoas.

Agora estamos em busca de desenvolvedores apaixonados por construir produtos digitais de qualidade, que estejam atualizados com as melhores práticas e tecnologias, envolvidos e engajados com comunidades de software.

Gostamos de pessoas proativas que somem ao time de desenvolvimento auxiliando na arquitetura da solução e preze pela qualidade do software como um todo.

### Conhecimentos necessários
HTML5 / CSS3 / JS / pré-processadores;
Conhecimento prático do fluxo de versionamento com GIT;
Conhecimento em frameworks Javascript;
Consumos de API;
CMS: Drupal ou Wordpress;

### Desejáveis
ReactJS ou VueJS;
Docker / SysOps.

### Local de trabalho

Morumbi - São Paulo

### Benefícios:

- Vale Refeição
- Vale Transporte
- Assistência Médica e Odontológica
- 8 Home Office/mês
- Seguro de Vida em Grupo
- Parceria com a Gympass e outros convênios em estabelecimentos e instituições de ensino

### Contratação
CLT

## Como se candidatar

**Vaga presencial!**

Por favor envie um email para entrepara@justdigital.com.br com seu CV anexado - enviar no assunto: Vaga Front end Jr

**Será que você é nosso próximo(a) Juster?**
Se candidata aqui e vem bater um papo com a gente!

## Labels

- CLT
- Júnior
- Homeoffice
- Front end
- Morumbi

**Comment by GustavoPrizon** [comment]
CV enviado!

**Comment by jimenez539** [comment]
CV enviado

**Comment by luccastrin** [comment]
Currículo enviado! Obrigado

**Comment by imortalout** [comment]
Olá, tenho interesse.
Um otimo resumo do meu currículo está no meu curso que lancei na Udemy.
https://www.udemy.com/course/mouse-labs-aprendendo-a-aprender-design-vol-1
