### ISSUE TITLE
[São Paulo] Arquiteto de Microserviços e API Manager na Capitale Tech

### ISSUE THREAD

**Issue by sergioohta** [frontendbr/vagas#2457]
## Descrição da vaga

Estamos em busca de pessoas do bem, esforçadas e que queiram crescer junto com a gente, para trabalhar como ARQUITETO DE MICROSERVIÇOS E API MANAGER em um de nossos clientes, uma empresa multinacional de grande porte.

## Local

no escritório do nosso cliente em São Paulo, próximo ao Shopping Morumbi... é pertinho do trem e metrô ;)

## Benefícios

Os benefícios dependem da forma de contratação, que pode ser PJ ou CLT.

#### Diferenciais

Trabalhar em projetos de grande visibilidade em empresa multinacional de grande porte, renomada e líder no mercado que atua.

## Requisitos

**Obrigatórios:**
• Experiência em Arquiteturas Orientadas a Serviço (SOA, Microserviços e API Management).
• Experiência em exposição e consumo de API Rest, SOAP e GraphQL.
• Experiência em Cloud AWS.
• Conhecimento de Docker e Ansible.
• Conhecimento em DevOps.
• Será o ponto focal do time técnico, implementando as melhores práticas de desenvolvimento.
• Desejável conhecimento em metodologias ágeis.

## Contratação

PJ ou CLT (a combinar).

## Nossa empresa

Aqui na Capitale oferecemos a empresas, serviços de tecnologia e de negócios digitais completos e integrados. Da infraestrutura de tecnologia da informação, desenvolvimento e mobilidade, tudo com um único objetivo, entregar resultados reais para sua empresa no mundo virtual. Temos como principal desafio traduzir as suas necessidades de negócio em uma visão de tecnologia e ajudá-lo na digitalização do seu negócio.

## Como se candidatar

Por favor envie um email para CV@CAPITALETECNOLOGIA.COM.BR com seu CV anexado - enviar no assunto: Vaga Arquiteto MS e API

## Labels

•	🏢 Flexível
•	🏢 Presencial
•	👴 Sênior
•	⚖️ CLT
•	⚖️ PJ
•	💰 10k-15k

**Comment by felipefialho** [comment]
Fala @sergioohta, beleza? É mais recomendável que poste essa vaga no @backend-br :)
