### ISSUE TITLE
[REMOTO] Full-stack Developer na DIVISIO

### ISSUE THREAD

**Issue by luizeduard0** [frontendbr/vagas#2458]
## Descrição da vaga
A Divisio é uma empresa sediada em Belo Horizonte - MG, especializada em desenvolvimento e consultoria utilizando as tecnologias React.js, React Native, Node.js, GraphQL, desde projetos pequenos até arquiteturas de aplicações de larga escala. Nós somos um time de especialistas, trabalhando em conjunto para lidar com os problemas de software mais difíceis, transformando idéias em realidade. Desenvolvemos produtos para grandes empresas, ajudando suas equipes internas a desenvolver habilidades necessárias para construir e manter sistemas complexos e escalonáveis.

Trabalhamos duro para promover uma cultura de apoio com uma hierarquia horizontal, onde todos podem aprender um com os outros. Nós garantimos que todos tenham oportunidade de crescimento e participação em decisões diárias. Você trabalhará remoto de qualquer lugar onde quiser, desenvolvendo novas aplicações, features e mantendo sistemas existentes para empresas que variam de tamanho, desde startups até grandes empresas. Quando você não estiver trabalhando em um projeto de um cliente, terá a oportunidade de contribuir com o desenvolvimento de nossos processos internos, sempre tendo voz para sugerir melhorias e oportunidade de contribuir para projetos open-source.

## Local
* Remoto

## Diferenciais
* Hierarquia horizontal: Todos tem voz na empresa
* Horário flexível
* Você pode trabalhar de qualquer lugar que quiser

### Obrigatórios:
* Experiência com JavaScript.
* Experiência com as principais APIs do React e bibliotecas comuns como Redux e Sagas.
* Experiência com desenvolvimento de aplicativos com React Native, mínimo entre 6 meses ~ 1 ano
* Entendimento sobre engenharia de Web: arquitetura client/server, REST, etc.
* Experiência com revisão e colaboração de código em equipes usando Git.

## Benefícios
* Descanso remunerados de 20 dias a cada 12 meses
* Horário Flexível
* Nos importamos com seu desempenho e não com sua carga horária
* Realmente nos importamos com seu crescimento

### Diferenciais:
* Experência com as APIs modernas do React: Context e Hooks
* Experiência com sistemas de tipos JavaScript: Flow
* Experiência com desenvolvimento Swift ou/e Java android

## Contratação
* PJ a combinar
* Remuneração R$5000-10000 (Dependendo da sua experiência)

## Como se candidatar
* Exclusivamente através: [http://www.interv.co/](http://www.interv.co/)

### Tempo médio de feedbacks
* Até 5 dias

## Labels
* PJ
* Remoto

**Comment by imortalout** [comment]
Olá, tenho interesse.
Um otimo resumo do meu currículo está no meu curso que lancei na Udemy.
https://www.udemy.com/course/mouse-labs-aprendendo-a-aprender-design-vol-1

**Comment by eduviictor** [comment]
Olá, estou bastante interessado. Tenho um conhecimento bom em quase todos os requisito, porém, não consigo realizar meu cadastro no aplicativo. Gera um erro ao inserir meu email.

**Comment by luizeduard0** [comment]
> Olá, estou bastante interessado. Tenho um conhecimento bom em quase todos os requisitos, porém, não consigo realizar meu cadastro no aplicativo. Gera um erro ao inserir meu email.

Opa, vou entrar em contato com você p/ vermos o que houve.

**Comment by apteles** [comment]
@luizeduard0, nunca usei essa aplicavo. A entrevista acontece já no momento do cadatro? Não tem como agendar?

**Comment by halkliff** [comment]
@luizeduard0 enviei lá! Aguardo o feedback.

**Comment by luizeduard0** [comment]
> @luizeduard0 enviei lá! Aguardo o feedback.

Recebido, entramos em contato na sequência

**Comment by luizeduard0** [comment]
> @luizeduard0, nunca usei essa aplicavo. A entrevista acontece já no momento do cadatro? Não tem como agendar?

Você pode fazer a entrevista no momento que achar melhor, não precisa agendar.
É só baixar, fazer o cadastro e fazer a entrevista quando for melhor pra você.

**Comment by luizeduard0** [comment]
> Olá, tenho interesse.
> Um otimo resumo do meu currículo está no meu curso que lancei na Udemy.
> https://www.udemy.com/course/mouse-labs-aprendendo-a-aprender-design-vol-1

Só aceitamos candidaturas através do app! abs

**Comment by rzorzal** [comment]
Essa vaga é fulltime ? Aceitariam um part-time ?

**Comment by luizeduard0** [comment]
> Essa vaga é fulltime ? Aceitariam um part-time ?

Idealmente procuramos por full-time, mas estamos abertos a conversar pois temos muita demanda. Essa resposta vai depender muito da sua experiência e características específicas. De qualquer forma o primeiro passo é se candidatar, ok?

**Comment by rzorzal** [comment]
Era o que eu queria ouvir :)

**Comment by eduviictor** [comment]
Enviado! Esperando ansiosamente por um retorno.

**Comment by luizeduard0** [comment]
> Enviado! Esperando ansiosamente por um retorno.

Recebido! Agora é só aguardar (;

**Comment by apteles** [comment]
@luizeduard0 tentei fazer a entrevista 2x, porém sempre que vai enviar o video não conclui. Fiz ontem, não deu, fiz hoje umas 12:40 e até agora está na barra de progresso, falando: "**Enviando sua entrevista**"... Inclusive falta pouco, porém assim como ontem não concluiu.

**Comment by luizeduard0** [comment]
> @luizeduard0 tentei fazer a entrevista 2x, porém sempre que vai enviar o video não conclui. Fiz ontem, não deu, fiz hoje umas 12:40 e até agora está na barra de progresso, falando: "**Enviando sua entrevista**"... Inclusive falta pouco, porém assim como ontem não concluiu.

Sinto muito você ter tido problemas com o app. 
Por favor entre em contato através do luiz@divisio.com.br que vou pedir para o time te ajudar na sua aplicação, ok?

**Comment by apteles** [comment]
@luizeduard0 já mandei o e-mail. Obrigado pelo retorno.
