### ISSUE TITLE
[São Paulo-SP] Front-end Developer na BRQ Digital Solutions

### ISSUE THREAD

**Issue by ReAnne123** [frontendbr/vagas#2459]
Descrição da vaga
Estamos em busca de profissionais com experiência em Front para atuar em projetos para grande cliente. Prazo indeterminado de contratação com muita chance de crescimento.

Local
Presencial no cliente perto da estação de trem Cidade Jardim. Várias linhas de ônibus para as principais regiões da capital.

Benefícios
-vale refeição
-vale alimentação
-seguro de vida
-plano médico Bradesco
-previdência privada
-plano odontológico

Requisitos
AngularJS, Webpack, Sass, CSS3, EcmaScript 6, git flow

Contratação
CLT full pela BRQ.
Horário das 9hs as 18hs, de segunda a sexta.

Nossa empresa
Fundada em 1993, a BRQ Digital Solutions é uma das maiores empresas de serviços de TI do país. Conta com 3000 profissionais distribuídos nas filiais de São Paulo, Alphaville, Rio de Janeiro, Curitiba, Recife e Nova Iorque.

Como se candidatar
Por favor envie um email para Renata- ryokota@brq.com, com seu CV anexado - enviar no assunto: Vaga Front.

Costumamos enviar feedbacks em até 20 dias após cada processo.
E-mail para contato em caso de não haver resposta: ryokota@brq.com.

## Labels
- Alocado
- CLT
- Pleno
- Sênior

**Comment by imortalout** [comment]
Olá, tenho interesse.
Um otimo resumo do meu currículo está no meu curso que lancei na Udemy.
https://www.udemy.com/course/mouse-labs-aprendendo-a-aprender-design-vol-1
