### ISSUE TITLE
[São Paulo] Desenvolvedor Front-End

### ISSUE THREAD

**Issue by MJVRHSP** [frontendbr/vagas#246]
**## Descrição da vaga**

AngularJS;
Git;
HTML5;
CSS3;

**## Perfis que desejamos:**
_Perfil Devops:_ Conhecimentos de Linux, e de configuração de ambientes de desenvolvimento;
_Perfil UX:_ Conhecimento das heurísticas de Nielsen e se interessar pelo assunto;
_Perfil Tester:_ Conhecimentos de planejar e executar testes;

**Atividades:**
Projeto novo, onde o desenvolvimento do produto com o cliente está em fase inicial. Foi desenvolvido um protótipo com Design Thinking, e será necessário trabalhar com Scrum para implementar. O produto será desenvolvido em AngularJS E Angular 2.

**## Local**
Zona Sul de São Paulo ( Interlagos)

**## Disponibilidade:** Imediata ou bastante breve.
**## Contratação**
CLT à combinar

## Nossa empresa

MJV busca os melhores profissionais para fazer parte da nossa equipe.

Tecnologia, Inovação e Integração Mobile. Identificar possíveis conexões entre as 3 áreas, este é o objetivo da MJV. Nosso campo de atuação é delimitado pela capacidade de enxergar além destas interseções, bem como compreender de que maneira elas podem nos conduzir à soluções realmente diferenciadas.Nós procuramos capacitá-los para tomar decisões, criando um ambiente de trabalho respeitoso, onde as pessoas são tratadas de forma justa e estão altamente motivados para o sucesso. 

Acompanhamos os membros de nossa equipe através de programas de educação continuada e da experiência on-the-job. 

E hoje estamos em busca de profissionais que tenha nosso perfil venha fazer parte de nossa equipe.

Precisamos de gente que se adapta às novas linguagens, é curiosa, trabalha em equipe e responde às necessidades de um negócio extremamente desafiador. Aqui, é para aprender, superar limites e atuar com qualidade e agilidade. 

Estamos buscando profissionais de FRONT-END ANGULAR.JS!!

## Como se candidatar

Encaminhar currículo com o nome da vaga no assunto + pretensão salarial para contratação CLT para: rhsp@mjv.com.br

**Comment by acacioosorio** [comment]
Sempre vejo vagas da MJV, mas o local nunca ajuda.

**Comment by wolfather** [comment]
Nunca dão feedback. Falar com essa empresa é perda de tempo.
