### ISSUE TITLE
[São Paulo] Front-end Angular Developer na Radar Profissional

### ISSUE THREAD

**Issue by RADARProfissional** [frontendbr/vagas#2460]
## Descrição da vaga

Estamos à procuta de um profissional com dois anos de atuação, como desenvolvedor Front End Angular 7, para um projeto indeterminado.

## Local

 Escritório, São Paulo - Avenida Paulista

## Benefícios
- Vale Transporte 
- VR de R$ 25/dia
- Férias remuneradas de 15 dias

## Requisitos
Requisitos:  

•             Superior Cursando ou Completo em Análise de Sistemas, TI ou áreas correlatas; 
•             Imprescindível experiência com angular 7+ com npm, Html 5, Css3 (Sass, padrão bem);

**Obrigatórios:**
Angular 7

**Diferenciais:**
•             Será considerado como diferencial, o profissional com conhecimentos com Wordpress (customização de Temas).

## Contratação
PJ 

## Nossa empresa

Aqui na Radar Profissional

## Como se candidatar

Por favor envie um talento@radarprofissional.com.br  com seu CV anexado - enviar no assunto: Front End Angular 7

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: talento@radarprofissional.com.br

## Labels

- PJ
- Pleno

**Comment by luqezman** [comment]
Padrão BEM *

**Comment by imortalout** [comment]
Olá, tenho interesse.
Um otimo resumo do meu currículo está no meu curso que lancei na Udemy.
https://www.udemy.com/course/mouse-labs-aprendendo-a-aprender-design-vol-1

**Comment by RADARProfissional** [comment]
@imortalout não consegui visualizar o seu CV. Poderia me enviar o anexo via e-mail?

**Comment by RADARProfissional** [comment]
@luqezman vc tem interesse?
