### ISSUE TITLE
[Piracicaba SP] Front-End Developer Sênior [IDGeo]

### ISSUE THREAD

**Issue by idgeo-dev** [frontendbr/vagas#2461]
## Descrição da vaga

Buscamos Desenvolvedoras/Desenvolvedores  Front-end Sênior para nosso  time com a missão de guiar o dev da nossa plataforma, redesenhar/reimaginar , liderar a formação do time front-end da empresa, com autonomia e com as melhores práticas de desenvolvimento, será responsável por toda a experiência Online do APP e do nosso site.
Você terá a oportunidade de trabalhar com equipes de profissionais interdisciplinares (Biólogos, Geógrafos, Florestais, Agrônomos e Administradores) para criação de produtos, num ambiente empreendedor, dinâmico, sempre em crescimento.

## Local

Remoto ou Escritório em Piracicaba

## Requisitos
Experiência prática com design de interfaces;
Habilidade para trabalhar em múltiplos projetos;
Liderança de times de desenvolvedores.
Conhecimentos:

- HTML e CSS
- GIT
- javascript
- VUE
- Angular (v1 e 2+)

**Diferenciais:**

- senso crítico e experiência com UI;
- Experiência com projetos responsivos/mobile;
- Domínio de ferramentas de prototipagem e edição de imagens;
- Ter experiência com AngularJS;
- Ter experiência com Bootstrap
- Ter experiência com CSS
- Ter experiência com Javascript e API
- Experiência com Framework Ionic;

## Contratação

PJ ou CLT a combinar

## Nossa empresa

A IDGeo – Inteligência em Dados Geográficos, empresa do segmento de geotecnologias aplicada à gestão e monitoramento agrícola, está buscando profissionais experientes na área de desenvolvimento Web, com interesse em integrar equipe multidisciplinar, com o desafio de inovar os processos de controle e gestão da lavoura.

## Como se candidatar

Por favor envie um email para selecao_dev@idgeo.com.br com seu CV anexado em pdf - enviar no assunto: Vaga Front-End

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após cada processo.
E-mail para contato em caso de não haver resposta: selecao_dev@idgeo.com.br

## Labels

- CLT
- Sênior
- PJ
- Pleno
- Remoto

**Comment by imortalout** [comment]
Olá, tenho interesse.
Um otimo resumo do meu currículo está no meu curso que lancei na Udemy.
https://www.udemy.com/course/mouse-labs-aprendendo-a-aprender-design-vol-1

**Comment by vmussato** [comment]
Enviado!

**Comment by idgeo-dev** [comment]
Legal, Obrigado por Participar!!

**Comment by idgeo-dev** [comment]
Obrigado a todos os participantes, vamos analisar os CV e entraremos em contato, Obrigado também para Front-End Brasil pelo espaço de divulgação. os candidatos que não foram chamados , vamos fazer depois uma outra convocatória e seus currículos vão na frente. Abrazos!
