### ISSUE TITLE
[São Paulo] Front-end Developer na DIGIBLE

### ISSUE THREAD

**Issue by carlosbrito** [frontendbr/vagas#2462]
## Descrição da vaga

Buscamos Desenvolvedor (a) Front end para compor o time responsável pelos aplicativos da Digible em São Paulo - SP.

## Local

Escritório, São Paulo - Berrini

## Requisitos

**Obrigatórios:**
Requisitos:
• Pelo menos 1 ano de experiência com desenvolvimento Front End - React-Native
• Excelentes conhecimentos e experiência em JavaScript / Typescript, React JS, HTML5, CSS3, ES6;
• Bootstrap;
• Integrações Rest;
• Bons conhecimentos dos conceitos: mvc, orientação a objetos;
• Experiência com versionamento (git);
• Publicações nas stores Android / IOS;

**Desejáveis:**
• Angular;
• Modelos Ágeis (Scrum, Kanban). 

## Contratação

PJ a combinar

## Nossa empresa

A Digible é uma empresa especializada no desenvolvimento, gestão e monetização de soluções mobile com foco na experiência do cliente e distribuição através das operadoras de telefonia móvel e lojas de aplicativos.

## Como se candidatar

Por favor envie um email para carlos.brito@digible.com.br com seu CV anexado - enviar no assunto: Vaga FrontEnd

## Labels

- PJ
- Pleno
- Sênior

**Comment by imortalout** [comment]
Olá, tenho interesse.
Um otimo resumo do meu currículo está no meu curso que lancei na Udemy.
https://www.udemy.com/course/mouse-labs-aprendendo-a-aprender-design-vol-1
