### ISSUE TITLE
[São Paulo] Front-end Developer na ALLEASY

### ISSUE THREAD

**Issue by Ana02071976** [frontendbr/vagas#2463]
DESCRIÇÃO DA VAGA

Buscamos profissionais Front-end SR para fazer parte do nosso time com a missão de unir forças ao nosso time front-end, que seja dinâmico, independente e que busque sempre conhecimento.
Você terá a oportunidade de trabalhar numa Startup de Mobilidade, Big Data e Tecnologia que vai transformar a maneira como as pessoas se deslocam nas cidades.

LOCAL
Bairro de Pinheiros / SP

REQUISITOS
• Graduação de nível superior em cursos relacionados à área de TI;
• Experiência com desenvolvimento Mobile (iOS Swift);
• Experiência em integração com banco de dados, integrações com APIs REST;
• Familiaridade com UI/UX e adaptação de layouts para diferentes tamanhos de telas e dispositivos;
• Metodologia ágil, DevOps, CI/CD;

DIFERENCIAL
Fluência no idioma inglês.

CONTRATAÇÃO
• PJ

NOSSA EMPRESA
Há mais de 20 anos, a AllEasy atua no mercado brasileiro ajudando líderes de TI de empresas de diversos portes e segmentos.
A AllEasy sabe o quanto é difícil e trabalhoso encontrar profissionais experientes e devidamente certificados para atuar em projetos e serviços na área de Tecnologia da Informação sem contar com um serviço especializado.
Trabalhamos com o objetivo principal de encontrar profissionais capacitados e certificados para atuar durante períodos pré-determinados  ou compor o time de sua empresa.

COMO SE CANDIDATAR
Por favor envie um email para vagas@alleasy.com.br anexado em Word.

TEMPO MÉDIO DE FEEDBACKS
Priorizamos o respeito com os profissionais que se envolvem em nossos processos, por isso o tempo médio de retorno varia de 05 à 07 dias.
E-mail para contato em caso de não haver resposta vagas@alleasy.com.br

LABELS
PJ
SR

**Comment by imortalout** [comment]
Olá, tenho interesse.
Um otimo resumo do meu currículo está no meu curso que lancei na Udemy.
https://www.udemy.com/course/mouse-labs-aprendendo-a-aprender-design-vol-1
