### ISSUE TITLE
[São Paulo] Front-end Developer na Mazzatech

### ISSUE THREAD

**Issue by Larirh500** [frontendbr/vagas#2465]
## Descrição da vaga

O profissional irá participar junto com uma equipe de desenvolvedores e Scrum Master de um novo projeto de viagens em uma das maiores companhias aéreas do Brasil. 

##  Pela Mazzatech 
Presencial, São Paulo - Congonhas 

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Desenvolvimento em Front-end
- Experiência com HTML 5, CSS, Java Script, Adobe PhotoShop ou Illustrator

**Desejáveis:**
- conhecimentos em UX e UI

## Contratação

PJ a combinar

## Nossa empresa

Aqui na Mazzatech somos especialistas em Tecnologia, focados em transformar oportunidades em sucesso. 

## Como se candidatar

Por favor envie um email para larissa@mazza.tech com seu CV anexado - enviar no assunto: Vaga Desenvolvedor Front-end 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.

## Labels

- Alocado
- PJ
- Pleno

**Comment by imortalout** [comment]
Olá, tenho interesse.
Um otimo resumo do meu currículo está no meu curso que lancei na Udemy.
https://www.udemy.com/course/mouse-labs-aprendendo-a-aprender-design-vol-1

**Comment by Larirh500** [comment]
Bom dia.
Não consegui acessar seu currículo. Consegue me mandar em anexo?

Atenciosamente.


Larissa Leite
Analista de RH

larissa@mazza.tech
011 2532.2992 <http://mazza.tech/assinatura/2019/11%2025322992> / 011
96342.5752
skype: lariissaleeite
[image: Site]
[image: Localização]


Em dom, 29 de set de 2019 às 13:14, imortalout <notifications@github.com>
escreveu:
