### ISSUE TITLE
[Florianópolis] Front-end Developer Magento na Avanti

### ISSUE THREAD

**Issue by Karinamatheus** [frontendbr/vagas#2467]
## Descrição da vaga

Procuramos um desenvolvedor front-end, com experiência em Magento, para o time da Avanti.

Somos especialistas em desenvolvimento e performance de e-commerce. Atuamos desde 2012 exclusivamente com plataforma VTEX e colocamos mais de 180 lojas no ar.

Estamos iniciando com a tecnologia Magento, por isso procuramos pessoas para formar este novo time aqui em Florianópolis. Aliás, time é o nosso forte, ganhamos em 2018 e 2019 prêmios GPTW.

Suas atividades serão customizar e desenvolver temas e funcionalidades de front-end na plataforma Magento 2.

## Local

Florianópolis, SC

## Benefícios

Vale alimentação ou refeição flexível
Vale transporte
Unimed
Bradesco Odonto
Folga no mês do aniversário
Cafés e chás
Fruta da estação diariamente
Moeda interna
Snacks
Espaço de descanso
Inglês na empresa
Café da manhã e da tarde
Academia
Benefício para quem vem de bike
Sem código de vestimenta
Ambiente descontraído
Cultura de desenvolvimento e autonomia
Eventos temáticos em datas comemorativa (fextenhas)
Uma equipe sensacional! – Somos GPTW!

## Requisitos

**Obrigatórios:**
Conhecimentos em Git;
Conhecimentos em HTML/CSS/JS;
Conhecimentos em Bootstrap, Less e Sass;
Conhecimentos em jQuery, Knokout.js;
Conhecimentos para criação de PWA;
Conhecimentos em SEO;
Conhecimento em responsividade;
Conhecimento em usabilidade e performance (Pagespeed)
Experiência com Magento 2.

**Desejáveis:**
Experiência com Magento Cloud;
Certificação em Magento 2 front-edn;
Experiência com Magento 1;
Conhecimento de React, Angular, Vue;
Inglês para leitura médio/avançado.
Essa oportunidade é a sua cara? Então se inscreve na vaga.

## Contratação

CLT

## Como se candidatar

Curtiu a vaga? Se inscreva no nosso site: https://jobs.solides.com/avantifloripa

## Labels

- CLT
- Pleno

**Comment by imortalout** [comment]
Olá, tenho interesse.
Um otimo resumo do meu currículo está no meu curso que lancei na Udemy.
https://www.udemy.com/course/mouse-labs-aprendendo-a-aprender-design-vol-1
