### ISSUE TITLE
[São Paulo] - Desenvolvedor FrontEnd | iCasei

### ISSUE THREAD

**Issue by le17i** [frontendbr/vagas#247]
## Descrição da vaga

Você curte projetos sofisticados? Deseja desenvolver soluções complexas e escaláveis? 
Procuramos Desenvolvedores(as) Front-end que sejam, assim como nós do iCasei, apaixonados por tecnologia.

Buscamos um profissional com uma postura e conduta condizentes com os valores pregados pela empresa, que trabalhe sempre com ética, comprometimento e paixão pelo que faz. Uma pessoa que seja proativa, "hands-on", sempre ligado em novidades e nas novas tecnologias que cercam o nosso mundo, a internet! 

## Local

Av. Chucri Zaidan 1550, 31º andar - São Paulo - CEP:04711-130 - Próximo ao Shopping Morumbi

## Benefícios

- Vale-refeição
- Vale-transporte
- Bônus de resultado
- Ajuda de custo para cursos, livros e palestras
- Ajuda de custo em estacionamento
- Seguro Saúde (Sul América)
- Horário flexível 
- Massagem
- Fruta na Mesa

## Requisitos

**Obrigatórios:**
- Área e especialização profissional: Informática, TI, Telecomunicações - Programador / Desenvolvedor
- Conhecimento sólido em HTML5, CSS3 e Pré-processadores SASS e LESS
- Trabalhar com frameworks CSS e JS
- Taskrunners (Grunt ou Gulp)
- Testes automatizados
- Conhecimento em WordPress (Temas e Plugins)
- Perfeccionista com detalhes de layout
- Conhecimento em GIT (Conhecimento do Terminal)
- Otimização e performance (Pagespeed)
- Inglês (técnico)

## Contratação

CLT

## O iCasei

Nós somos o maior portal de casamento da América Latina. Através de nosso site, ajudamos milhares de noivos a organizarem suas listas de presentes e sites de casamento.

Saiba mais https://www.icasei.com.br/

## Como se candidatar

Por favor, entre no nosso [repósitorio](https://github.com/icasei/teste-front-end) e siga as instruções. 
Não esqueça de enviar seu CV ou linkedin, e nos avisar que achou a vaga aqui. 😃

**Comment by acacioosorio** [comment]
Sempre lamento essas vagas legais serem nessas regiões.  :(

**Comment by danielGalvao** [comment]
@acacioosorio você precisa morar aqui!!!

**Comment by paulovitorwd** [comment]
Olá a vaga ainda está em aberto?
Pretendo fazer o teste, mas começarei em 2 dias.

**Comment by le17i** [comment]
@paulovitorwd está sim. :)

**Comment by MichaelSilva09** [comment]
Olá, eu gostaria de saber se tem estágio na área, tem um bom conhecimento em Html5 e css3, porém quero ter a experiência dentro do trabalho. Atualmente curso Análise e desenvolvimento de sistemas.

**Comment by le17i** [comment]
@MichaelSilva09 aqui no iCasei, no momento não.
