### ISSUE TITLE
[São Paulo] Front-end Developer na Vizir

### ISSUE THREAD

**Issue by FabricioFFC** [frontendbr/vagas#2471]
## Descrição da vaga

Projeto de um app de conta de pagamentos digital, em React Native. Você irá trabalhar no nosso escritório na República em São Paulo, e irá interagir com a equipe do cliente que está localizada em Boston.

## Local

Escritório, São Paulo - República

## Benefícios

- Ticket refeição: R$ 31,50 por dia (R$ 661,50 por mês) pago em dinheiro;
- Notebook: o note com o qual você irá trabalhar pode ser levado para casa, para a faculdade ou para onde quiser. Após dois anos, o notebook ficará para você;
- Plano de saúde SulAmérica, com acesso a uma boa rede de hospitais e quarto individual;
- Plano odontológico Odontoprev;
- Seguro de Vida no valor de R$ 60.000,00.

## Requisitos

**Obrigatórios:**
- Conhecer bem JavaScript, boa lógica e orientação a objetos
- Experiência com React
- Estar a fim de aprender
- Ser comprometido em entregar projetos com qualidade
- Curtir programar
- Conseguir se comunicar em inglês (ex: participar de uma daily)

**Desejáveis:**
- Ter experiência com React Native

## Contratação

CLT

## Nossa empresa

Somos uma Software Studio com 9 anos de existência, criamos software sob-demanda em diversas tecnologias: https://vizir.com.br

## Como se candidatar

Preencha o seguinte formulário: https://recruiterflow.com/vizir/jobs/5

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 semanas após cada processo.
E-mail para contato em caso de não haver resposta: queroentrar@vizir.com.br

## Labels

- Alocado
- CLT
- Pleno
- Sênior

**Comment by imortalout** [comment]
Olá, tenho interesse.
Um otimo resumo do meu currículo está no meu curso que lancei na Udemy.
https://www.udemy.com/course/mouse-labs-aprendendo-a-aprender-design-vol-1
