### ISSUE TITLE
[São Paulo] Front-end Developer [Minutrade]

### ISSUE THREAD

**Issue by B-headhunter** [frontendbr/vagas#2475]
## Descrição da vaga

Referência Técnica .

## Local

Escritório, São Paulo - JK, próximo a Faria Lima

## Benefícios

- Plano de saúde
- Seguro de vida
- VR 
- E outros padrões de mercado.

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Node.js
- 2 anos de experiência com React/ React Native

**Desejáveis:**
- desenho e prototipação de interfaces (web/mobile)

## Contratação

CLT (a combinar) 

## Nossa empresa

Minutrade é uma stratup de serviços, empresa inovadora que tem uma solução de marketing, relacionamento, fidelização e engajamento através de recompensas digitais no ambiente mobile. Eles trabalham com grandes clientes, em diferentes segmentos do mercado promovendo o engajamento entre marcas/produtos e seus clientes através de recompensas digitais de baixo custo e alto valor percebido.

## Como se candidatar

Por favor envie um email para beatriz.coelho@2xs.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.
E-mail para contato em caso de não haver resposta: beatriz.coelho@2xs.com.br

## Labels

- Alocado
- CLT
- Sênior
- Referência Técnica de ferramentas.

**Comment by brunopoc** [comment]
A Vaga é pra Full Stack? Se sim, está no local errado.
