### ISSUE TITLE
[São Paulo] Pessoa desenvolvedora Front-end na Gupy

### ISSUE THREAD

**Issue by nandoofz** [frontendbr/vagas#2480]
## Descrição da vaga
A Gupy é uma empresa de tecnologia que une um grupo de engenheiros de softwares apaixonados em gerar inovação para oferecer contratações mais ágeis, justas e encantadoras à sociedade. Somos movidos por grandes desafios e precisamos de pessoas que amem tecnologia, aprendizado constante, e que tenham muita gana para nos ajudarem a transformar a Gupy na melhor e maior empresa de Recrutamento Tech do Brasil.

Estamos crescendo muito rápido e criando a cada dia um produto ainda mais poderoso. O segredo disso? As pessoas incríveis que fazem parte conosco dessa construção contínua.

Estamos expandindo nossos produtos web e precisamos da sua ajuda! Se você é a pessoa que sabe:

Desenvolver aplicação em React (ou lib/framework SPA similar);
Implementar telas responsivas com HTML5 e CSS;
Conhecer (ou querer aprender) tecnologias como React, Redux, Saga, Webpack, SASS, BEM, Websocket, Node, Google Analytics e diversas outras, então a Gupy é o lugar para você!

## Local

Escritório (remote friendly), São Paulo - Pinheiros

## Benefícios

- Plano de saúde/odontológico
- Seguro de vida
- VR de R$ 20/dia
- Salários competitivos, com a possibilidade de virar sócio da Gupy!
- Subsidiamos uma parceria com o Zenklub, uma plataforma de psicólogos e coaches online, para focarmos 100% no bem estar e saúde mental de cada Gupier aqui dentro!
- Um clube inteiro de descontos para viagens, lazer, restaurantes e até mesmo aquela pós-graduação tão sonhada!
- Gympass

#### Diferenciais

- Flexibilidade de horários;
- Ambiente de alta cooperação e aprendizado;
- Happy hours sempre;
- Ambiente saudável e seguro;
- Um lugar pra você aprender, crescer e ser!

## Requisitos

**Obrigatórios:**
- Sólida experiência como desenvolvedor/desenvolvedora de software;
- Sólido conhecimento em testes de unidade / funcionais / integração;
- Hábito de aplicar boas práticas de engenharia de software;
- Hábito de fazer unit tests no dia a dia;
- Hábito de fazer refatoração no dia a dia;
- Hábito de implementar layouts responsivos.

**Desejáveis:**
- Mínimo 2 anos de experiência escrevendo client-side JavaScript;
- Mínimo 6 meses de experiência em React;
- Conhecimento em testes no front (usando jest, enzyme ou similares);
- Muito brilho no olho com nosso propósito de termos cada vez mais pessoas realizadas em seus trabalhos, através de contratações mais ágeis, justas e encantadoras!

## Contratação

CLT ou PJ, a combinar

## Nossa empresa

A Gupy é uma HR tech fundada em 2015 pela Mariana Ramos Dias e a Bruna Guimarães, que estavam insatisfeitas em como o mercado de recrutamento no Brasil era lento, custoso, injusto e pouco efetivo. Desde de 2017 estamos vindo numa expansão bem legal, em junho de 2017 éramos 12 e agora somos 120.

A Gupy é uma plataforma SaaS de recrutamento e seleção e faz uso de modelos de machine learning para triagem de candidatos que fazem o melhor fit com a vaga, dessa forma nós oferecemos pra empresa uma plataforma bem flexível para montarem seus processos seletivos e diminuímos o esforço operacional bem como o turnover, colocando as pessoas certas nos lugares certos.

Outro lado é a experiência candidato, onde trabalhamos para terem o menor atrito possível durante o processo seletivo, visto que é um momento muito importante na vida deles, assim sempre estamos evoluindo para melhorar a experiênca deles cada vez mais.

Nossa grande missão é ter gente realizada por meio de contratações justas, ágeis e encantadoras e com isso mudar o cenário brasileiro, ajudando na diminuição do desemprego e ajudando cada vez mais o país a contratar mais e melhor. :)

Hoje no nosso time como um todo 52% são mulheres, já no time de engenharia/produto (somos por volta de 45 pessoas) não estamos tão balanceados, mas temos a diversidade como uma preocupação constante.

Nesses links você consegue saber um pouquinho mais sobre a Gupy :)

https://exame.abril.com.br/pme/startup-que-acaba-com-contratacoes-sem-sentido-levanta-r-11-milhoes/

https://www.linkedin.com/pulse/como-organizar-times-de-engenharia-em-meio-ao-caos-uma-rodrigues/

https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Gupy-EI_IE2488824.13,17.htm

Podcasts com a nossa CEO:
https://www.likeaboss.com.br/episodios/mariana-dias-ceo-da-gupy-de-trainee-a-ceo-da-startup-de-recrutamento-mais-promissora-do-pais/

https://open.spotify.com/show/0y449BDXAK6wB8nNIZ3WQ9?si=VwvaDTjBRqWB1AcGZUS_oQ

Podcast com a nossa head de gestão:
https://hipsters.tech/gestao-de-pessoas-hipsters-157/

Podcast com a nossa head de gestão e nosso CTO:
https://hipsters.tech/gestao-de-pessoas-na-gupy-hipsters-on-the-road-14/

## Como se candidatar

Se candidate para uma de nossas vagas :dancer: 
https://vempra.gupy.io/

## Tempo médio de feedbacks

O nosso processo é bem rápido após a inscrição de um cadidato. ;)

## Labels

- Alocado
- CLT
- PJ
- Pleno
- Sênior

**Comment by juulhao** [comment]
@nandoofz não encontrei a vaga em questão no site :(

**Comment by nandoofz** [comment]
@juulhao, ainda não abrimos a vaga específica de front, devemos fazer isso até a próxima semana, mas se tiver interesse pode se candidatar na vaga de full stack :)
