### ISSUE TITLE
[São Paulo] Front-end Developer na Bovcontrol

### ISSUE THREAD

**Issue by FernandaAbreu** [frontendbr/vagas#2481]
## Descrição da vaga

Olá, nós somos a Bovcontrol.

E nós estamos revolucionando o agribusiness no mundo!!!

Somos a 3 startup mais inovadora, segundo a Startse.

O time de desenvolvimento da BovControl está procurando desenvolvedor(a) front-end apaixonados por desafios exponenciais.

## Local

Escritório, São Paulo - Berrini

## Benefícios

-Vale refeição
-Vale transporte
-Plano de saúde
-Ambiente descontraído e informal

## Requisitos

**Obrigatórios:**
- HTML5 👀
- CSS3 (SASS)
- Google Material Design

**Desejáveis:**
- Noções de programação funcional
- Single Page Application
- JavaScript (ECMAScript 6)
- Consumo de API REST
- Ambientação em Linux ou Mac
- Processos e métodos ágeis (SCRUM, Kanban)

**Diferenciais:**
-  React + Redux + Saga ou Vue.js
- Webpack / Gulp
- Controle de versão via Git

## Contratação

 a combinar

## Nossa empresa

Somos uma startup global que vem conectando todas as vacas e fazendas do planeta numa 'nuvem diferente' (antes do modismo do blockchain) - com o objetivo de erradicar a fome no mundo, empoderando produtores rurais com tecnologia para serem mais eficientes e sustentáveis.
Nossas soluções combinam coleta e a análise de dados, para toda a cadeia produtiva.

Os dados são coletados no campo por aplicativos móveis e podem ser analisados por vários meios, por diferentes elos da cadeia (varejo, bancos, processadores de leite, etc).

Alimentar 1 bilhão de pessoas por dia, em 10 anos de existência da empresa, é a nossa meta.

## Como se candidatar

Por favor envie um email para vagas@bovcontrol.com com seu CV anexado - enviar no assunto: Vaga Front end

## Labels

- Alocado
- CLT
- PJ
- Pleno
- Sênior

**Comment by danielswater** [comment]
É alocado ou remoto?

**Comment by FernandaAbreu** [comment]
> É alocado ou remoto?

Opa @danielswater é Alocado.

**Comment by danielswater** [comment]
Ah entendi @FernandaAbreu . É que nas labels está remoto. Então desconsidere o email que eu enviei ok? Obrigado :)

**Comment by rafaelkendrik** [comment]
@felipefialho :point_up:

**Comment by felipefialho** [comment]
My bad
