### ISSUE TITLE
[São Paulo] Front-End Developer na Cognizant

### ISSUE THREAD

**Issue by gabisaalves** [frontendbr/vagas#2482]
## Descrição da vaga

Olá,

Já ouviu falar sobre a Cognizant? Somos uma multinacional do ramo de tecnologia com sede nos Estados Unidos :)

Estamos com oportunidade para atuar em um de nossos clientes. Se você é apaixonado por desenvolvimento assim como nós, este desafio é para você!

## Local

Escritório, São Paulo - Próximo ao Centro

## Benefícios

- Convênio médico;
- Convênio odontológico;
- Seguro de vida;
- VR ou VA;
- Auxílio creche;
- Previdência privada.

## Requisitos

**Obrigatórios:**
- Ter domínio em Angular, CSS, JavaScript e HTML (desejável Node);
- Ter participado em projetos utilizando modelos ágeis;
- Experiência em criação de websites amigáveis para usuários;
- Graduação na área (Ciência da Computação, Análise e Desenvolvimento de Sistemas, Engenharia da Computação etc) ou experiência similar;
- Ter compreensão do processo completo de criação de websites (desde o design/desenvolvimento até a entrega).

**Desejáveis:**
- Experiência em startup.

## Contratação

CLT Full

## Nossa empresa

Fazer mais e melhor, com agilidade, é o que a era digital nos impulsiona, ser apaixonado pelos nossos negócios determina como iremos fazer. Nossos clientes e as nossas pessoas sabem que sempre encontraremos o melhor caminho, mas que nossos valores essenciais jamais mudarão. A Cognizant é uma das líderes mundiais em serviços profissionais. Com sede nos EUA e presente em mais de 40 países, ocupamos a 195.ª colocação no ranking da Fortune 500 e estamos, consistentemente, listados entre as empresas mais admiradas do mundo. 

## Como se candidatar

Envie um email para gabriela.alves@cognizant.com com seu CV anexado - enviar no assunto: Vaga Front-end Developer

## Labels

- CLT;
- Sênior.

**Comment by danielswater** [comment]
Pena não aceitar remoto :(
