### ISSUE TITLE
[Campinas/ALOCADO] Front-end Developer na Aware.

### ISSUE THREAD

**Issue by clarabritoaware** [frontendbr/vagas#2483]
## Sobre a Vaga

A aware. é uma startup em constante crescimento que desenvolve soluções em logística de alto nível para transportadoras e embarcadoras. Atualmente nosso maior cliente é a Ericsson Brasil e estamos expandindo para outros países da América Latina e ampliando nossa rede de clientes. 
No momento queremos aumentar nosso time. Precisamos de pessoas proativas que tenham interesse em participar ativamente dos processos de desenvolvimento de nossos produtos.
Buscamos desenvolvedores que tenham o foco em construir produtos digitais de altíssima qualidade, que estejam atualizados com as melhores práticas e tecnologias para crescerem junto com a empresa. 

## Local

Escritório, Campinas - Santa Genebra próximo Praça Capital

## Benefícios
- Horário Flexível
- Nos importamos com seu desempenho e não com sua carga horária

## Requisitos

**Obrigatórios:**
- Conhecimento Javascript 
- Experiência Angular

**Desejáveis:**
- Typescript 
- TypeORM
- Experiência Full-Stack

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para clara@awarelog.com com seu CV anexado - enviar no assunto: Vaga Front-End 

## Labels

- 🏢 Alocado
- 👦 Júnior
- 👴 Pleno
- ⚖️ PJ
- 💰 4k-6k

**Comment by danielswater** [comment]
Enviado

**Comment by halkliff** [comment]
Enviado!

**Comment by GustavoPrizon** [comment]
Cv enviado!

**Comment by GustavoPrizon** [comment]
Algum feedback? Enviei o cv faz 2 semanas e não tive resposta.

**Comment by Fraanst** [comment]
> Algum feedback? Enviei o cv faz 2 semanas e não tive resposta.

Envie faz 1 mês e ainda não tive retorno tb..
