### ISSUE TITLE
[São Paulo] Front-end Developer na DEX

### ISSUE THREAD

**Issue by raoferreira** [frontendbr/vagas#2489]
## Descrição da vaga

Somos a Dex, uma empresa focada em melhorar a produtividade de grandes empresas utilizando metodologias de startups e desenvolvimento ágil. Uma software house com vontade de deixar o mundo mais rápido e transparente. Estamos buscando desenvolvedores com conhecimento em React.Js para nos ajudar a construir esse mundo.

## Local

Presencial em São Paulo - Jd Paulistano (Av. Faria Lima)

## Benefícios

- Vale refeição
- Vale transporte

#### Diferenciais

- Horários flexíveis
- Happy hour de equipe toda quarta
- Sala de descompressão
- Café, frutas, cerveja, bolo sempre disponíveis

## Requisitos

**Obrigatórios:**
- Experiência anterior em React.js
- Conhecimento de Node.js
- Conhecimento de MongoDB
- Conhecimento em versionamento utilizando Git

**Desejáveis:**
- Conhecimentos em cloud
- Conhecimento em CI/CD

**Diferenciais:**
- Familiaridade com Jenkins
- Conhecimento em React Native

## Contratação

CLT

## Nossa empresa

Realmente acreditamos que nossa equipe pode mudar o mundo e para isso sempre trabalhamos com muita energia. Somos bem novos (desde Dez17), então obviamente tem muito mais risco do que uma empresa consolidada, mas tentamos criar um ambiente tranquilo, amigável onde você pode aprender muito com todo mundo em volta. Queremos que as pessoas que estão na empresa ajudem a moldar nossa cultura da melhor forma possível. Caso tenha dúvidas, ficaremos contentes em te conectar com nosso líder técnico ou qualquer colaborador para te ajudar a esclarecê-las.

## Como se candidatar

Por favor, envie um email para rao@dex.company com o assunto **[FrontendBR]**, anexe seu CV e qualquer outro material que tiver, tipo Linkedin, Github, site pessoal ou algum link que você gostaria de nos mostrar.

## Tempo médio de feedbacks

Costumamos responder na mesma hora mas tentamos valorizar a vida fora do escritório, então já já te respondo =)
E-mail para contato em caso de não haver resposta: bruno@dex.company.

## Labels

- CLT
- Júnior
- Pleno

**Comment by GustavoPrizon** [comment]
Cv enviado!
