### ISSUE TITLE
[São Paulo/Remoto] Web Developer - React/JavaScript

### ISSUE THREAD

**Issue by caiobgomes** [frontendbr/vagas#249]
[VAGA] Desenvolvedor Web (CLT ou PJ – a combinar)

Descrição das atividades:
- Criação de Single Page Applications (SPA) responsivas, usando HTML, Javascript, Bootstrap e React;
- Integração de SPA's com webservices;
- Criação de webservices em NodeJS.

Requisitos:
- Formação exigida: Matemática, Engenharias, Ciências da Computação e Sistemas de Informação;
- Domínio de JavaScript,
- Conhecimento adicional em Android,  NodeJS ou MongoDB é um diferencial;
- Ser apaixonado por aplicações mobile;
- Ser proativo e gostar de aprender;
- Ser organizado;
- Conhecimento intermediário em inglês;
- Ser comprometido com resultados, qualidade e deadlines;

Sobre a empresa:
Syligo is a Technology Company focused on Mobile and Web Application development. We Connect Ideas, to develop outstanding Apps and provide specialized trainings for developers, based on the most recent technologies. 

Focused on the following technologies: - iOS Application Development for iPhone and iPad (Apple Developer) - Android Application Development - Web Application - Database and Service Development

Site: http://www.syligo.com/

Local da vaga: Home Office E/OU Jardins/SP

Faixa Salarial: R$ 2.000,00 - R$4.000,00 (dependendo da experiência do candidato e disponibilidade de horas)

Para se inscrever, por favor, mande seu perfil Linkedin, CV ou Github para caiobgomes@syligo.com.

**Comment by valterjuniorifactory** [comment]
Enviado! ;)

**Comment by jvcjunior** [comment]
Enviado!! ;)

**Comment by brunooomelo** [comment]
Enviado!

**Comment by andrebrandaoo** [comment]
Enviado! xD

**Comment by thenewbiemaster** [comment]
Enviado!

**Comment by WelingtonMonteiro** [comment]
Enviado! :D
