### ISSUE TITLE
[Curitiba] Senior Front-End Developer na Easy Carros 

### ISSUE THREAD

**Issue by easycarros-tech** [frontendbr/vagas#2496]
## Sobre a Easy Carros

A Easy Carros é uma empresa que nasceu em 2014, focada no mercado de mobilidade.
Identificamos que hoje, 40% do valor de tudo o que compramos no nosso dia a dia (o pão do café da manhã, o chocolate de sobremesa, a cervejinha do final do dia) é referente ao custo de logística, que é extremamente caro no Brasil.

E o que queremos é criar cada vez mais serviços e tecnologias que possam entregar economia de custos para o setor de logística das principais empresas, para que, assim, os produtos cheguem a um preço muito mais justo e em conta para nós, os consumidores. 
Queremos, então, impactar a vida de milhões de brasileiros através dos nossos produtos. 

Nosso sonho é grande e nossa empresa tem sangue no olho para alcançar esse resultado. Trabalhamos focados em 5 principais valores: Ir além do esperado, Aprendizado exponencial, Ir fundo em dados e tecnologia, Winning Together e Pensamento de dono.

Você tem esses valores? Quer transformar o mundo? Se sim, aqui é o seu lugar.

## Suas responsabilidades:
* Criação de componentes para o sistema;
* Definição de padrões conceituais para as interfaces;
* Validação do trabalho realizado pela equipe;

## O que você precisa saber:
* HTML5;
* CSS3;
* BootStrap;
* JavaScript;
* Noções de APIs;
* REST/JSON/JWT;
* Framework JavaScript;    
* React/Redux;

## O que seria legal você saber:
* Controle de Versão;
* Azure Devops - VSTS;
* Visual Studio/Visual Studio Code;
* Scrum;

## Contratação
* PJ
* Alocado

## Benefícios
* Férias remuneradas
* Auxílio médico pela [Cuidas](https://www.cuidas.com.br)

## Gostou? Candidate-se!

[https://new.easycarros.com/vagas/](https://new.easycarros.com/vagas/)

**Comment by rodgomesc** [comment]
Digamos q eu tenha 95% das skills, alguma possibilidade de aceitar remoto?

**Comment by easycarros-tech** [comment]
@rodgomesc infelizmente por enquanto não é possível termos um profissional 100% remoto. Trabalhamos com times remotos, mas precisam estar alocados em alguma filial (SP ou PR) dada a dinâmica de trabalho que temos atualmente.

No entanto se optar por trabalhar alocado, é possível atuar remoto em alguns momentos sem problemas.

**Comment by vimaciel** [comment]
Olá

Gostaria de saber o endereço que vocês trabalham aqui em Curitiba.

Desde já obrigado.

**Comment by easycarros-tech** [comment]
@vimaciel fica na Travessa da Lapa, no Centro. Se quiser nos visitar, manda um email pra clarabernabe@easycarros.com que ela agiliza isso. Bem vindo!
