### ISSUE TITLE
[São Paulo - SP] Desenvolvedor Front-end

### ISSUE THREAD

**Issue by fernandofleury** [frontendbr/vagas#25]
## Descrição da vaga

Procuramos mais um desenvolvedor Front-end para fazer parte da equipe Leroy Merlin Brasil. Somos responsáveis por uma grande parcela de todo o meio web em que ela está inserida. Totens de loja, sistema de consulta no chão de loja, e-commerce, aplicativo mobile, e assim vai.

## Local

*Iremos ficar temporariamente localizados ao lado da estação Granja Julieta, com possibilidade ficar lá permanentemente.*

Escritório, São Paulo - Próximo ao Shop. Interlagos.

## Benefícios

- Equipe com nível técnico bem alto, excelente ambiente pra aprender.

## Requisitos

**Obrigatórios:**
- Conhecimento sólido nos pilares do front-end. HTML, CSS, JS.
- Conhecimento em modelo de desenvolvimento com testes, seja TDD/BDD ou afins.
- O mínimo de conhecimento de arquitetura de informação. Importante ter um pouco de senso crítico na hora de se construir ou modificar uma interface existente.
- Versionamento

**Desejáveis:**
- Conhecimento com Cordova

**Diferenciais:**
- Interação com o meio open-source. Valorizamos muito pessoas que ajudam as outras.

## Como se candidatar

Por favor, envie um email para me@fleury.io com o assunto Vaga Front-end com suas informações. Seja CV, github, site, blog e afins.

**Comment by sergiokopplin** [comment]
Qual nível do desenvolvedor?

**Comment by fernandofleury** [comment]
@sergiokopplin Não definido. Mas acho que pelos critérios, é no mínimo pleno.

**Comment by sergiokopplin** [comment]
Obrigado!

**Comment by fernandofleury** [comment]
@LFeh Se puder inserir a tag de Sênior e Alocado também, por favor.

**Comment by fernandofleury** [comment]
@LFeh Pode trocar a tag de CLT para PJ? Desculpa ficar pedindo :cry:

**Comment by LFeh** [comment]
Não se preocupa. \o

**Comment by LFeh** [comment]
A vaga foi preenchida? @fernandofleury

**Comment by fernandofleury** [comment]
Foi nada.

**Comment by LFeh** [comment]
Puts, vou deixar aberto.

Amanhã compartilho.

**Comment by camilatigre** [comment]
@fernandofleury 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by fernandofleury** [comment]
@camilatigre eu deixei em aberto a vaga. mas não estou mais na leroy, então é c.

**Comment by camilatigre** [comment]
Blz. Obrigada por responder

Em 24 de nov de 2016 10:54, "Fleury" <notifications@github.com> escreveu:
