### ISSUE TITLE
[REMOTO] - Última Semana - Front-end Javascript & Django (Até US$ 2,500 mês)

### ISSUE THREAD

**Issue by gmenegatti** [frontendbr/vagas#2502]
Olá, pessoal,

Estamos recrutando 1 a 2 pessoas para trabalhar remotamente para uma empresa dos EUA. O profissional deve ter **acima de 7 anos de experiência** prática em JavaScript e Django (Python).

**IMPORTANTE: A data para início na empresa será no dia 15 de outubro e o profissional selecionado se reunirá com toda a equipe em Austin (Texas, US), com todas as despesas pagas pela empresa.**

Para se candidatar, basta enviar uma mensagem para o email abaixo com o seu currículo (em inglês):
gabriel@simbioseventures.com

**Carga horária:**
44 horas semanais.

**Remuneração:**
- De US$1,500,00 (aprox. R$ 6.000,00) a US$2,500.00 (aprox. R$ 10.000,00) por mês.
- O pagamento sempre será feito em dólar, portanto o valor pode aumentar significativamente nos próximos anos.

**Forma de contratação:**
Prestação de Serviços (PJ)

**Local de trabalho:**
Trabalho exclusivamente remoto, mas com possibilidade de pagamento de um co-working para o profissional, caso ele não queira trabalhar de casa.

**Benefícios:**
- Notebook da empresa: MacBook Pro (15'', 8cores 2.4GHz, 32Gb, 2TB SSD, etc.)
- Possibilidade de pagamento de um co-working para o profissional, caso ele não queira trabalhar de casa.
- Horário de trabalho realmente flexível
- Estabilidade. Os próximos 10 anos estão assegurados sem pressão nas vendas, visto que o foco está no desenvolvimento do produto.
- Ter a possibilidade de trabalhar com grandes profissionais. Pessoas que tem criado várias empresas de tecnologia em diversas partes do mundo. Nossos sócios são ex-CXX da Rackspace. 
- Possibilidade de mudar para os EUA em 2 anos se o profissional demonstrar alto desempenho. 
- Viagens frequentes para Austin (temos 3 deliveries que deveriam ser feitos lá só nos próximos 11 meses)

**Candidatar:**
Para se candidatar, basta enviar uma mensagem para o email abaixo com o seu currículo (em inglês):
gabriel@simbioseventures.com

**Comment by guilhermeoa07** [comment]
Apenas front?

**Comment by gmenegatti** [comment]
@guilhermeoa07, buscamos back também. Eu postei a vaga no outro repo.

Segue o link:
https://github.com/backend-br/vagas/issues/1700

**Comment by Rodzman** [comment]
Precisa ter conhecimentos tanto de JS quanto de Python?

Em sex, 4 de out de 2019 às 14:38, Gabriel Menegatti <
notifications@github.com> escreveu:

**Comment by gmenegatti** [comment]
Sim @rodzman. Mais de Django e Python do que JS.

**Comment by rzorzal** [comment]
> Carga horária:
44 horas semanais.
<

Como vocês medem isso ?

**Comment by rzorzal** [comment]
Um outro ponto:

> IMPORTANTE: A data para início na empresa será no dia 15 de outubro e o profissional selecionado se reunirá com toda a equipe em Austin (Texas, US), com todas as despesas pagas pela empresa.

Sendo assim só aceitam pessoas que já possuem visto para entrada no EUA ?

**Comment by JIFerreira** [comment]
Nossa, mas esse salário é muito baixo cara, pra 7 anos de experiência, esse valor é baseado em qual mercado? porque o internacional, pelo que vejo nos sites gringos, não paga tão mal assim!

**Comment by gmenegatti** [comment]
Marcado Brasileiro, afinal o profissional trabalhará remotamente à partir do Brasil.

**Comment by maugravena** [comment]
O salário seira diferente para pessoas nos EUA?

**Comment by gmenegatti** [comment]
Sim, com certeza @maugravena. Inclusive seria diferente de acordo com o estado dos EUA onde a pessoa mora. O custo de vida varia muito de um lugar para o outro.

**Comment by phillipesouza** [comment]
Olá @gmenegatti, 

Quais as referências da empresa? Só pude acessar o site de recrutamento. Qual o foco de mercado? E existe teste para a vaga?

**Comment by vncscoelho** [comment]
Fiquei meio confuso. É front mas o foco é Python?

**Comment by gmenegatti** [comment]
@vncscoelho sim, Django.
