### ISSUE TITLE
[Polonia - Várias cidades] Front-end Developer na EPAM

### ISSUE THREAD

**Issue by augustoabreu** [frontendbr/vagas#2505]
DESCRIPTION

Currently we are looking for a JavaScript Developer for our Gdansk office to make the team even stronger.

Software Developer position in EPAM gives opportunity to interact with skilled engineers worldwide, be acquainted with various industries & domains and work with modern technologies used in our projects.

RESPONSIBILITIES

- Provide full-cycle web application development using Agile approach
- Communicate with the client to clarify requirements
- Be responsible for integration with other clients’ systems and applications

REQUIREMENTS

- Highly experienced in plain JavaScript, HTML and CSS
- Experience with React or/and AngularJS
- Understanding of software development life cycle and development methodologies
- Experience in unit testing
- Spoken English & experience in client-facing communications
- Solid SDLC understanding and experience working in Agile environment

NICE TO HAVE

- Experience with a Design Framework like Carbon is a huge plus

WE OFFER

-Possibility to be involved in an international project (Canada, China, Hong Kong, Mexico, USA, Switzerland, Germany, Sweden, United Kingdom, Russia, Belarus, Ukraine, Hungary, etc.)
- Language classes (English and Polish)
- Vast opportunities for self-development: online courses and library, experience exchange with colleagues around the world, partial grant of certification
- Career development center
- Unlimited access to LinkedIn learning solutions
- Possibility to take part in both: corporate and startup environment
- Possibility to relocate for short and long-term projects
- Relocation package for those who relocate to Krakow, Wroclaw, Katowice or Gdansk from other locations
- Benefit package (health care, multisport, lunch tickets, petrol vouchers and shopping vouchers, etc.)
- Fruits on a weekly basis
- Sponsored sport activities, E-sport program

https://www.epam.com/careers/job-listings/job.47240

**Comment by augustoabreu** [comment]
PS: A vaga é para o escritório de Gdansk, onde eu trabalho, mas existem vagas para todos os escritórios da EPAM na Polônia. https://www.epam.com/careers

**Comment by thiagofrancisquete** [comment]
@augustoabreu senioridade?

**Comment by augustoabreu** [comment]
> @augustoabreu senioridade?

Senior e pleno(regular).
