### ISSUE TITLE
[Florianópolis] Front-end Developer na Blueticket

### ISSUE THREAD

**Issue by mariaeugenialuz** [frontendbr/vagas#2507]
Nosso propósito é aproximar pessoas de experiências ao vivo. Para isso desenvolvemos ferramentas que auxiliam os organizadores na gestão dos seus eventos, e tecnologias que permitem que os clientes comprem seus ingressos, seja através do site, aplicativos mobile ou das tecnologias para os pontos de venda.

Nossos produtos são utilizados diariamente por mais de 1 milhão de visitantes no nosso site, além de centenas de organizadores que emitem mais de 3 milhões de ingressos por ano na nossa plataforma.

Estamos vivendo um momento muito especial, criando uma nova plataforma de gestão de eventos, utilizando nossos mais de 10 anos de experiências e aprendizados para criar um novo ambiente completo, possibilitando mais eficiência e recursos incríveis para organizadores e para o público final!

Quer embarcar com a gente nesse desafio? Conheça um pouco mais sobre nosso ambiente, sobre a vaga e o que esperamos de você:

**Tecnologias que utilizamos**

Front-end: Vue.js / Vuetify, React/React Native, Nuxt;
Back-end: Laravel, PHP, Python;
Banco de Dados: MySQL, Redis;
Cloud: AWS, Google Cloud, Docker, Kubernetes;
Ferramentas: Trello, Bitbucket, Github, Figma, Zeplin.

**Responsabilidades**

Escrever código claro, simples e otimizado;
Trabalhar no processo de construção de soluções, o que envolve projeto, requisitos, execução, manutenção e suporte;
Trabalhar para melhorar nossas soluções existentes;
Buscar constantemente seu aperfeiçoamento, mantendo-se atualizado sobre novas tecnologias e metodologias de desenvolvimento;
Ter proatividade em compartilhar seus conhecimentos, contribuindo com desenvolvimento profissional da equipe.

**O que você traz**

Graduação em Análise e Desenvolvimento de Software, Ciências da Computação, Sistemas de Informação ou Desenvolvimento de Sistemas, Design ou conhecimento equivalente;
Pelo menos 2 anos de experiência em desenvolvimento Front-end;
Conhecimento avançado em algum framework Javascipt (Vue, React, Angular 4+);
Experiência em desenvolvimento reativo ou bibliotecas de gerenciamento de estado (Redux, Vuex, NgRx);
CSS (Material Design, Stylus);
Vivência sobre a cultura do desenvolvimento de software ágil (Scrum, Kanban ou XP);
Conhecimento sobre integração contínua e os conceitos do Git como branching, pull-requests, etc;
Gosto por atuar em um ambiente com foco no cliente, valorização pela comunicação e feedback, auto disciplina, empreendedorismo, autopercepção e autodesenvolvimento, etc.;
Inglês intermediário.

## O que nos surpreenderia

Conhecimentos avançados sobre Vue.js;
Experiência em e-commerce;
Experiência com desenvolvimento de APIs RESTful estáveis, seguras, confiáveis e escaláveis;
Gosto pelo desenvolvimento utilizando técnicas de TDD/BDD;
Experiência com infra-estrutura (deploy em S3, CDN, Cache, etc).

## O que oferecemos

Uma cultura que valoriza o compromisso com a excelência e a persistência para que o ótimo seja ainda melhor;
Um ambiente de trabalho leve e estimulante, com equipes engajadas pela busca da qualidade e satisfação dos nossos clientes;
Uma biblioteca corporativa, com a aquisição ilimitada de livros, baseada nas sugestões dos colaboradores;
Frutas frescas todos os dias;
Remuneração compatível com mercado e com suas atribuições;
Além dos benefícios básicos como Vale Alimentação/Refeição, Vale Transporte e Plano de saúde.

## Local
Office, Florianopolis/SC
Nosso novo escritório fica no Corporate Park, em Santo Antonio de Lisboa.

## Contratação

CLT - 220 horas mensais, 40 horas semanais, 8 horas diárias :)

## Nossa empresa

Nascemos em 2006 com o propósito de aproximar pessoas de experiências ao vivo. E desde então nosso foco está em desenvolver produtos e serviços que possibilitam a venda, gestão e acesso a essas experiências em todo o país. Nossos produtos são utilizados diariamente por mais de 1 milhão de visitantes no nosso site, além de centenas de organizadores que emitem mais de 3 milhões de ingressos por ano na nossa plataforma. 

Viver ao vivo faz parte do nosso DNA, e por isso o #vivaaovivo é o nosso primeiro valor, seguido do Saia do Sofá, Seja Protagonista, Evolua, Descomplique e Quebre o teto.

Mais do que vender e gerenciar ingressos, trabalhamos com sonhos e expectativas dos nossos clientes, e queremos que eles saiam encantados dessa troca. E para que possamos proporcionar "A"​ experiência e não só mais uma, temos um time fera nos bastidores que está sempre pensando em formas de evoluir e melhorar a forma como fazemos as coisas por aqui. 
E quando as conquistas saem da curva, apitamos bem alto para que todos ouçam e celebrem juntos! 
Afinal depois do @SOMOS TODOS BLUETICKET, e isso nos enche de orgulho! :)

## Como se candidatar

Você pode se candidatar para uma de nossas vagas no site:
http://institucional.blueticket.com.br/trabalhe-conosco/#jobs

## Tempo médio de feedbacks

Em geral, costumamos enviar feedbacks em até no máximo 02 dias após cada etapa. Somos reconhecidos por não deixar nenhum candidato sem receber feedback <3

## Labels

- Alocado
- CLT
- Junior
- Pleno
# # #

**Comment by LuizGMiranda** [comment]
Ainda esta aberta?

**Comment by mariaeugenialuz** [comment]
> Ainda esta aberta?

Oii, bom dia! 
Sim, ainda temos oportunidade para Front End. Nesse link você pode se candidatar: http://institucional.blueticket.com.br/trabalhe-conosco/#jobs

Se tiver disponibilidade podemos bater um papo hoje as 18h ou amanhã as 11h
:)
Aguardo teu retorno!
Um abraço,
Maê
