### ISSUE TITLE
[Uberlândia] Front-end Developer Junior na NetSupport

### ISSUE THREAD

**Issue by vmesel** [frontendbr/vagas#2514]
Atributos da vaga:
Empresa: NetSupport
Faixa salarial: R$ 1.000,01 a R$ 3.000,00
Estado: Minas Gerais
Local da vaga: Uberlândia
Nível: Junior
Aceita Remoto?: Não
Descrição da vaga
A NetSupport é uma startup em estágio de scaleup que opera uma plataforma de Suporte Técnico de TI, que realiza atendimentos através de uma comunidade de Supporters (profissionais freelancers).

Ainda acha que essa vaga é a sua cara? Então venha fazer parte do nosso time!

O Profissional que integrará nosso time de desenvolvimento irá crescer junto com a gente e contribuir no nosso negócio com a sua formação acadêmica.

Requisitos
﻿Formação
* Curso superior na área de tecnologia da informação completo ou em andamento

Requisitos
* Framework Vue.js
* API REST
* HTML, padrões de CSS e JavaScript ES6
* Design Pattern
* Versionamento de código com git e github

Desejável conhecimento em:
* Conhecimento básico em Sistemas Operacionais (Linux)
* Node.js
* Desenvolvimento Agil Scrum.

[Se inscreva clicando aqui](http://frontjobs.com.br/job/97/?utm-source=frontendbr)

**Comment by jonathassk** [comment]
Olá, eu não estou fazendo o superior na área nesse momento, estou esperando para fazer a transferência de curso, mas tenho técnico em informática pelo instituto federal, espero que seja aceito, caso seja eu já me candidatei.

**Comment by vmesel** [comment]
@jonathassk manda aplicação! sem problemas!

**Comment by jonathassk** [comment]
@vmesel eu recebi um email com um link, porem ele não funciona, e não acho a parte de contato do site da frontJobs pra tentar descobrir o que faço, com quem entro em contato para conseguir ver o desafio proposto?
