### ISSUE TITLE
[Remoto] Front End Developer na CodeLeap UK

### ISSUE THREAD

**Issue by vrgimael** [frontendbr/vagas#2517]
## Descrição da vaga

👔 Vaga: Desenvolvedor Front-End
💼 Empresa: CodeLeap UK
📍 Localização: Onde quiser (remoto)
🌎 Idioma necessário: Inglês fluente

## Local

Remoto - Escritório central em Londres, Reino Unido

## Benefícios

💵 Remuneração: R$5000 a R$8000 por mês

#### Diferenciais

- Sem horário ou local de trabalho, o que importa é fazer acontecer!
- Equipe flexível, espaço para crescimento na empresa

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com desenvolvimento em React e JavaScript

**Desejáveis:**
- conhecimentos em React-Native
- conhecimentos em Python

## Contratação

PJ a combinar

## Nossa empresa

👉 Interessado? Veja: https://codeleap.co.uk/careers/frontend

## Como se candidatar

✉️ Mande seu CV para: apply@codeleap.co.uk

## Labels

- 🏢 Remoto
- 👨 Pleno
- ⚖️ A-Combinar
- ⚖️ PJ
- 💰 5k-8k

**Comment by tavaresrafa** [comment]
Enviado! ;)

**Comment by arielconti10** [comment]
Sent :)
