### ISSUE TITLE
[Rio de Janeiro] Front-end Developer na R4S

### ISSUE THREAD

**Issue by JulianaConte** [frontendbr/vagas#2525]
## Descrição da vaga

Estamos contratando um Front-end Developer que será o responsável por definir as tecnologias a serem utilizadas.

Desenvolver e manter os sistemas interno da companhia. 

## Local

Escritório em Botafogo

## Benefícios

- Plano de saúde
- Seguro de vida
- Auxílio creche

#### Diferenciais

- Carga horária reduzida

## Requisitos

**Obrigatórios:**
- Conhecimento em JS, HTML5, CSS3, Angular, e Bootstrap;
- Conhecimento em SASS ou LESS.

**Desejáveis:**
- Conhecimentos em Sharepoint

## Contratação

CLT

## Nossa empresa

R4S

## Como se candidatar

Por favor envie um email para juliana@r4s.com.br com seu CV anexado - enviar no assunto: Vaga Front-End Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: juliana@r4s.com.br

## Labels

- Alocado
- CLT
- Pleno
- Sênior
- Rio de Janeiro

**Comment by evertonProgramadorCriativo** [comment]
8 mil
