### ISSUE TITLE
[Florianópolis] Front-end Developer na Softplan

### ISSUE THREAD

**Issue by dantasrafael** [frontendbr/vagas#2528]
## Descrição da vaga

Desenvolvedor front-end - React

## Local

Escritório, Santa Catarina - Florianópolis

## Benefícios

- Plano de saúde
- VR/VT
- Outros

## Requisitos

**O que esperamos de você:**
- Definir a arquitetura e construir o frontend de sistemas e aplicações web e mobile, utilizando tecnologias atuais e atendendo requisitos de responsividade e acessibilidade na web, implementando códigos que sejam escaláveis, fáceis de manter, eficientes e elegantes;
- Definir boas práticas, mantendo-se atualizado nas novas tecnologias de frontend e capacitando outros desenvolvedores;
- Participar de projetos de desenvolvimento de novos softwares, seguindo os protótipos definidos, planejando e implementando a estrutura e componentes da interface, utilizando para isso o framework de javascript React;
- Apoiar e orientar a elaboração de rotinas automatizadas de testes, utilizando-se de ferramentas e padrões para os testes necessários;
- Construir e validar protótipos de interfaces com usuários e clientes;
- Utilizar metodologias de UX no desenvolvimento de produtos e/ou funcionalidades, assim como apoiar o time na utilização estas metodologias;

**Obrigatórios:**
- Conhecimento avançado em HTML5, CSS3 (Sass), JavaScript (ES6+);
- Conhecimento avançado em React e Redux;
- Conhecimento intermediário em GIT.
- Conhecimento intermediário em apis REST e testes automatizados;
- Conhecimento em algumas das bibliotecas Webpack, Gulp ou Grunt;
- Conhecimento de técnicas e práticas de Clean Code;
- Experiência em equipes dinâmicas e metodologias de desenvolvimento ágeis;
- Conhecimento em princípios de design de interação, UX e Design System;
- Ter um perfil proativo, boa comunicação, raciocínio lógico, responsabilidade e comprometimento;

**Diferenciais:**
- Formação completa em ciências da computação, sistemas de informação ou cursos equivalentes;
- Conhecimento das diretrizes de interfaces da Google (Material Design) e Apple;
- Conhecimento em Java e/ou outras linguagens backend;
- Conhecimento em bancos de dados relacionais e não relacionais;
- Conhecimento em outros frameworks JavaScript como Angularjs, Vue.js, etc;

## Contratação

CLT

## Nossa empresa

Aqui na Softplan somos apaixonados por desenvolver soluções que fazem a diferença na vida das pessoas e estamos entre as maiores empresas do Brasil no desenvolvimento de softwares de gestão!

## Como se candidatar

Por favor envie um email para rafael.d@softplan.com.br e/ou kleber.silva@softplan.com.br com seu CV anexado - enviar no assunto: Vaga Frontend - Black Tainhas

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.

## Labels

- Alocado
- CLT

**Comment by dantasrafael** [comment]
Olá amigos,

Não consegui devolver um feedback para todos.
Mediante isto, estou retornando um feedback aqui..

"O processo já está em avaliação pela gerência e em breve estarão entrando em contato com os candidatos selecionados."

Muito obrigado a todos.
Rafael Dantas.

**Comment by julianchaos** [comment]
@dantasrafael, estão aceitando cadastros para a vaga ou já fechou?

**Comment by dantasrafael** [comment]
Olá @julianchaos , ainda não fechamos a vaga. Se tiver interesse em participar, pode enviar analisaremos junto com os demais.
Obrigado.
