### ISSUE TITLE
[Belo Horizonte/Remoto] - Desenvolvedor Front-End Mobile Senior na mLearn

### ISSUE THREAD

**Issue by yanmagale** [frontendbr/vagas#253]
## Descrição da vaga

Procuramos por um desenvolvedor(a) front-end mobile que seja apaixonado(a) por Javascript, tecnologia móveis e, claro, tenha vontade de fazer parte de algo grandioso.

### Suas Responsabilidades
– Arquitetar e desenvolver aplicações mobile inovadoras.
– Análise de código para avaliar e melhorar o estilo e eficiência nos sistemas existentes.
– Definir e evangelizar a equipe no uso de boas práticas de desenvolvimento front-end.
– Aprimoramento de usabilidade e performance das interfaces.
– Auxiliar na implantação de Continuous Integration com testes de código Javascript e de Interface.

### Perfil Esperado
– Disciplina e organização é fundamental.
– Sedento por conhecimento.
– Interesse e facilidade em aprender novas tecnologias, linguagens de programação e ambientes de desenvolvimento.
– Trazer críticas em relação a ferramentas utilizadas, com o objetivo de melhorar o desenvolvimento.
– Pesquisador nas horas vagas, trazendo novidades que podem ser  aplicadas nos projetos existentes.
– Senso crítico.
– Engajamento com a comunidade e projetos open source.
– Engajamento com a equipe para o crescimento sustentável de todos.

## Local

Remoto ou no escritório, Avenida Bandeirantes, 330, Sion - Belo Horizonte

## Benefícios
– Contratação imediata.
– Ambiente descontraído e inovador.
– Flexibilidade para trabalho remoto.
– Oportunidade de trabalhar em projetos inovadores e divertidos.
– Incentivo para Palestrar e Participar de eventos.
– Plano de carreira.
– Plano de saúde.
– Vale refeição.
– Vale transporte.

## Requisitos

**Obrigatórios:**
– Conhecimento avançado em Javascript e framework Angular.
– Experiência com desenvolvimento mobile com Ionic / Cordova.
– Ter um bom conhecimentos de ES6.
– Bom conhecimento de task runner Gulp.
– Conhecimento em controle de versão Git.
– Inglês técnico. (Leitura e escrita).
– Bom entendimento sobre APIs RESTful.
– Domínio em HTML5 & CSS3 (SASS).

**Desejáveis:**
– Conhecimento básico em PHP.
– Conhecimentos em Vue.js, Flux/Redux e/ou React.js

**Diferenciais:**
– Participação ativa no GitHub.
– +200pts no StackOverflow.
– Gostar de rock n’ roll!

## Contratação

Contrato CLT com salário de acordo com a experiência

## Nossa empresa

Somos uma Startup mineira que busca revolucionar a forma como as pessoas aprendem por meio de seus dispositivos móveis, entregando uma experiência rica e inovadora com foco no engajamento do ensino a distância.  Em pouco mais de 3 anos de existência, já atendemos mais de 4 MILHÕES de usuários através de nossos produtos e conteúdos disponibilizados em conjunto com grandes marcas, que assim como a mLearn, acreditam que investir em educação é essencial para mudar os rumos do nosso país.  

Mais detalhes sobre a vaga [aqui](http://mlearn.com.br/frontend-dev-mobile-senior-at-mlearn/).

## Como se candidatar

Envie o seu currículo e github para `recrutamento@mlearn.com.br.` 
Caso selecionado, você será convidado para participar de uma entrevista presencial ou via Skype (dependendo da sua localidade).

**Comment by paulovitorwd** [comment]
Enviado!

**Comment by AllanPinheiroDeLima** [comment]
Enviado!
