### ISSUE TITLE
[São Paulo] Front-end Developer na Driven

### ISSUE THREAD

**Issue by megandavulpi** [frontendbr/vagas#2531]
### Sobre a empresa: Driven

Somos a Driven CX, um grupo formado pelas empresas TopperMinds, Profite e BlueFoot, juntos somos o maior grupo consultivo digital do segmento e a única nativa digital. 

### Descrição: O que você irá fazer?

Se você é apaixonado por desenvolvimento web e consegue resolver problemas lógicos de maneira ágil e inteligente, como front-end developer aqui na Driven você vai ter a oportunidade de desenvolver aplicações para um dos mais parrudos ecossistemas de e-commerce da América Latina.

### As habilidades necessárias:

HTML
CSS
JAVASCRIPT
JQUERY
GIT
GULP
SASS/LESS
AJAX
React

### Desejável:

Vue

### Beneficios:

Além de fazer parte de uma empresa e time muito legal, com um ambiente descontraído com sala de jogos, biblioteca compartilhada e pizzada todo mês, você terá:

Vale Refeição;
Vale Alimentação;
Vale Transporte;
Plano de Saúde coparticipativo;
Plano Odontologico

### Você gostará de trabalhar aqui se:

É normalmente inconformado(a) com coisas que não funcionam e gosta de mudar o jogo;
Gosta de interagir com a galera do trabalho;
Acredita que aprender mais sobre tecnologia e soft skills vão fazer de você um(a) profissional melhor;
Entende que o planejamento e o auto gerenciamento é imprescindível para o seu trabalho;
Gosta de participar ativamente e contribuir no produto com soluções realmente efetivas;
Gosta de um modelo de gestão horizontal e um ambiente muito legal de se trabalhar :);

### 🦊 Fale direto com o recrutador da vaga via WhatsApp: http://bit.ly/driven_frontjunior

**Comment by Ogunn** [comment]
Why do you use JQuery? Is it a legacy code?

**Comment by Ogunn** [comment]
No answer :(

**Comment by vncscoelho** [comment]
@Ogunn 

Não tenho a ver com a vaga, mas sei que a Vulpi é um intermediário, então melhor você clicar no link (que leva pra um chat de Whatsapp) se quiser alguma info.

**Comment by megandavulpi** [comment]
> No answer :(

Desculpe pela demora!

Favor entrar em contato com o recrutador da vaga via link divulgado... ele vai te informar tudo, ok?
