### ISSUE TITLE
[São Paulo] React Developer na Youniversity

### ISSUE THREAD

**Issue by viniciushvsilva** [frontendbr/vagas#2533]
## Descrição da vaga

Estamos a procura de um dev para desenvolver um admin de gerenciamento de vagas de estágio ofertadas por empresas.

## Local

Remote ou São Paulo – SP – centro

## Requisitos

**Obrigatórios:**
- HTML5, CSS3, Javascript
- React JS

**Desejáveis:**
- Experiência com MongoDB
- Experiência com ExpressJS
- Experiência com Redux

## Contratação

A combinar

## Nossa empresa

A Youniversity é uma startup que busca auxiliar o estudante de ensino superior em suas atividades diárias.

## Como se candidatar

Enviar email para recrutamento@youniv.com.br contendo Currículo/Linkedin/Github/Portfólio e meios de contato. Favor usar o assunto do email: Vaga ReactJS

## Labels

- 🏢 Presencial
- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ CLT
- ⚖️ Freela
- ⚖️ Outros
- ⚖️ PJ

**Comment by bonejah** [comment]
Ainda estão a procura?
