### ISSUE TITLE
[São Paulo] Desenvolvedor(a) Front-end | Profite

### ISSUE THREAD

**Issue by hjdesigner** [frontendbr/vagas#254]
## Descrição da vaga

Você já conhece a [Profite](http//www.profite.com.br)? Nós somos a maior implantadora de e-commerce do Brasil. Atendemos clientes como O Boticário, Tim, C&A, Avon, Timex, Shoestock, Trifil entre outros.

Estamos procurando um(a) Desenvolvedor(a) Front-end, com sólidos conhecimentos em HTML. CSS e JS para projetar interfaces e entregar a melhor experiência para os consumidores visando sempre a otimização do código e agilidade no desenvolvimento.

O perfil que procuramos é de uma pessoa ligada no 220v, que respire a cultura mobile first e que seja capaz de defender ideias e apresentá-las de forma clara e objetiva. De fácil relacionamento, organizado(a) e comprometido(a) com prazos e qualidade das entregas.

## Local

Rua do Rocio, 423 - Vila Olímpia

## Requisitos

- Html5
- CSS3
- Javascript
- Jquery
- Git
- Gulp/Grunt
- Sass/less
- AJAX
- Scrum
- Sites responsivos
- CrossBrowser
- Conhecimento em ambiente Node.js
- **Iniciativa, criatividade e colaboração**
- Boas práticas: reutilização de código, semântica, organização, performance

## Desejável

- Vtex
- React e Redux

## Benefícios

- Vale-refeição
- Vale-alimentação
- Plano de saúde
- Plano odontológico
- Vale-transporte
- Folga de aniversário

## Como se candidatar

Para se candidatar: allan.serra@profite.com.br

**Comment by julianorafael** [comment]
Aceita remoto ou só alocado?

**Comment by LFeh** [comment]
Quais as labels? :)

**Comment by hjdesigner** [comment]
@LFeh 
Alocado
CLT
Júnior, Pleno ou Senior
:)

**Comment by hjdesigner** [comment]
@julianorafael Só alocado :)

**Comment by Carlosxell** [comment]
Só da para se candidatar através desse site?....

**Comment by raulfernando** [comment]
Os requisitos são os mesmos para Junior, Pleno e Sênior?

**Comment by hjdesigner** [comment]
@Carlosxell Sim, somente pelo site.

**Comment by hjdesigner** [comment]
@raulfernando Sim, os requisitos são os mesmos. :)
