### ISSUE TITLE
[Curitiba e Região] Desenvolvedor Front-end Pleno

### ISSUE THREAD

**Issue by nandomoreirame** [frontendbr/vagas#255]
## Descrição da vaga

Trazer novas soluções de Front-end para plataforma de E-commerce própria.

## Local

Pinhais - Região Metropolitana de Curitiba

## Benefícios

- Vale Refeição
- Bonificação mensal
- Plano de saúde com coparticipação
- Ambiente diferenciado (Você vai curtir!)
- Descontos em universidades, farmácias e outros

## Requisitos

  **Obrigatórios:**
  - Grande vivência em tecnologias e ferramentas voltadas ao front-end;
  - Pré-processador SASS;
  - Automatização de tarefas com Gulp;
  - Técnicas Cross Browser e Cross Device;
  - Preocupação com segurança;
  - Preocupação com performance;
  - Noções de UX e SEO;
  - Conhecimentos de metologias Ágeis;

  **Desejáveis:**
  - Experiência do usuário (UX);
  - Conhecimento de SEO no front-end;
  - Testes automatizados com Javascripts;
  - Noções de testes de Usabilidade;
  - Noções de testes A/B;
  - Testes de interface e BDD;
  - Conhecimentos de ES6;
  - Conhecimentos de ReactJS;

**Diferenciais:**
 - Contribuição em projetos opensource;
 - Participação e colaboração em comunidades;

## Contratação

CLT

## Nossa empresa

A lojasKD é um dos principais E-Commerces de móveis do país. Uma enorme variedade de produtos inspiradas para decorar cada momento da vida do cliente. Fundada em 1997, começou com lojas físicas, mas hoje está 100% online. Somos 150 profissionais apaixonados pelo que fazemos! Cada vez mais querendo se posicionar como uma empresa de tecnologia.

## Como se candidatar

Envie um email para vagas.ti@lojaskd.com.br com título: **Sou o desenvolvedor front-end que vocês procuram**. Adicione seu LinkedIn, telefone e seu perfil do Github, BitBucket ou similar. Queremos ver seus códigos.

**Comment by raloliver** [comment]
Enviado!

**Comment by nandomoreirame** [comment]
Valeu @raloliver entraremos em contato contigo brother! :metal:

**Comment by thenewbiemaster** [comment]
Enviado!

**Comment by nandomoreirame** [comment]
Obrigado @thenewbiemaster, entraremos em contato :+1:

**Comment by JCMais** [comment]
Enviado. :)
