### ISSUE TITLE
[São José dos Campos] Front-End Developer na RM07

### ISSUE THREAD

**Issue by rodrigovmachado** [frontendbr/vagas#2552]
## Descrição da vaga

Buscamos um desenvolvedor Front-End pra somar ao time da RM07, dá um bizu nos requisitos da vaga:

## ATIVIDADES DIÁRIAS
- Tomar café;
- Trabalhar em Recorte de layouts (PSD to HTML);
- Desenvolvimento de Aplicativos Hibridos

## Local

Remoto ou Escritório, São José dos Campos-SP

## Requisitos

**Obrigatórios:**
Ter experiência em Desenvolvimento Web de, no mínimo, 3 anos;
Proficiência em CSS, Design Responsivo e Javascript;

**Desejáveis:**
Frameworks JS (Angular ou React);
Web Frameworks;
Desenvolvimento de Código com Melhores Práticas, Bem Estruturado, Testável e Escalável;
Pré-processadores de CSS (Sass ou Less);

**Diferenciais:**
Focado em Resultados;
Proativo;
Gosta de sempre Aprender Coisas Novas;
Ionic Framework
Uso de SDKs e APIs REST;
Web Frameworks (Rails, CakePHP);

## Contratação

PJ a combinar

## Nossa empresa

A RM07 é uma empresa com 10 anos no mercado de desenvolvimento e atual na produção de tecnologia para empresas de diversos tamanhos, de Startups à Multnacionais conseguimos atuar e desenvolver sempre a melhor solução pensando em quem vai usar.

## Como se candidatar
Enviar curriculo e portfólio (github ou site) para contato@rm07.com.br com o assunto "FRONT CABULOSO OUTUBRO" com PRETENSÃO SALARIAL e Regime de contratação (CLT ou PJ)

##  Labels
PJ
Alocado ou Remoto

**Comment by raloliver** [comment]
Enviado!

**Comment by willianmonteiro** [comment]
Enviado!
