### ISSUE TITLE
[Jaguariuna] Front-end Developer REMOTO na AbInbev

### ISSUE THREAD

**Issue by taianeuchoac** [frontendbr/vagas#2558]
## Descrição da vaga
Será contratado e atuará em projeto para a AbInbev, em regime remoto, até o final do ano de 2019.
Prestará serviços para uma squad que atua com dados de uma área especifica da empresa.

## Local
A empresa fica em Jaguariuna, mas o profissional atuará de forma remota

## Benefícios
Contratação PJ.

#### Diferenciais

- Atuação remota;
- Atuação em projeto global;
- Projeto com previsão de finalização no final de 2019.

## Requisitos

**Obrigatórios:**
Angular;
Bootstrap;
SaSS;
CSS 3;
HTML 5;

**Diferenciais:**
- inglês avançado

## Contratação
PJ a combinar

## Nossa empresa
A Mazzatech é uma consultoria de TI que esta no mercado há mais de 10 anos. A AbInbev é uma multinacional da área de bebidas, localizada em Jaguariuna.

## Como se candidatar
Por favor envie um email para taiane@mazza.tech com pretensão salarial.

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 2 dias após cada processo.

## Labels

- Alocado
- PJ
- Remoto
- Sênior

**Comment by raloliver** [comment]
Enviado.

**Comment by murigama** [comment]
Enviado
