### ISSUE TITLE
[Maringá] Desenvolvedor PHP na Precode Soluções em e-commerce

### ISSUE THREAD

**Issue by PrecodeSolucoes** [frontendbr/vagas#2561]
Contrata-se Desenvolvedor!

Conhecimentos necessários:

PHP Orientado Objeto
Desenvolvimento PHP e PostgreSQL
Desenvolvimento e integração de API Rest
Soap
JQuery
JavaScript

Benefícios:
Salário + Vale Transporte + Plano de Saúde Coparticipativo

Escolaridade:
Ensino Superior
Faixa Salarial:
R$ 2.500,00 - R$ 5.000,00

Maringá - PR
Email: recrutamento@precode.com.br

**Comment by MrS4w** [comment]
Vagas somente front-end 😄
