### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor(a) Front-end na Wikki Brasil

### ISSUE THREAD

**Issue by gilbuju** [frontendbr/vagas#2564]
[Front End] [CLT] [pleno]

Oportunidade para desenvolvedor Front End 

Programador com experiência e que faça a diferença para vencer os obstáculos inerentes ao desenvolvimento do frontend de um software web. Bom conhecimento e experiência em sistema Linux. Desenvolvimento utilizando JavaScript, CSS, XML, JSON, e sólidos conhecimento e  experiência no framework ReactJS. É necessário comprovar ter desenvolvido projetos usando essas ferramentas.

Empresa Wikki Brasil

Mais info ou envio de CV: 
gilmar.bueno@wikki.com.br

**Comment by fabiodaemon** [comment]
Qual nivel vcs procuram? Tenho conhecimento de tudo informado porem sou de nivel Jr/Pleno (depende da complexidade do projeto)

**Comment by gilbuju** [comment]
Olá Fabio, obrigado pelo retorno e pela dúvida. Vou alterar agora mesmo o
post. É uma vaga nível pleno.

Qualquer outra dúvida ou envio de CV, estou aqui.

Att


*Gilmar Bueno de Alcantara Júnior*

Universidade Federal do Rio de Janeiro
Graduando em Engenharia de Produção



Em ter, 22 de out de 2019 às 15:58, Fabio Daemon <notifications@github.com>
escreveu:
