### ISSUE TITLE
[São Paulo] Front-End Developer na follow55

### ISSUE THREAD

**Issue by FelipeMarcos** [frontendbr/vagas#2567]
## Descrição da vaga

Um estúdio criativo com foco em soluções digitais. Somos independentes e estamos em uma incansável busca por inovação. Estamos em constante crescimento e buscamos um(a) Front-End para integrar nossa equipe.

## Local

São Paulo - SP (Tatuapé)

## Benefícios

- 13º Salário;
- Férias;
- Home Office 2x por semana;
- Estacionamento;
- Sorvetes Rochinha free.

## Requisitos

**Obrigatórios:**
- HTML;
- CSS (SCSS);
- JavaScript (ES6);
- Git;
- Webpack
- Proatividade;
- Disposto a trabalhar com pessoas de perfis diferentes.

**Desejáveis:**
- Vue.js
- Docker

## Contratação

PJ a combinar

## Como se candidatar

Enviar e-mail para felipe@follow55.com.br com seu CV anexado.

## Labels

- Alocado
- PJ
- Pleno
- Sênior

**Comment by OnionHead** [comment]
Amei o site, enviado!
