### ISSUE TITLE
[Rio de Janeiro] Front-end Developer na TOTVS

### ISSUE THREAD

**Issue by brunoromeiro** [frontendbr/vagas#2569]
## Descrição da vaga

Que tal fazer parte de um time que está criando um produto internacional que está impactando grandemente o cenário da hotelaria atual?

## Local

Escritório, Rio de Janeiro - Centro

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ 26/dia
- 70% de GymPass
- Vale Transporte
- Plano Odontológico

#### Diferenciais

- No dress code
- máquina de café
- sala de jogos

## Requisitos

**Obrigatórios:**
- Conhecimentos sólidos em JavaScript
- Conhecimentos sólidos em TypeScript
- Conhecimentos sólidos em frameworks modernos (angular, react, vue, etc)
- Conhecimentos em testes unitários
- Git / GitFlow básico

**Desejáveis:**
- Estar disposto a aprender e trabalhar com Angular 6+
- RxJS
- Ter trabalhado com Angular 2+

**Diferenciais:**
- projetos opensource
- participação de palestras, eventos e meetups

## Contratação

CLT a combinar

## Nossa empresa

Líder absoluta no mercado SMB do Brasil, a TOTVS cria soluções inovadoras para transformar o dia a dia das empresas e ajudá-las a superar os desafios de seus negócios. É a maior empresa de desenvolvimento de software de gestão do país, investindo R$ 1.6 bilhão em pesquisa e desenvolvimento nos últimos 5 anos para atender as exigências de 12 setores da economia.

## Como se candidatar

Por favor envie um email para klaus.machado@totvs.com.br com seu CV anexado - enviar no assunto: Vaga FrontEnd

## Labels

- CLT
- Pleno
- Sênior

**Comment by fabiomirandaa** [comment]
Vaga muito interessante :)

**Comment by brunoromeiro** [comment]
Essa vaga continua em aberto, e agora são **3 vagas**!

**Comment by eriktos** [comment]
Tenho interesse!

**Comment by brunoromeiro** [comment]
@eriktos envia seu currículo pra gente.

**Comment by Rodrigo54** [comment]
eu enviei um currículo em outubro gostaria de um retorno

**Comment by totvs-challenges** [comment]
> eu enviei um currículo em outubro gostaria de um retorno

Olá @Rodrigo54, acabamos de te posicionar por email.
