### ISSUE TITLE
[Santos, SP] Desenvolvedor Front-End | Cubbo

### ISSUE THREAD

**Issue by diegomalone** [frontendbr/vagas#257]
## Descrição da vaga

Procuramos um desenvolvedor Front-End para trabalhar em nossos projetos já existentes e participar de novos projetos junto com nossa equipe de desenvolvimento.

## Local

Santos, SP.

## Benefícios
- Ambiente descontraído, informal e dinâmico
- Oportunidade de contribuir efetivamente para a evolução de uma startup
- Possibilidade de crescimento na empresa
- Contratação PJ

## Requisitos

Obrigatórios
- Fluência em JS
- Experiência com HTML e CSS3
- Conhecimentos em Git
- Boas práticas de desenvolvimento
- Facilidade para trabalhar em equipe
- Inglês técnico
- Disponibilidade para trabalho presencial em Santos, SP

Desejáveis
- Experiência com frameworks modernos: Vue, Angular, etc
- Profunda compreensão do DOM e suas propriedades
- Conhecimento básico de programação em PHP e framework Laravel
- Conhecimento em UX
- Pré-processadores CSS (PostCSS/Stylus/Sass/Less)
- Experiência com APIs RESTful
- Experiência em desenvolvimento ágil
- Curiosidade e vontade de aprender novas ferramentas e tecnologias
- Capacidade de pensar e resolver problemas de forma criativa

Diferenciais
- Projetos Open Source
- Experiência em startups
- Conhecimento em banco de dados

## Contratação

PJ a combinar.

## Nossa empresa

O Cubbo Design Studio é uma empresa formada por inovação e comprometimento, pioneira na baixada santista em seu segmento. Com o foco em projetos inovadores, desenvolvendo aplicativos e sistemas para facilitar a vida de clientes e empresas.

## Como se candidatar

Por favor envie um email para vagas@cubbo.com.br com o título "Vaga Front-End".

**Comment by diegomalone** [comment]
Labels: Alocado, Pleno, Sênior, PJ

**Comment by MatheusJusto** [comment]
pena não ter junior :(

**Comment by tunnes** [comment]
Meeu, que vaga linda!

**Comment by raloliver** [comment]
Me encaixo muito bem nessa descrição... só preciso voltar a praticar PHP.

**Comment by LFeh** [comment]
Encontrou? :)

**Comment by diegomalone** [comment]
A vaga foi preenchida, obrigado a todos.
