### ISSUE TITLE
[São Paulo] Front-end Developer na Stone

### ISSUE THREAD

**Issue by taianeuchoac** [frontendbr/vagas#2570]
## Descrição da vaga
Oportunidade para atuar em projetos internos da empresa.

## Local
Escritório, São Paulo - Vila Olímpia.
APENAS para profissionais que residem no interior de São Paulo, há a possibilidade de atuação remota após uma imersão de cerca de 30 dias no escritório da empresa.

## Benefícios
Contratação PJ

#### Diferenciais
Ambiente Inovador;
Escritório da empresa tem diversos ambientes diferentes para descompressão.

## Requisitos
Profissional com mais de 3 anos de experiência em desenvolvimento de sistemas.
Conhecimento e prática em boas práticas de desenvolvimento de software, como TDD, Código Limpo, Padrões de Projeto, entre outras;
Experiência em desenvolvimento voltado para Front-End;
Excelentes conhecimentos e experiência em JavaScript e integração com APIs;
Familiaridade com as práticas de Entrega Contínua (Continuous Delivery);
Experiência com algum Framework de Javascript como (Ex. React, Angular)

Experiência com design de interfaces, CSS e HTML.

**Diferenciais:**
Contribuições em projetos open-source;
Disposição para trabalhar com qualquer tecnologia

## Contratação
PJ a combinar

## Nossa empresa
A Stone é uma empresa brasileira de meios de pagamento, em grande crescimento e visibilidade no mercado. A contratação a principio é pela Mazzatech, consultoria brasileira de TI, que esta no mercado há mais de 10 anos.

## Como se candidatar
Por favor envie um email para taiane@mazza.tech com seu CV anexado - enviar no assunto: Vaga FrontEnd Vila Olimpia. Encaminhar também pretensão salarial.

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 5 dias após cada processo.

## Labels
- Alocado
- PJ
- Pleno
- Remoto
- Sênior

**Comment by ebsene** [comment]
Esta vaga ainda esta aberta?
