### ISSUE TITLE
[Ribeirão Preto] Front-end Developer (React) no Beblue

### ISSUE THREAD

**Issue by Gabrielle1012** [frontendbr/vagas#2573]
## Descrição da vaga

Buscamos um profissional que irá:

- Projetar e implementar soluções de software além de acompanhar os desenvolvedores menos experientes durante o desenvolvimento do produto;
- Desenvolver com alto padrão focado em entregas de software de qualidade com cobertura de código, testes automatizados, integração contínua, etc…;
- Trabalhar em conjunto com o time de design, no projeto de interfaces e UX do produto, seguindo fielmente as especificações;
- Desenvolver e executar planos de testes para validação de aplicações e revisar o resultado dos testes;
- Criar e definir arquitetura do software focando em reusabilidade, clareza e testabilidade, bem como a criação de padrões e bibliotecas internas;
- Participar da modelagem de API’s RESTFul, bem como, garantir a aplicação de boas práticas na criação de aplicações Híbridas ou SPA’s...

## Local

Ribeirão Preto/SP

## Benefícios

- Vale Refeição (CLT)
- Jornada de trabalho flexível

## Requisitos

- Programação Javascript para Front-End utilizando algum framework ou biblioteca como React e - - Redux e seu ecossistema;
- Ciclo de desenvolvimento Agile;
- Experiência com o ecossistema Web (Task Runners, Yarn/NPM, Webpack, Pré-processadores como SAAS e Babel);
- Fluência em JavaScript, HTML5, CSS3;
- Fluência em React e Redux e seu ecossistema;
- Formação de ensino superior em Ciência da Computação ou equivalente;
- Experiência com GIT e GITFlow;
- Conhecimento sobre os princípios de TDD e BDD;
- Inglês Técnico para Leitura e Escrita.

**Diferenciais:**
- Experiência com Integração Contínua e Entrega Contínua (Jenkins, Drone.io, CircleCI, etc...);
- Experiência com ferramentas de monitoramento (NewRelic, Sentry, Datadog, etc...);
- Experiência com AWS (Cloudfront, S3, API Gateway, Route53, ECS, etc...);
- Experiência com Aplicações conteinerizadas com Docker.

## Contratação

CLT ou PJ, a combinar.

## Nossa empresa

O Beblue é a plataforma pioneira de pagamentos atrelada a um sistema de recompensa via cashback - o famoso dinheiro de volta 💰 - para o varejo físico.
Nossa missão é oferecer experiências memoráveis para quem quer que seja, aumentando o poder de consumo das pessoas e ajudando nossos parceiros a vender mais e melhor.
Buscamos profissionais inovadores e apaixonados por tecnologia para se juntar a nós e ajudar na incrível e desafiadora caminhada de inovação nas indústrias de pagamentos e recompensas no Brasil.

## Como se candidatar

https://jobs.kenoby.com/beblue/job/desenvolvedor-front-end-react-senior/5c756de80bc4c269e4e72789

## Labels

🏢 Jornada Flexível
🏢 Presencial ou Remoto
👦 Sênior
⚖️ PJ ou CLT

**Comment by felipefialho** [comment]
@Gabrielle1012 por favor, nas próximas vagas use o padrão: Front-end Developer ou Desenvolvedor(a) 😉

**Comment by Gabrielle1012** [comment]
> @Gabrielle1012 por favor, nas próximas vagas use o padrão: Front-end Developer ou Desenvolvedor(a) 😉

Ok, obrigada @felipefialho

**Comment by wsoaresfilho** [comment]
Essa vaga não se encontra no link fornecido. Já foi preenchida?

**Comment by Gabrielle1012** [comment]
> Essa vaga não se encontra no link fornecido. Já foi preenchida?

A vaga já está novamente no site. Ainda está em aberto.
Obrigada por avisar.
