### ISSUE TITLE
[100% Remote] Front-end Developer na Unbox

### ISSUE THREAD

**Issue by glunbox** [frontendbr/vagas#2578]
Oi, somos a Unbox uma startup que está mudando o mercado de e-commerce no Brasil :)
Estamos buscando um(a) Desenvolvedor(a) Front com experiência em NodeJs e React para nos ajudar a acelerar o roadmap de desenvolvimento do nosso produto.

Somos uma empresa 100% remota com um time incrível de pessoas inquietas e ansiosas para crescer !

Caso tenha se identificado com a gente o link abaixo tem mais detalhes ou você pode mandar um e-mail para inquietos@unbox.plus e agendamos um bate papo por Hangouts.

https://www.linkedin.com/jobs/cap/view/1524815827/?pathWildcard=1524815827&trk=mcm

Psiu: também vale indicar aquelx amigx que tem a cara dessa vaga.

**Comment by simaodeveloper** [comment]
Aplicado <3
