### ISSUE TITLE
[São Paulo] Front-end Engineer na Linte

### ISSUE THREAD

**Issue by iagobyintera** [frontendbr/vagas#2585]
A Linte está crescendo e precisa de você para construir um novo produto.

**É tudo do início!** Estamos desenvolvendo a melhor arquitetura e as melhores tecnologias para construir uma plataforma sustentável, escalável e consistente à longo prazo. Tudo isso para fornecer a melhor performance e experiência para os nossos clientes, entre eles estão Fundação Leuman, Stone, Itaú, 99 e Renault. Apesar de estarmos no início, começamos com tudo!

Atualmente nós trabalhamos com Javascript ES6, Typescrit, GraphQL e React com Redux. Essas tecnologias com pessoas com propósito e dispostas é o que nos faz crescer exponencialmente. Serão bem vindos também conhecimentos em Programação Reativa, TDD, Metodologias Ágeis, e outras boas práticas de programação.

A contratação será feita em regime CLT com horário flexível ou PJ para trabalho remoto. Para o trabalho de forma presencial, estamos na CUBO, em São Paulo. Para mais informações, acesse a página da vaga.

Página da vaga: http://byintera.in/2b

## Labels
- REMOTO
- PLENO
- SÊNIOR
- CLT
- PJ

**Comment by felipefialho** [comment]
@iagobyintera Acho que o link para a vaga está errado

**Comment by iagobyintera** [comment]
@felipefialho Opa, corrigido perdão!

**Comment by fcjonas** [comment]
Qual a faixa salarial?

**Comment by iagobyintera** [comment]
> Qual a faixa salarial?

Essa informação é passada ao longo do processo, se achou interessante e faz sentido para você, pode se inscrever que será informado
