### ISSUE TITLE
[Rio de Janeiro] Full-stack Developer na iBlue consulting

### ISSUE THREAD

**Issue by ana-sene** [frontendbr/vagas#2586]
## Descrição da vaga

Estamos buscando desenvolvedor Full-stack para o nosso time no Centro - RJ, para atuar com Java e Angular 6+.

## Local

Centro - Rio de Janeiro

## Benefícios

- Plano de saúde
- Plano odontológico
- VR de R$ 25,31/dia
- VT
- TotalPass

#### Diferenciais

- Horário flexível
- Treinamentos com nossos parceiros.

## Requisitos
- Experiência com Java e Angular 6+

## Contratação

- CLT a combinar

## Como se candidatar

Por favor envie um email para rhrio@iblueconsulting.com.br com seu CV anexado - enviar no assunto: Vaga Full-stack - RJ

## Labels

- Alocado
- CLT
- Pleno

**Comment by RaphaAmericano** [comment]
O email que enviei retornou. Conferi e o destinatário está correto
