### ISSUE TITLE
[Uberlândia] Front-End Developer | Zup

### ISSUE THREAD

**Issue by Rodolpho16** [frontendbr/vagas#259]
## Descrição da vaga

Desenvolvimento e manutenção de sistemas Web no Front-End,  executando a manutenção dos sistemas e fazendo eventuais correções necessárias, visando atender às necessidades dos usuários. 

## Local

O seu local de trabalho será em nosso escritório de Uberlândia - Minas Gerais.

## Benefícios

- Plano de Saúde
- Plano Odontológico
- Vale alimentação e refeição
- Verba de treinamento 
- Bônus de indicação profissional
- PLR anual
- Seguro de Vida
- Plano de telefonia
- AssiNATURA
- Sala de jogos, Happy Hour e o melhor ambiente para se trabalhar!

## Requisitos

**Obrigatórios:**
- Experiência com HTML, CSS, Javascript
- Experiência com NodeJs, Angular

**Desejáveis:**
- Conhecimento em Rest e Web services
- Experiência com metodologias ágeis (SCRUM)

**Diferenciais:**
Praticas como: 
 ECMAScript 6; 
 Flexbox; 
 Testes unitários; 
 Layout responsivo; 
 npm; 
 webpack
 Clean code

## Contratação

CLT - Salario a combinar

## Nossa empresa

Fundada em 2011 por Bruno Pierobon, Flavio Zago, Gustavo Debs e Felipe Almeida, a zup tem como foco ajudar empresas a lidar com toda complexidade de integração de sistemas e externalização de serviços, apoiando grandes clientes de vários segmentos da economia.

A ZUP possui plataforma e ferramentas completas para viabilizar técnica e financeiramente suas estratégias digitais. Sua tecnologia começou a ser desenvolvida em 2007 e busca solucionar desafios de ambientes completos para TI

A companhia tem sua sede em Uberlândia (MG), onde está instalada a área de pesquisa e desenvolvimento, escritórios técnicos em São José do Rio Preto e Ribeirão Preto e escritório comercial em São Paulo.

## Como se candidatar

Por favor envie um email para vagas@zup.com.br com seu CV anexado - enviar no assunto: Front-End Zup

**Comment by brunoravanhani** [comment]
assiNATURA seria assinatura de coisas da Natura?

**Comment by Rodolpho16** [comment]
Olá Bruno,

Isso. É um app desenvolvido pela empresa. Funciona como uma assinatura da NATURA mesmo. Produtos da linha Soul. A Zup paga até 50,00 em compras pelo app.
