### ISSUE TITLE
[Remoto] Front-end Developer na Mimoo Grátis

### ISSUE THREAD

**Issue by LucasKauer** [frontendbr/vagas#2596]
# Mimoo Grátis &middot; <img src="https://static.wixstatic.com/media/840614_faaab4ff77fc41e0aff9137abf78778c~mv2.png/v1/fill/w_32%2Ch_32%2Clg_1%2Cusm_0.66_1.00_0.01/840614_faaab4ff77fc41e0aff9137abf78778c~mv2.png" />
## Descrição da vaga
A Mimoo busca uma pessoa desenvolvedora de software, entusiasta de tecnologia, especialista em Front-end e que tenha MUITA ânsia por aprendizado. Espera-se dessa pessoa boa comunicação escrita e verbal, vontade de desenvolver habilidades adjacentes a de desenvolvimento e capacidade de lidar com a diversidade das pessoas.

#### Nossos projetos
A [Mimoo](https://www.mimoogratis.com.br/) tem como objetivo fazer parte da rotina de consumo semanal dos consumidores e, para isso, desenvolverá uma solução que colete dados sobre o perfil e comportamento de compra dos seus usuários em troca de mimos (trials). Sobre a coleta:
1. **Sobre a pessoa**: perguntas e respostas sobre pessoa, perfil e comportamento...
2. **Sobre os lugares que ela compra**: upload de recibos que comprovem que o perfil é cliente da farmácia A, supermercado B, etc...
3. **Sobre os produtos que ela consome**: upload de fotos e/ou leitura cód. de barra de produtos / categoria CPG - dentro de casa...

#### Nossa stack:

* React (utilizando Hooks)
* AWS (incluindo Cognito, Lambda, DynamoDB, S3, Aurora, etc.)
* CD/CI (seed.run)
* GitHub (mimoo-tech)

## Local
Remoto

## Benefícios
* Cultura Officeless
* Contratação PJ (salário à combinar)

## Requisitos
**Esperamos que você seja:**

* Capaz de expressar ideias e soluções complexas para pessoas não-técnicas
* Capaz de propor soluções alternativas, visando sempre a decisão que vai gerar maior resultado para o produto
* Capaz de trabalhar em um ambiente de entrega contínua com automação de testes de unidade / integração
* Flexível em trabalhar remotamente
* Curioso em aprender tecnologias além da web Stack, como spark e programação funcional
* Confortável com um ambiente dinâmico e de extrema incerteza

**O que buscamos:**

* Domínio em desenvolver soluções Web utilizando React (conhecimento em React Native ou Flutter é um diferencial), Angular e/ou Vue
* Experiência com bancos de dados variados (SQL, NoSQL)
* Experiência com Git e algum dos git flow (Git flow, Gitlab flow)
* Experiência em automatizações em geral com task managers e práticas de entrega contínua
* Experiência com CI/CD em algum provedor de nuvem (AWS, Azure, GCP)
* Experiência com cloud architectures baseado em public cloud services
* Confortável em trabalhar com múltiplas linguagens de programação em um ambiente poliglota.

**Aqui você terá espaço para:**

* Desenhar e construir aplicações com tecnologias emergentes (como React, Angular e/ou Vue).
* Implementar estratégias de integração com tecnologias e serviços 3rd party
* Escolher as suas ferramentas e a maneira que você quer trabalhar

## Contratação
* Contratação PJ (salário à combinar)

## Nossa empresa
A [Mimoo](https://www.mimoogratis.com.br/) é uma Start-Up que nasceu para inovar e quebrar paradigmas no relacionamento entre a indústria de bens de consumo e o consumidor final. Hoje a Mimoo é a 1° rede de lojas do Brasil onde tudo é gratuito.

As lojas [Mimoo Grátis](https://www.mimoogratis.com.br/) já estão em operação em 3 (três) zonas de São Paulo: Zona Norte (Shopping Metrô Tucuruvi), Zona Sul (Mais Shopping) e Zona Leste (Shopping Metrô Tatuapé) e as empresas que investem nessa ideia são: BiC, ambev, Unilever, Nestlé, Jeunesse e Eudora.

Conheça mais sobre a Mimoo acessando o [nosso Instagram](https://www.instagram.com/mimoo.gratis/).

### Como se candidatar
Envie um email para [eu@lucaskauer.com](mailto:eu@lucaskauer.com) com o seu perfil do GitHub, link para sua home page ou algum de seus trabalhos publicados. Preferencialmente enviar o CV em código, **show me the code**.

## Labels
* PJ
* Pleno
* Sênior
* Remoto

**Comment by Possilvio** [comment]
Email enviado!
