### ISSUE TITLE
[Goiânia, Goiás] Full-stack developer na Ecxus Tecnologia

### ISSUE THREAD

**Issue by rengav13** [frontendbr/vagas#2597]
## Descrição da vaga

- Criar designs simples e intuitivo para aplicações web e mobile;
- Projetar, desenvolver e implantar soluções integradas;
- Se responsabilizar e gerenciar cada fase do ciclo de vida de desenvolvimento (planejamento, design, implementação, implantação e suporte);
- Projetar, construir e manter infraestruturas de API’s;
- Colaborar efetivamente com os companheiros de equipe e parceiros técnicos;
- Comunicar ideias técnicas e direções para a empresa, focando na solução de problemas.

## Local

Remoto ou Escritório, Goiânia - Goiás.

## Benefícios

- Vale transporte
- Vale alimentação
- Plano de saúde e odontológico
- Flexibilidade por meio de trabalho remoto
- Salário a combinar

## Requisitos

**Obrigatórios:**

- Ser formado em Engenharia de Computação, Ciência da Computação, Engenharia de Software ou similar;
- Ter pelo menos 5 anos de experiência com desenvolvimento full stack com Java ou Node;
- Ser proficiente em HTML5, CSS e frameworks JavaScript, como React, Angular ou Vue;
- Experiência com integração de aplicações internas e soluções de terceiros;
- Ter experiência na construção de APIs;
- Forte conhecimento em estrutura de dados, algoritmos e padrões de projeto;

**Desejáveis:**

- Ter conhecimento em plataformas de computação em nuvem como AWS ou GCP;
- Ter habilidade para trabalhar próximo aos stakeholders, para entender suas necessidades e construir soluções customizadas;
- Demonstrar habilidade para trabalhar em múltiplos times para entregar um produto final.

## Contratação

A critério do desenvolvedor, podendo ser PJ ou CLT.

## Nossa empresa

A Ecxus é uma empresa de tecnologia líder há mais de 25 anos, no desenvolvimento de soluções de automação para hotéis e motéis. A Ecxus investe substancialmente em Pesquisa e Desenvolvimento, criando soluções inovadoras e ditando as tendências do mercado nacional. Estamos expandindo, por isso, buscamos desenvolvedores sênior para integrar nossa equipe de desenvolvimento de software.

## Como se candidatar

Por favor envie um email para rh@ecxus.com.br com seu CV anexado - enviar no assunto: Full-stack developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@ecxus.com.br

**Comment by eduviictor** [comment]
Estou terminando a faculdade mas já atuo em projetos. Vale? Ou apenas superior totalmente completo?

**Comment by rodgomesc** [comment]
Poxa, esses 5 anos de experiência em uma das duas tecnologias mata muitos candidatos
