### ISSUE TITLE
[Remoto] Front-end Developer ReactJS Node.js  na Plastika TWY 

### ISSUE THREAD

**Issue by renann** [frontendbr/vagas#2598]
## Descrição da vaga

Front-end Developer Pleno para integrar time de desenvolvimento de projetos ágeis.
Se você é apaixonado por desenvolvimento (e por JavaScript), se mantém sempre atualizado esta sempre buscando novos desafios, essa vaga é para você.

Na Plastika TWY você poderá participar de projetos dos mais diferentes segmentos. Nosso foco é desenvolver aplicações factíveis, valiosas, usáveis e com aquele "UAU!"

## Local

Remoto

## Requisitos

**Obrigatórios:**
Estamos em busca de um dev PLENO, com os seguintes domínios mínimos:
- ReactJS
- Node.js
- MySQL
- PHP

**Desejáveis:**
- conhecimentos em framework Laravel
- SCRUM

**Diferenciais:**
- Oportunidade de participação dos lucros

## Contratação

PJ a combinar

## Nossa empresa

Ao longo de 13 anos a Plastika TWY lançou diversos projeto digitais para o mais diversos segmentos por todo o mundo. Pudemos ajudar muita gente e hoje vemos muitos dos nossos parceiros crescerem e se tornarem referência em seu segmento. Utilizamos do pensamento ágil e do desenvolvimento enxuto oportunizando que pessoas ou empresas validem sua ideia e construa futuros.

## Como se candidatar

Por favor envie um email para hiring@plastikastudio.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: hiring@plastikastudio.com.br

## Labels

- PJ
- Pleno
- Remoto

**Comment by renann** [comment]
Vaga preenchida através do Frontendbr.

**Comment by felipefialho** [comment]
Muito bom, quem foi a pessoa contratada? 😄
