### ISSUE TITLE
[São Paulo] Front-end Developer na Homeguru

### ISSUE THREAD

**Issue by muriloazevedo** [frontendbr/vagas#2602]
## Descrição da vaga

Somos uma startup que quer facilitar a compra e venda de imóveis, descomplicando a documentação e financiamento. Você pode conferir nosso stack no https://stackshare.io/homeguru/homeguru

## Local

Presencial, São Paulo - Itaim Bibi

## Requisitos

**Obrigatórios:**
- experiência com ReactJS

**Desejáveis:**
- conhecimento em Graphql e Firebase

**Diferenciais:**
- experiência com React Native

## Contratação

PJ a combinar

## Nossa empresa

Somos uma startup com pouco mais de um ano de vida e se inserindo no mercado. Temos um time com grande conhecimento do mercado.

## Como se candidatar

Faça o nosso teste prático fazendo o fork do repositório
https://github.com/homeguru/frontend-test

## Tempo médio de feedbacks

Em até 2 dias damos um feedback do seu PR. 

## Labels
- Júnior
- PJ
- Pleno
- Sênior

**Comment by ale-jr** [comment]
A vaga ainda está aberta? :D
