### ISSUE TITLE
[Home  - São José dos Campos] NodeJS Developer na Climatempo

### ISSUE THREAD

**Issue by oliverthies** [frontendbr/vagas#2605]
Sobre a Vaga
Cargo: Desenvolvedor NodeJS Full-stack com fluência em Microserviços e back-end

Local: Remoto com sede no Parque Tecnológico - São José dos Campos (http://www.pqtec.org.br/).
Quer fazer parte do time de tecnologia da maior empresa privada de meteorologia do Brasil? Aqui é seu lugar. A Climatempo está completando 30 anos e queremos você na nossa equipe para crescer com a gente.

Nosso time é jovem, entrosado, todos sempre dispostos a aprender e ajudar.

Aqui você tem a oportunidade de se relacionar com profissionais de diversas áreas de formação, possibilitando muito aprendizado e crescimento, e participará do desenvolvimento de um dos portais mais acessados da América Latina.

Nossa API atende cerca de 40milhões de requisições por dia, trabalhamos com bancos de dados relacionais e não relacionais além do uso de modelos estatísticos, inteligência artificial e uma infinidade de outras tecnologias.

Nossa missão é transformar ciência em soluções ambientais criando riqueza para a humanidade, você com certeza vai se engajar nessa causa!

Procuramos um desenvolvedor Full-stack com perfil colaborativo e que esteja apto a atuar com as tecnologias abaixo:

NodeJS
PHP 5 & 7
REST
Javascript
MongoDB
Python ( desejável )
Enviar cv ou linkedin para --> fullstack@climatempo.com.br

**Comment by felipefialho** [comment]
Essa vaga é bem focada em back, recomendo o @backend-br
