### ISSUE TITLE
[Guanhães/MG] Web Developer na Eagle Tecnologia

### ISSUE THREAD

**Issue by lauroguedes** [frontendbr/vagas#2609]
## Descrição da vaga

Vaga para Analista de Sistemas com atuação em Desenvolvimento Web. Procuramos profissionais que presam pelo trabalho em equipe, proativos e que tenham mentalidade empreendedora.

## Local

Sede da Eagle Tecnologia em Guanhães, MG

## Benefícios

- Horário Flexível
- Plano de Carreira

## Requisitos

**Obrigatórios:**
- Formação na área de TI;
- Capacidade de aprender rapidamente tecnologias emergentes mediante ao consumo de livros, cursos, documentação técnica, vídeos ou palestras;
- Ter espírito de trabalho em equipe, comprometimento e vontade de pôr a mão na massa;
- Ter trabalhado com Padrões de projeto, Controle de Versão (Git), Banco de dados Relacional (MySql/Postgres), Metodologias Ágeis (Scrum);
- Ter desenvolvido projetos utilizando tecnologias web: HTML5, CSS3, JavaScript ES6, PHP 7;
- Ter desenvolvido projetos utilizando o framework Laravel e VueJs lib ou similar.

**Desejáveis:**
- Conhecimentos em Docker/Kubernetes;
- APIs Rest;
- NodeJS.

**Diferenciais:**
- Arquitetura de Micro-Service;
- TDD (Test-driven Development);
- DDD (Domain-driven Design);

## Contratação

CLT

## Nossa empresa

A [Eagle Tecnologia](https://eagletecnologia.com) é uma empresa que preza pela gestão empresarial de seus clientes, oferecendo sistemas e serviços para apoiar o empresário nesta busca constante. Nós ajudamos inovar a gestão empresarial de nossos clientes.

## Como se candidatar

Acesse nossa pagina [Trabalhe na Eagle](https://eagletecnologia.com/vagas/analista-de-sistemas) e cadastre o seu currículo.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: dev@eagletecnologia.com

## Labels

- Alocado
- CLT
- Pleno

**Comment by FernandaTarallo** [comment]
Aceita remoto?

**Comment by lauroguedes** [comment]
@FernandaTarallo no momento não, essa vaga é para alocado, mas agradeço seu interesse
