### ISSUE TITLE
[Freela Remote] Dev Front-end

### ISSUE THREAD

**Issue by stdiopt** [frontendbr/vagas#261]
## Descrição da vaga

Precisamos de um Desenvolvedor Front-end para passar site para o WordPress e traduções que já estão feitas.

## Local

Remoto.

## Benefícios

- Se fizer um bom trabalho poderá receber mais trabalhos futuramente.

## Requisitos

**Obrigatórios:**
-CSS
-HTML
-PHP
-Wordpress 

**Desejáveis:**
-Experiência com Wordpress

**Diferenciais:**
-Fluente em Inglês

## Contratação

Freela, com pagamento por tela entregue e validada. Valor a combinar.

## Nossa empresa

SBecommerce, sediada em HongKong.

## Como se candidatar

Por favor envie um email para luisf@casemyway.com com seu portfólio - enviar no assunto:  freelancer front.

**Comment by Piulres** [comment]
Enviado :)

**Comment by ribeiroevandro** [comment]
@stdiopt enviado... ;)

**Comment by stdiopt** [comment]
Obrigada a todos pelo contato e envio de currículos/portfólios, recebemos muitos interessados e agora iremos dar seguimento com a seleção. Boa sorte a todos. Um abraço!
