### ISSUE TITLE
[Remoto  ou Sorocaba - SP] Front-End Developer na Bitwise

### ISSUE THREAD

**Issue by mendesbarreto** [frontendbr/vagas#2616]
## Descrição da vaga

Fala pessoal sou o [Douglas](https://github.com/mendesbarreto) atualmente sou o CTO da Bitwise e estou procurando pessoas capazes de produzir conteúdo Front-End para nossos projetos, no momento não procuro por conhecimento em tecnologias especificas como Angular ou React, se você é desenvolvedor é Web e é fera em alguma tecnologia que está sendo utilizada na atualidade mande seu CV.

## Local

Remoto ou Escritório, Sorocaba - Campolim

## Requisitos

**Obrigatórios:**
- Conhecimento em alguma das libs (ReactJS, Angular,  Vue.JS e etc.)
- HTML / CSS
- CSS
- JavaScript
- RESTful services
- SASS
- NPM ou yarn (para gerenciamente de pacotes/bibliotecas javascript)
- Repositórios: GIT (Hub/Lab/Flow);
- Saber criar testes unitários
- Frameworks de interface (ex: bootstrap).

**Desejáveis:**
- Banco de dados (relacional e/ou não relacional)
- TypeScript
- ElasticSearch (como noções de performance);
- Familiaridade com as novas especificações do EcmaScript.
- Desenvolvimento Ágil

**Diferenciais:**
- projetos opensource

## Contratação
- CLT
- PJ

## Nossa empresa

A Bitwise é uma comunidade dedicada e apaixonada por soluções tecnológicas e nosso objetivo é revolucionar o design e a criação de software. 

Nossa missão é ajudar nossos clientes a melhorar suas operações de mercado e desempenho com uma transição suave e rápido retorno do investimento, para alcançar estabilidade a longo prazo. Para isso, trabalhamos duro para capacitar nossas equipes e reforçar uma cultura com valores ágeis.

## Como se candidatar

Por favor envie um email para estevao@bitwise.ltda com seu CV anexado - enviar no assunto: Front End

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

## Labels

- Alocado
- CLT
- Estágio
- Freela
- Júnior
- PJ
- Pleno
- Remoto
- Sênior

**Comment by rodineicosta** [comment]
Enviado.

**Comment by fabianafarias** [comment]
Enviado.

**Comment by JohnPonciano** [comment]
Enviado.

**Comment by italocedrosales** [comment]
function enviar(cv) {
   console.log("Currículo " + cv + " enviado com sucesso!");
}

enviar("ItaloCedro.pdf");

Vleu e Obrigado!

**Comment by kaardeco** [comment]
Enviado!

**Comment by EzequielBrilhante** [comment]
Enviado!
