### ISSUE TITLE
[Remoto] FullStack Developer na Cricketz

### ISSUE THREAD

**Issue by crickettz** [frontendbr/vagas#2622]
## Descrição da vaga

- Desenvolvimento de funcionalidades no Front-End, principalmente com ReactJS;
- Desenvolvimento de funcionalidades no Back-End, utilizando principalmente NodeJS, PostgreSQL e Redis;

## Benefícios

- Plano de saúde
- VA 

#### Diferenciais

- Horário flexível.
- 13 / Férias msm sendo PJ.

## Requisitos

**Obrigatórios:**
Ser proficiente em HTML5, CSS e frameworks JavaScript, como React, Angular ou Vue;
Experiência com integração de aplicações internas e soluções de terceiros;
Ter experiência na construção de APIs;
Forte conhecimento em estrutura de dados, algoritmos e padrões de projeto;

**Desejáveis:**
Ter conhecimento em plataformas de computação em nuvem como AWS ou GCP;
Demonstrar habilidade para trabalhar em múltiplos times para entregar um produto final.
Conhecimento em React-Native é um baita diferencial =D

## Contratação

PJ a combinar possibilidade de CLT em Janeiro

## Nossa empresa
Somos uma fábrica de software fundada em 2012. O seu foco é a produção de aplicativos e sistemas web utilizando a linguagem JavaScript como sua principal ferramenta.você poderá participar de projetos dos mais diferentes segmentos. Nosso foco é desenvolver aplicações factíveis, valiosas

## Como se candidatar

Por favor envie um email para github@criktz.com seu CV anexado - enviar no assunto: Vaga FullStack JS

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

## Labels

- CLT
- PJ
- Pleno
- Remoto
- Sênior

**Comment by eduviictor** [comment]
Enviado :+1:

**Comment by xbrunosousa** [comment]
Não recomendo de maneira alguma... rapaz chamado Lucas entrou em contato comigo já pedindo para iniciar IMEDIATAMENTE, enviou o contrato mas pareceu estupidamente suspeito... minha pretensão salarial era X e ele quase dobrou e ainda ofereceu mais 1000 caso terminasse tal milestone em tal tempo, e, após eu topar, queria feedback a cada 10 minutos...

Fiquei 1h sem responder, pois estava focado no projeto... então me removeram do projeto no BitBucket sem mais explicações e outra funcionária já me bloqueou no LinkedIn.

**Comment by xbrunosousa** [comment]
@felipefialho, é uma "empresa" agindo de má fé... perfis falsos nas redes sociais, usa várias variações do nome da empresa (Cricketz, Criktz)... perfil entrou no Github 9 dias atrás, dominios registrados 9 dias atrás, CNPJ falso (e ainda mei)... alguns devs já vieram me procurar afirmando que estão agindo de má fé.

**Comment by diegohyenna** [comment]
concordo.
uma vez alguem falou no telegram do grupo ionic que era furada, o cara que tava divulgando disse que era so amigo do CEO mas pegou ar.
