### ISSUE TITLE
[Home Office] Front-end Developer na WA Project - React e React Native 

### ISSUE THREAD

**Issue by gustavowaproject** [frontendbr/vagas#2626]
Pessoal, estamos completando um time de 6 devs para um projeto e precisamos contratar devs full stack com foco maior no front-end. 

Descrição da empresa:
Desenvolvemos aplicativos e softwares para empresas. Nossa foco é na entrega.

Atividades e Responsabilidades:
- Desenvolvimento de projetos sob demanda para nossos clientes, utilizando tecnologias web e mobile. Implementação de novas features e manutenção.
- Compartilhar conhecimento e estar disposto a ajudar o time.

Requisitos:
- Experiência com as tecnologias: NodeJs, React, React Native, Typescript, Docker, HTML, CSS, Rest, NPM/Yarn, banco de dados SQL e GIT.

Metodologias utilizadas: 
Scrum e KanBan.

Diferenciais: 
- MongoDB, RxJs e Testes.
- Capacidade analítica para resolução de problemas.
- Comprometimento e ótima comunicação.

Para se candidatar, envie seu currículo para vagas@waproject.com.br

**Comment by romimaximus** [comment]
Se ainda estiver precisando estou disponível

**Comment by romimaximus** [comment]
Ok não entendi bem sua mensagem..só recebi esse link para um repo no Github..?

[cid:93561254-7386-4b9b-ba83-b069cc109532]


________________________________
