### ISSUE TITLE
[São Paulo] Front-end Developer na Trestto

### ISSUE THREAD

**Issue by ale-jr** [frontendbr/vagas#2627]
## Descrição da vaga
Estamos desenvolvendo novos produtos além de um novo CRM para nossos clientes, tudo isso usando React <3 procuramos alguém que esteja começando  para nos auxiliar em nosso time de frontend
## Local
Rua Haddock Lobo, na esquina com a Avenida Paulista

#### Diferenciais

- Sala de descompressão
- Horário flexível
- Ambiente descontraído

## Requisitos

**Obrigatórios:**
- Saber entender problemas e pensar em soluções simples
- Noções de CSS, HTML
- Ter um nível legal em JS

**Desejáveis:**
- Conhecer algum framework
- Saber nodejs

## Contratação

CLT

## Nossa empresa
Somos uma startup especialista em agentes digitais

## Como se candidatar

Por favor envie um email para alexandre.fernandes@trestto.com.br com seu CV anexado - enviar no assunto: Vaga Frontend JR

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até  3 dias após cada processo.
E-mail para contato em caso de não haver resposta: alexandre.fernandes@trestto.com.br

## Labels

- CLT
- Padawan
- Júnior

**Comment by FernandaTarallo** [comment]
Aceitam remoto?

**Comment by ale-jr** [comment]
Infelizmente não :/

Em qua, 6 de nov de 2019 15:35, FernandaTarallo <notifications@github.com>
escreveu:

**Comment by pedrorufino** [comment]
CV enviado 😊

**Comment by caabeatriz** [comment]
Enviado :smile:

**Comment by GustavoPrizon** [comment]
Cv enviado!

**Comment by ale-jr** [comment]
Pessoal que mandou CV para o email: vocês enviaram para o email selecao@trestto.com.br? Se sim, receberam feedbacks?
