### ISSUE TITLE
[São Paulo] Pessoa Desenvolvedora Front-end na StartSe

### ISSUE THREAD

**Issue by ederchristian** [frontendbr/vagas#2631]
## Descrição da vaga

Criação de landing pages de eventos offline, cursos offline e online e programas internacionais (Vale do Silício, China, Israel, Índia e Portugal) da StartSe.

## Local

Rua Capitão Antonio Rosa, 409 - Pinheiros - São Paulo/SP

Coworking Spaces (Próximo ao metrô Fradique Coutinho - Linha Amarela do Metrô)

## Benefícios

- Plano de saúde
- VR
- VT
- PLR a cada 6 meses (25% do lucro de cada mês é separado e dividido entre todos nesse período, de acordo com a performance de cada pessoa)

#### Diferenciais

- Horários flexíveis (de verdade)
- Negociável trabalhar remotamente em alguns dias da semana
- Monte a sua máquina como desejar
- Possibilidade de ida a eventos de tecnologia da empresa 
- Sala de jogos
- Ambiente muito descontraído

## Requisitos

**Obrigatórios:**
- Conhecimento de HTML, CSS e JavaScript
- Experiência com Bootstrap 4
- Boas práticas de desenvolvimento
- SEO e semântica (essenciais)
- Git
- Facilidade para trabalhar em equipe e boa comunicação

**Desejáveis:**
- Conhecimento de PHP
- Conhecimento de Docker

## Contratação

CLT a combinar

## Sobre a empresa

A StartSe é uma jovem empresa que acredita que somente a inovação e o empreendedorismo são capazes de transformar o país. Queremos ser o melhor integrador e o maior agente econômico do ecossistema brasileiro de startups.

Basicamente, a StartSe:

- tem um portal de notícias (em melhoria) sobre empreendedorismo e inovação
- promove conhecimento sobre as mudanças e inovações que estão acontecendo nos mais diversos mercados ao redor do mundo. São cursos online e offline, eventos e imersões. Alguns desses programas acontecem fora do Brasil, em polos de tecnologia, como o Vale do Silício, China, Israel, Índia e Portugal
- conecta, através de plataforma e um app, mais de 12 mil startups inscritas e quase 100 mil usuários

## Como se candidatar

Por favor, envie um email para eder@startse.com com seu CV anexado **ou** links de projetos que já fez com uma breve descrição sobre você. Enviar no assunto: Vaga Front-end Developer.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.

## Labels

- Alocado
- CLT
- Júnior
- Pleno

**Comment by caabeatriz** [comment]
:smile: :heavy_check_mark:

**Comment by ederchristian** [comment]
Vaga preenchida por uma pessoa que veio daqui. 💚
