### ISSUE TITLE
[REMOTO] Front-end Developer na Pythonic Café

### ISSUE THREAD

**Issue by turicas** [frontendbr/vagas#2635]
##  Descrição da vaga

Estamos buscando mulheres desenvolvedoras frontend com experiência para trabalhar remotamente em projetos de dados (alguns sobre gênero), full ou part-time. Ainda não foram definidas tecnologias de front-end (apenas de back-end: Python+Django e Wordpress).

- *Não* é necessária formação acadêmica;
- Boa parte do trabalho é *assíncrona*, com horários flexíveis (mães são bem-vindas!);
- Pessoas de todas as idades são bem-vindas (isso é básico, mas melhor explicitar);
- Inicialmente são 2 vagas: 1 FE/UX/Dataviz e 1 FE/UX/Wordpress;

## Local

Remoto.

## Benefícios

Dependem da quantidade de horas/forma de contratação.

#### Diferenciais

- Horários flexíveis

## Requisitos

**Obrigatórios:**
- Git e GitHub

**Desejáveis:**
- UX
- Wordpress
- Visualização de dados
- Colaboração com software livre
- Experiência com trabalho remoto

## Contratação

A combinar (dependendo da quantidade de horas).

## Nossa empresa

A Pythonic Café existe desde 2017 e empodera pessoas através do acesso à tecnologia; oferecemos cursos de programação para áreas, analisamos dados públicos brasileiros e desenvolvemos sistemas de apoio ao jornalismo.

## Como se candidatar

Por favor envie um email para turicas@pythonic.cafe com seu currículo, portfolio e pretensão salarial.

## Labels

- CLT
- Freela
- PJ
- Pleno
- Remoto
- Sênior

**Comment by raloliver** [comment]
Enviado!

**Comment by fsenaweb** [comment]
A vaga não é somente para mulheres ? Agora eu fiquei sem entender...

**Comment by turicas** [comment]
@fsenaweb sim, como está na descrição.

**Comment by FabianoLothor** [comment]
Daora, parabéns pela iniciativa!

**Comment by fsenaweb** [comment]
Ótimo @turicas! É que tinha vista uma pessoa postando que tinha mandado portfólio. 

E parabéns pela iniciativa! As empresas precisam abrir mais espaço para as mulheres. Pois elas são, sem dúvidas, muito mais caprichosas que os homens e nos códigos não seria diferente.. tem o meu apoio!
