### ISSUE TITLE
[Curitiba - PR] Desenvolvedor Mobile em AutomTech 

### ISSUE THREAD

**Issue by AutomTech** [frontendbr/vagas#2639]
Requisitos:
•	Formação em análise e desenvolvimento de sistemas ou afins; 
•	 Mobile Híbrido (Android e IOS); 
• JavaScript, React, Ionic; 
• API's RESTful. 
Diferenciais: experiência em Flutter e React Native. Conhecimento básico em TFS. Noções em UX. 

Atividades:
•	Desenvolver e dar manutenção em aplicativos híbridos usando Frameworks React, Ionic; 
•	Desenvolver e dar manutenção em sistemas: Angular com back-end NodeJs.

Enviar CV para trabalheconosco@automtech.com.br com a pretensão salarial para **PJ**.

![DEV MOBILE](https://user-images.githubusercontent.com/57018306/68610607-e57cfa80-0496-11ea-89de-b81e6c1a908e.png)

**Comment by felipefialho** [comment]
@AutomTech Por favor, poste a vaga em formato de texto, usar uma imagem com a descrição é completamente inacessível para algumas pessoas.

**Comment by AutomTech** [comment]
Agradeço pelo update, @felipefialho
