### ISSUE TITLE
[São Paulo] Desenvolvedor Front-end UX

### ISSUE THREAD

**Issue by thiagodiaz7** [frontendbr/vagas#264]
## O que esperamos?

- HTML
- CSS
- Javascript
- Conhecimento em Pré-processadores de CSS
- Grunt
- Código eficiente, escalável, reutilizável com foco em acessibilidade (B.E.M. CSS)
- Experiência em sites responsivos/grids, Bootstrap.
- Experiência em bibliotecas/frameworks Javascript (jQuery, AngularJS etc.)
- Pacote Adobe (Web)
- Noções de design UX/UI para sistemas web internos e externos
- Design de Interfaces (Photoshop, Illustrator, Design Mobile)

## O que desejamos?

- Conhecimento de SEO OnPage
- Inglês
- Conhecimento em CMS populares (Drupal, Wordpress)
- Performance 
- Conhecimento de Testes A/B

Buscamos profissionais com ambições de inovar e melhorar ainda mais os resultados da empresa através do front-end. O foco da vaga é no front-end, entretando, o candidato deve ter conhecimento de criação e desenvolvimento, independente de plataformas.

## Sobre a empresa

Empresa especializada no mercado de educação de trânsito e oferece aos CFCs – Centro de Formação de Condutores, cursos no sistema de educação a distância e presencial, para facilitar o processo de obtenção, atualização da renovação e reciclagem da Carteira Nacional de Habilitação.

## Local
Próximo a estação São Judas do metrô.

> Salário compátivel com o mercado
> Ambiente de trabalho familiar
> Horário das 9h às 18h
> Vale refeição
> Seguro de vida
> Vale transporte
> Convênio Médico
> Convênio Odontológico

## Como se candidatar

Por favor envie um email para talves@procondutor.com.br com seu CV anexado - enviar no assunto: Vaga Front-end.

**Comment by LFeh** [comment]
Opa, quais as labels?

**Comment by thiagodiaz7** [comment]
[Alocado] [CLT] [Pleno]
