### ISSUE TITLE
[Remoto] Front-end Developer na Gallica - ReactJS e ReactNative

### ISSUE THREAD

**Issue by marciowinicius** [frontendbr/vagas#2640]
**Descrição da vaga**
O profissional irá trabalhar diretamente na reformulação de um produto baseado em um que já temos pronto e está no mercado (Estamos chamando de v2). Basicamente é uma plataforma de gerenciamento de investimentos.

Com quem você irá trabalhar:
Irá fazer parte de uma equipe multidisciplinar, que dominam várias tecnologias e também gostam de bastantes desafios.

Em geral, os times aqui têm uma pessoa tech leader, que orienta e mentora as demais pessoas em questões técnicas; uma pessoa team leader, que é responsável por acompanhar entregas e direcionar o desenvolvimento de carreira das pessoas; e um(a) PM, que passa as demandas para desenvolvimento conforme a estratégia macro dos produtos. Todas essas pessoas têm background técnico!

Além disso, utilizamos métodos ágeis como Scrum, Kanban e XP. Somos adeptos a TDD (test-driven development).

**Local**
- Remoto (Trabalhe de onde quiser)

**Requisitos:**

- Ter conhecimento de JavaScript;
- Ser comprometido em entregar projetos com qualidade;
- Redux;
- React-router;
- Server Side Rendering;
- Programação funcional;
- Testes;

**Desejáveis:**

Ter experiência com práticas ágeis, AWS, Microservice e TypeScript.

**Contratação**
PJ a combinar

**Como se candidatar**
Email para vagas@gallica.io incluindo pretensão salarial e currículo com o assunto "Desenvolvedor ReactJS e ReactNative"

**Comment by tiagocharo** [comment]
@marciowinicius Enviado!

**Comment by vimaciel** [comment]
@marciowinicius Enviado =)
