### ISSUE TITLE
[Belo Horizonte] Front-end Developer na Labcred

### ISSUE THREAD

**Issue by Labcred** [frontendbr/vagas#2642]
[Belo Horizonte] Front-end Developer na Labcred

## Descrição da vaga

Desenvolvimento e manutenção em sistemas internos de workflow e vendas, baseados em PHP e MySQL, integrado com SOAP e REST.

## Local

Escritório, Belo Horizonte - Minas Gerais

## Benefícios

    • Salário a combinar
    • Vale Transporte
    • Vale Refeição
    • Lanche a vontade 
    • Convênio com assistência medica
    • Convênio com o clube de lazer sesc
    • Seguro de Vida
    • Convênio com instituições
    • Parcerias em restaurantes
  
#### Diferenciais

  • Ambiente inovador, com política de portas abertas 
    • Aprendizado intenso, constante e desafiador
    • Oportunidade real de crescimento. 
    • No-dress code

## Requisitos

    • Experiência em desenvolvimento Web PHP POO.
    • Conhecimento de:
        ◦ Banco de dados (MySql).
        ◦ Controle de versão (GIT).
        ◦ Javascript, ajax, HTML.
    • Curso superior completo.

**Diferenciais:**
    • Prática com Linux.
    • Conhecimento do Framework Laravel
    • Conhecimento de WordPress

## Contratação
CLT 

## Nossa empresa

Somos fruto de 10 anos de atuação no setor de vendas remotas em grande escala no Brasil. São 10 anos de experiência em mercados complexos, onde já atendemos mais de 13 milhões de clientes brasileiros em nossos sites, portais e time de televendas!

## Como se candidatar

Interessados gentileza enviar currículo para o e-mail curriculos@labcred.com e colocar no assunto o nome da vaga. 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após cada processo.

## Labels

- CLT
- Pleno

**Comment by felipefialho** [comment]
Essa vaga é no mínimo Full-stack, quase Back-end 🤔

**Comment by joaopedrodev** [comment]
Olá queria saber se existe alguma para desenvolvedor Laravel PHP, também trabalho como desenvolvedor FullStack obrigado deixo meu numero do whatsapp 61999955207.
