### ISSUE TITLE
[Recife-PE] Estágio Desenvolvimento de Software na Incorp Technology

### ISSUE THREAD

**Issue by flavioafa** [frontendbr/vagas#2644]
## Descrição da vaga

Estamos precisando de estagiários para nos auxiliar no desenvolvimento de sistemas. Hoje possuímos uma vaga para front-end e uma para back-end.

## Local

Escritório, Recife - Torreão

## Benefícios

- Bolsa auxílio: R$ 1.328,70
- Tíquete-alimentação: R$ 550,00
- Vale-transporte
- Seguro de vida

#### Diferenciais

- Ambiente que proporciona o aprendizado continuo

## Requisitos

**Obrigatórios:**
- Deverá estar cursando: Ensino Superior em Engenharia da Computação, Ciência da Computação, Sistemas de Informação ou correlatos, a partir do 3º período.
- Necessitamos que você tenha conhecimentos em PHP, Noções de banco de dados, JavaScript.

**Diferenciais:**
- Será um diferencial se você conhecer Laravel e Vue.js
- Demonstração de projetos no github

## Contratação

Regime de estágio

## Nossa empresa

Somos referência em sistemas pra conselhos regionais e temos clientes em todo o Brasil.

## Como se candidatar

Por favor envie um email para flavio@incorptech.com.br com seu CV anexado - enviar no assunto: Estágio Desenvolvimento de Software.
Não esqueça de enviar o linkedin e github

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 30 dias após cada processo.
E-mail para contato em caso de não haver resposta: flavio@incorptech.com.br

## Labels

- Estágio
- Presencial

**Comment by SEdilson** [comment]
Essa vaga ainda tá recebendo candidaturas?
