### ISSUE TITLE
[São Paulo] Desenvolvedor Front-End Júnior (web designer)

### ISSUE THREAD

**Issue by jaqueventurim** [frontendbr/vagas#265]
## Descrição da vaga

Estamos buscando uma(um) desenvolvedora(desenvolvedor) para trabalhar em um ambiente informal desenvolvendo aplicações em HTML/CSS/JavaScript, participando desde a concepção da ideia até a entrega final e manutenção.

## Local

Oxigênio Aceleradora | Remoto

## Benefícios

Trabalhar remoto
R$ 1.500. R$ 800 de ajuda de custo experiência 30 dias.
Aprendizado rápido
Ótimo ambiente de trabalho
Contato direto com o CEO da empresa
Ambiente e formato de trabalho: Startup
Será estimulado constantemente a aprender novas tecnologias, sair da zona de conforto, necessário gostar de concluir desafios.

## Requisitos

**Obrigatórios:**
- HTML/CSS/JavaScript
- Design gráfico
- WordPress
- Illustrator e Photoshop (ou uma ferramenta semelhante)

**Diferenciais:**
- Noções de marketing
- Conhecimento sobre empreendedorismo e startups
- Lean Startup

## Contratação

A combinar

## Nossa empresa

KickSIM - startup de roaming celular grátis. Nós encaminhamos as suas ligações para o número internacional sem o custo de roaming.
Nossa sede é no Vale do Silício e a equipe do Brasil trabalha remotamente.

## Como se candidatar

Entre nesse link (http://www.kicksim.com.br/jobs/) e faça o cadastro :)

**Comment by leonantvrs** [comment]
Cadastro enviado

**Comment by HaluDeCassia** [comment]
Essa vaga é ótima para o meu perfil, me cadastrei 😊

**Comment by freeboxd** [comment]
Me candidatei!
