### ISSUE TITLE
[Irlanda/Dublin] React Developer com possibilidade de sponsor

### ISSUE THREAD

**Issue by rxluz** [frontendbr/vagas#2665]
## Descrição da vaga
Trabalhar com React/Redux/Typescript

## Local
Inicialmente remoto com possibilidade de sponsor

## Benefícios
- Prêmios todos os meses de acordo com a performance
- Trabalhar presencial o nosso escritório em Dublin de uma semana a 10 dias por ano

## Requisitos

**Obrigatórios:**
- 6 meses de experiência com React e Redux
- 6 meses de experiencia com Javascript
- 6 meses de experiencia com Typescript
- Experiencia com ferramentas de testes como Jest e Cypress

**Desejáveis:**
- Conhecimentos em React Native
- Conhecimentos em AWS
- Algum projeto desenvolvido com Node e Express

**Diferenciais:**
- Projetos open-source
- Textos escritos no Medium/Blog/Dev.to
- Palestras
- Profile (e conteudo) no Github/NPM

## Contratação
PJ a combinar

## Nossa empresa
Loylap.com

## Como se candidatar
Por favor envie um email para ricardo@loylap.com com seu CV/Linkedin/GitHub - enviar no assunto: Vaga React/Redux/Typescript

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 14 dias após cada processo.
E-mail para contato em caso de não haver resposta: ricardo@loylap.com

## Labels
- Internacional
- Junior
- Pleno
- Remoto
- Sênior

**Comment by JIFerreira** [comment]
Olá, qual nível de inglês?

**Comment by kivervinicius** [comment]
Inglês fluente?

**Comment by rxluz** [comment]
O ingles pode ser so para escrita e leitura, a equipe tem bastante BR entao nao e um problema.

**Comment by Qnedy** [comment]
2+ anos de XP. Pq tem Jr ali? hm...

**Comment by juniorfernandesdev** [comment]
2+ anos de XP. Pq tem Jr ali? hm...

**Comment by nandomoreirame** [comment]
Caraca que jr foda hein, também quero.

**Comment by rxluz** [comment]
Opa galera beleza? Acabei copiando a spec da ultima vaga que era pra pleno/senior e esqueci de alterar a experiencia minima, ja esta corrigido

**Comment by kivervinicius** [comment]
@rxluz mandei e-mail faz mais de 20 dias e não tive resposta.

**Comment by rxluz** [comment]
Opa galera, desculpa a demora, acabamos de fechar a vaga, queria agradecer todo mundo que participou do processo, talvez esse artigo aqui ajude quem estiver na busca de trabalho (foi escrito por uma pessoa que participou do nosso processo): https://dev.to/ypedroo/what-i-ve-learned-from-blowing-my-first-remote-interview-4klg
