### ISSUE TITLE
[Belo Horizonte] WordPress Developer na Rock Content (Rock Stage)

### ISSUE THREAD

**Issue by adrianoresende** [frontendbr/vagas#2668]
# Sobre o Rock Stage

Rock Stage é uma plataforma de Hosting para WordPress. Com apenas um ano de vida, a plataforma já possui mais de 3 mil sites e lida com milhões de requisições todos os dias. 

Com uma infraestrutura orientada a micro-serviços conseguimos escalar horizontalmente para adequar às necessidades dos clientes e do mercado.

A infraestrutura dos sites é construída em cima do Kubernetes que orquestra tudo em relação ao Hosting. A plataforma é feita em Node JS, Typescript, Next JS e React JS.

## Você será responsável por:

- Atuar no desenvolvimento, produção, modificação, teste, manutenção e implementação de ativos da Web corporativos e interfaces de usuário de aplicativos da web;
- Desenvolver de plug-ins e novas features;
- Desenvolver temas, landing pages e outros tipos de ferramentas;
- Desenvolver métodos automatizados de entrega e garantia de qualidade;
- Manter a busca contínua por inovação.

## Local

Presencial na Rock Content, bairro Funcionários em Belo Horizonte

## Benefícios

- Regime de contratação CLT (40 horas semanais).
- Vale­ refeição ou alimentação
- Plano de Saúde
- Plano Odontológico
- Vale transporte
- Vale cultura

### Além disso...

- No dress code (pode trabalhar de bermuda, camiseta, chinelo, etc, afinal o que importa é seu resultado!)
- Oportunidade de trabalhar diretamente com grandes nomes do mercado de marketing digital
- Treinamentos semanais na Escola da Rock para aprendizagem e ensino constantes (afinal nossos valores são praticados no dia-a-dia, não estão só no papel!)
- Acesso a todos os cursos e certificações da Universidade Rock Content.
- Poder pegar o livro que quiser em nossa Biblioteca da Rock ou pedir para comprar se não tivermos
- Flexibilidade de horário
- Lanche para nossos Rockers <3
- Happy hour (o famoso Office Gela) de sexta-feira

## Requisitos

- Curso superior completo em Ciência da Informação, Engenharia de Software e/ou afins;
- Sólida experiência trabalhando com desenvolvimento de temas e plugins para WordPress;
- Conhecimento avançado de WordPress, PHP, MySQL, CSS, HTML e jQuery;
- Familiaridade com os princípios de programação orientada a objetos e as APIs fundamentais do WordPress;
- Especialista no desenvolvimento de padrões do WordPress, criação de plugins e temas personalizados;
- Experiência integrando plugins e temas com serviços externos utilizando a API JSON do WordPress;
- Experiência com desenvolvimento avançado de temas utilizando Advanced Custom Fields, Custom post types e as APIs nativas do WordPress sem a necessidade de plugins;
- Ter trabalhado com Git e SVN;

**Diferenciais:**

- Experiência com testes utilizando phpunit;
- Conhecimento em Cloud (AWS, Docker, Travis);
- Ter temas e plugins publicados no WordPress.org;
- Experiência com integração continua (CI/CD) para plugins e temas WordPress;

## Contratação

A combinar

## Nossa empresa

Rock Stage é uma plataforma de Hosting para WordPress. Com apenas um ano de vida, a plataforma já possui mais de 3 mil sites e lida com milhões de requisições todos os dias. 

Com uma infraestrutura orientada a micro-serviços conseguimos escalar horizontalmente para adequar às necessidades dos clientes e do mercado.

A infraestrutura dos sites é construída em cima do Kubernetes que orquestra tudo em relação ao Hosting. A plataforma é feita em Node JS, Typescript, Next JS e React JS.

## Como se candidatar

stage@rockcontent.com

## Label

- Presencial
- Full-time

**Comment by VitorHugo1** [comment]
Boa noite,
Não consegui entrar no link.

**Comment by adrianoresende** [comment]
@VitorHugo1 Manda seu currículo pelo email por favor? ;) 
stage@rockcontent.com

**Comment by VitorHugo1** [comment]
CURRÍCULUM VITAE - VITOR

Prezado(a),

Sou aluno do 3° período da faculdade COTEMIG.
Segue currículo para apreciação e espero poder fazer parte desta equipe.

Desde já agradeço.
Atenciosamente,
VITOR


Em seg, 3 de fev de 2020 09:11, Adriano Resende <notifications@github.com>
escreveu:

**Comment by VitorHugo1** [comment]
@adrianoresende  Mandei o currículo no email.
