### ISSUE TITLE
[São Paulo] Front-end Developer na Sim;Paul

### ISSUE THREAD

**Issue by jpcritis** [frontendbr/vagas#2671]
## Descrição da vaga

Saudações comunidade! O time de Design da sim;paul tem algumas oportunidades. Estamos recrutando Front-end Developers com bastante experiência em Angular. Está afim? Você será um membro crucial da equipe ao desenvolver produtos financeiros complexos de maneira simples, confiável, transparente e relevante.

## Local

São Paulo - Vila Olímpia

## Benefícios

- Plano de saúde
- VT
- VR de R$ 35,00/dia
- Desconto nos cursos da Fiap (Incluindo dependentes)

#### Diferenciais

- Politica de Home-Office
- frigobar sempre cheio :P
- Frutas e Snacks

## Requisitos

**Obrigatórios:**

- HTML5 + CSS3 + JS ECMAScript 6
- Dominar Pré-Processadores CSS (LESS, SAAS, Stylus)
- Framework: (Angular +2, React ou Vue)
- Bibliotecas: (Bootstrap, Material)
- Metodologia Ágil (Scrum)
- Executar Teste Unitário com (Jasmine, Jest)
- API REST e RESTFULL  
- Configurar Webpack, Gulp, Grunt
- Experiência com sistemas de versionamento (GIT, SVN, Mercurial)
- RXJS
- Programação Funcional
- PWA
- SPA

**Desejáveis:**

- Pré Processador HTML (PUG, HAML, Markdown, Slim, Jade, CofeeKup)
- TypeScript
Flutter
Redux (NGRX)
JIRA
SEO
Node Express
AWS
JsonP
Bibliotecas de Gráficos
Karma

**Diferenciais:**
-Experiência em projetos Financeiros
- Visualização de Dados / Dasboards

## Contratação

CLT

## Nossa empresa

Somos uma Fintech que leva transparência a um mercado acostumado a esconder o jogo. Simples assim. sim;paul

O time de Design hoje está com 10 membros sendo 5 UX/UI Designers e 5 Front-End. Precisamos de reforço para construir um produto financeiro robusto. Vem trabalhar com a gente! 

## Como se candidatar

Por favor envie um email para joao.critis@simpaul.com.br com seu CV e pretensão - enviar no assunto: Vaga Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após cada processo.
E-mail para contato em caso de não haver resposta: joao.critis@simpaul.com.br

## Labels

- CLT
- Sênior

**Comment by hallss93** [comment]
Essa vaga é somente presencial né
