### ISSUE TITLE
[Remoto] Front-end React Developer na Joyjet

### ISSUE THREAD

**Issue by PachecoRaphael** [frontendbr/vagas#2674]
##  Descrição da vaga

Hello, 

Joyjet is looking for a Front-end developer in React for one of our new project comming next year! It´s a project for an association but you may also help on other projects we have as all our Projects are on React. We have a lot of different projects from e-commerce to interns app for businesses.

If you know also Vue JS it´s good as this project has a part coded in Vue. But the principal is in React. 

Big part of the team speaks Portuguese but we all communicate in English via messages. Only the calls with the team are in Portuguese.

If you are interested please do this test and send us the repo URL so we can check: https://bitbucket.org/lixao/tech-interview/src/master/frontend/

## Local

Remoto

## Benefícios

- Plano de saúde
- Free course to study

## Requisitos

**Obrigatórios:**
- 3 years of experience as a front-end developer
- Java script
- Type script
- React
- HTML/CSS
- GIT

**Desejáveis:**
- Knowledge in Vue js
- Knowledge in Python (Framework: Django)

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para job@joyjet.com com seu CV anexado - enviar no assunto: VAGA FRONT-END React/vuejs

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

Test asked to all new members: https://bitbucket.org/lixao/tech-interview/src/master/frontend/

## Labels

- PJ
- Pleno
- Remoto
- React
- Type script

**Comment by rickrd** [comment]
Hi, i've tried to send to job@joyjet.com but it says the email doesn't exists.
