### ISSUE TITLE
[Remoto] Front-end VueJS Developer na Joyjet 

### ISSUE THREAD

**Issue by PachecoRaphael** [frontendbr/vagas#2677]
##  Descrição da vaga

Hello, 

Joyjet is looking for a Front-end developer in Vue JS for one of our new projects coming next year! It´s a project for an association but you may also help on other projects we have. We have a lot of different projects from e-commerce to interns app for businesses.

If you know also React it´s good as main of our projects are in React.

A big part of the team speaks Portuguese but we all communicate in English via messages. Only the calls with the team are in Portuguese.

If you are interested please do this test and send us the repo URL so we can check: https://bitbucket.org/lixao/tech-interview/src/master/frontend/

## Local

Remoto

## Benefícios

- Plano de saúde
- Free course to study

## Requisitos

**Obrigatórios:**
- 3 years of experience as a front-end developer
- Java script
- Vue JS
- HTML/CSS
- GIT

**Desejáveis:**
- Knowledge in React
- Knowledge in Python (Framework: Django)

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para jobs@joyjet.com com seu CV anexado - enviar no assunto: VAGA FRONT-END VueJS

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

Test asked to all new members: https://bitbucket.org/lixao/tech-interview/src/master/frontend/

## Labels

- PJ
- Pleno
- Remoto
- VueJs

**Comment by hallss93** [comment]
e-mail não dá certo.

**Comment by Leokuma** [comment]
The description says the job is to work with Vue, but the test is in React. I believe there's something wrong.

**Comment by fafa1** [comment]
@Leokuma Eles não mudaram, mas é pra fazer em Vue.js mesmo. Tem outra oportunidade deles que é pra ser feita com React.js.

**Comment by EzequielBrilhante** [comment]
O e-mail está dando como errado.

Em seg, 25 de nov de 2019 17:27, PachecoRaphael <notifications@github.com>
escreveu:

**Comment by PachecoRaphael** [comment]
Hey all, sorry I changed the email with the correct one! 

Yes for the front test, you can just do it in Vuejs and not in React :)
