### ISSUE TITLE
[Porto Alegre - RS] Desenvolvedor(a) Front-end [Triider]

### ISSUE THREAD

**Issue by gregslag** [frontendbr/vagas#2682]
# Sobre nós
O Triider é uma plataforma de serviços. É o app que te conecta aos melhores profissionais do mercado com a mesma praticidade de chamar um carro pelo celular. Nascemos de uma dificuldade que muitas pessoas enfrentam quando precisam contratar profissionais para serviços de manutenção como eletricistas, hidráulicos, pintores, diaristas e outros. Completamos 3 anos de operação em Porto Alegre e iniciamos a nossa expansão nacional em 2019. Já chegamos em Curitiba (PR), Belo Horizonte (MG) e Brasília (DF) e, nos próximos meses, iremos para São Paulo (SP). 
 
Procuramos desenvolvedor(a) que queira trabalhar em um ambiente inovador e diferenciado.
 
Somos apaixonados por usar os melhores métodos e ferramentas para construir os nossos produtos e trazer uma experiência fantástica para os nossos usuários.
 
# Responsabilidades
- Pensar constantemente em novas ideias e não ter medo de errar;
- Desenvolvimento de Landing Pages, Hotsites, Site e Sistemas, atuando no front-end, em integrações com o back-end e API's;
- Identificar e propor melhorias para os sistemas atuais para aumento de produtividade, escalabilidade, estabilidade e/ou controle;

# Requisitos
- Javascript, PHP5, HTML e CSS3, AngularJS, React.js;
- Integração e consumo de API’s REST;
- Conhecimento de API REST;
- Conhecimentos de computação em nuvem e distribuída;
- Conhecimentos de controle de versões (GIT);
- Conhecimento de metodologias ágeis;
- Esteja alinhado com as melhores práticas de desenvolvimento.
 
# Desejável
- Práticas de Devops para implementar rotinas de CI/CD;
- Conhecimento de desenvolvimento de aplicativos móveis;

# Como se candidatar
Mande seu currículo para para mecontrata@triider.com

**Comment by jorginhodev** [comment]
Boa tarde
A vaga ainda está aberta?
