### ISSUE TITLE
[REMOTO] Front-end Developer na UBIMINDS

### ISSUE THREAD

**Issue by Ubiminds** [frontendbr/vagas#2684]
**Oportunidade para trabalhar remoto para uma empresa americana do ramo SaaS / Educação. Todo o trabalho será realizado em inglês.** 

## About the job

We're looking for a Mobile Software Engineer to join our stellar team. What you´ll do:

- Help us build our native Android and iOS apps that millions of students, parents, and educators use every day. We have one mobile team that owns both apps, so you’ll regularly work on both platforms.

- Use a combination of native and web technologies to help us continue improving our apps.

- Release new versions of our app often. We practice continuous integration and continuous delivery. We release updates to our server platform nearly every day, sometimes multiple times a day.

- Troubleshoot problems our users have. When something goes wrong you’ll help find out what caused it, decide how to fix it, and get things back up and running quickly.

- Work on a cross-functional team to help decide how to prioritize our work, how to build the solutions, and to see how they’re behaving in the real world. We collaborate and don’t “throw specs over the wall”. We want to hear your ideas!

## Where?

Our positions are 100% remote, working from Brazil with teams mainly based in the United States.

## Requirements

In order to succeed in this position, you will need:

**Mandatory:**
- Advanced/Fluent English skills;

- Experience building native mobile apps for iOS and Android with at least two of the following technologies: Swift, Objective-C, Kotlin, and/or Java;

- Strong experience with automated tests;

- Be familiar with multithreaded code and tools for managing it;

- Understand lifecycle management and the way native mobile apps work;

- Be able to write clean code in both object-oriented and functional styles;

**We also apreciate:**
- Knowledge about architectural patterns used for mobile apps;

- Knowledge of REST and APIs in general;

- Knowledge of hybrid mobile technologies is a plus.

## Hire

PJ or CLT

## Our Business

Remote teams, near collaboration. Ubiminds matches American companies and Brazilian software engineers. Check out our blog for more: http://blog.ubiminds.com/pt/emprego-dev/

## How to Apply

**Here: https://ubiminds.com/software-engineer/**

## Labels

- PJ
- CLT
- Remoto
-Pleno
- Sênior

**Comment by joaoeudes7** [comment]
Link to apply os off

**Comment by Ubiminds** [comment]
fixed it.
