### ISSUE TITLE
[São Paulo] Junior Front-end Developer na AMARO

### ISSUE THREAD

**Issue by vithoriaamaro** [frontendbr/vagas#2687]
## Descrição da vaga

AMARO está buscando um Front end web developer jr para apoiar nossa equipe de marketing e design gráfico. 

## Local

São Paulo - Av. Paulista

## Benefícios

VR, VA and VT
Plano de saúde
Gympass 
Desconto em produtos AMARO

#### Diferenciais

Happy hour 
Frutas todo dia no escritório \o/

## Qualificações

Sólidos conhecimentos em HTML e CSS
Conhecimento em JavaScript (ES2015+);
Familiaridade com API REST and React 
Bug fixing skills, executar testes.

## Como se aplicar 

Para se aplicar favor enfiar e-mail para vithoria.duarte@amaro.com com o assunto:  Jr Front End 

## Labels

- CLT
- Júnior

**Comment by odntht** [comment]
Alocado? Remoto?

**Comment by vithoriaamaro** [comment]
Alocado

**Comment by GustavoPrizon** [comment]
Cv enviado!

**Comment by MellonFive** [comment]
CV enviado

**Comment by Qnedy** [comment]
Normalmente demora pra ter feedback? Enviei o CV tem 1 semana.

Obg.
