### ISSUE TITLE
[SÃO PAULO] Senior Front-End Developer no banco digital Cora - NOVA Startup Fintech

### ISSUE THREAD

**Issue by ViniciusRodrigues26** [frontendbr/vagas#2688]
A Cora está nascendo para revolucionar e precisa de você para construir um banco digital disruptivo e completo!

A FinTech foi fundada pelos criadores do Moip (concorrente do PayPal, vendido para o Wirecard por 165 milhões) e por trás dela estão o André Street, da Stone, e o Jorge Paulo Lemann, do grupo 3G Capital, investidora de marcas gigantes, como iFood e Ambev.

É tudo do zero! A Cora está escolhendo as melhores tecnologias para construir uma plataforma sustentável, escalável e consistente à longo prazo. Ela busca oferecer uma solução voltada para os micro e pequenos empreendedores do nosso país. O grande objetivo é que, até 2030, o trabalho da Cora possa aumentar o PIB do Brasil em 30% através do crescimento desses empreendedores!

Para isso, estão buscando profissionais fora da curva, de todo o Brasil, com propósito e dispostas a crescer exponencialmente! É preciso ter bastante experiência e estar disposto a colocar a mão na massa. A perspectiva é que o(a) Front-End Developer cresça junto com a empresa, construa o time de experts e seja uma liderança no futuro!

A contratação possui remuneração competitiva, benefícios atrativos e será feita em regime CLT, para atuar de forma presencial em São Paulo, com autonomia, flexibilidade e sendo parte de um time extremamente motivado, com senso de donos e personalidade!

Para mais informações, acesse a página da vaga http://byintera.in/corafrontend ou pode falar diretamente comigo através do linkedin https://www.linkedin.com/in/viniciusrdesouza/ para entender melhor o desafio.

É uma oportunidade fantástica para quem quer construir algo gigante em pouco tempo e deixar sua marca!

**Comment by mariamaron** [comment]
Qual o regime de contratação?

**Comment by luizadpassos** [comment]
Qual a carga horária?

**Comment by andre-reis93** [comment]
Quem só tem disponibilidade pra começar a trabalhar no ano que vem pode se candidatar?

**Comment by ViniciusRodrigues26** [comment]
> Qual o regime de contratação?

Olá, Maria! Tudo bem? O regime de contratação é CLT efetivo, para colaborar presencialmente na sede em São Paulo, na Vila Olímpia :)

**Comment by ViniciusRodrigues26** [comment]
> Qual a carga horária?

Oii, Luiza! Como está? A carga horária é de 40h semanais e o pessoal da Cora é super flexível com o horário, há possibilidade de realizar home office 1-2 vezes por semana :)

**Comment by ViniciusRodrigues26** [comment]
> Quem só tem disponibilidade pra começar a trabalhar no ano que vem pode se candidatar?

E aí, André! Tudo certinho? Claro, pode sim! Estamos super abertos a ter talentos participando do nosso processo independente da disponibilidade para início! O que a Cora busca é ter ótimos colaboradores com eles :)

**Comment by pauladiniz** [comment]
Vinicius, a vaga é incrível e há uns dois meses eu participei do processo seletivo através da Intera, se não me engano. Fiz duas entrevistas, uma com o pessoal de lá e outra por telefone com o RH. Acontece que eu tive um imprevisto e avisei um dia antes que não poderia comparecer ao Cora, nunca obtive resposta da menina por Whatsapp, que é por onde estávamos nos falando.

Meu marido também participou da seleção e nunca recebeu um retorno da Intera, que ficou de marcar entrevista com vocês. Até hoje eu e ele recebemos e-mail falando que estamos no processo, mas ninguém falou mais nada. Achei complicado, pois adoramos a vaga e acabou que fomos ignorados.

**Comment by ViniciusRodrigues26** [comment]
Olá, Paula! Tudo bem? Sinto muito por essa situação ter ocorrido, ela não condiz com o que realizamos na Intera. Prezar pela experiência dos nossos talentos é um princípio norteador do nosso trabalho e das nossas jornadas de conexão! Realmente não entendemos o porquê disso ter acontecido. Um dos nossos Ways Of Thinking (os nossos valores) é o Delta Maior Todos os Dias e ele representa justamente o caminho de aprendizado que trilhamos todos os dias. Gostaríamos de agradecer demais pelo feedback, você fez o nosso Delta terminar maior hoje e isso nos deixa bastante felizes! 

Posso te pedir um favor? Envia um e-mail para mim (através de vinicius.rodrigues@byintera.com) detalhando a situação (datas, endereços de e-mail que entraram em contato, o que exatamente aconteceu, qual a última etapa que realizaram...) que vou compartilhar com toda a nossa equipe para que possamos aprimorar os nossos processos e não volte a ocorrer novamente, ok?  Aproveita e coloca os nomes, sobrenomes e e-mails (seu e do seu marido) que vou buscar entender qual o status de vocês na nossa jornada para que possamos dar prosseguimento, caso acreditem que ainda faça sentido.

Esperamos poder conectar vocês a novas oportunidades incríveis em um futuro próximo! 
Um sorriso de orelha a orelha do Time Intera! E obrigado mais uma vez!  :)
