### ISSUE TITLE
[GOIÂNIA] Front-end Developer no Conexa Labs 

### ISSUE THREAD

**Issue by danpadua** [frontendbr/vagas#2692]
## Descrição da vaga

Desenvolver softwares e aplicativos, testes unitários e funcionais, aplicar as melhores práticas de desenvolvimento alinhados às definições de UX/UI e também implementar layout responsivo com frameworks como Bootstrap e React;

- Implementação de layout responsivo com frameworks como Bootstrap e React;
- Irá transitar entre as áreas de design e de desenvolvimento garantindo a performance do código, semântica e interação entre o layout, UX/UI;
- Irá trabalhar com linguagens como JavaScript, SASS/LESS, jQuery, HTML5, CSS 3, Bootstrap, React, React Redux;

## Local

Empresa, Avenida Caiapó, Nº 1510 - Santa Genoveva, Goiânia - GO

## Benefícios

- Vale Alimentação ou refeição
- Plano de saúde e odontológico

#### Diferenciais

- Geladeira Aberta
- Estacionamento
- Sala de descanso
- Horário Flexível
- All casual day

## Requisitos

**Requisitos Técnicos/Comportamentais**

- Mindset voltado para inovação, qualidade, performance, UX/UI;
- 3 anos de experiência como desenvolvedor front-end;
- Html5;
- JavaScript, TypeScript;

**Diferenciais:**
- Sólida experiência com a cultura DEVOPs;
- Desenvolvimento ágil (scrum, sprints);
- Conhecimento de back-end / .net;   
- Inglês intermediário / avançado para leitura e escrita de código;
- Experiência na criação de páginas responsivas, web e mobile;
- CSS avançado CSS3 com framework bootstrap;
- Bons conhecimentos em SASS/LESS;
- Desenvolvimento para os principais navegadores do mercado;
- Experiência com gulp, node.js;
- Testes unitários com Jest, QUnit ou frameworks do tipo;

## Contratação

CLT - A combinar

## Nossa empresa

Somos um time com o propósito de tornar o agro mais simples, usando o que há de mais avançado em tecnologia para construir produtos e ferramentas que conectam pessoas e negócios aos resultados desejados.

## Como se candidatar

Acesse o link para enviar o seu currículo:
[https://conexalabs.gupy.io/jobs/78542?jobBoardSource=gupy_public_page](url)

## Labels

- Alocado
- Júnior
- Pleno
- CLT

**Comment by rhanielvalle** [comment]
Ainda está aberta essa posição?

**Comment by pedroccaetano** [comment]
> Ainda está aberta essa posição?

A vaga não se encontra mais no site da empresa. Gostaria de saber também.
