### ISSUE TITLE
[Floripa] Front-end Developer na 14islands

### ISSUE THREAD

**Issue by marcobarbosa** [frontendbr/vagas#2693]
## Descrição da vaga

A 14islands está abrindo no Brasil e procuramos novos talentos para se juntar ao time escandinávio-brasileiro de gente criativa 🇧🇷🇸🇪.

As vagas são para 2020 mas o processo começa agora no final de 2019. E nada impede de começarmos a colaborar com jobs de freela e irmos nos conhecendo aos poucos pra ver se rola uma química ✨ 

## Local

Florianópolis ou Remoto 🏖 

## Benefícios

- Ajuda de custo para academia
- Ajuda de custo para conta de celular
- Drinks e atividades de equipe com frequência
- 6 semanas de férias remuneradas
- Seguro de vida (CLT, a definir)
- Plano de saúde (CLT, a definir)
- Budget alocado para aprendizado (CLT, a definir)
- E tem mais a definir... 😄 

#### Diferenciais

- Equipe global e criativa (somos do Brasil, Suécia, Islândia, França, Canadá, etc) 🌎 
- Buscamos ajudar na sua carreira, seja você o nível que for, cresceremos juntos 💯 
- Remuneração competitiva com o mercado 💰 
- Sempre buscamos empurrar os limites de design e desenvolvimento 🎱  
- Cultura do [Friday Hack](https://medium.com/14islands/why-fridays-are-hack-days-at-14islands-b6b4d1da6878), para cada trabalho renumerado você acumula horas para gastar depois em projetos pessoais dentro da empresa 😱 
- Cultura escandinávia de trabalho. Aqui levamos a sua vida profissional + pessoal a sério 🏳️‍🌈 

## Requisitos

**Obrigatórios:**
- Nível bom de Inglês.
- Domínio em Javascript e tecnologias front-end.
- Comunicação fácil e flexível. Busca pelo resultado melhor, sempre.
- Ser gente boa e team player.

**Desejáveis:**
- Fluência em Inglês.
- Gatsby.
- CSS.
- Manja de animaçōes e sempre busca aprender algo novo.
- Tem o "olho" para design ou aprecia algo bem feito.

**Diferenciais:**
- Projetos open source ou diferenciados.
- Gosta de palestrar ou tem desejo para isso.
- GIT.
- Experiência com trabalho em equipe criativa (com designers).

## Contratação

CLT ou PJ a combinar.

## Nossa empresa

A 14islands é uma empresa baseada em Estocolmo, Suécia, que busca a excelência em Design e Desenvolvimento. Empresa de "coders" desde o início, hoje expandimos para o design e sempre levamos a experiência de usuário como prioridade. Nossos projetos variam de sites até jogos e aplicativos.

https://14islands.com/work/

## Como se candidatar

Por favor envie um email para vagas@14islands.com com seu CV anexado - enviar no assunto: [Vaga Florianópolis]

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: marco@14islands.com

## Labels

- 🏢 Flexível
- 🏢 Presencial
- 👨 Pleno
- 👴 Sênior
- ⚖️ CLT
- ⚖️ Freela
- ⚖️ PJ
- 💰 5k-10k
- 💰 10k-15k

**Comment by souzasmatheus** [comment]
E-mail enviado! :)

**Comment by FeelipePM** [comment]
E-mail enviado com sucesso!

**Comment by marcobarbosa** [comment]
Obrigado a todos por participar. Os feedbacks estão sendo enviados. 

Abriremos novamente começo do ano que vem  :)
