### ISSUE TITLE
[Diversos] Vagas para Front-end na Codeminer42

### ISSUE THREAD

**Issue by abnersajr** [frontendbr/vagas#2699]
## Descrição da vaga

Buscamos Front-end developers para atuar  em diversos projetos, inclusive projetos internacionais com clientes estrangeiros. Temos diversos projetos, com diversos frameworks e tecnologias, então entre em contato.

## Local

A Codeminer42 está presente atualmente em mais de 12 estados do país. 
Temos vagas para todos eles. 
- São Paulo
- Campinas
- Sorocaba
- Batatais
- Guarapuava
- Novo Hamburgo
- Anápolis
- Goiânia
- Teresina
- Natal
- Santa Maria
- Florianópolis
- Poços de Caldas

## Benefícios
1. Plano de saúde e dental;
2. Auxílio transporte;
3. Vale-refeição;
4. Ambiente de trabalho descontraído;
5. Acesso a cursos e portais de educação como Front-end Masters e egghead.io;
6. Curso de inglês para aperfeiçoamento.

#### Diferenciais

- Horário flexível
- Oportunidade de trabalhar em projetos nacionais e internacionais

## Requisitos

**Obrigatórios:**
- Experiência com um dos UI frameworks a seguir: **React**, **VueJS**, **React Native** ou **Angular**. Experiência com algum outro não listado é analisado individualmente. Mas não deixe de entrar em contato.
- **Inglês avançado: temos clientes internacionais e a compreensão e conversação são fundamentais. Parte do processo seletivo é uma conversa para avaliarmos sua comunicação.**

**Desejáveis:**
- conhecimentos em ruby on rails
- conhecimentos em NodeJS
- conhecimentos de infra-estreutura, AWS e Heroku são amplamente usados.
- Design Patterns
- Programação funcional
- TypeScript

## Contratação

CLT, sobre valores cada caso é avaliado individualmente sobre diversos aspectos, mas podemos garantir que os valores são atraentes

## Nossa empresa

A Codeminer 42 é uma butique de software brasileira focada em entregar o melhor valor a seus clientes. Nós começamos a operar em Setembro de 2011 e até agora expandimos para 10 cidades diferentes no Brasil com os melhores profissionais do Brasil.

Nossa especialidade é desenvolvimento web com Ruby on Rails e seu ecossistema satélite - que inclui as melhores tecnologias de ponta -, nós temos muita experiência em todos os tipos de produtos de tecnologia como e-commerces, e-learning, redes sociais, gerenciamento de conteúdo, automação de processos.

Trabalhamos com empresas pequenas ou grandes, temos diversos tipos de serviços que vão de ciclo de vida de desenvolvimento de projetos do zero, resgate de projetos legados, terceirização e assim por diante.

Se quiser ter não somente uma boa aplicação web em produção mas também melhorar seus processos de software, garantia de qualidade, podemos ajudar.

## Como se candidatar

Por favor envie um email para become@codeminer42.com com seu CV anexado, github, site pessoal e demais infos.
No Assunto coloque [CIDADE] Vaga para Front-end .
Maiores dúvidas, podem usar a issue ou enviar para abner.alves@codeminer42.com

PS: Temos vagas para Back-end também: 🔗[Vaga Back-end](https://github.com/backend-br/vagas/issues/1933)

## Labels
* CLT
* Alocado
* Estágio
* Júnior
* Pleno
* Sênior

**Comment by abnersajr** [comment]
@MrS4w Rio de Janeiro não faz parte, acho que seria Rio Grande do Sul não? Quando puder mudar agradeço.

**Comment by MrS4w** [comment]
Confundi os "Rios" my bad 😅

**Comment by abnersajr** [comment]
@MrS4w quando possível remover a label de Remoto. Obrigado.

**Comment by fernando-Jesus** [comment]
Inglês :(

Pena que não tenho domínio!

**Comment by randhson** [comment]
enviado.

Randson N. dos S. França +55 79 99843 9878+55 79 99138 7628 

    Em segunda-feira, 2 de dezembro de 2019 10:49:09 BRT, Fernando Jesus <notifications@github.com> escreveu:  
 
 
Inglês :(

Pena que não tenho domínio!

**Comment by abnersajr** [comment]
@fernando-Jesus hoje em dia o Inglês é algo muito valioso se desejas crescer e ir longe. Não desanime e nunca é tarde para começar. E hoje em dia tem diversas maneiras de estudar e aperfeiçoar-se. 💪  Siga firme

**Comment by fernando-Jesus** [comment]
> @fernando-Jesus hoje em dia o Inglês é algo muito valioso se desejas crescer e ir longe. Não desanime e nunca é tarde para começar. E hoje em dia tem diversas maneiras de estudar e aperfeiçoar-se. 💪 Siga firme

Verdade, tenho esta ciência.

Brigadão pelas palavras.

Abs

**Comment by zeyuri** [comment]
opa ta tendo vaga pra curitiba?

**Comment by abnersajr** [comment]
@zeyuri Curitiba não. O mais próximo é Guarapuava.

**Comment by marciordj** [comment]
Opa, tem vaga pra estágio em Sorocaba ?

**Comment by italomlp** [comment]
@abnersajr Fiquei com duas dúvidas. A primeira é se posso me candidatar para remoto como pleno. A segunda é se esse inglês avançado exige conversação oral, ou se conversação escrita é suficiente.

**Comment by abnersajr** [comment]
@marciordj tem sim.
@italomlp remoto não é mais uma possibilidade infelizmente. E sobre o Inglês mais que escrito o principal é a conversação como você falou oral. A comunicação escrita querendo ou não  é um pouco facilitada com o tradutor. Mas trabalhamos diretamente com clientes internacionais e na sua grande maioria temos meetings, dailies, standups todos os dias. Por isso a necessidade.

**Comment by italomlp** [comment]
@abnersajr Entendi. Sucesso então na seleção, a Codeminer parece ser uma ótima empresa!

**Comment by marciordj** [comment]
@abnersajr Opa, enviei meu currículo,  muito obrigado

**Comment by vncscoelho** [comment]
@abnersajr Como funciona a questão do framework? São listados 3 mas como funciona no dia a dia?

**Comment by abnersajr** [comment]
@vncscoelho temos diversos projetos e isso varia do cliente. Hoje temos na ordem de mais usado para menos usado:
1. React
2. VueJS
3. Angular

Porém como temos diversos clientes isso varia muito. Por isso é importante a base sólida de JS. Se você sabe mais VueJS beleza, mas é legal aprender React também, ao menos saber o básico do seu funcionamento.

**Comment by esterfogaca** [comment]
Olá, como estão as vagas para Florianópolis? Tem posição para júnior? :D

**Comment by abnersajr** [comment]
@esterfogaca obrigado por perguntar. Infelizmente Florianópolis não temos um escritório ainda. Então não temos vagas para Júnior lá. Mas ficarei com seu contato para caso venhamos a montar uma sede entrarmos em contato ;)

**Comment by randhson** [comment]
Quanta tempo para um feedback sobre o envio do email com o curriculo ?

Randson N. dos S. França +55 79 99843 9878+55 79 99138 7628 

    Em segunda-feira, 9 de dezembro de 2019 10:09:05 BRT, Abner Soares Alves Junior <notifications@github.com> escreveu:  
 
 
@esterfogaca obrigado por perguntar. Infelizmente Florianópolis não temos um escritório ainda. Então não temos vagas para Júnior lá. Mas ficarei com seu contato para caso venhamos a montar uma sede entrarmos em contato ;)

**Comment by abnersajr** [comment]
@randhson normalmente não demora. Você enviou para qual e-mail?

**Comment by randhson** [comment]
enviei para o become@codeminer42.com
dia  29/11


Randson N. dos S. França +55 79 99843 9878+55 79 99138 7628 

    Em segunda-feira, 9 de dezembro de 2019 14:26:12 BRT, Abner Soares Alves Junior <notifications@github.com> escreveu:  
 
 
@randhson normalmente não demora. Você enviou para qual e-mail?

**Comment by marciordj** [comment]
@abnersajr To com o mesmo "problema". Eu mandei o meu currículo para o email informado e não tive nenhum feedback

**Comment by abnersajr** [comment]
@marciordj e @randhson temos os requísitos mínimos descrito na vaga, o pessoal faz a triagem de muitos email e se não preenche os requisítos obrigatórios o pessoal acaba não respondendo.

Caso vocês acham que tenha sido um equívoco peço por favor que mandem para mim diretamente que eu analiso novamente. abner.alves@codeminer42.com

Espero que compreendam.

**Comment by randhson** [comment]
Acabei de enviar para o seu email, se puder analisar novamente eu agradeço.

Randson N. dos S. França +55 79 99843 9878+55 79 99138 7628 

    Em terça-feira, 10 de dezembro de 2019 09:17:12 BRT, Abner Soares Alves Junior <notifications@github.com> escreveu:  
 
 
@marciordj e @randhson temos os requísitos mínimos descrito na vaga, o pessoal faz a triagem de muitos email e se não preenche os requisítos obrigatórios o pessoal acaba não respondendo.

Caso vocês acham que tenha sido um equívoco peço por favor que mandem para mim diretamente que eu analiso novamente. abner.alves@codeminer42.com

Espero que compreendam.

**Comment by abnersajr** [comment]
2020 começou e continuamos com oportunidades na Codeminer42. Quem tiver alguma dúvida após ler a descrição não deixe de perguntar.

**Comment by rhanielvalle** [comment]
> 2020 começou e continuamos com oportunidades na Codeminer42. Quem tiver alguma dúvida após ler a descrição não deixe de perguntar.

Abner, vi que tem vaga aberta na minha cidade, Goiânia. Você estimam que é pra quando o inicio do onboarding? Pergunto, pois eu vou iniciar a imersão em inglês, pra retomar conversação. Leitura e audição estão tranquilas.

**Comment by vivianeasaraiva** [comment]
Então basicamente é pra progamar em frameworks de Javascript?

**Comment by abnersajr** [comment]
@rhanielvalle desculpa a demora. Alguns dias para responder. Estamos sempre buscando pessoas para nosso time. Sinta-se avontade para aplicar quando achar que está pronto :)
