### ISSUE TITLE
[Recife] Front-end Developer na Justa Pagamentos (justa.com.vc)

### ISSUE THREAD

**Issue by matheusnascgomes** [frontendbr/vagas#2701]
## Descrição

E ai, pessoal, tudo bom com vocês?

Meu nome é Matheus, e eu trabalho na Justa Pagamentos, uma empresa que acredita e credita o nosso cliente. Somos uma fintech de São Paulo com filial em Recife, e adivinha só? Estamos com vagas para o nosso time de Front-end em Recife!

Procuramos pessoas que sejam apaixonadas por desenvolver, saibam trabalhar em equipe, e buscam dar o seu melhor sempre!

## Local

Presencial, Recife - Pernambuco

## Benefícios

- Plano de saúde
- VR de R$ 30
- Auxílio Transporte ou Gasolina

#### Diferenciais

- Você é o gestor do seu tempo
- Hierarquia horizontal
- Frigobar sempre cheio de cerveja :P
- Sala de jogos
- Varanda com vista para o Mar
- Computadores fornecido pela empresa
- Múltiplas telas
- Não temos Dress code (só não vale vir pelado)
- Temos chuveiro para quem gosta de se exercitar (por enquanto só temos sedentários, venha ser o primeiro a usar)

## Requisitos

**Obrigatórios:**

- 2 ano de experiência com JavaScript
- 2 ano de experiência com HTML / CSS
- 1 ano de experiência com algum Framework/Lib SPA - ( Angular 2+, React ou Vue)

**Desejáveis:**
- Conhecimento em metodologias ágeis - e.g. SCRUM
- Boa leitura, escrita e fala em inglês ou espanhol

**Diferenciais:**

- Projetos opensource
- Conhecimentos em Java ou Scala
- Conhecimentos em Android ou iOS
- Conhecimentos em PostgreSQL
- Conhecimentos em arquitetura reativa

## Contratação

PJ a combinar

## Como se candidatar

Entra no nosso github (https://github.com/justapagamentos/jst-job-challenges/tree/master/front-end) e segue o passo a passo do nosso desafio Front-end. Manda também um email pra gente (matheus.gomes@justa.com.vc e rai.siqueira@justa.com.vc) com o link do teu github e o linkedin, e falando um pouco sobre você.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: matheus.gomes@justa.com.vc e rai.siqueira@justa.com.vc

## Labels

- Alocado
- Júnior
- PJ

**Comment by mundau** [comment]
Oi

Em sáb, 30 de nov de 2019 04:44, Matheus Gomes <notifications@github.com>
escreveu:
