### ISSUE TITLE
[Gdansk - Polonia] Front-end Developer na EPAM

### ISSUE THREAD

**Issue by augustoabreu** [frontendbr/vagas#2707]
**DESCRIPTION**
Currently we are looking for a JavaScript Developer for our Gdansk office to make the team even stronger.

Software Developer position in EPAM gives opportunity to interact with skilled engineers worldwide, be acquainted with various industries & domains and work with modern technologies used in our projects.

**RESPONSIBILITIES**

- Full-cycle web application development using Agile approach
- Deliver features according to Software Design Specification (no maintenance work)
- Development of Unit Tests
- Troubleshooting problems and issues
- Communicate with the client to clarify requirements
- Taking part in planning and estimation
- Integration with other clients’ systems and applications

**REQUIREMENTS**

- Highly experienced in plain JavaScript, HTML and CSS
- Experience with React
- Experience with Redux
- Understanding of software development life cycle and development methodologies
- Experience in unit testing
- Solid SDLC understanding and experience working in Agile environment
- Spoken English & experience in client-facing communications

**NICE TO HAVE**

- Experience with a Design Framework like Carbon is a huge plus
- Experience with: Vue.JS, SaaS, Swagger, NPM, AJAX

**WE OFFER**

- Possibility to be involved in an international project (Canada, China, Hong Kong, Mexico, USA, Switzerland, Germany, Sweden, United Kingdom, Russia, Belarus, Ukraine, Hungary, etc.)
- Language classes (English and Polish)
- Vast opportunities for self-development: online courses and library, experience exchange with colleagues around the world, partial grant of certification
- Career development center
- Unlimited access to LinkedIn learning solutions
- Possibility to take part in both: corporate and startup environment
- Possibility to relocate for short and long-term projects
- Relocation package for those who relocate to Krakow, Wroclaw, Katowice or Gdansk from other locations
- Benefit package (health care, multisport, lunch tickets, petrol vouchers and shopping vouchers, etc.)
- Fruits on a weekly basis
- Sponsored sport activities

### Labels

- Realocação
- Contrato
- Pleno (Regular)

https://www.epam.com/careers/job-listings/job.49047?utm_source=invite&utm_medium=web&utm_content=job_post_link&utm_term=rfr_WFhYWDQwMjhlNGY2LTA5NzEtNDQ0MS04NmM3LTFhODdjOTYxNTAyNFhYWFg_srcid_2

**Comment by alessandroprudencio** [comment]
Aoo maldito inglês não sei conversar nessa porr...
