### ISSUE TITLE
[São Paulo] Estágio em Front-End

### ISSUE THREAD

**Issue by MicheleLabriola** [frontendbr/vagas#271]
## Descrição da vaga 

Estágio em Front-End

## Local

Escritório, São Paulo - ao lado do Metro Saúde

## Requisitos

Não é necessário experiência profissional prévia, mas vamos avaliar seus conhecimentos em um teste prático, como parte do processo seletivo.

**Obrigatórios:**
- HTML5
- CSS3

**Desejáveis:**
- Conhecimento em AngularJS
- Conhecimento em pré-compilador CSS (preferencialmente o SASS)
- Algum conhecimento em aplicações híbridas (preferencialmente Ionic framework)
- Java Script
- JQuery

## Contratação

Estágio, de segunda à sexta, das 09h as 16h com 1h de almoço
Bolsa auxílio de R$ 1.000,00/mês + R$ 600,00/mês de ajuda de custo para transporte e alimentação. Total de R$ 1.600,00/mês

## Nossa empresa

Negocie Online, Startup Brasil turma 3. 

Negocie Online é uma Assessoria Digital de Cobrança e Recuperação de Crédito.
Buscamos eficiência operacional para nossos Clientes e, especialmente, conveniência para os Clientes de nossos Clientes.
Fundada por profissionais com ampla experiência no mercado de Contact Center, nossa missão é combinar e explorar ao máximo as facilidades oferecidas pela Internet, Smartphones e Computação Cognitiva, para revolucionar os Serviços de Atendimento ao Consumidor.

Visite nosso site para saber mais: www.negocie.online

## Como se candidatar

Por favor envie um email para contato@negocie.online com seu CV anexado - enviar no assunto: Vaga Estagio Front-end

**Comment by gabriel-brito** [comment]
Que vaga bacana! Irei enviar meu curriculum o mais rápido possível!

**Comment by gabriel-brito** [comment]
Done!

**Comment by vinirossi** [comment]
Currículo enviado.

**Comment by F-Juliano** [comment]
Currículo enviado

**Comment by MatheusJusto** [comment]
Enviado ;)
