### ISSUE TITLE
[Rio de Janeiro] Senior Full Stack Developer na Lemoney

### ISSUE THREAD

**Issue by lemoneyhiring** [frontendbr/vagas#2712]
## Missão do Cargo

Nosso time de Desenvolvimento é o **coração** da empresa. Eles são os responsáveis pelo coding, manutenção e implementação de novas features para nossos principais produtos e projetos. 

Solução de ponta a ponta: _Front to Back_, passando por testes automatizados e tentando sempre encontrar as melhores opções tecnológicas para solucionar os problemas.

Procuramos pessoas proativas, com muita vontade de aprender e assumir novos desafios em sua carreira. 

## Nossa Tech Stack

Trabalhamos atualmente com Ruby on Rails, JavaScript e Vue.JS, mas em alguns projetos utilizamos Node.JS também. 
Nossa Sprint é semanal e utilizamos a metodologia SCRUM.
Utilizamos o Google Clouds como serviço de armazenamento.

## Pré Requisitos

- Experiência como Full Stack (+4 anos);
- Sólido conhecimento em JavaScript e alguma de suas frameworks (Vue é um diferencial);
- Desenvolver com testes automatizados;
- Ser apaixonado por aprender novas tecnologias e explorar novas soluções;

**Desejáveis**
- Experiência anterior trabalhando com CI (_Continuous Integration_);
- Experiência com Google Clouds;
- Conhecimentos em SEO;

## Sobre Nós

Somos uma startup americana de Cash Back e Cupons liderada por um time **Brasileiro**. Temos quatro anos de estrada e estamos em um momento chave de expansão e crescimento. Além de lidar com um mercado que é referência no mundo, estamos expandindo nossa operação para outros locais, o que torna o desafio mais gostoso ainda! :)

Aqui na **[Lemoney](https://www.lemoney.com/)**, você poderá contribuir para o crescimento e escalabilidade da empresa em ritmo _startup_ de ser. Agilidade está em nosso _core_.

## Local

Nosso Escritório fica em um dos pontos mais atrativos do Rio de Janiero, próximo à Praia de Ipanema, em frente ao metrô da Nossa Senhora da Paz. Temos também, um co working space em Downtown Miami.

Para essa vaga consideramos apenas posições **Presenciais**.

## Diferenciais

- Horário Flexível com política de Home Office duas vezes na semana;
- Ambiente compartilhado com muita possibilidade de troca e aprendizado;
- Oportunidade de lidar diretamente com o produto, participar e contribuir nas decisões chaves da empresa e da área de desenvolvimento;
- Nosso time é pequeno, mas é de ouro! Todos engajados e extremamente produtivos; 
- Você trabalhará diretamente com o mercado americano, onde a excelência é _default_;
- Ambiente informal e dinâmico, com amplo espaço para criatividade e inovação;

## Application

Se identificou com a oportunidade? Envie seu Currículo ou Linkedin para careers@lemoney.com

**Comment by romulolessa** [comment]
bom dia. Tem vaga para júnior ?

**Comment by lemoneyhiring** [comment]
Ola, Romulo!

No memento, não..
Mas pode mandar o seu curriculo pra gente que assim que abrir alguma vaga a
gente entra em contato :)

Abs,
--------

<https://www.lemoney.com/>
Odara Menezes
*Human Resources*
 +55 (21) 3502-2185
 odara.menezes@lemoney.com
<https://www.facebook.com/lemoneyway>
<https://www.instagram.com/lemoney_coupons>
<https://www.twitter.com/lemoneyway>  <https://www.pinterest.com/lemoneyway>
