### ISSUE TITLE
[São Paulo ou remoto] Desenvolvedor Front-End | Customer Success

### ISSUE THREAD

**Issue by cleytonmessias** [frontendbr/vagas#272]
## Descrição da vaga

A Trustvox, certificadora online de reviews, está procurando "A" pessoa para se trabalhar com Customer Success!

Estamos atuando em lojas virtuais em marcas como: O Boticário, Polishop, World Tennis e por aí vai.

A pessoa precisa ser um bom front-end developer e gostar de atender clientes :)

Gostamos MUITO de Customer Success. Veja o que já falamos sobre isso [aqui](https://pt.slideshare.net/cleytonmessias/customer-success-o-motor-de-crescimento-da-sua-empresa), [aqui](https://pt.slideshare.net/cleytonmessias/customer-success-o-que-e-como-fazemos-na-trustvox) e [aqui](https://papodehomem.com.br/por-que-atender-bem-faz-tao-bem-pra-sua-empresa/).

## Local

Remoto ou Escritório em São Paulo

## Requisitos

**Obrigatórios:**

- CSS3
- HTML5
- Conhecimento básico em Javascript
- Gostar de trabalhar com atendimento

**Desejáveis:**
- Trabalhar com atendimento a clientes 
- Fazer treinamento online e presencial
- Engajar clientes e mostrar resultados
- Entender a necessidade e propor upsells (venda de outros produtos)
- Gostar de estudar sobre Customer Success

## Contratação

CLT

## Como se candidatar

Por favor, se candidate nesse link: https://trustvox.recruiterbox.com/jobs/fk0m2y8

**Comment by ribeiroevandro** [comment]
Woooow essa vaga é perfeita, já trabalhei com atendimento ao cliente na ouviria da Cielo e hoje sou front-end... Junção perfeita, de duas coisas que curto fazer, vou aplicar agora... o/

**Comment by ygorlazaro** [comment]
E essa vaga estaria aberta a PJ ou somente CLT?

**Comment by ribeiroevandro** [comment]
Enviado o/

**Comment by cleytonmessias** [comment]
@ygorlazaro A princípio é CLT, porém podemos ver caso a caso :)

**Comment by rafaelassumpcao** [comment]
@cleytonmessias  já foram encerrada as vagas

**Comment by cleytonmessias** [comment]
@rafaelassumpcao Fechamos essa semana. Fechando o issue por aqui. Muito obrigado a todos 😄

**Comment by LFeh** [comment]
Alguem daqui?

**Comment by cleytonmessias** [comment]
@LFeh Fizemos várias entrevistas com pessoas daqui, porém escolhemos por outra pessoa que submeteu.

**Comment by LFeh** [comment]
Maneiro 🍡
