### ISSUE TITLE
[Remoto] Front-end Developer na Stone

### ISSUE THREAD

**Issue by taianeuchoac** [frontendbr/vagas#2723]
# Descrição da vaga
Atuará no desenvolvimento de aplicações internas.

## Local
Atuação remota para profissionais de fora do estado de São Paulo ou que residam no interior de SP.

## Benefícios
Contratação PJ

## Requisitos
Profissional com mais de 3 anos de experiência em desenvolvimento de sistemas.
Conhecimento e prática em boas práticas de desenvolvimento de software, como TDD, Código Limpo, Padrões de Projeto, entre outras;
Experiência em desenvolvimento voltado para Front-End;
Excelentes conhecimentos e experiência em JavaScript e integração com APIs;
Familiaridade com as práticas de Entrega Contínua (Continuous Delivery);
Experiência com algum Framework de Javascript como (Ex. React, Angular).

**Diferenciais:**
Contribuições em projetos open-source;
Disposição para trabalhar com qualquer tecnologia
Experiência com design de interfaces, CSS e HTML.

## Contratação
PJ a combinar

## Nossa empresa
A Mazzatech é uma consultoria de TI que esta no mercado há mais de 10 anos.
Estamos apoiando a Stone na busca por profissionais, uma empresa que atua com meios de pagamentos e vem crescendo rapidamente no mercado.

## Como se candidatar
Por favor envie um email para taiane@mazza.tech com seu CV anexado e sua pretensão salarial - enviar no assunto: Vaga FrontEnd

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: taiane@mazza.tech

## Labels
- Alocado
- PJ
- Pleno
- Remoto
- Sênior

**Comment by danielswater** [comment]
Enviado
