### ISSUE TITLE
[São Paulo] Fullstack Developer na RoutEasy 🚚

### ISSUE THREAD

**Issue by r-yoshimoto** [frontendbr/vagas#2728]
## Descrição da vaga

Esta oportunidade é para o time de Produto e Desenvolvimento aqui na RoutEasy. Que queira trabalhar e evoluir a nossa stack:

- AngularJS
- NodeJS
- Express
- MongoDB
- Ionic

Fazemos campeonato de pebolim e de Smash Bros Ultimate!! Falamos desde memes a política, mantendo sempre o respeito às diversas personalidades do time. No nosso time temos de tudo, desde headbanger, sertanejeiro a jpopeiro, rpgeiro - somos um time muito próximo, bem humorado e ao mesmo tempo introspectivo. Apesar de tudo, aqui a gente quer continuar a posicionar a RoutEasy como o melhor roteirizador do Brasil! (Aliás, estamos até invadindo a Latinoamérica junto a clientes como Mercado Livre e FEMSA - hola que tal?).

## Local

Escritório em São Paulo - Vila Clementino (Prox. Hosp. AACD - Linha Lilás do Metrô)

## Benefícios

- Contratação PJ
- Bônus de 20% mensal conforme metas da equipe! 
- Convênio Bradesco Médico e Odontológico
- Férias Remuneradas

#### Diferenciais

- Futebol de mesa ou totó ou pebolim ou pacal ou fla-flu ou matraquilhos ou matrecos.
- Cervejas

## Requisitos

**O que esperamos de você:**
- Querer trabalhar com a nossa stack (aquela lá do início da issue, hehe!)
- Que tenha alta visão de componentização construindo códigos de alto reuso com frameworks SPA;
- Que apresente facilidade de desenvolvimento de micro-interações e que traga experiência em construção de soluções de alta disponibilidade e alta resiliência;
- Com capacidade de evoluir tecnicamente tanto a si mesmo quanto a outros membros do time com sua experiência e vivência técnica;
- Que consiga manter no gerenciamento de projetos ligados aos softwares;uma boa autogestão, com boas estimativas e comunicação com o time;
- Que mantenha uma boa convivência com um time diverso e num ritmo de startup;
- Aceitamos juniors, plenos e seniors que queiram aprender e crescer ainda mais com a gente;

**O que levamos em consideração:**
- Experiência como desenvolvedor fullstack, mas aceitamos devs front-end e back-end que queiram aprender e se desenvolver como fullstack;
- Inglês intermediário - necessário para sustentar a internacionalização do nosso time e da RoutEasy!;
- Domínio relevante com Git;
- Domínio relevante com JavaScript e seus Design Patterns;
- Domínio relevante com NodeJS e Express;
- Domínio relevante com MongoDB e Mongoose;
- Domínio relevante em framework SPA;
- Domínio relevante com APIs RESTFul;
- Experiência ou vontade de aprender estrutura de testes, de preferência Mocha;
- Experiência com programação assíncrona (Promises, Generators, Streams);
- Trabalhar para entregar sempre o máximo de valor a aplicação ao mesmo tempo atendendo as expectativas dos clientes finais.  
- Experiência em otimização de interfaces para máximo de velocidade.
- Ter vontade de mexer em aplicação mobile (Ionic) é um plus!

**O que esperar do seu dia-a-dia:**
- Desenvolver softwares, sistemas e aplicações;
- Manutenção de sistemas para correção de falhas/erros;
- Implementação de melhorias;
- Participar ativamente na construção da solução (com ideias, brainstorm, etc.)
- Realizar testes nos sistemas;
- Automação de testes de interface;
- Atuar como parte do time ágil;
- Arquitetar, projetar, desenvolver, implantar e operar serviços na cultura DevOps.

## Contratação

PJ

## Nossa empresa

Hoje temos orgulho de dizer que somos a solução de roteirização com o algoritmo de processamento mais avançado do Brasil. O RoutEasy possui diversas funcionalidades e é capaz de considerar uma grande quantidade de restrições de operação e de atendimento ao cliente. Isso permite que o sistema fique totalmente adaptado ao modelo de operação de qualquer operação logística, otimizando e reduzindo custos de verdade!

Nossa equipe possui paixão por resolver problemas complexos do ramo de logística. Os fundadores trabalharam em empresas de diversos segmentos e em consultoria logística, sempre focados em assuntos relacionados à aumento de performance operacional. O nosso time de desenvolvedores é composto por nerds fantásticos (são eles que fazem o RoutEasy acontecer) e pela máquina de café, que é nossa funcionária do mês, todos os meses.

## Como se candidatar

Por favor envie um email para noemi.fukusig@routeasy.com.br com seu CV anexado e de preferência seu Github e Linkedin - enviar no assunto: 'Vaga Fullstack Dev'

## Tempo médio de feedbacks / Processo Seletivo

1. Fazemos um filtro e se seu perfil fizer sentido para vaga te chamamos pra um papo online. Se não fizer sentido a gente também avisa.
2. Dependendo do material que você nos enviar (github, repositórios, portifólio, site pessoal, projetos) e da sua senioridade, pode rolar um teste técnico. A gente sempre envia um feedback com algumas sugestões de melhorias e geralmente a gente vai te chamar online novamente pra conversar um pouco sobre o seu código.
3. Te chamamos para um papo final presencial para você nós conhecer pessoalmente, nessa ocasião provavelmente conhecerá alguns dos sócios.
4. Se tudo der certo: Proposta! 

## Labels

- Alocado
- Júnior
- PJ
- Pleno
- Sênior

**Comment by r-yoshimoto** [comment]
Continuamos com vagas abertas! ;)

**Comment by GesielBuffer** [comment]
Gostaria de uma oportunidade.

Sou estudante do BootCamp da Rocketseat.

Com ênfase em Nodejs, ReactJs, React Native e skills complementares.

Tenho experiência na área de TI como analista de TI.

Segue meu CV para melhor descreve4 minha experiência.

Preciso de uma oportunidade


Em qui, 9 de jan de 2020 16:53, Rodrigo Yoshimoto <notifications@github.com>
escreveu:
