### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor Front-end | Reserva

### ISSUE THREAD

**Issue by gusribeiro** [frontendbr/vagas#273]
## Descrição da vaga
Procuramos desenvolvedores frontends com experiência para fazer parte do nosso time.
Este profissional será parte atuante na construção/manutenção do ecommerce e sistemas web de nossas marcas.

## Local
Sede em São Cristóvão - Rio de Janeiro

## Benefícios
- Vale transporte
- 40% de desconto nos produtos Reserva após 3 meses (limite de 5 peças por mês)
- Bônus de até 30% do salário ao bater as metas de venda/mês do ecommerce
- Playstation, totó e sinuca
- Day-off no mês do seu aniversário

## Requisitos
**Obrigatórios:**
- Domínio de HTML, CSS e JavaScript
- Experiência com bibliotecas/frameworks Javascript (jQuery, AngularJS etc)
- Experiência com sites responsivos/grids fluidos

**Desejáveis:**
- Familiaridade com controle de versão (Git)
- Automatização de tarefas (Gulp)
- SEO no frontend

**Diferenciais:**
- AngularJS

## Contratação
CLT

## Nossa empresa
A história do Grupo Reserva é escrita todo dia por 1000 pessoas. A personalidade forte, o cuidado com o cliente, o design apurado e o investimento em inovação levaram a Reserva a se transformar em um grupo que hoje abriga 3 marcas.
Somos um organismo vivo em mutação e crescimento constante. Atualmente, o grupo soma 65 lojas próprias nas principais capitais do Brasil, 8 franquias e tem presença em 1.400 multimarcas pelo país.

## Como se candidatar
Enviar email com assunto **[Vaga Frontend - Github]** para eduardo.costa@usereserva.com informando sua pretenção salarial.

**Comment by gusribeiro** [comment]
@LFeh pode adicionar as labels: clt, alocado, pleno e senior pfvr?

**Comment by Marlysson** [comment]
**Uma dúvida :** Qual o objetivo da pretenção quando enviar o email ?

> Além de saber quanto cada um se propõe a receber.

**Comment by gusribeiro** [comment]
@Marlysson acredito que para saber se está de acordo com o que a empresa está disposta a pagar. aqui eles sempre pedem essa pretenção

**Comment by antigui22** [comment]
@gusribeiro boa tarde cara, eu consultor técnico de uma empresa de RH, o Eduardo Costa é o responsável direto pela vaga? Gostariamos de enviar uma propósta.

**Comment by gusribeiro** [comment]
@antigui22 pode enviar p/ ele mesmo :)

**Comment by antigui22** [comment]
Valeu man!

**Comment by grippado** [comment]
Po @gusribeiro Pretensão com Ç? Mais de uma vez? rs
deu até dorzinha de ler! T_T

**Comment by cs-gustavo-ribeiro** [comment]
hehehe! português nunca foi meu forte, acontece @grippado

**Comment by gusribeiro** [comment]
português nunca foi meu forte @grippado, acontece! hehehe

**Comment by paulo101977** [comment]
Bom dia. Eu enviei o curriculum para o e-mail informado. Porém, após aproximadamente 13 dias, não obtive qualquer informação.

**Comment by gusribeiro** [comment]
@paulo101977 peço que tente entrar em contato com o email informado. infelizmente não consigo ver isso para ti pois já saí da empresa.

@LFeh nesse caso, não sei se fechamos a issue ou continua aberta. help! :)

**Comment by LFeh** [comment]
Se você saiu e talvez não tenhamos feedback, acho que é melhor fechar por enquanto :)

**Comment by paulo101977** [comment]
@gusribeiro, vou entrar em contato novamente e aguardar se enviarão alguma resposta. Obrigado pelo feedback!

**Comment by nandosangenetto** [comment]
Pelo que eu saiba a vaga ainda está aberta, entraram em contato comigo ontem.

**Comment by LFeh** [comment]
Abro?

**Comment by gusribeiro** [comment]
@LFeh posso me comprometer a verificar com eles de tempos em tempos se já fecharam a vaga ou não, o que acha?

**Comment by LFeh** [comment]
Perfeito o/

**Comment by gusribeiro** [comment]
@LFeh vagas preenchidas, pode fechar pfvr
