### ISSUE TITLE
[Remoto] Frontend Developer Junior na Instruct

### ISSUE THREAD

**Issue by iassia** [frontendbr/vagas#2730]
Estamos buscando frontend developer que consiga trabalhar em um time multidisciplinar, que tenha bons conhecimentos em desenvolvimento web, criando interfaces, implementando frontend e integrando com backend.

Você fará parte de uma equipe que desenvolve soluções de automação de alto impacto na operação de TI de nossos clientes.

**Sua maior responsabilidade será atuar com interfaces desde o desenho, passando pela implementação do HTML, CSS, JavaScript e integrações com backend.**

É fundamental que você goste de compartilhar o seu conhecimento com outras pessoas. Ser curioso e autodidata são características bem vindas.

O trabalho poderá ser realizado totalmente remoto, dentro de horário comercial e seguindo o horário de Brasília, com ocasionais viagens a São Paulo, Brasília, Campinas e Rio de Janeiro para encontros com a equipe ou clientes, custeados pela empresa. Portanto, é fundamental ter disponibilidade para viajar.

Nós não perguntamos pretensão salarial. Se identificarmos que você é a pessoa que queremos ter em nossa equipe, faremos uma proposta financeira condizente dentro da faixa salarial inicial da empresa.

## Benefícios

 - Regime de contratação CLT;
 - Salário inicial entre R$ 2.000,00 e R$ 3.000,00;
 - Plano de saúde e odontológico Bradesco Top Nacional Top para o titular e seus dependentes;
 - Vale refeição de R$ 400,00;
 - Vale alimentação de R$ 600,00;
 - Seguro de vida corporativo custeado pela empresa;
 - Verbas para investimento em treinamentos e educação;
 - Acesso aos treinamentos da empresa sem custos;
 - Prêmio de participação nos resultados;
 - Prêmio quando se completa aniversário de empresa;
 - A empresa fornecerá um laptop com as seguintes configurações: Dell Inspiron 14 5480 (Core i7-8565U, RAM 16GB, GeForce MX150, HDD 1TB, SSD 128GB, Full HD);

## Por que trabalhar na Instruct?

 - Ambiente de trabalho amigável, inclusivo e seguro;
 - Resolvemos problemas desafiadores e em larga escala para nossos clientes;
 - Incentivos para participação em eventos, cursos e palestras;
 - Usamos ferramentas e métodos inteligentes e inovadores para interagir com nosso time;
 - Cultura blameless;
 - Café de qualidade!

## O que esperamos de você?

 - Esperamos que nos ajude a melhorar a performance dos nossos clientes;
 - Esperamos que você consiga se relacionar bem com o seu time de trabalho, que saiba fazer parte do time, respeitar o time, dividir e compartilhar responsabilidades, acertos e aprendizados;
 - Esperamos que você possa ir além, propondo, criando, mudando, construindo, crescendo e evoluindo junto conosco;
 - Queremos que você agregue valor ao nosso time e a nossa organização, e queremos que a nossa organização agregue valor a você;

## Conhecimentos e experiências fundamentais:

 - HTML 5 e noções de acessibilidade;
 - CSS 3 e Flexbox;
 - Javascript (ES6+);
 - Noções básicas de UI/UX;
 - Integração de aplicações via APIs REST;
 -  Uso de Git para versionamento de seu código;

## Conhecimentos diferenciais:
 - Desenvolvimento de algum projeto Frontend sem a utilização de libraries ou frameworks;
 - Uso de aplicações visuais como Figma, Sketch ou Illustrator;
 - Automatizadores e Bundlers: Gulp, Webpack, etc;
 - SCSS e BEM;
 - Experiência com Vue.js;
 - Ferramentas de testes JavaScript: Jasmine, Jest ou Mocha;

## Tecnologias e métodos
Estas são tecnologias, métodos e conceitos que utilizamos em nossos projetos, o conhecimento destes será um diferencial apreciado:

 - Fundamentos de modelos ágeis como Kanban e Scrum;
 - Fundamentos do conceito testes unitários;
 - Analise e desenho de interfaces utilizando Figma;
 - SCSS e BEM;
 - Vue.js e Node.js;
 - GitLab CI;
 - Participação em projetos Open Source;

## Informações adicionais
 - Local: Remoto com encontros presenciais
 - Horário: Comercial das 9h às 18h (40h semanais)

## Para participar do processo
Enviar um e-mail com CV para jobs@instruct.com.br com assunto "Desenvolvedor(a) Frontend Junior".

## Labels

- CLT
- Júnior
- Remoto

**Comment by LucasCastelo** [comment]
Enviado!

**Comment by EzequielBrilhante** [comment]
Enviado

**Comment by randhson** [comment]
Enviado.

Randson N. dos S. França +55 79 99843 9878+55 79 99138 7628 

    Em quarta-feira, 11 de dezembro de 2019 15:59:26 BRT, Fabio Iassia <notifications@github.com> escreveu:  
 
 
Estamos buscando profissional que consiga trabalhar em um time multidisciplinar, que tenha sólidos conhecimentos de programação e bons fundamentos de sistemas operacionais e redes.

Você fará parte de uma equipe que desenvolve soluções de automação de alto impacto na operação de TI de nossos clientes.

Sua maior responsabilidade será atuar com interfaces desde o desenho, passando pela implementação do HTML, CSS, JavaScript e integrações com backend.

É fundamental que você goste de compartilhar o seu conhecimento com outras pessoas. Ser curioso e autodidata são características bem vindas.

O trabalho poderá ser realizado totalmente remoto, dentro de horário comercial e seguindo o horário de Brasília, com ocasionais viagens a São Paulo, Brasília, Campinas e Rio de Janeiro para encontros com a equipe ou clientes, custeados pela empresa. Portanto, é fundamental ter disponibilidade para viajar.

Nós não perguntamos pretensão salarial. Se identificarmos que você é a pessoa que queremos ter em nossa equipe, faremos uma proposta financeira condizente dentro da faixa salarial inicial da empresa.

Benefícios
   
   - Regime de contratação CLT;
   - Salário inicial entre R$ 2.000,00 e R$ 3.000,00;
   - Plano de saúde e odontológico Bradesco Top Nacional Top para o titular e seus dependentes;
   - Vale refeição de R$ 400,00;
   - Vale alimentação de R$ 600,00;
   - Seguro de vida corporativo custeado pela empresa;
   - Verbas para investimento em treinamentos e educação;
   - Acesso aos treinamentos da empresa sem custos;
   - Prêmio de participação nos resultados;
   - Prêmio quando se completa aniversário de empresa;
   - A empresa fornecerá um laptop com as seguintes configurações: Dell Inspiron 14 5480 (Core i7-8565U, RAM 16GB, GeForce MX150, HDD 1TB, SSD 128GB, Full HD);

Por que trabalhar na Instruct?
   
   - Ambiente de trabalho amigável, inclusivo e seguro;
   - Resolvemos problemas desafiadores e em larga escala para nossos clientes;
   - Incentivos para participação em eventos, cursos e palestras;
   - Usamos ferramentas e métodos inteligentes e inovadores para interagir com nosso time;
   - Cultura blameless;
   - Café de qualidade!

O que esperamos de você?
   
   - Esperamos que nos ajude a melhorar a performance dos nossos clientes;
   - Esperamos que você consiga se relacionar bem com o seu time de trabalho, que saiba fazer parte do time, respeitar o time, dividir e compartilhar responsabilidades, acertos e aprendizados;
   - Esperamos que você possa ir além, propondo, criando, mudando, construindo, crescendo e evoluindo junto conosco;
   - Queremos que você agregue valor ao nosso time e a nossa organização, e queremos que a nossa organização agregue valor a você;

Conhecimentos e experiências fundamentais:
   
   - HTML 5 e noções de acessibilidade;
   - CSS 3 e Flexbox;
   - Javascript (ES6+);
   - Noções básicas de UI/UX;
   - Integração de aplicações via APIs REST;
   - Uso de Git para versionamento de seu código;

Conhecimentos diferenciais:
   
   - Desenvolvimento de algum projeto Frontend sem a utilização de libraries ou frameworks;
   - Uso de aplicações visuais como Figma, Sketch ou Illustrator;
   - Automatizadores e Bundlers: Gulp, Webpack, etc;
   - SCSS e BEM;
   - Experiência com Vue.js;
   - Ferramentas de testes JavaScript: Jasmine, Jest ou Mocha;

Tecnologias e métodos

Estas são tecnologias, métodos e conceitos que utilizamos em nossos projetos, o conhecimento destes será um diferencial apreciado:
   
   - Fundamentos de modelos ágeis como Kanban e Scrum;
   - Fundamentos do conceito testes unitários;
   - Analise e desenho de interfaces utilizando Figma;
   - SCSS e BEM;
   - Vue.js e Node.js;
   - GitLab CI;
   - Participação em projetos Open Source;

Informações adicionais
   
   - Local: Remoto com encontros presenciais
   - Horário: Comercial das 9h às 18h (40h semanais)

Para participar do processo

Enviar um e-mail com CV para jobs@instruct.com.br com assunto "Desenvolvedor(a) Frontend Junior".

Labels
   
   - CLT
   - Júnior
   - Remoto

**Comment by rodgeraraujo** [comment]
Enviado!

**Comment by GustavoPrizon** [comment]
Cv enviado!

**Comment by thiagotcs** [comment]
Enviado!

**Comment by Qnedy** [comment]
CV enviado!

**Comment by FabianoLothor** [comment]
Possuem vaga para Pleno ou Sênior?

**Comment by Qnedy** [comment]
Algum prazo para feedbacks? Enviei ja tem 11 dias o CV.

**Comment by iassia** [comment]
> Possuem vaga para Pleno ou Sênior?

infelizmente, no momento não

**Comment by Qnedy** [comment]
Fico no aguardo então. Vlw Fábio.

**Comment by iassia** [comment]
> Algum prazo para feedbacks? Enviei ja tem 11 dias o CV.

O processo está em andamento, enviamos uma resposta automática para todos os currículos recebidos com sucesso. Caso você seja selecionado nossa equipe entra em contato para dar prosseguimento ao processo :)

**Comment by Qnedy** [comment]
Entendi, no caso não recebi esse email de resposta automático não. Posso enviar novamente?

**Comment by iassia** [comment]
> Entendi, no caso não recebi esse email de resposta automático não. Posso enviar novamente?

Não precisa, confirmei aqui e seu curriculo já foi recebido. :+1:

**Comment by Qnedy** [comment]
Ah ok. Vlw, Fábio.

**Comment by thiagotcs** [comment]
Ola Boa Tarde! Também não recebi nenhuma confirma de recebimento de currículo.

**Comment by GustavoPrizon** [comment]
Boa tarde!
Faz 14 dias que enviei o cv e não tive nenhum Feedback

**Comment by EzequielBrilhante** [comment]
Boa tarde, @iassia , tbm não recebi nenhum feedback. Algum retorno?

**Comment by iassia** [comment]
Boa tarde pessoal
São muitos curriculos para serem avaliados, a equipe esta fazendo a primeira triagem nesse momento, algumas pessoas já foram chamadas para a primeira conversa.

Confirmando: não estamos enviando resposta automática, os candidatos selecionados para prosseguir serão contactados diretamente.

Infelizmente não consigo passar um prazo no momento, fazemos o processo com muita cuidado dando atenção a todos os currículos recebidos :)

**Comment by willianmonteiro** [comment]
@iassia Olá, a vaga ainda está aberta? Enviei o CV.. 
Obrigado.

**Comment by iassia** [comment]
> @iassia Olá, a vaga ainda está aberta? Enviei o CV..
> Obrigado.

Olá, a vaga está aberta sim!
Todos os currículos serão avaliados, porém dado o volume só conseguimos dar um feedback para um primeiro contato aos que passem nos nossos critérios iniciais e estejam alinhados com os requisitos da vaga.

**Comment by willianmonteiro** [comment]
> > @iassia Olá, a vaga ainda está aberta? Enviei o CV..
> > Obrigado.
> 
> Olá, a vaga está aberta sim!
> Todos os currículos serão avaliados, porém dado o volume só conseguimos dar um feedback para um primeiro contato aos que passem nos nossos critérios iniciais e estejam alinhados com os requisitos da vaga.

Ah sim, tranquilo. Só questionei pois vi que a issue já tem 1 mês praticamente e enviei o CV a poucos dias. 

Obrigado pelo retorno.

**Comment by rhanielvalle** [comment]
Enviado pessoal, valeu! Sucesso

**Comment by simaodeveloper** [comment]
Aplicado!

**Comment by ngustavo** [comment]
Até tu, Simão?! hahaha

**Comment by geovanipfranca** [comment]
CV Enviado

**Comment by guiananias** [comment]
CV Enviado!

**Comment by maxleon52** [comment]
CV enviado.

**Comment by Acastelo** [comment]
Enviado!

**Comment by thiagosullivan** [comment]
CV enviado!

**Comment by rodrigorhas** [comment]
Enviado! Empresa super transparente!

**Comment by jgalmeida93** [comment]
Enviado!

**Comment by flipChandler** [comment]
Essa vaga está em aberto ainda?
