### ISSUE TITLE
[São Paulo] Front-end Developer JR e PL na Metasix

### ISSUE THREAD

**Issue by alegalliard** [frontendbr/vagas#2737]
## Descrição da vaga

Procuramos uma boa pessoa de front-end com um perfil curioso e que goste de desafios. Além de dar manutenção nos projetos que já estão no ar, temos um styleguide feito pela nossa designer para transformar em código e mudar a cara do nosso sistema e formular novas propostas junto com a equipe do back-end.

Temos também um projeto de um agendador engrenando, é como uma startup dentro da Metasix e que também precisa de reformulação tanto do front-end quanto do back-end, prato cheio para profissionais criativos. 

## Local

Metasix Tecnologia fica na região da Paulista, próximo ao metrô Consolação em São Paulo.

## Benefícios

- Plano de saúde;
- VR ou VA;
- VT;

#### Diferenciais

- Horário flexível;
- Temos um ambiente super descontraído (super mesmo! Até os mais tímidos se transformam);
- Temos um PS4 pra quando você precisar espairecer;
- Temos bolos aleatórios e festinhas para os aniversariantes do mês;
- Temos a quarta-feira da fruta pra incentiva bons hábitos alimentares;
- Massagens todas as sextas;
- E temos também a dona Edi, que além de ser um doce de pessoa e peitar até os peixes grandes da empresa, mantém a garrafa de café sempre cheia, faz chá natural, pipoca todas as quintas e às vezes até uns mousses.

## Requisitos

**Obrigatórios:**
- JavaScript (Angular ou React);
- HTML;
- CSS3; 
- Git;
- SASS;

**Desejáveis:**
- Node;
- PHP;
- Docker;

**Diferenciais:**
- Grunt, Gulp ou Webpack;
- Python (para Plone);
- Conhecimento em UX ou usabilidade;
- Java;

## Contratação

CLT, salário a combinar dependendo do nível

## Nossa empresa

A Metasix é uma empresa com um ótimo ambiente que presta serviços para importantes orgãos públicos e prefeituras das maiores cidades do Brasil, além de diversos clientes do setor privado.

## Como se candidatar

Por favor envie um email para alessandra.souza@metasix.com.br com seu CV anexado ou link Linkedin com o assunto: Vaga Front-End

## Tempo médio de feedbacks

Enviaremos um teste para os candidatos e após isso, costumamos enviar feedbacks em até 1 semana após cada processo.
E-mail para contato em caso de não haver resposta: alessandra.souza@metasix.com.br

## Labels

- CLT
- Pleno
- Júnior
- Angular
- Alocado

**Comment by GustavoPrizon** [comment]
Cv enviado!

**Comment by alegalliard** [comment]
Hoje enviaremos aos candidatos o teste via e-mail. A vaga ainda está aberta para os que quiserem concorrer (:

**Comment by AndersonKV** [comment]
> Hoje enviaremos aos candidatos o teste via e-mail. A vaga ainda está aberta para os que quiserem concorrer (:

aceitam remoto?

**Comment by alegalliard** [comment]
Infelizmente não.

**Comment by alegalliard** [comment]
Sensacional, recebemos vários CVs e já estamos fechando. 
Agradeço a todos que enviaram!
