### ISSUE TITLE
[São Paulo] Front-end Developer na BRQ Digital Solutions

### ISSUE THREAD

**Issue by ingridamr** [frontendbr/vagas#2739]
[São Paulo] Front-end Developer na BRQ Digital Solutions

Front-End Developer Sênior

## Descrição da vaga
Forte experiência com: JavaScript, AngularJS, ReactJs, Angular 2+ 

## Local - Av. Paulista/SP

Escritório, São Paulo - Paulista

## Benefícios

- Plano de saúde
- Seguro de vida
- VR 

- Auxílio creche
- Assistência Odontológica
- Previdência Privada
- VA
- VT
- Programa de Incentivo à Certificações
- Gympass

#### Diferenciais

- Oportunidade de trabalhar numa célula totalmente digital e com tecnologias de ponta; - Possibilidade de Home Office alguns dias da semana; 
- Fácil acesso - Paulista/SP 
- Possibilidade de internalização no cliente; 
- Ambiente descontraído; 
- Contratação CLT com ótimos benefícios

## Requisitos

**Obrigatórios:**
- Experiência/ domínio em Javascript, React e Angular

**Desejáveis:**
- JAVA

**Diferenciais:**
- Projeto da área Digital, projeto novo, cliente do setor de Turismo

## Contratação

CLT Full 

## BRQ Digital Solutions
A BRQ é um dos 50 Melhores Lugares para trabalhar segundo Glassdoor!

## A BRQ tem paixão por transformar negócios com tecnologia, e há 26 anos apoia a digitalização de bancos, seguradoras, empresas de telecomunicações e outras empresas líderes em seus setores.
Os serviços e soluções oferecidos pela BRQ, aceleram a Transformação Digital em seus clientes e estão estruturados para suportar todo o ciclo de evolução:
- Pensar e Desenhar 
- Aportar tecnologia
- Construir e Evoluir
Unindo o Negócio do Cliente com a Tecnologia Correta e uma nova Cultura que elimina desperdícios, acelera a comunicação e otimiza a produtividade, a BRQ Digital Solutions apoia seus clientes para que seus negócios cresçam exponencialmente.

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: iribeiro@brq.com

## BRQ

- Alocado
- CLT
- Sênior

**Comment by lucasferreiralimax** [comment]
Currículo enviado :+1:
