### ISSUE TITLE
[Volta Redonda/RJ] Desenvolvedor(a) Front-end na Agência Tática Web

### ISSUE THREAD

**Issue by marcelabomfim** [frontendbr/vagas#274]
## Descrição da vaga

A Agência Tática Web está em busca de um(a) Desenvolvedor(a) Front-end para complementar o time, essa pessoa deverá ser capaz de estruturar o seu código a partir do PSD entregue pela equipe de designers, sempre pensando na responsividade do mesmo (utilizando-se ou não de frameworks).

## Local

Escritório, Volta Redonda/RJ - Vila Santa Cecília

## Benefícios

- Contratação imediata
- Contato direto com o CEO da empresa
- Ambiente descontraído
- Pessoas bacanas :P
- Refeitório no local

## Requisitos

**Obrigatórios:**
- HTML / CSS / Javascript (jQuery)
- Experiência com sites responsivos
- Habilidades com Photoshop

**Desejáveis:**
- Conhecimento básico em PHP
- Conhecimento básico em MySQL

**Diferenciais:**
- Noções de SEO

## Contratação

CLT

## Como se candidatar

Enviar email com assunto [Vaga Front-end #Github] para marcela@taticaweb.com.br com seu CV em anexo.

**Comment by ribeiroevandro** [comment]
Se rolasse remoto, apesar de morar relativamente perto, não tenho como mudar nesse momento...

**Comment by ivosoares** [comment]
enviado !

**Comment by marcelabomfim** [comment]
Já preenchemos a vaga.
Obrigada.
