### ISSUE TITLE
[São Bernado do Campo] Front-end Developer na Designhope

### ISSUE THREAD

**Issue by rogeriorioli** [frontendbr/vagas#2740]
## Descrição da vaga

Estamos montando um time , inicialmente estamos precisando de freelancers.
Desenvolvimento HTML , CSS , JS ,  Wordpress,  React e E-mail Marekting com MJML.

## Local

Remoto ou Escritório, São Bernado do Campo - Baeta (próximo ao supermedado Sonda)

## Benefícios

- horario flexivel
- cursos na udemy que desejar
 - Se desejar Home Office , Pelo menos  1 ou 2 x por semana na empresa para entrega de sprint e pegar novas demandas . 

## Requisitos

- PHP  
- WORPRESS
- REACT
- GATSBY 
- JAVASCRIPT 
- HTML
- CSS
- SASS
- Styled Components
- Gulp
- Consumo de API e GraphQL

**Desejáveis:**

- Um bom html , css e javascript e saber desenvolver um thema wordpress do zero o restante aprende conosco , se tiver uma base em framework e Blibliotecas ajuda demais . 

**Diferenciais:**

- Ter vontade de aprender e visão de mercado (criatividade)

## Contratação

PJ a combinar

## Nossa empresa

Somos uma produtora web que atendemos agencias, consultórias e temos projetos com clientes da casa também. Usamoss , Wordpress,  React , Gatsby e Vue , Nodejs, Firebase, MJML .

Fazemos muita coisa bacana desde de uma Simples, Landing Page , Peças de recomendação e retaguet em e-commerce, email MKT e até grandes portais .

Nosso objetivo além de uma boa entrega e garantir e gerar novas oportunidade de negocios para nossos clientes. 

Estamos no Wework em São Bernado do Campo que é um ambiente bem legal com Café a vontade , choop , mesa de pingue-pongue, eventos e workshops promovidos pela comuidade.

## Como se candidatar

Por favor envie um email para rogerio@designhope.com.br com seu CV anexado - enviar no assunto:  
FREELA FRONT - FRONTENDBR

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.

## Labels

- Freela
- PJ
- Pleno
- Remoto
- Alocado

**Comment by renanmurilo** [comment]
Currículo enviado

**Comment by rogeriorioli** [comment]
Pessoal que me enviou o cv estou separando é irei chamar para um call depois do dia 20 , grato a todos , quem eu não selecionar irei informar mas os cvs ficaram salvos para um momento oportuno
