### ISSUE TITLE
[Remoto] Front-end Developer na Changelogfy

### ISSUE THREAD

**Issue by paulocastellano** [frontendbr/vagas#2745]
## Descrição da vaga

Estou reescrevendo muitas coisas no [Changelogfy.com](https://changelogfy.com), e preciso de ajuda nesse processo.

Você vai aprender muitas coisas nesse trabalho, não somente front-end mas como negócios também, vai trabalhar diretamente comigo.

Porém você precisa ser uma pessoa que goste de aprender e próativo!

Nossa stack atual é AWS, Laravel, VueJS, SCSS, MySQL, Nuxtjs, Dynamodb e muito mais.

## Local
Remoto

## Benefícios
- Horário flexível
- Cursos na Udemy que desejar
- Possibilidade de Equity (ser sócio)

## Requisitos

**Obrigatórios:**
- CSS
- HTML
- Javascript puro
- Ter alguma experiência com VueJS (preferência), React ou Angular
- Npm
- Webpack
- Axios

**Desejáveis:**
- [Nuxtjs](https://nuxtjs.org/)
- Banco de dados (Mysql / Pgsql)
- Sass
- [GitLab](https://gitlab.com/)
- Unit test

**Diferenciais:**
O [Changelogfy.com](https://changelogfy.com) é uma empresa global e remota, você vai ter a oportunidade de trabalhar com um produto 100% em inglês (apesar de não ser requisito, pois atualmente todos os funcionários são brasileiros.)

## Contratação
PJ a combinar

## Nossa empresa
O [Changelogfy.com](https://changelogfy.com) é um software para changelog de produto ou servico. Facilitamos o processo de informar e coletar feedback dos usuários

## Como se candidatar

Por favor envie um email para paulo@changelogfy.com com seu CV ou LinkedIn - enviar no assunto: Vaga Desenvolvedor

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: paulo@changelogfy.com

## Labels
- Remoto
- PJ
- Estágiario
- Junior

**Comment by EzequielBrilhante** [comment]
Bom dia, o e-mail para enviar o CV paulo@123changelogfy.com, está dando como errado.

**Comment by paulocastellano** [comment]
> Bom dia, o e-mail para enviar o CV [paulo@123changelogfy.com](mailto:paulo@123changelogfy.com), está dando como errado.

Olá @EzequielBrilhante, me desculpe o e-mail correto é paulo@changelogfy.com (já arrumei a issue)

**Comment by EzequielBrilhante** [comment]
De boa, CV enviado!

**Comment by paulocastellano** [comment]
Pessoal, como a demanda de currículos foi muito alta, estou encerrando o recebimento de cv's.

Muito obrigado a todos que enviaram, estou marcando as entrevistas e dando os feedbacks.
