### ISSUE TITLE
[São Paulo] Desenvolvedor Freelancer - Angular 2 - LolDesign

### ISSUE THREAD

**Issue by fetraks** [frontendbr/vagas#275]
## Descrição da vaga

Desenvolvedor freelancer front-end / Angular 2.

## Local

Remoto e Escritório, São Paulo - Mooca

## Benefícios

- A combinar

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com front-end

**Desejáveis:**
- conhecimentos em ruby on rails

**Diferenciais:**
- projetos opensource

## Contratação

PJ a combinar

## Nossa empresa

Somos uma Software House localizada em São Paulo – SP. Nosso foco atual é desenvolver software para StartUP.

## Como se candidatar

Por favor envie e-mail para contato@loldesign.com.br com assunto (Desenvolvedor Angular 2)

**Comment by DaniloAgostinho** [comment]
Essa vaga esta muito exigente, observando a Time aqui.. Até agora nenhuma vaga.

**Comment by rands0n** [comment]
@LFeh tem duas labels de remoto, seria bom se tivesse `remoto - total` apenas para vagas que aceitem o remoto 100%, e `remoto` para aquelas parciais.

Hoje fica complicado achar qual é qual, a ñ ser q vc entre em cada uma e veja por si só.

O que acha?

**Comment by LFeh** [comment]
É que essa issue é antiga :)

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
