### ISSUE TITLE
[Remoto] [São José dos Campos/SP] Front-end Developer Pleno na Cuponomia

### ISSUE THREAD

**Issue by rafaelpradella** [frontendbr/vagas#2750]
## Descrição da vaga
O Cuponomia, empresa com mais de 7 anos no mercado de cupons de desconto e cashback está procurando uma pessoa para compor a nossa equipe de Design/Front-End por trabalho remoto, ou no nosso escritório em São José dos Campos - SP ([ver no Maps](https://bit.ly/2ZCeDw8))

Você vai contribuir para os nossos produtos web entregando protótipos e novas funcionalidades sempre se preocupando com a qualidade do código, impacto na performance da aplicação e SEO e ajudar no processo de aprendizado dos profissionais mais iniciantes da equipe com bons Code Reviews.

Tem interesse? Mande um email para `rh@cuponomia.com.br` com o seu currículo e portfólio/link do GitHub.

> Se não tiver um portfólio montado, pode mandar no corpo do email links para projetos que você contribuiu, **explicando a sua participação**: seja freelancer, projeto da faculdade, etc.

## Benefícios
- Plano de saúde
- Seguro de vida
- VR de R$ 26/dia
- Cashback em dobro
- Vale Transporte (para a vaga presencial)

#### Diferenciais
- Horário Flexível
- Cota anual pra você utilizar com cursos, eventos, livros, palestras etc.
- Sessões de feedbacks frequentes

## Requisitos
**Obrigatórios:**
- GIT
- Escrever HTML semântico e noções sólidas de SEO;
- Boas noções de layout, CSS sem frameworks e design responsivo;
- Javascript ES6+
- jQuery e manipulação do DOM com JS puro cross-browser;
- Técnicas de otimização de performance (lazy-loading, code splitting, otimização de assets);

**Diferenciais:**
- Experiência prévia com desenvolvimento de projetos utilizando frameworks modernos (VueJS, React, Svelte, Angular, etc.);
- Animação SVG;
- Desenvolvimento de PWA;
- Desenvolvimento mobile (React Native, NativeScript, Flutter, etc.)
- Noções de Google Analytics (ler eventos, estatísticas de uso);

## Contratação
CLT a combinar

## Tempo médio de feedbacks

O prazo de resposta dos CVs e envio dos testes é de 2 dias úteis. Após isso se você não recebeu uma resposta, pode mandar um email para `rh@cuponomia.com.br`

## Nossa empresa

O Cuponomia é um site totalmente gratuito que oferece desconto através de cupons, cashback e ofertas das principais lojas online nacionais e internacionais. Nós negociamos com os melhores e-commerces e vasculhamos toda a internet para encontrar e oferecer cupons exclusivos, descontos especiais e cashback para nossos usuários.

[Sobre o Cuponomia](https://www.cuponomia.com.br/sobre)
[Perfil no Glassdoor](https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-Cuponomia-EI_IE2492233.13,22.htm)

**Comment by rodineicosta** [comment]
Enviado.

**Comment by humbertoromanojr** [comment]
meu currículo enviado

**Comment by JoaoVitorSPereira** [comment]
Enviado.
