### ISSUE TITLE
[São Paulo] Front-end Developer na Acesso Digital

### ISSUE THREAD

**Issue by recarol13** [frontendbr/vagas#2751]
## Descrição da vaga

Para você que gosta de desafios, estou buscando Front End Pleno ou Sênior.  para atuar em uma Fintech de Contas Digitais.
## Local

Pinheiros | SP

## Requisitos
- React
- TDD
- Conhecimentos em Microsserviços

## Contratação
- CLT

## Benefícios
- VT
- VR (R$30,00 ao dia)
- Auxillio Creche
- Bonus anual quando a empresa atinge as metas.

## Nossa empresa
Somos uma equipe apaixonada e comprometida em impactar positivamente o dia a dia de nossos clientes. Nascemos com o propósito de contribuir na transformação do mercado financeiro e evoluir a relação que as pessoas têm com o seu próprio dinheiro. Baseada em simplicidade e tecnologia, nossa missão é prover acesso às melhores possibilidades da vida. Hoje, com 8 anos e um milhão de contas ativas, somos líder no Brasil em emissão, processamento e gestão de cartões pré-pagos, administrando cartões de marca própria e CoBranded.
## Como se candidatar

Por favor envie um e-mail para renata.fernandes@kornferry.com com seu CV anexado.

## Labels

- Contratação direta
- CLT
- Sênior 
- Pleno
- React

**Comment by Edinhomarques** [comment]
Sei que na descrição só diz pleno, senior. Mas não tem vagas pra junior também não? Tenho interesse
