### ISSUE TITLE
[Remote] Front-End Developer at Neat

### ISSUE THREAD

**Issue by hugw** [frontendbr/vagas#2755]
## Descrição da vaga

The front end engineer at Neat will be responsible for helping build exciting new functionality on top of Neat's new React/Node-based web, desktop and mobile applications backed by distributed system's APIs.

The position will report to the technical lead, but will frequently engage with other members of the development/QA staff, as well as with product and UX teams, to help scope, design, and estimate features and enhancements being considered for prioritization.

### Responsibilities

The primary responsibility for the role will be to develop new features and user experiences in our next-generation web, desktop, and mobile applications, working closely with QA to ensure a quality end-user experience.  In conjunction with that, the role will also involve:
- Coordinating with Product and UX teams to help scope, design, and estimate features and enhancements being considered.
- Ensuring clean coding practices and patterns are used through collaborative code design and review.
- Monitoring crash reporting and performance/analytics services to identify trends or spikes of importance or concern.

### Qualifications

- 3+ years of development experience on JavaScript applications using any modern framework (React, Angular, Backbone, etc.) with emphasis on the latest ECMAScript standards.
- 2+ year of experience with React/Redux in a web production setting (experience with Apollo client is a plus).
- Experience working with REST APIs and debugging API responses (Sockets/GraphQL is a plus).
- Experience with Node.js and maintaining NPM packages.
- Experience with SASS, and LESS preprocessors.
- Knowledge of the latest HTML and CSS standards and patterns.
- Experience writing unit/snapshot tests using Jest.
- Some experience building React Native and Electron apps.
- Some experience with Express.js (Mongoose ODM is a plus).
- Familiarity with development/build tools such as Webpack, Babel, Lerna, etc.
- Experience with agile methodologies.
- Ability to work well in a distributed team.
- Strong writing and communications skills.
- Good at time management and multitasking.
- Proactive mindset with a passion for making things better.
- Willingness to learn new technologies.

## Local

Remoto. Início imediato.
Preferencialmente na timezone brasileira ou próximo. Estamos situados na Filadélfia - US (EST).

## Requisito

- Inglês avançado.

## Contratação

Contrato via PJ ou Pessoa física, não faz diferença para nós. Pagamento em dólares americanos.

## Como se candidatar

Por favor envie um email para hcorrea+frontend@neat.com com o link do seu Github e Linkedin.
Enviar no assunto: _Vaga FE_
Se possível coloque sua pretensão salarial (em USD) e disponibilidade para começar.

## Labels

- Remoto
- Contrato
- PJ
- PF
- Pleno
- Sênior

**Comment by emirdeliz** [comment]
Inglês fluente?

**Comment by hugw** [comment]
@emirdeliz não precisa ser fluente. Escrita é desejável avançado e conversão pelo menos intermediário. Tendo dito isso, é importante ressaltar que todas as etapas da entrevista é na lingua inglesa.

**Comment by hugw** [comment]
Oi pessoal, considerando que recebemos uma quantidade significativa de candidatos, e como estamos nas etapa final de entrevistas, vou fechar a vaga.
