### ISSUE TITLE
[Curitiba] Front-end Developer React.JS na Plastika TWY

### ISSUE THREAD

**Issue by renann** [frontendbr/vagas#2757]
##Descrição da vaga
Front-end Developer Pleno para integrar time de desenvolvimento de projetos ágeis.
Se você é apaixonado por desenvolvimento (e por JavaScript), se mantém sempre atualizado esta sempre buscando novos desafios, essa vaga é para você.

Na Plastika TWY você poderá participar de projetos dos mais diferentes segmentos. Nosso foco é desenvolver aplicações factíveis, valiosas, usáveis e com aquele "UAU!"

##Local
Remoto

##Requisitos Obrigatórios:
Estamos em busca de um dev PLENO, com os seguintes domínios mínimos:
- Processadores SAAS
- ReactJS
- Padrões HTML CSS

##Desejáveis:
Conhecimentos em framework Laravel

##Diferenciais:
Oportunidade de participação dos lucros
PJ a combinar

##Nossa empresa
Ao longo de 13 anos a Plastika TWY lançou diversos projeto digitais para o mais diversos segmentos por todo o mundo. Pudemos ajudar muita gente e hoje vemos muitos dos nossos parceiros crescerem e se tornarem referência em seu segmento. Utilizamos do pensamento ágil e do desenvolvimento enxuto oportunizando que pessoas ou empresas validem sua ideia e construa futuros.

##Como se candidatar
Por favor envie um email para hiring@plastikastudio.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Developer

##Tempo médio de feedbacks
Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: hiring@plastikastudio.com.br

##Labels
PJ
Pleno
Remoto

**Comment by nandomoreirame** [comment]
@renann vocês precisam de um **front-end pleno** ou de um **fullstack**?
Acredito que **PHP, MySQL e Node.js** não são **Requisitos Obrigatórios** para um **front-end pleno**, front-end é quem cuida do que vai no _client side_ 😃

**Comment by renann** [comment]
> @renann vocês precisam de um **front-end pleno** ou de um **fullstack**?
> Acredito que **PHP, MySQL e Node.js** não são **Requisitos Obrigatórios** para um **front-end pleno**, front-end é quem cuida do que vai no _client side_ 😃

Alterei o issue para ficar no padrão. Obrigado.

**Comment by marcelomds** [comment]
Enviado!

**Comment by FabianoLothor** [comment]
O cara quer pagar R$ 3.000,00 por um profissional Pleno PJ por 40h/s.

Boa sorte para o selecionado. Eu passo.

**Comment by renann** [comment]
Obrigado pelo retorno.

Abs,
Renann Corrêa

Em seg, 6 de jan de 2020 20:37, Fabiano Carneiro de Oliveira <
notifications@github.com> escreveu:
