### ISSUE TITLE
[Remoto] Front-end Developer na Vigia de Preço

### ISSUE THREAD

**Issue by gislainy** [frontendbr/vagas#2759]
## Descrição da vaga

Atuar em correções, melhorias nos projetos já existentes e novos projetos do grupo Vigia de Preço, com atenção especial na qualidade do código. Buscamos um profissional com brilho nos olhos e que esteja disposto aprender e compartilhar conhecimento e experiência conosco, participando desde o processo de arquitetura, análise, evolução até a produção das nossas soluções. 

Se você adora desafios, tem fome por aprendizado e gosta de ambientes descontraídos com foco em evolução constante, venha trabalhar conosco! 

O trabalho será totalmente remoto com eventuais encontros durante o ano. 

Buscamos um profissional conhecimento e experiência comprovada com Javascript, ES6, VueJS e NuxtJS sendo desejável ter conhecimento em SEO. Vale ressaltar que o Vigia de Preço oferece excelentes oportunidades para crescimento dentro da empresa...Gostou? Então venha logo, pois estamos te esperando 😉.

## Local

Trabalho Remoto. Caso haja necessidade de reuniões de trabalho em um local específico, os custos com passagem, hospedagem e alimentação serão reembolsados pela empresa.

## Benefícios

- Férias Remuneradas de 15 dias (final do ano)

#### Diferenciais

- Horário flexível

## Requisitos

*Obrigatórios:*
- Javascript, ES6+ e Javascript Vanilla
- GIT (gitlab)
- VueJS e NuxtJS
- HTML5
- CSS3
- Sass ou Less ou Stylus
- Webpack
- APis REST
- SEO

*Desejáveis:*
- Otimização SEO
- Cache e performance
- Conhecimento de outros frameworks (React ou Angular)
- Testes automatizados

*Diferenciais:*
- NodeJS (Express)
- MongoDB
- Redis

### Seleção
Os candidatos devem preencher o formulário fornecendo: nome, email, repositório de codigo (github, gitlab ou afins), linkedin (usaremos para verificar experiências anteriores)
Formulário: https://forms.gle/J3EZN6PpMMGqzkox9 

### Entrevista
Será realizado entrevista inicial com duração de 10 a 20m em horário que o candidato tenha disponibilidade. Se você está trabalhando podemos marcar entrevista a noite sem problemas :)

### Teste 
O candidato irá participar de um teste prático para analisar os conhecimentos
O teste está disponível neste repositório https://github.com/vigiadepreco/vagas_frontend/blob/master/TESTE.md

### Feedback 
Será enviado feedback por e-mail e/ou uma chamada pelo Google Hangouts Meet.  

## Contratação

- PJ (Desejável que a PJ não seja MEI).
- Período de adaptação (experiência) de 3 meses.   
- Salário Inicial R$ 6.000,00. 
- Apresentando boa performance, a remuneração poderá ser reajustada de acordo com o desempenho e engajamento apresentado durante o período de adaptação. 

## Nossa empresa

O Grupo Vigia de Preço oferece uma série de soluções em tecnologia, com foco em performance para diversos segmentos.  O grupo conta com uma gama de produtos variados: um whitelabel de site de cupons; whitelabel de extensão Assistente de Compras para Google Chrome e Firefox; uma base de Push e parceria com grandes portais, disparadores de email, entre outras fontes de tráfego. Para saber mais sobre a empresa veja nossa [apresentação](https://vigiadepreco.com.br/index/img/apresentacao.pdf)

## Como se candidatar

- Os candidatos devem preencher o formulário fornecendo: nome, email, repositório de codigo (github, gitlab ou afins), linkedin (usaremos para verificar experiências anteriores)
- Formulário: https://forms.gle/J3EZN6PpMMGqzkox9 

## Labels
- PJ
- Pleno
- Sênior
- Remoto

**Comment by evertonProgramadorCriativo** [comment]
O teste ainda esta  aberto ? a vaga ainda esta aberta ?

**Comment by gislainy** [comment]
@evertonProgramadorCriativo a vaga continua em aberto. Iniciaremos a seleção na próxima semana.

**Comment by rhanielvalle** [comment]
Vocês tem algum posição aberta pra Júnior?

**Comment by gislainy** [comment]
@rhanielvalle infelizmente neste momento não estamos com vagas para júnior. 

Assim que tivermos com vagas será divulgado aqui :)

**Comment by gislainy** [comment]
As inscrições para o processo seletivo foram encerradas.
