### ISSUE TITLE
[Rio de janeiro/RJ] Front-end Developer na Órama Investimentos

### ISSUE THREAD

**Issue by gorifla** [frontendbr/vagas#2767]
### Sobre a Órama:
Criada em 2011 por profissionais experientes do mercado, foi a primeira plataforma digital de investimento no Brasil, premiada pela Amazon Web Services como uma das empresas mais inovadoras em serviços financeiros. 
Presente em todo o Brasil com uma estrutura 100% online, a Órama está comprometida com a entrega do melhor serviço para que o Brasileiro possa investir de forma consciente e transparente.

### Missão do desenvolvedor Front-end:
Ajudar no desenvolvimento e manutenção das nossas plataformas web.
Desafio: Ajudar no desenvolver e na manutenção de nossas plataformas, prezando a qualidade, performance e os prazos definidos.

### Plataformas disponíveis no momento:
- Área Aberta (web/responsivo) AngularJS
- Portal de Clientes (web/responsivo)AngularJS
- Plataforma de parcerias (web/responsivo)AngularJS

### Perfil do candidato:
- Precisa ter muita vontade de aprender;
- Ser comprometido com os prazos acordados;
Conhecimento minimo necessário: HTML, CSS, Javascript e Angular .

### 2 Vagas para Desenvolvedor Front-end Pleno
CLT + PL + Plano de Saúde + Refeição + Alimentação + Transporte

### Labels
- Pleno (2 vagas)
- CLT + PL + Plano de Saúde + Refeição + Alimentação + Transporte

Enviar currículo para igor.mantovano@orama.com.br

**Comment by felipefialho** [comment]
A vaga tá fora dos padrões de titulo, por favor seguir nosso template: https://github.com/frontendbr/vagas

**Comment by gorifla** [comment]
> A vaga tá fora dos padrões de titulo, por favor seguir nosso template: https://github.com/frontendbr/vagas



> A vaga tá fora dos padrões de titulo, por favor seguir nosso template: https://github.com/frontendbr/vagas

Fiz uma alteração solicitada, por favor, veja se fiquei seguindo o template
