### ISSUE TITLE
[Curitiba] Help Desk / Frontend Júnior

### ISSUE THREAD

**Issue by raloliver** [frontendbr/vagas#277]
O dev/designer vai trabalhar numa plataforma web com clientes em todo o Brasil.
Não vai virar noites trabalhando, nem ficar fazendo banco de horas!
O ambiente é bacana, somos "a família do amor", mas nosso trabalho é nosso trabalho, não nossa casa.

## Informações essenciais

- Dará suporte técnico aos clientes, bem como realizará ajustes e correções em landing pages criadas.
- Atendimento realizado através de tickets diários com prazo determinados. Quase sempre são necessárias implementações manuais usando linguagem de marcação (HTML/CSS) ou algumas das bibliotecas utilizadas (Bootstrap/jQuery) para correção de problemas ou melhorias pontuais em landing pages.
- Em alguns momentos, também realizamos atendimento através do Messenger/Grupo no Facebook, mas não é sempre. De preferência, é recomendado direcionar o cliente para algum ticket, mas sempre priorizando o bom atendimento e relacionamento.
- Além de trabalhar em conjunto com os times de design e atendimento, você vai ser o protagonista de decisões que podem impactar diretamente o negócio dos clientes que são atendidos.

## Local

Curitiba - PR no Parque De Software

## Benefícios

- Horário flexível ( 8 horas entre as 08:00 e 20:00 )
- As melhores máquinas sempre são dos devs
- Estar rodeado de pessoas que pensam da mesma maneira
- Oportunidade de crescimento num ambiente em constante mudança

## Níveis de Conhecimento de 1 a 5

- Comunicação Interpessoal (4)
- CSS (3)
- Bootstrap (3)
- HTML (2)
- SEO (2)

## Diferenciais

- Conhecimentos Básicos em Javascript (saber usar o console)
- Experiência de pelo menos 1 ano em ambiente organizacional, de atendimento a clientes e envolvimento direto em projetos, trabalhando com HTML e CSS.
- Proatividade, gostar de aprender, ter boa comunicação e carisma (bom humor, desinibido e ter empatia)
- Zona de conforto pra você é algo que não existe
- Perceber padrões facilmente

## Contratação

- CLT

## Nossa empresa

Depois de aprender muito em várias startups e sem reter clientes ou mesmo gerar leads, decidimos aprender a vender de verdade. O Marketing Digital abriu caminho para conexões incríveis, e escalar nosso negócio em direção ao sucesso ficou mais claro. No decorrer do caminho, descobrimos o que deveríamos fazer, não apenas pensando em números, mas em ajudar muitas pessoas a vender mais, com amor. 

**Nossa Missão** 
Facilitar e automatizar os processos de quem busca empreender de forma digital, através de plataformas que contém serviços integrados em constante inovação.

**Nossos Valores**
- Amor
- Comunicação
- Honestidade
- Liberdade
- Integração
- Inovação

**Não Toleramos**
- Procrastinação
- Falta de comprometimento
- Mentira
- Desrespeito
- Negligência
- Mi Mi Mi

## Como se candidatar

_Enviar email para para rh@leadlovers.com (A/C Israel Oliveira)_

**Comment by LFeh** [comment]
Pleno?

**Comment by raloliver** [comment]
Pode ser Júnior... mas em relacionamento com Humanos, deve ser pleno, rsrs.

**Comment by rhenanteix** [comment]
\o/ Interesse tenho sempre

**Comment by simaodeveloper** [comment]
Quem é de SP pode se candidatar?

**Comment by raloliver** [comment]
@rhenanteix manda o CV atualizado no email. Estamos pensando em deixar a vaga exclusiva pra mulheres, mas está difícil encontrar. A vaga é pra atendimento via ticket.

@simaodeveloper putz... estamos dando prioridade a quem já está aqui. Mas se vier por aqui esse mês podemos agendar uma entrevista.

**Comment by simaodeveloper** [comment]
@raloliver então é para a minha namorada ela é front-end, vou falar para ela.

**Comment by simaodeveloper** [comment]
@raloliver existe possibilidade de trabalhar remoto, ela ja tem expeciência em help desk, e tambem é front-end Júnior

**Comment by raloliver** [comment]
Putz... @simaodeveloper como tem um curva de aprendizado com a plataforma, o ideal é alguém alocado mesmo. Muda pra Curitiba, o custo de vida ta aqui: https://www.numbeo.com/cost-of-living/in/Curitiba Moro aqui a 5 anos e vim do interior da Bahia, claro que em outro contexto de país.

**Comment by evansantos** [comment]
@simaodeveloper aqui tem outro comparador de custo de vida https://www.expatistan.com/cost-of-living/comparison/sao-paulo/curitiba

**Comment by raloliver** [comment]
Pode fechar @LFeh. A vaga foi preenchida ontem, e conseguimos uma mulher =D

**Comment by LFeh** [comment]
Boa!
