### ISSUE TITLE
[São Paulo/SP] Developer React.JS na Eleven Financial Research

### ISSUE THREAD

**Issue by regular-alves** [frontendbr/vagas#2771]
## Descrição da vaga
O desenvolvedor(a) irá atuar na análise e desenvolvimento de novas funcionalidades com foco em performance, escalabilidade, segurança e qualidade para aplicações Web;
Será parte da rotina do desenvolvedor o levantamento de requisitos e integração de sistemas internos e de parceiros através de webservices REST.
Está no nosso DNA e procuramos desenvolvedores(as) com interesse por novas tecnologias e padrões de arquitetura 'fora da caixa', com a capacidade de trabalho com uma equipe multidisciplinar e com capacidade de compreender como seu trabalho afeta a empresa como um todo, muito além do código.
Prezamos por um  código limpo, de fácil compreensão e manutenção :)

## Local
Escritório, São Paulo - Berrini

## Benefícios
- Plano de saúde
- Assistencia odontológica
- VR de R$ 30/dia
- VT ou ajuda custo estacionamento

#### Diferenciais
- Massagem no escritório
- Gympass

## Requisitos

**Obrigatórios:**
 - Mínimo de 2 anos de experiência com desenvolvimento de aplicações mistas
 - Manutenção e criação de novas funcionalidades
 - Design Patterns
 - Boa capacidade de levantamento e análise de requisitos
 - JavaScript(ES6+), Redux e Webpack
 - Versionamento em GIT
 - React.js

**Desejáveis:**
 - React Native
 - Depuração de desempenho e benchmarking 
 - TDD
 - Node.js
 - PHP (Laravel)
 - Redux e Webpack;

## Contratação
CLT (enviar pretensão)

## Nossa empresa
Eleven é a maior casa de análises econômicas e financeiras independentes do Brasil. Com foco na qualidade, disciplina e responsabilidade, temos como missão auxiliar investidores locais e estrangeiros a tomarem as melhores decisões de investimento. Produzimos soluções de investimentos com respeito ao patrimônio do cliente, considerando suas características pessoais e ajudando-os a tomar as melhores decisões na hora de investir. 
Entregamos relatórios e soluções aos nossos clientes por meio de análises diárias, com teses que são discutidas entre toda a equipe, unindo a visão macro e micro. Além disso, oferecemos atendimento personalizado e acesso aos analistas para os nossos clientes.

## Como se candidatar
Envie o seu currículo junto com sua pretensão salarial para o email [rh@elevenfinancial.com](mailto:rh@elevenfinancial.com), com o assunto  **Developer React + Node Júnior**

## Labels
- CLT
- Pleno
- React.js

**Vaga permanece aberta:** _atualizado em 24/03/2020_

**Comment by joaopedrodev** [comment]
Olá queria saber se existe alguma para desenvolvedor Laravel PHP, também trabalho como desenvolvedor FullStack obrigado deixo meu numero do whatsapp 61999955207.

**Comment by regular-alves** [comment]
@joaopedrodev Sim, temos uma posição sim. Tanto JR, quanto PL.
https://elevenfinancial.com/vagas/programador-php-node-junior
https://elevenfinancial.com/vagas/programador-php-node-pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
