### ISSUE TITLE
[São Paulo] Front-end Developer na Vizir

### ISSUE THREAD

**Issue by apantaliao** [frontendbr/vagas#2776]
## Descrição da vaga

Vaga para trabalhar em dois projetos React e ReactNative na Vizir.  

## Local

Escritório, São Paulo - Centro

## Benefícios

- Plano de saúde
- Plano odontológico
- Seguro de vida
- VR de R$ 31,50 /dia pago em dinheiro
- Auxílio creche

#### Diferenciais
- O Computador depois de 2 anos é totalmente seu. 
- ambiente descontraído

## Requisitos

**Obrigatórios:**
- Conhecimento em React. 
- Manjar de teste unitário.

## Contratação
CLT, com opção de PJ. 

## Nossa empresa
Somos uma Software Studio, portanto você terá a oportunidade de trabalhar para clientes dos mais variados ramos e tamanhos, desde de start-ups que estão iniciando, até empresas estabelecidas  que faturam milhões por mês.

Temos 9 anos de vida, e durante esse tempo desenvolvemos mais de 200 projetos para nossos clientes, lançamos 3 produtos, fizemos mais de 27 talks, incontáveis Xepas e formamos um time ducaralho, que hoje são mais de 80 pessoas.

Temos projetos em JavaScript, C#, PHP e Ruby, desde aplicativos web com React Native, até micro-serviços com Node.js e .NET. Acreditamos em resolver o problema com a tecnologia mais adequada à necessidade e ao ambiente do cliente. Acreditamos que podemos ir muito mais longe, por isso fazemos este convite para que se junte ao nosso time de Nerds, Geeks e apaixonados por tecnologia e por atender bem nossos clientes.

Trabalhamos geralmente em projetos com equipes pequenas (média 4 pessoas), com entrega contínua e sprints de uma semana. Essas equipes são multidisciplinares e numa hierarquia flat, onde as pessoas se auto-organizam para a execução da sprint, com um facilitador para ajudar na comunicação com o cliente e o time em si a se auto-organizar.

O que procuramos?
Procuramos desenvolvedores ávidos por aprender, programar e resolver problemas. É importante o candidato ter uma boa base conceitual de arquitetura de software, orientação a objetos e Desenvolvimento Web. Com esta boa base, fica mais fácil aprender o que for preciso.

## Como se candidatar

Por favor se cadastre no link do [site da vaga.](https://recruiterflow.com/vizir/jobs/7?source=FrontEndBr) 

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: queroentrar@vizir.com.br

## Labels

- Alocado
- CLT
- PJ
- Pleno
- Remoto
- Sênior

**Comment by FabianoLothor** [comment]
Não ficou claro, a vaga é remota ou presencial?

No site fala que é presencial, aqui fala que é remoto.

**Comment by apantaliao** [comment]
Fabiano, boa tarde.

Temos os dois formatos. Temos mais vagas presenciais do que remotas, mas
atualmente temos 1/4 do time remoto.

Até mais,

André

Em qua, 1 de jan de 2020 13:29, Fabiano Carneiro de Oliveira <
notifications@github.com> escreveu:

**Comment by FabianoLothor** [comment]
Obrigado pelo esclarecimento André!

**Comment by ribeiroevandro** [comment]
Cadastrado

**Comment by lucasdaiki** [comment]
Trabalhei por 2 anos. Experiência muito boa!! Recomendo demais :)
