### ISSUE TITLE
[São Paulo] Front-end developer no Stoodi

### ISSUE THREAD

**Issue by thiagopadula** [frontendbr/vagas#2777]
## Descrição da vaga

Estamos procurando pessoas desenvolvedoras front-end com uma base sólida de HTML, CSS e Javascript (experiência com React ou outras bibliotecas JS populares é bem-vinda!) e que queiram muito aprender e contribuir para o nosso projeto de transformar o futuro dos brasileiros por meio da educação.

## Local

Escritório, São Paulo - próximo ao metrô Butantã

## Benefícios

- Vale refeição ou alimentação 
- Vale transporte
- Plano de saúde
- Plano odontológico
- Auxílio educação 
- Programa de remuneração variável

#### Diferenciais

- Ambiente ágil, descontraído e inovador em uma startup em crescimento.
- Horário flexível
- Dress code livre

## Requisitos

**Obrigatórios:**
- Conhecimentos sólidos de HTML, CSS e Javascript
- Ter muita vontade de aprender e compartilhar conhecimento

**Desejáveis:**
- Experiência com React

**Diferenciais:**
- Conhecimentos em GraphQL
- Experiência com testes

## Contratação

CLT

## Nossa empresa

O Stoodi transforma o futuro dos brasileiros por meio da educação. Somos uma empresa jovem com uma grande ambição de democratizar o acesso ao ensino superior para milhões de brasileiros. Fazemos parte do maior grupo de educação do mundo (sim, do mundo)! Combinando a agilidade, autonomia e alto crescimento de uma startup com a força e estabilidade de um gigante.

A nossa plataforma online de estudos serve mais de 100 mil exercícios e 50 mil vídeos por dia a alunos de todo Brasil! Além disso temos diversas outras soluções como simulados, planos de estudo personalizados, os apps mais bem rankeados de orientação vocacional, gabarito Enem, entre tantos outros.

Mas não são apenas os números que nos movem. Mudamos diariamente a vida de milhares de pessoas e acreditamos que ter um propósito de impacto é o que nos diferencia.

## Como se candidatar

Envie seu currículo pelo link nessa [página](https://jobs.kenoby.com/stoodi/job/pessoa-desenvolvedora-front-end-plena/5dc1e8a0272dbd20d9fea690)

## Labels

- Alocado
- CLT
- Pleno

**Comment by ribeiroevandro** [comment]
@thiagopadula me cadastrei pela plataforma, embora tenha solicitado anexar meu currículo, ainda foi preciso preencher dados que já consta nele, acabei ignorando e preenchendo apenas o que foi necessário, uma vez que tenho o CV anexado.

**Comment by thiagopadula** [comment]
@ribeiroevandro a plataforma é meio redundante mesmo. Desde que as informações estejam em algum lugar, não tem problema :)
