### ISSUE TITLE
[Fortaleza - CE] - Senior Front-End Developer na Delfos I.M.

### ISSUE THREAD

**Issue by samuellima06** [frontendbr/vagas#2778]
## Descrição da vaga

Estamos em busca de desenvolvedores experientes para desenvolver a nossa nova plataforma que conta com funcionalidades de Auto-ML (que testa e fornece modelos de Machine Learning em apenas um clique), um Marketplace de modelos de predição e ferramentas de self-service Machine Learning (onde o usuário cria e aplica seu próprio modelo de predição).

## Local

 A vaga é para Fortaleza, com a possibilidade de se tornar parcialmente remoto a partir do meio do ano de 2020.

## Benefícios

- Vale refeição
- assistência médica,
- horários flexíveis,
- auxílio transporte, 
- bônus semestral, e
- uma sala ampla com uma bela vista de Fortaleza

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com React.js
- 5 anos de experiência com desenvolvimento Front-End
- Comprometimento
- Vontade de aprender coisas novas
- Experiência com metodologias ágeis

**Desejáveis:**
- conhecimentos de back-end
- inglês avançado

**Diferenciais:**
- projetos opensource

## Contratação

CLT Full

## A Delfos Intelligent Maintenance

A **Delfos** é uma empresa de manutenção inteligente. Nós utilizamos algoritmos de Machine Learning para predizer falhas e otimizar a performance de ativos críticos como turbinas eólicas e sondas de perfuração de poços de petróleo.

Criada em 2017, a **Delfos** tem entre seus clientes grandes empresas como **Petrobrás**, **CPFL Energia**, **Votorantim Energia** e **Ocyan**. Atuamos em diferentes indústrias, como energia eólica, energia solar, petróleo e indústria de manufatura.

A sede de desenvolvimento da Delfos fica em Fortaleza, mas com uma base comercial em São Paulo, onde ficam a maioria de nossos clientes.

Já recebemos investimento de R$ 1,5 milhões de reais, e estamos em vias de finalizar uma rodada de investimento de R$ 5 milhões para iniciar nossa expansão internacional em Houston, nos Estados Unidos.

Utilizamos React.js e React Native para front-end e javascript e python para back-end. Toda a nossa infraestrutura é feita em cima de Kubernetes, utilizando microsserviços.

## Como se candidatar

Por favor envie um email para oportunidades@delfosim.com com seu CV anexado e com o assunto "Vaga Desenvolvedor Front-End Senior".

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.
E-mail para contato em caso de não haver resposta: contato@delfosim.com.

## Labels

- Alocado
- CLT
- React JS
- Sênior

**Comment by geekdoagrest** [comment]
Cara que massa ver uma vaga assim no meu ceará... hehehe muito feliz!

**Comment by samuellima06** [comment]
A vaga foi preenchida.
