### ISSUE TITLE
[Recife] Liferay - Front-End Developer

### ISSUE THREAD

**Issue by brunobasto** [frontendbr/vagas#278]
# Liferay - Front-End Developer

https://www.liferay.com/

## Description

Liferay Brazil is looking for a passionate Front-End Software Engineer to join our Front-End team in Brazil.

This position is for candidates who enjoy working in an international and multidisciplinary team, collaborating with engineers, UX designers and product managers from all around the world to build the required Front-End Foundation for outstanding and engaging web applications.

## Location

Casa Forte, Recife - Pernambuco.

## Benefits and Perks

- A place to be yourself, in which everyone can grow personally.
- Fast and powerful Mac or PC and a 24' monitor.
- Flexibility to work remotely when the task allows for it.
- Free healthy food in our kitchen. Tons of fruit, coffee, Tea or cookies diet...
- Health insurance for you and your family.
- Gympass
- No, we don't have an Xbox, PS4/4/X, but who need them when you enjoy your job so much ;)
- But above all, your happiness is important for the team. Money-back guarantee if you don't get enough daily smiles.

## Skills & Requirements

- Exceptional skills in JavaScript. Excellent knowledge of the basics of the language and the new standards.
- Passion about Front-End technologies. Up-to-date knowledge about the latest trends and frameworks in web development: Angular, React, ES2016, Web Components, Progressive Web Apps...
- Great knowledge about Front-End ecosystem and tooling: Babel, Browserify, Webpack, Rollup, npm, jspm, PostCSS, Grunt, Gulp...
- Great knowledge about HTML and CSS
- General knowledge in performance, accessibility and security for the web.
- Self-starter, quick learner, self-motivated, proactive beyond your duty.
- Good verbal and written communication skills in English.
- BS/MS in Computer Science or equivalent experience.
- Currently living or willing/able to relocate to Recife.

### An opportunity to change the world :)

Liferay, Inc. is a leading provider of enterprise open source portal and collaboration software products, servicing Fortune 500 companies worldwide, including Allianz, Barclay's, BASF, Cisco Systems, Lufthansa, T-Mobile, and the United Nations.

Working at Liferay is an opportunity to participate in an ethical, motivating, challenging and constantly expanding project within an international environment that offers the possibility developing a personal career according to your capabilities and preferences as part of the Liferay team.

## How to apply?

Send your application to http://app.jobvite.com/m?3j7Msiwr

## Notes

- Pleno / Júnior / Senior? 
Todas. Cada aplicação será avaliada individualmente.

- Salário?
A combinar.

**Comment by LFeh** [comment]
CLT? PJ?

**Comment by LFeh** [comment]
Olha ai @zenorocha, 😼

**Comment by brunobasto** [comment]
@LFeh CLT

**Comment by kivervinicius** [comment]
WOW, meu sonho

**Comment by samu101108** [comment]
PIZZA TIME!

Em 07/03/2017 17:03, "Bruno Basto" <notifications@github.com> escreveu:

**Comment by zenorocha** [comment]
Boa!

**Comment by gabriellamas** [comment]
Qual a chance de uma vaga de front pra quem não é tão bom quanto a vaga necessita mas que tmbm não é mais estagiário, tipo um meio termo querendo aprender 😀😀😀😀

**Comment by kvnol** [comment]
@gabriellamas eu sou exatamente esse cara, mas me inscrevi na vaga.

**Comment by samu101108** [comment]
Essa vaga foi publicada a mais de 6 meses! Ou não acharam alguém ou
esqueceram o anúncio no ar...

Em 07/03/2017 21:04, "Kevin Oliveira" <notifications@github.com> escreveu:

@gabriellamas <https://github.com/gabriellamas> eu sou exatamente esse
cara, mas me inscrevi na vaga.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/frontendbr/vagas/issues/278#issuecomment-284901887>,
or mute
the thread

**Comment by brunobasto** [comment]
@samu101108 Ainda estamos procurando desenvolvedores. Ainda temos 3 vagas em aberto para o cargo.

**Comment by LFeh** [comment]
Quer que feche a outra @brunobasto?

**Comment by brunobasto** [comment]
Por favor, @LFeh. Não achei o outro issue.

**Comment by netojose** [comment]
Caramba, 6 meses atrás do cara? Está difícil aparecer alguém? Todo mundo com medo?

**Comment by brunobasto** [comment]
A vaga foi preenchida, mas acabamos reaproveitando o anúncio do Jobvite para as novas vagas.

**Comment by guilherme6191** [comment]
Olá, @brunobasto. Tudo bom? Eu queria saber se a Liferay contrata remoto também ou tem outros escritórios para a área de tecnologia fora Recife. 
Valeu!

**Comment by joordas** [comment]
Opa @brunobasto beleza? Enviei minha candidatura com o currículo e cover letter! A vaga ainda está aberta? abs.

**Comment by brunobasto** [comment]
@guilherme6191, damos preferencia a contratar alocado.

@joordas, sim vamos analisar sua aplicação. Valeu por enviar!

**Comment by luizhenriquesoares** [comment]
@brunobasto, ainda está aberta ?

**Comment by netojose** [comment]
A issue está `closed`
