### ISSUE TITLE
[Belo Horizonte] Vue.js Developer na DialHost

### ISSUE THREAD

**Issue by flaviohcardoso** [frontendbr/vagas#2780]
## Descrição da vaga

Se você é um desenvolvedor faminto por desenvolver e otimizar produtos em um processo de ciclo contínuo e evolutivo, esta pode ser sua equipe.

Nós somos uma empresa que presa a evolução dos nossos produtos juntamente com um atendimento eficaz a todos os nossos clientes oferecendo soluções de datacenter que atendam suas necessidades de forma simples e transparente. Por isto estamos buscando um desenvolvedor que possua empatia e comprometimento para auxiliar nossos colaboradores e clientes discutindo e buscando as melhores opções para garantir uma experiência excepcional no atendimento ao cliente. 

Acreditamos que em nosso time, você não trabalhará sozinho e que um problema nunca é somente de um colaborador, ele é de todos da empresa.

## Local

Escritorio em Belo Horizonte, Bairro California

## Benefícios

Não ter chefe :)
Uma equipe de alto nível, comprometidas e colaborativa.
Salário compatível com o mercado.
Plano de Saúde.
Vale Refeição.
Vale Transporte.
Lanche na empresa.
Ambiente agradável.
Horário Flexível.
Estilo próprio para trabalhar.
Auxilio para pagar sua faculdade.
Diversos cursos online disponibilizados pela empresa.

## Requisitos

- HTML, CSS, Sass e JavaScript;
- Frameworks frontend (Vue.JS);
- Conhecimento basico em PHP;
- Ser focado em objetivos e resultados.
- WebPack para automação na compilação de assets;
- Experiência com utilização do Git;
- Proatividade e dinamismo ;)
- Ter carinho e ser apaixonado pelo seu trabalho.

## O que pode fazer diferença

- Inglês Intermediário;
- Noções de otimização de performance web;
- Otimização de código para SEO;
- Laravel;

**Para esta vaga iremos aplicar um teste simples e prático para que você possa demonstrar suas qualidades.**

## Contratação

CLT ou PJ (Presencial)

## Como se candidatar

https://www.dialhost.com.br/trabalhe-conosco/vaga/vue-js-developer/

## Labels

- CLT
- PJ
- Estágio
- Júnior
- Pleno
- Presencial

**Comment by joaopedrodev** [comment]
Olá queria saber se existe alguma para desenvolvedor Laravel PHP, também trabalho como desenvolvedor FullStack obrigado deixo meu numero do whatsapp 61999955207.
