### ISSUE TITLE
[Remoto] Front-end Developer na Agência Bein

### ISSUE THREAD

**Issue by yanbein** [frontendbr/vagas#2787]
## Descrição da vaga

Nós somos uma agência de desenvolvimento digital que está crescendo rapidamente. Estamos em busca de desenvolvedores para integrar nosso time de freelancers remotos. Você terá autonomia para decidir o melhor curso de ação em cada projeto e ter parte na decisão de quais tecnologias melhor se adaptam a cada necessidade.

Buscamos por pessoas flexíveis, introvertidas  (sério! todos nós somos parte do mesmo time por aqui e entendemos os problemas), de qualquer gênero e orientação sexual e que, principalmente, tenha amor por tudo que faz. Queremos sua personalidade dentro dos projetos.

Você é uma pessoa dedicada e quer montar um portfólio invejável? Seu lugar é conosco.

Método de Trabalho

1. Escopo detalhado com todas as features exigidas no projeto
2. Valores, prazos e meios de pagamento (do projeto) fechados contratualmente
3. Ao invés de ter um horário fixo de trabalho, você terá um prazo para entrega de cada feature (que pode ser definido por você) e poderá trabalhar no horário que melhor te servir
4. Controle de entrega de trabalho através de; Trello e GitHub
5. O(a) desenvolvedor(a) receberá o design pronto, de todos os projetos em que trabalhar, mas é livre para fazer boas modificações 🙂 

Responsabilidades

1. Desenvolvimento front-end e back-end com código limpo e organizado
2. Opinar sobre o melhor stack para o projeto
3. Analisar o prazo e escopo do projeto, com cuidado, e cumpri-lo

Tecnologias com as quais trabalhamos atualmente

1. Laravel
2. Ionic
3. ReactNative
4. WordPress

Nossa empresa

A Agência Bein nasceu em Março de 2018 e vem ganhando grandes clientes desde então. Nosso grande crescimento ocorre por três simples motivos:

    1. Amor e dedicação no que fazemos
    2. Carinho e atenção com nossos clientes
    3. Qualidade alta por um valor justo

Nosso objetivo é claro: Ajudar startup’s com ideias inovadoras em todos os nichos.

## Como se candidatar

Por favor, preencha o formulário [https://trabalhe-agencia-bein.paperform.co/](https://trabalhe-agencia-bein.paperform.co/)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: contato@agenciabein.com.br

## Labels

- Freelancer
- Júnior
- PF/PJ
- Remoto

**Comment by rhanielvalle** [comment]
Enviado meu contato. Obrigado pela oportunidade gente! Sucesso.

**Comment by edsonvieirademetrio** [comment]
Formulário preenchido, currículo enviado. Aguardo feedback. Abraço!!!

**Comment by odntht** [comment]
Boa!
Se me permitem, acredito que seria uma boa modificar um pouco o formulário deixando um pouco mais nítido onde fica os campos para digitar as informações. Como n tem borda nem cor diferente enquanto não se clica, tem aquele 1s que a pessoa acaba procurando onde que digita.
Abç e sucesso

**Comment by yanbein** [comment]
> Boa!
> Se me permitem, acredito que seria uma boa modificar um pouco o formulário deixando um pouco mais nítido onde fica os campos para digitar as informações. Como n tem borda nem cor diferente enquanto não se clica, tem aquele 1s que a pessoa acaba procurando onde que digita.
> Abç e sucesso

Agradecemos o feedback!

**Comment by humbertoromanojr** [comment]
ola boa tarde pessoal da Bein
estou interessado na vaga para Dev ReactNative
acabei de preencher o formulário
boa semana a toodos

**Comment by yanbein** [comment]
Boa tarde,
Estamos encerrando as vagas. Com tempo, teremos novas oportunidades. Obrigado à todos.

Aos que não foram selecionados; seus dados estão salvos e entraremos em contato assim que surgirem vagas.
