### ISSUE TITLE
[São Paulo] Front-end Developer na Restoque

### ISSUE THREAD

**Issue by gtotti2** [frontendbr/vagas#2789]
## Descrição da vaga

- Atualização e manutenção de projetos em andamento
Atualização de conteúdo do site atual, criação de campanhas sazonais, implementação de novas funcionalidades e customizações nas vitrines, páginas internas e home

 - Criação de novas funcionalidades e páginas
Novos carrosseis, vitrines, visualizações de produto, customização nos templates

## Local

Escritório - São Paulo - Vila Leopoldina - Ao lado da estação Ceasa

## Benefícios

- Plano de saúde
- Plano odontológico
- Vale Refeição
- Fretado até a estação
- Desconto para compra de produtos

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com HTML, CSS e JAVASCRIPT(Vanilla)
- 6 meses de experiência com Vue.Js 

**Desejáveis:**
- Ter conhecimento em uniformidade e metodologias de código 
- BEM, SASS

**Diferenciais:**
- E-commerce 
- Equipe em crescimento

## Contratação

CLT

## Nossa empresa

A Restoque é uma das principais empresas varejistas do setor de vestuário e acessórios de alto padrão no Brasil. Conta atualmente com 7 marcas: “Le Lis Blanc”, “Bo.Bô” ,“John John”, “Rosa Chá”, "Dudalina"​, "Individual"​ e "Base"​. Os clientes das marcas são principalmente mulheres e homens com alto poder aquisitivo, de todas as faixas etárias.

A Companhia desenvolve uma ampla linha de produtos para diversas ocasiões, cria produtos de vestuário e acessórios e contrata fornecedores para sua produção. Comercializa seus produtos por meio de lojas próprias, vendas on-line e lojas multimarcas. Promove os conceitos das marcas em todos os aspectos de seus negócios, por meio de produtos de alto-padrão, da experiência de compra em suas lojas e de atendimento diferenciado.

Para saber mais, consulte nosso site www.restoque.com.br ou acesse:

Le Lis Blanc | www.lelis.com.br
Bo.Bô | www.bobo.com.br
John John | www.johnjohndenim.com
Rosa Chá | www.rosacha.com.br
Dudalina | www.dudalina.com.br
Individual | www.individual.com.br
Base | www.basejeans.com.br

## Como se candidatar

Por favor envie um email para gian.santos@restoque.com.br com seu CV anexado - enviar no assunto: Vaga - Front End

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: gian.santos@restoque.com.br

## Labels

- Alocado
- CLT
- Júnior
- Pleno

**Comment by simaodeveloper** [comment]
Enviado!

**Comment by pedroreis01** [comment]
Enviado
