### ISSUE TITLE
[São Paulo]  Pessoa desenvolvedora Javascript

### ISSUE THREAD

**Issue by Raffesmind** [frontendbr/vagas#279]
## Descrição da vaga

Estamos em busca de profissionais que realizem a concepção e implementação de API's. O objetivo é realizar o entendimento e desenvolvimento dos produtos dos nossos clientes.​
Responsabilidades
Participar das cerimônias ( Sprint Planning, Daily Meeting, Sprint Review e Retrospectiva ).
Ajudar no entendimento do que deve ser desenvolvido;
Realizar uma documentação prévia das suas tarefas, garantindo o planejamento;
Realizar o desenvolvimento utilizando técnicas como TDD e BDD;
Utilizar as melhores práticas de desenvolvimento e Design Patterns;
Se preocupar com a qualidade dos entregáveis;
Comprometimento com as entregas em equipe;
Ajudar no review da tarefa de outros integrantes da equipe.
Levantar os problemas encontrados durante o processo de desenvolvimento, formalizando os impedimentos.
Compartilhar o conhecimento.
Sugerir melhorias no processo de trabalho.
Tratar o cliente e o colega de trabalho com cordialidade e ética.
Participar e promover os treinamentos visando o crescimento da equipe.

## Local
Escritório colado com o metro paraíso (Mas há possibilidade de fazer remoto)

## Benefícios
Salário competitivo;
Massagem no escritório;
Frigobar;
Sem regras de vestimenta;
Cursos pagos pela empresa;

## Requisitos

**Obrigatórios:**
GIT;
Conhecimentos aprofundados em Javascript;
Conhecimento em algum framework Javascript (Angular2, EmberJS, NodeJS). Meteor e React serão diferenciais;
HTML/CSS;
Boas práticas de desenvolvimento;
Modelagem de Serviço ( Rest ou SOAP );
Conhecimento em Service Oriented Architecture;
Code Review;
Pull Request;

**Desejáveis:**
Meteor e React
Conhecimentos básicos de MongoDB;
Ember.js
Vue.js

## Contratação

PJ a combinar

## Nossa empresa

Sciensa, antiga SOA Experts
Curte um ambiente de trabalho descontraído ? Sem dress code ? Aqui temos isso e muito mais ! Breja no final do expediente com uma partida de vídeo game, treinamentos internos trazendo mais conhecimento pra todos da equipe, projetos inovadores para colocar no portfólio, massagem para ficar relax e metodologia de trabalho ágil.

Se você é fera em tecnologia, seu lugar é aqui na Sciensa !
## Como se candidatar

https://sciensa.recruitee.com/o/react-fullstack-developer - No campo de observações fale que achou a vaga através do Github por favor gente :heart: 

Dúvidas me mandem um e-mail para: rafael.ventura@sciensa.com
Ou me procurem nas redes sociais.

**Comment by LFeh** [comment]
Opa, quais as labels? :)

**Comment by Raffesmind** [comment]
Acabei esquecendo na pressa, seriam de: PJ, Jr, Pleno, Senior, Alocado, Remoto e Freela

**Comment by ribeiroevandro** [comment]
A parte do remoto me interessa, mas tem algumas coisas que ainda não manjo :(

**Comment by thainanfrota** [comment]
@Raffesmind tentei te mandar um e-mail mas voltou! :(

Tem algum outro???

**Comment by Raffesmind** [comment]
@thainanfrota me manda no pessoal rafa.lluve@gmail.com ou no rafael.ventura@soaexpert.com.br

**Comment by Carlosxell** [comment]
Só para alinhar, tem vaga para júnior pleno e sênior ou é a mesma vaga e todos os níveis estão abertos a tentar?

**Comment by Raffesmind** [comment]
@Carlosxell é a mesma vaga está aberta para todos os níveis, hoje temos certa urgência para pleno ou Sênior, por conta de precisar padronizar alguns projetos da casa, mas estamos sempre abertos para encontrar bons profissionais para ter ao nosso lado 👍

**Comment by ericprieto** [comment]
O esquema de contratação é só PJ?

**Comment by Raffesmind** [comment]
Sim, hoje a empresa só trabalha com PJ, mas auxiliamos em todo o processo de abertura e o que mais tiverem de dúvidas.

**Comment by ericprieto** [comment]
Entendi... Eu tenho empresa aberta já, mas estou procurando algo CLT. Caso precisem de freelas para projetos fechados, principalmente com React, estou disponível.

**Comment by Raffesmind** [comment]
@ericprieto me manda um e-mail com suas informações? Talvez tenhamos algo para você.

**Comment by ericprieto** [comment]
Enviado :)

**Comment by guilherme6191** [comment]
@Raffesmind me candidatei pelo site da empresa. No meu caso, só seria possível remoto de BH, e minha intenção é PL. PJ é ok por mim. Valeu!

**Comment by WelingtonMonteiro** [comment]
enviado o/
