### ISSUE TITLE
[Rio de Janeiro] Front-end Developer no MIND (Multiplan)

### ISSUE THREAD

**Issue by RMontSerrat** [frontendbr/vagas#2791]
## Descrição da vaga

Olá! Nós somos a Multiplan, uma das maiores empresas da indústria de shopping centers do país. 

Buscamos candidatos para trabalhar em nosso escritório no Rio de Janeiro e se juntar à equipe de DEVs do MIND, área de inovação digital da empresa. Queremos desenvolvedores brilhantes que gostem de desafios. Nosso time é multidisciplinar e autogerenciado. Valorizamos muito o trabalho em equipe, a paixão pelo estudo e a troca de conhecimento e experiências.

## Local

Centro Empresarial Barra Shopping - Rio de Janeiro

## Benefícios

- Plano de saúde Bradesco
- Plano odontológico Bradesco
- Vale refeição de R$39,50/dia
- Salário competitivo com o mercado
- Participação nos lucros da empresa

## Requisitos

**Obrigatórios:**
- Tenha mais de 5 anos de experiência de desenvolvimento;
- Tenha conhecimento de ReactJS e seu ecossistema (React Router, Redux…);
- Tenha sólidos conhecimento de front-end - HTML5, CSS3 e WebPack;
- Tenha experiência avançada com Node.js e MongoDB;
- Domine Git e goste de fazer code-review;
- Saiba escrever testes automatizados (unitário, integração e end-to-end);
- Conheça metodologias ágeis (Scrum e Kanban);
- Seja adepto de boas práticas de desenvolvimento (Clean Code, CI/CD…);
- Tenha facilidade de atuação em times multidisciplinares.

**Desejáveis:**
- Mobile (React Native / Android / IOS)
- Elasticsearch
- GraphQL
- Ter desenvolvido sistemas prevendo alta-disponibilidade, escalabilidade e performance.

## Contratação

CLT

## Como se candidatar

Por favor envie um email para [devs@multishopping.com.br](url) com seu CV anexado - enviar no assunto: Vaga Front-End Multi

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

## Labels

- Alocado
- CLT
- Pleno
- Sênior

**Comment by fernandohenriques** [comment]
Ótima empresa. Recomendo.

**Comment by re-andrade1987** [comment]
Uma pena que um dos requisitos seja ter mais de 5 anos de experiência :(

**Comment by thallesmarchetti** [comment]
Teria alguma posição para Junior?

**Comment by danielsidev** [comment]
Olá! Tudo bem?
Essa vaga pode ser remota?
Sou do Rio de Janeiro .
Abraços!
