### ISSUE TITLE
[SP - Remoto] Engenharia de Front End na Linte_

### ISSUE THREAD

**Issue by iagobyintera** [frontendbr/vagas#2793]
A **Linte_** está crescendo e precisa de você para construir um novo produto.

**É tudo do início!** Estamos desenvolvendo a melhor arquitetura e as melhores tecnologias para construir uma plataforma sustentável, escalável e consistente à longo prazo. Tudo isso para fornecer a melhor performance e experiência para os nossos clientes, entre eles estão Fundação Leumann, Stone, Itaú, 99 e Renault. Apesar de estarmos no início, começamos com tudo!

Atualmente nós trabalhamos com **Javascript ES6, Typescript, GraphQL e React com Redux.** Essas tecnologias com pessoas com propósito e dispostas é o que nos faz crescer exponencialmente. Serão bem vindos também conhecimentos em Programação Reativa, TDD, Metodologias Ágeis, e outras boas práticas de programação.

A contratação será feita em **regime CLT com horário flexível ou PJ para trabalho remoto.** Para o trabalho de forma presencial, estamos na CUBO, em São Paulo. Para mais informações, acesse a página da vaga.

**Página da vaga:** http://byintera.in/2b

## Labels
- REMOTO
- PLENO
- SÊNIOR
- CLT
- PJ

**Comment by HenryKun55** [comment]
O site não funciona

**Comment by edsonvieirademetrio** [comment]
Tem alguma vaga em aberto para desenvolvedor Frontend (remoto)?

**Comment by iagobyintera** [comment]
> Tem alguma vaga em aberto para desenvolvedor Frontend (remoto)?

Essa oportunidade é para Frontend remoto Edson, basta acessar o link

**Comment by iagobyintera** [comment]
> O site não funciona

Pode tentar acessar o link diretamente: https://intera.talent-hacking.com/linte/engenheiro-front-end/

**Comment by thismarcoantonio** [comment]
@iagobyintera eu havia aplicado na outra oportunidade, não sei se vocês avaliaram meu perfil, porém como eu n tive feedback, aplicarei novamente, pode ser?

**Comment by iagobyintera** [comment]
@thismarcoantonio Está em avaliação Marco :)

**Comment by mundau** [comment]
x

**Comment by leandrojo** [comment]
Quando eu vejo que a vaga é da Intera já bate a tristeza, é muito ruim o processo, parece que tudo é subjetivo. Quando apliquei pra Linte eles já disseram que eu não tinha o perfil porque eles usam TypeScript... Oi? Como assim, não usam comumente TypeScript, mas é uma curva muito sútil principalmente para Sênior. Essa vaga já se extende à meses e assim acho que vai continuar.

**Comment by thismarcoantonio** [comment]
@leandrojo que bom saber disso cara, eu super fiquei empolgado com a vaga, mas quanto a esse seu parecer é bem desanimador, a empresa nem sequer tentou conversar contigo para trocar uma ideia?
