### ISSUE TITLE
[Recife] Front-end Developer no Amigo

### ISSUE THREAD

**Issue by guilhermefarias** [frontendbr/vagas#2796]
Estamos realizando uma forte expansão e temos 8 vagas abertas para início imediato em Recife!

Se você é Front-End, FullStack ou simplesmente manja muito de JavaScript, venha conversar com a gente, estamos com várias oportunidades e certamente você vai se encaixar em alguma delas :)

**Requisitos para todas as vagas de desenvolvimento:**
- Goste de programar
- Javascript, muito Javascript
- Algoritmos, padrões de projeto e refatoração
- Sólido conhecimento em desenvolvimento web
- Dominio em NodeJS ou AngularJS
- (para os backends) Conhecimento avançado em PostgreSQL, Oracle ou SQL Server

**Esperamos que você:**
- Se comunique bem
- Se atualize com novas tecnologias
- Aprenda rápido. Evoluímos muito e muito rápido!
- Tenha capacidade de resolver problemas de forma rápida e completa

**Oferecemos:**
- Vale Alimentação/Refeição;
- Vale Transporte/Cartão de Estacionamento;
- Plano de saúde;
- Contratação CLT;

**Interessou?**
Envie seu Github + LinkedIn + CV e o que mais você achar interessante para: vagas@amigoapp.com.br

**Comment by edsonvieirademetrio** [comment]
Olá! Tudo bem?
Remoto ou alocado?

**Comment by guilhermefarias** [comment]
@edsonvieirademetrio Olá amigo, a vaga é presencial, alocado.

**Comment by edsonvieirademetrio** [comment]
@guilhermefarias Ok. Obrigado pelo feedback

**Comment by WisleyRodrigues** [comment]
Bom dia @guilhermefarias, envie meu CV a voces a alguns dias atras, teria como me passar o status?
