### ISSUE TITLE
[São Paulo] Desenvolvedor Ruby on Rails

### ISSUE THREAD

**Issue by Natassiaperez** [frontendbr/vagas#280]
## Descrição da vaga

- Responsável pelo desenvolvimento de software e também testes, entrega, manutenção e documentação dos sistemas;
- Fazer parte de um time de desenvolvimento de produtos;
- Interagir com clientes internos, tais como Product Owners, UX, Suporte, Sysadmins e outras equipes de desenvolvimento

## Local

Zona Sul/ São Paulo (Prox Shopping Morumbi)

## Benefícios

AM, AO, PLR, Crédito de R$ 24,00 diários para refeição no local (restaurante e lanches), Estacionamento gratuito ou VT, Auxílio-Creche.
Infraestrutura com Quick Massage, Ginástica Laboral, Academia e Espaço Relax.

## Requisitos

- Apps web e api´s em Rails;
- Sidekiq;
- Postgres com Rails;
- Postfix;
- Nginx;
- Linux
- Integração contínua;
- Banco de dados relacionais e não relacionais;
- Metodologias ágeis

**Desejáveis:**
- Desenvolvimento em Python

## Contratação

CLT a combinar

QUANTA BRASIL - A matriz do Grupo Quanta está localizada em Milão. Na Itália a empresa  conta com outras 30 filiais distribuídas por todo o território. No contexto internacional a Quanta se faz presente na Suíça na cidade de Lugano, na Romênia com 2 escritórios, nos Estados Unidos com 4 escritórios e no Brasil com sua sede em São Paulo.

## Como se candidatar

Por favor envie um email para nperez@quanta.com, com seu CV anexado - enviar no assunto: Dev Ruby on Rails

**Comment by eduardojmatos** [comment]
Esse repositório é pra vagas de front-end exclusivamente! Obrigado por postar, mas iremos fechar a issue, ok? 😄

**Comment by Natassiaperez** [comment]
Ai puxa vida rs Um cara que me indicou esse repositório, vou tentar
procurar outro então.
Valeu


Natassia Perez
*Head of Digital Innovation*

Rua do Rócio, 288 – 1º andar
São Paulo – SP – 04552-000

*Tel: +55 11 3169 7777Cel: +55 11 9 7690 6966*

*www.quantabrasil.com.br <http://www.quantabrasil.com.br>*


[image: logo]

2017-03-14 18:16 GMT-03:00 Eduardo Matos <notifications@github.com>:

**Comment by LFeh** [comment]
Sem problemas @Natassiaperez :)
