### ISSUE TITLE
[Niterói/RJ] Front-end Developer na Wama Soluções Web

### ISSUE THREAD

**Issue by Gabrielmoraesp** [frontendbr/vagas#2804]
Descrição da vaga
Pessoal, sou o Gabriel, fundador da Wama Soluções Web. Estamos preparando nosso escritório na cidade de Niterói - RJ.
Possuímos alguns projetos em andamento e estamos em busca de profissionais com mente empreendedora. A princípio a vaga é para trabalhar remotamente, após o escritório ficar pronto, terá direito a 1 dia da semana em home office. 

Local: Remoto*

Requisitos:

ReactJS/, Vue.JS
HTML / CSS
CSS
JavaScript
RESTful services
SASS
NPM ou yarn (para gerenciamente de pacotes/bibliotecas javascript)
Repositórios: Git
Saber criar testes unitários
Frameworks de interface (ex: bootstrap).

Desejáveis:

Banco de dados (relacional e/ou não relacional)
TypeScript
ElasticSearch (como noções de performance);
Desenvolvimento Ágil

Contratação
PJ

Como se candidatar

Por favor, envie um email para contato@xekout.me com seu CV anexado - enviar no assunto: Front End

Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

Labels

Alocado
Estágio
Freela
Júnior
PJ
Pleno
Remoto
Sênior

**Comment by AnaVargasF** [comment]
A vaga para estágio também é para trabalhar remotamente?

**Comment by maxleon52** [comment]
Boa noite, alguma vaga para Dev Júnior? Stack NodeJs, ReactJS, HTML5 e CSS 3...
