### ISSUE TITLE
[Remoto] Elm Front-End Developer no Cálculo Jurídico

### ISSUE THREAD

**Issue by giovannibonetti** [frontendbr/vagas#2805]
## Descrição da vaga

Aqui no Cálculo Jurídico nós desenvolvemos sistemas para ajudar os advogados a fazerem cálculos de aposentadoria para seus clientes. Estamos expandindo para outras áreas de direito e precisamos de você para nos ajudar a dar conta desse trabalho. A empresa é 100% remota, e nos comunicamos via Slack, Hangout e Google Docs.

Nesta postagem estamos divulgando uma vaga disponível para **desenvolvedor(a) front-end Elm**. 
Estamos buscando alguém para ser o(a) principal desenvolvedor(a) de um projeto novo que está sendo escrito _do zero_ com [Elm](https://github.com/CalculoJuridico/create-elm-app) (e também Webpack porque gostamos de SASS).

Requisitos: experiência em desenvolvimento front-end e conhecimentos básicos de Elm.
Processo seletivo 100% online incluindo prova teórica e prática de Elm seguidos de entrevista via Hangouts.

Curiosidade: não é a primeira vez que divulgamos vagas aqui - vide #1526.

## Local

Remoto

## Contratação
PJ _full time_ com remuneração entre R$ 8 e 11 mil, dependendo da experiência do(a) candidato(a) e do resultado nas provas do processo seletivo.

## Requisitos

**Obrigatórios**
- Experiência profissional em desenvolvimento de front-end web com HTML, CSS e JS
- Conhecimento teórico de programação funcional
- Conhecimento básico de Elm - basta ter [completado o tutorial](https://guide.elm-lang.org/)
- inglês avançado para compreensão escrita e oral (vídeos de cursos, eventos etc.)

Obs.: todos os requisitos tem uma prova online correspondente no processo seletivo

**Desejáveis**
- Experiência de trabalho com Git
- Experiência de trabalho com programação funcional
- Experiência de trabalho com Elm
- Experiência com Webpack

## Empresa

Apesar de ser uma empresa nova - há cerca de 3 anos no mercado - o Cálculo Jurídico já é uma empresa lucrativa e, portanto, não precisa de investimento externo. Aqui a gente trabalha para fazer o melhor produto pro cliente, não para entregar as funcionalidades que o investidor pede.

Somos uma equipe pequena (cerca de 15 pessoas) mas bem organizada. Você pode observar isso pela organização do processo seletivo com várias etapas, sendo tudo realizado por nós mesmos (não terceirizamos recrutamento para nenhuma empresa de RH).

Do ponto de vista tecnológico, hoje temos um sistema feito em Ruby on Rails hospedado no Google App Engine / Google Cloud Platform com containers Docker. Estamos montando nossa API agora que vai ser usada pelas novas partes do front-end, que já foi todo desenhado no Figma e está sendo implementado agora.

#### Diferenciais da empresa

- empresa 100% remota;
- trabalho com projeto escrito do zero em Elm. Nada de legado de JS para manter;
- alta produtividade - você vai poder focar no trabalho sem muitas interrupções. Há raríssimas reuniões (normalmente só uma por semana), pois quase todas a comunicação ocorre de forma assíncrona via documentos do Google Docs, desenhos da interface no Figma, emails etc.

## Como se candidatar

Inscrições abertas até sexta-feira (17/jan) às 12h (BRT) [neste link](https://talentos.calculojuridico.com.br/selective_processes/desenvolvedor-a-front-end-elm-home-office-2020/candidates/new?referrer=github).

Assim que as inscrições se encerrarem você vai receber um email nosso explicando como iniciar o processo seletivo.

## Cronograma

Ação | Prazo
-- | --
Encerramento das inscrições | 17/jan (6ª feira) às 12h
Realização dos testes de lógica, inglês e comunicação | 17/jan (6ª feira) às 12h até 20/jan (2ª feira) às 12h
Comunicação do resultado na prova teórica | 20/jan (2ª feira) até às 18h
Realização da prova prática de desenvolvimento em Elm | 24/jan (6ª feira) às 12h até 27/jan (2ª feira) às 12h
Comunicação do resultado na prova prática e convocação dos aprovados para entrevista | 27/jan (2ª feira) até às 18h
Realização das entrevistas | 28/jan (3ª feira) e 29/jan (4ª feira)
Comunicação aos candidatos do resultado final do processo seletivo | até 31/jan (6ª feira) às 18h
Ínicio do trabalho | a partir de 04/fev (2ª feira)

**Comment by Daniray2008** [comment]
Olá tenho todos os requisitos, mas referente ao inglês meu nível é avançado em escrita e leitura, na parte da conversação não é tão bom, gostaria de saber se posso me inscrever mesmo assim?

**Comment by giovannibonetti** [comment]
Boa tarde! Pode se inscrever, sim! Conforme descrito no documento do Google Docs, o nosso requisito é inglês avançado para compreensão escrita e oral (vídeos de cursos, eventos etc.).

**Comment by Daniray2008** [comment]
Ótimo,  já fiz minha inscrição, quanto tempo demora pra liberar o teste?

**Comment by giovannibonetti** [comment]
Conforme descrito no cronograma acima, os testes serão liberados logo após o término das inscrições na sexta-feira às 12h.

**Comment by Daniray2008** [comment]
Ops já via aqui o cronograma, obrigada pela a ajuda,

**Comment by fafa1** [comment]
Boa tarde, Por que no formulário pede o cpf do candidatos, tem essa necessidade?

**Comment by giovannibonetti** [comment]
> Boa tarde, Por que no formulário pede o cpf do candidatos, tem essa necessidade?

A gente pede isso para aumentar a barreira contra cadastros fraudulentos.
Você tem um bom motivo para não querer preencher o seu CPF?

**Comment by fafa1** [comment]
Não, queria apenas saber o motivo do CPF, pois não  eh comum pedir nos processos seletivos. Obrigado.
