### ISSUE TITLE
[Araçatuba][Remoto] Front-End Developer no Grupo Acert

### ISSUE THREAD

**Issue by dougcavalheiro** [frontendbr/vagas#2807]
## Descrição da vaga

**Requisitos necessários:**
- JavaScript / ES6
- ReactJS / Redux (Sagas / Thunk)
- Webpack
- CSS
- APIs REST

**Hábito com as metodologias ágeis
Inglês técnico
Desejo de aprender**

**Será um diferencial já conhecer:** 
- Typescript
- Ferramentas de teste: Jest, Enzyme, React-Testing-Library, Cypress
- Material Design

## Contratação

PJ a combinar

## Remuneração

De R$4000,00 a R$5000,00

## Como se candidatar

Envie seu CV para o e-mail: douglas.cavalheiro@grupoacert.com.br com o assunto FRONT-END

## Labels

- PJ
- Remoto

**Comment by EdeiltonSO** [comment]
Enviado!

**Comment by Ronaldofj** [comment]
CV enviado! =)

**Comment by kivervinicius** [comment]
e ai @dougcavalheiro  quantas horas semanais? horário flexível?
