### ISSUE TITLE
[São Paulo] Pessoa desenvolvedora Front-end Jr/PL na Vamo!

### ISSUE THREAD

**Issue by joselialcosta** [frontendbr/vagas#281]
*Observação: Em fevereiro conseguimos contratar uma pessoa a partir desse repositório* ❤️  *Agora estamos procurando outra!* 👀 

Descrição da vaga
----

Estamos em busca de uma pessoa desenvolvedora front-end para integrar o nosso time. Neste momento, nosso espectro está entre uma pessoa junior e plena, que possa aprender conosco e também trazer boas práticas de arquitetura e performance, e que - acima de tudo - curta resolver problemas de uma forma coesa usando JavaScript, CSS bem escrito e HTML.

Nossa stack geral:

**Front**
- Angular 1.5.x
- TypeScript 1.X
- Pré processadores CSS (Less e Sass)
- Gulp, Grunt e Webpack

**Back**
- Scala (Akka e Play)
- Java(Spring boot e Java8)
- Deploy automatizado com Docker e AWS
- Apps nativos (iOS e Android)

Local
---

Vila Olimpia - SP
(Próximo à estação de trem e do Shopping Vila Olimpia)

Contratação
---

CLT Full, presencial

Benefícios
---
- VR (R$506 por mês)
- VT ou estacionamento para carros e bikes :bike:
- Plano de saúde One Health e odontológico Amil
- Seguro de Vida
- Convênio com SESC

Nenhum desses benefícios é descontado do salário :tada:

Requisitos
---
**O que você precisa saber:**
- Vanilla JS
- Web SPA com Angular ou outros
- Inglês para se comunicar (temos gringos no time!)
- Vontade de aprender e não ter preconceitos
- Código limpo
- Noções de usabilidade

**Será legal se você tiver:**
- Contribuições OpenSource
- Conhecimento sobre Task Runners
- Conhecimento ES6/ES7
- Formação: Bacharel em Engenharia/Ciência da Computação ou equivalente.

Nosso Ambiente
---

- Snacks, frutas e bolos!
- Video games
- ~Ping-Pong~ (Foi doada 😞 )
- Festa de aniversário todo mês :cake:
- Horário flexível
- Sem dress code (pode vir de pijama!)

Sobre Nós
---

Somos uma startup norte-americana comprometida a reinventar a maneira como as pessoas descobrem eventos e compram ingressos online usando seus smartphones. Também trabalhamos em uma série de outros projetos tão legais quanto esse.

Saiba mais em: https://vamoapp.com/

Como se candidatar
---

Preencha este formulário e informe que você viu a vaga no FrontendBR. 😃 
http://bit.ly/2m0h4JX

**Comment by LFeh** [comment]
Quais as labels @joselialcosta? o/

**Comment by joselialcosta** [comment]
Junior, Pleno, alocado e CLT @LFeh ! Obrigada!

**Comment by glauberfc** [comment]
Pra ser perfeita só falta a tag "Remoto"!

**Comment by danielGalvao** [comment]
@joselialcosta kkkkk "Pesssoa desenvolvedora"

**Comment by LFeh** [comment]
@joselialcosta É um dos motivos de curtir bastante usar o nome da nossa profissão em inglês... 

**Front-End Developer** não faz diferença de gênero.

Vou mudar inclusive na sugestão do repositório ;)

**Comment by LFeh** [comment]
Done 😃

**Comment by joselialcosta** [comment]
Muito bom, @LFeh !! Pequenas atitudes para conquistar grandes mudanças! Ficou ótimo :)
ah, ainda sobre o termo "pessoa desenvolvedora": a Thoughtworks tbm utiliza essa notação nas jobs descriptions deles

**Comment by LFeh** [comment]
Nóis!

**Comment by danielGalvao** [comment]
@joselialcosta Só para constar que achei o máximo!!! E a risada não foi sarcástica... A risada foi: Como nunca pensamos nisso antes ou nem percebemos pois já estamos no automático.

**Comment by ericprieto** [comment]
Achei um máximo o posicionamento quanto a identidade de gênero, parabéns!

Pena que é longe para mim e usam Angular :P

**Comment by ericprieto** [comment]
Achei um máximo o posicionamento quanto a identidade de gênero, parabéns!

Pena que é longe para mim :(

**Comment by ggviana** [comment]
Republiquei a vaga @LFeh, por favor fechar essa.

**Comment by sprc86** [comment]
> @joselialcosta kkkkk "Pesssoa desenvolvedora"

"Desenvolvedor", dentro de um contexto de anúncio de emprego, é considerado um termo neutro. Não há necessidade de usar "pessoa desenvolvedora". Vocês não estão promovendo "igualdade", estão apenas atacando a linguagem culta. 

Abraços.
