### ISSUE TITLE
[Rio de Janeiro] Front-end Developer na Liber

### ISSUE THREAD

**Issue by libereducacao** [frontendbr/vagas#2812]
## Descrição da vaga

Buscamos profissionais (perfil Júnior) proativos e engajados, focados em desenvolvimento Full Stack (usamos React Native para nossos apps mobile e Laravel na API) para compor nossa equipe em uma etapa de aceleração e ganho de escala da empresa.

## Local

Escritório na Barra da Tijuca, Rio de Janeiro - RJ (Menos de 1 minuto da estação Jardim Oceânico do metrô)

#### Diferenciais

-   Ambiente altamente inovador
-   Horário flexível

## Requisitos

**Obrigatórios:**
-   Javascript (ES6+)
-   React Native e/ou React

**Desejáveis:**
-   PHP (Laravel)
-   Design Patterns
-   Typescript
-   Metodologias Ágeis (Scrum)

**Diferenciais:**
-   Firebase
-   Testes automatizados (Jest, Detox, PHPUnit)

## Contratação

PJ a combinar

## Nossa empresa

Somos uma EdTech que nasceu em 2018 a partir de um projeto universitário. Selecionamos e treinamos talentos universitários de faculdades de ponta para darem aulas particulares presenciais no dia, horário e local que nossos clientes precisarem; levando uma experiência de aprendizado horizontal, focada em resultados e com acompanhamento personalizado voltado para as necessidades de cada família ou aluno.

## Como se candidatar

Basta acessar o link abaixo e preencher o formulário:
https://liber-educacao.typeform.com/to/RjhBsw

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.\
E-mail para contato em caso de não haver resposta: <developers@liberedu.com>

## Labels

-   Alocado
-   Júnior
-   PJ

**Comment by joaopedrodev** [comment]
Olá queria saber se existe alguma para desenvolvedor Laravel PHP, também trabalho como desenvolvedor FullStack obrigado deixo meu numero do whatsapp 61999955207.

**Comment by libereducacao** [comment]
Ainda disponível.
