### ISSUE TITLE
[Belo Horizonte] Front-end Developer no Clipping

### ISSUE THREAD

**Issue by viniciuscacd** [frontendbr/vagas#2818]
# Front-end Developer no Clipping
O Clipping é uma startup de educação sediada no Parque Tecnológico de Belo Horizonte. Nosso trabalho vem mudando a forma como as pessoas estudam para provas e concursos, ajudando candidatos a estudarem melhor, gastando menos tempo e dinheiro. Confira um pouco da nossa história aqui. 

Temos planos ambiciosos para 2020 e estamos expandindo nossa equipe! 

Há no momento 1 oportunidade aberta para desenvolvedor na cidade de BH:

### 🔰 Sobre a oportunidade
Somos uma equipe enxuta e orientada a oferecer uma experiência de estudo inovadora. Um dos principais desafios que você enfrentará no Front é o de desenvolver,  junto a nosso time de produto de TI,  soluções web inovadoras que impactem a rotina de estudo de milhares de usuários da nossa plataforma.

Se interessa? 

Detalhamos abaixo algumas das principais atribuições desta função:

## Requisitos
**Obrigatórios:**
 - Javascript (sólida experiência); 
- Experiência em algum framework javascript/ 
- HTML5, CSS3;
- Versionamento Git (GitFlow, PR, etc);
- Inglês Intermediário;

**Desejáveis:**

- React, Redux (caso não domine esses frameworks, você terá apoio da equipe para  se qualificar e aprender esses frameworks. No entanto, exigimos uma base sólida de Javascript);
-Experiência com metodologias ágeis.

## 😍 Benefícios e ambiente de trabalho

Estamos localizados no Parque Tecnológico de Belo Horizonte, o BHTEC. É um ambiente informal e riquíssimo para o aprendizado de quem se interessa por startups e inovação.

- 🏥 Plano de saúde Bradesco (internação em apto)
- 🚌 Vale transporte (pode ser convertido em vale combustível);
- 🍔 Vale alimentação ou Vale refeição;
- 🔰 Ambiente informal e sem dress code;
- ✌️ Horário flexível e home-office esporadicamente;
- 🔆 Investimos e arcamos com sua capacitação;
- 🤖 Trabalhamos com últimas tendências e tecnologias de ponta;
- 🚀  Possibilidade real de crescimento com a empresa;
- 💰 Distribuição de lucros;
 

**Interessou pela oportunidade?** 
Mande um email com um CV para a gente no vagas@clippingcacd.com.br  com o título: "CV Desenvolvedor Javascript".
## Labels

- Alocado
- CLT
- Júnior
- Pleno

**Comment by AckylaF** [comment]
Olá, alguma oportunidade para alguém que está começando e afim de mostrar serviço?

**Comment by robertov8** [comment]
Enviado! =D
