### ISSUE TITLE
[São Paulo] Desenvolvedor Front-End Angular

### ISSUE THREAD

**Issue by diogo-arantes** [frontendbr/vagas#282]
## Descrição da vaga

Buscamos um profissional front-end com conhecimentos em Angular+ para desenvolvimento do front-end de uma plataforma BI multi-níveis.

Temos interesse por pessoas criativas e determinadas, dispostas a aprender e compartilhar conhecimento e que se interessem pelas mais recentes tecnologias de programação.

## Local

Apenas São Paulo
Remoto e escritório (2x/semana no Escritório, São Paulo - Prox.Faria Lima)

## Requisitos

**Obrigatórios:**
- Experiência com algum frameworks SPA (Angular, React, Vue, Ember)
- Vontade de aprender e trabalhar com Angular2
- Bootstrap
- Javascript

- Mentalidade Startup, construir a empresa e crescer junto com a empresa.

**Desejáveis:**
- conhecimentos em Linux
- boas noções de design
- UX

## Contratação

PJ a combinar

## Como se candidatar

Enviar email para jobs@orfeus.com.br com assunto: Vaga Frontend ou chamar no whatsapp 98640 8282 (Diogo)

**Comment by bcarvalho89** [comment]
Enviado por e-mail ;)

**Comment by femontanha** [comment]
Enviado :)
