### ISSUE TITLE
[Remoto] Full-stack React Native developer at Outbound

### ISSUE THREAD

**Issue by vtrpldn** [frontendbr/vagas#2820]
## Descrição da vaga

Outbound is seeking a full-stack React Native developer with at least 3 years of experience with mobile development, at least 1 year with RN.

You'll be able to work from home, using Slack to communicate with our team.

## Local

Remoto

## Requisitos

- 3+ years of experience with mobile development
- 1+ years of experience with RN development
- English fluency
- Deep understanding of technology
- Ability to balance speed and quality, with a focus on tangible results
- Attention to detail
- Proven record of shipping features on time
- Flexible and focused on solutions
- Organized and self-motivated

## Contratação

The position is full-time (160 hours/month).

## Nossa empresa

We're based in Copenhagen, Denmark, but half of our team works remotely from places like Rio de Janeiro and Budapest 🇩🇰🇧🇷🇭🇺

Our platform is built using Node.js with a PostgreSQL database running in Docker containers on AWS, using SNS, SES, SQS, Route53, S3, and EC2.

You can check our complete tech stack in [this link](https://www.notion.so/Full-stack-React-Native-developer-9c9acc617a064eba875c99e47524eb13).

For more information about the product you can check [our website](http://outboundhq.com/).

## Como se candidatar

Does this role sound like a good fit? Email Stefan Bech at [stefan@outboundhq.com](mailto:stefan@outboundhq.com).

- Include the role's title in your subject line
- Send along links that best showcase the relevant things you've built and done
- We especially want to see what you've built with RN
- Let us know if you have experience with any other technologies in our stack, besides RN
- You're full-stack, but do you skew more towards backend or UI?
- What is your salary expectation for 160 hours/month?
- When would you be able to start?

## Tempo médio de feedbacks

We'll be selecting and interviewing candidates for the next couple weeks.

## Labels

- Remoto
- Pleno
- Sênior

**Comment by kaisermann** [comment]
Tenho interesse!
