### ISSUE TITLE
[Curitiba - PR] Angular Developer Sr na CINQ TECHNOLOGIES

### ISSUE THREAD

**Issue by cezarsg** [frontendbr/vagas#2821]
## Descrição da vaga
-How about be the protagonist of a complete overhaul on one of the top Class 1 railroad US companies?
-This is the first of a series of projects to modernize the current monolithic system to a service oriented architecture.
-If you like working on a cool environment, where your efford translates into a hightech world, we wanna meet you.
-Experience with complex projects,
-Angular 8;
-Cassandra noSQL.

## Local
Curitiba - PR

## Benefícios
-Health Plan
-Odontological Plan
-Life Insurance
-Pension Plan
-Meal Ticket
-Market Ticket
-Educational Aid

## Requisitos
**Obrigatórios:**
-Experience with complex projects,
-Angular 8;
-Cassandra noSQL.

## Contratação
CLT

## Nossa empresa
We are a company from Paraná, we have more than 27 years of histories, among them CMMI level 3 and GPTW for the 8th year in a row! We work with Software Solutions. We have a very well-structured factory that serves national and international clients. Outsourcing, CINQ professionals who work in clients of different segments and sizes.

We work with the focus of building careers and transforming lives!

## Candidatar-se
Favor enviar e-mail para c.gomes@cinq.com.br informando o título da vaga no assunto do e-mail.

## Labels
- ANGULAR
- CLT
- Sênior

**Comment by rodrigoputini** [comment]
Por favor envie um email para 

> **email@email.com.br**

 com seu CV anexado - enviar no assunto: Vaga NodeJS

------------
tem certeza?????????

**Comment by cezarsg** [comment]
> Por favor envie um email para
> 
> > **[email@email.com.br](mailto:email@email.com.br)**
> 
> com seu CV anexado - enviar no assunto: Vaga NodeJS
> 
> tem certeza?????????

Obrigado por avisar, corrigido!!!

**Comment by pedroferreirazup** [comment]
É possivel homeoffice?

**Comment by cezarsg** [comment]
> É possivel homeoffice?

Não tenho está informação. Manda o CV com está observação por favor.
