### ISSUE TITLE
[São Paulo] Front-end Developer na Espresso Labs

### ISSUE THREAD

**Issue by espressolabs** [frontendbr/vagas#2824]
## Descrição da vaga

**Sobre a Espresso Labs**
Somos uma software house dedicada a criar sistemas e aplicativos da mais alta qualidade para nossos clientes. Com um pouco mais de 2 anos de empresa já atendemos desde startups em ascensão até multinacionais como C&A e Unilever. Queremos aumentar o nosso time jovem e apaixonado por tecnologia para 40 pessoas até o ano que vem.

**Trabalho**
Temos clientes de uma grande variedade de setores, como automotivo, médico, esportivo, alimentício, entre outros. Dessa forma, sempre surgem novos desafios! Pela confiança dos clientes, geralmente escolhemos as tecnologias que cada um usará. Assim, você tem a possibilidade de moldar o nosso stack de tecnologias e processos das empresas. Atualmente utilizamos Ionic nos nossos aplicativos, mas nos planejamos para fazer a transição para o Flutter neste ano.

Não possuímos dress code e permitimos horários flexíveis para todos os colaboradores.

## Local

Nosso escritório atual fica na Rua Gomes de Carvalho, São Paulo - Vila Olímpia
Mas a partir de abril estamos na região de Pinheiros, perto do metrô Oscar Freire!

## Requisitos

**Obrigatórios:**
- Experiência sólida de HTML, CSS e Javascript
- 1+ ano de experiência com Angular

**Desejáveis:**
- conhecimentos em Ionic
- conhecimentos em Flutter

**Diferenciais:**
- projetos opensource

## Contratação

CLT ou PJ, a combinar

## Como se candidatar

Por favor envie seu CV em: https://espressolabs.com.br/equipe e vamos crescer juntos!

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: oi@espressolabs.com.br

## Labels

- CLT
- Estágio
- Júnior
- PJ
- Pleno

**Comment by espressolabs** [comment]
Pessoal, ainda estamos procurando mais devs!

**Comment by gregorispielmann** [comment]
possibilidade de ful remoto?

**Comment by espressolabs** [comment]
Infelizmente não! Somos flexíveis com home office por alguns dias, mas não conseguimos fazer totalmente remoto. Entretanto, podemos conversar sobre fazer trabalhos pontuais remotamente, nos envie um email!
