### ISSUE TITLE
[PR-Curitiba] Desenvolvedor(a) Android na Vega I.T. 

### ISSUE THREAD

**Issue by heitorri** [frontendbr/vagas#2827]
### Local
Curitiba - PR

### Benefícios
* Horário flexível;
* Café fresquinho à vontade;
* Barbecue + Happy Hour mensal;
* Quick Massage;
* Gympass;
* Beauty Day com barbearia e manicure;
* Inglês In Company;
* Auxílio para cursos e palestras;
* Plano de Saúde;
* Plano Odontológico;
* Refeição no local;
* Vale-transporte.

### Requisitos
* Fluência em JavaScript e conhecimento em alguma biblioteca ou framework (ReactJS, AngularJS ou VueJS);
* HTML e CSS;
* Sass, Less e Stylus;
* Familiaridade com APIs RESTful;
* Experiência com ferramentas comuns de desenvolvimento de front-end como Gulp, Grunt, Webpack, NPM, etc.;
* Desing patterns, Clean Code, SOLID;
* TDD e BDD.

### Diferenciais:
* Conhecimento em UI e UX;
* Conhecimento em Javascript (Mocha, Jest, Chai, etc.) e NodeJS;
* Familiaridade com testes de navegador e depuração;
* Familiaridade com o Agile;
* Conhecimento em Design System;
* GraphQL.

### Contratação
CLT

### Como se candidatar
Enviar currículo para: rh@vegait.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

**Comment by eduardojmatos** [comment]
Olá @heitorri! Ainda falta uma descrição sobre a vaga e as labels pra colocarmos aqui. Pode completar pra gente?
