### ISSUE TITLE
[São Paulo] Front-end Pleno Developer na VIX

### ISSUE THREAD

**Issue by reisraff** [frontendbr/vagas#2829]
## Descrição.

Dominar javascript, html, css e seus principais fameworks.

## Local

Escritório, São Paulo - Vila Olímpia

## Benefícios

- Plano de saúde/odonto
- VR
- ...

#### Diferenciais

- use softwares/ferramentas que desejar
- sala com bilhar
- ...

## Requisitos

**Obrigatórios:**
- Competência

## Contratação

CLT

## Como se candidatar

Por favor envie um email para rafael.reis@vix.com com seu CV anexado - enviar no assunto: Vaga Frontend Pleno

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dia após cada processo.

## Labels

- Alocado
- CLT
- Pleno

**Comment by LucasCastelo** [comment]
Enviado!

**Comment by reisraff** [comment]
Still Alive!

**Comment by reisraff** [comment]
Still alive.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
