### ISSUE TITLE
[Recife] Leet - Front-End Developer

### ISSUE THREAD

**Issue by netoabel** [frontendbr/vagas#283]
A Leet é uma empresa de tecnologia que atua no mercado de marketing e comunicação há 3 anos. Desenvolvemos software como serviço para otimizar o desempenho e melhorar os resultados de quem usa as redes sociais para alcançar seu público.

Somos um time enxuto e essencialmente colaborativo, que tem como missão desenvolver soluções escaláveis com qualidade e agilidade. Trabalhamos com um processo bem definido e centrado nas pessoas, que reflete a realidade do mercado e sua demanda por flexibilidade e respostas rápidas a mudanças. Como parte desse processo, integramos o design da experiência do usuário (UX) ao desenvolvimento ágil para que consigamos entregar software de qualidade, com código limpo que funciona.

## Como Front-End Developer, esperamos que você:

- Compreenda perfeitamente texto e áudio em inglês;
- Tenha experiência e conhecimento sólido em Javascript;
- Tenha conhecimento sólido em CSS e pré-processadores (sass, less, stylus);
- Tenha experiência com task runners (gulp, grunt);
- Seja capaz de trabalhar em equipe, em times auto-gerenciáveis;
- Já tenha trabalhado com métodos ágeis de desenvolvimento (XP, Scrum);
- Tenha experiência com AngularJS 1.x;
- Seja proficiente em Git e UNIX;
- Tenha interesse em UX;

## Consideraremos um diferencial se você:

- Tem alguma experiência com práticas de desenvolvimento ágil de software, como TDD e Integração Contínua;
- Já se envolveu no processo de análise e design de arquitetura de projetos de software;
- Tem conhecimento sólido em padrões de projeto, refatoração e testes unitários;
- Conhece e já implementou progressive web apps;
- Conhece e já trabalhou com web components;
- Domina programação funcional em Javascript;
- Conhece AngularJS 2;
- Conhece React e arquiteturas Flux e Redux;
- Sabe como otimizar performance no Front-End;
- É capaz de estruturar e implementar soluções em Javascript sem o uso de recursos de frameworks;
- Fala inglês fluentemente;

## O que oferecemos:

- Salário competitivo (de acordo com a qualificação e experiência);
- Ambiente de trabalho criativo e descontraído;
- Incentivo financeiro para cursos, eventos e treinamentos;
- Acesso a cursos online;
- Café, refrigerante e cerveja à vontade;

## Se interessou?

Envie seu currículo, GitHub, LinkedIn e pretensão salarial para careers@leet.tech.

**Comment by LFeh** [comment]
Opa @netoabel, quais as labels?

**Comment by netoabel** [comment]
Opa! `CLT` e `Alocado`.

Valeu!

**Comment by XLucifer** [comment]
Vaga ainda em aberto?

**Comment by netoabel** [comment]
@XLucifer , ainda está em aberto sim. Lembrando que a vaga é presencial em Recife!

**Comment by XLucifer** [comment]
@netoabel No meu caso, eu sou do RS, mas estou querendo morar no nordeste. Por isso estou procurando pelos empregos, antes.
Enviei o email com os meus dados, meus ultimos trabalhos e curriculo.

Abraços

**Comment by sergiohampel** [comment]
@netoabel, fiquei sabendo que a vaga ainda está em aberto. Procede?

**Comment by netoabel** [comment]
Opa @sergiohampel, tá em aberto sim!

**Comment by WandersonAlves** [comment]
Acabei de enviar, pertinho de casa a Leet ❤️

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by netoabel** [comment]
Opa @LFeh, foi mal, a vaga já foi preenchida. Vou fechar a issue. Valeu!
