### ISSUE TITLE
[Belo Horizonte] Fullstack Developer na nata.house

### ISSUE THREAD

**Issue by maryarossellini** [frontendbr/vagas#2835]
Para nós, software house vai além da definição tradicional. Colaboração, espírito jovem e excelência: esses são os pilares da nossa casa! Criamos produtos de software, tornando nossos os desafios de todos os clientes.

A *nata.house* é especializada no ecossistema JavaScript, trabalhando com React, React Native e NodeJS. Com isso, construímos um hub de desenvolvimento para nossos talentos e, por consequência, fortalecemos nossa cultura de qualidade de software.

Com forte crescimento nestes dois anos de existência, nos preocupamos em construir um time com pessoas talentosas, alinhadas à cultura e aos objetivos da empresa. Além disso, buscamos constantemente maneiras de engajar, motivar e desenvolver os colaboradores para que seu crescimento acompanhe o da *nata*.

**Você precisa ter:**

Conhecimento de linguagem JavaScript (preferencialmente nos frameworks React, React Native e/ou NodeJS)

Noções de conceitos e ferramentas arquiteturais referentes ao ecossistema de aplicações back-end, além de uma análise crítica e pragmática para utilizá-las dependendo do contexto da solução;

Fascínio não só por desenvolver, mas também pela melhoria contínua e por práticas garantem a qualidade do seu código;

Desejável conhecimento em Inglês.

**Procuramos alguém que:**

- Têm interesse em atuar como referência técnica, transmitem seu conhecimento para seus pares de maneira clara;
- Apoiam a resolução de problemas, tem proatividade e orientação para resultados,
- São capazes de selecionar recursos de trabalho, tais como metodologias e ferramentas de desenvolvimento de sistemas, planejando etapas e ações de trabalho.
- Têm interesse em fomentar um ambiente colaborativo para todos,
- Atuam com autonomia, usando a liberdade para opinar em processos e questões relacionadas ao cliente quando for preciso,
- São capazes de se adaptar a ambientes ambíguos e de colaborar em situações difíceis;
- Buscam sempre adquirir mais conhecimento,
- São abertas a novos pontos de vista e maneiras de pensar.

**São algumas vantagens de ser um *nativo*:**

- Carga horária de 40 horas semanais, de segunda a sexta;
- Temos vale-refeição/alimentação Sodexo de R$ 22,05 por dia;
- Para a galera do busão, vale-transporte de acordo com a necessidade, ou, se preferir, auxílio combustível no valor de R$120, sem desconto em folha;
- Bônus anual, pois, afinal, crescemos juntos! Se a empresa tem lucro, o mérito é seu e parte do lucro também;
- Se você está se desenvolvendo e gerando resultado, por quê não receber proporcionalmente? Nada de ficar estagnado: temos plano de carreira bem definido
- Who run the world? You! Temos incentivo ao aprendizado de inglês;
- Segurança extra com o nosso Seguro de Vida.
- Lanche à vontade;
- Horário flexível;
- Um happy hour mensal pago pela empresa;
- Auxílio financeiro para cursos, eventos e capacitações;
- No dress code (be you!)

Se interessou? Para se candidatar, basta preencher o [formulário](https://forms.gle/NnWCtNosUPhYbBECA) e boa sorte! :)

**Comment by AckylaF** [comment]
Olá, alguma oportunidade para alguém que está começando e afim de mostrar serviço?

**Comment by maryarossellini** [comment]
> Olá, alguma oportunidade para alguém que está começando e afim de mostrar serviço?

Ei, AckylaF! Infelizmente não temos vagas abertas para Junior hoje! Mas fique atento nas nossas redes sociais para futuras oportunidades :)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
