### ISSUE TITLE
[São Paulo] Front-end Developer na Digibee

### ISSUE THREAD

**Issue by leandro-adinolfi** [frontendbr/vagas#2839]
## Descrição da vaga

Empresa de Tecnologia que desenvolve e comercializa uma Plataforma SaaS de Integração "no-code" 
Desenvolver o Front-end da Plataforma baseado em React 
Entender e otimizar a experiência do usuário da Plataforma
Aderir às melhores práticas no desenvolvimento de UI e UX
Contribuir em decisões de arquitetura sobre novas partes do projeto
Elaboração de funcionalidades com responsividade e acessibilidade
Construir componentes reutilizáveis e performáticos

## Local

Escritório, São Paulo - Vila Olímpia

## Benefícios

- Remuneração Fixa
- Ambiente altamente inovador e descontraído operado pela WeWork
- Remuneração Competitiva

#### Diferenciais

- No dress code
- Horário flexível

## Requisitos

**Obrigatórios:**
- React
- Proficiência em JavaScript / ES6, incluindo DOM
- Proficiência em React Hooks
- Sólida experiência em Git
- Bom entendimento com Design Patterns tanto para JS quanto para React
- Sólida experiência com controle de estado - lib Redux
- CSS in JS (styled-components ou emotion)
- Ter conhecimento de Scrum
- Viciado em escrever código limpo, bonito e organizado, com boa documentação de suas implementações e utilização de design patterns
- Sólida experiência com bibliotecas de Estrutura de Dados - Immutable.js

**Desejáveis:**
- GraphQL
- Rematch
- Unit test com JEST
- Testes E2E com Cypress

## Contratação

PJ

## Nossa empresa

A Digibee está revolucionando o mercado de tecnologia com sua plataforma SaaS de integração "no-code". Atualmente temos mais de 80 clientes executando cargas de trabalho críticas, estamos negociando uma segunda rodada de investimentos e temos um agressivo plano de expansão nacional e internacional. 
Utilizamos tecnologia de ponta como Kubernetes, Arquitetura baseada em Micro-serviços, Istio, Mongo, RabbitMQ, Redis, ElasticSearch, JavaScript e React.

## Como se candidatar

Por favor envie um email para leandro@digibee.com.br com seu CV anexado e Linkedin - enviar no assunto: Vaga Front-end Developer 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

## Labels

- 🏢 Flexível
- 🏢 Presencial
- 👦 Júnior
- 👨 Pleno
- 👴 Sênior
- ⚖️ PJ

**Comment by LucasCastelo** [comment]
Enviado!
