### ISSUE TITLE
[ FREELA ] Front-end Developer

### ISSUE THREAD

**Issue by eversonjp** [frontendbr/vagas#284]
## **DESCRIÇÃO DO JOB**
Buscamos uma pessoa que esteja comprometida com a qualidade e principalmente com prazos. Não vamos dar prazos absurdos então você terá tempo para fazer com qualidade. Os projetos que temos em vista, não são complexos mas também não são coisas para iniciantes. Precisamos de alguém com qualidade e experiência no desenvolvimento do front-end.

Temos nossa metodologia que será repassada para que possamos dar manutenção depois, sem comprometer nosso tempo interno.

## **LOCAL**
Da sua casa mesmo, completamente remoto.

## **REQUISITOS**
Domínio de HTML5, CSS3, JavaScript
Photoshop e talvez Fireworks
Projetos em WordPress
Experiência com bibliotecas/frameworks Javascript (jQuery, NodeJS, etc)
Experiência com sites responsivos/grids fluidos
Fazer controle de versão (Git)
Automatização de tarefas (Gulp)
Uso de Stylus/LESS/SASS

## **PARA SE CANDIDATAR**
Por favor, envie-nos um email para falecom@voltsdigital.com.br com seu GIT ou portfolio para que possamos analisar seus trabalhos.

**Comment by emanuelgsouza** [comment]
Olá. Tem alguma regra na hora de enviar o email, como por exemplo, o título ser de uma determinada forma?

**Comment by eversonjp** [comment]
Não, nenhuma regra quanto a isso.

	Everson Pereira
(47) 3043-4082
	everson@voltsdigital.com.br
volts.ag



Emanuel G escreveu:

**Comment by emanuelgsouza** [comment]
Currícul enviado @eversonjp

**Comment by Marlysson** [comment]
É remoto full-time?

**Comment by eversonjp** [comment]
É freela, @Marlysson.

**Comment by ribeiroevandro** [comment]
Email enviado.
