### ISSUE TITLE
[Belo Horizonte] Front-end Developer na Symplicity Brasil

### ISSUE THREAD

**Issue by cecimeira** [frontendbr/vagas#2840]
## Nossa empresa

A Symplicity é uma empresa de tecnologia dos EUA que possui o software líder mundial em sucesso para estudantes. Com duas décadas de experiência no espaço de Tecnologia Educacional, estamos presentes em mais de 1.000 universidades em todo o mundo.
A Symplicity adquiriu recentemente a Contratanet, a maior rede integrada de portais de carreira para Instituições de Ensino no Brasil, fortalecendo suas operações no país e está recrutando talentos para trabalhar em nosso escritório em Belo Horizonte.

## Local

Savassi, Belo Horizonte - MG

## Benefícios

- Plano de Saúde Allianz
- Plano Odonto Inpao
- Sodexo - VR ou VA
- VT
- 40 horas semanais com flexibilidade
- Snacks
- Ginástica Laboral
- Aulas de Inglês
- Experiência Global

## Requisitos

**Obrigatórios:**

- Experiência de mercado no desenvolvimento de Web ou UI;
- Habilidade em HTML / CSS, JavaScript;
- Conhecimento de Angular e controle de versão (preferencialmente Git);
- Experiência anterior em equipes de desenvolvimento de produtos em um ambiente Ágil;
- Inglês para colaboração com membros de nossa equipe de design dos EUA.

## Como será o seu dia a dia?

- Nossa equipe de projeto desenvolve pesquisas centradas no usuário, design de experiência e desenvolvimento de interface do usuário em estreita colaboração com equipes de gerenciamento de produto, engenharia, sucesso do cliente e vendas.
- Ser responsável pela interface e experiência do usuário.
- Desenvolver a interface do produto com o uso de HTML, CSS / SASS, JavaScript.
- Contribuir para a criação e manutenção de documentação para sistemas de design em suporte a desenvolvedores das equipes de toda a empresa;
- Pesquisar e recomendar o uso de componentes e bibliotecas de software livre que atendam às especificações da interface do usuário;
- Codificar experiências de usuário universalmente acessíveis que sejam compatíveis com WCAG 2.0 AA;
- Realizar o desenvolvimento orientado a testes.

## Contratação

CLT

## Como se candidatar

- Enviar um email para ccarvalho@symplicity.com com seu CV anexado e assunto: Vaga de Front-end
- Acessar: https://facaparte.contratanet.com.br/vaga/visualizar.aspx?v=1767983

## Labels

- CLT
- Time internacional
- Belo Horizonte - MG

![logo](https://user-images.githubusercontent.com/60138630/72804646-9dfdb200-3c2f-11ea-8694-d42037f18211.png)

**Comment by danielswater** [comment]
Remoto?

**Comment by cecimeira** [comment]
Bom dia,

Não, essa vaga seria para atuar em nosso office na Savassi - BH.

Regards,

Cecília




________________________________
De: danielswater <notifications@github.com>
Enviado: terça-feira, 21 de janeiro de 2020 11:08
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: cecimeira <ceci_meira@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [Belo Horizonte] Front-end Developer na Symplicity Brasil (#2840)


Remoto?

**Comment by AckylaF** [comment]
Olá, alguma oportunidade para alguém que está começando e afim de mostrar serviço?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
