### ISSUE TITLE
[São Paulo] Front-end Developer na BovControl

### ISSUE THREAD

**Issue by adonaipinheiro** [frontendbr/vagas#2844]
## Nossa empresa
Olá, nós somos a Bovcontrol!

E nós estamos revolucionando o agribusiness no mundo!

Somos uma startup global que vem conectando todas as vacas e fazendas do planeta numa 'nuvem diferente' (antes do modismo do blockchain) - com o objetivo de erradicar a fome no mundo, empoderando produtores rurais com tecnologia para serem mais eficientes e sustentáveis. Nossas soluções combinam coleta e a análise de dados, para toda a cadeia produtiva.

Os dados são coletados no campo por aplicativos móveis e podem ser analisados por vários meios, por diferentes elos da cadeia (varejo, bancos, processadores de leite, etc).

Alimentar 1 bilhão de pessoas por dia, em 10 anos de existência da empresa, é a nossa meta.

## Descrição da vaga

O(A) profissional terá liberdade para propor e implementar novas soluções de tecnologia, frameworks e soluções. As principais atividades serão:

- Transforme especificações em sequência lógica; fluxogramas; pesquisando soluções.

- Codifica especificações convertendo sequência lógica e fluxo de trabalho em linguagem de programa.

- Verifica a codificação executando execuções de avaliação; código de modificação.

- Documentando código antigo e novo.

- Avança o conhecimento do trabalho para o próximo nível, participando de oportunidades educacionais; lendo publicações profissionais.

## Requisitos

- Mais de 2 anos de experiência em codificação

- Bacharel em Ciência da Computação, Engenharia de Computação e áreas afins;

- Forte conhecimento de padrões de design e engenharia de software;

- Experimente React e React Native

- Experiência em APIs REST

- Experimente o processo de distribuição da App Store e do Google Play

- Aprenda a aplicar diretrizes (Apple, Google ou outras)

- Experiência (Azure, AWS, Google Cloud ou outro)

- Trabalharam com ferramentas de construção e automação;

- Conhecimento de conceitos de design de API;

- Conhecimento em javascript e Git

- Participe de todas as etapas do aplicativo, com foco no desenvolvimento e solução de problemas

- Use o HTML das linguagens de marcação para criar páginas amigáveis

## Local
Sao Paulo/SP - (Berrini)

## Benefícios / Diferenciais
- Horário flexível
- No Dress Code
- Alto potencial de crescimento
- Plano de Stock Option

## Contratação
PJ a combinar

## Como se candidatar
<br>Envie seu CV, Linkedin e Pretensão salarial para sarita@bovcontrol.com

## Labels
- 🏢 Flexível
- 🏢 Presencial
- 👨 Pleno
- ⚖️ PJ

**Comment by hallss93** [comment]
pena que é somente presencial
