### ISSUE TITLE
[SP - Com Auxílio] Desenvolvedora(o) Javascript na Liv Up

### ISSUE THREAD

**Issue by iagobyintera** [frontendbr/vagas#2846]
A **Liv Up** é uma empresa incrível que apoia diversas causas sociais, inclusive a de **mais mulheres da área de tecnologia!** Estamos com uma oportunidade aberta para **Desenvolvedora(o) Javascript** com **experiência em um dos frameworks, React, Node ou React Native.**

Estamos desenvolvendo a **melhor arquitetura e as melhores tecnologias** para construir uma plataforma sustentável, escalável e consistente à longo prazo. Tudo isso para **fornecer a melhor performance e experiência à nossos clientes** em todo o Brasil.

Como disse, atualmente nós trabalhamos com **React.js, Node.js e React Native**. Essas tecnologias com pessoas com propósito e dispostas é o que nos faz **crescer exponencialmente 40% ao ano!**

A contratação é **CLT e custeamos toda a transição para SP** caso não seja daqui!

**Página da vaga:** http://byintera.in/vemserliv

**Comment by dancasttro** [comment]
Olá bom dia, está com problema no link da vaga.
