### ISSUE TITLE
[Home Office] Front-end Junior na Monday

### ISSUE THREAD

**Issue by andreas-monday** [frontendbr/vagas#2849]
**Descrição da vaga**
Estamos buscando um Front end web developer Jr

**Local**
Home Office

**Qualificações**
Sólidos conhecimentos em HTML e CSS

**Como se aplicar**
Favor **enviar portfolio** para contato@monday.com.br com o assunto: Jr Front End

**Labels**
PJ
Júnior
Home office

**Comment by threze** [comment]
Enviado

**Comment by danielswater** [comment]
Só junior? Senior n rola?

**Comment by edsonvieirademetrio** [comment]
CV enviado

**Comment by miguelrisquelme** [comment]
Enviado

**Comment by randhson** [comment]
Enviado.

Randson N. dos S. França +55 79 99843 9878+55 79 99138 7628 

    Em quinta-feira, 23 de janeiro de 2020 08:35:25 BRT, Miguel Riquelme <notifications@github.com> escreveu:  
 
 
Enviado

**Comment by viniciusjosecunha** [comment]
Enviado

**Comment by miguelrisquelme** [comment]
I'm replying that email, but I don't know what to do

GitHub: github.com/miguelrisquelme
LinkedIn: @miguelrisquelme




On Jan 23, 2020 10:11 AM, Vinícius Cunha <notifications@github.com> wrote:
>
> Enviado
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.




Enviado

**Comment by eriktos** [comment]
Bom dia!Enviado!

Em qui, 23 de jan de 2020 00:18, Andreas Piekarz <notifications@github.com>
escreveu:

**Comment by andreas-monday** [comment]
Inscrições encerradas, 
Muito obrigado pelo contato de todos.
