### ISSUE TITLE
[GO - Rio Verde] ON GO - Analista/Desenvolvedor WEB

### ISSUE THREAD

**Issue by fykos** [frontendbr/vagas#285]
## Empresa
 O ON GO é um aplicativo de mobilidade urbana, com táxi, mototáxi e motofrete.

## Descrição da vaga
 Remodelar o banco de dados com base no já existente.
 Desenvolver um painel em PHP/MySQL/Javascript/jQuery/HTML/CSS baseado no painel já existente.
 Efetuar testes e corrigir bugs e desenvolver novas implementações
Caso conheça alguém, também precisamos de programador iOS e Android.

## Posição
 Pleno

## Tipo de contratação
 Presencial, CLT, PJ. 

## Requisitos
 Desenvolvedor de painel administrativo em PHP/MySQL.

###### Obrigatórios
 Já possuir um painel/sistema web em PHP/MySQL já publicado ou em fase de testes.

## Com quem você vai trabalhar
| ![](https://github.com/fykos.png?size=117) | ![](https://github.com/waister.png?size=117) |
| --- | --- |
|[Elis](https://github.com/fykos) |[Waister](https://github.com/waister) |
|Desenvolvedor iOS|Desenvolvedor Android|

## Como aplicar
 Envie um e-mail para ongo-github@elisnunes.com.br

## Contato
 WhatsApp: (64) 99299-4416
 E-mail: ongo-github@elisnunes.com.br

**Comment by LFeh** [comment]
Opa, qual o nivel?
