### ISSUE TITLE
[Remote] Senior Front-end/React Developer

### ISSUE THREAD

**Issue by pwiszowaty** [frontendbr/vagas#2850]
## Job overview

At [FunnelGuard](https://www.funnelguard.co), we help companies maximize their lead generation and customer acquisition potential. We automatically map and monitor customers' marketing funnels to provide relevant, actionable, and up-to-the-minute information so they can identify and resolve issues that stop them from acquiring customers and waste marketing budget. 
You can think of us as Uptime Monitoring + Incident Response and Awareness for Marketers. We are passionate about building delightful software services to help customers succeed, and we are looking for great people to join us in that mission. You will join a small, tightly-knit team as the fourth team member to help our customers excel in their digital marketing operations. Our focus is to combine several different types of digital experience monitoring into a turn-key service built for marketers.

As a front-end engineer, you will work hand-in-hand with our team of product managers, designers, and software engineers. Together, we will develop and maintain the web application and Chrome extensions used by our customers. We are looking for engineers who are not only passionate about building web applications but also cultivate the teams that make them. We are looking for a motivated person with the experience to solve problems at scale and versatility to embrace the challenges that arise from pushing bleeding edge technology forward.

As an early senior member of our engineering team, you will have a huge impact on our company, from the product to the team, and therefore to our customers and our growth. You will also report directly to the CTO and Co-Founder

## Location

We're looking for remote developers located in Brazil. Our core team is located in San Francisco, CA. 

## Benefits

Our company offers exceptional compensation in the form of salary and stock options for early employees.

## Requirements

- Minimum of 8 years of professional software engineering experience on a released product or production service
- Highly skilled in JavaScript / Typescript, React 
- Experience with state management (Redux or similar) 
- Good verbal and written communication skills in English
- Experience with implementation of Design Systems (i.e. System UI, Styled System) 

## Apply
[https://apply.workable.com/funnelguard/j/7906A177E3/](https://apply.workable.com/funnelguard/j/7906A177E3/)

## Labels

- ⚖️ PJ
- 🏢 Remoto
- 👴 Sênior

**Comment by alvsgustavo** [comment]
Hi! Do FunnelGuard have any internship programme?

**Comment by THAYLLER** [comment]
Eu não tenho todos os requisitos mas queria saber qual a média salarial dos devs ai?

**Comment by dersonsena** [comment]
@pwiszowaty it was submmited! =)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
