### ISSUE TITLE
[Portugal] Front-end Developer na Join Us It 

### ISSUE THREAD

**Issue by parisamorim** [frontendbr/vagas#2851]
Competências:
Mínimo de 02 e máximo de 15 anos de experiência nas seguintes tecnologias:

- IT Background (or appropriate post-graduation qualification);
- Advanced experience of coding JavaScript plus HTML and CSS;
- Solid experience of using client-side JavaScript frameworks (ANGULAR);
- Solid understanding of browser performance best practices;
- Awareness and experience in using agile Software Development Life Cycle models & development tools;
- Experience of using established design patterns;
- Mandatory AngularJS and fluent english;
- We offer Visa support.
- Local de trabalho: Lisboa e grande Lisboa;
- Data de início: Imediato, pelo período de 12 meses e com possibilidade de contratação directa no 
final;

https://www.joinusit.pt/oportunidades/frontend-developer/ ou recrutamento@joinusit.pt com o assunto do email a vaga em questão.

**Comment by emirdeliz** [comment]
Somente presencial?

**Comment by parisamorim** [comment]
> Somente presencial?

Sim, é presencial.
