### ISSUE TITLE
[São Paulo] Front-end/React Developer no Hospital Israelita Albert Eistein

### ISSUE THREAD

**Issue by adhenrique** [frontendbr/vagas#2852]
## HIAE - Innovation Lab

Nós aqui da Innovation Lab - Hospital Israelita Albert Einstein, estamos em busca de um(a) desenvolvedor(a) React (16+ hooks, redux, redux-thunk, reselect, react-router, Material UI, etc). Ufa… bastante coisinha.

Mas calma, vamos por partes. O Innovation Lab é um departamento de inovação do qual cuida da idealização de novos produtos para o Einstein. Internos ou externos, vc pode fazer parte de projetos reais e mundiais na área de Educação e Saúde.

Agora falando do seu espaço, você fará parte de um time focado no front-end da nossa aplicação, caminhando juntamente com nossos Ui’s/Ux’ers. Criando telas e componentes reutilizáveis.

Sobre você, esperamos que vc seja um(a) cara/mina legal 😎! Só isso. 

## Dá uma olhada nos requisitos:
- Pró atividade
- Parceria no momento do fogo 🔥 
- Lógica de programação (Algoritmos, soa assustador pra vc? Deve ser o básico!)
- Analista de problemas (Não pode ficar com medo de pegar código legado 😋)
- React, react e react sempre. (Pra que serve o useCallback() ?)
- Javascript avançado. (Vamos e convenhamos, spread operator é um sucesso?!)
- Antenado(a). (Tem muitas tecnologias novas surgindo. Você poderia nos indicar uma?)
- Se vc souber desenvolver um bom Container, HoC, hooks, render props 🐎  ou souber algo sobre testes unitários, já é um grande diferencial.
- Vc gosta de café? 🤔 

Bem…
Atualmente, nós temos diversos problemas - mas é claro! Qual aplicação não tem? E você pode ser o(a) **Cara/Mina** ou nos indicar o(a) **Cara/Mina** para resolvê-los haha.

## Benefícios e diferenciais:
- Nosso espaço: Estamos localizados na Vila Mariana, bem pertinho da estação do metrô.
- Disponibilizamos pra vc: Qualidade de vida com muito espaço verde, muita cultura e diversidade, e o melhor, um **Macbook** só seu 💻 
- Alocação: Presencial, imediata e infelizmente, não temos alocação remota.
- Contratação: PJ - 1 ano com possibilidade de renovação.
- Experiência: Junior, Pleno, Senior… Não importa. Só vem!
- Horário: Flexível, 8h

Se vc se interessou, deixe um comentário ou envie um e-mail para adenilton.ribeiro@inovacaoeinstein.com.br | camila.pina@inovacaoeinstein.com.br com o assunto **Vaga Front-end/React**

## Labels
- Alocado
- PJ
- Júnior
- Pleno
- Sênior

**Comment by felri** [comment]
Estou recebendo

>A mensagem não foi entregue para camila.pina@inovacaoeistein.com.br porque o domínio inovacaoeistein.com.br não foi encontrado. Verifique se há erros de digitação ou espaços desnecessários e tente novamente.

**Comment by adhenrique** [comment]
> Estou recebendo
> 
> > A mensagem não foi entregue para [camila.pina@inovacaoeistein.com.br](mailto:camila.pina@inovacaoeistein.com.br) porque o domínio inovacaoeistein.com.br não foi encontrado. Verifique se há erros de digitação ou espaços desnecessários e tente novamente.

Fala meu brother. Obrigado por avisar. Corrigi o e-mail dela na descrição.
Tente novamente.

**Comment by caioAugustoRodrigues** [comment]
Tenho interesse!
Podem checar meus projetos(completos e em desenvolvimento) por aqui mesmo!
Meu linkedin: https://www.linkedin.com/in/caio-augusto-rodrigues-pantojo-029288195/

**Comment by PatricSPires** [comment]
Tive problemas para mandar o email para a Camila.

**Comment by JeanGoncalves** [comment]
Gostei demais da "chamada" para oportunidade da vaga.
Parabéns para quem fez o texto! :clap:

**Comment by lucasfieri** [comment]
Parabéns pelo texto, ficou show
