### ISSUE TITLE
[São Paulo] Front-end Developer na São Paulo Urbanismo

### ISSUE THREAD

**Issue by dev-spurbanismo** [frontendbr/vagas#2856]
## Descrição da vaga
Estágio Front-End Developer 

## Local
Rua São Bento, 405, 16º andar
Escritório, São Paulo - Centro

## Benefícios
- VR de R$ 30,76/dia
- VT
- Bolsa auxílio

## Requisitos
 - javascript
 - html/css
 - git

**Obrigatórios:**
 - Estar matriculado em curso superior
 - Não estar cursando o último semestre deste curso

**Desejáveis:**
 - Frameworks frontend modernos (usamos vuejs)
 - Desenvolvimento e integração de API's REST (nodejs, php ou C#)

**Diferenciais:**
- Projetos opensource

## Contratação
Estágio alocado. 30h semanais

## Nossa empresa
Empresa pública municipal voltada ao planejamento urbano da cidade de São Paulo

## Como se candidatar
Se tiver interesse de participar do nosso processo seletivo por favor preencha o formulário abaixo:
https://forms.gle/4956HvMbkpym41uX7
e aplicar-se no teste:
https://github.com/dev-spurbanismo/nasa-projects

## Tempo médio de feedbacks
1 a 2 semanas

E-mail para contato em caso de não haver resposta: treinamento@spurbanismo.sp.gov.br

## Labels
- Alocado
- Estágio

### Github
https://github.com/spurb

**Comment by robertveloso** [comment]
Essa proposta de trabalho também funciona na modalidade remoto?

**Comment by dev-spurbanismo** [comment]
@robertveloso. Infelizmente não. Apenas alocado no endereço especificado.

**Comment by dev-spurbanismo** [comment]
Primeira fase encerrada. Obrigado a todos que se inscreveram. Vamos responder a todos.
