### ISSUE TITLE
[Porto Alegre - RS / Sydney - AUS] Web / API Developer - Angular.JS / Node.JS

### ISSUE THREAD

**Issue by patrickds** [frontendbr/vagas#286]
## Empresa
Fundada há 24 anos, empregando as mais avançadas tecnologias de informação e o controle efetivo e ágil de projetos. Atualmente com mais de 400 colaboradores, atuando em Porto Alegre/RS, Caxias do Sul/RS, Curitiba/PR, São Paulo/SP, Rio de Janeiro/RJ e Sidney/AUS.

Nosso foco são as pessoas e a cultura da empresa. Bons resultados são gerados a partir da combinação de um bom clima organizacional, com colaboradores satisfeitos e uso de práticas e ferramentas adequados. 
- Indivíduos e interação entre eles – mais que processos e ferramentas
- Software em funcionamento – mais que documentação abrangente
- Colaboração com o cliente – mais que negociação de contratos
- Responder a mudanças – mais que seguir um plano

#### Serviços
Teste Center, Projetos de Software, Fábrica de Software, Outsourcing e Consultoria de Software e Métodos Ágeis.

## Descrição da vaga
Como Desenvolvedor Web/API no nosso time, você será responsável por definir a solução, desenvolver, testar e documentar aplicações.

### Mais informações

- Onboarding do projeto com todo o time em Sydney, Australia.
- Membros do time de Porto Alegre revezando em Sydney a cada 3 meses.
- Time Ágil extremamente colaborativo em Porto Alegre e Sydney.
- Ambiente de trabalho que promove aprendizado contínuo e experimentos com novas tecnologias.
- Você vai trabalhar com um time de alto calibre técnico distribuído e em fusos diferentes.

## Posição
Junior, Pleno ou Sênior

## Tipo de contratação
 CLT

###### Obrigatórios

- Experiência comprovada com desenvolvimento web de aplicações que utilizam Angular.JS e Node.JS
- Bons conhecimentos em integração com APIs RESTful, integração contínua e TDD
- Vivência em projetos com métodos ágeis
- Inglês Avançado - Escrita - Leitura - Compreensão - Conversação

## Remuneração

Salário a combinar + benefícios

## Como aplicar e Contato

Email: [vagas_australia@dbserver.com.br](vagas_australia@dbserver.com.br)

**Comment by XLucifer** [comment]
Enviado

**Comment by camillodev** [comment]
Existe chance de ficar no time de Sydney?

**Comment by patrickds** [comment]
Olá Rafael.
No momento não há possibilidade de alocação em Sydney.
