### ISSUE TITLE
[São Paulo] Frontend Engineer na Domvs

### ISSUE THREAD

**Issue by thaisvilladal** [frontendbr/vagas#2862]
## Descrição da vaga

Projeto em um cliente do segmento de Meios de Pagamento.

## Local
Presencial - São Paulo, SP - Região da Faria Lima

## Benefícios
- Férias remuneradas para contratação PJ.
- Para CLT os benefícios são (Vale transporte, Vale refeição e Assistência Médica).

## Requisitos

**Obrigatórios:**
- Experiência na criação de páginas responsivas, web e mobile.
- Experiência em desenvolvimento de aplicações web utilizando Javascript avançado (OO, herança, prototipação, design pattern, jQuery, ES6). 
- Experiência em CSS Avançado (SASS e LESS) e CSS3.
- Experiência em suporte a browsers antigos (graceful degradation).
- Conhecimentos de Regex.
- Domínio de protocolo (HTTP, HTTPS, cross domain).
- Conhecimentos de arquitetura backend (servidor web, estático, BFF).
- Conhecimento de React, Vue.

**Desejáveis:**
- Conhecimentos relacionados a performance (gzip, minify, quantidade de requests).
- Testes automatizados.
- Conhecimento em Apache Velocity.
- Conhecimento de virtualização (Docker, Mesos).

## Contratação
PJ ou CLT por prazo indeterminado - salário a combinar

## Nossa empresa
A DOMVS é constituída de profissionais com larga experiência em gestão de empresas, onde efetivamente participam de decisões de negócios embasadas pela utilização estratégica da tecnologia da informação.
Estamos presentes no Brasil e também em Portugal.

## Como se candidatar
Por favor envie um e-mail para consultoria_villadal@domvs.com.br com seu CV anexado - enviar no assunto: Vaga Eng Front 

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: consultoria_villadal@domvs.com.br

## Labels
- PJ
- CLT
- Pleno
- Sênior

**Comment by emirdeliz** [comment]
Aceita remoto?

**Comment by thaisvilladal** [comment]
Infelizmente somente presencial 🙁

Thais Villadal
Headhunter e Consultora de Carreiras
E-mail: villadalrh@hotmail.com
Tel e WhatsApp: (5511) 97386-5774
Skype: thais.villadal1
Villadal RH - Consultoria em Recursos Humanos<http://villadalrh.wix.com/villadalrh>

________________________________
De: Emir Marques <notifications@github.com>
Enviado: segunda-feira, 27 de janeiro de 2020 10:20
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: Thais Villadal <villadalrh@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [São Paulo] Frontend Engineer na Domvs (#2862)


Aceita remoto?
