### ISSUE TITLE
[São Paulo] Front-end Developer na Geru

### ISSUE THREAD

**Issue by rafaelsirotheau** [frontendbr/vagas#2863]
## Descrição da vaga

Estamos procurando um (a) profissional para atuar junto do nosso Time de Desenvolvedores.
Se você quer trabalhar em uma empresa com propósito, diversidade e um ambiente descontraído, vem trabalhar com a gente!!

A Geru usa **Python** e **Javascript** como suas principais linguagens de programação. Para frontend, utilizamos as seguintes libs:

- React;
- Styled Components;
- Flow (com planos de migração para Typescript);
- GraphQL (Node.js)

Além disso, utilizamos **Jest/Enzyme** para testes unitários e integrados (queremos migrar para react-testing-library).

## Local

Escritório, São Paulo - Pinheiros

## Benefícios

- Flexibilidade de horário;
- Plano de saúde Amil 700 (sem desconto para nossos funcionários);
- Vale refeição (R$ 27,00 dia);
- Vale transporte;
- Seguro de vida;
- PLR.

#### Diferenciais

- Reuniões semanais do **Capítulo de Front-end**, onde discutimos novas tecnologias (e a possibilidade de utiliza-las), melhorias e soluções para problemas comuns relacionados ao nosso dia a dia.
- No Dress Code: venha como se sente confortável!
- Ambiente descontraído, diverso e inclusivo;
- Snacks e frutas;
- Sala de descompressão, com jogos e video-game;
- Área exclusiva para guardar sua bike;
- Vestiário com Chuveiro;
- Geru Talks

## Requisitos

**Obrigatórios:**
- Javascript/ECMASCript
- HTML5
- CSS3
- React
- Ownership
- Princípios de desenvolvimento de software
- Design Patterns
- Boas práticas e Clean Code
- Cuidado com a UX

**Desejáveis:**
- GraphQL
- Styled Components
- State Management (Redux, MobX, Context)
- Git
- Implementação de testes automatizados (unitários, integrados, ...)
- Tipagem
- Vivência em metodologias ágeis

**Diferenciais:**
- Typescript
- BDD
- TDD
- Node.js

## Contratação

CLT

## Nossa empresa

Nascemos em 2015 com um propósito bem definido: ajudar pessoas. Temos a missão de levar crédito rápido, justo e descomplicado a milhões de brasileiros.

**Com isso, estamos fazendo uma revolução!**

A gente põe a mão na massa para entregar projetos que fujam do tradicional. Não queremos ser iguais os bancos, pelo contrário, somos uma alternativa financeira que combina tecnologia de ponta e humanização de processos para oferecer crédito justo.

**E como fazemos isso? Pensando diferente!**

Nossa cultura proporciona debates, sugestões e uma visão transparente de como organizamos nossas ações na hora de atacar alguma tarefa ou acelerar algum projeto. Tudo isso de forma simples, clara e honesta.

**Mas, como é o ambiente da Geru?**

Já pensou em trabalhar em uma balada? Mas, calma, não é como DJ. Nossa estrutura é uma antiga balada de São Paulo. Esse charme dá ao nosso escritório um estilo único.

**E sobre o pessoal?**
Nosso Time é diversificado! Temos em nossos valores o claro posicionamento de que somos uma empresa aberta a novas ideias e culturas. São mais de 140 colaboradores livres de preconceitos e repletos de respeito as diversas individualidades.

## Como se candidatar

Estamos migrando de plataforma, então, por hora, basta realizar o teste localizado em: https://github.com/geru-br/frontend-challenge

Por favor, adicionem, no README do seu teste, o nível e pretensão salarial.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 4 dias após envio do teste.

## Labels

- Alocado
- CLT
- Júnior
- Pleno
- Sênior

**Comment by cardoso0** [comment]
Olá, fui no site em busca de vagas e não encontrei para Júnior. Poderia por gentileza confirmar?

**Comment by rafaelsirotheau** [comment]
Oi @cardoso0! Estamos em processo de migrar a plataforma de recrutamento, então, ainda não aparece lá.

Mas pode fazer a inscrição usando o link de Pleno. Eu estou olhando cada inscrição e adicionando labels de Junior quando é o caso.

**Comment by cardoso0** [comment]
Obrigado Rafael pela resposta!
    Em quinta-feira, 6 de fevereiro de 2020 11:42:53 BRT, Rafael Sirotheau <notifications@github.com> escreveu:  
 
 
Oi @cardoso0! Estamos em processo de migrar a plataforma de recrutamento, então, ainda não aparece lá.

Mas pode fazer a inscrição usando o link de Pleno. Eu estou olhando cada inscrição e adicionando labels de Junior quando é o caso.

**Comment by hjdesigner** [comment]
Teste finalizado, agora é torce para que decerto o/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
