### ISSUE TITLE
[Rio de Janeiro] Front-End Developer na Wooza Ventures

### ISSUE THREAD

**Issue by albertofilho82** [frontendbr/vagas#2864]
## Descrição da vaga

Desenvolvimento de projetos web e mobile/ Desenvolver código semanticamente correto.
Experiência com HTML5, CSS3, sites responsivos Sólidos conhecimentos de jQuery e noções de Javascript (puro); Angular / react / ionic; Layout responsivo; Mobile first; Html5/ css3 / sass / less; Git

## Local

Barra da Tijuca

## Benefícios

- Plano de saúde
- VR 

#### Diferenciais

- flexibilidade de horário
- frigobar sempre cheio :P
- sala de jogos

Oportunidade de trabalhar em um time de pessoas dedicadas e que amam o que fazem; ambiente de trabalho cooperativo e descontraído
Salário: 6k (negociável) 

## Requisitos

**Obrigatórios:**
- Angular / Ionic / Mobile first

**Desejáveis:**
- React

## Contratação

CLT

## Como se candidatar

Por favor envie um email para rh@woozaventures.com.br com seu CV anexado - enviar no assunto: "Vaga Front-End Developer"

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

## Labels

- Alocado
- CLT
- Júnior
- Pleno
- Sênior

**Comment by Daniray2008** [comment]
ola, a vaga permite trabalhar remotamente?

**Comment by danielswater** [comment]
Vira somente remoto?

**Comment by albertofilho82** [comment]
> Vira somente remoto?

Olá, infelizmente não. 
Temos a flexibilidade de permitir um dia ou outro na semana caso haja necessidade. Mas a vaga é presencial.

**Comment by danielswater** [comment]
> > Vira somente remoto?
> 
> Olá, infelizmente não.
> Temos a flexibilidade de permitir um dia ou outro na semana caso haja necessidade. Mas a vaga é presencial.

Ok, obrigado pelo retorno. Desconsidere meu curriculum enviado agora mesmo

**Comment by portothree** [comment]
@MrS4w você com a label de remoto e não há essa possibilidade. Mandei o meu CV com endereço fora do BR e no momento ainda não tinha o comentário também perguntando sobre remoto. Fui respondido e comecei o processo de testes apenas para perder horas a toa, pois ainda não sabia que não era remoto.
Poderia prestar um pouco mais de atenção em como marca essas labels?

**Comment by MrS4w** [comment]
@portothree se você observar bem, a vaga foi editada! 😉
Sei apenas quando são criadas e aplico as labels.
![image](https://user-images.githubusercontent.com/32140289/74138443-6354bd00-4bd0-11ea-9aa6-f9e4d201dc17.png)

**Comment by portothree** [comment]
@MrS4w te peço desculpas então :)

**Comment by albertofilho82** [comment]
Obrigado a todos que se candidataram. A vaga foi preenchida.
