### ISSUE TITLE
[Rio de Janeiro] Front-end Engineer na Ame Digital

### ISSUE THREAD

**Issue by CamilaTavares** [frontendbr/vagas#2866]
**Descrição da vaga**
Estamos buscando desenvolvedores(as) com experiência em desenvolvimento de aplicações web e mobile - estamos crescendo exponencialmente, e precisamos de pessoas que gostem do desafio de criar novas funcionalidades, de forma rápida e com melhoria contínua. 

Tecnologia é o nosso core - trabalhamos com times onde todos participam ativamente e são responsáveis pelas decisões e metas do negócio.

**Local**
Escritório, Rio de Janeiro.

**Benefícios**
Pacote de remuneração compatível
Benefícios (vale transporte, vale refeição, plano de saúde médico e odontológico)

**Diferenciais**
Ambiente descontraído e no dress code
Ame Talks – conversa semanal sobre a estratégia e tudo o que está rolando na Ame.
Acesso a todo o time o tempo todo - trabalhamos juntos para ir mais longe mais rápido
...
**Requisitos Obrigatórios**
Formação Superior Completa.
Experiência em:
VueJS, Vuex, ReactJS, Redux, React Native, NodeJs e/ou ES6. 
HTML5 e CSS (responsivo). 
Integração com backend via APIs REST (protocolo HTTP). 
Libs conhecidas (lodash, momentjs, etc). 
Ferramentas de controle de versão (GIT). 
Desenvolvimento otimizado para SEO. 
Single page Apps & Progressive Web Apps. 
Programação assíncrona (Promises, Generators, Streams). 
Flexbox. 
Grid CSS. 

**Desejáveis**
Conhecimento/Experiência em:
Aplicação de técnicas TDD e BDD. 
Ferramentas de análise de código (Linters, Análise de complexidade). 
Ferramentas de automação JS (Webpack, Gulp, Grunt). 
Metodologias ágeis de desenvolvimento (Scrum, Kanban). 
Noções de UX e Design de Interação. 

**Nossa empresa**
Oi, somos a Ame!
Somos um fintech trabalhando para simplificar e revolucionar a maneira como as pessoas se relacionam com o dinheiro.

**Como se candidatar**
Por favor, envie a sua candidatura através da nossa página de carreiras, [aqui](https://grnh.se/e2502caf2).

**Comment by vinicius-assis** [comment]
Aceitar junior?

**Comment by RodrigoWebDev** [comment]
Aceita Remoto?

**Comment by diogomoretti** [comment]
Olá @CamilaTavares, consegue colocar a vaga no nosso [template](https://github.com/frontendbr/vagas/blob/master/.github/ISSUE_TEMPLATE/adicionar-nova-vaga.md)?

**Comment by diogomoretti** [comment]
Será fechada a issue até colocar no nosso template.
