### ISSUE TITLE
[São Paulo] Junior Front-End Developer ReactJs

### ISSUE THREAD

**Issue by brunobra** [frontendbr/vagas#287]
## Descrição da vaga

Será responsável por transformar a relação dos nossos clientes com seus usuários. É o cara que dará a “vida “ aos PSDs/layouts, tornando a ferramenta intuitiva e interativa. Nós não estamos procurando apenas um bom programador, mas alguém responsável para o cultivo de uma cultura técnica de excelência: qualidade no código e velocidade. Queremos alguém que pode refletir, validar projeto e ajudar-nos a avançar para encantar nossos clientes e sermos a melhor plataforma de atendimento do mercado. Por fim, que não tenha medo de trabalhar em startup.

## Local

Rua casa do ator, 919 - Vila Olímpia

## Benefícios

- Trabalhar no Cubo (Prédio de Coworking do Itaú)
- Home Office 1 vez por semana

## Requisitos

**Obrigatórios:**
- Organização;
- Confortável em fazer código responsivo e multi-plataforma;
- Excelente conhecimento em CSS, pré-processadores de CSS (SASS, LESS), HTML, JavaScript, jQuery, ReactJS, AngularJS;
- Bons conhecimentos em Grunt ou Gulp ou  Browserify ou Webpack, Git, RequireJS, AMD e REST;
- Ter trabalhado com metodologia ágil;
- Noções de usabilidade

**Desejáveis:**
- Conhecimento em ferramentas de testes (Jasmine, Karma, PhantomJS);
- Polyfill;
- Ter trabalhado/experimentado algum(ns) dos itens abaixo: NodeJS, ES6, Animações em CSS, Design Patterns, Flux design pattern, Alt ou Redux, Ionic/Cordova/Phonegap;

**Diferenciais:**
- Conhecer serviços da AWS(EC2, API Gateway, Lambda, CloudFront, Dynamo DB, RDS)
- Razoável conhecimento em back-end;

## Contratação

Modelo negociável de contratação (CLT / PJ)

## Nossa empresa

A Omnize é uma plataforma inteligente de atendimento que ajuda empresas a conhecerem seus clientes independente do canal de comunicação.Através de nossa plataforma a empresa pode atender clientes por múltiplos canais (chat, voz, vídeo, mensageiros, redes sociais; em breve, email e PABX), com gestão e histórico unificados - ou seja, mantendo uma identidade única do cliente, independente do canal utilizado. Isso resolve o problema do cliente (satisfaz suas expectativas), do atendente (passa a ter mais conhecimento para atender) e do gestor (tem acesso a inteligência para melhorar seus processos).

## Como se candidatar

Se aplique no link:
https://cubo.network/jobs/c8d74f84-720d-4f11-96e8-22eebbc1048e

**Comment by LFeh** [comment]
Boa!

**Comment by bcarvalho89** [comment]
É home office em tempo integral ou alguns dias na semana?

**Comment by brunobra** [comment]
O home office é 1 dia por semana. Vou atualizar na descrição.

**Comment by nativedone** [comment]
@bcarvalho89 se a vaga é pra `ReactJS` não era de se esperar `React Native `como desejável ou diferencial?

Soa um pouco estranho uma vaga de React ter  Ionic/Cordova/Phonegap como desejável e não falar nada de `React Native`. É isso mesmo?

**Comment by MathMesquita** [comment]
**Aplicado :D** 

@nativedone não necessariamente... Eles podem não ter aplicativos nativos para oferecer pros seus clientes, somente webapps, dessa forma só o conhecimento do ReactJS que é necessário... 😄
