### ISSUE TITLE
[Porto Alegre] Front-end Developer na STAFF RH

### ISSUE THREAD

**Issue by tgarziera** [frontendbr/vagas#2870]
Empresa situado na grande Porto Alegre, está entre as 100 empresas mais inovadoras do Brasil, além disso, é uma das melhores empresas para se trabalhar. Projetos com tecnologias de ponta completam a ótima oportunidade!

Desenvolvedor Javascript/Angular

http://www.staffrh.inf.br/Oportunidades/Detalhes/desenvolvedor-javascript---angular/76507

Requisitos:
Graduação em andamento no ramo de tecnologia da informação. 
Requisitos: Banco de Dados: Oracle e Mongo. 
Desejável atuar com elasticsearch. Frameworks**: Angular 5,** HTML, CSS e Javascript; Rxjs; Typescript; Ecmascript 6, Node, express, Webpack e Babel. 
Desejável conhecimento em Gulp. Domínio de Ferramentas de desenvolvimento de TI. 
Metodologia Ágil: SCRUM.
Atividades:
Atuar como desenvolvedor Frontend no projeto. Definir e orientar os desenvolvedores e testadores na implementação dos critérios especificados, bem como a validação da entrega. Atender em 3º nível os sistemas que estão sob sua responsabilidade, propor a otimização de rotinas, processos e procedimentos operacionais. Desenvolver, manter e implantar sistemas de informação em qualquer nível de complexidade que suportem as áreas de negócio. Prover soluções de tecnologia, avaliando de forma analítica e sistêmica os impactos e riscos para o negócio, propondo alternativas e plano de contingência para os desafios encontrados.

www.staffrh.inf.br
Interessados encaminhar curriculo para patriciaberte@staffrh.inf.br

**Comment by danielswater** [comment]
Remoto?

**Comment by tgarziera** [comment]
Oportunidade CLT OU PJ.

**Comment by diegohyenna** [comment]
Home office?

**Comment by tgarziera** [comment]
A oportunidade é CLT OU PJ, presencial.
Não possui contratação home office, nem remoto.
Necessariamente residir em PORTO ALEGRE RS.
