### ISSUE TITLE
[Curitiba - PR] Front-end Developer PL (I250AB) na CINQ TECHNOLOGIES

### ISSUE THREAD

**Issue by cezarsg** [frontendbr/vagas#2872]
## Descrição da vaga

Ei, Dev Front-end: temos uma super oportunidade para você entrar no #TimeCINQ e trabalhar em um projeto nacional cheio de desafios!
Software de escala global utilizado para gerenciamento de ativos e workflow de suporte técnico para equipamentos. Possui diversas integrações com sistemas e provedores de serviços locais para agilizar os processos de manutenção corretiva e preventiva.

Oque você irá fazer:
-Desenvolvimento de aplicações web utilizando Angular
-Modernização de aplicação web já existente
-Correção de bugs
-Participação de daily meetings
-Interface direta com cliente nos EUA e eventualmente Russia

## Local

Curitiba - PR

## Benefícios
-Plano de Saúde
-Plano Odontológico
-Seguro de vida
-Previdência Privada
-Vale Refeição
-Vale Alimentação
-Auxílio Estudo
-GymPass
E não para por aqui! Temos diversos convênios e parcerias legais pela cidade. Dá uma olhada:

https://cinqconvenios.now.sh/#noAction

#### Diferenciais
- Horário flexível
- Vídeo game free
- Muito café!!! ;)

## Requisitos

**Obrigatórios:**
-Angular 8
-HTML
-CSS
- Para essa posição, precisamos que você fale INGLÊS em nível AVANÇADO.

**Diferenciais:**
-.Net Core - C# (Web API)
-Jira
-PCF (Pivotal Cloud Foundry)
-Oracle
-SVN
-Git
-Clarity Design System

## Contratação

CLT 

## Nossa empresa
Somos uma empresa paranaense, possuímos mais de 27 anos de histórias, dentre elas o CMMI nível 3 e somos GPTW pelo 9º ano seguido! Trabalhamos com soluções de Software, possuímos uma fábrica muito bem estruturada que atende clientes nacionais e internacionais. Outsourcing, profissionais CINQ que atuam em clientes de diversos segmentos e diferentes portes. Trabalhamos com o foco de construir carreiras e transformar vidas!

## Como se candidatar
Favor enviar e-mail para c.gomes@cinq.com.br informando o título da vaga no assunto do e-mail.

## Labels
- Angular8
- Inglês
- HTML
- CSS
- CLT
- Senior

**Comment by ednilsonamaral** [comment]
Aceitam remoto?

**Comment by cezarsg** [comment]
Somente presencial mesmo.

Em ter, 28 de jan de 2020 15:45, Ednilson Amaral <notifications@github.com>
escreveu:
