### ISSUE TITLE
[Porto Alegre] Front-end Developer na Join Tecnologia e Design

### ISSUE THREAD

**Issue by JoinTecnologia** [frontendbr/vagas#2873]
## Descrição da vaga

- Desenvolvimento de aplicações frontend web, utilizando VueJS, integrando com APIs desenvolvidas pela equipe backend;
- Eventuais desenvolvimentos e manutenções de aplicações front utilizando CSS com Bootstrap/Materialize.

## Local

Fábrica de Software, Porto Alegre - Av. Praia de Belas

## Benefícios

- VT;
- VR ou VA;
- Assistência Médica e Odontológica(Cobertura Nacional);
- Rede de Convênios e Parcerias em diversas áreas.

#### Diferenciais

- Day Off no Dia do Aniversário;
- Incentivo a formação e certificações;
- Investimento em qualificação profissional (treinamentos presenciais e plataforma EAD);
- Horário Flexível;
- Home Office.

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento de software utilizando VueJS;

**Desejáveis:**
- Experiência em desenvolvimento mobile com React Native;
- Conhecimento em Angular.

## Contratação

CLT ou PJ a combinar

## Nossa empresa

A Join Tecnologia e Design é uma empresa com cultura de constante aprendizagem e ambiente descontraído, você vai encontrar eventos como o nosso Join Beer e Masterchef Join, além de MeetUps, Whorkshops e Treinamentos presenciais e EAD. Estamos localizados no prédio corporativo do Praia de Belas, com vista para o por-do-sol do Guaíba. Para conhecer melhor, acesse nosso site: https://jointecnologia.com.br/

## Como se candidatar

Por favor envie um email para rh@jointecnologia.com.br com seu CV anexado e pretensão salarial - enviar no assunto: Vaga Front-end Developer 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 4 dias após cada processo.

## Labels

- Fábrica
- Pleno
- Sênior

**Comment by Coystark** [comment]
Aceita remoto?

**Comment by JoinTecnologia** [comment]
> Aceita remoto?

Aceitamos :)
