### ISSUE TITLE
[Remoto] Front-end Developer na Jifcast

### ISSUE THREAD

**Issue by philxavier** [frontendbr/vagas#2879]
## Descrição da vaga

Estamos à procura de um desenvolvedor JavaScript experiente que seja proficiente com React.js. O foco principal do candidato selecionado seria desenvolver componentes de UI implementando-os e executando-os com tecnologias como Flux ou Redux. O dever do candidato contratado inclui garantir que esses componentes e a aplicação geral sejam robustos e fáceis de gerenciar. E também coordenar com as várias equipes que trabalham em camadas distintas da infraestrutura. Portanto, é importante um compromisso com a resolução colaborativa de problemas, design sofisticado e produtos de qualidade.

## Local

Remoto 

## Benefícios

- Salário inicial US$ 600 - 1300 por mês (dependendo da experiencia)
- Aumento de salário com base no desempenho após 90 dias
- opções de ações
- oportunidade de crescer com a empresa

## Requerimentos
- Forte proficiência em JavaScript, incluindo manipulação do DOM 
- Compreensão completa do React.js e seus princípios básicos
- Experiência anterior com Redux
- Familiaridade com APIs RESTful
- Familiaridade com HTML / CSS
- Experiência com GIT

## Responsabilidades

- Desenvolver recursos voltados para o usuário usando React.js
- Projetar uma interface de usuário moderna, altamente responsiva e web based
- Construir componentes reutilizáveis ​​e bibliotecas front-end para uso futuro
- Traduzir designs e wireframes em código de alta qualidade
- Otimizar componentes para obter o desempenho máximo em uma vasta gama de dispositivos e navegadores compatíveis com a Web
- Como desenvolvedor React.js., você estará envolvido desde a concepção até a conclusão com projetos tecnologicamente sólidos e esteticamente impressionantes.

## Contratação

a combinar

## Nossa empresa

Somos um provedor de serviços trabalhando em várias idéias de startup usando MERN stack. Trabalhe em estreita colaboração com engenheiros experientes em tecnologia de ponta.

Na nossa empresa, os relacionamentos são importantes e nossa equipe corporativa leva esse sentimento a sério na maneira como trabalhamos, apoiando e respeitando uns aos outros e compartilhamos os mais altos padrões de excelência. Estamos sempre procurando a próxima ótima idéia ou uma nova maneira de enfrentar um desafio, e colaboramos e inovamos para alcançar nossos objetivos.

## Como se candidatar

Por favor envie um email para MIKE4MAIN@GMAIL.COM com seu CV anexado - enviar no assunto: Vaga React Developer

## Labels

- Remoto
- Júnior
- PJ
- Pleno
- Remoto

**Comment by JoseFlavioBR** [comment]
Queria muito tentar mas não tenho os requisitos

**Comment by gustavoliveira94** [comment]
@MrS4w 

Galera, o responsável por essa vaga é um cara chamado Mike.
Conversei com ele e ele foi super ignorante, depois que ele ofereceu um salário de 600 dólares e eu falei que era baixo. E então eu conversando normal e ele começou a falar coisas do tipo: Eu não iria te contratar mesmo; você não mora nos EUA e esse salário é bom para o Brasil que é barato; Não perca meu tempo; Vai embora;
Começou a falar querendo ser superior.

Então, fiquem atentos!

**Comment by LucasHiago** [comment]
Eu nem respondi este mike depois do e-mail dele, muito estranho um "full
stack" chamado mike que desconheço me oferecer uma vaga com salário
desumano. PNC dele.

Em sáb., 1 de fev. de 2020 às 13:01, Gustavo Oliveira <
notifications@github.com> escreveu:

**Comment by MrS4w** [comment]
@felipefialho fecharei essa vaga temporariamente por conta das reclamações do @gustavoliveira94 e @LucasHiago 
Caso eu esteja errado me comunique ou permita-se reabrir a mesma :)

**Comment by williamlagos** [comment]
Olá! Sugiro que deixe ao menos os nomes que este sujeito utiliza para que possa ser localizado (jifcast.com e jifcam.com). Este mesmo Mike me contatou e foi bem mal educado no trato das conversas pelo Skype e/ou E-mail, sem falar o e-mail para lá de suspeito (lazlopanaflex66@gmail.com). O padrão se repetiu, salário bem abaixo da média e um trabalho muito estranho... plagiando trabalhos de outros sites, pouca orientação, e afins. Fujam que é cilada.

**Comment by trthhrtz** [comment]
Ok, I received an e-mail from this Mike today, let's see what he offers

**Comment by lai32290** [comment]
I just received e-mail from lazlopanaflex66@gmail.com too.

**Comment by KlausDevWalker** [comment]
O cara que postou tem a ver com esse Mike?

**Comment by iguit0** [comment]
Acabei de receber e-mail dessa pessoa. Agora ele tá com outro nome: Miguel
Salário muito abaixo do padrão. Fujam que é **cilada**!
![Screenshot_2020-05-31_12-13-02](https://user-images.githubusercontent.com/12905770/83355834-40dddf80-a338-11ea-9595-668101c26c13.png)

**Comment by juliocesarmfo** [comment]
Aceitei uma vaga desse Mike e ajudei ele durante uns 2 dias no desenvolvimento de uma plataforma em Next.js.
Ele é extremamente grosso e mal-educado, não especifica o que quer (e quando faz, depois que vc termina ele já diz que está errado e pede de uma forma completamente diferente).

Atualmente ele usa o e-mail jifcast.com@gmail.com e continua chamando-se por Mike, dizendo que é fullstack.

Me ofereceu o pagamento de US$350,00/mês inicialmente e um aumento depois de 30 dias caso eu "estivesse indo bem".
Ele está fazendo outra plataforma agora que é o http://viablee.com/, também está relacionada a ele.

**Não aceitem vaga desse Mike.**

**Comment by Tooluloope** [comment]
I also got an offer from the Mike guy. He's completely arrogant and rude. Offering a meager $350 per month which is way below the average pay.

**Comment by awesomeo99** [comment]
**All the fools complaining here failed the test.** 
When you fail the test or perform poorly, then your salary will be low.

Don't expect to get paid more money when you barely know how to code.

The ones who are complaining here, did not perform well on the test task or performed poorly in the interview.

The ones that were hired and were paid good salary will not come to post and cry :) 

The ones crying here are terrible coders with no experience but they expect to be paid like good experienced developers, what a joke!

**Comment by Tooluloope** [comment]
> **All the fools complaining here failed the test.**
> When you fail the test or perform poorly, then your salary will be low.
> 
> Don't expect to get paid more money when you barely know how to code.
> 
> The people who are complaining here, did not perform well on the test task or performed poorly in the interview.
> 
> The ones that were hired and were paid good salary will not come here to post and cry :)
> 
> The ones crying here are terrible coders with no experience but they expect to be paid like good experienced developers, what a joke!

You're shady, arrogant, and rude. Grow up man

**Comment by awesomeo99** [comment]
> > **All the fools complaining here failed the test.**
> > When you fail the test or perform poorly, then your salary will be low.
> > Don't expect to get paid more money when you barely know how to code.
> > The people who are complaining here, did not perform well on the test task or performed poorly in the interview.
> > The ones that were hired and were paid good salary will not come here to post and cry :)
> > The ones crying here are terrible coders with no experience but they expect to be paid like good experienced developers, what a joke!
> 
> You're shady, arrogant, and rude. Grow up man

You should learn to code. Africa has great schools and tech companies. Use them.

**Comment by marcospedro97** [comment]
Estou entendendo errado ou ele acha que o Brasil fica na africa?

**Comment by awesomeo99** [comment]
> Estou entendendo errado ou ele acha que o Brasil fica na africa?

This is how stupid these people are :)

The guy I replied to "Tooluloope" is clearly in Nigeria but then this idiot comes along with his geography lesson haha

**Comment by marcospedro97** [comment]
> > Estou entendendo errado ou ele acha que o Brasil fica na africa?
> 
> This is how stupid these people are :)
> 
> The guy I replied to "Tooluloope" is clearly in Nigeria but then this idiot "marcospedro97" comes along with his geography lesson haha
> 
> Yes you fools should get paid high salaries because you are all brilliant :))

ok... I'm not trying to be rude, please, do the same... But, as far as I can tell, you can't even try this, it's beyond your will, so I'll just stop talking here, hope you get banned from this repo and go back to some chan where this things are acceptable

**Comment by rodrigo-fonseca** [comment]
Galera, esse Mike muito provavelmente é um velho asiático com nome
americano, encontrei muito desse tipo qd estive nos EUA e o comportamento
deles é bem assim mesmo, só precisa ignorar

Em sáb., 24 de out. de 2020 às 15:02, Marcos Pedro Nunes Dantas da Trindade
<notifications@github.com> escreveu:

**Comment by awesomeo99** [comment]
Not trying to be rude? LOL
No bud, you tried to make fun of me because you thought I did not know my geography

And when I showed you the mirror, you come back with lame excuse "I'm not trying to be rude"

Nice try! You lost :))
Once again proving my point.

**Comment by awesomeo99** [comment]
For all people complaining here, at the time of your interview or test, you were just not skilled enough.

If any of you guys get better and more skilled, please re-apply.
I will be happy to offer you higher salary.

Good luck!

**Comment by KlausDevWalker** [comment]
@felipefialho, give a look on this discussion here, please.

**Comment by jliocsar** [comment]
> For all people complaining here, at the time of your interview or test, you were just not skilled enough.
> 
> If any of you guys get better and more skilled, please re-apply.
> I will be happy to offer you higher salary.
> 
> Good luck!

Well, let's point out a few things here.
You claimed that I was a "fake dev" as my "Github was empty". Your Github is empty too, based on forks from another projects (which is OK), but you don't have any personal project or anything you ever did yourself.
Second of all, when we worked together, you didn't write a single line of code. Every single problem we had with bad MRs or files conflicts were caused by YOU, and YOU know that, but you always argued that I was the problem.

Anyways, two days after I told you to F* off because you're just another scammer, I got a React job which pays me more in brazilian real than you paid in dollar, which is insane since american dollars are worth 5 times more than brazilian real, am I right?
Well, I'm done with this thread/repo for now, but instead of just lying about your skills, how about you show us a REAL project of yours that you REALLY coded and did not hire people for miserable amounts just to show off?

Obrigado a todos que também comentaram sobre o Mike aqui. Como vcs podem ver, não estávamos exagerando haha

**Comment by jliocsar** [comment]
> > For all people complaining here, at the time of your interview or test, you were just not skilled enough.
> > If any of you guys get better and more skilled, please re-apply.
> > I will be happy to offer you higher salary.
> > Good luck!
> 
> Well, let's point out a few things here.
> You claimed that I was a "fake dev" as my "Github was empty". Your Github is empty too, based on forks from another projects (which is OK), but you don't have any personal project or anything you ever did yourself.
> Second of all, when we worked together, you didn't write a single line of code. Every single problem we had with bad MRs or files conflicts were caused by YOU, and YOU know that, but you always argued that I was the problem.
> 
> Anyways, two days after I told you to F* off because you're just another scammer, I got a React job which pays me more in brazilian real than you paid in dollar, which is insane since american dollars are worth 5 times more than brazilian real, am I right?
> Well, I'm done with this thread/repo for now, but instead of just lying about your skills, how about you show us a REAL project of yours that you REALLY coded and did not hire people for miserable amounts just to show off?
> 
> Obrigado a todos que também comentaram sobre o Mike aqui. Como vcs podem ver, não estávamos exagerando haha

Also Mike, stop using fake profiles and names. It's just easier to tell you're up to something shady.
