### ISSUE TITLE
[Rio de Janeiro] Front-End Developer | Estúdio Touch

### ISSUE THREAD

**Issue by bruunas** [frontendbr/vagas#288]
## Descrição da vaga

Oportunidade para Desenvolvedor(a) Front-end com inglês fluente.

## Local

Escritório, Rio de Janeiro 

## Requisitos

**Obrigatórios:**
- Inglês fluente
- Javascript (jQuery e frameworks)
- AngularJS
- HTML5 e CSS3 avançados
- WordPress
- Pré-processadores (LESS/SASS, preferencialmente SASS)
- Variáveis, Mixins, Functions, Extend e Expressions
- Frameworks CSS (Bootstrap, Foundation, Stylus, preferencialmente Bootstrap)
- Git avançado (branching, rebase, etc. - preferencialmente Bitbucket e SourceTree)
- Grunt/Gulp (preferencialmente Grunt, saber usar e configurar)
- Noção de PHP, integração com WordPress e frameworks (CakePHP e Laravel)

**Desejáveis:**
- Git-flow
- Vue.js
- React
- ES6
- Mobile application HTML5 frameworks

## Contratação

Indiferente

## Como se candidatar

https://trampos.co/oportunidades/130827-desenvolvedor-front-end

**Comment by LFeh** [comment]
Pleno?

**Comment by bruunas** [comment]
De pleno à senior.
