### ISSUE TITLE
[São Paulo] Front-end Developer na Enext

### ISSUE THREAD

**Issue by cedrykaugusto94** [frontendbr/vagas#2882]
## Descrição da vaga

Trabalhar no desenvolvimento de e-commerces para grandes empresas como:
- Avon
- Bauducco
- Puma
- Yamaha
- Loreal Paris
- Santander  

## Local

Escritório, São Paulo - Cidade Monções

## Benefícios

- Plano de saúde
- VR 
- VT
- Home office

## Requisitos

**Obrigatórios (JR):**
- Conhecimento básico JavaScript, HTML e CSS
- Saber como funciona um Controle de versão - Git
- Saber como funciona consumo de APIs - Ajax
- Boas práticas: reutilização de código

**Obrigatórios (PL):**
- JavaScript, HTML e CSS
- Pré-processadores - Sass
- Cross Browser e responsividade
- Controle de versão - Git
- Experiência com bibliotecas de Javascript - jQuery
- Consumo de APIs - Ajax
- Boas práticas: reutilização de código, semântica e performance
- Experiência com o framework Knockout.js

**Diferenciais:**
- ECMAScript 2015
- Linters
- Conceitos de data-bind
- Experiência com plataformas de e-commerce
- SEO
- Liquid Template
- Metodologias CSS - BEM, SMACSS, ITCSS e etc.
- Task Runners / Module Bundler
- Modularização e Componentização 
- Template engine - Pug
- React

## Contratação

Oportunidades PJ e CLT

## Nossa empresa

A Enext é uma consultoria e agência digital, premiada em 2016 e 2017 pelo GREAT PLACE TO WORK. Nós fazemos parte do grupo WPP, a maior empresa de publicidade do mundo em termos de receita. Trabalhamos com vários clientes desafiadores, cujo alguns deles são: Santander, Arezzo, BASF, Suvinil, L’oreal, Sephora, Nespresso, The North Face e Bauducco.

Nosso time tem hoje aproximadamente 200 pessoas, focadas no nosso principal valor: OBSESSÃO PELO CLIENTE. E é esse pensamento que nos torna referências nas melhores tecnologias do mercado de desenvolvimento de e-commerce como: Salesforce, Oracle, Magento e Vtex.

Nosso time de tecnologia hoje, é um dos melhores do Brasil quanto a desenvolvimento WEB, tanto na stack front-end quanto na back-end. Além disso, somos parceiros de grandes empresas de cloud computing como AWS, Microsoft e Oracle. Usamos largamente os seus serviços e investimos no treinamento da equipe para atuar com elas.

## Como se candidatar

Você terá acesso a nossas vagas pelo https://enext.gupy.io/ ou entrando em contato com nossa recrutadora pelo email: luciana.dourado@enext.com.br

## Labels

- CLT
- Estágio
- Júnior
- PJ
- Pleno

**Comment by felipesaev** [comment]
Aplicado !! Obrigado pela oportunidade.

**Comment by MaickSilva** [comment]
Aplicado, fico no aguardo, obrigado.

**Comment by joaopedrodev** [comment]
Olá queria saber se existe alguma para desenvolvedor Laravel PHP, também trabalho como desenvolvedor FullStack obrigado deixo meu numero do whatsapp 61999955207.
