### ISSUE TITLE
[Angola] Desenvolvedor Full Stack [Unisaúde]

### ISSUE THREAD

**Issue by carvalhoemanuel** [frontendbr/vagas#2883]
A Unisaúde:
---
A Unisaúde é uma empresa de gestão de sistemas de saúde, com mais de 20 anos de experiência no Brasil e mais de 10 anos em Angola.
Oferecemos soluções de saúde para seguradoras e empresas privadas.
Contamos com a mais completa rede de prestadores em Angola, Brasil, Portugal, Namíbia, África do Sul, dentre outros.
Acreditamos ser fundamental promover a saúde e a qualidade de vida, além controlar e reduzir os custos dos tratamentos.

**Aqui nós:**

>Priorizamos o atendimento ao usuário
>Valorizamos o trabalho em equipe e as contribuições individuais
>Focamos no resultado, no controle de custos e no prazo
>Respeitamos e valorizamos a diversidade
>Crescemos e fazemos crescer

O que precisamos:
---
Se você é desenvolvedor fullstack, precisamos de você, para juntos, transformarmos nosso sistema na melhor plataforma de autorização, controle de atendimentos médicos e informações de África.
O que você precisa ter:
- Vontade de compreender o negócio
- Não ter medo de meter a mão na massa
- Ser capaz de acertar, errar e corrigir sem medo de ser feliz
- Ser capaz de apresentar soluções e inovações no produto
- Ter habilidades de liderança e desenvolvimento de equipe

Nosso Stack:
---
- PLSQL
- JavaScript
- Html
- CSS

Diferencial:
---
- Oracle Apex
- Experiência com desenvolvimento para aplicações web com alto volume de acessos, fazendo utilização de soluções para melhoria de desempenho de backend e frontend;
- Conhecimentos em frameworks React ou Angular
- Conhecimento de metodologias ágeis (Scrum, Lean, Kanban)
- Conhecimento em Modelagem de Banco de Dados
- Experiência com Metodologia de testes
- Experiência em Bootstrap

Local de Trabalho:
---
Bairro Talatona, Luanda - Angola.

Benefícios:
---
- Ajuda de custo para alimentação e transporte.
- Moradia: Casa compartilhada em condomínio fechado, próximo a empresa e a supermercados, shoppings, restaurantes, bares, hospitais, etc.
- Férias: 24 Dias úteis de Férias por ano.
- Passagem: 3 (três) passagens por ano ao país de origem, em classe econômica.
- Salários: 12 (doze) salários por ano.
- Subsídio de férias: 50% do salário base pagos mensalmente (1/12 mês).
- Subsídio de Natal: 50% do salário base pagos mensalmente (1/12 mês).
- Benefício saúde: assistência médica.

Contratação:
---
- Visto de Trabalho: A Empresa pagará os emolumentos associados ao visto de trabalho no consulado, sendo estes: a taxa de consularização e taxa de visto.
- Documentos pessoais, como passaporte, estão a cargo do contratado.

Candidatura:
---
Enviar e-mail para: vagas@unisaude.co.ao, assunto: **DESENV FULLSTACK**

**Comment by randhson** [comment]
Enviado.

Randson N. dos S. França +55 79 99843 9878+55 79 99138 7628 

    Em quinta-feira, 30 de janeiro de 2020 05:27:14 BRT, carvalhoemanuel <notifications@github.com> escreveu:  
 
 
A Unisaúde:

A Unisaúde é uma empresa de gestão de sistemas de saúde, com mais de 20 anos de experiência no Brasil e mais de 10 anos em Angola.
Oferecemos soluções de saúde para seguradoras e empresas privadas.
Contamos com a mais completa rede de prestadores em Angola, Brasil, Portugal, Namíbia, África do Sul, dentre outros.
Acreditamos ser fundamental promover a saúde e a qualidade de vida, além controlar e reduzir os custos dos tratamentos.

Aqui nós:


Priorizamos o atendimento ao usuário
Valorizamos o trabalho em equipe e as contribuições individuais
Focamos no resultado, no controle de custos e no prazo
Respeitamos e valorizamos a diversidade
Crescemos e fazemos crescer


O que precisamos:

Se você é desenvolvedor fullstack, precisamos de você, para juntos, transformarmos nosso sistema na melhor plataforma de autorização, controle de atendimentos médicos e informações de África.
O que você precisa ter:
   
   - Vontade de compreender o negócio
   - Não ter medo de meter a mão na massa
   - Ser capaz de acertar, errar e corrigir sem medo de ser feliz
   - Ser capaz de apresentar soluções e inovações no produto
   - Ter habilidades de liderança e desenvolvimento de equipe

Nosso Stack:
   
   - PLSQL
   - JavaScript
   - Html
   - CSS

Diferencial:
   
   - Oracle Apex
   - Experiência com desenvolvimento para aplicações web com alto volume de acessos, fazendo utilização de soluções para melhoria de desempenho de backend e frontend;
   - Conhecimentos em frameworks React ou Angular
   - Conhecimento de metodologias ágeis (Scrum, Lean, Kanban)
   - Conhecimento em Modelagem de Banco de Dados
   - Experiência com Metodologia de testes
   - Experiência em Bootstrap

Local de Trabalho:

Bairro Talatona, Luanda - Angola.

Benefícios:
   
   - Ajuda de custo para alimentação e transporte.
   - Moradia: Casa compartilhada em condomínio fechado, próximo a empresa e a supermercados, shoppings, restaurantes, bares, hospitais, etc.
   - Férias: 24 Dias úteis de Férias por ano.
   - Passagem: 3 (três) passagens por ano ao país de origem, em classe econômica.
   - Salários: 12 (doze) salários por ano.
   - Subsídio de férias: 50% do salário base pagos mensalmente (1/12 mês).
   - Subsídio de Natal: 50% do salário base pagos mensalmente (1/12 mês).
   - Benefício saúde: assistência médica.

Contratação:
   
   - Visto de Trabalho: A Empresa pagará os emolumentos associados ao visto de trabalho no consulado, sendo estes: a taxa de consularização e taxa de visto.
   - Documentos pessoais, como passaporte, estão a cargo do contratado.

Candidatura:

Enviar e-mail para: vagas@unisaude.co.ao, assunto: DESENV FULLSTACK
