### ISSUE TITLE
[Curitiba] Frontend Developer na [Paraná Banco S/A]

### ISSUE THREAD

**Issue by gustavobini** [frontendbr/vagas#2884]
## Descrição da vaga

Estamos em busca de 3 frontend developers, tanto para um produto interno quanto para um produto voltado ao nosso cliente final.

## O que você faz

- Trabalha em conjunto com a equipe de design na definição de melhores práticas e soluções
- Participa de decisões tecnológicas dentro de seu Squad e Chapter, tais como contratos de API e escolha de bibliotecas
- Coopera com os membros do seu Chapter na definição e criação de novos componentes
- Desenvolve as soluções com a melhor qualidade possível, levando em consideração o cliente e seus colegas desenvolvedores
- Mentora e auxilia membros de sua equipe quanto às melhores práticas de mercado

## Quem você é

- Você tem sólida experiência profissional com React
- Você entende ou trabalhou com Next.js
- Você domina JavaScript e é capaz de desenvolver uma Todo List sem a utilização de um framework
- Você entende as implicações de utilizar uma <div /> ao invés de um <button />
- CSS é tão importante quanto JavaScript e conceitos como CSS-in-JS, SASS e outros fazem parte do seu vocabulário
- Conceitos como Event Bubbling e Event Delegation são de seu conhecimento
- Criar testes unitários é natural para você, mais ainda com bibliotecas como Jest e @testing-library/react
- Você tem um excelente sendo crítico e experiência na revisão de pull requests
- Você fica muito confortável ao utilizar o Git
- Você considera o sucesso de sua equipe tão importante quanto seu próprio sucesso, colaborando com seus colegas mesmo que isso signifique sair de sua zona de conforto
- Você tem experiência profissional com equipes multidisciplinares

## Local

Rua Visconde de Nácar, 1441, Curitiba - Centro

## Benefícios

- Vale alimentação e vale refeição
- Vale transporte
- PLR
- Auxílio creche
- Plano de saúde e odontológico
- Clube Gazeta do Povo
- Previdência Privada
- Convênios com restaurantes, universidades e escolas de idiomas

## Contratação

CLT

## Nossa empresa

O Paraná Banco conquistou, ao longo de sua história, espaço merecido no mercado brasileiro. O banco foi uma das primeiras instituições financeiras do país a levar crédito consignado a beneficiários do INSS e, hoje, também agrega ao seu mix produtos de crédito, opções de investimentos para pessoas físicas e jurídicas. Configurando a lista das maiores instituições de crédito do país, o Paraná Banco mantém sua matriz estratégica em Curitiba, atuando com plataformas comerciais e correspondentes bancários em todo o território nacional.

Seus valores são pautados em:

Foco em resultados | Cumprimento de metas e melhoria contínua de processos | Ética nos negócios | Conhecer o cliente e superar suas expectativas | Pessoas fazem a diferença| Constante inovação tecnológica | Respeito a normas e governança.

https://www.paranabanco.com.br/

## Como se candidatar

Por favor envie um e-mail para talentos@paranabanco.com.br com seu CV anexado - enviar no assunto: Vaga Frontend Developer. Você também pode se candidatar via [LinkedIn](https://www.linkedin.com/company/paran-banco-s-a/jobs/).

## Labels

- CLT
- Pleno
- Sênior

**Comment by gsantiago** [comment]
@gustavobini tem horários flexíveis e dress code?

**Comment by gustavobini** [comment]
> @gustavobini tem horários flexíveis e dress code?

Não temos dress code, venha como bem entender.

A flexibilidade de horário existe, mas é importante para nós que você esteja presente durante as cerimônias, principalmente. A carga horária são 8 horas diárias - o que a maioria das pessoas costuma fazer é estar presente pelo menos entre 9:00 - 11:30 e 13:30 e 17:00.

**Comment by gustavobini** [comment]
Vaga preenchida.
