### ISSUE TITLE
[REMOTO] Front-End Developer na EMPREENDER

### ISSUE THREAD

**Issue by andreas-monday** [frontendbr/vagas#2886]
## Descrição da vaga

Estamos buscando um Front end web developer Pleno
Com um forte conhecimento em JS, CSS e HTML

## Local

Remoto 

## Contratação

PJ - 8h

## Nossa empresa

O profissional irá trabalhar em uma ferramenta de criação de landing page.

## Como se candidatar

Por favor envie um email para **contato@empreender.com.br** com:

- Links de trabalhos
- CV anexado
- Pretensão Salarial
- Enviar no assunto: Front-End Developer

## Labels

- PJ
- Pleno
- Remoto

**Comment by danielswater** [comment]
Enviado

**Comment by edsonvieirademetrio** [comment]
CV enviado!

**Comment by willianmonteiro** [comment]
CV enviado!

**Comment by nandomoreirame** [comment]
enviado.

**Comment by Acastelo** [comment]
CV enviado

**Comment by andreas-monday** [comment]
Processo seletivo encerrado.
Obrigado a todos.
Abraços
