### ISSUE TITLE
[Maceió-Alagoas/REMOTO] Front-end Developer na Ilhasoft

### ISSUE THREAD

**Issue by dyohan9** [frontendbr/vagas#2896]
## Descrição da vaga

Como desenvolvedor front-end, você integrará nosso time web no desenvolvimento de software para trabalhar nos nossos produtos e com nossos projetos.

Uma semana comum conosco pode incluir sprint planning, sprint review, revisão de código do time, tech talks e execução de tasks.

Mesmo durante período de crise nacional dos últimos anos, ganhamos diversos prêmios e continuamos a crescer acentuadamente. Temos um ambiente descontraído, somos 100% adeptos à metodologias ágeis e um açaí na nossa mão tem um resultado certo: papos profundos sobre tecnologia, música, série e animes.

No fundo, nós queremos você no time para:

1. Crescer conosco à medida que desbravamos novos projetos

2. Ter orgulho do trabalho que desenvolve
3. Melhorar a cada dia
4. Ter a certeza de ter contribuído para problemas de nossos clientes após um dia de trabalho desafiador
5. Ajudar todos seus colegas de trabalho a completar o check list acima

Vem com a gente!

## Local

Remoto ou Escritório, Maceió - Jatiúca

## Benefícios

- Plano de saúde para você
- Auxílio alimentação
- Auxílio transporte

## Requisitos

**Obrigatórios:**
- Domínio em HTML5, CSS3 e Javascript
- Domínio completo de Git Flow
- Conhecimento em SPA (Vue, Angular e React)
- Desejo por boas práticas de desenvolvimento e excelência técnica
- Conhecimento básico de inglês

**Desejáveis:**
- Experiência prévia em escrever e manter testes unitários
- Conhecimento em webpack
- Conhecimento em CSS patterns
- Contribuições em projetos open source
- Experiência prévia com Flexbox e SASS
- Fluência em Inglês

## Contratação

CLT, PJ a combinar

## Nossa empresa

Somos especialistas em desenvolver **chatbots** que utilizam os mais sofisticados recursos da **Inteligência Artificial** para automatizar a comunicação entre organizações e pessoas ao redor do mundo. 

**O QUE QUEREMOS?**

**Crescer com sustentabilidade, permanecendo com nossas raízes.**

Queremos conectar comunidades e fazer com que o uso da tecnologia seja democratizado: alcance a todos, onde quer que seja. Queremos inovar, revolucionar, provocar novos comportamentos. Queremos facilitar o acesso aos melhores serviços de um jeito rápido e prático, sem burocracias.

Queremos criar soluções para problemas, otimizar a interação entre empresas e consumidores, levar a igualdade para os lugares mais remotos, trabalhar em parceria com ONGs e Governos para conscientizar as pessoas e dar-lhes mais qualidade de vida.

**Queremos fazer parte de uma nova era sem sair da nossa terra!**

## Como se candidatar

[Link da VAGA](https://ilhasoft.gupy.io/jobs/162033?jobBoardSource=gupy_public_page)

## Labels

- Alocado
- CLT
- Júnior
- PJ
- Pleno
- Remoto
- Sênior

**Comment by EdeiltonSO** [comment]
Amei! Tem tempo médio de resposta?

**Comment by dyohan9** [comment]
> Amei! Tem tempo médio de resposta?

Eita, acredito que em até 3 dias devem entrar em contato, mas pode ser que entrem em contato antes

**Comment by danielswater** [comment]
Enviado

**Comment by fafa1** [comment]
Bom dia, tem como disponibilizar o email para mandar o currículo?

**Comment by dyohan9** [comment]
> Bom dia, tem como disponibilizar o email para mandar o currículo?

Boa tarde, o envio do curriculo tem que ser enviado pela plataforma, segue o URL: [Link da VAGA](https://ilhasoft.gupy.io/jobs/162033?jobBoardSource=gupy_public_page)

**Comment by pedro-surf** [comment]
já foi preenchida? @felipefialho

**Comment by dyohan9** [comment]
> já foi preenchida? @felipefialho @dyohan9

ainda não

**Comment by fafa1** [comment]
> > já foi preenchida? @felipefialho @dyohan9
> 
> ainda não

Enviei um email, com o desafio proposto feito!
