### ISSUE TITLE
[Curitiba/PR] Front-end na Herospark

### ISSUE THREAD

**Issue by jeanmalves** [frontendbr/vagas#2898]
## Descrição da vaga

Estamos buscando por um front-end pleno para integrar nosso time. Somos uma plataforma de empreendedorismo digital que já impactou mais de 6 milhões de alunos e gerou 90 milhões de reais em vendas aos nossos empreendedores heróis.
Funções: 
Desenvolvimento e manutenção front-end de websites;
Aplicação de templates;
Criação e customização de páginas.

## Local

Remoto ou escritório, Curitiba - Centro

## Benefícios

- Vale transporte;
- Vale refeição;
- Treinamentos e workshops (internos e externos);
- Seguro de vida;
- Parcerias com estabelecimentos da região;
- Computador;
- Assistência médica;

## Requisitos

**Obrigatórios:**
- Boa comunicação
- Espírito de equipe
- Ampla experiência como front-end (Prototipação de layout, flex layout, CSS, SASS, Bootstrap ou Material Design)
- Amplo conhecimento em Javascript
- Experiência no consumo de web APIs
- Ampla experiência com GIT

**Desejáveis:**
- Experiẽncia com AWS S3
- Inglês avançado/fluente
- Noções de design

**Diferenciais:**
- Projetos opensource
- Experiência no desenvolvimento de aplicações SPA em VueJS ou Angular

## Contratação

CLT a combinar

## Nossa empresa

Somos uma plataforma de empreendedorismo digital que já impactou mais de 6 milhões de alunos e gerou 90 milhões de reais em vendas aos nossos empreendedores heróis.

Nosso time é ágil e focado em entregar a melhor experiência para quem importa: nossos clientes e seus alunos. Usamos Scrum e Kanban na nuvem.

Desenvolvemos especialmente em Ruby on Rails, mas temos sistemas e componentes em Elixir, Node.Js, no front usamos Angular e Vue.Js, no App utilizamos Kotlin e Swift.

Utilizamos fortemente infraestruturas como Amazon, Heroku e Google Cloud, Sendgrid para email, Kubernets/Docker em infra, além de MongoDB, Postgresql e Redis.  No desenvolvimento, utilizamos Github, GitLab, TrackJS e Pingdom/AppSignal para análises e Circle CI para integração contínua - realizamos vários deploys diariamente!

## Como se candidatar

Por favor acesse o [link da oportunidade](https://herospark.abler.com.br/vagas/front-end-developer-pl-375070)  e clique em "candidatar-se".

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.

## Labels

- Alocado
- Remoto
- CLT
- Pleno
- Paraná

**Comment by nandomoreirame** [comment]
Sistema chato de se candidatar, desisti.

**Comment by danielswater** [comment]
Chato mesmo. Também desisti

**Comment by fabiomirandaa** [comment]
Nossa, que negócio chato.. Agora toda vaga tem uma aplicação diferente pra fazer cadastro.. Um saco isso.

**Comment by diegurm** [comment]
@jeanmalves, não consegui finalizar o cadastro, pelo anuncio diz que é uma vaga remoto. Mas não permite me cadastrar para a vaga.

 ![image](https://user-images.githubusercontent.com/1062248/73855831-6556fe80-4813-11ea-9d3c-c5066b73f2d8.png)

**Comment by jeanmalves** [comment]
Pessoal, me desculpe mas é o sistema que a empresa usa para recrutar, vou repassar os feedbacks. @diegurm obrigado pelo feedback, vou pedir pra ajustar isso já e te retorno aqui.

**Comment by jeanmalves** [comment]
@diegurm ajustado, pode se candidatar. Obrigado pelo contato.

**Comment by diegurm** [comment]
Obrigado @jeanmalves, consegui me candidatar, aguardando retorno.

**Comment by EdeiltonSO** [comment]
Experiência com React é uma alternativa válida?

**Comment by jeanmalves** [comment]
É válido sim, mas não tem foco em frameworks SPA, vou até alterar a descrição.
