### ISSUE TITLE
[Barueri - SP] Desenvolvedor Front-end Pleno/Sênior - Walmart.com

### ISSUE THREAD

**Issue by bertelledani** [frontendbr/vagas#29]
## Descrição da vaga

Estamos com duas vagas abertas para Front-end no Walmart.com para trabalhar na equipe de Marketplace. Um dos projetos utiliza node e angular, o outro tem um legado em rails e está sofrendo mudanças para micro serviços e possivelmente será feito uso de react, oportunidade interessante para colaborar desde o início no refactoring! :)

O ambiente é descontraído, bermuda liberada, temos um espaço bem legal de copa/café e a equipe de trabalho é incrível! Veja mais no vídeo:

https://www.youtube.com/watch?v=jClk8O5qfpw&sns=fb

## Local

O escritório fica em Alphaville/Barueri, bem pertinho do Shopping Tamboré e do Shopping Iguatemi Alphaville com fácil acesso pela Castelo Branco.

## Benefícios

Temos escritório com diversas coisas interessantes como:

- sala de jogos com pebolim;
- sinuca;
- xbox;
- mini golfe na área externa! :)

## Requisitos

**Obrigatórios:**

- conhecimentos sólidos nos 3 pilares do front-end: HTML, CSS, JS

**Desejáveis:**

- HTML semântico
- CSS3, SASS/Stylus
- Javascript/ES6, Angular/React
- design Responsivo/Adaptativo
- desenvolvimento cross-browser
- conhecimento de automação Gulp/Grunt/npm
- conhecimento de versionamento git
- integração com API’s
- experiência com times ágeis
- conhecimento de UX

**Diferenciais:**

- experiência com desenvolvimento de produto
- experiência com e-commerce
- desenvolvimento com node.js
- conhecimento de ruby on rails
- atomic CSS
- TDD/BDD

## Contratação

A contratação destas vagas é por empresa terceira modelo PJ

## Como se candidatar

Por favor envie um email para devcontrat@wal-mart.com com seu CV anexado e no assunto: Vaga Front-end Developer

**Comment by LFeh** [comment]
Boa sorte @bertelledani ;)

**Comment by bertelledani** [comment]
obrigada! :smile:

**Comment by LFeh** [comment]
A vaga foi preenchida? @bertelledani

**Comment by LFeh** [comment]
Como não teve respostas, vou fechar.

@bertelledani Avisa se precisar abrir.

**Comment by camilatigre** [comment]
@bertelledani 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
