### ISSUE TITLE
[São Paulo - SP] Front-end no Itaú Unibanco

### ISSUE THREAD

**Issue by rodssouza** [frontendbr/vagas#2901]
## Descrição da vaga
- Atuar no desenvolvimento de soluções aderentes às necessidades do negócio, visando criar sistemas de fácil manutenção e sustentáveis;
- Atuar na análise, no desenho lógico e físico, construção e configuração de ambiente;
- Seguir os principais e mais atuais princípios de arquitetura do mercado e do Banco;
- Gerar documentação de registro completo das soluções e do processo;
- Atuar em projetos de equipe utilizando metodologia Ágil e modelo de comunidade de entrega;
- Realizar a migração de sistemas legado para novas tecnologias;

## Local
São Paulo - Conceição (junto a estação de metrô)

## Benefícios
- Plano de saúde
- Seguro de vida
- VR, VA
- Auxílio creche
- Bolsa-auxílio
- PLR
- Diversas parcerias com descontos para universidades, produtos, serviços, etc.

#### Diferenciais
- Dress code leve
- Horário flexível (podemos combinar sempre que necessário)
- Trabalhar em soluções que impactam milhões de pessoas ;)

## Requisitos
**Obrigatórios:**
- Experiência com desenvolvimento Web front-end
- HTML5
- CSS3 (arquitetura componentizada, compressão, CSS reset, etc.)
- Javascript (Angular, JQuery, AJAX, chamadas assíncronas, manipulação de DOM, etc.)
- Conhecimento nos Patterns JS (constructor e module);
- Experiência com Java / Spring MVC / Maven;
- Arquiteturas de aplicação (MVC, MVP, MVVM);
- Conhecimento em ferramentas de versionamento (Git);
- Conhecimento em DevOps e esteiras de deploy (Jenkins, Fortify, Sonar);
- Conhecimentos em acessibilidade para web (WCAG);
- Conhecimento básico em backend e manutenção de APIs;
- Testes unitários e automatizados

**Desejáveis:**
- Conhecimento em framework js (Node.js, React, Vue, Angular.js);
- Conhecimento em microsserviços

**Diferenciais:**
- Certificações na área de tecnologia;
- Pós-graduação e/ou especialização

## Contratação
CLT

## Nossa empresa
Venha trabalhar no Itaú Unibanco!
Queremos o caminho que ninguém usou, porque ele geralmente leva aonde ninguém foi. Queremos os inconformados, os inquietos, os indignados, apaixonados por tecnologia. Queremos os impacientes e os inventivos. 
Queremos aqueles com vontade de mudar o mundo visando o melhor para o cliente. Não queremos você apenas por achar que você tem a nossa cara.
Queremos ter um pouco da sua também. Queremos você! 

## Como se candidatar
Via LinkedIn:
https://www.linkedin.com/jobs/view/1693336616/

Caso tenham algum problema ou dificuldade, podem me mandar mensagem pelo LinkedIn:
https://www.linkedin.com/in/rodssouza/

## Labels
- Alocado
- CLT
- Sênior
- Tech Lead

**Comment by ednilsonamaral** [comment]
me candidatei! 🤞
