### ISSUE TITLE
[São Paulo] Front-end Developer na Juntos Somos Mais

### ISSUE THREAD

**Issue by felipefialho** [frontendbr/vagas#2902]
Somos a Juntos Somos Mais, o maior programa de fidelidade do varejo de material de construção e maior marketplace B2B do setor.

Fomos criados em 2018, por 3 gigantes do setor (Votorantim Cimentos, Gerdau e Tigre), com o propósito de fortalecer o varejo e transformar a vida dos profissionais que constroem sonhos. Estamos crescendo a passos largos, já são mais de 20 empresas e 250 mil membros no programa de fidelidade.

Nosso time é fissurado pelo sucesso do varejo.

## Descrição

Precisamos de alguém que vá além de códigos e entenda que desenvolvemos aplicações para pessoas usarem. Sendo assim, você estará livre para propor melhorias, novas ideias, compartilhar conhecimento e participar ativamente de todas as partes da concepção do produto 😁

Importante ter boa capacidade de comunicação e visão de negócio, você vai atuar em um time multidisciplinar.

## Localização

Estamos localizados na região da Vila Olimpia em São Paulo, bem próximo da estação de trem e do shopping.

## Responsabilidades

- Desenvolver aplicações para atender às necessidades do negócio
- Manutenção e evolução dos produtos
- Construir códigos com qualidade e testáveis
- Estudar e implementar novas tecnologias
- Foco no usuário

## Skills

- HTML, CSS e JavaScript
- Arquiteturas e metodologias CSS
- Componentização
- Testes (Jasmine, Jest, Mocha, Chai, etc...)
- Experiência com SPA's
- Cuidado com UI/UX
- Git

## Desejáveis

- Design System
- Cultura open source
- Ter atuado em times ágeis (Kanban, Scrum)
- Conhecer técnicas e gostar de discutir sobre UI/UX

## Diferenciais

- Typescript
- React Native

## Benefícios

- CLT
- Plano de Saúde
- Plano Odontológico 
- Seguro de Vida
- Vale Refeição
- Vale-transporte ou subsídio estacionamento
- Bônus (Remuneração variável)
- Gympass – para sua saúde e bem-estar!
- Home office
- Equipamento de última geração ([MacBook Pro](https://www.apple.com/br/macbook-pro-13/specs/))

## Ambiente 

- Videogame e ping-pong 🎮
- Frutas e snacks todos os dias 🍓
- Dresscode liberado - seja você! 🧦

## Como se candidatar

1. Primeiramente faça nosso teste seguindo as instruções: https://github.com/juntossomosmais/frontend-challenge 
2. Esperamos que você envie o desafio em até 10 dias, mas caso precise de mais prazo avisa a gente 😊
3. Mande um e-mail p/ vagas-dev@juntossomosmais.com.br com o título: **[Front-end Developer] Seu nome**
4. Nesse email adicione tudo que considere relevante no seu perfil: Github, LinkedIn, projetos e etc...
5. Não esqueça de enviar o link do repositório com seu teste
6. Boa sorte 🙏
______

Quer ser protagonista da sua carreira e contribuir para um mundo melhor? 

Junte-se! 💕

**Comment by fabiomirandaa** [comment]
Só opção de alocado com home office esporádico, ou rola home office full?

**Comment by felipefialho** [comment]
Alocado com 1 home office semanal. Totalmente remoto ainda não.

**Comment by gabrielroodriz** [comment]
Meu, vou fazer com certeza, imagina eu trabalhando com vocês? Os cara foda do Front... Sonho total

**Comment by andilegal** [comment]
O mesmo teste para júnior, pleno e sênior ?

**Comment by felipefialho** [comment]
@andilegal O mesmo teste, é possível desenvolver usando técnicas mais simples ou mais complexas. 

Naturalmente o nível de exigência muda conforme a senioridade da pessoa que enviou 😊

**Comment by tassioFront** [comment]
Fala Felipe, beleza? :) 

Se não for perdir demais, seria possível divulgar quantos usuários se acaixam em cada perfil (especial, normal e trabalhoso)?

**Comment by felipefialho** [comment]
@tassioFront Quase todos são `trabalhoso` né? hahaha

A ideia é essa, trata os casos de `empty state` e boa.

**Comment by tassioFront** [comment]
@felipefialho  diria que tá dando todos haha Mas bom saber o foco, porque se a classificação estiver errada o que tá pegando é a geografia e não o js. hahahaha

**Comment by marcioc0sta** [comment]
Tem uma galera massa trampando lá 😄

**Comment by ferreirabh** [comment]
Ainda tem vaga?

**Comment by tassioFront** [comment]
@felipefialho , boa tarde. Tudo bom? :) 

Só pra confirmar, vocês receberam meu e-mail?

**Comment by felipefialho** [comment]
@tassioFront Dei uma olhada no email e não chegou nada ainda

**Comment by felipefialho** [comment]
@ferreirabh Temos sim

**Comment by tassioFront** [comment]
@felipefialho reenviei pelo meu gmail. 
O do Outlook estava bloqueando.  Valeu :)

**Comment by felipefialho** [comment]
@tassioFront Só constando, ainda não chegou.

**Comment by tassioFront** [comment]
@felipefialho uai?! Enviei pelos meus dois emails pro vagas-dev@juntossomosmais.com.br ... 

Tem algum outro que eu possa mandar?

**Comment by felipefialho** [comment]
@tassioFront Não sei porque não tá chegando mas me chama no LinkedIn ou Twitter pra gente ver isso 😄

**Comment by tassioFront** [comment]
@felipefialho 🤣🤣 mandei um convite pelo LinkedIn. Tássio Jordão meu perfil.

**Comment by brunopoc** [comment]
@felipefialho Ainda é possível fazer o teste?

**Comment by felipefialho** [comment]
@brunopoc Ainda está aberto sim, temos algumas vagas para serem preenchidas ainda.

**Comment by brunopoc** [comment]
@felipefialho Acabei agora o teste e enviei o email para vocês (também coloquei você e o @willianantunes no repositório), peço desculpas pelo atraso, qualquer coisa estou a disposição.
