### ISSUE TITLE
[São Paulo] Full-stack Developer Pleno na Flatbox (Laravel e Angular)

### ISSUE THREAD

**Issue by williamxsp** [frontendbr/vagas#2909]
## Descrição da vaga

A Flatbox está procurando por uma pessoa desenvolvedora Full Stack para trabalhar em um projeto com API Laravel e Front-End Angular.

## Local

Escritório, São Paulo - Santo Amaro (ao lado da estação de trem e metrô)

## Benefícios

- Oportunidade Crescimento
- Plano de desenvolvimento individual
- Férias Coletivas

#### Diferenciais

- Horário flexível
- No dress code
- Ambiente
- Vídeo game
- Participação em outros projetos com ideias e sugestões

## Requisitos

**Obrigatórios:**
- Experiência com Angular (Estamos na v8)
- Experiência com desenvolvimento de APIs com o Laravel (Estamos na v6)
- Boa lógica de programação

**Desejáveis:**
- Bootstrap
- Noções de UX
- Base sólida de RxJS
- Experiência com Ionic 3 ou superior
- Experiência com MySQL

## Contratação

- PJ de 3k a 5k

## Nossa empresa

Somos inquietos e estamos em constante transformação, como o digital. Nascemos para unir artistas e técnicos, comunicadores e estrategistas, programadores e designers e liderá-los para transformar sonhos em resultado. Nosso trabalho é construir pontes que conectam Tecnologia, Marketing e Comunicação ao que entendemos ser o foco de tudo: Pessoas. Afinal, somos pessoas, criando com pessoas, para servir pessoas.
Prazer, somos Flatbox.

## Como se candidatar

Por favor envie um e-mail para vempra@flatbox.ag com:
Assunto: Vaga Full Stack
Seu CV anexado
Faça o teste: http://mrcoach.com.br/teste-perfil-comportamental-disc.php
Envio o print do resultado anexado ao email

## Labels

- Alocado
- Pleno

**Comment by joaopedrodev** [comment]
Olá queria saber se existe alguma para desenvolvedor Laravel PHP, também trabalho como desenvolvedor FullStack obrigado deixo meu numero do whatsapp 61999955207.

**Comment by williamxsp** [comment]
Oi @joaopedrodev A gente não tem uma posição apenas pra Laravel no momento :(

**Comment by lucasantoniooficial** [comment]
Aceita Freelancer? Eu consigo preencher a vaga mas trabalho como freelancer.

**Comment by williamxsp** [comment]
@lucasantoniooficial a gente prefere trabalhar com profissional alocado aqui na empresa. Se for do seu interesse, a gente pode marcar uma conversa e ver como podemos trabalhar. ;)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
