### ISSUE TITLE
[São Paulo] Desenvolvedor Web Sr - AngularJS/ .NET

### ISSUE THREAD

**Issue by Willycasarini** [frontendbr/vagas#291]
[VAGA] Desenvolvedor Web Sr (PJ a combinar)
## Descrição da vaga

Desenvolvimento de novos aplicativos Web
Análise e levantamento de requisitos
Manutenção em sistemas em operação
Suporte a usuários

## Local

Escritório, São Paulo - Barra Funda (próximo a estação Barra Funda de metrô)

## Benefícios

- 1,5 horas de almoço
- remuneração agressiva

## Requisitos

**Obrigatórios:**
- AngularJS avançado
- ASP.NET avançado
- WEB.API avançado
- SQL Server avançado

- conhecimentos em HTML
- conhecimentos em NODEJS

**Diferenciais:**
- conhecimentos em Ionic/ Cordova

## Contratação

PJ a combinar

## Nossa empresa

A Prox é uma consultoria de tecnologia cuja missão é promover a união entre pessoas e sistemas, de verdade!
Estamos no mercado brasileiro desde 2009 e nossa missão é nos tornarmos a maior consultoria de negócios e tecnologia.
Nós desenvolvemos nossos próprios produtos e hoje, precisamos da sua ajuda para desenvolver um dos nossos sistemas.
Aqui você encontrará Ética, Franqueza, Qualidade, Transparência, Exclusividade e Comprometimento, já que esses são nossos principais valores.

## Como se candidatar

Por favor envie um email para willy.casarini@prox.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor Web Sr.

**Comment by Willycasarini** [comment]
Labels: alocado; senior, PJ

**Comment by ygorlazaro** [comment]
@Willycasarini boa tarde! Eu tenho os requisitos, mas sou do RJ. Vocês têm alguma disponibilidade para trabalho remoto?

**Comment by Willycasarini** [comment]
@ygorlazaro, boa tarde. Infelizmente nesse momento não. Temos somente uma posição para nosso escritório em São Paulo. mas pode me enviar seu CV, por favor. Manterei no meu banco para futuras oportunidades. Um abraço.
