### ISSUE TITLE
[São Paulo] Front-end Developer na Carenet Longevity

### ISSUE THREAD

**Issue by kevenjesus** [frontendbr/vagas#2915]
## Descrição da vaga

O nosso produto Orchestra conecta dados de dispositivos médicos com o sistema de registro eletrônico de saúde (HIS) de um hospital, para que os dados certos atualizem o registro do paciente certo no momento certo. Assim, reduzimos a entrada manual de dados, economizando tempo e erros neste processo e gerando dados mais precisos.

Se você estuda programação com foco em Front-end, gosta de pensar e questionar qual seria a melhor experiência que o usuário pode ter através de uma página web ou um app, mas também é faminto por tecnologia e está sempre atualizando seus conhecimentos por meio de cursos e eventos, essa vaga é para você.

## Local

Presencial, São Paulo - Moema

## Benefícios

- Vale Transporte
- VR de R$ 500/mês

#### Diferenciais

- Suporte para seu desenvolvimento de competências profissionais
- Oportunidade para crescimento internamente
- Mentoria do time de tecnologia (front, back, devops, testes, arquitetura)
- Horário flexível

## Requisitos

Conhecimentos básicos das tecnologias web (ainda que não possua experiência profissional na área)

**Obrigatórios:**
- HTML (estrutura semântica, formulários, botões)
- CSS (Flexbox, design responsivo, positions)
- JS (variáveis, objetos, loops, funções, eventos, DOM)

**Diferenciais:**
- Será um grande diferencial se você já tiver conhecimento em ReactJS.

## Contratação

Contrato R$ 1.100,00

## Nossa empresa

A Carenet Longevity é uma empresa de saúde e tecnologia com produtos IoMT (Internet of Medical Things) apaixonada por lidar com desafios e gerar inovação para que, com o uso de tecnologias modernas, possamos salvar vidas.

Nosso time leva nosso propósito a sério e estamos crescendo, por isso, estamos buscando alguém que deseja atuar como Front-end de fato, utilizando as melhores e mais modernas tecnologia do mercado (arquitetura de micro serviços e PWA, além tecnologias de ponta como React, Nodejs, Java, Redis, Mongo, Postgres, Kubernetes, Docker,  Google Cloud entre outras).

## Como se candidatar

Por favor envie um email para talentos@carenet.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: aline.molinari@carenet.com.br

## Labels

- Alocado
- Estágio

**Comment by barcellos-pedro** [comment]
Cv enviado.
Obrigado!

**Comment by felri** [comment]
>Contrato R$ 1.100,00

Esse é o valor do salário?
