### ISSUE TITLE
[São Paulo] FullStack Developer na Home Hero

### ISSUE THREAD

**Issue by mmbfreitas** [frontendbr/vagas#2916]
## Descrição da vaga

Buscamos pessoas que serão a base do time de produto e tecnologia da Home Hero, focadas em construir o maior marketplace de produtos e serviços para reforma e decoração da América Latina.

Como será o seu dia a dia:
- Você terá a oportunidade de criar, projetar e implementar novos produtos que irão não só ajudar a melhorar os processos internos, mas a indústria como um todo.
- Você estará trabalhando em projetos que serão extremamente utilizados pela empresa e clientes externos.
- Arquitetar e desenvolver software, com princípios de escalabilidade, testes e código limpo.

## Local

São Paulo - Pinheiros

## O que oferecemos

- Remuneração alinhada ao mercado;
- Oportunidade de participar da criação de uma startup do zero;
- Ambiente descontraído
- Ambiente meritocrático, com oportunidades e suporte para desenvolver sua carreira profissional de maneira meteórica com possibilidade de participação societária;
- Ecossistema horizontal

## Requisitos

**Obrigatórios:**
- Mínimo de 3 anos de experiência em engenharia de software no desenvolvimento e manutenção de aplicativos web;
- Mínimo de 2 anos de experiência em UI e na utilização de frameworks JavaScript MVC (AngularJS, ReactJS, Vue.JS)
- Sólidos conhecimentos em javascript;
- Sólidos conhecimentos de lógica de programação, orientação a objetos e design patterns;
- Experiência com testes unitários em JS (Mocha, Protractor, Jasmine...);

**Desejáveis:**
- Conhecimentos em aplicações mobile e PWA.
- Conhecimentos em Node.js

**Diferenciais:**
- Noções de Docker e Aws

## Contratação

PJ a combinar

## Nossa empresa

Criada por sócios da MAR ventures - Venture builder brasileira com foco em marketplaces e fintechs - a Home Hero está transformando o setor de reformas residenciais no Brasil.

Através de tecnologia e dados, levamos transparência e uma experiência extraordinária para quem quer reformar um imóvel.

Ao conectar toda a cadeia (arquitetos, empreiteiros, fornecedores, etc) e gerenciar o projeto em um único local, oferecemos uma solução completa, fornecendo aos nossos clientes tudo o que eles precisam, de serviços a produtos, para criar a casa dos seus sonhos.

A partir de agora, deixar a sua casa do seu jeito não é mais sinônimo de dor cabeça. E sim, é possível ter uma obra entregue no prazo, dentro do orçamento e com qualidade!

Portfólio MAR ventures:

- Bee Câmbio – www.beecambio.com.br (Forex) 

- Easy Carros - www.easycarros.com (Automotive industry)

- Singu - www.singu.com.br (Beauty industry) 

- Finpass - www.finpass.com.br (Structured credit)

- Remessa Online – www.remessaonline.com.br (Remittance) 

- Mosaico University - www.mosaicouniversity.com.br (Education & Tech) 

- Modiax - www.modiax.com (Cryptocurrency Exchange) 

- Insidly - www.insidly.io (Information & Tech) 

## Como se candidatar

Por favor preencha o formulário https://homeherohh.typeform.com/to/QTyPyP

## Labels

- Presencial
- PJ
- Sênior

**Comment by developer-sp** [comment]
wpa



> ## Descrição da vaga
> 
> Buscamos pessoas que serão a base do time de produto e tecnologia da Home Hero, focadas em construir o maior marketplace de produtos e serviços para reforma e decoração da América Latina.
> 
> Como será o seu dia a dia:
> 
>     * Você terá a oportunidade de criar, projetar e implementar novos produtos que irão não só ajudar a melhorar os processos internos, mas a indústria como um todo.
> 
>     * Você estará trabalhando em projetos que serão extremamente utilizados pela empresa e clientes externos.
> 
>     * Arquitetar e desenvolver software, com princípios de escalabilidade, testes e código limpo.
> 
> 
> ## Local
> 
> São Paulo - Pinheiros
> ## O que oferecemos
> 
>     * Remuneração alinhada ao mercado;
> 
>     * Oportunidade de participar da criação de uma startup do zero;
> 
>     * Ambiente descontraído
> 
>     * Ambiente meritocrático, com oportunidades e suporte para desenvolver sua carreira profissional de maneira meteórica com possibilidade de participação societária;
> 
>     * Ecossistema horizontal
> 
> 
> ## Requisitos
> 
> **Obrigatórios:**
> 
>     * Mínimo de 3 anos de experiência em engenharia de software no desenvolvimento e manutenção de aplicativos web;
> 
>     * Mínimo de 2 anos de experiência em UI e na utilização de frameworks JavaScript MVC (AngularJS, ReactJS, Vue.JS)
> 
>     * Sólidos conhecimentos em javascript;
> 
>     * Sólidos conhecimentos de lógica de programação, orientação a objetos e design patterns;
> 
>     * Experiência com testes unitários em JS (Mocha, Protractor, Jasmine...);
> 
> 
> **Desejáveis:**
> 
>     * Conhecimentos em aplicações mobile e WPA.
> 
>     * Conhecimentos em Node.js
> 
> 
> **Diferenciais:**
> 
>     * Noções de Docker e Aws
> 
> 
> ## Contratação
> 
> PJ a combinar
> ## Nossa empresa
> 
> Criada por sócios da MAR ventures - Venture builder brasileira com foco em marketplaces e fintechs - a Home Hero está transformando o setor de reformas residenciais no Brasil.
> 
> Através de tecnologia e dados, levamos transparência e uma experiência extraordinária para quem quer reformar um imóvel.
> 
> Ao conectar toda a cadeia (arquitetos, empreiteiros, fornecedores, etc) e gerenciar o projeto em um único local, oferecemos uma solução completa, fornecendo aos nossos clientes tudo o que eles precisam, de serviços a produtos, para criar a casa dos seus sonhos.
> 
> A partir de agora, deixar a sua casa do seu jeito não é mais sinônimo de dor cabeça. E sim, é possível ter uma obra entregue no prazo, dentro do orçamento e com qualidade!
> 
> Portfólio MAR ventures:
> 
>     * Bee Câmbio – [www.beecambio.com.br](http://www.beecambio.com.br) (Forex)
> 
>     * Easy Carros - [www.easycarros.com](http://www.easycarros.com) (Automotive industry)
> 
>     * Singu - [www.singu.com.br](http://www.singu.com.br) (Beauty industry)
> 
>     * Finpass - [www.finpass.com.br](http://www.finpass.com.br) (Structured credit)
> 
>     * Remessa Online – [www.remessaonline.com.br](http://www.remessaonline.com.br) (Remittance)
> 
>     * Mosaico University - [www.mosaicouniversity.com.br](http://www.mosaicouniversity.com.br) (Education & Tech)
> 
>     * Modiax - [www.modiax.com](http://www.modiax.com) (Cryptocurrency Exchange)
> 
>     * Insidly - [www.insidly.io](http://www.insidly.io) (Information & Tech)
> 
> 
> ## Como se candidatar
> 
> Por favor preencha o formulário https://homeherohh.typeform.com/to/QTyPyP
> ## Labels
> 
>     * Presencial
> 
>     * PJ
> 
>     * Sênior



>     * Conhecimentos em aplicações mobile e WPA.

Não seria PWA?
