### ISSUE TITLE
[Curitiba] Front-end Developer na Plastika TWY

### ISSUE THREAD

**Issue by guilhermegrunberg** [frontendbr/vagas#2917]
## Descrição da vaga

Olá! Estamos buscando um profissional com experiência com CMS Wordpress para compor nosso time de desenvolvimento aqui na Plastika TWY.

**Descrição de Tarefas:**
Produção de páginas html, css e javascript;
Aplicação de CMS Wordpress 
Levantamento de Requisitos do Projeto;
Programação de produto digitais robustos e MVPs Web e Mobile;
Produção de Documentação do Projeto
Teste de funcionalidades;
Desenvolvimento Ágil.

## Local
Remoto, Curitiba 

#### Diferenciais
Conhecimentos em React.

## Requisitos
Domínio de HTML, CSS e Javascript;
Domínio de PHP;
Domínio do CMS Wordpress e Woocomerce;

**Obrigatórios:**
3 anos de experiência com PHP / Wordpress

## Contratação

PJ
Remoto
40 horas semanais

## Nossa empresa

Aqui na Plastika TWY, buscamos conhecer cada negócio e assim criar produtos digitais usáveis, factíveis, valiosos e com aquele UAU. Nossa expertise é fruto de mais de 14 anos de experiência trabalhando com design estratégico e negócios e hoje temos o prazer de construir histórias com grandes empresas e startups. Se a sua motivação é criar produtos incríveis para negócios legais, somos o time ideal.

## Como se candidatar

Por favor envie um email para hiring@plastikastudio.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Wordpress.

**Comment by nandomoreirame** [comment]
enviado.
