### ISSUE TITLE
[Brasília] Front-end Developer na Greenant

### ISSUE THREAD

**Issue by gustable42** [frontendbr/vagas#2919]
## Descrição da vaga
Desenvolvimento Web e Mobile para produtos voltados ao setor energético

## Local

Escritório ou Remoto, Brasília - Asa Noirte

## Benefícios

- A combinar

## Requisitos

**Obrigatórios:**
- HTML5
- CSS3
- ECMAScript 6
- Framework de SPA

**Desejáveis:**
- Testes unitários
- Entender de boas práticas
- Sass/Stylus
- Angular
- Ionic 4

**Diferenciais:**
- Experiência com projetos utilizando Angular

## Contratação

PJ a combinar

## Nossa empresa

Nossa meta é ser referência em gestão no setor elétrico desenvolvendo tecnologias inovadoras de inteligência de dados. Atuamos com grandes varejistas no Brasil e nossa equipe está localizada em Brasília e no Rio de Janeiro.

## Como se candidatar

Se você se interessou, mande um email com seu CV para chegamais@greenant.com.br

## Labels

- Alocado
- PJ
- Estágio
- Júnior
- Pleno
- Remoto
- Sênior

**Comment by danielswater** [comment]
Enviado. Quanto tempo em média para um Feedback?

**Comment by ElmiRabelo** [comment]
Curti, eviado! Já conhecia um pouco da GreenAnt através do LinkedIn.

**Comment by gustable42** [comment]
O processo seletivo começou ontem, enviaremos um email de confirmação de recebimento do CV, mas o prosseguimento do processo começa em duas semanas

**Comment by danielswater** [comment]
> O processo seletivo começou ontem, enviaremos um email de confirmação de recebimento do CV, mas o prosseguimento do processo começa em duas semanas

Beleza, tá enviado

**Comment by fzuffo** [comment]
Somente angular ou ionic? Não aceitam ReactJS?

**Comment by gustable42** [comment]
> Somente angular ou ionic? Não aceitam ReactJS?
> […](#)

Trabalhamos com Angular majoritariamente aqui, mas conhecer a framework não é obrigatório, se já tem uma boa noção de React e não se importa em aprender mais uma tecnologia, com certeza estará no nosso processo seletivo

**Comment by lipecss** [comment]
Vuejs não está na Stacks de vocês?

**Comment by gustable42** [comment]
> Vuejs não está na Stacks de vocês?

Infelizmente, não trabalhamos com Vue, mas todo conhecimento de Framework pra SPA é bem-vindo! Manda seu CV que é sucesso!

**Comment by danielswater** [comment]
Nas labels falta remoto

**Comment by rodrigorhas** [comment]
Enviado! Amei a vaga, estou morando em Aguas Claras.
