### ISSUE TITLE
[São Paulo - SP] Front-end Developer | GetNinjas

### ISSUE THREAD

**Issue by eduardojmatos** [frontendbr/vagas#292]
## Descrição da vaga

Você! Quer trabalhar com uma pequena equipe de desenvolvimento porém forte? Ser responsável por contribuir para todos os aspectos de definição, construção e manutenção do site do GetNinjas e seus serviços? Mudar a maneira como as pessoas buscam prestadores de serviço é o nosso ramo!

## Local

Escritório, São Paulo - Pinheiros
Fica a 100 metros do Metrô Fradique Coutinho - linha amarela. É muito perto do metrô. Mesmo!

## Benefícios

* Remuneração competitiva;
* Plano de saúde;
* Vale-Transporte;
* Vale-refeição;
* Gympass;
* Possibilidade de um enorme impacto positivo na maneira como as pessoas usam a internet;
* Os NINJAS amam: Lanches e frutas gratuitas, ambiente de trabalho descontraído, divertido e descolado, NERFS, chinelo, bermuda, churrascos, Puffs, Tech Talks e NINJA Hack Day, eventos e meetups;

## Requisitos

**Obrigatórios:**
* Ter experiência com desenvolvimento de Web;
* Ter grande habilidade com desenvolvimento de software;
* Grande habilidade e facilidade com comunicação;
* CSS (usamos o pré-processador Sass);
* HTML (semântica e acessibilidade);
* JavaScript - conhecimento da linguagem além dos frameworks;
* Ter experiência com Mobile First;
* Git;
* Arrumar soluções para a melhor experiência pro usuário, pensando na qualidade de serviço como um todo;
* Aprendizado contínuo e disseminação do conhecimento adquirido;

**Desejáveis:**
* conhecimento de Ruby / Rails;
* Testes de JavaScript (TDD / BDD) com Jasmine, Mocha, Sinon, etc..

**Diferenciais:**
* Ter trabalhado com alguma arquitetura e/ou metodologia de CSS (BEM seria excelente);

**Gaiden:**

Estamos usando um styleguide que criamos aqui na GetNinjas, o Gaiden. Se você quiser saber um pouco da stack, visite esse link e divirta-se: https://github.com/getninjas/gaiden.

## Contratação

CLT

## Nossa empresa

**O GETNINJAS**

Com mais de 120 mil profissionais cadastrados em todo o Brasil, divididos em mais de 100 subcategorias, e uma média de 100 mil cotações por mês no site, o GetNinjas.com.br já captou mais de R$ 47 milhões de investimento da Tiger, Monashees Capital e Kaszek Ventures.

Atualmente, o GetNinjas proporciona uma renda de aproximadamente 14 milhões de reais aos nosso usuários por meio da nossa plataforma e por esse e outros motivos que acreditamos que podemos trabalhar para mudar o Mundo!

## Como se candidatar

Para se candidatar, basta aplicar para a vaga no site [https://getninjas.workable.com/j/B91509C366](https://getninjas.workable.com/j/B91509C366) (se possível, diga que viu a vaga aqui no frontendbr/vagas =D).

**Comment by brunooomelo** [comment]
getJuniors?

**Comment by FernandoRangel** [comment]
Inscrição feita =D

**Comment by eduardojmatos** [comment]
@brunooomelo já temos alguns aprendendo bastante lá. Agora queremos um perfil um pouco mais experiente :)

Mas fica ligeiro que podem surgir mais novas vagas nesse semestre 😄

**Comment by kvnol** [comment]
Quando aparecer o getJuniors eu tô dentro, por enquanto eu tô treinando com o @fdaciuk para virar um ninja.

**Comment by brunooomelo** [comment]
@eduardojmatos oopa, ótimo xD

**Comment by gabriellamas** [comment]
@eduardojmatos mandei, vai rolar aquele desafio maroto? (*fé em Deus*)

**Comment by marquinhosolis** [comment]
se rolar o desafio, compartilha publicamente? 
eu, por exemplo, moro no rio, mas é sempre bom praticar...rsrsrs 
Abs!

**Comment by eduardojmatos** [comment]
@gabriellamas opa, desafio vc diz um teste?

**Comment by eduardojmatos** [comment]
@kvnol daí vai virar samurai mesmo hehe

**Comment by LFeh** [comment]
Já sabe né @eduardojmatos ? https://github.com/LFeh/frontend-challenges

**Comment by eduardojmatos** [comment]
@LFeh sei sim mano! Estamos pensando em alguns dali, apesar de já termos um teste nosso hehe. Vou ver com o @lucasas a possibilidade de deixarmos nesse repo também ;)

**Comment by gabriellamas** [comment]
@eduardojmatos isso!

**Comment by rafael1995** [comment]
Inscrição feita! (:  Na torcida rs..
