### ISSUE TITLE
[Remoto] Front-End Developer no Cálculo Jurídico

### ISSUE THREAD

**Issue by giovannibonetti** [frontendbr/vagas#2920]
## Descrição da vaga

Aqui no Cálculo Jurídico nós desenvolvemos sistemas para ajudar os advogados a fazerem cálculos de aposentadoria para seus clientes. Estamos expandindo para outras áreas de direito e precisamos de você para nos ajudar a dar conta desse trabalho. A empresa é 100% remota, e nos comunicamos via Slack, Hangout e Google Docs.

Agora precisamos de um(a) desenvolvedor(a) talentoso(a) para tomar a frente de um novo produto que vamos lançar para atender a cada vez mais advogados brasileiros.

O processo seletivo é 100% online incluindo prova teórica e prática de desenvolvimento, seguidos de entrevista via Hangouts.

## Local

Onde você quiser, o trabalho é 100% remoto.

## Contratação
PJ _full time_ com remuneração entre R$ 8 e 11 mil, dependendo da experiência do(a) candidato(a) e do resultado nas provas do processo seletivo.

## Requisitos

**Obrigatórios**
- Experiência prática com desenvolvimento de front-end web usando HTML, CSS e JS
- Tenha desenvolvido alguma aplicação interativa com alguma biblioteca/framework baseada no conceito de [Virtual Dom](https://pt-br.reactjs.org/docs/faq-internals.html), como React, Vue, Angular etc.
- [Conhecimentos básicos de Typescript](https://www.typescriptlang.org/docs/handbook/basic-types.html) ou alguma linguagem com tipagem estática
- Inglês avançado para compreensão escrita e oral (vídeos de cursos, eventos etc.)

Obs.: todos os requisitos tem uma prova online correspondente no processo seletivo

**Desejáveis**
- Experiência com controle de versão usando Git
- [Conhecimentos básicos de programação funcional](https://www.freecodecamp.org/news/functional-programming-principles-in-javascript-1b8fc6c3563f/)
- Conhecimentos de boas práticas de usabilidade e design de interface
- Conhecimentos de pré-processadores de CSS como SASS, LESS ou Stylus

## Empresa

Apesar de ser uma empresa nova - há cerca de 3 anos no mercado - o Cálculo Jurídico já é uma empresa lucrativa e, portanto, não precisa de investimento externo. Aqui a gente trabalha para fazer o melhor produto pro cliente, não para entregar as funcionalidades que o investidor pede.

Somos uma equipe pequena (cerca de 15 pessoas) mas bem organizada. Você pode observar isso pela organização do processo seletivo com várias etapas, sendo tudo realizado por nós mesmos (não terceirizamos recrutamento para nenhuma empresa de RH).

Do ponto de vista tecnológico, hoje temos um sistema feito em Ruby on Rails hospedado no Google App Engine / Google Cloud Platform com containers Docker. Estamos montando nossa API agora que vai ser usada pelas novas partes do front-end, que já foi todo desenhado no Figma e está sendo implementado agora.

#### Diferenciais da empresa

- empresa 100% remota;
- alta produtividade - você vai poder focar no trabalho sem muitas interrupções. Há raríssimas reuniões (normalmente só uma por semana), pois quase todas a comunicação ocorre de forma assíncrona via documentos do Google Docs, desenhos da interface no Figma, emails etc.

## Como se candidatar

Inscrições abertas até sexta-feira (14/fev) às 12h (BRT) [neste link](https://talentos.calculojuridico.com.br/selective_processes/desenvolvedor-a-front-end-pleno-senior-home-office-2020/candidates/new?referrer=github).

Assim que as inscrições se encerrarem você vai receber um email nosso explicando como iniciar o processo seletivo.

O CPF é solicitado para garantirmos uma maior autenticidade dos cadastros no processo seletivo.

## Cronograma

Ação | Prazo
-- | --
Encerramento das inscrições | 14/fev (6ª feira) às 12h
Realização dos testes de lógica, inglês e comunicação | 14/fev (6ª feira) às 12h até 17/fev (2ª feira) às 12h
Realização dos testes de lógica, inglês, comunicação e prova teórica de desenvolvimento | 17/fev (2ª feira) até às 18h
Realização da prova prática de desenvolvimento | 21/fev (6ª feira) às 12h até 26/fev (4ª feira) às 12h
Comunicação do resultado na prova prática e convocação dos aprovados para entrevista | 26/fev (4ª feira) até às 18h
Realização das entrevistas | 27/fev (5ª feira) e 28/fev (6ª feira)
Comunicação aos candidatos do resultado final do processo seletivo | até 28/fev (6ª feira) às 18h
Ínicio do trabalho | a partir de 03/mar (3ª feira)

## Labels
- PJ
- Remoto
- Pleno
- Sênior

**Comment by nandomoreirame** [comment]
enviado.

**Comment by edsonvieirademetrio** [comment]
Inscrito!

**Comment by fabriciodanioj** [comment]
Applied!

**Comment by victorvhs** [comment]
Inscrito!

**Comment by gcdesigner** [comment]
Enviado!

**Comment by yuricamara** [comment]
@giovannibonetti , não há mais possibilidade de fazer a prova hoje?

**Comment by giovannibonetti** [comment]
@yuricamara infelizmente não há mais. Conforme o cronograma acima, a realização das provas se encerrou hoje às 12h.

De qualquer forma obrigado pelo interesse.

Como as incrições já se encerraram vou aproveitar e fecha a issue.
