### ISSUE TITLE
[Florianópolis-SC] Front-end Developer na FeracodeBR

### ISSUE THREAD

**Issue by christiancuri** [frontendbr/vagas#2922]
Somos um empresa americana com escritório no Brasil. Buscamos profissional para trabalhar em nosso time de Front-End.

## Local

Temos 2 vagas presenciais (possibilidade de remoto inicialmente) na Pedra Branca - Palhoça / SC - Região de Florianópolis

## Benefícios

- Salário e benefícios pagos em Dólar

#### Diferenciais

- Jornada Flexível
- Cadeiras Gamer
- Sala de Descanso
- Vídeo Game
- TV a Cabo
- Cozinha Equipada
- Lanches e Comidas
- Localização Privilegiada

## Requisitos

**Obrigatórios:**
- Sólidos conhecimentos em Angular 2+ (~2 anos)
- Sólidos conhecimentos em Javascript (3 anos)
- Sólidos conhecimentos em Typescript
- Sólidos conhecimentos em HTML
- Sólidos conhecimentos em CSS (sass, scss)
- GIT
- Clean Code

**Desejáveis:**
- Inglês avançado

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para mike@feracode.com com seu CV anexado - enviar no assunto: Vaga Angular

**Comment by pcfmello** [comment]
Enviado :)

**Comment by BenhurKulzer** [comment]
Enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
