### ISSUE TITLE
[SÃO PAULO -SP] Front-end Developer no Soluções Industriais

### ISSUE THREAD

**Issue by KaueGIT** [frontendbr/vagas#2923]
Vaga desenvolvedor Front-end Jr.

## Descrição da vaga

- Desenvolvedor Front-end, Seg à Sex, das 9h às 18h ao lado da estação Santo Amaro.
- Habilidades intermediárias em HTML, CSS(Flexbox), Bootstrap, Javascript e PHP.
- Desenvolver sites com foco em posicionamento orgânico (necessário ter noções básicas em SEO).
- Criatividade e curiosidade, buscando novas tendências de mercado.
- Ser pró-ativo.
- Apaixonado por tecnologia.
- Planos de carreira.

## Local

Rua Guido Calói nº 1985, São Paulo - Santo Amaro.

## Benefícios

- Plano de saúde.
- Plano odontológico.
- VR.
- VT.
- Van até a estação de metro.

#### Diferenciais

- Sala de jogos ( Sinuca, ping pong e mais).
- Sala de descompressão.
- Café da manhã e frutas disponíveis durante o expediente.
- Italian Coffee a vontade.

## Requisitos

**Obrigatórios:**
HTML, CSS3, JAVASCRIPT e BOOTSTRAP 

**Desejáveis:**
- conhecimentos em PHP
- conhecimentos em GitHub
- conhecimentos em Photoshop

**Diferenciais:**
- SEO
- UI/UX

## Contratação

CLT

## Nossa empresa

Quer fazer parte de um grupo de empresas, especializados em marketing digital? Deseja construir interfaces diversas que posicionam no Google e tenham foco em conversão? Então venha fazer parte do nosso time, e desenvolva sua carreira profissional!

## Como se candidatar

Por favor envie um email para kaue.dias@idealtrends.com.br com seu CV anexado - enviar no assunto: Vaga Front-end JR

## Tempo médio de feedbacks

Entramos em contado com os candidatos a vaga diariamente.

## Labels

- CLT
- Júnior

**Comment by igorpinhh** [comment]
sou do RJ e tenho possibilidade de mudança, posso mandar o currículo assim mesmo?
