### ISSUE TITLE
[Porto Alegre] Front-end Developer na dEx Digital

### ISSUE THREAD

**Issue by pvpaixao** [frontendbr/vagas#2925]
## Descrição da vaga

Buscamos desevolvedor Front-end para integrar a equipe e contribuir em projetos desafiadores.

## Local

Escritório, Porto Alegre (Presencial)

## Benefícios

- Salário compatível + VT + VR
- Liberdade para experimentação, inovações e crescimento
- Ambiente amigável e informal

## Perfil

Dinâmico, organizado com prazos, orientado à qualidade e atento aos detalhes.
Boa comunicação e senso estético.
Ligado às novas tecnologias e tendências na sua área de atuação.

## Requisitos

**Obrigatórios:**
- HTML5 (semântica)
-  Pré-processadores (SASS/SCSS)
-   Javascript (ES5/ES6)
-  GIT/SVN
-  Experiência com Design Responsivo
-  Experiência com algum Task Runner (Gulp, Grunt, etc)

**Desejáveis:**
- Conhecimento em PHP (Laravel)
- Experiência com alguma arquitetura/metodologia CSS (ITCSS, BEM, SMACSS, etc)
- Experiência com desenvolvimento mobile

**Diferenciais:**

- Conhecimento em algum framework JS (Angular, VueJS, React JS)
- Experiência com Google Tag Manager e implementação de Analytics

## Contratação

CLT 

## Como se candidatar

Por favor envie um email para rh@dexdigital.com.br com seu CV anexado

## Labels

- Alocado
- CLT
- Pleno
- Sênior

**Comment by pedro-surf** [comment]
Aceita parcialmente remoto?

**Comment by joaopedrodev** [comment]
Olá queria saber se existe alguma para desenvolvedor Laravel PHP, também trabalho como desenvolvedor FullStack obrigado deixo meu numero do whatsapp 61999955207.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
