### ISSUE TITLE
[Cuiabá - MT] Engenheiro(a) de software Front-End junior [Connect mindset]

### ISSUE THREAD

**Issue by gmarcial** [frontendbr/vagas#2926]
# 🏆 1º Trainee Connect Mindset

Um desafio prático, com mentorias, apoio técnico para que ***seu*** desenvolvimento, além do fornecimento de materiais diversos para o aprendizado e crescimento profissional.  

A competição tem ***como*** objetivo, selecionar dois engenheiros de software junior, sendo uma para front, avaliados em duas etapas, a primeira ***ocorrerá juntamente com a inscrição.***

***Obs:.*** Somente presencial e residentes ***em Cuiabá e Várzea Grande.***

Para saber mais sobre a competição, ***inscrição*** e acessar o primeiro desafio, ***Clique*** nos links abaixo, boa sorte!

- [📃 Sobre a competição](https://github.com/connectmindset/trainee-v0.1/wiki/%F0%9F%93%83-Sobre-a-competi%C3%A7%C3%A3o)
- [📑 Descrição das vagas](https://github.com/connectmindset/trainee-v0.1/wiki/%F0%9F%93%91-Descri%C3%A7%C3%A3o-das-vagas)
- [📝 Inscrição completa](https://www.sympla.com.br/1-trainee-connect-mindset__780777)
- [👩‍💻 👨‍💻 Primeiro desafio](https://github.com/connectmindset/trainee-v0.1/wiki/%F0%9F%91%A9%E2%80%8D%F0%9F%92%BB-%F0%9F%91%A8%E2%80%8D%F0%9F%92%BB-Primeiro-desafio)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
