### ISSUE TITLE
[Remoto] Front-end Developer na RioSlum Studio

### ISSUE THREAD

**Issue by robanquieri** [frontendbr/vagas#2927]
## Descrição da vaga

A RioSlum Studio está procurando um(a) Front-end Developer talentoso(a) para se juntar à nossa equipe de desenvolvimento para uma posição remota em tempo integral.

## Local

Remoto

## Benefícios

- Salário pago em Dólar

## Requisitos

**Obrigatórios:**
- Domínio em JavaScript, HTML e CSS
- Domínio em ambiente React (Next.js, Redux, e etc)
- Experiência em controle de versão, como Git, Github, Gitlab
- Experiência de trabalho anterior como Front-end, idealmente dentro de um ambiente de agência.

**Qualificações:**
- Métrica orientada para a tomada de decisões, priorização e implantação contínua
- Você se sente à vontade para equilibrar as necessidades técnicas, analíticas e de produtos e sabe a diferença entre Single Page Apps e Server-Side Rendering
- Você é animado com as tecnologias e estruturas front-end modernas
- Capacidade de escrever código eficiente, escalável e reutilizável
- Conhecimento em desenvolvimento multi-plataforma (Chrome, Firefox, Safari, IE, etc.)
- Aderência aos padrões web e boas práticas para a redução do tempo de carregamento e acessibilidade
- Habilidades de comunicação verbal e escrita, capacidade de interagir com um grupo diversificado de pessoas
- Habilidades de gestão de tempo em projeto
- Habilidade para definir prazo de entrega

**Desejáveis:**
- Inglês intermediário
- Conhecimentos em PHP.
- Conhecimentos em NodeJS.

**Diferenciais:**
- Ter atuado em agência
- Inglês intermediário

## Contratação

PJ a combinar

## Nossa empresa

RioSlum Studio é uma agência norte-americana que oferece serviços de marca, design, desenvolvimento de soluções web, mensagens, estratégia e videografia para empresas em todo o mundo. 

## Como se candidatar

Por favor envie um email para rogerio@rioslumstudio.com com seu CV, links de projetos e pretensão salarial - enviar no assunto: Vaga Front-end Developer

#### Alocação
- Remoto

#### Experiência
- Pleno
- Sênior

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by dersonsena** [comment]
@robanquieri Currículo enviado.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
