### ISSUE TITLE
MERN STACK

### ISSUE THREAD

**Issue by awesomeo99** [frontendbr/vagas#2928]

**Comment by BiancaPereira** [comment]
Gente como que oferece 500 dólares? Um JUNIOR CLT aqui em SP ganha no mínimo 3000 reais

**Comment by rodrigo-fonseca** [comment]
De $500 a $1200? Meu Deus!

Em ter, 11 de fev de 2020 às 23:16, Bianca Pereira <notifications@github.com>
escreveu:

**Comment by rodrigo-fonseca** [comment]
“Somos um provedor de serviço”. Leia-se: somos meros intermediários que não
fazemos nada além de comer o seu dinheiro

Em ter, 11 de fev de 2020 às 23:20, Rodrigo Fonseca <
ro.fonseca.melo@gmail.com> escreveu:

**Comment by awesomeo99** [comment]
> “Somos um provedor de serviço”. Leia-se: somos meros intermediários que não fazemos nada além de comer o seu dinheiro Em ter, 11 de fev de 2020 às 23:20, Rodrigo Fonseca < ro.fonseca.melo@gmail.com> escreveu:
> […](#)

No asshole, I actually code. Not a service provider.

**Comment by awesomeo99** [comment]
> Gente como que oferece 500 dólares? Um JUNIOR CLT aqui em SP ganha no mínimo 3000 reais

then don't apply. Did not ask for your opinion or inflated salary data from you.

**Comment by THAYLLER** [comment]
exige ingles fluente?

**Comment by rodrigo-fonseca** [comment]
Hahahahaha Não fui eu quem disse, tá na proposta sobre a empresa... hahahaha

Em ter, 11 de fev de 2020 às 23:24, Miguel Campos <notifications@github.com>
escreveu:

**Comment by awesomeo99** [comment]
> exige ingles fluente?

não básico

**Comment by awesomeo99** [comment]
> Hahahahaha Não fui eu quem disse, tá na proposta sobre a empresa... hahahaha Em ter, 11 de fev de 2020 às 23:24, Miguel Campos <notifications@github.com> escreveu:
> […](#)

Thanks, I have updated it. My Portuguese is basic.

**Comment by THAYLLER** [comment]
vlw essa parte passo batido, mas tentei fazer o enfio do email mas tem algo de errado pq volto

**Comment by awesomeo99** [comment]
> vlw essa parte passo batido, mas tentei fazer o enfio do email mas tem algo de errado pq volto

can you tell me exactly what error? I have been getting resumes.

**Comment by THAYLLER** [comment]
the error was that the email came back as if it were nonexistent, i will send it again to test

**Comment by THAYLLER** [comment]
it looks like now was it could you check if you received it correctly please?

**Comment by awesomeo99** [comment]
> it looks like now was it could you check if you received it correctly please?

I have many emails with resume but none with your name.

**Comment by awesomeo99** [comment]
> it looks like now was it could you check if you received it correctly please?

I just sent you an email, you can reply to it.

**Comment by THAYLLER** [comment]
I understand, it may take a while, there is a delay sometimes, especially if it is from different services

**Comment by diegohyenna** [comment]
Caras, desconfiem dessa vaga. Ela já foi postada aqui antes e um dev reportou a credibilidade dela.

**Comment by THAYLLER** [comment]
your email arrived

**Comment by awesomeo99** [comment]
> Caras, desconfiem dessa vaga. Ela já foi postada aqui antes e um dev reportou a credibilidade dela.

This is not junior dev position. if juniors like you apply then you will be rejected. So better not waste my time or yours.

**Comment by awesomeo99** [comment]
> your email arrived



> your email arrived

ok perfect

**Comment by THAYLLER** [comment]
Mas essa vaga ja foi postada e eu ja preenchi esse mesmo questionario, as perguntas feitas fogem e muito do que vcs pedem na descrição

**Comment by awesomeo99** [comment]
> Mas essa vaga ja foi postada e eu ja preenchi esse mesmo questionario, as perguntas feitas fogem e muito do que vcs pedem na descrição

can you forward your replies to me? 
If they did not respond meaning your experience or skill set was not what we are looking for. This is not a junior dev position. This position requires more experience with React, Next and Redux in production environment.

**Comment by THAYLLER** [comment]
entendo, mas tem muita coisa que foge do fullstack ate SEO vcs perguntam, nao tenho um nivel junior mas tbm nao tenho um nivel senior

**Comment by diegohyenna** [comment]
Essa vaga é uma furada, certeza. Não caiam nessa

**Comment by awesomeo99** [comment]
> entendo, mas tem muita coisa que foge do fullstack ate SEO vcs perguntam, nao tenho um nivel junior mas tbm nao tenho um nivel senior

SEO? It is just React libraries. If you have experience with Redux and Nextjs SSR please resend your answers, I will take a look again.

**Comment by awesomeo99** [comment]
> Essa vaga é uma furada, certeza. Não caiam nessa

With your coding skills, you will be better at cleaning toilets

**Comment by THAYLLER** [comment]
Acho que vc tem que rever o seu questionario, eu me viro bem nextjs e redux

**Comment by diegohyenna** [comment]
O cara que reportou da outra vez avisou que ele havia sido bem mal educado e desrespeitoso, falando que brasileiro aceita qualquer coisa. Pelo visto foi verdade.

**Comment by awesomeo99** [comment]
> O cara que reportou da outra vez avisou que ele havia sido bem mal educado e desrespeitoso, falando que brasileiro aceita qualquer coisa. Pelo visto foi verdade.

Brazilians are the best developers in the world. 
You are definitely NOT one of them. So go away and clean some toilets.

**Comment by diegohyenna** [comment]
> Acho que vc tem que rever o seu questionario, eu me viro bem nextjs e redux

Não cai nessa, mano. Merece coisa melhor e claramente não é uma empresa que se preze. O responsável é super mal educado.

**Comment by awesomeo99** [comment]
> > Acho que vc tem que rever o seu questionario, eu me viro bem nextjs e redux
> 
> Não cai nessa, mano. Merece coisa melhor e claramente não é uma empresa que se preze. O responsável é super mal educado.

Vá embora, perdedor. Você foi rejeitado.
Go away loser. You were rejected.

Learn to code and let other people who actually know how to code, apply to this job.

**Comment by powilliam** [comment]
Dude, i'm reporting you right now. It's the second time that i am seeing this job offer and people are saying that it's a fraud or something like that. Judge someone by his knowledge isn't the right thing assuming that everyone had a start poing. Anyone here knows more than anyone!

**Comment by CarlosHenriqueRC** [comment]
Com essa última resposta, já dá para desconfiar, quem fala a verdade

Em qua, 12 de fev de 2020 00:30, Miguel Campos <notifications@github.com>
escreveu:

**Comment by marcosabb** [comment]
Pelo que eu entendi, esse cara trabalha numa startup, e iria passar algumas demandas DELE pra outra pessoa, ou seja, bem furada.
