### ISSUE TITLE
[Remoto] Front End Software Engineer na Goodworld

### ISSUE THREAD

**Issue by fernandobandeira** [frontendbr/vagas#2929]
## Descrição da vaga

Buscamos um profissional com conhecimento em desenvolver experiências para o usuário final, seu papel na nossa equipe, será o de desenvolver as experiências da nossa plataforma. Este sistema ajuda organizaçōes, empresas e doadores a se conectarem, em um estilo similar a uma rede social, podendo realizar doações, organizar eventos e campanhas para arrecadação de fundos.

Você fará parte da equipe de desenvolvimento, atuando em conjunto com a nossa equipe de UX.

## Local

Remoto, a sede da empresa fica em Washington, DC

## Benefícios

- Horário flexível
- Trabalhe de qualquer lugar do seu jeito

#### Diferenciais

- Não precisa dar suporte para o IE (nem o 11)
- Trabalhamos com tecnologias de ponta
- Oportunidade de experiência internacional

## Requisitos

**Obrigatórios:**

- Inglês (conversar com o resto da equipe)
- React
- Emotion / Styled components / CSS in JS

**Desejáveis:**

- GraphQL (Apollo)
- Testes de integração automatizados (Cypress, por exemplo)

**Diferenciais:**

- Portfolio (GitHub)
- Experiência com ferramentas como Hotjar, Crazyegg, Optimizely (testes AB), ou outras (a sua escolha) para mensurar a efetividade das telas desenvolvidas

## Contratação

PJ (não exigimos o CNPJ, contrato empregatício diretamente com a empresa nos EUA)

## Nossa empresa

A Goodworld foi eleita uma das empresas mais inovadoras do mundo pela Fast Company, nossa missão é tornar doações e ações de impacto social, parte do seu dia a dia, queremos que ajudar alguém seja tão simples quanto compartilhar uma foto. A Startup já captou mais de $3M USD em investimento, incluindo $750k USD da Mastercard.

https://goodworld.me/

## Como se candidatar

Por favor envie um email para fernando@cheerfulgiving.com com seu CV anexado (de preferência em inglês) - enviar no assunto: Front End Software Engineer Application

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias úteis após cada processo.

#### Alocação
- Remoto

#### Experiência
- Júnior
- Pleno
- Sênior

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by ElmiRabelo** [comment]
The English requirement is for conversation or just written English?

**Comment by fernandobandeira** [comment]
@ElmiRabelo english requirement is for conversation, the designer / dev team are all brazilians though, but you'd eventually have to chat / talk with the rest of the company.

**Comment by giovannipds** [comment]
Posso afirmar que a vaga e a empresa são excelentes, super recomendados. Recomendo para níveís pleno/senior.

**Comment by allanreges** [comment]
É possível informar a faixa salarial do nível pleno?

**Comment by brenobaptista** [comment]
Enviado.

**Comment by julianamokrejs** [comment]
Enviado :)

**Comment by EduardoAraujoB** [comment]
enviei para o perfil de júnior, mas não entendi muito bem para qual nive de senioridade é a vaga

**Comment by Arthur-Serafim** [comment]
Enviei com o assunto errado, esqueci de colocar Application, devo enviar novamente? Abraços!

**Comment by giovannipds** [comment]
@Arthur-Serafim na dúvida manda de novo.

**Comment by fernandobandeira** [comment]
A vaga está sendo fechada, ainda não efetuamos uma contratação mas já temos uma pessoa em mente, quanto a questao do @EduardoAraujoB e do @allanreges, não respondi antes pois afetaria nosso plano de entrevistas / contratação, nosso maior objetivo nesse processo todo foi o de achar pessoas que amam tecnologia e estão sempre estudando / testando algo novo, independente se for usar isso no trabalho ou não, e isso é algo que não tem a ver com a experiência da pessoa, quanto a questão salarial, estavamos oferecendo qualquer salario que a pessoa achasse justo e confortavel para que trabalhasse conosco, todos os salarios pedidos estavam dentro do que poderiamos oferecer, estamos encerrando as entrevistas / analises e vamos responder a todos os que participaram quando tivermos uma decisao.
