### ISSUE TITLE
[Sao Paulo] Front-End-Developer - Allocated or Remote

### ISSUE THREAD

**Issue by rturk** [frontendbr/vagas#293]
## Descrição da vaga

V2UncmUgRW50cmlhLiBXZSBhcmUgbm90IGF2ZXJhZ2UgZGV2ZWxvcGVycywgbmVpdGhlciB0cml2aWFsLCB3ZSdyZSBmdW4gYW5kIGZhc3QuIFdlIGxvdmUgYmxlZWRpbmcgZWRnZSBhbmQgd2UgY29kZSByZWFsbHkgaGFyZC4NCg0KV2Ugc3VyZiBhbmQgbW92ZSBhcm91bmQgSmF2YXNjcmlwdCAmIGZyaWVuZHMgKE5vZGVKUywgUmVhY3QsIFJlbGF5KSBhbmQgd2UgbW92ZSByZWFsbHkgZmFzdC4NCldlIGFscmVhZHkgaGF2ZSBhIGZ1bGx5IGRlZGljYXRlZCB0ZWFtIG9mIDUgZGV2ZXMgYW5kIHdlIGFyZSBleHBhbmRpbmcgZmFzdC4gSm9pbiB1cyE=

## Local

U8OjbyBQYXVsbyAtIFpvbmEgU3VsDQpodHRwOi8vcGx1Zy5jby9ia2xu

## Benefícios

QW1iaWVudGUgbGVnYWwgcGFyYSB0cmFiYWxoYXINClNlbSBmcmVzY3VyYXMgcGFyYSBob3LDoXJpbyBkZSB0cmFiYWxoby4NCkxvY2FsaXphZG8gbmEgUGx1Z2cgQ293b3JraW5nIHpvbmEgc3VsIGRlIFNQDQo=

## Requisitos

TWFuZGF0b3J5Og0KLU1hc3RlciBKYXZhc2NyaXB0IG5pbmphIGNvZGVyDQotTm9kZWpzDQoNCk5pY2U6DQotU29tZSBpZGVhIGFib3V0IE1vbmdvZGIgb3IgTm9TUUwNCi1Tb21lIHNlbnNlIG9mIGRlc2lnbiAocG9yIGZhdm9yISkNCg0KUmVhbGx5IG5pY2U6DQotUmVsYXkNCi1SZWFjdCBOYXRpdmUNCi1NYWNoaW5lIExlYXJuaW5nDQo=

## Contratação

Q0xULCBhbG9jYWRvIG91IHJlbW90byAoUGFyYSByZW1vdG8gw6kgbmVjZXNzw6FyaW8gYWxndW1hIGRpc3BvbmliaWxpZGFkZSBkZSB2aXIgYW8gZXNjcml0w7NyaW8p

## Nossa empresa

QSBFbnRyaWEgKGh0dHBzOi8vd3d3LmVudHJpYS5jb20uYnIpIMOpIHVtYSBlbXByZXNhIGZvY2FkYSBlbSBBcHBzIGRlIGFsdGEgY29tcGxleGlkYWRlLiDDiSBsaWRlcmFkYSBwb3IgdW0gZXgtQW1hem9uLmNvbSBjb20gZXhwZXJpw6puY2lhIG5vIEJyYXNpbCBlIG5vIEV4dGVyaW9yLiBTb21vcyBhbWJpY2lvc29zIGUgZXN0YW1vcyBjcmVzY2VuZG8gbXVpdG8u

## Como se candidatar

UG9yIGZhdm9yIGVudmllIHVtIGVtYWlsIHBhcmEgdmFnYXNAZW50cmlhLmNvbS5iciBjb20gc2V1IENWIGFuZXhhZG8gLSBlbnZpYXIgbm8gYXNzdW50bzogRXUgc291IG8gc2V1IGNhbmRpZGF0byhhKSBtZSBjb250cmF0ZSBwb3JxdWUgZXUgc291IG8gY2FyYSE=

**Comment by rturk** [comment]
@LFeh tags: CLT, Senior e/ou Pleno, Alocado e/ou Remoto (quer idas regulares ao escritório)

**Comment by fabiomirandaa** [comment]
Muito bom hahaha

**Comment by rodrigooler** [comment]
42a9fb1f4f8981049faebe4ad6c5bdb1.

**Comment by LFeh** [comment]
Confesso que buguei na hora que eu vi e demorei um pouco pra matar a charada 😅

**Comment by bcarvalho89** [comment]
Coisa linda.

**Comment by dacferreira** [comment]
brilhante a ideia hahaha

**Comment by danielGalvao** [comment]
Tm9zc2EgcXVlIHJvbMOqLi4uLg==

**Comment by JCMais** [comment]
Enviado!

**Comment by klaygomes** [comment]
Bem diferente. 😄

**Comment by gabrielferreiraa** [comment]
Mandaram bem! haha Criatividade é nois

**Comment by AlexsandroSA** [comment]
Boa! :)

**Comment by marcelagodoy** [comment]
Que forma mais simpática =) hahaha

**Comment by abrasivoEvandro** [comment]
Bem criativo, rs

**Comment by fejaum** [comment]
Pior que já pensei em deixar meu currículo assim um dia e enviar de zoeira pra algumas empresas 😄

**Comment by bcperdigao** [comment]
Custei a entender!

**Comment by paulo101977** [comment]
Infelizmente a única coisa que me falta é a disponibilidade de vir ao escritório, devido a localidade :(

**Comment by leandrw** [comment]
Just past in your browser console:

```javascript
Array.from(document.querySelectorAll('.d-block.comment-body.markdown-body.js-comment-body')[0].childNodes)
	.filter(node => node.nodeType == 1 && node.tagName.toLowerCase() == 'p')
	.map(node => node.innerHTML = atob(node.innerHTML)
)
```

_Tested in Chrome 57_

**Comment by paulo101977** [comment]
SW5mZWxpem1lbnRlIGEgw7puaWNhIGNvaXNhIHF1ZSBtZSBmYWx0YSDDqSBhIGRpc3BvbmliaWxpZGFkZSBkZSB2aXIgYW8gZXNjcml0w7NyaW8sIGRldmlkbyBhIGxvY2FsaWRhZGUgOig=

**Comment by paulo101977** [comment]
@leandrw escreveu até um parser para decodificar o texto em base 64 sheuahahaheahah

**Comment by vbrosso** [comment]
Base 64 é um pré-requisio?

**Comment by rturk** [comment]
@fejaum pode mandar, nos vamos conseguir ler..

**Comment by paulo101977** [comment]
@vbrosso Acredito que base64 é um pré-requisito para ser desenvolvedor :)

**Comment by vbrosso** [comment]
@paulo101977 claro, hehhe foi só uma  brincadeira. Se bem que não precisa ser desencolvedor pra entrar no https://www.base64decode.org e decodificar a vaga.

**Comment by vbrosso** [comment]
*desenvolvedor

**Comment by paulo101977** [comment]
@vbrosso porém é necessário para utilizá-lo na hora de fazer parser ou codificar algo 👍

**Comment by cleber-programmer** [comment]
[].slice.call(document.querySelectorAll('.markdown-body p'), 0, 7).forEach(p => p.innerHTML = atob(unescape(decodeURIComponent(p.innerHTML))));

**Comment by rturk** [comment]
Caros, em respeito a quem ainda não matou a charada, peço não colar a resposta aqui. É divertido aprender coisas novas.

@paulo101977 @vbrosso é possível editar seus comentários?

**Comment by vbrosso** [comment]
@rturk mals, acho que só o admin

**Comment by paulo101977** [comment]
@rturk Vou ver se consigo editar, foi mal

**Comment by paulo101977** [comment]
@rturk , confere por favor os meus comentários. Se houver alguma divergência, eu edito-os novamente.

**Comment by LFeh** [comment]
Editei :)

**Comment by paulo101977** [comment]
@LFeh Vlw 👍

**Comment by paulo101977** [comment]
@LFeh tem dois parsers nos comentários, que colados no console, traduzem o código criptografado

**Comment by LFeh** [comment]
To ligado. Edita tambem @rturk?

**Comment by simaodeveloper** [comment]
Galera para mostrar que você sabem, basta mandar o e-mail com o currículo, não precisa colar o código aqui, isso é um filtro, só quem decifrou poderá ser convocado para uma entrevista, colando a resposta aqui  vocês acabam disputando com mais condidatos.

**Comment by LFeh** [comment]
Apaguei, sorry @leandrw

**Comment by leandrw** [comment]
@LFeh vou lembrar disso na FrontInSampa desse ano... 
Tenho 2 metros e to pegando 100kg no supino... e luto Jiu Jitsu

**Comment by LFeh** [comment]
Eita porra.

**Comment by leandrw** [comment]
Cole no teu console ;)
```javascript
Array.from(document.querySelectorAll(`.author[href="${atob('L0xGZWg=')}"]`))
   .map(node => node.innerHTML = atob('L0xGZWggPT4gc291IHVtIHZhY2lsYW8='))
```

**Comment by paulo101977** [comment]
Rindo até agora do comentário @leandrw :1st_place_medal: 
O cara é bom em escrever parsers 👍

**Comment by paulo101977** [comment]
E injeção de código

**Comment by manamachado** [comment]
Manjaram na criatividade, show!

**Comment by HaluDeCassia** [comment]
bWVsaG9yIGVudW5jaWFkbyBkZSB2YWdhIGV2ZXIhIEVudmlhZG8ga2tra2tra2tra2s=

**Comment by tgmarinho** [comment]
![image](https://user-images.githubusercontent.com/380327/40760259-eb4260d8-6463-11e8-90f9-af36c7700235.png)

Qual  eu escolho? hahaha

**Comment by vbrosso** [comment]
Base64



Em qui, 31 de mai de 2018 00:49, Thiago Marinho <notifications@github.com>
escreveu:
