### ISSUE TITLE
[São Paulo] Full Stack Developer na Sabion

### ISSUE THREAD

**Issue by marceloogeda** [frontendbr/vagas#2931]
## Nossa empresa
A Sabion Digital foi lançada em 2012 com o objetivo de ajudar empresas na evolução de seu negócio no ambiente digital. Com essência multidisciplinar, nossos especialistas em publicidade interativa baseiam-se na construção, desenvolvimento e design de maneira que usuários utilizem o meio digital como uma continuidade da vida offline. A empresa nasceu na era digital e nosso diferencial é trazer uma nova maneira de pensar, uma forma de transformar e realizar a partir de um novo olhar. Temos plena satisfação em auxiliar nossos clientes, entendendo sua rotina e propondo a melhor solução de negócio para atrair, encantar e fidelizar o cliente com soluções práticas e canais inovadores. Com pouco tempo no mercado, a SABION destaca-se no mercado pela conquista de clientes renomados que confiam e utilizam os serviços da agência digital.

## Local
Escritório, Av. Sagitário, 138 – Sls. 601 – 618 – Alpha Square Mall – Torre City |  Alphaville – Barueri – SP

## Benefícios

**CLT**
- Assistência Medica;
- Assistência Odontológica;
- Auxilio transporte;
- Seguro de vida;
- VR de R$ 25/dia;

**PJ**
- 15 dias de descanso (remunerado)

#### Diferenciais

- Ambiente descolado;
- Café à vontade;
- Desconto em restaurantes locais;
- Day off de aniversário;
- Frutas todas às Segundas e Quartas;
- Frigobar sempre cheio;  🍺 
- Horário flexível;
- Meditação todas às Quartas pela manhã;

## Requisitos

**Obrigatórios:**
- Domínio relevante com Git;
- Domínio relevante com JavaScript e seus Design Patterns;
- Experiência com NodeJS e Express;
- Experiência com MongoDB e Mongoose;
- Experiência com React e React Native;
- Experiência com GraphQL;
- Experiência com APIs RESTFul;
- Experiência com desenvolvimento de interfaces e front-end (HTML5, CSS3, Webpack).

**Desejáveis:**
- Noções de Bash script;
- Noções de Cloud Services - Google Cloud, AWS ou IBM Cloud.
- Noções de testes integrados;
- Experiência com programação assíncrona;
- Experiência com SPA;
- Experiência com metodologias ágeis de desenvolvimento (Scrum, Kanban);

**Diferenciais:**
- Noções de virtualização e containers (Docker);
- Noções em CDs/CIs  (CircleCI, Github Actions, Travis, Jenkins);
- Noções de monitoramento de serviços;
- Conhecimento em APIs nativas para acessar recursos dos dispositivos (IOS e Android);

## Contratação
CLT ou PJ (a combinar)

## Como se candidatar
Por favor envie um email para vagas@sabion.com.br com o link do seu perfil no LinkedIn - enviar no assunto: Full Stack Developer

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 02 dias após cada processo.
E-mail para contato em caso de não haver resposta: vagas@sabion.com.br

#### Alocação
+ Alocado

#### Regime
+ CLT
+ PJ

#### Nível
+ Pleno
+ Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
