### ISSUE TITLE
[Santo André - SP] Fullstack Developer na Engage

### ISSUE THREAD

**Issue by renatamelatto** [frontendbr/vagas#2933]
Desenvolvedor Full Stack Pleno na Engage em regime CLT

Principais atividades:

- Atuar junto a equipe no desenvolvimento de melhorias, evoluções e novas implementações na plataforma.

Requisitos Técnicos Necessários:
* Ensino Superior Completo na área de Tecnologia da Informação;
* Javascript, CSS, HTML5 e JQuery;
* ASP.NET Webforms e/ou MVC com C# 4.6;
* APIs REST;
* SQL Server 2014 ou superior;
* Design Patterns, DDD, SOLID e Clean Code;
* Conhecimentos de Github e Gitflow.

Requisitos Técnicos Desejáveis:
* ReactJS.

Benefícios:
Assistência médica e odontológica, vale transporte, vale refeição

Currículos devem ser enviados com pretensão salarial CLT para vagas@engage.bz

Saiba mais sobre nós em www.engage.bz

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
