### ISSUE TITLE
[Rio de Janeiro/RJ] Front-end Vue.js Developer @ Finxi

### ISSUE THREAD

**Issue by fernandovalente** [frontendbr/vagas#2935]
## Descrição da vaga

Estamos contratando Desenvolvedor Front-End Vue.js, se você deseja trabalhar em um ambiente de constante aprendizado e participar da construção de startups esse lugar é a FINXI.

## Local

Rio de Janeiro/RJ - Centro. 

## Requisitos

- Ter participado do início ao fim de um projeto (Software House, MVP)
- Experiência sólida em Javascript
- Ter trabalhado/conhecimento Vue.js
- Conhecimento em design e arquitetura de software (OOP, Clean Code, Design Patterns)
- Conhecimentos de consumo e escrita de serviços (REST)
- CSS e HTML para construção de sites leves e responsivos para desktop e mobile

**Desejáveis:**
- Cnhecimentos em Vuex
- Conhecimentos em GraphQL

**Diferenciais:**
- Conhecimento de escrita de testes automatizados
- Experiência com Docker
- Experiência com Bootstrap, material Design e WebPack

## Contratação

PJ a combinar.

## Nossa empresa

http://finxi.com.br/

## Como se candidatar

Mande seu currículo, perfil no LinkdIn, Github e tudo que achar válido para fernando.valente@finxi.com.br

#### Alocação

Disponibilidade para atuar no Centro do Rio de Janeiro, possibilidade de alguns dias de trabalho na modalidade Home Office.

#### Experiência
Pleno e Júnior

#### Regime
- PJ

**Comment by evertonProgramadorCriativo** [comment]
Desejáveis:

Cohecimentos em Vuex 


escreveu errado amigo ,  O certo -> Conhecimento em Vue.JS

**Comment by leoinho** [comment]
Everton, creio que ele quis dizer Vuex mesmo.
Vuex é o gerenciamento de estado do Vue.Js, é com se fosse o Redux do React.

**Comment by fernandovalente** [comment]
Everton, não escrevi errado, de uma olhada https://vuex.vuejs.org/

Em sex., 14 de fev. de 2020 às 13:10, Leonardo Menezes <
notifications@github.com> escreveu:

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
