### ISSUE TITLE
[São Paulo] Front-end Developer OpenCart na Printástico

### ISSUE THREAD

**Issue by rafaelaugustoferreira** [frontendbr/vagas#2936]
## Descrição da vaga

**Nós da Printástico estamos com uma vaga, no modo: remoto/freela/PJ para início imediato.**
O desenvolvedor fará alterações em um template OpenCart comprado, além de algumas integrações com o site atual (https://www.printastico.com.br) e possíveis novas telas.
A ideia, além  das alterações de layout das páginas: Home, Produtos, Área do Cliente e Processo de Checkout. É, alterar um pouco a estrutura do template para nos atender. Já que, trabalhamos com produtos personalizados, algumas demandas são totalmente especiais, se comparado aos e-commerces comuns.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Front-end
- CSS
- OpenCart
- Experiência com Docker

## Contratação

PJ

## Nossa empresa

A Printástico é uma empresa brasileira especializada em FotoProdutos e impressões digitais, que segue os mais altos padrões internacionais de tecnologia e qualidade. Nossa missão é oferecer aos nossos clientes um ambiente seguro e aplicações que garantam a criação de projetos personalizados de maneira rápida, fácil e divertida.

## Como se candidatar

Por favor envie um email para rf@printastico.com.br com seu valor/hora e CV anexado - enviar no assunto: Vaga Front-end OpenCart.

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
