### ISSUE TITLE
[Remoto] Sênior full-stack developer na Divisio

### ISSUE THREAD

**Issue by rodrigowpl** [frontendbr/vagas#2937]
## Descrição da vaga

# Vagas para pessoas desenvolvedoras

## O que fazemos?
A Divisio é empresa especializada em desenvolver software customizado, mobile apps, web apps utilizando as tecnologias React.js, React Native, Node.js, GraphQL e API REST. Trabalhamos com projetos de todos os tamanhos, desde pequenos até arquiteturas de aplicações de larga escala. Somos um time de especialistas, apaixonados por good code e trabalhamos em conjunto para lidar com os problemas de software mais difíceis e transformando idéias em realidade.

## Time
Trabalhamos duro para promover uma cultura de apoio com uma hierarquia horizontal, onde todos podem aprender um com os outros.
Todos têm a oportunidade de crescimento e participação em decisões diárias. Você poderá trabalhar remotamente de qualquer lugar, desenvolvendo novas aplicações, features e mantendo sistemas existentes para empresas que variam de tamanho, desde startups até grandes empresas. Quando você não estiver trabalhando em um projeto de um cliente, terá a
oportunidade de contribuir com o desenvolvimento de nossos processos e produtos internos, sempre tendo voz para sugerir melhorias e oportunidade de contribuir para projetos open-source.

## Local

Remoto

## Requisitos

**Requisitos obrigatórios:**
- Experiência com JavaScript.
- Experiência com Node.js.
- Experiência com API REST utilizando express ou koa e GraphQL utilizando Apollo client e server
- Experiência com React.js e suas principais APIs (hooks e context) e bibliotecas comuns como Redux
- Entendimento sobre engenharia de Web: arquitetura client/server, REST, GRAPHQL etc
- Experiência com revisão e colaboração de código em equipes usando Git
- Inglês avançado: Boa comunicação através chat e video conferências

**Diferenciais (Crédito extra):**
- Experiência com sistemas de tipos JavaScript: Flow e/ou TypeScript
- Experiência com React Native
- Experiência com dev-ops (Circle CI, CD/CI, Bitrise, automatização de deploys em geral: Web, Mobile React Native, Backend)
- Experiência com escrita de testes (Unitário, Integração, E2E)
### Benefícios
- Descanso remunerado de 20 dias por ano
- Mentoria de inglês semanais com professor particular tutor
- Incentivo para educação e cursos

## Contratação
PJ a combinar

## Como se candidatar
Responder: https://forms.gle/cLw6po5TnphpHASv7

## Tempo médio de feedbacks

Uma vez enviado todas as informações damos um retorno em 3 dias úteis caso seu perfil se encaixe na vaga.

## Labels

- PJ
- Sênior
- Remoto

**Comment by danielswater** [comment]
Aonde tem Front End ai? rs

**Comment by rodrigowpl** [comment]
Cliquei sem querer em salvar antes de terminar de editar.

**Comment by rodrigowpl** [comment]
> Aonde tem Front End ai? rs

Tinha clicado sem querer em salvar antes de terminar de editar

**Comment by rodrigowpl** [comment]
> Aonde tem Front End ai? rs

Tinha clicado sem querer em salvar antes de terminar de editar

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by danielswater** [comment]
Continua o processo?

Em qua, 18 de mar de 2020 21:04, Felipe Fialho <notifications@github.com>
escreveu:
