### ISSUE TITLE
[Florianopolis] Front-End Developer na Mission Brasil

### ISSUE THREAD

**Issue by paruckerr** [frontendbr/vagas#2939]
## Descrição da vaga

Buscamos desenvolvedores(as) que curtam novos desafios, que busquem resolver problemas, entregar tarefas com qualidade, autogerenciamento e que tenham boa comunicação.

## Local

Escritório, Florianópolis - Agronômica.

#### Diferenciais

- Flexibilidade de horário;
- Excelente localização;

## Requisitos

**Obrigatórios:**
- Reactjs;
- Hooks;
- Redux;
- Restful API oriented design;
- Styled Components;

**Desejáveis:**
- React Native;
- Noções de UX;
- Mobile;
- Xcode;
- Android Studio;
- Appium;
- Code Push;

## Contratação

PJ a combinar

## Nossa empresa

Aqui na Mission Brasil estamos construindo algo disruptivo e inovador. Acabamos de receber investimento feed para iniciar uma nova jornada em busca do Series A, estamos super empolgados e gostaríamos que você fizesse parte desse grande desafio que temos pela frente.

## Como se candidatar

Por favor envie um email para eduardo.parucker@missionbrasil.com.br com seu CV anexado - enviar no assunto: Vaga Front End

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.
E-mail para contato em caso de não haver resposta: contato@missionbrasil.com.br

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Pleno
- Senior

**Comment by rodgomesc** [comment]
Minhas skills se encaixam como uma luva, porém no momento só posso remoto, alguma possibilidade?

**Comment by paruckerr** [comment]
Olá @rodgomesc no momento é presencial mesmo =/

**Comment by BenhurKulzer** [comment]
Enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by paruckerr** [comment]
Fechamos ela recentemente, obrigado!
