### ISSUE TITLE
[São Paulo] Front-End-Developer

### ISSUE THREAD

**Issue by lucasjs** [frontendbr/vagas#294]
## Descrição da vaga

Temos certeza que você já pensou em desenvolver algo inovador! 
Um projeto que influenciará milhares de pessoas em um universo ainda pouco explorado. O mundo das gestantes, dos papais e mamães e de todos que de uma forma ou de outra vendem produtos infantis!

Esta é a oportunidade de fazer parte deste time. 
Estamos muito próximos do lançamento, alinhe os conhecimentos abaixo e descubra mais detalhes no processo seletivo. Temos uma mesa, cafezinho, ar-condicionado e muito COMMIT, DEPLOY esperando você.

## Local

Alocado, R. James Watt, 84, Jardim Edith - São Paulo, SP (Próximo à estação Berrini da CPTM)

## Benefícios

- Vale-Transporte;
- Vale-Refeição;
- Programa anual de bônus;
- Plano de saúde (empresa paga uma porcentagem);
- Frutas diaramente;
- Ser você mesmo sem ter medo de nada. Somos uma empresa que preza pelo respeito à diversidade. 

## Requisitos

**Obrigatórios:**
- HTML5, CSS;
- Lógica de programação;
- Programação orientada a objetos;
- Protocolo HTTP;
- REST;
- Ajax, JSON;
- Design responsivo;
- Versionamento (Git);
- Javascript / jQuery;
- Photoshop básico.

**Desejáveis:**
- Cursando ou graduado em Sistemas de Informação, Engenharia da Computação, Análise e Desenvolvimento de Sistemas, Ciência da Computação, Sistemas para Internet, ou afim;
- SASS;
- VTEX;
- Magento;
- Wordpress;
- Google Tag Manager.

## Contratação

CLT

## Nossa empresa

A Enext é a principal empresa de prestação de serviços para e-commerce do Brasil. Há 7 anos no mercado atendemos empresas de pequeno, médio e grande porte.

## Como se candidatar

Se candidatar via trampos: [https://trampos.co/oportunidades/130967-desenvolvedor-front-end-junior-pleno](https://trampos.co/oportunidades/130967-desenvolvedor-front-end-junior-pleno)

Qualquer problema, ajuda, dúvida, entre em contato comigo. Você receberá SIM um retorno caso participe do processo seletivo. :wink:

**Comment by ericprieto** [comment]
Putz, exigir graduação é meio ultrapassdo no nosso mercado, não?

**Comment by lucasjs** [comment]
@ericprieto Oi Eric. Conversei com quem abriu a vaga e vão mudar isso. Obrigado pelo toque.

**Comment by ericprieto** [comment]
Bacana!

**Comment by LFeh** [comment]
Bem legal :)

**Comment by gabriel-brito** [comment]
Bacana em! Vou mandar o curriculum agora mesmo! :D

**Comment by tunnes** [comment]
Nilce!
