### ISSUE TITLE
[São Paulo] Front-End Developer na [ITeam]

### ISSUE THREAD

**Issue by VivianeRHTI** [frontendbr/vagas#2940]
## Descrição da vaga

Desenvolvimento de aplicações frontend, utilizando linguagem Angular 2, 5, 6 ou 7; 
Desenvolvimento WEB (HTML, CSS, Javascript, JQuery, TypeScript); 
Conhecimento em arquitetura de microserviços; 
APIs REST, Webservices, e Json; 
Experiência em controle de versionamento com Git; 
Experiência com testes unitários; 
Bancos de dados MySQL, MongoDB e DinamoDB

## Local

São Paulo/SP - Morumbi

## Duração de projeto

5 meses

## Requisitos

**Obrigatórios:**
Angular 2, 5, 6 ou 7; 
Desenvolvimento WEB HTML, CSS, Javascript, JQuery.

## Contratação

Á combinar

## Nossa empresa

A ITEAM está presente no mercado há mais de 15 anos. Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 

## Como se candidatar

Por favor, envie um e-mail para viviane.pereira@iteam.inf.br com seu currículo anexado - enviar no assunto: Vaga Angular

#### Alocação
- Alocado no cliente

#### Regime

- Freela
- PJ

#### Nível

- Pleno
- Sênior

**Comment by VivianeRHTI** [comment]
Alocado
Pleno e Sênior
São Paulo/SP

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
