### ISSUE TITLE
PORTO ALEGRE Front-end Developer na DELL

### ISSUE THREAD

**Issue by carolina-brand-dell** [frontendbr/vagas#2941]
## Descrição da vaga

Projeto interno em REACT JS!

## Local

Eldorado do Sul - RS.

## Benefícios

Disponibilizados na entrevista e offer.

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com front end.
- 2 anos de experiência com angularJS e/ou react JS.
- Desenvolvimento em Javascript.
- Conhecimento em Rest APIs.

## Contratação

CLT + benefícios.

## Nossa empresa

Dell provides the technology that transforms the way we all work and live. But we are more than a technology company — we are a people company. We inspire, challenge and respect every one of our over 100,000 employees. We also provide them with unparalleled growth and development opportunities. We can’t wait for you to discover this for yourself as a  Senior Front-End Engineering on our DFS (Dell Financial Services) team in Eldorado do Sul - RS.

## Como se candidatar

Inscreva-se no link da vaga: https://dell.wd1.myworkdayjobs.com/External/job/Eldorado-Do-Sul-Brazil/Senior-Front-End-Engineer--Angular--React-_R041670 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias úteis.
E-mail para contato em caso de não haver resposta: carolina.brand@dell.com

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by carolina-brand-dell** [comment]
Olá Felipe, tudo bem?

A vaga pode ser tirada da publicação. Obrigado!!

Best Regards,

Carolina Brand
Talent Acquisition Advisor, Brazil IT
Dell Technologies | Talent Acquisition
office +55 51 32745365
mobile +55 51 989341257
Carolina_Brand@Dell.com<mailto:Carolina_Brand@Dell.com>
