### ISSUE TITLE
[Fortaleza] Front-end Developer na OSF Digital

### ISSUE THREAD

**Issue by camilaalencarOSF** [frontendbr/vagas#2942]
Se você quer fazer parte de um time super legal, uma empresa global que vem crescendo cada vez mais e que vai te possibilitar um incrível desenvolvimento de carreira, então vem para OSF!!

Estamos precisando de desenvolvedores Front End para atuar no nosso escritorio de Fortaleza. São diversos projetos. 
Necessário conhecimento em Angular, React, etc... 
Inglês ao menos intermediário é um SUPER plus!!!

## Local

Fortaleza - Cocó

## Benefícios

- Plano de saúde
- Plano Odontológico
- VR 
- Auxílio Educação
- Aulas de inglês por Skype
- Possibilidade de tirar Certificação
- Vale Transporte
- Plano de Carreira Acelerado

#### Diferenciais

A OSF é uma empresa Global, você terá a oportunidade de ser você mesmo, com horários flexível e um balanço real entre sua vida pessoal e profissional. Além de um plano de carreira acelerado.

## Requisitos

**Obrigatórios:**
- Experiência com Angulas
- Experiencia com React JS
- Conhecimento em XHTML/HTML5, CSS3 and Javascript

**Diferenciais:**
- Inglês pelo menos intermediario.

## Contratação

CLT a combinar

## Nossa empresa

A OSF Digital, anteriormente OSF Global, com sua marca OSF Commerce, é uma empresa especialista em transformação digital e líder em soluções de comércio global.
Temos experiência em integrações omnichannel , internacionalização e otimização de comércio. Ajudamos empresas a serem bem-sucedidas em face dos desafios presentes no ambiente digital em rápida transformação

## Como se candidatar

Por favor envie um email para camila.alencar@osf.digital :)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
