### ISSUE TITLE
[Porto Alegre] FULL STACK Developer na TRINCA

### ISSUE THREAD

**Issue by robertakoche** [frontendbr/vagas#2944]
**Buscamos Full Stack Developer** com sólida experiência em projetos digitais (web e mobile). Procuramos alguém que seja versátil na utilização de tecnologias, detalhista, exigente com qualidade, autodidata e que valorize acima de tudo o trabalho em equipe.

// Habilidades que você precisa ter:

• Conhecimento sólido em Javascript e ReactJS;
• Experiência com desenvolvimento backend em Node.js;
• Conhecimentos em arquitetura e engenharia de software;
• Desejável experiência com arquitetura de microserviços.

O que ofereceremos e como é trabalhar na Trinca: https://trin.ca/procuramos-por-voce/

![Full Stack Node e React ](https://user-images.githubusercontent.com/38670812/74741099-f8902b00-523a-11ea-8271-c82e24312c20.jpg)

**Comment by felipefialho** [comment]
Totalmente fora dos padrões, por favor [segue nosso template](https://github.com/frontendbr/vagas/blob/master/.github/ISSUE_TEMPLATE/adicionar-nova-vaga.md) :)

**Comment by dersonsena** [comment]
@robertakoche Currículo enviado para 2 vagas de vocês

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
