### ISSUE TITLE
[Florianopolis] Front-End Developer na Inter Telecom

### ISSUE THREAD

**Issue by joaodfmota** [frontendbr/vagas#2945]
## Descrição da vaga

Atuará no desenvolvimento de ferramentas internas da empresa (ERP, CRM), portais de acesso dos clientes e novos produtos.

O candidato será membro de uma equipe multidisciplinar com outros desenvolvedores de nível pleno/sênior. Terá autonomia para moldar os projetos em sintonia com o time e com os requisitos.

## Local

Florianópolis/SC - Centro

## Benefícios

* Participação nos resultados
* Assistência Odontológica Unimed
* Assistência Médica Unimed
* Seguro de Vida
* VA de R$ 600,00
* Vale transporte
* Linha de telefone móvel ilimitada com dados para uso pessoal.

## Requisitos

**Obrigatórios:**

* JavaScript
* CSS
* APIs Restful
* Capacidade para desenvolver códigos testáveis e conhecimento para automação de testes unitários, funcionais e de integração.

**Desejáveis:**

* React
* Redux
* Hooks
* Styled Components
* Jest

**Diferenciais:**

* Office Fabric UI
* Azure DevOps
* Docker

## Contratação

CLT - Salário competitivo a depender do nível de experiência (Jr/Pl).

## Nossa empresa

A Inter Telecom trabalha com serviços de telecomunicações com um modelo de negócios único no país e busca fomentar seu crescimento acelerado com o desenvolvimento de ferramentas próprias.

Utilizamos tecnologias modernas em um ambiente de autonomia, aprendizado e desafios.

## Como se candidatar

Interessados poderão entrar em contato pelo e-mail [recrutamento.dev@intertelecom.net.br](mailto:recrutamento.dev@intertelecom.net.br) com CV, perfil no GitHub ou Linkedin. O processo de seleção é remoto.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.

## Labels

* Alocado
* CLT
* Júnior
* Pleno

**Comment by BenhurKulzer** [comment]
Enviado!

**Comment by robertov8** [comment]
Enviado! =D

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by vegbrasil** [comment]
@felipefialho a vaga ainda está disponível.

Agradeço

**Comment by simaodeveloper** [comment]
@vegbrasil aceita remoto?

**Comment by vegbrasil** [comment]
@simaodeveloper temos preferência para o modelo de trabalho alocado com alguns dias de home office na semana. Porém não deixe de enviar seu e-mail, dependendo nós ajustamos.

**Comment by evertonProgramadorCriativo** [comment]
Eu gostaria de uma oportunidade de fazer teste para vaga junior , meu email e
evertonprogramadorcriativo@gmail.com

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
