### ISSUE TITLE
[São Paulo] Front-end Developer na Webbing Brasil

### ISSUE THREAD

**Issue by essejose** [frontendbr/vagas#2946]
## Descrição da vaga

Somos um time enxuto, procuramos alguém apaixonado por desenvolvimento, que busca desafios.
Seu papel será  na criação e manutenção de aplicações web.

## Local

Escritório, São Paulo
R. Ten. Gomes Ribeiro,  Vila Clementino

## Benefícios 

- Vale refeição
- Vale transporte
 

#### Diferenciais

- Horário flexível
- Ao lado da estação Santa Cruz
- Muito cafe 

## Requisitos

**Obrigatórios:**
- HTML5/CSS3
- ReactJS
- Ajax/API REST
- ES5/ES6
- Git

**Desejáveis:**
- conhecimentos em React Native
 

## Contratação
CLT

## Nossa empresa

Com mais de 10 anos de experiência, a Webbing Brasil é especialista em atuar em parceria com Agências e Consultorias para desenvolvimento de projetos Web e Mobile.

## Como se candidatar

Por favor envie um email para contato@webbingbrasil.com.br com seu CV anexado - enviar no assunto: Vaga [ Front-End Developer ]

## Labels

- Alocado
- CLT
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by essejose** [comment]
> Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

fechei essa posição na segunda :)
