### ISSUE TITLE
[São Paulo, SP] Front-end Developer na Spread

### ISSUE THREAD

**Issue by hrsoul1221** [frontendbr/vagas#2949]
## Descrição da vaga

 - Sólida experiência com desenvolvimento utilizando frameworks e bibliotecas JavaScript modernas (principalmente angular v2+);
 - Experiência com escrita de testes automatizados (Unitários e E2E – Jasmine, Karma, Protactor ou Jest); 
 - Atuação na região da Chácara Santo Antônio, zona sul de São Paulo.

## Local

São Paulo - Zona Sul

## Benefícios

- VR de R$ 18,62 ao dia;
- VT, Seguro de Vida, Auxílio Creche;
- Assistência Médica: Intermédica Notre Dame 100% colaborador (coparticipação de 20%);
- Assistência Odontológica (funcionário paga por volta de R$ 13,00 no plano básico ou R$ 51,00 no plano top);
- Reembolso de 100% para Certificação (para funcionários com + de 6 meses, desde que a certificação seja relacionada à sua área de atuação);

## Requisitos

**Obrigatórios:**
- Desenvolvimento do API em Node.js.
- Experiência com design patterns, GIT, API’s REST, CSS, Typescript ou Flow, SPA, Webpack;

**Desejáveis:**
 - Inglês Intermediário;

## Como se candidatar

Por favor envie um e-mail para pzaparolli@hrsoul.com.br com seu CV anexado - enviar no assunto: Vaga NodeJS

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
