### ISSUE TITLE
[Curitiba - São José dos Pinhais] Front-End Developer - VHSYS

### ISSUE THREAD

**Issue by anderwesch** [frontendbr/vagas#295]
## Descrição da vaga

Estamos Buscando um Front-end Developer para compor nossa equipe de desenvolvimento. Procuramos um profissional proativo, que tenha vontade de crescer profissionalmente e esteja disposto a enfrentar novos desafios.

## Local

Escritório, São José dos Pinhais, PR - Centro

## Benefícios

- Vale Transporte;
- Vale Refeição;
- Vale Alimentação
- Plano Odontológico;
- Plano de Saúde;
- Seguro de Vida;
- Biblioteca;
- Ginástica Laboral;
- Sala de descontração;
- Programas de incentivo;
- Plano de carreira;
- Salário compatível com os conhecimentos e funções exercidas;
- Ambiente de trabalho descontraído e inovador;
- Oportunidade de eventos e cursos;

## Requisitos

**Obrigatórios:**
- Conhecimentos em arquitetura Front End, usabilidade, desempenho e testabilidade;
- Conhecimentos em CSS, SASS;
- Conhecimentos em Javascript;
- Conhecimentos com ferramentas de automação front-end como Grunt, Gulp ou Webpack.
- Inglês técnico;

**Desejáveis:**
- Conhecimentos em php
- Conhecimentos em wordpress
- Conhecimentos em Jquery, Scrum, SVN/GIT;

**Diferenciais:**
- Conhecimentos em tecnologias Javascript (AngularJS, Node.js, jQuery, etc);

## Contratação

PF CLT

## Nossa empresa

Somos apaixonados por tecnologia. Possuímos um Sistema de Gestão Empresarial, chamado VHSYS, que vai além disso, nosso objetivo é ajudar o micro e pequeno empresário a fazer a gestão eficiente de sua empresa, com maior produtividade e melhor aproveitamento dos recursos disponíveis. 

Nós pensamos em soluções para resolver as dificuldades que já existem, sem deixar de lado a constante busca pela inovação. Seja por meio de um aplicativo gratuito para celulares e tablets, seja pela gestão em nuvem, realizada de qualquer lugar com acesso a internet, ou até mesmo um aplicativo novo que gere economia de tempo e recursos para a sua empresa. 

Quer saber mais sobre a VHSYS? [vhsys.com.br/sobre/](https://vhsys.com.br/sobre/)

## Como se candidatar

Por favor entre contato através de nosso mural de vagas dentro do nosso site - [vhsys.com.br/mural-de-vagas/](https://vhsys.com.br/mural-de-vagas/)

**Comment by thenewbiemaster** [comment]
Enviado!

**Comment by ribeiroevandro** [comment]
Enviado!

**Comment by anderwesch** [comment]
Obrigado a todos pelo contato.
