### ISSUE TITLE
[Santo André, SP] Front-end Developer na CVC

### ISSUE THREAD

**Issue by hrsoul1221** [frontendbr/vagas#2950]
## Descrição da vaga

 - Sólida experiência com desenvolvimento JavaScript;
 - Necessária experiência com Angular, Ember ou React;
 - Experiência em CSS, GIT, Workflows e versionamento semântico;
 - Vivência em ferramentas de pré e pós processamento (SASS, LESS, STYLUS);
 - Contratação por tempo indeterminado;
 - Imprescindível residir em Santo André e/ou região..

## Local

Escritório, Santo André - SP

## Requisitos

**Obrigatórios:**
 - Sólida experiência com desenvolvimento JavaScript;
 - Necessária experiência com Angular, Ember ou React;

**Desejáveis:**
 - Experiência em CSS, GIT, Workflows e versionamento semântico;
 - Vivência em ferramentas de pré e pós processamento (SASS, LESS, STYLUS).

## Contratação

PJ

## Nossa empresa

Aqui na Corporação ACME somos líderes em...

## Como se candidatar

Por favor envie um e-mail para kcarvalho@hrsoul.com.br com seu CV anexado - enviar no assunto: Vaga Front-End - Santo André

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
