### ISSUE TITLE
[São Paulo] Front-end Developer na VALID

### ISSUE THREAD

**Issue by taianeuchoac** [frontendbr/vagas#2952]
## Descrição da vaga
Oportunidade para integrar equipe de Desenvolvimento da empresa, com o intuito de atuar nas aplicações internas da instituição

## Local
Atuação na Av. Paulista (Próximo Metro Consolação).

## Benefícios
Contratação PJ.

## Requisitos

**Obrigatórios:**
Sólidos conhecimentos de JavaScript, HTML5, CSS3;
Conhecimento em TypeScript, e RestFul APIs;
Foco da Atuação em Angular.js e/ou React.

## Contratação
PJ a combinar

## Nossa empresa
A VALID é uma empresa que atua com certificação e desenvolvimento de serviços digitais.

## Como se candidatar
Por favor envie um email para taiane@mazza.tech com seu CV anexado - enviar no assunto: Vaga Angular/React

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 4 dias após cada processo.

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
