### ISSUE TITLE
[REMOTO] Senior Front-end Developer na Tesorio Inc

### ISSUE THREAD

**Issue by felipetio** [frontendbr/vagas#2954]
## Descrição da vaga

Senior Front-end Developer na Tesorio Inc.
Por favor leia com atenção o a descrição no link antes de aplicar.
https://jobs.lever.co/tesorio/d6e665c1-27e9-435f-9c0a-11dd736b87f6
**Atenção!** Precisa colocar como indicação Felipe Vieira (@felipetio) e me avisar pelo [linkedin](https://www.linkedin.com/in/felipetio/)

## Local

Remoto

## Diferenciais

- U$1.000 para montar home office OU reembolso integral de coworking
- Macbook fornecido pela empresa
- Reembolso de parte do plano de saúde

## Requisitos

**Obrigatórios:**
- Possui mais de 5 anos de experiência profissional.
- Tem um forte conhecimento do ES6
- Especialista em React e ecossistema relacionado
- Inglês
- Veja mais no [link](https://jobs.lever.co/tesorio/d6e665c1-27e9-435f-9c0a-11dd736b87f6) da descrição

**Desejáveis:**
- Veja no [link](https://jobs.lever.co/tesorio/d6e665c1-27e9-435f-9c0a-11dd736b87f6) da descrição

## Contratação

Você receberá dinheiro do exterior, é possível receber por pessoa física mas o imposto é o mais alto.
Mais recomendado mesmo é abrir uma empresa individual e emitir nota como exportação de serviços para o exterior. A empresa não emite vistos.

## Nossa empresa

Tesorio é a primeira e única plataforma de desempenho de fluxo de caixa do mundo. Ele capacita os CFOs e as equipes de finanças a aumentar os lucros usando inteligência artificial para gerenciar, prever e coletar melhor dinheiro

Para saber mais: https://www.tesorio.com/

## Como se candidatar

https://jobs.lever.co/tesorio/d6e665c1-27e9-435f-9c0a-11dd736b87f6
**Atenção!** Precisa colocar como indicação Felipe Vieira (@felipetio) e me avisar pelo [linkedin](https://www.linkedin.com/in/felipetio/)

## Tempo médio de feedbacks

Costumamos enviar feedbacks semanalmente uma vez que você esteja dentro do processo.
Isto é estar dentro dos requisitos obrigatórios.

## Labels
- Remoto
- PJ
- Sênior
- Especialista

**Comment by THAYLLER** [comment]
qual o nível de inglês exigido?

**Comment by felipetio** [comment]
Olha, eu posso dizer como alguém que trabalha lá. Você precisa de inglês avançado, não precisa ser fluente. Mas tem que conseguir conversar. Toda as interações serão em inglês.

**Comment by THAYLLER** [comment]
tendi, agradeço por me responder tão rapido, meu ingles ta num nivel que eu consigo ler mas conversar ainda não

**Comment by EdeiltonSO** [comment]
Tem possibilidade de surgir vaga pra junior/pleno?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
