### ISSUE TITLE
[LONDRINA] Front-end Developer na CSG International

### ISSUE THREAD

**Issue by RafaelGorski** [frontendbr/vagas#2957]
## Descrição da vaga

Vaga para Engenheiro de Software JavaScript.
Esta vaga é como funcionário permanente CLT. Não é para um projeto especifico.
O primeiro desafio é relacionado a Journey Orchestration: https://www.csgi.com/portfolio/journey-orchestration/
https://www.businesswire.com/news/home/20190619005020/en/CSG-Journey-Orchestration-Solution-Powers-Customer-centric-Experience

Membro do time internacional de desenvolvimento de soluções para clientes como Disney+ , Formula1, Domius Pizza, Mastercard, Tele 2, 3 UK.
Plataforma toda na Cloud AWS, membros do time terão oportunidade de aprender e se aperfeiçoar. 

## Local

Escritório, Londrina - PR

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ 370/mês
- Auxílio creche
- Cursos e Congressos
- Café da manhã com Frutas, Sucos, Refri, Pão...
- Brunch Mensal 

#### Diferenciais

- 1-2 horas de almoço
- Máquina TOP

## Requisitos

**Obrigatórios:**
- 3+ anos de experiência com JavaScript ES6
- Bom Inglês de conversação

**Desejáveis:**
- conhecimentos em AWS
- conhecimentos em C# ou JAVA

**Diferenciais:**
- projetos opensource

## Contratação

CLT

## Nossa empresa

A CSG é uma empresa Americana com escritórios no mundo todo. O time de customizações está dividido entre Londrina, Bogotá, Bangaluru, Denver, Chicago.

De uma olhada --> https://careers.csgi.com/

## Como se candidatar

Aplique a vaga direto no site:
https://careers.csgi.com/job/CSINUS17125/JAVASCRIPT-Software-Development-Engineer 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
Entre em contato no meu linkedin: https://www.linkedin.com/in/rafaelgorski/

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by RafaelGorski** [comment]
por favor feche a vaga. obrigado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
