### ISSUE TITLE
[Barueri] Frontend Developer na DOMVS

### ISSUE THREAD

**Issue by thaisvilladal** [frontendbr/vagas#2958]
## Descrição da vaga
Para atuar no desenvolvimento frontend de programas de fidelidade, campanhas de incentivo e recompensa para o mercado de Loyalty.

## Local
Presencial, Barueri, SP

## Benefícios
Férias remuneradas

## Requisitos
Experiência em UX, Design, React, redux, HTML5, CSS3, Git, Scrum.

**Desejáveis:**
Desejável conhecimentos em React Native.

## Contratação
PJ por prazo indeterminado - a combinar

## Nossa empresa
A DOMVS possui experiência em gestão de empresas, onde efetivamente participam de decisões de negócios embasadas pela utilização estratégica da tecnologia da informação.
Estamos presentes no Brasil e também em Portugal.

## Como se candidatar
Por favor envie um e-mail para consultoria_villadal@domvs.com.br com seu CV anexado - enviar no assunto: Des.Frontend

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 05 dias úteis após cada processo.
E-mail para contato em caso de não haver resposta: consultoria_villadal@domvs.com.br 

#### Alocação
- Alocado

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
