### ISSUE TITLE
[Belo Horizonte] Front-end Developer na Queima Diária

### ISSUE THREAD

**Issue by JohnCosta56** [frontendbr/vagas#2959]
## Descrição da vaga

React Developer na Queima Diária. 

## Local

Escritório, Belo Horizonte - Buritis

## Benefícios

- Vale Refeição ou Alimentação;
- Vale Transporte;
- Plano de Saúde;
- Plano odontológico;
- Lanche diário;
- Frutas à disposição;
- Ajuda de custo para aulas de inglês (in company);
- Acesso a programas Queima Diária <3;
- Acesso ao clube de vantagens da plataforma;
- No dress code (pode trabalhar com a roupa que quiser);
- Ambiente descontraído e motivador;
- Confraternizações frequentes na empresa.

## Requisitos

**Obrigatórios:**
Bons conhecimentos de padrões de projeto, refatoração e testes unitários;
Experiência no desenvolvimento de aplicativos Mobile
Experiência com React/React Native;

**Desejáveis:**
Inglês Avançado.
Experiência no desenvolvimento de aplicativos para Smart TV's;

## Contratação

CLT

## Nossa empresa

Somos uma startup inovadora e com crescimento a todo vapor! Visamos ajudar as pessoas a se tornarem aquilo que desejam ser através de uma vida mais saudável, harmoniosa e cheia de autoestima. Para isto acontecer, temos a maior e mais inovadora plataforma online do Brasil dedicada à atividade física e ao bem-estar.

Nosso time é um mix de excelência, trabalho em equipe e muuuita paixão! Por isso, buscamos profissionais que não só entreguem resultado, mas que chamem a responsabilidade do negócio para si, que tenham sede de crescimento, que sejam gestores do próprio processo e com a capacidade de criar relações abertas através da transparência. Fez sentido para você? Então vem fazer parte!

## Como se candidatar

Através do link: https://queimadiaria.recruiterbox.com/jobs/fk015mn/

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
