### ISSUE TITLE
[São Paulo] Front-end Developer @ AMARO

### ISSUE THREAD

**Issue by cassiocardoso** [frontendbr/vagas#296]
# Descrição da vaga

Estamos em busca de um _front-end developer_ (pleno/sênior) para integrar o nosso time. Buscamos alguém que já trabalhe na área, que possua bom conhecimento do ecossistema _front-end_ atual e que possua experiência com React e Redux que são a base da nossa nova plataforma de e-commerce.

# Local

Rua Antonio Nagib Ibrahim, Água Branca, São Paulo/SP

 # Responsabilidades

- Desenvolver novos componentes que serão integrados à nossa plataforma de e-commerce.
- Colaborar com os times de UX e Marketing para planejar, prototipar e construir novas interfaces.

# Requisitos

## Obrigatórios:

- Experiência com React (já ter feito algum projeto open-source ou ter usado no ambiente de trabalho).
- Bom conhecimento de JavaScript nativo (_ES2015 and beyond_).
- Bom conhecimento de CSS avançado (boas práticas de estruturação de projetos com Sass)
- Experiência com Git.
- Saber trabalhar em grupo.

## Diferenciais:

- Conhecimento em TDD (Test-driven development).
- Experiência em um ambiente de desenvolvimento ágil.

## Contratação

- CLT ou PJ a combinar

## Benefícios

- VR (ou restaurante na empresa)
- VT
- Plano de saúde
- Gympass
- Setup customizado de acordo com as preferências da pessoa
- _Budget_ anual para participação em eventos
- Incentivo ($$) para realização de cursos de aprimoramento técnico
- Desconto exclusivo em produtos AMARO

## Nossos Diferenciais

- Futebol na sexta-feira.
- Happy hour com cervejas artesanais.
- Não precisa dar suporte ao IE.

## A AMARO

AMARO é uma marca online de moda feminina com sede em São Paulo. Lançamos coleções mensais com as últimas tendências de moda a preços acessíveis, entregues rapidamente, em grande estilo. Através de tecnologia de ponta, integração vertical e distribuição omni-canal, a AMARO está mudando a forma como os brasileiros consomem moda.

Todos os dias nos desafiamos para encantar nossos clientes com uma variedade de produtos sempre em renovação, com as últimas tendências da moda, a preços acessíveis. Tudo isso, entregue de forma rápida e em grande estilo.

## Como se candidatar

- Acesse nosso [repositório no GitHub](https://github.com/amarofashion/front-end-challenge) e leia as instruções do desafio.
- Resolva o desafio, preste atenção nos requisitos e nos pontos extras.
- Submeta um pull-request e nós avaliaremos seu trabalho.

**Comment by cassiocardoso** [comment]
Labels: alocado, clt, pj, pleno, senior

**Comment by uselessdev** [comment]
E lá vamos nós.

**Comment by vedovelli** [comment]
**Não precisa dar suporte ao IE.** <<< mitada boa!

**Comment by cassiocardoso** [comment]
Fechando a issue. Não foi dessa vez que encontramos alguém. :(

**Comment by Marlysson** [comment]
Vaga ainda aberta? Ou não foi encontrado alguém daqui ..

Em ter, 9 de mai de 2017 às 09:18, Cassio Cardoso <notifications@github.com>
escreveu:

**Comment by cassiocardoso** [comment]
A vaga ainda está em aberto.

**Comment by jvcjunior** [comment]
Há possibilidade de remoto?

**Comment by LFeh** [comment]
@cassiocardoso Abre de novo?

**Comment by cassiocardoso** [comment]
Fala @jvcjunior estamos buscando alguém para presencial no momento. Sem possibilidade de remoto por enquanto.

Pronto @LFeh 😄

**Comment by mtmr0x** [comment]
@cassiocardoso essa vaga continua aberta?

**Comment by cassiocardoso** [comment]
Continua...
