### ISSUE TITLE
[São Paulo] JavaScript Software Developer na idwall

### ISSUE THREAD

**Issue by mjnr** [frontendbr/vagas#2960]
## Descrição da vaga
A **[idwall](https://idwall.co/sobre-nos/)** está em busca de um JavaScript Software Developer, com perfil Júnior/Pleno para nos ajudar a construir novas iniciativas e manter nossas aplicações web para clientes internos e externos. Gostaríamos primordialmente de uma pessoa interessada em produzir códigos robustos escaláveis e em contribuir para a evolução da nossa plataforma.

### O que esperamos de você
- Atuar de forma colaborativa no planejamento e desenvolvimento de webapps client/server-side utilizando JavaScript.
- Desenvolver componentes visuais utilizando boas práticas de UI/UX dialogando com nosso time de Designers de produto.
- Colaborar com a solidificação do nosso Design System, entregando código reutilizável e escalável.
- Atuar na manutenção e melhoria contínua de produtos já existentes.
- Participar da construção de uma cultura de tecnologia baseada em colaboração e diversidade.

## Local

Escritório, São Paulo - Consolação

## Benefícios

- Assistência médica
- Assistência odontológica
- Vale-refeição
- Vale-alimentação
- Benefício de saúde mental (ZenKlub)
- Auxílio-creche
- Frutas
- Massagem
- Gympass

## Requisitos

**Obrigatórios:**
- Perfil colaborativo, sempre buscando novos conhecimentos e validando ideias
- Conhecimentos em tecnologias para desenvolvimento Frontend HTML/CSS/JavaScript
- Familiaridade com frameworks/bibliotecas JavaScript para construção de SPAS, sites estáticos (Trabalhamos com React e NextJS atualmente, mas se você possui conhecimento em outras ferramentas semelhantes, sinta-se livre para dividir conosco um pouco da sua visão)
- Mentalidade agnóstica com relação a linguagens, bibliotecas e frameworks: conseguir enxergar o valor de cada estratégia, seus pontos fracos e fortes
- Familiaridade com JavaScript tooling (Package Managers, Test Runners, Task Runners, Bundlers, Linters, Formaters)
- Familiaridade com ferramentas de versionamento (Git)
- Familiaridade com metodologias ágeis (Kanban, Scrum)

**Desejáveis:**
- Design Patterns em JavaScript
- Conhecimentos básicos de JavaScript server-side(Node JS), frameworks e bibliotecas para desenvolvimento de APIs
- Interesse em outras linguagens e paradigmas (Rust, Golang, Clojure, Python)
- Princípios de programação funcional com JavaScript
- Inglês Técnico

## Contratação
CLT

## Nossa empresa

Somos uma empresa que valoriza a diversidade em todas suas formas. Em vez de apenas aceitarmos os vieses inconscientes de nosso sistema social, queremos hackear o sistema e trabalhar a favor da igualdade, criando ações afirmativas que favoreçam a diversidade.

Buscando ativamente promover a diversidade de gênero, encorajamos que mulheres se candidatem para nossas vagas de tecnologia.

Na idwall, trabalhamos para fazer a diferença. Nós desenvolvemos as melhores tecnologias para que as pessoas e empresas que usam nossos serviços possam atingir seus objetivos mais desafiadores. Nós nos movemos pelo esforço em construir um futuro mais seguro, livre de fraudes e menos burocrático, onde as organizações tenham a confiança necessária para impulsionar novos negócios. Acreditamos que relações de confiança são estabelecidas por meio da transparência e parceria, seja criando novas soluções ou auxiliando as empresas a combater fraudes de identidade. Nossas pessoas são motivadas por construir um futuro mais seguro, ágil e inovador – e só estamos no começo!

Saiba mais **[aqui](https://idwall.co/sobre-nos/)**

## Como se candidatar

Aplicar pela nossa plataforma de recrutamento:
https://apply.workable.com/idwall/j/68038BF4A5/apply/

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: mirella.barbin@idwall.co

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by mjnr** [comment]
A vaga foi fechada @felipefialho
