### ISSUE TITLE
[São Paulo] Front-end Developer Pleno na Deloitte

### ISSUE THREAD

**Issue by diogom-42** [frontendbr/vagas#2961]
## Local

São Paulo – SP 

## Requisitos

•	Definir o problema dos usuários, entrevista com usuário, teste com usuários, protótipos de baixa/média/alta fidelidade e outras metodologias para desenvolvimento de projetos
•	Desenvolvimento de wireframe
•	Desenvolvimento Front-End (site, sistema, blog Wordpress)
•	Criação de CSS com base em protótipo

## Contratação
CLT

## Como se candidatar

Interessados enviar CV por e-mail para jveiga@deloitte.com com o assunto [Oportunidade: Front-end Developer]

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by eriktos** [comment]
Enviado! Aguardo retorno! Boa noite! Obrigado!

Em sex, 21 de fev de 2020 09:46, Diogo Moura <notifications@github.com>
escreveu:

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
