### ISSUE TITLE
[Jaguariúna, logo em Campinas] Senior React Developer na AB-Inbev (Ambev)

### ISSUE THREAD

**Issue by xandebianchi** [frontendbr/vagas#2965]
# **Informações gerais da empresa**

### **A maior cervejaria do mundo** abriu no final de 2018 seu setor de _tecnologia_, o time chamado: _Beertech_.
Uma novidade, pois antes os aplicativos eram feitos por terceiros.

E agora está acontecendo a **Transformação Digital** da empresa, onde se constrói um aplicativo B2B para vendas dos seus produtos (cerveja, não alcoólicos, etc.), e ele funciona em todos os países que a empresa trabalha, pelo mundo todo. 

A **Anheuser-Busch InBev** (abreviada **AB InBev**), **líder no mercado mundial**, é uma empresa multinacional de bebidas e cervejas formada em 2004 pela fusão da belga **Interbrew** e da brasileira **Ambev**. Está sediada em Leuven, na Bélgica, e possui escritório em Nova York, e sedes em Jaguariúna-SP, Londres, Cidade do México, Johanesburgo, St. Louis, e outros locais. Conta com mais de duzentas marcas de bebidas, entre as quais se destacam Brahma, Skol, Antarctica, Budweiser, Corona, Stella Artois, Beck's, Leffe, Hoegaarden na Europa. 

### - A sede da vaga atualmente é em Jaguariúna-SP-Brasil. Em um futuro próximo, estaremos em Campinas-SP.

 **Porém,** há outros locais que estão sendo incluídos como possibilidade de se trabalhar, como sul, etc, e será possível transições de local. 

# **Sobre o time**

Estamos repensando a maneira como a AB InBev faz negócios com seus clientes de varejo e criando experiências digitais para atendê-los. Você ingressará em uma nova organização digital da AB InBev que consiste em estratégia digital, produto, design, análise, operações e engenharia. Essa organização é responsável por criar os produtos e plataformas que transformam nossas operações de vendas tradicionais em todo o mundo.

# **About the Job**

The Senior React Engineer will help lead the Render React (Next.JS) to victory. Armed with years of experience developing both team members, and awesome architecture, the Engineer will be helping us build a server-side rendering service with Next.JS (and TypeScript). We will have the opportunity to build this greenfield project using best practices, like Readme/Test Driven Development (TDD), and a performance budget. We will explore every avenue for speed/reliability. The main stakeholders will include the Directors of Engineering, Design, and Project Management. Overall, we are building a dynamic system to quickly iterate on designs, gain valuable customer insights, and redesign accordingly. Our goal is that each and every component will be built by the Component Library Team for each form of Frontend (we currently have Android, iOS, and we’re building a WebApplication).

You will:
- Have an active role in designing features, architecting scalable and composable building blocks of frontend code, made complicated by the need to support internationalization.
- Create and maintain code and git standards that govern the high-level architecture of all front-end applications and apply them in a large distributed team environment.
- Maintain the quality and performance of our growing set of React Web Components and help establish and monitor performance/quality metrics.
- Develop a growing team of engineers and participate in a massive digital transformation for one of the world’s largest companies.

# **Desired/Required Qualifications**

- 4+ years of development expertise in JavaScript (TypeScript preferred).
- 3+ years of development expertise in React (or Angular, Vue, similar Frontend frameworks).
- B.S. in Computer Science, Engineering, or equivalent years of work experience.
- Experience deploying on cloud infrastructure for Azure (or Amazon AWS, Google Cloud).
- Experience mentoring Junior developers and ensuring code standards you’ll help create.

# **Sobre nós**

No Brasil possuímos uma unidade com mais de 200 fanáticos por cerveja, e também nossa célula de tecnologia, chamada BeerTech que é focada em prover serviços e soluções em escala global para todas as cervejarias do grupo.

# **Tipo de Contratação**

CLT

# **Como se aplicar**

Mande seu CV para o e-mail abaixo com o título "Vaga Senior React Developer":
alexandre.bianchi@ab-inbev.com 

**- Link de diversidade e inclusão:**
[Link de diversidade e inclusão](https://www.ab-inbev.com/careers/why-ab-inbev/diversity-and-inclusion.html)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by xandebianchi** [comment]
Continua válida

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
