### ISSUE TITLE
[São Leopoldo, RS - Porto Alegre, RS - ou Remoto] Front-end Developer na CWI Software

### ISSUE THREAD

**Issue by Cristiane-Ibanez** [frontendbr/vagas#2966]
## **.: CWI Software :.**
Pra estar sempre em movimento, é preciso ter muita energia. Aqui na CWI, oferecemos aos profissionais um ambiente inspirador, onde o conhecimento circula e o entusiasmo movimenta a fazer sempre mais e melhor.
Por isso, acreditamos em nossos entusiastas e oferecemos oportunidades para eles crescerem em projetos desafiadores de grandes clientes, dando as ferramentas necessárias para que cada um construa seu próprio desenvolvimento, adquirindo um propósito em suas tarefas e tendo liberdade total para propor ideias e expressar opiniões.

## Local
São Leopoldo, RS / Porto Alegre, RS - ou Remoto 

## Requisitos
- Experiência com desenvolvimento frontend web e mobile
- Conhecimentos em React Native, Redux, AngularJS
- Conhecimentos em HTML, CSS, Javascript
- Conhecimentos em controle de versão no Git e gerenciamento de dependências

## Contratação
CLT

## Nossa empresa
CWI Software

## Como se candidatar
Envie teu cv para o email para work@cwi.com.br

#### Regime
- CLT

#### Nível
- Pleno / Sênior

**Comment by edsonvieirademetrio** [comment]
CV enviado!

**Comment by rodgomesc** [comment]
vaga ainda está aberta? @Cristiane-Ibanez  qual média salarial para o profissional de nível pleno?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
