### ISSUE TITLE
[Florianópolis] React Front-end Developer na HostGator

### ISSUE THREAD

**Issue by joaofidelix** [frontendbr/vagas#2967]
## Descrição da vaga

Quer fazer parte de um time que utiliza metodologia de desenvolvimento ágil e foca no aprendizado contínuo? Você está aberto a mudanças e ansioso para trabalhar com ferramentas e tecnologias que podem estar fora de sua zona de conforto? Você gosta de trabalhar em um ambiente aberto e colaborativo? Você expressa suas opiniões e tem os fatos para apoiá-los, e está disposto a comprometer-se quando necessário? Você gosta de se divertir enquanto trabalha, mas entenda quando é hora de ficar sério?

Se você respondeu SIM a todas as perguntas acima, você será mais do que bem-vindo ao nosso processo seletivo!

## Local

Presencial - Florianópolis/SC

## Benefícios

- Plano de Saúde sem custo nenhum para o colaborador;
- Vale alimentação ou refeição da Sodexo;
- Vale transporte;
- Cartão do Sesc;
- Dia da fruta;
- Ginástica laboral;
- Comemoração dos aniversariantes no final do mês;
- Parcerias com descontos em academia, restaurantes, universidades e escolas de idiomas;
- Sorteio de prêmios (caso atinja a meta);
- Confraternizações mensais (temáticas, open food & open drink);

#### Diferenciais

- Ajuda de custo *
- Pessoas de diversos pontos do Brasil e da América Latina, para promover ainda mais nossa cultura de diversidade;
- Espaço Gourmet e de lazer (churrasqueira, mesa de sinuca, fliperama, playstation4, entre outros);

## Requisitos

**Obrigatórios:**
- Vivência com mais de 5 anos de Front-end;
- React / Redux;
- ESLint;
- Git / Git Flow;
- Domínio em JavaScript / ES6 +, HTML5, CSS3;
- Conhecimento em análise de requisitos e APIs REST;
- Já ter familiaridade com a cultura e metodologias ágeis;
- Vivência com teste unitários;
- Inglês avançado.

**Desejáveis:**
- Morar em Florianópolis (a Ilha da magia) - Vale do Silício brasileiro;
- Docker;
- AWS Cloud;
- Experiência com BDD;
- Conhecimento de ferramentas Atlassian (JIRA, Bamboo, Confluence, Stash).

## Contratação

CLT a combinar

## Nossa empresa

A HostGator faz parte do grupo Endurance International, uma companhia de capital aberto que atua globalmente no mercado de web hosting. Com faturamento anual próximo a 1,2 bilhões de dólares, atendendo ao todo cerca de 4,8 milhões de pessoas, cada vez mais caminhamos para um mundo em que garantir uma presença online não precisará ser algo difícil e demorado.

Aqui somos apaixonados por fazer com que produtos e serviços possam inovar, gerar valor e também criar oportunidades aos nossos clientes. Para isso, contamos com os Gators - como chamamos nossa equipe - diariamente engajados em compreender mais sobre nosso público, otimizar sua jornada, experiência e também oferecer o melhor serviço! Hoje já são milhares de pessoas que confiam em nosso trabalho, tanto no Brasil quanto na América Latina.

## Como se candidatar

Candidatar-se pelo link: http://bit.ly/37OmzPh

## Labels

- 🏢 Flexível
- 🏢 Presencial
- 👴 Sênior
- ⚖️ CLT
- 💰 5k-10k

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by joaofidelix** [comment]
Está aberta ainda!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
