### ISSUE TITLE
[Brasília] Front-end Developer no Direção Concursos

### ISSUE THREAD

**Issue by caioreis** [frontendbr/vagas#2968]
## Descrição da vaga
Apaixonado por educação e tecnologia? Essa vaga pode ser pra você! O Direção Concursos, uma das mais promissoras EdTechs do país, está procurando por um front-end developer para compor o seu time. Depois de um 2019 onde tivemos 100% de crescimento a cada trimestre, entendemos que chegou a hora de dar o próximo passo em tecnologia. 

Queremos reconstruir toda a jornada do nosso cliente. Desde o fluxo de consumo de conteúdos gratuitos (temos milhões de visitas por aqui), passando pelo fluxo de compra até chegar no consumo de conteúdo. Você está pronto pra um desafio desse?

## Local

Remoto ou Escritório, Brasília

#### Diferenciais

- salário acima do mercado
- monte a sua máquina como desejar
- auxílio realocação
- home office
- vem conhecer pra ver todo o resto :)

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento e manutenção de sistemas responsivos
- Experiência em Javascript, principalmente Ajax e JQuery
- Experiência com consumo de APIs

**Desejáveis:**
- Expêriencia em frontend com sistemas em .NET
- Experiência com wordpress
- Experiência com angular
- Experiência com pipelines de assets

**Diferenciais:**
- Experiência com cloud AWS
- Experiência com manutenção e integração de sistema legado

## Contratação

PJ a combinar - Altamente competitivo

## Como se candidatar

Por favor envie um email para mario@direcaoconcursos.com.br com seu linkedin - enviar no assunto: Vaga Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by danielswater** [comment]
Enviado :)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
