### ISSUE TITLE
[São Paulo] Front-End Developer (Angular JS) 

### ISSUE THREAD

**Issue by Brunabrandasi** [frontendbr/vagas#297]
## Descrição da vaga

Ter atuado com desenvolvimento de FrontEnd (AngularJS, HTML5, CSS3 e JS);
Relacionamento com clientes no nível técnico e gerencial;
Experiência com projetos de FrontEnd;
## Benefícios

VR, AM, AO.
- ...

## Requisitos

**Obrigatórios:**
- 4 anos de experiência com desenvolvimento de Front.
- 2 a 3 anos de experiência com Angular JS.

**Desejáveis:**

Conhecimento de processo de integração continua
Conhecimento e atuação com metodologias ágeis (TDD, BDD, DDD e Scrum)
Conhecimento em desenvolvimento de portais e mobile

## Contratação

CLT

## Nossa empresa

A Resource IT é uma das principais e mais bem-sucedidas empresas de serviços de TI. Com mais de 25 anos de atuação no mercado, possui uma equipe de 2.5 mil profissionais altamente capacitados e aptos para atuar em projetos no País e no exterior, em especial na América Latina e Estados Unidos, por meio de uma moderna estrutura com 19 escritórios e Centro de Inovação no Vale do Silício (EUA).

## Como se candidatar

Por favor envie um email para bruna.vieira@resource.com.br com seu CV anexado - enviar no assunto: Vaga AngularJS

**Comment by paulo101977** [comment]
@Brunabrandasi Bom dia. Eu te enviei o currículo por engano, não tinha visto o local da vaga :(
