### ISSUE TITLE
[Jaguariuna/Campinas] React Developer PL/SR - AbInbev

### ISSUE THREAD

**Issue by taianeuchoac** [frontendbr/vagas#2976]
## Descrição da vaga
Atuará em projetos diversos dentro da organização, utilizando React.

## Local
Trabalho Presencial.

## Benefícios
- Plano odontologico
- Plano de saúde
- Seguro de vida
- VR
- VT
- PLR

#### Diferenciais
Ambiente descontraído/informal.
Possibilidade de carreira internacional.

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento utilizando React.

## Contratação
CLT a combinar

## Como se candidatar

Por favor envie um email para taiane@mazza.tech com seu CV anexado - enviar no assunto: Vaga React

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
