### ISSUE TITLE
[Belo Horizonte] Desenvolvedor Frontend React.js na Ensinio

### ISSUE THREAD

**Issue by guiavila** [frontendbr/vagas#2977]
Desenvolvedor Frontend Javascript React.js na Ensinio (BH)

Obs 1: Trabalho presencial, mas será remoto temporariamente até maio ou junho de 2020.
Obs 2: Apenas desenvolvedores de nível "Pleno Avançado" ou superior. Não estamos contratando desenvolvedores júniors.

## Descrição da Vaga

Procuramos desenvolvedores especialistas no framework React.js (Javascript) para integrar o time de desenvolvimento do Frontend da Ensinio. Nossa plataforma oferece soluções de ecommerce e recursos avançados de Cursos Online e ensinio à distância, para empresas e empreendedores dos mais diversos nichos. Nós oferecemos a plataforma perfeita para quem quer ensinar e vender online, e queremos ter você nesse time!

Procuramos pessoas competentes e pontos fora da curva que querem crescer junto com a Ensinio. Veja se você atende a esses 5 pontos:

1. Tenha experiência com Frontend;
2. Tenha experiência com React.js;
3. Goste de soluções online para Educação;
4. Goste de fazer parte de um time que cria produtos que revolucionam e quebram paradigmas;
5. É competente e está sempre estudando, aprendendo e se aperfeiçoando.

Se sim, vem com a gente. Nos preocupamos com o que você entrega e não como você se veste! Seja bem vindo à Ensinio :)

## Sobre a Ensinio

Pequena descrição sobre o que é a Ensinio:

A Ensinio é uma solução completa para quem precisa vender e ensinar online. Você vai ter sua  própria plataforma para vender produtos digitais e físicos, criar cursos e construir sua própria Escola  Online com um sistema EAD completo. A plataforma é inteiramente customizável e você vai ter uma rede social e comunidade de  usuários interagindo com seus conteúdos em uma plataforma gamificada, com centenas de recursos  avançados para garantir a melhor experiência de navegação, compra e aprendizado.

## Local

Escritório em Belo Horizonte - MG
Obs: Trabalho presencial, mas será remoto temporariamente até maio ou junho de 2020.

## Requisitos fundamentais

- Bastante conhecimento em Frontend;
- Conhecimento avançado de React.js;
- Conhecimento de Redux e Redux Saga;
- Conhecimento avançado de Javascript/JSX;
- Experiência comprovada de trabalho com React.js;
- Versionamento de código (Git);
- Conhecimento de UI e UX;
- Processos de code review;
- Integração do frontend em React.js com a API do Backend;
- Async;
- Typescript;
- Push Notification;
- CSS (CSS-SASS e CSS-LESS);
- HTML 5;
- React Navigation;
- React Hooks;
- Styled Components e Animações (parte do UI do frontend);
- Testes unitários;

## Seria fantástico se em seu background tivesse

- Vários projetos já desenvolvidos com React.js;
- Bastante experiência em frontend;
- Habilidade de escrever e falar em Inglês.
- Conhecimento de Ant-design

## Nível e experiência

Apenas desenvolvedores de nível "Pleno Avançado" ou superior. Não estamos contratando desenvolvedores júniors.

## Contratação

PJ a combinar

## Benefícios

- Você tem voz. Os fundadores ouvem todas as pessoas. Sua opinião será levada em consideração.
- Perspectiva de crescimento;
- Sem dress code (Valorizamos a diversidade. Pode se vestir do seu jeito!);
- Contato com novas tecnologias de mercado;
- Ingressos para Congressos/Convenções de Tecnologia e Programação;
- Férias anuais;
- Feriados;
- Flexibilidade de horários;
- Trabalhar remoto nas sextas feiras;
- Lanches na empresa;
- Cafés, bebidas e snacks.

## Como se candidatar

Seja bem vindo à Ensinio! Para entrar no time de desenvolvimento da Ensinio, envie seu CV para jobs@ensinio.com com pretensão salarial e seu perfil profissional. Nos conte mais detalhes sobre você e o motivo pelo qual você quer esta vaga. Nós queremos conhecer mais do seu background, das suas habilidades e das suas perspectivas futuras. Vamos construir um produto incrível juntos! Envie sua mensagem com o assunto: "Vaga - Backend Laravel" e vamos responder em até 5 dias úteis.

**Comment by ReactGirl** [comment]
Boa essa vaguinha.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by guiavila** [comment]
Já contratamos 2. Há mais 3 vagas.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
