### ISSUE TITLE
[São Paulo] Front-end Developer Pleno/Sênior na Logstore

### ISSUE THREAD

**Issue by diegodfsd** [frontendbr/vagas#2978]
## Descrição da vaga

Estamos em busca de aprimorar nossas plataformas, somos movidos por desafios e para isso gostaríamos de convidá-lo a fazer parte de nosso time :D

O que esperamos de você?

Procuramos pessoas capazes de entregar valor para os nossos clientes. Nos orgulhamos de ser uma empresa que ao longo do tempo vem conquistando clientes pela alta capacidade de solucionar problemas com rapidez e qualidade. Queremos pessoas que tenham em seu DNA o desejo de transformar para melhor o ecossistema ao seu redor, com disponibilidade para aprender e contribuir na busca por soluções ótimas para os desafios dos nosso clientes.

## Local

Escritório, São Paulo - Av. Angélica - inovaBra habitat

## Benefícios

- Vale-refeição
- Convênio médico
- Horário flexível
- Férias remuneradas
- Ambiente descontraído.

## Requisitos

**Obrigatórios:**
- Excelentes conhecimentos em Vanilla Javascript
- Excelentes conhecimentos em HTML5 e CSS3
- Excelentes conhecimentos em Frameworks JS (Angular e Ionic)
- Experiência em integração com API's Rest
- Testes automatizados
- Versionamento de código com Git
- Bom relacionamento e comunicação.

**Desejáveis:**
- Conhecimentos em Frameworks JS (React, React Native, Vue e etc)
- Experiência com práticas ágeis como Scrum, Kanban e XP
- Conhecimento em princípios de design de interação, UX e Design System

## Contratação

PJ a combinar

## Nossa empresa

Logstore é uma plataforma SaaS (Software as a Service) para tornar o varejo Omnichannel. Somos pioneiros no processo de transformação digital a partir da logística inboud. Nossa plataforma possibilita que lojas sejam transformadas em verdadeiros Mini Centros de Distribuição, habilitando mais de 15 diferentes tipos de entrega a partir da loja com solução ponta-a-ponta (Picking, Packing, Checkout e Shipment).

‘Pessoas compram em um CLICK, mas a entrega não acontece na mesma velocidade’.
Empoderamos a logística de nossos clientes para através de nossos softwares possibilitar a melhor jornada de experiência O2O (Online To Offline) do consumidor.
Atuando no mercado B2B com soluções de classe mundial, nossas tecnologias estão presentes em empresas como Leroy Merlin, Dafiti, FedEx, Renner e outras grandes.

## Como se candidatar

Por favor envie um email para diego@logstore.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor Front-End

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: joicy@logstore.com.br

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by diegodfsd** [comment]
@felipefialho não fechamos a vaga ainda, mas recebemos bem menos candidatos do que esperavamos, por isso, pode fechar a vaga. 

Obrigado
