### ISSUE TITLE
[Londrina-PR/Remoto] Front-end Developer na x-brain

### ISSUE THREAD

**Issue by gabrielgomesferraz** [frontendbr/vagas#2979]
![Publicação Front-end](https://user-images.githubusercontent.com/11380076/75453491-bf4e6e00-5952-11ea-8172-c630cd94e238.png)

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- Estágio

#### Nível
- Júnior (apenas alocado)
- Pleno
- Sênior
- Especialista

#### Labels
- CLT
- Júnior
- Pleno
- Sênior
- Especialista
- Remoto

**Comment by ElmiRabelo** [comment]
Currículo enviado! Estou de mudança para Maringá no dia 07.

**Comment by hallss93** [comment]
Há possibilidade de PJ?

**Comment by gabrielgomesferraz** [comment]
@hallss93 Apenas CLT mesmo
