### ISSUE TITLE
[São Paulo] Front-end Developer Senior na 3,2,1 Beauty

### ISSUE THREAD

**Issue by CavalcanteLeo** [frontendbr/vagas#2982]
**Descrição da empresa**
Oferecemos serviços de bem estar e beleza in company (manicures, quick massage, barbeiro, design de sobrancelhas, yoga etc.).
Nosso objetivo é que ajudar a otimizar o dia a dia dos colaboradores e melhorar a qualidade de vida no trabalho.
Cada empresa tem o seu próprio site para o agendamento online e o pagamento é feito no site no ato do agendamento ou na maquininha após o atendimento. Ou seja, zero trabalho para o RH e aumento de engagement.
Atendemos semanalmente gigantes do mundo das startups como WeWork, 99Taxis, Nubank e Regus e empresas nacionais e multinacionais como Suzano e Burger King.
Venha fazer parte das empresas inovadoras e que se preocupam com o bem-estar dos seus funcionários.

**Atividades e Responsabilidades**
- Desenvolvimento de telas/modulos e funcionalidades no Front-End;
- Documentar todos os componentes utilizando storybook; 
- Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas; 
- Integração com outros sistemas e APIs; 
- Ser auto-gerenciável, aplicar diariamente o conceito scrum;
- Participar da sprint planing, review e retrospectiva, assim como as daily; 
- Participar da concepção do produto (utilizando metodologia design thinking); 
- Conseguir quebrar as tasks de uma sprint backlog em no máximo 1 dia de duração ou menos;

Para se candidatar a essa vaga, você deve ter uma grande experiência com vue.js e react, ser obcecado por layout, transições de telas/componentes, animações, além de conhecimentos em metodologias ágeis como scrum, nexus e kanban.
Ambiente descontraído, com liberdade de horários.

Essa vaga é para você se tem como front-end seu amor maior.

**Requisitos**
* Javascript ES6
* Typescript (Desejável) 
* Vue (+4 anos)
* Vuex
* Nuxt.js
* React (+4 anos)
* Redux
* Next.js 
* CI/CD
* GraphQL
* Storybook
* Noções de UX
* Offline First
* Web Push Notification
* Webpack
* Internacionalização

**Outros requisitos** 

* Firebase (Cloud Messaging, Remote Config) 
* Código limpo e claro
* Testes automatizados 
* Scrum, kanban e OKR

**Desejáveis**

* React Native
* Flutter 
* Node

**Local**
Av Faria Lima - SP

**Contratação**
PJ ou CLT, ótimos salários

**Como se candidatar**
Por favor envie um email para leonardo@321beauty.com.br com seu linkedin e breve descrições nos projetos mais desafiadores que você já trabalhou
 Enviar no assunto: Vaga frontend

**Labels**
Alocado
 Sênior
 PJ ou CLT
 Salário a combinar 
Ninja

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
