### ISSUE TITLE
[São Paulo] Front-end Developer na Neverland

### ISSUE THREAD

**Issue by LRcompany** [frontendbr/vagas#2984]
## Local
São Paulo - SP - Avenida Paulista

## Benefícios
- VR / VT
- Férias
- 13º

## Requisitos

**Obrigatórios:**
- Conhecimentos em GULP, LESS/SASS, HTML5;
- Conhecimentos sólidos em Javascript/Jquery;
- Noções básicas de Design e saber trabalhar com easings/motions;
- Ser organizado, comprometido, ágil e saber trabalhar em equipe;
- Estar disposto a aprender sempre e a sair da zona do conforto regularmente;
obs. Saber identificar possíveis problemas e contorná-los.

**Diferenciais:**
- GIT;
- NODE JS;
- React / React Native;

## Contratação
PJ a combinar - Enviar Pretensão Salário

## Como se candidatar

Por favor envie um email para luiz@neverland.digital com seu CV anexado - enviar no assunto: Vaga FrontEnd

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

**Comment by renatorib** [comment]
Eu recomendo :wink: 
A pessoa que trampar com o @LRcompany vai aprender muito, assim como eu aprendi quando trabalhei com ele há 5 anos atrás

**Comment by jorgeluiz1586** [comment]
Currículo enviado

Em qui., 27 de fev. de 2020 às 18:27, Renato Ribeiro <
notifications@github.com> escreveu:

**Comment by HenryKun55** [comment]
Tem a possibilidade de remoto ?

**Comment by LRcompany** [comment]
> Tem a possibilidade de remoto ?

Infelizmente não, apenas presencial.

**Comment by LRcompany** [comment]
> Eu recomendo 😉
> A pessoa que trampar com o @LRcompany vai aprender muito, assim como eu aprendi quando trabalhei com ele há 5 anos atrás

Boaa.. o/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
