### ISSUE TITLE
[Rio de Janeiro ou Remoto] Front-end Developer (Jr ou PL) na W2Bit

### ISSUE THREAD

**Issue by davidsonsimoes** [frontendbr/vagas#2986]
## Descrição da vaga

Em seu dia a dia atuará com o HTML5, CSS3 e J5, React e React Native desenvolvimento de funcionalidades e telas novas para web ou Mobile, resolução de Bug’s, consumo de API’s e integração entre sistemas via front-end, por isso é necessário o conhecimento intermediário de aplicação dessas tecnologias;

Será um diferencial ter conhecimento e/ou experiência com a plataforma Firebase, ou apreender a plataforma em menos de 2 meses - desafiador!

Será um diferencial ter conhecimento básico ou avançado em back-end (Node).

## Local
Remoto ou Escritório do Rio de Janeiro (Barra da Tijuca)

## Benefícios

- A combinar

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com Node
- 2 anos de experiência com React e React Native

**Desejáveis:**
- conhecimentos em Javascript on Git, Trello etc

**Diferenciais:**
- Conhecimentos em Back-end ou infra

## Contratação

PJ a combinar

## Nossa empresa

StartUp promissora com diversos projetos desafiador!

## Como se candidatar

Por favor envie um email para davidson@w2bit.com com seu CV anexado e pretensão salarial - enviar no assunto: Vaga React

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 4 dias após cada processo.
E-mail para contato em caso de não haver resposta: davidson@w2bit.com

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- Freela
- PJ

#### Nível
- Júnior
- Pleno

**Comment by ReactGirl** [comment]
> 2 anos de experiência com Node

é full stacker a vaga?

**Comment by JoseFlavioBR** [comment]
Junior com 2 anos de XP ? está complicado isso em

**Comment by dbarrinha** [comment]
CV enviado !!!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by victoorraphael** [comment]
Tenho interesse nessa vaga, vou te enviar meu CV
