### ISSUE TITLE
[Jaguariúna, logo em Campinas] Tech Lead na AB-Inbev (Ambev)

### ISSUE THREAD

**Issue by xandebianchi** [frontendbr/vagas#2987]
# **Informações gerais da empresa**

### **A maior cervejaria do mundo** abriu no final de 2018 seu setor de _tecnologia_, o time chamado: _Beertech_.
Uma novidade, pois antes os aplicativos eram feitos por terceiros.

E agora está acontecendo a **Transformação Digital** da empresa, onde se constrói um aplicativo B2B para vendas dos seus produtos (cerveja, não alcoólicos, etc.), e ele funciona em todos os países que a empresa trabalha, pelo mundo todo. 

A **Anheuser-Busch InBev** (abreviada **AB InBev**), **líder no mercado mundial**, é uma empresa multinacional de bebidas e cervejas formada em 2004 pela fusão da belga **Interbrew** e da brasileira **Ambev**. Está sediada em Leuven, na Bélgica, e possui escritório em Nova York, e sedes em Jaguariúna-SP, Londres, Cidade do México, Johanesburgo, St. Louis, e outros locais. Conta com mais de duzentas marcas de bebidas, entre as quais se destacam Brahma, Skol, Antarctica, Budweiser, Corona, Stella Artois, Beck's, Leffe, Hoegaarden na Europa. 

### - A sede da vaga atualmente é em Jaguariúna-SP-Brasil. Em um futuro próximo, estaremos em Campinas-SP.

 **Porém,** há outros locais que estão sendo incluídos como possibilidade de se trabalhar, como sul, etc, e será possível transições de local. 

# **Sobre o time**

Estamos repensando a maneira como a AB InBev faz negócios com seus clientes de varejo e criando experiências digitais para atendê-los. Você ingressará em uma nova organização digital da AB InBev que consiste em estratégia digital, produto, design, análise, operações e engenharia. Essa organização é responsável por criar os produtos e plataformas que transformam nossas operações de vendas tradicionais em todo o mundo.

# **About the Job**

We are looking for a lead/architect engineer with direct responsibility for implementing/building/maintaining an eCommerce platform while working in conjunction with the Head of Engineering, Product leads, UX, outsourced engineering team and assist in hiring a local tech team to develop/maintain the new platform. This role will be centered on working with all the different groups for the design, build, and potentially the integration of the ecommerce platform from design, scoping, development and maintenance of eCommerce site.

Tech Leads should follow a “T shaped” profile. Have a broad understanding of E2E/Full-Stack web development along with deep expertise with at least one (or more) capabilities below.

# **Capabilities**

- Front-end web dev (React, Angular, Vue)
- Microservices dev (RESTful/JSON, Spring Boot Java)
- Microservices dev (RESTful/JSON, Spring Boot Java)
- Magento front-end template and theme development. Multi-zone, multi brand deployments.
- FE Frameworks (e.g. React, Angular, Vue, Spring Boot)
- Scrum and Agile
- API/Microservices Driven development
- Test Automation;
- Know the difference between SaaS, PaaS, IaaS
- iOS and Android native app development
- Database care and feeding (%SQL%, Mongo etc.)
- NativeApp development

# **Sobre nós**

No Brasil possuímos uma unidade com mais de 200 fanáticos por cerveja, e também nossa célula de tecnologia, chamada BeerTech que é focada em prover serviços e soluções em escala global para todas as cervejarias do grupo.

# **Tipo de Contratação**

CLT

# **Como se aplicar**

Mande seu CV para o e-mail abaixo com o título "Vaga Tech Lead X":
alexandre.bianchi@ab-inbev.com 

**- Link de diversidade e inclusão:**
[Link de diversidade e inclusão](https://www.ab-inbev.com/careers/why-ab-inbev/diversity-and-inclusion.html)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by xandebianchi** [comment]
Válida ainda

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
