### ISSUE TITLE
[São Paulo/SP - Remoto] WordPress Front-end Developer na Source 2IT

### ISSUE THREAD

**Issue by pamelapsi** [frontendbr/vagas#2988]
**Descrição da vaga**
Desenvolvimento de novas funcionalidades em WordPress

**Local**
Remoto, a cada 15 dias visita no cliente para alinhamento.

**Benefícios**
Não há - modalidade PJ

**Diferenciais**
Home Office

**Requisitos obrigatórios:**

3 anos de experiência com WordPress

**Contratação**
PJ 
**Nossa empresa**
Somos uma Consultoria em Atração e Seleção de profissionais de TI.
Nosso cliente é uma unicórnio no segmento de Investimentos

**Como se candidatar**
Por favor envie um email para pamela.miranda@source2it.com.br

**Tempo médio de feedbacks**
Costumamos enviar feedbacks em até 1 dia após cada processo. E-mail para contato em caso de 

**Nível**
Sênior

**Comment by edsonvieirademetrio** [comment]
CV enviado!

**Comment by VMilanii** [comment]
Bom dia Edson, gostaria de saber como participar do processo seletivo,

grato.
Victor

________________________________
De: Edson Vieira Demetrio <notifications@github.com>
Enviado: segunda-feira, 2 de março de 2020 11:23
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [São Paulo/SP - Remoto] WordPress Front-end Developer na Source 2IT (#2988)


CV enviado!

**Comment by felipefialho** [comment]
@pamelapsi A vaga ta completamente fora dos padrões, por favor siga o [template](https://github.com/frontendbr/vagas/blob/master/.github/ISSUE_TEMPLATE/adicionar-nova-vaga.md).

**Comment by pamelapsi** [comment]
@felipefialho corrigido. Obrigada ;)

**Comment by pamelapsi** [comment]
@VMilanii encaminhar o seu currículo: pamela.miranda@source2it.com.br
Muito obrigada :)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
