### ISSUE TITLE
[Uberlândia/MG] Front-end Engineer na Ilink

### ISSUE THREAD

**Issue by uhtred** [frontendbr/vagas#2989]
## Descrição da vaga

Trabalhar com time de engenheiros de software no desenvolvimento de um produto de nível internacional para empresas de grande porte, com muitos desafios arquiteturais, funcionais e de usabilidade.

## Local

Escritório, Uberlândia

## Requisitos

**Obrigatórios:**
- 4 anos de experiência com Javascript
- 2 anos de experiência com React

## Nosso Stack
React, Apollo, Nodejs

## Contratação

PJ a combinar

## Nossa empresa

Aqui na [Ilink](https://www.ilinksolutions.com.br/) vivemos a diversidade. Portanto, não nos importamos se o seu cabelo é verde ou amarelo ou qual é o seu penteado preferido. Prezamos pela forma que faça você se sentir bem, em casa.

O que priorizamos de verdade é a sua capacidade intelectual e, acima de tudo, seu engajamento com o grande propósito que nos move. 

Respiramos o propósito e sabemos a importância de cada um nessa jornada.

Se você é fora da curva, mente aberta, colaborativo e gosta de grandes desafios, essa vaga é para você. Você fará parte de uma equipe responsável pela criação de um produto inovador e inspirador!

## Como se candidatar

Por favor envie um email para daniel.franca@cvortex.io com seu CV(Pode ser linkedin :) ) anexado - enviar no assunto: "Vaga Front-end"

#### Regime
- CLT
- PJ

#### Nível
- Sênior
- Especialista

**Comment by gregorispielmann** [comment]
Somente alocado ou possibilidade de full remoto?

**Comment by uhtred** [comment]
> Somente alocado ou possibilidade de full remoto?

Somente alocado, mas obrigado pelo interesse!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
