### ISSUE TITLE
Fullstack C# .NET Developer

### ISSUE THREAD

**Issue by raloliver** [frontendbr/vagas#299]
O programador vai trabalhar numa plataforma web com clientes em todo o Brasil.
Não vai virar noites trabalhando, nem ficar fazendo banco de horas!
O ambiente é bacana, somos "a família do amor", mas nosso trabalho é nosso trabalho, não nossa casa.

## Informações essenciais

- Analisar, construir e otimizar interfaces web, desktop e mobile _(do início ao fim, front e back end)_
- Desenvolvimento e manutenção de funcionalidades voltadas ao EAD _(integrações com os principais meios de pagamento)_
- Desenvolvimento de funcionalidades voltadas ao marketing digital _(auto-responder, redes sociais e notificações push)_
- Dar manutenção em integrações com os principais meios de pagamento, redes sociais e ferramentas de marketing _(Adwords, FacebookAds)_

## Local

> Nossa empresa fica em Curitiba - PR no Parque De Software

## Benefícios

- Horário flexível ( 8 horas entre as 08:00 e 20:00 )
- As melhores máquinas sempre são dos devs
- Frigobar sempre cheio :P
- Estar rodeado de pessoas que pensam da mesma maneira
- Oportunidade de crescimento num ambiente em constante mudança

## Requisitos técnicos necessários

**Obrigatórios (Soft Skills):** _O que faz as pessoas felizes?_
1. Gostar do que faz
2. Colaboração
3. Transparência
4. Compartilhamento
5. A Comunicação Deve Funcionar
6. Respeito Mútuo (relacionamento)
7. Confiança no Time
8. Objetivo Compartilhado
9. Filosofia Startup (erre rápido e erre barato)
10. "Be the water my friend"

**Nível de conhecimento de 1 a 5 (Hard Skills)** _Vamos falar de código!_
- Visual Studio 2015/2017 (5)
- C#  (4)
- Banco de dados relacional (SQL Server) (4)
- Experiência com Integrações (Facebook, Pagseguro, Paypal e MoIP entre outras API RESTFul) (4)
- VB (3)
- Experiência com Controle de Versão (TFS, Visual Studio Online) (3)

**Diferenciais:**
- Javascript / JQuery / AngularJS 1.x
- Conhecimento em dotNet Core, Azure, Docker
- Conhecimento em Xamarim
- Ferramentas do Microsoft Azure
- Domínio em arquitetura de APIs RESTFul
- Estudar e aplicar novas integrações relevantes ao negócio, como auto responder de e-mail, integrações com Messenger do Facebook e outras APIs. _(Criamos Máquinas de Relacionamento, independente do meio de comunicação)_. 

**Diferenciais Extra:** _Você assistiu pelo menos um desses filmes?_
- [x] Matrix (1999)
- [x] Clube da Luta (1999)
- [x] Prenda-me Se For Capaz (2002)
- [x] O Poderoso Chefão (1972)
- [x] Jerry Maguire (1996)
- [x] Os Suspeitos (1996)
- [x] Batman - O Cavaleiro das Trevas (2008)

## Contratação

CLT (Pleno)

## Nossa empresa

Depois de aprender muito em várias startups e sem reter clientes ou mesmo gerar leads, decidimos aprender a vender de verdade. O Marketing Digital abriu caminho para conexões incríveis, e escalar nosso negócio em direção ao sucesso ficou mais claro. No decorrer do caminho, descobrimos o que deveríamos fazer, não apenas pensando em números, mas em ajudar muitas pessoas a vender mais, com amor. 

**Nossa Missão** 
Facilitar e automatizar os processos de quem busca empreender de forma digital, através de plataformas que contém serviços integrados em constante inovação.

**Nossos Valores**
- Amor
- Comunicação
- Honestidade
- Liberdade
- Integração
- Inovação

**Não Toleramos**
- Procrastinação
- Falta de comprometimento
- Mentira
- Desrespeito
- Negligência
- Mi Mi Mi

## Como se candidatar

_(Se quiser ser direto, manda email para rh@leadlovers.com com as respostas abaixo)_

1. Como você gosta de trabalhar?
2. Como você imagina um ambiente ideal de trabalho?
3. O que você está estudando?
4. Vai a eventos? Qual foi o último que foi?
5. Escreve? Tem blog? Vídeos? Produz conteúdo de forma independente?
6. Sabe o que é conversão (ROI)? Entende de Teste A/B? Já capturou algum lead hoje?
7. Diga o que acha deste vídeo: https://vimeo.com/183691821

**Comment by Mendrone** [comment]
Faaala @raloliver tudo bem? 

Cara, se importa se eu tirar esse anúncio de vaga do ar? Te explico porque: 

Temos feito um trabalho aqui de ajudar o pessoal de front a encontrar vagas legais. A ideia é ter vagas focadas nesse mercado pra manter o repositório sempre organizado e manter o interesse do pessoal em publicar vagas. 

Se você tiver vagas para frontend ai na sua empresa o espaço é todo seu pra divulgá-las por aqui. Sei que existe um espaço de vagas para backend (não me lembro o repo, infelizmente)

Sei que removendo a vaga pode parecer que estamos tentando segregar ou algo do tipo, porém é importante pra nós manter o foco nesse mercado, um esforço a mais pra manter a comunidade mais ativa. 

Valeu e boa sorte ai na busca pelo Csharpeiro ideal!
