### ISSUE TITLE
[Rio de Janeiro] [Alocado] Front-end Developer Jr na Metatron

### ISSUE THREAD

**Issue by danielgmota** [frontendbr/vagas#2990]
## Descrição da vaga

Ótima oportunidade para quem está começando, irá se integrar na equipe com outros desenvolvedores plenos/seniors.

## Local

Escritório, Centro RJ

## Benefícios

- Salário atrativo
- Plano de saúde
- VR
- VT

#### Diferenciais

- Ambiente de trabalho cooperativo e descontraído;
- Home Office 1x/semana
- Horário Flexível
- DayOff no aniversário
- No code Dress

## Requisitos

**Obrigatórios:**
- Boa comunicação
- Facilidade de trabalhar em equipe
- Superior completo ou cursando na área de TI
- HTML
- CSS
- JavaScript

**Desejáveis:**
- jQuery
- JS ES6+
- Boostrap
- GIT
- CSS SASS

## Nossa empresa

Oportunidade de trabalhar em um time de pessoas dedicadas e que amam o que fazem. Empresa consolidada no mercado desde 1998

## Como se candidatar

Por favor envie um email para daniel.mota@metatron.com.br com seu CV anexado - enviar no assunto: Vaga FrontEnd

## Labels
[Rio de Janeiro] [CLT] [Júnior] [Alocado]

#### Alocação
- Alocado

#### Regime
- CLT
- Estágio

#### Nível
- Júnior
- Estágio

**Comment by carlos-a-marc** [comment]
Enviado 👍

**Comment by danielgmota** [comment]
> Enviado 👍

Infelizmente eles só estão aceitando Alocado no escritório
O Home office é de no máximo 1 vez por semana

**Comment by thiagoperesbr** [comment]
Enviado!

**Comment by souzalarissa383** [comment]
Ainda estão contratando ???

**Comment by danielgmota** [comment]
Recebimento dos CV encerrados. Os CV selecionados estão sendo chamados para o processo seletivo.
