### ISSUE TITLE
[Remoto] Front-end Developer na Dialog

### ISSUE THREAD

**Issue by rod-stuchi** [frontendbr/vagas#2991]
## Descrição da vaga

Procuramos desenvolvedor(a) de front-end com experiência em React (e ecossistema) e UX, que goste de performance e de entregar uma ótima experiência ao usuário. O(a) candidato(a) irá trabalhar ao lado de um time senior de desenvolvedores do Dialog.

## Nossa empresa

O Dialog (www.dialog.ci) é uma startup de rede social corporativa gamificada para grandes empresas.
Há 4 anos no mercado, oferecemos uma plataforma SaaS que melhora a comunicação entre grandes empresas e seus colaboradores.
Somos a startup brasileira líder no segmento, reconhecida como Top 100 no ranking 100 Open Startups, e atendendo clientes como Carrefour, PepsiCo, BRF, SBT, Klabin e Via Varejo.

## Local

Presencial ou Remoto

## Benefícios

- A combinar

## Requisitos

**Obrigatórios:**

- React: 3 anos de experiência
- ECMAScript 2019
- PWA (service workers, cache)
- styled-components
- Apollo Client
- Git
- Figma

**Desejáveis:**
- conhecimentos em Node

## Modelo de Contratação

PJ (emissão NF)

## Como se candidatar

Enviar pull-request de um pequeno teste no repositório:

    https://github.com/criticalmassbr/cm-pwa-test

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após o envio do pull-request.

## Labels

- PJ
- Pleno
- 5k-8K
- Senior
- 8k-13k
- Remoto

**Comment by gregorispielmann** [comment]
Rodrigo, é necessário criar e enviar junto o projeto UI/UX do desafio no Figma?

**Comment by rod-stuchi** [comment]
@gregorispielmann não é necessário, mas é um bom diferencial.

**Comment by gregorispielmann** [comment]
@rod-stuchi enviado!

**Comment by YuriBrunetto** [comment]
enviado!!

**Comment by LucasMallmann** [comment]
@rod-stuchi enviado!!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by rod-stuchi** [comment]
@felipefialho opa, a vaga ainda está aberta, nas próximas semanas estaremos avaliando os pull requests.
