### ISSUE TITLE
[Brasília] Especialista Domain Driven Design - DDD na Coopersystem

### ISSUE THREAD

**Issue by vagasCoopersystem** [frontendbr/vagas#2992]
`[Brasilia] Especialista Domain Driven Design na Coopersystem`
==================================================
-->

## Descrição da vaga

Projeto PCB em Banco do Brasil 

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$32/dia

## Requisitos

**Obrigatórios:**
--Experiência em modelagem de software utilizando DDD (Domain Driven Design) 
-- Experiência de modelagem para microsserviços
-- Experiência em Metodologias Ágeis.

## Contratação

Contrato através de Cooperativa 

## Nossa empresa

Somos a maior Cooperativa de TI do Brasil. Há mais de 20 anos tiramos do papel idéias inovadoras e transformamos em sistemas que automatizam a rotina das empresas.

## Como se candidatar

Por favor envie um email para vagas@coopersystem.com.br com seu CV anexado - enviar no assunto: Especialista DDD

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após a finalização de cada processo.

#### Alocação
- Alocado

#### Regime
- Cooperativa

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
