### ISSUE TITLE
[São Paulo] Front-end Developer na Smart Fit

### ISSUE THREAD

**Issue by CamilaQuerubin** [frontendbr/vagas#2993]
## Descrição da vaga

Atuar como desenvolvedor Front-End nas squads de inovação do Grupo Bioritmo (Smartfit) na Avenida Paulista, com o objetivo de melhorar a jornada dos clientes do grupo.

## Local

Presencial - Avenida Paulista - SP

#### Diferenciais

- horário flexível 
- possibilidade de home office

## Requisitos

**Obrigatórios:**

- Git
- Bootstrap
- JavaScript
- CSS3
- HTML 5
- React

**Desejáveis:**

- Node.js
- SQL/NoSQL
- Conhecimento em json
- Conhecimento em design responsivo, bootstrap.
- Testes Unitários.
- Documentação.
- Scrum e Kanban

## Contratação

PJ (emissão NF)

## Empresa 

Somos uma empresa de inovação que atendem grandes clientes como a Smart Fit. 
ACE CORTEX (Corporate to Exponential): Com projetos de inovação corporativa, alavancamos, junto à liderança e aos colaboradores, grandes corporações ao futuro de seus novos mercados. Atendemos grandes empresas, como: BTG Pactual, EDP, BASF, Natura, Google e muitos outros.

Como empresa de investimentos em startups, entrega aos melhores empreendedores uma plataforma com capital, expertise e networking de alto nível. Já foram mais de 300 startups aceleradas, mais de 80 investidas e mais 150 mentores qualificados.

## Como se candidatar

Por favor envie um email para camila@goace.vc CV anexado - enviar no assunto: Vaga Front End

## Labels

- PJ
- Pleno 
- Senior
- Presencial

#### Alocação
- Alocado

#### Nível

- Junior
- Pleno
- Sênior

**Comment by Jhowslip** [comment]
Aplicado!

**Comment by carloshenrique-dev** [comment]
Cv enviado!

**Comment by Reginaldo1239** [comment]
ainda tem vaga ?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
