### ISSUE TITLE
[São Paulo] Front-end Developer na Verx Tecnologia e Inovação

### ISSUE THREAD

**Issue by VanMartinez** [frontendbr/vagas#2994]
## Descrição da vaga
- Ter familiaridade com camada de front-end do Drupal 8;
- Ter familiaridade com o funcionamento de lógica de template (Twig, Mustache, Handlebars ou similares);
- Conhecer o funcionamento e saber configurar task runners como Gulp ou bundlers como Webpack;
- Desenvolver temas na plataforma Drupal se baseando nos layouts desenhados por nossos designers ou conseguindo 
 integrar páginas front-end estáticas.
- Implementar layouts responsivos, aplicando os princípios de Mobile First quando necessário;
- Criar códigos semânticos, levando em consideração os princípios de SEO e principalmente de Acessibilidade;
- Saber trabalhar com GIT, utilizando Pull Requests;
- Conhecimento avançado em JavaScript (especialmente manipulação da DOM, objetos e arrays);
- Saber realizar integração com APIs REST via JS;
- Produzir sites que sejam performáticos, priorizando carregamento e utilizando os princípios de performance de código;
- Escrever código semântico e preparado para acessibilidade.

## Local
 São Paulo - Sacomã

## Contratação
PJ a combinar

## Projeto
Projeto de 6 meses com grandes chances de renovação ou contratação pelo cliente

## Como se candidatar

Por favor envie um email para vanessa.martinez@verx.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.
E-mail para contato em caso de não haver resposta: vanessa.martinez@verx.com.br

#### Alocação
- Alocado

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
