### ISSUE TITLE
[Florianópolis] Front-End Developer na Compasso

### ISSUE THREAD

**Issue by cleiton-goncalves** [frontendbr/vagas#2995]
## Descrição da vaga

A Compasso está procurando pessoas talentosas, inovadoras, comprometidas, inteligentes e que queiram ajudar a fazer a transformação digital acontecer em nossos clientes.

Queremos conhecer você, que está em busca de carreira desafiadora e oportunidades de crescimento profissional.  

## Local

Santa Mônica - Florianópolis - SC

## Benefícios

Além dos benefícios contratuais da Compasso, nossos colaboradores contam com trilhas de capacitação para aprendizado de novas tecnologias e métodos, além de subsídios de até 100% para a realização de certificações.

## Requisitos

**Obrigatórios:**
- Sólidos conhecimentos em Javascript e HTML/CSS.
- Conhecimento em UX/UI

**Desejáveis:**
-  Experiência com métodos ágeis;
-  Angular;
-  React;
-  Testes unitários;
-  SASS;
-  JQuery;
-  Prototipação de interfaces.

## Contratação
CLT

## Nossa empresa

Nossa missão é transformar o mundo, construindo soluções que permitem que empresas de diversos tamanhos e segmentos ingressem na era digital.

Fazemos isso, contando com um time talentoso, aplicando tecnologias em estado-da-arte e modelo ágil.

Queremos conhecer você, que busca desafios, conhecimento e crescimento profissional!

## Como se candidatar

https://compasso.gupy.io/jobs/126062?jobBoardSource=gupy_public_page

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
