### ISSUE TITLE
[Florianópolis] Front-end Developer FastTrack na Compasso

### ISSUE THREAD

**Issue by cleiton-goncalves** [frontendbr/vagas#2996]
## Descrição da vaga

Está aberta a nova edição do Compasso Fast Track em Florianópolis e queremos conhecer você, que tem sede de aprender e é apaixonado por tecnologia!

O **FastTrack** é o programa da Compasso, que conta com uma formação especializada para capacitar novos profissionais nas tecnologias que trabalhamos. O programa é estruturado no modelo multidisciplinar:
- Trilhas de aprendizagem com foco em Front-End: React, Angular, Vue e Javascript;
- Vivência em projetos e desafios reais;
- Orientação com os especialistas da Compasso.

## Local

Santa Mônica - Florianópolis - SC

## Benefícios

Além dos benefícios contratuais da Compasso, nossos colaboradores contam com trilhas de capacitação para aprendizado de novas tecnologias e métodos, além de subsídios de até 100% para a realização de certificações.

## Requisitos

**Obrigatórios:**
-  Graduação concluída ou em andamento em Engenharia da Computação, Ciências da Computação, Análise e Desenvolvimento de Sistemas ou correlatas;
-  Conhecimento de lógica e linguagens de desenvolvimento de software;
-  Ser curioso e buscar conhecimento.

**Desejáveis:**
-   Alta capacidade de aprendizado;
-   Conhecimento em inglês.

## Contratação

CLT

## Nossa empresa

Nossa missão é transformar o mundo, construindo soluções que permitem que empresas de diversos tamanhos e segmentos ingressem na era digital.

Fazemos isso, contando com um time talentoso, aplicando tecnologias em estado-da-arte e modelo ágil.

Queremos conhecer você, que busca desafios, conhecimento e crescimento profissional!

## Como se candidatar

https://compasso.gupy.io/jobs/94406

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by fogeid** [comment]
Nossa, queria que essa vaga fosse em Cuiabá kkkk.

**Comment by cleiton-goncalves** [comment]
Olá @fogeid, infelizmente ainda não temos sede em Cuiabá, mas se estiver interessado em vir pra Florianópolis, podemos conversar. Mas se não for de teu gosto, estamos com diversas vagas abertas em vários estados, confere la no https://compasso.gupy.io/

**Comment by jgalmeida93** [comment]
Eu interesso, mas sou do interior do PR. Como faríamos se eu me interessar em mudar para Florianópolis?

**Comment by cleiton-goncalves** [comment]
Olá @jgalmeida93, se inscreva para a vaga no https://compasso.gupy.io/jobs/94406, que entraremos em contato para conversarmos.

**Comment by JulianaAugusta** [comment]
Gostei da vaga e gostaria de mais informações, vou me inscrever.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
