### ISSUE TITLE
[Lisboa] Front-end Developer na Aubay

### ISSUE THREAD

**Issue by festaca** [frontendbr/vagas#2997]
A nossa empresa:
A Aubay, é uma empresa de origem francesa presente em diversos países na Europa.
Como cerca de 6500 pessoas, desenvolvemos projectos nas mais diversas tecnologias.
Neste momento, temos várias vagas em aberto para várias posições.

Descrição da vaga:
Projecto internacional para trabalhar em Portugal, em vários sectores de actividade utilizando as últimas tecnologias do mercado.

Local:
Portugal: Lisboa ou Porto

Benefícios:
• Visto de trabalho/autorização de residência
• Apoio jurídico e legal durante todo o processo
• Contrato de trabalho
• Passagem do avião
• Ajuda em alojamento
• Projetos inovadores nacionais e internacionais
• Oportunidades de formação todas as semanas
• Café e lanche grátis
• Entre outros
• Formações técnicas e comportamentais
• Prémios de referências de recrutamento
• Eventos team Building
• Convívios mensais
• Oferta de aniversário
• Projetos dinâmicos

Requisitos Obrigatórios:
• Experiência mínima de 3 anos como frontend engineer
• Experiência com as frameworks: React e Redux ou Angular 2+
• Experiência em desenvolvimento Javascript
• Nível de Inglês Avançado (obrigatório)

Diferenciais:
• Conhecimentos em NodeJS
• Experiência profissional com cloud pública
• Experiência internacional

Como se candidatar?
Por favor envie para fpiedade@aubay.com com seu CV em inglês anexado colocando no assunto
Candidato_Internacional_Frontend

Labels:
- Alocado
- CLT ou PJ
- Nível Sénior ou Especialista

**Comment by gregorispielmann** [comment]
Bom dia Filipe, posso enviar um email com algumas perguntas a respeito da vaga?

**Comment by festaca** [comment]
Claro, no que eu poder auxiliar e responder nesta fase do processo.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
