### ISSUE TITLE
[São Paulo] Software Engineer na Liv Up

### ISSUE THREAD

**Issue by joanacesco** [frontendbr/vagas#2999]
## Descrição da vaga

Usamos o termo "Engenharia" de forma deliberada, pois temos um time de criadores: criadores de soluções tecnológicas de qualidade que entregam valor em toda a cadeia; criadores que entendem dos problemas e elaboram soluções; criadores que são mais do que desenvolvedores de sistemas.

- Criar e desenvolver soluções escaláveis, sustentáveis e orientadas ao negócio da Liv Up.
- Construir serviços, aplicativos e APIs fáceis de entender com soluções baseadas em React Native e React.
- Tomar boas decisões de Engenharia de Software com autonomia, considerando variáveis técnicas e não-técnicas.
- Questionar por que as coisas são feitas do jeito que são e fazer parte da construção de um time de alta perfomance e muita colaboração multidisciplinar.

## Local

Pinheiros - São Paulo/SP

## Benefícios

- Vale refeição ou alimentação
-Plano odontológico e saúde
-Seguro de vida
-Vale transporte
-Gympass

#### Diferenciais

-40% de desconto nos produtos Liv Up, mais um valor bônus para gastar mensalmente em nosso escritório
- Ambiente divertido, informal e acelerado
-Happy hour mensal

## Requisitos

**Obrigatórios:**
- Alguém com experiência em desenvolvimento de software.
- Alguém com vontade de encontrar soluções para os problemas que encontramos do campo até a mesa do cliente.
- Experiência com tecnologias modernas e metodologias ágeis.

## Contratação
CLT

## Nossa empresa
A Liv Up é a startup que está construindo a alimentação do nosso tempo com o apoio da Kaszek Ventures, da Endeavor Catalyst, Spectra Investments e Thorn Tree Capital Partners. Somos digitais, temos controle total da cadeia produtiva, desde formar parcerias com produtores orgânicos, criar e desenvolver receitas até o desenvolvimento do nosso site e aplicativo. Tudo isso com o compromisso de gerar impacto positivo do campo ao consumidor final.

Já somos mais de 450 livupers, estamos em mais de 30 cidades no Brasil e crescendo a cada dia. Por isso, estamos em busca de talentos. Acreditamos na igualdade de oportunidades, e o único ingrediente que não pode faltar é o alinhamento com nossos valores. Bora?

## Como se candidatar
https://apply.workable.com/livup/j/E04537DEBB/

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 5 dias após cada processo.

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
