### ISSUE TITLE
Adicionar os estados e principais cidades nas milestones e as skills nos labels

### ISSUE THREAD

**Issue by lazarofl** [frontendbr/vagas#3]

**Comment by eduardojmatos** [comment]
@lazarofl vi sua sugestão no /forum. Eu acho que usar milestones pra separar por cidade desvirtua um pouco o propósito deles. Mas... Como a gente é dev, e gosta de uma gambiarra de vez em quando - hehehehe - acredito que seja uma forma legal de visualizar issues/vagas por estados/cidades.

Convoco os amigos do @frontendbr/admins pra decidirmos isso juntos.

+1 pra usar issues como vagas e milestones pra locais

**Comment by vitorbritto** [comment]
IMHO, não devemos impor muitos passos para definir as vagas aqui. Tem que ser prático para quem anuncia e para quem vai gerir.

As labels podem ser por níveis de experiência(estágio, junior, pleno, senior) e tipo de contrato(remoto, clt, freela...) apenas. Milestones acho desnecessário. O que for relevante para o candidato, vai no template descritivo da vaga. Uma vez que a vaga for preenchida, a issue é fechada.

**Comment by lazarofl** [comment]
Vocês tem razão, keep it simple stupid hehehe.
Vou atualizar o pull request incluindo o que foi discutido e os ajustes mencionados e subo pra uma nova avaliação, show de bola.

**Comment by vitorbritto** [comment]
Boa! :ghost:

**Comment by LFeh** [comment]
O que acham de colocar as cidades no titulo da vaga?

[São Paulo] Desenvolvedor FrontEnd

**Comment by luisfmsouza** [comment]
+1 Pra sugestão do @LFeh

**Comment by andersonweb** [comment]
+1 @LFeh

**Comment by andrevvalle** [comment]
+1 @LFeh

**Comment by lazarofl** [comment]
+1 @LFeh, facilita bastante na listagem

**Comment by fdaciuk** [comment]
+1

**Comment by Mendrone** [comment]
+1 @LFeh

**Comment by diogomoretti** [comment]
Putz, muito bom @LFeh +1

**Comment by LFeh** [comment]
Vou colocar no Readme \o

**Comment by lazarofl** [comment]
pessoal, com a questão das milestones e labels bem definidas acho que fechou a issue, assim já fica disponível pra galera ir cadastrando as issues como vagas aqui no repo
