### ISSUE TITLE
[São Paulo] Desenvolvedor Front-End - Scup

### ISSUE THREAD

**Issue by guisouza** [frontendbr/vagas#30]
## Descrição da vaga

Buscamos Desenvolvedor Web Sênior para atuar no desenvolvimento de novos projetos do Scup/Sprinklr. Procuramos pessoas apaixonadas por resolver problemas e também por tecnologia. Seu desafio será, junto ao seu time, melhorar as propostas atuais e construir novos projetos para o mundo todo. No nosso dia a dia lidamos com  SPA´s, muitos acessos e muito javascript. É esperado que as soluções envolvam as melhores técnicas e tecnologias com agilidade. 
## Local

São Paulo - Ao lado da estação CPTM Hebraica-Rebouças e próximo ao Metro Faria-Lima
Av. Das Nações Unidas, 8.501 - 24º andar - lado B
## Benefícios
- MacBook Pro 15' Retina
- Programa de Idiomas
- Programa de Desenvolvimento (cursos de curta duração)
- Programa de Coaching
- CLT (full, sem gambiarra)
- Stock Options
- Plano de saúde e odontológico
- Pacote de descontos
- Vale Refeição
- Vale Transporte
## Requisitos
- Conhecimento em arquitetura web;
- Gostar (muito) de aprender;
- Boa comunicação e gostar de trabalhar em equipe;
- Inglês avançado.
- Angular.js e/ou Node.js;
- JavaScript avançado (OO, Modules, Async);
- CSS3 (SMACSS, BEM ou OOCSS);
- HTML5;

Se você gosta de aprender vai ser fácil conhecer o resto, mas você terá vantagem se já tiver experiência com:
- Arquitetura para grandes aplicações;
- Wordpress.
- BDD / TDD.
- Mongodb.
- Mysql.
- Consumo de API's.
## Contratação

CLT (full, sem gambiarra)
## Nossa empresa

http://www.sprinklr.com
http://www.scup.com
## Como se candidatar

Envie um email para hiringbrazil+dev@sprinklr.com

**Comment by victormiguez** [comment]
Vaga fodona!
Gostei do "CLT (full, sem gambiarra)", huahah.

**Comment by LFeh** [comment]
A vaga foi preenchida?  @guisouza

**Comment by guisouza** [comment]
@LFeh manda o currículo, estamos sempre contratando ..

**Comment by LFeh** [comment]
haha, valeu @guisouza 

Deixo a issue aberta então?

**Comment by guisouza** [comment]
Deixa aí .. rs ...
