### ISSUE TITLE
[Campinas] Front-end Developer | UPX

### ISSUE THREAD

**Issue by victormiguez** [frontendbr/vagas#300]
## Descrição da vaga

Estamos buscando uma pessoa que nos auxiliará na construção do front-end das nossas aplicações para os próximos anos.
Sendo responsável por:

- Prototipar e desenvolver ferramentas de gerenciamento dos nossos serviços;
- Garantir a componentização de objetos de interface, criando e/ou evoluindo componentes e explicando como utilizá-los;
- Garantir alta performance do front-end;
- Garantir baixo acoplamento do Core da aplicação com frameworks JavaScript;
- Escrever código limpo, que funcione em todos os browsers;
- Escrever testes unitários;
- Seguir as recomendações dos guias de código e ajudar a aprimorá-los;
- Revisar o código dos colegas de trabalho (code review) e submeter seu próprio código para apreciação.
- Ajudar a definir processos de integração continua para desenvolvimento frontend;

Atuará em uma equipe com metodologia de trabalho ágil/lean com foco na melhoria continua.

## Local

**Alocado** no escritório da UPX

Av. Cambacicas, 520 • 3º andar • Torre 5

Campinas, SP

## Benefícios

- Happy-hour toda sexta-feira
- Puffs para descansar (não são apenas decoração)
- Retropie com games clássicos
- Tempo livre para estudos e experimentos
- Férias remuneradas

## Requisitos

**Obrigatórios:**

- Experiência desenvolvendo aplicações web utilizando HTML, CSS e JavaScript.
- Experiência com Single Page Applications;
- Experiência com mecanismos de autenticação e autorização (Ex: JWT e OAuth2).

**Desejáveis:**

- Experiência em escrita de testes unitários em JavaScript;
- Experiência com frameworks/bibliotecas de mercado, tais como React, Vue, EmberJS, Angular, etc.
- Conhecimento de controle de versão de código-fonte (Git);
- Experiência de trabalho em equipes de desenvolvimento ágil;
- Habilidade para trabalhar com independência, definindo prioridades e com supervisão mínima;
- Disposição em compartilhar o seu conhecimento com as pessoas da área de tecnologia da empresa;
- Boa habilidade de comunicação escrita e verbal;
- Disposição para aprender novas tecnologias e aplicá-las em um curto espaço de tempo;
- Espírito de equipe;

**Diferenciais:**

- Contribuições para software livre e atuação em comunidades de desenvolvedores;
- Familiaridade com as tecnologias do lado do servidor Web (PHP) e conceitos de orientação a objetos;
- Familiaridade com integração continua;
- Familiaridade com Docker;
- Familiaridade com micro-serviços;

## Contratação

PJ a combinar

## Nossa empresa

A [UPX Technologies](http://www.upx.com.br/) é uma empresa de tecnologia focada em soluções para infra-estrutura de internet.
Nossos serviços visam o mercado B2B e estamos passando por um momento de grande evolução tecnologica, por isso buscamos bons profissionais para integrar nosso time.

## Como se candidatar

Envie um email para thiago.rodrigues+frontendbr@upx.com.br com assunto *Vaga Frontend* com links para seu Linkedin e GitHub no corpo da mensagem.

**Comment by LFeh** [comment]
Quais as labels?

**Comment by victormiguez** [comment]
@LFeh, Alocado, PJ, Junior, Pleno e Senior.

Apesar dos requisitos, estamos procurando principalmente pessoas interessadas em aprender :)

**Comment by leonantvrs** [comment]
@victormiguez não cumpro todos os requisitos, mas estou disposto a aprender com vocês remotamente, aceita? ;)

**Comment by xthiago** [comment]
@leonantvrs infelizmente não, pois a vaga é para trabalhar presencialmente com nossa equipe.

**Comment by brunooomelo** [comment]
@xthiago Enviado!

**Comment by rockpraxedes** [comment]
Opa

**Comment by lucasaugustofrontend** [comment]
@xthiago enviado

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by xthiago** [comment]
@LFeh pode fechar, por favor. Obrigado :)

**Comment by danilosilvadev** [comment]
faz entrevista via Skype?

**Comment by xthiago** [comment]
@danilosilvadev quando o profissional é de outra cidade fazemos a primeira entrevista por Skype para evitar despesas de locomoção do candidato. Se depois dela houver interesse de ambas as partes, fazemos a presencial.

**Comment by xthiago** [comment]
Poderiam fechar essa issue? Abrimos uma nova em #1232.
