### ISSUE TITLE
[Belo Horizonte] Front-end Developer na mLearn

### ISSUE THREAD

**Issue by gustavoborboleta** [frontendbr/vagas#3000]
## Descrição da vaga

Procuramos por um Front-End Developer jr. que seja apaixonado por JavaScript, tecnologias móveis e, claro, tenha vontade de fazer parte de algo grandioso.

Programar em JavaScript utilizando boas práticas de desenvolvimento.
Aprimoramento de usabilidade e performance das interfaces de nossos produtos.

## Local

Funcionários, Belo Horizonte - MG

## Benefícios

- Plano de saúde e odontológico
- VR ou VA
- VT ou VC

#### Diferenciais

- Incentivo para palestrar e participar de eventos.
- Flexibilidade para trabalho remoto.

## Requisitos

**Obrigatórios:**
- Domínio em HTML & CSS (SASS).
- Bom conhecimento em JavaScript.

**Desejáveis:**
- Experiência com AngularJS.
- Experiência com desenvolvimento mobile em Ionic / Cordova.
- Bom entendimento sobre consumo de APIs.
- Conhecimento de Git.
- Inglês técnico. (Leitura e escrita).

**Diferenciais:**
- Experiência com Gulp
- Conhecimento em VueJS
- projetos open source

## Contratação

CLT ou PJ

## Nossa empresa

Somos uma startup criada em 2013, focada em aprendizagem móvel.
Nós desenvolvemos aplicativos educacionais e de treinamento corporativo para smartphones, tablets e desktop, utilizando gamificação e ferramentas de aprendizagem social.

## Como se candidatar

Por favor envie um email para recrutamento@mlearn.com.br com seu CV anexado - enviar no assunto: Front-End Developer jr

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Júnior

**Comment by jgalmeida93** [comment]
Enviado!

**Comment by lzhudson** [comment]
Remoto somente parcial ou full ?

**Comment by gustavoborboleta** [comment]
> Remoto somente parcial ou full ?

Ambos.

**Comment by MarcoMonteiro94** [comment]
Enviado :)

**Comment by lzhudson** [comment]
Enviado.

**Comment by guilhermecostalopes** [comment]
Enviado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
