### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor - Risco na UPNID

### ISSUE THREAD

**Issue by upnidrecruta** [frontendbr/vagas#3001]
**NOSSO DNA**

Somos uma startup em crescimento acelerado, então você terá a oportunidade de aprender muito e crescer com o time. O ambiente é descontraído, mas somos muito responsáveis com nosso trabalho e comprometidos com a entrega - **não fazemos trabalho meia boca**.

Temos fome! Estamos em constante evolução, buscando sempre a melhor solução para os desafios que encontramos, o que significa que nem sempre temos todas as respostas. Por isso, capacidade de adaptação, ser um entusiasta de novas tecnologias e ter disponibilidade para aprender são características muito importantes para fazer parte desse squad. Moramos fora da zona de conforto, **não sabemos tudo, mas aprendemos rápido.**

**TECNOLOGIAS - O QUE VOCÊ PRECISA SABER?**

Seus desafios envolvem o desenvolvimento de projetos tecnológicos para a área de risco, como:

Automação de ações de bloqueio, liberação de saque e antecipação de recebíveis
Desenvolvimento de indicadores de transações suspeitas ou movimentação atípicas nas contas
Desenvolver integrações de ferramentas via API
Desenvolver um anti-fraude (in-house)
Desenvolver microserviços de risco na API (reserva de segurança..)
Automações de processos de checagem de disputa
Para isso, é bacana ter um conhecimento prévio em:

Banco de dados relacionais, como MySQL ou PostgreSQL;
Conhecimento de gRPC;
Go (essa é a nossa linguagem para desenvolvimento de back-end e hoje representa 95% da nossa base).
Mas se você ainda não teve a oportunidade de utilizar essas tecnologias, tudo bem! A experiência em algumas outras linguagem podem fazer sentido para gente também, por exemplo:

- Ter mexido com uma linguagem compilada (mesmo não sendo Go), é um grande diferencial. Exemplos: Java, Erlang, Haskell, Rust, Swift, C, C++

Além disso, valorizar boas práticas de desenvolvimento é fundamental. Somos uma empresa de pagamentos e precisamos ser capazes de escalar o sistema de forma sustentável. Ainda pensando no nosso negócio, se você já trabalhou numa empresa que exija alta confiabilidade de sistemas, também é um ótimo sinal.

Para o momento que estamos, é importante encontrarmos uma pessoa que já entre jogando, por isso fica mais dificil se você estiver nos primeiros passos, procurando uma vaga de estagiário ou junior. Veja bem que não existe nenhum demérito nisso! Nós temos grande alegria em desenvolver nosso time, mas nesse momento, não seríamos capazes de fazer isso da forma como deve ser para quem está começando (lembra que não fazemos trabalho meia boca?), então estamos procurando gente que já tenha pelo menos uns 2-3 anos de experiência, ok?

Ah, se você já passou pelo mercado de meios de pagamento online (bancos, adquirentes, sub-adquirentes, gateways, e-commerces, marketplaces, etc), só vem! Vai ser um grande diferencial você conhecer do nosso mundo. :)

Um dia típico de um dev na Upnid inclui:

Alinhar com o time o andamento dos projetos
Planejamento das próximas etapas
Desenvolvimento dos projetos

**MAIS INFORMAÇÕES**
Em relação aos benefícios, temos Plano de Saúde, Refeição no Local e uma Cultura de Liberdade e Autonomia. Ah, e vale transporte, claro, mas esse não é benefício, é lei. :) Considerando isso, manda para gente a sua pretensão salarial quando se candidatar.

Se identificou? Clica no link pois aguardamos ansiosos a sua candidatura!

https://upnid.breezy.hr/p/049137215591-desenvolvedor-risco
#VemProNinho

**Comment by diogomoretti** [comment]
Favor colocar no nosso [template](https://github.com/frontendbr/vagas/blob/master/.github/ISSUE_TEMPLATE/adicionar-nova-vaga.md)
