### ISSUE TITLE
[REMOTO] Front-end Developer na UPNID

### ISSUE THREAD

**Issue by upnidrecruta** [frontendbr/vagas#3002]
**NOSSO DNA**

Somos uma startup em crescimento acelerado, então você terá a oportunidade de aprender muito e crescer com o time. O ambiente é descontraído, mas somos muito responsáveis com nosso trabalho e comprometidos com a entrega - não fazemos trabalho meia boca.

Temos fome! Estamos em constante evolução, buscando sempre a melhor solução para os desafios que encontramos, o que significa que nem sempre temos todas as respostas. Por isso, capacidade de adaptação, ser um entusiasta de novas tecnologias e ter disponibilidade para aprender são características muito importantes para fazer parte desse squad. Moramos fora da zona de conforto, não sabemos tudo, mas aprendemos rápido.

**TECNOLOGIAS - O QUE VOCÊ PRECISA SABER?**

Para compor o time de Front-End, é importante que trabalhe bem com React, Styled Component e GraphQL.

Além disso, valorizar boas práticas de desenvolvimento é fundamental. Somos uma empresa de pagamentos e precisamos ser capazes de escalar o sistema de forma sustentável. Ainda pensando no nosso negócio, se você já trabalhou numa empresa que exija alta confiabilidade de sistemas, também é um ótimo sinal.

Para o momento que estamos, é importante encontrarmos uma pessoa que já entre jogando, por isso fica mais dificil se você estiver nos primeiros passos, procurando uma vaga de estagiário ou junior. Veja bem que não existe nenhum demérito nisso! Nós temos grande alegria em desenvolver nosso time, mas nesse momento, não seríamos capazes de fazer isso da forma como deve ser para quem está começando (lembra que não fazemos trabalho meia boca?), então estamos procurando gente que já tenha pelo menos uns 2-3 anos de experiência, ok?

Ah, se você já passou pelo mercado de meios de pagamento online (bancos, adquirentes, sub-adquirentes, gateways, e-commerces, marketplaces, etc), só vem! Vai ser um grande diferencial você conhecer do nosso mundo. :)

**SOBRE A VAGA**

Nossos Devs trabalham remoto, então você pode se candidatar de qualquer lugar do Brasil! :)

Estamos considerando pretensão salarial e de benefícios, temos Plano de Saúde, Vale UpHouse (para você visitar o HQ) e uma Cultura Colaborativa, de Liberdade e Autonomia.

Se identificou? Então clica no link abaixo e cola no seu navegador pois aguardamos ansiosos a sua candidatura!

https://upnid.breezy.hr/p/99061a9c2471-desenvolvedor-front-end

**#VemProNinho**

**Comment by andreblb** [comment]
Boa noite.
A URL está quebrada.

Em qua, 4 de mar de 2020 às 17:52, upnidrecruta <notifications@github.com>
escreveu:

**Comment by upnidrecruta** [comment]
Boa noite! Alterei. Obrigada pelo aviso! Agora é só copiar o link e colar no navegador. 😊

**Comment by diogomoretti** [comment]
Favor colocar no nosso [template](https://github.com/frontendbr/vagas/blob/master/.github/ISSUE_TEMPLATE/adicionar-nova-vaga.md)
