### ISSUE TITLE
[São Paulo] Front-end Developer na L4U

### ISSUE THREAD

**Issue by matheuslugon** [frontendbr/vagas#3003]
## Descrição da vaga

Atuar exclusivamente no desenvolvimento de projetos web internos da empresa e manutenção de aplicações existentes.

## Local

Escritório, São Paulo - Vila Mariana

## Benefícios

- Horários flexíveis

#### Diferenciais

- Sala de jogos
- Snacks a vontade
- Ambiente descontraído

## Requisitos

**Obrigatórios:**
- +2 anos de experiência em desenvolvimento de sites, interfaces e aplicações web.
- Conhecimento e boas práticas de desenvolvimento: semântica, código limpo, padrões de projeto, entre outras
- Experiência em desenvolvimento voltado para Front-End
- Bons conhecimentos e experiência em JavaScript e integração com APIs
- Familiaridade com as práticas de Entrega Contínua (Continuous Delivery)
- Experiência com algum Framework de Javascript (Ex. VueJS, Angular)
- Experiência comprovada CSS e HTML

**Desejáveis:**
- JavaScript
- Node.js

**Diferenciais:**
- PHP (Frameworks como CakePHP e Laravel)

## Contratação

PJ a combinar

## Nossa empresa

A L4U é uma aceleradora de negócios digitais e há quatro anos nascemos com um objetivo: impulsionar resultados de empresas com performance e melhores tecnologias.

## Como se candidatar

Por favor, envie um email para matheus@l4u.com.br com seu CV anexado - enviar no assunto: Vaga Front-End Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: matheus@l4u.com.br

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Junior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
