### ISSUE TITLE
[Remoto] Front-end Developer @ Lukin Co.

### ISSUE THREAD

**Issue by diogomoretti** [frontendbr/vagas#3004]
<br>

A **[Lukin](https://lukin.co)** procura um(a) **Front-end Developer** para se juntar ao time. Queremos uma pessoa curiosa, criativa e com muita vontade de aprender (incentivamos tudo isso) 😍

## Requisitos

**Obrigatórios:**
- Escrever **HTML semântico e acessível**
- **Desenvolvimento de interfaces** utilizando HTML, CSS e técnicas de design responsivo
- Conhecimento de **styled-components**
- Conhecimento básico/intermedário no **Storybook**
- Entendimento básico de todo **processo web** (design, desenvolvimento e deploy)
- Capaz de construir stateless e statefull components utilizando **React**
- Sabe **consumir uma API** e formatar os dados recebidos

**Diferenciais:**
- Experiência com React Native
- Testes (TDD, integração, E2E)

**Valorizamos:**
- Projetos open-source
- Participação em eventos
- Contribuição com a comunidade de alguma forma

#### Contratação:

- Plano de saúde **Bradesco Top Nacional**
- Plano odontológico
- **VR** ou **VA**
- **Acesso completo e gratuito** a todos os [Cursos Ninja](https://www.udemy.com/user/fernando-daciuk/) do Fernando Daciuk (nosso CTO)
- **Ingressos na faixa** para os principais eventos de Front-end do Brasil

#### Ambiente:

- **Full Remoto**
- Usamos **Github** para todos nossos projetos
- Somos **dev-first**
- Trabalhar com [gente foda](https://lukin.co/about) 

## Contratação

CLT

## Local

Remoto

## Sobre a Lukin 

O grande propósito da **Lukin** é ser um lugar que seus fundadores sempre sonharam trabalhar: uma empresa que seja **dev-first** e **remote-first**, que tenha ótimos projetos com tecnologias de ponta, que valorize o open-source e que esteja junto da comunidade, afinal, a **Lukin** nasceu a partir dela.

Para saber mais sobre nossa cultura, acesse [lukin.co/careers](https://lukin.co/careers) 😍

## Como aplicar

Basta submeter o form: [lukin.co/vaga-frontend](https://lukin.co/vaga-frontend)

## Feedbacks 🗣

Costumamos enviar feedbacks em até **10 dias** após o envio do teste técnico. 

Caso você não tenha recebido nenhum feedback, favor entrar em contato com diogo@lukin.co =]

**Comment by codder404** [comment]
Boa tarde @diogomoretti 
Estou em Angola

**Comment by gregorispielmann** [comment]
Mandei!

**Comment by jgalmeida93** [comment]
Enviado!

**Comment by fogeid** [comment]
É remoto para junior?

**Comment by BenhurKulzer** [comment]
Enviado!

**Comment by itamar-nunes** [comment]
Pode ser PJ?

**Comment by pablojr17** [comment]
Enviado

**Comment by djianLucca** [comment]
Feitooo

**Comment by diogomoretti** [comment]
> É remoto para junior?

Sim 😁

> Pode ser PJ?

Somente CLT 😊

**Comment by luiznasciment0** [comment]
Enviado! :)

**Comment by ThalesAlonso** [comment]
Enviado! :)

**Comment by murigama** [comment]
Enviado :+1:

**Comment by daabraga** [comment]
Enviado !

**Comment by victorvhs** [comment]
Enviado 🤞🤞

**Comment by eduardoluizmaappz** [comment]
Enviado 🤞

**Comment by diogomoretti** [comment]
Pessoal, fechamos por aqui e já estamos filtrando as pessoas para a próxima etapa =]
