### ISSUE TITLE
[São Paulo - Faria Lima] Full Stack Developer no alt.bank 

### ISSUE THREAD

**Issue by SchultzVinicius** [frontendbr/vagas#3005]
As a Full-Stack Developer, you should be comfortable around both frontend and backend coding languages, development frameworks and third-party libraries. You should also be a team player with a knack for visual design and utility.

RESPONSABILIDADES E ATRIBUIÇÕES
THE ROLE:
We are looking for a Senior Full-Stack Developer to produce scalable software solutions. You’ll be part of a cross-functional team that’s responsible for the full software development life cycle, from
conception to deployment. We avoid bureaucracy, give a lot of autonomy and best tools available so senior developers can be high performant.

If you’re also familiar with Cloud Computing and Agile methodologies, have goodcommunication and organization skills, as well as attention to details, we’d like to meet you.
Our stack consists of Java for the backend and Flutter for our apps. We don't require for you to have knowledge of any specific language. Rather we want for you to have a solid grasp of the fundamentals and best fundamentals of software engineering.

## Local

São Paulo - Faria Lima

## Benefícios

- Seguro de vida
- VR
- Gympass

## Requisitos
Profundo conhecimento de Java e conhecimento de Flutter / Dart é diferencial!.
Interesse em integração contínua, implantação contínua e trunk-based development
Familiaridade com SQL, NoSQL e/ou outras arquiteturas e produtos de banco de dados.
Experiência no desenvolvimento de soluções de alta escala em negócios orientados para o desempenho.
Interesse em desenvolvimento Server-Driven para aplicativos de front-end.
Interesse em data science, machine learning e campos correlatos.
Inglês fluente - oral e escrita.
Experiência em métodos ágeis.
Flexibilidade para trabalhar em um ambiente de startup em rápido crescimento.
Experiência comprovada como desenvolvedor Full-Stack ou função semelhante.
Experiência no desenvolvimento mobile obrigatórios;
Familiaridade com stacks de desenvolvimento de software;
Conhecimento de várias linguagens, estruturas e bibliotecas de front-end, especialmente as relacionadas ao desenvolvimento mobile e da Web.
Conhecimento de várias linguagens e estruturas de back-end.
Familiaridade com bancos de dados, servidores Web e design de UI / UX.
Fortes habilidades organizacionais e de gerenciamento de projetos.
Excelente comunicação, habilidades de trabalho em equipe e atenção aos detalhes.

## Contratação

PJ 

## Como se candidatar

Por favor se candidate pelo link: https://altbank.gupy.io/jobs/166130

#### Alocação
- Alocado

#### Nível

- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by SchultzVinicius** [comment]
Olá @felipefialho, vaga ainda aberta!

Obrigado
