### ISSUE TITLE
[São Paulo - Paulista] Front-end Developer React na FDTE

### ISSUE THREAD

**Issue by VanessaBruno3** [frontendbr/vagas#3006]
Descrição da vaga
Experiência em desenvolvimento voltado para Front-End
Bons conhecimentos e experiência em React

Local
São Paulo - Paulista

Contratação
PJ

Benefícios
Horários flexíveis
Diferenciais
Ambiente descontraído
● 80hs em banco de horas, como descanso, após 1 ano de contrato
● Possibilidade de 13º. e 14º. salários (pois, depende de metas)
● Possibilidade de Bolsa MBA (parceria com a FIAP) - sorteio entre a equipe interessado no curso.
● Programa de terapia
● Incentivo financeiro mensal (em cartão de crédito corporativo) para desenvolvimento pessoal
compra de livros, cursos, certificações e participação de eventos da área de tecnologia.

Nossa empresa

Dê uma olhada no nosso Site : http://www.fdte.org.br/
a Fundação é com foco em engenharia - ligada a Poli USP
o nosso escritório é um braço que é da Tecnologia
Vaga é para Paulista

**Como se candidatar**
Por favor, envie um email para vanessa.bruno@fdte.io com seu CV anexado - enviar no assunto: Vaga Front-End Developer ou em meu watsapp: (11) 98208-1494

Tempo médio de feedbacks
Costumamos enviar feedbacks em até 7 dias após cada processo.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
