### ISSUE TITLE
[Rio de Janeiro - Barra da Tijuca] Front-end Developer na Solutto ERP

### ISSUE THREAD

**Issue by erickvils** [frontendbr/vagas#3007]
## Descrição da vaga

Front-end developer para atuar full-time na Solutto, uma empresa pioneira na modalidade SaaS e Cloud há mais de 17 anos e com práticas agile há 12 anos.

## Missão

> Desenvolver os sistemas e aplicações da Solutto, implementando interfaces gráficas, critérios ergonômicos de navegação, visando à performance e usabilidade.

## Sobre a Solutto

- A Solutto fabrica o ERP mais completo e especializado em franquias do mercado brasileiro. Um software web maduro com mais de 16 anos de melhorias contínuas no kernel do ERP, comercializado na modalidade de SaaS (Software como serviço) na nuvem (Cloud) e que possui dezenas de aplicativos e subsistemas conectados.
- Possui escritórios no Rio e em São Paulo. Mais de 350 franquias utilizam nossos softwares.
- Os aplicativos contectados ao ERP vão desde softwares de frente de loja até aplicativos Android e iOS.

## Local

Escritório, Rio de Janeiro - Barra da Tijuca próximo Shopping Metropolitano na Av Abelardo Bueno

## Benefícios

- VR de R$ 28/dia (para contratados via CLT)
- Auxílio mercado de R$212/mês (para contratados via CLT)

### Treinamentos fornecidos aos colaboradores
- A Solutto fornece treinamentos constantes através da Universidade Solutto (EAD)
- Treinamento e ambientação na cultura e história da empresa
- Treinamento no Solutto ERP e nos conceitos de sistemas de gestão integrada
- Treinamento em franchising
- Treinamento em varejo
- Treinamento nos principais segmentos de mercado (food, moda, serviços e educacional)
- Treinamentos técnicos em encontros da própria célula de desenvolvimento
- Treinamentos em outras 15 áreas de conhecimento

### Plano de carreira e um pouco da nossa cultura
- Todas as nossas carreiras possuem 4 graus de maturidade (Junior, Pleno, Sênior e Master). Em cada grau, são 5 níveis. Assim, temos um plano de carreira com até 20 níveis salariais e de responsabilidades.
- As carreiras permitem evolução vertical (analistas que podem se tornar coordenadores ou gerentes) e também deslocamentos horizontais, como por exemplo um analista de testes pode se deslocar para analista de soluções ERP ou para analista de projetos, caso seja interesse do colaborador fazer esta transição horizontal.
- Temos escritórios no Rio e em São Paulo e isso permite que em quase todas as carreiras seja viável uma eventual movimentação de base caso o colaborador assim deseje, por algum motivo pessoal.
- Valorizamos a pluraridade e a diversidade. Respeitamos suas escolhas no âmbito político, religioso e afetivo.
- O ambiente não é "tóxico", mas não espere um ritmo calmo. É bem dinâmico! A cobrança por agilidade é tão intensa quanto a qualidade e atenção. 

### Sobre o local de trabalho desta vaga
- O escritório do Rio de Janeiro fica dentro de um Coworking na Barra a Tijuca, próximo da Av. Abelardo Bueno na "Barra Olímpica"
- O local é bem legal e colorido e tem até estrutura para quem quiser vir de bicicleta e tomar um banho ao chegar.
- Próximo do BRT e pontos de ônibus e do shopping Metropolitano Barra.
- O café expresso é liberado e de vez em quando tem uns mimos (bolinhos).
Existe copa, pratos, talheres e microondas para aquecer sua comida se você preferir trazer de casa.

## Requisitos

**Obrigatórios:**
- Ensino médio completo;
- Conhecimento de HTML5, CSS, Javascript, Ajax, JQuery, Bootstrap, REST e XML;
- Conhecimentos de UX e UI;
- Compreensão de inglês técnico.

**Desejáveis:**
- Capacidade para treinar e desenvolver outras pessoas em níveis de maturidade inferior;
- Ser formado em alguma graduação
- Domínio de pelo menos destes frameworks: Vue.js, REACT ou Angular;
- Saber criar e publicar apps para Android e iOS;
- Tratamento de imagens;
- Experiência com aplicativos de varejo ou franquias e/ou segmentos de mercado como moda, alimentação, educacional e serviços.
- Conhecimentos em C# ou VB.Net
- Conhecimentos em ASP.NET WebForms
- Conhecimentos em Git

## Contratação

- CLT ou PJ a combinar.
- Possuímos um plano de cargos e salários com 20 níveis e no caso de PJ segue proporcionalmente

## Como se candidatar

Por favor acesse o link direto desta vaga e faça sua aplicação:
[https://www.solutto.com.br/vaga-desenvolvedor-web-front-end-rj-rio-de-janeiro](https://www.solutto.com.br/vaga-desenvolvedor-web-front-end-rj-rio-de-janeiro)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dia após a sua aplicação.
E-mail para contato em caso de não haver resposta ou se você encontrar algum problema no processo de aplicação: rh@solutto.com.br

#### Alocação
- Alocado

#### Regime
- CLT
- PJ

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by erickvils** [comment]
Qualquer dúvida pode ser inserida aqui nos comentários e será respondida o mais rápido possível de forma pública. Caso deseje a resposta de forma privada, basta sinalizar.

**Comment by solutto-rh** [comment]
@erickvils obrigada por publicar a vaga aqui como _issue_.  Não somos nerds como esses super-developers do Github, mas isso vai ajudar a trazer mais uns/umas admiradores(as) de Starwars pro time da Solutto.  Link direto para a aplicação rápida para esta vaga: [https://www.solutto.com.br/vaga-desenvolvedor-web-front-end-rj-rio-de-janeiro](https://www.solutto.com.br/vaga-desenvolvedor-web-front-end-rj-rio-de-janeiro)

**Comment by gabok2** [comment]
Boa tarde, existe a possibilidade de atuar na parte mobile da empresa usando react native?

**Comment by erickvils** [comment]
Olá @gabok2 tudo bem? Estamos à procura de um profissional front-end que atue em páginas responsivas 90% do tempo e só uns 10% na parte mobile.  Temos muitas coisas em webview, portanto o dev de mobile fica bem simples e não precisa de muita programação.

Sobre o react native, sim, é uma das tecnologias que temos na stack mobile, mas como citei acima, será só 10% do tempo.

Os outros 90% está bem mais para html5, css3, jquery, vue.js, javascript puro, bootstrap e muitas chamadas para apis rest.

**Comment by gabok2** [comment]
Pretende mudar a parte do site para reactJs?

**Comment by erickvils** [comment]
Oi @gabok2 , respondendo sua pergunta sobre mudar parte do site para reactJs, não pretendemos.

O maior tempo de um desenvolvedor front-end aqui na Solutto é na implementação de novas telas e manutenção das mais de 3.000 telas existentes no ERP que atualmente é em .net no backend e no front-end praticamente sem frameworks, ficando apenas com html5, javascript, vue.js e jquery.

**Comment by nayara1alka** [comment]
Oi... boa tarde! 
Tem possibilidade de remoto ?

**Comment by erickvils** [comment]
Olá @nayara1alka tudo bem?

Esta vaga infelizmente não tem como ser remota. Será demanda muita integração e atuação em conjunto com todo o time de dev.

Obrigado pelo seu contato de qualquer forma.

**Comment by rochagbr** [comment]
Olá, Erick. Tudo bem?
Essa vaga é pra início imediato?

**Comment by erickvils** [comment]
> Olá, Erick. Tudo bem?
> Essa vaga é pra início imediato?

Olá @rochagbr tudo bem?

Esta semana pausamos os processos seletivos em função da urgência em proteger nossos colaboradores.

[Divulgamos um comunicado](https://www.solutto.com.br/blog-plano-de-acao-pandemia-corona-virus) explicando um pouco do que tivemos de fazer, caso queira ler.

De qualquer forma, se desejar se aplicar à vaga e já deixe seu contato no nosso banco de talentos.
Por favor acesse o link direto desta vaga e faça sua aplicação: 
[https://www.solutto.com.br/vaga-desenvolvedor-web-front-end-rj-rio-de-janeiro](https://www.solutto.com.br/vaga-desenvolvedor-web-front-end-rj-rio-de-janeiro)

Obrigado pela compreensão.

É o momento de cuidar uns dos outros. Proteja-se!

**Comment by domuserk** [comment]
Olá me chamo Ryan me encaixo perfeitamente nesta vaga!

**Comment by erickvils** [comment]
> Olá me chamo Ryan me encaixo perfeitamente nesta vaga!

Oi @domuserk, Esta semana pausamos os processos seletivos em função da urgência em proteger nossos colaboradores.

Divulgamos um comunicado explicando um pouco do que tivemos de fazer, caso queira ler.

De qualquer forma, se desejar se aplicar à vaga e já deixe seu contato no nosso banco de talentos.
Por favor acesse o link direto desta vaga e faça sua aplicação:
https://www.solutto.com.br/vaga-desenvolvedor-web-front-end-rj-rio-de-janeiro

Obrigado pela compreensão.

É o momento de cuidar uns dos outros.

**Comment by vinnydev2016** [comment]
Boa noite, são muitas skills para 4 níveis.
Poderia por gentileza elencar quais são as skills para um Jr?
O processo seletivo ainda está em aberto?
Grato.

**Comment by domuserk** [comment]
CSS3,Javascript, Php,React.

**Comment by erickvils** [comment]
> Boa noite, são muitas skills para 4 níveis.
> Poderia por gentileza elencar quais são as skills para um Jr?
> O processo seletivo ainda está em aberto?
> Grato.

@vinnydev2016 

Na descrição da vaga separamos os requisitos entre obrigatórios e desejáveis. 

A vaga ainda está em aberto, porém estamos mais cautelosos na contratação e passamos a aceitar trabalho remoto, porém provavelmente só faremos oferta neste modelo para profissionais com maturidade Pleno/Sênior.

**Obrigatórios:**

- Ensino médio completo;
- Conhecimento de HTML5, CSS, Javascript, Ajax, JQuery, Bootstrap, REST e XML;
- Conhecimentos de UX e UI;
- Compreensão de inglês técnico.

**Desejáveis:**

- Capacidade para treinar e desenvolver outras pessoas em níveis de maturidade inferior;
- Ser formado em alguma graduação
- Domínio de pelo menos destes frameworks: Vue.js, REACT ou Angular;
- Saber criar e publicar apps para Android e iOS;
- Tratamento de imagens;
- Experiência com aplicativos de varejo ou franquias e/ou segmentos de mercado como moda, alimentação, educacional e serviços.
- Conhecimentos em C# ou VB.Net
- Conhecimentos em ASP.NET WebForms
- Conhecimentos em Git

**Comment by domuserk** [comment]
Boa noite domino jquery,ajax,JavaScript e css3
Então teria possibilidade de trabalho para minha pessoa é que moro em São
Paulo

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
