### ISSUE TITLE
[REMOTO] Front-end Developer React Native na Vesti

### ISSUE THREAD

**Issue by andressavazpinto** [frontendbr/vagas#3008]
**Descrição da vaga:**
A Vesti está procurando um profissional PJ aplicado, para manter as aplicações e criar novas funcionalidades.

**Requisitos:**
- Sênior em React
- Preocupado com a experiência do usuário, e não apenas com o código.
- Altamente responsável e com muita iniciativa.

**Diferencial:**
- Experiência com trabalho remoto 

**Vesti**
A Vesti está no mercado há 4 anos, oferecendo soluções para aumentar a produtividade das vendas no setor de vestuário atacado. (vesti.mobi)

**Processo**
Enviar currículo para andressa@vesti.mobi, com o assunto "[REMOTO] Front-end Developer React Native + seu nome" e o currículo em anexo. Envie também o valor/hora e disponibilidade para trabalhar conosco.

## Labels
- Remoto
- PJ
- Sênior

**Comment by fdaciuk** [comment]
Oi @andressavazpinto! Atualize seu post com as labels, por favor?

**Comment by andressavazpinto** [comment]
> Oi @andressavazpinto! Atualize seu post com as labels, por favor?

Oie! Como eu coloco?

**Comment by fdaciuk** [comment]
@andressavazpinto se você criar uma nova Issue, vai aparecer as opções de labels no final do texto padrão que aparece :)
