### ISSUE TITLE
[Goiânia] Front-end Developer na Bento Tecnologia

### ISSUE THREAD

**Issue by kelvinsleonardo** [frontendbr/vagas#3011]
## Descrição da vaga

- Conhecimentos em Angular2+, CSS/SASS, Typescript.
- Ter proatividade para encontrar soluções/melhorias.

## Local

JK New Concept Business (Av. E, 48 - Jardim Goiás, Goiânia) - **(Presencial)**

## Requisitos

**Obrigatórios:**
- Framework Angular2+
-  HTML, CSS, JavaScript
-  Integração e consumo de API REST

**Diferenciais:**
- Conhecimento em Java
- Scrum

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para bentotecnologia@outlook.com com seu CV anexado - enviar no assunto: Vaga Front-end.

#### Alocação
- Alocado

#### Regime
- PJ (Presencial)

#### Nível
- Júnior
- Pleno

**Comment by maycklima** [comment]
Ainda está vago?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
