### ISSUE TITLE
[São Paulo] Front-end Developer React na SorteOnline LottoCap

### ISSUE THREAD

**Issue by lottocap** [frontendbr/vagas#3013]
## Sobre a empresa

O SorteOnline é atualmente líder de mercado em intermediação de apostas em loterias no Brasil.

Há 15 anos no mercado, o SorteOnline simplifica a vida dos apostadores que ao invés de irem à casa lotérica, apostam pelo site.

Pioneiro em diversos produtos relacionados ao mundo de apostas, o Grupo SorteOnline também abriga uma série de novas empresas startup cujos produtos vão de títulos de capitalização digitais, ERP para lotéricas à apostas esportivas.

## Localização

O escritório fica em Pinheiros, na Rua dos Pinheiros 1040 - a 3 quarteirões da estação Fradique Coutinho (linha amarela do metrô). [link aqui](https://www.google.com/maps/place/Sorte+Online/@-23.5674255,-46.6902472,17z/data=!3m1!4b1!4m5!3m4!1s0x94ce575d4d87d6f5:0x7cdf0caa76d61b94!8m2!3d-23.5674255!4d-46.6880585])

## Sobre a vaga

Estamos buscando um desenvolvedor frontend pleno / sênior react para atuar no time do LottoCap (https://www.lottocap.com.br), um dos braços do SorteOnline, responsável por venda de títulos de capitalização digital em forma de jogos.

Nosso desafio é lançar novos jogos em 2020 além da migração para Docker e Kubernetes.

#### Obrigatórios:
- Git
- Bootstrap
- JavaScript ES6+
- CSS 3
- HTML 5
- React

#### Desejáveis:
- Node.js
- Testes Unitários
- Documentação
- Scrum e Kanban

#### Diferenciais:
- SQL
- Docker

## Sobre a Contratação

Contratação CLT ou PJ (faixa salarial será exposta durante a entrevista).

## Processo seletivo
- Inscrição (envie seu currículo PDF ou linkedin para joao@lottocap.com.br)
- Avaliação de currículos e experiências
- Entrevista por Skype
- Teste prático
- Entrevista em nosso escritório
- Contratação

### Alocação
- Alocado

### Regime
- CLT 
- PJ

### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
