### ISSUE TITLE
[Curitiba] Estágio em Desenvolvimento na Straube

### ISSUE THREAD

**Issue by straube** [frontendbr/vagas#3014]
# Descrição da vaga

Buscamos uma pessoa que esteja entrando no mercado de trabalho e muito afim de aprender para atuar com desenvolvimento front e back-end. Você vai ter a oportunidade de trabalhar em diversos projetos, usando tecnologias como React, Vue, SASS e Laravel.

# Local

Nosso escritório fica no Juvevê, em Curitiba, PR.

# Benefícios

* Bolsa auxílio: R$800,00
* Vale-transporte
* Vale-refeição

# Diferenciais

* Ambiente de trabalho descontraído
* Incentivo à participação em cursos e eventos
* Possibilidade de contratação

# Requisitos

## Obrigatórios

* Necessário cursar graduação em TI ou áreas relacionadas
* Disponibilidade para estagiar 30 horas por semana
* Capacidade de ler e escrever em inglês
* Noções de programação

## Desejáveis

* Conhecimentos em HTML, CSS e Javascript

## Diferenciais

* Experiência prévia com projetos de front-end

# Nossa empresa

A Straube foi fundada em Curitiba, em 2010, como uma empresa de desenvolvimento de software, atendendo inicialmente agências de publicidade e pequenos negócios. Em 2014, nossa área de atuação foi ampliada e passamos a oferecer também serviços de design. Hoje ajudamos startups, pequenos e médios negócios a alcançarem sucesso com projetos digitais, tanto para web quanto sistemas internos. Atendemos clientes no Brasil e exterior.

# Como se candidatar

Por favor envie um email para vanessa@straube.co com o link para o seu LinkedIn ou com seu CV anexado. Enviar no assunto: *Vaga de estágio desenvolvimento*

#### Alocação
- Alocado

#### Regime
- Estágio

**Comment by GuilhermeLis** [comment]
tem a possibilidade de ser remoto?

**Comment by straube** [comment]
Oi Guilherme. O nosso programa de estágio é focado em mentoria/capacitação profissional. Então ser remoto acaba dificultando um tanto o processo. De qualquer forma, a lei do estágio também não permite.

**Comment by straube** [comment]
Em função do risco de transmissão do coronavírus, fechamos nosso escritório por tempo indeterminado. Com isso também pausamos o processo de seleção para a vaga de estágio. Retomaremos o processo assim que considerarmos seguro. Vamos entrar em contato com todos que enviaram currículos até agora.
