### ISSUE TITLE
[São Paulo] Desenvolvedor .Net Pleno

### ISSUE THREAD

**Issue by camilaazuma** [frontendbr/vagas#302]
## Quem é a Inspira

A Inspira é uma empresa de tecnologia com foco em inovação, que trabalha com metodologias ágeis e possui cultura de aprendizado contínuo.

Estamos procurando um desenvolvedor .NET PLENO que nos ajude a encantar nossos clientes com produtos que melhorem o dia a dia dos seus usuários.

## Quem buscamos

* Apaixonado por desenvolvimento de software e metodologias ágeis
* Bons conhecimentos em .NET para a Web
* Espírito de equipe buscando sempre a excelência do grupo, sem #mimimi
* Foco em trazer o máximo de valor pro cliente, entendendo suas necessidades, prioridades e objetivos de negócio antes de começar a colocar a mão no código

## O que temos a oferecer

* Autonomia e espaço para influenciar nas decisões de como as coisas serão feitas
* Excelente ambiente de trabalho, cultura de aprendizado contínuo, pessoas * apaixonadas e comprometidas
* Horário flexível (entrada das 9h às 11h)
* Home office 1 dia por semana

## Principais atividades

* Desenvolvimento de sistemas web e mobile utilizando ASP.NET MVC e WebAPIs (C# / * ASP.Net MVC / Entity Framework / Javascript / CSS / HTML)
* Participação ativa na construção da arquitetura dos aplicativos e sistemas, * utilizando as melhores práticas da indústria, tais como design patterns, testes * automatizados / BDD e integração contínua
* Utilização de boas práticas de desenvolvimento e metodologias ágeis com o time, estimulando e participando de atividades como programação em par, revisão de código, coding dojos e tech talks

## Outros benefícios

Vale refeição / vale transporte / Plano de saúde - Bradesco Saúde Top Nacional - Quarto, com Plano Dental Padrão

## Local

Estamos localizados na Vila Mariana - 400m do metrô Ana Rosa

## Contratação

A combinar

## Como se candidatar

Por favor envie um email para vagas@inspira.com.br com seu CV anexado - enviar no assunto: Vaga .Net

**Comment by camilaazuma** [comment]
Labels: CLT, PJ, Pleno, Alocado

**Comment by Mendrone** [comment]
Olaa @camilaazuma  tudo bem?

Se importa se eu tirar esse anúncio de vaga do ar? Te explico porque:

Temos feito um trabalho aqui de ajudar o pessoal de front a encontrar vagas legais. A ideia é ter vagas focadas nesse mercado pra manter o repositório sempre organizado e manter o interesse do pessoal em publicar vagas.

Se você tiver vagas para frontend ai na sua empresa o espaço é todo seu pra divulgá-las por aqui. Sei que existe um espaço de vagas para backend (não me lembro o repo, infelizmente)

Sei que removendo a vaga pode parecer que estamos tentando segregar ou algo do tipo, porém é importante pra nós manter o foco nesse mercado, um esforço a mais pra manter a comunidade mais ativa.

Valeu e boa sorte ai na busca pelo Csharpeiro ideal!
