### ISSUE TITLE
[REMOTO] Front-end Developer CodeIgniter & Bootstrap na Empreender 

### ISSUE THREAD

**Issue by andreas-monday** [frontendbr/vagas#3020]
## Descrição da vaga

Procuramos um(a) profissional com experiência em CodeIgniter, PHP, JavaScript, HTML, CSS , jQuery, Bootstrap.

## Local

Remoto

## Contratação

PJ a combinar

## Nossa empresa

Somos uma empresa com diversos produtos voltados ao ecommerce.

## Como se candidatar

Por favor candidate-se pelo link https://empreender.com.br/vagas

#### Alocação

- Remoto

#### Regime

- PJ

#### Nível

- Pleno

**Comment by rodrigopluz** [comment]
CV enviado.

**Comment by danielswater** [comment]
Enviado

**Comment by dersonsena** [comment]
@andreas-monday Currículo enviado =)

**Comment by nandomoreirame** [comment]
enviado.

**Comment by felipetrova** [comment]
@andreas-monday poderiam verificar o form do site? Tá dando erro ao enviar o CV, ou se possível, adicionar um e-mail para que possamos enviar 😄

**Comment by danielswater** [comment]
Ainda está aberta essa vaga?

**Comment by andreas-monday** [comment]
Olá! Sim, ainda está aberta.
Muito obrigado.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
