### ISSUE TITLE
[CAMPINAS/SP] Front-end/Angular Developer na SHARK IT

### ISSUE THREAD

**Issue by rhsharkit** [frontendbr/vagas#3022]
## Descrição da vaga

Procuramos um profissional pleno/sênior para atuar em um grande projeto da área bancaria 

## Local

Campinas/SP  - Praça Capital 
Remoto 2 a 3x por semana

## Requisitos
Forte experiencia com Angular 
Versão 8 do Angular 
Experiencia com Ionic 
Banco de dados relacionais e não relacionais 

**Obrigatórios:**
- 3 anos de experiência com Angular

**Desejáveis:**
- conhecimentos em React Native

## Contratação

PJ - inicial 3 meses com probabilidade de renovação 
Full Time 

## Nossa empresa

Nós da Shark IT oferecemos as melhores soluções para recrutamento e seleção de profissionais de tecnológicas

## Como se candidatar

Por favor envie um email para relacionamento@sharkit.com.br com seu CV anexado e sua pretensão salarial PJ - enviar no assunto: Vaga front-end/Angular - Campinas 

## Tempo médio de feedbacks

Candidatos com o perfil da oportunidade, entramos em contato imediatamente para conversarmos melhor sobre a oportunidade, passamos o feedback negativo ou positivo, para o candidato, em cerca de uma semana desde o primeiro contato do RH. 

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by diegohyenna** [comment]
bom dia, não aceitam full remoto?

**Comment by rhsharkit** [comment]
> bom dia, não aceitam full remoto?

Infelizmente full remoto não :((

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
