### ISSUE TITLE
[REMOTE] Front-end React Developer na SimpleLegal 

### ISSUE THREAD

**Issue by darrendahl** [frontendbr/vagas#3024]
## Descrição da vaga

**Este trabalho requer inglês, salário muito competitivo**

Title: Engineer – Software Development
Frontend Engineer (React)

Responsibilities:
Build and maintain features on the frontend side of the codebase.
Review code written by your colleagues and help grow the team.
Work closely with our designers, communicate with product management, marketing, support, and customer success to refine requirements, document features, and debug production issues.
Skills & Experience:
Required:
JavaScript ES5 & ES6, HTML5, CSS3
React, Redux (or other flux architecture)
Webpack
jQuery
Desirable:
Flow, Jest, Enzyme, Cypress
NodeJS
Python
Django
Git, Heroku, AWS, GCP, Docker
3+ years of relevant experience
Education:
BE/BTech in CS/IT or MCA or MSc (CS) preferred
Our Tech Stack

New code is written in JavaScript ES6 & React and transpiled and minified with Webpack and Babel. Our flux architecture is driven by Redux for state management, and Redux Saga for application side effects such as data fetching. We use SASS and CSS Modules to write our CSS. We have our own shared component library, featuring a home grown react storybook-like system, and a design system. Unit tests are written in Jest & Enzyme, we use Flow for type checking, and Cypress for our end to end tests.

Our apps are built using Django + Postgres on Heroku. Developer services are hosted on AWS and GKE. Our users typically interact with SimpleLegal directly through the UI but we do have an API implemented using Django REST Framework for integrations with other legal-tech and fin-tech applications. The frontend is primarily Bootstrap with JavaScript & jQuery which is being incrementally replaced with modern infrastructure.

As alluded to earlier, you will have a responsibility to maintain the old jQuery/JS/Bootstrap application as problems arise, but primarily your work will be to build customer facing features in our new framework and grow our infrastructure.

### About SimpleLegal ###
SimpleLegal is a legal tech enterprise SaaS startup run by experienced founders, based in Mountain View, CA. We’ve created a software platform to run in-house legal operations. As a well-funded startup with a diversified customer base and meaningful revenue, we are bringing corporate legal teams into the modern age.  Sales has Salesforce, Marketing has HubSpot, Legal has SimpleLegal.  In May of 2019, SimpleLegal joined the Onit family as of an expansion to offer solutions to the leading companies around the world. 

### About Onit ###

Onit is a global leader of enterprise workflow solutions for legal, compliance, sales, IT, HR and finance departments. Our solutions transform best practices into smarter workflows, better processes and operational efficiencies. With a focus on enterprise legal management, matter management, spend management, contract management and legal holds, we operate globally and help transform the way Fortune 500 companies and billion-dollar legal departments bridge the gap between systems of record and systems of engagement. We help customers find gains in efficiency, reduce costs and automate transactions faster.

## Local

Trabalho de contrato remoto

## Como se candidatar

Por favor envie um email para darren.dahl@simplelegal.com com seu CV anexado - enviar no assunto: Vaga ReactJS

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by dersonsena** [comment]
@darrendahl Currículo enviado.

**Comment by robertveloso** [comment]
@darrendahl, I've also sent my resume. I'm looking forward for your reply.

**Comment by drrh12** [comment]
@darrendahl  Applied.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
