### ISSUE TITLE
[São Paulo] React Front-end Developer na Easynvest

### ISSUE THREAD

**Issue by taianeuchoac** [frontendbr/vagas#3025]
## Descrição da vaga
Profissional atuará em projetos internos da empresa, voltados para a área de investimentos.
Atuação com foco em React.

## Local
Atuação presencial, na região da Vila Olímpia.

## Benefícios
Horário Flexivel.

#### Diferenciais
Ambiente descontraído;
No dress code;

## Requisitos

**Obrigatórios:**
Minimo de 03 anos de atuação como Front End, desenvolvendo com Javascript Vanilla, React, HTML e CSS;
Experiência em novos desenvolvimentos, planejando a arquitetura do zero;
Ter a cultura de testes;
Organizar os sistemas Frontend em camadas de subsistemas e componentes para que possam ser facilmente gerenciados;
Criar esboços, modelos, protótipos e manuais de usuário, com o objetivo de manter os desenvolvedores e usuários constantemente atualizados;

## Contratação
A combinar.

## Nossa empresa
A Mazzatech é uma consultoria de TI, que esta no mercado há mais de 10 anos. Estamos auxiliando a Easynvest na busca deste profissional para atuar alocado nesta empresa.

## Como se candidatar
Por favor envie um email para taiane@mazza.tech com seu CV anexado e pretensão salairal - enviar no assunto: Vaga React (Vila Olimpia).

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: taiane@mazza.tech

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
