### ISSUE TITLE
[Rio de Janeiro] Front-end Developer na HomeHub

### ISSUE THREAD

**Issue by startecjobs** [frontendbr/vagas#3027]
## Descrição da vaga

Se você tem perfil empreendedor, gosta de desafios e quer ajudar as pessoas a encontrarem seu lugar no mundo, essa vaga pode ser pra você: buscamos desenvolvedor(a) front-end para trabalhar com SCRUM na startup que veio para mudar a forma com que se vende e compra imóveis.

“Na HomeHub, valorizamos muito o profissional que está disposto a aprender e melhorar cada dia mais a sua curva de aprendizado no nosso ambiente de trabalho informal.”

Quem vier para agregar ao time terá a oportunidade de estar na WeWork Barra da Tijuca, ambiente de muito networking e trocas com outras empresas.

## Local

WeWork, Barra da Tijuca. Rio de Janeiro, RJ

## Benefícios

- Salário: R$3.000,00
- Bônus anual podendo chegar a 8 salários

## Requisitos

**Obrigatórios:**
- Git
- HTML5
- CSS3
- React

**Desejáveis:**
- Redux
- RESTful
- CI
- Bitbucket
- Teste de software
- Conhecimento em metodologias ágeis

**Soft skills desejadas:**
- Sentimento de dono
- Proatividade
- Trabalho em equipe
- Busca por aprendizados constante
- Aprendizado contínuo

## Contratação

PJ

## Nossa empresa

A HomeHub veio para revolucionar o mercado imobiliário do Rio de Janeiro e no Brasil. Com anos de experiência nesse mercado tradicional, os sócios Fred, Vagner e Rodolfo decidiram, em 2018, montar um modelo de negócios digital que pudesse resolver os grandes problemas de proprietários de imóveis, clientes e corretores nessa experiência tão dolorosa que é vender e comprar imóveis.

## Como se candidatar

Basta preencher **nome** e **email** no link a seguir: http://bit.ly/Inscrição-Dev-HomeHub
Mandaremos todas as outras etapas do processo seletivo via email. 

## Tempo médio de feedbacks

Costumamos enviar feedbacks após o término das avaliações técnica e comportamental.

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Júnior

**Comment by gabok2** [comment]
Boa tarde, fiz os processos de fit cultural, avaliação, apresentação pessoal, etc. Mas n sei se vcs receberam pq eu consigo fazer essas coisas de novo, ai hj sem querer apertei pra fazer o fit cultural ai eu não sei se isso substitui o que eu já tinha feito.

**Comment by startecjobs** [comment]
> Boa tarde, fiz os processos de fit cultural, avaliação, apresentação pessoal, etc. Mas n sei se vcs receberam pq eu consigo fazer essas coisas de novo, ai hj sem querer apertei pra fazer o fit cultural ai eu não sei se isso substitui o que eu já tinha feito.

Não substitui! Mandaremos todas as informações sobre as etapas do processo seletivo por email! ;)

**Comment by gabok2** [comment]
Boa noite, quinta-feira recebi uma ligação falando que essa semana iria dar o feedback dizendo se eu passei para próxima fase ou não. Estou no aguardo

**Comment by startecjobs** [comment]
> Boa noite, quinta-feira recebi uma ligação falando que essa semana iria dar o feedback dizendo se eu passei para próxima fase ou não. Estou no aguardo

Show de bola. O processo seletivo foi estendido por conta dessa quarentena, mas fique tranquilo que continuaremos enviando todas as informações! ;)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by startecjobs** [comment]
> Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

As inscrições do processo foram prorrogadas. Processo permanece ativo.

**Comment by anacvignola** [comment]
Link não funciona
