### ISSUE TITLE
[São Paulo] Front-end Developer na [ACCT]

### ISSUE THREAD

**Issue by michelmacedogit** [frontendbr/vagas#3028]
### **Local**
Remoto, São Paulo (Capital) ou Atibaia 

## **Benefícios**
Vale-transporte;
Vale-refeição;
Assistência Médica por adesão;
Assistência Odontológica por adesão;
Seguro de vida em grupo;
Diferenciais
Convênio com empresas parceiras;
Parceria com faculdades;
Incentivo financeiro em cursos e certificações;
Inglês in Company;
Totalpass (academia);
Plano de carreira e mentoria;
No dress code;
Horário Flexível e Regras de Home-Office;
Frutas diariamente;
Videogame

## **Requisitos**
Obrigatórios:

Capacidade para escrever código consistente, eficiente, minimalista, reutilizável e escalável
Desenvolver código semanticamente correto e otimizado para SEO
JavaScript, HTML5, CSS3
SASS e/ou LESS
Task runners (Grunt / Gulp)
Controle de versão (Git / SVN)
Experiência com bibliotecas de Javascript, como jQuery
Experiência com grids fluidos e sites responsivos
Facilidade de trabalho em equipe
Proatividade

###**Desejáveis:**

Experiência com React, Vue ou Angular
Experiência com plataformas de e-commerce - VTEX, Magento, OCC
Conhecimento com API's (REST, SOAP)
Diferenciais:

### Projetos opensource
Inglês avançado ou fluente
Experiência em NodeJS
Contratação
CLT

## **Como se candidatar**
Por favor envie um email para michel.marques@acct.global com seu CV anexado - enviar no assunto: Vaga Frontend Developer

## **Labels**
CLT
Pleno
Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
