### ISSUE TITLE
[REMOTE] Front-end Developer na Agência Razzo

### ISSUE THREAD

**Issue by neomarbassani** [frontendbr/vagas#3029]
## Descrição da vaga

Somos uma Software House e buscamos profissionais front-end para complementar nossos times de desenvolvimento. Este profissional atuará em diversos projetos, sendo responsável pelo desenvolvimento das aplicações.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Sólidos conhecimentos em Javascript
- 1+ ano de experiência com React / React Native

**Desejáveis:**
- Ionic
- NodeJS

**Diferenciais:**
- Facilidade de aprendizado
- Muita vontade de aprender
- Bom relacionamento interpessoal
- Experiencia com metodologias ágeis

## Contratação
PJ a combinar

## Nossa empresa

A Agência Razzo é uma Software House gaúcha focada no desenvolvimento de softwares e soluções inovadoras, sempre buscando encarar novos desafios. Nosso time é composto por gerentes de negócio, designers e um seleto time de desenvolvedores, que atuam em conjunto com seus lideres em diversos projetos.

## Como se candidatar

Por favor envie um email para contato@agenciarazzo.com.br com seu CV anexado - enviar no assunto: Vaga React Front End

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: neomar@agenciarazzo.com.br

## Labels
- PJ
- Freela

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by BenhurKulzer** [comment]
Enviado!

**Comment by pablojr17** [comment]
**Enviado**

**Comment by neomarbassani** [comment]
Devido ao corona Vírus, acabamos fechando essa oportunidade! Aos que ja encaminharam, vamos retornar pelo email assim que possível.
