### ISSUE TITLE
[Rio de Janeiro] Fullstack Developer na BomCupom

### ISSUE THREAD

**Issue by startecjobs** [frontendbr/vagas#3030]
## Descrição da vaga

Essa é a vaga pra quem é fera no desenvolvimento web! 

Mas antes de ser fera desenvolvendo, é uma vaga para quem é apaixonado pelo mundo das startups. Aqui na BomCupom nós valorizamos mais as soft skills do que qualquer outra coisa.

## Local

Centro, RJ.

## Benefícios

- Salário: R$ 5.000,00 a R$ 7.000,00
- Vale Transporte
- Vale Refeição
- Assistência Médica

## Requisitos

**Obrigatórios:**
- React Native
- Git
- Ruby on Rails

**Desejáveis:**
- React
- Scrum
- SQL Server

**Soft skills:**
- Proatividade
- Automotivação
- Trabalho em equipe
- Criatividade
- Capacidade analítica

## Contratação

CLT

## Nossa empresa

A BomCupom surgiu entre ideias, rabiscos e sonhos em 2017, inspirada pelo que seu sócio fundador viveu nos EUA. Através do modelo de cuponagem, a empresa permite a integração entre empresas e clientes. Beleza, mas como funciona?

As empresas parceiras estão inseridas num ecossistema de publicidade e propaganda, e as bobinas (rolos) de notas fiscais fornecida pela BomCupom permite que os estabelecimentos divulguem descontos referentes a outras marcas no verso da nota fiscal. Isso permite que, ao consumir seu produto em algum estabelecimento parceiro, você possa ganhar descontos na compra do seu produto favorito de outro estabelecimento!

## Como se candidatar

Basta preencher nome e email no link a seguir: http://bit.ly/Inscrição-webdev-bomcupom
Mandaremos todas as outras etapas do processo seletivo via email.

## Tempo médio de feedbacks

Costumamos enviar feedbacks após o término das avaliações técnica e comportamental.

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by gabok2** [comment]
Boa noite, tenho conhecimento de reactjs e react-native, não sei nada de Ruby on Rails mas estou disposto a aprender. Me encontro no nível júnior, posso me candidatar?

**Comment by startecjobs** [comment]
Para essa vaga é indispensável o conhecimento em Ruby on Rails... Caso tenha interesse em receber outras oportunidades como essa é só se inscrever aqui: http://bit.ly/startecjobs

**Comment by startecjobs** [comment]
> Boa noite, tenho conhecimento de reactjs e react-native, não sei nada de Ruby on Rails mas estou disposto a aprender. Me encontro no nível júnior, posso me candidatar?

Para essa vaga é indispensável o conhecimento em Ruby on Rails... Caso tenha interesse em receber outras oportunidades como essa é só se inscrever aqui: http://bit.ly/startecjobs

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
