### ISSUE TITLE
[Curitiba] Front-end Developer na Imersys

### ISSUE THREAD

**Issue by tiagovignatti** [frontendbr/vagas#3033]
## Descrição da vaga

Procuramos candidatos com vontade de crescer individualmente e aptos a trabalhar com as tecnologias do futuro. Garantimos que os escolhidos irão ter um crescimento rápido! 

Desenvolvemos utilizando tecnologias front-end tais como Vue.js, WebXR, A-Frame, Three.js entre outras utilizando ES6 e Typescript.

https://www.imersys.com/post/trabalhe-com-as-tecnologias-do-futuro-oportunidades-para-desenvolvimento-web-curitiba

## Local

Tecnoparque, em frente a PUCPR. Rua Imaculada Conceição, 1430, Bloco I, Térreo. Sala Imersys.

## Requisitos

Estamos procurando candidatos para estagiar ou recém formados nos seguintes cursos: Ciência da Computação, Engenharia de Computação, Engenharia de Software, Análise e Desenvolvimento de Sistemas, Sistemas de Informação e outros cursos em áreas relacionadas.

Procuramos bons programadores, independente do conhecimento da tecnologia, linguagens e frameworks. Candidatos com vontade de crescer individualmente e aptos a trabalhar com as tecnologias do futuro. Garantimos que os escolhidos irão ter um crescimento rápido!

## Contratação

estágio ou PJ a combinar.

## Nossa empresa

Temos projetos diversos de "serious games" que exigem experiências diversas. Trabalhamos com projetos em Realidade Virtual e Realidade Aumentada (VR & AR), produção de vídeos 360 e outros “side projects” também.

Na área de Desenvolvimento Web, temos projetos desafiadores: a Imersys desenvolve a plataforma de produção de vídeos 360 em alta escala do Ambia e tem também seu próprio player de vídeos para Web. Desenvolvemos utilizando tecnologias front-end tais como Vue.js, WebXR, A-Frame, Three.js entre outras utilizando ES6 e Typescript; no back-end Node.js, AWS, Google Cloud Platform, Elasticsearch. Além do desenvolvimento, precisamos avançar também nas técnicas de Continuous Integration, DevOps e testes (Web, iOS, Android, iPad OS).

## Como se candidatar

Na descrição do email, escreva uma carta pequena (poucas frases, utilizando no máximo meia página) contando suas intenções - a redação é tudo! Um repositório git ou algum tipo de portfolio público disponível conta muito, então por favor se você tiver adicione uma referência também no corpo do e-mail. Currículo ou Linkedin atualizado também é essencial.

Enviar email para jobs@imersys.com com uma breve descrição das intenções.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: jobs@imersys.com

#### Alocação
- Alocado

#### Regime
- CLT
- Estágio
- Freela
- PJ

#### Nível
- Estágio
- Júnior

**Comment by nayara1alka** [comment]
Oi.. bom dia!
 Teria possibilidade de ser remoto ?

**Comment by tiagovignatti** [comment]
Infelizmente não estamos priorizando home-office neste momento @nayara1alka. Talvez futuramente. Muito obrigado pelo interesse no entanto!

**Comment by thauska** [comment]
Ia perguntar sobre homeoffice, mas já vi que tem resposta.

**Comment by tiagovignatti** [comment]
Sabemos que, desde que meu comentário foi postado há 20 dias, o cenário todo mudou. Por favor, enviem então os cúrriculos para jobs@imersys.com que entraremos em contatos com vocês @thauska @nayara1alka. Muito obrigado!

**Comment by jess-silvano** [comment]
a vaga ainda está disponível?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
