### ISSUE TITLE
[Florianópolis-SC] Front-end Developer na Agriness

### ISSUE THREAD

**Issue by anapadriano** [frontendbr/vagas#3035]
## Nossa empresa

A Agriness tem o propósito de impulsionar a prosperidade no campo e faz isso através de soluções em tecnologia e da aplicação de uma metodologia de aceleração de produtividade pioneira no mundo. Estamos em constante crescimento e expansão tanto para novas espécies do agronegócio quanto para outros países. Nosso desafio: escalar a Agriness para o mundo!## Local
Escritório em Florianópolis/SC.

Como Dev Frontend você atuará no Squad do produto “Corp”, uma solução para corporações de produção animal e no dia-a-dia você irá:

Interagir com os desenvolvedores e integrantes da sua Squad para definição e implementação das soluções planejadas.
Implementar código seguindo os padrões de qualidade definidos pela área, através de uso de testes automatizados, processos de integração contínua, revisão de código, buscando disseminar boas práticas.
Desenvolver soluções utilizando tecnologias já adotadas pela empresa como TypeScript, Angular, Sass.
Prezar pela otimização de processos de forma a evitar atividades manuais e repetitivas.

## Benefícios

- Plano de saúde Unimed estadual.
- VR/VA: R$ 670,00.
- Vale combustível no valor de R$ 258,00 ou vale transporte coletivo sem descontos.
- Ginástica Laboral duas vezes por semana.
- No dress code.
- Frutas, chá, café, água e chimarrão à vontade.
- Previdência Privada.
- Folga no dia do aniversário.
- Parcerias de descontos com convênios.
- Aulas de idiomas.

## Requisitos

**Obrigatórios:**
- Ensino superior em áreas de tecnologia e/ou design.
- Experiência com TypeScript, Angular, Sass.
- Criação de testes automatizados.
- Uso de versionamento com GIT.
- Inglês intermediário.

**Desejáveis:**
- Experiência com outras bibliotecas (React, Vue).
- Conhecimento em temas como: clean code, design patterns, design systems.

## Como se candidatar

Por favor envie um email para **ana.adriano@agriness.com** com seu CV anexado - enviar no assunto: "Vaga Frontend"

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
