### ISSUE TITLE
[REMOTO] Front-end Developer Pleno e SÊnior na INVILLIA

### ISSUE THREAD

**Issue by GabriellyLeonel** [frontendbr/vagas#3037]
## Descrição da vaga

Projeto por tempo indeterminado. 

## Local

Remoto.

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ X/dia
- Auxílio creche
- Ajuda de custo

#### Diferenciais

- 2 horas de almoço

## Requisitos

Ter experiência como desenvolvedor frontend com as tecnologias: Javascript, JQuery, JHipster, HTML, CSS, React/Redux, Velocity e SASS;

Ter experiência com testes unitários (Protractor, Seleniun ou Jasmine);

Ter experiência com os versionadores Git e SVN. Ter tido contato com metodologias ágeis como Kanban, SCRUM, XP, etc e práticas como TDD, BDD e Pair Programming;

Desejável: Conhecimento de configuração de servidores WEB como Apache ou NGINX;

Conhecimento em ferramenta de Continous Integration (Jenkins);

Conhecimento em serviços REST e WEB Standards (protocolos, verbos e respostas http, certificados, URI´s, etc);

Conhecimento em gerenciadores de dependência/pacotes (Bower, Maven e Gradle, NPM);

Conhecimento em automatizadores de tarefas como o Grunt

SQL básico;

## Contratação

CLT

## Nossa empresa

Está inovando a maneira como as empresas revolucionárias estão expandindo o poder de criar estratégias, produtos e serviços digitais.

## Como se candidatar

Por favor envie um email para gabrielly.leonel@invillia.com com seu CV anexado e sua pretensão salarial CLT - enviar no assunto: Vaga FRONT-END 

#### Nível
- Pleno
- Sênior

**Comment by hallss93** [comment]
Há possibilidade de PJ?

**Comment by GabriellyLeonel** [comment]
Olá,

Só trabalhamos com contratações CLT.

Att.,

[cid:image005.png@01D5FD3A.F3E158E0]


Gabrielly Leonel
+11 95387-6739
clique para expandir: invillia.com
Brasil Portugal Países Baixos Reino Unido

[cid:image006.png@01D5FD3A.F3E158E0]<https://www.linkedin.com/company/invillia/>   [cid:image007.png@01D5FD3A.F3E158E0] <https://www.facebook.com/invillia/>    [cid:image006.png@01D5FD3A.F3E158E0] <https://www.instagram.com/invillia/>
Global Growth Framework ® 2020.
Uma empresa Fast Track.
Todos os direitos reservados.


De: Hallison Pereira Melo <notifications@github.com>
Enviada em: terça-feira, 17 de março de 2020 17:06
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: Gabrielly Cristina Ruggeri Leonel <gabrielly.leonel@invillia.com>; Author <author@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [REMOTO] Front-end Developer Pleno e SÊnior na INVILLIA (#3037)


Há possibilidade de PJ?

**Comment by mrangel-jr** [comment]
Pode ser part time ?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
