### ISSUE TITLE
[São Paulo] React Front-end Developer na GlobalHitss/Claro Brasil

### ISSUE THREAD

**Issue by mpilao** [frontendbr/vagas#3038]
## Descrição da vaga

Faça parte de um grande time multidisciplinar na Claro Brasil, responsável por muitos sites e apps utilizados por milhões de clientes. São desenvolvedores, Q&As, designers/UX e área de negócios, criando produtos inovadores com as mais modernas tecnologias e de maneira ágil.

## Descrição do Cargo

Profissional experiente em desenvolvimento Front-end utilizando React.js.

## Responsabilidades Principais

- Desenvolvimento e manutenção de soluções responsivas com React.js, aderentes às necessidades do negócio, consumindo APIs internas e externas, baseadas em layouts feitos por designers;
- Ter perfil proativo, boa comunicação, responsabilidade e comprometimento;
- Habilidades interpessoais, mente analítica, atitude de realizar tarefas e paixão pela excelência no desenvolvimento;
- Entregar e exigir código elegante e limpo;
- Disposição para ajudar e compartilhar conhecimento;
- Construir e garantir a atualização da documentação da aplicação;
- Entregar projetos bem testados e sustentáveis;
- Participar ativamente das reuniões e cerimônias do time: review, retrospective, planning e daily’s;

## Experiência

Profissional Sênior com mais de 5 anos de experiência e vivência em grandes projetos de sites de alta audiência.
 
## Formação
Graduação: Ciências da Computação, Engenharia da computação, Sistemas de informação e afins da área de TI.

## Local

Escritório, São Paulo - Chácara Santo Antonio

## Benefícios

- Vale refeição
- Vale alimentação
- Vale transporte / Vale combustível
- Plano de saúde
- Plano odontológico
- Seguro de vida
- Ajuda em certificações
- Gympass
- PLR

#### Diferenciais

- Dayoff no aniversário
- Sala de jogos
- Ambiente informal
- Sem dress code (Pode vir de bermuda!)

## Requisitos

**Conhecimentos Obrigatórios**

Experiência avançada em: 

- HTML5, CSS3;
- JavaScript (ES6+);
- React.JS;

Experiência em:

- TypeScript;
- Gerenciadores de estados e padrões de arquitetura;
- Gerenciadores de dependência e build (Babel, Webpack, Gulp, NPM e etc.);
- Controladores de versão (Github, Gitlab e etc);
- Pré-processadores CSS (SASS, LESS e etc);
- Patterns (CSS e JS);
- Técnicas TDD e BDD (Jest, Enzyme e etc);
- Arquitetura Frontend;
- Integração de Design System;
- Integração de API´s (Rest, SOAP) e API Managers/API Gateways;

**Conhecimentos Desejáveis** 

- NodeJS;
- Apollo GraphQL;
- Práticas DevOps (CI/CD);
- Jenkins, Fortify, Sonar;
- Docker;
- Banco de Dados SQL e NoSQL (DynamoDB, MongoDB, Redis e etc);
- Metodologias Ágeis (Scrum, Kanban e etc);

**Conhecimentos Diferenciais**
 
- React Native;
- Serviços do tipo SaaS da AWS (Firebase, AppSync, Lambda e etc);

## Contratação

CLT pela GlobalHitss

## Nossa empresa

Somos uma empresa com mais de 30 anos de experiência, especialistas no desenvolvimento, implantação, consultoria e integração por meio da tecnologia da informação.  

Com o nosso amplo portfólio de práticas e serviços, GLOBAL HITSS é um aliado ideal para ajudar as empresas com a definição e apoio de suas estratégias, tornando nossos clientes ainda mais inteligentes, produtivos  e eficientes, minimizando riscos e custos.

Desde 2010, nossas conquistas têm crescido e para sustentá-las, contamos com aproximadamente 3.000 profissionais engajados no desenvolvimento consistente do nosso negócio no País.

Apostamos em talentos, no trabalho em equipe, na diversidade e em um ambiente inclusivo.

Acreditamos no desenvolvimento de pessoas, no empoderamento como meio de superação de limites e promoção de resultados.

Apoiamos boas práticas e a sustentabilidade.

​Todas as nossas vagas também são destinadas às pessoas com deficiência.

## Como se candidatar

Por favor, envie um email para mauricio.pilao#globalhitss.com.br com seu CV anexado - enviar no assunto: Vaga React Front-end Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 30 dias após cada processo.
E-mail para contato em caso de não haver resposta: mauricio.pilao#globalhitss.com.br

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
