### ISSUE TITLE
[São Paulo] Front-End Developer na Loop Brasil

### ISSUE THREAD

**Issue by williamespindola** [frontendbr/vagas#3039]
## Descrição da vaga

Front-End Developer experiente que gosta de boas práticas e está sempre 
estudando e se atualizando.

Temos muito trabalho pela frente com demandas novas que já seguem um padrão de
qualidade elevado com boas práticas do mercado, mas também temos aplicações 
legadas que demandam muito trabalho para evoluir e manter.

Buscamos alguém proativo que está sempre se comunicando com outras equipes
avaliando as melhores possibilidades de implementação elevando a qualidade e
facilitando o desenvolvimento.

## Local

São Paulo - Vila Olímpia

## Benefícios

- Férias remuneradas de 30 dias

## Requisitos

**Obrigatórios:**
- Conhecimento avançado de front-end (JavaScript + ReactJS)
- Forte experiência com Web Standards (HTML5, CSS3)
- Interessado em criar uma bela interface do UI/UX com atenção cuidadosa à perspectiva do usuário final
- Conhecimento profundo do ecossistema de front-end (Webpack, etc.)
- Conhecer os conceitos de uma API REST/JSON e Protocolo HTTP
- Capacidade de escrever código de alto desempenho, limpo e reutilizável para componentes da interface do usuário
- Experiência com frameworks de teste
- Git, só fazer commit não vale, tem que saber o que é rebase e usar no dia a dia

**Desejáveis:**
- Conhecimento básico de PHP e Node JS (você não vai desenvolver aplicações em PHP e NodeJS)
- Redux
- SSR
- JSS
- Material UI

**Diferenciais:**
- Projetos open source
- Conhecer e participar de comunidades
- Inglês básico
- Programação Funcional
- Experiência com WebSockets ou qualquer outra api assíncrona

## Contratação

PJ
## Nossa empresa

A Loop é uma empresa da Webmotors com a Estapar. Somos a única plataforma de 
negociação de veículos, desde a remoção até a entrega.

Fundada em 2014, já efetuamos a venda de mais de 35 mil veículos e realizamos 
mais de 1000 eventos de comercialização, tudo isso com excelência operacional
e tecnologia avançada para garantir os melhores resultados para os nossos 
clientes.

## Como se candidatar

Por favor envie um email para t.william.espindola@loopbrasil.com com seu CV anexado ou Linkedin atualizado, link do github se tiver e proposta de salário - enviar no assunto: Vaga Front-End.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: t.william.espindola@loopbrasil.com

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by williamespindola** [comment]
Olá pessoal, tudo bom?
Infelizmente eu vamos precisar fazer uma pausa no processo de avaliação desta contratação por causa do COVID-19, vocês podem continuar submetendo normalmente, vou guardar e analisar todos as propostas. Mas o processo de contratação não vai acontecer por agora e ainda não tenho previsão de quanto vamos voltar com ela. 
Obrigado pela atenção de todos.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
