### ISSUE TITLE
[São Paulo] Node.js Developer

### ISSUE THREAD

**Issue by Dani-Ventron** [frontendbr/vagas#304]
## Descrição da vaga

Projeto Node.JS

## Local
São Paulo - Barra funda

## Requisitos

**Obrigatórios:**
Sólidos conhecimentos em Node.JS, Angular, Metodologias ágeis, Bootstrap, MVC, Git

## Contratação

PJ

## Nossa empresa

A Ventron, empresa do grupo Cadmus, possui 20 anos de atuação no mercado de TI

## Como se candidatar

Por favor envie um email para daniele.silva@ventron.com.br com seu CV anexado - enviar no assunto: Vaga NodeJS

**Comment by WelingtonMonteiro** [comment]
enviado o/
