### ISSUE TITLE
[Rio de Janeiro / São Paulo] Front-end Developer na Árvore de Livros

### ISSUE THREAD

**Issue by lemagnetic** [frontendbr/vagas#3041]
## Descrição da vaga
Descrição completa sobre a vaga e como se candidatar [aqui](https://arvoredelivros.recruitee.com/o/desenvolvedora-frontend-senior).

## Local
Centro do Rio de Janeiro (Saúde), próximo ao Museu do Amanhã ou São Paulo, próximo a Avenida Paulista.

## Benefícios

- Salário compatível com o mercado
- Bonificações em PL anual
- Ambiente de trabalho descontraído e agradável
- Cultura colaborativa
- Flexibilidade de horários e autogestão do tempo
- Vale-transporte
- Vale-alimentação ou refeição
- Plano de saúde

## Requisitos

Importante ter mais de 6 anos de experiência em desenvolvimento de Front-End. Essencial JavaScript (ES6/ES7), familiaridade com Programação Funcional e Styled Components. Pelo menos 2 anos de experiência desenvolvendo aplicações usando React, Redux e React Native. GraphQL (Apollo), Git Flow e algum Module Bundler Webpack ou Brunch vão tornar seu dia mais fácil por aqui também.

## Contratação

Modelo de contratação: CLT ou PJ, a depender das condições negociadas durante o processo seletivo.

#### Alocação
- Alocado

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
