### ISSUE TITLE
[São Paulo] Front-end Developer Jr no Stoodi

### ISSUE THREAD

**Issue by thiagopadula** [frontendbr/vagas#3042]
## Descrição da vaga
Estamos procurando pessoas desenvolvedoras front-end Jr que já consigam se virar com HTML, CSS e Javascript (experiência com React é bem-vinda!) e que queiram muito aprender e contribuir para o nosso projeto de transformar o futuro dos brasileiros por meio da educação.

## Local
Escritório, São Paulo - próximo ao metrô Butantã
(devido ao cenário atual, no momento estamos todos de home office)

## Benefícios

- Vale refeição e alimentação
- Vale transporte
- Plano de saúde
- Plano odontológico
- Auxílio educação
- Programa de remuneração variável

### Diferenciais

- Ambiente ágil, descontraído e inovador em uma startup em crescimento.
- Horário flexível
- Dress code livre

### Obrigatórios:

- Saber se virar com HTML, CSS e JS
- Ter muita vontade de aprender e compartilhar conhecimento

### Desejáveis:

- Experiência com React
- Ter alguma experiência na área

## Contratação
CLT

## Nossa empresa
O Stoodi transforma o futuro dos brasileiros por meio da educação. Somos uma empresa jovem com uma grande ambição de democratizar o acesso ao ensino superior para milhões de brasileiros. Fazemos parte do maior grupo de educação do mundo (sim, do mundo!), combinando a agilidade, autonomia e alto crescimento de uma startup com a força e estabilidade de um gigante.

A nossa plataforma online de estudos serve mais de 100 mil exercícios e 50 mil vídeos por dia a alunos de todo Brasil! Além disso temos diversas outras soluções como simulados, planos de estudo personalizados, os apps mais bem rankeados de orientação vocacional, gabarito Enem, entre tantos outros.

Mas não são apenas os números que nos movem. Mudamos diariamente a vida de milhares de pessoas e acreditamos que ter um propósito de impacto é o que nos diferencia.

## Como se candidatar
Envie seu currículo pelo link [nessa página](https://jobs.kenoby.com/stoodi/job/pessoa-desenvolvedora-front-end-junior/5dc1e8a0272dbd20d9fea690)

## Labels
- Alocado
- CLT
- Júnior

**Comment by gabok2** [comment]
pode ser remoto?

**Comment by jgalmeida93** [comment]
Após o término da situação atual seria somente alocado? Me encaixo mas sou do paraná.

**Comment by DenisStael** [comment]
Tem possibilidade de ser remoto?

**Comment by Jhowslip** [comment]
Aplicado!

**Comment by thiagopadula** [comment]
Respondendo a todo mundo que perguntou sobre remoto: exceto nesse período de coronavírus, a ideia é que o trabalho seja presencial. A gente trabalha em um modelo presencial flexível (de às vezes ir para o escritório e às vezes trabalhar remoto, se a pessoa preferir e o time concordar), mas nesse momento a vaga não é para remoto total.

**Comment by gabok2** [comment]
podia ter vaga pro rj

**Comment by Jhowslip** [comment]
Total disponibilidade para trabalhar alocado, recentemente estive em um projeto próximo ao morumbi  no Banco Carrefour

**Comment by brunagil** [comment]
Enviado/

**Comment by domuserk** [comment]
Olá me chamo Ryan sou de SP me encaixo perfeitamente na vaga!

**Comment by lucaspmarra** [comment]
Vaga ainda está disponível?

**Comment by Qnedy** [comment]
fiz inscrição já tem mó tempão e nenhuma resposta pelo portal de inscrição :/

**Comment by MCiappina** [comment]
Inscrição feita!!

**Comment by domuserk** [comment]
Ola também fiz a inscrição

**Comment by evertonProgramadorCriativo** [comment]
tem algum email para podemos mandar as inscrições

**Comment by evertonProgramadorCriativo** [comment]
passa um desafio primeiro ,para fazer um melhor filtro de pessoas

**Comment by willian2s** [comment]
Inscrição feita

**Comment by jucielly** [comment]
Olá, A vaga ainda está disponível? apesar de estar aberta aqui  não aparece no link :/ , obrigado :D

**Comment by FlavioSantos37** [comment]
Boa Tarde. 
O link esta fora.
