### ISSUE TITLE
[São Paulo] Front-end Developer pleno na Guiabolso

### ISSUE THREAD

**Issue by Sergio-Belitardo** [frontendbr/vagas#3043]
Descrição da vaga
O Guiabolso é uma das maiores startups do Brasil! Ele tem o propósito de mudar a relação das pessoas com o dinheiro, ajudando-as a organizar melhor suas finanças.   Atualmente eles estão lançando um novo produto, o GB Connect,    e estão buscando talentos de front-end para cuidar da evolução e manutenção desse produto em específico, além de desenvolver outros produtos paralelamente.

Como Front-End Developer (Pleno), o que eu vou fazer?

Elaborar novas funcionalidades que brilhem os olhos dos nossos usuários;
Propor melhorias de processo e desenvolvimento e distribuição de nossos produtos;
Colaborar com a área de produto, design e com os desenvolvedores das outras plataformas com o objetivo de ter um produto final com uma visão unificada;
Medir e otimizar a performance e uso de dados.

Local
Escritório, São Paulo - Pinheiros (presencial flexível)

Benefícios

Vale Refeição
Vale Alimentação
Vale Transporte
Assistência Médica
Assistência Odontológica
Seguro de Vida

Diferenciais

Gympass
Escritório Pet Friendly
Sala de jogos
Biblioteca
Água saborizada, frutas e pipoqueira liberadas no escritório

Requisitos
Obrigatórios:

Conhecer stack de desenvolvimento web (REST, WebSockets, Storage, etc);
Ter experiência com cssnext e conhecimento em SASS;
Desenvolver aplicativos web com React e Redux.
Desejáveis:
Ter experiência com produtos digitais e páginas de alto acesso

Contratação
Efetivo (CLT)

Como se candidatar
Por favor, cadastre-se no link: https://byintera.in/dn

Labels
🏢 Flexível
🏢 Presencial
👨 Pleno
⚖️ CLT
💰 5k-10k

**Comment by felipefialho** [comment]
Faltou colocar o titulo e cidade

**Comment by MatheusFlausino** [comment]
Vaga encerrada !
