### ISSUE TITLE
[Rio de Janeiro] Front-end Developer na Capgemini

### ISSUE THREAD

**Issue by Leticiacoelho25** [frontendbr/vagas#3048]
## Requisitos

**Obrigatórios:**
- Inglês Avançado
- Front-end, the key technologies are: 
- JavaScript 
- React 
- Redux 
- (all the visualizations are written in d3) 
- Also, there is a "client-api", that transforms the data in Omnia for visualization purposes, which used Node.js and JavaScript.

**Diferenciais:**
- For the back-end, the key technologies are: 
- Azure 
- DataBricks 
- C# 
- SQL 
- Python 
- Also, GitHub is used for code management, and Azure DevOps for backlogs and run sprints

## Local

Rio de Janeiro - RJ

## Benefícios

- Plano de saúde
- Seguro de vida
- VR ou VA
- Plano odontológico
- Previdência Privada
- VT
- Universidade Corporativa
- Plataforma de idiomas

## Contratação

CLT + Benefícios

## Nossa empresa

Um dos líderes globais em consultoria, serviços de tecnologia e transformação digital, a Capgemini se mantém na vanguarda da inovação, para apoiar seus clientes, de maneira abrangente, em oportunidades de nuvem, tecnologias digitais e plataformas, que estão em constante evolução. Com base em nosso sólido patrimônio de 50 anos e no profundo conhecimento específico em indústrias, apoiamos organizações na concretização de suas ambições de negócios, por meio de uma completa gama de serviços que cobrem desde a estratégia até a operação. A Capgemini tem a convicção de que o valor da tecnologia para os negócios vem das pessoas e por meio delas. Somos uma empresa multicultural de 200 mil profissionais, distribuídos em mais de 40 países. Em 2016, o Grupo Capgemini reportou uma receita global de 12,5 bilhões de euros.

## Como se candidatar

Acesse o Link: https://lnkd.in/dCEM9hF e cadastre-se utilizando o código da vaga - 43708.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após cada processo.
E-mail para contato em caso de não haver resposta: gabriela.francisco@capgemini.com

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível

- Pleno

**Comment by Leticiacoelho25** [comment]
> ## Requisitos
> **Obrigatórios:**
> 
> * Inglês Avançado
> * Front-end, the key technologies are:
> * JavaScript
> * React
> * Redux
> * (all the visualizations are written in d3)
> * Also, there is a "client-api", that transforms the data in Omnia for visualization purposes, which used Node.js and JavaScript.
> 
> **Diferenciais:**
> 
> * For the back-end, the key technologies are:
> * Azure
> * DataBricks
> * C#
> * SQL
> * Python
> * Also, GitHub is used for code management, and Azure DevOps for backlogs and run sprints
> 
> ## Local
> Rio de Janeiro - RJ
> 
> ## Benefícios
> * Plano de saúde
> * Seguro de vida
> * VR ou VA
> * Plano odontológico
> * Previdência Privada
> * VT
> * Universidade Corporativa
> * Plataforma de idiomas
> 
> ## Contratação
> CLT + Benefícios
> 
> ## Nossa empresa
> Um dos líderes globais em consultoria, serviços de tecnologia e transformação digital, a Capgemini se mantém na vanguarda da inovação, para apoiar seus clientes, de maneira abrangente, em oportunidades de nuvem, tecnologias digitais e plataformas, que estão em constante evolução. Com base em nosso sólido patrimônio de 50 anos e no profundo conhecimento específico em indústrias, apoiamos organizações na concretização de suas ambições de negócios, por meio de uma completa gama de serviços que cobrem desde a estratégia até a operação. A Capgemini tem a convicção de que o valor da tecnologia para os negócios vem das pessoas e por meio delas. Somos uma empresa multicultural de 200 mil profissionais, distribuídos em mais de 40 países. Em 2016, o Grupo Capgemini reportou uma receita global de 12,5 bilhões de euros.
> 
> ## Como se candidatar
> Acesse o Link: https://lnkd.in/dCEM9hF e cadastre-se utilizando o código da vaga - 43708.
> 
> ## Tempo médio de feedbacks
> Costumamos enviar feedbacks em até 05 dias após cada processo.
> E-mail para contato em caso de não haver resposta: [gabriela.francisco@capgemini.com](mailto:gabriela.francisco@capgemini.com)
> 
> ## Labels
> #### Alocação
> * Alocado
> 
> #### Regime
> * CLT
> 
> #### Nível
> * Pleno

**Comment by Leticiacoelho25** [comment]
> ## Requisitos
> **Obrigatórios:**
> 
> * Inglês Avançado
> * Front-end, the key technologies are:
> * JavaScript
> * React
> * Redux
> * (all the visualizations are written in d3)
> * Also, there is a "client-api", that transforms the data in Omnia for visualization purposes, which used Node.js and JavaScript.
> 
> **Diferenciais:**
> 
> * For the back-end, the key technologies are:
> * Azure
> * DataBricks
> * C#
> * SQL
> * Python
> * Also, GitHub is used for code management, and Azure DevOps for backlogs and run sprints
> 
> ## Local
> Rio de Janeiro - RJ
> 
> ## Benefícios
> * Plano de saúde
> * Seguro de vida
> * VR ou VA
> * Plano odontológico
> * Previdência Privada
> * VT
> * Universidade Corporativa
> * Plataforma de idiomas
> 
> ## Contratação
> CLT + Benefícios
> 
> ## Nossa empresa
> Um dos líderes globais em consultoria, serviços de tecnologia e transformação digital, a Capgemini se mantém na vanguarda da inovação, para apoiar seus clientes, de maneira abrangente, em oportunidades de nuvem, tecnologias digitais e plataformas, que estão em constante evolução. Com base em nosso sólido patrimônio de 50 anos e no profundo conhecimento específico em indústrias, apoiamos organizações na concretização de suas ambições de negócios, por meio de uma completa gama de serviços que cobrem desde a estratégia até a operação. A Capgemini tem a convicção de que o valor da tecnologia para os negócios vem das pessoas e por meio delas. Somos uma empresa multicultural de 200 mil profissionais, distribuídos em mais de 40 países. Em 2016, o Grupo Capgemini reportou uma receita global de 12,5 bilhões de euros.
> 
> ## Como se candidatar
> Acesse o Link: https://lnkd.in/dCEM9hF e cadastre-se utilizando o código da vaga - 43708.
> 
> ## Tempo médio de feedbacks
> Costumamos enviar feedbacks em até 05 dias após cada processo.
> E-mail para contato em caso de não haver resposta: [gabriela.francisco@capgemini.com](mailto:gabriela.francisco@capgemini.com)
> 
> ## Labels
> #### Alocação
> * Alocado
> 
> #### Regime
> * CLT
> 
> #### Nível
> * Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
