### ISSUE TITLE
[SÃO PAULO] Front-end Magento Developer na JUST DIGITAL 

### ISSUE THREAD

**Issue by alicesrossi** [frontendbr/vagas#3049]
## Local

Presencial, na Avenida Paulista!

## Benefícios

- Plano de saúde
- Plano odontológico
- Seguro de vida
- VR de R$ 596/mês
- Vale Transporte

#### Diferenciais

- Home offices semanais
- Café da manhã
- Parceria com o SESC, FIAP e Gympass.

## Requisitos

HTML5 / CSS3 / JS / pré-processadores;
Conhecimento avançado com Magento
Versionamento com GIT;
Ótimo conhecimento em frameworks Javascript;
Consumos de API;
Testes unitários e comportamentais.

## Contratação

CLT a combinar

## Nossa empresa

Acreditamos no Design para criar experiências memoráveis em tudo o que fazemos e na engenharia de software para tornar isso possível.
Quando falamos em experiência para impactar pessoas, vemos isso nos produtos e serviços que entregamos, na relação com nossos clientes enquanto trabalham com a gente, quando os os clientes dos nossos clientes usam nossos produtos.

Gostamos de pessoas proativas que somem ao time de desenvolvimento auxiliando na arquitetura da solução e preze pela qualidade do software como um todo.

## Como se candidatar

Por favor cadastre-se no link https://justdigitalbr.recruitee.com/o/dev-front-end-magento-pleno

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após cada processo.

## IMPORTANTE
Ressaltamos que por conta do COVID-19, todas nossas pessoas estão de home office. Inclusive RH e líderes técnicos. Dessa forma, o processo será feito inteiramente via hangouts! 

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno

### Tags
- Dev
- SP
- vagas
- TI

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
