### ISSUE TITLE
[São Paulo] Front-End Developer (AngularJS)

### ISSUE THREAD

**Issue by GustavoCostaW** [frontendbr/vagas#305]
## Descrição da vaga

Desenvolvedor Front-end [Pleno/Senior] 
Experiência em aplicações AngularJS >= 1.5.x para desenvolvimento de e-commerce e sistemas.

## Local

Remoto e Escritório, São Paulo - Rua da Consolação - (Prox Metrô República)

## Benefícios

- Horário Fléxivel
- Sim, você pode trabalhar remoto até 2 dias na semana!
- Equipe bem humorada
- Se você toca algum instrumento (Violão/ Baixo / Guitarra / Bateria) poderá fazer um som junto com a turma nos finais de semana!
- Ótima localização de escritório (Ao lado do Mackenzie) lugares baratos para almoço, metrô próximo, etc...
- Possibilidade de participação % no projeto

## Requisitos

**Obrigatórios:**
- Experiência COMPROVADA no desenvolvimento de aplicações AngularJS
- **Javascript** (Tentamos focar o máximo de nosso código na linguagem e não depender de um framework pra lógica e modelo do negócio)
- Você DEVE ter um bom dominio em HTML e CSS
- Noção de consumo de API/REST

**Desejáveis:**
- ES6
- Grunt/Gulp
- Git
- Padrões de Projeto

**Diferenciais:**

- Angular (>= 2.x version)
- Typescript
- PHP
- MySQL

## Contratação

PJ a combinar

## Nossa empresa

A bitshopp é uma plataforma de ecommerce de alta performace mobile. 
Através da bitshopp você cria sua própria loja virtual mobile e vende seus produtos com a maior taxa e conversão e as menores taxas do mercado.

## Como se candidatar

Por favor envie um email para admin@bitshopp.com com seu CV anexado e linkedin se possuir - enviar com o assunto: Vaga Front-End

**Comment by LFeh** [comment]
Vaga bacana o/

**Comment by GustavoCostaW** [comment]
Valeu! @LFeh add Pleno também! :-)
