### ISSUE TITLE
[São Paulo - SP] Front-end no Itaú Unibanco

### ISSUE THREAD

**Issue by kikomesquita** [frontendbr/vagas#3051]
## Descrição da vaga

Atuar em células ágeis e multidisciplinares com engenharia e desenvolvimento de aplicações.
Testes unitários, Testes integrados.
Execução de code-reviews.
Direcionar a evolução da plataforma tecnológica.
Participar de todo o ciclo das aplicações desde a concepção até a implantação.

## Local

São Paulo - Conceição (junto a estação de metrô)

## Benefícios

- Plano de saúde
- Seguro de vida
- VR, VA
- Auxílio creche
- Bolsa-auxílio
- PLR
- Diversas parcerias com descontos para universidades, produtos, serviços, etc.

#### Diferenciais

- Dress code leve
- Horário flexível (podemos combinar sempre que necessário)
- Trabalhar em soluções que impactam milhões de pessoas ;)

## Requisitos

**Obrigatórios:**

- Experiência em desenvolvimento de Frond-end(Javascript,CSS, HTML);
- Experiência em Angular ou frameworks/libs similares(VueJS, React, etc);
- Experiência com GIT, Artifactory, Jira;
- Conhecimento de padrões de desenvolvimento(MVVM, MVC, etc);
- Vivência em projetos que utilizam metodologia ágil;
- Testes unitários, testes integrados;

**Desejáveis:**

- Sólidos conhecimentos de Orientação a Objetos;
- Conhecimento em outras tecnologias(Android, iOS, etc);
- Conhecimento de pré compiladores CSS(SASS, LESS, etc);
- Ferramentas de build de front(Webpack, Gulp, Grunt, etc);
- Ferramentas de APM(AppDynamics, Dynatrace, New Relic, etc);
- Ferramentas de centralização de Logs(Splunk, GrayLog, etc);

**Diferenciais:**

- Certificações na área de tecnologia;
- Pós-graduação e/ou especialização

## Contratação
- CLT

## Nossa empresa

Venha trabalhar no Itaú Unibanco!
Queremos o caminho que ninguém usou, porque ele geralmente leva aonde ninguém foi. Queremos os inconformados, os inquietos, os indignados, apaixonados por tecnologia. Queremos os impacientes e os inventivos.
Queremos aqueles com vontade de mudar o mundo visando o melhor para o cliente. Não queremos você apenas por achar que você tem a nossa cara.
Queremos ter um pouco da sua também. Queremos você!

## Como se candidatar

Enviar CV via inbox no LinkedIn:
[https://www.linkedin.com/in/francisco-mesquita/](https://www.linkedin.com/in/francisco-mesquita/)

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
