### ISSUE TITLE
[Fortaleza] Front-End Developer na [AGEFIS]

### ISSUE THREAD

**Issue by brunoabmoreira** [frontendbr/vagas#3052]
## Descrição da vaga
Vaga para desenvolvimento de software próprio.

## Local
Fortaleza - CE

## Benefícios
- Salário: R$: 3.157,22
- Plano de saúde
- Auxílio Refeição
- CLT

## Requisitos
**Obrigatórios:**
Conhecimentos em JAVA / JS (Angular / React)
Conhecimentos em postgreSQL

**Desejáveis:**
Conhecimentos em React Native.

## Contratação
CLT

## Nossa empresa

A Agencia de Fiscalização de Fortaleza é uma autarquia municipal responsável pela fiscalização de obras, posturas, vigilância sanitária, defesa do consumidor, meio ambiente, etc... desenvolvemos nosso próprios sistemas buscando melhorar cada vez mais nossos serviços.

#### Como se candidatar
Por favor envie um email para bruno.moreira@agefis.fortaleza.ce.gov.br com seu CV anexado - enviar no assunto: Vaga Front-End Developer

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by Afiodev** [comment]
Tenho interesse, estou a 2 anos no mercado... sou de Fortaleza mas gostaria de trabalhar remoto

**Comment by glerisonlima** [comment]
a vaga ainda esta disponível ?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
