### ISSUE TITLE
[São Paulo] Junior Front-end Developer na [Multiedro]

### ISSUE THREAD

**Issue by ebcasella** [frontendbr/vagas#3053]
## Descrição da vaga

Desenvolvimento de aplicações Web utilizando serviços do Google Cloud Platform (GCP)

## Local

São Paulo - Itaim Bibi

## Benefícios

- Salário compatível com o mercado
- VT + VR + Plano odontológico + Plano de saúde
- Auxílio plataforma de cursos Alura
- Bônus de participação nos lucros
- Horário de trabalho comercial com possibilidade de flexibilização

## Diferenciais

- Você atuará em uma área estratégica dentro de nossa empresa e terá grande espaço para crescimento
- Apoio em estudos e certificações

## Requisitos

**Tecnologias:**
- HTML, CSS, JS, Vue.js, Vuetify

**Desejáveis:**
- git
- criação de testes
- qualidade e padrões de código 
- metodologias ágeis 

## Contratação

CLT

## Nossa empresa

A Multiedro é uma empresa que desde 2010 trabalha 100% com soluções em nuvem com a seguinte abordagem: "A Tecnologia tem o poder de transformar os negócios das empresas". Para ajudar nossos clientes a se transformarem digitalmente, temos como diferencial nossas equipes de Serviços e Desenvolvimento, além de sermos importantes parceiros de líderes de mercado em nuvem, como Google e Salesforce.

## Como se candidatar

Acesse o link e preencha o formulário:
http://tiny.cc/RHUN_FE

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Júnior

**Comment by alexandreramosdev** [comment]
Somente alocado? aceita remoto

**Comment by fogeid** [comment]
Enviado!

**Comment by ebcasella** [comment]
Somente alocado.

**Comment by Seveshy** [comment]
Enviado.

**Comment by ebcasella** [comment]
Vaga em holding.
