### ISSUE TITLE
[Curitiba] Front-end Developer na Leads2b

### ISSUE THREAD

**Issue by BiaLeads2b** [frontendbr/vagas#3054]
## Descrição da vaga

Projeto bem foda em **VueJS**. Estamos criando nossa própria biblioteca de componentes (com base nos preceitos de design system), aplicando as noções de atomic design e levando muito a sério o gitflow. Além do fato de focarmos todas as nossas energias na melhoria do produto, então a abertura para novas idéias, técnicas e stacks é 100% ;)

## Local

Escritório em Curitiba - PR no Bigorrilho (região central)

## Benefícios

- Plano de saúde s/ mensalidade nem coparticipação
- Plano odonto
- VR de R$ 17/dia
- Descontos em restaurantes na região

#### Diferenciais

- Horário flexível
- Pagamento por hora
- Tem bera quando a galera atinge a meta nas sextas
- Preparando o sistema para internacionalizarmos ASAP

## Requisitos

**Obrigatórios:**
- Experiência de +2 anos como Front-end 
- HTML5, CSS3
- Já ter estudado / feito projetos / freelas em VueJS

**Desejáveis:**
- VueJS
- NPM
- Automatizadores de tarefas (Gulp e Bower)
- Biblioteca de componentes HTML (design system interno)

**Diferenciais:**
Manjar / já ter estudado sobre:
- Atomic Design
- Base de dados relacional e não relacional
- Docker
- TDD
- Web services e APIs

## Contratação

PJ com benefits e férias remuneradas

## Nossa empresa

Aqui na Leads criamos um software que faz a gestão comercial das empresas de uma ponta à outra, automatizando tudo! E somos únicos nesse planeta, por sermos uma solução all-in-one para a área de vendas, enquanto todos oferecem soluções parciais. E estamos crescendo absurdamente (de 20 leaders em jan 2019 para 140 esse mês :D)

## Como se candidatar

Se inscreva aqui please:
https://leads2b.gupy.io/jobs/187347

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: beatriz.lima@leads2b.com

## Labels
<Alocado>
<Pleno>
<Sênior>
<Curitiba>

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
