### ISSUE TITLE
[São Paulo] Front-end Developer na McCann Health

### ISSUE THREAD

**Issue by tiagords** [frontendbr/vagas#3055]
## Descrição da Vaga
Somos a maior agência Health do Brasil e estamos em busca de profissionais frontend com conhecimentos sólidos em Vue.js para atuar em um projeto de grande impacto na população brasileira.

## Requisitos
- Experiência de +2 anos como Front-end
- HTML5, CSS3, JavaScript
- Vue.JS
- Nuxt.js
- Sass

## Desejáveis:
- NPM

## Contratação
- PJ

## Nossa Empresa
A McCann Health é a comunidade de especialistas em saúde e bem-estar mais conectada do mundo e unida por um propósito: ajudar nossos clientes a desempenhar um papel significativo na vida das pessoas. Esse compromisso concentra nossos +1.900 funcionários em todo o mundo no desenvolvimento de ideias que mudam a vida e que melhoram a saúde das pessoas. http://mccannhealth.com.br/

## Como se Candidatar
Por favor, envie um email para tiago.rodrigues@mccannhealth.com.br com seu CV em anexo, portfólio (projetos em Vue.js) e pretensão salarial.

## Tempo Médio de Feedbacks
Feedbacks em até 10 dias.

## Local
Nosso escritório fica em:
Av. Chedid Jafet, 75 - Vila Olimpia
São Paulo - SP
04551-010

## Diferenciais
- Horário flexível
- Home Office

## Labels
- Alocado
- PJ
- Pleno
- Sênior
- Remoto
- Home Office

**Comment by henriquesan14** [comment]
100% remoto?

**Comment by rafaelkendrik** [comment]
Grato @tiagords, email enviado!

**Comment by tiagords** [comment]
> 100% remoto?

Oferecemos as duas opções. O profissional que escolhe. =)
