### ISSUE TITLE
[Remoto] Front-end Developer React Js / React native na Joyjet

### ISSUE THREAD

**Issue by PachecoRaphael** [frontendbr/vagas#3058]
##  Descrição da vaga

Hello, 

Joyjet is looking for a Front-end developer in React js, We have a lot of different projects from e-commerce to interns app for businesses.

If you know also React native it´s good as we also have mobile projects going on.

Big part of the team speaks Portuguese but we all communicate in English via messages. Only the calls with the team are in Portuguese. 

If you are interested please do this test and send us the repo URL so we can check: https://bitbucket.org/lixao/tech-interview/src/master/frontend/

## Local

Remoto

## Benefícios

- Plano de saúde
- Free course to study

## Requisitos

**Obrigatórios:**
- 3 years of experience as a front-end developer
- Java script
- Typescript
- React
- HTML/CSS
- GIT

**Desejáveis:**
- Knowledge in React native
- Knowledge in Python (Framework: Django)

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para jobs@joyjet.com com seu CV anexado - enviar no assunto: VAGA FRONT-END Reactjs/React native

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

Test asked to all new members: https://bitbucket.org/lixao/tech-interview/src/master/frontend/

## Labels

- PJ
- Pleno
- Remoto
- Reactjs
- Typescript

**Comment by fafa1** [comment]
Vocês têm vaga pra Vue.js?

**Comment by LucasMallmann** [comment]
@PachecoRaphael, might the test be posted on Github acc instead of a Bitbucket one?

**Comment by PachecoRaphael** [comment]
> Vocês têm vaga pra Vue.js?

No sorry we focus on React Js

**Comment by PachecoRaphael** [comment]
> @PachecoRaphael, might the test be posted on Github acc instead of a Bitbucket one?

Sure no problem for GitHub !

**Comment by LucasMallmann** [comment]
Hey @PachecoRaphael why did you close this issue? Is the job position already fulfilled?
