### ISSUE TITLE
[Remoto] Front-end Developer React Js na Joyjet

### ISSUE THREAD

**Issue by PachecoRaphael** [frontendbr/vagas#3059]
##  Descrição da vaga

Hello, 

Joyjet is looking for a Front-end developer in React Native, We have a lot of different projects from e-commerce to interns app for businesses.

If you know also React Js it´s good as we also have mobile projects going on.

A big part of the team speaks Portuguese but we all communicate in English via messages. Only the calls with the team are in Portuguese. 

If you are interested please do this test and send us the repo URL so we can check:

https://bitbucket.org/lixao/tech-interview/src/master/frontend/
(The use of Typescript is +)

## Local

Remoto

## Benefícios

- Plano de saúde
- Free course to study

## Requisitos

**Obrigatórios:**
- 3 years of experience as a front-end developer
- Java script
- Typescript
- React Js
- React Native
- HTML/CSS
- GIT

**Desejáveis:**
- Knowledge in Python (Framework: Django)

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para jobs@joyjet.com com seu CV anexado - enviar no assunto: VAGA FRONT-END React native / Reactjs

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

Test asked to all new members:

https://bitbucket.org/lixao/tech-interview/src/master/frontend/

## Labels

- PJ
- Pleno
- Remoto
- ReactNative
- Typescript

**Comment by ribeiroevandro** [comment]
Email enviado!

**Comment by rodgomesc** [comment]
Qual faixa salarial?

**Comment by PachecoRaphael** [comment]
> what salary range for this job? What about stability in the company? Is a temporary project? do you give opportunities to grow in the Company?

Salary range will only depend on your experience and the test done. The company has more than 16 years. It´s not for a temporary project we like to have a team that work in the long term together. We are a small agency so you can have grow fast as tech leader if you show that you´re capable of it yes.

**Comment by rodgomesc** [comment]
my skills meet the requirements for this vacancy, including experience with python + django, but I have no knowledge with typescript, this would influence a lot
 in the hiring process?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
