### ISSUE TITLE
[São Paulo] Desenvolvedor(a) Front-end Pleno

### ISSUE THREAD

**Issue by allangrds** [frontendbr/vagas#306]
## Descrição da vaga
O profissional será responsável pelo front end de uma startup de tecnologia no ramo de logística.

## Local
Home office / Presencial(São Paulo,  Pompeia)

## Requisitos

**Obrigatórios:**
- HTML5
- CSS3
- Javascript(+2 anos)
- Front-end package managers (Bower, NPM)
- Task Runners (Grunt ou Gulp)
- React(+ 1 ano)

**Desejáveis:**
- Testes funcionais
- Testes unitários

## Contratação
PJ a combinar

## Nossa empresa
A CARGOBR é um empresa de tecnologia com foco em desenvolver soluções para a área de transportes e logística. Para saber mais sobre nós acesse https://www.youtube.com/watch?v=SYilGNoTxmM

## Como se candidatar
Enviar email para ti@cargobr.com com seu CV anexado ou portfolio ou perfil do Github - assunto: Vaga Front End.

**Comment by RuanPissinati** [comment]
Nome: Ruan Pissinati
Idade: 23 anos
Estado Civil: Solteiro
Pretensão Salarial: 2,500 a 3000.
Trabalho com desenvolvimento de sites responsivos a 2 anos,
tenho experiência em trabalhar com:

Code
- Algoritiomo
- HTML
- CSS
- Bootstrap (Para layouts Responsivos).
- SASS
- JavaScript
- Biblioteca Jquery
- Angular (Basico)
- GIT versionamento e repositório.
- Wordprees
- SQL com javascript
- PHP (Basico)

Design
- UI/UX desing
- Photoshop
- Illustrator
- Corel Draw

Alguns dos meus trabalhos:

Escritorio de advocacia:
http://aneves.com.br/

ASN tendencias do Mercado:
http://www.asntendencias.com.br/

Site do app Joinder-me:
http://joinder.me/

Time Line Confidence de 20 anos
http://simulacao.tihum.com/timeline/

Redes:
Github
linkedin

**Comment by ygorlazaro** [comment]
Opa, tudo bem? Essa vaga é totalmente remoto?

**Comment by allangrds** [comment]
@ygorlazaro Bem, e você ? É sim, jovem :).

**Comment by JCMais** [comment]
Enviado!

**Comment by MathMesquita** [comment]
Enviado :D
