### ISSUE TITLE
[Remoto] Junior Front-end Developer (React) na CargoBR

### ISSUE THREAD

**Issue by marcelabomfim** [frontendbr/vagas#3060]
## Descrição da vaga

Você irá atuar no desenvolvimento front-end de nossas aplicações, bem como especificação de tarefas, análise de esforço e estimativas de prazos e pontuação(planing poker).
Além disso deverá ser feita a aplicação de testes unitários e testes end-to-end, code-reviews e execução de deploys.

## Local

Remoto ou Escritório, São Paulo - Alphaville.

## Benefícios

- Salário compatível com o mercado
- Horário de trabalho comercial com possibilidade de flexibilização
- Plano de saúde parcialmente custeado

## Requisitos

**Obrigatórios:**
- HTML5;
- CSS3;
- Javascript;
- React;
- Integração com API's Rest;
- Controle de versionamento com GIT.

**Desejáveis:**
- Testes Unitários;
- Testes E2E;
- Redux/Flux;
- Styled-Components;
- Gatsby.

**Diferenciais:**
- Experiência em processos ágeis (Scrum).
- Experiência de 1 ano ou mais com React.

## Contratação

PJ a combinar

## Nossa empresa

Somos uma startup pioneira em cotação e contratação de frete online no Brasil! Nossa grande paixão é tecnologia e nossa vocação é unir embarcadores com transportadoras, desburocratizar o processo e facilitando a comunicação entre eles. Nós vamos digitalizar todo o processo logístico! Sabemos disso porque acordamos e vamos dormir pensando em como vamos melhorar a vida dos nossos parceiros, não por obrigação, mas porque realmente gostamos disso. Aliás, fazemos sempre o que gostamos, afinal, a coisa mais importante é ser feliz e acreditamos que ninguém é feliz fazendo algo que não gosta.

## Como se candidatar

Enviar email para vagas@cargobr.com com seu CV anexado ou portfolio ou perfil do Github - assunto: Junior Front-end Developer.

## Labels
- PJ
- Júnior
- Remoto

**Comment by jgalmeida93** [comment]
Enviado!

**Comment by avrcoelho** [comment]
Enviado

**Comment by GuilhermeLis** [comment]
enviado

**Comment by Henriquepb22** [comment]
Enviado!

**Comment by maxarouca** [comment]
Enviado!

**Comment by drrh12** [comment]
Enviado! Ajudei a desenvolver uma plataforma de cotação de fretes muito parecida com a de vocês :)

**Comment by pablojr17** [comment]
Enviado

**Comment by diegohyenna** [comment]
Queria muito entender por que vocês escrevem "enviado" aqui. Se mandou o e-mail direitinho pra empresa, é só aguardar o retorno.

**Comment by domuserk** [comment]
Olá me chamo Ryan me encaixo perfeitamente na vaga!

**Comment by Afiodev** [comment]
Enviado

**Comment by juniorfernandesdev** [comment]
Enviado!

**Comment by teixeira83** [comment]
Enviado!
