### ISSUE TITLE
[Porto Alegre] Front-end Developer na SOUTH SYSTEM

### ISSUE THREAD

**Issue by kaueny** [frontendbr/vagas#3061]
A SOUTH SYSTEM está em busca de um(a) Desenvolvedor(a) Front-End que queira fazer parte do nosso propósito de impulsionar as pessoas para inovar o mundo. Para fazer parte do time, há algumas skills que valorizamos muito, e não estamos falando apenas de tecnologia, nós valorizamos profissionais que respeitem o próximo e suas diferenças, que sejam leais e responsáveis com as entregas e com as pessoas. A colaboração e engajamento devem fazer parte do dia a dia para que o resultado seja eficaz e que tenha sede de aprendizado para trabalhar com inovação contínua.

**Procuramos uma pessoa que tenha experiência com:**

- React
- Angular

**Será um diferencial bacana:**

- Conhecimento em web-components

**LOCAL:** Porto Alegre/RS 

Se interessou pela oportunidade e curte ambientes que invistam no teu desenvolvimento? Então não perde tempo e envia o teu currículo para kaueny.martins@southsystem.com.br

**Comment by acarolsf** [comment]
Aceita remoto?

**Comment by kaueny** [comment]
@acarolsf a vaga em questão é para atuar presencialmente em Porto Alegre, entretanto, devido ao atual cenário do coronavírus, a pessoa desenvolvedora ficaria home office, mas apenas enquanto estamos em quarentena

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
