### ISSUE TITLE
[Porto Alegre] Front-end Developer na SouthSystem

### ISSUE THREAD

**Issue by AlineLarruscaim** [frontendbr/vagas#3064]
A SOUTH SYSTEM está em busca de um Front-End Developer que queira fazer parte do nosso propósito de impulsionar as pessoas para inovar o mundo. Para fazer parte do time, há algumas skills que valorizamos muito, e não estamos falando apenas de tecnologia, nós valorizamos profissionais que respeitem o próximo e suas diferenças, que sejam leais e responsáveis com as entregas e com as pessoas. A colaboração e engajamento devem fazer parte do dia a dia para que o resultado seja eficaz e que tenha sede de aprendizado para trabalhar com inovação contínua.

Para essa oportunidade, o profissional atuará com:

ReactJS
Redux

Seria um diferencial bacana:

SaaS e NodeJS

## Contratação

Cooperado ou PJ

## Nossa empresa

Somos uma empresa focada nos desafios e resultados de nossos clientes. Alinhamos as nossas estratégias as de nossos parceiros, garantindo assim maior sinergia na busca dos objetivos planejados. Trabalhamos com grandes projetos do ramo financeiro.

## Como se candidatar

Por favor envie um email para aline.larruscaim@southsystem.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

## Nível da vaga
Pleno/ Sênior

**Comment by rodrigocdfidencio** [comment]
Boa tarde Aline a vaga é presencial ou remoto?

**Comment by AlineLarruscaim** [comment]
> Boa tarde Aline a vaga é presencial ou remoto?

Boa tarde Rodrigo, 
Inicialmente, devido a toque questão que estamos enfrentando, será remoto. Mas o projeto é para ficar alocado presencialmente no cliente

**Comment by rodrigocdfidencio** [comment]
Ok, obrigado

Em seg, 30 de mar de 2020 13:34, AlineLarruscaim <notifications@github.com>
escreveu:

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
