### ISSUE TITLE
[São Paulo] Web Frontend Developer na DOMVS

### ISSUE THREAD

**Issue by thaisvilladal** [frontendbr/vagas#3066]
Descrição da vaga
Para atuar no desenvolvimento Frontend em empresa de tecnologia com foco em atendimento a clientes do segmento de seguros, varejo e financeiro/bancos.

Local
Presencial, zona sul de São Paulo, SP

Benefícios
Plano de Saúde Individual, Plano Odontológico, Vale Transporte, Vale Refeição ou Alimentação

Requisitos
Experiência no desenvolvimento com foco em HTML 5.0, CSS 3.0, Javascript.
Domínio em React.
Ter atuado com TDD.

Desejáveis:
Conhecimentos de UX
Conhecimento de projetos ágeis Scrum

Contratação
PJ e/ou CLT por prazo indeterminado - a combinar

Observação importante: O processo ocorrerá de forma remota e o início do candidato também será de forma remota até o fim da quarentena por conta da pandemia.

Nossa empresa
A DOMVS possui experiência em gestão de empresas, onde efetivamente participam de decisões de negócios embasadas pela utilização estratégica da tecnologia da informação.
Estamos presentes no Brasil e também em Portugal.

Como se candidatar
Por favor envie um e-mail para consultoria_villadal@domvs.com.br com seu CV anexado - enviar no assunto: FRONT ZS ou entrar em contato através do whatsapp da consultoria 11 97386-5774

Tempo médio de feedbacks
Costumamos enviar feedbacks em até 05 dias úteis após cada processo.
E-mail para contato em caso de não haver resposta: consultoria_villadal@domvs.com.br

Alocação
Alocado
Regime
CLT
PJ
Nível
Pleno
Sênior
Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
