### ISSUE TITLE
[Valinhos, SP] React Júnior e Pleno na Kroton

### ISSUE THREAD

**Issue by iagobyintera** [frontendbr/vagas#3069]
**Impacte a vida de milhões!** Estamos transformando histórias, vidas e o futuro! Aqui, tradição e liderança não são traduzidas em modelos antigos e 'zona de conforto'. Pelo contrário. **Temos em nosso DNA a inovação e o dinamismo** de uma jovem startup. **Nós somos uma das maiores empresas de educação** e buscamos nos tornar o **maior grupo de EdTechs do Brasil!**

Atualmente nós trabalhamos com **Javascript ES6, React, AJAX e REST**. Essas tecnologias com **pessoas com propósito** e dispostas é o que nos faz **estar entre as melhores do Brasil**. Serão bem vindos também conhecimentos em SEO, Git e Metodologias Ágeis.

A contratação será feita em **regime CLT** com **horário flexível**. O **trabalho é presencial** e estamos na Alameda Maria Tereza, em Valinhos!

**Faça parte do time! -** https://byintera.in/timekroton

**Comment by caiquesandrade** [comment]
Como faço para me candidatar @iagobyintera ? Eu estudo React por conta propria e me aperfeiçoei na minha pós graduação em Desevolvimento Web Fullstack pela PUC Minas. Minha maior experiência é como back end PHP, mas gostaria de ingressar em novas oportunidades, principalmente com Reac.

**Comment by felipefialho** [comment]
@iagobyintera A vaga está totalmente fora do template. Por favor corrigir até o fim do dia, obrigado.

**Comment by diogomoretti** [comment]
Vaga não corrigida. Vamos fechar até entrar no template.
