### ISSUE TITLE
[São Paulo] Front-End Developer 

### ISSUE THREAD

**Issue by 84gio** [frontendbr/vagas#307]
Descrição da Vaga:
Criação de interfaces visuais para novas aplicações de negócios da empresa.

Local:
São Paulo - Chácara Sto. Antônio (próximo à estação Granja Julieta)

Benefícios:
- Seguro de Vida
- Assistência Médica Porto Seguro
- Vale Refeição
- Cartão de Descontos

Requisitos:
- 02 anos de experiência com desenvolvimento WEB: HTML5, CSS3, JavaScript e noções de Asp.Net MVC.
- Conhecimentos nos frameworks Angular, React.
- Idioma: Inglês avançado

Contratação: CLT full

Nossa empresa:
A Talent Group é uma consultoria especializada em Recrutamento e Seleção, Aplicação de Testes Psicológicos e Motivacionais e Terceirização de Profissionais com o objetivo de atender a necessidade específica de cada cliente, através de serviços diferenciados e customizados.Nossos diferenciais para a prestação de serviços estão baseados na assertividade, agilidade, comprometimento, qualidade e transparência que oferecemos aos nossos clientes e colaboradores.

Por favor envie um email para giovanna.braga@talentgroup.com.br com seu CV anexado - enviar no assunto: Vaga FrontEnd

**Comment by gabrielferreiraa** [comment]
Possibilidade de remoto ?

**Comment by 84gio** [comment]
Bom dia Gabriel,

Nesse caso não há possibilidade de trabalho remoto.


Att,

[http://www.talentgroup.com.br/assinaturas/talentgroup.jpg]

Giovanna B. R. Kirschner
Consultora de R&S
(11) 4052-4300 (pabx)
(11) 4095-5014 (ramal)
giovanna.braga@talentgroup.com.br<mailto:giovanna.braga@talentgroup.com.br>
www.talentgroup.com.br<http://www.talentgroup.com.br/>







De: Gabriel Ferreira [mailto:notifications@github.com]
Enviada em: segunda-feira, 10 de abril de 2017 14:17
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: Giovanna B. R. Kirschner <giovanna.braga@talentgroup.com.br>; Author <author@noreply.github.com>
Assunto: Re: [frontendbr/vagas] Front-End Developer [São Paulo] (#307)


Possibilidade de remoto ?
