### ISSUE TITLE
[Barueri] Front-end Developer na QUOD

### ISSUE THREAD

**Issue by michelleasouza** [frontendbr/vagas#3071]
## Descrição da vaga

Fintech QUOD localizada em Alphaville busca por Front-end Developer.
Desenvolvimento em PHP e conhecimento em Laravel, Banco de dados SQL Server e MySQL, Git, HTML, Bootstrap, Javascript e CSS, JQuery, React, Angular, NodeJS.

O profissional deve possuir boa comunicação, entendimento do negócio e saber levantar os requisitos de demandas.

**Rede de relacionamentos:**
- Fornecedores internos e externos
- Clientes internos e externos

**Atividades:**
- Manutenção de portais (responsabilidade total)
- Diagnóstico e resolução de problemas (responsabilidade total)
- Desenvolver protótipos e mockups (responsabilidade parcial)
- Criação de novos portais/websites (responsabilidade total)

## Local

- Escritório em Alhpaville - Barueri 

## Benefícios

- Plano de saúde SulAmerica
- Plano odontológico SulAmerica
- Seguro de vida
- VR de R$ 24,60/dia

#### Diferenciais

- Home office 1 vez na semana
- Horário flexível
- Sem dress code
- Sala de jogos

## Requisitos

**Obrigatórios:**
- PHP 7+
- Laravel 5+
- SQL ANSI (SQL Server/MySQL)
- Bootstrap / HTML / CSS / Javascript
- React, Angular
- Git

**Desejáveis:**
- Experiência de 2 anos ou mais como front-end developer

**Diferenciais:**
- n/a

## Contratação

CLT regime terceirizado, contratação pela da empresa Mendes Talent (consultoria de RH)

## Nossa empresa

A Quod nasceu de uma vontade transformadora. Viemos para impulsionar o Cadastro Positivo no Brasil. A Quod foi criada a partir da união dos cinco maiores bancos do país e da necessidade de lançar um novo prisma - mais positivo - sobre o mercado de informações de crédito. 

Maiores informações sobre a empresa: http://www.quod.com.br

## Como se candidatar

Por favor envie e-mail com CV e pretensão salarial para: michelle.a@mendestalent.com.br - escrever no assunto: Vaga - Front-end Developer  

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 04 dias após cada processo.

#### Alocação
- Alocado

#### Regime
- CLT Terceirizado (contratado pela consultoria Mendes Talent)

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
