### ISSUE TITLE
[Remoto] Angular Developer/Front-end na Visionnaire Tecnologia 

### ISSUE THREAD

**Issue by raulbalestra** [frontendbr/vagas#3073]
Vaga para projeto temporário ( possibilidade de ser extendido)
empresa: Visionnaire.com.br

Business
The customer is building a command control software for security control rooms (it would be used by companies providing security services for stores, other facilities). They're currently closing the seed round and planning to launch v.1.0 of their software by August.
The lead has the MVP ready, running a pilot collaboration with a SA-based company (a couple of locations). The MVP has just the CV side, no front end at this time - sends notifications about potential threats via Telegram. 
A Canadian team are currently working on the product, managing the development by breaking it down into sprints and using GitHub issues.
Current tech stack: Python/Flask, OpenCV, PostgreSQL, AWS.
Angular is planned for the front end (the decision's not set in stone yet though, can be discussed).
Requirements:
•	Great spoken English would be a must-have
•	Strong knowledge of foundation web technologies: HTML5, CSS, and JavaScript
•	Experience using Git version control
•	Ability to develop fully responsive websites
•	Create clean, well-organized and structured code
•	Advanced debugging and troubleshooting skills
•	Ability to scope and timeline a technical front-end project with the understanding and ability to gather the necessary inputs on their own
•	Ability to make the right technical decisions to build a solution meeting the requirements (expertise in technical options/approaches combined with project requirements and constraints)
•	Can work autonomously and self-initiated
•	A team player! We want people who are humble, hungry, and smart!

Nice to have:
•	Python knowledge
•	Flask knowledge
•	PostgreSQL knowledge
•	AWS knowledge
Timeframe & budget
Start: end of April/beginning of May.
Duration: 2-3 months, could be longer.
Rate: as close to R$11k /month

contato: raul.balestra@visionnaire.com.br

**Comment by raulbalestra** [comment]
Vacancy still available!

**Comment by raulbalestra** [comment]
Vacancy has been closed.

**Comment by mrangeljr** [comment]
I'll go to send now ... :(
