### ISSUE TITLE
[Porto Alegre] React Developer na SOUTH SYSTEM

### ISSUE THREAD

**Issue by kaueny** [frontendbr/vagas#3074]
## Descrição da vaga

A SOUTH SYSTEM está em busca de uma pessoa desenvolvedora Front-End Pleno/Sênior que queira fazer parte do nosso propósito de impulsionar as pessoas para inovar o mundo. Para fazer parte do time, há algumas skills que valorizamos muito, e não estamos falando apenas de tecnologia, nós valorizamos profissionais que respeitem o próximo e suas diferenças, que sejam leais e responsáveis com as entregas e com as pessoas. A colaboração e engajamento devem fazer parte do dia a dia para que o resultado seja eficaz e que tenha sede de aprendizado para trabalhar com inovação contínua.

## Local

Porto Alegre/RS (após o cenário do coronavírus, será presencial)

## Requisitos

**Procuramos alguém que tenha experiência profissional com:**

-  React
- Angular

**Será um diferencial bacana:**

- Conhecimento em web-components

## Contratação

PJ ou cooperado

## Nossa empresa

https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-SOUTHSYSTEM-EI_IE2433278.13,24.htm

## Como se candidatar

Se interessou pela oportunidade e curte ambientes que invistam no teu desenvolvimento? Então não perde tempo e envia o teu currículo para kaueny.martins@southsystem.com.br

## Labels

- Alocado
- Pleno
- Sênior

**Comment by vachterberg1** [comment]
São vagas para sênior e para pleno?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
