### ISSUE TITLE
Dev front e back

### ISSUE THREAD

**Issue by alvares777** [frontendbr/vagas#3075]
Precisamos redensenvolver sistema legado que já é WEB para outra linguagem como Java, PHP, React

No momento estamos avaliando Front e Back para decidirmos.

Para trabalhar em Tamboré-SP

A área de Análise de Sistemas e Negócios é bem conhecedora da empresa e necessidades e não terá problemas com modelagens, definições, etc. É sentar e codar.

Mande-me seu CV para análise com pretensão salarial.

**Comment by willianbvsanches13** [comment]
remoto?

**Comment by alvares777** [comment]
presencial

De: willianbvsanches13 <notifications@github.com>
Enviada em: sexta-feira, 3 de abril de 2020 17:12
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: alvares777 <alvares777@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [frontendbr/vagas] Dev front e back (#3075)


remoto?

**Comment by eduardocappellotto** [comment]
Olá @alvares777, tudo bem?
Pode adequar a issue no seguinte modelo a seguir?  https://github.com/frontendbr/vagas/blob/master/.github/ISSUE_TEMPLATE/adicionar-nova-vaga.md 
Ajuda na hora de colocar labels e filtrar resultados. Obrigado.

**Comment by guidevieiraa** [comment]
https://guidevieira.s3-us-west-1.amazonaws.com/Guilherme-Vieira-Quintino+(1).pdf

**Comment by alvares777** [comment]
Boa noite Guilherme
Recebi seu CV e se perfil nos interessa

Me mande sua pretensão salarial

Nossa empresa fica em Tamboré, você tem veículo próprio?

Att
Marcelo


De: guidevieiraa <notifications@github.com>
Enviada em: sábado, 4 de abril de 2020 22:39
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: alvares777 <alvares777@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [frontendbr/vagas] Dev front e back (#3075)


https://guidevieira.s3-us-west-1.amazonaws.com/Guilherme-Vieira-Quintino+(1).pdf<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fguidevieira.s3-us-west-1.amazonaws.com%2FGuilherme-Vieira-Quintino%2B(1).pdf&data=02%7C01%7C%7C02b7137dec114d9d9da108d7d902121e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637216475224418976&sdata=OHm9cEoDV7VfpzJaun3zbSzBYxB1snUZBe2UBREWEP4%3D&reserved=0>

**Comment by felipefialho** [comment]
@alvares777 A publicação está TOTALMENTE fora do padrão, favor seguir o [template](https://github.com/frontendbr/vagas/blob/master/.github/ISSUE_TEMPLATE/adicionar-nova-vaga.md) ou será removida.

**Comment by alvares777** [comment]
Não sei como usar template, tem um HOW To
Ou tenho que digitar as labels todas?
Se não tiver pode remover
Obrigado

De: Felipe Fialho <notifications@github.com>
Enviada em: segunda-feira, 6 de abril de 2020 10:45
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: alvares777 <alvares777@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [frontendbr/vagas] Dev front e back (#3075)


@alvares777<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Falvares777&data=02%7C01%7C%7Cd68587a2b2824ad8c57208d7da30b761%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637217775077504731&sdata=e71Uz3Vu6Zo52B8XWWmuCfirDuZ6HwCWG02%2FF0JyQqc%3D&reserved=0> A publicação está TOTALMENTE fora do padrão, favor seguir o template<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffrontendbr%2Fvagas%2Fblob%2Fmaster%2F.github%2FISSUE_TEMPLATE%2Fadicionar-nova-vaga.md&data=02%7C01%7C%7Cd68587a2b2824ad8c57208d7da30b761%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637217775077504731&sdata=mn2aGzKsFAVs6oIvYc8SmdrXp423gfIBb6o%2Ba6rDQiU%3D&reserved=0> ou será removida.

**Comment by diogomoretti** [comment]
Conforme as regras, vamos fechar até que coloque a vaga no nosso [template](https://github.com/frontendbr/vagas/blob/master/.github/ISSUE_TEMPLATE/adicionar-nova-vaga.md).
