### ISSUE TITLE
[São Paulo ou remoto] Fullstack developer na Fator3 Ventures - Fábrica de Startups

### ISSUE THREAD

**Issue by rarossi** [frontendbr/vagas#3077]
![FATOR3 Vaga DEV](https://user-images.githubusercontent.com/17744893/78667798-f4ce6b80-78af-11ea-8212-353fa3992020.jpg)

**Comment by theandersonn** [comment]
@rarossi Ajuste a sua postagem de acordo com o esse [modelo].(https://github.com/frontendbr/vagas/blob/master/.github/ISSUE_TEMPLATE/adicionar-nova-vaga.md)
