### ISSUE TITLE
[São Paulo ou remoto] Fullstack developer na Fator3 Ventures - Fábrica de Startups

### ISSUE THREAD

**Issue by rarossi** [frontendbr/vagas#3078]
## Descrição da vaga

Oportunidade para trabalhar em Startup Early Stage como fullstack developer.

## Local

Remoto ou Escritório, São Paulo.

## Benefícios

- Possibilidade de salário + equity

#### Diferenciais

- No momento, 100% remoto
- Startups em diferentes áreas com oportunidades abertas

## Requisitos

**Obrigatórios:**
- Fullstack
- Testes automatizados e manuais
- Levantamento de requisitos
- Deploy de aplicações (preferencialmente AWS + Nginx)

**Desejáveis:**
- Java
- Spring
- VueJS

## Contratação

A combinar

## Nossa empresa

Somos uma Venture Builder, ajudamos Startups a acelerarem e conseguirem investimentos.

## Como se candidatar

Preencher formulário em www.fator3.com.br/vagas

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- A combinar

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by teixeira83** [comment]
Formulário enviado!

**Comment by raulfranck** [comment]
Aplicado !

**Comment by arthur-mts** [comment]
Aplicado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
