### ISSUE TITLE
[Remoto] Front-end Developer na Mimoo

### ISSUE THREAD

**Issue by LucasKauer** [frontendbr/vagas#3079]
# Mimoo &middot; <img src="https://static.wixstatic.com/media/840614_faaab4ff77fc41e0aff9137abf78778c~mv2.png/v1/fill/w_32%2Ch_32%2Clg_1%2Cusm_0.66_1.00_0.01/840614_faaab4ff77fc41e0aff9137abf78778c~mv2.png" />
## Descrição da vaga
A Mimoo busca uma pessoa desenvolvedora de software, entusiasta de tecnologia, com conhecidos sólidos em front-end e que tenha MUITA ânsia por aprendizado. Espera-se dessa pessoa boa comunicação escrita e verbal, vontade de desenvolver habilidades adjacentes a de desenvolvimento e capacidade de lidar com a diversidade das pessoas.

#### Nossos projetos
A [Mimoo](http://mimoo.dev/) tem como objetivo fazer parte da rotina de consumo semanal dos consumidores e, para isso, está desenvolvendo uma solução que coleta dados sobre o perfil e comportamento de compra dos seus usuários em troca de mimos (trials). Sobre a coleta:
1. **Sobre a pessoa**: perguntas e respostas sobre pessoa, perfil e comportamento...
2. **Sobre os lugares que ela compra**: upload de recibos que comprovem que o perfil é cliente da farmácia A, supermercado B, etc...
3. **Sobre os produtos que ela consome**: upload de fotos e/ou leitura cód. de barra de produtos / categoria CPG - dentro de casa...

#### Nossa stack:

* React (utilizando Hooks)
* PWA
* AWS (incluindo Cognito, Lambda, DynamoDB, S3, Aurora, etc.)
* CD/CI (seed.run)
* GitHub (mimoo-tech)

## Local
Remoto

## Benefícios
* Cultura Officeless
* Contratação PJ (salário à combinar)

## Requisitos
**Esperamos que você seja:**

* Capaz de expressar ideias e soluções complexas para pessoas não-técnicas
* Capaz de propor soluções alternativas, visando sempre a decisão que vai gerar maior resultado para o produto
* Capaz de trabalhar em um ambiente de entrega contínua com automação de testes de unidade / integração
* Flexível em trabalhar remotamente
* Curioso em aprender tecnologias além da web Stack, como spark e programação funcional
* Confortável com um ambiente dinâmico e de incertezas

**O que buscamos:**

* Domínio em desenvolver soluções Web utilizando React (conhecimento em React Native ou Flutter é um diferencial), Angular e/ou Vue
* Experiência com bancos de dados variados (SQL, NoSQL)
* Experiência com Git e algum dos git flow (Git flow, Gitlab flow)
* Experiência em automatizações em geral com task managers e práticas de entrega contínua
* Experiência com CI/CD em algum provedor de nuvem (AWS, Azure, GCP)
* Experiência com cloud architectures baseado em public cloud services

**Aqui você terá espaço para:**

* Desenhar e construir aplicações com tecnologias emergentes (como React, Angular e/ou Vue).
* Implementar estratégias de integração com tecnologias e serviços 3rd party
* Escolher as suas ferramentas e a maneira que você quer trabalhar

## Contratação
* Contratação PJ (salário à combinar)

## Nossa empresa
A [Mimoo](https://www.mimoogratis.com.br/) é uma Start-Up que nasceu para inovar e quebrar paradigmas no relacionamento entre a indústria de bens de consumo e o consumidor final. Hoje a Mimoo é a 1° rede de lojas do Brasil onde tudo é gratuito.

As lojas [Mimoo Grátis](https://www.mimoogratis.com.br/) já estão em operação em 4 (quatro) zonas de São Paulo: Zona Norte (Shopping Metrô Tucuruvi), Zona Sul (Mais Shopping), Zona Leste (Shopping Metrô Tatuapé) e ABC (Grand Plaza Shopping) e as empresas que investem nessa ideia são: Nívia, Jeunesse, Unilever, Nestlé, Eudora e Bayer.

Conheça mais sobre a Mimoo acessando o [nosso Instagram](https://www.instagram.com/mimoo.gratis/).

### Como se candidatar
Envie um email para [lucas.kauer@mimoogratis.com.br](mailto:lucas.kauer@mimoogratis.com.br) com o seu perfil do GitHub, link para sua home page ou algum de seus trabalhos publicados. Preferencialmente enviar o CV em código, **show me the code**.

## Labels
* PJ
* Pleno
* Remoto

**Comment by JIFerreira** [comment]
você quer front-end ou fullstack?

**Comment by DiAugust** [comment]
Não compreendi se é uma vaga front-end ou fullstack. Também não compreendi se precisam de pleno ou especialista, visando que que especialista é um nível na tecnologia. Acredito também não ter compreendido a frase "de extrema incerteza" ao falar da empresa, não sei se era pra causar algum efeito positivo, mas não rolou. Num geral, como eu sou o candidato e sou eu quem esta precisando de trabalho, assumo que a culpa do não entendimento seja minha.

**Comment by LucasKauer** [comment]
Fala pessoal,
A partir do feedback de vocês ajustei alguns descritivos do anúncio. Mas, em resumo, é uma vaga para **desenvolvedor frontend de nível pleno**.. Ainda assim, saibam que a Mimoo é uma Startup (até por isso a referência ao "ambiente dinâmico e de incertezas") e o time está em crescimento então, obviamente, não temos ainda um chapter de frontend e de backends... é interessante que todos conheçam tudo que gira em torno da tecnologia da Mimoo.

**Comment by willianbvsanches13** [comment]
Qual é o salário pretendido para a vaga?

**Comment by pedroch4610** [comment]
@willianbvsanches13 Acho que as empresas deveriam ser aconselhadas a postar, pelo menos, um "range" dos salários que ela está oferecendo para o candidato. Não é uma boa esconder o salário, em primeiro momento, por medo de afugentar os candidatos, para os casos de salários abaixo do esperado, por que mesmo que o candidato passe por todo o processo e no final ele se depare com um salario abaixo de suas expectativas, levando em consideração suas habilidade e experiencia, ele provavelmente não ira aceitar. 

Seria bom para todos se as empresas postassem, junto a vaga, um "range" de salários disponíveis para a vaga, variando conforme as habilidades do candidato. Neste caso, o candidato não correria o risco de se candidatar a uma vaga com um salário abaixo de suas expectativas, e a empresa teria certeza de que todos os candidatos que se inscreveram para vaga já aceitaram, de antemão o salário oferecido. Isso, para mim, polparia tempo de ambas as partes. Fica aqui uma sugestão para, se fizer sentido, adicionar ao template das vagas @felipefialho. Abraços!

**Comment by Kulessa** [comment]
Em qua., 8 de abr. de 2020 às 08:37, Pedro Francisco <
notifications@github.com> escreveu:

**Comment by felipefialho** [comment]
@pedroch4610 Essa ideia já foi debatida algumas vezes. Até me lembro de ter rolado sugestão pra ficar no template, mas sinceramente não sei que fim deu.

Não vejo problemas, especialmente como campo "opcional".
