### ISSUE TITLE
[Curitiba/ Remote] Golang/React Developer na Visionnaire Tecnologia

### ISSUE THREAD

**Issue by raulbalestra** [frontendbr/vagas#3082]
Requirements
We are looking for a **junior/middle full-stack Golang/React** developer to help our client with the backend implementation. 

Timeframe & Budget
Start: asap

Duration: **at least 1 month of full-time work**

## Local

Remote

## Benefícios

**Required skills:**
- Great spoken English would be a must-have
- React Skills
- Golang Skills

## Contratação

PJ 

## Como se candidatar

Por favor envie um email para raul.balestra@visionnaire.com.br com seu CV anexado - enviar no assunto: Vaga React Native

## Labels

- 🏢 Remoto
- 👦 Júnior
- 👨 Pleno
- ⚖️ PJ
- 💰 5k-10k

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
