### ISSUE TITLE
[REMOTO ou São Paulo] Front-end Developer (qualquer nível) na Simbiose Ventures

### ISSUE THREAD

**Issue by gmenegatti** [frontendbr/vagas#3084]
## O que buscamos
Desenvolvedores front-end com qualquer nível de experiência em programação. As vagas são para aqueles que ainda estão iniciando até para os que já se consideram sênior. Se você já está trabalhando mas possui pelo menos 4 horas "livres" por dia (seg a sex), também poderá se candidatar para trabalhar "part-time" conosco.

**Não selecionaremos as pessoas com base no nível de conhecimento técnico**.

## Trabalho
Nosso trabalho é criar plataformas de gestão, processamento e armazenamento de dados em larga escala. Bilhões de requisições por dia. Nossos sistemas são criados para serem utilizados por outras empresas (pequenas, médias e grandes), visando analisarem seus dados e/ou criarem seus próprios produtos.
Nós valorizamos **MUITO** a experiência dos nossos clientes/usuários, portanto investimos muito tempo em UX/UI.

## Remuneração
Nosso plano de remuneração varia de acordo com a quantidade de horas que você deseja trabalhar. 
O valor base é de R$ 1.200,00 por mês para quem trabalha apenas 4 horas por dia,  podendo chegar até R$ 17.500,00 para quem trabalha (em média) 12 horas por dia.

## Empresa
Você consegue saber mais sobre a Simbiose acessando o [nosso site](https://www.simbioseventures.com) ou assistindo ao vídeo abaixo.

[![Equipe Simbiose](https://i.imgur.com/5gzqKDC.png)](https://www.youtube.com/watch?v=71Gdag1CnSU)

## Como se candidatar
Basta acessar o link abaixo e seguir os procedimentos indicados.

[Como fazer parte da Simbiose](https://www.simbioseventures.com/trabalhar-na-simbiose/como-trabalhar-na-simbiose)

## Vagas
Temos mais de 20 vagas abertas para desenvolvedores front-end, back-end, testers e DevOps/SysAdmin.

Qualquer dúvida, estamos à inteira disposição.

Muito obrigado!

**Comment by arrudacaio** [comment]
Enviado!

**Comment by fernandocamargo** [comment]
Uma empresa que normaliza uma jornada de trabalho de 12 horas tem mais é que se fuder e ser varrida do mercado. A começar por ser banida aqui do repo e da comunidade como um geral.

Lembro dessa 'empresa' num passado recente, acho que inclusive discuti em alguns posts em grupos de desenvolvimento no Facebook. Papagaiada de meritocracia travestida de exploração.

Aplica quem quer, óbvio, mas atenção redobrada para os menos experientes e iniciantes. Tem muita vaga por aí, não se sujeitem a qualquer oferta.

**Comment by gmenegatti** [comment]
Obrigado comentário @fernandocamargo. 

Obviamente temos uma percepção diferente em relação a sua opinião. Se tiver disposto a conhecer a Simbiose um pouco melhor e, quem sabe, ter uma opinião com base em fatos e vivência própria, estamos à sua inteira disposição.

De qualquer maneira, te desejo ainda mais sucesso.

**Comment by fernandocamargo** [comment]
O truque consiste basicamente em exigir conhecimento em inúmeras e mais diversas áreas, criando uma sensação de que o profissional está performando abaixo do esperado ou que não está atingindo ainda uma patamar de qualidade difícil de atingir, justificando assim uma baixa remuneração.

É um ciclo sem fim, visto que quando você ascende na escala de senioridade, piores e mais intangíveis ficam os critérios.

![image](https://user-images.githubusercontent.com/232828/78953105-0003e000-7ad8-11ea-8c6b-a75901a986f6.png)

Forte candidato pra aparecer no [Vagas Arrombadas](https://twitter.com/vagasvtnc?lang=en).

**Comment by fernandocamargo** [comment]
@giovannibonetti único convite que eu aceito de você é sair no soco.

Ouçam essa pepita aqui: 😆😆😆 
https://www.dropbox.com/s/a0m92z5vg6en50n/Jo%C3%A3o%20Medeiros.m4a?dl=0

**Comment by giovannibonetti** [comment]
Ei, não tenho nada a ver com essa conversa, @fernandocamargo! 😅

**Comment by fernandocamargo** [comment]
@giovannibonetti foi mal! Marquei errado. :(

**Comment by gmenegatti** [comment]
Poxa, que pena. Se a única forma de "diálogo" for "sair no soco", vai ter que ficar para uma próxima. 👍

**Comment by fernandocamargo** [comment]
Segundo o áudio ali em cima, ou nas suas próprias palavras: "o conflito é necessário, ele faz parte da vida, não existe uma vida sem conflito". 😆

A tua cara é pilantrar os desavisados e a minha é expôr isso.

**Comment by fernandocamargo** [comment]
https://docs.google.com/spreadsheets/d/15irL3QvgTHfk7joqURP8s036njPL4krl6JSw7KksHz4/edit#gid=0

Que piada de mau gosto.

**Comment by gmenegatti** [comment]
@fernandocamargo, por favor, na sua visão/percepção, como você acredita que deveria ser um bom plano de carreira/remuneração?

(Para ficar claro, o interesse com a pergunta é realmente legítimo, não é uma afronta)

**Comment by fernandocamargo** [comment]
Trabalho doze horas por dia pra você em troca de sair na mão 15 minutos por mês.

**Comment by fernandocamargo** [comment]
Sério, ouçam o áudio. O pobre diabo é avaliado por nunca ter reclamado de nada, inclusive de ter trabalhado de fim de semana (o que parece ter sido bastante frequente) e ainda perde ponto por isso.

Depois esse arrombado ainda quer controlar o que o cara faz no tempo livre (se é que sobra, né?).

Caí nessa, não. Moderador, fortalece a classe aí. Bane esse cuzeiro daqui logo.

**Comment by fernandocamargo** [comment]
Tirado do [LoveMondays/Glassdoor](https://www.glassdoor.com.br/Avalia%C3%A7%C3%B5es/Simbiose-Ventures-Avalia%C3%A7%C3%B5es-E2489298.htm#loveMondaysRedirect), exatamente o que eu suspeitava:

## Prós

> - Cultura forte
> - Metas de crescimento (mais ou menos) bem definido
> - Acompanhamento próximo
> - Impulsionamento técnico e pessoal (na base da dor)
> - Carga horária reduzida (mais ou menos) e flexível</p>

## Contras

> - Falta de tato no trato com as pessoas por parte do CEO
> - O CEO contraditório e manipulador, diz e se contradiz o tempo todo. Não dá para confiar muito na palavra do mesmo. É quase imperceptível a manipulação, mas ela existe e é um grande fator dentro da empresa.
> - Ou é do jeito do CEO ou você terá muitos problemas, com mesmo sendo impaciente, indelicado e muitas vezes até abusivo.
> - Requisições absurdas por parte do CEO
> - Controle excessivo de horário, atividade e até da vida pessoal do empreago. Inclusive fazendo demandas sem noção em horários de descanso.
> - Salário inicial absurdamente abaixo da média de mercado.
> -A empresa diz que só quer contratar pessoas com mentalidade de dono, porém, o que eles querem é alguém que trabalhe como se fosse dono da empresa, ganhando menos do que um estagiário ganharia (pelo menos de início) e que não reclamem de não receber nenhum tipo de beneficio (alimentação, plano de saúde e etc) mesmo recebendo 1240 reais por mês.
> -O plano de carreira não faz o menor sentido e parece que foi feito para promover a estagnação dos empregados na faixa salarial de 5000 reais. Isso quando ele já está atingindo o patamar de senior para o resto do mercado. Não a toa muitas pessoas que trabalham na empresa são do norte e nordeste do país (ou cidades pequenas do sul e sudeste. Raramente alguém de onde a empresa tem sede, SP-capital)

**Comment by fernandocamargo** [comment]
## Prós

> - Flexibilidade de horários, aprendizado rápido.

## Contras

> - Salário extremamente baixo, às vezes abaixo até de um salário mínimo. O pensamento ultra "empreendedor" do dono da empresa faz com que ele contrate muitos funcionários informalmente.
> - O plano de carreira é teoricamente bom, mas não é aplicado. Na prática, quando chega a avaliação é proposto um valor muito inferior ao mostrado no plano de carreira.
> - Cobrança desproporcional.
> - Horas extras não remuneradas.
> - Sem benefícios.
> - O dono da empresa gosta de se envolver com a vida pessoal do funcionário, cobrando que o funcionário compartilhe aspectos íntimos para que cresça pessoalmente.
> - Desorganização na estrutura da empresa.

**Comment by fernandocamargo** [comment]
## Prós

> - Na empresa há planos de carreira bem definidos. O trabalho é remoto com horário flexível. Aprendizado constante. Ambiente desafiador e bem exigente.

## Contras

> - Muito do que se fala na cultura não se aplica. A meritocracia é aplicada apenas até certo ponto, já que a empresa não dispõe de dinheiro o suficiente para fazer com que as pessoas cresçam financeiramente. O gerenciamento dos funcionários é feito de forma pobre, rude, grossa e muitos funcionários são maltratados pela gerência. A frustração da equipe com o próprio trabalho e a forma de gerenciamento é algo constante, algo que é possível notar pela quantidade de evasão dos funcionário. Alguns funcionários são tratados de forma distinta. O salário é muito baixo para o que exigem.

**Comment by fernandocamargo** [comment]
Até quando os caras elogiam, os caras reclamam: 😆 

## Prós

> - Trabalho remoto; Plano de carreira claro e bem definido, você sabe exatamente o que fazer para subir no plano; Horário flexível; Cultura meritocrática; Estudo e aprendizado MUITO intenso, aprender mais coisas em menos tempo; Aprendizado não somente técnico, mas pessoal/soft skills.

## Contras

> - Salario abaixo da média; Requer comprometimento TOTAL, seu foco deve ser as coisas da empresa e estudos indicados pela empresa; Comunicação falha em algumas ocasiões; Pouco contato com colegas de trabalho (trabalho remoto); Diminuição qualidade de vida; Algumas vezes parece que é uma organização dual compliance coercitiva e utilitária, mesmo que em sua maioria seja normativa e utilitária.

**Comment by fernandocamargo** [comment]
@gmenegatti tô quase te pagando um salário pra gente trocar aquela porrada.

**Comment by fernandocamargo** [comment]
## Prós

> - O trabalho remoto e o plano de carreira agressivo são os principais pontos positivos da empresa. Além disso, conforme descrito nos valores e cultura da empresa, o desenvolvedor é constantemente desafiado a dar o seu melhor e estar em constante evolução. É uma empresa que investe muito no desenvolvimento técnico e principalmente pessoal do funcionário.

## Contras

> - A empresa exige comprometimento total, não querem apenas que você apareça para "bater ponto". O funcionário desejado é aquele que toma o sonho da empresa como seu sonho pessoal e se dedica completamente aos projetos da empresa. Ao meu ver os valores e cultura da empresa são muito lindos no papel mas deveriam ser revistos na prática. Por incentivar uma curva de aprendizado além do comum, geralmente as tarefas não são muito bem distribuídas de acordo com o nível do desenvolvedor porém a cobrança continua sempre a mesma.

Porra, os caras investem muito no teu desenvolvimento pessoal, mas a moeda é o teu sangue.

![image](https://user-images.githubusercontent.com/232828/78957931-f5047c00-7ae6-11ea-9d17-d0d0b51c32ad.png)

**Comment by fernandocamargo** [comment]
Last but not least:
https://twitter.com/H1SaiaDaMatrix/status/1126132767832588299

**Comment by aiminhagastrite** [comment]
> @gmenegatti, o único convite que eu aceito de você é sair no soco.
> 
> Ouçam essa pepita aqui: laughinglaughinglaughing
> https://www.dropbox.com/s/a0m92z5vg6en50n/Jo%C3%A3o%20Medeiros.m4a?dl=0
Ouvir esse áudio atacou minha gastrite.

Este cara que está fazendo a avaliação claramente sente prazer em subjugar os outros, deve ter tido pelo menos uns três orgasmos fazendo essa avaliação.
Já parou pra pensar que talvez seus funcionários "se façam de anjo" e evitem o conflito, como você diz, devido a sua evidente falta empatia e liderança?

O único erro do avaliado, ao meu ver, foi não ter seguido seu conselho de não evitar conflitos e não ter te mandado pro quinto dos infernos ali mesmo.
Te dou nota 0 como gestor, "mas como é só uma sensação e não consigo expressar ela de forma fática, vou concordar com sua autoavaliação."

Depois não se esquece de vir aqui contar pra gente o que você faz no seu tempo livre, na sua vida pessoal, para podermos considerar como você está avançando na sua carreira. Vamos te dar uma nota entre 1 e 5.

**Comment by gmenegatti** [comment]
👍

**Comment by aiminhagastrite** [comment]
> +1
Poxa, não vai ficar nem um pouquinho bravo e reclamar? Vamos te dar nota 0 para gestão de conflitos, você se faz muito de anjinho.
PS: Se ficar bravo e reclamar também te daremos 0 para gestão de conflitos, porque o ideal não é conflito!

**Comment by aiminhagastrite** [comment]
Parece que o áudio da avaliação postada aqui foi apagado, convenientemente. Poucas frases podem explicar esse fenômeno tão bem como a popular "quem tem cu, tem medo".
Eu ia perder meu tempo escrevendo aqui tudo o que há de errado com essa empresa, mas é melhor evitar a fadiga. Não precisa ler muito do próprio site deles para tirar as próprias conclusões.

Minha recomendação aos candidatos: caiam fora enquanto há tempo.
Minha recomendação aos colaboradores: na justiça do trabalho a causa é ganha.

**Comment by fernandocamargo** [comment]
O cara é charlatão profissional. A melhor maneira para ele lidar com essa situação é ignorá-la e seguir capturando outras almas em outros canais (continuou no Facebook).

Mas onde pudermos, estaremos lá para chamá-lo pro soco e avisar os incautos. 😆 

Talvez seja uma boa hora de discutir um código de conduta das vagas e uma espécie de rede de proteção para evitar más empresas no repositório.

Tenhamos consciência de classe.

**Comment by fernandocamargo** [comment]
@felipefialho, cê - na condição de dono do rolê - poderia dar um overview da posição da org a esse respeito? Não só dessa vaga, mas como um todo mesmo. Resguardar os devs é interesse coletivo ou cada um por si?

**Comment by gmenegatti** [comment]
@fernandocamargo, eu realmente sinto muito pelo rancor e ódio interno que podemos visivelmente perceber em você. Honestamente torço e desejo que você se torne uma pessoa melhor. Que seja mais construtivo do que destrutivo para a humanidade.

Talvez você não consiga perceber o "favor" que nos faz vomitando ódio aqui ou em qualquer outro lugar, então vou te explicar.

Quando pessoas como você investem um tempo significativo para tentar nos "prejudicar", duas coisas podem acontecer: 
i) Pessoas que pensam como você não se inscrevem em nosso processo de seleção e, com isso, não perdemos tempo tentando separar o "joio do trigo".
ii) Pessoas que não pensam como você se inscrevem em nosso processo de seleção e, algumas delas, começam a trabalhar conosco e nos ajudam a melhorar.

Nos últimos três dias, mais de 45 pessoas desse grupo, de todos os níveis, se inscreveram em nosso processo de seleção. Será que todas elas são "coitadas" e "ignorantes desinformadas" como você sugere? Penso que seria muito presunçoso assumir isso.

Minha única sugestão para você é: seja a mudança que você quer ver no mundo.

Ao invés de investir tempo criticando algo, vai lá e cria alguma coisa diferente, nova, que tenha as suas crenças. Isso é bem mais honrado e bonito.

Por fim, você não tem e jamais terá a capacidade de nos calar. A única coisa que pode nos calar é alguém abrir uma empresa melhor do que a Simbiose e os membros da nossa equipe decidirem que faz mais sentido fazer parte daquela equipe ao invés dessa. Posso te garantir que isso jamais acontecerá, pois estamos constantemente melhorando e evoluindo.

Essa será minha última mensagem para você, independente dos ataques que vierem na sequência.

Muita luz e paz pra você. :-)

**Comment by fernandocamargo** [comment]
45 pessoas supostamente se inscreveram no seu processo e pelo menos outras 45 (baseado nas reações nos meus comentários) viram a pilantragem do seu esquema e certamente não se inscreveram e não se inscreverão nas suas vagas. Pra mim já valeu o empenho. E mesmo que eu tivesse evitado uma pessoa que seja de cair nessa roubada, já teria ficado igualmente satisfeito.

Em nenhum momento falei que alguém que cai no seu truque é coitado(a) ou ignorante mas, no máximo, desatento. A vulnerabilidade aqui não é cognitiva e sim econômica. Sinto pelas pessoas que, talvez por falta de outra oportunidade ou certa urgência financeira, se submetem a trabalhar pra empresas e pessoas como você.

Todos esses reviews no Glassdoor já confirmam a minha teoria. Não fui eu quem as escrevi. Você ter primeiramente desabilitado os comentário no áudio que você mesmo postou e depois deletou, já denota o seu modus operandi. O seu modelo de negócio é claro pra mim: você aposta que vai ser impossível que todo mundo seja ciente dos seus golpes. Sempre vai ter um 'otário' para sanguessugar. E de certo modo você tá certo. _Tamo_ só trabalhando pra que esse número seja cada vez menor.

A mudança que eu quero é a que eu boto em prática: se todo trabalhador fosse consciente, um verme como você não se criava. E a gente vai chegar lá, é só questão de tempo.

**Comment by felipefialho** [comment]
@fernandocamargo Não tenho como fazer triagem em toda vaga que aparece por aqui, várias são postadas todos os dias. Até porque isso seria um julgamento muito meu sobre determinada vaga e eu não represento a categoria de devs e nem teria condições pra tal.

Mas por outro lado, todas as vagas publicadas aqui são públicas com comentários públicos, então tudo fica exposto para quem quiser tirar suas próprias conclusões. Penso que é um dos melhores filtros que podem existir.

Vou fechar essa issue, mas tudo que foi comentado aqui (de ambas as partes) segue publico para quem quiser ler depois.
