### ISSUE TITLE
[ENCERRADO] Fullstack Developer na BomCupom

### ISSUE THREAD

**Issue by startecjobs** [frontendbr/vagas#3087]
## A Empresa

A BomCupom surgiu entre ideias, rabiscos e sonhos em 2017, inspirada pelo que seu sócio fundador viveu nos EUA. Através do modelo de cuponagem, a empresa permite a integração entre empresas e clientes.

Recentemente a BomCupom entendeu sua necessidade de transformação digital. _"Hoje, nosso maior desafio é transformar um modelo de negócios consolidado no meio físico em um modelo funcional e disseminado nas telas de celulares."_

## Descrição da vaga

Os contratados serão responsáveis pela manutenção e desenvolvimento das plataformas web e mobile da BomCupom

## Local

Remoto 

## Benefícios

- Salário: R$ 3.000,00 a R$ 5.000,00 (JUNIOR)
- Salário: R$ 6.000,00 a R$ 8.000,00 (PLENO)

#### Diferenciais

- Promoção para CTO entre 3-6 meses
- Participação societária de 5% entre 3-6 meses

*Plano de carreira aplicado mediante desempenho individual

## Requisitos

**Obrigatórios:**
- React Native
- Ruby on Rails
- Git

**Desejáveis:**
- React
- Scrum
- SQL Server

### Contratação

- PJ

## Como se candidatar

👇 Clique aqui para saber mais e se inscrever na vaga 
https://bit.ly/WebDevJunior-BomCupom (JUNIOR)
http://bit.ly/WebDev-BomCupom (PLENO)

## Tempo médio de feedbacks

Feedbacks enviados durante o processo e ao final (20/04/2020)
E-mail para contato em caso de não haver resposta: contato@startecexp.com

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

**Comment by ViniciusPuerto** [comment]
Olá, a vaga ainda está em aberto?

**Comment by MuriloRibas** [comment]
Ainda está aberta a vaga para desenvolvedor pleno?

**Comment by f0ntana** [comment]
No site a vaga está encerrada! @felipefialho

**Comment by startecjobs** [comment]
Vagas encerradas!
