### ISSUE TITLE
[Remoto] React-Native Developer na CodeLeap UK

### ISSUE THREAD

**Issue by vrgimael** [frontendbr/vagas#3090]
### Descrição da vaga
👔 Vaga: Desenvolvedor Front-End
⚙️ Experiência procurada: React & React-Native
💼 Empresa: CodeLeap UK
📍 Localização: Onde quiser (remoto)
🌎 Idioma necessário: Inglês básico
💵 Remuneração: R$7.000 a R$10.000 por mês (ou equivalente por projeto)
👉 Detalhes sobre a vaga (em inglês): https://codeleap.co.uk/careers/frontend
✉️ Mande seu CV para: apply@codeleap.co.uk

**Introdução**
Olá! Tudo bem? Somos uma pequena agência de design e desenvolvimento de aplicativos com sede e clientes em Londres (Reino Unido).

Estamos procurando alguém para se juntar a equipe e ajudar no desenvolvimento de produtos dos clientes, e também a construir a identidade de nossa empresa no long prazo. Você terá a oportunidade de tomar decisões importantes e terá responsabilidades, tanto tecnicamente, quanto em relação ao design, usabilidade, e outros aspectos dos produtos.

O foco principal para a vaga é frontend, mas experiência com backend e gerenciamento de infraestrutura no geral seria muito bem vindo (veja "desejáveis" abaixo).

O candidato ideal é alguém jovem que curte tecnologia, websites e aplicativos e é apaixonado por engenharia de software, usabilidade de UI/UX e minimalismo. Conhecimento e curiosidade por marketing e negócios também são bem vindos.

Com relação ao idioma, é importante conseguir se comunicar e escrever o código, conteúdo e comentários _in English_, mas não se preocupe se não estiver 100% confiante pra conversar fluentemente.

O foco da CodeLeap é o design e desenvolvimento de produtos digitais, websites e aplicativos para iOS e Android sob demanda. Cada projeto exige um approach diferente e traz novos desafios. Sempre temos algo diferente pra fazer! No médio e longo prazo temos interesse em desenvolver nossos próprios produtos, então se você gosta da ideia de experimentar internamente e criar coisas novas, você encontrou o lugar certo!

### Local
- Remoto - Central em Londres, Reino Unido

### Benefícios
💵 Remuneração: R$7.000 a R$10.000 por mês ou equivalente por projeto dependendo da experiência

**Diferenciais**
- Sem horário ou local de trabalho, o que importa é fazer acontecer!
- Equipe flexível, espaço para crescimento na empresa
- Gostamos bastante da engenharia em si, e tentamos manter tudo organizado :)

### Requisitos
**Obrigatórios:**
- 2 anos de experiência com desenvolvimento em React e JavaScript
- Alguma experiência com React-Native

**Desejáveis:**
- Interesse em design
- Conhecimentos backend em Python & Django ou Node
- Experiência com AWS, GCP, Firebase, Sentry
- Experiência com deployment e gerenciamento remoto de servidores 
- Experiência com apps nativos iOS & Android e gerenciamento de apps na Apple e Google stores

### Contratação
- PJ a combinar, somos flexíveis
- Início nas próximas semanas

### Nossa empresa
👉 Interessado? Veja: https://codeleap.co.uk/careers/frontend

### Como se candidatar
✉️ Mande seu CV explicando o que você gostou nessa vaga para: apply@codeleap.co.uk

### Labels
🏢 Remoto
👨 Pleno
⚖️ A-Combinar
⚖️ PJ
💰 7k-10k

**Edit:** tem bastante gente aqui com dúvida sobre Inglês - tinha colocado "avançado ou fluente" aqui antes, mas pra deixar claro, não precisa ser 100%. Conversamos em português internamente, e o Inglês é mais necessário pra entender o código, documentação e comentários. É mais importante ter conhecimento de leitura e escrita do que conversa. Espero que responda as perguntas!

**Comment by Luiz-junior** [comment]
Essa faixa salarial é o valor que normalmente oferecem sem exigir um inglês avançado ou fluente, acredito que deveriam valorizar quem tem esse diferencial.

**Comment by pedroch4610** [comment]
Duas dúvidas:

- O inglês pode ser apenas leitura e escrita?
- Tem que ser ambos (React e React Native) ou pode ser um dos dois?

Obrigado!

**Comment by thalesf** [comment]
Qual a carga horária diária ? 
Posso trabalhar nos meus horários livres ?

Obrigado!

**Comment by dougg0k** [comment]
Com uma rapida pesquisada, esse salario nao parece ser equivalente nem a um junior em Londres.

R$10000/mes ou R$120000/ano sai em torno de £18500.

https://www.glassdoor.co.uk/Job/london-react-react-native-developer-london-jobs-SRCH_IL.0,6_IC2671300_KO7,42.htm

**Comment by Luiz-junior** [comment]
Essa é a media salarial de quem não exigem o inglês avançado ou fluente então deveriam valorizar quem tem esse diferencial e acreditem, quem tem esse diferencial está ganhando no mínimo o dobro disso.
Como o dougg0ok disse acima, esse valor não corresponde nem a um nível junior em Londres e por mais que queiram mão de obra mais barata então exijam menos ou paguem mais, sejam justos por favor.

**Comment by ngustavo** [comment]
Esse salário tá dentro da faixa brasileira. Aqui no Rio de Janeiro tem muita empresa pagando menos que isso. Mas levando em consideração que a empresa vai receber o mesmo trabalho que receberia de um inglês e vai receber dinheiro de clientes ingleses, fica no ar a dúvida se vale a pena se candidatar.
Acho válido pagar menos quando o programador tem um nível abaixo do que é encontrado no mercado local ou quando a comunicação fica prejudicada pelo idioma.

**Comment by dougg0k** [comment]
@ngustavo A questao nao foi se esta dentro da faixa ou nao. Entendo que acontece acordos com um valor menor por contratacao internacional, porem em casos como esse estando um tanto abaixo, a empresa tende a lucrar um tanto mais, visto casos onde o desenvolvedor acontece de entregar um valor alto.

A empresa sempre pede e procura o melhor e tende a tentar extrair o maximo, espero um retorno semelhante, apenas isso. 

Nesse caso tambem pode ser o intermediador lucrando por ter aberto uma empresa aqui no Brasil para poder fazer a contratacao PJ. Porem, sem certeza.

Mas sim, varia do desenvolvedor contratado.

**Comment by diogorodrigues** [comment]
Galera, acho importante também pensarem um pouco além dessa questão salarial e levar em consideração a oportunidade de trabalharem para uma empresa estrangeira, podendo praticar o inglês, aumentar a confiança no sentido de prestar serviços se comunicando em outra língue e vivenciando outra cultura, e, talvez, passar um tempo trabalhando lá na sede da empresa. ;)

**Comment by diogorodrigues** [comment]
Galera, acho importante também pensarem um pouco além dessa questão salarial e levar em consideração a oportunidade de trabalharem para uma empresa estrangeira, podendo praticar o inglês, aumentar a confiança no sentido de prestar serviços se comunicando em outra língua e vivenciando outra cultura, e, talvez, passar um tempo trabalhando lá na sede da empresa. ;)

**Comment by fernandocamargo** [comment]
Vendo outros desenvolvedores questionando eventual exploração:
![emocionado](https://user-images.githubusercontent.com/232828/79230978-b0ba0880-7e65-11ea-994f-c90e20d42cce.gif)

**Comment by fernandocamargo** [comment]
> Galera, acho importante também pensarem um pouco além dessa questão salarial e levar em consideração a oportunidade de trabalharem para uma empresa estrangeira, podendo praticar o inglês, aumentar a confiança no sentido de prestar serviços se comunicando em outra língua e vivenciando outra cultura, e, talvez, passar um tempo trabalhando lá na sede da empresa. ;)

O certo seria você ganhar o suficiente para poder pagar pelo aprimoramento do domínio de uma lingua estrangeira, ganhando o suficiente para poder pagar uma viagem internacional como lazer, etc.

Eu acho que a sua intenção não é essa, mas tem um sotaque vira-latista muito presente nesse post. :(

**Comment by willycamargo** [comment]
Pessoal, acho que aqui não é lugar para debater. Por uma situação parecida foi criada uma thread no forum frontendbr: https://github.com/frontendbr/forum/issues/1510

Recomendo lerem as respostas e moverem suas opiniões para lá.

**Comment by vrgimael** [comment]
Mas de novo essa chatisse? Preferem que eu não contrate ninguém no Brasil?

As pessoas reclamando do salário aqui claramente não vivem no mundo real julgando pela quantidade de currículos interessados nessa vaga…

O cidadão que compara o salário de alguém que trabalha presencialmente em Londres com um salário remoto no Brasil e diz que isso é exploração é no mínimo sem noção, e provavelmente mal intencionado querendo causar a discórdia e o conflito… sinto muito, seu comportamento faz do mundo um lugar pior.

Gostaria eu que o mundo fosse tão fácil. No ultimo ano de operação, eu, como diretor da porra da empresa mal consegui fazer £2k por mes pessoalmente, sem contar impostos e o caralho a quatro. Tiveram meses que ficamos (eu e meu sócio) até sem receber pra pagar os funcionários. Se for pagar salário como a sugestão do excelentíssimo acima teria que pagar muito mais do que pra mim mesmo! Acha isso sensato? Produtivo? Quem dirá extorsão?

E isso ainda morando em Londres, onde o custo de vida é múltiplas vezes mais caro (isso é uma necessidade tendo em vista que os clientes e consequentemente fonte de receita estão por aqui). O cara que mora ai no Brasil ganhando R$10,000 por mês deve ter um poder aquisitivo relativo maior que o meu!

O fato é que uma pessoa vivendo na Inglaterra custa mais do que alguém vivendo noutro lugar. Nada mais natural que a remuneração seja refletida, e por essa mesma razão alguém em São Paulo ganha mais que alguém no Acre.
Se o excelentíssimo cidadão acima fosse fazer uma comparação bem intencionada, **deveria comparar nossos salários com a média salarial de trabalhadores remotos no mundo e não de trabalhadores locais na Inglaterra, não acham?**

Afinal, não estamos contratando pra uma vaga internacional. Há quem diga que é uma vaga internacional pois a empresa é de fora e falamos inglês (também), mas acontece que o funcionário trabalhando do Brasil também tem custos de vida significantemente mais baixos, ao contrario do trabalhador na Inglaterra ou noutro lugar.

Uma pesquisa rápida no Glassdoor revela que o salário oferecido pela CodeLeap **é mais alto do que a média do salário de desenvolvedores sênior em Sao Paulo,** na cidade mais cara do Brasil, e em uma posição ainda mais experiente do que o requisitado por nós.

Eu pessoalmente se estivesse ainda vivendo em minha cidade natal (Bauru-SP) e ganhando R$10,000 por mes trabalhando remotamente estaria pulando de alegria. Pra falar a verdade, acho que eu seria o jovem com maior salário que eu conheço na cidade inteira.

Enfim… essa mentalidade escrota (desculpa o linguajar) anti empresário é uma das principais razoes de eu ter saído do Brasil… eu poderia muito bem procurar gente em lugares mais baratos (India, Polonia, Ukraine), mas quis dar uma chance aos meus conterrâneos, e assim contribuir pro Brasil ir pra frente dando o oportunidade pra quem quer aprender e ganhar esse dinheiro que atualmente é o máximo que consigo oferecer da empresa de forma razoável… acha isso pouco? Te convido então a vir pra Inglaterra, abrir uma empresa, gastar muito com marketing, contadores e advogados, conseguir clientes e fazer melhor que isso. Não consegue? Então para de mimimi. Se voce é tão fodástico que consegue salários astronômicos, bom pra você! Mas não estrague a oportunidade dos outros.

O ódio é tão grande que mandaram uma mensagem da Alemanha nos xingando no site hoje (quem será… veja screenshot)… o cara foi até o site só pra espalhar o ódio… pra que tanto rancor?

<img width="1241" alt="Screenshot 2020-04-14 at 20 00 51" src="https://user-images.githubusercontent.com/14969223/79263459-c42b9a80-7e8a-11ea-8cd6-431a5bac4c8b.png">

Depois de ver posts de outras empresas estou começando a achar que meu maior erro é ser sincero e publicar o salário desejado logo de prima pra tirar todas as duvidas… Quem não posta salário não tem reclamação!

Bom… pra concluir,

Começamos a CodeLeap com a intenção de aprender, conhecer gente legal e criar nosso proprios produtos no futuro. A empresa/startup está ainda no seu início - eu mesmo tenho só 27 anos, e estamos buscando pessoas interessadas em crescer com a gente. Adoraríamos pagar salários mais altos, mas obviamente como disse acima isso não faria sentido para a empresa, a não ser que essa pessoa seja mais produtiva do que os próprios fundadores…


Pra quem tiver interesse, não deixem que os chatos te desencorajem! O mundo vai sempre estar cheio de rancor e gente querendo causar problema… Se a vaga se encaixa nas suas necessidades e expectativas, fico feliz em discutir a oportunidade!


Ps. Se alguém achar que estou fundamentalmente errado no raciocínio acima, por favor, argumente.

Obrigado,
Victor

**Comment by dougg0k** [comment]
Ola @vrgimael, certamente nao mencionei por ma intencao ou por rancor, foi algo que presenciei e prestei atencao por um tempo, onde parece existir essa procura intencional por custo menor afim de lucro maior e de forma nenhuma sou anti-empresario, entendo ao menos parcialmente as dificuldades. A ideia e ser justamente recompensado, nada mais, porem esta claro que depende da realidade de empresa, o que sua resposta deixa bem claro isso.

Alem disso nao acho R$10000 um salario baixo aqui, nao mencionei exploracao apesar da afirmacao tenha feito parecer. O que eu esperava era uma resposta mesmo, a sua foi exatamente o que eu esperava, assim dizendo/mostrando a realidade da situacao. 

Em questao a suas afirmacoes sobre achar isso ou aquilo de mim mesmo, nao se aplica a mim. 

Em todo caso, minhas desculpas caso tenha sido algo desconfortavel para ti.

Que nada, sinceridade nunca sera um erro, a nao ser que seja ma intencionada e ou mal pensada.

**Comment by fernandocamargo** [comment]
Caralho, que papo de empreendedor arrombado do caralho. Só no Brasil mesmo pra ter fetiche com esse tipo de relação. Quando essa bad trip coletiva passar, finalmente daremos alguns passos rumo ao progresso. Poucos argumentos são tão filhos da puta do que esse abrir a sua própria empresa. Tá passando perrengue? Que dó, hein, locomotiva do Brasil. O que seria de nós trabalhadores sem empresários tão generosos? Spoiler: a crise de agora tá escancarando que essa dependência é totalmente invertida.

Não é sobre o custo de vida do trabalhador na sua cidade local. Você está faturando em libras e pagando em reais. É exploração, sim. Se o modelo de negócio da sua porra de empresa depende vitalmente de pagar mão de obra mais barata em países de terceiro mundo para faturar, você é essencialmente um sanguessuga.

**Comment by vrgimael** [comment]
Faz melhor.

**Comment by fernandocamargo** [comment]
Como experimento vou perguntar pros meus colegas alemães (😉) e europeus se eles topariam exercer o mesmo trabalho que um norte-americano por um terço do preço (só porque lá paga-se muito mais). Meu palpite é que não. A diferença é que eles não se encontram entre a cruz e a espada e não estão financeiramente vulneráveis. Se você acha que tem alguma nobreza em se beneficiar da necessidade dos outros, maneiro. Desapontado mas não surpreso.

**Comment by fernandocamargo** [comment]
Fala aqui pro tio, quantos lugares você trabalhou antes de ser _patrão_? Só pra eu fazer uma pesquisa aqui rapidão. Porque quase sempre que vêm com esse papo, o roteiro é quase o mesmo: privilegiado que nunca trabalhou, ou ancap. Ou os dois.

**Comment by vrgimael** [comment]
Por que vc não cria sua empresa e venha aqui oferecer esses tais de salários justos que tanto diz?

Esse é o melhor que podemos oferecer agora. Acha ruim? Faz melhor! Simples assim.

**Comment by fernandocamargo** [comment]
Fui ver no Facebook e tudo se encaixou. Bolsominion e, como quase todos, mau-caráter.

Same energy:

![meme-01](https://user-images.githubusercontent.com/232828/79270537-a9632100-7e9e-11ea-8d30-1f5003d78977.jpg)

![meme](https://user-images.githubusercontent.com/232828/79270411-6903a300-7e9e-11ea-95cd-b7d024dfdfd3.jpg)

**Comment by vrgimael** [comment]
Tem moderador isso aqui? O cara não só está atrapalhando o post falando muita merda e agora ainda vem mentir...

Faz melhor... talvez esse já seja seu melhor...

**Comment by fernandocamargo** [comment]
O que você e o outro sanguessuga empreendedor da outra issue não entenderam ainda é: meu papel não é impedir que vocês possam aplicar seus golpes e explorar as pessoas. Isso iria contra os meus próprios conceitos de democracia e liberdade. Vida longa e próspera pra vocês e seus _negócios_ enquanto houver tempo. O papo aqui é com os meus pares. A única coisa que eu e algumas outras pessoas desejamos é que as pessoas tenham pelo menos a oportunidade de refletir sobre estarem ou não sendo exploradas. Se alguém achar que nada disso que eu falo tem coerência, ótimo, só se candidatar.

<img width="598" alt="Screenshot 2020-04-14 at 22 32 25" src="https://user-images.githubusercontent.com/232828/79271294-d9f78a80-7e9f-11ea-9ce4-3991cbd46906.png">

**Comment by marcospedro97** [comment]
Caramba, pra quê tudo isso? Ao contrário do caso da simbiose, não tem fatos sendo discutidos aqui... Por favor, vamos parar que isso está tornando uma comunidade focada em objetivismo em uma discussão desgradavel, infelizmente em vários momentos fiquei incomodado com as vagas que eu vi aqui e na backend-br, mas essa onda de cancelamento é inútil, infelizmente sempre haverão pilantras, mas não tem nada de excepcional nessa vaga, já fui contratado como freelancer para receber menos de 3 dolares por hora trabalhada (absurdamente baixo para o valor estrangeiro, mas ótimo para mim, cliente gringo), mas por favor, segura a onda galera... Menos contra a simbiose, aqueles caras são nocivos, acho que merecem processos na justiça do trabalho por muita coisa que fazem, mas sem evidencias deste tipo que não estão presentes aqui não há motivo lógico, quanto aos últimos argumentos usados são todos argumentos ad hominem, ao menos para uma galera que trabalha com TI espero que não se usem falacias lógicas

**Comment by marcospedro97** [comment]
Nós vendemos nossa força de trabalho, cada um vende pelo preço que considera justo, se não lhe interessa vender por esse preço o comércio em sua definição excluí a coerção, tudo que alguém aceita sob coerção é roubo, ninguém nunca colocou uma arma na minha cabeça para eu me candidatar a uma vaga (não precisaria se a vaga oferecer 7000,00 no mês para mim), não façam como se fosse esse o caso, não sei o que os motiva, mas é inútil, então parem ok?

**Comment by fernandocamargo** [comment]
A gente tá tratando de coisa séria aqui: relações de trabalho. É quase tudo o que uma pessoa tem pra oferecer e é de onde ela tira o seu sustento e a partir de onde o resto da sua vida se desenvolve. Se isso não for digno de discussão, o que é? Por que incomoda tanto as pessoas quando tentamos colocar luz em algumas práticas no mínimo questionáveis? Se fosse review de produto aposto que ficariam discutindo e comparando ad eternum.

**Comment by vrgimael** [comment]
O cara quer que ninguém ofereça trabalho pro Brasil...

Vamos fazer uma votação então:

**Quem quiser que a CodeLeap continue postando vagas aqui da um upvote, case contrário, downvote.**

Muito simples, vamos ver o que o povo acha.

**Comment by marcospedro97** [comment]
Colega, infelizmente é comércio, realmente acho que as relações de trabalho na nossa sociedade são cheias de problemas, mas nesse caso é uma relação de comércio bem padrão a única coisa que justificaria essa postura de cancelamento seria uma evidencia de crime, na ausencia das mesmas o que vocês estão fazendo é besteira e anti ético, contra democratico, e sabe-se lá mais quais termos se aplicam a isso, CodeLeap, serei pragmatico, não ligo se a empresa é administrada por bolsonaristas, petralhas, comunas ou ancaps, se vocês conseguem manter um ambiente de trabalho saudável para os colaboradores, vocês já tem meu currículo.

**Comment by fernandocamargo** [comment]
Ô, bebêzão neo-liberal, relê [isso aqui](https://github.com/frontendbr/vagas/issues/3090#issuecomment-613666771) faz favor. Cê pode postar uma vaga por dia, tá tranquilo pra mim. Mas porque parece tão ofensivo que as pessoas discutam a idoneidade da sua empresa? Você ia contratar alguém às cegas?

**Comment by marcospedro97** [comment]
Camarada @fernandocamargo realmente concordo com sua postura na outra issue, mas como um par seu, recomendo maior uso da ponderação e paciencia, a vida é um exercicio de resignação com tudo aquilo que está além do seu poder de mudança, e não há nada que possamos fazer infelizmente

**Comment by MrS4w** [comment]
Pessoal, por favor espaço apenas para divulgação de vagas.
Na intenção de discutir peço encarecidamente que entrem em algum chat e se resolvam. :)

**Comment by marcospedro97** [comment]
Me desculpe @MrS4w vou me retirar da conversa

**Comment by fernandocamargo** [comment]
@marcospedro97 você se enxerga como um proletário, o que já é ótimo começo. Onde alguém está sendo cancelado aqui? Nós somos uma comunidade. Alguém postou uma vaga e outro alguém acenou que parecia existir uma certa disparidade salarial.

Qual seria o nosso papel aqui? Bater palma quando qualquer pessoa se apresentar pra oferecer trabalho, ainda que esse esteja nos esfolando?

**Comment by vrgimael** [comment]
Com toda sinceridade, eu postei uma vaga aqui na maior boa que foi muito bem vinda pela maioria, mas o @fernandocamargo veio cheio de ódio aqui atrapalhar quem tá em paz...

**Comment by fernandocamargo** [comment]
Engraçado que é sempre ódio, né? Mesma coisa que o outro chapa falou. Se eu morasse em Piraporinha ia ser inveja da minha parte, certeza.

**Comment by fernandocamargo** [comment]
Lembre-se que o nosso empreendedor precoce e brilhante está oferecendo metade de um salário de junior para desenvolvedores plenos ou até seniores. Se vocês não enxergam nada de errado nisso, nossa classe tá muito fudida.

Essa ladainha de que preferiu pagar brasileiro é o meu pau de boné. Infelizmente as outras nacionalidades que ele mencionou não têm a fama da qualidade que os brasileiros têm. Especialmente indianos (o que é estranho, porque trabalho com vários e todos eles são ótimos profissionais).

Vou encerrar por agora mas insisto para vocês pararem de cair em qualquer pegadinha que aparece. 😆

**Comment by vrgimael** [comment]
Lembre-se que nosso brilhante militante sabe-se lá de que **não está oferecendo absolutamente nada** e reclamando de tudo que os outros oferecem.

Pela última vez: acha ruim? Faz melhor.

**Comment by fernandocamargo** [comment]
Olôco, tô me oferecendo pra ajudar a quebrar os grilhões dos meus semelhantes. 😆 

Isso startup nenhuma vai oferecer. E olha que já trabalhei em várias.

Infelizmente vou ficar te devendo oferecer vaga de trabalho, porque essa ambição de ser chefinho eu não tenho. Mas posso pesquisar aqui e fzer uma seleção de outras empresas e posições menos explorativas.

**Comment by fernandocamargo** [comment]
Reclamar de tudo = postar/alertar em 2/2000 posts

![image](https://user-images.githubusercontent.com/232828/79274758-580a6000-7ea5-11ea-9662-340d7fa089e3.png)

**Comment by THAYLLER** [comment]
Não acho o salario oferecido ruim, so uma pena eu não ter ingles fluente, será que não dão oportunidade para quem nao tem ingles ainda?

**Comment by rhenanteix** [comment]
Imaginei o mesmo @THAYLLER eu estou fazendo aulas de inglês e vejo essas oportunidades como ajuda a + pra aprender, tendo em vista as tecnologias em que já tenho base e trabalho em projetos atualmente

**Comment by THAYLLER** [comment]
@rhenanteix Pois é eu paguei um curso carissimo para me aperfeiçoar em algumas coisas, e o ingles estudo como posso usando plataformas como duolingo

**Comment by vrgimael** [comment]
Pra quem está se perguntando sobre falar inglês - como eu disse no post original (talvez eu deveria deixar isso mais claro), não se preocupe se não for 100%! É mais importante que tenha conhecimento de leitura e escrita do que conversa, e vc terá oportunidade pra aprender também.

Pode mandar o currículo e a gente discute na entrevista! Qualquer pergunta pode mandar :)

**Comment by marcospedro97** [comment]
@fernandocamargo nossa função é não comprar o que não nos interessa, quanto ao momento em que alguém foi cancelado foi no momento em que uma opinião sua transforma qualquer um em qualquer coisa sem evidencias, assim como você concordo que entender nossa condição no mundo é importante, mas deixar vazar nossa frustração nos outros é sinal de falta de profissionalismo, quando alguém tenta me vender agua por 10 reais a garrafa eu recuso, assim como faço quando me oferecem 1 real pela minha hora de trabalho, mas em momento nenhum se torna legitimo ofender um sujeito por qualquer uma dessas coisas, acredito acima de tudo em comunicação não violenta e dialética, algo que está faltando na sua postura, por isso peço encarecidamente como colega e potencial amigo, que se afaste de uma conversa que está sendo improdutiva e pior, despropositada

**Comment by marcospedro97** [comment]
e por favor pare de sujar minha caixa de email

**Comment by MrS4w** [comment]
Só dar **Unsubscribe** @marcospedro97

**Comment by marcospedro97** [comment]
Não considero válido, acho que esses dois deveriam se tratar com maturidade profissional, considero essa postura inaceitavel, mas a comunidade em si muito boa e muito util, por isso a primeira coisa que comentei era o desvio de uma comunidade objetiva para um assunto completamente desnecessariamente agressivo

**Comment by MrS4w** [comment]
Corretíssimo Marcos!

**Comment by fernandocamargo** [comment]
Sem evidência? No seu exemplo, se você resolver alertar quem tá próximo que uma garrafa de água por dez reais é abuso, você está emitindo opinião sem evidência? Eu não tentei adivinhar o salário que ele estava oferecendo. Eu sinceramente não entendi muito bem a sua idéia de subserviência, de resignação e aceitação, mas tenho certeza que eu discordo diametralmente.

Eu não faltei com respeito até o autor do post se manifestar.

Essa idéia de não se intrometer só é conveniente pro lado que tá se beneficiando da exploração.

De novo: se uma empresa vai te contratar, ela vai fazer múltiplas entrevistas, aplicar testes, pedir referências - dependendo do tipo de trabalho que você exerce, até antecedentes criminais - etc. Porque parece tão insolente discutir a idoneidade de uma empresa?

Minha sugestão cordial é que você reveja sua posição de capacho nessa história.

**Comment by marcospedro97** [comment]
está aí algo que nunca me chamaram, subserviente... achastes uma ofensa inovadora para mim camarada, minha postura é pragmática, 7.000,00 para uma vaga de react é um ótimo salário tendo em mente a experiencia exigida, não exitaria em aceitar isso de maneira nenhuma, você por outro lado está ofendendo pessoas, percebo em você uma postura extremamente nociva de alguém que entende de ideias e nem um pouco do mundo, isso é desagradavel e danoso quando ofende alguém, como eu disse não há justificativa para agredir um homem que tenta vender uma garrafa de agua por dez reais e nem aquele que tenta me fazer trabalhar por portifólio, apenas minha rejeição a oferta, creio que isso seja o mais saudável, e estou realmente conversando como colega, porque acho que sua postura é reflexo de algo alheio a esta conversa

**Comment by fernandocamargo** [comment]
Não tentei te ofender, de verdade. Mas eu não consigo condensar em outra palavra o conceito por trás do que eu entendo do seu comportamento.

Basicamente você está advogando pelo direito do pilantra em tentar passar a perna em alguém. E o seu conceito de justiça te convence de que o sujeito que potencialmente poderia ter sido passado pra trás exerça seu direito de se esquivar do golpe, mas nunca de se rebelar contra quem o praticou.

**Comment by fernandocamargo** [comment]
E esse é o problema do (neo-)liberal: ele coloca numa mesma balança o explorador e o explorado, como se as partes dispusessem de forças iguais. E posa como uma força externa, como se fosse o pêndulo. Acha que tá garantindo a relação das forças.

Seria cômico se não fosse trágico:
<img width="500" alt="Screenshot 2020-04-15 at 00 27 36" src="https://user-images.githubusercontent.com/232828/79280164-f69bbe80-7eaf-11ea-92d9-284144d6aced.png">

É o tipo de ideário que prega que o funcionário tem poder de barganha ao negociar com o patrão. As vezes até tem, mas são exceções não dignas de serem levadas em conta.

**Comment by marcospedro97** [comment]
Ok então o seu conceito de liberdade é simplesmente agredir todos os detentores de meios de produção, isso torna qualquer discussão um jogo de xadrez com pombos, uma vez que na sua concepção freelancers são os únicos homens livres uma vez que não são oprimidos por um burguês, infelizmente isso não resiste ao confronto da realidade e sinto lhe informar que sua agressividade destilada nessa conversa é inútil, não vai mudar o sistema socio economico, se você acha que pode mudar isso só posso identificar ingenuidade, como eu já disse, mesmo tendo lido tudo isso que você escreveu acho que a oportunidade de emprego é muito boa, uma vez que eu com dois anos de freelancer posso me candidatar para uma vaga que paga quase o salário de um sr BR, então realmente acho que essa empresa entraria como válida na minha lista de candidaturas, mesmo não pagando o salário que se paga no reino unido.

**Comment by fernandocamargo** [comment]
Vai nessa, boneco:
![image](https://user-images.githubusercontent.com/232828/79283062-066ad100-7eb7-11ea-98b7-0cb8a4e1047c.png)

- Quem detém os meios de produção na nossa área?
- Quem falou sobre ser freelancer?
- Você acha mesmo que esse cara representa uma média das empresas, oportunidades e condições disponíveis no mercado? Se sim, onde você já trabalhou? Qual a sua realidade?

Você não respondeu absolutamente nada referente ao que eu escrevi. Posso afirmar categoricamente que você entendeu zero do que eu escrevi.

Por fim: já candidatou pra vaga? Quem tá te impedindo?

**Comment by fernandocamargo** [comment]
Impressão minha ou você tá tentando fazer uma média com o mano que postou a vaga? 😆 

Pelo estilo do cara, acho que você vai impressionar mais e destacar a sua candidatura se falar que aceita 3/4 do que ele ofereceu (já que é tanto assim). Vai por mim, tu vai conseguir a vaga assim.

**Comment by vrgimael** [comment]
Alguém por favor tira esse idiota da thread?

**Comment by fernandocamargo** [comment]
Ô, sinhôzinho, se você tem tantos aplicantes e simpatizantes aqui, o que teme?

**Comment by vrgimael** [comment]
Vamos fazer uma outra votação... quem acha que esse idiota deveria ser banido da issue?

**Comment by felipefialho** [comment]
@fernandocamargo Naturalmente você é livre para postar seu ponto de vista e levantar debates sobre o que achar pertinente.

O único porém é que isso não pode ser feito a base de ofensas e xingamentos como aconteceu algumas vezes nessa (e na outra) issue.

Raramente é necessário intervir nos debates e evitamos sempre que possível, mas de novo, por favor mantenha o tom.

Por essa razão estou novamente fechando os comentários.
