### ISSUE TITLE
[Remoto] React-Native Developer na CodeLeap UK

### ISSUE THREAD

**Issue by vrgimael** [frontendbr/vagas#3092]
### Descrição da vaga
👔 Vaga: Desenvolvedor Front-End
⚙️ Experiência procurada: React & React-Native
💼 Empresa: CodeLeap UK
📍 Localização: Onde quiser (remoto)
🌎 Idioma necessário: Inglês básico
💵 Remuneração: R$7.000 a R$10.000 por mês (ou equivalente por projeto)
👉 Detalhes sobre a vaga (em inglês): https://codeleap.co.uk/careers/frontend
✉️ Mande seu CV para: apply@codeleap.co.uk

**Introdução**
Olá! Tudo bem? Somos uma pequena agência de design e desenvolvimento de aplicativos com sede e clientes em Londres (Reino Unido).

Estamos procurando alguém para se juntar a equipe e ajudar no desenvolvimento de produtos dos clientes, e também a construir a identidade de nossa empresa no long prazo. Você terá a oportunidade de tomar decisões importantes e terá responsabilidades, tanto tecnicamente, quanto em relação ao design, usabilidade, e outros aspectos dos produtos.

O foco principal para a vaga é frontend, mas experiência com backend e gerenciamento de infraestrutura no geral seria muito bem vindo (veja "desejáveis" abaixo).

O candidato ideal é alguém jovem que curte tecnologia, websites e aplicativos e é apaixonado por engenharia de software, usabilidade de UI/UX e minimalismo. Conhecimento e curiosidade por marketing e negócios também são bem vindos.

Teve bastante gente com dúvida sobre Inglês - com relação ao idioma, é importante conseguir se comunicar no básico e saber ler e escrever o código, conteúdo e comentários in English, mas não se preocupe se não estiver 100% confiante pra conversar - não tem necessidade.

O foco da CodeLeap é o design e desenvolvimento de produtos digitais, websites e aplicativos para iOS e Android sob demanda. Cada projeto exige um approach diferente e traz novos desafios. Sempre temos algo diferente pra fazer! No médio e longo prazo temos interesse em desenvolver nossos próprios produtos, então se você gosta da ideia de experimentar internamente e criar coisas novas, você encontrou o lugar certo!

### Local
- Remoto - Central em Londres, Reino Unido

### Benefícios
💵 Remuneração: R$7.000 a R$10.000 por mês ou equivalente por projeto dependendo da experiência

### Diferenciais
- Sem horário ou local de trabalho, o que importa é fazer acontecer!
- Equipe flexível, espaço para crescimento na empresa
- Gostamos bastante da engenharia em si, e tentamos manter tudo organizado :)

### Requisitos
**Obrigatórios:**
- 2 anos de experiência com desenvolvimento em React e JavaScript
- Alguma experiência com React-Native

### Desejáveis:
- Interesse em design
- Conhecimentos backend em Python & Django ou Node
- Experiência com AWS, GCP, Firebase, Sentry
- Experiência com deployment e gerenciamento remoto de servidores
- Experiência com apps nativos iOS & Android e gerenciamento de apps na Apple e Google stores

### Contratação
- PJ a combinar, somos flexíveis
- Início nas próximas semanas

### Nossa empresa
👉 Interessado? Veja: https://codeleap.co.uk/careers/frontend

### Como se candidatar
✉️ Mande seu CV explicando o que você gostou nessa vaga para: apply@codeleap.co.uk

### Labels
🏢 Remoto
👨 Pleno
⚖️ A-Combinar
⚖️ PJ
💰 7k-10k

Ps. Moderadores, podem por favor fechar a outra issue? Concordo sobre o direito de argumentar, mas aquilo já é spam... gostaria que a issue estivesse aberta para perguntas

**Comment by felipefialho** [comment]
Vou deixar essa fechada pra comentários a priori.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
