### ISSUE TITLE
[Curitiba/Remote] Vue.js Developer at Visionnaire

### ISSUE THREAD

**Issue by raulbalestra** [frontendbr/vagas#3093]
Business
The startup has built the first and main medical records management system for hospitals in Africa.
The product is launched and has lots of private and state hospitals of different sizes among its customers.
Current product stack: Angular, moving to Vue.js right now; Elixir; PostgreSQL; AWS; Datadog; Gitlab.
 
Requirements
The customer is looking for:
- 1 mid-senior Elixir dev. Oracle and/or Microsoft stack experience would be a great bonus 
- 1 mid-senior Vue.js developer 

Curitiba/Remote
PJ 

Nossa empresa
Somos uma fabrica de Software com mais de 24 anos de experiencia em desenvolvimento de Software, Outsourcing e Hunting.

Para mais informações visite nosso site : www.visionnaire.com.br

Como se candidatar
Por favor envie um email para raul.balestra@visionnaire.com.br com seu CV anexado - enviar no assunto: descrição da vaga

Labels
office Flexível
office Presencial
office Remoto
Pleno/Sênior
balance_scale PJ

Timeframe & budget
Start - asap.
Duration - 3 months.
money 8k+/Mês

**Comment by rafaelkendrik** [comment]
Grato @raulbalestra.
Enviei um e-mail com apresentação e solicitação de participação no processo seletivo :)

**Comment by raulbalestra** [comment]
Obrigado, Rafael, email respondido!

**Comment by pedroch4610** [comment]
O inglês pode ser apenas leitura e escrita? Obrigado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
