### ISSUE TITLE
[São Paulo ou Rio de Janeiro] Front-end Pleno na HavasPlus

### ISSUE THREAD

**Issue by jasielmacedo** [frontendbr/vagas#3095]
## Descrição da vaga

Estamos iniciando um novo Núcleo de Desenvolvimento dentro da HavasPlus para criar/customizar/dar manutenção de um Portal de Telefonia.
Será responsável pela criação de componentes front-end, edição de html, animações e criação de páginas e landing pages. 
Integrações front-end com APIs documentadas e etc.

## Local

São Paulo - Cidade Jardim
Rio de Janeiro - Barra da Tijuca

De acordo com a localização do candidato (Preferencialmente em SP)

## Requisitos

**Obrigatórios:**
- 3 anos de experiência em desenvolvimento web
- 3 anos de experiência em Html, Css e Javascript.
- Experiência com a linguagem Java ou Php
- Experiência com soluções SPA como React ou VueJS
- Experiência em trabalhar com Versionamento Git
- Graduação em Ciência da Computação, Engenharia de Software ou equivalente
- Estar atualizado com as últimas novidades das linguagens

**Desejáveis:**
- Experiência em integração com APIs
- Experiência com Vignette, Nukes/JBoss ou Drupal para criação de componentes
- Experiência em trabalhar com sistema de containers como Docker

**Diferenciais:**
- Experiência em React
- Experiência com Gitflow
- Experiência em Vignette
- Inglês (avançado)

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para recrutamento.havasplus@havas.com com seu CV anexado - enviar no assunto: Vaga Front-end Pleno

#### Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Alocado (Após a quarentena)
- Remoto (Durante a quarentena)

#### Nível
- Pleno

#### Remuneração

A combinar, enviar pretensão salarial junto ao CV

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
