### ISSUE TITLE
[São Paulo] Front-end Developer no Menso IO

### ISSUE THREAD

**Issue by esdrastavares** [frontendbr/vagas#3097]
## Nossa empresa

O Menso IO é uma plataforma a principio de Análise de Dados e Data Visualization, nosso roadmap é gigantesco mas estamos construindo de acordo com o mercado. Estamos em busca de um novo integrante para nosso time de builders que seja apaixonado por desenvolvimento de software.

## Descrição da vaga

Projeto desafiador, muito volume de dados, muitas formas de gerar uma boa visualização e análise, de fato é democratizar tarefas extremamente difíceis e transforma-las em informações.

## Local

Remoto ou Escritório, São Paulo - Sé

## Requisitos

**Obrigatórios:**

- Git
- Sólida experiência com projetos (Vue.js,Vuex)
- Criação de interfaces responsivas
- Boas noções de UX
- Javascript ES6 com Babel
- CSS3 e Pré-processadores como Stylus e SASS
- Webpack
- ESLint e Prettier
- Testes unitários e de integração
- Produzir código limpo e com boas práticas

**Desejáveis:**

- Ter facilidade de trabalhar em times multidisciplinares

**Diferenciais:**

- Conhecimentos de arquitetura de microsserviços
- Vivência em times ágeis com SCRUM
- Documentação de código (JSDoc ou similar)

## Benefícios

- 

**Diferenciais:**

- Completamente Home-Office mas vamos nos encontrar quando essa crise melhorar

## Contratação

PJ

## Como se candidatar

Por favor envie um email para vagas@menso.io com seu CV anexado - enviar no assunto: Vaga Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: vagas@menso.io

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível

- Pleno
- Sênior
- Especialista

**Comment by rafaelkendrik** [comment]
Grato @esdrastavares .
Enviei um e-mail com apresentação e solicitação de participação no processo seletivo :)
