### ISSUE TITLE
[Remoto] Front-end Developer na Divisio

### ISSUE THREAD

**Issue by luizeduard0** [frontendbr/vagas#3099]
## Sobre nós
Por trás da Divisio há programadores e gestores com vasta experiência no mercado de desenvolvimento de software internacional, são mais de 20 anos combinados. Esta não é apenas uma vaga ou um número a ser preenchido, buscamos pessoas que se importam de verdade em fazer a diferença através do seu trabalho, que querem crescer e estão constantemente aprendendo e dando seu melhor. 

# Sobre a vaga
Procuramos uma desenvolvedor frontend para atuar junto com a equipe no desenvolvimento e manutenção de projetos internacionais. A contratação é PJ e a vaga é remota, ou seja, você poderá trabalhar de casa ou aonde achar melhor. Quando não estiver atuando em projetos de clientes, você terá a oportunidade de fazer parte da melhoria dos nossos processos internos.

### Local
Remoto

### Requisitos
- Experiência com Javascript
- 2 anos de experiência com React
- Experiência com Redux
- Raciocínio lógico
- Proatividade

### Diferenciais
- Experiência com Trabalho Remoto
- Inglês Avançado

### Benefícios
- Horário Flexível
- Foco em resultados e não na carga horária
- Crescimento junto com seu desempenho
- Treinamento interno

## Como se candidatar
Preencha o formulário a seguir: [Clique aqui](https://forms.gle/VqkgSWdHLqUGdm3K6)

## Labels
- PJ
- Remoto

**Comment by thiagoneres** [comment]
Formulário preenchido :)

**Comment by thalesf** [comment]
Há possibilidade de part-time job ?

**Comment by PisciTec** [comment]
Quanto tempo até a resposta?

**Comment by carlosnani** [comment]
Formulário Preenchido.

**Comment by luizeduard0** [comment]
> Há possibilidade de part-time job ?

Não

**Comment by luizeduard0** [comment]
> Quanto tempo até a resposta?

No máximo 3 dias para resposta inicial. O processo total leva no máximo 2 horas (para quem chega até a última etapa)
