### ISSUE TITLE
[Campinas - SP] Estágio Desenvolvedor Front-End

### ISSUE THREAD

**Issue by webcoag** [frontendbr/vagas#31]
## Descrição da vaga

Quer fazer parte de uma equipe criativa e apaixonada por web? 
Venha desenvolver seu talento através de nosso programa de estágio.

## Local

Campinas/SP

## Benefícios

- Bolsa Auxílio
- Transporte
- Ticket Refeição

## Requisitos

**Obrigatórios:**
- Conhecimentos em HTML, CSS e JS
- Photoshop

**Diferenciais:**
- PHP
- GIT

## Contratação

Estágio

## Nossa empresa

A Webcompany é uma agência de marketing digital focada em estratégia online. Criamos campanhas de marketing digital, sites e aplicativos móveis, conectando marcas e consumidores a mais de 15 anos.

## Como se candidatar

Visite http://webcompany.com.br/talentos e inscreva-se!

**Comment by LFeh** [comment]
A vaga foi preenchida?

**Comment by LFeh** [comment]
Como não teve respostas, vou fechar.

@webcoag  Avisa se precisar abrir.

**Comment by camilatigre** [comment]
@webcoag 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
