### ISSUE TITLE
[Curitiba] Front-end Developer na ONLi

### ISSUE THREAD

**Issue by brendonferreira** [frontendbr/vagas#3100]
## Nossa empresa
A ONLi é uma Aceleradora Tecnologica do Mercado de Seguros. Somos especializados em resolver os maiores e mais desafiadores problemas do mercado, trazendo novas visões tecnológicas para o mercado de seguros.

## Descrição da vaga
A atuação será bem variada, temos varias frentes. Ferramentas manager, aplicativos para gerenciamento do negócio e front-ends de compra. Seguimos o padrão event-driven em nossa arquitetura de microserviços, então em basicamente todas as nossas implementações utilizamos o pattern BFF para os fronts com desenvolvimento back em node e o front em si.

## Local
Curitiba - Pr, Local ou Remoto

## Requisitos

**Obrigatórios:**
- Vue.js avançado
- Responsividade Web
- Node.js

**Desejáveis:**
- Vue.js
- HTML e CSS
- Node.js

**Diferenciais:**
- Ser Auto gerenciável
- Possuir projetos opensource

## Contratação
horário flexível
PJ 4k

## Como se candidatar

Por favor envie um email para brendon@onli.com.br com seu CV anexado - enviar no assunto: Vaga ONLi

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: brendon@onli.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by rafaelkendrik** [comment]
Grato @brendonferreira.
Enviei um e-mail com apresentação e solicitação de participação no processo seletivo :)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
