### ISSUE TITLE
[Florianópolis/Remoto] Front-End Developer na Proteína Digital

### ISSUE THREAD

**Issue by eduardorph** [frontendbr/vagas#3102]
## Nossa empresa

A Proteína Digital é uma agência de marketing digital com foco em performance e geração de leads para seus clientes. Estamos em busca de um novo integrante para nosso time web.

## Descrição da vaga

Criar/editar landing pages e sites em diferentes plataformas, Webflow, Unbounce e Wordpress. Auxiliar na atualização de conteúdos nas páginas dos clientes.

## Local

Remoto ou Escritório, Florianópolis - SC

## Requisitos

**Obrigatórios:**
- Javascript ES6
- HTML
- CSS
- PHP
- Git

**Diferenciais:**
- Conhecimentos nas plataformas Webflow e/ou Unbounce
- Facilidade para trabalhar remoto

## Contratação

PJ

## Como se candidatar

Por favor envie um email para vagas.dev@proteina.digital com seu CV anexado e pretensão salarial - enviar no assunto: Front-End Developer na Proteína Digital

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Júnior

**Comment by thierryrene** [comment]
massa, vou me candidatar \o/

**Comment by fogeid** [comment]
Enviado!

**Comment by billisantos18** [comment]
essa vaga e so para quem mora em Santa Catarina ou que é de outro estado poder concorre?

**Comment by PandaZIM** [comment]
Ainda há vagas ?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by 1TATO** [comment]
E-mail enviado
