### ISSUE TITLE
[Florianópolis] JavaScript Developer na Kiper

### ISSUE THREAD

**Issue by ygorgasparin** [frontendbr/vagas#3106]
## Descrição da vaga

Estamos buscando alguém que já possua experiência em React, e que esteja disposta a trabalhar tanto no _front_ quanto no _mobile(RN)_. A empresa trabalha no ramo de portaria remota, com soluções de hardware, cloud e mobile. Esta vaga se destina a atuar no front dos serviços cloud e no mobile para fazer o meio de campo entre hardware e cloud.

## Local

Santa Mônica - Florianópolis/SC

## Benefícios

Temos VT integral + VA + Plano de saúde e odontológico + Vale Pantufa + Ginástica Laboral + Café delicioso todos os dias + Máquina do Café a disposição + Vale estacionamento

#### Diferenciais
 
- Chopp liberado todos os dias e um ambiente de trabalho para se sentir super a vontade!
- Estrutura extremamente horizontal e que valoriza a autonomia e pró-atividade de cada time

## Requisitos

**Obrigatórios:**
- JavaScript avançado;
- Test unitário;
- REST API;
- GIT;
- Clean Code.

**Desejáveis:**
- REDUX e ASYNC Storage;
- NodeJS;
- Mongo DB;
- GraphQL;

**Diferenciais:**
- Docker

## Contratação

CLT

## Nossa empresa

A Kiper é uma empresa que desenvolve uma solução tecnológica completa de acesso a condomínios, combinando economia, precisão e segurança.
Um pouco da empresa:
https://www.youtube.com/watch?v=T61PS6H-Wn8

## Como se candidatar

Por favor envie um email para ygor.gasparin@kiper.com.br com seu CV anexado - enviar no assunto: Vaga React - Github

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada etapa processo.
E-mail para contato em caso de não haver resposta: rh@kiper.com.br

## Labels

- 🏢 Presencial
- 👨 Pleno
- 👴 Sênior
- ⚖️ CLT
- 💰 A-Combinar

**Comment by lelecoral10** [comment]
Super oportunidade!!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by lelecoral10** [comment]
Vaga ainda aberta na Kiper!! Buscamos um Desenvolvedor com experiência sólida em React para somar a nossa família Kiper! Interessados podem fazer contato comigo também: rh@kiper.com.br ;)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
