### ISSUE TITLE
[Porto Alegre] Full-Stack-end Developer na SOUTH SYSTEM

### ISSUE THREAD

**Issue by kaueny** [frontendbr/vagas#3107]
## Descrição da vaga

A SOUTH SYSTEM está em busca de uma pessoa desenvolvedora Full-Stack Pleno/Sênior que queira fazer parte do nosso propósito de impulsionar as pessoas para inovar o mundo. Para fazer parte do time, há algumas skills que valorizamos muito, e não estamos falando apenas de tecnologia, nós valorizamos profissionais que respeitem o próximo e suas diferenças, que sejam leais e responsáveis com as entregas e com as pessoas. A colaboração e engajamento devem fazer parte do dia a dia para que o resultado seja eficaz e que tenha sede de aprendizado para trabalhar com inovação contínua.

## Local

Porto Alegre/RS (após o cenário do coronavírus, será presencial)

A oportunidade é PRESENCIAL em Porto Alegre/RS. Nesse momento, estamos todos atuando de forma remota, mas quando o cenário do coronavírus passar, todos iremos retornar aos nossos escritórios. Sendo assim, a oportunidade é apenas para quem possui disponibilidade de atuar em Porto Alegre/RS.

## Requisitos

**Procuramos alguém que tenha:**

- Experiência com HTML, Javascript e CSS;
- Experiência no consumo de APIs Restful;
- Conhecimento avançado em React.js;
- Conhecimentos em ferramentas de empacotamento/build de aplicações hibridas mobile;
- Experiência com ferramentas de versionamento como Git;

**Será um diferencial bacana:**

- Conhecimento em Bootstrap e Material CSS;
- Conhecimento em React Native;
- Conhecimentos em Node.s;

## Contratação

PJ ou cooperado

## Nossa empresa

https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-SOUTHSYSTEM-EI_IE2433278.13,24.htm

## Como se candidatar

Se interessou pela oportunidade e curte ambientes que invistam no teu desenvolvimento? Então não perde tempo e envia o teu currículo para kaueny.martins@southsystem.com.br

## Labels

- Alocado
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
