### ISSUE TITLE
[Remoto] Mobile Developer na Joyjet

### ISSUE THREAD

**Issue by PachecoRaphael** [frontendbr/vagas#3108]
##  Descrição da vaga

Hello, 

Joyjet is looking for a mobile developer, We have a lot of different projects from e-commerce to interns app for businesses.

We have app projects for iOS, Android in Swift, Object C, Java and React Native. 

A big part of the team speaks Portuguese but we all communicate in English via messages. Only the calls with the team are in Portuguese. 

If you are interested please do these tests and send us the repo URL so we can check:

Android: https://bitbucket.org/lixao/tech-interview/src/master/android/

iOS: https://bitbucket.org/lixao/tech-interview/src/master/ios/

## Local

Remoto

## Benefícios

- Plano de saúde
- Free course to study

## Requisitos

**Obrigatórios:**
- 3 years of experience
- Java
- Obejective C
- Swift
- HTML/CSS
- GIT

**Desejáveis:**
- React
- React Native
- Flutter

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para jobs@joyjet.com com seu CV anexado - enviar no assunto: VAGA Mobile developer 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

Test asked to all new members:

Android: https://bitbucket.org/lixao/tech-interview/src/master/android/

iOS: https://bitbucket.org/lixao/tech-interview/src/master/ios/

## Labels

- PJ
- Pleno
- Remoto
- Swift
- Java
- Objective C

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
