### ISSUE TITLE
[Remoto] Front-end Developer (WordPress) na Parceiro Programador

### ISSUE THREAD

**Issue by lincolnlemos** [frontendbr/vagas#3109]
## Descrição da vaga

Estou procurando um desenvolvedor WordPress de nível intermediário ou avançado que tenha expertise na criação de temas do zero, não é necessário PHP avançado. Se tu consegue criar um tema do zero, domina responsivo e ACF, manda um alô :)

Você faz seu horário, mas é preciso ter disponibilidade em horário comercial para reuniões, tirar dúvidas e planejamento em grupo. 

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Ter criado temas WordPress do zero
- Expert em responsivo
- Dominar os conceitos de actions e filters do WordPress
- Entender de requisições HTTP

**Desejáveis:**
- Experiência com qualquer framework JS (preferência Vue)
- Experiência em trabalho remoto
- Experiência em integração de API's

**Diferenciais:**
- PHP avançado, conhecimento em Laravel
- Expert em Vue
- Inglês avançado
- Optimização e SEO

## Benefícios

- Horários flexíveis
- Subsídio para cursos/eventos
- Bônus por resultados

## Contratação

PJ a combinar.  Range conforme nível de experiência. 2.5k~4.5k + bônus de resultados. 

## Como se candidatar

Por favor envie um email para vagas@partnerprogrammer.com. No assunto, use "[Remoto - WordPress ] -  $seu_nome". No corpo do texto, escreva o por que você acredita ser o perfil ideal. Não se esqueça de mandar trabalhos já feitos e ou/experiência nos assuntos mencionados. E pra ver se tu leu esse texto até o final, manda também seu prato de comida favorito :)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by programador-pedroreis** [comment]
Enviado e-mail, veja meu site http://programador-pedroreis.github.io/
