### ISSUE TITLE
[São Paulo] Front-end Developer na Digi

### ISSUE THREAD

**Issue by luisa-haddad** [frontendbr/vagas#3110]
## Descrição da vaga

São 3 portais com características semelhantes funcionais e visuais. O Portal é voltado para um público interno, portanto com Login e características especificas para aquele usuário. O projeto já está em andamento.

## Local

100% Remoto

## Requisitos

**Obrigatórios:**
- React
- MongoDB
- Mongoose
- TypeScript

**Desejáveis:**
- Styled Components
- GraphQL
- AntD
- Storybook
- Lerna

## Contratação

PJ

## Como se candidatar

Por favor envie um email para luisa@digi.ag com seu CV | Linkedin - enviar no assunto: Vaga Developer na Digi

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: luisa@digi.ag

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Sênior
- Especialista

**Comment by thalesf** [comment]
Boa noite, aceita part-time ?

**Comment by luisa-haddad** [comment]
> Boa noite, aceita part-time ?

Boa noite Thales, pra essa vaga somente Full mesmo.

**Comment by lucaspmarra** [comment]
Boa noite!
Como estão as vagas de trainee/júnior?

**Comment by luisa-haddad** [comment]
> Boa noite!
> Como estão as vagas de trainee/júnior?

Boa Noite Lucas, no momento não tenho.

**Comment by mrangel-jr** [comment]
Qual é a faixa de remuneração ?

**Comment by luisa-haddad** [comment]
> Qual é a faixa de remuneração ?

Bom dia Rangel, vai depender muito do perfil que encontrarmos. 8k a 12k

**Comment by ribeiroevandro** [comment]
Email enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
