### ISSUE TITLE
[São Paulo/SP] Front-end Developer Pleno no Itaú-Unibanco

### ISSUE THREAD

**Issue by nathaliaambrosio** [frontendbr/vagas#3112]
## Local

Conceição, São Paulo/SP  

## Requisitos 💼

•	Conhecimento em desenvolvimento em Javascript, Html, Css;
•	Experiência em Angular ou React/Vuejs;
•	Experiência com metodologias ágeis;

## Contratação

CLT direto com o Itaú / Salário a combinar.

## A empresa

O banco Itaú e a maior instituição bancária privada do Brasil.

## Como se candidatar ✍ 

Por favor envie um e-mail para thais.mourato@beit.work com seu CV anexado - enviar no assunto: Vaga Frontend

**Comment by agnezi** [comment]
Enviei e-mail.

**Comment by rjcjunior** [comment]
Vaga ainda aberta?

**Comment by nathaliaambrosio** [comment]
Temos 1 vaga aberta ainda!

**Comment by ylanbenoliel** [comment]
Email enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
