### ISSUE TITLE
[Rio do Sul/SC] Front-End: React-Native na Riderize

### ISSUE THREAD

**Issue by fabriciosautner** [frontendbr/vagas#3113]
## Nossa empresa

O Riderize é a concepção de um App para um nicho de mercado que é atendido por uma grande indústria nacional dona do projeto.

## Descrição da vaga

Desenvolver em React Native o App Mobile.

## Local

Escritório em Rio do Sul - Santa Catarina 

## Requisitos

**Obrigatórios:**
- Estar familiarizado com linguagens de programação 

**Desejáveis:**
- Estar familiarizado com React Native (Stacks JS)

**Diferenciais:**
- Ter realizado o curso da Rocketseat

**Diferenciais:**
- Horário relativamente flexível, principalmente o almoço.
- Trabalhar com MacOS :D 
- Ambiente de trabalho moderno e descontraído
- Autonomia de desenvolvimento

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para fabricio.sautner@carrodemola.com.br com seu interesse para marcar uma Call de entrevista

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

#### Alocação
- Alocado Físicamente

#### Regime
- PJ

#### Nível
- Júnior em diante (vagas para ambos)

**Comment by rodgomesc** [comment]
Possibilidade de ser remoto?

**Comment by fabriciosautner** [comment]
Oi @rodgomesc !

As vagas são presencias, entendemos a necessidade de formar um time focado no mesmo objetivo. Temos para Backend também NodeJS.

**Comment by rodgomesc** [comment]
> Oi @rodgomesc !
> 
> As vagas são presencias, entendemos a necessidade de formar um time focado no mesmo objetivo. Temos para Backend também NodeJS.

ok, caso não encontrem precial estou a disposição

**Comment by fabriciosautner** [comment]
Processo encerrado.
