### ISSUE TITLE
[Salvador] Front-end Developer na Cubos Tecnologia

### ISSUE THREAD

**Issue by beatriz407** [frontendbr/vagas#3114]
## Nossa empresa

A Cubos uma desenvolvedora de softwares e, nos nossos projetos, utilizamos metodologias ágeis. Vamos muito além do desenvolvimento para fazer a diferença na vida das pessoas. Oferecemos um ambiente colaborativo, com uma galera massa trabalhando em busca da evolução contínua e prezando por fazer entregas foda.

## Descrição da vaga

- Participar ativamente das etapas de ideação, planejamento e desenvolvimento dos produtos dos nossos clientes;
- Participar de discussão das tecnologias que serão utilizadas nos projetos;
- Desenvolvimento de aplicações web responsivas com React.js, consumindo web services, baseadas em layouts feitos por nossos designers, visando uma UX de excelência;
- Deploy com continuous integration / continuous deployment;
- Ser curioso e estar disposto a se arriscar em novas tecnologias;
- Disposição para ajudar e compartilhar conhecimento.

### Nossa Stack Frontend 

- React
- Typescript
- MobX
- GatsbyJS
- NextJS
- Sass
- Styled Components
- GraphQL
- Jest
- GitLab CI

## Local

Escritório, Salvador - Caminho das Árvores. Por conta do Coronavírus, o trabalho será remoto até que a situação seja normalizada.

## Requisitos

**Obrigatórios:**

- Conhecimento de Javascript;
- Experiência com HTML e CSS;
- Conhecimento com algum framework javascript (React, Vue, Angular);
- Sabe fazer integração com APIs;
- Conhecimento em gerenciamento de estado global;
- Saber debbugar o código.

**Desejáveis:**

- Conhecimento de React;
- Conhecimento em versionamento com Git.

**Diferenciais:**

- Experiência com testes automatizados no frontend;
- Experiência com GraphQL;
- Conhecimento em acessibilidade e SEO;
- Experiência com back-end, Node em especial;
- Apresentação de portfólio, Github ou similares;
- Habilidades em padrões de design de interface e experiência de usuário;
- Conhecimento em pré-processadores de CSS (Sass, Stylus, Less, etc) ou CSS in JS (styled-components, emotion, etc).

## Benefícios

- Vale refeição ou alimentação (R$ 26,00 por dia);
- Plano de saúde;
- Plano odontológico.

**Diferenciais:**

- Happy hour mensal;﻿
- Aulas semanais multidisciplinares.

## Contratação

CLT

## Como se candidatar

Se inscreva em: https://bit.ly/vempracubos

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 8 dias após cada processo.

#### Alocação
- Salvador

#### Regime
- CLT

#### Nível
- Júnior

**Comment by rafaassism** [comment]
Boa tarde, @felipefialho!

Gentileza remover o label de remoto e inserir o de Salvador.

Obrigada :)

**Comment by ViniciusPuerto** [comment]
Boa tarde, o formulário está acusando que é nessária permissão do proprietário.

**Comment by pablojr17** [comment]
### **Necessária permissão do proprietário**

**Comment by beatriz407** [comment]
Foi corrigido, podem dar uma olhada ;)

**Comment by TalesHabib** [comment]
Enviado!
