### ISSUE TITLE
[São Paulo] TECH LEAD na startup Colab

### ISSUE THREAD

**Issue by rodriguesvini** [frontendbr/vagas#3115]
Estamos buscando talentos para atuar como Tech Lead no Colab, a startup que nasceu para ajudar os cidadãos a ter voz!

O Colab é uma plataforma interativa que conecta cidadãos diretamente à construção de cidades melhores. Através do aplicativo, é possível identificar e fiscalizar problemas, avaliar serviços e espaços públicos e participar de tomadas de decisão da sua comunidade. O propósito do Colab é democratizar o protagonismo urbano, permitindo que todos possam praticar a cidadania, da palma de sua mão, de onde estiver! Com uma proposta inovadora e 7 anos de história, o Colab já foi premiado diversas vezes. Dentre suas premiações, já foi considerado o melhor aplicativo urbano do mundo pela New Cities Foundation,  startup com maior potencial global pelo Banco Interamericano de Desenvolvimento e Banco Santander. No Colab, todos empreendem como donos e tem autonomia para despertar o melhor de si, crescer e criar conexões para a vida!

O Tech Lead no Colab será o(a) responsável por liderar a equipe (desde garantir o desempenho, serviço e melhorias técnicas, como também proporcionar o desenvolvimento da área e do time). A visão holística do negócio será fundamental, uma vez que como Tech Lead você terá uma participação estratégica e contato direto com os stakeholders da empresa. A mão na massa também não ficará de lado, então excelência técnica como desenvolvedor(a) é o que buscamos, considerando que servirá de referência para outras pessoas. É uma oportunidade de protagonizar melhorias, criar e crescer junto com uma equipe colaborativa, diversa, jovem e dinâmica! 

Requisitos:
• Experiência com desenho e arquitetura de soluções;
• Domínio das tecnologias: React, HTML, CSS, JavaScript, NodeJs e Express;
• Visão estratégica de negócio, conhecimento de metodologias ágeis e habilidade de gestão de times;
• Experiência com ambiente Cloud e conhecimento de Bancos de Dados Relacionais.

Diferenciais: 
• Experiência em empresas de produto ou em empresas de responsabilidade social.
• Experiência com tecnologias mobile para desenvolvimento nativo.

Contratação:
A contratação será feita em regime PJ, alocado na sede em São Paulo. A remuneração é competitiva, no entanto é confidencial. Há possibilidade de stock options! 

Para conhecer mais da oportunidade e participar do processo com a gente, é só acessar: https://bit.ly/2zD4UhS

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
