### ISSUE TITLE
[Rio de Janeiro | Remoto | Freelance] Front-end Developer na Octos

### ISSUE THREAD

**Issue by igormq** [frontendbr/vagas#3116]
## Nossa empresa

A [Octos](octos.ai) é a startup de Inteligência Artificial aplicada ao videomonitoramento para o mercado de segurança privada. Nossos algoritmos de Visão Computacional e Deep Learning transformam qualquer câmera em um dispositivo inteligente. Achou legal? Ainda tem nuvem, IoT e edge, só não temos blockchain (ainda! rs). 

## Descrição da vaga

Temos uma vaga aberta para um trabalho de *freelancer*.

A vaga consiste no desenvolvimento dos nossos aplicativos web e mobile (UX, UI, e o Wireframe/Componentes utilizando React e React Native). Queremos dar uma roupagem linda à nossa ideia. 

Esse trabalho tem uma duração estimada de **dois meses**. Uma vez entrando em contato conosco você receberá as especificações do projeto e deve enviar uma proposta com o valor e o que será entregue.

Não se preocupa muito com o horário, nós somos bastante flexíveis e a aceitamos trabalho remoto mesmo em épocas de não pandemia, afinal startup é isso. 

## Local

No conforto de sua casa

## Requisitos

**Obrigatórios:**
- Experiência com UX e UI
- Experiência em desenvolver componentes em React e React Native

**Desejáveis:**
- CSS3, HTML, NodeJS e Typescript

**Diferenciais:**
- Projetos open source (para que a gente possa melhor avaliar você)
- Entregar a documentação e as componentes no StoryBook.js :)

## Contratação

PJ, pois é necessário emitir uma nota fiscal !

## Como se candidatar

Por favor envie um email para recrutamento@octos.ai com seu CV anexado - enviar no assunto: Vaga FrontEnd

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: contato@octos.ai

#### Alocação
- Remoto

#### Regime
- Freela

#### Nível
- Pleno

**Comment by alessandroprudencio** [comment]
Já encontrou alguém ?

**Comment by igormq** [comment]
Olá gente, muito obrigado pelos mais de duas dezenas de currículos recebidos! Estamos dando feedback aos poucos para cada uma das pessoas.

Grato,
Igor!
