### ISSUE TITLE
[Florianópolis - SC / Remoto temporário] Fullstack Developer na Prevision

### ISSUE THREAD

**Issue by startecjobs** [frontendbr/vagas#3117]
## Sobre a Prevision
A Prevision veio para revolucionar o mercado da construção civil no Brasil. Uma das indústrias com maior poder de impacto socioeconômico no país, a construção civil sofre com baixa inserção de tecnologia, grandes desperdícios e pouca previsibilidade, principalmente em momentos de incertezas.

## Descrição da vaga

Se você tem perfil empreendedor, gosta de desafios, quer oportunidades de crescimento e tem um perfil analítico, essa vaga pode ser pra você: buscamos desenvolvedor(a) compor o time de tecnologia que irá ajudar a mudar a construção civil no país.

## Local

Exemplo: Saco Grande, Florianópolis - SC

## Requisitos

**Técnicos:**
• Vue.JS
• Ruby on Rails
• Javascript

**Desejáveis:**
• Teste de software
• Conhecimento em metodologias ágeis

## Benefícios

• Salário de R$ 5.500,00 a R$ 7.000,00

## Contratação

PJ 

## Como se candidatar

Acesse https://bit.ly/WebDev-Prevision e se inscreva. Essa é uma página com todo o descritivo da vaga. Todas as etapas do processo seletivo serão enviadas por email após o cadastro.

Para mais informações envie um email para contato@startecexp.com

## Tempo médio de feedbacks

Costumamos enviar feedbacks ao final do processo.
E-mail para contato em caso de não haver resposta: contato@startecexp.com

#### Alocação
- Alocado (inicialmente remoto por conta do isolamento)

#### Regime
- PJ

#### Nível
- Pleno

**Comment by vachterberg1** [comment]
Vocês aceitam pessoas com experiência em React ou a vaga é apenas para Vue?

P.S: De Florianópolis

**Comment by startecjobs** [comment]
> Vocês aceitam pessoas com experiência em React ou a vaga é apenas para Vue?
> 
> P.S: De Florianópolis

É necessário ter conhecimento em Vue.JS e Ruby on Rails, principalmente.

**Comment by nandomoreirame** [comment]
Enviado.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
