### ISSUE TITLE
[Encerrado]

### ISSUE THREAD

**Issue by maxmeio** [frontendbr/vagas#3119]
## Descrição da vaga

Transformar, fielmente, o layout de XD para HTML, CSS e Javascript. Auxiliar na inserção de conteúdo e ajustes de front-end.

## Local

Sede Principal, Natal - Petrópolis (Trabalhamos de forma presencial, porém durante a quarentena, estamos home office).

## Requisitos

**Obrigatórios:**
- Ótimo domínio em HTML, CSS e Javascript
- Experiência com Bootstrap
- Experiência com layout responsivo
- Ser fiel para detalhes do layout

**Desejáveis:**
- Conhecimento básico em Laravel (Não será para ajustes ou desenvolvimento de back-end, apenas para desenvolver o front-end dentro da base do Laravel, para adiantar a vida dos programadores)

**Diferenciais:**
- React

## Contratação

CLT/PJ a combinar - Necessário que possa trabalhar presencialmente, na nossa sede em Natal/RN (Estamos Home Office apenas durante a quarentena).

## Como se candidatar

Encerrado

## Tempo médio de feedbacks

Buscamos enviar feedbacks durante o processo, de acordo com a análise de cada currículo.

#### Alocação
- Alocado

#### Regime
- CLT
- PJ

#### Nível
- Júnior
- Pleno

#### Local
- Encerrado

**Comment by maxmeio** [comment]
@felipefialho a vaga é apenas para Natal/RN, blz? Tem uma label para São Paulo, se poder, substitui por Natal/RN, por favor.

**Comment by eriktos** [comment]
enviado!
