### ISSUE TITLE
[Porto Alegre] Angular Developer na DBServer

### ISSUE THREAD

**Issue by AlineSchorn** [frontendbr/vagas#3120]
## Nossa empresa

A DBServer é uma Softwarehouse gaúcha que constrói entregas sob medida. Há 27 anos trabalhamos com foco nas pessoas, guiados por nossos valores, crescendo lado a lado com nossos colaboradores. Nosso lema é fazer a coisa certa do jeito certo através do design e do build.

Nos últimos anos, iniciamos uma caminhada em direção a diversidade e a inclusão e após o lançamento do nosso Marco Ético temos agora um norteador dos princípios que irão trilhar a nossa trajetória.

Estamos orgulhosos de promover um ambiente de trabalho livre de discriminação. Acreditamos que a diversidade de experiências, perspectivas e histórico transforma nosso ambiente de trabalho. Estamos empenhados a construir esse legado com a sua parceria! 

Conheça nosso Marco ético: http://www.dbserver.com.br/marcoetico/

## Descrição da vaga

Nessa posição, você encontrará a possibilidade de trabalhar com times ágeis, montando soluções para diversos órgãos públicos do Estado.

## Local

Porto Alegre - RS

## Requisitos
Curso Superior em Informática ou Egresso de Informática completo ou em andamento;
Conhecimento técnico e experiência em Angular, HTML5, JSON, CSS, Javascript, Ajax, jQuery, nodeJS, ECMAScript e TypeScript;
Orientação a objetos e UML;
Desenvolvimento RESTful;
Métodos Ágeis;
Software de controle de versão GIT.

## Benefícios

- Plano de saúde
- Seguro de vida
- Vale Refeição
- Plano Odontológico

**Diferenciais:**
- horários flexíveis
- ambiente diverso
- troca de conhecimento
- oportunidade de aprender muito \o/

## Contratação

CLT

## Como se candidatar
Você pode se candidatar através do seguinte link: 
https://jobs.kenoby.com/dbserver/job/dev-front-end-angular/5ea1e71b65fb0d485bf971d2

Ou nos enviar um email para poa_selecão@dbserver.com.br com seu CV anexado 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: poa_seleção@dbserver.com.br

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível

- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by AlineSchorn** [comment]
Essa vaga segue aberta! Temos mais de uma vaga para o projeto :)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
