### ISSUE TITLE
[Curitiba/Remote] Front-end Developer+DB Administrator na Visionnaire

### ISSUE THREAD

**Issue by raulbalestra** [frontendbr/vagas#3121]
Hello All,

We are lookig for a team, 2 Front-End engineers and a DB adminitrator with Mongodb skills.

Customer
Director of Engineering of a US-based startup

Business
a car dealers website platform 

Requirements
the customer is looking for 2 Senior level full-stack engineers and 1 Database Administrator with MongoDB.

Backend skills:
Node.js
Elasticsearch
Redis
MongoDB
MySQL
Kubernetes
Docker
RabbitMQ
 
Front end skills:
Vue.js
Bootstrap
Sass
Javascript
HTML
CSS

General skills:
Git
Micro services architecture
Google cloud
Scrum

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para raul.balestra@visionnaire.com.br com seu CV anexado - enviar no assunto: Front-end Developer+DB Administrator

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
