### ISSUE TITLE
[São Paulo- Berrini] Front React Developer Pleno na BRQ Digital Solutions

### ISSUE THREAD

**Issue by ReAnne123** [frontendbr/vagas#3124]
Descrição da vaga
Estamos em busca de profissionais com experiência em React, para atuar em projeto global para grande multinacional. Prazo indeterminado de contratação com muita chance de crescimento. 

Local
Durante o período da pandemia de Covid-19, será home office, normalizando, será presencial na Berrini-SP.

Benefícios
-vale refeição
-vale alimentação
-seguro de vida
-plano médico Bradesco
-previdência privada
-plano odontológico

Requisitos
Experiência em React e Bootstrap

Contratação
CLT full pela BRQ.

Nossa empresa
Fundada em 1993, a BRQ Digital Solutions é uma das maiores empresas de serviços de TI do país. Conta com 2500 profissionais distribuídos nas filiais de São Paulo, Alphaville, Rio de Janeiro, Curitiba e Nova Iorque.

Como se candidatar
Por favor envie um email para Renata- ryokota@brq.com, com seu CV anexado - enviar no assunto: Vaga React Pleno.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
