### ISSUE TITLE
[Remota] Front-End Developer na [BXBLUE]

### ISSUE THREAD

**Issue by Rebeccapz** [frontendbr/vagas#3125]
**A Empresa**
A bxblue é uma fintech com a missão de ajudar as pessoas a terem acesso ao crédito pessoal mais barato do país. Fomos investidos por grandes nomes do cenário nacional e internacional. Dentre eles a Y Combinator (Aceleradora responsável por empresas como AirBnB, Dropbox, Heroku, Docker e Twitch). Também tivemos a honra de sermos selecionados pelo Banco do Brasil para co-criarmos juntos a primeira API de Empréstimo do Brasil. Também saímos na lista das 100 Startups para ficar de olho em 2019.

**O Time**
Nosso time é super enxuto, composto por pessoas das mais diversas histórias, habilidades e experiências. Nós trabalhamos em prol de construir nosso produto e usar as melhores ferramentas à nossa disposição.
Trabalhamos junto às demais áreas da empresa para garantir que todo mundo saia ganhando: os clientes, os bancos, nosso time e é claro, a bxblue.
Estamos a procura de pessoas diferentes que possam contribuir não em número, mas com pontos de vista, vivências e competências diferentes para nosso time.

**O que você vai fazer?**
Essa posição não tem apenas uma fronteira, você nos ajudará em diversos desafios. Pode ser junto ao usuário, ajudando-o a resolver as dificuldades com o produto, sempre próximo aos times de negócio (marketing ou vendas) ou conjunto com as equipes dos bancos parceiros. Desenvolvendo soluções que otimizem suas atividades ou integrando com ferramentas internas e externas.
Você atuará em equipe para discutir, desenhar e construir soluções estratégicas para problemas reais. Indo da compreensão a entrega e acompanhamento do valor gerado.
Nossa stack não é nossa lei, nosso interesse é encontrar as melhores ferramentas. Aqui você terá espaço para se desenvolver e aprimorar nas tecnologias que usamos e na escolha de novas opções.

**Requisitos**
O que você **PRECISA** para concorrer a essa vaga?

- Saber se comunicar em Inglês e Português
- Se sentir à vontade no desenvolvimento, manutenção e deploy de aplicações web
- Ter disponibilidade para trabalhar em período integral
- Se envolver com nosso propósito e nos ajudar com a nossa missão

O que você **NÃO PRECISA** para concorrer a essa vaga?

- Morar perto da gente (somos remotos)
- Ser fluente na nossa Stack de Desenvolvimento (teremos espaço para você desenvolver suas habilidades conosco)

**Remuneração**
Procuramos pessoas de todo o espectro de experiências. Ou seja, se você está ainda no começo da carreira ou já em muita estrada, temos espaço. A remuneração para esta vaga depende do nível em que a pessoa se encaixar podendo ir de R$ 2.600,00 a R$ 12.600,00.

Se interessou? Basta se candidatar nesse link: https://bit.ly/bxdev2020

Trabalhamos com um tempo médio de resposta de 3 à 5 dias

**Comment by rafaelkendrik** [comment]
Olá @Rebeccapz, tudo bem?
Por favor, é necessário que você estruture o título da vaga conforme o padrão do frontendbr:
https://github.com/frontendbr/vagas#cadastrando-uma-vaga

**Comment by Haple** [comment]
Enviei minha candidatura :) @Rebeccapz

**Comment by Rebeccapz** [comment]
Oi @rafaelkendrik arrumando já!

**Comment by Rebeccapz** [comment]
@Haple Obrigadaa por se candidatar, vou avaliar o teste e te dar uma resposta o mais rápido possível :)

**Comment by Qnedy** [comment]
Olá, @Rebeccapz.
Pode informar o formato de contratação?
obg

**Comment by tech3br** [comment]
Enviado! 🤝🏼 valeu bxblue! 💜🙏

**Comment by felipebc11** [comment]
Acabei de enviar @Rebeccapz aguardo o feedback.🙏

**Comment by KaoYuChunG** [comment]
Enviado!  obrigado bxblue! 🙏

**Comment by Marcosnto** [comment]
Enviado! Obrigado 💜

**Comment by DuplamenteH** [comment]
Qual a Stack de Desenvolvimento?

**Comment by KaoYuChunG** [comment]
Frontend

Em qui, 14 de mai de 2020 01:30, Carlos Matheus <notifications@github.com>
escreveu:

**Comment by euaaron** [comment]
Provavelmente nem tem mais vagas e mesmo se tiver nem devo ser selecionado, mas preenchi lá.
