### ISSUE TITLE
[São Paulo/Remoto] Front-End Developer Pleno/Sênior [B8ONE/PLUGONE]

### ISSUE THREAD

**Issue by hugoalvarenga** [frontendbr/vagas#3126]
## B8One/PlugOne

Somos um laboratório de soluções digitais inovadoras, apaixonada por tecnologia e focada em resultado. Aqui temos profissionais dos mais diferentes perfis em um ambiente descontraído e extremamente produtivo. 

## Descrição da vaga

Como desenvolvedor Front-End, você terá como atribuição o desenvolvimento de interfaces e integrações para o produto PlugOne. A abordagem de novas tecnologias e proposta de utilização de padrões são sempre bem vindas em nosso time.

## Local

Remoto ou Escritório, São Paulo - Vila Olímpia

## Requisitos

**Obrigatórios:**
- 2+ anos de experiencia como desenvolvedor Front-End (utilizando ReactJS ou ECMAScript);
- Fluente com a tecnologia ReactJS;
- Experiência em GraphQL;
- Experiência em Typescript;
- Conhecimento em padrões de projeto e melhores práticas em desenvolvimento de softwares;
- Inglês intermediário;
- Styled Components

**Desejáveis:**
- Conhecimento em processos de e-commerce;
- Conhecimento em NodeJS;
- 1+ de experiencia em micro-frontends;

**Diferenciais:**
- conhecer plataformas de e-commerce, como: Magento, VTEX, Shopify;

## Benefícios

- Horário Flexível
- Macbook Pro, deixe sua máquina como desejar. =))
- Happy Hour às sextas (em época de não corona)
- Ambiente descontraído
- No dress code

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para jobs@b8one.com com seu CV anexado e Github - enviar no assunto: [VAGA] Front-End Developer - Front-End Brasil

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 4 dias após cada processo.
E-mail para contato em caso de não haver resposta: hugo@b8one.com

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by vachterberg1** [comment]
Tenho experiência de 1 ano e meio, posso me candidatar a vaga?

**Comment by andrecampll** [comment]
Boa noite, enviei o cúrriculo! 🚀

**Comment by carlitoshxcx** [comment]
Enviado 👍
