### ISSUE TITLE
[Sāo Paulo] Estágio em desenvolvimento Wordpress na BLU365

### ISSUE THREAD

**Issue by raphaguasta** [frontendbr/vagas#3127]
## Nossa empresa

Com a proposta de ajudar os brasileiros a negociarem suas dívidas e a se manterem no azul sempre, a BLU365 oferece uma plataforma de negociação fácil, intuitiva e digital, para seus clientes ficarem no azul o ano todo.

## Descrição da vaga

**Aqui você vai trabalhar com:**

- Desenvolvimento de temas responsivos e performáticos para Wordpress
- Desenvolvimento de plugins Wordpress
- Docker
- Serviços AWS
- Consumo de APIs client e server side

**O que esperamos de você:**

- Preocupado com organizaçāo e qualidade do código
- Acompanhar as novidades e atualzaçōes, a tecnologia evolui rápido!
- Estudo e aprendizado constante (temos cursos pagos pela empresa)
- Habilidade de evoluir por conta própria
- Nāo ter apego a frameworks, libs... Código é código!

## Local

Estamos no Cubo Itaú, o maior centro de empreendedorismo tecnológico da América Latina!
(Início remoto devido a pandemia)
Vila Olímpia - Sāo Paulo, SP

## Requisitos

**Obrigatórios:**
- Conhecimentos básicos em JS, HTML, CSS e PHP
- Conhecimentos básicos de desenvolvimento Wordpress (templates, pages, wp loop)

**Desejáveis:**
- Git
- Protocolo HTTP e consumo de APIs
- Familiaridade com ambiente Linux e uso de linhas de comando (shell)

## Benefícios

- Vale Transporte
- Vale Refeiçāo
- Férias
- Incentivo a cursos
- No Dress Code
- Horário flexível

**Aqui você também tem:**
- Refeitório com microondas
- Pebolim, mesa de ping-pong, sinuca
- Chopp free a partir das 18:00hrs :)

## Contratação

Estágio

## Como se candidatar

Encaminhar cvs para: estagios@blu365.com.br

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

## Labels
- Alocado
- Estágio

**Comment by eriktos** [comment]
Olá! Boa tarde! Tudo bem? Enviado! Aguardo feedback, ok?Obrigado!

**Comment by raphaguasta** [comment]
> Olá! Boa tarde! Tudo bem? Enviado! Aguardo feedback, ok?Obrigado!

Obrigado! :)

**Comment by fogeid** [comment]
É remoto?

**Comment by raphaguasta** [comment]
> É remoto?
Presencial. Remoto durante o pandemia.

**Comment by wagner-lima** [comment]
Boa tarde! 
CV enviado.
Obrigado! 😄

**Comment by lucassilva996** [comment]
Boa dia!
Currículo enviado.
Valeu!!

**Comment by raphaguasta** [comment]
Pessoal, finalizamos o processo seletivo.

Muito obrigado a todos que se candidataram, e fiquem a vontade para se candidatar nas próximas novamente! :)
