### ISSUE TITLE
[RIO DE JANEIRO] Front-end Developer na B2W Digital

### ISSUE THREAD

**Issue by DioneMorais** [frontendbr/vagas#3128]
==================================================
-->

## Nossa empresa

Hey, quer trabalhar em uma companhia certificada pelo Great Place to Work?

A B2W Digital é líder na América Latina e tem como propósito CONECTAR PESSOAS, NEGÓCIOS, PRODUTOS E SERVIÇOS EM UMA PLATAFORMA DIGITAL.

A Companhia possui as maiores e mais queridas marcas da internet (Americanas.com, Submarino, Shoptime e SouBarato) e uma operação de marketplace em rápido crescimento. A plataforma construída ao longo dos últimos anos permite que a B2W Digital também ofereça serviços de tecnologia, logística, distribuição, atendimento ao cliente e pagamentos.

Somos o maior e-commerce da América Latina e buscamos Desenvolvedoras(es) Back end que queiram absorver conhecimento e se desenvolver tecnicamente com a gente, pessoas que não tenham medo de inovar, com curiosidade para experimentar novas soluções e tecnologias, com versatilidade e sede de aprendizado, com experiência na criação de soluções eficientes, escaláveis e acessíveis. Ao mesmo tempo, como prezamos por um ambiente colaborativo intra e inter equipes, gostar de compartilhar conhecimento é primordial. Acreditamos que o crescimento profissional de toda a equipe é necessário para mantermos nossa cultura focada em resultados, e, por isso, valorizamos a partilha de conhecimento a todo o instante. Então se prepare para aprender constantemente com nossas equipes!
## Descrição da vaga

Nesse time, você terá a oportunidade de:

- Trabalhar com tecnologias disruptivas e inovadoras, com grandes desafios. Nossa equipe está em crescimento, e somos responsáveis por projetos críticos para a companhia, nossas aplicações estão todas escritas em React, com exceção de uma que está passando por um processo de reescrita, usando React no front e NestJS no nosso BFF. Aqui dentro voce irá encontrar também projetos em Golang, Java, Clojure e React Native. 

Além disso, irá desenvolver, testar, implantar, operar, monitorar, corrigir e melhorar (em alta complexidade/ impacto/ risco) aplicações, componentes e integrações, analisando os objetivos propostos, estudando as características dos dados de entrada e o processamento necessário a obtenção dos dados de saída desejados.

_Quer saber mais sobre o BIT?_

O BIT é o Hub tecnológico da B2W Digital; sua sigla significa: _B2W Inovação e Tecnologia_. Nossos times trabalham com _metodologias ágeis_. Os times têm _autonomia_ em como desenvolver os produtos e serviços, o que significa que escolhem as tecnologias utilizadas e a metodologia ágil de trabalho que possibilite agilidade nas entregas.

Somos movidos a resultados e trabalhamos para entregar soluções valiosas aos nossos clientes. Encorajamos _pair-programming_ e as interações diárias, porque acreditamos que o sucesso vem da diversidade, autonomia e colaboração. Trabalhamos em um ambiente “open space”, com diversas áreas e espaços colaborativos. Sim! Nós também temos Hackaton, o IronBit, e é muito divertido. Nessa maratona, qualquer pessoa tem a oportunidade de implementar sua ideia.

Somos apaixonados por tecnologia e gostamos de compartilhar isso com a comunidade. Por isso, participamos dos principais eventos de tecnologia do país como patrocinadores e como palestrantes (QCon, TDC, Big Data Week, Campus Party e Velocity). Também abrimos nossos espaços para receber os Meetups das comunidades de tecnologia, e, mais recentemente, disponibilizamos para a comunidade os projetos open-source Marvin (https://marvin.incubator.apache.org/) e RestQL (http://restql.b2w.io/).

 _Diversidade e Inclusão_
Queremos entregar tudo, a toda hora e em qualquer lugar. Para isso, estamos construindo uma equipe cada vez mais diversa, composta por pessoas criativas, engajadas e que respiram inovação e tecnologia. Buscamos oferecer oportunidades iguais a todas as pessoas, independente de gênero, etnia, religião ou orientação sexual. Aqui as pessoas têm voz e são incentivadas a desenvolver projetos disruptivos. Vem transformar o mundo digital!

## Local

Escritório - Saúde, Rio de Janeiro - RJ

## Requisitos

**Obrigatórios:**
- Conhecimentos sólidos de CSS3 como Flexbox;
﻿- Graduação completa em Ciência da Computação ou áreas relacionadas ou experiência profissional equivalente;
- Saber escrever código em HTML, CSS e javascript;
- Utilizar ferramentas de versionamento de código;
- Conhecer frameworks e bibliotecas Javascript;
- Entender como funciona o TDD e ferramentas de testes unitários como Jest, Mocha ou Chai;
- Conhecer pré-processadores CSS(Sass, PostCSS) e/ou ferramentas de CSS-in-JS, como styled-components, Emotion ou Glamorous;
- Utilizar GIT como ferramenta de versionamento de código;
- Saber como funciona o protocolo HTTP e o padrão REST;
- Conhecimento sólido sobre DDD e conceitos presentes no design;
- Utilizar ferramentas medidoras de performance e saber interpretar seus resultados para implementar melhorias nas aplicações.

**Desejáveis:**
- Ter familiaridade com sistemas ou linguagens tipadas estaticamente como Typescript, Flow, ReasonML;
- Entender arquitetura Flux e implementações como Redux;
- Ter conhecimento em React, pois é o que mais usamos em nossos projetos, porém aceitamos pessoas com conhecimentos em outras bibliotecas e frameworks como Vue e Angular;
- Conseguir estender soluções para BFFs que utilizem outros paradigmas de programação como OO ou Procedural.

**Diferenciais:**
- Conhecimento sobre tipagem de código com TypeScript;
- Implementar testes E2E;
- Conceitos de Domain Driven Design;
- Conhecimento de Node.JS e Backend-For-Frontend;
- Experiência com bibliotecas para testes E2E como Cypress, PhantomJs ou Selenium;
- Conhecimento sobre ferramentas de performance como Lighthouse;
- Conhecimento sobre Layout Otimista e Máquinas de Estado Finitas são bons diferenciais.

## Benefícios

- Vale Refeição ou Alimentação; 
- Assistência médica e odontológica; 
- Vale transporte;
- Seguro de vida;
- Plano de saúde

**Diferenciais:**
- Fazemos nossa proposta salarial de acordo com a sua pretensão, avaliação técnica e nosso plano de cargos e salários, para que tenha a sua cara;
- Horário flexível;
- Club de compras com descontos exclusivos nas nossas marcas;
- Vans e ônibus para levar nossa galera com conforto até pontos estratégicos do Centro(RJ);
- Meetups e eventos de tecnologia para troca de conhecimento;
- Muitos eventos internos: aniversariantes do mês, aniversário das marcas, festa junina, Halloween, black friday, entre outros;
- Áreas de descompressão como: shiatsu, sinuca, biblioteca, cadeira de massagem e vídeo game;
- Copa para refeições;
- Uma filial das Lojas Americanas dentro do nosso escritório para chamar de nossa <3;
- Dress code informal: Uso de bermuda liberado \o/

## Contratação

- CLT

## Como se candidatar

Diretamente na nossa página de carreiras: https://b2w.gupy.io/jobs/211023

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Regime
- CLT

#### Nível

- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
