### ISSUE TITLE
[REMOTE] Senior Frontend Engineer @Ubiminds

### ISSUE THREAD

**Issue by Ubiminds** [frontendbr/vagas#3129]
We’re looking for a **Senior Frontend Engineer** to join our stellar team. **Our positions are 100% remote**, working with teams mainly based in the United States.

**What you’ll do**
- Work in a multidisciplinary team combining the art of design with the art of programming;
- Work closely with other teams to help decide which features to build and how to build them;
- Ensure the design translates the values ​​and needs of the company;
- Deliver clean code.

### **Local**
You get to work 100% remote in teams mainly based in the United States, from Brazil.

### **Requisitos**
**In order to succeed in this position, you will need**
- Advanced/fluent English skills – Excellent written and verbal communication skills;
- JavaScript with strong ReactJS experience – TypeScript is a plus;
- Understands common front-end build tools like npm, yarn, webpack, etc;
- Strong HTML/CSS experience, preferably with a media company or publishing background (i.e. high attention to detail);
- Experience with GatsbyJS or other static site-generators;
- Previous experience with WordPress – PHP or Ruby on Rails development experience are a plus;
- High degree of attention to detail and methodical when solving problems;
- Self-motivated with a high-sense of urgency around work;
- Strong ownership and accountability;
- Comfortable working in a Kanban/Agile environment;
- Used to task management tools like Jira.

### **Nossa empresa**
We at Ubiminds are a talent powerhouse, sourcing, recruiting and hiring sought-after tech professionals, from mid-level to leadership positions. Find out firsthand what it's like to work remotely for American SaaS companies from Brazil by listening to what customers and employees have to say: https://www.youtube.com/watch?v=GxfqmIPKxN8.

### **Como se candidatar**
Apply at https://ubiminds.com/sr-frontend-engineer/

**Labels**
🏢 Remoto
👴 Sênior
⚖️ PJ

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by Ubiminds** [comment]
Só para deixar claro, são 4 posições abertas. :)

**Comment by tiagocarmosantos** [comment]
Ola! Estou interessado. Gostaria de me candidatar, como faço?

**Comment by tiagocarmosantos** [comment]
Acabei de ver o Apply at
