### ISSUE TITLE
[São Paulo] Front-End Developer Angular

### ISSUE THREAD

**Issue by gpsanches** [frontendbr/vagas#313]
## Front-End Developer [Pleno | Senior]

Você possui habilidades para resolver problemas variados, "código clean", capacidade de simplificar problemas complexos e explicá-los para audiências diferentes, proatividade e um espírito mão na massa?

Oferecemos um ambiente descontraído, autonomia para tomar decisões, frutas no andar e outros benefícios bem legais.

Além do trabalho de programação, no seu dia a dia você também estará envolvido em decisões importantes relacionadas à arquitetura de sistemas e infraestrutura que suportam nossos sistemas. Você fará parte de uma equipe especializada, trabalhará junto aos líderes e terá a oportunidade de desempenhar um papel chave na construção de uma startup que está em crescimento acelerado, além de desenvolver software inovador no segmento de Cloud com tecnologia de ponta.

Você terá oportunidade de trabalhar em uma empresa parceiras da AWS.

## Local

Escritório, São Paulo - Morumbi (atrás do shopping Morumbi)

## Benefícios

- Café a vontade
- Frutas a vontade
- Video Game
- Vale transporte ou ajuda de custo no combustível
- Vale refeição
- Convênio médico Bradesco
- Seguro de Vida
- Desconto na academia
- Curso de inglês

## Requisitos

**Obrigatórios:**
- Angular
- JavaScript
- Css
- BootStrap
- Grunt
- Node.js

**Diferenciais:**
- Noções de Ux
- Conhecimento em Python

## Contratação

CLT full

## Como se candidatar

link: https://www.linkedin.com/jobs/view/301260382/

**Comment by camilaibs** [comment]
Oi, seria júnior, pleno, sênior?

**Comment by gpsanches** [comment]
Pleno ou senior depende das skills
