### ISSUE TITLE
[Remoto] Front-end Developer na Partner Programmer

### ISSUE THREAD

**Issue by lincolnlemos** [frontendbr/vagas#3130]
## Nossa empresa

Somos um time pequeno com uma grande gama de projetos próprios e também atendementos clientes. Nosso time é e sempre vai ser remoto. Aqui a cultura é ser da paz. Você que faz seu horário, mas é preciso ter disponibilidade em horário comercial para reuniões, tirar dúvidas e planejamento em grupo quando necessário.

## Descrição da vaga

Estamos procurando um desenvolvedor javascript que acredita em si mesmo e entenda que a tarefa mais importante é **resolver problemas**. Preferimos Vue, porem se você manja React/Angular e tem interesse em trabalhar com Vue você também é bem vindo!

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Domínio em javascript
- Domínio de React ou Vue
- Domínio REST API

**Desejáveis:**
- Testes automatizados
- Experiência com animações web (css / gsap / scrollmagic)

**Diferenciais:**
- Experiência com laravel / adonis
- Inglês
- Veia empreendedora

## Contratação

PJ  -  R$ 4.000 e/ou a combinar baseado em experiência

## Como se candidatar

Por favor envie um email para vagas@partnerprogrammer.com. No assunto, use "[Remoto - FrontEnd ] - $seu_nome". No corpo do texto, escreva **o por que você** acredita ser o perfil ideal. **Não se esqueça de mandar trabalhos já feitos** e ou/experiência nos assuntos mencionados. Se você tiver vários projetos legais, envie apenas os dois melhores. E pra ver se tu leu esse texto até o final, manda também seu prato de comida favorito :)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: vagas@partnerprogrammer.com

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by HaluDeCassia** [comment]
@felipefialho boa noite. Tentei dar uma pesquisada sobre a empresa e não tenho certeza se achei o link certo. Tem algum para eu confirmar, por favor?

A propósito, boa vaga.

**Comment by lincolnlemos** [comment]
Obrigado @HaluDeCassia !  O link é https://partnerprogrammer.com

Se tiver qualquer outra dúvida estou a disposição.
Abraço

**Comment by guilhermecostalopes** [comment]
Enviado
