### ISSUE TITLE
[Recife] Front-end Developer na Bleu

### ISSUE THREAD

**Issue by luizpaulogodoy** [frontendbr/vagas#3131]
## Nossa empresa

A Bleu Empreendimentos é uma empresa voltada para criação e desenvolvimento de tecnologia em Blockchain. Combinamos a inovação e descontração para o desenvolvimento de projetos.

## Descrição da vaga

É desenvolvedor Front-end e está procurando um job?

Estamos buscando um desenvolvedor(a) front-end para somar à nossa equipe e que goste de trabalhar em um ambiente dinâmico, aprendendo novas tecnologias.

Se você gosta de trabalhar com inovação, é antenado, auto-didata, pro-ativo, possui um bom relacionamento interpessoal e gosta ou tem interesse de trabalhar em uma empresa com foco em **Blockchain** entre em contato conosco.

## Local

Remoto ou Escritório, Recife

## Requisitos

**Obrigatórios:**
- Conhecimento em HTML, CSS e Javascript
- Conhecimento em pelo menos um framework de aplicação web (reactjs, vuejs, angular, etc)
- Conhecimento em controle de versão com GIT
- Conhecimento de padrões de projeto

**Desejáveis:**
- Conhecimento em metodologias ágeis
- Conhecimento em devops

**Diferenciais:**
- Contribuição em projetos open source
- Publicação de artigos para compartilhamento de conhecimento
- Perfil de stackoverflow

## Benefícios

- Plano de saúde
- Seguro de vida
- Seguro funeral
- Vale Refeição / Alimentação
- Plano odontológico
- Auxilio lentes
- DayOff (no dia do Aniversário)
- Almoço BLEU (confraternização mensal)
- Auxílio Home Office

## Contratação

CLT

## Como se candidatar

Por favor envie um email para rh@bleu.com.br - enviar no assunto: [Front-end]

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.

#### Alocação
- Presencial
- Remoto
- Recife

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by guilhermecostalopes** [comment]
Enviado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
