### ISSUE TITLE
[Curitiba/Remote] Senior FullStack Developer na Visionnaire

### ISSUE THREAD

**Issue by raulbalestra** [frontendbr/vagas#3132]
Business
A platform that identifies the content quality on customer's side and build blueprints that help to write cover topics comprehensively.

Requirements
the customer is looking for a Senior React/Node.js engineer preferably with **GraphQL** experience. __**Experience working with Python would be a plus.**__  

**Upper-Intermediate English is mandatory**

Timeframe & Budget
Start: asap

Duration: 2-3 months, could become ongoing.
This is a full-time occupation, **no part-time engineers required.**

Budget: around R$70/hour

Como se candidates:
Por favor envie um email para raul.balestra@visionnaire.com.br com seu CV anexado - enviar no assunto: Senior FullStack Developer female

Alocação:
**Alocado
Remoto**
Regime:
**CLT
PJ**
Nível:
**Sênior**

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
