### ISSUE TITLE
[São Paulo] Front-end Developer na Organize Cloud Labs

### ISSUE THREAD

**Issue by organizecloudlabs** [frontendbr/vagas#3133]
## Organize Cloud Labs

A Organize Cloud Labs é uma empresa brasileira, fundada em 2014, a primeira e única parceira Elite da ServiceNow na América Latina, com um extenso portfólio de serviços e soluções, especializada em automação de processos e desenvolvimento de aplicações.

Na América Latina, somos a maior, mais experiente e mais certificada equipe para ajudar a extrair o máximo da tecnologia ServiceNOW, com experiência em implementar fim-à-fim as mais diversas soluções desta fabricante, em projetos de relevância nacional e mundial.

Com sede no Brasil e Estados Unidos, nosso maior objetivo é a excelência em tudo o que fazemos. 

## Descrição da vaga

Vaga para atuar como Consultor Técnico ServiceNow (Analista de Desenvolvimento). 
Precisamos de alguém com domínio sobre linguagens Front-end para trabalhar na equipe de Portal e dar suporte também para a equipe. A função envolve estar também em contato com o cliente, uma vez que a Organize Cloud Labs é uma consultoria. 

## Local

São Paulo - Próximo ao Shop. Morumbi
Maior atuação é home-office, mas precisará ir ao escritório de vez em quando. 
* Só aceitaremos currículos de São Paulo!!!

## Requisitos

**Obrigatórios:**
- 3 anos de experiência atuando com JavaScript, HTML, CSS e frameworks;
- Inglês intermediário/ avançado. 

## Benefícios

- Plano de saúde
- Plano Odontológico
- Seguro de vida
- Vale Alimentação
- Auxílio Link de Internet
- Auxílio de Inglês
- Acesso a treinamentos oficiais ServiceNow
- PLR e mais...

**Diferenciais:**
- Home-office
- Escritório com ambiente agradável
- Time nota 10! 

## Contratação

CLT

## Como se candidatar

Para se candidatar, é necessário cadastrar o currículo em nosso site através do link: https://organizeprod.service-now.com/organize?id=organize_careers
*Só serão aceitos currículos de São Paulo!!! 

Se antes de se candidatar, você quiser mais sobre mais sobre ServiceNow e sobre a nossa empresa, deixo uns links abaixo que podem te auxiliar!

ServiceNow
Cursos e Instância free: http://developer.servicenow.com/
Vídeos: https://www.youtube.com/channel/UCQjE37R-Y4DTq7kUWPO83Wg

Organize Cloud Labs
Site: https://organizeprod.service-now.com/organize?id=organize_landing
Instagram: @organizecloudlabs
LinkedIn: https://www.linkedin.com/company/organizecloudlabs/

## Tempo médio de feedbacks

Sempre damos um retorno para quem começa os processos conosco. Fiquem tranquilos! 
Após cadastro no nosso site, o seu currículo será analisado por nossa equipe. Passando por essa primeira triagem, entraremos em contato para um bate papo rápido antes de começar o processo seletivo. 

#### Alocação
- Remoto
- Escritório

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by arthur-mts** [comment]
Possibilidade pra remoto?

**Comment by organizecloudlabs** [comment]
> Possibilidade pra remoto?

É remoto, mas apenas em São Paulo, Arthur. :(

**Comment by eduardocappellotto** [comment]
Não entendi o "Só aceitaremos currículos de São Paulo!!!" 
Se o profissional tiver disponibilidade de mudança ( como eu tenho! ), não rola?

**Comment by organizecloudlabs** [comment]
> Não entendi o "Só aceitaremos currículos de São Paulo!!!"
> Se o profissional tiver disponibilidade de mudança ( como eu tenho! ), não rola?

Olá, Eduardo! Tudo bem?
Neste caso, informe no currículo que você tem possibilidade de mudança para São Paulo, por favor.

**Comment by arthur-mts** [comment]
> > Possibilidade pra remoto?
> 
> É remoto, mas apenas em São Paulo, Arthur. :(

Beleza, obrigado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
