### ISSUE TITLE
[São Paulo] Front-end Developer na Aeroscan

### ISSUE THREAD

**Issue by Marcello09** [frontendbr/vagas#3134]
## Aeroscan

A Aeroscan é uma startup de tecnologia especializada em aeronaves remotamente pilotadas (drones). A 2 anos a empresa iniciou o processo de expansão para o mercado de segurança e está desenvolvendo uma plataforma de operação de aeronaves automatizada para este mercado.

## Descrição da vaga

Vaga de desenvolvedor(a) front-end para ampliação do projeto Aerobase. Um projeto desenvolvido em Angular 6 com interface responsiva com o framework Bootstrap que permite a operação automatizada das aeronaves.

## Local

Escritório localizado em Alphaville Industrial, Barueri.

## Requisitos

**Obrigatórios:**
- Angular 2 ou superior
- Lingua inglesa

**Desejáveis**
- Conhecimento em NodeJS
- Interesse em se tornar Fullstack
- Java para desenvolvimento Android

**Diferenciais**
- Conhecimento de veículos autônomos
- Conhecimento de sistemas em tempo real

## Benefícios

- Auxílio transporte
- Auxílio alimentação

**Diferenciais**
- Horario flexível
- Cachorro no escritório
- Chance de participação da empresa (stock option)

## Contratação

PJ a combinar

## Como se candidatar

Envie um email para m.moreira@aeroscan.com.br com o assunto: Vaga Front-end [NOME]

## Tempo médio de respostas

Após o primeiro contato, damos a resposta em até 2 dias úteis. Caso não receba uma resposta dentro do prazo, por favor entrar em contato no número (31) 99631-1979 ou pelo whatsapp do mesmo numero.

#### Alocação
- Alocado

#### Regime
- Estágio
- PJ

#### Nível
- Júnior
- Pleno

**Comment by JIFerreira** [comment]
Qual o nível do ingles?

**Comment by Marcello09** [comment]
Intermediario / Avançado (Conseguir ler e escrever emails, ler e compreender documentação de apis completamente em ingles)

**Comment by guilhermecostalopes** [comment]
Enviado

**Comment by Marcello09** [comment]
#### Informo que o envio de currículos está temporariamente pausado até analise dos candidatos atuais. 
Grato
