### ISSUE TITLE
[Curitiba/Remote] Senior FullStack Developer na Visionnaire

### ISSUE THREAD

**Issue by raulbalestra** [frontendbr/vagas#3139]
Requirements:
 - 4+ years experience in building API focused backend systems
- 3+ years of experience using Vue.js or React
- Experience building backend systems to scale and for fault tolerance
- Experience in building service-oriented architecture or microservices
- Highly skilled in backend technologies such as Python/Ruby/Go/Node.js
- Familiarity with Postgres or a similar SQL database
- Experience with Heroku/AWS or similar Cloud provider integrations
- Ability to cover at least 4 overlapping hours within PST

Responsibilities:
- Ownership of backend subsystems supporting main products
- Manage and enhance processes for deployment/maintenance of new features in production systems
- Manage and maintain active health metrics/alarming for critical backend components
- Evolve existing service APIs to be more scalable/fault-tolerant/performant using the best tool for the job

Como se candidates:
Por favor envie um email para raul.balestra@visionnaire.com.br com seu CV anexado - enviar no assunto: Senior FullStack Developer 

Alocação:
Alocado
Remoto
Regime:
CLT
PJ
Nível:
Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
