### ISSUE TITLE
[São Paulo] Senior Front-end Developer na Red Ventures

### ISSUE THREAD

**Issue by pstvalle** [frontendbr/vagas#3140]
## Nossa empresa

Fundada em Charlotte (USA) em 2000, a Red Ventures é uma empresa de tecnologia e marketing digital voltada à otimização de todo o processo de aquisição de clientes. Com uma base tecnológica e analítica muito forte, assumimos todo o processo de marketing e otimização do funil digital de uma operação - desde a captação até à efetivação da transação. Além de líder global nesse tipo de parceria, a empresa conta com uma série de ativos próprios e nosso portfolio de companhias conta com empresas como The Points Guy, uSwitch, BankRate, iq, Capital Research, dentre outras.

A equipe de front-end, juntamente a equipe de engenharia, é responsável pelo desenvolvimento e manutenção de aplicações robustas e de alto desempenho. Essa posição tem alta visibilidade e potencial de impactar a organização, participando diretamente da maneira como construímos e entregamos as soluções para nossos parceiros.

Nossa cultura é baseada na liberdade, você estará livre para executar, testar e aprender além disso terá a responsabilidade de se auto gerenciar de maneira colaborativa e ágil. Você terá a oportunidade de se desafiar e crescer. Você pode pensar no melhor dos dois mundos: trabalhar em um ambiente dinâmico de um start-up no Brasil e, ao mesmo tempo, ser apoiado por uma empresa líder global de tecnologia em um ambiente de carreira disruptivo, empreendedor e acelerado.

## Descrição da vaga

Esperamos que você desenvolva aplicações do zero e novas funcionalidades para as existentes, mantenha um processo de Git organizado e normalizado entre diferentes projetos, otimize o desempenho em aplicações (novas e existentes) e identifique e proponha soluções para problemas repetitivos.
Você trabalhará com designers, analistas, engenheiros e outros desenvolvedores em um ambiente em que poderá ver o impacto de suas ideias.
Terá a responsabilidade de liderar projetos participando ativamente em decisões relacionadas à tecnologia, prevendo os próximos passos em conjunto com o time de negócios e se desenvolver em disciplinas complementares e importantes para o desenvolvimento da liderança, como gestão de pessoas e conflitos e terá a oportunidade de contribuir para o desenvolvimento do time através da mentoria. A Red Ventures lhe dará a oportunidade de inovar e tomar decisões significativas à medida que você continua desenvolvendo suas habilidades.

## Local

Escritório em São Paulo - Vila Olímpia

## Requisitos

- Comprometimento com aprendizado e melhoria contínuas, sempre buscando novos conhecimentos e validando idéias.
- Sólidos conhecimentos em Javascript e Css.
- Familiaridade e interesse da áreas complementares como Design e Back-end, necessários para uma boa visão do desenvolvimento de um produto.
- Conhecimento em arquiteturas e técnicas de Desenvolvimento de Software como S.O.L.I.D, Design Patterns, Functional Patterns, entre outros.
- Ter familiariadade e interesse em outras linguagens de programação.
- Como você trabalhará com designers e desenvolvedores(as) de todo o mundo, você deverá se sentir à vontade para se comunicar em inglês, seja verbal ou por texto.
- Gostar de encontrar desafios em qualquer contexto seja em projetos novos como em projetos legados, visando melhorias e aperfeiçoamento constantes.
- Ter familiaridade com Metodologias Ágeis e Frameworks mas ser agnóstico o suficiente para não se prender à nenhuma delas afim de exercitar o pensamento autêntico utilizando os conhecimentos para formar uma solução mais adaptada.

- Contribuições para projetos internos que facilitem, automatizem e melhorem os processos das diferentes equipes.
- Preocupação com a carreira de outros desenvolvedores realizando 1 on 1's periódicos e participando de feedbacks constantes.
- Ajudar na contribuição para uma cultura saudável e construtiva.
- Se desenvolver constantemente e desempenhar papéis como : Gestão de Pessoas, Resolução de conflitos e Desenvolvimento do time, entendendo a importância dessas matérias na carreira e para o relacionamento interpessoal.
- Estimar entregáveis e se relacionar com os demais times quando necessário para fornecer cronogramas confiáveis para entrega.
- Ajudar e mentorar pessoas da sua equipe de forma consistente no intuito de contribuir para o desenvolvimento de outras pessoas do time.
- Participar de discussões não técnicas sempre desafiando o "status quo" e procurando sempre melhorar nos processos, nas tecnologias, na maneira como trabalhamos.
- Participar ativamente no dia a dia no desenvolvimento dos produtos programando e sendo responsável pelo desenvolvimento técnico de outros desenvolvedores com metodologias de aperfeiçoamento contínuo como: Code Reviews, Pair Programmings, Refactories etc.
- Terá a liberdade para se desenvolver e compartilhar suas ideias internamente e/ou externamente através de palestras, workshops e artigos.

## Benefícios

- Plano de carreira estruturado.
- Ambiente de trabalho informal que valoriza a colaboração e o respeito por pessoas de diversas origens e culturas.
- Incentivo à educação: bolsa anual para você usar para aprimorar de habilidades através da educação.
- Exposição direta à equipe de engenharia global da Red Ventures em outros países.
- Gympass.
- Red Adventure - organizamos passeios com o time (já fomos ao Kart, Tiro com Arco, Escape 60)
- Liberdade para ajudar a melhorar a cultura de desenvolvimento todos os dias.
- Plano de saúde superior à média do mercado.
- Plano odontológico.
- Vale Uber.
- Café da manhã e massagem no escritório.
- Bônus financeiro anual de acordo com o desempenho.

## Contratação

CLT 

## Como se candidatar

Por gentileza se candidatar através do link: https://careers.redventures.com/application/position/2165821?gh_jid=2165821

## Tempo médio de feedbacks

E-mail para contato em caso de não haver resposta: pvalle@redventures.com

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
