### ISSUE TITLE
[Belo Horizonte] Front-end React no Clipping

### ISSUE THREAD

**Issue by eluizbr** [frontendbr/vagas#3146]
## Descrição da vaga

Procuramos por um Front-End React que seja apaixonado por JavaScript, tecnologias móveis e, claro, tenha vontade de fazer parte de algo grandioso.

## Local

Alocado / Remoto, Belo Horizonte - MG

## Requisitos

**Obrigatórios:**
- Tenha experiência com Frontend (HTML / CSS );
- Tenha experiência com React;
- Goste de soluções online para Educação;
- Goste de fazer parte de um time que cria produtos que revolucionam e quebram paradigmas;
- competente e está sempre estudando, aprendendo e se aperfeiçoando.

## Benefícios

- Plano de saúde e odontológico Bradesco (sem desconto mensal, apenas a coparticipação de 10% no caso de consultas ou exames);
- Vale Refeição ou alimentação de R$20/dia;
- Nenhum dos benefícios é descontado no salário, somente impostos do governo;
- Investimos no nosso time e arcamos com sua capacitação;

## Contratação

CLT

## Como se candidatar

Por favor envie um email para emerson@clippingcacd.com.br com seu CV anexado - enviar no assunto: Vaga Front React

## Nossa Empresa

O Clipping CACD é a mais completa plataforma para a preparação para o concurso da diplomacia.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

#### Local
- Belo Horizonte

**Comment by THAYLLER** [comment]
esa vaga tambem pode ser remoto ou so no periodo de pandemia?

**Comment by eluizbr** [comment]
Olá @THAYLLER, Pode ser remoto...

**Comment by THAYLLER** [comment]
legal vlw
