### ISSUE TITLE
[São Paulo] Front-end Developer na we.digi

### ISSUE THREAD

**Issue by deniswedigi** [frontendbr/vagas#3147]
## Nossa empresa

A we.digi é uma consultoria digital e de performance com mais de 20 anos de mercado, localizada na capital de São Paulo, nas proximidades da estação Belém do metrô.
Para saber mais acesse wedigi.com.br.

## Descrição da vaga

Tudo joia, pessoal?

Estamos procurando profissionais Front-end Developer para trabalhar no desenvolvimento de e-commerces e sites nas plataformas Vtex e wordpress.

O modelo de contratação é PJ
A remuneração é a combinar
Pra que gosta, cervejinha artesanal e marcas convencionais na geladeira, mas com moderação hein?

## Local

SP, São Paulo, Belém

## Requisitos

**Obrigatórios:**
Conhecimento JavaScript, HTML e CSS
Consumo de APIs - Ajax
Boas práticas: reutilização de código
Cross Browser e responsividade

## Contratação

PJ a combinar

## Como se candidatar

Entre em contato conosco e envie seu currículo através do e-mail: vagas@wedigi.com.br
Também pedimos para informar a pretensão de remuneração no e-mail, ok?

### Alocação
Alocado

#### Regime
- PJ

#### Nível
- Júnior

**Comment by deniswedigi** [comment]
Boa tarde!
Acabei criando a vaga errada, corrigi neste instante. Seria possível remover o label "Remoto" ?
Obrigado!

**Comment by fogeid** [comment]
Como eu gostaria de morar em SP para pegar essas vagas...

**Comment by thiago-hs** [comment]
E-email enviado!

**Comment by arthur-mts** [comment]
Email enviado!

**Comment by barcellos-pedro** [comment]
E-mail enviado!

**Comment by rdgSantos-js** [comment]
E-mail enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
