### ISSUE TITLE
[São Paulo] Front-end Developer na Galileu

### ISSUE THREAD

**Issue by Izah-Silva** [frontendbr/vagas#3148]
## Nossa empresa

A Galileu é uma empresa que presta serviços de gestão de logística. Disponibilizam uma completa solução para a gestão da movimentação, transportes e entregas dos produtos para outras empresas ou para seus clientes.

## Descrição da vaga

Hoje trabalhamos com grandes clientes como Nestle, Heineken, Latam, Accenture, Arcelor, entre outros.

Nossa equipe está crescendo e estamos em busca de um desenvolvedor (a) Front End Pleno/Sênior para compor nosso time de tecnologia. Se você curte desafios, é uma pessoa dinâmica, comprometida com seu trabalho, gosta de pensar fora da caixa e busca agregar valor em uma organização, então vem pra Galileu!

## Local

[Moema] [São Paulo] 

## Requisitos

**Obrigatórios:**
- HTML;
- CSS;
- Typescript;
- Angular 6+;
- REST Services.

**Diferenciais:**
- Experiência com Vanilla JS;
- Experiência com programação orientada a objetos em Vanilla JS e TypeScript;
- Experiência com Graphql;
- Experiência com microsserviços.

## Contratação

PJ a combinar

## Como se candidatar

Interessado nessa oportunidade? Cadastre-se em nossa plafaroma: https://app.vulpi.com.br/galileu/1627 ou mande e-mail com sua candidatura para izabella.silva@vulpi.com.br com o assunto: Vaga Front-end Galileu.

#### Alocação
- Alocado

#### Regime
- CLT
- PJ

- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
