### ISSUE TITLE
[Santa Barbara D'Oeste - Remoto] Front-End Developer na 2SOW

### ISSUE THREAD

**Issue by yuritoledo** [frontendbr/vagas#3151]
## Descrição da vaga
- Criação e manutenção de apps web e mobile;
- Integração do frontend com APIs e microsserviços internos;
- Escrever testes para garantir as funcionalidades já existes, em conjunto com as novas;
- Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas;
- Construir componentes reutilizáveis - internamente e entre sistemas;
- Participar do processo criativo e auxiliar na construção/elaboração dos sistemas;
- Ajudar a enriquecer a cultura na empresa :)

## Local

Remoto ou Escritório, Santa Barbara D'Oeste/SP

## Requisitos

**Obrigatórios:**
- Experiência relevante em front-end
- Experiência com React
  - Hooks
  - ContextAPI
  - Redux
  - Router
  - testing-library
- Experiência com Angular (Ionic)
- Bons conhecimento em JavaScript puro e CSS
- Clean code

**Desejáveis:**
- Conhecimento em Typescript
- Conhecimento em SemanticUI
- Conhecimento em styled-components
- Conhecimento em TDD ou testes automatizados
- Conhecimento em GraphQL

## Benefícios

- Vale Alimentação
- Reembolso de viagens caso seja remoto e venha para a empresa esporadicamente.
- No caso de home office, ou caso o profissional deseje trabalhar com seu próprio equipamento, há um reembolso mensal pelo uso.

**Diferenciais:**
- Área de descanso
- Café expresso ou coado
- Cachorro no ambiente de trabalho

## Contratação

CLT presencial ou remoto

## Como se candidatar

Por favor envie um email para yuri@cacdigital.com.br com seu CV anexado - enviar no assunto: Vaga Front-End e com a pretensão salarial, se possível :)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 30 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by evertonProgramadorCriativo** [comment]
Eu gostaria de uma oportunidade de fazer teste para vaga junior , meu email e
evertonprogramadorcriativo@gmail.com
