### ISSUE TITLE
[São Paulo] Front-end Developer Pleno na EasyCarros

### ISSUE THREAD

**Issue by easycarros-tech** [frontendbr/vagas#3154]
## Nossa empresa

A Easy Carros é uma empresa que nasceu em 2014, focada no mercado de mobilidade.
Identificamos que hoje, 40% do valor de tudo o que compramos no nosso dia a dia (o pão do café da manhã, o chocolate de sobremesa, a cervejinha do final do dia) é referente ao custo de logística, que é extremamente caro no Brasil.
E o que queremos é criar cada vez mais serviços e tecnologias que possam entregar economia de custos para o setor de logística das principais empresas, para que, assim, os produtos cheguem a um preço muito mais justo e em conta para nós, os consumidores. 
Queremos, então, impactar a vida de milhões de brasileiros através dos nossos produtos. Nosso sonho é grande e nossa empresa tem sangue no olho para alcançar esse resultado.  Quer transformar o mundo? Se sim, aqui é o seu lugar.

## Descrição da vaga

**Na EasyCarros você vai:**

- Trabalhar com um time super competente que sempre busca utilizar com as melhores ferramentas e melhores práticas.
- Fazer parte de um projeto de alto impacto que pode afetar a vida de milhões de pessoas.
- Ter autonomia para sugerir melhorias e impactar decisões sem reuniões intermináveis e ladainha.
- Trabalhar num ambiente informal e descontraído.
- Aprender muito!

**Responsabilidades do desenvolvedor na EasyCarros:**

- Desenvolver interfaces para plataformas orientadas a (micro-)serviços para solucionar problemas específicos (ex: multas e documentação, serviços automotivos, compra e venda de veículos);
- Criar código de fácil compreensão e bem documentado.
- Criar soluções escaláveis e sustentáveis voltadas para o usuário.
- Ferramentas diversas de versionamento, deploy, monitoramento. Você não precisa conhecer todas mas precisa estar disposto a aprender.
- Auxiliar na organização da arquitetura dos produtos de frontend e experiência de usuário.

## Local

Escritório, São Paulo, Capital, Centro

## Requisitos

**Obrigatórios:**
- HTML
- CSS3
- BootStrap
- JavaScript
- React

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para people@easycarros.com com seu CV anexado - enviar no assunto: Vaga FrontEnd Pl - São Paulo

## Tempo médio de feedbacks

Enviamos sempre feedbacks após cada etapa do processo. Caso tenha alguma dúvida, ou não tenha recebido um retorno, pode mandar e-mail para people@easycarros.com

## Labels
- pleno
- pj
- react

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
