### ISSUE TITLE
[Curitiba] Front-end Developer Sr. na EuroIT

### ISSUE THREAD

**Issue by easycarros-tech** [frontendbr/vagas#3155]
## Nossa empresa

A EuroIT tem crescido cada vez mais e por isso estamos abrindo uma vaga de Desenvolvedor Front End Sr!

Nessa vaga você terá a oportunidade de construir uma nova versão de um produto para o mercado de mobilidade, onde tudo será novo e pronto para ser desenvolvido.

Como toda vaga, temos alguns requisitos, dá uma conferida aqui embaixo.

## Descrição da vaga

- Desenvolver interfaces para plataformas orientadas a (micro-)serviços para solucionar problemas específicos (ex: locação de veículos, reservas, contratos, estrutura financeira e operacional, etc.);
- Criar código de fácil compreensão e bem documentado;
- Auxiliar na organização da arquitetura dos produtos de frontend e experiência de usuário;
- Ferramentas diversas de versionamento, deploy, monitoramento;
- Saber trabalhar com layout responsivo;

## Local

Escritório, Paraná, Curitiba, Centro

## Requisitos

**Obrigatórios:**
- Ampla experiência em HTML5;
 - CSS3 (BEM; Layouts - floats, positioning, display, box model, grid, flex box; Media queries);
- JavaScript (ES6+);
- JQuery;
- TypeScript;
- Bootstrap;

**Desejáveis:**
- React;
- Cross-browser e frameworks front-end;

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para people@dre.com.br com seu CV anexado - enviar no assunto: Vaga Frontend Senior - Curitiba

## Tempo médio de feedbacks
Enviamos sempre feedbacks após cada etapa do processo. Caso tenha alguma dúvida, ou não tenha recebido um retorno, pode mandar e-mail para people@dre.com.br

## Labels
- pj
- alocado
- senior
- curitiba

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
