### ISSUE TITLE
[Remoto] Desenvolvedor Full-Stack na GrowthTech

### ISSUE THREAD

**Issue by kennethgt** [frontendbr/vagas#3156]
## Nossa empresa

A Growth Tech é uma startup fundada há 4 anos e que trabalha desenvolvendo projetos inovadores de tecnologia da informação. Dentre as suas principais áreas de atuação estão: Soluções em Blockchain para negócios, aplicativos e softwares customizados sob demanda.

## Local

100% Remoto

## Requisitos

**Obrigatórios:**

- Node.js
- Express.js
- React.js

**Desejáveis:**

- Blockchain

## Contratação

- PJ (R\$ 6.000,00)

## Desafio

Uma empresa deseja realizar um monitoramento de outros grupos empresariais em um site X para analisar seus posts. Sua tarefa é criar uma simples API que captura apenas os usuários (http://jsonplaceholder.typicode.com/users) os quais a empresa em que trabalham fazem parte de um grupo e exiba seus posts (http://jsonplaceholder.typicode.com/posts) unido do nome do funcionário e sua empresa. Além disso criar uma tela para facilitar a leitura desses posts.

- O backend obrigatoriamente precisa ser realizado com Express.js.
- O frontend obrigatoriamente precisa ser realizado com React.js.
- Apesar de bem simples, o projeto precisa estar pronto para produção.
- Sinta-se à vontade para adicionar mais features e criar uma UI maneira!

## Como se canditatar

Assim que finalizado preencher o [formulário](https://forms.gle/ajYAbSVtrAJGUsLXA) e aguardar, boa sorte!

**Comment by Luiz-junior** [comment]
Boa noite! Podem enviar algum e-mail aqui para eu tirar um dúvida por favor?

**Comment by kennethgt** [comment]
Dúvidas pelo email kenneth@growthtech.com.br
