### ISSUE TITLE
[Remoto ou em São Paulo] Front-end Developer na RiskNow

### ISSUE THREAD

**Issue by vmesel** [frontendbr/vagas#3157]
## Nossa empresa

A RiskNow é uma fintech focada no mercado de crédito imobiliário com diversas ferramentas para assessorar a Avaliação de Risco de Crédito Imobiliário.

## Descrição da vaga

Buscamos uma pessoa desenvolvedora com experiência em Vue (preferencialmente), ou ReactJS e experiência com Nodejs.

Se você adora desafios, é motivado e quer fazer a diferença numa empresa em crescimento, venha conversar com a gente.

Trabalho remoto ou não - você escolhe.

Aqui você vai ter um papel importante trabalhando com os times de back e front,

Somos uma fintech que torna o crédito imobiliário mais simples, justo e transparente para pessoas e empresas.

## Local

Remoto ou Escritório, São Paulo - Largo da Batata

## Requisitos

**Obrigatórios:**
- Experiência com Vue (preferencialmente), ou Reactjs.
- Experiência com Nodejs é um plus.
- Capacidade de trabalhar em grupo;
- Importante ser proativo e organizado;

**Diferenciais:**
- projetos opensource

## Contratação

A combinar

## Como se candidatar

Por favor preencha o [formulário](https://docs.google.com/forms/d/e/1FAIpQLSdN4IC3RGeq0wu8MfiL6S3PjXhzDTAA7dO4bf66Q-uCWCl1Aw/viewform?usp=sf_link)

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by nandomoreirame** [comment]
Enviado.
