### ISSUE TITLE
[Remoto ou Belo Horizonte] Senior Front-end Developer na Queima Diária 

### ISSUE THREAD

**Issue by JohnCosta56** [frontendbr/vagas#3158]
## Nossa empresa

Visamos ajudar as pessoas a se tornarem aquilo que desejam ser através de uma vida mais saudável, harmoniosa e cheia de autoestima. Para isto acontecer, temos a maior e mais inovadora plataforma online do Brasil dedicada à atividade física e ao bem-estar.

## Descrição da vaga

Projetos de inovação e sustentação utilizando React.js

## Local

Remoto ou escritório. Buritis - Belo Horizonte/MG

## Requisitos

**Obrigatórios:**
- Experiência em React.js
- Ter perfil Sênior

**Diferenciais:**
- Experiência no desenvolvimento de aplicativos Mobile;
- Experiência no desenvolvimento de aplicativos para Smart TV's;

## Contratação

A combinar

## Como se candidatar

[Você pode se candidatar clicando aqui.](http://queimadiaria.recruiterbox.com/jobs/fk015mn?apply=true)

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Sênior
- Especialista

**Comment by nandomoreirame** [comment]
Enviado.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
