### ISSUE TITLE
[Remoto] Web/Mobile Developer na TZ3 Tecnologia

### ISSUE THREAD

**Issue by dgilbertoni** [frontendbr/vagas#3160]
## Nossa empresa

Estamos há 11 anos no mercado e neste período já desenvolvemos centenas de projetos para empresas de todos os portes e segmentos de mercado. Somos especialistas em desenvolvimento de sistemas web, apps, e-commerce e robôs de automação de processos. 

[https://tz3.com.br](https://tz3.com.br)

## Descrição da vaga

Buscamos developers para atuação em projetos Web e Mobile. 

## Local

Remoto (Home Office)

## Requisitos

**Obrigatórios:**
- Experiência em uma ou mais das seguintes tecnologias: PHP, React, React Native, Node.js
- Experiência em HTML5, CSS3 e Javascript

**Desejáveis:**
- Conhecimentos de PHP Frameworks (preferencialmente Code Igniter)
- Conhecimentos de MySQL, PostgreSQL e MongoDB
- Conhecimentos de APIs RESTFUL
- Conhecimentos de AWS
- Conhecimentos de GIT e CI/CD
- Conhecimentos de Bootstrap / JQuery
- Inglês Avançado

## Benefícios

- Horário Flexível
- Ambiente Informal

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para rh@tz3.com.br com seu CV, pretensão de remuneração e disponibilidade de início. 

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by Luan-max** [comment]
Enviado!

**Comment by rdgSantos-js** [comment]
Email Enviado!

**Comment by evertonProgramadorCriativo** [comment]
Eu gostaria de uma oportunidade de fazer teste para vaga junior , meu email e
evertonprogramadorcriativo@gmail.com

**Comment by tuliosj** [comment]
Enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
