### ISSUE TITLE
Belo Horizonte - Remoto] Front End developer em FLUTTER na Stars Poker Club

### ISSUE THREAD

**Issue by MoacirSchmidt** [frontendbr/vagas#3161]
# STARS POKER CLUB, o maior clube de poker online do Brasil!
Procura desenvolvedor Front End com sólidos conhecimentos em FLUTTER para seu novo empreendimento.

Venha fazer parte de mais um projeto de sucesso conosco!

# Oferecemos
- Trabalho remoto
- Equipe moderna e motivada
- Horário flexivel (deve cumprir 8hs diárias em média)

# Exigimos
- Solidos conhecimentos em FLUTTER
- Experiencia com práticas modernas de desenvolvimento (git, scrum, rest)
- Diferencial: Conhecimento em desenvolvimento WEB com Flutter!

# Detalhes
- Projeto com expectativa de duraçao de 4 meses e possibilidade real de efetivação.
- Precisa ter disponibilidade full-time (8hs diárias, em média)
- Regime PJ com remuneração a combinar
- Interessados enviem curriculo com pretensão salárial para moacir.schmidt@gmail.com

**Comment by odaviribeiro** [comment]
Vocês querem dizer é desenvolvimento Mobile com Flutter correto? Flutter Web nem tem versão stable ainda .-.

**Comment by MoacirSchmidt** [comment]
Não. Nós queremos dizer Flutter Web Mesmo. Leia o anúncio com atenção e você entenderá que  Flutter Web é apenas um diferencial.

**Comment by MoacirSchmidt** [comment]
Não. Nós queremos dizer Flutter Web mesmo. Observe que é mencionado como um diferencial.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
