### ISSUE TITLE
[Remoto] Front-end na Evolux Sistemas

### ISSUE THREAD

**Issue by Mazuh** [frontendbr/vagas#3162]
## Nossa empresa

Na Evolux, criamos uma suite completa para Call Centers com operações críticas e experiência de cliente. Também temos projetos de Pesquisa e Desenvolvimento, para soluções inovadoras ao mercado. E ainda há o Outsourcing de desenvolvimento para integrarmos equipes estrangeiras em suas soluções de software.

A Evolux é certificada pelo [terceiro ano consecutivo como Great Place to Work](https://www.linkedin.com/posts/evoluxbr_deu-bom-evolux-%C3%A9-certificada-gptw-pelo-terceiro-activity-6669315160668151808-6b3L), obtendo a [posição 14 no ranking nacional e 1 no estadual](http://www.tribunadonorte.com.br/noticia/empresas-recebem-certificado-great-place-to-work/454297).

## Descrição da vaga

No momento estamos com vagas abertas para o time de Outsourcing usando React no frontend e, caso a pessoa se sinta confortável, Python com Django no server side.

## Local

Totalmente remoto, embora nossa sede seja em [Natal (RN)](https://pt.wikipedia.org/wiki/Natal_(Rio_Grande_do_Norte)).

## Requisitos

**Obrigatórios:**
- HTML e CSS;
- JavaScript (ECMAScript);
- Git (e seu git flow);
- Ecossistema React e Redux;
- Familiaridade com testes; 
- Leitura e escrita em inglês; 
- Boa comunicação técnica com sua equipe em português.

**Desejáveis:**
- Fluência geral em inglês;
- Noções básicas de usabilidade;
- Metodologia Ágil.

**Diferenciais:**
- Participação em projetos free source;
- Experiência com trabalho remoto;
- Alguma familiaridade com Python.

## Benefícios

- Plano de saúde;
- Vales alimentação/refeição;
- Vale cultura;
- Auxílio de trabalho remoto;
- Acesso (opcional) ao escritório no fim da quarentena (com vacinação grátis, video game, geladeira livre, barril de cerveja, cafeteira, snacks, etc);

## Contratação

CLT.

## Como se candidatar

Candidate-se através do link: [https://evolux.freshteam.com/jobs/xUP4WPQAi3jp/desenvolvedor-a-frontend-pleno-ou-senior](https://evolux.freshteam.com/jobs/xUP4WPQAi3jp/desenvolvedor-a-frontend-pleno-ou-senior)

## Tempo médio de feedbacks

Valorizamos a entrega de feedback mesmo em caso de negativa. Todos os currículos receberão respostas até dia 15 de junho. Os que fizerem entrevista terão um feedback mais detalhado em até dois dias úteis após sua entrevista.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by Mazuh** [comment]
Já fizemos uma contratação, e já estamos fazendo outra na sexta-feira. Já posso fechar já.
