### ISSUE TITLE
[Remoto ou Florianópolis] Front-end Developer na Jungsoft

### ISSUE THREAD

**Issue by pedro-lb** [frontendbr/vagas#3164]
## Nossa empresa

A Jungsoft é uma startup internacional sediada em Florianópolis - SC, com negócios na Alemanha e Estados Unidos. Trabalhamos sempre com tecnologias de ponta, como Elixir, GraphQL, React e React Native.

Possuímos diversos projetos, desde blockchain até big data - ou seja, você vai amar se gostar de desafios e de aprender coisas novas!

**Suas responsabilidades aqui serão:**
- Desenvolver interfaces que trazem uma experiência única e eficiente aos usuários;
- Utilizar linguagens como JavaScript e TypeScript para completar suas tarefas;
- Realizar a comunicação com APIs GraphQL;
- Contribuir com os padrões e melhores práticas;
- Fortalecer o ecossistema React local e internacional;

## Descrição da vaga

Nosso time está crescendo e queremos pessoas talentosas e apaixonadas por tecnologia trabalhando juntinho com a gente!

Gosta de se desafiar e o desenvolvimento profissional é prioridade na sua carreira?

Está procurando aquele ambiente de trabalho com pessoas incríveis?

Gosta de autonomia e liberdade na hora de trabalhar?

Quer um ambiente de trabalho onde você está o tempo todo aprendendo?

Já sonhou em iniciar uma carreira a nível internacional?

Então seu lugar é aqui com a gente!

## Local

Remoto ou escritório, sediado em Florianópolis / SC, no bairro Trindade, próximo à UFSC.

## Requisitos

**Requisitos Técnicos Necessários:**
- Domínio de React, incluindo React Hooks;
- Domínio de GraphQL;
- Fluência com Git;
- Facilidade com o formato de trabalho remoto;
- Ter experiência com planejamento e levantamento de requisitos;
- Boa gestão de tempo e organização pessoal;
- Inglês Intermediário;

**Você se destaca se possui:**
- Domínio de React Native;
- Conhecimento em testes de código;
- Conhecimento de metodologias ágeis;
- Experiência em projetos open-source;

**O perfil que procuramos tem:**
- Facilidade de comunicação;
- Capacidade Criativa;
- Prezar pela inovação nos projetos;
- Paixão pela programação;
- Gostar de trabalhar em formato mais independente;
- Capacidades autodidatas;
- Amar desafios;
- Estar sempre em busca de novas aprendizagens;

## Benefícios

- Contrato PJ, com benefícios a combinar
- Horários completamente flexíveis

**Diferenciais para trabalho presencial:**

- Café da manhã todos os dias
- Happy hours de vez em sempre
- Máquina de café top (moído) free 
- Açaí na empresa

## Contratação

PJ a combinar

## Como se candidatar

Preencha nosso formulário: https://bit.ly/3gtLFIC

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após cada processo.

E-mail para contato em caso de não haver resposta: vagas@jungsoft.io

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by allanreges** [comment]
A vaga é de Frontend ou Fullstack? vocês pedem os requisitos no começo e depois pedem experiência obrigatória com node no final.

**Comment by pedro-lb** [comment]
Oi, @allanreges ! 

Atualizei a descrição da vaga ali, a parte de node estava no template. É apenas Frontend =)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by pedro-lb** [comment]
Vaga fechada. =)
