### ISSUE TITLE
[Cruzeiro-SP/Remoto] Front-end Developer na Object1ve

### ISSUE THREAD

**Issue by eric-dev-object1ve** [frontendbr/vagas#3167]
## Nossa empresa

Nosso site: https://object1ve.com/
A Objective foi fundada em 2008 com uma forte crença no trabalho árduo aliando inteligência e tecnologia; 
Nosso principal objetivo é sempre o sucesso e a satisfação do cliente.
Estamos localizados em Cruzeiro, São Paulo, Brasil no histórico Vale do Paraíba.

## Descrição da vaga

Vaga para desenvolvedor(PL/SR) ReactJS remoto na empresa Object1ve
Precisa-se de desenvolvedor com conhecimento Pleno ou Senior. 

## Local

Remoto ou escritório Cruzeiro-SP
Exemplo: Remoto ou Escritório, [ESTADO], [CIDADE], [BAIRRO]

## Requisitos

**Obrigatórios:**
- Conhecimento avançado de Javascript/JSX;
- Conhecimento avançado de React.js;
- Conhecimento de Redux e Redux Saga;
- Operações assíncronas;
- React Hooks;
- Integração do frontend em React.js com a API do Backend;
- Styled Components;
- Experiência comprovada de trabalho com React.js;
- Versionamento de código (Git);
- HTML 5;

**Diferenciais:**
- Testes unitários;
- Typescript;

## Contratação

PJ a combinar ou CLT

## Como se candidatar

Por favor envie um email para recruiting@object1ve.com com seu CV anexado - enviar no assunto: Vaga ReactJS remoto

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: eric@object1ve.com

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- Freela
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by thalesf** [comment]
Aceita part-time job ?

**Comment by willianbvsanches13** [comment]
Eu também atendo a todos os requisitos, se aceitar part-time envio CV

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
