### ISSUE TITLE
[Belo Horizonte] Front-end Developer na Nata.house

### ISSUE THREAD

**Issue by johnatandias** [frontendbr/vagas#3169]
## Nossa empresa

A nata.house surgiu em 2017 com o propósito de gerar mais valor e uma experiência melhor para o cliente e proporcionar mais espaço de desenvolvimento e aprendizado para seus colaboradores.

Hoje, com quase 3 anos de empresa, construímos uma cultura de transparência, excelência, colaboração, inquietude, em que cada um sabe da sua responsabilidade, contribuindo, assim, para a construção de uma nata melhor. Somos movidos por desafios, respiramos tecnologia e acreditamos que qualidade de software é a base de qualquer empresa digital!

Especialistas em desenvolvimento de Software, hoje trabalhamos com principalmente com JavaScript, atuando não só como fornecedores, mas de fato como parceiros de tecnologia dos nossos clientes. Além disso, nos preocupamos em construir um time com pessoas talentosas, alinhadas à cultura e que acreditam nos objetivos da empresa, para manter as pessoas engajadas, motivadas e crescendo junto com a nata.

## Procuramos alguém que:

- Têm interesse em atuar como referência técnica, transmitem seu conhecimento para seus pares de maneira clara;
- Apoie a resolução de problemas, tem proatividade e é orientado para resultados,
- Têm interesse em fomentar um ambiente colaborativo para todos,
- Atua com autonomia, usando a liberdade para opinar em processos e questões relacionadas ao cliente quando for preciso,
- É capazes de se adaptar a ambientes ambíguos e de colaborar em situações difíceis;
- Busca sempre adquirir mais conhecimento,
- Aberto a novos pontos de vista e maneiras de pensar.

## Local

Escritório, Minas Gerais, Belo Horizonte, Funcionários

## Requisitos
- Conhecimento de JavaScript (preferencialmente nos frameworks React, React Native)
- Noções de conceitos e ferramentas arquiteturais referentes ao ecossistema de aplicações, além de uma análise crítica e pragmática para utilizá-las dependendo do contexto da solução;
- Fascínio não só por desenvolver, mas em solucionar problemas e também pela melhoria contínua através de práticas que garantem a qualidade do seu código;

## Benefícios

- Temos vale-refeição/alimentação Sodexo de R$ 22,05 por dia;
- Para a galera do busão, vale-transporte de acordo com a necessidade, ou, se preferir, auxílio combustível no valor de R$120, sem desconto em folha;
- Bônus anual, pois, afinal, crescemos juntos! Se a empresa tem lucro, o mérito é seu e parte do lucro também;
- Plano de Saúde
- Segurança extra com o nosso Seguro de Vida.
- Lanche à vontade;

**Diferenciais:**

- Who run the world? You! Temos incentivo ao aprendizado de inglês;
- Carga horária de 40 horas semanais, de segunda a sexta;
- Horário flexível;
- Se você está se desenvolvendo e gerando resultado, por quê não receber proporcionalmente? Nada de ficar estagnado: temos plano de carreira definido
- Consultoria financeira para ajudar seu dinheiro render mais;
- Um happy hour mensal pago pela empresa;
- Auxílio financeiro para cursos, eventos e capacitações;
- No dress code (be you!)

## Contratação

CLT

## Como se candidatar

Se interessou? Para se candidatar, basta preencher o [formulário](https://forms.gle/ayKHL7nNPJnTNBhz6) e boa sorte! :)

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
