### ISSUE TITLE
[São Paulo - SP] Front-end Developer @ Evnts

### ISSUE THREAD

**Issue by xWul** [frontendbr/vagas#317]
## Descrição da vaga
Estamos em uma transição enorme, deixando de ser uma pequena startup para se transformar em uma grande empresa, todo a nossa plataforma está rodando em cima do que era nosso MVP que foi escrito às pressas, por isso, decidimos começar a reescrever partes do nosso sistema.
Estamos em busca de desenvolvedores para entrar de cabeça nesse projeto, além de desenvolver, você vai contribuir na escolha de quais tecnologias vamos utilizar e vai ajudar a recrutar novos membros para o nosso time.

## Local

Alameda Santos, São Paulo - Jardim Paulista (5 minutos da estação Trianon - Masp)

## Requisitos

**Obrigatórios:**
-   Experiência com desenvolvimento Web;
-   HTML (semântica, acessibilidade);
-   JavaScript (ES2015 / Design Patterns);
-   CSS (pré-processadores / arquitetura);
-   Experiência com SPA (Angular, React, Vue, etc...);
-   Gostar muito de aprender e compartilhar;

**Desejáveis:**
-   Experiência com grandes aplicações;
-   Conhecimento em testes de JavaScript (TDD / BDD);
-   Ter trabalhado com metodologia ágil;   

## Benefícios

- Horário flexível
- Home office
- No dress code (pode trabalhar de chinelo, bermuda, regata, etc)
- Time com uma vontade absurda de querer ser sempre o melhor

## Contratação
- CLT

## Nossa empresa

A **Evnts** é uma startup que em menos de 1 ano já passou por dois dos maiores processos de aceleração do Brasil (Seed e Oxigênio) e estamos em um crescimento absurdo. 

Nós somos a maior plataforma de hospedagem para eventos do Brasil, com a nossa plataforma o organizador do evento consegue selecionar hotéis e oferecer para os visitantes com a menor tarifa do mercado, em pouco tempo no mercado já nos tornamos a plataforma oficial dos principais eventos do Brasil como *CASE, Campus Party, Brasil Games Show, Shows da Livepass, Eventos da Porto Seguro, Eventos da Mitsubishi, QCon SP, FIRE e Rock in Rio.* Temos um time pequeno, porém, muito apaixonado pelo que faz e em constante evolução.

[Matéria sobre nós na InfoMoney](http://www.infomoney.com.br/minhas-financas/turismo/noticia/6365416/startup-brasileira-garante-descontos-ate-hospedagem-para-grupo-turistas)

## Como se candidatar

Envie um email para wesley@evnts.com.br com (CV, Github, Linkedin, etc...).

Colocar no assunto: Vaga Front-end Developer

Caso você tenha se interessado pela vaga, mas, acha que não tem o conhecimento técnico necessário, também pode se candidatar, estamos em um crescimento absurdo, pode ter certeza que vamos analisar com carinho (:

**Comment by xWul** [comment]
Labels:
- Pleno
- Sênior
- CLT
- Alocado
- Remoto - Parcial

**Comment by bcarvalho89** [comment]
Tenho parte do conhecimento obrigatório, mas tentarei mesmo assim.
O que seria o remoto parcial de vocês?

**Comment by MathMesquita** [comment]
> Remoto - Parcial

Podem especificar o quanto é esse parcial? :smile:

**Comment by xWul** [comment]
Sobre o **Remoto - Parcial**: Nós trabalhamos muito tempo como remote-first e ainda temos essa cultura, mas, como estamos em um momento de crescimento e aumentando muito o nosso time, estamos criando alguns processos, inclusive alguns para resolver os problemas que tivemos com o remote, como comunicação e organização, por isso, preferimos que você venha ao escritório pelo menos algum dia da semana enquanto estamos melhorando esses processos, mas, somos totalmente liberais com o remoto, se você se mostrar capaz de trabalhando remoto ter uma ótima comunicação com o time e quiser vir 1 dia por semana para o escritório, não tem problema algum, ou se quiser ir todos os dias para o escritório e em algum dia não ta na vibe de ir pro escritório, pode ficar home office numa boa.
Pode ter ficado confuso (hehe), para resumir, temos gente do nosso time que é de outro estado e está trabalhando 100% home office.

**Comment by ericprieto** [comment]
O stack de vocês hoje é qual? React ou Angular?

**Comment by rafael1995** [comment]
Enviado :)
