### ISSUE TITLE
[Brasília] Front-End Developer na POUPEX

### ISSUE THREAD

**Issue by neylorsousa** [frontendbr/vagas#3174]
## Nossa empresa

A **POUPEX** atua em todo o território nacional e opera com recursos captados em caderneta de poupança, tendo por objetivos permanentes:

- captar, incentivar e disseminar a poupança, propiciando ou facilitando a aquisição e a construção da casa própria aos seus associados;
- possibilitar, por meio de empréstimos de recursos da poupança, que a FHE promova empreendimentos habitacionais nas melhores condições de preço, qualidade e segurança, com vista ao atendimento de seus associados.

https://www.poupex.com.br/a-poupex/quem-somos/

## Descrição da vaga

Front-End Developer Sênior para atuar no desenvolvimento e sustentação de projetos intranet e internet.

## Local

Brasília - DF

## Requisitos

Veja os detalhes no edital: https://www.poupex.com.br/wp-content/uploads/sites/14/2020/03/SC017120_EditalCredenciamentoTI.v3doc.pdf

Perfil da vaga:  A2.B - Desenvolvedor Front end

## Benefícios

- Salário: R$ 17500,00

**Diferenciais:**
- 1h 30m horas de almoço
- O local de tabalho oferece: facilidade de estacionamento, refeitorio, biblioteca, próximo a clube e restaurantes. Prédio moderno e com boa estrutura de trabalho.

## Contratação

Pessoa Juridica

## Como se candidatar

Por favor envie um email para neylor.sousa@poupex.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor Front-End

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by RicardoWEBSiTE** [comment]
Há possibilidade da vaga ser remota ?



Em qui., 4 de jun. de 2020 às 09:03, Neylor Leandro de Sousa <
notifications@github.com> escreveu:

**Comment by neylorsousa** [comment]
@RicardoWEBSiTE não. Atualmente estamos remoto devido ao COVID, porém não se sabe como ficará essa opção no futuro.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
