### ISSUE TITLE
[São Paulo] Front-End Developer Pleno/Sênior [B8ONE]

### ISSUE THREAD

**Issue by hugoalvarenga** [frontendbr/vagas#3176]
## Nossa empresa

Nós somos a B8one e queremos mudar o mundo através de experiências digitais. Prezamos pela alta qualidade e queremos da melhor forma, auxiliar nossos clientes a conectar-se com seu negócio. Estamos em crescimento e procuramos pessoas que queiram fazer parte da nossa jornada! Somos focados em Performance, Usabilidade, Inovação, Design e Conteúdo. Adoramos desafios e queremos expandir cada vez mais! Por isso, precisamos de desenvolvedores que queiram aprender e gerar a diferença e inovação no mercado digital!

## Descrição da vaga

Como desenvolvedor Front-End, você terá como atribuição o desenvolvimento de interfaces e integrações alocado em um grande cliente da B8. A abordagem de novas tecnologias e proposta de utilização de padrões são sempre bem vindas em nosso time.

## Local

Alocado: São Paulo - SP

## Requisitos

**Obrigatórios:**

- 2+ anos de experiencia como desenvolvedor Front-End (utilizando ReactJS ou ECMAScript);
- Experiência 6 meses + em ReactJS
- Noções em Typescript;
- Conhecimento em padrões de projeto e melhores práticas em desenvolvimento de softwares;
- Inglês intermediário;
- VTEX

**Diferenciais:**

- NodeJS
- Styled Components
- Design System

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ X/dia
- Auxílio creche
- ...

**Diferenciais:**
- Horário Flexível
- Macbook Pro, deixe sua máquina como desejar. =)
- Ambiente descontraído
- No dress code

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para jobs@b8one.com com seu **CV** anexado e **Github** - enviar no assunto: **[VAGA] Front-End Developer - Front-End Brasil**

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 4 dias após cada processo.
E-mail para contato em caso de não haver resposta: hugo@b8one.com

## Labels
Alocação
Alocado
Regime
PJ
Nível
Júnior
Pleno
Sênior

#### Alocação
- Alocado 
- Remoto (até a quarentena acabar)

#### Regime
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by welll** [comment]
Olá @felipefialho , acredito que o label remoto não se encaixa para "alocação remoto até a quarentena acabar"

abs
