### ISSUE TITLE
[Porto Alegre] Front-End Developer na [Trinca]

### ISSUE THREAD

**Issue by Gabrielarochay** [frontendbr/vagas#3177]
**Temos uma vaga para Front-end Developer PL/SR aqui na Trinca!** 
É importante que você tenha sólida experiência em projetos digitais (web e mobile), seja versátil na utilização de tecnologias, detalhista, exigente com qualidade, autodidata e que valorize acima de tudo o trabalho em equipe.

// Habilidades que você precisa ter:

• Conhecimento sólido em Javascript e ReactJS;
• Conhecimentos em arquitetura e engenharia de software;
• Conhecimentos em teste unitários
• Conhecimento em metodologias ágeis
• Desejável conhecimento de UI/UX

O que ofereceremos e como é trabalhar na Trinca: https://trin.ca/procuramos-por-voce/

![Vaga_front-end](https://user-images.githubusercontent.com/66493175/83918281-c73a5d00-a74e-11ea-83b6-89a11b05e015.jpg)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
