### ISSUE TITLE
[Campinas] Front-end Developer Pleno/Senior na HDNIT

### ISSUE THREAD

**Issue by marcelocpinheiro** [frontendbr/vagas#3178]
## Nossa empresa

Nós somos um time especializado em entregar soluções de tecnologia que agregam valor, otimizam o tempo e trazem inovação ao seu modo de trabalho. Nossa missão é colaborar, disseminar o conhecimento e a cultura de empresas através de novas tecnologias e processos ágeis.

Há mais de 10 anos temos a experiência em desenvolvimento de softwares e soluções digitais.

Estamos buscando quem topa vir pra HDN por um propósito e aceitar o desafio na área de desenvolvimento, muito contato direto com os sócios. Aqui todos tem muita voz e oportunidades de crescimento (MUITA). 

## Descrição da vaga

Você vai atuar em clientes de expressão utilizando React, Vue ou Angular (Não precisa saber todos :D)

## Local
R. Rafael Andrade Duarte, 68 - Nova Campinas, Campinas/ SP
(Neste momento, estamos trabalhando remoto, e temos políticas para trabalho remoto mesmo fora da pandemia)

## Requisitos

**Obrigatórios:**
- Experiência Sólida com um dos frameworks listados: React, vue ou Angular
- Experiência com Typescript;
- Bom entendimento de git, bancos de dados (sql e nosql) e filas;
- Conheça sobre construção, implantação e teste automatizados;
- Conhecer conceitos de arquitetura e Design patterns;

**Desejáveis:**
- Capacidade de realizar várias tarefas, ser uma pessoa organizada e detalhista;
- Fortes habilidades no ambiente Unix / Linux;
- Familiarizado com princípios ágeis;

## Contratação
Cooperativa a combinar

## Como se candidatar

Por favor envie um email para marcelo.pinheiro@hdnit.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.
E-mail para contato em caso de não haver resposta: marcelo.pinheiro@hdnit.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- Cooperativa

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
