### ISSUE TITLE
[São Paulo] [Remoto] Front-end Developer Pleno na Niddel!

### ISSUE THREAD

**Issue by rfranco** [frontendbr/vagas#318]
## Job Description

We're looking for frontend developers willing to solve problems and learn new technologies throughout the whole software development process. You will be part of a lean, multicultural, remote team working in innovative and award winning technology. You will have the chance to work in an agile environment with cutting-edge technology all over the software stack. The technologies we use include Angular, Bootstrap, Typescript, Scala, Play, Docker, AWS, Redis,, among others.

### Our front-end stack:
- Angular 1.6.x e 2.x
- TypeScript 2.x
- Bootstrap 3.x e 4.x
- Webpack 2.x

## Location

We are an American Startup looking for a smart guys to be part of our remote team so you can work from any where in Brazil.

## Contract
PJ (to negociate)
Indefinite Period

### Responsibilities
- Prototype and build Single-page Applications (SPA);
- Pro-actively look for ways to improve product;
- Rapidly solve problems and fix bugs ;
- Full time dedication.
### Must Have:
- Experience in web development (JS/Angular/Bootstrap/HTML5/CSS); 
- Passion for delivering great user experience and usability; 
- Experience in building Web SPA in AngularJS 1.6 and 2.x; 
- Experience building web integrated software and applications; 
- Clean code and Git; 
- Willingness to learn; 
- Readiness to work in a fast-paced, ever-changing environment; 
- Self-discipline and maturity to work cooperatively and constructively with other remote team members
### Nice to Have:
- Contributes to open source and has sample links; 
- Visual design and/or UX skills; 
- Build Tools (Webpack);  
- Great written communication and documentation abilities; 
- Data-informed product development: analytics, A/B testing, etc.

## About Us

Niddel provides the industry's first Autonomous Threat Hunting System by using machine learning and data science techniques to mimick extremely talented security analysts performing their daily tasks. Organizations use Niddel Magnet to rapidly detect unknown security breaches and malware infections with accuracy and at scale. 

For more information, visit: [niddel.com](http://www.niddel.com) and follow [@NiddelCorp](https://twitter.com/NiddelCorp) on Twitter.

https://conf.splunk.com/sessions/2016-sessions.html#search=niddel&

## How to apply

https://goo.gl/forms/U9T59jWUXIDHriDQ2

**Comment by rfranco** [comment]
@LFeh no caso a vaga seria Remoto fulltime e para a própria empresa e não seria alocado.

**Comment by LFeh** [comment]
Done

**Comment by nilkesede** [comment]
Enviado! 😄
