### ISSUE TITLE
[Remoto] Front-end Developer React/VueJS 

### ISSUE THREAD

**Issue by MariEasy2Recruit** [frontendbr/vagas#3185]
Oportunidade em regime de contratação Home Office

Empresa que fornece soluções para Tecnologia voltada ao público adulto.
Necessário possuir conhecimento nível Pleno em React ou Vue JS.

Atuará em regime de contratação PJ. Valor da Hora R$ 50,00.
Necessário ter disponibilidade de no mínimo 06 horas diárias.

encaminhar curriculo para mariana@recrutamentofacil.com

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
