### ISSUE TITLE
[São Paulo - SP] Ruby on Rails Developer na TZ3 Tecnologia

### ISSUE THREAD

**Issue by dgilbertoni** [frontendbr/vagas#3186]
## Nossa empresa

Estamos há 11 anos no mercado e neste período já desenvolvemos centenas de projetos para empresas de todos os portes e segmentos de mercado. Somos especialistas em desenvolvimento de sistemas web, apps, e-commerce e robôs de automação de processos. 

[https://tz3.com.br](https://tz3.com.br)

## Descrição da vaga

Buscamos Ruby on Rails Developers para atuar

## Local

São Paulo - SP

## Requisitos

**Obrigatórios:**
- Experiência em Ruby on Rails;
- Experiência em PostgreSQL;
- Conhecimentos de APIs RESTFUL;
- Experiência prévia nas linguagens informadas;
- Habilidades interpessoais de escrita e de comunicação verbal;

**Desejáveis:**
- Conhecimento em metodologias ágeis (Scrum/Kanban);
- Conhecimentos de AWS
- Conhecimentos de CI/CD
- Conhecimentos de Bootstrap / JQuery
- Inglês avançado

## Benefícios

- Horário Flexível
- Ambiente Informal

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para rh@tz3.com.br com seu CV, pretensão de remuneração e disponibilidade de início e o código RoR-SP no campo assunto. 

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
