### ISSUE TITLE
[Belo Horizonte] Front-End Developer na Raro Labs

### ISSUE THREAD

**Issue by rodrigosol** [frontendbr/vagas#319]
## Descrição da vaga

Estamos em busca de um profissional especializado no desenvolvimento  front-end para fazer parte do nosso time de alto desempenho.

## Local

Bairro Mangabeiras

## Benefícios

- Excelentes condições de trabalho
- Ambiente informal
- Salário compatível com a função
- Plano de Saúde
- Plano Odontológico
- Participação nos Lucros
- Treinamentos
- Participação em congressos
- Horário Flexível
## Requisitos

**Obrigatórios:**
- Experiência com AngularJS
- Bootstrap

**Desejáveis:**
- ES6
- ReactJs
- Redux
- AngularJs 2.0
- IONIC

## Contratação

CLT - R$ 2500,00 a 4500,00

## Nossa empresa

A Raro Labs desenvolve softwares de alta complexidade para os mais variados segmentos de negócio. Utilizamos uma abordagem focada na qualidade do produto final, que permite a construção de soluções complexas, integradas e sob medida para o negócio dos nossos clientes.

## Como se candidatar

Por favor envie um email para contato@rarolabs.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

**Comment by matheusggds** [comment]
Alocado?

**Comment by rodrigosol** [comment]
👍
