### ISSUE TITLE
[Belo Horizonte] Front-End Developer na IN8

### ISSUE THREAD

**Issue by gucanabrava** [frontendbr/vagas#3191]
Qual será o seu papel?

Você será parte ativa no nosso time de desenvolvimento backend. Esperamos que você contribua com ideias e talento para criar novas funcionalidades em API’s e sistemas (front end).

Como Será Seu Dia a Dia:

Você estará diretamente envolvido na criação de novas telas para nossos sistemas, API’s. Temos muitas funcionalidades para desenvolver e muitas correções que precisam ser feitas. Você trabalhará com liberdade, independência para entregar resultados e sugerir novidades.

O que pode ser desafiador:

Nossos sistema são muito dinâmicos e passam por várias mudanças/ajustes, além disso o sistema é projetado para alta disponibilidade e está distribuído em nuvem. Sua criatividade será constantemente acionada para criar novas soluções e entregar valor para nós e nossos clientes.

Esperamos que você:

Saiba programar em PHP (5 e/ou 7.x), python e/ou NodeJS, entenda bem a criação e manutenção de API’s restfull, domine banco de dados MySQL, saiba bastante de CSS, HTML, JS e saiba versionar o código utilizando Git.

Vamos ficar felizes se você:

Já tiver trabalhado com AngularJS e ou React.JS. Se você já trabalhou com API’s e sabe bem como criar, dar manutenção e (eventualmente) documentar, será sensacional. Se você já tem alguma experiência com AWS. Se você se provar muito atento e preocupado com detalhes e usabilidade você sai bem na frente.

Você vai amar trabalhar aqui se:

Se você consegue organizar bem seu horário, vai amar ter horário flexível e zero dress code. Pra nós o importante é você trabalhar confortável, tanto com o horário tanto com a sua roupa. Nós também pagamos os benefícios em dinheiro, ou seja, alimentação e transporte caem direto na sua conta para você utilizar onde achar melhor. E claro se tudo vai bem, ainda rola aquele bônus.

Mas por que eu devo ir trabalhar com vocês?

Todos os profissionais da IN8 fazem a diferença. Somos uma empresa horizontal, suas ideias chegam onde podem fazer a diferença. Sua evolução profissional será tratada,continuamente.

[Vaga no linkedin](https://www.linkedin.com/jobs/cap/view/1837108338/?pathWildcard=1837108338&trk=mcm)

**Comment by evertonProgramadorCriativo** [comment]
Eu gostaria de uma oportunidade de fazer teste para vaga junior , meu email e
evertonprogramadorcriativo@gmail.com

**Comment by ryanmata40** [comment]
https://ryanmata40.github.io/weverton-mata/
Estou muito interessado e me vejo qualificado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
