### ISSUE TITLE
[Remoto] Desenvolvedor Front End na Onyo

### ISSUE THREAD

**Issue by komyg** [frontendbr/vagas#3192]
# Desenvolvedor Frontend na Onyo

A experiência de refeição fora do lar nunca mais será a mesma. É por isso que estamos à procura de um Desenvolvedor Frontend para uma missão que ajudará a colocar nas mãos de nossos clientes o poder absoluto de escolher, o quê e quando comer. Você desenvolverá produtos incríveis, que irão transformar a vida dos nossos clientes e parceiros.

## Sobre nós:

Temos uma forte cultura moldada pelos nossos valores.

- "Trabalhamos em equipe, valorizando todas as contribuições individuais"
- "Somos máquinas de aprender”
- "A melhor experiência do cliente é o que nos guia”
- "Somos humildes e determinados"
- "Praticamos a transparência"
- "Agimos como donos"
- "Somos resilientes"

## Como trabalhamos:

Damos um alto valor ao poder de escolha em todos os assuntos, desde o design do código até opções de vida, podendo também decidir de onde quer trabalhar.

- Trabalhamos remotamente.
- Amamos desafios e os encaramos de frente sem medo.
- Acreditamos que temos sempre o melhor time, e você pode ser parte disso.

## Assim que ingressar em nosso time, esperamos de você:

- Contribuir com a concepção do produto como um todo para entregar a melhor experiência para os nossos usuários.
- Contribuir na implementação de novas features do zero, bem como melhorar o código existente.
- Ser dono do produto e lutar para a sua melhoria e o seu sucesso.
- Interagir com todas as equipes, do Backend à Operações, para ajudar a criar as melhores aplicações Front end de todos os tempos.
- Escrever código limpo, com testes automatizados e com deploy contínuo
- Resolver débitos técnicos

## O que estamos procurando:

- Experiência com Javascript, Typescript, HTML e CSS.
- Experiência com Frameworks de SPA como Angular e React.
- Experiência com frameworks de gestão de estado como Redux.

## São diferenciais:

- Experência com Apollo Graphql.
- Experiência com Python, SQL e GraphQL.
- Experiência com design e UX.
- Experiência com trabalho remoto.

## Candidatura

Para se candidatar a essa vaga preecha o formulário nesse link: https://onyo.recruiterbox.com/jobs/fk01bgx?source=frontend-br

**Comment by evertonProgramadorCriativo** [comment]
Eu gostaria de uma oportunidade de fazer teste para vaga junior , meu email e
evertonprogramadorcriativo@gmail.com

**Comment by komyg** [comment]
Oi @evertonProgramadorCriativo , para participar do processo, preciso que você se cadastre no link:  https://onyo.recruiterbox.com/jobs/fk01bgx?source=frontend-br.

Obrigado,
Felipe

**Comment by HenryKun55** [comment]
Candidatura enviada!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
