### ISSUE TITLE
[Brasília/DF] Front-end Developer na Fóton Informática

### ISSUE THREAD

**Issue by fotonti** [frontendbr/vagas#3196]
## Nossa empresa
A Fóton Informática é uma empresa de tecnologia especializada no mercado financeiro. Ajudamos a transformar o dia a dia dos bancos e da população brasileira, criando soluções que permitam uma maior aproximação das instituições bancárias a seus clientes (mobile banking, caixa eletrônico, agência, etc). Também atuamos como parceiros especializados no desenvolvimento e manutenção de produtos e serviços financeiros. Venha fazer parte do nosso time!

## Descrição da vaga
Estamos em busca de Front-End Developers [PLENO] para fazer parte da nossa equipe, alocada no cliente. 

## Local
Alocado no cliente, [DF], [BRASÍLIA], [ASA SUL]

## Requisitos

**Obrigatórios:**
- Graduação completa na área de TI
- 2 anos de experiência com Angular
- Experiência com Primefaces, HTML, CSS, JavaScript e Bootstrap;
- Disponibilidade para aprender novas tecnologias;

**Desejáveis:**
- Java, JavaEE, Hibernate, EJB, JAX-RS, JAX-WS;
- Banco de Dados: Postgres, SQL Server;
- Plus: Jboss, Maven, Teste Unitário, JMS e Git;
- Desejável: Oracle Certified Professional – Java SE Programer (Versão 5 ou Superior).

## Benefícios
Plano de Saúde nacional, Plano Odontológico, Seguro de Vida, Vale Alimentação / Refeição, Programa de Incentivo à Educação, Programa de Incentivo a Certificações e Auxílio Creche (para as fotonianas)

**Diferenciais:**
Horário flexível

## Contratação
CLT, efetivo. 

## Como se candidatar
Envie-nos o seu currículo através do email rh@foton.la informando no campo assunto a vaga pretendida. 

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
