### ISSUE TITLE
[SP] Front-end Developer na Afya

### ISSUE THREAD

**Issue by camilaintera** [frontendbr/vagas#3197]
A Afya está revolucionando o mercado de educação médica no Brasil e você pode entrar nesse movimento!

Nascemos oficialmente em 2019, com o objetivo de sermos a principal parceira dos médicos em suas jornadas de formação, nós **já formamos mais de 100 mil médicos** pelo Brasil e contamos com um time de **4.000 pessoas** para garantir que os nossos alunos possam transformar seus sonhos em realidade! 

**Em plena pandemia** pudemos ter maior noção de quão importante é o nosso papel, e por isso nesse estamos focados em **expandir o nosso time de tecnologia** para atender a todas as nossas unidades espalhadas pelo país.

Trabalhamos com desenvolvimento focado em **React**, e buscamos pessoas comunicativas, com espírito empreendedor e dispostas a crescer exponencialmente com a Afya. Serão bem-vindos conhecimentos em SEO e demais frameworks.

**E aí? Topa o desafio? 🙂**
https://byintera.in/rx

**Comment by felipefialho** [comment]
Olá @camilaintera a vaga tá completamente fora dos padrões, pode seguir nosso template? Obrigado.
