### ISSUE TITLE
[São Paulo] Vuejs Front-end Developer na TI Talentos

### ISSUE THREAD

**Issue by Renatadt** [frontendbr/vagas#3199]
## TI Talentos

A TI Talentos é especialista em apoiar start ups e PMEs a recrutar certo com educação para o recruiting e encontrar top talents para codar em ambientes flexíveis de código limpo. 

## Descrição da vaga

Procuramos uma pessoa que desenvolva vuejs (Front End) para fazer parte do time de uma fintech paulistana! A cultura oferece horizontalidade, ou seja, aqui os times têm opinião e são envolvidos nas decisões! Estão crescendo rápido (previsão para este ano de 5 a 10 x em relação a 2019).

Quem entrar agora vai viver duas experiências essenciais para qualquer desenvolvedor que quer crescer para uma posição de relevância numa empresa de tecnologia:
Evoluir um produto de algo funcional para um produto escalável e construir algo do zero! 

Você vai liderar todo desenvolvimento de front end das aplicações, garantir que o time utilize as boas práticas e metodologias para manter o código efetivo, limpo e legível, participar e contribuir com as decisões da arquitetura e processos e ajudar o time a se desenvolver tecnicamente. 

## Local

Exemplo: Escritório, [São Paulo], [São Paulo], [Pinheiros]

## Requisitos

**Obrigatórios:**
- Experiência considerável em desenvolvimento de frontend com vuejs
- Experiência com CSS Extension Languages (SASS, LESS), JavaScript (ES6/ES7) e bundlers (webpack), 
 assim como metodologias de organização de código (BEM, eslint)

**Desejáveis:**
- Experiência em Node.js, Nuxt e TypeScript

## Benefícios

- VR de R$ 25/dia
- Bônus por metas e avaliação

## Contratação

PJ valores de 8 a 11 k

## Como se candidatar

http://bit.ly/renatatedesco 

## Tempo médio de feedbacks

em tempo real, já que nos falaremos via whatsapp e todo processo começará por lá. A experiência não morre e não precisa ir até o seu e-mail agora mandar CV. Queremos o skill de habilidades e te conhecer primeiro!

E-mail para contato em caso de não haver resposta: renata@titalentos.com.br

#### Regime
- PJ

#### Nível
- Pleno a Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by oiagorodrigues** [comment]
Estou interessado. Entrarei em contato.
