### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor Front-End na Mongeral Aegon

### ISSUE THREAD

**Issue by hugodutra** [frontendbr/vagas#32]
## Desenvolvedor Front-End na Mongeral Aegon

Na área de marketing digital da Mongeral Aegon, uma empresa de seguros e previdência com mais de 180 anos, tão rolando duas vagas pra front-end aqui no Rio.

 Apesar da idade da empresa, nossa equipe é uma equipe ~xovem~ e ~descolada~. Temos tentado aplicar várias coisas novas por aqui e você vai ter abertura para propor e entregar projetos bacanas.

Curtimos muito metodologias ágeis, fazemos tech talks às sextas-feiras e temos uma cestinha de basquete pra você praticar caso desista de ser programador.

**Coisas não tããão legais:**

- Precisa já estar formado.
- Precisa usar roupa social.
- Não rola ser home office.

## Local

Rio de Janeiro - Centro

## Benefícios

- Vale Transporte
- Vale Refeição (R$ 27,46 ao dia)
- Vale Alimentação (R$ 469,85)
- Auxílio café da manhã em uma padaria perto do trabalho
- Plano de saúde e dental
- Participação nos lucros
- Fundo Multipatrocinado (previdência)

## Requisitos (Júnior ou Pleno)

**O que você PRECISA saber:**

- Javascript
- Algum pré-processador
- Algum task runner
- HTML5
- Versionar seu código (usamos GIT)
- Wordpress (apenas para uma das vagas)
- Saber trabalhar com Linux

**Aquele famoso ~plus a mais~:**
- Algum framework Javascript (Angular, Ember, React, backbone, etc…)
- Participar da comunidade, ir a eventos e tal

## Contratação

CLT

## Como se candidatar

Se tu curtiu e tá afim de trabaio, manda um currículo/Linkedin com pretenção pra nós. hadutra@mongeralaegon.com.br
Se você tiver um portfólio maneiro ou Github pode mander junto.

**Comment by Cleysonlb** [comment]
Se não fosse a parte de precisar ser formado eu me candidataria! Vaga bem daora, boa sorte :)

**Comment by hugodutra** [comment]
Isso é uma exigência da empresa todas as áreas. Estamos tentando mudar isso, mas por enquanto não tem jeito. :/

**Comment by walves** [comment]
Empresa dos sonhos de qualquer desenvolvedor, pena que não sei tudo que precisa, senão até me candidataria a jr.

**Comment by hugodutra** [comment]
Fala @walves

Manda ae seu currículo, que a gente dá uma olhada. :)

Abs,

**Comment by linikerdev** [comment]
Analista de sistemas a 2 anos, estou no 6º período de Ciência da Computação, trabalho com front-end e Back-end, posso concorrer a vaga ?

**Comment by tuliocastro** [comment]
Olá Hugo blz? Eu estava procurando algumas vagas para o Rio, essa vaga é
apenas para iniciantes? Eu sou Full Stack a 8 anos, atualmente sou PJ com
uma pequena empresa em brasília.

Grande abraço

_________________________________

Túlio de Almeida Castro
www.tuliocastro.com.br

Skype: tulio.ac88
_________________________________

2016-04-20 11:58 GMT-03:00 Liniker Silva <notifications@github.com>:

**Comment by patriciaquintiere** [comment]
Olá Hugo,
Já fecharam essa vaga?

**Comment by hugodutra** [comment]
Oi, @patriciaquintiere ainda não fechamos. Você consegue me mandar seu currículo hj ainda?

**Comment by patriciaquintiere** [comment]
Oi @hugodutra, te respondi no teu email hadutra@mongeralaegon.com.br ... Veja lá se meu conhecimentos servem para vaga ;)

**Comment by thallesmarchetti** [comment]
Boa noite,
Estou no ultimo período e teria alguma possibilidade de candidatura?

**Comment by hugodutra** [comment]
Pessoal, fechamos a vaga. Muito obrigado a quem se interessou.

Abraços!

**Comment by LFeh** [comment]
Valeu @hugodutra !

**Comment by camilatigre** [comment]
@hugodutra 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by linikerdev** [comment]
Olá @hugodutra  a vaga ainda esta em aberta ? o teste não parece complexo...
