### ISSUE TITLE
[João Pessoa - PB] Front-End Developer na Fractal Tecnologia

### ISSUE THREAD

**Issue by renanol** [frontendbr/vagas#320]
## Descrição da vaga

Desenvolver aplicações Web Frontend que se comunicam com APIs RESTful.

## Local

Remoto

## Requisitos

**Obrigatórios:**

- HTML 5
- CSS 3
- Javascript (ES6)
- Vue.js ou React
- Framework CSS: Bootstrap 4, Bulma, Foundation, etc
- Testes Unitários, e2e
- Git
- Linux
- SCRUM
- Experiência em UX/UI

**Desejáveis:**

- Node.js e NVM
- NPM ou Yarn
- Testes com Mocha, Sinon e Chai
- Rotas com VueRouter ou React Routes
- Gerenciamento de state com Vuex ou Redux
- Requisições HTTP com Axios
- Transpiler pra CSS como SASS ou POSTCSS
- Code coverage (Karma, Istambul, Jasmine)

## Contratação

PJ ou Autônomo a combinar

## Nossa empresa

A Fractal Tecnologia é uma empresa que visa contribuir com a melhoria na educação do mundo através do desenvolvimento de ferramentas que facilitam a vida de estudantes e educadores. Nossa filosofia é que através do aprendizado conseguimos nos tornar pessoas melhores e assim contribuir para um mundo melhor, por isso damos incentivo ao auto-desenvolvimento investindo na sua carreira e lhe proporcionando horários flexíveis.
Temos um ambiente de trabalho flexível, moderno, descontraído e colaborativo onde sua opinião é importante para crescermos juntos.

## Como se candidatar

Por favor envie um email para recrutamento@fractaltecnologia.com.br com seu CV anexado - enviar no assunto: Vaga Front-End

**Comment by ygorlazaro** [comment]
bom dia @renanol , a vaga ainda está aberta?

**Comment by renanol** [comment]
@ygorlazaro está sim.

**Comment by ygorlazaro** [comment]
@renanol enviado
