### ISSUE TITLE
[SP] Front-end Developer na Afya

### ISSUE THREAD

**Issue by camilaintera** [frontendbr/vagas#3200]
## Nossa empresa

Nascemos oficialmente em 2019, com o objetivo de sermos a principal parceira dos médicos em suas jornadas de formação, nós **já formamos mais de 100 mil médicos pelo Brasil** e contamos com um **time de 4.000 pessoas** para garantir que os nossos alunos possam transformar seus sonhos em realidade!

## Descrição da vaga

**Em plena pandemia** pudemos ter maior noção de quão importante é o nosso papel, e por isso nesse estamos focados em **expandir o nosso time de tecnologia** para atender a todas as nossas unidades espalhadas pelo país.

Trabalhamos com desenvolvimento focado em React, e buscamos pessoas comunicativas, com espírito empreendedor e dispostas a crescer exponencialmente com a Afya. Serão bem-vindos conhecimentos em SEO e demais frameworks.

O desafio corresponde a auxiliar os outros profissionais do time e trabalhar com um perfil cross dos nossos produtos!

## Local

Exemplo: Escritório, SÃO PAULO/SP.

## Requisitos

**Obrigatórios:**
- Conhecimentos avançados em React

**Desejáveis:**
- Conhecimentos de SEO
- Conhecimentos de demais frameworks

## Benefícios

- Vale-Transporte
- Vale-Refeição
- Auxílio Médico
- Auxílio Odontológico
- PLR
- Gympass

**Diferenciais:**
- Política de Home Office

## Contratação

CLT

## Como se candidatar

Deixe as suas informações registradas no site: https://byintera.in/rx

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
