### ISSUE TITLE
Barueri/SP - Senior React Developer na Sovos

### ISSUE THREAD

**Issue by thalitafl** [frontendbr/vagas#3201]
## Nossa empresa

Digital technology has forever changed business. Now, it’s transforming tax. Soon, tax enforcement will be part of every business process - and every transaction.
As governments go digital, financial systems and traditional tax software can't keep up. And, businesses now face escalating risk and mounting compliance costs.
Sovos was built for the digital future of tax. 

## Descrição da vaga

As a Senior React Developer you will be responsible for the research, design, implementation, testing and maintenance of the product.
Analyze, design and development front-end pages according to the Product Owner directives.
Code inspections: Ensure that the code applies best React practices.
Develop screens using React and unit tests creation.
Generate documentation for on-boarding new team members.

## Local

[Barueri], [SP]

## Requisitos

Bachelor’s Degree in related field/discipline preferred.
High English skills required (written and verbal).
Minimum of 3 years of experience workingw with React
Understanding of agile methodologies like Scrum, Kanban or XP;
Advanced knowledge of these languages and libraries: JavaScript, React, Redux, HTML5;
Advanced knowledge of React lifecycle and React + Redux.
Knowledge of any other language, JavaScript framework, library is a plus (Typescript, AngularJS, Vue, etc.).
Knowledge of C#, TSQL, PL/SQL as a plus.
Knowledge of SDLC and CI with VisualStudio, JIRA, Git/GitFlow, BitBucket and Team City;
Knowledge of modern software development principles like OOP, Clean Code, TDD, SOLID and Design Patterns;
Ability to achieve results in a fast-paced dynamic environment with shifting priorities and deadlines.
Ability to troubleshoot problems under pressure.
Cultivate and foster strong working relationships with colleagues, external clients and business partners.
Resolving conflicts across team.

## Contratação

CLT

## Como se candidatar

Apply no Link: https://hrbrg.co/il3lsh

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo e você pode contatar RH em caso de dúvidas.

#### Alocação
- Alocado / Remoto durante a pandemia

#### Regime
- CLT

#### Nível
- Senior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
