### ISSUE TITLE
[Curitiba/Remote] Senior FullStack RoR + React.js na Visionnaire

### ISSUE THREAD

**Issue by raulbalestra** [frontendbr/vagas#3202]
Business
a platform that helps families to find the best matching care providers through a different website such as Housekeeper.com,  HouseSitter.com,  CleaningLady.com, etc.

Requirements
Our client is looking for a Senior FullStack React + Ruby on Rails. 

The engineer will be managed by the VP of engineering and will be building a small project. On the project delivery results, the client will make a decision whether to proceed with the engineer for a longer period. The engineer is expected to be skilled enough to be able to lead the project himself without micromanagement from the customer's side.

Duration: 2-3 weeks of full-time work for a small project. If the collaboration goes well, the client will consider prolonging the contract for a longer period.

Budget: 11k PJ, if you are a TOP candidate the budget can be higher. 

Como se candidatar:
Por favor envie um email para raul.balestra@visionnaire.com.br com seu CV anexado - enviar no assunto: Senior FullStack RoR + React.js

Alocação:
Alocado ou Remoto
Regime:
PJ
Nível:
Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
