### ISSUE TITLE
[Barueri - SP] Front-end Developer Jr ou Pleno na Econverse Digital

### ISSUE THREAD

**Issue by robsonss** [frontendbr/vagas#3204]
## Descrição da vaga

Em plena pandemia estamos em crescente expansão, e como o ecommerce é fundamental para o nosso crescimento, e a sustentabilidade da economia hoje. Estamos em busca de Desenvolvedores Front End Junior e Pleno, afim de trabalhar no crescimento do ecommerce e digital que a pandemia vem nos trazendo como desafio.

## Local

São Paulo - Barueri

## Benefícios

- Vale Transporte
- Vale Refeição e/ou Vale Alimentação
- Plano de saúde
- Jornada Flexível
- PLR (Participação nos Lucros)

## Requisitos

**Obrigatórios:**
- HTML, CSS, Java Script, Jquery
- Pré-processadores Sass, Less ou outros
- Automatizadores de Tarefas como: (Grunt ou Gulp)
- Não utilizar framworks bootstrap, foundation, ou afins

**Diferenciais:**
- Boas práticas de SEO
- Vtex
- React
- Vue.js
- APIs Rest
- PHP
- MySQL

## Contratação

CLT

**Observações:
- Estamos trabalhando 100% home office no momento, mas a posição é para atuar na Agência após a pandemia.

## Nossa empresa

​Somos especializados em gestão completa para e-commerce. Trabalhamos forte em cima de usabilidade, arquitetura e estudo de métricas para lojas virtuais.

## Como se candidatar

Por favor envie um email para robson@agenciaeconverse.com.br com seu CV anexado e Portfolio se possuir - enviar no assunto: Vaga Front-end Developer

## Alguns Cases nossos

- Vila Romana
- Duratex
- Pearson
- Aleatory

## Labels

- Alocado
- CLT
- Junior
- Pleno
- Vtex
- Shopify

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
