### ISSUE TITLE
[Remoto] Pessoa Desenvolvedora Full Stack na Gupy

### ISSUE THREAD

**Issue by silvawillian** [frontendbr/vagas#3207]
## Nossa empresa

A Gupy é uma empresa de tecnologia que une um grupo de pessoas desenvolvedoras, engenheiras e cientistas apaixonados em gerar inovação. Somos movidos por grandes desafios e precisamos de pessoas que amem tecnologia, aprendizado constante, e que tenham muita gana para nos ajudarem a transformar a Gupy na melhor e maior empresa de Recrutamento Tech do Brasil.

Atualmente temos um índice de desemprego muito alto no Brasil e uma guerra por talentos a todo vapor. Por isso, nosso propósito é oferecer contratações mais ágeis, justas e encantadoras para os nossos clientes e candidatos.

Estamos crescendo muito rápido e criando a cada dia um produto ainda mais poderoso. O segredo disso? As pessoas incríveis que fazem parte conosco dessa construção contínua.

Então, quer saber um pouco mais sobre nossos valores, rituais do dia a dia, modelo de trabalho de nossos gupiers, desafios e ainda ter a oportunidade de fazer parte dessa história?

Se inscreva, e embarque nessa jornada com a gente! 🚀 💙

## Descrição da vaga

Estamos expandindo nossa arquitetura de serviços e queremos sua ajuda! Se você é a pessoa que sabe:

- Desenvolver APIs usando Node.
- Implementar telas com HTML5 e CSS;
- Desenvolver aplicação em React
- Conhecer (ou querer aprender) tecnologias como Kinesis, AWS, Kubernetes, PostgresSQL, Redis, ElasticSearch, React, Redux, Saga, Node e diversas outras, então a Gupy é o lugar para você! 

Além disso, estamos crescendo muito, mais de 20% ao mês, e assim enfrentamos diversos desafios, por isso, nós buscamos alguém com muita vontade em nos ajudar a:

- Evoluirmos a nossa arquitetura de serviços de forma escalável, suportando centenas de milhares de requisições por minuto;
- Descobrirmos novas técnicas e tecnologias para superar todas as expectativas de atendimento e de produto dos nossos usuários;
- Sermos cada vez mais ágeis em nossas entregas, utilizando metodologias como Scrum e Kanban;
- Desenvolvermos cada vez mais por meio de mentorias, parcerias com AWS e trocas de conhecimento em guildas internas focadas em diversas áreas da tecnologia;
- Estarmos cada vez mais ativos nas comunidades, participando de eventos como BrazilJS, Campus Party, Hackathons com Laboratoria, realizando nossas tech talks com pessoas desenvolvedoras referências internas e externas e sediando diversos meetups!
- Continuarmos a focar em um modelo de Tecnologia e Negócio andando completamente juntos.

## Local

Remoto.

## Requisitos

Como requisitos básicos, você deve ter:

- Experiência como pessoa desenvolvedora de software;
- Bom conhecimento em testes de unidade / funcionais / integração;
- Hábito de aplicar boas práticas de engenharia de software;
- Hábito de fazer unit tests no dia a dia;
- Hábito de fazer refatoração no dia a dia;

Você se destaca, se tiver:

- Mínimo 6 meses de experiência em NodeJS;
- Mínimo 6 meses de experiência em React;
- Muito brilho no olho com nosso propósito de termos cada vez mais pessoas realizadas em seus trabalho, através de contratações mais ágeis, justas e encantadoras!

## Benefícios

Oferecemos uma lista completa de benefícios, incluindo:

- Salários competitivos, com a possibilidade de virar sócio da Gupy! 
- Plano odontológico e médico;
- Flexibilidade de horários;
- Vale refeição;
- Subsidiamos uma parceria com o Zenklub, uma plataforma de psicólogos e coaches online, para focarmos 100% no bem estar e saúde mental de cada Gupier aqui dentro!  
- Um clube inteiro de descontos para viagens, lazer, restaurantes e até mesmo aquela pós-graduação tão sonhada! 

Além disso tudo, incluímos também alguns benefícios diferentes e únicos:

- Trabalhar e trocar conhecimentos diários com um time referência no mercado;
- Participar deste time incrível, de uma cultura forte, que curte Karaokê e noites de luau em nossa varanda, com ou sem cerveja (você escolhe);
- Trabalhar em uma startup que preza pelo trabalho em equipe, diversidade e acredita que a diferença é um dos maiores fermentos para nosso crescimento;
- Ter contato com mentores internacionais, especialistas na sua área;
- Criar um produto que brilha os olhos de clientes e usuários;
- Aprender e crescer na jornada, sempre se divertindo;

## Contratação

CLT ou PJ

## Como se candidatar

Inscreva-se pelo link: https://bit.ly/gupy-fullstack-205724

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by paulo70** [comment]
@silvawillian Remoto full time ou apenas no período da pandemia?

**Comment by silvawillian** [comment]
Oi, @paulo70! Remoto full time!

**Comment by nicollemadeira** [comment]
Oi, @silvawillian. Me candidatei pra vaga no dia 29 de maio mas ainda não obtive uma resposta. Sabe se há algum tipo de feedback pra esse caso?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
