### ISSUE TITLE
[Remoto] Tech Lead na Gupy

### ISSUE THREAD

**Issue by silvawillian** [frontendbr/vagas#3208]
## Nossa empresa

A Gupy é uma empresa de tecnologia que une um grupo de engenheiros de softwares apaixonados em gerar inovação para oferecer contratações mais ágeis, justas e encantadoras à sociedade. Somos movidos por grandes desafios e precisamos de pessoas que amem tecnologia, aprendizado constante, e que tenham muita gana para nos ajudarem a transformar a Gupy na melhor e maior empresa de Recrutamento Tech do Brasil.

Estamos crescendo muito rápido e criando a cada dia um produto ainda mais poderoso. O segredo disso? As pessoas incríveis que fazem parte conosco dessa construção contínua.

## Descrição da vaga

Como Tech Lead você vai:

- Ser responsável pelo desenvolvimento e crescimento de equipes de alto desempenho de pessoas desenvolvedoras;
- Desenvolver a habilidade de motivar e engajar sua equipe com o propósito da Gupy e com a missão de seu time;
- Conhecer e garantir o cumprimento de processos e boas práticas de desenvolvimento;
- Realizar 1:1s e promover a cultura Gupy em seu time, com foco em colaboração, melhorias contínuas e muito aprendizado 
- Acompanhar os OKRs de seu time;
- Acompanhar a saúde das sprints, acompanhando as dificuldades e desafios de cada membro do time;
- Ser responsável, juntamente com sua equipe, pelo monitoramento dos serviços que seu time mantém em produção;
- Ser o dono do processo de recrutamento de novos gupiers de seu time

Além disso, estamos crescendo muito, mais de 20% ao mês, e assim enfrentamos diversos desafios, por isso, nós buscamos alguém com muita vontade em nos ajudar a:

- Evoluirmos a nossa arquitetura de serviços de forma escalável, suportando centenas de milhares de requisições por minuto;
- Descobrirmos novas técnicas e tecnologias para superar todas as expectativas de atendimento e de produto dos nossos usuários;
- Sermos cada vez mais ágeis em nossas entregas, utilizando metodologias como Scrum e Kanban;
- Desenvolvermos cada vez mais por meio de mentorias, parcerias com AWS e trocas de conhecimento em guildas internas focadas em diversas áreas da tecnologia;
- Estarmos cada vez mais ativos nas comunidades, por meio de um orçamento ousado para desenvolvimento por meio de eventos como BrazilJS e Campus Party, participando de Hackathons com Laboratoria, realizando tech talks com desenvolvedores referências internos e externos e sediando diversos meetups!
- Continuarmos a focar em um modelo de Tecnologia e Negócio andando completamente juntos. 

## Local

Remoto.

## Requisitos

Como requisitos básicos, você deve ter:

- Experiência com metodologias ágeis e suas aplicações;
- Habilidade de apontar eventuais falhas no código e prover soluções de forma ágil;
- Experiência de no mínimo 3 anos como pessoa desenvolvedora com foco em Web.

Você se destaca se tiver:

- Experiência com liderança técnica em startups de alto crescimento.

## Benefícios

Oferecemos uma lista completa de benefícios, incluindo:

- Salários competitivos, com a possibilidade de virar sócio da Gupy! 
- Plano odontológico e médico;
- Flexibilidade de horários;
- Vale refeição;
- Subsidiamos uma parceria com o Zenklub, uma plataforma de psicólogos e coaches online, para focarmos 100% no bem estar e saúde mental de cada Gupier aqui dentro!  
- Um clube inteiro de descontos para viagens, lazer, restaurantes e até mesmo aquela pós-graduação tão sonhada! 

Além disso tudo, incluímos também alguns benefícios diferentes e únicos:

- Trabalhar e trocar conhecimentos diários com um time referência no mercado;
- Participar deste time incrível, de uma cultura forte, que curte Karaokê e noites de luau em nossa varanda, com ou sem cerveja (você escolhe);
- Trabalhar em uma startup que preza pelo trabalho em equipe, diversidade e acredita que a diferença é um dos maiores fermentos para nosso crescimento;
- Ter contato com mentores internacionais, especialistas na sua área;
- Criar um produto que brilha os olhos de clientes e usuários;
- Aprender e crescer na jornada, sempre se divertindo;

## Contratação

CLT ou PJ

## Como se candidatar

Inscreva-se pelo link: https://bit.ly/gupy-tech-lead-110327

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by thalesf** [comment]
Boa noite, quais tecnologias vocês usam na gupy ?

**Comment by silvawillian** [comment]
Oi, @thalesf! Nós utilizamos principalmente AWS, Kubernetes, ElasticSearch, React e Node.js!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
