### ISSUE TITLE
[Remoto] Desenvolvedor Full Stack na Growth Tech

### ISSUE THREAD

**Issue by kennethgt** [frontendbr/vagas#3209]
## Nossa empresa

A Growth Tech é uma startup fundada há 4 anos e que trabalha desenvolvendo projetos inovadores de tecnologia da informação. Dentre as suas principais áreas de atuação estão: Soluções em Blockchain para negócios, aplicativos e softwares customizados sob demanda.

## Local

100% Remoto

## Requisitos

**Obrigatórios:**

- Node.js
- Express.js
- React.js

**Desejáveis:**

- Blockchain

## Contratação

- PJ

## Desafio

Uma empresa deseja realizar um monitoramento de outros grupos empresariais em um site X para analisar seus posts. Sua tarefa é criar uma simples API que captura apenas os usuários (http://jsonplaceholder.typicode.com/users) os quais a empresa em que trabalham fazem parte de um grupo e exiba seus posts (http://jsonplaceholder.typicode.com/posts) unido do nome do funcionário e sua empresa. Além disso criar uma tela para facilitar a leitura desses posts.

- O backend obrigatoriamente precisa ser realizado com Express.js.
- O frontend obrigatoriamente precisa ser realizado com React.js.
- Apesar de bem simples, o projeto precisa estar pronto para produção.
- Sinta-se à vontade para adicionar mais features e criar uma UI maneira!

## Como se canditatar

Assim que finalizado preencher o [formulário](https://forms.gle/ajYAbSVtrAJGUsLXA) e aguardar, boa sorte!

**Comment by gugagranato** [comment]
Existe a possibilidade de part-time?

**Comment by evertonProgramadorCriativo** [comment]
quantos dias , eu tenho para fazer o teste( Desafio)?

**Comment by kennethgt** [comment]
> Existe a possibilidade de part-time?

No momento não.



> quantos dias , eu tenho para fazer o teste( Desafio)?

O tempo que precisar, as vagas estão abertas com tempo indeterminado :)

**Comment by imxuaum** [comment]
@kennethgt Olá, conclui o teste descrito, poderei receber o feedback independente do resultado? agradeço desde já.

**Comment by kennethgt** [comment]
> @kennethgt Olá, conclui o teste descrito, poderei receber o feedback independente do resultado? agradeço desde já.

Enviado :)

**Comment by Diogo-Felipe** [comment]
O feedback para teste saí em aproximadamente quantos dias? Enviei o meu neste domingo dia 05/07

**Comment by kennethgt** [comment]
> O feedback para teste saí em aproximadamente quantos dias? Enviei o meu neste domingo dia 05/07

Enviado :) 

Os feedbacks são enviados para as pessoas que passam para próxima etapa, para os demais, caso queiram pode me avisar que eu envio. Só não vou passar uma data de quando você irá receber, pois temos muitos testes/entrevistas para realizar fora o trabalho do dia-a-dia, mas assim que possível eu envio :)

**Comment by Diogo-Felipe** [comment]
> > O feedback para teste saí em aproximadamente quantos dias? Enviei o meu neste domingo dia 05/07
> 
> Enviado :)
> 
> Os feedbacks são enviados para as pessoas que passam para próxima etapa, para os demais, caso queiram pode me avisar que eu envio. Só não vou passar uma data de quando você irá receber, pois temos muitos testes/entrevistas para realizar fora o trabalho do dia-a-dia, mas assim que possível eu envio :)

Muito agradecido 👍

**Comment by Leonardogrtt** [comment]
> > O feedback para teste saí em aproximadamente quantos dias? Enviei o meu neste domingo dia 05/07
> 
> Enviado :)
> 
> Os feedbacks são enviados para as pessoas que passam para próxima etapa, para os demais, caso queiram pode me avisar que eu envio. Só não vou passar uma data de quando você irá receber, pois temos muitos testes/entrevistas para realizar fora o trabalho do dia-a-dia, mas assim que possível eu envio :)

Enviei o formulário. Quando puderem dar um retorno fico agradecido, mesmo que não passe.
Valeu
