### ISSUE TITLE
[São Paulo] Front-end Dev -> Stone Pagamentos

### ISSUE THREAD

**Issue by hammerox** [frontendbr/vagas#321]
![Stone](https://vindi-blog.s3.amazonaws.com/wp-content/uploads/2015/07/stone-adquirentes.jpg)

# [VEM SER PARTE DA STONE ](http://www.stone.com.br/)
[http://www.stone.com.br/](http://www.stone.com.br/)

## Nossa empresa

A Stone está mudando o mercado de pagamentos através de uma abordagem única, focada na satisfação do lojista. Nascemos de uma startup há menos de 5 anos e hoje contamos com mais de 1200 funcionários. Crescendo em um ritmo frenético.

Acreditamos no potencial de gente boa e nos comprometemos com o desenvolvimento das nossas pessoas. Por isso, oferecemos desafios enormes e um ambiente horizontal e cooperativo, com os quais sabemos que vamos construir um negócio enorme e formar pessoas melhores.

Se você é inteligente, íntegro, e cheio de energia, você tem um lugar com a gente...

## Descrição da vaga

Estamos buscando talentos para trabalhar como Front-End Developer. 

## Local

R. Fidêncio Ramos, 308 - Vila Olimpia
São Paulo - SP
04551-010

## Benefícios

- Vale Refeição / Vale Alimentação
- Plano de saúde
- Horários flexíveis
- Hierarquia horizontalizada
- Cantina com mesa de sinuca, PlayStation4, Air Hockey...

## Requisitos

**Obrigatórios:**
- Programação Orientada a Objetos
- Ferramenta de controle de Versão (Git, Mercurial, SVN, etc...)
- Ter ao menos um projeto que você se orgulha
- Domínio em HTML, CSS e JavaScript
- Domínio de ao menos um JS Framework (React, AngularJS, Backbone, Ember, jQuery, etc...)
- Conhecimento em ferramentas auxiliares (Grunt, Gulp, NPM, Bower, etc...)
- Respirar Design e UX
- Consumo de APIs RESTful e atividades assíncronas

**Diferenciais:**
Um grande plus se você souber:  Web Apps e tecnologias Mobile

## Contratação

Estágio e Efetivo, CLT

## Como se candidatar

Envie seu CV para mcustodio@stone.com.br.
Estamos esperando por você!

**Comment by randhson** [comment]
Tem possibilidade de remoto ?

**Comment by hammerox** [comment]
Temos sim, mas não é nossa prioridade agora
Avisa no email que seu interesse é por trabalho remoto e a gente marca uma entrevista assim que puder

**Comment by eduardojmatos** [comment]
@hammerox consegue descrever o nível que estão procurando?

**Comment by rafael1995** [comment]
Cv enviado :)

**Comment by richmanzoli** [comment]
enviado (:

**Comment by hammerox** [comment]
@eduardojmatos Estamos abertos com relação ao nível técnico, já que o importante mesmo é ter personalidade como dev. Vale de júnior a sênior, desde que se tenha os requisitos mínimos.

**Comment by brunooomelo** [comment]
Enviado!

**Comment by eldemonstro** [comment]
Enviado!
