### ISSUE TITLE
[Remoto] Senior Front-end Developer na Dog & Pony Studios

### ISSUE THREAD

**Issue by CaioCosta** [frontendbr/vagas#3210]
## Nossa empresa

Somos uma agência digital com sede em Toronto, no Canadá. Atendemos principalmente grandes clientes corporativos do mercado financeiro do Canadá e Estados Unidos, trabalhando majoritariamente com sites institucionais.

## Descrição da vaga

Estamos procurando um Desenvolvedor Frontend Sênior para se juntar ao nosso time de desenvolvimento, que está em crescimento. Por termos um escritório completamente remoto, nosso objetivo é cultivar um ambiente cativante e aconchegante de trabalho. Nossos desenvolvedores seniores são pessoas altamente auto-motivadas e dedicadas a melhorias de performance dos websites e de fluxo de desenvolvimento. Eles trazem para o time um conhecimento sólido de JavaScript, HTML e CSS, além de compreender o impacto de suas decisões na experiência do usuário, na acessibilidade e na manutenção do código.

Como Desenvolvedor Frontend Sênior você deve ser proficiente na tomada de decisões criativas e otimizadas para os desafios apresentados pelos projetos. Você deve dominar o contexto do seu código, principalmente compreendendo os objetivos dos projetos, e tornar esse conhecimento em soluções de código convenientes e inteligentes.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 10 anos ou mais de experiência com desenvolvimento frontend;
- Excelentes habilidades de comunicação (em português e inglês por escrito e falado);
- Experiência com Vue.js;
- Experiência com REST API ou GraphQL;
- Experiência com JS moderno (ECMA5+);
- Experiência sólida em HTML5, CSS e SCSS;
- Larga experiência em desenvolvimento de sites institucionais;
- Ser capaz de identificar, perseguir e resolver a raiz dos problemas de maneira lógica e otimizada – sem gambiarras, sem soluções "mágicas";
- Conhecimentos sólidos em Git (merge flags, rebasing, workflows);
- Experiência em refatoração e otimização de código;
- Saber se comunicar com clareza e de maneira eficaz;
- Ser organizado e pontual;
- Auto-motivação e autonomia;
- Proatividade na resolução de problemas;
- Disponibilidade para trabalhar em horário fixo;
- Aptidão para trabalhar remoto (home office) e
- Olhar crítico nos detalhes.

**Desejáveis:**
- Experiência com trabalho remoto;
- Experiência com Tailwind CSS;
- Experiência com WordPress (incluindo ACF);
- Experiência com twig;
- Experiência sólida em JavaScript 1.5 (ECMA3);
- Experiência com conceitos de acessibilidade;
- Conhecimentos de conceitos OOCSS, ITCSS e BEM;
- Conhecimentos de PHP.

## Diferenciais da vaga

- 3 semanas de férias anuais + 2 semanas no período do Natal e ano novo
- Feriados nacionais pagos
- Pagamento em Dólar Canadense
- Ambiente criativo e aberto a críticas
- Time de desenvolvimento e de design conversam e elaboram soluções juntos

## Contratação

PJ a combinar

## Como se candidatar

Para se candidatar, o desenvolvedor deve preencher o [Formulário de Aplicação](https://forms.gle/yqdiWPT1iVoQFBo88) e aguardar resposta por e-mail. Caso seja pré-selecionado, o candidato receberá um e-mail para combinar uma ligação por Skype para entrevista, que é a segunda e última parte do processo.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias úteis após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by vncscoelho** [comment]
Esta é a segunda vez que participo, mas fico em dúvida se o formulário foi
enviado corretamente pois não recebi nenhuma confirmação ou feedback.
Agradeço se for possível retornar com confirmação.

**Comment by billaddison** [comment]
Boa tarde Vinicius, recebemos a sua inscrição sim. Estamos avaliando todos
os inscrições ainda essa semana.

Thanks,
Bill
