### ISSUE TITLE
[Recife] Front-end Developer na Justa Pagamentos

### ISSUE THREAD

**Issue by raisiqueira** [frontendbr/vagas#3213]
## Nossa empresa

Somos uma Fintech localizada em São Paulo e Recife com tecnologias que ajudam nossos clientes e revendedores a capturarem vendas em Cartões de Crédito / Débito além diso oferecermos uma plataforma de crédito para os varejistas que usam nossa plataforma, e para aqueles varejistas que optarem por vender online, temos uma solução de links de pagamentos e recorrência.

## Descrição da vaga

Você irá trabalhar em projetos com React e Angular (versões 5 e 9), um monorepo com base no nx.dev (Tooling para facilitar a vida do dev que trabalha com monorepos 😁), seu dia-a-dia será desenvolvendo novas features nos projetos atuais (e em novos projetos, claro) e fazendo manutenção nos projetos que estão em produção.

## Local

Escritório, Pernambuco, Recife, Pina (remoto durante a pandemia)

## Requisitos

**Obrigatórios:**
- 2 anos de experiência Angular/React
- 2 anos de experiência com TypeScript/JavaScript
- 2 anos de experiência com HTML / CSS

**Desejáveis:**
- conhecimentos em Java, Kotlin
- conhecimentos em Spring boot ou Play Framework

## Benefícios

- VR e VT;
- Plano de Saúde e Odontológico;
- Seguro de vida;
- Sem nenhum dress code.

**Diferenciais:**
- Você é o gestor do seu tempo
- Hierarquia horizontal
- Frigobar sempre cheio de cerveja :P
- Sala de jogos
- Varanda com vista para o Mar
- Computadores fornecido pela empresa
- Múltiplas telas
- Gente descolada, nerd e tabacuda
- Não temos Dress code (Só não vale vir pelado)
- Temos chuveiro para quem gosta de se exercitar (Por enquanto só temos sedentários, venha ser o primeiro a usar)

## Contratação

PJ a combinar

## Como se candidatar

Acessando o link [https://jobs.kenoby.com/justa](https://jobs.kenoby.com/justa)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: it-recife@justa.com.vc

#### Alocação
- Alocado
- Remoto (durante a pandemia)

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

**Comment by raisiqueira** [comment]
@felipefialho tira a tag SP, o alocado só para o office de Recife.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by raisiqueira** [comment]
@felipefialho está sim o/. Segue o link para mais detalhes da vaga https://jobs.kenoby.com/justa/job/desenvolvedor-front-end/5ee3bd55cdf3db0ddfc77b1c
