### ISSUE TITLE
[Morumbi/SP] Front-end (React) Developer Pleno na Confitec

### ISSUE THREAD

**Issue by DaiannaCs** [frontendbr/vagas#3215]
## Nossa empresa

Somos especialistas em softwares voltados ao mercado segurador. Estamos ajudando a impulsionar a transformação no setor de seguros no Brasil. Estamos presentes em São Paulo e Rio de Janeiro, duas das principais capitais do país.
Você fará parte de um time de desenvolvedores extremamente qualificado fortemente orientado a resultados e que não tem medo de inovar.
Você será parte vital no desenvolvimento da nova plataforma de um de nossos principais clientes, trabalhando com boas práticas de desenvolvimento em um ambiente dinâmico que incentiva a autonomia e o aprendizado constante.
Estamos crescendo e precisamos de pessoas que amem tecnologia e que sejam fascinadas por aprender!

## Descrição da vaga

Projeto em React.JS chamado Aviso Web por tempo indeterminado.

## Local

Estamos 100% home office até passar a situação que enfrentamos pelo COVID19. Após isso, retomaremos as atividades no nosso escritório [São Paulo], [Morumbi].

## Requisitos

**Obrigatórios:**
- React + Redux
- Sólidos conhecimentos em HTML e CSS
- JavaScript Avançado (ES6 + ES7)
- Familiaridade com APIs RESTFull

**Desejáveis:**
- GIT.
- Web API’s.
- AWS.
- SASS
- Metodologia BEM CSS

**Diferenciais:**
- Conhecimento em metodologia ágil.
- Material-UI

## Benefícios

- Plano de saúde.
- Plano odontológico;
- Vale Transporte;
- Vale-Refeição;
- PLR;
- Auxílio-creche;

**Diferenciais:**
- Incentivo a cursos e certificações;
- Sem dress code (Valorizamos a diversidade. Pode se vestir do seu jeito!);
- Flexibilidade de horários;
- Café da manhã toda sexta-feira;
- Comemoração mensal dos aniversariantes;
- Sala de Descompressão;
- Grupo de corrida e caminhada;
- Campeonatos de futebol;
- Day off no mês do seu aniversário;

## Contratação

CLT Full a combinar

## Como se candidatar

Por favor envie um e-mail para daianna.souza@confitec.com.br com seu CV anexado - enviar no assunto: Vaga ReactJS

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias úteis após cada processo.
E-mail para contato em caso de não haver resposta: curriculos@confitec.com.br

#### Nível
- Pleno

**Comment by DaiannaCs** [comment]
Olá @felipefialho esta oportunidade não é para o Rio de Janeiro. Por favor, retire a label "Rio de Janeiro" para não confundir na hora do cadastro. Muito obrigada!

**Comment by felipefialho** [comment]
Oi @DaiannaCs duas vagas muito parecidas foram abertas mudando só a senioridade, vou fechar essa e manter as duas nessa daqui (https://github.com/frontendbr/vagas/issues/3216) ok? 😊

**Comment by DaiannaCs** [comment]
Claro @felipefialho, muito obrigada =)
