### ISSUE TITLE
[Curitiba/Remote] Senior FullStack Python+Django na Visionnaire

### ISSUE THREAD

**Issue by raulbalestra** [frontendbr/vagas#3223]
Olá a todos,

Estamos a procura de um profissional SR. fora da Curva com conhecimento de:
 BE - Python+Django+GraphQL, Graphene.
 FE - React.js, Next.js, Apollo.

Business
a solution that helps small-middle sized manufacturing companies with product design and implementation. In other words, the customer comes to the lead with an idea, they help to design and create it, and even produce it, as they have lots of suppliers from China.

Requirements
The customer is looking to extend his current team of 2 engineers and 1 QA with 4 more engineers until the end of 2020.

The customer would like to start with 1 **senior full-stack** engineer with at least 5 years of experience as a software engineer. 

Tech stack: 

BE - Python, Django, GraphQL, Graphene.
FE - React.js, Next.js, Apollo.
**Experience working with manufacturing projects would be a plus.**
 

**UPPER-INTERMEDIATE English is mandatory.**

Duration: Duration: up to 6 months of full-time work.

Budget: 16k PJ

Como se candidatar:
Por favor envie um email para raul.balestra@visionnaire.com.br com seu CV anexado - enviar no assunto: **Senior FullStack Python+Django**

Alocação:
Alocado ou Remoto
Regime:
PJ
Nível:
Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
