### ISSUE TITLE
[Home-office] Front-end Developer (Pleno e Sênior) na ITeam

### ISSUE THREAD

**Issue by VivianeRHTI** [frontendbr/vagas#3224]
## Descrição da vaga

Experiência front-end de sistemas e aplicações web, utilizando tecnologias atuais e atendendo requisitos de responsividade e acessibilidade na web, implementando códigos que sejam escaláveis, fáceis de manter, eficientes e elegantes;
Definir boas práticas, mantendo-se atualizado nas novas tecnologias de front-end e capacitando outros desenvolvedores;
Participar de projetos de desenvolvimento de novos softwares, avaliando os protótipos entregues pelo designer, planejando e implementando a estrutura e componentes da interface, utilizando para isso o framework de javascript React;
Participar de projetos de customização de softwares já existentes utilizando um framework interno, AngularJS ou React;

## Local

100% Home-office (Horário comercial)

## Benefícios

- Plano de saúde
- Seguro de vida
- VR ou VA

## Requisitos

**Obrigatórios:**
Experiência em JavaScript e no framework ReactJs.
Conhecimentos em Gerenciadores de estados, incluindo Redux e seus padrões de arquitetura; 
HTML, CSS, controle de versão (Git);
Conhecimento avançados em ES6;
Bibliotecas Webpack, Gulp ou Grunt; 
Técnicas e práticas de Clean Code; 
Experiência em equipes dinâmicas e metodologias de desenvolvimento ágeis; 
Experiência em testes unitários automatizados para a aplicação (Jest, Enzyme e etc).
Desenvolvimento de SPA (Single Page Application) utilizando React.

## Contratação

CLT 

## Nossa empresa

Há mais de 15 anos presente no mercado, a ITeam oferece o comprometimento com o cliente.
Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 
O relacionamento da ITeam é baseado no amplo comprometimento com os valores e objetivos dos nossos Clientes, fornecendo soluções e serviços de TI que contribuam para a realização de seus objetivos.

## Como se candidatar

Envie um e-mail para viviane.pereira@iteam.inf.br com seu currículo atualizado e pretensão salarial - enviar no assunto: Vaga Front-end - React 

## Labels

- 🏢 Horário comercial
- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ CLT

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
