### ISSUE TITLE
[Home-office] Front-end Developer - Temporário na ITeam

### ISSUE THREAD

**Issue by VivianeRHTI** [frontendbr/vagas#3225]
## Descrição da vaga

Realizar a manutenção e melhoria na plataforma e-commerce.
Ajudar desenvolvedores back-end no código e solução de problemas.

## Local

Remoto

## Requisitos

**Obrigatórios:**
Experiência em desenvolvimento Web requeridos.
Experiência em JavaScript; ES6; CSS; Diagramação e orientação a objetos.

## Tempo de projeto

Previsão de término de projeto: 31/07/2020 (com possibilidade de extensão)

## Regime

CLT ou PJ

## Nossa empresa

Há mais de 15 anos presente no mercado, a ITeam oferece o comprometimento com o cliente.
Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 
O relacionamento da ITeam é baseado no amplo comprometimento com os valores e objetivos dos nossos Clientes, fornecendo soluções e serviços de TI que contribuam para a realização de seus objetivos.

## Como se candidatar

Envie um e-mail para viviane.pereira@iteam.inf.br com seu currículo atualizado e pretensão salarial - enviar no assunto: Vaga Front-end - Temporário

## Labels

- 🏢 Horário comercial
- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ CLT ou PJ

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
