### ISSUE TITLE
[Remoto] React Developer na Croct

### ISSUE THREAD

**Issue by amorimjuliana** [frontendbr/vagas#3227]
![alt text](https://media-exp1.licdn.com/dms/image/C4E22AQEaww5NgzOlaQ/feedshare-shrink_800/0?e=1595462400&v=beta&t=_goiHP5lciH8E8_zqHP3Bxdo0GcVRIBJTBOKN0n49gs "Croct")

## Nossa empresa

**Prazer, somos o Time de Tecnologia da [Croct](https://croct.com/) (:**

A Croct é uma plataforma SaaS de personalização que ajuda empresas a criarem jornadas online que são únicas para cada usuário. Nós entendemos o perfil do cliente e suas necessidades para oferecer uma experiência excepcional no mundo online. Tudo isso de forma simples, rápida e conectada.

Aqui na Croct, prezamos pela diversidade, liberdade e autonomia. Liberdade para escolher seus horários, suas stacks, a forma como você vai trabalhar e mais importante, liberdade de ser quem você é. Somos fascinados pela troca de conhecimento e acreditamos que sozinhos nunca chegaremos a lugar nenhum. 

Buscamos inteligência, energia e integridade. E em troca, oferecemos autonomia, liberdade e flexibilidade.

**Venha fazer parte do nosso time!**

## Descrição da vaga

**Código excelente começa com pessoas incríveis. 🤓**

Se você é um desenvolvedor React fora da curva buscando uma startup com potencial global para trabalhar remotamente, você vai gostar do que temos para você.

Como um desenvolvedor front-end, você será desafiado a com um bom design e aprender a melhor forma de executar qualquer tarefa. Você vai ter contato direto com performance, otimização e escalabilidade de soluções, trabalhando diretamente com os fundadores da empresa. Se você busca uma oportunidade de crescimento com a possibilidade de liderar um time de tecnologia, essa é a oportunidade para você.

**Seu papel como desenvolvedor front-end:**
- Trabalhar lado a lado com os founders, garantindo a entrega de projetos desafiadores de grande impacto no negócio;
- Facilitar o planejamento de projetos para atender às necessidades de negócio atuais e futuros, antecipando e removendo barreiras;
- Colaborar com demais área da empresa para entendimento dos problemas, análise de oportunidades e busca de soluções;
- Desenvolver e implementar a área logada da plataforma, onde os clientes gerenciam suas features e campanhas de personalização.
- Documentar e mapear os processos relacionados à área.

## Local

A princípio, remoto. Possibilidade de trabalho em escritório em São Paulo em 2021.

## Requisitos

**Obrigatórios:**
- Forte experiência com HTML5, CSS3 e LESS/SASS;
- Proficiência em Javascript e Typescript;
- Experiência em React;
- Experiência com ferramentas de versionamento (GitHub);
- Saber lidar com gerenciador de pacotes como NPM.

**Desejáveis:**
- Forte experiência em testes unitários, integração e end-to-end.

**Diferenciais:**
- Experiência com projetos opensource;
- Conhecimento de boas práticas de qualidade como TDD e BDD;
- Conhecimento de bibliotecas/frameworks/ferramentas populares para frontend: Redux, Storybook, Babel e Eslint;
- Expeciência com Continuous Integration.

## Diferenciais:
- startup com potencial global e planos de internacionalização em 2021
- flexibilidade para trabalhar com o stack que desejar
- possibilidade de liderar um time de tecnologia
- trabalho lado a lado dos founders
- liberdade para trabalhar e contribuir com projetos opensource

## Contratação

PJ a combinar

## Como se candidatar

A primeira etapa do processo consiste em um teste de raciocínio lógico, disponível [neste link](https://forms.gle/DUjj27r6h6iPkvX29).

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: jobs@croct.com

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
