### ISSUE TITLE
[Remoto ou São Paulo/SP] Front-end Developer na Vizir

### ISSUE THREAD

**Issue by apantaliao** [frontendbr/vagas#3229]
## Nossa empresa

A Vizir tem 10 anos de vida, trabalhamos desenvolvendo projetos sob medida para nossos clientes e gostamos que as pessoas fiquem por bastante tempo conosco.

## Descrição da vaga

- A vaga é para pessoas com experiência em programação. Por isso colocamos pleno / sênior. Mas dentro do nosso time, no dia-a-dia, não usamos muito esta terminologia. 
- No cenário de pandemia, estamos todos remotos. Mas nosso escritório está no centro de SP, na República. Temos vagas para que no futuro sejam remotos ou presenciais. 
- Temos vagas abertas em projetos mais front-end, tanto React como ReactNative. Mas embora seja mais para o front-end, gostamos que seja um front sem medo de API, do back-end. Mais do que conhecimento específico em uma plataforma queremos que seja uma pessoa que goste de programar, de fazer testes unitários e de fazer software bem feito!
- Temos projetos  em React, ReactNative e projetos que envolvam ambas as tecnologias. 
 
Para conhecer mais sobre a vaga e[ um pouco da Vizir](https://vizir.com.br/2019/08/venha-fazer-parte-da-vizir-estamos-contratando/).

## Local

No momento e por mais um bom tempo ficaremos 100% remotos. Nosso escritório fica no centro de SP, mas cerca de 30% do nosso time de 108 pessoas já trabalhava remoto antes da pandemia. 

## Requisitos

- Conhecer bem uma linguagem de programação, boa lógica e orientação a objetos.
- Estar a fim de aprender. 
- Ser comprometido em entregar projetos com qualidade.
- Curtir entregar um front bonito e bem desenvolvido hehe... 
- Bons conhecimentos de React ou ReactNative são importantes, mas se tiver mais experiência com outros frameworks e quiser trabalhar com React, é bem-vindo.

**Desejáveis:**
- Ter experiência com práticas ágeis.
- Bons conhecimentos de teste

## Benefícios
- Vale Refeição pago em dinheiro.
- Plano de saúde SulAmérica, com acesso a uma boa rede de hospitais e quarto individual;
- Plano odontológico Odontoprev;
- Seguro de Vida no valor de R$ 60.000,00.
- Ambiente bacana para trabalhar e auxílio a montar seu home office (um computador para chamar de seu e auxílio cadeira). 

## Contratação
CLT ou PJ, como preferir.

## Como se candidatar
[Pode se candidatar no link](https://recruiterflow.com/vizir/jobs/12?source=FrontEndBR) 

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: queroentrar@vizir.com.br

## Labels
- Remoto
- Presencial

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by jhefflg** [comment]
Full remoto ou só durante a quarentena?
Achei bem interessante a oportunidade.

**Comment by apantaliao** [comment]
Temos os dois cenários....
