### ISSUE TITLE
[São Paulo] Desenvolvedor(a) Front-End Pleno na Lendico

### ISSUE THREAD

**Issue by camilaibs** [frontendbr/vagas#323]
## Descrição da vaga

Procuramos uma (um) profissional proativo, capaz de trabalhar e interagir com uma equipe multidisciplinar (backend, frontend, gerente de produto e designers), alinhado às práticas do nosso time, com foco em resultados, testes e criação de produtos referência no mercado.

## Local

Escritório, Rua Pais Leme, 524 - Pinheiros, São Paulo - SP, Brasil - CEP: 05424-010 Brasil

## Requisitos

**Obrigatórios:**
- Ser capaz de colaborar com o time quanto às melhores práticas de frontend do mercado;
- Ser capaz de propor otimizações de performance;
- Ser responsável pelo desenvolvimento frontend das novas funcionalidades do produto.

**Desejáveis:**

- 2 anos de experiência com Javascript;
- Saber manipular o DOM sem usar jQuery;
- Experiência em pelo menos um framework/biblioteca moderna de Javascript (React, Angular, Vue etc);
- Saber boas práticas para otimização de páginas web focado em experiência de usuário;
- Comprometimento em desenvolver código testável e de fácil manutenção.
 
**Diferenciais:**
- Projetos opensource;
- Participação ativa na comunidade
- Ter trabalhado em um projeto web utilizando React com uso do Redux;
- Experiência com desenvolvimento backend (Python/Flask ou outras linguagens, API’s REST);

## Benefícios

- Horário flexível;
- Frutas frescas;
- Máquina de café expresso, com leite, chocolate e cappuccino;
- Vale Refeição (valor de R$ 27,00 por dia, sempre comprado pelos dias úteis);
- Vale Transporte (comprado perante a necessidade do empregado, desconto de 6% em folha limitado ao valor da compra);
- Assistência odontológica (há 3 planos, cada um com um tipo de cobertura e valores, e é descontado em folha);
- Assistência médica, ambos pela Notredame e apartamento;
- Seguro de vida;
- Parceria com o SESC.

## Contratação

CLT a combinar.

## Nossa empresa

A Lendico, é uma fintech que está com desafios técnicos para manter seu forte crescimento.
Em pouco mais de 1 ano e meio após o lançamento do produto, já emprestamos mais de 60 milhões de reais aos nossos clientes do Brasil.
Pertence ao grupo Rocket Internet, foi fundada na Alemanha, em 2013.
Possui operação em cinco países. A empresa chegou ao Brasil em julho de 2015 para mudar o mercado de crédito nacional, recebendo solicitações de mais de 450 cidades de todo o Brasil.

## Como se candidatar

Por favor envie um email para cleiton.gomes@lendico.com.br e camila.belo@lendico.com.br com seu CV anexado - enviar no assunto: Vaga Front-End

**Comment by brunooomelo** [comment]
Enviado ;)

**Comment by mtmr0x** [comment]
@camilaibs a vaga continua aberta?

**Comment by camilaibs** [comment]
@mtmr0x a vaga continua aberta sim, posso manter esta issue aberta?

**Comment by LFeh** [comment]
Pode sim @camilaibs
