### ISSUE TITLE
[São Paulo / Remoto] Fullstack VueJS+Java Developer na Fator3/Surgemap

### ISSUE THREAD

**Issue by rafa-fator3** [frontendbr/vagas#3230]
## Nossa empresa

A Fator3 é uma Venture Builder e a Surgemap é uma startup healthtech early stage.

## Descrição da vaga

Projeto VueJS + Java na área da saúde. MVP já está desenvolvido e implantado em clientes.

## Local

Remoto, a princípio.

## Requisitos

**Obrigatórios:**
- VueJS
- Java

**Desejáveis:**
- DevOps

**Diferenciais:**
- Experiência como líder de projetos

## Contratação

PJ a combinar

## Como se candidatar

Preencher formulário em www.fator3.com.br/vagas

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias para os candidatos selecionados para entrevista.

## Labels

Remoto
Pleno
Fullstack
VueJS
Java
Startup
Healthtech

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by diogomoretti** [comment]
Olá, @rafa-fator3? O que significa `Remoto, a princípio`?

**Comment by rafa-fator3** [comment]
Olá! A vaga é para remoto no momento. Se a startup decolar talvez tenham um
escritório em SP no futuro.

Em seg., 22 de jun. de 2020 às 13:54, Diogo Moretti <
notifications@github.com> escreveu:

**Comment by diogomoretti** [comment]
E quando tiver um escritório a pessoa precisará trabalhar alocada?

**Comment by rafa-fator3** [comment]
Não. Podemos deixa como remoto mesmo na descrição da vaga.

Em seg., 22 de jun. de 2020 às 14:10, Diogo Moretti <
notifications@github.com> escreveu:
