### ISSUE TITLE
[Curitiba] Front-end Developer / Vue/React na Easy2Recruit

### ISSUE THREAD

**Issue by MariEasy2Recruit** [frontendbr/vagas#3234]
Nosso cliente é uma start-up que atua com a análise de dados e comportamento do consumidor. Irá atuar de forma remora durante a Pandemia.

Responsabilidades e atribuições
• Desenvolvimento de aplicativos WEB;
• Manutenção e desenvolvimento de novas funcionalidades nas aplicações;
• Realizar integração com as APIs;
• Participar do levantamento de requisitos para o desenvolvimento de produtos

Experiência/Conhecimento
• Desenvolvimento de aplicações WEB utilizando as seguintes tecnologias:
• HTML5 e CSS3;
• Javascript ES6;
• Diferencial: Vue.js2 e/ou React;.

Interessados encaminhar currículo com pretensão salarial para mariana@recrutamentofacil.com

**Comment by devartwa** [comment]
Olá, bom dia. Após a pandemia, o desenvolvedor deverá ficar alocado em qual cidade?

**Comment by MariEasy2Recruit** [comment]
> Olá, bom dia. Após a pandemia, o desenvolvedor deverá ficar alocado em qual cidade?

Curitiba.

**Comment by devartwa** [comment]
> > Olá, bom dia. Após a pandemia, o desenvolvedor deverá ficar alocado em qual cidade?
> 
> Curitiba.

Eu sou do interior de SP, mas tenho disponibilidade para me mudar. Em relação a pretensão salarial, eu poderia enviar sem? (Por conta de não saber o custo médio de vida na cidade)

**Comment by MariEasy2Recruit** [comment]
Pode sim.

Abraço,


[image: Easy2Recruit.com]



*Mariana Dietzsch Ricetti*
Headhunter | Easy2Recruit.com
phone: +55 41 9 <+55%2041%209%209684%202279> 9875 6458
site: easy2recruit.com
e-mail: *ma*riana@ <SUZI@Easy2Recruit.com.br>Easy2Recruit.com.br
<mariana@Easy2Recruit.com.br>


Em ter., 23 de jun. de 2020 às 08:59, Arthur Bueno <notifications@github.com>
escreveu:
