### ISSUE TITLE
[São Paulo] Front-end Developer no Decoradornet

### ISSUE THREAD

**Issue by Vipperland** [frontendbr/vagas#3238]
##Nossa empresa

Somos uma startup de projeto de decorador online.

## Descrição da vaga

Procuramos um desenvolvedor para cuidar do desenvolvimento e da manutenção do nosso Front-End.

## Local

Presencial no período da tarde em alguns dias da semana, a combinar.
Cidade Jardim, São Paulo, SP
Próximo a Estação de trem Cidade Jardim.

## Requisitos

**Obrigatórios:**

- Conhecimento em Javascript (pleno ou avançado)
- Conhecimento em HTML e CSS (avançado)
- Inglês (intermediário ou avançado)

**Desejáveis:**

- Conhecer a plataforma de desenvolvimento HAXE.
- Ser prático na solução de problemas.

## Benefícios

- Ajuda de Custo

**Diferenciais:**

- Não precisar ir no escritório nas Sextas Feiras :)

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para rafael@decoradornet.com.br com seu CV anexado - enviar no assunto: [Vaga] Desenvolvedor Fron-End

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 24 horas após cada processo.
E-mail para contato em caso de não haver resposta: rafael@decoradornet.com.br

## Processo Seletivo

Conversa online e teste técnico.

## Labels
Javascript, html, css, haxe

#### Alocação
 - Alocado
 - Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Senior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
