### ISSUE TITLE
[São Paulo] Front-end ReactJS Developer na Pixter

### ISSUE THREAD

**Issue by RecruiterFMonteiro** [frontendbr/vagas#3239]
## Nossa empresa

A Pixter é uma boutique de software focada na transformação digital de clientes de grande porte. Com operação em 3 países, mais de 70 colaboradores somente no Brasil, buscamos profissionais qualificados para grandes desafios.

## Descrição da vaga

Procuramos um(a) Desenvolvedor(a) Front-end Reactjs, nível Sênior, com experiência sólida e excelente nível de conhecimento.

## Local

São Paulo - Inicialmente Remoto.

## Requisitos

**Obrigatórios:**
HTML: padronização, acessibilidade, mobile patterns.
CSS hierárquico e de fácil manutenção.
Desenvolvimento voltado à componentização.
Domínio em Javascript nativo (ES6>).
Domínio em ReactJS e outros frameworks single-page.
Noções básicas de ferramentas para controle de versão.
Experiência com Gulp, Grunt ou Webpack.
**Redux (Imprescindível)**
GraphQL
Next JS
TDD (com React Testing Library)

**Desejáveis:**
VueJS;
NodeJS;

## Contratação

PJ - Remuneração a combinar, se preferir nos envie sua pretensão junto com o CV.

## Como se candidatar

Por favor envie um email para danilo.vieira@pixter.com.br com seu CV anexo ou perfil do LinkedIn atualizado - enviar no assunto: Reactjs SENIOR

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by diogomoretti** [comment]
@RecruiterFMonteiro o que significa o "inicialmente remoto"? Seria somente durante a pandemia? Se sim, após esse período a pessoa teria que ir presencialmente no escritório?

**Comment by RecruiterFMonteiro** [comment]
Olá @diogomoretti , durante a pandemia.
Não temos data prevista para retomada presencial.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
