### ISSUE TITLE
[Remoto] Front-End Developer Vue.js

### ISSUE THREAD

**Issue by igortrinidad** [frontendbr/vagas#324]
# Descrição da vaga

A We-Planner procura Front-End Developer Junior para atuar no desenvolvimento das aplicações de gestão da empresa.

Procuramos pessoas apaixonadas por tecnologia e inovação, gostem de desafios e que queiram transformar papel em tela (analógico para o digital).

Criamos um produto para gestão de empresas de eventos e nosso objetivo é quebrar o paradigma deste setor que ainda é muito analógico e avesso à mudanças.

Nossa aplicação é SPA em Vue.js + Laravel BackEnd, portanto ter experiência com os fw's é obrigatório.

## Local

Remoto
Segunda à sexta
08:30 às 12:30 | 13:30 às 18:30

## Requisitos

**Obrigatórios:**
Domínio em VueJS;
Domínio de HTML, CSS, JS (não é Jquery);
Conhecimento em Boostrap;
Experiência com versionamento GIT/SVN, preferencialmente GIT;
Conhecimentos de SASS, LESS ou outro Pré-Processador de CSS;
Integrações com APIs REST e Webservices;
Style guides;
Padrões de Projeto;
Conhecimento de automatizador de tarefas (Gulp, Webpack);
Experiencia com Design Responsivo (mobile first);

**Diferenciais:**
Experiência em Metodologias ágeis;
Conhecimento de UI/UX;
Conhecimento de versões de JS, ES5, ES2015, ES6;
Conhecimento de BackEnd Laravel-PHP (para melhor iteração entre as partes);
Saber manusear algum software de edição de imagem;
Conhecimentos de Perfomance;
Conhecimento de padrões de desenvolvimento de CSS (BEM, OOCSS, SMACSS, Atomic CSS);

## Contratação

CLT
Salário: R$2.000,00

## Como se candidatar

Por favor envie um email para contato@we-planner.com com seu CV anexado e profile GitHub - enviar no assunto: Vaga Front-End Developer

**Comment by AlisonVilela** [comment]
Sênior por R$2.000,00 brincadeira né

**Comment by joaoeffting** [comment]
@AlisonVilela Acho que não mudaram o label só. Na descrição da vaga fala que é pra Junior

**Comment by AlisonVilela** [comment]
aaah, menos mal =P

**Comment by AlisonVilela** [comment]
Mas na minha opinião é muito conhecimento exigido para um Junior

**Comment by kavalcante** [comment]
Honestamente para mim isso é a descrição de um pleno. Um junior ter domínio de Rest e Vue.js não é pouca coisa.

**Comment by igortrinidad** [comment]
Entendemos perfeitamente a colocação de vocês, mas sabemos de nossas limitações... Somos uma empresa pequenininha em busca de espaço no mercado, sem fundos, sem aceleradoras... Apenas um punhado de boas idéias, força de vontade e muito suor, nada de Startup Dream... Um produto feito na unha, mas que ta super legal... Realmente pode parecer muito, mas o desenvolvedor em empresa pequena geralmente terá contato com diversas skills, é um pouco diferente de empresa consolidada e grande que as vezes consegue separar bem as skills, os concerns... Infelizmente ainda não é nosso caso, mas esperamos chegar lá! Chegar lá, tanto em oferecer melhores condições, quanto em conseguirmos ter profissionais focados, quem sabe pleno's, sênior's, CEO's, CTO's, CMO's e por ai vai... Mas um passo de cada vez... Se alguém conseguir mudar a label, seria ótimo e no mais peço a compreensão de vocês, quem sabe um dia vocês não se candidatam à vagas mais interessantes por aqui...? ;)

**Comment by LFeh** [comment]
Mudei a label, hehe

**Comment by igortrinidad** [comment]
Esta vaga foi preenchida através do repositório.
Dev contratado: André Brandão

Obrigado a todos os interessados e boa sorte!
