### ISSUE TITLE
[Remoto] Magento Developer na Signativa

### ISSUE THREAD

**Issue by startecjobs** [frontendbr/vagas#3241]
## Nossa empresa

Fundada em 2005 na cidade de Blumenau/SC, a Signativa é uma das principais especialistas na plataforma de e-commerce Magento do Brasil. Com 15 anos de história e experiência no mercado da tecnologia, a Signativa é uma empresa jovem de espírito e essa característica reflete diretamente no seu perfil. 

## Descrição da vaga

O talento contratado terá como principal desafio atuar no desenvolvimento de uma plataforma SaaS utilizando Magento 2.

## Local

Remoto

## Requisitos

**Obrigatórios:**
• Conhecimentos em Magento 2

**Desejáveis:**
• PHP Avançado
• JavaScript
• CSS
• API Rest

## Benefícios

• Remuneração de R$ 1.500,00 a R$ 3.000,00

## Contratação

CLT ou PJ

## Como se candidatar

Preencha as informações do formulário no link a seguir: https://bit.ly/Inscrição-Signativa. Fique atento(a) à sua caixa de entrada, enviaremos todas as fases do processo por lá.

## Tempo médio de feedbacks

Enviamos os feedbacks após o término do processo seletivo da vaga em questão.

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Júnior

**Comment by evertonProgramadorCriativo** [comment]
Poderia me passar um teste para eu concorrer  a sua vaga,  meu email evertonprogramadorcriativo@gmail.com

**Comment by startecjobs** [comment]
> Poderia me passar um teste para eu concorrer a sua vaga, meu email [evertonprogramadorcriativo@gmail.com](mailto:evertonprogramadorcriativo@gmail.com)

Olá, Everton. Todas as informações da vaga e da empresa estão aqui: https://bit.ly/DevMagento-Signativa

Enviaremos todas as etapas do processo por email. Fique ligado na sua caixa de entrada. Forte abraço! :)
