### ISSUE TITLE
[São Paulo - Zona Sul] Junior Front-end Developer na ECS

### ISSUE THREAD

**Issue by stellamonfils-rh** [frontendbr/vagas#3242]
**[São Paulo] Junior Front-End Developer na ECS** 

## Requisitos: 
- Experiência em Git;
- Experiência com ferramentas de Build e Deply 
- Experiência em Desenvolvimento Web (Angular4+, HTML5,CSS). 
- Habilidade em desenvolvimento orientado a objeto. 

**Desejáveis:**

- Conhecimentos em Typescript.
- Experiência com MicroFront-ends; 

## Benefícios
- Plano de saúde (SulAmérica - com coparticipação) 
- Assistência Odontológica
- Seguro de vida
- VR de R$ 22,00/dia 
- Vale Transporte 
- Seguro de Vida 

**Diferenciais:**
- Ambiente colaborativo 

## Contratação

CLT 

## Como se candidatar

Por favor envie um email para stella.monfils@roberthalf.com.br com seu CV anexado - enviar no assunto: Vaga ECS Front-end 

## Tempo médio de feedbacks: 5 dias 

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: stella.monfils@roberthalf.com.br

#### Regime
- CL

#### Nível
- Júnior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by barcellos-pedro** [comment]
E-mail enviado, obrigado!
