### ISSUE TITLE
[Remoto] Front-end Developer na Quoretech

### ISSUE THREAD

**Issue by samuelmesq** [frontendbr/vagas#3244]
## Quoretech

Estamos desenvolvendo a primeira plataforma centrada no coração do mundo, alavancando o enorme potencial combinado da IOT, Telemetria e Inteligência Artificial, para eliminar as doenças cardiovasculares.

Saiba mais em [Quoretech Website](http://www.quore.tech)

## Descrição da vaga

Precisamos de pessoas que possam contribuir com melhorias tanto em performance e qualidade de código, escrevendo testes unitários e de integração, reescrevendo componentes e/ou estilos. 

Estamos interessados na contribuição para o projeto, independente do seu nível profissional. 

## Local
100% Remoto

## Requisitos

**Obrigatórios:**
- experiência com desenvolvimento front-end;

**Desejáveis:**
- conhecimento de Typescript e Preact;
- conhecimento em TDD (Jest / Cypress);

**Diferenciais:**
- participou de projetos open-source;
- facilidade em comunicação assíncrona; 

## Benefícios

- ajudar a salvar vidas;
- possibilidade de options;

**Diferenciais:**

- participação no desenvolvimento de novas tecnologias;
- integrar um time experiente em um projeto inovador e global;

## Contratação

PJ a combinar

## Como se candidatar

- enviar email para samuel.mesquita@quore.tech com apresentação e links de projetos;

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.
E-mail para contato em caso de não haver resposta: ricardo.iguchi@quore.tech.

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by thalesf** [comment]
Há possibilidade de part-time job ?

**Comment by samuelmesq** [comment]
oi @thalesf, Sim.

Nosso projeto funciona em um modelo de **open-source bounty**. Estamos abrindo o código fonte da plataforma web e buscando contribuições da comunidade.

**Comment by arrudacaio** [comment]
Enviado!

**Comment by samuelmesq** [comment]
Obrigado a todos que entraram em contato.

Nosso projeto esta' em https://gitlab.com/quoretech/web, quem tiver interesse em participar da construção da plataforma será bem vindo.
