### ISSUE TITLE
[São Paulo-SP] Tech Lead na startup Colab

### ISSUE THREAD

**Issue by rodriguesvini** [frontendbr/vagas#3245]
### Empresa:
O Colab é uma startup que nasceu para ajudar os cidadãos a ter voz! Através de uma plataforma interativa, o Colab conecta cidadãos diretamente à construção de cidades melhores. Para os usuários, o aplicativo permite identificar e fiscalizar problemas, avaliar serviços e espaços públicos e participar de tomadas de decisão. Para o poder público, o Colab torna o atendimento mais transparente, a solução dos problemas mais eficiente e a administração das cidades mais inclusiva e participativa. O propósito do Colab é democratizar o protagonismo urbano, permitindo que todos possam praticar verdadeiramente a cidadania, da palma de sua mão, de onde estiver!

### Desafio:
O Tech Lead no Colab será o(a) responsável por liderar a equipe (desde garantir o desempenho, serviço e melhorias técnicas, como também proporcionar o desenvolvimento da área e do time). A visão holística do negócio será fundamental, uma vez que como Tech Lead você terá uma participação estratégica e contato direto com os stakeholders da empresa. A mão na massa também não ficará de lado, então excelência técnica como desenvolvedor(a) é o que buscamos, considerando que servirá de referência para outras pessoas. É uma oportunidade de protagonizar melhorias, criar e crescer junto com uma equipe colaborativa, diversa, jovem e dinâmica! 

### Requisitos:
• Experiência com desenho e arquitetura de soluções;
• Domínio das tecnologias: React e  NodeJs;
• Visão estratégica de negócio, conhecimento de metodologias ágeis e habilidade de gestão de times;
• Experiência com ambiente Cloud (AWS é desejável);
• Conhecimento de Bancos de Dados Relacionais.

### Diferenciais: 
• Experiência em empresas de produto ou em empresas de responsabilidade social.
• Experiência com tecnologias mobile para desenvolvimento nativo.

### Contratação:
A contratação será feita em regime PJ, alocado na sede em São Paulo. A remuneração é competitiva, no entanto é confidencial. Há possibilidade de stock options! 

**Para conhecer mais da oportunidade e participar do processo com a gente, é só acessar: https://bit.ly/2A59G8C**

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
