### ISSUE TITLE
[São Paulo] Front-end React Developer na SupplyLabs

### ISSUE THREAD

**Issue by godois** [frontendbr/vagas#3247]
## Nossa empresa

A SupplyLabs foi criada em Julho de 2019 com o propósito de entregar uma experiência 100% para gestão de cadeia de suprimentos. 
Nossa plataforma é responsável por toda gestão de compliance e sustentabilidade de uma cadeia de fornecimento.
Estamos em um momento de plena expansão com grandes possibilidades de crescimento para os integrantes do time.
Visite-nos em https://supplylabs.com.br/ ou https://www.linkedin.com/company/supplylabsbr/ 

## Descrição da vaga

Estamos à procura de uma pessoa para integrar o time de frontend, que irá contribuir para o desenvolvimento de novas funcionalidades da nossa plataforma.

Você será responsável por:

Codificar o frontend será sua principal responsabilidade, onde terá total liberdade para aplicar as suas escolhas.
Ajudar na prototipação de produto.
Participar de discussões para levantamento de hipóteses de solução, nos ajudando a pensar novos produtos e novos módulos.
Participar ativamente de decisões de tecnologias, infraestrutura, etc.

## Local

Remoto full time

## Requisitos

- Ter trabalhado em ao menos um projeto utilizando ReactJS, e que seja um produto digital. Isso é imprescindível!
- Ser fluente com tecnologias como HTML, CSS e Javascript.
- Saiba consumir APIs REST de forma otimizada. 
- Saiba versionar código e interagir com GIT.
- Que tenha noções de testes automatizados em aplicativos web.
- Gostar de trabalhar em grupo, ter empatia e humildade para liderar discussões.
- Ser curioso e estudioso.
- Ter lado analítico, preocupado com a ciência por trás das decisões.
- Ter atuado em outras startups é um diferencial.

**Diferenciais:**
- Ter trabalhado com consumo de APIs GraphQL

## Benefícios

- Ambiente descontraído de trabalho e em plena expansão;
- Trabalhar com uma arquitetura 100% cloud, com tecnologias de ponta como React , Golang, Graphql, Microserviços e um montão de dados;

Por favor envie um email para rh@supplylabs.com.br com seu CV anexado - enviar no assunto: Vaga ReactJS

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: marcio@supplylabs.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

**Comment by devartwa** [comment]
Amigo, bom dia. Não querendo ser 'arrogante', mas acredito que a tag júnior não se encaixa na vaga pela questão de ser referencia pro time de front. Está correto mesmo?

**Comment by godois** [comment]
Olá @devartwa, obrigado pela consideração. Eu corrigi o texto, pois foi inadequado para essa vaga. Estamos também considerando perfis junior pois dependendo do perfil do candidato, para nós é interessante formá-lo.
Obrigado!

**Comment by devartwa** [comment]
> Olá @devartwa, obrigado pela consideração. Eu corrigi o texto, pois foi inadequado para essa vaga. Estamos também considerando perfis junior pois dependendo do perfil do candidato, para nós é interessante formá-lo.
> Obrigado!

Maravilha @godois. Eu acabei comentando por interesse nada vaga, mas como sou júnior, dificilmente conseguiria ser 'referencia' pra equipe.

**Comment by jjairojr** [comment]
@godois enviarei meu currículo amigo, me interessei bastante

**Comment by jjairojr** [comment]
Relatando a minha experiência de "processo seletivo" para essa vaga, a resposta que ele deu para o @devartwa não condiz com o email que me foi mandado "Estamos procurando alguém com mais experiência". Entretanto, não me foi passado um teste/avaliação no qual poderiam realmente avaliar isso, me disseram em seguida que era imprescindível ter um projeto React com GraphQL, eu realizei a arquitetura de um sistema aonde trabalho utilizando essas mesmas tecnologias e isso não foi sequer perguntado, apenas deduziram que eu não tinha feito (???). Não quero prejudicar as pessoas a se candidatar pra vaga muito menos a empresa, mas achei importante comentar minha experiência.

**Comment by godois** [comment]
Obrigado @jjairojr pelo relato da sua experiência e ressalto o compromisso da SupplyLabs em conduzir o processo com os candidatos com a maior transparência possível. Nesse momento estamos priorizando candidatos que possuem ao menos uma atuação em um projeto real. De acordo com o seu cv compartilhado, não conseguimos identificar a experiência relatada acima, o que nos levou a declinar o processo. Devido ao alto número de candidatos, não é possível aplicar teste à todos, então, quando identificamos o fit da vaga com o candidato pelo CV ou por uma breve descrição, levamos adiante o processo.
Claro de sua compreensão,
Marcio

**Comment by jjairojr** [comment]
@godois Compreendi, mas no meu currículo está as empresas que atuei como desenvolvedor e consequentemente atuei em projetos reais, grato!

**Comment by godois** [comment]
Entendi @jjairojr . Uma dica: para te ajudar a ter mais êxito no próximo processo, ressalte a experiência já que ela é relevante, mesmo que seja em poucas linhas. Pode ser no cv ou mesmo em uma breve mensagem, como muitos candidatos fazem. Isso ajudará muito o recrutador e você a conduzirem um processo de sucesso.
Muito obrigado pela mensagem!
