### ISSUE TITLE
[REMOTO] Especialista Javascript Frontend na BYCODERS

### ISSUE THREAD

**Issue by igrown-app** [frontendbr/vagas#3248]
## Nossa empresa

Temos mais de 25 anos de experiência em desenvolvimento de sistemas de gestão, em empresas de vários segmentos, utilizando processos e ferramentas consagrados na área de engenharia de software.

## Descrição da vaga

Missão
- Analisar funcionalidades, imaginar e prototipar soluções
- Sugerir soluções de arquitetura e modelagem de dados
- Implementar novas funcionalidades
- Escrever testes automatizados úteis e que documentem as funcionalidades implementadas.

## Salário

- PJ: de R$ 5.000 até R$ 7.000
- CLT: de R$ 3.000 até R$ 5.000

## Local

Remoto

## Requisitos

Obrigatórios:
- Excelente capacidade de comunicação e autogestão
- Habilidades interpessoais, de escrita e de comunicação verbal
- Experiência com Javascript
- Experiência com front end (CSS, html5…)

Desejáveis:
- Conhecimentos em backend
- Conhecimento de frameworks Js
- Experiência com AWS e outros Cloud Services
- Docker
- Inglês (técnico)

Diferenciais:
- Conhecimentos em Rails ou Node

## Benefícios

- Ajuda de custo de até R$150 para internet ou espaço em coworking (trabalhe onde você quiser)
- Reembolso de até R$ 50 em academia ou outra atividade esportiva.
Após 90 dias você também receberá:
- Até R$ 1.000 por ano para aquisição ou upgrade de seus equipamentos de trabalho
- Até R$300 por mês para livros e cursos

Diferenciais:
- Muitas oportunidades de crescimento e aprendizado
- Horário flexível

## Contratação

PJ ou CLT a combinar

## Como se candidatar

Faça seu cadastro em www.igrown.com.br, iforme a vaga para qual está de aplicando e faça seus testes de perfile e cultura na plataforma iGrown.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
Faça seu cadastro em igrown.com.br

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
