### ISSUE TITLE
[BARUERI] Front-End Developer na DRY COMPANY DO BRASIL

### ISSUE THREAD

**Issue by caiosalim** [frontendbr/vagas#3249]
## DRY COMPANY DO BRASIL

Exemplo: Empresa líder no segmento de MVNOs no mercado brasileiro, nosso propósito e a construção dos portais e lojas virtuais para alcançar o público de telecom.

## Descrição da vaga

Exemplo: Com portais desenvolvidos em Wordpress/WooCommerce precisamos de um desenvolvedor front-end para fazer manutenção e desenvolvimento dos portais.

## Local

Exemplo: Escritório, SP, Barueri, Bethaville. 

## Requisitos

**Obrigatórios:**
- Bons conhecimentos em HTML, CSS e Javascript
- Wordpress

**Desejáveis:**
- Conhecimento em WooCommerce
- Conhecimento em NodeJs
- Morar na região próxima.

**Diferenciais:**
- Conhecimento em React

## Benefícios
- Informações com o RH da empresa na hora da seleção.

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um email para caio@drycompanybrasil.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Developer Dry Company do Brasil

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 ou 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: caio.salim@gmail.com

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Júnior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
