### ISSUE TITLE
[Campinas - SP] Tech Lead - Front-End Developer

### ISSUE THREAD

**Issue by endrilcsilva** [frontendbr/vagas#325]
## Descrição da vaga

Work in a dynamic team to provide solutions for Web Frontend application ReactJS (or AngularJS):
- Development of new features;
- Maintenance of existing applications;
- Participate in the complete cycle of development from requirements gathering, development and testing;
- Participate in technical discussions with customer.

## Local

Campinas - SP (Próximo ao Galleria Shopping)

## Benefícios

- Plano de Saúde;
- Vale Refeição de R$712,00;
- Estacionamento Gratuito;
- Horário Flexível;
- Programa de Indicações;
- Vestimenta Casual;
- Frutas, Barras de Cereais e outros alimentos;
- Festas de Integração;
- Aulas de Inglês;
- Desconto em Farmácias;
- Premiações por Reconhecimento;
- Palestras Internas;
- Seguro de Vida;
- Reembolso para Atividades Físicas;
- Vale Alimentação de R$324,00;
- Previdência Privada;
- Plano Odontológico;
- Participação nos Lucros da Empresa;
- Auxílio Creche;
- Auxílio PcD.

## Requisitos

**Obrigatórios:**
- Solid Experience with Javascript (ES2015+);
- Experience with frontend Javascript Frameworks: ReactJS (at least AngularJS);
- Experience with Restful services;
- Experience with agile development (SCRUM);
- Experience with unit testing (w/ Jasmine, Mocha/Sinon, Jest, Ava or Tape);
- Experience with CI/Jenkins.

**Desejáveis/Diferenciais:**
- Knowledge of bases NoSQL;
- Experience with HTML/CSS;
- Experience with nodeJS;
- Experience with relational databases/SQL;
- Experience with docker/kubernetes.

## Contratação

CLT Full

## Nossa empresa

Leading global technology companies rely on Daitan to build their ground-breaking software products. Our experience, expert teams and broad range of software product development services will accelerate your product’s time to market — without introducing risk. We offer software development expertise in: cloud computing and virtualization; communications, collaboration and messaging; and big data and analytics. We offer a full range of services including: product development; product maintenance; and quality assurance and testing. Interested in Learning More? Send your resume to: talent@daitangroup.com.

## Como se candidatar

Por favor envie um email para talent@daitangroup.com com seu CV anexado - enviar no assunto: GitHub - Tech Lead - Front-End Developer

**Comment by gkal19** [comment]
Ótima vaga! Boa sorte!
