### ISSUE TITLE
[São Paulo] Front-End Developer na Printástico

### ISSUE THREAD

**Issue by rafaelaugustoferreira** [frontendbr/vagas#3253]
## Printástico
A Printástico é uma empresa brasileira especializada em FotoProdutos e impressões digitais, que segue os mais altos padrões internacionais de tecnologia e qualidade. Nossa missão é oferecer aos nossos clientes um ambiente seguro e aplicações que garantam a criação de projetos personalizados de maneira rápida, fácil e divertida.
## Descrição da vaga
Procuramos um dev para atuar majoritariamente em nossa ferramenta de criação de foto-produtos para impressão, além de conexões da ferramenta com o site e com a equipe de impressão.
Será necessário o conhecimento e experiência em Front-end, Javascript, HTML5, CSS, Framework React e Redux. Conhecimentos em Git, Redux-saga, Node.js, Webpack, Babel, Cross-env e Scrum são bons diferenciais.
## Local
Escritório, Avenida Paulista, São Paulo, SP
`Durante a pandemia estamos trabalhando remoto`
## Requisitos
**Obrigatórios:**
- Experiência com React e redux
- REST

**Desejáveis:**
- Conhecimentos em Redux-saga
- Conhecimentos em Node.js
- Scrum
## Contratação
PJ - Remuneração a combinar, se preferir nos envie sua pretensão junto com o CV.
## Como se candidatar
Por favor envie um email para rf@printastico.com.br com seu CV anexado - enviar no assunto: Vaga Front-end
#### Alocação
- Alocado
#### Regime
- PJ
#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
