### ISSUE TITLE
[São Paulo] Front-end Developer  PL/SR  na Mobiauto 

### ISSUE THREAD

**Issue by RobsonAraujo** [frontendbr/vagas#3255]
## Nossa empresa

A Mobiauto é uma plataforma de tecnologia do setor automotivo que visa promover maior eficiência e praticidade na relação de compra e venda de automóveis no Brasil. 
https://mobiauto.com.br/

## Descrição da vaga

Atua diretamente com desenvolvimento front-end, desenvolvendo novas features, atuando em bugfix e integração de novos projetos.

## Local

Escritório, São Paulo - Zona Sul - Santo Amaro
(Presencial) -  ps : Remoto  por tempo indeteminado, devido a pandemia  

## Requisitos

**Obrigatórios:**
- Html
- css
- Javascript
- React
- Bibliotecas de gerenciamento de estado do aplicativo.(Redux , mobx)
 

**Desejáveis:**
- conhecimentos em Typescript

**Diferenciais:**
- projetos opensource
- Qualquer outro framework Javascript (Angular, React Native, Vue)

## Benefícios

- fácil acesso da estação santo amaro
- máquina de café
- NO dress code
- Horário flexível
- Ambiente descontraído
- Open Space

**Diferenciais:**
- Mobilândia (video-games e simulador de corrida)
- Alguns campeonatos de FIFA  

## Contratação

Modelo CLT

## Como se candidatar

Por favor envie um email para  robson.carmo@mobiauto.com.br  com seu CV anexado - enviar no assunto: Vaga front-end 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: guilherme.braga@mobiauto.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível

- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
