### ISSUE TITLE
[São Paulo] Front-end Developer  na Mobiauto 

### ISSUE THREAD

**Issue by RobsonAraujo** [frontendbr/vagas#3256]
## Nossa empresa

A Mobiauto é uma plataforma de tecnologia do setor automotivo que visa promover maior eficiência e praticidade na relação de compra e venda de automóveis no Brasil. 
https://mobiauto.com.br/

## Descrição da vaga
Estamos procurando um Desenvolvedor Frontend para um desafio. Queremos desenvolver um blog (uma das principais frentes do nosso produto), com React ,  SSR  e com implementação do AMP(Accelerated Mobile Pages).
## Local

Remoto

## Requisitos

**Obrigatórios:**
- Html
- css
- Javascript
- React
- Bibliotecas de gerenciamento de estado do aplicativo.(Redux )
- conhecimentos em Typescript
- AMP
- Semantic HTML
 

**Diferenciais:**
- projetos opensource

## Benefícios

- No conforto de casa 

## Contratação

- Freela
- Pj

## Como se candidatar

Por favor envie um email para  robson.carmo@mobiauto.com.br  com seu CV anexado - enviar no assunto: Vaga front-end - Projeto revista

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: guilherme.braga@mobiauto.com.br

#### Alocação
- Remoto

#### Regime
- Freela

#### Nível

- Pleno
- Sênior

**Comment by EsioFreitas** [comment]
Aceita part-time?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
