### ISSUE TITLE
[Remoto] Senior Front-end Engineer na AvantStay

### ISSUE THREAD

**Issue by wellguimaraes** [frontendbr/vagas#3259]
E aí pessoal, blz? 😃

Estamos com duas vagas remotas para **senior front-end engineer** aqui na [AvantStay](https://avantstay.com). A empresa tem sede em Los Angeles, mas todo o time de dev é remoto e uma parte está no Brasil.

Estou na empresa há 2 anos e meio, sou o lead front-end e estou conduzindo o processo de contratação. 

## Nossa empresa

AvantStay is a technology-first hospitality brand for group travel. It delivers affordable, world-class, authentic, tech-enabled short-term rental (STR) group experiences targeted at the millennial generation. AvantStay was founded in 2016 and is headquartered in Los Angeles, California.

## O que usamos por aqui?

- React
- Typescript
- Mobx
- Emotion / Styled-components
- GraphQL
- Etc

## Algumas vantagens bem interessantes

- Trabalho remoto
- Horário flexível
- Salário em USD, bem acima do mercado brasileiro
- Feriados nacionais (cada um segue o calendário de feriados do país onde vive)
- Bastante liberdade técnica
- Uso das mais recentes tecnologias disponíveis
- Trabalhar com um time bastante experiente

## Requisitos

- Considerável experiência com FE e React
- Inglês fluente
- Boa percepção de usabilidade, pra implementar as interações adequadamente e colaborar com melhorias
- Boa percepção visual pra seguir adequadamente o design proposto

**Desejável**
- Experiência trabalhando remotamente
- Experiência com TypeScript ou qualquer outra linguagem tipada

## Carga horária
Full-time (40h semanais)

## Contratação
PJ

## Como se candidatar
Se você tiver interesse ou tiver alguém pra indicar, pode falar diretamente comigo via wguimaraes+hiring@avantstay.com.

**Comment by wellguimaraes** [comment]
Pessoal, vagas ainda em aberto por aqui!

**Comment by HenriqueACF** [comment]
tem pra junior?Em 24 de jul de 2020 10:13 AM, Wellington Guimaraes <notifications@github.com> escreveu:
Pessoal, vagas ainda em aberto por aqui!

**Comment by wellguimaraes** [comment]
Infelizmente nao.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
