### ISSUE TITLE
[Remoto] Front-End Developer Pleno/Sênior

### ISSUE THREAD

**Issue by henriquearremate** [frontendbr/vagas#326]
## Descrição da vaga

O Arremate Arte é uma plataforma de gestão e marketing que atende leilões de arte, design, decoração, jóias e colecionismo de todo o Brasil. Após quase 2 anos em nosso projeto piloto com 5 clientes, estamos prestes a lançar oficialmente e iniciar nosso plano de expansão.

Somos uma empresa com espírito jovem e estamos buscando um desenvolvedor front-end que possa ajudar nosso time de produto a continuar inovando e antecipando as necessidades de nossos clientes. Nossa atmosfera é remota, mas temos um aconchegante HQ no RJ. Procuramos por vínculos duradouros e há possibilidade de negociação dos valores e participação societária.

Caso haja interesse, favor entrar em contato através de team@arrematearte.com.br. Obrigado pela atenção! =)

![procuramos senior front end 2017 05 02](https://cloud.githubusercontent.com/assets/28316271/25638369/90d54c0e-2f5e-11e7-9f86-39eacccce088.png)

## Local

Remoto ou Escritório, Rio de Janeiro - RJ

## Contratação

PJ a combinar

## Como se candidatar

É só mandar um e-mail para team@arrematearte.com.br.

**Comment by gkal19** [comment]
É uma ótima vaga! Boa sorte!

**Comment by xereda** [comment]
A experiência em Ruby on Rails é pré-requisito incondicional para a vaga?

**Comment by henriquearremate** [comment]
Olá, Jackson. Não é um pré-requisito incondicional, mas, como o sistema se encontra programado em Ruby on Rails, esse é um diferencial. 

Abraços!

**Comment by xereda** [comment]
@henriquearremate O valor hora é de R$ 26,25?

**Comment by henriquearremate** [comment]
Na verdade R$ 24,00, pois consideramos meses de 30 dias com 22 dias de trabalho.

**Comment by ericprieto** [comment]
Sênior PJ por R$ 24,00/h é sacanagem, hein

**Comment by xereda** [comment]
@ericprieto @henriquearremate Realmente para "sênior" está fora.

**Comment by ygorlazaro** [comment]
É um valor interessante se for 15/horas semanais. Até porque se for sênior realmente, pela descrição, parecem ser projetos em que se levaria pouco tempo (de novo, como sênior).

**Comment by xereda** [comment]
@ygorlazaro mas são 40 horas semanais.

**Comment by ygorlazaro** [comment]
@xereda pois é, aí é puxado. Não deve existir um sênior com esse tempo disponível a esse valor

**Comment by joelwallis** [comment]
Fala @henriquearremate!

Cara, a vaga parece legal. Gostei do anúncio, ficou bem sensato e realista. A única questão a ser revista foi a remuneração. Ela não é mesmo compatível para um Senior. :-\ Fica a dica: você está procurando um Pleno 🙂

Sucesso na contratação!

**Comment by henriquearremate** [comment]
@joelwallis @xereda @ericprieto @ygorlazaro Galera, a vaga é para Senior ou Pleno. Nós vamos editar o anúncio. O valor é negociável dependendo do perfil do profissional, assim como a participação societária. O projeto é bacana e ainda existem aqueles que não são movidos apenas por dinheiro. Vamos ajudar os poucos que se aventuram a empreender nesse país ao invés de apenas criticar. No mais, agradeço pelos comentários. Abraços!

**Comment by ygorlazaro** [comment]
@henriquearremate eu entendo seu ponto de vista, eu também sou um empreendedor com uma microempresa. O que achamos estranho para sênior é a questão valor-hora, mas se você derais enfoque na participação creio que a vaga seja mais chamativa. Já que a ideia é ter profissionais que não estão buscando o valor no primeiro momento, pode considerar a possibilidade de ter um sócio/participação societária como sendo o diferencial dá oportunidade.

**Comment by ericprieto** [comment]
@henriquearremate "Ajudar os poucos que se aventuram", não. Que tal "Vamos remunerar de forma justa aqueles que te ajudam a construir seu empreendimento"?

Emprego não é "ONG De Ajuda à Empreendedores".

E sim, temos que criticar, nosso mercado é sério e precisa desesperadamente amadurecer, se nós não nos posicionarmos, logo logo estaremos sucateados.

**Comment by henriquearremate** [comment]
@ygorlazaro Obrigado pela sugestão. Vamos mudar o anúncio visual para deixar claro que o valor é negociável, que existe a possibilidade de equity e que pode ser um sênior ou um pleno. Abraços!

**Comment by henriquearremate** [comment]
@ericprieto Compreendo o seu lado. Não é objetivo nosso aviltar a remuneração de ninguém, tampouco remunerar de forma injusta aqueles nos ajudam, mediante remuneração - afinal, emprego não é "ONG de Ajuda à Autônomos" -, a construir o nosso empreendimento. 

Tanto é assim que: os valores são negociáveis; existe possibilidade de participação societária; aceita quem quer; e a vaga é pra Pleno ou Sênior, tendo havido retificação nossa nesse sentido.

Se a vaga não interessou, é só partir pra outra :). Melhor que não ter vaga alguma, né?

E sim, tenho plena certeza que o mercado de vocês é sério. Não estamos questionando isso, e a issue não pretende ofender ninguém, muito menos vocês, e sim apenas oferecer uma oportunidade, o que, por si só, já valoriza o mercado de vocês e qualquer outra remuneração em qualquer outro lugar, pelo mais que esta remuneração em específico possa parecer baixa. 

Programei dos 11 aos 14. Até um curso de programação web no SENAC fiz. Na época era PHP5 e outras frameworks ultrapassadas, rs. Adoro programar e até hoje sobra alguma coisa para fazer no Excel, rs. Não sou mais minimamente sequer entendido e nunca fui nenhum expert em programação.  No entanto, já estou empreendendo na área de Tecnologia há algum tempo e, há mais de 3 anos, ajudando a gerir e arquitetar este grande projeto de tecnologia que estamos desenvolvemos aqui na nossa empresa. Posso te afirmar que eu nunca compactuaria em vir aqui para provocar qualquer desmerecimento à classe dos programadores. 

Respeito muito a profissão de vocês e conheço o mercado, embora não seja programador. Como advogado, já geri grandes contratos de tecnologia e, no meu senti, não vejo que o mercado de vocês precise amadurecer ou que esteja caminhando para o sucateamento, pelo contrário, o mercado de vocês me parece até bastante valorizado, acredite. 

Desse modo, não acredito haver o porque de se criticar, mormente quando qualquer oportunidade divulgada apenas possui o efeito de valorizar a profissão de vocês. Conforme dito: o valor é negociável; a vaga é para pleno ou sênior (o que sempre esteve no título da issue); existe a possibilidade de participação societária; e todos são livres para não aceitá-la ou simplesmente ignorá-la.

De qualquer modo, peço desculpas por qualquer inconveniente ou mal entendido. 

Abraços, galera!

**Comment by ericprieto** [comment]
@henriquearremate obrigado pela resposta, eu só queria comentar uma última coisa, sobre o ponto "Se a vaga não interessou, é só partir pra outra :). Melhor que não ter vaga alguma, né?".

Não é exatemente assim, não podemos pensar em extremos, e quando existem vagas com valores baixos assim (considerando que esse valor seria de um sênior, só para completar meu ponto aqui) começa a acontecer um "leilão", onde quem aceitar o valor mais baixo ganha. Isso colabora para o clima de crise, de competização entre colegas de profissão, e o pior de tudo o sucateamento, pois o valor de toda a categoria para baixo, entende? É por isso que um piso salarial é importante, e uma consciência, tanto no empregado quanto no empregador, de que é positivo para todos e principalmente para a economia que uma remuneração justa.

Não estou dizendo que sua empresa ou você são culpados de nada individulamente, mas é um tipo de cultura que temos que evitar, e como desenvolvedor, não posso me calar. Espero que não tenha levado para o lado pessoal.

Boa sorte com seu empreendimento, espero de verdade de que prospere e que possa dividir o bolo com seus colaboradores.

Abraços,
Eric Prieto

**Comment by ygorlazaro** [comment]
Saiu uma discussão bem saudável, gostei muito 😀

**Comment by henriquearremate** [comment]
@ericprieto Não há de que! Obrigado a você. Estou plenamente de acordo. Realmente, não quis levar pra extremos. Só quis ponderar que toda a oportunidade existente e divulgada tende à elevação da remuneração média, visto que vagas com remuneração baixa serão depreciadas pelos próprios profissionais, enquanto vagas com remuneração alta serão apreciadas e procuradas. Se houver apenas vagas com remuneração baixa, aí, evidentemente, a remuneração média irá cair e, consequentemente, ocorrer o sucateamento. No entanto, isso está longe de ocorrer no mercado de vocês. Me parece que as coisas estão equilibradas. 

De qualquer modo, gostaria de deixar claro que não estamos fazendo leilão. Como disse, fomos mal interpretados, uma vez em que a vaga era pra Sênior ou Pleno. O valor de R$ 4.200,00 na verdade é uma referência, um ponto de partida, algo que poderíamos considerar até mesmo como um piso. Para contratação, levamos em consideração diversas variáveis: tempo disponível para dedicação ao projeto, empenho, perfil, capacidade/qualificação técnica, experiências profissionais pretéritas, etc. 

Se tem algo pelo que prezamos dentro da nossa empresa, é a excelência. Portanto, posso lhe assegurar, com plena convicção, que não optaremos pelo mais barato simplesmente por ser mais barato. Afinal, de vez em quando, o barato sai caro, né? Hahahaha

Abraços, 
Henrique Mendes.

**Comment by henriquearremate** [comment]
Galera, obrigado, os votos de sucesso deram certo! Estamos encerrado o processo seletivo!

Abraços!
