### ISSUE TITLE
[Remoto] Front-end Developer no Beblue

### ISSUE THREAD

**Issue by Gabrielle1012** [frontendbr/vagas#3260]
## Nossa empresa

O Beblue é uma Fintech de pagamentos com carteira digital que tem como objetivo aumentar o poder de compra das pessoas através de recompensa em cashback. 💰 Atuamos no varejo físico em centenas de cidades brasileira. 💙

## Descrição da vaga

Como um desenvolvedor(a) Front-End Pleno você será responsável por:

- Participar do projeto e implementar soluções de software além de acompanhar os desenvolvedores menos experientes durante o desenvolvimento do produto;
- Colaborar na arquitetura das soluções focando em requisitos não funcionais como disponibilidade, escalabilidade e performance;
- Desenvolver e executar planos de testes para validação de aplicações e revisar o resultado dos testes;
- Trabalhar em conjunto com o time de design, no projeto de interfaces e UX do produto, seguindo fielmente as especificações;
- Utilizar API’s RESTFul e abstrair componentes para a criação de aplicações Híbridas ou SPA’s;
- Utilizar ferramentas para inspeção e monitoramento do comportamento do sistema.

## Local

- Remoto ou Escritório, Ribeirão Preto/SP

## Requisitos

**Obrigatórios:**

- Fluência em React e Redux e seu ecossistema;
- Experiência com Programação Javascript para Front-End;
- Fluência em JavaScript, HTML5, CSS3;
- Conhecimento sobre os princípios de TDD e BDD;
- Desenvolvimento de interfaces responsivas.

**Desejáveis:**

- Formação de Ensino Superior em Análise e Desenvolvimento de Sistemas ou equivalente;
- Experiência com cultura Agile.

**Diferenciais:**

- Experiência com O.S. Linux/Unix;
- Experiência com o ecossistema Web (Task Runners, Yarn/NPM, Webpack, Pré-processadores como SAAS e Babel);
- Experiência com GIT e GITFlow;
- Desenvolver em alguma linguagem de programação Back-End;
- Conhecimento sobre Integração Contínua e Entrega Contínua (Jenkins, Drone.io, CircleCI, etc...).
- Conhecimento sobre AWS;
- Conhecimento sobre Aplicações conteinerizadas com Docker.

## Benefícios

Jornada de trabalho flexível

## Contratação

PJ a combinar

## Como se candidatar

https://www.linkedin.com/jobs/view/1905075494/
Ou enviar e-mail para: gabrielle.bocardi@beblue.com.br com o título: "Front-end Developer"

## Labels
- 🏢 Flexível
- 🏢 Remoto
- 👴 Sênior
- ⚖️ PJ

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
