### ISSUE TITLE
[São Paulo/SP] Front-end Developer na Athos

### ISSUE THREAD

**Issue by negaomor10** [frontendbr/vagas#3262]
## Descrição da vaga

Procuramos pessoass apaixonadas com o propósito de revolucionar o design e a criação de software atuando como um Desenvolvedor  Front-end SPA Junior/Pleno.

## Local

Liberdade - São Paulo - Inicialmente o trabalho será remoto devido as restrições do COVID-19	

## Benefícios

- Plano de saúde
- Seguro de vida
- Vale Refeição
- Vale Transporte
- Cursos

#### Diferenciais

- Horário Flexível
- No Dress Code
- Folga no dia do aniversário;
- Festa em comemoração aos aniversariantes do mês;
- Descontos em faculdades, cursos de inglês e espanhol;
- As datas comemorativas sempre são lembradas com uma surpresa (dia das mães, dias dos pais, Páscoa, etc...);

## Requisitos

**Obrigatórios:**
- Experiência com algum framework JS (Vue Js, Angular, React) - pelo meno 1 ano;
- Experiência em programação SPA - pelo menos 1 ano;
- Experiência em layouts responsivos - pelo menos 1 ano;
- Experiência em implementação de design (Bootstrap, Material ou similar) - pelo menos 1 ano;
- Conhecimento avançado de javascript;
- Experiência em desenvolvimento em equipe utilizando versionamento (GIT);
- CSS3 e Pré-processadores como Stylus e SASS;
- Clean code;
- Documentar implementações;

**Desejáveis:**
- Boas noções de UX;
- Experiência com criação de APIs REST;
- Experiência com Metodologias Ágeis / Scrum;

**Diferenciais:**
- Projetos open-source
- MongoDb;
- .Net

## Nossa empresa

A Athos está em constante crescimento no mercado e gostaríamos de trazer novas pessoas para nosso time. Nós buscamos trabalhar com as tecnologias mais atuais do mercado e com metodologias ágeis.
Estamos buscando um profissional com um perfil proativo, comunicativo e detalhista, com menor necessidade de mentoria e menor supervisão no cumprimento das tarefas.

**Aqui usamos:**
- Vue.js
- C#
- Azure

## Como se candidatar

Por favor, envie um e-mail para rh@athos.com.br com seu CV anexado. Enviar no assunto: _Vaga Vue.js_

#### Experiência
- Júnior
- Pleno

#### Regime
- CLT

**Comment by barcellos-pedro** [comment]
E-mail enviado, obrigado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
