### ISSUE TITLE
[Recife] Front-End Developer no Mola

### ISSUE THREAD

**Issue by vicentimartins** [frontendbr/vagas#3265]
## Nossa empresa

Somos uma startup pernambucana que nasceu para impulsionar quem atua nos mercados de correspondência bancária e de produtos financeiros. Vem ser mola com a gente!

## Descrição da vaga

Aqui no mola estamos desenvolvendo produtos novos, para isso, usamos React+Redux no front-end.

## Local

Nosso escritório fica na região do Porto Digital, PE, Recife, Recife Antigo

## Requisitos

**Obrigatórios:**
- Sólidos conhecimentos em Html e Css
- Sólidos conhecimentos em JS (ES6+) e/ou Typescript
- Sólidos conhecimentos em React/Redux
- Experiência atuando como front-end
- Experiência no consumo de API
- Experiência no desenvolvimento de SPA
- Conhecimento em GIT
- Experiência com metodologias ágeis

**Diferenciais:**
- Atuação anterior em projetos que utililzam microserviços
- Conhecimento em PHP ou uma outra tecnologia back-end
- Experiência com Angular, Vue.js ou outro framework/lib semelhante
- Conhecer ferramentas de testes e saber escrevê-los

## Benefícios

- Plano de saúde custeado integralmente
- Auxílios alimentação, transporte, creche e lente
- Frutas e café a vontade

**Diferenciais:**
- Flexibilidade de horário e para trabalho home-office
- Ambiente de trabalho extremamente descontraído

## Contratação

CLT

## Como se candidatar

Por favor envie um email para oportunidades@molacorban.com.br com seu CV anexado - enviar no assunto: Dev Front-End no Mola

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by vicentimartins** [comment]
@felipefialho a vaga é para Recife. Pode alterar a label pfv?!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by vicentimartins** [comment]
Vaga preenchida.
