### ISSUE TITLE
[DIVERSOS] Front-end Developer na Codeminer42

### ISSUE THREAD

**Issue by abnersajr** [frontendbr/vagas#3266]
## Nossa empresa

A Codeminer42 é uma butique de software brasileira focada em entregar o melhor valor a seus clientes. Começando suas operações em Setembro de 2011, já expandimos para 12 cidades diferentes no Brasil com os melhores profissionais e desenvolvedores do Brasil.

### Nossos Desafios
Nós somos miners.

Entregar valor em qualquer projeto é um processo difícil. Como desenvolvedores de software nos esforçamos para entregar não somente código bem escrito, mas código que entrega valor real a cada cliente.

Não é bom o suficiente se preocupar apenas com código pelo código, mas entregar código que resolve problemas reais e entregam valor real. E essa é a missão que nós, como miners, vamos continuar cavando fundo para cumprir.

### Seus desafios
Na Codeminer42 você terá a oportunidade de trabalhar com os mais diversos tipos de projetos, com tecnologias variadas e um time de pessoas incríveis que estarão sempre prontas a te ajudar no que você precisar. Incentivamos o diálogo e o compartilhamento de conhecimento e apoiamos o desenvolvimento open-source.

Alguns desafios farão parte dessa trajetória:
- Trabalhar juntamente com times diversificados;
- Buscar novos conhecimentos e tecnologias;
- Não ter medo de se adaptar. Buscamos e incentivamos o aprendizado;
- Saber se comunicar é de extrema importância.

## Local

- São Paulo
- Campinas
- Novo Hamburgo
- Natal
- Poços de Caldas
- Teresina
- Anápolis
- Goiânia
- Ribeirão Preto
- Guarapuava
- Santa Maria
- João Pessoa

## Requisitos

- Pelo menos 1 ano de experiência em desenvolvimento com JavaScript moderno (React, React Native, Vue ou Angular). Experiência com algum outro não listado é analisado individualmente. Mas não deixe de entrar em contato;
- Interesse em aprimorar suas habilidades através da prática em diferentes projetos, incluindo projetos de clientes e open source;
- Estar disposto a trabalhar em um ambiente de organização horizontal onde o "sim, senhor" não é aceito e as críticas proativas são sempre bem-vindas;
- Inglês avançado. Temos clientes internacionais e uma boa compreensão e conversação são fundamentais. O inglês é de extrema importância e será parte do processo seletivo.

### Extras

- Conhecimentos em NodeJS;
- Conhecimentos em Ruby e Ruby on Rails;
- Conhecimentos de infra-estrutura. Heroku e AWS são amplamente utilizados no dia a dia.

## Benefícios

- Vale-refeição;
- Vale-transporte;
- Ambiente de trabalho descontraído;
- Curso de inglês para aperfeiçoamento;
- Plano de saúde e dental;
- Participação nos resultados;
- Acesso a livros e cursos de programação.

## Contratação

CLT

## Como se candidatar

Preencha o formulário na vaga desejada no site (https://www.codeminer42.com/careers/front-end-software-engineer)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 4 dias após cada processo.
E-mail para contato em caso de não haver resposta: abner.alves@codeminer42.com

## Labels
- Remoto durante Pandemia

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by abnersajr** [comment]
As posições continuam abertas.
