### ISSUE TITLE
[São Paulo] Front-End Developer na Salú

### ISSUE THREAD

**Issue by miguelpragier** [frontendbr/vagas#3267]
# Nossa Empresa
A Salu nasceu em 2018, com a missão de aproximar as pessoas dos cuidados com sua própria saúde.
Nossos principais produtos são telemedicina por voz e vídeo, e checagem de sintomas para triagem virtual.
Nossa operação comercial já iniciou, e estamos prontos para o próximo passo, com o release do app mobile e o crescimento do time dev.
Somos orgulhosos por termos sido [acelerados pelo C6](https://medium.com/c6banknoticias/conhe%C3%A7a-as-seis-startups-selecionadas-para-a-2%C2%AA-turma-do-opp-3492380a172f) entre 2019 e 2020, e ainda hoje pelos pesos-pesados [Eintein Eretz](https://eretz.bio/startups) e pela [Quintessa](https://www.quintessa.org.br/portfolio/areas-de-impacto/saude/#saude-logos).
Pra saber mais, visite nosso [website](https://salu.com.vc/), e nossa página no [Linkedin](https://www.linkedin.com/company/salú/), onde você também conhece nosso time. 

# Descrição da vaga
Temos **uma** vaga para dev frontend VueJS junior, com pouca (mas alguma) experiência.
Será responsável por produzir desde os protótipos navegáveis, até os apps em produção, integrados via REST APIs.
No início, será ajudado por todos, e nas primeiras semanas mentorado por um membro do time.
Após a pandemia, a Salu reabrirá seu escritório em São Paulo, mas esta vaga é remota.
**Sabemos que o candidato iniciante poderá não dominar todos os requisitos, e estamos dispostos a ensinar, desde que o candidato demonstre interesse e comprometimento.**

# Local
Remoto

# Contratação
PJ

# Requisitos
- Experiência profissional em ao menos um projeto com html, css e javascript;
- Tem que saber programar em javascript. Pra valer!
- Base teórica de computação, em faculdade, curso médio ou curso livre;
- Inglês básico para leitura técnica;
- GIT, APIs REST;
- Disponibilidade em horário comercial, de segunda à sexta. O horário é flexível, mas a carga horária não;
- Curiosidade técnica;
- Autonomia para estudo;
- É importante que o profissional goste de frontend.

# Processo Seletivo
- 100% online;
- Análise do material enviado ou referenciado no email;
- Conversa para conhecer o candidato, e para o candidato conhecer a empresa;
- Conversa sobre engenharia de software, para avaliar os conhecimentos do candidato;
- Teste rápido de codificação online;
- Conversa com os gestores e o time dev;

# Como se candidatar
- Por favor envie um email para miguel@salu.com.vc, com assunto: Vaga Frontend JR.
- Inclua portfolio, repositório github, currículo, linkedin e todo material que possa nos mostrar um pouco de seu nível técnico.
- Conte na mensagem o porquê de ter se interessado na vaga.
- Certifique-se de haver lido, entendido e cumprido os três itens acima da candidatura. Isso nos demonstra que você é bom com especificações escritas :-)

# Tempo médio de feedbacks
3 dias, no máximo.
E-mail para contato em caso de não haver resposta é o mesmo da candidatura.

# Nossa Cultura e nossos valores
- Valorizamos muito a boa educação, a gentileza e a atitude positiva;
- Vontade de aprender e de participar são essenciais;
- Liberdade com responsabilidade;
- Nós nos ajudamos a crescer como pessoas e profissionais;
- A empresa ainda é pequena, e nossos processos simples e desburocratizados.

# Labels
Remoto
PJ
Júnior

**Comment by MarceloEsc** [comment]
Comecei a estudar Vue a pouco tempo e ainda estou me familiarizando com os frameworks front end do javascript, mas irei mandar o currículo, pois mesmo que a vaga não seja pra mim quero aprender com a oportunidade.

**Comment by miguelpragier** [comment]
Estou fechando a issue, pois já recebemos muitos currículos excelentes, e não conseguimos mais dar conta de tantos.
Lamento pela demora no retorno.
Mesmo que atrase alguns dias, todos receberão respostas nossas, positivas ou não.
