### ISSUE TITLE
[Curitiba/Remote] Senior FullStack TypeScript+Node.js na Visionnaire

### ISSUE THREAD

**Issue by raulbalestra** [frontendbr/vagas#3268]
Olá a todos,

Estamos a procura de um profissional SR. com para fazer parte de nossa equipe.

**Business**
a platform for automation logistics, which makes bulk shipping replacing the thousands of emails, excel files, and instant messages between players required for each booking. The tool-kit gets connected to any email inbox and extracts data from emails and attachments in real-time automatically.

**Requirements**
The customer is looking for a backend engineer with **TypeScript/Node.js and 4+ years** of experience. The engineer should be skilled as he will participate in the estimation, planning, and executions of projects, features, and integrations. Also, engineers will be developing new products and features, improving the existing ones with a focus on APIs and BE processes.

Technologies: **Node.js, TypeScript, CircleCi, Postgres, AWS Lambda**

This position has two specific things:

The customer has highly accurate data extracted from their ML platform which needs to be available via APIs and integrations with complex interactions between lead's and his customer's systems
Writing code for production level systems handling millions of shipments per year, used 24/7 across different time zones, with high requirements on reliability and security
 
Start date: asap
Duration: full-time collaboration for **at least 3 months**, could become ongoing

**English is MANDATORY.**

Budget: 16k PJ

Como se candidatar:
Por favor envie um email para raul.balestra@visionnaire.com.br com seu CV anexado - enviar no assunto: Senior FullStack TypeScript+Node.js

Alocação:
Alocado ou Remoto
Regime:
PJ
Nível:
Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
