### ISSUE TITLE
[Belém] Front-end Developer na Terras App Solutions

### ISSUE THREAD

**Issue by elton-terras** [frontendbr/vagas#3269]
## Terras App Solutions

Terras App Solutions é uma empresa nascida na Amazônia que simboliza o compromisso de profissionais e acadêmicos em contribuir para o desenvolvimento econômico e social, desde que conciliado com o uso sustentável dos recursos naturais.

Nossa Missão é desenvolver soluções sustentáveis para o campo. Nossa Visão é a de que soluções inovadoras nascem e são implementadas com parcerias estratégicas e que essas parcerias podem contribuir para um futuro melhor do nosso planeta.

## Descrição da vaga

Você irá desenvolver e contribuir junto com restante da equipe. Você pode conhecer um pouco mais da nossa equipe [aqui](https://terras.agr.br/2019/index-w#Equipe)

## Local

Remoto (ao menos) durante a pandemia, ou Escritório, [PA], [BELÉM], [REDUTO]

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Angular
- 4 anos de experiência com outras linguagens
- 

**Desejáveis:**
- conhecimentos em React, Vue
- conhecimentos em Leaflet

**Diferenciais:**
- projetos opensource
- trabalhos voluntários
- noções de UX
- experiência com criação de APIs REST
- experiência com metodologias ágeis / scrum

## Benefícios CLT

- plano de saúde
- vale alimentação
- seguro de vida

**Diferenciais:**
- ambiente sadio e colaborativo
- horário flexível
- sem "dress code"
- frutas e outros alimentos (quando no escritório)
- interações com empresas no mundo inteiro

## Contratação

CLT

## Como se candidatar

Por favor envie um email para contato+fep@terras.agr.br com seu CV anexado - enviar no assunto: Vaga Frontend Developer, e responder este [questionário](https://forms.gle/9jQEMnx576vpywZs9).

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 14 dias após cada processo.
E-mail para contato em caso de não haver resposta: contato@terras.agr.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by welll** [comment]
Oi @felipefialho , o label `Remoto` está errado, na descrição tem a seguinte frase `Remoto (ao menos) durante a pandemia,`

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
