### ISSUE TITLE
[Remoto] Front-end Developer Pleno na Trakto

### ISSUE THREAD

**Issue by jorgehsrocha** [frontendbr/vagas#3272]
# Frontend Pleno Na Trakto

## [ SOBRE A VAGA ]
Esta vaga é para desenvolvedores **Frontend**, nível pleno, 100% remoto, e com experiência em plataformas em "escala", com contrato PJ.   

## [ QUEM É A TRAKTO ? ]

(https://www.trakto.io) 

Somos uma startup com 6 anos de existência, para criação de "design's" digitais e impressos ([https://www.youtube.com/watch?v=FLEMUC1peqs](https://www.youtube.com/watch?v=FLEMUC1peqs&t=29s)). Atuamos no Brasil e  outros países, contamos com mais de 30k usuários ativos na plataforma.

 ## [ ATIVIDADES ]

- Sugerir e estruturar a arquitetura frontend das nossas aplicações;
- Sugerir novas ferramentas, tecnologias e arquiteturas que possam melhorar as aplicações e serviços;
- Componentizar itens de UI e features globais entre as aplicações;
- Criar testes automatizados de UI a fim de garantir fidelidade para views e experiência de uso;
- Garantir qualidade de processamento e perfomance da camada de frontend;
- Implementação e manter novas e antigas funcionalidades;

## [ REQUISITOS ] 

- Capacidade de comunicação e autogestão;
- Capacidade interpessoal de escrita e comunicação verbal;
- Inglês (técnico);
- Experiência consolidada com Typescript e Javascript;
- Experiência profissional com produtos reais utilizando o Angular 8+, VueJS ou React;
- Experiência com componentização e reuso de estruturas frontend;
- Noções ou experiência com integrações utilizando API's;

## [ HABILIDADES DESEJÁVEIS ]

- Habilidades com Google Cloud, Firebase ou AWS;
- Experiência com estruturas NodeJS que possam dar suporte ao frontend dos produtos;
- Experiência com bancos não-relacionais;

## [ Aplicação para a vaga ]

1. Enviar **Github, LinkedIn e/ou outras informações para o email jorge@trakto.io utilizando o assunto "Vaga Frontend Pleno".**
2. Aplicações sem pretensões salariais ou sem disponibilidade de trabalho imediato serão rejeitados automaticamente. Como o trabalho é remoto e itens bem definidos, é necessário estar atento(a) as necessidades da vaga;

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
