### ISSUE TITLE
[São Paulo-SP] Front-end Developer Pleno na ZX Ventures

### ISSUE THREAD

**Issue by rafaelrabaco** [frontendbr/vagas#3274]
## Sobre a ZX Ventures
A ZX Ventures é um grupo global de inovação e growth da AB InBev, líder mundial do mercado cervejeiro e uma das 5 maiores companhias de bens de consumo do mundo. Fundada em 2015, nosso objetivo é desenvolver novos produtos e negócios que atendam às necessidades emergentes do consumidor. Temos várias unidades de negócios globais que atuam em áreas que possuem relação com nosso principal negócio, a cerveja: artesanais, internacionais e especiais, eCommerce, homebrewing, experiência da marca, e exploration.

## Descrição da vaga
Você ira fazer parte do time do Sempre Em Casa.
Mas o que é o Sempre em Casa?
Todo final de semana você planeja um churrasco para reunir amigos e família, então você gasta muito tempo no supermercado buscando por promoções ou carregando vários packs de cerveja pra ter certeza que ninguém irá precisar sair da festa para buscar mais.
E se você não precisar passar mais por isso e ainda economizar tempo e dinheiro?
Com o Sempre em Casa você pode automatizar a sua rotina de consumo, escolhendo as bebidas que você ama e receber quando você precisar, sem burocracia ou taxas! E o preço é melhor ou igual ao que você encontra no mercado mais próximo. Legal né?
Nós acreditamos que todos merecem ter sua rotina de consumo facilitada, não importa como e quando. Para realizar isso, usamos tecnologia. Já pensou fazer parte desse time e criar soluções cada vez melhores pro consumidor?

## Local
Alocado em São Paulo - SP (Itaim Bibi), com possibilidade de homeoffice.
Estamos 100% remoto durante a pandemia.

## Requisitos

**Obrigatórios:**
- React
- Redux
- Hooks
- Next JS
- Styled-components
- GIT
- Webpack

**Será um plus:**
- Experiência com Serveless;
- Ferramentas de Continous Deploy;
- Ferramentas de Teste e Assertions;
- Experiência em SEO;
- Experiência com React Native;
- Conversação minima em inglês (Interações com time global de engenharia e de produto);

## Benefícios
- Plano de saúde SulAmerica;
- Plano odontológico OdontoPrev;
- Seguro de vida;
- Previdência Privada;
- Vale transporte;
- Vale refeição;
- Auxílio creche;
- Descontos em medicamentos;
- Licença maternidade e paternidade extendidas;
- Auxílio material escolar;
- Descontos expressivos em produtos e estabelecimentos Ambev;
- Geladeira abastecida com as melhores marcas;
- Frutas frescas no escritório;
- Gympass;
- Horário flexível;
- Assessoria financeira, jurídica e psicológica para funcionários;
- 14º salário;
- Remuneração variável anual (bônus) competitiva

## Contratação

CLT

## Como se candidatar
Candidatura simplificada no linkedin: [https://www.linkedin.com/jobs/view/1907716660/](https://www.linkedin.com/jobs/view/1907716660/)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
