### ISSUE TITLE
[Remoto ou São Paulo/SP] Front-end Developer no Curseduca

### ISSUE THREAD

**Issue by vcampitelli** [frontendbr/vagas#3275]
## Nossa empresa

O Curseduca é uma empresa especializada em _e-learning_ criada em 2013, oferecendo educação através de soluções tecnológicas.

Possuímos uma plataforma LMS _(EAD)_ de desenvolvimento próprio com foco na experiência de aprendizado de seus alunos, podendo ser utilizada por produtores que promovam seus conteúdos digitais e por empresas que queiram ter uma universidade corporativa para capacitação de colaboradores e/ou clientes.

## Descrição da vaga

Estamos procurando alguém para iniciar nossa equipe de front-end! Atualmente, contamos com full-stacks mas reconhecemos a necessidade de ter um time focado nessa área.

Iremos criar as novas funcionalidades do nosso sistema utilizando **React**, portanto precisamos de alguém que:

  - Crie interfaces responsivas e amigáveis com foco em usabilidade;
  - Trabalhe com o time de produto para entregar a melhor experiência para o usuário;
  - Tenha pró-atividade para incorporar tecnologias e ferramentas que estejam em alta no mercado.

## Local

Tempos disponibilidade para trabalho remoto ou presencial.

Para quem estiver em São Paulo/SP ou região, gostaríamos de contar com você durante o primeiro mês em nosso escritório, que se situa no Brooklin (Zona Sul da capital).

## Requisitos

**Obrigatórios:**
- Intermediário em React, Redux e seu ecossistema;
- Básico em ES6+;
- Consumo de APIs REST;
- Criação de layouts responsivos.

**Desejáveis:**
- Conceitos de UI para criação de interfaces agradáveis;
- Básico de Git;
- Padrões de qualidade de código (ex: clean code);
- Gerenciamento de dependências (npm ou yarn);
- Webpack.

**Diferenciais:**
- Conceitos de UX para entregar melhor experiência ao usuário;
- Componentização de elementos para reuso no sistema;
- Experiência com metodologias ágeis (principalmente SCRUM);
- Pré-processadores de CSS3 (principalmente SASS);
- TypeScript.

## Benefícios

- Incentivos para compra de livros, cursos e participações em eventos na área;
- Autonomia na escolha de padrões, tecnologias e ferramentas seguindo tendências de mercado.

## Contratação

PJ a combinar

## Como se candidatar

Envie um email com assunto `Vaga Front-end` para vcampitelli@curseduca.com e anexe seu CV e portifólio (se houver).

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.
E-mail para contato em caso de não haver resposta: contato@curseduca.com

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

**Comment by JuhVieira** [comment]
Nao estou conseguindo enviar curriculo para o email da vaga. 

A resposta do servidor remoto foi:
Recipient address rejected: Access denied.

**Comment by MatSa20** [comment]
@JuhVieira eles deixaram outro email, eu também não consegui pelo principal, então enviei pelo segundo e deu certo!

**Comment by vcampitelli** [comment]
Gente, o Outlook me trollou, a caixa foi criada mas está demorando para propagar huauhahua Podem mandar direto para contato@curseduca.com, vou editar a issue :) obrigado!

**Comment by maxrandrade** [comment]
Enviado!

**Comment by vcampitelli** [comment]
Agradeço a todos pelos currículos enviados! Fechei a issue pois finalizamos o processo seletivo.
