### ISSUE TITLE
[Curitiba] Front-end Developer na HeroSpark

### ISSUE THREAD

**Issue by jeanmalves** [frontendbr/vagas#3276]
## Nossa empresa

Somos uma plataforma de empreendedorismo digital que já impactou mais de 6 milhões de alunos, temos a missão de transformar conhecimento em negócios digitais de alto impacto e por isso, acreditamos que todas as pessoas possuem algo especial que as fazem ser especialista em algum assunto! Por isso, estamos buscando alguém para trabalhar no nosso time de Desenvolvimento para que possa nos ajudar cada vez mais a despertar essa faísca. 

Trabalhar no time de DEV da HeroSpark é a oportunidade de estar em um ambiente de alta performance, desenvolvendo habilidades e crescendo em diversas áreas.

## Descrição da vaga

Estamos buscando por um front-end sênior para integrar nosso time para atuar com:
- Desenvolvimento e manutenção nos produtos HeroSpark (plataformas de e-commerce, ensino, entre outros) 
- Aplicação de templates;
- Criação e customização de páginas
- Otimização de páginas para SEO
- Aplicar melhorias de performance relacionadas ao front-end.

## Local

Remoto ou escritório, Curitiba - Centro

## Requisitos

**Obrigatórios:**
- Boa comunicação
- Espírito de equipe
- Possuir mindset ágil (priorização, ciclos rápidos e feedback)
- Ampla experiência como desenvolvimento de websites (Prototipação de layout com HTML5 , flex layout, CSS3, SASS, Bootstrap e Materialize)
- Amplo conhecimento em Javascript e JQuery
- Experiência com bower, gulp, webpack
- Experiência com AngularJs
- Experiência com Angular ou VueJS
- Experiência no consumo de web APIs
- Ampla experiência com GIT
- Noções de design para web

**Desejáveis:**
- Experiência com liquid template language
- Experiência  com Ruby e Ruby on Rails
- Experiência com Amazon AWS S3
- Inglês avançado/fluente

**Diferenciais:**
- Projetos opensource
- Experiência com processos de deploy, CI/CD e monitoramento de aplicações front-end

## Benefícios

- Vale transporte;
- Vale refeição R$18,81;
- Treinamentos e workshops (internos e externos);
- Seguro de vida;
- Parcerias com estabelecimentos da região;
- Assistência médica;

## Contratação

Á combinar.

## Como se candidatar

Por favor acesse o [link da oportunidade](https://herospark.abler.com.br/vagas/front-end-developer-sr-408614)  e clique em "candidatar-se".

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Sênior

**Comment by jeanmalves** [comment]
@felipefialho poderia trocar a label São Paulo para Paraná? Não especifiquei ali, acabou passando.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
