### ISSUE TITLE
[Remoto] Front-End React Developer Part-Time na LocusPrime

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#3282]
## LocusPrime

A LocusPrime é uma plataforma de gestão que automatiza e integra todos os setores do seu negócio no setor da saúde, Bem-estar e Beleza. Somos obcecados em automatizar e tornar fluido a jornada do paciente em consultórios e clínicas médicas. 

## Descrição da vaga

Buscamos por uma Pessoa Desenvolvedora Front-End React Part-Time Home-Office dedicada e focada em resultados para integrar nosso time que está em crescimento.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- +2 anos de experiência em posição semelhante ou como freelancer
- Ser habituado no uso de NPM, Webpack e ESLint
- Sólida experiência em projetos React.js + Redux
- Fluente em Javascript
- Bom entendimento de cultura em startup (Lean Startup)
- Ser habituado com metodologias ágeis (Scrum e Agile)
- Disponibilidade de 20 a 30 horas por semana

**Diferenciais:**
- Trabalhar com Next.js
- Boas práticas em desenvolvimento orientado a SEO + Server Side Render (SSR)
- Trabalhe com React Native

**Atrativos:**
- 100% Home Office
- Contrato Flexível
- Horário Flexível - Part-Time

## Contratação

PJ a combinar

## Como se candidatar

Candidatar-se em: [https://bit.ly/3iB73g8](https://bit.ly/3iB73g8)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 48 horas após cada etapa do processo.
E-mail para contato em caso de não haver resposta: contato@coodesh.com (edited) 

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by JuhVieira** [comment]
O formulario ta com erro;

**Comment by FrancieleGhizzoni** [comment]
Estamos no processo de seleção e verificação dos perfis
