### ISSUE TITLE
[Curitiba/Remote] Senior FullStack React.js+Koa.js na Visionnaire

### ISSUE THREAD

**Issue by raulbalestra** [frontendbr/vagas#3288]
Olá a todos,

Estamos a procura de um profissional SR. React.js+Koa.js

Business
a marketing platform that helps customers to understand and optimize the text by finding out which information is interesting to the audience.

The lead has a team of 3 engineers from Belarus.
 
Requirements
The customer is looking for a colocated (!!!) team of **2** Senior engineers with **React.js**, **Koa.js** and **MongoDB**. The main tasks are to work with backlog tasks.

From the soft-skills the lead requires engineers' proactivity, being able to provide their own suggestions and solutions. 

The developers will be managed by the CTO directly so **Upper-Intermediate English** is mandatory.

Timeframe & Budget
Start: **asap**
Duration: 2-3 months of probation, possibility of ongoing collaboration.

Budget: 16k PJ

Como se candidatar:
Por favor envie um email para raul.balestra@visionnaire.com.br com seu CV anexado - enviar no assunto: Senior FullStack React.js+Koa.js

Alocação:
Alocado ou Remoto
Regime:
PJ
Nível:
Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
