### ISSUE TITLE
[São Paulo] Front-End Developer na Photongroup

### ISSUE THREAD

**Issue by bdmstyle** [frontendbr/vagas#329]
# Frond-end Developer Photon Group [Iridium Labs]

A Photon Group é uma startup que fabrica produtos para o mundo fitness.
Possuimos grandes marcas como a Iridium Labs que é uma das maiores empresas de suplementos no Brasil.

Arnold Classic South America 2017
<img src="https://scontent.fcgh5-1.fna.fbcdn.net/v/t31.0-8/18216721_10211100759492930_4925833912023247752_o.jpg?oh=a62f6caff15ce7b240b5ba5d58ef9619&oe=598BCB85" >

Alguns de nossos produtos

https://www.kimeraoficial.com.br/

https://www.somaprowoman.com.br/

Nossa loja 

https://loja.feitodeiridium.com.br/

**Contratação**: CLT + benefícios

#### Time

Nossa equipe é agil, altamente qualificada, valorizamos código de qualidade, automação de tarefas e pessoas que agreguem experiências/conhecimento assim como estejam dispostas a aprender.

#### Ambiente

Nossa empresa tem um ambiente descontraído, horário flexível e o melhor de tudo "No dress code" ou seja sua bermuda é bem vinda aqui \o/.

<img src="https://scontent.fgru3-1.fna.fbcdn.net/v/t31.0-8/18238729_10211101260705460_4218306443619147204_o.jpg?oh=9f22aa6891f98203ca93e555b33775e8&oe=59BDEBD5" >

#### Sua responsabilidade
Evolução de nossas plataformas usando as melhores práticas. Na maior parte do tempo usará:

- Html5
- CSS3 
- AngularJs 
- Grunt 
- Sass 
- JQuery 
- Github

#### Requisitos minimos

- Muito experiente em HTML5, CSS3.
- Ser um cara bom em Javascript
- Mentalidade Mobile-First para design responsivo
- Conhecimento de frameworks e ferramentas modernas (Less/Sass,Grunt,Gulp, Angular etc..).
- Proficiente com Photoshop, capacidade de traduzir layers em código.
- Git

#### Diferenciais

- Conhecer o protocolo HTTP.
- Experiência em otimizar webapps
- Experiência com SEO e UX/UI
- Conhecimentos em SQL (Básico)

#### Onde você vai trabalhar?

* Linda Casa na rua Luís Anhaia 77 - Vila madalena, São Paulo - SP, 05433-020.

<img src="https://scontent.fgru3-1.fna.fbcdn.net/v/t31.0-8/18216769_10211101321906990_6294130786708364640_o.jpg?oh=fe7bb456529ccf9ae913c13990f69d15&oe=59C0DAF3" >

#### Salário

* Salário compatível com o mercado,seu conhecimento e experiência.

#### Benefícios

* Regime CLT, 40 horas semanais
* Vale alimentação ou refeição
* Plano de saúde

#### Vamos Conversar!

Envie um email para `vagas@photongroup.com`

Assunto **[VAGA] Desenvolvedor Front-end** com as informações:

* Currículo ou Linkedin
* Pretensão salarial
* Github e/ou Blog - Vai nos ajudar a conhecer você e seu trabalho melhor :)

**Comment by bcarvalho89** [comment]
Alguma change de remoto?

**Comment by bdmstyle** [comment]
Não é remoto, fazemos home office esporadicamente.

**Comment by brunooomelo** [comment]
Enviado :)

**Comment by bdmstyle** [comment]
Done!
