### ISSUE TITLE
[Remoto] Vue.js Front-end Developer Jr/Pleno na BuildGroup (EUA)

### ISSUE THREAD

**Issue by juliovedovatto** [frontendbr/vagas#3299]
## Nossa empresa

A BuildGroup é uma empresa situada em Austin - Texas, desenvolvendo uma solução em Vue.JS para mercado de Investimento. Foi fundado por um antigo CEO da Rackspace, com um bom aporte de capital.

> At BGDS, our vision is to untap the economic welfare potential of technology through entrepreneurship. In order to fully realize our vision, we have committed ourselves the mission to provide transparency, openness, collaboration, ease-of-use and insights to technology startup financing so that entrepreneurship thrives globally, and founders can develop life-changing technologies.

## Descrição da vaga

Empresa está reformulando equipe de Front end e está na procure de profissionais de nílve Jr/Pleno para compor o quadro de funcionários. A pessoa será responsável por dar manutenção nos componentes existentes (Vue SFC standard), escrever testes (E2E e Unit Tests), além de criação de novas features. Tudo isso em cima de uma API REST.

Inglês técnico é requerido e inglês de conversação é diferencial (pelo menos entender o que for falado). Terá outros BR no grupo e o coordenador de projeto é um espanhol que passou 10 anos no Brazil, então sabe se comunicar muitíssimo bem.

*A Vaga tem diferencial de Python/Django, mas não é necessário ao desenvolvedor.*

> RESPONSIBILITIES AND DUTIES
> • Build interactive and thoughtful UIs in VueJS and Python that solve complex problems and are a delight to use
> • Build End-to-end ownership of major sections of our web user interface, new visualizations, and new reports
> • Contribute to creating view components and extend the company API
> • Participate in the conceptualization and wireframing of new interfaces
> • Prototyping and building clean and intuitive user interfaces through various iterations
> • Identify and troubleshoot UX problems (e.g. responsiveness, performance, usability, mobile)
> • You have feelings about how a webpage should look and feel and care about the nuances of how users will work with the product you’re building.
> • Ensuring implementations follow web standards, accessibility, and usability best practices
> • We able to test the Graphical User Interface (GUI), functionality and usability of a complex website, that involve checking functionalities like forms, graphs, menus, reports, etc. as well as associated Javascript
> • Our approach to supervision is very adaptive, which is to say that we are happy to accommodate a variety of personal styles. We are searching for someone who is an independent contributor, but you will also get the support you need when you need it

## Local

Remoto - seguindo fuso horário comercial do Texas (atualmente 2h de diferença)

## Requisitos

- Experiência em trabalho remoto - ser capaz de manter horário de trabalho e  ter curto tempo de resposta
- Formação na área
- Excelente conhecimento de HTML5/CSS/JS (ES5-ES10) e suas particularidades
- Experiência com construção de interfaces UI
- 1-3 anos de experiência com Vue.JS
- Experiência com API REST
- Experiência webpack e outros task managers
- Experiência com Git/Github

**Desejáveis:**
- Python
- Django
- SQL/NoSQL
- Web Components
- Inglês de conversação
- Experiência escrevendo testes E22 e Unit Tests
- Experiência com DevOps

**Diferenciais:**
- Ter  experiência de trabalho remoto para empresas fora do BR
- Bônus semestral
- Empresa disponibiliza Macbook para funcionário
- Possibilidade de viagem para os EUA para conhecer empresa e fazer um período de integração de equipe.

## Benefícios

* Feriados pagos - PTO (Paid Time Off) - tanto feriados BR como EUA, mas tem um limite de escolha de dias
* Ferias remuneradas
* Jornada 40h semanais

## Contratação

PJ

* USD 1.500 - Jr
* USD 2.500 - Pleno

## Como se candidatar

Por favor envie um email para `xalperte@buildgroupai.com` com seu CV anexado (em inglês) - enviar no assunto: `Vue.js developer opportunity`

## Labels

* Remoto
* Júnior
* Jr
* Pleno
* Vue.js
* Vue
* Javascript
* Front end

#### Alocação
- Remoto

#### Regime
- PJ  (MEI ou Simples)

#### Nível
- Júnior
- Pleno

**Comment by fogeid** [comment]
Boa vaga, queria ter o inglês melhor.

**Comment by FlapNips** [comment]
> Boa vaga, queria ter o inglês melhor.

Eu também ;(

**Comment by dbarjs** [comment]
@juliovedovatto valeu por compartilhar essa oportunidade!
A vaga se encaixa perfeitamente com o meu perfil e já enviei meu currículo, espero que dê certo!

**Comment by rodrigoronin** [comment]
A vaga ainda está aberta?

**Comment by juliovedovatto** [comment]
@rodrigoronin até começo da semana estava a berto ainda @rodrigoronin

**Comment by rodrigoronin** [comment]
> @rodrigoronin até começo da semana estava aberto ainda @rodrigoronin

Obrigado @juliovedovatto

**Comment by barcellos-pedro** [comment]
E-mail sent, thank you!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
