### ISSUE TITLE
[Belo Horizonte - MG] Desenvolvedor Front-end Pleno na BHTEC

### ISSUE THREAD

**Issue by skyzito** [frontendbr/vagas#33]
## Descrição da vaga

Vaga para Desenvolvedor Front-end Pleno em Belo Horizonte.

EMPRESA: BHTEC INTERNET MARKETING

## Local

Belo Horizonte , Minas Gerais , Bairro Floresta

## Requisitos

**Obrigatórios:**

- HTML5
- CSS3
- Javascript
- SASS
- Design responsivo
- Automatizadores
- Utilizar padrões e boas práticas para desenvolvimento
- Experiência com Controle de Versão (Git)

**Desejáveis:**

- Acessibilidade
- Angular.js
- ECMA 6
- Manipulação de SVGs
**Diferenciais:**

- projetos opensource

## Nossa empresa

Bhtec e:house
Desenvolvendo soluções digitais e produzindo resultados  há mais de 17 anos.

Nosso site: www.bhtec.com.br

## Como se candidatar

Não contratamos remoto.
Interessados devem enviar o CV para glauber.fontora@bhtec.com.br.

**Comment by LFeh** [comment]
@skyzito A vaga é remoto?

**Comment by skyzito** [comment]
@LFeh Opa , Alocado.

**Comment by candidodmv** [comment]
Boa empresa, recomendo!

**Comment by skyzito** [comment]
@candidodmv  Obrigado pela recomendação 👍

**Comment by LFeh** [comment]
A vaga foi preenchida?

**Comment by LFeh** [comment]
Como não teve respostas, vou fechar.

@skyzito Avisa se precisar abrir.

**Comment by camilatigre** [comment]
@skyzito 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by skyzito** [comment]
Olá , não foi não.

**Comment by camilatigre** [comment]
Ah ): obrigada por ajudar mesmo asdim

Em 24 de nov de 2016 10:46, "Diêgo Bolina" <notifications@github.com>
escreveu:
