### ISSUE TITLE
[Remoto / Barueri-SP] Frontend React Developer Júnior na Mindbe

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#3300]
## MindBe

Nascemos para trazer de volta a satisfação e a confiança das pessoas nas marcas e produtos que estão no mercado. Aqui na Mindbe somos antes de tudo criativos. Nosso trabalho é encontrar soluções que geram eficiência para as empresas, lançando um olhar estratégico para os processos do negócio, mas sem deixar de ver as reais necessidades e desejos das pessoas.

## Descrição da vaga

Estamos em busca de uma Pessoa Desenvolvedora Front-End React nível júnior com conhecimentos em HTML5, HTTP, JavaScript, Wordpress, Git, PHP, React.. Irá atuar com o desenvolvimento para sistema web.

## Local

Remoto ou SP, Barueri

## Requisitos

- Conhecimento em HTML5/CSS3
- Boa prática em HTTP
- Conhecimento em desenvolvimento front-end usando react.js
- Confortável com Javascript
- Contato com Wordpress

**Desejáveis:**
- Redux

**Diferenciais:**
- Conhecimento em PHP e/ou PHP + Laravel

## Benefícios

- Home Office

## Contratação

CLT

## Como se candidatar

Candidatar-se em: [https://bit.ly/38F8RjH](https://bit.ly/38F8RjH)

## Tempo médio de feedbacks

E-mail para contato em caso de não haver resposta: recrutamento@mindbe.com.br 
Assunto: Vaga:  Analista Frontend React Jr na Mindbe através da Plataforma Coodesh

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Júnior

**Comment by arthur-mts** [comment]
Possibilidade para estagio?

**Comment by gabrielhws** [comment]
@arthur-mts não tenho certeza. Melhor olhar diretamente com a responsável; : Thaysa Araujo - recrutamento@mindbe.com.br

**Comment by FeelipePM** [comment]
@gabrielhws a vaga já foi preenchida?
