### ISSUE TITLE
[Remoto] FullStack Developer na Cout

### ISSUE THREAD

**Issue by FigueiraIure** [frontendbr/vagas#3305]
## Cout App

Somos uma plataforma focada em Gestão de Processos Empresariais e nosso primeiro produto é uma ferramenta de gerenciamento de Escalas e Jornadas de trabalho. Nossa startup está em fase inicial mas conta com um primeiro investidor.

## Descrição da vaga

Desenvolvedor fullstack. Nossa stack atual é Vue/Laravel, mas estamos abertos para novas ideias.

## Local

Remoto

## Requisitos

**Obrigatórios:**
Front: Vue JS
Back: Laravel

## Benefícios
- Flexibilidade

**Diferenciais:**
- Equity

## Contratação

PJ a combinar

## Como se candidatar

Enviar um email para vagas@cout.app falando um pouco de suas habilidades, sua experiência e como pode somar com nosso time.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dia após cada processo.
E-mail para contato em caso de não haver resposta: dev@cout.app

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
