### ISSUE TITLE
[São Paulo] Front-end Developer Sênior na Doc88

### ISSUE THREAD

**Issue by lucasalvessantos** [frontendbr/vagas#3308]
Desenvolvedor Front-end Pleno/Sênior na DOC88

🧡 Nossa empresa
Nós da DOC88 temos grandes sonhos e desafios e sabemos que para chegarmos cada vez mais longe precisamos aumentar nossa grande família com uma pessoa desenvolvedora Front-End Sênior.

Nosso time multidisciplinar de Doctors (Front-End, Back-End, Infraestrutura, DevOps, UX/UI, etc) faz parte do grupo COMERC, eleita a melhor empresa de energia do Brasil.

Estamos no Itaim Bibi – São Paulo.

Missão do novo Doctor:

Desenvolver novas funcionalidades;
Manutenção de melhorias e correções de bugs;
Participação de reuniões de planejamento;
Apoio na elaboração, identificação de necessidades, desenho de soluções, priorização em backlog e apresentação para clientes;

Quer fazer parte da nossa equipe de Doctors? 🥰

🤝 Contratação
CLT - salário a combinar

📣 Requisitos e qualificações
JavaScript (ES6+);
CSS3 (Flexbox);
HTML5;
Vue.js ou React.js (preferência Vue.js);
Vuex ou Redux
Vue Router(ou React Router)
SASS, LESS, Stylus ou PostCSS;
Git (Fluxo Gitflow);
Experiência com aplicações escaláveis;
SO Linux;
Lints (Eslint, Stylelint…);
TDD (Jest, Mocha ou outro);
Integração com backend via APIs REST;
Inglês leitura e escrita;
Desenvolver código semanticamente correto e otimizado para SEO;
Gerenciadores de dependência e build (npm, yarn e etc);
Facilidade para trabalhar dentro de times multi-disciplinares;
Capacidade para escrever código consistente, eficiente e reutilizável (princípios OOP e de programação funcional).

🤓 Desejável
TypeScript;
Metodologia ágil (Scrum);
Node;
Build (Webpack, gulp ou outro);
GraphQL;
Atomic Design;
PWA;
Noções de UX e Design de Interação;
Docker;
Experiência com programação assíncrona (Promises, Generators, Streams);
Socket.io / Pusher.
CSS Grid
Design Patterns, SOLID, DRY, KISS
Flutter
React Native
Nuxt.js/Next.js
Express.js

🤩 Benefícios
Vale-transporte;
Vale-refeição;
Vale cultura;
Plano de saúde (Omint);
Plano odontológico (Omint);
14º salário;
Hora extra;
Subsídio academia;
Dress code flexível;
Bike friendly;
Ambiente agradável e descontraído com video-game (PS4), Free máquina de café, capuccino, chocolate, frutas, chás, biscoitos etc.
🚀 Como se candidatar
Mande um email para
lucas.santos@doc88.com.br

**Comment by thalesf** [comment]
@lucasalvessantos Apenas presencial ?

**Comment by lucasalvessantos** [comment]
@thalesf , apenas presencial. Talvez exista a possibilidade de ficar remoto durante a pandemia. Mas o foco da vaga é presencial mesmo.

**Comment by grsantos2215** [comment]
Existe possibilidade de estágio ?

**Comment by lucasalvessantos** [comment]
@grsantos2215 , infelizmente não temos vagas de estágio abertas no momento.

**Comment by lucasalvessantos** [comment]
A oportunidade ainda está aberta galera

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
