### ISSUE TITLE
[REMOTO] Full Stack Sênior Developer - Node.js e React Native na FindMe

### ISSUE THREAD

**Issue by findmesp** [frontendbr/vagas#3309]
## FindMe

A FindMe tem como visão revolucionar as operações do mercado de segurança e facilities. Hoje já são mais de 150 empresas otimizando milhares de postos em todo Brasil e Paraguai.

No entanto, no meio dessa jornada, descobrimos que podemos revolucionar a cada um de nós do time FindMe, construindo pessoas e profissionais extraordinários.

Mais detalhes sobre nossa solução pode ser visto em nosso site: www.findme.id 
E mais detalhes sobre nossa cultura em nosso Culture Code: bit.ly/culturafindme

## Descrição da vaga

Estamos construindo um novo time de produto sênior e multidisciplinar, atuando em engenharia, front-end, UX/UI e mobile, para construir a versão 3.0 de nosso produto, que será melhor plataforma de gestão operacional do mercado de segurança e facilities.

A construção dessa plataforma será baseada em 4 anos de operação e feedbacks contantes de mais de 150 empresas que são clientes da FindMe, monitorando mais de 5 mil funcionários diariamente em milhares de operações por todo Brasil, gerando milhares de dados a cada minuto.

Essa vaga dará oportunidade para o primeiro membro desse time, que pode ser você!

## Local

REMOTO

## Requisitos

**Obrigatórios:**
- Boa experiência em Node.js e React Native

**Desejáveis:**
- Postgrees, Mongo DB, Docker, Kubernetes, Microsserviços, Cloud e métodos ágeis.

**Diferenciais:**
- Projetos mobile e capacidade de liderança

## Contratação

PJ a combinar

## Como se candidatar

Por favor, preencha o formulário: www.findme.id/jobs

## Tempo médio de feedbacks

Temos um Programa de Desenvolvimento Individual (PDI), vinculado a suas metas e crescimento, com fluxos semanais de feedbacks e mentorias, cursos, tempo de trabalho dedicado e bônus mensais. Tudo isso para ciclos de promoção a cada 6 meses.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
