### ISSUE TITLE
[Remoto] Full-Stack Developer na Thunders Tecnologia

### ISSUE THREAD

**Issue by lucasbahiaa** [frontendbr/vagas#3310]
A Thunders é uma empresa líder no segmento ETRM (Energy Trading and Risk Management) com mais de 50 clientes do setor elétrico espalhados em várias regiões do país.

Nível: Sênior/Pleno
Local: **Remoto**
Requisitos: NET Core, ASP.NET Core, Testes de unidade e de integração, Injeção de Dependência, Padrões de Eventos
Diferencial: Angular 6+, Azure/Docke/Kubernetes, Microserviços, Infraestrutura como código.
Contratação: PJ
Expectativa Salarial: 8 a 10K

Mais informações sobre a vaga e Link de Inscrição:
**https://byintera.in/thundersfsgh**
Dúvidas:
https://www.linkedin.com/in/jessica-santana-96b5141a8/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
