### ISSUE TITLE
[Remoto] Front-end Developer na XP Investimentos

### ISSUE THREAD

**Issue by dzfweb** [frontendbr/vagas#3312]
> **Vaga Remota PARA SEMPRE**

## Nossa empresa

O nosso propósito é transformar o mercado financeiro para melhorar a vida das pessoas. Começamos em 2001, como um pequeno escritório de agentes autônomos de investimentos em Porto Alegre. Chegamos até aqui com a dedicação de pessoas talentosas que, por meio da nossa cultura de Sonho Grande, Mente Aberta e Espírito Empreendedor, tiveram a autonomia e liberdade que precisavam para transformar o mercado financeiro.

Porém, sabemos que o desafio é muito maior. Os grandes bancos ainda possuem 95% do mercado de investimentos no Brasil, mas estamos aqui para romper essa lógica e melhorar a vida de muito mais pessoas. Somos exatamente o que o sistema financeiro nunca foi.

Se você se identifica com esses conceitos e deseja construir algo especial, mergulhe de cabeça nesta oportunidade.

## Descrição da vaga

Como Pessoa Engenheira de Software da squad DX Wealth Services, você ajudará a cuidar de toda a experiência do cliente no produto de Wealth Services, criando sistemas robustos que gerem valor e escalabilidade para o negócio. 

Somos uma empresa em construção, então aqui o aprendizado é constante e você terá pista livre para criar e muitos (muitos mesmo!) desafios. Além disso, você trabalhará ao lado de pessoas diversas e talentosas que irão te ajudar a usar todo o seu potencial e gerar o maior impacto possível. 

Alguns dos desafios que você vai encarar:   

Desenvolver sistemas com tecnologia de ponta, serviços escaláveis e de alta resiliência;
Aprender sobre os produtos de mercado financeiro;
Incentivar e melhorar as práticas ágeis.
Sobre o ambiente de trabalho, é importante você saber que:

Nossa cultura de mente aberta torna o ambiente horizontal para que as decisões sejam tomadas com base em fatos e dados, colocando os interesses dos clientes sempre em primeiro lugar.
Com espírito empreendedor, cada um de nós protagoniza a sua própria história, então não espere encontrar uma empresa que tome decisões por você.
Apesar de todos terem autonomia para assumir as rédeas da própria vida, a nossa rotina é intensa por sonharmos grande e amarmos o que fazemos.

## Local

Remoto, #XPAnyWhere

## Requisitos

**Obrigatórios:**

- Ter a nossa cultura  
- React + TypeScript; 
- .NET
- Clean Code + SOLID + DDD + Design Patterns;
- Bancos de dados NoSQL e SQL;
- Testes de unidade / integrados / performance;
- Conhecimento prático de metodologias ágeis

**Desejáveis:**

- Inglês (reading and listening)  
- Atomic Design;
- Conceitos DevOps;
- Azure (Service Bus, Service Fabric etc.);
- Cloud Native Patterns (Circuit Breaker, CQRS, Feature Flag, Event Sourcing, Healthcheck, Anti Corruption Layer, BFF)

## Benefícios

- Plano de saúde
- Seguro de vida
- VR e VA
- Auxílio creche
- Auxilio academia
- Auxilio home-office (para estruturar seu escritório)
- Participação nos lucros (PLR) semestral

## Contratação

CLT

## Como se candidatar

Por favor envie um email para douglas.franco@xpi.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Engineer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by Jason-Alves** [comment]
Vocês teriam algum banco de vagas de tecnologia para consultar oportunidades para outros níveis?

**Comment by dzfweb** [comment]
> Vocês teriam algum banco de vagas de tecnologia para consultar oportunidades para outros níveis?

Aqui você pode consultar todas as vagas, mas sinta-se livre para me mandar eu CV também, temos muitas oportunidades.

https://www.xpinc.com/carreiras/#/tecnologia

**Comment by lucasferreiralimax** [comment]
Não tenho os conhecimentos de db e backend, mas mesmo assim enviei meu currículo para apreciação e analise.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by dzfweb** [comment]
> Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

Está aberta ainda
