### ISSUE TITLE
[São Paulo] Engenheiro de Software - Frontend Pl/Sr no PagSeguro 

### ISSUE THREAD

**Issue by fernandapmartinz** [frontendbr/vagas#3313]
> Vaga Remota durante a pandemia

## Nossa empresa

O PagSeguro foi criado para oferecer soluções inovadoras, simples e seguras em meios de pagamento. Trabalhando conosco, você tem a oportunidade de fazer a diferença na vida de milhões de brasileiros e construir novas formas de se fazer e receber pagamentos.
Trabalhamos em times multidisciplinares e cultivamos uma filosofia de trabalho ágil e enxuta, com as áreas de Tecnologia e de Negócios trabalhando lado a lado para criar produtos que evoluam de forma iterativa para entregar valor aos clientes.

## Descrição da vaga

Avaliar, discutir e definir arquitetura de sistemas e propor melhorias, promovendo a coesão técnica e consistência dos processos de negócio e apresentando alternativas para os diversos desafios​;
Trabalhar em equipes de alto nível. Adoramos métodos ágeis e estamos sempre em busca de melhoria contínua;
Trabalhar com técnicas e ferramentas de automação de testes;
Participar da pesquisa e implantação de novas tecnologias;
Cuidar da monitoração do ambiente e criar ações proativas que garantam a sua estabilidade;
Manter contato estreito com a equipe de segurança para garantir a confiabilidade dos sistemas.

## Local

São Paulo/SP - Bairro: Faria Lima

## Requisitos

Experiência na criação de páginas responsivas/mobile;
Experiência em desenvolvimento de aplicações web utilizando Javascript avançado (OO, herança, prototipação, design pattern, jQuery, etc.);
Experiência em CSS3​, SASS e LESS;
Conhecimentos em arquitetura backend (servidor web, BFF e Node.js);
Experiência em testes utilizando Jasmine, Karma, Cypress, etc;
Experiência em React e Vue;
Conhecimento de AngularJS.

**Desejável**

Conhecimentos relacionados à performance (gzip, minify, etc.) ​;
Conhecimento em ferramentas de construção: GruntJS e/ou Gulp;
Conhecimento de GraphQL;
Conhecimento em ferramenta de CD/CI. Ex: Jenkins; ​
Conhecimento em desenvolvimento em PWA e React Native;
Experiência profissional com métodos ágeis, como Scrum e Kanban;
Conhecimento em Docker.

## Como se candidatar

Por favor envie um email para fmartinz@uolinc.com com seu CV anexado - enviar no assunto: Vaga FRONTEND

**Comment by fernandapmartinz** [comment]
a vaga não é remota, somente remota durante a pandemia

**Comment by Rodzman** [comment]
Pessoal,

Trabalho no PagSeguro e super recomendo essa vaga. Se tiverem dúvidas e quiserem me perguntar, fiquem a vontade pra me procurar diretamente.

Abs

**Comment by lucasferreiralimax** [comment]
Não tenho os conhecimentos de backend, mas enviei meu currículo para apreciação e analise.
