### ISSUE TITLE
[Rio de Janeiro] Front-end Developer na Consultoria MP

### ISSUE THREAD

**Issue by Mari-Ana-RH** [frontendbr/vagas#3315]
> Vaga Remota durante a pandemia

## Nossa empresa

Atuamos em uma consultoria em busca de profissionais para uma empresa do ramo educacional. Eles possuem mais de 20 anos nessa área e enxergam a área de Desenvolvimento como uma setor chave da empresa. Desejam ter grandes aprovações e com isso vestem a camisa para entregar valor ao nosso aluno. Tudo o que fazem e a  própria existência se baseia na crença de desafiar o STATUS QUO e PENSAR DIFERENTE.

## Descrição da vaga

Buscamos um Front-End Developer, mas que possuam mais familiaridade com programação e suas nuances. A atuação será com JavaScritp e Angular promovendo a comunicação com os APIs. Há possibilidade de atuar com mobile e website em diversos projetos internos. Terá atuação com time multidisciplinar.
Fixo no Rio de Janeiro, mas vaga aberta para todos os estados.

## Local

Exemplo: Remoto ou Escritório, [Rio de Janeiro], [Rio de Janeiro], [Barra da Tijuca]

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com JavaScript
- 2 anos de experiência com Angular e Ionic
- Experiência com Testes Unitários. Componentes e Programação orientada a Objeto

**Desejáveis:**
- conhecimentos em Metodologia ágil

**Diferenciais:**
- conhecimento Jasmine/Karma
- conhecimento Git/Github

**Diferenciais da vaga:**
- Variedade de projetos (mobile, desktop e websites)
- Uso de tecnologia de ponta
- ...

## Contratação

PJ com faixa de 70 à 100 reais hora/homem (será avaliado técnicamente)

## Como se candidatar

Por favor envie um email para desenvolvedorpj@gmail.com com seu CV anexado - enviar no assunto: Vaga Front-end Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: desenvolvedorpj@gmail.com

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
