### ISSUE TITLE
[Remoto] Vue.js Developer na DialHost

### ISSUE THREAD

**Issue by flaviohcardoso** [frontendbr/vagas#3316]
## Descrição da vaga

Se você é um desenvolvedor faminto por desenvolver e otimizar produtos em um processo de ciclo contínuo e evolutivo, esta pode ser sua equipe.

Nós somos uma empresa que presa a evolução dos nossos produtos juntamente com um atendimento eficaz a todos os nossos clientes oferecendo soluções de datacenter que atendam suas necessidades de forma simples e transparente. Por isto estamos buscando um desenvolvedor que possua empatia e comprometimento para auxiliar nossos colaboradores e clientes discutindo e buscando as melhores opções para garantir uma experiência excepcional no atendimento ao cliente. 

Acreditamos que em nosso time, você não trabalhará sozinho e que um problema nunca é somente de um colaborador, ele é de todos da empresa.

## Local

Remoto

## Benefícios

Não ter chefe :)
Uma equipe de alto nível, comprometidas e colaborativa.
Salário compatível com o mercado.
Plano de Saúde.
Vale Refeição.
Vale Transporte.
Lanche na empresa.
Ambiente agradável.
Horário Flexível.
Estilo próprio para trabalhar.
Auxilio para pagar sua faculdade.
Diversos cursos online disponibilizados pela empresa.

## Requisitos

- HTML, CSS, Sass e JavaScript;
- Frameworks frontend (Vue.JS);
- Conhecimento basico em PHP;
- Ser focado em objetivos e resultados.
- WebPack para automação na compilação de assets;
- Experiência com utilização do Git;
- Proatividade e dinamismo ;)
- Ter carinho e ser apaixonado pelo seu trabalho.

## O que pode fazer diferença

- Inglês Intermediário;
- Noções de otimização de performance web;
- Otimização de código para SEO;
- Laravel;

**Para esta vaga iremos aplicar um teste simples e prático para que você possa demonstrar suas qualidades.**

## Contratação

PJ (Remoto)

## Como se candidatar

https://www.dialhost.com.br/trabalhe-conosco/vaga/vue-js-developer/

## Labels

- PJ
- Remoto
- Júnior
- Pleno

**Comment by EdvaldoLima** [comment]
Enviado.

**Comment by gqueiroz1** [comment]
Enviado.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
