### ISSUE TITLE
[Remoto] Front-End Developer na Deal Technologies

### ISSUE THREAD

**Issue by zeyuri** [frontendbr/vagas#3318]
## A Deal Techonologies

A Deal Techonologies é uma empresa de consultoria digital que trabalha com transformação digital em diversos parceiros e big players no mercado.

## Descrição da vaga
Buscamos um desenvolvedor front-end que tenha vontade de criar experiências pro usuário de qualidade e que não tenha medo de propor soluções, mudanças e ideias diferentes buscando a solução de nossos problemas. Você trabalhará em projetos relacionados a fidelização e loyalty em uma das empresas referências no mercado no Brazil. 

## Local

Remoto ou Escritório em Curitiba/PR. Fica a seu critério

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com HTML5, CSS e Javascript
- 2 anos de experiência com React
- Experiência com RESTFull Design Patterns
- Vivência em metodologias Ágeis e scrum
- Versionamento em Git
- Conhecimento em Web Standards(W3C) e Acessibilidade 

**Desejáveis:**
- NodeJS
- MongoDb
- Integração continua
- Jest/Cypress
- Cloud, serviços PAAS (Service BUS, API Manager, Fila)
- Experiência em aplicações de alta performance
- Identity Server (AWS Cognito / Azure AD B2C)

**Diferenciais:**
- projetos opensource

## Benefícios

- Salário altamente competitivo
- Plano Odontológico
- Plano de Saúde

**Diferenciais:**
- Flexibilidade de horário
- Treinamentos internos e externos

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para deal.recrutamento@deal.com.br com seu CV anexado - enviar no assunto: Vaga Front-end React

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7dias após cada processo.
E-mail para contato em caso de não haver resposta:  jose.cunha@deal.com.br

#### Alocação
- Remoto ou Presencial

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
