### ISSUE TITLE
[Joinville/SC] - Front-End Developer na ContaAzul

### ISSUE THREAD

**Issue by fernahh** [frontendbr/vagas#332]
## Descrição da vaga

E aí pessoal, tudo certo?

Precisamos de front-end developers na [ContaAzul](https://contaazul.com/), pleno e sênior. Estamos desenvolvendo uma das maiores plataformas SaaS do Brasil, onde enfrentamos vários desafios de como escalar uma aplicação e manter consistência de nossas UI em diferentes produtos para micro e pequenos empreendedores.

Temos vagas para diversos times, que funcionam de forma multidisciplinares, onde você irá trabalhar com designers, back-end, ops, etc.

> https://github.com/contaazul

## Local

Alocado no escritório, em [Joinville, SC](https://contaazul.com/carreiras/sobre-joinville/) (uma das melhores cidades do Brasil pra se viver, só dar uma _googlada_).

> https://contaazul.com/carreiras/sobre-joinville/

## Benefícios

- Um ambiente de trabalho diferente e inovador, com uma cultura que valoriza as pessoas e a entrega de resultados;
- Autonomia e flexibilidade;
- Cozinha sempre abastecida com lanches **ilimitados**;
- Salário compatível, acima da média do mercado;
- Ticket refeição/alimentação;
- Auxílio financeiro para gradução e pós-graduação;
- Ajuda financeira para aprender inglês;
- Afiliação com farmácias;
- Plano de saúde completo e **sem desconto** no seu salário;
- Plano odontológico completo e **sem desconto** em seu salário;
- Ajuda financeira para atividades físicas;
- Uma equipe que tem nossos valores em seu DNA;
- Vivendo em uma das melhores cidades para viver no Brasil;
- Acesso a livros e outros materiais;
- Assistência em Transporte.

> https://contaazul.com/carreiras/beneficios/

## Requisitos

- Conhecimento de padrões de desenvolvimento, como SOLID, Clean Code e Design Patterns e TDD;
- Experiência com arquitetura Front-end, usabilidade, desempenho e testabilidade;
- Experiência com tecnologias JavaScript (frameworks, node.js, etc);
- Experiência com CSS, e algum pré-processador de CSS em grande escala;
- Experiência com SPA;
- Experiência com ferramentas de automação front-end como Gulp ou Webpack.

> https://jobs.lever.co/contaazul/860aa08b-d4ba-4f54-86bd-66bd5a37d6b9

## Contratação

CLT.

## Nossa empresa

A ContaAzul é startup que nasceu em 2007 e hoje tem um dos maiores sistemas SaaS do Brasil. Aqui temos especialistas de diversas áreas (front-end, back-end, design, UX, marketing, etc) que trabalham com o objetivo de criar soluções para facilitar a vida dos micros e pequenos empresários. 

Há pouco tempo, ela ficou entre as [10 empresas mais amadas por seus funcionários, segundo a Love Mondays](https://noticias.contaazul.com/ranking-love-mondays-contaazul-entre-as-10-empresas-mais-amadas-por-seus-funcion%C3%A1rios-f11ed6f7ad28). Temos diversas guildas que tem uma forte influência sobre as decisões de nossos produtos. 

Se quiser ler um pouco sobre o que fazemos aqui, recém lançamos o [blog da nossa engenharia](https://engineering.contaazul.com/).

> https://contaazul.com/carreiras/

## Como se candidatar

Só se aplicar na [página da vaga](https://jobs.lever.co/contaazul/860aa08b-d4ba-4f54-86bd-66bd5a37d6b9). Caso queira trocar uma ideia sobre como é trabalhar aqui, sinta-se a vontade pra falar comigo também :)

**Comment by jotavejv** [comment]
Enviado :)

**Comment by Josue23** [comment]
O Aurélio falou da experiência que ele teve trabalhando na ContaAzul
http://aurelio.net/blog/2017/02/06/contaazul/

É bom pra que quiser saber como é o ambiente da empresa
Abs!
:-)

2017-05-09 21:20 GMT-03:00 João Victor <notifications@github.com>:

**Comment by fernahh** [comment]
> O Aurélio falou da experiência que ele teve trabalhando na ContaAzul
> http://aurelio.net/blog/2017/02/06/contaazul/
> É bom pra que quiser saber como é o ambiente da empresa

Esse post é bem sincero e muito bom! :tada:

**Comment by xereda** [comment]
> O Aurélio falou da experiência que ele teve trabalhando na ContaAzul
> http://aurelio.net/blog/2017/02/06/contaazul/
> É bom pra que quiser saber como é o ambiente da empresa

Sensacional essa história @Josue23 e @fernahh.

**Comment by diegocandido** [comment]
Sensacional o texto do Aurélio, exatamente como me sinto hoje ao fazer um teste em uma startup. O "tio da Sukita" (não tenho 40 anos), mas a tecnologia está tão volátil que... enfim! Vamos nos adaptar, e torcer que as empresas mesclem os dois mundos, algo raro hoje em dia, a maioria prefere os "garotinhos" de programa! 😉

**Comment by fysp11** [comment]
@diegocandido, mesclar normalmente dá certo. Mas cuidado com os termos. Pode soar pejorativo mesmo sem ter a intenção. Aqui, assim como em muitos lugares, o que você fala é normalmente entendido como o que pensa! ;)

**Comment by raloliver** [comment]
Aquele momento em que você lê isso e pensa: por que eu não fui pra Joinville antes?

**Comment by mateussmohamed** [comment]
@fernahh gostaria de saber se o conta azul tem algum auxilio de moradio, algo do tipo, caso o candidato aprovado more em outro estado?

**Comment by fernahh** [comment]
> @mateussmohamed gostaria de saber se o conta azul tem algum auxilio de moradio, algo do tipo, caso o candidato aprovado more em outro estado?

Humm, acho que tem um auxílio mudança. :thinking: 

Não posso falar com certeza quais são as ajudas nesses casos, mas se tu aplicar teu currículo, o pessoal do RH vai te explicar isso direitinho.

**Comment by Josue23** [comment]
Luiz, se o pessoal do RH for atencioso como tu então deve ser bacana
trabalhar ai :-)

Em 10 de maio de 2017 22:29, Luiz Fernando Rodrigues <
notifications@github.com> escreveu:

**Comment by fernahh** [comment]
> @Josue23 Luiz, se o pessoal do RH for atencioso como tu então deve ser bacana trabalhar ai :-)

Galera do RH mandou recado pra comunidade **Front-End Brasil**!

![img_0129 1](https://cloud.githubusercontent.com/assets/2369851/25969626/f77bb98e-366b-11e7-91ac-25a0cef91334.jpg)

**Comment by uselessdev** [comment]
Aplicado :tada:

**Comment by LFeh** [comment]
Sensacional @fernahh hahaha

**Comment by Josue23** [comment]
Hahaha!!
Tu mandou bem @fernahh

2017-05-11 18:02 GMT-03:00 Felipe Fialho <notifications@github.com>:

**Comment by harrysbaraini** [comment]
Só pra informar: Joinville realmente está entre as melhores do país ;)
Quem chegar agora vai pegar mas obras de infraestrutura rolando, mas é pra ficar ainda melhor!

obs: não trabalho nem nunca trabalhei da CA, mas é destaque por aqui.

**Comment by kvnol** [comment]
Não estou pronto para essa vaga ainda, mas é um sonho que pode estar próximo!

**Comment by uselessdev** [comment]
@fernahh essa vaga ainda está aberta?

**Comment by fernahh** [comment]
@uselessdev  essa vaga ainda está aberta?

Está sim.

**Comment by harrysbaraini** [comment]
Pra quem não é de Joinville, não deixe de ver https://youtu.be/WE29MdRMLBc, os belo documentário sobre essa wonderful city!

**Comment by mtmr0x** [comment]
@fernahh a vaga continua aberta?

**Comment by fernahh** [comment]
> @mtmr0x a vaga continua aberta?

Conversei com o pessoal aqui e não tem mais vaga ativa, mas em breve vamos abrir mais. Sendo assim, vou fechar aqui e publico de novo se abrir mais.
