### ISSUE TITLE
[Remoto] Front end Developer Sr. na Byne

### ISSUE THREAD

**Issue by alicepantoja97** [frontendbr/vagas#3321]
>Vaga Remota 
>Senior

## Nossa empresa

Somos uma empresa nacional, criada há mais de 10 anos, com o objetivo de descomplicar ambientes críticos de operação.

Com foco na experiência do usuário, acreditamos que exercer diversas tarefas ao mesmo tempo não precisa gerar estresse.

Excesso de ferramentas e plataformas torna o processo complexo e suscetível a falhas. Podemos fazer mais simples.

Queremos fazer diferente. E melhor.

## Descrição da vaga

Nossa solução é utilizada por clientes em atividades importantes e em momentos de crise, quando dependem dele para se comunicar, fazer negócios ou resolver situações emergenciais.
Por isso esperam uma interface simples, intuitiva e funcional.
Nos orgulhamos de oferecer recursos avançados de comunicação, monitoramento e controle, em uma tela acessível e agradável, com feedback em tempo real, oferecendo a segurança necessária ao usuário.

Estamos trabalhando em novas versões Web e Mobile de nosso produto e buscamos alguém com experiência e habilidade para colaborar com designers e desenvolvedores de backend no desenvolvimento de produtos e funcionalidades para uma melhor experiência do usuário.

É seu papel encorajar e participar no desenvolvimento de boas práticas de desenvolvimento de tecnologia Web based e contribuir com a equipe em questões relacionadas a engenharia de UI, design de APIs e protocolos de comunicação com o backend.

## Local

Florianópolis,  Acate - SC | Home Office durante a pandemia e depois também!

## Requisitos

**Obrigatórios:**
Framework React ou similares
Framework React Native ou similares
Javascript(ES6+)
Pré-processadores CSS como LESS e Sass
Frameworks de interface WEB responsiva: Bootstrap, Foundation.
Testes automatizados de interface

**Desejáveis:**
Experiência com interfaces nativas para dispositivos móveis: Android e iOS.

**Diferenciais:**
Experiência com BFF Pattern, GraphQL, arquitetura Flux e frameworks relacionados.

## Benefícios
A combinar de acordo com o contrato de trabalho

## Contratação
PJ ou CLT a combinar

## Como se candidatar

Por favor envie seu CV com prtensão salarial para recrutamento@rtm.net.br 😉😉😉

Não perca essa oportunidade!!!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
