### ISSUE TITLE
[São Paulo-SP] Front-end Developer na BRQ Digital Solutions

### ISSUE THREAD

**Issue by ReAnne123** [frontendbr/vagas#3327]
Descrição da vaga
Estamos em busca de profissional com experiência em Front para atuar em empresa de grande porte do segmento Financeiro. Prazo indeterminado de contratação com muita chance de crescimento.

Local
Durante o período da pandemia de Covid-19, será home office; normalizando, presencial na Faria Lima (estação de trem Cidade Jardim).

Benefícios
-vale refeição
-vale alimentação
-seguro de vida
-plano médico Bradesco
-previdência privada
-plano odontológico

Requisitos necessários:
-Angular 2+
-Typescript
-Git
-HTML
-SASS/SCSS
-NPM
-Domínio de integração com API`s

Contratação
CLT full pela BRQ.

Nossa empresa
Fundada em 1993, a BRQ Digital Solutions é uma das maiores empresas de serviços de TI do país. Conta com 2500 profissionais distribuídos nas filiais de São Paulo, Alphaville, Rio de Janeiro, Curitiba e Nova Iorque.

Como se candidatar
Por favor envie um email para Renata- ryokota@brq.com, com seu CV anexado - enviar no assunto: Vaga Front.

Tempo médio de feedbacks
Costumamos enviar feedbacks em até 30 dias após cada processo.
E-mail para contato em caso de não haver resposta: ryokota@brq.com

Alocação
- Alocado

Regime
- CLT

Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
