### ISSUE TITLE
[Remoto] Front-end Vue.js Developer at Tog Design

### ISSUE THREAD

**Issue by JanainaLudwig** [frontendbr/vagas#3328]
## Nossa empresa
We use the power of design to solve complex problems and transform business that become great stories.

## Descrição da vaga
This is a short-term european project; But after this trial, we look for someone that would like to have a long-term value exchange with Tog Design.

## Local
Remote

## Requisitos

**Obrigatórios:**
- Software Developer Front-End / +5 years experience
- Web development: Vue.js, TypeScript / +3 years experience;
- Flexibility with different timezone;
- Advanced English

**Desejáveis:**
- Mobile: Android development (Kotlin) and iOS Development (Swift);

## Contratação

PJ a combinar

## Como se candidatar
CV/Info Contact: daron@tog.design

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by pauladiniz** [comment]
Just applied!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
