### ISSUE TITLE
[São Paulo] Front-end Developer na MarketUp

### ISSUE THREAD

**Issue by NadineMelo** [frontendbr/vagas#3330]
Desenvolvedor Front-End

A MarketUP é uma startup inovadora sendo considerada uma das empresas com alto potencial para transformar o mercado brasileiro e está em busca de um novo talento para potencializar o time!!
Estamos trabalhando com a faixa salarial de R$5.000,00. 
 
O que esperamos de você:
 
•	Conhecimentos necessários: HTML5, CSS3, Less, Javascript
•	Conhecimentos desejáveis (diferencial mas opcionais): AngularJS, Angular 2+
•	Experiência: Mínimo de 2 anos e vivência no desenvolvimento envolvendo
 
Local: Bela Vista - São Paulo, SP

Enviar cv para: vagas@pgconsulting.com.br

**Comment by diogomoretti** [comment]
Por favor, colocar no modelo para que a vaga seja reaberta: https://github.com/frontendbr/vagas/blob/main/.github/ISSUE_TEMPLATE/adicionar-nova-vaga.md
