### ISSUE TITLE
[Remoto] Front-end Developer 

### ISSUE THREAD

**Issue by motajuliana** [frontendbr/vagas#3334]
> Vaga Remota durante a pandemia

## Nossa empresa

Seguimento de E-commerce 

## Local

Home office full time 

## Requisitos

É necessario ter conhecimento em Oracle ATG.
Node.JS
Integração SOAP
Integrações de APIs
Banco de dados: MySQL / SQL Server / Oracle ATG
Conhecimento em desenvolvimento de máquina virtual / painel / dashboard
JQuery, HTML5, CSS3, JS, GraphQL, Java, Js, Json, Endeca, Gradle, Liquibase, Weblogic, Apache. 

## Benefícios

Ajuda com AM, seguro de vida, VA

## Contratação

CLT

## Como se candidatar

Por favor envie um email para juliana.mota@genter.com.br com seu CV anexado e pretensão salarial - enviar no assunto: Vaga Front-end

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Qual o nome da empresa @motajuliana?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
