### ISSUE TITLE
[São Paulo] Senior FullStack Node.js & React Software Engineer na startup Colab

### ISSUE THREAD

**Issue by rodriguesvini** [frontendbr/vagas#3336]
### Empresa:
O Colab é uma startup que nasceu para ajudar os cidadãos a ter voz! Através de uma plataforma interativa, o Colab conecta cidadãos diretamente à construção de cidades melhores. Para os usuários, o aplicativo permite identificar e fiscalizar problemas, avaliar serviços e espaços públicos e participar de tomadas de decisão. Para o poder público, o Colab torna o atendimento mais transparente, a solução dos problemas mais eficiente e a administração das cidades mais inclusiva e participativa. O propósito do Colab é democratizar o protagonismo urbano, permitindo que todos possam praticar verdadeiramente a cidadania, da palma de sua mão, de onde estiver!

### Requisitos:
• Front-End: React, JavaScript (desejável contato com Typescript);
• Back-End: Node.js – servidor Express;
• Biblioteca de gerenciamento: Redux, Mobix ou Hooks;
• Banco de Dados: PostgreSQL;
• Experiência com computação em Cloud/Nuvem;
• Experiência com microsserviços e ambientes de alta performance/disponibilidade;

### Diferenciais: 
• Experiência de liderança de equipe(s)/projeto(s);
• Experiencia com soluções voltadas para governo, instituições públicas ou organizações de propósito social;
• Configuração e otimização de infraestrutura em nuvem (AWS);
• Contato com desenvolvimento mobile.

### Contratação:
• Regime PJ (com 13º, férias remuneradas e stock options);
• Preferencialmente presencial, em São Paulo. No momento, a operação está ocorrendo de forma 100% remota.
• A remuneração é competitiva, compatível ao nível Sênior, no entanto é confidencial.

### Informações Adicionais e Inscrição:
**Para conhecer mais da oportunidade e participar do processo com a gente, é só acessar: https://bit.ly/3eKAyZJ**

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
