### ISSUE TITLE
[Remoto] Full-stack developer Node.js e Ionic usando Angular

### ISSUE THREAD

**Issue by gustable42** [frontendbr/vagas#3337]
## Nossa empresa

Sou um desenvolvedor, que me uni junto com alguns colegas de trabalho para trabalhar com freelas.

## Descrição da vaga

A demanda está maior que nossa disponibilidade e gostaríamos de alguém pra trabalhar num projeto de um novo cliente; este projeto está bastante avançado, e precisamos finalizar tudo para colocá-lo em produção e prestar o suporte. O projeto é feito em Ionic para uma versão Mobile e outra Web do sistema, e o backend é feito todo em node.js usando a infraestrutura serverless da AWS.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência profissional com Ionic
- Experiência profissional com Node.js

**Diferenciais:**
- conhecimentos em React JS; este é um diferencial, pois parte da aplicação está desenvolvida em React JS, porém está quase finalizada, caso o candidato possua este diferencial, daremos preferência para a contratação dele.

## Benefícios

- Nenhum

**Diferenciais:**
- Nenhum

## Contratação

PJ

## Como se candidatar

Envie um email para gustablealves@gmail.com com o assunto "Vaga - full-stack"

## Tempo médio de feedbacks

Daremos um feedback no mesmo dia, no mais tardar, no dia seguinte caso enviem em um horário mais avançado da noite

## Labels
Angular, Ionic, Node.js, AWS, Serverless, React JS

#### Alocação
- Alocado
- Remoto

#### Regime
- Freela

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
