### ISSUE TITLE
[Florianópolis/Remoto] Full-stack developer na Datarisk 

### ISSUE THREAD

**Issue by gustavodgbernardo** [frontendbr/vagas#3339]
# Sobre a empresa: Datarisk
A Datarisk é uma empresa focada em resolver problemas utilizando as mais modernas ferramentas de machine learning.
Desenvolvemos produtos para análise de dados e imagens prevendo fraudes e inadimplências, otimizando cobranças e aumentando vendas.
Tornando o processo de decisão dos nossos clientes mais rápido, ágil e simples.
## Descrição: Qual será o seu papel?
Suas principais responsabilidades serão criar, manter, implantar nosso sistema de maneira geral, com foco princialmente no frontend, mas podendo atuar no backend em determinadas ocasiões.
## Esperamos que você tenha experiência com:
    * Bons conhecimentos em Javascript, HTML e CSS
    * Experiência com React
    * Experiência com NodeJS e express
    * Testes automatizados (unitários/integração/e2e)
    * Desenvolvimento, manutenção e operação de sistemas
    * Git
    * Boas práticas de programação
## Vamos ficar felizes se você conhecer:
    * Redux
    * GraphQL
    * Typescript
    * MaterialUI
    * Configuração de CI/CD
    * Docker
    * AWS
## Você vai amar trabalhar aqui se:
    * Gostar de ambiente de startup
    * Crescimento acelerado
    * Gostar de aprender
    * Trabalhar com foco em resultados
## Benefícios
    * Horário flexível
    * Trabalho remoto
## Informações Complementares:
    * Contratação tipo PJ;
    * Vaga presencial/remoto;
    * Estamos localizados no bairro Santa Mônica Florianópolis.
Envie seu currículo para [vagas.ti@datarisk.io](mailto:vagas.ti@datarisk.io)

**Comment by tiago123456789** [comment]
Boa tarde! A vaga ainda está em aberto?

**Comment by gustavodgbernardo** [comment]
> Boa tarde! A vaga ainda está em aberto?

Olá @tiago123456789  a vaga ainda está aberta sim. 

Abs

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
