### ISSUE TITLE
[Maringá/PR] - Front-End Developer na MATERA Systems

### ISSUE THREAD

**Issue by gss-patricia** [frontendbr/vagas#334]
## Descrição da vaga
Precisamos de front-end developers Pleno para a <a href="http://www.matera.com/br/" target="_blank">MATERA Systems</a>, para atuar com análise e desenvolvimento de Front-end em projetos para clientes internos e externos.

## Local
Maringá, Paraná -  Novo Centro (Zona 07).

## Benefícios
- Horário de trabalho flexível (40 hs semanais);
- Pacote de Benefícios Flexíveis + PLR (Plano de participação nos lucros e resultados).

## Requisitos
**Obrigatórios:**
- Experiência com XML/HTML/CSS/JavaScript;
- Experiência com ReactJS e/ou Redux;

**Desejáveis:**
- Experiência com Angular2; 
- Experiência NodeJS;
- Testes Unitários; 
- Familiaridade com SVN, Git e com ferramentas como Jira, Confluence, Jenkins e Stash;

**Diferenciais:**
- Projetos opensource
- Conhecimento intermediário de Java e serviços REST;

## Contratação

CLT

## Nossa empresa

A MATERA Systems, desde 1987, atua como fornecedora de soluções e serviços de TI para o mercado financeiro e corporativo, além de realizar o desenvolvimento de aplicativos e projetos. São marcas registradas da empresa investir constantemente em inovação e capacitação de seus profissionais e aliar a excelência técnica ao conhecimento de negócios. Possui mais de 400 profissionais e desde 2008 está no ranking da GPTW. Sedes: Campinas­SP, São Paulo­SP, Niterói­RJ e Maringá­PR

## Como se candidatar

Por favor envie um email para aline.vida@matera.com com seu CV anexado - enviar no assunto: Vaga Front-End Developer.

**Comment by uselessdev** [comment]
enviado :smile:
