### ISSUE TITLE
[Remoto/Presencial] Front-end Developer na ITeam

### ISSUE THREAD

**Issue by VivianeRHTI** [frontendbr/vagas#3340]
## Descrição da vaga

Desenvolvimento Front-end com Angular JS.

## Local

A princípio remoto e após pandemia será presencial.
Residir nas seguintes regiões: São Paulo-SP/ Recife-PE/ Rio de Janeiro-RJ/ Nova Lima-MG

## Requisitos

Experiência em desenvolvimentos Front End com Angular JS.
Desjável conhecimento em React e/ou Java Spring.

**Obrigatórios:**
 Inglês avançado para conversação - Contato direto com cliente nos EUA.
 Angular JS.

## Contratação

5 meses 
CLT + Benefícios

## Nossa empresa

Há mais de 15 anos presente no mercado, a ITeam oferece o comprometimento com o cliente.
Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 
O relacionamento da ITeam é baseado no amplo comprometimento com os valores e objetivos dos nossos Clientes, fornecendo soluções e serviços de TI que contribuam para a realização de seus objetivos.

## Como se candidatar

Envie um e-mail para viviane.pereira@iteam.inf.br com seu currículo atualizado e pretensão salarial - enviar no assunto: Vaga Front-Angular com inglês

## Labels

- 🏢 Horário comercial
- 🏢 Remoto e presencial
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ CLT

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
