### ISSUE TITLE
[São Paulo] Front-end Developer na Ânimo Creative

### ISSUE THREAD

**Issue by bkawakami** [frontendbr/vagas#3342]
> Vaga Remota durante a pandemia

## Ânimo Creative

Agência Ânimo Creative, uma agência focada em soluções digitais e com forte pegada de marketing digital situada em Santa Isabel, SP. Possuímos grandes clientes como CNA, Ultragaz dentre outros.

## Descrição da vaga

Buscamos um desenvolvedor front-end **pleno/sênior** com um bom contato(não precisa ser especialista em todos) nos principais frameworks(React, Vue e Angular) front atualmente utilizados e algum conhecimento em Wordpress.

O desenvolvedor será o principal ponto focal das demandas da agência, tendo a responsabilidade desde compreender a necessidade do cliente a ser desenvolvida até disponibilizar os projetos em produção, além disso terá um desenvolvedor **junior** para auxilia-lo.

É importante que tenha uma boa capacidade de estimar prazos e atende-los, umas vez que os prazos serão dados por total você.

Além disso, terá total espaço para desenhar o processo de recebimento de demanda e entrega.

## Local

Remoto, porém esporadicamente podem acontecer reuniões onde a presença pessoal será requisitada.

## Requisitos

**Obrigatórios:**
- 2 a 4 anos com experiência em desenvolvimento front.
- 2 a 4 anos com experiência em processos de deploy e disponibilização do projeto.

**Desejáveis:**
- Algum conhecimento em Vue, React ou Angular
- Conhecimentos em Wordpress
- Conhecimento com o versionador GIT
- Conhecimento no processo de deploy produtivo

**Diferenciais:**
- Conhecimento em NodeJS com Express
- Conhecimentos em Mongo
- Conhecimentos em MySQL
- Conhecimento em Linux

## Benefícios

Vaga PJ

**Diferenciais:**
- Trabalho totalmente HomeOffice, mesmo depois do final da quarentena

## Contratação

PJ, salário R$ 8.000,00

## Como se candidatar

Por favor envie um email para bruno@animocreative.com.br com seu CV anexado - enviar no assunto: Vaga Front Ânimo Creative

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
