### ISSUE TITLE
[REMOTE POSITION] Shopify Front-end Developer @ Prediktive

### ISSUE THREAD

**Issue by majobonel7** [frontendbr/vagas#3344]
We are looking for a **Shopify Front End Developer** based in Latin America to work on a short term project for one of our clients, a digital agency based in Boston, Massachusetts.

Our client’s website is one of the fastest on the entire Internet. They are looking for someone that wants the challenge of working with top-shelf design and hitting a mark higher than a typical agency. You will work with cool stuff, like Gatsby and Shopify Plus. You will work with a team that believes the way you become a great engineer is to try and be less bad every day.

Hundreds of millions of people use the projects they work on every month for very well known clients worldwide.

**Responsibilities**
- Develop websites for client and internal projects
- Consult on client project goals (technology stack, development workflow, QA process, deployment strategy, etc.)
- Handle multiple clients and internal projects simultaneously
- Work with UX and designers to produce tight, forward-thinking, responsive and scalable front-end experiences
- Build out custom Shopify themes and modifying pre-existing themes depending on the scope of the project
- Work with Project Management to scope new functionality requests and support Sales to scope new projects

**Requirements**
- Advanced Level of English
- Minimum of 2+ years experience working within the Shopify Plus platform, including knowledge of Slate / Themekit or similar
- 2+ years working with modern technologies such as HTML5 and CSS3 experience
- 2+ years experience working with Liquid, JavaScript, jQuery and AJAX as necessary
- Knowledge of Shopify Ajax API a plus, as well as experience configuring third-party apps
- Super troubleshooting and debugging skills

**Bonus Points**
- Bachelor’s Degree in Computer Science, Systems Engineering or related fields

### Please include my name, Maria Bonel, when applying and I'll get back to you as soon as possible!

#RemotePosition #FrontendDeveloper #Shopify

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
