### ISSUE TITLE
[Florianópolis - SC] Full Stack Developer at CodeFoundry (Angular and NestJS)

### ISSUE THREAD

**Issue by jeanpchr** [frontendbr/vagas#3345]
> Vaga Remota durante a pandemia

## Nossa empresa

CodeFoundry is a bespoke software development company based in Florianópolis, Brazil. Our focus is on web development (front and backend), computer vision and image processing. Our mission is to form a critical mass of excellent professionals in several different key fields for kickstarting disruptive ideas. 

## Descrição da vaga

We are seeking professionals who can support, maintain and grow a variety of products being developed by us and our South African partner Britehouse (Dimension Data). We expect you to be a pro-active, detail-oriented, self-motivated and self-managed person. Good English skills are required. Communication and organization skills are key, as it is expected that you interact constantly with peers to achieve your goals and that you report your progress to management with precision and clarity. Finally, we expect excellent work ethics, responsibility and commitment to deadlines. 

## Local

Our company is based in Florianópolis, however, employees are free to work remotely and relocation is not mandatory.

## Requisitos

**Obrigatórios:**
- Solid Angular skills
- Experience as a full stack developer

**Desejáveis:**
- TypeScript and modern JavaScript
- NestJS 
- NodeJS
- CSS (not just hacking it, but actually owning it)
- PostgreSQL
- MySQL
- MongoDB
- Docker
- Testing frameworks (Jest, Mocha, AVA, ...)
- Git
- Design libraries (Material, Ant Design, ...)

## Benefícios

- Remote work
- VR/VA
- Health Plan

## Contratação

- CLT: R$7.000,00 ~ R$8.500,00 
- PJ: R$10.000,00 ~ R$12.000,00 

## Como se candidatar

Please send an email to info@codefoundry.com.br with the subject line "Full Stack Developer na CodeFoundry (Angular and NestJS)", containing a copy of your CV.

## Tempo médio de feedbacks

You can expect to hear back from us within a maximum of two days.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by jeanpchr** [comment]
Ainda aberta, por favor manter.
