### ISSUE TITLE
[SÃO PAULO] Magento Front-end Developer na JUST DIGITAL

### ISSUE THREAD

**Issue by alicesrossi** [frontendbr/vagas#3346]
> Vaga Remota durante a pandemia

## Nossa empresa

Acreditamos no Design para criar experiências memoráveis em tudo o que fazemos e na engenharia de software para tornar isso possível.
Quando falamos em experiência para impactar pessoas, vemos isso nos produtos e serviços que entregamos, na relação com nossos clientes enquanto trabalham com a gente, quando os os clientes dos nossos clientes usam nossos produtos.

## Local

Escritório, Bela Vista - São Paulo

## Requisitos

**Obrigatórios:**
HTML5 / CSS3 / JS / pré-processadores;
Conhecimento avançado com Magento 2
Conhecimento prático do fluxo de versionamento com GIT;
Ótimo conhecimento em frameworks Javascript;
Consumos de API;
Testes unitários e comportamentais.

## Benefícios - para CLT
- Vale Refeição
- Vale Transporte
- Horário Flexível
- Frutas no escritório
- Home Office
- Assistência Médica e Odontológica
- Gympass
- Parceria com SESC 

## Contratação
CLT ou PJ

## Como se candidatar

Acesse o link e cadastre-se https://bityli.com/sF2rJ
Entraremos em contato o mais breve possivel

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
