### ISSUE TITLE
[Full Remoto] Front-end Developer na Softplan

### ISSUE THREAD

**Issue by Jungles22** [frontendbr/vagas#3348]
## Nossa empresa

A Softplan é uma das maiores empresas no desenvolvimento de software do Brasil. Suas soluções apoiam instituições públicas e privadas a aumentar eficiência operacional, reduzir despesas e melhorar a prestação de serviços aos cidadãos, com respostas mais rápidas e qualificadas. Com cerca de 1,7 mil colaboradores, 3,5 mil clientes e 30 anos de atuação, é reconhecida pelo pioneirismo do desenvolvimento do Sistema de Automação da Justiça (SAJ). Atualmente, é líder em soluções de transformação digital, analytics, e inteligência artificial para o ecossistema da Justiça. Por meio de uma ampla linha de produtos e serviços focados na eliminação do papel e na adoção do processo digital, atende aos segmentos de Tribunais, Procuradorias, Ministérios Públicos e Advocacia.
Novamente fomos certificados com selo GPTW em 2020.

## Descrição da vaga

Nesta posição você vai atuar num time de especialistas, objetivo é a evolução do nosso produto (SAJ - ele está indo para sua 6º versão).
Nela você vai definir a arquitetura e construir o frontend de sistemas e aplicações web e mobile, utilizando tecnologias atuais e atendendo requisitos de responsividade e acessibilidade na web, implementando códigos que sejam escaláveis, fáceis de manter, eficientes e elegantes;
Vai definir boas práticas, mantendo-se atualizado nas novas tecnologias de frontend e capacitando outros desenvolvedores;
Participar de projetos de desenvolvimento de novos softwares, avaliando os protótipos entregues pelo designer, planejando e implementando a estrutura e componentes da interface, utilizando para isso o framework de **javascript React;**
Participar de projetos de customização de softwares já existentes utilizando um framework interno, AngularJS ou React;
Apoiar e orientar a elaboração de rotinas automatizadas de testes, utilizando-se de ferramentas e padrões para os testes necessários;

## Local

100% remoto

## Requisitos

**Obrigatórios:**
Ser capaz de desenvolver uma SPA (Single Page Application) utilizando React;
Saber utilizar gerenciadores de estado da aplicação (Redux e etc);
Conhecimento em integrar as SPAs com REST APIs;
Experiência em testes unitários automatizados para a aplicação (Jest, Enzyme e etc);
Ter conhecimentos de arquitetura de software;
Conhecimento em controle de versão (Git);
Conhecimento em JavaScript e no framework ReactJs, incluindo conceitos de programação assíncrona, definições de escopo (clojures), componentização e ES6+;  
Conhecimentos avançado em HTML e CSS, incluindo conceitos de layout, compatibilidade entre browsers e acessibilidade;  
Conhecimento em paradigmas de orientação a objetos e funcional;  
Conhecimento em algumas das bibliotecas Webpack, Gulp ou Grunt;  
Conhecimento de técnicas e práticas de Clean Code;  
Experiência em equipes dinâmicas e metodologias de desenvolvimento ágeis;  

**Diferenciais:**

Conhecimento em GraphQL em alguma biblioteca de mercado (Apollo, Relay); 
Conhecimento em princípios de design de interação, UX e Design System;  
Conhecimento das diretrizes de interfaces da Google (Material Design);  
Conhecimento em bancos de dados relacionais e não relacionais;  
Conhecimento em outros frameworks JavaScript como Angular, Vue.js etc.  
Experiência em bancos de dados relacionais SQL Server/Oracle;

## Benefícios

- Plano de saúde Unimed
- Plano Odontológico
- VR ou VA
- Programa de Bônus
- Oportunidade de desenvolvimento, meet ups, cursos e treinamentos in-company;

**Diferenciais:**
- 2 horas de almoço ( ou você pode negociar com seu líder o horário)
- Acolhimento psicológico
-  Yoga e meditação

## Contratação

CLT

## Como se candidatar

Por favor envie um email para ana.h@softplan.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

#### Nível
- Sênior

**Comment by HenriqueACF** [comment]
estão aceitando pra JR?Em 24 de jul de 2020 11:19 AM, Jungles22 <notifications@github.com> escreveu:

Nossa empresa

A Softplan é uma das maiores empresas no desenvolvimento de software do Brasil. Suas soluções apoiam instituições públicas e privadas a aumentar eficiência operacional, reduzir despesas e melhorar a prestação de serviços aos cidadãos, com respostas mais rápidas e qualificadas. Com cerca de 1,7 mil colaboradores, 3,5 mil clientes e 30 anos de atuação, é reconhecida pelo pioneirismo do desenvolvimento do Sistema de Automação da Justiça (SAJ). Atualmente, é líder em soluções de transformação digital, analytics, e inteligência artificial para o ecossistema da Justiça. Por meio de uma ampla linha de produtos e serviços focados na eliminação do papel e na adoção do processo digital, atende aos segmentos de Tribunais, Procuradorias, Ministérios Públicos e Advocacia.

Novamente fomos certificados com selo GPTW em 2020.

Descrição da vaga

Nesta posição você vai atuar num time de especialistas, objetivo é a evolução do nosso produto (SAJ - ele está indo para sua 6º versão).

Nela você vai definir a arquitetura e construir o frontend de sistemas e aplicações web e mobile, utilizando tecnologias atuais e atendendo requisitos de responsividade e acessibilidade na web, implementando códigos que sejam escaláveis, fáceis de manter, eficientes e elegantes;

Vai definir boas práticas, mantendo-se atualizado nas novas tecnologias de frontend e capacitando outros desenvolvedores;

Participar de projetos de desenvolvimento de novos softwares, avaliando os protótipos entregues pelo designer, planejando e implementando a estrutura e componentes da interface, utilizando para isso o framework de javascript React;

Participar de projetos de customização de softwares já existentes utilizando um framework interno, AngularJS ou React;

Apoiar e orientar a elaboração de rotinas automatizadas de testes, utilizando-se de ferramentas e padrões para os testes necessários;

Local

100% remoto

Requisitos

Obrigatórios:

Ser capaz de desenvolver uma SPA (Single Page Application) utilizando React;

Saber utilizar gerenciadores de estado da aplicação (Redux e etc);

Conhecimento em integrar as SPAs com REST APIs;

Experiência em testes unitários automatizados para a aplicação (Jest, Enzyme e etc);

Ter conhecimentos de arquitetura de software;

Conhecimento em controle de versão (Git);

Conhecimento em JavaScript e no framework ReactJs, incluindo conceitos de programação assíncrona, definições de escopo (clojures), componentização e ES6+;

Conhecimentos avançado em HTML e CSS, incluindo conceitos de layout, compatibilidade entre browsers e acessibilidade;

Conhecimento em paradigmas de orientação a objetos e funcional;

Conhecimento em algumas das bibliotecas Webpack, Gulp ou Grunt;

Conhecimento de técnicas e práticas de Clean Code;

Experiência em equipes dinâmicas e metodologias de desenvolvimento ágeis;

Diferenciais:

Conhecimento em GraphQL em alguma biblioteca de mercado (Apollo, Relay);

Conhecimento em princípios de design de interação, UX e Design System;

Conhecimento das diretrizes de interfaces da Google (Material Design);

Conhecimento em bancos de dados relacionais e não relacionais;

Conhecimento em outros frameworks JavaScript como Angular, Vue.js etc.

Experiência em bancos de dados relacionais SQL Server/Oracle;

Benefícios

Plano de saúde UnimedPlano OdontológicoVR ou VAPrograma de BônusOportunidade de desenvolvimento, meet ups, cursos e treinamentos in-company;

Diferenciais:

2 horas de almoço ( ou você pode negociar com seu líder o horário)Acolhimento psicológicoYoga e meditação

Contratação

CLT

Como se candidatar

Por favor envie um email para ana.h@softplan.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

Nível

Sênior

**Comment by ejklock** [comment]
Existe alguma oportunidade para fullstack ou backend ?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
