### ISSUE TITLE
[Remoto] Front-end Developer @ Plugg.to

### ISSUE THREAD

**Issue by fabriciovieira** [frontendbr/vagas#3349]
## Nossa empresa

Plugg.To é um hub de integração de e-commerce que possibilita integrações rápidas e inteligentes entre plataformas de lojas virtuais, ERPs, Fornecedores e Marketplaces. Diversas ferramentas de automações são oferecidos pelas integrações para possibilitar que tarefas repetidas em um Marketplace específico sejam realizadas sem interferência manual.

A empresa, fundada no início 2013 recebeu investimento da Wayra e do Fundo de investimento MercadoLivre no início de 2015 e desde então não para de crescer.

## Descrição da vaga

Estamos buscando um(a) profissional de Front-end para compor nosso time de desenvolvedores. O(a) profissional vai participar junto com os times de produto e desenvolvimento back-end na evolução das interfaces atuais e construção dos novos produtos web e mobile. 

É imprescindível o conhecimento em boas práticas para desenvolvimento web, Vue.js e integração de APIs.

## Local

Remoto

## Requisitos

**Obrigatórios:**	
- Sólidos conhecimentos em desenvolvimento web (HTML, CSS, javascript);
- Experiência com o framework Vue.js;
- Experiência com APIs RESTful;
- Experiência e conhecimento em UX e UI para construção e evolução da plataforma
- Experiência com ferramentas de versionamento: Git.

**Desejáveis:**
- Conhecimentos em React Nativo ou outro framework para desenvolvimento mobile;
- Conhecimento do framework Laravel.

## Contratação

PJ

## Como se candidatar

Por favor envie um email para fabricio.vieira@plugg.to com seu CV anexado - enviar no assunto: Vaga FrontEnd Developer

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

**Comment by romulolessa** [comment]
enviei o meu currículo.

**Comment by krivax** [comment]
Enviei o currículo
