### ISSUE TITLE
[Remoto] Pessoa Desenvolvedora Frontend React Sênior na iClinic

### ISSUE THREAD

**Issue by gabrielferreiraa** [frontendbr/vagas#3353]
## Descrição da vaga
A **iClinic** está à procura de uma **pessoa desenvolvedora front-end** (remoto) para fortalecer e expandir nossas capacidades técnicas. Buscamos uma pessoa responsável para o cultivo de uma cultura técnica de excelência: **obcecado por qualidade e desenvolvimento ágil.** Procuramos alguém para refletir, validar ideias e ajudar-nos a encantar nossos clientes.

Você vai trabalhar com times multidisciplinares, com pessoas incríveis, capazes de realizar trabalhos incríveis e produzir resultados incríveis para os nossos usuários. Será responsável por desenvolvimento contínuo diariamente e irá garantir a qualidade que almejamos.

Tecnologia é o nosso core, então terá autonomia para arquitetar ou sugerir algo novo, deve ter uma mentalidade analítica, aptidão para solução de problemas e preocupação com a qualidade do código e boas práticas.

Temos serviços em Python/Django, Node, sistemas na AWS com e sem Kubernetes. Nossa aplicação front-end é desenvolvida em React + Redux.

## Local

Remoto 🏠 

## Benefícios

- Vale refeição/alimentação;
- Convênio médico nacional;
- Plano de participação nos resultados (PPR);
- Fornecemos MacBook Pro como equipamento para desenvolvimento;
- Ajuda de custo para modalidade remota (cadeira, mesa, acessórios para ergonomia etc);
- Bônus por indicação de outros profissionais para trabalhar na iClinic;
- Relacionamento próximo aos fundadores e diretores da empresa;
- Incentivo financeiro para desenvolvimento técnico;

#### Quando fizer uma visita em nosso escritório - pós pandemia :) - você encontrará:
- Ambiente jovem, descontraído, escritório confortável, videogame, puffs para descanso;
- Sem dress code,  Trabalhe do jeito que achar confortável;
- Café da manhã, frutas e o sagrado cafezinho ao longo do dia;

### O que esperamos de você:
- Vontade de repassar conhecimento, ensinar, criar ou já ter criado artigos de programação;
- Já ter implementado testes com Selenium ou Cypress;
- Não ter receio em alterar um código que você não escreveu;
- Empatia por seus colaboradores;
- Capacidade de comunicar ideias de forma clara;
- Desejamos proatividade para adquirir novos conhecimentos rapidamente.

#### Obrigatórios:
- Experiência comprovada em React + gerenciamento de estado (Redux, Hooks, Saga) como front-end;
- Alta capacidade de auxiliar os outros membros do time a se desenvolverem, sendo capaz de comunicar ideias de forma clara;
- Visão ampla sobre processos de desenvolvimento e fluxo de trabalho em metodologias ágeis;
- Conhecimentos abrangentes em todas as partes do software, podendo conversar com diversas frentes do produto, pesquisa, dev-ops, back-end, QA tester;
- Conhecimentos em arquitetura de projetos, design patterns e boas práticas de desenvolvimento;
- Conhecimentos em paradigmas funcionais e suas práticas;
- Conhecimentos em metodologias de testes unitários, integração e E2E.

#### Nice to have:
- Ter conhecimentos de back-end e Docker;
- Inglês avançado em leitura e escrita;
- Conhecimento em ferramentas da AWS;

## Contratação

CLT

## Nossa empresa

A **iClinic** é uma das startups de tecnologia em saúde que mais cresce no Brasil.
Nossa missão é **Descomplicar a saúde no Brasil**.

E como fazemos isso hoje? 
_Oferecendo o melhor software de gestão para clínicas e consultórios médicos._

E como atingir este objetivo?
_Montando um time de pessoas incríveis, capazes de colocar os nossos clientes no centro do processo de criação e desenvolvimento do nosso sistema. Aqui são os clientes quem mandam e você será uma das vozes deles dentro da empresa e do time de Pesquisa e Desenvolvimento._

## Como se candidatar

https://iclinic.gupy.io/jobs/153837?jobBoardSource=gupy_public_page

## VENHA DESCOMPLICAR A SAÚDE NO BRASIL
Por aqui, **curtimos nossa jornada**!

Acreditamos genuinamente em nosso grande objetivo de descomplicar a saúde no Brasil e vivenciamos esse propósito em cada ação, diariamente. Entendemos que somos parte de algo maior e isso nos motiva a curtir cada segundo que estamos juntos - ainda mais quando temos cerveja.

E só conseguimos concretizar esse propósito **cuidando das pessoas**, nossos clientes. Vamos além do atendimento de qualidade: estamos genuinamente preocupados com seu problema. Temos empatia para agregar o máximo de valor possível, em cada ação, a qualquer hora para aqueles que são nossa razão de ser.

Pra isso, **acertamos juntos**. Agimos juntos, em função do todo e cada conquista é de todos nós, assim como cada um dos nossos erros. Sentimos genuína felicidade em compartilhar nossos desafios com nossos amigos de trabalho porque entendemos que estamos todos em busca dos mesmos resultados.

E isso só é possível porque **jogamos limpo**. Somos sinceros e íntegros em absolutamente todos os momentos, mesmo que não sejam os nossos melhores momentos. 

Por isso **causamos o verdadeiro impacto.** Em cada uma de nossas ações, somos os melhores. Somos inconformados e exigentes com nossos resultados. Temos autonomia para fazer a diferença e melhorar até o que já é bom.

E é assim que **somos incríveis**! 

**iClinic: um lugar de gente boa e boa gente!**

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

P.S: Qualquer dúvida podem me procurar no Slack React Brasil @gabriel.ferreira

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by gabrielferreiraa** [comment]
Olá @felipefialho 
A vaga ainda está aberta!

**Comment by gabrielferreiraa** [comment]
@felipefialho por que foi fechada a issue? 🤔
