### ISSUE TITLE
[Remoto] Vue.js Front-end Developer Senior na BuildGroup (EUA)

### ISSUE THREAD

**Issue by gmenegatti** [frontendbr/vagas#3355]
Essa vaga já havia sido postada há algumas semanas através da issue #3299, mas naquele momento focava apenas em profisisonais Junior ou Pleno.

Na realidade, a BuildGroup está buscando um total de 4 profissionais, sendo 2 Seniors + 2 Juniors ou 2 Plenos.

O processo seletivo completo acontecerá **ainda essa semana** (27/07 a 31/07), sendo que a resposta aos candidatos será informada na segunda ou terça-feira da próxima semana (até 04/08).

## Empresa
A BuildGroup é uma empresa situada em Austin - Texas, desenvolvendo uma solução em Vue.JS para mercado de Investimento. Foi fundado por um antigo CEO da Rackspace, com um bom aporte de capital.
 
> At BGDS, our vision is to untap the economic welfare potential of technology through entrepreneurship. In order to fully realize our vision, we have committed ourselves the mission to provide transparency, openness, collaboration, ease-of-use and insights to technology startup financing so that entrepreneurship thrives globally, and founders can develop life-changing technologies.
 
## Descrição da vaga
Empresa está reformulando equipe de Front end e está na procure de profissionais de nível Senior (e também Junior e Pleno) para compor o quadro de funcionários. A pessoa será responsável por dar manutenção nos componentes existentes (Vue SFC standard), escrever testes (E2E e Unit Tests), além de criação de novas features. Tudo isso em cima de uma API REST.

Inglês técnico é requerido e inglês de conversação é diferencial (pelo menos entender o que for falado). Terá outros brasileiros no grupo e o coordenador de projeto é um espanhol que passou 10 anos no Brasil, então sabe se comunicar muitíssimo bem.

_A Vaga tem diferencial de Python/Django, mas não é necessário ao desenvolvedor._

> RESPONSIBILITIES AND DUTIES
> • Build interactive and thoughtful UIs in VueJS and Python that solve complex problems and are a delight to use
> • Build End-to-end ownership of major sections of our web user interface, new visualizations, and new reports
> • Contribute to creating view components and extend the company API
> • Participate in the conceptualization and wireframing of new interfaces
> • Prototyping and building clean and intuitive user interfaces through various iterations
> • Identify and troubleshoot UX problems (e.g. responsiveness, performance, usability, mobile)
> • You have feelings about how a webpage should look and feel and care about the nuances of how users will work with the product you’re building.
> • Ensuring implementations follow web standards, accessibility, and usability best practices
> • We able to test the Graphical User Interface (GUI), functionality and usability of a complex website, that involves checking functionalities like forms, graphs, menus, reports, etc. as well as associated Javascript
> • Our approach to supervision is very adaptive, which is to say that we are happy to accommodate a variety of personal styles. We are searching for someone who is an independent contributor, but you will also get the support you need when you need it
 
## Local
Remoto - seguindo fuso horário comercial do Texas (atualmente 2h de diferença)

## Requisitos
* Experiência em trabalho remoto - ser capaz de manter horário de trabalho e  ter curto tempo de resposta
* Formação na área
* Excelente conhecimento de HTML5/CSS/JS (ES5-ES10) e suas particularidades
* Experiência com construção de interfaces UI
* 1-3 anos de experiência com Vue.JS
* Experiência com API REST
* Experiência webpack e outros task managers
* Experiência com Git/Github

**Desejáveis:**

* Python
* Django
* SQL/NoSQL
* Web Components
* Inglês de conversação
* Experiência escrevendo testes E22 e Unit Tests
* Experiência com DevOps

**Diferenciais:**

* Ter  experiência de trabalho remoto para empresas fora do BR
* Bônus semestral
* Empresa disponibiliza Macbook para funcionário
* Possibilidade de viagem para os EUA para conhecer empresa e fazer um período de integração de equipe.

## Benefícios
* Feriados pagos - PTO (Paid Time Off) - tanto feriados BR como EUA, mas tem um limite de escolha de dias
* Ferias remuneradas
* Jornada 40h semanais

## Contratação
PJ
* Até USD 5.000 mês (Aprox. R$ 26.000,00 mês) - Senior
* Até USD 2.500 mês (Aprox. R$ 13.000,00 mês) - Pleno
* Até USD 1.500 mês (Aprox. R$ 7.800,00 mês) - Jr

## Como se candidatar
Por favor envie um email para `gabriel@simbioseventures.com` com seu CV anexo.

## Labels
* Remoto
* Senior
* Vue.js
* Vue
* Javascript
* Front end

#### Alocação
* Remoto

Com possibilidade de mudar para os EUA no futuro e trabalhar alocado, caso tenha interesse.

#### Regime
* PJ  (MEI ou Simples)

#### Nível
* Senior

Também estamos buscando profissionais:
* Pleno
* Junior

**Comment by gmenegatti** [comment]
@felipefialho, por favor, se puder adicionar a label "senior" nesta issue, te agradeço. :-)

**Comment by rodrigopluz** [comment]
Boa tarde, currículo enviado.

**Comment by mystrader** [comment]
Boa tarde, acabei de enviar também.

**Comment by ddiegommachado** [comment]
Boa tarde! Enviado!!!

**Comment by Arthurin915** [comment]
Boa tarde, enviado!

**Comment by ngustavo** [comment]
Enviado!

**Comment by gmenegatti** [comment]
Olá, pessoal,

Agradeço por todos os currículos enviados.

Vou encerrar essa issue pois já recebemos mais CVs do que temos capacidade de analisar.

O processo continua (para quem já enviou CV até agora) e todos receberão um retorno até a próxima terça-feira (04/08).

Saúde e sucesso à todos.
