### ISSUE TITLE
[Tangará da Serra - MT] Front-end Developer na Omega Sistemas

### ISSUE THREAD

**Issue by kivervinicius** [frontendbr/vagas#3356]
## Nossa empresa

Fundada e mantida por pessoas apaixonadas por tecnologia e educação, a OMEGA é especialista em soluções para gestão educacional. 

Nascida em uma época de carência de soluções no setor, a OMEGA desde sua criação vem cultivando um histórico positivo com seus casos de sucesso. Saiba mais em: [https://omegasistemas.net.br/quemsomos.html](https://omegasistemas.net.br/quemsomos.html)

## Descrição da vaga

Estamos procurando pessoas desenvolvedoras front-end Jr que já consigam se virar com HTML, CSS e Javascript (experiência com React é bem-vinda!) e que queiram muito aprender e contribuir para o nosso projeto de transformar o futuro dos brasileiros por meio da educação. 

## Local

Escritório em Tangará da Serra - MT

## Requisitos

**Obrigatórios:**

- Saber se virar com HTML, CSS e JS.
- Conseguir consumir api's rest
- Ter muita vontade de aprender e compartilhar conhecimento.

**Desejáveis:**

- Habilidade em desenvolvimento orientado a objeto.
- Experiência com React
- Experiência com RESTFull Design Patterns
- Versionamento em Git
- Conhecimento em Web Standards(W3C) e Acessibilidade

**Diferenciais:**
- Conhecimentos em NodeJS
- Conhecimentos em Java
- Conhecimento em banco de dados (Sql Server, Postgres, Redis)
- Ser ativo na comunidade.

## Benefícios

- Salário altamente competitivo
- Plano de Saúde

## Contratação

CLT

## Como se candidatar

Por favor envie um email para kiver@omegasistemas.net.br com seu CV anexado - enviar no assunto: Vaga Front-end Developer.
Os testes poderão ser realizados para qualquer nível a diferença é a forma que será avaliado para cada nível, favor no e-mail informar qual o nível pretendido.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by lucaspmarra** [comment]
O link encurtado do site principal não está funcionando... é redirecionado para a página principal do [Short URL](https://www.shorturl.at/).

**Comment by kivervinicius** [comment]
@lucaspmarra pois é, valeu, ajustado

**Comment by kivervinicius** [comment]
Obrigado a todos que concorreram a vaga, como recebemos muitos candidatos vamos analisar todos os recebidos e retornar a todos o feedback.
