### ISSUE TITLE
[São Paulo / Recife] Front-end Angular Developer na Deloitte

### ISSUE THREAD

**Issue by Augustus118** [frontendbr/vagas#3357]
**Deloitte**
Qual será o seu impacto?

Todos os seus planos, sonhos e desafios pessoais cabem no futuro que você pode construir com a Deloitte. Nós acreditamos no seu poder de impactar e transformar o mundo.

A Deloitte tem um propósito claro, que define o que somos e para que existimos em 150 países: making an impact that matters.

Todos os dias, nossos 312 mil profissionais se desafiam a gerar impactos e fazer o que realmente é importante − aos nossos clientes, às nossas pessoas e à sociedade −, a partir dos projetos e da ação que cada um é capaz de conduzir.

No Brasil, nossos 5.500 profissionais são reconhecidos pela integridade, competência e habilidade em transformar seus conhecimentos em soluções para os clientes. As operações da Deloitte no País cobrem todo o território nacional, a partir de escritórios em São Paulo, Belo Horizonte, Brasília, Campinas, Curitiba, Fortaleza, Joinville, Porto Alegre, Rio de Janeiro, Recife, Salvador e Ribeirão Preto.

Construa sua história com a Deloitte.

**Descrição da vaga**
Desenvolvedor Angular

**Formação, educação e exigências de experiência de trabalho:**  
- Formação superior em áreas relacionadas a tecnologia (Análise de Sistemas, Engenharia de Software), Engenharias, Matemática ou disciplinas afins; 
- Desenvolvimento de aplicações frontend, utilizando linguagem Angular 2, 5, 6 ou 7; 
- Desenvolvimento WEB (HTML, CSS, Javascript, JQuery, TypeScript); 
- Conhecimento em arquitetura de microserviços; 
- APIs REST, Webservices, e Json; 
- Experiência em controle de versionamento com Git; 
- Experiência com testes unitários; 
- Bancos de dados MySQL, MongoDB e DinamoDB; 
- Familiaridade com ambientes de Cloud Computing, preferencialmente AWS; 
- API Gateway. 
 
**Desejável conhecimento em:** 
- Conhecimentos de metodologias ágeis (Scrum e KanBan); 
- Desenvolvimento Web Responsivo; 
- Jira para controle de Projetos Agile; 
- Maven; 
- CI/CD; 
- Jenkis; 
- Swagger. 
 
**Competências comportamentais:** 
- Comprometimento; 
- Organização; 
- Gestão de tempo; 
- Iniciativa; 
- Trabalho em equipe. 

Buscamos profissionais que sejam protagonistas de suas carreiras e tenham vontade de transformar a si mesmos para ser fonte de inspiração positiva das transformações a seu redor.

**Local**
Av. Chucri Zaidan, 1240 - Golden Tower – 9º andar

**Beneficios**
Trabalhar em um ambiente colaborativo e com gente com vontade de fazer acontecer. Horário Flexível, Home office, Dress Code - Casual Business, Oportunidade de trabalhar com um time de alta performance, Licença Maternidade de 6 meses para mulheres e 20 dias para os pais, Participação nos Lucros e Resultados, Ticket refeição / Alimentação, Vale-transporte / Reembolso de KM (projetos), Gym Pass, Benefícios Flexíveis, Assistência médica, Seguro de vida.

**Como se candidatar**
Por favor, enviar um email para abernardes@deloitte.com com seu CV em anexo e no assunto a descrição “Vaga Angular”.

**Alocação**
•	Remoto (Durante a Pandemia)

**Regime**
•	CLT

**Nível**
•	Pleno
•	Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
