### ISSUE TITLE
[São Paulo] Front-end Developer na Iz Dev

### ISSUE THREAD

**Issue by hrsoul1221** [frontendbr/vagas#3358]
> Vaga Remota durante a pandemia

## Nossa empresa

HrSoul empresa focada em recrutamento e seleção de TI.

## Descrição da vaga

- Experiência em PHP, WordPress - criação de temas próprios, HTML, CSS e jQuery (JS);
- Imprescindível disponibilidade para início imediato;
- Atuação remota (necessária disponibilidade para eventuais reuniões presenciais).

## Local

São Paulo, Remoto

## Requisitos

**Obrigatórios:**
- 1 ano de experiência com PHP
- 1 ano de experiência com HTML, CSS e jQuery (JS);

**Diferenciais:**
- Home Office

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para sgimenes@hrsoul.com.br com seu CV anexado - enviar no assunto: Vaga Front-End

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
