### ISSUE TITLE
[São Paulo] Front-end Developer na Mobiauto!!

### ISSUE THREAD

**Issue by paulahribola** [frontendbr/vagas#3359]
> Vaga Remota durante a pandemia

## Nossa empresa

A Mobiauto (www.mobiauto.com.br) é uma plataforma de tecnologia do setor automotivo que visa promover maior eficiência e praticidade na relação de compra e venda de automóveis no Brasil. 

A startup surgiu para desburocratizar os processos de compra e venda de automóveis. Para isso, foi criada uma plataforma online, que permite criar e publicar anúncios de carros, de forma simples e intuitiva. O site possibilita uma comunicação rápida entre comprador e vendedor, através de tecnologias e processos que aceleram a negociação e proporcionam a melhor experiência aos usuários.

A empresa começou com apenas sete funcionários numa sala de coworking e não demorou para decolar. Hoje, são quase 80 funcionários, que trabalham em um dos principais arranha-céus da cidade de São Paulo. 

## Descrição da vaga

Construção da plataforma em React pensando em aprimorar alguns recursos e proporcionais uma experiência tecnológica mais completa para o usuário.

## Local

Av. das Nações Unidas, 17007 - Várzea de Baixo, São Paulo - SP

## Requisitos

**Obrigatórios:**
- Experiência com HTML, CSS e React (e seu ecossistema)
- Experiência com Redux ou Mobx
- Next.js (SSR)

**Desejáveis:**
- Conhecimento de outros frameworks Javascript
- Typescript

**Diferenciais:**
- projetos opensource

## Benefícios

- Plano de saúde
- Plano odontológico
- VR de R$ 35/dia
- VA
- VT
- Home office

## Como se candidatar

Por favor envie um email para paula.ribola@beit.work com seu CV anexado - enviar no assunto: Vaga Front

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Alocado (quando as coisas se estabilizarem)

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
