### ISSUE TITLE
[Natal RN] Frontend Developer | Nova M3

### ISSUE THREAD

**Issue by davidcostadev** [frontendbr/vagas#336]
## Descrição da vaga

Saber dominar a técnica e conseguir atingir as metas

## Local

Softhouse - Natal - RN

## Benefícios

2 horas de almoço
Ambiente descontraído
sala de jogos

## Obrigatórios:
Bootstrap

## Desejáveis:
Experiencia ou Portfólio
Vue
Angular

## Contratação
CLT - Mandar Pretensão Salarial
Tempo Integral - Segunda a Sexta

## Nossa empresa

Nova M3 - Produto digitais

## Como se candidatar

Por favor envie um email para gerencia@novam3.com com seu CV anexado - enviar no assunto: Vaga Frontend

**Comment by richmanzoli** [comment]
Possibilidade de remoto?

**Comment by davidcostadev** [comment]
Não amigo. Só presencial.

**Comment by raloliver** [comment]
Massa hein... tenho parentes em Morro Branco e em São Paulo do Potengi. <3 Bom saber se um dia eu for morar por ai, já sei onde deixar o currículo.

**Comment by davidcostadev** [comment]
Com certeza!
