### ISSUE TITLE
[São Paulo] Pl/Sr Front-end Developer no BTG Pactual

### ISSUE THREAD

**Issue by taianeuchoac** [frontendbr/vagas#3360]
> Vaga Remota durante a pandemia. Após a normalização da situação, parcial remoto e parcial presencial.

## Nossa empresa
O BTG Pactual é um grande banco de investimentos. A empresa nesse momento esta expandindo seus negócios, criando também um banco digital.

## Descrição da vaga
Oportunidade para atuar desenvolvendo aplicações internas da empresa.

## Local
Av. Faria Lima, próximo ao Itaim Bibi

## Requisitos
Angular JS & Angular 2+
Javascript        
Typescript
Git
HTML5
SASS/SCSS
CSS3+
Gulp
NPM
Testes unitários
Conceitos de API Restful
Webpack

- Desejáveis:
Scrum
Gitflow

## Benefícios
- Plano de saúde
- Seguro de vida
- VR
- Auxílio creche
- VT
- Plano Odontologico

## Contratação
CLT a combinar

## Como se candidatar
Por favor envie um taiane@mazza.tech com seu CV anexado - enviar no assunto: Vaga FrontEnd Angular

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: taiane@mazza.tech

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
