### ISSUE TITLE
[SÃO CARLOS - SP] Tech Lead na Ênfase

### ISSUE THREAD

**Issue by luisavocurvello** [frontendbr/vagas#3364]
O Ênfase é um curso jurídico online formado por um grupo de apaixonados pelo direito e pela arte de mudar a vida profissional das pessoas através do ensino jurídico! Há mais de 25 anos, o curso que mais aprova em concurso. Essa tradição está pautada em tecnologia de ponta. Na plataforma, o aluno encontra ferramentas que facilitam o estudo e dão acesso, das melhores maneiras, a temas e assuntos mais cobrados. Dentre elas, vídeos, podcasts, resumos, e-books, etc. Todas organizadas para a melhor experiência do usuário.

### Requisitos:
•        Inglês intermediário;
•        Experiência em desenvolvimento de aplicações Mobile ou Web utilizando frameworks em Javascript (React, Vue.js, Angular);
•        Conhecimento em ferramentas de versionamento de códigos (SVN ou Git);
•        Alta capacidade lógica e de resolução de problemas;
•        Conhecimento sólido em estruturas de dados;
•        Domínio em princípios de design de algoritmos;

### Diferenciais: 
•        Docker;
•        Teste automatizado;
•        DevOps.

### Contratação:
•        CLT (com benefícios) ou PJ (sem beneficios)

Benefícios: 
•        Vale Alimentação
•        Vale Refeição
•        PLR (Anual)
•        Plano de Saúde 

Local de Trabalho: R. Nove de Julho, 1913 – Centro, São Carlos – SP, 13560-042, mas aceita remoto.

### Informações Adicionais e Inscrição:
**Para conhecer mais da oportunidade e participar do processo com a gente, é só acessar: https://bit.ly/3hNQb4F **

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
