### ISSUE TITLE
[Recife/PE - Remoto] PL/SR Front-End Developer @ N3urons

### ISSUE THREAD

**Issue by andregomesoliveira** [frontendbr/vagas#3365]
> Vaga Remota durante a pandemia

## Nossa empresa

Somos uma startup focada em soluções web/mobile inovadoras relevantes para o mercado que atuamos. Nosso diferencial é aplicar inteligência artificial com foco em automação e inteligência de negócios, com laboratórios incubados em empresas reais para validação dos nossos produtos. 

## Descrição da vaga

Estamos buscando profissionais de desenvolvimento que tenham capacidade de trabalhar em um time multidisciplinar entendendo a cultura de união e propósito do que fazemos, integrados como um só organismo assim como os neurônios que representam nossa startup. 
Compartilhamento de conquistas e conhecimentos, soluções em conjunto, busca de melhoria contínua e sede de inovar são imprecindíveis. **Na N3urons valorizamos estas _soft skills_ antes de tudo!**
Você irá participar da concepção de novos produtos como otimização das versões correntes, desde desenvolvimento mobile, web e participação dos projetos de UI/UX.

## Local

Vagas presenciais em Recife/PE e full Remoto.

## Requisitos

**Obrigatórios:**
- 2+ anos de experiência com desenvolvimento web/mobile frontend
- Conhecimento intermediário em React Native/ReactJS, NodeJS e JavaScript
- Experiência com APIs REST
- Experiência com times de desenvolvimento
- Conhecimento nas Metodologias Ágeis

**Desejáveis:**
- React avançado
- NodeJS avançado
- Conhecimento intermediário em Redux, Codepush
- Experiência com desenvolvimento em ambientes Cloud (Kubernetes, Docker, arquitetura de microserviços)
- Conhecimento em Banco de Dados não-relacionais (MongoDB) e mobile (Realm)

## Benefícios

- Horário flexível (40hs semanais)
- Note fornecido pela empresa no padrão Dell Core i7, RAM 16GB, placa de vídeo GeForce dedicada e disco SSD.
- Plano de saúde 100% custeado pela empresa
- VR/VA mensal
- Incentivos para participação em treinamentos, eventos, palestras e cursos
- Envolvimento no propósito do projeto e não somente codar um escopo pré-definido

## Contratação

CLT ou PJ, podemos te oferecer a modalidade que melhor se adequar a você!

## Como se candidatar

Por favor envie um email para andre.oliveira@n3urons.com com seu CV e LinkedIn informado - enviar no assunto: Vaga Frontend

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior

#### Tecnologias
- React
- NodeJS
- RESTful
- API
- Javascript
- Cloud
- MongoDB
- Realm

**Comment by deeborges** [comment]
Pra deixar comentado e pra dar uma visão geral sobre mim ;)
Github: https://github.com/deeborges
Linkendin: https://www.linkedin.com/in/deyvisonborges/
YouTube: https://www.youtube.com/c/deyvisonborges

**Comment by zumbizar** [comment]
Fala galera, tudo certo? 
Meu nome é Fernando Henrique e sou de RECIFE-PE também ♥ 
Github: https://github.com/zumbizar
LinkedIn: https://www.linkedin.com/in/zumbizar/
