### ISSUE TITLE
[REMOTO] Front-end Developer no Grupo DB1

### ISSUE THREAD

**Issue by talentos-db1** [frontendbr/vagas#3368]
## Nossa empresa
Somos um grupo de tecnologia com 20 anos de expertise em desenvolvimento de software voltado para soluções de grandes empresas. Estamos há 10 anos consecutivos dentre as melhores empresas para trabalhar, pelo GPTW. 
Ser DB1 é pertencer a um grupo que transforma a vida das organizações e das pessoas por meio da tecnologia. Nossa cultura, conhecimento e habilidades nos movem para fazer entregas que ajudam as pessoas a terem um dia a dia melhor.  
Fazer parte do DB1 Group é ser movido a desafios!

## Descrição da vaga
Buscamos por um perfil profissional com proatividade para resolver problemas, comprometido em entregar software com qualidade, contribuindo com conhecimentos e experiências . Atuará na construção do Front-end de projeto utilizando Angular 2+

## Local

Remoto ou em um de nossos escritórios [Maringá-PR][Campo Grande-MS][Presidente Prudente-SP]

## Requisitos

**Obrigatórios:**

- Sólida vivência em JavaScript, TypeScript, Html, CS;
- Domínio em Angular JS e Angular 9;
- Uso de boas práticas de desenvolvimento e conceitos de código limpo;
- Conhecimento em ECMAScript nas suas versões atuais;
- Conhecimentos em consumo de APIs REST;
- Conhecimentos em repositório de código Git;
- Conhecimento em frameworks de Testes Unitários.

**Desejáveis:**
- Experiência prévia com Scrum
- Conhecimento em ecossistema de e-commerce

**## Benefícios**
- Plano de saúde
- VR ou VA mínimo de R$ 400/mês
- Ferramentas de trabalho oferecidas pela empresa (computador, teclado, segunda tela, teclado). 

**Diferenciais:**
- Horários flexíveis
- Desenvolvimento de Carreira (Plano de Desenvolvimento Individual, feedbacks, acompanhamentos). 
- Café e chá feitos pela Dona Rosa com carinho para toda a equipe na sede;
- DB1 Snacks: um mercadinho dentro da empresa para você fazer compras; 
- Diversos Comitês para você participar de ações com impacto dentro e fora da DB1; 

**## Contratação**
CLT

**## Como se candidatar**

Através do nosso site https://vagasdb1.recruiterbox.com/jobs/fk0qlf7?source=Github (todos os CVs são recebidos por aqui!)
Em caso de dúvidas, pode entrar em contato através do talentos@db1.com.br. 

**## Tempo médio de feedbacks**
Costumamos enviar feedbacks em até 30 dias após cada processo.
E-mail para contato em caso de não haver resposta: talentos@db1.com.br.

**#### Alocação**
- Alocado
- Remoto

**#### Regime**
- CLT

**#### Nível**
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by talentos-db1** [comment]
@felipefialho é possível reativar essa vaga?
