### ISSUE TITLE
[Maringá-PR ou Remoto] Front-end Developer (Vue.js) @ DB1 Group

### ISSUE THREAD

**Issue by talentos-db1** [frontendbr/vagas#3369]
## Nossa empresa
Somos um grupo de tecnologia com 19 anos de expertise em desenvolvimento de software voltado para soluções de grandes empresas. Estamos há 10 anos consecutivos dentre as melhores empresas para trabalhar, pelo GPTW. 
Ser DB1 é pertencer a um grupo movido a desafios, e que transforma a vida das organizações e das pessoas por meio da tecnologia. Nossa cultura, conhecimento e habilidades nos movem para fazer entregas que ajudam as pessoas a terem um dia a dia melhor. 

## Descrição da vaga
Buscamos por um perfil profissional com proatividade e comprometimento em entregar software com qualidade, contribuindo com conhecimentos e experiências para aumentar a qualidade técnica do próprio time. Atuará na construção do Front-end utilizando Vue.js em projeto da Softwarehouse, no ramo de Energia Elétrica. 

## Local
Remoto ou em um de nossos escritórios [MARINGÁ-PR],[CAMPO GRANDE-MS] ou [PRESIDENTE PRUDENTE-SP]

## Requisitos

**Obrigatórios:**
- Mínimo 3 anos experiência em Front-end
- Experiência prévia com Vue.js;
- HTML/CSS:
- JavaScript/ES6;
- Bootstrap;
- Sass
- B.E.M.
- Jest
- RESTFul API; 

**Desejáveis:**
- Conhecimento em Node.js

## Benefícios
- Plano de saúde
- VR ou VA mínimo de R$ 400/mês
- Ferramentas de trabalho oferecidas pela empresa (computador, teclado, segunda tela, teclado).

**Diferenciais:**
- Horários flexíveis
- Desenvolvimento de carreira (Plano de Desenvolvimento Individual, feedbacks, acompanhamentos)
- Café e chá feitos pela Dona Rosa com carinho para toda a equipe na sede;
- DB1 Snacks: um mercadinho dentro da empresa para você fazer compras pro lanche da manhã ou tarde;
- Diversos comitês para você participar de ações com impacto dentro e fora da DB1;

## Contratação
CLT

## Como se candidatar

Através do nosso site https://vagasdb1.recruiterbox.com/jobs/fk0qdw8?source=Github (todos os CVs são recebidos por aqui!)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 45 dias após cada processo.
E-mail para contato em caso de não haver resposta: talentos@db1.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by Carlosxell** [comment]
O Link não está encontrando a vaga descrita e termina enviando a uma página de listagem de vagas.

**Comment by talentos-db1** [comment]
Olá @Carlosxell ! Obrigada pela observação, a vaga foi fechada recentemente, por isso retiramos o link. Continuamos com vagas para Angular!
