### ISSUE TITLE
[São Paulo - SP] Frontend Developer | Purple Cow

### ISSUE THREAD

**Issue by robsonlb** [frontendbr/vagas#337]
Estamos contratando Frontend Developer

Obrigatórios:
Domínio de HTML, CSS, JS, Jquery;
Conhecimentos de SASS, LESS ou outro Pré-Processador de CSS;
Integrações com APIs REST e Webservices;
Style guides;
Padrões de Projeto;
Conhecimento de sistema de GRIDs;
Experiência com versionamento GIT/SVN, preferencialmente GIT;
Conhecimento em algum framework, Angular I/II, React, VueJS, Elm, ...;
Conhecimento em alguma framework de CSS (Boostrap, Foundation, Skeleton, Pure, Material Design ou outro);
Conhecimento de automatizador de tarefas (Grunt, Gulp, Webpack,...);
Experiencia com Design Responsivo (mobile first);
SEO;
Tagueamento de sites;

Diferenciais:
Experiência em Metodologias ágeis;
Conhecimento de BackEnd (para melhor iteração entre as partes);
Saber manusear algum software de edição de imagem;
Noção de áreas de TI (servidor, banco de dados, redes, etc.);

## Contratação
PJ
Valor R$ 5.000,00 + VR 

## Local

São Paulo - Vila Madalena

## Como se candidatar

Por favor envie um email para robson@purplecow.com.br com seu CV anexado - enviar no assunto: Frontend Developer

**Comment by ygorlazaro** [comment]
Aceitaria remoto?

**Comment by robsonlb** [comment]
@ygorlazaro somente alocado. vc mora onde?

**Comment by ygorlazaro** [comment]
@robsonlb no RJ

**Comment by robsonlb** [comment]
me manda seu CV

**Comment by ygorlazaro** [comment]
Vou te mandar um e-mail com meus links e portfolio, estou reestruturando o meu site para deixar mais visível

**Comment by fysp11** [comment]
Enviado :)

**Comment by MatheusJusto** [comment]
Róla pra quem mora na baixada santista?

**Comment by simaodeveloper** [comment]
@LFeh esta faltando mais detalhes sobre a empresa nas novas vagas.
