### ISSUE TITLE
[São Paulo] Sr. FullStack Developer (GraphQL) na Descomplica

### ISSUE THREAD

**Issue by taianeuchoac** [frontendbr/vagas#3370]
## Nossa empresa
Profissional será contratado pela Mazzatech para atuar alocado na Descomplica

## Descrição da vaga
Desenvolvimento de aplicações internas da empresa.

## Local
Atuação Remota

## Requisitos
Profissional com mais de 5 anos de experiência escrevendo código;
Experiência com GraphQL, microservice oriented architecture ou RESTful API oriented design;
Bancos de dados SQL e NoSQL;
Experiência com serviços AWS;
Experiência com testes automatizados (unit, integration e E2E testing);
Experiência no desenvolvimento de soluções escaláveis;
Aptidão analítica;
Fluência em inglês e português;
Atenção aos detalhes. 
Habilidade para criticar e modificar designs/arquiteturas existentes.
Serão considerados diferenciais:
Formação superior em engenharia da Computação ou equivalente.
Experiência com Javascript (React, React Native ou VueJS) e NodeJS;
Conhecimentos de  Docker e CI/CDs atuais;
Conhecimentos de Messaging Architecture;

## Contratação
A combinar.

## Como se candidatar
Por favor envie um email para taiane@mazza.tech com seu CV anexado - enviar no assunto: Vaga GraphQL

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 5 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by luqezman** [comment]
O email está correto "taiane@mazzatech"?

**Comment by taianeuchoac** [comment]
Oi! Nossa muito obrigada! Ta faltando um .
O correto é taiane@mazza.tech. Muito obrigada mais uma vez!
Abraço!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
