### ISSUE TITLE
[Remota]  Senior Software Engineer na Estratégia Educacional

### ISSUE THREAD

**Issue by IgorHalfeld** [frontendbr/vagas#3372]
## Sobre a Estratégia Educacional 

A Estratégia Educacional (@estrategiahq) é a holding de educação da Estratégia Concursos, Estratégia OAB, Estratégia Carreiras Jurídicas, Estratégia Vestibulares e Estratégia Militares. 

Somos uma edtech que está trabalhando no edge da tecnologia de forma a criar os melhores produtos e melhores experiências de educação do Brasil. 

Na Estratégia Educacional você irá:

+ Participar de discussões técnicas acerca das demandas do produto da empresa;
+ Trabalhar de forma colaborativa com uma equipe, disposto a ajudar e ser ajudado;
+ Programar e estudar linguagens de programação que melhor atenda no desenvolvimento de uma solução para algum problema; 

## Local

Remoto ou Escritório em São Paulo (Brooklin)

## Requisitos

**Desejáveis:**
+ Experiência com desenvolvimento Web;
+ Facilidade para aprender uma nova linguagem de programação;
+ **Abertura/habilidade para stack de desenvolvimento em Golang, Vue.js e Flutter**;
+ Conhecimento em cloud (AWS, GCP, Azure);
+ Preocupação com qualidade de código;
+ Ler, compreender e discutir demandas e requisitos; 
+ Ser um resolvedor de problemas; 
+ Ser autodidata e buscar sempre aprender coisas novas;
+ Ser pragmático;

_A ideia é você ser aberto a aprender a nossa stack, **entrar sabendo Vue.js e te ensinarmos Golang e Flutter** (mas se já souber fica ❤️)_

**Diferenciais:**
 + Conhecimentos em Golang, Vue.js, Flutter, base de dados em grafos (Neo4j, DGraph), AWS;
 + Experiência com arquiteturas de micro-serviços;
 + Conhecimento em Docker;
 + Experiência em desenvolver aplicações com grande escala;

## Benefícios

+ Salário competitivo com o mercado;
+ Bônus anual;
+ Vale Refeição ou Alimentação (R$ 30 / dia);
+ Plano de saúde Amil 900;
+ Vaga de estacionamento (carro, moto ou bicicleta) ou Auxílio transporte;

## Diferenciais

+ Ambiente criativo, descontraído, inovador e com profissionais referência no mercado;
+ No dress code (pode trabalhar de bermuda, chinelo, etc);
+ Café, bebidas variadas;
+ Carga horária flexível (de verdade!! se você trabalha só 4 horas e entrega, é noix);
+ Setup de Máquina (Macbook PRO ou Dell XPS);
+ Home office;
+ Política Remote-first;

## Contratação

CLT

## Como se candidatar

https://www.linkedin.com/jobs/view/1910119446/

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 semanas após cada processo.
E-mail para contato em caso de não haver resposta: carlos.assis@estrategiaconcursos.com.br

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by IgorHalfeld** [comment]
Segue aberta e recebendo submissões 🚀
