### ISSUE TITLE
[Remoto] Front-end Developer na Consultoria MP

### ISSUE THREAD

**Issue by Mari-Ana-RH** [frontendbr/vagas#3373]
> Vaga Remota durante a pandemia

## Nossa empresa

Atuamos em uma consultoria em busca de profissionais para uma empresa do ramo educacional. Eles possuem mais de 20 anos nessa área e enxergam a área de Desenvolvimento como uma setor chave da empresa. Desejam ter grandes aprovações e com isso vestem a camisa para entregar valor ao nosso aluno. Tudo o que fazem e a própria existência se baseia na crença de desafiar o STATUS QUO e PENSAR DIFERENTE.

## Descrição da vaga

Gosta de grandes desafios? Tem foco no resultado? Possui alta flexibilidade? Está buscando um time multidisciplinar que utiliza tecnologia de ponta? 
Então vem atuar com a gente!
O desafio consiste em: Migrar de uma aplicação para Ionic5/Angular 9 de forma componetizada e testável.
A oportunidade é PJ, mas não para um projeto X. A ideia é que você siga agregando à equipe.

## Local

Remoto 

## Requisitos

**Obrigatórios:**
Typescript 
Angular (min versão 7)
Teste em Karma/Jasmine
Componentização
RxJS

_- Mínimo de 2 anos de experiência com os requisitos acima_

**Desejáveis:**
- Web components
- Cordova
- Ionic 4/5
- NgRx
- Experiência com metodologia ágil

**Diferenciais da oportunidade:**
- Possibilidade de vivenciar aplicativo, mobile e websites em um único time.

## Contratação

PJ - 70 à 100 reais (será testado conhecimento técnico)

## Como se candidatar

Por favor, envie um email para desenvolvedorpj@gmail.com com seu CV anexado - enviar no assunto: Vaga Typescript

## Tempo médio de feedbacks

Informaremos o recebimento do currículo. Se estiver no perfil faremos contato telefônico, DDD 21.
Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: desenvolvedorpj@gmail.com

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
