### ISSUE TITLE
[São Paulo] Front-end Developer (Júnior/Pleno) na Seed Incorp

### ISSUE THREAD

**Issue by stellamonfils-rh** [frontendbr/vagas#3374]
## Nossa empresa

A Seed lncorp é uma companhia que tem crescido e se destacado cada vez mais no ramo de incorporação e desenvolvimento imobiliário.  Investindo em inovação, conforto e funcionalidade como diferenciais de seus produtos, a empresa tem como foco transformar espaços em histórias, onde o bem-estar familiar é prioridade.
 
Na Seed lncorp, nossos colaboradores pensam como donos e trabalham com motivação, transparência e propósito, buscando sempre um impacto positivo, duradouro e que influencie ativamente a qualidade de vida dos clientes internos e externos.

## Descrição da vaga
Responsabilidades: 
 
· Implementar layouts responsivos, aplicando os princípios  de Mobile First
· Trabalhar em equipe multidisciplinar, usando metodologia ágil para criação e evolução de produtos;
· Escrever código limpo, reutilizável e de fácil manutenção;
· Ajudar a definir e manter padrões de design e arquitetura dos sistemas;
· Deployment, code review, documentação e monitoramento dos sistemas;
· Tomar decisões técnicas quando for preciso, envolvendo e alinhando equipe, clientes e stakeholders;
· Criar códigos semânticos, levando em consideração os princípios de SEO e principalmente de Acessibilidade;

## Local

São Paulo, SP - Zona Sul 
Escritório na região da Berrini. 

## Requisitos

**Obrigatórios:**
· Conhecer e usar testes unitários em seus projetos (usando qualquer framework ou biblioteca de testes conhecidos);
· Produzir sites que sejam performáticos, priorizando carregamento e utilizando os princípios de performance de código;
· Escrever código semântico e preparado para acessibilidade.
· CSS3
· HTMLS;
· JavaScript
· WebPack ou Gul p;
· APls REST;
Testes automatizados

**Desejáveis:**
- Conhecimento em linguagens Backend (Java,.NET,NodeJS)

**Diferenciais:**
- Será o primeiro desenvolvedor da empresa, vai ter bastante espaço para criar e desenvolver os projetos com a stack que achar mais adequada. 

##Remuneração: R$ 4.500,00 

## Benefícios

- Plano de saúde
- Plano Odontológico 
- VR de R$ 27,50

**Diferenciais:**
- Ambiente de start-up 
- Empresa em crescimento constante e dinâmica 
- Política de Home Office 

## Contratação

CLT 

## Como se candidatar

Por favor envie um email para stella.monfils@roberthalf.com.br com seu CV anexado - enviar no assunto: Desenvolvedor Seed 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: stella.monfils@roberthalf.com.br 

## Labels
- Presencial 

#### Regime
- CLT

#### Nível
- Pleno

**Comment by stellamonfils-rh** [comment]
@felipefialho , poderia remover o label de remoto? Em nenhum lugar da publicação a posição está descrita como remota. Tks!

**Comment by Lopacinsk1** [comment]
também poderiam adicionar que requer experiência comprovada em empresas, já que na vaga não diz em nenhum lugar sobre a necessidade de se ter experiência em "empresas"

**Comment by ArturRibeiro01** [comment]
Olá. 
No descrição da vaga está constando Desenvolvedor Junior /Pleno mas na descrição de nível apenas pleno. 
Desenvolvedores Jr também podem concorrer a vaga?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
