### ISSUE TITLE
[Remoto] Front-end Developer na Work In Ideas - WiiD

### ISSUE THREAD

**Issue by chgyn** [frontendbr/vagas#3376]
> Vaga Remota durante a pandemia

# Descrição da vaga

O candidato deverá estar capacitado a:
 - Executar projetos de desenvolvimento envolvendo o ReactJS ou VueJS
 - Implementar interfaces (Front-End) utilizando as HTML+ CSS + JS, React ou Vue

#### Conhecimentos necessários: 

 - HTML5
 - CSS3
 - Javascript (+ frameworks)
 - APIs Rest
 - VueJS ou ReactJS

#### Diferenciais:

Experiência com desenvolvimento front-end utilizando como base:
 - Laravel PHP
 - React Native
 - ReactJS
 - VueJS
 - Conhecer e saber como lidar em times que executam SCRUM
 - Consumo e utilização de APIs Rest

## Local

Sede física da empresa, Alpha Coworking (Av. T-1, 2266 - St. Bueno, Goiânia) - (híbrido presencial / remoto)

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento front-end 

**Desejáveis:**
- conhecimentos em Laravel PHP
- conhecimentos em API Rest
- Scrum

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para contato@wi-id.com com seu CV anexado - enviar no assunto: Vaga Front-End

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
