### ISSUE TITLE
[BH ou Manaus] Pessoa Desenvolvedora Front-end Pleno Méliuz

### ISSUE THREAD

**Issue by Folks-Meliuz** [frontendbr/vagas#3377]
## Méliuz

O Méliuz é uma empresa que desbloqueia relações inteligentes de consumo. Estamos em uma busca constante de melhorar a forma que nossos usuários fazem suas compras em nossas lojas parceiras, de maneira que todos saiam ganhando. Queremos que nossos parceiros continuem conosco para toda a vida e, para isso, estamos sempre levando inovações até eles. Tudo isso aliado ao nosso espírito empreendedor nos tornou na maior empresa de cashback do Brasil e tem nos proporcionado um crescimento consistente. Precisamos de uma pessoa para complementar nossa equipe fora da curva, que desenvolva front-end e esteja disposta a ter o resultado do seu trabalho sendo usado por milhões de pessoas.
O nosso time trabalha com Python, AWS, React e Next para renderização de páginas no servidor.

## Local
BH ou Manaus

## Você será responsável por:
- Desenvolvimento do nosso novo site em React.js.
- Manutenção e desativação do nosso antigo site em PHP.
- Criação e manutenção de aplicações para clientes internos, como administração de parceiros, ofertas e usuários.
- Prover soluções escaláveis, resilientes e altamente disponíveis, que sustentem picos de acesso.

**E precisamos que você tenha conhecimentos como:**
- HTML, CSS, JavaScript, PHP
- React.js

**Você vai se destacar se tiver:**
- ReactNative
- REST.API
- AWS: CloudFront, Caches, Edge@Lambdas, CloudWatch
-  Portfólio/Repositório com soluções em novos frameworks que você tenha criado.( React, Vue.js, Angular)
- Ser referência em tecnologias Web com participações em congressos e redes sociais com conteúdo relacionado e relevante.

## Benefícios
- Vale transporte
- Vale refeição ou alimentação;
- Plano de saúde;
- Plano odontológico;
- Horário flexível;
- Premiação por atingimento de metas coletivas;
- Convênio com Sesc;
- Biblioteca interna;
- Cashback online em dobro;
- Licença Maternidade/Paternidade estendida;
- Auxílio Creche;
- Auxílio luto

## Contratação
CLT

## Como se candidatar
Cadastre-se clicando [AQUI](https://jobs.lever.co/meliuz)

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
