### ISSUE TITLE
[São Paulo/SP | Presencial] Front-end Vue.js Developer @ Minery

### ISSUE THREAD

**Issue by betodoescher** [frontendbr/vagas#3381]
## Descrição da vaga

Buscamos por um perfil profissional com proatividade e comprometimento em entregar software com qualidade, contribuindo com conhecimentos e experiências para aumentar a qualidade técnica do próprio time. Atuará na construção do Front-end utilizando Vue.js.

## Aqui você irá

- Desenvolver código limpo, testável e de fácil manutenção
- Contribuir com todo o processo de desenvolvimento de software
- Crie e aprimore interfaces web com design visual previamente feito por UI/UX
- Contribuir nas discussões técnicas sobre os desafios encontrados
- Participar do processo de code review, garantindo qualidade e consistência do código

## Procuramos por pessoas que
- Sejam detalhistas e analíticas
- Gostem de lidar com projetos grandes e desafiadores
- Consigam trabalhar em equipe de forma colaborativa e em função de um objetivo comum
- Busquem aprendizado constante
- Queiram construir um ambiente de trabalho de respeito e apoio mútuo

## Requisitos

**Obrigatórios:**
- Experiência desenvolvendo aplicações complexas
- Domínio do Vue.js e Vuex, com experiência profissional / de produção
- Proficiente em Javascript, HTML5 e CSS3 modernos
- Sólido entendimento das integrações da API RESTful 
- Git
- Inglês técnico

**Desejáveis:**
- Quasar Framework
- Processos/Ferramentas de Integração Contínua
- Um olho afiado para design visual e UX é importante. A familiaridade com Sketch ou Figma é uma grande vantagem

**Diferenciais:**
- Projetos open-source

## Local

Escritório, São Paulo/SP - Zona Sul

## Contratação

- CLT
- Salário R$ 7.500

## Nossa empresa

Marketplace de commodities minerais, com o principal propósito de mapear, validar, registrar e expor mineradoras de pequeno e médio porte.
Desafiamos um sistema de negociação desatualizado e ineficiente ao construir um ambiente 100% digital, simples e seguro que atende às necessidades do mercado de mineração, sem intermediários. Através da Minery empresas do mundo todo poderão ter acesso a minérios ofertados pelos fornecedores cadastrados em nosso banco de dados.

## Como se candidatar

Por favor, envie um e-mail para klelber.doescher@census.inf.br com seu CV anexado. Enviar no assunto: _Vaga Vue.js_

#### Alocação
- Presencial

#### Experiência
- Pleno

#### Regime
- CLT

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
