### ISSUE TITLE
[São Paulo-SP] Front-end Developer na RSI 

### ISSUE THREAD

**Issue by ANA153426** [frontendbr/vagas#3382]
Front-End Developer Pleno e Sênior 

Vaga Remota durante a pandemia. 

## Nossa empresa

A Minds é uma consultoria de recrutamento e seleção com foco em demandas de tecnologia. Em parceria com a RSI Informática, buscamos um profissional para atuar em um projeto sem prazo determinado para um cliente do ramo de seguros. 

## Descrição da vaga

Requisitos:

- Irá atuar em um projeto do ramo de seguros.
- Sólidos conhecimentos desenvolvendo com Angular 6 ou superior, Typescript, Métodos ágeis e API Rest.
- Desejável vivência com Cloud - AWS ou Azure.

## Local

Remoto e pós-pandemia [São Paulo], [SP], [Estação Granja Julieta]

## Benefícios
● Plano de Saúde SulAmérica sem desconto mensal ao titular;
● Assistência Odontológica SulAmérica com 4 níveis de planos para escolher;
● Vale Refeição (R$ 428,12 mês) sem desconto;
● Vale Alimentação (R$ 167,00 mês), com desconto de R$ 1,00;
● Seguro de Vida sem desconto;
● Auxílio Creche para filhos com até 60 meses;
● Vale transporte com o desconto de 6%;
● Plataforma online de descontos em escolas, academias e muitos outros.

## Contratação

CLT | Não tem opção de ser PJ!

## Como se candidatar

Por favor envie um email para carolina@mindsrh.com.br com seu CV anexado - enviar no assunto: Vaga Angular 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: carolina@mindsrh.com.br

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
