### ISSUE TITLE
[Remoto] Front-End Developer na Bitwise

### ISSUE THREAD

**Issue by mendesbarreto** [frontendbr/vagas#3385]
## Descrição da vaga

Fala pessoal sou o [Douglas Mendes](https://github.com/mendesbarreto) atualmente sou o CTO da Bitwise e estou procurando pessoas capazes de produzir conteúdo Front-End para nossos projetos, no momento não procuro por conhecimento em tecnologias especificas como Angular ou React, se você é desenvolvedor é Web e é fera em alguma tecnologia que está sendo utilizada na atualidade mande seu CV.

## Local

100% Remoto

## Requisitos

**Obrigatórios:**
- Conhecimento em alguma das libs contemporáneas (ReactJS, Angular,  Vue.JS e etc.)
- HTML / CSS
- CSS
- JavaScript
- RESTful services
- SASS
- NPM ou yarn (para gerenciamente de pacotes/bibliotecas javascript)
- Repositórios: GIT (Hub/Lab/Flow);
- Saber criar testes unitários
- Frameworks de interface (ex: bootstrap).

**Desejáveis:**
- Banco de dados (relacional e/ou não relacional)
- TypeScript
- ElasticSearch (como noções de performance);
- Familiaridade com as novas especificações do EcmaScript.
- Desenvolvimento Ágil

**Diferenciais:**
- projetos opensource

## Contratação
- CLT
- PJ

## Nossa empresa

A Bitwise é uma comunidade dedicada e apaixonada por soluções tecnológicas e nosso objetivo é revolucionar o design e a criação de software. 

Nossa missão é ajudar nossos clientes a melhorar suas operações de mercado e desempenho com uma transição suave e rápido retorno do investimento, para alcançar estabilidade a longo prazo. Para isso, trabalhamos duro para capacitar nossas equipes e reforçar uma cultura com valores ágeis. 

Somos Humanos e amamos trabalhar com pessoas humanas, pode parecer estranha essa frase, mas pense bem nas empresas que você já trabalhou e em algum momento você foi tratado como um robô ou pior como recurso, aqui sabemos que nossos 'wisers' são a nossa assinatura, cultura e o motivo pelo qual nossa empresa existe.

## Como se candidatar

Por favor envie um email para vagas@bitwise.ltda com seu CV anexado - enviar no assunto: Front End

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

## Labels

- Alocado
- CLT
- PJ
- Freela
- Júnior
- Pleno
- Remoto
- Sênior

**Comment by nathanmrtns** [comment]
Tem site da empresa?

**Comment by RafaPalau** [comment]
> Tem site da empresa?

https://bitwise.ltda/ Acredito ser esse.

**Comment by mendesbarreto** [comment]
> > Tem site da empresa?
> 
> https://bitwise.ltda/ Acredito ser esse.

Esse mes rapaziada, infelizmente esta sendo finalizado ainda =) .

Abs.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
