### ISSUE TITLE
[Belo Horizonte - MG] Front-end Developer na Sinaxys

### ISSUE THREAD

**Issue by bielcapanema** [frontendbr/vagas#3386]
> Vaga Remota durante a pandemia

## Nossa empresa
https://sinaxys.com/

### Desenvolvedor Full-Stack (Web)
- Linguagem/framework: Ruby on Rails 6
- Banco de dados: PostgreSQL
- Front-end: HTML/CSS, Sass, JavaScript, Bootstrap 4
- Infra/DevOps: Linux Ubuntu, Nginx, Phusion Passenger
- Conhecimentos de Git (nossos repositórios estão no GitHub).
- Desejável experiência com desenvolvimento de REST APIs, boas práticas de programação e código limpo. Conta e projetos no GitHub valem pontos.

---

### Desenvolvedor Mobile (React Native)
- Desenvolvimento em React Native para ambos Android e iOS.
- Atribuições: desenvolvimento de novos recursos e manutenção em aplicativo mobile já em produção e integração com REST API.
- Software de design: Figma

- Experiência com Storybook
- Conhecimentos de Git (nossos repositórios estão no GitHub) e deploys na AppStore e Google Play.
- Diferencial: boas práticas de programação e código limpo. Conta e projetos no GitHub valem pontos.

## Local

Exemplo: Remoto ou Escritório, MG, Belo Horizonte, Av. Contorno

## Contratação

PJ ou CLT

## Como se candidatar

Por favor envie um email para bernardo@sinaxys.com com seu CV anexado - enviar no assunto: Vaga Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Alocado

#### Regime
- CLT
- PJ

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
