### ISSUE TITLE
[Remoto] Pessoa Desenvolvedora Mobile na Magnetis

### ISSUE THREAD

**Issue by recruiter-felipe** [frontendbr/vagas#3388]
## Nossa empresa

**SOBRE A MAGNETIS**
A Magnetis é uma fintech e gestora de investimentos digital que desde 2015 tem a missão de ajudar as pessoas a investir no que importa. Dentro do nosso ambiente de trabalho, seguimos esta regra: investimos nas pessoas que trabalham com a gente e buscamos um ambiente de diversidade e inclusão.

**SOBRE O TRABALHO E O TIME**
Cada pessoa desenvolvedora nos ajuda a construir um produto cada vez melhor, participando do ciclo de concepção de novas funcionalidades, auxiliando nas decisões técnicas e realizando manutenção do código produzido. Nos organizamos em times multidisciplinares, que permitem que todos participem da concepção, planejamento, testes e lançamento do produto. 

Entendemos que o segredo do sucesso é o compartilhamento de conhecimento, comunicação e pair programming uma vez que quase todo nosso time está remoto em diversos estados do Brasil (você também terá acesso ao nosso escritório em São Paulo, caso queira trabalhar presencialmente). 

Nós valorizamos pessoas que reconhecem as próprias falhas e falam abertamente sobre elas. Errar não é um tabu dentro do time e esperamos um plano de ação dos aprendizados. Autonomia e responsabilidade são outros dois pontos vitais que fazem com que as entregas sejam cumpridas em dia sem microgerenciamento. 

## Descrição da vaga

Estamos buscando uma pessoa que tenha interesse em trabalhar em ambiente de desenvolvimento de produtos, com autonomia e com mudanças constantes.

## Local

Remoto

## Requisitos

**Hard Skills:**

- Experiência com desenvolvimento em React Native (ou linguagem correlata como Flutter) para aplicações críticas ao negócio.
- Experiência com desenvolvimento de software voltado para qualidade (TDD ou BDD).
- Conhecimento em versionamento de código utilizando Git/Github/GitLab. 
- Experiência com equipes ágeis (Kanban, scrum,XP). 
- Habilidade de atuar no processo de definição de arquitetura de soluções de software.
- Conhecimento em inglês para escrita de comentários, revisão de PRs e leitura.

**Desejáveis:** 

- Experiência com escrita de testes automatizados.
- Habilidade em design de aplicações pensando em boas práticas de integração, performance e segurança.
- Prévia experiência em startups ou e-commerces.
- Experiência com mentoria de novos membros do time.
- Experiência em construção de apps para dispositivos móveis em React Native, iOS Nativo ou Android Nativo
- Experiência com Mobile Ops - Build, testes e processo de deploy para apps móveis (iOS and Android)

 

**Soft Skills:** 

- Transparência.
- Proatividade.
- Paixão por desenvolvimento de produto e/ ou mercado financeiro.
- Ótima comunicação escrita e oral. 
- Comprometimento com prazos e entregas.

## Benefícios

Na Magnetis você terá a oportunidade de trabalhar em ambiente diverso, flexível e inovador. Alguns dos nossos benefícios são:

- Plano de saúde e Odontológico
- Vale-refeição / vale-alimentação
- Vale-transporte
- Oportunidade de ganhar stock options (participação na empresa)
- Verba educacional para participação em cursos e eventos
- Flexibilidade para trabalho remoto ou no nosso escritório próximo a estação Faria Lima do metrô
- Para remotos fora da cidade São Paulo: ajuda de custo para você montar o seu ambiente ideal de trabalho
- Gympass

## Contratação

CLT

## Como se candidatar

Pode se candidatar automaticamente neste link: https://jobs.kenoby.com/magnetis/job/pessoa-desenvolvedora-mobile-react-native-remoto/5e0505e680486353497b0d01

Ou se tiver alguma dúvida envie um email para felipe.silveira@magnetis.com.br 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: felipe.silveira@magnetis.com.br 

#### Alocação

- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by GuilhermeLis** [comment]
essa vaga aimda está aberta?
