### ISSUE TITLE
[São Paulo] Front-end Developer na Take 5

### ISSUE THREAD

**Issue by alexpvieira** [frontendbr/vagas#3389]
- Pessoa Desenvolvedora com experiência utilizando frameworks JavaScript no front-end (Vue.js, React, Angular)

- Conhecimento em desenvolvimento mobile híbrido (Cordova) é um diferencial

- Conhecimento em Quasar é um diferencial

- Conhecimento em ferramentas AWS e Google Firebase é um diferencial

Disponibilidade imediata
Local de trabalho: remoto durante a pandemia e após ela próximo a estação Berrini CPTM
Horário: segunda a sexta, das 09h às 18h
Regime de contratação: CLT
Benefícios: VT e VR
Salário: a combinar

Enviar CV para o email: contato@take5.com.br

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
