### ISSUE TITLE
[Rio de Janeiro] Front-End Developer na Totvs Hospitality

### ISSUE THREAD

**Issue by totvs-challenges** [frontendbr/vagas#3392]
> Vaga Remota durante a pandemia - em Analise após o periodo de pandêmia

## Nossa Empresa

A TOTVS possui uma visão tecnológica e uma história de impacto para se orgulhar.

Nossa cultura de inovação é focada no desenvolvimento de soluções diferenciadas para empresas de todos os portes e segmentos, incluindo softwares de gestão (ERP), plataformas de inteligência artificial, novos negócios e consultoria.

Assim, Impactamos os negócios de mais de 30.000 clientes em escala global há quase quatro décadas.

Em cada etapa desta constante evolução, nossos TOTVERS, compartilhando uma paixão por colaboração, aprendizado constante e impacto significativo, contribuem para esse legado de sucesso.

Estamos convidando talentos com mentes inovadoras e voltadas à tecnologia, para continuar escrevendo essa história junto com a TOTVS em um ambiente de ritmo acelerado. Aqui você vai encontrar grandes desafios todos os dias, onde a mudança e o aprendizado são parte da nossa rotina.

Venha fazer parte do nosso time. Nossa marca na história da tecnologia continuará sendo escrita por você.

#SOMOSTOTVERS

## Descrição da Vaga
Nossa meta é revolucionar o setor de Hospitalidade!
Estamos com alguns projetos que estão crescendo bastante e com grandes desafios.
Nossas aplicações estão sendo desenvolvidas com foco internacional, dessa forma lidamos com todos os desafios de criar um sistema que atenda usuários dentro e fora do Brasil.
Nossas stack é toda em Angular 9+, com gerênciamento de estados com @ngrx.

## Local

Remoto ou Escritório: RJ, Rio de Janeiro, Centro

## Requisitos
- Amplo conhecimento em Javascript
- Conhecer Typescript 3.7+
- Sólidos conhecimento em orientação a objeto
- Versionamento de código com Git
- Experiência com Angular
- Ter experiência com arquitetura Flux e gerenciamento de estados
- Desenvolver Testes unitários
- Ter conhecimento com padrões Observable e operadores. ( rxjs )

## **Desejáveis**
 - Conhecer ngrx
 - Ter trabalhado com monorepositório
 - Conhecer fundamentos de clean Code

## Benefícios
- Plano de saúde
- Plano Dental
- Seguro de vida
- VR de R$ X/dia
- Auxílio creche

**Diferenciais:**
- Plano de Saude e Odontologico
- Vale transporte
- Vale refeição
- Previdência privada
- Seguro de Vida
- PLR
- Gympass

## Contratação
CLT - pretenção salárial

## Como se candidatar

Enviar email para souza.nagila@totvs.com.br com o assunto "vaga Frontend Sênior" com seu CV e linkedin.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
