### ISSUE TITLE
[Rio de Janeiro] Front-end Developer na inChurch

### ISSUE THREAD

**Issue by talitaclerc** [frontendbr/vagas#3393]
> Vaga Remota durante a pandemia

## inChurch

Bom, nós somos a InChurch, uma startup referência na construção de aplicativos para o terceiro setor na América Latina.
Você irá trabalhar em nosso escritório, na Barra da Tijuca, em um ambiente informal e descontraído! Se você você busca um crescimento acelerado e muita autonomia para fazer acontecer, essa vaga é pra você!

## Descrição da vaga

- Desenvolver funcionalidades para nossas plataformas de comunicação, inscrições em eventos, gestão financeira e de membros dentre outras, junto com o nosso time de desenvolvedores.
- Criar variantes do layout original de uma aplicação whitelabel

## Local

Remoto ou Escritório, Rio de Janeiro, Rio de Janeiro, Barra da Tijuca

## Requisitos

**Obrigatórios:**
- Domínio da linguagem Angular/AngularJS .
- Familiaridade com integração APIs REST.
- Experiência em versionamento de projetos com Git.

## Benefícios

- VT ou Vale Auto (Benefício Flexível)
- Vale refeição (Benefício Flexível)
- Assistência Médica
- Assistência Odontológica
- Academia
- Universidade Corporativa (Alura)
- Cultura interna de aprendizado constante

**Diferenciais:**
- sala de descompressão (piscina de bolinha)
- clima descontraído
- lanches da meta
- festas de aniversário

## Contratação

CLT ou PJ

## Como se candidatar

Para participar do processo, basta enviar um e-mail para rh@inchurch.com.br com o assunto “Desenvolvedor Front”, anexando currículo ou enviando a URL do seu Linkedin, junto a sua pretensão salarial.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.

#### Regime
- CLT
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
