### ISSUE TITLE
[São Paulo] Front-end Developer na MZ

### ISSUE THREAD

**Issue by Teusegantine** [frontendbr/vagas#3394]
> Vaga Remota durante a pandemia

## MZ 

É uma empresa que opera no modelo B2B e desenvolveu uma plataforma "100% customizável" de relacionamento com investidores para seus clientes que são empresas listada na bolsa de valores.

## Especialista Front-End

JavaScript (ReactJS) / HTML / CSS
Que tenha trabalhado com desenvolvimento e manutenção de aplicações web.

## Requisitos
**Obrigatórios:**
- 4 anos de experiência com React

**Desejáveis:**
- Experiência com Git para versionamento de código
- Desenvolvimento Mobile (React Native) 
- Angular / Vue 

## Benefícios

- Férias remuneradas

## Contratação

PJ 8k a 11k (a combinar)

## Como se candidatar

Por favor envie um email para sega@jobler.com.br com seu CV anexado - enviar no assunto: Vaga FRONT END (REACT)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
