### ISSUE TITLE
[São José dos Campos/SP] Full Stack Developer Vue + Node @ SoluCX

### ISSUE THREAD

**Issue by thaisnakamura** [frontendbr/vagas#3396]
> Vaga Remota durante a pandemia

## Conhece a SoluCX?
A [SoluCX](https://solucx.com.br/) é uma startup joseense que entrega detalhes sobre a Experiência dos Clientes de grandes empresas por meio de Pesquisas de Satisfação transacionais que utilizam os dados para dar maior clareza aos seus resultados. 
Estamos mudando a maneira como as Pesquisas de Satisfação são realizadas e precisamos de pessoas feras para fazer parte do nosso time.

## Seu desafio no dia a dia
- Desenvolver interface de usuário usando o Vue.js;
- Desenvolver aplicações Back-end Node Typescript seguindo as melhores práticas de desenvolvimento;
- Manter-se atualizado com as recentes novidades no mundo Front-end e Vue.js;
- Implementar testes automatizados integrados aos fluxos de trabalho de desenvolvimento e manutenção;
- Integrar serviços third-party, como gateways de pagamento, ferramentas de e-mail marketing e cloud computing;
- Desenvolvimento de projeto a partir de Testes (TDD);
- Criar e/ou alterar banco de dados das aplicações.

## Demais atividades envolvidas
- Construir bibliotecas e componentes modulares e reutilizáveis;
- Implantar ações de suporte (corretivas e/ou de manutenção);
- Propor as atualizações necessárias para acompanhar as práticas recomendadas de segurança e desenvolvimento modernas;
- Contribuir em decisões de arquitetura sobre novas partes do projeto;
- Aplicar técnicas de segurança da informação orientadas aos sites e aos dados.

## Nós esperamos de você
- Altamente proficiente com a linguagem JavaScript e Typescript e sua sintaxe e recursos modernos do ES6+;
- Altamente proficiente na estrutura do Vue.js e seus princípios fundamentais, como componentes, reatividade e o DOM virtual;
- HTML5 e CSS3;
- Node.js;
- Consumo e o design de APIs RESTful;
- Proficiente conhecimento das ferramentas de versão de código, como Git;
- Familiaridade com o ecossistema Vue.js, incluindo Vue CLI, Vuex, Vue Router e Nuxt.js;
- Framework NestJS;
- Framework Type ORM;
- Testes automatizados de Typescript, testando especificamente estruturas como Jest ou Mocha;
- Conhecimento de programação funcional e paradigmas de programação orientada a objetos;
- Modelagem de banco de dados relacionais;
- Gerenciamento de Banco de dados (Mysql);
- Conhecimentos em SO Linux;
- Tecnologias serverless, como FaaS (Cloud Functions, Amazon Lambda e OpenFaas).

**Pode ser um diferencial:**
- Ao desenvolver, manter sempre em mente as melhores práticas relacionadas à segurança;
- Capacidade de escrever código eficiente, seguro, bem documentado e limpo;
- Compreensão do processo de aquisição, tratamento e enriquecimento de dados;
- Controle de versionamento Git;
- Experiência em desenvolvimento de projetos em Metodologias Ágeis;
- Graduação na área (Ciência da Computação, Tecnologia em Processamento de Dados, Engenharia da Computação) ou experiência similar;
- Gestão da segurança de dados e de sistemas;
- Uso de ferramentas ágeis para controle de demandas.

## Observações
- Proposta PJ;
- Presencial (com flexibilidade de horário, alguns dias de home office por semana - no momento, 100% remoto);
- Aqui o ambiente é de muita autonomia, aprendizado e desafios;
- O escritório é informal, descontraído e com pessoas incríveis;
- Temos vale-transporte;
- Também temos cursos in-company (técnicos, línguas).

Para se candidatar, [clique aqui](https://solucx.com.br/talento-full-stack-pleno-vuejs-e-node-typescript/) (:

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Pleno
- Senior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
