### ISSUE TITLE
[Valinhos/SP e Londrina/PR] Analista e Especialista de Sistemas na Platos Educação

### ISSUE THREAD

**Issue by carolgdsouza** [frontendbr/vagas#3397]
**Faça parte do time de uma startup do grupo Cogna, uma das maiores empresas de educação do mundo!** 
-> **https://byintera.in/w7**

## Nossa Empresa

A Platos faz parte da nova holding Cogna Educação, uma das principais organizações educacionais do mundo, e atende ao mercado B2B do Ensino Superior. Seguindo o conceito de EdServ Platform (plataforma de serviços educacionais), a companhia oferta uma série de serviços e soluções para as 
instituições de ensino superior de todo o país. Atualmente, a Platos atende 176 IES da Kroton e tem cerca de 40 contratos com IES terceiras com a solução Saraiva Educação. 

## Descrição da vaga Analista e Especialista

Desenvolvimento de API’s Restful
Criação de testes unitários
Vivência em práticas, técnicas e metodologias ágeis
Espírito colaborativo
Criação de scripts de bancos de dados
Ajuda nas definições arquiteturais de sistema.

**Alem disso o especialista é** 
Responsável pela criação de soluções técnicas dos Squads
Disseminação de ferramentas, técnicas e soluções de mercado
Mentoria para os desenvolvedores com menos experiência.

## Local

Presencial em Valinhos-SP ou em Londrina-PR com possibilidade de flexibilização 

## Requisitos

**Obrigatórios:**
-  Experiência com Java ou Javascript

**Desejáveis:**
Java 8 ou superior
Spring Boot/Micronaut
Gradle
API Restful
Kubernetes
PostgreSQL
GIT
React
React Native
Redux
Javascript ES6
HTML 5
CSS 3
MongoDB (para especialista)

**Diferenciais:**
AWS
Kafka
GitLab CI
System Design (para especialista)
Prototipação de interfaces (para especialista)
Experiencia com times ágeis  

## Benefícios
- Programa de Participação nos Resultados – PRV;
- Assistência Médica e Odontológica;
- Vale Alimentação/Refeição em Londrina e Restaurante em Valinhos
- Vale Transporte;
- Seguro de Vida;
- Bolsa Estudantil (em Valinhos extensiva a dependentes legais (cônjuge e filhos))

## Contratação
CLT

#### Nível
- Pleno
- Sênior
- Especialista

## Como se candidatar
Acesse o Link para se candidatar e para obter mais informações: **https://byintera.in/w7**

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
