### ISSUE TITLE
[São Paulo] Desenvolvedor Front-End - Iterative

### ISSUE THREAD

**Issue by LFeh** [frontendbr/vagas#34]
## Descrição da vaga

Desenvolvedor Front-End Pleno ou Sênior. 

## Local

Alocado, Pinheiros - São Paulo/SP

## Benefícios

- Trabalhar de bermuda
- Jogar um vídeo-game
- Horário Flexivel
- Participação no lucro trimestral
- Trabalhar com o lindo do [Guilherme Garcia](https://www.facebook.com/gui.garcialife?fref=ts)

## Requisitos
 
- HTML
- CSS (Pré-processadores)
- JavaScript
- Task Builders (Grunt, Gulp..)
- AngularJS
 
## Contratação

PJ, R$ 6,000,00

## Nossa empresa

http://www.iterative.com.br/

## Como se candidatar

Por favor envie um e-mail para guilherme.garcia@iterative.com.br com seu CV anexado e portfólio - enviar no assunto: Vaga - Desenvolvedor Front-End

**Comment by angusyoung84** [comment]
Pessoal, o email não está indo, dando 500 no such user.

**Comment by LFeh** [comment]
@angusyoung84 Comuniquei o responsável aqui :)

**Comment by LFeh** [comment]
Era .com.br :worried:

**Comment by angusyoung84** [comment]
Valeu @LFeh !

**Comment by camilatigre** [comment]
@LFeh 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
