### ISSUE TITLE
[Belo Horizonte] Front-end Developer Sênior na Agência Open

### ISSUE THREAD

**Issue by PriscilaRocha** [frontendbr/vagas#3400]
> Vaga remota durante a pandemia

## Nossa empresa
Aqui na Agência Open vivemos intensamente muitas aventuras e hoje, tem uma reputação louvável. Vencemos muitos desafios e atendemos diversos clientes de renome.

Agora, como uma verdadeira veterana do marketing digital, se especializou em mais de 23 skills para atender as missões de mais de 300 clientes. Essas proezas foram conquistadas por uma equipe de pelo menos 50 bravos guerreiros e você pode fazer parte dessa party!

## Descrição da vaga

Responsável por:
• Planejar e executar com a equipe a organização do código Front End;
• Definir e aplicar boas práticas de desenvolvimento Front End;
• Contribuir nas discussões técnicas sobre os desafios encontrados no dia a dia.
• Avaliar junto com os membros da equipe, a adoção de novos componentes e tecnologias;
• Gerenciar o versionamento de controle(Azure) dos projetos Front End
• Desenvolver o novo front-end das aplicações atuais
• Manutenção do código atual e a desativação dele a medida que for migrado para os novos front-ends
 
E precisamos que você tenha avançados em:
• HTML 
• CSS 
• JavaScript 
• Angular 
• TypeScript 
Saiba integrar com APIs Rest e noções de segurança com JWT;
 
Diferenciais
• Conhecimentos de SEO
• Conhecimentos em Browsers Storages
• Conhecimentos de PWA
• Noções Node e algum banco de dados NoSql
• Docker
• Azure

## Local

Em período de pandemia estamos remoto, MG, Belo Horizonte, Cidade Jardim. 

## Requisitos

**Obrigatórios:**
• HTML 
• CSS 
• JavaScript 
• Angular 
• TypeScript 
Saiba integrar com APIs Rest e noções de segurança com JWT;s

**Desejáveis:**
- Fazer parte de comunidades de tecnologia

**Diferenciais:**
• Conhecimentos de SEO
• Conhecimentos em Browsers Storages
• Conhecimentos de PWA
• Noções Node e algum banco de dados NoSql
• Docker
• Azure

## Benefícios

- Plano de saúde
- Seguro de vida
- VR ou VA de R$ 20/dia
- Vale transporte ou combustível

## Contratação

CLT no momento. 

## Como se candidatar

Por favor envie um email para gente@agenciaopen.com com seu CV anexado - enviar no assunto: Vaga FRONT END SENIOR

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
