### ISSUE TITLE
[Remoto] Front-end Developer React.js na Restfy

### ISSUE THREAD

**Issue by joaofidelix** [frontendbr/vagas#3401]
## Nossa empresa

Desenvolver software é nossa paixão.
Construímos aplicações para brilhar os olhos de nossos clientes. Nosso foco é em segurança digital e rastreabilidade de processos.

## Descrição da vaga

Desenvolvimento de software de rastreabilidade interligado com o SERPRO.
Front React.js

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com React.js
- Material UI / Ant Design / BootStrap

**Desejáveis:**
- AWS
- Figma
- Gulp, Grunt, Webpack
- SASS, LESS
- Redux

**Diferenciais:**

- projetos opensource

## Benefícios

- Via Cooperativa

## Contratação

Cooperado.
Junior
Pleno

## Como se candidatar

Candidatura Enviar CV por e-mail: vagadev@restfy.com.br

#### Alocação
- Remoto

#### Regime
- Cooperado
- Freela

#### Nível
- Júnior
- Pleno

**Comment by thalesf** [comment]
Vocês aceitam part-time job ?

**Comment by joaofidelix** [comment]
> Vocês aceitam part-time job ?

Apenas Full time.
