### ISSUE TITLE
[Remoto/Curitiba-PR] Sr. Front-End Developer (Javascript + React) na Pipefy 

### ISSUE THREAD

**Issue by danielnass** [frontendbr/vagas#3402]
### Job Description:
We are looking for a great JavaScript developer who is proficient in React. Your primary focus will be on developing new user-facing features, implementing them following well-known React workflows with State Management and interaction with our GraphQL API.

You will ensure that the application is robust, easy to maintain, understand and extend.

Commitment to collaborative problem solving, sophisticated design, and quality are important.

We are also ramping up our Typescript usage, so if that is something that interests you, come work with us!

### What you'll do:
- Developing new user-facing features using React;
- Building reusable components and front-end libraries for future use;
- Developing components for a vast array of web-capable devices and browsers.

### What We Need You to Have:
- Proficiency in JavaScript, including DOM manipulation and the JavaScript object model;
- Thorough understanding of the Component - Model style of programming;
- Experience with state management in React;
- Knowledge of isomorphic React is a plus;
- Familiarity with RESTful and GraphQL APIs;
- Knowledge of modern authorization mechanisms, such as JSON Web Token;
- Familiarity with modern front-end build pipelines and tools;
- Experience with common front-end development tools such as Babel, Yarn, NPM, etc.;
- Ability to understand business requirements and translate them into technical requirements;
- Familiarity with Git.

### It Would be Awesome if:
- Knowledge of Typescript/Flow
- Interest on benchmarking and optimization;
- CSS knowledge
- HTML semantic

### What You’ll Get in Return:
- Fast-paced environment full enormous challenges and the possibility to create a global brand.
- All the tools you might need to make a great work (We´ll save no Money to make you feel ready to overcome all these challenges).
- Get to work on an ambitious project, with great professionals, with an entrepreneurial mindset and great technical skills.
- Awesome kitchen with a lot of things for you!
- Pet-friendly and open-minded environment that values diversity :)

### Benefits:
- Semi-Flexible Hours (40h/ week).
- A casual and international environment – Be who you are and meet other cultures every day.
- Gympass.
- A competitive compensation package.
- Health and Dental Insurance.
- Meal Allowance.
- Bus pass.

### Pipefy: The Work Management Platform – Meet Us:
We believe that when do-ers have the tools they need to improve their work, without relying on anyone else, there’s no limit to what they can accomplish. We make it easy for anyone to streamline recurring business processes on their own, from employee onboarding to customer service to agile development. Our customizable, template-driven software helps people eliminate wasted time and effort and become more agile and efficient.

## Contratação

CLT

## Como se candidatar

You can apply to the job from here https://portal.pipefy.com/5c1ee32e-0d38-4b6f-b026-6dedd81c6d50

Good luck 🍀 and if you have any question, just comment here 😄

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by danielnass** [comment]
@felipefialho atualizei o título para o bater com a vaga do site de contratação. Obrigado! 🚀
