### ISSUE TITLE
[São Paulo e Brasil] Front-end Developer - One Choice Recrutamento

### ISSUE THREAD

**Issue by OneChoiceRH** [frontendbr/vagas#3403]
-->
> Vaga Remota durante a pandemia

## Nossa empresa
Olá, nós somos a One Choice, uma empresa que faz seleção e recrutamento de talentos de TI. 
Veja as vagas em aberto para Front End https://www.onechoice.com.br/vagas/681

Temos diversas outras vagas abertas em nosso site

## Descrição da vaga
 Estamos buscando devs que tenham os seguintes conhecimentos:

• HTML5
• CSS
• JavaScript (ES6) (se souber React é legal)

## Contratação

CLT

## Como se candidatar

Por favor envie um email para talentos@onechoice.com.br com seu CV anexado, pretensão salarial e nome da vaga - enviar no assunto o nome da vaga

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
