### ISSUE TITLE
[Remoto] Front-end Angular 2+ Developer na Bume

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#3406]
## Nossa empresa

O Bume é uma plataforma de gestão, marketing e vendas nas redes sociais. A empresa ajuda desde pequenos a grandes negócios, autônomos e especialistas a monetizarem seus conteúdos e a impulsionar resultados.

De maneira prática, a plataforma permite que o profissional possa vender mais nas redes sociais, captando leads e monetizando seu conteúdo. Conheça nossas principais funções:
- Agendamento de posts nas principais redes sociais
- Gestor de Close Friends
- Bume Pages
- Bume Leads
- Relatórios avançados

Através desses recursos, contribuímos para que as pequenos negócios possam vender nas redes sociais.

## Descrição da vaga

Estamos buscando pessoas desenvolvedoras fullstack com foco em front-end Angular 4+.

O time de desenvolvimento é o coração do Bume. Por causa dele, conseguimos entregar aos nossos clientes uma ferramenta incrível para gestão e crescimento de redes sociais, utilizando o que há de mais inovador entre as tecnologias do mercado.

**No Bume, você encontrará:**

- Desafios relacionados a desenvolvimento de produtos;
- Oportunidade de trabalhar com algumas das tecnologias mais atuais do mercado;
- Oportunidade de participar de novos projetos de longo prazo com ambição de alcance internacional;
- Um time de profissionais empreendedores em um ambiente dinâmico e em crescimento constante;
- Um ambiente flexível e informal.

## Local

Remoto

## Requisitos

- Fluente em Javascript ou Typescript
- Últimos 2 anos trabalhando com front-end em framework javascript moderno (Angular 2+)
- Ter experiência com Bootstrap, CSS e HTML Semântico
- Tenha conhecimento em versionamento de código (GIT)
- Tenha boa comunicação e trabalho em equipe
- Siga as tendências do mercado e que seja capaz de se adaptar rapidamente a novas tecnologias
- Tenha senso de organização, atenção a detalhes e foco
- Bom entendimento de cultura em startup (Lean Startup)
- Sente responsável pelo produto como um todo (Não se importa de sujar as mãos)
- Inglês intermediário (capaz de ler e escrever, será utilizado principalmente para estudo e leitura de documentações)

**Diferenciais:**

- Tenha experiência de atuação em back-end usando C#
- Tenha experiência em desenvolvimento de WebApi e serviços de background em .NET
- Tenha noções de docker e linux
- Tenha noções de cloud e bancos No-SQL
- Já tenha trabalhado em uma equipe ágil

## Benefícios

- Salário compatível com o mercado e com a sua habilidade técnica
- Vale transporte sem desconto (quando trabalhando na empresa)
- Vale refeição ou alimentação
- Plano de saúde e odontológico Unimed
- Unimed aéreo
- Frutas à vontade no lanche
- PLR
- Uma conta do Bume todinha sua
- Aulas de inglês 50% custeada pelo bume
- Flexibilidade de horário
- Trabalho remoto
- No dress-code

## Contratação

PJ ou CLT

## Como se candidatar

Candidatar-se em: [https://bit.ly/2XzQ98P](https://bit.ly/2XzQ98P)

## Tempo médio de feedbacks

E-mail para contato em caso de não haver resposta: contato@coodesh.com

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
