### ISSUE TITLE
[Remoto] Full-stack Developer (Firebase/NodeJS/Angular/Flutter) no Meu Vizinho

### ISSUE THREAD

**Issue by ruandeveloper** [frontendbr/vagas#3407]
O [Meu Vizinho](https://meuvizinho.me) é uma plataforma que conecta negócios locais com seus vizinhos

## Local

100% Remoto

## Requisitos

**Obrigatórios:**
- Experiência com Typescript
- Experiência com Angular 2
- Experiência com ferramentas de versionamento de código (GIT);
- Experiência com Firebase (Auth, Firestore, Cloud Functions)
- Experiência com prototipagem (de preferência utilizando o Figma)
- Experiência com desenvolvimento mobile
- Experiência com Flutter
- Experiência com NodeJS

**Desejáveis:**
- Experiência com AWS ou Google Cloud
- Experiência com MongoDB
- Experiência com testes unitários

**Diferenciais:**
- Experiência com arquitetura de micro serviços

## Contratação

Freela

## Como se candidatar

Por favor envie um email para vizinhome@gmail.com com seu CV anexado - enviar no assunto: Vaga Freela

#### Alocação
- Remoto

#### Regime
- Freela

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
