### ISSUE TITLE
[São Paulo] Front-end Developer na Bettha

### ISSUE THREAD

**Issue by Bettha20** [frontendbr/vagas#3409]
> Vaga Remota durante a pandemia

## Nossa empresa

Nós somos o Bettha, a primeira HR Tech do Brasil a atrelar engajamento, employer branding e educação ao processo de recrutamento de estagiários e analistas.

Acreditamos no match entre empresas e colaboradores e pra fazer ele acontecer, usamos algoritmos inteligentes que mapeiam e cruzam o perfil de empresas e candidatos durante o processo seletivo para tornar as contratações mais rápidas e assertivas. Como nosso nome já diz, o nosso propósito é ser melhor a cada dia: bettha (better than yesterday, everyday).

O lema move quem trabalha por aqui, os usuários da nossa plataforma e as empresas que contratam com a gente. Somos a conexão entre empresas, jovens e o futuro. #soubettha

## Descrição da vaga

Buscamos candidatos de alto desempenho que queiram crescer conosco, apaixonados por Desenvolvimento de interfaces web, fluxos e navegações, sempre buscando a melhor UX, que não se limitam a descrição de cargo e sim que envolva no projeto contribuindo com seu conhecimento e que tenha paixão por novas tecnologias.

Temos uma Stack com Core sendo Ruby on Rails e AngularJS e Angular 2+

## Local

CENU, São Paulo

## Requisitos

**Obrigatórios:**
HMTL & CSS,  JavaScript,  AngularJS, Angular, Git,  Linux

**Desejáveis:**
Redis,  Sidekiq,  Rspec,  Docker,  AWS, PostgreSQL, XD, Figma e SEO

**Diferenciais:**
-Ambiente colaborativo, com grande autonomia e baixa burocracia. 

-Contratação PJ                        

-Horário flexível

-Home office 

-Gestão horizontal

## Benefícios

Contratação PJ

## Contratação

PJ R$7.000,00

## Como se candidatar

Entre no [ link](https://www.bettha.com/vagas/1310-front-end-pleno) e se cadastre na vaga!

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 30 dias após cada processo.
E-mail para contato em caso de não haver resposta: contato@bettha.com

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível

- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
