### ISSUE TITLE
[São Paulo] Front-end Developer (Vue.js) na Juntos Somos Mais

### ISSUE THREAD

**Issue by felipefialho** [frontendbr/vagas#3410]
<p align="center"><img src="https://assets-img.juntossomosmais.com.br/images/logo.svg" width="300"></p>

Somos a Juntos Somos Mais, o maior programa de fidelidade do varejo de material de construção e maior marketplace B2B do setor.

Fomos criados em 2018, por 3 gigantes do setor (Votorantim Cimentos, Gerdau e Tigre), com o propósito de fortalecer o varejo e transformar a vida dos profissionais que constroem sonhos. Estamos crescendo a passos largos, já são mais de 20 empresas e 250 mil membros no programa de fidelidade.

## Descrição

Precisamos de alguém que vá além de códigos e entenda que desenvolvemos aplicações para pessoas usarem. Sendo assim, você estará livre para propor melhorias, novas ideias, compartilhar conhecimento e participar ativamente de todas as partes da concepção do produto 😁

Importante ter boa capacidade de comunicação e visão de negócio, você vai atuar em um time multidisciplinar.

Nessa vaga vamos precisar de alguém que atua ou já tenha experiência com **Vue.js**.

Temos alguns [repositórios abertos no nosso Github](https://github.com/juntossomosmais), caso queira dar uma olhada em alguns dos nossos projetos 😋

## Localização

Estamos localizados na região da Vila Olimpia em São Paulo, bem próximo da estação de trem e do shopping.

## Responsabilidades

- Atender às necessidades do negócio
- Manutenção e evolução dos produtos
- Construir códigos com qualidade e testáveis
- Estudar e implementar novas tecnologias
- Foco no usuário

## Skills

- HTML, CSS e JavaScript
- Experiência com Vue.js
- Arquiteturas e metodologias CSS
- Componentização
- Testes
- Cuidado com UI/UX
- Git

## Desejáveis

- Design System
- Cultura open source
- Ter atuado em times ágeis (Kanban, Scrum)
- Conhecer e gostar de discutir sobre UI/UX

## Diferenciais

- Typescript

## Benefícios

- CLT
- Plano de Saúde
- Plano Odontológico 
- Seguro de Vida
- Vale Refeição
- Vale-transporte ou subsídio estacionamento
- Bônus (Remuneração variável)
- Gympass – para sua saúde e bem-estar!
- Home office semanal
- Equipamento de última geração ([MacBook Pro](https://www.apple.com/br/macbook-pro-13/specs/))

## Ambiente 

- Videogame e ping-pong 🎮
- Frutas e snacks todos os dias 🍓
- TechTalks internas - quinzenais 
- TechTalks [externas - mensais](https://www.youtube.com/watch?v=6uWzv_P_Ui0)

## Como se candidatar

1. Aplicar na [vaga cadastrada na Gupy](https://juntossomosmais.gupy.io/jobs/269209?jobBoardSource=gupy_public_page)
2. **Após nosso contato** faça [o desafio seguindo as instruções](https://github.com/juntossomosmais/frontend-challenge)
3. Esperamos que você envie o desafio em até 10 dias, mas caso precise de mais prazo avisa a gente 😊
4. Mande um e-mail p/ vagas-dev@juntossomosmais.com.br com o título: **[Front-end Developer] Seu nome**
5. Nesse email adicione tudo que considere relevante no seu perfil: Github, LinkedIn, projetos e etc...
6. Não esqueça de enviar o link do repositório com seu teste
7. Boa sorte 🙏
______

Junte-se! 💕

**Comment by marcioc0sta** [comment]
se eu fosse você, aplicaria para esta vaga

**Comment by lucaspmarra** [comment]
Boa noite, há também a oportunidade para Júnior?

**Comment by HelenDias** [comment]
Está sendo a melhor experiência da minha vida ❤️
Recomendo!

**Comment by felipefialho** [comment]
@lucaspmarra Especificamente pra essa vaga estamos buscando alguém com um pouco mais de experiência 😊

**Comment by fogeid** [comment]
Está difícil achar empresa que contrata Junior...

**Comment by felipefialho** [comment]
@fogeid Contratamos bastante pessoas com perfil Júnior [na nossa última leva de contratação](https://github.com/frontendbr/vagas/issues/2902) 😃

**Comment by Rarfael** [comment]
Chance desse remoto se extender para depois da pandemia?
Sou Minas (BH) e gostei muito da vaga!

**Comment by felipefialho** [comment]
@Rarfael A principio não 😢 , pode ser que isso mude no futuro mas estamos deixando avisado que é alocado pra evitar desalinhamentos.

**Comment by felipefialho** [comment]
Vaga preenchida, obrigado a todo mundo que se interessou e se candidatou ❤️
