### ISSUE TITLE
[São Paulo] Front-end Developer na Sow 

### ISSUE THREAD

**Issue by sowrh** [frontendbr/vagas#3411]
> Vaga Remota durante a pandemia

## Nossa empresa

Criada em 2011, a  SOW  nasceu do desejo de levar às organizações, soluções e serviços em TI que ajudem a maximizar o potencial dos negócios. SOW: Transformando conhecimento em resultados 

## Descrição da vaga
Desenvolvimento em PL/SQL Oracle
Requisitos para FrontEnd (Maestro Angular 2+)

## Local

Remoto, e caso o cliente solicite o recurso deverá ir presencialmente até São Paulo (Vila Tramontano)

## Requisitos

**Obrigatórios:**
JavaScript/ES6
AngularJS v1
Angular v2+
Angular CLI
Webpack
NPM Script
TypeScript 3.5
Material Design/Angular Material
AMD/RequireJS
MomentJS
Gulp
Yeoman/Slush
SASS ou SCSS ou LESS
Bootstrap 3/4
HTML 5
CSS 3
Responsive Web Design
Rest
Git
Visual Studio Code

**Desejáveis:**
Clean Code
Solid
DDD
NodeJs

**Diferenciais:**

## Benefícios

**Diferenciais:**

## Contratação

PJ 

## Como se candidatar

Por favor envie um email para thamiris.oliveira@sow.inf.br com seu CV anexado - enviar no assunto: Vaga FrontEnd – Angular SR

## Tempo médio de feedbacks
E-mail para contato em caso de não haver resposta: oportunidades@sow.inf.br

## Labels
Inicio: 10.08.2020
Termino Previsto: 10.10.2020

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
