### ISSUE TITLE
[remoto] Front-end Developer na Sow

### ISSUE THREAD

**Issue by sowrh** [frontendbr/vagas#3413]
> Vaga Remota durante a pandemia

## Nossa empresa
Criada em 2011, a  SOW  nasceu do desejo de levar às organizações, soluções e serviços em TI que ajudem a maximizar o potencial dos negócios. SOW: Transformando conhecimento em resultados.

## Descrição da vaga
Líder técnico especialista no desenvolvimento de aplicações front-end com ênfase na segregação de aplicações para otimização de desenvolvimento, testes, implantação, uso e monitoramento dos módulos.

## Local
Remoto

## Requisitos

**Obrigatórios:**
Angular, Bootstrap, NodeJS
Micro-front-ends (design pattern) , back-end for -front-end (BFF)
Conhecimento Swagger; API Specification
Conhecimentos CMS (Adobe, Drupal, Joomla)

**Desejáveis:**
Material Design for bootstrap 

**Diferenciais:**
Inglês, não obrigatório, mas será um diferencial

## Benefícios
- Plano de saúde
- Seguro de vida
- VR 

**Diferenciais:**

## Contratação
CLT

## Como se candidatar

Por favor envie um email para tania.silva@sow.inf.br com seu CV anexado - enviar no assunto: Vaga Tech Lead  Front-end (modularização)

## Tempo médio de feedbacks
E-mail para contato em caso de não haver resposta: oportunidades@sow.inf.br

#### Alocação
Remoto
Inicio: Imediato
Termino Previsto: 31.12.2020

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
