### ISSUE TITLE
[SÃO PAULO] Front-end Developer | Mercado Financeiro 

### ISSUE THREAD

**Issue by CapassoLevinia** [frontendbr/vagas#3414]
**Pessoa Desenvolvedora Angular Pleno** 
Atividades e Responsabilidades
- Desenvolvimento de arquitetura para os clientes;
- Foco em transformação digita;
- Acompanhamento e contribuição de projetos (definição de requisitos planejamento, testes, etc).
Requisitos Técnicos:
- Javascript
- HTML
- CSS
- API's
- Metodologia ágil

Conhecimento diferencial:
- Experiência com arquiteturas SPA;
- Inglês avançado

O que nós oferecemos
Academia/Gympass
Seguro de Vida
Plano Odontológico
Plano de Saúde
Vale Transporte
Vale Alimentação
Vale Refeição
Previdência Privada

==================================================
> Vaga Remota durante a pandemia
e-mail de resposta: lilactechrh@gmail.com

**Comment by lucaspmarra** [comment]
Boa noite, há alguma oportunidade para Júnior?

**Comment by Cristianojr9** [comment]
Vaga remoto apenas durante a pandemia ou poderá ser estendida?

**Comment by CapassoLevinia** [comment]
> Vaga remotamente apenas durante uma pandemia ou pode ser estendida?

Pode ser estendia.

**Comment by RafaPalau** [comment]
Boa tarde. Também procuro vaga para Junior. Se tiver oportunidade gostaria de fazer um teste. Obrigado.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by CapassoLevinia** [comment]
> Boa tarde. Também procuro vaga para Junior. Se tiver oportunidade, gostaria de fazer um teste. Obrigado.

Ola infelizmente essa oportunidade é para o nível pleno e sênior. 
Obrigada.
