### ISSUE TITLE
[Rio de Janeiro] Front-end Developer Pleno na Original.io

### ISSUE THREAD

**Issue by tamirispussente** [frontendbr/vagas#3416]
Front-End Developer Pleno na Original.io
[Vaga Remota durante a pandemia]

Na Original.io transformamos sonhos e desejos em experiências digitais apaixonantes! E ai está o nosso maior desafio: construir soluções inteligentes com foco nas necessidades dos nossos clientes e, na conversão. Atuamos em diversas divisões de negócio, como B2C, B2B, marketplace, integrações entre outras. 

Por amarmos o que fazemos, queremos você que também tem uma paixão por isso!

## Descrição da vaga

- Engajamento com as metas junto aos clientes;
- Atuação na área de desenvolvimento da empresa junto aos demais membros do time com o foco em front end e implantação das e-commerces em plataforma VTEX e outras;
- Em seu dia a dia atuará com o HTML5, CSS3 e JS5 (ES5 OU ES6) desenvolvimento de funcionalidades e telas, resolução de Bug’s, consumo de API’s e integração entre sistemas via front-end, por isso é necessário o conhecimento intermediário de aplicação dessas tecnologias;
- Será um diferencial ter conhecimento e/ou experiência com a plataforma VTEX, ou apreender a plataforma em menos de 3 meses - desafiador!
- Será um diferencial ter conhecimento em React e certificado Magento 2.0.

## Local

Remoto, Rio de Janeiro - Centro

## Requisitos

**Obrigatórios:**
- experiência comprovada com HTML5, CSS3 e JS5 (ES5 OU ES6) e derivados

**Desejáveis:**
- já ter atuado com implantação em e-commerce

**Diferenciais:**
- já ter atuado com VTEX

## Benefícios

- Plano de saúde (sem desconto) - após 3 meses
- Seguro de odonto (sem desconto) - após 3 meses
- VR/VA de R$ 33/dia (sem desconto)
- Transporte
- Dayoff aniversário

**Diferenciais:**
- horário flexível
- monte a sua máquina como desejar
- ping pong e vídeo game
- time multidisciplinar

## Contratação

CLT ou PJ (a combinar)

## Como se candidatar

Por favor envie um e-mail para cv@original.io com seu CV anexado - enviar no assunto: Desenvolvedor Front end e realize nosso desafio: https://github.com/original-io/join-us

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno

**Comment by PedroAbdalla** [comment]
Vaga em aberto? devo mandar o desafio pronto junto com o email?

**Comment by tamirispussente** [comment]
> Vaga em aberto? devo mandar o desafio pronto junto com o email?

Olá, Pedro, boa tarde!

Sim, basta realizar o desafio e nos encaminhar o link do repositório, bem como seu currículo para os e-mails sinalizados. :)

**Comment by hikild** [comment]
Aceita dev jr?

**Comment by tamirispussente** [comment]
> Aceita dev jr?

Olá, Hithalo!
Podemos sim avaliar seu desafio mesmo sendo júnior, dependendo do nível de conhecimento em determinadas linguagens podemos analisar sim.

**Comment by tamirispussente** [comment]
> Vaga em aberto? devo mandar o desafio pronto junto com o email?

Olá,
Sim, está aberta, basta realizar o desafio e nos informar :)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by tamirispussente** [comment]
> Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

Sim, estamos ainda com esta vaga em aberto.
