### ISSUE TITLE
[Remoto] Lead Front-end Developer @ Intricately

### ISSUE THREAD

**Issue by danisangster** [frontendbr/vagas#3417]
[Apply here](https://jobs.lever.co/intricately/8cf7ed9b-bc35-422e-9e7a-13bd72910bf3)!

### The opportunity
We are looking for a remote Lead Front-End Engineer excited to own front-end product delivery. We have a founding team with deep technical expertise and have seen the tremendous impact first-hand that this role can deliver. You've got the right combination of software wizardry, technical prowess, leadership traits, and (most importantly) is someone we enjoy spending lots of time with. 

As an early hire, you will be a core leader within the engineering organization with a tremendous impact on the product, culture, and the trajectory of the company. You'll be part of a team creating a service that's heavily used (and loved) by some of the largest cloud and infrastructure companies in the world. The majority of our engineers are based in Brazil, and we're excited to strengthen the team there. You'll work closely with the CTO to refine, improve, and ship product, and will lead a frontend team through example, mentorship, and training. If you think there could be a fit, we'd love to talk to you!

### About Intricately
Intricately is the leading provider of data insights on cloud product usage, adoption, and spend. Based, in San Francisco, the platform delivers real-time intelligence to cloud vendors to prospect and prioritize opportunities, start better conversations with customers, deliver more wins, and help customer success teams identify issues before they become problems. Founded in 2014, Intricately is proudly backed by Counterpart Ventures, Bloomberg Beta, Singtel Innov8, and Susa Ventures.

Many companies talk about Big Data- we're actually *living* it. How would you model cloud/infrastructure spend for the Fortune 500? How would you collect this data? How would you track variations in this dataset? What's noise vs signal? What's the most efficient way to query 30mm+ Internet Gateways? How do you create a front-end to surface insights for customers so they can get the information they need and get on with their day? Intricately engineering is focused on solving these challenges every day. Got strong opinions on the topic? We're excited to discuss them with you!

### **Some context on our scale:**
- We see Millions of daily real-time events representing the living, breathing internet
- We track Billions of digital assets
- We store Petabytes of event-state data

### **Our stack:**
- Front-End : VueJS
- Back-End : Ruby / Rails, Node
- Data Stores : Postgres, Mongo, ElasticSearch, DynamoDB, InfluxDB, Redis, Memcache, S3
- Clouds : AWS, DigitalOcean, Heroku

### **In the short term, you'll:**
- Lead a team of software engineers by example, mentoring them to level up the function
- Build product features quickly and efficiently
- Lead code reviews, pairing sessions, and knowledge transfers
- Improve our front-end development tooling and workflow
- Scale yourself by writing clear and concise engineering spec for other engineers to follow
- Create a culture of knowledge sharing and mentorship

### **In the long term, you'll:**
- Partner with technical leadership to manage and grow a team of software engineers
- Be an on-demand resource of knowledge for technical teams
- Ship beautiful and functional product

### You have:
- 7+ years of experience as a front-end software engineer w/extensive knowledge of VueJS.
- Fluency in English. You'll be communicating with team members around the world, and English is our core language.
- Startup experience building products people love
- Strong command of software engineering principles, design, and process
- Excellent written and oral communication skills
- Aptitude for coaching and mentorship
- Ability to work in a fast-paced startup environment and lead a team of globally dispersed developers.

### You get:
- Competitive monthly pay
- Bonuses based on company success
- Open vacation policy
- Yearly team retreats (when the global pandemic has subsided)

[Apply here!](https://jobs.lever.co/intricately/8cf7ed9b-bc35-422e-9e7a-13bd72910bf3)

#### Alocação
- Remoto
#### Experiência
- Sênior
#### Regime
- PJ

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
