### ISSUE TITLE
[Remoto] Front-end Developer na Wiretrack

### ISSUE THREAD

**Issue by lowercase00** [frontendbr/vagas#3418]
## Nossa empresa

Wiretrack é uma ideia que esta prestes a sair do papel com alguns produtos distintos. O projeto está em estágio totalmente inicial, na ideia, e busco alguém que ajude a torna-lo realidade.

## Descrição da vaga

Busco alguém iniciante que já conheça o básico de front (VueJS), e entenda a lógica de interação com o backend. Como é um projeto em desenvolvimento, é esperado que as coisas mudem muito ao longo do desenvolvimento, então muita paciência é fundamental. Essa não é uma vaga de uma grande empresa, com time estabelecido, e diversas equipes de suporte.

É importante flexibilidade: são diversos produtos distintos e o desenvolvimento de cada um deles deve rodar em paralelo.

Espero algo part-time, não haverá controle de horário nem horas, resultado é o que importa, 100% de flexibilidade.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Vontade de aprender
- Ingles
- Total e absoluta autonomia na resolução de problemas
- Proatividade para resolver problemas, trazer soluções e ser criativo
- Flexibilidade para um projeto que vai mudar bastante ao longo do desenvolvimento 
- Conforto ao virar a chave e trabalhar em diferentes projetos ao mesmo tempo
- Códigos bem documentados e boas práticas de programação e organização 

**Desejáveis:**
- Ingles fluente
- Conhecimentos em Vue, Vuex, VueRouter
- Conhecimentos de UI e frameworks
- conhecimentos em Python (é o backend)

**Diferenciais:**
- Noções de UX
- Sketch/Adobe XD

## Benefícios

.

**Diferenciais:**
- 100% remoto
- 100% flexível

## Contratação

A combinar. CLT não é uma opção.

## Como se candidatar

Por favor envie um email para contato@wiretrack.io com seu CV anexado - enviar no assunto: Vaga VueJS

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: contato@wiretrack.io

#### Alocação
- Remoto

#### Regime
- Estágio
- Freela
- PJ

#### Nível
- Júnior

**Comment by oiagorodrigues** [comment]
@lowercase00 Fiquei interessado. Enviei um e-mail para vocês. Vamos conversar?

**Comment by frvs** [comment]
Enviei o meu currículo. :)

**Comment by lowercase00** [comment]
Em processo de avaliação.
