### ISSUE TITLE
[São Paulo - SP] - Senior Front End Engineer

### ISSUE THREAD

**Issue by mtmr0x** [frontendbr/vagas#342]
## Descrição da vaga

We're looking for a Senior Front End Engineer to help us keep on delivering an amazing experience for our customers. In 2016 we were awarded as a top 10 app in Brazil and for this year we're aiming on improving the platforms even more. The right candidate for this position will be a key player in helping us scale our Web efforts while also delivering an amazing user experience for wine lovers in Brazil.

Please apply if: you share a passion for technology and software development, with a keen eye for clean, concise and healthy code; you have strong problem solving skills combined with a well structured thought process; you have significant experience developing front end applications and value user experience as a first class deliverable; you embrace change and innovation, with a hunger for learning and trying new technologies.

## Local

Consolação, close to Avenida Paulista

## Benefícios

- VR
- VT
- Life insurance
- Health and dental health care plans
- Wine Friday's (Every Friday a wine tasting with our sommeliers to understand more about wine and wine culture)

## Requisitos

**Responsabilidades**

Architect, code and maintain our Front End Application (NodeJS + React + Redux)

Deliver high level and well tested code to every Pull Request you create

Work with the Product team towards understanding requirements and implementing amazing features

Integrate with third party analytical tools (Mix Panel, Hotjar, google analytics) for proper instrumentation

**Obrigatórios:**

Solid understanding of at least three of the following Javascript technologies such as NodeJS, React, Redux, Angular, Ember, Backbone, etc

Solid understanding of CSS best practices with tools like Stylus, SASS, SCSS, PostCSS, etc

Solid understanding of unit tests, TDD and best practices for testing code and behaviors

Knowledge about Functional Programming paradigm and its features such as immutability, lazy loading, curried and currying functions, recursion, closures, etc

Awesome versioning control systems knowledge such as GIT

Significant experience using Web Services (REST, SOAP)

Well acquainted with modern development best practices, such as Design Patterns

Familiar with at least one Agile framework (Scrum, Kanban, XP)

**Desejáveis:**

Knowledge about concurrent / parallel mechanisms such as reactive architectures, multithreading, asynchronous programming

Previous experience with retail / e-commerce

## Contratação

CLT

## Nossa empresa

In less than 4 years of existence ( evino ) has become one of the biggest Brazilian e-commerces and fastest growing wine platform. We're now counting with 200+ people, an outstanding revenue growth and break-even, all of that while also enjoying pretty cool wine labels. Besides wine, the preparation for a new business scale and managing people / growth are the foundations of our success.

## Como se candidatar

Send e-mail to: leticia.santinelli@evino.com.br; with "Front End Engineer Position" in subject and your LinkedIn profile link in the e-mail body.

Cheers.

**Comment by alanrsoares** [comment]
hmu, bro

**Comment by X-X-Xavito** [comment]
What's up?

**Comment by mtmr0x** [comment]
A vaga continua aberta :)

**Comment by LFeh** [comment]
Aberto ainda @mtmr0x ?
