### ISSUE TITLE
[Remoto] React Native Developer Senior na Platform Builders

### ISSUE THREAD

**Issue by lucianohleao** [frontendbr/vagas#3420]
## Nossa empresa

Ao ingressar na Builders, você fará parte de um movimento que idealiza, co-cria e conecta pessoas. Desfrutando de um ambiente colaborativo que propicia oportunidade de crescimento exponencial. Se você está em busca de autonomia, liberdade e curte desafios, aqui é o seu lugar. #SejaBuilder

## Descrição da vaga

Você terá o desafio de transformar ideias em produtos, tirar do âmbito de ideação para co-criação. Conseguir se adaptar ao ecossistema, resolvendo problemas de crescimento exponencial.

## Local

Remoto

## Requisitos

**Tecnologias que vão gerar valor nos projetos:**
- React Native (+Redux/Mobx)
- Flutter
- Fluência em JavaScript (ES7)
- APIs REST
- Conhecimento geral do ambiente móvel
- Versionamento de código com Git
- Conhecimento em arquitetura de software
- Metodologias ágeis

**O que te aproxima de ser um (a) Builder:**
- Conhecimento em CI/CD (App Center, Fastlane, Testflight, etc)
- Conhecimento em Firebase (Analytics, Crashlytics, etc)
- Experiência em linguagens nativas e construção de bridges

**Informações Adicionais:**
- Oportunidades reais de empreender e impactar
- Fazer parte de uma comunidade de empreendedores de ponta, o Movimento
- Inovação e criação liberados
- Participar de um processo único de geração de valor
- Contribuir na criação de métodos disruptivos
- Colocar suas ideias no mercado, na prática! :)
- Possibilidade de Profit share em novos Negócios
- Prestador de Serviços (PJ)
- Flexibilidade de horário

## Contratação

PJ a combinar

## Como se candidatar

Por favor me envie um email demonstrando interesse para luciano.leao@platformbuilders.io com seu CV anexado - enviar no assunto: Vaga React Native

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 48h após término de cada etapa.
E-mail para contato em caso de não haver resposta: luciano.leao@platformbuilders.io

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
