### ISSUE TITLE
[Remoto] Desenvolvedor Full Stack JavaScript - FitDance

### ISSUE THREAD

**Issue by ednilsonamaral** [frontendbr/vagas#3422]
## Nossa empresa
Uma empresa que torna sua vida mais feliz por meio da dança. O programa de aulas de dança que mais cresce no mundo. A FitDance se tornou um estilo de vida.

## Descrição da vaga
- Buscamos Desenvolvedores Full Stack Javascript para compor nosso time de Tech.

## Local
- Remoto durante pandemia
- Após, Escritório em São Paulo

## Requisitos
**Obrigatórios:**
- Mínimo de 2 anos de experiência em posição similar
- API Rest
- Node.js
- Typescript
- SQL
- Git flow
- Experiência em desenvolvimento front-end usando React.js
- Conhecimentos em React Native

**Diferenciais:**
- Metodologias Ágeis
- PostgreSQL
- AWS
- Docker
- Kafka
- NoSQL
- Experiência e visão para projetos em que o modelo de negócio está no formato de marketplace

## Contratação
PJ à combinar

## Como se candidatar
- Enviar CV com link para o GitHub e pretensão salarial para o e-mail technology@fitdance.com. Enviar no assunto: Vaga Full Stack Javascript

#### Alocação
- Remoto durante pandemia
- Após, Escritório em São Paulo

#### Regime
- PJ

#### Nível
- Pleno

**Comment by rfoel** [comment]
@felipefialho remoto durante pandemia

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
