### ISSUE TITLE
[Remoto] Front-end React Developer Júnior Part-Time na Alfred

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#3423]
## Nossa empresa

Alfred faz a intermediação de mão-de-obra entre negócios e profissionais da área de hospitalidade através da sua plataforma (aplicativo+site). 

Nossa missão é ajudar a viabilizar as operações dos negócios e promover inclusão social através de novas oportunidades e renda extra. A solução staffing-as-a-service, oferece flexibilidade, independência e conveniência para os players deste ecosistema. vamos mudar a maneira que as pessoas trabalham!

## Descrição da vaga

Alfred faz a intermediação de mão-de-obra entre negócios e profissionais da área de hospitalidade através da sua plataforma (aplicativo+site). 

A solução staffing-as-a-service, oferece flexibilidade, independência e conveniência para os players deste ecossistema. Vamos mudar a maneira que as pessoas trabalham!

Estamos buscando uma pessoa desenvolvedora fullstack javascript júnior para trabalho part-time.

## Local

Remoto

## Requisitos

- Conhecimentos em desenvolvimento de projetos front-end usando React
- Confortável para trabalhar com HTML5, CSS3 e Flexbox
- Confortável com comandos GIT e Linux
- Conhecimentos em Node.js
- Ser habituado com metodologias ágeis
- Escreva código estável e eficiente
- Habituado com banco de dados relacional

**Diferenciais:**

- Conhecimentos ou estudando nos últimos meses sobre desenvolvimento mobile usando React Native
- Conhecimentos em desenvolvimento de REST APIs usando Node com Typescript

## Contratação

PJ

## Como se candidatar

Candidatar-se em: [https://bit.ly/2PLLlZM](https://bit.ly/2PLLlZM)

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior

**Comment by Cristianojr9** [comment]
CV Enviado!

**Comment by gabrielhws** [comment]
Em revisão de perfis e CVs enviados.
