### ISSUE TITLE
[Remoto] React Native Developer na Restfy

### ISSUE THREAD

**Issue by joaofidelix** [frontendbr/vagas#3424]
## Nossa empresa

Desenvolver software é nossa paixão.
Construímos aplicações para brilhar os olhos de nossos clientes. Nosso foco é em segurança digital e rastreabilidade de processos.

## Descrição da vaga

Desenvolvimento de um app para controle e rastreabilidade de produtos.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com React Native
- Material UI / Ant Design / BootStrap
- Publicações em Lojas
- Consumo de API Rest

**Desejáveis:**
- AWS
- Figma
- Conhecimento em leitura de QRCode
- Conhecimento em GeoPosicionamento

**Diferenciais:**

- projetos opensource

## Benefícios

- Via Cooperativa

## Contratação

Cooperado.
Junior
Pleno

## Como se candidatar

Candidatura Enviar CV por e-mail: vaga.mobile@restfy.com.br

#### Alocação
- Remoto

#### Regime
- Cooperado
- Freela

#### Nível
- Júnior
- Pleno

**Comment by brunocrpontes** [comment]
Essa vaga ainda tá disponível? Enviei meu CV a uns dias, mas sem feedback até o momento.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
