### ISSUE TITLE
[São Paulo] Front-end Developer React SR na Sciensa Digital

### ISSUE THREAD

**Issue by RitaBrandt** [frontendbr/vagas#3425]
==================================================
Front-End Developer React SR 

São Paulo - Front-End Developer React na Sciensa Digital

Vaga Remota durante a pandemia

Nós da Sciensa somos pessoas entusiastas e apaixonadas pela Transformação Digital, e trabalhamos para tornar empresas analógicas em Digitais por meio de tecnologia e estratégia, para assim, proporcionar às empresas brasileiras crescimento de forma exponencial e constante!

Temos uma Cultura que prega a diversidade, inclusão e colaboração, com um ambiente em que todos se sintam confortáveis e tenham liberdade para ser quem são. Acreditamos que a tecnologia é um meio fundamental para tornar o mundo um lugar melhor, e estamos em constante busca por talentos que possam nos ajudar a realizar esse objetivo.

Você é um desses talentos? Gostaríamos muito de ter Você trabalhando com a gente! Inscreva-se.

Projeto interno na Sciensa (longo prazo)

São Paulo / SP / Rua Cerqueira Cesar

Requisitos:

Obrigatórios:

React Native
React
App Center (Pipeline)
Git
React
Yarn
NodeJs
Typescript
Style Components

Desejáveis:
Reactotron
Sentry
Acessibilidade
Google Analytics
Publicação Lojas(Google Play/App Store)

Escritório e equipamentos de qualidade
Flexibilidade de horário
Home Office (ate setembro 100%)

**Diferenciais:**
Treinamentos constantes. 
Palestras e Eventos
Massagem
Cozinha
Lounge & Vídeo Game

Contratação
Contratação PJ (Valor hora + Ajuda de Custo)

Como se candidatar

Por favor envie um email para rita.brandt@sciensa.com com seu CV anexado - enviar no assunto: Vaga React SR

Tempo médio de feedbacks (2 dias)

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: rita.brandt@sciensa.com

Remoto/ Presencial 

Regime
PJ + Ajuda de Custo

Nível
Sênior
Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by gianpedrol** [comment]
Tenho interesse

Em Ter, 13 de out de 2020 21:16, Felipe Fialho <notifications@github.com>
escreveu:
