### ISSUE TITLE
[REMOTO] Front-end Developer na Invillia

### ISSUE THREAD

**Issue by GabriellyLeonel** [frontendbr/vagas#3426]
## Nossa empresa
A experiência de trabalhar na Invillia é única. E global. Temos o nosso próprio jeito de conectar talentos e construir inovações.

Revolucionamos o ambiente de trabalho #Instation + somos experts em desenvolver soluções complexas para #GameChangers + temos uma metodologia única #EngagedbyDataPeopleAction + investimos em pessoas #InvilliaAcademy

Alguns diferenciais Invillia:
_inovamos lado-a-lado com #GameChangersGlobais
_cultura de trabalho distribuído #inStation
_metodologia exclusiva #GlobalGrowthFramework
_benefícios únicos entre as techs #InfinitePowers

Faça uma imersão aqui https://invillia.com/

## Local

100% remoto fulltime 

## Requisitos
React e Hooks;
Gerenciamento de Estados (Redux);
HTML5, CSS3 (Sass), Javascript, JSS, WebSockets e Bootstrap/Material Design;
Git, Docker, Gulp, Webpack, Gerenciamento de Pacotes (ex: NPM, Yarn) e TDD;
Soluções e definições de arquitetura (Flux Architecture, SAGA Pattern);
Conhecimento teórico e prático em microserviços e APIs;
JWT, RestFull, Rest Hateoas, oAuth2.0;
Padrões de Projetos (DDD, Solid, Design Patterns);
Integração e entrega contínua (CI/CD);
Banco de Dados Relacional e Não-Relacional;
Desenvolvimento Ágil - Scrum e Kanban. 

## Benefícios
1.000 em benefícios - VA, VR, AM, AO, SV. 

## Contratação

CLT

## Como se candidatar

Por favor se cadastre neste link: https://invillia.gupy.io/jobs/260634?jobBoardSource=gupy_public_page 
Não esqueça de colocar seu telefone, e-mail e pretensão CLT.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by GabriellyLeonel** [comment]
@felipefialho a vaga é 100% remoto durante todo o contrato e não só durante a pandemia. Pode editar a label, por favo?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by GabriellyLeonel** [comment]
Temos mais 4 vagas!! :D

**Comment by SaMatheus** [comment]
@GabriellyLeonel Alguma para estágio ou Jr? =D
