### ISSUE TITLE
[Porto Alegre] Fullstack Developer (Angular + Java) na DBServer

### ISSUE THREAD

**Issue by AlineSchorn** [frontendbr/vagas#3428]
> Vaga Remota durante a pandemia

## Nossa empresa

A DBServer

Somos uma softwarehouse que constrói entregas sob medida. Há 27 anos trabalhamos com foco nas pessoas, guiados por nossos valores, crescendo lado a lado com nossos colaboradores. Nosso lema é fazer a coisa certa do jeito certo através do design e do build.

Nos últimos anos, iniciamos uma caminhada em direção a diversidade e a inclusão e após o lançamento do nosso Marco Ético temos agora um norteador dos princípios que irão trilhar a nossa trajetória.

Estamos orgulhosos de promover um ambiente de trabalho livre de discriminação. Acreditamos que a diversidade de experiências, perspectivas e histórico transforma nosso ambiente de trabalho. Estamos empenhados a construir esse legado com a sua parceria! 

Conheça nosso Marco ético: http://www.dbserver.com.br/marcoetico/

## Descrição da vaga

O que vamos construir juntos?

Nessa posição, você trabalhará conosco em uma grande conta do segmento financeiro. Nosso cliente trabalha fortemente com agilidade e foco na qualidade das entregas. Buscamos pessoas que gostem de atuar com autonomia, trabalhar em time, compartilhar conhecimentos e atuar com qualidade.

Nos ajude a desenhar a solução!

Se você chegou até aqui e é uma Pessoa Desenvolvedora Fullstack, que se identifica tanto com o backend quando com o frontend, você está muito perto de fazer parte do nosso time!

## Local

Porto Alegre, RS - Zona Norte

## Requisitos
Experiência em desenvolvimento Java no backend;
Experiência com desenvolvimento Angular 2+ no frontend;
Conhecimento em javascript e typescript.

**Desejáveis:**
Experiência em Python.

## Benefícios

- Plano de saúde
- Plano Odontológico
- Seguro de vida
- VR 
- VT

**Diferenciais:**
Horários flexíveis

## Contratação

CLT

## Como se candidatar

Você pode se candidatar através do link: https://jobs.kenoby.com/dbserver/job/dev-fullstack-angular-java/5ec53a024844530bbba0ea4e

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: poa_selecao@dbserver.com.br

#### Alocação
- Alocado
#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
