### ISSUE TITLE
[São Paulo/Remoto] Front-End Developer [B8ONE/PLUGONE]

### ISSUE THREAD

**Issue by hugoalvarenga** [frontendbr/vagas#3429]
> Vaga Remota durante a pandemia

## Nossa empresa

Somos um laboratório de soluções digitais inovadoras, apaixonada por tecnologia e focada em resultado. Aqui temos profissionais dos mais diferentes perfis em um ambiente descontraído e extremamente produtivo.

## Descrição da vaga

Como desenvolvedor Front-End, você terá como atribuição o desenvolvimento de interfaces e integrações para o produto PlugOne ou trabalhar em projetos nacionais e internacionais na B8One. A abordagem de novas tecnologias e proposta de utilização de padrões são sempre bem vindas em nosso time.

## Local

Remoto ou Escritório, São Paulo - Vila Olímpia

## Requisitos

**Obrigatórios:**

- 2+ anos de experiencia como desenvolvedor Front-End (utilizando ReactJS ou ECMAScript);
- Fluente com a tecnologia ReactJS;
- Experiência em GraphQL de preferência com Apollo Client;
- Experiência em Typescript;
- Conhecimento em padrões de projeto e melhores práticas em desenvolvimento de softwares;
- Inglês intermediário/Avançado;
- Styled Components

**Desejáveis:**

- Conhecimento em processos de e-commerce;
- Conhecimento em NodeJS;
- 1+ de experiencia em micro-frontends;

**Diferenciais:**

- Conhecer plataformas de e-commerce, como: Magento, VTEX, Shopify;

## Benefícios

- Horário Flexível
- Macbook Pro, deixe sua máquina como desejar. =))
- Happy Hour às sextas (em época de não corona)
- Ambiente descontraído
- No dress code

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para jobs@b8one.com com seu CV anexado e Github - enviar no assunto: [VAGA] Front-End Developer - Front-End Brasil

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: jobs@b8one.com

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by krivax** [comment]
Não entendo coloca o titulo Pleno/Sênior mas nas tags tem estágio e Júnior. Qual dos 2 está correto?

**Comment by MatSa20** [comment]
Não entendi também, mas mandei meu CV pra estágio 😄

**Comment by luizeboli** [comment]
No local consta remoto ou escritório, mas a vaga está com label de durante a pandemia.

É remoto apenas durante, ou também será após?

**Comment by hugoalvarenga** [comment]
> @hugoalvarenga No local consta remoto ou escritório, mas a vaga está com label de durante a pandemia.
> 
> É remoto apenas durante, ou também será após?

Para o pessoal que quer ficar alocado, estamos remoto durante a pandemia. =)

**Comment by luizeboli** [comment]
> > @hugoalvarenga No local consta remoto ou escritório, mas a vaga está com label de durante a pandemia.
> > É remoto apenas durante, ou também será após?
> 
> Para o pessoal que quer ficar alocado, estamos remoto durante a pandemia. =)

Entendo, então pretendem retornar. 

Obrigado e uma boa noite 🙌

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by gianpedrol** [comment]
Tenho interesse

Em Ter, 13 de out de 2020 21:16, Felipe Fialho <notifications@github.com>
escreveu:
