### ISSUE TITLE
[Joinville/SC] Front-End UI | SoftExpert

### ISSUE THREAD

**Issue by thvieira86** [frontendbr/vagas#343]
## Descrição da vaga

Estamos à procura de um guardião dos padrões visuais, um especialista em frontend e apaixonado por design, que consiga trazer o efeito “wow” para os nossos produtos e ainda trabalhar com componentes visuais  (html, css, js, etc) que sejam produtivos para o time de backend, tudo isso em conjunto com o apoio do time de designers. 

**Responsabilidades**

- Entender demandas de UX e DEVs para solucionar problemas de usuários por meio de pixel-perfect interfaces.
- Definir a estratégia e padrões visuais de interface dos nossos produtos. aka Design System 

## Local

Escritório, Joinville / SC

## Requisitos

**Obrigatórios:**
- Repertório visual com foco em user interface
- Domínio das tecnologias HTML5, CSS3, JavaScript e afins.
- Experiência de 3 anos na área
- Portfólio/git  que comprove suas habilidades
- Experiência no uso das ferramentas: Illustrator, Photoshop, XD
- Conhecimentos dos conceitos de responsividade
- Experiência desenvolvendo para mobile
- Detalhista com as entregas visuais

**Desejáveis/diferenciais:**

- Experiência em ambientes de desenvolvimento ágil;
- Experiência com guias de estilo para sistemas;
- Ser um participante ativo na comunidade de UX/UI/Frontend;
- Conhecimentos em testes com usuário e testes a/b 
- Conhecimentos em react.

## Contratação

CLT

## Benefícios

- Vale refeição ou alimentação ;
- Vale transporte;
- Bolsa de Estudos;
- Bônus por atingimento de resultados;
- Plano de saúde;
- Reembolso de medicamentos;
- Convênio Farmácia / Livraria;
- Convênio Odontológico;
- Convênio Estacionamento

## Como se candidatar

https://softexpert.recruiterbox.com/jobs/9d6f853c572e43df903e3f1b09ac9100

**Comment by jotavejv** [comment]
Enviado!
