### ISSUE TITLE
[São Paulo] Front-end Developer na Pricefy

### ISSUE THREAD

**Issue by leandrosilva** [frontendbr/vagas#3431]
## Nossa empresa

A Pricefy é uma das maiores retailtechs (startups de varejo) do país. Atendemos mais de 4.000 lojas de diversos segmentos com uma inovadora solução de comunicação inteligente de preços. Dentre os principais clientes, destacam-se: GPA, Carrefour, Leroy Merlin e Via Varejo. Somos membros do Cubo Itaú, TOP10 Marketing do ranking 100 Open Startups, Apoiadores do RetailTechClub.com e RetailLab ESPM, destaques do RetailTech Mining Report e Inovativa Brasil, e membros do portfólio da ACE, considerada a melhor aceleradora de startups da América Latina.

## Descrição da vaga

Estamos em busca de um desenvolvedor de software “pleno” para integrar uma de nossas squads, que trabalha em uma linha de produtos web e mobile com ampla base de usuários.

Procuramos por alguém que queria estar **focado no client-side das aplicações**, mas que se sinta confortável em se aventurar no **server-side quando necessário**; e tenha certeza que será.

## Local

Remoto ou Escritório, SP, São Paulo, Pinheiros.

## Requisitos

**Obrigatórios:**
- 5 anos de experiêcia em desenvolvimento web
- Git
- HTML e CSS
- JavaScript / TypeScript
- Angular 2+ ou React JS
- Material Design ou Bootstrap

**Desejáveis:**
- Uso de serviços em cloud (AWS / GCP / Azure)
- REST API em Node.js
- AWS Lambda com Node.js
- C# / .NET Core
- Docker
- Redis, Elasticsearch, Postgres e SQL Server

**Diferenciais:**
- Golang
- Android, iOS, PWA
- AWS Amplify, Google Firebase

## Benefícios

- Local de trabalho e horário flexível
- 2 semanas de descanso remunerado
- Investimentos em treinamentos e eventos

## Contratação

PJ a combinar.

## Como se candidatar

Por favor envie um email para leandro.silva@pricefy.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Developer.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: leandro.silva@pricefy.com.br.

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by tech3br** [comment]
Apenas para avisar que o email de contato está errado.

Está faltando o *c* no *pricefy*.

Att

Em sex., 14 de ago. de 2020 às 13:14, Leandro Silva <
notifications@github.com> escreveu:

**Comment by leandrosilva** [comment]
Valeu!!!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
