### ISSUE TITLE
[Curitiba] Front-end Estágio na [Ecompleto]

### ISSUE THREAD

**Issue by hoffmannico** [frontendbr/vagas#3433]
## Nossa empresa

A E-completo, empresa sediada em Curitiba-PR, é especializada em soluções para comércio eletrônico, atende hoje, clientes nas áreas de: Comércio Eletrônico (E-commerce), Venda de Imóveis e Compra/Venda de Veículos.

Adoramos tecnologia, comércio eletrônico e somos apaixonados pelo que fazemos.

Pensamento grande, lembrando sempre do foco nos pequenos detalhes.

## Local

Escritório, [Paraná], [Curitiba], [Bacacheri]

## Requisitos

**Obrigatórios:**
• Escrever código limpo, conciso;
• Compreensão da Semântica HTML 5;
• Noções em CSS e SASS;
• Conhecimento em jQuery / Javascript (básico/intermediário);
• Compreender as capacidades do navegador;
• Experiência na tradução de wireframes de web design em páginas da web reais.

**Atividades:**
• Layout para sites, E-mail, Newsletter
• Criação de banners;
• Criação visual de materiais internos, comunicação interna, library de conteúdo, mídia kit, etc);
• Converter o design da peça UX/UI em realidade
• Desenvolver com HTML, CSS e JavaScript
• Manutenção e optimização de websites e interfaces de utilizador
• Criar ferramentas e elementos que melhorem a interacção com o site em qualquer dispositivo ou navegador
• Melhorar a velocidade de carregamento da web

**Desejáveis:**
Php / Sass / GIT / Javascript / XD

## Como se candidatar

Por favor envie um email para infra@ecompleto.com.br com seu CV anexado - enviar no assunto: Vaga Estágio FrontEnd

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 20 dias após cada processo.

## Labels

- Curitiba
- Alocado

#### Alocação
- Alocado

#### Regime
- Estágio

**Comment by Douglasdevxoxo** [comment]
Tenho interesse.
