### ISSUE TITLE
[São Paulo] Front-end Developer na BR Mendes

### ISSUE THREAD

**Issue by mendesbruna** [frontendbr/vagas#3434]
> Vaga Remota durante a pandemia

## BR Mendes
Empresa especializada em Gente!

## Descrição da vaga

- Formação superior completa em engenharia, ciências da computação ou áreas relacionadas;
- Full stack (foco maior em front-end):  Com amplos conhecimentos em Angular, VueJS, CSS.
- Será considerado diferencial conhecimentos em back-end c#,python, banco de dados Sql server, postrgreSql. 
- Conhecimento em design patterns e orientação objeto.
- Experiência em cloud (preferencialmente AWS)

## Local

Escritório [FARIA LIMA] [SP]

## Benefícios

- VR
- VT
- Plano de Saúde (Bradesco Saúde)

## Contratação

CLT

## Como se candidatar

Por favor envie um email para bruna@brmendesconsultoria.com.br com seu CV anexado - enviar no assunto: Front-end .Net

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: bruna@brmendesconsultoria.com.br

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
