### ISSUE TITLE
[SP] Fullstack Developer na Finanzero

### ISSUE THREAD

**Issue by ITSimara** [frontendbr/vagas#3437]
==================================================
-->
> Vaga Remota durante a pandemia

## Nossa empresa

Exemplo: Somos um correspondente bancário online. A partir do seu perfil, negociamos empréstimos com instituições financeiras parceiras e enviamos propostas pré-aprovadas para você — tudo isso gratuitamente.
Nossa Missão
Facilitar sua busca por empréstimo pessoal reunindo, no mesmo lugar, as melhores opções de acordo com o seu perfil. Garantir sua liberdade de escolha

## Descrição da vaga

Exemplo: Se você é um(a) #DevFullstack que almeja ir longe e utilizar suas habilidades pra tal, quero te conhecer! Olha só essa vaga :)

Mínimo de 4 anos de experiência como programador(a) profissional Mínimo 2 anos de projetos utilizando:
#MongoDB, #C#, #Java ou #C++ (mínimo 2 anos)
#NodeJS (mínimo 1 ano) #Linux (Sênior)
Programação de front-end (HTML, CSS)

Diferencial? Sim, nossos olhos brilham por você que ainda manjar de Linguagens #Go (diferencial) Front-end com #ReactJS (diferencial)

## Local

Exemplo: Remoto na pandemia e pós Escritório, [SP], [SP], [Avenida Paulista]

## Requisitos

**Obrigatórios:**
- 4 anos de experiência como programador(a) profissional 
- MongoDB, C#, Java ou C++ (mínimo 2 anos)
-#NodeJS (mínimo 1 ano)

**Diferenciais:**
- Linguagens #Go (diferencial) Front-end com ReactJS (diferencial)

## Benefícios

Plano de saúde
VR
Aulas de inglês
Se preferir ir de carro ou moto? A empresa oferece subsídio para o estacionamento no prédio.
Ambiente de trabalho? Saudável, com excelente localização, em frente ao metrô Trianon (ou em casa, isso mesmo #homeoffice enquanto durar a quarentena).
Resumindo, ambiente descontraído de uma startup com a pegada de uma multinacional.

## Contratação

CLT

## Como se candidatar

Por favor candidate-se pelo link:  https://forms.gle/NYNY3J8z5NCUDA7SA

#### Alocação
- Alocado 
- Remoto na pandemia

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by mrangel-jr** [comment]
Há a possibilidade de ser 100% remoto ?

**Comment by ITSimara** [comment]
Olá Marcos,

Nesse momento as empresas estudam sim, tal provisionamento porque sai mais
acessível pra elas o home office.
Porém, ainda é remoto na pandemia, pós pandemia escritório!
Pode mudar, mas por enquanto nada certo!

Se você tem o perfil, candidata e venha conhecer o desafio caso seja
aprovado no processo seletivo!!!!

Segue o link https://forms.gle/NYNY3J8z5NCUDA7SA para darmos início ao
processo seletivo. Peço que assim que terminar de preencher, me avise, para
que hoje mesmo eu olhe a triagem e encaminhe para a especialista da vaga
ok? Qualquer dúvida, estou por aqui.

Em sáb., 15 de ago. de 2020 às 04:38, Marcos Rangel Junior <
notifications@github.com> escreveu:

**Comment by ITSimara** [comment]
VAGA FECHADA
