### ISSUE TITLE
[Remoto] Front-end Developer na Kyte

### ISSUE THREAD

**Issue by rafaelmotta** [frontendbr/vagas#3439]
## Nossa empresa

At Kyte we love what we do and believe our diverse team of ridiculously ambitious people is what makes our company great. Together, our motley crew of mobility enthusiasts has an assortment of wide-ranging backgrounds from Stanford, Berkeley, MIT, TUM, Uber, BMW, McKinsey, and others. We’re proud of what we are accomplishing by creating the world’s first vehicle-as-a-service platform and believe we are fundamentally changing transportation and urban planning. See you on the road!

## Descrição da vaga

You'll be working in our internal tools:

- Our fleet tool, where we manage our vehicles
- Our twilio flex tool, where we run our CRM

Both written in React.js

## Local

Wherever you are, but you have to work at least 50% of the time during business hours of Pacific or Berlin times.

## Requisitos

**Obrigatórios:**
- At least 5 years working with Javascript
- At least 2 years working with React and its ecosystem 
- Good notions of UX 
- Diligent
- Fluent in English
- Flexibility of having meetings sometimes in the evenings, as the company has its operation on Pacific Time / Berlin Time

**Desejáveis:**
- Next.JS
- Redux Saga
- AWS 

**Diferenciais:**
- React Native
- TDD

## Contratação

Freela por hora. R$50,00 a R$100,00 / hora dependendo da experiencia

## Como se candidatar

Por favor envie um email para rafael@drivekyte.com com seu CV anexado em ingles com o titulo "Front-end Developer na Kyte"

## Tempo médio de feedbacks

Up to 3 weeks. But I won’t reply candidates not respecting the minimum requirements for this position.

#### Alocação
- Remoto

#### Regime
- Freela

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by pedroch4610** [comment]
Olá, @rafaelmotta. Tudo bem? Tenho inglês bom para leitura e escrita apenas, poderia me candidatar a vaga? Obrigado!

**Comment by rafaelmotta** [comment]
Infelizmente não @pedroch4610. Será necessário fazer algumas reuniões em inglês, já que o time é basicamente americano e alemão.
