### ISSUE TITLE
[São Paulo] Front-end Developer no Sicoob Cecres

### ISSUE THREAD

**Issue by andrelbsouza** [frontendbr/vagas#3440]
> Vaga Remota durante a pandemia

## Nossa empresa

Sicoob Cecres é um banco do sistema Sicoob

## Descrição da vaga

Desenvolvimento de aplicação internas com react e react native.

## Local

Exemplo: Escritório, [SP], [São Paulo], [República], Remoto durante a pandemia

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com React e React Native
- 2 anos de experiência com Typescript

**Desejáveis:**
- conhecimentos em Node, Express ou adonis

**Diferenciais:**
- conhecimentos em UX
- Conhecimento do sistema do Sistema Sicoob ou do segmento financeiro

## Benefícios

- Plano de saúde
- Seguro de vida
- VR e VA
- Auxílio creche
- Participação de Resultados

## Contratação

CLT

## Como se candidatar

Por favor envie um email para cassia.rosana@sicoobcecres.com.br com seu CV anexado - enviar no assunto: Vaga Analista de Desenvolvimento

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.
E-mail para contato em caso de não haver resposta: cassia.rosana@sicoobcecres.com.br

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
