### ISSUE TITLE
[Cidade] Fulltack Developer - React + Node na DBServer

### ISSUE THREAD

**Issue by AlineSchorn** [frontendbr/vagas#3441]
> Vaga Remota durante a pandemia

## Nossa empresa

A DBServer

Somos uma softwarehouse que constrói entregas sob medida. Há 27 anos trabalhamos com foco nas pessoas, guiados por nossos valores, crescendo lado a lado com nossos colaboradores. Nosso lema é fazer a coisa certa do jeito certo através do design e do build.

Nos últimos anos, iniciamos uma caminhada em direção a diversidade e a inclusão e após o lançamento do nosso Marco Ético temos agora um norteador dos princípios que irão trilhar a nossa trajetória.

Estamos orgulhosos de promover um ambiente de trabalho livre de discriminação. Acreditamos que a diversidade de experiências, perspectivas e histórico transforma nosso ambiente de trabalho. Estamos empenhados a construir esse legado com a sua parceria! 

Conheça nosso Marco ético: http://www.dbserver.com.br/marcoetico/

## Descrição da vaga

O que vamos construir juntos?

Atuaremos em um projeto do segmento financeiro, que tem como um forte pilar a agilidade e a colaboração. 

Nos ajude a desenhar a solução!

Se você gosta de atuar tanto no backend quanto no frontend, adora desafios e quer atuar em um time que respira ágil, essa pode ser a vaga para você!

## Local

Porto Alegre, RS 

## Requisitos
Experiência em Node.JS;
Conhecimento em Reactive;
Conhecimento em DevOps.

**Desejáveis:**
Front - React;
Métodos ágeis.

## Benefícios

- Plano de saúde
- Plano Odontológico
- Seguro de vida
- VR 
- VT

**Diferenciais:**
Horários flexíveis

## Contratação

CLT

## Como se candidatar

Você pode se candidatar através do link: https://jobs.kenoby.com/dbserver/job/dev-fullstack-react-nodejs/5efb4c538844bb096039152b

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: poa_selecao@dbserver.com.br

#### Alocação
- Alocado
#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
