### ISSUE TITLE
[JAGUARIÚNA] Freelance Front-end Developer na Agência SALA

### ISSUE THREAD

**Issue by cfcarreira84** [frontendbr/vagas#3442]
## Agência SALA

Agência de propaganda no interior de São Paulo.

## Descrição da vaga

Buscamos por desenvolvedor com experiência em VUE.js, Tailaind e Nuxt para auxiliar na produção de algumas telas prototipadas em XD para projeto em fase final.

## Local

Remoto.

## Requisitos

**Obrigatórios:**
Domínio e experiência em Vue.js, Tailwind e XD. 

## Benefícios

- potencial de ser efetivado no projeto para manutenção quando o site estiver em produção.

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para carlos.carreira@agenciasala.com.br com seu CV anexado - enviar no assunto: Freela Vue+Tailwind

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 horas após o contato.

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
