### ISSUE TITLE
[Goiânia] Front-end Dev na Blue Tecnologia

### ISSUE THREAD

**Issue by Blue-tecnologia** [frontendbr/vagas#3443]
## Nossa empresa

Somos uma nova fábrica de software que atua no segmento financeiro/imobiliário. 

## Descrição da vaga

Dev front para o núcleo de inovação da fábrica de software. 

## Local
Goiânia, Jardim Goiás.

## Requisitos

**Obrigatórios:**
- XP em dev web, javascript, CSS, HTML, Bootstrap etc.
- Flexibilidade de encarar novas liguagens e frameworks (Com apoio e compreensão dos squads.);

**Desejáveis;:**
- XP AWS.
- XP Docker.
- XP Angular;
- XP Mobile(native or hybrid);

## Benefícios

- Plano de saúde pago integralmente(Unimed);
- VR de R$ 20/dia;
- PLR semestral;
- Cultura diferenciada;
- Autonomia ao dev;

**Diferenciais:**
- Novos projetos, novas techs.
- Stacks diferentes por projeto;
- XP Flutter;
- XP Python;

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um email para rh@blueinv.com.br com seu CV anexado - enviar no assunto: Vaga Front-End Dev

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após cada processo.
E-mail para contato em caso de não haver resposta: dev@bluetechno.com.br

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Júnior
ou
- Pleno
ou
-Sênior

Obs.: Determinado pelo teste técnico do processo seletivo

**Comment by lucaspmarra** [comment]
Opa! Ótima oportunidade para voltar pra minha gyn! CV enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
