### ISSUE TITLE
[REMOTO] Front-end Developer ReactJS na Nave.rs

### ISSUE THREAD

**Issue by jpbretanha** [frontendbr/vagas#3444]
## Nossa empresa

A Nave.rs é uma empresa de consultoria para criação de soluções digitais e utilizamos tecnologia para otimizar e inovar a operação dos nossos clientes. O time da Nave.rs é experiente e atua como uma consultoria em todos os momentos do desenvolvimento das soluções. Somos especialistas na construção de produtos digitais utilizando o que há de mais inovador no mercado de aplicativos e sistemas.

## Descrição da vaga

Buscamos uma pessoa com experiência prévia na construção ou manutenção de sistemas web utilizando ReactJS para integrar nosso time de frontend.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- ReactJS
- Styled Components
- Context API
- Hooks

**Diferenciais:**
- Conhecimento em metodologias ágeis
- React Native

## Benefícios

- Coparticipação no plano de saúde
- VR
- Auxílio Psicológico

**Diferenciais:**
- horário flexível
- notebook da empresa

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um email para vagas@nave.rs com seu CV anexado, linkedin e github - enviar no assunto: Vaga Frontend

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: joaopedro@nave.rs

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by guipolive** [comment]
Adicionar label Júnior
