### ISSUE TITLE
[Remoto] Front-end Developer na Amachains

### ISSUE THREAD

**Issue by defremont** [frontendbr/vagas#3445]
## Nossa empresa

A Amachains (https://www.amachains.com) é uma startup que tem como missão levar transparência e confiança para as pessoas através do desenvolvimento de redes de negócios sustentáveis com Blockchain. Estamos contratando um(a) profissional na área de desenvolvimento Frontend júnior remoto de forma temporária (2 meses), com possibilidade de permanência.

## Descrição da vaga

O(A) candidato(a) ideal será responsável pelo desenvolvimento, teste e depuração de aplicativos Web e móveis responsivos para a empresa. Usando principalmente Nodejs com Vue.js, este candidato deverá traduzir as necessidades do projeto Figma, do usuário e da empresa em um design de front-end funcional.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Conta no Banco do Brasil
- Lattes atualizado

**Desejáveis:**
- Desenvolver e testar a interface do usuário para aplicativos móveis e da Web
- Criar códigos e bibliotecas reutilizáveis para uso futuro
- Usar o Git para gerenciar versões
- Traduzir com precisão as necessidades do projeto Figma, do usuário e do negócio em código de interface funcional

**Diferenciais:**
- Conhecimento de design de API e integração de back-end é uma vantagem

## Benefícios

- Bolsa CNPQ de 2.500,00 R$
- Foco em entregáveis estimados em conjunto, com limite de 30h semanais

## Contratação

Bolsa CNPQ de 2 meses com possibilidade de renovação ou contratação CLT.

## Como se candidatar

Por favor envie um email para selecao@amachains.com com seu CV anexado - enviar no assunto: Vaga Front-end Developer.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: andre@amachains.com

#### Alocação
- Remoto

#### Regime
- Bolsista CNPQ

#### Nível
- Júnior

**Comment by silvablack** [comment]
kkkkk, bolsista pleno?

**Comment by ThalesAlonso** [comment]
A Vaga só se aplica a View JS ? Existe uma carga Horária ? Caso o candidato saiba React JS é possível se inscrever para vaga ?

**Comment by defremont** [comment]
@felipefialho Favor tirar a tag 'pleno'. Acredito que seja inapropriada. 

> A Vaga só se aplica a View JS ? Existe uma carga Horária ? Caso o candidato saiba React JS é possível se inscrever para vaga ?
A vaga tem foco em entregáveis estimados 30h semanais, considerando de seg. a sex.
A seleção será através de um teste em Vue, assim como o trabalho que será realizado. Por tanto é um requisito que seja um profissional apto em Vue.

**Comment by fogeid** [comment]
O horário é flexível?

**Comment by defremont** [comment]
> O horário é flexível?

@fogeid Sim! Contanto que siga entregando semanalmente, não temos este nível de controle do horário de trabalho.

**Comment by defremont** [comment]
Já temos um possível candidato selecionado através desta comunidade! Obrigado a todos!
