### ISSUE TITLE
[São Paulo] Front-end Developer na IAB Consulting

### ISSUE THREAD

**Issue by hrsoul1221** [frontendbr/vagas#3446]
> Vaga Remota durante a pandemia

## HRSOUL

Aqui na HRSOUL somos líderes em recrutamentos e seleções...

## - Sólida experiência com WordPress;
- Bons conhecimentos de plugins e temas de WordPress, HTML5 + CSS3;
- Lógica de programação com JS (ECMA6) e PHP;
- Conhecimento de API REST e RESTFUL e experiência com banco de dados relacional;
- Desejável disponibilidade para início imediato;
- Projeto de 6 meses com possibilidade de extensão;
- Atuação remota durante a pandemia (necessária disponibilidade para eventuais reuniões presenciais).

## Local
São Paulo,SP

## Requisitos

**Obrigatórios:**
- Sólida experiência com WordPress;
- Bons conhecimentos de plugins e temas de WordPress, HTML5 + CSS3;
- Lógica de programação com JS (ECMA6) e PHP;
- Conhecimento de API REST e RESTFUL e experiência com banco de dados relacional;
- Desejável disponibilidade para início imediato;
- Projeto de 6 meses com possibilidade de extensão;
- Atuação remota durante a pandemia (necessária disponibilidade para eventuais reuniões presenciais).

## Contratação
PJ 

## Como se candidatar

Oportunidade TI: Desenvolvedor Front End - Nível Sênior - São Paulo – Indicações p/ sgimenes@hrsoul.com.br ou cadastre seu CV em nosso Site - www.hrsoul.com.br.

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
