### ISSUE TITLE
[São Paulo ou Curitiba] Tech Lead (React Js Sênior) @Grupo Boticario

### ISSUE THREAD

**Issue by joanamendes12** [frontendbr/vagas#3448]
**Descrição:** O Grupo Boticário está em busca de um perfil para contribuir na melhoria tecnológica da empresa. Com a função de liderar o squad de catalogo digital, um produto sendo construído do zero. Uma ótima experiencia de inovação e transformação.

**Local:** Vila Olimpia - São Paulo ou Jardim Botânico - Curitiba

**Contratação:** CLT pelo Boticário.

Requisitos principais: Experiência com React JS Front End, desejável conhecimento em Node JS;
Experiência prévia em gestão de times multidisciplinares de desenvolvimento de software;
Experiência com metodologias ágeis.

Diferencial: Vivência em times ágeis (Scrum, Kanban, etc);
Conhecimento em IaaS Cloud (AWS, Google ou Azure);
Familiaridade em banco de dados relacional e não relacional;
Conhecimento em programação orientado a eventos;
Conhecimento de APIs REST;
Conhecimento de boas práticas de qualidade como TDD e BDD.

Fazer o cadastro no seguinte site: **https://byintera.in/bottlghfe** 
Dúvidas: https://www.linkedin.com/in/joana-mendes-/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
