### ISSUE TITLE
[São Leopoldo] Front-end Developer Reactjs na V4 Company

### ISSUE THREAD

**Issue by mjuchemf** [frontendbr/vagas#3449]
> Vaga Remota durante a pandemia

## Nossa empresa

Quando o assunto é Marketing Digital, aparecem fórmulas mágicas e "novas estratégias" para todos os lados. Você pode ter dúvidas sobre como investir e o que fazer neste ambiente repleto de "gurus" e sobrecarregado de informações. Para o Sócio Fundador da V4 Company, Dener Lippert, Marketing só é Marketing quando vende o produto da empresa. V4 significa vender o seu produto, vender para mais pessoas, vender mais vezes e vender pelo maior valor. Então não importa se você vai criar um site, investir em mídia paga ou qualquer outra estratégia de Marketing Digital. O que realmente importa é vender mais! Faz sentido para você?

Este pensamento foi incorporado pela V4 Company. Depois de alguns anos investindo em Marketing Digital, entendemos que são necessárias amplas estratégias para colher resultados, não apenas uma ou outra iniciativa. Dessa maneira, nos tornamos uma assessoria de vendas com a internet. Dominamos diversas estratégias de marketing para fazer uma empresa vender tudo que é capaz de produzir. Continue navegando no nosso site www.v4company.com e compreenda melhor o nosso processo.

## Descrição da vaga

Alguns dos desafios que você vai encarar:
- Desenvolvimento em Reactjs e React Native.
- Encontrar novas técnicas e tecnologias, com o foco de escalabilidade.
- Expandir seus conhecimentos através da utilização de novas ferramentas, tecnologias, bibliotecas, …
- Necessidade de aprender rápido, e se adaptar às mudanças de situações e prioridades.
- Definição, junto a equipe, de Key Results (conversões e micro-conversões) para acompanhamento de resultados e da utilização do software pela base.

## Local

Escritório, [RIO GRANDE DO SUL], [PORTO ALEGRE]

- Estamos localizados no pólo empresarial Empretec, ao lado da Unisinos , em São Leopoldo/RS.
- Somos guiados por atitudes claras e transparentes em nossa rotina, que nos permitem fazer o máximo para nossos clientes. Trabalhamos de modo colaborativo, o que significa que confiamos nas pessoas que estão do nosso lado.
- Aqui ninguém é empregado de ninguém. O ambiente é o mais horizontal possível, possibilitando a sua autonomia para tomar as melhores decisões para as atividades pelas quais você é responsável. Não espere pelos outros aquilo que você pode fazer por si mesmo.
- Processos claros com rotinas determinadas é o que buscamos, sempre criando maneiras de sermos people-proof. Só assim conseguiremos a escalabilidade que almejamos.

## Requisitos

**Obrigatórios:**

- Conhecimento em Reactjs e React Native
- Familiaridade com marketing digital
- Habilidade de comunicação interpessoal
- Organização e metodologia
- Conhecimento de metodologias ágeis

**Desejáveis:**
- Inglês (reading and listening)  

**Diferenciais:**
- Estatística aplicada a Marketing

## Benefícios

- Liberdade de horário
- Oportunidade de se tornar sócio da empresa com base em objetivos claros

## Contratação

PJ a combinar

## Como se candidatar

Por favor, se cadastrar neste link: https://bit.ly/carreirasv4-github

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: gustavo@v4company.com

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
