### ISSUE TITLE
[Salvador - BA] Front-End Developer

### ISSUE THREAD

**Issue by luisrbferreira** [frontendbr/vagas#345]
## Descrição da vaga

Buscamos um Front-End Developer que tenha conhecimentos consolidados para trabalhar em projetos utilizando Angular.

## Local

Escritório da Conectta Softwares (Disponibilidade para Remoto)

## Benefícios

- Vale transporte
- Vale refeição ou vale alimentação
- Plano de saúde

## Requisitos

**Obrigatórios:**

* Experiência com HTML5
* CSS3, Sass (pré-processador de CSS)
* JavaScript
* Git
* Conhecimentos avançados em: Angular 2 e jQuery

**Desejáveis:**

* Perfil dinâmico, criativo, perfeccionista
* Comprometimento com prazos
* Já ter trabalhado ou se adequar facilmente aos ciclos de entregas de demandas baseados em metodologias ágeis
* Saber trabalhar em equipe e ter boa comunicação
* Noções de: Usabilidade, Acessibilidade e UX

**Diferenciais:**

* Inglês Avançado

## Contratação

CLT a combinar

## Nossa empresa

A Conectta Softwares é uma empresa especializada no desenvolvimento de aplicativos e softwares de acordo com as necessidades de cada cliente, facilitando tarefas administrativas, gerindo custos, rentabilizando tempo e garantindo maior competitividade no mercado.

## Como se candidatar

Por favor envie um email para vagas@conecttasoftwares.com.br com seu CV anexado - enviar no assunto: Vaga Front-End Developer.

**Comment by luisrbferreira** [comment]
A vaga ainda está aberta e agora com disponibilidade para home office.

**Comment by jardelsantana** [comment]
Olá @luisrbferreira, a vaga ainda está aberta?
