### ISSUE TITLE
[100% Remoto] Front-End Architect na [Softplan]

### ISSUE THREAD

**Issue by Jungles22** [frontendbr/vagas#3450]
##Nossa empresa

A Softplan, conhecida como uma das maiores empresas de desenvolvimento de software do país. Temos 1,9 mil Softplayers, cada um com sua referência no mercado e que agregam nos resultados para as nossas unidades. Nosso maior orgulho é dizer que nossos colaboradores são especiais naquilo que fazem e juntos entregamos um produto próprio e de qualidade.

## Descrição da vaga

Hoje nosso desafio é para unidade de justiça, nela construímos o software SAJ, estamos migrando para 6º versão e por isso precisamos aumentar o time.
Este desafio é para quem curte trabalhar com sistema robusto e com as melhores práticas de mercado.
Nele você vai apoiar os times de desenvolvimento a acelerarem suas curvas de aprendizado e boas práticas.
Atuar transversalmente com os vários times de produto da empresa.
Ao invés de deixar os times produzirem vários monolitos de front-end você estará responsável por ajudar esses times a desenvolverem seus fronts de forma modular e bem estruturada. Seja através de mecanismos de plugins / extension points ou "microservices de front-end", você definirá os padrões que serão adotados, bibliotecas de widgets e soluções de design de front-end.
Promoverá partes genéricas / reusáveis de front-end passíveis de serem usados em várias linhas de produto - e não apenas copiar/colar.

## Local

100% remoto (equipamento é enviado na residência)

## Requisitos

Conhecimento avançado de JavaScript e TypeScript.
Conhecimento avançado de frameworks e bibliotecas FrontEnd, com foco principal em React/React Native e Angular.
Conhecimento avançado em Git/GitLab.
Entendimento sobre arquitetura Front-end no que diz respeito a MicroFrontends, Server Side Rendenring, FrontEnd Modular ou Arquitetura de Componentes.
Conhecimento avançado em paradigmas de computação, com foco em POO(Programação orientada a objetos), paradigma funcional e programação orientada a componentes.
Dominar mecanismos de plugins e sua aplicação em JS/TS, buscando a ideologia de fronts desacoplados e componentes espetáveis.
Ter trabalhado na criação de bibliotecas e dependências JS/TS.
Entendimento sobre a filosofia DevOps e criação de pipelines de automatização.
Conhecimento sobre métricas e ferramentas de análise de código.
Como efetuar análises comparativas objetivas entre ofertas de bibliotecas e/ou componentes.
Além de skills técnicos, contamos com suas habilidades em peopleware para trabalhar ajudando e ensinando os diversos times. Sentar junto, entender o problema, saber orientar, ter paciência.

## Benefícios
Oferecemos VR + Plano de saúde + Odonto + Programa de bônus
Oportunidade de desenvolvimento, meet ups, cursos e treinamentos in-company; Incentivo financeiro a cursos de Graduação ou Pós Graduação (50%). Após o período de experiência e mediante aprovação. Incentivo financeiro a certificações (100%). Após o período de experiência e mediante aprovação. Acolhimento psicológico

## Contratação

CLT

## Como se candidatar

Por favor envie um email para ana.h@softplan.com.br com seu CV anexado - enviar no assunto: Vaga Front end

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by lucasfieri** [comment]
Meu sonho de vaga, quem sabe um dia? haha

**Comment by JMustang** [comment]
Waww , só falto um programa pra iniciantes heheheheheheheh sensacional.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
