### ISSUE TITLE
Vaga fechada

### ISSUE THREAD

**Issue by RafaelferC** [frontendbr/vagas#3452]
## Nossa empresa

Uma Instituição Financeira, uma das maiores do Brasil, presente no mercado global e com uma média de 45 mil funcionários no Brasil.

## Descrição da vaga
(9 vagas)

Principais atividades:
- Responsável pela análise e desenvolvimento de sistema em Angular, incluindo a testes unitários e funcionais automatizados;
- Configuração, Build e Deploy nos ambientes;
- Acompanhamento de implantação e suporte aos consumidores;
- Avaliar defeitos através de análises, identificar as causas e implementar correções.

## Local

Escritório, 
Estado: São Paulo, 
Cidade: São Carlos,
(Aceitamos candidatos de outras regiões que avaliem mudança).

## Requisitos

**Obrigatórios:**

- 2 anos de experiência em programação utilizando plataforma Angular 5+ (Typescript, HTML, CSS);
- Experiência com preprocessador CSS (SaSS)
- Conhecimentos de testes funcionais automatizados (Selenium);
- Conhecimento em Integração de Sistemas utilizando Serviços e/ou APIs;
- Conhecimento em ferramentas colaborativas (Jira e Confluence);
- Conhecimento metodologia Ágil (Scrum Team);
- Concluído ou cursando tecnólogo ou bacharel.

**Desejáveis:**
- Conhecimento de práticas para desenvolvimento seguro.

## Benefícios

- Plano de saúde – Sulámerica (Cooparticipação);
- Assistência odontológica  – Interodonto;
- VR de 600,00/mês;
- Auxilio creche;
- Bonificação variável de acordo com a meta.

## Contratação

CLT (direto com o banco).

## Como se candidatar

Basta cadastre-se no link: http://gg.gg/loehc

#### Alocação
- Alocado.

#### Regime
- CLT.

#### Nível
- Júnior.

**Comment by igorpinhh** [comment]
e remoto ou alocado?

**Comment by RafaelferC** [comment]
> é remoto ou alocado?

alocado!

**Comment by RafaPalau** [comment]
Não consegui acessar o link do encurtador.

**Comment by mrangel-jr** [comment]
É melhor então remover a tag remoto ou se estiverem remoto durante a pandemia, colocar a tag apropriada

**Comment by RafaelferC** [comment]
> É melhor então remover a tag remoto ou se estiverem remoto durante a pandemia, colocar a tag apropriada

A tag remoto foi automático. Como faço para tirar, quanto é assim?

**Comment by RafaelferC** [comment]
> Não consegui acessar o link do encurtador.

Atualizei!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by RafaelferC** [comment]
Oi pessoal, vagas fechadas!
