### ISSUE TITLE
[São Paulo] Front-End Developer na D1

### ISSUE THREAD

**Issue by everton-ribeiro** [frontendbr/vagas#3453]
> Vaga Remota durante a pandemia

## Nossa empresa

A D1 é a plataforma de customer engagement responsável pela automação de
comunicações personalizadas e relacionamento multicanal de grandes varejistas,
seguradoras e líderes em meios de pagamento.
Com tecnologia baseada em Computação em Nuvem e Big Data, ela integra os canais de
comunicação digitais, móveis e impressos, reduzindo custos operacionais e tornando
as corporações mais inteligentes através de uma visão única do seu cliente.
Acesse o nosso site para mais informações [d1.cx](https://www.d1.cx).

## Descrição da vaga

Participar do o ciclo de vida dos produtos, com foco em desenvolvimento front-end.
Desenvolver interfaces em parceria com designers e especialistas de UX.
Experiência na integração de front-end e back-end por meio de REST APIs.

## Local

100% Remoto durante a pandemia após 3 vezes por semana.
Escritório próximo a estação Granja Julieta - SP.

## Requisitos

**Obrigatórios:**

- Domínio de Html, Css, Javascript, Typescript;
- Experiência com React, Styled Components, Redux, Redux-Saga;
- Testes (TDD, BDD), testes de unidade com Jest e integrados (E2E) Cypress;
- Experiência com Git para versionamento de código;

**Desejáveis:**

- Conhecimento em Docker;
- Conhecimento de GraphQL;
- Vivência com métodos ágeis, como Scrum e Kanban;

## Benefícios

- Plano de Saúde;
- Vale Refeição;
- Vale Transporte;
- GymPass (Auxílio Academia);
- Plano Odontológico;
- Alura;
- Oportunidades de aprender muito a cada dia, trabalhando com mentores Endeavor e líderes referência em suas áreas;

## Contratação

CLT

## Como se candidatar

Link para se candidatar na Gupy [clique aqui](https://d1.gupy.io/jobs/187227?jobBoardSource=gupy_public_page).

Link para se candidatar no linkdin [clique aqui](https://www.linkedin.com/jobs/view/1997046949/).

Ou se preferir envie um e-mail para everton@d1.cx com seu CV anexado. Não se esquece de escrever no assunto: Vaga Front-End.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: everton@d1.cx.

#### Alocação

- Alocado
- Remoto

#### Regime

- CLT

#### Nível

- Júnior
- Pleno

**Comment by igorpinhh** [comment]
aceita candidatos de outros estados?

**Comment by everton-ribeiro** [comment]
Olá @igorpinhh desculpa a demora, mas  vaga não e 100% remoto somente durante a pandemia, no caso vc teria que vim 2 vezes por semana no escritório .

**Comment by mrangel-jr** [comment]
Então @everton-ribeiro , seria interessante manter somente a tag "🦠 Remoto durante pandemia"

**Comment by everton-ribeiro** [comment]
Bom dia @mrangel-jr, @felipefialho  desculpa a demora mas a Label remoto e somente para vaga 100% remoto pq após a pandemia nos temos 3 dias fiquei confuso agora

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
