### ISSUE TITLE
[São Paulo] Front-end Developer /React  na 5A Attiva

### ISSUE THREAD

**Issue by helenmatos** [frontendbr/vagas#3457]
Olá Developer! 
Tudo bem? A 5A Attiva, está com vagas para Front End Sr. 

## Descrição da vaga
Buscamos alguém que AME programar, que GOSTE muito do que realmente faz. 
Que atue com desenvolvimento Front End; React, Redux, React Native, Material Design, banco de dados 
Vai participar do projeto do portal do cliente, com aplicações web e mobile.

## Local
Remoto durante a pandemia ( previsto até final do ano) Após isso, será no Escritório, [São Paulo], [São Paulo], [Jardim Paulista]

## Requisitos

**Obrigatórios:**
- 5 anos de experiência com Front End
- 3 anos de experiência com React 

**Desejáveis:**
- conhecimentos em React Native 

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para helen.matos@5aattiva.com.br com seu CV anexado - enviar no assunto: Vaga Front End Sr 

#### Alocação
- Alocado e Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by mrangel-jr** [comment]
@helenmatos , seria interessante trocar a label e colocar "Remoto durante a pandemia"

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
