### ISSUE TITLE
[São Paulo] PL / SR Front-end Developer na BTG Pactual 100% REMOTO

### ISSUE THREAD

**Issue by taianeuchoac** [frontendbr/vagas#3459]
## Nossa empresa
O BTG Pactual é um dos maiores bancos de investimentos em atuação no Brasil.

## Descrição da vaga
Atuará na equipe IT Digital, que está inserida dentro do pilar de System Development/Digital e é responsável por desenvolver o Portal de Clientes, que é uma ferramenta voltada para os clientes da empresa e tem como objetivo disponibilizar informações sobre seus investimentos, transações, onboarding digital e acesso a produtos e serviços. Também é responsável por outros canais de comunicação com os clientes, como o Portal Institucional, Área Administrativa B2B e Soluções mobile.

## Local
Empresa esta alocada na Av. Faria Lima, porém abriu a possibilidade para atuação 100% remota mesmo após a pandemia.

## Requisitos
Técnico:
Angular JS & Angular 2+
Javascript        
Typescript
Git
HTML5
SASS/SCSS
CSS3+
Gulp
NPM
Testes unitários
Conceitos de API Restful
Webpack

- Desejáveis:
Scrum
Gitflow

## Benefícios
Plano de saúde
Seguro de vida
VR
Auxílio creche
Plano Odontológico

## Contratação
CLT

## Como se candidatar
Por favor envie um email para taiane@mazza.tech com seu CV anexado - enviar no assunto: Vaga FrontEnd

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: taiane@mazza.tech

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
