### ISSUE TITLE
[São Paulo] - Frontend Developer | B2W Digital

### ISSUE THREAD

**Issue by williamcosta** [frontendbr/vagas#346]
## Descrição da vaga

Transformar os PSD's desenhados por nossa equipe de design em código fonte WEB (Html, CSS e JS), transformando em interfaces web para plataforma Magento (e-commerce), reunião de briefing com cliente e demais envolvidos nos projetos, participar do processo de homologação dos layouts implementados, acompanhar a publicação dos projetos em produção, e atuar nas correções no período de operação assistida, boa comunicação e relação interpessoal.

## Local

Alocado, São Paulo - Vila Olímpia

## Benefícios

- VR e VT
- Plano de Saúde
- Horário Flexivel

## Requisitos

**Obrigatórios:**
- Conhecimentos sólidos em desenvolvimento frontend: HTML5, CSS3, Javascript e jQuery;
- Conhecimento em pré-processadores CSS (SASS ou LESS);
- Conhecimento de task-runners como Grunt ou Gulp;
- Conhecimento básico em programação PHP;
- Desejável conhecimento de desenvolvimento WordPress (e experiência com custom fields, taxonomies, custom post types) ou outro CMS;
- Experiência com desenvolvimento frontend para Magento (estrutura de temas e fallback);
- Experiência com design responsivo e cross-browser;
- Experiência com desempenho, otimização e web performance;
- Experiência com Git;

**Desejáveis:**
- Conhecimento em SEO e boas práticas de código semântico;
- Conhecimento em Google Analytics e Google Tag Manager;
- Inglês intermediário para leitura, escrita e entendimento.

## Contratação

CLT

## Nossa empresa

A **E-smart** foi adquirida pela **B2W Digital** nos meados de 2015, aonde nos unimos com o time da **BSeller**, hoje somos um dos principais braços da companhia no desenvolvimento de novos e-commerces atendendo a grandes empresas do setor. 

## Como se candidatar

Por favor envie um email para valdir.calixto@e-smart.com.br com seu CV anexado e pretensão salarial - enviar no assunto: Vaga - Frontend Developer

**Comment by williamcosta** [comment]
Labels - Alocado, CLT, Pleno e Sênior.

**Comment by IgorSousaFront** [comment]
possibilidade de remoto?

**Comment by williamcosta** [comment]
Opa @IgorSousaFront infelizmente não. :(

**Comment by williamcosta** [comment]
Vaga ainda está aberta.
