### ISSUE TITLE
[REMOTE POSITION] Front-end Developer @ Prediktive

### ISSUE THREAD

**Issue by majobonel7** [frontendbr/vagas#3460]
We are looking for a **Front End Engineer** based in Latin America to work on a long-term project for one of our clients, a consulting group based in Charlotte, North Carolina.

Our client builds onboarding and payment solutions to Financial Services, Healthcare, and Logistics. Their stack is composed of a large variety of technologies such us: Angular 8, Typescript 3.5, MobX 5.9.0, Bootstrap 4, Ngx-bootstrap for Angular Integration, Google Analytics, C#, Node, DotNet Core 3.1, Azure Keyvault, Encrypted CosmosDB, SQLServer, Azure Functions & Webapps & API Mgmt, Swagger, HTTPS. Also, it’s integrated to several third-party systems such as GIACT API set, LexisNexis, Real Search, SendGrid, Amazon: Simple Email Service (SES), Zip-Tax, NPESS, MATCH, Taxware.

The person in this role should have top-notch software engineering knowledge and needs to be really passionate about it and open to new ideas and technologies.

**Responsibilities**
- Work on the development of an onboarding/enrollment tool that boards merchants to a processor through a bank partner and the corresponding support tool.
- Enhancement and maintenance of our client’s current platform
- Development of new features as needed

**Requirements**
- Advanced Level of English
- Self-driven. Work autonomously with little supervision
- 5+ years of experience working with Angular2+ (8 is preferred) and Typescript 3.5
- Solid experience working with front end technologies such as HTML, CSS, MobX 5.9.0, Bootstrap 4, Ngx-bootstrap for Angular Integration, Google Analytics
- Experience managing state within a single page application
- Ability to take ownership of new features
- Communicates well with other developers/managers with comments, criticisms, and general input
- Ability to work with and guide junior developers
- Experience creating self-contained, reusable modules and components
- Experience working with Start-ups

**Bonus Points**
- Bachelor’s Degree in Computer Science, Systems Engineering or related fields
- Experience developing with Node JS and/or C#
- Team leader experience
- Experience creating UI libraries

### You can apply by filling this form: https://bit.ly/pso-163-frontend
**Please include my name, Maria Bonel, when applying and I'll get back to you as soon as possible!**

**#angular8 #typescript #frontend #javascript**

**Comment by r-enemy** [comment]
It hasn't completed 4 years since Angular's 2 first release yet.
