### ISSUE TITLE
[Remoto] Front-end Developer na Performa_IT

### ISSUE THREAD

**Issue by TaliaCouto** [frontendbr/vagas#3463]
## Novas tecnologias e desafios
E aí Devs! A Performa_IT está decolando e precisamos da sua ajuda para alcançar esse objetivo. 
Saca só.. um pouquinho do que vai encontrar:

## O que você vai fazer
Inclusão da conversão dos wireframes de design da UI/UX para o código real produzindo elementos visuais da web. Junto com o designer, você fará a ponte entre o design interações e a implementação técnica.

## O que você precisa ter
Conhecimento em Git, HTML5, CSS3, LESS, SASS, JavaScript, Angular 2+ e processamento de solicitações assíncronas

## Local
Remoto
 
## Benefícios
- Plano de saúde
- Vale de R$ 500,00
- Bonus de 1 salário (equivalente ao 13 salário)
- Descanso Remunerado
- Jornada de 40hs semanais
- Horário de trabalho das 9h as 18h
- Acesso a novas tecnologias

## Contratação
Cooperativa de Tecnologia

## Como se candidatar
Mande seu CV para o e-mail oportunidades@performait.com com o Assunto: Front-end

## Quem somos
A PerformaIT é uma empresa de tecnologia atenta as necessidades dos clientes e as novas tecnologias que surgem a todo momento. Acreditamos que nossos produtos e serviços devem ajudar nossos clientes a atingir uma meta, resolver um problema ou satisfazer uma necessidade.
Com uma busca incessante pela qualidade procuramos definir nossos processos de forma à atender aos principais modelos de mercado, porém sem perder a agilidade e a flexibilidade no atendimento as necessidades de nossos clientes. Nosso conhecimento, criatividade e estratégias diferenciadas são nossos pilares para o desenvolvimento de relações de longo prazo com todos nossos parceiros, colaboradores e clientes.

#### Alocação
- Remoto

#### Regime
- Cooperado

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
