### ISSUE TITLE
[REMOTE POSITION] Front End Engineer (Angular) @ Prediktive

### ISSUE THREAD

**Issue by majobonel7** [frontendbr/vagas#3464]
We are looking for a **Front End Engineer** with extensive experience with Angular, based in Latin America to work on a long-term project for a Fintech Startup based in Charlotte, North Carolina.

Our client builds onboarding and payment solutions to Financial Services, Healthcare, and Logistics. Their stack is composed of a large variety of technologies such as Angular 8, Typescript 3.5, MobX 5.9.0, Bootstrap 4, Ngx-bootstrap for Angular Integration, Google Analytics, C#, Node, .NET Core 3.1, Azure Keyvault, Encrypted CosmosDB, SQL Server, Azure Functions (Webapps & API Mgmt), Swagger, and HTTPS. Also, these solutions are integrated into several third-party systems such as GIACT API set, LexisNexis, Real Search, SendGrid, Amazon: Simple Email Service (SES), Zip-Tax, NPESS, MATCH, and Taxware.

The person in this role should have top-notch software engineering knowledge. Passionate people open to new ideas and technologies will fit in our client’s Team.

**Responsibilities**
- Development of an onboarding/enrollment tool that boards merchants to a processor through a bank partner and the corresponding support tool
- Enhancement and maintenance of their current platform
- Development of new features as needed

**Requirements**
- Advanced Level of English
- Self-driven. Work autonomously with little supervision
- 5+ years of experience working as a Software Engineer
- 3+ years of experience with Angular2+ (8 is preferred) and Typescript 3.5
- Solid experience working with front end technologies such as HTML, CSS, MobX 5.9.0, Bootstrap 4, Ngx-bootstrap for Angular Integration, and Google Analytics
- Experience managing state within a single page application
- Ability to take ownership of new features
- Great communication skills, providing feedback and general input to other developers/managers
- Ability to work with and guide junior developers
- Experience creating self-contained, reusable modules and components
- Experience working with Start-ups

**Bonus Points**
- Bachelor’s Degree in Computer Science, Systems Engineering or related fields
- Experience developing with Node JS and/or C#
- Team leader experience
- Experience creating UI libraries

### You can apply by filling this form: https://bit.ly/pso-163-frontend
**Please include my name, Maria Bonel, when applying and I'll get back to you as soon as possible!**

#RemotePosition #FrontendDeveloper #angular8 #typescript #frontend #javascript

**Comment by felipefialho** [comment]
@majobonel7 Why you [open the same issue](https://github.com/frontendbr/vagas/issues/3460) again? 🤔
