### ISSUE TITLE
[São Paulo] Front-end Developer na Prontmed

### ISSUE THREAD

**Issue by tkolling-ptmd** [frontendbr/vagas#3465]
> Vaga Remota durante a pandemia

## Prontmed

A Prontmed é uma empresa de tecnologia e dados na área de saúde e por isso a área de desenvolvimento é o coração do nosso time. O nosso time de desenvolvedores cria novas features para médicos, assim como novos modelos de comunicação com parceiros e melhores formas de análise de dados.

Nós trabalhamos com novas tecnologias e por isso valorizamos os profissionais que são abertos a aprender novas coisas e não tem medo de sair de sua zona de conforto.
●	Desenvolvimento de features que irão aprimorar o atendimento dos médicos aos pacientes
●	Integração com sistemas terceiros
●	Triagem de bugs e exceções em produção

Como é um dia típico para um desenvolvedor na Prontmed?
Nosso time de desenvolvimento trabalha usando metodologias ágeis com bastante proximidade com o time de produto, e tentamos adaptar as nossas formas de trabalho levando em consideração o estilo de desenvolvimento dos desenvolvedores. Possuímos um ambiente de trabalho aberto e nosso escritório possui locais colaborativos e confortáveis (puffs e tatames). De modo geral queremos que nossos desenvolvedores se sintam confortáveis e por isso não temos um dress-code, então você pode se quiser trabalhar usando shorts e crocs.
Também somos adeptos do Home Office, porém não exclusivo pois gostamos de nos encontrar para um HH, reuniões etc.

## Local

Remoto com eventuais dias no escritório localizado no bairro Jardim Paulista, São Paulo, SP

## Requisitos

**Obrigatórios:**
- Domínio em HTML5 e CSS3
- React + Redux
- Bootstrap
- LESS
- Versionamento GIT
- Desenvolvimento ágil de projetos (Scrum )

**Desejáveis:**
- Testes unitários/funcionais/integrados
- SASS
- Conhecimento de UX

**Diferenciais:**
- React Native

## Benefícios

- Salário competitivo de mercado
- Outros benefícios a combinar conforme modelo de contratação

**Diferenciais:**
- Horários flexíveis

## Contratação

CLT ou PJ a combinar

## Como se candidatar

Por favor envie um email para carreiras@prontmed.com com seu CV anexado - enviar no assunto: Vaga Front-end Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após cada processo.
E-mail para contato em caso de não haver resposta: thiago.kolling@prontmed.com

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
