### ISSUE TITLE
[Remoto] Front-end Developer na Ziba Design

### ISSUE THREAD

**Issue by gaprl** [frontendbr/vagas#3466]
## Nossa empresa

www.ziba.com

Na Ziba Design, nós inovamos e criamos experiências físicas e digitais.

Não é um exagero dizer que as melhores e mais importantes empresas do mundo confiam na Ziba para criar ou transformar suas marcas, produtos e serviços, seus ambientes físicos, e reimaginar seus negócios para o mundo digital.

Somos obsecados pela importância da experiência do cliente, e estamos procurando por novos parceiros talentosos dispostos a trabalhar em desafios digitais, em uma variedade de projetos, com parceiros do mundo todo.

Somos uma empresa Norte-Americana de Portland, Oregon, estabelecida no mercado por mais de 35 anos, e estamos expandindo nossa equipe de parceiros Brasileiros e Portugueses para trabalhar em diversos projetos tanto front-end quanto back-end.

## Descrição da vaga

Nesta posição, você vai trabalhar diretamente com a nossa excelente equipe de UI e UX para desenvolver lindas experiências digitais para a web, liderar decisões técnicas para nossas projetos front-end, e ajudar a criar excelentes soluções à diversos desafios de nossos clientes.

## Local

Completamente remoto! 👨‍💻 👩‍💻

## Requisitos

**Obrigatórios:**
- 🇺🇸 ⠀Excelente Inglês ([B2, C1, C2](https://tracktest.eu/english-levels-cefr/)), principalmente a facilidade em comunicação verbal e escrita para entender requirementos de projeto e para participar e contribuir à diversas sessões de brainstorming, tanto com pessoas com experiência técnicas ou não.
- 💻  ⠀Conhecimento sólido em Javascript, CSS, HTML, Responsive Design e você tá sempre ligado com as boas práticas do mercado.
- 🕸 ⠀Experiência prévia com React ou Angular.
- 🌎  ⠀Habilidade de participar de uma equipe internacional, diversa, e em um ambiente rápido e extremamente dinâmico.
- 👨‍🎨  ⠀Entusiasmo pela atenção aos detalhes e por criar boas experiências e interfaces para o usuário. 
- 🧠  ⠀Familiaridade com Git, Agile, RESTful APIs, e testes.

**Desejáveis:**
- 🎞 ⠀Trabalho prévio em animar experiências na web, como parallax, etc.
- 👨‍🏫⠀Experiência em treinamento, mentoria, e assistência à outros desenvolvedores.
- 🤝⠀Capacidade de prever e coordenar integrações entre equipes de front-end e back-end para um trabalho eficiente e ágil. 

**Diferenciais:**
- ⭐️⠀Experiência com Wordpress, Contentful, ou SquareSpace.

## Benefícios

- 💰 ⠀Excelent remuneração (em USD).
- 🕐  ⠀Horas flexíveis.
- 🔥 ⠀Trabalhar em projetos impactantes com grandes empresas do mundo todo.
- 💪 ⠀Alto nível de independência, e oportunidades frequentes de você escolher quais tecnologias e métodos de desenvolvimentos à sua preferência.
- 📈⠀Ajuda a crescer profissionalmente, em um abiente de constante aprendizado e exploração.

## Contratação

PJ

## Como se candidatar

Por favor, se candidate preenchendo este formulário:
[https://forms.gle/ojmaBZ3DF6Cdq1gEA](https://forms.gle/ojmaBZ3DF6Cdq1gEA)

Todo o processo de entrevista será conduzido em inglês.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
