### ISSUE TITLE
[Anywhere Office/Remoto] Front-end Developer (vue.js) na viralize.online (R$ 2.100,00) 

### ISSUE THREAD

**Issue by viralize-devs** [frontendbr/vagas#3468]
# Viralize (viralize.online)

A Viralize é uma startup brasileira no segmento de marketing digital. Começamos em 2019 e hoje, um ano e meio depois, estamos tendo um crescimento mensal constante e por conta desse sucesso, já contamos com uma equipe de 30 pessoas espalhadas por todo Brasil (e crescendo).

Acreditamos que o principal valor que devemos cultivar é o bom caráter, é a base de qualquer outro valor interpessoal e o mínimo necessário para se construir um time de uma empresa ambiciosa. Com isso fica mais fácil desenvolver relacionamentos, comunicação entre as pessoas e principalmente criar um ambiente de trabalho agradável e motivador, mesmo que 100% remoto. 

Hoje nosso carro chefe é a nossa plataforma para criação de posts. Conseguimos reduzir em até 90% o custo de produção de posts profissionais para redes sociais, mas ainda temos muitas coisas para melhorar e expandir. Acesse: viralize.online

## Descrição da vaga

Criação de telas em vue.js que o nosso designer de UI/UX irá fornecer no Figma

## Local

Remoto, qualquer lugar que tenha uma boa internet e um ambiente silencioso pra gente fazer uma call eventualmente :) 

## Requisitos

**Obrigatórios:**
- Experiência em VUE.JS 
- Experiência em Jasvascritp 

**Desejáveis:**
- Quasar.js

**Diferenciais:**
- TypeScript 
- Konvas
- Svg
- Metodologia Ágil
- Inglês

**Diferenciais:**
- Anywhere office (Pq não há nada mais importante na vida do que liberdade)
- Time incrível (A melhor cultura de empresa que você já viu)
- Oportunidade de crescimento (time esta crescendo todo mês) 

## Contratação

PJ a combinar

## Como se candidatar

Acessar o formulário: https://forms.gle/4GE9NfWYk8FBF5SL8

## Tempo médio de feedbacks

Instantaneo/ a combinar

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by bhfigueiredo** [comment]
Enviado!

**Comment by fogeid** [comment]
Quais são os horários?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
