### ISSUE TITLE
[100% Remote] Front-end Developer at Mobile Jazz

### ISSUE THREAD

**Issue by lucianosantana** [frontendbr/vagas#3469]
## Nossa empresa

Founded in 2011, [Mobile Jazz](https://mobilejazz.com/) has evolved from a mobile app development agency to a full-stack technology partner, including development services like backend, frontend, native mobile, embedded systems, UX & design, and security.

We’re a fully remote working company with team members spread all over the world, from Thailand to the Czech Republic, although many of us are based in Barcelona, where the company previously had an office. All our communication is in English.

Although we work in the CET timezone, our work schedule is flexible. We don’t have restrictions on holidays and time off, and many of our team continue to work with us while traveling the world. As long as you deliver the work you’ve committed to, that’s what matters to us.

You can find out a bit more about us by reading our [company handbook](https://mobilejazz.com/docs/company-handbook/mobile-jazz-company-handbook.pdf), which has had nearly 100,000 downloads since going live in March. We’re proud to say that our average employee stay is three years — more than double the average for our industry. And we’ve got a long list of retained clients, based everywhere from Melbourne to San Francisco. We take immense pride from the fact that they trust our expertise, methodologies and market knowledge.

## Descrição da vaga

We’re looking for a **senior web frontend developer** to join our growing team! You will join the web engineering team in Mobile Jazz and will work closely together with our backend engineers, as well as with UX experts and graphic designers on delivering excellent consulting work for our international clients.

## Local

Remote

## Requisitos

As a senior frontend developer, you should have:

* A strong understanding of **TypeScript**, **JavaScript** and **ES6** standards.
* Have plenty of experience building single page applications, preferably using **Angular** and **Ionic** knowledge.
* Have expert knowledge of **HTML**, **CSS** and pre-processors like **SASS**.
* Have used version control systems such as **Git**.

Additionally, the candidate we’re looking for must possess the following:

* A good level of **English** (both written and spoken)
* First-rate communication skills
* The ability and aim to work remotely

## Benefícios

- Work from anywhere
- Quarterly bonus program
- Flexible working hours
- Company sponsored retreats
- Remote office events

## Contratação

To be defined

## Como se candidatar

Use our Jobs API. Check the instructions on Mobile Jazz website [carreers page](https://mobilejazz.com/careers/)

## Tempo médio de feedbacks

If you fit on the profile you'll get a response in few days

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
