### ISSUE TITLE
[São Paulo] - Front-End Developer

### ISSUE THREAD

**Issue by kadurodrigues** [frontendbr/vagas#347]
## Descrição da vaga
 
Buscamos um Front-End de nível pleno / sênior que possa nos ajudar na implementação de um sistema desenvolvido em PHP.

## Local

Região da Berrini (Alocado)

## Requisitos
- HTML5
- CSS3
- SASS
- Bootstrap
- JavaScript
- jQuery
- Experiência com UX
- Metodologias ágeis

**Desejáveis:**
- Conhecimento mínimo em PHP

## Contratação

PJ (3 meses) depois CLT

## Nossa empresa

A TalentFour é uma empresa de consultoria de TI com foco maior nos processos de Desenvolvimento de Software, Governança, Segurança da Informação, Infraestrutura (TI e Telecom),
Suporte Técnico e Operação.

## Como se candidatar

Por favor envie um email para amanda.placa@talentfour.com.br com seu CV anexado - enviar no assunto: Vaga Front-End Developer

**Comment by uselessdev** [comment]
Enviado :D

**Comment by kadurodrigues** [comment]
Dev contratado 👍🏻
