### ISSUE TITLE
[Florianópolis/Remoto] Full-Stack Developer na ArcTouch

### ISSUE THREAD

**Issue by ramospedro** [frontendbr/vagas#3470]
## Nossa empresa

We're ArcTouch, and for over a decade we've been creating lovable apps, web sites and more for world leading companies like Walmart, Disney, Audi, 3M (colocar o link do portfolio junto), and many more. Since launching our first app in 2009, we've followed these core principles for success:

- Create lovable apps, the perfect blend of something that's both useful and delightful
- Help our clients become superheroes, because long-term partnerships matter
- Treat every app like it’s our own, even if our name isn’t on it
- Stand behind everything we build with a Forever Warranty 
- And most of all, be a software development company that people trust

If you're passionate about technology and building great products, we want you to join us!

## Descrição da vaga

- Develop great front-end features, rich of interactions, scalable and maintainable, using ReactJS, Angular or VueJS
- Design and create data fetching and state management systems on the front-end using Flux, Redux or Mobx (but if you are familiar with another tool that may do a great job with that, bring it on)
- Partner up with our Product Designers to iterate, validate and improve the design of our product
- Write unit tests to detect and prevent any changes that may break the design contract
- Focus on cross-browser development, deploying the same user experience for a wide range of browsers, even those not chromium-based
- Define and implement a fit usage of GitFlow, using either GitHub, GitLab or any other git repository
- Design and build readable code, well-defined architecture, following the OOP pillars: Encapsulation, Data Abstraction, Polymorphism, and Inheritance (hey, Functional Programmers, feel free to join as well. We’d love to level our products with some FP)
- Engage in English meetings with our clients, helping them identify better approaches and solutions, sustain opinions on complex conversations to negotiate and estimate deadlines

## Local

Remoto ou Escritório, Florianópolis, SC, Saco Grande

## Requisitos

**Obrigatórios:**
- English (Advanced)

## Diferenciais

ArcTouch offers a competitive base salary with comprehensive benefits including medical and dental, catered meals, video game room, a fully stocked fridge, paid English training, professional development, and more. But don’t just take our word for it. Make sure to check out our employee reviews on Glassdoor to find out why they love working for ArcTouch.
ArcTouch is an Equal Opportunity Employer (EOE). Applicants are considered for employment without regard to age, race, color, religion, sex, national origin, sexual orientation, gender identity and gender expression, disability or veteran status.

Come join us!

## Contratação

CLT

## Como se candidatar

More details about this role and application form here https://grnh.se/987ae3c51us

Or feel free to contact on LinkedIn me and we can chat about the company and this role : )
https://www.linkedin.com/in/ramos-pedro/

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by ramospedro** [comment]
A vaga permanece aberta!
Preenchemos algumas posições, mas ainda temos algumas em aberto.

**Comment by SaMatheus** [comment]
@ramospedro Alguma para Estágio ou Jr?

**Comment by ramospedro** [comment]
> @ramospedro Alguma para Estágio ou Jr?

Olá, Matheus!
Esta não é nível junior. Depois me manda uma mensagem no LinkedIn pra eu manter teu contato. De vez enquando surge alguém pedindo indicações e é sempre bom ter contatos pra indicar : )

**Comment by SaMatheus** [comment]
@ramospedro Opa Pedro, muitíssimo obrigado, mando sim. Pode me passar seu linkedin?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
