### ISSUE TITLE
[Belo Horizonte] Front-end Developer na 123Milhas

### ISSUE THREAD

**Issue by damasiomg** [frontendbr/vagas#3475]
## Nossa empresa

A 123Milhas é uma empresa brasileira de emissão de passagens aéreas com milhas. Buscamos mudar as relações de consumo oferecendo para nossos clientes a possibilidade de viajar pagando menos em passagens aéreas com transparência e responsabilidade. 

Unindo tecnologia avançada à uma excelente equipe, a 123Milhas está crescendo e demonstra a necessidade de inovar e oferecer bons preços e atendimento de qualidade para os clientes. 
 
Com nossos preços, milhares de pessoas fizeram a viagem dos sonhos, reencontraram a família e conheceram novos lugares e culturas. Fazer com que mais gente tenha novas experiências é o nosso objetivo!

## Local

Bairro Funcionários em Belo Horizonte - Minas Gerais.

## Requisitos

**Obrigatórios:**
- Graduação ou graduando na área de tecnologia;
- Javascript (ES2017+) com conhecimentos voltado para linguagem client-side;
- Libs e Frameworks de desenvolvimento Front-end orientados a componentes (AngularJS e/ou React);
- Conhecimento eme Pré-processadores (LESS/SAAS);
- Git/github;
- Bundling (GULP - Webpack);
- HTML5, CSS3;
- Design Responsivo.

**Diferenciais:**
- NodeJS;
- REDUX - HOOKS;
- Programação Funcional;
- Aplicação de técnicas de SEO.

## Benefícios

- Convênio saúde UNIMED;
- Cursos tecnológicos;
- 90% reembolso para certificações na área de atuação;
- Pagamento de inscrições de eventos de TI, como: conferência DevOps Day, Front In entre outros;
- Vale-refeição R$ 22,00 ao dia.

**Diferenciais:**
- Incentivo de R$ 200 mensal (pode ser utilizado em educação);
- Horário flexível, banco de horas e horas extras remuneradas.

## Contratação

CLT

## Como se candidatar

Por favor, envie um email para vagas@123milhas.com.br com seu CV anexado - enviar no assunto: FRONT-END PLENO

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
