### ISSUE TITLE
[São Paulo] Frontend Developer na Legaltech Digesto

### ISSUE THREAD

**Issue by ricardocabral** [frontendbr/vagas#3476]
> Vaga Remota durante a pandemia

## Nossa empresa

Somos uma lawtech fundada em 2012 e desde então temos construídos bases de dados, novos produtos, serviços e tecnologias de extração, tratamento e classificação de dados jurídicos, que entregam inteligência agregada para nossos clientes.

### Porque construímos
Nosso objetivo é tornar o direito no Brasil mensurável e computável através de tecnologia, além de ajudar os operadores do Direito a focarem em atividades de alto valor intelectual, delegando tarefas repetitivas para máquinas.

### As pessoas
No Digesto você vai encontrar pessoas que priorizam o fazer acima do parecer e que têm paixão em usar tecnologia para resolver problemas de nossos clientes. Batalhamos diariamente para nos manter inovadores e aplicar com excelência tecnologias para melhorar a prática do Direito no Brasil.

Para viabilizar a manutenção e crescimento da empresa, cultivamos uma equipe de indivíduos de talento ímpar, preocupados com a melhoria contínua deles mesmos, nossos produtos, processos e satisfação do cliente. Como organização, prosperamos em equipes pequenas, que nos permite sermos ágeis e flexíveis, evitando qualquer burocracia que atrase o crescimento. Somos motivados pelas oportunidades dadas por nossos clientes e nossa paixão de construirmos juntos soluções.

### Nosso processo de desenvolvimento de software
Usamos internamente processos ágeis (com "a" minúsculo, i.e. sem dogmas) e leves, seguindo as boas práticas da comunidade opensource. Cada equipe tem autonomia para definir detalhes de seu ciclo de sprints e suas práticas. Geralmente adotamos scrum com ciclos quinzenais, incluindo reuniões de planejamento e revisão de roadmaps bimestrais com todas as equipes.

Embora sejam missão-crítica para nossos clientes, nossos produtos web, robôs e APIs são bastante estáveis e praticamente não há incêndios para serem apagados. Assim não há stress nas equipes e todos mantêm uma carga horária de trabalho saudável.

## Descrição da vaga

Estamos crescendo nossa equipe e buscamos desenvolvedores para integrar o time e construir novos produtos focados em dados. Temos vagas de frontend para a criação de produtos novos que permitam nossos clientes a extrair mais valor de nossas bases de dados massivas.

Trabalhamos muito com Angular 9 em nossos produtos, e um pouco de React nos sistemas internos. De curiosidade, no backend usamos bastante Python, PostgreSQL, Flask, FastAPI, webscraping e serviços distribuídos, mas mesmo sem conhecer as tecnologias, o que buscamos acima de tudo são pessoas curiosas e interessadas em aprender, fazer parte do time, abraçar os produtos e crescer.

## Local

Pinheiros - São Paulo - SP

## Requisitos

**Obrigatórios:**

- Angular
- CSS
- Typescript
- Tempo de experiência: 2-4 anos

**Desejáveis:**

- Python
- Testes unitários web/E2E com Selenium/PhantomJS/Protractor
- Plataformas de CD/CI
- Kubernetes e Docker
- Google Cloud

**Diferenciais:**

- Contribuição em projetos opensource
- Figma
- Noções de boas práticas de UX/UI
- Experiencia trabalhando com equipes ágeis/Scrum

## Benefícios

- Remuneração acima da média do mercado
- Plano de saúde Notredame Premium (sem co-participação)
- VR de R$ 40/dia
- Plano odontológico
- Vale transporte

**Diferenciais:**

- Um dia mensal fora do escritório dedicado a estudos
- Orçamento anual individual para compra de livros técnicos e participação em eventos
- monte a sua máquina como desejar
- Frutas e guloseimas no escritório
- sala de jogos
- Ambiente descontraído e ágil

## Contratação

CLT.

## Como se candidatar

Preencher [este formulário](https://docs.google.com/forms/d/e/1FAIpQLSf0UtVEQMxif0L87AmpmLawPe4bddfLqZEYb7BDkNUEWgBJYQ/viewform).

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 4 dias após cada processo.
E-mail para contato em caso de não haver resposta: digesto@digesto.com.br

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by ricardocabral** [comment]
bom dia @felipefialho, estamos buscando novamente devs para esta vaga, poderia reabri-la?
