### ISSUE TITLE
[REMOTO] Front-end Developer na Agryo

### ISSUE THREAD

**Issue by agryo-company** [frontendbr/vagas#3477]
> Vaga Remota em JavaScript

## Nossa empresa

A Agryo é uma startup provedora de inteligência de risco para operações financeiras no agronegócio que auxilia empresas do setor que podem ajudar as 500 milhões de famílias de agricultores em todo o mundo acessem serviços financeiros pela primeira vez.

Se você deseja fazer parte de uma equipe global multicultural para resolver um dos maiores desafio de nossos tempos, você deve fazer parte da equipe agryo!

## Descrição da vaga

O papel da posição é participar do desenvolvimento e aprimoramento da interface web dos dashboards da Agryo e trabalhar com clientes da agryo para integrar os serviços em sua infraestrutura. Além de implementar melhorias constantes no website da Agryo e intregração de growth hack de marketing e gestão.  

Lembre que é uma startup, trabalho desafiador e para quem não tem medo de resolver problemas e sabe trabalhar em equipe. 

**Início na primeira semana de setembro de 2020.**

Quer saber mais sobre a Agryo?  Acesse - https://bit.ly/2Pb91q9

## Local

Exemplo: Remoto ,  [GLOBAL], [DISTRITO FEDERAL], [BRASILIA]

## Requisitos

**Obrigatórios:**
-  2+ anos de experiência em desenvolvimento de software
-  2+ de experiência em javascript 
-  Saiba construir com foco no SEO 
-  Conheça bem HTML, CSS, Git, React ou Vue ou Angular
-  Excelente experiência em Javascript e Node.js
-  Experiência com serviços web RESTful
-  Experiência com bancos de dados relacionais e gráficos
-  Escreva código bem projetado, testável e eficiente
-  Paixão e curiosidade por criar e construir coisas
-  Disponibilidade imediata para começar (em setembro de 2020)

**Desejáveis:**
-  Experimente em trabalhar remotamente
-  Familiar / envolvido com sistemas de informação geográfica (SIG)
-  Desenvolver microsserviços e aplicativos sem servidor
-  Experiência em trabalhar em um ambiente de integração e implantação contínua (CI / CD)

**Diferenciais:**
-  Independente, motivado
-  Fluente em inglês
-  Histórico comprovado de sempre aprendendo e crescendo
-  Atitude proativa

## Benefícios

- Potencial vesting após período de experiência

## Contratação

PJ a combinar

## Como se candidatar

Por favor preencha seu perfil neste - [link](https://www.linkedin.com/jobs/view/1989950987/)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: agryo@agryo.com

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
