### ISSUE TITLE
[REMOTO] FullStacks no BTG

### ISSUE THREAD

**Issue by MarianaPassos24** [frontendbr/vagas#3478]
TÍTULO: [REMOTO] FullStack @ BTG
Issue:
**Descrição:** O BTG Pactual é o maior banco de investimentos da América Latina, somos meritocráticos com uma equipe versátil. Valorizamos quem tem cabeça de dono, sonha grande e é apaixonado em aprender e ensinar. A posição tem como objetivo atuar em sistema de reconciliações financeiras de todas operações e em conjunto com as demais áreas do banco no desenvolvimento de integrações de novos produtos e mapeamento de fluxos financeiros
**Local:** FULL REMOTO
**Contratação:** CLT + Benefícios. 
Requisitos principais: C#, Java e Javascript; · Conhecimento em frameworks e linguagens de programação front-end, como : React, HTML5, CSS e Bootstrap; · Domínio em implementações de WebServices, Windows Services e APIsRestful; · Vivência de Trabalho com Métodos Ágeis (Scrum); · Domínio de banco de dados relacionais, Postgres preferencialmente; · Desejável: conhecimentos em AWS Cloud, arquitetura Micro-Services e Agile

Fazer o cadastro no seguinte Link: byintera.in/btgfsfegh

Dúvidas: linkedin.com/in/mariana-mota-passos-a993571a9

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
