### ISSUE TITLE
[São Paulo] Front-end Developer na Everis 

### ISSUE THREAD

**Issue by AmandaPrestes** [frontendbr/vagas#3479]
> Vaga Remota durante a pandemia

## Nossa empresa

A Everis é uma empresa multinacional de consultoria que desenvolve soluções de negócio, tecnologia da informação e outsourcing para os setores de bancos, seguros, telecomunicações, indústria e governo.

## Descrição da vaga

Posição de nível pleno para atuar como Front-end Developer com Angular2+

## Local

São Paulo (Remoto durante a pandemia)

## Requisitos

**Obrigatórios:**

- Desenvolvimento com as linguagens Angular Js, Angular 2+, HTML, CSS3, XML, JavaScript+jQuery;
- Experiência em banco de dados relacional (SQL) e diretrizes de acessibilidade;
- Experiência com integrações de API's REST e/ou SOAP e testes unitários e TDD.

## Benefícios

- Plano de saúde
- Seguro de vida
- Assistência Odontológica 
- Vale Refeição / Vale transporte 
- Auxílio creche
- Gympass 
- Outros benefícios... 

## Contratação

CLT

## Como se candidatar

Por favor envie um e-mail para amanda.prestes@integritygroup.com.br com seu CV anexado - enviar no assunto: Vaga Front-end - Everis

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
