### ISSUE TITLE
[Cariacica] Full Stack Developer na Green Belt Tecnologia

### ISSUE THREAD

**Issue by amandacei** [frontendbr/vagas#3480]
## A Green Belt Tecnologia é uma empresa terceirizada da Casa do Adubo no Espírito Santo. 

Exemplo: Aqui na Corporação ACME somos líderes em...

## Atuar como Developer em ferramentas desenvolvidas para a Casa do Adubo. 

Exemplo: Projeto bazinga em NodeJS, etc.

## Semi remoto e/ou Espírito Santo, Cariacica, Alto Lage 

Exemplo: Remoto ou Escritório, [ESTADO], [CIDADE], [BAIRRO]

## Requisitos

**Obrigatórios:**
- Experiência como Desenvolvedor(a)
- Banco de dados SQL
- Java
- C#
- APIs RESTful

**Desejáveis:**
- Graduação em Tecnologia da Informação ou áreas afins (concluída ou em andamento)
- JavaScript
- CSS
- Metodologias Ágeis
- Oracle Forms 11g
- Oracle PL/SQL

**Diferenciais:**

## Benefícios

**Diferenciais:**
Flexibilidade de horário 

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para amandacei.psi@gmail.com com seu CV anexado - enviar no assunto: Vaga Developer 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: amandacei.psi@gmail.com

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
