### ISSUE TITLE
[Remote] Front-end Engineer at CodeLathe Inc

### ISSUE THREAD

**Issue by Los** [frontendbr/vagas#3481]
## CodeLathe Inc
CodeLathe (an Austin, TX, USA based company), is looking for a passionate front-end software engineer to develop and expand our FileCloud product line. As a front end software engineer, you will be primarily responsible for the development of cross browser web application functionality. This is a 100% remote position and will require working remotely with other team members. We prefer candidates from Brazil, India, Poland or US.

#### Responsibilities
* Create elegant web user interfaces and layouts
* Own the user experience
* Integrate the front-end with databases, file systems, cloud services via HTTP APIs when delivering solutions
* Troubleshoot and fix reported customer issues, delivering software patches as needed
Required Qualifications
* Bachelor’s degree in Computer Science, or in related discipline with 4 or more years of professional software engineering experience
* 3+ years experience in front-end web app development is required
* Strong understanding of JavaScript, **Vue.js**, CSS and HTML is required
* Strong knowledge of Web Technologies including HTTP protocol, XML, JSON, REST is required
* Experience using Google Web Toolkit (GWT) and Java is a plus
* Experience using Electron is a plus
* Strong knowledge of client server architecture is required
* Knowledge of Bootstrap framework is a plus
* Self starter, highly motivated and works with little or no supervision
* Passionate in software development, takes ownership and pride in their job.
* Solid english communication skills

#### Benefits
* Competitive compensation based on experience in USD
* Fully remote position (no annoying tracking software needed)
* Annual meetups somewhere in the world
* Hardware program

To apply fill out:
https://forms.gle/teDHSFZ9GzpUttXj8

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by Los** [comment]
Vaga preenchida por um brasileiro! Obrigado!
