### ISSUE TITLE
[São Paulo] Full Stack Java na SysMap Solutions

### ISSUE THREAD

**Issue by 20201102** [frontendbr/vagas#3483]
## São Paulo

Exemplo: Remoto durante a pandemia, depois algumas vezes na semana (3x).

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Java e Angular
- 2 anos de experiência com Node, PostgreSQL, GCP e Bitbucket.

**Diferenciais:**
- Home Office

## Contratação
PJ - imediata

## Como se candidatar

Por favor envie um email para janaina.lima@sysmap.com.br. com seu CV anexado - enviar no assunto: Vaga Full Stack Java

#### Alocação
- Alocado
- Remoto

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
