### ISSUE TITLE
[Belo Horizonte] Analista React 

### ISSUE THREAD

**Issue by 20201102** [frontendbr/vagas#3484]
[Belo Horizonte]  Analista React - SysMap Solutions Consultoria de TI.
==================================================

> Vaga Remota durante a pandemia

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com React e React Native

**Desejáveis:**
- SQL
- Java e Spring Boot;
- Orientação a Objetos (SOLID);
- DDD (Drive Domain Design);
- TDD (Test Driven Development);

## Benefícios

- Assistência Médica
- Plano Odontológico
- Vale Refeição
- Vale Transporte

## Contratação
CLT - prazo indeterminado

## Como se candidatar

Por favor envie um email para janaina.lima@sysmap.com.br com seu CV anexado - enviar no assunto: Analista React

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
