### ISSUE TITLE
[Remoto] Front-end Developer na CyberGamer (até R$ 8.000,00)

### ISSUE THREAD

**Issue by wchagas** [frontendbr/vagas#3486]
## Atividades e Responsabilidades

- Realizar mentoria e/ou orientação de equipes para garantia da qualidade;
- Garantir a qualidade do código;
- Apoiar na definição das atividades (Planning);
- Setup de ambientes;
- Corrigir erros e defeitos.

## Requisitos

- Domínio em JavaScript;
- Conhecimentos avançados em ReactJS;
- Style-components;
- TypeScript;
- Gerenciamento de estado (ex: Reactn);
- Entendimento sobre Design System;
- Experiência com integrações de API's;
- Testes automatizados;
- Server renderer;
- Experiência com o processo de integração contínua (CI/CD);
- Versionamento de código utilizando GIT;
- Conhecimento comprovado na área (Github);
- Métodos Ágeis;

## Contratação

PJ 

## Como se candidatar

Por favor envie um email para willy@cybergamer.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Sênior

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

#### Salário
- até R$ 8.000,00

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
