### ISSUE TITLE
[Remoto] Front-end Developer na CyberGamer (até R$ 6.000,00)

### ISSUE THREAD

**Issue by wchagas** [frontendbr/vagas#3487]
## Atividades e Responsabilidades

- Desenvolvimento de integração com API's
- Criação de componentes visuais (Design System);
- Compartilhar conhecimento com os membros da equipe;
- Apoiar na definição das atividades (Planning);

## Requisitos

- Conhecimentos em JavaScript;
- Conhecimentos em ReactJS;
- Style-components;
- TypeScript;
- Gerenciamento de estado (ex: Reactn);
- Experiência com integrações de API's;
- Versionamento de código utilizando GIT;
- Server renderer
- Métodos Ágeis;

## Contratação

PJ 

## Como se candidatar

Por favor envie um email para willy@cybergamer.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Pleno

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

#### Salário
- até R$ 6.000,00

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
