### ISSUE TITLE
[São Paulo] Front-end Developer na Sorte Online

### ISSUE THREAD

**Issue by ValeriaSalmazo** [frontendbr/vagas#3488]
> Vaga Remota durante a pandemia e 90% após pandemia

## Nossa empresa

Grupo de sorteios lotéricos online busca por desenvolvedor front-end pleno para somar no time de tecnologia em modelo home office. 

## Descrição da vaga

Dos requisitos imprescindíveis, precisamos encontrar um front-end focado em react e React Native.

## Local
Remoto , SP, SP, Pinheiros

## Requisitos

**Obrigatórios:**
- Domínio de ferramentas HTML, CSS, Jquery e Typescript 
- Domínio de frameworks React e React Native
 - Uso de metodologia ágil kanban 
- Familiaridade com banco de dados principais Velocidade é o foco principal, perfil será muito hands-on, mãos no código completamente. 

## Benefícios

Plano Odontológico
Seguro Saúde | 80% empresa e coloborador 20%
Vale Refeição | 30,00 dia
Vale Alimentação de 250,00 mês, 
- ...

**Diferenciais:**

Auxílio de internet mensal de 100,00, computador da empresa, trabalho remoto (90%)

## Contratação
CLT

## Como se candidatar

Se você se identificou com a proposta, então se candidate no link abaixo, para podermos marcar um bate papo:

https://www.99hunters.com/job/11132O132702/via_hunting

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível

- Pleno
- Sênior

**Comment by mrangel-jr** [comment]
Há a possibilidade de ser 100% remoto ?

**Comment by ValeriaSalmazo** [comment]
Oi, eu não sou dona da vaga, atuou como hunter.
Esta parte presencial, será somente em eventos, as atividades do dia a dia, será 100% remota.
Atte,
Valeria SalmazoFone: 11 99128 4166 

    Em terça-feira, 25 de agosto de 2020 16:29:15 BRT, Marcos Rangel Junior <notifications@github.com> escreveu:  
 
 


Há a possibilidade de ser 100% remoto ?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
