### ISSUE TITLE
[SP, BH, Floripa ou Itajubá/MG] Software Developer na Trybe

### ISSUE THREAD

**Issue by eminetto** [frontendbr/vagas#3489]
> Vaga Remota durante a pandemia

## Nossa empresa

A Trybe é uma escola de desenvolvimento de software, feita para pessoas dedicadas e estudiosas que querem construir uma carreira em tecnologia. Quem estuda na Trybe pode escolher pagar só depois de conseguir um bom trabalho.

A cultura da Trybe tem como principal característica o foco em gente. Temos obsessão por atrair, desenvolver e gerar oportunidades para pessoas excepcionais. Construímos relações fortes baseadas em confiança, transparência, autonomia, colaboração, propósito, foco no longo prazo.

Nos empenhamos em construir uma equipe diversa e forte, e contratamos dando oportunidades iguais, independente de gênero, orientação sexual, raça, religião, formação. Acreditamos que ter experiências, perspectivas e trajetórias de vida diferentes enriquecem nosso ambiente, contribuem para evoluir nossa visão de mundo e nos ajuda a construir produtos e experiências que entreguem real valor para a sociedade.

Buscamos criar um espaço justo, seguro e agradável para todo o time e incentivamos um ambiente aberto e questionador e respeitoso, onde todos têm a oportunidade de se manifestar e participar, crescer e compartilhar idéias.

## Descrição da vaga

Estamos buscando pessoas desenvolvedoras de software para construir funcionalidades, criar interfaces web funcionais, desenhar e implementar APIs e melhorar e performance e confiança de nossos sistemas à medida que crescemos nosso produto e organização.

Nós construimos nossos produtos utilizando tecnologias que o time conhece e confia, como Elixir, React, NodeJS e PostgreSQL. Experiência com essas tecnologias são um diferencial, mas ter experiência com outras linguagens usadas no desenvolvimento web (como Ruby, Python, Go) e outros bancos de dados relacionais são bons substitutos. Nós somos um time colaborativo que gosta de trabalhar em squads com product managers e designers para construir um produto de educação incrível com a Trybe. Buscamos pessoas que entendem que simplicidade e confiança são aspectos importantes na construção de qualquer sistema.

## Local

SP, BH, Floripa ou Itajubá/MG - durante a pandemia estamos trabalhando full-remote e em caso de mudança, ela pode acontecer após a reabertura dos escritórios.

## Benefícios

- Vale Alimentação ou Refeição
- Plano de Saúde e Odontológico
- Vale Transporte
- Seguro de Vida

## Contratação

Contratação CLT
Dedicação: integral

## Como se candidatar

Por favor preencha seus dados no [formulário](https://bit.ly/trybe-softdev)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: elton.minetto@betrybe.com

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by wagnerrodrigo** [comment]
me candidatei à vaga para Júnior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
