### ISSUE TITLE
[ Campinas - SP ] - Front-End Pleno (Vue JS) 

### ISSUE THREAD

**Issue by tiagovilasboas** [frontendbr/vagas#349]
## Descrição da vaga
Experiência comprovada em: AngularJS ou Vue.Js, JavaScript (ES5 ou ES6), HTML5, CSS, Sass, Git e Bootstrap

## Local
Swiss Park Office, Campinas - SP

## Benefícios
- Assistência médica
- Auxílio creche
- Participação nos lucros
- Vale-refeição
- Vale-transporte

## Requisitos
**Obrigatórios:**
- 2 anos de experiência com JavaScript
- 1 ano de experiência com Angular JS ou Vue.Js
- Conhecimento em Design Patterns

**Desejáveis:**
- conhecimentos em PHP
- conhecimentos em JIRA
- conhecimentos em Scrum

**Diferenciais:**
- conhecimentos em PostgreSQL, SQL Server
- inglês (Intermediário)

## Contratação
CLT a combinar

## Nossa empresa
A Phone2Business  apresenta um portfólio de serviços e produtos que convergem as plataformas de telefonia e internet, oferecendo soluções e projetos que atendem aos mais diversos perfis de clientes.

## Como se candidatar
Por favor envie um email para bruno.guimaraes@phone2b.com.br com seu CV anexado - enviar no assunto: Vaga Front-End (Vue JS)

**Comment by mtmr0x** [comment]
@tiagovilasboas ainda esta aberta essa vaga?

**Comment by tiagovilasboas** [comment]
sim meu caro!
