### ISSUE TITLE
[Sorocaba] Front-end Developer na QPro Innovations

### ISSUE THREAD

**Issue by paulomach** [frontendbr/vagas#3491]
> Vaga Remota durante a pandemia

## Sobre a QPro Innovations

Somos uma empresa de Pesquisa e Desenvolvimento que atua em projetos de inovadores para as mais diversas indústrias. Atuamos com um time de engenharia enxuto que agrega conhecimento em tecnologias como manufatura aditiva, RFID, IoT, automação e robótica.

## Descrição da vaga

Desenvolvedor(a) frontend para atuação em projetos de inovação.

## Local

Remoto na pandemia. Escritório em Sorocaba/SP

## Requisitos

**Obrigatórios:**
- 2+ anos de experiência como frontend
- Fluência em javascript, html5, css3
- Forte experiência com React e outras libs baseadas em componentes
- NodeJS
- Alguma noção em UX/UI e design responsivo
- Web services REST (plus para grahql)
- Experiência com scrum
- Domínio git e feature branching model com peer review

**Diferenciais:**
- TDD
- Deno
- Bundling (GULP)
- Clean code

## Benefícios

- Contratação PJ vantajosa em relação ao mercado
- Almoço garantido
- Escritório moderno e confortável
- Flexibilidade de horário e modo de trabalho
- Orçamento para aprimoramento
- Garantia de projetos desafiadores e interessantes

## Contratação

PJ a combinar

## Como se candidatar

Aplicar via formulário (praticamente só upload de cv...) no [link](https://forms.clickup.com/f/2vzut-2915/OA04RFSI5G770HKHT8)

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Júnior

#### Local
- Sorocaba

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
