### ISSUE TITLE
[REMOTO] Pessoa Engenheira de Software Senior na Kenoby

### ISSUE THREAD

**Issue by amandagasineo** [frontendbr/vagas#3493]
A Kenoby, empresa que vem revolucionando o mercado de recrutamento, foi escolhida pela Endeavor como uma das melhores 16 scale up SAAS! Atualmente, a empresa recebeu um investimento de 20 milhões do fundo Astela e é uma das startups que mais vem crescendo no Brasil.

Estamos te esperando. Topa o desafio? 🙂 
https://byintera.in/z9	

## Local

Remoto

## Requisitos

Não estamos em busca de nenhuma stack especifica, buscamos pessoas com propósito, proatividade, mão na massa e dispostas a aprender e crescer exponencialmente. Serão bem vindos conhecimentos em Javascript, AWS, testes automatizados, integração contínua...

## Benefícios

- 30 dias de licença remunerada. 
- Licença maternidade/paternidade.
- Clube de descontos

## Contratação

PJ

## Como se candidatar

https://byintera.in/z9

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista
- Líder

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
