### ISSUE TITLE
[Remoto] Desenvolvedora Fullstack na Pling

### ISSUE THREAD

**Issue by felipekm** [frontendbr/vagas#3494]
![image](https://user-images.githubusercontent.com/205932/91355765-06fc6800-e7c5-11ea-89c0-aaf53fbce620.png)

A [PLING](https://pling.net.br/) é uma startup do hub [4all](https://4all.com/) focada em desenvolver produtos digitais e em renovar e/ou desenvolver identidades visuais agregando últimas tendências de tecnologia e design.

## 📝  Descrição da vaga

**Contamos com duas vagas para Desenvolvedoras Fullstack**, estamos priorizando 👩  **MULHERES** para essas contratações, com atuação em diversos projetos que utilizam diversas tecnologias, tais como:

## Requisitos

**Necessários:**

- Experiência em HTML, CSS e JavaScript;
- Mínimo de 3 anos de experiência com desenvolvimento de softwares;
- Experiência com Frameworks JS (ReactJS, AngularJS);

**Desejáveis e não necessários:**

- Conhecimento de REST APIs;
- Conhecimento em Linux/MacOSX;

## Contratação

- PJ;

#### Mercados da saúde em que a PLING atua no momento:

* [Psicologia](https://psicologia.pling.net.br)
* [Medicina](https://medicina.pling.net.br)
* [Nutrição](https://nutricao.pling.net.br)
* [Odontologia](https://odontologia.pling.net.br)

Todas essas aplicações acima foram desenvolvidas com ReactJS/NextJS, NodeJS, Go, entre outras!
Venha se divertir conosco! 😆 

## Como se candidatar

**Envie um email para**: recrutamento@pling.net.br com seu CV anexado.
**Enviar no assunto**: Vaga para Desenvolvedora

Tempo de resposta: `48h`

## Labels

- PJ
- Home office full
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by felipekm** [comment]
A vaga foi fechada, obrigado @felipefialho
