### ISSUE TITLE
[CURITIBA] Front-end Developer na aftersale

### ISSUE THREAD

**Issue by laissend4** [frontendbr/vagas#3495]
A **aftersale é uma suíte de soluções e tecnologia para o e-commerce**, somos a mais nova integrante da Holding T.group, do qual fazem parte Compre&Confie, Lomadee e a gigante ClearSale (Great Place to Work).

Já passamos por uma aceleração no Vale do Silício, e estamos iniciando nossa expansão para a América Latina. Somos cheios de energia, motivados a gerar impacto na vida de nossos usuários e apaixonados por transformar a experiência de consumo do Brasil e da América Latina.

**Sobre a vaga de Desenvolvedor Front End:**

Esta vaga é totalmente hands-on, tudo que você fizer afetará diretamente nos resultados da empresa, estamos a cada dia criando e melhorando nossos produtos e a sua participação neste processo será intensa e indispensável.

Para fazer parte do nosso time é importante ser um profissional proativo, resiliente, que se importe em garantir o resultado dos nossos clientes, que tenha bom relacionamento interpessoal, que tenha capacidade de resolver problemas e que seja responsável e comprometido com nossas metas e nossos valores.

Aqui, nós gostamos muito de correr atrás das metas de crescimento da empresa, por isso se você se motiva por desafios, está no lugar certo!

**Suas principais responsabilidades serão:**

Desenvolvimento Front End para aplicações responsivas;
Pesquisar e se atualizar sobre como e quais tecnologias podem ajudar na transformação do mercado de logística;
Ter opiniões sobre o business e colaborar de forma construtiva para o sucesso de uma empresa emergente;
Ter proatividade para criar propor novas soluções, não ficar só sentado esperando acontecer!

**O básico para esta vaga:**

Experiência com consumo e criação de web services ou APIs;
HTML5, Bootstrap;
GIT;
Experiência e conhecimento em ES6;
Conhecimentos sólidos em React.

**O que a gente adoraria ver (vale pontos extras!!!):**

CSS3 / Sass / Less;
Experiência em plataformas de e-commerce (Magento, WooCommerce);
Wordpress;
Conhecimentos em SCRUM
Ter o foco na solução e não no problema;
Haver trabalhado em startup/empresa .com
Ter sede por produtividade e aprendizado.
Experiências diferenciadas como voluntariado, ongs, aiesec, empresas juniores, projetos próprios/empreendimentos.

**Não se candidate se você não for ou tiver:**

Papo reto: Valoriza a objetividade. Falamos o que precisa ser falado.
Casca grossa: Resiliente e motivado por desafios.
Sempre inconformado: Não se contenta com a média.
Focamos na solução: Coloque o peixe podre na mesa para resolver.
Todos donos: construímos a nossa empresa ideal todos os dias.
Positividade e Simplicidade: Atitude e energia sem complicações.

**Porque você deveria se candidatar e nos conhecer?**

Nosso foco é na qualidade de entrega não na sua formação ou título;
Horário flexível, autonomia, home-office e trabalho remoto;
Metodologia de desenvolvimento Ágil com fluxo e cerimônias maduras;
Ambiente informal, diverso e aberto para todos;
Gestão com alto conhecimento estratégico e reconhecimento de mercado;
Time organizado em SQUADS com gestão por resultados e cultura de feedback;
Mentorias constantes com referências e incentivo para eventos e formações;
Nossos Pilares: Service Design, Data e Customer Experience;
Contratação CLT ou PJ

Se identificou? Bora revolucionar o e-commerce com a gente!

Ps: temos mais de uma vaga, indica pros amigos também!

VAGA FECHADA!

**Comment by vinicius-assis** [comment]
Aceita junior?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by GabrielOliveira321** [comment]
[CV Gabriel - Google - 10112022 (2) (4).pdf](https://github.com/frontendbr/vagas/files/12653200/CV.Gabriel.-.Google.-.10112022.2.4.pdf)
