### ISSUE TITLE
[Araçatuba][Remoto][Junior][ReactJS] Front-End Developer no Grupo Acert

### ISSUE THREAD

**Issue by MendesFilipe** [frontendbr/vagas#3496]
## Descrição da vaga

*Requisitos necessários:*
- JavaScript / ES6
- ReactJS / Redux 
- Webpack
- CSS
- APIs REST

**Hábito com as metodologias ágeis
Inglês técnico
Desejo de aprender**

*Será um diferencial já conhecer:* 
- Typescript
- Ferramentas de teste: Jest, Enzyme, React-Testing-Library, Cypress
- react-final-form
- Material UI

## Contratação

PJ a combinar

## Como se candidatar

Envie seu CV para o e-mail: trabalhe.conosco@grupoacert.com.br com o assunto FRONT-END

## Labels

- PJ
- Remoto

**Comment by krivax** [comment]
full time? ou pode trabalhar em horário flexível?

**Comment by MendesFilipe** [comment]
> full time? ou pode trabalhar em horário flexível?

Horário flexível sendo necessário participar de reuniões diárias de 15 min e outras eventuais

**Comment by krivax** [comment]
então ok @MendesFilipe vou me candidatar.

**Comment by Cristianojr9** [comment]
CVEnviado

**Comment by rodgo4k** [comment]
CV enviado, sabe dizer em quanto tempo recebo um feedback?
