### ISSUE TITLE
[SÃO PAULO] Especialista no BTG

### ISSUE THREAD

**Issue by MarianaPassos24** [frontendbr/vagas#3497]
**Descrição:** O BTG Pactual é o maior banco de investimentos da América Latina, somos meritocráticos com uma equipe versátil. Valorizamos quem tem cabeça de dono, sonha grande e é apaixonado em aprender e ensinar. A posição tem como objetivo atuar em sistema de reconciliações financeiras de todas operações e em conjunto com as demais áreas do banco no desenvolvimento de integrações de novos produtos e mapeamento de fluxos financeiros
**Local:** São Paulo
**Contratação:** CLT + Benefícios. 
Requisitos principais.Net Core, Elixir C#, Typescript, Dart (Flutter), Docker, Kubernetes, AWS · Trabalhar com arquitetura orientada a microsserviços e modelos de integração contínua; · 
Formação superior completa em engenharia, ciências da computação ou áreas relacionadas; · 
· Inglês avançado.
Fazer o cadastro no seguinte Link: byintera.in/btgespfegh
Dúvidas: linkedin.com/in/mariana-mota-passos-a993571a9

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
