### ISSUE TITLE
[São Paulo] Front-end Developer na ITeam

### ISSUE THREAD

**Issue by VivianeRHTI** [frontendbr/vagas#3498]
## Descrição da vaga

Desenvolvimento de projetos Front-end.

## Local

Disponibilidade para atuar presencialmente em São Paulo/SP (Santo Amaro), porém devido a pandemia inicialmente será remoto.

## Requisitos

Experiência com desenvolvimento Front End
Conhecimentos em HTML, CSS utilizando frameworks/bibliotecas BootStrap e jQuery.
Conhecimento em SEO e Web Analytics aceitáveis.
Estruturar e modelar componentes no CMS.
Integrações de APIs utilizando boas práticas de mercado.
Metodologia Scrum.

## Contratação

Contrato de 4 meses
Regime: CLT + benefícios 

## Necessário
Possuir disponibilidade para projeto temporário.

## Nossa empresa

Há mais de 15 anos presente no mercado, a ITeam oferece o comprometimento com o cliente.
Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 
O relacionamento da ITeam é baseado no amplo comprometimento com os valores e objetivos dos nossos Clientes, fornecendo soluções e serviços de TI que contribuam para a realização de seus objetivos.

## Como se candidatar

Envie um e-mail para viviane.pereira@iteam.inf.br com seu currículo atualizado e pretensão salarial CLT - enviar no assunto: Vaga Front-end CLT

## Labels

- 🏢 Horário comercial
- 🏢 Presencial - Porém inicialmente Remoto.
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ CLT

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
