### ISSUE TITLE
[São Paulo] Front-End Developer OpenCart na Printástico

### ISSUE THREAD

**Issue by rafaelaugustoferreira** [frontendbr/vagas#3499]
## Printástico
A Printástico é uma empresa brasileira especializada em FotoProdutos e impressões digitais, que segue os mais altos padrões internacionais de tecnologia e qualidade. Nossa missão é oferecer aos nossos clientes um ambiente seguro e aplicações que garantam a criação de projetos personalizados de maneira rápida, fácil e divertida.
## Descrição da vaga
Procuramos um dev para atuar na customização de um template Opencart comprado, além de comunicações com o API’s. O layout das telas é enviado nos formatos: PSD, JPEG e DOC (com a documentação das alterações), onde o resultado final deve ser 100% igual ao layout enviado.
Portanto, será necessário sólido conhecimento e experiência em HTML/CSS/Javascript, precisão na adaptação dos layouts para HTML, experiência em customização do OpenCart e comunicação com API’s, conhecimento básico em Docker e GIT. Conhecimento básico em Photoshop, será um diferencial e um facilitador nas tarefas.
## Local
Remoto
## Requisitos
**Obrigatórios:**
- Experiência plena com Front-end
- Experiência plena com OpenCart
- Experiência básica com Docker
- Experiência básica com GIT

**Desejáveis:**
- Conhecimentos básicos em Photoshop
## Contratação
PJ - Remuneração a combinar, se preferir nos envie sua pretensão junto com o CV.
## Como se candidatar
Por favor envie um email para rf@printastico.com.br com seu CV anexado - enviar no assunto: Vaga Front-end OpenCart
#### Alocação
- Remoto
#### Regime
- PJ
#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
