### ISSUE TITLE
[Rio de Janeiro] Estágio Desenvolvedor Front-end

### ISSUE THREAD

**Issue by rdourado** [frontendbr/vagas#35]
## Descrição da vaga

Estamos a procura de um estagiário para auxiliar no desenvolvimento e manutenção de sites, sistemas web e aplicativos mobile. Precisamos de alguém interessado em trabalhar com técnicas mais modernas e disposição para implementar novos conhecimentos de imediato. Além disso, uma boa noção estética e atenção para detalhes também são essenciais.

## Local

Espaço de _coworking_ localizado na Rua São Clemente, em __Botafogo__.

## Benefícios

- Bolsa auxílio
- Transporte
- Horário flexível

## Habilidades/Conhecimentos

**Obrigatórios:**
- Plena familiaridade com as linguagens básicas de front-end (HTML5/CSS3/JS)
- Conhecimentos básicos de design (não apenas web)

**Desejáveis (podem ser estudados no próprio estágio):**
- Pré-compiladores: SASS, Jade e CoffeeScript *
- Grunt *
- Git *

**Diferenciais (podem ser estudados no próprio estágio):**
- AngularJS
- Xcode.

## Atividades e responsabilidades

- Auxiliar no desenvolvimento de interfaces, tanto no planejamento quanto na codificação.
- Participar de decisões sobre aprimoramento de metodologia de trabalho.
- Desenhar e implementar elementos complementares de interface.
- Cumprir prazos, manter controle de atividades e documentar código.

## Qualidades pessoais

- Demonstrar disposição e agilidade para o aprendizado.
- Manter-se informado e atento a melhorias na execução de cada tarefa.
- Respeitar os demais profissionais da empresa e do ambiente (estamos em um espaço de _coworking_).
- Ter capacidade de resolver problemas comuns de código e de interface.

## Nossa empresa

[parafernalia.net.br](http://parafernalia.net.br)

## Como se candidatar

Por favor envie um email para contato@parafernalia.net.br com seu CV e uma apresentação pessoal. Enviar no assunto: Vaga Estágio

**Comment by LFeh** [comment]
Boa sorte @rdourado ;)

**Comment by LFeh** [comment]
A vaga foi preenchida?  @rdourado

**Comment by camilatigre** [comment]
@rdourado 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
