### ISSUE TITLE
[REMOTO] Full Stack Jr. na DataKompass

### ISSUE THREAD

**Issue by amandagasineo** [frontendbr/vagas#3500]
Seguindo a filosofia Data-Driven Decisions, a Datakompass é uma G-Tech, empresa que une gestão e tecnologia, com o proposito de entregar plataformas de inteligência de dados para tomada de decisão da alta liderança dos seus clientes!

Atualmente, estamos iniciando o processo de internalização da equipe de desenvolvimento e buscamos um Full Stack com o desafio de desenvolver novos produtos e fazer correções e melhorias nos produtos já existentes. Uma posição de extrema relevância para desenvolvimento da empresa e na relação direta com os sócios e clientes.

Estamos te esperando. Topa o desafio? 🙂 
https://byintera.in/zh	

## Local

Remoto

## Requisitos

Buscamos pessoas com propósito, curiosidade, proatividade, compromisso, dispostas a aprender e crescer exponencialmente, e que tenham conhecimento em Python, Javascript e React. Serão bem vindos também conhecimentos em Django, GraphQL, Pandas, Docker, Linux, Typescript e Styled Components.

## Contratação

PJ

## Como se candidatar

https://byintera.in/zh

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior

**Comment by grsantos2215** [comment]
Aceita CLT ?

**Comment by amandagasineo** [comment]
> Aceita CLT ?

Somente PJ!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
