### ISSUE TITLE
[Belo Horizonte/MG | Remoto] Front-end Vue.js Developer @ Onegreen

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#3501]
## Nossa empresa

O Onegreen é um software especializado para a gestão de todo o Processo de Licenciamento Ambiental.

O desenvolvimento do Onegreen iniciou em 2009 com a ajuda de grandes mineradoras, e desde então vem sendo atualizado com novas funcionalidades e já é utilizado por empresas dos mais diversos segmentos e portes.

## Habilidades

- Vue.js
- Javascript
- Git
- HTML5
- CSS3

## Descrição da vaga

A OneGreen está buscando uma Pessoa Desenvolvedora Front-end com experiência em Vue.js, para fazer parte do seu time. Vagas para júnior ou pleno.

Estamos em busca de um profissional com grande capacidade e liberdade criativa, que possua independência para trabalhar em conjunto com equipe de desenvolvimento e planejamento.

Se você possui essas características, venha fazer parte do nosso time!

## Local

- Remoto 
- Belo Horizonte-MG

## Requisitos

- 2+ anos de experiência em posição similar ou atuando como freelancer
- Ser habituado com metodologias ágeis (Scrum)
- Capacidade criativa e independência para atuar em equipe
- Necessário experiência com HTML5, CSS3, Bootstrap, JavaScript, jQuery, Visual Studio e controle de versão (GIT)
- Noção de usabilidade UI/UX.
- Fluente em Javascript
- Experiência em front-end usando Vue.js

**Desejáveis:**
- Conhecimentos em Vuex

**Diferenciais:**

- Conhecimentos em TypeScript
- Conhecimentos em Nuxt.js ou Quasar
- Inglês intermediário

## Benefícios

- Possibilidade de contrato PJ
- Vale Alimentação ou Refeição
- PLR

## Contratação

CLT ou PJ

**Aqui usamos:**
- Vue.js
- C#
- SQL Server

## Como se candidatar

Candidatar-se em: [https://bit.ly/3lpuRF5](https://bit.ly/3lpuRF5)

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Júnior
- Pleno

**Comment by rayanmarcus** [comment]
Tentei por mais de 5 vezes enviar o currículo através do link informado, mas todas as vezes deu erro: "Ocorreu um erro ao tentar enviar o formulário
Network Error"
