### ISSUE TITLE
[São Paulo] Dev Front-end Pleno na Hubblefy

### ISSUE THREAD

**Issue by enriquesaid** [frontendbr/vagas#3504]
## Nossa empresa
Hubblefy é uma startup em crescimento, com uma equipe enxuta, residente do Inovabra Habitat. Somos um aplicativo para equipes que precisam se comunicar, organizar e controlar informações compartilhadas com alta eficiência.

## Descrição da vaga
Estamos em busca de Devs Front-End Pleno para seguir com a gente na construção de um negócio de alto-impacto no mercado.

Você gosta de programar e solucionar problemas, propondo soluções criativas e disruptivas. Tem curiosidade por novas tecnologias e principalmente sobre desenvolvimento multi-plataforma.

Nenhum dia é igual ao outro e nada é pra sempre, mas no nosso dia a dia você trabalhará com:
- Metodologia ágil (Sprint/Planning, Daily Meetings, 1x1, Reviews)
- Gitflow
- TDD
- Code Review
- Microservices

Atuando com liberdade, focado em resultados e sendo você mesmo.

## Local
Remoto e/ou no InovaBra Habitat (Metrô Paulista, São Paulo, SP)

## Atividades 🏋️‍♀️ 
- Apoiar no desenvolvimento do nosso aplicativo (web/mobile) 👩‍💻
- Trabalhar em conjunto (pair-programming) com outros membros do time 👨‍💻👨‍💻
- Participar em entregas e organização de sprints 🙋‍♀️
- Identificar oportunidades de melhorias no produto 🕵️‍♀️
- Auxiliar os times não-tech 👩‍🚀

## Algumas tecnologias que você terá contato:
- Serviços Google Cloud ☁
- Dart e Flutter 🎯
- Firebase 🔥
- Angular 📕

## Requisitos
- Saber trabalhar em equipe
- Participar ativamente das reuniões de sprint
- Organização e qualidade de código
- Português: boa comunicação verbal e escrita
- Inglês: intermediário para leitura
- Capacidade de autogestão
- Ter visão e empatia com as experiências de Clientes

### Conhecimento pleno nas tecnologias:
- HTML/CSS 
- Javascript
- Familiaridade com APIs
- NodeJS
- Javascript Frameworks

## Benefícios
- Cartão Vale Saúde
- Telemedicina Einstein
- Full Time Job com horário flexível
- Suporte em Eventos Tech
- Cursos e treinamentos

## Contratação
PJ

## Como se candidatar
Por favor envie um e-mail para enrique@hubblefy.com com seu CV anexado - Enviar com assunto: Vaga Dev Front-end Pleno

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: enrique@hubblefy.com

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
