### ISSUE TITLE
[São Paulo] Front-end Developer na Lumis

### ISSUE THREAD

**Issue by LumisTecnologia** [frontendbr/vagas#3505]
> Vaga Remota durante a pandemia

Geração de interfaces para projetos de portais, hotsites, apps e criação/evolução dos produtos internos da empresa.

**Local**
São Paulo - Vila Olímpia

**Necessário**
- Superior completo em Ciência de Computação, Engenharia de Computação, Informática ou correlatos;
- Conhecimento em HTML, CSS, JS;
- Experiencia em conversão de layouts (Figma, PSD), criação de telas estáticas, criação de portais institucionais, CMS;
- Conhecimento de JavaScript puro;
- Conhecimento de pré-processadores css (LESS, Sass);
- Conhecimento de ferramentas de compilação de pacotes (gulp, webpack, etc.)
- Conhecimento de jQuery

**Desejável**
- Criação de telas dinâmicas e integração com APIs;
- Experiência com Lumis.
 

 **Benefícios**
- Plano de saúde
- Plano Odontológico
- VR - R$ 26,10/dia
- VA - R$ 212,59/mês
- Vale Transporte

**Como se candidatar**
Por favor, envie um e-mail para rh@lumis.com.br com seu CV anexado - enviar no assunto: Front End SP

**Regime**
- CLT

**Nível**
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
