### ISSUE TITLE
[Remoto] Fullstack na Anestech

### ISSUE THREAD

**Issue by raivitor** [frontendbr/vagas#3506]
## Nossa empresa

Na Anestech desenvolvemos soluções para anestesistas. Criando softwares que melhoram o seu desempenho na hora de realizar os procedimentos, dando mais qualidade e diminuindo as chances de erros.

## Descrição da vaga

Tá de saco cheio de ficar só fazendo CRUD? Quer dar um sentido diferente às suas linhas de código, ter a chance de salvar vidas em risco e acordar para um desafio diferente fazendo parte de um time foda?

Nosso produto principal é o AxReg, aplicativo que possibilita a digitalização e libertação dos dados contidos no registro anestésico, feito pelo profissional anestesiologista. O AxReg traz consigo diversas soluções de integração, análise e gerenciamento de dados. Nossa stack é Node.js, Mysql e React. Para deixar tudo de pé, mantemos desde a VPN interna até os bancos de dados utilizando diversos serviços da AWS.

## Local

Remoto ou Escritório, Florianópolis/SC

## Requisitos

**Obrigatórios:**
- NodeJs
- React
- Mysql

**Desejáveis:**
- Docker
- AWS (EC2, S3, ECS, RDS, Lambda...)

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para talentos@anestech.com.br com seu CV anexado - enviar no assunto: Vaga Fullstack

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefln** [comment]
@raivitor só uma dica, deem retorno e/ou feedback do teste técnico. Me dediquei em torno de 5 dias full-time para entregar o teste técnico, e sinceramente é bem ruim não ter retorno. Obrigado

**Comment by raivitor** [comment]
@felipefln Peço desculpas pelo ocorrido, vou falar agora com a RH para saber o que houve. Tbm detesto fazer teste técnico e não receber nenhum retorno.

**Comment by felipefln** [comment]
@raivitor Boa, parabéns pela atitude. Acredito muito que retorno e feedback nos testes técnico, faz com que o Dev melhore ou pelo menos perceba onde deve melhorar. Obrigado e sucesso.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by raivitor** [comment]
Ainda está aberta :)
