### ISSUE TITLE
[São Paulo] Front-end Developer na Atados (React.js, Next.js)

### ISSUE THREAD

**Issue by vinpac** [frontendbr/vagas#3508]
## Nossa empresa

Somos uma organização que mobiliza pessoas e empresas para o engajamento social. Hoje nosso maior projeto é nossa plataforma de voluntariado que conecta pessoas com projetos sociais. Além disso, oferecemos consultoria de responsabilidade social para empresas.

Atualmente estamos trabalhando em combate as consequências do COVID-19 com projetos de doação, voluntariado remoto ou presencial para emergências, doação de máscaras, cestas básicas e vários outros projetos que você pode encontrar no nosso site (atados.com.br). Algumas empresas que já trabalhamos: Samsung, Boticário, Coca-Cola, Carrefour, Via Varejo, Shell.

## Descrição da vaga

Nosso projeto é nossa plataforma de voluntariado (atados.com.br) que funciona em modelo SaaS. Hoje nós temos 10 clientes que utilizam nossa plataforma (empresas ou movimentos) para conectar ainda mais pessoas com projetos sociais.

Periodicamente trabalhamos em projetos paralelos, como a nossa última plataforma chamada **Conectados Pelo Futuro** para a Samsung. O back-end foi feito com Hasura e Node.js. O front-end com Next.js, React e Typescript.

https://www1.folha.uol.com.br/empreendedorsocial/2020/06/samsung-lanca-voluntariado-online-para-orientar-jovens-sobre-o-mercado-de-trabalho.shtml

Segue listado todas as tecnologias que usamos no front-end: React.js, Next.js, TailwindCSS, apollo, Styled Components.

## Local

Você tem total liberdade para trabalhar remoto (mesmo após a pandemia) ou trabalhar em uma de nossas casas em São Paulo (2 min a pé do Metrô Fradique Coutinho, em Pinheiros) ou Rio de Janeiro (a 4 min a pé do metrô Saens Peña, no bairro da Tijuca). Atualmente estamos trabalhando remotamente devido ao isolamento social.

## Requisitos

**Obrigatórios:**
- Boa experiência com React.js
- Experiência aplicando transformando designs em código

**Desejáveis:**
- Boa experiência com hooks

**Diferenciais:**
- Projetos open source
- Conhecimentos de TailwindCSS
- Já ter feito voluntariado

## Contratação

PJ 

## Como se candidatar

Envie um email para pacheco@atados.com.br com seu CV ou link do Github, site ou qualquer projeto que demonstre seu trabalho - enviar no assunto: Vaga Front-end - <seu nome>

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by vmesel** [comment]
@vinpac podemos fechar a vaga aqui para trabalharmos via FrontJobs igual tinhamos combinado?
