### ISSUE TITLE
[São Paulo] Front-end Developer na GFT

### ISSUE THREAD

**Issue by GabrielaGFT** [frontendbr/vagas#3509]
50% remoto e 50% presencial
## Nossa empresa

Já conhece nossa empresa? A GFT é uma Multinacional Alemã presente em 15 países, somos especialistas no mercado Financeiro. Estamos entre as melhores empresas para se trabalhar, com mais de 5 mil profissionais pelo mundo!

## Local

SP/São Paulo, Interlagos.

## Requisitos

**Obrigatórios:**
- Sólida experiência em Angular

## Benefícios

• Convênio Médico;
• Convênio Odontológico;
• Vale Refeição;
• Cartão Multibenefícios;
• Fretado / Vale Transporte
• Plano de Previdência Privada;
• Seguro de Vida em grupo;
• Auxilio creche;
• Gympass;
• Bolsa de estudos;
• Graduação e Pós-graduação;
• MBA;
• Cursos de idiomas;
• Treinamentos externos;
• Certificações.

## Contratação

CLT Full

## Como se candidatar

Por favor envie um email para gabriela.fernandes@gft.com. com seu CV anexado - enviar no assunto: Front-end Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
