### ISSUE TITLE
[São Paulo - SP] Desenvolvedor(a) Front-end | Horizon Four

### ISSUE THREAD

**Issue by Halfeld** [frontendbr/vagas#351]
## Descrição da vaga

Nós procuramos um desenvolvedor(a) front-end (junior/pleno) que terá como responsabilidade principal criar/manter  dashboards e aplicações complexas. Venha fazer parte do time H4!

## Local

Escritório, São Paulo - Paulista/Sé

## Benefícios

- Ecossistema de startups
- Aprendizado constante
- VIP para hackathons (CEO com mais de 16 mil conexões no linkedin :P)

## Requisitos

**Obrigatórios**

- HTML, CSS, JavaScript;
- Sass, LESS ou algum pré processador;
- Noções de UX;
- Angular.js 2.x + ou Vue.js;
- Proatividade.

**Desejáveis:**

- WebFlow.
- Prototipagem (Invision, Marvel ou similares).
- Projetos Open Source :D

## Contratação

PJ a combinar

## Nossa empresa

A H4 é uma software house com uma pegada de startup, uma empresa bastante ligada a comunidade e hackathons :P
Aqui é aprendizado sempre e estamos em constante evolução!

## Como se candidatar

Interessados, enviem o CV para o e-mail: [erick.wendel@horizonfour.com.br](erick.wendel@horizonfour.com.br)

**Comment by anony000** [comment]
Contratam remoto?

**Comment by Halfeld** [comment]
Infelizmente ainda não @anony000

**Comment by WandersonAlves** [comment]
A entrevista pode ser remota?

**Comment by Halfeld** [comment]
Pode sim @WandersonAlves!

**Comment by mtmr0x** [comment]
@Halfeld ainda esta aberta essa vaga?

**Comment by Halfeld** [comment]
Ainda está sim @mtmr0x

**Comment by pereirajunior1407** [comment]
A vaga ainda está aberta?

**Comment by Halfeld** [comment]
Sim @pereirajunior1407 !

**Comment by X-X-Xavito** [comment]
A vaga ainda está aberta?

**Comment by Halfeld** [comment]
Esta sim @X-X-Xavito!

**Comment by X-X-Xavito** [comment]
Enviado.
