### ISSUE TITLE
[Campinas - SP] Professional Services Engineer na Griaule

### ISSUE THREAD

**Issue by henrique-griaule** [frontendbr/vagas#3510]
## Nossa empresa

A Griaule é uma empresa Brasileira com tecnologias de ponta para reconhecimento de impressões digitais, facial, íris, entre outras para Big Data. Com escritórios no Brasil, EUA e Europa somos líderes em desenvolvimento de sistemas multibiométricos de reconhecimento, identificação e autenticação em larga escala.

Estamos crescendo rapidamente e oferecemos muitas oportunidades para que nosso tome cresça conosco. Não perca esta oportunidade!

## Descrição da vaga

Como Professional Services Engineer, você será responsável por integrar os produtos Griaule em sistemas complexos, atendendo aos requisitos dos usuários e às necessidades dos clientes. Você terá a oportunidade de se envolver com aplicativos e serviços móveis, da web, de desktop Windows e Linux. Você trabalhará em projetos de grande escala, com responsabilidades que impactam a vida de milhões de usuários.

## Local

Escritório, [SP], [CAMPINAS], [BARÃO GERALDO]

## Requisitos

**Obrigatórios:**
-Java
-Linux e Windows OS 
-Inglês - Leitura e escrita

**Desejáveis:**
- JS, C++, Python, Bash
- SQL
-Experiência com Testes

**Diferenciais:**
- projetos opensource

## Benefícios

- Salários acima do mercado;
- Participação nos lucros;
- Vale refeição e alimentação;
- Plano de saúde;
- Plano dental;

**Diferenciais:**
- Snacks, doces e chocolates por toda parte
- frigobar sempre cheio :P

## Contratação

CLT

## Como se candidatar

Candidate-se através da página de carreiras no nosso site: griaule.com/careers/

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: hr@griaule.com

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by pedrovsiqueira** [comment]
Não teria que ser somente vagas front end?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
