### ISSUE TITLE
[São Paulo] Front-end Developer na Avivatec

### ISSUE THREAD

**Issue by ThaynacMenezes** [frontendbr/vagas#3511]
[São Paulo] Front-end Developer na Avivatec

==================================================
Caso a vaga for remoto durante a pandemia deixar a linha abaixo
==================================================
-->
> Vaga Remota durante a pandemia

## Nossa empresa

Você quer fazer parte de projetos inovadores em uma empresa que tem como propósito promover a transformação digital de negócios através da tecnologia?

Então vem fazer parte da nossa equipe!

A Avivatec é uma empresa de TI com 12 anos de atuação em desenvolvimento de software.

## Descrição da vaga

Projetos no seguimento bancário e de seguros.

## Local

 Remoto e/ou Escritório, [SP], [São Paulo], [Pinheiros]

## Requisitos

**Obrigatórios:**
 Experiência com Angular 4 ou superior, HTML, CSS e JavaScript 

**Desejáveis:**

**Diferenciais:**
- Ter atuado com Scrum
- Less e Sass
- Flutter

## Benefícios
- 20 dias de descanso remunerado após 1 ano

**Diferenciais:**
Home office parcial 

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para t.menezes@avivatec.com.br com seu CV anexado - enviar no assunto: Vaga Angular

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: Recrutamento@avivatec.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
