### ISSUE TITLE
[São Paulo] Front-end Developer Sr na Petlove

### ISSUE THREAD

**Issue by brubsland** [frontendbr/vagas#3512]
> Vaga Remota durante a pandemia

## Nossa empresa

A Petlove é o maior petshop online e clube de assinaturas para pets do Brasil. Nascemos em 1999 a partir do sonho visionário de um médico veterinário que foi pioneiro em apostar na venda online de produtos pets em uma época em que a internet no país ainda era uma incerteza. Somos investidos pelos melhores fundos de venture capital do Brasil e estamos em ritmo de crescimento acelerado para continuarmos cumprindo nossa principal missão: ajudar pais e mães de pets a fazerem seus filhos peludos mais felizes e saudáveis. 

## Descrição da vaga

Nosso Desenvolvedor Front-End é responsável pela criação e manutenção das interfaces do website mobile e desktop da Petlove, certificando-se sempre em manter um padrão de qualidade e performance. É responsável por criar testes automatizados que assegurem o correto funcionamento dos produtos, além de monitorar e corrigir eventuais bugs e falhas que possam ocorrer. Participa de um squad de produto, atuando em conjunto com PO, designers e demais desenvolvedores a fim de entregar sempre a melhor experiência para nossos clientes.

Estamos crescendo a todo vapor e criando novos produtos, sempre com a meta de fazer os pets mais felizes e saudáveis.

Se você é um(a) profissional que está sempre em busca de novos conhecimentos e formas de inovar, proativo(a) e que adora trabalhar em equipe, temos a oportunidade perfeita pra você!

## Local

Remoto

## Requisitos

Vivência nas seguintes tecnologias:

- VueJS ou React
- GIT
- Javascript (Vanilla)
- Gulp ou Webpack
- HTML 5
- CSS 3
- Sass/Less
- NodeJS
- APIs/REST
- Testes automatizados
- SEO

## Benefícios

- Assistência médica e odontológica 100% custeada pela empresa;
- Vale Refeição (podendo dividir com Vale Alimentação);
- Crédito para Snacks;
- Bicicletário no prédio;
- Sala de descompressão com vídeo-game, mesa de ping-pong e pebolim;
- Day-off de aniversário;
- Ambiente descontraído e dinâmico;
- Parcerias com descontos;
- Desconto em produtos no site;
- PLR - Atrelado a metas;
- Gympass;
- E claro, Pet Friendly, pets são muito bem vindos no escritório!!

## Contratação

CLT Efetivo

## Como se candidatar

Se candidate através do link: https://petlove.gupy.io/jobs/467444

#### Alocação
- Remoto inicialmente
- Pós pandemia; Berrini - SP 

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
