### ISSUE TITLE
[São Paulo] Programador PHP Full Stack na Fotoarena

### ISSUE THREAD

**Issue by claudiofsilva** [frontendbr/vagas#3514]
> Vaga Remota durante a pandemia

## Nossa empresa

A Fotoarena é uma agência de fotojornalismo e banco de imagens que licencia fotografias nacionais e internacionais, além de ilustrações, tiras e charges.

## Descrição da vaga

Programador PHP Full Stack para atuar diretamente no desenvolvimento e manutenção de nossa plataforma de gestão de imagens e conteúdo digital. Procuramos uma pessoa organizada, pró-ativa e focada.

## Local

 Remoto ou Escritório, [São Paulo], [São Paulo], [Perdizes]

## Requisitos

**Obrigatórios:**
- Conhecimento avançado em PHP
- Conhecimento avançado em banco de dados MySQL
- Conhecimento de MVC
- HTML, CSS,  Bootstrap, Javascript, Jquery
- Serviços AWS

**Desejáveis:**
- Conhecimento de Elasticsearch
- Conhecimento de NodeJs

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um e-mail para tecnologia@fotoarena.com.br com seu CV anexado e com pretensão salarial - enviar no assunto: Vaga PHP Full Stack

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: tecnologia@fotoarena.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
