### ISSUE TITLE
[REMOTE] Front-end Developer Pleno na Agriness

### ISSUE THREAD

**Issue by anapadriano** [frontendbr/vagas#3516]
> Vaga pode ser remota pós pandemia

## Nossa empresa

Somos uma empresa de gestão da produção animal que tem como propósito impulsionar a prosperidade no campo. Trabalhamos muito para tornar o agronegócio mais produtivo e rentável, não somente no Brasil, mas no mundo. Estamos em constante crescimento e expansão. Nosso desafio: escalar a Agriness para o mundo!

## Descrição da vaga

Estamos procurando um(a) Desenvolvedor(a) Frontend Pleno apaixonado(a) por criar produtos incríveis.

Estamos construindo a maior plataforma agro do mundo e para isto precisamos de pessoas que curtem grandes desafios, interessados em participar das decisões de tecnologia e ajudem na evolução dos nossos produtos web, mas principalmente mobile.

Sendo mais específico, aqui você irá:
- Interagir com os PMs e Designers para alinhamento sobre a implementação de novas soluções, funcionalidades ou melhorias no produto Presence.
- Implementar código seguindo os padrões de qualidade definidos pela área, através de uso de testes automatizados, processos de integração contínua e revisão de código.
- Fazer entregas de forma contínua, buscando manter a cadência necessária para atendimento dos acordos firmados, interagindo também com outros squads no alinhamento de entregas evitando geração de dependências.
- Apoiar a construção de soluções utilizando para isso tecnologias já adotadas pela empresa como Javascript, ReactJS e React Native.

## Local

Possibilidade de trabalhar em Florianópolis/SC ou full remote.

## Requisitos

**Obrigatórios:**
- Ensino superior em áreas de tecnologia.
- Experiência nas linguagens: Javascript, CSS.
- Experiência nas tecnologias: ReactJS e React Native.
- Conhecimento na construção de soluções para Cloud.
- Conhecimento no uso de testes automatizados.
- Conhecimento no consumo de Rest API’s e WebSockets.
- Conhecimento em temas como: containers, componentização e estilização.
- Inglês intermediário.

**Desejáveis:**
- Conhecimentos nos temas como: Git Workflow, documentação de API’s, design systems.

## Benefícios
- Oportunidade de trabalhar em uma empresa que te desafia, motiva, incentiva e dá liberdade para questionar e contribuir com novas ideias.
- No dress code.
- Previdência Privada.
- Folga no dia do aniversário.
- Parcerias de descontos com convênios.
- Pacote de benefícios tradicionais: VR/VA, Auxílio Combustível, Plano de Saúde.

## Contratação

CLT.

## Como se candidatar

Por favor envie um email para ana.adriano@agriness.com com seu CV anexado - enviar no assunto: Vaga Front-end.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

#### Alocação
- Alocado ou;
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
