### ISSUE TITLE
[Niterói] Front-end Developer na Internit

### ISSUE THREAD

**Issue by Fredpeixoto** [frontendbr/vagas#3519]
> Vaga Remota durante a pandemia

## Nossa empresa

Empresa situada em Niterói com mais de 23 anos de atuação na área de desenvolvimento de sistemas, portais, lojas virtuais e sites.

## Descrição da vaga

Saca de HTML e CSS? É fera em implementar sites em Wordpress?
Estamos abrindo 3 vagas de estágio na Internit para programador front-end.

## Local

No escritório, [RJ], [Niterói], [Santa Rosa]

## Requisitos

**Obrigatórios:**
Vivência em Html, CSS, Java Script com JQuery e implantação de sites em Wordpress. O candidato deve estar no máximo no 6º período em um curso na área. Também é obrigatório se cadastrar no nosso site no link Currículo

**Diferenciais da Internit:**
Ótimo ambiente de trabalho somado à desafios constantes.
Horário flexível em formato de banco de horas.
Jogos no horário do almoço.
Pós pandemia: Estamos situados em uma rua tranquila em Niterói com facilidade de estacionamento além de termos um bicicletário na empresa.

## Benefícios

- Bolsa
- Vale transporte
- Seguro contra acidentes pessoais

- ...

## Contratação

Estátgio

## Como se candidatar

Cadastre-se seu currículo em https://internit.com.br/curriculo

#### Alocação
- Alocado

#### Regime
- Estágio

**Comment by RenatoAreas** [comment]
Aceita Dev Jr ?

**Comment by Fredpeixoto** [comment]
Enviar currículo pelo site, por favor, que avaliamos

*www.internit.com.br
<https://mailtrack.io/trace/link/d8f40fc8af4e83c0c62b9b808096e67a1f2edb82?url=http%3A%2F%2Fwww.internit.com.br%2F&userId=393368&signature=95de46e49aa0ae82>www.incenadigital.com.br
<https://mailtrack.io/trace/link/d892584bcba1df7a6c058599a38f0793ed7ded8d?url=http%3A%2F%2Fwww.incenadigital.com.br&userId=393368&signature=d003d2c174e57b62>*

[image: Internit]
*Frederico Peixoto*
Diretor Comercial
fred@internit.com.br <luciano@internit.com.br>
(21) 2621-7788 | (21) 98123-2303
[image: Acompanhe a Internit no Facebook]
<https://mailtrack.io/trace/link/dbba7e5e40a15946a6342a2a342e86b4f01eb691?url=http%3A%2F%2Fwww.facebook.com%2Fsejainternit&userId=393368&signature=c35ee38d6265ba3c>
[image:
Siga a Internit no Linkedin]
<https://mailtrack.io/trace/link/6bcaa881f4f4472b99b229a6310f33b8ad4c7ea9?url=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F3283804%3Ftrk%3Dtyah%26trkInfo%3Dtas%253Ainternit%2520LTD%252Cidx%253A1-1-1&userId=393368&signature=e17f699ecd47b5c4>


Em ter., 1 de set. de 2020 às 17:05, RenatoAreas <notifications@github.com>
escreveu:

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by EmanuelNerys** [comment]
tenho certa experiencia em html, css, js. tailwind , python, git e git hub

**Comment by Fredpeixoto** [comment]
Bacana. Não deixe de se cadastrar em https://internit.com.br/curriculo.
Assim, teremos os seus dados em nosso banco de dados.

Abs

[image: Internit]
*www.internit.com.br <http://www.internit.com.br/>**www.incenadigital.com.br
<http://www.incenadigital.com.br/>*
 RJ
***@***.***,-43.1073818,17z/data=!3m1!4b1!4m5!3m4!1s0x9983f238c0e803:0x36d8501864605205!8m2!3d-22.8961089!4d-43.1051931>
  SP
<https://www.google.com/maps/place/Rua+Norma+Pieruccini+Giannotti,+141+-+V%C3%A1rzea+da+Barra+Funda,+S%C3%A3o+Paulo+-+SP,+01137-010/data=!4m2!3m1!1s0x94ce580ebf4681b1:0xbc9940a345bbe3e6?sa=X&ved=2ahUKEwjm9rTIpdvkAhUcK7kGHZ-bDkEQ8gEwAHoECAoQAQ>
*Frederico
Peixoto*
Diretor Comercial
***@***.***
(21) 2621-7788 <+55212621-7788> | (21) 98123-2303 <+552198123-2303>
[image: Acompanhe a Incena no Facebook]
<https://www.facebook.com/incenadigital> [image: Acompanhe a Incena no
Facebook] <https://www.instagram.com/incenadigital/> [image: Siga-me no
Linkedin] <https://www.linkedin.com/in/fredericopeixoto/>


Em qui., 26 de set. de 2024 às 15:58, 'EmanuelNerys' via Vagas <
***@***.***> escreveu:
