### ISSUE TITLE
[São Paulo] - Frontend Developer

### ISSUE THREAD

**Issue by raulfernando** [frontendbr/vagas#352]
## Descrição da vaga

Nós procuramos um desenvolvedor(a) front-end (junior/pleno) que terá como responsabilidade principal criar/manter sites responsivos.

## Local

Escritório, São Paulo - Pinheiros

## Benefícios

- Assistência médica
- Assistência Odontologica
- Vale-refeição
- Vale-transporte

## Requisitos

**Obrigatórios:**
- Conhecimentos sólidos em desenvolvimento frontend: HTML5, CSS3, Javascript e jQuery;
- Conhecimento em pré-processadores CSS (SASS ou LESS);
- Conhecimento de task-runners como Grunt ou Gulp;
- Conhecimento básico em programação PHP;
- Desejável conhecimento de desenvolvimento WordPress (e experiência com custom fields, taxonomies, custom post types);
- Conhecimento com design responsivo;
- Conhecimento com desempenho, otimização e web performance;
- Conhecimento com Git;

**Desejáveis:**
- Docker (Basico)

## Contratação

CLT

## Nossa empresa

Nascida no ano de 1993 tendo como principais características a aposta no bom jornalismo, o senso empreendedor e uma fina percepção do mercado, a Editora Segmento é, hoje, uma das principais referências brasileiras na produção de conteúdos sobre educação e gestão de pessoas.

## Como se candidatar

Por favor envie um email para raul@editorasegmento.com.br com seu CV anexado - enviar no assunto: Vaga FrontEndBR

**Comment by raulfernando** [comment]
Vaga preenchida,
Obrigado a todos que enviaram seus CVs

**Comment by LFeh** [comment]
Boa!
