### ISSUE TITLE
[São Paulo] Pessoa desenvolvedora front-end na Viva Decora 

### ISSUE THREAD

**Issue by teles** [frontendbr/vagas#3520]
> Vaga Remota durante a pandemia

## Descrição da vaga

Então você acredita que um trabalho é bom se o time é bom? Não tem medo de fazer parte de um time pequeno que já conseguiu grandes resultados? Acredita que a tecnologia é um meio para um fim e adora dormir tranquilo sabendo que seu trabalho foi bem feito? Além disso você ainda conhece esses tais Javascript, SASS, Single Page Application, e talvez um pouquinho de angularJS ou Vue? Quer trabalhar 100% remoto até o final de 2020? O destino te trouxe essa vaga.

A Viva Decora é uma empresa criada em 2015 e que hoje, entre outros resultados positivos, é o maior site de decoração da América Latina. Temos mais de 12 milhões de sessões mensais! Tudo isso com um time de tecnologia focado e enxuto que agora precisa de você: uma pessoa desenvolvedora front-end nível pleno!!

Em 2019 um marketplace com 1 milhão de produtos e que só vem crescendo desde então, em 2020 passamos a fazer parte do grupo Duratex.

Procure por algum termo relacionado a decoração no Google e conheça um pouco sobre nossos sistemas.

### Você é bom em:

* Ler o código dos seus pares antes de escrever o seu
* Trabalhar na mesma base de código que seus companheiros sem medo de conflito
* Avaliar o impacto das suas decisões de arquitetura e design
* Conversar com o time de design, backend e produto compartilhando dos mesmos objetivos
* Lógica (logicamente)

### Também seria legal se você:
* Escrevesse testes unitários para o seu código
* Entendesse de SEO o suficiente para tomar decisões pontuais 
* Tivesse alguma experiência ou curiosidade sobre AMP e/ou PWA 

### Dia a dia:

![Sim, temos kanban](https://cdn.startupi.com.br/wp-content/uploads/2017/06/Daily-1.jpg)

* Como front-end você aqui vai trabalhar com tecnologias como angularJs, git, sass, html5, AMP, ES6, SEO e eventualmente WordPress.
* As ferramentas que usamos no dia a dia incluem AWS, GitHub, Analytics, TagManager, Optimize, Jira, Slack, Kanban, Hangouts e nossa versão adaptada do Scrum.
* O time conta com você: somos 6 desenvolvedores, 2 designers, 1 gerente de produtos e 1 analista SEO. É muito comum conversarmos diariamente sobre as demandas pra alinhar expectativas e compartilhar ideias.

### Nós temos:
* Um time de engenharia pequeno, focado e que costumar trabalhar em pares
* Um fluxo de trabalho bem definido do iníncio ao fim das tarefas (me pergunte sobre isso)
* Uma crença na autonomia dos nossos desenvolvedores e no alinhamento do time
* Todas as ferramentas comuns de suporte ao time como Jira, NewRelic, Analytics
* Faixa salarial competitiva entre R$ 6.500 e R$ 7.500 e outros benefícios
Se você leu até aqui seu coração quer que você se inscreva para essa vaga.
Faça isso e me pergunte o que você quiser sobre o time, a empresa ou outras coisas.

## Local

São Paulo - SP.
Av. Paulista - 1938 - Bela Vista São Paulo (esquina com a rua Frei Caneca)

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com Single Page Application, CSS e HTML

**Desejáveis:**
- Conhecimentos em angularJS

**Diferenciais:**
- Conhecimentos em VueJS

## Benefícios

- Plano de saúde
- VR de R$ 30/dia
- Auxílio creche

**Diferenciais:**
- time enxuto e com autonomia

## Contratação

CLT

## Como se candidatar

Siga as instruções disponíveis no projeto GitHub https://github.com/vivadecora/projeto-front-end-vivadecora-nao-fazer-fork
Ou se tiver dúvidas, por favor, envie um email para ![dummy_200x20_ffffff_ff5656_josemacielvivadecoracombr](https://user-images.githubusercontent.com/762639/92024161-2a2e9680-ed34-11ea-8125-a8176991f812.png)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após cada processo.
E-mail para contato em caso de não haver resposta: ![dummy_200x20_ffffff_ff5656_josemacielvivadecoracombr](https://user-images.githubusercontent.com/762639/92024161-2a2e9680-ed34-11ea-8125-a8176991f812.png)

## Labels

* Alocado
* CLT
* PLENO

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno

**Comment by victorhsantiago** [comment]
Super recomendo!

**Comment by RafaPalau** [comment]
Não tem vaga para Junior não? Sonho em trabalhar na Viva Decora. hehehe

**Comment by MayaraRMA** [comment]
O teste pode ser feito em Vue?

**Comment by teles** [comment]
Valeu, @victorhsantiago.
Foi excelente a experiência de trabalhar com você aqui também. Sucesso pro senhor e se precisar dá um toque

**Comment by teles** [comment]
@RafaPalau não sei qual o seu momento na carreira mas aqui já ocorreu de profissional que se considerava júnior fazer o teste e entrar como pleno. 
Aí vai de você considerar se isso seria uma possibilidade agora :)

**Comment by teles** [comment]
@MayaraRMA pode sim, com certeza.

**Comment by RafaPalau** [comment]
> @RafaPalau não sei qual o seu momento na carreira mas aqui já ocorreu de profissional que se considerava júnior fazer o teste e entrar como pleno.
> Aí vai de você considerar se isso seria uma possibilidade agora :)

Nossaaaa. Vou tentar então. 
Meu momento é terminando a facul e estudando igual um condenado. hehehe 
Procurando um oportunidade. 

Quanto tempo pra fazer o teste?

**Comment by teles** [comment]
@RafaPalau o recomendado é 1 semana para fazer o teste proposto no GitHub.

**Comment by olucasgomes** [comment]
Há possibilidade de trabalhar remoto após a pandemia? Adoraria trabalhar com vocês, mas presencialmente não rola :/

**Comment by teles** [comment]
@olucasgomes infelizmente não, depois que passar a pandemia o trabalho é alocado mesmo :/

**Comment by dziul** [comment]
> > @RafaPalau não sei qual o seu momento na carreira mas aqui já ocorreu de profissional que se considerava júnior fazer o teste e entrar como pleno.
> > Aí vai de você considerar se isso seria uma possibilidade agora :)
> 
> Nossaaaa. Vou tentar então.
> Meu momento é terminando a facul e estudando igual um condenado. hehehe
> Procurando um oportunidade.
> 
> Quanto tempo pra fazer o teste?

@RafaPalau , sou prova disso... Tinha mudado de área design (web) pra frontEnd, e nessa migração a única que acreditou no meu potencial foi a VivaDecora. me considerava junior (por estar iniciando na área), mas entrei como pleno... por questão do conhecimento mostrado no teste.

**Vai com tudo**! 

O time é excelente, ambiente agradável, _dailies_ sem enrolações, 

aah aprendi muita coisa também, ótimos _professores_.

ps: os cara são apelões no MarioKart  🤣

**Comment by teles** [comment]
@dziul muito obrigado, Luiz. Fiquei feliz com suas palavras aqui.

Você é fera, foi muito bom trabalhar contigo.

Mario Kart agora tá só no "Mario Kart Tour" me adiciona lá haha

**Comment by pedrolucasD** [comment]
Email enviado para José Maciel 😄 
Tive problemas de somente no iphone, com sidebar, pensei até que fosse o safari, porém testei no Safari usando android e não tive problemas, somente com iPhone mesmo.
https://vd-movie-curation.vercel.app/

**Comment by teles** [comment]
Obrigado, @pedrolucasD

**Comment by pedrolucasD** [comment]
@teles esse projeto pode ser publicado no LinkedIn com a marca de vocês?

**Comment by teles** [comment]
@pedrolucasD pode sim. Basta mencionar também o nome da empresa e tudo certo. Valeu :)

**Comment by teles** [comment]
⚠️ ⚠️ ⚠️ 
Vou deixar a vaga como encerrada para novos testes, por enquanto.
Caso você que está lendo isso esteja finalizando esse teste, fale comigo ou responda aqui que conversamos.
Obrigado
