### ISSUE TITLE
[Belo Horizonte] Front-end Developer na Teknisa

### ISSUE THREAD

**Issue by rhteknisa** [frontendbr/vagas#3522]
## Nossa empresa

  A Teknisa oferece soluções de suporte à gestão com forte atuação nos segmentos de indústrias alimentícias, químicas e farmacêuticas, e atende todos os canais ligados ao mercado de food service. Hoje ocupamos uma posição de destaque no mercado latino americano de software, com sistemas implantados em várias empresas, presente em 6 países, 20 mil instalações, 65 mil usuários ativos e mais de 20 milhões de clientes atendidos por dia pelos sistemas Teknisa. Nosso objetivo é acompanhar as tendências e desenvolver soluções que possam transformar, de maneira positiva, a gestão empresarial.

## Descrição da vaga

Buscamos uma pessoa que seja centrada, tenha o foco em resultados e engajada em aprender novos conhecimentos.

## Local
Savassi, Belo Horizonte - Minas Gerais

## Requisitos

**Obrigatórios:**
JavaScript, HTML e CSS;
JAVA;
TypeScript;
Conhecimento de aplicações Mobile;
Experiência com APIs;
Conhecimento em metodologias ageis
Frameworks React native / React JS.

Superior concluído ou cursando a partir do 8 período em Ciências da Computação, Sistema de Informações e áreas afins.

## Benefícios
-> Vale transporte;
-> Vale refeição;
 -> Plano de saúde;
 -> Plano odontológico;
-> seguro de vida.
 ->  PL
-> 40hs semanais

## Como se candidatar

Por favor envie o seu curriculo através desse link:  Programador na Teknisa | https://jobs.solides.com/teknisa/vaga/31625 ou em nosso email rh.teknisa@gmail.com

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
