### ISSUE TITLE
[Belo Horizonte] Front-end Developer na RM

### ISSUE THREAD

**Issue by marcelovna** [frontendbr/vagas#3524]
## Requisitos **Desejáveis:**
-Dev sistemas Web
-Javascript, React (Vue.js, Angular)
-Conhecimento em UX/UI e Computação Gráfica
-Inglês técnico avançado
-Disponibilidade em horário comercial
-Formação em Engenharia de Sistemas, Ciências da Computação ou áreas afins

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ X/dia

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para marcelo@radiomemory.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Developer RM

#### Alocação
- Remoto

#### Regime
- CLT
- Freela
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
