### ISSUE TITLE
[São Paulo] Front-end Developer na Contabilizei

### ISSUE THREAD

**Issue by KarineLiuti** [frontendbr/vagas#3525]
# [São Paulo] Front-end Developer na Contabilizei

> Vaga Remota durante a pandemia

## Nossa empresa

Com mais de 20 mil clientes, atuando em mais de 50 cidades do Brasil, a Contabilizei está mudando a maneira como o micro e pequeno empreendedor gerencia o seu negócio em nosso país. Continuamos a crescer rapidamente, criando novos produtos e proporcionando que o empreendedor seja o contador de sua própria história.

Por aqui, somos mais de 400 pessoas, todas selecionadas a dedo, e que levam muito a sério o nosso propósito de resolver o problema real brasileiro, trabalhando em busca de soluções inovadoras para facilitar a vida dos nossos clientes.

## Descrição da vaga

Um dia típico inclui:

- Entender as exigências e especificações dos arquitetos do sistema, contribuindo no desenvolvimento de sistemas que entreguem valor;
- Entregar código testável com qualidade, sinalizando problemas e impedimentos que impactam no prazo acordado;
- Manter sistemas e funcionalidades do lado do cliente (front-end) para fornecer aos usuários finais acesso às funções do sistema;
- Colaborar com a construção de componentes de aplicativos front-end para incluir scripts a serem executados em navegadores web de diversos dispositivos do lado do cliente.

## Local

São Paulo - SP

## Requisitos

**Obrigatórios:**
- Graduação concluída ou cursando em Análise de Sistemas, Engenharia da Computação ou áreas afins;
- Conhecimento em Arquitetura Web;
- Conhecimento em Angular, React ou VueJS;
- Conhecimento em linguagens e melhores práticas (JavaScript, TypeScript, paradigmas funcional e orientação a objetos);
- Conhecimento em arquitetura de software;
- Conhecimento em qualidade de software;
- Conhecimento em DevOps;
- Conhecimento em UX/UI.

## Benefícios

**Diferenciais:**
Nossas Guardiãs e Guardiões acreditam e perseguem nosso propósito: Entendem que o sucesso do empresário é o nosso sucesso. Oferecemos um ambiente descontraído, completamente colaborativo, com ritmo acelerado e desafiador, a fim de atingir resultados e promover a melhor experiência aos nossos clientes, construindo uma jornada de sucesso. Acreditamos no protagonismo, aqui você constrói sua carreira da sua forma e cresce junto com a Contabilizei. 
Aqui, você terá a oportunidade de gerar um grande impacto positivo, construindo o futuro de como os empresários brasileiros gerenciam seus negócios com sucesso.

## Contratação
CLT

## Como se candidatar
Acesse: [Gupy Contabilizei]: https://contabilizei.gupy.io/jobs/468688?jobBoardSource=gupy_public_page

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Júnior

**Comment by MatSa20** [comment]
Olá,  estou tendo problemas para me cadastrar pela Gupy, teria algum método alternativo? Ou talvez um email para que eu encaminhe meu CV?

**Comment by rayanmarcus** [comment]
Olá @KarineLiuti.
No último teste, do teste técnico, ele não exibe o código que deve ser analisado para poder responder o formulário. Dessa forma, a resposta acaba sendo aleatória, porque não se sabe o que foi solicitado no código.
Como posso enviar um print dessa tela para vocês analisarem?

**Comment by luialbeto** [comment]
Mesma situação aqui

**Comment by KarineLiuti** [comment]
> Olá @KarineLiuti.
> No último teste, do teste técnico, ele não exibe o código que deve ser analisado para poder responder o formulário. Dessa forma, a resposta acaba sendo aleatória, porque não se sabe o que foi solicitado no código.
> Como posso enviar um print dessa tela para vocês analisarem?

Olá, @rayanmarcus ! Você pode me mandar por e-mail, se quiser: karine.silva@contabilizei.com.br
Se quiser gravar um vídeo do que está acontecendo e me mandar o link, você pode usar essa extensão aqui: https://chrome.google.com/webstore/detail/loom-for-chrome/liecbddmkiiihnedobmlmillhodjkdmb

Obrigada pelo feedback! =)

**Comment by KarineLiuti** [comment]
> Olá, estou tendo problemas para me cadastrar pela Gupy, teria algum método alternativo? Ou talvez um email para que eu encaminhe meu CV?

Olá, @MatSa20 !
Então, todo o processo é somente pela Gupy mesmo...
Você pode me mandar por e-mail um print do problema, se quiser (eu repasso pra galera do RH): karine.silva@contabilizei.com.br
Se quiser gravar um vídeo do que está acontecendo e me mandar o link, você pode usar essa extensão aqui: https://chrome.google.com/webstore/detail/loom-for-chrome/liecbddmkiiihnedobmlmillhodjkdmb

:)

**Comment by luialbeto** [comment]
@KarineLiuti enviado 👍🏼

**Comment by rayanmarcus** [comment]
> > Olá @KarineLiuti.
> > No último teste, do teste técnico, ele não exibe o código que deve ser analisado para poder responder o formulário. Dessa forma, a resposta acaba sendo aleatória, porque não se sabe o que foi solicitado no código.
> > Como posso enviar um print dessa tela para vocês analisarem?
> 
> Olá, @rayanmarcus ! Você pode me mandar por e-mail, se quiser: [karine.silva@contabilizei.com.br](mailto:karine.silva@contabilizei.com.br)
> Se quiser gravar um vídeo do que está acontecendo e me mandar o link, você pode usar essa extensão aqui: https://chrome.google.com/webstore/detail/loom-for-chrome/liecbddmkiiihnedobmlmillhodjkdmb
> 
> Obrigada pelo feedback! =)

Enviei para o seu e-mail ;)

**Comment by KarineLiuti** [comment]
> > > Olá @KarineLiuti.
> > > No último teste, do teste técnico, ele não exibe o código que deve ser analisado para poder responder o formulário. Dessa forma, a resposta acaba sendo aleatória, porque não se sabe o que foi solicitado no código.
> > > Como posso enviar um print dessa tela para vocês analisarem?
> > 
> > 
> > Olá, @rayanmarcus ! Você pode me mandar por e-mail, se quiser: [karine.silva@contabilizei.com.br](mailto:karine.silva@contabilizei.com.br)
> > Se quiser gravar um vídeo do que está acontecendo e me mandar o link, você pode usar essa extensão aqui: https://chrome.google.com/webstore/detail/loom-for-chrome/liecbddmkiiihnedobmlmillhodjkdmb
> > Obrigada pelo feedback! =)
> 
> Enviei para o seu e-mail ;)

@rayanmarcus, @MatSa20 e @luialbeto,

Já passei esse problema para o RH. Eles irão remover essa questão do banco e desconsiderar a resposta dela.
Obrigada pelo feedback!

**Comment by rayanmarcus** [comment]
> > > > Olá @KarineLiuti.
> > > > No último teste, do teste técnico, ele não exibe o código que deve ser analisado para poder responder o formulário. Dessa forma, a resposta acaba sendo aleatória, porque não se sabe o que foi solicitado no código.
> > > > Como posso enviar um print dessa tela para vocês analisarem?
> > > 
> > > 
> > > Olá, @rayanmarcus ! Você pode me mandar por e-mail, se quiser: [karine.silva@contabilizei.com.br](mailto:karine.silva@contabilizei.com.br)
> > > Se quiser gravar um vídeo do que está acontecendo e me mandar o link, você pode usar essa extensão aqui: https://chrome.google.com/webstore/detail/loom-for-chrome/liecbddmkiiihnedobmlmillhodjkdmb
> > > Obrigada pelo feedback! =)
> > 
> > 
> > Enviei para o seu e-mail ;)
> 
> @rayanmarcus e @luialbeto,
> 
> Já passei esse problema para o RH. Eles irão remover essa questão do banco e desconsiderar a resposta dela.
> Obrigada pelo feedback!

Obrigado! =)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
