### ISSUE TITLE
[Curitiba] Front-end Mobile Developer Pleno na Contabilizei

### ISSUE THREAD

**Issue by KarineLiuti** [frontendbr/vagas#3526]
# [Curitiba] Front-end Mobile Developer Pleno na Contabilizei

> Vaga Remota durante a pandemia

## Nossa empresa

Com mais de 20 mil clientes, atuando em mais de 50 cidades do Brasil, a Contabilizei está mudando a maneira como o micro e pequeno empreendedor gerencia o seu negócio em nosso país. Continuamos a crescer rapidamente, criando novos produtos e proporcionando que o empreendedor seja o contador de sua própria história.

Por aqui, somos mais de 400 pessoas, todas selecionadas a dedo, e que levam muito a sério o nosso propósito de resolver o problema real brasileiro, trabalhando em busca de soluções inovadoras para facilitar a vida dos nossos clientes.

## Descrição da vaga

Com mais de 20 mil clientes, atuando em mais de 50 cidades do Brasil, a Contabilizei está mudando a maneira como o micro e pequeno empreendedor gerencia o seu negócio em nosso país. Continuamos a crescer rapidamente, criando novos produtos e proporcionando que o empreendedor seja o contador de sua própria história.

No Squad Engajamento acreditamos que uma boa experiência aliada a dados para propor melhorias e mudanças dentro dos canais, pode ser agente transformador da jornada do cliente, agregando valor também ao negócio dos empreendedores brasileiros.

Pensamos diariamente em como tornar a contabilidade simples e intuitiva. Para que nossos clientes possam focar em seus negócios e não na burocracia contábil. Somos os responsáveis pela qualidade e performance da plataforma da Contabilizei. 

Empreender no Brasil é um desafio, e no squad de Engajamento, você tem a oportunidade de ajudar a vencer diariamente a burocracia através da tecnologia.

Acreditamos que a diversidade promove o crescimento sustentável. Na Contabilizei queremos que você seja a melhor versão de si, e as oportunidades são para todos. Valorizamos as diferenças, e estamos abertos a receber pessoas com quaisquer deficiências, gênero, etnia, orientação sexual e diferentes mindsets. Juntos, construímos a Contabilizei do nosso jeito.

Ahhh e essa oportunidade é para trabalhar em Curitiba após a pandemia, além disso, todas as nossas vagas são regime CLT.  

## Local

Curitiba - PR

## Requisitos
**Obrigatórios:**
- Graduação concluída em Análise de Sistemas, Engenharia da Computação ou áreas afins;
- Experiência em desenvolvimento de aplicativos mobile;
- Ampla habilidade com Fronts responsivos, Javascript (ES5, ES6), HTML5 e CSS3;
- Experiência em AngularJS, VueJS ou React;
- Consumo de API's RESTful;
- Noções de UX/UI;
- Conhecimentos em controle de versão (Git);
- Conhecimento sobre métodos ágeis de desenvolvimento.

**Desejáveis:**
- Controle de Estado, Vuex ou Redux;
- Prática com automação de testes (Selenium, Jasmine, Jest).

**Responsabilidades e Atribuições**
- Analisar as exigências e especificações dos arquitetos do sistema, e contribuir com o desenho da solução (arquitetura, modelagem, design de código), atuando no desenvolvimento de sistemas que entreguem valor;
- Entregar com autonomia código testável com qualidade, estimando o esforço e o custo necessário para cumprir expectativas acordadas e comunicando necessidade de novos prazos;
- Desenvolver e propor melhorias em sistemas e funcionalidades do lado do cliente (front-end) para fornecer aos usuários finais acesso às funções do sistema;
- Construir componentes de aplicativos front-end para incluir scripts a serem executados em navegadores web de diversos dispositivos do lado do cliente, considerando conceitos da experiência do usuário;
- Identificar problemas na base de código existente e aplicar melhorias;
- Pode apoiar no desenvolvimento técnico de profissionais com menos experiência, ajudando a desenvolver um time com nível adequado de qualificação.

## Benefícios

**Diferenciais:**
Nossas Guardiãs e Guardiões acreditam e perseguem nosso propósito: Entendem que o sucesso do empresário é o nosso sucesso. Oferecemos um ambiente descontraído, completamente colaborativo, com ritmo acelerado e desafiador, a fim de atingir resultados e promover a melhor experiência aos nossos clientes, construindo uma jornada de sucesso. Acreditamos no protagonismo, aqui você constrói sua carreira da sua forma e cresce junto com a Contabilizei. 
Aqui, você terá a oportunidade de gerar um grande impacto positivo, construindo o futuro de como os empresários brasileiros gerenciam seus negócios com sucesso.

## Contratação
CLT

## Como se candidatar
Acesse: [Gupy Contabilizei]: https://contabilizei.gupy.io/jobs/472154?jobBoardSource=gupy_public_page

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
