### ISSUE TITLE
[São Paulo] Front-end Developer na Spread Tecnologia

### ISSUE THREAD

**Issue by spreadthais** [frontendbr/vagas#3527]
> Vaga Remota durante a pandemia

## Nossa empresa

Nós acreditamos que boas ideias nascem de bons relacionamentos, boas conversas e troca de experiências. 

Se você, assim como nós, sente vontade de transformar os negócios, a sociedade e o mundo por meio da tecnologia, em seu DNA está a #PaixãoPorTransformação, portanto, junte-se a nós e venha ser um #Spreader. 

## Descrição da vaga

Aqui você pode atuar como Desenvolvedor Front End Angular e seu dia a dia será repleto de desafios para juntos construirmos a revolução na tecnologia.

## Local

 Escritório, [SÃO PAULO], [SÃO PAULO], [GRANJA JULIETA]

## Requisitos

**Obrigatórios:**
- Experiência com Angular 9, Typescript

**Desejáveis:**
- conhecimentos em Rxjs
- Métodos ágeis 

**Diferenciais:**
- conhecimento em API Rest e Cloud Pública (AWS, Azure)

## Benefícios

- Plano de saúde
- Plano odontológico
- Seguro de vida
- VR de R$ 18,62/dia
- Auxílio creche
- VT

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um email para thais.silva@spread.com.br com seu CV anexado - enviar no assunto: Vaga Front End

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: thais.silva@spread.com.br

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
