### ISSUE TITLE
[REMOTO] React Developer @Pipefy

### ISSUE THREAD

**Issue by joanamendes12** [frontendbr/vagas#3528]
A Pipefy, uma poderosa plataforma de gestão do trabalho, sendo usada em mais de 150 países e por empresas líderes como Visa, IBM, Coca-Cola, Volvo, Santander e Kraft Heinz, está em busca de uma pessoa desenvolvedora de JavaScript, que seja proficiente em React. Com a responsabilidade de garantir que o aplicativo seja robusto, fácil de manter, compreender e estender.  

**Local:** Remoto

**Contratação:** CLT 

**Senioridade:** Sênior

Requisitos principais: Proficiência em JavaScript, incluindo manipulação de DOM e o objeto JavaScript modelo;
Compreensão completa do estilo de programação do Modelo de Componente;
Experiência com gestão de estado no React;
Conhecimento em React Isomorphic é uma vantagem;
Familiaridade com APIs RESTful e GraphQL;
Conhecimento de modernos mecanismos de autorização, como JSON Web Token;
Familiaridade com pipelines e ferramentas de construção front-end modernos;
Experiência com ferramentas de desenvolvimento front-end comuns, como Babel, Yarn, NPM, etc.;
Capacidade de entender os requisitos de negócios e traduzi-los em aspectos técnicos requisitos;
Familiaridade com Git;
Conhecimento CSS;
Semântica HTML.

Diferencial: Conhecimento em Typescript/Flow;
Interesse em benchmarking e otimização.

Fazer o cadastro no seguinte site: **https://byintera.in/pfrdghfe** 
Dúvidas: https://www.linkedin.com/in/joana-mendes-/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
