### ISSUE TITLE
[Remoto] React Native Developer Pleno/Sênior na Skilopay

### ISSUE THREAD

**Issue by ssscassio** [frontendbr/vagas#3529]
## Nossa empresa

Somos uma empresa com pouco mais de um ano, em fase de tração, possuímos milhares de clientes na nossa base e pretendemos crescer MUITO :rocket: nos próximos meses. Queremos impactar milhões de pessoas!

## Descrição da vaga

Que tal resolver problemas do mercado financeiro e impactar milhões de pessoas? A Skilopay é uma empresa de tecnologia que desenvolve produtos e serviços financeiros. Atualmente está em busca de pessoas incríveis para ajudar a revolucionar a maneira que lidamos com dinheiro no Brasil.

## Local

100% Remoto (somos uma empresa _remote-first_)

## Benefícios

- Trabalhe de onde quiser;
- Horário flexível;
- Tecnologias de ponta;
- Participação nos lucros da empresa;
- Ajuda de custo para montar seu Home Office;

## Requisitos

**Obrigatórios:**
- React Native

**Desejáveis:**
- TypeScript
- GraphQL/Apollo

## Contratação

CLT ou PJ

## Como se candidatar

Por favor, envie um email para [jonata@skilopay.com.br](mailto:jonata@skilopay.com.br) com seu currículo ou linkedin - enviar com assunto: Vaga Mobile Developer

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior

**Comment by krivax** [comment]
qual o nivel?

**Comment by ssscassio** [comment]
@krivax Pleno ou Sênior

**Comment by ssscassio** [comment]
@felipefialho Poderia adicionar as labels Pleno e Sênior por favor?

**Comment by LuanCassiano** [comment]
CV enviado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
