### ISSUE TITLE
[São Paulo] Front-End Developer @ Bluesoft

### ISSUE THREAD

**Issue by brenocordeiro** [frontendbr/vagas#353]
Que tal trabalhar em uma organização que estimula o crescimento de seus profissionais? 

Estamos sempre de olho em oportunidades desafiadoras (em clientes bacanas e sérios). Essa posição é uma delas, a Bluesoft é reconhecida como uma empresa com excelente ambiente de trabalho e oportunidade de longo prazo.

Caso deseje entrar para um time em que todos gostam de aprender, compartilhar o conhecimento e trabalhar em equipe, continue a leitura...

**Oportunidade**
•	Salário Competitivo
•	Plano de Saúde + VR + VA + Seguro de Vida
•	Localização: Moema
•	Empresa Referência em Ambiente Ágil
•	Academia Alto Padrão + Café + Frutas a vontade ☺ + Biblioteca da Empresa 
•	Hackathon Mensal + Game Night + Noite do Filme 
•	Flexibilidade no horário: sim. Trabalho remoto não disponível. 
•	Ambiente Descontraído, trabalho sério, com clima bacana, confira no vídeo: https://vimeo.com/132328850

**Atividades**
•	Trabalhar colaborativamente como membro de time ágil formado por desenvolvedores, testadores, designers e analistas no desenvolvimento de software com foco em Design e Front-end.
•	Prototipar novos conceitos de interface, testar ideias, implementar modelos elaborados, definir padrões e ajudar os times aplicá-los em seu dia-a-dia, validar impacto esperado na entrega.
•	Manter os produtos da Bluesoft sempre no estado da arte em relação a Front End, Design e UX, e sendo uma referência nessas áreas de conhecimento para todo o nosso time.

**Requisitos**
•	HTML 5
•	CSS/SASS/LESS
•	Bootstrap
•	Javascrip/JQuery
•	AngularJS 1
•	Mockups
•	Design Responsivo
•	Testes Unitários com Jasmine
•	Inglês Técnico

**Extras**
•	Experiência Ambiente Ágil 
•	Conhecimento de Framework de Marcação (Velocity, JSP, Fremarker, ASP)
•	Conhecimento Editoração Gráfica, Design de Interação e Design Thinking.
•	Frameworks Javascript (Backbone, Spine, Knockout, EmberJS)
•	Conhecimento SEO, Lean UX, Design de Interação, AB Testing.
•	Conhecimento de ERP (Financeiro, Contábil, Logística, Comercial, Fiscal)
•	Ferramentas para Desenvolvimento Frontend (YeomanJS, Grunt, Gulp, Bower)
•	Contribuição Projetos Open Source
•	Design de Interação
•	Design Thinking

Se interessou? Envie e-mail para breno.cordeiro@venturatec.com ou ligue e agende uma conversa confidencial (11) 4872-2422

Possui Indicação? Envie contato e receba uma recompensa de R$ 300,00 caso aconteça contratação.

**Comment by IgorSousaFront** [comment]
Possibilidade de remoto?:

**Comment by rafaelassumpcao** [comment]
@IgorSousaFront  bastava ler a descrição da vaga cara  "Flexibilidade no horário: sim. Trabalho remoto não disponível."

**Comment by brenocordeiro** [comment]
@IgorSousaFront a oportunidade é presencial em SP. Assim que tivermos oportunidades remotas farei contato com você. Obrigado! Abs, Breno @ VT

**Comment by mtmr0x** [comment]
@brenocordeiro essa vaga ainda esta aberta?

**Comment by brenocordeiro** [comment]
Olá @mtmr0x sim, por favor me envie e-mail (breno.cordeiro@venturatec.com) e vamos agendar um bate papo para eu lhe apresentar detalhes. Obrigado! Um abraço, Breno @ VT

**Comment by tpreviero** [comment]
@brenocordeiro td bem ?
Ainda aceita candidatura ?
Abs,

**Comment by brenocordeiro** [comment]
@tpreviero tudo certo e com você? Me desculpe a demora. Sim, ainda aceitamos candidatura, você poderia me enviar CV e bom horário para uma conversa por telefone essa semana? Segue e-mail: breno.cordeiro@venturatec.com 

Muito obrigado,
Um abraço,
Breno

**Comment by lucasaugustofrontend** [comment]
enviado

**Comment by thenewbiemaster** [comment]
Show de vaga. Ainda aceita cv?

**Comment by brenocordeiro** [comment]
Olá @thenewbiemaster valeu pela mensagem. Acredito que não está aceitando mais. Irei checar com o cliente. Obrigado! Um abraço, Breno

**Comment by LFeh** [comment]
Aberto ainda?
