### ISSUE TITLE
[Remoto] Rock Star Front-end Developer na @FieldControl

### ISSUE THREAD

**Issue by lfreneda** [frontendbr/vagas#3532]
## Field Control

Somos um SaaS (Software as a service) para empresas que possuem prestadores de serviços externos.

Entregamos controle, organização e melhor relacionamento com o cliente para empresas de Climatização, Segurança eletrônica, Telecom, Provedores de internet, Montadoras de móveis, Empresas de limpeza, enfim, qualquer empresa que possui uma equipe de campo para realização de serviços.

Nossa missão é melhorar a prestação de serviços no Brasil.

Te convido a conhecer um pouco mais da Field e da nossa **cultura** pelo nosso instagram: [@FieldControlApp](https://www.instagram.com/fieldcontrolapp/)

Um ponto importante é que a Field foi fundada por desenvolvedores, só por esse motivo você pode TER CERTEZA que aqui as coisas são muito diferentes das empresas tradicionais.

Aqui utilizamos **princípios ágeis DE VERDADE** para criação de software. Veja bem, não estou falando de post its ou reuniões em pé.. E sim de: Pair programming, Continuous Integration, Continuous Deployment e claro, testes automatizados.

Queremos a cada dia mais flexibilidade e continuar animados a evoluir nossas aplicações.

Nosso trabalho é baseado em autogestão. Só existe uma regra de convivência: É proibido murmurar! Aqui as opiniões são discutidas, resolvidas e sempre chegamos a um consenso para melhorar a nossa convivência. Isso não foi descrito por um gerente de RH e sim por um desenvolvedor de software.

## Descrição da vaga

Estamos em busca de desenvolvedores Front-end **FODAS** e **APAIXONADOS** para fazer parte do nosso time de produto.

Na Field, o seu dia-a-dia será repleto de:

```javascript
[
  'GitHub & Git <3',
  'Muito, muito e muito JavaScript',
  'Object-oriented programming, SOLID Principles & Design Patterns',
  'Práticas e princípios ágeis (Pair programming, Continuous Integration, Continuous Deployment)',
  'Testes de software (unitários, integração, e2e..)',
  'Desafios de escalabilidade',
  'Desafios de alta disponibilidade',
  'Micro services e aplicações distribuídas',
  'Amazon Web Services',
  'PAAS & Cloud Services',
  'Serverless apps',
  'AngularJS, Angular',
  'REST APIs',
  'GraphQL APIs',
  'Material Design',
  'Open source software'
]
```

Nossa stack é praticamente toda em JavaScript: Node.js, SPA's e Hybrid Mobile Apps.

Acreditamos que bons desenvolvedores usam a melhor ferramenta para cada problema, então, para resolver alguns problemas bem específicos usamos a melhor alternativa disponível, por isso, temos uma pitada de C#, Java e PHP também.

Nossos servidores estão na AWS e usamos a núvem como plataforma. Temos apps rodando no Elastic BeanStalk, S3 e Serverless na AWS Lambda :)

Antes do conhecimento técnico, temos preferência pelo perfil pessoal. Ou seja, se você for esforçado, interessado e curioso.. é isso que importa pra a gente! :)

## Local

Exemplo: Remoto ou Escritório em São José do Rio Preto

Trabalhamos com uma boa infraestrutura e possuímos um ambiente de trabalho agradável:

<p float="left">
  <img src="https://raw.githubusercontent.com/FieldControl/valinor/master/field3.jpeg" width="210"/> 
  <img src="https://raw.githubusercontent.com/FieldControl/valinor/master/field1.jpeg" width="370"/>
  <img src="https://raw.githubusercontent.com/FieldControl/valinor/master/field4.jpeg" width="210"/> 
</p>

Com essa questão da pandêmia, adotamos o HomeOffice e a ida para o escritório é opcional.

É uma pena pq sempre que a Field bate meta (quase sempre) o frigobar fica assim:

<p>
  <img src="https://raw.githubusercontent.com/FieldControl/valinor/master/frigobar-da-field-quando-meta-eh-batida.jpeg" width="400" /> 
</p>

## Requisitos

 - P R O A T I V I D A D E
 - Sentimento de DONO
 - Boa comunicação e trabalho em equipe :)
 - Proficiência em JavaScript e Typescript 
 - Experiência com CSS e HTML Semântico
 - Experiência sólida com Angular e Ionic
 - Familiaridade com princípios de UX
 - Familiaridade com APIs REST, GraphQL e WebSockets
 - Ter prática em testar software!

## Benefícios

Alimentação, Plano de saúde, Seguro de vida, conta Pluralsight <3

## Como se candidatar

Faça o desafio que está no link: https://github.com/FieldControl/valinor :blue_heart: 

#### Alocação
- Remoto ou presencial (você escolhe)

#### Regime
- CLT
- Freela
- PJ

#### Nível
- Especialista
- Sênior
- Rock star
- GOD
- DEUS

**Comment by JMustang** [comment]
o animo de você me motivou tanto que eu tenho que pergunta. tem espaço para frontend junior??? EhEhEhEEH

**Comment by lfreneda** [comment]
> o animo de você me motivou tanto que eu tenho que pergunta. tem espaço para frontend junior??? EhEhEhEEH

@JMustang sendo bem sincero, pra essa posição atual queremos uma pessoa experiente, mas é sempre bom ter contato com outras pessoas. 

Então, a sugestão é que você faça o teste sim. O máximo que vai acontecer é você praticar e eventualmente aprender alguma coisa nova, não é mesmo? 

Aguardo seu teste.

Grande abraço,

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by lfreneda** [comment]
@felipefialho Estamos com a posição em aberto! Alias, mais de uma vaga :heart:

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
