### ISSUE TITLE
[Remoto] Front-end Developer na Somos Educação

### ISSUE THREAD

**Issue by andregaldino** [frontendbr/vagas#3537]
## Nossa empresa

A Somos Educação é um dos principais grupos de Educação Básica do Brasil e fazemos parte do Grupo Cogna que com mais de 50 anos de atuação, é uma das maiores empresas do setor de educação do mundo!

Oferecemos um amplo portifólio de soluções educacionais como sistemas de ensino, editoras, além de uma tecnológica plataforma de aprendizado digital e de e-commerce.

Há pouco tempo, fizemos nossa estreia na Nasdaq, Bolsa de Valores norte-americana.

Este passo nos orgulha muito pelo reconhecimento de sermos a terceira empresa brasileira de #educação listada na Bolsa de Valores Nasdaq; e, principalmente, por nos permitir ampliar nossos serviços de apoio à #escola!

## Descrição da vaga

Engenheiro(as) front-end apaixonado(a)s para nos ajudar a melhorar a educação no Brasil!

A Somos tem vários produtos, mas a vaga é para atuar no time Digital, especificamente no produto Plurall.

## Local

Remoto

## Requisitos

Programação Front-end (SPA) que comunicam com API (Rest e GraphQL)
Metodologias de desenvolvimento ágil
Mobile First
Componetização da Biblioteca de Design Sytem (React + Emoction + NPM/Yarn) (9 aplicações usando os componentes)

**Obrigatórios:**
- JavaScript (vanilla)
- React
- HTML e CSS
- NPM (usamos para pacotes internos privados/públicos)
- Ter opinião na hora de planejar/arquitetar features/soluções

**Diferenciais:**
- Noções de UX/UI
- Angular (as vezes temos que resolver algo no sistema de account)

## Contratação

CLT

## Como se candidatar

Clique [Aqui](https://jobs.kenoby.com/somos/job/somos-desenvolvedor-frontend/5f905a3b9525fc7a53b9eb62) para se candidatar

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by herbertcordeiro** [comment]
Enviado ^^

**Comment by victorbadaro** [comment]
Curriculo enviado 🙂

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by andregaldino** [comment]
Olá @felipefialho  está sim, só irei atualizar o link para se cadastrar
