### ISSUE TITLE
[Remoto / Valinhos/ Londrina] Desenvolvedor/a FullStack na Platos

### ISSUE THREAD

**Issue by rodriguesvini** [frontendbr/vagas#3538]
A Platos é a mais nova startup do grupo Cogna Educação, a segunda maior empresa voltada à educação do mundo, e atende o mercado B2B do Ensino Superior. Seguindo o conceito de EdServ Platform (plataforma de serviços educacionais), a Platos oferece uma série de serviços e soluções digitais completas para as instituições de ensino superior (IES) de todo o país. Movida pela inovação e pelo propósito de transformar a vida das pessoas por meio de uma educação libertadora e de qualidade, a Platos atende a mais de 200 instituições e está expandindo exponencialmente sua rede de parcerias!

**(Link da página das oportunidades no final ↓)**

### Para este desafio, estamos buscando:
• Java (8 ou superior desejável);
• Spring Boot/Micronaut;
• API Restful;
• GIT;
• Javascript ES6, HTML 5 e CSS 3;
• React;
• Bancos de dados relacionais e/ou não relacionais (PostgreSQL ou MongoDB desejável);

### Serão considerados diferenciais:
• Gradle;
• Kubernetes;
• React Native;
• Redux;
• Design System (para Especialista);
• Prototipação de Interfaces (para Especialista).

### Contratação:
A contratação será feita em regime CLT, com remuneração compatível aos níveis Pleno, Sênior ou Especialista e no modelo de atuação Remoto (100% home office) ou presencial em Valinhos (SP) ou Londrina (PR). Para as pessoas que optarem pelo modelo presencial, a atuação acontecerá no modelo remoto (home office) enquanto durar a pandemia, até quando for seguro retornar às atividades presenciais.

### Benefícios:
Além de uma oportunidade de Carreira, desenvolvimento profissional e pessoal, a empresa oferece:
•  Programa de Participação nos Resultados – PRV;
•  Assistência Médica e Odontológica;
•  Vale Alimentação/Refeição em Londrina e Restaurante em Valinhos;
•  Vale Transporte;
•  Seguro de Vida;
•  Bolsa Estudantil (em Valinhos extensiva a dependentes).

**Para mais informações da oportunidade e participar do processo com a gente, é só acessar: https://bit.ly/3gLutxl**

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
