### ISSUE TITLE
[Palhoça/SC] Angular + PHP Developer na Essentia Technologies

### ISSUE THREAD

**Issue by brunoricardore** [frontendbr/vagas#3539]
## Nossa empresa

Somos uma empresa que desenvolve soluções web para médicos e nutricionistas, e precisamos complementar nosso time de devs

## Descrição da vaga

Nos usamos atualmente, Angular como nosso principal framework front-end, PHP e NodeJS no backend,
usamos MySQL e MongoDB como banco de dados, você tem conhecimento dessa stack, favor entre em contato conosco!

## Local

Nosso escritorio fica em SC, Palhoça, Pedra Branca

## Requisitos

**Obrigatórios:**
- Conhecimentos em Angular
- PHP
- MySQL

**Desejáveis:**
- NodeJS 
- MongoDB
- Scrum
- Agile
- Jira

**Diferenciais:**
- Aqui usamos uma técnica de sempre nos questionar sobre os recursos, usamos um método diferente de gerenciamento de equipe para evitarmos burocracias e mudanças, usando o agile ao máximo.

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ X/dia
- Auxílio creche
- ...

## Contratação

CLT

## Como se candidatar

Enviar um email para bruno.ricardo@essentia.com.br com seu CV anexado - enviar no assunto: Vaga Angular Dev, resolvendo o seguinte teste: https://bitbucket.org/easy-health/fullstack-test/src/master/

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
