### ISSUE TITLE
[São Paulo] Fullstack Developer no Cubo

### ISSUE THREAD

**Issue by LFeh** [frontendbr/vagas#354]
## Fullstack Developer na plataforma digital do Cubo

Nossa missão é inspirar, educar e conectar pessoas brilhantes para fomentar o empreendedorismo digital no Brasil.

Estamos criando o "Cubo Digital", uma plataforma que tem como propósito entregar o mesmo valor que o Cubo Coworking oferece aos residentes de maneira expandida "digitalmente" a outras startups do mercado, ou seja, conectar empreendedores com empreendedores, com universidades, com talentos, com investidores, com grandes empresas e todos os outros atores que acercam este ecossistema e geram densidade ao empreendedorismo e inovação.

Seu maior desafio será desenvolver e manter as features desta plataforma junto aos demais do time: desenvolvedores back-end, front-end, designers e UX.
Estamos com a oportunidade de fazer algo do zero e não temos legado, raro isso, não? 
Para tanto, precisamos de um "killer" em javascript, alguém que respire ES6, Node.js e que corra tecnologias de SPA na veia como Angular2, React.js, etc.

## Local

São Paulo - Vila Olímpia, Cubo

## Benefícios

- Salário competitivo
- Vale Refeição
- Vale Alimentação
- Plano de Saúde 
- Plano Odontológico
- Seguro de Vida
- Participação nos lucros (de verdade)
- Trabalhar no Cubo: Ambiente descontraído, colaborativo e divertido.
- Trabalhar com o @danilodevhub, comigo e mais um monte de pessoas legais 😄

## Requisitos

- Concluir o teste que está em nosso [GitHub](https://github.com/cubonetwork/fullstack-challenge)
- Superior Completo;

### Conhecimentos em Front-End:
- HTML e CSS
- Conhecimento em um ou mais frameworks SPA (Angular 1, Angular 2, React.js, Ember, etc)

### Conhecimentos em Back-End:
- Javascript, ECMAScript 6
- Node.js & Express
- APIs Restfull
- Frameworks de teste: Mocha, Chai

### Diferencial:
- Arquitetura Cloud Native;
- Conhecimentos de AWS (Gateway API, Functions Lambda, SNS, S3)

## Contratação

CLT

## Como se candidatar

Faça nosso teste no [GitHub](https://github.com/cubonetwork/fullstack-challenge) e envie um pull-request privado, publico ou até mesmo envie por email 😊

Link da aplicação: https://cubo.network/jobs/d69815f0-4aca-11e7-bfed-2930c9251a9d

**Comment by mateussmohamed** [comment]
@LFeh tudo bom? é necessário para vaga o curso superior completo?

**Comment by LFeh** [comment]
Opa @mateussmohamed, beleza?

Infelizmente é necessário.

Somos registrados como funcionários do Banco Itaú, e isso é um requisito.

**Comment by mateussmohamed** [comment]
Tranquilo @LFeh 👍 

Vou fazer o desafio pra treinar 😄

**Comment by WandersonAlves** [comment]
Não aceita remoto né? 😢

**Comment by LFeh** [comment]
@WandersonAlves apenas presencial

**Comment by mtmr0x** [comment]
@LFeh a vaga esta aberta ainda?

**Comment by LFeh** [comment]
Aberta 🗡

**Comment by LFeh** [comment]
Done ;)
