### ISSUE TITLE
[São Paulo ou Remoto] Front-end Developer Pleno na Vizir

### ISSUE THREAD

**Issue by marceloeferro-vizir** [frontendbr/vagas#3540]
## Nossa empresa
A Vizir tem 10 anos de vida, trabalhamos desenvolvendo projetos sob medida para nossos clientes e gostamos que as pessoas fiquem por bastante tempo conosco.

## Descrição da vaga
- A vaga é para pessoas com experiência em programação. Por isso colocamos pleno. Mas dentro do nosso time, no dia-a-dia, não usamos muito esta terminologia.
- No cenário de pandemia, estamos todos remotos. Mas nosso escritório está no centro de SP, na República. Temos vagas para que no futuro sejam remotos ou presenciais.
- Temos vagas abertas em projetos mais front-end, tanto React como ReactNative. Mas embora seja mais para o front-end, gostamos que seja um front sem medo de API, do back-end. Mais do que conhecimento específico em uma plataforma queremos que seja uma pessoa que goste de programar, de fazer testes unitários e de fazer software bem feito!
- Temos projetos em React, ReactNative e projetos que envolvam ambas as tecnologias.

Para conhecer mais sobre a vaga e [um pouco da Vizir](https://vizir.com.br/2019/08/venha-fazer-parte-da-vizir-estamos-contratando/).

## Local
No momento e por mais um bom tempo ficaremos 100% remotos. Nosso escritório fica no centro de SP (República), mas cerca de 30% do nosso time de 117 pessoas já trabalhava remoto antes da pandemia.

## Requisitos
- Conhecer bem uma linguagem de programação, boa lógica e orientação a objetos.
- Estar a fim de aprender.
- Ser comprometido em entregar projetos com qualidade.
- Curtir entregar um front bonito e bem desenvolvido hehe...
- Bons conhecimentos de React ou ReactNative são importantes, mas se tiver mais experiência com outros frameworks e quiser trabalhar com React, é bem-vindo.

**Desejáveis:**
- Ter experiência com práticas ágeis.
- Bons conhecimentos de teste

## Benefícios
- Vale Refeição pago em dinheiro.
- Plano de saúde SulAmérica, com acesso a uma boa rede de hospitais e quarto individual;
- Plano odontológico Odontoprev;
- Seguro de Vida no valor de R$ 60.000,00.
- Ambiente bacana para trabalhar e auxílio a montar seu home office (um computador para chamar de seu e auxílio cadeira).

## Contratação
CLT ou PJ, como preferir.

## Como se candidatar
[Pode se candidatar no link](https://recruiterflow.com/vizir/jobs/12?source=FrontEndBR)

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: queroentrar@vizir.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno

**Comment by RafaPalau** [comment]
Pena não tem uma vaga para Junior. Parece legal trabalhar ai com vocês.

**Comment by vimaciel** [comment]
Aplicado, vou ficar no aguardo.

Obrigado @marceloeferro-vizir

**Comment by GabrielModog** [comment]
Não consigo me candidatar pelo link.

**Comment by marceloeferro-vizir** [comment]
> Pena não tem uma vaga para Junior. Parece legal trabalhar ai com vocês.

Bom dia Rafa,
Tudo bem? Estamos em um momento legal aqui na Vizir. Acompanhe a gente nas nossas redes sociais que sempre postamos nossas vagas lá

Abraços

**Comment by marceloeferro-vizir** [comment]
> Aplicado, vou ficar no aguardo.
> 
> Obrigado @marceloeferro-vizir

Obrigado Vinicius, 
Boa sorte

**Comment by marceloeferro-vizir** [comment]
> Não consigo me candidatar pelo link.

Bom dia Gabriel,
Tudo bem?

Apareceu algum erro? Poderia nos enviar mais informações para conseguir ajudá-lo?

**Comment by GabrielModog** [comment]
> > Não consigo me candidatar pelo link.
> 
> Bom dia Gabriel,
> Tudo bem?
> 
> Apareceu algum erro? Poderia nos enviar mais informações para conseguir ajudá-lo?

Diz que eu já enviei, realmente já havia enviado antes, tipo meses atrás...

**Comment by vimaciel** [comment]
> > Aplicado, vou ficar no aguardo.
> > Obrigado @marceloeferro-vizir
> 
> Obrigado Vinicius,
> Boa sorte

Olá @marceloeferro-vizir realizei o teste técnico. 
Fico no aguardo de novas orientações.
Obrigado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
