### ISSUE TITLE
[São Paulo ou Remoto] Front-end Developer na follow55

### ISSUE THREAD

**Issue by FelipeMarcos** [frontendbr/vagas#3541]
## Descrição

Um estúdio criativo especialista na criação e desenvolvimento de projetos digitais. Somos independentes e estamos em uma incansável busca por inovação. Estamos em constante crescimento e buscamos um(a) Front-End para integrar no nosso time.

Procuramos alguém comprometido(a), autodidata e principalmente, que queira crescer junto com a gente.

Valorizamos cada integrante do nosso time.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- HTML5, CSS3;
- Pré-processadores CSS;
- JavaScript;
- Vue.js;
- Node.js;
- Git;
- Proatividade.

**Desejáveis:**
- React;
- React Native;
- Noções de UX Design;
- Gostar de inovação, estar por dentro de tendências;
- Disposto a trabalhar com pessoas de perfis diferentes.

## Benefícios
- Horário flexível
- Bônus por desempenho

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para felipe@follow55.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Developer

Vagas: 2

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
