### ISSUE TITLE
[Remoto] Customizar Rocket.chat  na Finata

### ISSUE THREAD

**Issue by wilsonpilar** [frontendbr/vagas#3542]
## Nossa empresa

Somos uma empresa de soluções para o mercado de crédito

## Descrição da vaga

Criação de novas features para um fork do projeto https://github.com/RocketChat/Rocket.Chat

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência em desenvolvimento front/back
- Ter trabalhos desenvolvidos com o projeto rocket.chat

**Desejáveis:**
- Meteor

**Diferenciais:**
- projetos opensource

**Diferenciais:**
- Liberdade e autonomia

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para wilson@afinata.com com informações informais sobre seu trabalho

## Tempo médio de feedbacks

Respondo na hora

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
