### ISSUE TITLE
[Remoto] Front-end Developer na Hostgator

### ISSUE THREAD

**Issue by Vagas-HunterCo** [frontendbr/vagas#3544]
> Vaga Remota durante a pandemia

## Nossa empresa

A HostGator faz parte do grupo Endurance International, uma companhia de capital aberto que atua globalmente no mercado de web hosting. Com faturamento anual próximo a 1,2 bilhões de dólares, atendendo ao todo cerca de 4,8 milhões de pessoas, cada vez mais caminhamos para um mundo em que garantir uma presença online não precisará ser algo difícil e demorado.

Aqui somos apaixonados por fazer com que produtos e serviços possam inovar, gerar valor e também criar oportunidades aos nossos clientes. Para isso, contamos com os Gators - como chamamos nossa equipe - diariamente engajados em compreender mais sobre nosso público, otimizar sua jornada, experiência e também oferecer o melhor serviço! Hoje já são milhares de pessoas que confiam em nosso trabalho, tanto no Brasil quanto na América Latina.

## Descrição da vaga

Nosso time utiliza metodologia de desenvolvimento ágil e foca no aprendizado contínuo. Nosso ambiente é aberto e colaborativo.
Procuramos uma pessoa que seja aberta a mudanças, ansiosa para ensinar profissionais menos experientes, goste de interagir e comunicar-se com pessoas e tenha características de liderar equipe e projetos.
Nosso objetivo é que você seja a referência em Front-End, determine os caminhos que serão tomados e capacite os profissionais menos experientes 

## Local

Remoto ou Escritório, Santa Catarina, Florianópolis, Trindade

## Requisitos

**Obrigatórios:**
Profunda experiência com React / Redux;
Experiência com arquitetura, performance, responsividade, escalabilidade e qualidade de SPAs (single-page applications);
ESLint;
Git / Git Flow;
Domínio em JavaScript / ES6 +, HTML5, CSS3;
Conhecimento em análise de requisitos e APIs REST;
Inglês fluente ou avançado;

**Desejáveis:**
Experiência com a cultura e metodologias ágeis;
Experiência com teste unitários;
Docker;
AWS Cloud;
Experiência com BDD;
Conhecimento de ferramentas Atlassian (JIRA, Bamboo, Confluence, Stash);

**Diferenciais:**
Continuous Integration;
Continuous Delivery;
Formação na área de Ciência da Computação ou afins, Inglês avançado;

## Benefícios
Possibilidade de trabalho home office (garantido até junho/2021);
Fornecemos toda a infra estrutura de TI e ajuda de custo ($) para o trabalho remoto;
Plano de Saúde e odontológico subsidiado pela empresa;
Vale alimentação/refeição;
Parcerias com descontos em academia, restaurantes, universidades e escolas de idiomas;
Presente especial no dia do aniversário;
Ginástica Laboral/Meditação online;
Happy hour mensal online;
Pessoas de diversos pontos do Brasil e da América Latina, para promover ainda mais nossa cultura de diversidade;

**Diferenciais:**

## Contratação

CLT

## Como se candidatar

Por favor acesse esse link e aplique-se: 
https://vagas.hunterco.com.br/job/5f3c607cdcd904001b220ba5?r=frontendbr

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: sabrina.tomio@parceirohunterco.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
