### ISSUE TITLE
[Remoto] Full-Stack Javascript developer (React/React Native/Node) na Ruptiva 

### ISSUE THREAD

**Issue by maikelfb** [frontendbr/vagas#3548]
# Nossa empresa
A Ruptiva desenvolve soluções personalizadas de acordo com a necessidade de nossos clientes. Cada aplicativo ou sistema é desenhado especificamente para cada negócio. Já trabalhamos com projetos nos mais variados segmentos, dentre eles no ramo de transporte, indústria, varejo e meios de pagamentos. Desde o desenho até o desenvolvimento, passamos por uma jornada bastante dinâmica de aprendizado contínuo da equipe. 

## Modalidade
Remoto

## Regime
PJ

## Requisitos
- Pelo menos 2 anos de experiência em posição similar
- React / React Native
- Typescript
- Redux
- Node.js / Express
- API Rest
- SQL
- Controle de versão
- Trabalho em equipe
- Comprometimento
- Responsabilidade
 
## Diferenciais
- Docker
- Firebase
- Metodologias Ágeis
- GraphQL
- Microservices
- Integração de serviços
- Heroku
- AWS
- Google Cloud Platform
- PostgreSQL
- NoSQL

## Como se candidatar
Envie um e-mail com seu CV, links de projetos online e pretensão salarial para maikel@ruptiva.com com o assunto: `Vaga Full-Stack Javascript - ${Seu nome aqui}`

## Tempo médio de feedbacks
Costumamos enviar feedbacks o mais breve possível após cada processo.

## Labels
- PJ
- Pleno
- Salário compatível
- Remoto
- Flexibilidade
- Aprendizado contínuo
- Desafios motivadores
- Sem estagnação

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
