### ISSUE TITLE
[São Paulo] Fullstack Developer (Node.JS)

### ISSUE THREAD

**Issue by Dani-Ventron** [frontendbr/vagas#355]
Fullstack Developer (Node.JS)
==================================================
-->

Sólidos conhecimentos em:
•	Node.JS
•	Angular
•	Bootstrap
•	MVC
•	Git
•	Metodologias ágeis

## Local: São Paulo

Escritório, São Paulo - Barra Funda

## Requisitos

**Obrigatórios:**
•	Node.JS
•	Angular
•	Bootstrap
•	MVC
•	Git
•	Metodologias ágeis

**Diferenciais:**
Programação .Net

## Contratação

PJ a combinar

## Nossa empresa

A VENTRON é especialista em soluções que simpliﬁcam processos com inteligência e foco no resultado.

## Como se candidatar

Por favor envie um email para daniele.silva@ventron.com.br com seu CV anexado - enviar no assunto: Vaga NodeJS

**Comment by Dani-Ventron** [comment]
Olá pessoa, aceito indicações. Muito obrigada!

**Comment by mtmr0x** [comment]
@Dani-Ventron a vaga continua aberta?

**Comment by LFeh** [comment]
Aberto ainda?
