### ISSUE TITLE
[Porto Alegre] Senior Front-End Developer na Appmax

### ISSUE THREAD

**Issue by RHAppmax** [frontendbr/vagas#3551]
> Vaga Remota durante a pandemia

## Nossa empresa

A Appmax respira tecnologia, e por isso nossa área tech trabalha incessantemente para garantir a entrega de valor ao nosso parceiro. Esse time é responsável por fazer a manutenção e o desenvolvimento da nossa plataforma, garantindo a qualidade e oferecendo aos nossos parceiros a melhor experiência ao utilizar os nossos serviços. Contamos com excelentes profissionais que trabalham fazendo melhorias e trazendo soluções criativas para as demandas recorrentes da plataforma.

## Descrição da vaga

Usar o melhor em desenvolvimento de software aliado a boas práticas de design;
Desenvolver código limpo, eficaz, escalável, legível e de fácil manutenção para as interfaces;
Participar dos processos criativos da nossa plataforma, dando suporte no que tange a viabilidade técnica de desenvolvimento de novas features e interfaces;
Otimizar as aplicações para a sua melhor performance e eficiência;
Trazer sua visão e experiência para a equipe de desenvolvimento.

## Local

Exemplo: Escritório, [RS], [Porto Alegre], [Centro]

## Requisitos

**Obrigatórios:**
- Ensino superior completo ou em andamento em cursos relacionados a tecnologia da informação;
- Experiência com JavaScript, HTML e CSS.

**Desejáveis:**
- Uma busca constantemente de conhecimento sobre novas práticas de desenvolvimento, ferramentas e processos que melhorem a performance e usabilidade da nossa plataforma;
- Bastante senso crítico orientado ao mais alto padrão de qualidade.
- Paixão e brilho nos olhos por tecnologia;
- Muita vontade de crescer.

**Diferenciais:**
- Experiência com plataformas de e-commerce;
- Experiência em trabalhar com eventos e filas;
- Interesse em compartilhar ideia e criar soluções coletivamente;
- Flexibilidade para trabalhar em um ambiente volátil com demandas constantes.

## Benefícios

- Contratação remota durante o período de enfrentamento da pandemia;
- Todos os equipamentos e recursos necessários para você trabalhar da sua casa;
- Ajuda de custo para internet, luz ou outros gastos;
- Vale alimentação para você utilizar no mercado.
- Horários Flexíveis.

## Contratação

CLT

## Como se candidatar

Por favor envie um email para carolina.rohde@appmax.com.br ou candidatar-se no link https://appmax.com.br/carreiras/ 

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
