### ISSUE TITLE
[REMOTO] Vaga de Estágio como Frontend Developer (em ReactJS) na VISOR

### ISSUE THREAD

**Issue by leoronne** [frontendbr/vagas#3552]
## Nossa empresa

A VISOR é uma Fintech que atua no Brasil e no México, visamos ajudar as PMEs nos seus caminhos em direção à estabilidade e um futuro bem sucedido.

Nosso trabalho é tão desafiador quanto satisfatório. Por isso buscamos profissionais excepcionais, que se caracterizem por serem proativos, colaborativos e responsáveis, mas que, sobretudo, estejam obcecados em criar valor para os usuários.

Sabemos que transformar o ecossistema empresarial em nosso país requer soluções tecnológicas disruptivas e inovadoras. Temos o apoio de fundos de investimento de grande renome como IGNIA, American Express Ventures, Bluerun Ventures, Leap Global Partners, ALL VP e 500 startups que apostaram na nossa missão: empoderar as PMEs na sua luta por sobreviver, crescer e prosperar, fazendo nosso melhor esforço para traduzir seus dados em acesso à produtos financeiros.

Se você é Desenvolvedor Frontend (ou quer trilhar seu caminho nessa área), tem proatividade, vontade de fazer acontecer, o seu lugar é conosco! Sendo parte do time, você terá os desafios e reconhecimentos que você precisa para dar o próximo passo na sua carreira.

## Descrição da vaga

- Desenvolvimento de aplicações web responsivas com ReactJS, consumindo web services e baseadas em layouts feitos por nosso time de UX/UI;
- Participar de etapas de ideação, planejamento e desenvolvimento de nossos produtos;
- Desenvolvimento de novas funcionalidades nas aplicações web;
- Ser curioso e estar disposto a se arriscar;
- Disposição para ajudar e compartilhar conhecimento.

## Requisitos

**Obrigatórios:**
- Conhecimento em Javascript e/ou frameworks relacionados (ReactJS);
- Conhecimento em integração com APIs;
- Conhecimento em HTML e CSS.

**Desejáveis:**
- Conhecimento em versionamento com Git;
- Habilidades em padrões de design de interface e experiência de usuário;
- Boa conversação em Espanhol.

## Local

Remoto.

## Benefícios

- Home office;
- Vale refeição;
- Horários flexíveis.

## Como se candidatar

Por favor envie um email para leonardo.deoliveira@visor.io com seu CV anexado - enviar no assunto: Vaga de Estágio para Frontend Developer.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Remoto.

#### Regime
- Estágio.

#### Nível
- Estágio.

**Comment by grsantos2215** [comment]
Currículo enviado.

**Comment by lucasbeliene** [comment]
currículo enviado.

**Comment by PedroGomes1** [comment]
Currículo enviado.

**Comment by AngeloBonini** [comment]
currículo enviado.

**Comment by cp-yago** [comment]
Tenho bastante interesse, precisa estar cursando graduação? (Já me formei mas quero mudar para essa área.)

**Comment by GabrielCastro17** [comment]
currículo enviado.

**Comment by advaner** [comment]
Currículo enviado.

**Comment by sandra-source** [comment]
Currículo enviado.

**Comment by helio17** [comment]
Currículo enviado

**Comment by GustavoCarvalhoRodrigues** [comment]
Currículo enviado

**Comment by m-santos-nepo** [comment]
Enviado

**Comment by danieltinois** [comment]
Currículo enviado
