### ISSUE TITLE
[REMOTO] Full Stack Developer no Plugg.to

### ISSUE THREAD

**Issue by fabriciovieira** [frontendbr/vagas#3553]
## Nossa empresa
Plugg.To é um hub de integração de e-commerce que possibilita integrações rápidas e inteligentes entre plataformas de lojas virtuais, ERPs, Fornecedores e Marketplaces. Diversas ferramentas de automações são oferecidos pelas integrações para possibilitar que tarefas repetidas em um Marketplace específico sejam realizadas sem interferência manual.

A empresa, fundada no início 2013 recebeu investimento da Wayra e do Fundo de investimento MercadoLivre no início de 2015 e desde então não para de crescer.

## Descrição da vaga
Estamos buscando um(a) profissional de FullStack para compor nosso time de desenvolvedores. O(a) profissional vai participar junto com os times de produto e desenvolvimento back-end na evolução das interfaces atuais e construção dos novos produtos web e mobile.

É imprescindível o conhecimento em boas práticas para desenvolvimento web, Vue.js e integração de APIs.

## Local
Remoto

## Requisitos
**Obrigatórios**
* Front-End: Vuejs, jQuery
* Back-End: PHP (Laravel), Node.js – servidor Express;
* Banco de Dados: MySql e MongoDB

**Desejáveis:**
* Conhecimentos em React Nativo ou outro framework para desenvolvimento mobile;
* Experiência com computação em Cloud/Nuvem;
* Experiência com microsserviços e ambientes de alta performance/disponibilidade;

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para fabricio.vieira@plugg.to com seu CV anexado - enviar no assunto: Vaga FullStack Developer

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
