### ISSUE TITLE
[São Paulo – (SP)] [Engineer Lead Especialista na Creditas]

### ISSUE THREAD

**Issue by Victorsantanass97** [frontendbr/vagas#3556]
**Somos a principal plataforma online de crédito com garantia do Brasil** e trabalhamos com quatro produtos principais: empréstimo com garantia de imóvel e veículo, empréstimo consignado privado e o financiamento de veículo. Nossa missão é viabilizar as novas conquistas dos brasileiros multiplicando o potencial dos seus bens.

**O desafio é para ser Engineer Lead Especialista na Creditas**, sendo responsável por gerenciar uma equipe de alta performance, desenvolver Devs e Tech Leads, construir e implementar visão técnica de produtos e negócios, realizar alinhamento de entregas de delivery com stakeholders, garantir que os resultados definidos serão alcançados, trabalhar em um ambiente ágil, apoiado em métricas e focado em resultado.

**Se interessou?** O que você precisa saber para vir com a gente nesse desafio: Experiência prévia em gestão de times multidisciplinares de desenvolvimento de software; Conhecimento técnico para tomadas de decisão que garantam o output e alta capacidade técnica das soluções e do time; Experiência com metodologias ágeis; Capacidade de trabalhar em um ambiente multifuncional, multi-linguagem e colaborativo, de maneira autônoma; Pragmatismo para resolução de problemas.

**Contratação CLT.**

Vem fazer parte: https://byintera.in/credelsr

**Comment by felipefialho** [comment]
@Victorsantanass97 Por favor adiciona a [vaga dentro do template](https://github.com/frontendbr/vagas/blob/main/.github/ISSUE_TEMPLATE/adicionar-nova-vaga.md)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
