### ISSUE TITLE
[Remoto] Front-end Developer na Nextly

### ISSUE THREAD

**Issue by ggoncales** [frontendbr/vagas#3557]
A Nextly está com processo seletivo aberto para quem domina HTML!
Somos uma empresa que atua com engenharia e desenvolvimento de software para clientes internacionais. Atuamos com projetos como o portal web da Olimpíada Juvenil de Inverno na Suíça, portal da ONU Noruega, portal do Ministério da Saúde, Federação de Futebol da Noruega, dentes outros.

## Sobre a vaga:
- Remoto
- Temos 3 modalidades de contratação: PJ, Cooperativa ou CLT.

## Requisitos:
- Domínio com HTML5, CSS3, Bootstrap, Photoshop e Illustrator;
- Será um diferencial se tiver prática com SASS, Gulp e Javascrip. 
- **Inglês avançado**.

## Como se candidatar:
Envie um email para gabriela.goncales@nextly.team com seu CV anexado - enviar no assunto: Frontend Developer.

Ou me chamar no [LinkedIn](https://www.linkedin.com/in/gabriela-gon%C3%A7ales/).

# Labels

- 🏢 Remoto
- 👴 Sênior
- ⚖️ Cooperativa
- ⚖️ CLT
- ⚖️ PJ
- 💰 Pretensão salarial

**Comment by krivax** [comment]
aff esse inglês avançado me tira dessa candidatura

**Comment by pauladiniz** [comment]
Apliquei! :)
