### ISSUE TITLE
[Remoto] Front-end Developer na Carupi

### ISSUE THREAD

**Issue by dcsdarlan** [frontendbr/vagas#3558]
## Carupi

Nossa missão é revolucionar o mercado de compra e venda de automotores e estamos num momento de expansão. Contamos com um time 100% remoto e ativo.

## Sobre a Vaga

- Remoto
- Nível Pleno

## Requisitos

**Obrigatórios:**
- Conhecimentos em React

**Desejáveis:**
- Conhecimentos em Gatsby
- Conhecimentos em Next

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para darlan.sousa@carupi.com com seu CV anexado - enviar no assunto: Vaga Frontend.

Favor enviar pretensão salarial.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by pedrolucasD** [comment]
Enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
