### ISSUE TITLE
[Morumbi/SP] Desenvolvedor(a) React Pleno na Confitec

### ISSUE THREAD

**Issue by DaiannaCs** [frontendbr/vagas#3559]
### **Local de trabalho:**
Atuação remoto durante a pandemia. Após COVID, retornaremos para o escritório que fica no Morumbi (próximo do Shopping e trem do Morumbi).

### **Empresa**
Somos especialistas em softwares voltados ao mercado segurador. Estamos ajudando a impulsionar a transformação no setor de seguros no Brasil. Estamos presentes em São Paulo e Rio de Janeiro, duas das principais capitais do país.
Você fará parte de um time de desenvolvedores extremamente qualificado fortemente orientado a resultados e que não tem medo de inovar.
Você será parte vital no desenvolvimento da nova plataforma de um de nossos principais clientes, trabalhando com boas práticas de desenvolvimento em um ambiente dinâmico que incentiva a autonomia e o aprendizado constante.
Estamos crescendo e precisamos de pessoas que amem tecnologia e que sejam fascinadas por aprender!

### **Responsabilidade e atribuição:**
Desenvolvimento de sistemas.

### **Requisitos:**
React + Redux
Sólido conhecimento em HTML e CSS
JavaScript Avançado (ES6 + ES7)
Familiaridade com APIs RESTFull

### **Seria fantástico se o seu background tivesse:**
GIT.
Web API’s.
AWS.
SASS
Metodologia BEM CSS
Conhecimento em metodologia ágil.
Material-UI

### **Benefícios**
• Plano de saúde.
• Plano odontológico;
• Vale Transporte;
• Vale-Refeição;
• Auxílio-creche;
• Incentivo a cursos e certificações;
• PLR;
• Sem dress code (Valorizamos a diversidade. Pode se vestir do seu jeito!);
• Flexibilidade de horários;
• Sala de Descompressão;
• Day off no mês do seu aniversário;

### **Contratação e como se candidatar** ✍
CLT - Salário: R$4.000,00 - R$8.000,00.
Por favor envie um e-mail para daianna.souza@confitec.com.br com seu CV anexado - enviar no assunto: Vaga React – SP e vamos responder em até 5 dias úteis 💙

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT Full

#### Nível
- Júnior
- Pleno

**Comment by pedrolucasD** [comment]
Currículo enviado!

**Comment by PedroGomes1** [comment]
Currículo enviado.

**Comment by rodolfovieira95** [comment]
Currículo enviado.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by DaiannaCs** [comment]
Boa tarde!
Pra mim aparece que encerra todas as vagas de React.
Por fabor, pode retirar esta vaga. Obrigada!

Obter o Outlook para Android<https://aka.ms/ghei36>
________________________________
