### ISSUE TITLE
[São Paulo] Front-End Developer

### ISSUE THREAD

**Issue by quesiacnogueira** [frontendbr/vagas#356]
# **Descrição da vaga**

Desenvolvedores Front-End que tenham paixão por inovação, busquem sempre as tendências do mercado e gostem de interagir e trocar experiências com o time.
Os profissionais irão atuar com sustentação e evolução da plataforma.

Imprescindível:
- Linguagens: NodeJS, Javascript;
- SASS, HTML5, CSS3
- Testes: Mockito
- Versionamento: Git (GitFlow, PR, etc)

 
Desejável:
- AngularJS, React, Dust
- Testes de Stress: Gatling;
- Trabalhar com metologia ágil: Scrum e Kanbam
- Inglês Intermediário (Leitura, Escrita e Conversação);
 

# **Sobre a Netshoes** 

Fazemos o que amamos. #tesaoporfazer
Inovamos porque não sabemos olhar para trás. #romperpadroes
A liberdade de ser mais e fazer melhor está em nossas mãos. #aquieuposso
E está na cara que conseguimos. #foconoresultado
Somos parte do negócio. #donodonegocio
Dominamos nossa rotina e agimos sem perder tempo. #rapidocomoumclick
Simples, diretos e precisos, como tem que ser. #descomplica
O resultado? Mera consequência da nossa equipe. #gentevalorizada

Como se candidatar

Para se candidatar, envie um e-mail para quesia.nogueira@netshoes.com com assunto: "[NTFront] Desenvolvedor(a) Front-end" com seu LinkedIn ou cv.

**Comment by mtmr0x** [comment]
@quesiacnogueira a vaga continua aberta?

**Comment by quesiacnogueira** [comment]
sIMMM

De: Matheus Marsiglio [mailto:notifications@github.com]
Enviada em: segunda-feira, 10 de julho de 2017 12:43
Para: frontendbr/vagas
Cc: QUESIA CRISTINA NOGUEIRA COSTA; Mention
Assunto: Re: [frontendbr/vagas] [São Paulo] Front-End Developer (#356)


@quesiacnogueira<https://github.com/quesiacnogueira> a vaga continua aberta?

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
