### ISSUE TITLE
[Remoto] Full Stack Developer (Ruby on Rails | Vue.js) na Prevision

### ISSUE THREAD

**Issue by Startec-Jobs** [frontendbr/vagas#3560]
## Descrição da vaga

A Prevision está buscando os novos desenvolvedores que farão parte da equipe de produto para contribuir com a evolução dos softwares da empresa. Se você gosta de desafios, trabalha bem em equipe e gosta de codar, essa é a vaga para você!
 
Atividades da vaga:
• Liderar projetos de alta complexidade e risco
• Seguir e questionar os padrões atuais desenvolvimento
• Disseminar e utilizar boas práticas de código
• Construção e ampliação da cobertura dos testes
• Revisar e apoiar o trabalho dos profissionais com menor conhecimento
• Desenvolvimento back-end em Ruby on Rails
• Desenvolvimento front-end em Vue.js

## Local

Remoto

## Benefícios

• Remuneração: R$6.000,00 a R$ 10.000,00

## Requisitos

**Obrigatórios:**
• Experiência avançada com Vue.js, Rect ou Angular 4+
• Experiência com uma linguagem não tipada (Ruby, Python, JavaScript)
• Conhecimento avançado em Orientação a Objetos
• Ter hábito na prática do TDD

**Desejáveis:**
• GraphQL
• Protocolo WebSocket

## Contratação

PJ 

## Nossa empresa

A Prevision veio para revolucionar o mercado da construção civil no Brasil. Uma das indústrias com maior poder de impacto socioeconômico no país, a construção civil sofre com baixa inserção de tecnologia, grandes desperdícios e pouca previsibilidade, principalmente em momentos de incertezas.

Em todos esses problemas os fundadores da startup viram uma oportunidade. A oportunidade de aliar tecnologia e auxiliar grandes construtoras a executar projetos transformadores com a maior qualidade possível.

Mas como fazer isso?

Prevision é um software de planejamento e gestão que consolida dados de performance de todos os empreendimentos em uma só tela, trazendo acompanhamento em tempo real e entendendo os diferentes cenários do planejamento com facilidade.

O planejamento pode ser feito em poucas horas e o replanejamento em minutos, e a construtora ganha eficiência e domínio sobre a gestão física e econômica de suas obras.

Para construtoras e incorporadoras isso significa maior controle e previsibilidade sobre suas obras.

Hoje, a Prevision está expandindo seu time de tecnologia para incrementar cada vez mais funcionalidades ao seu produto. Com um time de 25 pessoas, sendo 9 no time de produto, estão buscando profissionais com muita vontade de aprendizado e capacidade de crescimento, auxiliando no impacto do negócio.

“Somos uma empresa enxuta e há espaço para participação em tudo que envolve o produto (discovery, prototipagem, desenvolvimento, devops, suporte, entre outros).”

https://www.prevision.com.br/

## Como se candidatar

Inscrições pelo link: https://bit.ly/prevision-dev-inscricao

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
