### ISSUE TITLE
[Remoto] Front-end Coder Warrior na Fhinck

### ISSUE THREAD

**Issue by michelzf** [frontendbr/vagas#3562]
> Vaga Remota durante a pandemia

## Nossa empresa

Fhinck é um software que fica instalado nos computadores e identifica automaticamente atividades e comportamentos para aumentar a eficiência operacional de back-offices das grandes empresas. O Software trabalha realizando a leitura da experiência do usuário com a tecnologia utilizada para as suas atividades do dia a dia. Quantificamos tempos, cliques e navegação em tempo real. Em resumo o Fhinck realiza 3 tipos de análises: People Analytics (análise da jornada de trabalho analisando a atividade digital, espera sistêmica, internet não corporativa e atividades fora do PC, horas extras e perfis de usuários); Activity Analytics (análise das atividades manuais como planilhas e controles paralelos); e System Analytics (análise de todos os sistemas utilizados pelos colaboradores). Tudo isto é feito usando modelagem estatística e ciência de dados para identificar onde há maiores oportunidades e ganhos, aumentando o desempenho da equipe.

## Descrição da vaga

O/A desenvolvedor(a) front end na Fhinck é responsável pelo desenvolvimento de nosso dashboard, plataforma online em que nossos clientes realizam o acompanhamento de seus indicadores. Além de grande habilidade de desenvolvimento, o/a Desenvolvedor(a)Front End deve ter um grande conhecimento na área de design e usabilidade, para a criação de painéis de cadastro intuitivos para nossos clientes.

## Local

Remoto

## Requisitos

**Obrigatórios:**
-Experiência em desenvolvimento na linguagem NodeJS.
-Experiência em desenvolvimento no framework ReactJS.
-Experiência em desenvolvimento de páginas web, utilizando HTML5, CSS3 e Javascript.
-Experiência de uso da Google Cloud Platform.
-Experiência de uso da ferramenta Git.
-Experiência em SQL.
-Inglês avançado.

**Desejáveis:**
-Experiência na biblioteca Redux.
-Experiência em design e prototipação.
-Experiência em tecnologias serverless, como Cloud Functions, AWS Lambda ou Azure Functions.
-Experiência com a metodologia Git Flow.

## Contratação

 a combinar

## Como se candidatar

Inscreva-se em: https://lnkd.in/eGZVEzb

#### Alocação
- Remoto

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
