### ISSUE TITLE
[Remoto] Estagiário(a) de Desenvolvimento na Mainô

### ISSUE THREAD

**Issue by rhgrow** [frontendbr/vagas#3563]
A Mainô está com vagas abertas para Estagiários de Desenvolvimento.

## Nossa empresa

QUEM É A MAINÔ?

Nosso propósito é utilizar tecnologia para ajudar as empresas e os profissionais a lidarem com as especificidades do comércio internacional. Para fazer isso, nós escolhemos ser bons (não somos vacilões, falamos a verdade com respeito e transparência, somos honestos e corretos com todos). Respeitamos as individualidades. Queremos nos superar constantemente, crescendo com as dificuldades que enfrentamos, ou seja, basicamente somos Saiyajins. Usamos a criatividade para resolver problemas (we hack the task) e somos apaixonados pela empresa que a gente ajuda a construir.

A gente acredita demais no que faz e o nosso sonho é ser uma plataforma global de serviços para Comércio Exterior com liderança expressiva na América Latina.

## Sobre a vaga

Essa pessoa irá compor a equipe de pesquisa e desenvolvimento e, com um time 100% remoto, essa vaga pode ser ocupada por pessoas de qualquer lugar do mundo!

Aqui você terá contato direto com as equipes de marketing, atendimento, comercial e inclusive com as lideranças. Valorizamos demais a vontade de crescer de quem trabalha conosco.

Nosso stack é:
● Ruby on Rails
● Javascript
● HTML
● CSS
● PostgreSQL
● React
● Git

Ter algum conhecimento nessas áreas (principalmente ruby on rails e SQL) é importante, mas vamos te ajudar no seu processo de capacitação para alcançar o potencial que esperamos. Você terá mentoria dos nossos devs e espaço para crescer e tirar suas dúvidas.

A cultura é nosso traço mais importante e você pode nos conhecer mais através de nosso instagram: https://www.instagram.com/mainosistemas/

Estamos buscando pessoas que tenham um forte senso de trabalho em equipe para integrar nosso time. 

## Benefícios

A bolsa é R$1200, além de Vale refeição. E após 6 meses mais avaliação, a bolsa pode subir para R$1500.

## Contratação

Estágio

## Como se candidatar

Envie seu currículo para nosso email: selecao.rhgrow@gmail.com, colocando no assunto ESTAG DEV

#### Alocação
- Remoto

#### Regime
- Estágio

**Comment by ricckneves** [comment]
CV enviado

**Comment by GrandeDev** [comment]
CV enviado

**Comment by IggorSantos** [comment]
CV enviado

**Comment by fernando1208** [comment]
CV enviado

**Comment by Mr-1000** [comment]
CV enviado obgdo pela oportunidade..

**Comment by Oliveiras96** [comment]
CV enviado!

**Comment by brgabrielmartins** [comment]
CV enviado!

**Comment by berrytern** [comment]
CV enviado!

**Comment by mguilherm** [comment]
Obrigado pela oporunidade! Currículo enviado!

**Comment by brgabrielmartins** [comment]
Cv enviado! Obrigado!

**Comment by MatheusAFPimentel** [comment]
Grato pela oportunidade, currículo enviado!

**Comment by advaner** [comment]
Currículo enviado!

**Comment by SantosMaycon** [comment]
Currículo enviado! Obrigado pela oportunidade!

**Comment by rhgrow** [comment]
Gente, muito obrigada por todos os envios! Estamos em etapa final para essa vaga, mas se você não foi chamado, não desanima não! Vamos abrir agora  uma vaga de Junior com uma stack bem parecida! Se vocês já tem alguma experiência, seja em projetos pessoais, em estágios, já resolveram problemas, só vem!

**Comment by rhgrow** [comment]
Vaga fechada! Obrigada a todos que enviaram curriculos! :)
