### ISSUE TITLE
[Remoto] Front-end Developer na Resultados Digitais

### ISSUE THREAD

**Issue by fernandapoloniaRD** [frontendbr/vagas#3567]
## Nossa empresa

A RD nasceu no Brasil, em 2011, com o objetivo de ajudar empresas de todos os portes e segmentos a entender e a aproveitar os benefícios do marketing digital, conquistando resultados reais e efetivos para seus negócios.

Já somos mais de 22k clientes em quase 30 países
Somos um dos principais cases de SaaS B2B no Brasil
Temos escritórios na América Latina e Europa
GPTW: são 4 anos consecutivos como uma das melhores empresas para se trabalhar no Brasil
Criamos o RD Summit, maior evento de Marketing Digital e Vendas da América Latina
Já somos +650 pessoas (RDoers)!
No nosso Culture Code você pode checar os nossos valores e no blog como trabalhamos no dia a dia.
 
## Descrição da vaga

Você vai atuar no RD Station CRM (Customer Relationship Management) tendo como missão empoderar e melhorar a qualidade de vida dos times de vendas das pequenas e médias empresas que trabalham com inbound e inside sales!

A equipe de CRM é quase como uma startup dentro da RD e opera com muita flexibilidade, permitindo arriscar mais, testar mais coisas diferentes e claro, exige também bastante dinamismo e velocidade no ambiente de desenvolvimento. 

Como Front-end Developer dentro do CRM você terá bastante autonomia para tomadas de decisões em termos de implementações técnicas e neste momento estamos passando por um momento bem desafiador de Redesign de toda nossa interface atual, ou seja, toda a parte de experiência, UI UX, está sendo modificada e, no cenário de desenvolvimento, estamos migrando o nosso sistema legado que atualmente está em Angular 1 para React. 

Você vai focar na orquestração disso tendo bastante foco em manutenções, correções, evoluções de features com a perspectiva de crescimento em nossa estrutura após essa migração que ficará totalmente em React. 😀

Além disso estamos traçando um caminho de muito impacto com iniciativas em Micro Frontends, a arquitetura ainda está no inicio do seu desenvolvimento, mas você terá possibilidade de acompanhar, participar e interagir com esse cenário. E também poderá contribuir bastante com Design System.

## Local

Remoto ou Escritório, Florianópolis - Monte Verde

## Requisitos

**Obrigatórios:**
 

- Que tenha experiência com desenvolvimento e arquitetura de software. Experiência com CRM é super interessante, bem como com outros produtos SaaS.

- Que já tenha uma experiência consolidada em desenvolvimento e arquitetura em front-end, de preferência com foco em Angular e que tenha vontade em posteriormente atuar diretamente com React. 

- Vivência com boas praticas de desenvolvimento ágil. Dentre as praticas que usamos: Clean Architectures, TDD, BDD, DDD, que valorize e incorpore qualidade na sua forma de modelar soluções e codar com melhoria continua.

As pessoas da área técnica da RD também costumam ser muito ativas na comunidade, difundindo conhecimento em eventos internos e externos - curtimos e valorizamos muito isso!

**Desejáveis:**
- Ter lidado com questões de escalabilidade e performance é bem importante, mas o essencial mesmo é ter experiência com aplicações de larga escala, que lidam com grandes volumes de dados, transações, etc.

**Diferenciais:**
- Experiência no contexto de CDP (Customer Data Platform), que envolva camada de dados e volume será considerada um diferencial! 😉

## Benefícios

Plano de saúde (100% subsidiado, até para os seus dependentes);
Plano odontológico;
Vale alimentação ou refeição;
Vale transporte;
Gympass;
Outras parcerias de benefícios.

**Diferenciais:**
Horário flexível e opção de Home Office;
Trabalhar lado a lado e aprender diariamente com profissionais referência no mercado;
Cursos e certificações da RD University (nossa universidade corporativa) para você explorar;
Cultura de feedback e desenvolvimento intenso;
No dress code - então pode trazer a sua pantufa;

## Contratação

CLT

## Como se candidatar

Pode se candidatar diretamente no link: https://grnh.se/b6cc6f082us

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: fernanda.polonia@resultadosdigitais.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível

- Sênior

#### Foco
- Angular
- React

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
