### ISSUE TITLE
[São Paulo] Front-End Developer

### ISSUE THREAD

**Issue by cleytonb** [frontendbr/vagas#357]
## Descrição da vaga

A Voxel Digital está ampliando a equipe de marketing digital e desenvolvimento de produtos. Estamos em busca de talentos para atuar no desenvolvimento de aplicações WEB com especialização em Frontend. Nossa equipe respira inovação e queremos contratar profissionais com essa pegada.

## Local

Escritório, São Paulo - Butantã

## Escolaridade e Idiomas
- Nível superior;
- Graduação em cursos de ciência da computação, sistemas da informação, engenharia com noções ou ênfase em computação, design, comunicação visual e ou marketing digital;
- Inglês (Leitura fundamental voltado a tecnologia e escrita para programação).

## Benefícios

- Vale Transporte;
- Alimentação.

## Requisitos

**Obrigatórios:**
- HTML;
- CSS;
- JavaScript.

**Complementares**
- HTML5;
- CSS3 frontend framework (Bootstrap) e pré-processadores (SASS e ou LESS);
- JavaScript framework (AngularJS, Backbone, Ember, ReactJS, NodeJS ou Aurelia);
- SEO;
- Desenvolvimento de interfaces responsivas com técnicas de cross-browser e cross-device;
- Experiência com desenvolvimento e integração com algum CMS e ou plataforma de e-commerce de mercado, como: WordPress, Joomla, Drupal, Magento e ou VTek;
- Experiência com integração e consumo de API REST para serviços como: Facebook e Twitter;
- Utilização de alguma ferramenta de gestão de código e versionamento, como: GIT e ou TFS;
- Utilização de ferramenta IDE para codificação, como: Visual Studio, Code, Eclipse.

**Diferenciais:**
- Banco de dados (SQL, NoSQL);
- API (RESTFull, Webservice);
- Cloud (Amazon, Azure, Rackspace, Google).

## Contratação

PJ ou CLT

## Nossa empresa

Voxel Digital

## Como se candidatar

Por favor envie um email para rh@voxeldigital.com.br com seu CV anexado - enviar no assunto: Vaga Front-End Developer

**Comment by mtmr0x** [comment]
@cleytonb a vaga continua aberta?

**Comment by cleytonb** [comment]
@mtmr0x continua sim.

**Comment by cleytonb** [comment]
Contratamos pelo LinkedIn. Fechando a vaga.
