### ISSUE TITLE
[Remote] React Front-end Developer na Razzo.tech

### ISSUE THREAD

**Issue by neomarbassani** [frontendbr/vagas#3570]
## Descrição da vaga

Somos uma Software House e buscamos profissionais front-end para complementar nossos times de desenvolvimento. Este profissional atuará em diversos projetos, sendo responsável pelo desenvolvimento das aplicações.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência com React / React Native
- Experiência com Redux
- Conhecimentos sólidos em Javascript

**Desejáveis:**
- Animações com React
- NodeJS
- MongoDB

**Diferenciais:**
- Facilidade de aprendizado
- Muita vontade de aprender
- Bom relacionamento interpessoal

## Contratação
PJ a combinar

## Nossa empresa

A Razzo é uma Software House gaúcha focada no desenvolvimento de softwares e soluções inovadoras, sempre buscando encarar novos desafios. Nosso time é composto por gerentes de negócio, designers e um seleto time de desenvolvedores, que atuam em conjunto com seus lideres em diversos projetos.

## Como se candidatar

Por favor envie um email para contato@razzo.tech com seu CV anexado - enviar no assunto: Vaga React Front End

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: neomar@razzo.tech

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

**Comment by Nephxlin** [comment]
Opa, tudo bem? o Email disponibilizado para o envio do C.V não está sendo encontrado

**Comment by neomarbassani** [comment]
Olá,

Realmente os e-mails já estavam sendo retornados... Mas já foi corrigido.

**Comment by neomarbassani** [comment]
Pessoal... Recebemos um grande número de curriculos em 3 dias e estamos fechando a vaga aqui enquanto finalizamos os contatos e entrevistas com estes.

Desde já agradecemos e desejamos sucesso a todos!
