### ISSUE TITLE
[REMOTE] Front-end Developer React Pleno na Atados

### ISSUE THREAD

**Issue by Egarter** [frontendbr/vagas#3571]
Empresa: Atados
Faixa salarial: R$ 3.000,01 a R$ 6.000,00
Estado: São Paulo
Local da vaga: Pinheiros ou Tijuca ou Remoto
Nível: Pleno
Aceita Remoto?: Sim

Descrição da vaga:

Somos uma organização que mobiliza pessoas e empresas para o engajamento social. Hoje nosso maior projeto é nossa plataforma de voluntariado que conecta pessoas com projetos sociais. Além disso, oferecemos consultoria de responsabilidade social para empresas.

Atualmente estamos trabalhando em combate as consequências do COVID-19 com projetos de doação, voluntariado remoto ou presencial para emergências, doação de máscaras, cestas básicas e vários outros projetos que você pode encontrar no nosso site (atados.com.br). Algumas empresas que já trabalhamos: Samsung, Boticário, Coca-Cola, Carrefour, Via Varejo, Shell.

Requisitos:

Obrigatórios:

- Boa experiência com React.js
- Experiência aplicando transformando designs em código

Desejáveis:

- Boa experiência com hooks

Diferenciais:

- Projetos open source
- Conhecimentos de TailwindCSS
- Já ter feito voluntariado

Se interessou?

Se inscreva pelo site:
[http://www.frontjobs.com.br/job/140/]

**Comment by Streeterxs** [comment]
Essa vaga é referente a essa: https://github.com/frontendbr/vagas/issues/3508 ?

**Comment by Egarter** [comment]
@Streeterxs Isso mesmo! A #3508 foi fechada e abrimos no site da FrontJobs, junto com a issue aqui

**Comment by Streeterxs** [comment]
Ah, não sabia, me inscrevi novamente. Mas vocês estão contratando pleno ou sênior?

**Comment by Egarter** [comment]
@Streeterxs Perfeito. Estamos analisando perfis plenos e seniors para contratação de acordo com o perfil.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
