### ISSUE TITLE
[Joinville] Analista Desenvolvedor(a) Pl/Sênior na HunterCo

### ISSUE THREAD

**Issue by SuennyBoos** [frontendbr/vagas#3574]
> Vaga Remota durante a pandemia

## Nossa empresa
Estamos buscando um profissional apaixonado por tecnologia e desafios!
Por isso, se você domina Angular 6,TypeScript e HTML e deseja atuar em uma empresa consolidada na área de soluções para gerenciamento de negócios, essa é a sua chance! Queremos te conhecer!

Mais do que uma desenvolvedora de softwares e sistemas, a IBRATAN é uma empresa nacional especializada em soluções para o gerenciamento de negócios. Com sede na cidade de Joinville, já estamos presentes em 14 estados e somos uma marca reconhecida por auxiliar nossos clientes na tomada de decisões estratégicas. Desde a nossa fundação, em 1996, atendemos entidades de classe, setor público, empresas de pequeno, médio e grande porte.

## Descrição da vaga

Para esta vaga, você precisar dominar as tecnologias:
Inglês Técnico
Angular 6 ou superior
TypeScript
HTML

Será um diferencial se conhecer;
PrimeNG
Java
SQL
Spring
## Local

Remoto durante a pandemia, mas é necessário residir ou ter disponibilidade de mudança para Joinville/SC

## Benefícios

Home Office durante a pandemia
Vale-Alimentação
Plano de Saúde, com co-participação, estendido a dependentes
Vale-transporte;
Programa IE Ibratan (após 3 meses)

## Contratação

PJ ou CLT a combinar

## Como se candidatar

Por favor envie se candidatar em nosso site: https://vagas.hunterco.com.br/job/5f5ed1e813d8c4001b20cf05?r=hmshlf

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 48 horas após cada processo.
E-mail para contato em caso de não haver resposta: suenny@parceirohunterco.com.br

#### Alocação
- Remoto durante a pandemia

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
