### ISSUE TITLE
[São Paulo] Front-end Developer na Mazzatech

### ISSUE THREAD

**Issue by LuNogueira** [frontendbr/vagas#3576]
Front-end Developer na Mazzatech

> Vaga Remota durante a pandemia

## Nossa empresa

Transformamos oportunidades em sucesso, impulsionando o potencial de cada profissional através da nossa precisão em identificar talentos.

## Descrição da vaga

§  Sólidos conhecimentos em desenvolvimento Web, HTML5, CSS3, Javascript.
§  Conhecimentos em Node.Js.
§  Conhecimento em Vue.js
§  Conhecer ferramentas de controle de versão de código (TFS / GitHub);
§  Experiência de 2 à 4 anos na função - Pleno
§ Experiência acima de 1 ano na função - Junior

## Local

Exemplo: Escritório, [SP], [São Paulo], [Bela Vista]

## Requisitos

**Obrigatórios:**
- 2 -4  anos de experiência com Web, HTML5, CSS3, Javascript - Pleno
- 1 ano de experiência com Web, HTML5, CSS3, Javascript - Junior

**Desejáveis:**
§  Conhecimento em Vuetify
§  Conhecimento em Elastic Search
§  Arquitetura em nuvem.
§  Conhecimento de Banco de Dados Neo4J.
§  Conhecimento de Banco de Dados MongoDB

## Benefícios

- Plano de saúde e odontológico
- Seguro de vida
- VR de R$ 22,75/dia
- PLR

## Como se candidatar

Por favor envie um email para lucas@mazza.tech com seu CV anexado - enviar no assunto: Vaga Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: rhmazza@mazza.tech

#### Alocação
- Alocado em nosso cliente da área de seguros.

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by igorpinhh** [comment]
enviado!

**Comment by fernando1208** [comment]
A label tá estágiario e o nivel é junior e pleno? não entendi

**Comment by margotpaon** [comment]
Cv enviado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
