### ISSUE TITLE
[REMOTO] Freela Frontend para CMSs PHP

### ISSUE THREAD

**Issue by vmesel** [frontendbr/vagas#3578]
## Descrição da vaga

Estamos em busca de freelances para desenvolvimento de sites com CMS na linguagem PHP.

Todos os sites estão com layout desenvolvido no figma, photoshop, ilustrator e já vem recortados para a codificação.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- PHP 7+
- HTML 5
- CSS 3
- JS (JQuery, VueJS, React)
- CMS https://octobercms.com/ ou Wordpress

## Contratação

Freela - PJ a combinar

## Como se candidatar

Entre no link: [http://frontjobs.com.br/job/142/](http://frontjobs.com.br/job/142/)

#### Alocação
- Remoto

#### Regime
- Freela

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by apteles** [comment]
@vmesel tudo bom? Então estou tentando resetar minha senha na plataforma, mas não estou conseguindo. Não estou recebendo o e-mail de redefinição de senha na caixa de entrada, spam ou lixeira. Como faço para candidatar a vaga?

**Comment by vmesel** [comment]
@apteles tudo bem e contigo?

Me manda um email em `vinicius arroba pyjobs ponto com ponto br` para eu te mandar uma senha provisória!

Abs

**Comment by apteles** [comment]
@vmesel enviado. Obrigado!

**Comment by JoseFlavioBR** [comment]
Ainda estão aceitando ?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
