### ISSUE TITLE
[Remoto/São Paulo] Front React Sênior Developer na BRQ Digital Solutions

### ISSUE THREAD

**Issue by ReAnne123** [frontendbr/vagas#3579]
Descrição da vaga
Estamos em busca de profissionais com experiência em React para integrar um time de um dos maiores bancos americanos do mundo. Prazo indeterminado de contratação com muita chance de crescimento.

Local
no momento home office, sem previsão de retomada do presencial. Normalizando a pandemia, a sede do banco fica na Av. Faria Lima- Bairro Itaim Bibi- zona sul de São Paulo.

Benefícios
-vale refeição
-vale alimentação
-seguro de vida
-plano médico Bradesco
-previdência privada
-plano odontológico
-Gympass;
-reembolso de certificações.

Requisitos necessários:
React.js, Git, CSS, HTML, Angular.

Requisitos diferenciais:
Jenkins (DEVOPS)
Electron
Phyton
Protocolo HTTP para API (Restful)
Websockets
Inglês avançado para lidar com times do exterior.

Contratação
CLT full pela BRQ.

Nossa empresa
Fundada em 1993, a BRQ Digital Solutions é uma das maiores empresas de serviços de TI do país. Conta com 2500 profissionais distribuídos nas filiais de São Paulo, Alphaville, Rio de Janeiro, Curitiba e Nova Iorque.

Como se candidatar
Por favor envie um email para Renata- ryokota@brq.com, com seu CV anexado - enviar no assunto: React.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
