### ISSUE TITLE
[Curitiba - PR] Front End Developer

### ISSUE THREAD

**Issue by debonaleonardo** [frontendbr/vagas#358]
## Descrição da vaga

Procuramos desenvolvedor FrontEnd com capacidade de autogerênciamento e comprometimento para atuar em um projeto com capacidade de causar um grande impacto na maneira em como fazemos negócios.

## Local

Curitiba, bigorrilho, próximo ao Condor Champagnat

## Benefícios

Vt, Vr

## Requisitos

Sólidos conhecimentos em Javascript, CSS, SASS.

**Desejáveis:**
- VueJS

## Contratação

CLT ou PJ a combinar

## Nossa empresa

A Langowski é uma empresa que está no mercado desde 2012, sempre focada em desenvolver produtos que possam causar um impacto positivo no seguimento.
Na Langowski você irá encontrar o que há de melhor em termos de tecnologia e infra-estrutura aliado a um ótimo ambiente de trabalho.

## Como se candidatar

Para mais informações sobre a vaga e a empresa, interessados devem enviar email para: leonardo@langowski.com.br

**Comment by jotavejv** [comment]
Enviado.

**Comment by mtmr0x** [comment]
@debonaleonardo a vaga continua aberta?
