### ISSUE TITLE
[Remoto] Front-end Sênior Developer na BRQ Digital Solutions

### ISSUE THREAD

**Issue by ReAnne123** [frontendbr/vagas#3581]
Descrição da vaga
Estamos em busca de profissionais com experiência em Front para integrar um time de um dos maiores bancos do país. Prazo indeterminado de contratação com muita chance de crescimento.

Local
home office.

Benefícios
-vale refeição
-vale alimentação
-seguro de vida
-plano médico Bradesco
-previdência privada
-plano odontológico
-Gympass;
-reembolso de certificações.

Requisitos necessários:
SASS
Foco em Javascript
AngularJS ou Angular 4+
CSS e SASS
Experiência com Desenvolvimento de sites/páginas com Design Responsivo
Gulp
NPM
Versionamento em GIT

Contratação
CLT full pela BRQ.

Nossa empresa
Fundada em 1993, a BRQ Digital Solutions é uma das maiores empresas de serviços de TI do país. Conta com 2500 profissionais distribuídos nas filiais de São Paulo, Alphaville, Rio de Janeiro, Curitiba e Nova Iorque.

Como se candidatar
Por favor envie um email para Renata- ryokota@brq.com, com seu CV anexado - enviar no assunto: Front remoto.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
