### ISSUE TITLE
[Remoto / São José dos Campos - SP] Front-end Developer Jr./Pleno na Cuponomia

### ISSUE THREAD

**Issue by rafaelpradella** [frontendbr/vagas#3584]
## Descrição da vaga
O Cuponomia, empresa com mais de 8 anos no mercado de cupons de desconto e cashback está procurando uma pessoa para compor a nossa equipe de Design/Front-End por trabalho remoto, ou no nosso escritório em São José dos Campos - SP ([ver no Maps](https://bit.ly/2ZCeDw8))

Você vai trabalhar bem perto de nossa equipe de Marketing, inicialmente ajudando a desenvolver testes A/B para nossas landing pages, criação e protótipo de novas páginas e peças de campanhas promocionais utilizando o Google Tag Manager e Google Optimize. A partir daí também vai criar novas funcionalidades para o nosso site e produtos adjacentes utilizando nossa stack .NET MVC, LESS/SASS, Vue.JS.

Tem interesse? Mande um email para `rafael@cuponomia.com.br` com o assunto 'Vaga Front - [SEU NOME]' com o seu currículo e portfólio/link do GitHub.

> Se não tiver um portfólio montado, pode mandar no corpo do email links para projetos que você contribuiu, **explicando a sua participação**: seja freelancer, projeto da faculdade, etc.

## Benefícios
- Plano de saúde + odontológico
- Seguro de vida
- VR de R$ 26/dia
- Cashback em dobro
- Vale Transporte (para a vaga presencial)

#### Diferenciais
- Horário Flexível;
- Cota anual pra você utilizar com cursos, eventos, livros, palestras etc.;
- Dojos mensais;
- Sessões de feedbacks semestrais

## Requisitos
**Obrigatórios:**
- Manipulação do DOM com JS vanilla e com suporte cross-browser;
- Escrever HTML semântico e noções sólidas de SEO;
- Proficiência em JavaScript (ES2015+);
- Boas noções de layout, escrever CSS sem utilizar frameworks e design responsivo;

**Diferenciais:**
- Noções de Google Analytics (ler eventos, estatísticas de uso);
- Noções de Google Tag Manager (criar scripts, gerenciar timing e triggers);
- Familiaridade com a nossa stack: (.NET MVC, LESS/SASS, Vue.JS);
- Familiaridade com frameworks JS modernos (Vue.JS, React, Svelte, Angular etc.);
- Técnicas de otimização de performance (lazy-loading, code splitting, otimização de assets, etc.);

## Contratação
CLT a combinar

## Tempo médio de feedbacks

O prazo de resposta dos CVs e envio dos testes é de 3 dias úteis, 7 dias úteis para as etapas seguintes.
Após isso se você não recebeu uma resposta, pode mandar um email para `rafael@cuponomia.com.br`.

## Nossa empresa

O Cuponomia é um site totalmente gratuito que oferece desconto através de cupons, cashback e ofertas das principais lojas online nacionais e internacionais. Nós negociamos com os melhores e-commerces e vasculhamos toda a internet para encontrar e oferecer cupons exclusivos, descontos especiais e cashback para nossos usuários.

[Sobre o Cuponomia](https://www.cuponomia.com.br/sobre)

#### Alocação
- Alocado
- Remoto
- Remoto durante a pandemia

#### Regime
- CLT

#### Nível
- Junior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
