### ISSUE TITLE
[Remoto/Grande Florianópolis] Front-end Developer na Koper

### ISSUE THREAD

**Issue by morais90** [frontendbr/vagas#3585]
## Nossa empresa

Koper é a plataforma de gestão de construção cívil mais completa do mercado!

Acreditando em uma gestão horizontal, buscamos proporcionar ao nosso time a melhor experiência possível, enxergando a
criatividade e autonomia como pilares fundamentais em nossa cultura.

Para a criação do Koper, foram investidos 5 anos de pesquisa e desenvolvimento, temos como laboratório algumas Construtoras
e Incorporadoras de Biguaçu, que foram nossos verdadeiros parceiros ao longo dessa jornada.

Acreditamos que soluções inovadoras são aquelas que resolvem problemas reais! Por isso, nos orgulhamos em dizer
que o Koper é um sistema construído pelo cliente!

Foram tantas experiências práticas e contribuições de nossos parceiros, que hoje temos grande satisfação em dizer que
somos mais que somente uma solução inovadora.

## Descrição da vaga

O que você vai encontrar aqui:
– Ambiente descontraído e saudável.
– Reuniões pontuais e curtas.
– Foco total no usuário, nosso objetivo é encantar os nossos clientes.
– Pessoas comprometidas e apaixonadas em construir a melhor plataforma de gestão de construção civil.

Procuramos por pessoas que:
– Amem um desafio.
– Sejam inquietas, questionadoras e gostem de aprender constantemente.
– Gostem de participar da criação do produto.
– Não tenham medo de mexer em código legado.
– Escrevam código limpo, legível e de fácil manutenção.
– Entreguem código testado e ajudem o time a melhorar a qualidade do código.
– Compartilhem conhecimento e enriqueçam as discussões técnicas.

## Local

Grande Florianópolis ou Remoto

## Requisitos

**Obrigatórios:**
– Javascript ES6+
– React
– HTML semântico
– Pré-processadores (SASS, PostCSS)
– Module Bundler (Webpack)
– Experiência com REST API
– Framework de teste (Jest, Cypress

**Diferenciais:**
– Typescript
– React Native
– Next.js
– Websockets

## Benefícios
– Internet
– Horário realmente flexível
– Home office
– Notebook

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para willian.morais@koper.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
