### ISSUE TITLE
[Goiânia] Front-end Developer (Remoto/Full-time) na RBOOH

### ISSUE THREAD

**Issue by danillodouglas** [frontendbr/vagas#3587]
[Goiânia] Front-end Developer (Remoto/Full-time) na RBOOH
==================================================
-->
> Vaga definitiva

## Nossa empresa

A RBOOH.COM.BR conecta de forma rápida e eficiente anunciantes às melhores opções de mídia out-of-home (OOH).

Somos a solução que consolida o sistema comercial dos melhores veículos de mídia OOH, em um só lugar, no menor tempo possível, Oferecendo uma experiência de compra única, com informações ricas e padronizadas dos pontos de exibição.

## Descrição da vaga

Front-end Developer na plataforma.RBOOH.com.br
*Atuação remota, full-time (mínimo de 6 horas/dia) com emissão de NF para recebimento.

## Local
Remoto. A sede da RBOOH fica em Goiás.

## Requisitos
- Sólida experiência em projetos React + Redux
- Proficiência em JavaScript
- Experiência com CSS e HTML semântico
- Familiaridade com APIs RESTful
- Experiência com ferramentas comuns de desenvolvimento front-end como: Babel, Webpack, NPM, Lint, JSX, Git, etc

## O que esperamos:
- Proatividade
- Boa comunicação e trabalho em equipe
- Desenvolver com fidelidade os layouts recebidos
- Capacidade de entender os requisitos de negócios e traduzi-los em requisitos técnicos
- Disponibilidade para reuniões pela manhã (8h às 9h), duas vezes na semana

## Diferenciais do candidato:  
- Material-UI e Styled Components
- Boa experiência com hooks
- Mobile First
- React Native
- Testes (Jest e Cypress)
- Conhecimento de boas práticas de UI e UX

## Benefícios
- Oportunidades de promoção dentro da equipe com aumento de ganhos

## Contratação
PJ (com emissão de NF)

## Como se candidatar
Por favor envie um email para danillo.douglas@rbooh.com.br com seu CV anexado - enviar no assunto: Vaga ReactJS Remoto Full-time 

## Tempo médio de feedbacks
Costumamos enviar feedbacks *SOMENTE PARA OS SELECIONADOS* em até 7 dias após cada candidatura.
E-mail para contato: danillo.douglas@rbooh.com.br

#### Alocação
- Remoto
- Full-time

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

#### Remuneração
- De 7k a 9k

**Comment by Bilusca** [comment]
Da um erro mandar o email para a vaga.

**Comment by WillianSugiyama** [comment]
O e-mail parece estar errado.

**Comment by danillodouglas** [comment]
Senhores, o e-mail está correto. Recebi normalmente a candidatura de todos. Do @WillianSugiyama recebemos hj às 12h53 e do @Bilusca recebemos dia 18 setembro.

**Comment by danillodouglas** [comment]
Já contratamos um candidato que viu a vaga aqui.
