### ISSUE TITLE
[Florianópolis] Front-end Developer na Suntech/Verint

### ISSUE THREAD

**Issue by felipegb34** [frontendbr/vagas#3588]
A Suntech está buscando um desenvolvedor frontend fera em React para completar o time. Se identificou? Vem entender mais sobre essa oportunidade!

https://cis.verint.com/careers/C0.812/react-developer/

**Como será o seu dia-a-dia?**

·       Trabalhará com desenvolvimento de produtos e soluções na área de telecomunicações e segurança;

·       Fará parte do time, trocando experiências e trabalhando em equipe;

·       Avaliará tecnologias para desenvolvimento de novas soluções;

·       Terá incentivos para crescimento e desenvolvimento profissional;

·       Atuará ativamente com os membros da equipe na criação de novos produtos/funcionalidades, buscando o aprimoramento da experiência dos usuários e mantendo padrões visuais da empresa;

·       Atuará na criação de mockup e protótipos que permitam validar novos conceitos, novas funcionalidades ou para demonstrar novas versões;

·       Desenvolverá e manterá atualizados os guias/frameworks/padrões que permitam a outros desenvolvedores utilizarem a identidade visual e seus componentes na construção de novos produtos ou funcionalidades;

·       Pesquisará e desenvolverá novas ferramentas/produtos para área de telecomunicação e segurança;

·       Identificará, analisará e corrigirá problemas em sistemas.

**E aí, gostou? Tem mais!**

Atualmente estamos trabalhando em modelo Home Office em função da pandemia e, até o momento, não temos previsão para voltar ao escritório. Mas algo é certo: quando a situação for normalizada, manteremos o trabalho home office (ao menos em alguns dias da semana) como uma possibilidade - além de uma jornada de trabalho flexível!

**Mas as vantagens não param por aí:**

   ·       Fazer parte de um time global, desenvolvendo não só suas habilidades técnicas, mas também sua capacidade de comunicação e interação com outros países;

·       Verba disponível para treinamentos, participação em eventos, cursos EaD;

·       Benefícios para deixar o seu dia mais saudável: frutas, iogurte, granola;

·       Café, Capuccino, Chocolate quente e chá liberados!

·       Folga no dia do aniversário;

·       Banco de horas;

·       Ginástica laboral;

·       Massagem;

·       Casual dress code;

·       Convênios diversos com restaurantes, academias e outros;

·       Participação nos lucros e resultados;

Pacote de benefícios tradicionais com valores diferenciados: VT, VR/VA, Plano de saúde, Plano odontológico, Seguro de vida.

**Parece maravilhoso! Mas, afinal, o que a Suntech faz?**

Somos uma multinacional americana que desenvolve produtos e soluções de alta tecnologia para as áreas de Defesa e Segurança e empresas de telecomunicações. Nosso amplo portfólio de produtos é utilizado em mais de 100 países, ajudando governos, infraestruturas críticas e organizações empresariais a neutralizar e prevenir o terror, crime e ameaças cibernéticas. Somos líderes de mercado no que fazemos e estamos sempre em busca de novos produtos que façam a diferença para os nossos clientes. Nossa missão é fazer do mundo um lugar mais seguro!

**O que você precisa ter?**

·       Ensino superior completo ou em andamento na área de Tecnologia;

·       Experiência com React;

·       Conhecimento em JavaScript / JQuery / CSS;

·       Experiência prévia com desenvolvimento Backend

·       Flexibilidade e interesse para estar sempre aprendendo novas tecnologias; 

·       Inglês intermediário.

 O que será um diferencial?

·       Experiência com tecnologias como Java, NodeJS, APIs REST, Git, entre outras.

·       Experiência com Cloud (AWS / Azure);

·       Conhecimento na arquitetura microsserviços;

·       Conhecimento em GitLab - CI/CD e Docker

·       Linux

·       Pós-graduação em Engenharia de Software ou Sistemas de Informação.

Fez sentido? Manda o seu currículo e vem conversar com a gente ;)
https://cis.verint.com/careers/C0.812/react-developer/

> Vaga Remota durante a pandemia
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by felipegb34** [comment]
> Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

Vaga em aberto. Mais de uma contratação.
