### ISSUE TITLE
[Ribeirão Preto - SP] Front End Developer

### ISSUE THREAD

**Issue by fernandarbr** [frontendbr/vagas#359]
## Descrição da vaga

Nós procuramos por desenvolvedores(as) front-end que serão responsáveis por desenvolver nosso site. Você irá trabalhar com a equipe de Marketing, a equipe de CS e com outros desenvolvedores em um ambiente onde você conseguirá ver o impacto das suas idéias. O @hippodrs  é uma ótima oportunidade de inovar e tomar decisões significativas, enquanto você continua a se desenvolver. Se você quer revolucionar o cenário da saúde e impactar a vida de pessoas, seu lugar é no Hippo! Estamos crescendo e queremos pessoas que queiram crescer com a gente!

Procuramos por pessoas apaixonadas e incomodadas, que foquem nas constante melhorias em favor de soluções que aumentem nosso desempenho, usabilidade, performance, taxa de conversão, etc.

## Local

 Ribeirão Preto - SP

## Por que trabalhar aqui:

Nós somos um time de incomodados, curiosos e que tem sede de aprendizado. Aqui você vai ter a oportunidade de crescer em ritmo acelerado, contribuir para nosso negócio e impactar a vida das pessoas. Além disso, contamos com: 
- Horário flexível
- Pessoas incríveis
- No dress code

## Requisitos

**Obrigatórios:**
- Javascript
- HTML5
- CSS3
- AngularJS ou React
- JQuery
- git

**Desejáveis:**
- Python / Django
- gulp
- sass / less
- Docker

## Contratação

PJ ou CLT - de R$$4.000 a R$6.000

## Nossa empresa

Somos a startup de saúde que mais cresce no Brasil. Nascemos em Ribeirão Preto em 2015 com a proposta de solucionar os problemas de saúde no mundo!!
Nossa missão é oferecer a melhor experiência de saúde para todos. Levamos muito a sério essa missão e todas as nossas decisões são tomadas em cima dela.
Nossa visão, que é onde queremos chegar, é ser reconhecida como a empresa que mudou o cenário da saúde no Brasil até o final de 2017, ou seja, esse é o nosso ano. Ou vai, ou racha! (ps: fechamos o ano de 2016 em 5 cidades, já estamos em 25 e nossa meta é chegar em 100!!). 

Nossos valores, que são os pilares da nossa empresa são:
*Mais amor*: sempre tratar os pacientes com carinho e respeito. As pessoas procuram a gente, geralmente, doentes, depois de esperar um logo tempo para agendar, com vários pré-conceitos e tristes. Ou seja, é nosso dever fazer desse momento um pouco mais feliz.
*Hard Work*: Get shit done!
*Curiosidade*: Como vocês eu também estou aprendendo. Nunca fui fundador e nunca passei por muitos dos nossos desafios atuais. Mas tudo isso é superado com curiosidade para aprender e comprometimento.
*Team Hippo*: Somos um time e não uma família, todos precisam marcar gol.
*Ousadia*: Ser ousado significa ter a coragem para ir contra o status quo. Ou seja, realmente, lutar pelo que acredita e estar disposto a tomar o risco pelo o que acredita.
 
Se você se identifica com essa maneira de pensar e agir, seu lugar é aqui!

## Como se candidatar

Por favor envie um email para vagas@hippodrs.com.br com seu CV anexado - enviar no assunto: Vaga Front

**Comment by matheusggds** [comment]
Possibilidade de remoto?

**Comment by fernandarbr** [comment]
@matheusggds existe sim, Matheus! Temos preferência por pessoas que trabalhem com a gente na empresa, mas também existe a possibilidade de remoto sim! Teria interesse?

**Comment by matheusggds** [comment]
@fernandarbr tenho muito! Mandando CV agora :)

**Comment by mtmr0x** [comment]
@fernandarbr a vaga continua aberta?
