### ISSUE TITLE
[Remoto/Alphaville-SP] Front-end Developer Jr. na Conversarium

### ISSUE THREAD

**Issue by Conversarium** [frontendbr/vagas#3590]
## Nossa empresa

A Conversarium é uma plataforma de conversas um a um entre quem tem assuntos a oferecer e quem quer conversar e aprender, oferecendo uma experiência próxima, segura e inovadora entre pessoas com diversas vivências e experiências diferentes.

## Descrição da vaga

Buscamos profissional com pelo menos 2 anos de experiência vivenciando projetos em JavaScript e em vue.js, além de frameworks adicionais. Projetos utilizando roteamento com vue-router e state management com vuex são desejáveis, bem como a utilização de vue-firestore.
Participará da equipe implementando elementos visuais para que os usuários da plataforma vejam e interajam na web e na aplicação mobile. Contará com o suporte da equipe back end e a sua responsabilidade será na integração desses serviços com o front da aplicação. 

## Local

Trabalho remoto durante a pandemia.
Volta prevista (a confirmar) em março de 2021 em Alphaville/SP.

## Requisitos

Mínimo de 2 anos de experiência em projetos JavaScript e vue.js

**Desejáveis:**

Conhecimentos em vue-router e state management com vuex;
Conhecimentos em vue-firestore.

## Contratação
PJ a combinar

## Como se candidatar
Por favor envie um email para operacoes@conversarium.com com seu CV anexado - enviar no assunto: Vaga Front-End Jr

#### Alocação
- Alocado
- Remoto
- Remoto durante a pandemia

#### Regime
- PJ

#### Nível
- Júnior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
