### ISSUE TITLE
[Remoto] Front-end PWA Developer na Zipz

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#3591]
## Nossa empresa

Somos uma ferramenta de digitalização de ofertas por assinatura. (Coupon as a Service)

De uma lado fornecemos ao consumidor um App gratuito (*Zipz) onde ele tem acesso a uma lista de shoppings, lojas, restaurantes, bares, etc... com base na sua localização. Clicando na loja o consumidor terá acesso a uma lista de ofertas que aquele pdv está oferecendo naquele momento. 

*também oferecemos a nossa ferramenta no modelo white label (sdk) para ser integrada ao qualquer aplicativo proprietário ou PWA (progressive web app) personalizado para o cliente.

Do outro lado, fornecemos ao comerciante um painel de controle web para que eles possa abastecer o App com ofertas customizadas de acordo com sua estratégia. 

A nossa ferramenta consegue comprovar a conversão do cupom na loja física sem a necessidade de integração com o sistema POS local. O Zipz não também não realiza transações financeiras.

No painel de controle fornecido ao comerciante, nós disponibilizamos algumas informações geradas pelo usuário em sua jornada dentro do App. 

Para a indústria, nós fornecemos uma painel de controle central onde todas as informações geradas pelos pdvs participantes são compiladas e disponibilidades em tempo real.

## Descrição da vaga

A front-end developer specialized in building the front end, or client-side that knows React.js or Vue.js and has previous experience in building a PWA structure.

REQUIRED SKILLS:

- Javascript

- CSS

- HTML

- React.js or Vue.js

- have experience with PWA

- Be organized

- Meet deadlines

To apply you must be able to work with an international team based on East Europe, be able to communicate in English (online), and be willing to face some challenges. We are serious, you MUST speak English!

This is a full-time job (100% home office) and you will be answering directly to the CTO (Belgrade, Serbia) and the CEO (São Paulo, Brazil).

## Local

Remoto

## Requisitos

- Have experience with PWA
- Be organized
- Meet deadlines
- Speak English

## Contratação

Freela

## Como se candidatar

Candidatar-se em: [https://bit.ly/2H40eFu](https://bit.ly/2H40eFu)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 48 horas após cada etapa do processo.
E-mail para contato em caso de não haver resposta: developers@zipzapp.com

#### Alocação
- Remoto

#### Regime
- Freela

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
