### ISSUE TITLE
[Remoto] Front-end Developer @Toptal

### ISSUE THREAD

**Issue by eluttner** [frontendbr/vagas#3592]
## Nossa empresa

![Toptal](https://www.toptal.com/toptal-logo.png "Toptal")

Somos líderes em trabalho remoto global.

## Descrição da vaga

A Toptal sempre tem vagas abertas para todas as linguagens de programação. 

A maioria das vagas são para empresas americanas. 

O trabalho pode ser com startups (em vários níveis de maturidade) ou empresas de grande porte. 

Existem 3 tipos de carga horária.

- Hora: Deve-se enviar a planilha de horas a cada duas semanas.
- Part-Time: 20h/semana
- Full-Time: 40h/semana

Os trabalhos podem ser curtos (1-2 semanas) ou longos (12+ meses)

- Front-end/WEB
  - React em alta demanda
  - Vagas para todas as tecnologias de Front-end

- Frontend/mobile
  - ReactNative em alta demanda
  - iOS
  - Android

## Local

- 100% Remoto / Qualquer lugar do mundo.

## Requisitos

- Inglês fluente
- 3+ anos de experiência profissional

## Benefícios

- Participar da rede global da Toptal
- Pagamento em USD.
- Pagamento a cada duas semanas.
- Não tem benefícios adicionais. 
- Cartão pré-pago em USD. Direto em USD, não precisa converter para BRL e USD de volta.
- O valor hora é definido pelo freelancer. A Toptal funciona orientada a mercado, ou seja, o mercado que decide se seu valor hora é viável ou não
- Aqui pode-se verificar os valores pagos por hora: [https://www.toptal.com/developers/hourly-rate](https://www.toptal.com/developers/hourly-rate)

## Contratação

- A contratação é feita por PJ ou Autônomo. 
- O pagamento é feito em USD e deve-ser fazer o câmbio para receber em BRL.

## Como se candidatar

Inscreva-se na vaga pelo link: [http://toptal.com](https://www.toptal.com#select-eye-opening-coders-now)

O processo seletivo é padronizado e consiste nestas etapas:

1. Cadastro no site pelo link: [http://toptal.com](https://www.toptal.com#select-eye-opening-coders-now)
2. É feita uma pré avaliação para atender a demanda
3. Entrevista em inglês
4. Desafio de código online
   1. Este é feito pelo site codility. São três questões onde serão avaliados o funcionamento do código (correctness) e complexidade (time/space complexity)
   2. 1:30h para completar as 3 questões. Cada questão vale 100 pontos e precisa de um mínimo de 100 pontos
   3. Caso não seja aprovado e tenha algum problema, enviar um email explicando
5. Entrevista Técnica 1
   1. Experiência profissional
   2. Testar a resolução de problemas
   3. Desafio de código ao vivo
      1. Compartilhar a tela
      2. Resolver duas questões de código. Elas são simples mas precisa de resolver com atenção
6. Entrevista Técnica 2
   1. Duas semanas para fazer um projeto simples ná area em que está se candidatando
      1. Full Stack
      2. Front-End
      3. Backend

- Caso tenha alguma dúvida enviar um email para eduardo.luttner@toptal.com 

## Tempo médio de feedbacks

2-3 semanas

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
