### ISSUE TITLE
[Remoto] React.js/PWA Developer  @ Harpio

### ISSUE THREAD

**Issue by thaisvilladal** [frontendbr/vagas#3593]
## Descrição da vaga

Para atuar em nosso cliente, uma startup de rede social corporativa, líder no segmento, que oferece uma plataforma SaaS com foco na melhoria de comunicação e engajamento entre grandes empresas e seus colaboradores.

Reconhecida e premiada como Top 100 no ranking 100 Open Startups e atendendo grandes clientes como Carrefour, PepsiCo, Unimed, BRF, SBT, Klabin e Via Varejo.

Responsabilidades:
Desenvolvimento de aplicações web PWAs (Progressive Web App), bem como atuar em suas melhorias, novas implementações e correções de bug.
O PWA tem seu core desenvolvido com React, styled-components e Apollo Client.
Na API que os Apps consomem dados, irá executar melhorias correções e novas features.
A API é desenvolvida com graphql-relay e alguns endpoints com express.

Desafios do projeto:
Será um grande diferencial a experiência em refazer/reescrever um produto do zero.
Diferencial experiência em liderança técnica, pois esse profissional irá atuar como um “mentor” para a equipe em atividades referente a refatoração.

## Local
Remoto - mesmo pós-pandemia

#### Diferenciais

- home office
- horário flexível

## Requisitos

**Obrigatórios:**
- Domínio em PWA
- Experiência com React e Node
- Conhecimentos em Express, Relay, Apollo Client, Styled-components
- PWA (service work, cache)
- Unix-like (Linux / Mac / BSD)

**Desejáveis:**
- Typescript
- Figma
- Git

## Contratação

PJ por prazo indeterminado - remuneração a combinar

## Nossa empresa

Somos uma consultoria de recrutamento digital, utilizando ciência de dados e inteligência artificial, técnicas de entrevistas e hunting feito por consultores especializados, entregamos uma lista de candidatos relevantes, testados e validados, sob medida para a sua necessidade.

## Como se candidatar

Por favor envie um e-mail para thais.villadal@harpio.com.br com seu CV anexado ou se inscreva através do link https://jobs.kenoby.com/vagasharpiotecnologiamkt/job/desenvolvedor-fullstack-sr/5f5f575cfc47e436e0771bba - enviar no assunto: Vaga Full Sr

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ PJ
- 💰 10k-15k
- 💰 15k+

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
