### ISSUE TITLE
[Cidade] Front-end Developer na Empreender

### ISSUE THREAD

**Issue by andreas-monday** [frontendbr/vagas#3594]
## Descrição da vaga

Procuramos um(a) profissional com experiência em CodeIgniter, PHP, JavaScript, HTML, CSS , jQuery, Bootstrap.

## Local

Remoto

## Contratação

PJ a combinar

## Nossa empresa

Somos uma empresa com diversos produtos voltados ao ecommerce.

## Como se candidatar

Por favor envie uma mensagem com a pretensão salarial para PJ, 8h para https://www.linkedin.com/in/brunofelipebrito/

#### Alocação

- Remoto

#### Regime

- PJ

#### Nível

- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
