### ISSUE TITLE
[Curitiba/PR - Remoto] Front-end React na Gobrax

### ISSUE THREAD

**Issue by aline-matos** [frontendbr/vagas#3595]
## Gobrax

Somos a melhor empresa de gestão de frotas em tempo real da América Latina. Somos uma startup e estamos em fase de expansão contratando profissionais adaptados à metodologia ágil e que saibam trabalhar constantemente com planejamentos e prazos de entrega. Desde o início, estamos reunindo pessoas comprometidas, dedicadas e que sonham em escrever uma história revolucionária no mercado da Logística e Transporte.

Nesta função, suas responsabilidades serão:

- Ajudar a construir aplicações web modernas e aplicativos móveis;
- Escrever código reutilizável, testável e eficiente;
- Buscar ativamente inovação e melhoria contínua bem como eficiência em todas as tarefas atribuídas;
- Reforçar uma cultura de excelência em engenharia da qual você tem orgulho de pertencer.

## Descrição da vaga

Front-end React. Procuramos um profissional que tenha como foco o aprimoramento constante, seja questionador, tenha uma atitude positiva e seja dono de suas atividades. É preciso gostar de algumas rotinas, ter bom raciocínio lógico e capacidade de trabalhar com pessoas de diferentes áreas da Gobrax.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência em aplicações React/React Native
- Experiência com desenvolvimento de interfaces responsivas

**Desejáveis:**
- Experiência em trabalho remoto
- Ferramentas de versionamento e colaboração como git e github
- Figma, Adobe XD, Protopie, Sketch, similares
- HTML5, CSS3, TypeScript
- Interesse em evoluir na área de UX/UI
- Domínio de Inglês e Espanhol para atuação com parceiros internacionais

**Diferenciais:**
- Experiência com publicação de aplicativos nas lojas Google Play e Apple Store
- Expo
- Material Design, Bootstrap, Materialize, AntD, similares
- UmiJS

## Benefícios

**Diferenciais:**
- Muita flexibilidade e autonomia
- A Gobrax está localizada em Curitiba/PR, mas também é adepta ao home office
- Um ambiente desafiador, com oportunidades de crescimento

## Como se candidatar

Por favor envie um email para ti@gobrax.com com seu CV anexado - enviar no assunto: Vaga Front-end React

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by aline-matos** [comment]
@felipefialho poderia excluir essa vaga, por gentileza? Obrigada!
