### ISSUE TITLE
[Remoto - Porto Alegre/RS] Front-end Developer na TownSq

### ISSUE THREAD

**Issue by JGhignatti** [frontendbr/vagas#3598]
## Nossa empresa

A TownSq é uma empresa de tecnologia, líder global em soluções para administração de condomínios.
Temos em torno de 5 milhões de usuários em 4 países.

## Descrição da vaga

Estamos procurando uma pessoa desenvolvedora front-end web pleno/sênior para fazer parte do nosso time de desenvolvimento, aqui você irá:
- Arquitetar e desenvolver nossos produtos web (Angular, RxJs, Nx workspaces, NgRx, Jest, Cypress)
- Colaborar com times pequenos em um ambiente ágil
- Trabalhar de perto com o time de Design e Produto para entregar novos produtos e funcionalidades
- Ser responsável pela saúde do código dos nossos projetos através de boas práticas de desenvolvimento
- Identificar oportunidades de melhorias em nossa plataforma através de pesquisa e provas de conceito

## Local

Remoto ou Porto Alegre, RS, Bairro Bom FIm.

## Requisitos

**Obrigatórios:**
- Fluência em engenharia de software e design patterns
- Experiência em frameworks modernos de front-end, como Angular ou React
- Sólidos conhecimentos de JS, TS
- CSS3 (Flex, Grids)
- Inglês

**Desejáveis:**
- State management
- Unit Tests com Jasmine/Jest
- Nx workspaces
- Angular avançado

## Benefícios (CLT)

- Unimed a partir do 3o mês. Sem mensalidade, apenas co-participação
- VR de R$ 23/dia
- Vale transporte quando necessário

**Diferenciais:**
- Horário flexível (ex: estudantes)

## Como se candidatar

Por favor envie um email para giordana.andrade@townsq.com.br com seu CV anexado - enviar no assunto: Vaga front-end Web.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: giordana.andrade@townsq.com.br.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior

Se tiver alguma dúvida sobre a vaga, projeto, etc, pode me chamar na [DM do twitter](https://twitter.com/JGhignatti) e a gente conversa ou email para jv@townsq.com.br.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
