### ISSUE TITLE
[Rio de Janeiro] Front-end Developer na Teamsoft

### ISSUE THREAD

**Issue by SybrandWillen** [frontendbr/vagas#3599]
## Nossa empresa
A Teamsoft é uma empresa de desenvolvimento de sistemas e aplicativos no modelo Fábrica de idéias, ajudamos startups e grandes corporações a terem sucesso em sua jornada. Além disso, temos um time voltado para o nosso produto de Delivery e Gestão de Estabelecimentos.

## Descrição da vaga
Conhecimento técnico é muito importante, mas acima de tudo, buscamos pessoas que queiram crescer e se desenvolver junto conosco. 

- Trabalhar com um time no modelo SCRUM em desenvolvimento Ágil.
- Arquitetura e desenvolvimento de nossos produtos internos e de clientes.
- Sinergia entre as áreas de Levantamento, Design, BackEnd e Comercial.
- Liberdade em sugerir e ter atitude de dono em relação aos nossos produtos e projetos.

E aí, topa o desafio? Então vem para o DreamTeam, vem para a TeamSoft! 

## Local

Remoto ou RJ, Rio de Janeiro, Penha.
É um diferencial a possibilidade de estar presencial ao menos 2x na semana, trabalhando junto ao time.

## Requisitos

**Obrigatórios:**
- Experiencia em React, React Native
- Experiencia em Saga e Redux
- Solidos conhecimentos em lógica de programação com JS.
- Imprescindivel saber realizar a integração entre Frontend e Backend, Axios.
- CSS3 (Flex, Grids)

**Diferenciais:**
- Conhecimento em Node.js
- Conhecimento em Filas (queues)
- Conhecimento em Redis

## Benefícios

- Férias
- DayOff Aniversário
- Horário Flexível
- HomeOffice
- PL

## Contratação

PJ a combinar

## Como se candidatar

Por favor preencha o [formulário](https://forms.gle/FG5b6YAiQpFarg7J7)

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
