### ISSUE TITLE
[São José dos Campos] Front-end developer

### ISSUE THREAD

**Issue by lucasrcdias** [frontendbr/vagas#360]
## Descrição da vaga

Buscamos Front-end developers de nível júnior ou pleno para atuar no desenvolvimento contínuo de nossa plataforma.

## Local

Presencial em São José dos Campos - São Paulo

## Requisitos

**Obrigatórios:**
- HTML5
- CSS3 e SASS
- Javascript
- Design responsivo
- Git
- Noções de UX

**Diferenciais:**
- Familiaridade com MVC
- Conhecimento/experiência com AngularJS 1.x

## Contratação

PJ com possibilidades de CLT e participação nos lucros

## Nossa empresa

O iMusics é uma startup inovadora e disruptiva que une o melhor da tecnologia com o melhor da música e valores muito positivos. Possuímos um ambiente inovador, horários flexíveis, uma equipe multidisciplinar, influenciadores da música, tv e futebol e uma meta bem ambiciosa a atingir.

## Como se candidatar

Por favor envie um email para hr@imusics.com com seu CV anexado - enviar no assunto: Vaga Front-end developer

**Comment by Iqueda** [comment]
Até quando pode ser enviado o currículo?

**Comment by lucasrcdias** [comment]
@Iqueda Pode mandar!

**Comment by mtmr0x** [comment]
@lucasrcdias a vaga continua aberta?

**Comment by lucasrcdias** [comment]
@mtmr0x Opa, continua aberta!

**Comment by ErikGMatos** [comment]
@lucasrcdias estou a procura de um estágio com Front End, sou de SJC, vcs teriam alguma oportunidade aí?

**Comment by lucasrcdias** [comment]
@ErikGMatos Fala Erik!

Eu me desliguei da empresa e não sei se estão com essa vaga aberta ou para estágio. :/

**Comment by ErikGMatos** [comment]
@lucasrcdias  ah sim, sem problemas, vou dar uma verificada, obrigado pela atenção!

_Sent from my Motorola XT1058 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
