### ISSUE TITLE
[Belo Horizonte] React Developer na Queima Diária 

### ISSUE THREAD

**Issue by JohnCosta56** [frontendbr/vagas#3600]
## Nossa empresa

Somos uma startup inovadora e com crescimento a todo vapor! Visamos ajudar as pessoas a se tornarem aquilo que desejam ser através de uma vida mais saudável, harmoniosa e cheia de autoestima. Para isto acontecer, temos a maior e mais inovadora plataforma online do Brasil dedicada à atividade física e ao bem-estar.

## Descrição da vaga

Projetos de inovação e sustentação utilizando React.js;
Fornecer soluções de software ágeis usando as melhores práticas, como TDD e programação em par;
Contribuir para a evolução do produto.

## Local

Remoto ou Escritório, [Minas Gerais], [Belo Horizonte]

## Requisitos

**Obrigatórios:**
Experiência com análise, design e codificação;
Experiência e expertise em alguma dessas linguagens e seus frameworks: Javascript, Typescript, React.js e React Native.
Capacidade de trabalhar em equipe, em um ambiente colaborativo (pareando, dando feedbacks e influenciando seu time a cada dia ser melhor);
Visão sistêmica: você entende o que faz, porque faz e qual impacto seu trabalho tem no negócio, tem maturidade profissional e sabe lidar com conflitos, inspirar e desenvolver pessoas e está sempre em busca de se desenvolve

**Diferenciais:**
Bons conhecimentos de padrões de projeto, refatoração e testes unitários;
Experiência no desenvolvimento de aplicativos Mobile;
Experiência no desenvolvimento de aplicativos para Smart TV's;

## Benefícios

- Plano de saúde;
- Plano odontológico;
- Ajuda de custo para curso de idiomas;
- VR ou VA;

## Contratação

CLT

## Como se candidatar

Através do link: https://queimadiaria.gupy.io/jobs/484254

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@queimadiaria.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
