### ISSUE TITLE
[Remoto] Front-end Developer na Órama

### ISSUE THREAD

**Issue by ppaulojr** [frontendbr/vagas#3601]
## Nossa empresa

A Órama foi criada em 2011 por profissionais experientes do mercado financeiro, foi uma das pioneiras a oferecer investimento digital no Brasil. Além disso, foi premiada pela Amazon Web Services como uma das empresas mais inovadoras em serviços financeiros.

Presente em todo o país, com uma estrutura 100% online, também está comprometida com a entrega do melhor serviço para que o brasileiro possa investir de forma consciente e transparente.

## Descrição da vaga

Estamos em busca de desenvolvedor Angular que seja proativo e focado no trabalho. Não acreditamos em pessoas trabalhando por muitas horas, mas sim em pessoas trabalhando focadas numa jornada máxima de 40 horas.

## Local

Remoto ou Escritório, Rio de Janeiro - Botafogo

## Requisitos

**Obrigatórios:**
- Experiência com Javascript
- Experiência com Angular

**Desejáveis:**
- Capacidade de compreender e propor soluções para problemas complexos.
- Capacidade de se adaptar rapidamente a um ambiente de produção.
- Vivência com metodologia de Trabalho Ágil.
- Vivência com Code Review.

**Diferenciais:**
- projetos opensource

## Benefícios

- Plano de saúde
- Vale Alimentação ~R$ 460/mês
- Vale Refeição ~R$ 31/dia
- Auxílio creche
- Seguro de vida

**Diferenciais:**
- PLR (participação nos lucros/resultados) semestral
- Possibilidade de opções (sociedade) mediante mérito/destaque
- 40 horas semanais – trabalhe focado e trabalhe 40 horas.

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie e-mail com o subject [Angular 2020/2] para igor.mantovano@orama.com.br

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.
E-mail para contato em caso de não haver resposta: igor.mantovano@orama.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
#### Nível
- Pleno
- Sênior

**Comment by silversurferbeats** [comment]
dejo aqui mi porfolio:
https://silversurferbeats.github.io/portfolioweb/index.html

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
