### ISSUE TITLE
[Curitiba] Front-end Developer na FH

### ISSUE THREAD

**Issue by felipelssilva** [frontendbr/vagas#3603]
> Vaga Remota durante a pandemia

## Nossa empresa

A FH faz parte do Grupo itelligence, que se concentra nas soluções SAP em todo o mundo. e da NTT DATA Corporation, empresa multinacional japonesa de integração de sistemas e uma subsidiária da Nippon Telegraph and Telephone. Somos uma empresa de tecnologia especializada em processos de negócios e software, com sólida trajetória de crescimento. Desde 1999 no mercado, a companhia possui atuação global, com projetos realizados em mais de 30 países nos mais variados segmentos da indústria, como uma grande parceria SAP, presta serviços e comercializa software.

Contamos com uma estrutura robusta, que possui mais de 650 colaboradores. A FH, preza pela entrega de projetos personalizados para seus clientes, e, por este motivo, atua de forma regional com seis sedes localizadas em: Curitiba, São Paulo, Porto Alegre, Joinville, Rio de Janeiro, Goiânia.

Essa oportunidade é para trabalhar com projetos focado com desenvolvimento Front-end.

> Todas as vagas da FH são destinadas também para pessoas com deficiência.

## Descrição da vaga

Oportunidade para trabalhar com projetos focado com desenvolvimento Front-end.

## Local

Remoto

## Requisitos

**Obrigatórios:**

- Experiência em desenvolvimento frontend com habilidades em HTML5, CSS3, SASS, LESS e Javascript;
- Experiência em NPM, GRUNT e GULP
- Experiência com Bootstrap;
- Experiência com Semantic Web (W3C), Responsive Web, Progressive Enhancement;
- Conhecimento em ferramentas de versionamento (Bitbucket, Github);
- Conhecimento básico em ferramentas gráficas como Adobe Photoshop e Sketch ou similares;
- Domínio das melhores práticas de desenvolvimento, Design Patterns e Metodologias Ágeis;
- Cultura de reaproveitamento de código, componentização e qualidade embarcada ao longo do desenvolvimento;
- Cursado ou cursando Engenharia da Computação, Ciência da Computação, Sistemas de Informação, Análise e Desenvolvimento de Sistemas, Gestão em Tecnologia da Informação

**Desejáveis:**

- Conhecimento com SQLServer, MySQL ou algum outro Banco de Dados relacional;
- Vivência com padrão MVC, SEO, Webpack, prototipação, Hybris, React/Vue, Java, JSP/JSTL, Node, Jira,SQL;
- Atuação como Full-Stack, desenvolvendo em Java, C# ou alguma outra linguagem orientada a objetos;
- Atuação em projetos de e-commerce;
- Atuação em projetos com metodologias ágeis, como SCRUM;
- Graduação Completa;
- Inglês avançado.

## Benefícios

- Plano de saúde
- Plano odontológico
- VR / VA
- VT
- Auxílio creche
- Vale Gasolina
- Seguro de Vida
- GymPass
- Previdência privada

## Contratação

CLT

## Como se candidatar

Por favor envie um email para GroupTalentAcquisition@fh.com.br com seu CV anexado - enviar no assunto: Front-end Developer - FH
Ou candidate-se em: https://bit.ly/3iR0dmh

#### Alocação

- Remoto

#### Regime

- CLT

#### Nível

- Pleno
- Sênior

**Comment by aocabral** [comment]
Olá a todos, sou arquiteto de software na FH e estou passando para deixar mais alguns detalhes sobre a vaga:

- Os desenvolvedores trabalharão primariariamente com E-commerce, utilizando a plataforma SAP Commerce Cloud (antigo SAP Hybris);
- Estamos abertos a contratar profissionais em capitais ou cidades próximas de aeroportos com maior movimento, como Campinas.
- Temos 4 posições abertas para esta vaga.

**Comment by SaMatheus** [comment]
Boa noite! 

Fiquei muito empolgado com a vaga e já encaminhei meu curriculo.

Obrigado pela oportunidade =D

**Comment by aocabral** [comment]
> Boa noite!
> 
> Fiquei muito empolgado com a vaga e já encaminhei meu curriculo.
> 
> Obrigado pela oportunidade =D

Boa Matheus! O RH avalia e me encaminha, boa sorte!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
