### ISSUE TITLE
[Porto Alegre] Front-end Developer na Elysios

### ISSUE THREAD

**Issue by Levitrevisan** [frontendbr/vagas#3605]
## Nossa empresa

Somos a startup de inteligência agrícola que desenvolve soluções de sensoriamento, controle e gestão de cultivos. Como somos uma nova empresa, você será uma das primeiras pessoas a integrar o time, com isso, terá muita oportunidade de crescimento junto com a empresa! 
Somos ágeis e buscamos sempre as melhores práticas no ambiente de trabalho.
Você pode conhecer mais sobre nossas soluções e projetos em elysios.com.br

## Descrição da vaga

Procuramos alguém que tenha um perfil empreendedor, com pro atividade, responsabilidade e autonomia no dia-a-dia, sempre em busca de novos desafios e consciente da amplitude de um trabalho em uma startup. Ah, que seja, principalmente, gente boa!

Esta pessoa será uma das responsáveis pelo desafio de desenvolver o front-end de diversas aplicações web que são utilizadas por produtores familiares, técnicos agrícolas e demais entes da cadeia do agronegócio!

## Local

Remoto ou híbrido: (nosso escritório fica em Porto Alegre, RS, Bairro Bela Vista)

## Requisitos

**Obrigatórios:**
- Experiência em desenvolvimento de front Web: React
- Conhecimento de Banco de Dados e SQL

**Desejáveis:**
- Conhecimento em testes unitários e/ou de interface

**Diferenciais para qualificação do candidato:**
- Conhecimentos em Ruby on Rails
- Projetos opensource
- Conhecimentos em UI & UX
- Atenção ao detalhe

**Diferenciais do trabalho na Elysios:**
- Oportunidade de se desenvolver em diversas áreas e participar de diferentes tipos de projeto, já que trabalhamos com desenvolvimento de software, controle e automação para agricultura
- Horários flexíveis
- Contato com produtores de alimentos 

## Contratação

CLT ou PJ, dependendo da opção da pessoa!

## Como se candidatar

Por favor envie um email para rh@elysios.com.br com seu CV anexado - enviar no assunto: 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- Estágio
- PJ

#### Nível
- Júnior
- Pleno

**Comment by antoniotex** [comment]
Boa noite Levi, vocês estão avaliando part-time para PJ? Obrigado desde já.

**Comment by Levitrevisan** [comment]
@antoniotex Bom dia Antonio. Sim, estamos avaliando 👍

**Comment by evandersondev** [comment]
Fala @Levitrevisan ainda estão recendo cadidatos?

**Comment by Levitrevisan** [comment]
Boa tarde!

Encerramos a vaga ontem.
Logo abriremos novas 👍🏻👍🏻

________________________________
De: Evanderson Vasconcelos <notifications@github.com>
Enviado: Thursday, October 22, 2020 4:00:55 PM
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: Levi <levitrevisan@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [Porto Alegre] Front-end Developer na Elysios (#3605)


Fala @Levitrevisan<https://github.com/Levitrevisan> ainda estão recendo cadidatos?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
