### ISSUE TITLE
[REMOTO] Front-end Developer na Invillia

### ISSUE THREAD

**Issue by GabriellyLeonel** [frontendbr/vagas#3606]
## Nossa empresa
A experiência de trabalhar na Invillia é única. E global. Temos o nosso próprio jeito de conectar talentos e construir inovações.
Revolucionamos o ambiente de trabalho #Instation + somos experts em desenvolver soluções complexas para #GameChangers + temos uma metodologia única #EngagedbyDataPeopleAction + investimos em pessoas #InvilliaAcademy

## Descrição da vaga
O profissional será responsável em prover soluções técnicas para novas features e dar o suporte necessário as features já existentes, afinal, nem tudo são flores.

Esperamos também que essa pessoa auxilie os outros membros do time em questões técnicas não esquecendo de fornecer a melhor solução para o negócio.

## Local

100% REMOTO

## Requisitos
React e Hooks / ou React Native.
Gerenciamento de Estados (Redux);
HTML5, CSS3 (Sass), Javascript, JSS, WebSockets e Bootstrap/Material Design;
Git, Docker, Gulp, Webpack, Gerenciamento de Pacotes (ex: NPM, Yarn) e TDD;
Soluções e definições de arquitetura (Flux Architecture, SAGA Pattern);
Conhecimento teórico e prático em microserviços e APIs;
JWT, RestFull, Rest Hateoas, oAuth2.0;
Padrões de Projetos (DDD, Solid, Design Patterns);
Integração e entrega contínua (CI/CD);
Banco de Dados Relacional e Não-Relacional;
Desenvolvimento Ágil - Scrum e Kanban;

## Benefícios
AM, AO, SV, AJUDA DE CUSTO.

## Contratação
CLT

## Como se candidatar

Por favor envie um email para gabrielly.leonel@invillia.com com seu currículo e pretensão salarial CLT. 

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
