### ISSUE TITLE
[Remoto/SSA- Front End Mobile na Tec Fun] 

### ISSUE THREAD

**Issue by rafaelafrazao** [frontendbr/vagas#3607]
Quer impulsionar o desenvolvimento dos melhores aplicativos de esportes do mercado? É um entusiasta ou apaixonado pelo mundo do futebol? Então essa oportunidade é para você!

A TecFun utiliza a tecnologia para conectar pessoas e negócios de forma genuína, com muita alegria e diversão. Somos uma empresa formada e gerida por jovens com muita vontade de crescer fazendo acontecer! Trabalhamos com a criação de um fantasy game para times de futebol, personalizável para cada clube de futebol.

O desafio desse time de devs é estruturar aplicativos para acompanhamento dos clubes de futebol. Estamos com oportunidades abertas: Para Front end Dev (Flutter, Nativo - IOS e Android) desejável: React e Vanilla JS). 

Vagas com regime de contratação PJ, nível pleno e possibilidade de ser remoto mesmo após a pandemia. Se identificou com a oportunidade ou conhece alguém que faça sentido? 

É só se inscrever pelo link: https://bit.ly/3iXAt86

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
