### ISSUE TITLE
[Belo Horizonte] Front-end Developer na ETEG TECNOLOGIA

### ISSUE THREAD

**Issue by ETEG2020** [frontendbr/vagas#3609]
> Vaga Remota durante a pandemia

## Nossa empresa

- Somos uma empresa de TI, localizada em Belo Horizonte, com mais de 19 anos de mercado. Nossa missão é gerar tecnologias que possibilitem um maior equilíbrio entre trabalho e vida pessoal pela simplicidade e produtividade entregues. Simplificamos a vida das pessoas e empresas com o uso da tecnologia para que cada ser humano seja positivamente impactado na sua vida ao ser mais produtivo. 

## Descrição da vaga

- Desenvolvimento de APIs para integração dos sistemas
- Desenvolvimento de sistemas utilizando Javascritp, Node e React

## Local

Durante a pandemia, home office. Após a pandemia, home office também ;) Mas, se você quiser trabalhar na sede estamos localizados há 3 quarteirões do Pátio Savassi, Rua Raul Pompeia 101 / 11º andar - bairro São Pedro.

## Requisitos

**Obrigatórios:**
- 5 anos de experiência com Javascript
- 3 anos de experiência com Node

**Desejáveis:**
- conhecimentos em Javascript
- conhecimentos em Node
- Conhecimentos em React
- Conhecimento em RESTful APIs

## Benefícios
- Assistência Médica pela Allianz Saúde
- Assistência Odontológica - Odontoprev (desconto de R$20,00)
- Vale Alimentação de R$22,10 por dia útil
- Auxílio home office de R$90,00 por mês
- Possibilidade de continuar em home office após a pandemia

**Diferenciais:**
- 40 horas semanais
- Ambiente sempre ligado, mesmo em home office (slack aberto com todos os canais bombando!)
- Time unido, que busca solução junto
- Desconto de 70% no curso de Inglês :D
- Assistência médica sem desconto de coparticipação
- Alimentação e vale transporte também sem desconto
- Nosso plano é voltarmos a figurar entre as melhores empresas para se trabalhar - contamos com sua ajuda para isso ;)

## Contratação

PJ ou CLT - a combinar

## Como se candidatar

Por favor, acesse o link: https://jobs.solides.com/eteg/vaga/36440 para se cadastrar na vaga.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@eteg.com.br

#### Alocação
- Home office

#### Regime
- CLT ou PJ - você escolhe

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by ETEG2020** [comment]
Bom dia Felipe. A vaga continua em aberto.
