### ISSUE TITLE
[São Paulo] Desenvolvedor Front-End Angular

### ISSUE THREAD

**Issue by diogo-arantes** [frontendbr/vagas#361]
## Descrição da vaga

Buscamos um profissional front-end com conhecimentos em Angular(2/4) para desenvolvimento do front-end de uma plataforma BI.

Temos interesse por pessoas criativas e determinadas, dispostas a aprender, compartilhar conhecimento e que se interessem pelas mais recentes tecnologias de programação.

## Local

**Apenas São Paulo**
Remoto e escritório (2x/semana no Escritório, São Paulo - Prox.Faria Lima)

## Requisitos

**Obrigatórios:**
- Experiência e vontade de aprender Angular
- Bootstrap
- Typescript

- Mentalidade Startup, construir e crescer junto com a empresa.

**Desejáveis:**
- conhecimentos em Linux
- boas noções de design
- UX

## Contratação

PJ a combinar

## Como se candidatar

Enviar email para jobs@orfeus.com.br com assunto: Vaga Frontend ou chamar no whatsapp 98640 8282 (Diogo)

**Comment by mtmr0x** [comment]
@diogo-arantes a vaga continua aberta?

**Comment by diogo-arantes** [comment]
Boa tarde Matheus,

Não mais, mas pretendemos abrir outra. Enviei pf seu CV para
jobs@orfeus.combr.

Obrigado

Diogo Arantes

2017-07-10 12:44 GMT-03:00 Matheus Marsiglio <notifications@github.com>:
