### ISSUE TITLE
[São José dos Campos] Front-end Developer na DeepESG

### ISSUE THREAD

**Issue by fbaltor** [frontendbr/vagas#3610]
## DeepESG

Somos uma **greentech** brasileira em estágio inicial, disposta a revolucionar os critérios de mensuração de **impacto socioambiental** e assim dar as **novas diretrizes de investimentos sustentáveis**. 

Estamos em sintonia com a crescente demanda do mercado por investimentos baseados na filosofia **ESG - Environmental, Social and Corporate Governance**, que já se manifesta em nomes grandes e consolidados do mercado, como a XP Investimentos no Brasil e o fundo internacional Nordea. Surgimos para suprir o vácuo de ferramentas robustas de aferição de impacto, com um produto que se alinha também às pesquisas de vanguarda na academia: somos pois, a implementação em **estado da arte** de ferramentas como a idealizada por recentes artigos da Harvard Business School sobre o tema.

## Descrição da vaga

Na área de tecnologia somos um time pequeno (4 desenvolvedores) e integrado, com um perfil profissional proativo e ávido, dispostos a criar soluções on demand.

Procuramos um desenvolvedor de front-end para liderar a construção da nossa plataforma de visualização em constante sintonia com o restante da equipe. O modelo inicial de front-end é um site relativamente simples, priorizando a apresentação clara e visual dos dados e métricas calculadas pelo nosso core. 

## Local

Remoto ou híbrido, com escritório em São José dos Campos, São Paulo, Palmeiras de São José. 

## Requisitos

**Obrigatórios:**
- Conhecimentos básicos de arquitetura web (modelo cliente-servidor, etc).
- Javascript ES2015+.
- HTML semântico.
- Noções básicas de layout, CSS e design responsivo.
- Disponibilidade para jornada de trabalho integral (~40 horas semanais).

**Desejáveis:**
- Familiaridade com frameworks modernos: ReactJS, Vue, Angular ou similar.
- Consumo de APIs REST.
- Git.
- Metodologias ágeis, SCRUM.
- Database e SQL: Microsoft SQL Server, PostgreSQL, MongoDB.
- Disponibilidade de trabalhar presencialmente.

**Diferenciais:**
- Portifólio de projetos (pessoais, profissionais).
- Contribuição em projetos Open Source.

**Não estamos preocupados com idade, formação acadêmica ou extensa experiência profissional prévia. Nos interessa mais o seu conhecimento atual de programação, velocidade de aprendizado, curiosidade intelectual e comprometimento. Projetos anteriores, pessoais ou profissionais, são um grande ponto positivo.**

## Benefícios

- Remuneração em linha com o mercado, porém com **possibilidade de crescimento agressivo**.
- Possibilidade de trabalho remoto.
- Horário extremamente flexível.

## Contratação

PJ, MEI e CLT a combinar.

## Como se candidatar

Por favor envie um email para contato@deepesg.com com o link do seu GitHub (ou similar: GitLab, SourceForge, BitBucket, etc) e seu CV anexado - enviar no assunto: [VAGA FRONT-END] (com colchetes)

#### Regime
- CLT
- PJ
- MEI

#### Nível
- Júnior
- Pleno

**Comment by cp-yago** [comment]
Achei a vaga MUITO interessante, ja enviei meu CV!

**Comment by Pliavi** [comment]
Híbrido parece bom, sou de Caraguatatuba, dependendo de onde for aí, acho que é legal ir um dia ou outro na semana, pois é +- 1:30 de viagem só
