### ISSUE TITLE
[Fortaleza / CE] Full Stack Developer @ Advance Comunicação

### ISSUE THREAD

**Issue by lucas-varela** [frontendbr/vagas#3611]
## Nossa empresa
A [Advance](https://advance.com.br/) é uma agência _one-stop shop_ voltada para o crescimento sustentável de marcas em constante transformação. Aliamos o pensamento estratégico a ideias criativas, com o objetivo de gerar retorno efetivo aos nossos clientes. O resultado disso é que somos a agência do Ceará com maior número de clientes Top of Mind. Com 25 anos de mercado, a Advance atua em todo o Brasil e está entre as maiores agências de comunicação do Norte e Nordeste.

Acreditamos que as marcas fortes, amadas e desejadas vendem mais e melhor. Mas, acima de tudo, acreditamos na propaganda honesta, ética e responsável. É com esse pensamento que abraçamos várias causas e implantamos políticas socioambientais para contribuir com o cuidado com pessoas e com o meio ambiente.

Nosso time de Design e Tecnologia é um dos braços digitais da agência, e é responsável pela criação de sites, aplicativos, lojas e outras experiências digitais para grandes clientes como Pague Menos, RioMar, Tijuca Alimentos, Ari de Sá e Angola Cables.

## Local

A vaga é **presencial**. Estamos trabalhando em regime de home-office por conta da pandemia, mas procuramos candidat@s que possam comparecer presencialmente quando for seguro para todos.
 
Ficamos na [Rua José Avelino](https://g.page/advancecomunicacao?share), no Centro de Fortaleza, Ceará.

## Descrição da vaga
Estamos em busca de candidat@s que gostam trabalhar implementando sites e aplicações web utilizando tecnologias estáveis, mas que não tem medo de se aventurarem com novas tecnologias em momentos oportunos.

Internamente, usamos diversas tecnologias, e nos adaptamos às necessidades dos nossos clientes. Ultimamente, tentamos trabalhar o máximo possível com Jamstack, e nos últimos meses produzimos vários sites e aplicações utilizando Next.js, com resultados de agilidade no desenvolvimento e desempenho no Lighthouse imprescindíveis.

Apesar do forte foco no Jamstack e tecnologias serverless, sabemos que a maioria das aplicações precisa de uma fonte de conteúdo, e é por isso que criamos soluções in-house para o gerenciamento de conteúdo dos nossos clientes utilizando APIs. Trabalhamos com Laravel nessas soluções, e gostamos da agilidade do desenvolvimento e na facilidade de uso das várias ferramentas de desenvolvimento feitas para a framework.

Pensando nisso, estamos buscando profissionais confortáveis com desenvolvimento web com React e PHP.

### Obrigatórios
- Experiência com PHP 7 e JavaScript ES6+
- Experiência com React, incluindo Hooks
- Experiência com Laravel
  - Prezamos em utilizar as versões mais recentes, dando suporte às versões 5.8 a 7.0
- Experiência com CSS moderno

### Desejáveis
- Conhecimento dos princípios e práticas de desenvolvimento de software ágil
- Conhecimento em bancos de dados relacionais, especialmente o MySQL
- Inglês intermediário

### Diferenciais
- Experiência com AWS
- Experiência com Next.js
- Experiência com Emotion, styled-components ou frameworks parecidas
- Experiência com metodologias de teste, como BDD ou TDD
- Experiência em desenvolvimento e consumo de APIs GraphQL

## Benefícios
- Plano de saúde
- Ticket refeição
- Vale-transporte
- Folga no dia do aniversário

## Diferenciais
- Workshops semanais com toda a equipe da agência
- Escritório aberto e descontraído
- Café de graça
- Áreas de descanso com redes e poltronas

## Contratação

CLT

## Como se candidatar

Envie um email para [lucas.varela@advance.com.br](mailto:lucas.varela@advance.com.br?subject=Vaga%20de%20Desenvolvimento%20Full%20Stack) com o assunto `Vaga de Desenvolvimento Full Stack`. 

No corpo do email, basta nos enviar seu LinkedIn, seu currículo e, se você quiser, seu perfil no GitHub. Responderemos assim que possível com as instruções para o nosso teste.

Quer spoilers sobre o nosso teste? Você pode dar uma olhadinha [nesse repositório](https://github.com/penseadvance/tes-tee-full-stack).

## Tempo médio de feedbacks
Em geral, respondemos dentro de uma semana. Sempre damos feedback sobre o teste, independente do resultado.

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
