### ISSUE TITLE
[REMOTO] Front-end Developer Sr na Pier Digital

### ISSUE THREAD

**Issue by gabriel-franzoni-pier** [frontendbr/vagas#3612]
:warning: **Vaga exclusiva para mulheres!**

## Nossa empresa

Cultivamos na Pier a mesma semente que estamos fomentando no mundo: a confiança. E fazemos isso construindo relações fortes, capazes de mudar a forma com que nos relacionamos com o mundo.

Buscamos quem tenha o peito aberto porque não sabemos viver longe da transparência. Levamos isso tão a sério que aqui na Pier **todos conhecem a estrutura societária e têm acesso aos salários de qualquer funcionário**.

Somos inquietos por natureza e gostamos de gente disposta a desbravar e construir o novo. Trabalhamos com autonomia porque acreditamos que adultos tratados como crianças correm o risco de começar a agir como tais. Vem saber mais sobre a cultura Pier nesse artigo que está em nosso blog.

Bem-vindo ao mundo Pier! :)

## Descrição da vaga

Você será o ponto de referência de mobile dxs Software Engineers da Pier! 🤩

Escrever código para implementar, junto com times de produto, novas funcionalidades nas nossas plataformas e construir uma nova maneira de oferecer seguros no mundo
Estar aberto para trabalhar com Front, App, Back, Scripts - o que o time precisar
Manter a qualidade de código e engenharia num nível invejável de excelência
Manter o front-end resiliente, testado, e capaz de suportar o nosso crescimento
Ajudar a construir decisões de arquitetura dos nossos aplicativos mobile

## Local

Exemplo: Remoto

## Requisitos

**Obrigatórios:**
- Experiência com React/React Native ou desenvolvimento Mobile
- Testes automatizados e TDD
- Clean code e design patterns
- Conhecimento do funcionamento de APIs padrão REST e microsserviços

**Desejáveis:**
- Em torno de 3 anos de experiência com Javascript/Typescript e biblioteca React Native
- Em torno de 3 de experiência com desenvolvimento mobile nativo: iOS e/ou Android
- Experiência em empresas de crescimento e mudança em ciclos rápidos
- Back-end for frontends (BFF)
- Domain Driven Design (DDD)
- Data Analysis

## Benefícios

- Plano de saúde
- Plano odontológico
- VR flexível (via Caju)

## Contratação

CLT

## Como se candidatar

[Link para a vaga](https://pier.recruitee.com/o/engenheiras-de-software-sr-mobile-web-frontend/c/new)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada etapa, exceções são combinadas durante a entrevista.
E-mail para contato em caso de não haver resposta: contato@pier.digital

#### Alocação

- Remoto

#### Regime
- CLT

#### Nível

- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
