### ISSUE TITLE
[SÃO PAULO] [OPORTUNIDADE] Tech Lead | KONTIK

### ISSUE THREAD

**Issue by TMPenha** [frontendbr/vagas#3613]
A KONTIK PROCURA POR VOCÊ!

Nós da Kontik oferecemos os melhores produtos e serviços  para a gestão de viagens corporativas, lazer e eventos através de soluções tecnológicas ágeis e inovadoras. Atualmente estamos encarando o desafio de desenvolver um novo negócio(TIPTRIP) no mercado do turismo e buscamos o primeiro profissional de tecnologia desse novo time , um “Tech Lead”.

Esse profissional sênior será responsável  por liderar e auxiliar a construção de um time disruptivo de tecnologia (infraestrutura, back-end e front-end), pelo o roadmap digital da empresa, o fortalecimento da cultura de excelência em tecnologia e a realização da  interface entre as áreas de negócio e de tecnologia. 

Já a oportunidade segue o formato a seguir: 

- Contratação: PJ
- Modalidade: Presencial
- Remuneração: Competitiva ao mercado

Se identificou e quer saber um pouco mais sobre o desafio de ser Kontik, dá uma olhadinha no link a seguir https://byintera.in/166

Não faz sentido pra você mas conhece alguém que pode se interessar? Comenta aqui embaixo, compartilhe o link ou me chama no privado e vamos conversar!

Abração e um sorriso de orelha a orelha =)

#vaga #vagasbyintera #oportunidade #emprego #desafiasse #techlead #kontik

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
