### ISSUE TITLE
[Três Lagoas, MS] Front-end Developer na Leiloapp

### ISSUE THREAD

**Issue by FelipeWaddington** [frontendbr/vagas#3614]
Somos uma startup dando start ao nosso projeto envolvendo o Agro Negócio, você poderá ajudar a definir padrões e metodologias. Assim com influenciar em diversas tomadas de decisões. Irá trabalhar com que não é iniciante nesse mundo das startups e que entende do negócio e de tecnologia.

Estamos sediados em Três Lagoas/MS, aceitamos o trabalho remoto. Mas se você for da região ou do estado, será um ponto a mais, pois queremos fomentar a indústria da tecnologia em nossa região.

O excelente desempenho e alto engajamento poderá resultar em um convite para ser sócio da nossa startup.

Front-end Developer / full-time

Três Lagoas, Mato Grosso do Sul, Brazil, Remote Allowed

Job description

**O que precisa saber para se candidatar:**
- JavaScript e Vue
- Básico de SSR
- Básico de PWA
- Básico de Teste Automatizado

**Você irá trabalhar com (e irá aprender):**
- Vue3 / Vuetify / Nuxt
- Serverless
- WebSockets
- RESTfull / Swagger / Grapql
- S3 / Cloudfront
- Gitlab CI/CD

**Como é o nosso backend?**

Python/Django rodando em um Lambda da AWS conectado em um banco de dados PostgreSql Serverless
Não é pré-requisito da vaga, apenas um informativo. Se estiver apto para ser fullstack, isto contará como ponto positivo

**Contratação**

PJ a combinar

Como eu faço para me inscrever?
E-mail para: talentos@leiloapp.com.br

**Comment by rarysson** [comment]
Quais os níveis de experiências que vocês estão procurando?

**Comment by FelipeWaddington** [comment]
> Quais os níveis de experiências que vocês estão procurando?

Olá Rarysson, estamos buscando nível pleno.

Atenciosamente

**Comment by antoniotex** [comment]
Oi Felipe, Boa noite. Vocês estão avaliando part-time? Obrigado desde já.

**Comment by FelipeWaddington** [comment]
Olá, tudo bem?

Nessa etapa estamos selecionando os currículos, em outras etapas avaliamos
a disponibilidade dos candidatos de acordo com o perfil da vaga!

Atenciosamente

Em seg., 28 de set. de 2020 às 19:22, Antonio Carlos <
notifications@github.com> escreveu:
