### ISSUE TITLE
[Belo Horizonte] Front-end Developer na SmarttBot

### ISSUE THREAD

**Issue by guilhermethales** [frontendbr/vagas#3615]
> Vaga Remota durante a pandemia

## Nossa empresa

A SmarttBot é uma empresa especializada em automatização de investimentos na bolsa de valores, que movimenta 3bi por dia, certificada pela Great Place to Work® Brasil. Trabalhamos todos os dias para democratizar o investimento realmente inteligente!

Como um dos principais produtos da empresa, temos a plataforma da SmarttBot, focada para traders operarem na bolsa de forma automatizada. O trader configura sua estratégia em nossos robôs (algoritmo online), que enviam as ordens diretamente para as principais corretoras do país.

Com o desafio de democratizar o investimento para pessoas físicas, a SmarttBot lançou este ano a SmarttInvest, uma plataforma de automatização de investimentos que disponibiliza carteiras recomendadas, onde o usuário pode seguir e começar a investir em poucos minutos.

Estamos impactando o mercado financeiro e a forma como as pessoas investem! Seria ótimo ter você com a gente inovando, gerando valor para os nossos clientes e vivendo grandes desafios! 

## Descrição da vaga

Procuramos uma pessoa que se identifique com nossos valores #respeito #leveza #raça,raça,raça #inovação #evolução, com grande experiência na área de desenvolvimento de software, que irá atuar em projetos de grande impacto na bolsa de valores, utilizando React.js e tecnologias em torno dela nas duas principais plataformas: SmarttBot e SmarttInvest.

## Local

A vaga é presencial, porém, no atual cenário(pandemia) todos estamos trabalhando em regime de home office.

Nosso escritório se encontra na Rua Antônio de Albuquerque, 156, 16o andar, no bairro Funcionários - BH/MG.

## Requisitos

**Obrigatórios:**
- Dominar JavaScript, HTML, CSS, ES6+;
- Conhecimento em pelo menos um framework atual, como React (principal), Angular, VUE;
- Conhecimento sobre Node.js, Redux, bundlers e transpilers;
- Desenvolvimento e automatização de testes;
- Conhecimento em padrões de projeto;
- Experiência em integrações utilizando API REST;
- Dominar ferramenta de controle de versão Git.

**Desejáveis:**
- Ter experiência em CI/CD;
- Ter vivência com algum banco de dados relacional;

**Diferenciais:**
- Conhecimento em PWA e Service Workers. – Ter experiência em conteinerização (docker);
- Conhecimento em serviços de nuvem, preferencialmente AWS.

## Benefícios

- Plano de Saúde (Co-participativo) e Odontológico pela UNIMED, estendido a cônjuge e filhos. Cuide da sua saúde e da sua família. #respeito
- Licença maternidade, paternidade estendidas, além de licença na adoção proporcional a idade da criança. Esse é um momento de grande importância na vida do Botter, e para a gente faz todo sentido você ter mais tempo com a sua família nessa nova etapa :). #respeito
- Vale Refeição e/ou Vale Alimentação no valor de R$30,00 por dia… para você comer/beber à vontade. #respeito
Temos snacks, lanches e frutas a vontade! E de quebra refri, sucos e aquela cervejinha no dia a dia (beba com moderação ^^). #leveza
- GymPass, pois cuidar de sua saúde física e mental é importante. #leveza
- Vale Transporte, para você que usa o busão de acordo com a sua necessidade...com desconto de apenas R$1 real! #inovação
- Subsídio para cursos, treinamentos, eventos, congressos, etc. Entendemos que o seu desenvolvimento precisa ser constante. #evolução
- Gratuidade em qualquer plano SmarttBot e SmarttInvest. Seja uma sardinha e conte com nosso apoio. #inovação
- Day Off aniversário, aproveite e curta esse grande dia, ele é todo seu. #raçaraçaraça
- Day Off aniversário de SmarttBot (a cada um ano de empresa)! Pois a cada dia e a cada ano você faz parte dessa trajetória e comemorar é preciso. #raçaraçaraça
- Horário Flexível. #leveza
- Your dress code! Seja você mesmo, seja feliz. #respeito

## Contratação

A combinar

## Como se candidatar

https://jobs.kenoby.com/smarttbot/job/pessoa-desenvolvedora-front-end-senior/5d5db6d6105b24173999d9bc

#### Alocação
- Alocado

#### Regime
- CLT
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by guilhermethales** [comment]
A vaga ainda está aberta.
