### ISSUE TITLE
[Remoto] Senior Front-end Developer na Contabilizei

### ISSUE THREAD

**Issue by KarineLiuti** [frontendbr/vagas#3616]
# [Remoto] Front-end Developer na Contabilizei

> Vaga Remota

## Nossa empresa

Com mais de 20 mil clientes, atuando em mais de 50 cidades do Brasil, a Contabilizei está mudando a maneira como o micro e pequeno empreendedor gerencia o seu negócio em nosso país. Continuamos a crescer rapidamente, criando novos produtos e proporcionando que o empreendedor seja o contador de sua própria história.

Por aqui, somos mais de 400 pessoas, todas selecionadas a dedo, e que levam muito a sério o nosso propósito de resolver o problema real brasileiro, trabalhando em busca de soluções inovadoras para facilitar a vida dos nossos clientes.

## Descrição da vaga
Com mais de 20 mil clientes, atuando em mais de 50 cidades do Brasil, a Contabilizei está mudando a maneira como o micro e pequeno empreendedor gerencia o seu negócio em nosso país. Continuamos a crescer rapidamente, criando novos produtos e proporcionando que o empreendedor seja o contador de sua própria história.

O Squad Ativação é responsável por apoiar os clientes que estão iniciando sua jornada na Contabilizei. Esse time tem como missão propor e desenvolver as funcionalidades que facilitarão o processo tanto para os nossos clientes, quanto para a própria Contabilizei. Garantir a simplicidade para o micro e pequeno empreendedor, em um processo burocrático como a abertura de empresas no Brasil, é um desafio a se vencer a cada dia. Por aqui, construímos juntos essas soluções, pois entendemos que o sucesso do empresário, é o nosso sucesso.

Acreditamos que a diversidade promove o crescimento sustentável. Na Contabilizei queremos que você seja a melhor versão de si, e as oportunidades são para todos. Valorizamos as diferenças, e estamos abertos a receber pessoas com quaisquer deficiências, gênero, etnia, orientação sexual e diferentes mindsets. Juntos, construímos a Contabilizei do nosso jeito.

**Um dia típico inclui:**

- Desenhar a solução (arquitetura, modelagem, design de código), desenvolvendo sistemas que entreguem valor e alinhados com os objetivos da companhia;
- Entregar e revisar código testável assegurando qualidade das entregas da equipe, resolvendo problemas e impedimentos que impactam no prazo acordado e realinhando expectativas acordadas;
- Idealizar sistemas e funcionalidades do lado do cliente (front-end) para fornecer aos usuários finais acesso às funções do sistema;
- Projetar e construir componentes de aplicativos front-end para incluir scripts a serem executados em navegadores web de diversos dispositivos do lado do cliente, avaliando experiência do usuário e desempenho da aplicação;
- Identificar problemas na base de código existente e de arquitetura e aplicar melhorias;
- Disseminar e compartilhar conhecimento com as comunidades interna e externa; mantendo-se atualizado sobre tendências e melhores práticas, e contribuindo para aumentar a relevância da companhia frente o mercado;
- Ajudar no desenvolvimento técnico de profissionais com menos experiência, ajudando a desenvolver um time com nível adequado de qualificação.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Graduação concluída ou cursando em Análise de Sistemas, Engenharia da Computação ou áreas afins;
- Ampla habilidade com Fronts responsivos, Javascript (ES5, ES6), HTML5 e CSS3;
- Experiência em AngularJS, VueJS ou React;
- Consumo de API's RESTful;
- Noções de UX/UI;
- Conhecimentos em controle de versão (Git);
- Conhecimento sobre métodos ágeis de desenvolvimento.

**Desejáveis**
- Experiência em desenvolvimento de aplicativos mobile;
- Controle de Estado, Vuex ou Redux;
- Prática com automação de testes (Selenium, Jasmine, Jest).

## Benefícios

**Diferenciais:**
Nossas Guardiãs e Guardiões acreditam e perseguem nosso propósito: Entendem que o sucesso do empresário é o nosso sucesso. Oferecemos um ambiente descontraído, completamente colaborativo, com ritmo acelerado e desafiador, a fim de atingir resultados e promover a melhor experiência aos nossos clientes, construindo uma jornada de sucesso. Acreditamos no protagonismo, aqui você constrói sua carreira da sua forma e cresce junto com a Contabilizei. 
Aqui, você terá a oportunidade de gerar um grande impacto positivo, construindo o futuro de como os empresários brasileiros gerenciam seus negócios com sucesso.

## Contratação
CLT

## Como se candidatar
Acesse: [Gupy Contabilizei](https://contabilizei.gupy.io/jobs/473674?jobBoardSource=gupy_public_page)

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Senior

**Comment by rayanmarcus** [comment]
Queria muito trabalhar com vocês, pena que não tem vaga remoto pra júnior. :/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
