### ISSUE TITLE
[REMOTO] Front-End Developer (Junior) na Mainô

### ISSUE THREAD

**Issue by rhgrow** [frontendbr/vagas#3617]
## Nossa empresa

QUEM É A MAINÔ?

Nosso propósito é utilizar tecnologia para ajudar as empresas e os profissionais a lidarem com as especificidades do comércio internacional. Para fazer isso, nós escolhemos ser bons (não somos vacilões, falamos a verdade com respeito e transparência, somos honestos e corretos com todos). Respeitamos as individualidades. Queremos nos superar constantemente, crescendo com as dificuldades que enfrentamos, ou seja, basicamente somos Saiyajins. Usamos a criatividade para resolver problemas (we hack the task) e somos apaixonados pela empresa que a gente ajuda a construir.

A gente acredita demais no que faz e o nosso sonho é ser uma plataforma global de serviços para Comércio Exterior com liderança expressiva na América Latina.

A cultura é nosso traço mais importante e você pode nos conhecer mais através de nosso instagram: https://www.instagram.com/mainosistemas/

Estamos buscando pessoas que tenham um forte senso de trabalho em equipe para integrar nosso time.

## Descrição da vaga

Esta é uma vaga para compor o nosso time de Pesquisa e Desenvolvimento. Buscamos por um profissional Junior, com muita vontade de aprender e crescer. Você não precisa vir sabendo tudo, a gente vai ensinar! O que esperamos da sua parte é curiosidade, dedicação e comprometimento. :) 
Você irá participar de ciclos de sprints, implementação de novas funcionalidades e melhorias incrementais em nosso sistema.

## Local

Remoto, então você pode se candidatar de qualquer lugar do mundo! :)
A título de curiosidade, a empresa fica localizada no Rio de Janeiro

## Requisitos

**Obrigatórios:**

Conhecimento em:
- HTML
- CSS
- Javascript (ES6 será diferencial)
- Ruby on Rails
- PostgresSQL

- Conhecimento em serviços AWS ou Heroku
- Conhecimento sobre APIs REST

**Desejáveis:**
- Ter alguma experiência com trabalhos ou projetos.

**Diferenciais:**
- Já ter sido responsável por resolver problemas em ambiente de produção.

## Salário e Benefícios

- Salário entre 2k e 3k.
- VR ou VA (25,00 por dia)
- Plano de saúde, após 3 meses.

## Contratação

CLT

## Como se candidatar

Envie seu currículo para nosso email: selecao.rhgrow@gmail.com, colocando no assunto DEV JUNIOR

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: selecao.rhgrow@gmail.com

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior

**Comment by IggorSantos** [comment]
CV enviado

**Comment by margotpaon** [comment]
Cv enviado!

Em sex., 25 de set. de 2020 às 14:41, rhgrow <notifications@github.com>
escreveu:

**Comment by SaMatheus** [comment]
Acabei de enviar também, pela segunda vez heheheeh =D

Quero mesmo trabalhar com vocês!

**Comment by Luizfelippepucca** [comment]
Enviado!

**Comment by rhgrow** [comment]
Obrigada a todos que se candidataram. Vaga fechada! :)
