### ISSUE TITLE
[Remoto] Desenvolvedor Full Stack @Brainship

### ISSUE THREAD

**Issue by srjope** [frontendbr/vagas#3619]
Descrição: a Brainship é uma startup de e-learning movida pela paixão de disseminar o conhecimento. Acreditamos que o compartilhamento da experiência daqueles que já trilharam o caminho das pedras em suas áreas, é o ponto de guinada na vida de profissionais, empresários e estudantes que desejam ser impulsionados em suas carreiras.

Site: https://brainship.com.br

Local: São Paulo, porem profissionais de todos os Estados podem se candidatar, pois o trabalho é remoto.

Contratação: termo de prestação de serviços (B2B).

Requisitos principais: bons conhecimentos para desenvolver software usando as tecnologias/linguagens/frameworks NodeJS, React, Next.js, Graphql, Banco de Dados NoSQL.

Diferencial: conhecimento em arquitetura serverless, conhecimento em mensageria e arquitetura orientada a eventos.

Interessados preencher o seguinte formulário: https://forms.gle/y5SSLiQDueaHR4vC6

**Comment by srjope** [comment]
Ainda estamos recebendo inscrições!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
