### ISSUE TITLE
[São Paulo] Front-End Coder (Fhinck/Cubo)

### ISSUE THREAD

**Issue by MartinaCarvalho** [frontendbr/vagas#362]
## Descrição da vaga

O time da Fhinck está crescendo \o/

Se você acredita que criatividade e tecnologia podem contribuir com resultados empresariais e gostaria de ajudar grandes organizações a fazer mais com menos, esta oportunidade é para você.

Procuramos um Desenvolvedor Front End que consiga resolver problemas complexos com precisão e criatividade e que, além de tudo, seja capaz de criar soluções que auxiliem nossos clientes a acompanhar seus processos e otimizar suas operações. 

Para esta posição, buscamos profissionais que vão muito além do domínio de uma tecnologia. Estamos interessados em desenvolvedores web criativos, que consigam rapidamente transformar ideias e sonhos em realidade.

Quer conhecer melhor a Fhinck e saber os detalhes desta posição? Acesse www.fhinck.com/recrutamento.html

## Local

São Paulo - Vila Olímpia

## Requisitos

**Obrigatórios:**
- Experiência como Desenvolvedor Web.

**Desejáveis:**
- Conhecimento em HTML5, CSS3 e Javascript. JQuery, AJAX e PHP.

**Diferenciais:**
- Conhecimento de linguagens para desenvolver aplicações em desktop/windows, tais com C++;
- Experiência em Sartup.

## Contratação

CLT a combinar

## Nossa empresa

A Fhinck é uma startup brasileira, localizada no Cubo/SP, com foco no desenvolvimento de soluções inteligentes que melhoram a eficiência das das operações de backoffice. Com nossos produtos, ajudamos grandes companhias a fazer mais com menos.

## Como se candidatar

Ficou interessado na vaga? Mande um e-mail pra jobs_is_alive@fhinck.com contando um pouco mais sobre você, com um currículo em anexo (assunto: Vaga Front-End - GitHub).

**Comment by LFeh** [comment]
Startup muito legal aqui do Cubo pessoal. Boa sorte 😉

**Comment by matheusggds** [comment]
@LFeh O que seria o Cubo? Já ouvi falar sobre em alguns lugares, tem algum lugar que posso saber mais? (sem querer fugir do tópico da pergunta, mas já fugindo)

**Comment by arthureggert** [comment]
@matheusggds Acredito que o [Cubo](https://cubo.network/) é um espaço de coworking em SP

**Comment by LFeh** [comment]
@matheusggds 

É um espaço privado de coworking que conta com quase 60 startups, o ambiente é bastante inovador e criativo. Pode conhecer mais no nosso [site](https://cubo.network/)

Eu trabalho no Cubo, mas é para o próprio Cubo, nos produtos digitais (temos vaga #354). 

Mas a vaga em questão dessa issue é para uma startup residente.

**Comment by mtmr0x** [comment]
@MartinaCarvalho a vaga continua aberta?
