### ISSUE TITLE
[Home-office] Front-end Developer na ITeam

### ISSUE THREAD

**Issue by VivianeRHTI** [frontendbr/vagas#3620]
## Descrição da vaga

Desenvolvimento Front-end com React (JSX), Javascript.

## Local

Home-office

## Requisitos

Experiência em projetos com React (JSX), Javascript (ES6), Sass, Less; Experiência em consumo de API (RESTfull);
Produção de telas e recortes HTML, Responsive Web Design; Pacote Adobe (Photoshop, XD, Illustrator);
Experiência em projetos Web (Hotsites, Intranets, E-commerces e Integradores);
Continuous integration, Controle de Versão (GIT); Swagger, Postman.
Desejável: Angular
Metodologia: SCRUM

**Obrigatórios:**
React (JSX), Javascript (ES6), Sass, Less; API (RESTfull);
HTML, Responsive Web Design; Pacote Adobe (Photoshop, XD, Illustrator);
Experiência em projetos Web (Hotsites, Intranets, E-commerces e Integradores);
Controle de Versão (GIT).

## Contratação

Indeterminado
PJ

## Nossa empresa

Há mais de 15 anos presente no mercado, a ITeam oferece o comprometimento com o cliente.
Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 
O relacionamento da ITeam é baseado no amplo comprometimento com os valores e objetivos dos nossos Clientes, fornecendo soluções e serviços de TI que contribuam para a realização de seus objetivos.

## Como se candidatar

Envie um e-mail para viviane.pereira@iteam.inf.br com seu currículo atualizado e pretensão de valor - enviar no assunto: Vaga Front-React.

## Labels

- 🏢 Horário comercial
- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ PJ

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
