### ISSUE TITLE
[São Paulo/Remoto] Front-End Developer na Smartia

### ISSUE THREAD

**Issue by danielpossa** [frontendbr/vagas#3621]
## Our Company

Smartia is a Brazilian startup powered by QuinStreet, Inc (NASDAQ: QNST), a Silicon Valley company founded in 1999 and the world leader in Digital and Performance Marketing. We use technology to match consumers with the offers that best suit their needs. With more than 10 years of experience in the Brazilian market, Smartia works directly with clients like Porto Seguro, Youse, Bradesco, Minuto Seguros, Qualicorp and many other big and small players in the Financial Services scene in Brazil.

## Job Description

We’re looking for a technically-minded Front-End Developer that can hand-code HTML and CSS to the latest standards. You will work side by side with the design team to deliver beautiful user interfaces for desktop and mobile, website themes and forms. You should be able to interact with a remote English-speaking technical team and be able to work closely with the design team.

**Please send your CV in English - Interviews are in English.** (Please only sign up if your English level matches this requirement.)

## Local

Smartia is based in São Paulo (SP). We provide the essential so you can work from anywhere you like!

## Skills

**Essential:**

- HTML, CSS hand-coded to the latest standards.
- Basic JavaScript
- Familiar with Git
- Intermediate level English (or above)

**Valuable:**

- Experience with ReactJS components
- SVG
- Experience of app UI development

## Benefits

- Health Plan
- Dental Plan
- Life Insurance
- VR - R$ 40/dia

## Work Regime

CLT (Brazilian law)

## How to apply

We'd love to tell you more and hear it from you, send your **CV and Portfolio** to **careers@smartia.com.br** - subject: "HTML/CSS Designer"

#### Alocação
- Remoto (office in São Paulo)

#### Regime
- CLT

**Comment by paulo70** [comment]
@danielpossa Essa vaga foi postada já faz algum tempo, e vocês retornam o email dizendo que o processo iria se iniciar após uma semana ou duas, isso foi em 16 agosto.
Acho que seria legal ter mais clareza nos feedbacks.

**Comment by danielpossa** [comment]
@paulo70, apesar da descrição parecida as vagas são diferentes. A anterior era mais focada em Design e a vaga foi preenchida com um profissional encontrado aqui pelo grupo (ainda em processo). Esta vaga de agora é para Developer Front End especificamente, não há avaliação de portfolio. Obrigado

**Comment by Mufolk** [comment]
> @paulo70, apesar da descrição parecida as vagas são diferentes. A anterior era mais focada em Design e a vaga foi preenchida com um profissional encontrado aqui pelo grupo (ainda em processo). Esta vaga de agora é para Developer Front End especificamente, não há avaliação de portfolio. Obrigado

Vocês então desejam ou não q enviemos o portffólio? pq ali tá pedindo
