### ISSUE TITLE
[Remoto/São Paulo] Pessoa desenvolvedora Front-end na Pagar.me

### ISSUE THREAD

**Issue by rsmelo** [frontendbr/vagas#3622]
> Vaga Remota durante a pandemia

## Já conhece o Pagar.me?

Somos uma empresa focada em desenvolver soluções para os mercados de pagamento e financeiro no Brasil e fazemos parte do Grupo Stone Co. De pequenas lojas e startups a grandes e-commerces e marketplaces, criamos uma estrutura de pagamentos poderosa e flexível para atender diferentes clientes.

Aqui, você irá trabalhar com um time apaixonado por desafios, focado no atendimento personalizado aos nossos clientes e em busca dos melhores resultados em suas entregas. Quer mais? Tudo isso em um ambiente descontraído e com uma galera que é referência no mercado de tecnologia!

Conheça mais sobre a nossa empresa no site www.pagar.me

### O que é ser Pessoa desenvolvedora Front-end | Software Engineer Front-end.?

 Aqui você vai colaborar com product managers, designers e software engineers para identificar oportunidades e implementar soluções e produtos para os nossos clientes. Desenvolver serviços e sistemas. Melhorar arquitetura e ou design dos sistemas atuais;

Buscamos alguém que se envolva ativamente na construção de produtos do começo ao fim, desde a experimentação, design, implementação e deploy, até o feedback dos clientes;

Trabalhar em conjunto com todo o time de tecnologia, revisando o trabalho de outras pessoas, participando de decisões importantes de produto e tecnologia, e garantindo a saúde dos nossos serviços.

## Local

Estamos remoto sem previsão para retomada ao escritório e com possibilidade de remoto mesmo após a volta.
Nosso escritório fica localizado na Vila Olimpia, São Paulo.

## Requisitos

**Obrigatórios:**
- Experiência com CSS, HTML e Javascript;
- Experiência no desenvolvimento de uma aplicação React em produção;
- Experiência com testes automatizados;

**Desejáveis:**
- Experiência no desenvolvimento de interfaces mobile first.
- Experiência com aplicação de um design system em um produto;
- Experiência com desenvolvimento em React Native;
- Experiência com Amazon AWS (S3 & Cloudfront);
- Experiência na implementação de processo de integração contínua e entrega contínua.

## Como trabalhamos

Nossos produtos utilizam um ecossistema baseado em React no front-end, possuímos um design system e sua implementação como um conjunto de bibliotecas de componentes utilizando React e CSS.

Ainda possuímos uma dashboard legada escrita em Angular.js, a qual damos manutenção. Sempre buscamos as ferramentas mais adequadas para resolver os nossos problemas, sem nos prendermos a uma tecnologia específica.

Gerenciamos nossa infraestrutura através de infrastructure-as-code, deployando nossas aplicações na AWS. Todo serviço que escrevemos tem uma boa cobertura de testes, consegue ser facilmente escalável do ponto de vista de infraestrutura, e tem monitoramento ativo sobre ele.

Por sermos uma empresa que tem produtos financeiros, somos extremamente cuidadosos com tudo que colocamos em produção e temos padrões altos de qualidade, mas sem deixar de perder agilidade e velocidade no desenvolvimento dos produtos

## Benefícios

- Plano de Saúde e Odontológico Bradesco (sem coparticipação)
- Vale transporte
- Vale Refeição e/ou Vale Alimentação
- Seguro de Vida
- Gympass
- Auxílio Creche
- Horário flexível

## Contratação

Regime CLT

## Etapas do nosso processo seletivo:

- Inscrição
- Phone Screening | Entrevista com o time de People
- Entrevista com a liderança
- Apresentação do desafio técnico
- Feedbacks e/ou contratação

## Como se candidatar

através do link da vaga em https://boards.greenhouse.io/pagarme/jobs/4180396003

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
