### ISSUE TITLE
[REMOTO] Fullstack Developer @ BIG BRAIN

### ISSUE THREAD

**Issue by lucasbahiaa** [frontendbr/vagas#3623]
**Descrição:**  A Big Brain Education é a principal parceira da Microsoft na América Latina focada em transformação e tecnologia educacional. Com grande objetivo em Desenvolver soluções e projetos que visam provocar, transformar e empoderar o ambiente de aprendizagem. Procuramos um perfil de Fullstack para transformar ideias em produtos, participando do design e implementando sistemas, além de propor soluções inovadoras de serviços, desde a concepção até a produção, garantindo alta performance e larga escala. Gostaria de fazer parte desse desafio?

**Local: 100% REMOTO**
**Contratação:** PJ + Assistência médica. 

Requisitos principais: C#, .Net Core, .Net Framework, MVC, React, SQL Server, Oracle, PostGres, MySQL
Desejável: Azure, Certificações Microsoft.

Fazer o cadastro no seguinte site:  **https://byintera.in/bbdfsrgh**

Dúvidas: https://www.linkedin.com/in/jessica-santana-96b5141a8/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
