### ISSUE TITLE
[Remoto] Front-End Developer no Cálculo Jurídico

### ISSUE THREAD

**Issue by giovannibonetti** [frontendbr/vagas#3624]
## Descrição da vaga

Aqui no Cálculo Jurídico nós desenvolvemos sistemas para ajudar os advogados a fazerem cálculos de aposentadoria para seus clientes. Estamos expandindo para outras áreas de direito e precisamos de você para nos ajudar a dar conta desse trabalho. A empresa é 100% remota, e nos comunicamos via Slack, Github, Google Docs e Google Meet.

Se você gosta de programação funcional ou tipagem forte com Typescript, vai adorar saber que a empresa patrocina o aprendizado de uma revolucionária tecnologia do mundo front-end: [a linguagem de programação Elm](https://elm-lang.org/). [Todo o nosso sistema em produção](https://app.calculojuridico.com.br/) utiliza essa tecnologia fantástica 🚀 . 

O processo seletivo é 100% online incluindo prova teórica e prática de desenvolvimento, seguidos de entrevista via Google Meet.

## Local

Onde você quiser, o trabalho é 100% remoto.

## Contratação
PJ _full time_ com remuneração de R$ 10 mil **depois de 6 meses de experiência**. Até lá o valor vai ser reduzido para R$ 8,5 mil em função do aprendizado da [linguagem funcional Elm](https://elm-lang.org/) que utilizamos na empresa. Esse aprendizado acontecerá durante o expediente, sem prejuízo para a vida pessoal do desenvolvedor.

## Requisitos

**Obrigatórios**
- Experiência prática com desenvolvimento de front-end web usando HTML, CSS e JS
- Tenha desenvolvido alguma aplicação interativa com alguma biblioteca/framework baseada no conceito de [Virtual Dom](https://pt-br.reactjs.org/docs/faq-internals.html), como React, Vue, Angular, Ember ou o próprio Elm
- [Conhecimentos básicos de Typescript](https://www.typescriptlang.org/docs/handbook/basic-types.html) ou alguma linguagem com tipagem estática
- Inglês avançado para compreensão escrita e oral (vídeos de cursos, eventos etc.)

**Diferenciais**
- [Conhecimentos básicos de programação funcional](https://www.freecodecamp.org/news/functional-programming-principles-in-javascript-1b8fc6c3563f/)

## Empresa

Apesar de ser uma empresa nova - há cerca de 3 anos no mercado - o Cálculo Jurídico já é uma empresa lucrativa e, portanto, não precisa de investimento externo. Aqui a gente trabalha para fazer o melhor produto pro cliente, não para entregar as funcionalidades que o investidor pede.

Somos uma equipe pequena (cerca de 20 pessoas) mas bem organizada. Você pode observar isso pela organização do processo seletivo com várias etapas, sendo tudo realizado por nós mesmos (não terceirizamos recrutamento para nenhuma empresa de RH).

Do ponto de vista tecnológico, hoje temos um sistema com o _back-end_ em Ruby on Rails hospedado no Google App Engine / Google Cloud Platform com _containers_ Docker. Estamos montando nossa API agora que vai ser usada pelas novas partes do front-end, que já foi todo desenhado no Figma e está sendo implementado agora.

#### Diferenciais da empresa

- empresa 100% remota;
- alta produtividade - você vai poder focar no trabalho sem muitas interrupções. Há raríssimas reuniões (normalmente só uma por semana), pois quase todas a comunicação ocorre de forma assíncrona via _issues_ no Github, documentos do Google Docs, desenhos da interface no Figma, emails etc.

## Como se candidatar

Inscrições abertas até sexta-feira (02/out) às 14h (BRT) [neste link](https://talentos.calculojuridico.com.br/selective_processes/desenvolvedor-a-front-end-pleno-senior-home-office-out-2020/candidates/new?referrer=github).

Assim que as inscrições se encerrarem você vai receber um email nosso explicando como iniciar o processo seletivo.

O CPF é solicitado para garantirmos uma maior autenticidade dos cadastros no processo seletivo.

## Cronograma

Ação | Prazo
-- | --
Encerramento das inscrições | 02/out (6ª feira) às 14h
Realização dos testes de lógica, inglês, desenvolvimento e prova de comunicação | 02/out (6ª feira) às 14h até 05/out (2ª feira) às 12h
Comunicação do resultado na prova teórica | 05/out (2ª feira) até às 18h
Realização da prova prática de desenvolvimento | 09/out (6ª feira) às 8h até 13/out (3ª feira) às 12h
Comunicação do resultado na prova prática e convocação dos aprovados para entrevista | 13/out (3ª feira) até às 18h
Realização das entrevistas | 14/out (4ª feira) e 15/out (5ª feira)
Comunicação aos candidatos do resultado final do processo seletivo | até 16/out (6ª feira) às 18h
Ínicio do trabalho | a partir de 19/out (2ª feira)

## Labels
- PJ
- Remoto
- Pleno
- Sênior

**Comment by eduardocappellotto** [comment]
Parabéns pela postagem, está muito bem estruturada.
Dá até vontade de aplicar, pena eu não ter senioridade necessária.. tem algum outro lugar onde eu consigo ver as oportunidades abertas pela cálculo jurídico? 
Obrigado!

**Comment by giovannibonetti** [comment]
> Parabéns pela postagem, está muito bem estruturada.

Obrigado!

>  tem algum outro lugar onde eu consigo ver as oportunidades abertas pela cálculo jurídico?

Todas as vagas [estão disponíveis aqui](https://talentos.calculojuridico.com.br/)

**Comment by GuilhermeLis** [comment]
O que vocês querem dizer com PJ full time?

**Comment by giovannibonetti** [comment]
Processo seletivo encerrado. Foi bem produtivo e gerou duas contratações. Obrigado a todos que participaram!

Na próxima vez que tivermos vagas (deve demorar pelo menos 1 ano) divulgaremos aqui de volta.
