### ISSUE TITLE
[Remore] Fullstack (Sr/Tech lead) na @bxblue

### ISSUE THREAD

**Issue by Rebeccapz** [frontendbr/vagas#3625]
## Nossa empresa

A bxblue é uma fintech com a missão de ajudar as pessoas a terem acesso ao crédito pessoal mais barato do país. Fomos investidos por grandes nomes do cenário nacional e internacional. Dentre eles a Y Combinator (Aceleradora responsável por empresas como AirBnB, Dropbox, Heroku, Docker e Twitch). Também tivemos a honra de sermos selecionados pelo Banco do Brasil para co-criarmos juntos a primeira API de Empréstimo do Brasil. Também saímos na lista das 100 Startups para ficar de olho em 2019.

## O Time

Nosso time é super enxuto, composto por pessoas das mais diversas histórias, habilidades e experiências. Nós trabalhamos em prol de construir nosso produto e usar as melhores ferramentas à nossa disposição.
Trabalhamos junto às demais áreas da empresa para garantir que todo mundo saia ganhando: os clientes, os bancos, nosso time e é claro, a bxblue.
Estamos a procura de pessoas diferentes que possam contribuir não em número, mas com pontos de vista, vivências e competências diferentes para nosso time.

## Descrição da vaga

Essa posição não tem apenas uma fronteira, você nos ajudará em diversos desafios. Pode ser junto ao usuário, ajudando-o a resolver as dificuldades com o produto, sempre próximo aos times de negócio (marketing ou vendas) ou conjunto com as equipes dos bancos parceiros. Desenvolvendo soluções que otimizem suas atividades ou integrando com ferramentas internas e externas.
Você atuará em equipe para discutir, desenhar e construir soluções estratégicas para problemas reais. Indo da compreensão a entrega e acompanhamento do valor gerado.
Nossa stack não é nossa lei, nosso interesse é encontrar as melhores ferramentas. Aqui você terá espaço para se desenvolver e aprimorar nas tecnologias que usamos e na escolha de novas opções.

## Local

Remoto 

## Requisitos
O que você PRECISA para concorrer a essa vaga?

- Saber se comunicar em Inglês e Português
- Se sentir à vontade no desenvolvimento, manutenção e deploy de aplicações web
- Ter disponibilidade para trabalhar em período integral
- Se envolver com nosso propósito e nos ajudar com a nossa missão 

O que você **NÃO PRECISA** para concorrer a essa vaga?

- Morar perto da gente (somos remotos)
- Ser fluente na nossa Stack de Desenvolvimento (teremos espaço para você desenvolver suas habilidades conosco)

## Remuneração

A remuneração para todas as nossas vagas dependem do nível em que a pessoa se encaixar podendo ir de R$ 5.700,00 a R$ 16.800,00.

## Contratação

PJ 

## Como se candidatar

É só entrar no link e se candidatar: https://apply.workable.com/bxblue/j/4D993CE8D3/

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Remoto
#### Regime
- PJ
#### Nível
- Pleno
- Sênior
- Especialista
- Team Lead
#### Stacks 
ReactJr
Ruby on Rails
Heruko + AWS
MongoDB

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
