### ISSUE TITLE
[São Paulo] Front-end Developer [Angular] na T4W Tecnologia

### ISSUE THREAD

**Issue by GeracaoTalento** [frontendbr/vagas#3626]
Front-end Developer – Angular 

Assessoramos a Empresa T4W Tecnologia neste processo seletivo.

Atuará como Desenvolvedor .NET Frontend, no desenvolvimento de novas funcionalidades e manutenção da plataforma. 

Trabalhará em contato direto com outras equipes e áreas da empresa. 

Conhecimento obrigatório: 

- HTML, CSS3, JavaScript, TypeScript 
- SASS e LESS 
- AngularJs e Angular 2+ 
- Otimização, Responsividade e experiência do cliente nos dispositivos desktop e mobile 
- RESTful APIs 
- Design Patterns 

Conhecimento desejável:

- Linguagem C# 
- Asp.net Core 2.0 
- Team Foundation Server (TFS) 
- MySQL 
- MongoDB 
- Gulp.js 

Diferencial:

- Conhecimento em UX e Usabilidade.
- Ter trabalhado no mercado de turismo. 

- Possibilidade de Trabalho Remoto.

- Local : Vila Olímpia – SP.

- Contratação CLT + benefícios ou como PJ (enviar pretensão salarial).

Enviar e-mail para : marcelo@geracaotalento.com.br

**Comment by antoniotex** [comment]
Boa noite. Vocês estão avaliando part-time para PJ? Obrigado desde já.

**Comment by GeracaoTalento** [comment]
> 
> 
> Boa noite. Vocês estão avaliando part-time para PJ? Obrigado desde já.

Boa noite Antonio! No momento não, apenas (full time). Obrigado

**Comment by GeracaoTalento** [comment]
Vaga encerrada, agradeço pelos interessados!
