### ISSUE TITLE
[Recife/PE] Front-end Developer na MV 

### ISSUE THREAD

**Issue by anifernanda** [frontendbr/vagas#3629]
## Nossa empresa

A MV é uma empresa líder no mercado de sistemas de gestão de saúde, estamos em constante crescimento. 
O nosso sucesso se deve não só a eficiência das nossas soluções e serviços, mas também a equipe de profissionais talentosos e altamente capacitados. Convidamos você a um ambiente desafiador, inovador e com grandes oportunidades para explorar. Venha aprender e crescer, com uma equipe entusiasmada e colaborativa.
Como membro do time, você participará do desenvolvimento de projetos voltados para área da saúde, trocando experiências e compartilhando conhecimentos com profissionais de diferentes lugares.

## Descrição da vaga

Experiência em JAVA, PL/SQL, RDMS Oracle e PostgreSQL, APIs – Rest / Soap, Containers – Docker, GIT e Jira, Selenium.

## Local

Remoto 

## Requisitos

**Obrigatórios:**
- Conhecimentos em metodologias ágeis;
- Experiência com AngularJS;
- Experiência em projetar componentes;
- Experiência em projetar e conectar partes de pilhas de software - padrões de programação;
- Experiência com conceituação, desenvolvimento e manutenção de ferramentas de desenvolvimento de software, como estruturas e bibliotecas;
- Experiência em testes automatizados.

**Desejáveis:**
-  Idioma Espanhol.

## Benefícios
-Plano de Saúde;
-Plano Odontológico;
-Vale Refeição;
-Gympass
-Clube de Vantagens - Uppo;
-RedeMed;
-Convênio Apple;
-Seguro de Vida;
-Auxílio Creche;
-Auxílio Lente.

**Diferenciais:**
- 2 horas de almoço

## Contratação

CLT, valor a combinar

## Como se candidatar

Acesse o link e cadastre seu currículo
https://jobs.kenoby.com/oportunidadesmv/job/desenvolvedor-senior-front-end-home-office/5f46aad3e0a2095344224f70

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta anieli.fernanda@wtime.com.br

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
