### ISSUE TITLE
[São Paulo] Front-End Dev (Ionic)

### ISSUE THREAD

**Issue by brenocordeiro** [frontendbr/vagas#363]
Recrutamos Desenvolvedor Ionic com experiência Front-end e conhecimento em C#. 

A oportunidade é para um contrato de longo prazo em cliente importante de entretenimento em SP. 

Segue resumo da posição:

**Necessário**
•	Desenvolvimento Ionic
•	Desenvolvimento Front-end
•	Cordova
•	AngularJS
•	Web API
•	C#
•	Perfil Pessoal: Comprometido, Proativo, Inovador e Espírito de equipe

**Oportunidade**
•	Próximo ao Shopping Morumbi, SP
•	Contrato CLT ou PJ de longo prazo
•	Início Imediato
•	Não existe possibilidade de trabalho remoto.

Se interessou? Envie e-mail para breno.cordeiro@venturatec.com ou ligue e agende uma conversa confidencial (11) 94343-7501 (whatsapp)

**Comment by mtmr0x** [comment]
@brenocordeiro a vaga continua aberta?
