### ISSUE TITLE
[SãoPaulo] Node.js Developer na Influu.me

### ISSUE THREAD

**Issue by influu** [frontendbr/vagas#3630]
## Descrição da vaga
Desenvolvedor NODE JS com vasta experiência em API e Integrações

Diferencial
 - VueJs ou React

## Local
Próximo ao metro Faria Lima

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com desenvolvimento Javascript
- 2 anos de experiência com desenvolvimento NodeJS
- Apollo GraphQL Server

**Desejáveis:**
- VUE ou React
- AWS Lambda 

## Contratação
PJ a combinar

## Nossa empresa
Somos uma agência com foco no mercado de influenciadores.

## Como se candidatar

Por favor envie um email para contato@influu.me com seu CV ou Link Git- enviar no assunto: [VAGA_NodeSP] + Nome + Sobrenome

## Labels
- PJ
- Pleno
- Remoto
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by influu** [comment]
Vaga em aberto.
