### ISSUE TITLE
[São Paulo/Remoto] Front-end Developer na Air Liquide Brasil

### ISSUE THREAD

**Issue by albdigitalteamdev** [frontendbr/vagas#3632]
> Vaga Remota durante a pandemia

## Nossa empresa

A Air Liquide é uma multinacional francesa, líder mundial em produção e fornecimento gases para grandes industrias, hospitais e pessoas físicas.

## Descrição da vaga

- Criar produtos internos (web e mobile) para uso nacional e internacional, podendo impactar a vida de milhares de pessoas
- Contribuir ativamente para a cultura do time com tendências de mercado e novas metodologias
- Participará na concepção e solução de problemas técnicos em projetos novos e o projetos legados

## Local

Av. Morumbi 8234, Santo Amaro – São Paulo 
(Home Office enquanto pandemia. Modelo híbrido após pandemia)

## Requisitos

**Obrigatórios:**
- Experiência com 5+ anos de desenvolvimento front-end
- Experiência com ECMAScript
- Conhecimento em TypeScript
- Experiência com React e React Native
- Experiência com Git e GitFlow
- Experiência com métodos ágeis (Scrum, Lean, Kanban)
- Facilidade no consumo de CLIs
- Cultura de Clean Code
- Gostar de sair da zona de conforto

**Desejáveis:**
- Cultura de otimização de performance
- Conhecimento em outras linguagens de programação
- Disponibilidade para deslocamento e viagens para realização de entrevistas com usuários, testes e pesquisas de campo

**Diferenciais:**
- Inglês
- Conhecimento com UI & UX
- Experiência com DevOps (CI, CD, Monitoramento, etc)
- Cultura de qualidade e testes (unidade, integração, aceitação, e2e, etc)
- Experiência com desenvolvimento mobile nativo (Java, Kotlin, Swift)

## Benefícios

- Bônus anual
- VR de R$ 30/dia

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para marilia.neves-sc@airliquide.com com seu CV anexado - enviar no assunto: Vaga Front-End

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: marilia.neves-sc@airliquide.com

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by Morpheuseam** [comment]
🚀🎉

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
