### ISSUE TITLE
[REMOTO] Frontend Developer VueJS Estag/Jr na Wiretrack

### ISSUE THREAD

**Issue by lowercase00** [frontendbr/vagas#3637]
## Nossa empresa

Somos uma startup focada em integrações de aplicações web, vaga para quem quer desafio e fazer acontecer!
Estamos buscamos um estagiário / analista jr. que irá atuar em vários projetos em paralelo: envolve não só a manutenção de uma base de código existente como o desenvolvimento do frontend do zero.

## Descrição da vaga

Buscamos alguém que conheça bem Javascript e entenda a lógica de interação com o backend. Adaptabilidade e autonomia na resolução de problemas sao fundamentais.  Essa não é uma vaga de uma grande empresa, com time estabelecido e equipes de suporte. Cargo part-time (6hrs), remoto. Não temos controle de horário, nem de quantidade de horas, entregas e resultado é o que importa, 100% de flexibilidade. Não há necessidade de estar na faculdade (por isso a possibilidade de DevJr também), mas a posição é a mesma.

## Local

100% Remoto

## Requisitos

**Obrigatórios:**
- Experiência com Javascript: VueJS ou React
- Roteamento (Vue Router)
- Gerenciamento de Estado (Vuex)
- Lifecycle-Hooks 
- Bibliotecas de UI
- Noções de UX/UI

**Diferenciais:**
- Vontade de aprender
- Vontade de trabalhar com desenvolvimento de produto
- Autonomia na resolução de problema
- Proatividade para encontrar soluçoes
- Flexibilidade
- Organização
- Inglês

## Contratação

PJ a combinar

## Como se candidatar

Por favor entrar no portal:
[Wiretrack | Vaga Frontend](https://wiretrack.freshteam.com/jobs/QRZh8J_OMVo1/frontend-vuejs-estagiario-analista-jr-remoto)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: frontend_vuejs_estagiario_anali_id_QRZh8J_OMVo1@wiretrack.freshteam.com

#### Alocação
- Remoto

#### Regime
- Estágio
- PJ (se não estiver na faculdade)

#### Nível
- Júnior

**Comment by leandrocodes** [comment]
Vaga de estágio pedindo experiência em Vue.js?

**Comment by eduardocappellotto** [comment]
Não entendi, a posição é pra estagiário ou pra analista? 
Contratam pra analista dev jr? 
Ou o cargo é o mesmo e só com um nome diferente?

**Comment by lucasmoore2k** [comment]
Como assim vaga de estágio em regime de contratação PJ?

**Comment by lowercase00** [comment]
@leandrocodes sim! é bem legal quando um estagiário já interagiu com a tecnologia e já tem algum nível de familiaridade. além disso é bastante comum: profissionais que estão na faculdade e que já escolheram o framework para experimentos. seria diferente se tivesse pedindo alguma experiência em qualquer outra coisa?

**Comment by lowercase00** [comment]
@eduardocappellotto pessoas que não estão na faculdade também podem se interessar, por isso a vaga tá mais ampla (estágio necessariamente remete à faculdade), aceitando o cargo com "nome" analista. também há flexibilidade e o importante é o perfil. valeu!

**Comment by margotpaon** [comment]
Bom dia CV enviado

Em qui, 1 de out de 2020 22:46, lowercase00 <notifications@github.com>
escreveu:

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by adrianocruzweb** [comment]
Já encerraram as candidaturas?
