### ISSUE TITLE
[REMOTO] Front-end Developer na Telavita

### ISSUE THREAD

**Issue by mstrcnvs** [frontendbr/vagas#3638]
## Nossa empresa

A [Telavita](www.telavita.com.br) é uma clinica de consultas de saúde online. Utilizamos uma solução própria para gestão de atendimentos e consultas, digitalizando toda a jornada médica do paciente e do profissional.

## Descrição da vaga

Nosso time na Telavita está crescendo e por isso estamos em busca de desenvolvedores para nos ajudar a democratizar o acesso a terapia no Brasil. Prezamos por um ambiente ágil que mantem o equilíbrio entre alta performance e qualidade de vida. Procuramos pessoas criativas e engajadas, apaixonadas por desafios e soluções fora da caixa que desejam trabalhar em projetos desafiadores e de impacto social.

Nesta posição você trabalhará com o time no desenvolvimento da nossa principal solução tendo como atividades:
- Desenvolvimento e manutenção de aplicações em React
- Integração com API's
- Redux
- Documentação com storybook
- Pair programming com outros desenvolvedores
- Escrita de testes de aceitação e unidade
- Sugerir soluções criativas que otimizem o trabalho
- Estimar junto com o time a complexidade das tarefas

## Local

Remoto

## Requisitos

**Obrigatórios:**
- React
- Redux
- CSS/SASS
- REST
- GIT

**Desejáveis:**
- TDD
- Clean code
- Storybook
- Docker

**Diferenciais:**
- Component Driven Design
- CI/CD
- Websockets
- WebRTC
- NodeJS
- NextJS
- React Native

## Benefícios

- VT
- VR

## Contratação

PJ a partir de 7k mensal

## Como se candidatar

Por favor envie um email para pessoas@telavita.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Sênior

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.
E-mail para contato em caso de não haver resposta: pessoas@telavita.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
