### ISSUE TITLE
[Marília/SP] Front-end Developer na Eficaz Tecnologia e Marketing

### ISSUE THREAD

**Issue by AkemiJaqueline** [frontendbr/vagas#3639]
[Marília/SP] Front-end Developer na Eficaz Tecnologia e Marketing

> Vaga Remota durante a pandemia

## Nossa empresa

Faça parte do time de Desenvolvedores de uma das maiores agências de Marketing e Tecnologia da região - Eficaz Tecnologia

## Descrição da vaga

Conhecimentos essencial:
- HTML, CSS, Javascript
- PHP

## Local

Escritório, [SÃO PAULO], [MARÍLIA], [UNIVEM]

## Requisitos

**Diferenciais:**
- Conhecimento em plataforma de e-commerce: Tray, VTex
- Conhecimento em Wordpress + Woocommerce
- Conhecimento em React ou VueJS

## Benefícios

. Ambiente de trabalho leve, descontraído e colaborativo
. Horário flexível
. Equipe jovem e muito unida
. Cozinha própria para almoço
. Café à vontade ☕
. Sexta da pipoca
. Day Off de aniversário
. Mesa de pebolim
. Vale-refeição (CLT)
. Convênio UNIMED (CLT)
. Parceria com Universidades

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para vagas@eficazconsultoria.net.br com seu CV anexado - enviar no assunto: Front Marília

## Tempo médio de feedbacks

Costumamos enviar feedbacks para os entrevistados em até 20 dias após cada processo.
E-mail para contato em caso de não haver resposta: vagas@eficazconsultoria.net.br

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível

- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
