### ISSUE TITLE
[São Paulo] Front End Mobile Developer (AngularJS+Cordova) na SisAlu

### ISSUE THREAD

**Issue by marcospereda** [frontendbr/vagas#364]
Estamos procurando programador Front End Pleno para desenvolvimento em cordova e AngularJS
 
Nosso principal App é uma agenda de comunicação entre escola e pais, feito com backend php + mysql

## Local

Em São Paulo, Rua Caramuru, 417 cj 77 - Próximo ao metrô praça da árvore.
Horário : das 8:30 as 17:30 de segunda à sexta.

## Benefícios

VT+VR+Plano de saude+Plano dental+PLR+Seguro de Vida

## Requisitos
Experiência em AngularJS ou VueJS, Bootstrap , CSS, AJAX / JSON , JQuery/Javascript.
Experiência com cordova / SlimFramework (WebService)
Residir  a 1 hora do nosso escritório

**Desejáveis:**
Desejável conhecimentos em PHP com MYSQL 

**Diferenciais:**
Se tiver experiência na área educacional será um diferencial, por favor informar no corpo do email.

## Contratação

CLT apenas, não aceitamos freelancer nem PJ
Inicio imediato

## Nossa empresa

Desenvolvemos sistemas de gestão escolar, veja mais em www.sisalu.com.br

## Como se candidatar

Por favor envie um email para marcos.pereda at sisalu com br com seu CV anexado e sua pretensão salarial 
enviar no assunto: Vaga SisAlu Front End

**Comment by mtmr0x** [comment]
@marcospereda a vaga continua aberta?

**Comment by marcospereda** [comment]
sim, continua aberta


Em 10/07/2017 12:45, Matheus Marsiglio escreveu:

**Comment by acacioosorio** [comment]
Já preencheram a vaga?

**Comment by marcospereda** [comment]
já


Em 15/08/2017 08:53, acacioosorio escreveu:
