### ISSUE TITLE
[Florianópolis] Front-end Developer na Audaces

### ISSUE THREAD

**Issue by MarinaGaikoski** [frontendbr/vagas#3640]
Vaga Remota durante a pandemia

## Nossa empresa

A Audaces é referência mundial em inovação tecnológica para a moda. Há mais de 25 anos desenvolvemos soluções fáceis de aprender, usar e manter, que aceleram a criação, o desenvolvimento e a produção de moda. Nossos produtos também atendem às necessidades de outras indústrias, como estofados, calçados, móveis e de outros materiais flexíveis.

## Descrição da vaga

Estamos em busca de uma pessoa proativa, atualizada em novas tendências, bibliotecas e frameworks, com capacidade de auto-crítica e que tenha como valor o respeito a todas as pessoas para atuar como Frontend em uma equipe que desenvolve uma solução web inovadora e disruptiva, utilizando Angular 2+ e C#.

## Local

[João Paulo - Florianópolis](https://www.google.com/maps/place/Audaces/@-27.5688829,-48.5121479,15z/data=!4m2!3m1!1s0x0:0x6a02e05dd9aa5564?sa=X&ved=2ahUKEwiQ9cPagZTsAhWxBtQKHRaLBfIQ_BIwHXoECBUQBQ)

## Requisitos

**Obrigatórios:**

- Conhecimento sólido em HTML, CSS e Typescript;
- Familiaridade com conceitos de Design e UX;
- Experiência com frameworks web, como Angular, React e Vue;
- Experiência com sistemas de versionamento (Git);
- Inglês intermediário.

**Desejáveis:**
- Familiaridade com conceitos de clean code;
- Experiência com Angular 2+;

**Diferenciais:**
- Contribuições em projetos open source;
- Formação na área (Sistemas da informação, Ciências da computação ou afins)

## Benefícios

- Plano de saúde
- Seguro de vida
- VR ou VA
- Convênio farmácia e odontológico
- Vale transporte

**Diferenciais:**

- Horário flexível
- Programa de Desenvolvimento de Líder
- Sala de jogos

## Contratação

CLT

## Como se candidatar

Candidate-se [aqui](https://audaces.enlizt.me/vagas/frontend_developer-140820)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: recrutamento@audaces.com

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
