### ISSUE TITLE
[Porto Alegre ou Remoto] Frontend Developer (AngularJS) @DeepX

### ISSUE THREAD

**Issue by brunatonetto** [frontendbr/vagas#3642]
### **Feel like changing the world today?**

O que acha de trabalhar num lugar onde você possa tirar suas ideias do papel, onde o teu e nosso maior desafio seja o contato constante com as mais novas tecnologias e ainda se desenvolver numa cultura de conhecimento e aprendizado compartilhado? :) 

Procuramos por desenvolvedores que gostem de estar em constante aprendizado, um lugar onde "pior que errar é não tentar" e que consigam se manter com energia frente aos desafios, buscando formas de superar eles em equipe. Aqui o autogerenciamento e a colaboração são valores muito importantes pra nós :)

### **Descrição da Vaga:**

Estamos com vagas abertas aqui na Deepx! :D como AngularJS developer, você vai ajudar a criar e desenvolver soluções para nossos clientes internacionais, na área da consultoria. Como frontend developer, você também vai poder atuar com React, construindo componentes e implementar como Flux ou Redux. Ao se juntar ao time, você irá:

- Desenvolver novas funcionalidades usando AngularJS e / ou React
- Criar componentes reutilizáveis ​​e bibliotecas front-end para uso futuro;
- Traduzir designs e wireframes em código de alta qualidade;
- Criar componentes responsivos para desempenho máximo.

### **Local:** 
Remoto ou Escritório, Porto Alegre - Moinhos de Vento

### **Procuramos por developers que tenham:**

- Experiência em desenvolvimento frontend;
- Conhecimento em AngularJS, ou Elm, React, Vue.js, Purescript, ou também outras linguagens/framework;
- Ter paixão por melhores práticas de programação e aprendizado constante.

### **Contratação:**
CLT ou PJ a combinar.

### **Como se candidatar:**
É só usar esse [link](https://jobs.lever.co/deepx/815854a9-07aa-4f70-a7b5-6e48c40341e5) :D

### **Tempo médio de feedbacks:**
Costumamos enviar feedbacks em até 7 dias após cada processo.
Caso você não receba uma resposta, mande um email para: careers@deepx.it

### **Nível:**
Pleno
Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
