### ISSUE TITLE
[Remoto] Full Stack Node e React PL/SR na Trinca

### ISSUE THREAD

**Issue by Gabrielarochay** [frontendbr/vagas#3643]
// Detalhes da vaga
Buscamos Full Stack Developer PL/SR com sólida experiência em projetos digitais (web e mobile). Procuramos alguém que seja versátil na utilização de tecnologias, detalhista, exigente com qualidade, autodidata e que valorize acima de tudo o trabalho em equipe.

// Habilidades que você precisa ter:• Conhecimento sólido em Javascript e ReactJS;
• Experiência com desenvolvimento backend em Node.js;
• Conhecimentos em arquitetura e engenharia de software;
• Desejável experiência com arquitetura de microserviços.

// Contratação
• PJ

// Como é trabalhar na Trinca: https://trin.ca/procuramos-por-voce/

Por favor envie um e-mail para jobs@trin.ca com seu CV anexado - enviar no assunto: Vaga FullStack

**Comment by GesielBuffer** [comment]
necessário ajustar o e-mial de envio do cv.

Em sex., 2 de out. de 2020 às 15:17, Gabriela Rocha <
notifications@github.com> escreveu:

**Comment by GesielBuffer** [comment]
desconsiderar
9o

Em sex., 2 de out. de 2020 às 15:24, Gesiel Fernandes <
gesielbuffer@gmail.com> escreveu:

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
