### ISSUE TITLE
[Porto Alegre] Desenvolvedor Node.js na BRS

### ISSUE THREAD

**Issue by marcelorichter** [frontendbr/vagas#3644]
## QUEM SOMOS:

Somos uma design-house de produtos eletrônicos, trabalhando nos bastidores para criar produtos de alta tecnologia. 
Nos envolvemos com diversas tecnologias na área de automação predial e industrial.
Estamos em fase de internacionalização e competindo com grandes marcas dos setores que atuamos.
	
Buscamos pessoas apaixonadas por tecnologia que gostem de um ambiente desafiador, com muita liberdade para trabalhar e propor soluções.

## PARA FAZER O QUE:

Desenvolvimento de aplicações em NODE.JS (front e backend) para a área de automação industrial e predial. Análise e teste de soluções, correções de defeitos, suporte aos clientes e todas as tarefas relacionadas ao desenvolvimento de software.

## O QUE PRECISA TER/CONHECER:

* Conhecimentos avançados em JavaScript
* Conhecimentos avançados em NodeJS
* Conhecimentos de React

## SERÁ UM DIFERENCIAL:

* Experiência com linguagem C++.
* Experiência com Material-UI
* Conhecimento da Node add-on API
	
## O QUE ESPERAMOS DE VOCÊ:

* Trabalho com autonomia
* Não tenha medo de grandes desafios
* Engajamento com o crescimento da empresa

## CONTRATAÇÃO:
CLT ou PJ, à combinar.
Necessário residir na grande Porto Alegre

## GOSTOU?
Envie seu currículo para marcelo@brs.ind.br

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
