### ISSUE TITLE
[Londrina/PR] Mobile Android Developer na Revelo

### ISSUE THREAD

**Issue by drtorchio** [frontendbr/vagas#3645]
## Nossa empresa

Empresa de Consultoria Estratégica.
Construindo a maior plataforma de logística do país!
Aqui temos mindset aberto e muita troca.

## Descrição da vaga

Desenvolver e manter sistemas de logística, fretes e serviços financeiros para caminhoneiros e operações de frete de cargas em nosso pool de serviços ou parceiros.
Participar junto com nossos grupos em discussão em arquitetura, stacks de tecnologia, agilidade, dados e negócios e promover o aprendizado e desenvolvimento do time, sempre trazendo formas de inovar e buscar resultados que nos diferenciem no mercado.
Suportar todo o ciclo de desenvolvimento de produtos e auxiliar em experimentos e novas formas de entregar valor para nossos clientes finais.
Pesquisar e implementar tecnologias disruptivas que criem valor e diferenciação para o time de tecnologia da empresa.

## Local

Londrina - PR (Serão considerados candidatos dessa região, ou do Estado do Paraná com interesse em mudança de cidade)

## Requisitos

**Obrigatórios:**
- Desenvolvimento Android Nativo (Java/ Kotlin)
- Conhecimento em SQL
- .NET e/ou Node.JS

## Benefícios

- Vale-Refeição
- Vale-Alimentação
- Plano de saúde
- Seguro de vida
- Auxílio educação

## Contratação

CLT

## Como se candidatar

Por favor envie um email para drtorchio@gmail.com com seu CV anexado - enviar no assunto: Vaga Mobile Android Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após o envio do currículo.
E-mail para contato em caso de não haver resposta: drtorchio@gmail.com

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by drtorchio** [comment]
@felipefialho poderia por favor retirar o label de remoto?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
