### ISSUE TITLE
São Paulo - Front-end Developer  - TechFor TI

### ISSUE THREAD

**Issue by LeticiaTechFor** [frontendbr/vagas#3647]
## Nossa empresa

Empresa de Tecnologia, presente há mais de 10 anos no mercado. 

## Descrição da vaga

Exemplo: Projeto em Front end

## Local
Local: Estação Hebraica – Rebouças – O profissional irá permanecer homeoffice até a finalização da pandemia.

## Requisitos

Buscamos um profissional com experiência em análise e desenvolvimento front end, utilizando, HTML - BOOTSTRAP – CSS, Javascript, Visual Studio - Interfaces para Mobile (Responsivo).
Desejável conhecimentos em TFS, ter trabalhado em equipe de desenvolvimento Ágil (SCRUM)

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um e-mail para lcavalcante@techforti.com.br com seu CV anexado - enviar no assunto: Vaga Front end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: lcavalcante@techforti.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível

- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
