### ISSUE TITLE
[Sorocaba] Front-end Developer na Kiron Sistemas

### ISSUE THREAD

**Issue by kironsolucoes** [frontendbr/vagas#3648]
## Nossa Empresa
Empresa de Tecnologia, presente há mais de 10 anos no mercado.

## Descrição da vaga
Projeto em Front end.

## Local
Remoto ou Escritório, [SP], [Sorocaba], [Jd. Vergueiro]

## Requisitos
Estamos procurando um(a) Front-end Developer

- Conhecimentos sólidos em HTML5, CSS3;
- Conhecimentos em Javascript e TypeScript;
- Experiência com comunicação via API REST;
- Experiência com Angular Material;

**Desejáveis:**
- Conhecimento de UI e boas noções de UX;
- Vivência em times com desenvolvimento ágil;

## Contratação

PJ a combinar

## Como se candidatar

Quer encarar o desafio e trabalhar com soluções que utilizam tecnologia no desenvolvendo de sistemas? Envie seu currículo/portfólio mais pretensão salarial no e-mail: vagas@kiron.net.br

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
