### ISSUE TITLE
[Santos - SP] Front-end Developer - Agencia Manga

### ISSUE THREAD

**Issue by matheusmpessoa** [frontendbr/vagas#365]
## Descrição da vaga

A agencia Manga (https://www.agenciamanga.com) busca um front end para foco em desenvolvimento de novos projetos, atuando principalmente com nossos principais clientes.
Além da codificação o front end deverá estar em constante comunicação com a equipe de Design, a fim de melhorar cada vez mais o processo de desenvolvimento de sites (desde o layout até a codificação semântica).
Atualmente a agência Manga possui clientes no Brasil, Estados Unidos e Reino Unido. 🇧🇷 🇺🇸 🇬🇧

## Local

Escritório, Santos - Canal 1 (futuramente no Canal 5).
Não aceitamos remoto.

## Requisitos

**Obrigatórios:**
- Recorte e implementação de layout (PSD) com HTML5/CSS3/JS
- Experiência em projetos de sites responsivos
- Manuseio básico de Wordpress e plugins
- Ser comunicativo

**Desejáveis:**
- conhecimentos básicos de SEO
- conhecimentos em UX
- Versionamento com GIT

## Contratação

CLT

## Como se candidatar

Por favor envie um email para matheus@agenciamanga.com com seu CV anexado - enviar no assunto: Vaga Front-end

**Comment by MatheusJusto** [comment]
Enviado :)
