### ISSUE TITLE
[Remoto] Front-end Developer na Hubvet

### ISSUE THREAD

**Issue by samuellealb** [frontendbr/vagas#3650]
## Nossa empresa

A Hubvet é uma startup focada no desenvolvimento de uma solução de integração de processos no ambiente médico-veterinário.

## Descrição da vaga

Desenvolver aplicação web em Vue.js/Laravel
Criação de componentes reutilizáveis e recursos de interface para usuários (utlilizamos o Vuetify)
Implementação de bibliotecas frontend
Trabalhar com gerente de produto e equipe de backend para implementação de recursos
Trabalhar com designer para propor soluções de usabilidade da interface e implementação de wireframes e layouts
Revisão de código, rastreamento e correção de bugs
Auxiliar na criação e manutenção de padrões de design para um código eficiente e inteligível
Participação em metodologia Ágil e Scrum para desenvolvimento de software

## Local

Remoto

## Requisitos

**Obrigatórios:**
Domínio dos frameworks/ferramentas:
- Vue (componentes, vue life-cycle, methods, hooks, state management)
- Vuetify
- SASS
- Git

**Desejáveis:**
- conhecimentos em ruby on rails
- conhecimentos em C#

**Diferenciais:**
- Conhecimento de boas práticas UX/UI e responsividade
- Conhecimento avançado em JavaScript (ES6+)

## Contratação

Freelancer, a combinar, com possibilidade de efetivação CLT

## Como se candidatar

Contato para CV’s: leonel@hubvet.cloud

#### Alocação
- Remoto

#### Regime
- CLT
- Freela

#### Nível
- Júnior
- Pleno

**Comment by elvishuges** [comment]
Enviado !!!

**Comment by joelpmonteiro** [comment]
enviado!

**Comment by samuellealb** [comment]
A vaga ainda está aberta, estamos recebendo CVs.

**Comment by evertonProgramadorCriativo** [comment]
Olá meu nome é Everton Eduardo , trabalhei 2meses como programador junior remotamente  , estou precisando muito dessa oportunidade, meu Whatsapp é 5521968840782

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by samuellealb** [comment]
A vaga ainda está aberta, estamos recebendo CVs.
