### ISSUE TITLE
[São Paulo] PL/SR Front-end Developer na @Mazzatech - 100% REMOTO mesmo após a pandemia

### ISSUE THREAD

**Issue by taianeuchoa** [frontendbr/vagas#3651]
#Nossa empresa
Profissional será contratado pela Mazzatech para prestar serviços para grande multinacional francesa que atua no varejo de materiais para construção e decoração.

## Descrição da vaga
Atuará no desenvolvimento de aplicações internas da empresa.

## Local
Exemplo: Remoto. A empresa fica em São Paulo.

## Requisitos
**Obrigatórios:**
- Domínio de Javascript;
- CSS3;
- SCSS e PostCSS;
- Reactjs com hooks;
- Redux;
- Webpack, Babel;
- Consulta em api REST/graphql
- Teste unitários;
- Conhecimento em Git;

**Desejáveis:**
- Typescript;
- Conhecimento em graphql;
- Vivência em projetos Scrum

## Contratação
A combinar.

## Como se candidatar
Por favor envie um email para taiane@mazza.tech com seu CV anexado e sua pretensão salarial - enviar no assunto: Vaga FrontEnd.

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: taiane@mazza.tech.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
