### ISSUE TITLE
[Rio de Janeiro] Front-end Developer na EuSegurado

### ISSUE THREAD

**Issue by lcescrivani** [frontendbr/vagas#3655]
Prezados,

Busco um profissional de angular para implementar o front-end de um projeto a curto prazo.

Oportunidade freelancer;
Home Office/remoto.

Necessário ter experiência comprovada em angular;

Enviar CV para lcescrivani@gmail.com

**Comment by dominguetigs** [comment]
Aonde envio CV?

**Comment by lcescrivani** [comment]
> Aonde envio CV @lcescrivani ? Pois tenho interesse em estar sabendo mais sobre esse projeto freela. Trabalho com Angular há quase 5 anos.

Envia para lcescrivani@gmail.com


Obrigado

**Comment by dominguetigs** [comment]
Enviado @lcescrivani. Obrigado!

**Comment by lcescrivani** [comment]
Encontrei o profissional.
