### ISSUE TITLE
[REMOTO] JR/PL/SR Front-end Developer na SolarView

### ISSUE THREAD

**Issue by EduD** [frontendbr/vagas#3656]
## Nossa empresa
Somos uma empresa da área de energia solar, setor que cresce mais de 100% ao ano. Buscamos front-end developers para se juntarem ao nosso time e crescer junto com a empresa.

## Descrição da vaga
O front-end atuará a frente de alguns sistemas desenvolvidos pela empresa, que são destinados a outras empresas do setor de energia fotovoltaica.

## Local
100% Remoto

## Requisitos

**Obrigatórios:**
- Sólidos conhecimentos em HTML / CSS (saber css na unha);
- Conhecimentos em Vue, React ou Angular;
- Experiência com controle de versão Git

**Desejáveis:**
- Experiência com Typescript;
- Sólidos conhecimentos em VueJS;
- Testes automatizados;

**Diferenciais:**
- Já ter trabalhado com Graphql
- Conhecimento e experiência com práticas de uma cultura DevOps;
- Experiência em times com metodologias ágeis

## Contratação

a combinar, compativel com o mercado e dependendo do seu nível (JR/PL/SR)

## Como se candidatar

Por favor envie um email para ```contato@dantasdev.com``` com seu CV anexado - enviar no assunto: Vaga Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by krivax** [comment]
o Horário de trabalho é flexível?

**Comment by EduD** [comment]
> o Horário de trabalho é flexível?

Fala tudo bem? e sim.

**Comment by krivax** [comment]
> > o Horário de trabalho é flexível?
> 
> Fala tudo bem? e sim.

Boa noite, acabei de enviar o currículo.

**Comment by WendelSantosNunes** [comment]
Bom dia, como funciona o estágio ? Quais são os requisitos ? ( Estou no segundo período da faculdade de sistema de informação e estou esperando acabar essa pandemia para me formar como técnico em manutenção e suporte de computadores)

**Comment by SaMatheus** [comment]
@EduD Ainda está disponível?
Acabei de enviar meu CV =D

**Comment by EduD** [comment]
> Bom dia, como funciona o estágio ? Quais são os requisitos ? ( Estou no segundo período da faculdade de sistema de informação e estou esperando acabar essa pandemia para me formar como técnico em manutenção e suporte de computadores)

Os requisitos são os descritos na vaga (lembrando que para cada "nível" exige um grau de conhecimento menor/maior), o estágio e como qualquer outro estágio, nada diferente.

**Comment by EduD** [comment]
> @EduD Ainda está disponível?
> Acabei de enviar meu CV =D

Aos 45min do segundo tempo heim? rsrs 
Estou fechando aqui pois já recebi muito contato e vai ser impossivel lidar com mais pessoas no momento. Caso precise vou reabrir!

Obs: tem uma galera enviando a vaga com o titulo diferente do que informei, então vai direto para caixa de spam e não vou conseguir ficar validando, eu tenho um filtro exatamente por esse título, então quem não recebou retorno foi devido a isso!

**Comment by EduD** [comment]
reaberto!

**Comment by GuilhermeSenna** [comment]
@EduD Boa noite, ainda está disponível?

**Comment by victordlmoraes** [comment]
@EduD Olá, a vaga ainda está disponível? Aguardo seu retorno!

**Comment by EduD** [comment]
Olá! no momento só para PL / SR, já contratamos bastante JR

**Comment by Walter-Jucah** [comment]
Tem estágio?
