### ISSUE TITLE
[Remoto] Fullstack Developer na GNAR

### ISSUE THREAD

**Issue by dotpegaso** [frontendbr/vagas#3658]
## About
GNAR is a remote-first company that works mainly to improve heavy industries. You can learn more about our work by listening to [Code[ish] podcast](https://www.heroku.com/podcasts/codeish/88-monitoring-productivity-through-iot) or reading about some success stories on [Heroku](https://www.heroku.com/customers/gnar).

We're looking for a mid-level or senior Fullstack Engineer to be part of our team developing features and delivering improvements on both the backend and frontend of the project by proving simple yet performant interfaces and ensuring long term stability and scalability.

## What's my mission?
As a member of such a small team at GNAR (we're just 6 people company-wide!), you'll work closely with our product team in our biggest project.

We're continuing to expand and build new features, to be implemented during the next 2 years, and we need someone with good experience to help us deliver them with quality. At the same time, we've been building this project for the past 2.5 years, and we have lots of opportunities to improve our stack.

## Who will I be working with?
You will be working closely with our engineers @dotpegaso, @osmanpontes and our Head of Product.

## What do I need?
- English skills - you feel comfortable to write and talk on calls using english.
- React experience - you have front-end development experience using ES6. You have also worked with React and Redux.
- Node.js experience - you can use ORMs like Sequelize but also knows how to write raw SQL when needed.
- Excellent engineer - you understand and advocate for testing, analytics, observability and error tolerance.
- Product mindset - you can challenge product features, propose simpler implementation, and propose excellent technical decisions to improve user experience.

## Skills
We believe everyone can learn on the job, that's why we won't require you to know everything.

**Must have:**
- NodeJS
- Postgres
- React
- Redux

**Bonus points:**
- KoaJS
- Sequelize
- Redis
- Kafka

## Why join GNAR?
Work with talented & passionate people with diverse experiences and backgrounds (Physics, Psychology, Computer Science).
Feel your impact: GNAR is a small company, everything we do matters and your impact is critical.

## What do I get?
- 👩‍💻 40h / week
- 💵  US$24 to US$30/h (based on experience)
- 🏖️  3 Weeks PTO (Paid Time Off)

## Interested? Send
- CV and/or Portfolio
- Cover letter
- 📬  Email to: yuri@gnar.io with title: Fullstack Engineer 
- Find us at gnar.io

### Feedbacks
- Usually within 3 days

#### Alocação
- Exterior
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by GuilhermeLis** [comment]
should I send my CV in english?

**Comment by dotpegaso** [comment]
> should I send my CV in english?

Yeah, you're free to choose but I'd strongly recommend that! 😉

**Comment by felri** [comment]
Do you guys accept part time? I think I'm a good fit but I can only work 20hrs/week

**Comment by dotpegaso** [comment]
> Do you guys accept part time? I think I'm a good fit but I can only work 20hrs/week

It could be a good start!
Please, send an email to Yuri with or CV or portfolio and let him know about this part time thing. 🤗
