### ISSUE TITLE
[Florianópolis] Front-end Developer na Delivery Much Brasil

### ISSUE THREAD

**Issue by vncscoelho** [frontendbr/vagas#3659]
> Vaga Remota durante a pandemia

## Nossa empresa

Nossa missão é democratizar o delivery no interior do Brasil fomentando o empreendedorismo. Conectamos usuários, restaurantes e entregadores em mais de 250 cidades por todo o país, valorizando o comércio local e estimulando a economia das cidades.

## Descrição da vaga

Como Desenvolvedor(a) Frontend você será responsável por desenvolver interfaces de acordo com as necessidades dos produtos voltados aos diferentes parceiros da Delivery Much Brasil, conforme necessidades levantadas. 

**Como será seu dia a dia:**

- Auxiliar na definição das interfaces dos produtos de gestão da franqueadora e franqueados da Delivery Much Brasil.
- Garantir que o layout estipulado para a interface seja entregue conforme o especificado;
- Realizar testes de forma a garantir que as funcionalidades desenvolvidas atendam ao que foi especificado;
- Implementar testes unitários no código;
- Realizar correções de bugs;
- Realizar manutenção e otimização no código quando necessário;
- Otimizar performance.  

## Local

A prioridade é por candidatos que queiram trabalhar presencialmente em Florianópolis.

## Requisitos

**Obrigatórios:**

- Testes de integração;
- Conhecimento em Vue.JS/Angular;
- Testes unitários;
- HTML;
- CSS;
- JavaScript.

**Diferenciais:**

- Já ter trabalhado em franqueadora/conhecer o modelo.
- Conhecimento em Cloud AWS.

## Contratação

CLT

## Como se candidatar

Seguir os passos em https://jobs.kenoby.com/deliverymuch/

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
