### ISSUE TITLE
[São Leopoldo/RS] Full Stack Developer (React/Node) na V4 Company

### ISSUE THREAD

**Issue by mjuchemf** [frontendbr/vagas#3661]
## Descrição da vaga

Nosso time de Tech está em expansão! Estamos em busca de pessoas que queriam se envolver em um dos projetos mais promissores da empresa, com o objetivo de escalar a forma como nós entregamos nossos projetos de marketing com foco no cliente e na qualidade de nosso produto final através da tecnologia. Conheça mais da vaga e da V4 Company abaixo:

Sobre o ambiente de trabalho, é importante você saber que: 

Estamos localizados no pólo empresarial Empretec, ao lado da Unisinos , em São Leopoldo/RS.
Somos guiados por atitudes claras e transparentes em nossa rotina, que nos permitem fazer o máximo para nossos clientes. Trabalhamos de modo colaborativo, o que significa que confiamos nas pessoas que estão do nosso lado.
Aqui ninguém é empregado de ninguém. O ambiente é o mais horizontal possível, possibilitando a sua autonomia para tomar as melhores decisões para as atividades pelas quais você é responsável. Não espere pelos outros aquilo que você pode fazer por si mesmo.
Processos claros com rotinas determinadas é o que buscamos, sempre criando maneiras de sermos people-proof. Só assim conseguiremos a escalabilidade que almejamos.

## Local

Escritório, São Leopoldo - Tecnosinos

#### Diferenciais

- Ambiente vibrante, cheio de pessoas com o propósito de crescer
- Foco em metas, não em horários
- Gestão meritocrática, através de Objetivos Chave de Resultados (OKRs)
- Possibilidade de sociedade através de Stock Options

## Requisitos

**Obrigatórios:**
- Conhecimento em Reactjs e React Native
- Familiaridade com marketing digital
- Habilidade de comunicação interpessoal
- Organização e metodologia
- Conhecimento de metodologias ágeis
- Conhecimento em NodeJS
- Conhecimento em banco de Dados SQL e NoSQL

**Desejáveis:**
- Inglês (reading and listening) 
- Desenvolvimento de aplicações voltadas ao Marketing
- Estatística aplicada a Marketing

## Contratação

PJ a combinar

## Nossa empresa

Na V4 somos guiados por atitudes claras e transparentes que nos permitem fazer o máximo para os nossos clientes, criando soluções que gerem resultados para todos é o nosso propósito. Trabalhamos de modo colaborativo, o que significa que confiamos nas pessoas que estão do nosso lado. Aqui ninguém é empregado de ninguém!

Todos são investidores. Clientes investem dinheiro para terem resultado, e as pessoas aqui investem seu tempo para ajudar o negócio a crescer. Juntos, seremos cada vez maiores e melhores! O ambiente é o mais horizontal possível, possibilitando a sua autonomia para tomar as melhores decisões para as atividades pelas quais você é responsável!

Antes dos processos, produtos, serviços, mesas e cadeiras; uma empresa é a união de pessoas em busca de um propósito. Em função disso temos um grande foco em quem faz parte do nosso negócio. Por isso, se você estiver aqui e se destacar de maneira meritocrática no que você faz e estar alinhado com nossa cultura, será convidado a ser sócio da empresa. Afinal, existe maior reconhecimento que uma empresa pode fazer para quem se dedica e se destaca?

Acreditamos que a V4 precisa ser um meio para que a pessoa consiga atingir seus objetivos profissionais, para isto proporcionamos um ambiente aberto e alinhando com as expectativas de cada um, para que a pessoa trabalhe com gosto e motivado!

## Como se candidatar

Para se candidatar basta acessar https://v4company.gupy.io/jobs/479616?jobBoardSource=github e fazer o cadastro

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
