### ISSUE TITLE
[São Paulo ou Remoto] Front-end Developer no Apto

### ISSUE THREAD

**Issue by httpedrao** [frontendbr/vagas#3663]
## Nossa empresa

O Apto é uma startup do mercado imobiliário estabelecida na Vila Olímpia, em São Paulo. Semanalmente publicamos novos apartamentos e casas de construtoras consolidadas de todo o Brasil com informações de qualidade e uma experiência visual única para nossos clientes.

Através da tecnologia, informações exclusivas e um toque humano, o Apto está mudando a forma que os Brasileiros procuram por um novo lar.

## Descrição da vaga
Como desenvolvedor você irá executar soluções projetadas para nossa plataforma, prezando por código sólido e manutenível.

## Local
Remoto, presencial ou semi-presencial 😃

O escritório fica na Vila Olímpia, ZS de São Paulo.

## Requisitos
**Obrigatórios:**
- Experiência com React

**Desejáveis:**
- Experiência com NextJS (muito desejável)
- Conhecimento em GraphQL
- Conhecimento em NodeJS
- Experiência em SEO

**Diferenciais:**
- Experiência em processos de DevOps
- Experiência com BEM CSS ou outra metodologia semelhante

## Benefícios
- Plano de saúde
- VR 
- VT
- Horário Flexível

**Diferenciais:**
- Geladeira sempre abastecida! 🍻
- Ambiente de startup

## Como se candidatar

Enviar e-mail para pessoas@apto.vc com o assunto "Vaga Front-end". Não esqueça de linkar seu perfil no GitHub e LinkedIn :)

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by httpedrao** [comment]
Ainda temos vagas ;)

**Comment by italofelipe** [comment]
Nao consigo me candidatar no LinkedIn, poderia re-abrir a vaga por lá? Grato.

**Comment by httpedrao** [comment]
> Nao consigo me candidatar no LinkedIn, poderia re-abrir a vaga por lá? Grato.

Oi Italo. Você pode se candidatar enviando um e-mail pra pessoas@apto.vc, com o assunto "Vaga Front-end". Manda seu LinkedIn também, por favor. Valeu!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
