### ISSUE TITLE
[REMOTO] Fullstack Developer na Gaudium

### ISSUE THREAD

**Issue by rhgrow** [frontendbr/vagas#3666]
> 

## Nossa empresa

A Gaudium é uma empresa de tecnologia que desenvolve aplicativos para o mercado de mobilidade urbana (corridas entre passageiros e motoristas) e para o mercado de entregas (Delivery).

Somos uma Startup ScaleUp Endeavor, com selo GPTW e altas taxas de crescimento anual.

Atuamos em todos os estados brasileiros e somos responsáveis por milhões de corridas e entregas por mês, fornecendo o motor para os negócios de mais de 700 empresas.

## Descrição da vaga

Quais serão seus desafios?

Programar com qualidade e boas práticas nas linguagens GO, PHP, JS e HTML;
Modelagem de dados e SQL
Participar de SQUAD de produtos, com ideias para melhoria da mobilidade urbana e mercado de Delivery.

## Local

Essa é uma vaga remota, então você pode se candidatar de qualquer lugar do Brasil. :)

## Requisitos

**Obrigatórios:**
- Gostar de trabalhar em equipe com transparência e honestidade, focando nos resultados com excelência e agilidade;
- Experiência com desenvolvimento fullstack;
- Raciocínio lógico apurado e organização;
- Disponibilidade para 40 horas semanais remota (home office).

## Salário e Benefícios
- Salário em torno de 6k (pode variar para menos ou mais, dependendo da experiência)
- Desafios, muito desafios;
- Oportunidade de crescimento rápido, pois somos uma startup Scaleup;
- Treinamento GO;
- Vale refeição/alimentação diário de R$ 35,00;
- Plano de saúde e Gympass;
- Ambiente com vários desafios que farão você crescer e se desenvolver rapidamente;

## Contratação

CLT

## Como se candidatar

Para se candidatar, acesse: https://gaudium.breezy.hr/p/2a2d935af822-programador-fullstack-p2
Você pode se candidatar com 1 click, utilizando seu linkedin. :)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: selecao.rhgrow@gmail.com

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
