### ISSUE TITLE
[Rio de Janeiro] Estágio Front-End Developer

### ISSUE THREAD

**Issue by amandavr** [frontendbr/vagas#367]
## Descrição da vaga

Estamos buscando pessoas: motivadas, participativas, que querem aprender muito e com disponibilidade imediata!

É sempre bom que tenha:
- Boa comunicação verbal e escrita;
- Responsabilidade;

## Local

Glória - Rio de Janeiro!
Não é 100% presencial, o horário é flexível e rola um home-office. São só 6h/dia! 👍 

## Benefícios

- Passagem;
- Home Office;

## Requisitos

**Obrigatórios:**
- HTML/CSS/JS

**Desejáveis:**
- SASS, LESS;
- Glunt, Grump;
- NPM;
- Bootstrap;
- Git;

**Diferenciais:**
Se já tiver alguma curiosidade com angular e node é bem legal! :)
Se souber usar Visual Studio também é bom. :)

## Contratação

Estágio

## Nossa empresa

Somos uma empresa de nômades digitais, focada em desenvolver soluções digitais incríveis para nossos clientes!
Conheça melhor nossa empresa: www.verticecomputacao.com

## Como se candidatar

Acesse nossa área de vagas https://verticecomputacao.com.br/rh-vagas e cadastre-se. :)

**Comment by viniciusdocanto** [comment]
Só estágio ou rola pleno remoto?

**Comment by amandavr** [comment]
Oi Vinícius, vc é do Rio?

Em 9 de jun de 2017 5:31 PM, "Vinicius" <notifications@github.com> escreveu:

**Comment by eronbr** [comment]
Boa Noite, gostaria de me candidatar

**Comment by amandavr** [comment]
Eron, se candidata no nosso site.

**Comment by eronbr** [comment]
Beleza, vou lá fazer isso agora, obrigado

**Comment by gabrielferreiraa** [comment]
@amandavr, apenas estágios ? :)

**Comment by amandavr** [comment]
Pessoal, nosso foco e estágio, mas se cadastra lá no site, vai que....rs

**Comment by eronbr** [comment]
Cadastrado no site já, obrigado @amandavr

**Comment by lucasbarrossantos** [comment]
Inscrito :+1:

**Comment by gkal19** [comment]
Infelizmente meu conhecimento ainda é pouco, mas boa sorte com a vaga @amandavr

**Comment by saulojmc** [comment]
aceitam estudantes acima dos 30 anos?

2017-06-09 22:05 GMT-03:00 Gabriel Kalani <notifications@github.com>:

**Comment by thallesmarchetti** [comment]
Já sou formado, mas busco vagas no perfil... Tem como me candidatar?

**Comment by amandavr** [comment]
@gkal19 que pena! brigada! :)

@saulojmc não deixe de se inscrever por isso.

@thallesmarchetti claro que sim! :)

**Comment by viniciusdocanto** [comment]
@amandavr sou do rio sim.

**Comment by brunooomelo** [comment]
rola remoto para o estagio?

**Comment by amandavr** [comment]
@brunooomelo 100% remoto não. Precisaremos de alguns dias alocado. Por isso é importante ser do Rio. ;)

**Comment by DougMoraes** [comment]
Opa! Currículo enviado!

**Comment by mtmr0x** [comment]
@amandavr a vaga continua aberta?

**Comment by thaguioliveira** [comment]
Estou tentando me candidatar, entretanto parece que há um erro no dropdown. Poderiam verificar? Por favor

**Comment by rafaelassumpcao** [comment]
@thaguioliveira deve ser  parte  do desafio. Se não for, pelo menos  vc já sabe  qual vai  ser  sua  primeira atividade no estagio

**Comment by amandavr** [comment]
Pessoal, a vaga está encerrada! Desculpem a demora em avisar. :)

**Comment by fdaciuk** [comment]
Legal @amandavr! 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
