### ISSUE TITLE
[Remoto] Front-end Developer na Bornlogic

### ISSUE THREAD

**Issue by tiagorlampert** [frontendbr/vagas#3670]
## Nossa empresa

A marca gerentes**digitais** não caminha sozinha, vem com respaldo de ser um produto criado por um dos maiores parceiros (global) Oficiais de Marketing do Facebook, do Instagram e do Google, a **bornlogic**. Desde 2013, presente fisicamente nas três principais capitais do país, a empresa se demonstrou sempre inovadora, famosa no mercado de adtech por seus algoritmos e produtos, e também reconhecida pela excelente trabalho de customer success em social media.

## Descrição da vaga

Você pode fazer parte desse projeto (remoto), receber um salário compatível, participar com voz de peso de toda tomada de decisão técnica, indicar colegas/amigos, contribuir em decisões estratégicas do produto em si, e principalmente, criar nome no currículo de ter participado desse projeto maravilhoso. As vagas, infelizmente são limitadas.

## Local
100% Remoto;

#### Obrigatórios:
- Conhecimento avançado de Javascript;
- Experiencia (mais de 1 ano) com React, VueJS ou uma versão avançada do Angular;
- Consumo de API's RESTful;
- Conhecimentos em controle de versão (Git);

#### Pontos a mais se você possui:
- Conhecimento de controle de Estado, Vuex ou Redux;
- Prática com automação de testes (Selenium, Jasmine, Jest);
- Vivência de trabalhar em conjunto com a equipe de UX na criação e planejamento de novas features e design system;
- Experiência com componentização de interfaces (de preferência para múltiplas aplicações);
- Participação ativa na comunidade javascript;

## O que esperamos no dia-a-dia
- Contribuir na construção da solução de governança de nossos clientes, utilizando react em sua ultima versão;
- Participar ativamente de um time multidisciplinar (squad/tribo);
- Planejar seu próprio escopo de trabalho, além de comunicar e negociar com o time;
- Compartilhar conhecimentos com os colegas, e participar de PR's (jogar pelo time, acima de tudo);

## Como se candidatar
Você pode se candidatar a vaga clicando [aqui](https://jobs.lever.co/bornlogic/6a61c062-c189-48b6-a845-36b38f6671fd).

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
