### ISSUE TITLE
[Joinville] Mobile Developer (React Native/Flutter) na NG Informática

### ISSUE THREAD

**Issue by jacksjm** [frontendbr/vagas#3671]
> Vaga Remota durante a pandemia

## Nossa empresa
A NG Informática é responsável pelos módulos de Manutenção de Ativos (SIGAMNT), Medicina e Segurança no Trabalho (SIGAMDT) e Gestão Ambiental (SIGASGA) do ERP Protheus (TOTVS). Iniciamos recentemente uma nova fase em um sistema SAAS, fazendo o lançamento do Keepfy e amamos isso, iniciamos novos projetos e agora precisamos de você para compor nossa equipe!

## Descrição da vaga
Buscamos um Mobile Developer para se juntar ao nosso time. Você irá participar do planejamento, desenvolvimento e implementação de novas funcionalidades em nossa plataforma. Temos um grande caminho pela frente e você terá bastante liberdade para trabalhar com React, React Native, Flutter e Typescript no desenvolvimento de aplicações em um ambiente que valoriza as boas práticas de programação (ex. testes automatizados, unitários, code review, etc) e metodologias de desenvolvimento ágil.

## Local
Av. Santos Dumont, nº 935, 3º Andar - Santo Antônio - Joinville/SC

## Requisitos

**Obrigatórios**:

- 1+ anos de experiência de mercado;
- Ter autonomia e pró-atividade;
- Conhecimento de React, React Native e Flutter;
- Conhecimentos em HTML, CSS e Javascript;
- Experiência anterior com API's RESTful com resposta em JSON;
- Experiência com Git para versionamento de código;
- Inglês técnico (stackoverflow);
- Morar em Joinville ou ter disponibilidade para se mudar para a cidade;

**Desejáveis:**

- Familiaridade com desenvolvimento ágil;
- Ser autodidata;
- Conhecimento em GraphQL, Apollo e Artemis;
- Ter espírito empreendedor;
- Gostar de aprender e testar conceitos de UX.

**Diferenciais:**

- GitHub ativo;
- Functional programming (Ramda);
- Conhecimento de CLI, bundlers e automações de front-end;
- Banco de dados não relacional (MongoDB) e/ou relacional (PostgreSQL);

## Benefícios
- Vale alimentação ou refeição
- Vale transporte ou vale combustível
- Plano de saúde
- Plano odontológico
- Auxílio Pandemia

**Diferenciais:**

- Ambiente extremamente propício à aprendizagem;
- Liberdade para sugerir novas tecnologias e melhorar o processo de desenvolvimento da equipe;
- Home-office;
- Mesa de sinuca para jogar nos intervalos e almoço (estamos em home-office, saudades sinuca :cry:);
- Horário flexível;
- Almoço de 1 a 2 horas;
- Café + bolachas/biscoitos + frutas todos os dias (Saudades frutas too :cry:);
- Microondas para esquentar seu almoço e lanches.

## Contratação
CLT a combinar

## O que usamos:

- GIT + Scrum + Kanbam + Azure DevOps
- React + React Native + Flutter + Typescript
- Github (open source)
- Slack

## Como se candidatar
Por favor, envie um email para curriculo@ngi.com.br com seu CV anexado e link do Github com o assunto: Vaga Mobile Developer (React Native/Flutter) - Github/FrontendBR

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: <curriculo@ngi.com.br>

#### Alocação
- Presencial/Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

#### Tecnologias
- React
- React Native
- Flutter
- Typescript

**Comment by ylanbenoliel** [comment]
Currículo enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
