### ISSUE TITLE
[Joinville] Mobile Developer (Java/Kotlin) na NG Informática

### ISSUE THREAD

**Issue by jacksjm** [frontendbr/vagas#3672]
> Vaga Remota durante a pandemia

## Nossa empresa
A NG Informática é responsável pelos módulos de Manutenção de Ativos (SIGAMNT), Medicina e Segurança no Trabalho (SIGAMDT) e Gestão Ambiental (SIGASGA) do ERP Protheus (TOTVS).
Agregamos ao ERP uma plataforma mobile e iniciamos novos projetos e agora precisamos de você para compor nossa equipe!

## Descrição da vaga
Buscamos um Android Developer para se juntar ao nosso time. Você irá participar do planejamento, desenvolvimento e implementação de novas funcionalidades em nossa plataforma. Temos um grande caminho pela frente e você terá bastante liberdade para trabalhar com Java e Kotlin no desenvolvimento de aplicações em um ambiente que valoriza as boas práticas de programação (como testes unitários e revisão de código) e metodologias de desenvolvimento ágil.

## Local
Av. Santos Dumont, nº 935, 3º Andar - Santo Antônio - Joinville/SC

## Requisitos

**Obrigatórios**:

- 1+ anos de experiência de mercado;
- Ter autonomia e pró-atividade;
- Conhecimento de Java e Kotlin - App Android;
- Conhecimentos em HTML, CSS e Javascript;
- Experiência anterior com API's RESTful com resposta em JSON;
- Experiência com Git para versionamento de código;
- Inglês técnico (stackoverflow);
- Morar em Joinville ou ter disponibilidade para se mudar para a cidade;

**Desejáveis:**

- Familiaridade com desenvolvimento ágil;
- Ser autodidata;
- Ter espírito empreendedor;
- Gostar de aprender e testar conceitos de UX.

**Diferenciais:**

- GitHub ativo;
- Functional programming (Ramda);
- Conhecimento de CLI, bundlers e automações de front-end;
- Banco de dados não relacional (MongoDB) e/ou relacional;

## Benefícios

**Diferenciais:**

- Ambiente extremamente propício à aprendizagem;
- Liberdade para sugerir novas tecnologias e melhorar o processo de desenvolvimento da equipe;
- Mesa de sinuca para jogar nos intervalos e almoço (estamos em home-office, saudades sinuca :cry:);
- Almoço de 1 a 2 horas;
- Café + bolachas/biscoitos + frutas todos os dias (Saudades frutas too :cry:);
- Microondas para esquentar seu almoço e lanches.

## Contratação
Cooperado a combinar

## O que usamos:

- GIT + Scrum + Kanbam + Azure DevOps
- Java + Kotlin
- Github (open source)
- Slack

## Como se candidatar
Por favor, envie um email para curriculo@ngi.com.br com seu CV anexado e link do Github com o assunto: Vaga Mobile Developer (Java/Kotlin) - Github/FrontendBR

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: <curriculo@ngi.com.br>

#### Alocação
- Presencial/Remoto

#### Regime
- Cooperado
- CLT

#### Nível
- Júnior
- Pleno

#### Tecnologias
- Java
- Kotlin

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
