### ISSUE TITLE
[São Paulo] Desenvolvedoras/Desenvolvedores FullStack JS Pleno na BR Mendes Consultoria

### ISSUE THREAD

**Issue by brunohenrq** [frontendbr/vagas#3673]
## Descrição da vaga

Desenvolvimento de ferramentas de chat, colaboração e CRM.

## Local

São Paulo (100% remoto)

## Requisitos

Conhecimentos em Ecma script e Node.
Conhecimentos em Angular.
Conhecimentos em Vue.
Conhecimentos em versionamento com git.
Conhecimentos em jQuery e Bootstrap.
Conhecimentos em HTML5 e CSS3.

**Diferenciais:**

Conhecimentos em PHP/Codeigniter
Experiência com ambientes de alta performance.

## Contratação

Regime CLT + Benefícios

.::Salário:

A combinar 

## Como se candidatar

Mais informações, envie seu currículo através do link:
https://lnkd.in/dBAyssU

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
