### ISSUE TITLE
[São Paulo] Front-end Developer na Otimize.Me

### ISSUE THREAD

**Issue by devallanrod** [frontendbr/vagas#3675]
## Nossa empresa

Sobre a Empresa: Somos uma empresa com foco em ecommerce e produtos. Estamos localizados em Vila Mariana, somos um time bem tranquilo e lidamos com problemas na conversa =)
Possibilidade de crescimento.

## Descrição da vaga

Estamos em busca de Devs para fazer parte do nosso time imediatamente! A todo gás em um novo projeto e queremos você na equipe. Trabalhamos em um clima informal com foco em produtividade das tarefas, que em alguns casos são recompensadas com bônus $$$.

## Local

> Vaga 80% Remota durante a pandemia
> 2 vezes por semana alocado

## Requisitos

**Obrigatórios:**

- Grande conhecimento em CSS e SASS
- Desenvolvimento com JavaScript Vanilla ES6+
- Conhecimentos sobre frameworks populares do mercado como React, Vue ou Angular
- Ter paciência de documentar o próprio código
- Boa vontade de compartilhar o que sabe

**Desejáveis:**
- Experiência com UX/UI
- Saber trabalhar com uso de boas práticas
- Conhecimento de Node.js
- Implementação de UI envolvam animação baseada em dados, SVG e Canvas

**Diferenciais:**
- Ensino superior completo em áreas relacionadas à Design e Front-end
- Conhecimento em testes unitários com Jest, Mocha, Jasmine ou similares
- Possuir projetos pessoais

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para projetos@otimize.me com seu CV anexado - enviar no assunto: Vaga Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: allanrod@otimize.me

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by mrangel-jr** [comment]
tem vaga 100% remoto ?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
