### ISSUE TITLE
[Remoto] Front-end Developer na People Interactive

### ISSUE THREAD

**Issue by fabiopinhorj** [frontendbr/vagas#3678]
## Nossa empresa

Somos uma empresa de inovação que atua em produtos, serviços e e-commerces criando experiências irresistíveis que transformam negócios e impactam a vida das pessoas.

## Descrição da vaga

Implementação de interfaces elaboradas pela equipe de design
Desenvolvimento de código reutilizável
Revisão de código, rastreamento e correção de bugs

## Local

Remoto ou Escritório, Rio de Janeiro - Barra da Tijuca

## Requisitos

**Obrigatórios:**
- Grande conhecimento em CSS e SASS
- Grande conhecimento em JavaScript
- Conhecimentos sobre React

**Desejáveis:**
- Conhecimento de Node.js

**Diferenciais:**
- Conhecimento de Vtex ou Magento
- Experiência com React Native

## Benefícios

- VR de R$21,43/dia

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para vempraca@peopleinteractive.com.br com seu CV anexado - enviar no assunto: [Front-end Pleno]
Envie um e-mail com o título [Front-end Pleno]

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: fabiopinho@peopleinteractive.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
