### ISSUE TITLE
[Remoto] Front-end Developer na Chili Piper 🌶

### ISSUE THREAD

**Issue by lucas-barros** [frontendbr/vagas#3679]
## Nossa empresa

Chili Piper helps businesses help their buyers.

People interested in your business typically have to wait hours or days after filling out a form. Not anymore. Our intelligent assistant offers them a simple way to book a meeting or start a phone call immediately upon form submission.

Unlike the traditional method of inbound lead management, Chili Piper uses smart rules to qualify and distribute leads to the right reps in real time. Our software also allows companies to automate opportunity distribution from their SDR’s to their AE’s, and book meetings from their marketing campaigns and live events.

Companies like Square, Twilio, DiscoverOrg, SalesLoft, and SiriusDecisions use Chili Piper to create an amazing experience for their leads, and in return experience higher conversions for their business.

Chili Piper is focused on helping Businesses help their Buyers - building a new category we call Buyer Enablement

## Descrição da vaga

Chili Piper is seeking talented, motivated engineers to join our fully remote team building interactive data applications. As a part of growing front-end team, you will work with designers to constantly improving our users’ experience. You will also collaborate with others throughout our organization and technology stack to build products that are revolutionizing the way our clients achieve their business goals.

On the front-end team, we feel strongly about developing solutions that are both technically and aesthetically sound. We invite you to bring your experience and perspective to conversations about the future growth of our applications and environment. We work closely together, with a healthy and non-combative review process aimed at improving code as well as developing each other’s skills. In short, we strive to write solid, thoroughly tested, and readable code; and we are seeking a new contributor to our already highly effective team.

## Local

Remoto

## Requisitos

- Strong English communication and documentation skills
- Strong proficiency in JavaScript, including DOM manipulation and the JavaScript object model
- Thorough understanding of React.js and its core principles (2+ years of work experience with React)
- Experience with popular React.js workflows (such as Flux or Redux)
- Familiarity with newer specifications of EcmaScript
- Experience with data structure libraries (e.g., Immutable.js)
- Familiarity with RESTful APIs
- Knowledge of modern authorization mechanisms, such as JSON Web Token
- Familiarity with modern front-end build pipelines and tools
- Experience with common front-end development tools such as Babel, Webpack, NPM, etc.
- Ability to understand business requirements and translate them into technical requirements
- A knack for benchmarking and optimization

## Benefícios

- Unlimited Vacation
- WeWork membership so you can work from anywhere
- Any equipment/software/tech that you need to do your job

## Contratação

PJ ou PF

## Como se candidatar

https://grnh.se/6fa556b83us

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by lucas-barros** [comment]
Ainda está aberta!
