### ISSUE TITLE
[São Paulo] Front-End Developer [Pleno/Sênior]

### ISSUE THREAD

**Issue by danilomelo** [frontendbr/vagas#368]
## Descrição da vaga

Um perfil inovador, comprometido e focado na identificação e resolução de problemas. Irá atuar como 
arquiteto de soluções em frontend, prevendo melhores práticas, performance, reutilização, testes e 
escalabilidade. 

## Requisitos
- 6 anos de experiência com desenvolvimento Web 
- Experiência com frameworks MVVM 
- Sólidos conhecimentos em JavaScript e arquitetura de serviços RESTful 
- Conhecimentos de pré-compiladores de CSS 
- Conhecimento sobre integração contínua e os conceitos do Git 
- Sólidos conhecimentos em AngularJS
- Conhecimento em Bootstrap

**Diferenciais:**
- Conhecimentos avançados sobre os serviços da AWS 
- Conhecimentos avançados em Java 
- Certificações ou experiência relevante em outras áreas de tecnologia 
- Desenvolvimento mobile nativo e/ou híbrido
- Experiência com bancos de dados relacionais/não relacionais 

## Local
Escritório, São Paulo - Brooklin

## Contratação
CLT + Cotas

## Nossa empresa

A Plusoft desenvolve soluções de atendimento e CRM, dentro do conceito de multicanalidade, proporcionando a melhor experiência ao cliente em todos os pontos de contato e, ao mesmo tempo, promovendo a redução dos custos operacionais.

http://www.plusoft.com.br

## Como se candidatar

Por favor envie um email para marcosdonato@plusoft.com.br com seu CV anexado - enviar no assunto: Vaga Front-End Developer

**Comment by mtmr0x** [comment]
@danilomelo a vaga continua aberta?

**Comment by danilomelo** [comment]
Sim @mtmr0x

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
