### ISSUE TITLE
[REMOTO] Technical Support Engineer @ Nuvemshop

### ISSUE THREAD

**Issue by lucasbahiaa** [frontendbr/vagas#3681]
**Descrição:** A NuvemShop vem revolucionando o mercado de platafomas eccomerce ao longo dos últimos anos. Neste momento está em busca de Technical Support Engineer para compor seu time, garantindo a eficiência e qualidade de sempre. Esse profissional será um Especialista em suporte técnico: além de engenheiro, terá um conhecimento holístico de toda a plataforma, ajudará também parceiros e agências a resolver situações cotidianas. 

**Local:** 100% REMOTO
**Contratação:** CLT

Requisitos principais:Experiência em desenvolvimento web, Capacidade de executar consultas SQL, API, Capacidade de navegar em base de código e encontrar e selecionar problemas.  
Desejável: PHP, Java, JavaScript.

Fazer o cadastro no seguinte site:  **https://byintera.in/nstslgh**

Dúvidas: https://www.linkedin.com/in/ana-carolina-santos-7a6612114/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
