### ISSUE TITLE
[São Paulo] Front-end Developer no Mercado Pago

### ISSUE THREAD

**Issue by freddybrasileiro** [frontendbr/vagas#3685]
> Vaga Remota durante a pandemia

Meu nome é **Freddy Brasileiro** e sou **Líder de Projetos** da equipe de **Checkout Web** aqui do **Mercado Pago**. 

Se você é **frontend sênior** e está interessado em fazer parte da equipe de Checkout Web do Mercado Pago, vem comigo!

Nosso objetivo em Checkout é criar soluções simples, escaláveis, tolerantes a falhas e mensuráveis para suportar milhares de requests por minuto. Aspiramos ter um uptime de 99.9% e hoje estamos muito perto de alcançar.

Nosso Checkout Web é o que faz a junção entre o ecossistema do Mercado Pago e os usuários que querem comprar e vender utilizando Mercado Envios, Mercado Pontos e Mercado Créditos.

No momento, estamos trabalhando 100% remoto devido ao contexto do COVID-19. Mesmo assim, continuamos tendo apoio para enfrentar da melhor maneira nossos desafios pessoais e profissionais.

Procuramos um desenvolvedor com experiência sólida, autonomia, forte conhecimento técnico e com grande capacidade analítica para enfrentar os desafios técnicos que envolvem trabalhar em um projeto para milhões de usuários.

Tá esperando o que?
Entra em contato comigo via LinkedIn e a gente bate um papo https://www.linkedin.com/in/freddybrasileiro/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
