### ISSUE TITLE
[Remoto - SP] Front-end Developer na Grupo Easytech

### ISSUE THREAD

**Issue by Recrutamentogrupoeasy** [frontendbr/vagas#3686]
> Vaga Remota durante a pandemia

## Grupo Easytech
Empresa que presta Consultoria em RH e Serviços de TI em todo o Brasil.

## Descrição da vaga

Atuará criando a interface Web para a nova loja de serviços e fará a integração através de biblioteca de consumo de serviços para integrar o Front End ao Back End.

## Local

Remoto.

## Requisitos

**Obrigatórios:**

•	Frameworks de lojas virtual (Magento, Wordress, WooCommerce, entre outras);
•	HTML avançado;
•	Javascript (JQuery, Bootstrap);
•	CSS (Inline, flexbox);
•	Estilização de componentes;
•	Node;
•	Git;
•	APi via Node;
•	React
•	PHP

**Desejáveis:**
Ensino Superior em cursos voltados a TI.

## Contratação

PJ a combinar

## Como se candidatar

Nos envie seu currículo atualizado para o recrutamento@grupoeasytech.com.br
Coloque no assunto o nome da vaga e A/C Larissa

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
