### ISSUE TITLE
[São Paulo] Front-end Developer na CBYK

### ISSUE THREAD

**Issue by Sol2612** [frontendbr/vagas#3688]
Olá,

Se você é Front end Developer temos uma vaga para você!

Requisitos Obrigatórios:

- Experiência e conhecimentos avançados de JavaScript e TypeScript.
- Experiência e conhecimentos avançados de frameworks e bibliotecas FrontEnd como Angular, React, Vue ou similares.
- Experiência em Single Page Applications, preferêncialmente utilizando Angular e Ionic (PWA).
- Entendimento em arquiteturas Front-end:  MicroFrontends, Server Side Rendenring, FrontEnd Modular ou Arquitetura de Componentes.
- Conhecimentos sólidos e avançados em HTML, CSS e pré-processadores como SASS ou SCSS.
- Conhecimento sólido em paradigmas de computação: POO(Programação orientada a objetos), paradigma funcional e programação orientada a componentes.
- Conhecimento sobre métricas e ferramentas de análise de código.
- Conhecimento em versionamento de código (GIT)

**Desejáveis:**

- Entendimento sobre a filosofia DevOps e criação de pipelines de automatização.
- Ter conhecimento com NgRx
- Ter conhecimento com padrões Observable e operadores. ( rxjs )

> Vaga Remota durante a pandemia, após dois dias por semana em home office

## Nossa empresa

A CBYK foi criada para ser uma consultoria diferenciada, realmente entregando aos clientes uma tecnologia consultiva que agrega valor ao negócio. Nosso ideal é justamente o desafio que impede nosso cliente de atingir sua meta tecnológica com soluções relevantes, se tornar exemplo para o cenário atual de inovações, soluções e performance.

## Benefícios

- 15 dias de férias remuneradas
- Gympass
- Parceria com escolas de idiomas e universidades

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para: solange.costa@cbyk.com.br com seu CV anexado - enviar no assunto: FRONT END

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
