### ISSUE TITLE
[RECIFE] Front-end Developer na PITANG

### ISSUE THREAD

**Issue by Luanadsl** [frontendbr/vagas#3689]
## Nossa empresa

Estamos há 16 anos no mercado desenvolvendo projetos de transformação digital. Nosso foco é desenvolvimento de software sobre demanda.
Spinoff da área de projetos do CESAR, hoje temos em média 400 colaboradores em diversas regiões do pais para atender clientes de médio e grande porte nos setores privados e públicos. Somos uma empresa certificada pelo Great Place To Work.

## Descrição da vaga

Projeto em nosso cliente, utilizando :
- Angular 2 ou maior;
- html5;
- css;
- javascript;
 - OAuth 2;
- Ferramenta de versionamento (GIT).

## Local

RECIFE

## Requisitos

**Obrigatórios:**
- Desenvolvimento Front And

## Benefícios

- Plano de saúde
- plano Odontológico
- VR 
- Auxílio creche

## Contratação

CLT

## Como se candidatar

Por favor envie seu currículo para oportunidades@pitang.com

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
