### ISSUE TITLE
[São Paulo] Developer na Inex

### ISSUE THREAD

**Issue by marciosnovaes** [frontendbr/vagas#369]
## Descrição da vaga

DESENVOLVEDOR NODEJS E ANGULAR SR

## Local

Escritório, São Paulo - Vila Olímpia
Horário comercial

## Benefícios

À COMBINAR

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Node
- SÓLIDA EXPERIÊNCIA EM ANGULAR

**Diferenciais:**
- projetos opensource

## Contratação

À combinar

## Nossa empresa

INEX CONSULTING
Somos uma empresa de Consultoria em Tecnologia e Serviços, com perfil de Integradora, especializada em atender a área de TI nos diversos segmentos de mercado como: Financeiro, Indústria, Seguros, Telecomunicações e Governo

## Como se candidatar

Por favor envie um email para marcio.novaes@inexsoft.com.br com seu CV anexado - enviar no assunto: Vaga NodeJS

**Comment by mtmr0x** [comment]
@marciosnovaes a vaga continua aberta?

**Comment by marciosnovaes** [comment]
Sim pessoal aberta e com MUITA urgência!

**Comment by marciosnovaes** [comment]
@mtmr0x 
 Preciso de 3 desenvolvedores fullstack urgente!
Pode me ajudar?

**Comment by kivervinicius** [comment]
Somente alocado mesmo?

**Comment by thainanfrota** [comment]
Permite remoto ou só alocado em SP?

**Comment by marciosnovaes** [comment]
Alocado no cliente em SP, cliente grande uma grande oportunidade!

**Comment by OTTOSG** [comment]
Se precisar de Estagiario/Junior. Tenho grande interesse.

**Comment by marciosnovaes** [comment]
@OTTOSG Essa vaga é pra MUITO SR.
Mas cara me manda seu CV, eu já dei no gatilho aqui.

Eu não sou de RH sou Arquiteto mas eu preciso muito montar esse time então eu mesmo estou montando.

Um abraço

**Comment by uselessdev** [comment]
@marciosnovaes precisa ser de sp? 😄

**Comment by marciosnovaes** [comment]
@uselessdev Precisa sim! Se fosse remoto seria otimo! Mas é regra do cliente!

**Comment by marciosnovaes** [comment]
@LFeh thanks!

**Comment by uselessdev** [comment]
@marciosnovaes te mandei um e-mail explicando melhor. 😄

**Comment by marciosnovaes** [comment]
Show!

**Comment by OTTOSG** [comment]
Obrigado @marciosnovaes ! Lhe encaminhei meu CV para vossa análise.

**Comment by marciosnovaes** [comment]
Pessoal preciso de mais pessoas!

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
