### ISSUE TITLE
[Remoto - PA] Front-End Developer Pleno com especialidade em Angular na Super

### ISSUE THREAD

**Issue by hersonls** [frontendbr/vagas#3690]
## Nossa empresa

Super é uma startup focada em inovações e no desenvolvimento de aplicativo marketplace onde o foco é trazer praticidade para o dia a dia de seus clientes.

## Descrição da vaga

Nós estamos procurando por desenvolvedor Front-end com experiências em Angular e Ionic, para executar seus serviços de forma remota, através de contrato PJ. Espera-se que o candidato tenha boas experiências como desenvolvedor na criação de produtos e recursos de software, prototipagem durante o ciclo de projeto e criação de recursos prontos para produção. Buscamos um candidato que possua pensamento inovador, criatividade em design e alcance dos resultados esperados.

## Local

Remoto, empresa localizada em Belem - Pará, São Luís - Maranhão e São Paulo - SP

## Requisitos

**Obrigatórios:**

- Deve ter no mínimo 4+ anos provados de experiência como desenvolvedor Front-end.
- Experiente em HTML, HTML5, JavaScript, CSS, pre-processadores CSS como Sass e LESS
- Experiente em Angular 2+ e Typescript.

**Desejáveis:**
- Experiente em criação de aplicativos híbridos utilizando o framework Ionic/Cordova.
- Utilizar ferramentas de versionamento como GIT.

**Diferenciais:**

- Colaborar em projetos opensource

## Contratação

- Contrato PJ
- Full-time
- Faixa salarial de R$ 3.000,00 a 6.000,00 de acordo com experiência.

## Como se candidatar

Por favor envie um email para tecnico@appsuper.com.br com seu CV anexado ou Linkedin - enviar no assunto: Vaga Front-end Developer Angular.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by hersonls** [comment]
A vaga ainda esta aberta
