### ISSUE TITLE
[Remoto] Fullstack Developer na Harpio

### ISSUE THREAD

**Issue by thaisvilladal** [frontendbr/vagas#3692]
## Nossa empresa

Somos uma equipe de consultores de estratégia, especialistas em recrutamento e cientistas de dados focados em pessoas, processos e conhecimento.

As Equipes da Harpio são comprometidas em realizar suas visões de recrutamento e formação de equipes. Nós acreditamos em sucesso colaborativo, fazendo sua empresa mais forte em cada engajamento conosco, construindo confiança para desafios cada vez maiores.

## Descrição da vaga

Projeto em startup startup de rede social corporativa gamificada para grandes empresas.
Há 4 anos no mercado, oferecem uma plataforma SaaS que melhora a comunicação entre grandes empresas e seus colaboradores.
É uma startup brasileira líder no segmento, reconhecida como Top 100 no ranking 100 Open Startups, e atendendo clientes como Carrefour, PepsiCo, BRF, SBT, Klabin e Via Varejo.

Responsabilidades:
Desenvolvimento de aplicações web PWAs (Progressive Web App), bem como atuar em suas melhorias, novas implementações e correções de bug.
O PWA tem seu core desenvolvido com React, styled-components e Apollo Client.
Na API que os Apps consomem dados, irá executar melhorias correções e novas features.
A API é desenvolvida com graphql-relay e alguns endpoints com express.

Desafios do projeto:
Será um grande diferencial a experiência em refazer/reescrever um produto do zero.
Diferencial experiência em liderança técnica, pois esse profissional irá atuar como um “mentor” para a equipe em atividades referente a refatoração.

## Local

Exemplo: 100% Remoto 

## Requisitos

**Obrigatórios:**
- Domínio em PWA
- Experiência com React e Node
- Conhecimentos em Express, Relay, Apollo Client, Styled-components
- PWA (service work, cache)

**Desejáveis:**
- conhecimentos em Typescript, Figma e Git

## Contratação

PJ por prazo indeterminado - remuneração a combinar

## Como se candidatar

Por favor envie um e-mail para thais.villadal@harpio.com.br com seu CV anexado - enviar no assunto: Vaga FULL PWA

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.
E-mail para contato em caso de não haver resposta: thais.villadal@harpio.com.br 

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
