### ISSUE TITLE
[Florianópolis] Mobile Front-end Developer Pleno na Agriness

### ISSUE THREAD

**Issue by MonicaDirksen** [frontendbr/vagas#3693]
> Vaga Remota durante a pandemia

## Nossa empresa

Nosso propósito é impulsionar a prosperidade no campo e fazemos isso através de soluções em tecnologia e aplicação de uma metodologia de aceleração de produtividade pioneira no mundo, auxiliando o produtor a utilizar análises e conhecimentos para obter resultados de excelência em produtividade e, assim, aumentar a rentabilidade dos negócios.

## Descrição da vaga

Estamos procurando um(a) Desenvolvedor(a) Frontend Mobile Pleno apaixonado(a) por criar produtos incríveis.
Estamos construindo a maior plataforma agro do mundo, nosso propósito é impulsionar a prosperidade no campo e para isto precisamos de pessoas que curtem grandes desafios, interessados em participar das decisões de tecnologia e ajudem na evolução dos nossos produtos mobile.

Sendo mais específico, aqui você irá:

- Interagir com os PMs e Designers para alinhamento sobre a implementação de novas soluções, funcionalidades ou melhorias no produto Presence.
- Implementar código seguindo os padrões de qualidade definidos pela área, através de uso de testes automatizados, processos de integração contínua e revisão de código.
- Fazer entregas de forma contínua, buscando manter a cadência necessária para atendimento dos acordos firmados, interagindo também com outros squads no alinhamento de entregas evitando geração de dependências.
- Apoiar a construção de soluções utilizando para isso tecnologias já adotadas pela empresa como React Native e Javascript.
- 

## Local

Remoto ou Escritório em Florianópolis/SC

## Requisitos

**Obrigatórios:**
- Ensino superior em áreas de tecnologia. 
- Experiência na tecnologia: React Native.
- Experiência nas linguagens: Javascript, CSS.
- Conhecimento na construção de soluções para Cloud.
- Conhecimento no uso de testes automatizados.
- Conhecimento no consumo de Rest API’s e WebSockets.
- Conhecimento em temas como: containers, componentização e estilização.
- Inglês intermediário.

**Desejáveis:**
- Conhecimentos nos temas como: Git Workflow, documentação de API's, design systems.

## Benefícios

- Oportunidade de trabalhar em uma empresa que te desafia, motiva, incentiva e dá liberdade para questionar e contribuir com novas ideias.

- Muita oportunidade de desenvolvimento!
- Ginástica Laboral duas vezes por semana.
- No dress code.
- Previdência Privada.
- Folga no dia do aniversário.
- Parcerias de descontos com convênios.
- Pacote de benefícios tradicionais: VR/VA, Auxílio Combustível, Plano de Saúde.

## Contratação

CLT

## Como se candidatar

Por favor envie um email para pertencer@agriness.com com seu CV anexado - enviar no assunto: Vaga Front-end

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
