### ISSUE TITLE
[REMOTO] React Web e React Native Developer - @MyBway

### ISSUE THREAD

**Issue by erickne** [frontendbr/vagas#3695]
## Nossa empresa

Criada em 2018, a MyBway nasce trazendo soluções tecnológicas para o mercado da Beleza Profissional. Nossa proposta é encantar e empoderar o Universo da Beleza, por meio da tecnologia e do conhecimento.
Pensando em soluções para os cinco pontos da cadeia da beleza: (Profissionais, Consumidores, Indústria, Distribuidores e Salões) a MyBway propõe unificar as necessidades do mercado utilizando um único canal.
Oferecemos um nova forma de relacionamento, compra e venda, educação direcionada e informações,  em que o usuário possui total controle de suas preferencias e necessidades.

## Descrição da vaga

Buscamos novos desenvolvedores de nível **PLENO** e **SÊNIOR** para compor o time tecnológico. As vagas serão para React Native e ReactJS e experiência em ambas tecnologias é fundamental!

As principais atividades serão:
- Desenvolvimento de novas interfaces web em ReactJS, com foco em análises e indicadores;
- Desenvolvimento de aplicativos híbridos em React Native;
- Desenvolvimento e execução de testes.

## Local

- 100% Remoto
- Horário comercial

## Requisitos

**Obrigatórios:**
- Domínio em ReactJS e React Native
- Domínio em React State Management
- Integração de RESTFull APIs
- Boas noções de layout 
- Ótima comunicação verbal e escrita
- Sólidos conhecimentos em criação e execução de teste em **ReactJS** e **React Native**

**Desejáveis:**
- Conhecimento em gestão de projetos ágeis
- Conhecimento na biblioteca Expo

**Diferenciais:**
- Conhecimento em CI/CD (Jenkins, Fastlane)
- Experiência em utilização do Figma
- Experiência em linguagens nativas

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para carreiras@rockapps.com.br com seu CV anexado - enviar no assunto: Vaga React Native

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
