### ISSUE TITLE
[Sorocaba e Jaguariúna] Front-end Developer no Instituto de Tecnologia Flextronics - FIT

### ISSUE THREAD

**Issue by aledaluz** [frontendbr/vagas#3696]
> Vaga Remota durante a pandemia

## FLEXTRONICS INSTITUTO DE TECNOLOGIA - FIT
Fundado em 2003, o FIT – Instituto de Tecnologia é uma organização sem fins econômicos, de abrangência nacional, credenciada pelo Ministério da Ciência, Tecnologia e Inovação.
Nossa infraestrutura foi criada para desenvolver soluções tecnológicas nos mais diversos segmentos de negócios. Soluções que antecipam as necessidades do mercado, das empresas e das pessoas.
Com equipamentos modernos e equipe qualificada, o FIT pode desenvover, prototipar e testar os produtos que farão parte da rotina das pessoas e quem sabe, mudarão vidas?
Estamos todos os dias construindo este futuro ao mesmo tempo que democratizamos o uso e até o desenvolvimento da tecnologia.
Os projetos contratados no FIT podem ser custeados com verba de PPB (Processo Produtivo Básico) da Lei da Informática ou investimentos de empresas que não disponham dos benefícios do PPB.

## Descrição da vaga

Buscamos desenvolvedores de software com trabalhos executados em desenvolvimento WEB e Aplicativos móveis.

## Local

Remoto ou Escritório, [SP], [SOROCABA], [JAGUARIÚNA]

## Requisitos

**Obrigatórios:**
- Formação nas áreas de Engenharia de Software, Computação, ou afins.
- 1 ano ou mais de experiência com linguagens de alto nível.

**Desejáveis:**
- conhecimentos em HTML, CSS, JAVASCRIPT
- conhecimentos em C#
- Noções de design UX e UI.
- Noções em ReactNative e Angular.

## Benefícios

- Plano de saúde
- Seguro de vida
- Plano de carreira
- entre outros de uma grande empresa.

## Como se candidatar

Por favor envie um email para alessandro.luz@fit-tecnologia.org.br com seu CV anexado - enviar no assunto: Vaga Frontend

#### Regime
- CLT

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by ylanbenoliel** [comment]
Currículo enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by aledaluz** [comment]
Olá  @felipefialho , podemos fechar.
