### ISSUE TITLE
[Florianópolis] Estágio Full Stack Developer na Conexão Solar

### ISSUE THREAD

**Issue by dandeastrigi** [frontendbr/vagas#3697]
> Vaga Remota durante a pandemia

## Nossa empresa

Somos uma empresa que tem como objetivo impulsionar o mercado de energia fotovoltaica no Brasil.

## Descrição da vaga

Você vai auxiliar no desenvolvimento de soluções web utilizando as tecnologias Angular, GoLang e MongoDB.

## Local

Remoto durante a pandemia, flexível após ou Escritório, [SC], [Florianópolis], [João Paulo]

## Requisitos

**Obrigatórios:**
Completar o desafio neste [link](https://github.com/Conexao-Solar/challenge-user-crud)

**Desejáveis:**
- conhecimentos GoLang
- conhecimentos em JavaScript
- conhecimentos em MongoDB

**Diferenciais:**
- projetos opensource

**Diferenciais:**
- trabalho remoto

## Contratação

Estágio

## Como se candidatar

Por favor envie um email para dande.astrigi@gmail com o link para o seu desafio - enviar no assunto: Vaga Full Stack

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: dande.astrigi@gmail.com

#### Alocação
- Remoto

#### Regime
- Estágio

#### Nível
- Júnior

**Comment by will-796** [comment]
Qual o prazo de entrega?

**Comment by dandeastrigi** [comment]
Pretendemos manter em aberto até 30/10

**Comment by lucaspmatos** [comment]
Se esses requisitos aí são desejáveis, como a pessoa vai responder o desafio obrigatório da vaga? Estágio tem que treinar o estudante ou aplica a vaga como júnior mesmo.

**Comment by dandeastrigi** [comment]
>  como a pessoa vai responder o desafio obrigatório da vaga? 
Com os requisitos desejáveis, e algumas pesquisas no [google](google.com) ou no próprio [github](github.com)

E sim, a pessoa que preencher o estágio vai receber treinamento, e caso queira aplicar seu currículo como júnior, fique a vontade, o email é o mesmo informado na divulgação da vaga.

**Comment by dandeastrigi** [comment]
Por enquanto estamos encerrando o processo por aqui, obrigado a todos.
