### ISSUE TITLE
[Curitiba] Analista Dev Front End  - SR [4VANTS] #clt #IA #html # Bootstrap

### ISSUE THREAD

**Issue by recrutar10** [frontendbr/vagas#3698]

**Comment by recrutar10** [comment]
About the job Analista DEV Front - SR - Curitiba
Nosso Cliente:

A 4VANTS é uma empresa de inteligência artificial que identifica e analisa ativos em imagens.

Capturam ou recebem fotos e vídeos dos ativos dos clientes e identifica com inteligência artificial a quantidade de ativos, anomalias e localização de cada item.

Trabalham com tecnologias que envolvem drone, tracking, mapa, imagem, cadastro, IA, entre outras. 

 

▶A Vaga:
ANALISTA DEV FRONT SR/ARQUITETO DE SOLUÇÕES
Projeto Top!! 🙋🏾‍♀️

 

▶Stacks para a vaga:

Linguagens – HTML5, CSS3, JS,

Framework – Bootstrap, Vue.js,

Outros – Google Maps, NPM, Node.js, PWA, ANT DESIGN (template).

Banco de dados – MongoDB

Metodologias Ágeis: Scrum, Sprints

 


▶Desafio:

Transformar provas de conceito em produtos robustos profissionalizando a plataforma com experiência de melhor usabilidade, intuitivo para o usuário com melhores resultados.

 

▶Tarefas:
Desenvolvimento de Front-end, componets, assets e padronização do guia de estilo aplicado.

Liderança técnica do time.

É facultativo ao profissional o desenvolvimento de back-end.

Participação de rituais do scrum: planning, review, retrospective e daily.

Uso de práticas do manifesto ágil.


▶Responsabilidades:
Apetite em colaboração

Aprendizado do nosso produto

Ensinar e aprender com os colegas

Ser a referência do arquiteto de soluções

 

▶O que buscamos para iniciar o processo:
Ensino Superior Completo.
Perfil Executor e Analista.

Criatividade

Foco no resultado

Gestão do Tempo

Gostar de Programar de Verdade

Iniciativa

Liderança

 

▶Horário de trabalho: 9 as 18h

▶Remuneração: 5 a 7k - CLT

▶Benefícios: 
VA e Ajuda de Custo 👍🏽


▶ Como participar? ✔🤩 
Fazer o apply da vaga para fazer as avaliações online e participar da entrevista.
Fique de olho no seu e mail, pois daremos continuidade no processo por ele.

**Comment by recrutar10** [comment]
[](url)www.novarerh.com.br

> curitiba

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
