### ISSUE TITLE
[São Paulo] Front-End Developer na Adyou

### ISSUE THREAD

**Issue by rmiyasaki** [frontendbr/vagas#3699]
**OPORTUNIDADE FRONT-END Pleno!**

Procuramos canditados Front-End, que tenha conhecimentos em React Native, para atuação de trabalho em formato de Squad, que esteja familiarizado com as metodologias agéis e experiência na linguagem por pelo menos 2 anos.

Esse profissional será integrante ativo de uma Squad de desenvolvimentos mobile, responsável por desenvolver, testar e entregar as aplicações, seguindo as histórias votadas e acordadas com o PO em cerimônia de Planning, utilizando as boas práticas de programação Front-end!

**Responsabilidades:**
- Desenvolver, testar IU e entregar aplicativos móveis.
- Criar código reutilizável e bibliotecas para uso futuro seguindo boas práticas de desenvolvimento.
- Seguir com precisão protótipos.

**Qualificações:**
- Bacharelado ou equivalente em Ciência da Computação.
- Mais de 2 anos de experiência em desenvolvimento front-end com React Native.
- Familiaridade usando metodologias de desenvolvimento Scrum / Agile.
- JavaScript, HTML, CSS.

_Canditado por favor enviar currículo com pretensão de contratação PJ para rafael.miyasaki@adyou.app_

**Quer mudar o mundo?**
Somos uma empresa em grande ascensão, com meritocracias de verdade, ambiente agradável e infinitas oportunidades!
Nosso sonho, está em nossas mãos!
Venha mudar o mundo com a Adyou!

**Comment by emersonbrs** [comment]
Enviado. ;D

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
