### ISSUE TITLE
[São Paulo] Front-End Developer Sr. – React

### ISSUE THREAD

**Issue by CadmusConsult** [frontendbr/vagas#37]
## Descrição da vaga
Front-End Developer Sr. – React
Formação em Análise de Sistemas / Ciência da Computação ou Correlatos
Experiência de 6 anos em:
•	Javascript
•	HTML
•	CSS
Experiência de 6 meses ou mais em:
•	React JS
•	SASS ou LESS
•	Bootstrap 
•	Gulp ou Grunt
Conhecimentos desejáveis:
•	Redux ou Flux
•	NodeJS
•	AngularJS
Contratação: Prestador de Serviços 
Valor acordado: Negociável.
Benefícios: VA / VR / Seguro Saúde / Seguro de Vida.
Local: Av. Paulista.

Interessados, encaminhar currículo para: adriano.antonio@cadmus.com.br

**Comment by LFeh** [comment]
Boa sorte @CadmusConsult ;)

**Comment by LFeh** [comment]
A vaga foi preenchida?  @CadmusConsult

**Comment by LFeh** [comment]
Como não teve respostas, vou fechar.

@CadmusConsult  Avisa se precisar abrir.

**Comment by camilatigre** [comment]
@CadmusConsult 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
