### ISSUE TITLE
[São Paulo] Front End Developer na Easynvest

### ISSUE THREAD

**Issue by alexkawaharada** [frontendbr/vagas#370]
Descrição da vaga

Buscamos desenvolvedores Front-End que nos ajude a trabalhar a nossa plataforma do zero, desde a arquitetura até os testes. Você vai trabalhar com designers, PM´s e outros desenvolvedores. 

Local

São Paulo / Vila Olimpia ( 5 minutos da estação Vl. Olimpia )

Benefícios

Vale Refeição, Vale Alimentação, Vale Transporte, Plano de Saúde, Plano odontológico, Gympass

Qualificações

Conhecimento e experiência em desenvolvendo com Javascript Vanilla, Angular, React, Redux, HTML e CSS; 
Experiência em novos desenvolvimentos, planejando a arquitetura de soluções do zero; 
Capacidade de desenvolvimento estruturada; 

Contratação

CLT Full + Benefícios

Nossa empresa

A Easynvest é essencialmente uma empresa de tecnologia, que quer construir a melhor experiência de investimento que existe. Estamos montando um time multidisciplinar para realizar esse desejo, com pessoas brilhantes para pensar em todos os aspectos da nossa estrutura. 

Como se candidatar:

Se você topa encarar o desafio de mudar o mundo de investimentos, mande seu CV para http://grnh.se/6i1tbe1

**Comment by LFeh** [comment]
Repetida
