### ISSUE TITLE
[São Paulo] Front-end Developer na Pontte

### ISSUE THREAD

**Issue by Xhamps** [frontendbr/vagas#3700]
> Vaga Remota durante a pandemia

## Nossa empresa

Se você ainda não ouviu falar sobre a Pontte, vem conhecer o que fazemos e quem sabe essa vaga não é tudo que estava procurando?
 
Somos uma plataforma de empréstimo digital construída para resolver o doloroso cenário de crédito no Brasil.
Além das altas taxas de juros e do processo burocrático, as relações entre devedor e credor são desiguais, com os players abusando de seu poder sobre o consumidor e levando pessoas a se endividarem cada vez mais,
 
Nós viemos para mudar isso. Acreditamos que o crédito deve ser simples, inteligente, justo, flexível e principalmente humano.
 
Combinamos nossa obsessão com eficiência com dados e tecnologia para oferecer taxas de juros mais baixas, prazos de pagamento mais longos e mais controle sobre o contrato. Nossos empréstimos se adaptam ao fluxo financeiro das pessoas - e não o contrário.
 
Se você quer trabalhar em uma Fintech com um ambiente descontraído, pessoas motivadas e participar da mudança da experiência de crédito no Brasil, dá uma olhadinha com carinho nessa vaga:

Estamos em fase de crescimento, temos muitos desafios pela frente. Por enquanto precisamos muito de um(a) engenheiro(a) de software, com experiência e acima de tudo brilho no olho :) Se você quer construir produtos do zero, melhorar produtos existentes, trabalhar em uma Fintech de crescimento acelerado, com um ambiente descontraído, pessoas motivadas e com muita autonomia, essa vaga é pra você.

## Descrição da vaga

- Ajudar na evolução do nosso design system.
- Desenvolver e treinar outros engenheiros de software, ajudando-os a avançar em suas carreiras.
- Compartilhe conhecimento de forma eficaz.
- Ajudar no levantamento de requisitos junto com o time de produto.
- Inspire e conduza a excelência operacional e de engenharia entre as equipes.
- Apoie a equipe de engenharia na obtenção de um alto nível de qualidade técnica, confiabilidade e facilidade de uso.
- Desenvolvimento do sistema e das documentações

## Local

Escritório, São Paulo, SP
End: R. Dr. Renato Paes de Barros, 955 - 132 - Itaim Bib

## Requisitos

**Obrigatórios:**
- 6+ anos de experiência com desenvolvimento de software.
- Ter conhecimentos sólidos em HTML, CSS e JS
- Ter grande experiências com REACT.
- Capacidade de elaborar testes unitários e de integração.

**Desejáveis:**
- Vivência com AWS
- Experiencias com CI/CD
- Noções de design UX e UI.

**Diferenciais:**
- Conhecimentos em python

## Benefícios

- Plano de Saúde Bradesco pago integralmente pela Pontte para você e seus dependentes diretos (Marido, Mulher e filhos).
- Plano Odontológico pago integralmente pela Pontte para você e seus dependentes diretos (Marido, Mulher e filhos).
- Vale Alimentação/Vale Refeição com valor total de R$ 800,00 que você pode dividir como preferir.
- Incentivo aos estudos no valor anual de R$ 1.500,00 (você pode usar esse dinheiro para cursos, livros, eventos que tiverem relação com a sua atividade aqui na Pontte).
- Gympass com desconto de até 75% para você e seus dependentes
- Vale Transporte.
- Pipoca e frutas todos os dias 
- Muita risada, gente bacana, crescimento pessoal e profissional e projetos desafiadores

## Como se candidatar

Por favor envie um email para xhamps@pontte.com.br com o link do Github e Linkedin - enviar no assunto: Vaga Senior Front-end Developer

#### Alocação
- Alocado (Remota durante a pandemia)

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
