### ISSUE TITLE
[São Paulo/SP] FullStack Developer @ InfoCensus

### ISSUE THREAD

**Issue by betodoescher** [frontendbr/vagas#3701]
## Nossa empresa

A partir de um projeto de consultoria desafiador, a InfoCensus nasceu com a visão de fornecer ferramentas de gestão inovadoras que trouxessem uma grande variedade de auxílios para o mercado corporativo.
A InfoCensus trabalha desde o fornecimento de soluções web e mobile, até na otimização de processos e controles na cadeia de produção.
Oferecer as melhores alternativas para agilizar processos, proporcionar soluções inteligentes e rápidas e garantir flexibilidade são os principais objetivos da InfoCensus. Seja para pequenos e grandes negócios como para a área governamental, estamos à disposição para atender o cliente de forma eficiente.

## Descrição da vaga

Buscamos por um perfil profissional com proatividade e comprometimento em entregar software com qualidade, contribuindo com conhecimentos e experiências para aumentar a qualidade técnica do próprio time. Atuará na construção do Front-end e Back-end utilizando Vue.js e Laravel.

## Aqui você irá

- Desenvolver código limpo, testável e de fácil manutenção
- Contribuir com todo o processo de desenvolvimento de software
- Implementar features novas e investigar problemas em produção
- Contribuir nas discussões técnicas sobre os desafios encontrados
- Participar do processo de code review, garantindo qualidade e consistência do código

## Procuramos por pessoas que

- Sejam detalhistas e analíticas
- Gostem de lidar com projetos grandes e desafiadores
- Consigam trabalhar em equipe de forma colaborativa e em função de um objetivo comum
- Busquem aprendizado constante
- Queiram construir um ambiente de trabalho de respeito e apoio mútuo

## Local

Escritório, São Paulo/SP - Zona Sul

## Requisitos

**Obrigatórios:**
- Experiência desenvolvendo aplicações complexas
- Conhecimentos avançados em PHP 7 e Laravel/Lumen
- Sólido conhecimento em API RESTful e JWT
- Conhecimentos avançados em HTML, CSS, JavaScript
- Vue.js 2 ou framework similar (React, Angular)
- Git
- Inglês técnico

**Diferenciais:**

- Vue.js 2 ou framework similar (React, Angular)
- Quasar Framework
- Github ou projetos pessoais de estudo
- Processos/Ferramentas de Integração Contínua
- Docker
- Plataformas em nuvem (experiência em GCP, Azure ou AWS)
- Projetos open-source

## Contratação

- CLT

## Como se candidatar

Por favor, envie um e-mail para klelber.doescher@census.inf.br com seu CV anexado. Enviar no assunto: Vaga FullStack Laravel/Vue-js

#### Alocação
- Flexível

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
