### ISSUE TITLE
[REMOTO] Front-end Developer Reactjs na Pixter

### ISSUE THREAD

**Issue by D440** [frontendbr/vagas#3705]
## Nossa empresa

A Pixter é uma boutique de software, focada em grandes clientes. Com um time de mais de 100 pessoas, trabalhando em projetos nos EUA, Portugal e Brasil, a Pixter está guiando a transformação digital de algumas das principais empresas do mundo.

Estamos em busca de Reactjs Developer, com experiência sólida, em nível Pleno/Sênior, excelente comunicação, boa desenvoltura em reuniões de planejamento, organização e bom relacionamento interpessoal.

## Descrição da vaga

Requisitos:

HTML: padronização, acessibilidade, mobile patterns.
CSS hierárquico e de fácil manutenção.
Desenvolvimento voltado à componentização.
Domínio em Javascript nativo (ES6>).
Domínio em ReactJS e outros frameworks single-page.
Noções básicas de ferramentas para controle de versão.
Experiência com Gulp, Grunt ou Webpack

## Local

REMOTO

## Benefícios

O que a gente te oferece?
Benefícios Flexíveis (Rappi, Uber, Ubereats, Ifood, Starbucks, Bilhete Único, Spotify, Netflix, Mercados, Padarias, Serviços Médicos, Cursos, etc) - você decide com o que gastar, afinal pessoas são diferentes, seus benefícios também podem ser.
Trabalho Remoto.
Se precisar, escritório disponível com: salas de reuniões, área de descompressão, cabines de call, 24/7, café, água saborizada e chopp (isso mesmo, chopp todo dia), pra relaxar :)
Contratação no modelo PJ

**Diferenciais:**
 Processo seletivo são apenas de duas etapas.

## Contratação

PJ

## Como se candidatar

Por favor envie um email para lara.todeschini@pixter.com.br com seu CV anexado - enviar no assunto: Vaga Reactjs

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.

## Labels

- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
