### ISSUE TITLE
[REMOTO] Front-end Developer na Colored Byte

### ISSUE THREAD

**Issue by lucascredie** [frontendbr/vagas#3706]
> Vaga Remota

Esta posição é 100% remota, para trabalhar em uma agência americana de crescimento constante, cheia de projetos diferentes. Somos uma start-up que precisa de pessoas que querem trampar, crescer e aprender junto.

**Alguns detalhes:**

- A gente não se importa com quantos anos de experiencia você tem, contanto que você seja bom e tenha paixão por aprender
- **Ego** não existe nessa empresa, o nosso foco é trabalhar juntos para criar projetos e obter resultados para os clientes

**O que você vai fazer:**

- Usar temas de Shopify para montar lojas
- Usar Liquid, HTML, CSS e JS (vanilla ou jQuery) para customizar temas e criar features
- Fazer o set up de apps nas lojas
- Criar settings do Shopify como Shipping, Collections e Products
- Se comunicar com clientes para entender os requerimentos e apresentar os projetos
- Trabalhar com o gerente de projeto e desenvolvedores para garantir uma boa entrega

**Beneficios:**

- Salário de 4K - 6K reais mensais.
- Posição 100% remota. Só avise a gente aonde você está no mundo :)
- Possibilidade de crescer com a empresa e moldar os processos
- Cursos e investimentos em educação
- **Equilíbrio**. Diferente de agencias tradicionais Brasileiras, a gente não espera que você trabalhe 12 horas por dia

**O que você precisa:**

- Não ter Ego e ter sempre vontade de aprender mais.
- Atitude. Você quer resolver problemas e não desiste fácilmente.
- **Domínio de Shopify e os Apps que existem**.
- Domínio de HTML, CSS e JS Vanilla
- Noções básicas de ferramentas para controle de versão.
- Capacidade de trabalhar 8 horas por dia
- Ótima comunicação com clientes e gerente de projetos em inglês.
- Estar disponível para se comunicar com o time.
- **Inglês fluente** (não precisa ser nativo)
- Familiaridade com Slack, Asana e G-Suite
- Não se importar em fazer tarefas manuais e repetitivas
- Ter ownership do projeto. Você vai atras e resolve as coisas.
- Multitasking em projetos diferentes
- Ter um laptop e computador com Internet estável

**O que seria mais do que perfeito:**

- Entender SVGs e Animações web com JS

**Se você se identifica:**

1. Preencha: [https://forms.gle/5v7Y6cXxf9cjZaqs8](https://forms.gle/NBH4jdL5dXwWfBT49)
2. Nós entraremos em contato

Att,

Lucas & Gustavo,

Founders at [coloredbyte.com](http://coloredbyte.com)

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
