### ISSUE TITLE
[Remoto] Front-end Developer VUE.JS na Angular e-Commerce

### ISSUE THREAD

**Issue by reichert** [frontendbr/vagas#3707]
## Vaga remota - para sempre remota
- Vaga remota CLT para fazer parte da nossa equipe
- Vaga para nível Pleno

## Nossa empresa
- Nossa empresa faz um e-commerce de nicho (para academias) e se baseia em vue.js no frontend e python no backend. Somos hoje os maiores deste segmento no Brasil e competimos com soluções estrangeiras, batendo em qualidade em muitos aspectos.

## Descrição da vaga
- A vaga é exclusiva para frontend em vue.js (existe outra equipe de backend);
- A vaga é para desenvolvimento de mecanismos javascript que são colocados em outros websites; construir painéis administrativos; apoiar a parte de javascript de nosso CMS;
- A vaga é para fazer parte da equipe e ter carteira assinada CLT;
- A vaga é para pleno, precisamos de experiência de pelo menos 12 meses em desenvolvimento vue.js;
- Nosso desejo é ter você conosco no longo prazo!

## Local
- A sede fica em Barueri - SP
- Site: https://angulare.app/

## Requisitos
**Obrigatórios:**
- 12 meses de experiência desenvolvendo websites em alguma ferramenta CMS (wordpress, duda, etc)
- ser meticuloso no design - ou seja - saber olhar para a tela e saber onde a margem está errada, onde a fonte está um pouco maior, etc...
- conhecimento em javascript avançado e vue.js

**Desejáveis:**
- conhecimentos na plataforma duda seria fantástico
- conhecimento em dashboards administrativos em vue.js seria ótimo

## Contratação
- Exclusivamente CLT

## Como se candidatar
- Por favor, envie um e mail para rh@angular-ecommerce.com - com seu CV anexado - enviar no assunto: Vaga Developer Frontend VUE.JS

## Tempo médio de feedbacks
- Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by JeanGoncalves** [comment]
Desculpe o comentário, mas acho válido também colocar um ponto ai para a vaga que necessita de pessoas que conheçam de Segurança também, pois acabei de verificar que o Swagger da aplicação backend está aberta ao público com todos os endpoints disponíveis 😞 

![image](https://user-images.githubusercontent.com/12532647/96766608-bb73ce00-13b1-11eb-9974-8e05f73839c9.png)
