### ISSUE TITLE
[Fortaleza ou Remoto] Front-end Developer na Agenda Edu

### ISSUE THREAD

**Issue by gurgelrenan** [frontendbr/vagas#3711]
## Nossa empresa

Surgimos em 2014 para ajudar a resolver o problema de um pai, mas vimos que poderíamos ir além e nos tornamos a solução de milhares de responsáveis. Conseguimos, assim, construir juntos uma comunicação escolar simples, rápida e eficiente que ajuda diariamente mais de meio milhão de pessoas.

Nosso propósito é ajudar, é estar lado a lado na jornada educacional, construindo uma rede inteligente para troca de ideias e experiências. Aproximamos famílias e escolas com interações que geram valor e fortalecem laços.

Conquistamos amigos, parceiros e estamos presentes em mais de 2.000 escolas em todo o Brasil e com mais de 1 milhão e meio de usuários. Temos o apoio do programa Promessas da Endeavor e da Fundação Lemann, uma das maiores fundações educacionais do país, além de sermos a solução oficial da empresa líder mundial em educação. Também somos reconhecidos pela inovação através de prêmios como Santander Universidades, Desafio Brasil, Você Empreendedor e Campus Party. Atualmente fazemos parte do grupo Eleva Educação, referência nacional.

Nossa missão é engajar, tornar alunos e responsáveis participantes ativos da rotina escolar e, juntos, prepararmos para dar o próximo passo na construção de um saber plural e globalizado.

## Descrição da vaga

Buscamos por uma pessoa desenvolvedora, nível pleno e sênior. É necessário que tenha um bom conhecimento de Javascript e boa familiaridade com React Native. Você irá atuar na evolução do nosso aplicativo. Nosso app, é a solução de comunicação de mais de um milhão de usuários que acompanham diariamente a rotina escolar por meio dele. Assim, você estará impactando diretamente na jornada educacional de escolas, alunos, famílias e educadores. Venha fazer parte dessa revolução!

## Local

Remoto ou Escritório, Fortaleza - Dionísio Torres

## Requisitos

**Obrigatórios:**

 Conhecimento na stack usada na aplicação:

* React Native
* Redux
* Redux Saga
* Javascript (ES6+)
* HTML/CSS3
* Frameworks de testes unitários e funcionais

**Desejáveis:**
- Gerenciamentos de aplicações usando as lojas da google play e app store.

**Diferenciais:**
- Conhecimento em Typescript, Styled Components
- Experiência com delivery de aplicações mobile com Fastlane.

## Benefícios

- Plano de saúde (Amil 400) 100% pago pela empresa
- Plano odontológico (Amil) 100% pago pela empresa
- VR ou VA de R$ 21/dia (Alelo)
- Clube de benefícios

**Diferenciais:**
- Flexibilidade combinada de horários
- Ambiente informal onde cada um sabe das suas responsabilidades

## Contratação

CLT

## Como se candidatar

Aplicar em https://talentos.agendaedu.com/

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: renan@agendaedu.com

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by cp-yago** [comment]
Achei muito interessante a oportunidade! Estão aceitando candidaturas de nível júnior?

**Comment by gurgelrenan** [comment]
@cp-yago no momento não.
