### ISSUE TITLE
[Uberlândia/ Home Office] Front-end Developer no Social Bank

### ISSUE THREAD

**Issue by LeticiaGonzaga** [frontendbr/vagas#3712]
## Nossa empresa 

O Social Bank é uma startup inovadora que atua no ramo de serviços financeiros. Somos uma empresa feita de pessoas que acreditam em pessoas e estamos numa grande jornada para ressignificar os valores da sociedade.
Além de ser uma empresa que está em ascenção o nosso diferencial é que vemos as relações com um olhar mais humano, com o lema “Não é sobre dinheiro e sim sobre valores. ”

[Visite nosso site](https://socialbank.com.br)

[Visite nosso blog](https://blog.socialbank.com.br)

## Descrição da vaga

Desenvolvedor Front-End com foco em Angular para atuar nas aplicações do Social Bank.

## Local

Remoto ou Escritório, Uberlândia - MG

## Requisitos

**Obrigatórios:**
- HTML5 e CSS3;
- JavaScript e ECMAScript;
- Angular 7 ou Superior.

**Desejáveis:**
- Criação de WebComponents;
- Noções em UX e UI;
- Consumo de APIs REST;
- React, Vue, Node.js e jQuery.

**Diferenciais:**
- Ser preocupado com qualidade e adepto de boas práticas de desenvolvimento;
- Senso de empreendedorismo, estar sempre em busca de conhecimento, ser dinâmico e proativo;
- Gostar de criar, inovar e transformar o complexo em simples;
- Conhecimentos em metodologias ágeis, Scrum e Kanban.

## Benefícios

- Plano de saúde
- Seguro de vida
- Vale Refeição
-  Vale Alimentação
- Plano Odontológico

**Diferenciais:**
- Vale Boas Vindas
- Vale Indicação
- Vale Aniversário
- Meio período de folga no aniversário
- Vale tempo de casa
- Parcerias com estabelecimentos

## Como se candidatar

Por favor envie um email para teamtech@socialbank.com.br com seu CV anexado - enviar no assunto: Vaga Front-End

## Labels

- Angular
- React
- HTML
- CSS
- REST
- CLT
- PJ

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by fabiomirandaa** [comment]
Essa vaga tem possibilidade de ser Totalmente remota?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
