### ISSUE TITLE
[Remoto ou Belo Horizonte/MG] Front-end Developer na Brickz

### ISSUE THREAD

**Issue by rafaelmagal** [frontendbr/vagas#3714]
### **Front-end Developer -Pleno**

**A Brickz**
A Brickz, pertencente a Ipê, é o programa de vantagens criado para fidelizar e incentivar toda a cadeia construtiva. Atuamos em parceria com grandes empresas da construção nos segmentos: indústria, civil, infraestrutura, incorporação de edifícios e muitos outros.

Chegamos para oferecer a solução para o maior desafio do setor: a improdutividade!

Saiba mais [aqui](https://www.linkedin.com/company/brickzcoin/)!

### **Descrição da vaga - Front-end Developer - Pleno**
- Desenvolvimento de Front-end Web e Mobile em Cordova;
- Integração entre front-end e back-end com protocolo HTTP;
- Programar em JavaScript, HTML 5, CSS, ES6 e ES7;
- Utilização de framework tais como VueJS;
- Realizar modelagem e arquitetura front-end, integrações utilizando API REST e com controle de versão, preferencialmente Git e uso do CodeCommit.

### **Requisitos**

**Conhecimento Avançado**
- JavaScript;
- API REST;
- HTML 5 + CSS3;
- ES6 e ES7;
- Protocolo HTTP;
- VueJS.

**Conhecimento Intermediário**
- Cordova;
- Sass.

**Conhecimento Desejável**
- Conhecimentos em frameworks atuais, como Angular, Ember, React;
- LESS.

### **Informações Adicionais**
- Trabalho remoto ou presencial (Belo Horizonte/MG);
- CLT;
- 40 horas semanais, de segunda a sexta.

### **Benefícios e diferenciais**
- Vale Alimentação ou Refeição - R$25/dia;
- Vale Transporte (caso necessário);
- Plano de Saúde - Bradesco;
- Plano Odontológico - Bradesco;
- Gympass;
- Seguro de Vida;
- Horário flexível.

### **Como se candidatar**
Todo o processo seletivo e feedbacks são feitos através da nossa Página de Carreiras!
[https://ipeholding.gupy.io/jobs/518832](https://ipeholding.gupy.io/jobs/518832)

## Labels

Local: Remoto ou Belo Horizonte/MG
Nível: Pleno
Contratação: CLT
Tecnologias: JavaScript, VueJs

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
