### ISSUE TITLE
[São Paulo] Front-end Developer na Mazzatech

### ISSUE THREAD

**Issue by LuNogueira** [frontendbr/vagas#3715]
[São Paulo] Front-End Developer na Mazzatech

> Vaga Remota durante a pandemia

## Mazzatech 

Transformamos oportunidades em sucesso, impulsionando o potencial de cada profissional através da nossa precisão em identificar talentos.

## Descrição da vaga

Atuação em projetos de desenvolvimento de uma grande empresa de Seguros.

## Local

 Escritório, [SP], [São Paulo], [Bela Vista]

## Requisitos

**Obrigatórios:**
-  Experiência com HTML5, CSS3, Javascript
-  Experiência com Angular 8, Vue, React

**Diferenciais:**
- Conhecimento em Flutter

## Benefícios

- Plano de saúde
- Plano Odontológico 
- Seguro de vida
- VR de R$ 22,75/dia
- VT
- Auxílio creche
- PLR
- ...

## Contratação

CLT 

## Como se candidatar

Por favor envie um email para lucas@mazza.tech com seu CV anexado - enviar no assunto: Vaga Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.
E-mail para contato em caso de não haver resposta: rhmazza@mazza.tech

#### Alocação
- Alocado
- Remoto durante a pandemia

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by BrendonHenrique** [comment]
Enviei meu currículo ! :)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
