### ISSUE TITLE
[São Paulo] Front-end Developer na EXAME

### ISSUE THREAD

**Issue by lcarvalho-pixel** [frontendbr/vagas#3717]
> Vaga Remota durante a pandemia

## Nossa empresa

A Exame é uma marca sólida, fundada há 52 anos e uma das publicações mais respeitadas do Brasil. Nós pertencíamos à um grupo editorial e desde o início deste ano nos tornamos um empresa independente e o que isso significa? Significa que tudo é novo! Somos uma empresa nova, com mentalidade nova, novos produtos e principalmente um sonho grande! Estamos desenvolvendo o modelo de negócio para torná-la uma plataforma one stop shop de educação, conteúdo, análise e experiências buscando ser o principal veículo para o desenvolvimento pessoal e profissional dos Brasileiros.

E Para nos ajudar nesse desafio estamos buscando pessoas apaixonadas por construir aplicações web altamente escaláveis!

## Descrição da vaga

**No seu dia-a-dia:**

- Você irá trabalhar junto com o time para criar uma nova plataforma de criação/publicação de conteúdo editorial
- Refinar e analisar dados sobre o uso dos nossos aplicativos web
- Usar API de serviços (internos e externos)
- Terá liberdade e pensamento crítico para propor e questionar soluções relacionadas a engenharia

**O que esperamos de você:**

- Domínio em CSS/HTML/JavaScript
- Domínio em PHP
- Saiba utilizar APIs REST
- Conhecimento em ReactJs
- Conhecimento em testes unitários, performance e integrados;
- Conhecimento em bancos de dados relacionais e não relacionais;
- Conhecimento da cultura DEVOPS (Jenkins, Pipeline scripts).
- Conhecimento em GIT

## Local

São Paulo

## Benefícios

- Plano de saúde
- Seguro de vida
- VR e VA
- VT
- Bônus

## Contratação

CLT

## Como se candidatar

Se candidatar no link: https://jobs.kenoby.com/exame/job/frotend-engineer/5f934cde8b33d6247f2adbde

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
