### ISSUE TITLE
[Rio de Janeiro] Fullstack Developer

### ISSUE THREAD

**Issue by nandosangenetto** [frontendbr/vagas#372]
## Descrição da vaga

- Profissional atuará como líder técnico
- Atuará junto a equipe comercial da empresa, auxiliando na compreensão da necessidade do cliente, como nas estratécias de desenvolvimento, levantamento de requisitos e demais necessidades técnicas.
- Será responsável por articular e atuar na pesquisa e desenvolvimento de projetos internacionais
- Em conjunto com os demais líderes técnicos, auxiliará no desenvolvimento do modelo e na implementação de processos técnicos
- Atuará como apoio no desenvolvimento e produção
- Auxiliará na padronização do código e na documentação de projetos

## Local

Escritório, Rio de Janeiro - Botafogo

## Benefícios
- Café da manhã e da tarde
- Vale refeição
- Vale transporte
- Plano de saúde
- Plano odontológico
- Uma festinha por mês

## Requisitos

**Obrigatórios:**
- Inglês
- Experiência no mercado digital
- Sólida experiência com desenvolvimento frontend: HTML, CSS, JavaScript (desenvolvimento responsivo)
- Sólida experiência com desenvolvimento backend: PHP (Zend ou Laravel)
- Experiência com banco de dados MySQL, controle de versão GIT, ambientes Linux
- Experiência em metologias ágeis

**Diferenciais:**
- Experiência com projetos internacionais
- Experiência com gestão de equipes
- Experiência com CMS: WordPress
- Excelente habilidade de comunicação
- Experiências em outras linguagens de programação não citadas acima serão um diferencial importante

## Contratação

CLT a combinar (Pleno-Sênior)

## Nossa empresa

A Webedia é um grupo de mídia digital de origem francesa presente atualmente em sete países, com verticais que totalizam 92 milhões de visitantes únicos por mês, cobrindo temáticas de entretenimento como cinema, games, gastronomia, celebridades/glamour, viagem e influenciadores.

No Brasil, publicamos seis verticais próprios como os líderes TudoGostoso (gastronomia), AdoroCinema (cinema) e IGN (games); além de PurePeople, Purebreak e PureViagem. Somos hoje o 12º maior grupo de mídia digital no Brasil, com total de 34 milhões de visitantes únicos por mês. Considerando apenas a área de entretenimento, o ComScore apontou a operação brasileira da Webedia como uma das sete maiores audiências digitais da América Latina, em ranking liderado pelo YouTube.

Por meio de nossa divisão de Brand Publishing, colocamos à disposição das marcas todo este conhecimento de geração de audiência e produção de conteúdo. Sempre em sinergia com nossos verticais, produzimos conteúdos relevantes para as marcas e o target de cada uma delas como, por exemplo, o site Beleza Extraordinária para a L’Oréal Paris ou o dispositivo #PreparadoPraValer para a Gillette. 

Nossas publicações recebem milhões de visitas diárias em diferentes plataformas como Google, Facebook e Youtube. Contamos com uma equipe altamente treinada para a otimizar a produção de conteúdo e potencializar a performance de nossos verticais nessas nossas plataformas. 

Nossa chegada ao Brasil aconteceu em 2012, num empreendimento liderado por Cyrille Reboul, um dos fundadores da Webedia na França e com histórico pessoal no Brasil. A operação começou com as versões brasileiras dos verticais PurePeople e PureBreak, dedicados aos jornalismo de celebridades e conteúdo para o público jovem respectivamente. Capitalizada pela aquisição do grupo francês Fimalac, do bilionário Marc Ladreit de Lacharriere, da acionista da agência de classificação de risco de crédito Fitch Ratings; a Webedia comprou o vertical AdoroCinema em 2013 e o ajudou a se consolidar como líder em audiência no segmento de cinema na internet brasileira, com 25 milhões de acessos por mês, marca alcançada em 2016. 

Após experimentar crescimento orgânico em 2014, o ano seguinte foi dedicado a importantes investimentos. Em fevereiro de 2015, a Webedia lançou o IGN Brasil, que em menos de um ano se tornou o vertical líder em games e a terceira maior edição nacional da franquia em todo mundo, atrás apenas dos EUA e do Reino Unido. Em agosto, a empresa anunciou a aquisição do TudoGostoso, maior comunidade de gastronomia da América Latina por R$ 49 milhões. 

Ainda em 2015, no mês seguinte, foi a vez de adquirir capacidade de produção de conteúdo em formato de vídeo digital através da compra da Paramaker. Nessa mesma negociação, a Webedia assumiu o controle do canal Parafernalha, uma das referências do humor no YouTube brasileiro e um dos poucos que já ultrapassou a barreira de um bilhão de views.

O apetite por aquisições seguiu forte em 2016. Em março, a Webedia anunciou investimento na Digital Stars, agência brasileira especializada em gerenciamento de carreira de influenciadores digitais. Fundada no ano anterior por Luiz Felipe Barros, a empresa conta com uma seleção dos maiores influenciadores digitais do país: Kéfera do canal 5incominutos; Christian Figueiredo, do Eu Fico Loko; Felipe Castanhari, do Nostalgia; o casal Leon Martins e Nilce Moretto, do Coisa de Nerd; Eduardo Benvenuti, do BRKsEDU; Lukas Marques e Daniel Mologni, do Você Sabia; Malena Nunes; Flavia Calina, entre outros. No total, são mais de 5,7 bilhões de visualizações e uma média de 300 milhões de visualizações mensais. No Facebook são mais de 20 milhões de seguidores, 15 milhões no Instagram e 17 milhões no Twitter.

Após a consolidação de sua presença nos segmentos de cinema, celebridades, games, gastronomia e influenciadores digitais, a Webedia encerrou 2016 anunciando a aquisição da Nerd ao Cubo, empresa de assinaturas de caixas surpresas com produtos do universo Nerd com o objetivo de criar produtos e sinergias com todas as comunidades de verticais, oferecendo um novo canal de relacionamento para todas as marcas parceiras.

A Webedia, que começa 2017 de casa nova em São Paulo, terá área de eSports como um dos focos de investimento ao longo do ano. Para promover competições e engajar parceiros e fãs de games nessa nova frente, a empresa construiu uma área com capacidade para 200 pessoas em sua nova sede, no bairro da Vila Olímpia, tendo como estreia a Overwatch Old Spice Tournament by IGN.

“Somos uma empresa jovem, nascida e criada no mundo digital, de visão ilimitada e com forte crescimento orgânico. Incentivamos os colaboradores a desenvolver seu lado empreendedor, valorizando cada conquista. Nosso ambiente de trabalho é transparente e inspirador, onde a criatividade e o dinamismo são praticados com espontaneidade e paixão”, afirma Cyrille Reboul, destacando o papel chave do Brasil na estratégia global da Webedia.

## Como se candidatar

Por favor envie um email para nando.sangenetto@webedia-group.com com seu CV anexado - enviar no assunto: Vaga PHP Full Stack

**Comment by thiagoverly** [comment]
Legal a vaga, ainda está aberta?

**Comment by nandosangenetto** [comment]
Sim

**Comment by LFeh** [comment]
Aberto ainda?
