### ISSUE TITLE
[Rio de Janeiro/Remoto] Full-Stack NodeJS/React Developer @ COOBO

### ISSUE THREAD

**Issue by VIMGAS** [frontendbr/vagas#3721]
## Nossa empresa

A COOBO é uma consultoria especializada em gestão de gastos (procurement) que existe desde 2011 com o objetivo de ajudar seus clientes a melhorar seus processos de compras e, com isso, gastar menos.

_"Nossa atuação está voltada para uma gestão ágil, colaborativa, tecnológica e inovadora para a área de compras, buscando adaptar novos conceitos de mercado às necessidades que identificamos em nossos clientes."_

Em 2017, a COOBO resolveu pivotar parte de seu negócio e criou o Spendfy, plataforma SaaS de monitoramento e análise de gastos que ajuda os seus clientes a ter uma visão direta e isenta de como sua empresa utiliza seus recursos.

## Descrição da Vaga

Seu foco será manter e criar novas features para o Spendfy, sistema distribuído em microserviços e alocado na Microsoft Azure, utilizando Docker, Nginx, MongoDB, Redis, entre outros. Você trabalhará diretamente com o CTO da empresa e terá inúmeras oportunidades de crescimento.

### Local

- Escritório no Humaitá, Rio de Janeiro; ou
- Trabalho Remoto

## Requisitos

**Obrigatórios:**
- Javascript
- NodeJS
- ReactJS
- NGINX
- Docker
- Git e Github
- MongoDB

**Desejáveis:**
- Conhecimentos em Microservices
- Experiência com DDD
- Experiência com Microsoft Azure
- Experiência com Github Actions
- Conhecimentos em Python

**Diferenciais:**
- Typescript
- Experiência com Observabilidade e Monitoramento

## Benefícios

- Horário 100% flexível de 44 horas semanais

## Contratação

- PJ a combinar

## Como se candidatar

Por favor envie um e-mail para: victor.silva@coobo.com.br contendo seu currículo, link para o linkedin e github. Favor colocar no assunto "Vaga NodeJS Dev".

## Tempo médio de feedbacks

Costumamos enviar feedbacks até 10 dias após o fim do processo. O e-mail para contato em caso de não haver feedback é o mesmo.

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

#### Outros
- Rio de Janeiro
- Full Stack
- React

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
