### ISSUE TITLE
[Rio de Janeiro/Remoto] Full-Stack Developer | NodeJS / React #TVManager

### ISSUE THREAD

**Issue by danielcozer** [frontendbr/vagas#3722]
# Descrição da vaga

Somos uma Startup especializada em inovações em mídia, desenhadas para atender o mercado televisivo e produtores de conteúdo audiovisual. Não importa sua formação, o que importa é o talento e a vontade de fazer parte de um time para desenvolver uma plataforma extremamente inovadora para o mercado ! Conheça nossa plataforma: http://tvmanager.io/

OBS: Contratação imediata! 👀

Perfil desejado: Junior e Pleno

# Local

Work AnyWhere 🚀

Sede: Rio de Janeiro, Catete
StartupRio - http://www.startuprio.rj.gov.br/

# Benefícios

• Horário de trabalho flexível
• Um ambiente de trabalho diferente e inovador, com uma cultura que valoriza as pessoas e a entrega de resultados
• Hierarquia horizontalizada
• No dress code

# Requisitos

**Obrigatórios:**

• Fluência em Javascript
• Desenvolvimento de sistemas: Node js.
• Experiência com Mongo DB
• Experiencia GraphQL

• Experiência com arquitetura Front-end, usabilidade e testabilidade
• capacidade de traduzir layers em código
• Fluência em HTML/CSS
• Experiência com REACT

• Experiência de controle de versão de código-fonte (Git-flow);
• Ajudar a construir o software ao invés de apenas codar requisitos! participar ativamente da concepção e construção da TVManager

**Desejáveis e Diferenciais:**

• Conhecimento de serviços cloud - AWS
• Experiência com Sistemas Web / SaaS
• Experiência com testes Automatizados;

# Contratação

A combinar

# Nossa empresa

• **http://tvmanager.io/**
• Vídeo explicativo da Solução: http://bit.ly/TVManager

# Como se candidatar

Por favor envie um email para **daniel@tvmanager.io** com o seguinte título e informações:

• Assunto [VAGA] Desenvolvedor Full-Stack
• Github e/ou Blog - Vai nos ajudar a conhecer você e seu trabalho melhor :)
• Currículo ou Linkedin

Labels
Júnior
Pleno
Remoto
JavaScript
Node JS
React & GraphQL

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
