### ISSUE TITLE
[SÃO PAULO] Full-Stack Developer na Deploy. Future Agency

### ISSUE THREAD

**Issue by gabsvteixeira** [frontendbr/vagas#3723]
> Vaga Remota durante a pandemia

## Nossa empresa

A Deploy. Future Agency é uma agência de comunicação guiada por estratégia, inovação e criatividade.

Nosso objetivo é fomentar a inovação no mercado de comunicação e utilizar a tecnologia para construir experiências imersivas para os nossos clientes.

## Descrição da vaga

Irá atuar com o desenvolvimento de aplicações web, participando desde a ideação dos projetos até a produção de fato.
Será um dos principais envolvidos no desenho inicial dos fluxogramas, estruturação de banco de dados e setup dos ambientes.

Atuará junto com a gestão do projeto, participando na construção das sprints e reportando possíveis problemas.
## Local

Jornada híbrida em São Paulo / Capital (Bairro Pinheiros)

## Requisitos

**Obrigatórios:**
- Experiência com Node.js
- Experiência com React.js
- Experiência com MongoDB
- Vivência com o planejamento de projetos, desde a fase da ideação

**Desejáveis:**
- Conhecimento profundo em conceitos de responsividade

**Diferenciais:**
- Experiência com criação de temas wordpress
- Ter participado de projetos de live streaming e/ou eventos

## Contratação

PJ a combinar

## Como se candidatar

Por favor, preencha o formulário em: https://bit.ly/vagasdeploy

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.
E-mail para contato em caso de não haver resposta: gabriel@deploy.ag

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
