### ISSUE TITLE
[Curitiba/Remoto] Front-end Developer Sênior/Especialista no Pipefy 

### ISSUE THREAD

**Issue by Matheus-Quevedo** [frontendbr/vagas#3726]
> Vaga Remota durante a pandemia

## Nossa empresa

A Pipefy foi fundada em 2015 por Alessio Alionço, ex-consultor de fusões e aquisições que estava passando por profunda frustração com a inflexibilidade, má experiência do usuário e custo das ferramentas disponíveis no mercado. Suas necessidades eram simples: garantir a execução do processo ao combinar as operações comerciais de duas empresas. 

Construída por necessidade, a Pipefy tornou-se uma poderosa plataforma de Gestão do Trabalho, permitindo que as equipes tivessem mais controle sobre suas operações, conectando departamentos, centralizando solicitações e contribuindo para uma melhor visualização.

A plataforma cresceu rapidamente, alimentada por um intenso desejo de mercado por melhores soluções para gerenciar processos de negócios e automação. A Pipefy agora é usada em mais de 150 países por empresas líderes como Visa, IBM, Coca-Cola, Volvo, Santander e Kraft Heinz.

## Descrição da vaga

Buscamos uma pessoa desenvolvedora, nível sênior ou especialista. 
São fundamentais conhecimentos em React, Vue, Angular, HTML, CSS e Javascript. 
O desafio é para ser Front-end Developer com boas práticas de resolução de problemas, tomadas de decisão e análise de dados para além de execuções técnicas com grande intenção de escalonar processos dentro do time da Pipefy!
Você ajudará a melhorar o desempenho, escalabilidade e confiabilidade de nossos componentes para que o Pipefy esteja sempre disponível e no topo de seu jogo.

## Local

Curitiba ou Remoto

## Requisitos

**Obrigatórios:**
HTML
CSS
Javascript 
React 
Vue.js 
Angular
Redux
Hooks

**Diferenciais:**
Typescript 
GraphQL
Apollo 

## Benefícios

Seguro de saúde 
Remuneração competitiva 
Gympass
Plano Odontológico 
Vale refeição
Horário de trabalho semiflexível 

## Contratação

CLT

## Como se candidatar

Aplicar em [https://bit.ly/37KOG5p]

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 20 dias após cada processo.
E-mail para contato em caso de não haver resposta: contato@byintera.com

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
