### ISSUE TITLE
[São Paulo (SP) / São José do Rio Preto (SP) / Remoto] Front-End Developer Sênior na Accurate

### ISSUE THREAD

**Issue by luanmateus** [frontendbr/vagas#3729]
## Por que vir para a Accurate?

Se você busca a oportunidade de colocar seus conhecimentos em prática, aperfeiçoa-los e crescimento profissional, você está no caminho certo.

Somos uma consultoria de TI que está há três décadas no mercado, buscando sempre o aperfeiçoamento em novas tecnologias para fornecer as soluções mais adequadas às necessidades do mercado.

Prezamos pelo respeito, a ética e a transparência em todo e qualquer ambiente, acreditamos que esses são alguns dos valores básicos para qualquer relacionamento.

Oferecemos um ambiente leve e descontraído de trabalho, realizamos treinamentos, bate-papos, eventos tudo on-line pensando sempre em estratégias para tornar o seu desempenho produtivo e saudável.

Então, se você quer atuar com o que gosta, com as últimas tecnologias do mercado e fazer parte de uma equipe que só cresce, venha trabalhar na Accurate.

## Fazendo parte do time
Você terá a possibilidade de aprender novas tecnologias, colocar em prática o que conhece, tendo a possibilidade de pôr em uso suas ideias e habilidades. Trabalhando com equipes diversas esperamos que você possa evoluir sempre.

## Nossos benefícios

- Vale Refeição & Alimentação
- Seguro Saúde integral
- Plano Odontológico 
- Gympass
- PLR
- Café free
- Happy Hour
- Dayoff
- Vale Transporte/Fretado
- Aux. Creche
- Vale Home Office
- Flexibilidade de horário*
- Bônus por indicação
- No dress code
- e muito mais...

_*Flexibilidade de horário com apontamento por exceção_

## Conheça seu local de trabalho
A Accurate atualmente possui duas unidades, sendo uma delas em São Paulo e a outra em São José do Rio Preto.

Devido ao novo cenário que estamos vivenciando, causado pela pandemia, nossos colaborados estão 100% em Home Office, com grande probabilidade de continuarmos desta maneira, então a sua localidade não será um impeditivo para contratação.

## Esperamos de você
Lembre-se que você é capaz e pode sim fazer a diferença.  Acreditamos em você e estamos aqui para apoiá-lo nessa jornada. Precisamos de seu apoio e confiança para conduzirmos projetos eficientes satisfatórios para todos os envolvidos.

## Requisitos

- Possuir domínio de React
- Possuir domínio de outro frameowrk JavaScript (Angular, Vue)
- Possuir domínio sobre Testes Automatizados
- Possuir domínio sobre práticas de testes unitários utilizando Jasmine / Karma
- Possuir sólidos conhecimentos sobre JavaScript, HTML e CSS
- Conhecimento em Responsive Design
- Conhecimento em PWA
- Conhecimento em Microfrontend
- Conhecimento em SASS
- Conhecimento em LESS

**Desejável:**

- Conhecimento em Off Line First
- Conhecimento em DevOps

## Venha trabalhar com a gente
Encaminhe seu currículo para rh@accurate.com.br e no título coloque o cargo.

## Labels

- Remoto
- Remoto durante pandemia
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by luanmateus** [comment]
Vaga aberta.
