### ISSUE TITLE
[São Paulo] Estágio React/Angular/Nodejs

### ISSUE THREAD

**Issue by alanleite** [frontendbr/vagas#373]
## Descrição da Vaga

Participará no desenvolvimento de sistemas de diversas áreas de atuação, utilizando principalmente tecnologias como: React, Angular, Nodejs, JS, CSS, HTML, Docker, Rest, Hapi, Bookshelf, Knex, Mongoose, Webpack, Grunt etc...

## Local
- Alocado
- Vila Mariana - São Paulo, SP

## Benefícios
- Vale Refeição
- Vale Transporte
- Expediente de 6 horas diárias (segunda ~ sexta)

## Requisitos

**Obrigatórios:**
- Primeiro ou segundo ano da faculdade
- Não há requisitos de conhecimento, apenas desejamos que o profissional tenha a paixão de aprender e o objetivo de ser um excelente desenvolvedor.

**Diferenciais:**
- Inglês
- Javascript
- Nodejs
- Angular
- React
- Git
- Docker
- Linux
- Conceitos básicos em Rest API e SPA.  

## Contratação
- Estágio
- Auxílio: R$ 1.100,00

## Nossa empresa
http://www.interativaengenharia.com.br/

## Como se candidatar

Por favor envie um e-mail para alan@interativaengenharia.com.br com seu CV anexado - enviar no assunto: Vaga NodeJS

**Comment by gkal19** [comment]
Pena que ainda estou no ensino médio :cry:

**Comment by Iqueda** [comment]
Do interior de São Paulo não teria possibilidade? Estou a 1 hora e 30 de sp :(

**Comment by alanleite** [comment]
@Iqueda Podemos avaliar em uma entrevista, mas acredito que fique bem pesado para você, viagem + transito de SP + faculdade..

@willianjusten Pode ser enviado até segunda feira 26/07.

**Comment by willrsousa94** [comment]
@alanleite Obrigado!

**Comment by kivervinicius** [comment]
@willianjusten estão querendo te contratar? hehe
