### ISSUE TITLE
[São Paulo] Front-end Developer Pleno / Senior no Itaú Unibanco

### ISSUE THREAD

**Issue by willgm** [frontendbr/vagas#3730]
> Vaga Remota durante a pandemia, remoto eventual após esse período

## Nossa empresa

Somos o Maior Banco da América Latina, a **marca mais valiosa do Brasil e** empresa ganhadora do **Carreira dos Sonhos em 2019**, estamos presentes em 18 países impactando diariamente mais de 55 milhões de clientes através dos nossos produtos e soluções. Somos uma área que busca ser cada vez **mais digital nas soluções, humana na experiência** e no contato com as pessoas. Temos clientes diversos e precisamos oferecer soluções que atendam às necessidades e expectativas de cada um. 

Queremos as pessoas inconformadas, as inquietas, as indignadas e **apaixonadas por tecnologia**. Queremos as questionadoras e as inventivas. Não queremos você apenas por achar que você tem a nossa cara. Queremos ter um pouco da sua também.  Queremos ser a empresa que pessoas de **todos os gêneros, etnia, idade, classe e orientação sexual** escolham como lugar onde vão se desenvolver e contribuir para transformar as experiências dos nossos clientes.

### Nossa área

Somos a **Digital Foundation**, uma área de inovação que visa o desenvolvimento de uma **plataforma completa de tecnologia**, para acelerar o desenvolvimento dos canais digitais do Itaú Unibanco. Nós desenvolvemos todo tipo de ferramental interno, como SDKs, Design Systems, CLI's, automatizamos processos em esteiras, criamos e padronizamos arquiteturas que serão escaladas por centenas de equipes.

Se quiser conhecer um pouco mais sobre nós e sobre a cultura de **FrontEnd do Itaú**, recomendamos o podcast do **Hipsters On The Road**, onde falamos um pouco sobre o que estamos fazendo:

https://hipsters.tech/cultura-frontend-no-itau-hipsters-on-the-road-13/

### O que esperamos de você:

- Foco na melhor experiência para o cliente;
- Buscar aprendizado constantemente;
- Colaboração, saber oferecer e pedir ajuda;
- Proatividade, nós pensamos e agimos como dono;
- Resiliência, não se limite;
- Ética, para nós é inegociável.

### Quais serão minhas contribuições?

- Atuar em times ágeis e multidisciplinares com engenharia e desenvolvimento de aplicações e ferramental interno para FrontEnd Web, usando principalmente Angular, TypeScript e SCSS.
- Estudar, testar e documentar novas ferramentas, libs, frameworks e arquiteturas para uso interno;
- Gerar o desenho técnico e padrões de arquitetura para soluções;
- Desenhar soluções sustentáveis a partir do conhecimento da estrutura dos sistemas e soluções;
- Garantir elasticidade e escalabilidade na construção de sotfware;
- Garantir a atualização da documentação e gestão do conhecimento dos sistemas;
- Participar de todo o ciclo das aplicações desde a concepção a construção.

## Local

CEIC – Centro Empresarial Itaú Conceição - Av. Av. Eng. Armando de Arruda Pereira, 707 - Vila Guarani

## Requisitos

**Obrigatórios:**

- Experiência como desenvolvedor FrontEnd Web
- Experiência com Angular, React, Vue ou outro framework JS moderno.
- JavaScript intermediário / avançado
- Experiência TypeScript
- HTML Semântico
- Pré-processadores CSS (Sass, Stylus, Less, etc)
- Experiência com Testes de Unitários
- Frameworks de testes (Karma, Jasmine, Jest, Mocha)
- Desenvolvimento Web responsivo
- GIT na linha de comando

**Desejáveis:**

- TypeScript e Angular avançados
- Conhecimento em acessibilidade e SEO
- Ter trabalhado com grandes aplicações em produção
- Habilidades em padrões de design de interface e experiência de usuário

**Diferenciais:**
- Ter contribuições Open Source
- Participação ativa em comunidades de TI (presenciais e online)
- Experiência com testes integrados e de aceitação

## Benefícios

- Vale Transporte
- Vale Refeição (Restaurantes) / Vale Alimentação (Supermercados)
- Convênio médico e odontológico
- Seguro de Vida
- PLR (Mediante resultados do banco)
- Previdência privada
- Descontos exclusivos em nossos produtos financeiros
- Licença maternidade estendida
- Auxílio Creche / Babá (para papais e mamães)
- Gym Pass (Mas se preferir temos Bio Ritmo em alguns polos)
- Acesso aos Clubes Itaú (Guarapiranga / Itanhaém e São Sebastião)
- Algumas vantagens que você pode conhecer durante o processo 😊

**Diferenciais:**

- Horário flexível
- Equipe multi-disciplinar autônoma
- Ambiente descontraído (permitido uso de bermuda)
- Salas de jogos (pebolim, sinuca, ping-pong)
- Videogame, fliperama
- Sala de música
- Sala zen

## Contratação

CLT com salário acima da média do mercado + Benefícios

## Como se candidatar

[Se candidate pelo Linkedin.](https://www.linkedin.com/jobs/cap/view/2215569228/)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em 1 até 2 semanas após a entrevista, porém o processo pode se estender além disso.
E-mail para contato em caso de não haver resposta: fernando.basilio@itau-unibanco.com.br

#### Alocação
- Alocado
- São Paulo
- Remoto durante pandemia
- Home Office Eventual

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by fabiomirandaa** [comment]
Infelizmente não há possibilidade de Full-Remoto após a pandemia. Mas, ótima vaga! 
Se eu fosse de SP, seria minha cara hahaha!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
