### ISSUE TITLE
[Florianópolis ou Remoto] Senior JavaScript Developer @ Resultados Digitais

### ISSUE THREAD

**Issue by fernandapoloniaRD** [frontendbr/vagas#3737]
## Nossa empresa

A RD nasceu no Brasil, em 2011, com o objetivo de ajudar empresas de todos os portes e segmentos a entender e a aproveitar os benefícios do marketing digital, conquistando resultados reais e efetivos para seus negócios. 🚀

Já somos mais de 22k clientes em quase 30 países
Somos um dos principais cases de SaaS B2B no Brasil
Temos escritórios na América Latina e Europa
GPTW: são 4 anos consecutivos como uma das melhores empresas para se trabalhar no Brasil
Criamos o RD Summit, maior evento de Marketing Digital e Vendas da América Latina
Já somos +650 pessoas (RDoers)!
No nosso Culture Code você pode checar os nossos valores e no blog como trabalhamos no dia a dia.

## Descrição da vaga

Você irá participar do time que chamamos de Sauron (sim, bem vibe de LOTR, "O olho que tudo vê 👁️") que está em uma iniciativa bem desafiadora de desenvolver a própria ferramenta de web analytics, removendo então a necessidade de integração que temos hoje com o Google Analytics.

O objetivo é termos os dados e trackings dos visitantes do RD Station Marketing por meio de nossos scripts e assim ter um controle cada vez mais assertivo dos dados gerados pelos nossos clientes! 😉 Um aspecto que é bem importante nesta posição é ter um nível de conhecimento avançado em JS puro, pois você será uma referência dentro do time em relação ao browser, entender/validar o comportamento dele, além de apoiar em scripts e integrações em plataformas parceiras.

E nesse sentido, teremos MUITOS desafios na operação ligados à escala e performance uma vez que o número de visitas e conversões estão na casa dos milhões por dia e o volume de dados está na casa dos terabytes! 😮 

Por isso, buscamos uma pessoa com bastante ownership, resiliência (lidar com uma operação nesse nível não é fácil) e proatividade para abraçar essa iniciativa como sua!

As pessoas da área técnica da RD também costumam ser muito ativas na comunidade, difundindo conhecimento em eventos internos e externos - curtimos e valorizamos muito isso!

## Local

Remoto ou Escritório, Florianópolis.

## Requisitos

**Obrigatórios:**

- Que já tenha uma experiência consolidada em desenvolvimento e arquitetura em Javascript, além de estar aberto para também atuar diretamente com Ruby e Go no mesmo projeto. 

- Vivência com boas praticas de desenvolvimento ágil. Dentre as praticas que usamos: Clean Architectures, TDD, BDD, DDD, que valorize e incorpore qualidade na sua forma de modelar soluções e codar com melhoria continua.

- Seja experiente com arquitetura de software escaláveis, performáticos e de fácil manutenção;

**Diferenciais:**
-  Experiência com desenvolvendo projetos web analytics será considerada um diferencial! 😉
- Projetos opensource

## Benefícios

Plano de saúde (100% subsidiado, até para os seus dependentes);
Plano odontológico;
Vale alimentação ou refeição;
Vale transporte;
Gympass;
Outras parcerias de benefícios.

**Diferenciais:**
Horário flexível e opção de Home Office;
Trabalhar lado a lado e aprender diariamente com profissionais referência no mercado;
Cursos e certificações da RD University (nossa universidade corporativa) para você explorar;
Cultura de feedback e desenvolvimento intenso;
No dress code - então pode trazer a sua pantufa;

## Contratação

CLT

## Como se candidatar

Pode se candidatar diretamente no link: https://grnh.se/ceb67e3c2us

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: fernanda.polonia@resultadosdigitais.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Especialista

#### Foco
- Javascript

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
