### ISSUE TITLE
[Rio de Janeiro] Estágio em Front-end Developer na Fattoria

### ISSUE THREAD

**Issue by CarolPimentel** [frontendbr/vagas#3739]
<!-- Estágio em Front-End para o Centro do RJ

> Vaga Remota durante a pandemia

## A Nossa empresa:
      Possuímos sólido conhecimento do mercado digital, atuamos desenvolvendo sistemas escaláveis e aplicativos mobile, planejamento de campanha de marketing digital e criação de marca. 
      

## Descrição da vaga

       Participação na execução de sistemas web, aplicativos, portais e intranets.
       Se deseja se desenvolver, venha fazer parte do time!

## Local

Exemplo: Remoto ou Escritório, [RJ], [Rio de Janeiro], [Cen tro]

## Requisitos

**Obrigatórios:**
-  Conhecimento em:
    HTML;
    CSS;
    JAVASCRIPT nível intermediário;
    SASS;
     Git
   
**Diferenciais :**
- vivência com Adobe XD, Node.Js, Angular, React ou Vue

## Benefícios
- Seguro de vida
- VT/dia (ao retomar o trabalho presencial)
- Vale Refeição 

## Contratação

CONTRATO DE ESTÁGIO CIEE

## Como se candidatar

Por favor envie um email para rh@fattoriaweb.com.br com seu CV anexado - enviar no assunto: Vaga Estagio Front

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.

Boa sorte!

**Comment by Yanaiara** [comment]
Oii, vai adicionar a descrição da vaga ?

**Comment by atila-tokyo** [comment]
Descrição e forma de aplicar, por favor.

**Comment by CarolPimentel** [comment]
Fiz a descrição no dia. nao saiu?

Podem ajudar?

Obrigada!

Descrição da Vaga:

Auxílio em projetos Front, participando do desenvolvimento de sistemas e
aplicativos mobile, observando o fluxo de navegação, estrutura e estilo das
páginas, dentre outras aplicações de interface.


Em qua., 28 de out. de 2020 às 12:29, Yanaiara <notifications@github.com>
escreveu:

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
