### ISSUE TITLE
[Campinas] Frontend Javascript

### ISSUE THREAD

**Issue by fabriciofrontarolli** [frontendbr/vagas#374]
- Frontend Javascript

## Local

Escritório, Campinas

## Benefícios

- Vale Refeição
- Vale Alimentação
- UNIMED
- UNIODONTO
- Seguro de Vida
- PLR
- Previdência privada
- Programas de incentivos de qualidade de vida (kart, futebol, basquete, ...)
- Cesta de frutas ou barrinhas de cereais em todas as salas para incentivar uma alimentação saudável
- Ganhar um dia de folga no mês do aniversário

## Requisitos

**Obrigatórios:**
- JavaScript
- AngularJS
- ReactJS
- NodeJS
- HTML/CSS
- SQL.

**Desejáveis:**
- Inglês Intermediário ou Avançado para conversação

**Diferenciais:**
- projetos opensource

## Contratação

CLT

## Nossa empresa

Daitan Group provides high quality software development services to significantly accelerate time to market for global technology companies. The company’s expert agile teams deliver full lifecycle software product development, maintenance and quality assurance services across today’s leading technologies, including: cloud computing and virtualization; communications, collaboration and messaging; and big data/analytics. 

## Como se candidatar

Por favor envie um email para ffrontarolli@daitangroup.com com seu CV anexado - enviar no assunto: Vaga Frontend Javascript

**Comment by jvcjunior** [comment]
Possibilidade de remoto?

**Comment by fabriciofrontarolli** [comment]
Não Valter. A empresa só trabalha com funcionários alocados.

**Comment by fabriciofrontarolli** [comment]
Vaga preenchida! Valeu galera!
