### ISSUE TITLE
[Munich] Front-end Engineer na Kyte

### ISSUE THREAD

**Issue by rafaelmotta** [frontendbr/vagas#3741]
> Vaga Remota durante a pandemia

## Nossa empresa

Kyte is the answer to a lot of questions we’ve been asking ourselves.
        •  What do we want our cities to look like in the future - and for our children?
        •  How do we design an experience that has all the benefits of owning a car, without the annoyances and drawbacks of current solutions?
        •  What if ordering a car would be as easy as ordering food or a rideshare?

People don’t want to own cars, and neither do we. But when cars are not owned by individuals anymore, who will own them?  At Kyte we believe that vehicles should be owned by professionals. We are working with professional fleet owners that are the best in what they do - just as we are the best in what we do. We help professional fleet owners achieve the maximum utilization and return on assets by deploying and distributing their vehicles using Kyte - the world’s first vehicle-as-a-service platform.

https://drivekyte.com/team-and-culture

## Descrição da vaga

We are excited to grow our team with a Frontend Engineer. 

We ship code daily. Your role involves building reliable and scalable systems and infrastructure that can handle our fast growing ecosystem of customers, suppliers and operators. Both in real-time as well as in batch.

You will work closely together with the product and operations team to develop features, architect and design systems and ship products to our users, partners and internal stakeholders.

## Local

Munich (but remote during the pandemic)

## Requisitos

**Obrigatórios:**
- English (at least C1 or equivalent)
- **Bachelor in Computer Science or equivalent (required for getting a visa)**
- Relevant experience working on fast-scaling and complex systems
- Appreciation towards software craftsmanship, clean code, and SOLID design principles
- Deep knowledge of Javascript and React
- Ability to architect and design modular and scalable systems (**senior**)
- High standards for the quality of UI and experience interpreting and executing on the outcomes of UX research and Product Design
- Coaching experience. It’s important for you to learn from and teach peers, and to continuously help junior team members appreciate and apply best engineering and UX practices (**senior**)
- Hustling-, hardworking- & shipping-products attitude: Go above and beyond to get things done!
- Ownership: You are a self-starter and are satisfied by owning large chunks of the product roadmap.

**Desejáveis:**
- AWS
- Gitlab
- React Native
- Next.js

**Diferenciais:**
- Open source projects

## Benefícios

- The opportunity to be a part of the exciting early stages of a well-funded, Silicon Valley based startup that has massive growth and venture potential
- You’ll be able to work, innovate, and grow with a ridiculously ambitious, committed and fun team in the Munich and San Francisco tech ecosystem
- You’ll have the ability to have major impact on a product that is on its way to impact millions of users in a profound way
- Kyte benefits include significant equity, transportation benefits, gym benefits, office visits across between US and Europe and much more.

## Contratação

- Contrato em regime full-time (40h/mes), sem duraçao para acabar.

## Como se candidatar

Por favor envie um email para rafael@drivekyte.com com seu CV anexado em **ingles**.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by myrgato** [comment]
Mandei lá, @rafaelmotta 👍

**Comment by rafaelmotta** [comment]
up

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
