### ISSUE TITLE
[São Paulo]  Front-end Developer na Ctowl

### ISSUE THREAD

**Issue by manzettidenis** [frontendbr/vagas#3743]
**Vaga para Desenvolvedor Front-end PL/SR;**

**Nós somos a Ctowl**! Uma empresa que atua no treinamento e formação de profissionais de tecnologia com cursos livres para a comunidade. Possuímos uma fábrica de software onde prestamos serviços como “CTO as a service” e outsourcing e também temos nosso próprio startup studio, onde validamos ideias e desenvolvemos startups. Somos apaixonados por inovação, empreendedorismo e open-source e possuímos nossa própria comunidade chamada EmpreenDev, onde fomentamos conhecimentos de gestão, empreendedorismo e soft skills para desenvolvedores que buscam capacitação para cargos de liderança. Estamos criando também a DevHouse, o primeiro Hostel exclusivo para profissionais de tecnologia da cidade de São Paulo, dando uma opção para profissionais que desejam se estabelecer na cidade ou estejam só de passagem já inserindo-os no ecossistema de desenvolvimento de software paulistano e acelerando sua imersão.

**Tipo de contratação**
Integral;
Empresa 100% remota e assíncrona;
Contratação PJ

**Habilidades:**
Principalmente vontade de aprender e sempre evoluir mas além disso:
- Auto gerenciável;
- Autodidata;
- Comunicativo
- Cooperativo;
- Comprometido;
- Dinâmico;

**Principais responsabilidades**
- Desenvolvimento e manutenção de white labels em React;
- Integração com API's
- Redux / Saga
- Pair programming com outros desenvolvedores
- Escrita de testes automatizados
- Sugerir soluções criativas que otimizem o trabalho
- Estimar junto com o time a complexidade das tarefas
- Contribuir com as demais frentes da organização;
- Interesse em ensinar e desenvolver novos talentos;

**Conhecimentos avançados em:**
- React
- Desenvolvimento Ágil
- Redux
- CSS/SASS
- REST
- TDD
- GIT
- Clean code
- GitFlow
- API

**Estar disposto a aprender:**
- Storybook
- GitFlow
- CodeReview
- Component Driven Design
- Docker
- Scrum
- CI/CD
- BDD
- Websockets
- NodeJS
- Saga
- React Native
- Talks, Meetups e Comunidade;
- Gestão, Empreendedorismo e Inovação

**Desejável:**
Inglês leitura/escrita; 
typescript;

**Extras:**
- 100% remoto
- Bolsa estadia para quem deseja se estabelecer na cidade de São Paulo (DevHouse);
- Bonificação trimestral por resultado;
- Bônus por novos talentos;
- Bônus por novos negócios;
- Projeto de carreira;
- Cursos gratuitos;

**Interessados enviar CV / Linkedin / Github / Portfólio e pretensão salarial para:
denis@ctowl.com.br**

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
