### ISSUE TITLE
[Remoto] Front-end Developer na Celcoin

### ISSUE THREAD

**Issue by MelissaCelcoin** [frontendbr/vagas#3745]
> Vaga Remota durante a pandemia

## Nossa empresa

Venha trabalhar em uma Startup, com uma equipe altamente colaborativa, um lugar sem burocracia e com muito espaço para inovação.
Somos uma empresa certificada pelo GPTW e reconhecida por ter um excelente ambiente para se trabalhar!

## Descrição da vaga

Buscamos um desenvolvedor front end para atuar no Celcoin na construção de produtos e ferramentas voltadas para a nossa rede de agentes espalhados por todo o Brasil. O profissional irá atuar em conjunto com o time de UX/UI e o time de desenvolvimento transformando protótipos em códigos precisos e rápidos para garantir a melhor experiência dos nossos agentes com o uso do nosso Site e Aplicativo. Aqui você irá trabalhar com Bootstrap, JavaScript, CSS, AngularJS, Android e Flutter (em migração). Essa é uma oportunidade única de trabalhar em uma Startup em crescimento acelerado, altamente inovadora e com um time altamente capacitado no uso de tecnologias e ferramentas para alcançar a satisfação do seu cliente.

## Local

Barueri-SP

## Requisitos

·         Formação em Ciência da computação, Engenharia ou sistema de informação.

·         Requisitos: HTML5, CSS3, jQuery, Bootstrap, JavaScript, Angular;

·         Bons conhecimentos em chamadas assíncronas para atualização parcial de páginas, como AJAX;

·         Construção de Interfaces Android nativo (Material Design);

·         Integração com APIs REST;

·         Conhecimento em metodologias ágeis (SCRUM)

·         Desejável: Conhecimento de construção de interfaces em Flutter e widget testing; Conhecimento em ferramentas de edição de imagens para realizar pequenos ajustes; desenvolver interfaces utilizando Clean Archtecture

·         Experiência em desenvolvimento front-end.

·         Bom relacionamento com o time;

·         Comunicação objetiva;

·         Criatividade para resolver problemas desafiadores;

·         Pensamento Crítico;

·          Pensamento Analítico;

·         Capacidade de tomar decisões;

·         Entendimento do negócio.

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ 22,00/dia
- Auxílio creche
- ...

## Contratação

CLT

## Como se candidatar

Por favor envie um email para melissa.souza@celcoin.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Júnior

**Comment by evertonProgramadorCriativo** [comment]
Olá meu nome é Everton Eduardo , trabalhei 2meses como programador junior remotamente  , estou precisando muito dessa oportunidade, meu Whatsapp é 5521968840782

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
