### ISSUE TITLE
[Remoto] Full Stack Developer @ alamoWEB

### ISSUE THREAD

**Issue by alamops** [frontendbr/vagas#3746]
## Nossa empresa

A alamoWEB é uma agência focada em tecnologia e projetos inovadores.
Estamos sempre buscando trabalhar com as tecnologias de ponta do mercado.

A alamoWEB é uma empresa 100% remota!

## Descrição da vaga

Buscamos um desenvolvedor Full Stack para atuar no desenvolvimento de novas funcionalidades e melhorias em diversos web apps, bem como no desenvolvimento de novos produtos da empresa.

## Local

100% Remoto

## Requisitos

**Obrigatórios:**
- Angular 6+
- NodeJS
- Conceitos de UX/UI e Responsividade
- TypeScript
- CSS
- GIT
- APIs / Rest

**Desejáveis:**
- ReactJS
- React Native
- Inglês Intermediário
- SASS
- GraphQL

**Diferenciais:**
- Noções de criptomoedas e blockchain
- Ter trabalhado no desenvolvimento de aplicativos móveis
- Flutter

## Benefícios

- 100% Remoto
- Horários flexíveis

## Contratação

- PJ
- Integral
- Remuneração: R$ 4.000,00 ~ R$ 6.000,00

## Como se candidatar

Por favor envie um email para jobs@alamoweb.com.br com seu CV anexado - enviar no assunto: Vaga Full Stack

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
