### ISSUE TITLE
[CURITIBA] Tech Lead - Gerente de Tecnologia @ Contabilizei

### ISSUE THREAD

**Issue by nataliaintera** [frontendbr/vagas#3748]
[OPORTUNIDADE] [CURITIBA - PARANÁ] TECH-LEAD - GERENTE DE TECNOLOGIA

A Contabilizei está crescendo rapidamente e construindo histórias de sucesso através de tecnologia, mudando a forma como o micro e pequeno empreendedor gerencia o seu negócio.

Se você quer apoiar os desenvolvedores nas entregas de soluções, definir o backlog técnico junto com o time, identificar problemas e garantir soluções, a Contabilizei é o seu lugar.

• Nível Sênior
• Java, domínio de Cloud, paradigmas e sistemas distribuídos
• Formato Remoto ou presencial (Curitiba)
• Modelo CLT

Uma oportunidade de construir o futuro e crescer com a Contabilizei!

Conheça mais sobre essa oportunidade: https://byintera.in/212

Lembrou de alguém? Marca essa pessoa aqui nos comentários que eu entro em contato!

#java #cloud #gcp #vaga #oportunidade #contabilizei #techlead #gerentedetecnologia

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
