### ISSUE TITLE
[Belo Horizonte] Front-end Developer na NuVidio

### ISSUE THREAD

**Issue by gustavo-a-m** [frontendbr/vagas#3750]
## Nossa empresa

Somos a primeira startup de videocommerce no Brasil.

Venha desenvolver soluções em videochamadas para vendas para grandes bancos e varejistas.

Vamos revolucionar o modo como as compras online são feitas, vem também!

## Descrição da vaga

- Aplicar e encorajar boas práticas de desenvolvimento;
- Desenvolver códigos simples, eficazes, escaláveis, legíveis e de fácil manutenção, utilizando as melhores práticas de desenvolvimento de software;
- Atuar em conjunto com o time, comprometendo-se com os objetivos do time e trabalhando em harmonia com todos; 
- Questionar e inovar buscando sempre as melhores alternativas alinhadas a necessidade da empresa.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência em projetar, construir e gerenciar soluções HTML, CSS e JavaScript;
- Conhecimentos sólidos de JavaScript e/ou TypeScript;
- Domínio de ao menos um framework como Angular, React ou semelhante;
- Conhecimento em versionamento utilizando Git.

**Desejáveis:**
- Experiência com ReactJS ou/e React Native;
- Conhecimento de UI e noções de UX.

## Benefícios

- VR de R$ 25/dia

## Contratação

PJ ou CLT a combinar

## Como se candidatar

Por favor envie um email para gustavo@nuvidio.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: gustavo@nuvidio.com.br

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Júnior

**Comment by IggorSantos** [comment]
É remoto mesmo? Porque no titulo está Belo Horizonte.
