### ISSUE TITLE
[São Paulo] Front-end Developer SR na Air Liquid Brasil

### ISSUE THREAD

**Issue by Nathalialiveira** [frontendbr/vagas#3754]
> Vaga Remota durante a pandemia

## Nossa empresa

A empresa fornece soluções inovadoras em gases e tecnologias aos clientes, aumentando a performance e auxiliando na redução do impacto ambiental. Provemos essas soluções inovadoras a uma variedade de clientes em cada etapa da produção, incluindo gases industriais e especiais, soluções de energia, aplicação de tecnologias e serviços. Não importa onde, asseguramos que as nossas soluções são seguras, confiáveis, eficientes e sustentáveis.

## Descrição da vaga

Criará produtos (softwares web e mobile) internos para uso nacional e internacional podendo impactar a vida de milhares de pessoas;
Irá contribuir ativamente para a cultura do time com tendências de mercado e novas metodologias;
Participará na concepção e solução de problemas técnicos em projetos novos e o projetos legados.

## Local

 [São Paulo]

## Requisitos

**Obrigatórios:**
Experiência no desenvolvimento front-end nas linguagens React e React Native;
Experiência com TypeScrip, ECMAScript, Git, consumo de CLIs;
Experiência com métodos ágeis (Scrum, Lean, Kanban) e cultura de Clean Code;
Conhecimento de testes de código (unidade e integração) e com Component-Driven Development.

**Diferenciais:**
Experiência com cultura DevOps (Pipelines, CI, CD, Monitoramento); 
Cultura de otimização de performance; 
Disponibilidade para deslocamento e viagens para realização de entrevistas com usuários, testes e pesquisas de campo; 
Gostar de sair da zona de conforto; 
Conhecimento em outras linguagens de programação; 
Conhecimento com UI & UX; 

**Diferenciais:**
Ajuda de Custo
Bônus atrelado ao resultado

## Contratação

PJ 

## Como se candidatar

Por favor envie um email para nathalia.oliveira@integritygroup.com.br com seu CV anexado - enviar no assunto: Front-end SR

#### Alocação
-Hibrido

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
