### ISSUE TITLE
[REMOTO] Front-end Developer na Fandone

### ISSUE THREAD

**Issue by geekrootbr** [frontendbr/vagas#3755]
#3264  Nossa empresa

Somos uma holding com diversas startups de tecnologia, em fase de seed ou growth. Procuramos pessoas que curtem desafios, querem crescer junto com a empresa e buscam oportunidades futuras de participação. Nossa startup é focada na construção de comunidades online, fornecendo para professores, infoprodutores uma plataforma de gestão de conteúdo inteligente, dinâmica e com recursos que engajam seus alunos.

## Descrição da vaga

Você estará trabalhando diretamente com o time de founders no desenvolvimento do front-end da nossa plataforma, para web e mobile. Procuramos pessoas com vontade de aprender, que desejem crescimento na carreira, que busquem uma visão de longo prazo na nossa empresa. 

## Local

REMOTO

## Requisitos

**Obrigatórios:**
Forte experiência com HTML5, CSS3 
Proficiência em Javascript e Typescript;
Experiência em React;
Experiência em Vue.JS
Experiência com ferramentas de versionamento (GitHub);

**Desejáveis:**
- conhecimento em LESS/SASS
- conhecimentos em MySQL
- conhecimentos em PHP/Laravel

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para rh@triadps.com com seu CV anexado - enviar no assunto: Vaga Front End

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
