### ISSUE TITLE
[Remoto] Senior React Developer at ARK Ecosystem

### ISSUE THREAD

**Issue by luciorubeens** [frontendbr/vagas#3756]
## Nossa empresa

A Ark Ecosystem é uma empresa com sede na França, que visa criar um ecossistema de blockchains conectadas fornecendo ferramentas open-source e fáceis de utilizar para publicar sua própria blockchain.

Website: [ark.io](https://ark.io)
Github: [/ArkEcosystem](https://github.com/ArkEcosystem)

### Diferenciais

- Horário flexível
- Salário competitivo
- Trabalhar com novas tecnologias
- Contribuir com projetos open source

## Descrição da vaga

Estamos expandindo nossos projetos e procuramos por desenvolvedores **Senior React**.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com React
- Experiência com TypeScript
- Inglês avançado (leitura e escrita)

**Desejáveis:**
- React Native
- TailwindCSS
- Electron.js

**Diferenciais:**
- Conhecimentos em criptografia/criptomoedas, P2P e tecnologias decentralizadas.

## Contratação

- 40h / semana
- Salário baseado em Euro com pagamentos em Bitcoin
- R$20k+ (baseado na experiência)

## Como se candidatar

Preencha o formulário em: https://ark.io/careers/senior-react-developer

## Labels

- Remoto
- Sênior
- Exterior

**Comment by myrgato** [comment]
Show, mandei lá @luciorubeens

**Comment by jonyw4** [comment]
Ainda está aberta?

**Comment by luciorubeens** [comment]
@jonyw4 Sim!

**Comment by rodrigo-fonseca** [comment]
Oi Lucio,

 Eu preenchi o formulário e não recebi nem resposta, e olha que eu acredito
que tenho perfil para essa vaga

Em qua., 25 de nov. de 2020 às 17:46, Lúcio Rubens <notifications@github.com>
escreveu:

**Comment by rodrigo-fonseca** [comment]
Enviei novamente, não custa tentar

Em qua., 25 de nov. de 2020 às 17:47, Rodrigo Fonseca <
ro.fonseca.melo@gmail.com> escreveu:

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
