### ISSUE TITLE
[Remoto] Software Engineer Senior Frontend @ Jusbrasil

### ISSUE THREAD

**Issue by cristianossd** [frontendbr/vagas#3759]
## Nossa empresa

Faça parte da maior plataforma jurídica do mundo e ajude-nos a diminuir o Justice GAP existente no Brasil, que é a distância entre ter um direito e fazê-lo prevalecer.

O Jusbrasil existe para conectar pessoas à justiça através de advogados e informação jurídica acessíveis a todos. Hoje temos o privilégio de observar de perto a interação de milhões de jusbrasileiros e sabemos como as pessoas querem e precisam de uma forma fácil e eficiente de "fazer valer a justiça".

Se quiser saber mais sobre o Jusbrasil e sua cultura única de trabalho você pode clicar [aqui](https://sobre.jusbrasil.com.br/) e/ou dar uma espiadinha dentro da nossa empresa neste [link](https://danielmurta.jusbrasil.com.br/artigos/383937197/o-o-uma-espiadinha-dentro-do-jusbrasil)!

## Descrição da vaga

Ao contrário do que muitos pensam, somos uma empresa de tecnologia, reunindo engenheiros e pessoas com background jurídico.

Estamos à procura de engenheiros de software de excelência, não necessariamente desenvolvedores experientes, mas aqueles que são talentosos, criativos, que primam pela qualidade dos códigos e, acima de tudo, queiram aprender e se aperfeiçoar.

Você, enquanto Frontend Senior, será uma das lideranças do nosso time que é responsável por construir e manter projetos em sua maioria usando React, Relay e GraphQL, além de outras tecnologias atualmente utilizadas.

## Local

Remoto

## Requisitos

**Obrigatórios:**

- Tem pelo menos 6 anos de experiência em software;
- É experiente em desenvolvimento React e seu ecossistema: React/Hooks/Relay/GraphQL/Testes (jest/react-testing-library);
- Não tem problemas em ler conteúdo em inglês e tem compreensão auditiva (fluente é um diferencial);
- Sempre está na borda do conhecimento, é uma pessoa curiosa e não tem problemas em experimentar tecnologias novas;
- Fica desconfortável com códigos sem testes;
- Tem conhecimento avançado de Javascript;
- Utiliza Git para controle de versão;
- Sente-se confortável em realizar tarefas que envolvam Backend e Infra;

**Diferenciais:**

- É envolvido com a comunidade de tecnologia e open-source;
- Tem experiência com liderança de equipes de desenvolvimento;
- Tem experiência com Webpack/Lerna;
- É também Fullstack e consegue desenvolver features no backend;
- Tem experiência com Typescript/Scala/Python;

## Benefícios

- Plano de saúde
- Plano dentário
- Vale Refeição
- Vale Transporte
- Auxílio creche
- Gympass

## Contratação

CLT

## Como se candidatar

Por favor, submeter via [Lever](https://jobs.lever.co/jusbrasil/39a26d2f-306a-4e05-b57d-c9e2dcb70946)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: cris@jusbrasil.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível

- Sênior

**Comment by vinculuzX** [comment]
Aceitam PJ?

**Comment by cristianossd** [comment]
Infelizmente n, @vinculuzX

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
