### ISSUE TITLE
[São Paulo] Software Developer Front-End na @ ECTP (BTG Pactual? 

### ISSUE THREAD

**Issue by Lucasquintanilha** [frontendbr/vagas#3761]
[VAGA] Desenvolvedor de Software Front-end Sênior na ECTP (BTG Pactual)

A ECTP é uma empresa com presença Global no comércio commodities, foi fundada em 2013 pelo Grupo BTG Pactual, possuindo uma forte estrutura de risco além de ampla experiência de traders em todos os segmentos do mercado .... Neste momento está precisando de um Software Desenvolvedor Front-end (Senior) para compor seu tempo, projetando e aprimorando os métodos de integração dos sistemas da empresa e automatizando processos e funções para melhorar uma operação.

Local: São Paulo
Requisitos principais: Inglês avançado
- 3 anos de experiência
- NET, C #, JavaScript, JSON, Angular, React, DevExpress.
- .NET Core, .NET Framework, Rest API, Web API e Entity Framework.
-Docker e Kubernetes.
Contratação: CLT
Faixa SALARIAL: A combinar + benefícios.

Mais informações sobre a vaga e Link de Inscrição:

https://vagas.byintera.com/ectp/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
