### ISSUE TITLE
Front-end Developer Intern na CodeLeap

### ISSUE THREAD

**Issue by youmorthor** [frontendbr/vagas#3762]
**Descrição da vaga**

👔 Vaga: Desenvolvedor Intern Front-End 
⚙️ Experiência procurada: React & React-Native
💼 Empresa: CodeLeap UK
📍 Localização: Onde quiser (remoto)
🌎 Idioma necessário: Inglês básico
💵 Remuneração: R$2.000 a R$3.000 por mês 
👉 Empresa: https://codeleap.co.uk/#top
✉️ Preencher o formulário:  https://forms.gle/w3F6RWwCu3pqKCn87

**Introdução**
Olá! Tudo bem? Somos uma agencia de desenvolvimento de software em Londres.

Estamos procurando alguém para a posição de Intern que além de preencher requerimentos da vaga, esteja interessado na ideia de se juntar à uma empresa relativamente jovem para atuar em várias áreas, ajudar na construção da organização, e assumir bastante responsabilidades.

O candidato ideal é alguém jovem que curte tecnologia, websites e aplicativos e é apaixonado por engenharia de software, usabilidade de UI/UX e minimalismo. 

Teve bastante gente com dúvida sobre Inglês - com relação ao idioma, é importante conseguir se comunicar no básico e saber ler e escrever o código, conteúdo e comentários in English, mas não se preocupe se não estiver 100% confiante pra conversar - não tem necessidade.

O foco da CodeLeap é o design e desenvolvimento de produtos digitais, websites e aplicativos para iOS e Android sob demanda. Cada projeto exige um approach diferente e traz novos desafios. Sempre temos algo diferente pra fazer! No médio e longo prazo temos interesse em desenvolver nossos próprios produtos, então se você gosta da ideia de experimentar internamente e criar coisas novas, você encontrou o lugar certo!

**Local**

Remoto - Central em Londres, Reino Unido

Benefícios

💵 Remuneração: R$2.000 a R$3.000 por mês

**Diferenciais**

Sem horário ou local de trabalho, o que importa é fazer acontecer!
Equipe flexível, espaço para crescimento na empresa
Gostamos bastante da engenharia em si, e tentamos manter tudo organizado :)

Requisitos

**Obrigatórios:**
1 ano com desenvolvimento web com JS/HTML ou outras frameworks
Alguma experiência com React-Native

**Desejáveis:**
Interesse em design
Conhecimentos backend em Python & Django ou Node
Experiência com AWS, GCP, Firebase, Sentry
Experiência com deployment e gerenciamento remoto de servidores
Experiência com apps nativos iOS & Android e gerenciamento de apps na Apple e Google stores
Contratação

PJ a combinar, somos flexíveis
Início nas próximas semanas

👉 **Interessado?** Veja: https://codeleap.co.uk/ & https://forms.gle/w3F6RWwCu3pqKCn87

**Comment by Marilzon** [comment]
> Enviei uma aplicação para estágio, espero ansiosamente e sigo estudando

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
