### ISSUE TITLE
[São Paulo] Front-end Developer na [Skymail LTDA]

### ISSUE THREAD

**Issue by lucasmarin** [frontendbr/vagas#3764]
> Vaga Remota durante a pandemia

## Nossa empresa

A Skymail é uma empresa de cloud computing com 6 anos de mercado. Possui um corpo diretivo jovem e aberto a ideias, foi fundada por gente interessada em fazer diferente e o melhor. Trabalhamos principalmente com soluções em cloud computing e e-mail corporativo. Possuímos hoje uma solução robusta de e-mail corporativo com colaboração (skybox, skymi) utilizada por mais de 400 mil usuários pelo Brasil, nossa ferramenta de virtualização de máquinas virtuais que é integrada ao mesmo painel de controle que gerencia os e-mails corporativos. Possuímos também soluções de Disparo de E-mail em massa e Backup inteligente de servidores.

Nossas soluções estão em constante evolução e o ambiente é desafiador todo dia, estamos sempre focados em trazer a melhor solução para os nossos clientes e também o melhor atendimento, esses são um dos nossos grandes diferenciais.

Estamos em franca expansão, com crescimento sólido e constante mês a mês em 2020.

## Descrição da vaga

- Desenvolver novas features e interfaces
- Integrar a aplicação front-end com o back-end
- Validar a performance da aplicação
- Ser responsável pela qualidade do código do front-end

Requisitos

- experiência e domínio de Vue.js
- noções avançadas de HTML5, CSS3 e JS, com capacidade para desenvolver projetos de forma responsiva
- foco na otimização e performance da solução desenvolvida: minificação, code splitting, otimização de imagens e etc.
- ser criterioso, detalhista e atento com o layout a ser implementado, respeitando dimensões, posicionamento, cores e demais
- comportamentos — foco na qualidade
- familiaridade com integração de APIs diversas

Habilidades Obrigatórias
- JavaScript
- Vue.js

Habilidades Desejáveis
- Flutter
- Git
- PHP

## Local

Exemplo: Escritório (remoto 100% durante a pandemia, estamos avaliando remoto parcial de 3 à 4x por semana) , [SP], [São Paulo], [Pinheiros]

## Benefícios

- 1 mês de folga remunerada

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para lucas.marin@skymail.com.br com seu CV anexado com sua pretensão salarial - enviar no assunto: Vaga Frontend

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Remoto parcial

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
