### ISSUE TITLE
[REMOTO] Full-Stack Developer na TeclaT

### ISSUE THREAD

**Issue by teclat** [frontendbr/vagas#3766]
Descrição da vaga

Buscamos novos desenvolvedores para compor o time tecnológico. 
As vagas serão para React Native, ReactJS e NodeJS e experiência em ambas tecnologias é fundamental!

As principais atividades serão:

Desenvolvimento de novas interfaces web em ReactJS;
Desenvolvimento de aplicativos híbridos em React Native;
Desenvolvimento de APIs
Desenvolvimento e execução de testes.

Local
100% Remoto
Horário comercial

Carga Horária
40 horas semanais

Benefícios 
Vale alimentação
Ajuda de custo para certificações.  

Requisitos
Obrigatórios:

Domínio em ReactJS e React Native
Domínio em React State Management (Redux)
Domínio em NodeJs na criação RESTFul APIs 
Integração de RESTFul APIs 
Boas noções de layout
Ótima comunicação verbal e escrita
Sólidos conhecimentos em criação e execução de teste em ReactJS e React Native 

Desejáveis:
Conhecimento em gestão de projetos ágeis
Conhecimento na biblioteca Expo

Diferenciais:
Experiência em utilização do Figma
Conhecimento em Python (Django)

Contratação
PJ a combinar

Como se candidatar
Por favor envie um email para vagas@teclat.com.br com seu CV anexado - enviar no assunto: Vaga Dev

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
