### ISSUE TITLE
[Rio de Janeiro] Estágio em Front-end Developer na Fattoria

### ISSUE THREAD

**Issue by CarolPimentel** [frontendbr/vagas#3771]
> **Vaga Remota durante a pandemia**

A Nossa empresa possui sólido conhecimento do mercado digital. Atuamos no desenvolvimento de sistemas e aplicativos mobile, na criação da marca, planejamento de campanha de marketing digital e outsourcing.

## Descrição da vaga

Participação nos projetos front-end, auxiliando no desenvolvimento e otimizacao de interfaces, estruturação e observação do fluxo de navegação. 
Interação com bibliotecas e frameworks de front-end e com a equipe de back-end.

## Local
 Remoto enquanto durar a pandemia ou no Escritório, [Rio de Janeiro], [Rio de Janeiro], [Centro]

## Requisitos

**Obrigatórios.**
Conhecimentos em HTML, Javascript (básico), CSS, SASS e Git.

**Desejáveis:**
- Javascript (nível avançado)

**Diferenciais:**
-Conhecimentos em Adobe XD, Node JS, Angular, React e Vue.

## Benefícios

- Seguro de vida
- VR de R$ 26,10/dia
- Vale Transporte a partir da retomada do trabalho presencial.

## Contratação
Contrato via CIEE
Bolsa auxílio a combinar

## Como se candidatar

Por favor envie um email para rh@fattoriaweb.com.br com a pretensão de bolsa e o seu CV anexado - enviar no assunto: Vaga Efront RJ

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver respostas, recursos3008@gmail.com

#### Alocação
- Remoto enquanto durar a pandemia.
   É necessário residir no Rio de Janeiro.

#### Regime
- Estágio

#### Nível
Estágio 

Boa sorte!

**Comment by igorpinhh** [comment]
tem que estar cursando ou pode ser pj? eu estou com o curso trancado

**Comment by CarolPimentel** [comment]
Nos envie o seu currículo Igor e os links do que consegue realizar em front.


Att.


Em qua, 4 de nov de 2020 14:48, Igor Pinheiro <notifications@github.com>
escreveu:

**Comment by IggorSantos** [comment]
Existe a possibilidade de continuar remoto quando acabar a pandemia?

**Comment by krivax** [comment]
essa vaga é para estágio mesmo? parece um júnior disfarçado. se for júnior posso até colocar o curriculo.

**Comment by CarolPimentel** [comment]
Olá Krivax, boa tarde! Tudo bem?

A vaga é para estágio, e como tal não exigimos experiência. Porém, é
necessário o conhecimento das linguagens,  ferramentas que estão descritas
como (requisitos)... para que seja possível a atuação nos projetos.
É importante observar o que se pede no requisito (obrigatório). Já os
conhecimentos descritos como desejáveis ou diferenciais, não são
obrigatórios.

Ficamos à disposição em caso de outras dúvidas!

Boa semana!
Att.

Em qua., 4 de nov. de 2020 às 15:40, Krivax Jr <notifications@github.com>
escreveu:

**Comment by CarolPimentel** [comment]
Olá Igor,

Como a descrição da vaga, será remoto até que cesse a pandemia.
Qual a sua cidade?

Att.

Em qua., 4 de nov. de 2020 às 15:22, Igor Santos <notifications@github.com>
escreveu:

**Comment by SantosMaycon** [comment]
Currículo enviado!

**Comment by evertonProgramadorCriativo** [comment]
Sou  do Rio de Janeiro,  trabalhei 2meses como junior  Remoto  , meu Whatsapp 5521968840782,  estou precisando muito dessa oportunidade

**Comment by CarolPimentel** [comment]
Olá Everton, boa noite!

Envie o seu currículo para rh@fattoriaweb.com.br

Espero que tenha um ano bom e com saúde!

Att.


Em dom, 3 de jan de 2021 21:13, everton eduardo E2 <notifications@github.com>
escreveu:

**Comment by asvpxcelo** [comment]
Boa noite, a vaga ainda está disponível?

**Comment by freiiirer** [comment]
é possivel essa vaga ser somente remota ?

**Comment by macedojeh** [comment]
A vaga ainda está disponível? :)

**Comment by devlobao84** [comment]
Olá tudo bem? Estou estudando FullStack na Instituição Digital House (formação junior), com conclusão previsto para junho/julho, e gostaria de saber se a vaga estágio (remoto durante a pandemia) é também oferecida para candidatos de outra cidade (no caso sou de São Paulo - Capital), sabendo que ainda não tenho experiência prática  nem mesmo algum projeto já feito mas tenho muita vontade de aprender e crescer dentro da área front-end pra quem está começando agora e quanto seria a remuneração. Agradeço a atenção se puder me responder. 


Att,  

Jonas

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
