### ISSUE TITLE
[Belo Horizonte] Front-end Developer @ SYDLE

### ISSUE THREAD

**Issue by SYDLE-talentos** [frontendbr/vagas#3772]
## Nossa empresa

Somos uma empresa de produtos de tecnologia corporativa. Temos mais de 15 anos de história e estamos só no começo! Vivemos um forte crescimento no mercado nacional e internacional, sem perder a nossa essência que é conciliar desafios técnicos com um clima leve e colaborativo. Atualmente somos reconhecidos como a melhor empresa de TI para trabalhar do país e, há mais de 10 anos, estamos entre as melhores empresas do Brasil e da América Latina. Ficamos muito felizes com tanto reconhecimento, o que nos motiva a fazermos ainda mais.

## Descrição da vaga

- Desenvolver sistemas e aplicações, a partir das solicitações recebidas;

- Otimizar as interfaces para melhorar a performance e garantir a boa usabilidade;

- Definir e aplicar boas práticas de desenvolvimento, planejando com a equipe a organização do código front end;

- Realizar as manutenções necessárias e monitorar o desempenho e performance dos sistemas e aplicações desenvolvidas;

- Dar suporte no que tange a viabilidade técnica de desenvolvimento de novas features e interfaces.

## Local

Minas Gerais, Belo Horizonte, Savassi.

## Requisitos

- Formação em Ciência da Computação, Sistemas de Informação, Engenharias ou afins;

- Experiência com front-end, incluindo CSS e HTML;

- Conhecimento em JavaScript;

- Experiência com frameworks JS (React, React Native, Angular).

## Benefícios

Cada colaborador tem uma necessidade única. Há quem tenha família grande e queira todo mundo no plano de saúde ou quem já tenha o plano junto com sua família. Também temos aqueles que utilizam transporte público ou que tenham carro e valorizem uma vaga no estacionamento. Há quem prefira comer em restaurantes e quem prefira fazer supermercado para preparar aquela comidinha em casa... Enfim, por que impor benefícios engessados para todos, se as pessoas têm necessidades diferentes? Essa é a SYDLE, uma empresa humana, flexível, preocupada com as necessidades individuais dos seus colaboradores.

Algumas das nossas opções:

- Nosso plano de saúde e Odontológico em BH é a Unimed e oferecemos uma série de opções dessa operadora e você poderá incluir seu cônjuge e filhos;

- Temos o vale alimentação ou refeição, você escolhe, com um valor acima da média da nossa região. Ah, e esse benefício não é suspendido nas férias, pra você continuar se alimentando bem;

- Vale transporte ou a possibilidade de vaga para carro ou moto no prédio da empresa;

- Você também poderá usar parte do valor do seu pacote de benefícios para fazer aquilo que tiver interesse e for mais conveniente para você, como: academia, algum programa cultural, como ir ao cinema, gasolina, etc.

**Diferenciais:**

- Auxílio à cursos e certificações técnicas;

- 40 horas semanais (nada de 44 horas) e o horário é flexível;

- Seguro de Vida;

- Ausência de dress code;

- Convênios com restaurantes;

- Bonificação para indicação de amigos às vagas da SYDLE;

- Política de PR diferenciada;

- Sala de descompressão, com área gourmet, além de um grande espaço aberto pra você relaxar ou trabalhar em um ambiente diferente;

- Lanches liberados, como frutas, misto quente e outros;

- Além claro, de um clima sem igual, amigável e colaborativo como deve ser na empresa que é considerada a melhor de TI do país!

## Contratação

CLT

## Como se candidatar

Acesse: http://bit.ly/front-end-sydle

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
