### ISSUE TITLE
[Curitiba] Front-end Developer | Remoto

### ISSUE THREAD

**Issue by AlexdeOliveiraSilva** [frontendbr/vagas#3773]
A oportunidade é para participar de um time com o desafio de continuar evoluindo um aplicativo/plataforma utilizado por cerca de 50 mil usuários. 

Descrição do cargo:
- Executar melhoria contínua no produto para atender ou exceder as especificações de disponibilidade, qualidade e experiência do usuário do produto;
- Implementação e manutenção de site em Wordpress
- Criação de temas para Wordpress
- Implementação de sistemas em React e integração com APIs
- Implementação de Landing pages e sites diversos
- Manutenção de sites e otimização para SEO

Competências desejadas:
- Autodidata e ser curioso, buscando sempre novas tecnologias e ideias, aprendendo rapidamente.
- Hands on foco em entrega e resolução de problemas, atrelado a alta capacidade técnica.
- Comunicação e trabalho em equipe

Desejável:
- Ensino superior completo
- Conhecimento em linux

Diferencial:
- Conhecimento em back-end
- Conhecimento em AWS
- Conhecimento em react-native 

Nível de experiência
- Junior/Pleno

Tipo de contratação:
PJ

Carga horária:
40 horas semanais

Empresa localizada em Curitiba - PR

Para se candidatar a vaga utilizar o formulário abaixo:
https://forms.gle/PP6jqeBZvBtBzUum9

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
