### ISSUE TITLE
[ REMOTO ] - Full Stack Javascript Developer na Adsoft

### ISSUE THREAD

**Issue by rodrigo-oliveira-1** [frontendbr/vagas#3774]
### **Descrição do cargo**

Você irá trabalhar com uma equipe multidisciplinar e fará parte de um grande desafio de transformação tecnológica, o objetivo é migrar uma base de 2.000 clientes que utilizam uma aplicação desktop para um ambiente web, integrado, prático e rápido.

As tecnologias do ambiente web mudam muito rápido, daí a importância do dinamismo e proatividade, desde o início.

O seu trabalho será desenvolver recursos e módulos empresariais de gestão em React e backend em NodeJS com ExpressJS.

Topa participar deste desafio? Então junte-se a nós, código e café não irão faltar.

### **Descrição da vaga**
- 5 vagas para Full Stack Javascript Developer [PLENO ou SÊNIOR] em aberto para integrar ao nosso time.

- Implementação de software com foco em empresas que atendem ao varejo.

### **Local**
- REMOTO

### **Tipo de contratação ( A escolha do candidato )**
- PJ
- CLT

### **Requisitos obrigatórios**

- Comprometimento e ótima comunicação
- Javascript
- NodeJs
- ES6
- ReactJS

**Desejável experiência ou conhecimento em:**

- Microsoft SQL Server
- GIT
- APIs REST

**Diferenciais:**

- Conhecimento em software para varejo
- ExpressJS
- Sequelize
- Experiência com nuvem Azure
- Testes Unitários

### **A Empresa**

Trabalhamos desenvolvendo Solução em Software de Gestão Empresarial voltado para o varejo há mais de 25 anos.

Site da empresa para você conhecer um pouco mais sobre o que fazemos, nossos objetivos e informações para entrar em contato, caso tenha alguma dúvida relacionada a empresa www.adsoft.com.br

A sede da empresa esta localizada em Teixeira de Freitas no sul da Bahia.

### **Como se candidatar**
Por favor envie um Email para **rodrigo@adsoft.com.br** com seu CV anexado, informe no assunto: Vaga Full Stack JS Developer.

Você também pode entrar em contato pelo **Telegram @rodrigo_oliveira**.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by rodrigo-oliveira-1** [comment]
Vagas em aberto, temos 5 vagas disponiveis.
