### ISSUE TITLE
[SALVADOR-BA] Mobile Developer (React Native) na Bloxs Investimentos

### ISSUE THREAD

**Issue by lucasayres** [frontendbr/vagas#3775]
## Nossa empresa

A Bloxs Investimentos é uma startup da área financeira (Fintech) e nossa missão é conectar Investidores que buscam rentabilidade e diversificação com Empreendedores que buscam acesso ao Mercado de Capitais. Tudo isso 100% online e com a segurança de um mercado regulado e autorizado pela CVM.
Saiba mais em: https://bloxs.com.br

## Descrição da vaga

Buscamos um(a) desenvolvedor(a) React Native de nível Pleno ou Sênior para atuar no desenvolvimento do nosso aplicativo de investimentos, criando funcionalidades que vão gerar muito valor para nossos usuários! Além disso, você será responsável por todo o processo de desenvolvimento, desde a discussão de tasks até os testes e a entrega de novas soluções.

## Local

Salvador - BA
Remoto

## Requisitos

**Obrigatórios:**
- Sólidos conhecimentos em programação mobile e react-native;
- Sólidos conhecimentos de integração de APIs REST;
- Conhecimentos em Redux;
- Publicações em Lojas;
- Boas noções de layout;
- GIT;
- Conhecimento em metodologia ágil (SCRUM, OKRs, Daily..);

**Desejáveis:**
- Familiaridade com testes automatizados;
- Familiaridade com metodologia ágil;

**Diferenciais:**
- Conhecimento em TypeScript;
- Docker;

## Contratação

CLT - Faixa salarial: R$ 2.500,00 a R$ 5.000,00

## Benefícios

- Tecnologias de ponta
- Vale Transporte
- Auxílio Alimentação
- Flexibilidade de horário
- Ambiente de Startup

## Como se candidatar

Envie seu currículo e portfólio para o e-mail lucas@bloxs.com.br - enviar no assunto: Vaga React Native

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
