### ISSUE TITLE
[100% Remoto] Front-end Developer na Celcoin

### ISSUE THREAD

**Issue by MelissaCelcoin** [frontendbr/vagas#3777]
#### Alocação

- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by rdrsantos** [comment]
Como posso enviar meu cv para me candidatar?

**Comment by deeborges** [comment]
@MelissaCelcoin , poderia passar uma descrição mais detalhada sobre a vaga?

**Comment by zumbizar** [comment]
> @MelissaCelcoin , poderia passar uma descrição mais detalhada sobre a vaga?

espernado a resposta também..

**Comment by victorhsantiago** [comment]
@felipefialho vaga fora dos padrões

**Comment by MelissaCelcoin** [comment]
> @MelissaCelcoin , poderia passar uma descrição mais detalhada sobre a vaga?

Olá, boa tarde! https://jobs.kenoby.com/celcoin/job/desenvolvedor-front-end/5f7e284e66794d1ea9132c95 aqui temos mais informações sobre a vaga!

Se tiver interesse, pode se candidatar pelo link, ou me mandar um e-mail (melissa.souza@celcoin.com.br) para conversarmos sobre mais detalhes.

**Comment by MelissaCelcoin** [comment]
> > @MelissaCelcoin , poderia passar uma descrição mais detalhada sobre a vaga?
> 
> espernado a resposta também..

Olá! 

Aqui temos mais detalhes sobre a posição: 
https://jobs.kenoby.com/celcoin/job/desenvolvedor-front-end/5f7e284e66794d1ea9132c95 

Também pode me enviar um e-mail, para conversamos mais detalhes: melissa.souza@celcoin.com.br

**Comment by FilipeAugustoVO** [comment]
Só avisando que o link do e-mail na postagem está incompleto, quando enviei
meu currículo não pode mandar.

**Comment by MelissaCelcoin** [comment]
Olá, Felipe! O e-mail está correto. É melissa.souza@celcoin.com.br
