### ISSUE TITLE
[Remoto e presencial] Front-end Developer Pleno e Sênior na ITeam

### ISSUE THREAD

**Issue by VivianeRHTI** [frontendbr/vagas#3778]
## Descrição da vaga

Desenvolvimento de aplicações WEB usando Angular Material.

## Local

Local de trabalho: Inicialmente remoto devido a pandemia, mas depois será presencial no cliente na região da Zona Sul de SP.

## Requisitos

Experiência de desenvolvimento de aplicações, integrando com .net core
Lógica de programação.
Conceitos e modelagem para banco de Dados Oracle e SQL.
Web Frameworks Javascript (JQuery, Bootstrap, Angular Material)
Conceitos e Orientação para testes (Unitários, Automatizados)

## Contratação

6 meses

## Nossa empresa

Há mais de 15 anos presente no mercado, a ITeam oferece o comprometimento com o cliente.
Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 
O relacionamento da ITeam é baseado no amplo comprometimento com os valores e objetivos dos nossos Clientes, fornecendo soluções e serviços de TI que contribuam para a realização de seus objetivos.

## Como se candidatar

Envie um e-mail para viviane.pereira@iteam.inf.br com seu currículo atualizado e pretensão de taxa/hora - enviar no assunto: Vaga no GITHUB - Front Angular Material.

## Labels

- 🏢 Horário comercial
- 🏢 Remoto 
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by VivianeRHTI** [comment]
Encerrada pelo cliente.
