### ISSUE TITLE
INVÁLIDO - Não informado nome da empresa

### ISSUE THREAD

**Issue by recrutamentobdr** [frontendbr/vagas#378]
A BDR – Talentos Corporativos procura profissionais para a vaga:
 
DESENVOLVEDOR FRONT END SÊNIOR – FLORIANÓPOLIS – 01 Vaga
 
## Requisitos:
Superior cursando ou completo em Análise de Sistemas, Sistemas de Informação, Ciência da Computação ou afins;
Experiência como desenvolvedor frontend;
Experiência com HMTL 5, CSS 3 e Javascript;
Experiência com frameworks Javascript (Ember, Angular, Backbone, React);
Vivência em desenvolvimento mobile nativo (iOS ou Android) e bibliotecas como Ionic, Cordova / PhoneGap e Bootstrap;
Conhecimento em lógica de programação;
Conhecimento em pré-processadores de CSS (Less, Sass);
Conhecimento em PHP e Rest;
Conhecimento em GIT;
Conhecimento em CMS Wordpress (Temas);
Conhecimento em Photoshop / Illustrator (recorte e aplicação dos layouts produzidos).

## Desejável: 
NPM, Gulp e Nativescript;
SEO;
Usabilidade;
Conhecimento em testes unitários (Karma, Jasmine e Protractor).
 
## Atividades:
Desenvolver interfaces para web;
Realizar frontend;
Apoiar na construção da arquitetura da informação dos projetos;
Auxiliar na produção de recursos multimídias.
 
## Salário: R$ 5.396,06 - CLT.
Horário: Segunda a Sexta - Horário Comercial - 40h semanais.
Benefícios: VA ou VR (R$ 528,00/mês) + Plano de Saúde Unimed Completo + Auxílio Creche + VT (Passe) + Convênio Odontológico + Convênio SESC + Convênio Farmácia + Auxílio Educação. A empresa ainda conta com uma área de lazer, com sinuca, games, minuto da fruta às 10h e 15h, além de outras atividades ao longo do ano.
Local: Santo Antônio de Lisboa/SC 401 - Florianópolis.
 
## Interessados devem cadastrar seu currículo em www.empresabdr.com.br, e candidatar-se no link da vaga Desenvolvedor Front End Sênior - Florianópolis.

**Comment by diogomoretti** [comment]
@recrutamentobdr a vaga é para trabalhar na própria BDR?
