### ISSUE TITLE
[São Paulo] Front-end Developer na Afya Educacional

### ISSUE THREAD

**Issue by Glelcia** [frontendbr/vagas#3783]
[São Paulo] Front-end Developer na Afya Educacional

## Afya Educacional

A Afya Educacional nasce em 2019 com o objetivo de ser a grande parceira dos profissionais médicos em toda a sua jornada de formação. Mas a nossa história já tem mais de 20 anos, especialmente nos cursos de saúde e Medicina.

Por meio de nossas unidades de ensino, atuamos desde a graduação - são mais de 30 cursos diferentes, além da Medicina -, passando pelos cursos para provas de residência e outros títulos até a pós-graduação médica.

Possuimos mais de 2 mil professores e 35 mil alunos.

Na graduação estamos em cinco estados, com 13 Instituições de Ensino Superior, sendo três delas reconhecidas como Centros Universitários pelo Ministério da Educação (MEC).

## Descrição da vaga

Mobile Android Pleno

## Local

Remoto 

## Requisitos

**Obrigatórios:**
- Conceitos de design, usabilidade e Experiência do Usuário
- Conhecimentos em Kotlin, API Rest, Android Architecture Components, Git, Code Review, Bash e Otimização de Desempenho
- Comunicativo, Dinâmico, Flexível, Administrar Tempo, Gerenciar Prioridades, Pró Ativo, Habilidade para Ensinar
- Desenvolvimento de plataformas mobile e tablet
- Desenvolvimento utilizando métodos ágeis

**Desejáveis:**
- Desejável curso nas áreas de Engenharia de Software, Análise e Desenvolvimento de Sistemas, Sistemas de Informação, Ciências da computação ou áreas correlatas

**Diferenciais:**
- Conhecimento em desenvolvimento híbrido iOS, Android e React Native

## Benefícios

-Gympass
- Plano Odontológico Bradesco
- Plano de Saúde Notre Dame
 -Vale Alimentação
 - Vale Refeição
- Seguro de Vida
- Vale Transporte
- Home Office
- PLR (1 salário)

## Contratação

CLT 

## Como se candidatar

Por favor envie um email para glelcia.alencar@harpio.com.br com seu CV anexado - enviar no assunto: Mobile Android Pleno ou pelo link: https://jobs.kenoby.com/vagasharpiotecnologiamkt/job/mobile-android-pleno/5f85a7e6a3879142efb2679f

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: glelcia.alencar@harpio.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível

- Pleno

**Comment by hallss93** [comment]
Vaga front-end ou mobile?

**Comment by Glelcia** [comment]
Oi Hallison, é mobile!!!
________________________________
De: Hallison Pereira Melo <notifications@github.com>
Enviado: sexta-feira, 6 de novembro de 2020 14:32
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: Glelcia <glelcia@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [São Paulo] Front-end Developer na Afya Educacional (#3783)


Vaga front-end ou mobile?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
