### ISSUE TITLE
[Remoto/Goiânia] Front-end Developer na Supera Tecnologia

### ISSUE THREAD

**Issue by brunocroh** [frontendbr/vagas#3784]
## Nossa empresa

A Supera Inovação em Tecnologia apoia quem enfrenta a crescente competitividade dos mercados. Está preparada para apoiar o cliente que se preocupa em alinhar a estratégia e trabalhar de forma pró-ativa na gestão dos recursos materiais e intelectuais inerentes a tecnologia da informação.

## Descrição da vaga

Procuramos um Desenvolvedor(a) Javascript + React  para trabalhar no desenvolvimento Web e Mobile com produtos inovadores, que envolvem manutenção e construção de telas e funcionalidades.
O teste será feito em React Native, mas não é necessária experiência com a tecnologia, você pode aprender no processo, oque será avaliado é a qualidade do código, e uso do Javascript.

## Local

Remoto ou Escritório em Goiânia-GO, Cidade Jardim

## Requisitos

**Obrigatórios:**
Javascript, HTML, CSS

**Desejáveis:**
React, React Native, Git, Node e Graphql.

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie o CV através do link - https://curriculo.supera.com.br/curriculo/

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: elton.souza@supera.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ
- CLT

#### Nível
- Júnior
- Trainee

**Comment by anabeatrizzz** [comment]
Olá,
Esta vaga ainda está disponível?

**Comment by brunocroh** [comment]
> Olá,
> Esta vaga ainda está disponível?

Infelizmente não está mais diponivel @anabeatrizzz.
Irei encerrar a issue.
Obrigado pelo interesse!
