### ISSUE TITLE
[REMOTO ou SP/CAMPI/SCARL/POA/REC] Desenvolvedor Front-End @ Wavy

### ISSUE THREAD

**Issue by Nagaumi** [frontendbr/vagas#3785]
**Nossa empresa**
A Wavy é uma empresa especialista no Customer Experience, sempre buscando as melhores experiências para seus clientes e usuários, por isso está buscando Desenvolvedores Front-End para integrar seu time!

**Descrição da vaga**
Buscamos um perfil que trabalhe em equipe para desenvolver e aprimorar plataformas web e aplicações ricas em boas experiências para os usuários, para que a Wavy se consolide cada vez mais e possa aprimorar e afetar positivamente a vida de cada vez mais pessoas.

**Local**
São Paulo, Campinas, São Carlos, Porto Alegre, Recife ou Remoto.

**Requisitos**
**Obrigatórios:**

- Experiência com Tecnologias de desenvolvimento front-End: JavaScript, HTML e CSS.
- Experiência prática com framework Javascript de mercado (preferencialmente Angular)
**Desejáveis:**

- Conhecimentos de React e Vue.js
- Inglês avançado

**Nível**
- Pleno

**Contratação**
CLT

**Como se candidatar**
Acesse: https://byintera.in/1hr

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
