### ISSUE TITLE
[Full Remoto/São Paulo] Front-end Developer no Elo7

### ISSUE THREAD

**Issue by marielmoura** [frontendbr/vagas#3786]
## Nossa empresa

O Elo7, o maior marketplace de produtos criativos da América Latina, está com muitos desafios técnicos para implementar com seus novos projetos. Utilizamos práticas ágeis de desenvolvimento e gostamos de ter um ambiente bem descontraído.

## Descrição da vaga

O nosso time de front-end web trabalha principalmente no desenvolvimento das páginas do marketplace utilizando as tecnologias HTML, SCSS, JavaScript, Node e Java. 

Somos um time Fullstack participando do desenvolvimento do layout das páginas e da integração no back-end.

Também cuidamos de todo o ambiente ao redor que pode facilitar o desenvolvimento, influenciar o usuário, detectar bugs e automatizar processos. Testes automatizados, reaproveitamento de código entre telas e métricas são algumas dessas tarefas.

O público alvo da vaga são profissionais com alguma experiência no mercado de trabalho e disposto a aprender e compartilhar conhecimento.

## Local

Full Remoto ou Escritório: SP / São Paulo / Vila Olímpia

## Requisitos

**Obrigatórios:**
- 2-3 anos de experiência com front-end

**Desejáveis:**
- Semântica HTML
- Layout CSS
- JavaScript puro
- Lógica de programação

**Diferenciais:**
- Node
- Arquitetura de componentes
- Padrão MVVM (two way data binding)
- Isomorfismo
- SEO
- Performance
- Acessibilidade

## Benefícios

- Vale Refeição e alimentação: benefício flexível;
- Plano de Saúde;
- Odontológico;
- Seguro de Vida;

**Diferenciais:**
- Gympass: plataforma que te dá acesso a mais de 18 mil academias no Brasil. Nas academias conveniadas são oferecidas mais de 700 modalidades esportivas
- Auxílio Creche;
- Yoga, Meditação e Ginástica Laboral;
- Parceria com Zenklub que oferece 4 sessões gratuitas por mês;
- Temos descontos em cursos de empresas como Caelum, ESPM e ComSchool;
- Manicure, Massoterapeuta, Naturólogo, Aula de Música e Aula de Inglês: Parcerias com valor acessível e atendimento no escritório;

## Contratação

O nosso regime de contratação é CLT, com flexibilidade (40h semanais);

## Como se candidatar

Inscreva-se em https://elo7.gupy.io/jobs/556840

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@elo7.com.br

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
