### ISSUE TITLE
[100% home office]  Front-end Developer na BRQ Digital Solutions

### ISSUE THREAD

**Issue by ReAnne123** [frontendbr/vagas#3787]
Sobre a BRQ Digital
Há 27 anos no mercado, a BRQ Digital Solutions se consolidou como uma das maiores empresas de tecnologia do país, promovendo a digitalização de bancos, seguradoras, companhias de telecomunicação e outras instituições líderes em seus setores. Com mais de 2 mil funcionários, espalhados em seis unidades, sendo cinco no Brasil e uma em Nova York, a empresa é destaque como um dos melhores lugares para trabalhar pela GPTW e Glassdoor.

Descrição da vaga
Estamos em busca de 2 profissionais com experiência em Front Pleno para atuar em projeto inicialmente de 5 meses. 100% home office, por isso profissionais de todo o Brasil são bem vindos.

Local
100% remoto.

Requisitos
JavaScript, HTML5, Angular 8.

Contratação
CLT, salário a combinar + cesta de benefícios contendo plano de Saúde; Plano Odontológico; Seguro de Vida; Vale Refeição; Vale Alimentação; Gympass e muito mais!

Como se candidatar
Envie seu cv para Renata (ryokota@brq.com).

Labels
CLT
Remoto
Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
