### ISSUE TITLE
[Belo Horizonte] Pessoa Desenvolvedora Front-end na Studio Sol

### ISSUE THREAD

**Issue by arturbani** [frontendbr/vagas#3788]
> Vaga Remota durante a pandemia

## Nossa empresa

A Studio Sol é uma empresa de inovação e tecnologia feita por pessoas incríveis, como você. Estamos há mais de 20 anos no mercado e criamos produtos que impactam mais de 17 milhões de pessoas por mês!

É aqui que é feito o trampo incrível do Cifra Club, maior site de ensino de música do Brasil, e do Palco MP3, app brasileiro de música mais baixado na história do Google Play!

Temos um app que é escolha de editor no Google Play e já fomos mencionados em diferentes edições do Google I/O. Já fomos destaque nas páginas iniciais das lojas de apps do Android, iOS e Windows Phone. Recebemos o prêmio de parceiro do ano com a Microsoft. Nossos sites tem acessos recordes no Brasil e já ganhamos o prêmio iBest por 6 anos consecutivos. O canal do Cifra Club ganhou placa de ouro do YouTube e hoje já conta com mais de 5.4 milhões de inscritos. Quer ajudar a gente a escrever os próximos marcos dessa história?

Vem pra Studio Sol =)

## Descrição da vaga

Nosso propósito é criar produtos inovadores para o maior número de pessoas viverem experiências transformadoras e queremos que você construa isso com a gente.

Estamos buscando pessoas que cuidem com muito carinho e atenção de nossos nossos sites desktop e mobile. React, Sass, REST, GraphQL, CSS Modules são alguns recursos que utilizamos.

Usabilidade, com código otimizado e performático é o nosso foco. 💪🏼

Se identificou? Vem trabalhar com a gente! 😄

### Responsabilidades

- Desenvolver novas features e produtos relacionados ao Cifra Club;
- Dar manutenção em todas as aplicações que servem ao Cifra Club;
- Garantir que nossas plataformas funcionem bem em diferentes navegadores e dispositivos;
- Trabalhar em equipe realizando e recebendo code reviews.

## Local

Remoto durante a pandemia, por enquanto. Após a pandemia, nosso escritório fica no bairro Funcionários, em Belo Horizonte - MG.

## Requisitos

- Domínio de Javascript, CSS e HTML;
- Perfomance  (tanto do Javascript, quanto do CSS. Sim CSS!);
- Design responsivo;
- Conhecimentos em SEO;
- React;
- Typescript;
- Controle de versão Git;
- Ferramentas de automação e build (webpack);
- Consumo de APIs REST;
- Padrões de projeto.

**Desejáveis:**

- Experiência com testes unitários e testes ponta a ponta (e2e);
- Experiência em desenvolvimento Front-end de pelo menos 3 anos;

## Benefícios

- Remuneração compatível com o mercado;
- Carga horária 40h semanais;
- Vale transporte;
- Vale refeição ou alimentação de R$30,00 por dia trabalhado;
- Plano de saúde e odontológico;
- Não temos "Dress Code";
- Temos ginástica laboral;
- Frutas e café ficam à vontade na nossa cozinha (quando voltarmos ao escritório).

Ah! Todos os benefícios não possuem desconto em folha!

## Como se candidatar

Candidate-se em: https://studiosol.gupy.io/jobs/487908

## Tempo médio de feedbacks

Costumamos enviar feedbacks em no máximo 4 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@studiosol.com.br

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by arturbani** [comment]
Opa, @felipefialho . A label de `São Paulo` foi por acidente no hook =)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
