### ISSUE TITLE
[REMOTO] Senior FrontEnd Developer

### ISSUE THREAD

**Issue by ednilsonamaral** [frontendbr/vagas#379]
A Manatee é uma startup em fase de desenvolvimento beta e está a procura de um Desenvolvedor Front-End Senior remoto. Para se candidatar, envie um email para manateebrasil@gmail.com com seu CV anexado, links para github e portfólio com o assunto “[Vaga] Senior FrontEnd Developer”

## Descrição da vaga
- Desenvolvimento front-end de um editor de vídeo web
- Contribuirá no planejamento e evolução do projeto
- Atuará com toda a equipe, auxiliando na compreensão da necessidade que o projeto requer, bem como nas estratégias de desenvolvimento, levantamento de requisitos e demais necessidades técnicas  
- Auxiliará na padronização do código e na documentação do front-end do projeto

## Local
100% Remoto

## Requisitos

**Obrigatórios:**
- 4/5 anos de experiência com desenvolvimento front-end
- Inglês técnico
- Conhecimentos avançados em HTML
- Conhecimentos avançados em CSS
- Conhecimentos avançados em JavaScript (ES5, ES6)
- Conhecimentos avançados gerenciadores de tarefas e bundles (Gulp, Webpack)
- Conhecimentos avançados em pré-processadores de CSS (Stylus, SASS, SCSS)
- Experiência em consumo de APIs
- Conhecimentos em frameworks CSS
- Conhecimentos em frameworks JavaScript (AngularJS, Vue.js)

**Desejáveis:**
- Conhecimentos avançados em HTML
- Conhecimentos avançados em CSS
- Conhecimentos avançados em JavaScript (ES5, ES6)
- Experiência em consumo de APIs
- Conhecimentos em frameworks JavaScript (AngularJS, Vue.js)

**Diferenciais:**
- Excelente habilidade de comunicação
- Trabalho em equipe
- Gerenciamento de tempo
- Responsabilidade para trabalhos remotos
- Experiência em outras linguagens de programação e/ou frameworks não mencionados acima serão um diferencial importante
- Ter trabalhado com metodologias ágeis
- Facilidade para trabalhar com sprints semanais e entregas pontuais

## Contratação
PJ, valores à combinar

## Como se candidatar

Para se candidatar, envie um email para manateebrasil@gmail.com com seu CV anexado, links para github e portfólio com o assunto “[Vaga] Senior FrontEnd Developer”

**Comment by XLucifer** [comment]
Enviado o curriculo
Aguardando um retorno =]]

**Comment by sunfreitas** [comment]
Email enviado

**Comment by XLucifer** [comment]
Fechou a vaga??

**Comment by ednilsonamaral** [comment]
@XLucifer ainda não. Quem enviou e-mail de contato, estamos entrando em contato.

**Comment by XLucifer** [comment]
@ednilsonamaral Ok, fico no aguardo, abraços

**Comment by ednilsonamaral** [comment]
Vaga preenchida, pessoal. Obrigado à todos!
