### ISSUE TITLE
[Remoto / Belo Horizonte/MG] Fullstack PHP Developer na Teknisa

### ISSUE THREAD

**Issue by Marissol-coodesh** [frontendbr/vagas#3793]
## Descrição: 
 <p>A Teknisa está buscando <strong>Pessoas Desenvolvedoras de Sistema</strong>!</p>
<p>A Teknisa oferece soluções de suporte à gestão com forte atuação nos segmentos de indústrias alimentícias, químicas e farmacêuticas, atendendo todos os canais ligados ao mercado de food service.</p>
<p>A Teknisa ocupa hoje uma posição de destaque no mercado latino americano de software, com seus sistemas implantados em várias empresas, presente em 6 países, 20 mil instalações, 65 mil usuários ativos e mais de 20 milhões de clientes atendidos por dia pelos sistemas Teknisa. Atuando nos níveis estratégicos, táticos ou operacionais, hoje a Teknisa compõe o roll das cinco empresas que comercializam soluções específicas para atender diferentes segmentos.&nbsp;</p>
<p><strong>Responsabilidades:</strong></p>
<ul>
<li>Elaborar documentação para os sistemas e aplicações de fácil entendimento, visando a melhor interpretação dos programadores;</li>
<li>Efetuar o levantamento das informações através de entrevistas com os clientes finais e gestores de desenvolvimento, visando elaborar os processos que serão utilizados na confecção dos sistemas e aplicações;</li>
<li>Desenhar o diagrama de fluxos de informações, bem como inventariar software e hardware, efetuando o levantamento de todas as ferramentas necessárias para o desenvolvimento do projeto;</li>
<li>Emitir parecer técnico, sobre o desenvolvimento do sistema e aplicação, quando for necessário;</li>
<li>Elaborar os estudos de viabilidade técnica e econômica, bem como especificações técnicas, verificando a viabilidade do projeto;</li>
<li>Desenvolver sistemas informatizados através do levantamento de dados e estudos das regras de negócios;</li>
<li>Realizar auditoria e monitorar a performance do sistema e aplicação, identificando e corrigindo falhas e executando procedimentos para melhorias;</li>
<li>Administrar os recursos de banco de dados e ambiente operacional, administrando perfil de acesso às informações, dados e recursos, evitando conflitos de informações;</li>
<li>Orientar as áreas de apoio, nas consultas a documentações técnicas e fontes alternativas de informações, simulando problemas em ambiente controlado quando necessário ou acionando suporte;</li>
<li>Prestar consultoria técnica, quando necessário, identificando necessidades do cliente;</li>
<li>Pesquisar e identificar novas tecnologias, identificando fornecedores, solicitando demonstrações de produto e avaliando a funcionalidade do produto, visando manter atualizados os sistemas e aplicações da empresa;</li>
<li>Coordenar projetos de desenvolvimento de sistemas e aplicações;</li>
</ul>

## Teknisa: 
 <p>Venha sentir a alegria de ser Teker! Consulte as vagas em aberto ou cadastre seu curriculo no nosso Banco de Talentos no final da página.</p>
<p></p>
<p>A Teknisa é uma empresa com 30 anos de atuação que oferece soluções com diferenciais tecnológicos, baseado nas demandas do mercado. Por meio de softwares desenvolvidos com distintas finalidades, as ferramentas potencializam a performance tanto de líderes quanto de colaboradores, agregando mais resultados a seus clientes. Especializada no segmento de food service, apresenta soluções utilizando a inteligência Artificial / IoT para melhorar os resultados do setor de alimentação fora do lar.</p>

## Habilidades: 
 - HTML 
- CSS 
- Vue.js 
- PHP 
- Symphony 
- Laravel 
- Git
## Local: 
 Belo Horizonte/MG
## Requisitos: 
 - Experiência de 2 anos ou mais na stack da vaga 
- Experiência em HTML, PHP, Vue.js 
- Experiência em banco de dados relacionais (MySQL) 
- Habituado com GIT / Versionamento 
- Conhecimento em logística

## Benefícios: 
 - Vale refeição 
- Plano de saúde 
- Plano odontológico 
- Seguro de vida 
- PL 
- 40hs semanais
## Como se candidatar:
Candidate-se em: [Fullstack PHP Developer na Teknisa](https://coodesh.com/vagas/desenvolvedor-a-de-sistema-210821?origin=github&modal=open)
## Tempo médio de feedbacks:
 Costumamos enviar feedbacks em até 48 horas após cada etapa do processo. E-mail para contato em caso de não haver resposta: [contato@coodesh.com](mailto:contato@coodesh.com)
#### Alocação
Alocado
#### Regime
CLT
#### Nível
Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
