### ISSUE TITLE
[Remoto] Front-end Developer na WECANCER

### ISSUE THREAD

**Issue by leomamerlo** [frontendbr/vagas#3794]
**Nossa história**
Em 2014, César e Lorenzo vivenciaram os desafios da jornada contra o câncer ao cuidar de suas mães. Da dor e da saudade nasceu a vontade de apoiar os milhares de pacientes que passam pelo tratamento oncológico. Assim foi fundada a WeCancer, uma ferramenta de suporte digital, que proporciona mais conforto e cuidado ao paciente. Quer conhecer, um pouco mais? www.wecancer.com.br

**Front-end Developer**
Estamos à procura de programadoras/es sênior com foco em React para se juntarem à nossa equipe e construir um futuro de muito impacto à saúde brasileira.

A principal responsabilidade é: desenvolver e otimizar aplicativos móveis que possibilitam a assistência à pacientes com câncer.
- Participar da concepção do produto junto com a equipe de Design;
- Construir interfaces com React e React-native;
- Otimizar requisições com um servidor NodeJS (GraphQL/Apollo);
- Escrever códigos com cobertura de teste (TDD);
- Ajudar o time a monitorar a estabilidade dos sistemas;

Conhecimento obrigatório em:
- Experiência mínima de 5 anos como Desenvolvedor;
- Experiência mínima de 3 anos com React;
- React e React-native;
- Redux e React Hooks;
- Testes automatizados;

Conhecimento desejável em:
- Scrum

**Local**
Remoto ou Escritório para quem quiser na Eretz.bio, coworking de startups do Hospital Albert Einstein localizado na Vila Mariana, São Paulo.

**Benefícios**
- 13º salário
- Férias 30 dias remunerada
- Recesso fim de ano
- Homeoffice

**Contratação PJ** 

**Como participar?**
Acesse o descritivo da vaga aqui: **www.bit.ly/wecancer-oportunidade06**. Ou inscreva-se direto aqui: **www.bit.ly/wecancer-quero06**. Qualquer dúvida, mande um email para leo@wecancer.com.br
.
Um abraço!
Time WeCancer

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
