### ISSUE TITLE
[Remoto] Front-End React Developer (Remote) na Celcoin

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#3796]
## Descrição: 
 <p>A CELCOIN está buscando uma <strong>Pessoa Desenvolvedora Front-End React.js.</strong></p>
<p>Trabalhe em uma Startup, com uma equipe altamente colaborativa, um lugar sem burocracia e com muito espaço para inovação.</p>
<p>Somos uma empresa certificada pelo GPTW e reconhecida por ter um excelente ambiente para se trabalhar!</p>
<p>Buscamos uma pessoa desenvolvedora front-end para atuar no Celcoin na construção de produtos e ferramentas voltadas para a nossa rede de agentes espalhados por todo o Brasil.&nbsp;</p>
<p>A pessoa irá atuar em conjunto com o time de UX/UI e o time de desenvolvimento transformando protótipos em códigos precisos e rápidos para garantir a melhor experiência dos nossos agentes com o uso do nosso Site e Aplicativo. Aqui você irá trabalhar com Bootstrap, JavaScript, CSS, React.js, Android e Flutter (em migração). Essa é uma oportunidade única de trabalhar em uma Startup em crescimento acelerado, altamente inovadora e com um time altamente capacitado no uso de tecnologias e ferramentas para alcançar a satisfação do seu cliente.</p>
<p><strong>Responsabilidades:</strong></p>
<ul>
<li>Desenvolvimento e manutenção de aplicações web;&nbsp;</li>
<li>Integração com os projtos backend para consumo de dados via API;</li>
<li>Escrever bibliotecas de interface reutilizáveis para web e mobile responsivo (Design System);</li>
<li>Extrair o máximo de velocidade das interfaces implementas;</li>
<li>Trabalhar com o time de UX/UI e traduzir os protótipos/wireframes em códigos;</li>
<li>Trabalhar com o time de design com diretrizes técnicas;</li>
<li>Desenvolvimento e manutenção de landing pages, blogs etc.</li>
</ul>

## Celcoin: 
 <p>Fundada em 2016, com a ideia de facilitar novos entrantes a empreender no sistema financeiro, que até seu surgimento, era completamente fechado, de difícil acesso e difícil de se conectar, a Celcoin uma plataforma que permite empresas a se conectar ao sistema financeiro de forma simples e sem burocracias para oferecerem experiências inovadoras para seus clientes, seja no mundo digital, com mais de 100 clientes entre bancos digitais, fintechs, empresas de fidelização, ou seja no mundo físico, onde já conta com uma rede própria de mais de 33 mil correspondentes digitais em 3.100 municípios brasileiros.&nbsp;</p>
<p>Pioneira em seu segmento, a Celcoin adota uma estratégia multicanal única em seu segmento, e já processa mais de 10 milhões de transações financeiras e um volume superior a R$ 1,1 bi mensalmente.</p>
<p>Em 2017 recebeu os títulos de “Melhor Startup do Brasil” pelo grupo de investidores suíços Seedstars, “Melhor Fintech do País” pelo BBVA Open Talent, acelerada em 2019 pelo Programa de Aceleração da Visa e pela ScaleUp (Endeavor). Também em 2019, recebeu aporte de R$ 6 milhões do principal fundo de investimentos de impacto social, Vox Capital, e é a única fintech da América Latina e Caribe a receber o prêmio global “The Inclusive Fintech 50”. Em 2019, foi certificada também como uma companhia Great Place to Work (GPTW). Em 2020 foi acelerada pelo BoostLab (by BTG Pactual) e foi nomeada pela terceira vez consecutiva na lista 100 Startups to Watch, da revista PEGN.</p>
## Habilidades: 
 - HTML5 
- CSS3 
- Bootstrap 
- Javascript 
- React.js

## Local: 
 100% Remoto

## Requisitos: 
 - Formação em Ciência da computação, Engenharia ou sistema de informação 
- Habituado com HTML5, CSS3, Bootstrap, Javascript e React.js 
- Bons conhecimentos em chamadas assíncronas para atualização parcial de páginas, como AJAX; 
- Construção de Interfaces utilizando Material Design 
- Integração com APIs REST 
- Conhecimento em metodologias ágeis (SCRUM) 
- Experiência em desenvolvimento front-end 
- Comunicação objetiva 
- Criatividade para resolver problemas desafiadores 
- Pensamento Crítico e analítico 
- Capacidade de tomar decisões

## Benefícios: 
 - Plano Médico (sem coparticipação) 
- Plano odontológico (sem coparticipação)   
- Vale Refeição de R$22,00/Dia 
- Auxílio Home Office: R$150,00/ mês 
- Seguro de Vida 
- Auxílio- Creche 
- 100% Home Office

## Como se candidatar:
Candidate-se em: [Front-End React Developer (Remote) na Celcoin](https://coodesh.com/vagas/desenvolvedor-a-frontend-173408?origin=github&modal=open)

## Tempo médio de feedbacks:
 Costumamos enviar feedbacks em até 48 horas após cada etapa do processo. E-mail para contato em caso de não haver resposta: [contato@coodesh.com](mailto:contato@coodesh.com)

#### Alocação
Remoto

#### Regime
CLT

#### Nível
Pleno

**Comment by suyfranca** [comment]
Franciele, bom dia! Alguma oportunidade para nível Jr?

**Comment by FrancieleGhizzoni** [comment]
Bom dia, Tudo bem? Essa vaga aceita também candidaturas nível júnior, com
conhecimento em React. Abraço

Em ter, 10 de nov de 2020 10:26, Suyanne França <notifications@github.com>
escreveu:

**Comment by FrancieleGhizzoni** [comment]
Vaga em revisão de candidaturas.
