### ISSUE TITLE
[Remoto] Front/Mobile Developer na Sotero Tech

### ISSUE THREAD

**Issue by fxcosta** [frontendbr/vagas#3797]
> Vaga Remota durante a pandemia

## Nossa empresa
Somos uma empresa brasileira de tecnologia digital e estamos localizados na região metropolitana de Salvador, na Bahia.
Realizamos trabalhos de destaque em pesquisa, concepção, coordenação e desenvolvimento de projetos nas áreas de Marketing, Comunicação, Tecnologia e Arte Digital, combinando inovação e praticidade na criação dos nossos projetos. Quer conhecer mais? www.soterotech.com.br

## Descrição da vaga
Buscamos pessoa desenvolvedora com foco em React e seu ecossistema para trabalhar num projeto na área da saúde grande potencial de crescimento e impacto na área.

## Local
Remoto

## Requisitos

**Obrigatórios:**
- Base sólida de HTML5/CSS3
- Proficiência em JavaScript e TypeScript
- Experiência com React (Web e Mobile)
- Experiência em consumo de APIs REST

**Desejáveis:**
- Testes automatizados
- Noções de Nodejs
- Noções de Clean code e boas práticas

**Diferenciais:**
- Projetos pessoais no github ou contribuição ao opensource

## Benefícios

- Horário flexível

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para selecao@soterotech.com.br com seu CV anexado - enviar no assunto: Vaga Front/Mobile Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: contato@soterotech.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
