### ISSUE TITLE
[Remoto] Front-end Developer na Todo Cartões

### ISSUE THREAD

**Issue by kalicki** [frontendbr/vagas#3799]
## Todo Cartões
A Todo Cartões é uma Fintech no segmento de Gift Cards e Listas de Presente. Nosso crescente time busca causar um impacto relevante nos maiores varejistas do país. Nossos produtos são usados por centenas de milhares de usuários todos os dias.

Prezamos por uma estrutura horizontal, explorando ao máximo o espírito de colaboratividade, ou seja: todos contribuem para a entrega.

**Estamos contratando Front-end Developer (mais de 3 anos de experiência) para fazer parte do nosso time de tecnologia.**

### Nosso stack atual
- React;
- Next.js;
- Angular JS;
- Ruby on Rails;
- PostgreSQL;
- Redis e Sidekiq;
- Elixir e Phoenix;

### Você:
- Coloca a experiência do usuário como prioridade nas suas decisões;
- Se comunica bem e valoriza relações interpessoais; 
- Sabe transitar entre tecnologias, sempre aprendendo coisas novas;
- Se sente confortável com metas ousadas, comunicando caso for preciso revisá-las;
- Gosta de discutir em time sobre design de sistemas complexos;

### Desejáveis:
- Habilidades de design de tela;
- Boas habilidades de comunicação (transparência, clareza);
- Experiência com UX;
- Experiência participando de reuniões para design de sistemas complexos;

### Metodologia

Estamos trabalhando com o Shape Up e o software Basecamp para executar projetos. Para o desenvolvimento de uma nova feature ou produto, são 6 semanas de esforço e 2 semanas de "cool-down" para os engenheiros decidirem o que querem fazer com o este tempo.

### Sobre a Todo

A Todo Cartões cria e opera programas de Gift Card digitais para grandes varejistas de todo o Brasil. Nossas plataformas ajudam a fidelizar clientes e gerar mais valor para a marca, com grande representatividade no aumento vendas, rastreabilidade e conhecimento de marca.

Nosso trabalho pode ser visto em grandes marcas como: Outback Steakhouse, Applebee’s, Lojas Leader, Riachuelo, TNG, Grupo RiHappy, Electrolux, Pizza Hut, TGI Friday’s, entre muitos outros.

Trabalhamos com OKR’s (Objectives and Key Results) que nos ajuda a manter um foco trimestral importante e a medição objetiva de metas de time e individuais também. 

### Benefícios
Horário flexível
Cultura de valorização e premiação interna com Kudos que geram Gift Cards
Frutas e comidinhas saudáveis no escritório (quando pudermos voltar a frequentar)

**_A Todo Cartões preza e valoriza a diversidade. Temos um ambiente descontraído onde todos são bem vindos. Nossas vagas estão abertas a todas as pessoas! Se você sente que pode fazer a diferença por aqui, candidate-se!_**

## Como se candidatar

Para se candidatar, se inscreva em: https://airtable.com/shryJlHDe3b4yAT6o

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após cada processo.
Dúvidas: amanda@todocartoes.com.br ou kalicki@todocartoes.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
