### ISSUE TITLE
[São Paulo] - Desenvolvedor(a) Front-End - Jussi

### ISSUE THREAD

**Issue by DouglasAmarelo** [frontendbr/vagas#38]
## Descrição da vaga

Estamos à procura de desenvolvedores front-end para fazer parte da nossa equipe.
Buscamos pessoas que tenham experiência em desenvolver produtos digitais em diferentes plataformas e ambientes. Especialistas em HTML e CSS e JavaScript, que pensem fora da caixa, que queiram melhorar a vida das pessoas através de prdutos inovadores, criativos, bem feitos e com códigos bem escritos e eficientes.
Durante o dia de trabalho você será desafiado e, será responsável pelo desenvolvimento de grandes projetos capazes de afetar a vida de milhares de pessoas ao redor do mundo.
Se você gosta de desafios, é curioso, sonha em crescer profissionalmente e em fazer parte de uma empresa com grandes clientes, essa pode ser a sua oportunidade.
Venha conhecer nosso escritório e conversar com a gente.

## Local

Rua Bandeira Paulista, São Paulo - Itaim Bibi

## Benefícios
- Excelente ambiente de trabalho
- Oportunidade de crescimento profissional
- Oportunidade de trabalhar com grandes clientes
- Vale refeição
- Vale transporte
- Assistência médica
- Assistência odontológica

## Requisitos

**Obrigatórios:**
- Domínio em JavaScript, HTML5, CSS3
- Capacidade para escrever código consistente, eficiente, minimalista, reutilizável e escalável
- Desenvolver código semanticamente correto e otimizado para SEO
- Grunt ou Gulp
- Experiência com bibliotecas de Javascript
- Experiência com grids e sites responsivos
- Familiaridade com PHP e CMSs populares, como Wordpress
- Experiência com controle de versão, como Git/SVN
- Facilidade de trabalho em equipe
- Proatividade

**Desejáveis:**
- Portfólio
- Experiência de pelo menos 2 anos com web e/ou produtos digitais
- Conhecimento em SASS e/ou LESS

**Diferenciais:**
- Conhecimento avançado em javascript (sem plugins ou bibliotecas)
- Conhecimento de técnicas de otimização de performance
- Experiência em construção de e-comnerce na plataforma VTEX

## Contratação

CLT 
Salário a combinar

## Como se candidatar

Por favor envie um email para douglas.lopes@jussi.com.br com o assunto: "Vaga Desenvolvedor(a) Front-end"

No email deve conter: 
- Currículo
- LinkedIn
- Link do portfólio
- Link de trabalhos feitos

**Comment by LFeh** [comment]
Boa sorte @DouglasAmarelo

**Comment by DouglasAmarelo** [comment]
Vlw @LFeh!!!

**Comment by LFeh** [comment]
Deu certo? \o

**Comment by camilatigre** [comment]
@DouglasAmarelo 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
