### ISSUE TITLE
[REMOTO] Full Stack Developer

### ISSUE THREAD

**Issue by jsteruya** [frontendbr/vagas#380]
## Descrição da vaga
 
Trabalhará como desenvolvedor em Projetos Novos e Ambiciosos, com uma equipe de desenvolvedores de alto nível.
Os Projetos englobam Aplicativos, Web, API’s e Bots.
conhecimento obrigatório é JavaScript/HTML/CSS, tendo vontade de aprender as outras linguagens serão aprendidas no dia-a-dia com pull requests para code review.
 
## Local
 
100% Remoto
 
## Benefícios
 
1 Happy hour por mês (Residentes em São Paulo).
 
## Requisitos
 
**Obrigatórios:**
JavaScript(es5/es6).
Git/Github.
Ter boa comunicação.
 
**Desejáveis:**
Ionic2, 
Rails
Nodejs
 
**Diferenciais:**
projetos opensource.
Mentalidade Startup, construir a empresa e crescer junto com a empresa.
Python
 
## Contratação
 
PJ a combinar
 
## Nossa empresa
 
A Lenord é uma empresa nova no Mercado, com corpo diretivo de profissionais com mais de 20 anos atuando no Varejo.
Desenvolvemos soluções voltadas para o Varejo de Pequeno e Médio porte, para que melhorem a efetividade de seus negócios.
Estamos Desenvolvendo um ERP próprio também.
 
## Como se candidatar
 
Envie um e-mail para rh@lenord.com.br com seu CV Anexado - Enviar no assunto: Vaga Fullstack Developer

**Comment by jsteruya** [comment]
Labels :point_right: Remoto, PJ, Estagiario, Júnior, Pleno

Valeuu!

**Comment by jvcjunior** [comment]
@jsteruya Vocês tem algum projeto com React?

**Comment by jsteruya** [comment]
Por enquanto nao @jvcjunior

**Comment by jsteruya** [comment]
Currículos recebidos, vamos analisar essa semana ainda!

**Comment by HaluDeCassia** [comment]
Obrigada. Aguardando resposta 😊
-- 
Att, Haluane Amâncio

**Comment by mtmr0x** [comment]
@jsteruya a vaga continua aberta?
