### ISSUE TITLE
[REMOTO/ VALINHOS SP] REACT Developer na KROTON

### ISSUE THREAD

**Issue by marianeors1** [frontendbr/vagas#3800]
## Nossa empresa
A Kroton tem mais de 50 anos de tradição e é atualmente uma das maiores empresas do setor de educação, atuamos com ensino superior B2C. Mas, especialmente em nosso caso, tradição e liderança não são traduzidas em modelos antigos e ‘zona de conforto’. Pelo contrário!

Temos em nosso DNA a inovação e o dinamismo de uma jovem startup. Um dos reflexos disso é a nossa busca constante pela #TransformaçãoDigital. Estamos em busca de transformação em todos os sentidos: de histórias, de vidas, do futuro.

## Descrição da vaga
A Kroton está passando por um forte processo de transformação digital e planeja ser o maior grupo de edtechs do Brasil. Pra isso, está construindo um time de tecnologia de alto nível e está buscando pessoas desenvolvedoras em NODE, PHP e REACT para fazer parte da equipe e impactar a vida de milhões!
## Local

 Remoto ou Escritório, Valinhos- SP

## Requisitos

**Obrigatórios:**

DESENVOLVEDOR REACT
Familiaridade com técnicas de Code-Review e Pair Programming;
Conhecimentos em Java Script incluindo manipulação de DOM;
Alta visão de componetização construindo códigos de alto reuso;
Facilidade de desenvolvimento de micro-interações;
Capacidade em desenvolvimento de aplicações SinglePage;
Experiência em otimização de interfaces para máximo de velocidade de carregamento;
Conhecimentos de conceitos de SEO;
Capacidade de construir soluções com compatibilidade cross-browsers;
Conhecimentos de desenvolvimento de interfaces assíncronas realizando chamadas serviços REST;
Familiaridade com git e/ou GitHub;
Capacidade de desenvolvimento utilizando pré-processadores de CSS  como LESS e SAAS;
Conhecimento em bases NoSQL com preferência a MongoDB;
Experiências em desenvolvimento Web 2.0 utilizando tecnologias jQuery, CSS3, HTLM5, Less, AJAX, JSON, Bootstrap;
Automação de testes de interface.

**Diferenciais:**

REACT

Familiaridade com Jenkins.
- projetos opensource

## Benefícios

Assistência Médica
Assistência Odontológica
Vale Refeição ou Alimentação
Vale Transporte
Seguro de Vida
Gympass
Desconto em Bolsa graduação/pós-graduação nas marcas Kroton
K-Vantagens: Clube de benefícios com descontos nos parceiros;
Be Youserlf - Aqui você pode se vestir para o trabalho do jeito que você se sentir melhor
Havaianas Friendly
Participação nos Lucros
Temos espaços de descompressão em todos escritórios corporativos para você ter aquele momento relax.

## Contratação

CLT

## Como se candidatar

Através do link http://byintera.in/1is

#### Regime
- CLT

#### Nível
- Júnior

**Comment by igorpinhh** [comment]
necessário ensino superior?

**Comment by marianeors1** [comment]
> necessário ensino superior?

Não! Mas é necessário estar cursando e próximo da conclusão :)

**Comment by diiegoburiti** [comment]
Enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
