### ISSUE TITLE
[100% REMOTO] Front-end Developer na BRQ Digital Solutions

### ISSUE THREAD

**Issue by ReAnne123** [frontendbr/vagas#3804]
Descrição da vaga
Estamos em busca de profissionais com experiência em front para integrar um time para uma grande instituição de ensino.

Local
100% home office.

Benefícios
-vale refeição
-vale alimentação
-seguro de vida
-plano médico Bradesco
-previdência privada
-plano odontológico
-Gympass;
-reembolso de certificações.

Requisitos necessários:
Angular 8, HTML, CSS, javascript.

Contratação
CLT full pela BRQ.
Vaga temporária por 5 meses.

Nossa empresa
Fundada em 1993, a BRQ Digital Solutions é uma das maiores empresas de serviços de TI do país. Conta com 2500 profissionais distribuídos nas filiais de São Paulo, Alphaville, Rio de Janeiro, Curitiba e Nova Iorque.

Como se candidatar
Por favor envie um email para Renata- ryokota@brq.com, com seu CV anexado - enviar no assunto: Front remoto.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
