### ISSUE TITLE
[Remoto] Front-end Developer na Celcoin 

### ISSUE THREAD

**Issue by MelissaCelcoin** [frontendbr/vagas#3809]
> Vaga Remota durante a pandemia

## Nossa empresa

Buscamos um desenvolvedor front end para atuar no Celcoin na construção de produtos e ferramentas voltadas para a nossa rede de agentes espalhados por todo o Brasil. O profissional irá atuar em conjunto com o time de UX/UI e o time de desenvolvimento transformando protótipos em códigos precisos e rápidos para garantir a melhor experiência dos nossos agentes com o uso do nosso Site e Aplicativo. Aqui você irá trabalhar com Bootstrap, JavaScript, CSS, React JS, Android e Flutter (em migração). Essa é uma oportunidade única de trabalhar em uma Startup em crescimento acelerado, altamente inovadora e com um time altamente capacitado no uso de tecnologias e ferramentas para alcançar a satisfação do seu cliente.

## Descrição da vaga

O que você fará:

·         Desenvolvimento e manutenção de aplicações web e mobile; Integração com do desenvolvedor Backend para consumo de dados via API;

·         Escrever bibliotecas de interface reutilizáveis para web e mobile (Design System);

·         Extrair o máximo de velocidade das interfaces implementas;

·         Trabalhar com o time de UX/UI e traduzir os protótipos/wireframes em códigos;

·         Trabalhar com o time de design com diretrizes técnicas;

·         Desenvolvimento e manutenção de landing pages, blogs etc.

## Local
 Remoto

## Requisitos

*Para essa vaga você precisa ter:

·         Formação em Ciência da computação, Engenharia ou sistema de informação.

·         Requisitos: HTML5, CSS3, jQuery, Bootstrap, JavaScript, ReactJS;

·         Bons conhecimentos em chamadas assíncronas para atualização parcial de páginas, como AJAX;

·         Construção de Interfaces Android nativo (Material Design);

·         Integração com APIs REST;

·         Conhecimento em metodologias ágeis (SCRUM)

·         Desejável: Conhecimento de construção de interfaces em Flutter e widget testing; Conhecimento em ferramentas de edição de imagens para realizar pequenos ajustes; desenvolver interfaces utilizando Clean Archtecture

·         Experiência em desenvolvimento front-end.

·         Bom relacionamento com o time;

·         Comunicação objetiva;

·         Criatividade para resolver problemas desafiadores;

·         Pensamento Crítico;

·          Pensamento Analítico;

·         Capacidade de tomar decisões;

·         Entendimento do negócio.

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ 22/dia
- Auxílio creche
- Auxílio Home Office

## Contratação

CLT

## Como se candidatar

Por favor envie o seu currículo pelo link: https://jobs.kenoby.com/celcoin/job/desenvolvedor-front-end/5f7e284e66794d1ea9132c95

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
