### ISSUE TITLE
[São Paulo] Front-End Developer

### ISSUE THREAD

**Issue by 4vets** [frontendbr/vagas#381]
4Vets do Brasil procura profissionais para a vaga:

DESENVOLVEDOR FRONT END Jr/Pleno – São Paulo – 01 Vaga
Requisitos:

**Vagas para iniciantes**

Superior cursando ou completo em Análise de Sistemas, Sistemas de Informação, Ciência da Computação ou afins;
Conhecimento básico como desenvolvedor frontend;
Conhecimento básico com HMTL 5, CSS 3 e Javascript;
Conhecimento básico com frameworks Javascript (Ember, Angular, Backbone, React);
Conhecimento básico em lógica de programação;
Conhecimento básico em pré-processadores de CSS (Less, Sass);
Conhecimento básico em PHP;
Conhecimento básico em GIT;
Conhecimento em Magento (Temas);
Conhecimento em Photoshop / Illustrator (recorte e aplicação dos layouts produzidos).

Atividades:

Desenvolver interfaces para web;
Realizar frontend;
Apoiar na construção da arquitetura da informação dos projetos;
Auxiliar na produção de recursos multimídias.
Salário: à combinar.

**Comment by vicainelli** [comment]
CLT? PJ? Remoto?

**Comment by 4vets** [comment]
Qualquer conhecimento listado à cima é bem vindo, mas o que conta mesmo é o comprometimento e a força de votnade de aprender, a vaga é PJ no momento, existindo a possibilidade de efetivação.

interessados podem enviar email com CV para carlos@4vets.com.br.

**Comment by lucasbarrossantos** [comment]
Está aceitando remoto ?

**Comment by mathvbarone** [comment]
Email enviado! :D

**Comment by 4vets** [comment]
A vaga é pra trabalhar alocado no escritório.

**Comment by mtmr0x** [comment]
@4vets a vaga continua aberta?

**Comment by X-X-Xavito** [comment]
A vaga continua em aberto?
