### ISSUE TITLE
[Remoto] Senior Fullstack Developer @ Gama Academy

### ISSUE THREAD

**Issue by rferro** [frontendbr/vagas#3810]
# Senior Fullstack Developer @ Gama Academy

## :thinking: SOBRE NÓS

Nós somos uma escola que prepara profissionais para o mercado digital, promovendo transformação através da nossa metodologia educacional e tecnologia, atraindo, selecionando e treinando profissionais nas áreas de desenvolvimento, design, marketing e vendas.

Eleita pelo segundo ano consecutivo a melhor startup de educação pelo Startup Awards, nossa missão é transformar um milhão de vidas através da educação, norteando nossos programas educacionais pelas necessidades reais do mercado de trabalho digital, e transformando a vida e a carreira das pessoas de forma ágil e acessível.

## :sunglasses: NOSSA CULTURA

Para garantir o sucesso da nossa missão, temos valores que norteiam nossas decisões e demonstram o que valorizamos e no que acreditamos.

- **Be Owner**

Nos perguntamos constantemente, quando fazemos o que fazemos, se esse é o caminho mais alinhado com nosso propósito.

- **Be Radical Candid**

Nossa melhor forma de valorizar o indivíduo é nos importarmos pessoalmente na mesma medida que desafiamos diretamente.

- **Be a Problem Solver**

Promovemos a mudança sendo parte da solução, não do problema.

- **Be a Manic Learner**

Temos curiosidade em aprender e valorizamos pessoas que se dedicam em compartilhar seus aprendizados e que reconhecem que nunca sabemos tudo.

- **Better Together**

Sabemos que juntos vamos mais longe e mais rápido.

- **Be a Results Hunter**

Iniciativa e acabativa vem de todos, pois somos aficionados(as) em ver os resultados.

- **Enjoy the Ride**

Acreditamos que o trabalho não é a parte ruim da vida.

## :star2: CONHEÇA O DESAFIO...

- Desenvolvimento e manutenção de aplicações e serviços.
- Entender e solucionar problemas e objetivos de negócios da Gama Academy.
- Participar ativamente das decisões sobre desafios técnicos de nosso time de tecnologia.
- Prezar pelas boas práticas de testes e qualidade.
- Estar antenada/o nas novas tecnologias.
- Estar disposta/o a realizar projetos desafiadores com novas tecnologias.

### :fire: ESPERAMOS QUE VOCÊ CONHEÇA...

- Comprovada e avançada experiência com Javascript / Node.js (+ 4 anos).
- Typescript.
- React, React Native, Redux.
- Bancos de dados relacionais: PostgreSQL, MySQL.
- TDD, Testes Unitários, Funcionais e de Integração.
- Clean Code / Coding Standards.
- Proficiência em Git.
- Arquitetura de projetos.

### :+1: ALÉM DISSO, QUE VOCÊ...

- Trabalhe com uma cultura de melhoria contínua e incremental.
- Seja apaixonada/o por educação e tecnologia.
- Queira fazer parte da transformação da educação para o mercado digital.
- Tenha boa atitude, maturidade e comprometimento.

### :blue_heart: VAMOS CURTIR MUITO SE VOCÊ...

- Tiver conhecimento e estiver antenada/o nas tendências do mercado digital.
- Tiver conhecimento em Ruby.
- Tiver noções sobre Integração e Entrega Contínua.
- Tiver conhecimento com serviços AWS: IAM, S3, SQS, SNS, Cognito, e etc.
- Tiver conhecimento ou vivência anterior em metodologias ágeis (Scrum / Kanban).
- Tiver experiência com bancos de dados NoSQL (DynamoDB, MongoDB, e etc).
- Tiver experiência com GraphQL.

## :black_nib: PROPOSTA DE TRABALHO

- Regime de contratação PJ.
- Trabalho Remoto + Escritório em Pinheiros/SP, caso queira utilizar.
- Cartão Benefício Flexível (Flash) de R$800,00 ao mês.
- Bônus Anual de 1 salário no final do ano.
- Férias remuneradas após 12 meses na empresa.
- Auxílio Mensal em Educação/Eventos.
- Auxílio Terapia (Zenklub).
- Computador e acessórios fornecidos pela empresa.
- Licença maternidade de 6 meses e licença paternidade de 1 mês.
- Acesso gratuito a todos nossos cursos e eventos e cupom de descontos para amigos e familiares.

## :question: Se interessou?

Candidate-se [aqui](https://app.pipefy.com/public/form/jt5n79YV).

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
