### ISSUE TITLE
[REMOTO] Front-end Developer na Jungsoft

### ISSUE THREAD

**Issue by pedro-lb** [frontendbr/vagas#3811]
## Nossa Empresa

A Jungsoft é uma startup 100% remota, sediada em Florianópolis - SC com negócios na Alemanha e Estados Unidos. Trabalhamos sempre com tecnologias de ponta, como Elixir, GraphQL, React e React Native.

Possuímos diversos projetos, desde blockchain até big data - ou seja, é um match perfeito se você se gostar de desafios e de sempre aprender coisas novas!

### Suas responsabilidades aqui serão

- Trabalhar em equipe para desenvolver interfaces que trazem uma experiência única e eficiente aos usuários;
- Utilizar linguagens como JavaScript e TypeScript para completar suas tarefas;
- Realizar a comunicação com APIs GraphQL;
- Contribuir com os padrões e melhores práticas;
- Fortalecer o ecossistema React local e internacional;

## Descrição da Vaga

Nosso time está crescendo e queremos pessoas talentosas e apaixonadas por tecnologia trabalhando juntinho com a gente!

Gosta de se desafiar e o desenvolvimento profissional é prioridade na sua carreira?

Está procurando aquele ambiente de trabalho com pessoas incríveis?

Gosta de autonomia e liberdade na hora de trabalhar?

Quer um ambiente de trabalho onde você está o tempo todo aprendendo?

Já sonhou em iniciar uma carreira a nível internacional?

Então seu lugar é aqui com a gente!

## Local

100% remoto

## Requisitos

**Requisitos Técnicos Necessários:**
- Domínio de React, incluindo React Hooks;
- Domínio de GraphQL;
- Fluência com Git;
- Facilidade com o formato de trabalho remoto;
- Ter experiência com planejamento e levantamento de requisitos;
- Boa gestão de tempo e organização pessoal;
- Inglês Intermediário;

**Você se destaca se possui:**
- Domínio de React Native;
- Conhecimento em testes de código;
- Conhecimento de metodologias ágeis;
- Experiência em projetos open-source;

**O perfil que procuramos tem:**
- Facilidade de comunicação;
- Capacidade Criativa;
- Prezar pela inovação nos projetos;
- Paixão pela programação;
- Gostar de trabalhar em formato mais independente;
- Capacidades autodidatas;
- Amar desafios;
- Estar sempre em busca de novas aprendizagens;

## Benefícios

- Contrato PJ, com benefícios a combinar
- Horários completamente flexíveis
- Rotina de trabalho 100% remota

## Contratação

PJ a combinar

## Como se candidatar

Preencha nosso formulário: https://l.jungsoft.io/frontend-position

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.

E-mail para contato em caso de não haver resposta: vagas@jungsoft.io

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
