### ISSUE TITLE
[Remoto] Front-End Developer React/React Native na Ruptiva

### ISSUE THREAD

**Issue by maikelfb** [frontendbr/vagas#3812]
# Sobre a Ruptiva
A Ruptiva desenvolve soluções personalizadas de acordo com a necessidade de nossos clientes. Cada aplicativo ou sistema é desenhado especificamente para cada negócio. Já trabalhamos com projetos nos mais variados segmentos, dentre eles no ramo de transporte, indústria, varejo e meios de pagamentos. Desde o desenho até o desenvolvimento, passamos por uma jornada bastante dinâmica de aprendizado contínuo da equipe.

Buscamos por profissionais que gostem de desenvolvimento de software e tecnologia em geral, que estejam atentos às novidades e em constante evolução, que tenham capacidade de inovar e propor soluções, bem como facilidade de trabalhar em grupo.

Em nosso ambiente de trabalho cultivamos bons laços de relacionamento e amizade - prezamos muito pela harmonia e bem-estar de nossa equipe.

## Modalidade
100% Remota

## Tipo de contratação
PJ

## Remuneração
Salário a combinar (compatível com o mercado)

## Atividades
Você será responsável por:
- Construir interfaces;
- Transformar designs e wireframes em código de qualidade;
- Construir componentes reutilizáveis;
- Manter e testar o código.

## Requisitos
- Pelo menos 1 ano de experiência em posição similar;
- React / React Native;
- Typescript;
- Redux;
- Ter familiaridade com as especificações mais recentes do ES6/ES7;
- Saber consumir APIs de forma otimizada (GraphQL é um diferencial);
- Saber aplicar testes automatizados em aplicativos mobile;
- Ter conhecimentos de design de interface e experiência do usuário;
- Saber versionar código e interagir com GIT;
- É um diferencial ter experiencia com métodos ágeis;
- Ser curioso e estudioso. 

## Diferenciais
- Docker;
- Firebase;
- Ruby on Rails;
- Node.js / Express;
- Metodologias Ágeis.

## Como se candidatar
Envie um e-mail com seu CV, links de projetos online e pretensão salarial para maikel@ruptiva.com com o assunto: Vaga Frontend React - Seu nome aqui

## Labels
- React
- React Native
- PJ
- Remoto

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
