### ISSUE TITLE
[São Paulo/SP] Front-end React Developer na ITeam

### ISSUE THREAD

**Issue by VivianeRHTI** [frontendbr/vagas#3813]
## Descrição da vaga

Desenvolvimento de soluções satélites web e mobile.

## Local

Local de trabalho: São Paulo/SP - Zona Oeste.
Não aceita remoto.

## Requisitos

Experiência profissional em projetos com React e React Native (Mobile).
Conhecimentos em HTML, CSS, Javascript.

## Contratação

Tempo indeterminado (Fixo).
PJ ou outro modelo á combinar.

## Nossa empresa

Há mais de 15 anos presente no mercado, a ITeam oferece o comprometimento com o cliente.
Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 
O relacionamento da ITeam é baseado no amplo comprometimento com os valores e objetivos dos nossos Clientes, fornecendo soluções e serviços de TI que contribuam para a realização de seus objetivos.

## Como se candidatar

Envie um e-mail para viviane.pereira@iteam.inf.br com seu currículo atualizado e pretensão de taxa/hora - enviar no assunto: Vaga no GITHUB - React - SP Presencial

## Labels

- 🏢 Horário comercial
- 🏢Presencial
- 👨 Pleno
- 👴 Sênior
- ⚖️ PJ ou á combinar

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by VivianeRHTI** [comment]
Está aberta ainda.
