### ISSUE TITLE
[Belo Horizonte] Javascript Developer na nata.house

### ISSUE THREAD

**Issue by izabelamonteiro002** [frontendbr/vagas#3815]
> Vaga Remota durante a pandemia

## Sobre a nata.house

Para nós, software house vai além da definição tradicional. Colaboração, espírito jovem, transparência, maturidade e excelência são os valores que nos guiam! Criamos produtos de software, tornando nossos os desafios de todos os clientes.

A *nata.house* é especializada no ecossistema JavaScript, trabalhando com React, React Native e NodeJS. Com isso, construímos um hub de desenvolvimento para nossos talentos e, por consequência, fortalecemos nossa cultura de qualidade de software.

Com forte crescimento nestes três anos de existência, nos preocupamos em construir um time com pessoas talentosas, alinhadas à cultura e aos objetivos da empresa. Além disso, buscamos constantemente maneiras de engajar, motivar e desenvolver os colaboradores para que seu crescimento acompanhe o da *nata*.

## Local

Belo Horizonte - remoto durante a pandemia.

## Requisitos

**Você precisa ter:**

- Conhecimento de JavaScript (preferencialmente trabalhando com React, React Native e/ou NodeJS)
- Paixão por desenvolvimento de software, prezando sempre pela qualidade e se dispondo a aprender e crescer contínuamente.

**Procuramos alguém que:**

- Seja capaz de resolver problemas, tenha proatividade e orientação para resultados;
- Têm interesse em fomentar um ambiente colaborativo para todos;
- Atua com autonomia, usando a liberdade para opinar em processos e questões relacionadas ao cliente quando for preciso;
- É capaz de se adaptar a ambientes dinâmicos e de colaborar em situações difíceis;
- Busca sempre adquirir novos conhecimentos;
- Aberto a novos pontos de vista e maneiras de pensar.

**Seria bom se você tivesse:**

- Noções de conceitos e ferramentas arquiteturais referentes ao ecossistema de aplicações back-end, além de uma análise crítica e pragmática para utilizá-las dependendo do contexto da solução;
- Capacidade de selecionar recursos de trabalho, tais como metodologias e ferramentas de desenvolvimento de sistemas, planejando etapas e ações de trabalho;
- Desejável conhecimento em Inglês.

## Benefícios

- Carga horária de 40 horas semanais, de segunda a sexta;
- Temos vale-refeição/alimentação Sodexo de R$ 22,05 por dia;
- Para a galera do busão, vale-transporte de acordo com a necessidade, ou, se preferir, auxílio combustível no valor de R$120, sem desconto em folha;
- Bônus anual, pois, afinal, crescemos juntos! Se a empresa tem lucro, o mérito é seu e parte do lucro também;
- Se você está se desenvolvendo e gerando resultado, por quê não receber proporcionalmente? Nada de ficar estagnado: temos plano de carreira bem definido;
- Who run the world? You! Temos incentivo ao aprendizado de inglês;
- Consultoria financeira com a Monetus;
- Segurança extra com o nosso Seguro de Vida.
- Lanche à vontade;
- Horário flexível;
- Um happy hour mensal pago pela empresa;
- Auxílio financeiro para cursos, eventos e capacitações;
- No dress code (be you!)

## Contratação

CLT

## Como se candidatar

Se interessou? Para se candidatar, basta preencher o [formulário](https://docs.google.com/forms/d/e/1FAIpQLSd9MC-1ee9Gn4gpOPSXzO4ATN7Jr8PKIeefUPPGD7YXc7Zb1w/viewform) e boa sorte! :)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: izabela.monteiro@natahouse.com

#### Alocação
- Alocado
- Remoto durante a pandemia

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by deeborges** [comment]
Currículo enviado com sucesso ! 
:D

**Comment by moutlender** [comment]
Acabei de mandar o meu currículo

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
