### ISSUE TITLE
[Rio de Janeiro] Freelancer Front-end Developer na Enter Sistemas

### ISSUE THREAD

**Issue by merciomedina** [frontendbr/vagas#3816]
## Nossa empresa

A Enter Sistemas é uma empresa focada no desenvolvimento de soluções para o mercado de marketing digital.
Estamos no processo de criação de plataforma específica para o mercado e contratando pessoas que tenham
vontade de participar de um projeto grandioso e desafiador.

## Descrição da vaga

Freelancer para finalização de projeto desenvolvido em ANGULAR.

## Local

Remoto ou Presencial na Barra da TIjuca. Rio de Janeiro.

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para atacoshi@entersistemas.com.br com seu CV anexado - enviar no assunto: Vaga Freelancer ANGULAR.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
