### ISSUE TITLE
[Rio de Janeiro/PRESENCIAL] Front-end Developer na Enter Sistemas

### ISSUE THREAD

**Issue by merciomedina** [frontendbr/vagas#3817]
## Descrição da Empresa
A Enter Sistemas é uma empresa focada no desenvolvimento de soluções para o mercado de marketing digital.
Estamos no processo de criação de plataforma específica para o mercado e contratando pessoas que tenham
vontade de participar de um projeto grandioso e desafiador.

## É fundamental que:
O analista desenvolva aplicações ReactJS;
Conhecer e desenvolver em NodeJS é um diferencial;
Tenha Disponibilidade em período integral;
Esteja disposto a aprender e ensinar. 
Compartilhar conhecimento é um diferencial.

## Requisitos
É ESSENCIAL ter experiência mínima de 3 anos;
Capacidade de tocar um projeto sozinho;
Cumprimento de prazos;
Estar envolvido em todo o processo de entrega;
Compartilhar e sugerir melhorias que tornem a plataforma mais competitiva;
Conhecer e implementar novos processos do GIT;
Experiência anterior com desenvolvimento em React e trabalhado em equipe;
Ter ótimo raciocínio lógico;
Ter foco e disciplina;
Conhecimento em UI Design;

## Local de trabalho
Barra da Tijuca/RJ

## Remuneração
Salário PJ de 5k a 7k;

** NÃO SERÃO CONSIDERADOS CURRÍCULOS DE DEVS JUNIOR  **

## Diferenciais
Bancos relacionais e não relacionais;
Estar sempre antenado as novidades do mercado;
Ser pró ativo e comprometido com os resultados;

## Contratação
Pessoa Jurídica.

## Como se candidatar
Por favor envie um email para atacoshi@entersistemas.com.br com seu CV anexado - enviar no assunto: Front-end Developer.

## Labels
🏢 Presencial
👨 PLENO
⚖️ PJ
💰 5k-7k

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
