### ISSUE TITLE
[São Paulo] Front-End Developer na Tera

### ISSUE THREAD

**Issue by mateushsantos** [frontendbr/vagas#3818]
## Nossa empresa

A Tera desenvolve jornadas de aprendizado para inovadores, criativos e sonhadores que querem fazer a diferença num mundo conectado, tecnológico e global. Com cursos imersivos de UX Design, Product Management, Data Science, Data Analytics, Data Leadership e Growth Marketing, que são liderados por uma rede de mais de 150 experts do mercado de tecnologia no Brasil.

## Descrição da vaga

Estamos contratando uma Desenvolvedora Front-end para participar do desenvolvimento, manutenção e criação de nossos produtos. Vaga exclusiva para mulheres.

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com Front-end
- Vue
- Testes de Integração e Unitários (JEST)
- SASS
- Experiência com ambiente de desenvolvimento (webpack, pré-processadores, bundlers, packages, transpiladores)

**Desejáveis:**
- Firebase (Firestore)

## Benefícios

- Faixa Salarial R$ 6.500
- Vale Refeição R$20,00/dia
- Plano de Saúde Allianz Saúde

**Diferenciais:**
- Bolsa de estudos nos cursos da Tera

## Contratação

CLT

## Como se candidatar

Por favor aplicar pela vaga no LinkedIn: [aqui!](https://www.linkedin.com/jobs/view/2269465435/)

## Tempo médio de feedbacks

Costumamos enviar feedbacks o mais rápido possível
E-mail para contato em caso de não haver resposta: mateus.santos@somostera.com

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by Eduruiz** [comment]
seguindo o link, acho que a vaga já está encerrada :)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
