### ISSUE TITLE
[São Paulo] Front-end Developer na ClickBus

### ISSUE THREAD

**Issue by albuquerque-apr** [frontendbr/vagas#3819]
> Vaga Remota durante a pandemia

## Nossa empresa

Venha ser um ClickBuser! 🚌 🚌 🚌

A ClickBus é a maior plataforma online de vendas de passagens rodoviárias no Brasil, temos como um de nossos valores o foco no cliente e por isso somos incansáveis na busca por inovação do setor.

Agilidade e ousadia está em nosso sangue, aqui levamos muito em conta a colaboração inclusive nosso processo seletivo é feito por todos os ClickBusers, somos todos responsáveis pela busca por novos integrantes para embarcar nesse busão acelerado!

IMPORTANTE: Durante a pandemia estamos trabalhando de Home Office, pois nossos ClickBusers são nosso maior ativo e cuidar deles é o que importa! Quando tudo isso passar, retornaremos ao escritório em São Paulo, seguindo todas as normas e sempre pensando na saúde de nossas pessoas.

Venha fazer parte dessa equipe que mesmo à distância dá um jeito de estar sempre unida!

#### Seu dia a dia no busão será incrível! Sua missão vai ser:

- Trabalhar com uma equipe de alto nível que busca sempre se desenvolver utilizando as melhores práticas e ferramentas;
- Propor inovações e implementar novas ideias de negócio para nossos viajantes;
- Desenvolver interfaces para viajantes que acessam a ClickBus via Web Desktop e Web Mobile;
- Atuar em conjunto com demais Frontends da ClickBus na evolução do ambiente e da tecnologia utilizada;
- Planejar em conjunto com o time a arquitetura mais adequada para novas entregas;
- Realizar pair programming e code review com membros da equipe.

## Local

Presencial: Vila Olimpia, São Paulo/SP

## Requisitos

- Experiência com algum framework PHP (Symfony, Laravel, Zend Framework, etc.);
- Experiência em React e/ou Vue;
- Conhecimentos em conceitos de SSR (Server Side Rendering);
- Conhecimento em JavaScript moderno (ES6+);
- Experiência em HTML5 e pré processadores CSS;
- Experiência em desenvolvimento de aplicações web e habilidades associadas (REST, HTTP, web services);
- Experiência com frameworks de testes unitários (usamos PHPUnit e Jest/Mocha) e de integração;
- Progressive Web App (PWA)
- Google AMP (AMP Project)
- Desejável experiência em desenvolvimento de sistemas de alta disponibilidade.
- Docker
- Git/GitHub
- Webpack/Gulp

## Benefícios

- Ambiente de trabalho descontraído, com espírito de equipe e pessoas talentosas;
- Incentivo e autonomia para trabalhar, desenvolver e implementar ideias;
- Empresa que valoriza a melhor versão de você mesmo;
- Vale Home Office de R$200,00/mês (benefício oferecido durante o período de pandemia)
- Frutas todos os dias;
- Café para quem é de café;
- Chá para quem é de chá;
- Horário flexível;
- Espaço para soneca (aquela recarga) e vídeo game;
- Vale refeição/alimentação de R$31,00/dia;
- Vale transporte;
- Gympass;
- Auxílio Creche para as mamães;
- Plano de saúde sem co-participação;
- Plano odontológico;
- Seguro de vida;
- Local de trabalho: Vila Olímpia próximo da estação.

## Contratação

CLT

## Como se candidatar

Por favor aplicar pela vaga pelo site [Kenoby](https://jobs.kenoby.com/clickbus)!

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 semana após cada processo.

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
