### ISSUE TITLE
[São Paulo] React Native Developer na UseBike

### ISSUE THREAD

**Issue by mstrcnvs** [frontendbr/vagas#382]
## Descrição da vaga

Desenvolvimento de aplicativo utilizando React Native.

## Local

Remoto ou Escritório em São Paulo - Centro

## Benefícios

- Horário flexível e negociável

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com JavaScript/ECMAScript 6
- 1 ano de experiência com React Native
- Conhecimento de REST APIs
- PJ/MEI

**Desejáveis:**
- GIT
- Desenvolvimento iOS

**Diferenciais:**
- Python
- HTML5/CSS3
- Animações SVG

## Contratação

PJ/MEI

## Nossa empresa

O UseBike é o aplicativo do ciclista urbano. São mais de 22.000 pontos de interesse cadastrados de forma colaborativo e mais de 1.500 rotas seguras traçadas por mês.

[Saiba mais no nosso site](http://usebikeapp.com)

## Como se candidatar

Por favor envie um email para contact@usebikeapp.com com seu portfólio anexado.
Enviar no assunto: Vaga React Native

**Comment by mtmr0x** [comment]
@mstrcnvs a vaga continua aberta?

**Comment by mstrcnvs** [comment]
Desculpe @mtmr0x.

A vaga foi fechada.

Abraço.

**Comment by gadielkalleb** [comment]
Não sei se por aqui é o melhor canal, mas tem um usuário aqui é no dia dez comentou 189 issues eu dou watch aqui nas vagas so desse cara tinha 189 emails, poxa se tá aberta a vaga não custa nada manda um email com seu currículo. Escreve aqui e depois manda isso é retrabalho. E não fica enchendo a. Caixa de email dos outros perguntando se a vaga tá aberta ou não. 

Tá lá aberta manda o email man se for pra será.

**Comment by LFeh** [comment]
@gadielkalleb Se estiver falando do @mtmr0x, ele é moderador e fez um trabalho para fechar as vagas que já não estão contratando. 

Era totalmente necessário para limpar vagas antigas ;)

**Comment by gadielkalleb** [comment]
Kkkk tranquilo. Eu estava esperando um email importante foi um pouco difícil de achar com um. Boom de emails, mas desculpa a gaff RS

**Comment by LFeh** [comment]
Entendo a overdose de e-mail, mas não existe outra maneira de fazer isso (ou não pensamos em nenhuma) 😄

**Comment by mstrcnvs** [comment]
A vaga foi reaberta.
