### ISSUE TITLE
[São Paulo] Front-end Developer na Supply Labs

### ISSUE THREAD

**Issue by godois** [frontendbr/vagas#3821]
## Nossa empresa

A SupplyLabs foi criada com o propósito de entregar uma experiência 100% para gestão de cadeia de suprimentos.
Nossa plataforma é responsável por toda gestão de compliance e sustentabilidade de uma cadeia de fornecimento.
Nosso time é composto por gente bacana, qualificada e amigável.
Nossos desafios como plataforma de software são imensos, desde qualidade de software, escalabilidade e reproveitamento de código, análise de dados, entre outros.
Como time, esperamos que os membros sejam disciplinados, colaborativos, humildes e honestos.
Esta é uma posição que exige dedicação exclusiva, e disponibilidade integral durante nosso horário de trabalho.

## Descrição da vaga

Estamos à procura de uma pessoa que integrará nosso time que desenvolve e é responsável pelo frontend da nossa plataforma.
Codificar o frontend será sua principal responsabilidade, onde terá total liberdade para aplicar as suas escolhas.
Ajudar na prototipação de produto.
Participar de discussões para levantamento de hipóteses de solução, nos ajudando a pensar novos produtos e novos módulos.
Participar ativamente de decisões de tecnologias, infraestrutura, etc.

## Local

Exemplo: Remoto

## Requisitos

**Obrigatórios:**
* Ter trabalhado em ao menos um projeto utilizando javascript ou ReactJS, e que seja um produto digital.
* Ser fluente com tecnologias como HTML, CSS e Javascript.
* Saiba consumir APIs REST de forma otimizada.
* Saiba versionar código e interagir com GIT.
* Gostar de trabalhar em grupo, ter empatia e humildade para liderar discussões.
* Ser curioso e estudioso.
* Ter lado analítico, preocupado com a ciência por trás das decisões.

**Diferenciais:**
* Que tenha noções de testes automatizados em aplicativos web.
* Ter atuado em outras startups é um diferencial.

**Diferenciais:**
- Ambiente descontraído de trabalho e em plena expansão;
- Full time home-office;

## Contratação
PJ a combinar

## Como se candidatar
Envie um e-mail para rh@supplylabs.com.br, com assunto: Vaga Desenvolvedor ReactJs;
Inclua portfolio, repositório Github, currículo, Linkedin e todo material que demonstre seu nível técnico e histórico profissional e acadêmico;
Conte na mensagem o quê lhe interessou na vaga;
Informe sua pretensão salarial;

## Tempo médio de feedbacks

Processo Seletivo 100% online;
Análise do material enviado ou referenciado no e-mail de candidatura;
Conversa para conhecer a(o) candidata(o), e para apresentar a empresa;
Conversa sobre engenharia de software;
Teste de codificação;
Conversa com os gestores e o time dev;

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior

**Comment by raulfranck** [comment]
Aplicado 👍

**Comment by vitorrubim1** [comment]
Opa, email enviado :)
