### ISSUE TITLE
[ Florianópolis ] Front-end Developer VueJS @ Art Lab

### ISSUE THREAD

**Issue by artlabr** [frontendbr/vagas#3822]
> Vaga Presencial

## Sobre a Artlab.dev

Venha fazer parte do nosso time da Art Lab!

Apaixonados por tecnologia somos um laboratório de Startups (modelo Venture Builder), que cria ou investe em novas startups através dos nossos próprios recursos, usufruindo da nossa estrutura, rede e conhecimento compartilhado.

Agilidade e inovação fazem parte do nosso sistema, aqui levamos muito em conta a participação do time com ideias e sugestões de cada membro.

Buscamos o trabalho com pessoas que são apaixonadas pelo que fazem, com brilho nos olhos na busca para desenvolver sempre o melhor entregando cada vez mais valor aos projetos.

Vamos inovar juntos? Faça parte do nosso time!

## Descrição da vaga

Vaga de desenvolvedor para trabalhar em plataforma Web em VueJS (SPA) que utiliza modelo de negócio SaaS, com modelo PWA, arquitetura Serveless (Backed by Google Firebase) e banco de dados não relacional (Firestore).

## Local

Escritório - Presencial - Centro - Florianópolis - Santa Catarina.

## Requisitos

**Técnico Necessários:**
- Conhecimento de JavaScript (com experiência comprovada em VueJS, Vuex e  NodeJS);
- Conhecimento de Firebase (Auth,  Firestore, Functions e Storage);
- Pelo menos 2 anos de experiência comprovada com desenvolvimento web;
- Paixão por desenvolvimento de software, prezando sempre pela qualidade.

**Interpessoal:**
- Ser capaz de resolver problemas, ter proatividade e orientação para resultados;
- Fomentar um ambiente saudável e colaborativo para todos;
- Ser capaz de se adaptar a ambientes dinâmicos e de colaborar em situações difíceis;
- Buscar sempre adquirir novos conhecimentos;
- Ser aberto a novos pontos de vista e maneiras de pensar.

**Desejável:**
- Noções de conceitos e ferramentas arquiteturais referentes ao back-end, além de uma análise crítica e lógica para utilizá-las dependendo da solução;
- Noção de aplicações PWA (Progressive Web App).
- Familiaridade com metodologias e ferramentas ágeis de desenvolvimento de sistemas, como SCRUM por exemplo;
- Conhecimento em Inglês.

## Benefícios

- Carga horária de 40 horas semanais, de segunda a sexta;
- Ambiente de trabalho descontraído, com espírito de equipe e pessoas talentosas;
- Incentivo e autonomia para trabalhar, desenvolver e implementar ideias;
- Plano de carreira bem definido;
- Horário flexível;
- Sem exigência de vestuário (Dress code).

**Diferenciais:**
- 2 horas de almoço

## Contratação

Contrato de trabalho para PJ (a combinar)

## Como se candidatar

Para se candidatar, basta enviar um email com currículo anexo para lab.art.br@gmail.com - enviar no assunto: Vaga VueJS

## Tempo médio de feedbacks

Enviaremos, para os candidatos selecionados e que atendam os requisitos necessários para a vaga, um feedback em até 5 dias após cada processo.

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by artlabr** [comment]
@felipefialho Boa tarde Felipe, você poderia trocar o label São Paulo por Florianópolis. A vaga é para Santa Catarina. Obrigado.

**Comment by highlabs** [comment]
@artlabr A vaga tem a label "remoto", mas na descrição diz apenas presencial. Qual é o correto?

**Comment by artlabr** [comment]
> @artlabr A vaga tem a label "remoto", mas na descrição diz apenas presencial. Qual é o correto?

Olá. Os labels foram adicionados automaticamente e provavelmente deu algum bug (não era para apareces nem São Paulo, nem Remoto). A vaga é para trabalho alocado presencial na cidade de Florianópolis, Santa Catarina.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
