### ISSUE TITLE
[São Paulo] Front-End Developer no Chopp Brahma Express | Ambev

### ISSUE THREAD

**Issue by vfcoelho** [frontendbr/vagas#3826]
> Vaga Remota durante a pandemia

## Nossa empresa

Nossa **gente** aqui na **[Ambev](https://www.ambev.com.br/)** sonha **GRANDE**! Somos milhares de apaixonados pelo que fazemos. Nosso maior objetivo é inovar no setor de bebidas com a maior qualidade e diversidade possível, para que você possa brindar qualquer ocasião escolhendo o que mais gosta!

A nossa **Cultura** é focada em construir um ambiente inclusivo e colaborativo, onde as pessoas possam ser o melhor delas mesmas! Gente é o nosso maior ativo, afinal sabemos que investir no potencial de nossos colaboradores é trazer ainda mais qualidade ao nosso negócio e às nossas bebidas. Por isso, estamos sempre em busca de **talentos diversos**, dispostos a construir esse grande sonho com a gente de unir as pessoas por um mundo melhor.

Prazer, somos a **Ambev** e adoraríamos te ter com a gente.

**Cheers!**

## Descrição da vaga

Procuramos profissionais para auxiliar na criação e manutenção de funcionalidades para o nosso [E-Commerce de cerveja](https://www.choppbrahmaexpress.com.br/), utilizando-se de suas habilidades em programação e de ideias criativas! A atuação contará com alta proximidade e sinergia com outras áreas. Buscamos alguém com sentimento de dono(a), que terá responsabilidade e autonomia sobre as funcionalidades implementadas, tendo a oportunidade de impactar um grande número de usuários.

- Utilizar tecnologias Frontend para desenvolver as features alinhadas com o time, assegurando os requisitos da equipe de negócio e gerando valor para os usuários
- Trabalhar com o Designer UI/UX, auxiliando no planejamento de novas funcionalidades
- Definir estratégias para comportamentos de elementos;
- Auxiliar na operação das ferramentas de suporte ao negócio como Google Analytics
- Conhecimento de plataforma de eCommerce Vtex.IO
- Trabalhar com Desenvolvedores Backend no planejamento e construção de funcionalidades do site

## Local

Escritório, SP, São Paulo, Itaim Bibi

## Requisitos

**Obrigatórios:**

- HTML, CSS, Javascript
- React
- Consumo de APIs REST
- Desenvolvimento de Páginas Responsivas para Mobile e Desktop
- Inglês Intermediário

**Desejáveis:**

- Consumo de APIs GraphQL

**Diferenciais:**

- Experiência com VTEX e VTEX IO

## Benefícios

- Plano de saúde SulAmerica;
- Plano odontológico OdontoPrev;
- Seguro de vida;
- Previdência Privada;
- Vale transporte;
- Vale refeição;
- Auxílio creche;
- Descontos em medicamentos;
- Licença maternidade e paternidade extendidas;
- Auxílio material escolar;
- Assessoria financeira, jurídica e psicológica para funcionários;
- Gympass;
- Descontos expressivos em produtos e estabelecimentos Ambev;
- 14º salário;
- Remuneração variável anual (bônus) competitiva

**Diferenciais:**

- Geladeira abastecida com as melhores marcas;
- Frutas frescas no escritório;
- Horário flexível;

## Como se candidatar

Acesse nossa vaga por **[aqui](https://ambev.gupy.io/jobs/564765)**

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
