### ISSUE TITLE
[REMOTO][PCD][Auditivo] Front-end React / React Native PCD Auditivo na RockApps

### ISSUE THREAD

**Issue by erickne** [frontendbr/vagas#3828]
## Descrição da vaga

Buscamos novos desenvolvedores/consultores de nível **JÚNIOR** e **PLENO** para compor o time tecnológico. As vagas serão para React Native e / ou ReactJS.

A principais atividades serão:
- Desenvolvimento de novas interfaces em React Native;
- Avaliação e Experiência do Usuário;
- Desenvolvimento e execução de testes.

## Local

- 100% Remoto
- Horário comercial

## Requisitos

**Obrigatórios:**
- **Pessoa com Deficiência - Surdo**
- Experiência em ReactJS ou React Native
- Ótima comunicação escrita

**Desejáveis:**
- Conhecimentos em criação e execução de teste em **ReactJS** e **React Native**
- Conhecimento na biblioteca Expo

**Diferenciais:**
- Conhecimento em CI/CD (Jenkins, Fastlane)
- Experiência em utilização do Figma

## Contratação

PJ a combinar

## Nossa empresa

Desenvolvimento ágil e profissional de produtos e ideias, utilizando modernas tecnologias através de um modelo de custos acessível e flexível. A atuação de nossa empresa busca personalizar projetos e  aplicações integrar soluções aos sistemas pré-existentes de nossos clientes. Sempre atualizados com as novas tecnologias de mercado, trazemos conosco aplicações inovadoras que certamente atenderão sua necessidade. Hoje em dia, a RK se consolidou no mercado, possuindo mais de 50 clientes e mais de 60 softwares e aplicativos criados. Realizações que nos mantém em andamento.

## Como se candidatar

Por favor envie um email para carreiras@rockapps.com.br com seu CV anexado - enviar no assunto: Vaga React Native

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Júnior
- Pleno

**Comment by garciamendes** [comment]
Olá, tudo bem? A vaga é especifica para pessoas com deficiência?

**Comment by erickne** [comment]
Olá Matheus.

Sim, a vaga é específica para PCD.

Abraços,

Erick Engelhardt

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
