### ISSUE TITLE
[Remoto] Front-end Developer na CODEROCKR

### ISSUE THREAD

**Issue by ricardosaraiva** [frontendbr/vagas#3829]
## CODEROCKR

A Coderockr acredita que o desenvolvimento de sistemas e aplicativos é uma arte, que deve ser feita com paixão e dedicação. Bons programadores são únicos, assim como estrelas no mundo do rock, e é nesse ritmo que fazemos aplicações Web e Mobile.

O candidato(a) fará parte de uma equipe multidisciplinar, onde todos colaboram com postura entusiasta, paixão por tecnologia e inovação, e ampla experiência em desenvolvimento Web e Mobile.

##  Descrição da vaga

- Seja proativo(a), analisando e compreendendo os impactos e reais necessidades por trás das suas entregas;
- Tenha responsabilidade pelo que você produz e entrega. (Ownership mindset);
- Acredite que pode obter melhores resultados trabalhando em equipe;
- Saiba se comunicar abertamente, participando de debates saudáveis, trazendo ideias que contribuam para o seu sucesso, e o da equipe;
- Tenha capacidade de entender Produtos & Negócios. Nosso objetivo maior sempre é a entrega de valor, indo muito além de apenas criar um código bonito;
- Seja versátil: Você entende como todas as peças se conectam (front-end, back-end, database, camadas de rede, etc) e como isso impacta a performance do seu código/aplicação);
- Seja capaz avaliar e aprender sobre novas tecnologias e ferramentas.

## Local

- 100% Remoto

## Requisitos

**Obrigatórios:**
- Conhecimento prático em HTML5 e CSS3 Responsivo.
- Conhecimento avançado de JavaScript.
- Desenvolvimento cross-plataforma e testes cross-browser.
- Confortável trabalhando com o controle de versão (Git).
- Capacidade de trabalhar de forma independente com uma supervisão mínima.
- Experiência de trabalho com APIs, ou integrar uma API de terceiros ou criar o seu próprio, quando necessário.
- Conhecer pré-processadores CSS como Less, Sass e Stylus.
- Conhecer os frameworks JS como React, React Native, ou VueJS.
- Atenção à detalhes na implementação de layouts.

**Diferenciais:**

- Experiência com sistemas de build (Bash, Grunt, Make, Ant)
- Conhecimento básico de pelo menos uma linguagem server side (Python, PHP, Node.js, Ruby, Go, etc)
- Experiência com UI e UX;

## Benefícios

- Plano de Saúde: Unimed Nacional 100% de um plano de 50% de co-participação;
- Seguro: 50% de um seguro de vida, caso optado;
- Horário flexível: 40 horas semanais, com flexibilidade perante acordo prévio entre a equipe;
- Plano de Carreira: publico e transparente: https://github.com/Coderockr/carreira
- Bônus Anual: Baseado no impacto de suas contribuições;
- Aprendizado: Evento interno trimestral para apresentação de palestras, hackathons e ações sociais;
- Cultura: Eventos internos de confraternização;
- Budget para Educação: R$ 2.000/ano para serem usados em cursos, palestras, ou livros. Apoio no aprendizado de idiomas.

## Contratação

CLT

## Como se candidatar

https://careers.smartrecruiters.com/Coderockr

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by vitorrubim1** [comment]
Opa, email enviado :)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by ricardosaraiva** [comment]
Ainda temos vagas em aberto
