### ISSUE TITLE
[São Paulo] WebGados -Full Stack Developer (Node.JS)

### ISSUE THREAD

**Issue by workstein** [frontendbr/vagas#383]
## Empresa
WebGados: A primeira e única plataforma online integrada para vender e comprar o melhor em gado de corte e leite, equídeos, ovinos, caprinos, maquinários agrícolas, caminhões, propriedades rurais, produtos e serviços através do seu computador ou smartphone.

Site: https://webgados.com.br

## Descrição da vaga

Desenvolvimento e Manutenção do site/api WebGados

## Local

Escritório em São Paulo - Vila Leopoldina

## Horário

9h as 18hs ou 8h as 17hs

## Requisitos

**Obrigatórios:**
- Nível Pleno ou Sênior
- 2 anos de experiência com Node
- 2 anos de experiência com mongodb e express

**Desejáveis:**
- conhecimentos em vue.js

**Diferenciais:**
- Mentalidade Startup, construir a empresa e crescer junto com a empresa.

## Contratação

PJ (R$ 5.000,00 ~ R$ 7.000,00)

## Como se candidatar

Por favor envie um email para gabriel.stein@webgados.com.br com seu CV anexado - enviar no assunto: Vaga NodeJS

**Comment by danielrohers** [comment]
Remoto ou apenas presencial?
