### ISSUE TITLE
[Remoto/Florianópolis] Front-end Developer(Javascript/Angular) na Neoprospecta

### ISSUE THREAD

**Issue by rodrigomarchena** [frontendbr/vagas#3830]
> Vaga Remota durante a pandemia

## Nossa empresa

Somos uma empresa de biotecnologia dedicada à geração de conhecimento e inteligência para a tomada de decisões. Desenvolvemos e comercializamos análises microbiológicas inovadoras, baseadas em sequenciamentos de DNA de nova geração, análises biocomputacionais e técnicas de PCR.
[https://www.neoprospecta.com](https://www.neoprospecta.com)

## Descrição da vaga

É Front-end Developer e quer trabalhar em uma empresa inovadora de biotecnologia? Mora em Florianópolis ou tem vontade de mudar para a Ilha do Silício?
A Neoprospecta está com oportunidades abertas!
RESPONSABILIDADES:
– Ter princípios como os de crescimento em equipe, foco em gerar resultado, autogerenciamento, e colocando o cliente sempre em primeiro lugar.
– Desenvolver Front-end para sistemas para suportar fluxos de trabalhos internos e externos com os nossos clientes;
– Desenvolver interfaces dinâmicas para visualização de dados microbiológicos e genéticos;

CARACTERÍSTICAS:
– Escrever código organizado e fácil de entender;
– Trabalhar com metodologia ágil;
– Proativo;
– Ter excelência na leitura em inglês;

## Requisitos

– Ensino superior em área de sistemas ou afins (ou mínimo de 3 anos de experiência profissional);
– Experiência com algum framework Front-end (Angular, React, Vue, etc);
– Experiência com Javascript, Typescript, HTML5, CSS, SASS;
– Experiência com Design Responsivo e boas habilidades com CSS é imprescindível.
– Experiência com APIs REST;
– Experiência com Linux e Git;

## Local

*A oportunidade é para moradores de Florianópolis ou com pretensão de mudança para a cidade.
Remoto durante a pandemia / Presencial (com dias remotos na semana)

## Benefícios e Diferenciais

- Vale-Transporte, Plano de Saúde (CLT)
- Flexibilidade de horário (Equipe auto gerenciável)
- Salários compatíveis com o mercado
- Catálogo de cursos de TI e possibilidade de adquirir novos mensalmente

## Contratação

- Contrato CLT ou PJ, valor à combinar

## Como se candidatar

Responder o formulário:
https://forms.gle/rL26y4n6B434WCat9

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior

**Comment by rodrigomarchena** [comment]
@felipefialho os emails não chegaram pros inscritos acho :( sabe o que pode ter ocorrido de errado?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
