### ISSUE TITLE
[Itaperuna - RJ] Front-end Developer na Nome da Empresa

### ISSUE THREAD

**Issue by carlosoliveiradev** [frontendbr/vagas#3835]
> Vaga Remota durante a pandemia

## Nossa empresa

Nascemos da expertise de transformar pessoas em influencers digitais, através do melhor que elas têm a oferecer. Transformo marcas e pessoas em expressões digitais, através de uma metodologia própria.

## Descrição da vaga

Desenvolvimento de Landing Pages com foco em lançamentos (LP de captura, Blog de lançamento, LP de Vendas, etc)

## Local

Exemplo: Remoto ou Escritório, RJ, Itaperuna, Aeroporto

## Requisitos

**Obrigatórios:**
- Experiência com: Wordpress, PHP, CSS, JavaScript
## Contratação

A combinar

## Como se candidatar

Por favor envie um email para carlosoliveira@inovany.com.br com seu CV anexado - enviar no assunto: Vaga FrontEnd

E-mail para contato em caso de não haver resposta: tequero@inovany.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- Freela
- PJ

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
