### ISSUE TITLE
[Remoto] FullStack Developer na Ribon 

### ISSUE THREAD

**Issue by rodriggochaves** [frontendbr/vagas#3837]
## Ribon

Somos uma startup de impacto social de Brasília que trabalha com experiência de doação digital. Atualmente trabalhamos através de um aplicativo Android e iOS que conta com uma comunidade de mais de 34 mil usuários que doam de forma rotineira. Recentemente alcançamos o marco de 8 milhões e 700 mil doações realizadas. 

## Descrição da vaga

Nosso time está cada vez mais engajado em trazer a equidade racial para nosso ambiente de trabalho. Para que possamos dar um grande passo nesse trajeto estamos lançando essa vaga exclusiva para pessoas pretas. 

Estamos buscando uma pessoa para trabalhar na área de desenvolvimento da Ribon, hoje temos uma API em Ruby on Rails e um app em React. 

## Local

Remoto. 

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento de testes;
- Experiência com desenvolvimento de APIs;
- Ser proativo, adaptativo e trabalhar bem com incertezas;
- Se auto declarar uma pessoa preta. 

**Desejáveis:**
- Experiência com Ruby on Rails;
- Experiência com React;
- Experiência de trabalho com designers e metodologias ágeis.

## Benefícios

- Trabalho remoto
- Férias remuneradas de 20 dias úteis por ano
- Décimo terceiro
- Licença maternidade e paternidade de 6 meses

## Contratação

PJ - R$5.000,00 a R$15.000,00/mês

## Como se candidatar

[Preencha esse form](https://app.pipefy.com/public/form/kv0jC__O)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após a submissão.
E-mail para contato em caso de não haver resposta: rods@ribon.io

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
