### ISSUE TITLE
[Remoto/Florianópolis] Full-stack Developer(Python/Javascript) na Neoprospecta

### ISSUE THREAD

**Issue by rodrigomarchena** [frontendbr/vagas#3838]
> Vaga Remota durante a pandemia

## Nossa empresa

Somos uma empresa de biotecnologia dedicada à geração de conhecimento e inteligência para a tomada de decisões. Desenvolvemos e comercializamos análises microbiológicas inovadoras, baseadas em sequenciamentos de DNA de nova geração, análises biocomputacionais e técnicas de PCR.
[https://www.neoprospecta.com](https://www.neoprospecta.com)

## Descrição da vaga

É Full-Stack Developer(DE VERDADE) e quer trabalhar em uma empresa inovadora de biotecnologia? Mora em Florianópolis ou tem vontade de mudar para a Ilha do Silício?
A Neoprospecta está com oportunidades abertas!

RESPONSABILIDADES:
– Ter princípios como os de crescimento em equipe, foco em gerar resultado, autogerenciamento, e colocando o cliente sempre em primeiro lugar.
– Desenvolver Frontend e Backend para sistemas para suportar fluxos de trabalhos internos e externos com os nossos clientes;
– Desenvolver interfaces dinâmicas para visualização de dados microbiológicos e genéticos;
– Manter aplicações e integrações em nuvem;
– Manter alto volume de dados de forma segura e otimizada;

CARACTERÍSTICAS:
– Escrever código organizado e fácil de entender;
– Trabalhar com metodologia ágil;
– Proativo;
– Ter excelência na leitura em inglês;

## Requisitos

– Ensino superior em área de sistemas ou afins (ou mínimo de 3 anos de experiência profissional);
– Experiência com Python (Framework Django ou Flask);
– Experiência com Banco de Dados Postgres ou MySQL;
– Experiência com algum framework Frontend (Angular, React, Vue, etc);
– Experiência com Javascript, Typescript, HTML5, CSS, SASS;
– Experiência com APIs REST (Desenvolvimento e Integração);
– Experiência com Linux e Git;
– Experiência com Cloud Computing (AWS, GCloud);
– Experiência com Testes Unitários;
– Experiência com APIs REST (Desenvolvimento e Integração);
– Experiência com Linux e Git;

## Local

*A oportunidade é para moradores de Florianópolis ou com pretensão de mudança para a cidade.
Remoto durante a pandemia / Presencial (com dias remotos na semana)

## Benefícios e Diferenciais

- Vale-Transporte, Plano de Saúde (CLT)
- Flexibilidade de horário (Equipe auto gerenciável)
- Salários compatíveis com o mercado
- Catálogo de cursos de TI e possibilidade de adquirir novos mensalmente

## Contratação

- Contrato CLT ou PJ, valor à combinar

## Como se candidatar

Responder o formulário:
[https://docs.google.com/forms/d/e/1FAIpQLSfeAdUxupbib13GRuKkwiyyRq3Ib9lmVPr-CEbO_AYSWPg1Eg/viewform](https://docs.google.com/forms/d/e/1FAIpQLSfeAdUxupbib13GRuKkwiyyRq3Ib9lmVPr-CEbO_AYSWPg1Eg/viewform)

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
