### ISSUE TITLE
[São Paulo] - Front-End Developer Pleno na Foster

### ISSUE THREAD

**Issue by ogilvy-subscriptionsbrazil** [frontendbr/vagas#384]
## Descrição da vaga
Buscamos um Front-end para fazer parte do time de produção digital aqui na Foster. Esta equipe atua exclusivamente atendendo os projetos da Agência Ogilvy.

## Local
R. Maestro Cardim, 1293 - Bela Vista, São Paulo - SP

## Benefícios
- Vale Transporte
- Vale Refeição ou Vale Alimentação
- Seguro de Vida
- Plano de Saúde SulAmérica

## Requisitos

**Obrigatórios:**
- HTML5;
- CSS3 (Desenvolvimento responsivo e compatibilidade cross-browser)
- Pré-processadores CSS (Sass + Compass) e Frameworks CSS (Bootstrap, Bulma e etc...)
- Javascript
- Integração com Web Services RESTFUL
- Experiência com Frameworks SPA (AngularJS, Vue e etc...)
- Orientação a objetos
- Código limpo e organizado
- Task Runners (Gulp ou Grunt)
- Git (Command Line)
- Photoshop para recorte de assets

**Desejáveis:**
- Node.js
- Phonegap ou Ionic
- Noções de PHP

**Diferenciais:**
- Typescript
- ES6

## Contratação
CLT Full

## Nossa empresa
A Foster é uma agência que desde 1993 é referência no cenário digital. Hoje uma empresa do grupo WPP. Sua especialidade é analisar e entender o que as pessoas e as empresas querem fazer online. Seus serviços incluem criação de portais, mobile marketing, aplicativos mobile, estratégias/campanhas em redes sociais.

## Como se candidatar
Por favor envie um email com o assunto (Front-End Developer Pleno) para frontend@fosterasp.com.br com as seguintes informações:
- CV
- Pretensão Salarial
- Links: Portfolio, projetos, github e etc...

**Comment by ecouto** [comment]
Não custa tentar rs, enviado.
 Obs.: o site www.fosterasp.com.br aqui não esta entrando, esta dando erro.

**Comment by mtmr0x** [comment]
@ogilvy-subscriptionsbrazil a vaga continua aberta?

**Comment by ogilvy-subscriptionsbrazil** [comment]
@mtmr0x, a vaga ainda não foi preenchida.
