### ISSUE TITLE
[São Paulo/SP] Front-end Developer na ITeam

### ISSUE THREAD

**Issue by VivianeRHTI** [frontendbr/vagas#3840]
## Descrição da vaga

Desenvolvimento front-end em angular 7, para uma aplicação desenvolvida on cloud, consumindo backlog de melhorias, bem como a implementação de novas funcionalidades.

## Local

Local de trabalho: Inicialmente remoto e após pandemia presencial em São Paulo/SP.

## Requisitos

Experiência em Desenvolvimento de aplicações frontend, utilizando linguagem Angular 2, 5, 6 ou 7.
Desenvolvimento WEB (HTML, CSS, Javascript, JQuery, TypeScript);
Conhecimento em arquitetura de microserviços;
APIs REST, Webservices, e Json;
Experiência em controle de versionamento com Git;
Experiência com testes unitários;
Bancos de dados MySQL, MongoDB e DinamoDB;
Familiaridade com ambientes de Cloud Computing, preferencialmente AWS; API Gateway.

## Contratação

2 meses
PJ ou outro modelo á combinar.

## Nossa empresa

Há mais de 15 anos presente no mercado, a ITeam oferece o comprometimento com o cliente.
Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 
O relacionamento da ITeam é baseado no amplo comprometimento com os valores e objetivos dos nossos Clientes, fornecendo soluções e serviços de TI que contribuam para a realização de seus objetivos.

## Como se candidatar

Envie um e-mail para viviane.pereira@iteam.inf.br com seu currículo atualizado e pretensão de taxa/hora - enviar no assunto: Vaga no GITHUB - Front Angular

## Labels

- 🏢 Horário comercial
- 🏢Remoto e depois presencial
- 👨 Pleno
- 👴 Sênior
- ⚖️ PJ ou á combinar

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
