### ISSUE TITLE
[Campinas/SP] Desenvolvedor(a) Front-End @wavy

### ISSUE THREAD

**Issue by fabio-talles** [frontendbr/vagas#3841]
A Wavy é uma empresa focada em AI e precisa de pessoas resilientes e apaixonadas em criar/definir tendências tecnológicas e alcançar a missão de oferecer um atendimento ao consumidor excelente surpreendendo através de dados.

Nível: **Pleno**

Local:  Campinas - SP 

Contratação: CLT pela Wavy.

**Requisitos:**

Experiência sólida em tecnologias de desenvolvimento front-end (Javascript, HTML e CSS)
Experiência prática com framework Javascript de mercado (**Angular**)

**Diferenciais:**

Conhecimento sobre programação funcional;
Conhecimento de ferramenta para controle de estado de aplicações web (NgRx, Redux, Vuex, etc);
Conhecimento de linguagens do back end;
Afinidade com dados.

Fazer o cadastro no seguinte site: https://byintera.in/1l2 
Dúvidas: https://www.linkedin.com/in/marcelo-de-andrade-08b231197/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
