### ISSUE TITLE
[São Paulo] Full Stack Developer na houpa!

### ISSUE THREAD

**Issue by AninhaMelo** [frontendbr/vagas#3843]
Estamos contratando!! ⚠️🥳

Programador Full Stack

DESCRIÇÃO:
- Desenvolver e realizar manutenções em API's estruturadas em PHP;
- Manipular dados e criar schemas em mysql;
- Criar interfaces com base em protótipos do Adobe XD;
- Dar manutenção em telas existentes em ReactJS e AngularJS.

QUALIFICAÇÕES:
- PHP;
- ReactJS e/ou AngularJS.

DESEJÁVEIS:
- Conhecimento em React Native;
- Conhecimento em git;
- Ter conhecimento de como funciona uma Startup;
- Saber trabalhar em equipe;
- Ser proativo;
- Ter pensamento analítico.

IMPRESCINDÍVEL:
- Humildade e vontade de aprender!!!

Se identificou? Envie seu currículo para rh@houpa.app ou chama no WhatsApp (11) 98926-3398 junto à sua pretensão salarial.
Local de Trabalho: São Paulo.

Vem pro houpa! 💜

**Comment by AninhaMelo** [comment]
@felipefialho como eu adiciono as labels?😅

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
