### ISSUE TITLE
[Belo Horizonte/MG] Front-end Developer na Evob

### ISSUE THREAD

**Issue by rhrfonseca** [frontendbr/vagas#3846]
> Vaga Remota durante a pandemia

## Nossa empresa

A EVOB é uma empresa de soluções em educação para o mercado da beleza. Nosso principal objetivo é facilitar o acesso à educação, democratizar o conhecimento e contribuir para o desenvolvimento do setor através de tecnologia. Nossas soluções conectam produtores de conteúdo, grandes marcas e profissionais do setor, possibilitando a venda e gestão de cursos e eventos presenciais e online.

## Atividades
- Implementar novas funcionalidades com React
- Implementar testes automatizados
- Integração da plataforma com APIs
- Propor melhorias e novas funcionalidades

## Local

Remoto enquanto durar a pandemia, escritório + remoto após.

## Requisitos

**Obrigatórios:**
- Experiência de pelo menos 2 anos com React
- Experiência com CSS e técnicas responsivas de desenvolvimento

**Desejáveis:**
- Experiência com testes automatizados
- Git/Gitflow

**Diferenciais:**
- Conhecimento de backend (Rails/ NodeJS)
- Experiência com AWS
- Experiência com times ágeis

## Contratação

PJ

## Salário
- Júnior: R$3.000 a R$5000
- Pleno: R$5.000 a R$7.500

## Como se candidatar

Envie um email para rafael@evob.com.br com seu CV anexado - enviar no assunto: Vaga Frontend

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

**Comment by vitorrubim1** [comment]
Email enviado :)

**Comment by vitorrubim1** [comment]
Olá agradeço a oportunidade de realizar o teste, não consegui realizar todas funcionalidades mas estou bem feliz com o que consegui fazer, dei o meu máximo, e apesar de tudo foi uma conquista pessoal, até mesmo por não ter tanta familiaridade com React Native 🙂

Link do repositório no Github: https://github.com/vitorrubim1/ecommerceGameApp/tree/master/ecommerceGamer
________________________________
De: Rafael Fonseca <notifications@github.com>
Enviado: segunda-feira, 30 de novembro de 2020 15:08
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: Vitor Rubim <vitorrubim1@hotmail.com>; Comment <comment@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [Belo Horizonte/MG] Front-end Developer na Evob (#3846)


Closed #3846<https://github.com/frontendbr/vagas/issues/3846>.
