### ISSUE TITLE
[Rio de Janeiro] Front-end Developer Júnior  na Fattoria Web

### ISSUE THREAD

**Issue by CarolPimentel** [frontendbr/vagas#3847]
> Vaga Remota durante a pandemia (presencial após a pandemia).

## Nossa empresa
Somos uma empresa com sólida experiência no mercado digital. Desenvolvemos sistemas e app, planejamento de campanha de marketing digital e outsourcing. 

## Descrição da vaga

Participar do desenvolvimento front-end de projetos de pequeno e grande portes. Atuação no desenvolvimento de interfaces gráficas, funcionalidades de sites e app, levando em conta uma melhor interação com o usuário.
Atuação com equipe de Web Designers e Back-end.

## Local
Remoto apenas enquanto durar a pandemia e Escritório, [RJ], [RIO DE JANEIRO], [CENTRO]

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento em HTML, CSS, JavaScript (intermediário) e JQuery (Intermediário);
- Conhecimentos em Git e SASS (básico);

**Desejáveis:**
- Conhecimentos avançados em Javascript;
- Conhecimentos básicos em Adobe XD, Sketch;
- Conhecimentos em SVG, NodeJS, Gulp.

## Benefícios
- Plano de saúde Golden Cross - Nacional 
- Seguro de vida em grupo
- VR de R$ 26,10/dia
- VT ( após retomada do trabalho presencial)

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um email para rh@fattoriaweb.com.br com seu CV anexado - 
Enviar no assunto: Vaga RJFrontJR

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver respostas entrar em contato através do mesmo email.

#### Alocação
- Remoto enquanto durar a pandemia.

#### Regime
- CLT

#### Nível
- Júnior

Boa sorte!!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
