### ISSUE TITLE
[São Paulo] Front-end Developer na [Alfacon]

### ISSUE THREAD

**Issue by CamillaMoriya** [frontendbr/vagas#3848]
<!--
==================================================
Caso a vaga for remoto durante a pandemia deixar a linha abaixo
==================================================

## Nossa empresa

Acreditamos que a educação muda as pessoas! E as pessoas mudam o mundo!
Através da tecnologia, fornecemos a oportunidade de realizar sonhos, transformando a vida de milhares de pessoas diariamente.

## Descrição da vaga

Desenvolver soluções com foco em qualidade e disponibilidade e melhores padrões de Arquitetura, com foco na usabilidade

## Local

Escritório, [São Paulo], [São Paulo], [Bela Vista]

## Requisitos

**Obrigatórios:**
- 1 ano de experiência com UX ou UI design
- 1 ano de experiência com Angular 2+
- 1 ano de experiência com metodologia ágil

**Desejáveis:**
- conhecimentos em bootstrap

**Diferenciais:**
- experiência com prototipação

## Benefícios

- Férias remuneradas

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para camilla.moriya@alfaconcursos.com.br com seu CV anexado - enviar no assunto: Vaga FrontEnd

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@alfaconcursos.com.br

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Júnior

**Comment by rafaelkendrik** [comment]
link da vaga: https://alfacon.gupy.io/jobs/478076?jobBoardSource=gupy_public_page

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
