### ISSUE TITLE
[Remoto/São Paulo] Front-end Developer na Lemon Energy

### ISSUE THREAD

**Issue by prxg22** [frontendbr/vagas#3849]
### **Sobre a Lemon**

A Lemon é uma das primeiras Enertechs brasileiras, empresas dedicadas a inovar o setor elétrico. Nossa missão  é democratizar a energia limpa, dando ao cliente poder para decidir de onde vem a energia que consome, por meio de uma experiência totalmente digital sem precedentes.

### **Por que inovar no setor elétrico?**

Porque fontes de energia poluentes são responsáveis hoje por quase metade das emissões de carbono no mundo. Democratizar e facilitar o acesso à novas fontes de energia renovável vai estimular que mais usinas sejam construídas, tornando nossa matriz energética cada vez mais verde

## Descrição da vaga

**Não há requisitos de senioridade, queremos as melhores pessoas para nosso time independente de quanta experiência você já tem.**

Trabalhar com o time de design e backend para desenvolver e manter aplicações afim de solucionar os desafios em conversão de leads, sistemas internos, onboarding e faturamento de clientes. Sempre visando a melhor experiência para nossos clientes!

Desenvolver, manter e documentar pacotes que são a base de nossas aplicações e com as mais diferentes utilidades: componentes UI, ferramentas de analytics, state management, roteamento e outros.

Além disso, estamos sempre melhorando e aplicando scripts para inclusão de funcionalidades e conteúdo em nosso site.

## Local

Remoto ou Escritório, SP, São Paulo, Vila Madalena

## Requisitos

**Obrigatórios:**
- Conhecimento sólido em JavaScript
- Ter experiência com pelo menos um framework SPA
- Trabalhar na melhoria contínua para um código sempre mais limpo, testado, organizado e melhor

**Desejáveis:**
- Ter experiência com React

**Diferenciais:**
- Experiência com Node JS
- Experiência com AWS
- Experiência com Serverless

## Benefícios

1. Salários compatíveis com mercado
1. Plano de saúde e Cartão Benefício Flexível

**Diferenciais:**
1. Horário flexível e possibilidade de home office (mesmo quando tiver vacina)
1. Possibilidade de ganhar equity: uma fatia da empresa pode ser sua 
1. Cultura de trabalho que prioriza: transparência, autonomia e colaboração, diversidade e inclusão.

## Contratação

PJ a combinar

## Como se candidatar

Siga as instruções em: https://www.notion.so/lemonenergy/Software-Engineer-Front-End-641aa11fe58742d6a9dabb8d58ac0760

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: carreiras@lemon.energy

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by rfoel** [comment]
🎉

**Comment by cp-yago** [comment]
Essa vaga me chamou bastante atenção! Incrição feita :)

**Comment by prxg22** [comment]
Boa, @cp-yago! Aguardo sua inscrição 😄

**Comment by raulfranck** [comment]
Inscrito 🎉🎉

**Comment by BrenerQuevedo** [comment]
Muito bom, me inscrevi

**Comment by wgleen** [comment]
Bem legal. Inscrito!
