### ISSUE TITLE
[REMOTO] Front-end Developer na empresa @Risknow

### ISSUE THREAD

**Issue by Egarter** [frontendbr/vagas#3850]
Empresa: Risknow
Faixa salarial: R$ 6.000,01 a R$ 10.000,00
Estado: São Paulo
Local da vaga: São Paulo
Nível: Sênior
Aceita Remoto?: Sim

**Descrição da vaga**
Risknow é uma fintech de Real-Estate com foco em tecnologia e inovação. A empresa vem crescendo a cada ano com uma cultura de transparencia e meritocrática.
Time legal e forte em tech/product. Processos ágiles com autonomia para cada POs.

Vaga remota para pleno++ ou senior front-end em React/vue com typescript. Responsável para a parte front-end de uma linha de produto. Possa contribuir com CRUD em nodejs.

**Requisitos**

- Excelente conhecimento de Typescript, e React (preferência) ou Vue.
- Nodejs seria um plus

Se interessou?
Corre lá no FrontJobs!
http://www.frontjobs.com.br/job/146/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
