### ISSUE TITLE
Vaga para Profissional Em 3d - @Empresa Interprise Management - Home Office

### ISSUE THREAD

**Issue by cristianpazdasilva** [frontendbr/vagas#3851]
Vaga para Profissional em 3d.

1-Qual a experiência com projetos de 3D design (Maquete electronica de predios e casas) para o ramo de arquiterura (desenho de predios casas etc)
2- Alguma experiencia com criacao de videos em 3d para o  ramo de arquitetura?
3- Disponibilidade de horas por semana?

Interessados Enviar email com o questionário respondido para:

webprogramdesen@gmail.com

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
