### ISSUE TITLE
[REMOTO] Front-end Developer (Pleno) ou (Sênior) na W2Bit / KHUBE

### ISSUE THREAD

**Issue by w2bit** [frontendbr/vagas#3852]
> Vaga Remota durante a pandemia

## Nossa empresa
W2Bit e Khube agora são uma só!
Quer trabalhar em uma empresa 100% inovadora com as novas staks e projetos bem desafiadores? 
Se você é um ninja no JavaScript e gosta de trabalhar com react, node, react native, vue, ou algo mais voltado para o back-end essa vaga combina com você!

## Descrição da vaga
Em seu dia a dia atuará com o JavaScript,React e React Native, Node, Firebase, desenvolvimento de funcionalidades e telas novas para web ou Mobile, resolução de Bug’s, consumo de API’s e integração entre sistemas via front-end, por isso é necessário o conhecimento intermediário de aplicação dessas tecnologias;

Será um diferencial ter conhecimento e/ou experiência com a plataforma Firebase, ou apreender a plataforma em menos de 2 meses - desafiador!

Será um diferencial ter conhecimento básico ou avançado em back-end (Node, Python, AWS, GC).

## Local
Remoto / Rio de Janeiro / São Paulo / Miami

## Requisitos

**Obrigatórios:**
- 1 anos de experiência com REACT
- 2 anos de experiência com JavaScript

**Desejáveis:**
- conhecimentos em React
- conhecimentos em React Native
- conhecimentos em JavaScript

**Diferenciais:**
- conhecimentos em Firebase
- conhecimentos em Node
- conhecimentos em Python
- conhecimentos em Vue
- conhecimentos em Back-End
- conhecimentos em AWS

## Contratação
PJ a combinar (ENVIAR PRETENSÃO)

## Como se candidatar
Por favor envie um email para contato@w2bit.com com seu CV anexado e **pretenção salárial** - enviar no assunto: Vaga W2bit

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: contato@w2bit.com

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by davidsonsimoes** [comment]
Ainda em aberto
