### ISSUE TITLE
[Curitiba] Front-end Developer Angular na Sisteplan

### ISSUE THREAD

**Issue by Janaina-Lima** [frontendbr/vagas#3853]
Front-end Developer Angular - Pleno

Atuar no desenvolvimento e sustentação de sistemas, com foco no front end em Angular.

Atividades

Implementar novas funcionalidades na plataforma. 
Implementar correções de código conforme necessário.
Requisitos

Mínimo de 3 anos de experiência no desenvolvimento front end com Angular (versões 7, 8 ou 9)
Experiência no desenvolvimento em CSS,TypeScript, Html, Json, JavaScript
Conhecimento em SQL Ansi
Desejável

Conhecimento em Spring-Boot, Java, JSP
Perfil

Boa capacidade de comunicação, relacionamento e trabalho em equipe;
Proatividade e iniciativa.
Saber trabalhar sob pressão.
Benefícios

Ticket refeição de R$ 25,00/dia.
VT.
Seguro de vida.Plano de saúde (Unimed ou CliniPam) para família sem desconto.
Bolsa de estudos depois de 1 ano de empresa.
Horário de Trabalho: Seg à Sex 08:00 às 18:00.

Modelo de contratação CLT – Presencial

Interessados enviar cv para contato@icontalent.com.br e informar o nome da vaga no título do e-mail.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by Janaina-Lima** [comment]
vaga encerrada
