### ISSUE TITLE
[Remoto/São Paulo] Front-end Developer na Influu

### ISSUE THREAD

**Issue by influu** [frontendbr/vagas#3854]
## Descrição da vaga
Desenvolvedor frontend com vasta experiência em VUE e Integrações com API.

## Nossa empresa
Somos uma agência com foco no mercado de influenciadores.

## Local
Próximo ao metro Faria Lima ou Remoto

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com desenvolvimento Javascript
- 1 anos de experiência com desenvolvimento VueJS
- Conhecimento com Tailwind V2.0
-  GraphQL

## Contratação
PJ a combinar

## Como se candidatar
Por favor envie um email para contato@influu.me com seu CV ou Link Git- enviar no assunto: [VAGA_VUEjs] + Nome + Sobrenome

## Labels
- PJ
- Pleno
- Remoto
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
