### ISSUE TITLE
[Cidade] Front-end Mobile Developer FLUTTER na Angular e-Commerce

### ISSUE THREAD

**Issue by reichert** [frontendbr/vagas#3857]
## Vaga remota - para sempre remota
- Vaga remota CLT para fazer parte da nossa equipe
- Vaga para nível Pleno

## Nossa empresa
- Nossa empresa faz um e-commerce de nicho (para academias) e se baseia em flutter no mobile, vue.js no frontend e python no backend. Somos hoje os maiores deste segmento no Brasil e competimos com soluções estrangeiras, batendo em qualidade em muitos aspectos.

## Descrição da vaga
- A vaga é exclusiva para desenvolvedor mobile em flutter (existe outra equipe de frontend web e backend);
- A vaga é para fazer parte da equipe e ter carteira assinada CLT;
- A vaga é para pleno, precisamos de experiência de pelo menos 6 meses em desenvolvimento flutter;
- Nosso desejo é ter você conosco no longo prazo!

## Local
- A sede fica em Barueri - SP
- Site: https://angulare.app/

## Requisitos
**Obrigatórios:**
- 6 meses de experiência desenvolvendo aplicativos em flutter;
- ser meticuloso no design - ou seja - saber olhar para a tela e saber onde a margem está errada, onde a fonte está um pouco maior, etc...

## Contratação
- Exclusivamente CLT

## Como se candidatar
- Por favor, envie um e mail para rh@angular-ecommerce.com - com seu CV anexado - enviar no assunto: Vaga Developer Mobile Flutter

## Tempo médio de feedbacks
- Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
