### ISSUE TITLE
[Remoto] Web Designer na Angular e-Commerce

### ISSUE THREAD

**Issue by reichert** [frontendbr/vagas#3858]
## Vaga remota - para sempre remota
- Vaga remota CLT para fazer parte da nossa equipe
- Vaga para nível Pleno
- Estamos buscando um webdesigner para uma posição CLT em nossa empresa, com trabalho 100% remoto. A vaga possui itens desejados e outros necessários

## Nossa empresa
- Nossa empresa faz um e-commerce de nicho (para academias) e se baseia em vue.js no frontend e python no backend. Somos hoje os maiores deste segmento no Brasil e competimos com soluções estrangeiras, batendo em qualidade em muitos aspectos.

## Descrição da vaga
- A vaga é exclusiva para frontend em vue.js (existe outra equipe de backend);
- A vaga é para desenvolvimento de mecanismos javascript que são colocados em outros websites; construir painéis administrativos; apoiar a parte de javascript de nosso CMS;
- A vaga é para fazer parte da equipe e ter carteira assinada CLT;
- A vaga é para pleno, precisamos de experiência de pelo menos 12 meses em desenvolvimento vue.js;
- Nosso desejo é ter você conosco no longo prazo!

## Local
- A sede fica em Barueri - SP
- Site: https://angulare.app/

## Requisitos
**Obrigatórios:**
- saber usar a ferramenta XD da Adobe;
- saber tratar, recortar e manipular imagens via fotoshop, indesign ou ferramentas equivalentes;
- já ter feito desenvolvimento de website;
- ter método para extrair do cliente as informações para realizar um trabalho;

**Desejáveis:**
- ter experiência em layoutar interfaces administrativas;
- ter experiência em design de aplicativos;
- ter experiência em testes e validação das páginas, apps ou aplicativos desenhados por você após o desenvolvimento pela equipe de Frontend.

## Contratação
- Exclusivamente CLT

## Como se candidatar
- Por favor, envie um e mail para rh@angular-ecommerce.com - com seu CV anexado - enviar no assunto: Vaga Web Designer

## Tempo médio de feedbacks
- Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
