### ISSUE TITLE
[ Remoto/São Paulo] Front-end Reactjs Developer @Pixter

### ISSUE THREAD

**Issue by D440** [frontendbr/vagas#3860]
## Nossa empresa

A Pixter é uma boutique de software, focada em grandes clientes. Com um time de mais de 100 pessoas, trabalhando em projetos nos EUA, Portugal e Brasil, a Pixter está guiando a transformação digital de algumas das principais empresas do mundo.

## Descrição da vaga

Estamos em busca de Reactjs Developer, com experiência sólida, em nível Pleno/Sênior, excelente comunicação, boa desenvoltura em reuniões de planejamento, organização e bom relacionamento interpessoal.

## Local

Exemplo: Remoto por enquanto, sem previsão de retorno, após a pandemia seria na Região Central de SP - Campos Elíseos

## Requisitos
HTML: padronização, acessibilidade, mobile patterns.
CSS hierárquico e de fácil manutenção.
Desenvolvimento voltado à componentização.
Domínio em Javascript nativo (ES6>).
Domínio em ReactJS e outros frameworks single-page.
Noções básicas de ferramentas para controle de versão.
Experiência com Gulp, Grunt ou Webpack.

**Desejáveis:**
VueJS;
Noções básicas de NodeJS;
TDD.

## Como se candidatar

Por favor envie um email para danilo.vieira@pixter.com.br com seu CV anexado - enviar no assunto: Vaga Reactjs

#### Nível
- Pleno
- Sênior

**Comment by vitorrubim1** [comment]
Email enviado :)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
