### ISSUE TITLE
[Cascavel-PR] Front-End Developer na TOTVS CRM

### ISSUE THREAD

**Issue by luizwbr** [frontendbr/vagas#3861]
> Vaga Remota durante a pandemia

## Nossa empresa

Aqui na TOTVS a ousadia e a transformação fazem parte da nossa rotina.

Somos a maior empresa de tecnologia do Brasil e nosso poder de transformação faz com que nossos softwares estejam presentes em mais de 40mil empresas no Brasil e no mundo.

O nosso grande segredo para estar sempre um passo a frente do mercado é a ousadia e a transformação que nossos TOTVERS promovem todos os dias.

Ousadia para movimentar 25% do PIB brasileiro por meio dos clientes que usam os nossos softwares.
Ousadia para ser a primeira empresa de tecnologia do Brasil a ser listada na Ibovespa.
Ousadia para fazer da mudança a nossa rotina, com mais de 40 aquisições ao longo de nossa história.

Nossa curiosidade nos impulsiona e, o melhor, todo mundo colabora com todo mundo, não importa quem deu a ideia: todos estão dispostos a ajudar e se envolvem legitimamente para fazer dar certo e entregar resultados.

Tudo isso acontece em um ambiente leve e divertido, mas já deixamos claro: a intensidade e a rapidez com que as coisas acontecem aqui é acima da média.

Vem fazer parte de tudo isso!

#sejaumTOTVER

## Descrição da vaga

Venha trabalhar na construção do Front-end do produto TOTVS CRM.

Usamos React Native para mobile e ReactJS na parte web.

## Local

[PR], [Cascavel], [Centro]

## Requisitos

- Experiência com build tools e gerenciamento de dependências (Ex: Npm, Yarn, webpack);
- Experiência em uso de recursos da linguagem Javascript (Ex: Promises, Callbacks);
- Conhecimento de ECMAScript moderno (2018);
- Experiência em desenvolvimento Web utilizando HTML5, CSS3, Javascript e frameworks Javascript como JQuery, React, React - Native ou AngularJS;
- Flexível e capaz de adquirir conhecimento em diversas plataformas e tecnologias;
- Capacidade de resolver problemas de forma rápida e objetiva;
- Capacidade de encontrar e comparar ferramentas para resolver os desafios que surgem diariamente;
- Capacidade de analisar problemas em equipe e propor soluções utilizando bons argumentos;
- Autodidata e apaixonado por desenvolvimento de software.

## Benefícios
- Vale alimentação;
- Plano de saúde Unimed (co-participativo);
- Plano odontológico (co-participativo);
- Seguro de vida;
- Programa de empresas parcerias;
- SESC, SENAC, ACIC, AMIC;
- Vale Transporte;
- Cadeira de massagem;
- Estacionamento para bikes e motos. 

**Diferenciais:**
- Programa "Eu Indico";
- Disponibilização de Bebidas e Frutas diariamente;
- Ambiente descontraído e colaborativo;
- Horário Flexível;
- Café da Dona Maria;
- Dress Code Free.

## Contratação

CLT

## Como se candidatar

Clique em "Apply" por meio do [link](https://totvs.gupy.io/jobs/574001?jobBoardSource=gupy_public_page) 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: mariana.albuquerque@totvs.com.br

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
