### ISSUE TITLE
[São Carlos/SP Remoto] FullStack Developer @Sigalei

### ISSUE THREAD

**Issue by DaniloOliveira28** [frontendbr/vagas#3862]
## Nossa empresa

Para as organizações que buscam maximizar o impacto positivo na sociedade, é fundamental ouvir, entender, conciliar e gerenciar demandas de todos os seus stakeholders, sejam eles comunidades locais, consumidores, colaboradores, governos e até os seus acionistas. Mas gerir os stakeholders e suas demandas é complexo e necessita de uma fina coordenação entre os diversos departamentos, porém sem as ferramentas adequadas torna o processo ineficiente ou mesmo ineficaz.

Pensando nestes problemas, a Sigalei desenvolve uma plataforma de gestão e monitoramento de stakeholders utilizando BigData e Machine Learning para organizações mensurarem e gerenciarem as demandas de cada stakeholder, sejam elas formatadas em documentos regulatórios oficiais como projetos de leis, ou dispersas na opinião pública manifestadas nas mídias e redes sociais.

## Descrição da vaga

O desenvolvedor fullstack é responsável por criar, manter e melhorar nossa plataforma. Você irá trabalhar tanto com o nosso backend tanto com o nosso frontend.

Trabalhando ao lado do nossa equipe de design e se relacionando com todas as áreas da empresa, você será responsável por ajudar no desenvolvimento do produto da Sigalei.

Oferecemos feedbacks constantes e todo o apoio necessário para você alcançar o sucesso na sua carreira profissional. 

Estamos construindo uma cultura horizontal focada no aprendizado e na autonomia da pessoa. Assim, você terá total liberdade para testar ideias e métodos.

Vamos juntos!

**Responsabilidades**
• Trabalhar junto a área de produto e de design para desenvolver o módulos da nossa plataforma
• Trabalhar com TDD no desenvolvimento do código
• Refatorar códigos legados para melhorar a manutenibilidade e performance da nossa aplicação

## Local

Exemplo: Remoto ou Escritório, São Carlos/SP

## Requisitos

**Obrigatórios:**
• graduação na área de computação ou correlatas (engenharia);
• 3 anos de experiência profissional com JS/TS;
• Experiência com TDD (Jest);
• Experiência com PostgreSQL/NoSQL;
• Experiência com: bancos NoSQL, automação de pipelines (circleci ou github actions), docker;
• Boa comunicação;
• Autonomia;
• Interesse por tecnologias do estado da arte;
• Interesse por dados abertos.

**Desejáveis:**
• Experiência com Kubernetes;
• Experiência com React Native.

**Diferenciais:**
• projetos opensource

## Benefícios

• CLT (Salário competitivo)
• Horário Flexível
• VA ou VR (R$ 500,00/mês)
• Plano Unimed integral Nacional
• Auxílio Home Office
• Trabalho Remoto
• Yoga Laboral

**Diferenciais:**
• Opensource Day - A cada 15 dias reservamos nossas sextas para investir em projetos abertos para a comunidade

## Contratação
CLT

## Como se candidatar
Preencher formulário
https://app.pipefy.com/public_form/468888

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: contato@sigalei.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
