### ISSUE TITLE
[Brasil] Front-end Developer na Projeto 22 Remoto Fintech React js  Vue Angular

### ISSUE THREAD

**Issue by ketlinP22** [frontendbr/vagas#3864]
> Vaga Remota 

## Nossa empresa
Projeto 22, Empresa dedicada em prestar serviço de excelência em R&S (hunting) e Terceirização (bodyshop) de profissionais de tecnologia, metodologia de projetos, gestão e designer de produtos.
 
O nosso grande proposito é ser um parceiro de confiança e efetivo dos nossos clientes. Trabalhando sempre com atitudes positivas, ações transparentes e de boa fé, que prezam o bom relacionamento e o respeito às pessoas. Esses são os nossos pilares, desta forma teremos uma relação de confiança e uma parceria duradoura com nossos clientes e colaboradores.

## Descrição da vaga

Projeto baseado em 3 Frameworks: Angular 2+, React JS, Vue.

## Local

Remoto 

## Requisitos

**Obrigatórios:**

Engenheiro Front End Sênior
Contratação: PJ 
Região: São Paulo/ Atuar 100% remoto. 

Requisitos: 
produção; Manutenção evolutiva e garantia de estabilidade dos serviços; Avaliação de novas tecnologias e frameworks; Comunicação com áreas clientes para atendimento de demandas; Comunicação com outras equipes da empresa a fim de realizar integrações; Automação de testes;

Pré-requisitos: Superior completo ou em andamento em Ciência da Computação, Engenharia, Sistemas da Informação ou áreas correlatas; Bons conhecimentos de desenvolvimento de lógica e algoritmos; Experiência de pelo menos 3 anos com desenvolvimento de sistemas web; Experiência no desenvolvimento de aplicações com serviços RESTful; HTML/HTML5, CSS3, JavaScript; Design Patterns; SASS, CSS animations, design responsivo, media query; Conhecimentos em pelo menos duas tecnologias Javascript: React, Vue.js ou Angular; Conhecimentos em sistemas de controles de versão (git); Inglês técnico avançado para leitura. Desejáveis: Experiência em Node.js; Typescript; Webpack, Babel; Conhecimentos em componentização de elementos (Web Components, Stencil) Conhecimentos sobre pipelines de entrega e integração contínua.

**Diferenciais:**
- Chance de crescimento 

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para ketlin.sales@pro22.com.br com seu CV anexado - enviar no assunto: Vaga Front End

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
