### ISSUE TITLE
[Florianópolis] Front-end Developer na Nexfar

### ISSUE THREAD

**Issue by willianmonteiro** [frontendbr/vagas#3865]
## Nossa empresa

A Nexfar busca a inovação do mercado farmacêutico através da tecnologia. Com a nossa plataforma de e-commerce, auxiliamos as distribuidoras de medicamentos a impulsionarem suas vendas online para farmácias de pequeno e médio porte. Na outra ponta, ajudamos os donos de farmácia a comprar de maneira rápida, prática e eficiente.

Você gosta da ideia de trabalhar com pessoas que não medem esforços para entregar valor e excelência aos seus clientes? Faça parte do nosso time!

## Descrição da vaga

Juntamente com nossa equipe, você irá implementar funcionalidades projetadas pelo nosso time de produto e UX.

## Local

Santa Mônica - Florianópolis / SC

## Requisitos

**Obrigatórios:**
- Conhecimento sólido em JavaScript
- React 
-- Componentização
-- Estado, ciclo de vida e propriedades do componente
-- Hooks
-- JSX
- HTML
- CSS
- Git
- Rest API
- Redux (ou conceito de estado global)
- Trabalhar na melhoria contínua para um código sempre mais limpo, organizado e melhor

**Desejáveis:**
- Sass / Styled-Components
- Material UI / Bootstrap
- StoryBook

## Benefícios

- VR / VA

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um email para vagas@nexfar.com.br com uma breve apresentação e o seu Linkedin - enviar no assunto: Vaga ReactJS

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
