### ISSUE TITLE
[Remoto] Desenvolvedor(a) Angular Pleno/Sênior na Supero

### ISSUE THREAD

**Issue by larissaaguiar** [frontendbr/vagas#3866]
## Nossa empresa

Somos movidos por desafios e buscamos soluções que atendam às necessidades de nossos clientes e os deem destaque no mercado em que atuam. Com projetos personalizados para suas demandas, trazemos sempre as melhores tecnologias e práticas inovadoras que elevam nossos clientes para o próximo nível.

## Descrição da vaga

Responsabilidade: Atuar no desenvolvimento de solução construindo funcionalidades e componentes definidos com a equipe de desenvolvimento. Implementar interfaces usando Angular.

Projeto: Implementar uma solução para sistemas industriais.

## Local

 Remoto 

## Requisitos

**Obrigatórios:**
- Conhecimentos em Angular 2 ou superior, HTML 5, JavaScript, CSS e TypeScript.

**Desejáveis:**
- Formação: Superior na área de TI.

**Diferenciais:**
-  Inglês intermediário, e conhecimentos em outras tecnologias não relacionadas são um diferencial.

## Benefícios

- Horários flexíveis;
Happy Hour;
Ginástica Laboral;
Convênios e descontos;
Treinamentos;
Programa Indique um amigo.

## Contratação

Cooperativa

## Como se candidatar

Candidate-se através do link: https://bit.ly/2KkZoWx

#### Alocação
- Remoto

#### Regime
- Cooperativa

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
