### ISSUE TITLE
[Florianópolis] Front-end Developer na BDR-Talentos Corporativos

### ISSUE THREAD

**Issue by laraschramm** [frontendbr/vagas#3869]
A BDR – Talentos Corporativos procura profissionais para a vaga:

DESENVOLVEDOR(A) FRONT END PLENO – FLORIANÓPOLIS – 01 Vaga 

Requisitos:
Experiência com React ou Vue.js;
Experiência com Javascript;
Experiência com Mac ou Linux;
Conhecimento avançado de CSS;
Conhecimento avançado de GIT e CLI;
Conhecimento de protocolos de comunicação e rede;
Inglês avançado.

Diferenciais: 
Superior Cursando ou Completo;
Conhecimento em LESS/SASS;
Linguagem TypeScript.

Atividades:
Estamos à procura de um(a) desenvolvedor(a) de front-end que possa nos ajudar a levar nosso produto ao próximo nível. No momento, procuramos profissionais para trabalhar com a interface do usuário do nosso sistema, players e aplicações para sinalização digital. Se você deseja saber mais sobre nosso produto, dê uma olhada em https://onsign.tv.

Salário: Entre R$ 4.500,00 e R$ 7.000,00 - CLT.
Horário: Segunda a Sexta - 40h semanais - Horário Flexível.
Benefícios: VR/VA (R$600,00) + Plano de Saúde Unimed + Plano Odontológico Uniodonto + Vale Academia (R$150,00) + PLR. 
Local: Trindade - Florianópolis (Home Office na Quarentena).

Interessados devem cadastrar seu currículo em www.empresabdr.com.br, na vaga 
Desenvolvedor(a) Front End Pleno - Florianópolis.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
