### ISSUE TITLE
[São Paulo] - Front-End-Developer Junior/Pleno 

### ISSUE THREAD

**Issue by Renatomsilva** [frontendbr/vagas#387]
## Descrição da vaga

Participará do desenvolvimento de novas interfaces , identidade visual e UX, de todas nossas aplicações web e mobile. Utilizando principalmente tecnologias como: React Native, Angular, Nodejs, JS, CSS, HTML, etc...

## Local

Escritório (Presencial) , São Paulo - Paulista

## Benefícios

- 1 hora de almoço
- Expediente de 8 horas diárias (segunda ~ sexta)

## Requisitos

**Obrigatórios:**

- Estar confortável com cada parte do processo de design: pesquisa, criação da UI e a produção do código;
- Ser proficiente com as ferramentas gráficas mais comuns;
- Estar confortável criando os wireframes e protótipos, para apresentar suas criações;
- Ser proficiente com HTML & CSS;
- Saber o essencial de JavaScript, para por exemplo, lidar com a exibição dos dados advindos do backend através de 'templates engines';
- Ter como  pontos fortes, ser auto-orientado, ter plena posse de suas ideias  e resolver problemas desafiadores;
- Ter o desejo de trabalhar de forma colaborativa com uma equipe.
- Experiência com Frameworks SPA (AngularJS, Vue e etc...)
- Git (Command Line)
- Inglês Técnico para leitura
- Conhecimentos de pré-compiladores de CSS

**Diferenciais:**
- React Native

## Contratação

- PJ a combinar

## Nossa empresa

Somos a OriginalMy , um starup pioneira no uso de Blockchain para autenticação de documentos.

## Como se candidatar

Por favor envie um email para contato@originalmy.com com seu CV anexado - enviar no assunto: Vaga Front End Developer Junior

**Comment by diogorodrigues** [comment]
Júnior? kkkkkk

**Comment by xfilipe** [comment]
> Saber o essencial de JavaScript, para por exemplo, lidar com a exibição dos dados advindos do backend através de 'templates engines'; 

Isso é bem júnior, menos que isso na minha opinião é estágio...

**Comment by kvnol** [comment]
Creio que não, <del>Lino</del> @xfilipe. O cara que é júnior não tem tanta experiência assim com JavaScript, com tantos frameworks. O cara que é júnior tem que aprender na empresa, não chegar sabendo tudo.
