### ISSUE TITLE
[Remote] Specialist PHP Developer na Rock Content

### ISSUE THREAD

**Issue by adrianoresende** [frontendbr/vagas#3870]
## Nossa empresa

We are a global leader in content marketing and we exist to enable growth opportunities for our customers, employees and partners! We help brands to drive revenue and build awareness by- Unleashing collaboration through technology- Connecting them to a global network of creative talents- Delivering premium brand and content experiences for their audience If you are looking to learn something new every day with outstanding professionals in the area, if you want to have the opportunity to innovate and use new technologies for marketing, you will find all of that at Rock! We have the most dynamic, collaborative and intelligent environment there is. Also, we're in strong expansion, having tripled our growth in the last 2 years! Diversity is also very important to us and that's why we commit to it. We do not tolerate discrimination by race, gender, disability, sexual orientation, religion or any other type of physical and/or psychosocial characteristic.

## Descrição da vaga

As Specialist PHP Developer at Rock Content, you will be tasked with investigating problems and implementing solutions!

We hope that you will contribute to the technical discussions about the challenges encountered, participating in the technical training of the team, sharing knowledge with the company and the community!

**Responsibilities:**
- Contribute and play a leading role in the development of an international team.
- Ensure the implementation of good code practices and design patterns, object orientation and performance optimization;
- Develop and deploy using our infrastructure;
- Contribute to technical discussions about the challenges encountered, acting as technical mentor of the team;
- Participate in the code review process, ensuring code quality and consistency;
- Share knowledge with the company and the community;
- Acting in the development, production, modification, testing, maintenance and implementation of WordPress themes, plugins and websites; 
- Develop and modify plugins and WordPress themes;
- Identify and solve problems related to WordPress sites;

## Local

Remoto e possui escritórios aqui no Brasil até em Canadá, México e USA.

## Requisitos

- Advanced or fluent English skills;

**Experience:**
- Domain of PHP 7.x, with experience in object orientation and development architecture; preferably MVC and / or SOA;
- Solid experience working with WordPress themes and plugins development;
- Experience integrating plugins and themes with external services using the WordPress JSON API;
- Experience with PostgreSQL / MySQL database;
- Be familiar with the main PHP development standards (PSRs).

**Knowledge:**
- Advanced knowledge of WordPress, PHP frameworks, MySQL, CSS, HTML and jQuery;
- Knowledge of HTTP protocols, API Rest;

**Soft skills:**
- Detail oriented and analytical;
- Excited about different challenges;
- Communication and openness to feedback;

**Differentials:**
- Knowledge in Cloud (AWS, GCP or Azura);
- Knowledge in Docker and build tools;
- Knowledge in Linux;
- Knowledge of security and performance optimization for WordPress sites;

## Benefícios

- Flexible hours;
- Health insurance;
- Dental insurance;

Other benefits may be available according to your location.

## Contratação

A combinar

## Como se candidatar

https://jobs.lever.co/rockcontent/dbb8c457-71b0-493d-a937-12c0fa025556

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
