### ISSUE TITLE
[São Paulo]  Front-end Developer na Fastcash

### ISSUE THREAD

**Issue by MuriloFernandoCavalcante** [frontendbr/vagas#3871]
### **Estamos buscando um Front End Developer com experiencia em Ionic, stencil, html, css e javascript. Capaz de evoluir um projeto de uma aplicação white label com web components.**

Fastcash é uma Fintech jovem e em crescimento acelerado com um ambiente de grande colaboração, que incentiva fortemente a inovação e o crescimento de todos através do ganho de produtividade com soluções inovadoras orientadas a dados e automação de processos.

### **Desejavel:** 

- Html5
- Css3 e 4 (diferencial)
- Javascript
- Typescript
- Ionic
- Stencil
- Firebase

### **Diferenciais:** 

- Azure devops
- Experiencia com aplicação hibridas
- Pwas

### **Como se candidatar:**

Aplique para vaga: rh@fastcash.com.br

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
