### ISSUE TITLE
[REMOTO] Fullstack Developer @ BDR - Talentos Corporativos - HOME OFFICE

### ISSUE THREAD

**Issue by empresabdr** [frontendbr/vagas#3872]
A **BDR – Talentos Corporativos** procura profissionais para a vaga:

**DESENVOLVEDOR(A) FULL STACK PLENO - HOME OFFICE – 01 Vaga** 

**Requisitos:**
Experiência com React, NodeJS, Docker, Git e MySQL;
Conhecimento em Arquitetura MVC;
Conhecimento em RestFul.

**Diferenciais:** 
Experiência com metodologias ágeis;
Experiência com GitLab e Jira Software;
Conhecimento em Swift.

**Atividades:**
Você atuará com diferentes demandas, realizando um trabalho dinâmico e de grandes responsabilidades. As principais atividades serão no Desenvolvimento e Integração, estando na linha de frente em diversos projetos. :)

**Salário:** Entre R$5.000,00 e R$7.000,00 - PJ.
**Horário:** 40h semanais - Segunda a Sexta - Horário Comercial.
**Benefícios:** 30 dias de Férias.
**Local:** Home Office.

**Interessados devem cadastrar seu currículo em www.empresabdr.com.br, na vaga 
 Desenvolvedor(a) Full Stack Pleno - Home Office.**

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
