### ISSUE TITLE
[FLORIANÓPOLIS] Fullstack Developer Senior @ BDR - Talentos Corporativos

### ISSUE THREAD

**Issue by empresabdr** [frontendbr/vagas#3873]
A **BDR – Talentos Corporativos** procura profissionais para a vaga:

**DESENVOLVEDOR(A) FULL STACK – FLORIANÓPOLIS – 01 Vaga** 

**Requisitos:**
Superior Completo em Ciências da Computação ou áreas relacionadas;
Experiência com Javascript, HTML e CSS;
Experiência com Node.js;
Conhecimento em ReactJS;
Conhecimento de interação com bancos de dados não relacional (MongoDB);
Conhecimento em gestão de arquitetura AWS.

**Atividades:**
Realizar o desenvolvimento e manutenção da plataforma na empresa;
Garantir eficiência e facilitação de interação entre usuário e plataforma;
Realizar a manutenção de banco de dados Mongo;
Pesquisar e desenvolver a arquitetura de infraestrutura cloud;
Monitorar serviços e servidores;
Desenvolver os testes automatizados;
Desenvolver integrações com RD e Analytics;
Realizar concepção de telas e funcionalidades em conjunto com a equipe UX.

**Salário:** A combinar - CLT.
**Horário:** Segunda a Sexta - Horário Comercial.
**Benefícios:** VA/VR (R$30,00/dia útil) + VT ou Auxílio Combustível (R$8,68/dia útil) + Plano de Saúde Integral + Auxílio Home Office (R$100,00 - durante a pandemia).
**Local:** Santa Mônica - Florianópolis (Home Office na Quarentena).

**Interessados devem cadastrar seu currículo em www.empresabdr.com.br, na vaga 
Desenvolvedor(a) Full Stack - Florianópolis.**

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
