### ISSUE TITLE
[São Paulo] Desenvolvedor Angular na Wayon IT

### ISSUE THREAD

**Issue by anamazzi** [frontendbr/vagas#3874]
> Vaga Remota durante a pandemia

## Nossa empresa

A Wayon IT Solutions, Empresa sólida no mercado, atua de forma integrada desenvolvendo soluções completas com serviços e produtos para empresas em toda América do Sul e que, transforma tecnologia em soluções de negócio.

## Local

Remoto e Escritório, [São Paulo], [São Paulo], [Barra Funda]

## Requisitos

**Obrigatórios:**

Experiência como Desenvolvedor AngularJs, Angular 2+, git, html5, css, sass, rest
Noções em nodeJs.
Experiência com homologação, testes, correções e suporte.

**Desejáveis:**
Front-end single page apps: components, JavaScript, Typescript, RestFull, JSON, Bootstrap, CSS3, HTML5, jQuery.

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para ana.mazzi@wayon.global com seu CV anexado - enviar no assunto: Vaga Angular

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
