### ISSUE TITLE
[REMOTO] Front-end Developer no Elo7

### ISSUE THREAD

**Issue by tamimaia02** [frontendbr/vagas#3875]
> Vaga Remota durante a pandemia 100% remota

## Nossa empresa

O Elo7 é o maior site de produtos autorais do Brasil. Formamos a maior comunidade de vendedores criativos e buscamos fomentar o comércio de produtos autorais. Muito mais que um site, o Elo7 nasceu em 2008 com a missão de transformar a vida das pessoas através de um ambiente humanizado de compra e venda que conecta e inspira, conferindo significado a cada transação realizada.

Trabalhamos para desenvolver as melhores tecnologias e oferecer aos vendedores soluções simples e práticas para o gerenciamento de suas vendas e para os compradores, uma experiência de compra fora de série.

## Descrição da vaga

O nosso time de front-end web trabalha principalmente no desenvolvimento das páginas do marketplace utilizando as tecnologias **HTML, SCSS, JavaScript, Node e Java**.

Somos um time Fullstack participando do desenvolvimento do layout das páginas e da integração no back-end.
Também cuidamos de todo o ambiente ao redor que pode facilitar o desenvolvimento, influenciar o usuário, detectar bugs e automatizar processos. Testes automatizados, reaproveitamento de código entre telas e métricas são algumas dessas tarefas.
O público alvo da vaga são profissionais com alguma experiência no mercado de trabalho e disposto a aprender e compartilhar conhecimento.

## Local
- Remoto ou Escritório - Ficamos em São Paulo, mas estamos todos 100% remotos. 

## Requisitos

**Obrigatórios:**
- Semântica HTML
- Layout CSS
- JavaScript puro
- Lógica de programação

**Diferenciais:**
- Node
- Arquitetura de componentes
- Padrão MVVM (two way data binding)
- Isomorfismo
- SEO
- Performance
- Acessibilidade

## Benefícios
- O nosso regime de contratação é CLT, com flexibilidade (40h semanais);
- Oferecemos Vale Refeição e alimentação: benefício flexível;
- Plano de Saúde, Odontológico e Seguro de Vida;
- Gympass: plataforma que te dá acesso a mais de 18 mil academias no Brasil. Nas academias conveniadas são oferecidas mais de 700 modalidades esportivas
- Auxílio Creche;
- Yoga, Meditação e Ginástica Laboral;
- Parceria com Zenklub que oferece 4 sessões gratuitas por mês;
- Temos descontos em cursos de empresas como Caelum, ESPM e ComSchool;
- Manicure, Massoterapeuta, Naturólogo, Aula de Música e Aula de Inglês: Parcerias com valor acessível e atendimento no escritório;

## Contratação

CLT 

## Como se candidatar

Através do link https://elo7.gupy.io/jobs/556840 ou envie um email para tamires.maia@elo7.com seu CV anexado - enviar no assunto: Vaga Fron End

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 40 dias após cada processo.
E-mail para contato em caso de não haver resposta: tamires.maia@elo7.com.br

#### Regime
- CLT

#### Nível

- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
