### ISSUE TITLE
[VAGA – São Paulo/SP] [Tech Lead – Orbia] 

### ISSUE THREAD

**Issue by joaorneto** [frontendbr/vagas#3876]
Com mais de 140 mil agricultores em na base de clientes, a Orbia é líder de mercado e vem promovendo a transformação digital no agronegócio. A missão é ligar o agricultor a uma rede para facilitar seus processos, fazer negócios e gerar valor - Criando a maior plataforma de comércio digital do agronegócio.

Como Tech Lead da Orbia, você será responsável por supervisionar o desenvolvimento de fornecedores de software, garantindo soluções robustas e escaláveis com tecnologias modernas e boas práticas. Desenvolver soluções de ótima qualidade trabalhando em times multifuncionais em parceria com gestão de produtos, UX e Software house. 

Contratação: CLT

Nível: Especialista

Requisitos:
Experiência em novos desenvolvimentos, planejando a arquitetura do zero;
Perfil Full Stack;
Background técnico no desenvolvimento de solução para web e mobile;
Ter experiência com gestão de fornecedores de software (software houses);
Ter experiência com C# (.NET), bancos de dados SQL e noSQL, micro serviços e event driven; 

Incrível né? Agora imagine você fazendo parte disso?! Para mais informações sobre essa oportunidade, dá uma olhada no link: https://byintera.in/1n0

Um sorriso de orelha a orelha!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
