### ISSUE TITLE
[REMOTO] Front-end Developer React no Grupo DB1

### ISSUE THREAD

**Issue by talentos-db1** [frontendbr/vagas#3877]
## Nossa empresa
Somos um grupo de tecnologia com 20 anos de expertise em desenvolvimento de software voltado para soluções de grandes empresas. Estamos há 10 anos consecutivos dentre as melhores empresas para trabalhar, pelo GPTW. 

Ser DB1 é pertencer a um grupo que transforma a vida das organizações e das pessoas por meio da tecnologia. Nossa cultura, conhecimento e habilidades nos movem para fazer entregas que ajudam as pessoas a terem um dia a dia melhor.  

Fazer parte do DB1 Group é ser movido a desafios, afinal, são neles que as melhores oportunidades surgem.

## Descrição da vaga

Buscamos um(a) profissional apaixonado(a) por tecnologia, que desenvolva em frontend com React JS para no desenvolvimento de uma plataforma educacional com abrangência nacional. Deverá garantir as melhores práticas de programação, um código limpo e com uma boa usabilidade, focado na sustentabilidade e performance do sistema. 

Sua responsabilidade será iniciar um novo projeto, apoiando um de nossos parceiros a alavancar seus negócios!
Por isso essa vaga se destina a profissionais antenados, interessados em evolução contínua, sejam curiosos e acompanhem as melhores tendências em desenvolvimento.

## Local

Remoto ou em uma de nossas unidades.
[MARINGÁ/PR]
[CAMPO GRANDE/MS]
[PRESIDENTE PRUDENTE/SP]

## Requisitos

**Obrigatórios:**
- Experiência com HTML5, CSS3;
- Experiência com Javascript;
- Conhecimento em ES6;
- Conhecimento em pré-processadores CSS (SASS, LESS, PostCSS);
- Experiência com alguma metodologia atual de padrões de CSS/HTML (BEM, Atomic, outros);
- Conhecimento em Git;
- Criação de código limpo, legível e cross-browser;

**Desejáveis:**
- Conhecimento em usabilidade de usuário e boas práticas de UX e UI;
- Experiência com desenvolvimento de sites responsivos;
- Testes Automatizados (mochajs, jasmine, jest);
- Redux/Flux;
- Conhecimentos com Server Side Rendering;
- Conhecimentos em GraphQL.

## Benefícios
- Plano de saúde
- VR MÍNIMO de R$ 400/mês

**Diferenciais:**
- DB1 at home office: essa vaga permite atuação remota! 
- Trabalhar com pessoas incríveis que adoram compartilhar conhecimento; 
- Estar em um ambiente de camaradagem constante, onde o trabalho em equipe fala mais alto; 
- Desafios para alcançar desenvolvimento pessoal e profissional; 
- Horário flexível; 
- Diversos Comitês para você participar de ações com impacto dentro e fora da DB1;

## Contratação
CLT

## Como se candidatar
Através de nosso site: https://vagasdb1.recruiterbox.com/jobs/fk0q575?source=Github

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 40 dias após cada processo.
E-mail para contato em caso de não haver resposta: talentos@db1.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
