### ISSUE TITLE
[REMOTO] Front-end Developer (PART-TIME) na RBOOH

### ISSUE THREAD

**Issue by danillodouglas** [frontendbr/vagas#3879]
### **Nossa empresa**
A RBOOH.COM.BR conecta de forma rápida e eficiente anunciantes às melhores opções de mídia out-of-home (OOH).
Somos a solução que consolida o sistema comercial dos melhores veículos de mídia OOH, em um só lugar, no menor tempo possível, oferecendo uma experiência de compra única e inovadora aos moldes do digital/ON do ambiente da cidade/OFF

### Descrição da vaga
Front-end Developer na plataforma.RBOOH.com.br
*Atuação remota, full-time **(mínimo de 4 horas/dia)**.

### Local
REMOTO
A sede da RBOOH fica em Goiás.

### Requisitos
Sólida experiência em projetos React + Redux
Proficiência em JavaScript
Experiência com CSS e HTML semântico
Familiaridade com APIs RESTful
Experiência com ferramentas comuns de desenvolvimento front-end como: Babel, Webpack, NPM, Lint, JSX, Git, etc

**O que esperamos:**
Proatividade
Boa comunicação e trabalho em equipe
Desenvolver com fidelidade os layouts recebidos
Capacidade de entender os requisitos de negócios e traduzi-los em requisitos técnicos
Disponibilidade para reuniões pela manhã (8h às 9h), duas vezes na semana

**Diferenciais do candidato:**
Material-UI e Styled Components
Boa experiência com hooks
Mobile First
React Native
Testes (Jest e Cypress)
Conhecimento de boas práticas de UI e UX

### Benefícios
Fazer parte de um GRANDE PROJETO
Oportunidades de promoção dentro da equipe com aumento de ganhos
Aprendizado em equipe
Feedbacks constantes
Contratação PJ

### Como se candidatar
Por favor envie um **email para danillo.douglas@rbooh.com.br com seu CV** anexado
Enviar no assunto: **Vaga ReactJS Remoto PART-TIME**
Descrever no corpo do e-mail **aonde viu a vaga**

### Tempo médio de feedbacks
Costumamos enviar feedbacks SOMENTE PARA OS SELECIONADOS em até 7 dias após cada candidatura.
E-mail para contato: danillo.douglas@rbooh.com.br

### Alocação
Remoto
Part-time

### Regime
PJ (Pessoa Jurídica com emissão de NF)

### **Nível**
Pleno
Sênior

### Remuneração
De 4k a 6k

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
