### ISSUE TITLE
[São Paulo] - Front-End Developer React with SSR Pleno e Sr

### ISSUE THREAD

**Issue by luisa-haddad** [frontendbr/vagas#388]
## Descrição da vaga

Buscamos perfis Seniors e Pleno para fazer parte de um projeto de 4 a 5 meses. É um freela alocado em Pinheiros. O projeto consiste no desenvolvimento de um portal com foco em SEO e fácil manutenção.

## Local

Co-Working, São Paulo - Pinheiros

## Requisitos

**Obrigatórios:**
- Conhecimento sólidos e experiência com React;
- Aplicação de Server Side Render;
- Gulp;
- Git;
- Integração com Web Service;
- SASS;
- HTML5;
- Crossbrowser;
- Flexbox;
- ES6;

## Contratação

PJ por tempo determinado

## Nossa empresa

VML Brasil - Mais informações no primeiro contato.

## Como se candidatar

Por favor envie um email para luisa.haddad@vmlbrasil.com com seu CV anexado - enviar no assunto: Vaga React Portal

- CV
- Projetos (GitHub, portfolio etc)
- Pretensão Salarial

**Comment by mtmr0x** [comment]
@luisa-haddad a vaga continua aberta?

**Comment by luisa-haddad** [comment]
Continua sim @mtmr0x Até o momento não encontrei a pessoa para preencher a vaga de Sênior.

**Comment by luisa-haddad** [comment]
@mtmr0x Não consegui nenhum contato portanto irei fechar essa e abrir uma nova sem ser alocado e somente para perfil senior, ok?
