### ISSUE TITLE
DESENVOLVEDOR FRONT-END PLENO NA KLB GROUP

### ISSUE THREAD

**Issue by Claulu3** [frontendbr/vagas#3882]
VAGA DESENVOLVEDOR FRONT-END PLENO - KLB GROUP

Requisitos:
 
- Superior completo na área de TI (Análise e Desenvolvimento de Sistemas, Sistemas de Informação, Ciência da Computação ou Engenharia da Computação)
 
- Experiência com AngularJS, Ionic Framework, Cordova, Capacitor, Microserviços REST
  
          Escopo:
 
- O profissional será responsável evolução de aplicativo mobile híbrido construído utilizando IONIC FRAMEWORK com backend NodeJS rodando em ambiente Kubernetes,
- Profissional atuará como um desenvolvedor Pleno de sistemas.
 

Atuação remota, local de trabalho quando houver reunião presencial: 
Jardim Paulistano, a 3 quadras do metrô Faria Lima 
 
Contratação PJ

       Benefícios:
•       20 dias corridos de férias por ano
•       Home office
 

      Email: clucena@klbgroup.com

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
