### ISSUE TITLE
[REMOTO/Braço do Norte SC] Front-end Developer na LOGPRO Sistemas para Saneamento

### ISSUE THREAD

**Issue by leandromartinz** [frontendbr/vagas#3886]
> Vaga Remota durante a pandemia

## Nossa empresa

A LOGPRO Sistemas para Saneamento é líder no segmento no Brasil, cresce exponencialmente  ano a ano, e tem uma proposta inovadora no setor.

## Descrição da vaga

Integrar desenvolvimento de software SAAS para saneamento na função de Front-end Developer.

## Local

Remoto ou no escritório em Braço do Norte/SC.

## Requisitos

**Obrigatórios:**
- Experiência com JAVA e Angular.

**Desejáveis:**
- conhecimentos em Spring Framework.
- conhecimentos em Docker.

**Diferenciais:**
- tecnologias inovadoras e ótimo ambiente de trabalho.

## Benefícios

- Vale alimentação.

**Diferenciais:**
- Horário flexível

## Contratação

PJ a combinar ou CLT

## Como se candidatar

Por favor envie um email para rh@logpro.com.br com seu CV anexado - enviar no assunto: Vaga Saneamento 4.0

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após cada processo.
E-mail para contato em caso de não haver resposta: leandro@logpro.com.br

#### Alocação
- Remoto

#### Regime
- CLT
- Freela
- PJ

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by JohnnyHonorato** [comment]
Bom dia. A vaga ainda esta aberta? Acabei de mandar um e-mail.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
