### ISSUE TITLE
[São Paulo] React Native Developer na UmHelp

### ISSUE THREAD

**Issue by MarceloPrado** [frontendbr/vagas#3887]
## Nossa empresa

💜 CONECTAMOS DIARISTAS COM QUEM QUER UMA CASA BEM CUIDADA 💜

Nós sabemos que gente extraordinária e motivada faz a diferença, e é por isso que somos uma empresa que acredita e valoriza as pessoas acima de tudo. Um time com paixão que usa a tecnologia a seu favor transformará a vida de milhares de diaristas.

👉🏼 [Site da UmHelp](https://www.umhelp.com/)

## Descrição da vaga

- Dar vida às telas projetadas e desenhadas em conjunto com a área de produto.
- Garantir que o tracking de eventos e ações do usuário no app estejam implementados e prontos para serem consumidos e analisados.
- Realizar integração das rotas entre o back e o front.
- Garantir que a experiência do usuário seja consistente em diversas plataformas.
- Garantir que os produto performem de maneira otimizada (baixo consumo de dados, memória e bateria).
- Manter o app das lojas atualizados seguindo alterações e documentações das mesmas.

## Local

Remoto, presencial ou um mix dos dois. Cada time decide seu modelo de trabalho 🤩
Nosso escritório fica em São Paulo - SP, no bairro da Vila Olímpia.

## Requisitos

**Obrigatórios:**
- 1 ano de experiência em desenvolvimento
- 6 meses de experiência com React

**Desejáveis:**
- Experiência com TypeScript
- Experiência com testes automatizados (Jest, Mocha ou outra biblioteca)

**Diferenciais:**
- Familiaridade com React Native
- Experiência com Redux ou outra lib de gerenciamento de estado

## Benefícios

- Acesso aos melhores mentores do mercado, em todas as áreas ⭐️
- Auxílio em cursos e certificações 🏫
- Possibilidade de stock options 💰

**Diferenciais:**
- Desafios para crescer. Você vai mudar a vida de muitas pessoas, impactando diretamente a economia brasileira, criando um ecossistema de diaristas com incríveis histórias para contar. Assim, vamos mudar o Brasil, juntos.
- Equipe horizontal e transparente, que não só valoriza seu conhecimento em sua área, mas quer te ver fazendo parte de discussões em nível estratégico.
- Ambiente descontraído, tranquilo e catalisador de criatividade e inovação.

## Contratação

PJ a combinar.

## Como se candidatar

Se interessou?
Nos envie um email para pessoas@da1help.com com o assunto “Frontend”, lembre-se de incluir o seu Github (e/ou Linkedin) contando um pouquinho sobre você. Se quiser já realizar o nosso desafio técnico é só acessar o https://bit.ly/39amkCq e nos avisar no mesmo email acima quando terminar.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até uma semana após cada processo.
E-mail para contato em caso de não haver resposta: luis.sertori@umhelp.com

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Júnior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by MarceloPrado** [comment]
@felipefialho pode fechar!
