### ISSUE TITLE
[São Paulo-SP] Fullstack Developer na Afya

### ISSUE THREAD

**Issue by marianeors1** [frontendbr/vagas#3888]
## Nossa empresa

A Afya está revolucionando o mercado de educação médica no Brasil e você pode entrar nesse movimento! Nascemos oficialmente em 2019, com o objetivo de sermos a principal parceira dos médicos em suas jornadas de formação, nós já formamos mais de 100 mil médicos pelo Brasil e contamos com um time de 4.000 pessoas para garantir que os nossos alunos possam transformar seus sonhos em realidade! Em plena pandemia pudemos ter maior noção de quão importante é o nosso papel, e por isso nesse estamos focados em expandir o nosso time de tecnologia para atender a todas as nossas unidades espalhadas pelo país. 

## Descrição da vaga

Trabalhamos principalmente com Javascript e muito focados em AWS, e buscamos pessoas comunicativas, com espírito empreendedor e dispostas a crescer exponencialmente com a Afya. Serão bem-vindos conhecimentos avançados em serviços Cloud e Git.

## Local

Remoto durante a pandemia, após será presencial em São Paulo

## Requisitos

**Obrigatórios:**
Javascript, Node.js, MongoDB, Redis, SQL, AWS, Git, Code Review, API Rest, HTML, CSS, Web Design Responsivo, Bash, React e React Native.

## Benefícios

Vale Transporte
Vale Refeição
Auxílio Médico
Auxílio Odontológico
Programa de Participação nos Lucros e Resultados (PLR)
Gympass
Política de Home Office

## Contratação

Modelo de Contratação: CLT

## Como se candidatar

através do link  https://byintera.in/1o0
#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
