### ISSUE TITLE
[Remoto] Full Stack Developer (Node & Vue.JS) @ Zoox Smart Data

### ISSUE THREAD

**Issue by VictorPinto-TechRecruiterZoox** [frontendbr/vagas#3889]
## Nossa empresa

Fundada em 2010 e presente em sete países, Zoox Smart Data é uma empresa de tecnologias e soluções integradas de Big Data e Analytics que digitaliza serviços, captura dados, enriquece e entende a experiência das pessoas.

Com mais de 100 colaboradores e presente em Rio de Janeiro, São Paulo, Argentina, México, Espanha, Estados Unidos e Portugal, a Zoox desponta como uma das startups mais promissoras do Brasil. Venha fazer parte do nosso time!

## Descrição da vaga

Através de reuniões de planejamento, analisar demandas junto com o time e estimar prazo para cada tarefa.

Criar e manter features em linguagem Node.js, utilizando o framework Koa ou o respectivo framework do projeto.

Criar e manter features em linguagem Javascript, através da utilização de frameworks de desenvolvimento de interface com o usuário (Vue.js).

Realizar manutenção em bugs de baixo e médio impacto, observando o que foi definido pela área de produtos, time de arquitetura e/ou membros do time.

Definir com o time de Arquitetura, a forma como as tarefas serão desenvolvidas (código fonte).

Revisar código dos membros do time. Propor soluções. Avaliar e sinalizar necessidade de refactoring do código.

Promover ações para guiar e estimular o time, a utilizar sempre as melhores práticas de desenvolvimento, definidas pela empresa.

Definir soluções técnicas para as demandas complexas, graves e/ou críticas.

Desenvolver soluções com foco em escalabilidade e custo.

## Local

Remoto

## Requisitos

Experiência em desenvolvimento em ambiente Linux

Experiência em desenvolvimento utilizando Veu.JS.

Experiência com framework de desenvolvimento Node.js (Express, Koa, etc)

Experiência em projetos distribuídos com microserviços

Trabalhar com ORM Node, como por exemplo mongoose

Banco de dados SQL e NoSQL

Conhecimento de qualquer framework JavaScript de desenvolvimento de interface com o usuário

Experiência em projetos utilizando a metodologia Scrum

Conhecimentos de elasticsearch

Conhecimento de serviços AWS tais como: EC2, Elastic Beanstalk, RDS, SQS, ElastiCache e Lambda

Conhecimento ferramentas de monitoramento de ambientes de desenvolvimento (exemplo: New Relic)

Desejável conhecimentos com CI/CD

Desejável conhecimentos em GraphQL.

## Benefícios

Plano de saúde
Plano Odontológico
Seguro de vida
VR ou VA de R$ 27/dia

## Contratação

CLT

## Como se candidatar

Por favor, envie um e-mail para victor.pinto@zooxsmart.com com seu CV anexado. Enviar no assunto: Github_Full Stack Developer (Node &Vue.JS)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: victor.pinto@zooxsmart.com

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by VictorPinto-TechRecruiterZoox** [comment]
UP

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by VictorPinto-TechRecruiterZoox** [comment]
Continuamos com vagas abertas!
