### ISSUE TITLE
[Belo Horizonte] - Front-End Developer React Pleno

### ISSUE THREAD

**Issue by bielcapanema** [frontendbr/vagas#389]
## Descrição da vaga
Trabalhar em uma startup promissora na área de seguros e assistência 24hrs.

## Local

Belo Horizonte - MG 
Alocado/Remoto

## Benefícios

A combinar

## Requisitos

**Obrigatórios:**
- React
- Redux
- Middlewares
- JavaScript avançado
- ES6
- Git
- API REST

**Desejáveis:**
- Experiência com APIs Java

**Diferenciais:**
- Perfil empreendedor

## Nossa empresa

https://reboque.me/

## Contratação

PJ ou CLT

## Como se candidatar

Enviar currículo, portfólio, github e pretenção para: samuel.freire@reboque.me : Vaga Dev FrontEnd

**Comment by mtmr0x** [comment]
@bielcapanema a vaga continua aberta?

**Comment by bielcapanema** [comment]
@mtmr0x Foi preenchida.

**Comment by highfeed** [comment]
@bielcapanema @Adiltons Hello! Check the update.
