### ISSUE TITLE
[REMOTE] Angular Front-end Developer na CloseCare

### ISSUE THREAD

**Issue by Egarter** [frontendbr/vagas#3890]
Empresa: CloseCare
Faixa salarial: A combinar
Estado: São Paulo
Local da vaga: Remoto
Nível: Sênior
Aceita Remoto?: Sim

**Descrição da vaga:**

A Closecare é uma plataforma de gestão de saúde para RH e médicos do trabalho de médias e grandes empresas!

A nossa grande missão aqui na Closecare é descomplicar a saúde corporativa, ajudando as empresas a (i) identificar os funcionários que mais precisam de cuidado de saúde e a (ii) coordenar as ações dos prestadores de serviço de saúde (ex: médico do trabalho, saúde ocupacional, corretora, operadora e etc) em torno destes principais casos! Cuidar da saúde do funcionário implica em ganhos significativos de produtividade, melhoria no ambiente de trabalho e em reduções drásticas em custos importantes como o custo do plano de saúde!

E toda esta história começa na gestão do atestado médico..

Quer saber mais? Vamos conversar!

**Requisitos**

- Requisito básico:
Alinhamento de valores!
Se você tem vontade de construir algo relevante e pensa grande, contamos para você os outros valores quando nos conhecermos!

- Requisitos técnicos:

- Experiência em programação web;
- +3 anos de experiência com programação em Angular / Typescript
- Experiência com SPA (single page application)

Se interessou?
Se inscreva pelo FrontJobs!
http://www.frontjobs.com.br/job/147/

Qualquer dúvida, é só falar.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
