### ISSUE TITLE
[REMOTO / Curitiba-PR] Pessoa Engenheira de software Frontend @ Trackmob

### ISSUE THREAD

**Issue by focezar** [frontendbr/vagas#3891]
## Nossa empresa
A Trackmob é uma empresa de IMPACTO SOCIAL, com a missão de transformar a sociedade empoderando as instituições que buscam fazer o bem. Atendemos Organizações sem Fins Lucrativos como UNICEF, Médicos Sem Fronteiras, sem contar outras centenas de grandes, médias e pequenas instituições.

## Descrição da vaga
Buscamos em nosso time profissionais que sejam capazes de lidar com os seguintes desafios:
- Compreensão e entendimento de features a serem desenvolvidas, assim como manutenções necessárias;
- Criação de telas baseadas em detalhamentos informados pelo time de produto;
- Participar do planejamento das sprints para mapear todos os requisitos técnicos para uma entrega de qualidade;
- Executar codeview de outros desenvolvedores;
- Trabalhar em time para resolver problemas.

## Local
Remoto ou Escritório (Centro Cívico, Curitiba - PR)

## Requisitos

**Obrigatórios:**
- Experiência em HTML, CSS e JavaScript;
- Conhecimentos sólidos sobre Vue.js;
- Conhecimentos básicos de UX e UI;
- Organizar arquitetura e componentes dos recursos a serem desenvolvidos;

**Desejáveis:**
- Experiência com integração de APIs;
- Experiência com Nuxt;
- Experiência com NPM e/ou Yarn;
- Experiência com SaaS;

**Diferenciais:**
- Experiência anterior ou interesse em trabalhar em ambiente inovador de Startup;
- Experiência com React;
- Experiência com React Native;
- Experiência com Node.js;
- Experiência com metodologias ágeis.

## Benefícios
- Descanso Remunerado já nos primeiros 6 meses de empresa.
- Day-off de aniversário.
- Acesso à plataformas de estudos a distância.
- Auxílio laptop caso queria usar o seu próprio PC.
- Horário Semi-Flexível
- Licença Maternidade/Paternidade com mais de uma opção de tempo/trabalho
- Realização de sentir que o seu trabalho tem um impacto real em diversas causas sociais.
- Contratação

## Contratação
PJ

## Como se candidatar
Para se candidatar, acesse o link: https://trackmob.recruiterbox.com/jobs/fk0qbtg

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
