### ISSUE TITLE
[REMOTO] Fullstack Developer Pleno Typescript @Profitfy.me 

### ISSUE THREAD

**Issue by profitfyme** [frontendbr/vagas#3892]
## Nossa empresa

Somos uma startup de inovação & tecnologia fundada em
2016, visando solucionar problemas e automatizar processos
no mercado de e-commerce e digital.

## Descrição da vaga

A nossa empresa começará desenvolver uma solução de pagamentos para e-commerce.

Nós trabalhamos com novas tecnologias e por isso valorizamos os profissionais que são abertos a aprender novas coisas e não tem medo de sair de sua zona de conforto.

### Principais atividades:
- Desenvolvimento de telas a partir de layouts (feitos por nossos UI/UX designers) com React + TypeScript;
- Desenvolvimento de projetos NodeJS + TypeScript;

## Local

Remoto ou Escritório, São Paulo - Jardim São Paulo

## Requisitos

**Obrigatórios:**
- Experiência de desenvolvimento de projetos com Typescript;
- Experiência com React Hooks, Context.

**Desejáveis:**
- Conhecimento em AWS;
- Conhecimento em Docker;
- Conhecimento em CI/CD;
- Conhecimento em Clean Architecture;

**Diferenciais:**
- Ter trabalhado com areas relacionadas e-commerce

## Contratação

Salário: Entre R$5.000,00 e R$8.000,00 - PJ.
Horário: 40h semanais - Segunda a Sexta.

## Como se candidatar

Link para se candidatar: https://forms.gle/Tb7qcWG4rHktc1GU9

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
