### ISSUE TITLE
[São Paulo] Front-end Angular Pleno - Capgemini

### ISSUE THREAD

**Issue by 18021984-gif** [frontendbr/vagas#3896]
Localidade: São Paulo 
OBS: Nesse momento 100% remoto e pós pandemia 2 dias remoto e 3 dias presenciais. 

Requisitos: 
Superior Completo na área de tecnologia 
Experiência como desenvolvedor front end 

Requisitos desejáveis: 

NET FRONT-END: Framework Front-end angular; 
Ferramenta de versionamento - GIT; 
Type Script e Java Script; 
Experiência em HTML, JSON, CSS, JAVA SCRIPT, avançados; Sass, SCSS; Custom Components; Interface para Mobile (responsive, adaptativo, user behaviour etc.) Conhecimento em back-end.

Candidatos interessados enviar o Cv com pretensão salarial para recrutatecnologias@gmail.com , colocando Front End no assunto

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
