### ISSUE TITLE
[Remoto] Front-end Vue.js Senior Developer @ SuperViz

### ISSUE THREAD

**Issue by brunokunace** [frontendbr/vagas#3898]
## Nossa empresa

Nós da SuperViz, procuramos um desenvolvedor frontend sênior. 
Somos uma startup remote-first com colaboradores espalhados ao redor do mundo, com investimento internacional, trabalhando em tecnologias inovadoras de colaboração em ambientes imersivos. 
Conheça mais do nosso trabalho aqui https://www.superviz.com

## Descrição da vaga

Procuramos um(a) desenvolvedor(a) frontend vue.js sênior para nosso projeto principal, o SuperViz. Trata-se de uma ferramenta colaborativa que integra RTC, ambientes imersivos de 360˚ e VR.

## Local

Remoto

## Requisitos

**Obrigatórios:**
 - Vue + Vuex
 - JavaScript
 - Experiência com testes unitários(JEST) m projetos com 100% de cobertura
 - HTML5
 - CSS3 / Pré processador (Sass)

**Desejáveis:**
- Three.js ou experiência com algum framework 3D

**Diferenciais:**
 - Experiência na criação de componentes e manutenção de design system 
 - A-Frame

## Contratação

A combinar

## Como se candidatar

Para aplicar, envie seu currículo e github para jobs@superviz.com

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
