### ISSUE TITLE
[Remoto] Front-end Developer Pleno @ Helpet (Itália)

### ISSUE THREAD

**Issue by fernandohenriques** [frontendbr/vagas#3899]
## Nossa empresa

Somos uma startup jovem, muito jovem (menos de um ano), baseada na Itália. Nosso objetivo é criar soluções diversas para pets e seus donos. Nosso principal produto já está no ar na Itália (Helpet App) e foca em uma série de soluções que fazem sentido no mercado italiano, que é bastante friendly para pets. Algumas das soluções que já temos neste App:
 - Pet ID (documento digital que na Itália funciona como RG/CPF do Pet);
 - Gerenciamento de receitas e vacinas para seu pet, integrado com serviços do governo da Itália;
 - Mapa com 20k parceiros (empresas que prestam serviços diversos para pets), onde o usuário pode encontrar o serviço ou produto que precisa mais perto dele.

Estamos em franco crescimento e pretendemos escalar tanto na Itália, como para outros países. Temos um backlog interessantíssimo a sua espera. Se você gosta de escrever software de qualidade e que seja hiper relevante para seus usuários, vem conosco. 

P.S.: O idioma corrente é o português. Todo o time de desenvolvimento está baseado no Brasil.

## Descrição da vaga

Estamos em busca de um profissional que tenha experiência com aplicações React/Vue.js, e que esteja interessando em focar em mobile com React Native. Isto porquê grande parte da dedicação será à este App principal, citado acima, que foi construído com React Native. Temos também um sistema administrativo construído com React Admin e poderemos ter outras soluções no futuro. Tal profissional integrará um time multidisciplinar, tendo contato constante com profissionais de produto e UX/UI, e colaborará na construção/manutenção de tais soluções de forma pró-ativa, tendo espaço constante para proposição.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- JavaScript
- React.js ou Vue.js (nossa stack é React, mas acreditamos que a curva não é grande para profissionais curiosos ;))
- Experiência com gerenciamento de estado global (Redux / Mobx / Apollo Client)
- Styled Components
- Jest
- Enzyme / Vue Test Utils / React Testing Library / Vue Testing Library

**Desejáveis:**
- GraphQL
- Apollo Client
- App publicado (ou site/aplicação web) para mandar para gente dar uma olhada

**Diferenciais:**
- Experiência com desenvolvimento de apps com React Native
- Sólidos conhecimentos das plataformas nativas Android e/ou IOS
- Experiência com desenvolvimento de APIs com Node.js

## Benefícios

 - Horário 100% flexível;
 - Irá trabalhar com devs muito experientes (e caprichosos), que podem te ofertar uma mentoria para te ajudar a dar o próximo passo na carreira.

## Contratação

PJ a combinar

## Como se candidatar

Para aplicar, envie um email para fernando@helpetapp.com com seu currículo, Github e LinkedIn - Assunto: Vaga Front-end Pleno.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by iurybrasileiro** [comment]
@fernandohenriques bom dia tudo bem? Man qual a faixa salarial?

**Comment by fernandohenriques** [comment]
@iurybrasileiro Vai depender da sua performance no processo seletivo.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
