### ISSUE TITLE
[São Paulo] Desenvolvedor Rails/Front-End - loldesign

### ISSUE THREAD

**Issue by henriquesacramento** [frontendbr/vagas#39]
## Descrição da vaga

Rails/Front End
## Local

Escritório, São Paulo - Mooca
## Benefícios
- VR
- VT
## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Desenvolvimento Web
- Experiência em criação de UX (photoshop, illustrator)

**Desejáveis:**
- conhecimentos em ruby on rails

**Diferenciais:**
- projetos opensource
## Contratação

PJ a combinar
## Nossa empresa

Somos uma Software House localizada em São Paulo – SP. Nosso foco atual é desenvolver software para StartUP.
## Como se candidatar

Por favor envie e-mail para paulo@loldesign.com.br com assunto (Desenvolvedor Front End/ Web Designer)

**Comment by LFeh** [comment]
Boa sorte @henriquesacramento

**Comment by rkb81** [comment]
Putz a vaga seria show de bola, mas são 3horas pra ir de casa.

**Comment by henriquesacramento** [comment]
@rkb81 Vem morar em SP :P

**Comment by LFeh** [comment]
@henriquesacramento A vaga foi preenchida?

**Comment by henriquesacramento** [comment]
Ainda estamos recebendo CV.

**Comment by LFeh** [comment]
;)
