### ISSUE TITLE
[São Paulo] MEAN Developer

### ISSUE THREAD

**Issue by rafaelcunha123** [frontendbr/vagas#390]
## Descrição da vaga

Buscamos desenvolvedores que auxiliem nosso time a desenhar, projetar e implementar nossa plataforma web (MEAN Stack). 
Para que isso seja possível, nossos devs devem se interessar profundamente pelo modelo de negócios, pela experiência do usuário e pelos problemas propostos por nosso clientes. Adorar programar, aprender e estar às margens da evolução tecnológica também é essencial.
Nosso time não se importa com hierarquias -> esteja preparado para lutar pelo mérito de suas ideias e para vê-las implementadas.
Nosso time não se importa com hierarquias 2 -> TODOS falam com clientes, dão suporte, analisam dados e programam.
Não há melhor hora de se juntar a nós. Esteja entre os primeiros hires da startup que transformará a saúde no Brasil.

## Local

São Paulo - SP, em frente ao Allianz Parque.

## Benefícios

- Horários 100% flexíveis
- No dress code
- Organização flat (devs impactam produto e negócio)

## Requisitos

**Obrigatórios:**
- MEAN Stack, com Angular SÓLIDO.
- Git
- HTML & CSS
- Inglês Fluente

**Desejáveis:**
- Webpack
- AWS
- Cordova / PhoneGap
- Experiência com testes

## Contratação

A combinar

## Nossa empresa

A eDoc Saúde está criando uma plataforma única que reúne pacientes, médicos, convênios e farmácias. Hoje temos um produto de gestão hospitalar na nuvem com mais de 10 mil atendimentos realizados em dois meses de operação. Nossa tração nos levou a trazer a bordo investidores e advisors que, além de acreditar no nosso modelo único de negócios, nos ajudarão a crescer exponencialmente nos próximos meses.
 
Não temos dress code, nem formalidades. Trabalhamos muito e somos completamente flexíveis com horários. Focamos no relevante - resultado final e experiência do cliente.

## Como se candidatar

Envie um e-mail para jobs@edocsaude.com com o título “Vaga MEAN Developer” com o CV no anexo. Enviar um portfólio de projetos implementados é um bom diferencial.

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by rafaelcunha123** [comment]
Sim! Ainda estamos contratando. 

Enviado do meu iPhone

**Comment by vinyguedess** [comment]
Enviado

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
