### ISSUE TITLE
[Remoto] Front-end Developer Sênior na Accenture

### ISSUE THREAD

**Issue by albuquerque-dev** [frontendbr/vagas#3900]
Existem algumas vagas para um projeto global contratação direta com a empresa CLT, projeção de carreira, preciso de dev front end senior, que tenha experiência com angularjs, bootstrap e conhecimento em d3js(adicional).

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
