### ISSUE TITLE
[Remoto] FullStack Developer na bxblue

### ISSUE THREAD

**Issue by Rebeccapz** [frontendbr/vagas#3902]
## Nossa empresa

Bxblue é uma fintech que tem como missão ajudar as pessoas a terem acesso ao crédito pessoal mais barato do país. Fomos investidos por grandes nomes do cenário nacional e internacional. Entre eles o Y Combinator, acelerador responsável por empresas como AirBnB, Dropbox, Heroku, Docker e Twitch.

Tivemos a honra de ser selecionados pelo Banco do Brasil para co-criarmos juntos o primeiro API de Empréstimo do Brasil. Estávamos na lista das 100 startups para ficar de olho em 2019.

Nascemos em Brasília mas sempre fomos e seremos remotos. Por isso a vaga é para trabalhar full home office.

## Descrição da vaga

Você atuará em equipe para discutir, desenhar e construir soluções estratégicas para problemas reais. Indo da compreensão a entrega e acompanhamento do valor gerado.
Nossa stack não é nossa lei, nosso interesse é encontrar as melhores ferramentas. Aqui você terá espaço para se desenvolver e aprimorar nas tecnologias que usamos e na escolha de novas opções.

Você nos ajudará em diversos desafios:

- Pode ser junto ao usuário, ajudando-o a resolver as dificuldades com o produto;
- Resolvendo problemas próximo aos times de negócio (marketing ou atendimento);
- Otimizando as nossas integrações em conjunto com as equipes dos bancos parceiros;
- Desenvolvendo soluções que otimizem suas atividades ou integrando com ferramentas internas e externas.

Vamos te receber com um **onboarding estruturado** para te dar a ideia geral do mundo bxblue, você também terá um padrinho ou madrinha para te ajudar com todas as suas dúvidas do produto, ferramentas ou sobre a bxblue.

Por fim suas responsabilidades virão de acordo com a sua senioridade e, também, com seu tempo de casa.

## Local

Remoto

## Requisitos

Estamos em busca de talentos em **todos os níveis**, por isso nossos requisitos mínimos são apenas:

- Se sentir a vontade no desenvolvimento, manutenção e deploy de aplicações web;
- Ter vontade de trabalhar em diversas frentes do projeto, tendo uma visão mais generalista;
- Se envolver com nosso propósito e nos ajudar com a nossa missão.

Vamos ressaltar que você não precisa ser fluente na nossa Stack de Desenvolvimento. Nós te damos **o espaço e apoio** necessário para desenvolver suas habilidades conosco. 

Mas se ficou curioso, hoje trabalhamos majoritariamente com Ruby on Rails, React, MongoDB e Heroku + AWS

## Diversidade

Estamos crescendo e com isso diversidade passou a ser uma das mais importantes pautas no nosso processo de seleção. Entendemos que hoje, mesmo com um time diverso, ainda temos muito o que caminhar. Estamos construindo programas que nos ajudem na inclusão de mais pessoas que sofrem discriminação sistêmica para dentro time. Nosso foco está nas mais diversas minorias como pessoas negras, indígenas, trans, refugiadas e mulheres, mais não se limitando apenas a estas. Por isso, se você faz parte de um dos grupos minoritários, te convidamos e encorajamos a participar desse processo seletivo. Queremos conhecer você e ouvir a sua perspectiva!

E caso queira entender como estamos construindo isso vem conversar com a gente, podemos te colocar em contato com uma das pessoas que estão a frente do projeto.

## Contratação

Procuramos pessoas de todos os níveis de experiências. Ou seja, se você está ainda no começo da carreira ou já tem muita estrada, temos espaço!

A remuneração para esta vaga depende do nível em que a pessoa se encaixar podendo ir de R$ 5.600,00 a R$ 16.600,00.

## Como se candidatar

Se inscrever na nossa pagina de carreiras https://apply.workable.com/bxblue/j/F4BC875C2C/

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Regime
-Ruby
-ReactJS

#### Regime
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by RobsonGap** [comment]
**Currículo   Enviado .!**

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
