### ISSUE TITLE
[Florianópolis] React.js | React Native Software Engineer na Cheesecake Labs

### ISSUE THREAD

**Issue by cheesecakelabs-challenges** [frontendbr/vagas#3904]
Cheesecake Labs is a software design and engineering partner that builds tech products.

With locations in California and Brazil, we have been building apps since 2013. We know the process and empower a multidisciplinary team of 60+ designers, engineers, and project managers to deliver delightful solutions.

If you’re an enthusiastic, talented, and resourceful Software engineer with the relevant skills & IT experience, let's talk about creating disruptive products, with an international and multidisciplinary team.

We offer home office policy, health & dental care, career plan, meal allowance, Profit Share Program (PPLR), Gympass, flexible working time, additional benefits (massage, yoga, English classes, nutritionist, parking lot, fuel assistance, psychotherapy, and education allowance), videogames, library, scooter, hoverboard, above-average salary, events and courses budget, 24/7 snacks, beers, and a unique work environment.

**Some activities you would do on a typical day at Cheesecake Labs**
Develop and maintain Web applications
Interact with other teams and professionals, including other developers, designers, project managers, and stakeholders
Create outstanding front-end interfaces
Make sure the application has a great user experience
Assist in the creation and implement mockups
Develop and maintain Backend solutions using Django, NodeJS
Build docker images that can run on top of AWS or other PaaS
Model databases using MySQL, Postgres, DynamoDB
Write beautiful, readable, and scalable code
Review the code of other developers
Make sure the application solves real-world problems
Understand the needs of our partners and come up with solutions for their problems
Participate in Sprint Plannings and daily stand-up meetings
Build estimates and plan roadmaps

**In order to succeed, you'll likely need the following skills**
Experience with Javascript, CSS, and HTML
Experience with ReactJS, React Native, and/or other Single Page Application libraries
Experience with Git
Experience with RESTful backend applications, specially built with Django
Experience with deployment processes using Docker, CircleCI, AWS, Heroku
Experience with different databases
Experience with UNIX systems and terminal
Knowledge about clean code, design patterns, and reactive programming
Knowledge about basic design principles
Being self-taught
Being up-to-date with the latest news and technologies about Frontend and Backend
English proficiency
Good communication skills, both in verbal and writing

This is a full-time (CLT) position located in our cool Florianopolis/SC office.
Salary may vary according to our career path.

Apply at: https://cheesecake.recruiterbox.com/jobs/fk0m2vk/

We are an equal opportunity employer and embrace, support, and value diversity at our company for the benefit of our employees, our products, and our community. We do not discriminate on the basis of race, religion, ancestry, color, national origin, gender identity, sexual orientation, age, citizenship, marital status, or disability status. If you have a disability or special need that requires accommodation, please let us know at careers@cheesecakelabs.com.

Cheesecake Labs continues to hire for all open roles, all interviewing and onboarding are done virtually due to COVID-19. Everyone new to the team and our current staff will temporarily work from home until it is safe to return to our office.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
