### ISSUE TITLE
[Remoto] React Developer na Zygmus

### ISSUE THREAD

**Issue by pablonajt** [frontendbr/vagas#3905]
## Nossa empresa

https://zygmus.com

## Descrição da vaga

For a customer in the US, we are looking for a fully remote React Developer to work in English as a freelance. Rates in USD (based on experience)

## Local

100% Remoto

## Requisitos

**Obrigatórios:**
- Excellent English (to be able to work directly with the customer in the US)
- 2+ anos de experiência com React
- 5+ anos de experiência com Software Development (Sênior/Especialista)

**Desejáveis:**
- conhecimentos em React Native, Javascript, HTML & CSS
- conhecimentos em Git 

**Diferenciais:**
- Experience working remotely in English

## Contratação

A combinar

## Como se candidatar

Por favor envie um email para talent@zygmus.com com seu CV anexado - enviar no assunto: Vaga React

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 30 dias após cada processo.
E-mail para contato em caso de não haver resposta: talent@zygmus.com

#### Alocação
- Remoto

#### Regime
- Freela

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
