### ISSUE TITLE
[Remoto] Front-end Developer na McFadyen

### ISSUE THREAD

**Issue by Startec-Jobs** [frontendbr/vagas#3909]
## Nossa empresa

A McFadyen Digital é uma agência global de comércio digital com mais de 30 anos de história em inovação para mais de 250 das principais marcas do mundo, como ABB, AB InBev e Cruz Vermelha Americana. 

Oferecem serviços de comércio digital, marketplace, marketing digital e experiência do usuário (UX), em escritórios localizados na América do Norte, América do Sul e Índia contando com um total de 125 colaboradores. 

“Por meio de nosso modelo de fornecimento global, oferecemos aos nossos clientes as vantagens competitivas de implantação rápida, com qualidade de classe mundial e custos reduzidos.”

McFadyen Digital é o principal consultor e implementador de soluções de mercado online. Durante 15 anos de implementação de marketplaces, construíram dezenas de plataformas que geram cumulativamente bilhões de dólares de GMV. 

Desde 2019, o escritório do Brasil atende apenas clientes internacionais. Essa mudança de cenário fez com que o número de projetos aumentasse e aumentasse nosso time também. 

“Nossa missão é tornar-nos o principal provedor de serviços para empreendimentos digitais e com isso viabilizar o sucesso de nossos clientes por meio de tecnologias transformadoras.”

mcfadyen.com/

## Descrição da vaga

A McFadyen está com vaga para Front-End Developer! Venha conhecer essa oportunidade para trabalhar em uma empresa reconhecida internacionalmente e considera a Great Place To Work. 

**Atividades da vaga: **

Manter e desenvolver componentes da aplicação
Implementar designs produzidos por outras áreas
Entender os requisitos de software para desenvolvimento

**Perfil desejado:**
Habilidade de trabalhar em equipe 
Alinhamento forte com os valores da empresa: foco no usuário, controle sobre resultados, adaptabilidade e colaboração

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Alto conhecimento Javascript, HTML e CSS
- Experiência de 3 anos ou mais com desenvolvimento front-end
- Inglês avançado ou fluente

**Desejáveis:**
- Conhecimento em Git
- Conhecimento em Webpack 
- Conhecimento em UX Design

## Benefícios

- Remuneração: R$ 7.000,00
- Plano de Saúde
- Plano odontológico
- Vale alimentação

## Contratação

PJ ou CLT

## Como se candidatar

Através do link https://bit.ly/McF-Dev-Inscricao

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: suporte@startecexp.com

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
