### ISSUE TITLE
[Brasília] Frontend Developer 

### ISSUE THREAD

**Issue by ianzitow** [frontendbr/vagas#391]
## Descrição da vaga

Vaga para trabalho em projetos envolvendo HTML5, CSS3 e JavaScript. Utilizamos o Angular como framework. 

## Local

Escritório na Asa Norte, Brasília, DF ou Remoto

## Benefícios

- Ambiente com puffs, Xbox, café & snacks
- Internet padrão Campus Party™
- Possibilidade de trabalho remoto;

## Requisitos

**Obrigatórios:**
- 1 ano de experiência com Angular
- 2 anos de experiência com CSS3
- 2 anos de experiência com HTML5

**Desejáveis:**
- Ser um membro proativo em nosso time usando metodologia ágil de desenvolvimento;
- Conhecimentos em Ruby on Rails
- Codificação de software com testes unitários e funcionais
- Ajudar o time a priorizar e encontrar jeitos inovadores de alcançar objetivos
- Ter capacidade de trabalhar independentemente

**Diferenciais:**
- Conhecimento de outros frameworks de frontend, como React

## Contratação

A combinar.

## Nossa empresa

Somos uma empresa especializada no desenvolvimento de aplicativos para iOS e Android. Queremos unir a beleza de um bom design com a eficiência de códigos-fontes de alta qualidade. Temos experiência no desenvolvimento de web sites, design e apps móveis para celulares. Atuamos em todos os ramos de negócio, desde restaurantes a salões de beleza.

## Como se candidatar

Por favor, enviar currículo e, se possível, exemplos de projetos para jobs@yimobile.com.br, com o título "Vaga em Desenvolvimento Frontend".

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
