### ISSUE TITLE
[Campinas] Front-End Developer na Superlógica

### ISSUE THREAD

**Issue by hugofabricio** [frontendbr/vagas#3910]
> Vaga Remota durante a pandemia

## Descrição da vaga

O Grupo Superlógica é formado por marcas diversas, abrangentes e que se comunicam com diferentes públicos. Estamos procurando por uma pessoa desenvolvedora Front-End que nos ajudará a projetar belas páginas com soluções e tecnologias modernas, bem como auxiliar em nosso Design System e sua difusão por todos os produtos da nossa empresa. O(a) profissional irá trabalhar dentro de um time dedicado a comunicação de marca junto de designers, front-ends e videomakers.

﻿Buscamos um perfil inquieto, que queira rapidamente promover mudanças e evolução em tudo o que fazemos. O trabalho do Design Team da Superlógica, acima de tudo, é de criar, promover e solidificar uma cultura de consistência no uso das marcas e na direção de arte para nossas comunicações independente do suporte de aplicação, buscando a intersecção entre criatividade e coerência na construção dessas marcas. Procuramos alguém com experiência em resolver e alicerçar questões de consistência visual por meio do código com marcas e/ou contextos de comunicação complexos.

## Local

Escritório, Campinas - Vila Teixeira

## Requisitos

**Obrigatórios:**
- HTML, CSS e Javascript
- React
- Flexbox e CSS Grid
- Mobile First e Web Design Responsivo
- Noções de API Rest
- ES6+
- Styled-component e outras técnicas de CSS-in-JS
- Pré-processadores: SASS, Less ou Stylus

**Desejáveis:**
- NextJS ou GatsbyJS
- SEO e técnicas de acessibilidade como WAI-ARIA
- PHP Básico
- Ser ativo nas comunidades de desenvolvimento

## Benefícios

- Flexibilidade de horário
- Restaurante interno
- Vale transporte ou auxílio combustível (fixo, sem desconto)
- Estacionamento
- Plano de saúde
- Plano odontológico
- Auxílio farmácia: desconto de até 20% em medicamentos nas redes Droga Raia e Drogasil
- Auxílio creche
- Se tornar mãe ou pai é algo espetacular, por isso damos todo o apoio: tanto a licença-maternidade como a paternidade são estendidas

**Diferenciais:**
- Honest Market e cantina via PicPay
- Fácil acesso ao board da empresa
- Biblioteca com mais de 200 títulos
- EADbox interno sobre nossas verticais, para você não cair de paraquedas, entre outros incentivos para você desenvolver-se
- Ambiente que valoriza feedbacks e 1:1

## Contratação

CLT

## Como se candidatar

Através do Gupy no link [https://superlogica.gupy.io/jobs/576609](https://superlogica.gupy.io/jobs/576609)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até uma semana.
E-mail para contato em caso de não haver resposta: rh@superlogica.com

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno

## Nossa empresa

Nosso propósito é transformar o mundo através do empreendedorismo! 

Fazemos isso criando produtos e serviços inovadores, ousados, úteis e apoiamos a transformação na mentalidade das empresas, trazendo palestrantes internacionais e nacionais em eventos como o Superlógica Xperience e o Superlógica Next.

Somos líderes no mercado de software de gestão financeira para empresas de pagamentos recorrentes como administradoras de condomínios, imobiliárias, SaaS, serviços por assinatura, escolas e cursos.

Isso é ser superlógico!

A nossa cultura é o nosso principal ativo intangível. Nos dá a coragem, a humanidade, a ousadia e força necessárias para transformar o mundo através do empreendedorismo. Ela nos torna uma empresa sempre à frente em busca de inovação e desafios.

O que nos move é resolver problemas, melhorar as experiências dos clientes e contribuir para um mundo melhor, mais justo e humano.

Somos centrados em pessoas e resultados de longo prazo em um ambiente colaborativo, que valoriza a transparência, experimentação e ousadia.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by hugofabricio** [comment]
@felipefialho, vaga preenchida, obrigado!
