### ISSUE TITLE
[São Paulo/SP] Desenvolvedor front-end no ITeam

### ISSUE THREAD

**Issue by VivianeRHTI** [frontendbr/vagas#3912]
## Descrição da vaga

Desenvolvimento de soluções satélites web e mobile.

## Local

São Paulo/SP - Lapa (100% Presencial).
Necessário disponibilidade para atendimento somente presencial.

## Requisitos

Experiência em desenvolvimento Front-End React e React Native (mobile).
Conhecimentos em HTML, CSS, Javascript.
Ter atuado em equipes dinâmicas e metodologias de desenvolvimento ágeis.

## Contratação

Tempo indeterminado 
PJ ou á combinar. 

## Nossa empresa

Há mais de 15 anos presente no mercado, a ITeam oferece o comprometimento com o cliente.
Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 
O relacionamento da ITeam é baseado no amplo comprometimento com os valores e objetivos dos nossos Clientes, fornecendo soluções e serviços de TI que contribuam para a realização de seus objetivos.

## Como se candidatar

Envie um e-mail para viviane.pereira@iteam.inf.br com seu currículo atualizado e pretensão de taxa/hora - enviar no assunto: Vaga no GITHUB - Front React Presencial

## Labels

- 🏢 Horário comercial
- 🏢Presencial
- 👨 Pleno
- 👴 Sênior
- ⚖️ PJ

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
