### ISSUE TITLE
[REMOTO] Front-end Developer na MAXIHOST

### ISSUE THREAD

**Issue by claudiafeijo-hr** [frontendbr/vagas#3914]
**Frontend Development at Maxihost**

At [Maxihost](https://www.maxihost.com/), we are passionate about making the cloud more straightforward and faster. We work at the physical infrastructure layer, building products and solutions that automate the deployment and management of bare metal servers. We don’t use strict methodologies or copy industry standards. We’ve created our own workflow, which allows us to work calmly and productively. This workflow is public and can be found [here](https://www.notion.so/maxihost/How-we-work-51df61186a924e97ad4c05a4a5106c96).

We work in an agile and highly collaborative environment, with many members of the Engineering team working remotely. You will also have the option to work from our offices in São Paulo or Florianópolis.

**About the team and role**

We love building beautiful, accessible, and intuitive experiences, mostly for our website and dashboards. We are now working on a whole new dashboard experience, which will completely change how customers interact with our product. While at it, you will also have the opportunity of working on open source projects like Metal UI.

You might be a fit for this role if you consider yourself an enthusiastic and resourceful software engineer who is passionate about building great products, someone who loves being part of a team, whilst enjoying the autonomous nature of working remotely.

**You will**

- Plan, build, test, and release new features and experiments in Javascript and React.
- Develop and improve the components that make our website and dashboard.
- Work with designers to build a new dashboard from the ground up, using modern technologies like Next.JS, PostCSS, and more.
- Participate in design reviews and share your work regularly with Engineering leadership.
- Collaborate with engineers across the department to identify and build on improvements to our processes and systems.
- Sometimes work on very broadly defined, loose concepts, and sometimes on narrowly defined, tactical deliverables.
- Understand the array of technical constraints, user goals, and business requirements that shape a product.

**You might be a fit for this role if**

- You have a strong technical background and consider yourself an expert in HTML, CSS, and Javascript.
- Have front-end development experience, building, running, and debugging web applications using modern JS frameworks (React, Angular, etc).
- You like to write and run tests and believe stability is instrumental to build great user experiences.
- You are either an English-native or have proficiency in both writing and speaking the language. 
- You are a pragmatic engineer who actively avoids over-engineering of solutions and understands how to maintain a high-quality code in a delivery-focused environment.
- Are someone who wishes to work in a respectful, transparent, and collaborative work environment.
- Are a person who values collaboration with your peers to deliver exceptional experiences.

**Bonus**

- Previous work scaling enterprise software and infrastructure.
- Previous experience in the IT infrastructure industry.

_Experience comes in many forms, many skills are transferable, and passion goes a long way. If your experience is this close to what we're looking for, consider applying. We know that diversity of thought makes for the best problem-solving and creative thinking, which is why we're dedicated to adding new perspectives to the team and encourage everyone to apply._

--------------------
Nivel de Experiência: Sênior
Contratação: PJ ou CLT
-------------------

**Envie seu currículo através deste link:** https://www.maxihost.com/careers?jobId=mCIGWoNjwjYG&ft_source=Github_4000128629&ft_medium=Free%20Advertisement_4000121128

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
