### ISSUE TITLE
[Remoto] [São Paulo] [Curitiba] Front-end Developer Junior @ Contabilizei

### ISSUE THREAD

**Issue by jessicaalorena** [frontendbr/vagas#3917]
## Contabilizei

Com mais de 20 mil clientes, atuando em mais de 50 cidades do Brasil, a Contabilizei está mudando a maneira como o micro e pequeno empreendedor gerencia o seu negócio em nosso país. Continuamos a crescer rapidamente, criando novos produtos e proporcionando que o empreendedor seja o contador de sua própria história.
Acreditamos que a diversidade promove o crescimento sustentável. Na Contabilizei queremos que você seja a melhor versão de si, e as oportunidades são para todos. Valorizamos as diferenças, e estamos abertos a receber pessoas com quaisquer deficiências, gênero, etnia, orientação sexual e diferentes mindsets. Juntos, construímos a Contabilizei do nosso jeito.

## Descrição da vaga

**RESPONSABILIDADES E ATRIBUIÇÕES
Um dia típico inclui:**

- Entender as exigências e especificações dos arquitetos do sistema, contribuindo no desenvolvimento de sistemas que entreguem valor;
- Entregar código testável com qualidade, sinalizando problemas e impedimentos que impactam no prazo acordado;
- Manter sistemas e funcionalidades do lado do cliente (front-end) para fornecer aos usuários finais acesso às funções do sistema;
- Colaborar com a construção de componentes de aplicativos front-end para incluir scripts a serem executados em navegadores web de diversos dispositivos do lado do cliente.

## Local

100% Remoto ou Presencial (após a pandemia) em Curitiba ou São Paulo.

## Requisitos

**Obrigatórios:**
- Graduação concluída ou cursando em Análise de Sistemas, Engenharia da Computação ou áreas afins;
- Conhecimento em desenvolvimento de aplicação SPA;
- Conhecimento em Javascript e framework Vue.js ou React;
- Conhecimento em WordPress;
- Conhecimento em PHP;
- Conhecimento em consumo de API's RESTful; 
- Noções de UX/UI; 
- Conhecimentos em controle de versão; 
- Conhecimento sobre métodos ágeis de desenvolvimento.

**Desejáveis:**
- Desejável conhecimento em Nuxt.js;
- Desejável conhecimento em SEO;
- Desejável conhecimento em Web Analytics.

## Contratação

CLT

## Como se candidatar

Para se candidatar, basta acessar o link: https://contabilizei.gupy.io/jobs/558387 e realizar o cadastro :)

## Tempo médio de feedbacks

Costumamos enviar feedbacks à cada 7 dias através do e-mail cadastrado, sempre após a triagem de currículos.

#### Regime
- CLT

#### Nível
- Júnior

**Comment by brunopeople** [comment]
Boa Noite!! tem algum outro e-mail ou link para aplicação da vaga. Eu não gosto do Gulp, por que sempre sou dispensado das vagas por lá!

**Comment by jessicaalorena** [comment]
> Boa Noite!! tem algum outro e-mail ou link para aplicação da vaga. Eu não gosto do Gulp, por que sempre sou dispensado das vagas por lá!

Olá @brunopeople  tudo bem?
Obrigada pelo contato! :) 

Todos os nossos processos seletivos ocorrem através da plataforma Gupy por padrão da CIA, para que haja maior centralização das informações e para que nenhum candidato fique sem receber os contatos/retornos.

**Comment by jessicalorenacontabilizei** [comment]
> mais

Olá @luizlima-code esta vaga encontra-se encerrada! Aqui está nossa página de banco de talentos, assim que surgir uma nova oportunidade, eu atribuo ela para você! :) https://contabilizei.gupy.io/jobs/469531

**Comment by jessicalorenacontabilizei** [comment]
**### Vaga encerrada**
