### ISSUE TITLE
[Remoto] Front-end Developer na Home Hero

### ISSUE THREAD

**Issue by mmbfreitas** [frontendbr/vagas#3919]
## Nossa empresa

Home Hero é uma startup criada para solucionar o problema de obras e reformas no Brasil, focada em uma plataforma SaaS e marketplace de produtos e serviços para conectar toda a cadeia (arquitetos, empreiteiros, fornecedores, etc) e gerenciar o projeto em um único local, fornecendo aos nossos clientes tudo o que eles precisam, de serviços a produtos, para criar a casa dos seus sonhos.

## Descrição da vaga

Buscamos pessoas que serão a base do time de produto e tecnologia da Home Hero, focadas em construir o maior marketplace de produtos e serviços para reforma e decoração da América Latina.

## Local

Remoto

## Requisitos

**Obrigatórios:**

- Mínimo de 3 anos de experiência em engenharia de software no desenvolvimento e manutenção de aplicativos web;
- Fortes conhecimentos em javascript;
- Sólidos conhecimentos de lógica de programação, orientação a objetos e design patterns;
- Experiência na utilização de frameworks JavaScript MVC (AngularJS, ReactJS, VueJS);
- Experiência com testes unitários em JS (Mocha, Protractor, Jasmine...);
- Experiência com Rest API, preferencialmente Node.JS;
- Conhecimento em banco de dados SQL e NoSQL;
- Noções em Docker e AWS.

**Desejáveis:**
- Experiência em mobile

## Benefícios
- Gympass

**Diferenciais:**

- Oportunidade de participar da criação de uma startup do zero;
- Ambiente meritocrático, com oportunidades e suporte para desenvolver sua carreira profissional de maneira meteórica com possibilidade de participação societária;
- Liberdade para propor novas idéias e assumir grandes responsabilidades;
- Ecossistema horizontal.

## Contratação

PJ R$ 10.000,00

## Como se candidatar

Por favor envie um email para vagas@homehero.com.br com seu CV anexado - enviar no assunto: Vaga software engineer 

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
