### ISSUE TITLE
[São Paulo] Front-end Developer na Praxio Tecnologia

### ISSUE THREAD

**Issue by lucardosob** [frontendbr/vagas#3920]
> Vaga Remota durante a pandemia

## Nossa empresa

A Praxio está em constante crescimento no mercado, e para continuarmos nesse ritmo buscamos profissionais que se enquadrem na nossa cultura.

Nosso time trabalha com metodologias ágeis, zela pelas boas práticas de código e são agarrados aos detalhes, não tem medo de novos desafios, são comunicativos e proativos, amam programar e conhecer novas tecnologias.

Você acredita que é um desenvolvedor(a) front-end compatível conosco? Então #vemprotime.

Você é uma pessoa proativa, com sede de aprender e quer fazer parte de um time muito divertido e que ama o que faz? Nós temos uma vaga com o seu perfil!

## Descrição da vaga

O candidato irá trabalhar com sistemas Web e Desktop, visando as boas práticas de código.

## Local

Remoto ou Escritório, Jabaquara (10 min do metrô) - São Paulo - SP

## Requisitos

**Obrigatórios:**

- Saber algum framework de Java Script, seja ele Angular ou React 

**Desejáveis**
- HTML 5;
- CSS 3 (desenvolvimento responsivo adequado em browsers);
- Frameworks (Bootstrap);
- JS;
- Angular 2+;
- TypeScript;
- Comunicação via API Rest;
- Angular Material.

**Diferenciais:**
- Conhecimentos de UI/UX;
- Scrum (Metodologias Ágeis);
- Automação de Teste;
- PWA;
- Conhecimentos em tagueamento GA;
-  NativeScript.

## Benefícios

-Vale Refeição
-Vale Transporte
-Plano de Saúde
-Plano Odontológico
-Seguro de Vida
-Auxílio Creche

**Diferenciais:**
-GymPass;
-Horário Flexível;
-DressCode: Do jeito que você é; 
-Folga no dia do aniversário;
-Presente de casamento/nascimento dos filhos;
-Festa em comemoração aos aniversariantes do mês;
-Descontos em faculdades, cursos de inglês e espanhol;
-Premiação por tempo de casa;
-Café da manhã (às quartas-feiras);
-As datas comemorativas sempre são lembradas com uma surpresa (dia das mães, dias dos pais, Páscoa, etc...);
-Aula de Patins e Futebol.

## Contratação

CLT

## Como se candidatar

Por favor se cadastre através do link: https://jobs.kenoby.com/praxio/job/front-end-pleno/5f5fab8e6024c83a7723fef4

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: luana.batista@praxio.com.br

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
