### ISSUE TITLE
[SÃO PAULO] Front-end Developer @ Ambev

### ISSUE THREAD

**Issue by FabianaSN** [frontendbr/vagas#3922]
**Descrição:**  A Ambev é uma empresa que sonha grande: são milhares de pessoas apaixonadas pelo que fazem com objetivo de impulsionar o setor de bebidas com novos sabores e sempre com muita qualidade. Estamos procurando profissionais para auxiliar na criação e manutenção de funcionalidades para o E-Commerce de cerveja da Ambev.

**Local:**  atualmente em Home Office, no **Itaim (SP)** com **home office flexível** pós pandemia.
**Contratação:** CLT + BENEFÍCIOS
**Nível:** Senior
**Requisitos:**  HTML, CSS, Javascript, jQuery, React, APIs REST e conhecimento de **plataforma VTEX.**

Mais informações, benefícios e interesse em participar basta fazer cadastro no seguinte site para darmos continuidade ao processo:

**https://byintera.in/ambevf3**

Dúvidas: https://www.linkedin.com/in/larissagandarela/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
