### ISSUE TITLE
[REMOTO] FULLSTACK Developer na Pravaler

### ISSUE THREAD

**Issue by nataliaintera** [frontendbr/vagas#3923]
[OPORTUNIDADE] [REMOTO] DESENVOLVEDOR FULLSTACK http://byintera.in/2c1 #vagasbyintera

Impulsionar sonhos através do acesso à educação, transformar histórias e o mundo. No time Pravaler você pode levar essa realidade adiante.

Pravaler é uma fintech de financiamento estudantil que há 20 anos torna sonhos, realidade. Em amplo e sólido crescimento, o objetivo aqui é atingir ainda mais pessoas e garantir mais acesso ao ensino superior. Hoje o desafio enfrentado é trazer, cada vez mais, o negócio para perto das tecnologias mais avançadas. E para isso, precisamos dos melhores talentos em arquitetura, Ruby, PHP, Elixir e Cloud para realizar sonhos junto com a gente.

Sonhos grandes, como os seus.
#vagasbyintera #vaga #oportunidade #pravaler #fullstack #softwareengineer #ruby #php #elixir #cloud

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
