### ISSUE TITLE
[Itajaí/SC | Remoto] Front-end VueJS Developer na We Dev Software

### ISSUE THREAD

**Issue by adeildo-jr** [frontendbr/vagas#3928]
## Descrição da vaga

Essa vaga é voltada para construção de API's e integração à API's de parceiros.

## Local

Itajaí/SC ou Remoto

## Benefícios

- Participação nos resultados
- Flexibilidade de horário
- Ajuda de custo para aulas de inglês
- Ajuda de custo para mudança de cidade, caso deseje se mudar para a cidade do escritório
- Gosta de pizza ou lanche? Vamos mandar um vale-lanche para você mensalmente

**Diferenciais:**
- Participação nos resultados
- Flexibilidade de horário
- Ajuda de custo para aulas de inglês
- Ajuda de custo para mudança de cidade, caso deseje se mudar para a cidade do escritório
- Gosta de pizza ou lanche? Vamos mandar um vale-lanche para você mensalmente

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com desenvolvimento JavaScript
- 2 anos de experiência com desenvolvimento Vue.js
- HTML5, JS, CSS
- Conhecer os design systems mais famosos: Bootstrap, Material Design

**Desejáveis:**
- Conhecimentos em Vuex
- Conhecimentos em API's
- Inglês
- TDD
- Conhecimento em metodologias ágeis
- Se você é uma pessoa pro-ativa e comunicativa, é um extra também ;)

**Diferenciais:**
- Temos diversos OSS no qual é voltado a manter pacotes de integração a parceiros e no desenvolvimento do ecossistema de criptografia e blockchain.

## Contratação

PJ a combinar.

## Nossa empresa

Somos uma Software House que desenvolve tecnologias inovadoras. Criamos soluções de pagamentos, especialistas em blockchain e open banking.
Quer mudar a forma de como usamos o dinheiro? Então venha fazer parte da nossa equipe!

**Aqui usamos:**
- Vue.js
- PHP
- Python
- Ruby
- Flutter
- React Native
- Docker

## Como se candidatar

Por favor, acesse o link e preencha o formulário para se candidatar na vaga: https://docs.google.com/forms/d/e/1FAIpQLSeUfSPV1t9yaD_rBIk9WZm--DtZgEfesp8pUJqeX3VAQv1zdQ/viewform?usp=sf_link

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@wedev.software

#### Alocação
- Flexível
- Presencial
- Remoto

#### Nível
- Pleno

#### Regime
- PJ a combinar

**Comment by Georgegantus** [comment]
Opa, acredito que há um erro no anúncio vaga, o formulário anexado diz respeito a uma vaga para back-end enquanto o anúncio se refere a uma vaga de front-end

**Comment by adeildo-jr** [comment]
> Opa, acredito que há um erro no anúncio vaga, o formulário anexado diz respeito a uma vaga para back-end enquanto o anúncio se refere a uma vaga de front-end

@Georgegantus obrigado por avisar, havia colado o link errado.

Corrigi aqui.
