### ISSUE TITLE
[Florianópolis/SC] Front-end Developer (Vue) na Blueticket

### ISSUE THREAD

**Issue by diogokleinubing** [frontendbr/vagas#3929]
> Vaga Remota durante a pandemia

## Nossa empresa

Temos como propósito Aproximar as pessoas de experiências ao vivo, desenvolvendo ferramentas para os organizadores dos eventos gerenciarem seus eventos, além de tecnologias que permitam que os clientes comprem seus ingressos, seja através do site, aplicativos mobile ou das tecnologias para pontos de venda que também desenvolvemos.

Nossos produtos são utilizados diariamente por mais de 1 milhão de visitantes no nosso site, além de centenas de organizadores que emitem mais de 3 milhões de ingressos por ano na nossa plataforma

Para apoiar os resultados dos eventos, desenvolvemos ferramentas avançadas e específicas para o mercado de ventos, como Analytics, CRM entre outras ferramentas de inteligência.

## Descrição da vaga

Estamos em busca de talentos para nosso time de Produto e Tecnologia para atuar como Front End Developer, atuando no desenvolvimento de novos recursos para nossa plataforma de gestão de ingressos.
Veja abaixo mais detalhes do que esperamos e oferecemos!

## Local

Escritório em Florianópolis/SC, possibilidade para remoto

## Requisitos

**Obrigatórios:**
- Pelo menos 2 anos de experiência em desenvolvimento Front-end;
- Conhecimento em VueJS, Nuxt, Vuex;
- Experiência com SPA (Single Page Application);
- Experiência em CSS3 e HTML5;
- Experiência em consumir APIs Rest;
- Experiência com versionamento Git;
- Perfil focado em geração de valor para o cliente, valorização pela comunicação e feedback, empreendedorismo e autodesenvolvimento.

**Diferenciais:**
- Conhecimento em Vuetify
- Experiência com desenvolvimento mobile em React Native
- Conhecimento em infraestrutura AWS

## O que oferecemos

- Uma cultura que valoriza o compromisso com a excelência e a persistência para que o ótimo seja ainda melhor;
- Um ambiente de trabalho leve e estimulante, com equipes engajadas pela busca da qualidade e satisfação dos nossos clientes;
- Remuneração compatível com mercado e com suas atribuições (Regime de trabalho a definir);
- Vale Alimentação/Refeição (você escolhe), Vale Transporte e Plano de saúde (após 3 meses);
- Horário de trabalho flexível e com possibilidade de home office.

## Contratação

A combinar.

## Como se candidatar

Envie CV em https://blueticket.breezy.hr/p/dfa87f3f7fba-front-end-developer-vue

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 semana após cada processo.
E-mail para contato em caso de não haver resposta: vagas@blueticket.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior

**Comment by hamiltongabriel** [comment]
Página para aplicação não está enviando quando mando enviar o curriculum.

**Comment by diogokleinubing** [comment]
> Página para aplicação não está enviando quando mando enviar o curriculum.

Conforme conversamos por email, parece ter sido pontual, CV recebido!

**Comment by Eduruiz** [comment]
O erro que o @hamiltongabriel comentou continua acontecendo @diogokleinubing.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
