### ISSUE TITLE
[Rio de Janeiro] Front-End Developer na Stone Pagamentos

### ISSUE THREAD

**Issue by Lucasktrindade** [frontendbr/vagas#393]
## Descrição da vaga

Se você tem uma boa base de HTML,CSS e Javascript, com uma boa experiência com Single Page Applications, e não gosta de ficar parado, sempre buscando novas tecnologias e querendo melhorar cada vez mais sua stack, sendo assim o produto em que trabalha, e cada vez mais a experiência pro cliente final. É você que estamos buscando para nos ajudar a transformar cada vez mais a experiência do nosso cliente e a realidade dos meios de pagamento. Abaixo alguns conhecimentos que esperamos de você:

## Local

Escritório Rio de Janeiro - Av. General Justo, 375 - Centro, Rio de Janeiro.

## Benefícios

   - Vale refeição/alimentação;
   - Vale transporte;
   - Plano de saúde;
   - Horário flexível;
   - Ambiente de de trabalho descontraído;
   - Snackbar dentro do escritório;
   - Entretenimento: Vídeo games, sinuca, mesa de poker, etc;

## Requisitos

**Obrigatórios:**
- CSS3
- HTML5
- Javascript
- ES6
- Experiência com SPA's(AngularJS, Vue.js ou React)
- API RESTful
- Git

**Desejáveis:**
- Experiência com testes
- Design Patterns em JS
- Ter trabalhado com metodologias ágeis (Scrum)
- Conhecimentos sobre Progressive Web Apps

## Contratação

A combinar

## Nossa empresa

A Stone é uma entidade que está licenciada para processar pagamentos eletrônicos em todo território nacional, no mundo físico e virtual.

Nosso propósito é melhorar a vida do empreendedor através de tecnologias no mercado de pagamentos.

Em um mercado que por muito tempo foi desrespeitoso com o cliente, nós nascemos para fazer a diferença na vida do lojista brasileiro através da tecnologia e do bom atendimento. 

Mais informações: [https://enter.stone.com.br/](https://enter.stone.com.br/)

## Como se candidatar

Por favor envie um email para ltrindade@stone.com.br com seu CV anexado - enviar no assunto: Vaga Front-End Developer

**Comment by ecouto** [comment]
Rio ou SP?

**Comment by Lucasktrindade** [comment]
Rio

**Comment by Lucasktrindade** [comment]
Podem colocar a label de Estágio, Júnior, Pleno e Sênior, por favor?

**Comment by ecouto** [comment]
Não entendi a parte escritório , Vila Olimpia - São Paulo

**Comment by AlexsandroSA** [comment]
Essa biblioteca de vocês, que massa!

**Comment by felipecesr** [comment]
Tem possibilidade de ser remoto?

**Comment by Lucasktrindade** [comment]
Sem possibilidades no momento.

**Comment by JonasEmanuel** [comment]
Enviado

**Comment by hillarysousa** [comment]
Enviei! ˆ-ˆ
