### ISSUE TITLE
[Florianópolis/SC] Front-end Developer na Aurum Softaware

### ISSUE THREAD

**Issue by Larihii** [frontendbr/vagas#3930]
Dentro do time de Tecnologia a sua missão será desenvolver novas funcionalidades, dar manutenção e aprimorar a performance do melhor software jurídico do país. Além disso, criar e monitorar métricas que garantam o bom funcionamento e performance do software e atuar junto ao time de Produto no planejamento e validação de novas funcionalidades.

**Dá uma olhada nas principais responsabilidades da vaga:**

- Colaborar na criação de arquiteturas escaláveis;- 
- Colaborar na migração de uma aplicação AngularJS para React;
- Desenvolver código clean, escalável, de fácil manutenção e seguindo as boas práticas de desenvolvimento de software;
- Desenvolver telas prezando pela usabilidade, experiência do usuário e portável para qualquer dispositivo;
- Projetar e desenvolver componentes com escopo bem definidos, visando reutilização e performance;
- Criar testes unitários para os componentes criados;
- Atuar juntamente com o time de produto no levantamento e especificação de novas features;

**Para participar desta seleção, você precisa:**

- Superior completo ou cursando nas áreas de Sistemas de Informação, Ciências da Computação, Engenharias ou afins;
- Experiência prévia com Javascript (ES6 ou superior) e React;
- Experiência prévia em versionamento de código com Git e GitHub;
- Experiência prévia com os padrões JSON e REST para consumo de APIs;
- Conhecimento das novas features do React (Hooks, Context, Suspense);
- Conhecimentos em  gerenciamento de estado no React (Redux, MobX, Context API, ...);
- Familiaridade com ferramentas de bundle como webpack e gulp;
- Conhecimento do ecossistema de testes de frontend;
- Ser proativo e fast learning;
- Bom relacionamento interpessoal.

**É um diferencial se você possuir:**

- Conhecimento em AngularJS;
- Familiaridade com a biblioteca @react-testing-library para testes de componentes React;
- Familiaridade com tecnologias de cloud;

**Ah! Vale ressaltar quais são os requisitos para ser um #ÁUREO:**

- Ser um eterno aprendiz.
- Trabalhar em equipe (mesmo!).
- Saber ouvir com atenção e responder com respeito.
- Ser persistente e jogar pra ganhar.
- Protagonizar suas próprias entregas.

**E agora dá uma olhadinha quais são os benefícios de ser um #ÁUREO:** 

- Trabalhar em um Great Place to Work©: somos uma das melhores empresas para se trabalhar em Santa Catarina e no Brasil.
- Resenha + Happy Hour: a cada 15 dias nos reunimos para que todos fiquem por dentro do que está acontecendo na Aurum e depois sempre rola aquele happy hour!
- Transparência em OKR: nossa reunião de diretoria é aberta para a empresa inteira, assim todos ficam por dentro do status do negócio.
- Aurum Talks: incentivamos o Time a dividir seus aprendizados com a empresa inteira!
- Dia da Cultura: todo quarter temos um dia inteirinho para falar mais sobre a nossa cultura e garantir que ela esteja presente no nosso dia a dia.
- Guildas para desenvolvimento: de acordo com os interesses e desafios que temos, criamos guildas para estudar e compartilhar juntos.
- Integrando #áureos: temos uma verba mensal para ações de integração para o Time. Quem decide o que fazer somos nós mesmos.
- Zen Time: queremos nossos Áureos felizes e saudáveis. Que tal uma massagem para relaxar?
- Frutas: temos frutinhas no escritório pra um dia a dia mais saudável!
- Café, chocolate quente e chás: para aquecer os corações de alguns ou dar aquela turbinada no trabalho!
- Aniversariantes do mês: comemoramos os aniversários juntos com bolo e salgadinhos.
- Mesa de Ping Pong, videogame e jogos de tabuleiro: estão sempre ali pra quem estiver precisando fazer uma pausa. 
- Sem dress code: seja você mesmo e se vista como gosta.

**E os benefícios tradicionais:**

- VR e/ou VA
- Plano de Saúde
- Plano Odontológico
- Vale-Transporte
- Seguro de Vida
- Descontos em algumas lojas e restaurantes da região

E aí, curtiu!? Então vem com a gente :)
Para participar do processo seletivo basta se candidatar [Aqui](https://jobs.kenoby.com/aurum/job/frontend-developer-pleno/5fa313bfa3929846a04a6264)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
