### ISSUE TITLE
[Rio de Janeiro] Vaga Frontend Pleno - Totvs Rio (Hospitality)

### ISSUE THREAD

**Issue by fabiomirandaa** [frontendbr/vagas#3931]
> Vaga Remota durante a pandemia

Nossa meta é revolucionar o setor de Hospitalidade!  
Estamos com alguns projetos que estão crescendo bastante e com grandes desafios.  
Nossas aplicações estão sendo desenvolvidas com foco internacional, dessa forma lidamos com todos os desafios de criar um sistema que atenda usuários dentro e fora do Brasil.  Nossa stack é toda em Angular 9+.

## Local

Rio de Janeiro, Centro  
(Durante o período da pandemia, estamos 100% home office)

## Benefícios

-   Plano de saúde
-   Plano Dental
-   Seguro de vida
-   VR de R$ X/dia
-   Auxílio creche

## Diferenciais

-   Plano de Saúde e Odontológico
-   Vale transporte
-   Vale refeição
-   Previdência privada
-   Seguro de Vida
-   PLR
-   Gympass

### Obrigatórios:

-   Sólida experiência com JavaScript
-   Sólidas experiência no desenvolvimento de aplicações *SPA*
-   Conhecer os paradigmas de modernos de desenvolvimento de Frontend
-   Conhecimento em algum framework moderno de Frontend
-   Estar disposto à trabalhar com Angular 9+
-   Boas noções de GIT

### Desejáveis:

-   Experiência em Angular 8+
-   Desenvolvimento de testes unitárias
-   Conhecer RxJs
-   Conhecer NgRx

### Diferenciais:

-   Projeto com preocupações internacionais
-   Ambiente de trabalho descontraído
-   Contratação
-   CLT - pretensão salarial

## Nossa empresa

A TOTVS possui uma visão tecnológica e uma história de impacto para se orgulhar.  
Nossa cultura de inovação é focada no desenvolvimento de soluções diferenciadas para empresas de todos os portes e segmentos, incluindo softwares de gestão (ERP), plataformas de inteligência artificial, novos negócios e consultoria.  
Assim, Impactamos os negócios de mais de 30.000 clientes em escala global há quase quatro décadas.  
Em cada etapa desta constante evolução, nossos TOTVERS, compartilhando uma paixão por colaboração, aprendizado constante e impacto significativo, contribuem para esse legado de sucesso.  
Estamos convidando talentos com mentes inovadoras e voltadas à tecnologia, para continuar escrevendo essa história junto com a TOTVS em um ambiente de ritmo acelerado. Aqui você vai encontrar grandes desafios todos os dias, onde a mudança e o aprendizado são parte da nossa rotina.

## Como se candidatar

Enviar email para  [souza.nagila@totvs.com.br](mailto:souza.nagila@totvs.com.br)  com o assunto "Vaga Frontend Pleno" com seu CV e linkedin.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
