### ISSUE TITLE
[REMOTO] Front-end Developer em NTH WORK

### ISSUE THREAD

**Issue by fduchewski** [frontendbr/vagas#3932]
## Descrição da vaga

Full time - REMOTO.

Desenvolvedor front-end com experiência em CSS/SASS/LESS, boas noções de UI e UX e interfaces responsivas. 
Experiência com Mobile e publicações Android e IOS.

O mais importante, porém, é que você não tenha medo de aprender e se aventurar em novas linguagens e frameworks. Na Nth trabalhamos com diversos projetos, em stacks diferentes, e constantemente adotando novas tecnologias.

## Nossa empresa

Nth.work - Great design, cutting edge technology and product excellence. The solutions of tomorrow, today. Our team of specialists can help you reshape your business and create innovative products.
We’re an international group of creative technologists and business folks. From ideation, to development and launch of unique products, we nail it!
https://nth.work ("Nth o quê?" Em caso de dúvida: https://www.nth.work/what-nth/ )

## Local

[REMOTO]

## Requisitos

- CSS/SASS/LESS
- Boas noções de UI/UX
- Experiência com criação de interfaces responsivas
- Compromisso com a criação de aplicações performáticas
- React
- React Native
- Angular
- Testes
- Experiência com integrações com API
- Mobile IOS/Android

## Contratação

 PJ a combinar

## Como se candidatar

Por favor envie um email para info@nth.work com:
seu CV anexado
link para o LinkedIn,
link para GitHub ou outros projetos anteriores
enviar no assunto: Vaga FrontendBr 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: flavia@nth.work

## Labels

Remoto
Freelancer
Google Cloud
Django
React 
React Native

#### Regime
- Freela
- PJ

#### Nível

- Pleno-Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
