### ISSUE TITLE
[REMOTO ou FLORIANÓPOLIS/SC] Senior Front-end Developer na Studos

### ISSUE THREAD

**Issue by keitoliveira** [frontendbr/vagas#3933]
## Nossa empresa

Nós somos uma plataforma educacional focada em facilitar a vida dos professores e coordenadores, criando ferramentas de apoio para otimizar os processos pedagógicos e, também, na melhora do desempenho dos alunos.

Entendemos que todos devem ter acesso a novas formas de estudar, sendo assim, desenvolvemos uma plataforma que potencializa o ensino na sala da aula e também fora dela. 

Atuamos nos segmentos de Pré-Vestibular e ENEM, Concursos Públicos, Concursos Militares, OAB e Ensino Superior. 

Hoje, já contamos com mais de 1 milhão usuários em todo Brasil.

## Descrição da vaga

- Participar de planejamentos junto aos demais times, do desenvolvimento do nosso design system, refactoring de nossas plataformas e das integrações com sistemas parceiros
- Participar da documentação técnica e de processos dentro do time
- Ser referência em desenvolvimento dentro do time, ajudando a elevar o nível de qualidade das entregas
- Ter comunicação clara e descomplicada, disseminar conhecimento através de pair-programming, code review ou treinamento, ajudando os desenvolvedores a avançar em suas carreiras

## Local

Caso você seja de SC, há opção de ir para o escritório se desejar. Nosso escritório está localizado no bairro João Paulo, próximo a Florianópolis. Remoto para outras localidades.

## Requisitos

**Obrigatórios:**
- 6+ anos de experiência com desenvolvimento Front-End
- Conhecimento avançado em HTML, CSS e JavaScript
- Conhecimento sólido em React e suas APIs e Redux
- Conhecimento sólido em testes unitários e de integração com Jest e/ou Cypress
- Conhecimento sólido com module bundler Webpack e/ou Rollup
- Conhecimento sólido em práticas de acessibilidade
- Conhecimento sólido em práticas de performance
- Boa comunicação

**Desejáveis:**
- CSS-in-JS
- Lerna
- Participação anterior em desenvolvimento de design system
- Conhecimento em criação e manutenção de CI/CD para projetos Front-End e publicação de pacotes através do NPM ou GitHub

**Diferenciais:**
- Conhecimentos em Graphql

## Benefícios

- Vale Refeição ou Vale Alimentação
- Plano de saúde
- [Zenklub](https://zenklub.com.br/) com direito a 2 consultas grátis e 2 sessões com custo reduzido
- Vale Transporte (Alocado)
- Ajuda de custo para Home Office (Remoto)
- Se precisarmos que vá em nossa sede, arcamos com todos os custos (Remoto)
- Folga de aniversário

## Contratação

CLT

## Como se candidatar

Enviar um e-mail para keit@studos.com.br com o link do Github, caso tenha projetos open source que deseje apresentar, e LinkedIn com assunto "Vaga Senior Front-End Developer"

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 4 dias úteis após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
