### ISSUE TITLE
[São Paulo ou Porto Alegre] Front-end Senior Developer na Dell Technologies

### ISSUE THREAD

**Issue by carolina-brand-dell** [frontendbr/vagas#3934]
> Vaga Remota durante a pandemia

## Nossa empresa

Dell Technologies é uma família única de empresas que ajuda organizações e indivíduos a construir seu futuro digital e transformar a forma como trabalham, vivem e se divertem - fornecendo aos clientes o portfólio de tecnologia e serviços mais amplo e inovador do setor. Valorizamos nossos clientes, conquistando juntos, inovação, resultados e integridade. Faça sua carreira crescer com um salário altamente competitivo, programas de bônus, benefícios de classe mundial e oportunidades incomparáveis ​​de aprendizado e desenvolvimento - tudo em uma empresa que se orgulha de ser diversificada e inclusiva.

Na Dell Technologies, temos o compromisso de impulsionar o progresso humano. Por meio de nosso alcance, tecnologia e pessoas, nos esforçamos para criar um impacto positivo e duradouro na humanidade e no planeta. Cultivar a inclusão é uma das principais áreas de nossas metas de impacto social para 2030.

• Em 2030, 50% de nossa força de trabalho global e 40% de nossos líderes globais de pessoas serão mulheres.

• Até 2030, 95% dos nossos funcionários participarão do aprendizado anual básico em tópicos-chave, como preconceito inconsciente, assédio, microagressão e privilégio.

## Descrição da vaga

Junte-se a nós como Pessoa Engenheira de Software em nosso Sistema de Linguagem de Design no Brasil para fazer o melhor trabalho da sua carreira e causar um profundo impacto social. Trabalhando com tecnologia de ponta, você projetará e desenvolverá software para plataformas, periféricos, aplicativos e diagnósticos - todos com as mais avançadas tecnologias, ferramentas, metodologias de engenharia de software e a colaboração de parceiros internos e externos.

Você irá depurar com maestria os problemas mais complicados que a equipe encontrar. Você conduzirá as conversas internamente sobre a direção de áreas significativas da tecnologia, conduzirá o consenso de toda a equipe para a adoção dessa direção e usará essa direção para inspirar os engenheiros. Nesta função, você atuará como modelo e mentor para cada membro técnico da equipe.

Você irá:

Crie especificações de design para aplicativos de alta disponibilidade e escaláveis ​​que serão usados ​​por clientes internos e externos
Depura com maestria os problemas mais complicados que a equipe encontra
Converte os requisitos do produto em soluções técnicas
Conduz as conversas internamente sobre a direção de áreas significativas da tecnologia, conduz o consenso de toda a equipe para a adoção dessa direção e usa essa direção para inspirar engenheiros
Atua como modelo e mentor para cada membro técnico da equipe

## Local

Porto Alegre de modo flexível ou São Paulo 100% remoto.

## Requisitos

**Obrigatórios:**

Experiência moderada na indústria de TI, BA / BS em Ciência da Computação ou campo relacionado (ou experiência equivalente)
Tem uma boa compreensão do funcionamento interno dos navegadores, motores JavaScript e tecnologias de software que interagem com eles.
Experiência com UX / UI (User Experience / User Interface) ou trabalhar junto com equipes de UX (User Experience)
Experiência em arquitetura web e tecnologias-chave com tecnologias JavaScript básicas
Capaz de projetar a arquitetura central que outros engenheiros projetarão em torno

**Diferenciais:**
Experiência com Design System.

## Benefícios

É compartilhado na primeira conversa.

## Contratação

CLT + benefícios. 

## Como se candidatar

Por favor, se candidatar no link: https://dell.wd1.myworkdayjobs.com/External/job/Eldorado-Do-Sul-Brazil/Senior-Front-End-Software-Engineer---Design-System_R074229 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: carolina_brand@dell.com

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
