### ISSUE TITLE
[São Paulo/Belo Horizonte] Front-end Developer Sênior na Sympla 

### ISSUE THREAD

**Issue by uemuraharumi** [frontendbr/vagas#3938]
**[São Paulo/Belo Horizonte] Front-end Developer na Sympla 
> Vaga Remota durante a pandemia**

Simplicidade é nosso nome e sobrenome. Somos a maior plataforma de venda de ingressos e gestão de eventos do Brasil e temos orgulho de ter tecnologia e design no nosso DNA.

Acreditamos em experiências acessíveis, agradáveis e inspiradoras, que simplifiquem a vida das pessoas. Para acompanhar o crescimento da Sympla estamos escalando nosso time e para isso buscamos pessoas incríveis!

Nosso time atua sempre com foco nos melhores resultados, construímos juntos, somos analíticos e pensamos em todo o contexto para entregar com qualidade a melhor experiência para nossos clientes, entendendo seus dilemas.

**Por que a Pessoa Desenvolvedora Frontend é importante para nós?** Como membro da equipe de Produto e Desenvolvimento, você será responsável pela elaboração de novas ferramentas, manutenção das ferramentas existentes e pela tomada de decisões relacionadas à arquitetura das aplicações que compõem o ecossistema da Sympla.

**Seus desafios serão:**

Contribuir com tomada de decisões de todos os processos de desenvolvimento, passando desde a escolha das tecnologias utilizadas até os processos de build/deploy;
Auxiliar a manter um "espírito" ágil;
Se orgulhar de colocar em produção um código que é usado por milhões de pessoas Brasil afora. :)
Assegurar a melhor qualidade de experiência para nossos usuários.
**Desejáveis:**
- conhecimentos em ruby on rails
- conhecimentos em C#

**Diferenciais:**
- projetos opensource

**Oferecemos:**

Ambiente criativo, inovador e estimulante;
No dress code (Venha como se sentir melhor, fechou?);
GymPass é um benefício corporativo de atividade física, nele você tem acesso a diversas modalidades de atividades em várias
academias;
Plano de Saúde Sulamérica com cobertura Nacional na modalidade apartamento;
Plano Odontológico;
O momento da cegonha chegou? Nossas licenças são estendidas! Maternidade 6 meses e paternidade 20 dias;
Auxílio creche para crianças de até 4 anos e 12 meses para mamães e papais;
Acesso gratuito ao MyAcademy, plataforma de e-learning com acesso a + 40.000 cursos dos mais variados temas e parceiros;
Café expresso, bebidas variadas, frutas e snacks a qualquer hora do dia;
Happy Hour que acontece uma vez ao mês em comemoração aos aniversariantes;
Trabalhar lado a lado de pessoas que são apaixonadas pelo que fazem, tendo a oportunidade de aprender diariamente e ampliar seus conhecimentos;
40h semanais, de segunda a sexta com horário flexível;
Folga de um dia no mês do aniversário, que é a nossa maneira de presentear o funcionário;
Regime de contratação CLT, Vale Transporte e Vale Refeição.

**O que buscamos?**

Experiência com desenvolvimento Front-End;
Ser proativo trazendo sempre novas ideias para resolvermos nossos desafios;
Excelente conhecimento em tecnologias de desenvolvimento front-end, em geral;
Seguir às tendências do mercado e que seja capaz de se adaptar rapidamente a novas tecnologias;
Ter um amplo conhecimento das ferramentas do ecossistema de front-end, em geral: Gulp, Grunt, npm, etc;
Conciliar demandas e prazos comerciais com qualidade de engenharia;
Conhecimentos avançados em Javascript! Conhecimento em HTML5 e CSS3;
Ter senso de organização, atenção a detalhes e foco;
Must rock!
 

**Alguns diferenciais para a função:**

Perfil analítico e propositivo. Ter iniciativa para propor novas soluções e contribuir na tomada de decisões de produto e de tecnologia
Rotinas de feedback fazem parte da nossa cultura, então é esperado que esta pessoa esteja preparada para receber e fornecer feedbacks.

 
**Contratação**
CLT

**Como se candidatar**
https://www.sympla.com.br/trabalhe-conosco-vaga?gh_jid=4982566002 
ou através do email: raquel.uemura@sympla.com.br

Tempo médio de feedbacks: 48 horas.

Costumamos enviar feedbacks em até 2 dias após cada processo.

Nível:
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
