### ISSUE TITLE
[São Paulo] Pessoa desenvolvedora front-end plena ou sênior na Viva Decora

### ISSUE THREAD

**Issue by teles** [frontendbr/vagas#394]
## Descrição da vaga

😄  ❤️  🏠 

Temos **uma vaga** na [Viva Decora](https://www.vivadecora.com.br) para pessoas desenvolvedoras níveis **pleno** ou **sênior**.

- Criação e manutenção de módulos Angular para uma Single Page Application.
- Criação e manutenção de componentes SASS.
- Desenvolvimento de HTML orientado a boas práticas de SEO.
- Manutenção do front-end (apenas front-end) de uma aplicação Wordpress.
- Especificação e priorização de tarefas em um ambiente de startup.

## Local

Trabalho presencial. Escritório no bairro da Consolação em SP.

## Benefícios

- Horário flexível
- Salário competitivo
- Vale Refeição
- Plano de Saúde
- Plano Odontológico
- Seguro de Vida
- A equipe de desenvolvedores ainda é pequena e o nível de autonomia e participação nas decisões de código e negócio é elevado.

## Requisitos

**Obrigatórios:**
- Entregar o [projeto disponibilizado no github](https://github.com/vivadecora/projeto-vaga-front-end-nao-fazer-fork)

**Desejáveis:**
- Javascript
- CSS 
- HTML5
- SASS
- Git
- Single Page Applications
- Desenvolvimento Ágil.

**Diferenciais:**
- AngularJS 1.x
- Teste JS
- BEM
- Noções de SEO
- SMACSS

## Contratação

CLT

## Nossa empresa

O Viva Decora é uma empresa do grupo [VivaReal](https://www.lovemondays.com.br/trabalhar-na-vivareal/perfil), fundada em 2014, partiu da necessidade de completar o ciclo do consumidor de móveis online.

O Viva Decora iniciou as atividades com o apoio da estrutura de back-office do VivaReal e depois ganhou equipes independentes de marketing B2B e B2C, operações, produto e engenharia, atualmente com 20 profissionais.

Nossa plataforma de arquitetura e decoração online é voltada para ajudar os usuários a criar e comprar móveis e objetos para ambientes, baseado em recomendações e inspirações de diferentes arquitetos e designers. Temos mais de 1,5 milhão de visitas por mês em nosso site e aplicativos e mais de 3 mil profissionais cadastrados.

## Como se candidatar

Siga as instruções disponíveis no [projeto no Github](https://github.com/vivadecora/projeto-vaga-front-end-nao-fazer-fork)
 
Não esqueça de [cadastrar seu currículo](https://jobs.lever.co/vivareal/33e96820-2426-4568-852d-da36839a0c3c)

**Comment by teles** [comment]
## Gostou da vaga e conhece outra pessoa adequada?

<a align="left" href="https://www.facebook.com/sharer/sharer.php?u=https://github.com/frontendbr/vagas/issues/394"><img src="https://placeholdit.imgix.net/~text?txtsize=20&txtclr=fff&bg=3b5998&txt=Compartilhar+no+Facebook&w=250&h=60" align="left"></a>

<a href="https://www.linkedin.com/shareArticle?mini=true&url=https://github.com/frontendbr/vagas/issues/394&title=Vaga%20Desenvolvedor%20Front%20End%20Viva%20Decora"><img src="https://placeholdit.imgix.net/~text?txtsize=20&txtclr=fff&bg=0077b5&txt=Compartilhar+no+Linkedin&w=250&h=60"></a>

**Comment by WandersonAlves** [comment]
Qual a data da entrega?

**Comment by taciogt** [comment]
@WandersonAlves
Enquanto a vaga estiver aberta, todos que enviarem o currículo seguindo as instruções terão uma semana para entrega do projeto. A qualquer momento podemos fechar a participação de novas pessoas e só quem já enviou o currículo participará.

**Comment by teles** [comment]
Aqui tem uma matéria recente sobre a empresa https://startupi.com.br/2017/06/a-ideia-de-recomecar-a-carreira-em-uma-grande-empresa-nao-me-atrai-empreendedor-conta-como-e-cuidar-da-operacao-de-duas-startups até apareço em uma foto :camera_flash:

**Comment by teles** [comment]
Obrigado pelas tags @LFeh

**Comment by teles** [comment]
**Gostaria de informar que a vaga foi fechada**. ⚠️ 

Agradecimentos a todos :)

**Comment by LFeh** [comment]
@teles 🗡
