### ISSUE TITLE
[Remoto] Pessoa Engenheira de Software Front-end Sênior na Intera 

### ISSUE THREAD

**Issue by Matheus-Quevedo** [frontendbr/vagas#3945]
## Descrição da vaga

Buscamos uma pessoa desenvolvedora, nível sênior. 
São fundamentais conhecimentos em React e VueJS, técnicas de styling (regular, CSS, SASS), teste A/B, ferramentas de user behavior e Design System. 
O desafio é para ser pessoa Engenheira de Software Front-end e você desempenhará as seguintes atividades; manter a biblioteca de componentes, desenvolver interfaces responsivas, direcionar o squad em relação as melhores práticas de front-end, setup de teste A/B, analisar a performance das interfaces desenvolvidas, aprovar pull requests.

## Local

•	Remoto 

## Benefícios

•	Remuneração competitiva 
•	Home Office first 
•	Horário de trabalho flexível 

## Requisitos

**Obrigatórios:**
•	HTML
•	CSS
•	Javascript 
•	React 
•	Vue.js 
•	Angular
•	Redux
•	Hooks

**Diferenciais:**
•	GTM
•	SSR

## Contratação

PJ.

## Nossa empresa

Existimos para transformar o Brasil em um país mais inovador e desenvolvido, impulsionando o
crescimento de empresas inovadoras. Fazemos isso abastecendo as empresas inovadoras com o seu maior ativo: pessoas.

Com o nosso serviço de recrutamento online, o HUNT HACKING, atendemos hoje empresas como:
Kroton, Itaú, Ambev, Creditas, iFood, QuintoAndar, BTGPactual, Accenture, Zup Inovation, Guiabolso, LivUp, Votorantim, Alpagartas, BrasilPrev, Contabilizei, Olist, Afya, Sicoob, Quero Educação, Arco, Vtex, Cogna Educação, Clearsale, Nuvemshop, Zé Delivery, Cora, Movile Pay, Warren, Agile Content, Orbia, Kovi.
Estamos nos tornando a maior abastecedora de capital humano das empresas que transformam o país.
Estamos construindo a base para sermos a grande ponte catalizadora do mercado de trabalho para a nova economia. Vamos revolucionar o modelo de empregabilidade, que cá pra nós é o maior motor da economia. Vamos juntos?

## Como se candidatar

Aplicar em https://bit.ly/2JtBCaJ

#### Alocação
- Flexível
- Remoto

#### Experiência
- Sênior

#### Regime
- PJ

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
