### ISSUE TITLE
[Remoto] Pessoa Desenvolvedora Front-End React.js (Pleno) na Executiva Outsourcing

### ISSUE THREAD

**Issue by RaonyMarcondes** [frontendbr/vagas#3946]
## Descrição da vaga

Pioneira em outsourcing no mercado brasileiro, a Executiva Outsourcing investe em tecnologia de ponta e conta com uma equipe de TI própria. O candidato fará parte desta equipe multidisciplinar atuando no desenvolvimento e implementação de sistemas, trabalhando com metodologias e ferramentas modernas, a fim de garantir o sucesso da equipe e das implementações nos mais diversos cenários.

### Esperamos que você:

- Seja pró-ativo(a), analisando e compreendendo os impactos e reais necessidades por trás das suas entregas;
- Tenha responsabilidade pelo que você produz e entrega. (Ownership mindset);
- Acredite que pode obter melhores resultados trabalhando em equipe;
- Saiba se comunicar abertamente, participando de debates saudáveis, trazendo ideias que contribuam para o seu sucesso, e o da equipe;
- Tenha capacidade de entender Produto & Negócios. Nosso objetivo maior sempre é a entrega de valor, indo muito além de apenas criar um código bonito;
- Seja versátil: Você entende como todas as peças se conectam (front-end, back-end, database, camadas de rede, etc) e como isso impacta a performance do seu código/aplicação);
- Seja capaz avaliar e aprender sobre novas tecnologias e ferramentas.

## Local

**FULL Remoto**

## Benefícios / Diferenciais

- **Horário flexível:** 44 horas semanais, com flexibilidade perante acordo prévio entre a equipe;
- **Cultura:** Eventos internos de confraternização;

## Requisitos

**Obrigatórios:**

- Utilizar conceitos do GitHub, branching, issues, pull-requests, etc;
- Javascript / CSS / HTML;
- Conhecimento em React e seu universo;
- Conhecimento em TDD, Clean Code e Design Patterns;
- Capacidade de criar aplicaçõs escalonáveis horizontalmente, baseadas em técnicas de programação funcional e arquitetura hexagonal.

**Desejáveis:**

- Noções de PHP orientado a objetos;
- Noções de Bash script;
- Conhecimento em aplicações orientadas a componentes;
- Conhecimento em Single Page Apps integrados com API RESTful;
- Experiência com serviços AWS (EC2, S3);

**Diferenciais:**

- Projetos OpenSource

## Contratação

PJ a combinar.

## Nossa empresa

A Executiva Outsourcing foi fundada em 1998, em Curitiba/PR. Inicialmente, oferecíamos serviços de outsourcing de folha de pagamento e, com o passar do tempo, agregamos outras soluções ao nosso portfólio, ampliando nossa expertise. Nestes 20 anos, investimos em inovação e ganhamos destaque nacionalmente. Desenvolvemos projetos customizados para garantir a conformidade com a lei dos processos de gestão, trazendo segurança e agilidade para nossos clientes.

Saiba mais: https://executiva.com.br

## Como se candidatar

Por favor candidate-se pela plataforma: https://smrtr.io/4HDBP

## Tempo médio de feedbacks

Costumamos enviar feedbacks em no máximo 1 semana após cada processo.
E-mail para contato em caso de não haver resposta: thiago.santos@executiva.com.br

## Labels

- Remoto
- PJ
- Pleno

**Comment by roxdavirox** [comment]
me inscrevi lá <3

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
