### ISSUE TITLE
[São Paulo] Front-End Developer

### ISSUE THREAD

**Issue by fernandoperroni** [frontendbr/vagas#395]
## Descrição da vaga
Desenvolvimento em HTML, CSS, Javascript; 
Git e pre-processadores CSS(Sass, Stylus, PostCSS); 
Pensamento Mobile First.

## Local

Escritório, São Paulo - Avenida Faria Lima

## Benefícios

- Assistência Médica, Odontológica, Seguro de Vida
- Vale Transporte (desconto de R$ 1,00)
- Vale Refeição ou Alimentação (R$ 20/dia)
- Vale Gympass para academias com valor de até R$ 499/mês
- Ambiente informal, orientado para resultados
- Região de Fácil acesso (SP) - próximo ao metrô Faria Lima

## Requisitos

**Obrigatórios:**
Conhecimento nas linguagens: HTML, CSS, Javascript;
Git e pre processadores CSS (Sass, Stylus, PostCSS);
Pensamento Mobile First.

**Desejáveis:**
- Conhecimento de metodologias CSS;
- Familiaridade com task runners e Bundlers(Grunt, Gulp, Webpack);

**Diferenciais:**
- Experiencia com frameworks JavaScripts Modernos(Vue, React, Angular);
- TDD;
- Experiencia com metodologia Ágil;
- ES6.

## Contratação

CLT

## Nossa empresa

Aqui no Gympass, acreditamos que todos podem ter uma vida mais saudável, independente da localidade ou tipo de atividade física! Nossa missão é levar qualidade de vida para o maior número de pessoas possível. Começamos as operações em 2012 aqui no Brasil com apenas três pessoas. Hoje, contamos com 500 pessoas em nível mundial, sendo 300 no BR. Nosso time é focado em performance, nossos líderes lideram pelo exemplo e nós recrutamos e desenvolvemos talentos para serem melhores que nós! Estamos em busca de pessoas focadas em resultados e dispostas a atingir grandes objetivos com postura humilde. Junte-se a nós neste desafio global!

## Como se candidatar

Enviar e-mail para recrutamento@gympass.com

**Comment by ecouto** [comment]
Enviado
