### ISSUE TITLE
[Remoto / Joinville - SC] Desenvolvedor(a) FrontEnd / Mobile Sênior na JetBov

### ISSUE THREAD

**Issue by CassioRecruiter** [frontendbr/vagas#3952]
## Nossa empresa

A JetBov é uma Startup que está transformando a pecuária de corte no mundo. Usamos a tecnologia de inteligência artificial e armazenamento de dados com o objetivo de digitalizar a cadeia produtiva da bovinocultura de corte. Nosso propósito é empoderar o(a) pecuarista, através de informação e oportunidades, agregando maior valor a cadeia de forma sustentável.

Quer saber como é ser um **JetBover**? Acesse o link:

https://jetbov.com/vagas/

## Descrição da vaga

Como **Desenvolvedor(a) Sênior** você irá ter um importante papel no desenvolvimento do nosso produto, incorporando novas funcionalidades, arquiteturas e tecnologias. Fará parte de um time experiente e inovador em uma empresa em constante crescimento.

Praticamos uma cultura de autonomia, responsabilidade, velocidade, qualidade de entrega e meritocracia.

**Responsabilidades:**

- Desenvolver código FrontEnd;
- Desenvolver código Mobile;
- Estruturar a evolução do stack de desenvolvimento Web e Mobile;
- Participar ativamente de uma equipe usando processo de desenvolvimento Ágil;
- Realizar atividades de garantia de qualidade (ex.: TDD);
- Automatizar testes FronEnd e Mobile;
- Realizar versionamento de código (Git), utilizar e melhorar processos de ciclo de vida de software (ALM);
- Estruturar e executar processo de deploy de App Mobile.

## Local

Exemplo: Remoto ou Escritório (Joinville - SC)

## Requisitos

**Obrigatórios:**

- Graduação em Ciência da Computação, Sistemas Aplicativos ou experiência equivalente;
- Experiência em desenvolvimento e serviços Cloud / SaaS;
- Experiência com arquitetura de software e boas práticas como clean code, design patterns, componentização e integração;
- Proficiência em linguagens (HTML, CSS, JS) e framework de FrontEnd (Angular, React, e preferencialmente com Vue.JS);
- Habilidade com testes automatizados e modelo TDD;
- Habilidade com ferramenta e modelo GIT para versionamento de código;
- Habilidade de trabalhar em equipe com autonomia e responsabilidade.

**Desejáveis:**

- Modelagem e consumo de API;
- Experiência com metodologia ágil (Scrum / Kanban);
- Habilidade com práticas ágeis de programação (ex.: Pair programming, testes unitários, code review);
- Conhecimento com Deploy Mobile.

## Benefícios

- Atuar com as mais modernas tecnologias incluindo IA, ML e IoT;
- Ambiente casual que estimula e valoriza atitudes inovadoras;
- Poder participar da transformação da vida de pessoas que trabalham e vivem da Pecuária de Corte no Brasil e no Mundo;
- Plano de saúde com cobertura nacional, sem desconto em folha para titular (*);
- Vale refeição ou alimentação (*);
- Vale transporte (*);
- Horário flexível.

_(*) Para contratações no modelo CLT._

## Contratação

PJ ou CLT

## Como se candidatar

**Tem interesse na vaga?** Envie um email para: talentos@jetbov.com

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
