### ISSUE TITLE
[São Paulo / Remoto ] Full Stack Developer (Foco Front-end) NodeJS @ Vórtx #3656

### ISSUE THREAD

**Issue by jhomarolo-vortx** [frontendbr/vagas#3953]
## Nossa empresa

Somos um time de tecnologia com foco no cliente (interno e externo) e em inovação constante, sempre voltado para resultados de negócio e entregas.

Também somos agilistas, portanto XP/SCRUM/Kanban/Pair Programming fazem parte do nosso dia a dia. Inclusive trabalhamos em Squads.

## Descrição da vaga

Desenvolvimento de novos sistemas, implantação, manutenção de sistemas e suas API's – REST e GraphQL;

Nossa Stack é principalmente feita em C# e NodeJS (que está crescendo muito por aqui), porém possuímos minoritariamente sistemas em PHP;

Possuímos inúmeros bancos de dados, mas os predominantes são SQL Server, MongoDB e PostgreSQL. Assim, seria legal você saber sobre SQL / Big Data / NoSQL;

Propor novas tecnologias e formas diferentes de programar, afinal nada é escrito na pedra 😉.

Gostamos muito de DDD/ BDD / TDD / Clean Architecture, estes conceitos precisam estar claros para você pois irá colocá-los em prática aqui.

Nosso site: https://vortx.com.br/
## Local

Remoto ou Escritório (estamos remoto durante a pandemia) , São Paulo - em frente ao metrô Pinheiros

## Requisitos

**Obrigatórios:**

· Conhecimento sólido em arquitetura web;
· Conhecimento sólido em pelo menos uma linguagem de programação;
· Sede por aprender coisas novas;
· Boa comunicação e gostar de trabalhar em equipe;
· Inglês intermediário/avançado.
· Gostar de contribuir para projetos open-source, temos uma biblioteca própria, o herbsJS e estamos em constante evolução nesta frente.

**Desejáveis:**
· Node.js;
· SQL;
· AWS;
· Angular / React

**Diferenciais:**
- projetos opensource (@herbsjs)
- meetups
- participação em comunidades e eventos
- treinamentos técnicos
- auxilio para certificações

## Benefícios

- Plano de saúde
- VR/VA de R$ 1.150 por mês
- Auxílio creche
- Bônus (PLR)
- Auxílio educação
- Oportunidade de compra de ações 

## Contratação

CLT Full

## Como se candidatar

Se cadastre pelo [Kenoby](https://jobs.kenoby.com/vortx/job/desenvolvedor-full-stack/5e50139600d72114f5ac396b)

## Tempo médio de feedbacks

Nosso processo é bem rápido e costumamos não ser burocráticos.
Costumamos enviar feedbacks em até 2 dias após cada processo. E o processo no total costuma levar de 1 a duas semanas.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by roxdavirox** [comment]
Excelente vaga, me inscrevi lá! <3

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by jhomarolo-vortx** [comment]
vaga aberta ainda :)
