### ISSUE TITLE
[Remoto] Desenvolvedor(a) Front-end Angular 8 - Pleno/Sênior na Supero

### ISSUE THREAD

**Issue by larissaaguiar** [frontendbr/vagas#3954]
## Nossa empresa

Somos movidos por desafios e buscamos soluções que atendam às necessidades de nossos clientes e os deem destaque no mercado em que atuam. Com projetos personalizados para suas demandas, trazemos sempre as melhores tecnologias e práticas inovadoras que elevam nossos clientes para o próximo nível.

## Descrição da vaga

Responsabilidades
Desenvolver e testar soluções na tecnologia Angular 8, utilizando boas práticas de desenvolvimento de software;
Auxiliar nas soluções de negócio/sistema do cliente, ideias de negócio;

Sobre o projeto
Atuará com projetos de gestão da produção industrial (soluções para manufatura avançada - industria 4.0), com foco em desenvolvimento de novas aplicações e manutenção do sistema legado. 

## Local

Remoto

## Requisitos

**Obrigatórios:**
Formação
Graduação completa ou em andamento em Análise e Desenvolvimento de Sistemas ou áreas afins.

Domínio na tecnologia Angular 8 (ou superior);
Conhecimento de consumo de API´s Rest;
Orientação a Objetos;
Conceitos de microserviços, APIs;
Postman/Insomnia;
Git;

**Diferenciais:**
Conhecimento em recursos do Google Cloud e Firebase;
Conhecimento AzureDevOps.
**Desejáveis:**
- conhecimentos em ruby on rails
- conhecimentos em C#

## Benefícios

Horários flexíveis;
Happy Hour;
Ginástica Laboral;
Convênios e descontos;
Treinamentos;
Programa Indique um amigo..

## Contratação
Cooperativa

## Como se candidatar

Candidate-se em:  https://bit.ly/3lWzm9p

#### Alocação
- Remoto

#### Regime
Cooperativa

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
