### ISSUE TITLE
[remoto] Desenvolvedor(a) FullStack .Net + Angular - Pleno/Sênior na Supero

### ISSUE THREAD

**Issue by larissaaguiar** [frontendbr/vagas#3955]
## Nossa empresa

Somos movidos por desafios e buscamos soluções que atendam às necessidades de nossos clientes e os deem destaque no mercado em que atuam. Com projetos personalizados para suas demandas, trazemos sempre as melhores tecnologias e práticas inovadoras que elevam nossos clientes para o próximo nível.

## Descrição da vaga

Responsabilidades
Desenvolver e testar soluções na linguagem .NET C# + Angular, utilizando boas práticas de desenvolvimento de software;
Auxiliar nas soluções de negócio/sistema do cliente (SOLID, DDD, Clean Code);

Sobre o projeto
Atuará com projetos de gestão/operação portuária, com foco em desenvolvimento de novas aplicações e manutenção do sistema legado. 

## Local

Remoto

## Requisitos

**Obrigatórios:**
Conhecimento em ASP.NET C# (ORM) ou .NET Core 2.1 ou superior (Full Framework);
Consumo e desenvolvimento de APIs REST;
Conhecimentos em Docker, para criação de Docker File/Compose;
Conhecimentos em Angular 8 ou superior
Banco de dados: Oracle (Querys)
Orientação a Objetos;
Git;

**Desejáveis:**
Conhecimento Oracle/PL/SQL;
Conhecimento em HMTL5, CSS3 e TypeScript;
Conhecimento em Xamarin;
Experiência com Mensageria;
Vivência em equipes com métodos ágeis.

## Benefícios

Horários flexíveis;
Happy Hour;
Ginástica Laboral;
Convênios e descontos;
Treinamentos;
Programa Indique um amigo.

## Contratação

Cooperativa

## Como se candidatar

Candidate-se em: https://bit.ly/2VRn2wp

#### Alocação
- Remoto

#### Regime
Cooperativa

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
