### ISSUE TITLE
[São Paulo] Head de Tecnologia na Glory

### ISSUE THREAD

**Issue by Pedromelemen** [frontendbr/vagas#3957]
> Vaga Remota durante a pandemia

## Descrição da vaga
**Time de Engenharia:**

A equipe de engenharia da Glory está sendo montada do zero com foco no desenvolvimento de um produto divertido e inovador, mesclando profissionais experientes e funcionários com potencial de crescimento, em um ambiente fortalecido pelo aprendizado, compartilhamento de experiências e respeito.

Entendemos que a execução é a chave para o sucesso, e daremos autonomia e todo suporte desejado aos desenvolvedores para implementarem suas ideias. Juntos, construiremos o primeiro unicórnio de Wellbeing e Insurtech do Brasil.

**Nosso Business**

A Glory é uma corretora de Seguro de Vida digital B2B2C. Nosso objetivo é revolucionar o mercado de Seguro de Vida no Brasil. Impulsionados por essa missão, nós protegemos e recompensamos os membros ativos por seus hábitos saudáveis, como a prática de atividades físicas e mentais.

**Estamos desenvolvendo dois produtos:**
- Aplicativo para colaboradores
- Software para departamentos de RH
Levantamos um capital relevante junto a investidores anjo para, em 2021, ajudarmos as empresas a fortalecer seus programas de Wellbeing e transformar a relação das pessoas com o Seguro de Vida.

“Nossa missão é fazer com que as pessoas vivam mais e melhor, de forma divertida e animadora. Queremos criar equipes mais felizes, saudáveis e produtivas.” (Bruno Pierri, CEO - Chief Executive Officer – Criou, investiu e mentorou mais de 35 startups em incubadora e aceleradora de Startups em Londres, focado nos setores de Insurtech, Healthcare e AI)

**Responsabilidades**

Você vai liderar, arquitetar e desenvolver soluções escaláveis de alta qualidade, montando equipes multidisciplinares, que buscam uma experiência incrível e eficiente para os usuários. Queremos alguém que consiga tirar nossas ideias do papel, com foco na construção e gestão de um time direcionado para desenvolver soluções que resolvam problemas complexos e criem um produto de extrema qualidade aos nossos usuários.

A equipe de engenharia da Glory trabalha com variedades de tecnologias e técnicas para resolver nossos desafios. Tentamos ver sempre além das “palavras da moda” para desenvolver um software de forma pragmática e eficiente.

Atualmente trabalhamos com a tecnologia Flutter.

## Local

Remoto ou Escritório, [SP], [São Paulo]

## Requisitos

- Experiência relevante em cargos de alta performance em engenharia de software, além de cargos de liderança (técnico ou gestão de pessoas);
- Experiência excepcional em codificação e arquitetura de software em projetos de grande escala;
- Excelente visão de negócios, capaz de identificar e priorizar problemas de alto impacto, influenciando as equipes de engenharia de toda a organização na solução desses problemas;
- Experiência em trabalhar em ambiente colaborativo de equipes de engenheiros, gerentes de produto e designers;
- Disponível para aprender outras linguagens de programação, se necessário.

## Benefícios

- Seguro de Vida
- Vale Refeição
- Plano de Saúde
- Stock option (Ao ajudar a empresa à escalar seus negócios e atingir os objetivos descritos em nossa missão, você terá a possibilidade de receber ações da Glory à um valor pré-determinado)

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para people@glorylife.com.br com seu CV anexado - enviar no assunto: Vaga Head de Tecnologia

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
