### ISSUE TITLE
[São Paulo] Front-end Developer na Docket

### ISSUE THREAD

**Issue by RecrutamentoDocketBrasil** [frontendbr/vagas#3959]
> Vaga Remota durante a pandemia

## Nossa empresa

A Docket é uma startup que realiza busca, gestão e pré-análise de documentos. Com tecnologia avançada e inovadora, otimizamos os processos jurídicos de empresas de vários segmentos. Atuamos como facilitadores para nossos clientes, pois reduzimos o custo e o prazo com demandas de documentação. 

## Descrição da vaga

Desenvolver páginas web com base em um layout criado no Adobe XD;
Realizar análises técnicas para propor as melhores soluções para o produto;
Participar de reuniões com o time de produto para definição de boas práticas de design, usabilidade e interações;
Manutenção do style guide e design system junto do time de design;
Trabalhar em equipe utilizando a metodologia ágil SCRUM;
Criação de POCs (provas de conceito) para validar ideias para implementação no produto;
Ajudar a construir e manter nossa bibliotecas de componentes front-end;
Prestar suporte aos usuários durante e após as entregas do projeto;

## Local

Remoto, [São Paulo], [São Paulo], [Pinheiros]

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com HTML 5, CSS 3, JavaScript, Thymeleaf e REACT;
- Noções de desenvolvimento de páginas responsivas utilizando bootstrap e Ajax;
- Conhecimento intermediário ou avançado em lógica de programação. 

**Desejáveis:**
- conhecimentos na construção de design systems;
- conhecimentos em protótipos e trabalho com time de UI/UX;

**Diferenciais:**
- conhecimentos em sistemas/plataformas complexas (preferencialmente SaaS).

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ 30/dia
- Auxílio creche
- Plano odontológico

**Diferenciais:**

-  Ambiente descontraído, criativo e com oportunidade de crescimento acelerado =)

## Contratação

CLT

## Como se candidatar

Por favor envie um email para vagasdocket@gmail.com com seu CV anexado - enviar no assunto: Vaga Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.
E-mail para contato em caso de não haver resposta: vagasdocket@gmail.com

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
