### ISSUE TITLE
[São Paulo] Node.JS Developer

### ISSUE THREAD

**Issue by Dani-Ventron** [frontendbr/vagas#396]
## Descrição da vaga

Sólidos conhecimentos em  Node.JS; Angular
Metodologias ágeis
Bootstrap
MVC
GIT

## Local

São Paulo - Barra Funda

## Requisitos

**Obrigatórios:**
Sólidos conhecimentos em  Node.JS Angular
Metodologias ágeis
Bootstrap
MVC
GIT

**Desejáveis:**
- conhecimentos em C#

## Contratação

PJ a combinar

## Nossa empresa

A VENTRON, especialista em soluções que simpliﬁcam processos com inteligência e foco no resultado

## Como se candidatar

Por favor envie um email para: daniele.silva@ventron.com.br com seu CV anexado - enviar no assunto: Vaga NodeJS

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
