### ISSUE TITLE
[Florianópolis] Front-end Developer na [Banco Digital WTK]

### ISSUE THREAD

**Issue by gcoliveira** [frontendbr/vagas#3960]
### NOSSA EMPRESA

Somos uma fintech – basicamente uma empresa de tecnologia financeira – que organiza a área de serviços financeiros com processos inteiramente baseados em tecnologia e ainda oferece produtos e serviços para auxiliar no crescimento e organização do agronegócio.

### Descrição da vaga

Desenvolver páginas web com base em um layout criado no Adobe XD;
Realizar análises técnicas para propor as melhores soluções para o produto;
Participar de reuniões com o time de produto para definição de boas práticas de design, usabilidade e interações;
Manutenção do style guide e design system junto do time de design;
Trabalhar em equipe utilizando a metodologia ágil SCRUM;
Criação de POCs (provas de conceito) para validar ideias para implementação no produto;
Ajudar a construir e manter nossa bibliotecas de componentes front-end;
Prestar suporte aos usuários durante e após as entregas do projeto;

### Local

[Florianópolis]

### Requisitos

Obrigatórios:

    1 anos de experiência com HTML 5, CSS 3, JavaScript e REACT;
    Noções de desenvolvimento de páginas responsivas utilizando bootstrap e Ajax;
    Conhecimento intermediário ou avançado em lógica de programação.

Desejáveis:

    conhecimentos na construção de design systems;
    conhecimentos em protótipos e trabalho com time de UI/UX;

### Diferenciais:

    conhecimentos em sistemas/plataformas complexas (preferencialmente SaaS).

### Diferenciais:

    Ambiente descontraído, criativo e com oportunidade de crescimento acelerado =)

### Contratação

CLT

### Como se candidatar

Por favor envie um email para rh@wtkagro.com.br com seu CV anexado - enviar no assunto: Vaga Front-end
Tempo médio de feedbacks

**Comment by XLucifer** [comment]
Boa tarde.

Esta vaga tem a modalidade home office para quem não mora em Santa Catarina?

Obrigado.

**Comment by gcoliveira** [comment]
Não. Somente presencial.



Att,
--



Em ter., 8 de dez. de 2020 às 14:52, André Luz da Silva <
notifications@github.com> escreveu:

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
