### ISSUE TITLE
[São José dos Campos] Front-end Developer na DeepESG

### ISSUE THREAD

**Issue by fbaltor** [frontendbr/vagas#3968]
## DeepESG

Somos uma **greentech** brasileira em estágio inicial, disposta a revolucionar os critérios de mensuração de **impacto socioambiental** e assim dar as **novas diretrizes de investimentos sustentáveis**.

Estamos em sintonia com a crescente demanda do mercado por investimentos baseados na filosofia **ESG - Environmental, Social and Corporate Governance**, que já se manifesta em nomes grandes e consolidados do mercado, como a XP Investimentos no Brasil e o fundo internacional Nordea. Além disso, estamos também alinhados com as pesquisas de vanguarda na academia (Harvard Business School).

Nosso produto é, por fim, a implementação das mais modernas soluções para os maiores desafios deste século: as **mudanças climáticas** e a **desigualdade social**.

## Descrição da vaga

Na área de tecnologia somos um time pequeno e integrado, com um perfil profissional proativo e ávido, dispostos a criar soluções on demand.

Procuramos um desenvolvedor front-end júnior para nos auxiliar na constante construção e lapidação das nossas plataformas de visualização de dados. Para se ter uma ideia do que seria uma plataforma similar, acesse o seguinte link: https://exchange.bitpanda.com/.

## Local

Remoto ou híbrido, com escritório em São José dos Campos, São Paulo, Palmeiras de São José.

## Requisitos

**Obrigatórios:**
- Conhecimento robusto de arquitetura web (modelo cliente-servidor, etc).
- Base forte em Javascript ES2015+.
- Noções básicas de layout, CSS e design responsivo.
- Disponibilidade para jornada de trabalho integral (~40 horas semanais).
- Experiências prévias em projetos pessoais ou profissionais.
- Inglês intermediário/avançado.
- Boa comunicação interpessoal (falada e escrita).

**Desejáveis:**
- Familiaridade com frameworks modernos: ReactJS, Vue, Angular ou similares.
- Consumo de APIs RESTful.
- Git.
- Metodologias ágeis, SCRUM.
- Database e SQL: Microsoft SQL Server, PostgreSQL, MongoDB.
- Disponibilidade para trabalhar presencialmente.

**Diferenciais:**
- Portfólio de projetos (pessoais, profissionais).
- Contribuição em projetos Open Source.

**Não estamos preocupados com idade, formação acadêmica ou extensa experiência profissional prévia. Nos interessa mais o seu conhecimento atual de programação, velocidade de aprendizado, curiosidade intelectual e comprometimento. Projetos anteriores, pessoais ou profissionais, são um grande ponto positivo.**

## Benefícios

- Remuneração em linha com o mercado, porém com **possibilidade de crescimento agressivo**.
- Possibilidade de trabalho remoto.
- Horário extremamente flexível.

## Contratação

PJ, MEI e CLT a combinar.

## Como se candidatar

Para se candidatar, acesse o seguinte formulário: https://forms.gle/CwZ32GHixAEZxdhf6.

#### Regime
- CLT
- PJ
- MEI

#### Nível
- Júnior
- Pleno

**Comment by redmasters** [comment]
Olá, ainda tem vaga pra estágio?

**Comment by fbaltor** [comment]
> Olá, ainda tem vaga pra estágio?

Sim!

**Comment by SaMatheus** [comment]
@fbaltor  E como fazemos pra nos candidatar para a vaga de estágio?
