### ISSUE TITLE
[Curitiba] Front-End Developer

### ISSUE THREAD

**Issue by EduardoLangowski** [frontendbr/vagas#397]
## Descrição da vaga

Colaborar no desenvolvimento de aplicação SPA/WEB com mais de 2000 clientes.

## Local

Escritório em Curitiba, Bairro Bigorrilho

## Benefícios

- 1:30 horas de almoço
- Trabalhar com Mac 
- Frigobar sempre cheio!
- Galera gente boa!
- VT
- VR
- PJ / CLT

## Requisitos

**Obrigatórios:**
CSS3, HTML5, ES / JS, etc.
Habilidades em LESS / SASS e TypeScript
Conhecimentos em design, UX, Bootstrap e design responsivo (grades CSS, Mobile First).
Trabalhar com GIT.

**Desejáveis:**
Frameworks JS como Vue.js React.js, AngularJS, Ember.js, Backbone.js, etc.

**Diferenciais:**
- projetos opensource

## Contratação

CLT/PJ a combinar

## Nossa empresa

Leads2b.com  - Empresa com solução para geração/nutrição/administração de novos negócios.

## Como se candidatar

Por favor envie um email para leonardo@langowski.com.br com seu CV anexado - enviar no assunto: Vaga Front-End

**Comment by felipecesr** [comment]
Remoto?

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
