### ISSUE TITLE
[Remoto] Full-stack Developer na AutoForce

### ISSUE THREAD

**Issue by emanuel-campos** [frontendbr/vagas#3970]
## Nossa empresa

A AutoForce é uma startup (martech) que desenvolve tecnologia e soluções de marketing digital para o segmento automotivo. Possui 5 anos de mercado, 27 colaboradores e 3 sócios fundadores. Seu modelo de negócio é do tipo SaaS, com mais de 500 concessionárias utilizando a sua principal solução, o criador e gerenciador de showrooms digitais Autódromo. Atua em todo território nacional e possui alguns dos principais grupos de concessionárias, do país, como clientes. 

No ano de 2020 a AutoForce foi homologada como parceira oficial do programa DDM (dealer digital marketing) da montadora FCA, responsável pela fabricação e comercialização dos veículos Fiat e Jeep no Brasil, tornando-se fornecedora de software para criação de showrooms digitais para as concessionárias da rede. 

No ano de 2019 a AutoForce foi acelerada pelos maiores programas de aceleração de startups da América Latina - Inovativa Brasil e Endeavor Scale-up. 

PROPÓSITO
Tornar vendas complexas em experiências incríveis, conectando compradores e vendedores de veículos pela internet.

MISSÃO
Promover a transformação digital no setor automotivo, por meio de tecnologias, processos e modelos de negócios que geram mais valor e inovação para os clientes.

VISÃO
Ser uma empresa referência em Tecnologia e Marketing Digital para o setor automotivo na América Latina até 2024, sendo reconhecida pela qualidade e inovação de seus produtos e serviços.

VALORES
1. Levamos o cliente ao pódio
2. Inovamos para vencer
3. Agimos com base em dados
4. Entregamos além do esperado
5. Temos um poderoso espírito de time
6. Somos adaptáveis

## Descrição da vaga

- Refatorar código legado;

- Construir novas funcionalidades;

- Desenvolvimento guiado por testes (TDD); e

- Trabalhar com APIs externas.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Noções de algoritmos e estrutura de dados;

- Desenvolvimento com linguagens Ruby e JavaScript;

- Saber trabalhar com tarefas da aplicação em background;

- Utilizar banco de dados SQL e NoSQL (PostgreSQL e Redis);

- Utilizar Git para versionamento de código; e

- Saber trabalhar em equipe.

**Desejáveis:**
- Ter trabalhado com infraestruturas como Heroku, Amazon e Nginx; e

- Ter trabalhado com o desenvolvimento de micro-serviços.

**Diferenciais:**
- Possibilidade de trabalho remoto;

- Ambiente informal e descontraído;

- Time dinâmico e colaborativo;

- Grande autonomia;

- Horário flexível; e

- Oportunidade de ter uma formação interdisciplinar em uma empresa ágil.

## Contratação

PJ a combinar

## Como se candidatar

Por favor acesse nosso site de vagas e inicie o processo seletivo pelo link:
https://jobs.kenoby.com/autoforce

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
