### ISSUE TITLE
[Remoto - Atlanta/US] Frontend Developer na Pinestraw

### ISSUE THREAD

**Issue by VinPinestraw** [frontendbr/vagas#3972]
Vaga para trabalho remoto full-time em uma das maiores startup da área de saúde americana, através da Pinestraw Enterprise (localizada em Atlanta/US).
Não é uma vaga freelancer, é para trabalho full-time, de segunda a sexta, em horário comercial, 40h por semana. O contrato de trabalho pode ser W-2 (se você tiver cidadania americana), contrato PJ ou como funcionar melhor para você (pode ser até por bitcoin).

Abaixo seguem os detalhes da vaga em inglês, caso deseje mais informações sobre a vaga ou se candidatar envie um e-mail para vin@pinestraw.org com sua pergunta e /ou currículo (em inglês).

Frontend Software Engineer
Responsibilities
- Build upon, architect, scale, work on building our platform in VueJS that support and help millions of users
- Maintain and become familiar with our legacy and modern systems, and the intricacies that come along with them
- Write high quality and well tested code to meet the needs of our users
- You'll innovate and take ownership of new features and development projects
- Passionate about working to help millions of people
- Able to work independently and collaboratively in a team environment
Requirements
- Write performant, maintainable code that is easy to read and well-documented
- 2+ years of experience working with VueJS, AngularJS, or React
- 5+ years of experience doing software development
- Capable of working on PDT time from 9-5 daily
- 5+ years of experience working with git, subversion, or mercurial
- Experience working in a scrum and agile based environment
- Experience working with a handoff tool such as Figma, Marvel, or Invision (or similar)
- Experience working in a remote environment or capable of working in a remote environment
Benefits
- This is a full-time position (40 hours per week)
- Payment can be made via bank transfer, eBanx, PayPal or Bitcoin (all Contractor option) OR bank transfer/wire for W-2 position (only for US citizen) 
- Overtime (if applicable)
Preferences
- Resource must be in the Western hemisphere (South America, Latin America, North America, or the Carribean)
- You must be able to speak good English for communication purposes
- You must be available 8 hours a day, 40 hours full time per week

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
