### ISSUE TITLE
[Remoto] Front-end Developer Pleno no Inatel

### ISSUE THREAD

**Issue by lpliao** [frontendbr/vagas#3975]
## Descrição da vaga

O Inatel está recrutando Especialista para atuar como Desenvolvedor de Software no ICC Wireline. 

## Local
 - Remoto 

## Requisitos

**Obrigatórios:**
 - Formação superior em Engenharia, sistemas de informação e/ou áreas correlatas;
 - Experiência em desenvolvimento de projetos em Javascript (NodeJS e Angular);
 - Conhecimentos em: Desenvolvimento Frontend, utilizando Javascript, CSS3, HTML5, JSON, Desenvolvimento Backend, utilizando NodeJS, Angular 2, REST APIs, Banco de dados MySQL e MongoDB, Git, Linux.

**Desejáveis:**
 - Conhecimentos em: Docker, Angular 6, RabbitMQ, Scrum,  arquitetura (ex: Monolítico, microsserviços).

## Contratação

CLT

## Como se candidatar

Por favor envie um email para vagas@inatel.br com seu CV anexado - enviar no assunto: Vaga ESII Wireline ou pelo link vagas.com.br/v2131032

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
