### ISSUE TITLE
[Rio de Janeiro] Front-end Developer Júnior na Pluga

### ISSUE THREAD

**Issue by leocamelo** [frontendbr/vagas#3976]
> Vaga Remota durante a pandemia

## Nossa empresa

A [Pluga](https://pluga.co/) é uma ferramenta que conecta outras ferramentas web. Integramos qualquer ferramenta que possua API disponível e disponibilizamos essas integrações para serem configuradas de maneira autônoma pelos nossos usuários, que não possuem background técnico.

## Descrição da vaga

Buscamos uma pessoa pra integrar nosso time de tecnologia, o seu primeiro desafio é auxiliar nossa equipe de UI/UX na elaboração de novos produtos e implementação de ajustes e funcionalidades na Pluga, que são usados tanto pelos nossos +4000 usuários quanto pela nossa equipe.

O segundo desafio é, a partir de sugestões de clientes, identificar oportunidades de melhoria nos produtos da Pluga e eventuais correções de bugs.

## Local

Estamos em Copacabana, no Rio de Janeiro. Nesse momento, em pandemia, estamos em regime remoto.

## Requisitos

**Obrigatórios:**
- 1 ano de experiência com JavaScript
- React
- HTML/CSS
- Git
- Frameworks de teste (TDD/BDD)
- Consumo de APIs REST
- Muita vontade de aprender ⚡
- Desejo de trabalhar em um ambiente de trabalho respeitoso, transparente e colaborativo, seguindo os valores e cultura da Pluga

**Desejáveis:**
- TypeScript
- Algum framework backend (ex: Ruby on Rails, Django)

**Diferenciais:**
- Next.js
- Testes com Jest
- Projetos opensource

## Benefícios

- Plano de saúde
- Day-off no mês do aniversário
- Oportunidade de contribuir efetivamente para o crescimento de uma startup em expansão! 🚀
- No dress code e happy hours com cerveja! 🍺

## Contratação

PJ

## Como se candidatar

Basta acessar [pluga.co/trabalhe-conosco](https://pluga.co/trabalhe-conosco/) e preencher o formulário da vaga.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: camelo@pluga.co

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Júnior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
