### ISSUE TITLE
[REMOTA] Engenheiro Front- End- AM53

### ISSUE THREAD

**Issue by suelenm** [frontendbr/vagas#3978]
Empresa Líder no mercado de pagamentos. Estamos em busca de profissionais que gostam de desafios de de trabalhar com tecnologias de ponta. 
Empresa com sua sede localizada em São Paulo Faria Lima - Vaga Remota. 

## Descrição da vaga

Requisitos
• Experiência na criação de páginas responsivas, web e mobile • Experiência em desenvolvimento de aplicações web utilizando Javascript avançado (OO, herança, prototipação, design pattern, jQuery, ES6). • Experiência em CSS Avançado (SASS e LESS) e CSS3 • Experiência em suporte a browsers antigos (graceful degradation) • Conhecimentos de Regex • Domínio de protocolo (HTTP, HTTPS, cross domain) • Conhecimentos de arquitetura backend (servidor web, estático, BFF) • Conhecimento de React, Vue

Desejáveis
• Conhecimentos relacionados a performance (gzip, minify, quantidade de requests) • Testes automatizados • Conhecimento em Apache Velocity • Conhecimento de virtualização (Docker, Mesos)

## Benefícios
Vale Refeição , 
Assistência Medica 
Odontológica
Participação nos lucros
Seguro de vida
Descontos em cursos e faculdades 
Cartão Farmácia 
Benefícios sem desconto. 

## Contratação

CLT 

## Como se candidatar
Envie o currículo atualizado para suelen.matta@am53.com.br no Assunto informar o cargo pretendido . 

Nível 
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
