### ISSUE TITLE
[Remoto] Front-end Developer na Bonaparte

### ISSUE THREAD

**Issue by eduardomello** [frontendbr/vagas#3979]
## Nossa empresa

A Bonaparte é uma agência que atua tanto no marketing digital quanto no desenvolvimento de soluções web. Há 10 anos no mercado, atuando em Porto Alegre, já colaboramos com marcas como Converse, Youcom, Coca-Cola, Facebook e Heineken.

## Descrição da vaga

Desenvolvimento de novas telas em projetos existentes utilizando HTML/CSS.

## Local
Remoto

## Requisitos

**Obrigatórios:**
- Experiência com HTML/CSS

**Desejáveis:**
- conhecimentos em vue.js
- conhecimentos em docker

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para eduardo.mello@bonaparte.ag com seu CV anexado - enviar no assunto: Vaga Front-End

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Pleno
- Sênior

**Comment by brunoalvs** [comment]
Ainda aceitando candidaturas?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
