### ISSUE TITLE
[Rio de Janeiro] JavaScript Developer - Junior ou Pleno

### ISSUE THREAD

**Issue by vinicius73** [frontendbr/vagas#398]
## Descrição da vaga

Vaga na https://decision6.com/
JavaScript Developer Junio/Pleno (Vue.js, JavaScript, Node...)

Será responsável por aplicações e serviços internos e externos, usando Vue.js, Quasar Framework, Node e GraphQL.

Buscamos devs engajados em melhorar o produto, comunicativos, atentos aos detalhes... que goste de fazer a coisa bem feita.

## Local

Rio de Janeiro - Barra da Tijuca (presencial)

## Benefícios

- Salário acima do mercado
- Almoço

## Requisitos

**Obrigatórios:**
- JavaScript
- Node
- Git
- Html e CSS

**Desejáveis:**
- Vue
- Quasar Framework
- Experiencia com GraphQL
- Conhecimento de Programação Funcional

**Diferenciais:**
- Cordova
- PostgreSQL
- Webpack 
- Experiencia com Testes
- Restify 
- Knexjs 
- Electron 
- GoLang
- PHP
- Participa de comunidades de desenvolvimento
- projetos opensource

## Contratação

CLT

## Nossa empresa

Somos uma empresa inovadora que fornece informações ao mercado de varejo físico, para que ele possa entender o comportamento dos seus clientes e definir estratégias para otimizar suas receitas.

## Como se candidatar

Interessados mandar currículo, github, linkedin e afins para: vreis@decision6.com com o assunto: *Vaga JavaScript Junior/Pleno*

**Comment by ronaiza-cardoso** [comment]
Infelizmente não é remoto, seria lindo trabalhar com vocês.
