### ISSUE TITLE
[Remoto] Senior Frontend Developer na Central do Frete

### ISSUE THREAD

**Issue by xandyalexandrec** [frontendbr/vagas#3981]
## Descrição da vaga

Nós somos uma startup de tecnologia que está transformando a maneira como as empresas contratam fretes.
Contratar um frete pode ser mais fácil: nosso sistema seleciona as melhores transportadoras, você compara, contrata, faz o pagamento e consegue rastrear a carga.

Você como pessoa desenvolvedora frontend irá atuar em uma plataforma desenvolvida com React no frontend e PHP com Laravel no Backend.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência comprovada com ReactJS
- Sólida experiência com HTML/CSS
- Experiência utilizando Material UI

**Desejáveis:**
- Experiência utilizando GraphQL
- Experiência utilizando Gatsby
- Experiência com Design
- Experiência com Figma

## Contratação

Contratação PJ.

## Como se candidatar

Obs: Não se candidate se você for Junior, neste momento somos uma equipe pequena e esta vaga é destinado a Senior, não teremos capacidade para oferecer uma estrutura de aprendizado/revisão que um Junior precisa.

Por favor envie um email para alexandre@centraldofrete.com
Assunto: [Vaga] Senior Frontend Developer
Corpo da mensagem:
- Pretensão como PJ
- Github
- LinkedIn
- Link de algum projeto react que participou
- CV em Anexo

## Labels

- 🏢 Remoto
- 👴 Sênior
- ⚖️ PJ
- 💰 5k-10k

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by xandyalexandrec** [comment]
Vaga ainda disponível
