### ISSUE TITLE
[Joinville] WEB Front-end Developer na weKnowbi

### ISSUE THREAD

**Issue by EmeliPavanello** [frontendbr/vagas#3983]
> Vaga Remota durante a pandemia

## Nossa empresa

A weK Technology in Business é uma empresa comprometida em oferecer soluções inteligentes para o mercado de Business Intelligence (BI). Derrubamos o conceito de que um projeto de BI é necessariamente complexo, caro e que somente consegue apresentar resultados após alguns meses de execução.

## Descrição da vaga

Buscamos profissional para atuar no desenvolvimento de aplicações web. Seu desafio será, junto ao time, melhorar as propostas atuais e evoluir os projetos. Esperamos o uso das melhores técnicas visando a agilidade e qualidade nas aplicações.

## Local

Escritório, [SANTA CATARINA], [JOINVILLE]

## Requisitos

**Obrigatórios:**
– Experiência mínima de 1 ano em desenvolvimento web;
– Experiência com JavaScript avançado (OO, Modules, Async).

**Desejáveis:**
– Experiência com AngularJS.

## Benefícios

– Ambiente moderno que proporciona crescimento e aprendizado constante;
– Programa de bônus conforme atingimento de metas;
– Regime de contratação via Cooperativa.

**Diferenciais:**
- Modelo de trabalho híbrido

## Contratação

- Cooperativa

## Como se candidatar

Por favor envie um email para emeli.pavanello@weknowbi.com.br com seu CV anexado - enviar no assunto: WEB Front-end Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@weknowbi.com.br

#### Alocação
- Alocado

#### Regime
- Cooperativa

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
