### ISSUE TITLE
[remoto] Desenvolvedor(a) Angular Pleno @ Supero

### ISSUE THREAD

**Issue by larissaaguiar** [frontendbr/vagas#3985]
## Nossa empresa

Somos movidos por desafios e buscamos soluções que atendam às necessidades de nossos clientes e os deem destaque no mercado em que atuam. Com projetos personalizados para suas demandas, trazemos sempre as melhores tecnologias e práticas inovadoras que elevam nossos clientes para o próximo nível.

## Descrição da vaga

Responsabilidade: Desenvolvimento de software em projeto de documentação eletrônica e nota fiscal eletrônica.

## Local

 Remoto 

## Requisitos

Formação: Formação completa em ciências da computação, sistemas de informação ou cursos equivalentes.

Requisitos: Angular 2+ , REST,  HTML ,CSS, GIT. Ter um perfil proativo, boa comunicação, raciocínio lógico, responsabilidade e comprometimento.

Diferenciais/Desejável:  Angular JS,  Metodologias Ágeis; React JS.

## Benefícios

Horários flexíveis;
Happy Hour;
Ginástica Laboral;
Convênios e descontos;
Treinamentos;
Programa Indique um amigo.
## Contratação

Cooperativa

## Como se candidatar

Candidate-se em: https://bit.ly/37952E2

#### Alocação
- Remoto

#### Regime
Cooperativa

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
