### ISSUE TITLE
[remoto] Desenvolvedor(a) Fullstack Pleno/Sênior - Angular e .Net @ Supero

### ISSUE THREAD

**Issue by larissaaguiar** [frontendbr/vagas#3986]
## Nossa empresa

Somos movidos por desafios e buscamos soluções que atendam às necessidades de nossos clientes e os deem destaque no mercado em que atuam. Com projetos personalizados para suas demandas, trazemos sempre as melhores tecnologias e práticas inovadoras que elevam nossos clientes para o próximo nível.

## Descrição da vaga

Responsabilidade:  Participar de desenvolvimento de software em projeto de nota fiscal eletrônica e frete.

## Local

Remoto

## Requisitos

Formação:  Formação completa em ciências da computação, sistemas de informação ou cursos equivalentes.

Requisitos:  Conhecimento em Angular 2+, .NET,  Entity Framework,   REST,  SQL Server,   HTML ,CSS,  GIT. Ter um perfil proativo, boa comunicação, raciocínio lógico, responsabilidade e comprometimento.

Diferenciais/Desejável: Metodologias Ágeis ; Azure.

## Benefícios

Horários flexíveis;
Happy Hour;
Ginástica Laboral;
Convênios e descontos;
Treinamentos;
Programa Indique um amigo.

## Contratação

Cooperativa

## Como se candidatar
Candidate-se em: https://bit.ly/37952E2

#### Alocação
- Remoto

#### Regime
Cooperativa

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
