### ISSUE TITLE
[São José dos Campos/SP ou Remoto] Front-end Vue.JS Developer na SoluCX

### ISSUE THREAD

**Issue by thaisnakamura** [frontendbr/vagas#3988]
## Conhece a SoluCX?
A [SoluCX](https://solucx.com.br/) é uma startup joseense que entrega detalhes sobre a Experiência dos Clientes de grandes empresas por meio de Pesquisas de Satisfação transacionais que utilizam os dados para dar maior clareza aos seus resultados. 
Estamos mudando a maneira como as Pesquisas de Satisfação são realizadas e precisamos de pessoas feras para fazer parte do nosso time.

## Seu desafio no dia a dia

- Desenvolver interface de usuário usando o Vue.js;
- Manter-se atualizado com as recentes novidades no mundo Front-end e Vue.js;
- Observar as atualizações de segurança e os problemas encontrados com o Vue.js e todas as dependências do projeto;
- Altamente proficiente com a linguagem JavaScript e Typescript e sua sintaxe e recursos modernos do ES6 +;
- Altamente proficiente na estrutura do Vue.js. e seus princípios fundamentais, como componentes, reatividade e o DOM virtual;
- Familiaridade com o ecossistema Vue.js., incluindo Vue CLI, Vuex, Vue Router e Nuxt.js;
- Bom entendimento de HTML5 e CSS3.

## Demais atividades envolvidas

- Construção de bibliotecas e componentes modulares e reutilizáveis;
- Otimização de aplicativo para desempenho;
- Implementar testes automatizados integrados aos fluxos de trabalho de desenvolvimento e manutenção;
- Proficiência em ferramentas de desenvolvimento modernas, como Babel, Webpack;
- Saber filtrar o que faz sentido para o produto tecnicamente ou não;
- Habilidades para lidar com muitas tarefas ao mesmo tempo e trabalhar em equipe;
- Ter habilidades comunicativas para lidar com pessoas de diversas áreas do conhecimento.

## Nós esperamos de você

- Experiência com o consumo e o design de APIs RESTful;
- Proficiente conhecimento das ferramentas de versão de código, como Git;
- Ao desenvolver, manter sempre em mente as melhores práticas relacionadas à segurança;
- Experiência em desenvolvimento de projetos em Metodologias Ágeis;
- Habilidade para gerenciamento de suas atividades;
- Atualização constante com as novas tendências, como bibliotecas e frameworks;
- Mente aberta para lidar com um ambiente amigável e descontraído;
- Capacidade de entrega das tarefas dentro das estimativas.

**Pode ser um diferencial:**

- Propor as atualizações e atualizações necessárias para acompanhar as práticas recomendadas de segurança e desenvolvimento modernas;
- Conhecimento de programação funcional e paradigmas de programação orientada a objetos;
- Capacidade de escrever código Typescript eficiente, seguro, bem documentado e limpo;
- Familiaridade com testes automatizados de Typescript, testando especificamente estruturas como Jest ou Mocha.

## Observações
- Proposta PJ;
- Aqui o ambiente é de muita autonomia, aprendizado e desafios;
- O escritório é informal, descontraído e com pessoas incríveis;
- Também temos cursos in-company (técnicos, línguas);
- Bônus por produtividade.

Para se candidatar, [clique aqui](https://solucx.com.br/talento-front-end-vue/) (:

#### Regime
- PJ

#### Nível
- Júnior
- Pleno
- Senior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
