### ISSUE TITLE
[São Paulo / Remoto] Front-End Developer na PyDev

### ISSUE THREAD

**Issue by ivokoga** [frontendbr/vagas#399]
## Descrição da vaga

Startup de consultoria política que se baseia na análise de dados legislativos, procura Desenvolvedor Front-End Python para integrar equipe.

## Local

Possibilidade de trabalhar remotamente, uma vez comprovado o comprometimento com o projeto. Estamos sediados em São Paulo.

## Requisitos

**Obrigatórios:**
- Front-end web development (Javascript, HTML5, CSS, etc)
- Conhecimento em Bootstrap
- Conhecimentos de UX/UI
- Habilidades de comunicação verbal e escrita excelentes
- Disponibilidade de 40 horas semanais
- Experiência no desenvolvimento de front com consumindo backend em Django.

**Desejáveis:**
- Experiência em Python e Django
- Desenvolvimento de layout responsivo
- Desenvolvimento limpo/fluído e comentado.

## Contratação

PJ a combinar

## Nossa empresa

- um time de profissionais com altíssima qualificação, entusiastas e com foco na inovação e pesquisa
- consultoria estratégica com vínculo a grupos de pesquisa da USP
- rigor acadêmico na construção das análises e indicadores.
- não fazemos lobby, nem indicamos quem faça.
- os resultados gerados têm fundamentos científico, ou seja, não arredondamos análises nem dados para satisfazer clientes.

## Como se candidatar

Interessados, favor encaminhar currículo com pretensão salarial para selecao@ellopolitico.com.br com o título: [Front-End PyDev]

**Comment by ecouto** [comment]
Que lugar de são paulo fica a empresa @ivokoga

**Comment by ivokoga** [comment]
@ecouto Fica na Vila Mariana e com possibilidades de trabalho remoto.

**Comment by netojose** [comment]
Front-End Python? Python é server side, no front é javascript. Meio confuso aí, a meu ver.

**Comment by simaodeveloper** [comment]
@netojose provavelmente estão dizendo que o Front-End vai trabalhar com Template Engine do Django, Um exemplo https://docs.djangoproject.com/en/1.11/ref/templates/builtins/
