### ISSUE TITLE
[remoto] Desenvolvedor(a) React JS Pleno/Sênior @ Supero

### ISSUE THREAD

**Issue by larissaaguiar** [frontendbr/vagas#3990]
Na Supero somos movidos por desafios, valorizamos a alta performance e quem pega junto com a equipe pra fazer acontecer! Estamos há 17 anos no mercado, realizando projetos personalizados de acordo com a necessidade de cada cliente. Nosso grande diferencial é trabalhar sempre com as melhores tecnologias e  um elevado nível de resolutividade. 
Buscamos um perfil #Supers para agregar ao time. Você busca evolução contínua? Está a procura de novos desafios? Então confere essa oportunidade!  

O que você irá fazer?

Aqui você vai atuar junto com a equipe de devs em projetos voltados para a área jurídica. Buscamos um perfil proativo, com boa comunicação, raciocínio lógico, responsabilidade e comprometimento. Esperamos de você:

Definir a arquitetura e construir o frontend de sistemas e aplicações web e mobile, utilizando tecnologias atuais e atendendo requisitos de responsividade e acessibilidade na web, implementando códigos que sejam escaláveis, fáceis de manter, eficientes e elegantes;
Definir boas práticas, mantendo-se atualizado nas novas tecnologias de frontend e capacitando outros desenvolvedores;
Participar de projetos de desenvolvimento de novos softwares, avaliando os protótipos entregues pelo designer, planejando e implementando a estrutura e componentes da interface, utilizando para isso o framework de javascript React;
Participar de projetos de customização de softwares já existentes utilizando um framework interno, AngularJS ou React;
Apoiar e orientar a elaboração de rotinas automatizadas de testes, utilizando-se de ferramentas e padrões para os testes necessários;
Ser capaz de desenvolver uma SPA (Single Page Application) utilizando React;
Saber utilizar gerenciadores de estado da aplicação (Redux e etc)
Conhecimento em integrar as SPAs com REST APIs;
Experiência em testes unitários automatizados para a aplicação (Jest, Enzyme e etc);
Conhecimento avançados em ES6;
Experiência em bancos de dados relacionais SQL Server/Oracle;
Ter conhecimentos de arquitetura de software;
Conhecimento em controle de versão (Git);

O que você traz?

Conhecimento em JavaScript e no framework ReactJs, incluindo conceitos de programação assíncrona, definições de escopo (clojures), componentização e ES6+;  
Conhecimento em GraphQL em alguma biblioteca de mercado (Apollo, Relay); 
Conhecimento em gerenciadores de estados, incluindo Redux e seus padrões de arquitetura;  
Conhecimentos avançado em HTML e CSS, incluindo conceitos de layout, compatibilidade entre browsers e acessibilidade;  
Conhecimento em paradigmas de orientação a objetos e funcional;  
Conhecimento intermediário em GIT;  
Conhecimento intermediário em apis REST e testes automatizados;  
Conhecimento em algumas das bibliotecas Webpack, Gulp ou Grunt;  
Conhecimento de técnicas e práticas de Clean Code;  
Experiência em equipes dinâmicas e metodologias de desenvolvimento ágeis; 
 
Você irá se destacar se tiver:

Formação completa em ciências da computação, sistemas de informação ou cursos equivalentes;  
Conhecimento em princípios de design de interação, UX e Design System;  
Conhecimento das diretrizes de interfaces da Google (Material Design);  
Conhecimento em Java, Go e outras linguagens backend;  
Conhecimento em bancos de dados relacionais e não relacionais;  
Conhecimento em outros frameworks JavaScript como Angular, Vue.js etc. Nível básico/intermediário em inglês ou espanhol

O que oferecemos:

Ginástica Laboral;
Horários flexíveis;
Convênios e descontos;
Workchopps;
Treinamentos;
No dress code;
Programa indique um amigo;
Cultura que valoriza feedbacks e a diversidade;
Oportunidades profissionais a todo momento!

Eai? Quer ser um #Supers? Então corre e se inscreve ;)

Candidate-se em: https://bit.ly/3gIwBaE

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
