### ISSUE TITLE
[Remoto] Front-End Developer ReactJs/ReactNative Pleno ou Sênior na Softo

### ISSUE THREAD

**Issue by fseixas** [frontendbr/vagas#3993]
## Nossa empresa

Somos um atelier de desenvolvimento de software focado na criação de sistemas que geram valor para nossos clientes. Nossos valores são capacidade de pensar como o cliente, foco na geração de resultado acima da simples implementação de tecnologia de qualidade e espírito de parceria. Somos agnósticos de tecnologia e nossos pilares de atuação são (1) desenvolvimento de aplicações web, mobile e micro-serviços, (2) planejamento, operação e otimização de infraestrutura na nuvem - DevOps e (3) soluções baseadas em blockchain, smart contracts e DLT. http://sof.to

## Descrição da vaga

Estamos à procura de um desenvolvedor sênior front-end em ReactJs que tenha conhecimentos também em React Native, interessado em trabalhar na criação de aplicativos móveis e sistemas web de alto desempenho e que tenha pelo menos 2 anos de experiência nesse framework e pelo 6 anos de experiência em desenvolvimento de software.

Você será responsável por desenvolver interfaces web a partir de especificações realizadas pelo time de design primariamente utilizando ReactJs mas também atendendo demandas de desenvolvimento e manutenção em sistemas desenvolvidos com React Native.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Pelo menos 2 anos de experiência em ReactJs e React Native e pelo 6 anos de experiência em desenvolvimento de software em geral.
- Grande conhecimento em desenvolvimento ReactJs
- Habilidade para desenvolver em Typescript
- Experiência em desenvolvimento React Native
- Capacidade de escrever código limpo e bem documentado

**Desejáveis:**
- Experiência de desenvolvimento mobile em React Native
- Conhecimento em operação de sistemas em ambiente cloud
- Conhecimento de AWS

## Contratação

De R$7.000 a R$ 9.000 dependendo da experiência e senioridade, por contrato de prestação de serviço.

## Como se candidatar

Enviar CV aqui https://airtable.com/shruSfs2Ji2HNwzAT

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
