### ISSUE TITLE
[Belo Horizonte] Front-End Developer Júnior/Pleno na Onisys

### ISSUE THREAD

**Issue by mateusncosta** [frontendbr/vagas#3995]
> Vaga Remota durante a pandemia

## Descrição da vaga

Automatizamos as inspeções de atos e condições inseguras em ambientes de risco e digitalizando os processos de gestão de segurança do trabalho.

Procuramos um desenvolvedor Frontend para atuar conosco em:

-Desenvolver novas features focadas na experiência do usuário
-Colaborar com o produto em novas interfaces e interações
-Elaborar e manter atualizadas as documentações técnicas dos sistemas
-Criar componentes reutilizáveis e responsivos

## Local

Belo Horizonte - Funcionários

## Requisitos

**Obrigatórios:**
-Pelo menos 1 ano de experiência em ReactJs
-Utilizar banco de dados SQL
-Utilizar Git para versionamento de código

**Desejáveis:**
-Experiência de desenvolvimento mobile em React Native
-Conhecimento em operação de sistemas em ambiente cloud

## Contratação

PJ a combinar

## Como se candidatar

Cadastre-se em: https://app.pipefy.com/public/form/5BBQfTjE

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.

#### Alocação
- Alocado

#### Regime

- PJ

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
