### ISSUE TITLE
[REMOTO] – Engenheira de Software Sênior na Kenoby (Vaga para Mulheres)

### ISSUE THREAD

**Issue by Franciely12** [frontendbr/vagas#3996]
A cada 5 profissionais da área de TI, 1 é mulher, e apenas 12% dos postos de chefia do setor são ocupados por essas mulheres, é o que apresenta a pesquisa CIO 2019, realizada pela KPMG em conjunto com a Harvey Nash.

A Kenoby incentiva a inserção de mulheres no mercado da tecnologia e é uma empresa que vem revolucionando o mercado de recrutamento. Foi escolhida pela Endeavor como uma das melhores 16 scale up SAAS e atualmente recebeu um investimento de 20 milhões do fundo Astela, sendo uma das startups que mais vem crescendo no Brasil.

Buscamos mulheres que tenham propósitos, sejam proativas, mão na massa e que tenham vontade de aprender e crescer exponencialmente.

Para essa oportunidade são necessários conhecimentos em Javascript, AWS, testes automatizados, integração contínua, e entre outros.

Contratação CLT

Gostou da oportunidade e topa esse desafio? Se inscreva no link abaixo:

https://byintera.in/1s6

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
