### ISSUE TITLE
[São Paulo] Front-end Developer Reactjs @ Pixter

### ISSUE THREAD

**Issue by D440** [frontendbr/vagas#3998]
==================================================
-->
> Vaga Remota durante a pandemia

## Nossa empresa

A Pixter é uma boutique de software, focada em grandes clientes. Com um time de mais de 100 pessoas, trabalhando em projetos nos EUA, Portugal e Brasil, a Pixter está guiando a transformação digital de algumas das principais empresas do mundo.

## Descrição da vaga

Estamos em busca de Reactjs Developer, com experiência sólida, em nível Pleno/Sênior, excelente comunicação, boa desenvoltura em reuniões de planejamento, organização e bom relacionamento interpessoal.

## Local

Exemplo: Remoto durante a pandemia, futuramente na região central de SP

## Requisitos

2 anos de exp com Reactjs
HTML: padronização, acessibilidade, mobile patterns.
CSS hierárquico e de fácil manutenção.
Desenvolvimento voltado à componentização.
Domínio em Javascript nativo (ES6>).
Domínio em ReactJS e outros frameworks single-page.
Noções básicas de ferramentas para controle de versão.
Experiência com Gulp, Grunt ou Webpack.

**Desejáveis:**
- conhecimentos em VueJS;
- conhecimentos em NodeJS;

## Como se candidatar

Por favor envie um email para danilo.vieira@pixter.com.br com seu CV anexado - enviar no assunto: Vaga Reatjs

#### Regime
- CLT
- PJ

#### Nível

- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
