### ISSUE TITLE
[São Paulo] Desenvolvedor Front-End - PlugCreative

### ISSUE THREAD

**Issue by LFeh** [frontendbr/vagas#40]
## Descrição da vaga

Alguém mais voltado pra campanha (email, banner, landing page etc).
Coisa simples, mas precisaria ficar alocado porque o volume é grande.

## Local

Rua Gomes de Carvalho, Vila Olímpia, São Paulo
 
## Requisitos

**Obrigatórios:**
- HTML
- CSS
- JavaScript
- Photoshop

**Desejáveis** 
- Boas noções de Design
 
## Contratação

PJ, R$ 3500,00

## Nossa empresa

http://www.plugcreative.com.br/

## Como se candidatar

Por favor envie um email para daniel@plugcreative.com.br com seu CV anexado - enviar no assunto: Desenvolvedor Front-End

**Comment by cmpereirasi** [comment]
Pode ser remoto? Eu sou de Juiz de fora - MG

**Comment by LFeh** [comment]
Só alocado =(

**Comment by thierryrene** [comment]
enviado. :+1:

**Comment by thierryrene** [comment]
enviado. :+1:

**Comment by brunooomelo** [comment]
ainda em aberto? mandei meu CV.

**Comment by LFeh** [comment]
Não sei dizer, vou conferir.

**Comment by LFeh** [comment]
Fechou ;)

**Comment by camilatigre** [comment]
@LFeh 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
