### ISSUE TITLE
[São Paulo] Front-End UI

### ISSUE THREAD

**Issue by joaovarandas** [frontendbr/vagas#400]
## Descrição da vaga

O profissional irá atuar com o desenvolvimento de interfaces para soluções de CRM para Web e Mobile, prevendo melhores práticas e a melhor experiência do usuário;

## Local

Escritório, São Paulo - Brooklin

## Requisitos

**Obrigatórios:**
- Buscamos um profissional comprometido e focado no negócio para auxiliar na identificação e resolução de problemas, com criatividade para inovação e sugestão de melhorias;
- 3 anos de experiência com desenvolvimento de interfaces de aplicações / análise de UX;
- Sólidos conhecimentos em HTML e CSS;
- Sólidos conhecimentos e utilização de pre-compiladores de CSS;
- Experiência na criação de Ilustrações/Sprites/Ícones;

**Diferenciais:**
- Um portifólio bem montado;
- Um senso estético semelhante ao nosso;
- Conhecimento Básico em Linguagens/Lógica de Programação;
- Certificações ou experiência relevante em áreas de tecnologia;
- Desenvolvimento mobile nativo e/ou híbrido;

## Contratação

CLT Cotas 

## Nossa empresa

Se você é apaixonado por tecnologia e quer trabalhar em uma empresa inovadora, o momento é esse. A Plusoft, pioneira no desenvolvimento de soluções multicanais para a Gestão de Relacionamento com Clientes no Brasil, está ampliando o seu quadro de funcionários e buscando profissionais de frontend.  

A Plusoft desenvolve soluções de atendimento e CRM, dentro do conceito de multicanalidade, proporcionando a melhor experiência ao cliente em todos os pontos de contato e, ao mesmo tempo, promovendo a redução dos custos operacionais.

http://www.plusoft.com.br

## Como se candidatar

Por favor envie um email para joaovarandas@plusoft.com.br com seu CV anexado - enviar no assunto: 
[FrontendBR] Front-End UI

**Comment by mathvbarone** [comment]
Email enviado! :D

**Comment by joaovarandas** [comment]
Boa! 
Obrigado pela atenção pessoal, estamos recebendo todas as mensagens e vamos começar a entrar em contato e agendar conversas ainda essa semana, ok?
Valeu!
