### ISSUE TITLE
[Remoto ou Lisboa, Portugal] Senior Front-End Develper @ Integer Consulting

### ISSUE THREAD

**Issue by AnaMargaridaAlmeida** [frontendbr/vagas#4000]
> Vaga Remota durante a pandemia

## Integer Consulting 

INTEGER Consulting is a Portuguese IT consulting company with offices in Lisbon and Porto.
We specialize in Outsourcing Services, Software and Product Development and Nearshore projects.
Our team has know-how in different technologies and we have collaborators in projects from different sectors such as Banking and Insurance, Industry, Retail, Telco, Health and Energy, among others.

## Job description

Responsibilities

Participate in the design of the solution based on business requirements gathered and analyzed by analysts
Develop new features for mobile/web applications
Build reusable code and libraries across platforms
Optimize applications in terms of scalability and stability
Use the best coding standards and practices, to assure the quality of the code
Perform development testing
Collaborate with other team members and stakeholders

Skills

Degree in Informatics Engineering, Computer Science or in similar areas
Minimum of 6 years work experience in creating front-end (mobile/web) applications, using Angular 6+, Typescript, JavaScript and React Native
Experience with HTML, CSS and Bootstrap.
Experience with Agile (SCRUM) methodologies
Experience with Unit Testing and TDD
Experience with REST based APIs
Knowledge of iOS or Android development is a plus
Excellent capacity to work autonomously or integrated in a team
Excellent problem-solving and analytical skills
Proactivity and ability to adapt in a context in which priorities often change
Developed sense of responsibility, oriented to customer solutions and associated improvements
Fluent in English - written and spoken (mandatory)

Please send me your CV to margarida.almeida@integer.pt

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
