### ISSUE TITLE
[Remoto] Front-end Developer na Quave

### ISSUE THREAD

**Issue by filipenevola** [frontendbr/vagas#4001]
## Nossa empresa

quave: PASSIONATE PEOPLE TRANSFORMING CODE INTO PRODUCTS

[quave.dev](quave.dev)
[GitHub](https://github.com/quavedev/)

## Descrição da vaga

Produto utilizando:
Javascript
React
NodeJS
MeteorJS

100% Remota, trabalhe de onde quiser e ganhe em dólar!

Dedicação full-time é esperada.

## Local

Remoto

## Requisitos

**Obrigatórios:**

- Ser Brasileiro
- Ser fiscalmente ativo no Brasil
- Saber Javascript (pelo menos o conteúdo dos 6 livros [YDKJS](https://github.com/getify/You-Dont-Know-JS/blob/1st-ed/README.md))
- Saber NodeJS (já ter utilizado)
- Saber React (saber muito bem hooks e context, por exemplo)

**Desejáveis:**

- Ter participado de competições de programação
- Saber algoritmos muito bem (inclusive Grafos e assuntos mais complexos)

**Diferenciais:**

- já ter utilizado Meteor

## Benefícios

- Receber em Dólar
- Liberdade total

## Contratação

A escolha do candidato.

## Como se candidatar

Por favor envie um email para contato@quave.com.br com seu CV anexado, projetos no GitHub e porque a gente deve te contratar em uma frase com o assunto: Vaga de Front-end Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: contato@quave.com.br

## Remuneração

1k-7k USD

#### Categoria

- Front-End
- UI-UX

#### Alocação

- Remoto

#### Regime

- CLT
- PJ

#### Nível

- Júnior
- Pleno
- Sênior
- Especialista

**Comment by velton765** [comment]
Olá, sou Velton Lopes, desenvolvedor Junior front-end
Já utilizei o meteor e utilizo nodejs e react.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
