### ISSUE TITLE
[Remoto] Front-end Developer na Company Hero

### ISSUE THREAD

**Issue by diegoleft** [frontendbr/vagas#4002]
## Nossa empresa 

*Faça parte de uma Startup remote first que cresceu 300% em 2 anos*

- Toda a equipe está trabalhando 100% remota, com processos e plataformas para home office;
- Férias flexíveis;
- Aporte mensal da Company Hero em uma conta de investimento individual para você ter Previdência Privada sem taxas;
- Trabalhe com um time motivado, jovem e internacional (bom para seu inglês, alemão, espanhol ou húngaro rsrs);
- Cultura de feedback 360º para desenvolvimento pessoal e sucesso profissional;
- Ajudamos pequenas e médias empresas de todos os segmentos a crescer. Respire inovação e gestão de negócios todos os dias;
- Bônus mensal por metas e desempenho;
- Happy Hour online com a equipe toda sexta-feira às 17h.
- https://www.companyhero.com

## Descrição da vaga

- Nível: Pleno.
- Habilidades sólidas em React js
- Experiência em Next js
- Capacidade para escrever código consistente, eficiente, minimalista, reutilizável e escalável
- Desenvolver código semanticamente correto e otimizado para SEO
- Experiência em manipulação de API externas
- Controle de versão (Git)
- Experiência com grids fluídos e sites responsivos
- Proficiência em JavaScript, HTML5, CSS, LESS

## Local

100% Remoto (para sempre)

## Requisitos

**Obrigatórios:**
- 3+ anos de experiência com Front-end
- 1+ anos de experiencia com React js
- Ser ágil e versátil para responder a diferentes demandas
- Domínio da comunicação verbal e escrita
- Alto nível de organização e atenção aos detalhes
- Capacidade de trabalhar em um ambiente multifuncional, multi-linguagem e colaborativo, de maneira autônoma;

**Desejáveis:**
- conhecimentos de libreria Ant.design
- conhecimentos em Next.js
- conhecimentos em Web-vitals

**Diferenciais:**
- Conhecimento de outras linguagens de programação, desenvolvimento mobile ou backend (node ou python em especial).
- Conhecimento de boas práticas de qualidade como TDD e BDD.
- Ter projetos opensource, portfólio ou sites online
- Inglês intermedio ou avançado
- Experiência com React Native
- Familiarizado com princípios ágeis
- Experiência com tecnologias para aplicações real-time;

## Benefícios

- previdência privada

## Contratação

PJ

## Como se candidatar

Preencher formulário https://go.companyhero.com/front

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by pauladiniz** [comment]
Só queria comentar que adorei o Remoto (pra sempre). Hahaha

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
