### ISSUE TITLE
[Remote] Senior Front-end Developer na ipanema.tech

### ISSUE THREAD

**Issue by givigier** [frontendbr/vagas#4006]
## Nossa empresa

We are a software development company that helps small and mid business to create/maintain great products to support their business. We are focused on Ruby on Rails and JavaScript and most of our clients are from North America and Europe. For this position you're gonna work on a company of the Silicon Valley.

We believe that code quality is extremely important to create a successful project in the long term and we value to craft beautiful UIs. We value a peaceful work environment and we don't expect developers to work more than 8 hours/day. Also, weekends are to have fun and to relax.

We are a remote-only company, so we expect you to feel comfortable to work from home/coworkings.

## Descrição da vaga

We are looking for a Senior JavaScript developer with good knowledge about React. On this project you will be part of a Silicon Valley startup that values awesome UIs. So you'll need to work and also suggest improvements on beatiful UIs. We expect from you to create a well organized React project following all the best practices from industry. If you have more questions about the job, feel free to reach us, we're welcome to answer your questions.

## Local

Remote

## Requisitos

**Obrigatórios:**
- JavaScript: 4+ years of experience
- CSS
- React: 3+ years of experience
- You need to be able to read and write in English

**Desejáveis:**
- Automated Tests

**Diferenciais:**
- Open Source contributor

## Contratação

PJ

## Como se candidatar

Please send an email to contact@ipanema.tech with your Github, Linkedin, and a brief description of you.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta:contact@ipanema.tech

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
