### ISSUE TITLE
[Goiânia] Front-End Developer na Neru - Serviços de Pagamento

### ISSUE THREAD

**Issue by gomescarlosjunior** [frontendbr/vagas#4009]
## Nossa empresa

Neru - Serviços de Pagamento Ltda

## Descrição da vaga

Estamos procurando profissionais que queiram aprimorar seus conhecimentos em Elixir desenvolvendo
tecnologias para meios de pagamento. Você irá trabalhar com os fundadores do projeto desenvolvendo APIs,
interfaces Web e integrações com serviços de parceiros.

## Local

Goiânia - PJ 

## Requisitos

**Obrigatórios:**
- Desenvolver, testar e documentar funcionalidades;
- Criar interfaces de acordo com as especificações de UX/UI;
- Identificar pontos de melhoria no código e na arquitetura para melhorar a experiência dos usuários;
- Colaborar com restante da equipe de desenvolvimento para entregar novos produtos;
- Colaborar e participar de treinamentos para difusão de boas práticas de desenvolvimento e estar aberto para
aprender novas tecnologias.

**Diferenciais:**
- Experiência prévia em Elixir, Ruby ou outra stack de desenvolvimento web moderna

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para contato@neru.com.br seu CV anexado - enviar no assunto: Desenvolvedor Web (Elixir, HTML, CSS e JS) | Pleno

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
