### ISSUE TITLE
[São Paulo] Front-End Developer - VAGA PREENCHIDA!

### ISSUE THREAD

**Issue by marcusvdm** [frontendbr/vagas#401]
## Descrição da vaga

Somos uma empresa de mídia digitais e estamos com uma oportunidade para Front-End Developer com experiência em responsivos, inclusive para emails mkt.

## Local

Escritório, São Paulo - Paraíso

## Requisitos

**Obrigatórios:**
- experiência com programação de emails mkt responsivos

## Contratação

PJ, pode ser MEI

## Nossa empresa

Agência I-Goal, empresa européia focada em mídias digitais.

## Como se candidatar

Por favor envie um email para martini@i-goal.com.br com seu CV anexado - enviar no assunto: Vaga Frontend

**Comment by XLucifer** [comment]
Seria apenas presencial?
Abraços

**Comment by vinirossi** [comment]
Ainda não trabalhei na área de front-end e ainda não mexi nessa parte de e-mail marketing. Estou disposto a aprender, posso me candidatar?

**Comment by marcusvdm** [comment]
Sim. Abs

Em 3 de jul de 2017 17:33, "André Luz da Silva" <notifications@github.com>
escreveu:

**Comment by marcusvdm** [comment]
Procuramos alguma experiência.

Obrigado

Em 4 de jul de 2017 13:18, "Vinicius Rossi da Silva" <
notifications@github.com> escreveu:

**Comment by budhelisson** [comment]
Enviei e-mail. o/

**Comment by marcusvdm** [comment]
Valeu Pessoal! Vaga preenchida.
