### ISSUE TITLE
[Goiânia] Front-end Developer Firebase/TypeScript na Neru

### ISSUE THREAD

**Issue by gomescarlosjunior** [frontendbr/vagas#4010]
## Nossa empresa

Neru - Serviços de Pagamento Ltda

## Descrição da vaga

Procuramos desenvolvedores para trabalhar no nosso projeto mobile criando integrações entre nosso time
mobile e nossa API utilizando a stack do Firebase. Você irá trabalhar com os fundadores do projeto e aprimorar
seus conhecimentos em bases de dados NoSQL, javascript e typescript.

## Local

Goiânia - PJ 

## Requisitos

**Obrigatórios:**
- Desenvolver, testar e documentar funcionalidades;
- Identificar pontos de melhoria no código para melhorar a experiência dos usuários;
- Colaborar com o restante da equipe de desenvolvimento para entregar novos produtos;
- Colaborar e participar de treinamentos para difusão de boas práticas de desenvolvimento e aprender novas
tecnologias.

**Diferenciais:**
- Experiência prévia em Angular, React ou outra Stack  Front-end;
- Conhecimento em Firebase ou algum banco de dados NoSQL;
- HTML, CSS e Typescript.

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para contato@neru.com.br com seu CV anexado - enviar no assunto: Desenvolvedor Web (Firebase / Typescript) | Pleno

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
