### ISSUE TITLE
[Marília-SP] Front-end Developer na Telecontrol

### ISSUE THREAD

**Issue by professorwaldir** [frontendbr/vagas#4011]
## Nossa empresa

Telecontrol líder de mercado em soluções para gestão de serviços em campo com clientes em mais de 17 países, grandes multinacionais, como Makita, Bosch, Midea Carrier.

## Descrição da vaga

Estamos contratando Dev Pleno/Senior frontEnd para desenvolvimento de aplicativo híbrido com Ionic.

## Local

Remoto ou Escritório, [SP], [Marília], [Fragata]

## Requisitos

**Obrigatórios:**
-  Experiência JavaScript,
-  Experiência em Ionic.
- Já ter desenvolvido aplicativos comerciais híbridos.

## Benefícios

- Plano de saúde
- VR 

## Contratação

CLT ou PJ a combinar

## Como se candidatar

Por favor envie um email para rh@telecontrol.com.br e waldir@telecontrol.com.br com seu CV anexado - enviar no assunto: Vaga IONIC

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
