### ISSUE TITLE
[Remoto] Senior Software Engineer - Front-end na Cloud Humans

### ISSUE THREAD

**Issue by ksetoue** [frontendbr/vagas#4014]
## Cloud Humans

Na cloud humans estamos mudando a forma como as pessoas trabalham e como as empresas constroem seus times de operações e vendas. Fazemos isso alinhando incentivos entre Cloud Pros (profissionais independentes) que desejam aprender e trabalhar com empresas que esperam alta qualidade nas entregas de resultados. 

Conheça mais em: [http://cloudhumans.com/ ](http://cloudhumans.com/ )

## Descrição da vaga

Somos uma startup em early stage, e estamos montando nosso primeiro squad de tecnologia. Você terá a chance de trabalhar junto com os fundadores consolidando processos, e ajudando a construir produtos que entreguem uma experiência excelente para os Cloud Pros e empresas clientes. 

Nosso objetivo é contratar um Senior Software Engineer que tenha se especializado em desenvolvimento front-end, que compartilhe nossa paixão pela missão da cloud humans, e esteja disposto(a) a nos ajudar a construir uma cultura de desenvolvimento saudável e inclusiva, valorizando excelência técnica e o mindset de crescimento. Planejamos contratar junior developers no futuro, fornecendo um ambiente onde eles tenham acesso a mentoria e todo o suporte necessário para se desenvolverem em suas carreiras.      

**Responsabilidades:**

- **Gerenciamento de processo e resultados:** arquitetar e implementar produtos, incluindo definições de requisitos e especificações da solução a ser desenvolvida, trabalhando em conjunto com os fundadores

- **Ciclo de desenvolvimento completo:** responsável por todo o ciclo de vida de desenvolvimento de uma fetaure, acompanhando o ciclo de desenvolvimento de aplicações e/ou produtos 
- **Time ágil:** definir entregas baseadas em uma cultura dinâmica de desenvolvimento ágil, utilizando scrum 
- **Set a high bar for the product:** utilizar boas práticas de desenvolvimento e documentação, garantindo que a  solução implementada e atende aos requisitos, entregando aplicações de alta qualidade  
- **Mentoria e cross-leadership:** Mentorar e ajudar developers menos experientes a se desenvolver na empresa

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 6+ anos de experiência em desenvolvimento de software
- Experiência prévia trabalhando em times que utilizam desenvolvimento ágil em startups, desenvolvendo aplicações complexas e que entregam valor para o cliente
- Sólido conhecimento em boas práticas, incluindo conhecimento acerca do ciclo completo de desenvolvimento (boas práticas de desenvolvimento, code review, git flow, testes, processos de desenvolvimento) 
- Experiência prévia se comunicando com usuários e gerentes para definir requisitos , definir features e implementações

**Desejáveis:**
- Habilidades analíticas e de resolução de problemas 
- Proficiente em Javascript ou Python
- Strong interpersonal and communication skills

## Benefícios

- Salário competitivo
- Plano de saúde e dentário
- Férias flexíveis
- Rotina Remote friendly 
- Possibilidade de obter stock options de uma das startups com rápido crescimento na América Latina 

## Contratação

PJ 

## Como se candidatar

Por favor se inscreva para a vaga pelo link: https://cloud-humans.breezy.hr/p/8dcbfac2a929

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: karoline.setoue@cloudhumans.com

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by evertonProgramadorCriativo** [comment]
Oi Gostaria de uma oportunidade de estagio remoto, evertonprogramadorcriativo@gmail.com

**Comment by pedro5655** [comment]
A vaga tem o label de estágio também, só que na descricao é apenas a vaga senior =/

**Comment by Marilzon** [comment]
o texto  "startup estágio inicial", acabou puxando flag de estagio 👍🏿

**Comment by pedro5655** [comment]
> o texto "startup estágio inicial", acabou puxando flag de estagio 👍🏿

Entendi amigo, falha minha, como pode ver, por isso estou procurando estágio haha. tmj

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by ksetoue** [comment]
Oi, ainda está aberta :)
