### ISSUE TITLE
[Belo Horizonte] Front-end Developer  Java/AEM na CI&T

### ISSUE THREAD

**Issue by anapr1** [frontendbr/vagas#4015]
> Vaga Remota durante a pandemia

## Nossa empresa
CI&T é o seu parceiro de transformação digital de ponta a ponta. Como um nativo digital, trazemos um histórico de 25 anos de aceleração do impacto nos negócios por meio de soluções digitais completas e escaláveis. Com uma presença global de 3.000 profissionais em estratégia, pesquisa, ciência de dados, design e engenharia, desbloqueamos um crescimento de primeira linha, melhoramos a experiência do cliente e impulsionamos a eficiência operacional.

## Descrição da vaga
Desenvolvedor Java conhecimento de AEM (Adobe Experience Manager)
Experiência com projetos de Web Content Management.

## Local
Exemplo: Remoto ou Escritório, [Minas Gerais, Belo Horizonte.

## Requisitos
**Obrigatórios:**
Experiência com projetos de Web Content Management (CMS)
Atuação com  framework Agile

**Desejáveis:**
Atuação com  framework Agile 
**Diferenciais:**
- Experiência com projetos de Web Content Management e atuação com  framework Agile

## Benefícios
- Plano de saúde
- Seguro de vida
- VR e VA
- Auxílio creche

**Diferenciais:**
Remuneração atrativa mais pacote de benefícios.

## Contratação
CLT

## Como se candidatar
Por favor envie um e-mail para anapr@ciandt.com  com seu CV anexado - enviar no assunto: Vaga Developer AEM

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.

#### Regime
- CLT

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
