### ISSUE TITLE
[remoto] Desenvolvedor(a) Front-End Pleno/Sênior Angular 2+ @ Supero

### ISSUE THREAD

**Issue by larissaaguiar** [frontendbr/vagas#4018]
Na Supero somos movidos por desafios, valorizamos a alta performance e quem pega junto com a equipe pra fazer acontecer! Estamos há 17 anos no mercado, realizando projetos personalizados de acordo com a necessidade de cada cliente. Nosso grande diferencial é trabalhar sempre com as melhores tecnologias e  um elevado nível de resolutividade. 
Buscamos um perfil #Supers para agregar ao time. Você busca evolução contínua? Está a procura de novos desafios? Então confere essa oportunidade!

O que você irá fazer:
Aqui você vai atuar junto com a equipe da APIPASS, que é uma plataforma de integração que coloca os diversos sistemas utilizados pelas empresas conversando entre si, permitindo automatizar todos os dados e processos de maneira simples, rápida e segura.  

Você irá atuar no desenvolvimento de solução construindo funcionalidades e componentes definidos com a equipe de desenvolvimento e implementar interfaces usando Angular. Além disso, irá atuar no desenvolvimento de novas funcionalidades da APIPASS e melhorar as já existentes.

Para isso, você precisa:

Graduação completa ou em andamento em Análise e Desenvolvimento de Sistemas ou áreas afins.
Conhecimentos em Angular 2+, HTML 5, JavaScript, CSS e TypeScript, RESTFul.
Será um diferencial se tiver:

Inglês intermediário;
Conhecimento dem Node.JS, serviços AWS e IPaaS.
O que oferecemos:

Ginástica Laboral;
Horários flexíveis;
Convênios e descontos;
Workchopps;
Treinamentos;
No dress code;
Programa indique um amigo;
Cultura que valoriza feedbacks e a diversidade;
Oportunidades profissionais a todo momento!

Eai? Quer ser um #Supers? Então corre e se inscreve ;)
Caniddate-se em: http://bit.ly/3nyH1MF

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
