### ISSUE TITLE
[Remoto] Front-end Developer na Extended Team

### ISSUE THREAD

**Issue by rafaelpaixao** [frontendbr/vagas#4019]
## Nossa empresa

Somos uma empresa de Vitória-ES, há 8 anos no mercado e com o DNA e modelo de trabalho baseado nas melhores empresas do Vale do Silício.

Estamos no meio de uma grande expansão e com a possibilidade de contratação Home Office e com salários acima do mercado.

## Descrição da vaga

Temos as seguintes vagas abertas no momento, todas com necessidade de inglês avançado:

Frontend React ou Angular
Fullstack Java e React/Angular
Fullstack Ruby on Rails e React

## Local

Remoto.

## Requisitos

**Obrigatórios:**
- Experiência em desenvolvimento de software nível pleno ou sênior;
- Inglês avançado;

## Benefícios

- Plano de saúde
- VR ou VA

**Diferenciais:**

- Autonomia
- Oportunidade de praticar o inglês

## Contratação

CLT.

## Como se candidatar

Telefone: +55 27 98836-6950 
Email: contact@extendedteam.com.br

Pode falar comigo pelo telegram: [@rafaelpaixao](https://t.me/rafaelpaixao).

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
