### ISSUE TITLE
[Porto Alegre] Full Stack Developer na Lighthouse

### ISSUE THREAD

**Issue by donnes** [frontendbr/vagas#402]
![cardfb](https://user-images.githubusercontent.com/9506146/27804768-12bdc1fa-6007-11e7-88ae-4e99b44e1597.png)

## Descrição da vaga

A [Lighthouse](http://www.lighthouseit.com.br) é uma empresa focada no desenvolvimento de aplicativos móveis e estamos com uma oportunidade para Full Stack Developer, pois além de Apps, também gostamos desenvolver outras coisa em casa, como APIs, Interfaces Web, etc.

## Local

Nossa empresa utiliza o espaço do Nós Coworking que se localiza no Shopping Total, em Porto Alegre.
Devido a isso, damos a possibilidade de trabalhar remoto quando necessário.
Shopping Total - Porto Alegre / RS

## Benefícios

- Espaço descontraído e com uma galera bem legal no Coworking
- Café a vontade
- Possibilidade de trabalhar remotamente quando necessário

## Requisitos

**Obrigatórios:**
- JavaScript(es5/es6)
- Nodejs
- React Native
- Git/Bitbucket
- Ter boa comunicação
- Praticar o "Deboísmo"

**Desejáveis:**
- Ionic2
- MongoDB
- Firebase
- MySQL

**Diferenciais:**
- Projetos Open Source

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para andre@lighthouseit.com.br com seu CV anexado - enviar no assunto: Vaga Full Stack Developer

**Comment by donnes** [comment]
@LFeh Por favor, adicionar as tags: PJ, Alocado, Remoto - Parcial, Pleno, Sênior. Obrigado!

**Comment by heruying** [comment]
Olá! Vocês por acaso não teriam nenhuma vaga de estágio por aí?
Terminei agora o primeiro semestre de ciência da computação na UFRGS.

**Comment by cescoferraro** [comment]
@donnes a vaga já foi preenchida?

**Comment by LFeh** [comment]
Aberto ainda?
