### ISSUE TITLE
[SP/BH/RJ/BAURU/REMOTO] Front-end Developer na Somos Educação

### ISSUE THREAD

**Issue by brnocorreia** [frontendbr/vagas#4020]
## Nossa empresa

A SOMOS Educação é o maior grupo de Educação Básica do Brasil e faz parte do Grupo Cogna Educação, que com mais de 50 anos de atuação, é uma das maiores empresas do setor de educação do mundo! Oferecemos um amplo portfólio de soluções educacionais como sistemas de ensino, editoras, além de uma tecnológica plataforma de aprendizado digital e de e-commerce. Nossa missão é transformar o ecossistema das escolas privadas, unindo educação e gestão de alta qualidade por meio da neurociência e tecnologia em larga escala, além de liderar as escolas no processo de transformação digital.

## Descrição da vaga

Estamos com oportunidades abertas para  Front-End Developer Sênior. As atividades principais contam com:

- Programação Front-End (SPA) que comunicam com API (Rest e GraphQL)
- Metodologias de Desenvolvimento Ágil
- Mobile First
- Componetização da biblioteca de Design System (React + Emoction + NPM/Yarn (9 aplicações usando os componentes) 

- Buscamos pessoas com propósito, proatividade, mão na massa e dispostas a crescer exponencialmente.

## Local

Remoto ou Escritório [São Paulo/SP, Belo Horizonte/MG, Rio de Janeiro/RJ ou Bauru/SP]

## Requisitos

**Obrigatórios:**
- Javascript (Vanilla)
- React
- HTML e CSS
- NPM (usamos para pacotes internos privados/públicos)

## Benefícios

- Vale Refeição
- Vale Transporte
- Assistência Médica
- Seguro de Vida
- Gympass
- PLR / Stock Options
- Incentivo educacional

## Contratação

CLT 

## Como se candidatar

Página com formulário de inscrição e todas as informações referentes a vaga e a empresa: https://byintera.in/1vl

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível

- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
