### ISSUE TITLE
[REMOTO] JavaScript Developer no DOT group 

### ISSUE THREAD

**Issue by gabriela-dot** [frontendbr/vagas#4021]
Somos o **DOT digital group** e a educação é o nosso negócio! Somos especialistas em **EdTech - Education Technology.** Aqui a tecnologia e a educação caminham juntas. A transformação que a educação promove é grande! Os nossos números e desafios também!

## Descrição da vaga

Precisamos de alguém que entenda muito de lógica e linguagens de programação. Alguém que conheça o comportamento da Web e seus padrões. 

**As principais atividades serão:**
- Desenvolver aplicações utilizando JavaScript em uma plataforma de mercado;
- Atuar na manutenção dos sistemas desenvolvidos;
- Atuar no desenvolvimento e definição de novas features;
- Propor e implementar melhorias nos processos e arquitetura da aplicação;
- Planejar, arquitetar, especificar e implementar soluções baseadas em tecnologia Web;
- Fazer análise, avaliação técnica e estimativa de esforço para desenvolvimento de soluções e funcionalidades;
- Codificar e realizar testes.

## Local de trabalho

100% Remoto
Escritório da empresa localizado em Florianópolis - SC 

## Requisitos da vaga

**Obrigatórios**
- Conhecimentos e experiência com JavaScript, atuação com front-end, GIT, SQL.

**Desejáveis**
- Conhecimentos em arquitetura de projetos e testes unitários. 

## Forma de contratação

PJ ou CLT

## Benefícios da empresa
- R$2.000,00 de verba para treinamento e desenvolvimento em 2021 + 40 horas ano para treinamento e desenvolvimento,
- Contratação Home Office
- Horário flexível,
- R$528,00 de VR/VA, você ajusta como preferir
- Convênio médico com cobertura nacional sem custo
- Convênio odontológico
- Convênio de farmácia
- Auxílio-pandemia R$100,00
- Remuneração alinhada com o mercado 
- Trabalhar com tecnologia de ponta e uma equipe maravilhosa com quem você vai ter a possibilidade de aprender e ensinar todos os dias ;) 

## Sobre a empresa

Com mais de 24 anos de atuação, somos um dos maiores grupos nacionais de educação digital e pioneiros no mercado de Educação Comunicacional no país. Possuímos sede em Florianópolis, polo tecnológico no estado de Santa Catarina, temos escritórios também em São Paulo e Brasília. No mercado internacional, temos operação em Lisboa, Portugal.

## Como se candidatar

Candidate-se diretamente em nosso site: https://dotgroup.enlizt.me/vagas/analista_desenvolvedor_javascript-170919
Ou envie um e-mail para gabriela.souza@dotgroup.com.br com seu CV anexado - Enviar no assunto: Vaga JavaScript - DOT

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 4 dias após cada etapa do processo.

## Labels

- CLT
- PJ
- Pleno

- Presencial
- Remoto
<!--- Informar abaixo o nome do estado por extenso.
- Brasil 
- Santa Catarina

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
