### ISSUE TITLE
[Remoto / RJ] NodeJS Developer na Clique Retire

### ISSUE THREAD

**Issue by xerminada** [frontendbr/vagas#4022]
## Clique Retire

Somos a Clique Retire, solução inovadora e disruptiva de autoatendimento: a tecnologia que chega para ajudar o varejo brasileiro a vender muito mais! A Clique Retire é uma Startup brasileira de tecnologia e logística que está revolucionando a logística no país agregando acesso a compras online a milhares de pessoas no país. Temos uma plataforma responsável por gerenciar as operações de logística integrada as principais plataformas de E-commerce e Marketplace do mercado.

Prezamos sempre pela experiência dos nossos usuários e somos focados em oferecer sempre aos nossos clientes e usuários engajados em entregar soluções que modifiquem a forma com que eles pensam e fazem logística no seu dia-a-dia.

Estamos à procura de um novo #CLICKER para nos auxiliar na integração com os principais sites e plataformas de e-commerce do país.

## Descrição da vaga

- Trabalhar com uma arquitetura moderna de micro-serviços usando tecnologias como Node.js, Lambda, Typescript, MongoDB, NoSQL, Serverless;
- Participar de um time ágil, comprometido com qualidade, eficiência na automatização de processos, robustez, escalabilidade e performance dos nossos sistemas;
- Implementar integrações RestFul API entre nossa plataforma e nossos clientes e parceiros;
- Documentar APIs seguindo as boas práticas de documentação;
- Desenvolver interfaces e dashboards Web com agilidade utilizando frameworks como bootstrap, ionic, angular e vuejs;
- Atuar de maneira consultiva entendendo as necessidades dos clientes e replicando na nossa plataforma;
- Realizar testes que garantam o bom funcionamento e desempenho das features desenvolvidas;
- Identificar melhorias na usabilidade do nosso produto e na condução dos nossos processos e reportar aos Times de Produto e Tecnologia.

## Local

Remoto / RJ

## Requisitos

**Obrigatórios:**
- Javascript
- HTML / CSS
- 3 anos de experiência com projetos envolvendo NodeJS 
- Experiência em arquiteturas de microserviços
- Lambda
- NoSQL
- AWS Cloud Services
- Programação funcional
- Elaboração de TDD
- Boas práticas de programação e documentação;
- Graduação completa em Análise e Desenvolvimento de Sistemas, Ciência da Computação; Sistema de Informação ou áreas correlatas;

**Desejáveis:**
- Serverless
- Metodologias ágeis de desenvolvimento;
- Boa comunicação e empatia, afinal você fará parte de um time;

**Diferenciais:**
- Inglês Fluente;
- Experiência com desenvolvimento para plataformas de e-Commerce
- Experiência com ERP, WMS e/ou TMS;

## Benefícios

- Plano de saúde
- TR Sodexo

**Diferenciais:**
- Trabalhar em uma startup que agrega valor a milhares de pessoas
- Ter a visibilidade e reconhecimento pelo seu trabalho
- Aprendizado e desenvolvimento pessoal com tecnologias de ponta no mercado
- Estar inserido no mercado de e-commerce e logística que cresceu mais de 70% no último ano

## Contratação

CLT

## Como se candidatar

Por favor envie um email para ti@cliqueretire.com.br com seu CV anexado - enviar no assunto: Vaga NodeJS

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: contato@cliqueretire.com.br

#### Alocação
- Remoto
- Eventuais encontros presenciais no RJ e SP

#### Regime
- CLT
 
#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
