### ISSUE TITLE
[Remoto] Front-end Developer *Freelancer na HomeHub 

### ISSUE THREAD

**Issue by Startec-Jobs** [frontendbr/vagas#4023]
## Nossa empresa

A HomeHub veio para revolucionar o mercado imobiliário do Rio de Janeiro e no Brasil. Com anos de experiência nesse mercado tradicional, os sócios Fred, Vagner e Rodolfo decidiram, em 2018, montar um modelo de negócio digital que pudesse resolver os grandes problemas de proprietários de imóveis, clientes e corretores nessa experiência tão dolorosa que é vender e comprar imóveis.

“Aqui na HomeHub, nós acreditamos que profissionais de ponta, munidos de ferramentas tecnológicas, terão um papel de protagonismo no mercado imobiliário, tornando a experiência de cada cliente única!”

Em um formato de franquia, a HomeHub facilita a vida de corretores autônomos e offices no mercado imobiliário por meio da tecnologia. Ferramentas como o comparador de imóveis, algoritmo de relevância e análise prévia da documentação permitem uma experiência mais fluida no processo de compra e venda.

Hoje, a HomeHub está expandindo seu time de tecnologia para incrementar cada vez mais funcionalidades ao seu produto. Com um time enxuto de 11 pessoas, sendo 4 no time de tecnologia, estão buscando profissionais com muita vontade de aprendizado e capacidade de crescimento, tornando-se dono do negócio.

homehub.com.br/

## Descrição da vaga

A HomeHub está com vaga aberta para Front-End Developer! Buscamos pessoa desenvolvedora front-end para trabalhar como freelancer na startup que veio para mudar a forma com que se vende e compra imóveis.
 
Com horários flexíveis e a remuneração proporcional as entregas feitas no período acordado (sprint), a vaga não exige exclusividade. Ou seja, você não precisa sair do seu emprego atual para contribuir com o time da HomeHub, sendo uma opção complementar de renda.
 
**Perfil desejado:**
Proatividade
Trabalho em equipe
Busca por aprendizados constante

## Local

Remoto

## Requisitos

**Obrigatórios:**
Experiência de 3 anos ou mais com desenvolvimento em React
Alto conhecimento em Git, HTML5 e CSS3

**Desejáveis:**
Conhecimentos em Redux, RESTful, CI e Bitbucket
Conhecimento em Teste de software
Conhecimento em metodologias ágeis

## Contratação

PJ (Freelancer)

## Como se candidatar

Através do link https://bit.ly/HomeHub-DevFront-inscricao

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: suporte@startecexp.com

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Sênior

**Comment by djalmajr** [comment]
O link não está funcionando

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
