### ISSUE TITLE
[Porto Alegre] React Developer na DBServer

### ISSUE THREAD

**Issue by AlineSchorn** [frontendbr/vagas#4024]
A DBServer é uma Softwarehouse gaúcha que constrói entregas sob medida. Há 27 anos trabalhamos com foco nas pessoas, guiados por nossos valores, crescendo lado a lado com nossos colaboradores. Nosso lema é fazer a coisa certa do jeito certo através do design e do build.

Nos últimos anos, iniciamos uma caminhada em direção a diversidade e a inclusão e após o lançamento do nosso Marco Ético temos agora um norteador dos princípios que irão trilhar a nossa trajetória.

Estamos orgulhosos de promover um ambiente de trabalho livre de discriminação. Acreditamos que a diversidade de experiências, perspectivas e histórico transforma nosso ambiente de trabalho. Estamos empenhados a construir esse legado com a sua parceria!

Conheça nosso Marco ético: http://www.dbserver.com.br/marcoetico/

**Descrição da vaga:**

O que vamos construir juntos?

Nessa posição, você trabalhará conosco em uma grande conta do segmento financeiro. Nosso cliente trabalha fortemente com agilidade, e nesse projeto você nos auxiliará nas demandas relacionadas ao time de infraestrutura, pensando nas melhores soluções voltadas a arquitetura de software.

Nos ajude a desenhar a solução!

Se você chegou até aqui e é uma Pessoa Desenvolvedora que manja de React e que gosta muito de estar conectada com práticas de arquitetura, tem curiosidade intelectual e está sempre em busca das melhores soluções, essa vaga é para você! Você está muito próximo de fazer parte desse time!

**Local:**
Porto Alegre - RS

**Requisitos:**
Requisitos para se candidatar a vaga:

Experiência em ReactJs
Conhecimento em JavaScript
Conhecimento em Conheicmento em TypeScript
Conhecimento emHTML
Conhecimento emCSS
Conhecimento emJest para testes unitários
Será legal se você tiver vivência em:

Metodologias ágeis

**Benefícios:**
- Plano de saúde
- Seguro de vida
- Vale Refeição
- Plano Odontológico

**Diferenciais:**
- horários flexíveis
- ambiente diverso
- troca de conhecimento
- oportunidade de aprender muito \o/
- Contratação
- CLT

**Como se candidatar:**
Você pode se candidatar através do seguinte link:
https://jobs.kenoby.com/dbserver/job/dev-react-segmento-financeiro/5fdba299943f0c1a6484b21c?utm_source=website
Ou nos enviar um email para poa_selecão@dbserver.com.br com seu CV anexado

**Tempo médio de feedbacks:**
Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: poa_seleção@dbserver.com.br

Labels
Alocação
Alocado

**Regime:**
CLT

**Nível:**
Pleno
Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
