### ISSUE TITLE
[SÃO PAULO] Desenvolvedor NodeJS full-stack Senior Remoto.@DIGI

### ISSUE THREAD

**Issue by BarbaraOgoshi** [frontendbr/vagas#4025]
Descrição da vaga
Desenvolvimentos de plataforma digitais para grandes clientes.

Local
Remoto, São Paulo

Benefícios
Recesso Remunerado
Day-off aniversário
Zenklub

Requisitos Obrigatórios:
Organização, disciplina trabalho em equipe, pontualidade, planejamento, espírito de liderança, precisão em estimativas e entregas são essenciais para essa vaga.

Sólidos conhecimentos em:
- NodeJS
- Typescript 
- MongoDB
- React e React Hooks
- GIT
Experiência com GraphQL é um plus.

Contratação
PJ a combinar

Nossa empresa
Somos uma agencia de publicidade localizada na Faria Lima e atuamos com campanhas de incentivo. Buscamos um profissional para atuar em nosso time de Tecnologia no cargo de Desenvolvedor NodeJS full-stack Sênior

Como se candidatar
Por favor envie um e-mail para barbara@grupodigi.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor NodeJS full-stack.

Labels
🏢 Flexível
🏢 Remoto
👴 Sênior
⚖️ A-Combinar
⚖️ PJ
💰 10k-11k

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
