### ISSUE TITLE
[São Paulo - Centro] Front-end Angular Developer Pl. 

### ISSUE THREAD

**Issue by Riyuzo** [frontendbr/vagas#4026]
Pessoal, boa noite! Me chamo Rodrigo e trabalho para uma consultoria chamada Headhunters.io. Estamos assessorando uma multinacional francesa e infelizmente, não podemos fazer a divulgação documentada da bandeira por limitações de contrato, mas aqueles com quem eu entrar em contato **terão essa informação**. Entendo que isso não seja atrativo e adoraria poder divulgar, seria metade do meu trabalho feito, pois é uma empresa que se vende sozinha, mas se eu puder contar com sua compreensão, peço que leia até o final antes de decidir pular esta oportunidade.

> Vaga Remota durante a pandemia, após, 2 dias home 3 presencial

## Nossa empresa

Multinacional francesa de #TI que está entre os maiores fornecedores de serviços de consultoria, tecnologia e outsourcing do mundo!

**10 razões para se trabalhar nesta empresa:**

1. Seus valores são os nossos valores - Somos guiados por sete valores principais: honestidade, audácia, confiança, liberdade, espírito de equipe, modéstia e fun. Se você compartilha dos mesmos valores, aqui é o seu lugar.
2. Pessoas em primeiro lugar - Em nosso trabalho, incentivamos a troca de ideias, o respeito às diferenças e o bem-estar no ambiente de trabalho.
3. Nunca pare de aprender - Na Universidade corporativa, você aprenderá por meio de cursos presenciais e virtuais,  módulos de e-learning e recursos ricos de mídia on-line.
4. Sinta-se livre para crescer - Suas metas podem mudar ao longo de sua carreira. Você quer mudar de foco? Seguir outro caminho? Estamos aqui para ajudar.
5. Inspire-se em seus colegas - Nossa diversidade cultural permite que você sempre tenha algo para aprender com aqueles a sua volta.
6. Esqueça o que você entende por “dia comum” - O desafio e a variedade são constantes aqui. Desde o trabalho que você faz, até as pessoas que você conhece e os lugares para onde você viaja. Nós te mantemos preparado para tudo isso.
7. Encontre o equilíbrio ideal para você - Você é humano – e nós também! Fazemos o máximo para que os nossos funcionários alcancem o equilíbrio de uma vida profissional saudável e feliz.
8. Conte conosco para desenvolver sua carreira - Estamos sempre crescendo e você deve fazer o mesmo. Priorizamos o desenvolvimento pessoal dos membros da nossa equipe, com a Universidade corporativa.
9. Prazer em viajar - Temos 300 escritórios em 40 países no mundo inteiro. Você terá a chance de viajar ou trabalhar em diferentes lugares.
10. Desafios positivos  - Seja recém-formado ou profissional experiente, aqui você trabalha em projetos desafiadores desde o primeiro dia.

## Descrição da vaga

NET FRONT-END: Framework Front-end angular;
Ferramenta de versionamento - GIT;
Type Script e Java Script;
Experiência em HTML, JSON, CSS, JAVA SCRIPT, avançados;
Sass, SCSS;
Custom Components;
Interface para Mobile (responsive, adaptativo, user behaviour etc.)
Conhecimento em back-end.

## Local

São Paulo - SP região central - inicialmente remoto, após pandemia, 2 dias home e 3 presencial.

## Requisitos

Foco, que busca novos desafios e tenha flexibilidade em questão de linguagens de programação; comprometido com a entrega.
Trilha de desenvolvimento: Consultor III, IV e, após isso, escolhe entre virar um Especialista/Arquiteto ou seguir a área de Coordenação.

## Benefícios

Assistência Médica;
Assistência odontológica;
Auxílio creche/Babá;
Bolsa/desconto de estudos para idiomas;
Horário flexível;
Previdência privada;
Vale-refeição;
Vale-transporte; 
Seguro de Vida;

## Contratação

CLT

## Como se candidatar

Por gentileza encaminhar CV para rrm.psi@gmail.com com o título da vaga no anúncio. Aproveito para deixar o link de divulgação, sintam-se à vontade para me adicionar lá no IN
[https://www.linkedin.com/posts/psicologorodrigomaruyama_consultor-frontend-angular-pl-activity-6745778244135505922-p5WI](url)

## Tempo médio de feedbacks

O processo se encerra comigo dia 29/12/2020 nesse período terei todos os profissionais já cadastrados em nossa plataforma que também é por onde nossos cliente realizam a gestão dos próprios processos, ou seja, temos muitas vezes atualizações e feedbacks de aderência em tempo real. Após essa data, ele migra automaticamente para as mãos do cliente que fará o contato direto para as etapas ou feedbacks finais, mas pode acontecer disso nos ser solicitado. Ainda que o processo final não seja conduzido por mim, faço questão de acompanhar TODOS os profissionais que ficam sob meus cuidados, pelo sim ou pelo não. Gosto de dar devolutivas consultivas, não existe ficar sem retornos no meu processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Faixa de remuneração 6,5k

https://user-images.githubusercontent.com/76498502/102948578-f6bf7580-44a4-11eb-88d6-ca8f6330b5cf.mp4

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
