### ISSUE TITLE
[Belo Horizonte/MG] Front-end Developer Angular/NodeJs no Beduka

### ISSUE THREAD

**Issue by beduka-code** [frontendbr/vagas#4027]
## Nossa empresa

Quer fazer parte de uma empresa jovem, com foco em inovação, e que não para de crescer? Venha para o Beduka!⁣
⁣
Nós ajudamos mais de 1 milhão de estudantes por mês a dominarem os conteúdos e se prepararem para o ENEM e vestibulares, por meio de nossa plataforma que reúne testes vocacionais, artigos com matérias, os melhores exercícios, planos de estudo, simulados do ENEM e um buscador que permite pesquisar cursos e instituições públicas e privadas.⁣

## Descrição da vaga

Procuramos por um desenvolvedor Angular/ Nodejs que seja criativo, determinado e que deseje alavancar ainda mais o nosso sucesso com as suas habilidades.
⁣
## Desafios:
•Atuar no desenvolvimento de aplicações Angular e NodeJS fazendo uso de padrões e boas práticas de programação. ⁣
•Análise demandas e propor soluções técnicas adequadas codificar a partir de documento de especificação realizar manutenções corretivas e evolutivas dos aplicativos existentes e realizar testes. ⁣

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Angular 6+
- Typescript 
- Banco de Dados (MySQL e MongoDB) 
- API Rest/Json
- NodeJS 

**Desejáveis:**
- conhecimentos em ReactJs
- conhecimentos em ElasticSearch
- formação em Ciência da Computação, Engenharia da Computação, Sistemas de Informação ou similares. 

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um email para rh@beduka.com com seu CV anexado - enviar no assunto: Vaga Angular/NodeJS

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@beduka.com

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by beduka-code** [comment]
.
