### ISSUE TITLE
[São Paulo] - Front-End Developer (Hybrid Mobile App)

### ISSUE THREAD

**Issue by kadurodrigues** [frontendbr/vagas#403]
## Descrição da vaga
 
Buscamos um Front-End de nível pleno / sênior que atue principalmente no desenvolvimento de aplicações mobile híbridas (Ionic/Phonegap).

## Local

Região da Vila Olímpia

## Requisitos
- HTML5
- CSS3
- SASS
- Frameworks CSS (Bootstrap, etc...)
- JavaScript
- Phonegap e Ionic Framework
- Experiência com Frameworks SPA (AngularJS)
- Integração com Web Services API RESTful

**Desejáveis:**
- UI / UX Design (Criação de layouts e protótipos, WEB e Mobile)
- ES6 / Typescript

## Contratação

PJ 

## Nossa empresa

A TalentFour é uma empresa de consultoria de TI com foco maior nos processos de Desenvolvimento de Software, Governança, Segurança da Informação, Infraestrutura (TI e Telecom),
Suporte Técnico e Operação.

## Como se candidatar

Por favor envie um email para safira.santana@talentfour.com.br com seu CV anexado - enviar no assunto: Vaga Front-End Developer

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by kadurodrigues** [comment]
Vaga preenchida, Valeu mano!
