### ISSUE TITLE
[Remoto] Front-end Developer na Wa Project

### ISSUE THREAD

**Issue by AliciaMalvez** [frontendbr/vagas#4032]
## Nossa empresa

Somos uma software house especializada em desenvolvimento de sistemas para empresas, tendo como filosofia entregas ágeis, orçamentos compatíveis e proximidade com o cliente.

## Descrição da vaga

Desenvolvedor(a) Full Stack - C# / React Sênior

Hard Skill
C#;
HTML; 
CSS; 
JavaScript; 
React
.Net Core;

**Diferenciais:**
Asp.Net; 
WebForms; 
API Rest; 
Jquery; 
Postgres.

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para vagas@waproject.com.br com seu CV anexado - enviar no assunto: Vaga C#

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
