### ISSUE TITLE
[Remoto] Front-End Tech Lead na Dell

### ISSUE THREAD

**Issue by jokapoa** [frontendbr/vagas#4033]
## Contratante

Empresa internacional de tecnologia

## Descrição da vaga

Acompanhar os desenvolvedores menos experientes e interagir com as áreas de negócio para buscar as melhores soluções conforme as necessidades para o olhar de front-end dos projetos.

Interagir com as demais equipes de backend e sistemas para prototipar as melhores soluções

Criar aplicações otimizadas e responsivas utilizando Angular 8+, CSS, SASS, HTML, JavaScript / Typescript;

Manter um alto padrão de qualidade de código e arquitetura de suas aplicações.

Garantir o correto funcionamento em diferentes navegadores e dispositivos;

Criar mockups e protótipos de qualidade.
## Local
Remoto 

## Requisitos

**Obrigatórios:**
Bom relacionamento e trabalho em equipe;

Domínio completo de Javascript,, Typescript  CSS, SASS, HTML, react ou angular

Inglês: conversação é imprescindviel

Boas noções de design e usabilidade;

Ampla experiência com desenvolvimento Front-End;

Conhecimento em arquiteturas baseadas em APIs Restfull;

Experiência com versionamento GIT, Docker, DEVOPS.

Desejável  conhecimentos em Azure Cloud/Devops

**Desejáveis:**
- conhecimentos em C#

**Diferenciais:**
- projetos internacionais

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ 27
-  PLR
- ...

 ...

## Contratação

CLT a  combinar

## Como se candidatar

Por favor envie um email para frontend@holdenrh.com.br com seu CV anexado 

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Especialista / Líder Técnico

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
