### ISSUE TITLE
[Remoto] Front-end Developer (Pleno / Sênior) na Cheap2ship

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#4035]
## Descrição da vaga: 
 <p>Buscamos uma <strong>Pessoa Desenvolvedora Front-end</strong>.</p>

## Cheap2ship: 
 <p>Plataforma que atua com negociação de fretes nacionais e internacionais.</p>
</p>

 ## Habilidades: 
 - API 
- PostgreSQL 
- Typescript 
- Vue.js 
- GraphQL 
- Material-UI
## Local: 
 100% Remoto
## Requisitos: 
 - Mínimo de 5 anos na área de desenvolvimento 
- Conhecimentos em Vue.js 
- Fluente em javascript ou Typescript

## Benefícios: 
 - Salário competitivo
## Como se candidatar:
Candidate-se em: [Desenvolvedor(a) Front-end (Pleno / Sênior) na Cheap2ship](https://coodesh.com/vagas/desenvolvedor-pleno-senior-front-end-173212?origin=github&modal=open)
## Tempo médio de feedbacks:
 Costumamos enviar feedbacks em até 48 horas após cada etapa do processo. E-mail para contato em caso de não haver resposta: [jociano@cheap2ship.com](mailto:jociano@cheap2ship.com)
#### Alocação
Remoto
#### Regime
PJ
#### Nível
Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
