### ISSUE TITLE
[REMOTA] Fullstack Developer na Certsys Tecnologia da Informação

### ISSUE THREAD

**Issue by ItalaTechRecruiter** [frontendbr/vagas#4037]
## **Certsys Tecnologia da Informação**

Eleita como uma das 100 empresas mais promissoras do mundo em implementação de soluções baseadas em tecnologia IBM, a Certsys atua fortemente na Transformação Digital das empresas, liderando grandes mudanças através de tecnologias inovadoras. 

## **Descrição da vaga**

Desenvolvimento de chatbots para o Labs, célula de Inovação da Certsys com as tecnologias: JavaScript, React e Node.js. 

## **Local**

Remoto (Escritório fica em São Paulo - SP, para quem é da região poderá ir ao escritório)

## **Requisitos**

**Obrigatórios:**
Experiência de 3 a 4 anos com as tecnologias: 
- JavaScript, React e Node.js. 
- Bom nível de inglês

**Desejáveis:**
- Conhecimentos em IBM Watson

**Diferenciais:**
- Conhecimento e experiência com DevOps e times ágeis e/ou Kanban e com user stories

## **Benefícios**

- Seguro de vida
- 15 dias de férias remuneradas
- Parcerias para cursos e certificados

## **Contratação**

PJ a combinar

## **Como se candidatar**

Por favor envie um email para itala.santos@certsys.com.br com seu CV anexado - enviar no assunto: Vaga Dev. Fullstack

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: itala.santos@certsys.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
