### ISSUE TITLE
[Remoto] Front-end Developer na Fácil Sistemas

### ISSUE THREAD

**Issue by Startec-Jobs** [frontendbr/vagas#4043]
## Nossa empresa

A Fácil Sistemas é especializada no desenvolvimento de soluções tecnológicas para a Gestão de empresas de médio e pequeno porte do comércio. Criam produtos para serem utilizados por pessoas de todos os níveis hierárquicos dentro das organizações. 

“Somos motivados a resolver os problemas dos clientes através de soluções que facilitem o dia a dia da Gestão.”

Fundada em 2006, a Fácil Sistemas é uma empresa compromissada com qualidade e respeito, e acima de tudo humana, pois trás desde sua origem a valorização do ser humano, e consideram isto seu diferencial.  Existem para contribuir para o desenvolvimento e crescimento das empresas. 

Hoje, com mais de 7000 usuários e um Índice de Satisfação de 92%, querem atuar em nível nacional, sendo reconhecida como a melhor opção por clientes, consultores, parceiros e colaboradores, pela qualidade de nossos produtos, serviços e relacionamento.

Valores com os quais caminham: 

Colaboração
Comprometimento
Responsabilidade
Empatia
Relacionamento
Melhoria Contínua
Sustentabilidade
Inovação Tecnológica
Responsabilidade Social
facilsistemas.com.br/

## Descrição da vaga

A Fácil Sistemas está com vaga aberta para Front-End Developer! 

“Como integrante do time de desenvolvimento da Fácil, você poderá contar com um ambiente onde a autonomia, criatividade e a coragem são bastante estimuladas. Aprendemos juntos e não abrimos mão das boas práticas de desenvolvimento de software. Procuramos pessoas que gostam de aprender coisas novas e que amam o que fazem!” 

Conheça mais sobre a oportunidade:

Atividades da vaga:

Trabalhará em uma equipe multidisciplinar com desenvolvedores Full Stack, UX e QA na construção de uma nova geração de ERP da Fácil
Desenvolverá também outros serviços para a gestão e automação do varejo em geral
Trabalhará em um ambiente que valoriza as boas práticas de programação e utiliza de metodologia ágil para gerenciamento
Perfil desejado:

Iniciativa e colaboração em equipe
Flexibilidade
Comunicação
Autogestão e auto-organização do trabalho

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Amplo conhecimento em JavaScript, Angular, HTML5 e CSS3/SASS

**Desejáveis:**
- Conhecimento de testes automatizados, AWS, Webservice RESTful e Git
- Experiência com componentização de interfaces (de preferência para múltiplas aplicações) 
- Conhecimento em React

## Benefícios

Remuneração: R$ 3.000,00 a R$ 4.000,00
Plano Odontológico
Vale Alimentação
Seguro de Vida
Horário Flexível
Home Office
Day off no aniversário

## Contratação

CLT

## Como se candidatar

Através do link http://bit.ly/Facil-Dev-Front-inscricao

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 20 dias após cada processo.
E-mail para contato em caso de não haver resposta: suporte@startecexp.com

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior

**Comment by FernandoGreco** [comment]
Em requisitos obrigatórios pede angular, quando fui me candidatar pergunta sobre React, bom como sei só Angular decidi não me candidatar.

**Comment by rodrigoantas** [comment]
ainda está aberto? faz 3 dias que foi postado mas o link pra se candidatar parece não funcionar.

**Comment by Startec-Jobs** [comment]
> ainda está aberto? faz 3 dias que foi postado mas o link pra se candidatar parece não funcionar.

Fechamos as inscrições ontem no fim da tarde, Rodrigo. Agradeço o interesse, irei fechar a vaga aqui!
