### ISSUE TITLE
[São Paulo] JavaScript Developer na idwall

### ISSUE THREAD

**Issue by mjnr** [frontendbr/vagas#4044]
> Vaga Remota durante a pandemia

## Nossa empresa

Acreditamos que tecnologia tem o poder de mudar o mundo e fortalecer as relações de confiança. Por aqui, respiramos inovação em nosso dia a dia e sabemos que diferentes pontos de vista enriquecem os nossos produtos, agregando mais valor às soluções que desenvolvemos para resolver os desafios de identidade dos nossos clientes.

Também incentivamos um ambiente onde todas as pessoas têm autonomia e compartilham livremente as suas ideias, pois essa é a chave para o nosso crescimento. Se você procura um lugar para crescer exponencialmente e deseja ajudar a construir conexões mais transparentes entre pessoas e empresas #VemSERidwaller

## Descrição da vaga

Você vai atuar em um ambiente de squads autônomas responsáveis por todo o processo de desenvolvimento e release de software e assim garantir que os projetos estão em conformidade com as metodologias que utilizamos, entendendo e trabalhando a melhoria do nosso produto no dia a dia, colaborando com a evolução da plataforma através de novas ideias, novos pontos de vista e assim elaborar novas funcionalidades que brilhem os olhos dos nossos usuários;

Além disso, você vai desenvolver APIs públicas e privadas, em uma arquitetura escalável de microserviços, desenvolver contextos de regras de negócio nos backends das aplicações e garantir que os projetos estão em conformidade com as boas práticas e convenções internas principalmente relacionadas a qualidade e segurança.

## Local

Atualmente estamos todes de home office, mas para você saber nossa localização ficamos na Rua Haddock Lobo, 595, no prédio da BandTec, bem pertinho do metrô Consolação, só 120 metros.

## Requisitos

**Obrigatórios:**
- Ter um mindset colaborativo, pensando na qualidade, segurança, desempenho, escalabilidade e seus impactos nos releases;
- Ter experiência com desenvolvimento Node (TypeScript) e Java em plataformas escaláveis e distribuídas.
- Experiência em testes automatizados - unitários, integrados, funcionais e instrumentados;
- Domínio de ferramentas de versionamento (git) e processos de CI/CD;
- Familiaridade com ambientes de Cloud Computing - AWS e Google Cloud;
- Conhecimento de banco de dados relacionais a não relacionais, frameworks MVC (Springboot ou Dropwizardd), autenticação utilizando Token Based Authentication (JWT) e arquitetura orientada a microsserviços e APIs RESTful.

**Desejáveis:**
- Conhecer orquestração de containers;
- Tiver experiência com ferramentas de Continuous Integration, Delivery e Deploy;
- Conhecer os padrões OAuthe e OpenId Connect, além de conhecimento em TDD;
- Tiver atuado com metodologias ágeis - Kanban, Scrum e XP.

## Benefícios

- Vale Refeição de R$710,00/mês;
- Vale Alimentação de R$ 300,00/mês;
- Vale Transporte (opcional com desconto de 6% em folha);
- Para nós, o bem estar mental dos idwallers é muito importante, por isso temos o ZenKlub para você fazer terapia ou coaching 1x por semana com custo zero;
- Gympass para manter a saúde mental e física em dia;
- Auxílio creche (para filhos de 0 a 5 anos) no valor de R$ 412,50;
- Plano de Saúde e Odontológico; 
- Seguro de Vida.

## Contratação
CLT

**Diferenciais:**
Para a idwall cultura é tudo o que pode ser ensinado e transmitido. São as histórias que vivemos e o que compartilhamos. É a nossa forma de fazer, de criar e principalmente de acreditar. Para que isso sempre aconteça, somos guiados pelos nossos valores: Confiança, Coragem, Felicidade, Colaboração, Diversidade, Fazer Acontecer, eles estão com a gente todos os dias em cada oportunidade que temos de vivenciá-los.

Também temos nossos rituais, que amamos demais:

Reunião do Conhecimento semanalmente, nossos idwallers compartilham e debatem livremente um assunto que conhecem, pode ser de qualquer tema.

Celebration Breakfast, a cada 2 semanas, nos reunimos e cada time apresenta os acontecimentos, aprendizados e dificuldades das últimas semanas e os próximos projetos.

Idlabs, logo após o Celebration, nas sextas-feiras, nos dedicamos a trabalhar em projetos que estimulam o empreendedorismo interno e o trabalho multidisciplinar.

## Como se candidatar
Candidate-se **[aqui](https://jobs.kenoby.com/idwall/job/pessoa-de-engenharia-de-software-javascript/5fa2e952d8ff926fcf87db3d?utm_source=website)**

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: gabriela.luna@idwall.co

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by victorhsantiago** [comment]
Olá, está vaga é para dev back-end, aqui as vagas são focadas para frontend/fullstack.

Acredito que você terá mais sucesso se divulgar sua vaga [aqui](https://github.com/backend-br/vagas).

CC.: @felipefialho

**Comment by felipefialho** [comment]
Oi @victorhsantiago essa vaga tem um perfil mais Backend mas focada em JavaScript, acho super tranquila estar aqui 😊

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
