### ISSUE TITLE
[São Paulo] - Front-end Developer na idwall [Exclusiva para Mulheres]

### ISSUE THREAD

**Issue by mjnr** [frontendbr/vagas#4045]
> Vaga Remota durante a pandemia

## Nossa empresa

Acreditamos que tecnologia tem o poder de mudar o mundo e fortalecer as relações de confiança. Por aqui, respiramos inovação em nosso dia a dia e sabemos que diferentes pontos de vista enriquecem os nossos produtos, agregando mais valor às soluções que desenvolvemos para resolver os desafios de identidade dos nossos clientes.

Também incentivamos um ambiente onde todas as pessoas têm autonomia e compartilham livremente as suas ideias, pois essa é a chave para o nosso crescimento. Se você procura um lugar para crescer exponencialmente e deseja ajudar a construir conexões mais transparentes entre pessoas e empresas #VemSERidwaller

## Descrição da vaga

Você vai atuar em um ambiente de squads autônomas responsáveis por ajudar a construir novas iniciativas e manter nossas aplicações web para clientes internos e externos. No seu dia a dia você vai produzir códigos robustos escaláveis e contribuir para a evolução da nossa plataforma através de novas ideias. Também vai elaborar novas funcionalidades que brilhem os olhos dos nossos usuários garantindo que os projetos estão em conformidade com as boas práticas e convenções internas principalmente relacionadas a qualidade e segurança.

## Local

Atualmente estamos todes de home office, mas para você saber nossa localização ficamos na Rua Haddock Lobo, 595, no prédio da BandTec, bem pertinho do metrô Consolação, só 120 metros.

## Requisitos

**Obrigatórios:**
- Ter um mindset colaborativo, pensando na qualidade, segurança, desempenho, escalabilidade e seus impactos nos releases;
- Ter experiência com desenvolvimento de webapps client/server-side utilizando React, saber desenvolver componentes visuais utilizando boas práticas de UI/UX dialogando com nosso time de Designers de produto e contribuindo com a evolução do nosso Design System.

**Desejáveis:**
- Experiência com times multidisciplinares
- Tiver atuado com metodologias ágeis.

## Benefícios

- Vale Refeição de R$710,00/mês;
- Vale Alimentação de R$ 300,00/mês;
- Vale Transporte (opcional com desconto de 6% em folha);
- Para nós, o bem estar mental dos idwallers é muito importante, por isso temos o ZenKlub para você fazer terapia ou coaching 1x por semana com custo zero;
- Gympass para manter a saúde mental e física em dia;
- Auxílio creche (para filhos de 0 a 5 anos) no valor de R$ 412,50;
- Plano de Saúde e Odontológico; 
- Seguro de Vida.

**Diferenciais:**
Para a idwall cultura é tudo o que pode ser ensinado e transmitido. São as histórias que vivemos e o que compartilhamos. É a nossa forma de fazer, de criar e principalmente de acreditar. Para que isso sempre aconteça, somos guiados pelos nossos valores: Confiança, Coragem, Felicidade, Colaboração, Diversidade, Fazer Acontecer, eles estão com a gente todos os dias em cada oportunidade que temos de vivenciá-los.

Também temos nossos rituais, que amamos demais:

Reunião do Conhecimento semanalmente, nossos idwallers compartilham e debatem livremente um assunto que conhecem, pode ser de qualquer tema.

Celebration Breakfast, a cada 2 semanas, nos reunimos e cada time apresenta os acontecimentos, aprendizados e dificuldades das últimas semanas e os próximos projetos.

Idlabs, logo após o Celebration, nas sextas-feiras, nos dedicamos a trabalhar em projetos que estimulam o empreendedorismo interno e o trabalho multidisciplinar.

## Contratação
CLT

## Como se candidatar
Candidate-se **[aqui](https://jobs.kenoby.com/idwall/job/pessoa-desenvolvedora-frontend-pleno-exclusiva-para-mulheres/5fa5c6c7151f2b22c9358af5?utm_source=website)**

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: gabriela.luna@idwall.co

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno
- Exclusiva para mulheres

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
