### ISSUE TITLE
[Remoto] Fullstack Developer na VipCommerce

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#4046]
## Descrição da vaga: 
 <p>Buscamos Pessoas Desenvolvedoras <strong>Fullstack para atuar com stack: Node.js, PHP e Angular</strong>. Profissional com perfil de destaque e que possa crescer de maneira acelerada juntamente com a VipCommerce.</p>
<p>A VipCommerce é uma empresa especializada em e-grocery, especificamente e-commerce para supermercados, atacarejos e atacados. Atualmente é Líder no segmento na vertente white-label, integrada e homologada com os maiores ERP´s do segmento.</p>

## VipCommerce: 
 <p>A VipCommerce nasceu dentro de um supermercado e com vários anos de experiência no segmento varejista, entendemos o dia-a-dia do setor. E, prevendo que a venda online seria um progresso natural para os supermercados, transformamos nosso conhecimento em uma solução completa e robusta para habilitar as lojas tradicionais a venderem online.</p>

<p>Nosso compromisso é conduzi-lo, através de uma parceria duradoura, nesta transformação digital. Conte com a gente para vender online e faturar mais de um jeito seguro e descomplicado.<br></p><a href='https://coodesh.com/empresas/vipcommerce'>Veja mais no site</a>

 ## Habilidades: 
 - Angular.js 
- AWS 
- Ionic 
- MySQL 
- PHP 
- Node.js

## Local: 
 100% Remoto

## Requisitos: 
 - 2+ anos de experiência em posição similar ou como freelancer 
- Domínio de programação orientada a objeto 
- Conhecimentos em TDD e escrever Unit Tests 
- Essencial trabalhar em ambiente Linux 
- Escreva código bem projetado, testável e eficiente 
- Habituado em trabalhar com princípios SOLID, DDD e Design Patterns 
- Experiência em escrever REST APIs usando PHP Laravel ou Node 
- Experiência em trabalhar com banco de dados relacionais 
- Fluente em trabalhar com front-end Angular 4 ou superior 
- Habituado em trabalhar com metodologias ágeis / scrum 
- Saber trabalhar em equipe, em times (participativo, paciente, mediador) 
- Ser engajado com os ideias do negócio, abraçar as causas da empresa e frequentemente ser "confundido com o dono", pelo aspecto do pensamento comprometido 
- Ser engajado em pequenos times, clima de startup e negócios que crescem de maneira acelerada (pouca zona de conforto / Lean Startup)

## Benefícios: 
 - CLT ou PJ (negociável) 
- 100% Home Office 
- Subsídio de cursos e eventos em determinadas periodicidades 
- Boa flexibilidade de horários de trabalho 
- Plano de Saúde 
- Vale alimentação

## Como se candidatar:
Candidate-se em: [Fullstack Developer na VipCommerce](https://coodesh.com/vagas/fullstack-developer-153450?origin=github&modal=open)

## Tempo médio de feedbacks:
 Costumamos enviar feedbacks em até 48 horas após cada etapa do processo. E-mail para contato em caso de não haver resposta: [contato@coodesh.com](mailto:contato@coodesh.com)

#### Alocação
Remoto

#### Regime
CLT

#### Nível
Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
