### ISSUE TITLE
[Curitiba] Front-end Developer na Asap Log

### ISSUE THREAD

**Issue by nataliaintera** [frontendbr/vagas#4049]
[CURITIBA-PR] [FRONT-END @ ASAP LOG] byintera.in/j51 #vagasbyintera

Se você acredita em transformação e eficiência, a ASAPLog é o seu lugar. Uma startup de Logística e Tecnologia com a solução certa para um grande problema que enfrentamos nos e-commerces: o alto custo e a lentidão de fretes para compras online. Parte do grupo ViaVarejo e presente em 450 cidades com clientes de peso, a empresa vem transformando o cenário de entregas de através da agilidade e da redução de custos. Desenvolveu internamente a sua plataforma e assim vive um momento de alto crescimento e grandes oportunidades.

E você pode construir a transformação...

Se possui conhecimento ou experiência em:
- React, Node e Angular

Não pode perder essa oportunidade!

Basta se inscrever no link. Mas caso não seja para você, marca aqui um amigo e eu entrarei em contato. Um sorriso de orelha a orelha :)

#frontend #react #node #angular

**Comment by eliasfernandesbr** [comment]
Não encontrei o link.

**Comment by patrick1302** [comment]
Boa tarde,
Onde está o link?

**Comment by JMustang** [comment]
qual nível de experiencia vocês estão buscando?

**Comment by RafaPalau** [comment]
#### Qual link?

**Comment by nataliaintera** [comment]
> #### Qual link?

byintera.in/j51 Aqui, Rafa!

**Comment by nataliaintera** [comment]
> qual nível de experiencia vocês estão buscando?

Pleno/Senior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
