### ISSUE TITLE
[Remoto] Front-end ReactJS na Let's Delivery

### ISSUE THREAD

**Issue by FernandesFernanda** [frontendbr/vagas#4051]
> Vaga Remota

## Nossa empresa

Somos uma consultoria de food delivery que conta com uma metodologia própria
para prototipar as soluções de plataforma, serviço, logística interna e treinamento
que levarão cada restaurante até seus objetivos. No centro de nossa operação
contamos com estrategistas, consultores, engenheiros e programadores que
preparamos para produzir toda a inteligência e tecnologia que facilitará a gestão do
delivery de nossos clientes

## Descrição da vaga

Buscamos um desenvolvedor Front-End para se juntar ao time da Let’s Delivery.
Seu foco será desenvolvimento Front-End com ReactJS, Bootstrap e TypeScript.
Se você gosta de trabalhar em ambientes desafiadores e dinâmicos, é pró-ativo,
busca crescer e se desenvolver, valoriza o trabalho em equipe e a troca de
experiências para evoluir seus conhecimentos e de seus parceiros de trabalho, é
flexível para entender demandas e veloz para entregar resultados, então essa vaga
é pra você.
Na Let’s, somos apaixonados por tecnologia e buscamos constantemente inovação
e excelência técnica. Aqui, você terá a oportunidade de desenvolver código de
qualidade do conforto de sua casa.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Proficiência técnica em desenvolvimento Front-End com ReactJS,
Bootstrap e TypeScript;
- Experiência em trabalhos anteriores com Atomic Design;
- Boa noção estética sobre design e layout;
- Experiência em escrever testes para o Front-End;
- Conhecimento das boas práticas de versionamento usando Git (AWS
CodeCommit);
- Senioridade com linguagens de Front-End.

**Desejáveis:**
- Paixão e curiosidade por aprender coisas novas. Nosso ambiente está
em constante mudança, e precisamos de pessoas que se adaptem e
proponham soluções rapidamente;
- Ter experiência no setor de Food Services;
- Experiência em trabalhar em um ambiente multidisciplinar, com
designers e outros desenvolvedores;
- Experiência em Metodologias Ágeis e práticas de DevOps;

## Contratação

PJ a combinar

## Como se candidatar

Preencha o formulário: https://forms.gle/UsWxTcsFYpFLoLCv5

#### Alocação

- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
