### ISSUE TITLE
[Remoto] Front-end Developer (Vue.js) na Juntos Somos Mais

### ISSUE THREAD

**Issue by felipefialho** [frontendbr/vagas#4052]
<p align="center"><img src="https://assets-img.juntossomosmais.com.br/images/logo.svg" width="300"></p>

Somos a maior rede de relacionamento do mercado de construção civil. 

Trabalhamos para conectar empresas líderes do setor com varejistas e profissionais de obra. Nascemos em 2018, de uma parceria de três gigantes do mercado (Votorantim Cimentos, Gerdau e Tigre), e hoje contamos com mais de 21 empresas, mais de 150 mil lojistas, mais de 350 mil profissionais de obra, movimentamos mais de 6 bilhões de reais em nossa Loja Virtual em 2019, e crescemos mais a cada dia.

O nosso time é empreendedor e apaixonado pelo propósito: fortalecer o varejo de materiais de construção e transformar a vida dos profissionais que constroem sonhos! Nosso sonho é grande e a vontade de fazer mais é o que nos move!

## Descrição

Precisamos de alguém que vá além de códigos e entenda que desenvolvemos aplicações para pessoas usarem. Sendo assim, você estará livre para propor melhorias, novas ideias, compartilhar conhecimento e participar ativamente de todas as partes da concepção do produto 😁

Importante ter boa capacidade de comunicação e visão de negócio, você vai atuar em um time multidisciplinar.

Temos alguns [repositórios abertos no nosso Github](https://github.com/juntossomosmais), caso queira dar uma olhada em alguns dos nossos projetos 😋

Nessa vaga vamos precisar de alguém que atua ou já tenha experiência com **Vue.js**.

## Localização

Estamos localizados na região da Vila Olimpia em São Paulo, bem próximo da estação de trem e do shopping.

## Responsabilidades

- Atender às necessidades do negócio
- Manutenção e evolução dos produtos
- Construir códigos com qualidade e testáveis
- Estudar e implementar novas tecnologias
- Foco no usuário

## Skills

- HTML, CSS e JavaScript
- Experiência com Vue.js
- Testes
- Cuidado com UI/UX
- Git

## Desejáveis

- Design System
- Cultura open source
- Ter atuado em times ágeis (Kanban, Scrum)
- Conhecer e gostar de discutir sobre UI/UX

## Diferenciais

- Typescript

## Benefícios

💰 Remuneração variável;
🏥 Seguros de Saúde, de Vida e Odontológico de primeira - saúde sempre em primeiro lugar!
🍓 Vale-refeição;
🚗 Vale-transporte ou subsídio do estacionamento;
💻 Equipamento de última geração ([MacBook Pro](https://www.apple.com/br/macbook-pro-13/specs/))
🤸 Gympass – Academia e saúde do corpo onde você quiser!
🧘 Zenklub - Para você cuidar do seu bem-estar e saúde mental :)
🧘 Sessões de Mindfulness semanais, para relaxar, desestressar e praticar a atenção plena;
👶 Auxílio creche, para você cuidar do desenvolvimento de quem mais ama!
🍼 Sabemos como se tornar mãe ou pai é marcante e queremos dar todo o apoio. A licença-maternidade é de 180 dias e a licença parental de 20 dias. O benefício também vale para papais e mamães que adotarem ou obtiverem a guarda judicial da criança e para casais homoafetivos. Além disso, também oferecemos auxílio-creche.

## Ambiente 

- TechTalks internas - quinzenais 
- TechTalks [externas - mensais](https://www.youtube.com/watch?v=6uWzv_P_Ui0)

## Como se candidatar

1. Aplicar na [vaga cadastrada na Gupy](https://juntossomosmais.gupy.io/jobs/631210?jobBoardSource=gupy_public_page)
2. **Após nosso contato** faça [o desafio seguindo as instruções](https://github.com/juntossomosmais/frontend-challenge)
3. Boa sorte 🙏
______

Junte-se! 💕

**Comment by mateusavila** [comment]
Esta vaga não existe a chance dela de ser 100% remoto? Pois moro em Blumenau, e minha mudança com minha família seria impossível hoje.

PS: vaga sensacional

**Comment by felipefialho** [comment]
@mateusavila A vaga é 100% remoto com idas eventuais (a combinar) pra São Paulo no pós pandemia.

**Comment by mateusavila** [comment]
Que pena. a passagem aérea de Blumenau para SP deve ser bem cara. Bom, vamos a luta

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by mateusavila** [comment]
close

**Comment by esabrito** [comment]
Bom dia!

cancelar minha escrição por favor.

Obrigado.

Em seg., 22 de mar. de 2021 às 09:19, Mateus Ávila Isidoro <
***@***.***> escreveu:

**Comment by Gabri3el** [comment]
Enviado \o/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
