### ISSUE TITLE
[REMOTO] Front-End Developer (Foco em Angular) Senior na Conquest One

### ISSUE THREAD

**Issue by lucasherodoto** [frontendbr/vagas#4058]
## Nossa empresa

A Conquest One é uma empresa especializada em Staffing de TI, sendo eleita 9 vezes como uma GPTW e agora está em busca de uma pessoa apaixonada por tecnologia e inovação para uma oportunidade incrível!

## Descrição da vaga

Foco em desenvolvimento, levantamento de requisitos técnicos e atuação em projeto que já está em andamento, sempre atento ao surgimento de novas demandas

## Local

Remoto

## Requisitos

**Obrigatórios:**

Mais de 5 anos de experiência com Angular 2 ou superior
• Versionamento de código utilizando Git
• Conhecimentos em técnicas e ferramentas para testes automatizados (unitário e integrado)
• Scrum
• Boa comunicação e relacionamento interpessoal para interagir com usuário e área de negócios

**Desejáveis:**

• Fluência com Git Flow
• Conhecimento de arquitetura de micro-serviços
• Conhecimento de Ruby On Rails e/ou .NET
• Docker
• Linux

**Diferenciais:**
Inglês 

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para lucas.martins@cq1.com.br com seu CV anexado - enviar no assunto: Vaga Angular Senior

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
