### ISSUE TITLE
[Porto Alegre] Fullstack Developer na DBServer

### ISSUE THREAD

**Issue by AlineSchorn** [frontendbr/vagas#4061]
A DBServer é uma Softwarehouse gaúcha que constrói entregas sob medida. Há 27 anos trabalhamos com foco nas pessoas, guiados por nossos valores, crescendo lado a lado com nossos colaboradores. Nosso lema é fazer a coisa certa do jeito certo através do design e do build.

Nos últimos anos, iniciamos uma caminhada em direção a diversidade e a inclusão e após o lançamento do nosso Marco Ético temos agora um norteador dos princípios que irão trilhar a nossa trajetória.

Estamos orgulhosos de promover um ambiente de trabalho livre de discriminação. Acreditamos que a diversidade de experiências, perspectivas e histórico transforma nosso ambiente de trabalho. Estamos empenhados a construir esse legado com a sua parceria!

Conheça nosso Marco ético: http://www.dbserver.com.br/marcoetico/

**Descrição da vaga:**

O que vamos construir juntos?

Nesse projeto, trabalharemos juntos no desenvolvimento do sistema na área ambiental para órgão público. Nosso time é preocupado em propor as melhores soluções baseado em excelência técnica, pensando em alternativas que agreguem valor, com mindset ágil e cultura de colaboração. Nós respeitamos a diversidade e acreditamos que times diversos contribuem para construir ideias mais inovadoras.

Nos ajude a desenhar a solução!

Se você chegou até aqui e é uma pessoa que gosta de trabalhar com qualidade, aprecia muito desafios, de implementar soluções baseadas em boas práticas e curte trabalhar em times que respeitam quem você é e as suas opiniões, você está MUITO perto de integrar nosso time DB.

**Local:**
Porto Alegre - RS

**Requisitos:**

Experiência mínima de 3 (três) anos em desenvolvimento de software na linguagem de programação JAVA;
Conhecimento sólido com desenvolvimento de software para servidor de aplicações na especificação JEE (CDI, EJB, JPA, JAX-RS);
Conhecimento sólido em Angular (desejável conhecimento em testes com Jest);
Conhecimento em Orientação a Objetos, Design Patterns, SOLID e Clean Code;
Conhecimento em desenvolvimento de RESTful APIs;
Conhecimento em JUnit (testes unitários), Weld e RESTEasy (testes integração).

Será legal se você tiver conhecimento em:

Servidor de aplicações Wildfly;
Banco de Dados PostgreSQL;
Ferramentas de migrations (Liquibase ou Flyway);
Conhecimento em metodologia ágil.

**Benefícios:**
- Plano de saúde
- Seguro de vida
- Vale Refeição
- Plano Odontológico

**Diferenciais:**
- horários flexíveis
- ambiente diverso
- troca de conhecimento
- oportunidade de aprender muito \o/
- Contratação
- CLT

**Como se candidatar:**
https://jobs.kenoby.com/dbserver/job/dev-fullstack-javaangular/5ff601d6940e1974796dc246?utm_source=website

**Tempo médio de feedbacks:**
Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: poa_seleção@dbserver.com.br

Labels
Alocação
Alocado

**Regime:**
CLT

**Nível:**
Pleno
Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
