### ISSUE TITLE
[São Paulo] Front-end / Back-end no Gasola

### ISSUE THREAD

**Issue by nurycaroline** [frontendbr/vagas#4062]
## Nossa empresa

O Gasola nasce para conectar empresas e postos de combustível, através de uma plataforma 100% digital. Possibilitamos aumento dos descontos negociados e melhoramos a gestão de consumo!

Para saber mais sobre nossos produtos ⇒ [https://gasola.net](https://gasola.net/)

## Descrição da vaga

Para saber mais sobre as tecnologias que estamos utilizando ⇒ [https://app.rocketseat.com.br/us/gasola](https://app.rocketseat.com.br/us/gasola)

As principais atividades serão:

- Desenvolver aplicações utilizando JavaScript ( Nodejs, React e React Native );
- Atuar na manutenção dos sistemas desenvolvidos;
- Atuar no desenvolvimento e definição de novas features;
- Propor e implementar melhorias nos processos e arquitetura da aplicação;
- Planejar, arquitetar, especificar e implementar soluções baseadas em tecnologia Web;
- Codificar e realizar testes.

## Local

 Escritório, São Paulo - SP

## Requisitos

**Obrigatórios:**
- ReactJS
- NodeJS + Express
- React Native
- Jest + Supertest
- Git / Github

**Desejáveis:**
- conhecimentos em aws
- conhecimentos em Typescript
- conhecimentos em docker

## Benefícios
- A combinas

## Contratação

A combinar

## Como se candidatar

Por favor envie um email para nurielly@gasola.net com seu CV anexado e link do Github

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: nurielly@gasola.net

#### Alocação
- Alocado

#### Regime
- CLT
- PJ

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
