### ISSUE TITLE
[São Paulo] Front-end Engineer Pleno

### ISSUE THREAD

**Issue by webdthiago** [frontendbr/vagas#407]
## Descrição da vaga

Nos preocupamos com o que você entrega e não como você se veste. Sabe como é uma Startup, né? Pessoas criativas, ambiente dinâmico, despojado, horário flexível, pouca burocracia e formalidades... Dá uma olhada nas fotos para sentir a vibe dos nerds :P

Estamos procurando engenheiro(a)s front-end apaixonado(a)s para nos ajudar a acabar com o SPAM no mundo. Não é brincadeira, temos uma missão de transformar a experiência de compra das pessoas em algo muito mais humanizado e inteligente.

Com grandes poderes vêm grandes responsabilidades e para ser um super Miner vai lidar com isso aqui:

- Renderização de plugins inteligentes "on the fly" (+300 milhões de pageviews/mês)
- Mobile First
- Metodologias de desenvolvimento ágil
- Programação Front-End (SPA)

* Incentivamos a rotatividade em projetos diferentes para disseminar o conhecimento do time.

## Local

Escritório, São Paulo - Pinheiros

## Requisitos

Valorizamos muito a capacidade de aprendizado, mas precisamos de alguém que já chegue dando uma voadora nestas linguagens/metodologias:

- HTML 5
- CSS 3 
- JavaScript
- Angular JS
- Bower

Estas aqui são nice to have:

- React
- SASS
- Gulp
- NPM
- Webpack
- Noções de UX/UI

## Contratação

PJ ou CLT a combinar

## Nossa empresa

A Social Miner é uma plataforma de People Marketing que ajuda empresas a automatizarem sua comunicação de marketing, entregando experiências personalizadas para cada indivíduo em grande escala. A startup possui mais de 11 milhões de usuários conectados através de seus plugins sociais e mais de 100 milhões de impressões únicas.

## Como se candidatar

Por favor envie um email para roger@socialminer.com com seu CV anexado - enviar no assunto: Vaga Front-end

**Comment by paulo-campos** [comment]
Conheci a galera e já fui no MeetUp da Social Miner, o lugar me pareceu muito bom de se trabalhar...Recomendo!

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
