### ISSUE TITLE
[Lisboa/Portugal] Front-end Developer na Integer Consulting

### ISSUE THREAD

**Issue by AnaMargaridaAlmeida** [frontendbr/vagas#4070]
## Integer Consulting

A INTEGER, uma empresa de consultoria na área das tecnologias, com mais de uma década de presença no mercado português, está à procura de Front-End Developer (M/F) com fortes habilidades de comunicação e sentido de responsabilidade e de trabalho em equipa.

Este pode ser o desafio perfeito para ti se tens:

• Licenciatura em IT;
• Mínimo 1 ano de experiência em React;
• Conhecimentos de Redux e TypeScript;
• Inglês intermédio;

## Lisboa/ Portugal

Se tens o amazINg talent pretendido e queres fazer parte da equipa INTEGER, responde a este anúncio com o teu CV atualizado para margarida.almeida@integer.pt.

Participar neste projeto significa a integração numa empresa sólida em crescimento e numa equipa jovem e dinâmica. #jumpIN

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
