### ISSUE TITLE
[Belo Horizonte] Javascript Developer Pleno na nata.house

### ISSUE THREAD

**Issue by izabelamonteiro002** [frontendbr/vagas#4073]
> Vaga Remota durante a pandemia!

## Sobre a nata

A nata.house surgiu em 2017 com o propósito de melhorar a dinâmica do mercado de software, gerando mais valor e uma experiência melhor para o cliente e proporcionando mais espaço de desenvolvimento e aprendizado para seus colaboradores.

Hoje, com 3 anos de empresa, construímos uma cultura de transparência, excelência, colaboração, inquietude, em que cada um sabe da sua responsabilidade, contribuindo, assim, para a construção de uma nata melhor. Somos movidos por desafios, respiramos tecnologia e acreditamos que qualidade de software é a base de qualquer empresa digital!

Especialistas em desenvolvimento de software, hoje trabalhamos principalmente com o ecossistema JavaScript, atuando não como fornecedores, mas de fato como parceiros de tecnologia dos nossos clientes. Atendemos empresas de base tecnológica nacionais e internacionais, atuando no desenvolvimento e construção de novas features. 

Além disso, nos preocupamos em construir um time com pessoas talentosas, alinhadas à cultura e que acreditam nos objetivos da empresa, para manter as pessoas engajadas, motivadas e crescendo junto com a nata.

## Local

Belo Horizonte - MG

## Quem estamos procurando? 

Na nata.house, entendemos que construímos a empresa juntos. Por isso, buscamos alguém disposto a encarar grandes desafios, e que tenha como um de seus valores a colaboração.  Estamos vivendo um momento  importante  de crescimento, sendo necessário que a pessoa tenha foco em resolver problemas, usando de sua autonomia inclusive para propor melhorias na forma como trabalhamos. 

Dessa forma, seu papel também é apoiar a nossa missão de conseguir fomentar um ambiente de desenvolvimento para o time e estabelecer uma relação de parceria com nossos clientes, garantindo a qualidade dos nossos serviços e eficiência dos nossos processos. 

Trabalhamos em um ambiente dinâmico e estamos sempre atentos ao que há de mais novo no mercado, incorporando o que faz sentido para nosso contexto. Com isso, a pessoa terá a oportunidade de aprender novas tecnologias e propor formas de aplicá-las dentro da nata.

## Você será responsável por:

- Desenvolver aplicações em JavaScript (preferencialmente nos frameworks React, React Native e/ou NodeJS), garantir a qualidade e as entregas técnicas dos projetos sob sua responsabilidade e acompanhar a execução das tarefas;
- Participar do desenvolvimento do planejamento arquitetural dos projetos;
- Entender em profundidade o contexto técnico do projeto, compreendendo o modelo de negócio do cliente e como deve funcionar o sistema.

**Obrigatórios:**
- Estar familiarizado com: apis, cloud functions, SDKs, front-ends;
- Ter noção de como funciona a infraestrutura de cloud e DevOps: storage, hosting, VMs, ambientes de produção/homologação;
- Ter interesse não apenas por desenvolver, mas também pela melhoria contínua e por práticas garantem a qualidade do seu código;
- Ter conhecimento de inglês.

**Hoje trabalhamos com as seguintes tecnologias:**
- React
- React Native
- NodeJS
- Git
- AWS/GCP

## Benefícios

- Carga horária de 40 horas semanais, de segunda a sexta;
- Temos vale-refeição/alimentação Sodexo de R$ 22,05 por dia;
- Para a galera do busão, vale-transporte de acordo com a necessidade, ou, se preferir, auxílio combustível no valor de R$120, sem desconto em folha;
- Bônus anual, pois, afinal, crescemos juntos! Se a empresa tem lucro, o mérito é seu e parte do lucro também;
- Se você está se desenvolvendo e gerando resultado, por quê não receber proporcionalmente? Nada de ficar estagnado: temos plano de carreira bem definido
- Who run the world? You! Temos incentivo ao aprendizado de inglês;
- Segurança extra com o nosso Seguro de Vida.
- Lanche à vontade;
- Horário flexível;
- Um happy hour mensal pago pela empresa;
- Auxílio financeiro para cursos, eventos e capacitações;
- No dress code (be you!)

## Contratação

CLT

## Como se candidatar

Se interessou? Para se candidatar, basta preencher o formulário (https://forms.gle/DLAegPXCxeLJVDQ77) e boa sorte! :)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: vagas@natahouse.com

#### Regime
- CLT

#### Nível
-Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
