### ISSUE TITLE
[Campinas] Front-end Web Developer na Griaule

### ISSUE THREAD

**Issue by henrique-griaule** [frontendbr/vagas#4074]
## Nossa empresa

Somos líderes mundiais em software de reconhecimento biométrico, focado em Big Data e projetos de larga escala. Fornecemos soluções de ponta para organizações ao redor do mundo, garantindo segurança na identificação de indivíduos. 

## Descrição da vaga

Estamos buscando um Desenvolvedor Front-End Web para integrar nossa equipe e trabalhar nos produtos de identificação biométrica.

## Local

 Escritório, Campinas-SP (Barão Geraldo)

## Requisitos

**Obrigatórios:**
-React ou outro framework Web e Redux;
-Boas práticas de versionamento com GIT e Gitlab;
-Inglês - Leitura e Escrita.

**Desejáveis:**
-Conhecimentos de TDD, Cypress, Jest, GitlabCI ou Docker.

## Benefícios

- Salários acima do mercado;
- Participação nos lucros;
- Vale refeição e alimentação;
- Plano de saúde;
- Plano dental;

**Diferenciais:**
- Doces, frutas e bebidas a vontade
- Escritório com piscina

## Contratação

CLT ou Estágio

## Como se candidatar

 Candidaturas através do site: https://griaule.com/careers/web-developer/

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: hr@griaule.com

#### Alocação
- Alocado

#### Regime
- CLT
- Estágio

#### Nível
- Júnior
- Pleno

**Comment by lucasfe4nor** [comment]
currículo tem que ser em inglês ?

**Comment by henrique-griaule** [comment]
> currículo tem que ser em inglês ?

Não é necessário! Pode ser em português.

**Comment by rodrigoantas** [comment]
Somente alocado? Não existe possibilidade de remoto?

**Comment by henrique-griaule** [comment]
> Somente alocado? Não existe possibilidade de remoto?

A empresa já retornou as atividades presencialmente, então somente alocado.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
