### ISSUE TITLE
[Brasil] Software Engineer Front-end  na NILO

### ISSUE THREAD

**Issue by anacarolinasant** [frontendbr/vagas#4076]
**Descrição:**  A Nilo é uma HealthTech brasileira que nasceu para revolucionar o nosso olhar para a saúde nas organizações. Integrando de forma singular o mundo digital com o serviço de saúde de excelência, a Nilo tem a missão de redesenhar como é feito o cuidado da população 50+ no Brasil, trazendo mais qualidade de vida e saúde. Neste momento estamos em busca de um (a) **Software Engineer Front End**, um profissional que tenha um espírito empreendedor,  que encante-se pelo propósito e missão do time. **Este profissional fará parte da equipe responsável pela plataforma inteligente que unifica todos os dados de pacientes e ajuda o time de coordenação com sugestões de intervenções acionáveis para prevenção de internações e procedimentos desproporcionais, melhorando a saúde do paciente e evitando gastos desnecessários**. Você topa revolucionar a saúde brasileira junto com a Nilo? 

**Contratação:** PJ

**Local:** 100% Remoto

**Nível.** Pleno

**Requisitos:** Experiência com JavaScript, React e Typescript, práticas ágeis de desenvolvimento de software; conhecimento de boas práticas como Clean Code, SOLID e Design Patterns; conhecimento em Firebase e familiaridade com ferramentas Google Cloud.

Fazer o cadastro no seguinte site:  ** https://byintera.in/nilofegt **

Dúvidas: https://www.linkedin.com/in/ana-carolina-santos-7a6612114/
==================================================

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
