### ISSUE TITLE
Vaga para Programador com Experiência em Vídeos - Home Office

### ISSUE THREAD

**Issue by cristianpazdasilva** [frontendbr/vagas#4077]
Programador com experiência em programação de vídeos, criação, e desenvolvimento de funcionalidades relacionas a criação dinâmica de vídeos.

• Experiência com banco de dados.
• Conhecimento em Laravel
• Conhecimento desejável nos frameworks: Lumen, Yii ou Zend.
• Inglês intermediário (Leitura e escrita de requisitos Inglês)

Interessados enviar Currículo para webprogramdesen@gmail.com com o questionário abaixo respondido:
Pretensão salarial
Descrever experiência (Quantos anos) em desenvolvimento, listar projetos envolvidos.
Disponibilidade de horas por dia (em quais horários e dias)
Qual a experiência com trabalho remoto, home office?
Motivo do desligamento do último trabalho?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
