### ISSUE TITLE
[Remoto]  Senior Frontend Developer na KOUD

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#4079]
## Descrição da vaga: 
 <p>As a frontend engineer within KOUD you will be working on our costumer new eCommerce platform across multiple markets</p>
<p>Expect “Design it, build it, run it” with a team of strong, driven contributors.</p>
<p></p>
<p></p>

## KOUD: 
 <p>A KOUD foi fundada em 2018 com o objetivo de ajudar empresas na transformação digital de seus processos.</p>
<p>Trabalhamos nas áreas de Marketing Digital e Desenvolvimento de Softwares, provendo a nossos clientes uma solução completa de posicionamento digital.</p><a href='https://coodesh.com/empresas/koud'>Veja mais no site</a>

 ## Habilidades: 
 - CSS 
- HTML 5 
- Javascript 
- React.js 
- Vue.js 
- Unit Test 
- BDD 
- GitLab 
- TDD
## Local: 
 100% Remoto
## Requisitos: 
 - 3+ years of frontend software development experience 
- You have specific technical knowledge such as Javascript, EcmaScript, HTML and CSS, SCSS, BEM, Webpack 
- Experience with JavaScript frameworks (Vue or React) 
- Integrating UI components with RESTful API's or GraphQL 
- You have knowledge about the concept of micro Frontends 
- You have knowledge in some testing approaches and tools (Unit testing, e2e testing, BDD, TDD) 
- Experienced with version control technologies, such as Git (Gitlab) 
- You have an eye for pixel-perfect design, attention to quality and detail 
- You are a strong team player, you like to share your knowledge, and communicate in person with your team members and other stakeholders to come to the best solution 
- Excellent communication skills in English (mandatory) and Portuguese (Nice to have)

## Como se candidatar:
Candidate-se em: [ Senior Frontend Developer na KOUD](https://coodesh.com/vagas/senior-frontend-developer-170250?origin=github&modal=open)
## Tempo médio de feedbacks:
 Costumamos enviar feedbacks em até 48 horas após cada etapa do processo. E-mail para contato em caso de não haver resposta: [frederico.sieck@koud.com.br](mailto:frederico.sieck@koud.com.br)
#### Alocação
Remoto
#### Regime
PJ
#### Nível
Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
