### ISSUE TITLE
[Remoto][Brasília] Front-end Developer no Jazida.com

### ISSUE THREAD

**Issue by tvaamorim** [frontendbr/vagas#4080]
** Front-end Developer (Junio ou Pleno)**

## Descrição da vaga

O JAZIDA está em busca de Front-End Developer para entrega de melhorias e aplicação de tecnologias inovadoras maximizando a efetividade e eficiência do sistema. O cargo é requerido para entender e interpretar os aspectos técnicos, legais, comerciais, econômicos e corporativos que impactam o desenvolvimento de um software. 

Este cargo é uma grande oportunidade de fazer parte  do time de desenvolvimento de um sistema complexo entregando aos clientes do Jazida.com ferramentas capazes de mudar a maneira como milhares de pessoas trabalham diariamente. Este trabalho tem um foco estratégico e responsabilidade em todo território nacional.  

Somos pioneiros na automatização da gestão de processos minerários e mudamos a forma que a mineração do Brasil gerencia seus processos.  
Nossa história é marcada por inovações e pioneirismo. Fomos os primeiros a automatizar a leitura e interpretação de milhares de códigos e textos publicados diariamente em sites do governo e jornais oficiais que impactam a vida de milhares de pessoas em todo o Brasil. Fomos os primeiros a espacializar isso e traduzir de forma simplificada, removendo barreiras burocráticas e elevada exigência de conhecimento técnico. Além de impactar na vida de mineradores, esta eficiência se traduz na democratização de um setor, gerando empregos e renda para milhares de pessoas. 

ATIVIDADES PRINCIPAIS

- Projetar, codificar, testar, operar e resolver problemas
- Suportar decisões e priorizações das demandas com o intuito de evoluir os produtos atuais e desenvolver novos produtos que gerem valor para os nossos clientes.
- Dar suporte para o restante da equipe de desenvolvimento em nível técnico
- Responsável por trazer novas ideias para soluções de problemas
- Ter um desejo de participar em projetos desafiadores que impactam na vida de milhares de pessoas 
- Desenvolvido de Testes Automatizados 
- Colaborar com outro setores da empresa para gerar valor
- Manutenção e cuidado de sistema em produção

## Local

Escritório localizado em Brasília - DF ou Remoto

## Benefícios

**O que o Jazida oferece** 

Seguem apenas uma amostra do nosso pacote de benefícios 
- Home Office 
- Um pacote de salário competitivo com prêmio salarial de incentivo anual em dinheiro (PLR) 
- Desenvolvimento de carreira e assistência educacional para promover seus objetivos 
- Assistência educacional para inglês 
- Uma política abrangente de licenças que cobre todos os momentos importantes da vida (férias / anuais, licença parental remunerada, licença médica, férias remuneradas) 
- Suporte no acesso a Plano de Saúde e Academia 
- Apoio contínuo de bem-estar individual  

#### Diferenciais

Ambiente de trabalho sem formalidades, horário flexível e hierarquia plana
Temos um ambiente muito livre para tomada de decisões técnicas

## Requisitos

Para ter sucesso neste cargo você deve 

- Ter um desejo de participar em projetos desafiadores que impactam na vida de milhares de pessoas 
- Conhecimento em ReactJS e Redux
- Conhecimento em linux 
- CSS - SASS
- HTML

Diferencial
- Conhecimento em Testes Automatizados 
- Conhecimentos em Docker e Kubernetes é um diferencial 

## Contratação

PJ a combinar

## Como se candidatar
**Apenas Perfis Junior e Senior**
Venha fazer parte do Jazida, envie seu CV para vagas@jazida.com no assunto adicionar "Vaga Frontend" E no email colocar a **pretensão salarial** e **perfil [PLENO] OU [JUNIOR]**

## Tempo médio de feedbacks

Caso você seja selecionado, receberá um contato da nossa equipe.
E-mail para contato em caso de não haver resposta: vagas@jazida.com

## Labels

- 🏢 Flexível
- 🏢 Presencial
- 🏢 Remoto
- 👨 Pleno
- Junior
- ⚖️ A-Combinar
- ⚖️ PJ

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
