### ISSUE TITLE
[RJ / Remoto] - inChurch - Dev Frontend

### ISSUE THREAD

**Issue by Pereira746** [frontendbr/vagas#4082]
Se você é louco pelo que faz e apaixonado por pessoas e por tecnologia, vem fazer parte do nosso dream team!
Para isso você precisa curtir transformar e mandar super bem nas habilidades requeridas pela vaga. :)

Bom, nós somos a InChurch, uma startup referência na construção de aplicativos para o terceiro setor na América Latina.
Desenvolvemos Apps, Sites, Totens Interativos e tudo o que for importante para entregar conveniência para os nossos usuários.

**Sua Missão:**
Desenvolver funcionalidades no gestor de conteúdo dos aplicativos e sites
Criar variantes do layout original de uma aplicação de site whitelabel
Migrar aplicações de AngularJS para Angular 6

**Habilidades Técnicas:**
Proficiência em HTML5, JavaScript e CSS3
Proficiência em AngularJS
Familiaridade com APIs REST
Experiência em versionamento de projetos com Git
Experiência com Bootstrap e pré-processador de CSS (preferencialmente SASS)

**Adoraríamos se você soubesse também:**
Utilizar princípios de SEO no desenvolvimento
Angular 4 (ou mais recente) e Angular Universal
UI/UX utilizando ferramenta de prototipagem
Graduação em Ciência da Computação, Engenharia de Software, Análise e Desenvolvimento de Sistemas ou correlata

**Local de Trabalho:** Essa vaga também é oferecida remotamente. No entanto, havendo interesse de ser contratad@ nos moldes presenciais em um próximo momento (sem previsão ainda de quando) nós ficamos no Rio de Janeiro - Barra da Tijuca (Próximo ao Shopping Metropolitano).

Estamos trabalhando com pretensão salarial para essa posição.

**Benefícios:**
VT ou Auxílio Combustível
VR
Plano de Saúde (Golden Cross ou Bradesco)
Plano Odontológico (Golden Cross)
Academia no Local
Frutas todos os dias \o/
Descontos em instituições parceiras
Cultura interna de aprendizado constante

**Inscrições: https://inchurch.solides.jobs/vacancies/51730
Ou enviar currículo para rh@inchurch.com.br**

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
