### ISSUE TITLE
[Barueri] Front-end Developer na Auditeste Consultoria

### ISSUE THREAD

**Issue by auditeste-consultoria** [frontendbr/vagas#4083]
> Vaga Remota durante a pandemia

## Nossa empresa

A Auditeste Consultoria é uma empresa totalmente focada em promover qualidade de software, e desde 2001 se mantém como referência neste segmento. 

## Descrição da vaga

Oportunidade para profissionais Front-end.

## Local

Remoto [SP], [Barueri]

## Requisitos

**Obrigatórios:**
✅React (JSX), Javascript (ES6), Sass, Less, TypeScript
✅Aplicações Web Mobile / Webview (Android e IOS)
✅Experiência em consumo de API (RESTfull)
✅Produção de telas e recortes HTML, Responsive Web Design
✅Pacote Adobe (Photoshop, XD, Illustrator)
✅Experiência em projetos Web (Hotsites, Intranets, E-commerces e Integradores)
✅Continuous integration, Controle de Versão (GIT)
✅Swagger, Postman
✅Metodologia: Scrum

**Desejáveis:**
•             Conhecimento em outras linguagens (Angular, Vue.JS);
•             Experiência em aplicações de alta performance;
•             TDD, SEO, Testes A/B;
•             Mobile First, Conhecimento em UX.

## Modalidade de contratação e Benefícios

💰 Vaga PJ - férias remuneradas
🏘️ 100% Home Office. 

## Como se candidatar

Currículos deverão ser encaminhados para: vagas@auditeste.com.br com o assunto: Dev. Front-end

## Tempo médio de feedbacks

E-mail para contato em caso de não haver resposta: vagas@auditeste.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
