### ISSUE TITLE
[Remoto] Front-end Developer na Assertive Yield

### ISSUE THREAD

**Issue by lucasavila00** [frontendbr/vagas#4084]
## Nossa empresa

A [Assertive Yield](https://www.assertiveyield.com/) trabalha com analytics de ads. Todos os funcionários trabalham remotamente. A empresa é da Holanda.

## Descrição da vaga

Estamos à procura de alguém para ajudar no desenvolvimento da plataforma que é usada para visualização de dados. A plataforma já está online mas estamos adicionando novas funcionalidades todos dias, à medida que os clientes as desejam.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- experiência com Node
- experiência com react

**Desejáveis:**
- conhecimentos em mongodb
- conhecimentos em SQL
- conhecimentoes em meteor (plataforma de apps em JS)

**Diferenciais:**
- projetos opensource

## Benefícios

- Monte seu próprio horário

## Contratação

- Contrato assinado na Europa.

## Como se candidatar

Por favor envie um email para lucaxx@gmail.com com seu CV anexado - enviar no assunto: Vaga AY. O contato comigo pode ser em português. Depois eu vou encaminhar seu CV para o resto da equipe (neste ponto o CV precisa estar em inglês)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- Prestação de Serviço

#### Nível
- Júnior

**Comment by mrangel-jr** [comment]
Tem a faixa salarial de remuneração ?

**Comment by lucasavila00** [comment]
@mrangel-jr infelizmente eu não posso falar sobre salário.

**Comment by lucasfe4nor** [comment]
@lucasavila00 tem algum nível de inglês obrigatório ?

**Comment by lucasavila00** [comment]
@lucasfe4nor Um inglês de conversação básico pra quando tiver ligação em vídeo (raro) e um inglês bom em texto. As coisas que você vai ter que fazer vão te informar em inglês, e se tiver dúvida, tem que perguntar em inglês, etc.
A empresa opera em inglês totalmente.

**Comment by ItaloCanturil** [comment]
Só tenho experiência com Vue mas sou totalmente aberto ao React, pode ser?

**Comment by lucasavila00** [comment]
@ItaloCanturil como a nossa equipe é muito pequena não teríamos como treinar alguém.
