### ISSUE TITLE
[SãoPaulo] Front-end Developer Pleno na Uello

### ISSUE THREAD

**Issue by Uello1** [frontendbr/vagas#4086]
> Vaga Remota durante a pandemia

## Nossa empresa

A UELLO É UMA LOGTECH FOCADA EM ENTREGAS URBANAS 📦
A Uello está mudando a maneira como as entregas urbanas são realizadas através de *tecnologia e otimização.

Atuamos com uma abordagem moderna para resolver problemas complexos que ainda são tratados à moda antiga pelo mercado tradicional.

Buscamos conectar tecnologia e operação para criar experiências logísticas customizadas para nossos clientes, simplificando o fluxo de entregas, fazendo um melhor uso de recursos e com a melhor eficiência possível.

Nossa missão é criar um ecossistema logístico com uso de tecnologia de ponta para simplificar problemas.

## Descrição da vaga

No time de tecnologia da Uello, você trabalhará no desenvolvimento de nossos sistemas internos e integrações. Hoje, todo o sistema da Uello é desenvolvido in-house e precisamos cada vez mais de excelentes pessoas para nos auxiliar a deixar a plataforma cada vez melhor. Buscamos um ambiente onde as pessoas possam ter autonomia para trazer soluções e abertura para opinar em todas as etapas do processo, através de melhoria contínua.

## Local

Remoto ou Modelo Hibrido 

## Requisitos

Para a posição de desenvolvedor FrontEnd Pleno, espera-se que você possua os seguintes conhecimentos:

- Proficiência nos fremeworks VueJS ou ReactJS
- Integrações com APIs REST
- CSS3, SASS, styled-components
- Criação de componentes reutilizáveis
- Criação com base em layouts oferecidos por um UX/UI (sem pixel perfect)

Conhecimento em bibliotecas ou SDKs de mapas (Mapbox, GoogleMaps, Here, Leafleat) será considerado um diferencial.

## Contratação

PJ 

## Como se candidatar

https://uello.gupy.io/jobs/634574

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
