### ISSUE TITLE
[São Paulo] Front-End Developer Senior no [ITAÚ]

### ISSUE THREAD

**Issue by brulucenacord** [frontendbr/vagas#4087]
## Nossa empresa

O Itaú Unibanco é o maior banco privado do Brasil, a maior instituição financeira da América Latina e uma das maiores do mundo. Nossa marca é apontada como a mais valiosa do país, segundo o ranking Interbrand, entre outros importantes reconhecimentos. Presente em 18 países, buscamos oferecer soluções completas em termos de produtos e serviços por meio de inteligência financeira e um ecossistema de parcerias. Isso repercute em nossos contínuos esforços em atender plenamente às necessidades de cada cliente, desde pessoas físicas e microempresas a organizações de grande porte, e proporcionar a melhor experiência tanto digital quanto presencial.

_Gente é tudo pra gente_

Pessoas são o maior ativo do Itaú, pois cuidam de seu bem mais precioso: o cliente. Por isso, o Itaú vive verdadeiramente sua cultura organizacional, valoriza e respeita a diversidade e o protagonismo de seus colaboradores em todas as suas relações. Faz o que é certo e quer que você seja autêntico, inclusive na forma de se vestir, para exercer todo o seu potencial, focar no seu desenvolvimento e nas soluções para os clientes. 

Na Tecnologia, os times são multidisciplinares, com diversas especialidades, e trabalham com práticas ágeis e lean, focadas no aprendizado contínuo e colaboração. Além disso, tem grupos de afinidade de raça, mulheres, LGBT e PCDs em que os colaboradores protagonizam pautas importantes da sociedade e contribuem com a transformação e centralidade no cliente.

## Descrição da vaga

Nossa vaga é pra vc fazer parte do time de Engenharia na Comunidade Integrada de Crédito Imobiliário.

O propósito da família IMOB é liderar o movimento de transformação do crédito construindo a plataforma mais moderna, mais desejada, mais digital e de juros baixos do mercado. Nós queremos revolucionar a experiência do cliente e vc pode fazer parte dessa missão através da modernização e evolução dos nossos canais digitais!

Se quiser conhecer um pouco mais sobre nós e sobre a cultura de FrontEnd do Itaú, recomendamos o podcast do Hipsters On The Road, onde falamos um pouco sobre o que estamos fazendo:

https://hipsters.tech/cultura-frontend-no-itau-hipsters-on-the-road-13/

## Local

Remoto [período da pandemia] e/ou Escritório, [SP], [São Paulo], [Moóca]

## Requisitos

<b>O que esperamos de você:</b>
- Foco na melhor experiência para o cliente;
- Buscar aprendizado constantemente;
- Colaboração, saber oferecer e pedir ajuda;
- Pró-atividade, nós pensamos e agimos como dono;
- Resiliência, não se limite;
- Ética, para nós é inegociável.

<b>Quais serão minhas contribuições?</b>
- Atuar em times ágeis e multidisciplinares com TI e Negócio trabalhando na mesma Comunidade;
- Estudar, testar, documentar e contribuir com novas ferramentas, libs, frameworks e arquiteturas para uso interno;
- Gerar o desenho técnico e contribuir com padrões de arquitetura;
- Desenhar soluções sustentáveis a partir do conhecimento da estrutura dos sistemas e soluções;
- Garantir elasticidade e escalabilidade na construção de software;
- Garantir a atualização da documentação e gestão do conhecimento dos sistemas;
- Participar de todo o ciclo das aplicações desde a concepção à construção.

<b>Conhecimentos Técnicos</b>
- Experiência com Angular, React, Vue ou outro framework JS moderno (Angular será um diferencial)
- JavaScript 
- JQuery 
- HTML 
- Typescript
- CSS 
- Bootstrap
- SQL
- Linux
- Conhecimento em Cloud AWS será um diferencial;
- Desejável colaboração com projetos Open Source;

## Benefícios

- Assist Médica
- Assist Odonto
- Seguro de vida
- Previdência
- Produtos Financeiros
- VR / VA / VT (seguindo sindicato dos bancários)
- Auxílio creche
- Benefícios parceiros (lojas, drogarias, academias, etc., + de 1.000 parceiros cadastrados)
- Bolsa Auxilio Educação
- Itaú Unibanco Clube 
- PLR

## Contratação

CLT

## Como se candidatar

- Por favor envie um e-mail para bruna.lucena@itau-unibanco.com.br com seu CV anexado ou link do LinkedIn atualizado + perfil aqui GitHub.
- enviar no assunto: VAGA FRONT-END IMOB

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: bruna.lucena@itau-unibanco.com.br

#### Alocação
- Remoto durante pandemia
- Home Office Eventual

#### Regime
- CLT

#### Nível
- Sênior

**Comment by ErikGMatos** [comment]
Muito tentador 😁

**Comment by brulucenacord** [comment]
Chegue mais! :)

**Comment by fabiomirandaa** [comment]
Pena que é remoto só durante a pandemia

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by brulucenacord** [comment]
Ainda estamos contratando (:

Em dom., 21 de mar. de 2021 21:19, Felipe Fialho ***@***.***>
escreveu:

**Comment by JordanaNadur** [comment]
em anexo curriculo

Em seg., 22 de mar. de 2021 às 22:05, Bruna Lucena ***@***.***>
escreveu:
