### ISSUE TITLE
[Remoto] Front-End Developer JavaScript/React Sr. na Eskolare

### ISSUE THREAD

**Issue by vrbarros** [frontendbr/vagas#4089]
## Nossa empresa

Somos uma startup do setor de educação com 3 anos de vida, equipe com grandes realizações e experiências no setor, algumas rodadas de investimento e futuro promissor! Estamos em busca de um novo membro para nosso squad de front-end para trabalhar na consolidação da nossa plataforma.

Nosso stack de tecnologia é composto por Python/Django, Django REST Framework, AWS (utilizamos 100% de CloudFormation no gerenciamento da infraestrutura) e nossa aplicação core está 100% no AWS Lambda e AWS RDS Aurora (sim, somos extremamente escaláveis!). No front-end temos JavaScript/React suportando mais de 40.000 usuários atualmente, tanto no desktop quanto no mobile.

## Descrição da vaga

Para a vaga, esperamos que o novo membro se engaje em:
- Implementação do Next.js, consideranda a transição da aplicação atual para a nova estrutura
- Otimização de códigos, refactoring e testes para garantir estabilidade da plataforma
- Identificação, análise e resolução de bugs
- Estabelecer padrões e boas práticas de desenvolvimento que ajudem na manutenção do produto
- Proponha novas tecnologias ou soluções para os problemas complexos que enfrentamos
- Precisamos melhorar a performance de carregamento de nossas aplicações, utilizando abordagens como code splitting e carregamentos assíncronos de componentes e containers
- Manter o projeto atualizado com todas as suas dependências

## Local

Remoto

## Requisitos

**Obrigatórios:**
É fundamental ter experiência com JavaScript e React (principalmente Next.js), e ter algum projeto publicado para apresentação durante a entrevista. Vamos explorar aspectos como:
- Lógica e estratégia na resolução do problema, além da arquitetura da solução
- Domínio do React e compreensão das possibilidades, abordagens e limitações
- Comunicação e interação com outros membros da equipe
- Antecipação de testes e visão de negócios
- Boas práticas e padrões de projeto que foram adotados
- Esperamos que esteja com muita vontade de aprender, pois estamos aprendendo algo novo todos os dias e tenha vontade de compartilhar seus aprendizados também.

**Diferenciais:**
- Experiência em projetos anteriores implementando com Next.js qualquer solução
- Atuação em projetos que envolvam e-commerce ou marketplace

## Benefícios

- Adicional de R$ 500/mês

## Contratação

R$ 13k/mês PJ e potencial Equity (à combinar)

## Como se candidatar

Por favor aplique através da [AngelList](https://bit.ly/2K9v6X1)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dia após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by vrbarros** [comment]
@felipefialho a vaga continua aberta sim.
