### ISSUE TITLE
[Remoto/USA] Lead Frontend Engineer at Ubiminds

### ISSUE THREAD

**Issue by Ubiminds** [frontendbr/vagas#4090]
## Nossa empresa

Join a company where you’ll find an engineering team that is committed to overcoming obstacles and continually making forward progress.

Are you passionate about the idea of being part of a company in early stages and the opportunity to build a whole new product? Come join our team and lead the creation of a new frontend application and drive key decisions around architecture, framework, tooling, and library selection.

## Descrição da vaga

**What you’ll do**
* Contribute as a key member of a multidisciplinary scrum team to deliver an amazing product experience to our users.
* Assure that the team makes technical decisions with the goal of enabling rapid delivery.
* Support the team in making active decisions about when to incur technical debt based on the value of speed vs the ongoing cost of the debt.
* Provide mentorship to less experienced team members.
* Set an example and advocate for unit and integration testing best practices across the frontend engineering organization.
* Be an advocate for accessibility best practices in collaboration with the entire product delivery organization.

## Local

Remote, working full-time with a USA team from Brazil. 

## Requisitos

**Cultural fit:**
* People First. We are all about people!
* Challenge yourself. There’s always room for improvement and continuous improvement is in our essence.
* Make it happen. Be ready to take challenges as they come. It’s all about attitude and commitment. 
* We’re in this together. We work as a team, we thrive as a team and we evolve as a team.
* Averaging on awesome. We work hard to deliver high-quality services and look forward to exceeding expectations. 
* Keep it real. We promise you honesty, transparency, and openness, regardless of the situation.

**Mandatory skills:**
* Advanced/fluent English skills – Excellent written and verbal communication skills.
* Significant production experience with modern frontend applications built on.
* React/Redux.
* Solid background in JavaScript language fundamentals.
* Experience building responsive and accessible consumer-facing web applications.
* Deep expertise in core web specifications like CSS and HTML as well as their variance across browsers.
* Experience with test frameworks and technologies. 

**Non-technical skills:**
* Experience leading technical discussions with technical and non-technical stakeholders to make the right tradeoffs for the business.
* Grit to work through any challenges we may face while developing the product.
* Willingness to work across system boundaries to take a look at datastores or backend services implementations as needed to continue to make progress.

## Benefícios

**As a Lead Frontend Engineer @Ubiminds, you:**
* Are placed in a product-based company, with the same treatment as their full-time employees.
* Have our full back-office support, from career guidance to HR and concierge services.
* Choose to work remotely or at our office – we are a distributed team, after all.
* Get your own MacBook (none of that BYOD stuff here).

Plus, when we’re back from COVID-19 lockdown:
* Tasty snacks, soft drinks & booze at our HQ
* Trips to Florianopolis every few months
* Weekly massage if you choose to stay in Floripa
* Financial support to take part in conferences, meetups, and relevant events

## Como se candidatar

Apply here: https://ubiminds.com/job/lead-frontend-engineer-react-redux/

## Tempo médio de feedbacks

We send feedbacks as soon as possible. Right after your application, you'll receive an e-mail confirming your participation in the process. 

#### Regime de contratação

To be settled.

#### Nível

Tech Lead or Architect.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
