### ISSUE TITLE
[Remoto] VueJS ou VueX Front-end Developer na ília Digital

### ISSUE THREAD

**Issue by thayssa-radmylla** [frontendbr/vagas#4094]
**Sobre a ília Digital**

A ília digital é uma empresa de tecnologia especializada em simplificar as interações entre pessoas, produtos e serviços por meio de tecnologia e design.

Mais de 100 times dedicados a construir produtos digitais nos permitiram evoluir nosso método interativo e cocriativo. Toda a nossa experiência fez com que construíssemos um modelo próprio de framework adaptado do ágil.

Nosso propósito é tornar o mundo surpreendentemente mais simples, compartilhando uma cultura transformadora!

Estamos no Brasil e atendemos a uma variedade de clientes premium nas Américas e na Europa. Nos concentramos em três principais setores: serviços financeiros, mobilidade e seguros. Cada dia mais conquistamos novos espaços e estamos estabelecendo uma subsidiária também na Espanha.

**O que você precisa para fazer parte do nosso time?**
• Experiência em desenvolvimento com VueJs;
• Conhecimento consolidado com Javascript es2018+;
• Conhecimentos consolidado com consumo de APIs;
• Conhecimentos de estado em aplicações SPA;
• Implementação de layout Web/Mobile Responsivo;
• Conhecimentos com práticas de processo de desenvolvimento tais como GitFlow e Code Review.

**O que pode te diferenciar:**
• Conhecimento consolidado com implementação de testes;
• Conhecimentos em Testes unitários;
• Experiência em alguma metodologia ágil como Scrum e/ou Kanban e uso do JIRA;
• Inglês avançado (fala, escrita e leitura).

**Benefícios e Incentivos**
- Assistência Médica e Odontológica extensivo aos dependentes;
- Vale Refeição/Alimentação;
- Programa de Incentivo ao inglês com atividades de mentoria e prática da língua;
- Programa de premiação a indicação de outros profissionais;
- Fóruns Técnicos: Neles o time compartilha práticas, estudos, projetos, ideias etc;
- Grupos de Chapter: Reúnem pessoas com skills similares para compartilhamento de ideias, práticas e experiências; 
- Seu Niver, seu bolo!
- Byod: Alugamos o seu notebook pessoal (valor mensal) ou disponibilizamos uma máquina da empresa (livre escolha).

**Alocação**
- Temos as seguintes modalidades na ília - 100% remoto ou híbrido com escritórios em Brasília e  São Paulo (após a pandemia). Você escolhe!

**Regime**
- Contrato de Trabalho CLT - 40h semanais com jornada flexível.

**Nível**
- Pleno e Sênior. Temos 2 oportunidades em **aberto**.

**Como se candidatar**
É só cadastrar o seu currículo atualizado: https://ilia.gupy.io/jobs/566545

**Para tirar dúvidas:** https://www.linkedin.com/in/thayssa-radmylla-61b18a153/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by thayssa-radmylla** [comment]
Olá @felipefialho a oportunidade já foi fechada. Obrigada ;)
