### ISSUE TITLE
[Rio de Janeiro][REMOTO] Front-end Developer na Mídia 3 Tecnologia e Criação

### ISSUE THREAD

**Issue by adailsonaguiar** [frontendbr/vagas#4096]
## Nossa empresa

Soluções em Tecnologia, Design e Consultoria. Projetos customizados, planejados e estruturados visando uma experiência rica para seus clientes.
https://www.midia3.com.br/clientes.shtml

## Local

Remoto

## Requisitos

- Experiência React Native
- Experiência ReactJs

## Diferenciais
- Conhecimento em programação .NET C# 

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para oportunidades@midia3.com.br com seu CV anexado - enviar no assunto: Vaga ReactJS React Native

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by vachterberg1** [comment]
A vaga é para ReactJS e React Native mas são requisitos c# e angular?

**Comment by adailsonaguiar** [comment]
@vachterberg1 são diferenciais, ou seja, requisitos não obrigatórios.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
