### ISSUE TITLE
[São Paulo] Desenvolvedor Front-End - ABInBev

### ISSUE THREAD

**Issue by libanio** [frontendbr/vagas#41]
## Descrição da vaga

Vagas para Desenvolvedor FrontEnd (CSS, HTML, Angular, Java Script) - ZX Ventures, Disruptive Growth Unit of AB-Inbev

www.zx-ventures.com

Se você já está formado e tem interesse em trabalhar com desenvolvimento em um ambiente Startup , não deixe de enviar seu CV.
Perfil: Buscamos pessoas com espírito empreendedor e que procuram rápido crescimento profissional, trabalhando alavancado com métodos ágeis em um time de alto nível. Queremos desenvolvedores com ótima formação e poder de execução para compor nosso time de desenvolvimento no escritório de São Paulo.
## Local

Itaim - São Paulo
## Benefícios
- Bonificações acima da média do mercado ($$$)
- Ambiente Startup
- Happy Hour com Open Bar de cerveja artesanal/importadas/especiais :dancer :D
- Vale refeição
- Plano de saúde
- Flexibilidade de horário
- Trabalhar com profissionais (incluindo desenvolvedores) de altíssimo nível
## Requisitos
- já formado em faculdades de referência (USP, ITA, UNICAMP, UNESP, ...)
- experiência em desenvolvimento FrontEnd (CSS, HTML, Angular, Java Script)

**Obrigatórios:**
- Formado
- ao menos 2 anos de experiência em FrontEnd

**Desejáveis:**
- inglês intermediário/avançado
- formação preferencialmente em áreas relacionadas a exatas (computação/matemática...)  
- espírito empreendedor
- conhecimento em SCRUM / XP
- conhecimento em Design Patterns
- noções de User Experience (UX)
- noções de User Interface (UI)

**Diferenciais:**
- projetos de alto nível no portifólio
## Contratação
- CLT
## Nossa empresa

O Grupo AB-InBev, maior grupo cervejeiro do mundo e uma das maiores empresas de bem de consumo do mundo, está iniciando uma nova área denominada Disruptive Growth que tem o intuito de trazer novas tecnologias e inovação disruptiva ao grupo gerando impacto global.
Ambiente de trabalho: Estamos dentro de uma das maiores empresas do mundo com profissionais bastante experientes, porém prezamos por um ambiente descontraído, com horários flexíveis, remuneração meritocrática, hierarquia reduzida e muito espaço para novas idéias. 
## Como se candidatar

Por favor, envie um email para diego.libanio@ambev.com.br com seu CV anexado.
Enviar como assunto: Vaga ZX - FrontEnd.

**Comment by LFeh** [comment]
Vaga bacana.

Boa sorte @libanio ;)

**Comment by LFeh** [comment]
@libanio A vaga foi preenchida?

**Comment by eduardojmatos** [comment]
@libanio a vaga foi preenchida? Se puder nos avisar pra removermos ou mantermos aqui seria uma boa! :)

**Comment by libanio** [comment]
Temos vagas ainda

**Comment by LFeh** [comment]
Ainda?

**Comment by CesarNobre** [comment]
sim, ainda!

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
