### ISSUE TITLE
[São Paulo] Front-End Developer / React no Mercado Livre

### ISSUE THREAD

**Issue by gfelizola** [frontendbr/vagas#410]
## Descrição da vaga

Galera, temos vagas para desenvolvedores aqui no Mercado Livre

## Local

[Melicidade](https://www.youtube.com/watch?v=9mB5ohJPsgE), São Paulo/Osasco

## Benefícios

- refeitório/cafeteria
- vale alimentação (vale mercado)
- vale transporte / fretado / vale combustível (R$ 700,00)
- estacionamento
- sala de jogos (ping pong / toto / playstation / xbox )
- academia sem custo (Bio Ritmo)
- massagem sem custo
- **bonificação anual de até 3 salários**

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Node
- 1 anos de experiência com React
- 5 anos de experiência em Front-End (html, css, javascript, pre-processadores, task-runners)

**Desejáveis:**
- conhecimentos em Java
- ter trabalhado com e-commerce é um bom diferencial

## Contratação

CLT (salário a combinar)

## Nossa empresa

No Mercado Livre estamos democratizando o comércio e os pagamentos na América Latina.

Tecnologia é a essência de nosso produto. Equipes integradas de desenvolvedores, arquitetos, especialistas em banco de dados, experiência do usuário, inteligência de negócios, cocriam e são responsáveis pela principal plataforma para e-commerce da América Latina e um dos lugares de maior tráfego em todo o mundo. Em uma indústria que se reinventa diariamente, os profissionais de TI do Mercado Livre são reconhecidos por sua visão e liderança. De aplicações móveis a aprendizagem de máquina, a nossa inovação tem um foco claro: facilitar a vida do usuário, de modo que se possa comprar e vender com a melhor experiência.

## Como se candidatar

Por favor envie um email para gustavo.felizola@mercadolivre.com com assunto assunto: Vaga Front-End e: 
 - seu CV anexado
 - linkedin (obrigatório)
 - github (opcional)

**Comment by rubenmarcus** [comment]
@gfelizola  tem vaga pra pleno? eu moro 30min apé do ML. Eu tava passando no processo dessa vaga, mas ainda não consegui terminar o teste. Acho que consigo fazer o teste em Node puro e React mas não tenho 3 anos de Node e nem 1 ano de React. só os 5 anos de front. 
Mas é uma empresa que sempre quis trabalhar.

**Comment by gfelizola** [comment]
@rubenmarcus, a gente precisa de maiores conhecimentos em React do que Node.
O Node é interessante pra configurações de ambientes e APIs que usamos aqui.
A gente manda um teste pros candidatos e consegue avaliar a capacidade necessária pra Pleno ou Senior.

**Comment by gfelizola** [comment]
@LFeh pode adicionar o label Pleno também?
Estamos com vagas para plenos e seniors

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by gfelizola** [comment]
Temos novas no mesmo cenário.
Acha melhor manter esse ou criar uma nova?

**Comment by LFeh** [comment]
Se quiser pode criar uma nova! Ai fecha essa :)

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
