### ISSUE TITLE
[Rio de Janeiro] Front-end Developer na IK Solution

### ISSUE THREAD

**Issue by VANESSAGIRARDI** [frontendbr/vagas#4101]
> Vaga Remota durante a pandemia

## Descrição da vaga

Projeto em Node Js, Vue Js e React

## Local

[Rio de Janeiro], [RJ], [Barra da Tijuca]

## Requisitos

**Obrigatórios:**
- Experiência com Node Js
- Experiência em React
- Vue Js

## Benefícios
- Plano de saúde
- VR
- VA

## Contratação
CLT
Por favor envie um email para vagas@iksolution.com.br com seu CV anexado - enviar no assunto: Vaga FE

**Comment by Ruttmann** [comment]
Poxa, pelo menos preenche direito o template...

**Comment by VANESSAGIRARDI** [comment]
Desculpa, é a primeira vez que uso o Github, estou meio perdida ainda.
Vc consegue me ajudar?
Atenciosamente,

*Vanessa Girardi*
*Girardi - Psicologia & Consultoria*
*girardipsivanessa@gmail.com <girardipsivanessa@gmail.com>*




Em qui., 14 de jan. de 2021 às 11:00, Marlon Erich Ruttmann <
notifications@github.com> escreveu:

**Comment by cleitonosilva** [comment]
Vanessa bom dia! 
Se ainda tiver alguma dúvida, posso ajudar !

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
