### ISSUE TITLE
[Remoto/ Alphaville] Front-end Developer na ITeam

### ISSUE THREAD

**Issue by VivianeRHTI** [frontendbr/vagas#4102]
## Local

Local de trabalho: Inicialmente remoto e após pandemia, semipresencial (2 a 3 vezes na semana) na região de Alphaville - Barueri/SP.

## Requisitos

Experiência com React (JSX), Javascript (ES6), Sass, Less, TypeScript
Aplicações Web Mobile / Webview (Android e IOS)
Experiência em consumo de API (RESTfull)
Produção de telas e recortes HTML, Responsive Web Design
Pacote Adobe (Photoshop, XD, Illustrator)
Experiência em projetos Web (Hotsites, Intranets, E-commerces e Integradores)
Continuous integration, Controle de Versão (GIT)
Swagger, Postman e metodologia Scrum.

## Contratação

Tempo indeterminado
PJ ou outro modelo á combinar.

## Nossa empresa

Há mais de 15 anos presente no mercado, a ITeam oferece o comprometimento com o cliente.
Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 
O relacionamento da ITeam é baseado no amplo comprometimento com os valores e objetivos dos nossos Clientes, fornecendo soluções e serviços de TI que contribuam para a realização de seus objetivos.

## Como se candidatar

Envie um e-mail para viviane.pereira@iteam.inf.br com seu currículo atualizado e pretensão de taxa/hora - enviar no assunto: Vaga no GITHUB - Front-End React - Remoto/Alphaville

## Labels

- 🏢 Horário comercial
- 🏢Remoto e semipresencial
- 👨 Pleno
- 👴 Sênior
- ⚖️ PJ ou á combinar

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
