### ISSUE TITLE
[São Paulo] Front-end Developer React na Multinacional Francesa

### ISSUE THREAD

**Issue by Patricia-MaithaTech** [frontendbr/vagas#4105]
## Nossa empresa

Empresa multinacional francesa, sendo uma das maiores redes de varejo no Brasil.

## Descrição da vaga

A empresa e o time estão em grande expansão, sendo atualmente responsável pelo Site, Ecommerce, Plataforma de Vendas das Lojas e APP. O profissional de front-end irá atuar com React, além do time sempre inovar com as novas stacks. 

## Local

Próximo a estação Campo Belo (após pandemia), São Paulo/SP.

## Requisitos

**Obrigatórios:**
- HTML5
- CSS
- React
- JavaScript (ES6)

**Diferenciais:**
- Testes automatizados

## Benefícios

- Plano de saúde
- Plano Odontologico
- Vale Refeição/Refeição no Local
- Prêmio de Participação nos Lucros e Resultados;
- Vale Transporte;
- Descontos na Compra de Produtos da Loja;
- Seguro de Vida em Grupo;
- Empréstimo Consignado em Folha de Pagamento;
- Kit Material Escolar para Filhos de 3 a 17 anos de idade;
- Cartão Farmácia;
- Gympass.

## Contratação

CLT

## Como se candidatar

Contato via Linkedin: https://www.linkedin.com/in/patriciapcarrillo/ ou envie um e-mail para patricia@maitha.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor Front End React

#### Alocação
- Remoto (em período de pandemia), após será presencial

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
