### ISSUE TITLE
[REMOTO] Front-end Developer na TamoVip

### ISSUE THREAD

**Issue by angelocerqueira** [frontendbr/vagas#4107]
## About TamoVip: 
Everybody has an idol. But how many of us would have a chance to get the personal attention of the ones we admire? TamoVip provides a meaningful connection creating an emotional experience and a timeless gift. For celebrities it means a new way to engage their audience and a new source of income, even for small digital influencers. 

We are currently looking for a Senior Front-End Software Developer with 4+ years of experience as front-end engineer working with TypeScript React to join our team. We accept CVs in English, Portuguese or Spanish.

## Software Developer responsibilities at TamoVip:

Improve the development experience at TamoVip by enhancing development tools, test coverage, and/or code structure;
Participate actively in discussions and decisions of software design. Building and helping to create documentations;
Help organize software architecture to harmonically orchestrate our services architecture.

### What we are looking for:

* Strong understanding of Typescript, React, Next10;
* Styled Components;
* Server Side Rendering;
* Experience using RESTful APIs;
* People that are seeking to learn and deliver real impact through high-quality data-driven and structured software, valuing work-life balance;
* Fluency in Portuguese and knowledge in English - we usually use English to write our code, documentation, tools, reference materials and eventually talk to partners and co-workers from other countries;
* Strong problem-solving skills;
* Create tests of developed features;
* Build reusable components for our design system.

### You'll stand out if you:

* Understand how modern CD/CI works;
*Know how to test and tune scalability;
* Understand the work is never done; we are always taking care and evolving our services;
* Understanding the AWS fundamentals;
* Socket.io. 

## We offer:
* Paid vacation days;
* Competitive compensation depending on experience and skills;
* PJ; 
* This is a remote position.

## Como se candidatar

Por favor envie um email para ac@tamovip.com com seu CV anexado - enviar no assunto:  Senior Front-end Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dias após cada processo.
E-mail para contato em caso de não haver resposta: ac@tamovip.com.

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
