### ISSUE TITLE
[Remoto] Front-end Developer na Arena

### ISSUE THREAD

**Issue by rodrigoreis22** [frontendbr/vagas#4115]
## Nossa empresa

O [Arena](https://arena.im/) é uma plataforma para sites de notícias e esportes cobrirem eventos em tempo real utilizando conteúdo de redes sociais e inteligência artificial.

A empresa foi fundada nos Estados Unidos em 2016 por dois desenvolvedores brasileiros, e hoje conta com milhões de usuários em 86 países, com investimento do Vale do Silício.

Saiba mais sobre nossa história nos links abaixo:
https://exame.com/pme/startup-de-marketing-criada-por-brasileiros-nos-eua-recebe-r116-milhoes/

## Descrição da vaga

- Desenvolver com alto padrão focado em entregas de software de qualidade com cobertura de código, testes automatizados, integração contínua, etc.;
- Trabalhar em conjunto com o time de back-end para definição de APIs e modelo de dados;
- Criar e definir arquitetura do software focando em reusabilidade, clareza e testabilidade, bem como a criação de padrões e bibliotecas internas;
- Participar da modelagem de APIs REST e GraphQL, bem como, garantir a aplicação de boas práticas na criação de aplicações Híbridas ou SPA’s.

## Local

Remoto

## Requisitos

**Obrigatórios:**
Por favor, só se candidate se você atende/tem experiência com:

- Mínimo de **2 anos de experiência** **profissional** com desenvolvimento front-end (bootcamps não são considerados como experiência profissional)
- 2 anos de experiência **profissional** com ReactJS ou outro framework/lib moderno (Angular, VueJS)
- Testes unitários, de integração e de interface (usamos o Jest e Cypress)
- Básico de bundlers e build tools: Webpack, Babel, Rollup, Parcel, NPM, Yarn
- Styled Components
- Apollo GraphQL
- Github/Gitflow
- HTML/CSS, responsive design

**Desejáveis/Diferenciais:**
E abaixo segue mais tecnologias da nossa stack. Caso você tenha experiência em uma ou mais dessas tecnologias será considerado um **plus**:

- TypeScript
- Prettier/ESLint
- AWS Lambda/Serverless framework
- Google Firestore/Firebase
- Socket.io
- Cloudflare
- Gatsby
- Lighthouse
- Service Workers
- PWA
- Mobile: Flutter
- Back-end: NodeJS, MongoDB, Postgres, Redis, AWS, Docker

🇺🇸  É fundamental também possuir inglês intermediário/avançado, conseguir ler e escrever bem (toda nossa comunicação escrita é em Inglês).

## Benefícios

- Bônus de performance a cada 3 meses
- Férias remuneradas de 3 semanas por ano
- Oportunidade de viagem para nossa sede no Vale do Silício com todas despesas pagas (pós-pandemia)

## Contratação

PJ

## Como se candidatar

1. O nosso processo seletivo começa na inscrição! Se você está realmente interessado(a) em fazer parte do nosso time, capriche nessa etapa do processo. Nós analisamos todos os candidatos individualmente ~ sim, lemos todas as candidaturas 😎.
2. Toda comunicação é feita por e-mail, então fique atento às nossas mensagens e libere o domínio @arena.im para nossos e-mails não irem parar no spam.

Se interessou? [Inscreva-se aqui](https://airtable.com/shryVTxwsEJ2SXj4Z)

## Tempo médio de feedbacks

Geralmente leva em torno de 30 dias (desde a aplicação até o final do processo) e contém as seguintes etapas:

1. Aplicação
2. Avaliação técnica (testes online e take home challenge)
3. Entrevista com o time/gestor
4. Offer :)

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by ItaloCanturil** [comment]
O que é experiência **profissional** para você?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by JordanaNadur** [comment]
Boa noite

Tenho interesse em participar da empresa.

Obrigada
Att,

Em qui., 18 de mar. de 2021 às 21:15, Felipe Fialho <
***@***.***> escreveu:
