### ISSUE TITLE
[Remoto] Front-end Developer na Trinca

### ISSUE THREAD

**Issue by Gabrielarochay** [frontendbr/vagas#4121]
Temos uma vaga para Front-end Developer aqui na Trinca! É importante que você tenha sólida experiência em projetos digitais (web e mobile), seja versátil na utilização de tecnologias, detalhista, exigente com qualidade, autodidata e que valorize acima de tudo o trabalho em equipe.

// Habilidades que você precisa ter:
Conhecimento sólido em Javascript e ReactJS;
• Conhecimentos em arquitetura e engenharia de software;
• Conhecimentos em teste unitários
• Conhecimento em metodologias ágeis
• Desejável conhecimento de UI/UX  
• Conhecimento de teste unitário e/ou e2e  

// Contratação: PJ
// Nível : Pleno 

Saiba mais sobre a nossa Cultura: https://www.trin.ca/cultura
Gostou? Envia teu currículo para jobs@trin.ca :) 

![Trinca - Front End React Square](https://user-images.githubusercontent.com/66493175/104959519-23d24b80-59b1-11eb-8785-7dcf47e86af6.jpg)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
