### ISSUE TITLE
[SÃO PAULO/SP] Front-end Developer na BrasilPrev

### ISSUE THREAD

**Issue by aliveiga** [frontendbr/vagas#4122]
[OPORTUNIDADE] [PRESENCIAL] [SOFTWARE DEVELOPER FRONT-END]

A ECTP é uma empresa com presença Global no comércio commodities, foi fundada em 2013 pelo Grupo BTG Pactual, possuindo  uma forte estrutura de risco além de ampla experiência de  traders em todos os segmentos do mercado.

Neste momento estamos precisando de um Software Developer Front-End para compor seu time, projetando e aprimorando os métodos de integração dos sistemas da empresa e automatizando processos e funções para melhorar a operação.

Requisitos principais: Angular, React, C# (diferencial) + Inglês intermediário

Contratação CLT + benefícios

https: https://byintera.in/ectpctfe

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
