### ISSUE TITLE
[Remoto] Front-end Developer na Levee

### ISSUE THREAD

**Issue by maiconpazin** [frontendbr/vagas#4124]
## Descrição da vaga

Levee é uma empresa nascida no Vale do Silício, Califórnia/EUA, e que atende grandes clientes dentro e fora do Brasil.

Do recrutamento e seleção até a coordenação de entrevistas e contratação, a plataforma da Levee otimiza os processos humanos adicionando automação e inteligência artificial a cada etapa do processo, para que nossos clientes possam contratar a pessoa certa para a vaga certa, e assim, evoluir o negócio mais rápido.

Estamos em busca um novo integrante para nosso time de builders que seja apaixonado por desenvolvimento de software com qualidade e escalável.

Nosso stack envolve:
- Javascript (React/Next.js, Vue.js/Nuxt.js, Node.js)
- Ruby on Rails
- Go
- Python
- Android
- PostgreSQL
- Ops (AWS, Docker, Librato, CircleCI)
- RabbitMQ

## Local

100% Remoto

## Benefícios

- Plano de carreira
- VR de 33 reais/dia (pode ser dividido com o VA)
- Plano de saúde e odontológico Sulamérica integral extendido para dependentes e cônjuge
- Seguro de Vida
- Auxílio creche
- Auxílio estudo
- Parceria com o SESC

#### Diferenciais

- Opção de macbook ou notebook fornecido pela empresa
- Horário flexível
- Ambiente descontraído e informal
- Acesso a coleção de livros digitais da O'Reilly
- Acesso a plataforma Open English

## Requisitos

**Obrigatórios:**
- Sólida experiência com projetos reais em React e/ou Vue.js
- Experiência com TypeScript
- Criação de APIs com Node e Express
- Facilidade na criação de interfaces responsivas
- Boas noções de UX
- Práticas com otimização de sites (SEO)
- Testes unitários e de integração

**Desejáveis:**
- Experiência com GraphQL
- Redux e Next.js (SSR)
- Vuex e Nuxt (SSR)
- Experiência prévia com PWA
- CSS3 e Pré-processadores como Stylus e SASS
- Webpack
- ESLint e Prettier
- Ter facilidade de trabalhar em times multidisciplinares
- Produzir código limpo e com boas práticas
- Oh, I almost forgot, you will read and write English a lot, then you do not need to be fluent, but your code, Pull Requests and other discussions should be done in English

**Diferenciais:**
- Ruby (Rails) ou Go
- Conhecimentos de arquitetura de microsserviços
- Vivência em times ágeis com SCRUM

## Contratação

CLT

## Nossa empresa

Fundada em 2012, a Levee é uma empresa brasileira de tecnologia, que aplica Machine Learning, Análise Preditiva e People Analytics para melhorar os índices de eficiência, produtividade e engajamento dos colaboradores, em empresas com altos volumes de contratação de mão de obra operacional.

Premiada pelo MIT, a Levee conecta pessoas, processos e dados para atender a demanda de setores complexos, como varejo, que enfrentam problemas de alta rotatividade, absenteísmo e baixa produtividade.

Mais informações sobre a Levee:
- https://levee.com

## Como se candidatar

Enviar currículo para o e-mail: engenharia@levee.com.br

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dia após cada processo.

## Labels

- Remoto
- CLT
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
