### ISSUE TITLE
[Criciúma/SC ou Remoto] Frontend Developer na Central do Frete

### ISSUE THREAD

**Issue by xandyalexandrec** [frontendbr/vagas#4125]
## Descrição da vaga

Você poderá trabalhar em projetos utilizando a stack React com Material Design UI e GraphQL
O produto é uma plataforma para cotações de frete para empresas, através da plataforma em poucos segundos você consegue descobrir quais são as transportadoras que atendem uma origem/destino e contratar o frete através da plataforma.
Utilizamos Jira e Discord para organização e comunicação, usando kanban como metodologia. 

## Local

100% remoto

## Requisitos

**Obrigatórios:**
- Ter muita experiência com React e seu ecossistema.
- Ter experiência usando Material Design UI
- Ter noções de Design e resolução de problemas.

**Desejáveis:**
- conhecimentos em GraphQL
- conhecimentos usando Figma

**Diferenciais:**
- ter experiência como UX/UI designer
- ter experiência com PHP e Laravel

## Contratação

PJ a combinar

## Nossa empresa

Nós somos uma startup de tecnologia que está transformando a maneira como as empresas contratam fretes.

Em um mundo onde descomplicar é a palavra de ordem, chegamos para criar uma experiência mais satisfatória tanto para quem compra quanto para quem vende.

Contratar um frete pode ser mais fácil: nosso sistema seleciona as melhores transportadoras, você compara, contrata, faz o pagamento e consegue rastrear a carga.

Tudo em um só lugar. Fácil assim.

Acreditamos em fretes menos complicados, em vendedores menos preocupados e em clientes mais satisfeitos.

https://centraldofrete.com/

## Como se candidatar

Etapa 1: Preencher o formulário: https://forms.gle/zRFFTUpVMMyK52pZ9
Etapa 2: Desafio técnico
Etapa 3: Chamada de vídeo

## Labels

- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ PJ
- 💰 5k-10k

**Comment by xandyalexandrec** [comment]
Up

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
