### ISSUE TITLE
[Remoto/Recife] Full-stack developer na MB Sistemas

### ISSUE THREAD

**Issue by brunomunizaf** [frontendbr/vagas#4127]
## Requisitos

**Obrigatórios:**
- Experiência com Node
- Experiência com Angular
- Experiência com MySQL

**Desejáveis:**
- Conhecimentos em Rails
- Conhecimentos em Cypress

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para contato.mbsistemas@gmail.com com seu CV anexado - enviar no assunto: Vaga Full-stack

![Uploading WhatsApp Image 2021-01-19 at 19.17.33.jpeg…]()

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
