### ISSUE TITLE
[Remoto] Desenvolvedor(a) de front-end | Pleno/Sênior na empresa MaisMei

### ISSUE THREAD

**Issue by mateusw3c** [frontendbr/vagas#4130]
## Descrição da vaga

Somos o MaisMei. Nascemos para auxiliar o microempreendedor individual a gerenciar seu negócio, além de permitir pagar e acompanhar o status das guias de pagamento DAS de forma simples e muito organizada através de uma plataforma (web e aplicativos) segura e fácil de usar.

Até hoje já ajudamos mais de 188 mil empreendedores em todo o Brasil a manterem seus MEIs regulares e formalizamos mais de 3.500 mil negócios! Mas queremos alcançar muito mais! E para isso estamos buscando um(a) profissional com ótimas skills em front-end e alinhado(a) com nosso propósito. \o/

## Quais serão seus desafios e responsabilidade?

- Entender muito bem os requisitos e escrever código simples e claro; 
- Manter o sistema e aplicativos sustentáveis para grande escala e performance; 
- Trabalhar no processo de construção de soluções front-end, o que envolve projeto, requisitos, execução, manutenção e suporte.

 
## O que é indispensável para a vaga?
- Conhecimentos de HTML, CSS e JS;
- Experiência com React Native;
- Conceitos de componentização;
- Consumo de API's; 
- Conhecimentos em controle de versão (git);

## O que mais a gente adoraria ver?
- Experiência com Expo para aplicativos;
- Jquery para algumas LPs Web.

## Informações Adicionais
- Toda a equipe trabalha remotamente e com horário flexível;
- Somos uma nova startup e você irá participar de muitas coisas que serão novas também para nós;
- Sua experiência e skills vão moldar muito dos padrões e tecnologias que usaremos em nosso front;

## Informações Adicionais
https://www.maismei.com.br

## Local
Remoto

## Contratação
PJ a combinar

## Como se candidatar
Aplicação via Linkedin [https://www.linkedin.com/jobs/view/2373685942](https://www.linkedin.com/jobs/view/2373685942)

## Labels
- 🏢 Flexível
- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ PJ

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
