### ISSUE TITLE
[SÃO PAULO] Front-end Developer na Hubert

### ISSUE THREAD

**Issue by mariapaulacarvalho** [frontendbr/vagas#4132]
> Vaga Remota ou alocado 

## Nossa empresa

Que tal aceitar o desafio mais incrível da sua carreira?
A Hubert Administração de Condomínios e Imóveis, que atua há 65 anos no setor imobiliário está em busca de Pessoas desenvolvedoras Front-End para, junto com seu time, oferecer seus clientes produtos inovadores, mais completos e eficientes para facilitar e agilizar a gestão do negócio!

Temos uma estrutura robusta de atendimento dedicado com especialistas em diversas áreas, sistema tecnológico próprio que permite customização e agilidade e um conhecimento adquirido ao longo dos anos utilizado para oferecer serviços a diferentes setores como condomínios comercias, residenciais, associações ou investidores imobiliários.

Estamos em busca de pessoas curiosas, otimistas, proativas, empreendedoras, que querem aprender, fazer e acontecer do jeito certo com transparência, ética e jogando como um só time! Se quiser saber mais sobre esse desafio só clicar no link https://vagas-emb.byintera.com/1-k

## Descrição da vaga

Exemplo: Projeto bazinga em NodeJS, etc.

## Local

Remoto ou Escritório, [SÃO PAULO]

## Requisitos

**Obrigatórios:**
- Experiência com React e Angular
- Realizar análises, correções, implementações de funcionalidades, integrações com outras plataformas e codificações de novos sistemas, 
- Investigar e resolver bugs reportados ou identificados, 
- Avaliar especificações, 
- Discutir arquitetura e implementar funcionalidades, 
- Implementar testes unitários para garantir qualidade das funcionalidades implementadas.

**Diferenciais:**
-  Ninja Javascript (especificações mais recentes do ECMAScript), Proficiência em Typescript, 
- Proficiência em Angular (+2) e React, 
- Capacidade de copiar o layout desenhado pelo time UI/UX, 
- Git (branches, git flow), 
- Builders e ferramentas de comandos (webpack, angular-cli, create-react-app, expo-cli, nvm), 
- Experiência em Cloud e CI/CD

## Contratação

PJ a combinar

## Como se candidatar

Para se cadastrar é só preencher o formulário no link https://vagas-emb.byintera.com/1-k

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
