### ISSUE TITLE
[Remoto/São Paulo] Full-Stack developer PHP na empresa UpVarejo

### ISSUE THREAD

**Issue by maikelfb** [frontendbr/vagas#4134]
# Nossa empresa
UpVarejo é uma empresa de tecnologia focada em inteligência de gestão e ganho de produtividade para empresas do segmento de varejo. Este braço de tecnologia faz parte de um grupo com mais de 26 anos de experiência no segmento.

## Descrição da vaga
Atuação em projeto de Business Analytics que possui frentes de API, mobile e plataforma web, atendendo o segmento de Varejo no Brasil, com clientes superando mais de 5 bilhões de faturamento.

## Modalidade
Remoto ou Presencial em São Paulo / Zona Sul, próximo a estação Morumbi (Linha amarela, Via Quattro). 

## Regime
PJ

## Requisitos
- Mínimo de 3 anos como desenvolvedor PHP Laravel
- Framework Vue.js 
- API REST JSON
- Experiência com projetos Docker
- CSS, HTML, JavaScript
- Ajudar o time com soluções de alto nível para backend, frontend e banco de dados
- Experiência com times ágeis e SCRUM
- Experiência com AWS
- GIT

## Diferenciais
- Banco de dados Oracle
- Experiência com Microsserviços
- Experiência com DevOps

## Benefícios
- 30 dias de férias remuneradas

## Como se candidatar
Envie um e-mail com seu CV, links de projetos online e pretensão salarial para maikel@upvarejo.com.br com o assunto: `Vaga Full-Stack PHP`

## Tempo médio de feedbacks
Costumamos enviar feedbacks o mais breve possível após cada processo.

## Labels
- PJ
- Senior
- Pleno
- Remoto
- Presencial

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
