### ISSUE TITLE
[Lisboa] Technical Manager na Integer Consulting

### ISSUE THREAD

**Issue by raquelinteger** [frontendbr/vagas#4136]
# Integer Consulting

A INTEGER está à procura de um Technical Manager, capaz de analisar as necessidades da equipa, integrar informações e desenvolver soluções para cliente em Lisboa!

Perfil:
👉 conhecimentos sólidos de Java, Angular, Kafka e SOAP
👉 experiência em Cloud, Kubernetes e Docker
👉 fluência em Inglês

Se tens o amazINg tech talent pretendido e queres fazer parte da equipa INTEGER, responde a este anúncio com o teu CV atualizado para raquel.almeida@integer.pt📨

Participar neste projeto significa a integração numa empresa sólida em crescimento e num projeto num sector numa área estratégica e inovadora. #jumpIN

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
