### ISSUE TITLE
[Lisboa/Portugal] Angular Developer na Integer Consulting

### ISSUE THREAD

**Issue by AnaMargaridaAlmeida** [frontendbr/vagas#4137]
## Integer Consulting
# Ok para trabalho remoto durante a pandemia

A INTEGER, uma empresa de consultoria na área das tecnologias, com mais de uma década de presença no mercado português, está à procura de Angular Developer (M/F) com fortes habilidades de comunicação e sentido de responsabilidade e de trabalho em equipa.

Este pode ser o desafio perfeito para ti se tens:

Licenciatura em TI ou similar;
Experiência mínima de 3 anos com Angular2+;
Conhecimentos de TypeScript, Rest, CI/CD;
Inglês Avançado;

Se tens o amazINg talent pretendido e queres fazer parte da equipa INTEGER, responde a este anúncio com o teu CV atualizado para margarida.almeida@integer.pt.

Participar neste projeto significa a integração numa empresa sólida em crescimento e numa equipa jovem e dinâmica. #jumpIN

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
