### ISSUE TITLE
[Itajubá / MG] Front-end Developer no Grupo Bee

### ISSUE THREAD

**Issue by mattbrios** [frontendbr/vagas#4138]
## Nossa empresa

O Grupo Bee está no mercado brasileiro desde 2011 e faz parte da holding portuguesa Impacting Group que existe desde 2007. Somos uma empresa com DNA no marketing digital, e possuímos diversas plataformas de mídia e tecnologia que ajudam os clientes no entendimento e na otimização dos seus funis de conversão em todos os níveis do seu negócio. 

## Descrição da vaga

const requirements = {
  knowledge: {
    vcs: 'git',
    mandatory: ['HTML5', 'CSS3'] // domain required
    programmingLanguage: ['JavaScript'], //ES6 e TS are differentials
    frameworkFrontend: 'React', // Vue and Angular are differentials
    english: "If you can understand this requirements, you're fine"
  }
}

const Apply = (resume) => {
  SendEmailTo({
      email: 'vagas.ti@beeleads.com.br',
      attachment: resume,
      subject: 'Front-end Developer at Beeleads'
    })
}

## Local

Vaga para trabalho Alocado.
Escritório localizado no Centro de em Itajubá - MG

## Requisitos

**Obrigatórios:**
- Experiência com HTML, CSS e JavaScript
- Ter noções de ReactJS

**Desejáveis:**
- Ter projetos publicados em ReactJS

**Diferenciais:**
- Vue e Angular
- ES6 e TS

## Benefícios

- Plano de saúde
- VR de cerca de R$ 20,00/dia
- Bônus por desempenho geral

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um email para vagas.ti@beeleads.com.br com seu CV anexado - enviar no assunto: Front-end Developer at Beeleads

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Júnior

**Comment by mrangel-jr** [comment]
Tem a possibilidade de ser 100% remoto ?

**Comment by mattbrios** [comment]
Infelizmente não. Somente durante a pandemia.

**Comment by lucasfe4nor** [comment]
Enviado.

**Comment by sandrocarvalho10** [comment]
É para Itajubá ou São Paulo?

**Comment by mattbrios** [comment]
> É para Itajubá ou São Paulo?

Itajubá / MG
