### ISSUE TITLE
[Remoto] Front-End Developer na Droopi

### ISSUE THREAD

**Issue by agenciadroopi** [frontendbr/vagas#414]
labels: PJ, Remoto - Total, Júnior, Pleno

## Descrição da vaga

Projetos diversos para e-commerce, blogs e hotsites

## Local

Remoto ou Escritório,  Londrina - Gleba Palhano

## Benefícios

- Horário Flexível
- 100% remoto
- Comunicação via Slack ou Skype

## Requisitos

**Obrigatórios:**
- Experiência em HTML, CSS e JavaScript
- Conhecimento da biblioteca jQuery
- Conhecimento em framework Bootstrap
- Conhecimento em grid e design responsivo
- Utilização de padrões e boas práticas para desenvolvimento

**Desejáveis:**
- conhecimentos em PHP
- conhecimentos em plataformas de e-commerce

**Diferenciais:**
- experiência com VTEX

## Contratação

PJ a combinar
ou por Projeto

## Nossa empresa

[FINALIZADA]
Somos uma agência especializada em e-commerce e marketing digital localizada em Londrina - PR (operaciona) e Pinheiros - SP (escritório comercial).

## Como se candidatar

Por favor envie um email para rh@droopi.com.br com seu CV anexado e seus 3 melhores projetos de front (tema não vale) - enviar no assunto: Vaga Frontend

**Comment by gkal19** [comment]
Adorei a vaga! Me tornaria um candidato se eu soubesse um pouco mais de HTML e CSS

**Comment by adelmojnr** [comment]
Ótima vaga, pena que não tenho portfólio, vocês não teriam nenhum tipo de teste?

**Comment by RaphaAmericano** [comment]
Também tenho interesse sobre algum tipo de teste. Meu portfólio é pequeno.

**Comment by samuelsilvadev** [comment]
Um teste seria ótimo, pois no meu caso só tenho experiência com ERP's internos..

**Comment by gabrielferreiraa** [comment]
@agenciadroopi tenho os conhecimentos listados, porém os projetos que realizei são privados por conta da empresa que atuo. Um teste seria interessante.

**Comment by lucasbarrossantos** [comment]
@agenciadroopi tenho o perfil que procura, porém os projetos que realizei são privados por conta da empresa. Seria bom um teste. Enviei um projeto Open Source para o e-amil informado!

**Comment by LFeh** [comment]
Bela vaga :)

**Comment by jschneiders** [comment]
Enviei por e-mail. Um teste realmente seria muito bom.

**Comment by willrsousa94** [comment]
Me interessei pela vaga, será que teria um tipo de teste para realizar?

**Comment by IgorSousaFront** [comment]
Tenho os conhecimentos necessário, acredito que um teste seria uma ótima forma de filtrar os candidatos.

**Comment by agenciadroopi** [comment]
Obrigado pessoal, recebemos diversos ótimos currículos e selecionamos um profissional, por hora a vaga está preenchida. Excelente canal de divulgação, parabéns!

**Comment by ribeiroevandro** [comment]
Já trabalhei com a Droopi e recomendo muito, os caras são fantásticos e os projetos são irados...

**Comment by clautercarlos** [comment]
Fechar issue! :)
