### ISSUE TITLE
Vaga Programador com Experiência em Vídeos - "Ffmpeg"  - Home Office 

### ISSUE THREAD

**Issue by cristianpazdasilva** [frontendbr/vagas#4141]
Vaga com para programador com Experiência em Vídeos ""Ffmpeg". Interessados, enviar o questionário abaixo respondido para
webprogramdesen@gmail.com

Pretensão salarial:
Descrever experiência (Quantos anos) em desenvolvimento, listar projetos envolvidos:
Disponibilidade de horas por dia (em quais horários e dias:
Qual a experiência com trabalho remoto, home office:
Motivo do desligamento do último trabalho:

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
