### ISSUE TITLE
[Florianópolis] Pessoa Desenvolvedora Frontend Senior na Feedz

### ISSUE THREAD

**Issue by emersonsilva75** [frontendbr/vagas#4142]
## Nossa empresa

Somos uma das startups que mais crescem no mundo e temos como propósito criar ambientes de trabalho mais felizes

<https://materiais.feedz.com.br/quero-ser-parrot> 

## Descrição da vaga

Somos um time diverso, que cria soluções que impulsionam a felicidade no ambiente de trabalho. Essa vaga tem por objetivo fortalecer a nossa equipe e entregar experiências de impacto aos nossos clientes.

## Local

Remoto 

## Requisitos

**Responsabilidades e atividades**

- Desenvolver com HTML, CSS(SASS ou LESS), Bootstrap e Javascript usando os melhores patterns, práticas e clean code
- Entregar as experiências do time de design para nosso frontend
- Contribuir para o UX do produto
- Evoluir nosso ambiente de desenvolvimento com as melhores práticas e recursos
- Melhorar a performance e segurança do frontend
- Ajudar na construção e evolução de nosso Design System
- Implementar testes no frontend
- Realizar testes A/B
- Desenvolver tecnicamente seus pares
- Atualizar bibliotecas de desenvolvimento
- Estimar prazos
- Conectar o frontend com o backend(noção de PHP)

**Obrigatórios:**

- Senioridade no desenvolvimento frontend
- Ter conduzido projetos de implantação de frameworks de frontend
- Atuado no desenvolvimento de projetos com mais de 10 mil usuários

## Benefícios

    Vale-Alimentação/Refeição
    Vale-Transporte
    Plano de Saúde com Coparticipação Unimed
    Plano odontológico Nacional da Bradesco Dental
    Auxílio Parrot Feliz
    Auxílio Contas
    Ifood Office

## Contratação

PJ ou CLT a combinar

## Como se candidatar

Através de nossa página de carreiras - <https://materiais.feedz.com.br/quero-ser-parrot>

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
