### ISSUE TITLE
[Remoto] Fullstack Developer (100% Remote) na SolarView

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#4143]
## Descrição da vaga: 
 <p>A SolarView está buscando <strong>Fullstack Javascript e/ou PHP Laravel Developer</strong>. Não é necessário dominar todas estas tecnologias, se garantindo em alguma delas já está apto para tentar a vaga.</p>
<p>Nossos fundadores, parceiros e colaboradores compartilham da mesma paixão pela TECNOLOGIA, A ENERGIA E A SUSTENTABILIDADE. Acreditamos que estes conceitos estarão se relacionando e transformando cada vez mais o dia-a-dia de todas as pessoas e que através deles poderemos mudar significativamente o panorama da indústria brasileira.</p>

## SolarView: 
 <p>SolarView é a solução completa para a gestão de dados e informações relacionadas ao consumo e à produção de energia elétrica a partir de sistemas fotovoltaicos.</p>

<p>A SolarView é uma empresa do Grupo AWC, que desde 2013 dedica-se ao desenvolvimento de tecnologia nacional para mercados inovadores no país, como é o caso do mercado de geração distribuída fotovoltaica.</p><a href='https://coodesh.com/empresas/solarview'>Veja mais no site</a>

 ## Habilidades: 
 - Laravel 
- MySQL 
- PHP 
- React.js 
- GIT 
- Node.js 
- CodeIgniter 

## Local: 
 100% Remoto

## Requisitos: 
 - 1 ou mais anos de experiência em posição similar  
- Sólidos conhecimentos em lógica e programação orientada a objetos 
- Experiência em construir Back-end / Rest API Node.js ou PHP Laravel 
- Domínio em SQL  
- Habituado com scrum 
- Habituado com Git e controle de versão 
- Conhecimentos em React.js 

## Benefícios: 
 - 100% Home Office 
- Contratação PJ ou CLT

## Como se candidatar:
Candidate-se em: [Fullstack Developer (100% Remote) na SolarView](https://coodesh.com/vagas/fullstack-javascript-php-laravel-developer-122031?origin=github&modal=open)

## Tempo médio de feedbacks:
 Costumamos enviar feedbacks em até 48 horas após cada etapa do processo. E-mail para contato em caso de não haver resposta: [contato@coodesh.com](mailto:contato@coodesh.com)

#### Alocação
Remoto

#### Regime
CLT

#### Nível
Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
