### ISSUE TITLE
[São Paulo] Front-end Developer na MJV Soluções

### ISSUE THREAD

**Issue by williamMJV** [frontendbr/vagas#4144]
> Vaga Remota e Presencial 

## MJV Soluções

Somos uma consultoria global de inovação e tecnologia. Fornecemos soluções end-to-end, da ideação até a implementação de TI, passando por Data Science e Analytics. Iniciamos nossa trajetória na área de TI! Mas também nos transformamos, trouxemos o Design Thinking e o Ágil para nosso DNA a fim de compreender a fundo o negócios dos nossos clientes e alcançar resultados cada vez mais eficientes. Nesse processo de evolução, entendemos que não há como uma empresa ser competitiva sem Data Science e Analytics. Dessa forma enriquecemos ainda mais nosso ciclo de soluções end-to-end. Hoje, atuamos desde o entendimento do cliente até a construção de cenários futuros, desenvolvendo tecnologias e operações mais inteligentes, sempre orientadas por dados. Consultoria em tecnologia - Outsourcing de Profissionais - Estratégia Digital - Inovação em Negócios.

## Descrição da vaga
Experiência: - Com consumo de APIs RESTfull; - Utilização das ferramentas Git, React-Redux, Typescript, React Hooks e Styled-Components. Características pessoais e conhecimentos: - Clareza de raciocínio e exposição da solução; - Conhecimento e vivência dos princípios S.O.L.I.D.; - Conhecimentos em arquitetura de projetos, design patterns e boas práticas de desenvolvimento; - Visão ampla sobre processos de desenvolvimento e fluxo de trabalho em metodologias ágeis; - Alta capacidade de auxiliar os outros membros do time a se desenvolverem, sendo capaz de comunicar ideias de forma clara; - Familiaridade com processo de Pull Requests.

## Local

Exemplo: Remoto e Presencial, SP, São Paulo, Centro

## Requisitos

**Obrigatórios:**
- Experiência com React
-  Experiência com consumo de APIs RESTful
- Conhecimento e vivência dos princípios S.O.L.I.D

**Desejáveis:**
- Familiaridade com processo de Pull Requests.

**Diferenciais:**
- 

## Benefícios

- VT ou reembolso para fretado  com desconto em carteira de até 6% de acordo com a lei da CLT;
- VR de 23,89/ dia sem desconto em folha; Plano de saúde Sulamérica acomodação apartamento parcialmente subsidiado pela empresa, (valor inicial 230,00) 
- Opcional; Plano odontológico de 12,50/ mês - Opcional; Seguro de vida em grupo 
- E mais... Temos parceria com Alura, onde os nossos colaboradores podem fazer cursos gratuitamente; Descontos em academias, escolas de inglês e universidades

**Diferenciais:**
- No Dresscode

## Contratação

CLT

## Como se candidatar

Por favor envie um email para william.junior@mjv.com.br com seu CV anexado - enviar no assunto: Vaga :Front-End Developer (Pleno ou Sênior) - REACT

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dia após cada processo.
E-mail para contato em caso de não haver resposta:  william.junior@mjv.com.br com

## Labels
#react #front

#### Alocação
- Alocado presencial e remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
