### ISSUE TITLE
[Remoto - Diadema] Front-end Developer [FULLSTACK] @ Assa Abloy

### ISSUE THREAD

**Issue by assaabloybr** [frontendbr/vagas#4145]
> Vaga Remota durante a pandemia

## ASSA ABLOY

Líder mundial em soluções para abertura de portas.

O Grupo ASSA ABLOY foi constituído em 1994 e hoje compreende mais de 400 empresas subsidiárias em 70 países, ultrapassando a casa de 48.500 funcionários e faturamento de cerca de 9,9 bilhões de dólares aproximadamente.

## Descrição da vaga

Estamos à procura de um Consultor de Desenvolvimento Pleno para atuar na área de Engenharia da marca Vault na unidade de Diadema - SP.

Você terá como desafio trabalhar com equipes de desenvolvimento de muitas partes do mundo, principalmente Canadá e Estados Unidos, e criar soluções de alto nível para que as pessoas possam vivenciar um mundo mais seguro e aberto.

## Local

Predominantemente remoto, com reuniões ocasionais na sede administrativa.

## Requisitos

**Obrigatórios:**
- Superior completo ou cursando em: Ciência da Computação, Engenharia da Computação ou Engenharias afins, Sistemas de informação ou Análise e desenvolvimento de sistemas;
- Conhecimentos em linguagens: Java Script e .NET (Core, C#, Asp.Net MVC, Web API, Entity Framework);
- Experiência com APIs REST e SOAP;
- Pensamento crítico e visão analítica;
- Inglês Avançado (leitura, escrita e conversação );
- Disponibilidade para trabalhar remoto em dias esporádicos.

**Desejáveis:**
- Conhecimentos em Banco de Dados (SQL Server)
- Conhecimentos em documentação de software, APIs e produção de manuais;
- Experiência com processos ágeis ( Scrum , Kanban )

**Diferenciais:**
- Conhecimentos básicos em eletrônica
- Espanhol Intermediário

## Contratação

CLT

## Como se candidatar

Por favor envie um e-mail para janete.araujo@assaabloy.com com seu CV anexado - enviar no assunto: Vaga CONSULTOR DE DESENVOLVIMENTO PLENO

ou

Via LinkedIn: https://www.linkedin.com/jobs/view/2374075470/?refId=YuoM%2Bw5ISHWOGPm0x6vrmQ%3D%3D

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 30 dias após cada processo.
E-mail para contato em caso de não haver resposta:  janete.araujo@assaabloy.com

#### Alocação
- Predominantemente Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
