### ISSUE TITLE
[São Paulo] Front-End Developer na SHIPAY

### ISSUE THREAD

**Issue by ikenofh** [frontendbr/vagas#4147]
## Shipay

Somos uma Fintech promissora que nasceu com o propósito de simplificar e democratizar pagamentos digitais para o varejo Brasileiro.

Uma startup que vive um momento único de crescimento exponencial onde recentemente recebeu aporte financeiro de 2 grandes empresários referências para o empreendedorismo no Brasil.

Conheça mais sobre a Shipay nos links abaixo:

https://www.shipay.com.br
https://www.shipay.com.br/blog/09/11/2020/noticia-valor-economico-aporte-shipay/

## Descrição da vaga

Estamos em busca de Engenheiro de Software Front-end (nível pleno) para atuar com desenvolvimento de produtos em startup de pagamentos digitais!

## Local

[WeWork Nações Unidas 14261](https://www.wework.com/pt-BR/buildings/nacoes-unidas-14261-torre-b--sao-paulo-9e9f00a2-1473-4a6d-a78f-5fe100f2677c)
São Paulo, SP
em frente à estação Morumbi da CPTM

## Requisitos

**Obrigatórios:**
- Fluência em desenvolvimento e manutenção de aplicações Javascript e Angular;
- Experiência com pré-processadores CSS;
- Experiência com arquitetura e modularização de código (Front-end);
- Experiência com testes de Front-end (pelo menos unitário);
- Experiência com integrações utilizando APIs;
- Experiência em desenvolvimento de aplicações distribuídas e assíncronas;

**Diferenciais:**
- Conhecimentos de design e usabilidade (UX);
- Conhecimentos em Enterprise Patterns (Circuit Breaker, Event Sourcing, BFF);

## Benefícios

- Plano de saúde com cobertura nacional
- Plano odontológico
- Benefício Flexível (Caju) para utilizar em refeição, alimentação, mobilidade, cultura, farmácia, etc.
- Horários flexíveis com possibilidade de trabalhar em casa de acordo com função e demanda
- Ambiente descontraído e Happy Hour

**Diferenciais:**
- vc escolhe a sua máquina: Macbook ou Avell
- frigobar sempre cheio (cerveja, energético, água, etc.)
- snacks e doces à vontade
- nespresso
- sala de jogos com pebolim, mesa de ping-pong...

## Contratação

CLT

## Como se candidatar

Se candidate em http://frontjobs.com.br/job/183/?utm-source=jobs-listing

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
