### ISSUE TITLE
[SP] Front-end Developer na Hive Comunicação

### ISSUE THREAD

**Issue by fernandaalfonsof** [frontendbr/vagas#4149]
> Vaga Remota durante a pandemia

## A empresa

A Hive é uma empresa orientada a dados, focada no desenvolvimento e aplicação de plataformas de unificação de dados para empresas de médio e grande porte. Aqui você fará parte de um time que enxerga desafios como crescimento, que curte inovação e que gosta de um ambiente colaborativo.

Conheça mais sobre a empresa >>  [hive.com.br](https://hive.com.br/)

## Porque precisamos de você:

Procuramos um Front End developer para trabalhar em ambiente colaborativo e descontraído, fazer parte de uma equipe que está em constante busca por crescimento e que é motivada a desafios. Esperamos que você tenha domínio em desenvolvimento front-end prezando pelo código limpo e escalável.

## Local
Remoto durante a pandemia e depois no escritório, SP / Jardim das Acácias

## O que buscamos
- 3+ anos de experiência com desenvolvimento Front-End;
- Desenvolvimento de sistemas e aplicações web;
- Interface entre back-end/front-end;
- Sólidos conhecimentos em JS (ES6+) e/ou Typescript (ter interesse ou conhecimentos em frameworks React/Vue/jQuery são diferenciais positivos);
- Habilidade em implementar APIs;
- Manutenção de sistemas para correção de falhas/erros;
- Implementação de melhorias;
- Otimização de aplicações para melhor velocidade e escalabilidade;
- Criar código e bibliotecas reutilizáveis para uso futuro;
- Conhecimento de pré-processadores de CSS, tais como LESS e SASS;
- Experiência com Git (gitflow);
- Colaborar com outros membros da equipe, engenheiro, product owner, scrum master e tech leader para resolver os desafios existentes;
- Familiaridade com metodologias ágeis

**Desejáveis:**
- Bom relacionamento interpessoal e que possa trabalhar em equipe (perfil liderança ter vantagem)
- Raciocínio lógico
- Flexibilidade e fácil adaptação
- Colaborativo e com facilidade para trabalhar em equipe
- Habilidades para lidar com pessoas diversas, ter muita empatia e ser resiliente
- Ser organizado e saber ser auto gerenciado

## Contratação
CLT

## Gostou da oportunidade?
Me chama no linkedin pra gente conversar https://www.linkedin.com/in/fernandaalfonsof/

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
