### ISSUE TITLE
[São Paulo] JavaScript Developer na Entria

### ISSUE THREAD

**Issue by rturk** [frontendbr/vagas#415]
## Descrição da vaga

Projeto de Aplicativo incluindo o FrontEnd + App + Backend. 
Todo o projeto criado com Javascript & friends (NodeJS, React, Relay). Suportado por um banco de dados em MongoDB

Vale reforçar que o escopo é para trabalhar em um único App, ou seja no dá para explorar bastante novas tecnologias e garantir um código de qualidade, o qual você irá se orgulhar e poderá acrescentar no seu portfolio

O time já tem developers e precisamos de ajuda! 
## Local

Escritório, São Paulo - Zona Sul
http://plug.co/bkln
## Benefícios
- Ambiente legal para trabalhar 
- Sem frescuras para horário de trabalho.
- Localizado na Plugg Coworking zona sul de SP
## Requisitos

**Obrigatórios:**
- Mestre em coding Javascript

**Desejáveis:**
- Experiência com Node
- Experiência com Mongodb 
- Alguma noção de Design (por favor!)

**Diferenciais:**
- Relay
- React Native
- Machine Learning
## Contratação

CLT 
## Nossa empresa

A Entria (https://www.entria.com.br) é uma empresa focada em Apps de alta complexidade. É liderada por um ex-Amazon.com com experiência no Brasil e no Exterior. Somos ambiciosos e estamos crescendo muito.
## Como se candidatar

Por favor envie um email para vagas@entria.com.br com seu CV anexado - enviar no assunto: Eu sou o seu candidato(a) me contrate porque eu sou o cara!

**Comment by jgcmarins** [comment]
Galera, ainda estamos contratando. São 10 vagas pra trabalhar na **Entria**!
Qualquer dúvida, me procurem no Slack do React Brasil: http://react-brasil-slack.herokuapp.com/ @jgcmarins

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by rturk** [comment]
sim!

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
