### ISSUE TITLE
[Lisboa] Front-end React Developer na Aubay (in Portugal!)

### ISSUE THREAD

**Issue by CarolinaFFonseca** [frontendbr/vagas#4150]
## Aubay 

A Aubay Portugal é uma empresa multinacional francesa, em Portugal desde 2007. Temos escritórios em Lisboa e no Porto e somos uma consultora especializada em Gestão, Implementação, Desenvolvimento e Manutenção de Sistemas de Informação. Contamos com mais de 130 parceiros ativos e atuamos em setores como bancos, seguros, telecomunicações, serviços, energia e transportes.

## Descrição da vaga

Projeto em React e Angular

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com React
- 2 anos de experiência com Nodejs ou Angular
- Inglês mínimo B2

## Benefícios
- Plano de saúde;
- A possibilidade de trabalho remoto;
- Uma Academia de Treinamento projetada para pensar em você e em suas necessidades. Você pode contar com treinamentos técnicos e comportamentais (e-Learning e presencial), Meet & Techs, Webinars e Mentoring;
- Eventos e formação de equipas.

**Diferenciais:**
- A nossa cultura organizacional é baseada em valores como transparência, espírito de equipe, feedback regular e aprendizado contínuo;
- Prêmios de referência e presente de aniversário;
- Lounge;
- Não temos um código de vestuário;
- Chamamos você pelo seu nome e todos nos tratamos informalmente;
- Café e lanches à sua disposição;
- Tu crescerás em boa companhia. Não é a melhor forma de se aprimorar profissionalmente?

## Contratação

PJ a combinar ou CLT (contrato)

## Como se candidatar

Por favor envie um email para cfonseca@aubay.com com seu CV anexado - enviar no assunto: Vaga React

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: cfonseca@aubay.com

#Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
