### ISSUE TITLE
[Remoto] Fullstack Developer na Econodata

### ISSUE THREAD

**Issue by MuriloRS** [frontendbr/vagas#4151]
**Descrição da Vaga**

A Econodata, startup investida pelo Grupo Telefonica e fundada por ex-alunos da UFRGS, investe forte em Big Data e na sua Plataforma Online de Dados de Empresas e Inteligência de Mercado que permite pesquisar e segmentar todas as empresas do Brasil. Mais informações em: https://econodata.recruitee.com/o/full-stack-developer

Nosso grupo de devs está crescendo e buscamos novos devs, do junior ao senior, preferencialmente com perfil fullstack, motivados a trabalhar com métodos ágeis numa startup que está bombando.

O trabalho consiste em desenvolvimento frontend e backend, utilizando Big Data e tecnologias como Java, SQL, NoSQL, Elasticsearch, Airflow, REST, Spring, Maven, Vue.js, Node.js, webcrawling, webscraping e outras.

É uma grande oportunidade de trabalhar num ambiente muito dinâmico, com constantes novos desafios e busca de novas tecnologias.

**Requisitos Principais**

- Formado ou cursando graduação em Computação ou afins
- Disponibilidade para 40 horas semanais
- Experiência mínima de um ano com qualquer linguagem de programação
- O que realmente importa é ser bom no que faz!

**Diferenciais que valorizamos**

Experiência fullstack (frontend + backend), principalmente Web e SQL/NoSQL
Conhecimento em Spring, Angular, Vue.js e node.js

**Benefícios**

- CLT, VR
- remuneração a combinar
- Horário flexível e 100% remoto
- Plano Médico Unimed Unimax
- Ambiente de startup bastante jovem, com equipe de TI 
- MUITO aprendizado e crescimento rápido na carreira

**Comment by EdvaldoLima** [comment]
Eu me candidatei agora, enviei um primeiro form sem querer com uma resposta "inválida", submeti um outro :sweat_smile:

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
