### ISSUE TITLE
[Remoto] Fullstack Developer (Estágio) na Econodata

### ISSUE THREAD

**Issue by MuriloRS** [frontendbr/vagas#4152]
**Descrição da Vaga**
A Econodata, startup investida pelo Grupo Telefonica e fundada por ex-alunos da UFRGS, investe forte em Big Data e na sua Plataforma Online de Dados de Empresas e Inteligência de Mercado que permite pesquisar e segmentar todas as empresas do Brasil. Mais infos em: https://econodata.recruitee.com/o/full-stack-developer-estagio

Nosso grupo de devs está crescendo e buscamos novos estagiários devs motivados a se desenvolver como full stack e a trabalhar com métodos ágeis numa startup que está bombando.

O trabalho consiste em desenvolvimento frontend e backend, utilizando Big Data e tecnologias como Java, SQL, NoSQL, Elasticsearch, Airflow, REST, Spring, Maven, Vue.js, Node.js, webcrawling, webscraping e outras.

É uma grande oportunidade de trabalhar num ambiente muito dinâmico, com constantes novos desafios e busca de novas tecnologias.

**Requisitos Requisitos:**

- Saber alguma linguagem de programação
- Cursando 5º semestre ou superior em Computação ou afins
- Disponibilidade de 30 horas semanais (estágio)
- MUITA VONTADE de aprender e de trabalhar em equipe

**Diferenciais que valorizamos**

Experiência fullstack (frontend + backend), principalmente Web e SQL/NoSQL
Conhecimento em Spring, Angular, Vue.js e node.js

**Benefícios**

- Possibilidade de efetivação
- Bolsa de estágio a combinar
- Horário flexível e 100% remoto
- Plano Médico Unimed Unimax
- Ambiente de startup bastante jovem, com equipe de TI
- MUITO aprendizado e crescimento rápido na carreira

**Comment by Nerd00F** [comment]
@MuriloRS 

Tenho interesse, como posso me cadastrar para esta vaga?

**Comment by jhonpedro** [comment]
Eu me candidatei por aqui: https://econodata.recruitee.com/o/developer-estagio

**Comment by TechugoX** [comment]
Obrigado


Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: João<mailto:notifications@github.com>
Enviado:viernes, 12 de febrero de 2021 21:09
Para: frontendbr/vagas<mailto:vagas@noreply.github.com>
Cc:TechugoX<mailto:victor_arantes10@outlook.com>; Comment<mailto:comment@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [Remoto] Fullstack Developer (Estágio) na Econodata (#4152)


Eu me candidatei por aqui: https://econodata.recruitee.com/o/developer-estagio

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
