### ISSUE TITLE
[Remoto] Tech Lead na Econodata

### ISSUE THREAD

**Issue by MuriloRS** [frontendbr/vagas#4153]
**Descrição da Vaga**
A Econodata, startup investida pelo Grupo Telefonica e fundada por ex-alunos da UFRGS, investe forte em Big Data e na sua Plataforma de Dados de Empresas e Inteligência de Mercado que permite pesquisar e segmentar todas as empresas do Brasil. 
Mais informações em: https://econodata.recruitee.com/o/tech-lead

Buscamos um dev experiente, motivado para se desenvolver também como líder, trabalhar com métodos ágeis e influenciar diretamente os resultados de uma startup que está bombando.

Você é um dev em busca de novo nível para sua carreira?
Se sente apto para discutir questões de arquitetura, DevOps e processos?
Liderança é uma área que lhe atrai e que gostaria de desenvolver-se mais?

Buscamos um Tech Lead para nossa squad de produto para trabalhar com a seguinte stack (experiência ajuda mas não é necessária):

Banco: SQL e Elasticsearch
Back: microserviços em Node.js e Java com Spring
Front: Vue.js
APIs REST
Infra: AWS, Kubernetes

**Se é um desafio que brilha seus olhos, esta oportunidade pode ser pra você!**

**Principais Atividades**

- Atuar como tech lead, apoiando o time com decisões de arquitetura e de processos
- Botar a "mão na massa", ou seja, também programar
- Promover a melhoria contínua do processo de desenvolvimento
- Definir tecnologias, padrões e boas práticas junto com a equipe
- Atuar como Scrum Master, promovendo os processos e rituais do scrum
- Se comunicar com demais times da empresa
- Atuar como team leader, motivando e desenvolvendo profissionalmente os membros do time
- Ajudar na seleção e recrutamento técnicos

**Requisitos Principais**

- Formação superior completa em Computação
- Disponibilidade para 40 horas semanais
- Experiência mínima de 4 anos em TI e programação
- Experiência com métodos ágeis e scrum
- Alguma experiência com liderança de equipes de desenvolvimento
- Habilidade com comunicação e liderança é fundamental
- Bom relacionamento interpessoal

**Diferenciais que valorizamos**

- Experiência em startup
- Experiência full stack e full cycle
- Conhecimento da nossa stack

**Benefícios**

- CLT, VR
- remuneração a combinar
- Horário flexível e 100% remoto
- Plano Médico Unimed Unimax
- Ambiente de startup bastante jovem, com equipe de TI 
- MUITO aprendizado e crescimento rápido na carreira

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
