### ISSUE TITLE
[Remoto] Data Engineer na Econodata

### ISSUE THREAD

**Issue by MuriloRS** [frontendbr/vagas#4154]
**Descrição da Vaga**
A Econodata, startup investida pelo Grupo Telefonica e fundada por ex-alunos da UFRGS, investe forte em Big Data e na sua Plataforma Online de Dados de Empresas e Inteligência de Mercado que permite pesquisar e segmentar todas as empresas do Brasil. Mais informações em: https://econodata.recruitee.com/o/data-engineer

Buscamos DATA HACKERS: devs motivados a se desenvolver na área de dados, trabalhando com métodos ágeis e influenciando diretamente os resultados de uma startup que está bombando.

Você é um dev que se interessa por desempenho e web crawlers?
Sente que pode ser muito mais desafiado como dev?
Possui perfil prático e gosta de buscar tecnologias para resolver diferentes problemas?

Utililizamos tecnologias como SQL, NoSQL, Elasticsearch, Airflow, Neo4j, Python, Kubernetes, Docker, REST, Java, Spring, Maven, Angular, Vue.js, Node.js, webcrawling, webscraping e outras.

Se são tecnologias que brilham seus olhos, esta oportunidade pode ser pra você!

**Atividades:**

- Criar robôs para captura de dados na web
- Criar e manter pipelines de ingestão de dados 
- Processar, automatizar e otimizar processos envolvendo grandes volumes de dados
- Participar de discussões e iniciativas de Data Engineering sobre novas arquiteturas e tecnologias
- Monitorar performance e sugerir mudanças de infraestrutura

**Requisitos Principais**

- Formado ou cursando graduação em Computação ou Engenharia
- Conhecimento consistente em modelagem de dados, SQL e NoSQL
- Experiência sólida com ao menos uma linguagem de programação

**Experiências opcionais que valorizamos**

- Rotinas de processamento e transformação de dados (ETL)
- Ferramentas de DevOps, tais como AirFlow, Jenkins, Kubernetes, Docker, etc
- AWS
- AirFlow
- Python
- Microserviços e APIs

**Benefícios**

- CLT, VR
- remuneração a combinar
- Horário flexível e 100% remoto
- Plano Médico Unimed Unimax
- Ambiente de startup bastante jovem, com equipe de TI 
- MUITO aprendizado e crescimento rápido na carreira

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
