### ISSUE TITLE
[Remota] AEM  Front-end Developer (Adobe Experience Manager) na Pixter

### ISSUE THREAD

**Issue by D440** [frontendbr/vagas#4155]
## Nossa empresa

A Pixter é uma boutique de software, focada em grandes clientes. Com um time de mais de 100 pessoas, trabalhando em projetos nos EUA, Portugal e Brasil, a Pixter está guiando a transformação digital de algumas das principais empresas do mundo.
Estamos em busca de AEM Front-End Developer, com experiência sólida, em nível Pleno/Sênior, excelente comunicação, boa desenvoltura em reuniões de planejamento, organização e bom relacionamento interpessoal.

## Descrição da vaga
Quais as responsabilidades?
Discussão e Definição de soluções, baseadas em Adobe Experience Manager e Vue.JS;
Análise de requisitos e avalição de arquiteturas já existentes junto as áreas de negócios, TI e Segurança.
Elaborar e desenvolver arquiteturas utilizando principalmente React.JS ou Vue.JS e componentes do Adobe Experience Manager, integrados com API´s e BFF´s;
Participação de reuniões e contribuir com ideias e sugestões;

## Local

Remoto 

## Requisitos

Quais os requisitos?
Sólida experiência em desenvolvimento e definição de arquitetura front-end;
Sólida experiência em definição de solução baseado em Adobe Experience Manager;
Excelente experiência com desenvolvimento nas tecnologias Vue.JS ou React.JS;
Integração entre sistemas - ênfase em APIs;
HTML, CSS e Java Script;
Uso do GIT;
Noção de Design Patterns;
Ótima comunicação;

## Benefícios

Outras informações legais:

Benefícios Flexíveis (Rappi, Uber, Ubereats, Ifood, Starbucks, Bilhete Único, Spotify, Netflix, Mercados, Padarias, Serviços Médicos, Cursos, etc) - você decide com o que gastar, afinal pessoas são diferentes, seus benefícios também podem ser.
Se precisar, escritório disponível com: salas de reuniões, área de descompressão, cabines de call, 24/7, café, água saborizada e chopp (isso mesmo, chopp todo dia), pra relaxar :)
Contratação no modelo PJ

## Contratação

PJ 

## Como se candidatar

Por favor envie um email para danilo.vieira@pixter.com.br com seu CV anexado - enviar no assunto: Vaga AEM 

## Labels

- Remoto

#### Regime
- PJ

#### Nível

- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
