### ISSUE TITLE
[São Paulo - Metro Consolação] Front-end Developer na Mazzatech

### ISSUE THREAD

**Issue by taianeuchoa** [frontendbr/vagas#4156]
## Nossa empresa
Profissional será contratado pela Mazzatech para atuar em grande multinacional que atua com Certificação Digital, com forte atuação no setor publico.

## Descrição da vaga
Integrará o time de desenvolvimento da empresa, atuando em projetos internos.

## Local
Atualmente remoto para todos os profissionais.
Para profissionais de fora da cidade de São Paulo, atuação 100% remoto mesmo após a pandemia.

## Requisitos
**Obrigatórios:**
Desenvolvimento com React 
Implementação e consumo de RESTfull APIS 
Conhecimento de websockets 
Conhecimento em CSS (Responsivo) e HTML5 
Conhecimento em GCP (Google Cloud) é um diferencial 
Experiência em ambientes com Versionamento de código 
Conhecimento da Suite Atlasian (JIRA e CONFLUENCE) ou experiência em tecnologias similares 
Conhecimento de web 

**Diferenciais:**
Conhecimento em NodeJS e Vue é um diferencial
Conhecimento em criptografia e OAuth2 é um diferencial

## Contratação
A combinar

## Como se candidatar
Por favor envie um email para taiane@mazza.tech com seu CV anexado - enviar no assunto: Vaga React.
Por favor informar também sua pretensão salarial.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: taiane@mazza.tech

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
