### ISSUE TITLE
[Remoto] Front-end Angular 11 Developer na Visionnaire Tecnologia

### ISSUE THREAD

**Issue by Vilcilaine** [frontendbr/vagas#4157]
## Nossa empresa

A Visionnaire é uma Fábrica de Software de Curitiba com 24 anos de experiência e inovação. O Vagas Visionnaire é uma área dedicada aos talentos da nossa empresa e compartilhamento de oportunidades de emprego na área de TI.

Nossa demanda por profissionais produtivos, dinâmicos e criativos e alta. Se você esta por dentro das diversas tecnologias e metodologias atuais do mercado, venha fazer parte do time de Talentos da Visionnaire! 

## Descrição da vaga

Buscamos profissional com experiência em desenvolvimento de sistema Web em Angular. 
Participar no desenvolvimento Front-end (Angular) de um projeto do zero, com Back-end sendo desenvolvido em PHP.
É importante que o candidato já tenha desenvolvido sistemas com AngularJS, bem como ter uma boa experiência em HTML, CSS e JS. O foco será Front-end.
Terá um novo Aplicativo Móvel sendo desenvolvido em React Native, onde a comunicação entre o Front-end (App) e o Back-end será feita via APIs. Para esse item, caso venha a conhecer React, poderá ajudar/apoiar na execução do aplicativo.

## Local

Remoto

## Requisitos

**Obrigatórios:**
Forte conhecimento em Angular, preferencialmente na versão 11;
Experiência de ter desenvolvido/participado pelo menos um sistema completo com Angular;
Experiência de fazer a comunicação do Front-end (App) com o Back-end através de APIs;
Ter boa comunicação com o cliente para alinhamentos de dúvidas e mudanças visuais e/ou usabilidade.

**Desejáveis:**
Conhecimento em React Native;
Conhecimento em PHP (Laravel).

## Contratação

PJ a combinar

## Como se candidatar

Candidate-se através do link https://visionnaire.abler.com.br/vagas/desenvolvedor-front-end-angularjs-pleno-ou-senior-924327 ou via e-mail vilcilaine@visionnaire.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
