### ISSUE TITLE
[Remoto] Front-end Developer na SouAgro Soluções

### ISSUE THREAD

**Issue by phelipealves** [frontendbr/vagas#4159]
## Nossa empresa

A **SouAgro Soluções** é uma empresa com foco em construir soluções tecnológicas para o agronegócio.
Com uma base de clientes consolidados no mercado brasileiro e em constante crescimento.
No Ano de 2021 iremos expandir nossa operação e estamos em busca de profissionais e parceiros para nos auxiliar nesta jornada.

## Descrição da vaga

Trabalhar em uma equipe, 100% remoto, "Às vezes nos encontramos para fazer um churrasco. Mas claro, iremos fazer isso apenas quando terminar a pandemia".

Utilizamos uma arquitetura moderna, tecnologias como NodeJS, ReactJS, Typescript, MongoDB, NoSQL, GraphQL e Hasura;
Você irá participar de um time super ágil, comprometido com a qualidade do software, que utiliza automatizações em CI/CD, construindo sistemas escaláveis.

Nosso principal foco é desenvolver sistemas para o gerenciamento de carregamentos do setor da agroindústria.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência com NodeJS
- Experiência com ReactJS

**Desejáveis:**
- Conhecimentos em banco de dados, relacionais (e.g., PostgreSQL) e não relacionais (e.g., MongoDB)
- Conhecimentos em Typescript
- Conhecimentos em GraphQL
- Conhecimentos em Firebase

**Diferenciais:**
- Projetos opensource (software livre)
- Docker
- Kubernetes
- Github
- CI/CD (Github Actions, CircleCI ou Travis CI)
- Hasuralin
- NestJS
- Processo de otimização combinatória (Se você souber isso, ganhará uma rodada de cerveja/suco grátis quando tivermos a reunião da “firma”)

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um e-mail para valquer.novaes@souagrosolucoes.com com seu CV anexado - enviar no assunto: `Vaga SafraControl`

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: valquer.novaes@souagrosolucoes.com

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

**Comment by RafaPalau** [comment]
Não me candidatei mas vou atrás em aprender **Processo de otimização combinatória**.  kkkk
Vai que uma hora dessas ganho cerveja grátis.

**Comment by gynchiii** [comment]
Mandei :D

**Comment by LordMendes** [comment]
Vejo "Processo de otimização combinatória" e penso em usar algoritmo genético pra isso kkk

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
