### ISSUE TITLE
[São Paulo] - Front-End Developer no Mira Educação

### ISSUE THREAD

**Issue by thiagonetorh** [frontendbr/vagas#416]
Descrição da vaga
Desenvolver novas funcionalidades para nosso projeto de portal. Todo nosso portal segue conceito de mobile first e single page application, tendo o conceito de dashboard para usuários.
Escrever testes unitários, manter a integração contínua e participar dos ritos de nossas metodologias ágeis.

Local
Vila Mariana - São Paulo

Benefícios
Assistência médica, odontológica, VR, VT e PLR

Requisitos
- Experiência em desenvolvimento com javascript e frameworks relacionados;   
- Conhecimento prático sobre design patterns, refactoring e testes unitários;   
- Experiência trabalhando com APIs Restfull;  
- Experiência com desenvolvimento de linguagens orientada a objetos, utilização de angular js, node js, bootstrap, sass ou coffescript;   
- Trabalhar com aspectos de metodologia Ágil, xp, scrum ou kanban, tdd;   
- Integração e entrega contínua (e ferramentas relacionadas);   
- Modelagem de dados e utilização de bancos de dados relacionais e não-relacionais

Obrigatórios:
Java

Nossa empresa
Damos suporte aos processos educativos para que professores e gestores escolares possam fazer o seu melhor, envolvendo responsáveis e alunos com impacto positivo.
Brand Lovers é uma startup fundada por ex-funcionários da Amazon.com e Nivea. Finalista do Inovativa Brasil entre outros prêmios no Brasil e Exterior.

Como se candidatar

Envie o currículo com pretensão salarial para para thiagonetorh@gmail.com

**Comment by LFeh** [comment]
PJ ou CLT?

**Comment by thiagonetorh** [comment]
CLT

*Thiago Neto*
Consultor de Recrutamento e Seleção
+ 55 11 99381.2125
Skype: thiagonetorh

*[image: https://br.linkedin.com/pub/thiago-neto/3a/329/446]
<https://br.linkedin.com/pub/thiago-neto/3a/329/446>*


2017-07-10 13:25 GMT-03:00 Felipe Fialho <notifications@github.com>:

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
