### ISSUE TITLE
[Remoto] Full Stack Software Developer na Pixida do Brasil

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#4160]
## Descrição da vaga: 
 <p>To strengthen our product development of cloud-based solutions we are seeking a Full Stack Software Engineer, who has the enthusiasm to demonstrate excellency in creating new and innovative products with us.</p>
<p><strong>RESPONSIBILITIES:</strong></p>
<ul>
<li>Take responsibility for developing new cloud-based products or major features using the latest technologies and methodologies</li>
<li>Support our customers with solution analysis, development and integration</li>
<li>Create concepts for future developments of existing systems&nbsp;</li>
<li>Advance and foster our culture of best practices, clean code and testing in our development processes</li>
</ul>
<p></p>

## Pixida do Brasil: 
 <p>Pixida Group is an innovative technology consulting corporate group with focus on digitalization and mobility solutions for different industries. Our consultants and developers offer expertise in the fields of IoT, Telematics, Location-based Services, Multimedia, Driver Assistance Systems, Cloud Solutions and Data Analytic. They design tailor-made products and applications for highly challenging technical environments to meet individual customer requirements across all sectors at a global level.</p>
<p>Pixida is international. The group’s cooperation and exchange of knowledge transcend national borders beyond Germany, USA, Brazil and China.</p><a href='https://coodesh.com/empresas/pixida-do-brasil'>Veja mais no site</a>

 ## Habilidades: 
 - C# 
- Javascript 
- React.js 
- Typescript 
- Node.js

## Local: 
 100% Remoto

## Requisitos: 
 - Deep knowledge in one or more of the following technology areas from experience in a professional environment or a considerable private project 
- Back-end development  with Node.js or C# 
- Front-end development with e.g. JavaScript/TypeScript and React.js 
- Knowledge in Cloud Platforms and DevOps with AWS, Azure, Microservices and Terraform 
- Web Security with Authentication and JSON Web Token 
- Experienced to work with Git, GitLab, and Docker 
- Practical knowledge encompassing at least one full technology stack and familiarity with the other major technology stacks 
- Domain knowledge or interest in any of the following domains: Mobility, Connectivity, Big Data, Connected Navigation, Cloud Computing, Automotive 
- Considerable experience with agile software development and extreme programming, including but not limited to SCRUM, Kanban, Continuous Integration and Deployment 
- Naturally curious and boundless enthusiasm to learn new technologies 
- Knowledge in SQL Databases and NoSql Databases 
- Fluent English 

## Como se candidatar:
Candidate-se em: [Full Stack Software Developer na Pixida do Brasil](https://coodesh.com/vagas/full-stack-software-developer-130327?origin=github&modal=open)

## Tempo médio de feedbacks:
 Costumamos enviar feedbacks em até 48 horas após cada etapa do processo. E-mail para contato em caso de não haver resposta: [contato@coodesh.com](mailto:contato@coodesh.com)

#### Alocação
Remoto

#### Regime
CLT

#### Nível
Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by FrancieleGhizzoni** [comment]
Vaga permanece em andamento.
