### ISSUE TITLE
[Rio de Janeiro / Remoto] Full Stack Developer no MIND - Multiplan

### ISSUE THREAD

**Issue by RMontSerrat** [frontendbr/vagas#4163]
## MIND - Multiplan

O MIND é o braço de inovação da Multiplan, hoje dona de 18 shoppings pelo Brasil e diversos outros empreendimentos. Atuando há 45 anos no mercado, atualmente passamos por uma grande transformação digital, e contamos com você para nos ajudar nessa missão!
Buscamos pessoas persistentes, com mente analítica, percepção de futuro, orientação ao negócio durante o desenvolvimento e por último, mas não menos importante, ter a capacidade de trabalhar bem em equipe.

## Local

Exemplo: Remoto ou Escritório no Rio de Janeiro, Barra da Tijuca (no momento, todos estão remotos por conta da pandemia)

## Requisitos

**Obrigatórios:**
- 3 anos ou mais de experiência em desenvolvimento Javascript;
- Base sólida em React, React Native e NodeJS;
- Flexibilidade para atuar no backend e frontend;
- Domínio do Git e Git Flow;
- Facilidade para atuar em times multidisciplinares;
- Experiência em metodologias/frameworks ágeis;
- Conhecimento em testes automatizados (Unitário e Integração);

**Desejáveis:**
- Conhecimento em infraestrutura (AWS, Docker, CI/CD);
- Experiência com MongoDB, Elasticsearch e Redis;
- Conhecimentos em GraphQL (Apollo);

## Benefícios

- Participação nos lucros e resultados;
- Vale refeição R$ 40,50;
- Plano de saúde Bradesco Top Nacional;
- Plano odontológico Bradesco;
- Incentivo a cursos e palestras pelo Brasil;
- Vaga para carro;

## Contratação

CLT ou PJ, a combinar

## Como se candidatar

Por favor envie um email para devs@multishopping.com.br com seu CV anexado - enviar no assunto: [Vaga FullStack]

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by BrenerQuevedo** [comment]
A vaga é realmente para Júnior ?

**Comment by RafaPalau** [comment]
> A vaga é realmente para Júnior ?

Um junior com 3 anos de experiencia.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
