### ISSUE TITLE
[100% 🌎 Remoto] Front-end Developer em produto SaaS prestes a ser lançado

### ISSUE THREAD

**Issue by jfoliveira** [frontendbr/vagas#4165]
> Vaga Remota - PERMANENTEMENTE REMOTA, Seja fera de onde cê quiser ser fera

## Nossa empresa

Estamos desenvolvimento plataforma SaaS - ainda não lançada - que tem desenvolvedores de software como público alvo, e inúmeros desafios de usabilidade e performance.
Nossa missão é tornar absolutamente intuitivo o gerenciamento de servidores e aplicações na nuvem. Talvez a gente não consiga, mas vai que? Menos difícil com a ajuda de gente fera. :-)

## Descrição da vaga

Buscamos pessoa apaixonada por desenvolvimento front-end e os desafios de oferecer uma interface amigável com performance admirável e que simplifique a resolução dos casos de uso de nossos usuários.

Se você tem bom conhecimento de arquitetura de software e excelente compreensão das interações entre front-end e back-end, entende a importância de boa experiência do usuário, gosta de ter orgulho de suas entregas, e se vê com capacidade e interesse em atuar e influenciar o futuro de um produto inovador, essa pode ser uma boa oportunidade.

Trabalho inicial como free-lancer (sem limite de horas) com possibilidade de demanda contínua caso o trabalho seja bem executado. Exigência de qualidade das entregas é alta. Se gostar de trabalhar conosco e nós gostarmos de trabalhar contigo, seguimos.

## Local

Não há exigência de horário ou local de trabalho. Nossa equipe já era remota mesmo antes da pandemia.
Nos comunicamos de maneira assíncrona via `Slack` e ferramentas de gestão de projetos.

## Requisitos

**Obrigatórios:**
- Ter ao menos 15 (quinze) horas disponíveis semanalmente para atuação como free-lancer remoto
- Cê manja muito de desenvolvimento web. E espero que cê manje bem mais do que eu
- Conhecer muito bem `React.js`:
  - Se você é fera em `Vue.js` ou outro framework será bem vindo também. Não precisa morrer de amores pelo `React`, mas é o que tem pra hoje e vamos evoluir sobre a base atual do produto e mudar framework não é uma opção nos próximos 12 meses, e não consideraremos perder tempo em análises de substituição de tecnologia base antes do produto se tornar rentável e conseguirmos ter receita pare re-investir;
- Experiência com detecção e correção de erros em apps web
- Desejo de atuar em plataforma global de DevOps e automação que será utilizada por seus colegas de profissão :-)

**Desejáveis:**
- Experiência com Design System e organização de galeria de componentes
- Vivência com Storybook
- Vivência com TypeScript
- Automação de testes no front-end

**Diferenciais:**
- Ser ou ter sido responsável por manter aplicação web em produção (em qualquer tecnologia)
- Ter boa comunicação e desejo de influenciar outros desenvolvedores da equipe na adoção de boas práticas de desenvolvimento de software;
- Ser, ou desejar se tornar, uma referência no desenvolvimento front-end
- Almejar ter em seu portfólio uma plataforma global inovadora que será lançada simultaneamente em múltiplos idiomas e tem devs como público alvo;

## Benefícios
- Liberdade de trabalhar na hora que cê quiser de onde cê quiser. Desde que entregue as tarefas com as quais cê se comprometeu, tudo certo.
- Equipe pequena, altamente técnica, bem humorada, e principalmente obstinada e orientada a resultados. Sem perda de tempo em discussões inúteis. A gente ama o que faz e foca na entrega de resultados.

## Contratação

PJ, por hora. Valor a combinar

### Sobre o processo seletivo:

1. Um bate papo via texto no LinkedIn, cerca de 15 minutos
2. Uma conversa ao telefone, entre 30 e 60 minutos
3. Envio de um teste técnico de programação que muitos já conseguiram resolver em menos de 4 horas. No entanto a pessoa terá 24 horas para entregar uma solução
4. Ligação para revisão do teste, cerca de 15 minutos.
5. Se pessoa foi aprovada já passamos a primeira tarefa, remunerada

## Como se candidatar

Por favor candidate-se via LinkedIn: https://www.linkedin.com/jobs/view/2392464099/

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias úteis após iniciado o processo seletivo.

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by vncscoelho** [comment]
Creio que está fechado a candidatura pelo link do Linkedin.

Em sáb, 23 de jan de 2021 12:42, jfoliveira <notifications@github.com>
escreveu:

**Comment by jfoliveira** [comment]
@vncscoelho eu tinha digitado o link incorreto, desculpa a vergonha que eu passei :-)
Obrigado pelo toque!
Tente novamente, e se tiver algum problema dá o grito aqui, por favor. Valeu!

**Comment by gynchiii** [comment]
Mandei :D

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
