### ISSUE TITLE
[São Paulo - Metro Faria Lima] Front-end Developer na Influu

### ISSUE THREAD

**Issue by influu** [frontendbr/vagas#4166]
## Descrição da vaga
Desenvolvedor frontend com vasta experiência em Javascript e em frameworks como NodeJS, VUeJS ou React.

## Nossa empresa
Somos uma agência com foco no mercado de influenciadores.

## Local
Próximo ao metro Faria Lima

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com desenvolvimento Javascript - ES6, ES2015

## Diferenciais:
Conhecimento em NodeJS e Vue é um diferencial

## Contratação
PJ a combinar

## Como se candidatar
Por favor envie um email para contato@influu.me com seu CV ou Link Git- enviar no assunto: [VAGA_JS] + Nome + Sobrenome

## Labels
- PJ
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
