### ISSUE TITLE
[Lisboa/Portugal] iOS Mobile @Integer Consulting

### ISSUE THREAD

**Issue by brunoalexandrecarvalho** [frontendbr/vagas#4167]
## Vaga iOS Mobile

A INTEGER, uma empresa de consultoria na área das tecnologias, com mais de uma década de presença no mercado português, está à procura de iOS Mobile com fortes habilidades de comunicação, sentido de responsabilidade e espírito de equipa.

Este pode ser o desafio perfeito para ti se tens conhecimentos de:
• Objective C e/ou Swift
• Restful APis
• Multithreading
• Inglês

Se tens o amazINg talent pretendido e queres fazer parte da equipa INTEGER, responde a este anúncio com o teu CV atualizado para bruno.carvalho@integer.pt

Participar neste projeto significa a integração numa empresa sólida em crescimento e numa equipa jovem e dinâmica. #jumpIN

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
