### ISSUE TITLE
[Remoto] Desenvolvedor Front-end React.js na Ensinio

### ISSUE THREAD

**Issue by guiavila** [frontendbr/vagas#4170]
# Descrição da vaga

Procuramos desenvolvedores especialistas em JavaScript e React.js para integrar o time de desenvolvimento front-end da Ensinio. Nossa plataforma oferece soluções de ecommerce e recursos avançados de cursos online e ensino à distância para empresas e empreendedores dos mais diversos nichos. Nós oferecemos a plataforma perfeita para quem quer ensinar e vender online, e queremos ter você nesse time! Procuramos pessoas competentes e fora da curva para crescer junto conosco. Suas responsabilidades incluiriam manter e expandir o front-end de um SaaS desenvolvido em React.js sob arquitetura multi-tenancy, e nos ajudar a tomar as melhores decisões técnicas em novos projetos no futuro.

# Local

Trabalho 100% remoto.

# Requisitos fundamentais

* Versionamento de código com Git em times de desenvolvimento;
* Sólidos conhecimentos de HTML e CSS (incluindo CSS-in-JS). Você deve ser capaz de codificar, com maestria, qualquer tipo de interface de forma responsiva;
* Sólidos conhecimentos de JavaScript (manipulação da DOM, estruturas de dados, funções assíncronas, iteradores e geradores, etc);
* Experiência prévia no desenvolvimento de uma aplicação em produção sob React.js;
* Sólidos conhecimentos acerca dos paradigmas do React.js (JSX, hooks, estado e ciclo de vida, etc);
* Sólidos conhecimentos de gerenciamento de estado com Redux (incluindo, preferencialmente, redux-saga);
* Sólidos conhecimentos acerca da comunicação cliente-servidor (ser capaz de compreender o fluxo de dados e consumir informações de uma API REST);
* Legítima vontade de resolver problemas de forma eficiente através da tecnologia, ao passo em que evolui pessoalmente e profissionalmente, recebendo feedbacks constantemente;
* Noções acerca de boas práticas de código, arquitetura de software, processos e metodologias de desenvolvimento, performance, manutenibilidade e escalabilidade de aplicações.

# Seria fantástico se em seu background houvesse:

Conhecimentos/experiências desejáveis, não-excludentes.

* Experiência com metodologias ágeis, sobretudo Scrum;
* Noções acerca de UI/UX, princípios de usabilidade e do design de interfaces;
* Conhecimentos de e/ou experiência com TypeScript;
* Conhecimentos de e/ou experiência com Next.js;
* Experiência com aplicações escaláveis;
* Experiência com testes (unitários, de integração e afins);
* Conhecimentos de arquitetura e manutenibilidade de software;
* Significativo conhecimento de orientação a objetos e princípios SOLID;
* Graduação completa ou em andamento em Ciência da Computação, Engenharia de Software, Engenharia da Computação, Sistemas de Informação ou congêneres.
* Nível conversacional de inglês.

# Sobre a Ensinio: uma breve descrição

A Ensinio é uma solução completa para quem quer vender e ensinar online. Permitimos que nossos clientes tenham suas próprias plataformas para vender produtos digitais e físicos, criar e distribuir cursos e conteúdos, e construir sua própria escola online com um sistema de EAD completo. A plataforma é inteiramente customizável, conta com funcionalidades de rede social e centenas de recursos avançados para garantir a melhor experiência de navegação, compra e aprendizado. Nosso ambiente é de aprendizado constante e, conosco, suas ideias serão ouvidas.

# Contratação

PJ a combinar

# Como se candidatar

Envie seu CV para jobs@ensinio.com com pretensão salarial e seu perfil profissional. Nos conte um pouco sobre você e o motivo pelo qual você quer esta vaga. Queremos conhecer o seu background, suas habilidades, ambições e perspectivas futuras. Se possível, inclua também seu LinkedIn e GitHub, enviando a mensagem com o assunto "Vaga - Desenvolvedor Front-end". Faremos o possível para responder em até 5 dias úteis.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
