### ISSUE TITLE
[Curitiba/Remoto] Front-end Developer na Agrotis

### ISSUE THREAD

**Issue by girardiricardo** [frontendbr/vagas#4171]
## Nossa empresa

Somos uma empresa com um rico histórico no desenvolvimento de sistemas e serviços que já ajudam na gestão de mais de 2.000 empresas do agronegócio em todo o Brasil.

## Descrição da vaga

Buscamos uma pessoa que nos ajude a impactar a maneira como o agronegócio brasileiro faz uso de tecnologia.

## Local

Remoto ou Presencial [Curitiba]

## Requisitos

**Obrigatórios:**
- Experiência com React de pelo menos 2 anos
- Desenvolvimento voltado à componetização
- Conhecimentos sólidos em HTML5 e CSS3
- Domínio em Javascript nativo (ES6)
- Conhecimento básico de versionamento de código com GIT
- Experiência com ferramentas de gerenciamento de estado (redux, useContext)
- Experiência com Typescript

**Desejáveis:**
- Experiência com testes
- Conhecimento em Design System
- Conhecimento em Design Responsivo

**Diferenciais:**
- Projetos opensource
- Experiência com alguma metodologia atual de padrões de CSS/HTML (BEM, Atomic,...)

## Contratação

PJ/CLI a combinar

## Como se candidatar

Por favor envie um email para ricardo.girardi@agrotis.com com seu CV anexado - enviar no assunto: Vaga Front-end Developer ou entre em contato pelo [LinkedIn](https://www.linkedin.com/in/girardiricardo/)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: ricardo.girardi@agrotis.com

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Senior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
