### ISSUE TITLE
[Remoto] Front-end Developer na ZAPPTS

### ISSUE THREAD

**Issue by zappts** [frontendbr/vagas#4172]
## Nossa empresa

Venha trabalhar em uma empresa que triplicou de tamanho no último ano e segue conquistando cada vez mais clientes!

## Descrição da vaga

Vaga 100% remota, contrato CLT.
Enviar CV com assunto: Desenvolvedor Frontend Mobile ReactNative para queroser@zappts.com

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento mobile React Native
- Arquiteturas MVVM, MVP e outras;
- Testes unitários;

**Desejáveis:**
- Ágil (Scrum, Kanban)
- Inglês

**Diferenciais:**
- Java/Kotlin para Android;
- Objective-C/Swift para iOS;

## Benefícios

- Plano de saúde ou auxílio saúde
- VR ou VA
- Seguro de vida
- Auxílio teletrabalho

**Diferenciais:**
- 100% remoto (home office)
- horário flexível
- time incrível

## Contratação

CLT (40 horas/semana)

## Como se candidatar

Enviar CV com assunto: Desenvolvedor Frontend Mobile ReactNative para queroser@zappts.com

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 20 dias após cada processo.
E-mail para contato em caso de não haver resposta: queroser@zappts.com

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
