### ISSUE TITLE
[Remoto] Senior Mobile React Native Developer (Android/iOS) na Pixida do Brasil

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#4176]
## Descrição da vaga: 
 <p>To strengthen our product development teams in creating mobile applications for our products and customers, we are seeking a Software Developer for iOS or Android, who is motivated to share his enthusiasm in creating new and innovative products with us.</p>
<p><strong>RESPONSIBILITIES: </strong></p>
<ul>
<li>Develop mobile applications for our products and customers using the latest technologies and methodologies</li>
<li>Support our customers with solution analysis, development and integration</li>
<li>Create concepts for future developments of existing products&nbsp;</li>
<li>Contribute to our culture of best practices, clean code and testing in our development processes</li>
<li>Participation in our Competence Area and Peer Learning programs</li>
</ul>
<p></p>

## Pixida do Brasil: 
 <p>Pixida Group is an innovative technology consulting corporate group with focus on digitalization and mobility solutions for different industries. Our consultants and developers offer expertise in the fields of IoT, Telematics, Location-based Services, Multimedia, Driver Assistance Systems, Cloud Solutions and Data Analytic. They design tailor-made products and applications for highly challenging technical environments to meet individual customer requirements across all sectors at a global level.</p>
<p>Pixida is international. The group’s cooperation and exchange of knowledge transcend national borders beyond Germany, USA, Brazil and China.</p><a href='https://coodesh.com/empresas/pixida-do-brasil'>Veja mais no site</a>

 ## Habilidades: 
 - Android SDK 
- iOS 
- Java 
- Javascript 
- Kotlin 
- React Native 
- GIT 
- Swift 
- Android 
- Flutter

## Local: 
 100% Remoto

## Requisitos: 
 - Knowledge in one or more of the following technology areas from experience in a professional environment or a considerable private project 
- Swift (iOS) or Java/Kotlin (Android) 
- Native UI Frameworks and Components (Flutter, React Native) 
- iOS: Xcode, Instruments, Cocoa Touch or equivalent 
- Android: Android Studio, Gradle or equivalent 
- Version control system: GIT, SVN, Mercurial 
- Domain knowledge or interest in any of the following domains: Mobility, Connectivity, Big Data, Connected Navigation, Cloud Computing, Automotive 
- Experience with agile software development and extreme programming, including but not limited to SCRUM, Kanban, Continuous Integration and Deployment 
- Naturally curious and boundless enthusiasm to learn new technologies 
- Fluent English

## Como se candidatar:
Candidate-se em: [Senior Mobile Developer (Android/iOS) na Pixida do Brasil](https://coodesh.com/vagas/senior-mobile-developer-androidios-125746?origin=github&modal=open)

## Tempo médio de feedbacks:
 Costumamos enviar feedbacks em até 48 horas após cada etapa do processo. E-mail para contato em caso de não haver resposta: [contato@coodesh.com](mailto:contato@coodesh.com)

#### Alocação
Remoto

#### Regime
CLT

#### Nível
Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
