### ISSUE TITLE
[Remoto] UI/UX Designer na Pixida do Brasil

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#4177]
## Descrição da vaga: 
 <p>To strengthen our product development teams for our cloud-based products, we are seeking a <strong>UI / UX Specialist</strong>, who is motivated to share his enthusiasm in creating outstanding user experiences.</p>
<p><strong>RESPONSIBILITIES:</strong></p>
<ul>
<li>As part of one of our teams realize UI/UX concepts developing our cloud-based products using the latest technologies and methodologies</li>
<li>Create UI and UX concepts for our existing and new products based on collaborative research, design and development&nbsp;</li>
<li>Contribute to our culture of best practices and evaluation in our development processes to enable high-value customized solutions</li>
</ul>
<p></p>

## Pixida do Brasil: 
 <p>Pixida Group is an innovative technology consulting corporate group with focus on digitalization and mobility solutions for different industries. Our consultants and developers offer expertise in the fields of IoT, Telematics, Location-based Services, Multimedia, Driver Assistance Systems, Cloud Solutions and Data Analytic. They design tailor-made products and applications for highly challenging technical environments to meet individual customer requirements across all sectors at a global level.</p>
<p>Pixida is international. The group’s cooperation and exchange of knowledge transcend national borders beyond Germany, USA, Brazil and China.</p><a href='https://coodesh.com/empresas/pixida-do-brasil'>Veja mais no site</a>

 ## Habilidades: 
 - CSS 
- HTML 5 
- UI 
- UX 
- GIT 
- Sass/Less 
- Figma 
- AdobeXD 

## Local: 
 100% Remoto

## Requisitos: 
 - Deep knowledge in creating and improving user experience for web and mobile applications 
- Experience in data visualization on web frontends 
- Experience with some of the following technologies from a professional environment or a considerable private project 
- Low-fidelity and high-fidelity prototyping, e.g. Adobe XD, Figma, Sketch, Axure or equivalent 
- Graphic Design with e.g. InDesign, Photoshop or equivalent 
- Video creation and editing tools, e.g. GoAnimate, Animoto  
- Usage and maintenance of Design Systems  
- Experiences in interdisciplinary collaborative development together with Frontend Developers  
- Understanding of Web Technologies: HTML/JavaScript, CSS, Less, Sass or equivalent 
- Domain knowledge or interest in any of the following domains is a plus: Mobility, Connectivity, Big Data, Connected Navigation, Cloud Computing, Automotive 
- Comfortable and thriving working in an agile software development environment 
- Naturally curious and boundless enthusiasm to learn new technologies 
- Fluent English 
- Development and maintenance of corporate Styleguide and Design System 
- Experience with Material Design and iOS Design guidelines

## Como se candidatar:
Candidate-se em: [UI/UX Designer na Pixida do Brasil](https://coodesh.com/vagas/ui-ux-specialist-123415?origin=github&modal=open)

## Tempo médio de feedbacks:
 Costumamos enviar feedbacks em até 48 horas após cada etapa do processo. E-mail para contato em caso de não haver resposta: [contato@coodesh.com](mailto:contato@coodesh.com)

#### Alocação
Remoto

#### Regime
CLT

#### Nível
Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
