### ISSUE TITLE
[Remoto] Front End Engineer na linte_

### ISSUE THREAD

**Issue by xguhkaa** [frontendbr/vagas#4179]
## Nossa empresa

Há 5 anos a Linte combina ferramentas de automação e colaboração para oferecer uma nova experiência de trabalho para todos que precisam lidar com consultas jurídicas, contratos e outros documentos. Mais de 50 empresas hoje economizam tempo e dinheiro por utilizarem nossos produtos.

O nosso desafio, contudo, vai além. Mais do que revolucionar a tradicional indústria jurídica, estamos construindo, juntos, a empresa em que a gente sonhava em trabalhar: um lugar no qual a gente possa ser quem a gente é de verdade, onde todo mundo tem voz e é parte do processo. Nossa jornada é baseada na confiança e transparência.

Já participamos do programa de aceleração da _500 Startups_, em São Francisco/CA, e levantamos $3M em _seed capital_ com fundos como _Valor Capital Group_ e _RedPoint eVentures_.

## Descrição da vaga

Como _Front End Engineer_, sua missão é desafiar o status quo em um ambiente de incertezas e constantes mudanças. Os desafios são grandes e muito inspiradores, pois estamos construindo uma empresa a frente do tempo em seu nicho de mercado.

Além disso, o desafio técnico e a abordagem usada, eleva o nível de profissionais que fazem parte da Linte. Se você possui vontade de ser referência no assunto, contribuir para comunidades e ainda possui o sonho de construir um case de sucesso usando Programação Funcional e uma _Stack_ diferenciada, participe do nosso processo!

## Local

Remoto

## Requisitos

**Obrigatórios:**

- Ter usado _TypeScript_ profissionalmente;
- Proficiência em JavaScript/ES6, incluindo manipulação do DOM;
- Proficiência em _React Hooks_ e _Apollo Cache_;
- Ter trabalhado profissionalmente com GraphQL/Apollo;
- Ter trabalhado com testes unitários utilizando Jest;
- Conhecimento sólido de Bibliotecas de Estrutura de Dados como _Immutable JS_ ou _MoriJS_;
- Conhecimento sólido em Git & Git-Flow & Linux;
- Conhecimento sólido em CSS (SASS ou LESS);
- Familiaridade com _Reactive Programming_ / _RxJS library_;
- Conhecimento de mecanismos de autorização, como JWT;
- Promover melhores práticas, tais como code _reviews_ e testes unitários;
- Ótima comunicação pessoal para entregar projeto no prazo;
- Experiência em _Agile_ / _Scrum_ / _Dual Track_;
- 1+ ano de experiência profissional em _GraphQL_;
- Experiência em padrões de componentização em _React_;
- 5+ anos de experiência profissional;
- Inglês básico (leitura e escrita).

**Desejáveis:**

- Interesse por _benchmarking_ e otimização;
- Isomorphic React;
- Boas práticas de Programação Funcional;
- Familiaridade com CICD;
- Familiaridade com BDD;
- Inglês avançado/ fluente.

**Diferenciais:**

- Experiência em Docker e/ou Kubernetes;
- Ninja em _Chrome Dev Tools debugging_;
- 1+ ano de experiência profissional em _open-source_;

## Benefícios

- Vale Alimentação & Refeição (flexibilidade pelo [Caju](https://www.caju.com.br/));
- Gympass;
- Plano Médico (100% pago pela linte);
- Férias Remuneradas + 13° (mesmo p/ modalidade PJ);
- Flexibilidade de Horário.

**Diferenciais:**

- Fazer parte desta empresa e time incríveis :)

## Contratação

PJ ou CLT.
Aberto p/ negociação

## Como se candidatar

Através deste [link](https://linte.gupy.io/jobs/641890?jobBoardSource=gupy_public_page) da página da Gupy.

## Tempo médio de feedbacks

Costumamos enviar _feedbacks_ em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: monise@linte.com

#### Alocação

- Remoto

#### Regime

- CLT
- PJ

#### Nível

- Sênior

**Comment by xguhkaa** [comment]
[**UPDATE**] Ainda estamos com esta posição em aberto

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by xguhkaa** [comment]
[**UPDATE**] Ainda estamos com esta posição em aberto
