### ISSUE TITLE
[São Paulo] Front-End Developer Sênior na Memed

### ISSUE THREAD

**Issue by gabrielrcouto** [frontendbr/vagas#418]
![cabecalho memed vaga](https://user-images.githubusercontent.com/2197005/28040232-8be9e3c6-659b-11e7-9bee-b86e00241fbd.png)

## Descrição da vaga

Procurando por uma carreira que te desafie e inspire?

Somos uma startup inovadora na área da saúde que se propõe a repensar a forma com que os médicos fazem suas prescrições e como os pacientes aderem ao tratamento. 

Estamos vivendo o melhor momento da vida curta da Memed: grande crescimento, engajamento, produto sólido, novo escritório e muitas coisas para construir junto com pessoas talentosas.

Procuramos alguém que ame front-end, goste de desenvolver aplicativos híbridos, curta utilizar novos padrões web e que não consegue ver um pixel fora do lugar.

## O que você vai fazer:

- Desenvolver a maior plataforma médica de prescrição digital do Brasil 
- Evoluir nosso aplicativo híbrido mobile
- Usar muito CSS, somos "pixel perfeccionistas"
- Fazer fine tuning de UI/UX, adoramos performance

O que usamos no front-end: Arquitetura modular + CQRS/ES + Backbone.js + Underscore Templates + App.js + jQuery/Zepto + Cordova + Grunt/Bower/NPM + LESS

O que usamos para BDD: Gherkins + Selenium

## Local

No [Bela Vista](https://www.google.com.br/maps/place/Memed/@-23.5648302,-46.6436615,15z/data=!4m2!3m1!1s0x0:0xc370598c92acf2db?sa=X&ved=0ahUKEwisjoyP0f_UAhWCjJAKHWUoDLYQ_BIIejAK), a 7 minutos da estação de metrô Brigadeiro, em São Paulo. 

Horário das 09h às 18h, de segunda a sexta-feira (Presencial).

## Benefícios
- VR
- VT
- Seguro de Vida
- Seguro Saúde

## Requisitos

**Obrigatórios:**
- Pelo menos 5 anos de experiência na área
- Gosta de Vanilla Javascript e sabe quando utilizar frameworks
- Experiência em pré-processadores de CSS (ex: SASS, SCSS, LESS)
- Experiência em ferramentas de automação de tarefas (ex: Grunt, Gulp)
- Experiência com desenvolvimento de aplicativos mobile híbridos (Phonegap/Cordova)
- Conhecimento de design patterns (ex: Repository, Service layer, Locator)
- Desenvolvimento de código com organização, modularização e documentação
- Percepção de estética e noções de design
- Capacidade de autogestão e aprendizado rápido
- Vontade em inovar e melhorar a saúde do Brasil

**Desejáveis:**
- Envolvimento com projetos open source/comunidade
- Experiência com Backbone.js e Zepto
- Experiência com ferramentas para BDD (ex: Cucumber, Behat, Selenium)
- Experiência com GitFlow

## Contratação

CLT

## Como se candidatar

Por favor envie um email para gabriel.couto@memed.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Sr.

Caso queira bater um papo, no Slack do Front-End Brasil (http://frontendbrasil.slack.com/) é só chamar o @bob.

**Comment by gabrielrcouto** [comment]
Labels: alocado, clt, senior

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
