### ISSUE TITLE
[Niterói] Web design na Internit

### ISSUE THREAD

**Issue by Fredpeixoto** [frontendbr/vagas#4180]
> Vaga Remota durante a pandemia

## Nossa empresa

Produtora web consolidada com 24 anos de marcado.

## Descrição da vaga

Criação e manutenção de site, sistemas, landing pages e peças

## Local

Exemplo: Remoto na pandemia. Pós pandemia ou Escritório, [RJ], [Niterói], [Santa Rosa]

## Requisitos

**Obrigatórios:**
- Ser muito criativo e ter bom gosto.
- Experiência na criação de identidade visual, layouts sites, landing pages e peças.
- Fundamentos sobre design (tipografia, teoria das cores, usabilidade e performance).
- Experiência com Adobe XD e/ou Figma, Photoshop, Illustrator e After Effects. 
- Produtividade, facilidade de relacionamento, atenção aos detalhes, comprometimento com prazos e entregas. 
- Já cadastrou seu currículo em nosso site? É fundamental que o faça.

**Diferenciais:**
- UI e UX Design
- Implementação de sites em Wordpress

## Benefícios

- Vale transporte 
- Vale refeição

**Diferenciais:**
- Horário flexível
- Pós pandemia, alguns dias de home office
- Somos uma empresa consolidada com ótimo ambiente de trabalho somado à desafios constantes.
- Pós pandemia: Estamos situados em uma rua tranquila em Niterói com facilidade de estacionamento, além de termos um bicicletário na empresa.

## Como se candidatar

Se tiver interessado e se encaixa nos requisitos acima, gostaria que acessasse https://internit.com.br/curriculo e cadastrasse seu currículo.

## Tempo médio de feedbacks

E-mail para contato em caso de não haver resposta: vagas@internit.com.br

#### Regime
- CLT

#### Nível
- Pleno ou mais

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
