### ISSUE TITLE
[Remoto / São Paulo] Front-end Developer Hubert

### ISSUE THREAD

**Issue by mariapaulacarvalho** [frontendbr/vagas#4182]
Que tal aceitar o desafio mais incrível da sua carreira?
A Hubert Administração de Condomínios e Imóveis, que atua há 65 anos no setor imobiliário está em busca de Pessoas desenvolvedoras Front-End para, junto com seu time, oferecer seus clientes produtos inovadores, mais completos e eficientes para facilitar e agilizar a gestão do negócio!

Temos uma estrutura robusta de atendimento dedicado com especialistas em diversas áreas, sistema tecnológico próprio que permite customização e agilidade e um conhecimento adquirido ao longo dos anos utilizado para oferecer serviços a diferentes setores como condomínios comercias, residenciais, associações ou investidores imobiliários.

Estamos em busca de pessoas curiosas, otimistas, proativas, empreendedoras, que querem aprender, fazer e acontecer do jeito certo com transparência, ética e jogando como um só time! Se quiser saber mais sobre esse desafio só clicar no link!

## Local

Remoto ou Escritório [SÃO PAULO]

## Requisitos

**Obrigatórios:**
- Proficiência em Typescript,
- Proficiência em Angular (+2) e React,
 - Ninja Javascript (especificações mais recentes do ECMAScript),
- Capacidade de copiar o layout desenhado pelo time UI/UX,
- Git (branches, git flow),
- Builders e ferramentas de comandos (webpack, angular-cli, create-react-app, expo-cli, nvm),
- Experiência em Cloud e CI/CD.

**Desejáveis:**
- conhecimentos em ruby on rails
- conhecimentos em C#

**Diferenciais:**
- Experiência em aplicativos mobile com React Native,
- Experiência em REST ou BFF (Backend for Frontend) com NodeJs.
- Conhecimento em OS Mac e Linux.

## Contratação
PJ
## Como se candidatar

Responder o formulário no final da página: https://vagas-emb.byintera.com/1-k

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
