### ISSUE TITLE
[REMOTO] Front-end Pleno e Senior Developer na Coduxy

### ISSUE THREAD

**Issue by diiegoloopes** [frontendbr/vagas#4183]
## Coduxy

A Coduxy é uma startup 100% remota que surgiu  com objetivo de atender clientes dos Estados Unidos e Brasil, fornecendo suporte a projetos Wordpress, Mobile Apps, Web Apps e muitos outros. Somos uma empresa  totalmente multidisciplinar com objetivo de trabalhar com a cultura remota como nosso princípio.

## Descrição da vaga

Estamos a procura de profissionais responsáveis para atuar em nossos projetos atuais e projetos dos nossos clientes, com desenvolvimento de componentes, revisões, manutenção e propostas de novas arquiteturas para os projetos.

## Local

100% Remoto!

## Requisitos

**Obrigatórios:**
- 3+ anos de experiência com Node
- 3+ anos de experiência com React ou React Native
- 3+ anos de experiência com Git e Gitflow
- Ser Pixel Perfect!!!!

**Desejáveis:**
- conhecimentos em HTML, CSS3, Javascript
- conhecimentos em SASS, LESS ou STYLUS
- conhecimento em algum Task Runner (e.g. Gulp, Grunt)

**Diferenciais:**
- projetos opensource
- conhecimentos em AWS

## Benefícios

- Plano de saúde
- Auxílio Academia

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para diegol@coduxy.com com seu CV, Portfoólio e Pretensão Salarial anexados - enviar no assunto: Vaga Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
