### ISSUE TITLE
[São Paulo] Front-end developer na SimbioX

### ISSUE THREAD

**Issue by Jonas-buriti** [frontendbr/vagas#4184]
### [São Paulo] Front-end developer na SimbioX

Precisamos de você para criar interfaces ricas e componentes reutilizáveis e performáticos!

Você participará de todo processo de concepção de nossos projetos / soluções, interagindo com os outros times desde a criação de novas funcionalidades, até as etapas de arquitetura, desenvolvimento, code-review , teste e deploy 😀

Aqui na SX, todos profissionais possuem autonomia e liberdade para garantir que as melhores escolhas e caminhos sejam tomados 🚀

**Local**

São Paulo, SP - Próx. ao metrô Faria Lima

(Remoto durante a pandemia)

**Conhecimentos técnicos:**

-   Conhecimento em arquitetura de software e boas práticas de desenvolvimento;
-   Domínio em HTML5 / CSS3 / SASS / Vanilla Js (ES6+)

-   Conhecimento Gulp / VSCode / GitHub / React ou VueJS
-   Desejável: vivência com desenvolvimento Sass

**Responsabilidades:**

-   Apoiar na formação de novos desenvolvedores, fazendo code-review e auxiliando com dúvidas
-   Compartilhar e estimular o compartilhamento de conhecimento com a equipe de dev
-   Aqui você aprenderá na prática desenvolver sob a plataforma para Microsoft SharePoint e utilizar SPFX;

**Requisitos pessoais**

-   Perfil analítico, responsável e engajado com os objetivos da empresa
-   Muita vontade de aprender e evoluir a cada dia;
-   Comprometimento com os projetos e prazos;
-   Trabalho em equipe e boa comunicação;
-   Proatividade e foco;

**Contratação**

- Regime de contratação: PJ a combinar

- Horário: 10:00h às 19:00h (pode ser negociado com seu líder)

**Benefícios**

Além disso, temos:

-   Opcional: Custeamos 60% de um plano de saúde corporativo da NotreDame (opção de sua escolha entre os plano -- os valores variam entre aprox. R$250 à R$400, então pagamos 60% disso e 40% é descontado da remuneração);
-   Temos refeitório no escritório e no prédio para que é da #TurmaDaMarmita;
-   Investimento em capacitações de acordo com necessidades do time e programas online de educação;
-   Acesso gratuito à academia do prédio;
-   Bonificação de aniversário + day-off
-   Bonificação para alcance das metas da empresa, ou seja, a união do trabalho de toda equipe. Como falamos, a equipe que atuou em 2019 foi para Disney! Fica o mistério do que teremos para este novo ano.

**Como se candidatar**

Por favor envie um email para comunicacao@simbiox.com.br com seu CV anexado - enviar no assunto: Vaga-front-end-2021

**Regime**
PJ

**Nível**
Pleno / Senior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
