### ISSUE TITLE
[Remoto] Front-end Vue.js/Quasar Developer @ {CloudBrasil}

### ISSUE THREAD

**Issue by abernardobr** [frontendbr/vagas#4186]
# TRABALHO REMOTO COM QUASAR/VueJS 

## Descrição da empresa
Somos uma empresa focada em um software 100% brasileiro de BPM, WMS, GED e ECM (CloudBrasil - www.dbrasil.com.br) e atualmente estamos partindo para Low-code. Nossa maior concentração de cliente está no Nordeste. Dentre os nossos clientes estão: Lojas Nagem, Prefeitura de Joboatão dos Guararapes, Consôrcio Grande Recife, PVAX, Interne e Hospitais. Estamos em plena fase de crescimento e precisamos de profissionais Junior, Pleno e Senior que estajam prontos para trabalhar com Frontend e tenham vontade de crescer, desafiar-se e trabalhar em um time dinâmico, ágil e totalmente remoto.

E aí, está pronto para mais um desafio profissional? 

Está pronto para expandir e adquirir mais e novas habilidades profissionais dentro da área de TI?  
 
## Descrição da vaga

Responsibilities
-Developing user-facing applications using Vue.js
-Design the next generation UI
-Building modular and reusable components and libraries
-Optimizing your application for performance
-Implementing automated testing integrated into development and maintenance workflows
-Staying up-to-date with all recent developments in the JavaScript and Vue.js space
-Keeping an eye on security updates and issues found with Vue.js and all project dependencies
-Proposing any upgrades and updates necessary for keeping up with modern security and development best practices
-Work as part of a team developing applications and services using --Agile development methods
-Effectively use tools and ingenuity to identify and fix defects before they become a problem

Skills
-Proven experience in UI design
-Highly proficient with Vue.js framework and its core principles such as components, reactivity, and the virtual DOM
-Familiarity with the Vue.js ecosystem, including Vue CLI, Vuex, Vue Router, Nuxt.js, and Quasar Framework
-Expert understanding of HTML5 and CSS3
-Understanding of server-side rendering and its benefits and use cases
-Knowledge of functional programming and object-oriented programming paradigms
-Ability to write efficient, secure, well-documented, and clean JavaScript code
-Familiarity with automated JavaScript testing, specifically testing frameworks such as Jest or Mocha
-Proficiency with modern development tools, like Babel, Webpack, and Git
-Experience with both consuming and designing RESTful APIs
-High experience working with NodeJS (Express or HAPI)

## Local

Remoto

## Benefícios

- Férias
- Treinamento

## Contratação

PJ a combinar.

## Como se candidatar

Havendo interesse é só clicar no link abaixo para se candidatar: https://bit.ly/2mdYgYF

#### Regime
- PJ A-Combinar

**Comment by jorginhodev** [comment]
O link para se candidatar está errado

**Comment by abernardobr** [comment]
Jorge,

Já ajustei. Muito obrigado.

Segue o link: https://bit.ly/2mdYgYF

Abs,

Augusto Pissarra

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by abernardobr** [comment]
Ainda estamos contratando profissionais para essa vaga. Temos mais 3 vagas abertas.
