### ISSUE TITLE
[Remoto] Desenvolvedor(a) Front-End (Reactjs) na Studyclix

### ISSUE THREAD

**Issue by edegilson** [frontendbr/vagas#4187]
## Nossa empresa

Studyclix (https://studyclix.ie/) é uma plataforma que auxilia alunos e professores a estudarem e se prepararem para os exames de conclusão do ensino fundamental e médio. Atualmente é a maior plataforma da Irlanda neste segmento, em expansão na Austrália (https://studyclix.com.au/) e com boa projeção para iniciar em outros países.

## Descrição da vaga

Estamos reconstruindo nossa plataforma, criando novas funcionalidades, além de um aplicativo para smartphone. Buscamos um desenvolvedor(a) front-end para nos auxiliar neste processo.

## Local

100% Remoto

## Requisitos

**Obrigatórios:**
- Inglês para conversação, leitura e escrita (temos daily standup meeting pelo Zoom)
- Bom conhecimento em JavaScript, HTML e CSS;
- Boa experiência com Reactjs
- Experiência com GIT.

**Desejáveis:**
- Conhecimento em PWA.
- Conhecimento em Nodejs/Nextjs
- Conhecimento em Capacitorjs (https://capacitorjs.com/)

## Contratação

Contratação PJ
Full-time (de 30hs a 40hs por semana)
Pagamento em USD (valor por hora a depender da experiência)

## Como se candidatar

Se interessou? Me mande um email (edegilsons@gmail.com) com seu CV/Github/LinkedIn e vamos conversar :)

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
