### ISSUE TITLE
[REMOTO] Pessoa Desenvolvedora Fullstack @ Gupy

### ISSUE THREAD

**Issue by FabianaSN** [frontendbr/vagas#4189]
Apenas algumas empresas estão preocupadas em mudar a realidade do cenário de tecnologia e torná-lo mais diverso, e a Gupy é uma delas!

Não sei se você conhece mas a Gupy é uma startup fundada por profissionais de RH e de Tecnologia, com o objetivo de transformar a maneira como são feitos processos seletivos no Brasil. Afinal, quem nunca participou de um processo seletivo bem bagunçado em sua carreira? 

Nesse momento, gostaríamos de encorajar talentos com as mais diversas histórias e backgrounds a se candidatarem. Buscamos mulheres, pessoas pretas, LGBTQIA+ e PcDs que sejam apaixonados por gerar inovação, movidos por grandes desafios, que amem tecnologia e que queiram protagonizar a transformação da Gupy na melhor e maior empresa de Recrutamento Tech do país.
Vaga: Pessoa Desenvolvedora Fullstack
Nível: Pleno/Sênior
Modelo de contratação: CLT 
Requisitos: Experiência com React.js e Node.js,  computação em nuvem e banco de dados. 

Para mais informações: https://byintera.in/gupyfsgh

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
