### ISSUE TITLE
[Belo Horizonte] Desenvolvedor(a) Front End na SYDLE

### ISSUE THREAD

**Issue by veronica-veloso** [frontendbr/vagas#4192]
> Vaga Remota durante a pandemia

**Quem somos?**

Somos uma empresa de produtos de tecnologia corporativa. Temos mais de 15 anos de história e estamos só no começo! Vivemos um forte crescimento no mercado nacional e internacional, sem perder a nossa essência que é conciliar desafios técnicos com um clima leve e colaborativo. Atualmente somos reconhecidos como a melhor empresa de TI para trabalhar do país e, há mais de 10 anos, estamos entre as melhores empresas do Brasil e da América Latina. Ficamos muito felizes com tanto reconhecimento, o que nos motiva a fazermos ainda mais.

**Quer fazer parte do nosso time? Confira o que é preciso.**

- Formação em Ciência da Computação, Sistemas de Informação, Engenharias ou afins;

- Experiência com front-end, incluindo CSS e HTML;

- Conhecimento em JavaScript;

- Experiência com frameworks JS (React, React Native, Angular).

**O que você irá fazer no seu dia a dia?**

- Desenvolver sistemas e aplicações, a partir das solicitações recebidas;

- Otimizar as interfaces para melhorar a performance e garantir a boa usabilidade;

- Definir e aplicar boas práticas de desenvolvimento, planejando com a equipe a organização do código front end;

- Realizar as manutenções necessárias e monitorar o desempenho e performance dos sistemas e aplicações desenvolvidas;

- Dar suporte no que tange a viabilidade técnica de desenvolvimento de novas features e interfaces.

**Se interessou pela SYDLE e pela oportunidade?**
Será incrível receber seu currículo e saber do seu interesse pelo nosso time! Cada currículo recebido é avaliado pelo nosso RH e, caso o seu seja selecionado, entraremos em contato convidando para nossa seleção. As candidaturas são realizadas em nosso site, por isso pedimos que cadastre seu currículo no link a seguir:  http://bit.ly/desenvolvedor-front-end-sydle

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
