### ISSUE TITLE
[São Paulo] Front-end Developer numa Scale-up no CUBO

### ISSUE THREAD

**Issue by wadaeko** [frontendbr/vagas#4193]
## Uma SCALE-UP que fica no maior centro de inovações do Brasil - CUBO
Não mais uma startup, abre novas posições para um novo projeto em uma estrutura já robusta e consolidada no mercado.

## Descrição da vaga

**Desafio de um projeto inovador usando de um conhecimento diferenciado de Programação Funcional.**
Se não sabe do que se trata, não é o perfil adequado.
Quer avançar no seu conhecimento com um case exclusivo em uma empresa em franco crescimento com profissionais de alto nível de conhecimento? Esse é o DESAFIO aqui!!

## Local

CUBO Itaú - maior hub de inovação do Brasil agregando mais de 300 startups [SP], [São Paulo], [Vila Olímpia]

## Requisitos

**Obrigatórios:**
- PROGRAMAÇÃO FUNCIONAL
- TYPESCRIPT
- JS/ES6 (DOM)
- REACT HOOKS e APOLLO CACHE
- JEST
- Biblioteca de estrutura de dados Immutable JS ou MoriJS
- Git / Git-Flow / Linux
- CSS (SASS ou LESS)
- noção de Reactive Programming / RxJS
- mecanismo de autorização JWT
- 1 ano de experiência em GraphQL

**Desejáveis:**
- 5 anos de experiência em desenvolvimento
- Inglês intermediário (leitura e escrita)
- melhores práticas / code reviews
- experiência Agile / Scrum / Dual Track
- boa comunicação e cumprimento de prazos

**Diferenciais:**
- conhecimentos em benchmarking e otimizações
-Isomorphic React
- Docker / Kubernetes
- Familiaridade com CICD
- Familiaridade com BDD
- Chrome Dev Tools debugging
- componentização em React
- experiência em open-source
- inglês avançado

## Benefícios

- 13o.
- férias remuneradas
- assistência médica sem comparticipação
- VR

**Diferenciais:**

- estar no maior hub de inovação do Brasil, convivendo com profissionais dos mais variados segmentos e aprendendo e absorvendo know-how e redes de contatos com mais de 300 das maiores startups brasileiras.
- remuneração compatível à listagem de conhecimentos e experiências, chegando a CINCO DÍGITOS

## Contratação

PJ ou CLT (o que preferir) com o benefício válido para qualquer uma das modalidades

## Como se candidatar

Por favor envie um email para wada@ekodesign.com.br com seu CV anexado - enviar no assunto: Vaga FrontEnd Power 
OU entre em contato direto pelo WhatsApp (11) 98199-9529 - Wada

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
Sendo tech-hunter estou encarregado em dar todos os detalhes em mãos para o CTO para seleção

#### Alocação
- Presencial com possibilidade para negociar alguns dias remoto (treinamento exige o presencial)

#### Regime
- CLT
- PJ

#### Nível

- Pleno
- Sênior
- Ninja

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by wadaeko** [comment]
Boa noite,

A vaga continua sim aberta, porém é de difícil preenchimento.

Obrigado


Em seg, 29 de mar de 2021 às 21:33, Felipe Fialho ***@***.***>
escreveu:

**Comment by SaMatheus** [comment]
@wadaeko  tenta ampliar a vaga para Júnior, que tenho certeza que vc fecha ela bem rápido e treina esse júnior pra atender as necessidades da empresa. Talvez seja melhor do que esperar Sêniores aparecer.

**Comment by RafaelN3103** [comment]
Boa noite,

Se abrir para júnior gostaria de me candidatar.



Em seg, 29 de mar de 2021 22:45, Matheus Fernandes de Sá <
***@***.***> escreveu:
