### ISSUE TITLE
[Rio de Janeiro] Front-end Developer na Macher Tecnologia

### ISSUE THREAD

**Issue by antabi-mt** [frontendbr/vagas#4194]
> Vaga Remota durante a pandemia

## Nossa empresa

Somos uma empresa em pleno crescimento, com um ambiente bacana de colaboração e aprendizado. 

Nossa missão é simplificar interações entre empresas e seus clientes através da tecnologia, desenvolvendo soluções customizadas, provendo suporte, realizando consultoria e treinamentos para deixar nossos clientes mais preparados para competir no ambiente Digital.

## Descrição da vaga

Esta é uma oportunidade para trabalhar em um projeto internacional (outsourcing), onde o inglês para conversação é necessário. Nosso cliente está no ramo das Fintechs e buscamos um(a) desenvolvedor(a) em ReactJS para o desenvolvimento da nova versão de seu sistema.

Como desenvolvedor(a), esperamos que você seja orientado(a) a resultados, responsável por suas entregas, sendo hábil no trabalho colaborativo e participativo em um time. 

**No dia-a-dia- você fará:**
- Compreender os objetivos do projeto e interagir com outros membros da equipe para implementar as melhores soluções técnicas disponíveis;
- Desenvolver a nova versão - a "Next Generation" - de um sistema existente e expandi-lo através do uso de novas tecnologias e plataformas;
- Prototipar, Redesenhar e Customizar interfaces conforme a necessidade do cliente;
- Utilizar as boas práticas de mercado para desenvolvimento e segurança de aplicações;
- Reunir-se com o cliente e com o time, interagindo continuamente e oferecendo informações e atualizações conforme planejado;
- Buscar soluções e interagir com os demais membros do time visando o atingimento dos objetivos propostos.

## Local

Remoto durante a pandemia e Escritório no Rio de Janeiro/RJ, no bairro da Glória. O profissional precisa no Rio de Janeiro.

## Requisitos

**Obrigatórios:**
- Curso superior completo em TI (e suas variantes), com experiência relevante na área de atuação e/ou função;
- Experiência de trabalho com equipes pequenas/médias (6-10 profissionais);
- Compreensão (e aplicação) dos conceitos de User Experience (UX);
- Desejo de aprender novas tecnologias e rapidez na sua implementação;
- Ter o inglês para conversação é pré-requisito.
- Experiência com HTML, HTML5, JS, jQuery, CSS, SASS
- ReactJS
- Conhecimento em arquitetura de APIs / JSON / REST;
- Conhecimentos intermediários em SQL (MySQL, Oracle, MS-SQL);
- Conhecimentos em Git e/ou similares (controle de versão, pipelines, integração, etc);

**Desejáveis:**
- Conhecimento em ambientes Cloud e seus serviços (preferencialmente AWS, Azure);
- Microsserviços e segurança de APIs;
- Experiência em ambiente Linux;

## Benefícios
- Plano de saúde Sul América
- VT e VR (ou VA)

**Diferenciais:**
- Quando presencial, ambiente estruturado em um dos maiores centros de coworking mundiais;
- Oportunidade de aprendizado
- Projeto desafiador!

## Contratação
- CLT

## Como se candidatar
Por favor envie um email para rh@machertecnologia.com.br com seu CV anexado - enviar no assunto: Vaga ReactJS

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 07 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@machertecnologia.com.br

#### Alocação
- Alocado

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
