### ISSUE TITLE
[REMOTO] FullStack Developer na Trading365

### ISSUE THREAD

**Issue by therck1** [frontendbr/vagas#4196]
## Nossa empresa

Somos uma startup em estado inicial, no mercado de trading esportivo.

## Descrição da vaga

Você irá trabalhar no desenvolvimento de um projeto relacionado ao mercado de apostas esportivas

## Local

Remoto

## Requisitos

**Obrigatórios:**

- React
- Node
- Python
- Mysql

**Desejáveis:**
- Redes

## Contratação

PJ a combinar

## Número de vagas
- 2

## Como se candidatar

Por favor envie um email para therq1ck@outlook.com  com seu CV anexado - enviar no assunto: Vaga NodeJS

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: therq1ck@outlook.com

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
