### ISSUE TITLE
[São Paulo] Front-end Developer na PagSeguro

### ISSUE THREAD

**Issue by DanieleUOL** [frontendbr/vagas#4199]
O PagSeguro foi criado para oferecer soluções inovadoras, simples e seguras em meios de pagamento. Trabalhando conosco, você tem a oportunidade de fazer a diferença na vida de milhões de brasileiros e construir novas formas de se fazer e receber pagamentos.

Trabalhamos em times multidisciplinares e cultivamos uma filosofia de trabalho ágil e enxuta, com as áreas de Tecnologia e de Negócios trabalhando lado a lado para criar produtos que evoluam de forma interativa para entregar valor aos clientes.

## Descrição da vaga

Principais atividades
• Garantir que a experiência levada aos usuários, seja a melhor possível e aderente ao nosso design system e à nossa identidade visual. 
• Ser um agente integrador, com comunicação eficiente para unir as ideias de desenvolvedores de back-end, POs, UI e UX, entre outros envolvidos nos projetos. 
• Avaliar, discutir e definir arquiteturas de sistemas novos e propor melhorias para os atuais, promovendo a coesão técnica e a consistência dos processos de negócio como base para solucionar os desafios. 
• Contribuir na evolução do design system. 
• Cuidar da monitoração do ambiente e criar ações proativas que garantam a sua estabilidade. 
• Manter contato com a equipe de segurança da informação para garantir a confiabilidade dos sistemas. 
• Trabalhar de forma colaborativa. 
• Atuar com métodos de gestão ágil e com melhoria contínua.

## Local

Remoto ou Escritório em São Paulo

## Requisitos

**Obrigatórios:**
• Superior em Tecnologia da Informação ou áreas correlatas.
• Experiência em desenvolvimento de aplicações web utilizando JavaScript e ES6+. 
• Experiência com React + e Redux. 
• Experiência em formatação com CSS3, (Sass e LESS). 
• Experiência em realizar a integração com APIs RESTful. 
• Conhecimentos em testes unitários utilizando Jest, Enzyme e React Testing Library. 
• Experiência com a aplicação de versionamento com Git. 

**Desejáveis:**
• Experiência com programação funcional, mindset reativo.
•  Conhecimento de design patterns. 
• Experiência com Next.js e Server Side Rendering (SSR). 
• Experiência em arquitetura de integração com microsserviços (API Gateways, servidores web, BFF e Express.js). 
• Experiência em formatação avançada: BEM, JSS, e Styled Components. 
• Conhecimento de DevOps (CI/CD, Cloud AWS, Jenkins, Docker, e Kubernetes). 
• Conhecimento sobre boas práticas de usabilidade. 
• Conhecimento de tendências em tecnologias e engajamento na comunidade. 
• Inglês intermediário. 

## Benefícios
- Plano de saúde/Odonto
- Seguro de vida
- VR 
- PPR

## Contratação

CLT

## Como se candidatar

Por favor envie um email para dcosilva@uolinc.com seu CV anexado - enviar no assunto: Vaga Front End Pleno

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
