### ISSUE TITLE
[São Paulo] Desenvolvedor Back-End Junior - ABInBev 

### ISSUE THREAD

**Issue by libanio** [frontendbr/vagas#42]
## Descrição da vaga

Vagas para Desenvolvedor BackEnd Junior (PHP, Ruby on Rails) - ZX Ventures, Disruptive Growth Unit of AB-Inbev

www.zx-ventures.com

Se você acabou de se formar e tem interesse em trabalhar com desenvolvimento em um ambiente Startup , não deixe de enviar seu CV.
Perfil: Buscamos pessoas com espírito empreendedor e que procuram rápido crescimento profissional, trabalhando alavancado com métodos ágeis em um time de alto nível. Queremos desenvolvedores com ótima formação e poder de execução para compor nosso time de desenvolvimento no escritório de São Paulo.
## Local

Itaim - São Paulo
## Benefícios
- bonificações acima da média do mercado ($$$)
- ambiente Startup
- Happy Hour com Open Bar de cerveja artesanal/importadas/especiais :dancer :D
- vale refeição
- plano de saúde
- flexibilidade de horário
- trabalhar com profissionais (incluindo desenvolvedores) de altíssimo nível
## Requisitos
- já formado em faculdades de referência (USP, ITA, UNICAMP, UNESP, ...)
- experiência em desenvolvimento BackEnd

**Obrigatórios:**
- formado

**Desejáveis:**
- conhecimento em PHP
- conhecimento em Ruby on Rails
- inglês intermediário/avançado
- formação preferencialmente em áreas relacionadas a exatas (computação/matemática...)  
- espírito empreendedor
- conhecimento em SCRUM / XP
- conhecimento em Design Patterns
- noções de User Experience (UX)
- noções de User Interface (UI)

**Diferenciais:**
- projetos de alto nível no portifólio
## Contratação
- CLT
## Nossa empresa

O Grupo AB-InBev, maior grupo cervejeiro do mundo e uma das maiores empresas de bem de consumo do mundo, está iniciando uma nova área denominada Disruptive Growth que tem o intuito de trazer novas tecnologias e inovação disruptiva ao grupo gerando impacto global.
Ambiente de trabalho: Estamos dentro de uma das maiores empresas do mundo com profissionais bastante experientes, porém prezamos por um ambiente descontraído, com horários flexíveis, remuneração meritocrática, hierarquia reduzida e muito espaço para novas idéias. 
## Como se candidatar

Por favor, envie um email para diego.libanio@ambev.com.br com seu CV anexado.
Enviar como assunto: Vaga ZX - BackEndJr.

**Comment by LFeh** [comment]
Boa sorte.

**Comment by grippado** [comment]
A Descrição dessa vaga está repetida com a vaga de Front-End, é isso mesmo, ou vai ser atualizado para os requisitos de Back-end?

**Comment by libanio** [comment]
Não, são duas vagas... Acabei de fazer os ajustes! Valeu!!!

**Comment by fabioinfo** [comment]
Linda vaga, lindos benefícios #valeCervejas na próxima eu me candidato.

**Comment by LFeh** [comment]
@libanio A vaga foi preenchida?

**Comment by libanio** [comment]
Ainda existe vaga

**Comment by mtmr0x** [comment]
Oi @libanio acho que passou (BASTANTE) despercebido isso, mas a fim de manter um padrão para as vagas da comunidade de Front End, precisamos manter essas vagas aqui apenas para Front Ends.

Eu bati uma pesquisa aqui e achei um lugar legal para publicar essa sua vaga: https://github.com/phpdevbr/vagas

Eles fizeram um fork desse mesmo repositorio e têm vagas lá com o foco que precisa. Acredito, inclusive, que terá mais sucesso por lá. Poderia me dar um ok fechando sua Issue?

Desculpe a confusão de nosso lado.

**Comment by mtmr0x** [comment]
@libanio eu fechei aqui já. :) se precisar de qualquer coisa para as vagas de front end, ficaremos felizes em ajudar.
