### ISSUE TITLE
[Santana de Parnaíba - SP] Front-End Developer na Buscapé Company

### ISSUE THREAD

**Issue by paulinhapenedo** [frontendbr/vagas#420]
## Descrição da vaga
Olá pessoal, tudo bom? Temos vagas para desenvolvedores aqui na Buscapé Company.
As vagas são para trabalhar no portal Buscapé, com uma stack bacana com Node + React (com server side rendering) + Redux. Inclusive, uma das vagas é a minha hehe

Você irá participar ativamente da concepção e do desenvolvimento de novas features e será responsável por entregar a melhor experiência para o usuário Buscapé, com foco em performance, animações e interações de fácil uso.

As vagas são para Pleno/Sênior e há uma iniciativa para trabalho remoto em alguns dias da semana.

## Local
Santana de Parnaíba - São Paulo

## Benefícios
- Pacote Alimentação/Refeição de 800 reais (você pode escolher quanto quer no VA e no VR)
- Vale Combustível ou VT e/ou Fretado da empresa
- Convênio Médico Sulamerica
- Convênio Odontológico
- Auxílio Creche
- Convênio com GymPass
- Frutas no café da manhã
- Máquina de snacks saudáveis
- Quick Massage toda semana
- Auxílio idioma
- Videogame, pebolim, sinuca, bateria, guitarra e contrabaixo no lounge
- Sala de descompressão
- PLR

## Requisitos

**Obrigatórios:**

- 1 ano de experiência com React
- Experiência com Redux em grandes aplicações
- Experiência com Node em grandes aplicações
- Experiência com HTML semântico
- Experiência com CSS (usamos Stylus como preprocessador, BEM, ITCSS)
- Experiência com JS nativo (ES2015 / ES2016)

**Desejáveis:**

- Testes em JS (Mocha, Chai, Sinon)
- Sketch/Photoshop (para exportar assets)

## Contratação

CLT Full

## A empresa

A Buscapé Company é a líder de comparação de preços na internet e está expandindo o seu negócio para o marketplace. Somos movidos a desafios e respiramos tecnologia com o objetivo de auxiliar o consumidor a fazer a melhor compra na internet.
Hoje estamos passando por uma reestruturação da stack de tecnologia e buscamos pessoas que queiram construir a nova Buscapé com a gente!

## Como se candidatar

[Temos um teste que precisa ser feito](https://github.com/buscape-company/exercicios/tree/master/frontend). Você não tem um timebox determinado para enviá-lo e também pode escolher onde hospedá-lo (github, bitbucket...).

Ao finalizar, envie o link do repositório para o e-mail julivan.santos@buscapecompany.com junto com o seu CV atualizado - enviar no assunto: Vaga Front-End Developer

**Comment by kvnol** [comment]
Que vaga linda, mas ainda tenho que estudar bastante! :heart:

**Comment by paulinhapenedo** [comment]
@kvnol vê o teste e arrisca :) aqui o pessoal tem o costume de trocar conhecimento com links pelo Slack, BP talks a cada 2 semanas sobre N assuntos (de tecnologia, produto, UX, QA), fóruns focados em agilidade. Por aqui, só não aprende e não cresce quer realmente não quer....

**Comment by kvnol** [comment]
@paulinhapenedo farei isso! ♥

**Comment by LFeh** [comment]
Bela vaga.

@kvnol para de bobeira e faça o teste, no minimo irá aprender e se preparar para os proximos.

**Comment by WandersonAlves** [comment]
Caramba, se fosse um Vuezinho em vez de React kkkkk

**Comment by LFeh** [comment]
@WandersonAlves Quase a mesma coisa cara, isso não devia te impedir ;)

**Comment by WandersonAlves** [comment]
@LFeh Sim sim, concordo kkkkkkk bom que toco pra frente meu "projeto de conhecimento" "full reactive" (Aprender vue e react ❤️)

**Comment by LFeh** [comment]
Angular, React e Vue é a mesma coisa, se sabe um, sabe os outros :)

**Comment by paulinhapenedo** [comment]
@LFeh valeu por adicionar o teste ao seu repo de challenges! =)
@WandersonAlves digo o mesmo que disse pro Kevin: arrisca!

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by paulinhapenedo** [comment]
Pode fechar, @LFeh :)
