### ISSUE TITLE
[Remoto] Front-end Developer na Catho

### ISSUE THREAD

**Issue by palomabelon** [frontendbr/vagas#4200]
> Vaga Remota durante a pandemia

## Nossa empresa
Somos uma empresa de tecnologia e o nosso principal produto é o nosso site para busca de empregos. Somos Criativos, Antenados, Apaixonados pelo Cliente e estamos sempre Ligados no Negócio. Trabalhamos buscando a Excelência Pura, de forma colaborativa e plural. Acreditamos que Juntos Somos +. 

## Descrição da vaga
Na Catho você terá a responsabilidade de atuar em um time multidisciplinar em formato de squad. 
Nosso time atua com desenvolvimento web e está responsável pelo design system da Catho . Dentre os desafios estão entender as necessidades do cliente, acompanhar tendências do mercado e usar o melhor da tecnologia para disponibilizar features com qualidade e rapidez. No dia a dia, você terá a oportunidade de contribuir com suas ideias e agregar valor continuamente para os diversos candidatos que usam a nossa plataforma para a busca de uma nova oportunidade de trabalho.

## Local
Remoto

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento Web;
- Conhecimento nas linguagens Javascript ( React), CSS3 e  HTML5;
- Testes automatizados (conceito, benefícios, utilização e ferramentas);
- Virtual DOM;
- Arquiteturas de aplicação Javascript;
- Metodologias ágeis (Scrum e Kanban);
- Graduação em Ciência da Computação ou área correlata.

**Desejáveis:**
- Conhecimento em acessibilidade;
- Conhecimento em Atomic Design.

## Benefícios

-Assistência Médica
-Assistência Odontológica
-Seguro de vida
-Convênio com Farmácia
-Convênio com Academias
-Auxílio Creche
-Cartão Flash Benefícios
-Participação nos lucros
-dayoff

## Contratação
CLT

## Como se candidatar
Por favor envie um email para paloma.leao@catho.com com seu CV anexado - enviar no assunto: Vaga Front-end 

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: juliana.pereira@catho.com

#### Nível
- Pleno

**Comment by palomabelon** [comment]
Por favor,  remover a label "remoto durante a pandemia". @felipefialho

**Comment by daviesdesenvolvedor** [comment]
Tenho interesse.

**Comment by felipefialho** [comment]
> Por favor, remover a label "remoto durante a pandemia". @felipefialho

Pegou a label porque está na descrição 😋

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
