### ISSUE TITLE
[Itaperuna] Front-end Developer na iNova

### ISSUE THREAD

**Issue by carlosoliveiradev** [frontendbr/vagas#4201]
## Nossa empresa

A iNova nasceu da expertise de transformar pessoas em influencers digitais, através do melhor que elas têm a oferecer. Transformamos marcas e pessoas em expressões digitais, através de uma metodologia própria.

## Descrição da vaga

Vaca focada para o desenvolvimento de landing pages e sites instucionais utilizando **Wordpress**.

## Local

Remoto ou Escritório, [RJ], [Itaperuna], [Aeroporto]

## Requisitos

**Obrigatórios:**
- Experiência com Wordpress, Bootstrap, CSS, JavaScript e jQuery.

**Desejáveis:**
- noções de UX/UI
- velocidade no desenvolvimento de landing pages principalmente

**Diferenciais:**
- Caso venha trabalhar de forma presencial, vai encontrar um ambiente descontraído  com puffs para descansar, mesa de ping pong e arcade.

## Contratação

PJ ou CLT a combinar

## Como se candidatar

Por favor envie um email para tequero@inovany.com.br com seu CV anexado - enviar no assunto: Vaga Front-end na iNova

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dia após cada processo.
E-mail para contato em caso de não haver resposta: carlosoliveira@inovany.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
