### ISSUE TITLE
[Remoto] Front-end Developer na Pagar.me

### ISSUE THREAD

**Issue by laisrosalini** [frontendbr/vagas#4202]
## Nossa empresa

**Já conhece o Pagar.me?** 

Somos uma empresa focada em desenvolver soluções para os mercados de pagamento e financeiro no Brasil e fazemos parte do Grupo Stone Co. De pequenas lojas e startups a grandes e-commerces e marketplaces, criamos uma estrutura de pagamentos poderosa e flexível para atender diferentes clientes. 

Aqui, você irá trabalhar com um time apaixonado por desafios, focado no atendimento personalizado aos nossos clientes e em busca dos melhores resultados em suas entregas. Quer mais? Tudo isso em um ambiente descontraído e com uma galera que é referência no mercado de tecnologia!

Conheça mais sobre a nossa empresa [aqui](https://pagar.me/)!

#Como trabalhamos:

Nossos produtos utilizam um ecossistema baseado em React no front-end, possuímos um design system e sua implementação como um conjunto de bibliotecas de componentes utilizando React e CSS.
 
Ainda possuímos uma dashboard legada escrita em Angular.js, a qual damos manutenção. Sempre buscamos as ferramentas mais adequadas para resolver os nossos problemas, sem nos prendermos a uma tecnologia específica.
 
Gerenciamos nossa infraestrutura através de infrastructure-as-code, deployando nossas aplicações na AWS. Todo serviço que escrevemos tem uma boa cobertura de testes, consegue ser facilmente escalável do ponto de vista de infraestrutura, e tem monitoramento ativo sobre ele.
 
Por sermos uma empresa que tem produtos financeiros, somos extremamente cuidadosos com tudo que colocamos em produção e temos padrões altos de qualidade, mas sem deixar de perder agilidade e velocidade no desenvolvimento dos produtos

#Open Source

Nós <3 Open Source. Nós usamos muita coisa que veio da comunidade, e queremos retribuir. Além de compartilhar nossas talks no youtube, nós também decidimos deixar open source o código de alguns dos nosso serviços que são usados em produção por nossos
clientes todos os dias. Alguns exemplos:
 
[Superbowleto](https://github.com/pagarme/superbowleto) - Nosso microsserviço de registro de boletos, por onde passam todos os
boletos do Pagar.me 
 
[TLDR](https://github.com/pagarme/tldr) - Nosso microsserviço para armazenar e mostrar recibos
 
[Pilot](https://github.com/pagarme/pilot) - A nova versão da nossa dashboard, que também está 100%

[Café com Testes](https://github.com/pagarme/cafe-com-testes) - Repositório com dicas de teste e boas práticas 

## Descrição da vaga

**O que é ser Pessoa desenvolvedora Front-end | Software Engineer Front-end.?** 

 Aqui você vai colaborar com product managers, designers e software engineers para identificar oportunidades e implementar soluções e produtos para os nossos clientes. Desenvolver serviços e sistemas. Melhorar arquitetura e ou design dos sistemas atuais;

Buscamos alguém que se envolva ativamente na construção de produtos do começo ao fim, desde a experimentação, design, implementação e deploy, até o feedback dos clientes;

Trabalhar em conjunto com todo o time de tecnologia, revisando o trabalho de outras pessoas, participando de decisões importantes de produto e tecnologia, e garantindo a saúde dos nossos serviços.

## Local

Remoto ou Escritório, [SP], [São Paulo], [Vila Olímpia]

## Requisitos

**Obrigatórios:**
👾 Experiência com CSS, HTML e Javascript;

👾Experiência no desenvolvimento de uma aplicação React em produção;

👾Experiência com testes automatizados;

👾Experiência no desenvolvimento de interfaces mobile first.

**Desejáveis:**
👾 Experiência com aplicação de um design system em um produto;

👾 Experiência com desenvolvimento em React Native;

👾 Experiência com Amazon AWS (S3 & Cloudfront);

👾 Experiência na implementação de processo de integração contínua e entrega contínua.

## Benefícios

🩺 Plano de Saúde e Odontológico Bradesco (sem coparticipação)

🚌 Vale transporte

🥗 Vale Refeição e/ou Vale Alimentação

💚 Seguro de Vida

💪 Gympass

👶 Auxílio Creche

🕗 Horário flexível

## Contratação

CLT

## Como se candidatar

Através desse [link](https://boards.greenhouse.io/pagarme/jobs/4208606003)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: lais.penedo@mundipagg.com

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
