### ISSUE TITLE
[Portugal] Front-end Developer na Integer Consulting 

### ISSUE THREAD

**Issue by Catia987** [frontendbr/vagas#4203]
A INTEGER, uma empresa de consultoria na área das tecnologias, com mais de uma década de presença no mercado português, está à procura de Front-end Developer(m/f), com fortes habilidades de comunicação e sentido de responsabilidade e de trabalho em equipa.

#Descrição da vaga

Este pode ser o desafio perfeito para ti se tens:

Bacharelado em Engenharia da Computação ou similar;

4 anos de conhecimentos em Javascript, Angular JS, Jquery, CSS, HTTP e HTML, React.Js, Vue.Js and/or Angular;
Fluência em Inglês;
Se tens o amazINg talent pretendido e queres fazer parte da equipa INTEGER, responde a este anúncio com o teu CV atualizado para catia.jorge@integer.pt

Participar neste projeto significa a integração numa empresa sólida em crescimento e numa equipa jovem e dinâmica. #jumpIN

**Comment by hallss93** [comment]
presencial ou remoto?

**Comment by Catia987** [comment]
> presencial ou remoto?

Presencial :)
Obrigada

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
