### ISSUE TITLE
Remoto <EDTECH> Desenvolvedor(a) Frontend React

### ISSUE THREAD

**Issue by HUNTINGTECH** [frontendbr/vagas#4204]
A HUNTINGTI é uma consultoria de recrutamento e seleção de profissionais de tecnologia e digital. Atuamos de forma global com vagas no Brasil e na União Europeia. 
Estamos apoiando um cliente (EDTECH) na busca por um profissional Desenvolvedor(a) Frontend React
Descrição da empresa:
 Edtech com plataforma digital online, que permite ao aluno aprender inglês. Projeto global com presença em mais de 55 países.

Descrição da oportunidade:
 Compor uma das squads e atuar no desenvolvimento frontend de projetos, componentes, libs, etc. 
Atuar na sustentação, melhoria e novas implementações. 
Contribuir para o crescimento de produtos digitais de forma global.
Desenvolver aplicações em Javascript, React e nextJS;
Construir Módulos, libs, componentes e projeto;
Analisar e propor soluções de software;
Auxiliar na estimativa de prazos;
Atuar com time multidisciplinar;
Atuar no papel de líder de boas práticas e arquitetura frontend.

Requisitos:
Sólidos conhecimentos em HTML5 e pré processadores CSS, Javascript moderno (ES6+), React, Hooks, Context API, GIT.
Expertise em aplicações web e habilidades associadas (REST, HTTP, web services.
Conhecimento em GIT Flow, SSR, NextJS, Redux & Redux saga, styled, componentes e React router.

Desejáveis:
Conhecimento em automatização de testes; TDD, padrões de projetos e arquitetura (Design Patterns) – clean Architecture, SOLID, Google AMP (AMP Project), Progressive Web APP (PWA); experiência em desenvolvimento de sistemas de alta disponibilidade, Webpack/Gulp, ter construído ou trabalhado com design system.

Vaga: Remota
Contratação: CLT
Nível: Especialista
Tem interesse nessa oportunidade?
Ou envie um e-mail com o seu currículo para roberta@huntingti.com com o assunto: Desenvolvedor(a) Frontend React
Ou me chama lá no linkedin https://www.linkedin.com/in/robertasantoshrtech/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
