### ISSUE TITLE
[Remoto] Front-End Developer na Cyza (California)

### ISSUE THREAD

**Issue by cyzainc** [frontendbr/vagas#421]
We are a startup based in Newport Beach, California, developing an incredible and innovative online marketplace platform (web & mobile based). 

We are interested in hiring talented and experienced frontend programmers. Must have solid experience and knowledge of the following front-end technologies: 

CSS3, SASS, HTML5, JQuery, ES6 JavaScript, Gulp, and Webpack.

Our current backend is in Golang web API and frontend consists of above technologies.

This is a remote position, you will be working from your own home/office and requires a longer-term commitment of at least part-time but we prefer full-time. Basic conversational English is enough to work with our team and you do not need to be fluent. Good and reliable internet connection is a must. 

Must have strong interpersonal and communication skills and be comfortable with a fast paced working environment. Able to work independently and also be productive in a team. Implement new features and work with existing code. Analysis of bugs and optimization issues. Help in establishing new development frameworks and systems. 

We look forward to learning about you and your knowledge. Please apply by emailing to jobs@cyza.com  and including the following:
1- Basic resume that describes your current and past  jobs and education/training
2- Describe your availability and preference for full-time or part-time

**Comment by grippado** [comment]
@LFeh I believe that if you edit the position, and place the title [CALIFORNIA COMPANY HIRING TALENTED FRONTEND DEVELOPERS- REMOTE POSITION] with which it was disclosed in the body of the same, leaving the title in the pattern of the repo, can add value for disclosure.
And by the way, that a fuc**** and sensational position!!

**Comment by jvcjunior** [comment]
Is this position still available?
