### ISSUE TITLE
[Remoto] Senior Front-End Developer na KnowBe4

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#4210]
## Descrição da vaga: 
 <p>El Pescador is an independent subsidiary of KnowBe4, Inc., the world’s largest security awareness training and simulated phishing platform. El Pescador will be the first company in Brazil to introduce simulated phishing as a way to help manage the ongoing problem of social engineering. Its primary focus will be research and expansion into the Brazilian market.The atmosphere has a start-up feel but with the power and backing of a multinational company.</p>
<p></p>
<p>To learn more about our team and office culture in Brazil, visit the following links.</p>
<p></p>
<p><a href="https://www.glassdoor.com.br/Vis%C3%A3o-geral/Trabalhar-na-KnowBe4-EI_IE969384.13,20.htm" target="_blank">Glassdoor</a> | <a href="https://www.linkedin.com/company/knowbe4/life/brazil" target="_blank">LinkedIn</a>&nbsp;</p>
<p></p>
<p>The Senior Front End Software Engineer is responsible for developing new and exciting products for KnowBe4’s customers, alongside other engineers in a fast-paced, agile development environment.</p>
<p></p>
<p><strong>Responsibilities:</strong></p>
<ul>
<li>Design and develop applications in an Agile development environment</li>
<li>Design and develop front-end end solutions</li>
<li>Rapidly prototype and refine applications based on user experience feedback</li>
<li>Collaborate with product managers and fellow engineers to establish and refine technical requirements</li>
<li>Maintain quality standards for developing products</li>
</ul>
<p></p>

## KnowBe4: 
 <p>KnowBe4, Inc. is the provider of the world's largest security awareness training and simulated phishing platform. KnowBe4 enables organizations to manage the ongoing problem of social engineering by helping them train employees to make smarter security decisions, every day. Tens of thousands of organizations worldwide use KnowBe4’s platform to mobilize their end users as a last line of defense and enable them to make better security decisions, every day.</p>

<p>We have ranked a best place to work for women, millennials, and in technology nationwide by Fortune Magazine as well as #1 or #2 in The Tampa Bay Top Workplaces Survey for the last five years.</p><a href='https://coodesh.com/empresas/knowbe4'>Veja mais no site</a>

 ## Habilidades: 
 - API 
- Angular.js 
- C# 
- HTML 5 
- Java 
- Javascript 
- Go Lang 
- CSS 3 
- RESTful

## Local: 
 100% Remoto

## Requisitos: 
 - Bachelor’s Degree in Computer Science or 8+ years of programming work experience 
- MS or equivalent plus 3+ years of programming work experience 
- Professional experience programming in Javascript Language 
- Strong understanding of Typescript 
- Experience designing applications using declarative frameworks like VueJS, React, SwiftUI 
- An eagerness to work with the latest technologies and expand your skill set 
- Able to ship code quickly and efficiently 
- Creativity, initiative and acute attention to detail 
- Strong written and verbal communications skills in English and Portuguese. 
- Preferred: 
- Able to leverage structured formats like JSON, YAML, XML and related technologies to build scalable, testable RESTful applications 
- Built applications with current and forward-facing web standards like CSS3 and HTML5 
- Effective communication skills with the ability to influence/collaborate with multiple teams to ensure there is no delay in new releases forecasted on the product roadmap 
- Ability to quickly grasp new languages (Golang, Python, C#, Java) 
- Has used automated unit testing tools

## Benefícios: 
 - Vale Refeição 
- Plano de Saúde 
- Plano Odontológico  
- Classpass  
- Previdência Privada 
- Seguro de Vida 
- Benefício Flexível

## Como se candidatar:
Candidate-se em: [Senior Front-End Developer na KnowBe4](https://coodesh.com/vagas/senior-frontend-developer-184723?origin=github&modal=open)

## Tempo médio de feedbacks:
 Costumamos enviar feedbacks em até 48 horas após cada etapa do processo. E-mail para contato em caso de não haver resposta: [alineb@knowbe4.com](mailto:alineb@knowbe4.com)

#### Alocação
Remoto

#### Regime
CLT

#### Nível
Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
