### ISSUE TITLE
[Remoto] Senior Front-End Developer na GeekHunter Brasil

### ISSUE THREAD

**Issue by MalletJorge** [frontendbr/vagas#4211]
# 👩‍💻 Pessoa Desenvolvedora  👨‍💻

Sua missão principal por aqui será realizar melhorias e criação de novas telas na nossa principal plataforma, numa abordagem Full-stack de desenvolvimento, com identificação e correção de erros e suporte aos experimentos da equipe!

Você vai se envolver em atividades de interação da nossa plataforma com APIs internas escritas em **Ruby** e Python e APIs de serviços externos dos quais somos clientes. Trabalhará com exportação de dados e construção de queries em bancos relacionais.
E o melhor é que você poderá contar com um time que ama cooperação, para lhe auxiliar e ajudar a coordenar as suas missões aqui dentro.

## 🤠 Você atuará em projetos ligados a:
+ Implementação Full-stack de novas funcionalidades da plataforma;
+ Identificação e correção de erros em funcionalidades já existentes;
+ Suporte a experimentos;
+ Entender muito bem os requisitos e escrever código claro, simples e otimizado utilizando orientação a objetos;
+ Trabalhar para melhorar as soluções existentes da GeekHunter;
+ Aprender e aplicar novas tecnologias para otimizar nossos processos e produtos.

## 🤠 Experiência em desenvolvimento web Full-stack;
+ Experiência e conhecimento em JavaScript; 
+ Experiência com metodologias ágeis;
+ Conhecimento em HTML, CSS;
+ Conhecimentos em banco de dados relacionais (SQL);
+ Disponibilidade e motivação para aprender rápido e compartilhar conhecimentos;
+ Boa comunicação;
+ Autogestão (organização e planejamento);
+ Inclinação a abraçar desafios.

## 🚀 Nossos benefícios 
+ Vale-refeição/alimentação de R$ 600,00;
+ Assistência médica;
+ Assistência odontológica;
+ Um ambiente flexível e descontraído. Queremos que você se sinta motivado(a) para vir trabalhar até mesmo nas segundas de manhã!!
+ Gympass 

## 🚀 Informações sobre o contrato 
+ CLT 
+ 8 Horas por dia 
+ Estamos trabalhando 100% home-office no momento (não precisa estar em Floripa). No futuro você terá a possibilidade de flexibilizar para ir no escritório (se preferir).
## Labels 
+ Ruby 
+ Javascript
+ Python 
+ AWS
+ SQL

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
