### ISSUE TITLE
[Remoto] Front-end Developer na Conquest One

### ISSUE THREAD

**Issue by brunabritocq1** [frontendbr/vagas#4212]
> Vaga Remota durante a pandemia

## Nossa empresa

A Conquest One é uma empresa especializada em Staffing de TI, sendo eleita 9 vezes como uma GPTW e agora está em busca de uma pessoa apaixonada por tecnologia e inovação para uma oportunidade incrível no nosso time.

## Local

Remoto.

## Requisitos

**Obrigatórios:**
Requisitos: Desenvolvimento Frontend Angular 2+ e outros frameworks JS, como Vue.JS e React Native. Familiaridade com TDD.

## Contratação

PJ.

## Como se candidatar

Por favor envie um email para bruna.brito@cq1.com.br com seu CV anexado - enviar no assunto: Vaga Frontend

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 semana dias após cada processo.
E-mail para contato em caso de não haver resposta: bruna.brito@cq1.com.br

#### Alocação
- Alocado para cliente.
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by jonatasoc** [comment]
Olá, Bruna.

A carga horária desse trabalho é de 40h semanais?

Att.
Jonatas


Em seg., 1 de fev. de 2021 às 14:27, brunabritocq1 <notifications@github.com>
escreveu:

**Comment by brunabritocq1** [comment]
Jonatas, boa tarde!

Creio que seria algo em torno disso -  8hs p/ dia, horário comercial (média mensal 168hs).

Att,


[Código QR  Descrição gerada automaticamente] BRUNA BRITO
 Aquisição de Talentos
[cid:image003.png@01D6F8B5.98658F50]

BRZ: +55 (11) 2164.9500/ (11) 97145-0724
USA: +1 (415) 738.2085
www.conquestone.com.br<http://www.conquestone.com.br/>­­
   [cid:image004.png@01D6F8B5.98658F50] <https://www.linkedin.com/company/conquest-one>  [cid:image005.png@01D6F8B5.98658F50] <https://www.instagram.com/conquestonebr>  [cid:image006.png@01D6F8B5.98658F50] <https://pt-br.facebook.com/ConquestOne/>  [cid:image007.png@01D6F8B5.98658F50] <https://www.youtube.com/c/ConquestoneBr>


De: Jonatas de Oliveira Coêlho <notifications@github.com>
Enviada em: segunda-feira, 1 de fevereiro de 2021 15:57
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: Bruna Fernanda Castro Brito <bruna.brito@cq1.com.br>; Author <author@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [Remoto] Front-end Developer na Conquest One (#4212)

Olá, Bruna.

A carga horária desse trabalho é de 40h semanais?

Att.
Jonatas


Em seg., 1 de fev. de 2021 às 14:27, brunabritocq1 <notifications@github.com>
escreveu:

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
