### ISSUE TITLE
[São Paulo] Sr Front-end Developer na @Mazzatech

### ISSUE THREAD

**Issue by taianeuchoa** [frontendbr/vagas#4213]
> Vaga Remota durante a pandemia

## Nossa empresa
Nós da Mazzatech estamos apoiando empresa que detém aplicações web e mobile que atua como marketplace para venda de gás.

## Descrição da vaga
Nossos aplicativos de web são vitais para as nossas revendas parceiras e para os usuários internos. Além disso, oferecemos aos consumidores um aplicativo da web que facilita o pedido de gás de cozinha. É a ferramenta que milhares de pessoas usam todos os dias. Você fará parte de nossa equipe de desenvolvimento multidisciplinar que constrói soluções novas e inovadoras para nossos aplicativos web.
Você tem habilidades práticas de desenvolvimento e cria códigos de qualidade com um produto limpo, sustentável e reutilizável.
Você oferece uma ótima experiência (UX / UI).
Você gosta de estar ativamente envolvido nas discussões de design e implementação.
Você se sente confortável com um aumento de escala de tecnologia em ritmo acelerado, onde as prioridades podem mudar e tudo está em discussão.
Você adora compartilhar conhecimento e ajudar outras pessoas.
Você é capaz de conceituar, realizar e entregar projetos de forma eficaz, de forma independente, se necessário.
Você tem boas habilidades de comunicação

## Local
Remoto durante a pandemia. Após este periodo, atuará no escritório da empresa, próximo a Paulista.

## Requisitos
Você tem pelo menos mais de 3 anos de experiência com desenvolvimento moderno da Web.
É necessário um forte conhecimento de Javascript, porém nossos novos recursos são desenvolvidos usando Typescript.
Experiência na construção de aplicativos web responsivos usando HTML5 e CSS3.
Experiência com aplicativos de página única usando tecnologias modernas como React, Vue ou Angular.
Experiência com aplicativos de página única usando React. Conhecimento de como o conceito de fluxo é importante.
Confortável com programação orientada a objetos.
Forte compreensão dos princípios SOLID.
Você sabe como construir software testável.
Confortável com NodeJS + NPM, WebPack, Babel, ECMAScript 6, PostCSS e Jest
Fluente em Portugués - Inglês será um diferencial. 

Bônus se tiver:
Um bom conhecimento e entendimento de React;
Conhecimento de programação funcional;
Conhecimento do paradigma de programação reativa;
Compreensão dos diferentes tipos de teste, como Funcional (Unidade, Aceitação de Integração) e Não Funcional ;(Desempenho, Carga, Estresse, Segurança);
Capacidade de explicar soluções técnicas usando UML, mapas mentais ou qualquer outra prática.

## Benefícios
Bônus, baseado em metas pessoais, da equipe e da empresa;
Escritório despojado com espaço aberto e área de descompressão;
Sem código de vestimenta - Seja quem você é o dia todo, todos os dias;
Assistência médica;
Assistência dental;
Seguro de vida;
Vale-transporte e / ou combustível;
Cartão de benefício flexível Vee;
Parcerias com ZenKlub e TotalPass;

## Contratação
CLT a Combinar

## Como se candidatar
Por favor envie um email para taiane@mazza.tech com seu CV anexado - enviar no assunto: Vaga FrontEnd Sr.

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: taiane@mazza.tech

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
