### ISSUE TITLE
[REMOTO] Front-end Developer no DOT group 

### ISSUE THREAD

**Issue by gabriela-dot** [frontendbr/vagas#4215]
Somos o **DOT digital group** e a educação é o nosso negócio! Somos especialistas em **EdTech - Education Technology.** Aqui a tecnologia e a educação caminham juntas. A transformação que a educação promove é grande! Os nossos números e desafios também!

## Descrição da vaga
Precisamos de alguém que queira aprender sempre, que tope encarar desafios e que seja proativo. Precisamos de uma pessoa que seja fera em Front End para atuar no **time de Produto!** 

**As principais atividades serão:**

- Desenvolver interfaces para web;
- Realizar Front End;
- Apoiar na construção da arquitetura da informação dos projetos;
- Produzir multimídias.

## Local de trabalho

100% Remoto
Escritório da empresa localizado em Florianópolis - SC 

## Requisitos da vaga

**Obrigatórios**

- Conhecimentos em Vue. js; Javascript; React; Docker e Adobe XD.

**Desejáveis**

- Experiência com MariaDB e Postgres.

## Forma de contratação

PJ ou CLT

## Benefícios da empresa
- R$2.000,00 de verba para treinamento e desenvolvimento em 2021 (a empresa disponibiliza esse valor para que você invista em melhorias no seu aprendizado técnico)
- Contratação Home Office
- Horário flexível,
- R$528,00 de VR/VA, você ajusta como preferir
- Convênio médico com cobertura nacional sem custo
- Convênio odontológico
- Convênio de farmácia
- Auxílio-pandemia R$100,00
- Remuneração alinhada com o mercado 
- Trabalhar com tecnologia de ponta e uma equipe maravilhosa com quem você vai ter a possibilidade de aprender e ensinar todos os dias ;) 

## Sobre a empresa

Com mais de 24 anos de atuação, somos um dos maiores grupos nacionais de educação digital e pioneiros no mercado de Educação Comunicacional no país. Possuímos sede em Florianópolis, polo tecnológico no estado de Santa Catarina, temos escritórios também em São Paulo e Brasília. No mercado internacional, temos operação em Lisboa, Portugal.

## Como se candidatar

Candidate-se diretamente em nosso site: https://dotgroup.enlizt.me/vagas/desenvolvedor-a-_front_end_-_produto-290121 
Nesse primeiro momento iremos pedir suas informações pessoais (você pode importá-las diretamente do LinkedIn) e em seguida enviaremos as próximas etapas do processo que consistem em mapeamento cultural, teste técnico e entrevista. 

Ou envie um e-mail para gabriela.souza@dotgroup.com.br com seu CV anexado - Enviar no assunto: Vaga FRONT - DOT

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 4 dias após cada etapa do processo.

## Labels

- CLT
- PJ
- Pleno
- Vue 
- Javascript 

- Remoto
<!--- Informar abaixo o nome do estado por extenso.
- Brasil 
- Santa Catarina

**Comment by 2lembre** [comment]
# Spoiler 

Empresa ignora teste enviado e envia um feedback genérico sem nenhum embasamento técnico.
Esperando que você venha a desenvolver outro teste futuramente...

Feedback recebido:

***Optamos por avaliar sua prova técnica devido a sua apresentação no currículo, porém ela apresentou uma qualidade abaixo do que buscamos para as demandas que possuímos no momento.  De toda forma, ambos são pontos que você pode desenvolver e tentar uma nova inscrição dentro de alguns meses.***

- Quais pontos foi informado para se desenvolver? Nada informado.
- O que no projeto condiz a inferior ou baixa qualidade? Nada informado.

Aconselho tomarem cuidado para não perderem tempo de desenvolvimento enviando código sobe demanda.

Dois projetos solicitados para serem desenvolvidos
Primeiro projeto com **React.js**, **Styled components**, lib de component e testes unitários
Segundo projeto Vanilla com **Webpack**, **Pug.js**, **Stylus.js**, **PostCSS**, **Eslint** e **Babel.js**
***
Notas auditoria Google projeto React.js
![Audit React](https://i.imgur.com/BPsKmR6.png)
***
Notas auditoria Google projeto Vanilla
![Audit Vanilla](https://i.imgur.com/ECJdyYg.png)
***
Nota auditoria GTMetrix projeto React.js
![Audit React](https://i.imgur.com/TnMDjQl.png)
***
Nota auditoria GTMetrix projeto Vanilla
![Audit Vanilla](https://i.imgur.com/Bv3iAyo.png)
***
Analisem o [Glassdoor](https://www.glassdoor.com.br/Entrevista/DOT-digital-group-Perguntas-entrevista-E1092381.htm) e veja os feedback sobre a mesma antes de dedicar seu tempo acreditando em um feedback sincero, evitando frustação e decepção.

Ignoraram todo desenvolvimento Open-Source, essa é minha conta secundária apenas para informa sem me expor.
Se quiserem comprovar mais informações sobre o teste desenvolvido entre em contato nesse email: **2lembre@gmail.com**

**Comment by gabriela-dot** [comment]
@2lembre
Tudo certo? 
 
Dialoguei contigo por e-mail explicando alguns pontos sobre a prova assim como também expliquei que você realizou o mapeamento cultural da empresa e não foi aprovado. Assim como informado, fornecemos um feedback mais extenso aos candidatos que chegam na etapa de entrevista (algo que você informou no glassdoor que realizou porém não chegasse a essa etapa). 

Sinto que sua experiência não tenha sido a melhor conosco e de toda forma, agradeço por seu feedback e sugestões para melhorias.
Todo o comentário é válido para que possamos repensar em nosso processo seletivo!

**Comment by 2lembre** [comment]
> @2lembre
> Tudo certo?
> 
> Dialoguei contigo por e-mail explicando alguns pontos sobre a prova assim como também expliquei que você realizou o mapeamento cultural da empresa e não foi aprovado. Assim como informado, fornecemos um feedback mais extenso aos candidatos que chegam na etapa de entrevista (algo que você informou no Glassdoor que realizou porém não chegasse a essa etapa).
> 
> Sinto que sua experiência não tenha sido a melhor conosco e de toda forma, agradeço por seu feedback e sugestões para melhorias.
> Todo o comentário é válido para que possamos repensar em nosso processo seletivo!

## Avaliação
Respondi a prova de questões que me enviaram
Recebi um e-mail seu solicitando desenvolver o teste e escrever duas aplicação, um em React.js e outra com Javascript Vanilla.

Se vocês discriminam a avaliação do teste técnico com o possível desmatch com o candidato, por que mesmo assim solicitam o teste para ser desenvolvido fazendo a pessoa gasta tempo e esforços em algo que vocês iram discriminar e não dar retorno nenhum sobre o produto desenvolvido?

Só recebi retorno mesmo do processo pois liguei para outro setor e entraram em contato, até os e-mails foram ignorados por um período extenso algo que ultrapassa semanas. Assim como no [Glassdoor](https://www.glassdoor.com.br/Entrevista/DOT-digital-group-Perguntas-entrevista-E1092381.htm) tem outros feedback sobre a falta de retorno, respeito e discriminação na avaliação de testes.

## Tecnologia e mão de obra
Nosso desenvolvimento e mão de obra na tecnologia são os códigos que escrevemos, e se vocês fazem pessoas gastar tempo de vida, mão de obra ao desenvolver algo com toda excelência possível, o mais humano no mínimo seria dar um retorno com embasamento técnico assim como foi solicitado.

As pessoas dedicam a mão de obra e tempo sem ao menos saber que não iria ter retorno sincero sobre tudo que foi desenvolvido.

Em nenhum momento você informa aos candidatos que terá discriminação e possível falta de feedback com embasamento técnico Já que é uma prova técnica? contraditório.

## Feedback
Será mesmo que vocês querem tratar o candidato com respeito?
Ou apenas receber testes sobe demanda de um produto e discriminar o candidato
Ignoram até o desenvolvimento open-source que venho mantendo e ajudando muitas pessoas.

Mesmo após todo esse tratamento, tive a cordialidade de enviar em resposta alguns pontos para se melhorar no próprio produto de vocês e me ignoraram.
Pois estava avaliando vocês tecnicamente assim como deveriam ter feito com o teste que solicitaram.

## Direitos humanos
Talvez meu teste não foi avaliado pois coloquei textos sobre os direitos humanos
***Devemos agir uns aos outros com espírito de fraternidade.***
***Ninguém será submetido à tortura, nem a tratamento ou castigo cruel, desumano ou degradante.***

## Apenas um alerta
Como outros profissionais que estudam, desenvolve e cada vez mais quer colaborar com o desenvolvimento humano, apenas compartilhei minha opinião para alerta outros profissionais para não sofrerem a mesma descriminação e desvalorização profissional.
Antes de dedicar seu tempo acreditando que ira ter algum retorno sincero com embasamento técnico sobre o que foi entregue.

E sendo sincero, seria tão simples se realmente tivesse sido avaliado com carinho e humanidade.
Como você mesmo afirma e se contradiz em sua resposta não teve avaliação nenhuma e foi descriminado.

Pode me descriminar e censurar, mas eu acho isso um ato sódico e criminoso solicitar testes e mão de obra e nem avaliar com embasamento técnico ou humano sobre o que foi enviado.

Repito novamente o que falei por e-mail de forma publica para outros profissionais analisar o contexto.

> "Analisem o desenvolvimento open-source evita muito solicitar teste que não vai ser avaliado com sinceridade.  
> Sejam mais humanos, se foi solicitado um teste prático, avaliem, se não tem tempo para avaliar os testes não solicite.
> Fica parecendo que vocês querem o código e o produto produzido antes de contratar as pessoas e qualificá-las após."
> ``28 de jan. de 2021``

Enfim, este último e-mail que ainda não tiveram coragem de responder e acredito que nunca será respondido
Isso aconteceu comigo que desenvolvi buscando as melhores praticas das bibliotecas e seguindo os padrões [W3C](https://www.w3.org/).

**Comment by Gabriel-Tomaz** [comment]
Olá boa noite, gostaria de esclarecer algumas dúvidas que não estão listadas no desafio técnico. 
A primeira é sobre o prazo para a entrega do desafio e a segunda é sobre as "Duas Versões" é obrigatória a entrega das duas formas (com e sem Framework) ou posso selecionar umas das duas ?

**Comment by gabriela-dot** [comment]
Oi @Gabriel-Tomaz! Bom dia 

Você pode realizar conforme o seu tempo, sugiro para realizar com calma e atenção :) 

Verifiquei as instruções e faltou a orientação para a entrega com framework, ela pode ser realizada tanto em Vue como em React. Utilizamos ambas as tecnologias aqui, então utilize aquela que se sentir mais confortável. 

É necessário realizar as duas entregas, uma com framework e a outra sem. 

Qualquer outra dúvida, sigo á disposição!

**Comment by paulo70** [comment]
@gabriela-dot 
Vocês entraram em contato comigo e até hoje não retornaram. Enviam um teste rídiculo de perguntas e nada mais, somos desenvolvedores e não estamos fazendo testes piscólogicos.
O colega acima tem razão sobre os comentários. Acho que legal vocês serem mais éticos e transparentes no processo. Aqui é um lugar aonde se concentra muitos desenvolvedores e com isso vocês(empresa) podem não ter ficarem com uma imagem legal.
Dicas: não vi o teste técnico de vocês, mas desnecessário fazer dois testes um com algum framework outro não. Façam um teste inteligente capitando o conhecimento necessário.

**Comment by gabriela-dot** [comment]
@paulo70 Verificando a plataforma vi que enviamos um retorno pra ti, mas o e-mail consta como não aberto, pode ter caído no SPAM ou algo assim. 
De toda forma, assim como citado ao colega anterior, sinto que sua experiência não tenha sido a melhor e fico feliz com os comentários que vocês trazem. Acredito que o ouvir os candidatos e ter abertura ao diálogo é a melhor forma de aprimorar o processo seletivo. 
Com certeza irei levar essas considerações ao nosso time técnico para que possamos pensar em avaliações técnicas que façam sentido para vocês. 
Um abraço e estou sempre à disposição! :)

**Comment by paulo70** [comment]
@gabriela-dot , Obrigado pelo feedback.
