### ISSUE TITLE
[Remoto/Lisboa] Digital Analytics Specialist na Integer Consulting

### ISSUE THREAD

**Issue by raquelinteger** [frontendbr/vagas#4216]
# Integer Consulting

INTEGER, a technology consulting company with more than a decade of presence in the Portuguese market, is looking for a Digital Analytics Specialist, with strong communication skills, a sense of responsibility and teamwork.

This can be the perfect challenge for you if you have:

-3+ years of experience analyzing, interpreting, and visualizing data into clean, clear, and digestible dashboards and reports
-Experience with Web Analytics (Google Analytics); experience with BI tools (PowerBI), JavaScript and databases (Snowflake) is a plus
-Experience with SEM & SEO
-Fluency in English

If you have the desired amazINg talent and want to be part of the INTEGER team, respond to this announcement with your updated CV to raquel.almeida@integer.pt.

Participating in this project means integrating into a solid growing company and a young and dynamic team. #jumpIN

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
