### ISSUE TITLE
[Remoto/Lisboa] Identify Speacilist na Integer Consulting

### ISSUE THREAD

**Issue by raquelinteger** [frontendbr/vagas#4217]
INTEGER, a technology consulting company with more than a decade of presence in the Portuguese market, is looking for a Identify Specialist, with strong communication skills, a sense of responsibility and teamwork.

This can be the perfect challenge for you if you have:

-Knowledge in Active Directory and/or Azure AD
-Knowledge in Google OpenID
-Experience integrating SaaS applications using:
-SAML
-SCIM
-OAuth
-Experience implementing RBAC/ABAC approaches in multiple identity providers environments

If you have the desired amazINg talent and want to be part of the INTEGER team, respond to this announcement with your updated CV to raquel.almeida@integer.pt.

Participating in this project means integrating into a solid growing company and a young and dynamic team. #jumpIN

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
