### ISSUE TITLE
[REMOTO] UX/UI Designer | Product Designer na A2Tech

### ISSUE THREAD

**Issue by a2techsolutions** [frontendbr/vagas#4218]
## Descrição da vaga

Atuação 100% remota, com Horário flexível: Apenas 1 Standup diário para follow up.

Estamos buscando uma pessoa curiosa e estudiosa, que tenha experiência junior-plena em design de produtos e soluções digitais, e que goste de trabalhar em ambientes jovens, dinâmicos e colaborativos. Esperamos que você tenha experiência com as metodologias, frameworks e entregáveis de UX design, e ferramentas de prototipagem (figma, XD, etc), e consiga construir wireframes, wireflows e protótipos funcionais (navegáveis e interativos) de alta fidelidade, com foco na melhor usabilidade e experiência possível. 

## Local

Remoto

## Requisitos

Experiência sólida na execução das responsabilidades da vaga.
Familiaridade com HTML e CSS.
Experiência com definição e implantação de Design System.

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para recrutamento@a2tech.co com seu CV anexado - enviar no assunto: Vaga Designer

## Labels

- PJ
- Pleno
- Remoto
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
