### ISSUE TITLE
CALIFORNIA COMPANY HIRING TALENTED UI/UX DESIGNERS - REMOTE POSITION

### ISSUE THREAD

**Issue by cyzainc** [frontendbr/vagas#422]
We are a startup based in Newport Beach, California, developing an incredible and innovative online marketplace platform (web and mobile based). 

We are interested in hiring talented and creative designers. Knowledge of using Sketch app is preferred and Photoshop is a must. 

This is a remote position and requires a longer-term commitment of at least part-time. Basic conversational English is enough to work with our team and you do not need to be fluent. Good and reliable internet connection is a must. 

We look forward to your reviewing your resume; please briefly discuss your availability and your experience level (from scale of 1 to 10) with Sketch app and Photoshop. Our email: jobs@cyza.com

**Comment by LFeh** [comment]
Just Front-End ;)
