### ISSUE TITLE
[Remoto/ São Paulo ou Rio de Janeiro] Front & Back-End Developer no Instituto Moreira Salles

### ISSUE THREAD

**Issue by lauraklemz** [frontendbr/vagas#4220]
## Nossa empresa

O Instituto Moreira Salles (IMS) é uma das mais importantes e ativas instituições de memória da América Latina. O IMS está presente nas cidades de São Paulo, Rio de Janeiro e Poços de Caldas e possui acervo nas áreas de Fotografia, Música, Literatura e Iconografia. E gosta de Cinema.

O objetivo fundamental da instituição é difundir seus acervos da maneira mais ampla através de exposições, de publicações e do atendimento a pesquisadores e outros consulentes. O IMS também tem aperfeiçoado e renovado seu endereço na internet para propagar de forma ágil e gratuita seus acervos e sua programação.

Além do site institucional, o IMS abriga também mais de uma dezena de endereços virtuais, como a Rádio Batuta, com programas especiais e streaming 24h, sites dedicados a artistas como Pixinguinha, Clarice Lispector e Ernesto Nazareth, sites das revistas ZUM e serrote e mais.

Mais informações: http://ims.com.br

## Descrição da vaga

O(a) programador(a) front e back-end irá trabalhar em atividades relacionadas aos sites do ecossistema digital do Instituto Moreira Salles, como parte da Coordenação de Internet. Procuramos um(a) profissional experiente para atuar em ambiente altamente dinâmico e desafiador.

• Desenvolver código e soluções para sites WordPress com foco em eficiência, escalabilidade e estabilidade
• Participar do processo de desenvolvimento de arquitetura front-end, usabilidade, performance, testabilidade e acessibilidade
• Auxiliar na manutenção dos sites do ecossistema do IMS (WordPress e frameworks personalizados)

## Local

Remoto, a partir de São Paulo ou do Rio de Janeiro

## Requisitos

**Obrigatórios:**
• JavaScript, HTML, CSS e PHP
• Banco de dados (mySQL)
• GitLab (gitflow) para versionamento de sites
• Frameworks atuais (VUE, Angular, React etc)
• Domínio escrito e oral da língua portuguesa
• Inglês intermediário
• É preciso ser organizado(a), ter boa comunicação interpessoal e estar disposto(a) a trabalhar em parceria com equipe multidisciplinar.

**Desejáveis:**
• Docker e Amazon AWS
• Cultura DevOps
• Banco de dados (Dynamo DB e Redis)
• Desenvolvimento de jogos (Unity, C#)
• Page Builder SiteOrigin
• Sistemas de gerenciamento de projeto

**Diferenciais:**
• Acessibilidade
• SEO
• Interesse na área cultural

## Benefícios
• Contrato de Teletrabalho
• Salário R$ 7.000,00
• Vale Refeição e Alimentação (valor total: R$ 1.500,00)
• Plano de saúde Sulamérica Especial
• Plano odontológico Sulamérica Básico
• Auxílio educação após 6 meses de admissão
• Seguro de vida em grupo
• Auxílio com plano de dados de Internet
• Equipamentos e acessórios de microinformática fornecidos pelo IMS

## Contratação

CLT, contrato de teletrabalho

## Como se candidatar

O processo seletivo será feito totalmente online.
Preenchimento e envio de formulário online até 19 de fevereiro de 2021, às 10h (horário de Brasília).
https://trabalhe.ims.com.br

## Tempo médio de feedbacks

As pessoas escolhidas a partir das informações enviadas pelo formulário serão convidadas por e-mail, até 5 de março de 2021, para uma entrevista.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
