### ISSUE TITLE
[São Paulo] Front-end Developer na Skymail LTDA

### ISSUE THREAD

**Issue by lucasmarin** [frontendbr/vagas#4228]
> Vaga Remota durante a pandemia

## Nossa empresa

A Skymail é uma empresa de cloud computing com 8 anos de mercado. Possui um corpo diretivo jovem e aberto a ideias, foi fundada por gente interessada em fazer diferente e o melhor. Trabalhamos principalmente com soluções opensource em cloud computing e e-mail corporativo. Possuímos hoje uma solução robusta de e-mail corporativo com colaboração (skybox, editor de arquivos office online, compartilhamento de calendários e desenvolvendo uma ferramenta de chat/conferência) utilizada por mais de 500 mil usuários pelo Brasil, nossa ferramenta de virtualização de máquinas virtuais que é integrada ao mesmo painel de controle (projeto que inicialmente a pessoa contratada irá atuar) que gerencia os e-mails corporativos, soluções de Disparo de E-mail em massa e Backup inteligente de servidores.

Nossas soluções estão em constante evolução e o ambiente é desafiador todo dia, estamos sempre focados em trazer a melhor solução para os nossos clientes e também o melhor atendimento, esses são um dos nossos grandes diferenciais.

Trabalhamos na modalidade de cliente direto e revendedores, onde nosso painel de controle tem total domínio do ambiente destes tipos de clientes. 

Estamos em franca expansão, com crescimento sólido e constante desde a fundação e com um crescimento de 40% no ano de 2020.

## Descrição da vaga

A pessoa contratada inicialmente será responsável pelo desenvolvimento do frontend de uma área dentro do painel de controle da Skymail relacionada à nossa solução de Cloud Computing. Esta área faz comunicação direta com nossa API e executará funções diretamente nos itens do usuário e produzirá relatórios gerenciais a respeito do consumo e utilização do ambiente do usuário. 

- Desenvolver novas features e interfaces
- Integrar a aplicação front-end com o back-end
- Validar a performance da aplicação
- Ser responsável pela qualidade do código do front-end

### Requisitos

- Experiência em Vue.js, React ou Angular.
- Noções avançadas de HTML5, CSS3 e JS, com capacidade para desenvolver projetos de forma responsiva.
- Foco na otimização e performance da solução desenvolvida: minificação/code splitting.
- Ser criterioso, detalhista e atento com o layout a ser implementado, respeitando dimensões, posicionamento, cores e demais
- Comportamentos — foco na qualidade
- Familiaridade com integração de APIs diversas
- Conhecimento em gerenciamento do estado da aplicação. (state management: redux, vuex ou NgRx)
- Conhecimento em componentização do frontend

### Habilidades Obrigatórias

- JavaScript
- Vue.js, React ou Angular

### Habilidades Desejáveis

- UX (User Experience)
- UI (User Interface)
- Git
- PHP básico
- Flutter

## Local

Escritório (remoto 100% durante a pandemia, estamos avaliando remoto parcial de 3 à 4x por semana) , [SP], [São Paulo], [Pinheiros]

## Benefícios

- 1 mês de folga remunerada

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para lucas.marin@skymail.com.br com seu CV anexado com sua pretensão salarial - enviar no assunto: Vaga Frontend

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Remoto parcial

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
