### ISSUE TITLE
[São Paulo] Front-End Developer na VAGAS.com

### ISSUE THREAD

**Issue by danielGalvao** [frontendbr/vagas#423]
## Descrição da vaga

Responsabilidades:
• Desenvolvimento de interfaces que se adaptam a diversos dispositivos e tamanhos de tela;
• Em parceria com Designers e UXs, entregar valor para o usuário, garantindo melhor usabilidade e fidelidade do layout.;
• Trabalhar com requisições HTTP utilizando API Rest;
• Participar de equipes multifuncionais interagindo com os profissionais de todas as áreas de conhecimento;
• Participar de todo o ciclo de desenvolvimento de produto, passando pelas fases de concepção e análise de mercado, por exemplo, não apenas produção;
• Gestão compartilhada de sua equipe e negócio.

## Local

Escritório - Brooklin Novo (Zona Sul - São Paulo/SP).

## Benefícios

• Auxílio desenvolvimento p/ cursos;
• Auxílio creche (crianças até 5 anos);
• Convênio médico - Porto Seguro;
• Convênio odontológico - MetLife;
• VT, fretado ou auxílio estacionamento;
• VR de R$28,00/dia;
• Cesta de natal;
• Seguro de vida.

**Diferenciais:**

• Great Place To Work - TI (2014,2015,2016);
• Ambiente informal;
• Horário flexível;
• Possibilidade de fazer home-office alguns dias;
• Café da manhã e da tarde + fruta;
• Ginástica laboral, quick massage e assessoria esportiva;
• Parceria com a Gympass;
• Videogame, revistas & jornais;
• Parabéns com coxinha e bolo todo mês;
• Festas e eventos ao longo do ano;
• Parcerias com universidades e escolas de idiomas;
• Fácil acesso de carro, trem ou fretado.

## Requisitos

• Reproduzir layouts com fidelidade;
• Ser proativo;
• Vivência com:
- HTML, CSS, bibliotecas Javascript (heavy user);
- Frameworks Javascript MV*;
- Design responsivo;
- Frameworks de CSS;
- Algum CMS;
- Softwares de criação e edição de layouts;
- SEO, cross-browser e acessibilidade;
- Chamadas API Rest;
- Sistemas de versionamento de código.

**Desejáveis:**

• Ter trabalhado com metodologias ágeis;
• Experiência com desenvolvimento orientado por testes (TDD).

## Contratação

CLT

## Nossa empresa

Há 17 anos buscamos contribuir para que pessoas escolham melhor as empresas e empresas escolham melhor as pessoas, impactando positivamente no objetivo de cada um. Como? Através da tecnologia!

Como resultado, temos um sistema de currículos com aproximadamente 13 milhões de currículos, 74 das 100 maiores empresas do país contratando através das nossas soluções tecnológicas, além de inovações que auxiliam os candidatos ao longo de sua trajetória profissional, como o Mapa VAGAS de Carreiras, e um banco de dados do tamanho de 5 teras. Toda a conquista é feita através da vivência do modelo de gestão horizontal, que possibilita a liberdade, autonomia e responsabilidade no negócio, mas todos têm tudo a ver com isso.

## Como se candidatar

Por favor acesse [aqui](http://www.vagas.com.br/vagas/v1487336/desenvolvedor-front-end-pleno-senior.html) ou envie um email para selecao@vagas.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Developer

**Comment by danielGalvao** [comment]
Tags: Alocado | CLT | Pleno | Sênior

**Comment by igor9silva** [comment]
Porque não posta no vagas.com?

**Comment by danielGalvao** [comment]
@igor9silva a vaga está lá, inclusive a candidatura pode ser feita por lá também. Na descrição da vaga tem o link exatamente na parte de "Como se candidatar"... Mas caso não tenha visto segue: http://www.vagas.com.br/vagas/v1487336/desenvolvedor-front-end-pleno-senior.html 
Abraços!

**Comment by igor9silva** [comment]
Eu vi @danielGalvao, só estava brincando. Achei engraçado 😄

**Comment by jadir-junior** [comment]
quais libraries e frameworks vocês utilizam?

**Comment by danielGalvao** [comment]
@jadir-junior React e Vue, somos abertos e tranquilos para utilizarmos o que for melhor para o projeto. Temos alguns legados em Jquery mas que são bem atendidos por ele...

**Comment by danielGalvao** [comment]
Closed
