### ISSUE TITLE
[REMOTO] Front-end Developer na The Brooklyn Brothers

### ISSUE THREAD

**Issue by thebrooklybrothers** [frontendbr/vagas#4231]
1) Quem somos 

Somos parte do grupo Interpublic, um dos maiores grupos de agências de publicidade do mundo. Somos criativos e inquietos. Trabalhamos com muita paixão e espírito empreendedor todos os dias. Temos mais de 130 colaboradores ao redor do mundo, com escritórios em Florianópolis, Nova York e Londres.

Em Florianópolis, nosso time é focado em gerenciamento de conteúdo e desenvolvimento de plataformas digitais. Criamos ideias e soluções para atingir uma audiência cada vez mais exigente, conectada e multi-cultural. 

Quer fazer parte do nosso time? 

 

2) Quais serão suas atividades e desafios aqui? 

- Desenvolver websites e aplicações; 

- Investigar e corrigir problemas em sites e sistemas de terceiros; 

- Quando necessário, interagir com o cliente em questões técnicas (dúvidas ou definições); 

- Compartilhar conhecimento com os demais integrantes da equipe. 

3) Para ocupar este cargo, você precisa ter:

- Inglês fluente;

- Proatividade;

- Organização e atenção à detalhes;

- Bom relacionamento interpessoal;

- Foco em resultado;

- Formação: Análise de Sistemas, Sistemas de Informação, Ciências da Computação ou áreas correlatas;

- Ao menos 5 anos de experiência comprovada;

Profundo conhecimento em Javascript, HTML/CSS e Git são requisitos básicos e essenciais, além de sólido conhecimento e experiência comprovada em alguma das seguintes tecnologias:

React.js, Typescript, Gatsby.js, Node.js, JAMStack

Conhecimento em Netlify e/ou Sanity.io são diferenciais.

4) Oferecemos:

 

- Vaga CLT: 40 horas

- Remuneração: Entre R$ 5.000,00 - R$ 6.500,00

- Vale alimentação/refeição (sem desconto em folha);

- Vale transporte ou combustível (sem desconto em folha);

- Plano de saúde (sem carência e sem custo para você);

- Plano odontológico (sem desconto em folha);

- Acesso ilimitado a plataforma de cursos;

- Cultura que valoriza feedback, diversidade, inclusão, causas sociais e valores humanos;

- Café da manhã semanal;

- Day-off no mês do aniversário;

- No dress code;

Interessou? Acesse o formulário a seguir para que possamos conhecer você melhor e aguarde o nosso contato.
https://forms.office.com/Pages/ResponsePage.aspx?id=weQm0JJYekm52u5JPJ8DZL_DalNJmT5KvGb6GKvNiZlUMExBUkhBTE02N0dZS1YwWjNWVUxCQkJPMC4u

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
