### ISSUE TITLE
[Remoto] Full-stack JS developer na Outbound

### ISSUE THREAD

**Issue by vtrpldn** [frontendbr/vagas#4232]
## Nossa empresa

We are a small venture studio that builds software products for the experience economy.

Our main product is Outbound, the all-in-one business platform for travel agencies:

- Our [business dashboard](https://drive.google.com/file/d/11a3ipOZabZTylhrX7Lz67qp0r2CblSGh/) (React) brings bookings, CRM, and customer communication together in one place to make admin, sales, and customer service easier.
- Our [mobile travel app](https://outboundhq.com) (React Native) gives the traveller a single point of access to trip information and destination content, curated by the travel agency.

We're based in Copenhagen, Denmark, but half of our team works remotely from places like Rio de Janeiro and Budapest 🇩🇰🇧🇷🇭🇺

## Descrição da vaga

Outbound is seeking a full-stack JS developer with at least 3 years of experience with React.

The position is full-time (160 hours/month) with a salary of around 3000-3500 Euro/month.

You'll be able to work from home.

## Local

Remoto

## Requisitos

- 3+ years of React experience 
- 5+ years of HTML/JS experience
- English fluency 
- Deep understanding of technology 
- Ability to balance speed and quality, with a focus on tangible results 
- Attention to detail - we obsess over user experience and design 
- Proven record of shipping features on time 
- Flexible and focused on solutions 
- Organized and self-motivated 

## Como se candidatar

Does this role sound like a good fit? Email Stefan Bech (CEO) at [stefan@outboundhq.com](mailto:stefan@outboundhq.com).

- Include the role's title in your subject line
- Include your LinkedIn and GitHub profiles
- Send along links that best showcase the relevant things you've built and done
- We especially want to see what you've built with React
- Let us know if you have experience with any other technologies in our stack, besides React
- You're full-stack, but do you skew more towards frontend or backend?
- What is your salary expectation for 160 hours/month?
- When would you be able to start?

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
