### ISSUE TITLE
[Remoto / Viçosa MG] Front-end Developer na Cientec Aceleradora

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#4236]
## Descrição da vaga: 
 <p>O GESUAS é uma empresa do grupo Cientec Aceleradora! <a href="http://www.gesuas.com.br" target="_blank">www.gesuas.com.br</a>&nbsp;</p>
<p>Somos um software referência nacional para gestão da política de assistência social para prefeitura, e estamos presente em todas as regiões do Brasil. Estamos crescendo e precisamos completar o nosso time!</p>
<p>Nosso propósito é levar excelência na gestão do SUAS aos municípios de todo o país, ofertando soluções que auxiliem a superação de situações de vulnerabilidade ou risco social.</p>
<p><strong>O que você vai fazer:</strong></p>
<p>Procuramos um DESENVOLVEDOR WEB que irá trabalhar junto a nossa equipe de engenharia auxiliando na criação de soluções que irão impactar as secretarias de assistência social a atingirem a Excelência na Gestão do SUAS.</p>
<p></p>
<p><strong>O que esperamos de você:</strong></p>
<p>Aqui é pra quem ama de verdade tecnologia e sonha em trabalhar em um ambiente dinâmico, descontraído e de evolução constante. Sabe o que vai fazer você se encaixar direitinho com a gente? Ser uma pessoa com senso de organização, atenção a detalhes e foco.</p>

## Cientec Aceleradora: 
 <p>Somos um Grupo de empresas preocupadas em impactar os negócios deste Brasil afora (e porque não o mundo?) desenvolvendo soluções simples, eficazes, gerando valor no dia a dia dos nossos clientes. Além de buscarmos ser autoridade nas respectivas áreas de atuação. Nosso compromisso é sermos melhores naquilo que nos propusermos a fazer. Estamos imersos em um ambiente dinâmico, inovador e de constante busca pelo conhecimento (além de divertido). Nosso dia a dia é feito de interações, aprendizados, e muita, muitaaaa mão na massa. Tudo que a gente faz é para impactar a vida dos nossos clientes, e não abrimos mão de levar toda nossa bagagem e experiência por onde a gente passa. Afinal, já são 19 anos de experiência. Inovar é o nosso DNA, e aqui buscamos profissionais excepcionais que queiram crescer e realizar tanto quanto a gente</p>
</p>

 ## Habilidades: 
 - HTML 5 
- Javascript 
- JQuery 
- MySQL 
- PHP 
- Vue.js 
- GIT

## Local: 
 Viçosa MG

## Requisitos: 
 - Habituado com Git 
- Domínio em HTML 
- Conhecimentos em Javascript, jQuery e Vue.js (ou outro framework JS) 
- Domínio em PHP 
- Conhecimentos em MySQL 
- Sólidos conhecimentos em orientação a objetos e padrões de projeto 
- Experiência no desenvolvimento de aplicações WEB

## Benefícios: 
 - Plano de Saude 
- Seguro de vida 
- Vale transporte

## Como se candidatar:
Candidate-se em: [Front-end Developer na Cientec Aceleradora](https://coodesh.com/vagas/desenvolvedor-web-175737?origin=github&modal=open)

## Tempo médio de feedbacks:
 Costumamos enviar feedbacks em até 48 horas após cada etapa do processo. E-mail para contato em caso de não haver resposta: [juliana@cientec.net](mailto:juliana@cientec.net)

#### Alocação
Alocado

#### Regime
CLT

#### Nível
Pleno

**Comment by FilipeAugustoVO** [comment]
Boa noite, cavalheiros. Pergunta: A vaga é remota? No título parece ser,
mas o corpo do anúncio parece ser presencial.

**Comment by FrancieleGhizzoni** [comment]
Bom dia Filipe, tudo joia?

Já ajustei a vaga, a mesma é para atuação parcialmente remota.

Abraço


Franciele Ghizzoni - Tech Recruiter
2021, Coodesh
https://coodesh.com
f.ghizzoni@coodesh.com <http://coodesh.com/>


Em qui., 4 de fev. de 2021 às 20:23, FilipeAugustoVO <
notifications@github.com> escreveu:
