### ISSUE TITLE
[Remote] Front-end Developer na LAR.app

### ISSUE THREAD

**Issue by henrique-lar-app** [frontendbr/vagas#4238]
## LAR.APP

A LAR.app é um startup que nasceu em 2018 atuando com serviços de administração de condomínios. No final de 2020, pivotamos o modelo de negócios para oferecer nossa tecnologia proprietária para outras administradoras do mercado, como SaaS. Estamos em um momento de construção de muita coisa nova, ativando nossas primeiras administradoras clientes e incrementando nosso produto dia a dia.

## Descrição da vaga

Estamos procurando um desenvolvedor Front-end Sr. Nossa equipe está crescendo e em um momento bem legal, criando muita coisa nova. Nosso produto principal é construído com VueJS e nossa página + blog em VueJS+Gridsome. Ter grande conhecimento e experiência em VueJS é um plus, mas não 100% necessário. Já tivemos grandes casos de devs que vieram do React ou Angular e começaram a fazer boas entregas super rápido.
Grande chance para trabalhar direto com o produto, tento contato contínuo com o time de UI/UX e muita autonomia. 

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Muitos anos de experiência com grandes projetos em Front-end
- Boa comunicação e trabalho em equipe
- Muita vontade de aprender e contribuir na construção de um produto de diferenciado
- HTML5
- CSS3
- JavaScript (ECMA6+)
- GIT
- Frameworks SPA

**Desejáveis:**
- GraphQL
- Vue
- VueX
- Vue Router
- Gridsome
- Metodologias Ágeis
- Jira
- Experiência com Testes Unitários (Jest)
- Sass

**Diferenciais:**
- Experiência com Software as a Service(SaaS) e Startups
- MongoDB

## Benefícios

VR no cartão Flash (cartão de crédito pré-pago que você poderá usar como quiser);

Assistência Médica;

- Ambiente informal;
- Autonomia, home office e horários flexíveis;
- Day-off de aniversário;
- Expectativa de alta performance e desenvolvimento.

## Contratação

PJ

## Como se candidatar

Por favor envie um email para henrique@lar.app com seu CV anexado, linkedin, github, ou o que você achar interessante a gente receber - enviar no assunto: Vaga Front-end

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
