### ISSUE TITLE
[100% Remoto - US] Integrations Software Engineer na Dialpad

### ISSUE THREAD

**Issue by cassianodialpad** [frontendbr/vagas#4239]
Pessoal, eu trabalho na Dialpad há 2 anos como gerente de engenharia para o time de iOS. Em Outubro recebemos um funding de 100 milhões de dólares, e estamos dobrando o time de engenharia, com expansão forte no Brasil! Já contratamos 3 desenvolvedores iOS remotos do Brasil, e estamos abrindo vagas para todas as outras áreas da engenharia. Quem quiser mais informações fique à vontade pra me adicionar no meu [LinkedIn](https://www.linkedin.com/in/cassianomonteiro/) e bater um papo!

## Empresa
Dialpad é uma empresa que fornece soluções de *business communications* para outras empresas, incluindo ligações voip, mensageria, video conferência, call center, etc. O diferencial do produto é a plataforma de telefonia totalmente cloud, permitindo transferir ligações da rede comum de telefonia (operadoras de celular por exemplo) para ligações voip de maneira instantânea. Isso permite (por exemplo) atender uma ligação no meu celular e continuar no computador sem a outra pessoa perceber a transferência. Além disso, temos forte AI integrada à plataforma, o que permite *speech-to-text* em tempo real. O nosso foco é o mercado de pequenas e médias empresas, mas já temos grandes clientes como Uber, TED e Motorola.

## Com quem você vai trabalhar
Uma galera boa pra caramba, vários devs com 7+ anos de experiência!

## Como aplicar
Obviamente é necessário inglês nível profissional.
Link para aplicar: https://grnh.se/a69774bf2us

## Tipo de contratação
CLT

## Contato
Para mais informações, podem me mandar [email](mailto:cmonteiro@dialpad.com) ou através do meu [LinkedIn](https://www.linkedin.com/in/cassianomonteiro/). Mais detalhes da vaga em inglês abaixo.

## About the company

Dialpad is the most modern business communications company in the industry.  Our products range from conferencing calling, to phone systems to contact center solutions that are all built with the end-user in mind.  We allow workers to be productive from anywhere on any device and have moved all the power of an on-premise phone system or contact center to the cloud to be accessed and used by modern workers in today’s Work from Anywhere environment.

## Who We Are

At Dialpad, work isn’t a place you go, it's a thing you do. We not only build products to enable the everywhere worker, but we also are everywhere workers.  With offices in San Francisco, San Ramon, Austin, Raleigh, Vancouver, Waterloo, Tokyo, London and Bangalore, we truly believe in finding the best talent everywhere.  We also embrace the Work from Home movement and are just as happy hiring great talent from anywhere if they choose to work from home rather than in an office.

With over $220 million in funding from OMERS Growth Equity, ICONIQ Capital, GV, Andreessen Horowitz, Felicis Ventures, Work-Bench, Scale Ventures and other top VCs, Dialpad attracts top engineers from companies like Microsoft and Google, and every member of our team plays an essential role in creating dynamic products that enable workers to be productive from anywhere!

### About The Role

The integrations team is part of our Product Engineering team. This team builds intelligent workflow integrations of Dialpad with business applications like Salesforce, Slack, Servicenow, Okta etc. We are looking  to grow this team. As an engineer at Dialpad, you will work with a close-knit product engineering team and technical lead. Our teams are cross disciplinary, and include Product Managers, Designers, QA, and other Engineers (Data Engineering, Data Science, Telephony). 

You will participate in design meetings and ask clarifying questions to fully understand customer scenarios and requirements.  You will work with consumer/dependency owners for design review and sign-off, be a technical leader within your software feature, mentor and share knowledge with the rest of the engineering team.

### Responsibilities

- Work with Python on Google App Engine
- Cloud Datastore (NoSQL database)
- Memcache (distributed cache)
- Analysis with BigQuery
- Debug with StackDriver
- Interface with designers, product managers, and other engineers (our policy: with fewer organized meetings, engineers have more time to code)
- Launch new code weekly with our fast release cycles
- Owning the release of the server and client in a rotation as release engineer
- Improve performance to handle rapid increase in user base and use-cases
- Writing backend and frontend unit tests
- Monitoring and alerts in Datadog 
- Participating in Python and JavaScript code reviews

### Traits we’ll look for in you

We hire smart Engineers that are willing to learn new technologies and take ownership in the work they are assigned to. When it comes to your background, we are extremely flexible with industry experience and the technologies you  have worked with in the past.

If you like to tackle complex engineering problems, build scalable cloud-based features in a full-stack capacity and love taking features from design to production, then you are the engineer for us!

### Technology Stack

Python, Django, JavaScript, Vue.JS, NoSQL, Google Cloud and Google App Engine.

## About Us

Joining our team means collaborating with people that aren’t just passionate about their work but about Argentine tango, musicals, sushi burritos, comic books - you name it. Because if you’re going to redefine the status quo, you need a group of people hungry to do more, to see more, and be more than where they started.

There is no idea too crazy and no task too small — we work together to make things we’re proud of.

### Compensation & Equity

Teamwork makes the dream work. We recognize that our dedicated team members are what make us successful. That’s why we offer competitive salaries in addition to stock options.

### Healthcare

An apple a day keeps the doctor away - and it doesn’t hurt that we offer 100% paid medical, dental, and vision plans for all employees.

### Reimbursements

We offer a monthly stipend to help cover your cell phone, home internet, and even gym membership costs.

### Education

We believe in your future as much as you do! That's why we offer a yearly stipend for continued learning and education expenses.

*Dialpad is an equal opportunity employer; we believe in creating a community of inclusion and an environment free from discrimination or harassment.*

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by cassianodialpad** [comment]
@felipefialho A vaga já fechou, obrigado!
