### ISSUE TITLE
[Belo Horizonte/MG] Front-End Developer na conta.MOBI

### ISSUE THREAD

**Issue by rhcontamobi** [frontendbr/vagas#424]
## Descrição da vaga

•	Atuar no desenvolvimento dos produtos;
•	CSS, HTML5 e Javascript;
•	Bootstrap e soluções responsivas;
•	Análise de usabilidade (UI) e experiência do usuário (UX);
•	Gulp / Grunt / SASS / Compass;
•	Controle de versão GIT e desenvolvimento em ambiente Linux;
•	React Native ou Ionic (desejável);
•	Elaboração de layouts de aplicações web e mobile (desejável).
•	Formação na área de Tecnologia da Informação, preferencialmente em Desenvolvimento de Software.

## Local

CLT - Belo Horizonte/MG

## Benefícios

Vale Refeição ou Alimentação;
Vale Transporte;
Seguro de Vida.

## Requisitos

**Obrigatórios:**
• Formação na área de Tecnologia da Informação, preferencialmente em Desenvolvimento de Software;
• CSS, HTML5 e Javascript;
• Bootstrap e soluções responsivas;
• Análise de usabilidade (UI) e experiência do usuário (UX);
• Gulp / Grunt / SASS / Compass;
• Controle de versão GIT e desenvolvimento em ambiente Linux.

**Desejáveis:**
• React Native ou Ionic (desejável);
• Elaboração de layouts de aplicações web e mobile (desejável).

**Diferenciais:**

## Contratação

CLT

## Nossa empresa

A conta.MOBI é uma Startup do ramo financeiro que fornece uma Conta Digital, dentre outros serviços, para quem é Microempreendedor Individual (MEI).
www.conta.mobi

## Como se candidatar

Interessados enviar cv + portfólio para rh@conta.mobi com o assunto “DEV FRONT END”

**Comment by yanmagale** [comment]
Galera da conta.MOBI é show :smile:

**Comment by paulo-campos** [comment]
Pena não ser Remoto, gostei muito da vaga.

**Comment by NataliaAvila** [comment]
gostei da vaga!!

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
