### ISSUE TITLE
[Porto Alegre/RS] FullStack Developer na Deliver IT

### ISSUE THREAD

**Issue by SejaDeliver** [frontendbr/vagas#4240]
## Nossa empresa

A Deliver IT é uma consultoria de serviços de tecnologia da informação. Nossa missão é entregar valor aos nossos clientes, através de serviços de tecnologia de informação, dentro de uma relação de parceira.

Nascemos em 2014, a partir da união das atividades da Absoluta. Net com a experiência de mercado de dois profissionais sêniores, em áreas complementares! Acreditamos em equipes multidisciplinares, que possuem confiança em suas relações e sobretudo transparência. Nosso time se caracteriza pelo engajamento, comprometimento e foco na qualidade das entregas.

Acreditamos que a qualidade dos nossos processos se deve a todas as pessoas que fazem parte da Deliver, e por isso prezamos por um ambiente de trabalho agradável, leve e muito amigável. Aqui os colaboradores têm espaço para o seu desenvolvimento profissional, oportunidade de trabalhar em projetos globais e para empresas de reconhecimento a nível nacional.

Nosso portfólio de serviço utiliza tecnologias vanguardistas dentre as seguintes linhas: Fábrica de Software, Business Intelligence, Mobile e Outsourcing.

Aqui na Deliver IT temos uma cultura leve, descontraída, colaborativa e diversa :-) Venha nos conhecer!

## Descrição da vaga

Estamos em busca de Desenvolvedor(a) FullStack, para atuar em projetos no segmento financeiro, no formato outsourcing, em um cliente referência no seu segmento :) A principal atribuição seria realizar análise de dados e desenvolvimento de APIS REST.

## Local

Zona Norte de Porto Alegre, Rio Grande do Sul

## Requisitos

**Obrigatórios:**

* NodeJs;
* Angular 2, React ou VueJs;
* API REST;
* MongoDB;
* Modelagem de dados no NoSQL

**Diferenciais:**

* Stack ELK (Elastic Search, Kibana, Logstash);
* Grafana;
* Familiaridade/interesse nas linguagens C/C++

## Benefícios

* VA e/ou VR
* VT
* Plano de Saúde
* Plano Odontológico
* Premiação por tempo de empresa
* Premiação por indicação.

**Diferenciais:**

* Ginástica Laboral
* Incentivo ao Inglês
* Horários Flexíveis
* Participação em Workshops técnicos

## Contratação

CLT

## Como se candidatar

Por favor envie um email para sejadeliver@deliverit.com.br com seu CV anexado - enviar no assunto: Vaga NodeJS

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 30 dias após cada processo.
E-mail para contato em caso de não haver resposta: sejadeliver@deliverit.com.br

#### Alocação

* Híbrido

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
