### ISSUE TITLE
[Remoto] Designer Front-End Sênior na Dotz

### ISSUE THREAD

**Issue by NicoliPioli** [frontendbr/vagas#4243]
Quer trabalhar em um time ágil? Temos vagas 100% remotas e uma delas pode ser sua!

Mais do que líder nacional no segmento de fidelidade por coalizão, somos um ecossistema digital. Nosso propósito é grande: aumentar o poder de compra da população brasileira.
Estamos vivendo um forte processo de expansão e transformação digital, e nossos times ágeis são fundamentais nessa missão!

Atividades a serem desempenhadas:​
- Codificar leiaute de sistemas de média/alta complexidade;
- Codificar testes;
- Documentar código fonte / sistemas;
- Planejar, organizar e reportar atividades (tarefas);
- Desenhar protótipos (storyboard).

Experiência Desejada:​
- Formação superior completa ou cursando na área de Tecnologia;
- Experiência de 4 anos com desenvolvimento Web;
- Experiência com HTML, CSS e JavaScript;
- Desejável conhecimento em Angular.

E, ah! É para trabalhar remotamente!

Venha transformar sua carreira em um ambiente ágil, dinâmico e de muito crescimento! Venha ser um Dotzeiro! 
Acesse: www.vagasdotz.com/vagas

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
