### ISSUE TITLE
[REMOTO] FULLSTACK NODE + ANGULAR | LYNCAS

### ISSUE THREAD

**Issue by karinpetermann** [frontendbr/vagas#4246]
Buscamos desenvolvedores que gostem de desafios e de evoluir. Queremos profissionais que tenham senso de dono, sejam críticos construtivos, que prezam pela qualidade do código e tenha sede de conhecimento. 🙌👊
⠀
⠀
Além disso:

Participar ativamente do planejamento das Sprints e definições das tarefas;
Realizar manutenção de funcionalidades do produto;
Desenvolver novas funcionalidades do produto;
Oferecer mentoria e tutoria para com membros do time;
Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas.
⠀
### OPORTUNIDADE 100% REMOTA
**VAGAS PARA NÍVEL PLENO e SÊNIOR**
⠀
**Desejável conhecimento:**

Arquitetura RESTful (Async e Sync)
Banco de Dados: NoSql e Relacional .
Frontend: HTML5, CSS3 (LESS/SASS), Javascript (AngularJS), jQuery, Bootstrap.
Microsserviços, Kubernetes, Docker, Graylog, Cote, Integrações complexas,
APIs e Webservices, Arquitetura RESTful, MVC, JWT.

**Diferenciais**

- TDD,
- Cubernates,
- API,
- CI (continuous Integration).

**### Para fazer parte do nosso time, cadastre-se: http://talentos.lyncas.net**

- Academia Lyncas
- Acolhimento psicológico
- Ambiente descontraído de trabalho
- No-dress code
- Bônus indicação
- Horário flexível

## Contratação

PJ ou CLT a combinar

## Como se candidatar

Cadastre-se no link: https://talentos.lyncas.net que nossa equipe entrará em contato com você.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias 

#### Nível

- Pleno
- Sênior

**Comment by karinpetermann** [comment]
Buscamos desenvolvedores que gostem de desafios e de evoluir. Queremos profissionais que tenham senso de dono, sejam críticos construtivos, que prezam pela qualidade do código e tenha sede de conhecimento. 🙌👊
⠀
⠀
Além disso:
- Participar ativamente do planejamento das Sprints e definições das tarefas;
- Realizar manutenção de funcionalidades do produto;
- Desenvolver novas funcionalidades do produto;
- Oferecer mentoria e tutoria para com membros do time;
- Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas.
⠀
**OPORTUNIDADE 100% REMOTA
VAGAS PARA NÍVEL PLENO e SÊNIOR**
⠀

**Desejável conhecimento:**

- Arquitetura RESTful (Async e Sync)
- Banco de Dados: NoSql e Relacional .
- Frontend: HTML5, CSS3 (LESS/SASS), Javascript (AngularJS), jQuery, Bootstrap.
- Microsserviços, Kubernetes, Docker, Graylog, Cote, Integrações complexas,
- APIs e Webservices, Arquitetura RESTful, MVC, JWT.

**Diferenciais**

- TDD, 
- Cubernates, 
- API, 
- CI (continuous Integration).


Para fazer parte do nosso time, cadastre-se: http://talentos.lyncas.net 


- Academia Lyncas
- Acolhimento psicológico
- Ambiente descontraído de trabalho
- No-dress code
- Bônus indicação
- Horário flexível

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
