### ISSUE TITLE
[São Paulo/SP] Front-end Developer na Suprevida

### ISSUE THREAD

**Issue by gabernardi** [frontendbr/vagas#4248]
## Nossa empresa

Somos a primeira plataforma B2B2C de produtos médicos do Brasil! 

Suprevida é uma Startup Healthtech instalada dentro do Hospital das Clínicas em São Paulo. 

Criamos conexão entre consumidores e fornecedores de produtos. 

## Descrição da vaga

Buscamos desenvolvedores(as) com experiência em desenvolvimento front-end para compor nosso squad interno.

## Local
Escritório, São Paulo, São Paulo, Pinheiros.

## Requisitos

Obrigatórios:

Experiência com desenvolvimento web
Ranking e posicionamento no google (SEO)
HTML e CSS
Ecossistema React (pré-processadores CSS, Material-UI, Redux, , Next.js)
Axios
TypeScript
Desejáveis:

React Native
AWS e/ou Azure
Metodologias ágeis de desenvolvimento (Scrum, Kanban)
Diferenciais:

Experiência com Back-end
Clean code
Teste unitário
Boas práticas em geral
Organização e trabalho em equipe

## Benefícios

- Plano de saúde
- VR de R$ 30/dia
- VT ou VC

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um e-mail para vagas@suprevida.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

## Tempo médio de feedbacks

Vaga para início imediato. Feedback não maior que 02 dias.

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by rafaelfgyn** [comment]
Alocado ou remoto?

**Comment by gabernardi** [comment]
Alocado, Rafael. CLT.

Abs,
[https://suprevidabucket1.s3-sa-east-1.amazonaws.com/Assinatura+de+E-mail/gif_assinatura-de-email_03.3.gif]     GABRIEL BERNARDI
CTO
E-mail:gabriel.bernardi@suprevida.com.br
Fone:(11) 98989-5910
www.suprevida.com.br
[https://suprevidabucket1.s3-sa-east-1.amazonaws.com/icon-facebook.png]<https://www.facebook.com/suprevida> [https://suprevidabucket1.s3-sa-east-1.amazonaws.com/icon-instagram.png] <https://www.instagram.com/suprevida/>  [https://suprevidabucket1.s3-sa-east-1.amazonaws.com/icon-linkedin.png] <https://www.linkedin.com/company/suprevida/?originalSubdomain=br>  [https://suprevidabucket1.s3-sa-east-1.amazonaws.com/Assinatura+de+E-mail/whats.png] <https://api.whatsapp.com/send?text=Sa%C3%BAde%20ao%20seu%20lado.%20Informa%C3%A7%C3%A3o%20%C3%BAtil%20e%20produtos%20m%C3%A9dicos%20acess%C3%ADveis%20em%20todos%20os%20momentos%20e%20lugares%20-conhecimento%20qualificado%20e%20oferta%20on-line.%20-%20https://www.suprevida.com.br>  [https://suprevidabucket1.s3-sa-east-1.amazonaws.com/icon-youtube.png] <https://www.youtube.com/channel/UCU8Y1600_BrMfTupu6Q9Z5Ar>
Conheça o Clube Suprevida<https://clube.suprevida.com.br/>

________________________________
De: Rafael Ferreira <notifications@github.com>
Enviado: segunda-feira, 8 de fevereiro de 2021 15:58
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: Gabriel Bernardi <gabriel.bernardi@suprevida.com.br>; Author <author@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [São Paulo/SP] Front-end Developer na Suprevida (#4248)


Alocado ou remoto?

**Comment by gabernardi** [comment]
@felipefialho poderia por gentileza, remover o label "remoto"? A vaga é presencial.
Obrigado.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
