### ISSUE TITLE
[Remoto] Front-end Developer na Croct

### ISSUE THREAD

**Issue by amorimjuliana** [frontendbr/vagas#4249]
> Vaga Remota durante a pandemia

## Nossa empresa

**Prazer, somos o Time de Tecnologia da [Croct](https://croct.com/) (:**

A Croct é uma plataforma SaaS de personalização que ajuda empresas a criarem jornadas online que são únicas para cada usuário. Nós entendemos o perfil do cliente e suas necessidades para oferecer uma experiência excepcional no mundo online. Tudo isso de forma simples, rápida e conectada.

Aqui na Croct, prezamos pela diversidade, liberdade e autonomia. Liberdade para escolher seus horários, suas stacks, a forma como você vai trabalhar e mais importante, liberdade de ser quem você é. Somos fascinados pela troca de conhecimento e acreditamos que sozinhos nunca chegaremos a lugar nenhum. 

Buscamos inteligência, energia e integridade. E em troca, oferecemos autonomia, liberdade e flexibilidade.

**Venha fazer parte do nosso time!**

## Descrição da vaga

Código excelente começa com pessoas incríveis. 🤓

Se você é da área de desenvolvimento, trabalha com React e é uma pessoa fora da curva buscando uma startup com potencial global para trabalhar remotamente, você vai gostar do que temos para você.
Como uma pessoa desenvolvedora front-end, você vai encontrar desafios relacionados ao desenvolvimento de um bom design e ao aprendizado da melhor forma de executar qualquer tarefa. Você vai ter contato direto com performance, otimização e escalabilidade de soluções, trabalhando diretamente com os fundadores da empresa. Se você busca liberdade para trabalhar e contribuir com projetos opensource, essa vaga é para você.

### Como será o seu dia a dia

- Garantir a entrega de projetos desafiadores de grande impacto no negócio, trabalhando lado a lado com founders da Croct
- Facilitar o planejamento de projetos para atender às necessidades de negócio atuais e futuros, antecipando e removendo barreiras
- Colaborar com demais área da empresa para entendimento dos problemas, análise de oportunidades e busca de soluções
- Desenvolver e implementar a área logada da plataforma, onde os clientes gerenciam suas experiências personalizadas
- Documentar e mapear os processos relacionados à área

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência em React, GraphQL, Javascript, Typescript, HTML5, CSS3 e LESS/SASS
- Conhecimento de bibliotecas/frameworks/ferramentas para frontend: Relay, Storybook, Jest, Cypress e Emotion
- Habilidade com testes unitários, integração e end-to-end sempre que aplicável no processo de desenvolvimento

**Desejáveis:**
- Embasamento teórico, habilidade e preocupação com excelência técnica e boas práticas de desenvolvimento (TDD, BDD, design de código, arquitetura, etc.)
- Experiência com ferramentas de versionamento (GitHub) e de linting (ESLint)
- Habilidade com gerenciador de pacotes como NPM
- Experiência com Continuous Integration e Continuous Delivery

**Diferenciais:**
- Experiência com Design System e projetos open source

## Benefícios

- Contratação: PJ
- Trabalho remoto
- Flexibilidade de horários
- Startup com potencial global e planos de internacionalização
- Flexibilidade para trabalhar com o stack que desejar
- Trabalho lado a lado dos founders e de um time com alta capacidade técnica
- Liberdade para trabalhar e contribuir com projetos opensource

## Contratação

PJ

## Como se candidatar

Por favor envie um email para jobs@croct.com com seu CV anexado (enviar no assunto: Vaga Front-End React).

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.
E-mail para contato em caso de não haver resposta: jobs@croct.com

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
