### ISSUE TITLE
[São Paulo] Front-end Developer na BEYOUNG

### ISSUE THREAD

**Issue by evelimassis** [frontendbr/vagas#4254]
> Vaga majoritariamente remota, eventualmente precisa ir ao escritório.

## Nossa empresa

A BEYOUNG é uma empresa que está revolucionando o mercado de cosméticos brasileiro, a partir de um novo conceito: SMART BEAUTY. Produtos multifuncionais e com alta tecnologia agregada que permitem simplicidade na relação do consumidor com a beleza. Sendo essencialmente digitais, buscamos o controle de toda a cadeia produtiva, desde a pesquisa por novas fórmulas até o desenvolvimento das nossas plataformas. O objetivo é garantir ao consumidor final uma experiência que permita grandes resultados com a simplicidade que a rotina do nosso tempo exige.

Somos a primeira DNVB (Digital Native Vertical Brand) no segmento de beleza no Brasil dominando o mercado online de cosméticos na categoria dos nossos produtos e expandindo rapidamente para o mercado offline, com mais de 3.000 pontos de revenda espalhados pelo país e mais de 60.000 clientes atendidos todos os meses. 

Por isso, buscamos novos talentos. Na Beyoung pulsamos inovação, design e tecnologia. Buscamos por pessoas questionadoras, proativas, colaborativas, criativas, inovadoras, e que curtem aprender. E acreditamos que todos devem crescer juntos. Bora?

Caso queira saber um pouco mais sobre os nossos produtos, entre no site: www.beyoung.com.br.

## Descrição da vaga

A Beyoung procura por desenvolvedores de software para integrar o time de desenvolvimento. Aqui você encontrará um ambiente bastante dinâmico e com muita chance de aprendizado e crescimento. Nosso time de tecnologia busca continuamente melhorar nossos processos e sistemas, resolver problemas complexos e propor soluções inovadoras para agregar valor para os clientes Beyoung. 

Nós trabalhamos com uma arquitetura baseada em serviços, 100% na nuvem. Como desenvolvedor front-end você irá participar de todo o desenvolvimento do e-commerce da Beyoung, incluindo novas páginas, componentes e features da plataforma de vendas, auxiliar no desenvolvimento do nosso APP e atuar na manutenção e melhoria contínua dos sistemas existentes.

Nossa atual stack: 

Os sistemas e sites são feitos em React no front-end, NodeJS e PHP no back-end. Nosso APP é desenvolvido em Flutter. Sistemas legados são full-stack em PHP com HTML, CSS e JavaScript. Usamos MySQL, Redis, Big Query e Firebase para armazenar dados.

## Local

Remoto | Escritório, [São Paulo], [São Paulo], [Alto de Pinheiros (ao lado do Parque Villa Lobos]

## Requisitos

**Obrigatórios:**
- Ter experiência com desenvolvimento front-end
- Inglês Técnico
- Javascript
- Git
- Conhecimento em algum Framework JS (Ex: React, Vue JS Angular, etc)
- Integração com API REST
- HTML/CSS
- Design Responsivo

**Desejáveis:**
- Conhecimento de design system
- Conhecimento em Flutter
- React 16 (Hooks)

**Diferenciais:**
- Conhecimento em gerenciamento de estado no React (contexto, local, etc...)
- Familiaridade com os softwares Figma, Photoshop, Adobe XD ou similares

## Benefícios

- Plano de saúde (sem coparticipação)
- Plano odontológico (sem coparticipação)
- Auxílio home office
- VR de R$ 30,00/dia
- Desconto nos produtos da empresa
- Bonificação anual
- Desconto no ZenKlub, em academias (smart fit e bio ritmo) e em lojas do varejo e escolas de idiomas

**Diferenciais:**
- Horário flexível
- Autonomia nos processos
- Cultura de startup

## Contratação

CLT ou PJ, a combinar

## Como se candidatar

Através do link: https://vagas.revelo.com.br/bbrands-beyoung/desenvolvedor-front-end-pleno-senior
Se preferir pode me enviar mensagem no linkedin: linkedin.com/in/evelimassis

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.

#### Regime
- CLT ou PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
