### ISSUE TITLE
[REMOTO] Full-Stack(React, Node) na Modus Create

### ISSUE THREAD

**Issue by pedrohyvo** [frontendbr/vagas#4256]
## Sobre a empresa

About Modus

Modus Create is a digital product agency that accelerates digital transformation. We use high performing small teams, emerging technology, and “new school” product development tools and methods to accelerate business outcomes. We support our clients across four core delivery areas: business and product strategy consulting, customer experience, cloud services, and Agile software delivery. 

Driven by a team of world-class talent, we have been recognized by the Inc. 5000 list of fastest growing private companies 5 years in a row, the Washington Business Journal list of Fastest Growing Companies in the Washington, DC area two years in a row, and a top company for remote work by FlexJobs. We’re also an official partner to Atlassian, AWS, Cloudflare, GitHub, InVision, Ionic Framework, and Vue.js!

Based on the model of an open source team, Modites work remotely, and are located across the globe. That’s allowed us to hire the best talent in the world, no matter where they live. Our highly collaborative, autonomous, and effective working environment is fueled by a team unified by a love of continuous learning. Our years of thought leadership including books, whitepapers, blog posts, conference and MeetUp talks, demonstrate our commitment to sharing what we’ve learned. 

We encourage every Modus employee to do the same. Our company is a platform for the growth of our employees. Through working with our distributed team of experts on challenging projects, every person that joins the Modus team can expect to continue growing and learning every day. This is your chance to be part of building something great. 

## Requisitos

Experience: Senior Level

Hello! Are you ready to Work from Home and transform your career?

We're looking for a Full Stack Engineer to join the engineering team at Modus. Want to help our client’s build awesome solutions to accomplish their goals and vision? Are you interested in working from home with some of the best talent on the planet? Then keep reading.

About You

You love building great software. Your work could be supporting new feature development, migrating existing features, or creating APIs. You'll have a primary focus on full stack development in React.js, Node.js. Our client’s tech stack is React, Node.js and AWS. 

You have strong development experience working with large and demonstrable projects and passionate about the latest industry trends, innovations occurring in web based and RESTful products. You have designed, developed, and tested software components using Node.js, React.js and have extensively worked in API Layer : AWS API Gateway & Lambda – Typescript with exposure to DynamoDB, Elasticsearch.

You relish creating high quality code from the comfort of your own home. Your engineering projects will focus on understanding customers' needs and translating those needs from product specifications into functional, production ready code. You'll have the opportunity to ship code daily that will be used by customers.

You love learning. Engineering is an ever-evolving world. You enjoy playing with new tech and exploring areas that you might not have experience with yet.  You are self-driven, self-learner willing to share knowledge and participate actively in your community.

Having overlap with your team is critical when working in a global remote team. Modus requires all team members to overlap with EST morning hours daily. In addition, reliable high speed internet is a must and having a machine to work in that meets the following criteria:  Mac running Mac OS or a Windows machine running Windows 10Pro.

Linux is required, one of the following: Ubuntu 14.04 LTS or higher, Red Hat Enterprise Linux / CentOS 6 or higher, Fedora 25 or higher, Debian 8.0 or higher.

Additionally, as part of this role you will be expected to adhere to our customers information security requirements. This includes but is not limited to installing BitDefender endpoint security, provided by Modus Create on the machine you will be connecting to the clients network and systems with. BitDefender provides the following features: AntiVirus/AntiMalware, Intrusion detection systems, Blocking of Phishing/compromised websites, Full Disk Encryption (using native tools to the operating system), Disables external storage, Automatic patch deployment and Windows risk management.

Things You Might Do

Modus is a fast-growing, and remote-first company, so you'll likely get experience on many different projects across the organization. That said, here are some things you'll probably do:

Give back to the community via open source and blog posts
Teach and be taught: Modus creates active teams that work in internal and external projects together, giving opportunities to stay relevant with the latest technologies and learning from experts worldwide
Interact directly with internal and external clients to represent Modus and its values

## Local

100% Remote

## Requisitos

- Your work could be supporting new feature development, migrating existing features, or creating APIs. 
- You'll have a primary focus on full stack development in React.js, Node.js. Our client’s tech stack is React, Node.js and AWS. 

- You have strong development experience working with large and demonstrable projects and passionate about the latest industry trends, innovations occurring in web based and RESTful products. 
- You have designed, developed, and tested software components using Node.js, React.js and have extensively worked in API Layer : AWS API Gateway & Lambda – Typescript with exposure to DynamoDB, Elasticsearch.

## Benefícios

Our Benefits may vary according to the Country you are located in, so please reach out to our recruiter in case you have any questions.

If you become a contractor we offer:

- Competitive compensation
- 100% Remote work (could vary according to the client's needs)
- Travel according to client's needs
- The chance to work side-by-side with thought leaders in emerging tech

## Contratação

PJ

## Candidata-se

Candidate-se por esse [link](https://grnh.se/1c44fda23us)

## Tempo médio de feedbacks

O processo leva em média de 2 a 3 semanas.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
