### ISSUE TITLE
[São Paulo] Front-end Developer na VIX

### ISSUE THREAD

**Issue by reisraff** [frontendbr/vagas#4258]
## Description

We are looking for FullStack developers focused in Front-end (Javascript) to join our Development team and participate in different projects made up of multicultural teams distributed throughout the world. We are looking for proactive people, team players passionate about programming and oriented to provide the best experience to the end user!
These developers will face numerous technical challenges, so they must use current technologies, get involved in the mobile world, web applications, devices, etc.

## Main Activities
- Developing interface applications using Vue.js, HTML5, React-Native and the surrounding ecosystem.
- Accurately translate user and business needs into functional frontend code.
- Developing, and testing UI for desktop, responsive websites and mobile devices.
- Implementing automated testing integrated into development and maintenance workflows.
- Build reusable code and libraries for future use.
- Staying up-to-date, as much as possible, with all recent developments in the techonologies used by us.
- Focus on security updates and issues.
- Doing upgrades and updates necessary for keeping up with modern security and development best practices.
- Contribute ideas and innovations, wherever you see opportunity for improvement.
- Work collaboratively with our multi-disciplinary teams.

## What are we looking for
- 3 to 5 years of experience.
- Strong skills with the JavaScript language, and frameworks (React, ReactNative, Vuejs, Vanilla JavaScript).
- Expert/Advanced experience in front-end technologies, security architectures and user experience.
- Experienced in service integrations (Web Services, CMS / Commerce systems, 3rd party APIs, etc).
- Experience with both consuming and designing RESTful APIs.
- Intermediate level English.

## Desirable requirements:
- A person who understand the need of good and clean code, with knowledge in SOLID, and Object Calisthenics
- Advanced in developing and testing web-based, mobile-web based, and fully responsive web applications using JavaScript - frameworks such as Jest, Mocha, Chai, Jasmine, etc.
- As a fullstack we expect a person who has bagage with the backend side, desired knowledge in PHP, Python, and NodeJS
- Spanish

## VIX is Offering:
- 100% remote work (until pandemic is not over) and flexible schedule.
- Excellent compensation — well above the market average.
- Extensive opportunities for growth and professional development thanks to our mentoring system.

# We have opportunities for:
- Pleno -  Salário R$ 4.5k +
- Senior - Salário R$ 8k +

Send your resume to rafael.reis@vix.com with subject for "Frontend Fullstack"

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
