### ISSUE TITLE
[Campinas-SP] Front-end Developer na Griaule

### ISSUE THREAD

**Issue by henrique-griaule** [frontendbr/vagas#4259]
## Nossa empresa

Somos líderes mundiais em software de reconhecimento biométrico, focado em Big Data e projetos de larga escala. Fornecemos soluções de ponta para organizações ao redor do mundo, garantindo segurança na identificação de indivíduos.

## Descrição da vaga

Estamos buscando um desenvolvedor para integrar a equipe responsável por novas features, interfaces e produtos da Griaule. Você terá contato com soluções de Big Data, serviços em nuvem, conceitos de tecnologia biométrica entre outras tecnologias de identificação pessoal.

Estamos com projetos para migrar sistemas desktop para web, então tem muita coisa legal pra ser feita!

## Local

Escritório, [SP], [Campinas], [Barão Geraldo]

## Requisitos

**Obrigatórios:**
- Contato com framework React para desenvolvimento WEB.
- Inglês - Leitura e Escrita

**Desejáveis:**
- Git, TDD, Cypress, Jest, GitlabCI, Docker.

## Benefícios
-Plano de saúde sem coparticipação
-Seguro de vida
-VA e VR
-PLR
-Plano odontológico

**Diferenciais:**
- Salário acima do mercado
- Frigobar sempre cheio
- Vista pra piscina no escritório
- Frutas
- Doces a vontade
- CAFÉ

## Contratação

CLT

## Como se candidatar

Através do site: https://griaule.com/careers/web-developer/

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 14 dias após cada processo.
E-mail para contato em caso de não haver resposta: hr@griaule.com

#### Alocação
- Alocado

#### Regime
- CLT
- Estágio

#### Nível
- Júnior
- Pleno

💰 5k-10k

**Comment by Jhessiny** [comment]
Parece que a tag remoto está equivocada.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
