### ISSUE TITLE
[Rio de Janeiro/RJ] Backend Software Engineer

### ISSUE THREAD

**Issue by GeorgeLopes** [frontendbr/vagas#426]
Job Description

BackEnd Software Engineer

Se você é apaixonado por tecnologia, rejeita rótulos, adora hardware, é louco por software e maluco o bastante para achar que pode mudar o mundo e revolucionar o mercado de Fintech global, então você é Zoop. 

Nossa sede fica na Barra da Tijuca, no Rio de Janeiro. Se você quer fazer parte do nosso time, dá uma olhadinha para entender se você é a pessoa que estamos procurando e vem fazer história com a gente!

Desafio

Estamos buscando um BackEnd Software Engineer apaixonado por tecnologia e que não tenha medo de sujar as mãos de graxa e colocar a mão na massa. Procuramos aqueles que não esperam acontecer, que são proativos e gostam principalmente de resolver problemas.

O que você precisa? 
• Ser craque em PHP, Ruby, Javascript, jQuery, Android, RESTful Services, Linux, Mac, Git, Mobile Payments, Dev Ops, HTML5 & CSS3, REST APIs, SQL, MySQL, PostgreSQL. 
• Paixão por trabalhar em um ambiente de startup, com capacidade de entregar rápido e com qualidade. 
• Ter um perfil empreendedor, ser dinâmico e proativo.

Serão diferenciais se...

• Tiver noções de Cloud / Amazon AWS/VPC, Frontend - JavaScript full, otimizações em geral e não copy and paste. :) 
• Have great english skills.

O que você vai fazer?

Você vai atuar na concepção e desenvolvimento de nossas APIs, SDKs, plataformas de pagamento e transferências eletrônicas. A oportunidade tem como missão desenvolver e arquitetar aplicações web e serviços confiáveis e que suportem milhões de usuários ativos, colaborando com os gerentes de produto, designers e outros engenheiros.

[https://angel.co/zoopbrasil/jobs/30601-backend-software-engineer]

**Comment by mtmr0x** [comment]
Oi @GeorgeLopes,

O repositório tem finalidade de filtrar apenas vagas referentes a front end. Para mantermos um padrão no público, precisamos garantir ter vagas apenas para front ends e, inclusive, tu terá mais sucesso em outros fóruns. Alguns deles fizeram um fork desse repositório e estão mais focados no mundo de back end. 

Vou precisar fechar sua issue, infelizmente, 😞  se precisar falar a respeito para esclarecimentos de quaisquer dúvidas, fico a disposição.

Obrigado pela atenção, anyway e desculpe o incômodo.

**Comment by GeorgeLopes** [comment]
ops desculpa, troquei a vaga. vou colocar a correta.
