### ISSUE TITLE
[REMOTO - Santos/SP] Front-end Developer (Angular) na [MODALGR]

### ISSUE THREAD

**Issue by MODALGR** [frontendbr/vagas#4260]
### **SOMOS MODALGR**
Somos um time apaixonado por tecnologia e a entrega de resultados é uma obsessão de nossos consultores.
Venha fazer parte do time da ModalGR, empresa de tecnologia, consultoria e outsourcing, com foco na inovação e apaixonada por tecnologia!

### **Procuramos uma pessoa que:**
- Valorize a diversidade;
- Orientado ao cliente e resultados;
- Goste de trabalhar em equipe;
- Goste de novos desafios;
- Atue com autonomia, usando a liberdade e a experiência para opinar na solução dos projetos;
- Apaixonado por inovação e tecnologia!

### **Sua Missão**
- Atuação com o time de desenvolvimento interno e do cliente, propondo e desenvolvendo soluções frontend aderentes com a realidade dos nossos clientes

### **Os requisitos para o desafio são:**
- Possuir experiência em: Angular 11, Typescript, SASS, Git

### **Não é obrigatório mas será TOP se você:**
- Tiver conhecimento/experiência com: DevOps, backend, NgRx, Git flow, padrão Atomic Design e MVC.

## **Contratação**
CLT ou PJ (a combinar)

## Como se candidatar
- Por favor envie um email para querofazerparted@modalgr.com.br com seu CV anexado
- Informar no assunto: DEV FrontEnd (Angular)
- Informar pretensão salarial CLT e PJ

#### **Nível**
- Pleno
- Sênior

**Todas as nossas vagas se destinam também para portadores de necessidades especiais :)**

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
