### ISSUE TITLE
[Remoto] Fullstack Developer (Angular e .NET) na Builtcode

### ISSUE THREAD

**Issue by dionisioleonardo** [frontendbr/vagas#4262]
> Vaga Remota durante a pandemia

## Nossa empresa

A Builtcode nasceu em 2009 com o propósito de ajudar empresas na criação de soluções de software para integrar processos operacionais, táticos e estratégicos, tornando-as mais competitivas e eficientes.
Acreditamos que precisamos unir tecnologia, conhecimento, pessoas inquietas e motivadas capazes de promover a disruptura na era digital.
Sabemos que o futuro deve ser construído por cada um de nós, e temos a certeza de que estamos ajudando a construir esse futuro a cada linha de código que escrevemos.

## Descrição da vaga

Oportunidade para desenvolvedores Fullstack nas tecnologias Angular (Front-end) e .NET (Back-end)

**Atividades e Responsabilidades**:

- Desenvolvimento e manutenção de aplicações .NET (Core e 5) Web API;
- Utilização de bancos de dados PostgreSQL ou SQL Server;
- Desenvolvimento e manutenção de aplicações FrontEnd em Angular;
- Desenvolvimento de funcionalidades em aplicações existentes ou novos projetos;
- Aplicar melhores práticas de documentação de código desenvolvido;
- Desenvolver e sustentar integrações;
- Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas;
- Realizar a manutenção e criação de novas funcionalidades;

## Local

Remoto durante a pandemia. Híbrido (remoto ou presencial) após o fim da pandemia.
O escritório está localizado em Santo André - SP

## Requisitos

**Obrigatórios:**
- EntityFramework Core (Code-First);
- Experiência com ferramentas de versionamento de código (Git);
- Conhecimento em metodologias ágeis (Scrum/Kanban);
- 1 ano de experiência na stack (Angular e .NET)

**Desejáveis:**
- Conhecimento em Repository Pattern;
- Injeção de dependência e Inversão de Controle (IoC);
- Conhecimento em CQS (Command Query Segregation);
- Conhecimento em UnitOfWork;
- Conhecimento em DDD;
- Conhecimento em Mediator;
- SQL com ADO / Dapper;

**Diferenciais:**
- Conhecimento em DevOps e CI/CD;
- Conhecimento em plataforma Azure;
- Conhecimento em plataforma AWS;
- Conhecimento em desenvolvimento Mobile (React Native);
- Conhecimento em Docker / Kubernetes;

**Diferenciais da empresa:**
- Horário flexível
- Oportunidade de trabalhar com projetos inovadores e projetos com Machine Learning e Visão Computacional!
- Trabalhar com um time de feras em diversas áreas como Empreendedorismo, Inovação e Inteligência Artificial!
- Ambiente descontraído, livre de Dress Code e toda carga corporativa!
- Salário compatível com o Mercado.
- Modelo de trabalho híbrido: Remoto ou presencial (quando passar a pandemia de COVID-19);

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para dionisio@builtcode.com.br com seu CV anexado - enviar no assunto: Vaga Dev Fullstack

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 48 horas após cada processo.
E-mail para contato em caso de não haver resposta: contato@builtcode.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
