### ISSUE TITLE
[São Paulo] Eng Software Front na Cuidas

### ISSUE THREAD

**Issue by gagaus** [frontendbr/vagas#4263]
> Vaga Remota durante a pandemia

## Nossa empresa

Na Cuidas estamos revolucionando o acesso à saúde no Brasil. Oferecemos um cuidado eficiente e personalizado conectando médicos e enfermeiros de família a empresas que se preocupam com a saúde de seus colaboradores, facilitando o acesso destes a cuidados de atenção primária à saúde.

Nosso time se preocupa e considera tudo o que influencia a saúde dos nossos usuários e utilizamos a tecnologia como uma ferramenta essencial para aproximar o contato entre as pessoas e o seu Time de Saúde Cuidas.

Por meio do aplicativo da Cuidas, nossos usuários têm acesso à(o) enfermeira(o) durante o horário comercial e podem agendar consultas com sua Equipe de Saúde sempre que precisarem. Além de oferecer atendimentos virtuais por chat ou videoconferência, a Cuidas também oferece o serviço de atendimento ambulatorial presencial, seja no local de trabalho do paciente ou em pontos de atendimento parceiros.

Nosso propósito é cuidar de muitas pessoas, uma de cada vez, tornando o acesso à saúde mais acessível e menos burocrática. Por isso, prezamos pelo cuidado de qualidade, próximo e focado na experiência do usuário, incentivando a criação de vínculos com o profissional de saúde e a pessoa atendida.

## Descrição da vaga

Na Cuidas utilizamos a tecnologia como uma ferramenta essencial para aproximar o contato entre o paciente e o seu time de saúde, construindo produtos inovadores pros nossos usuários, equipe assistencial e empresas clientes. Neste contexto, a equipe de Engenharia é fundamental para projetar, construir, testar e manter toda nossa stack, sempre pensando em performance, escalabilidade e impacto para as vidas.

Como Engenheiro (a) de Software, você será responsável por discutir novos produtos, planejar soluções e arquiteturas, escolher tecnologias e desenvolver novas partes do nosso software.

## Local

Flexível / Híbrido, São Paulo - Higienópolis

## Requisitos

**Obrigatórios:**
- 2+ anos de experiência com engenharia de software: Procuramos pessoas que sabem aplicar boas práticas de engenharia de software, seja no frontend ou backend, independentemente de linguagem e framework.
- Experiência com desenvolvimento de aplicações front-end: Procuramos pessoas com conhecimento de frameworks e bibliotecas SPA (React/React Native, Angular, Vue, Ember) e preocupação com interfaces visuais e experiência do cliente
- Experiência com metodologias ágeis

**Diferenciais:**
- Experiência trabalhando em startups de rápido crescimento
- Experiência com BDD, DDD

## Benefícios

- Remuneração compatível com o mercado
- Acesso gratuito ao serviço da Cuidas;
- Plano de saúde e plano dental;
- Vale-refeição;
- Política de folga
- Parceria para crédito consignado Creditas.
- E para quem gosta de trabalhar do escritório…​ ​Um escritório pet friendly bastante aconchegante e bem localizado: uma casa com jardim e refeitório em Higienópolis.

## Contratação

CLT

## Como se candidatar

Basta aplicar pela página da [Cuidas na Kenoby](https://jobs.kenoby.com/cuidas/job/pessoa-engenheira-de-software-front-end/5fff4ff3e649fc22a7500ced)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: pessoasecultura@cuidas.com.br

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by gagaus** [comment]
Vaga continua aberta!
