### ISSUE TITLE
[São Paulo] Front-End Developer na [Accurate Software]

### ISSUE THREAD

**Issue by themrhead** [frontendbr/vagas#4265]
![temvaganaaccurate](https://user-images.githubusercontent.com/2358039/107585655-69afb780-6bdd-11eb-83e0-025527db9b69.png)

## Nossa empresa

- Se você busca a oportunidade de colocar seus conhecimentos em prática, aperfeiçoa-los e crescimento profissional, você está no caminho certo.
- Somos uma consultoria de TI que está há três décadas no mercado, buscando sempre o aperfeiçoamento em novas tecnologias para fornecer as soluções mais adequadas às necessidades do mercado.
- Prezamos pelo respeito, a ética e a transparência em todo e qualquer ambiente, acreditamos que esses são alguns dos valores básicos para qualquer relacionamento.
- Oferecemos um ambiente leve e descontraído de trabalho, realizamos treinamentos, bate-papos, eventos tudo on-line pensando sempre em estratégias para tornar o seu desempenho produtivo e saudável.
- Então, se você quer atuar com o que gosta, com as últimas tecnologias do mercado e fazer parte de uma equipe que só cresce, venha trabalhar na Accurate.
- Saiba um pouco mais em https://accurate.com.br/carreiras/

## Descrição da vaga

Buscamos desenvolvoderes Frontend, níveis Junior, Pleno, Senior.

## Local

Remoto ou Escritório, em caso de projetos alocados em cliente, [SP], [SÃO PAULO, SÃO JOSÉ DO RIO PRETO], [VILA OLIMPIA, CENTRO]

## Requisitos

**Obrigatórios:**
- Conhecimentos em consumos de serviços (REST e JSON)
- Lógica de programação
- Desenvolvimento web (HTML, CSS, JavaScript)
- Conhecimento de linguagem funcional
- Conhecimento de React
- Conhecimentos de sistema de versionamento (Git)

**Desejáveis:**
- Conhecimento básico de Linux
- Conhecimento de Redux
- Conhecimentos de servidores web
- Conhecimento de NPM, Webpack e Node
- Conhecimento básico em Inglês
- Metodologia ágil
- Conhecimento de banco de dados: relacional e não relacional

## Benefícios 
- Vale Refeição & Alimentação
- Seguro Saúde integral
- Plano Odontológico
- Gympass
- PLR
- Café free
- Happy Hour
- Dayoff
- Vale Transporte/Fretado
- Aux. Creche
- Vale Home Office
- Flexibilidade de horário*
- Bônus por indicação
- No dress code
- e muito mais...
- ...

## Contratação

CLT OU PJ

## Como se candidatar

Por favor envie um email para rh@accurate.com.br com seu CV anexado - enviar no assunto: "Dev Frontend Júnior/Pleno/Senior"

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
