### ISSUE TITLE
[Remote] Fullstack Developer (Node + React) @ Climatempo 

### ISSUE THREAD

**Issue by feahorita** [frontendbr/vagas#4268]
## Descrição da vaga

Estamos em busca desenvolvedor fullstack ambicioso, cansado do comodismo e pronto para desafiar seus limites. As tech skills necessárias são React/React Native, NodeJS, APIs Rest e GraphQL, SQL/NoSQL e OOP.

## Nossa Empresa

Empresa 100% Online

A [Climatempo Consultoria](http://climatempoconsultoria.com.br) é a maior empresa brasileira de meteorologia, com papel fundamental na assistência estratégica de empresas afetadas por riscos climáticos. A excelência em prestação de serviço é voltada para 22 segmentos da economia, por meio de produtos e atendimento personalizados, com monitoramento de meteorologistas certificados pelo CREA. Desde 2019, a Climatempo uniu forças com a norueguesa StormGeo, líder global em inteligência meteorológica e soluções para suporte à decisão com escritórios em mais de 18 países. 

## Requisitos

* Graduação em Ciência da Computação e áreas afins, desejável
* 1 ano de experiência com desenvolvimento  
* Experiência com ferramentas de versionamento de código
* Habilidades interpessoais de escrita e de comunicação verbal
* Facilidade em debugar e identificar problemas
* Excelente raciocínio lógico
* Facilidade com algorítmos mais complexos

## Benefícios

* Contratação: PJ
* Trabalho remoto
* Flexibilidade de horários
* Empresa consolidada com potencial global e mobilidade internacional

## Como se candidatar

Curtiu? Nós também queremos te conhecer!!! Envie seu currículo com pretensão salarial para curriculo@climatempo.com.br com o nome da vaga no assunto Desenvolvedor Fullstack

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

**Comment by silversurferbeats** [comment]
https://silversurferbeats.github.io/portfolioweb/index.html
