### ISSUE TITLE
[Rio de Janeiro/RJ] FrontEnd Software Engineer no Zoop

### ISSUE THREAD

**Issue by GeorgeLopes** [frontendbr/vagas#427]
Job Description

FrontEnd Software Engineer

Se você é apaixonado por tecnologia, rejeita rótulos, adora hardware, é louco por software e maluco o bastante para achar que pode mudar o mundo e revolucionar o mercado de Fintech global, então você é Zoop. 

Nossa sede fica na Barra da Tijuca, no Rio de Janeiro. Se você quer fazer parte do nosso time, dá uma olhadinha para entender se você é a pessoa que estamos procurando e vem fazer história com a gente!

Desafio

Estamos buscando um FrontEnd Software Engineer apaixonado por tecnologia e que não tenha medo de sujar as mãos de graxa e colocar a mão na massa. Procuramos aqueles que não esperam acontecer, que são proativos e gostam principalmente de resolver problemas.

O que você precisa?

• Experiência com Javascript, jQuery, Angular, React, RESTful Services, Linux, Mac, Git, Mobile Payments, HTML5 & CSS3. 
• Paixão por trabalhar em um ambiente de startup, com capacidade de entregar rápido e com qualidade. 
• Ter um perfil empreendedor, ser dinâmico e proativo.

Serão diferenciais se...

• Tiver experiência em desenvolvimento de soluções backend. 
• Have great english skills.

O que você vai fazer?

Você vai atuar na concepção e desenvolvimento de nosso dashboard. A oportunidade tem como missão desenvolver e arquitetar aplicações web e serviços confiáveis e que suportem milhões de usuários ativos, colaborando com os gerentes de produto, designers e outros engenheiros.

Compensation
$65K – $85K 
0.2% – 0.5%
Browse Candidates Edit Job
What We're Building

Zoop enables online and offline marketplaces to easily incorporate card-present (face-to-face) and card-not-present (e/m-commerce) payment acceptance in a flexible way into both web and mobile platforms.

Developers can easily build apps that securely accept payments and offer digital payments to buyers and sellers. Our flexible SDK/API seamlessly integrates into existing systems, so that you can combine it with your own business logic.

Ready to get started? Read our reference documentation and test our API. [https://pagzoop.com/developer]
[https://angel.co/zoopbrasil/jobs/170150-frontend-software-engineer]

**Comment by RaphaAmericano** [comment]
Teria alguma vaga de estágio ai na empresa?

**Comment by rodrigues882013** [comment]
CLT?

**Comment by ygorlazaro** [comment]
É uma vaga bem interessante, mas eu tenho buscado por PJ ultimamente. Vocês trabalham com PJ?

**Comment by GeorgeLopes** [comment]
@rodrigues882013 sim, se candidata la.

**Comment by GeorgeLopes** [comment]
@ygorlazaro Ygor, boa tarde, infelizmente nao. Estas vagas em aberto somente para CLT.

**Comment by jessicaclalves** [comment]
@RaphaAmericano Boa tarde! Você poderia enviar seu currículo e telefone para o e-mail selecao@pagzoop.com?

**Comment by RaphaAmericano** [comment]
@jessicaclalves Boa tarde! Encaminhei meu cv para esse email. Obrigado.

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
