### ISSUE TITLE
[REMOTO] Full Stack Developer na Mainô

### ISSUE THREAD

**Issue by rhgrow** [frontendbr/vagas#4270]
## Nossa empresa

A Mainô uma startup que desenvolve um sistema de gestão rápido, simples e especializado em Comex. 
Estamos localizados no Rio de Janeiro e buscamos um novo Dev para compor nosso time, para uma vaga 100% remota (mesmo depois da pandemia).

## Descrição da vaga

Desenvolvimento e manutenção de funcionalidades para software de gestão, utilizando Ruby on Rails e React

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 2 a 3 anos de experiência com Ruby on Rails OU React. O importante é que você saiba bem um e esteja disposto a aprender o outro (caso ainda não domine).

## Benefícios

- Plano de saúde Sulamérica
- VR ou VA de R$ 26/dia

## Contratação

CLT

## Como se candidatar

Curtiu? Envie seu currículo para: selecao.rhgrow@gmail.com com o assunto: DEV PLENO
Quer saber mais detalhes sobre a empresa ou tirar dúvidas específicas? 
Entre em contato com a gente pelo whatsapp (21) 99393-8859

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: selecao.rhgrow@gmail.com

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
