### ISSUE TITLE
[Remoto] React.JS Sênior Web Developer na Suno Research

### ISSUE THREAD

**Issue by castmetal** [frontendbr/vagas#4271]
## Nossa Empresa

Na **Suno Research** trabalhamos para ajudar o pequeno e médio investidor a ter sucesso na bolsa de valores com recomendações e análises de investimento em renda variável. Mais do que vender relatórios, nosso foco é ajudar nossos clientes a atingir o sucesso e a independência financeira investindo no mercado de capitais de forma sustentável, sem pegadinhas ou promessas mirabolantes.

*Valorizamos, o respeito, ética, diversidade e a transparência entre nossas equipes.*

## Descrição da Vaga

A Suno Research está contratando uma pessoa **React WEB Sênior** irá atuar com desenvolvimento de novos sites, negócios e plataformas e dar apoio a todos os times para realizar testes, metrificações, integrações com ferramentas de performance e ajudar no apoio de tecnologia.

Este profissional ainda ser responsável por criar UIs dinâmicas, performáticas que ajudem a aumentar a experiência do usuário. Ajude também na construção de dashboards para a organização.

## Local

**100% Remoto**

## Requisitos

**Obrigatórios:**

- 2+ anos de experiência de mercado;
- Ter autonomia e pró-atividade;
- Conhecimentos em HTML/CSS, HTML5, CSS3 e Javascript;
- React e/ou React Native;
- Typescript
- React Hooks -> Context API;
- Props, refs, Redux, Flow, Javascript ES6;
- Styled Components ou outro estilizador;
- Testes: jest ou enzyme, React Testing Library;
- Babel, Gulp, Webpack, Configuração CI/CD;

## Desejáveis:

- Familiaridade com desenvolvimento ágil;
- Ser autodidata;
- Ter espírito empreendedor;
- Gostar de aprender e testar conceitos de UX.

## Diferenciais:

- GitHub ativo;
- Conhecimento de CLI, bundlers e automações de front-end;
 Espírito de aprendizagem contínua;
- Conhecimento no ramo financeiro;

## Contratação
PJ (com benefícios) a combinar

**Benefícios:**
- Bônus de até 3 salários ano;
- Plano de Saúde 70% Sompo Nacional pago pela empresa - quarto privativo;
- Plano Odontológico 100% pago pela empresa;
- Descontos em academias Gympass;
- Assinatura de Investimentos 100% Suno Black;
- Treinamentos, Livros, Cursos e Workshops pagos pela empresa;
- Férias 15 - 30 dias PJ;

## O que usamos:
- GIT + Scrum + Kanbam + Kubernetes EKS AWS
- React + React Hooks + Styled Components
- Gitlab
- Slack

## Como se candidatar
Por favor, envie um email para michel.laguardia@sunoresearch.com.br com seu CV anexado e link do Github com o assunto: Vaga React Web Sênior - Github/FrontendBR

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: softwares@sunoresearch.com.br

### Alocação
- Remoto
### Regime
- PJ
### Nível
- Pleno
- Sênior
### Tecnologias
- React.JS
- Typescript

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
