### ISSUE TITLE
[Remoto] Front-end Jr. Developer na ISAT

### ISSUE THREAD

**Issue by hammsterdjinn** [frontendbr/vagas#4273]
## Nossa empresa

Somos uma empresa de Tecnologia voltada para a área Educação a Distância e Comunicação Digital! 

Para não ficar muito longo aqui, vou deixar o endereço do nosso site: www.isat.com.br, para que você consiga ver um pouco mais a fundo nossos serviços e história nesse mercado. 

## Descrição da vaga

Entendemos que ter plataformas tecnológicas e processos de negócio otimizados são fundamentais para vencer na era digital. Para melhorar continuamente a experiência de seus clientes, contamos com um time multidisciplinar que faz da sua busca por resultados uma obstinação diária.

Somos próximos dos clientes, flexíveis para entender as demandas, velozes para entregá-las e apaixonados por tecnologia e eficiência.

Estamos buscando os melhores profissionais para fazer parte do nosso time de Desenvolvimento, se você tem perfil de entrega de projetos com foco em eficiência em gestão e processos, analise abaixo as demais responsabilidades e requisitos para a vaga.

Procuramos por pessoas que:

• Sejam apaixonados por tecnologia e eficiência;
• Flexíveis para entender as demandas;
• Velozes para entregar os serviços/resultados;
• Próximas dos clientes; 
• Busquem constantemente a inovação e excelência técnica; 
• Valorizem o trabalho em equipe e a troca de experiências.
• Que sejam proativas e comprometidas.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- HTML, CSS
- Javascript, Ajax
- Pré-processadores de CSS (SASS ou Less)
- Conhecimento em design responsivo com foco em usabilidade

**Desejáveis:**
- Noções de design de interação

**Diferenciais:**
- VUE, Git e .NET, MVC

**Diferenciais:**
- Ambiente descontraído, grandes desafios, muita autonomia para realizar as tarefas, oportunidade de crescimento, feedbacks e 1:1;
- Pessoas curiosas, objetivas, inteligentes, que sonham grande e são abertas ao novo;
- Remuneração competitiva ao mercado;

## Contratação

A combinar

## Como se candidatar

Por favor envie um email para paulo.carvalho@isat.com.br com seu CV anexado - enviar no assunto: Vaga Front End Jr

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: paulo.carvalho@isat.com.br

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Júnior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
