### ISSUE TITLE
[REMOTO] Desenvolvedor(a) Full Stack NodeJS @ Grupo A Educação

### ISSUE THREAD

**Issue by lucasbahiaa** [frontendbr/vagas#4274]
**Descrição:**  Somos a maior Edtech do Brasil! Com mais de 40 anos de história e tradição, somos um ecossistema de negócios voltado para a saúde e educação, com o propósito de expandir os horizontes do conhecimento. Estamos no mercado de Educação, Saúde e tecnologia, que são mercados que não param de crescer, em 2018 tivemos um aporte de um fundo do Itaú, e temos a meta de ser IPO até 2024. 
Neste momento buscamos um desenvolvedor Fullstack para para fazer parte da  novatech, área de inovação e desenvolvimento de novos produtos. Vou deixar aqui o link com os detalhes da vaga na nossa página para  facilitar  a visualização:

**Local:** 100% REMOTO
**Contratação:** CLT + Benefícios
**Benefícios:** Assistência médica e odontológica, VR/VA, PLR, Auxílio estudos, Horários flexíveis.
**Requisitos:** Desenvolvimento de APIs com Node.JS ; desenvolvimento de aplicações com VUE.JS ou React.JS; SQL (Postgrees, MySQL, SQL Server).

Mais informações, benefícios e interesse em participar basta fazer cadastro no seguinte site para darmos continuidade ao processo:

**https://byintera.in/gaedugh**

Dúvidas: https://www.linkedin.com/in/jessica-santana-96b5141a8/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
