### ISSUE TITLE
[São Paulo] Sênior Front-end Developer na ConstruCode

### ISSUE THREAD

**Issue by LayconJ0hn** [frontendbr/vagas#4275]
Aqui na ConstruCode somos uma startup que nasceu para transformar o ramo de engenharia civil. Trazemos inovação através de QRCodes posicionados estrategicamente pela obra, facilitando a visualização, acompanhamento e comunicação no projeto.

Estamos buscando alguém inovador, dinâmico que possa atuar no Desenvolvimento Front End, com Java Script, Bootstrap e JQuery para desenvolvimento Web.

CLT, Presencial, SÃO PAULO, SÃO PAULO.

## Requisitos

**Obrigatórios:**
- JavaScrip
- Bootstrap
- JQuery
- Proficiência em HTML5 e CSS 
- Pleno ou Sênior

**Desejáveis:**
- Experiência em Startups e Metodologias Ágeis
- Já ter atuado com desenvolvimento de Banners Digitais
- Ter domínio de HTML & CSS para E-mail Marketing

## Benefícios

- VR de R$ 27,30/dia
- Auxílio médico

**Diferenciais:**
- Horário Flexível

Gostou do desafio? Faz sentido pra o seu momento de carreira? Então, clica no link e confere: https://vagas-emb.byintera.com/vagafront-end

Um sorriso de orelha a orelha :D

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
