### ISSUE TITLE
[São Paulo- Interlagos- PRESENCIAL] Front Angular Júnior em BRQ Digital Solutions

### ISSUE THREAD

**Issue by ReAnne123** [frontendbr/vagas#4278]
Sobre a BRQ Digital
Há 27 anos no mercado, a BRQ Digital Solutions se consolidou como uma das maiores empresas de tecnologia do país, promovendo a digitalização de bancos, seguradoras, companhias de telecomunicação e outras instituições líderes em seus setores. Com mais de 2 mil funcionários, espalhados em seis unidades, sendo cinco no Brasil e uma em Nova York, a empresa é destaque como um dos melhores lugares para trabalhar pela GPTW e Glassdoor.

Descrição da vaga
Estamos em busca de profissionais com experiência em front com Angular, nível Júnior, para integrar o time de um grande banco internacional. Presencial em Interlagos (Zona Sul de São Paulo- estação de trem Jurubatuba).

Local
Presencial em Interlagos (Zona Sul de São Paulo- estação de trem Jurubatuba).

Requisitos
Obrigatórios:
Angular (preferência o 4).

Benefícios
Plano de saúde
Seguro de vida
VR
VA
-Previdência privada
-Plano odonto
-Gympass

Contratação
CLT full pela BRQ, salário a combinar.

Como se candidatar
Por favor envie um email para Renata (ryokota@brq.com) com seu CV anexado - enviar no assunto: Vaga Front Jr

Tempo médio de feedbacks
Costumamos enviar feedbacks em até 15 dias após cada processo.

Alocação

Alocado
Regime

CLT
Nível

Júnior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
