### ISSUE TITLE
[São Paulo - Região do Metro São Bento] PL Front-end Developer na @Mazzatech

### ISSUE THREAD

**Issue by taianeuchoa** [frontendbr/vagas#4282]
## Nossa empresa
Profissional será contratado pela Mazzatech e atuará alocado em empresa de investimentos. Esta empresa faz parte de um grande grupo bancário.
Atuação em ambiente Startup

## Descrição da vaga
•	Profissional atuará no desenvolvimento do frontend das funcionalidades do aplicativo

## Local
Empresa localizada na região do Metro São Bento, em São Paulo.
Regime atual: 3 dias de home office e 2 dias no escritório.

## Requisitos
•	Formação técnica e experiência profissional em desenvolvimento de software;
•	Conhecimento em arquiteturas de micro frontends;
•	Experiência com o desenvolvimento em ReactJS;
•	Habilidades de TDD, BDD e automação de teste;
•	Experiência com AWS
•	Versionamento de código com Git;
•	Experiência com CI / CD;
•	Cultura de automação;
•	Experiência com metodologias ágeis (como scrum, kanban);

## Benefícios
Férias remuneradas
Bonus anual

## Contratação
A combinar

## Como se candidatar
Por favor envie um email para taiane@mazza.tech com seu CV anexado - enviar no assunto: Vaga FrontEnd

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: taiane@mazza.tech

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
