### ISSUE TITLE
[Remoto] Desenvolvedor(a) Fullstack NodeJs @Deliver IT

### ISSUE THREAD

**Issue by SejaDeliver** [frontendbr/vagas#4287]
## Nossa empresa

A Deliver IT é uma consultoria de serviços de tecnologia da informação. Nossa missão é entregar valor aos nossos clientes, através de serviços de tecnologia de informação, dentro de uma relação de parceira.

Nascemos em 2014, a partir da união das atividades da Absoluta. Net com a experiência de mercado de dois profissionais sêniores, em áreas complementares! Acreditamos em equipes multidisciplinares, que possuem confiança em suas relações e sobretudo transparência. Nosso time se caracteriza pelo engajamento, comprometimento e foco na qualidade das entregas.

Acreditamos que a qualidade dos nossos processos se deve a todas as pessoas que fazem parte da Deliver, e por isso prezamos por um ambiente de trabalho agradável, leve e muito amigável. Aqui os colaboradores têm espaço para o seu desenvolvimento profissional, oportunidade de trabalhar em projetos globais e para empresas de reconhecimento a nível nacional.

Nosso portfólio de serviço utiliza tecnologias vanguardistas dentre as seguintes linhas: Fábrica de Software, Business Intelligence, Mobile e Outsourcing.

Aqui na Deliver IT temos uma cultura leve, descontraída, colaborativa e diversa :-) Venha nos conhecer!

## Descrição da vaga

Estamos em busca de um (a) Desenvolvedor (a) Fullstack para atuar junto com um time ágil e criativo, propondo novas ideias e técnicas de desenvolvimento enquanto impacta e auxilia na construção de uma plataforma global de pagamentos!!

## Local

Remoto

## Requisitos

* Sólidos conhecimentos em Node e preferencialmente em React, Java Sprint, Angular. 

## Benefícios

* VA e/ou VR
* VT
* Plano de Saúde
* Plano Odontológico
* Premiação por tempo de empresa
* Premiação por indicação.

**Diferenciais:**

* Ginástica Laboral
* Incentivo ao Inglês
* Horários Flexíveis
* Participação em Workshops técnicos

## Contratação

CLT

## Como se candidatar

Por favor envie um email para sejadeliver@deliverit.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor(a) Fullstack NodeJs

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 30 dias após cada processo.
E-mail para contato em caso de não haver resposta: sejadeliver@deliverit.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
