### ISSUE TITLE
[REMOTO] FullStack Software Engineer Sênior @ Curso Ênfase

### ISSUE THREAD

**Issue by Nagaumi** [frontendbr/vagas#4289]
### Nossa empresa
O Curso Ênfase é uma Edtech com cultura e filosofia de Startup, e mais de uma década de atuação! Contando com uma plataforma EAD de alta performance que busca cada vez mais sair da tradicionalidade dos famigerados “cursinhos preparatórios”, o Ênfase busca cada vez mais integrar tecnologia com educação, almejando tornar-se a maior plataforma tecnológica de educação do país! 

### Sobre a Vaga
Como um Desenvolvedor Full Stack, você irá participar do desenvolvimento de ferramentas e soluções que utilizam tecnologia e inovação para propor um novo jeito de estudar. Nosso foco é em uma equipe altamente engajada que se preocupa com excelência não só nos produtos, mas também no ambiente, cultura e principalmente, nas pessoas.

### Principais Stacks
- Frameworks em Javascript (Node.js, React/Vue.js/Angular);
- Ferramentas de versionamento de códigos (SVN ou Git);
- Conhecimento sólido em estruturas de dados.

### Modelo de contratação 
PJ

### Mais informações sobre a empresa e a vaga
https://byintera.in/enfasefsgh

Gostou da oportunidade? Acessa o link para se inscrever.

Achou esse desafio a cara de alguém? Manda para essa pessoa!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
