### ISSUE TITLE
[Remoto] Front-end React Sênior na Maitha Tech

### ISSUE THREAD

**Issue by Patricia-MaithaTech** [frontendbr/vagas#4295]
## Nossa empresa

Somos uma empresa digital, com experiência em tecnologia e inspirada pela inovação. Atuamos na aceleração, transformação e ideação de novas soluções e times de alta performance.
Atuamos tanto na construção de times de tecnologia, quanto em frentes de negócio, na co-criação de produtos, levantamento de requisitos, resolução de problemas, entre outros.

## Descrição da vaga

Para prestar serviço a uma empresa que é especialista em negócios digitais e conta com clientes como: Ambev, Bayer, Coca Cola, Dior, Mondelez, entre outros!
Estamos com um novo projeto para atuar a frente de uma nova fintech que está sendo criada do zero, então o projeto primário é a criação da Fintech, secundário é um projeto de cashback e checkout.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- React
- HTML
- CSS
- Javascript

## Contratação

PJ - até 15k

## Como se candidatar

Contato via Linkedin: https://www.linkedin.com/in/patriciapcarrillo/ ou envie um e-mail para patricia@maitha.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor Front End React

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
