### ISSUE TITLE
  [REMOTO] Desenvolvedor(a) Full Stack JAVA @ EscolaConquer

### ISSUE THREAD

**Issue by PedroGabrielFBarbosa** [frontendbr/vagas#4296]
**Descrição:**  A Conquer nasceu da nossa insatisfação com as instituições tradicionais – faculdades e pós-graduações -, que focam muito na parte teórica e não ensinam as habilidades práticas que realmente fazem a diferença para um profissional se destacar e chegar mais longe.Somos a maior Edtech do Brasil! Com mais de 40 anos de história e tradição, somos um ecossistema de negócios voltado para a saúde e educação, com o propósito de expandir os horizontes do conhecimento. Atualmente o mercado de Educacao teve crescimentono ultimo trimestre de XXX%, captando diversos profissionais de diferentes areas para instituicoes que fazem a diferenca no mercado. 
Neste momento buscamos um desenvolvedor Fullstack para para fazer parte da  Conquer, área de inovação,otimizacao e desenvolvimento de novos produtos. Vou deixar aqui o link com os detalhes da vaga na nossa página para  facilitar  a visualização:

**Local:** 100% REMOTO
**Contratação:** CLT (PJ negociavel)
**Benefícios:** Assistência médica e odontológica, VR/VA, PLR, Auxílio estudos, Horários flexíveis.
**Requisitos:** Sólida experiência com linguagem Java
experiência com framework spring, no front-end React (Vue.JS ou angular também funciona), conhecimento APIs rest.

Mais informações, benefícios e interesse em participar basta fazer cadastro no seguinte site para darmos continuidade ao processo:

**https://vagas-emb.byintera.com/28p**

Dúvidas: https://www.linkedin.com/in/pedro-gabriel-41137b1ba/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
