### ISSUE TITLE
[CURITIBA-PR] Web Designer @ Grupo A Educação

### ISSUE THREAD

**Issue by FabianaSN** [frontendbr/vagas#4297]
**Descrição:**  Somos a maior Edtech do Brasil! Com mais de 40 anos de história e tradição, somos um ecossistema de negócios voltado para a saúde e educação, com o propósito de expandir os horizontes do conhecimento. Estamos no mercado de Educação, Saúde e tecnologia, que são mercados que não param de crescer, em 2018 tivemos um aporte de um fundo do Itaú, e temos a meta de ser IPO até 2024. 
Neste momento buscamos um Web Designer para ajudar na criação e edição de peças publicitarias para redes sociais, e-mails marketing, banners e catálogos e criação e manutenção de paginas no site.

**Local:** Curitiba-PR
**Nível:** Pleno
**Contratação:** CLT + Benefícios
**Benefícios:** Assistência médica e odontológica, VR/VA, PLR, Auxílio estudos, Horários flexíveis.
**Requisitos:** Conhecimento em programação Web, Javascript, HTML, CSS,  Marketing Digital e Ferramentas de edição de imagem e vídeo.

Mais informações, benefícios e interesse em participar basta fazer cadastro no seguinte site para darmos continuidade ao processo:

**https://byintera.in/wdesignergh**

Dúvidas: https://www.linkedin.com/in/fabisnascimento

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
