### ISSUE TITLE
[REMOTO - Santos/SP] Tech Lead (REACT e Node.js) na MODALGR

### ISSUE THREAD

**Issue by MODALGR** [frontendbr/vagas#4299]
### **SOMOS MODALGR**
Somos um time apaixonado por tecnologia e a entrega de resultados é uma obsessão de nossos consultores.
Venha fazer parte do time da ModalGR, empresa de tecnologia, consultoria e outsourcing, com foco na inovação e apaixonada por tecnologia!

### **Procuramos uma pessoa que:**
- Valorize a diversidade;
- Orientado ao cliente e resultados;
- Goste de trabalhar em equipe;
- Goste de novos desafios;
- Atue com autonomia, usando a liberdade e a experiência para opinar na solução dos projetos;
- Apaixonado por inovação e tecnologia!

### **Sua Missão**
- Atuação com o time de desenvolvimento interno e do cliente, liderando os times de Node.js e REACT no desenvolvimento de  soluções frontend e backend aderentes com a realidade dos nossos clientes

### **Os requisitos para o desafio são:**
- Possuir experiência em: REACT, Node.js, API REST, Redux, Styled Components, Storybook, Git

### **Não é obrigatório mas será TOP se você:**
- Tiver conhecimento/experiência com: DevOps, Git flow e padrão de desenvolvimento MVC.

## **Contratação**
CLT ou PJ (a combinar)

## Como se candidatar
- Por favor envie um email para querofazerparted@modalgr.com.br com seu CV anexado
- Informar no assunto: Tech Lead (REACT e Node.js) - GitHub
- Informar pretensão salarial CLT e PJ

**Todas as nossas vagas se destinam também para portadores de necessidades especiais :)**

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by rodolfocharles** [comment]
Gostaria de candidatar para esta vaga. Segue meu linkedin: [https://www.linkedin.com/in/rodolfo-martins-charles-00869a23/](url)
