### ISSUE TITLE
[São Paulo] Desenvolvedor Front-End - R7.com

### ISSUE THREAD

**Issue by tcelestino** [frontendbr/vagas#43]
## Descrição da vaga

O R7.com está aumentando sua equipe e está em busca de desenvolvedor Frontend com proficiência em HTML5, CSS3 e Javascript. Nossa equipe é multidisciplinar, com projetos envolvendo integrações de múltiplas aplicações nas mais diversas linguagens e tecnologias.

O profissional que buscamos deve ser dinâmico, pro-ativo, responsável e acima de tudo com atitude positiva e paixão pelo que faz.
## Local

Rua da Várzea, São Paulo - Barra Funda
## Benefícios
- home office (2x ao mês)
- sala com xBox 360
- PLR
- dois monitores
## Requisitos

**Obrigatórios:**
- experiência com HTML5, CSS3, JS
- trabalhar com sistemas UNIX
- experiência com GIT

**Desejáveis:**
- conhecimentos em Backbone, Angular ou React
- conhecimentos em libs Javascript (jquery, underscore, lodash)
- conhecimentos em templates engines (underscore, mustache, handlebars)
- conhecimentos em pré-processadores CSS (SASS/ Less/ Stylus)
- conhecimento em ferramentas de tasks (Grunt/ Gulp)
- inglês técnico

**Diferenciais:**
- conhecimento em Ruby
- teste unitário (jasmine)/ teste funcional (selenium/nightwatch)
## Contratação

CLT Full
## Nossa empresa

O [R7.com](http://r7.com) é um portal mantido pela Rádio e Televisão Record S/A, com mais de 5 anos de vida. Possui 50 milhões de visitantes únicos, e 1 bilhão e meio de page views mensalmente e conta com uma equipe de quase 500 pessoas.
## Como se candidatar

Por favor envie um email para [apinto@sp.r7.com](apinto@sp.r7.com) com seu CV anexado.
Enviar no assunto: Vaga Front-End

**Comment by LFeh** [comment]
@tcelestino Entendi que a vaga é pleno, to certo? :smile_cat:

**Comment by tcelestino** [comment]
@LFeh pode ser pleno ou senior.

**Comment by simaodeveloper** [comment]
@tcelestino Essa vaga ainda esta aberta?

**Comment by gkal19** [comment]
Queria ser se São Paulo

**Comment by tcelestino** [comment]
@simaodeveloper, vou procurar saber e te passo a informação. :)

**Comment by simaodeveloper** [comment]
@tcelestino  Me manda o seu facebook

**Comment by simaodeveloper** [comment]
@tcelestino mandei e-mail, mas até agora nada, consegue algum contato pra mim?

**Comment by LFeh** [comment]
@tcelestino A vaga foi preenchida?

**Comment by NicholasPedroso** [comment]
Espero que sim @LFeh pois acabei de mandar um email para lá kkkkk ✌️ ✌️

**Comment by gkal19** [comment]
Tem chances de remoto?

**Comment by eduardojmatos** [comment]
@tcelestino sabe se foi preenchida ou ainda estão contratando? Só pra gente remover ou manter aqui :)
