### ISSUE TITLE
[SÃO PAULO] Javascript Developer na Evolution IT 

### ISSUE THREAD

**Issue by MarinaEvolutionIT** [frontendbr/vagas#430]
## Local

Fábrica de desenvolvimento Evolution IT
Barra Funda (São Paulo/SP) próximo ao metrô e Memorial da América Latina

## Requisitos

• Excelente raciocínio lógico e lógica de programação
• Disciplina, qualidade, organização e pragmatismo
• Domínio da linguagem Javascript e seu ecossistema:
o Containers: PhoneGap, Cordova, Ionic
o Frameworks Javascript tais como Angular.js, Jquery, Bootstrap, React
o HTML 5, CSS 3
o MVC
o Webstorage, off-line apps e SQLite
• Serviços REST, OData, JSON, SOAP, XML.

## Contratação

PJ 

## Como se candidatar

Por favor envie um email para marina.duarte@evolutionit.com.br com seu CV anexado, pretensão PJ e disponibilidade de início - enviar no assunto: Vaga Front End.

**Comment by gadielkalleb** [comment]
Jr, PL ou sr ?

**Comment by MarinaEvolutionIT** [comment]
Estamos analisando perfis PL e SR
