### ISSUE TITLE
[Palhoça] Front-end Developer DotNet C# na Weduka

### ISSUE THREAD

**Issue by dorischavinski** [frontendbr/vagas#4301]
Weduka

Estamos no Vale do Silício brasileiro. Respiramos novidade diariamente na cidade mais inovadora do país, ao lado de startups que estão reescrevendo a forma como a tecnologia influencia a vida das pessoas.

Descrição

Trabalhar em diferentes arquiteturas, atuando no Front-end e Back-end; discutir e contribuir com melhorias de código, arquitetura e até mesmo processos; possuir flexibilidade para assumir novos projetos e/ou dar manutenção nos existentes.

Local: Pedra Branca, Palhoça/SC - trabalho em modelo híbrido.

Requisitos
.Net C#; banco de dados, principalmente SQL Server; JavaScript, HTML e CSS e desenvolvimento WEB.

Obrigatórios:
1 ano de experiência com C#;
2 anos de experiência com SQL Server.

Desejáveis:
sistema Git

Diferencial:
sólidos conhecimentos de Front-end.

Benefícios
Vaga em modalidade PJ com 30 dias de férias.

Contratação
- PJ a combinar

Como se candidatar
Por favor envie um email para doroti@consultoriacontato.com com seu CV anexado - enviar no assunto: Vaga DotNet. Ou cadastre-se em nossa plataforma através do link https://contato.enlizt.me/vagas/desenvolverdor_fullstack_.net_c--290121

Tempo médio de feedbacks
Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: nathalia@consultoriacontato.com

Nível
- Pleno

Período
- Full time

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
