### ISSUE TITLE
[OPORTUNIDADE] [REMOTO] [FRONT END] [PLENO]

### ISSUE THREAD

**Issue by Irand27** [frontendbr/vagas#4302]
Estamos com uma oportunidade incrível para atuar como Front-end Developer Pleno na CUBOS, CLT ou PJ! Empresa com desejo pujante de criar, impactar, aprender e causar uma diferença significativa na vida das pessoas através da tecnologia! É uma grande oportunidade de contribuir ativamente nas etapas de ideação, planejamento e desenvolvimento dos produtos web!

Oferecendo um ambiente colaborativo, flexibilidade, pessoas incríveis dispostas a aprender e ensinar. Usamos tecnologia porque dá acessibilidade de conhecimento, porque simplifica o mundo, porque tecnologia é sinônimo de evolução, porque tecnologia é consequência da própria existência humana. Criamos tecnologia com significado.

A oportunidade requer conhecimento em TypeScript e React.js! 
Caso tenha também VTEX.IO como stack, será um bom diferencial! 
Um pouco mais sobre no link:
byintera.in/2ad

Se você está aberto(a) a oportunidades e quer saber um pouco mais sobre o desafio a ser enfrentado, dá uma olhadinha no link

Não faz sentido pra você mas conhece alguém que pode se interessar? Compartilha o link!
Ótima semana! E um sorriso de orelha a orelha =)
#vagasbyintera #oportunidade #emprego #recolocação

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
