### ISSUE TITLE
[Remoto - Amsterdam] Senior Front-end Developer na powerUp

### ISSUE THREAD

**Issue by comutech** [frontendbr/vagas#4304]
## Nossa empresa

oneUp is a corporate innovation factory and home to 40+ rebel innovators, dreamers, space explorers and nerds based in Amsterdam. We design, validate, execute and scale new digital products and services for large organizations. And help them to do it on their own structurally through our innovation management approach.

In our free time, we like to work to make our company better and share our knowledge with each other (and have some fun together ;)).

## Descrição da vaga

oneUp is a corporate innovation factory and home to 40+ rebel innovators, dreamers, space explorers and nerds based in Amsterdam, Antwerp and Hamburg. 
We design, validate, execute and scale new digital products and services for large organizations. And help them to do it on their own structurally through our innovation management approach.

oneUp is looking for a talented Front-end Developer to be part of our newest and hottest spin-off startup ([powerUp](https://powerupinnovation.com)) our ultra-techy division that has the mission to develop all our software and digital applications for innovation management.

### powerUp Team Culture

powerUp has oneUp's DNA but also has its own culture. It’s a team that has been always working 100% remote, as each of us different country (Netherlands, Belgium, Norway and Sweden). By joining our tech division you will be part of a creative team that is passionate about technology, values work-life balance and has a good team vibe. We are productivity hackers and autonomous self-motivated beasts! We value respect and NVC (Non-violent communication).

We are all unique in our own ways, from mindfulness practitioners, beer/kombucha brewers, biohackers to gamers and cooking pros. We are an odd bunch that gets along well together. You are welcome to bring your own personality and badassness to this mix. 😎

We are building SaaS that incorporates all necessary functions to enable a radical innovator to stay focused on what matters. Our software suite includes idea, innovation portfolio and project management tools to enable corporate innovators of all levels to innovate based on data and evidence. We incorporate the best practices of Lean startup, Design thinking, and agile-scrum/kanban to make a streamlined end-to-end experience.

### Responsibilities

- Translate Figma designs into pixel-perfect implementations
- Provide technical expertise to the team
- Create and maintain components in our component library
- Functionally implement said components in the software
- Speak your mind and challenge ideas when necessary
- Take pride and responsibility in delivering quality implementations
- Own and contribute to the powerUp vision with your ideas and insights
- Identify, log and fix those pesky bugs
- Keep others to a high standard by conducting code reviews
- Write unit tests for the stuff you build
- Asking too many questions is always better than asking too few
- Being creative to propose creative solutions when faced with a challenge

### Practical details 

- oneUp BV is a Dutch company located in Amsterdam, The Netherlands
- powerUp BV is a dutch SaaS company located in Amsterdam, The Netherlands but we operate remotely. 
- The job is a full-time period (40h/week)
- The job is 100% remote but you are expected to be available to interact with the team during European working hours (around 9:00 pm-5:00 pm, CET time

### Why we need each other

powerUp is a young software company that is spinning off from oneUp this year and we have grandiose plans for our software. We want to be the crème de la crème innovation software and you are invited to join us in this very early stage of our journey to help us achieve this big goal! There’s plenty of room for you to grow and be an early member of our dream!

You need us because of our awesomeness levels match! Because you will have freedom at work and will be empowered to make decisions. You will have fun for sure with lots of responsibilities. Our standards are high, but we know you are not a cyborg, so you can expect a reasonable work-life balance and flexibility to work on your rhythm as far as you deliver on your commitments. 

## Local

REMOTE

The job is 100% remote but you are expected to be available to interact with the team during European working hours (around 9:00 pm-5:00 pm, CET time

## Requisitos

Outstanding front-end developers are team players who apply their discipline and meticulous eye for details combined with creativity and good communication. 

To broaden the powerUp team we are looking for an experienced UI developer with the following skills: 

#### Hard Skills

- Javascript/Ecmascript
- Vue.js
- HTML (Focus on standard compliance and semantics)
- CSS (SCSS/SASS, PostCSS)
- Interaction development 

#### Solid experience with

- Implementing designs into fully functional pixel-perfect components
- Cross-browser development
- Distributed teams and development

### Diferenciais

- Experience with Webpack
- Experience with Figma/Sketch/similar tools
- Experience with the process from idea to design to implementation
- Experience building extensive design systems
- Knowledge of automated UI testing
- Back-end or DevOps related development
- Experience with agile frameworks

### Interpersonal/soft skills

- Implementer - you just get shit done. As simple as that
- Being in a team gives you energy
- You don't need anyone breathing on your neck to get shit done
- Autodidactic and addicted to learning
- Fluent English speaker/communicator
- You don't lose your cool under pressure
- Effective communicator, both written and verbal
- You are meticulous and have a natural focus on quality and details

## Benefícios

- Own oneUp Academy and additional personal development budget
- Operating from one of the biggest start-up eco systems: B3
- Macbook/iphone and all other perks a techie could dream of
- Amazing (Masterchef) lunches and events (weekend in Belgium, ski-trip)
- Working for and with renowned corporates; Unilever, JDE, PVH and many more

## Contratação

Permanent contract - CLT

## Como se candidatar

Envie um email para comutechbr@gmail.com com seu LinkedIn e CV anexado - enviar no assunto: "Vaga Front-end Developer @ powerUp".

Nós vamos facilitar para você o contato com a powerUp. Tire qualquer dúvida sobre a empresa, vaga ou processo seletivo!

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
