### ISSUE TITLE
[Remoto] Senior/Lead Front-end Developer na Dentsu World Services Brazil (DWS Brazil)

### ISSUE THREAD

**Issue by Cristinaandradesouza** [frontendbr/vagas#4309]
###  **Nossa empresa**

**Sobre a DWS Brazil**

A Dentsu World Services (DWS) é parte do grupo dentsu, presente em 145 países e com mais de 62.000 pessoas comprometidas com soluções em inovação, comunicação e tecnologia. Em Porto Alegre atuamos como centro de tecnologia, inovação e design do grupo Dentsu.

Muitos desafios, aprendizado e crescimento esperam você na DWS!

**Sobre os times:**

O profissional irá se juntar ao time da Isobar DWS Brazil para atender aos projetos provenientes de várias parcerias com Isobares ao redor do mundo, podendo fazer parte de times com US ou com a Suíça/Portugal, sendo parte do time localizado no Brasil.

Inglês é fundamental, pois os times contam com pessoas de vários países, sendo o Inglês é a língua oficial.

Vaga para projeto internacional, então vamos seguir em Inglês ;)

## Descrição da vaga

Requirements (the ideal candidate will):

- Be familiar with a team approach to execution
- Possess effective written and verbal communication skills in English
- Understand approaches to designing and implementing responsive websites

## Local

100% Remoto ou híbrido no escritório em Porto Alegre/RS para residentes próximos (após a pandemia).
Aceitamos candidatos de todo BR.

## Requisitos

**Obrigatórios:**

- Master of web technologies, including HTML5, CSS3, JavaScript, Typescript, JavaScript frameworks (e.g. React.js, Vue.js);
- Good understanding of state management libraries (e.g. Flux, Redux, Vuex);
- Thorough understanding of responsive web design, fluid layouts, and positioning;
- Thorough understanding of performance, cross-browser / cross-device development, testing, optimization, and front-end performance requirements;
- Expertise in the evaluation, selection and use of development frameworks and tools;
- Experience with source-code management tools (e.g., Git, SVN);
- Able to set up source control and continuous integration tools, as well as assist in code branching and merging within the project;
- Experience with build systems (e.g. Webpack, Gulp, Grunt) and unit testing;
- Experience with NodeJS and NPM;
- Design and conceptual skills;
- Knowledge of Clean Architecture concepts;
- Good understanding of SOLID principles;

## Benefícios

- Plano de saúde e odontológico
- Seguro de vida em grupo
- VR de R$ 730/mensais
- Auxilio HO de R$ 120/mensais até o final da pandemia
- VT ou estacionamento ou auxilio a apps de transporte no valor de ate R$ 200/mensais

**Diferenciais:**
- Horário flexível
- Incentivo a aulas de inglês (inglês in company)
- Mimos enviados em casa pelo nosso awesomeness committee
- frigobar sempre cheio no escritório

## Contratação

CLT com pretensão a combinar.

## Como se candidatar

Por favor, realize inscrição no link: https://apply.workable.com/dwsbrazil/j/57DA1CD59F/ 

Usamos o Workable como plataforma para os nossos processos seletivos.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada etapa do processo (entrevista geral, teste técnico, entrevista técnica, entrevista com pessoal do projeto em US).

E-mail para contato em caso de não haver resposta: cristina.souza@iwsbrazil.com ou amanda.kurle@iwsbrazil.com

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível

- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
