### ISSUE TITLE
[SAO PAULO] Front-End Developer na redspark

### ISSUE THREAD

**Issue by isabellasales** [frontendbr/vagas#431]
A redspark é uma empresa de desenvolvimento de software e aplicativos mobile que está a 10 anos no mercado com sede em São Paulo (Berrini) e Ribeirão Preto. 

## **Local**

redspark tecnology
Berrini (São Paulo/SP) próximo à estação de trem Berrini.

## **Requisitos**

- Orientação a objetos
- Desenvolvimento JavaScript
- Desenvolvimento HTML e CSS
- Desenvolvimento de Web Single Page Applications
- Desenvolvimento de WEB Pages com HTML5 e CSS3
- Bibliotecas e plugins Javascript (JQuery)
- Frameworks Javascript MVC, como AngularJS, BackboneJS, EmberJS
- Desenvolvimento de páginas responsivas

## **Atividades** 

É necessário que possua experiência na área, disponibilidade para trabalhar na região do Berrini e que atendam os requisitos acima :)

## **Como se candidatar**

Por favor envie um email para isabella.sales@redspark.io com seu CV anexado, pretensão salarial.

**Comment by LFeh** [comment]
Quais as labels?
