### ISSUE TITLE
[Lisboa ou Porto/ Portugal ] Java Developer @Integer Consulting

### ISSUE THREAD

**Issue by brunoalexandrecarvalho** [frontendbr/vagas#4312]
# Integer Consulting

A INTEGER, uma empresa de consultoria na área das tecnologias, com mais de uma década de presença no mercado português, está à procura de desenvolvedores JAVA com fortes habilidades de comunicação, sentido de responsabilidade e trabalho em equipa.

## Este pode ser o desafio perfeito para ti se tens:

• Experiência em desenvolvimento BackEnd (Java, Spring Boot, Microserviços);
• Conhecimentos de serviços e arquiteturas web (HTTP, SOA, REST, JSON);
• Conhecimentos em bases de dados não relacionais;
• Conhecimentos na implementação de metodologias ágeis e ambientes CI e CD;
• Inglês Fluente;

Se tens o amazINg talent pretendido e queres fazer parte da equipa INTEGER, responde a este anúncio com o teu CV atualizado para bruno.carvalho@integer.pt.

Participar neste projeto significa a integração numa empresa sólida em crescimento e numa equipa jovem e dinâmica. #jumpIN

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
