### ISSUE TITLE
[Remoto] Senior Front-end Developer na Kyte

### ISSUE THREAD

**Issue by rafaelmotta** [frontendbr/vagas#4317]
## Nossa empresa

Kyte is a technology platform that brings seamless delivery into the rental car experience. We are building the most compelling and customer-centric way to rent a car. With our value proposition of an easy car rental delivery experience with consistent & approachable support, we saw record growth throughout COVID19, and are now doubling down on gaining market share.

We recently [raised](https://techcrunch.com/2021/01/05/kyte-raises-9-million-to-deliver-rental-cars-to-your-doorstep) more than $9M in venture funding from some of the best investors in the industry (amongst others, investors in Auto 1, Bird, Lime, DoorDash, Flexport, and Slack).

**How we work**

- Our Backend is written with Python using Flask and PostgreSQL
- Our Frontend is written with Typescript using React and React Native
- We have the mindset "you built it, you run it"
- We ship code to production (AWS) several times per day using Gitlab CI/CD

## Descrição da vaga

As a Senior Frontend Engineer, you will build reliable and scalable systems from day one that handle tons of data points, match our booking requests, dispatch vehicles, calculate ETAs and much more. Both in real-time as well as in batch.

You will work closely together with the product and operations team to develop features, architect and design systems and ship products to our users, partners and internal stakeholders.

**Responsibilities**

- Contribute to Kyte's codebase as a Senior Frontend Engineer (Web and Mobile)
- Identify, discuss, document and communicate technical improvements within your area of responsibility
- Support, improve and reinforce Frontend/Engineering standards and guidelines
- Close collaboration with technical (Backend engineers, Site Reliability Engineers) and non-technical (product designers and product managers) roles to understand and challenge end user requirements, and ultimately translate these into effective technical solutions
- Coach and onboard team members

## Local

Exemplo: Remoto ou Escritório, Bavária, Munique, Nymphenburg

## Requisitos

**Obrigatórios:**
- At least 7 years of experience
- Fluent in English
- Ability to architect and design modular and scalable systems
- Appreciation towards software craftsmanship, clean code, and SOLID design principles
- Deep knowledge of Javascript and React
- High standards for the quality of UI and experience interpreting and executing on the outcomes of UX research and Product Design
- Experience working in an agile setup using continuous deployment and delivery
- Hustling-, hardworking- & shipping-products attitude: Go above and beyond to get things done!
- Ownership: You are a self-starter and are satisfied by owning large chunks of the product roadmap.
- Ambition: You are ridiculously ambitious and want to get the most out of your life.

**Desejáveis:**
- AWS & DevOps
- Data/Cyber security
- React Native
- D3

**Diferenciais:**
- projetos opensource

## Benefícios

- Market-proven, well-funded and fast-growing company
- Virtual shares (full-time employees only)
- Macbook Pro and gadgets
- Transportation benefits
- Gym benefits
- Office visits across San Francisco and Munich
- The opportunity to be a part of the exciting early stages of a well-funded, Silicon Valley based startup that has massive growth and venture potential
- You’ll be able to work, innovate, and grow with a ridiculously ambitious, committed and fun team in the Munich and San Francisco tech ecosystem
- You’ll have the ability to have major impact on a product that is on its way to impact millions of users in a profound way

## Contratação

PJ. 4000-6000 USD mensais de acordo com experiencia. Possibilidade de realocao pra Munique caso tenha Diploma em em ciencias da computacao ou similar (faculdade, nao curso técnico)

## Como se candidatar

https://jobs.lever.co/drivekyte/5aba1b4a-b544-4b7b-ad83-8b9eb34a7c67

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
