### ISSUE TITLE
[Remoto] Pessoa Desenvolvedora de Software na ISH

### ISSUE THREAD

**Issue by brunosantanarj** [frontendbr/vagas#4318]
## Nossa empresa

O nosso negócio é oferecer serviços customizados de cibersegurança, infraestrutura crítica e nuvens blindadas e nossa missão é tornar o mundo digital mais seguro e acessível.

Estamos há mais de 20 anos no mercado e ocupamos a 27ª posição no ranking das 200 principais provedoras de serviços de segurança gerenciados do mundo, publicado pela MSSP Alert.

Com mais de 400 profissionais especializados, tem entre seus clientes algumas das maiores empresas do Brasil, incluindo bancos, fintechs, instituições financeiras, varejistas, atacadistas, empresas da área de saúde e órgãos públicos.

A matriz fica em Vitória (ES), e a empresa mantém filiais em São Paulo, Rio de Janeiro, Belo Horizonte, Brasília, Curitiba e Goiânia.

Se você gosta de ambientes estáveis e estruturados, com tarefas bem definidas e com um plano de carreira consistentemente estruturado que assegure uma linha previsível para evolução, aqui NÃO é o seu lugar.

Agora, se você procura um ambiente de extrema velocidade e volatilidade, onde você vai respirar inovação e encontrar espaço para desenvolver seu potencial ao máximo, com uma cultura totalmente baseada em meritocracia e na construção de times de altíssima performance... vem com a gente!

## Descrição da vaga

Atuar em todas as etapas do processo de construção de Produtos inovadores que ajudem a rastrear, prevenir e mitigar ações cibernéticas maliciosas, contribuindo para tornar o mundo digital mais seguro.

Atualmente temos projetos com as seguintes tecnologias:

- Front-end: React(Redux-Saga, TypeScript), Vue e Angular(TypeScript). Usamos muitos gráficos(Charts) aqui.
- Back-end: Python(Django) e PHP(Laravel). Diversos serviços e API's.
- DevOPS: Docker, Rancher e GitLab. Nosso CI/CD.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Trabalho em equipe e boa comunicação
- Sólidos fundamentos em Ciência de Computação e Informática.
- Entendimento de processos e boas práticas de Engenharia de Software;
- Gostar de todos os tópicos de Engenharia de Software tais como backend, frontend, devops, sem desconsiderar sua vocação natural para algum deles;
- Capacidade analítica/raciocínio logico (problem solving/algoritmo)
- Escrever código limpo, reutilizável e de fácil manutenção;
- Práticas de XP
- Prezar pela qualidade e privacidade desde a concepção
- Ajudar a definir e manter padrões de design e arquitetura dos sistemas (Pleno e Sênior);
- Tomar decisões técnicas quando for preciso, envolvendo e alinhando equipe, clientes e stakeholders (Pleno e Sênior);
- Atuar como mentor e referência, colaborando com o aprendizado dos demais Devs (Pleno e Sênior).

**Desejáveis:**
- TypeScript
- Conhecimento em Libs de gráficos(nivo.rocks e GoogleCharts por exemplo)

**Diferenciais:**
- React
- Vue
- Angular
- RxJs
- Redux-Saga

## Contratação

PJ a combinar ou CLT.

## Como se candidatar

Por favor envie um email para bruno.santana@ish.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor de Software - frontendbr

No e-mail peço que coloque o nível que você se considera (JR, PL, SR).

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias úteis após cada processo.
E-mail para contato em caso de não haver resposta: bruno.santana@ish.com.br

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by ItaloCanturil** [comment]
Me interessei bastante, gosto de Vue e ja usei a biblioteca Google Charts, CV enviado!!!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
