### ISSUE TITLE
[Remoto] Fullstack / Angular Developer na VipCommerce

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#4319]
## Descrição da vaga: 
 <p>Buscamos Fullstack Developers com foco em front-end para trabalhar em produto com stack: Angular 4+, Node.js, PHP e AWS.</p>
<p>A VipCommerce é uma empresa especializada em e-grocery, especificamente e-commerce para supermercados, atacarejos e atacados. Atualmente é Líder no segmento na vertente white-label, integrada e homologada com os maiores ERP´s do segmento.</p>

## VipCommerce: 
 <p>A VipCommerce nasceu dentro de um supermercado e com vários anos de experiência no segmento varejista, entendemos o dia-a-dia do setor. E, prevendo que a venda online seria um progresso natural para os supermercados, transformamos nosso conhecimento em uma solução completa e robusta para habilitar as lojas tradicionais a venderem online.</p>

<p>Nosso compromisso é conduzi-lo, através de uma parceria duradoura, nesta transformação digital. Conte com a gente para vender online e faturar mais de um jeito seguro e descomplicado.<br></p><a href='https://coodesh.com/empresas/vipcommerce'>Veja mais no site</a>

 ## Habilidades: 
 - Angular.js 
- MySQL 
- PHP 
- Node.js 
- BDD 
- AWS Aurora 
- TDD

## Local: 
 100% Remoto

## Requisitos: 
 - Fluente em trabalhar com Angular 4+ 
- Experiências em posições semelhante ou atuando como freelancer 
- Habituado em trabalhar com consumo de REST APIs 
- Domínio de programação orientada a objetos 
- Saber trabalhar em equipe, em times (participativo, paciente, mediador) 
- Ser pró-ativo e interessado em aprendizado contínuo 
- Conhecimentos em TDD e BDD 
- Habituado em trabalhar com metodologias ágeis / Scrum 
- Muito interesse em se desenvolver como fullstack developer e atuar em features de back-end 
- Ser engajado em pequenos times, clima de startup e negócios que crescem de maneira acelerada (pouca zona de conforto / Lean Startup) 
- Ser engajado com os ideias do negócio, abraçar as causas da empresa e frequentemente ser "confundido com o dono", pelo aspecto do pensamento comprometido.

## Benefícios: 
 - Convênio Médico e Odontológico Sul América - Nacional 
- Vale Alimentação / Refeição 
- Horários Flexíveis 
- Auxilio Home Office 
- Participação nos Lucros e Resultados 
- PJ ou CLT

## Como se candidatar:
Candidate-se em: [Fullstack / Angular Developer na VipCommerce](https://coodesh.com/vagas/desenvolvedor-a-fullstack-angular-150000?origin=github&modal=open)

## Tempo médio de feedbacks:
 Costumamos enviar feedbacks em até 48 horas após cada etapa do processo. E-mail para contato em caso de não haver resposta: [contato@coodesh.com](mailto:contato@coodesh.com)

#### Alocação
Remoto

#### Regime
CLT

#### Nível
Sênior

#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
