### ISSUE TITLE
[São Paulo / Remoto] Desenvolvedor Front-End, com foco em Angular 4, na Sem Hora

### ISSUE THREAD

**Issue by gnumoksha** [frontendbr/vagas#432]
## A empresa
O Sem Hora é uma empresa de tecnologia aplicada à eventos (TAE) que nasceu há cerca de 4 anos e está localizada em Alto de Pinheiros, São Paulo. Oferecemos aos nossos clientes soluções que abrangem várias etapas dentro do ciclo de vida de um evento, indo desde a sensibilização do público alvo até a análise posterior.

Aqui você encontrará um ambiente descontraído e alegre, além de desafios diários em busca da excelência e melhoria contínua.

Se você é um programador apaixonado pelo que faz e gostaria de embarcar na nossa trajetória rumo ao topo do ranking, esta é a oportunidade :)

## A vaga
Você irá atuar como principal desenvolvedor front-end em um software responsável por realizar pagamentos.
O projeto foi iniciado há alguns meses e utiliza modernas tecnologias tanto de back-end quanto de front-end.

#### Contratação
PJ

#### Requisitos
* Sólido conhecimento em Javascript
* Git
* Single Page Applications
* Angular (2 ou 4)
* RESTFul

#### Diferencial
* Habilidade com testes automatizados, principalmente `End-to-End tests`.
* IoT
* Angular Material
* Design Patterns
* Residir na região metropolitana de São Paulo
* Aptidão em outro framework Javascript (além do Angular)
* Aptidão em outra linguagem de programação (além de Javascript)

#### Benefícios
* Horário flexível
* Trabalho remoto
* Salário competitivo
* A equipe de desenvolvimento é pequena, o que significa que seu nível de autonomia e participação nas decisões de código e negócio será elevado

#### Como se candidatar
Envie e-mail com currículo (e, opcionalmente, portifólio) para tobias.sette at semhora com br.

**Comment by gnumoksha** [comment]
Labels: Freela, PJ, Pleno, Remoto - Total

**Comment by fysp11** [comment]
Tem horário de trabalho definido?

**Comment by gnumoksha** [comment]
@fysp11 não.

**Comment by AllanD1** [comment]
Já contratou?

**Comment by jvgm** [comment]
Já contratou?

**Comment by ygorlazaro** [comment]
@gnumoksha Já contratou?³

**Comment by ygorlazaro** [comment]
@gnumoksha Já contratou?³

**Comment by gnumoksha** [comment]
Contratamos. Porém estamos com um novo projeto em Angular e Ionic e estamos recebendo currículos. Aos interessados, seguiam o mesmo procedimento descrito nesta issue.
