### ISSUE TITLE
[REMOTO, São Paulo/SP, Curitiba/PR] Full Stack Dev (React) na NZN

### ISSUE THREAD

**Issue by kavalcante** [frontendbr/vagas#4321]
## Nossa empresa

A NZN tem mais de 20 anos de expertise além de ser um dos principais players para soluções de publicidade e comunicação online. Proprietária das verticais TecMundo, VOXEL, The BRIEF, Mega Curioso, Minha Série, Baixaki e Click Jogos, a NZN veicula campanhas de mídia e de conteúdo de alto impacto para seus clientes entre marcas e agências de publicidade digital, de forma direta e em parceria com redes programáticas. Além disso, possui 23 milhões de usuários únicos mensais, alcançando 1 em cada 5 usuários da internet brasileira.

## Descrição da vaga

Para dar continuidade a esse trabalho, nós buscamos um(a) profissional com capacidade de traduzir a necessidade dos nossos clientes e usuários e entregar valor, se juntando ao nosso time de produto e desenvolvimento e atuando na criação e evolução dos nossos produtos. Se você quer trabalhar conosco e possui capacidade técnica, então queremos te conhecer.

## Local

Exemplo: Remoto ou Escritório, [SP ou CWB].

## O que o(a) Desenvolvedor(a) Full Stack PL faz na NZN?

- Se tornar protagonista das ações da empresa;
- Desenvolver soluções e produtos buscando a melhor eficiência entre qualidade e tempo;
- Interage com todos os departamentos da empresa para mobilizar as ações do time;
- Participa de SQUADs multi-disciplinares.

**O que o(a) novo(a) Desenvolvedor(a) Full Stack PL traz em sua mochila para a NZN?:**
- Mínimo de 3 anos de experiência na área de desenvolvimento;
- Gás para realizar entregas desafiadoras;
- Vontade de aprender e construir grandes produtos;
- Senso de urgência, parceria e boa vontade;
- HTML, JavaScript, CSS, SASS/LESS;
- Grunt/Gulp;
- GIT;
- Frameworks CSS;
- Frameworks JS: Angular, React/React Native, Node.Js/Espress.Js.

**Desejáveis:**
- ASP.Net Core, C# (ou outra linguagem de programação orientada a objetos);
- Técnicas de SEO/AMP.

## Benefícios

- Desconto em restaurantes próximos ao escritório;
- VR (Vale Refeição) ou VA (Vale Alimentação), sem desconto em folha;
- Assistência médica Seguros Unimed apartamento (com extensão para dependentes legais) e com a possibilidade de consultas online durante a pandemia;
- Assistência odontológica Metlife (com extensão para dependentes legais);
- VT (Vale Transporte), desconto de 1% na folha de pagamento;
- Seguro de Vida
- Auxílio creche;

**Diferenciais:**
- Pães, frios, sucrilhos e café à vontade;
- Canjicas, bolos e alguns mimos da Rose e da Dani;
- Frutas fresquinhas todos os dias;
- Política de Aprimoramento (Ajuda de custo em cursos);
- Ajuda de custo com a mensalidade de qualquer academia;
- Happy Friday - mensal com um almoço top;
- NZN Club de descontos;
- Home Office de Março/2020 até ser seguro o retorno para os escritórios;
- Notebook, periféricos e cadeira da empresa podendo ser utilizados de casa durante o período de home office.

## Contratação

CLT a combinar

## Como se candidatar

Link para candidatura: https://nzn.gupy.io/jobs/686798

## Tempo médio de feedbacks

Costumamos enviar feedbacks entre 2 a 15 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
