### ISSUE TITLE
[Rio de Janeiro] Líder Técnico na Robert Half.

### ISSUE THREAD

**Issue by rafassenoff** [frontendbr/vagas#4322]
> Vaga 100% Remota 

## Nossa empresa

Multinacional do segmento de seguros.

## Descrição da vaga
- Sólidos conhecimentos em projetos mobile.
- Evoluir solução de integração entre sistemas no contexto de Apólices de Seguro.
- Background técnico robusto em sistemas.
- Conhecimento técnico em seguros necessários para implantar produtos digitais de acordo com as regras do órgão regulador (SUSEP). 
- Gestão técnica de equipe.
- Experiência com metodologias ágeis (SCRUM, KANBAN, AGILE) e Waterfall (Cascata), trabalhando em projetos híbridos.
- Orientar o time e todos os envolvidos em relação às boas práticas das metodologias ágeis;
- Resolver impedimentos e conflitos.
- Projetos cross altamente estratégicos e relevantes pra empresa.
- Inglês fluente para interface internacional.
- Início imediato

## Local

[100% Remoto]

## Requisitos

**Obrigatórios:**
Sólida experiência com projetos mobile

**Desejáveis:**
- conhecimentos em IOS

**Diferenciais:**
- projetos na área de seguros

## Benefícios

- Plano de saúde - extensível para dependentes (cônjuge e filhos)
- Seguro de vida
- VR de R$ 30/dia

## Contratação

CLT

## Como se candidatar

Por favor envie e-mail para rafael.almeida@roberthalf.com.br com seu CV anexado - enviar no assunto: Vaga Líder Técnico.

#### Alocação

- 100% Remoto

#### Regime
- CLT

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
