### ISSUE TITLE
[Remoto] Angular Frontend Developer [ília Digital]

### ISSUE THREAD

**Issue by thayssa-radmylla** [frontendbr/vagas#4323]
A **ília** digital é uma empresa de tecnologia especializada em simplificar as interações entre pessoas, produtos e serviços por meio de tecnologia e design.

Mais de 100 times dedicados a construir produtos digitais nos permitiram evoluir nosso método interativo e cocriativo. Toda a nossa experiência fez com que construíssemos um modelo próprio de framework adaptado do ágil.

Nosso propósito é tornar o mundo surpreendentemente mais simples, compartilhando uma cultura transformadora!

Estamos no Brasil e atendemos a uma variedade de clientes premium nas Américas e na Europa. Nos concentramos em três principais setores: serviços financeiros, mobilidade e seguros. Cada dia mais conquistamos novos espaços e estamos estabelecendo uma subsidiária também na Espanha.

**Para saber mais acesse: https://ilia.digital ou https://ilia.gupy.io/**

**_O que você precisa para fazer parte do nosso time?_**

• Ter bastante experiência com Angular;
• Conhecimento consolidado com Javascript, CSS3 e HTML 5;
• Conhecimentos consolidado com consumo de APIs;
• Conhecimentos de estado em aplicações SPA;
• Implementação de layout Web/Mobile Responsivo;
• Conhecimentos com práticas de processo de desenvolvimento tais como GitFlow e Code Review.

**_O que pode te diferenciar:_**

• Conhecimento consolidado com implementação de testes;
• Conhecimentos em Testes unitários;
• Experiência em alguma metodologia ágil como Scrum e/ou Kanban e uso do JIRA.

**_Benefícios e Incentivos:_**

- Assistência Médica e Odontológica extensivo aos dependentes;
- Vale Refeição/Alimentação;
- Seguro de vida;
- Programa de Incentivo ao inglês com atividades de mentoria e prática da língua;
- Programa de premiação a indicação de outros profissionais;
- Fóruns Técnicos: Neles o time compartilha práticas, estudos, projetos, ideias etc.
- Grupos de Chapter: Reúnem pessoas com skills similares para compartilhamento de ideias, práticas e experiências. 
- Seu Niver, seu bolo!
- Byod: Alugamos o seu notebook pessoal (valor mensal) ou disponibilizamos uma máquina da empresa (livre escolha).

**_Informações adicionais:_** 

- Contrato de Trabalho CLT - 40h semanais com jornada flexível, sendo executado 100% de forma remota.

**Inscrições:** https://ilia.gupy.io/jobs/602768

**Para tirar dúvidas:** https://www.linkedin.com/in/thayssa-radmylla-61b18a153/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
