### ISSUE TITLE
[Rio de Janeiro] Front-end Developer

### ISSUE THREAD

**Issue by elisajardimpinarodrigues** [frontendbr/vagas#4325]
> Vaga Remota durante a pandemia

## Descrição da vaga

Atuação em um time de alta performance desenvolvendo sistemas.

## Local

Escritório localizado no Rio de Janeiro. Remoto durante a pandemia, híbrido na sequência.

## Requisitos

**Obrigatórios:**

•	C# .Net Core/Framework;
•	Banco de dados SQL Server
•	Entity Framework e Dapper;
•	GIT;
•	Angular;
•	HTML, CSS e Javascript;
•	Formação Superior completa;
•	Perfil proativo, acelerado e sinérgico;

**Desejáveis:**
•	Conhecimentos em DDD;
•	React Native

**Diferenciais:**
•	Inglês

## Contratação

CLT

## Nossa empresa

Empresa de grande porte no segmento jurídico.

## Como se candidatar

Por favor envie um email para elisa.rodrigues@roberthalf.com.br com seu CV anexado.

## Benefícios

Pacote completo de benefícios.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
