### ISSUE TITLE
[Remoto] Front-End React Developer na Fazendinha em Casa

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#4326]
## Descrição da vaga: 
 <p>&nbsp;Fazendinha em Casa (<a href="https://fazendinha.me" target="_blank">https://fazendinha.me</a>) está buscando uma <strong>Pessoa Programadora Front-End React.js + Next.js</strong> para trabalhar com foco em projeto E-Commerce.</p>
<p>🚜~💛🍃&nbsp;</p>
<p>A Fazendinha em Casa aproxima quem produz de quem consome, num modelo colaborativo do produtor à mesa, resgatando o prazer da boa comida, da comida de verdade.</p>
<p>Acreditamos que a forma como nos alimentamos tem profunda influência no mundo a nossa volta: seja na paisagem, na biodiversidade da terra, na economia local ou na nossa cultura e tradições.</p>
<p>Por isso, cultivar um mundo melhor, valorizando o pequeno produtor, a produção local de alimentos, a diversidade, as culturas regionais, o consumo consciente e sustentável, é o que nos move diariamente.</p>
<p></p>
<h6>Processo:</h6>
<ul>
<li>Análise de perfil e experiências através da candidatura para a oportunidade;</li>
<li>Entrevista com Tech Recruiter;</li>
<li>Responder ao mapeamento comportamental;</li>
<li>Resolver e apresentar o Tech Challenge (Live Coding ou Challenge Presentation);</li>
<li>Entrevista de Fit Cultural com os resposáveis na Fazendinha em Casa.&nbsp;&nbsp;</li>
</ul>

## Fazendinha em Casa: 
 <p>A Fazendinha em Casa aproxima quem produz de quem consome, num modelo colaborativo do produtor à mesa, resgatando o prazer da boa comida, da comida de verdade.</p>
<p>Acreditamos que a forma como nos alimentamos tem profunda influência no mundo a nossa volta: seja na paisagem, na biodiversidade da terra, na economia local ou na nossa cultura e tradições.</p><a href='https://coodesh.com/empresas/fazendinha-em-casa'>Veja mais no site</a>

 ## Habilidades: 
 - eCommerce 
- HTML 5 
- Javascript 
- React.js 
- Next.js 
- CSS 3 
- Preact

## Local: 
 100% Remoto

## Requisitos: 
 - 3 ou + anos de experiência trabalhando em projetos front-end usando React.js 
- Sólida experiência em projetos web usando Next.js (SSR) 
- Escreva código bem projetado, testável e eficiente 
- Habituado com otimização de código e melhorias de desempenho em projetos web com foco em SEO 
- Ser habituado no uso de Webpack e ESLint 
- Habituado com Jest 
- Perfil com facilidade em comunicar-se, exploratório e com autonomia 
- Confortável em trabalhar 100% remoto e com equipe geograficamente distribuída 
- Ter disponibilidade de 20 a 30 horas por semana

## Benefícios: 
 - 100% Remoto 
- Horário Flexível

## Como se candidatar:
Candidate-se em: [Front-End React Developer na Fazendinha em Casa](https://coodesh.com/vagas/desenvolvedor-front-end-react-part-time-192228?origin=github&modal=open)

## Tempo médio de feedbacks:
 Costumamos enviar feedbacks em até 48 horas após cada etapa do processo. E-mail para contato em caso de não haver resposta: [contato@coodesh.com](mailto:contato@coodesh.com)

#### Alocação
Remoto

#### Regime
PJ

#### Nível
Pleno

#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
