### ISSUE TITLE
[REMOTO] Front-end Developer Reactjs na Pixter

### ISSUE THREAD

**Issue by D440** [frontendbr/vagas#4327]
## Nossa empresa
A Pixter é uma boutique de software focada em grandes clientes. Com um time de mais de 100 pessoas trabalhando em projetos nos EUA, Portugal e Brasil, a Pixter está guiando a transformação digital de algumas das principais empresas do mundo.

Aqui você fará parte de um time INCRÍVEL, atuando em grandes e desafiadores projetos dos principais clientes do mercado!
Valorizamos a troca de conhecimentos a todo o instante, para que você continue sempre evoluindo!

## Descrição da vaga

Estamos em busca de Reactjs Developer, com experiência sólida em nível Sênior, boa comunicação, desenvoltura em reuniões de planejamento, organização e bom relacionamento interpessoal.

## Local

Remoto

## Requisitos

Experiência mínima: 2+ anos
Domínio em ReactJS e outros frameworks single-page.
HTML: padronização, acessibilidade, mobile patterns.
CSS hierárquico e de fácil manutenção.
Desenvolvimento voltado à componentização.
Domínio em Javascript nativo (ES6>).
Noções básicas de ferramentas para controle de versão.
Experiência com Gulp, Grunt ou Webpack.

**Desejáveis:**
VueJS;
NodeJS;
TDD.

**Diferenciais:**
O que a gente te oferece?
Benefícios flexíveis (Alimentação, Cultura, Lazer, Educação e etc) - você decide com o que gastar, afinal pessoas são diferentes, então seus benefícios também podem ser!
Se precisar, temos um escritório disponível com: salas de reuniões, área de descompressão, cabines de call, 24/7, café, água saborizada e chopp (isso mesmo, chopp todo dia!) pra relaxar;
Contratação no modelo PJ.
Trabalho Home Office

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para danilo.vieira@pixter.com.br com seu CV anexado - enviar no assunto: Vaga Reactjs

## Labels

- Remoto

#### Regime

- PJ

#### Nível

- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
