### ISSUE TITLE
[REMOTE] Senior Frontend Developer at AlphaSights

### ISSUE THREAD

**Issue by andretessmann** [frontendbr/vagas#4328]
## Our company

AlphaSights provides global investment and business professionals with on-demand access to business expertise across all industries and geographies. Through AlphaSights, decision makers from investment management, private equity, management consulting, and corporates connect with a dynamic network of industry experts that provide qualitative and quantitative market insights, industry expertise, and execution support. Leveraging cutting-edge technology and our global team of 1,000+ professionals in nine offices on three continents, we support our clients 24/7 around the globe. AlphaSights regularly ranks as one of the fastest-growing companies in the world.

Learn more at alphasights.com

## Description

Senior Front End Engineer
at AlphaSights

THIS IS A REMOTE POSITION EXCLUSIVELY FOR BRAZILIAN CITIZENS.

At AlphaSights, we search through more than 500 million professionals working in the world today to find the small handful of experts qualified to answer our clients' needs. They use these insights to drive amazing progress within their organizations. Our mission is to provide access to dispersed, hidden, and underutilized knowledge.

We’ve made terrific progress working in this new space, but there is still an incredible amount of work to do. We’ve only just scratched the surface on how we can apply technology to this problem. AlphaSights' Engineers build features across our ecosystem of products and services, both internal and client facing.

**Your role**

As a Senior Frontend Engineer, you will develop innovative interfaces to empower the next generation of our product-suite, on the edge of what is possible with today's browsers. You’ll achieve your goals by developing highly interactive and aesthetically pleasing screens and well architected UI components. Your work is extremely important as it relates to how our clients feel when using our products. You'll work closely with users, engineers, product managers and designers to arrive at the best solution, immediately see the impact of your work, and get feedback directly from users.

**Key responsibilities:**

- Scale our Transcript offerings to serve all clients across the globe
- Build our next-generation Survey system
- Work with a team of full stack and front end engineers and help set the team's front end standards and technical direction
- Build frameworks and reusable React components used by all AlphaSights engineering teams
- Perform ongoing maintenance (bug fixing) and development (features iteration/additions) in our systems
- Integrate our apps with APIs and third party partners
- Perform UI Testing in your deliverables
- Contribute with our growing Open Source efforts

**Main requirements:**

- Have 10+ years of industry experience
- Excellent domain of HTML5, CSS3, JavaScript. TypeScript is a plus
- Experience with task runners, module bundlers, package managers, testing frameworks, linting tools and CSS preprocessors
- Have a good understanding of design systems, componentization, rendering and performance
- Are an expert using React and have previous experience working with Ember.js apps
- Enjoy working in an agile and collaborative environment
- Possess strong architectural experience, acting as Lead developer in big frontend projects
- Are passionate about building elegant, highly performant and modern designs
- Advanced English skills

**Your team**

- You would join a dynamic, multinational, and diverse team who enjoy solving interesting problems in a collaborative environment
- We have self-taught engineers as well as graduates from top Computer Science and Engineering schools
- Your co-workers will include motivated recent graduates as well as experienced industry leaders from companies such as Google and Amazon
- We believe a broad spectrum of experience provides a great perspective on solving problems in new and innovative ways. If your background doesn't check all the boxes above, but you are passionate about front end engineering, we’d still love to hear from you.

**About AlphaSights:**

AlphaSights is a leading global industry research platform. We leverage proprietary knowledge search technology powered by machine learning, natural language processing and data science to connect decision makers to globally distributed knowledge faster than ever before. Professionals at investment firms, consultancies, corporations and non-profits rely on us to connect them seamlessly with knowledgeable domain experts who help enhance their thinking, inform critical decisions and propel their business forward. Founded in 2008, AlphaSights currently employs nearly 1,000 professionals in nine offices around the globe and regularly ranks as one of the fastest-growing companies in the world. AlphaSights has been consistently profitable since 2010, is internally (not VC/PE) funded and pursues a strategy of ambitious long-term growth.

Find out more: http://engineering.alphasights.com

## Local
Anywhere

## Contratação
PJ a combinar

## Como se candidatar
https://grnh.se/1162e96a1us

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 15 dias após cada processo.

## Labels
html5, css3, react, ember.js, cypress, jest, sass, es6+

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
