### ISSUE TITLE
[São Paulo] Front-End Developer na RADAR Profissional

### ISSUE THREAD

**Issue by RADARProfissional** [frontendbr/vagas#433]
## Descrição da vaga
•	Superior completo em Administração, Análise de Sistemas, Ciências da Computação, Tecnologia da Informação, Engenharia da Computação ou áreas afins;
•	Experiência HTML, CSS, JS; REST e Integração de API´s, Webservices, CSS, SASS, LESS, versionamento GIT, Framework Angular I/II, React, Vue.JS, automatizador de tarefas, SEO.

## Local

São Paulo - SP 

## Benefícios
AM, AO, VA, VR, entre outros. 

## Requisitos
Experiência HTML, CSS, JS; REST e Integração de API´s, Webservices, CSS, SASS, LESS, versionamento GIT, Framework Angular I/II, React, Vue.JS, automatizador de tarefas, SEO.

## Contratação
CLT

## Nossa empresa

A Radar Profissional, Consultoria de Recrutamento & Seleção e Terceirização de mão de obra, busca profissionais para atuar em um dos nossos clientes. 

## Como se candidatar

Por favor, envie um email para cristiane@radarprofissional.com.br com seu CV anexado - enviar no assunto: Front-End Developer

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by RADARProfissional** [comment]
fechado

 

 



 

Esta mensagem pode conter informações confidenciais e/ou privilegiadas. Se você não for o destinatário ou a pessoa autorizada a recebê-la, não pode usar, copiar ou divulgar as informações nela contidas ou tomar qualquer ação baseada nelas. Se você recebeu esta mensagem por engano, por favor, avise imediatamente o remetente, e em seguida, apague-a. Comunicações pela Internet não podem ser garantidas quanto à segurança ou inexistência de erros ou de vírus. O remetente, por esta razão, não aceita responsabilidade por qualquer erro ou omissão no contexto da mensagem decorrente da transmissão via Internet. "ECONOMIZE PAPEL - PENSE ANTES DE IMPRIMIR!"

 

De: Felipe Fialho [mailto:notifications@github.com] 
Enviada em: terça-feira, 23 de janeiro de 2018 14:03
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: RADAR Profissional - Consultoria de Recrutamento & Seleção <cristiane@radarprofissional.com.br>; Author <author@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [São Paulo] Front-End Developer na RADAR Profissional (#433)

 

Aberto ainda?
