### ISSUE TITLE
[Remoto] Front-end Developer na GeekHunter

### ISSUE THREAD

**Issue by pedro-lb** [frontendbr/vagas#4331]
## OLÁ, EU SOU A GEEKHUNTER! 👋

Eu nasci com com o propósito de transformar o dia a dia de empresas e a vida das pessoas desenvolvedoras!

A minha plataforma já conta com milhares de candidatos e empresas, que se beneficiam do sistema que mais cresce no Brasil na área de RH tech.

O que me move é poder proporcionar uma ferramenta revolucionária para a contratação de profissionais de tecnologia conectando as melhores mentes desenvolvedoras às melhores empresas.

Eu sou cult, sou nerd, sou gamer, sou transformadora e conectada em um ambiente descontraído permitindo que tenhamos muitos insights e possamos resolver as coisas com criatividade e muito embasamento em dados. Enfim, sou Geek!

Estou em plena evolução e em crescimento constante! Tenho uma série de desafios para escalar minha solução para dezenas de milhares de usuários. Minha plataforma usa especialmente Ruby on Rails, mas tenho a previsão em curto prazo de novos módulos utilizando outras tecnologias, como Python, Node. js, Go etc. Minha infra-estrutura fica na AWS e utilizo tecnologias como Postgres, Ruby on Rails, AngularJS, entre outras. Sou #TeamMetodologiaÁgil, respiro deploy e tenho uma equipe de Geeks maravilhosos. 

Se você quer pertencer a algo grandioso, desafiador e transformar o mundo por meio da tecnologia, vista a camisa roxa e venha ser um Geek você também!

## Descrição da vaga

Nessa posição sua missão principal será realizar melhorias e implementar novas funcionalidades na plataforma da GeekHunter, numa abordagem full-stack com ênfase em Frontend.

Você vai se envolver em atividades de interação da nossa plataforma escritas em Ruby On Rails e Angular. Trabalhará também com tecnologias como React e Python.

Estamos procurando profissionais com senioridade Pleno e Sênior, não se acanhe em nos mandar sua candidatura!

## Local

Remoto

## Requisitos

**Obrigatórios:**

- Experiência em desenvolvimento web full-stack;
- Conhecimentos em AngularJS, React ou equivalente;
- Ser capaz de transformar artefatos de Design em Front-End;
- Saber sobre consumo de APIs REST ou GraphQL;
- Conhecer framework de testes;

**Diferenciais:**

- Pragmatismo no dia-a-dia;
- Focar na raiz dos problemas;
- Gostar de verdade de desafios;
- Se identificar com o valor: cliente sempre em primeiro lugar!
- Gostar de trabalhar em equipe e com bastante autonomia;
- Saber "se virar" no Back-End.

## Benefícios

- Vale-refeição/alimentação de R$ 600,00;
- Plano de saúde (Bradesco Saúde Nacional);
- Assistência odontológica;
- Gympass;
- Vale Padawan de R$130,00 mensais (benefício precioso para você utilizar no seu desenvolvimento educacional ou cultural);
- Um ambiente flexível e descontraído. Queremos que você se sinta motivado(a) para vir trabalhar até mesmo nas segundas de manhã :)

## Contratação

- CLT

## Como se candidatar

Siga os passos no [link da vaga](https://geekhunter.gupy.io/jobs/708406)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 48 horas após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
