### ISSUE TITLE
[Remoto] Fullstack Developer na Nuage IT.

### ISSUE THREAD

**Issue by techrecruiterbsb** [frontendbr/vagas#4333]
## Local

Remoto.

## Requisitos

**Obrigatórios:**
- Curso superior na área de TI;
- Experiência/conhecimento com a plataforma de serviços Cloud/AWS;
- Docker
- APIs REST e SOAP;
- Node.js, PHP, React e SQL;
- DDD e TDD;
- Swagger.

## Contratação

PJ ou CLT a combinar.

## Como se candidatar

Se interessou pela oportunidade e preenche os requisitos? Envie o seu currículo para: techrecruiterbsb@gmail.com

## Labels

- 🏢 Remoto
- 👦 Júnior
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ CLT
- ⚖️ PJ
- 💰 3k-5k
- 💰 5k-10k
- 💰 10k-15k

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
