### ISSUE TITLE
[Remoto] Front-End Developer na Manipulaê

### ISSUE THREAD

**Issue by LeoAltissimo** [frontendbr/vagas#4334]
## Nossa empresa

A [Manipulaê](https://web.manipulae.com.br/) é uma startup que esta revolucionando a forma
como as pessoas consomem medicamentos manipulados.

## Descrição da vaga

Estamos buscando um desenvolvedor front-end de nível <b>Pleno</b> para fazer parte
no nosso time. É necessário ter experiência com:
- React Web/Native
- Redux
- Next.Js
- Gerenciamento de pessoas e projetos

## Local

- 100% remoto
- Horário comercial

## Requisitos

**Obrigatórios:**
- Domínio em ReactJS e React Native
- Domínio em Redux
- Domínio em Next.js
- Ter conhecimento avançado sobre o funcionamento de aplicações Web
- Experiência com gerenciamento e entrega de projetos
- Domínio do git
- Ter conhecimento dos processos e metodologias ágeis
- Experiência com deploy e plublicação de aplicativos 
- Experiência com deploy de aplicações web

**Desejáveis:**
- conhecimentos de banco de dados SQL
- conhecimentos em C# e .NET Core

## Benefícios

- Cartão Flash
- Gympass

## Contratação

PJ a combinar

## Como se candidatar

Por favor preencher o [seguinte formulário](https://forms.office.com/Pages/ResponsePage.aspx?id=Mk8eZ0APlEWm0j7yHrS0izkDlYc_0RVFpo3Gi4XrvIJUNjU2RUlNUVZKNTFaUkJHSzZKRTNJNk9HRy4u)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: tech@manipulae.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
