### ISSUE TITLE
[Remoto] Full Stack Developer na @ProJuris

### ISSUE THREAD

**Issue by vanessaliebl** [frontendbr/vagas#4335]
## Nossa empresa

Descobrimos que a ineficiência é o principal obstáculo dos advogados, portanto, sonhamos em oferecer uma experiência jurídica mais eficiente, segura e descomplicada.
Diariamente são mais de 2.000 departamentos jurídicos e escritórios de advocacia que, somados, somam mais de 20 mil advogados em todo o Brasil que acreditam no poder deste propósito.
Vamos evoluir juntos?

## Descrição da vaga

Buscamos um profissional para compor nosso time de desenvolvimento na ProJuris. Essa vaga é para atuação no ProJuris para Escritórios, software SaaS da ProJuris que tem crescido +70% ao ano e que possui +1700 clientes.

A missão deste profissional será atuar compreendendo a necessidade dos clientes direcionadas pelo time de produtos e desenvolver as soluções para atender a estas necessidades de forma inovadora, ágil e performática.

Se você sonha com cultura de autonomia e alta performance, a hora é agora!

## Local

Presencial Joinville ou Remoto

## Requisitos

**Obrigatórios:**

- Conhecimento sólido em Java, CSS, HTML, JavaScript, SQL, JPA, JSON.

- Conhecimento em Framework Front-End MVC. Preferencialmente Angular, mas também pode ser React ou VueJS.

- Conhecimento em desenvolvimento de API (Rest, gRPC).

- Disposição a aprender rapidamente os itens acima que não tiver conhecimento.

**Desejáveis:**

- Conhecimento em metodologias ágeis (Kanban), Clean Code, TDD, Design Patterns.

- Conhecimento em Micro-serviços, Spring Boot.

**Diferenciais:**

- Conhecimento em arquitetura de Software, AWS, Docker.

## Benefícios

Vale alimentação/refeição sem custo ao colaborador
Plano de saúde Nacional (imediato) e sem custo ao colaborador;
Plano odontológico
PPR anual
Bolsas de Estudos
Seguro de Vida;

**Diferenciais:**

Disponibilidade de frutas;
Happy Hour;
Um ambiente trabalho dinâmico com pessoas engajadas com os valores da empresa;
Horário flexível

## Contratação

CLT

## Como se candidatar

Acesse: https://projuris.gupy.io/jobs/639397?jobBoardSource=gupy_public_page

#### Categoria

- Front-End
- Back-End
- Java
- Angular
- React
- JavaScript
- CSS
- HTML

#### Alocação

- Alocado
- Remoto

#### Regime

- CLT

#### Nível

- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
