### ISSUE TITLE
[REMOTA/ Florianópolis-SC] Front-end Developer na Agriness

### ISSUE THREAD

**Issue by brunobiesczad** [frontendbr/vagas#4339]
> Vaga Remota durante a pandemia

## Nossa empresa

A Agriness tem o propósito de impulsionar a prosperidade no campo e faz isso através de soluções em tecnologia e da aplicação de uma metodologia de aceleração de produtividade pioneira no mundo.
Estamos em constante crescimento e expansão tanto para novas espécies do agronegócio quanto para outros países. Nosso desafio: escalar a Agriness para o mundo. Nós já estamos conseguindo, vem com a gente!

## Descrição da vaga

Como Dev Front-end Pleno você atuará no Squad do produto “S4”, a melhor solução para granjas de suínos, e no dia-a-dia você irá:

- Interagir com os desenvolvedores e integrantes da sua Squad para definição e implementação das soluções planejadas.
- Implementar código seguindo os padrões de qualidade definidos pela área, processos de integração contínua, revisão de código, buscando disseminar boas práticas.
- Desenvolver soluções utilizando tecnologias já adotadas pela empresa como JavaScript, AngularJS, Sass.
- Prezar pela otimização de processos de forma a evitar atividades manuais e repetitivas.

## Local

Remoto ou Escritório, Florianópolis/SC

## Requisitos

**Obrigatórios:**

- Ensino superior em áreas de tecnologia e/ou design.
- Experiência com JavaScript, Angular (preferencialmente AngularJS), Sass.
- Uso de versionamento com GIT.
- Inglês intermediário. 

**Desejáveis:**
- conhecimentos em ruby on rails
- conhecimentos em C#

**Diferenciais:**
- Conhecimento em temas como: clean code, design patterns, design systems, micro frontend e progressive enhancement.
- Experiência com outras bibliotecas (React, Vue).
- Experiência com conteinerização (docker).
- Experiência com pipelines.
- Experiência com testes unitários no frontend.

## Benefícios

- Oportunidade de trabalhar em uma empresa que te desafia, motiva, incentiva e dá liberdade para questionar e contribuir com novas ideias.
- Muita oportunidade de desenvolvimento!
- Ginástica Laboral duas vezes por semana.
- Previdência Privada.
- Aulas de idiomas.
- Folga no dia do aniversário.
- Parcerias de descontos com convênios.
- Possibilidade de trabalho 100% pós pandemia.
- Pacote de benefícios tradicionais: Auxílio home office, VR/VA, Plano de Saúde.

## Contratação
CLT

## Como se candidatar
Por favor envie um e-mail para pertencer@agriness.com com seu CV anexado - enviar no assunto: Vaga Frontend

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
