### ISSUE TITLE
[Remoto] Revisor de Projetos em React na Udacity

### ISSUE THREAD

**Issue by thalescomp** [frontendbr/vagas#434]
## Descrição da vaga

Contribua com o seu conhecimento e expertise para a comunidade de estudantes do [Nanodegree React](https://br.udacity.com/course/react-nanodegree--nd019/) da Udacity, uma das [50 Smartest Companies 2017](https://www.technologyreview.com/lists/companies/2017/intro/#udacity_in). Avalie projetos incríveis, faça revisão de código e coloque o nosso estudante em um próximo nível, contribuindo diretamente em sua educação e habilidades de front-end.

Você receberá via PayPal por cada projeto revisado. Cada revisão dura em torno de 20-40 minutos. O valor da revisão depende da complexidade do projeto, mas varia entre $12-$36 por revisão.

## Local

Remoto

## Benefícios

- Flexibilidade total de horários: avalie projetos quando quiser e puder.

## Requisitos

**Obrigatórios:**
- 1 ano ou mais de experiência com React
- domínio total de componentes, gerenciamento de estado, ciclo de vida, programação declarativa, ECMAScript 6, Ajax, React Router
- domínio de interação com APIs

**Desejáveis:**
- React & Redux

**Diferenciais:**
- React Native
- Facebook SDK
- Firebase
- Flexbox

## Contratação

Via nosso site.

## Nossa empresa

Somos uma universidade online, "feita pelo Vale do Silício", que:
- ensina as habilidades mais requisitadas pelo mercado de tecnologia e inovação
- oferece certificações aprovadas por empregadores
- gera aprendizado por um custo muito menor do que em escolas tradicionais

Oferecemos programas Nanodegree em parceria com gigantes da indústria, como Google, AT&T, Facebook, Amazon, IBM, Mercedes-Benz, Uber ATG, Vive, etc. Os cursos são projetados para que os profissionais se tornem desenvolvedores Web, analistas de dados, desenvolvedores mobile, etc. Nossos alunos adquirirem competências reais através de uma série de cursos on-line e projetos práticos.

## Como se candidatar

Por favor, envie um email para novosrevisores@udacity.com com o link do seu LinkedIn e GitHub - enviar no assunto: Vaga Revisor de Projetos React

**Comment by diogomoretti** [comment]
@thalescomp labels?

**Comment by thalescomp** [comment]
@diogomoretti , acho que o @LFeh adicionou as principais mesmo, obrigado!. Apenas retirar o PJ, pois o pagamento das revisões é via pessoa física no PayPal.

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
