### ISSUE TITLE
[São Paulo] Front End React Js na [Projeto 22]

### ISSUE THREAD

**Issue by ketlinP22** [frontendbr/vagas#4340]
Requisitos: Alguns dos frameworks (React, Angular 2+) HTML, CSS, experiência com compiladores de estilo (Sass ou Less), consumo de APIs, manipulação de JSON, ter atuado em projetos ágeis, auto-organização é fundamental, JavaScript, versionamento de códigos .git, vivência em metodologias ágeis.

Contratação: CLT e PJ

100% Remoto

**Comment by gabrielsouza1** [comment]
Qual é o e-mail para se candidatar?

**Comment by HenriqueACF** [comment]
qual o email?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by ketlinP22** [comment]
Vaga aberta

Em dom, 25 de abr de 2021 21:37, Felipe Fialho ***@***.***>
escreveu:

**Comment by SaMatheus** [comment]
@ketlinP22 como agente se candidata?

**Comment by ketlinP22** [comment]
Bom dia, Pessoal!

Segue email para mais informações sobre a vaga.
***@***.***

Abs,



Em seg, 26 de abr de 2021 08:08, Matheus Fernandes de Sá <
***@***.***> escreveu:

**Comment by SaMatheus** [comment]
Apareceu assim:
![image](https://user-images.githubusercontent.com/38141771/116085062-d1ba5980-a674-11eb-98f5-6668cfabd66a.png)

**Comment by SaMatheus** [comment]
@ketlinP22 
Não foi, o e-mail aparece assim:
![image](https://user-images.githubusercontent.com/38141771/116085293-0dedba00-a675-11eb-8f7d-af16542d7c24.png)

**Comment by ketlinP22** [comment]
Matheus, envia o seu número para contato.?

Em seg, 26 de abr de 2021 09:52, Matheus Fernandes de Sá <
***@***.***> escreveu:

**Comment by SaMatheus** [comment]
@ketlinP22  Claro :)

11 985374474 - Pode mandar msg no whatsapp se preferir
