### ISSUE TITLE
[São Paulo] Front-end Developer React na Projeto 22

### ISSUE THREAD

**Issue by ketlinP22** [frontendbr/vagas#4341]
"Front-End Developer" 

==================================================
100% remoto
==================================================
-->
> Vaga Remota durante a pandemia

## Projeto 22

Oportunidade para atuar em uma empresa de grande porte.
## Descrição da vaga

Requisitos: Alguns dos frameworks (React, Angular 2+) HTML, CSS, experiência com compiladores de estilo (Sass ou Less), consumo de APIs, manipulação de JSON, ter atuado em projetos ágeis, auto-organização é fundamental, JavaScript, versionamento de códigos .git, vivência em metodologias ágeis.

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

Interessados, enviar cv para: ketlin.sales@projeto22.com.br

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
