### ISSUE TITLE
[São Paulo/SP] Front-end React/React Native na ITeam

### ISSUE THREAD

**Issue by VivianeRHTI** [frontendbr/vagas#4344]
## Descrição da vaga

Atuará em projetos de desenvolvimento de e-commerce e outras melhorias.

## Local

São Paulo/SP – Lapa (100%Presencial) - Horário comercial

## Requisitos

Experiência em projetos com React.js e React Native.
Obs. Imprescindível experiência em React Native.

## Contratação

Tempo indeterminado
PJ ou a combinar

## Nossa empresa

Há mais de 15 anos presente no mercado, a ITeam oferece o comprometimento com o cliente.
Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 
O relacionamento da ITeam é baseado no amplo comprometimento com os valores e objetivos dos nossos Clientes, fornecendo soluções e serviços de TI que contribuam para a realização de seus objetivos.

## Como se candidatar

Envie um e-mail para viviane.pereira@iteam.inf.br com seu currículo atualizado e pretensão de valor - enviar no assunto: Vaga no Github React/React Native -10294

## Labels

- 🏢 Horário comercial
- 🏢 Presencial
- 👴  Sênior
- ⚖️ A-Combinar
- ⚖️ PJ ou a combinar

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
