### ISSUE TITLE
[Home-Office] Front-end React Developer na ITeam

### ISSUE THREAD

**Issue by VivianeRHTI** [frontendbr/vagas#4345]
## Descrição da vaga

Front-end de sistemas e aplicações web e mobile, utilizando tecnologias atuais e atendendo requisitos de responsividade e acessibilidade na web, implementando códigos que sejam escaláveis, fáceis de manter, eficientes e elegantes;
Definir boas práticas, mantendo-se atualizado nas novas tecnologias de frontend e capacitando outros desenvolvedores;
Participar de projetos de desenvolvimento de novos softwares, avaliando os protótipos entregues pelo designer, planejando e implementando a estrutura e componentes da interface, utilizando para isso o framework de javascript React;
Participar de projetos de customização de softwares já existentes utilizando um framework interno, AngularJS ou React;
Apoiar e orientar a elaboração de rotinas automatizadas de testes, utilizando-se de ferramentas e padrões para os testes necessários.

## Local

Home-Office (100%)

## Requisitos

Experiência com JavaScript e no framework React.Js e componentização e ES6+;
Conhecimento em gerenciadores de estados, incluindo Redux e seus padrões de arquitetura; HTML e CSS.
Experiência em equipes dinâmicas e metodologias de desenvolvimento ágeis;

## Contratação

Tempo indeterminado
Somente CLT Full

## Nossa empresa

Há mais de 15 anos presente no mercado, a ITeam oferece o comprometimento com o cliente.
Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 
O relacionamento da ITeam é baseado no amplo comprometimento com os valores e objetivos dos nossos Clientes, fornecendo soluções e serviços de TI que contribuam para a realização de seus objetivos.

## Como se candidatar

Envie um e-mail para viviane.pereira@iteam.inf.br com seu currículo atualizado e pretensão de valor - enviar no assunto: Vaga no Github Front-End React - 10498

## Labels

- 🏢 Horário comercial
- 🏢 Remoto
- 👴  Sênior
- ⚖️ A-Combinar
- ⚖️ CLT

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
