### ISSUE TITLE
[Recife/PE ou Home-Office] Front-end React Developer na ITeam

### ISSUE THREAD

**Issue by VivianeRHTI** [frontendbr/vagas#4346]
## Descrição da vaga

Projetar, criar e configurar aplicativos para atender aos requisitos de processos de negócios e aplicativos..

## Local

Recife/PE ou Home-Office (100%)

## Requisitos

Experiência com Front-End utilizando React.js.

## Contratação

Contrato de 13 meses
CLT Full ou PJ (Somente com empresa aberta)

## Nossa empresa

Há mais de 15 anos presente no mercado, a ITeam oferece o comprometimento com o cliente.
Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 
O relacionamento da ITeam é baseado no amplo comprometimento com os valores e objetivos dos nossos Clientes, fornecendo soluções e serviços de TI que contribuam para a realização de seus objetivos.

## Como se candidatar

Envie um e-mail para viviane.pereira@iteam.inf.br com seu currículo atualizado e pretensão de valor - enviar no assunto: Vaga no Github Front-End React Recife/Home - 10641

## Labels

- 🏢 Horário comercial
- 🏢 Presencial ou Home-Office
- 👴  Sênior
- ⚖️ A-Combinar
- ⚖️ CLT

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
