### ISSUE TITLE
[Home/Office e Barueri-SP] Front-end React Developer na ITeam

### ISSUE THREAD

**Issue by VivianeRHTI** [frontendbr/vagas#4348]
## Descrição da vaga

Desenvolvimento de sistemas Web e e-commerce.

## Local

Home-Office devido a pandemia e posteriormente atuação em Barueri/SP.

## Requisitos

Experiência com React (JSX), Javascript (ES6), Sass, Less, TypeScript;
Aplicações Web Mobile / Webview (Android e IOS); GIT;
Experiência em consumo de API (RESTfull);
Produção de telas e recortes HTML, Responsive Web Design;
Pacote Adobe (Photoshop, XD, Illustrator);
Experiência em projetos Web (Hotsites, Intranets, E-commerces e Integradores);

## Contratação

Tempo indeterminado
PJ ou a combinar

## Nossa empresa

Há mais de 15 anos presente no mercado, a ITeam oferece o comprometimento com o cliente.
Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 
O relacionamento da ITeam é baseado no amplo comprometimento com os valores e objetivos dos nossos Clientes, fornecendo soluções e serviços de TI que contribuam para a realização de seus objetivos.

## Como se candidatar

Envie um e-mail para viviane.pereira@iteam.inf.br com seu currículo atualizado e pretensão de valor - enviar no assunto: Vaga no Github Front-End React Home/Barueri - 11036 

## Labels

- 🏢 Horário comercial
- 🏢 Home-Office/Presencial pós pandemia
- 👴  Sênior
- ⚖️ A-Combinar
- ⚖️ PJ ou a combinar

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
