### ISSUE TITLE
[Remoto / Belo Horizonte] Front-end Developer na Bertholdo Consultoria

### ISSUE THREAD

**Issue by heyralfs** [frontendbr/vagas#4349]
## Nossa empresa

A Bertholdo é uma empresa que atua no mercado de tecnologia da informação desde 1999. Nosso diferencial é oferecer soluções completas e inovadoras aos nossos clientes, sempre investindo na capacidade intelectual de nossos colaboradores.

Aqui, você passará a maior parte do seu tempo, por isso investimos em um ambiente agradável e descontraído, onde nosso principal foco é o trabalho em equipe.

## Descrição da vaga

Estamos à procura de um Desenvolvedor Front-end para fazer parte do nosso time. O profissional atuará no desenvolvimento de interfaces de lojas virtuais, portais, aplicativos mobile e sistemas web.

Juntando-se a nós, você vai fazer parte de uma das melhores equipes de desenvolvimento e-commerce do Brasil.

Procuramos por pessoas que:
•	Sabem e gostam de trabalhar em equipe, interagir com outros times e estão sempre dispostas a ajudar;
•	Demonstram iniciativa e interesse em resolver problemas e propor soluções;
•	Responsabilizam-se pelos prazos e resultados planejados e detestam pessoas que dão desculpas;
•	Superam obstáculos e agem com senso de urgência em situações de maior impacto;
•	Mantém o ambiente, documentos e informações organizadas visando a otimização de tempo e recursos;
•	Adorem internet, e-commerce e marketing digital;
•	Sejam leitores do nosso blog.

As principais tarefas são:
• Atuar com desenvolvimento Front-end, construção de interface de lojas virtuais, portais, aplicativos mobile e sistemas Web.

## Local

Remoto ou Escritório (Belo Horizonte, MG) - preferência do candidato*
*durante a pandemia, apenas REMOTO

## Requisitos

**Obrigatórios:**
Conhecimento específico desejado:
• Domínio em HTML, CSS, Abobe Illustrator e Photoshop;
• Experiência com Bootstrap e/ou SASS/LESS;
• Experiência em WordPress (customização de temas);

**Desejáveis:**
• Conhecimento em e-commerce: Magento ou WordPress + WooCommerce;
• Conhecimento intermediário em lógica de programação;
•Conhecimento intermediário em linguagem de programação Javascript.

## Benefícios
• Ajuda de Custo para transporte e alimentação;
• Plano de saúde Unimed;
• No dress code (pode trabalhar de bermuda, camiseta, chinelo, etc. Afinal, o que importa é seu resultado!)
• Participação nos Lucros e Resultados
• Horário flexível

## Contratação
Remuneração Fixa; CLT
• Contratação: Devido a pandemia, o trabalho poderá ser remoto ou presencial, de acordo com a disponibilidade e preferência do candidato;
• Horário: 8:48 horas diárias

## Como se candidatar
Através do link:
https://jobs.solides.com/bertholdo/vaga/27100#

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by honnyevol** [comment]
Obrigado pela oportunidade porem não consegui preencher o cadastro que boqueou diversas vezes até chegar ao ponto que desisti. Convido os senhores (as) da empresa a conhecer meu currículo e caso seja do agrado estou a disposição.
[CURRICULUM VITAE-utimo.docx](https://github.com/frontendbr/vagas/files/6085679/CURRICULUM.VITAE-utimo.docx)

**Comment by honnyevol** [comment]
Olá seja bemvindo(a)!

           Estou interessado  na vaga aberta no gitHub 
Sou programador junior (javascript , html , css, bootstrap , lógica de programação, portugol, c, github e muito mais).
Inglês , português e espanhol (todos avançado).
            Estou disposto a conhecer a proposta da empresa com a mente aberta e oferecer o meu melhor .
Muito obrigado!!!

**Comment by heyralfs** [comment]
> Olá seja bemvindo(a)!
> 
> ```
>        Estou interessado  na vaga aberta no gitHub 
> ```
> 
> Sou programador junior (javascript , html , css, bootstrap , lógica de programação, portugol, c, github e muito mais).
> Inglês , português e espanhol (todos avançado).
> Estou disposto a conhecer a proposta da empresa com a mente aberta e oferecer o meu melhor .
> Muito obrigado!!!

@honnyevol sinto muito pelo ocorrido! Esta issue foi apenas para ajudar na divulgação da vaga, porém não sou responsável pelo recrutamento.
O processo seletivo foi encerrado, mas acompanhe as próximas oportunidades através da página https://www.bertholdo.com.br/trabalhe-conosco/ ou pelo Instagram https://instagram.com/bertholdo.ecommerce.

Forte abraço!
