### ISSUE TITLE
[Remoto] Live Coding em React na Udacity

### ISSUE THREAD

**Issue by thalescomp** [frontendbr/vagas#435]
## Descrição da vaga

Contribua com o seu conhecimento e expertise para a comunidade de estudantes do [Nanodegree React](https://br.udacity.com/course/react-nanodegree--nd019/) da Udacity, uma das [50 Smartest Companies 2017](https://www.technologyreview.com/lists/companies/2017/intro/#udacity_in). Elabore [Live Codings](https://en.wikipedia.org/wiki/Live_coding) com tutoriais, dicas, etc, que visam incrementar o currículo dos alunos no que tange React. Aborde melhores práticas sobre estruturação de código, bibliotecas, exemplos de aplicações em React e afins. Alguns exemplos, um live coding  "Integrando React com Bootstrap", "React e Oauth2", "React & WebGL", etc. Tutoriais que no dia-a-dia eles certamente vão precisar durante seus trabalhos como desenvolvedores/engenheiros front-end.

Receba por cada Living Code realizado, girando em torno de 300 a 700 reais. Valor a combinar.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 1 ano ou mais de experiência com React
- domínio total de componentes, gerenciamento de estado, ciclo de vida, programação declarativa, ECMAScript 6, Ajax, React Router
- domínio de interação com APIs
- React & Redux

**Desejáveis:**
- React Native
- Facebook SDK
- Firebase
- Flexbox

**Diferenciais:**
- WebGL
- ReactVR
- GraphQL

## Nossa empresa

Somos uma universidade online, "feita pelo Vale do Silício", que:
- ensina as habilidades mais requisitadas pelo mercado de tecnologia e inovação
- oferece certificações aprovadas por empregadores
- gera aprendizado por um custo muito menor do que em escolas tradicionais

Oferecemos programas Nanodegree em parceria com gigantes da indústria, como Google, AT&T, Facebook, Amazon, IBM, Mercedes-Benz, Uber ATG, Vive, etc. Os cursos são projetados para que os profissionais se tornem desenvolvedores Web, analistas de dados, desenvolvedores mobile, etc. Nossos alunos adquirirem competências reais através de uma série de cursos on-line e projetos práticos.

## Como se candidatar

Por favor, envie um email para brasil@udacity.com com o link do seu LinkedIn e GitHub - enviar no assunto: Vaga Living Coding em React

**Comment by diogomoretti** [comment]
@thalescomp labels?

**Comment by thalescomp** [comment]
@diogomoretti , acho que o @LFeh adicionou as principais mesmo. O mesmo do comentário na vaga de revisões, retirar o PJ. Obrigado! :+1:
