### ISSUE TITLE
[Remoto] FullStack Developer na Cout

### ISSUE THREAD

**Issue by FigueiraIure** [frontendbr/vagas#4350]
## A Cout

Somos uma HR Startup focada em Gestão de Pessoas e Processos Empresariais e nosso primeiro produto é uma ferramenta de gerenciamento de Escalas e Jornadas de trabalho.

## Descrição da vaga

Inicialmente, buscamos um FullStack Developer com foco em Vue.js/Nuxt.js, para atuar em nossa stack atual que é Vue/Laravel. Mas, também estamos abertos para receber candidatos que sejam Front-End (Vue.js/Nuxt.js) ou Back-End (Laravel).

## Local

Remoto

## Requisitos

**Obrigatórios:**

Front-End
- Experiência com HTML, CSS e JavaScript (Vue.js / Nuxt.js)

Back-End
- Experiência com Laravel
- Experiência com MySQL

**Desejáveis:**
- Experiência em projetos remotos e colaborativos, utilizando o GitLab
- Conhecimento em Design Pattern
- Conhecimento em Vue.js

**Diferenciais:**
- Projetos opensource no github

## Contratação

- PJ > R$ 2400 para 20h/semanais ou;
- PJ > R$ 5800 para 40h/semanais com possibilidade de Stock Option e/ou variáveis por resultado;

## Como se candidatar

Enviar um email para danielcouto@cout.app com o assunto "Vaga [FullStack]" contando um pouco de suas habilidades, sua experiência e como pode somar com nosso time.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dia após cada processo.
Contato em caso de não haver resposta: +55 (62) 991725365 (Daniel)

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
