### ISSUE TITLE
[Fortaleza-CE] Senior React.js Developer na Mondrian Tecnologia

### ISSUE THREAD

**Issue by mondriantecnologia** [frontendbr/vagas#4351]
## Descrição da vaga

Liderar o desenvolvimento front-end (Web/Mobile) utilizando React;
Utilizar GitFlow para versionamento de código;
Padronização de código;
Auxílio nas estratégias e tomadas de decisão do time para evolução do produto;

## Local

Rua João Carvalho, 800, Aldeota - Fortaleza, CE

## Benefícios

- Plano de saúde
- VR
- VT

## Requisitos

**Obrigatórios:**
- 4 anos de experiência com desenvolvimento com React

**Diferenciais:**
- Next.js

## Contratação

CLT ou PJ a combinar

## Nossa empresa

A Mondrian Tecnologia atua como desenvolvedora de sistemas proprietários e consultoria em banco de dados PostgreSQL a mais de 10 anos.

## Como se candidatar

Por favor envie um email para contato@mondriantecnologia.com com seu CV anexado - enviar no assunto: Senior React.js

## Labels

- 🏢 Presencial
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ CLT
- ⚖️ PJ
- 💰 7k-10k

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
