### ISSUE TITLE
[Araçatuba][Remoto][ReactJS] Front-End Developer no Grupo Acert

### ISSUE THREAD

**Issue by GustavoAlbunio** [frontendbr/vagas#4352]
## Descrição da vaga

**Requisitos necessários:**
- JavaScript / ES6
- ReactJS / Redux 
- Webpack
- CSS
- APIs REST

**Hábito com as metodologias ágeis
Desejo de aprender**

**Será um diferencial já conhecer:** 
- Typescript
- Ferramentas de teste: Jest, Enzyme, React-Testing-Library, Cypress
- react-final-form
- Material UI

## Contratação

PJ a combinar

## Remuneração

De R$3000,00 a R$4000,00

## Como se candidatar

Envie seu **CV** e **Github** para o e-mail: trabalhe.conosco@grupoacert.com.br com o assunto FRONT-END

## Labels

- PJ
- Remoto
- Junior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
