### ISSUE TITLE
[Remoto] Senior Front-End Developer na Arbeit 

### ISSUE THREAD

**Issue by BarbaraEv0lu1r** [frontendbr/vagas#4355]
NOSSA EMPRESA

When two collection agency owners became frustrated over phone dialers and automated calling systems that didn’t grow their business—they built their own. The result was Arbeit Software, a platform dedicated to helping agents call with confidence.

Today, Arbeit is growing fast and finding new ways to support a healthy, compliant, and productive collections industry including TCPA-compliance solutions.

DESCRIÇÃO DA VAGA

Estamos à procura de um Desenvolvedor Front-End Sênior para construir e implementar interfaces de usuário atraentes e funcionais, com usabilidade aprimorada e foco na experiência do usuário. Você trabalhará com outros Designers de IU, Desenvolvedores, Gerentes de Produto e Scrum Masters ao longo do ciclo de vida de desenvolvimento de software.

Responsabilidades

Atuar em equipe com desenvolvedores e designers de IU para implementar o front-end
Produzir código limpo e eficiente com base nas especificações
Auxiliar na criação de especificações
Resolver problemas, depurar e atualizar o código existente
Recomendar e executar melhorias
Criar documentação técnica para referência e relatórios
Criar e colaborar em novos padrões de desenvolvimento baseados em boas práticas
Apoie a equipe compartilhando conhecimento e promovendo revisões técnicas

REQUISITOS

Obrigatórios:

5+ anos como desenvolvedor front-end
Inglês avançado
Familiaridade com metodologias de desenvolvimento Ágil
Experiência com design e desenvolvimento de software em um ambiente orientado a testes
Conhecimento de linguagens de codificação e frameworks / sistemas (por exemplo, React, Git, JavaScript )
Experiência com bancos de dados e frameworks Object-Relational Mapping (ORM)

Diferencial:
Conhecimento em C#

BENEFÍCIOS
Seguro saúde e odontológico pago
Cronograma de PTO generoso 
17 feriados pagos
Participação nos lucros qualificada após o ano 1
Dias de trabalho reduzidos, ainda mais curtos na sexta-feira

CONTRATAÇÃO
CLT

Como se candidatar

Por favor envie um email para barbara.borges@evoluirdesenvolvimento.com.br com seu CV anexado - enviar no assunto: Vaga Arbeit ou me chame no linkedin https://www.linkedin.com/in/b%C3%A1rbara-vieira-borges-238b3323/

Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.
E-mail para contato em caso de não haver resposta: barbara.borges@evoluirdesenvolvimento.com.br

Alocação
- Remoto

Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
