### ISSUE TITLE
[São Leopoldo] Front-end Developer na V4 Company

### ISSUE THREAD

**Issue by mjuchemf** [frontendbr/vagas#4357]
> Vaga Remota durante a pandemia

## Nossa empresa

Na V4 somos guiados por atitudes claras e transparentes que nos permitem fazer o máximo para os nossos clientes, criando soluções que gerem resultados para todos é o nosso propósito. Trabalhamos de modo colaborativo, o que significa que confiamos nas pessoas que estão do nosso lado. Aqui ninguém é empregado de ninguém! Todos são investidores. Clientes investem dinheiro para terem resultado, e as pessoas aqui investem seu tempo para ajudar o negócio a crescer. Juntos, seremos cada vez maiores e melhores! O ambiente é o mais horizontal possível, possibilitando a sua autonomia para tomar as melhores decisões para as atividades pelas quais você é responsável!
Antes dos processos, produtos, serviços, mesas e cadeiras; uma empresa é a união de pessoas em busca de um propósito. Em função disso temos um grande foco em quem faz parte do nosso negócio. Por isso, se você estiver aqui e se destacar de maneira meritocrática no que você faz e estar alinhado com nossa cultura, será convidado a ser sócio da empresa. Afinal, existe maior reconhecimento que uma empresa pode fazer para quem se dedica e se destaca? Acreditamos que a V4 precisa ser um meio para que a pessoa consiga atingir seus objetivos profissionais, para isto proporcionamos um ambiente aberto e alinhando com as expectativas de cada um, para que a pessoa trabalhe com gosto e motivado!

## Descrição da vaga

- Desenvolvimento em NodeJS.
- Encontrar novas técnicas e tecnologias, com o foco de escalabilidade.
- Expandir seus conhecimentos através da utilização de novas ferramentas, tecnologias, bibliotecas, …
- Necessidade de aprender rápido, e se adaptar às mudanças de situações e prioridades.
- Definição, junto a equipe, de Key Results (conversões e micro-conversões) para acompanhamento de resultados e da utilização do software pela base.

## Requisitos

**Obrigatórios:**
- Desenvolvimento em Reactjs e React Native.
- Encontrar novas técnicas e tecnologias, com o foco de escalabilidade.
- Expandir seus conhecimentos através da utilização de novas ferramentas, tecnologias, bibliotecas, …
- Necessidade de aprender rápido, e se adaptar às mudanças de situações e prioridades.
- Definição, junto a equipe, de Key Results (conversões e micro-conversões) para acompanhamento de resultados e da utilização do software pela base.

**Desejáveis:**
- Inglês (reading and listening)

**Diferenciais:**
- Estatística aplicada a Marketing

**Diferenciais:**
- Horários flexíveis
- Oportunidade de se tornar sócio da empresa

## Contratação

PJ de R$ 5.000,00 à R$10.000,00

## Como se candidatar

Por favor, se cadastrar em https://v4company.gupy.io/jobs/716381?jobBoardSource=githubFront

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
