### ISSUE TITLE
[SÃO PAULO] Front-end Developer (Teste AB - CRO) PL Math Marketing

### ISSUE THREAD

**Issue by bruweirich** [frontendbr/vagas#4359]
A Math Marketing é uma consultoria de inteligência de dados para marketing.
Nosso foco é aumentar a capacidade de vender, usando dados e fatos para otimizar os investimentos de marketing (desde mídia até recursos humanos). Para isso atuamos da estratégia até a Otimização por AI, passando por Analytics, Automação e Compliance de Dados.

 **Suas principais atividades serão**:

Realizar análises de comportamento de navegação de usuários em canais digitais
Identificar oportunidades de otimizações na experiência dos usuários
Interagir com as área de negócio e tecnologia
Desenvolver testes AB e MVT nas ferramentas Google Optimize e Oracle Maxymiser
Realizar as configurações de público alvo e métricas de sucesso dos testes
Analisar os resultados dos testes
 

**O que você precisa ter:**

Disponibilidade de alocação no cliente (o profissional ficará junto ao time Math já alocado no cliente)
Conhecimento sólido em Javascript, HTML e CSS
Conhecimento sólido em Teste AB e MVT
Experiência em Google Optimize ou Oracle Maxymiser
Conhecimento em tagueamento
 

**Será legal se você tiver:**

Angular
Google Analytics
BigQuery
Google Tag Manager

**Aqui você vai encontrar:** 

Dinamismo e abertura para troca de ideias e experiências. 
Oportunidade de crescer profissionalmente. 
Cultura plural e aberta. 
Onboarding e colegas muito receptivos. 
Ótima infraestrutura remota de trabalho. 
Ambientes físicos e virtual dinâmicos e descontraídos. 
Cultura colaborativa, de gestão horizontal e incentivo à troca de feedbacks. 
Work Life balance: programa de bem-estar físico, mental e financeiro, plataforma de cursos, meetups para desenvolvimento de hard e soft skills, happy hours constantes entre o time.
 
**Nível: Pleno**

 

 Enviar currículo para p&c@wikeen.com.br com o assunto Front-end (Teste AB) github

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
