### ISSUE TITLE
[São Paulo] Front-End Developer na 99jobs

### ISSUE THREAD

**Issue by andressamelo** [frontendbr/vagas#436]
## Descrição da vaga

Você vai trabalhar em conjunto com os nossos times de produto e tecnologia, desenvolvendo a plataforma 99jobs.com através de novos produtos, features e páginas. Mais do que "construir", você vai pensar, prospectar e validar uma série de inovações conosco!

## Local

Alocado no escritório na região da Faria Lima, porém com possibilidade de home-office alguns dias.

## Benefícios

- Vale Transporte
- Seguro de Vida
- Assist. Médica
- Almoço na empresa
- Horário Flexível
- Bicicletário
- 13ª Bolsa Auxílio

## Requisitos

HTML5 
CSS3, SASS 
Orientação a objetos 
Ter uma ótima organização de código e semântica 
Javascript, jQuery, CoffeeScript 
Desenvolvimento de páginas responsivas 
Ajax 
Json 
Boas práticas de SEO 
Experiência com controle de versão, preferencialmente Git 
Atenção aos detalhes visuais

**Desejáveis:**

Algum frameworks Javascript (AngularJS, BackboneJS, EmberJS ou KnockoutJS) 
Bower, Grunt etc 
Ter trabalhado com Rails 
Bootstrap 
WordPress 
Photoshop e/ou illustrator 
Usabilidade (UX) 
TDD 
Conhecimentos em métodos Agile

## Contratação

CLT ou PJ (a combinar)

## Nossa empresa

A 99jobs tem um ambiente de trabalho dinâmico e descontraído, como boa startup focada em tecnologia que é! 
Nosso escritório fica em uma casa no Jardim Paulista em São Paulo. Nós trabalhamos com um modelo horizontal de gestão (não temos chefes) e você pode trabalhar em mesas coletivas, sofás, poltronas, varanda ou no lugar que achar mais confortável.

## Como se candidatar

[Clique aqui para aplicar ](https://www.99jobs.com/99jobs/jobs/10879-desenvolvedor-front-end) ou envie um email para andressa.melo@99jobs.com para mais detalhes.

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by andressamelo** [comment]
@LFeh Preenchemos a vaga. A pessoa contratada encontrou a vaga no próprio site! Obrigada

**Comment by LFeh** [comment]
Da hora!
