### ISSUE TITLE
[Campinas ou Remoto] Senior React Developer na HDN.Digital

### ISSUE THREAD

**Issue by marcelocpinheiro** [frontendbr/vagas#4360]
## Nossa empresa

Somos um estúdio de transformação digital que está no mercado há 12 anos, e estamos em franca expansão.

Temos um time especializado em entregar soluções de tecnologia que agregam valor, otimizam o tempo e trazem inovação ao seu modo de trabalho. Nossa missão é colaborar, disseminar o conhecimento e a cultura de empresas através de novas tecnologias e processos ágeis.

Há mais de 10 anos temos a experiência em desenvolvimento de softwares e soluções digitais.

Faz parte do DNA da HDN entender a dor dos nossos clientes, se colocar no lugar dele e oferecer as soluções que melhor se adequam às específicas necessidades.

Toda mudança e transformação digital requer um primeiro passo, e estamos preparados para caminhar lado a lado.

Prezamos pelo desenvolvimento do colaborador tanto a nível técnico quanto a nível pessoal, temos um ambiente leve e divertido, queremos que você tenha voz e seja ouvido, tenha participação nos processos da empresa e encontre um ambiente amigável para crescer profissionalmente e construir sua carreira conosco!

## Descrição da vaga

Você vai atuar junto ao nosso time de engenheiros front-end para arquitetar e implementar soluções para diversos clientes (nacionais e internacionais) em projetos ágeis e desruptivos, com impacto direto no negócio. Queremos um profissional comunicativo, que ame codar e tenha responsabilidade sobre suas entregas.

## Local

Remoto ou Escritório, Campinas - Nova Campinas

## Requisitos

**Obrigatórios:**
- 5+ anos de experiência com Javascript
- 2+ anos de experiência com react

**Desejáveis:**
- Experiência com React Native
- Experiência com CI/CD
- Experiência com Testes unitários com Jest
- Experiência com testes de integração

**Diferenciais:**
- Node.js
- Inglês Avançado

## Benefícios

- 30 dias de férias remuneradas
- Gympass

**Diferenciais:**
- Sala de jogos
- Acesso aos cursos internos disponibilizados pela empresa

## Contratação

Cooperativa, a combinar

## Como se candidatar

Por favor envie um email para marcelo.pinheiro@hdnit.com.br com seu CV anexado - enviar no assunto: Vaga React Sênior

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: contato@hdnit.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- Cooperativa

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
