### ISSUE TITLE
[São Paulo/Remoto] Front-end React na Maitha Tech

### ISSUE THREAD

**Issue by Patricia-MaithaTech** [frontendbr/vagas#4361]
## Nossa empresa

Somos uma empresa digital, com experiência em tecnologia e inspirada pela inovação. Atuamos na aceleração, transformação e ideação de novas soluções e times de alta performance.
Atuamos tanto na construção de times de tecnologia, quanto em frentes de negócio, na co-criação de produtos, levantamento de requisitos, resolução de problemas, entre outros.

## Descrição da vaga

As Squads são responsáveis por 15 produtos, com destaque para a Venda Assistida, Marketplace, Pagamento, Portal de Fornecedores e Portal de Serviços e a oportunidade é para integrar o time (será avaliado em qual squad mais se identifica) para atuar no desenvolvimento dos produtos.

## Local

São Paulo e/ou Remoto

## Requisitos

**Obrigatórios:**
- React
- Javascript
- HTML5
- CSS
- Testes Automatizados

**Disposto a se aprofundar em:**
- Arquitetura (Webpack, Babel, ESLint, stylelint, Micro Frontend)
- RESTful
- GraphQL
- WebSocket

## Contratação

PJ a combinar

## Como se candidatar

Contato via Linkedin: https://www.linkedin.com/in/patriciapcarrillo/ ou envie um e-mail para patricia@maitha.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor Front End React

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by Erlingsjunior** [comment]
Adicionei a Recrutadora no LinkedIn, gostaria de me candidatar.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
