### ISSUE TITLE
[Lisboa/Remoto] Front-end Developer na Integer Consulting

### ISSUE THREAD

**Issue by AnaMargaridaAlmeida** [frontendbr/vagas#4362]
![image](https://user-images.githubusercontent.com/76117436/109308102-7bc66280-7839-11eb-9a66-f571cdb1f462.png)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
