### ISSUE TITLE
[REMOTO] Tech Lead Front-End na Conquest One

### ISSUE THREAD

**Issue by lucasherodoto** [frontendbr/vagas#4363]
## Nossa empresa

A Conquest One é uma empresa especializada em Staffing de TI, sendo eleita 9 vezes como uma GPTW e agora está em busca de uma pessoa apaixonada por tecnologia e inovação para uma oportunidade incrível!

## Descrição da vaga

Você irá projetar, desenvolver, testar, implantar, manter e melhorar o software. Você gerenciará as prioridades, prazos e trabalhos individuais do projeto. Você terá que traduzir requisitos funcionais e técnicos em arquitetura e design detalhados de soluções, direcionando o time na direção correta e com visão de longo prazo. Você precisará instruir o time em boas práticas de desenvolvimento, padrões de projeto, testes e revisão de código.

## Local

Remoto

## Requisitos

●	Experiência com desenvolvimento FrontEnd
●	Experiência com Reactjs
●	Experiência com TypeScript
●	Sólidos conhecimentos sobre padrões de projetos (Design Patterns) e SOLID Principles,
●	Conhecimentos em Restful APIs
●	Conhecimentos em OAuth, OpenID e JWT
●	Conhecimentos básicos de UI/UX
●	Usar git de forma natural e conhecer o gitflow
●	Familiaridade com metodologias ágeis e suas aplicações práticas, principalmente Kanban e/ou Scrum

## Benefícios

Convênio SESC; Plano de Saúde e Odontológico Bradesco; 

Auxílio-creche para crianças até 5 anos;

Gympass (bora malhar!!!); 

Horário Flexível; 

Dress Code Informal; 

Seguro de Vida; 

Vale Transporte; 

Vale refeição e/ou Vale Alimentação 

Bicicletário

**Diferenciais:**

Incentivamos idas a eventos e treinamentos

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um email para lucas.martins@cq1.com.br com seu CV anexado e pretensão salarial
Enviar no assunto: Tech Lead Front End

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
