### ISSUE TITLE
[Rio de Janeiro] Front-end Developer na Manu

### ISSUE THREAD

**Issue by vicenthy** [frontendbr/vagas#4364]
## Nossa empresa

Aqui temos uma missão principal: levar simplicidade a vida de nossos clientes através de uma plataforma que leva um salão de beleza a qualquer lugar! Priorizamos o conforto e a praticidade, por isso buscamos levar a melhor experiência desde a solicitação até a realização do serviço. Para isso ser possível, precisamos de grandes talentos que nos ajude a construir o futuro da beleza e mostrar que ele é #SimplesAssim

Vem pro #TimeManu
## Descrição da vaga

A pessoa será responsável por projetar, desenvolver, testar e depurar aplicativos móveis e web responsivos para a empresa. Usando JavaScript, HTML e CSS, este candidato será capaz de traduzir as necessidades do usuário e da empresa.
## Local

Exemplo: Escritório, [RIO DE JANEIRO], [RIO DE JANEIRO], [CENTRO]

## Requisitos

**Obrigatórios:**
- Bacharelado ou equivalente em Curso de Tecnologia 
- Mais de 2 anos de experiência em desenvolvimento front-end
- Experiência na construção de aplicativos da web orientados a objetos em JavaScript, HTML5 e CSS3
- Experiência em algum framework JavaScript (Angular, React etc.)
- Experiência com pré-processadores CSS

**Desejáveis:**
- Inglês

**Diferenciais:**
- projetos opensource
- conhecimentos em Java

## Benefícios

- VR de R$ 15/dia
- ...

**Diferenciais:**
- horário de trabalho flexível 

## Contratação

CLT ou PJ
## Como se candidatar

Por favor envie um email para atila.augusto@usemanu.com.br com seu CV anexado - enviar no assunto: Front-end Developer na Manu

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dias após cada processo.
E-mail para contato em caso de não haver resposta: atila.augusto@usemanu.com.br

#### Alocação
- Alocado

#### Regime
- CLT
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
