### ISSUE TITLE
[100% REMOTO] Front-end/Angular8  Developer na BRQ Digital Solutions

### ISSUE THREAD

**Issue by ReAnne123** [frontendbr/vagas#4365]
Sobre a BRQ Digital
Há 27 anos no mercado, a BRQ Digital Solutions se consolidou como uma das maiores empresas de tecnologia do país, promovendo a digitalização de bancos, seguradoras, companhias de telecomunicação e outras instituições líderes em seus setores. Com mais de 2 mil funcionários, espalhados em seis unidades, sendo cinco no Brasil e uma em Nova York, a empresa é destaque como um dos melhores lugares para trabalhar pela GPTW e Glassdoor.

Descrição da vaga
Estamos em busca de profissionais com experiência em front com Angular 8 para integrar o time no atendimento a uma grande empresa sediada em Curitiba. VAGA 100% REMOTA DURANTE E PÓS PANDEMIA.

Local
REMOTO

Requisitos
Obrigatórios:
Angular 8.
html5, css3

Benefícios
Plano de saúde
Seguro de vida
Vale Refeição
Vale alimentação
-Previdência privada
-Plano odonto
-Gympass

Contratação
CLT full pela BRQ, salário a combinar.

Como se candidatar
Por favor envie um email para Renata (ryokota@brq.com) com seu CV anexado - enviar no assunto: Vaga Front Remota

Tempo médio de feedbacks
Costumamos enviar feedbacks em até 15 dias após cada processo.

CLT
Nível
Pleno ou Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
