### ISSUE TITLE
[São Paulo] Front-end Developer na @ Air Liquide Brasil | Digital Team

### ISSUE THREAD

**Issue by albdigitalteamdev** [frontendbr/vagas#4366]
> Vaga Remota durante a pandemia

![](https://i.ibb.co/JFpd3f0/logo-AL.png)
## Air Liquide Brasil

A Air Liquide é uma empresa multi-nacional francesa líder mundial em gases, tecnologias e serviços para a Indústria e Saúde. Estamos com vagas para profissionais de TI com foco em desenvolvimento Front-end.

## 💼 Descrição da vaga

- Criará produtos (softwares web e mobile) internos para uso nacional e internacional
podendo impactar a vida de milhares de pessoas;
- Irá contribuir ativamente para a cultura do time com tendências de mercado e novas
metodologias;
- Participará na concepção e solução de problemas técnicos em projetos novos e o projetos
legados.

## 📌 Local

Remoto ou Escritório, SP, São Paulo, Brooklin

## 🎯 Requisitos

**Obrigatórios:**
- Confortável com programação orientada a objetos;
- Facilidade no consumo de CLIs;
- Cultura de Clean Code;
- Conhecimento patterns de arquitetura Front-end (Web e Mobile);
- HTML5 + CSS3 (Pré-processadores como SASS/LESS);
- Experiência e conhecimento com React e React Native;
- Experiência em gerenciamento de estados com Context API / Redux e Redux Saga;
- Experiência e conhecimento em ECMAScript e Vanilla JS;
- Experiência e conhecimento com Styled-components;
- Experiência com Git;
- Experiência com 3 anos+ de desenvolvimento como Front-end;
- Experiência e conhecimento em TypeScript;

**Desejáveis:**
- Inglês;
- Autodidata;
- Conhecimento com UI & UX;
- Gostar de sair da zona de conforto;
- Cultura de otimização de performance;
- Esteja em atualização constante da tecnologia dominada e novas tecnologias
- Equilíbrio para lidar com sistemas de alta criticidade
- Experiência com métodos ágeis (Scrum ou Kanban);

**Diferenciais:**
- Conhecimento em outras linguagens de programação (Java, Kotlin, Swift, Objective-C ou Dart);
- Experiência com cultura DevOps (Pipelines, CI, CD, Monitoramento);

## ⭐️ Benefícios
- VR de R$ 30/dia

**Diferenciais:**
- Bônus anual mediante metas atingidas

## Contratação

PJ a combinar

## 🚀 Como se candidatar

Acesse o [repositório do teste](https://github.com/albdigitalteam/frontend-test) e siga as instruções. Para saber mais sobre a vaga, [cliquei aqui](https://github.com/albdigitalteam/vagas/blob/master/frontend.md).

Por favor envie também um email para vitor.cazelatto-sc@airliquide.com com seu CV anexado - enviar no assunto: Vaga Front-end Developer.

## ⏰ Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: paulo.monte-sc@airliquide.com

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

_**Na ALB as pessoas interessadas são bem vindas em todas as vagas, independentemente de gênero, orientação sexual, raça, etnia ou deficiência.**_

![](https://i.ibb.co/X4GV83K/Whats-App-Image-2020-09-29-at-10-01-09.jpg)
![](https://i.ibb.co/jyyTGxY/Whats-App-Image-2020-09-29-at-10-01-08.jpg)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
