### ISSUE TITLE
[REMOTO] Desenvolvedor(a) Front-end Júnior na Instruct Soluções em Tecnologia

### ISSUE THREAD

**Issue by Elisa2207** [frontendbr/vagas#4367]
> 

## Instruct Soluções em Tecnologia

Aqui na Instruct nossos times são multidisciplinares e valorizamos a troca de experiência dos colaboradores entre as diversas áreas. Sabemos que os resultados dependem do trabalho em equipe! 

Prezamos por um ambiente amigável, inclusivo e seguro e estamos sempre abertos e dispostos a contribuir com a comunidade. 

Acreditamos na cultura blameless como forma de melhoria constante dos nossos processos, identificando rapidamente as falhas para corrigi-las, sem deixar de lado as responsabilidades inerentes de cada função. 

Compartilhamos as informações e o conhecimento diariamente e acima de tudo, valorizamos a transparência, respeito e honestidade nos relacionamentos. Mesmo de longe!
 
Sim! Somos 100% remotos! Mas estamos juntos todos os dias.
 
Venha provar um café de qualidade! Quer saber como? Então participe da nossa equipe!

## O que esperamos de você? 

Esperamos que você tenha bons conhecimentos em desenvolvimento web, criando interfaces, implementando frontend e integrando com backend.

Sua maior responsabilidade será atuar com interfaces desde o desenho, passando pela implementação do HTML, CSS, JavaScript e integrações com backend.

Queremos que você aplique seus conhecimentos a cada nova tarefa e reconheça áreas que não tem entendimento para resolver um problema buscando ajuda do time.

Queremos que você participe de planejamentos e estime o tempo de suas atividades, compartilhando responsabilidades, acertos e aprendizados.

## Conhecimentos e experiências fundamentais:

- De 1 a 3 anos de experiência em desenvolvimento frontend. 
- JavaScript, HTML semântico e CSS3.
- Fundamentos de Vue.js, React ou Angular.
- Fundamentos de UX e UI.
- Conceitos de integração de interface via APIs REST.
- Uso de Git para versionamento de seu código.

## Conhecimentos diferenciais:

- Vue.js.
- Docker.
- Figma.
- Jest e Cypress.
- GraphQL.

## Remuneração e benefícios:

- Regime de contratação CLT.
- Salário inicial entre R$ 2.500,00 e R$ 3.500,00.
- Plano de saúde e odontológico Sul América Saúde para o titular e seus dependentes 100% custeado pela empresa e sem coparticipação.
- Vale refeição de R$ 400,00.
- Vale alimentação de R$ 600,00.
- Seguro de vida corporativo custeado pela empresa.
- Verbas para investimento em treinamentos e educação.
- Acesso aos treinamentos da empresa sem custos.
- Prêmio de participação nos resultados.
- Prêmio quando se completa aniversário de empresa.
- A empresa fornecerá um laptop com as seguintes configurações: Dell Inspiron 14 5480 (Core i7-8565U, RAM 16GB, GeForce MX150, HDD 1TB, SSD 128GB, Full HD).

## Informações adicionais:

- O trabalho é 100% home office, dentro do horário comercial e seguindo o horário de Brasília, com viagens ocasionais custeadas pela empresa. Portanto, é fundamental ter disponibilidade para viajar.
- Horário comercial - das 9h às 18h (40h semanais).

## Como se candidatar

Acesse o link: https://instruct.com.br/trabalhe-com-a-gente/vagas/desenvolvedor-frontend-junior/

**Comment by ViniciusUrias** [comment]
Júnior com 1 - 3 anos de experiência é complicado

**Comment by guibfo** [comment]
> 
> 
> Júnior com 1 - 3 anos de experiência é complicado

Eu não entendo que conto de fadas da tecnologia é esse que a gente tá vivendo, não sei os demais, mas eu com 3 anos de experiência ainda me considerava um desenvolvedor júnior.

Essa vaga, como poucas, tem uma descrição, exigências, remuneração + benefícios em excelente acordo, veja que não estão pedindo nem "Conhecimentos sólidos em....", estão pedindo fundamentos e conceitos. Pode até argumentar que com 3 anos de experiência você conseguiria uma oportunidade pagando melhor, a única coisa que vai acontecer é que pessoas com 3 anos de experiência nessa condição não vão se candidatar, e tudo bem.

Acho que esse povo que tá entrando na área agora tá com a expectativa acima do razoável por causa do papo de que faltam profissionais na área, completamente desconexos com a realidade. Respira e volta um passinho pra trás, pedir 1 ano de experiência pra Júnior é muito razoável, acho que até mais que razoável, é o mínimo. Se você não fez faculdade pra ter 1 ano de experiência com um estágio, você pode criar seu um ano de experiência com estudos e projetos pessoais, pode provar que sabe os fundamentos de Vue, React, Angular, pode ter coisas no seu Github pra demonstrar que você sabe utilizar pelo menos basicamente, pode ter um projetinho consumindo uma API pra mostrar que você conhece o conceito de integração com APIs REST, tudo isso sem precisar ter uma carteira assinada por 1 ano

**Comment by SaMatheus** [comment]
@guibfo Concordo plenamente mano, mas a empresa precisa encarar dessa forma também. É por isso que me candidatei, por que faz 1 ano que estudo programação e vi que muitas das coisas que a empresa está pedindo estão dentro dos meus conhecimentos. E mesmo eu não tendo experiência em carteira, no decorrer desse ano eu desenvolvi muitas aplicações web como projetos pessoais e até freelas. Tomara que a empresa veja ou entenda isso como experiência.

**Comment by mciurcio** [comment]
> Júnior com 1 - 3 anos de experiência é complicado

Veja como tratamos quem ainda não tem experiência profissional: https://www.linkedin.com/posts/mciurcio_tecnologia-desenvolvimento-junior-activity-6765966848522539008-a_QM/

**Comment by SaMatheus** [comment]
@mciurcio Top de mais, encaminhei meu portifolio para vocês no email, espero que atenda as expectativas pq eu quero MUUUITO essa vaga haha

**Comment by 1gjunior** [comment]
Vaga top!
Me candidatei, espero que consiga... HAHA.!

[](https://media2.giphy.com/media/3ohfFBBSxOfr6Eqbja/giphy.gif)

**Comment by 1gjunior** [comment]
> > Júnior com 1 - 3 anos de experiência é complicado
> 
> Veja como tratamos quem ainda não tem experiência profissional: https://www.linkedin.com/posts/mciurcio_tecnologia-desenvolvimento-junior-activity-6765966848522539008-a_QM/

Já tinha enviado minha candidatura, mas após ver seu vídeo dizendo que é importante ter os projetinhos com link no currículo, fui correndo adicionar os links dos meus projetos no currículo e reenviei o currículo.
![](https://media2.giphy.com/media/3ohfFBBSxOfr6Eqbja/giphy.gif)

**Comment by devlobao84** [comment]
Olá tudo bem? Estou estudando FullStack na Instituição Digital House (formação junior), com conclusão previsto para junho/julho, e gostaria de saber se a empresa oferece alguma vaga junior em front-end, talvez até estágio, sabendo que ainda não tenho experiência prática  nem mesmo algum projeto já feito mas tenho muita vontade de aprender e crescer dentro da área front-end pra quem está começando agora e quanto seria a remuneração. Agradeço a atenção se puder me responder. :)
