### ISSUE TITLE
[São Paulo] ReactJS Developer na Mobicity

### ISSUE THREAD

**Issue by gask** [frontendbr/vagas#4369]
> Vaga Remota durante a pandemia

## Nossa empresa

A Mobicity é uma empresa de gestão de Mobilidade Corporativa. Utilizamos a tecnologia para dar às empresas a gestão completa de sua mobilidade, atuando em todos os deslocamentos dos funcionários bem como promovendo o compartilhamento de viagens, gerando mais economia e otimização de recursos. Temos como veia a integração com diversas empresas conhecidas no mercado de transportes, estando conectadas com aplicativos de transporte, locadoras de veículos, aplicativos de car sharing e até mesmo empresas de telemetria de frotas da empresa!

## Descrição da vaga

Procuramos um Desenvolvedor ReactJS júnior, para integrar a nossa equipe, alguém com perfil curioso, amante de lógica e matemática, que goste da rotina dinâmica de uma startup e que queira crescer conosco.
Na nossa equipe, queremos formar os desenvolvedores e ensinar as tecnologias de ponta utilizadas no mercado e dar os soft-skills necessários para o desenvolvimento completo.
Somos um time MUITO unido e motivado, ainda pequeno mas atendendo mais de 100 mil usuários corporativos. O desafio é enorme. E para isso sabemos que a empresa precisa investir no desenvolvedor ao máximo: Acreditamos na complementaridade dos paradigmas das plataformas e dentro do nosso time, os devs têm a oportunidade de aprender todas as plataformas que utilizamos (Além do front descrito na vaga, NodeJS para o backend, Swift e Objective C para iOS, Java para o Android e até o nosso conhecimento nos produtos de infra que utilizamos). 

## Local

Escritório, São Paulo - Av. Paulista (remoto durante a pandemia)

## Requisitos

**Obrigatórios:**
- NodeJS (básico)
- ReactJS (básico)
- Webpack (básico)

**Desejáveis:**
- ExpressJS
- MongoDB
- Redis
- Ambiente AWS
- Heroku
- Inglês intermediário

**Diferenciais:**
- Perfil empreendedor
- Trabalho em equipe
- Disciplinado

**Diferenciais:**
- Computador da empresa
- Aulas e cursos internos
- Possibilidade de Vesting

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para giovanni.ferraro@mobi-city.net com seu CV anexado - enviar no assunto: Vaga NodaJS Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: giovanni.ferraro@mobi-city.net

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Júnior

**Comment by sdavi38** [comment]
Bom dia
Sou de Recife- PE , posso enviar meu currículo para avaliação.?

**Comment by gask** [comment]
Bom dia @sdavi38 , a vaga é remota apenas durante a pandemia. Se você não tem problemas com se mudar após essa situação, pode enviar. Quando retornarmos da pandemia a vaga é alocada em São Paulo capital.

Abs!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
