### ISSUE TITLE
[Natal - RN] Senior Frontend Developer na Clavis IT

### ISSUE THREAD

**Issue by marinhoarthur** [frontendbr/vagas#437]
## Descrição da vaga

Estamos à procura de um profissional talentoso com no mínimo 5 anos de experiência com Frontend, seja Web ou Mobile. Capaz de atingir alto nível de qualidade e demonstrar alto nível de criatividade. Você trabalhará em um time misto de brasileiros e suíços e contribuirá para projetos internacionais de grande empresas em busca de inovação e soluções.

## Local

Remoto ou Escritório (se possível), Natal - RN

## Requisitos

- Conceituação e realização de Aplicações Web
- Aprimoramento e otimização de Aplicações existentes
- Uso de tecnologias e ferramentas de ponta
- No mínimo 5 anos de experiência profissional como Desenvolvedor Frontend
- Inglês fluente
- Design Responsivo
- Single Page Applications (Angular, React, Vue)
- HTML5, CSS (SASS / LESS), JavaScript, JQuery, NodeJS, GIT, Linux e MySQL
- Webservices, REST, JSON
- Interessado em layout, design, UX e tipografia
- Autocrítico em relação à qualidade

## Benefícios

- Vale-transporte
- Subsídio de plano de saúde (50%)
- Vale-refeição
- Ferramentas e hardware de ponta
- Ambiente descontraído
- Projetos internacionais
- Boa remuneração 

## A empresa

Desde 2001, a clavis IT ajuda empresas a ter ainda mais sucesso através de tecnologia inovadora, know-how e criatividade. Como um elo entre a tecnologia da informação e o comércio, nós oferecemos um vasto espectro de serviços para cumprir as suas exigências no setor da eficiência de processos, em interfaces e no alcance de grupos alvo com a ajuda de meios de comunicação digital.

## Contratação

A combinar.

## Como se candidatar

Você pode se candidatar [aqui](https://clavis.workable.com/jobs/498371).

**Comment by guilhermedeoliveira** [comment]
Moro em Natal. Teria alguma vaga de entrada na empresa, uma vaga de estágio? Tenho conhecimentos em React.js, React Native e Node.js.

**Comment by ygorlazaro** [comment]
Vocês trabalham com PJ?

**Comment by marinhoarthur** [comment]
@ygorlazaro depende do candidato e da proposta, mas é uma alternativa sim

**Comment by marinhoarthur** [comment]
@guilhermedeoliveira no momento não, somente no futuro.

**Comment by ygorlazaro** [comment]
@marinhoarthur então acho que vocês não devem se incomodar se eu ao menos mandar meu curriculo.

muito obrigado!

**Comment by marinhoarthur** [comment]
@diogomoretti tem como botar a label PJ tb? Obrigado

**Comment by georgetassiano** [comment]
@marinhoarthur aceitam quem desenvolve com o framework Vue.js?

**Comment by marinhoarthur** [comment]
@georgetassiano claro, estamos utilizando bastante vue. Super bem-vindo!

**Comment by georgetassiano** [comment]
@marinhoarthur muito obrigado pela informação, acabo de submeter!
