### ISSUE TITLE
[Remoto] Arquiteto de Software Front-end na Ensinio

### ISSUE THREAD

**Issue by guiavila** [frontendbr/vagas#4370]
# Descrição da vaga

Estamos procurando por um arquiteto ou engenheiro de software com sólida experiência projetando sobretudo aplicações client-side verdadeiramente escaláveis e manuteníveis, com significativa experiência em TypeScript e React.js para integrar o time da Ensinio.
Nós oferecemos a plataforma perfeita para quem quer ensinar e vender online, e queremos ter você nesse time! Procuramos pessoas competentes e fora da curva para crescer junto conosco. Suas responsabilidades incluiriam manter e expandir o front-end de um SaaS multi-tenancy desenvolvido com React.js, ao passo em que projeta uma nova versão dessa aplicação, nos ajudando a tomar as melhores decisões técnicas e arquiteturais.

# Local

Trabalho 100% remoto.

# Requisitos fundamentais

* Domínio acerca das melhores práticas de código, arquitetura de software, processos e metodologias de desenvolvimento, performance, manutenibilidade e escalabilidade de aplicações;
* Domínio de arquitetura limpa, arquitetura hexagonal, e sólidos conhecimentos acerca de padrões de design (DDD e afins);
* Excelentes conhecimentos de orientação a objetos e princípios SOLID (esperamos que você seja capaz inclusive de ensinar sobre isso);
* Versionamento de código com Git em times de desenvolvimento;
* Conhecimentos de HTML, CSS, JavaScript, TypeScript e Next.js;
* Experiência prévia no desenvolvimento de uma aplicação client-side verdadeiramente escalável em produção (preferencialmente sob React.js);
* Conhecimentos acerca dos paradigmas do React.js (JSX, hooks, estado e ciclo de vida, etc);
* Conhecimentos acerca de microsserviços e micro frontends;
* Sólidos conhecimentos de gerenciamento de estado em aplicações client-side escaláveis (usamos atualmente Redux aliado ao Redux Saga; no entanto, estamos totalmente abertos a novas abordagens);
* Sólidos conhecimentos acerca da comunicação cliente-servidor;
* Conhecimentos de engenharia de requisitos (elicitação, análise e especificação de requisitos) e modelagem de software (diagramação de classes, máquina de estados, casos de uso, atividades e afins).
* Experiência com testes (unitários, de integração e afins);
* Legítima vontade de resolver problemas de forma eficiente através da tecnologia;
* Disposição para compartilhar conhecimentos, liderar e instruir tecnicamente os desenvolvedores durante a implementação do software a ser projetado;

# Seria fantástico se em seu background houvesse:

Conhecimentos/experiências desejáveis, não-excludentes.

* Experiência com metodologias ágeis, sobretudo Scrum;
* Graduação completa ou em andamento em Ciência da Computação, Engenharia de Software, Engenharia da Computação, Sistemas de Informação ou congêneres.
* Conhecimentos em PHP, Laravel, Laravel Nova e/ou Vue.js (nossa stack atual do back-end);
* Nível conversacional de inglês.

# Sobre a Ensinio: uma breve descrição

A Ensinio é uma solução completa para quem quer vender e ensinar online. Permitimos que nossos clientes tenham suas próprias plataformas para vender produtos digitais e físicos, criar e distribuir cursos e conteúdos, e construir sua própria escola online com um sistema de EAD completo. A plataforma é inteiramente customizável, conta com funcionalidades de rede social e centenas de recursos avançados para garantir a melhor experiência de navegação, compra e aprendizado. Nosso ambiente é de aprendizado constante e, conosco, suas ideias serão ouvidas.

# Contratação

A combinar.

# Como se candidatar

Envie seu CV para jobs@ensinio.com com pretensão salarial e seu perfil profissional. Nos conte um pouco sobre você e o motivo pelo qual você quer esta vaga. Queremos conhecer o seu background, suas habilidades, ambições e perspectivas futuras. Se possível, inclua também seu LinkedIn e GitHub, enviando a mensagem com o assunto "Vaga - Arquiteto de Software". Faremos o possível para responder em até 5 dias úteis.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
