### ISSUE TITLE
[Remoto] Front-end Developer na Xgrow 

### ISSUE THREAD

**Issue by geekrootbr** [frontendbr/vagas#4374]
Somos uma holding com diversas startups de tecnologia, em fase de seed ou growth. Procuramos pessoas que curtem desafios, querem crescer junto com a empresa e buscam oportunidades futuras de participação. Nossa startup é focada na construção de comunidades online, fornecendo para professores, infoprodutores uma plataforma de gestão de conteúdo inteligente, dinâmica e com recursos que engajam seus alunos.

Descrição da vaga
Você estará trabalhando diretamente com o time de founders no desenvolvimento do front-end da nossa plataforma, para web e mobile. Procuramos pessoas com vontade de aprender, que desejem crescimento na carreira, que busquem uma visão de longo prazo na nossa empresa.

Local
REMOTO

Requisitos

Obrigatórios:
Forte experiência com HTML5, CSS3
Proficiência em Javascript;
Experiência em React;
Conhecimentos em ReactNative

Desejáveis:
• Conhecimento básico de NodeJS

Contratação
PJ a combinar

Como se candidatar
Por favor envie um email para rh@triadps.com com seu CV anexado - enviar no assunto: Vaga Front End

Tempo médio de feedbacks
Costumamos enviar feedbacks em até 5 dias após cada processo.

Regime
• PJ

Nível
• Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
