### ISSUE TITLE
[Brazil, Remote] Software Engineer - React Native @ Cheesecake Labs

### ISSUE THREAD

**Issue by cheesecakelabs-challenges** [frontendbr/vagas#4378]
> Vaga Remota durante a pandemia ou presencial em Florianópolis

## Nossa empresa

[Cheesecake Labs](https://cheesecakelabs.com/) is a software design and engineering partner that builds tech products. With locations in California and Brazil, we have been building apps since 2013. We know the process and empower a multidisciplinary team of 60+ designers, engineers, and project managers to deliver delightful solutions. If you’re an enthusiastic, talented, and resourceful Software engineer with the relevant skills & IT experience, let's talk about creating disruptive products, with an international and multidisciplinary team.

Cheesecake Labs continues to hire for all open roles, all interviewing and onboarding are done virtually due to COVID-19. Everyone new to the team and our current staff is working full remote from home. Our cool Florianópolis office is open since February 2021 for those who feel comfortable. We are an equal opportunity employer and embrace, support, and value diversity at our company for the benefit of our employees, our products, and our community. We do not discriminate on the basis of race, religion, ancestry, color, national origin, gender identity, sexual orientation, age, citizenship, marital status, or disability status. If you have a disability or special need that requires accommodation, please let us know at careers@cheesecakelabs.com.

Check some tips our Developer Diego has to share on [this video](https://www.youtube.com/watch?v=AksQAxRINg8).

## Descrição da vaga
Some activities you would do on a typical day at Cheesecake Labs:

- Develop and maintain mobile applications using React Native
- Develop and maintain web applications using ReactJS
- Create outstanding front-end interfaces
- Integrate apps with different APIs
- Collaborate with the design team to create mockups
- Make sure the application has a great user experience
- Write beautiful, readable, and scalable code
- Review the code of other developers
- Make sure the application solves real-world problems
- Understand the needs of our partners and come up with solutions for their problems
- Participate in Sprint Plannings and daily stand-up meetings
- Build estimates and plan roadmaps

## Local

Remoto ou Escritório no bairro Trindade, Florianópolis, Santa Catarina

## Requisitos
In order to succeed, you'll likely need the following skills:

- Experience with React Native and ReactJS – or other Single Page Application libraries
- Extras if you have experience with NodeJS, Python, Kotlin and/or Swift. But if you don’t, that’s OK too!
- Experience with Git
- Experience with RESTful backend applications
- Experience with mobile apps release pipeline
- Being up-to-date with the latest news and technologies about Frontend and Backend
- Knowledge about clean code, design patterns, and reactive programming
- Knowledge about basic design principles
- Being self-taught
- English proficiency
- Good communication skills, both in verbal and writing

## Benefícios

We offer full home office policy, health & dental care, career plan, meal allowance, Profit Share Program (PPLR), Gympass, flexible working time, English classes, additional benefits (home office setup refund, massage, yoga, nutritionist, parking lot, fuel assistance, psychotherapy, and education allowance), videogames, library, scooter, hoverboard, above-average salary, events and courses budget, and a unique work environment.

## Contratação

CLT ou outros

## Como se candidatar

Apply at https://cheesecake.recruiterbox.com/jobs/fk0uu9i/

#### Alocação
- Remoto
- Alocado

#### Regime
- CLT
- Outros

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
