### ISSUE TITLE
[REMOTO/SP] Front-end Developer Pleno e Sênior na NAVITA

### ISSUE THREAD

**Issue by rayanmarcus** [frontendbr/vagas#4379]
## Local

Remoto/São Paulo

## Responsabilidades e Atribuições

- Trabalhar na manutenção da plataforma, atuando na fila de correções de BUGs e pequenas melhorias;
- Desenvolver novas implementações, acompanhando o cronograma de atividades do RoadMap junto ao PO e especificação técnica do time de UX;
- Atuar junto ao UX e CS, para entendimento das novas demandas relacionadas ao portfólio de UI.

## Requisitos e Qualificações

- Ensino superior em ciência/engenharia da computação, sistemas de informação ou afins;
- Arquitetura de microsserviços;
- Conhecimento em estilização e conceitos modernos de UX/UI, como HTML, CSS, Bootstrap e responsividade de layout;
- Conhecimentos técnicos em Javascript, VueJS e Angular e comunicação com WEB API’s REST;
- Versionamento com Git/Bitbucket;
- Banco de dados relacional Postgres SQL / Sql Server;
- Consciência da necessidade de testes unitários e integração;
- Conhecimento de metodologias ágeis de desenvolvimento como Scrum, Kanban e XP;
- Conhecimento dos conceitos de Cloud Computing e Amazon Web Services, como ECS, EC2, ECR, ELB, S3;
- Conhecimento dos conceitos de aplicações em cluster, Docker.
- De 3 até 5 anos de experiência (para Pleno)
- Mais de 5 anos de experiência (para Sênior)

## Perfil Comportamental

- Disciplinado e organizado;
- Curioso, investigativo, persistente;
- Facilidade de comunicação e criação de relacionamento;
- Foco em resultado;
- Responsabilidade (cumpre prazos e atividades).

## Benefícios

- Ticket Refeição;
- Assistência Médica;
- Assistência Odontológica;
- Seguro de Vida;
- Auxílio Creche;
- Day Off;
- Parceria Estudantil;
- PLR.

## Como se candidatar

🔗 Se inscreva pelo link [navita.gupy.io](https://navita.gupy.io/)

#### Alocação
- Remoto
- Alocado

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by rayanmarcus** [comment]
Vaga já preenchida.
