### ISSUE TITLE
[Recife] Front-end Developer na Guava

### ISSUE THREAD

**Issue by eduardoformiga** [frontendbr/vagas#4380]
![front-guava-2021](https://user-images.githubusercontent.com/11325562/109562947-d839b400-7abd-11eb-996c-1261cf28b34c.png)

# Em busca de pessoa desenvolvedora de front-end (ou full stack)

Se você é uma **pessoa desenvolvedora de front-end** que ama desenvolver aplicações rápidas, acessíveis e bem feitas, gosta de um ambiente de trabalho leve, repleto de colaboração, discussões profundas (mas respeitosas), e memes, vem fazer parte da Guava!

Vaga para **nível pleno ou sênior** em tempo integral e **regime CLT** com **salário entre R$ 8,3k e 11k**. A vaga é para trabalho presencial no nosso escritório em Casa Forte, Recife, mas estamos trabalhando em modo remoto até o fim das medidas de isolamento social.

---

# Requisitos mínimos

- Proficiência em JavaScript/ES6
- Pelo menos dois anos de experiência trabalhando com front-end
- Vue.js, React ou Angular
- Inglês intermediário

# Diferenciais

- React Native
- APIs (REST/GraphQL)
- PWAs
- Otimização de front-end
- Tecnologias de back-end
- Testes automatizados
- Gostar de HTML, CSS e design de interação
- Curso superior na área de tecnologia

Não precisa saber de tudo isso pra se candidatar, beleza? Qualquer um destes itens já vai te deixar na frente na hora da seleção. 😉

## Na Guava você vai ter

- Horário flexível, remote-friendly
- Auxílio alimentação
- Auxílio mensal para educação, cultura e bem-estar
- Auxílio plano de saúde
- Seguro de vida
- Auxílio de viagem para até duas conferências por ano
- Outros auxílios previstos em lei
- Open bar de bebidas e lanches

---

Curtiu? É só mandar seu currículo, portfólio, Github, LinkedIn e/ou o que mais você achar relevante para [vagas@guava.software](mailto:vagas@guava.software) até **12/03/2021**! Quer saber mais sobre a empresa? Dá uma olhada no nosso site: [guava.software](https://guava.software/).

---

É mais fã de back-end? Tem vaga também!

[Em busca de pessoa desenvolvedora de back-end (Ruby)](https://www.notion.so/Em-busca-de-pessoa-desenvolvedora-de-back-end-Ruby-6bd5334e522e4f9e9aa86a888220af00)

---

### Labels

- CLT 
- Pleno 
- Sênior 
- Pernambuco
- Alocado
- Remoto durante pandemia

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
