### ISSUE TITLE
[home office] Front-end Developer na Just Digital

### ISSUE THREAD

**Issue by alicesrossi** [frontendbr/vagas#4383]
> Vaga Remota até mesmo depois da pandemia

## Nossa empresa

Acreditamos no Design para criar experiências memoráveis em tudo o que fazemos e na engenharia de software para tornar isso possível. Queremos mostrar ao mundo que entregar resultado para hoje e amanhã pode ser mais simples do que se imagina, mais divertido do que se espera, e inesquecível para gerar laços e conexões duradouras entre pessoas.
Gostamos de pessoas proativas que somem ao time de desenvolvimento auxiliando na arquitetura da solução e preze pela qualidade do software como um todo.

## Descrição da vaga

No dia a dia irá desenvolver o projeto juntamente com o restante do time, realizando a implementação do novo portal do cliente para aluguel e compra de imóveis. Desenvolvimento de componentes de front-end, integração/consumo de APIs, assim como a implementação da jornada do usuário.
O candidato deve ter experiência em implementação de portais/sistemas com controle de acesso restrito, área privativa por perfil de usuário, manipulação de dados e implementação de regras de front-end, integração com APIs REST/GraphQL e envio de arquivos.

## Local

Exemplo: Remoto ou no Escritório, em São Paulo, zona sul

## Requisitos

**Obrigatórios:**
HTML5 / CSS3 / JS / pré-processadores;
Bom conhecimento em ReactJS e Nuxt.JS
Conhecimento prático do fluxo de versionamento com GIT;
Consumos de API;
Testes unitários e comportamentais.
React Native
GraphQL

## Benefícios

Vale Refeição ou Alimentação no cartão Caju
Assistência Médica e Odontológica Notredame
Horário sempre flexível
Desconto em todas as modalidades FIAP
Credencial Plena do SESC
Terapia e grupos de conversa/apoio

## Após o COVID-19, no escritório:

Vale Transporte ou Vale Combustível
Política de home office e revezamento
Frutas no escritório e café da manhã toda sexta feira

## Contratação

CLT

## Como se candidatar

Por favor envie um email para job.ao9mo@justdigitalbr.recruitee.com

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após a finalização cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by devlobao84** [comment]
Olá tudo bem? Estou estudando FullStack na Instituição Digital House (formação junior), com conclusão  previsto para junho/julho, e gostaria de saber se  a empresa oferece alguma vaga junior em front-end, talvez até estágio pra quem está começando agora e quanto seria a remuneração. Agradeço a atenção se puder me responder.  :)

**Comment by devlobao84** [comment]
@alicesrossi  boa tarde tudo bem? havia comentando aqui na sua publicação a +/- 13 dias atrás e não tive nenhum feedback, poderia me responder tirando minhas duvidas sobre a vaga??

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
