### ISSUE TITLE
[REMOTO] Front-end Developer na nave.rs

### ISSUE THREAD

**Issue by gabrieldocoutos** [frontendbr/vagas#4388]
## Quem somos?

O time da Nave é experiente e atua como uma consultoria em todos os momentos do desenvolvimento das soluções. Somos especialistas na construção de produtos digitais utilizando o que há de mais inovador no mercado de aplicativos e sistemas.

## O que nos move? 

O nosso pilar principal é “pessoas em primeiro lugar”, sendo assim, independente do cargo e área, focamos na empatia e no bem estar de nosso clientes e membros do time. Pois só assim conseguiremos impulsionar processos de qualidade.

## Aqui você vai:

* Participar de projetos com times multidisciplinares.
* Construir um espaço que seja confortável e agradável para você vivenciar.
* Fugir do trabalho mecânico e se reinventar a todo instante através de desafios.
* Ter um ambiente flexível que proporciona crescimento e desenvolvimento constantes.
* Ser quem você é! Nós apoiamos a diversidade e não fazemos distinção de raça, religião, deficiência, gênero ou orientação sexual.
* Poder trabalhar com a roupa que quiser! Queremos que você atinja os resultados e o seu modo de vestir não nos interfere em nada.

## Skills que estamos procurando 

* HTML;
* CSS;
* Javascript;
* ReactJS;
* Styled Components;
* Hooks;
* Boa comunicação;

## Remuneração

* A faixa salarial para essa vaga é de R$1.500,00 até R$3.700,00, contratação CLT + benefícios. A proposta com o valor salarial exato será feita ao final do processo seletivo de acordo com o nível técnico, experiência e fit cultural.

## Benefícios

* Assistência médica e odontológica;
* Auxilio psicológico;
* Vale Refeição e/ou Vale Alimentação;
* Aulas de inglês;
* Horário flexível e possibilidade de home office.

## Como se candidatar

Todo processo acontece pela plataforma da Gupy. O link da vaga é esse: https://nave-team.gupy.io/jobs/714209?jobBoardSource=gupy_public_page

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 14 dias após cada processo.
E-mail para contato em caso de não haver resposta: tech@nave.rs

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
