### ISSUE TITLE
[Uberlândia/Remoto] Freelancer React

### ISSUE THREAD

**Issue by viniciusz42** [frontendbr/vagas#4389]
Instituto de Arte e Cultura de Uberlândia procura um freelancer para execução de um layout de blog em react.

## Descrição da vaga

Blog em nextjs/react com API em wordpress, sendo que o trabalho tem escopo apenas na parte do react.

## Local

Preferencialmente de Uberlândia, apesar de que o trabalho será todo remoto.

## Requisitos

**Obrigatórios:**
- React
- CSS3

**Desejáveis:**
- Wordpress

**Diferenciais:**
- Docker

## Contratação

Freelancer

## Como se candidatar

Por favor envie um email para viniciusdevep@gmail.com

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Júnior
- Pleno

**Comment by tiagooliveira08** [comment]
Inglês fluente?
