### ISSUE TITLE
[São Caetano do Sul] Front-End Developer Júnior na Biggy

### ISSUE THREAD

**Issue by agvedotti** [frontendbr/vagas#439]
labels: PJ, Júnior, CLT

## Descrição da vaga

Estamos à procura de um profissional com grande entusiasmo, vontade de aprender e crescer profissionalmente. Responsabilidade e engajamento para solucionar problemas serão um grande diferencial

Os selecionados integrarão o time de uma startup de tecnologia voltada para big data + e-commerce

## Local

Estamos localizados no Espaço Cerâmica, em frente ao Park Shopping São Caetano

## Benefícios

- A oportunidade de aprender, se desenvolver profissionalmente e assumir responsabilidades (autonomia)
- Ambiente de trabalho descontraído e equipe colaborativa
- Área de descanso com puffs, colchão de massagem, guloseimas e Playstation 4

## Requisitos

**Obrigatórios:**
- Experiência em desenvolvimento front-end
- Experiência em jquery + html5 + css + sólido conhecimento em javascript
- Experiência em: angular 2 (e versões atuais) + typescript + sass
- Conhecimentos do formato json e arquitetura rest e restful
- Conhecimentos de design responsivo
- Conhecimentos de controle de versões (git)
- Comprometimento, trabalho em equipe, ter iniciativa e boa comunicação
- Curiosidade investigativa na busca de soluções inovadoras e criativas para melhoria da ux

**Diferenciais:**
- Arquitetura css (smacss, oocss e bem)
- Design patterns (mvc, mvp e mvvm)
- Template engine - freemarker
- Template engine - ejs (embedded javascript)
- Cross-browser (internet explorer 9)

## Contratação

CLT + benefícios ou PJ a combinar (Simples)

## Como se candidatar

Por favor envie um email para vagas@biggy.com.br com seu CV anexado - enviar no assunto:  [Biggy] Front-End Developer

**Comment by angelorubin** [comment]
A vaga é remota?

**Comment by lucasaugustofrontend** [comment]
enviado

**Comment by kvnol** [comment]
@agvedotti, quais os benefícios? Não tem nenhum listado. :disappointed:

**Comment by vinirossi** [comment]
@agvedotti  boa tarde, teria uma vaga de júnior mais para estágio?

**Comment by LFeh** [comment]
Aberto ainda?
