### ISSUE TITLE
[Remoto] Front-end Developer na Workalove Edtech

### ISSUE THREAD

**Issue by LordMendes** [frontendbr/vagas#4390]
## Nossa empresa

A Workalove é uma Edtech que está construindo o maior ecossistema de Trabalhabilidade e Carreiras do mundo conectando instituições de ensino, estudantes e o setor produtivo.

Tudo que fazemos, nós acreditamos em pensar diferente, em mudar a forma como desenvolvemos o potencial humano gerando valor para as pessoas. O modo como desafiamos o modelo tradicional é criando soluções educacionais de carreira inovadoras integrada ao setor produtivo, muito bonitas, fáceis de usar e fáceis de aprender que usam algoritmos e muita ciência aplicada.

De forma pioneira e exclusiva, desenvolvemos uma tecnologia que integra, em tempo real, os planos pedagógicos dos cursos das instituições de ensino às competências exigidas pelo novo mundo do trabalho (hard skills e soft skills), na plataforma 3 em 1 que conecta instituições de ensino, estudantes e o setor produtivo.

## Descrição da vaga

Trabalhar no desenvolvimento e manutenção do produto da empresa (Front em Reactjs e Back Django)

## Local

Exemplo: Remoto

## Requisitos

**Obrigatórios:**
- Conhecimento em desenvolvimento web;
- Boa lógica de programação;
- Conhecimento em Javascript/React ;
- Inglês intermediário.

**Desejáveis:**
- Conhecimento da linguagem Python (Django)
- Git/Github

**Diferenciais:**
- Conhecimento em banco de dados;
- Suporte Técnico ou Atendimento ao Cliente;
- Docker;
- Git/Github;
- Testes automatizados;
- Conhecimento linux;
- Métodos ágeis de gestão de projetos - Scrum

## Benefícios

- Horário Flexível
- 100% Remoto

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para katia.monteiro@workalove.com com seu CV anexado - enviar no assunto: Vaga Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by JonneBR** [comment]
Opa eae, a vaga ainda está aberta?

**Comment by LordMendes** [comment]
Ja foi preenchido!
