### ISSUE TITLE
[São Paulo] Front-end Developer na Wayon

### ISSUE THREAD

**Issue by anamazzi** [frontendbr/vagas#4391]
> Vaga Remota durante a pandemia

## Nossa empresa

A Wayon IT Solutions, Empresa sólida no mercado, atua de forma integrada desenvolvendo soluções completas com serviços e produtos para empresas em toda América do Sul e que, transforma tecnologia em soluções de negócio

## Local

Butantã - SP (home office, após pandemia presencial)

## Requisitos

**Obrigatórios:**
- Experiência em HTML5, CSS3, Pré Processadores (SASS), Javascript.
- Experiência em Angular, Design Responsivo Web, Controle De Versionamento (Git/Bitbucket), Automatização De Builds (NPM, GULP, WEBPACK), Rest, Angular E React

**Desejáveis:**
Ter Senso Crítico E Se Preocupar Com Ui, Experiência Em Spa (Vuejs), Typescript, Testes Automatizados (Jasmine, Mocha)

## Contratação

PJ ou Cooperado

## Como se candidatar

Por favor envie um email para ana.mazzi@wayon.global com seu CV anexado - enviar no assunto: Front end (React e Angular)

#### Alocação
- Alocado
- Remoto

#### Regime
- Cooperado
- PJ

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
