### ISSUE TITLE
[Remoto] React Developer @ Brainn Co.

### ISSUE THREAD

**Issue by diogomoretti** [frontendbr/vagas#4392]
A **[Brainn](https://brainn.co)** procura um(a) **React Developer** para se juntar ao time. Queremos uma pessoa curiosa, criativa e com muita vontade de crescer conosco  😍

## Requisitos

**Obrigatórios:**
- Proficiência em **React** + **TypeScript**
- **GraphQL** ou **REST**: sabe consumir uma API e formatar os dados
- Familiaridade com **testes** (TDD e Integração) utilizando jest, testing-library e/ou similares
- **Desenvolvimento de interfaces** utilizando HTML, CSS e design responsivo
- Conhecimento de **Styled Components**
- Entendimento de todo **processo web** (design, desenvolvimento e deploy)

**Desejáveis:**
- Conhecimento/interesse em NodeJS ou Elixir

**Valorizamos:**
- Projetos open-source
- Contribuição com a comunidade de alguma forma

#### Contratação:

- Plano de saúde **Vitta/Unimed Seguros** (CLT sem co-participação)
- **VR** ou **VA** (CLT)

#### Auxílio Remoto:
- **Vale hardware**: ajudamos você a comprar seu fone, cadeira, PC ou o que mais você queira para se sentir confortável trabalhando
- **Vale cultura**: ajudamos você a comprar livros, cursos, entrada para eventos ou o que mais você queira para evoluir na carreira

#### Ambiente:

- **Full Remoto** (empresa nasceu remota – desde 2017)
- Trabalhar com [gente foda](https://www.linkedin.com/search/results/people/?currentCompany=%5B%2224998510%22%5D&origin=COMPANY_PAGE_CANNED_SEARCH) 

## Contratação

CLT ou outros

## Local

Remoto

## Sobre a Brainn 

Fundada em 2017 e hoje com aproximadamente 50 pessoas, a **Brainn** é uma **Venture Product Studio** que possui mais de 20 produtos entregues para grandes clientes do Brasil, EUA e Europa. Desde de 2020 a empresa vem crescendo como **consultoria**, **produtos próprios** e por meio de **M&A** (em 2021 com a [Lukin](https://www.linkedin.com/company/lukinco/)).

A empresa hoje é uma das referências em **Elixir** no Brasil, onde a maior parte dos(as) devs back-end são de Elixir.

## Como aplicar

▶️ **https://apply.workable.com/brainn/j/430F491B06**

–
<small>Temos vaga de **Elixir** e **NodeJS** também. [Veja todas →](https://apply.workable.com/brainn/)</small>

## Feedbacks 🗣

Costumamos enviar feedbacks em até **10 dias** após o primeiro contato.

Caso você não tenha recebido nenhum feedback, você pode entrar em contato pelo e-mail diogo@brainn.co =]

**Comment by marcusviniciusf** [comment]
Me interessei muito! Mas gostaria de saber se o modelo é somente CLT?

**Comment by diogomoretti** [comment]
> Me interessei muito! Mas gostaria de saber se o modelo é somente CLT?

temos outros modelos de contratação também =]

**Comment by martinsbicudo** [comment]
Existe a possibilidade de **PJ - part-time**? :grimacing:

**Comment by diogomoretti** [comment]
> Existe a possibilidade de **PJ - part-time**? 😬

Somente full-time =]

**Comment by llouiz** [comment]
Olá, bom dia! Qual seria o valor?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by diogomoretti** [comment]
Estamos contratando 👍

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
