### ISSUE TITLE
[100% Remote / London] Front-end Developer Freelancer

### ISSUE THREAD

**Issue by chrisid** [frontendbr/vagas#4393]
## Empresa
Twisted Ideas London
Somos uma pequena agencia digital com clientes na Europa e no Brasil
Alguns  trabalhos que desenvolvemos:
https://rider44.com/
http://goalergame.com/
https://lanistar.com/en/
https://rated.global/
https://www.eversys.com/
https://www.theclash.com/

## Descrição da vaga
Desenvolver e integrar Frontend com Headless backend.
Horário flexível. Apenas desejamos que responda Slack no horário de Londres (GMT)

## Local
100% Remoto.

## Requisitos

**Obrigatórios:**
- 4 anos de experiência com Vanilla Javascript
- Experiencia com RESTFul

**Desejáveis:**
- React, Svelte, Vue
- Sass, Styled Components, etc...

## Contratação
Freelancer, o projeto deve durar aproximadamente 3-6 meses.

## Como se candidatar
**NÃO aplique se estiver trabalhando. Essa vaga é FULL TIME. 8/h por dia.**
Por favor envie um email para chris@chrisid.com, com:
- link para seu CV, Linkedin ou website.
- link para sites no ar, mesmo que pessoais ou experimentais
- enviar no assunto: Vaga Frontend

## Labels
- 🏢 Remoto
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ Freela

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
