### ISSUE TITLE
[Remoto] Front-end Sênior na Simbiose

### ISSUE THREAD

**Issue by gmenegatti** [frontendbr/vagas#4395]
Olá,

Estamos buscando desenvolvedores sênior para nos ajudar na criação, lançamento e evolução produtos SaaS na Simbiose. Todos os produtos que criamos estão relacionados a dados, como bancos de dados, processamento de dados, análise e visualização de dados etc.

Buscamos profissionais full-time, part-time e também freelancers.

Envio abaixo mais algumas informações para que você possa entender melhor quem somos e o que fazemos.

# Sobre a Simbiose
https://docs.simbioseventures.com/#/public/about

# Alguns de nossos produtos
Nós criamos soluções SaaS para a área de dados e analytics. Nosso foco é no mercado internacional, portanto tudo o que fazemos é 100% em inglês. Esses são alguns dos produtos que criamos:

- https://www.slicingdice.com

- https://www.storagequery.com

- http://www.querycache.com

- https://www.gettingstartedwithdata.com

# Perfil das pessoas que buscamos
- Objetivo de vida relacionado a ajudar/desenvolver/evoluir pessoas.

- Nível de garra (paixão e perseverança) acima de 4.0 (de acordo com nossos questionários)

- Alta predisposição à riscos.

- Alto desejo de evoluir comportamentalmente (já faz terapia ou tem predisposição a fazer).

- Alta flexibilidade (baixa resistência).

- Controle emocional (pensa mais racionalmente do que emocionalmente).

- Alto nível de organização (já usa agenda, anota e organiza seus gastos, etc).

- Alta predisposição em pedir ajuda para outras pessoas.

- A maioria dos membros da família e amigos apoiando fortemente o objetivo de vida da pessoa.

- Inglês fluente ou avançado.

# Expectativas para o profissional de frontend

- Conhecimento avançado em JavaScript e/ou Python/Django

- Conhecimento prático na criação e utilização de APIs REST (OpenAPI v3)

- Conhecimento prático em otimização de código (profiling)

- Conhecimento avançado em modelagem de dados / banco de dados (afinal nossos produtos trabalham com dados)

# Remuneração

Entre R$ 10.000,00 e R$ 18.000,00 dependendo do nível técnico e comportamental do profissional.

# Candidatura

Caso tenha interesse, por favor, pedimos gentilmente que você olhe o material acima e envie seu currículo no email abaixo.

giovanna@simbioseventures.com

Agradeço antecipadamente pelo interesse e atenção.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by mrangel-jr** [comment]
@fernandocamargo, qdo puder, deixe seus comentários sobre a vaga.

**Comment by fidelisrafael** [comment]
Só queria lembrar que é sempre possível checar o o Glassdoor de qualquer empresa antes de entrar em contato: https://www.glassdoor.com.br/Avalia%C3%A7%C3%B5es/Simbiose-Ventures-Avalia%C3%A7%C3%B5es-E2489298.htm
