### ISSUE TITLE
[São Paulo - Home Office] Front-end Developer na Medway

### ISSUE THREAD

**Issue by Vilson-Ferreira** [frontendbr/vagas#4396]
> Vaga Remota durante a pandemia

## Nossa empresa

Somos a Medway, uma EdTech formada por médicos em plena expansão que atua ajudando médicos a alcançar a residência dos seus sonhos.

## Descrição da vaga

Irá atuar dentro de um time de tecnologia sendo responsável pelas soluções de marketing, foco na vitrine de vendas, sites de conteúdo e integrações com ferramentas externas. Autonomia é a principal característica que buscamos,para que apoie áreas de design, criação e marketing no apoio não somente ao desenvolvimento mas também nos processos de design, prototipação e aprovação do que será implementado.

## Local

Remoto, com escritório em SP, São Paulo, Berrini.

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com PHP, preferencialmente em soluções de marketing e vitrine de vendas.
- Linguagem PHP 7.3 e amplo domínio integrado com CMS WordPress 5.5.3. 
- Ambiente Google Cloud usando servidores CentOS e Apache 
- Biblioteca JavaScript: jQuery, SASS, ReactJS, Webpack, BarbaJS. 
- RD Station. 
- Linguagem SQL e banco de dados MySQL. 
- Cultura de atuação com práticas ágeis, preferencialmente Kanban.

**Desejáveis:**
- Integração de checkout com Hotmart. 
- Node. 
- Google Analytics. 
- Hotjar. 
- Yoast SEO. 
- Metabase.

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para vilson.ferreira@medway.com.br.
- Envie currículo anexo e linkedin.
- Envie sua pretensão.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: renata.freitas@medway.com.br

#### Alocação
- Remoto, com reuniões presenciais conforme necessidade.

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

**Comment by pablo-moraes** [comment]
Isso realmente é uma vaga Front-end?

**Comment by Vilson-Ferreira** [comment]
> Isso realmente é uma vaga Front-end?

Com certeza Pablo. Alguma dúvida ou algo estranho que tenha sentido?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
