### ISSUE TITLE
[São Paulo - Home Office] Front-end Developer na Medway

### ISSUE THREAD

**Issue by Vilson-Ferreira** [frontendbr/vagas#4397]
> Vaga Remota durante a pandemia

## Nossa empresa

Somos a Medway, uma EdTech formada por médicos em plena expansão que atua ajudando médicos a alcançar a residência dos seus sonhos.

## Descrição da vaga

Atuação dentro de um time de tecnologia e produto, responsável pela nossa Plataforma do Aluno solução esta Web e Apps Android + iOs. Buscamos pessoas engajadas com desenvolvimento de produtos, atuantes não apenasem desenvolvimento, mas em ciclos de MVP, apoio ao roadmap, ideação e planejamento de releases com experiência em práticas ágeis (não simplesmente 
Scrum). 

## Local

Remoto, com escritório em SP, São Paulo, Berrini.

## Requisitos

**Obrigatórios:**
- React JS para desenvolvimento web. 
- React Native para desenvolvimento mobile. 
- Conhecimento na plataforma Expo. 
- Redux + Axios. 
- Soluções baseadas em microserviços Restful. 
- Repositório de código com GIT. 

**Desejáveis:**
- Infraestrutura em AWS usando Amplify. 
- Firebase e/ou outras ferramentas de Analytics. 

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para vilson.ferreira@medway.com.br.
- Envie currículo anexo e linkedin.
- Envie sua pretensão.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: renata.freitas@medway.com.br

#### Alocação
- Remoto, com reuniões presenciais conforme necessidade.

#### Regime
- PJ

#### Nível
- Pleno
- Senior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
