### ISSUE TITLE
[São Paulo] Estágio Desenvolvedor Front End - Trendi

### ISSUE THREAD

**Issue by fabriciovieira** [frontendbr/vagas#44]
## Descrição da vaga

Estamos à procura de um estagiário(a) de desenvolvimento front-end que queira aprender e possa ajudar nosso time a desenvolver projetos inovadores com o que há de mais moderno nas tendências tecnológicas.

​Desejamos um profissional ​atento aos detalhes e que saiba que toda boa interface começa com um código bem organizado.

## Local

São Paulo - Berrini

## Benefícios

- Vale transporte (VT)
- Vale refeição (VR)

## Requisitos

**Obrigatórios:**
- HTML
- CSS
- Javascript

**Diferenciais:**
- Ser detalhista
- Pré-processadores CSS (LESS, Stylus...)
- Automatizadores (Grunt, Gulp...)
- Gerenciador de dependências (Bower...) 
- Perfil no Github

## Contratação

Estágio

## Nossa empresa

A [Trendi](http://trendi.com.br) é uma agência de transformação fundada em São Paulo em 2009 e com filial inaugurada em 2014 em Nova Iorque. Trabalhamos com marketing digital e somos apaixonados pela nova dinâmica de comunicação fomentada pela internet e as novas tecnologias.
 
Temos o privilégio de trabalhar com grandes marcas, em projetos de longo prazo com resultados contundentes. 

## Como se candidatar

Enviar currículo para: ​vagas-front@trendi.com.br, com o título “Estagiário(a) em Desenvolvimento Front-End”

**Comment by LFeh** [comment]
Boa sorte @fabriciovieira ;)

**Comment by Rxon7** [comment]
Tem certeza desse email tah certo?

**Comment by fabriciovieira** [comment]
@Rxon7 estamos recebendo por lá sim. Deu algum erro com você?

**Comment by Rxon7** [comment]
Acho que agora <h1>Foi</h1>

**Comment by thierryrene** [comment]
cv enviado, obrigado!

**Comment by gstvribs** [comment]
enviado :+1:

**Comment by camilatigre** [comment]
@fabriciovieira 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
