### ISSUE TITLE
[São Paulo] Freela REACT Isomorphic - Montagem da arquitetura

### ISSUE THREAD

**Issue by luisa-haddad** [frontendbr/vagas#440]
## Descrição da vaga

Buscamos perfil Senior para fazer arquitetura de um projeto isomorphic. O projeto consiste no desenvolvimento de um portal com foco em SEO e fácil manutenção.

## Local

Própria casa ou Pinheiros

## Requisitos

**Obrigatórios:**
* Conhecimento sólidos e experiência com React;
* Aplicação de Server Side Render;
* NPM
* Webpack
* Gulp;
* Git;
* Integração com Web Service;
* SASS;
* HTML5;
* Crossbrowser;
* Flexbox;
* ES6;

## Contratação

PJ por tempo determinado

## Nossa empresa

VML Brasil - Mais informações no primeiro contato.

## Como se candidatar

Por favor envie um email para luisa.haddad@vmlbrasil.com com seu CV anexado - enviar no assunto: Vaga React Portal
* CV
* Projetos (GitHub, portfolio etc)
* Pretensão Salarial

**Comment by mtmr0x** [comment]
@luisa-haddad Essa é a vaga Senior que comentou? Se não, qual seria? Assim coloco a label certinha aqui e ajuda os candidatos a filtrarem :)

**Comment by suissa** [comment]
@mtmr0x “Buscamos perfil Senior ”

**Comment by mtmr0x** [comment]
@suissa hahahaha nao tinha visto

**Comment by suissa** [comment]
@mtmr0x respondi pelo Telegram ainda hehehheee

**Comment by luisa-haddad** [comment]
@mtmr0x Oie, só uma coisa, não precisa ser alocado. ;)

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by luisa-haddad** [comment]
Não, vou finalizar. Obrigada.
