### ISSUE TITLE
[São Paulo] Front-end Developer Sênior no PagSeguro

### ISSUE THREAD

**Issue by DanieleUOL** [frontendbr/vagas#4403]
> Vaga Remota durante a pandemia

## Nossa empresa

Nascemos em 2006 com o propósito de revolucionar o mercado de meios de pagamento e promover soluções inovadoras em serviços financeiros. Foi com a gente que os consumidores passaram a comprar e vender – dentro e fora da internet – de forma rápida, simples e segura. Acreditamos tanto no potencial da tecnologia, que criamos o PagBank, um banco digital, que visa democratizar os serviços financeiros no Brasil.

Hoje somos gigantes e seguimos impactando a vida de milhões de pessoas diariamente, oferecendo serviços rápidos, simples e seguros.

Tudo isso só possível, pois aqui, no PagSeguro PagBank, a pesquisa e a inovação fazem parte do nosso DNA, compartilhamos experiências com profissionais talentosos e criativos, em um ambiente colaborativo, onde o aprendizado é garantido.

Quer fazer parte dessa história? Confira nossas vagas e #vemproPags.

## Descrição da vaga

Participar da interpretação de requisitos junto ao Product Owner.
Criar protótipos para validar ideias. Isso quer dizer que pode ser necessário fazer código web para desktop e mobile, sem descartar testes com tecnologias emergentes.
Dar manutenção nas ferramentas internas criadas pelo time.
Atuar de forma proativa na identificação de problemas e causa raiz.
Testar tecnologias que possam ter alguma sinergia com o nosso negócio.

## Local
São Paulo ou Remoto

## Requisitos
Superior completo em Ciência da Computação, Engenharia, Sistemas da Informação ou áreas correlatas.
Experiência em Stash, Git.
Experiência em desenvolvimento Javascript.
Experiência em React, Node.js e CSS.
Experiência em testes unitários
Experiência em documentação.

**Desejáveis:**
Conhecimento em boas práticas de usabilidade.
Entendimento em tendências em tecnologias.
Conhecimento em Cloud AWS, Jenkins e Next.js.

## Benefícios

- Plano de saúde e Odontologico
- Seguro de vida
- VR 
- PPR

## Contratação

CLT

## Como se candidatar

Por favor envie um email para dcosilva@uolinc.com com seu CV anexado - enviar no assunto: Vaga Front End Sr

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
