### ISSUE TITLE
[Remoto] Front-End Developer (VueJS/NuxtJS) no [SPOTZ]

### ISSUE THREAD

**Issue by LuisaALibanio** [frontendbr/vagas#4404]
Vaga para Front-End Developer (VueJS/NuxtJS) no [SPOTZ]

Requisitos para a vaga:

* Conhecimento de HTML e CSS 
* Conhecimento em Javascript (framework VueJS) 
* Entendimento sobre requisições e api’s 
* Entendimento sobre versionamento de código com Git 

Diferenciais técnicos:

* Experiência com GCP 
* Conhecimento em Typescript 
* Entendimento sobre práticas de TDD 
* Conhecimento/experiência com NuxtJS 

Soft skills:

* Gostar de desafios e muita vontade de aprender 
* Perfil autodidata com atitudes positivas apontando soluções para situações adversas 
* Boa comunicação oral e escrita 
* Pró-atividade e trabalhar bem em equipe   
* Saber fazer a gestão do próprio tempo, sendo disciplinado, comprometido e organizado para lidar com múltiplas demandas respeitando os prazos das entregas

Somos um Marketplace de locação de espaços para eventos e produções audiovisuais!
Site: https://spotz.co/

Formato de trabalho: 

* Remoto 
* PJ 
* Salário a combinar

Como se candidatar: 

* Por favor envie um email para luisa@spotz.com.br com cópia para Luiz.felipe@spotz.com.br  com seu CV anexado - enviar no assunto: Vaga Front-End Developer (VueJS/NuxtJS)

**Comment by N3R00** [comment]
Email Enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
