### ISSUE TITLE
[São Paulo] Full Stack Engineer na RoutEasy

### ISSUE THREAD

**Issue by coca-routeasy** [frontendbr/vagas#4405]
# [São Paulo] Full Stack Engineer na RoutEasy

## Nossa empresa

A RoutEasy está construindo a mais completa plataforma de roteirização do Brasil, com maior uptime, performance e segurança para nossos clientes e parceiro, transformando assim a vida de milhões de brasileiros, criando experiências únicas para os clientes finais das maiores empresas de transportes, indústrias, empresas de serviços e e-commerces dos Brasil.
Nossa missão é colocar o cliente em primeiro lugar, pensar de maneira simples, disruptiva e realista! Trazer soluções personalizadas, escaláveis que se adequem a qualquer tipo de desafio logístico de transporte

Nosso algoritmo baseado em inteligência artificial nos permite ofertar o processamento mais rápido do mercado, com aderência a diversos tipos de operações em uma plataforma 100% web, com mapas atualizados em tempo real a cada interação com os pontos de controle.
Através de 4 funcionalidades básicas, ajudamos nossos clientes e parceiros a trabalhar a construção de rotas eficientes, monitoradas através de nossas torres de controle, com 100% de visibilidade, previsão de chegada, checkpoint dos entregadores e etc.

Como fizemos isso? Aplicando tecnologia de ponta, trabalhando com pessoas excelentes, especialistas, prezando pelo desenvolvimento profissional, dando autonomia, criando um ambiente colaborativo onde as palavras chaves são cultura, engajamento, compartilhamento de conhecimento e parceria.

Agora que chegamos até aqui estamos precisando de mais pessoas com essa mentalidade para assumirem essa missão.

## Descrição da vaga

Procurando Full Stack Engineer Sr que esteja interessado em fazer parte dessa história, que goste de atuar com times multidisciplinares (de verdade), times que estão em constante evolução, pessoas que respiram tecnologias, que buscam se desenvolver profissionalmente, que gostam de compartilhar conhecimento, desenvolver pessoas e acima de tudo prezam pela cultura. Aqui todos são responsáveis pelo team builder.

## Principais responsabilidades:

Garantir que os interesses dos nossos clientes e parceiros estão sempre em primeiro lugar
Desenvolver pessoas, compartilhar conhecimento, auxiliar no team builder, replicar a cultura e mindset RoutEasy para os membros do time.
Garantir uptime de 99,999% dos nossos produtos
Implementar novas funcionalidades e melhorias em nossas plataformas
Dar suporte para o time de desenvolvimento nas tomadas de decisão do dia a dia
Auxiliar o time no processo de brainstorm, discovery e criação de pocs
Participar ativamente das decisões de tecnologia, auxiliando o time nas tomadas de decisões, escolha do stack tecnológico, desenho da solução, infraestrutura e etc.

Tecnologias que utilizamos:
Nossa plataforma foi estruturada em NodeJS, utilizamos express para nossa camada de serviços RESTFull, juntamos alguns patterns na construção da nossa solução e optamos pelo mongoDB e mongoose para garantir a persistência dos dados.
Como nem só API’s vivem nossos clientes, construímos um frontend em AngularJS (Calma, estamos migrando para React) para juntar tudo isso e criar a melhor experiência funcional.

## Local

Exemplo: Remoto/Escritório, [SP], [São Paulo], [Vila Clementino]

## Requisitos

**Obrigatórios:**
- Sede de conhecimento, pró atividade, interesse em aprender e compartilhar conhecimento.
- Compromisso com a qualidade do ambiente de trabalho e cultura
- NodeJS com express
- AngularJS (Legado RoutEasy)
- React (Interface em desenvolvimento)
- Git
- MongoDB e Mongoose
- APIs RESTFul

**Desejáveis:**
- IONIC
- Framework SPA
- Mocha
- TDD
- BDD

**Diferenciais:**
- Design Patterns
- Twelve Factors
- Cultura DevOps
- CI/CD
- Event Driven

## Benefícios

- Salário compatível com mercado
- Remuneração variável em até 20%/Mês
- Bônus semestral
- Férias remuneradas
- Plano de Saúde e odontológico

**Diferenciais:**
- Ambiente descontraído, com PS4 (breve PS5)
- Pebolim (Totó para os cariocas de plantão ou Fla-Flu para os gaúchos)
- Café 0800, frutas
- HH com cerveja toda última sexta-feira de cada mês.

## Contratação

PJ 

## Como se candidatar

Por favor envie um email para david.coca@routeasy.com.br com seu CV anexado - enviar no assunto: Full Stack Engineer na RoutEasy [GIT]

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: david.coca@routeasy.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
