### ISSUE TITLE
[REMOTO] Front-end Developer @ Orbital

### ISSUE THREAD

**Issue by wallaceerick** [frontendbr/vagas#4408]
## Empresa
Somos a [Orbital](https://orbital.company), parceiros de grandes agências de comunicação e startups que não possuem um time de desenvolvimento. 
Valorizamos muito e somos fiéis aos nossos parceiros, admiramos a criatividade e o trabalho em equipe. Nascemos remotos para combinar estratégia com criatividade e expertise, buscando soluções inovadoras do planejamento até o resultado.

## Vaga
Estamos procurando developers que já tenham experiência no mercado utilizando Vue.js e dominem totalmente HTML, CSS e JS.

## Local
Remoto (temos um escritório na Vila Olímpia que pode ser utilizado)

## Requisitos

**Obrigatórios:**
- Mínimo de **5 anos** de experiência com HTML, CSS e JS;
- Experiência de **2 anos** Vue.js;
- Experiência com o desenvolvimento de aplicações complexas;
- Consumo de APIs Restfull;
- Git Workflow.

**Desejáveis:**
- Wordpress;
- Noções de PHP para trabalhar dentro do Laravel.

**Diferenciais:**
- Flutter
- Node.js

## Contratação

PJ

## Candidatos
Por favor, [preencha esse formulário](https://docs.google.com/forms/d/e/1FAIpQLSeSJshXX-biwk4Wx2tovGMfvOxyIqj2ris2_2kT-0LlE4LCGg/viewform) com suas informações pessoais.

## Feedbacks
Entraremos em contato com os candidatos selecionados em 1 ou 2 dias.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
