### ISSUE TITLE
[Remoto] Fullstack Angular Developer na Pontomais

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#4410]
## Descrição da vaga: 
 <p>A Pontomais está buscando Fullstack Developer!</p>
<p>Como Full Stack Developer você terá a missão de desenvolver tecnicamente o produto visando a melhor experiência para o usuário, mantendo a estabilidade, SLA e entregas de qualidade, usando as melhores práticas de código.</p>
<p><strong>RESPONSABILIDADES E ATRIBUIÇÕES:</strong></p>
<ul>
<li>Desenvolver novas features usando boas praticas de código, DRY, KISS, SOLID entregando o mais próximo possível do prazo estimado;</li>
<li>Garantir que automação de testes esteja sendo implementada;</li>
<li>Corrigir bugs no software;</li>
<li>Revisar e fazer a preparação para o deploy de produto;</li>
<li>Fazer code review;</li>
</ul>

## Pontomais: 
 <p>Hey, bora levar sua carreira para o PONTOMAIS alto 🚀🚀🚀</p>

<p>Se chegou até aqui, é porque você quer fazer parte do time incrível de Pontomakers da 7ª melhor empresa para se trabalhar no Paraná (segundo o GPTW).</p><a href='https://coodesh.com/empresas/pontomais'>Veja mais no site</a>

 ## Habilidades: 
 - Angular.js 
- MongoDB 
- PostgreSQL 
- Ruby on Rails 
- GIT

## Local: 
 100% Remoto

## Requisitos: 
 - Experiência em desenvolvimento com Ruby on Rails de pelo menos 2 anos; 
- Experiência com banco de dados PostgreSQL; 
- Desenvolvimento de aplicações Angular 2+ ; 
- Experiência em tarefas de background (Resque ou Sidekiq); 
- Experiência com versionamento de código utilizando Git 
- Conhecimento em automação de testes;

## Benefícios: 
 - Vale Refeição de R$30 por dia (+- R$630 por mês) - para aquele almoço incrível com a galera; 
- Vale Alimentação de R$300tão fixo por mês - para abastecer a geladeira (ah, e quando vc sair de férias ainda recebe o VA, viu). Ah, e VR e VA não tem aquele desconto na folha de pagamento de 20% de coparticipação ;) 
- Clube da fruta no escritório - para você se manter ficar bem saudável e se alimentar bem;  
- Vale Transporte ou Vale Combustível - tem para quem vem de busão e pra quem vem com seu próprio possante; 
- R$ 100 como ajuda de custo, enquanto estivermos em home office - para te ajudar com os gastos por trabalhar de casa durante a pandemia do Covid;  
- Plano de Saúde sem custo na mensalidade - para manter aqueeeele check-up com sua saúde sempre em dia;   
- Plano Odontológico sem custo na mensalidade - se é pra rir com a gente, os dentes vão estar brilhantes =D  
- Serviço de ambulância para emergências médicas com cobertura na empresa ou onde vc estiver - a gente espera que vc não use... mas, se precisar chamar uma ambulância, vc já tem o plano; 
- Plano de Carreiras, Cargos e Salários - para vc saber para onde vai, como deve ir e acelerar ainda mais o seu crescimento profissional por aqui;   
- Treinamentos e workshops (internos e externos) - pq nós olhamos para seu crescimento profissional junto com vc;  
- Parcerias com Instituições de Ensino - Ok, tá bom... ta aí mais um plus para você aprender mais e se desenvolver;  
- Parcerias com diversos estabelecimentos - pq a gente gosta é de desconto, seja para ter um rango mais barato ou para outras facilidades; 
- Day-off em 1 dia no mês do seu aniversário - pq é um dia especial e vc merece esse mimo de escolher qual dia vc quer folgar no mês do seu aniversário (só não esquece de trazer um pedacíneo de bolo pra gente!) 
- No dress code - tá de roupa e usou o bom senso, tá valendo :P 
- Ambiente descolado com vídeo game, puffs e muito café, chá, achocolatado (Nescau ou Toddy?) para você socializar com o os Pontomakers - aqui tem aquela máquina de cappuccino, que dá vontade de ficar tomando o dia inteiro, e o melhor: não precisa colocar a moedinha =D   
- E muita festa! Já te avisamos que a gente tem um ambiente super animado, que a gente celebra junto tudo que acontece por aqui, tanto as conquistas e sucessos quanto os aprendizados. A gente gosta de comer, beber e jogar conversa pro ar. 

## Como se candidatar:
Candidate-se em: [Fullstack Developer na Pontomais](https://coodesh.com/vagas/fullstack-developer-140507?origin=github&modal=open)

## Tempo médio de feedbacks:
 Costumamos enviar feedbacks em até 48 horas após cada etapa do processo. E-mail para contato em caso de não haver resposta: [contato@coodesh.com](mailto:contato@coodesh.com)

#### Alocação
Remoto

#### Regime
CLT

#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
