### ISSUE TITLE
[REMOTA] Tech Lead na Certsys Tecnologia da Informação 👨‍💻👩‍💻 

### ISSUE THREAD

**Issue by ItalaTechRecruiter** [frontendbr/vagas#4411]
**Certsys Tecnologia da Informação**

Eleita como uma das 100 empresas mais promissoras do mundo em implementação de soluções baseadas em tecnologia IBM, a Certsys atua fortemente na Transformação Digital das empresas, liderando grandes mudanças através de tecnologias inovadoras.

**Descrição da vaga**

**Responsabilidades:**

🔹 Definição de OKR
🔹 Acompanhamento do time
🔹 Definição sobre atuação técnica dos membros do time
🔹 Contato com cliente
🔹 Definição de estratégias de desenvolvimento

_Remoto (Escritório fica em São Paulo - SP, para quem é da região poderá ir ao escritório)_

**Requisitos**

**Obrigatórios:**

✔ Domínio de JavaScritpt para Front-end e Back-end, preferencialmente Node & React
✔ Experiência desenvolvendo um back-end com API Rest
✔ Conhecimento em arquitetura de software
✔ Conhecimento sobre Clean Architecture, Dependency Injection, Inversion of Control
✔ Testes Automatizados
✔ Liderança técnica
✔ Inglês avançado

**Diferenciais:**

✔ Conhecimento e experiência com DevOps e times ágeis e/ou Kanban e com user stories
✔ Conhecimento e experiência com Desenvolvimento de Chatbots
✔ Conhecimento e experiência com Inteligência Artificial

**Benefícios**

Seguro de vida
15 dias de férias remuneradas
Parcerias para cursos e certificados
Contratação
PJ a combinar

Como se candidatar
Por favor envie um email para **itala.santos@certsys.com.br** com seu CV anexado - enviar no assunto: Tech Lead

Labels

Alocação
• Remoto

Regime
• PJ

Nível
• Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
