### ISSUE TITLE
[São Paulo - SP] Front-end Developer na Indra Company

### ISSUE THREAD

**Issue by Wiviane** [frontendbr/vagas#4412]
## Indra Company

Aqui na Indra, buscamos profissionais com senso de dono, comprometidos com o sucesso de nossos clientes e com o desenvolvimento da sua carreira dentro da Indra.
Você atuará no nosso time de serviços financeiros em um projeto estratégico, utilizando metodologias ágeis e em um ambiente de inovação!

## Descrição da vaga

• Experiência em desenvolvimento com Angular 8+

• HTML5, CSS3, JSON, REST, Javascript, TypeScript, Jquery, Bootstrap

Desejável:

• Já ter atuado em times ágeis, utilizando Scrum

• Node JS, Java ou outra linguagem backend

• Conhecimento em Testes unitários

## Local

São Paulo - SP - Zona Sul - SP

## Benefícios

Plano de Saúde subsidiado pela empresa para o titular (com coparticipação) (acomodação quarto privativo )
Opção de inclusão de dependentes no Plano de Saúde com desconto em folha e valor reduzido (com coparticipação)
Assistência Odontológica 100% subsidiado pela empresa
Assistência Odontológica para os dependentes 100% subsidiado pela empresa
Vale Refeição OU Alimentação
Vale Transporte (opcional)
Gympass (Acesso a mais de 700 academias em todo o Brasil com planos a partir de R$ 29,90 descontado em folha de pagamento)
Opção de inclusão de dependentes no Gympass (até 03 dependentes - pago via cartão de crédito)
Parcerias com grandes marcas de consumo
Convênios para descontos com instituições de ensino (graduação e pós-graduação) e escola de idiomas
Seguro de vida em grupo
- ...

## Contratação

CLT Full

## Como se candidatar

Por favor envie um email para wrochas@indracompany.com  com seu CV anexado - enviar no assunto: Vaga Front End

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 01 dia após cada processo.

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível

- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
