### ISSUE TITLE
[REMOTA] Front-end Developer Angular + Ionic na VipCommerce

### ISSUE THREAD

**Issue by Laisiemma** [frontendbr/vagas#4413]
[REMOTA] Front-end Developer na VipCommerce

> REMOTA 100%

## Nossa empresa

A VipCommerce, através de uma plataforma white-label e um modelo logístico criados exclusivamente para o varejo alimentar, permite aos varejistas integrarem um novo canal online à operação já existente com rapidez e eficiência.

## Descrição da vaga

Você irá desenvolver front-end Web e Mobile utilizando Angular e Ionic. 

## Local

Exemplo: Remoto 

## Requisitos

**Obrigatórios:**
- Mais de 2 anos de experiência
- ANGULAR 2+ Javascript, teste unitário, HTML, CSS, typescript; 
- Essencial trabalhar em ambiente Linux; 

**Desejáveis:**
Desenvolvimento orientado a objetos, ANGULAR 8+; IONIC, Consumir API Rest; Flutter;

**Diferenciais:**

## Benefícios

- Plano de saúde e odonto
- VR de R$ 22,70/dia

**Diferenciais:**
- auxílio home office a partir do segundo mês.

## Contratação

CLT

## Como se candidatar

Por favor envie um email para lais.i@redpillrh.com.br com seu CV anexado - enviar no assunto: Vaga Front End
Ou entre em contato no celular (14) 98834-5799

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: feedbacks@empresasuperlegal.com.br

#### Alocação

- Remoto

#### Regime
- CLT

#### Nível

- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
