### ISSUE TITLE
[Lisboa/Portugal] Enterprise Service BUS @ Integer Consulting

### ISSUE THREAD

**Issue by brunoalexandrecarvalho** [frontendbr/vagas#4414]
# Integer Consulting

A INTEGER, uma empresa de consultoria na área das tecnologias, com mais de uma década de presença no mercado português, está à procura de Consultores em Enterprise Service BUS com fortes habilidades de comunicação, sentido de responsabilidade e trabalho em equipa.

## Este pode ser o desafio perfeito para ti se tens experiência em:

• Plataforma WSO2;
• Integração em processos de normalização/integração de dados;
• Orquestração de processos de sistemas distribuídos;

## Nota: Esta vaga pressupõe uma vinda para Portugal a curto/médio prazo.

Se tens o amazINg talent pretendido e queres fazer parte da equipa INTEGER, responde a este anúncio com o teu CV atualizado para bruno.carvalho@integer.pt.

Participar neste projeto significa a integração numa empresa sólida em crescimento e numa equipa jovem e dinâmica. #jumpIN

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
