### ISSUE TITLE
[São Paulo - SP] Front-end Developer Junior na Superare

### ISSUE THREAD

**Issue by wearesuperare** [frontendbr/vagas#4415]
> Vaga Remota durante a pandemia

## Nossa empresa

A Superare hoje é o braço de tecnologia do Grupo WE, uma das maiores agências full-service totalmente nacional e, mesmo no período de pandemia, estamos em expansão e precisamos de novos integrantes.

## Descrição da vaga

Você atuará no nosso time de demandas, ligado diretamente a um de nossos grandes clientes. Corriqueiramente surgem projetos que necessitem de Wordpress e outros que utilizam de Next.js + Contentful.

## Local

Próximo a Chácara Sto. Antônio, São Paulo - SP.

## Requisitos

**Obrigatórios:**
- 1 ano de experiência como desenvolvedor Front-End
- Conhecimento prático em HTML, CSS (Preferência SCSS), JavaScript/jQuery e Bootstrap
- Conhecimento em criação de temas com Wordpress

**Desejáveis:**
- React.js / Next.js
- Node.js ou outra linguagem back-end

**Diferenciais:**
- Conhecimento em bancos de dados não-relacionais
- Conhecimento com algum CMS headless

## Benefícios

- Plano de saúde
- Seguro de vida
- VR
- VT (Caso retorno ao escritório pós-pandemia)

## Contratação

CLT/PJ a combinar

## Como se candidatar

Favor enviar um email para [lucas@superare.co](mailto:lucas@superare.co) com seu CV anexado - enviar no assunto: Vaga front-end junior

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 01 dias após cada processo.

#### Alocação
- Alocado

#### Regime
- CLT
- PJ

#### Nível
- Júnior

**Comment by afoliveira** [comment]
Aceita candidatos de fora ?
