### ISSUE TITLE
[São Paulo - SP] Front-end Developer Pleno na Superare

### ISSUE THREAD

**Issue by wearesuperare** [frontendbr/vagas#4416]
> Vaga Remota durante a pandemia

## Nossa empresa

A Superare hoje é o braço de tecnologia do Grupo WE, uma das maiores agências full-service totalmente nacional e, mesmo no período de pandemia, estamos em expansão e precisamos de novos integrantes.

## Descrição da vaga

Você atuará no nosso time de projetos, ligado diretamente a demandas vigentes e novos contratos. Esses projetos vão desde a plataformas de BI e data-analytics até Chatbots para Whatsapp (somos FB partner) e, em grande maioria, nossa stack gira em React, Node e Mongo.

O Inglês é necessário para essa vaga, já que somos tanto Facebook, quanto Google partner e vez ou outra ficamos em contato com esses caras.

## Local

Próximo a Chácara Sto. Antônio, São Paulo - SP.

## Requisitos

**Obrigatórios:**
- 2 a 3 anos de experiência como desenvolvedor Front-End
- Conhecimento em React.js (Angular e Vue são opcionais)
- Conhecimento prático em HTML, CSS (Preferência SCSS), JavaScript/jQuery e Bootstrap
- Conhecimento em criação de temas com Wordpress
- Conhecimento em bancos de dados relacionais

**Desejáveis:**
- Node.js ou outra linguagem back-end
- Já ter trabalhado utilizando Next.js com foco em performance e SEO
- Conhecimento em bancos de dados não-relacionais
- Inglês para conversação

## Benefícios

- Plano de saúde
- Seguro de vida
- VR
- VT (Caso retorno ao escritório pós-pandemia)

## Contratação

CLT/PJ a combinar

## Como se candidatar

Favor enviar um email para [lucas@superare.co](mailto:lucas@superare.co) com seu CV anexado - enviar no assunto: Vaga front-end pleno

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 01 dias após cada processo.

#### Alocação
- Alocado

#### Regime
- CLT
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
