### ISSUE TITLE
[Remote] Pessoa Engenheira de Software - Frontend (React) na RD Station

### ISSUE THREAD

**Issue by fernandapoloniaRD** [frontendbr/vagas#4417]
## Nossa empresa

Ajudamos pessoas a crescerem seus negócios e países a crescerem suas economias.

🚀 Somos uma das maiores empresas SaaS do Brasil. Desenvolvemos uma plataforma 100% brasileira de automação de marketing digital e vendas;

🌎 Temos desafios de expansão nacional (onde somos líderes) e de penetração internacional na América Latina e Europa. Atendemos + 25.000 clientes de todos os portes em +20 países;

⭐ Nossos RDoers, como chamamos as +650 pessoas do time, nos elegeram 7 vezes uma das melhores empresas para se trabalhar no país e nos deram 4.5 estrelas no Glassdoor.

**_Nossa cultura:_**

Lançado em 2014, nosso Culture Code ‘tangibiliza’ em atitudes e práticas a cultura que vivemos todos os dias na RD e é dividido em 6 valores:

A-team: contratamos pelo talento, atitude e valores, o resto a gente desenvolve;
Excellence: fazemos entregas com alto nível de qualidade, menos é mais;
Lean: trabalhamos de forma ágil, criamos apenas o necessário;
Out-teach: promovemos o aprendizado contínuo, somos referência no mercado;
Data-Driven: provamos nossas hipóteses usando dados (e um pouco de intuição);
Customer First: acreditamos no sucesso do nosso cliente, e trabalhamos por isso.

## Descrição da vaga

O desafio de nossa área de Engenharia está ligado à escala & performance, por isso estamos focados na evolução da nossa plataforma no tripé de infraestrutura (Kubernetes), dados (100% na GCP) e APIs (internas e externas) — e não vamos medir esforços pra isso! Para 2021 já dedicamos R$ 100.000 milhões em tecnologia e aquisição de novos negócios que complementem nossa visão de plataforma, e colocaremos ainda mais grana se tivermos boas oportunidades na mesa.

Queremos oferecer a melhor DevXP para nossas pessoas, por isso no dia a dia inovamos com velocidade utilizando micro front-ends e desenvolvemos com produtividade através de nosso Design System em React (que já está em sua versão 2.0). Dentro do seu squad, você contará com o apoio de pessoas na posição de Team Leader, Product Manager, Designer e Developer, além de toda a galera dos chapters, guildas e tribos pra te ajudar a tracionar suas entregas como Software Engineer!

**Suas principais entregas:**
Desenvolver novas features para as soluções principalmente em React (conheça todas as nossas linguagens aqui);
Participar do discovery técnico de novas features, trazendo a visão de engenharia para a solução proposta;
Executar e medir experimentos no cenário de desenvolvimento em alguns projetos; 
Seguir nossos princípios de Engenharia (Loose Coupling, High Cohesion; Design your code to be easier to understand, not easier to write; Reducing global complexity is more important than reducing local complexity; Automate Everything).
 
**Nossas principais entregas:**
Promover um ambiente de trabalho respeitoso, diverso e leve, guiado por uma cultura sólida que é compartilhada por pessoas com as mesmas crenças e ambições;
Potencializar seu desenvolvimento através de ações de capacitação que vão desde o onboarding e goal setting, até os treinamentos, mentorias e feedbacks contínuos;
Oferecer desafios com impacto e propósito em todas as fases da sua jornada por aqui;
Entregar um pacote de benefícios completo para atender suas necessidades nos pilares de alimentação, mobilidade, saúde, bem-estar, cultura, educação e família.

## Local

Remoto ou Escritório em Florianópolis

## Requisitos

**Obrigatórios:**
Experiência com desenvolvimento frontend, principalmente em React;
Vivência com boas práticas de desenvolvimento, como Clean Architectures, TDD, BDD, DDD;
Conhecimento sobre desenvolvimento de software escalável e performático.

**Diferenciais:**
Experiência trabalhando com micro front-ends;
Experiência com Design System;
Atuação com Sidekiq, ElasticSearch;
Boas noções de desenvolvimento backend, principalmente em Ruby ou Golang;
Experiência com arquitetura em nuvem (AWS, GCP ou Azure);
Experiência com metodologias ágeis de entrega, Scrum ou Kanban;
Conhecimento sobre ferramentas de análise de produto, como Mixpanel, Gainsight PX, Amplitude, Hotjar, Google Analytics ou Segment;
Inglês ou Espanhol a partir do nível intermediário (fala, leitura e escrita);
Ser (ou querer se tornar) uma pessoa ativa na comunidade, que compartilha conhecimento dentro e fora da empresa através de eventos, artigos, mentorias, iniciativas voluntárias, projetos open source, etc.

## Benefícios

Horário flexível e opção de Home Office;

Trabalhar lado a lado e aprender diariamente com profissionais referência no mercado;

Cursos e certificações da RD University (nossa universidade corporativa) para você explorar;

Cultura de feedback e desenvolvimento intenso;

No dress code - então pode trazer a sua pantufa;

Além do que é comum como:

Plano de saúde (100% subsidiado, até para os seus dependentes);

Plano odontológico;

Vale alimentação ou refeição;

Vale transporte;

Outras parcerias de benefícios.

## Contratação

CLT

## Como se candidatar

Candidatar neste link: https://grnh.se/f58cf2a02us

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: fernanda.polonia@rdstation.com

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

#### Tecnologias
React
JS

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
