### ISSUE TITLE
[Remota] Javascript/Nodejs Developer na Venda Válida

### ISSUE THREAD

**Issue by victorgsouto** [frontendbr/vagas#4418]
## Nossa empresa

Somos uma Startup com o foco no engajamento e retenção do cliente, estamos no mercado a 3 anos e somos apaixonados pelo que fazemos. Estamos buscando um desenvolvedor com conhecimento em NodeJS para fazer parte do nosso time.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência mínima de 6 anos em Javascript, NodeJs;
- Experiência mínima de 4 anos em MongoDB, Redis e RabbitMQ;
- Consumo de APIs Restfull;
- Experiência com Front-end: HTML, EJS, CSS, SASS;
- Experiência com o desenvolvimento de aplicações complexas;
- Experiência com metodologias ágeis, sobretudo Scrum;
- Graduação completa ou em andamento em Ciência da Computação, Engenharia de Software, Engenharia da Computação, Sistemas de Informação.

## Contratação

- PJ 
- De R$ 8k a R$ 10k PJ (a depender da experiência);

## Como se candidatar

Por favor envie um e-mail para victor@vendavalida.com.br com seu CV anexado, github e pretensão salarial - enviar no assunto: Vaga Javascript/Nodejs Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
