### ISSUE TITLE
[São Paulo] Front-End Developer na Mira Educação

### ISSUE THREAD

**Issue by MiraEduc** [frontendbr/vagas#442]
## Descrição da vaga

**QUEM SOMOS:**
A Mira é uma Startup que busca solucionar uma questão básica em todo o mundo: educação. Desenvolvemos ferramentas para o aprendizado, com o objetivo de facilitar a vida de professores e gestores, envolvendo os responsáveis e garantindo uma melhora no processo educativo das crianças de modo escalável e com baixo custo.

Queremos inspirar outras pessoas, contribuir positivamente para o futuro de nosso país. Para isso contamos com colaboradores engajados, apaixonados pela nossa causa e motivados pelo impacto social.

Se você gosta de desafios, quer trabalhar com as melhores tecnologias e participar da construção do nosso projeto, veja abaixo detalhes do job:

## Local

São Paulo - Vila Clementino (Metrô Santa Cruz)

## Benefícios

•	Vale Refeição, Vale Transporte e Auxílio Creche;
•	Assistência Médica – 100% custeada pela empresa;
•	PLR – Atrelado a metais gerais;
•	Ambiente divertido, casual e liberdade para se vestir;
•	Bem-estar e diversão: Happy Hour toda sexta, Snacks a vontade, sala de descanso, vídeo game, ginástica laboral e quick massage;
•	Desconto com escola de idiomas;

## Requisitos

Como Desenvolvedor Frontend seus maiores desafios serão:

•	Desenvolver novas funcionalidades para nosso projeto de portal. Todo nosso portal segue conceito de mobile first e offline first, tendo o conceito de que deve funcionar sem conectividade;
•	Escrever testes unitários e de integração;
•	Realizar code review;
•	Participar e contribuir para o desenvolvimento dos ritos de nossas metodologias ágeis;
•	Se manter atualizado e gostar de aprender novas tecnologias;

O que esperemos de você:
•	Experiência em desenvolvimento com javascript [ES5, ES6, ES7]; 
•	Conhecimento prático sobre design patterns, refactoring, code review e testes; 
•	Experiência trabalhando com APIs Restfull; 
•	Experiência com React, Redux, Node, Socket IO e Webpack; 
•	Trabalhar com aspectos de metodologia Ágil, XP, Scrum BDD e TDD; 
•	Integração e entrega contínua (ferramentas relacionadas); 
•	Conhecimento prático com ServiceWork;
•	Ser dinâmico e gostar de compartilhar ideias;
•	Boa capacidade para resolução de problemas;
•	Capacidade de entregar rápido e com qualidade;
•	Capacidade de dar boas soluções técnicas;
•	Facilidade em aprender novas tecnologias;
•	Inglês Técnico/Avançado;

Será um diferencial:
•	Experiência com GraphQl;
•	Experiência com suporte offline para projetos web;

## Contratação

CLT Full

## Como se candidatar

Por favor envie um email para larissa.rocha@mira.vc com seu CV anexado - enviar no assunto: Vaga Front-end Developer

**Comment by gadielkalleb** [comment]
Quais são as Labels?

**Comment by LFeh** [comment]
Aberto ainda?
