### ISSUE TITLE
[Remote] Frontend Developer (Pleno e Sênior) - Post2B

### ISSUE THREAD

**Issue by lfalcao** [frontendbr/vagas#4420]
## Nossa empresa

A Post2B é um marketplace que conecta influenciadores a marcas e agências. Hoje temos em torno de 50000 influenciadores cadastrados e estamos desenvolvendo novas soluções para esse público 😄 

## Descrição da vaga

Procuramos pessoas com experiência em desenvolvimento frontend (React e React Native) e/ou backend (Ruby) para ajudar com nosso sistemas. Nossa stack hoje se resume a uma API em Ruby on Rails, um front em React e o aplicativo em React Native (ios e android). 

## Local

Conforto do seu lar - Remoto
Escritório em São Paulo - SP caso prefira.

## Requisitos

**Obrigatórios:**
- conhecimento em javascript
- experiência com react
- experiência com react native
- layout responsivo
- testes automatizados
- consumo de apis
- git

**Desejavel:**
- experiência em ruby on rails
- inglês intermediário
- firebase

## Contratação

- PJ a combinar

## Como se candidatar

Por favor envie um email com pretensão salarial para vagas@post2b.com com seu CV anexado - enviar no assunto: Vaga Dev

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.

## Labels

- Remoto
- PJ
- Junior
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
