### ISSUE TITLE
[Remote] Senior Front-end Developer (Vue.js) @ Intricately

### ISSUE THREAD

**Issue by dlarios21** [frontendbr/vagas#4423]
https://jobs.lever.co/intricately/a2b23bdc-3425-4dcf-bfc3-79f555539f63

==================================================

## Nossa empresa

Intricately is the leading provider of data insights on cloud product usage, adoption, and spend. The platform delivers real-time intelligence to cloud vendors to prospect and prioritize opportunities, start better conversations with customers, deliver more wins, and help customer success teams identify issues before they become problems. Founded in 2014, Intricately is proudly backed by Counterpart Ventures, Bloomberg Beta, Singtel Innov8, and Susa Ventures.

## Descrição da vaga

We are looking for a remote Sr. Front-End Engineer excited to own front-end product delivery. We have a founding team with deep technical expertise and have seen the tremendous impact first-hand that this role can deliver. You've got the right combination of software wizardry, technical prowess, leadership traits, and (most importantly) is someone we enjoy spending lots of time with.
As an early hire, you will be a core leader within the engineering organization with a tremendous impact on the product, culture, and the trajectory of the company. You'll be part of a team creating a service that's heavily used (and loved) by some of the largest cloud and infrastructure companies in the world. You'll work closely with the CTO to refine, improve, and ship product, and will lead a frontend team through example, mentorship, and training. If you think there could be a fit, we'd love to talk to you!

## Local

Remote.

## Requisitos

5+ years of experience as a front-end software engineer w/extensive knowledge of VueJS.
Startup experience building products people love
Strong command of software engineering principles, design, and process
Excellent written and oral communication skills
Aptitude for coaching and mentorship
Ability to work in a fast-paced startup environment and lead a team of globally dispersed developers.

## Benefícios

- Competitive salary (paid in US Dollars)
- Open vacation policy
- Up to 12 weeks of parental leave
- Fully subsidized English lessons
- Equipment stipend

## Contratação

PJ (full time).

## Como se candidatar

Please find more about us and apply here: https://jobs.lever.co/intricately/a2b23bdc-3425-4dcf-bfc3-79f555539f63

#### Regime

- PJ

#### Nível

- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
