### ISSUE TITLE
[BARUERI/SP] Front-end Developer na Dry Company do Brasil

### ISSUE THREAD

**Issue by caiosalim** [frontendbr/vagas#4424]
## Nossa empresa

Exemplo: Dry Company do Brasil é uma empresa focada no universo de telecom.
Licenciamos grande marcas e fazemos toda a parte de gestão, comunicação e uma parte do desenvolvimento.

## Descrição da vaga
Precisamos de um front-end developer para seguir nas frentes:
- Desenvolvimento dos sites (wordpress, woocommerce, html, css, js, react js)
- Desenvolvimento dos sistemas internos (node js, mysq[para registro de logs, etc])
- Auxílio na criação de uma cultura front-end dentro da empresa (melhores práticas, devops, etc)

## Local

Exemplo: Escritório, Barueri/SP
Av. Anapolis 510 - Terreo

## Requisitos

**Obrigatórios:**
- Conhecimentos sólidos em HTML, CSS e JS
- Conhecimento em Wordpress / WooCommerce
- Conhecimento em NodeJs, GIT
-

**Desejáveis:**
- Conhecimento em AWS

## Contratação

PJ ou CLT

## Como se candidatar
Por favor envie um email para caio@drycompanybrasil.com.br com seu CV anexado - enviar no assunto: Vaga Front-End Dry Company

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Alocado

#### Regime
- CLT
- PJ

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
