### ISSUE TITLE
[São Paulo] Front-end Developer na Bomtrato

### ISSUE THREAD

**Issue by JulianaPiau** [frontendbr/vagas#4425]
-->> Vaga Remota durante a pandemia

A Bomtrato, startup que vêm crescendo exponencialmente nos últimos anos sendo pioneira no ramo de aquisição de créditos judiciais, está buscando Pessoa Desenvolvedora de Front-end para compor o time. 

Nível: Sênior

Local: Atualmente home office, posteriormente modelo híbrido (dias remotos e dias presenciais em São Paulo. 

Contratação: CLT. 

Requisitos: 
- HTML5, CSS3, JS, ES6;
- Angular 6;
- Pré-processadores CSS (SASS, Less, PostCSS);
- Versionamento de projetos com GIT;
- Experiência com SPA;

Diferenciais: 
 - Conhecimento em NG-Zorro;
- Criação de código limpo, legível e cross-browser (IE8+);
- Familiaridade com metodologias ágeis e trabalho em equipes multidisciplinares;
- Experiência com ambientes de cloud computing similares (Azure)
- Desenvolvimento orientado a testes (mochajs, jasmine, jest, cypres);

Mais informações sobre a vaga e Link de Inscrição: https://byintera.in/btfegh
Dúvidas: https://www.linkedin.com/in/juliana-piau-castro/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
