### ISSUE TITLE
[REMOTO] Frontend Developer Reactjs @ Pixter

### ISSUE THREAD

**Issue by D440** [frontendbr/vagas#4426]
## Nossa empresa

A Pixter é uma boutique de software, focada em grandes clientes. Com um time de mais de 100 pessoas, trabalhando em projetos nos EUA, Portugal e Brasil, a Pixter está guiando a transformação digital de algumas das principais empresas do mundo.

## Descrição da vaga

Estamos em busca de Nodejs Developer, com experiência sólida em nível Pleno, excelente comunicação, boa desenvoltura em reuniões de planejamento, organização e bom relacionamento interpessoal, com vontade de participar de projetos GIGANTES e um time INCRÍVEL! :D

## Local

Remoto

## Requisitos

 

Requisitos:

- Experiência 2 anos+ com Reactjs
- HTML: padronização, acessibilidade, mobile patterns.
- CSS hierárquico e de fácil manutenção.
- Desenvolvimento voltado à componentização.
- Domínio em Javascript nativo (ES6>).
- Noções básicas de ferramentas para controle de versão.
- Experiência com Gulp, Grunt ou Webpack.
-

O que seria legal se você tivesse conhecimento?

- VueJS;
- NodeJS;
- TDD.
-

## Benefícios

O que a gente te oferece?

Benefícios Flexíveis (Rappi, Uber, Ubereats, Ifood, Starbucks, Bilhete Único, Spotify, Netflix, Mercados, Padarias, Serviços Médicos, Cursos, etc) - você decide com o que gastar, afinal pessoas são diferentes, seus benefícios também podem ser.
Trabalho Remoto.
Se precisar, escritório disponível com: salas de reuniões, área de descompressão, cabines de call, 24/7, café, água saborizada e chopp (isso mesmo, chopp todo dia), pra relaxar :)
Contratação no modelo PJ

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para danilo.vieira@pixter.com.br com seu CV anexado - enviar no assunto: Vaga Reactjs

## Labels

- Remoto

#### Regime

- PJ

#### Nível

- Pleno
- Sênior

**Comment by nicholasess** [comment]
@D440 essa vaga é de fullstack e não ReactJs

@felipefialho no React Brasil não aceitamos vagas que não correspondem ao que definimos, senão vira festa.

Tomem cuidado

**Comment by D440** [comment]
A vaga é front, apenas postei a descrição errada, mas arrumei minutos
depois.

Em ter., 9 de mar. de 2021 às 13:51, Nicholas Eduardo <
notifications@github.com> escreveu:

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
