### ISSUE TITLE
[São Paulo] Front-End/React Developer na Liv Up

### ISSUE THREAD

**Issue by rstraat** [frontendbr/vagas#443]
## A Liv Up

Estamos com uma vaga de front na Liv Up, uma food tech que busca tornar um prato de comida gostosa, saudável e sustentável em algo bem prático e acessível.

A empresa tem crescido exponencialmente (30% ao mês!) e parte fundamental da nossa estratégia é ter um time cada vez mais forte de tecnologia, responsável por otimizar a experiência do usuário em nosso site e desenvolver sistemas com tecnologia de ponta visando automatizar e acelerar todos os processos da empresa, desde a produção até a logística e envio dos produtos.

## Descrição da vaga

Buscamos pessoas que tenham iniciativa e sede de conhecimento, gostem de programar (com código organizado) e queiram participar de decisões focadas nos clientes e nas diferentes áreas da empresa.
Um dos desafios será migrar nosso front para React.

Nosso sistema é em Node.js, bem organizado, com testes automatizados e o time é enxuto e ágil. A oportunidade é muito boa, o time está crescendo bastante e o trabalho envolve contato direto com todas as áreas e participação direta nas tomadas de decisão.

## Local

R. Fradique Coutinho 1346, Vila Madalena - São Paulo, SP

## Benefícios

- VR
- VT
- Gympass
- Comida Liv Up à vontade pra comer aqui :D
- 40% off no nosso site
- Ambiente descontraído e informal :)
- Perto do metrô
- Horário flexível
- Eventos e happy hours

## Requisitos

- HTML5, CSS, JS
- Experiência com React (projetos open-source e/ou profissionais)

**Diferenciais:**
- Server Side Rendering
- SEO
- React Native
- Node.js

## Contratação

CLT

## Como se candidatar

Por favor envie um email para troqueumaideia@livup.com.br com seu CV em anexo - enviar no assunto: Vaga Dev Front

**Comment by rstraat** [comment]
Labels: Alocado, CLT

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
