### ISSUE TITLE
[Florianópolis] Front-end Developer na Conexão Solar

### ISSUE THREAD

**Issue by dandeastrigi** [frontendbr/vagas#4434]
## Nossa empresa

Somos uma empresa que surgiu para facilitar o acesso a Energia Solar Fotovoltaica. Por meio de um portal educativo e marketplace para a compra de equipamentos, contratação de serviço de instalação e financiamentos, nós oferecemos a solução completa para empresas e residências

##### Nossos valores
Comodidade para os clientes
Busca por excelência
Integridade
Entusiasmo
Valorização Humana
Ensinar e Aprender

##### Nossa visão
Ser a empresa referência do mercado solar brasileiro.

## Descrição da vaga

Você irá trabalhar no desenvolvimento de aplicações web e mobile utilizando tecnologias bem conhecidas no mercado, como Angular/Bootstrap/Material. 

## Local

Remoto durante a pandemia, flexível após ou Escritório, SC, Florianópolis, João Paulo.

## Requisitos

**Obrigatórios:**
Estar cursando ou ter finalizado graduação na área de tecnologia ou desenvolvimento de sistemas.
Possuir infra estrutura para trabalho (nosso modelo de trabalho é home office), se residir em Florianópolis temos escritório.

**Desejáveis:**
- Conhecimentos GoLang
- Mobile (ionic/flutter)
- Conhecimentos em JavaScript
- Conhecimentos em MongoDB
- Completar o desafio neste link (será um diferencial)
- Ser pró ativo(a)
- Comunicativo(a)
- Curioso(a)
- Possibilidade de crescimento
- Completar o desafio neste [link](https://github.com/Conexao-Solar/challenge-user-crud) (será um diferencial)

**Diferenciais:**
- Trabalho remoto

## Tipo de Contratação
- PJ

## Como se candidatar

Por favor envie um email para claudio@conexaosolar.com.br com o seu CV no assunto: Vaga Full Stack, ou por WhatssApp pelo telefone (48) 9 9981-3959

**Comment by djbrunomonteiro** [comment]
Ainda disponível ?

**Comment by dandeastrigi** [comment]
Opa, esta disponível sim!

**Comment by agsvensson** [comment]
@dandeastrigi Oi! Você tem previsão de até quando ficará aberta a vaga?
(É que vou tentar fazer o desafio, se não der tempo, envio só o cv!)

**Comment by dandeastrigi** [comment]
@agsvensson Opa, a gente preencheu esta vaga recentemente.
