### ISSUE TITLE
[remoto] Desenvolvedor(a) JavaScript Pleno/Sênior @ Supero

### ISSUE THREAD

**Issue by larissaaguiar** [frontendbr/vagas#4435]
Sobre nós:

Na Supero somos movidos por desafios, valorizamos a alta performance e quem pega junto com a equipe pra fazer acontecer! Estamos há 17 anos no mercado, realizando projetos personalizados de acordo com a necessidade de cada cliente. Nosso grande diferencial é trabalhar sempre com as melhores tecnologias e um elevado nível de resolutividade.
Buscamos um perfil #Supers para agregar ao time. Você busca evolução contínua? Está a procura de novos desafios? Então confere essa oportunidade!

O que você irá fazer:

Aqui você vai atuar junto com a equipe de desenvolvimento e encontrará um ambiente jovem e descontraído. Estamos em busca de um perfil dinâmico, que goste de desafios e superação!
Você irá trabalhar com um projeto para o ramo portuário buscando inovações, além da sustentação dos projetos existentes, com a participação na definição e execução das demandas. Vai receber a demanda do cliente, analisar com criticidade, desenvolver e atender chamados.

Para isso, você precisa:

- Experiência com: JavaScript, ReactJS ou NodeJS e RESTful.

Será um diferencial se:

- Tiver conhecimento nas tecnologias: GIT, SQL, Java, JPA e Spring Boot

O que oferecemos:

Ginástica Laboral;
Horários flexíveis;
Convênios e descontos;
Workchopps;
Treinamentos;
No dress code;
Programa indique um amigo;
Cultura que valoriza feedbacks e a diversidade;
Programa de evolução e acompanhamento profissional;
Oportunidades profissionais a todo momento!

Eai? Quer ser um #Supers? Então corre e se inscreve ;)

Candidate-se em: https://bit.ly/30iwVoZ

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
