### ISSUE TITLE
[remoto] Desenvolvedor(a) Front-end - Pleno/Sênior | Angular 8 @ Supero

### ISSUE THREAD

**Issue by larissaaguiar** [frontendbr/vagas#4436]
Responsabilidades
Desenvolver e testar soluções na tecnologia Angular 8, utilizando boas práticas de desenvolvimento de software;
Auxiliar nas soluções de negócio/sistema do cliente, ideias de negócio;

Sobre o projeto
Atuará com projetos de gestão da produção industrial (soluções para manufatura avançada - industria 4.0), com foco em desenvolvimento de novas aplicações e manutenção do sistema legado.

Formação
Graduação completa ou em andamento em Análise e Desenvolvimento de Sistemas ou áreas afins.

Requisitos
Domínio na tecnologia Angular 8 (ou superior);
Conhecimento de consumo de API´s Rest;
Orientação a Objetos;
Conceitos de microserviços, APIs;
Postman/Insomnia;
Git;

Diferenciais/Desejável
Conhecimento em recursos do Google Cloud e Firebase;
Conhecimento AzureDevOps.

Candidate-se em:https://bit.ly/2MKgfDq

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
