### ISSUE TITLE
[Remoto] Front-end Developer (React) na Cloudiabot

### ISSUE THREAD

**Issue by bernardimatheus** [frontendbr/vagas#4438]
>

## Nossa empresa

A Cloudia é uma Startup que usa Inteligência Artificial para automatizar o atendimento de pacientes em estabelecimentos de saúde. Com a Cloudia, empresas de saúde tornam-se disponíveis para os pacientes a qualquer hora do dia, em qualquer dia da semana. Ela comunica-se com o paciente via aplicativos de troca de mensagens, sem que o paciente precise baixar aplicativos extras. O estabelecimento de saúde passa a ter uma central de atendimentos que atende um número ilimitado de pacientes instantaneamente e automaticamente. O paciente ganha a comodidade de poder marcar uma consulta e tirar as suas dúvidas a qualquer hora do dia, em qualquer dia da semana.

A startup está em crescimento acelerado. Já ajudamos mais de 1000 estabelecimentos de saúde a comunicarem-se com mais de 4,2 milhões pacientes e temos o objetivo de ajudar milhões de pessoas a comunicarem-se com empresas de saúde sem complicações em todo o mundo, iniciando pelo Brasil.

O nosso produto principal consiste em uma assistente virtual na forma de um chatbot. Utilizamos Inteligência Artificial, entendimento de linguagem natual (NLU) e processamento de linguagem natural (NLP) para que a nossa assistente virtual entenda a linguagem utilizada pelos pacientes.

Aqui você trabalhará em um ambiente em constante evolução, onde terá a oportunidade de se desenvolver e crescer junto com a empresa.

Veja tudo sobre a nossa equipe no https://www.cloudia.com.br/sobre-nos/

## Descrição da vaga

Esta vaga é para trabalhar principalmente na evolução e manutenção do front-end da nossa área de login, que também chamamos de área de membros, desenvolvida atualmente utilizando React, com uma parte legada em Angular.js. Por isso, precisamos que você ame e domine essas tecnologias e já tenha alguma experiência anterior principalmente em React.

O trabalho é 100% remoto.

A lista de atividades envolve:

- Desenvolver software para a evolução do front-end da nossa área de membros utilizando o React;
- Desenvolver software para a manutenção de algumas telas antigas do front-end da nossa área de membros utilizando o AngularJS;
- Conduzir a migração de mais telas antigas da área de membros do Angular.js para novas telas em React;
- Desenvolver testes para as implementações realizadas no front-end;
- Documentar o código;
- Ajudar com o deploy do software na AWS;
- Participar das reuniões de SCRUM da equipe e ajudar na organização do projeto utilizando essa metodolodia ágil de desenvolvimento de projetos de software;

## Local

Remoto

## Requisitos

Antes de tudo, você precisa estar alinhado com os valores da empresa (veja os nossos valores em https://www.cloudia.com.br/sobre-nos/), ser humilde, gostar de servir aos clientes, ter pró-atividade, ter responsabilidade para gerir a sua própria lista de tarefas a fazer e ter uma atitude empreendedora para trabalhar e fazer a diferença no time da nossa startup.  Se você não se identificou com algum de nossos valores ou características descritas anteriormente, por favor, não se candidate a esta vaga.

É pré-requisito ser apaixonado por aprender, gostar muito de tecnologia, programar em JavaScript para React , além de ter muito interesse em desenvolver suas habilidades em outras linguagens e tecnologias que utilizamos e que você eventualmente ainda não conhece.

**Conhecimentos Importantes:**

- ReactJS;
- TypeScript
- Context (React);
- React Hooks;
- Webpack;
- Prototipação de tela;
- Styled-components;
- Noções de UX;
- UI;
- SCRUM;
- GIT (para versionamento de código).

**Conhecimentos Diferenciais:**
- AngularJS (<= v 1.7);
- Micro front-ends;
- Design Systems;
- Docker;
- CICD;
- TDD.

## O que nós oferecemos:

- Muito aprendizado.
- Fazer parte de um time que ama tecnologia, impacta socialmente e está mudando o setor da saúde brasileira.
- Possibilidade de evoluir profissionalmente e crescer junto com a startup que se encontra com altas taxas de - crescimento.
- Estar no centro do ecossistema de startups brasileiro.
- Trabalhar com tecnologias, plataformas, frameworks e linguagens de programação modernas e em crescente uso.
- Aplicar metodologias modernas de criação de startups e desenvolvimento de software na prática.
- Programa de trilhas profissionais.
- Plano de premiação anual.

## Contratação

Modalidade de contratação PJ, contrato por hora trabalhada.

## Remuneração
Entre R$3.500,00 a R$7.000,00 por mês, dependendo da experiência do candidato. Modalidade de contratação PJ, contrato por hora trabalhada.

## Como se candidatar

Por favor candidate-se através da vaga no Linkedin: https://www.linkedin.com/jobs/view/2436412670/

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
