### ISSUE TITLE
[São Paulo - Rio de Janeiro] Front-end Developer Onyo

### ISSUE THREAD

**Issue by nathpaiva** [frontendbr/vagas#444]
## Sobre a Onyo 
A Onyo ajuda os restaurantes a reter mais clientes através do pedido e pagamento pelo aplicativo. Consumidores poupam tempo, com mais conveniência. Praças de alimentação alcançam maior fidelização.

Temos uma forte cultura imposta por nossos valores. Quer conhecer todos os 5 valores? Venha conversar com a gente! Por enquanto, segue 3:

"Trabalhamos em equipe, valorizando todas as contribuições individuais".
"Somos máquinas de aprender".
"A melhor experiência do cliente é o que nos guia".

## Local

Remoto

## Benefícios

- VR
- Plano de Saúde

## Requisitos

**Obrigatórios:**
- experiência com Angular, CSS, HTML e NWJS

**Desejáveis:**
- NodeJS

## Contratação

CLT

## Como se candidatar

Por favor se cadastre pelo [formulário no site Onyo](http://onyo.com/#op-198466-front-end-developer)

**Comment by nathpaiva** [comment]
Labels: Remoto, CLT, Sênior

**Comment by ygorlazaro** [comment]
@nathpaiva Vocês trabalham com PJ?

**Comment by georgetassiano** [comment]
@nathpaiva pode ser com outro framework front-end?

**Comment by nathpaiva** [comment]
@georgetassiano a aplicação é toda em angular! se for bom se JS e conseguir fazer o teste em angular vai se dar bem!

**Comment by nathpaiva** [comment]
A vaga está fechada!

**Comment by jvgm** [comment]
Quando existir uma próxima possibilidade de trabalho remoto estou disposto :)
