### ISSUE TITLE
[Remoto] Vaga Full Stack com foco em Front-End - GeekHunter

### ISSUE THREAD

**Issue by daimasson** [frontendbr/vagas#4440]
## OLÁ, EU SOU A [GEEKHUNTER!](https://www.geekhunter.com.br/sobre) 👋 ##
Eu nasci com com o propósito de **transformar o dia a dia de empresas e a vida das pessoas desenvolvedoras**!

A minha plataforma já conta com milhares de candidatos e empresas, que se beneficiam do sistema que mais cresce no Brasil na área de RH tech.

O que me move é poder proporcionar uma ferramenta revolucionária para a contratação de profissionais de tecnologia conectando as melhores mentes desenvolvedoras às melhores empresas.

Eu sou cult, sou nerd, sou gamer, sou transformadora e conectada em um ambiente descontraído permitindo que tenhamos muitos insights e possamos resolver as coisas com criatividade e muito embasamento em dados. Enfim, sou Geek!

Estou em plena evolução e em crescimento constante! Tenho uma série de desafios para escalar minha solução para dezenas de milhares de usuários. Minha plataforma usa especialmente Ruby on Rails, mas tenho a previsão em curto prazo de novos módulos utilizando outras tecnologias, como Python, Node. js, Go etc. Minha infra-estrutura fica na AWS e utilizo tecnologias como Postgres, Ruby on Rails, AngularJS, entre outras. Sou #TeamMetodologiaÁgil, respiro deploy e tenho uma equipe de Geeks maravilhosos. 

Se você quer pertencer a algo grandioso, desafiador e transformar o mundo por meio da tecnologia, vista a camisa roxa e venha ser um Geek você também!

## DESCRIÇÃO DA [VAGA](https://geekhunter.gupy.io/jobs/708406) ##

Nessa posição sua missão principal será realizar melhorias e implementar novas funcionalidades na plataforma da GeekHunter, numa abordagem full-stack com ênfase em Frontend.

Você vai se envolver em atividades de interação da nossa plataforma escritas em Ruby On Rails e Angular. Trabalhará também com tecnologias como React e Python.

**_Alguns mandamento do nosso time de Produto:_**

- Sabe aquele time cooperativo e alto astral, você vai encontrar conosco!
- Usamos a metodologia de Pair Programming no nosso dia-a-dia, pois acreditamos que na troca é que mais se aprende!
- Usamos metodologias ágeis.
- Para nós, uma boa entrega é aquela que resolve o problema do cliente.
- Tudo que programamos é orientado a testes, TUDO mesmo!
- Somos um time que acredita que a tecnologia é o meio que utilizamos para conquistar nossos objetivos.

## RESPONSABILIDADES E ATRIBUIÇÕES ##

**_Você atuará em projetos ligados a:_**

- Implementação de novas funcionalidades da plataforma;
- Identificação e correção de erros em funcionalidades já existentes;
- Suporte a experimentos;
- Entender muito bem os requisitos e escrever código claro, simples e orientado a testes;
- Trabalhar para melhorar as soluções existentes da GeekHunter;
- Aprender e aplicar novas tecnologias para otimizar nossos processos e produtos.

## REQUISITOS E QUALIFICAÇÕES ##

**_Esperamos tecnicamente de você:_**

- Experiência em desenvolvimento web full-stack;
- Conhecimentos em AngularJS, React ou equivalente;
- Ser capaz de transformar artefatos de Design em Front-End;
- Saber sobre consumo de APIs REST ou GraphQL;
- Conhecer framework de testes;
- Saber "se virar" no Back-End.

**_Quais características serão esperadas de você:_**

- Pragmatismo no dia-a-dia;
- Focar na raiz dos problemas;
- Gostar de verdade de desafios;
- Se identificar com o valor: cliente sempre em primeiro lugar!
- Gostar de trabalhar em equipe e com bastante autonomia.

## 😋 ALÉM DISSO, AINDA OFERECEMOS: ##

- Vale-refeição/alimentação de R$ 600,00;
- Plano de saúde (Bradesco Saúde Nacional);
- Assistência odontológica;
- Gympass;
- Vale Padawan de R$130,00 mensais (benefício precioso para você utilizar no seu desenvolvimento educacional ou cultural);
- Home Office Setup no valor de R$ 600,00, em uma parcela única após seu período de experiência!
- Auxílio Internet no valor de R$ 125,00 mensal;
- Um ambiente flexível e descontraído. Queremos que você se sinta motivado(a) para vir trabalhar até mesmo nas segundas de manhã :)

### Labels ###

Remoto
CLT

Pleno
Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
