### ISSUE TITLE
[Remoto] Front-End Developer @ Before T.I

### ISSUE THREAD

**Issue by Victorhcr-pot** [frontendbr/vagas#4446]
Nossa empresa:
Com mais de 130 colaboradores, somos uma empresa especializada no desenvolvimento de softwares para médias e grandes empresas. Todos os dias, por meio de soluções digitais personalizadas, ajudamos nossos clientes a converterem mais vendas, aumentando a rentabilidade de seus negócios com segurança e praticidade. Atuamos em todo o Brasil e temos clientes como Vivo, Huawei, entre outros.

Descrição da vaga:
Projeto em Vue.js

Local
A contratação pode ser 100% remoto, hibrido ou presencial. Temos uma unidade em Campo Grande - MS

Requisitos:
Conhecimentos em framework de componetização Vue.js
Conhecimento em Javascript (com conhecimento em ES6)
Conhecimento em testes de unidade desejável (Mocka etc)
Experiência em migração de sistema legados para novas tecnologias
Conhecimento de webpack e babel

Benefícios
Cartão flexível de Benefícios no valor de R$1.000 (bandeira Visa)
Plano de Saúde Unimed
Plano de Carreira

Diferenciais:

Ambiente descontraído
Programa de Saúde Mental

Contratação
CLT ou PJ a combinar

Como se candidatar
Através do nosso site: https://www.before.com.br/sejabefore
Se tiver interesse imediato na vaga, já preencha o nosso formulário de pré-entrevista:
http://bit.ly/EntrevistaFrontEnd

Nível
Junior
Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
