### ISSUE TITLE
[São Paulo] Front-end Developer @ Superare

### ISSUE THREAD

**Issue by eadebarros** [frontendbr/vagas#445]
## Superare

Estamos com uma vaga de front-end developer pleno na Superare, uma empresa de tecnologia que cria tecnologias focadas para o mercado de publicidade. **Somos uma agência de Tecnologia!** 

Uma empresa com crescimento sólido e com vários clientes em diversas áreas de atuação. Hoje temos a conta da América Móvil (Claro, NET e Embratel) como seus desenvolvedores oficiais. 

## Descrição
Estamos em busca de uma pessoa com experiência para tocar uma equipe de desenvolvedores e ser um dos cabeças do time dev da Superare. 

A vaga é para pessoas que gostam de desafio e tenham tempo para se dedicar em atender um dos maiores anunciantes do Brasil em mídia digital. 

No projeto usaremos git, grunt, bower, angular, node, cdn e muitas outras tecnologias voltadas para desenvolvimento front-end. 

## Local

São Paulo - Chácara Santo Antônio 

## Benefícios
A combinar.

## Requisitos

**Obrigatórios:**
- 2 anos de experiência comprovadas com projetos front-end
- 2 anos de experiência comprovadas com algumas das ferramentas.

**Desejáveis:**
- conhecimentos em handle bars
- conhecimentos em banco de dados não relacional

**Diferenciais:**
- conhecimentos em wordpress

## Contratação

PJ ou CLT. A combinar.

## Como se candidatar

Por favor envie um email para gobeyond@superaremedia.com.br com seu CV anexado - enviar no assunto: Vaga Front-End - AMX

**Comment by IgorSousaFront** [comment]
Há possibilidade de remoto?

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
