### ISSUE TITLE
[Remoto] Front-end Developer na Bullcode

### ISSUE THREAD

**Issue by giorgiofellipe** [frontendbr/vagas#4452]
## Nossa empresa

Acreditamos em ideias e criamos soluções com foco em usuários reais e em seus problemas cotidianos. Desenvolver produtos com propósito, eficientes e seguros é o que nos motiva. Aliando tecnologia, design e inteligência de negócios, a Bullcode auxilia clientes e parceiros a elaborar modelos, otimizar processos, reduzir riscos, tomar decisões e alcançar resultados.

Operando em Santa Catarina desde 2014, nosso portfólio conta com aplicativos mobile e web nas áreas de varejo, saúde, eventos, finanças, logística, dentre outras.

https://bullcode.com.br

## Descrição da vaga

Desenvolvedor React/React Native!

Atribuições:
- Desenvolver e manter aplicações web e móveis dos mais diversos segmentos do mercado

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Mínimo de 2 anos de experiência profissional com React
- Habilidade analítica

**Desejáveis:**
- Experiência com TypeScript
- Experiência com Git
- Experiência com NodeJS

**Diferenciais:**
- Inglês
- Metodologias Ágeis
- Conhecimento em consumo de APIs REST
- Conhecimento em banco de dados SQL ou No-SQL
- Trello

**Diferenciais:**
- Horário de trabalho flexível
- 100% remoto
- Possibilidade de trabalhar com as mais recentes tecnologias disponíveis
- Participação nas decisões de novos projetos
- Desenvolvimento pessoal e profissional

## Contratação

PJ

## Como se candidatar

Por favor envie um email para contato@bullcode.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.

## Labels
PJ, Pleno, Remoto

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
