### ISSUE TITLE
[100% Remoto] Desenvolvedor Front-end React.js @ Ensinio Tecnologia

### ISSUE THREAD

**Issue by luizfosc** [frontendbr/vagas#4453]
### Descrição da vaga
A Ensinio é uma solução completa para quem precisa ensinar e vender online. Nossos clientes são escolas, empresas e empreendedores que utilizam nossa tecnologia para construir uma escola online completamente personalizável e 100% white label com rede social, gamificação, clube de assinaturas, ecommerce e sistema EAD completo.

Procuramos desenvolvedores especialistas em JavaScript e React.js para integrar ao nosso time de desenvolvimento Front-end. Nosso ambiente é de aprendizado constante, e você terá autonomia para sugerir e implementar suas próprias ideias. Procuramos pessoas competentes e fora da curva para crescer junto com a gente, e queremos você nesse time!

### Seu desafio e suas responsabilidades incluiriam:

- Manter e expandir o Front-end de um SaaS desenvolvido em React.js sob arquitetura multi-tenancy;
- Implementar telas com foco na experiência do usuário, seguindo boas práticas de UX;
- Desenvolver telas fiéis aos protótipos de design;
- Manter a aplicação saudável com código limpo;
- Desenvolver sempre com boas práticas e princípios SOLID;
- Nos ajudar a tomar as melhores decisões técnicas em novos projetos no futuro.

### Requisitos fundamentais

- Versionamento de código com Git em times de desenvolvimento;
- Sólidos conhecimentos de HTML e CSS (incluindo CSS-in-JS). Você deve ser capaz de codificar, com maestria, qualquer tipo de interface de forma responsiva;
- Sólidos conhecimentos de JavaScript (manipulação da DOM, estruturas de dados, funções assíncronas, iteradores e geradores, etc);
- Experiência prévia no desenvolvimento de uma aplicação em produção sob React.js;
- Sólidos conhecimentos acerca dos paradigmas do React.js (JSX, hooks, estado e ciclo de vida, etc);
- Sólidos conhecimentos de gerenciamento de estado com Redux (incluindo, preferencialmente, redux-saga);
- Sólidos conhecimentos acerca da comunicação cliente-servidor (ser capaz de compreender o fluxo de dados e consumir informações de uma API REST);
- Legítima vontade de resolver problemas de forma eficiente através da tecnologia, ao passo em que evolui pessoalmente e profissionalmente, recebendo feedbacks constantemente;
- Noções acerca de boas práticas de código, arquitetura de software, processos e metodologias de desenvolvimento, performance, manutenibilidade e escalabilidade de aplicações.

### Seria fantástico se em seu background houvesse:
(Conhecimentos/experiências desejáveis, não-excludentes)

- Experiência com metodologias ágeis, sobretudo Scrum;
- Noções acerca de UI/UX, princípios de usabilidade e do design de interfaces;
- Conhecimentos de e/ou experiência com TypeScript;
- Conhecimentos de e/ou experiência com Next.js;
- Experiência com aplicações escaláveis;
- Experiência com testes (unitários, de integração e afins);
- Conhecimentos de arquitetura e manutenibilidade de software;
- Significativo conhecimento de orientação a objetos e princípios SOLID;
- Graduação completa ou em andamento em Ciência da Computação, Engenharia de Software, Engenharia da Computação, Sistemas de Informação ou congêneres.
- Nível conversacional de inglês.

### Local
Trabalho 100% remoto.

### Contratação
PJ ou CLT a combinar

### Como se candidatar
Para aplicar para a vaga, basta acessar [este formulário](https://forms.gle/XWR6FND8ehUAXVK2A) e preencher com suas informações. Faremos o possível para responder em até 5 dias úteis.

**Comment by cpereiramt** [comment]
Boa tarde, é possível horário flexível?

Em qui, 11 de mar de 2021 14:58, luiizfosc ***@***.***>
escreveu:

**Comment by luiizfosc** [comment]
Olá!
Podemos conversar a respeito.
Caso tenha interesse, valor acessar este formulário
<https://forms.gle/XWR6FND8ehUAXVK2A>.

Obrigado! 😊

Em qui., 11 de mar. de 2021 às 16:08, Clayton Pereira <
***@***.***> escreveu:

**Comment by cpereiramt** [comment]
Ok, irei fazer minha inscrição

Obrigado !

Em qui, 11 de mar de 2021 15:17, luiizfosc ***@***.***>
escreveu:

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
