### ISSUE TITLE
[100% remoto] Arquiteto de software (Front-end) @ Ensinio Tecnologia

### ISSUE THREAD

**Issue by luizfosc** [frontendbr/vagas#4454]
### Descrição da vaga
A Ensinio é uma solução completa para quem precisa ensinar e vender online. Nossos clientes são escolas, empresas e empreendedores que utilizam nossa tecnologia para construir uma escola online completamente personalizável e 100% white label com rede social, gamificação, clube de assinaturas, ecommerce e sistema EAD completo.

Estamos em busca de um arquiteto ou engenheiro de software para integrar ao time da Ensinio. É necessário sólida experiência em projetar sobretudo aplicações client-side verdadeiramente escaláveis e manuteníveis e significativa experiência em TypeScript e React.js.

Nosso ambiente é de aprendizado constante, e você terá autonomia para sugerir e implementar suas próprias ideias. Procuramos pessoas competentes e fora da curva para crescer junto com a gente, e queremos você nesse time!

### Seu desafio e suas responsabilidades incluiriam:

- Manter e expandir o Front-end de um SaaS desenvolvido em React.js sob arquitetura Multi-Tenancy;
- Garantir que o software se mantenha em uma arquitetura limpa, sustentável, escalável e robusta;
- Liderar o time a implementar as melhores práticas de arquitetura;
- Nos ajudar a tomar as melhores decisões técnicas em novos projetos no futuro.

### Requisitos fundamentais

- Domínio acerca das melhores práticas de código, arquitetura de software, processos e metodologias de desenvolvimento, performance, manutenibilidade e escalabilidade de aplicações;
- Domínio de arquitetura limpa, arquitetura hexagonal, e sólidos conhecimentos acerca de padrões de design (DDD e afins);
- Excelentes conhecimentos de orientação a objetos e princípios SOLID (esperamos que você seja capaz inclusive de ensinar sobre isso);
- Versionamento de código com Git em times de desenvolvimento;
- Conhecimentos de HTML, CSS, JavaScript, TypeScript e Next.js;
- Experiência prévia no desenvolvimento de uma aplicação client-side verdadeiramente escalável em produção (preferencialmente sob React.js);
- Conhecimentos acerca dos paradigmas do React.js (JSX, hooks, estado e ciclo de vida, etc);
- Conhecimentos acerca de microsserviços e micro frontends;
- Sólidos conhecimentos de gerenciamento de estado em aplicações client-side escaláveis (usamos atualmente Redux aliado ao Redux Saga; no entanto, estamos totalmente abertos a novas abordagens);
- Sólidos conhecimentos acerca da comunicação cliente-servidor;
- Conhecimentos de engenharia de requisitos (elicitação, análise e especificação de requisitos) e modelagem de software (diagramação de classes,  máquina de estados, casos de uso, atividades e afins).
- Experiência com testes (unitários, de integração e afins);
- Legítima vontade de resolver problemas de forma eficiente através da tecnologia;
- Disposição para compartilhar conhecimentos, liderar e instruir tecnicamente os desenvolvedores durante a implementação do software a ser projetado;

### Seria fantástico se em seu background houvesse:
(Conhecimentos/experiências desejáveis, não-excludentes)

- Experiência com metodologias ágeis, sobretudo Scrum;
- Graduação completa ou em andamento em Ciência da Computação, Engenharia de Software, Engenharia da Computação, Sistemas de Informação ou congêneres.
- Conhecimentos em PHP, Laravel, Laravel Nova e Vue.js (nossa stack atual do back-end);
- Nível conversacional de inglês.

### Local
Trabalho 100% remoto.

### Contratação
PJ ou CLT a combinar

### Como se candidatar
Para aplicar para a vaga, basta acessar [este formulário](https://forms.gle/XWR6FND8ehUAXVK2A) e preencher com suas informações. Faremos o possível para responder em até 5 dias úteis.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
