### ISSUE TITLE
[Remoto] Front-end Developer sênior PJ (Vue.js) para startup em Inglaterra

### ISSUE THREAD

**Issue by hdantas** [frontendbr/vagas#4456]
## Nossa empresa

Estou procurando developers para uma fintech em Inglaterra. A tecnologia está no centro da oferta desta startup que recentemente se tornou duplo 🦄, isto é foi avaliada em $2B e está na vanguarda da inovação em fintech no Reino Unido. Foi das primeira seguradora de animais de estimação no Reino Unido a oferecer sinistros on-line sem formulário e com sistemas desenvolvidos para tornar as coisas mais rápidas e fáceis para os clientes.

## Descrição da vaga

Estamos à procura de um experiente programador frontend para contribuir para as nossas aplicações internas e externas em Vue.js.

Procuramos nível sénior de experiência, alguém que possa trabalhar de forma independente e tenha excelente capacidade de comunicação em inglês. Já temos uma equipe remota experiente e bem establecida que estamos a aumentar.

Trabalhamos num modelo de squads inspirado no modelo da Spotify onde os programadores têm autonomia para tomarem as melhores decisões. A equipa é bastante experiente e se esforça para aplicar as melhoras práticas da indústria (CI/CD, trunk based development, SOLID, progamação em pares, BDD, etc)

A empresa está sediada no Reino Unido mas abriu recentemente um escritório nos Estados Unidos. A posição é 100% remota para trabalhar maioritariamente com a nova equipa dos Estados Unidos. O contrato é PJ com a duração de 12 meses com possibilidade de renovação.

## Local

Remoto

## Requisitos

- Nível sénior de experiência com Javascript, incluindo ES6 + e node.js
- Experiência com Nuxt, Netlify ou SSR é uma vantagem
- Vue.js (ou outras frameworks de JavaScript)
- Teste com Jest (ou outras framework de testes unitários)
- HTML e CSS responsivos
- Pré-compiladores: SASS, LESS
- APIs REST e GraphQL
- Práticas e arquiteturas de segurança de front-end
- Bons conhecimentos de ferramentas de build relevantes, como webpack, rollup
- Metodologias ágeis como Scrum ou Kanban
- Excelente inglês verbal e escrito (o processo de recrutamente será feito em Inglês)

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email _em inglês_ para henrique@omarcodes.com com seu CV anexado - enviar no assunto: 
"Frontend Developer Position (frontendbr)"

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias úteis após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
