### ISSUE TITLE
[Remoto / São José dos Campos] Front-End Developer Jr na Worked

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#4457]
## Descrição da vaga: 
 <p><strong>*Esta vaga é para uma empresa parceira, OnCar</strong></p>
<p>Aqui não vemos sua experiência pelo seu tempo de trabalho, mais sim, pela sua capacidade. Se é júnior e entende de React ou Vue.js, queremos entender mais sobre você para entrar no nosso time. Toda nossa estrutura está em jQuery, mas estamos em constante evolução por aqui, atualizando todos os nossos produtos. Se quer começar algo do zero e se desafiar conosco, estamos de braços abertos para você!</p>
<p></p>
<p><strong>Responsabilidades da vaga:</strong></p>
<p>• Construir interfaces com padrões de qualidade de código e usabilidade;</p>
<p>• Atuar diretamente com a equipe de marketing para criação de novas funcionalidades;</p>
<p>• Integrar o front-end com nossas as aplicações através de Web APIs;</p>
<p>• Trabalhar em equipe utilizando a metodologia ágil SCRUM;</p>
<p>• Implementar os designs pré desenvolvidos de forma responsiva e “pixel perfect”.</p>
<p></p>
<p><strong>Diferencias de trabalhar conosco:</strong></p>
<p>• Remuneração competitiva;</p>
<p>• Crescimento acelerado dentro da empresa;</p>
<p>• Ambiente aberto para criar e inovar;</p>
<p>• Desbravar um mercado com muitos desafios e ter papel ativo nas soluções;</p>
<p>• Horário Flexível.</p>

## Worked: 
 <p>Somos uma HT Tech de São José dos Campos, cujo principal objetivo é conseguir reduzir a desigualdade de oportunidade para jovens talentos no Brasil, por meio da tecnologia.</p>
</p>

 ## Habilidades: 
 - Bootstrap 
- HTML 5 
- JQuery 
- React.js 
- Vue.js 
- Docker 
- CSS 3
## Local: 
 São José dos Campos
## Requisitos: 
 - HTML5; 
- CSS3 (Flexbox); 
- Bootstrap; 
- React ou VueJs; 
- jQuery (Infelizmente, ou felizmente, esse é nosso legado); 
- Atenção para qualidade de código e design patterns; 
- Versionamento de códigos utilizando Github. 
- Habituado com metodologias ágeis

## Como se candidatar:
Candidate-se em: [Front-End Developer Jr na Worked](https://coodesh.com/vagas/frontend-developer-jr-011142?origin=github&modal=open)
## Tempo médio de feedbacks:
 Costumamos enviar feedbacks em até 48 horas após cada etapa do processo. E-mail para contato em caso de não haver resposta: [gustavogarrett@worked.com.br](mailto:gustavogarrett@worked.com.br)
#### Alocação
Alocado
#### Regime
PJ
#### Categoria
Front-End

**Comment by SaMatheus** [comment]
@gabrielhws  Olá Gabriel, qual seria a faixa salarial?

**Comment by rafaelfgyn** [comment]
A label é alocado mas no título está remoto. É remoto msm?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
