### ISSUE TITLE
[Remoto] Front-end Developer na Sabido

### ISSUE THREAD

**Issue by omrqs** [frontendbr/vagas#4459]
## Nossa empresa

Somos uma empresa com cultura full-homeoffice, inclusiva, aǵil e flexível.

## Descrição da vaga

Temos oportunidade em tecnologia para continuar construindo nossa plataforma de microlearning.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência com Vue e Typescript
- Experiência com Vuex, Vue Router
- Desenvolvimento de componentes
- Vivência com GitFlow, testes, ESlint

**Desejáveis:**
- Nuxt

**Diferenciais:**
- Full-remote (independente da pandemia)
- Flexibilidade de horário

## Contratação

CLT ou PJ, à combinar

## Como se candidatar

Por favor envie um email para vinicius.vaz@talentify.io com seu CV anexado - enviar no assunto: Vaga Frontend

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior

**Comment by RafaPalau** [comment]
Se for possível, tirar a tag JÚNIOR. 
Obrigado.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
