### ISSUE TITLE
[São Paulo] Front-End Developer Noping Tunnel

### ISSUE THREAD

**Issue by dann95** [frontendbr/vagas#446]
## Descrição da vaga
O NoPing Tunnel é uma startup de tecnologia voltada para acelerar a velocidade de internet voltada para jogos online e reduzir o LAG gerado nos mesmos. Somos líderes no mercado brasileiro a quase 4 anos de existência. Contamos com tecnologia própria e única no mercado produzindo sistemas realmente incríveis.

Acreditamos que com o nosso serviço ajudamos diversas pessoas que sofrem com o LAG em seus jogos online favoritos ao redor do mundo, a disputar suas partidas da melhor forma possível e batalhar de forma justa com seus concorrentes.
Descrição da vaga

Estamos em busca de um(a) profissional para atuar no desenvolvimento Front-end.

## Local

Rua Carlito, 635 - Vila Formosa - São Paulo, SP

## Benefícios

- Ambiente descontraído e informal :)
- Horário flexível
- Eventos e happy hours
- Possibilidade de promoções

## Requisitos

**Obrigatórios:**
- HTML5, CSS, JavaSscript
- O básico de Node.JS

**Desejáveis:**
- Gulp/Grunt

**Diferenciais:**
- PHP
- MYSQL

## Contratação
PJ - Pessoa Jurídica

## Como se candidatar
Por favor envie um email para thomas@nptunnel.com com seu CV em anexo, e a pretensão salarial - enviar no assunto: Vaga Dev Front

**Comment by thenewbiemaster** [comment]
tem possibilidade de ser remoto? apenas PJ? (pergunta apenas)

**Comment by dann95** [comment]
Apenas presencial, e sim, apenas pj. Caso esteja interessado, podemos fazer uma entrevista por skype, e conversar.

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by dann95** [comment]
@LFeh infelizmente não, caso haja necessidade outra vez, voltaremos.

obg e abç.
