### ISSUE TITLE
[Remoto] Front-end Developer Angular/React na Adroit Robotics

### ISSUE THREAD

**Issue by jgurzoni** [frontendbr/vagas#4464]
## Nossa empresa

A Adroit Robotics desenvolve softwares disruptivos de IA e sensores avançados para o monitoramento totalmente automatizado de pomares, aumentando a produtividade e detectando deficiencias em campo. Nossos clientes sao os maiores produtores de frutas do mundo. www.adroitrobotics.com

## Descrição da vaga

Buscamos por Front-end Developers (Angular, NodeJs, Python) para nossa equipe de R&D e engenharia, que atualmente trabalha em tecnologias inovadores de análise de imagens e fusão de sensores, em um ritmo acelerado. 
O candidato selecionado participará do desenvolvimento dos dashboards para os clientes em interfaces responsivas e repletas de gráficos e visualizações de dados. O selecionado será responsável por escrever código de qualidade para uso em produção, conduzir revisões de codigos e trabalhar em conjunto com a equipe de engenharia do produto.

## Local

Remoto, caso o contratado prefira, pode vir ao nosso escritório em Sao Paulo, Itaim Bibi, quando quiser.

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Node, Javascript e Typescript
- 2 anos de experiência com Angular ou React
- Experiência no consumo de RESTful APIs
- Experiência na criacao de UX and UI de alta qualidade
- Experiência em trabalhar em ambientes Linux
- Experiência em trabalhar com metodologias Agile
- Habilidades em solução de problemas e trabalho em equipe

**Desejáveis:**
- proficiência em SQL
- proficiencia em Python
- experiência na implementacao de unit tests e CI/CD

**Diferenciais:**
- startup em expansão, trabalho com tecnologia inovadora
- potencial de stock option

## Benefícios

- Plano de saúde
- Até 2 salários ao ano de bonus por metas atingidas 

**Diferenciais:**
- horarios flexiveis
- ser parte de equipe de engenheiros e cientistas da computacao com vasta experiencia em IA

## Contratação

CLT ou PJ, a combinar

## Como se candidatar

Por favor envie um email para contact@adroitrobotics.com com seu CV anexado - enviar no assunto: Vaga Front-End

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.
E-mail para contato em caso de não haver resposta: contact@adroitrobotics.com

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
