### ISSUE TITLE
Desenvolvedor Full Stack @ CONSTRUCODE #vagasbyintera

### ISSUE THREAD

**Issue by LayconJ0hn** [frontendbr/vagas#4465]
## Nossa empresa

Aqui na ConstruCode somos uma startup que nasceu para transformar o ramo de engenharia civil. Trazemos inovação através de QRCodes posicionados estrategicamente pela obra, facilitando a visualização, acompanhamento e comunicação no projeto.

## Descrição da vaga

Estamos buscando alguém inovador, dinâmico que possa atuar no Desenvolvimento Full Stack para ajudar a digitalizar o canteiro de obras por meio de celulares e tablets. 

## Local

Presencial, SÃO PAULO, SÃO PAULO.

## Requisitos

**Obrigatórios:**
-  Domínio de .NET
- Domínio do Bootstrap
- Conhecimento em MySQL
- Proficiência em HTML e CSS 
- Experiência com AWS
- Experiência com API REST

**Desejáveis:**
- Experiência com Flutter
- Experiência com Desing responsivo

**Diferenciais:**
- Auto gerenciamento
- Ser inovadora e dinâmica

## Como se candidatar

Para se inscrever, basta preencher o formulário através do link: byintera.in/2f2

#### Alocação
- Alocado presencialmente pós pandemia

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
