### ISSUE TITLE
São Paulo - Front-end Developer na iProduce

### ISSUE THREAD

**Issue by iproduce** [frontendbr/vagas#4466]
Descrição da vaga
São duas vagas, uma para a cidade do Rio de Janeiro (região da Barra) e outra para a cidade de São Paulo (região da Vila Leopoldina). Os profissionais precisam ter experiência em produção de: banners de internet, landing pages, sites e hot-sites, e-mails marketing. 

Local
A empresa fica em São Paulo e 

Requisitos
É necessário ter conhecimento avançado em: HTML5, CSS3, Javascript, React, Wordpress.

Desejáveis:
É um diferencial conhecer as seguintes ferramentas: Google WebDesign, Adobe Animate e Adobe Photoshop.

Contratação
PJ
O salário é R$ 4000,00

Como se candidatar
Por favor envie um e-mail para freela@iproduce.com.br com seu CV e portfólio - enviar no assunto: Front-end Developer

Labels
Alocado (não aceitamos remoto)
PJ
Pleno
Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
