### ISSUE TITLE
[Remoto] Front-end React.js Developer na TeamHub

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#4467]
## Descrição da vaga: 
 <p>Somos um Hub de tecnologia que <strong>DESCOMPLICA </strong>a gestão de cultura para <strong>CONECTAR </strong>pessoas e <strong>MULTIPLICAR </strong>resultados.</p>
<p>O nosso foco é criar um ambiente onde a gestão da cultura seja fácil, acessível, dinâmica e de todos.</p>
<p><strong>Regime de contratação</strong></p>
<p>CLT</p>
<p></p>
<p><strong>Atividades</strong></p>
<ul>
<li>Desenvolvimento Backend em Node.js</li>
<li>Desenvolvimento Frontend com React.js (Class e Functional components)</li>
<li>Participar de propostas de arquitetura de solução</li>
<li>Participar ativamente das reuniões de refinamento, planejamento e dailys</li>
</ul>
<p></p>

## TeamHub: 
 <p>Somos um Hub de tecnologia que <strong>DESCOMPLICA </strong>a gestão de cultura para <strong>CONECTAR </strong>pessoas e <strong>MULTIPLICAR </strong>resultados.</p>
<p>O nosso foco é criar um ambiente onde a gestão da cultura seja fácil, acessível, dinâmica e de todos.</p><a href='https://coodesh.com/empresas/teamhub'>Veja mais no site</a>

 ## Habilidades: 
 - React.js 
- Typescript 
- Node.js 
- Sequelize
## Local: 
 100% Remoto
## Requisitos: 
 - Frontend: React.js (Redux, Ant Design) 
- Backend: Node.js / Typescript (Express, Sequelize)

## Benefícios: 
 - Horário Flexível 
- Plano de Saúde 
- Seguro de Vida 
- Vale Alimentação
## Como se candidatar:
Candidate-se em: [Fullstack Node.js + React.js Developer na TeamHub](https://coodesh.com/vagas/fullstack-nodejs-reactjs-232931?origin=github&modal=open)
## Tempo médio de feedbacks:
 Costumamos enviar feedbacks em até 48 horas após cada etapa do processo. E-mail para contato em caso de não haver resposta: [contato@teamhub.com.br](mailto:contato@teamhub.com.br)
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Full-Stack

**Comment by Marcosnto** [comment]
A descrição da vaga está bem confusa. No título tem front-end, mas na descrição a categoria está fullstack.
