### ISSUE TITLE
[REMOTO] Front-end Developer no Vagalume

### ISSUE THREAD

**Issue by lafraia** [frontendbr/vagas#4468]
## Descrição da vaga

Estou buscando profissionais que possam fazer parte de uma equipe remota para vários projetos no [Vagalume](https://www.vagalume.com.br/). Já temos algumas tarefas bem interessantes prontas para iniciar o desenvolvimento, mas boa parte do trabalho neste início é refatoração, otimização e ganho de confiança (qualidade, prazo e tempo de execução). Teremos melhorias no CMS interno, otimização de carregamento do site, automação, criação de testes, desenvolvimento do app e muitas outras coisas.

O foco é encontrar pessoas **bem** proativas, experientes, autodidatas, auto-motivadas e que possam executar as tarefas com bastante paixão, rapidez e com qualidade técnica. 💪

Também estamos procurando pessoal focado em backend (fullstack) https://github.com/backend-br/vagas/issues/4625

## Local

100% Remoto! 🙏

## Requisitos

**Obrigatórios:**
- 4 anos de experiência com HTML5 e CSS3 (avançado)
- 4 anos de experiência com PHP
- 3 anos de experiência com Javascript / NodeJS
- 1 ano de experiência com VueJS
- Experiência anterior com trabalho remoto
- Foco em qualidade do resultado final
- Experiência com sites responsivos

**Desejáveis:**
- conhecimentos sólidos na [semântica do html5](https://www.semrush.com/blog/semantic-html5-guide/) (leia também [este artigo](http://html5doctor.com/avoiding-common-html5-mistakes/))
- conhecimentos AWS e Docker

## Contratação

PJ fixo mensal

## Nossa empresa

Você já deve ter buscado uma letra de música no Vagalume, chegou a hora de poder contribuir com o projeto ;-)

## Como se candidatar

Por favor envie um email para rh@vagalume.com.br com seu CV anexado - enviar no assunto: **Vaga Frontend** e responder as perguntas abaixo:

* Quanto tempo você tem disponível por semana?
* Qual é o melhor horário do dia que você tem a disponibilidade?
* Qual experiência anterior com trabalho remoto?
* O que você busca no seu desenvolvimento profissional?
* Qual sua experiência com (favor elaborar a resposta):
    * AWS (quais serviços usou?)
    * Javascript
    * PHP
    * VueJS
    * React
    * Sites responsivos
    * PHP
* Por que você acha que deve ser escolhido?
* Tem algum projeto pessoal que vale a pena mencionar?
* Como é o seu ambiente de desenvolvimento? SO, conexão, ambiente calmo, etc?
* Qual sua pretensão de valor mensal para dedicação tempo integral?

Se achar interessante compartilhar outras informações, pode mandar.

## Labels

- Remoto
- Freela
- PJ
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
