### ISSUE TITLE
[Global] Front-end Developer na Wavy Global

### ISSUE THREAD

**Issue by Fabicaneyu** [frontendbr/vagas#4471]
> Vaga Remota durante a pandemia

## Nossa empresa

O {DE}CODE  to Empower é uma iniciativa da Wavy, criada para promover a diversidade de gênero nas nossas áreas de tecnologia! Com foco na contração de mulheres e pessoas não binárias. 

Não importa quem você seja, ou em que lugar do mundo você esteja, procuramos pessoas que, como nós, queiram ser agentes de mudança para promover a diversidade de gênero em ambientes de tecnologia.

Com oportunidades em Frontend, garantimos que pessoas de diferentes origens se sintam parte de nossa jornada, construindo um ambiente cada vez mais diverso e inclusivo para que possam desenvolver os projetos mais significativos das     suas carreiras.

Não se preocupe em não ter conhecimento de todos os requisitos! Se necessário, teremos uma etapa de mentoria específica para conectar você com as ferramentas que usamos e especialistas das nossas áreas!

## Descrição da vaga

Oportunidades para atuação nos times de Produto - O time de Produto trabalha junto com outros times para proporcionar a melhor experiência aos nossos clientes e usuários ou time de Engenharia - Atuar com desenvolvimento de aplicações web e software. Analisar requisitos, ajudar na arquitetura de software, investigações de problemas/bugs, testes automatizados, implantações, análise e acompanhamento de resultados. 

## Local

Remoto 

## Requisitos

**Obrigatórios:**
- Desempenho de HTML, CSS e JavaScript
- Desenvolvimento de aplicativos com Vue, Angular ou React
- NPM / Node como uma ferramenta de construção.
- Conhecimento em RESTful e consumo de serviços RESTful

**Diferenciais:**
- Noção de Java ou NodeJS
- Teste automatizado
- Jenkins para automação de construção / testes e implantação
- Conhecimento do Google Cloud

## Benefícios

- Life at Wavy
- Para você
- Saúde & cuidado
- Cuidado familiar

## Contratação

CLT

## Como se candidatar

Pessoa Desenvolvedora de Frontend | Nível Pleno 
Inscrições:https://grnh.se/8ecb6f162us

Pessoa Desenvolvedora de Frontend | Nível Sênior
Inscrições: https://grnh.se/f513271d2us

Pessoa Desenvolvedora de Software, Chatbot | Nível Sênior
Senior Frontend | Chatbot | {DE}Code to Empower
Inscrições: https://grnh.se/51ff5ccb2us

## Tempo médio de feedbacks
As inscrições se encerram no dia 21/03. Início previsto para 20/04. 

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
