### ISSUE TITLE
[Maceió/Remoto] Front-end Developer na Weni

### ISSUE THREAD

**Issue by marianacruzs** [frontendbr/vagas#4473]
## Nossa empresa

A Weni Plataforma é uma ferramenta intuitiva para a criação de chatbots robustos que demandam integrações e inteligência artificial complexas. Os chatbots Weni são personalizados e facilmente integráveis a outros sistemas por meio de API.

Nossa plataforma tem o poder do Weni NLP, sistema de processamento de linguagem natural, campo da Inteligência Artificial responsável por fazer com que as máquinas compreendam as intenções das pessoas através do treinamento de frases.

## Descrição da vaga

Como Pessoa Desenvolvedora Front-End, você terá como missão desenvolver aplicações, features ou resolver bugs de aplicações mantidas pela Weni. Irá definir a arquitetura e funcionalidades das aplicações, nos ajudando nas principais decisões técnicas e seus impactos no produto no médio/longo prazo.

Será sua responsabilidade:

- Desenvolver novas interfaces gráficas;
- Realizar otimizações de performance de ferramentas existentes;
- Realizar consultas a APIs (Interface de Programação de Aplicativos);
- Realizar integrações de sistemas de Login;
- Elaborar manual para utilização de ferramentas;
- Documentar algoritmos no código;
- Escrever código bem projetado, testável e eficiente.

## Local

Remoto

## Requisitos

- Experiência com HTM5, CSS3 e Javascript
- Experiência com Frameworks Javascrit (Vuejs)
- Nível de Inglês Intermediário
- Estar cursando ou ser graduado em Análise de Sistemas, Ciências da Computação, Engenharia da Computação ou áreas afins
- Conhecimento prévio com JWT
- Conhecimentos de REST API
- Conhecimentos de Testes unitários
- Experiência com State Management (Ex: Redux, Mobx, Vuex, Recoil)
- Experiência com git
- 2+ anos de experiência em desenvolvimento de software front-end

## Benefícios

- Faixa Salarial de R$3.600,00 à R$4.500,00 (Pleno).
- Vale Alimentação ou Refeição
- Plano de Saúde

**Diferenciais:**

- Uma startup que preza pela diversidade e o trabalho em equipe.
- Um time que respira tecnologia.
- Cultura de feedback e desenvolvimento com acompanhamento mensal da sua liderança.
- Uma oportunidade de crescimento profissional com plano de cargos e salários.
- Modelo de trabalho remoto.
- Horários Flexíveis

## Contratação

CLT

## Como se candidatar

Inscreva-se no link: https://weni.gupy.io/jobs/747334?jobBoardSource=gupy_public_page

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@weni.ai

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
