### ISSUE TITLE
[São Gonçalo/RJ] Front-end Developer na Autum

### ISSUE THREAD

**Issue by hafael** [frontendbr/vagas#4474]
## Nossa empresa

Autum é uma empresa fundada no Rio e entrega aplicações de alto desempenho na nuvem para negócios que demandam informação de qualidade para tomada de decisão.

## Descrição da vaga

Oportunidade para Front-end Developer Pleno+

Autum está selecionando para o time de desenvolvimento web de uma grande rede varejista de supermercados. O profissional será contratado(a) pelo cliente e atuará suportando as demandas internas da empresa, trabalhando em conjunto, através de metodologias ágeis, divididas em pequenas entregas a partir de metas e prazos.
Você deve se sentir confortável trabalhando como parte de uma equipe e, ao mesmo tempo, tomar a iniciativa de liderar novas inovações e projetos transferindo conhecimento aos outros colaboradores.

## Local

Exemplo: Remoto ou Escritório, RJ, São Gonçalo, Arsenal

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com Javascript
- 2 anos de experiência com Angular, Vue ou React
- código testado
- CSS e pré-processadores
- entrega contínua

**Desejáveis:**
- conhecimentos em consumo de APIs
- conhecimentos em protocolos de autenticação
- conhecimentos em configuração de cache

**Diferenciais:**
- projetos opensource
- experiencia com e-commerce

## Benefícios

- VT
- VR

## Contratação

CLT
PJ (remoto em demandas pontuais)
Salário à Combinar

## Como se candidatar

Por favor responda ao formulário do google ou envie as respostas para rafael@autum.com.br com o título da vaga "Processo seletivo Front-end Developer": https://forms.gle/nk7nWsCwWxpknKt28

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- Freela
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
