### ISSUE TITLE
[São Paulo] Front-End Developer Ninja / Senior na Jexia

### ISSUE THREAD

**Issue by willgm** [frontendbr/vagas#448]
# Front-end Developer Ninja / Senior

## Descrição da vaga

Estamos procurando por Engenheiros de Software com excelentes skills em programação, para se juntar ao nosso time, com capacidade de criar aplicações de alta qualidade. O candidato ideal deve ter experiência na construção de produtos reais para a web e ter meios de apresentar exemplos do seu trabalho.

## Responsabilidades

Você irá colaborar na especificação, design e desenvolvimento de software de acordo com os requisitos do produto, que demanda um alto comprometimento com diferentes áreas da arquitetura, trabalhando em equipe, comunicando progressos e riscos ao time 
- Criar novas funcionalidades, assim como manter as existentes;
- Participar ativamente no design técnico e arquitetura das soluções;
- Escrever documentação técnica;
- Participar em code reviews;
- Prototipar novas funcionalidades e redesenhar outras;
- Corrigir bugs.

## Local

Escritório no bairro de Pinheiros em São Paulo, ao lado da estação Faria Lima da linha amarela do metrô.

## Benefícios

- Horário flexível
- Ambiente descontraído e informal
- Contato diário com o escritório na Holanda
- Oportunidade de crescimento junto com a empresa no Brasil

## Requisitos

**Obrigatórios:**
- Graduação em Ciência da Computação ou experiência equivalente;
- Inglês nível intermediário ou avançado;
- 6+ anos de experiência com tecnologias web;
- Vasta experiência com Javascript puro;
- Atualizado com a evolução do ECMAScript;
- Vasto conhecimento em semântica HTML e CSS;
- Atualizado com a evolução das API’s do HTML5 e features do CSS3+;
- Vasto conhecimento em web services e API’s;
- Boa compreensão de testes e debugging em browsers;
- 2+ anos de experiência com frameworks JS modernos;
- Experiência com testes automatizados e TDD;
- Experiência com websites otimizados para dispositivos móveis;
- Conhecimento de princípios de SEO;
- Experiência com Git e workflows;
- Comprometimento com qualidade e performance de software.

**Desejáveis:**
- Experiência com TypeScript e Angular 2+;
- Experiência com programação funcional e reativa;
- Experiência com Back-end, principalmente usando Golang e NodeJS;
- Participação ativa em comunidades de desenvolvimento de software;
- Ser um contribuidor Open Source.

## Contratação

CLT

## Nossa empresa

Jexia is a platform for developers, by developers: a better way to build software. No shortcuts. No workarounds. What we offer is a wide range of services, developed in-house and integrated into a single platform. That means you'll need less code for the same professional result. And because it's horizontally scalable by design, the sky really is the limit.

## Como se candidatar

Utilize seguinte link:
https://jexiabr.recruitee.com/o/engenheiro-frontend-senior

**Comment by kivervinicius** [comment]
Uau

**Comment by willgm** [comment]
Processo ainda esta de pé galera! :rocket:
