### ISSUE TITLE
[Fortaleza] Front-end Developer na Desenrolado

### ISSUE THREAD

**Issue by fcoalcantarajr** [frontendbr/vagas#4480]
> Vaga Remota durante a pandemia

## Nossa empresa

A Desenrolado é uma produtora de conteúdo educacional, startup cearense fundada em 2014, com o propósito de aumentar e despertar o interesse dos alunos por aprender.
Para entregar conteúdo de qualidade, precisamos contar com times operacionais extraordinários :D. Como forma de garantir entregas em tempo hábil para os nossos clientes, temos uma dinâmica interna de contratação por projetos, de acordo com as demandas e fechamentos de novos contratos. 

Por conta dessa dinâmica, nós abrimos um banco de talentos fixo, que tem como objetivo manter em nosso radar os dados de pessoas interessadas em contribuir para a educação através da produção de conteúdo educacional, e fazer parte dos nossos squads de projetos.

## Descrição da vaga
O Desenvolvedor (a) front-end desenvolve as interações e o layout que foi desenhado do produto, implementa a interface se preocupando com a usabilidade. Planeja, constrói e dá manutenção para produtos referentes aos nossos objetos interativos. Esse profissional desenha aplicação por linha de código, cria esqueleto de programação, cuida de toda a parte de estrutura visual dos nossos produtos interativos. Sua atuação envolve gerenciamento, e acompanhamento das atividades e entregas do time envolvido com objetos interativos.

## Local

- Remoto durante pandemira
- Escritório localizado em Fortaleza, Ceará
## Requisitos

**Obrigatórios:**
HTML5 
CSS3
JavaScript
Noções de SCORM 1.2 e/ou 2004 
Noções de LMS 
Noções de metodologias de projeto

**Desejáveis:**
Noções básicas de design de interfaces e experiência do usuário

## Contratação

PJ a combinar.

## Como se candidatar

Inscreva-se [neste link](https://docs.google.com/forms/d/e/1FAIpQLSdWtUGc0v3Yt6hIKoJf4jntTyMq2pmpceRXwGY_Aw2pdL9NxA/viewform?fbzx=1254440148739324961).

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até XX dias após cada processo.
E-mail para contato em caso de não haver resposta: feedbacks@empresasuperlegal.com.br

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Júnior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by fcoalcantarajr** [comment]
A vaga continua ativa!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
