### ISSUE TITLE
[São Paulo] Front-end Developer na ADDI (startup Colombiana)

### ISSUE THREAD

**Issue by rodrigogama** [frontendbr/vagas#4485]
> Vaga Remota durante a pandemia

## About us

We are a technology company working to transform credit and banking in Latin America starting with point of sale finance. We aim to build fair, simple and affordable financial services that empower our clients, treating them with dignity, and building financial freedom. We launched in February 2019 and have already served thousands of clients and disbursed millions of dollars. 

We operate as a full stack startup. We have built our core systems and processes from scratch, and we believe our technology and analytics platform will drive our progress into the years to come. We come at this with deep experience building and growing technology teams and financial products. As important as what we do is how we do it. We are a conscious company, and are deeply committed to working and living our five core values - A company of owners inspiring colleagues, we pull rabbits out of hats, we care and we trust, act with integrity, win today every day, and scale exponentially 

We are backed by Andreessen Horowitz, Monashees, Village Global, and an outstanding team of individual angels, including Kevin Ryan, Josh Abramowitz, and Scott Weiss.

## Requirements
- You have 3+ years of full time technical work experience as a software engineer
- Great communication abilities with technical and non-technical stakeholders.
- Willingness to work with a distributed team.
- Good foundations in UX/UI design.
- Strong expertise building user interfaces using well-structured HTML and CSS code.
- Experience with modern JavaScript libraries and tools.
- Awareness of web performance optimization techniques.

## Benefits

- Generous compensation
- Equity
- Bradesco 100% health insurance (and 90% for dependents), 
- Meal allowance (VR and VA)
- VT or transportation assistance

**Diferenciais:**
- English classes (in house teacher)
- Learning budget
- Home office support

## Hiring process
- Meet with our recruiter for a 30-minute video chat. In this interview, we will get to know you better, understand what you’re looking for and answer any questions you might have about ADDI.
- Meet with an ADDI engineer for a 45-minute video chat interview. Here we will ask you questions about your technical background and basic computer science concepts. You will be able to ask any questions about the culture and how we work at ADDI.
- Complete a simple take-home exercise within a 1-week window. With this technical challenge, we want to see your technical expertise solving a real world problem. We expect that you invest 5 hours or less developing a working solution.
- Meet with our head of engineering (and potentially one additional engineer) for a 45-minute chat to talk about your work experience, your take-home exercise submission and any questions you might have.
- Meet with our CEO for a 30-minute chat to talk about the vision of the company, what we are building and how you will contribute to our product.

## Contratação

CLT

## How to apply

Please, apply [here](https://jobs.lever.co/addi/4c524024-d74c-4809-bf8b-51baa388c153). Feel free to contact me if you have any questions!

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
