### ISSUE TITLE
[Remoto] Front-end Developer na @Mazzatech

### ISSUE THREAD

**Issue by LuNogueira** [frontendbr/vagas#4489]
## Nossa empresa

Criamos oportunidades de trabalho para os profissionais de TI, dando suporte necessário para que executem um bom trabalho e atendam com excelência nossos clientes.

## Descrição da vaga

Atuação com desenvolvimento Web para um grande cliente de hospedagem de sites líder no Brasil e América Latina.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 4 anos de experiência com HTML5, CSS3 e JS
- 2 anos de experiência com Vue.js, React ou Angular

**Desejáveis:**
- Experiência com a arquitetura Flux (Vuex, Redux ou NgRx)

## Contratação

PJ - 50/h - 70/h

## Como se candidatar

Por favor envie um email para lucas@mazza.tech ou matheus.rubio@mazza.tech com seu CV anexado - enviar no assunto: Vaga Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.
E-mail para contato em caso de não haver resposta: lucas@mazza.tech ou matheus.rubio@mazza.tech

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
