### ISSUE TITLE
[Recife] Front-End Developer na Epitrack

### ISSUE THREAD

**Issue by jgabriellima** [frontendbr/vagas#449]
# Desafio

Estamos buscando um FrontEnd Software Engineer apaixonado por tecnologia e que não tenha medo de criar soluções inovadoras para problemas diversos e colocar a mão na massa. Procuramos aqueles que não esperam acontecer, que são proativos e gostam principalmente de resolver problemas desafiadores.

# O que você vai fazer?

Você vai atuar na concepção e desenvolvimento de nossas aplicações mobile utilizando React Native e nosso dashboard. Terá a oportunidade de interagir com um time multidisciplinar, utilizando as mais modernas tecnologias, em uma empresa SSB - Science Based Business.

# Requisitos:

- React Native
- Domínio de interação com APIs de terceiros
- Facebook SDK
- Flexbox
- Paixão por trabalhar em um ambiente de startup, com capacidade de entregar rápido e com qualidade.
- Ter um perfil empreendedor, ser dinâmico e proativo.

# Diferenciais:

- Tiver experiência em desenvolvimento de soluções backend.
- Conhecimentos em Ciência de Dados e Aprendizagem de Máquina

**Regime de Contratação:** CLT

# Benefícios

- Vale-transporte
- Plano de saúde 
- Vale-refeição
- Ambiente descontraído
- Projetos internacionais

# Local

R. Alfredo Coutinho, 74. Sala 201.  Poço da Panela, Recife - PE, 52061-130 

# Enviar currículo para: ninjas@epitrack.tech

**Comment by neysimoes** [comment]
Empresa e equipe incrível! Altamente recomendado! 😄

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
