### ISSUE TITLE
[REMOTO] Front-end Developer no DOT digital group

### ISSUE THREAD

**Issue by gabriela-amancio** [frontendbr/vagas#4490]
Somos o **DOT digital group** e a educação é o nosso negócio! Somos especialistas em **EdTech - Education Technology.** Aqui a tecnologia e a educação caminham juntas. A transformação que a educação promove é grande! Os nossos números e desafios também!

## Descrição da vaga
Precisamos de alguém que queira aprender sempre, que tope encarar desafios e que seja proativo. Precisamos de uma pessoa que seja fera em Front End para atuar no **time de Marketing!** 

**As principais atividades serão:**

- Garantir a estabilidade e alta performance de nossos sites;
- Implementar layouts em landing pages Wordpress;
- Integrar ferramentas e forms de inbound com WP;
- Criar e otimizar Plugins e templates em Wordpress - com foco na geração de leads;
- Realizar integração com APIs;
- Criar planos para desenvolvimento do SEO no ambiente.

## Local de trabalho

100% Remoto
Escritório da empresa localizado em Florianópolis - SC 

## Requisitos da vaga

**Obrigatórios**

- Conhecimentos Javascript;
- Conhecimento de HTML5 e CSS3;
- Experiência com softwares open source de CMS Wordpress, Craft, plugins e templates;
- Conhecimento em ElementorPro;

**Desejáveis**

- Noções de CMS Craft;
- Noções de UX e UI;

## Forma de contratação

PJ ou CLT

## Benefícios da empresa
- R$2.000,00 de verba para treinamento e desenvolvimento em 2021 (a empresa disponibiliza esse valor para que você invista em melhorias no seu aprendizado técnico)
- Contratação Home Office
- Horário flexível,
- R$528,00 de VR/VA, você ajusta como preferir
- Convênio médico com cobertura nacional sem custo
- Convênio odontológico
- Convênio de farmácia
- Auxílio-pandemia R$100,00
- Remuneração alinhada com o mercado 
- Trabalhar com tecnologia de ponta e uma equipe maravilhosa com quem você vai ter a possibilidade de aprender e ensinar todos os dias ;) 

## Sobre a empresa

Com mais de 24 anos de atuação, somos um dos maiores grupos nacionais de educação digital e pioneiros no mercado de Educação Comunicacional no país. Possuímos sede em Florianópolis, polo tecnológico no estado de Santa Catarina, temos escritórios também em São Paulo e Brasília. No mercado internacional, temos operação em Lisboa, Portugal.

## Como se candidatar

Candidate-se diretamente em nosso site: https://dotgroup.enlizt.me/vagas/desenvolvedor-a-_front_end_-_marketing-120321
Nesse primeiro momento iremos pedir suas informações pessoais (você pode importá-las diretamente do LinkedIn) e em seguida enviaremos as próximas etapas do processo que consistem em mapeamento cultural, avaliação de portfólio e entrevista. 

Ou envie um e-mail para gabriela.souza@dotgroup.com.br com seu CV anexado - Enviar no assunto: Vaga FRONT - MKT 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada etapa do processo.

## Labels

- CLT
- PJ
- Pleno
- Javascript 
- Wordpress 
- HTML5

- Remoto
<!--- Informar abaixo o nome do estado por extenso.
- Brasil 
- Santa Catarina

**Comment by XLucifer** [comment]
Boa tarde, por acaso não tem vaga no Marketing, para quem têm experiência no front ( 13 anos ) , mas deseja trabalhar em MKT( formado em MKTdigital) ?

Abraços

**Comment by gabriela-dot** [comment]
@XLucifer Oi André! Agradeço por seu contato!
No momento não temos outras vagas abertas no time de marketing :/ 
Mas como estamos em expansão, teremos várias oportunidades novas ainda nesse primeiro semestre ;) 
Fique de olho em nossa página de carreiras: https://web.enlizt.com/app/dashboard/home e me acompanhe no Linkedin também https://www.linkedin.com/in/gabriela-amancio/

**Comment by XLucifer** [comment]
> @XLucifer Oi André! Agradeço por seu contato!
> No momento não temos outras vagas abertas no time de marketing :/
> Mas como estamos em expansão, teremos várias oportunidades novas ainda nesse primeiro semestre ;)
> Fique de olho em nossa página de carreiras: https://web.enlizt.com/app/dashboard/home e me acompanhe no Linkedin também https://www.linkedin.com/in/gabriela-amancio/

Ok, mto obrigado
