### ISSUE TITLE
[Porto Alegre] Front-end Developer (E-commerce) na Muv Recursos Humanos

### ISSUE THREAD

**Issue by robertafonseca** [frontendbr/vagas#4493]
>

## Muv Recursos Humanos

**Atuação presencial, sem possibilidade de Home Office!**

## Descrição da vaga

- Desenvolvimento Front-end;
- Atuar no desenvolvimento de sistemas e sustentação do e-commerce com equipes internas e externas;
- Dominar o ciclo de vida da aplicação no que tange versionamento, desenvolvimento, integração, testes e deploy.

## Local

Porto Alegre, RS - Bairro Higienópolis

## Requisitos

**Obrigatórios:**
- **HTML, JavaScript, React e/ou Vue, CSS**;
- Experiência em projetos que aplicam Metodologias Ágeis.

**Desejáveis:**
- Ensino Superior Completo ou em finalização em áreas da Tecnologia da Informação ou afins;
- Noções de desenvolvimento para Cloud (preferencialmente Azure);
- Noções de SEO e otimização para motores de busca;
- Experiência no desenvolvimento para plataformas de E-commerce (VTEX é um grande diferencial);
- Noções de desenvolvimento de templates VTEX (será um diferencial);
- Inglês Intermediário.

## Benefícios

- Vale-transporte;
- Refeitório no local;
- Plano de saúde Unimed (após contrato de experiência);
- PPR (após um ano de empresa).

## Como se candidatar

Por favor envie um email para cv@muvrh.com.br com seu CV anexado - enviar no assunto: 0854 - Front-end Developer.

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by robertafonseca** [comment]
@felipefialho na verdade a vaga é Presencial e para Porto Alegre (RS) - é possível alterar as labels?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by robertafonseca** [comment]
A vaga segue em aberto.

**Comment by robertafonseca** [comment]
Fechamos a vaga \o/
