### ISSUE TITLE
[Remoto] Python + React Developer @ Finetune Learning (US)

### ISSUE THREAD

**Issue by tyagow** [frontendbr/vagas#4498]
## Nossa empresa

https://www.finetunelearning.com/custom.html

## Descrição da vaga

Finetune procura desenvolvedores Python com habilidades em React para trabalhar em um projeto inovador usando OpenAI.
Você sera gerenciado por um Brasileiro portando não precisa ser 100% proficiente em Inglês.
Inicialmente projeto com duração de 6-8 meses com possibilidade de extensão de contrato para tempo indeterminado. (Melhorar a comunicação em Inglês fundamental para essa extensão)
Se você é um desenvolvedor com vontade de crescer rápido, evoluir seu inglês e trabalhar com um tecnologias de ponta, envie seu currículo para tiago@finetunelearning.com e vamos conversar!

## Local

Remoto 

## Requisitos

**Obrigatórios:**
- 1 ano de experiência com desenvolvimento React
- 1 ano de experiência com desenvolvimento Python
- Habilidade de escrever código em inglês
- Ser capaz de ler tickets em Inglês

**Desejáveis:**
- Conhecimentos em GraphQL
- Hasura

**Diferenciais:**
- Ingles Fluente

## Benefícios

- Pagamento em dolar

**Diferenciais:**
- Horario Flexivel
- Oportunidade de desenvolvimento de carreira

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para tiago@finetunelearning.com com seu CV anexado - enviar no assunto: Vaga React + Python
## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by fogeid** [comment]
Nossa, que vaga legal!
