### ISSUE TITLE
[100% Remoto] Senior React Js Developer na Robert Half

### ISSUE THREAD

**Issue by LiviaMaron** [frontendbr/vagas#4499]
## Nossa empresa

A Robert Half combina profissionais de TI com algumas das melhores empresas em caráter temporário, de projeto ou em período integral. Desde funções em software e aplicativos até infraestrutura e operações de TI, fornecemos acesso sem paralelo a emocionantes oportunidades de carreira. Nossa abordagem personalizada, tecnologia inovadora de correspondência e rede global com experiência no mercado local ajudam a encontrar rapidamente os trabalhos de tecnologia que correspondem às suas habilidades e prioridades. Ao trabalhar conosco, você tem acesso a oportunidades desafiadoras, remuneração e benefícios competitivos e treinamento para aprimorar seu conjunto de habilidades.

## Descrição da vaga
 
Atuar alocado 100% remoto em squad com foco no desenvolvimento e aprimoramento de produtos em um dos maiores e-commerce de móveis e artigos de decoração do país, 

## Local

100% remoto até depois da pandemia.

## Requisitos

Experiência de mercado com:
-  JavaScript;
-  React Js;
-  Consumo de APIs.

Diferencial: experiência com Typescript e Next js
 
## Benefícios

- Assistência Médica (s/ dependente) e Odonto Executivo (s/ dependente)
- Seguro de Vida
- Vale Refeição (R$ 660,00)
- Vale Alimentação (R$ 150,00)

## Contratação

Contratado como CLT Robert Half e depois de alguns meses, há uma grande oportunidade de ser internalizado pelo cliente.

Salário com base de Curitiba/Paraná.

## Como se candidatar

Interessados deverão enviar o currículo para livia.mello@roberthalf.com.br ou se candidatar através do nosso site: https://www.roberthalf.com.br/vagas/tecnologia

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
