### ISSUE TITLE
[Ribeirão Preto ou REMOTO] Frontend Developer (React/Redux)

### ISSUE THREAD

**Issue by renanvalentin** [frontendbr/vagas#45]
## Descrição da vaga

Crave Food Services is an innovation & technology company specialized in generating efficiency in the food service industry. Our product WhatsGood is an online marketplace that connects chefs and local food purveyors.

Purveyors find at WhatsGood a place to showcase and offer their products to purchasers, while efficiently managing their ordering process.

Purchasers find at WhatsGood a place to connect with purveyors and organize their local purchasing.

We currently have an office in Providence (RI – USA) and we are just opening a new office in Ribeirão Preto (SP – Brazil). While this position is for the Ribeirão Preto office there is no problem if you prefer to work remotely.

Are you able to understand backend developers and UX designers? Can you put their work together to make beautiful and useful applications? Then you should apply to work with us! Independently of the position we expect that everyone involved in the development process be interested in the whole stack and product – there is no part of the system that is somebody's else problem.

## Local

While this position is for the Ribeirão Preto office there is no problem if you prefer to work remotely.

## Requisitos

At Crave we use React, Redux, Webpack and other great tools available in JS world! 

Some skills we would like to see in our candidates:

- User Interface design and development
- Good understanding of git
- Pixel perfect eye
- Ability to multi-task and work under pressure
- Passion for technology and high quality engineering
- Be able to build custom UI and animation
- Strong skills on Unix/Linux environment
- Familiar with agile principles
- Know about automated building, deployment and testing (karma, mocha, sinon, chai, and the list goes on)
- Deal with cross browser compatibility
- Be able to build an app without left-pad
- Know about coding/designing strategies and methods (TDD, SOLID, Clean Code, etc) 

## Contratação

PJ a combinar

## Como se candidatar

https://crave.workable.com/jobs/171277

**Comment by willianjusten** [comment]
Looks great =)
But I have something to ask, about the salary, will be in Dollars or BRL?

**Comment by renanvalentin** [comment]
BRL

**Comment by willianjusten** [comment]
Nice, Good Luck =)

**Comment by joelwallis** [comment]
**This job is not available any more.** :(

Há uma outra vaga, mas essa não é remota :\ https://crave.workable.com/jobs/295226

**Comment by willianjusten** [comment]
Estou fechando essa vaga então e se você quiser abrir esta outra =)

**Comment by camilatigre** [comment]
@renanvalentin 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
