### ISSUE TITLE
[São Paulo- Campinas] Front-End Developer JR na Evolucional

### ISSUE THREAD

**Issue by rafadev** [frontendbr/vagas#450]
## Descrição da vaga

Meu querido padawan! Estamos atrás de você que tem a força mas ainda não a domina.
Somos uma startup como manda o script, ambiente descontraído, todo mundo de bermuda por 
aqui, sabe? Te falar que tem até uma piscininha 
Se interessou? Então se você manda bem no front e está disposto a lidar com vários 
desenvolvedores backend daqueles bem típicos, barbudos e tal, talvez essa vaga seja para você!

Sabia que somos a maior empresa privada do Brasil em nosso segmento? Temos a maior 
quantidade de escolas clientes ativas e estamos crescendo mais de 200% ao ano
## Local

R. Fernão de Magalhães, 891 - Parque Taquaral, Campinas

## Requisitos

Precisamos de alguém que saíba um pouco e tem interesse em aprender mais um montão dos 
seguintes pontos:

- Noção de JavaScript e AngularJS
- Conhecer o bom e velho HTML, saber estruturar uma página
- Deixar tudo uma lindeza via CSS
- Pré-Processador CSS (SASS)
- Taskrunner (Gulp,Grunt)
- Entender que flexibidade é mais importante do que aplicar literalmente o que está escrito nos 
livrozinhos

## Contratação

CLT

## Como se candidatar

Por favor envie um email para clayton.oliveira@evolucional.com.br com seu CV anexado - enviar no assunto: PROG-FRONTJR

**Comment by Iqueda** [comment]
Eu tenho disponibilidade para me mudar caso passe na entrevista e no teste, mesmo nao sendo de Campinas não tem problema?

**Comment by rafadev** [comment]
@Iqueda Beleza! Me manda um e-mail para acertarmos os detalhes

**Comment by Iqueda** [comment]
@rafadev mandar no email clayton.oliveira mesmo ou em algum seu?

**Comment by rafadev** [comment]
@Iqueda Pode mandar no e-mail do Clayton mesmo, já alinhei com ele aqui e de qualquer forma, mandando pra lá vem uma cópia pra mim

**Comment by Marcelosilva10** [comment]
@rafadev mandei meu CV e não tive resposta será que meu perfil se enquadra com a vaga?

**Comment by rafadev** [comment]
@Marcelosilva10 eu não recebi seu e-mail, você mandou com a tag certinho? Enfim, me encaminha agora se puder, rafael.barbosa@evolucional.com.br. Independente de enquadrar ou não, a gente da sempre um retorno porque sabemos que a pior coisa é ficar na expectativa e não ter nenhum feedback

Inclusive, se mais alguém teve o mesmo problema, faça o que sugeri acima.

**Comment by degaus** [comment]
@rafadev Enviei o CV 👍

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
