### ISSUE TITLE
[100% 🌎 Remoto] Front-end Developer na Khube (React Native/React)

### ISSUE THREAD

**Issue by davidsonsimoes** [frontendbr/vagas#4500]
> Vaga Remota - PERMANENTEMENTE REMOTA, Seja fera de onde cê quiser ser fera

## Nossa empresa

W2Bit e Khube agora são uma só!
Quer trabalhar em uma empresa 100% inovadora com as novas staks e projetos bem desafiadores?
Se você é um ninja no JavaScript e gosta de trabalhar com react, node, react native, vue, ou algo mais voltado para o back-end essa vaga combina com você!

## Descrição da vaga

Em seu dia a dia atuará com o JavaScript,React e React Native, Node, Firebase, desenvolvimento de funcionalidades e telas novas para web ou Mobile, resolução de Bug’s, consumo de API’s e integração entre sistemas via front-end, por isso é necessário o conhecimento intermediário de aplicação dessas tecnologias;

Será um diferencial ter conhecimento e/ou experiência com a plataforma Firebase, ou apreender a plataforma em menos de 2 meses - desafiador!

Será um diferencial ter conhecimento básico ou avançado em back-end (Node, Python, AWS, GC).

https://davidsonsimoes.typeform.com/to/TgDrCPuj

## Local

Não há exigência de horário ou local de trabalho. Nossa equipe já era remota mesmo antes da pandemia.
Nos comunicamos de maneira assíncrona via Slack e ferramentas de gestão de projetos.

Mas se preferir temos escritorio no Rio e SP =)

## Requisitos

**Obrigatórios:**
- 1 anos de experiência com REACT
- 2 anos de experiência com JavaScript

**Desejáveis:**
- conhecimentos em React
- conhecimentos em React Native
- conhecimentos em JavaScript

**Diferenciais:**
- conhecimentos em Firebase
- conhecimentos em Node
- conhecimentos em Python
- conhecimentos em Vue
- conhecimentos em Back-End
- conhecimentos em AWS
- conhecimentos em TypeScript

## Benefícios

- Aula de inglês particular
- Liberdade de trabalhar na hora que cê quiser de onde cê quiser. Desde que entregue as tarefas com as quais cê se comprometeu, tudo certo.
- Equipe pequena, altamente técnica, bem humorada, e principalmente obstinada e orientada a resultados. Sem perda de tempo em discussões inúteis. A gente ama o que faz e foca na entrega de resultados.

**Diferenciais:**
- 2 horas de almoço
- monte a sua máquina como desejar
- frigobar sempre cheio :P
- sala de jogos
- ...

## Contratação

PJ a combinar (ENVIAR PRETENSÃO)

## Como se candidatar

Por favor envie um email para davidson@khube.com.br com seu CV anexado e pretenção salárial - enviar no assunto: Vaga Khube

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: contato@w2bit.com

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
