### ISSUE TITLE
[São Paulo] Front-end Developer na Roy

### ISSUE THREAD

**Issue by caiosalim** [frontendbr/vagas#4501]
> Vaga Remota durante a pandemia

## Nossa empresa

Roy é uma start up com forte desenvolvimento de negócios. Nosso propósito é alavancar outras empresas através de marketing de qualidade e técnologia. 

## Descrição da vaga
Precisamos um front-end developer que venha agregar ao time com seus conhecimentos técnicos, motivação para desenvolver novas técnologias e criar um ambiente tech

## Local
Remoto, [SP], [São Paulo]

## Requisitos
**Obrigatórios:**
- Conhecimentos sólidos em HTML, CSS e JS
- Conhecimentos em Wordpress / Woocommerce
- Conhecimentos em NODE JS
- Utilização de APIs em REST
- Conhecimentos em hospedagem compartilhada e servidores CPANEL.

**Desejáveis:**
- React JS / Node JS

## Contratação
PJ a combinar

## Como se candidatar
Por favor envie um email para caio@royconsulting.com.br com seu CV anexado - enviar no assunto: Vaga Front-End Roy

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: caio@royconsulting.com.br

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
