### ISSUE TITLE
[Rio de Janeiro] Front-end Developer na Telecine (Grupo Globo)

### ISSUE THREAD

**Issue by Juuhz** [frontendbr/vagas#4503]
## Nossa empresa

A Telecine é uma Joint venture do Grupo Globo e dos maiores estúdios de Hollywood, reúne mais de 2.000 filmes, dos mais variados gêneros, selecionados a partir de uma curadoria especializada e comprometida, que alia tecnologia e inovação para promover a melhor experiência.

Pela internet, a plataforma de streaming é a única dedicada exclusivamente ao cinema. Líder de audiência na TV paga no Brasil, reúne em seis canais lineares segmentados por gêneros as produções que o público quer ver. Pela internet ou na TV, Telecine proporciona o seu momento cinema quando e onde você quiser.

## Descrição da vaga

O Futuro colaborador/colaboradora irá atuar em nossa [plataforma de streaming](http://telecine.com.br/), implementando features novas e realizando integrações com parceiros, afim de gerar mais valor ao produto e facilitar a aquisição/conversão de novos usuários.

É um case bem bacana, poder utilizar a tecnologia para levar entretenimento para a casa de milhões de pessoas. 

## Local

Esta vaga é para o nosso escritório no Rio de Janeiro, Barra da Tijuca, porém, devido a pandemia, estamos trabalhando de forma remota durante a pandemia.

## Requisitos

**Obrigatórios:**
- Sólidos conhecimentos em HTML e CSS.
- Bem desenrolado em Javascript 
- Conheçe e usa o ReactJS no dia a dia.
- Conhecer Git e Github (Versionamos nossos projetos no GitHub).
- Experiência com metodologia Ágil.

**Desejáveis:**
- Conhece e já usou o NextJS.
- ReactHooks e Context API.
- Testes unitários com Jest.

**Diferenciais:**
- Typescript.
- Node.
- Serverless.
- Storybook.
- Webpack.
- Design System.
- Já ter criado um pacote pro NPM.

## Benefícios

- Plano de Saúde e Odontológico.
- VR ou VA (Ou os 2 com % de cada à escolha) de R$ 36/dia.
- Horário flexível.

**Diferenciais:**
- Participação nos lucros.
- Auxilio ergonômico.
- Reembolso do cinema com direito a acompanhante (apenas para filmes que Telecine apoia).
- Reembolso de até **R$ 275** em planos de Internet + TV + Telefone.
- Reembolso em cursos de inglês.
- Assinatura dos produtos globo (Telecine, Globo Play, etc...).
- Clube de descontos em Restaurantes, Lojas, Academias, etc...
- E muito mais, vai na fé.

## Contratação

A combinar.

## Como se candidatar

Por favor envie um email para reinaldo.amorim@telecine.com.br com seu **CV + Linkedin + Portfólio + Github** - enviar no assunto: [Vaga Front-End] - SEU NOME 

#### Alocação
- Alocado
- Remoto durante a pandemia.

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by Juuhz** [comment]
**Update 22/03/2021** - Ainda estamos aceitando candidaturas (RIO x SP x Outros estados que queiram se mudar para o RJ).

**Comment by Juuhz** [comment]
**Update 24/03/2021** - Ainda estamos aceitando candidaturas (RIO x SP x Outros estados que queiram se mudar para o RJ).

**Comment by Gabri3el** [comment]
@Juuhz a vaga não é para remoto né ? tenho todos os requisitos, porém não tenho disponibilidade para morar no Rio.

**Comment by Juuhz** [comment]
Oi @Gabri3el, remoto apenas durante a pandemia :/

**Comment by aoligama** [comment]
ainda estão aceitando candidaturas?

**Comment by Juuhz** [comment]
> ainda estão aceitando candidaturas?

Sim o/ 

Update 29/03/2021 - Ainda estamos aceitando candidaturas (RIO x SP x Outros estados que queiram se mudar para o RJ).
