### ISSUE TITLE
[Goiânia] Front-end Developer na PerfectLine

### ISSUE THREAD

**Issue by thalessr** [frontendbr/vagas#4505]
> Vaga Remota durante a pandemia

## Nossa empresa

A [PerfectLine](https://www.perfectline.co) em sua forma atual foi iniciada em outubro de 2008, numa época em que o mundo enfrentava a maior crise financeira da história. Apesar das chances improváveis de sucesso, Martin (fundador da PerfectLine) decidiu construir a empresa com dois colegas engenheiros.

Naquela época, o principal objetivo da empresa era ajudar startups em estágio inicial a criar seus produtos mínimos viáveis de forma eficiente.

Hoje, nossa agência trabalha tanto com startups quanto com empresas para fornecer serviços eficientes de desenvolvimento de produtos em todo o mundo.

Codificamos nas linguagens: Ruby, PHP, NodeJS, Go, React Native, Vue.js, React.js, Java.

## Local

Goiânia, Lozandes Shopping

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com Vuejs/React
- HTML
- CSS/SASS
- Inglês intermediário

**Desejáveis:**
- conhecimentos em Tailwind CSS
- conhecimentos em design - saber ajustar a margem, se fonte está correta, etc.
- conhecimentos em React Native
- conhecimentos em Ruby on Rails

**Diferenciais:**
- horário flexível
- 40h/semanais (de segunda à sexta)

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para thales@perfectline.co com seu CV anexado - enviar no assunto: Vaga Front-end Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.

#### Alocação

- Alocado

#### Regime

- PJ

#### Nível

- Pleno
- Sênior

**Comment by thalessr** [comment]
@felipefialho a tag da cidade está errada. Por favor, substitua "São Paulo" por "Goiânia".

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
