### ISSUE TITLE
[REMOTO - BRASIL] FRONT-END ANGULAR - Front-End Developer

### ISSUE THREAD

**Issue by incredibleHR** [frontendbr/vagas#4506]
**DESCRIÇÃO DE ATIVIDADES**

Analisar a viabilidade de demandas apresentadas pelos usuários a serem implementadas nos programas/sistemas existentes;
Desenvolver, testar e implantar programas e sistemas customizados;
Providenciar a documentação funcional e técnica dos programas e sistemas customizados;
Pesquisar, analisar, sugerir e contribuir na implementação de novas tecnologias associadas com aplicações corporativas;
Projetar, construir e otimizar interfaces web;
Implementar layouts intuitivos e responsivos utilizando princípios ergonômicos de usabilidade.

**REQUISITOS**

Experiência com desenvolvimento FrontEnd em Angular.
Experiência em HTML5, Angular, CSS3, Javascript, SQL, entre outras;
**Experiência em Cloud AWS.**

**BENEFÍCIOS**
Vale-refeição ou Vale-alimentação, Assistência Médica e Odontológica, Auxílio Internet

**REMUNERAÇÃO** 
Estamos trabalhando com pretensão salarial, não deixe de se candidatar

## Como se candidatar?

Por favor envie um email para juliana@gobettirh.com.br com seu CV anexado - enviar no assunto: Vaga FrontAngular

OU

Preencha o formulário através do link : https://forms.gle/oLHS4RdVm6Sj86KX6 

Aguardo por vc!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
