### ISSUE TITLE
[Vitória/ES] ou [Remoto] Senior Front-end Developer na Trustly

### ISSUE THREAD

**Issue by Trustly-br** [frontendbr/vagas#4509]
## Nossa empresa

At Trustly, we’re passionate about simplifying the way people pay and get paid online. We are a licensed payment institution and our B2B products available across Europe and the US attract global merchants in segments such as e­-commerce, travel, financial services and gaming. In June 2018, private equity firm Nordic Capital acquired a majority stake in Trustly with ambitions to support us in becoming the leading global online banking payments provider.
 
We are a diverse and fast-growing team with our headquarters in Stockholm, Sweden, and offices in Barcelona, Spain; Cologne, Germany; Helsinki, Finland; Lisbon, Portugal; London, UK; Örebro, Sweden; Redwood City, US; Sliema, Malta and Vitória, Brazil. Together we are leading the development of the payments industry and the work you’ll do here will make a great impact.

## Descrição da vaga

What you'll do:
Write client-side code for web-based and mobile applications, create robust high-volume production applications, and develop prototypes quickly.
Optimize web applications to maximize speed and scale.
Active role during sprint planning and scrum meetings with teams in Vitória, San Francisco (headquarters) and other locations.  

## Local

100% remoto, ou no nosso escritório em Vitória/ES.

## Requisitos

**Obrigatórios:**
Experience developing/designing software systems;
Understanding of layout aesthetics, and a drive to create thoughtful UX experiences and pixel-perfect web pages;
Excellent coding skills in Javascript (ES6), HTML and CSS;
Expert in modern front-end frameworks (e.g. React, Angular, Vue);
Excellent coding skill and understanding of OO concepts;
Previous experience with source control;

**Desejável:**
Ability to communicate effectively in English (written and verbal).

## Benefícios

- Plano de saúde
- Plano odontológico
- Seguro de vida
- Vale refeição/alimentação 
- Gympass 
- Kit admissional contendo MacBook Pro e Iphone
- Kit onboarding
- Flexibilidade de horário

**Diferenciais:**
- Aulas semanais de inglês 
- Ginástica laboral
- Happy hour semanal
- Happy hour mensal com cupom Ifood 
- Trustly Club (parceria com instituições)
- Bônus anual

## Contratação

CLT

## Como se candidatar

Por favor envie um email para jobs-br@trustly.com com seu CV anexado (Enviar no assunto: Vaga Front-End), ou cadastre-se no link: https://www.trustly.net/job/senior-front-end-developer

#### Alocação
- Remoto
- Vitória/ES

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
