### ISSUE TITLE
[São Paulo- Campinas] Front-End Developer Pleno na Evolucional

### ISSUE THREAD

**Issue by rafadev** [frontendbr/vagas#451]
## Descrição da vaga

Meu querido padawan que já está mais treinadinho! Estamos atrás de você que tem a força mas 
ainda não a domina totalmente.
Somos uma startup como manda o script, ambiente descontraído, todo mundo de bermuda por 
aqui, sabe? Te falar que tem até uma piscininha 
Se interessou? Então se você manda bem no front e está disposto a lidar com vários 
desenvolvedores backend daqueles bem típicos, barbudos e tal, talvez essa vaga seja para você!

Sabia que somos a maior empresa privada do Brasil em nosso segmento? Temos a maior 
quantidade de escolas clientes ativas e estamos crescendo mais de 200% ao ano

## Local

R. Fernão de Magalhães, 891 - Parque Taquaral, Campinas

## Requisitos

Precisamos de alguém que saiba e tem interesse em aprender mais e ajudar os coleguinhas que 
ainda estão aprendendo os seguintes pontos:

- JavaScript e AngularJS
- O bom e velho HTML
- Deixar uma lindeza via CSS
- Pré-Processador CSS (SASS)
- Taskrunner (Gulp,Grunt)
- Entender que flexibidade é mais importante do que aplicar literalmente o que está escrito nos 
livrozinhos

## Contratação

CLT

## Como se candidatar

Por favor envie um email para clayton.oliveira@evolucional.com.br com seu CV anexado - enviar no assunto: PROG-FRONTPL

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
