### ISSUE TITLE
[Vitória] Front-end Developer na Code n' App

### ISSUE THREAD

**Issue by LiliamGaviorno** [frontendbr/vagas#4510]
> Vaga Remota durante a pandemia

## Nossa empresa

Somos uma empresa que busca inovar através de processos e ferramentas para entregar soluções em tecnologias que atendam as expectativas do mercado.

## Descrição da vaga

Procuramos profissionais com mais de 5 anos de experiência em construção de interfaces de software web com foco em aplicação de templates, criação e utilização de componentes UI.

## Local

Remoto ou Escritório, [ES], [VITÓRIA]

## Requisitos

**Obrigatórios:**
HTML, CSS e Javascript,
Bootstrap  
JQuery

**Desejáveis:**
React, 
Vue 
Angular

## Benefícios

Faixa salarial de R$4.000 a R$8.000, plano de saúde, plano odontológico, vale transporte, ticket refeição, Gympass

## Contratação

PJ ou CLT a combinar

## Como se candidatar

Se você é esse profissional, venha fazer parte da nossa equipe. Envie seu currículo, com o nome da vaga no título, para queroser@codeanpp.com

#### Nível
- Sênior
- Especialista

![Vaga_Desenvolvedor_ Front-end_Senior](https://user-images.githubusercontent.com/80852236/111792148-ba809300-88a2-11eb-9a12-6209489e07e4.png)

**Comment by JordanaNadur** [comment]
Boa tarde segue em anexo currículo conforme vaga abaixo

Desde já agradeço

Jordana Nadur

Em sex., 19 de mar. de 2021 às 11:04, LiliamGaviorno <
***@***.***> escreveu:

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
