### ISSUE TITLE
[Remoto] Front-end React Developer - Pleno/Sênior na iClinic

### ISSUE THREAD

**Issue by renvieir** [frontendbr/vagas#4514]
## Nossa empresa

A **iClinic** é uma das startups de tecnologia em saúde que mais cresce no Brasil.

**Nossa missão é Descomplicar a saúde no Brasil**.

E como fazemos isso hoje?
Oferecendo o melhor software de gestão para clínicas e consultórios médicos.

E como atingir este objetivo?
Montando um time de pessoas incríveis, capazes de colocar os nossos clientes no centro do processo de criação e desenvolvimento do nosso sistema. Aqui são os clientes quem mandam e você será uma das vozes deles dentro da empresa e do time de Pesquisa e Desenvolvimento.

## Descrição da vaga

A **iClinic** está à procura por Front-end React Developer (100% remoto) para fortalecer e expandir nossas capacidades técnicas. Buscamos uma pessoa responsável para o cultivo de uma cultura técnica de excelência: obcecado por qualidade e desenvolvimento ágil. Procuramos alguém para refletir, validar ideias e ajudar-nos a encantar nossos clientes.

Você vai trabalhar com times multidisciplinares, com pessoas incríveis, capazes de realizar trabalhos incríveis e produzir resultados incríveis para os nossos usuários. Será responsável por desenvolvimento contínuo diariamente e irá garantir a qualidade que almejamos.

Tecnologia é o nosso core, então terá autonomia para arquitetar ou sugerir algo novo, deve ter uma mentalidade analítica, aptidão para solução de problemas e preocupação com a qualidade do código e boas práticas.

Temos serviços em Python/Django, Node, sistemas na AWS com e sem Kubernetes. Nossa aplicação front-end é desenvolvida em React + Redux.

**O que esperamos de você**:
* Vontade de repassar conhecimento, ensinar, criar ou já ter criado artigos de programação;
* Não ter receio em alterar um código que você não escreveu;
* Empatia por seus colaboradores;
* Capacidade de comunicar ideias de forma clara;
* Desejamos pro atividade para adquirir novos conhecimentos rapidamente.

## Local

100% Remoto

## Requisitos

* Experiência comprovada em **React + Redux** como front-end;
* Alta capacidade de auxiliar os outros membros do time a se desenvolverem, sendo capaz de comunicar ideias de forma clara;
* Visão ampla sobre processos de desenvolvimento e fluxo de trabalho em metodologias ágeis;
* Conhecimentos abrangentes em todas as partes do software, podendo conversar com diversas frentes do produto, pesquisa, dev-ops, back-end, QA tester;
* Conhecimentos em arquitetura de projetos, design patterns e boas práticas de desenvolvimento;
* Conhecimentos em paradigmas funcionais e suas práticas;
* Conhecimentos em metodologias de testes unitários, integração e E2E.

## Benefícios

* Vale refeição;
* Vale alimentação;
* Convênio médico nacional;
* Convênio odontológico;
* Convênio Farmácia;
* Seguro de vida;
* Convênio SESC;
* Auxílio-Creche;
* Licença maternidade/paternidade estendida; 
* Plano de participação nos resultados (PPR);
* Acesso a cursos gratuitos através da plataforma da UCA - Universidade Corporativa Afya;
* Fornecemos notebook como equipamento para trabalho;
* Ajuda de custo para trabalho remoto;
* Bônus por indicação de outros profissionais para trabalhar na **iClinic**;
* Relacionamento próximo aos fundadores e diretores da empresa;
* Incentivo financeiro para desenvolvimento técnico;

Quando fizer uma visita em nosso escritório - pós pandemia :) - você encontrará:

* Ambiente jovem, descontraído, escritório confortável, videogame, puffs para descanso;
* Sem dress code. Trabalhe do jeito que achar confortável;
* Café da manhã, frutas e o sagrado cafezinho ao longo do dia;

## Contratação

CLT, com pacote de benefícios

## Como se candidatar

Por favor candidate-se em: https://iclinic.gupy.io/jobs/628347?

Além disso, você pode conectar-se conosco via LinkedIn:

https://www.linkedin.com/in/fabianakimie/
https://www.linkedin.com/in/franciscofreitas92/
https://www.linkedin.com/in/vinicius-luis-parisi/

## Tempo médio de feedbacks

Costumamos enviar feedbacks ao encerramento do processo seletivo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
