### ISSUE TITLE
[Remoto] Front-end Developer (React) na Softplan

### ISSUE THREAD

**Issue by rochalauriane** [frontendbr/vagas#4516]
Somos apaixonados por desenvolver soluções que geram alto impacto e fazem a diferença na vida das pessoas. Além disso, estamos entre as maiores empresas do Brasil no desenvolvimento de software de gestão, segundo ranking do GPTW (Great Place to Work).

Tente coisas novas, foque no que você é apaixonado, seja curioso, tenha sucesso. Este é o tipo de coisa que oferecemos: muito espaço para fazer. Estamos crescendo e mudando como empresa, então queremos que você cresça como pessoa e profissionalmente também. Sempre que você precisar de suporte, faremos tudo o que pudermos para ajudá-lo. Aqui na Softplan, você trabalhará lado a lado com especialistas de classe mundial.

Nós nos esforçamos para oferecer transparência e oportunidades para que nossa equipe tenha representatividade em toda a empresa. Na Softplan, você tem autonomia e é encorajado para tomar boas decisões.

**Vaga nível pleno.
Suas responsabilidade:
Ser capaz de desenvolver uma SPA (Single Page Application) utilizando React; 
Saber utilizar gerenciadores de estado da aplicação (Context API, Cache com Apollo/Relay); 
Conhecimento avançado em ES6+; 
Conhecimento em controle de versão (Git); 
Conhecimento em GraphQL (Apollo ou Relay); 
Processos CI/CD (Gitlab CI ou Github Action); 
Suíte de testes @testing/library; 
Estilização utilizando CSS-in-JS; 
Conhecimento de técnicas e práticas de Clean Code; 
Conhecimento ferramentas de qualidade de código (linters); 
Conhecimento avançado em HTML e CSS, incluindo conceitos de layout, compatibilidade entre browsers e acessibilidade; 
Experiência em equipes dinâmicas e metodologias de desenvolvimento ágeis; 
Ter um perfil proativo, boa comunicação, raciocínio lógico, responsabilidade e comprometimento; 

Você se destaca se possuir: 
Formação completa em ciências da computação, sistemas de informação ou cursos equivalentes; 
Conhecimento em princípios de design de interação, UX e Design System; 
Conhecimento em Docker; 
Conhecimento em algumas das bibliotecas Webpack, Rollup e Parcel; 
Conhecimento em .Net Core; 
Saber estruturar e implementar micro-frontends; 

Modelo de Trabalho 
A partir de 2021, o novo modelo conta com as opções de home&office (modelo híbrido - parte remoto e parte presencial com média de 2x por semana no escritório) ou anywhere office (100% remoto). Esta vaga é em Modelo 100% Remoto.

Benefícios
Plano de saúde e odontológico;
Vale-alimentação/Vale-refeição;
Vale-transporte;
Bônus anual por resultados;
Programa de promoção à saúde e bem-estar (ginástica laboral 3x na semana, acolhimento psicológico, atendimento médico, nutricionista, ambulatório na sede etc.);
Programa Desenvolve Softplan: apoio para realizar cursos e certificações;
Parcerias e descontos.

Confiamos e valorizamos nossa equipe, pois todos e cada um de nós construímos a Softplan todos os dias. É assim que fortalecemos Softplayers como nossa base. Por isso, consideramos todas as candidaturas para as nossas vagas sem distinção de raça, cor, religião, gênero e identidade de gênero, nacionalidade, deficiência, orientação sexual, ascendência, idade etc. 

Interessados encaminhar currículo para: lauriane.moco@softplan.com.br

**Comment by Marcosnto** [comment]
Boa tarde! 

No texto não há uma descrição de como a pessoa pode se candidatar a vaga.

**Comment by ElbertRibeiro** [comment]
@rochalauriane Boa noite, como posso me candidatar?

**Comment by rochalauriane** [comment]
> @rochalauriane Boa noite, como posso me candidatar?

Olá, você pode encaminhar o seu currículo para lauriane.moco@softplan.com.br

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
