### ISSUE TITLE
[Remoto] Phoenix liveview Front-End Developer na payfy

### ISSUE THREAD

**Issue by andreapollaro** [frontendbr/vagas#4517]
## Nossa empresa

Somos uma spin-off da [KM Online](https://www.kmonline.com.br/), responsável pela construção da Conta payfy, uma conta de pagamento de meio de pagamento para empresas modernas.

Queremos mudar a forma como empresas gerenciam os gastos em seus negócios. Para isso, contamos com um time fora da curva e distribuído por diversas cidades do Brasil. Além disso, não temos medo de inovar na tecnologia para entregar os melhores produtos!

Nossa stack é baseada principalmente em Elixir no backend, Phoenix liveview no frontend, serviços na AWS e app em Flutter.

## Descrição da vaga
 
Estamos buscando Software Developers que tenham interesse em trabalhar com Phoenix liveview e queiram encarar conosco o desafio de construir toda a plataforma web da Conta payfy, nos ajudando nas principais decisões técnicas e seus impactos no produto no médio/longo prazo.

# Tipo de Contratação

A contração será em regime PJ, com possibilidade de trabalho presencial nos escritórios de Florianópolis ou 100% remoto. Sim, você pode trabalhar de qualquer lugar do Brasil :)

# O que não pode faltar

- Interesse em trabalhar com Elixir e Phoenix liveview;
- Nível de experiência: Pleno-sênior
- Capacidade de produzir código limpo e de fácil manutenção;
- Nível avançado de leitura e escrita em inglês; 
- Motivação por aprendizado e desenvolvimento contínuos;
- Capacidade de se comunicar de forma concisa, franca e clara (também por escrito).

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para andre@payfy.io com seu CV anexado - enviar no assunto: Vaga Phoenix liveview Front-End Developer

Costumamos enviar feedbacks em até 2 dias após cada processo.

Abs,
Equipe [payfy.io ](https://www.payfy.io/)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by andreapollaro** [comment]
Oi @felipefialho , estamos com a vaga aberta ainda sim! @

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
