### ISSUE TITLE
Porto Alegre - Front-end Developer na Cursos Edgar Abreu

### ISSUE THREAD

**Issue by PRISCILANIFFA** [frontendbr/vagas#4518]
## Nossa empresa

Somos uma empresa de Tecnologia, inserida em um mercado de educação e em constante evolução. Se você é uma pessoa apaixonada por tecnologia, ama codar, e nos últimos anos vêm ajudando a construir a internet, essa vaga é para você.

## Descrição da vaga

• Usar o melhor em desenvolvimento de software aliado a boas práticas de design;
• Desenvolver código limpo, eficaz, legível e de fácil manutenção para as interfaces;
• Participar dos processos criativos da nossa plataforma, dando suporte no que tange a viabilidade técnica de desenvolvimento de novas features e interfaces;
• Otimizar as aplicações para a sua melhor performance e eficiência;
• Trazer sua visão e experiência para a equipe de desenvolvimento.

## Local

Modelo de atuação híbrido, RS, Porto Alegre, Boa Vista

**Obrigatórios:**
• Experiência com JavaScript, Vue.js, HTML e CSS;
• Experiencia traduzindo designs (figma, Sketch, etc) pra assets web (HTML, CSS, js)
• Uma busca constantemente de conhecimento sobre novas práticas de desenvolvimento, ferramentas e processos que melhorem a performance e usabilidade;
• Brilho nos olhos por tecnologia;

**Desejáveis:**
• Experiência com plataformas LMS;
• Noções de Laravel (PHP)
• Flexibilidade para trabalhar em um ambiente volátil com demandas constante

## Benefícios

- Plano de saúde
- Bonificações

**Diferenciais:**
- Modelo híbrido
- frigobar sempre cheio :P
- sala de jogos

## Contratação

CLT ou PJ

## Como se candidatar

Por favor envie um email para priscila@cursosedgarabreu.com.br com seu CV anexado - enviar no assunto: Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: priscila@cursosedgarabreu.com.br

#### Nível

- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
