### ISSUE TITLE
[São Paulo] Front-end React/Redux na Laborit

### ISSUE THREAD

**Issue by desoares1975** [frontendbr/vagas#452]
Você é ninja no Front-End, manja de React e Redux? Venha trabalhar na Laborit , somos uma empresa focada em desenvolvimento de produtos para startups e ponto com. Nosso portfólio de produtos vai de apps, search engine, chatbots, redes sociais até cms.

Local
Você trabalhará como desenvolvedor freelance remotamente, com comunicação diária via Trello, Slack e Hangout envolvendo nossos times de engenharia, ux e produto. Faremos planning, reviews e principalmente o alinhamento dos resultados e validação de entregáveis semanalmente em nosso escritório, localizado no bairro Pinheiros, bem próximo à estação do metro.

Requisitos
* Experiência com desenvolvimento front-end em geral (JavaScript, HTML, SASS e CSS);
* Experiência com desenvolvimento React e Redux;
* Integração com o backend (API RESTful e websocket);
* Experiência com desenvolvimento de Single Page Applications, ferramentas e técnicas relacionadas (build e deployment pipelines, etc);
* Experiência com TDD/BDD;
* Experiência ou conhecimentos em APIs REST;
* Kanban e Scrum;
* Inglês avançado;

Contratação
Freela PJ, com possibilidade de contratação fulltime clt (em SP).
Interessados enviar currículo para telma@laborit.com.br.

**Comment by uselessdev** [comment]
@desoares1975 como se candidatar?

**Comment by desoares1975** [comment]
Envie o currículo para telma@laborit.com.br, valeu o alerta.

**Comment by uselessdev** [comment]
@desoares1975 enviado :smile:

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
