### ISSUE TITLE
[Joinville-SC] Front-end Developer Mobile Jr - Flutter na BeAudio Informática

### ISSUE THREAD

**Issue by MatheusRauchRosa** [frontendbr/vagas#4520]
## Nossa empresa

- Somos a beAudio, o mais completos sistemas de gerenciamento e automação de rádio do Brasil. Entregamos para nossos clientes Confiança, estabilidade, segurança e agilidade
Temos mais de 10 anos de história. Atualmente, mais de 200 emissoras utilizam nossas soluções, envolvendo estúdio, produção, comercial, financeiro, jornalismo, recepção e CRM.
Construímos uma base sólida com nossos clientes firmada no atendimento de excelência. Dessa forma, cada pessoa que interage com nossas soluções faz parte da evolução de todos os produtos beAudio.

- Conheça mais sobre a beAudio:
www.facebook.com/beAudiobr/
www.instagram.com/beaudiobr/
www.youtube.com/channel/UCbVv3sWwFDaQTZWMQLGjt9Q

## Descrição da vaga

- Se você curte um ambiente inovador, ágil e deseja trabalhar em aplicativos personalizados, atuando com foco no Front-end, essa oportunidade é para você!!!

**Responsabilidades**

- Trabalhar com desenvolvimento, manutenções e atualizações do aplicativo já existente em nossos clientes.
Executar tarefas para o back-end ou front-end de nossa aplicação principal.

## Local

- Presencial

## Requisitos

**Obrigatórios:**

- Dart
- Flutter
- JavaScript
- Node.js
- PostgreSQL

**Diferenciais:**

- Vue.js
- Flux
- Vuex
- Git
- Publicações de aplicativos na PlayStore e AppStore

## Benefícios

- Vale-refeição
- Vale-transporte
- Seguro de Vida
- Folga no dia do aniversário
- Plano de saúde e odontológico após o período de experiência

## Contratação

- CLT
 
## Como se candidatar

Acesse o [link](https://vagas.hunterco.com.br/job/60363c96e710a6001bb0ee97?c=3759)
Click em "Quero participar" ou conheça as nossas outras vagas.

#### Nível

- Júnior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
