### ISSUE TITLE
[Piracicaba-SP] Front-End Developer na [Geplant]

### ISSUE THREAD

**Issue by vrechi** [frontendbr/vagas#4522]
### A Geplant busca **Desenvolvedor Front-End** - Pleno/Sênior

**Requisitos Obrigatórios:**
**Graduação completa** na área de TI ou áreas correlatas
**Cinco anos de experiência** (após graduação) OR doutorado na área

**Conhecimento Desejável:**
JavaScript, HTML5, CSS  |  React,js, Angular ou VueJS |  Git   |  APIs RESTful  |  Node.js
Diferencial: conhecimento em UX/UI   |  Bootstrap 

**Como será seu dia a dia:**
- Pesquisar e implementar novas tecnologias e melhorias em nossa plataforma
- Aplicar e disseminar boas práticas de versionamento, desenvolvimento, testes, documentação, integrações, cloud, segurança e metodologias ágeis
- Apoiar a equipe do projeto

**Local de trabalho**
Piracicaba-SP 
(Presencial pelo menos uma parte do tempo, após passarem as restrições da COVID-19)

Importante: a modalidade da contratação é via Bolsa de Treinamento Técnico da FAPESP TT-V (https://fapesp.br/capacitacaotecnica), com duração total de 2 anos e remuneração mensal de R$ 7.372,40.

**Quem somos:**
Somos a Geplant, uma empresa de tecnologia para a área florestal e agro, com cultura de startup e ambiente que promove a inovação, aprendizado e desenvolvimento.
Estamos desenvolvendo uma solução de base tecnológica e científica para nosso setor, que integra fontes de Big Data e algoritmos de inteligência analítica e espacial para gerar insights e melhoria de processos.
Faça parte do nosso time!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
