### ISSUE TITLE
[REMOTO] Front-end Software engineer na Vobi 

### ISSUE THREAD

**Issue by mmbfreitas** [frontendbr/vagas#4523]
## Nossa empresa

Criada por ex-sócios da MAR ventures - Venture builder brasileira com foco em marketplaces e fintechs -  a Vobi está transformando a indústria da construção civil (A segunda indústria menos digitalizada globalmente) através da tecnologia. A Vobi é uma plataforma de gestão para pequenas empresas do setor, como arquitetos e designers. Nós os ajudamos a gerenciar melhor os seus projetos e negócios, eliminando tarefas administrativas e manuais para que se concentrem no que fazem de melhor.

Por meio da Vobi, eles conseguem gerenciar projetos de reforma ou construção do início ao fim, colaborar com seus clientes, planejar, criar orçamentos e fazer compras ou pagamentos a fornecedores, tudo em uma única  plataforma.

**Somos Scale-UP Endeavor 2020**

A Vobi está em busca de pessoas para fazer parte da área de tecnologia e nos ajudar a construir a próxima geração de infraestrutura tecnológica do setor da construção civil.   

Se você gosta de desafios e está a fim de sacudir uma indústria tradicional e arcaica por completo, venha falar conosco.

## Local

REMOTO

## Requisitos

**Obrigatórios:**
- Mínimo de 3 anos de experiência em engenharia de software no desenvolvimento e manutenção de aplicativos web
- Fortes conhecimentos em javascript
- Sólidos conhecimentos de lógica de programação, orientação a objetos e design patterns
- Experiência na utilização de frameworks JavaScript MVC (AngularJS, ReactJS, VueJS)
- Experiência com testes unitários em JS (Mocha, Protractor, Jasmine...)
- Experiência com Rest API, preferencialmente Node.JS

**Desejáveis:**
- Conhecimento em banco de dados SQL e NoSQL
- Noções em Docker e AWS
- Bom nível de inglês

## Porque fazer parte do nosso time:

- Oportunidade de participar da criação de uma startup do zero
- Remuneração alinhada ao mercado
- Ambiente descontraído e meritocrático, com oportunidades e suporte para desenvolver sua carreira, incluindo a possibilidade de participação societária
- Gympass
- Trabalhe de onde desejar
- Liberdade para propor novas ideias e assumir grandes responsabilidades

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para ti@vobi.com.br com seu CV anexado - enviar no assunto: Vaga Software Engineer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

## Labels

- Remoto
- PJ
- Startup
- React

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
