### ISSUE TITLE
[Remoto / Porto Alegre ] Front-end Developer (React) na DeepX

### ISSUE THREAD

**Issue by sam-ferreira** [frontendbr/vagas#4525]
## Descrição da vaga

A DeepX está procurando por um **Senior React Developer** para atuar na nossa área da consultoria, trabalhando com um dos nossos clientes, uma das grandes redes de fast food! 🍔👑 No nosso time, você trabalhará construindo componentes de UI e fazendo implementação com Flux ou Redux. Você estará envolvido nas decisões dos sistemas de arquitetura e terá a oportunidade de implementar novas ideias junto de times de desenvolvimento e design. Em nossas rotinas, nós utilizamos metodologias ágeis, processos de CI/CD, TDD e valorizamos boas práticas de implementação de código.

## Local

Remoto ou Escritório, Porto Alegre - Moinhos de Vento (Porém, somente remoto durante a pandemia.)

## Requisitos

- Experiencia com desenvolvimento frontend;
- Conhecimento em React, Javascript, ou outras linguagens e frameworks;
- Inglês avançado;
- Vontade de aprender coisas novas e trabalhar colaborativamente.

## Nossa empresa

A DeepX é uma empresa americana fundada em 2014, com intuito de criar produtos próprios inovadores e também ajudar empresas a acelerarem seus negócios através da tecnologia. Desde então, existe essa conexão Porto Alegre e Austin, criando produtos e trabalhando com empresas de diversos lugares do mundo.

Quer saber mais sobre a nossa cultura? Da uma olhadinha no nosso site: https://www.deepx.it/life-at-deepx

**Diferenciais:**

- Projetos internacionais;
- Oportunidade de usar o inglês no dia-a-dia;
- Flexibilidade de horários;
- Compartilhamento de conhecimento;
- Um time verdadeiramente aberto pra receber pessoas novas.

## Contratação

PJ a combinar

## Como se candidatar

Aplique aqui: https://jobs.lever.co/deepx/85b920c8-d66b-4852-bb39-d67a3858d7b0/apply

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: careers@deepx.it

## Labels

- Remoto
- CLT
- PJ
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
