### ISSUE TITLE
[Remoto] Front-end Angular Developer no DB1 Group

### ISSUE THREAD

**Issue by alissongusmao** [frontendbr/vagas#4526]
## Nossa empresa

Somos um grupo de empresas de tecnologia nascido em Maringá, interior do Paraná, com 20 anos de experiência em desenvolvimento de software voltado para soluções de grandes empresas. Atuamos em diversas frentes de mercado: com produtos (ANYMARKET, CONSIGNET, EIVE) e também com serviços e projetos personalizados através da nossa Fábrica de Software - DB1 Global Software. E estamos em expansão!!! 🚀🚀🚀

Somos colaboradores distribuídos em todo o Brasil e na Argentina, com escritório em Maringá/PR, Campo Grande/MS e Presidente Prudente/SP e atuamos também de forma remota (home office) desde 2017. Estamos há 12 anos consecutivos entre as Melhores Empresas Para Trabalhar, segundo o GPTW, com reconhecimento pela instituição em 2020 como empresa referência na prática de escutar o colaborador.

Somos movido por desafios diários, sempre buscando uma forma de melhorar o que já existe e criar coisas novas com qualidade! Todos(as) aqui temos autonomia e voz para dar feedbacks, testar coisas novas e ser parte dessa mudança. Aqui aprendemos uns com os outros diariamente, com um forte senso de equipe. DB1 é pra quem não quer ser mais um!

## Descrição da vaga

Buscamos um(a) profissional apaixonado(a) por tecnologia, próativo, comprometido em entregar software com qualidade, contribuindo com conhecimentos e experiências . Atuará no desenvolvimento Frontend utilizando AngularJS e Angular 2+.

**Suas principais atividades serão:**

- Atuar na customização e evolução de um sistema no segmento de farmácias.
- Desenvolver com foco em frontend, utilizando AngularJS e Angular 2+
- Trabalhar em conjunto com equipe de desenvolvimento backend Java. 

## Local

Remoto ou Escritório, Paraná, Maringá

## Requisitos

**Obrigatórios:**
- Experiência em frontend;
- HTML;
- Javascript;
- Css;
- Angular 2 +;
- Angularjs;
- Restful API;
- Conceitos de componentização;
- Boas praticas de desenvolvimento.

**Desejáveis:**
- Conhecimento em Testes Unitários, utilizando Jasmine.

**Diferenciais:**
- Conhecimento em Java.

## Benefícios

- Vale alimentação e/ou vale refeição;
- Plano de Saúde e plano odontológico;
- Uma trilha de carreira com Plano de Desenvolvimento Individual (PDI) e feedbacks constantes para te ajudar na sua evolução profissional;
- Horários flexíveis!;
- Convênio com farmácia Droga Raia, com desconto para colaboradores;
- Pra celebrar seu aniversário, é possível sair um pouco mais cedo no dia para comemorar com quem quiser e organizar o que for necessário 🥳
- Aqui você terá a oportunidade de aprender coisas novas - seja no dia-a-dia, em um Programa de Mentoria ou em um desafio do nosso programa de gamificação Mestre dos Códigos.
- Home office como modelo de contratação. Atuamos com essa possibilidade desde 2017. Além de viabilizar a nossos colaboradores trabalhar de casa em algum dia da semana quando necessário :)

## Contratação

CLT com possibilidade 100% remota

## Como se candidatar

[Clique aqui para se inscrever na oportunidade](https://vagasdb1.recruiterbox.com/jobs/fk0uvze?source=Github), envie seus dados e nosso time de recrutamento e seleção entrará em contato.

Contamos mais sobre como é trabalhar na DB1 no nosso [site de carreira](https://www.db1group.com/home-office/), também nas nossas Redes Sociais: [LinkedIn](https://www.linkedin.com/company/db1-group), [Instagram ](https://www.instagram.com/db1group/)e [Facebook](https://www.facebook.com/DB1Group). Se quiser ficar por dentro das novidades do mundo de tecnologia ou novas oportunidades, acompanha a gente lá! 🧐

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: talentos@db1.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
