### ISSUE TITLE
[Remoto] Front-end Pleno e Sênior na Digital Code (Dentsu Brasil)

### ISSUE THREAD

**Issue by Conchetto** [frontendbr/vagas#4527]
> Vaga Remota durante a pandemia

## Digital Code

Somos a Digital Code, uma empresa de tecnologia do grupo Dentsu. A Dentsu é o maior grupo de publicidade da Ásia e figura entre os principais players da publicidade brasileira.

Buscamos um profissional comprometido com qualidade de código e apaixonado por tecnologia.

Alguém que busca otimizar e evoluir seus processos de desenvolvimento, criando projetos tecnicamente elaborados, mas que entregam resultados práticos e claros.

## Local

Trabalho 100% Remoto

## Requisitos

**Obrigatórios:**
- Amplo domínio no front-end (experiência em HTML5/CSS3/JS)
- Autonomia com ReactJS / VUE.js ou Vanilla
- Bons conhecimentos de Redux
- Sass e webpack
- Integração com APIs REST
- Bons conhecimentos com GIT

**Desejáveis:**
- Experiência com metodologias ágeis
- Base de UX ou UI

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para lucas.conchetto@digitalcode.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
