### ISSUE TITLE
[São Paulo] Front-end Developer na EcoStage

### ISSUE THREAD

**Issue by phillipp-oliveira** [frontendbr/vagas#453]
## Descrição da vaga

Buscamos developers apaixonad@s por tecnologia e trabalhar com o que há de melhor, pessoas que queiram crescer e aprender com a gente.

Temos um time de alto nível, nosso stack é moderno e está sempre em constante evolução. Valorizamos o desempenho e comprometimento da equipe.

## Local

Presencial - Próximo à Av. Paulista (Av. Brigadeiro Luís Antônio)

## Benefícios

- Horários flexíveis

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento Javascript- Webpack
- React / Redux
- TDD
- Ser comprometid@ com o projeto e a qualidade do código.
- Experiência com times auto-gerenciáveis e metodologias ágeis (XP, SCRUM, Kanban, Lean).

**Desejáveis:**
- Ruby ou Elixir
- Functional & Reactive Programming

**Diferenciais:**
- Participar da comunidade open source

## Contratação

- PJ

## Nossa empresa

A EcoStage é líder no desenvolvimento de plataformas sócio-ambientais. Nossos projetos têm grande impacto em políticas e estratégias sobre o tema.

Somos uma empresa com ambiente descontraído e horários flexíveis. Você trabalhará em uma equipe pequena, multi-disciplinar e auto-gerenciável.

## Como se candidatar

Por favor aplique pela plataforma: https://ecostage.breezy.hr/p/e599e2233364-desenvolvedor-front-end

**Comment by phillipp-oliveira** [comment]
Continuamos a procura de desenvolvedores front-end.

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
