### ISSUE TITLE
[Hamburg | Remote] Front-end Developer — UX Engineer @ Factorial

### ISSUE THREAD

**Issue by dberri** [frontendbr/vagas#4532]
## Nossa empresa

Factorial is a technology partner and develops sophisticated digital products. We have been working with local and international customers since 2015 and have been growing steadily ever since.
Our team consists of people with different backgrounds and career paths, united by curiosity and passion for technology and digital innovation. We live New Work, appreciate personal responsibility and flexibility.

## Descrição da vaga

**Your tasks**
You take ownership of frontend solutions in a multi-disciplinary project team.
You plan frontend architectures and API integration in complex web applications.
You implement new features or improve existing components.
You write clean and understandable code using modern tools and workflows.
You collaborate closely with UX and visual designers.
You evaluate technical feasibility of feature requests.
You test and document your code.
You support your teammates with code reviews and pair programming.

## Local

Remote or Hamburg, Germany

## Requisitos

**Your profile**
- At least 3 years experience in writing JavaScript applications and websites.
- Intermediate to advanced knowledge of HTML, CSS and JavaScript.
- Proficiency in at least 1 major reactive JavaScript framework (We prefer Vue.js).
- Working self-organized, open-minded and communicative.
- Having an eye for design, accessibility and performance.
- Good communication skills in English (must) and German (nice to have).
- Experience in working in agile processes such as Scrum and Kanban.
- Ability to quickly become productive in different development environments.

## Benefícios

**What we offer you**
Extensive development possibilities in a fast-growing company
Experienced colleagues and a culture of exchanging experience
A great team and a pleasant working atmosphere
An annual training budget at your own disposal
Flexible time management
A beautiful office with garden and roof terrace in the heart of Ottensen
Very good coffee, various drinks, organic fruit & kicker 
A great cook who prepares lunch for us every 2 weeks.

## Contratação

A combinar

## Como se candidatar

You do not have to match all the listed requirements exactly to apply. Please send your application including your aspired start date and salary expectations by email to our HR Manager Seda. You can reach her at jobs@factorial.io. We value real-life, working code higher than academic titles.

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
