### ISSUE TITLE
[Porto Alegre - Remote] Front-end Developer [Azion]

### ISSUE THREAD

**Issue by julsngst** [frontendbr/vagas#4534]
## Nossa empresa

A Azion é uma plataforma de Edge Computing, que permite ao usuário construir e executar suas aplicações Serverless na nossa edge. A empresa começou com o foco em P&D e nos últimos anos começou a focar na sua expansão e dos seus produtos. E com isso, tivemos um grande crescimento e em novembro do ano passado a Monashess e a Qualcomm decidiram investir na Azion, acreditando no potencial da empresa e dos nossos produtos. Atualmente a maior parte dos e-commerces e as maiores plataformas LATAM entregam seu conteúdo via Azion, temos mais de 100 clientes, trabalhando com empresas como Magalu, Submarino (e-commerce), Kroton (educação), Grupo RBS (mídia), Banco Agibank na área de segurança e entre outros. Nossa atuação está em todo território nacional, na LATAM e nos EUA.

## Descrição da vaga

Você atuará na arquitetura, criação, componentização e manutenção de diversos sistemas, incluindo plataformas de autenticação, Marketplace, gerenciamento de configuração em Edge de clientes, dentre muitos outros desafios. Você terá envolvimento em todo o processo, desde a análise do problema até o desenvolvimento, teste, monitoramento, e sua entrega em ambiente de produção. Prezamos pela qualidade, resiliência e segurança das nossas aplicações e produtos, então se você se identifica com esse perfil e topa os desafios, venha fazer parte do nosso time! 

## Local

100% Remoto

## Requisitos

**Obrigatórios:**
Experiência com desenvolvimento frontend (HTML/CSS/JS);
Experiência com VueJs ou outro framework de mercado (React, Angular);
Experiência com desenvolvimento em ambiente UNIX;;
Conhecimento de componentização e boas práticas de UI e UX;
Conhecimento de Client-Side APIs (DOM, Storage, XmlHttpRequest etc);
Conhecimento de modelos de API REST;
Conhecimento de requests HTTP;
Conhecimento de GIT, fluxos de desenvolvimento em times;
Conhecimento de fluxos de CI e CD;
Boa organização de código e conhecimento de boas práticas;
Conhecimento de ferramentas de teste;
Inglês intermediário ou avançado.

**Desejáveis:**
Conhecimento de utilitários e serviços de cloud (AWS, GCP, Digital Ocean etc);
Conhecimento de containers e conceitos relacionados (Docker, Compose, Kubernetes);
Conhecimento de banco de dados SQL e NoSQL;
Conhecimento de API GraphQL;
Conhecimento de storybook.

## Benefícios

- Plano de saúde
- Plano odontológico
- Seguro de vida
- VR/VA com valor mensal
- Auxílio para aulas de inglês e espanhol

**Diferenciais:**
- Horários flexíveis
- R$200 para você personalizar a sua mesa de trabalho para ficar com o seu jeitinho
- Geladeira com refrigerante, água, cerveja, chás, cafés e etc, grátis para quem for no escritório

## Contratação

CLT

## Como se candidatar

Enviar email para julia.angst@azion.com com "Vaga Front-end" no assunto, seu CV e seu telefone para contato.

## Tempo médio de feedbacks

Costumamos dar o feedback em até 1 semana.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
