### ISSUE TITLE
[São Paulo] Front-end Developer no Banco Santander 

### ISSUE THREAD

**Issue by luansmr** [frontendbr/vagas#4535]
## Nossa empresa

Já pensou em trabalhar em um lugar em constante **transformação digital**, inovação, colaboração e crescimento? **Aqui é o lugar!**

Se você tem paixão por tecnologia e pessoas, empatia, foco em resultados e gosta de mudanças, faça parte de tudo isso!

Estamos sempre inovando e buscando trabalhar com as melhores tecnologias do mundo. Nosso time de tecnologia conta com Agile coach, desenvolvedores Mobile, profissionais full stack, BPM, DevOps, Cloud e outros.

Nosso compromisso com a valorização da Diversidade está presente em todas as nossas oportunidades. Acreditamos no potencial humano para desenvolver talentos e gerar inovação para nossos clientes. Aqui você pode ser quem você é!

Se você se identificou #deumatch!

## Descrição da vaga

Buscamos Front-End Developer, com entusiasmo e energia para trazer soluções inovadoras, focadas em usuários do mercado financeiro.

Procuramos pessoas com alto nível de comprometimento, foco na solução de problemas e interesse em atuar em projetos de grande porte, e que estejam disposto a crescer junto com a gente, pois aqui você vai ter muita voz e responsabilidade logo de cara!

Nossos desafios crescem no ritmo do nosso crescimento e isso faz com que a gente seja um time muito unido e cooperativo, sempre aprendendo, empreendendo e crescendo juntos!

## Local

Escritório: [SP], [São Paulo], [Centro Histórico de São Paulo]

## Requisitos

**Obrigatórios:**
- Angular
- TypeScript
- Javascript
- HTML5
- SASS
- CSS

**Desejáveis:**
- Testes unitários
- Angular Elements
- Jira

**Diferenciais:**
- Webviews

## Benefícios

- Plano Odontológico
- Plano de Saúde
- Seguro de Vida
- Vale Transporte
- Vale Refeição
- Auxílio creche

**Diferenciais:**
- Horário flexível
- PLR
- Dress Code

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um email para luan.sommerhauzer@santander.com.br com seu CV anexado - enviar no assunto: Vaga - Front end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 20 dias após cada processo.
E-mail para contato em caso de não haver resposta: luan.sommerhauzer@santander.com.br

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by ReginaldoViana** [comment]
O email retorna, deve ter algo errado.

**Comment by luansmr** [comment]
> O email retorna, deve ter algo errado.

Desculpa, estava faltando o .br

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
