### ISSUE TITLE
[REMOTO] Desenvolvedor Front-End na TO Brasil

### ISSUE THREAD

**Issue by NerdProgramador-com-br** [frontendbr/vagas#4536]
## Descrição da vaga

- Ensino superior em Tecnologia da Informação
- Sólida experiência com Javascript;
- Sólida experiência com HTML/CSS; 
- Domínio de gerenciamento de estados; 
- Conhecimento em Angular 7+; 
- Conhecimento de GIT; 
- Conhecimento de Testes unitários;  
- Conhecimento de metodologia ágil.

## Local

Remoto

## Como se candidatar

Accesse a [Vaga de Desenvolvedor Front-End na TO Brasil](https://nerdprogramador.com.br/to-brasil-desenvolvedor-front-end/f61945c7-8429-4002-b705-ba6a3210a083) para mais informações.

## Labels
- Remoto

#### Alocação
- Remoto

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
