### ISSUE TITLE
[Porto Alegre] Front-end Developer na Bonaparte

### ISSUE THREAD

**Issue by eduardomello** [frontendbr/vagas#4538]
## Nossa empresa

A Bonaparte é uma agência que atua tanto no marketing digital quanto no desenvolvimento de soluções web. Há 10 anos no mercado, atuando em Porto Alegre, já colaboramos com marcas como Converse, Youcom, Coca-Cola, Facebook e Heineken.

## Descrição da vaga

Trabalhar na manutenção de Objetos Educacionais Digitais (OEDs) desenvolvidos em HTML.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiências com HTML/CSS/JS
- Experiência com Jogos HTML e Canvas

**Desejáveis:**
- Conhecimentos com jQuery
- Conhecimentos com jQuery-UI
- Conhecimentos com Interact

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para carlos.rosa@bonaparte.ag com seu CV anexado - enviar no assunto: Vaga OEDs

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
