### ISSUE TITLE
[Rio de Janeiro] Estágio - Front-End Developer na Sensorial Comunicação Digital

### ISSUE THREAD

**Issue by didiraja** [frontendbr/vagas#454]
## Descrição da vaga

Manutenção de páginas HTML e Blogs Wordpress
Criação de Landing Pages
Criação de peças de Mídia Online

## Local

**Presencial somente.** Shopping Downtown na Barra da Tijuca.

## Requisitos

**Obrigatórios:**
HTML, CSS e Javascript/jQuery
Bootstrap
Google WebDesigner ou Flash/Animate

**Desejáveis:**
Interesse em aprender novas tecnologias

**Diferenciais:**
Wordpress
Php
JS intermediário
GIT

## Benefícios

R$ 1000 +  VT

## Contratação

A combinar _(não sou o responsável por isso, haha)_

## Nossa empresa

A Sensorial Comunicação é uma agência digital plena, e conta com uma equipe de profissionais altamente qualificados. Somos uma equipe de criativos, planners de mídia, atendimento, social media, analistas de métricas e estrategistas de mercado. Temos completa estrutura e expertise para desenvolver planejamento de comunicação e de marketing digital adequados à demanda de cada cliente.

O objetivo principal da nossa agência digital é oferecer o serviço de Planejamento Estratégico de Marketing Digital.

## Como se candidatar

Mande currículo (e portfolio, se tiver) para criacao5@sensorialcomunicacao.com.br com "Estágio - Desenvolvimento Front-End"

**Comment by didiraja** [comment]
Amigos, como informado, vagas apenas presenciais e residentes do RJ.

**Comment by nandosangenetto** [comment]
Sem VR?

**Comment by didiraja** [comment]
@nandosangenetto Sem VR. 6 horas, o estagiário chega depois do almoço.

**Comment by andreyazevedo** [comment]
É possível fazer o estágio sem estar cursando alguma graduação?

**Comment by didiraja** [comment]
@andreyazevedo sim

**Comment by rafaelassumpcao** [comment]
A empresa que o fizer corre grande risco de se dar mal  se  contratar em
regime de estágio sem estar cursando a graduação... É muito mais plausível
contratar como programador

Em 04/08/2017 13:24, "didiraja" <notifications@github.com> escreveu:

**Comment by gmmoraes** [comment]
@didiraja ainda estão aceitando candidaturas?

**Comment by DaianeAlvesRJ** [comment]
já preencheram a vaga?

**Comment by LFeh** [comment]
Aberto ainda?
