### ISSUE TITLE
[REMOTO] Front-end Developer Angular 4+ na Platform Builders

### ISSUE THREAD

**Issue by Izah-Silva** [frontendbr/vagas#4546]
> Vaga Remota durante a pandemia

## Nossa empresa

Somos empreendedores e buscamos pessoas que não têm medo de mirar alto com metas audaciosas, que estão cansadas dos padrões tradicionais do mercado, nunca tiveram a oportunidade mas não desistiram diante das adversidades. Enxergamos soluções onde os outros só enxergam problemas. 

Os inconformados com o status quo, que queiram transformar realidades, sobretudo pessoas e estão abertos aos processos de mudança, que encaram com entusiasmo a ambição de crescer, são bem vindos entre nós.

Aqui, você pode, aliás você deve se expor! As fraquezas só se transformam em pontos fortes quando reconhecemos a necessidade de mudança. Vamos sempre errar rápido para acertar rápido. Reconhecendo que para inovar sempre, precisamos correr riscos! Então, queremos que você seja livre nesse terreno fértil para frutificar valor.

Nós vivemos da ousadia de provocar e temos propostas audaciosas, mesmo. Não temos clientes, mas sim amigos, que estão no topo da nossa cadeia de valor. Se interessou pelo nosso movimento de empreendedores? Veja nossas oportunidades! 

## Descrição da vaga

Estamos procurando uma Pessoa Desenvolvedora Angular para se juntar a nós na mudança que move o mundo, para que a criatividade e o crescimento possam inspirar cada vez mais pessoas a fazer mais daquilo que amam, construindo um roadmap de impacto e valor.

Aqui é o lugar onde suas ideias são bem vindas, frutos da construção do pensamento coletivo, prontas para ganharem vida.

Saca só os requisitos que pensamos:

#SejaBuilder

## Local
[REMOTO]

## Requisitos

**Obrigatórios:**
Angular (4+)
Fluência em TypeScript
Forte conhecimento no consumo de APIs RESTful
Conhecimento da biblioteca RXJS, e programação reativa
Criação de layout responsivo
Versionamento de código com Git
Metodologias ágeis

**Desejáveis:**
Conhecimento em Firebase (Analytics, Crashlytics, etc)
Experiência em linguagens nativas e construção de bridges
Animações (Angular Animations)

**Diferenciais:**
Oportunidades reais de empreender e impactar
Fazer parte de uma comunidade de empreendedores de ponta, o Movimento
Inovação e criação liberados
Participar de um processo único de geração de valor
Contribuir na criação de métodos disruptivos
Colocar suas ideias no mercado, na prática! :)
Possibilidade de Profit share em novos Negócios
Prestador de Serviços (PJ)
Flexibilidade de horário

## Contratação

PJ

## Como se candidatar

Candidate-se através do link: https://bit.ly/2VUZDu8

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
