### ISSUE TITLE
[Belo Horizonte] Front-end Developer na SysMap Solutions

### ISSUE THREAD

**Issue by ngomes28** [frontendbr/vagas#4549]
> Vaga Remota durante a pandemia

## Nossa empresa

Nós, aqui da SysMap, temos paixão por #inovação e sempre buscamos excelência em tudo o que fazemos. São mais de 20 anos de experiência no mundo da tecnologia, criando relacionamentos duradouros, trabalhando para desenvolver talentos, proporcionar oportunidades e influenciar vidas positivamente.
Gostaria de fazer parte de uma empresa que te desafia a transformar o mundo através da tecnologia?
Então venha para o nosso time!

## Descrição da vaga

Senior Front-End Developer, para atuar em uma squad ágil de desenvolvimento de sistemas para o segmento financeiro.
Após a pandemia, será adotado modelo de trabalho híbrido (remoto com idas ao cliente).

## Local

Híbrido [Minas Gerais], [Belo Horizonte], [Lourdes]

## Requisitos

**Obrigatórios:**
- 4 anos de experiência com Desenvolvimento Front-End
- Angular.js
- Angular 10
- DDD/TDD
- APIs REST
- SQL Server
- GIT
- Scrum

**Desejáveis:**
- Arquitetura Hexagonal

## Benefícios

- Plano de Saúde Bradesco
- VR de R$ 22,70/dia
- Vale Alimentação ou Combustível
- Plano Odontológico

## Contratação

CLT Full

## Como se candidatar

Por favor envie um e-mail para natalia.gomes@sysmap.com.br OU recrutamento@sysmap.com.br com seu CV anexado - enviar no assunto: Front-End BH
Ou, envie seu CV pelo WhatsApp: (11) 98491-0400.

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
