### ISSUE TITLE
[Porto Alegre] Front-End Developer na [Agência Kiweb]

### ISSUE THREAD

**Issue by agencia-kiweb** [frontendbr/vagas#455]
## Descrição da vaga

Buscamos desenvolvedor com conhecimento nas seguinteslinguagens: HTML5, CSS3, Jquery, Bootstrap, AngularJsO desenvolvedor trabalhará com projetos web como sites, sistemas online e criação de aplicativos mobile.É importante ter interesse em aprender novas linguagens, ter comprometimento com prazos e qualidade.Desejável: Angular2, Ionic2A empresa oferece VR e VT.

## Local

Petrópolis, Porto Alegre - RS

## Benefícios

VT, VR, 1 hora de almoço, escolha maquina Window ou Mac, ótimo ambiente.
- ...

## Requisitos

**Obrigatórios:**
- HTML5, CSS3, Javascript, Bootstrap, AngulaJS

**Desejáveis:**
- PHP, MySql, Ionic

## Contratação

CLT

 

## Como se candidatar

Por favor envie um email para comercial@kiweb.com.br com seu CV anexado - enviar no assunto: Vaga FRONT

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
