### ISSUE TITLE
[São Paulo] Front-end Developer - Angular na MJV Tecnology

### ISSUE THREAD

**Issue by Ys2801** [frontendbr/vagas#4550]
## Nossa empresa

Somos a MJV uma empresa focada em tecnologia e inovação, com mais de 21 anos no mercado, com escritórios no Rio de Janeiro, São Paulo, Curitiba, Roma, França, Londres, Colômbia e Estados Unidos. Atuando dentro dos maiores clientes como Bradesco Seguros, Santander, Sulamérica, Safra.

## Descrição da vaga

Sobre o desafio �

Será responsável pelo desenvolvimento de novos projetos e manutenção aos mesmos.

Pra gente dar #match precisamos que você conheça ✅

Conhecimentos necessários: Front end (Angular 2+, HTML, CSS, Javascript). Programar interfaces de Web e ferramentas de edição de imagem. Executa a manutenção dos sistemas, fazendo eventuais correções necessárias.

## Local

Home Office 
## Requisitos

**Obrigatórios:**
- Experiência com Angular

## Benefícios

- Plano de saúde
- Plano Odontológico
- Seguro de vida
- VR 

## Contratação

CLT

## Como se candidatar

Por favor envie um email para yasmin.ferreira@mjv.com.br com seu CV anexado - enviar no assunto: Vaga NodeJS

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
