### ISSUE TITLE
[São Paulo] Desenvolvedor .Net + Angular/Angular JS [CAMARASYS Tecnologia]

### ISSUE THREAD

**Issue by rhcamarasys** [frontendbr/vagas#4551]
## CAMARASYS Tecnologia

Atuante no desenvolvimento de soluções sistêmicas, nascemos de um sonho pela busca da constante inovação e acesso à tecnologia para todos, proporcionando aos nossos clientes um direcionamento com mais integridade e segurança.

## Descrição da vaga

Desenvolvedor .Net + Angular/Angular JS
## Local
[São Paulo], [São Paulo], [Alphaville]
## Requisitos
**Obrigatórios:**
Ensino Superior completo na área de exatas. 
- Desenvolvimento em .NET Full Framework.
- Desenvolvimento em Angular JS.
- Linguagem C#
- Web API Rest
- Orientação a objetos
- Aplicações em camadas

Competências comportamentais obrigatórias:
- Boa comunicação
- Resiliência
- Proativo

**Desejáveis:**
- Metodologia Agile Scrum.
- Azure DevOps, para o gerenciamento do ciclo de vida das aplicações.
- Github, para o controle de versionamento dos scripts de desenvolvimento das aplicações.

**Diferenciais:**
- projetos opensource

## Como se candidatar
Por favor envie um email para rh@camarasys.com.br com seu CV anexado - enviar no assunto: Vaga A117

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@camarasys.com.br

#### Alocação
- Remoto

#### Regime
- PJ

- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
