### ISSUE TITLE
[REMOTO] Front-end Developer na Studos/Arco Educação

### ISSUE THREAD

**Issue by keitoliveira** [frontendbr/vagas#4553]
## Nossa empresa

Nós somos uma plataforma educacional focada em facilitar a vida dos professores e coordenadores, criando ferramentas de apoio para otimizar os processos pedagógicos e, também, na melhora do desempenho dos alunos.

Entendemos que todos devem ter acesso a novas formas de estudar, sendo assim, desenvolvemos uma plataforma que potencializa o ensino na sala da aula e também fora dela. 

Atuamos nos segmentos de Pré-Vestibular e ENEM, Concursos Públicos, Concursos Militares, OAB e Ensino Superior. 

Hoje, já contamos com mais de 1 milhão usuários em todo Brasil.

## Descrição da vaga

- Participar de planejamentos junto aos demais times, do desenvolvimento do nosso design system, refactoring de nossas plataformas e das integrações com sistemas parceiros
- Participar da documentação técnica e de processos dentro do time
- Ter comunicação clara e descomplicada, disseminar conhecimento através de pair-programming, code review ou treinamento, ajudando os desenvolvedores a avançar em suas carreiras

## Local

Remoto.

## Requisitos
Pedimos conhecimento naquilo que realmente usamos 🚀

**Obrigatórios:**
- 3+ anos de experiência com desenvolvimento Front-End
- Conhecimento sólido em HTML e CSS
- Conhecimento em JavaScript
- Conhecimento em React
- Conhecimento em práticas de acessibilidade
- Boa comunicação

**Desejáveis:**
- Conhecimento em práticas de performance

**Diferenciais:**
- Conhecimento em testes unitários e de integração com Jest e/ou Cypress
- Conhecimento em module bundler Webpack e/ou Rollup
- Participação anterior em desenvolvimento de design system
- CSS-in-JS
- Lerna
- Storybook
- TypeScript
- Conhecimento em criação e manutenção de CI/CD para projetos Front-End e publicação de pacotes através do NPM ou GitHub
- Conhecimentos em Graphql

## Benefícios

- *Vale Refeição ou Vale Alimentação
- Plano de saúde
- Plano Odontológico
- [Zenklub](https://zenklub.com.br/) com direito a 2 consultas grátis e 2 sessões com custo reduzido
- Gympass
- *Auxilio Home Office
- *Auxilio educação em acordo com o Plano de Desenvolvimento Individual criado em conjunto com a liderança
- Folga de aniversário
- Folga de 5 dias corridos em 2021 alinhado com a liderança
- Se precisarmos que vá em nossa sede, arcamos com todos os custos

*Creditados através do serviço de benefícios flexíveis [Flash](https://seja.flashapp.com.br/beneficios/solucao-beneficios).

## Contratação

CLT

## Como se candidatar

Enviar um e-mail para keit@arcotech.io com assunto "Vaga Front-End Developer" com pretensão salarial atual, o link do Github caso tenha projetos open source que deseje apresentar e link do LinkedIn.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias úteis após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
