### ISSUE TITLE
[Uberaba] Full-Stack Developer na Grão Direto 

### ISSUE THREAD

**Issue by felpshn** [frontendbr/vagas#4554]
## Grão Direto

Assim como a Uber revolucionou o mercado de transporte, o Nubank o mercado bancário e várias outras startups mudaram seus respectivos mercados, a Grão Direto revoluciona o agronegócio conectando toda a cadeia de comercialização. Através da tecnologia, vendedores e compradores podem negociar grãos de forma muito mais rápida e eficiente, tornando a compra e venda de milho, soja, sorgo e outros grãos muito mais moderna e segura!

## Descrição da vaga

Você irá integrar a equipe de engenharia da Grão Direto, que utiliza metodologia ágil de desenvolvimento na entrega de produtos de alta tecnologia. Nossos engenheiros atuam tanto em frontend quanto backend durante todo o ciclo de vida da solução, e encaram desafios complexos na computação em larga escala, utilizando habilidades em estruturas de dados, algoritmos e programação orientada a objetos. Nosso time é colaborativo por natureza, e você terá voz ativa durante todo o processo, sempre com o objetivo de construir produtos que promovam excelentes experiências para nossos clientes.

## Local

[PRESENCIAL] UBERABA, MINAS GERAIS

## Requisitos

**Obrigatórios:**
- Conhecimento de conceitos básicos como estrutura de dados, algoritmos, orientação a objetos, etc;
- Conhecimento em estrutura e consulta em Bancos de Dados relacionais.
- Experiência em desenvolvimento de aplicações WEB, seja frontend ou backend.
- Linguagens de desenvolvimento web HTML/CSS/JavaScript.
- Habilidade para comunicação e escuta ativa.

**Desejáveis:**
- Experiência em boas práticas de desenvolvimento de software, como TDD, Clean Code, Padrões de Projeto e SOLID;
- Experiência nas linguagens Angular, Node.js e Ionic.
- Experiência em banco de dados MySQL (criação de views, procedures, functions, etc).
- Contato com ambiente em nuvem Amazon AWS.
- Vivência de cultura DevOps e automação de tarefas de integração e entrega.
- Conceitos de metodologias ágeis (Scrum/Kanban).
- Inglês intermediário.

## Benefícios

- Existe sim ALMOÇO GRÁTIS! ;) (Dois restaurantes conveniados para você escolher seu almoço todos os dias).
- Sua SAÚDE em primeiro lugar! (Plano de saúde - a mensalidade do seu plano você deixa com a gente).
- Com SORRISO tudo fica melhor! (Plano Odontológico - esta mensalidade também é nossa).
- Apoiamos ainda mais seu DESENVOLVIMENTO PESSOAL! (Terapia, academia, cursos, livros além de outros itens que podem ajudar no seu desenvolvimento mental e físico, nós te incentivamos com um valor mensal).
- Não é de Uberaba e está de MUDANÇA pra cá? (Auxílio Mudança - Apoio financeiro para te ajudar com as despesas da mudança + nosso apoio para você conhecer a nova cidade, encontrar um ótimo lugar para morar e realocar a família.).

**Diferenciais:**
- Ambiente descontraído
- Horário flexível
- Sala de jogos
- Time jovem e engajado

## Contratação

CLT Período Integral (8hrs/dia)

## Como se candidatar para essa vaga

https://graodiretovagas.gupy.io/candidates/jobs/621308/apply

## Também temos vagas para outros setores relacionados a tecnologia!!!

https://www.graodireto.com.br/vagas/vagas-disponiveis.php

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.
E-mail para contato em caso de não haver resposta: ursula@graodireto.com.br

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by felpshn** [comment]
Felipe, a vaga já foi preenchida. Obrigado.
