### ISSUE TITLE
[RJ/REMOTO] Desenvolvedor(a) Frontend - Health Tech

### ISSUE THREAD

**Issue by frisone3d** [frontendbr/vagas#4556]
**QUEM SOMOS**
---
**A PEBMED É UMA DAS HEALTH TECHS QUE MAIS CRESCEM NO BRASIL** 🚀💜
Nossa história começou em 2012 com três médicos ainda na faculdade querendo multiplicar conhecimento entre os amigos. Desde o início, entendemos que todos podem ensinar e criamos um propósito que conecta todo nosso time de #mestres: transformar a saúde no Brasil através da tecnologia, apoiando médicos e profissionais da saúde para tomar decisões, por meio de diagnósticos que impactam positivamente milhares de pessoas ao redor do mundo!

Conteúdos feitos por médicos para médicos para auxiliar o profissional de saúde na hora da tomada de decisão clínica. Utilizamos aplicativos e ferramentas eficientes voltadas para um melhor desempenho do profissional de saúde, de maneira dinâmica e para valorizar seu tempo.

Dá um orgulho enorme saber que tudo que fazemos por aqui é pra cuidar da saúde das pessoas e ajudar os médicos em sua atuação profissional.

Nossos produtos são: _Portal PEBMED, Whitebook e Nursebook_.  

**NOSSOS NÚMEROS**
---

Atualmente, temos mais de 520 mil usuários nas nossas plataformas e caminhamos para nos tornar referência digital na América Latina.

Você sabia que 1 em cada 3 médicos utilizam nossa plataforma? 

Somos a ferramenta número 1 na tomada de decisão clínica!

**Há quatro anos, o Whitebook está no Top 10 dos apps de maior receita gerada no Brasil.** 

**PORQUE TRABALHAR COM A GENTE**
---

Valorizamos pessoas com um propósito de vida, vontade de ir além, que amam o que fazem e que possuem valores claros e transparentes. Aqui na PEB somos uma verdadeira família e temos muito orgulho de todos que fazem parte do crescimento do nosso negócio dia após dia.

Esperamos que você se sinta estimulado a fazer parte do nosso time, com autonomia para tirar suas ideias do papel sem se preocupar com burocracia e hierarquias rígidas, assumindo desafios pra crescer junto com a gente.

 

E aí, curtiu? Que tal transformar a saúde com a gente?! 💚

**DESCRIÇÃO DA VAGA**
---
***Quais serão suas responsabilidades e desafios?***

Você sabia que desenvolvimento de software vai além de programação? Aqui na PEB buscamos candidatos que sejam apaixonados por tecnologia e utilizem boas práticas de Engenharia de Software, Arquitetura, Algoritmos, Metodologia Agil no desenvolvimento do produto.

**REQUISITOS E QUALIFICAÇÕES**
---
***O que você precisa ter?***

- Entendimento de processos e boas práticas de Engenharia de Software;
- Capacidade analítica e raciocínio lógico;
- Conhecimento de sistemas web e protocolo HTTP / web-APIs
- Conhecimento em continuous delivery e infraestrutura com código;
- Sólido conhecimento em banco de dados e domínio de pelo menos uma linguagem;
- Experiência com infraestrutura em nuvem na AWS ou em algum outro cloud provider;
- Ser interessado(a) por todos os aspectos de Engenharia de Software: Backend, Frontend, Mobile, Cultura Devops - sem desconsiderar sua vocação natural para algum deles;
- Conhecimento em Docker;
- Conhecimento em testes automatizados;
- Conhecimento em Frameworks Javascript (Angular.js, React.js, Vue.js, etc…);
- Diferencial: Conhecimento em Kubernetes; Domínio de sistemas operacionais baseados em Linux/Unix; Conhecimento em CI/CD.

**INFORMAÇÕES ADICIONAIS**

***Ao entrar nessa jornada com o nosso time de #Mestres, você vai:***

- Trabalhar em uma empresa de tecnologia, em um ambiente leve e descontraído e vivenciar a experiência de uma realidade a favor do #reconhecimento e da #inovação;
- Nosso time é #colaborativo e nossa #liderança é próxima (quando você olhar pro lado, nosso CEO ou um dos Heads devem estar trabalhando pertinho de você);
- Gympass para te ajudar a cuidar da sua saúde;
- Dress code da forma que você se sentir mais confortável;
- Flexibilidade para home office e horários;
- Bolsa-curso;
- Bolsa para participação em eventos;
- Plano de saúde e odontológico;
- Seguro de vida;
- Vale Refeição e/ou Vale Alimentação;
- Acesso a cursos gratuitos através da plataforma da UCA;
- Pacote salarial competitivo;
- Bônus diferenciado, conforme política da empresa;
- Selo GPTW: Estamos entre as “Melhores Empresas para Trabalhar"

Se você se interessou e atende aos critérios citados acima, queremos conhecê-lo(a) ;)
Aqui na PEB a gente preza pela igualdade de oportunidades em todos os sentidos! 

Por isso, a gente não faz distinção de raça, cor, religião, gênero e identidade de gênero, nacionalidade, deficiência, orientação sexual ou idade. #VemPraPEB

**LOCAL DE TRABALHO**
---
Botafogo, RJ

_**Devido ao COVID-19 estamos trabalhando no formato remoto por período indefinido**_

**COMO SE CANDIDATAR**
--
Por favor enviar o email com o currículo para vagas.tech@pebmed.com.br com o título: **[Desenvolvedor(a) Web Frontend]**

Tempo médio de feedbacks
Nosso processo é bem rápido e costumamos não ser burocráticos.
Costumamos enviar feedbacks em até 2 dias após cada processo. E o processo no total costuma levar de 1 a duas semanas.

Labels
Alocação
Alocado
Remoto
Regime
CLT
Nível
Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
