### ISSUE TITLE
[Remoto] Front-end Developer na Pier

### ISSUE THREAD

**Issue by josianepenachio** [frontendbr/vagas#4557]
## Nossa empresa

A Pier nasceu pra levar leveza pra vida das pessoas e queremos que elas vivam a vida do jeito que elas mais gostam! Somos um seguro sem desconfiança, que as pessoas têm porque gostam de ser livres para serem elas mesmas. Oferecemos coberturas inteligentes, criadas com tecnologia Pier: menos papelada, menos preocupação, mais agilidade e capacidade de entregar produtos que cumprem o que prometem e ainda te arrancam suspiros de alegria.

## Descrição da vaga

**Missão:** Manter a qualidade de código e engenharia num nível invejável de excelência sem abrir mão da autonomia e produtividade.

- Escrever código para implementar, junto com times de produto, novas funcionalidades nas nossas plataformas e construir uma nova maneira de oferecer seguros no mundo
- Abertura para trabalhar com Back-end, Infra, o que o time precisar (T-shaped model)
- Manter o front-end resiliente, testado, e capaz de suportar o nosso crescimento (já crescemos 10x a quantidade de hits desde janeiro e devemos crescer mais umas 10x até o fim do ano)
- Ajudar a construir decisões de arquitetura dos nossos aplicativos e sites

**Você se encaixará no time se:**
- Tiver conhecimento de tecnologias de front-end e bibliotecas como React e React Native
- Conseguir garantir qualidade de código seguindo padrões que garantem agilidade e revisando PRs
- Buscar promover legibilidade escrevendo código de qualidade que será lido por outros desenvolvedores da equipe, assim disseminando conhecimento do framework
- Escrever código para implementar novas soluções para nossos membros e construir uma nova maneira de oferecer seguros no mundo
- Aumentar nossa eficiência e produtividade!
- Tiver curiosidade e humildade intelectual, autonomia para tomada de decisão e cooperação
- Tiver senso de dono(a) de suas entregas
- Valorizar aprendizado constante

## Local

Ficamos em Pinheiros - São Paulo/SP mas somos distribuídos! (trabalhamos de forma 100% remota)

## Requisitos

- 4-5 anos de experiência como Front-End Developer
- Conhecimento em React e React Native, NextJS, Ruby on Rails (importante: não necessariamente conhecer/ter experiência com tudo isso).

## Benefícios

- Plano de saúde e odontológico da SulAmérica
- Gympass
- Benefício flexível de 1,3k por mês para cultura, mobilidade, refeição, alimentação e saúde
- Infraestrutura de trabalho remoto + R$ 150,00 por mês
- Incentivos à educação
- Possibilidade de se tornar sócio(a)

**Diferenciais:**
- Mais de 35% da empresa possui stock options
- Dados de salários e stocks são 100% visíveis para qualquer um
- Agendas são abertas e disponíveis para todos
- Organize seus horários como quiser: trabalhamos de forma distribuída e assíncrona :)

## Contratação

CLT a combinar

## Como se candidatar

Acesse https://jobs.lever.co/pier/182db30e-c4e9-41e0-a613-fb06cb44cb51 para se candidatar!

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
