### ISSUE TITLE
[Florianópolis/SC] Desenvolvedor C++ na SUNTECH

### ISSUE THREAD

**Issue by ribeiroaana** [frontendbr/vagas#456]
## Descrição da vaga

O que acha de ajudar a gente a fazer do mundo um lugar mais seguro? Criamos nossos produtos voltados a esta missão e procuramos pessoas que se identifiquem com ela!

Estamos buscando programadores para a nossa área de produto que estejam a fim de fazer a diferença e vivenciar uma experiência única de desenvolvimento – não só de produto, mas pessoal e profissional também. Desenvolvemos soluções com alta tecnologia para as áreas de Defesa e Segurança (sim, tipo CSI). São plataformas robustas, escaláveis e ágeis que fornecem suporte estratégico e operacional para que analistas e equipes de inteligência e segurança possam detectar, remediar, prever e proteger a população. Aqui na Suntech você terá a oportunidade de vivenciar o dia a dia de uma multinacional, participando do desenvolvimento de um produto de nível internacional.

E aí, a fim de trabalhar com desafios de verdade? Estas são algumas das atividades:

- Desenvolvimento de produtos, envolvendo protocolos de comunicação, APIs e soluções na àrea de telecomunicações e segurança;
- Planejamento e desenvolvimento de testes de integração;
- Pesquisa de novas aplicações para componentes e protocolos na àrea de telecomunicações e segurança.

## Local

Centro, Florianópolis/SC

## Benefícios

- Fazer parte de um time global, desenvolvendo não só suas habilidades técnicas, mas também sua capacidade de comunicação e interação com outros países;
- Ter a possibilidade de pesquisar e desenvolver novos produtos;
- Ambiente que estimula o equilíbrio entre o trabalho e a vida pessoal;
- Benefícios para deixar o seu dia mais saudável: frutas, massagens, ginástica laboral;
- Banco de horas e Participação nos lucros e resultados;
- Pacote de benefícios tradicionais com valores diferenciados: VT, VR/VA, Plano de saúde, Plano odontológico, Seguro de vida.

## Requisitos

- Linguagens C++/Python e Linux. Porém o mais importante é que você tenha flexibilidade e interesse para estar sempre aprendendo novas tecnologias;
- Experiência com programação de redes de computadores;
- Experiência na área de Telecomunicações e com sistemas distribuídos;
- Be fluent in English because we are a multinational, yeah o/

## Contratação

CLT

## Como se candidatar

Por favor se aplique na vaga neste link: https://suntech.recruiterbox.com/jobs/fk0mb2e/

**Comment by rubenmarcus** [comment]
@LFeh  essa vaga ta errada não tá?

**Comment by eduardojmatos** [comment]
@rubenmarcus sim...

**Comment by eduardojmatos** [comment]
Oi @ribeiroaana ,

O repositório tem finalidade de filtrar apenas vagas referentes a front end. Para mantermos um padrão no público, precisamos garantir ter vagas apenas para front ends e, inclusive, tu terá mais sucesso em outros fóruns. Alguns deles fizeram um fork desse repositório e estão mais focados no mundo de back end. 

Vou precisar fechar sua issue, infelizmente, 😞  se precisar falar a respeito para esclarecimentos de quaisquer dúvidas, fico a disposição.

Obrigado pela atenção, anyway e desculpe o incômodo.
