### ISSUE TITLE
[Remoto] Front-end Developer na OmniChat

### ISSUE THREAD

**Issue by Rebaduy** [frontendbr/vagas#4563]
> Vaga Remota mesmo após a pandemia

## Nossa empresa

Em 2016 nasceu a OmniChat. Uma startup que traz um convite à evolução. Nascemos da necessidade de resolver um problema: deixar a experiência de compra verdadeiramente omnichannel. Unimos a consultoria da compra offline com a praticidade da compra online através do chat-commerce, fazendo com o que o novo digital seja, cada vez mais, uma realidade.

Ajudamos empresas a surpreenderem seus clientes com uma experiência incrível de atendimento e compra dentro dos apps de mensagens que eles utilizam.

Venha ser Omni, venha fazer parte desta evolução.

## Descrição da vaga

Desenvolvimento microsserviços; 
Realizar correções de bugs; 
Criação de funcionalidades novas; 
Monitorar as aplicações; 
Sugerir soluções e arquiteturas. 

## Local

Remoto

## Requisitos

**Obrigatórios:**
Experiência em desenvolvimento de aplicações SPA;
Experiência com Desenvolvimento de Software e Automação;
Ter trabalhado com AngularJS e Angular +2.X e amplo conhecimento em HTML, CSS e Javascript.

## Benefícios

- Plano de saúde
- Plano odontológico
- Seguro de vida
- VR de R$ 30/dia
- Incentivo aos estudos

**Diferenciais:**
- Demo Friday
- Sala de Descompressão

## Contratação

CLT à combinar

## Como se candidatar

Por favor envie um email para renata.baduy@omni.chat seu CV anexado - enviar no assunto: Vaga Front End

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: renata.baduy@omni.chat

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by Rebaduy** [comment]
Ainda estamos contratando.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
