### ISSUE TITLE
[Goiânia] Front-End Developer na CodeMiner42

### ISSUE THREAD

**Issue by fabricionaweb** [frontendbr/vagas#457]
## Descrição da vaga

A [CodeMiner42](http://codeminer42.com) conta com 10 escritórios por todo país **e agora também em Goiânia**. 
Queremos aumentar nosso time e para isso buscamos os melhores desenvolvedores Júnior, Pleno e Sênior.

## Local

**Presencial em Goiânia, Setor Bueno**

## Benefícios

- Vale refeição ou alimentação
- Plano de saúde top + dental
- Frigobar sempre cheio :P
- Investimento de carreira (livros, cursos, codeschool, egghead, aulas de ingles, etc)

## Requisitos

**Obrigatórios:**
- Conhecimento dos frameworks da atualidade (React, Angular, Vue, Ember, etc)
- Aquela bagagem do Front-End moderno (ES6, webpack, node, processadores, etc)
- Inglês

**Desejáveis:**
- Testes unitários
- Conhecimentos em Ruby on Rails

## Contratação

CLT

## Como se candidatar

Envie um email para fabricio.augusto@codeminer42.com com seu CV anexado e pretensão salarial

**Comment by cpdrenato** [comment]
Enviei meu currículo.

**Comment by cpdrenato** [comment]
Agora que visualizei seu e-mail, ja te responde la.ok!

**Comment by leoamrl** [comment]
Ainda à procura?

**Comment by fabricionaweb** [comment]
@leoamrl sim, estamos sempre contratando

**Comment by Pedro-Souza** [comment]
@fabricionaweb Ainda está aberta a vaga?

**Comment by leonardotessaroalves** [comment]
@Pedro-Souza ainda em aberto? urgente!!!!
https://docs.google.com/document/d/1pbRyb_eYwqpkKEg1yFfq5nq1Fmz30K68Bnh2hVDyVxk/edit?usp=sharing

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
