### ISSUE TITLE
[Remoto] Desenvovedor Front End Oi

### ISSUE THREAD

**Issue by VanessaSantolin** [frontendbr/vagas#4572]
A Oi acredita no poder da interação, no poder de conectar e mover pessoas, trazendo novas possibilidades de um futuro melhor. Passamos o dia conectados com pessoas, com a sociedade e com o mundo. Queremos incentivar essas conexões, porque ninguém é feliz sozinho.
Se você também possui esse espirito colaborativo venha  fazer parte do nosso time!

RESPONSABILIDADES E ATRIBUIÇÕES
##Qual será seu desafio aqui?
Exercer liderança técnica para definição de soluções de E-commerce (Web e Mobile);
Liderar e acompanhar as atividades dos projetos da área.

REQUISITOS E QUALIFICAÇÕES
##O quanto você já estudou até hoje?
Graduação completa em Análise de Sistemas, Tecnologia da Informação ou Ciência da Computação.

##Conhecimentos que não podem faltar:
Experiência em gerenciamento de projetos utilizando metodologia PMI e ágeis (Scrum e Kanban);
Experiência e conhecimento técnico para conduzir e liderar projetos e assuntos relacionados a e-commerce e aplicações Web e Mobile;
Experiência com arquitetura de sistemas complexos (corporativos), com muitas integrações, grande volume de transações e variedade de processos automatizados;
Experiência em gestão técnica de temas críticos da área preparando materiais e apresentações executivas.

##Habilidades que aumentam as suas chances:
Conhecimento em banco de dados relacional e não relacional;
Habilidade em negociação e gestão de conflitos;
Conhecimento sobre HTML, React.Js, Node.Js, REST, SOA, Java, JavaScript, SQL, MongoDB, WebLogic, Jenkins, GIT, Docker e Redis;
Conhecimento sobre técnicas e ferramentas para realização de testes automatizados em soluções web e mobile;
Conhecimento de arquitetura de microserviço;
Conhecimento de arquitetutura BFF;
Conhecimento em plataforma de edição e publicação de conteúdo (CMS) para canais digitais;
Conhecimento em salesforce.

INFORMAÇÕES ADICIONAIS
##Benefícios:
Aparelho celular e linha exclusiva Oi com pacote de dados
Plano de Carreira
Dress Code Casual
Oi Play
Participação nos Lucros
Home Office
Vale-transporte
Plano de Saúde, Plano Odontológico; Desconto em Medicação e Seguro de Vida
Ticket Refeição e Alimentação
Trilha de Capacitação e Desenvolvimento; Cursos Online - Treinamento
Clube de Desconto/Convênio com empresas parceiras
Auxílio-Creche
Previdência Privada
 

#VEMPRAOI
Nossa missão é criar novos futuros, levando a vida digital para todos. Por isso a inovação e a criatividade são as principais aliadas para promover experiências que melhorem a vida de pessoas e empresas em todo país. Se você gosta de pensar em soluções transformadoras e experiências únicas, e tem muita fibra para fazer acontecer, vem com a gente!

GENTE DE FIBRA
A Oi é feita de gente com garra, muita energia, disposição e versatilidade. Mas principalmente gente com fibra para encarar desafios, buscar a superação e fazer acontecer. Aqui dentro a gente se reinventa e, diante dos obstáculos, nós sempre mostramos a nossa força.

DIVERSIDADE NOS CONECTA
Aqui nos respeitamos e nos sentimos seguros para ser quem somos. Oferecemos um ambiente de trabalho plural, inclusivo e colaborativo, onde as pessoas podem ser autênticas e viver boas experiências. Criamos conexões que valorizam as diferenças.

APRENDER TODO DIA
Temos o desafio diário de buscar soluções acessíveis para problemas complexos. Acreditamos que o desenvolvimento contínuo do nosso time estimula a transformação do negócio. Por isso quem está na Oi, não para de aprender. 

CRIAR O FUTURO AGORA
Acreditamos que a tecnologia cria novas possibilidades de futuro. Por isso, levar a vida digital para dentro da casa e dos negócios faz parte do nosso propósito. Transformar a vida das pessoas faz parte da nossa ambição.

## Contratação
CLT

## Como se candidatar
Favor efetuar seu cadastro no link https://oi.gupy.io/jobs/659034

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 15 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
