### ISSUE TITLE
[São José dos Campos] Front-End React na [Capittale]

### ISSUE THREAD

**Issue by fernandofajardoangelo** [frontendbr/vagas#4573]
https://www.linkedin.com/posts/capittale_fintech-capittale-crescimento-activity-6777694135995441152-lK7K

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
