### ISSUE TITLE
[Remoto] Front-end Developer na Objective Solutions

### ISSUE THREAD

**Issue by gabrielahoffmann** [frontendbr/vagas#4574]
## Nossa empresa
A Objective é feita de pessoas. Somos um time comprometido e com foco no desenvolvimento de pessoas e lideranças. Somos apaixonados por tecnologia e criativos, gostamos de aprender e romper barreiras desenvolvendo soluções que resolvam os problemas e necessidades de nossos clientes com qualidade.

Algumas informações que você precisa saber:
- +300 colaboradores
- Uma das melhores empresas para se trabalhar no Paraná em 2019, segundo o GPTW
- Uma das empresas de TI que melhor remuneram no Brasil, segundo o Glassdoor
- Escritórios em São Paulo, Maringá, Curitiba e Chicago
- Referência em desenvolvimento ágil, com um case relatado no livro ‘The Scrumban [R]Evolution: Getting the Most Out of Agile, Scrum, and Lean Kanban’ do autor Ajay Reddy

## Descrição da vaga
- Atuar em todo o ciclo de desenvolvimento de demandas geradas por clientes internos ou externos, sendo responsável pela entrega da solução proposta ao cliente.
- Entender a necessidade do cliente, desenhar uma solução/nova demanda, identificando aderência aos produtos existentes, realizar a especificação funcional (alinhando-a com o cliente) e elaborar a especificação técnica.
- Responsabilizar-se pelas demandas (OS, bugs, atividades, entre outros...) desde seu início até conclusão, garantindo que os prazos e escopo sejam atendidos, observando qualidade, esforço e prazos definidos.

## Local
Remoto.

## Requisitos

**Competências Técnicas:**
- Design Orientação a Objetos;
- Experiência com desenvolvimento React;
- Padrões de desenvolvimento;
- Processos internos de desenvolvimento;
- Análise de requisitos (reuniões, condução para solução, separar problema de solução, priorização, faseamento);
- Análise de Risco.

## Benefícios
- Cartão flexível (VR/VA);
- Plano de Saúde;
- Plano Odontológico;
- Estacionamento;
- Vale Transporte;
- PLR;
- Seguro de vida;
- Auxílio home office;
- Auxílio academia;
- Programa de indicação de funcionários;
- Convênios de descontos com universidades, escolas de idiomas e restaurantes.

## Contratação
CLT

## Como se candidatar
Você pode se candidatar a vaga clicando [aqui](https://objective.gupy.io/jobs/769972?jobBoardSource=gupy_public_page).

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
