### ISSUE TITLE
[Remoto] Front-end Developer Angular Senior  na @ProJuris

### ISSUE THREAD

**Issue by vanessaliebl** [frontendbr/vagas#4575]
## Nossa empresa

SONHAMOS EM ELIMINAR INEFICIÊNCIAS DO JURÍDICO
A ProJuris é protagonista no mercado tecnológico jurídico. A empresa foi a primeira a desenvolver um software online voltado para advogados autônomos, escritórios de advocacia e departamentos jurídicos. Além disso, desenvolveu o primeiro chatbot com inteligência artificial integrado a um software jurídico do Brasil.

Descobrimos que a ineficiência é o principal obstáculo dos advogados, portanto, sonhamos em oferecer uma experiência jurídica mais eficiente, segura e descomplicada. 

## Descrição da vaga

Se você está atualizado com as novas tecnologias e quer trabalhar com o que há de mais novo no mercado, essa vaga é para você! Procuramos pessoas comprometidas, engajadas, que gostem de tecnologia e que tenham habilidades na construção de um código de qualidade e performático. Se você é engajado na resolução de problemas complexos e orientado ao desenvolvimento da codificação, aqui você vai encontrar as melhores tecnologias para se trabalhar.

## Requisitos

Angular 2+ (RxJS);
Javascript;
CSS;
HTML5;
Bootstrap;
NodeJS.

**Desejáveis:**
NgRx e/ou NgXs (gerenciamento de estado)
Java 8+
Spring Boot
Scrum ou Kanban
Git

## Benefícios

Vale alimentação ou refeição sem custo ao colaborador;
Plano de saúde (imediato) sem custo ao colaborador;
Plano odontológico opcional;
PPR anual;
Bolsas de Estudos
Seguro de Vida

**Diferenciais:**
Happy hour;
Um ambiente trabalho dinâmico com pessoas engajadas com os valores da empresa;
Horário flexível

Nós temos o compromisso com a diversidade e acolhemos todas as pessoas, sem discriminação por gênero, raça, religião, etnia, deficiência, idade, orientação sexual ou qualquer grupo da sociedade. Todas as pessoas são bem-vindas aqui! 💙

## Contratação

CLT ou PJ a combinar

## Como se candidatar

projuris.com.br/talentos

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível

- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
