### ISSUE TITLE
[Remoto] Angular Frontend Developer na ília Digital

### ISSUE THREAD

**Issue by thayssa-radmylla** [frontendbr/vagas#4576]
_**Sobre nós:**_

A **ília** é uma empresa que veio para facilitar. Somos especialistas em simplificar as interações entre pessoas, produtos e serviços por meio da tecnologia e do design.
Somos focados principalmente em três setores: serviços financeiros, mobilidade e seguros. Temos mais de 100 equipes dedicadas, sediadas no Brasil e na Espanha, que atendem clientes premium nas Américas e na Europa. 
Construímos soluções centradas nas pessoas, buscando a melhor experiência de usuário possível. Afinal, só assim alcançaremos o nosso objetivo: **tornar o mundo surpreendentemente mais simples**. 

**Responsabilidades e Atribuições:**

Nossos projetos em específico, tem como principal desafio a grandeza e o contato com clientes nacionais e internacionais. Conta com um time altamente capacitado em desenvolvimento de aplicações web e mobile em diferentes plataformas, onde o objetivo é entregar para o usuário uma plataforma que faça a diferença na vida das pessoas em qualquer hora e local.

**O que você precisa para fazer parte do nosso time?**

• Ter bastante experiência com Angular;

• Conhecimento consolidado com Javascript, CSS3 e HTML 5;

• Conhecimentos consolidado com consumo de APIs;

• Conhecimentos de estado em aplicações SPA;

• Implementação de layout Web/Mobile Responsivo;

• Conhecimentos com práticas de processo de desenvolvimento tais como GitFlow e Code Review.

**O que pode te diferenciar:**

• Conhecimento consolidado com implementação de testes;

• Conhecimentos em Testes unitários;

• Experiência em alguma metodologia ágil como Scrum e/ou Kanban e uso do JIRA.

**Informações adicionais:**

- Contrato de Trabalho CLT - 40h semanais com jornada flexível, sendo executado 100% de forma remota;
- 
- Senioridade: Pleno.

**Benefícios e Incentivos:**

- Assistência Médica e Odontológica extensivo aos dependentes;
- Vale Refeição/Alimentação;Seguro de vida;
- Programa de Incentivo ao inglês com atividades de mentoria e prática da língua;
- Programa de premiação a indicação de outros profissionais;
- Fóruns Técnicos: Neles o time compartilha práticas, estudos, projetos, ideias etc;
- Grupos de Chapter: Reúnem pessoas com skills similares para compartilhamento de ideias, práticas e experiências;
- Seu Niver, seu bolo!
- Byod: Alugamos o seu notebook pessoal (valor mensal) ou disponibilizamos uma máquina da empresa (livre escolha).

**Inscrições:** https://boards.greenhouse.io/iliadigital/jobs/4008166004

**Para tirar dúvidas:**  https://www.linkedin.com/in/thayssa-radmylla-61b18a153/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
