### ISSUE TITLE
[Remoto] Vue Front-End Developer na Psicologia Viva

### ISSUE THREAD

**Issue by brunorcunha-pv** [frontendbr/vagas#4577]
## Nossa empresa
O Psicologia Viva é uma startup que está em processo acelerado de crescimento, a Startup é investida por grandes grupos da área de saúde e atualmente levantou uma nova rodada que impulsionou ainda mais seu crescimento. Atualmente, a empresa é líder de mercado, já conta com uma operação internacional no Chile e atua com as principais operadoras de saúde do país.

No Psicologia Viva você irá trabalhar em uma startup líder em seu mercado e com desafios diários e metas desafiadoras.

## Descrição da vaga
Principais responsabilidades:
- Manutenção e criação de novas funcionalidades;
- Aplicação das melhores práticas de documentação de código desenvolvidas;
- Busca por novas ferramentas e técnicas para a melhoria contínua de nossos sistemas.

## Local
Remoto, Belo Horizonte/MG

## Requisitos
**Obrigatórios:**
- Experiência com desenvolvimento Vue.js
- Experiência em metodologia ágil.
- HTML, CSS, Sass e JavaScript;
- Conhecimentos em Vuex

**Diferenciais:**
- Graduação completa em TI;
- Experiência com desenvolvimento Nuxt.js

## Benefícios
- Trabalhar na empresa que está transformando a saúde mental na América Latina;
- Plano de saúde;
- No dress code;
- Programa de saúde emocional/apoio psicológico;
- Um ambiente incrível! <3

**Diferenciais:**
- Ambiente descontraído
- Horário flexível

## Contratação

PJ ou CLT.

## Como se candidatar

Por favor, realize o desafio do link https://drive.google.com/file/d/1SC78d3vk-I13o6KGR_y7lpfGCHJtThYZ/view seguindo as instruções do documento. Caso queira ver outras vagas em aberto, acesse: https://psicologiaviva.solides.jobs 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias.
E-mail para contato em caso de não haver resposta: brunoricardo@psicologiaviva.com.br

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
