### ISSUE TITLE
[remoto] Arquiteto(a) de Software – Sênior | Java e JS @ Supero

### ISSUE THREAD

**Issue by larissaaguiar** [frontendbr/vagas#4578]
Projeto: Atuar em um projeto global do segmento de saúde.

Responsabilidades:
Criar, manter e desenvolver o portfólio atual de componentes e bibliotecas
Conceituar, criar e manter módulos, bibliotecas, serviços e APIs, visando eficácia, facilidade de uso, desempenho, normalização e uma curva de aprendizado baixa.

Requisitos: 
Conhecimento avançado em Java, Javascript, HTML, CSS e vivência com RestAPI;
Em Java, ter trabalhado com Spring ou JavaEE e ter conhecimento aprofundado na tecnologia;
Em Javascript ter trabalhado com algum framework de mercado: React, Angular, Vue, entre outros.

Desejável:
Ter atuado como Arquiteto em trabalhos anteriores;
Conhecimento em inglês, leitura e escrita essencial, conversação será diferencial;
Conhecimento em React, AngularJS

Candidate-se em: https://bit.ly/3jaNKL9

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
