### ISSUE TITLE
[Joinville] Frontend Developer(React)/Full Stack Developer na NG Informática

### ISSUE THREAD

**Issue by jacksjm** [frontendbr/vagas#4579]
> Vaga Remota durante a pandemia

## Nossa empresa
A NG Informática é responsável pelos módulos de Manutenção de Ativos (SIGAMNT), Medicina e Segurança no Trabalho (SIGAMDT) e Gestão Ambiental (SIGASGA) do ERP Protheus (TOTVS). Iniciamos recentemente uma nova fase em um sistema SAAS, fazendo o lançamento do Keepfy e Quírons e amamos isso, iniciamos novos projetos e agora precisamos de você para compor nossa equipe!

## Descrição da vaga
Buscamos um Frontend Developer ou Full Stack Developer para se juntar ao nosso time. Você irá participar do planejamento, desenvolvimento e implementação de novas funcionalidades em nossa plataforma. Temos um grande caminho pela frente e você terá bastante liberdade para trabalhar com React (Hooks), GraphQL, Apollo e Typescript no desenvolvimento de aplicações em um ambiente que valoriza as boas práticas de programação (ex. testes automatizados, unitários, code review, etc) e metodologias de desenvolvimento ágil.

## Local
Av. Santos Dumont, nº 935, 3º Andar - Santo Antônio - Joinville/SC

## Requisitos

**Obrigatórios**:

- 1+ anos de experiência de mercado;
- Ter autonomia e pró-atividade;
- Conhecimento de React (Hooks);
- Conhecimentos em HTML, CSS e Javascript;
- Experiência anterior com API's RESTful com resposta em JSON;
- Experiência anterior com GraphQL e Apollo;
- Experiência anterior com Material.UI;
- Experiência anterior com Docker;
- Experiência com Git para versionamento de código;
- Inglês técnico (stackoverflow);
- Morar em Joinville ou ter disponibilidade para se mudar para a cidade;

**Desejáveis:**

- Familiaridade com desenvolvimento ágil;
- Ser autodidata;
- Conhecimento em Artemis;
- Conhecimento em Cypress, Detox e Jest;
- Conhecimento em Figma;
- Ter espírito empreendedor;
- Gostar de aprender e testar conceitos de UX.

**Diferenciais:**

- GitHub ativo;
- Functional programming (Ramda);
- Conhecimento de CLI, bundlers e automações de front-end;
- Banco de dados não relacional (MongoDB) e/ou relacional (PostgreSQL);

## Contratação
CLT a combinar

### Benefícios
- Vale alimentação ou refeição - 100% pago pela empresa
- Vale transporte se presencial ou combustível - 100% pago pela empresa
- Na pandemia Ajuda de Custo
- Plano de saúde - Bradesco Saúde Nacional -100% pago pela empresa - quarto privativo
- Plano Odontológico - 100% pago pela empresa
- PLR (Participação nos Lucros e Resultados)
- Auxilio Educação
- Auxilio Farmácia
- Convênio Farmácia
- Casa de praia em Piçarras-SC
- Seguro de vida
- Horário Flexível nas entradas e saída

**Diferenciais:**

- Ambiente extremamente propício à aprendizagem;
- Liberdade para sugerir novas tecnologias e melhorar o processo de desenvolvimento da equipe;
- Home-office;
- Mesa de sinuca para jogar nos intervalos e almoço (estamos em home-office, saudades sinuca :cry:);
- Horário flexível;
- Almoço de 1 a 2 horas;
- Café + bolachas/biscoitos + frutas todos os dias (Saudades frutas too :cry:);
- Microondas para esquentar seu almoço e lanches.

## O que usamos:

- GIT + Scrum + Kanbam + Azure DevOps
- Node + React + Typescript
- Github (open source)
- Slack

## Como se candidatar
Por favor, envie um email para curriculo@ngi.com.br com seu CV anexado e link do Github com o assunto: Vaga Frontend Developer(React)/Full Stack Developer - Github/ReactBrasilBR

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: <jackson.machado@ngi.com.br>

#### Alocação
- 🏢 Presencial
- 🏢 Remoto

#### Regime
- ⚖️ CLT
- ⚖️ A-Combinar

#### Nível
- 👨 Pleno

#### Tecnologias
- React
- Node
- GraphQL
- Apollo
- Typescript

**Comment by jacksjm** [comment]
ainda estamos com a vaga em aberto :tada:

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
