### ISSUE TITLE
[Remoto] Web-designer na Joyjet (HTML, css, WordP, React) 

### ISSUE THREAD

**Issue by PachecoRaphael** [frontendbr/vagas#4583]
## Descrição da vaga

Procuramos um web designer pra trabalhar em projetos diversios, em WordPress é HTML/CSS/React. Somos uma agência digital baseada na França. Temos projectos em todas as areas (BtoB é BtoC)

Somos todos muinto de boa se ajudando e trabalhando como um time. Todo mundo tem 30 dias de ferias por ano e ajuda pra ter um plano de saude legal. 

Precisa de ter no minimum 1 ano de experience em uma empresa como web designer.

All internal communications are in English, only the meetings are in Portuguese but 90% of the team is from Brazil.

https://joyjet.com/

**Test for all new candidates**: https://bitbucket.org/lixao/tech-interview-tests/src/master/webdesign/

## Local

Remoto em todo ou Brazil ou na europa.

## Benefícios

30 dias de ferias
Plano de saúde
Salario dependente da experiencia
Curso pago pela empresa
Vai melhorar bastante seu inglês

## Requisitos

**Obrigatórios:**
- HTML/CSS
- git
- Java-script
- PHP
- WordPress
- Able to read and communicate in English

**Desejáveis:**
- Conhecimentos em react

## Contratação

PJ a combinar

## Nossa empresa

Mais de 15 anos atrás, Marcio Marinho, criou a Joyjet, uma agencia digital com 15 pesoas trabalhando juntos pra projetos do mundo inteiro. O time esta baseado na Europa, Brazil e nos Estados Unidos.

## Como se candidatar

Por favor envie um email para jobs@joyjet.com com seu CV em anexo
Completando esse teste

https://bitbucket.org/lixao/tech-interview-tests/src/master/webdesign/

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias maximum depois de ter recebido o test concluido.

## Labels

- PJ
- Pleno
- Remoto
- Sênior
- Web-developper
- Tech-designer

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
