### ISSUE TITLE
[Amsterdam/Utretch/Rotterdam] - Senior FrontEnd Engineer na NonDutch

### ISSUE THREAD

**Issue by lucasbento** [frontendbr/vagas#459]
## Descrição da vaga

NonDutch is hiring multiple developers to work as consultants, we have multiple clients in all size including: ING, Rabobank, NS, KLM, The Telegraaf and more. It’s a fun, small, international and experienced team, most of the team give talks in conferences across the globe and we will motivate you to do the same.

## Local

Amsterdam/Utretch/Rotterdam (depends on the client) in The Netherlands.

## Benefícios

- Competitive salary based on your experience;
- Yearly bonus - (it doubles in your second year);
- 25 work-days of vacation witch is 1 month and half +/- (Different from Brazil, it is inside the calendar year, you don’t need to wait 1 year to have it);
- 2 yearly company trips - for conferences usually but we stay more time to enjoy the country - All paid (This year: Germany, Iceland, SF and probably Israel);
- 4 hack-days pear year (free to hack whatever you want);
- 4 guru-days (We hire people to give workshops inside the company. This year: CSS Wizardry from and Getify);
- €3k per year to spend with education, conferences and tech stuff;
- We pay you to lease a car or buy a car or pay for you trip expenses;
- Telephone bill up to $50 (Get a nice new iPhone on us);
- You’ll be able to choose the city (Amsterdam, Utretch or Rotterdam), company and technology you want to work on;
- Choose your hardware (Want a new 15’ Macbook Pro with Touch bar? - 20k reais in Brazil - just take it);
- We pay for you to talk in conferences (travel expenses usually);
- Free beers at the office;
- Be part of our meetups and conferences;
- 30% ruling application;
- Visa sponsorship.

## Requisitos

- 4+ years experience;
- 2+ years of experience on React or Angular;
- Deep understanding of JavaScript;
- Fluent English - you will work close with clients, you’ll need to communicate a lot.

## Nossa empresa

NonDutch helps organisations with their approach regarding frontend development. Be it frontend architecture, performance improvement, implementing new components, you name it and we're up for it! This common passion and desire has brought us together to help implement the next generation enterprise environment of tomorrow, starting today!

## Como se candidatar

Please submit https://goo.gl/forms/k6485hDW7hDTC9Si1 with your information and you will hear from us soon. 😄

**Comment by lucasbento** [comment]
Ainda estamos contratando, quem se interessar pode se candidatar aqui: https://goo.gl/forms/k6485hDW7hDTC9Si1.

**Comment by vinyguedess** [comment]
Preenchi

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by lucasbento** [comment]
Sim, vaga ainda aberta!
