### ISSUE TITLE
[Parcialmente Remoto em Curitiba ] Front-End Developer Jr na StartLaw

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#4590]
## Descrição da vaga: 
 <p>Olá, Somos a StartLaw! Acreditamos que grandes ideias transformam o mundo e, por isso, queremos ajudar elas a se consolidarem por meio de inovação e tecnologia, garantindo maior segurança, agilidade e controle da informação para esses agentes! De quebra, queremos transformar o mundo do direito, tornando-o mais preciso, célere e digitalizado!</p>
<p>Pra fazer tudo isso, estamos buscando um colaborador na área de T.I./Desenvolvimento para nosso time, sendo que essa pessoa irá participar do planejamento, desenvolvimento e implementação de novas funcionalidades em nossa plataforma.</p>
<p></p>
<h6>O que oferecemos?</h6>
<ul>
<li>Ambiente com muito aprendizado, reconhecimento, diversidade e flexibilidade de horários;</li>
<li>Espaço para trabalho remoto em casa;</li>
<li>Chance de crescimento profissional;</li>
<li>Oportunidades para expansão de network;</li>
</ul>

## StartLaw: 
 <p>Auxiliamos a sua startup a promover eficiência e segurança jurídica aos seus negócios digitais e inovadores.</p>

<h4>NOSSO DNA</h4>
<h6>MISSÃO</h6>
<p>Surgimos com o propósito de facilitar o seu departamento jurídico.</p><a href='https://coodesh.com/empresas/startlaw'>Veja mais no site</a>

 ## Habilidades: 
 - CSS 
- HTML 5 
- Javascript 
- React.js 
- Node.js 
- Cloud Functions
## Local: 
 Curitiba 
## Requisitos: 
 - Conhecimento de desenvolvimento Frontend de aplicações; 
- Conhecimento de HTML, CSS e JavaScript; 
- Conhecimentos de Cloud Computing; 
- Conhecimento de banco de dados;

## Como se candidatar:
Candidate-se em: [Front-End Developer Jr na StartLaw](https://coodesh.com/vagas/dev-front-end-jr-201714?origin=github&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção <b>Pedir Feedback</b> entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa <b>Recruiter</b> responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Nível
Júnior
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
