### ISSUE TITLE
[REMOTO] Full Stack Engineer - React / Node.js - Excellent Rates (USD) na Zygmus

### ISSUE THREAD

**Issue by pablonajt** [frontendbr/vagas#4592]
## Nossa empresa

Zygmus.com

## Descrição da vaga

We are looking for a Full Stack Engineer (React / Node.js) with 6+ years of experience to work 100% remotely in English with a client in the US. Excellent rates in USD.

## Local

100% Remoto

## Requisitos

**Obrigatórios:**
- 6+ years of experience with NodeJS and JS
- 4+ years of experience with mongoDB and ReactJS
- Great communication skills
- Strong experience with testing using Jest and Cypress
- Excellent team collaboration skills
- Strong experience with Redux and State management
- Strong experience integrating RestFul APIs
- Strong experience with pub/sub architecture
- Experience working with AWS

**Desejáveis:**
- Experience with Apollo and GraphQL
- Experience with TypeScript

**Diferenciais:**
- Experience working remotely in English

## Contratação

Freelance

## Como se candidatar

Por favor envie um email para talent@zygmus.com com seu CV anexado - enviar no assunto: Vaga FullStack React/Node

#### Alocação
- Remoto

#### Regime
- Freela

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
