### ISSUE TITLE
[Florianópolis/SC] Desenvolvedor Java Full Stack

### ISSUE THREAD

**Issue by Segware** [frontendbr/vagas#46]
## Descrição da vaga

Atividades: atuar no desenvolvimento em Java dos produtos da Segware.

## Local

Rodovia SC 401, 8600
Corporate Park - Bloco 2 - Sala 7
Santo Antônio de Lisboa, Florianópolis - SC

## Benefícios

18 reais por dia trabalhado de VA ou VR (sem desconto em folha) + 50% da mensalidade do plano nacional sem coparticipação da Unimed e Uniodonto + seguro de vida + ginástica laboral 3x/semana + espaço lounge com video game e copa + auxílio educação (50% dos cursos de graduação, pós ou curta duração) + ajuda de custo para cursos de inglês e espanhol realizados instituições específicas + inglês e espanhol in company + estacionamento ou VT + lanche da tarde (sanduiche natural, fruta)

## Requisitos

**Obrigatórios:**
- Conhecimentos em: Java (avançado); Spring / Hibernate; HTML; CSS (Bootstrap); Frameworks javascript (Angular JS e JQuery)
- Experiência necessária com desenvolvimento em Java front e back-end.

**Desejáveis:**
- Conhecimentos em: Flex, utilização de controle de versão e metodologias ágeis.

**Diferenciais:**
- Inglês e/ou espanhol.

## Contratação

CLT

## Nossa empresa

A Segware é uma empresa multinacional responsável pelo desenvolvimento e comercialização do sistema de monitoramento de alarmes e imagens SIGMA, software mais completo da sua categoria, com mais de 70% das contas monitoradas no Brasil.

## Como se candidatar

Por favor envie um email para gestaorh@segware.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor Full Stack

**Comment by willianjusten** [comment]
Opa fala @Segware, creio que pelos requerimentos a vaga seja para um Sênior certo?

**Comment by Segware** [comment]
Isso mesmo, esta vaga é para um nível mais Sênior

**Comment by willianjusten** [comment]
Show, tudo anotado e boa sorte!

**Comment by LFeh** [comment]
@Segware A vaga foi preenchida?

**Comment by Segware** [comment]
Olá @LFeh sim, a vaga já foi preenchida

**Comment by LFeh** [comment]
;)

**Comment by camilatigre** [comment]
@Segware 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
