### ISSUE TITLE
[São Paulo] WebGados - Full Stack Developer (Node.JS)

### ISSUE THREAD

**Issue by workstein** [frontendbr/vagas#460]
## Empresa
WebGados: A primeira e única plataforma online integrada para vender e comprar o melhor em gado de corte e leite, equídeos, ovinos, caprinos, maquinários agrícolas, caminhões, propriedades rurais, produtos e serviços através do seu computador ou smartphone.

Site: https://webgados.com.br

## Descrição da vaga

Desenvolvimento e Manutenção do site/api WebGados

## Local

Escritório em São Paulo - Vila Leopoldina

## Horário

9h as 18hs ou 8h as 17hs

## Requisitos

**Obrigatórios:**
- Nível Pleno
- 2 anos de experiência com Node
- 2 anos de experiência com mongodb e express

**Desejáveis:**
- conhecimentos em vue.js

**Diferenciais:**
- Mentalidade Startup, construir a empresa e crescer junto com a empresa.

## Contratação

PJ (R$ 4.000,00 ~ R$ 6.000,00)

## Como se candidatar

Por favor envie um email para gabriel.stein@webgados.com.br com seu CV anexado - enviar no assunto: Vaga NodeJS

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
