### ISSUE TITLE
[Porto Alegre] Front-End Developer na XPROG

### ISSUE THREAD

**Issue by bombassaro** [frontendbr/vagas#4600]
## Nossa empresa

A XPROG é uma empresa de tecnologia sediada em Porto Alegre que atua no mercado brasileiro desde 2015, atendendo a clientes do varejo e da mídia. Nosso escritório fica no bairro Bom Fim (Porto Alegre/RS) mas a gente trabalha de forma remota. Somos um grupo de 10 pessoas e estamos procurando profissionais para se desenvolverem conosco.

## Descrição da vaga

A oportunidade é para alguém com experiência na tecnologia Javascript e no framework ReactJS. É esperado que o profissional esteja habituado com as cerimônias ágeis e que seja capaz de performar no frontend de forma plena. Nessa posição, a pessoa irá trabalhar diretamente com o líder técnico, com designers e com outros desenvolvedores.

## Local e horário

A preferência é por pessoas de Porto Alegre ou da região, que possam eventualmente irem ao nosso escritório. O horário de trabalho é comercial, flexível através do registro de horas, com remuneração mensal no regime contratação PJ para MEI. O processo seletivo se dá por entrevista com o time e a proposta é para uma experiência de 3 meses de trabalho.

## Requisitos

**Desejáveis:**
- Experiência com Javascript
- Experiência com ReactJS
- Conhecimento em NextJS
- Conhecimento em NodeJS

## Contratação

- PJ a combinar

## Como se candidatar

Por favor envie um email para xproglabs@gmail.com.
Anexar o seu CV e enviar no assunto: Vaga Front-End Developer

#### Alocação
- Remoto

#### Nível
- Pleno

#### Regime
- PJ

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
