### ISSUE TITLE
[Remote] Full-time Salary - UI/UX Designer

### ISSUE THREAD

**Issue by Eaven** [frontendbr/vagas#4602]
## Nossa empresa

[Popstand](https://www.popstand.com) is a 7 year, 35+ team, remote-first company looking to hire talented UI/UX Designer to join our growing team full time. 

Your work will be centered around developing in-house and for-client projects. If you find yourself designing ui's that impress, ux flows that teleport you into another realm, and you want to pave the way to the future with web3 technologies, wanting more and different project exposure than your current company can provide, feeling like your job is going no where and you want to work with a team you can grow into the career you deserve, and you’re proficient with general React stacks, then you’re a perfect fit. 

This is a full-time, competitive salary, full-time ui/ux designer position, for the right candidates. 

We’re interested in applicants that have an entrepreneurial drive, self starters, doesn't mind a tough bug or feature that is a good challenge and excitement around building a future together as a team.

## Descrição da vaga

UI/UX Designer

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 2.5+ years professional experience
- Figma
- Mobile Apps
- Web Apps
- Wireframes
- Full design from concept, wires to design.

**Desejáveis:**
- Brand identity

## Benefícios

- Unlimited PTO
- Paid vacation days
- End of year bonuses
- We assist with buying hardware (Mac / iPhone)

## Como se candidatar

Please send an email to info@popstand.com with subject "Front-end Brasil UX/UI Designer Job Posting" and please include and fill out the following below to be considered:

**Questionnaire:**
Availability (part-time or full-time):
Do you have a Mac:
When can you start:
Overall years of experience designing (start to present day):
Other unlisted experience you want to let us know about:

## Tempo médio de feedbacks

We try to respond to everyone, though sometimes we get busy and may take a bit longer to get back to you.

#### Alocação
- Remoto

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
