### ISSUE TITLE
[Remote] Front-end Developer na Pier

### ISSUE THREAD

**Issue by gabriel-franzoni-pier** [frontendbr/vagas#4603]
## Nossa empresa

Somos uma companhia que, apesar de novos, prezamos muito por quem está conosco e somos transparentes de verdade:

+ Mais de 30% da empresa possui stock options
+ Dados de salários e stocks são 100% visíveis para qualquer um da Pier
+ Agendas são abertas e disponíveis para todos
+ Buscamos sempre profissionais de excelência e temos fundos como Monashees, BTG e Meli que nos apoiam
+ Fomos a primeira seguradora digital do Brasil no modelo sandbox pela SUSEP

## Descrição da vaga

Você é o tipo de pessoa sempre pensa em formas de deixar um código mais elegante e legível?

A pessoa que todo mundo vai atrás quando estão tendo problemas com algoritimos e lógica, e sempre corre atrás de excelência técnica? 

Tem encantamento por produtos que são fáceis de usar e respeitam o usuário? Prazer, somos a Pier :)

## Local

Exemplo: Remoto ou Escritório, SP, São Paulo, Pinheiros

## Requisitos

**Obrigatórios:**

**Desejáveis:**
- Conhecimento de tecnologias de front-end e bibliotecas como React e React Native

**Diferenciais:**

- Conseguir garantir qualidade de código seguindo padrões que garantem agilidade e revisando PRs
- Buscar promover legibilidade escrevendo código de qualidade que será lido por outros desenvolvedores da equipe, assim disseminando conhecimento do framework
- Escrever código para implementar novas soluções para nossos membros e construir uma nova maneira de oferecer seguros no mundo
- Aumentar nossa eficiência e produtividade!
- Tiver **curiosidade e humildade intelectual**, autonomia para tomada de decisão e cooperação
- Tiver **senso de dono(a) de suas entregas**
- Valorizar **aprendizado constante**

## Benefícios

- Plano de saúde e odontológico da SulAmérica
- Gympass
- Benefício flexível de R$ 1300,00 por mês para cultura, mobilidade, refeição, alimentação e saúde
- Infraestrutura de trabalho remoto + R$ 150,00 por mês
- Incentivos à educação
- Possibilidade de se tornar sócio(a)
- Salário a combinar

**Diferenciais:**
- Mais de 30% da empresa possui stock options
- Dados de salários e stocks são 100% visíveis para qualquer um da Pier
- Agendas são abertas e disponíveis para todos
- Buscamos sempre profissionais de excelência e temos fundos como Monashees, BTG e Meli que nos apoiam
- Fomos a primeira seguradora digital do Brasil no modelo sandbox pela SUSEP

## Contratação

CLT

## Como se candidatar

[Link Lever](https://jobs.lever.co/pier/182db30e-c4e9-41e0-a613-fb06cb44cb51)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: juliana.lazzari@pier.digital

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível

- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
