### ISSUE TITLE
[Remote] Facilitação Tech (WebDev - Front-end)

### ISSUE THREAD

**Issue by felipez3r0** [frontendbr/vagas#4604]
## Nossa empresa

SOMOS A RESILIA. E estamos capacitando o Brasil para o século 21.
A Resilia é uma edtech que prepara e emprega jovens para as profissões mais quentes do mercado. Questionamos o status quo e constantemente buscamos formas mais rápidas, acessíveis e eficientes de capacitar as pessoas para as profissões mais demandadas pelas empresas. Somos apaixonados por fazer as pessoas aprenderem e por gerar uma real diferença na vida dos nossos alunos e Resilientes.

## Descrição da vaga
Se você gosta de desenvolver pessoas, facilitar o aprendizado e quer fazer a diferença por meio da educação, essa vaga é para você! Se você sentiu vontade mas nunca facilitou, não se preocupe! Você vai passar pela nossa formação de facilitadores e ainda ter a chance de desenvolver várias habilidades para sua vida e carreira.

Nossas turmas são por módulos e cada módulo tem um foco diferente. Então se você sabe bem de algum dos assuntos abaixo e tem interesse em transformar vidas, vem com a gente!

Tópicos abordados ao longo da jornada de aprendizagem:
. Lógica de Programação
. Linguagens de programação (foco em JavaScript)
. HTML/CSS (Flexbox e Grid Layout).
. React ou VueJS
. Node.Js / Express
. Banco de dados
. Engenharia de Software e Metodologias ágeis

## Local

100% Remoto

## Requisitos

**Obrigatórios:**
- Conhecimento em um ou mais tópicos acima.
- Excelente comunicação (escrita e oral).
- Adorar se relacionar com pessoas.
- Paixão pela educação.
- Empatia.

**Desejáveis:**
- Formação acadêmica: Graduação completa ou em andamento em Engenharia da Computação, Tecnologia da Informação, Ciência da Computação, Análise e Desenvolvimento de Sistemas e áreas relacionadas.

**Diferenciais:**
- Experiência em monitoria, docência de cursos livres, técnico ou superior é um diferencial, mas não determinante.

## Contratação

PJ a combinar

## Como se candidatar

https://www.notion.so/Fa-a-parte-do-time-ab51f6b97cf24c6fb20c9d90033f6dfc?p=5dd87397827843e19810a2336dec1c8c

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

**Comment by raloliver** [comment]
Enviado.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
