### ISSUE TITLE
[Remoto] Front-end Developer na Superare

### ISSUE THREAD

**Issue by lucas-superare** [frontendbr/vagas#4605]
## Nossa empresa

A Superare hoje é o braço de tecnologia do Grupo WE, uma das maiores agências full-service totalmente nacional e, mesmo no período de pandemia, estamos em expansão e precisamos de novos integrantes.

## Descrição da vaga

Você atuará no nosso time de projetos, ligado diretamente a demandas vigentes e novos contratos. Esses projetos vão desde a plataformas de CRM até Chatbots para Whatsapp (somos FB partner) e, em grande maioria, nossa stack gira em React, Node e Mongo.

O Inglês é necessário para essa vaga, já que somos tanto Facebook, quanto Google partner e vez ou outra ficamos em contato com esses caras.

## Local

Próximo a Chácara Sto. Antônio, São Paulo - SP.

## Requisitos

**Obrigatórios:**
- 2 a 3 anos de experiência como desenvolvedor Front-End
- Conhecimento em React.js (Angular e Vue são opcionais)
- Conhecimento prático em HTML, CSS (Preferência SCSS), JavaScript/jQuery e Bootstrap
- Conhecimento em criação de temas com Wordpress
- Conhecimento em Node.js
- Conhecimento básico em Linux

**Desejáveis:**
- PHP, .NET ou outra linguagem back-end (fora node.js)
- Já ter trabalhado utilizando Next.js com foco em performance e SEO
- Conhecimento em bancos de dados não-relacionais e relacionais
- Inglês para conversação

## Benefícios

- VR

## Contratação

PJ a combinar

## Como se candidatar

Favor enviar um email para [lucas@superare.co](mailto:lucas@superare.co) com seu CV anexado - enviar no assunto: Vaga front-end pleno

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
