### ISSUE TITLE
[Remoto] React Developer Sênior na Maitha Tech

### ISSUE THREAD

**Issue by Patricia-MaithaTech** [frontendbr/vagas#4607]
## Nossa empresa

Somos uma empresa digital, com experiência em tecnologia e inspirada pela inovação. Atuamos na aceleração, transformação e ideação de novas soluções e times de alta performance.
Atuamos tanto na construção de times de tecnologia, quanto em frentes de negócio, na co-criação de produtos, levantamento de requisitos, resolução de problemas, entre outros.

## Descrição da vaga

Irá prestar serviço a um cliente que é a maior empresa de Full Service para negócios digitais e atua com o conceito modular, reunindo plataforma, marketing, conteúdo, pagamento, logística e SAC em 3 núcleos centrais de competência: Plataforma Omnichannel, Marketing & Vendas e Operações, irá reestruturar a nova plataforma de e-commerce B2B e B2C, olhar para escala, performance e micro serviços.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- React
- Redux
- HTML
- CSS
- Javascript

**Desejáveis:**
- conhecimentos em micro serviços

## Contratação

PJ a combinar

## Como se candidatar

Contato via Linkedin: https://www.linkedin.com/in/patriciapcarrillo/ ou envie um e-mail para patricia@maitha.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor Front End React

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
