### ISSUE TITLE
[Remoto] Front-end Developer Jr no Grupo GPS

### ISSUE THREAD

**Issue by araujovicthor** [frontendbr/vagas#4609]
[Remoto] Front-end Developer Jr no Grupo GPS

## Descrição da vaga

Exemplo: Implementar, testar e manter interfaces responsivas focadas na interação do usuário assim como buscar e propor novas soluções e também interagir com pessoas envolvidas para a criação do melhor produto/resultado.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- ReactJS
- Javascript ou Typescript (Preferencialmente)
- HTML5, CSS3
- Git
- Preocupação com interfaces e experiência do cliente
- Integração com API's

**Desejáveis:**
- React hooks
- Next.js
- styled-components, SASS ou LESS
- Testes de frontend
- Técnicas de SEO
- PWA
- CI/CD
- Metodologias ágeis

**Ficaríamos impressionados se você soubesse:**
- Micro-frontend
- GraphQL
- Criação de bibliotecas

## Benefícios

- Assistência médica e odontológica
- VR/VA

## Contratação

CLT

## Como se candidatar

Por favor envie um email para michel.macedo@gpssa.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Developer Jr

## Labels
Desenvolvimento de Software, Programação Funcional, Responsividade, Frontend, Interação entre equipes, Métodos ágeis, Testes.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior

![Desenvolvedor Front-End - v2 pptx](https://user-images.githubusercontent.com/33492333/113616388-678d3680-962b-11eb-991c-30ad9a0c096b.png)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
