### ISSUE TITLE
[São Paulo] WebGados - Front-End Developer

### ISSUE THREAD

**Issue by workstein** [frontendbr/vagas#461]
## Empresa
WebGados: A primeira e única plataforma online integrada para vender e comprar o melhor em gado de corte e leite, equídeos, ovinos, caprinos, maquinários agrícolas, caminhões, propriedades rurais, produtos e serviços através do seu computador ou smartphone.

Site: https://webgados.com.br

## Descrição da vaga

Desenvolvimento e Manutenção do site WebGados
Desenvolvimento de Newsletters a partir de layout pronto

## Local

Escritório em São Paulo - Vila Leopoldina

## Horário

9h as 18hs ou 8h as 17hs

## Requisitos

**Obrigatórios:**
- Nível Pleno
- 2 anos de experiência com HTML/CSS
- Implementação de bibliotecas e plugins javascript
- Layout Responsivo
- Portfólio de sites construidos

**Desejáveis:**
- conhecimentos em vue.js
- conhecimentos em node.js e mongo.db

**Diferenciais:**
- Mentalidade Startup, construir a empresa e crescer junto com a empresa.
- Metas semanais... terminou? Vai jogar videogame!! =)

## Contratação

PJ (R$ 2.500,00 ~ R$ 4.000,00)

## Como se candidatar

Por favor envie um email para gabriel.stein@webgados.com.br com seu CV e Portfólio anexados - enviar no assunto: Vaga FrontEnd

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
