### ISSUE TITLE
[Porto Alegre] Front-end Developer - empresa do segmento financeiro (remoto)

### ISSUE THREAD

**Issue by gabrielanatascha** [frontendbr/vagas#4610]
Quer atuar numa empresa do setor financeiro utilizando tecnologias e soluções inovadoras?

Então, confira essa vaga 🤩🤩

Desenvolvedor Frond-End (Trabalho Remoto) - Vaga para PL/SR

Atribuições: Participar do desenvolvimento de uma nova plataforma para instituições de pagamentos, codificar sistemas e aplicações de acordo com os padrões e metodologias estabelecidas e aplicar testes unitários.

Requisitos: Superior completo nas áreas de tecnologia, desenvolvimento front-end utilizando Angular 7, Rest, HTML5, CSS3, Bootstrap, JavaScript e Json.

Se interessou pela vaga?

Envie seu currículo: gabriela@escolhacertarh.com.br

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
