### ISSUE TITLE
[Florianópolis] Front-end Developer na [WK Technology]

### ISSUE THREAD

**Issue by gkologeski** [frontendbr/vagas#4614]
> Vaga Remota durante a pandemia

## Nossa empresa

A WK Technology é uma empresa de alocação de mão-de-obra que entrega aos seus clientes os melhores desenvolvedores para suas demandas

## Requisitos

**Obrigatórios:**
- Conhecimento pleno em Angular 11, com destaque para os recursos
    - Routing;
    - Modules;
    - Components;
    - Observables;
    - Resolvers;
    - Guards.
- Conhecimento pleno em Material Design Components (https://material.io/components)
- Conhecimento avançado em Git;
- Conhecimento avançado CSS (SCSS e TailwindCSS);
- Conhecimento em integração Angular com OAuth2;
- Conhecimento em integração Angular com API REST

**Desejáveis:**
- Angular 2+ 
- Arquitetura de microserviços
- WebFlux
-Template Treo da Pulsetheme https://treo.pulsethemes.com/angular/

## Benefícios

- Remuneração no formato PJ de acordo com o mercado;
- 15 dias de férias remuneradas;
- Possibilidade de fazer Free-Lance como um extra (além do salário);
- Não é um projeto pontual, mas sim, contrato por tempo indefinido;
- Possiblidade de fazer cursos pagos pela WK Technology.

## Contratação

PJ de 4K a 7K

## Como se candidatar

Interessados enviar CV com o título "Front-end Developer Angular" para rh@wkconsultoria.com.br

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@wkconsultoria.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
