### ISSUE TITLE
[Remoto] Fullstack Developer na Mentores Digital

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#4619]
## Descrição da vaga: 
 <p>A Mentores Digital está buscando <strong>Full Stack Developer em nível pleno</strong> para compor seu time!</p>
<p>A Mentores é uma empresa que desenvolve soluções digitais centradas no usuário. A experiência do usuário é a essência do nosso processo, por isso co-criamos soluções através de Design Sprint e Design Thinking, prototipamos e validamos com usuários. Com um time de desenvolvimento integrado, ágil e alinhado com essa forma de pensar e construir, provemos soluções para grandes e médias empresas no Brasil, e algumas startups no Vale do Silício.</p>
<p>Você será responsável por desenvolver aplicações web usando React, Wordpress, Node.js e Docker.</p>

## Mentores Digital: 
 <p>Somos uma agência digital curitibana que atende clientes de diferentes portes em todo Brasil. Na Mentores acreditamos que o design e a tecnologia devem andar juntos e o usuário em primeiro lugar. Acreditamos no diálogo e em nossos profissionais, que são movidos pela inovação.</p>
<p>Faça parte de um time multidisciplinar, criativo e inovador!</p><a href='https://coodesh.com/empresas/mentores-digital'>Veja mais no site</a>

 ## Habilidades: 
 - HTML 5 
- PHP 
- React.js 
- Wordpress 
- Docker 
- CSS 3 
- Node.js
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência em React.js e Node.js 
- Conhecimento em Wordpress e PHP 
- Conhecimento Docker 
- Perfil com iniciativa, comprometimento com metas e prazos 
- Boas noções de metodologias ágeis 
- Habituado com HTML 5 e CSS 3 
- Gostar de trabalhar em equipe

## Benefícios: 
 - Vale Transporte 
- Vale Alimentação. 
- Possibilidade de contratação PJ ou CLT
## Como se candidatar:
Candidate-se em: [Fullstack Developer na Mentores Digital](https://coodesh.com/vagas/fullstack-developer-134710?origin=github&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção <b>Pedir Feedback</b> entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa <b>Recruiter</b> responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Nível
Pleno
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
