### ISSUE TITLE
[Remoto] Fullstack Developer na SolarView

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#4620]
## Descrição da vaga: 
 <p>A SolarView está buscando <strong> Fullstack Developer.</strong></p>
<p>Somos é uma empresa de Tecnologia e Inovação, voltada para o gerenciamento de usinas de energia Fotovoltáica no mercado desde 2013, somos uma empresa consolidada.&nbsp;</p>
<p>Buscamos um profissional que tenha ambição por sempre obter novos conhecimentos e queira atuar neste segmento de mercado.&nbsp;</p>
<p>Trabalhamos com as seguintes tecnologias em nosso contexto: Node.js, React.js, React Native, PHP : CodeIgniter, Laravel e SGBD MYSQL.</p>

## SolarView: 
 <p>SolarView é a solução completa para a gestão de dados e informações relacionadas ao consumo e à produção de energia elétrica a partir de sistemas fotovoltaicos.</p>

<p>A SolarView é uma empresa do Grupo AWC, que desde 2013 dedica-se ao desenvolvimento de tecnologia nacional para mercados inovadores no país, como é o caso do mercado de geração distribuída fotovoltaica.</p><a href='https://coodesh.com/empresas/solarview'>Veja mais no site</a>

 ## Habilidades: 
 - MySQL 
- PHP 
- React.js 
- React Native 
- GIT 
- Node.js
## Local: 
 100% Remoto
## Requisitos: 
 - 1 ou mais anos de experiência em posição similar 
- Sólidos conhecimentos em lógica e programação orientada a objetos 
- Experiência em construir Back-end / Rest API Node.js ou PHP Laravel 
- Domínio em SQL 
- Habituado com scrum 
- Habituado com Git e controle de versão 
- Conhecimentos em React.js

## Benefícios: 
 - Horários Flexíveis 
- 100% Home office
## Como se candidatar:
Candidate-se em: [Fullstack Developer na SolarView](https://coodesh.com/vagas/fullstack-developer-150000?origin=github&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção <b>Pedir Feedback</b> entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa <b>Recruiter</b> responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
