### ISSUE TITLE
[Remoto] Front-end Developer na Pollux Technology [Imediato]

### ISSUE THREAD

**Issue by getinpllx** [frontendbr/vagas#4621]
## Nossa empresa

Somos uma empresa jovem, com pessoas experientes. Profissionais com uma média de 17 anos na indústria de TI e Comunicação.

Formamos uma equipe onde a combinação de nossos talentos resulta em muito mais que aplicativos, jogos, sites, gamification, internet das coisas ou qualquer outra coisa que envolva bits e bytes.

## Local

Remoto

## Requisitos
Experiência com desenvolvimento frontend (HTML/CSS/JS);
Experiência com framework de mercado (React, Angular,Vue);
Experiência com desenvolvimento em ambiente UNIX;;
Conhecimento de componentização e boas práticas de UI e UX;
Conhecimento de Client-Side APIs						  		
Conhecimento de modelos de API REST;
Conhecimento de requests HTTP;
Conhecimento de GIT, fluxos de desenvolvimento em times;
Conhecimento de fluxos de CI e CD;
Boa organização de código e conhecimento de boas práticas;
Conhecimento de ferramentas de teste;

**Desejáveis:**
Conhecimento de utilitários e serviços de cloud (AWS, GCP, Digital Ocean etc);
Conhecimento de containers e conceitos relacionados (Docker, Compose, Kubernetes);
Conhecimento de banco de dados SQL e NoSQL;
Conhecimento de API GraphQL;
Conhecimento de storybook.

## Benefícios

Plano de saúde
•	Plano odontológico
•	Seguro de vida
•	VR/VA com valor mensal
•	Auxílio para aulas de inglês e espanhol
•	Horário Flexivel
•	PLR Anual

## Contratação

PJ ou CLT

## Como se candidatar

Por favor envie um email para getin@pollu-xtechnology.com com seu CV anexado - enviar no assunto: Vaga Frontend
## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível

- Pleno
- Sênior
- Especialista

**Comment by getinpllx** [comment]
@felipefialho obrigada :)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
