### ISSUE TITLE
[São Paulo ou Remoto] Analista de QA @ Port Louis

### ISSUE THREAD

**Issue by gbmatheus** [frontendbr/vagas#4623]
## Nossa empresa
A Port Louis possui soluções de RPA para tarefas de contabilidade e financeiras. O nosso stack é composto por um front de vue, e o back em node + net core, ambos rodando em AWS.
 
## Descrição da vaga
Procuramos um analista de qa júnior para crescer junto com a empresa.
 
O escopo de atuação do profissional inclui: 
* Definição dos testes funcionais
* Desenvolvimento e validação de testes
* Especificação de requisitos e definição de critérios de aceite

## Local
Remoto ou São Paulo - Jardins.

## Requisitos
**Obrigatórios:**

* Conhecimento de Javascript ou C#
* Conhecimento de Selenium ou puppeteer
* Conhecimento de jest

## Benefícios
Salário compatível com a posição
VR

## Contratação
CLT

## Como se candidatar
Por favor envie um email para [eduardo@portlouis.inf.br](mailto:eduardo@portlouis.inf.br) com seu CV anexado - enviar no assunto: Vaga Analista de QA

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 5 dias após o recebimento do currículo

#### Regime
* CLT

#### Nível
* Júnior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
