### ISSUE TITLE
[Campinas-SP, Remoto] Front-end Developer na AB-Inbev / Bees Brasil

### ISSUE THREAD

**Issue by gss-patricia** [frontendbr/vagas#4624]
> Vaga Remota durante a pandemia

## Nossa empresa

We are part of ABInBev’s ecosystem, the biggest brewer in the world, and we work to help our costumer’s life using a range of BEES Applications.
As a tech cell of our organization, we have a simple goal: to grow. Grow as people, as professionals, as a company.
To achieve it, we use the technology creating digital solutions that make our costumers lives simpler, their decisions smarter and their business more profitabl

## Descrição da vaga

What you'll do

- Be part of a cross-functional team, directly contributing to feature development and maintenance of a global product;
- Partner with colleagues to build and maintain tooling for test development, automation, and release processes improvement;
- Advocate for the user experience when communicating with product, design, and tech;
- Follow best development practices to achieve continuous improvement;
- Provide the team with a quality strategy that supports the team's delivery goals;
- Be constantly challenged to create world-class solutions.

## Local

Remoto durante a pandemia e depois parcialmente remoto, [SP], [Campinas].

## Requisitos

**Obrigatórios:**

- 3+ years of relevant professional experience in software development using HTML, CSS and JS;
- Solid fundamentals in object-oriented design, data structures, algorithms and problem solving;
- Experience with front-end with strong skills in JavaScript;
- Advanced knowledge in React JS or React Native frameworks;
- Advanced knowledge in Typescript;
- Experience with GIT version-control system;
- Experience testing with Jest;
- Experience with Agile projects.
- Intermediate English level at least;

**Desejáveis:**

- Experience implementing DevOps tools such as Chef, Ansible, Jenkins, or similar;
- Advanced knowledge of software testing concepts (testability, escape rate, regression, unit, integration, soak, stress, test automation);
- Advanced communication skills in English (written and spoken);
- Micro frontend, and experience w/ event-driven architecture.

**Diferenciais:**

- Experience with distributed systems, CI/CD(Azure DevOps / VSTS) tools, and containerizing applications(Kubernetes), Cloud Hosting (Azure).
- Experience with XP practices such as pair programming and Test-Driven Development.

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ 20/dia
- Auxílio creche
- Bonus;
- 14º Salario;
- Fretado;
- Auxilio Material Escolar;

**Diferenciais:**
- Compra bebidas com descontos;
- frigobar sempre cheio :P;
- sala de jogos;
- Aulas de Inglês in company;

## Contratação

CLT

**More about you**

- You´re passionate about software development and knows how to ensure its quality.
- You´re motivated by building up front-end solution and is aware of its different architectures.
- Experienced working in an environment which uses and stimulates DevOps culture.
- You´re creative when solving problems and is continuously seeking improvements for processes and solutions.
- You can communicate clearly with your team and the company to identify issues and demands.
- You have the autonomy to recognize the current and new priorities, evaluating the impact of their outcomes in the final result.

**Equal Opportunity & Affirmative Action**
Bees is proud to be an Equal Opportunity and Affirmative Action employer. We do not discriminate based upon of race, colour, national origin, gender, gender identity, sexual orientation, protected veteran status, disability, age, or other applicable legally protected characteristics.

## Como se candidatar

Por favor cadastrar aqui: https://boards.greenhouse.io/abinbev/jobs/5157752002 ou https://boards.greenhouse.io/abinbev/jobs/5148607002

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.

## Labels

- Remoto durante pandemia
- Parcialmente remoto
- Remoto
- Pleno
- Sênior
- Especialista
- CLT
#### Alocação
- Alocado
- Remoto
- Remoto durante pandemia
- Parcialmente remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
