### ISSUE TITLE
[Full Remote] Front-end React Developer na iClinic

### ISSUE THREAD

**Issue by franfrw** [frontendbr/vagas#4625]
## Nossa empresa

A iClinic é uma das startups de tecnologia em saúde que mais cresce no Brasil.

Nossa missão é Descomplicar a saúde no Brasil.

_E como fazemos isso hoje?_ 
Oferecendo o melhor software de gestão para clínicas e consultórios médicos.

_E como atingir este objetivo?_
Montando um time de pessoas incríveis, capazes de colocar os nossos clientes no centro do processo de criação e desenvolvimento do nosso sistema. Aqui são os clientes quem mandam e você será uma das vozes deles dentro da empresa e do time de Pesquisa e Desenvolvimento.

## Descrição da vaga

A iClinic está à procura por Front-end React Developer (100% remoto) para fortalecer e expandir nossas capacidades técnicas. Buscamos uma pessoa responsável para o cultivo de uma cultura técnica de excelência: obcecado por qualidade e desenvolvimento ágil. Procuramos alguém para refletir, validar ideias e ajudar-nos a encantar nossos clientes.

Você vai trabalhar com times multidisciplinares, com pessoas incríveis, capazes de realizar trabalhos incríveis e produzir resultados incríveis para os nossos usuários. Será responsável por desenvolvimento contínuo diariamente e irá garantir a qualidade que almejamos.

Tecnologia é o nosso core, então terá autonomia para arquitetar ou sugerir algo novo, deve ter uma mentalidade analítica, aptidão para solução de problemas e preocupação com a qualidade do código e boas práticas.

Temos serviços em Python/Django, Node, sistemas na AWS com e sem Kubernetes. Nossa aplicação front-end é desenvolvida em React + Redux.

## Local

Full Remote

## Requisitos

Experiência comprovada em React + Redux como front-end;
Alta capacidade de auxiliar os outros membros do time a se desenvolverem, sendo capaz de comunicar ideias de forma clara;
Visão ampla sobre processos de desenvolvimento e fluxo de trabalho em metodologias ágeis;
Conhecimentos abrangentes em todas as partes do software, podendo conversar com diversas frentes do produto, pesquisa, dev-ops, back-end, QA tester;
Conhecimentos em arquitetura de projetos, design patterns e boas práticas de desenvolvimento;
Conhecimentos em paradigmas funcionais e suas práticas;
Conhecimentos em metodologias de testes unitários, integração e E2E.

## Benefícios

Vale refeição;
Vale alimentação;
Convênio médico nacional;
Convênio odontológico;
Convênio Farmácia;
Seguro de vida;
Convênio SESC;
Auxílio-Creche;
Licença maternidade/paternidade estendida; 
Plano de participação nos resultados (PPR);
Acesso a cursos gratuitos através da plataforma da UCA - Universidade Corporativa Afya;
Incentivo em certificações AWS;
Fornecemos notebook como equipamento para trabalho;
Ajuda de custo para trabalho remoto;
Bônus por indicação de outros profissionais para trabalhar na iClinic;
Relacionamento próximo aos fundadores e diretores da empresa;
Incentivo financeiro para desenvolvimento técnico;

_Quando fizer uma visita em nosso escritório - pós pandemia :) - você encontrará:_

Ambiente jovem, descontraído, escritório confortável, videogame, puffs para descanso;
Sem dress code. Trabalhe do jeito que achar confortável;
Café da manhã, frutas e o sagrado cafezinho ao longo do dia.

## Contratação

CLT Full

## Como se candidatar

Por favor envie um email para francisco.freitas@iClinic.com.br com seu CV anexado ou cadastre-se na [Gupy](https://iclinic.gupy.io/jobs/628347?jobBoardSource=gupy_public_page)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: francisco.freitas@iclinic.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
