### ISSUE TITLE
[Remoto] Front-end Developer na Comadre

### ISSUE THREAD

**Issue by MarceloPrado** [frontendbr/vagas#4626]
## Um pouco sobre a Comadre :)
🙋🏾‍♀️ A Comadre é a porta de entrada para digitalização da vida financeira das diaristas do Brasil. Nossa missão é educar e organizar o dinheiro das mulheres mais fortes do país!
:moneybag:  Nós somos experts em tecnologia e produto, e nossa missão é mudar o Brasil, começando com as 7 milhões de diaristas que existem pelo território nacional.
:purple_heart:  Somos apaixonados por pessoas e cultura. Gostamos mesmo é de cuidar uns dos outros e garantir que todos estamos trabalhando felizes e com o mesmo propósito!
## Descrição da vaga
👩🏽‍💻 Procuramos alguém com pelo menos 2 anos de experiência em desenvolvimento e mais de 6 meses de experiência com React ou React Native
:joystick: Gostaríamos de uma pessoa com experiência com TypeScript e testes automatizados
:iphone: É um difererencial se você tiver familiaridade com React Native ou experiência com Redux ou outra lib de gerenciamento de estado
## Local
Remoto, presencial ou um mix dos dois. Cada time decide seu modelo de trabalho 🤩
Nosso escritório fica em São Paulo - SP, no bairro da Vila Olímpia.

## Requisitos
**Obrigatórios:**
- 2 anos de experiência em desenvolvimento
- +6 meses de experiência com React ou React Native

**Desejáveis:**
- Experiência com TypeScript
- Experiência com testes automatizados (unitários, integração e e2e)

**Diferenciais:**
- Familiaridade com React Native
- Experiência com Redux ou outra lib de gerenciamento de estado

## Benefícios
- Acesso aos melhores mentores do mercado, em todas as áreas :star:️
- Auxílio em cursos e certificações :school:
- Possibilidade de stock options :moneybag:
- Férias remuneradas

**Diferenciais:**
- Desafios para crescer. Você vai mudar a vida de muitas mulheres, criando um ecossistema de diaristas com incríveis histórias para contar. Assim, vamos mudar o Brasil, todo mundo junto.
- Equipe horizontal e transparente, que valoriza seu conhecimento em sua área, e também quer te ver fazendo parte de discussões em nível estratégico.
- Ambiente descontraído, tranquilo e catalisador de criatividade e inovação.

## Contratação
PJ a combinar
## Como se candidatar
Por favor, se inscreva na nossa vaga [no Linkedin](https://www.linkedin.com/jobs/view/2469426378/?recommendedFlavor=IN_NETWORK) 
## Tempo médio de feedbacks
Costumamos enviar feedbacks em até uma semana após cada processo.
E-mail para contato em caso de não haver resposta: fernanda.bernardo@comadre.com.br
#### Alocação
- Alocado
- Remoto
#### Regime
- PJ
#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
