### ISSUE TITLE
[Remoto] Front-end Developer Sênior na Remote.com

### ISSUE THREAD

**Issue by lucasmazza** [frontendbr/vagas#4627]
## Nossa empresa

A Remote é uma plataforma global para empresas que querem contratar pessoas em qualquer lugar do mundo, cuidando da gestão de pagamentos, benefícios, impostos e questões legais na contratação de funcionários e contractors para empresas de todos os tipos e tamanhos.

Nós encorajamos pessoas de todos os grupos étnicos, gêneros, sexualidade, idade e habilidades a se candidatar. Valorizamos gentileza, responsabilidade e colaboração, e você pode saber mais sobre como trabalhamos no nosso [Handbook](https://www.notion.so/Handbook-a3439c6ccaac4d5f8c7515c357345c11) público. Se essa posição lhe interessou, queremos conversar com você!

A Remote é totalmente distribuída e trabalhamos de [forma assíncrona](https://www.notion.so/Working-Async-80c01cd443ad4c77a8ceaef7c5fba5d0). Isso significa que cada pessoa faz a sua rotina de trabalho, independente de fuso horário e localização.

## Descrição da vaga

A vaga é para o nosso time de engenharia que conta com +- 30 pessoas entre Back end, Front end, SRE e QA. Estamos organizados em diversos times de produto junto de designers, product managers e pessoas dos times de operações e financeiro dedicados em domínios diferentes do nosso produto. 

Nosso time usa uma abordagem simples de produtividade e processo que você pode ler mais a respeito no [The Remote Flow](https://www.notion.so/remotecom/The-Remote-Flow-d90982e77a144f4f990c135f115f41c6).

## Local

Remoto

## Requisitos

**Obrigatórios:**

- Bom inglês, verbal e escrito
- Pelo menos 4 anos de experiência com Front end, com proficiência em **React** e **Jest**
- Interesse nos tópicos de performance e acessibilidade de interfaces web

**Desejáveis:**

- Experiência prévia com trabalho remoto
- Experiência com **Next.JS**

## Benefícios

- Plano de saúde
- Seguro de vida
- Vale Refeição

**Diferenciais:**

- Cultura de trabalho remota e assíncrona
- Você e sua família vem primeiro! [Férias e folgas ilimitadas](https://www.notion.so/Personal-time-off-e2e71e5dcdef43ff82515d7c711ed4af)
- Equipamento (computador e periféricos) entregues pela empresa
- Salário de mercado global e pacote de opções

## Contratação

CLT

## Como se candidatar

Aplicar através do [https://grnh.se/33cac5d83us](https://grnh.se/33cac5d83us), incluindo CV e Cover Letter **em inglês**

## Como é o processo

- Entrevista de 30 minutos com Recruiter
- Entrevista de 30 minutos com o CTO
- Teste técnico
- Entrevista com pessoas do time de engenharia

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: [lucas@remote.com](mailto:lucas@remote.com) ou via [https://t.me/lucasmazza](https://t.me/lucasmazza)

### Alocação

- Remoto

### Regime

- CLT

### Nível

- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
