### ISSUE TITLE
[São Paulo Remoto] Front-end Developer na 99jobs

### ISSUE THREAD

**Issue by tecnologia99jobs** [frontendbr/vagas#4628]
> Vaga Remota durante a pandemia

## Nossa empresa

Sobre a 99jobs.com 

A 99jobs é uma das HR Techs que mais cresce na América Latina!
São 6 anos de criação, operação e expansão em um ambiente super legal.  
A verdade é que a gente tem uma missão que impacta positivamente muita gente: ajudar pessoas a encontrarem trabalhos onde elas realmente se sintam felizes, possam ser elas mesmas e explorem ao máximo seu potencial.

## Descrição da vaga

Nosso principal produto, que é o ATS (um sistema de gestão de recrutamento e seleção), não para de crescer. 

Já temos 7M de usuários (sendo que todos os meses entram mais +200k) e nós temos mais de 100 grandes marcas no portfólio, como Magazine Luiza, Itaú, Coca-Cola e Heineken.

Nosso convite é para você participar do novo desenho da arquitetura de front-end da nossa plataforma de gestão de recrutamento e seleção, propondo e implantando novas soluções em usabilidade, design, experiência do usuário, performance e escalabilidade.

## Atividades

- Aplicar no sistema as novas soluções de produto desenhada pela visual designer e UX.
- Melhorar performance e escalabilidade, criar uma experiência incrível para o usuário.
- Utilizar seu conhecimento para pensar na arquitetura de front, com novos padrões e soluções.

## Local

Remoto / Escritório, [São Paulo], [São Paulo], [Bela Vista]

## Requisitos

**Obrigatórios:**
- Testes automatizados (mochajs, jasmine, jest)
- Experiência com (HTML, Javascript, CSS, SASS, ES6, ES7);
- Experiência com desenvolvimento de sites responsivos
- Git
- React
- Webpack
- Redux
- Babel

**Desejáveis:**
- Continuous Integration
- Node.js
- Lerna

## Benefícios

Plano de saúde
- Cartão de Benefícios Caju: R$ 28/dia útil
- Auxílio home office
- Horário Flexível
- Férias Remuneradas
- Equipamentos da empresa

## Contratação

PJ - Salário 10K

## Como se candidatar

https://www.99jobs.com/99jobs/jobs/131780-senior-front-end-developer?source=frontendbr

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: people@99jobs.com

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
