### ISSUE TITLE
[Curitiba][Remoto] Front-end Developer | Squad Aquisição na Contabilizei

### ISSUE THREAD

**Issue by ContabilizeiVagas** [frontendbr/vagas#4632]
## Nossa empresa

Com mais de 30 mil clientes, atuando em mais de 50 cidades do Brasil, a Contabilizei está mudando a maneira como o micro e pequeno empreendedor gerencia o seu negócio em nosso país por meio da tecnologia. Continuamos a crescer rapidamente, criando novos produtos e proporcionando que o empreendedor seja o contador de sua própria história.

Aqui na Contabilizei, as oportunidades são para todos! Queremos que você seja a melhor versão de si e se sinta bem onde estiver. Valorizamos as diferenças e temos um ambiente onde todos são mais que bem-vindos, independente de deficiência, gênero, etnia, orientação sexual, origem, entre outras diversidades, pois entendemos que JUNTOS construímos a Contabilizei do nosso jeito.

Essa oportunidade permite trabalho remoto e você poderá trabalhar de onde quiser, ou se preferir, poderá trabalhar presencial/híbrido em nosso escritório em Curitiba após a pandemia, além disso, todas as nossas vagas são regime CLT.  

## Descrição da vaga

O **Squad Aquisição** tem como missão, apoiar a área de Growth por meio da tecnologia em nosso site, blogs, landing pages de campanhas, construindo novos canais de aquisição e identificando oportunidades que direcionam as decisões do dia a dia, garantindo principalmente que os clientes tenham uma experiência encantadora com a Contabilizei desde a primeira interação.  

**Um dia típico em nosso foguete inclui:**

- Analisar as exigências e especificações, contribuindo com o desenho da solução (arquitetura, modelagem, design de código), atuando no desenvolvimento de sistemas que entreguem valor;
- Entregar com autonomia código testável com qualidade, estimando o esforço e o custo necessário para cumprir expectativas acordadas e comunicando necessidade de novos prazos;
- Desenvolver e propor melhorias em sistemas e funcionalidades do lado do cliente (front-end) para fornecer aos usuários finais acesso às funções do sistema;
- Construir componentes de aplicativos front-end para incluir scripts a serem executados em navegadores web de diversos dispositivos do lado do cliente, considerando conceitos da experiência do usuário;
- Identificar problemas na base de código existente e aplicar melhorias;
- Pode apoiar no desenvolvimento técnico de profissionais com menos experiência, ajudando a desenvolver um time com nível adequado de qualificação.

## Local

Full Time Remoto ou Presencial/Híbrido em Curitiba (após a pandemia).

## Requisitos

**Você precisa de:**

- Graduação concluída ou cursando em Análise de Sistemas, Engenharia da Computação ou áreas afins;
- Experiência com desenvolvimento de aplicação SPA;
- Experiência com Javascript e framework Vue.js;
- Experiência com WordPress;
- Experiência com PHP.

**Pontos a mais se você possui:**

- Desejável experiência com Nuxt.js;
- Desejável experiência com SEO;
- Desejável experiência com Web Analytics.

## Benefícios

**Nossos benefícios:**
Vale Refeição e/ou Alimentação;
Plano de Saúde;
Plano Odontológico;
GymPass;
Convênio Farmácia;
Seguro de vida;
Psicoterapia Online;
Infraestrutura tecnológica de trabalho.

﻿**O que esperar da Contabilizei**
Nossas Guardiãs e Guardiões acreditam e perseguem nosso propósito: Entendem que o sucesso do empresário é o nosso sucesso. Oferecemos um ambiente descontraído, completamente colaborativo, com ritmo acelerado e desafiador, a fim de atingir resultados e promover a melhor experiência aos nossos clientes, construindo uma jornada de sucesso. Acreditamos no protagonismo, aqui você constrói sua carreira da sua forma e cresce junto com a Contabilizei. 

Aqui, você terá a oportunidade de gerar um grande impacto positivo, construindo o futuro de como os empresários brasileiros gerenciam seus negócios com sucesso.

## Contratação

CLT

## Como se candidatar

Há duas maneiras de realizar sua inscrição:

- Candidatura via Gupy: https://contabilizei.gupy.io/jobs/796557

- Candidatura simplificada via Linkedin: https://www.linkedin.com/jobs/view/2467666451

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após a triagem dos perfis, seja pelo Linkedin ou e-mail de cadastro.

#### Nível
Pleno

**Comment by jessicaalorena** [comment]
Em aberto

**Comment by jessicaalorena** [comment]
Atualizado.

**Comment by jessicaalorena** [comment]
up

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
