### ISSUE TITLE
[Remoto] Frontend  na GFT

### ISSUE THREAD

**Issue by NerdProgramador-com-br** [frontendbr/vagas#4633]
## Descrição da vaga 
✅Angular 6+
✅Javascript/Typescript
✅Testes unitários (Jasmine ou Jest)
✅Construção e estrutura de stylesheet utilizando SASS
✅Versionamento em GIT (respeitando flows com pull requests e code reviews)
✅Experiência com Desenvolvimento de sites/páginas com Design Responsivo
✅Conhecimento em bundlers/builders como Webpack e Gulp. (Webpack é mandatório)
✅NPM
✅Atuação em projetos de stack JAVA
✅Profissional deve estar aberto a trabalhar com Wordpress
## Local 
REMOTO 
## Como se candidatar 
Accesse a [Vaga de Frontend ](https://nerdprogramador.com.br/gft-frontend-/eeb758f5-a666-4f13-ac2c-602966027b67?utm_source=github) para mais informações. 
## Labels 
* Remoto

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
