### ISSUE TITLE
[Remoto] FullStack Developer @ Cout

### ISSUE THREAD

**Issue by FigueiraIure** [frontendbr/vagas#4636]
## A Cout

Somos uma plataforma focada em Gestão de Processos Empresariais e nosso primeiro produto é uma ferramenta de gerenciamento de Escalas e Jornadas de trabalho. Nossa startup está em fase inicial mas conta com um primeiro investidor.

## Descrição da vaga

Desenvolvedor Full Stack Sênior em PHP (Laravel) e JavaScript (Vue/Nuxt)

## Local

Remoto

## Requisitos

*Obrigatórios:*
- Experiência mínima de 4 anos em PHP (Laravel) e JavaScript (Vue/Nuxt)

*Desejáveis:*
- Experiência em projetos remotos e colaborativos, utilizando o GitLab
- Conhecimento em Design Pattern

**Diferenciais:**
- Projetos opensource no github
- Felixibilidade de Horários

## Contratação

 PJ > R$ 6000 — R$ 12000  para 40h/semanais com possibilidade de Stock Option e/ou variáveis por resultado;

## Como se candidatar

Enviar um email para danielcouto@cout.app com o assunto "Vaga [FullStack]" contando um pouco de suas habilidades, sua experiência e como pode somar com nosso time.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dia após cada processo.
Contato em caso de não haver resposta: +55 (62) 991725365 (Daniel)

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
