### ISSUE TITLE
[Home Office ] Desenvolvedor FullStack SR (Foco Java) na Meta

### ISSUE THREAD

**Issue by NerdProgramador-com-br** [frontendbr/vagas#4637]
## Descrição da vaga 
Nível Pleno em linguagem de programação Java; • Nível Pleno em frameworks Javascript como React, Angular e/ou Vue.js; • Experiência em desenvolvimento de software Web, incluindo conceitos de layout, compatibilidade entre browsers e acessibilidade; • Conhecimento em GIT; • Conhecimento em apis REST; • Experiência em Banco de dados Oracle e/ou SQLServer; • Conhecimento em Docker e Integração contínua; • Conhecimentos em testes automatizados; • Conhecimento de técnicas e práticas de Clean Code; • Experiência em equipes dinâmicas e metodologias de desenvolvimento ágeis; • Procuramos um perfil participativo que não somente execute, mas também proponha soluções; e • Perfil proativo, boa comunicação, saber trabalhar em equipe, raciocínio lógico, responsabilidade e comprometimento são imprescindíveis para essa oportunidade. Você irá se destacar se tiver: • Ser orientado a resolver o problema do cliente com noções de boas práticas de UX para impactar positivamente pessoas e organizações; • Experiência em projetos para o setor público para provocar pequenas revoluções; • Conhecimento em Banco de dados NoSQL; • Conhecimento na linguagem GO; • Conhecimento em Rancher e Gitlab; • Desenvolvimento Mobile; • Experiência com Flutter; • Experiência em banco de dados Postgresql; e • Conhecimentos em cloud computing (Azure, AWS ou Oracle Cloud). Um dos nossos pilares é a valorização das pessoas e temos orgulho de dizer que somos uma empresa que apoia a diversidade e inclusão. Sendo assim, consideramos todos os candidatos para as nossas vagas, sem distinção de raça, cor, religião, gênero e identidade de gênero, nacionalidade, deficiência, orientação sexual, ascendência, idade e etc.
## Local 
Home Office /Home Office  
## Como se candidatar 
Accesse a [Vaga de Desenvolvedor FullStack SR (Foco Java)](https://nerdprogramador.com.br/meta-desenvolvedor-fullstack-sr-foco-java/104a7660-cc3d-409b-9b0e-073833a066ab?utm_source=github) para mais informações. 
## Labels 
* Alocado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
