### ISSUE TITLE
[Remoto] Designer UX/UI na Tratorweb. 

### ISSUE THREAD

**Issue by tugzera** [frontendbr/vagas#4640]
## Local

Remoto

## Requisitos
Boas práticas de UX/UI.
Modelagem e prototipação com Figma e AdobeXD.

## Diferenciais
Se desenvolvedor front-end e ter experiência com React/React-Native.

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para damascenobdm@gmail.com com seu CV anexado - enviar no assunto: Vaga UX/UI
OBS: se tiver um link com o portifólio de projetos que já realizou seria de grande ajuda

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 01 dias após cada processo.
E-mail para contato em caso de não haver resposta: damascenobdm@gmail.com

## Labels

- Freela
- PJ
- Júnior
- Pleno
- Remoto

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
