### ISSUE TITLE
[Remoto ou São José/SC] Front-end Developer na Nexti

### ISSUE THREAD

**Issue by marinasgriza** [frontendbr/vagas#4641]
Empresa de sistema inovador em ponto eletrônico contrata **Desenvolvedor Front-end Pleno ou Júnior!** 

Buscamos profissional com experiência em Angular! 
(1 a 2 anos de experiência)

Local: São José, Santa Catarina, Centro

**Requisitos** 

**Obrigatórios:**
- Ensino Superior completo ou cursando em Engenharia da Computação, Sistemas de informação ou afins;
- Desenvolvimento Front-end utilizando Framework AngularJS ou Angular 2+;
- Conhecimento em Javascript, HTML5 e CSS.

Desejáveis:
- Conhecimento em metodologias ágeis (Scrum, Kanban);
- Experiência em desenvolvimento Back-end em Java utilizando Spring Framework;
- Conhecimentos no uso de APls em REST e conhecimento em SQL.

**Benefícios**

- Vale transporte
- Vale refeição
- Plano de saúde
- Assistência odontológica

Contratação: CLT

Por favor envie um email para **recrutamento_selecao@visionnaire.com.br** com seu CV anexado - **enviar no assunto: Vaga Front-end Angular**

E-mail para contato em caso de não haver resposta: marina@visionnaire.com.br
**Link para candidatura:** https://visionnaire.abler.com.br/vagas/desenvolvedor-front-end-angular-junior-ou-pleno-659383

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by marinasgriza** [comment]
#frontend #angular #javascript #html5 #css

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
