### ISSUE TITLE
[Remote] Front-end Developer at TrueLogic Software

### ISSUE THREAD

**Issue by didierpachas** [frontendbr/vagas#4642]
**Essentials**

- 5 years working on software development professionally.
- The ability to create well responsive, accessible, and performant web interfaces managed by clean UI code using a modern framework (Vue, Angular)
- Solid experience with the standard tech stack for your technology of choice (like Redux, MobX, etc)
- Deep understanding of all web-related technologies and protocols (like HTTP/S, TLS, Sockets, REST, etc)
- Experience working with mobile-first applications
- Knowledge about how to work with containerized application development (Docker).
- Strong computer science foundation.

**It will be nice if you also know**

- Accessibility rules and standards and how to apply them to a web application.
- How to create mobile native applications using javascript based frameworks like React Native.Experience with Server Side Rendering (like Nextjs or vue-server-render)
- How to create a Progressive Web App
- How to set up and maintain a CI environment to enable continuous delivery
- How to work with applications and services on the public cloud, AWS, GCP, or Azure

**What's in for you:**

- 100% remote work
- Payment in USD
- Free credentials for e-learning platforms.
- Remote workshops & activities.

**Contratação**
PJ

**Nossa empresa**
TrueLogic: https://www.truelogicsoftware.com/company

**Como se candidatar**

- Apply here: https://boards.greenhouse.io/truelogic/jobs/5153562002
- Find other roles here: https://boards.greenhouse.io/truelogic
- Get in touch with me: https://www.linkedin.com/in/didierpachas/

## Labels
🏢 Remoto
👴 Sênior
⚖️ PJ
💰 15k+

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
