### ISSUE TITLE
[Remoto - Brasil] Senior Front-end Developer na Engineering Brasil

### ISSUE THREAD

**Issue by MajuMoreira** [frontendbr/vagas#4643]
## Descrição da vaga

A Engineering Brasil, multinacional italiana com foco em transformação digital está criando um departamento de Produtos e buscando profissionais para compor esse time!

A proposta é para atuar como Dev. Front-End Sr no desenvolvimento e decisões de arquitetura da nossa oferta PaaS, contribuindo nos desafios de interface do produto em conjunto com os times de UI/UX.

Stacks principais: JavaScript, React Native, React, Vue.js e Angular

## Local

100% remoto - Brasil Inteiro

## Benefícios

- Contratação CLT ou PJ
- Se CLT, os benefícios incluem seguro de vida + pacote de benefícios flexível com VA, VR, Plano de Saúde e muito mais.
- Auxílio a educação contínua, como plataforma interna de treinamento, acesso a plataformas de aprendizado de língua estrageira, e apoio a certificações e cursos.

### Diferenciais

- Empresa realmente focada em desenvolvimento profissional, que realiza avaliações de performance e construção de planos de desenvolvimento semestrais
- Ambiente de trabalho descontraído e colaborativo
- Trabalhar com tecnologias modernas

## Requisitos

**Obrigatórios:**

- Tenha experiência no desenvolvimento front-end utilizando React Native, React, Vue.js e Angular;
- Tenha conhecimento avançado em typescript, javascript, jquery, bootstrap, css e html;
- Conheça metodologias ágeis;
- Ame os desafios complexos.

**Desejáveis:**

- Conhecimento de APIs Rest;
- Conhecimento de Git;
- Portfólio/Repositório com soluções em novos frameworks que você tenha criado.( React, Vue.js, Angular);
- Conhecimento de Testes (unit/e2e).

## Como se candidatar

Por favor se aplique através de nossa página de carreira e entraremos em contato rápidamente com feedback:
[https://jobs.kenoby.com/engineering/job/analista-desenvolvedor-front-end-senior-remoto/604242dfb1ca0e41a44a5189?utm_source=website](https://jobs.kenoby.com/engineering/job/analista-desenvolvedor-front-end-senior-remoto/604242dfb1ca0e41a44a5189?utm_source=website)

## Labels

- CLT
- PJ
- Remoto

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
