### ISSUE TITLE
[Remoto] Front-end Developer (React) na DClick

### ISSUE THREAD

**Issue by JonatasRicardo** [frontendbr/vagas#4644]
## Nossa empresa

A DClick nasceu em 2005 com o objetivo de desenvolver as melhores Rich Internet Applications do mercado, ou seja, aplicativos com o melhor da Internet: alcance, disponibilidade, performance e Interface de usuário agradável e intuitiva.

Ao longo destes anos atendemos a grandes clientes no Brasil e exterior e aprimoramos nosso conhecimento em Engenharia de Software, Interfaces de Usuário e Design de Interfaces e Desenvolvimento de Produtos. Hoje utilizamos a nossa expertise através das mais variadas tecnologias.

Nosso quadro de profissionais trabalham juntos em busca do equilíbrio adequado entre a forma e a função, o que leva a resultados de excelente qualidade técnica e estética.

Hoje nosso principal objetivo é desenvolver projetos que as pessoas usam porque gostam, não porque são obrigadas, seja no Desktop, tablets ou telefones celulares.

## Descrição da vaga

Estamos com vagas abertas para  Front-end Developer React ( Pleno e Sênior)

## Local

100% Remoto.

## Requisitos

**Obrigatórios:**
- Javascript, React, HTML e CSS

**Desejáveis:**
- Hooks
- arquitetura flux (como redux, mobx, recoil, etc)

**Diferenciais:**
- Experiência com Typescript
- Pré-processadores CSS (sass, less, stylus, etc)
- Desenvolvimento Mobile com React Native
- Testes

## Benefícios

- Plano de saúde
- VR

## Como se candidatar

Por favor envie um email para andreza.pereira@dclick.com.br com seu CV anexado - enviar no assunto: Vaga React

#### Alocação
- Remoto

#### Regime
- PJ/Cooperativa

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
