### ISSUE TITLE
[Remoto] Desenvolvedor(a) React Native na Empresa 

### ISSUE THREAD

**Issue by NerdProgramador-com-br** [frontendbr/vagas#4646]
## Descrição da vaga 
Desenvolvedor(a) React Native (PJ) 100% Remoto Experiência de no mínimo 3-6 anos em React Native. Perfil Front end. Salario: 5 a 10k (depende do nível do profissional Jr, Pleno ou Sr) Benefícios: R$1.340,00 de Cartão de Benefícios Flexível email: debora.macedo@revelotalent.com.br
## Local 
REMOTO 
## Como se candidatar 
Accesse a [Vaga de Desenvolvedor(a) React Native](https://nerdprogramador.com.br/empresa-desenvolvedora-react-native/6454015c-f4a4-4f1b-a2db-da641364a2b9?utm_source=github) para mais informações. 
## Labels 
* Remoto

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
