### ISSUE TITLE
 [São Paulo] Front-End Developer na Polishop

### ISSUE THREAD

**Issue by gdomiciano** [frontendbr/vagas#465]
## Descrição da vaga

Estamos procurando um profissional front-end nível pleno apaixonado por desenvolver interfaces limpas e intuitivas. Que saiba manter seu código limpo e organizado. Que tenha atenção aos detalhes e goste (muito!) do que faz.

O profissional atuará no desenvolvimento de novas interfaces digitais para os produtos da empresa - com grande foco em mobile - além da manutenção das já existentes.

## Local

Horário comercial - Santo Amaro - Zona Sul de SP.

## Benefícios

- Plano de saúde e odontológico
- Seguro de vida
- Restaurante no Local
- Auxílio creche

## Requisitos

**Obrigatórios:**
- Conhecimento avançado em HTML5 e CSS3;
- Conhecimento intermediário em Javascript puro (existe vida além do jQuery ;D);
- Conhecimento em Sass;
- Comprometimento e facilidade para trabalhar em equipe;
- Domínio no desenvolvimento de projetos responsivos e adaptativos;
- Saiba utilizar ferramentas de controle de versão (Git).

**Desejáveis:**
- Conhecimento em Vue.js e AngularJS;
- Consumo de APIs RESTful e atividades assíncronas (promises, callbacks, async/await);
- Prática com Gulp e NPM (ou Yarn);
- Noções de UX.
- Conhecimento em gitflow.

**Diferenciais:**
- Noções/conhecimento de fluxo de CI/CD

## Contratação

CLT Full

## Nossa empresa

A POLISHOP é a maior empresa verdadeiramente multicanal do mundo. Desde o seu nascimento em 1999, a POLISHOP se empenha em oferecer soluções e produtos inovadores e de qualidade, além de um completo leque de possibilidades de interação. Através de uma grande rede de canais de comunicação, distribuição e vendas, POLISHOP consegue alcançar hoje mais de 180 milhões de brasileiros.

**NOSSA MISSÃO**

Oferecer sempre a melhor experiência para o cliente, onde ele estiver, através de soluções inovadoras e de qualidade.

**NOSSA VISÃO**

Ser uma empresa verdadeiramente multicanal, e oferecer sempre produtos e serviços inovadores

**NOSSOS VALORES**

- Inovação e Criatividade
- Qualidade
- Empreendedorismo
- Gente
- Dinamismo
- Relacionamentos

## Como se candidatar

Por favor envie um email para johnny.santana@polishop.com.br com seu CV anexado - enviar no assunto: Currículo Front-End

**Comment by gdomiciano** [comment]
Labels: Alocado, CLT, Pleno

**Comment by gdomiciano** [comment]
Vaga continua aberta...

**Comment by gdomiciano** [comment]
vaga continua aberta...

**Comment by brunoramalho** [comment]
Pode participar do processo seletivo remotamente?


At.

Bruno Ramalho
FrontEnd and PHP Developer

​​

2017-09-10 20:58 GMT-03:00 Geisy Domiciano <notifications@github.com>:

**Comment by gdomiciano** [comment]
Pode sim @brunoramalho  :)

**Comment by gdomiciano** [comment]
Vaga Preenchida, 

Agradeço a todos os que enviaram seus CVs, o RH deverá entrar em contato com aqueles que participaram do processo para feedback.
