### ISSUE TITLE
[São Paulo-SP] Front-end Developer Mobile no Santander Tecnologia

### ISSUE THREAD

**Issue by vagastech** [frontendbr/vagas#4650]
We## Nossa empresa

Somos, antes de mais nada, uma empresa de tecnologia. No Geração Digital, nosso hub de tecnologia, as equipes contam com a estrutura ideal para permitir um trabalho ágil, eficiente e inovador em um ambiente aberto e flexível. Junte-se a nós e trabalhe com profissionais referência no mercado.

## Descrição da vaga

Projeto Mobile.

## Local

Presencial , [São Paulo], [Sp], [Interlagos]

## Requisitos

**Obrigatórios:**
-Experiencia com desenvolvimento mobile para as plataformas Android e IOS.

 *IOS: conhecimentos em SWIFT, design patterns e integrações REST MVVM e MVVM-C
Distribuição na Apple Store
 
*Android: Proficiência em desenvolvimento para plataformas móveis. 
Experiência em desenvolvimento Kotlin e Android Studio
Integracoes API REST
Distribuição na Play Store

Interlagos – Zona Sul/SP

## Benefícios

- Modelo: CLT 

Benefícios: 
-Vale Alimentação, 
-Vale refeição
-Vale combustível. 
-Assistência Médica
-Assistência Odontológica
-Seguro de Vida 
-Gympass

## Contratação

CLT

## Como se candidatar

Por favor envie um email para e-mail: belen.ramirez.tech@gmail.com, com seu CV anexado - enviar no assunto: Vaga Mobile

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: belen.ramirez.tech@gmail.com

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
