### ISSUE TITLE
[Remoto] Sr. Front End Developer na AY

### ISSUE THREAD

**Issue by lucasavila00** [frontendbr/vagas#4651]
## [Remoto] Sr. Front End Developer na AY

A Assertive Yield fornece soluções de coleta de dados, análise e otimização para editoras digitais.

A empresa trabalha de forma totalmente remota, toda a comunicação é em inglês e é necessário inglês escrito fluente.

A posição é para trabalhar na visualização dos dados dos clientes que consistem em bilhões de eventos a cada mês. A interface utiliza um alto nível de abstração e o desempenho de renderização é a chave para tudo. 

Portanto, estamos à procura de desenvolvedores experientes em React que conheçam os aspectos internos e externos do desempenho e da abstração com React.

# Requisitos

## Obrigatório

- Normas UI/UX

- React (profundo entendimento do desempenho e da capacidade de trabalhar com altos níveis de abstração)

- Jest incl. renderização

- CSS

- Git (PullReqs, Branches...)

## Desejável

- CI

- Experiência com Storybook

- Experiência Docker

- Fullstack (NodeJS, Golang)

## Importante para o sucesso

- Capacidade de apresentar código totalmente testado que passa em QA +70% do tempo

- Alta qualidade de código e convenções de nomenclatura

- Experiência de trabalho em equipes de desenvolvimento

## Benefícios

- 5-15k - com base na experiência

- Seu próprio horário de trabalho

- Salário competitivo

#  Como se candidatar

Favor enviar um e-mail com os seguintes detalhes para jobs-frontend@assertiveyield.com (em Inglês)

- Resumo rápido por escrito da experiência relevante e dos desafios nos quais você trabalhou

- Link para o perfil do Github se ele contiver contribuições relevantes de código aberto

- Qual é a sua situação atual? Quando você poderia começar o mais cedo possível?

- CV

## Processo de contratação

1. Os e-mails são analisados duas vezes por semana

2. No prazo de uma semana, enviaremos uma task de avaliação, de 20-30 minutos, para ser feita "em casa"

3. No prazo de uma semana, faremos uma entrevista de "live coding"

4. No prazo de uma semana, enviaremos rejeição ou oferta

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
