### ISSUE TITLE
[Remoto/SP/RJ] Front-end Developer na OLX Brasil

### ISSUE THREAD

**Issue by LuannaMiranda1** [frontendbr/vagas#4652]
> Vaga Remota durante a pandemia

## Nossa empresa

Quer fazer parte de uma das mais relevantes empresas 100% digitais do mercado brasileiro? Nós, da OLX Brasil, estamos de portas abertas para você.

Agora nós somos uma holding com duas business units (unidades de negócio): a OLX e o Zap+. Somamos nossa expertise em tech e produto para continuarmos desenvolvendo tecnologia feita em casa e nos tornando cada vez mais uma referência no segmento de anúncios online. Só nosso time de tecnologia conta com quase 400 pessoas com grandes desafios. Afinal, conectamos milhares de pessoas diariamente, com mais de 500 milhões de anúncios publicados todos os dias, que recebem mais de 70 milhões de visitas por mês.

Se você gosta de aprender e quer fazer parte desse desafio, essa oportunidade é  a sua chance, Desenvolvedor(a) de Software, nessa posição você vai somar no time de Tecnologia. 

Na OLX entendemos que desenvolvimento de software vai além de programação. Buscamos candidatos que sejam apaixonados por tecnologia e entendam a importância de usarmos boas práticas (Engenharia de Software, Arquitetura, Algoritmos, Cultura Agil, etc) no desenvolvimento de um produto.

## Descrição da vaga

No seu dia a dia, você deve ir além dos códigos e trabalhar em conjunto com os demais times de engenharia para construir e manter produtos que colocam os nossos clientes no centro das decisões - que é o que nos diferenciam das demais empresas de tecnologia. Uma pessoa desenvolvedora  de sucesso no Zap+, prima pela excelência do software, aliando o seu conhecimento técnico e experiência, com uma postura de dono(a) e um viés de ação. Você terá autonomia, mas com a responsabilidade de entregar um software que atenda um volume massivo de requisições, com alta disponibilidade e que gere um impacto ressonante para o nosso negócio. 

## Local

Exemplo: Remoto ou Escritório, [São Paulo], [SP], [Bela Cintra] ou [Rio de Janeiro], [RJ], [Flamengo]

## Requisitos

**Obrigatórios:**

- Experiência prévia com desenvolvimento de software front-end;
- Conhecimento em arquitetura de software e boas práticas de desenvolvimento;
- Conhecimento em JavaScript e DOM;
- Atenção com a qualidade e padronização do código, garantindo legibilidade, escalabilidade e performance;
- Capacidade de elaborar testes unitários e de integração;
- Conhecimento em CI/CD com preprocessors, transpilers, bundles etc.

**Desejáveis:**

- Vivência próxima com sistemas em produção e experiência em performance e testes A/B;
- Conhecimento sobre semântica e SEO;
- Conhecer BEM ou outras metodologias de organização de CSS;
- Experiência prévia realizando testes e2e;
- Ter experiência com algum framework SPA.

## Contratação

CLT

## Como se candidatar

Por favor envie um email para michely.santana@olxbr.com com seu CV anexado - enviar no assunto: Vaga - Frontend 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.
E-mail para contato em caso de não haver resposta:  michely.santana@olxbr.com

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
