### ISSUE TITLE
[Remoto / Sao Paulo] -  Angular Front-end Developer na Capco

### ISSUE THREAD

**Issue by Tai-Morena** [frontendbr/vagas#4654]
Somos da **CAPCO**, uma multinacional do Reino Unido, e atuamos em 32 países, especialmente no Ramo Financeiro.

No momento estamos atuando 100% Home Office, e após a pandemia, iremos atuar no modelo Hibrido - SP.

Vaga: **Angular Front End Developer** que possua atuação com 

**Beneficios:**
- VR+VA+Auxilio Combustive
- PLR
- Previdência Privada
-  Auxilio Creche
- Gym Pass
- Descontos em Pós e Faculdades, entre outros
- Planos de carreira com Coach

**Requisitos necessários:**
- Formação completa em T.I.
- Experiência com Angular (2+)

**Diferencial:**
- Ter atuado em ramo financeiro
- inglês avançado

Quem tiver interesse, enviar cv por email para:

tainan.nogueira@capco.com

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
