### ISSUE TITLE
[Florianópolis/Remoto] Front-end Developer na Mission Brasil

### ISSUE THREAD

**Issue by paruckerr** [frontendbr/vagas#4655]
> Vaga Remota durante a pandemia

## Mission Brasil

Aqui na [Mission Brasil](https://www.missionbrasil.com.br) estamos construindo algo disruptivo e inovador. Em 2020 recebemos investimento feed para iniciar uma nova jornada em busca do Series A, estamos super empolgados e gostaríamos que você fizesse parte desse grande desafio que temos pela frente.

## Descrição da vaga

Buscamos pessoas desenvolvedoras que curtam novos desafios, que busquem resolver problemas, entregar tarefas com qualidade, auto-gerenciamento e que tenham boa comunicação.

## Local

Remoto ou Escritório, SC, Florianópolis, Agronômica.

## Requisitos

**Obrigatórios:**
- Reactjs;
- Hooks;
- Redux;
- Restful API oriented design;
- Styled Components;

**Desejáveis:**
- React Native;
- Noções de UX;
- Mobile;
- Xcode;
- Android Studio;
- Appium;
- Code Push;

**Diferenciais:**
- Flexibilidade de horário;
- Excelente localização;

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para eduardo.parucker@missionbrasil.com.br com seu CV anexado - enviar no assunto: Vaga Front-End Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: eduardo.parucker@missionbrasil.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by paruckerr** [comment]
up

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by paruckerr** [comment]
up

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by paruckerr** [comment]
up

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by paruckerr** [comment]
up

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by paruckerr** [comment]
up
