### ISSUE TITLE
[São Paulo / Remoto] Front-end Developer na TRACTIAN

### ISSUE THREAD

**Issue by ericamafra** [frontendbr/vagas#4656]
> Vaga Remota durante a pandemia

## Nossa empresa

A TRACTIAN é a startup industrial de mais rápido crescimento no Brasil. Facilitamos a vida dos gestores de manutenção ao eliminar rotinas de planilhas intermináveis e quebras inesperadas. Somos como um Shazam, escutamos a condição das máquinas e prevemos anomalias. Em janeiro de 2021, recebemos um aporte da Y Combinator (W21), maior fundo early-stage do mundo, para mostrar que aqui também se faz startup boa para a indústria. Junte-se a nós!!

## Descrição da vaga

Com a gente você vai:

- Desenvolver produtos e serviços que atendem as necessidades dos nossos clientes com as melhores tecnologias front-end do mercado
- Criar e dar manutenção nas nossas novas funcionalidades em ReactJS
- Dar vida aos novos gráficos da plataforma que os gestores de manutenção utilizam diariamente
- Interagir com bases de dados não relacionais e criar novas APIs REST

## Local

Exemplo: Remoto ou Escritório, [SP], [São Paulo], [Vila Mariana]

## Requisitos

**Obrigatórios:**
Não exigimos cursos específicos. Acreditamos muito em pessoas dispostas para aprender o que for preciso com muita velocidade.

**Desejáveis:**
- Experiência em HTML e SCSS
- Experiência em Javascript (ReactJS)
- Experiência com frameworks e design de páginas
- Experiência em desenvolvimento de aplicações responsivas
- Facilidade em aprender novas tecnologias e conceitos

**Diferenciais:**
- Diferencial: Conhecimento em Redux/Recoil, Typescript e Arquitetura Limpa

## Benefícios

- Salário competitivo e bônus em stock options
- Cajuzinho de R$300/mês para você gastar com seu 
bem-estar, entretenimento e crescimento pessoal

**Diferenciais:**
- Autonomia para tomar decisões sem precisar investir tempo e energia em reuniões desnecessárias
- Plano de Carreira, metas e recompensas

## Contratação

PJ a combinar

## Como se candidatar

Por favor aplique pelo link abaixo:
https://www.notion.so/TRACTIAN-Carreiras-ec9892386a2248889f317547ab859d1a

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime

- Estágio

- PJ

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
