### ISSUE TITLE
[Remoto] FullStack Developer na Professor Ferretto - Nodejs + React

### ISSUE THREAD

**Issue by rcmerlo** [frontendbr/vagas#4657]
**Professor Ferretto** procura um(a) FullStack Developer para se juntar ao time. Queremos uma pessoa curiosa, criativa e com muita vontade de aprender.

### Requisitos
---
**Obrigatórios:**

- Escrever HTML semântico e acessível
- Desenvolvimento de interfaces utilizando HTML, CSS e técnicas de design responsivo
- Conhecimento de styled-components
- Conhecimento básico/intermedário no Storybook
- Entendimento básico de todo processo web (design, desenvolvimento e deploy)
- Capaz de construir stateless e statefull components utilizando React
- Sabe consumir uma API e formatar os dados recebidos
- Nodejs
- ReactJS

**Diferenciais:**

- Conhecimento de Graphql (ter trabalhado profissionalmente com, ganha mais pontos)
- Experiência com React Native
- Testes (TDD, integração, E2E)

### Benefícios
---
**Contratação:**

- PJ com salário de até R$ 10 mil dependendo do nível

**Ambiente:**

- **Full Remoto**
- Usamos **Github** para todos nossos projetos

### Local
---
Remoto

### Sobre a Professor Ferretto
---
A empresa Professor Ferretto é referência na área de cursos online pré-vestibular. Aliando qualidade de ensino com excelente custo-benefício, oferece uma preparação completa para a prova do ENEM e vestibular nas disciplinas de Matemática, Ciências da Natureza e Ciências Humanas. O ensino ocorre através de uma plataforma online, que oferece todos os recursos para que o aluno possa estudar de forma totalmente independente.

### Como aplicar
---
Basta enviar email com CV em anexo para:  katiany@professorferretto.com.br

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
