### ISSUE TITLE
[São Paulo] Front-end Developer na T4W Tecnologia

### ISSUE THREAD

**Issue by GeracaoTalento** [frontendbr/vagas#4658]
Sobre a Empresa: Grande porte de Tecnologia desenvolvedora de soluções para o mercado de Turismo, localizada na região da Vila Olímpia – São Paulo - SP.

Atuará como Desenvolvedor .NET Frontend, no desenvolvimento de novas funcionalidades e manutenção da plataforma. 

Requisitos: 

- HTML, CSS3, JavaScript, TypeScript 
- SASS e LESS 
- AngularJs e Angular 2+ 
- Otimização, Responsividade e experiência do cliente nos dispositivos desktop e mobile 
- RESTful APIs 
- Design Patterns 

Desejável:

- Linguagem C# 
- Asp.net Core 2.0 
- Team Foundation Server (TFS) 
- MySQL 
- MongoDB 
- Gulp.js 

Diferencial (não obrigatório)

- Conhecimento em UX e Usabilidade
- Ter trabalhado no mercado de turismo 

- Trabalho Remoto (home office)

- Contratação como PJ

Enviar CV com pretensão PJ para Marcelo : marcelo@geracaotalento.com.br

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
