### ISSUE TITLE
[Remoto] Junior Front-end Developer no Inatel

### ISSUE THREAD

**Issue by lpliao** [frontendbr/vagas#4662]
## Descrição da vaga

O Inatel está recrutando Especialista para atuar como Desenvolvedor Front-end, no ICC Software Aplicativo.

**Responsabilidades:**

- Desenvolver aplicações Front-end;
- Preparar, configurar e disponibilizar ambientes de desenvolvimento e testes;
- Configurar container para os projetos;
- Codificar bancos de dados relacionais e não relacionais;
- Depurar códigos em diferentes ferramentas;
- Atuar em correções/ajustes da solução;
- Realizar testes em ambiente de desenvolvimento;
- Elaborar documentação de projeto.

## Local

Exemplo: Remoto 

## Requisitos

**Obrigatórios:**
Ensino Superior Completo, preferencialmente em cursos de Computação, Sistemas de Informação ou Ciência da Computação;
Domínio de lógica de programação e programação orientada a objetos;
Conhecimentos em: Controle de versão Git, API RESTful, Linguagem de programação Java, SQL, Javascript, Frameworks React, AngularJS, Angular, HTML/CSS;
Inglês intermediário.

## Contratação

CLT

## Como se candidatar

Pelo link https://jobs.kenoby.com/inatel/job/desenvolvedor-front-end-i-home-office/603e683fda70fa06d43e35f3?utm_source=website

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Júnior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
