### ISSUE TITLE
[Porto, Portugal] [Visa Sponsorship] Front-end Developer na New Work SE

### ISSUE THREAD

**Issue by rlage** [frontendbr/vagas#4664]
> Vaga Remota durante a pandemia

## A empresa

A [New Work SE](https://www.new-work.se/en/) é uma grande empresa alemã, que oferece uma grande quantidade de produtos e serviços para melhorar a experiência do mercado de trabalho. Não é uma consultoria, é uma empresa que possui diversas empresas que possuem seus próprios produtos.

## Descrição da vaga

Essa vaga, em específico, é para a Xing, uma plataforma de rede social profissional, líder no mercado dos falantes de língua alemã. A [Xing](www.xing.com) conta com mais de 18 milhões de membros e procura ajudá-los a encontrar o melhor trabalho, o melhor colaborador, promover eventos e encontros interessantes (mesmo online), entre outras funcionalidades, com o objetivo de proporcionar a melhor experiência possível no mercado de trabalho.

## Local

Porto, Portugal (oferece sponsor para o visto de trabalho e apoio no processo)
Na pandemia: Remoto
Pós-pandemia: Provavelmente 50/50

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com React
- Testes unitários
- Inglês fluente

**Desejáveis:**
- GraphQL
- Typescript
- React Testing Library

## Benefícios

- Plano de saúde
- VR

**Diferenciais:**
- Excelente equilíbrio entre vida e trabalho
- Escritório pós pandemia (videogame, ping pong, pão...)
- 2 semanas no ano livres para poder desenvolver projetos pessoais
- Budget para treinamentos

## Contratação

Contrato equivalente ao CLT do Brasil. Inicialmente, enquanto o visto não é expedido, é permitido trabalhar remotamente do Brasil, recebendo como Freelancer

## Como se candidatar

Por favor envie um email para rafael.tavares@xing.com com seu CV (em inglês) anexado - enviar no assunto: Vaga React Xing

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by rlage** [comment]
Oi @felipefialho , se puder, remova a tag São Paulo, pois o trabalho é em Portugal, por favor. Obrigado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
