### ISSUE TITLE
[Remoto] Front-end Developer na CWI Software

### ISSUE THREAD

**Issue by CWI-RH** [frontendbr/vagas#4665]
==================================================
-->[REMOTO] Front-End Developer na CWI Software

<!--
==================================================

## Descrição da vaga

Estamos com projetos em nichos varejistas, bancários e financeiros para atuação como Front-end React ou Angular

## Local

Exemplo: [REMOTO]

## Requisitos

**Obrigatórios:**
Para React:
Experiência em desenvolvimento web responsivo, seguindo as melhores práticas;
- React ou Angular nas versões de 2 em diante.
- TypeScript
- Testes unitários em frontend utilizando Jest
- Git
- Trabalho em equipe
- Metodologias ágeis

**Desejáveis:**
- NextJS
- Styled Components
- Styled System
- Redux & Saga

## Benefícios

- Plano de saúde
- VR de R$ à combinar/dia
- Auxílio Odonto
- ...

**Diferenciais:**
- FullRemoto
-  Formações internas
- ...

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um email para work@cwi.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: wendel.dorneles@cwi.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by rjulio** [comment]
Boa tarde, teria mais informações sobre a vaga?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
