### ISSUE TITLE
[Remoto] Front-end Developer na Tatango

### ISSUE THREAD

**Issue by marisnner7** [frontendbr/vagas#4666]
## Descrição da vaga
Tatango is looking for a passionate software developer to join our growing (and 100% remote)
engineering team. You’ll be working to help modernize the Tatango user experience and to add
exciting new features as we continue to scale in a fast-paced industry

## Requirements:
● 2+ years of React experience
● Experience working with back-end REST API’s
● Ability to work in a fast-paced environment and dealing with ambiguity
● Solid verbal and written English communication skills
● Good analytical and problem-solving skills

**Desejáveis:**
Extra Credit:
● Experience writing software in Ruby on Rails
● Experience writing software in Node.js
● High proficiency with CSS
● Strong sense of system architecture and design patterns

## Como se candidatar

Me chama no linkedin(Marianne Aguiar) ou email mariannehaguiar@gmail.com que eu mando pro CTO

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
