### ISSUE TITLE
[Remoto] Desenvolvedor React Native na Join Tecnologia

### ISSUE THREAD

**Issue by NerdProgramador-com-br** [frontendbr/vagas#4667]
## Descrição da vaga 
Alô Desenvolvedores Mobile!! Se você curte trabalhar com React Native, e gosta de desafios, essa vaga é para você!! 

  

Como Desenvolvedor Mobile você irá atuar com desenvolvimento utilizando React Native, irá realizar implementação dos códigos fontes de artefatos de implementação de acordo com os padrões de arquitetura e projeto definidos, irá apoiar o Scrum Master no planejamento das sprints e seguir as melhores práticas definidas para codificação na linguagem de programação e framework adotados.

  

Vaga 100% remota para atender um dos nossos cliente no Ceará. Aceitamos candidatos de todas as regiões do Brasil =D
## Local 
REMOTO 
## Como se candidatar 
Accesse a [Vaga de Desenvolvedor React Native](https://nerdprogramador.com.br/join-tecnologia-desenvolvedor-react-native/5eb0b94e-5ea6-4c13-9700-c588d22e8c85?utm_source=github) para mais informações. 
## Labels 
* Remoto

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
