### ISSUE TITLE
[Floripa] Front-End Engineer na Chaordic

### ISSUE THREAD

**Issue by zago** [frontendbr/vagas#467]
## Descrição da vaga

Linx+Neemu+Chaordic uniram suas forças para mudar ainda mais o mundo do ecommerce e do varejo como um todo. Proporcionamos a cada usuário uma experiência única e personalizada no momento de fazer suas compras. Para isso, temos em mãos uma das maiores bases de dados de comportamento de compra online da América Latina, e a usamos para construir recomendações para milhões de pessoas que hoje navegam nos sites dos nossos clientes. o/

Então, você está procurando algo legal para fazer? Bom ... precisamos conversar!

Se você é aquele desenvolvedor que se interessa não só pelas linguagens da sua área, mas em sair do seu quadrado e gosta de trabalhar em projetos inovadores que realmente fazem a diferença e causam grande impacto na vida das pessoas, bem... é por você que estamos procurando.

Aqui estão alguns sinais de que teríamos um bom "match":

- Domínio de Javascript
- Conhecimentos em HTML e CSS
- Conhecimento em Git
- Ferramentas de buid(Grunt, Gulp, NPM)
- Algum framework SPA(Angular, React, Vue)
- Estar atualizado em relação as novas tendências no mundo da tecnologia da sua área (ECMAScript6, por exemplo)
- Noções técnicas de inglês: A língua padrão de comunicação dentro do código é o inglês.

Desejáveis
- UX/UI experience
- Test-driven-development
- Functional & Reactive Programming

## Local

Lagoa da Conceição, Florianópolis - SC

## Benefícios

- Plano de saúde
- Plano odontológico
- Seguro de vida
- VR / VT
- Café da manhã 
- Café da tarde (bolos, cucas, pao de queijo, etc..)

#### Diferenciais

- cozinha(bar) comunitária
- Happy hours frequentes dentro da própria sede (é bem legal aqui)
- Sede irada da uma espiada nas [fotos](http://bit.ly/2u9238I), e fica na Lagoa da Conceição em Floripa, ve as [fotos](http://bit.ly/2u94eJp) tb . ;) )

## Requisitos

**Obrigatórios:**
- Ter experiência com algum framework SPA
- Noções de arquitetura e banco de dados

## Contratação

CLT

## Nossa empresa

http://chaordic.com.br

## Como se candidatar

https://linxneemuchaordic.recruiterbox.com/jobs/fk0mosv/

**Comment by danielGalvao** [comment]
Séloco trabalhar com o @diogomoretti  IRADO!

**Comment by diogomoretti** [comment]
@danielGalvao dia 11/agosto é oficialmente meu último dia. Mas SUPER RECOMENDO a empresa.

**Comment by zago** [comment]
Closed!
