### ISSUE TITLE
[Rio de Janeiro] Front-end Developer Jr ou Pleno na Plannera

### ISSUE THREAD

**Issue by Planneraa** [frontendbr/vagas#4671]
[Rio de Janeiro] Front-End Developer na Plannera
==================================================
-->
> Vaga Remota durante a pandemia

**## Nossa empresa**

Somos uma boutique especializada em implantar e apoiar processos de planejamento colaborativo em médias e grandes empresas. Trabalhamos a quatro mãos com a equipe de clientes como Coca Cola, Souza Cruz e outras, para gerar resultados reais, trabalhando nas dimensões de Pessoas, Processos, Tecnologia e Data Science. 

**## Principais desafios**

- Desenvolver e propor melhorias em funcionalidades do lado do cliente (front-end) para fornecer melhor experiência ao usuário final;​
- Construção de novos componentes e produtos para melhor atender os clientes;​
- Identificar bugs e problemas de performance no código existente e aplicar as correções;​
- Entregar com autonomia um código testável com qualidade, estimando o esforço e o custo necessário para cumprir expectativas acordadas e comunicando necessidade de novos prazos

**## Competências Técnicas**

- Sólido conhecimento em lógica de programação e metodologia de desenvolvimento;​
- Sólido conhecimento em HTML, CSS e Javascript;​
- Familiaridade com API Rest;​
- Experiência com AngularJS ou Angular 7+;​
- Breve conhecimento de VueJS ou ReactJS;​
- Experiência com desenvolvimento de aplicação SPA; ​
- Práticas de desenvolvimento orientado a testes; ​
- Conhecimento de versionamento usando Git (incluindo Code Review).

## Benefícios

- Auxílio Home office
- Vale Happy hour

**Diferenciais:**
- Horário flexível
- videogame (quando voltarmos para o escritório)
- cerveja na geladeira (quando voltarmos para o escritório)

## Contratação

PJ

## Como se candidatar

Por favor envie um email para curriculos@plannera.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Developer.

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
