### ISSUE TITLE
[Brasília-DF] Front-end Developer na IDVLab

### ISSUE THREAD

**Issue by matheusgvieira** [frontendbr/vagas#4674]
> 

## Nossa empresa

A IDVLab é uma empresa de tecnologia que trabalha com desenvolvimento de software, hardware e firmware. Nós desenvolvemos nossos produtos e soluções. Todo o know how da empresa é fruto da experiencia do nosso time composto pela diretoria comercial responsável pela rede de contatos e relacionamentos e de engenharia composta por colaboradores, que somados aos anos de dedicação acadêmica e experiencia profissional de mercado são capazes de criar soluções para conectar uma infinidade de coisas (equipamentos, dispositivos e muito mais) à internet.

Em nossos projetos buscamos a transparência e a excelência máxima, seja por meio de nossa equipe própria de profissionais altamente qualificados nas diversas plataformas tecnológicas disponíveis no mercado, quer seja por uma de nossas empresas associadas. Juntos formamos um grande time com muita experiência em tecnologia.

## Descrição da vaga

Desenvolvimento de aplicativos web responsivos em React e mobile com React-Native.

## Local

Exemplo: Escritório, Distrito Federal, Brasília, Asa Norte

## Requisitos

**Obrigatórios:**
- 1 anos de experiência com Node 
- 2 anos de experiência com React
- 2 anos de experiência com bancos relacionais.

**Desejáveis:**
- conhecimentos em React Native 

**Diferenciais:**
- projetos Django

## Benefícios

- Plano de saúde
- Vale Refeição ou Alimentação
- Vale-Transporte

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um email para idvlab@idvlab.com.br com seu CV anexado - enviar no assunto: Desenvolvedor React

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: idvlab@idvlab.com.br

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
