### ISSUE TITLE
[Projeto Remoto] Desenvolvedor Full Stack Sênior na Visionnaire

### ISSUE THREAD

**Issue by marinasgriza** [frontendbr/vagas#4675]
🙌 **Helloo Full Stack Developerss!**
Temos um projeto **internacional** pra vocês! 💃

A Visionnaire é uma fábrica de software de mais de 24 anos, sendo responsável pelo desenvolvimento, manutenção,
testes de software em ambiente corporativo e serviços de profissionais de TI, com atuação nacional
e internacional.

✨**Desenvolvedor Full Stack Sênior** ✨

✔Requisitos **fundamentais:**
- Experiência como desenvolvedor Full Stack;
- Experiência com desenvolvimento Web;
- Experiência comprovada com HTML/CSS, JavaScript e jQuery;
- Experiência comprovada com Python/Django e/ou Java/Spring Framework;
- Experiência comprovada com ReactJS e
- **Inglês intermediário a avançado, ok?!** 💭

✔Requisitos desejáveis:
- Experiência com Desenvolvimento mobile;
- Experiência com cloud-stacks, e.g., AWS, Kubernetes, OpenShift;
- Experiência com React Native;
- Experiência com MongoDB.

⚖️ Contratação: PJ

💻Para se candidatar acesse o link abaixo ou envie seu currículo no e-mail: recrutamento_selecao@visionnaire.com.br - enviar no assunto: Vaga Desenvolvedor Full Stack Sênior.
https://lnkd.in/eqykT_B

#fullstacksênior #python #internacional #react
![210414-Arte-Vaga-Desenvolvedor-Full-Stack-SR](https://user-images.githubusercontent.com/82222290/114881211-2b02cd00-9dd9-11eb-98cc-592a8bbdfb35.png)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
