### ISSUE TITLE
[Remoto] Fullstack Developer (Node.js Stack) na Tatic

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#4676]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url https://coodesh.com com o pop-up personalizado de candidatura. :wave:
<h4>Conheça a Tatic</h4>
<p>Com mais de 15 anos de experiência, a Tatic é uma empresa inovadora de tecnologia da informação. Nossos serviços e soluções irão modernizar sua arquitetura de dados e impulsionar a adoção da inteligência artificial na tomada de decisões de negócios: uma verdadeira parceria estratégica para o sucesso.</p>
<p>Os produtos e serviços Tatic atendem às necessidades de tratamento e armazenamento de grandes volumes de dados, potencializando os BSS (Business Support Systems) e a aplicação de Machine Learning, Analytics avançado e muito mais para seu negócio.</p>
<p>Hoje, grandes corporações em nível global já se beneficiam da nossa expertise para otimizar investimentos, reduzir custos operacionais, reter e fidelizar clientes e aumentar receita. Afinal, a eficiência em dados transforma resultados.</p>
<h4>Como é ser um dev na Tatic?</h4>
<ol>
<li>Ter paixão por aprender novas tecnologias</li>
<li>Desenvolver códigos com as boas práticas de qualidade (TDD, BDD and beyond)</li>
<li>Saber se relacionar bem com outros devs e os líderes do projeto.</li>
<li>Saber que o problema de um é um problema de todos</li>
<li>Gostar de aprender</li>
<li>Estar aberto a aprender novas formas de codificar</li>
<li>Ter o domínio técnico das tecnologias utilizadas nos projetos</li>
<li>Garantir que o desenvolvimento siga os padrões e melhores praticas do mercado</li>
<li>Garantir a qualidade dos produtos desenvolvidos</li>
<li>Aproveitar bem os nossos happy hours!!</li>
</ol>

## Tatic: 
 <p>Com mais de 15 anos de experiência, a Tatic é uma empresa inovadora de tecnologia da informação. Nossos serviços e soluções irão modernizar sua arquitetura de dados e impulsionar a adoção da inteligência artificial na tomada de decisões de negócios: uma verdadeira parceria estratégica para o sucesso.</p>

<p>Os produtos e serviços Tatic atendem às necessidades de tratamento e armazenamento de grandes volumes de dados (big data e analytics). E hoje, grandes corporações em nível global já se beneficiam da nossa expertise para otimizar investimentos, reduzir custos operacionais, reter e fidelizar clientes e aumentar receita.</p><a href='https://coodesh.com/empresas/tatic'>Veja mais no site</a>

 ## Habilidades: 
 - MongoDB 
- Vue.js 
- Google Cloud 
- Node.js 
- Nuxt.js
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência em projetos com Stack Node.js 
- Conhecimento de metodos ágeis 
- Experiência com MongoDB

## Benefícios: 
 - 100% remoto
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack Developer (Node.js Stack) na Tatic](https://coodesh.com/vagas/fullstack-dev-nodejs-stack-112034?origin=github&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção <b>Pedir Feedback</b> entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa <b>Recruiter</b> responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
