### ISSUE TITLE
[Remoto] Fullstack Developer (foco em back-end) na EduQ

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#4677]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url https://coodesh.com com o pop-up personalizado de candidatura. :wave:
<p>Estamos buscando <strong><em><ins>pessoas desenvolvedoras fullstack javascript</ins></em></strong> para atuar full-time 100% remoto na <strong>EduQ</strong>.&nbsp;</p>
<p>Maior foco dos perfis em backend node, mongo e graphql.&nbsp;</p>

## EduQ: 
 <p>A EduQ surgiu para modificar a maneira como a preparação de médicos para a prova e Residência Médica (especialização) acontece. Desenvolvemos uma metodologia que tira o foco do estudo da apostila/videoaula e leva para o paciente, trazendo humanização ao processo de aprendizado e melhorando a retenção do conhecimento no longo prazo.&nbsp;</p>
<p>A inovação em nossa metodologia educacional garantiu que fôssemos incubados no Hospital Albert Einstein e, apesar do pouco tempo da empresa, contamos com mais de 30 mil usuários inscritos na plataforma (formam-se menos de 25 mil médicos por ano no Brasil).</p><a href='https://coodesh.com/empresas/eduq'>Veja mais no site</a>

 ## Habilidades: 
 - MongoDB 
- React.js 
- Typescript 
- Node.js 
- GraphQL
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência prévia nas stacks 
- Conhecimentos ou experiência como Front-end Developer ou Back-end Developer 
- Habituado em ler e criar documentações de endpoints com Swagger 
- Conhecimentos ou experiência em desenvolvimento Front-end usando React.js 
- Escreva código bem projetado, testável e eficiente 
- Habituado em trabalhar com programação orientada a objetos 
- Domínio em Javascript e/ou Typescript 
- Conhecimentos e boas práticas com HTML5 / CSS3 
- Conhecimentos ou experiência em desenvolvimento de REST APIs usando Node.js + MongoDB

## Benefícios: 
 - Horários flexíveis 
- Programa de desenvolvimento individualizado 
- 100% remoto
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack Developer (foco em back-end) na EduQ](https://coodesh.com/vagas/backend-developer-20210410?origin=github&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção <b>Pedir Feedback</b> entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa <b>Recruiter</b> responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Back-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
