### ISSUE TITLE
[Manaus] Full Stack Developer na Way Consultoria e Psicologia

### ISSUE THREAD

**Issue by NerdProgramador-com-br** [frontendbr/vagas#4678]
## Descrição da vaga 
**Atividades**

\- Desenvolvimento de novas funcionalidades em sistemas web frontend/backend;

\- Desenvolvimento da interface de interação com o usuário.

  

**Requisitos**

\- Formação superior em Engenharia Elétrica, Computação, Sistemas de Informação ou similar;

\- Experiência com NodeJS, Express, APIs REST e BDD;

\- Experiência com banco de dados MySQL;

\- Experiência com Javascript, CSS, Bootstrap, HTML e Angular;

\- Inglês intermediário para conversação, escrita e leitura.

  

Candidatos fora de Manaus também podem participar.
## Local 
Manaus/Amazonas 
## Como se candidatar 
Accesse a [Vaga de Full Stack Developer](https://nerdprogramador.com.br/way-consultoria-e-psicologia-full-stack-developer/09c93f11-35fa-4c33-ac71-a2bcc935c467?utm_source=github) para mais informações. 
## Labels 
* Alocado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
