### ISSUE TITLE
[REMOTE] Senior VueJs Developer For International Remote Project

### ISSUE THREAD

**Issue by joaovictortinoco** [frontendbr/vagas#4679]
## Empresa

Parceiro trabalha na Ucrânia e possui demanda de projeto com Vue.Js.

Procura por pessoa sênior que tenha um domínio maduro com a tecnologia

## Descrição da vaga

- Experiência sólida com VueJs
- Inglês sólido para comunicação efetiva (conversação e escrita)

## Local

- Remoto

## Requisitos

**Obrigatórios:**
- VueJs
- Inglês Intermediário/Avançado para escrita e comunicação

**Desejáveis:**
- Conhecimento com NextJs

## Contratação

PJ
Valor de hora: USD 25

## Como se candidatar

Por favor envie um email para gleb@paradigma.dev com seu CV anexado EM INGLÊS - enviar no assunto: VueJs Developer - SeuNome

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by juliovedovatto** [comment]
@joaovictortinoco 

> Desejáveis:
> 
> - Conhecimento com NextJs

Não seria Nuxt.js? 

Pergunto pois a vaga é para Vue, porém NextJS é p/ React.

**Comment by pedroch4610** [comment]
@joaovictortinoco

A vaga é para Freelancer ou Efetivo?

**Comment by glbchk** [comment]
Hello, guys!

I would like to clarify one moment. It's my mistake, but our agency offers a maximum 20 USD per hour.

Best regards,
Glen

**Comment by joaovictortinoco** [comment]
Oi pessoal, fechando essa issue pois a chamada foi encerrada.
