### ISSUE TITLE
[São Paulo] Front-end Developer na Itelios

### ISSUE THREAD

**Issue by florbraz** [frontendbr/vagas#468]
## Descrição da vaga

Temos mais duas vagas abertas pra desenvolvedores front-end aqui na Itelios :) Agora, estamos focando nos níveis junior e pleno.

Na Itelios, você trabalhará em um time jovem, multidisciplinar e apaixonado por tecnologia. Você trabalhará em diferentes projetos de sistemas, portais e e-commerces, em contato direto com outros desenvolvedores e gerentes de projeto, nos nossos escritórios em São Paulo, NY e na França (Paris, Lille e Mâcon). 

Fará parte do seu dia-a-dia desenvolver e sustentar o front-end de websites responsivos (sempre sendo bem cuidadoso em relação ao layout proposto), analisar layouts (de forma a identificar possíveis problemas de implementação), propor soluções e trazer melhorias para o nosso fluxo de trabalho (como um todo, mas em especial, voltado ao front-end). 
Além disso, você participará de palestras / treinamentos (assim como poderá preparar e apresentar os seus) e reuniões em conjunto com a equipe técnica, revisará o código de outros desenvolvedores e (potencialmente) tomará muito café. :)

## Local

Esta vaga é presencial (com possibilidade de combinar 1-2 dias remoto por semana), em nosso escritório em São Paulo, próximo à av. Paulista.

## Benefícios 

- Vale Refeição (R$ 22,00 dia);
- Vale Transporte (o quanto precisar, inclusive fretado);
- Assistencia Médica;
- Assistencia Odontológica;
- Seguro de Vida.

#### Diferenciais
- Possibilidade de trabalho remoto 1 a 2x por semana (estamos testando e estudando para aumentar);
- Não há co-participação nos nossos benefícios - não há desconto em folha.

## Requisitos

**Obrigatórios:**
- Trabalhou como front-end por pelo menos um ano;
- Sabe se comunicar e trabalhar em equipe;
- Experiência em desenvolvimento front-end + codificação de layouts responsivos utilizando pré-processadores (estamos utilizando Stylus, mas damos suporte a projetos com SASS);
- Desenvolvimento Javascript "vanilla" e/ou jQuery;
- Inglês (imprescindível para leitura e comunicação escrita).

**Desejáveis:**
- Experiência com algum framework SPA, como React, Vue, Angular.
- Experiência em integrações utilizando RESTful APIs;
- Git
- Conhecimento de alguma linguagem back-end;
- Facilidade em compartilhar conhecimentos;
- Inglês fluente.

**Diferenciais:**
- Experiência e conhecimentos em e-commerce;
- Já ter trabalhado com VTEX;

## Contratação

CLT full

## Nossa empresa

A Itelios é uma consultoria francesa de tecnologia para E-Commerce, Conteúdo e Omnichannel. Investimos fortemente em pessoas, construindo uma equipe capaz de entregar o melhor da tecnologia para facilitar a vida dos nossos clientes. Buscamos usar sempre o que há de mais inovador em termos de ferramentas e gestão. Somos parceira número 1 da Salesforce no Brasil e Europa, além de uma das maiores empresas de Drupal e Magento no Brasil. Pelo 2o ano consecutivo fomos premiados como Great Place to Work! :)

## Como se candidatar

Envie um email para flora.braz@itelios.com com seu CV anexado e pretensão salarial CLT. 

Assunto: Vaga Desenvolvedor Front-end

**Comment by florbraz** [comment]
Bom dia, pessoal! Quando postei a vaga originalmente, procurávamos níveis pleno e senior, mas essa vaga já foi preenchida. Hoje, buscamos nível junior a pleno. Alguém poderia trocar as labels, por favor?

**Comment by LFeh** [comment]
Claro! 

Mas não prefere abrir outra vaga?

**Comment by florbraz** [comment]
Pode ser :) Acabei editando o texto aqui...
