### ISSUE TITLE
[Remoto] Front-end Senior Developer na Pagar.me

### ISSUE THREAD

**Issue by LauraCorrea12** [frontendbr/vagas#4681]
Para ver a visualização completa/ se inscrever: https://boards.greenhouse.io/pagarme/jobs/4208606003

![Capa-LinkedIn_Pagar me-V2a](https://user-images.githubusercontent.com/80124214/115073329-8d89c500-9ece-11eb-8e93-73c5a0e967fc.png)

**Já conhece a Pagar.me?** 

Somos uma empresa focada em desenvolver soluções para os mercados de pagamento e financeiro no Brasil e fazemos parte do Grupo Stone Co. De pequenas lojas e startups a grandes e-commerces e marketplaces, criamos uma estrutura de pagamentos poderosa e flexível para atender diferentes clientes. 

Aqui, você irá trabalhar com um time apaixonado por desafios, focado no atendimento personalizado aos nossos clientes e em busca dos melhores resultados em suas entregas. Quer mais? Tudo isso em um ambiente descontraído e com uma galera que é referência no mercado de tecnologia!

**O que é ser Pessoa desenvolvedora Front-end | Software Engineer Front-end.?** 

 Aqui você vai colaborar com product managers, designers e software engineers para identificar oportunidades e implementar soluções e produtos para os nossos clientes. Desenvolver serviços e sistemas. Melhorar arquitetura e ou design dos sistemas atuais;

Buscamos alguém que se envolva ativamente na construção de produtos do começo ao fim, desde a experimentação, design, implementação e deploy, até o feedback dos clientes;

Trabalhar em conjunto com todo o time de tecnologia, revisando o trabalho de outras pessoas, participando de decisões importantes de produto e tecnologia, e garantindo a saúde dos nossos serviços.

**#O que não pode faltar?**

👾 Experiência com CSS, HTML e Javascript;

👾Experiência no desenvolvimento de uma aplicação React em produção;

👾Experiência com testes automatizados;

👾Experiência no desenvolvimento de interfaces mobile first.

**#O que aumenta a chance das pessoas nessa vaga?**

👾 Experiência com aplicação de um design system em um produto;

👾 Experiência com desenvolvimento em React Native;

👾 Experiência com Amazon AWS (S3 & [Cloudfront);](url)

👾 Experiência na implementação de processo de integração contínua e entrega contínua.

**Se inscreva aqui: https://boards.greenhouse.io/pagarme/jobs/4208606003**

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
