### ISSUE TITLE
[Remoto] Fullstack Developer (Node.js Stack) 

### ISSUE THREAD

**Issue by IlumeoTech** [frontendbr/vagas#4682]
Descrição da vaga
 SOBRE A ILUMEO:

 Somos uma consultoria de Data Science que propõe uma conexão grande entre Academia e Mercado. A proposta da Ilumeo é ser o parceiro de inteligência auxiliando gestores em decisões de risco complexas e que exigem a leitura e análise de dados. Em 9 anos, já realizamos mais de 500 projetos com as maiores empresas e agências do país, como Google, XP Investimentos, Youse, Quinto Andar, Stone, Natura, LATAM, Bayer e Rede Globo. Conheça alguns de nossos cases e textos sobre data Science.

 http://ilumeo.com.br

 

Na Ilumeo, você vai ter oportunidades de:

 • FLEXIBILIDADE PARA ESTUDAR:

Criamos uma cultura que estimula os colaboradores a fazerem Mestrado e Doutorado, mesmo que as aulas sejam durante o horário de trabalho. Acreditamos que o conhecimento do stricto sensu nos ajuda a inovar em método e atrair pessoas que têm Ímpeto pelo Conhecimento.

 • APRENDER ENQUANTO TRABALHA:

Aqui você vai interagir com consultores com muita experiência no Mercado e na Academia. A troca de conhecimento é intensa.

 • AUTONOMIA PARA CRESCER:

Queremos pessoas empreendedoras e que consigam construir seus projetos de maneira autônoma. Crescemos muito nos últimos anos criando produtos, não só fazendo mais do mesmo.

 

TRABALO NA PRÁTICA: 

Desenvolvimento e manutenção de aplicações web, sustentar integrações e em ambiente de produção; como por exemplo uma aplicação de cadastros e segmentação de usuários para envio de e-mails marketing, utilizando integração com o SurveyMonkey para uma gigante corretora brasileira.
Realizar a manutenção e criação de novas funcionalidades;  Foco na criação de página de usuários para cadastro;
Desenvolvimento de funcionalidades Full Stack;
Implantação de boas práticas, Documentação;
Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas;
Ajudar na construção da cultura e desenvolvimento da equipe;
Desenvolver novos processos e aprimorar processos existentes.

 REQUISITOS TÉCNICOS:

Conhecimentos em UX/UI;
Metodologia ágil;
Noção de Design Patterns;
Conhecimento em metodologias ágeis (Scrum/Kanban);
Sólido conhecimento em tecnologias Front-end e responsividade (HTML5, CSS3 e SASS, Boostrap, VueJs e JavaScript, Typescript);
Sólido Experiência prática com NodeJs (Avançado) e seu ecossistema: (Express, TypeORM, Mongoose)
SQL (Básico)
Conhecimento de implementação de APIs RESTful.
Conhecimento de implementação de microsserviços.
Conhecimento e configurações SES AWS 
Integração de soluções de armazenamento de dados com mongodb e datalake;
Compreender a natureza da programação assíncrona e suas peculiaridades e soluções alternativas.
Governança de APIs e operação de API Gateway (KONG, APIGEE, MULESOFT)
Compreendendo e atender as conformidade de segurança.
Autenticação e autorização de usuário entre vários sistemas, servidores e ambientes.
Integração de várias fontes de dados e bancos de dados em um sistema.
Compreendendo os princípios fundamentais de design por trás de um aplicativo escalável.
Criando esquemas de banco de dados que representam e suportam processos de negócios.
Implementando plataformas de teste automatizadas e testes de unidade.
Conhecimento proficiente de ferramentas de versão de código, como Git.
Conhecimento proficiente de integração contínua e pipeline de implantação contínua
  

 FORMAÇÃO E IDIOMA 
﻿

Áreas do conhecimento: Matemática, Estatística, Tecnologia, Análise e Ciência da Computação ou correlatos.
Escrita, leitura e fala fluentes em inglês
  

Boa sorte! 

Contatos pelo e-mail silvio.oliveira@ilumeo.com.br

**Comment by rodrigo-fonseca** [comment]
Qual o email para contato? ***@***.***? Peguei esse email site
acima

Em sex., 16 de abr. de 2021 às 16:25, IlumeoTech ***@***.***>
escreveu:

**Comment by IlumeoTech** [comment]
@rodrigo-fonseca - Rodrigo você pode mandar  silvio.oliveira@iluemo.com.br

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
