### ISSUE TITLE
[CURITIBA] Mobile Front-end Developer na Connect Plug

### ISSUE THREAD

**Issue by NovareRH** [frontendbr/vagas#4685]
## Nossa empresa

A CPlug surgiu de experiências de empresários não satisfeitos com ferramentas e plataformas atualmente disponíveis no mercado. Está presente em 100% dos estados brasileiros, trabalhando em parceria com milhares de clientes ativos nas mais diversas regiões e áreas de atuação como restaurantes, bares, lanchonetes e diversos estabelecimentos do comércio varejista em geral.
Seus produtos são: Gestão Completa, Frente de Caixa PDV, Mesas e Comandas e Auto Atendimento onde reúne soluções de PDV, ERP e autoatendimento para restaurantes, comércio e varejo em geral.
Recentemente a Locaweb anunciou a aquisição da Connect Plug.

## Descrição da vaga

- Saber desenvolver, testar, lançar e manter aplicações Android Nativas.
- Montar aplicações de ponta a ponta 
- Desenvolver e contribuir melhorias e inovação.  

## Local

[CURITIBA] [PARANÁ] [BATEL]
Preferencialmente presencial (cogitamos contratação remota).

## Requisitos

**Obrigatórios:**
Linguagens – Android Nativo e Kotlin
Banco de dados – Realm
Metodologias Ágeis – Scrum

**Desejáveis:**

- Flutter e Jetpack
- Trabalhar sobre pressão
- Comunicação
- Foco em resultado
- Resiliência
- Resolução de Problemas

**Diferenciais:**
- Entender muito de consumo e construção de API e utilização de Socket.
- Padrões de projetos e Clean code.
- Experiência nas tecnologias da vaga.
- Gostar de programar de verdade.

## Benefícios

- Treinamentos e Cursos para atualizações.
- VR – R$600,00
- Plano de Saúde – após 90 dias de contrato

## Contratação

- A partir de 8k – Contrato CLT

## Como se candidatar

Aplique para a vaga [por aqui](https://www.careers-page.com/novare-rh/job/8R53RR) .

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by MariPsi** [comment]
Vaga ainda aberta.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
