### ISSUE TITLE
[Remoto] Front-end Web Developer na Zenklub

### ISSUE THREAD

**Issue by falleco** [frontendbr/vagas#4688]
## Nossa empresa

O Zenklub é a plataforma de saúde emocional e mental líder em Portugal & Brasil e está procurando por um(a) Frontend Engineer para nos ajudar a expandir e construir a AI da próxima geração para saúde emocional. Esta é uma chance de deixar sua marca em algo que afeta mais de 700 milhões de pessoas no mundo.

Estamos em um estágio de crescimento incrível e planejamos triplicar nosso mercado no próximo ano. Quer se juntar a nós e fazer algo bom para a humanidade?

## Local

Remoto

## Requisitos

**Se você for uma pessoa que:**
- Sabe trabalhar em equipe, e acredita que pessoas trabalhando em conjunto para entregar valor é mais importante do que processos ou frameworks (por mais que eles possam ajudar bastante)
- Não tem medo de trabalhar em ambientes dinâmicos, com mudanças constantes e incertezas de uma fase de crescimento da empresa
- Tem experiência trabalhando com times multidisciplinares para entender, documentar e desenvolver software para atender requisitos de vários stakeholders
- Tem um entendimento profundo de arquitetura de sistemas, estrutura de dados e algoritmos
- Trabalhou com Angular 2+
- Concorda com a frase ‘Typescript arrebenta’
- Conhece as últimas tendências e boas práticas no que diz respeito a estilizar aplicações
- Se importa com a aparência das coisas
- Testes são parte da sua zona de conforto
- Gosta de criar sistemas mais eficientes, escaláveis e estáveis
- É capaz de entregar código com nível de produção e gerenciar o ciclo de vida do sistema

**Será bem-vindo ao time, focando em:**
- Criar aplicações cliente para web, focando em alta performance, UI lindas & qualidade de código
- Desenhar, desenvolver e deployar de ponta a ponta pipelines de dados que atendam a requisitos de negócio
- Colaborar com outros(as) da área de tech, produto e design para identificar e resolver problemas desafiantes e criar uma experiência incrível para usuários no mundo inteiro

**O que encontrará aqui:**
- Acesso grátis a terapias, coachings e outras ferramentas de auto desenvolvimento
- Time de liderança experiente
- Ambiente casual (contanto que você vista roupas, na maioria dos dias, está tudo bem)
- Horário flexível, a sério…
- Pequenos times com alta produtividade
- Slack, Slack em todo lugar
- Ideias arrojadas são extremamente valorizadas
- Títulos não significam muito, você é respeitado pelos resultados produzidos
- Colaboração, colaboração, colaboração

## Nossa Stack
- Node.js
- Angular
- Typescript
- AWS
- Firebase
- Tailwind

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para israel+vagas@zenklub.com com seu CV anexado - enviar no assunto: Vaga Fronend Zenklub

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
