### ISSUE TITLE
[São Paulo] JavaScript na EVOLUTION IT

### ISSUE THREAD

**Issue by MarinaEvolutionIT** [frontendbr/vagas#469]
## Descrição da vaga

Profissional full stack JavaScript com foco Frontend/Híbrido/Web/Mobile para atuação em Fábrica de Desenvolvimento (Perfis Pleno e Sênior).

## Local

Barra Funda, com possíveis visitas a clientes (Próximo ao metrô)
Escritório

#### Diferenciais

A Evolution IT oferece oportunidades de desenvolvimento e crescimento conforme as conquistas e sucesso de seus profissionais.

## Requisitos

•	Excelente raciocínio lógico e lógica de programação 
•	Disciplina, qualidade, organização e pragmatismo
•	Domínio da linguagem Javascript e seu ecossistema:
•	Containers: PhoneGap, Cordova, Ionic
•	Frameworks Javascript tais como Angular.js, Jquery, Bootstrap, React
•	HTML 5, CSS 3
•	MVC
•	Webstorage, off-line apps e SQLite
•	Serviços REST, OData, JSON, SOAP, XML.
•	Prática com planilhas Excel.
•	Flexibilidade e habilidade para trabalho em equipe e relacionamento com times multidisciplinares.
•	Habilidade com levantamentos e desenho de soluções.
•	Habilidade com prototipação de aplicações com base em frameworks.
•	Background em plataformas de serviços como Java e .Net são diferenciais.

•	Inglês
•	Leitura – imprescindível
•	Conversação – desejável

**Diferenciais:**

•	SAP Fiori
•	oAuth 2.0
•	Node.JS
•	Frameworks OpenUI5 ou SAPUI5
•	Experiência com aplicações híbridas e off-line
•	Background em soluções SAP, incluindo SAP Gateway e ABAP são diferenciais importantes

## Contratação

PJ por prazo indeterminado

## Como se candidatar

Enviar CV para marina.duarte@evolutionit.com.br com disponibilidade de início e pretensão PJ

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by MarinaEvolutionIT** [comment]
Está sim!!!

 

-- 
Marina


http://www.evolutionit.com.br/

Marina Duarte
Recursos Humanos
www.evolutionit.com.br <http://www.evolutionit.com.br/> 
Tel: +55 (19) 3115-3210 
 <mailto:marina.duarte@evolutionit.com.br> marina.duarte@evolutionit.com.br

cid:c12469820afcc88e25fad238e6034043@evolutionit.com.br

 

 

De: Felipe Fialho [mailto:notifications@github.com] 
Enviada em: terça-feira, 23 de janeiro de 2018 14:05
Para: frontendbr/vagas
Cc: MarinaEvolutionIT; Author
Assunto: Re: [frontendbr/vagas] [São Paulo] JavaScript na EVOLUTION IT (#469)

 

Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
