### ISSUE TITLE
[REMOTO] Front-end Developer na Foton

### ISSUE THREAD

**Issue by clarabsa1** [frontendbr/vagas#4693]
**Vaga para Front-End [REMOTO] na https://fotontech.io/!** 

Se você gosta de desafios, trabalhar em um ambiente dinâmico, estamos loucos para te conhecer!

**O que esperamos de você:**
- Queira mais que todo mundo!
- Entregue valor!
- Aproveite a vida mais que todo mundo!

**Requisitos para a vaga:**
- Experiência profissional com React de pelo menos 1 ano.
- Inglês avançado. 

**Diferenciais:** 
- Amar trabalhar com React.
- Conhecer sobre mitologia nórdica
- Gostar de fazer bagunça em call as 9:00 da manhã.

Interessados mandar CV (em inglês), Linkedin e Github no e-mail clara@fotontech.io.

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by esabrito** [comment]
Olá, Felipe, tudo bem?

Estou tentando cancelar o recebimento dos emails, mas não estou conseguindo.
Já cliquei várias vezes em cancelar inscrição, mas continuo recebendo.

Vi que você e o adm da pagina. Pode me ajudar?


Em seg., 19 de abr. de 2021 às 16:17, clarabsa1 ***@***.***>
escreveu:

**Comment by clarabsa1** [comment]
Oi Eduardo,

Como você está inscrito no repositório do frontendbr, nós da Foton não conseguimos cancelar o envio de emails feitos pela plataforma. Sendo assim, você precisa desabilitar as notificações do github relacionados ao frontendbr.
