### ISSUE TITLE
[Remoto] Front-end Developer Pleno/Sênior na @SaudeiD

### ISSUE THREAD

**Issue by givaldojr** [frontendbr/vagas#4694]
## Nossa empresa

Somos uma plataforma de tecnologia e saúde do Grupo Fleury que integra informações e soluções, tratando cada indivíduo como único. Usamos ciência de dados e inteligência artificial para reinventar o acesso à saúde no Brasil.

Em nosso aplicativo, é possível agendar e realizar teleconsultas, consultas presenciais, marcar e acessar resultados de exames diagnósticos, consultar prontuários eletrônicos e auto gerenciar problemas de saúde (doenças crônicas).

A saúde do paciente agora está à distância de um toque na tela. Pela primeira vez, ele será dono de todas as suas informações e as terá integradas em um único lugar. As empresas e operadoras, por sua vez, poderão aproveitar a inteligência de dados para prestar uma melhor assistência aos seus colaboradores e utilizar seus recursos financeiros com mais eficiência.

Quer saber mais sobre nós?
- https://exame.com/negocios/saude-id-o-novo-produto-do-fleury-para-quem-nao-tem-plano-de-saude/
- https://saudedigitalnews.com.br/16/09/2020/saude-id-buscar-criar-uma-marketplace-de-servicos-de-saude-no-brasil/
- https://revistamelhor.com.br/plataforma-saude-id-moderniza-a-saude-e-se-torna-o-primeiro-marketplace-no-brasil/

Saúde iD
Toda saúde é única.

## Como será seu dia à dia?

- Analisa e entende as necessidades do negócio
- Propõe soluções técnicas
- Estima a complexidade das demandas e planeja as entregas a cada interação
- Desenvolve e implementa as funcionalidades a cada interação
- Faz alinhamentos diários sobre o trabalho
- Atualiza constantemente o quadro com as tarefas "em andamento" e "concluídas"
- Realiza entregas com excelência e qualidade, considerando boas práticas e padrões de teste.
- Revisa e apresenta o que foi entregue
- Reavisa o código de outros desenvolvedores da equipe.
- Realiza a inspeção e adaptação do processo (Retrospectiva)

## Local

- Remoto ou Escritório, São Paulo - Pinheiros (Em virtude da pandemia estamos 100% remoto, não atuando com a opção escritório. Pós-pandemia será opcional).

## Requisitos:
- React 
- Next.Js 
- Typescript 
- GraphQL 
- Apollo 
- Git

## Diferenciais:
- Conhecer storybook.

## Benefícios

- 20 dias de férias (Remuneradas)

## Contratação

- PJ a combinar

## Como se candidatar

- Por favor envie um e-mail para givaldo.junior@saudeid.com.br com seu CV anexado - enviar no assunto: Vaga Frontend React

## Tempo médio de feedbacks

- Costumamos enviar feedbacks no mesmo dia.
- E-mail para contato em caso de não haver resposta: sysmap.kenneth@grupofleury.com.br

##  Alocação
- Remoto

##  Regime
- PJ

## Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
