### ISSUE TITLE
[REMOTE] Front-end Developer na Kobe (INTERNATIONAL PROJECT) 

### ISSUE THREAD

**Issue by fbttec** [frontendbr/vagas#4696]
## Nossa empresa

Exemplo: Aqui na Corporação ACME somos líderes em...

## Descrição da vaga

Kobe is looking for a Front-end Engineer to join the team! With your React and Javascript skills you will have the opportunity to build a SAAS platform for one of the largest heavy truck and bus manufactures in the world.

As a Kober, you will be part of a stimulating environment recognized as a Great Place to Work in 2018, 2019 and 2020. On the last 2 years, we were among the top 3 best small companies to work in RS and top 9 on the same ranking to work in Brazil.
 
*Kobe has a remote-first policy. No matter where you are, our culture reaches you!

## Local

Remote

## Requisitos

**Obrigatórios:**

- Proficiency in English;
- Experience of at least 2 years with React and Javascript;
- Familiarity with Next.js;
- Knowledge of different APIs.

**Diferenciais:**

- Having worked with data experience web applications;
- Experience in agile teams;
- Previous experience in international projects;
- Active presence on Github.

## Benefícios

- **Your Way Holidays:** 40 days of paid rest per year to enjoy as you wish
- **Health Insurance:** health plan, dental and life insurance 100% covered
- **Flexible Time:** start to work in the morning and stop whenever you want
- **Remote-First:** home office culture with dedicated activities for remote professionals
- **Kobe Growth:** individual development plan (PDI) for each Kober
- **Legendary Happy Hours:** periodic instagramable integration activities
- **International Immersion:** international culture with projects and offices outside the BR
- **The Right Tools:** Macbook Air and more for a Kobe-level work

## Contratação

PJ 

## Como se candidatar

Através do link: https://kobe.gupy.io/jobs/820658

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
