### ISSUE TITLE
[Remota] Pessoa Instrutora Front-end na Trybe

### ISSUE THREAD

**Issue by Danielabarrote** [frontendbr/vagas#4697]
## Nossa empresa

A Trybe é a uma escola de desenvolvimento web que se compromete integralmente com o sucesso das pessoas. Afinal, elas só começam a nos pagar quando tiverem uma remuneração mensal mínima. 

Trabalhamos com muito propósito e estamos procurando pessoas que, assim como nós, sonham em transformar o mundo por meio da educação. 

Nosso negócio é GENTE. Trabalhamos exclusivamente com gente talentosa, comprometida, curiosa, motivada e obcecada por qualidade e entrega. Para nós, cultura e valores são inegociáveis. Reconhecemos que todas as pessoas que estão conosco o fazem por escolha própria, pois teriam oportunidades em qualquer outro lugar. 

Fazemos o (im)possível para que cada Tryber tenha oportunidades, desafios, recompensas, se divirta e seja muito feliz. Sabemos que o caminho de construção é longo, que precisamos ter abertura e flexibilidade e que vamos aprender em conjunto todos os dias. Nada nunca está pronto!

## Descrição da vaga

Se você gosta de compartilhar conhecimentos e quer trabalhar com algo que impacte positivamente a vida das pessoas, venha trabalhar conosco! 💚
A área de instrução é responsável por cuidar do aprendizado técnico das nossas pessoas estudantes.
Temos oportunidades para pessoas de diferentes senioridades (Júnior/Pleno/Sênior), não deixe de se inscrever! 

## Local

Remoto

## Requisitos

**Obrigatórios:**

- Experiência com desenvolvimento em HTML, CSS e JavaScript;
- Experiência com Git & GitHub;
- Familiaridade com ambiente UNIX (Linux e/ou MacOS);
- Capacidade de resolver problemas utilizando lógica de programação;
- Preocupação genuína com a qualidade do código que escreve;
- Experiência profissional com desenvolvimento React;
- Experiência com Redux e/ou React Hooks e Context API;
- Noções de código assíncrono.

**Desejáveis:**

- Experiência profissional de, pelo menos, um ano com uma ou mais em outras linguagens de programação incluindo, mas não limitado a: JavaScript, Python, Ruby, Java, Swift;
- Capacidade de engajar pessoas através de uma comunicação objetiva e assertiva;
- Conhecimentos sobre testes unitários;

## Benefícios

- VA/VR
- Plano de saúde 
- Seguro de Vida
- Empresa cidadã (Licença maternidade e paternidade estendida) 
- 38 dias de férias

**Diferenciais:**
- Stock options 

## Contratação

CLT

## Como se candidatar

Se inscrever pelo link: (https://trybe.gupy.io/jobs/553353?jobBoardSource=gupy_public_page)

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
