### ISSUE TITLE
[Remoto | Rio de Janeiro] Front-end Developer na Zee.Dog

### ISSUE THREAD

**Issue by eduardobbrito** [frontendbr/vagas#4698]
## Nossa empresa

A Zee.Dog é líder no segmento de acessórios para Cachorros e Gatos, com presença internacional e lojas no Rio de Janeiro e Nova Iorque. Fundada em 2012, a empresa que começou com acessórios pet conta hoje com produtos na área de alimentação através da Zee.Dog Kitchen, roupas e acessórios para humanos com a Zee.Dog Human, além da Zee.Now, um app de entrega rápida com frete grátis para produtos de pet shop. Em 2020, o grupo Zee.Dog recebeu aporte financeiro através de uma rodada de investimentos, e tem entre seus objetivos para 2021 o aumento da cobertura da Zee.Now e a expansão do mix de produtos ofertados com opções como comida natural.

Com desenvolvimento totalmente "in-house", acreditamos no impacto da tecnologia e do design na criação de produtos, soluções e experiências. Nossos times são todos plurais, com pessoas de diversas trajetórias colaborando juntas pra criar produtos que amamos e desejamos ver no mercado. Temos no DNA da nossa cultura valores como trabalho em equipe, colaboração, atenção a prazos e detalhes e, acima de tudo, respeito total às diferenças e particularidades de cada um.

## Descrição da vaga

Estamos procurando pessoas para:

- Atuar em projetos que utilizam desde o básico do front-end a ferramentas como React e Next.
- Criar e implementar novas funcionalidades em produtos em produção e acessados por milhares de usuários diariamente.
- Criar e implementar novos produtos usando stacks modernas.
- Participar de squads multidisciplinares e interagir com times como design e back-end afim de oferecer a melhor experiência final aos usuários.

## Local

Remoto, com escritório no Rio de Janeiro, Botafogo (apenas pra quem puder e quiser, a vaga é totalmente remota).

## Requisitos

**Obrigatórios:**
- Scss
- React
- Git/Github

**Desejáveis:**
- NextJS
- Redux
- Redux-Saga
- Styled Components
- Testes com Cypress e/ou Jest

**Diferenciais:**
- Experiência em comércio virtual.
- Proatividade na busca por melhorias, novas ferramentas e interação em equipe.
- Familiaridade com ferramentas de análise de tráfego e performance como Google Analytics e Google Optimize, além do Google Tag Manager.

## Benefícios

- VR
- Plano de Saúde.

**Diferenciais:**
- Escritório sem dress code e aberto a animais (apenas pra quem puder e quiser, a vaga é totalmente remota).
- Acesso a cursos e plataformas de treinamento.
- Ambiente de troca de conhecimento e incentivo ao desenvolvimento pessoal.
- No Work Wednesdays - folgas quinzenais nas quartas feiras.

## Contratação

CLT

## Como se candidatar

Através do link na [Revelo](https://vagas.revelo.com.br/zee-dog-28c5942a-83ed-4ef5-9224-69ec241cbb74/desenvolvedor-front-end-pleno). Ou enviar email para eduardo.brito@zee-dog.com com Assunto "Vaga Front-End Zee.Dog".

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
