### ISSUE TITLE
[São Paulo] Front-end Developer na Nilo Saúde

### ISSUE THREAD

**Issue by rayanerocha07** [frontendbr/vagas#4699]
## Nossa empresa

A missão da Nilo é redesenhar como é feito o cuidado da população 50+ no Brasil, trazendo mais qualidade de vida e saúde.

Criamos uma experiência mágica para o paciente e usamos tecnologia e um time multidisciplinar de coordenação de cuidado para oferecer uma solução custo-efetiva à operadoras de saúde.

 Cuidamos de tudo da saúde do 50+ para ele viver bem. Nossa plataforma inteligente unifica todos os dados do paciente e ajuda o time de coordenação com sugestões de intervenções acionáveis para prevenção de internações e procedimentos desproporcionais, melhorando a saúde do paciente e evitando gastos desnecessários.

## Descrição da vaga

- Ajudar a entender problemas, analisar soluções, desenvolvê-las e testá-las;
- Mentorar outros desenvolvedores através de revisão de código;
I- mplementar novas funcionalidades e corrigir bugs;
- Ser independente e proativo, puxando ou refinando tarefas e mantendo o quadro de tarefas organizado;
- Colaborar com Gerentes de Produto, Engenheiros e profissionais de saúde para uma construção iterativa de produtos e serviços;
- Participar das cerimônias de gestão ágil;
- Monitorar o desempenho, disponibilidade, segurança e erros da solução enquanto ela estiver em produção;

## Local

Remoto.

## Requisitos

- 4+ anos de experiência trabalhando com práticas ágeis de desenvolvimento de software;
- Conhecimento de boas práticas como Clean Code, SOLID e Design Patterns;
- Experiência com JavaScript e React;
- Experiência com Typescript;
- Conhecimento em Firebase e familiaridade com ferramentas Google Cloud;

## Benefícios
- Vale Refeição
- Assistência Médica
- Assistência Odontológica
- PLR / Stock Options
- Política de Home Office

## Contratação

PJ a combinar.

## Como se candidatar

Através do formulário no site: https://bit.ly/32rZSQH

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
