### ISSUE TITLE
[São Paulo] Full Stack - Pleno - Javascript & Friends

### ISSUE THREAD

**Issue by rturk** [frontendbr/vagas#47]
## Descrição da vaga

Projeto de Aplicativo incluindo o FrontEnd + App + Backend. 
Todo o projeto criado com Javascript & friends (NodeJS, React, Relay). Suportado por um banco de dados em MongoDB

Vale reforçar que o escopo é para trabalhar em um único App, ou seja no dá para explorar bastante novas tecnologias e garantir um código de qualidade, o qual você irá se orgulhar e poderá acrescentar no seu portfolio

O time já tem developers e precisamos de ajuda! 
## Local

Escritório, São Paulo - Zona Sul
http://plug.co/bkln
## Benefícios
- Ambiente legal para trabalhar 
- Sem frescuras para horário de trabalho.
- Localizado na Plugg Coworking zona sul de SP
## Requisitos

**Obrigatórios:**
- Mestre em coding Javascript

**Desejáveis:**
- Experiência com Node
- Experiência com Mongodb 
- Alguma noção de Design (por favor!)

**Diferenciais:**
- Relay
- React Native
- Machine Learning
## Contratação

CLT 
## Nossa empresa

A Entria (https://www.entria.com.br) é uma empresa focada em Apps de alta complexidade. É liderada por um ex-Amazon.com com experiência no Brasil e no Exterior. Somos ambiciosos e estamos crescendo muito.
## Como se candidatar

Por favor envie um email para rh@entria.com.br com seu CV anexado - enviar no assunto: Eu sou o seu candidato(a) me contrate porque eu sou o cara!

**Comment by LFeh** [comment]
@rturk A vaga foi preenchida?

**Comment by eduardojmatos** [comment]
@rturk cara, sabe dizer se foi preenchida ou não? Só pra não deixarmos aqui sem ter a vaga :)

**Comment by rturk** [comment]
@eduardojmatos Estamos contratando sim!

**Comment by rturk** [comment]
@LFeh vc pode trocar os labels de `PJ` para `CLT`, grato.
