### ISSUE TITLE
[São Paulo] Hybrid Mobile App Developer na Solidaridad Network

### ISSUE THREAD

**Issue by caike08** [frontendbr/vagas#470]
## Descrição da vaga

For our Digital 3S development program we are looking for a talented MOBILE APP DEVELOPER that wishes to learn and grow with our young and passionate team in Sao Paulo. Being part of the IT team, you will be responsible for providing hybrid mobile solutions to millions of users worldwide, developing impactful products with customer focus, integrating mobile app in REST services, working in a team with different profiles (backend, frontend, infrastructure and research).

## Local

Office, São Paulo - Água Branca

## Benefícios

- Flexible working hours.
- Competitive third-sector salary.
- Other CLT benefits.

#### Diferenciais

- Flexible working hours.
- Third-sector environment.
- Work with a cause.
- May require occasional (inter)national travels.

## Requisitos

**Obrigatórios:**

- Bachelor degree in Information Systems, Software Engineering, Computer Science or related fields;
- Vast knowledge and experience with web development in JavaScript, jQuery, HTML 5 and CSS3;
- Proven track record of experience in the following frameworks: Ionic, Cordova, AngularJS, and Node.js;
- License to work in Brazil.

## Contratação

CLT

## Nossa empresa

With almost 50 years of experience, Solidaridad is a frontrunner in the area of sustainable economic development. We excel in facilitating the development of socially responsible, ecologically sound and profitable supply chains. We are an international market and solution-oriented civil society organization working through nine regional-expertise centers in almost 40 countries. We aspire to transform production practices in such a way that it provides fair and profitable livelihoods and business opportunities, guarantees decent working conditions and a fair living wage, and does not deplete the landscapes where people thrive, now and for generations to come.

Solidaridad South America is spearheading the transition of the Solidaridad Network towards becoming a data-driven organization. The development of digital systems and tools that benefit the organization and its target groups has become a rapidly growing area of work. Farmers in Africa, Asia and Latin America are increasingly using our solutions to improve their production systems be it growing cocoa, coffee, cotton, flowers, soy, sugarcane or oil palm.

## Como se candidatar

Kindly, send your application package containing CV, a link to your portfolio and motivation letter in English until **27 August 2017** to: horizonterural@solidaridadnetwork.org mentioning “Mobile App Developer” in the subject field.

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by caike08** [comment]
Não, ela já foi fechada.
