### ISSUE TITLE
[Remoto] Front-end Vue/Shopify Developer na Basico&Co

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#4701]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url https://coodesh.com com o pop-up personalizado de candidatura. :wave:
<p>Buscamos <strong>Pessoas Desenvolvedoras Frontend Shopity</strong> para atuar 100% remoto na Basico&amp;Co.&nbsp;</p>

## Basico&Co: 
 <p>Nosso grupo é formado por três das principais marcas do país:</p>
<ul>
<li><a href="https://basicamente.com/" target="_blank">basicamente.</a> , uma one stop shopping de básicos com qualidade e o melhor custo beneficio, fundada em 2020, para toda a família</li>
<li><a href="https://www.basico.com/" target="_blank">basico.com</a> , marca de lifestyle básico e uma das primeiras DNVBs do Brasil, fundada em 2013, com produtos básicos premium e inovadores.</li>
<li><a href="https://basico.ink/" target="_blank">basico.ink</a>, um hub d e personalização de vestuário, facilitando através da tecnologia marcas e empresas de criarem produtos incríveis.</li>
</ul>
</p>

 ## Habilidades: 
 - HTML 5 
- Javascript 
- Ruby 
- Shopify 
- Vue.js 
- GIT 
- CSS 3
## Local: 
 100% Remoto
## Requisitos: 
 - Conhecimentos ou experiência em desenvolvimento front-end 
- Experiência em desenvolvimento Shopify 
- Desejável conhecimentos em front-end vue.js 
- Habituado com Git 
- Habituado com trabalho remoto, times ágeis e scrum 
- Fluente em HTML5 e CSS3

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Shopify Developer na Basico&Co](https://coodesh.com/vagas/frontend-developer-101539?origin=github&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção <b>Pedir Feedback</b> entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa <b>Recruiter</b> responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Nível
Pleno
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
