### ISSUE TITLE
[Belo Horizonte] Analista de Sistemas (PO) na Empresa não Informado

### ISSUE THREAD

**Issue by NerdProgramador-com-br** [frontendbr/vagas#4702]
## Descrição da vaga 
Localização: Belo Horizonte/MG

  

Um pouco sobre a oportunidade:

\- Garantir o desenvolvimento de sistemas complexos mediante supervisão técnica do time desenvolvimento, visando garantir as entregas acordadas;

\-Definir soluções técnicas e funcionais para as necessidades e oportunidades identificadas, assim como elaborar documentações pertinentes e realizar modelagem de dados; visando a contribuição com as metas das áreas que atende e da coordenação em que está inserido;

\- Responsável por realizar planejamentos e entregas, conduzindo iniciativas da Squad em que atua e iniciativas cross, além de participar de projetos de qualquer porte;

  

O que você precisa saber:

Formação: Superior completo (Sistemas de Informação / Ciência da Computação).

Experiência sólida na função.

  

Regime de Contratação: CLT

  

Benefícios: Vale refeição; Vale alimentação ; Vale transporte; Seguro de vida - cobertura completa; Plano de saúde - Unimed Pleno; Plano odontológico; Plano aeromédico; PPR.
## Local 
Belo Horizonte/Minas Gerais 
## Como se candidatar 
Accesse a [Vaga de Analista de Sistemas (PO)](https://nerdprogramador.com.br/empresa-no-informado-analista-de-sistemas-po/dabb0d8e-52b8-4579-8c79-ba44a0d7fc90?utm_source=github) para mais informações. 
## Labels 
* Alocado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
