### ISSUE TITLE
[São Paulo] Full Stack Developer na HOOBOX

### ISSUE THREAD

**Issue by gusmana** [frontendbr/vagas#4703]
## Descrição da vaga

Somos uma empresa que utiliza a Inteligência Artificial e Visão Computacional para criar sistemas incríveis nas áreas da saúde, segurança, transporte e varejo. Acreditamos que podemos aproveitar as melhores habilidades de uma pessoa para compensar suas limitações.
Na Hoobox você vai trabalhar com times multidisciplinares. Vai ter o desafio de desenvolver produtos envolvendo tecnologia de reconhecimento facial em produtos exclusivos,utilizando tools novas. Pode ser que surjam demandas de última hora (nesses momentos você tem que ser proativo e multitasking).

## Local

Remoto ou Escritório em São Paulo - Vila Mariana

## Benefícios

- Flash Benefícios (distribua a verba de benefício como for melhor para você).
 
#### Diferenciais
- Time que te dá o suporte necessário para a realização das tarefas; 
- Happy hour (online durante a pandemia);
- Estrutura moderna em nosso escritório;
- Te damos o tempo necessário para aprender o que você precisar! 

## Requisitos

**Obrigatórios:**
- Conhecimentos sólidos nas linguagens JS (ES6), Python, SQL, Bash / Shell Script;
- Conhecimento sólido em Express (Node), Typescript;
- Conhecimento sólido em React, CSS;
- Estar familiarizado com ferramentas de trabalho em equipe como VCS (Git), CI, Testing;
- Experiência com sistemas Unix / Linux;
- Experiência de +3 anos na função (em caso de inscrição para a vaga de pleno)

**Desejáveis:**

- Conhecimentos de MongoDB, MySQL e Docker;
- Experiência com API e AWS;
-  Boa relação interpessoal.

## Contratação

PJ a combinar

## Nossa empresa

A Hoobox é uma startup que surgiu na UNICAMP em 2016. Desde então, estabelecemos parcerias com clientes e investidores importantes, como o Hospital Albert Einstein, Samsung, Intel e outros. 

## Como se candidatar

Por favor envie um email para vagas@hoobox.one com seu CV anexado - enviar no assunto "Vaga Full Stack Junior" ou "Vaga Full Stack Pleno" de acordo com seu nível. 

## Labels

- 🏢 Flexível
- 🏢 Presencial
- 🏢 Remoto
- 👦 Júnior
- 👨 Pleno
- ⚖️ PJ

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
