### ISSUE TITLE
[REMOTO] Senior Front-end Developer na ARBEIT

### ISSUE THREAD

**Issue by BarbaraEv0lu1r** [frontendbr/vagas#4705]
NOSSA EMPRESA

From New York, Arbeit Software is a platform dedicated to helping agents call with confidence.
Today, Arbeit is growing fast and finding new ways to support a healthy, compliant, and productive collections industry including TCPA-compliance solutions.

DESCRIÇÃO DA VAGA

Estamos à procura de um Desenvolvedor Front-End Sênior para construir e implementar interfaces de usuário atraentes e funcionais, com usabilidade aprimorada e foco na experiência do usuário. Você trabalhará com outros Designers, Desenvolvedores, Gerentes de Produto e Scrum Masters ao longo do ciclo de vida de desenvolvimento de software.

Responsabilidades

Atuar em equipe com desenvolvedores e designers de IU para implementar o front-end
Produzir código limpo e eficiente com base nas especificações
Auxiliar na criação de especificações
Resolver problemas, depurar e atualizar o código existente
Recomendar e executar melhorias
Criar documentação técnica para referência e relatórios
Criar e colaborar em novos padrões de desenvolvimento baseados em boas práticas
Apoiar a equipe compartilhando conhecimento e promovendo revisões técnicas

REQUISITOS

Obrigatórios:

5+ anos como desenvolvedor front-end
Inglês avançado
Familiaridade com metodologias de desenvolvimento Ágil
Experiência com design e desenvolvimento de software em um ambiente orientado a testes
Conhecimento de linguagens de codificação e frameworks / sistemas (por exemplo, React, JavaScript, Typescript )

Diferencial:
Conhecimento em C#

BENEFÍCIOS
Seguro saúde e odontológico sem desconto;
Participação nos lucros paga em dólar, anual 
Carga horária reduzia - 33 horas semanais

CONTRATAÇÃO
CLT

Como se candidatar

Por favor envie um email para barbara.borges@evoluirdesenvolvimento.com.br com seu CV anexado - enviar no assunto: Vaga Arbeit ou me chame no linkedin https://www.linkedin.com/in/b%C3%A1rbara-vieira-borges-238b3323/

Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.
E-mail para contato em caso de não haver resposta: barbara.borges@evoluirdesenvolvimento.com.br

Alocação
Remoto

Nível
Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
