### ISSUE TITLE
São Paulo -  Front-end Developer Vue.JS na Spread Tecnologia

### ISSUE THREAD

**Issue by milenavieira554** [frontendbr/vagas#4706]
> Vaga Remota 

## Descrição da vaga

🔺 Experiência em Node.js
🔺 Desenvolvimento Web com FrontEnd em VueJS ou AngularJS
🔺 Diferencial ter conhecimento em Reac Native, Flutter, Kotlin

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com Vue.JS
- Experiência com NodeJS

**Diferenciais:**
- Ter conhecimento em React, Flutter ou Kotlin 

## Benefícios

- Convênios com Academias
- Vale Transporte conforme necessidade
- Vale Refeição ou Alimentação
- Assistência Médica
- Assistência Odontológica
- Seguro de Vida
- Auxílio home-office

**Diferenciais:**
- Horário Flexível

## Contratação

- CLT

## Como se candidatar

Por favor envie um e-mail para milena.vieira@spread.com.br com seu CV anexado - enviar no assunto: Vaga VueJS

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
