### ISSUE TITLE
Home Office - Desenvolvedor Full Stack Sênior – Angular - K2 Solutions

### ISSUE THREAD

**Issue by fbis42** [frontendbr/vagas#4707]
Requisitos:
– Angular Avançado;
– Java/JavaScript/Typescript ;
– Conhecimento em testes (unitários/integração/comportamento);
– Conhecimento em Cloud Computing (lambda, RDS, S3, EC2);
– Consumo de APIs REST;
– Inglês fluente/avançado para leitura e escrita (obrigatório)

Contratação PJ e trabalho home-office
Skills principais: Angular, Cloud, Java, Javascript, REST, testes, typescript

Interessados, encaminhar currículo atualizado com valor pretendido e disponibilidade para o e-mail:  rh@k2solutions.com.br

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
