### ISSUE TITLE
[Remoto] Senior Mobile Developer na Conta Simples

### ISSUE THREAD

**Issue by brunno-dev** [frontendbr/vagas#4709]
`[São Paulo] Sênior Mobile Developer na Conta Simples`

> Vaga Remota durante e depois da pandemia

## Nossa empresa

A Conta Simples é uma das scale-ups que mais se destaca no cenário de fintechs do país. Com duas rodadas de investimento e passagem pela maior aceleradora do mundo, a Y Combinator, está na lista das 100 Startups to Watch e entre as 50 Startups que Mudam o Brasil. Estamos crescendo exponencialmente e buscamos pessoas colaborativas, questionadoras, curiosas e que queiram crescer conosco.

Venha para a Conta Simples!!

## Descrição da vaga

- Contribuir com o time na implementação de boas práticas de desenvolvimento e code design
- Definir e implementar a melhor arquitetura para novos projetos e melhorias nos projetos atuais
- Colaborar com a melhoria contínua dos nossos processos de desenvolvimento, bem como na melhoraria da nossa arquitetura nas aplicações web
- Colaborar com a execução e sugerir melhorias nos nossos processos ágeis

## Local

Remoto ou Híbrido (pós pandemia), você escolhe. Nosso escritório fica em São Paulo (Vila Olímpia) e toda empresa está em home office até junho/21.

## Requisitos

**Obrigatórios:**
- 4 anos de experiência com Javascript
- 4 anos de experiência com React Native
- Já ter trabalhado com algum Framework/Library de teste como Jest, Testing Library, Jasmine, etc
- Sólidos conhecimentos de Git

**Desejáveis:**
- Conhecimentos em Typescript

**Diferenciais:**
- Conhecimentos em Typescript

## Benefícios

- Plano de saúde (sem custos)
- Seguro de vida
- Benefício flexível de R$ 500 reais (pode comprar o que quiser em estabelecimento físico/online)
- Auxílio creche

## Contratação

PJ

## Como se candidatar

Por favor envie um e-mail para vagas@contasimples.com com seu CV anexado - enviar no assunto: Vaga Mobile Sênior

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: vagas@contasimples.com

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
