### ISSUE TITLE
[Campinas] Front-End Developer Júnior na Assertiva

### ISSUE THREAD

**Issue by henriquejensen** [frontendbr/vagas#471]
## Descrição da vaga

Uma pessoa apaixonada por tecnologia e que esteja em busca de novos desafios. Ela será responsável pelo desenvolvimento do front-end de diversos produtos e irá consumir serviços via REST. O nosso diferencial, é que aqui você participará das reuniões de concepção dos produtos, atuando assim de forma direta na melhoria dos produtos.

## Local

Av. João Erbolato, 364, Jardim Chapadão - Castelo -  Campinas

## Requisitos

**Obrigatórios:**
- Conhecimento em HTML5 e CSS3;
- Conhecimento em JavaScript.

**Desejáveis:**
- Conhecimento em algum framework JavaScript (React, Angular, Vue.JS, etc);
- Conhecimento em REST e integração via APIs;
- Conhecimento em UX;
- Conhecimento em UI.

## Contratação

CLT

## Nossa empresa

A Assertiva é uma empresa que desenvolve e integra tecnologias para impulsionar negócios mediante o uso inteligente dos dados.
Assertiva:
Site: http://www.assertivasolucoes.com.br/
Facebook: https://www.facebook.com/assertivainformacoes/
LinkedIn: https://www.linkedin.com/company-beta/22323349/

Castelo Creative Space:
Site: http://castelocreativespace.com.br/
Facebook: https://www.facebook.com/castelocreativespace
LinkedIn: https://www.linkedin.com/company-beta/21610290/

Venha fazer parte da nossa transformação digital!

## Como se candidatar

Ficou interessado? Envie o seu currículo para:

talentoti@assertivasolucoes.com.br

**Comment by jonatasbueno** [comment]
Muito eu essa vaga

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by henriquejensen** [comment]
fechado
