### ISSUE TITLE
[Remoto ou Maringá/PR] Front-end Developer React na DevApi

### ISSUE THREAD

**Issue by willhoffmann** [frontendbr/vagas#4710]
## Nossa empresa

Somo uma plataforma de automação para negócios.

Nosso objetivo é revolucionar a experiência de integração, através de API seguras e automações inteligentes.

## Descrição da vaga

Na DevApi, você poderá participar das decisões de evolução tecnológica e de todo o processo de desenvolvimento, desde a análise de requisitos até a disponibilização das funcionalidades aos clientes. Como time, temos a missão de evoluir nossos produtos, tornando nossas soluções ainda mais robustas e escaláveis.

Se você é um profissional com espírito de equipe, preocupado com a qualidade do código que desenvolve, gosta de desafios e de estar envolvido na criação de produtos que fazem a diferença, você vai adorar trabalhar conosco!

## Local

Remoto ou em nosso escritório [MARINGÁ-PR]

## Requisitos

**Obrigatórios:**

- Possuir domínio de React;
- Possuir sólidos conhecimentos em Typescript e Javascript;
- Possuir sólidos conhecimentos sobre HTML5 e CSS3;
- Conhecimento em Responsive Design;
- Metodologias Ágeis: Scrum e Jira.

**Desejáveis:**

- Testes unitários e automatizados (Jest, Cypress, etc...);
- CSS in JS (styled components, etc...);
- Experiência com Amazon AWS (S3 & Cloudfront);
- Experiência com aplicação de um design system em um produto.

**Diferenciais:**

- Conhecimento com estrutura em microFrontend;
- Implementação de processo de integração contínua e entrega contínua.

## Benefícios

- Plano de saúde;
- Vale alimentação.

## Contratação

CLT

## Como se candidatar

Por favor envie um email para mariana.ganassin@devapi.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Developer React.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 30 dias após cada processo.
E-mail para contato em caso de não haver resposta: mariana.ganassin@devapi.com.br.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
