### ISSUE TITLE
[Remoto] Front-end Developer na GamerSafer

### ISSUE THREAD

**Issue by paezao** [frontendbr/vagas#4711]
## Nossa empresa

A GamerSafer é uma empresa de identity management usando biometria facial. Com nossas soluções, diminuímos toxicidade, bullying, smurfing, cheating, racismo, etc. Estamos aqui para tornar as comunidades de gamers mais seguras e divertidas para todos. Bora causar impacto positivo?? 

## Descrição da vaga

Nosso projeto é todo em typescript, sendo que o backend usa o máximo possível dos AWS Managed Services, ou seja, totalmente serverless. No caso do frontend, temos projetos em React Native e React e estamos num momento de reescrever os projetos, mudando inclusive vários fluxos do produto. É uma boa oportunidade para começar um projeto do zero utilizando as melhores práticas do mercado (Storybook, Atomic Design, TDD, etc).

## Local

A empresa fica em San Jose, California. Então o trabalho é 100% Remoto, e continuará assim pois somos uma empresa global.

## Requisitos

**Obrigatórios:**
- Pelo menos 2 anos de experiência com React
- Inglês
- Gamer!

**Desejáveis:**
- Experiência com React Native
- Experiência com Typescript

**Diferenciais:**
- Contribuições em Projetos Open Source

## Benefícios

- Férias Remuneradas (2 semanas a cada 6 meses)

**Diferenciais:**
- Empresa early stage, muito potencial de crescimento
- Empresa global, possibilidade de interação com pessoas do mundo todo, com diferentes culturas e idiomas
- Stack moderno, vai trabalhar com as técnicas mais modernas de desenvolvimento de software
- Estamos no mercado de games! É muito divertido!
- Pessoas super descontraídas e com muita leveza

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para marcelo@gamersafer.com com seu CV anexado - enviar no assunto: Vaga Frontend Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
