### ISSUE TITLE
São Paulo|SP, Desenvolvedor Front End - K2 Solutions

### ISSUE THREAD

**Issue by fbis42** [frontendbr/vagas#4712]
Requisitos:
Experiência mínima de 2 anos.
Familiarizado com JavaScript, ES6, HTML e CSS.
Sólida experiência na construção de aplicações PHP/Laravel.
Experiência anterior com bancos de dados SQL é uma vantagem.
Conhecimento em AWS e Google Cloud é um diferencial.

Conhecimentos:
• PHP/Laravel
• React
• SQL
• Git e Github
• Linux
• Java

Contratação: CLT
Benefícios: VR + VT

Trabalho: Home-Office (enquanto pandemia)
Local:  Zona Leste de São Paulo.

Skills principais: CSS, HTML, Javascript, laravel, PHP

**_Interessados, encaminhar currículo atualizado com pretensão salarial e disponibilidade para o e-mail:  rh@k2solutions.com.br_**

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
