### ISSUE TITLE
[Remoto] Front-end Developer na Doublelab

### ISSUE THREAD

**Issue by mateusnb** [frontendbr/vagas#4713]
A Doublelab está procurando um desenvolvedor FullStack para um projeto pontual

Se você é desenvolvedor nativo Android com experiência mande um e-mail com seu linkedin e portfoio com alguns projetos que ja realizou para mateusnb@gmail.com ou contato por whatsapp 11 98809 7669

Além da experiência comprovada em desenvolvimento Android Nativo Java/Kotlin os seguintes requisitos também são importantes:

- Conhecimento em desenvolvimento end to end AWS, Git, Playstore
- Possuir portifolio comprovado
- Ter indicacao de projetos e pessoas é um plus.

Enviar para mateusnb@gmail.com e/ou whatsapp 11 98809 7669

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
