### ISSUE TITLE
[Remoto] Frontend Angular Developer Pleno no DB1 Group

### ISSUE THREAD

**Issue by alissongusmao** [frontendbr/vagas#4715]
## Nossa empresa

Somos um grupo de empresas de tecnologia nascido em Maringá, interior do Paraná, com 20 anos de experiência em desenvolvimento de software voltado para soluções de grandes empresas. Atuamos em diversas frentes de mercado: com produtos ([ANYMARKET](https://anymarket.com.br/), [CONSIGNET](https://www.consignet.com.br/), [EIVE](https://eive.com.br/)) e também com serviços e projetos personalizados da nossa Fábrica de Software - [DB1 Global Software](https://www.db1.com.br/) . E estamos em expansão !!!🚀🚀🚀

Somos colaboradores distribuídos em todo o Brasil e na Argentina, com escritório em Maringá / PR, Campo Grande / MS e Presidente Prudente / SP e atuamos também de forma remota (home office) desde 2017. Estamos há 12 anos consecutivos entre as Melhores Empresas para Trabalhar, segundo o GPTW, com reconhecimento pela instituição em 2020 como empresa referência na prática de escutar o colaborador. Em 2121, fomos reconhecidos, pela segunda vez consecutiva, pela Financial Times como uma das [Empresas que Mais Crescem das Américas](https://www.ft.com/content/ac773779-98ba-442d-a1f2-a14f1a67ddfe). 

Somos movido por desafios diários, trabalhamos com o conceito de Melhoria Continua. Entendemos que tudo pode ser melhorado, mesmo que ainda não saibamos como! Todos (as) aqui temos autonomia e voz para dar feedbacks, testar coisas novas e ser parte dessa mudança. Aqui aprendemos uns com os outros diariamente, com um forte senso de equipe. DB1 é pra quem não quer ser mais um!

## Descrição da vaga

Buscamos um(a) profissional apaixonado(a) por tecnologia, proativo, comprometido em entregar software com qualidade, contribuindo com conhecimentos e experiências . Atuará no desenvolvimento Frontend, utilizando AngularJS e Angular 2+

**Suas principais atividades serão:**

- Atuar na customização e evolução de um sistema no segmento de farmácias.
- Desenvolver com foco em frontend, utilizando AngularJS e Angular 2+
- Trabalhar em conjunto com equipe de desenvolvimento backend Java. 

## Local

Remoto ou Escritório, Paraná, Maringá.

## Requisitos

**Obrigatórios:**

- Experiência em frontend
- HTML
- Javascript
- Css
- Angular 2 +
- Angularjs
- Restful API
- Conceitos de componentização
- Boas praticas de desenvolvimento.

**Desejáveis:**

- Conhecimento em Testes Unitários, utilizando Jasmine.
 
**Diferenciais:**

- Ter conhecimento em Java.

## Benefícios

- Vale alimentação e/ou vale refeição;
- Plano de Saúde e plano odontológico;
- Uma trilha de carreira com Plano de Desenvolvimento Individual (PDI) e feedbacks constantes para te ajudar na sua evolução profissional;
- Horários flexíveis!;
- Convênio com farmácia Droga Raia, com desconto para colaboradores;
- Pra celebrar seu aniversário, é possível sair um pouco mais cedo no dia para comemorar com quem quiser e organizar o que for necessário 🥳
- Aqui você terá a oportunidade de aprender coisas novas - seja no dia-a-dia, em um Programa de Mentoria ou em um desafio do nosso programa de gamificação Mestre dos Códigos.
- Home office como modelo de contratação. Atuamos com essa possibilidade desde 2017. Além de viabilizar, nossos colaboradores que não são 100% Home Office, trabalhar de casa em algum dia da semana quando necessário.

## Contratação

CLT

## Como se candidatar

[Clique aqui para se inscrever na oportunidade](https://vagasdb1.recruiterbox.com/jobs/fk0uvze?source=Github) , envie seus dados e nossa equipe de recrutamento e seleção entrará em contato.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: talentos@db1.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
