### ISSUE TITLE
[Remoto] Pessoa Desenvolvedora de Software Sênior Frontend @ VAGAS.com

### ISSUE THREAD

**Issue by reginaldojunior** [frontendbr/vagas#4719]
### Conheça a VAGAS.com

Somos uma comunidade que tem o propósito de contribuir para um mundo em que empresas escolhem melhor as pessoas e pessoas escolhem melhor as empresas.

### Empresa horizontal: o modelo de gestão que transforma

Nós temos nossa própria cultura e jeito de trabalhar. Somos uma empresa de tecnologia radicalmente horizontal, ou seja, sem chefes, onde mais de 140 pessoas trabalham diariamente por um propósito.

## Detalhes da Vaga

Nossos colaboradores estão trabalhando em regime de home office e permanecerão assim por tempo indeterminado. Por isso, os processos seletivos são 100% remotos.

A equipe de Frontend tem como missão entregar um sistema com mais acessibilidade e melhor usabilidade aos usuários, proporcionando uma boa experiência e auxiliando na realização do propósito da VAGAS: Contribuir para um mundo em que pessoas e trabalho/empresas se escolham mutuamente cada vez melhor.

O seu desafio dentro do time será participar de todo o ciclo de vida das interfaces e aplicações tendo como foco: usabilidade, escalabilidade e manutenibilidade. 

## Local

Remoto

### Como será seu dia a dia

- Desenvolverá interfaces responsivas e acessíveis utilizando React
- Garantirá a melhor usabilidade e fidelidade do layout em parceria com Designers e UXs, entregando valor para o usuário
- Definirá em conjunto com back-end os contratos de APIs
- Participará de equipes multifuncionais e interdisciplinares, interagindo com profissionais de outras áreas da empresa
- Participará de todo o ciclo de desenvolvimento do produto, passando, inclusive, pelas fases de concepção e análise de mercado
- Fará a criação e evolução à Arquitetura de projetos
- Fará a gestão compartilhada de sua equipe e do negócio
- Atuará tanto com sistemas legados como com novas tecnologias
- Compartilhará conhecimento e apoiará no desenvolvimento dos seus pares, fazendo mentoria dos membros mais juniores da equipe 

### O que buscamos em você

- Experiência comprovada com aplicações frontend em projetos complexos de mercado
- Experiência sólida em HTML, CSS e Javascript
- Sólidos conhecimentos de React
- Boas práticas de desenvolvimento, com foco em qualidade, melhorias de performance, acessibilidade e escalabilidade;
- Vivência em projetos que implementem acessibilidade de forma ativa
- Experiência com protocolo HTTP e APIs REST
- Analisar e implementar interfaces de produto considerando UI e UX
- Experiência com testes automatizados de unidade e de integração
- Bom relacionamento interpessoal e proatividade
- Experiência com mentoria de membros da equipe

### Plus

- Conhecimentos em React ou Vue
- Experiência com diferentes padrões de projeto
- Experiência com reutilização de recursos (componentização)
- Experiência com documentação
- Experiência em TDD
- Vivência com metodologias ágeis

## Benefícios

- Assistência médica
- Assistência odontológica
- Auxílio-academia
- Auxílio-creche
- Auxílio-desenvolvimento
- Auxílio-estacionamento
- Seguro de vida
- Vale-refeição
- Vale-transporte
- Auxílio-fretado
- Café da manhã
- Cesta de natal
- Consignado
- Ginástica laboral
- Massoterapia
- Home office 

## Contratação

CLT

## Como se candidatar

Se inscreva através do nosso site:

 - https://trabalheconosco.vagas.com.br/vagas/oportunidade/pessoa-engenheira-de-software-senior-frontend/2177631

#### Alocação
- Remoto

#### Regime
- CLT
- 
#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
