### ISSUE TITLE
[Remoto] Front-end Developer na NuVidio < by Coodesh />

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#4724]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url https://coodesh.com com o pop-up personalizado de candidatura. :wave:
<p>Dia a dia:</p>
<ul>
<li>Aplicar e encorajar boas práticas de desenvolvimento;</li>
<li>Desenvolver códigos simples, eficazes, escaláveis, legíveis e de fácil manutenção, utilizando as melhores práticas de desenvolvimento de software;</li>
<li>Atuar em conjunto com o time, comprometendo-se com os objetivos do time e trabalhando em harmonia com todos;&nbsp;</li>
<li>Questionar e inovar buscando sempre as melhores alternativas alinhadas a necessidade da empresa.</li>
</ul>
<p>Capacidades necessárias:</p>
<ul>
<li>Experiência em projetar, construir e gerenciar soluções HTML, CSS e JavaScript;</li>
<li>Conhecimentos sólidos de JavaScript e/ou TypeScript;</li>
<li>Domínio de ao menos um framework como Angular, React ou semelhante;</li>
<li>Conhecimento de Git.</li>
</ul>
<p></p>

## NuVidio: 
 <p>As videochamadas já vinham apresentando grande crescimento e massificação do uso há alguns anos. Agora com a pandemia e o isolamento social tudo se acelerou, conversar por vídeo deixou de ser uma atividade corporativa e se tornou “mainstream”.&nbsp;</p>
<p>Com o mesmo impulso, o e-commerce se expande como nunca e está tomando o mercado das vendas físicas. Além disso, as pessoas, cada vez mais sozinhas, passaram a valorizar mais as interações humanas.</p><a href='https://coodesh.com/empresas/nuvidio'>Veja mais no site</a>

 ## Habilidades: 
 - HTML 5 
- Javascript 
- React.js 
- React Native 
- Typescript 
- GIT
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência em projetar, construir e gerenciar soluções HTML, CSS e JavaScript; 
- Conhecimentos sólidos de JavaScript e/ou TypeScript; 
- Domínio de ao menos um framework como Angular, React ou semelhante; 
- Conhecimento de Git.

## Benefícios: 
 - Horários Flexíveis 
- Totalmente home-office 
- Possibilidade de crescimento junto com a startup
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Front-end Developer na NuVidio](https://coodesh.com/vagas/frontend-developer-135324?origin=github&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção <b>Pedir Feedback</b> entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa <b>Recruiter</b> responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
