### ISSUE TITLE
[Curitiba] Fullsatck Developer @ SISAND

### ISSUE THREAD

**Issue by MariPsi** [frontendbr/vagas#4725]
## Nossa empresa

A SISAND desenvolve soluções para gestão de concessionárias, descomplicando o controle do negócio de ponta a ponta.
Fundada em 2005, a Sisand nasceu com a união de profissionais com experiência no ramo automotivo e amplo conhecimento na área de tecnologia da informação. Ao longo destes anos vem oferecendo ao mercado excelentes soluções de gestão para concessionárias de moto e carro.

## Descrição da vaga

- Planejar, analisar a implementar um sistema ERP
- Entender o negócio da Sisand
- Descrever as histórias
- Desenvolvimento do sistema
- Montagem de componentes
- Trabalhar dentro da etica e da metodoloia Scrum
- Ser colaborativo para o desenvolvimento de todos

## Local

[CURITIBA][PARANÁ][BRASIL]

## Requisitos

**Obrigatórios:**

- Front End  - HTML, CSS,  ASP.NET  - Angular 7
- Framework - Bootstrap
- Banco de dados - SQL Server 
- Back End - C#   
- Trabalhar dentro da etica e da metodoloia Scrum
- Ser colaborativo para o desenvolvimento de todos

**Desejáveis:**
Vontade de aprender, ter afinidade e curiosidade com as tecnologias da vaga, ser autodidata e ter tido alguma experiência com desenvolvimento e programação, colocado a mão no código e desenvolvido algum projeto com ele. 

**Diferenciais:**
- Perfil Analista - procurar entender 
- Visão Sistêmica - Visão do todo
- Honestidade
- Senso de urgência 
- Resolutivo
- Gostar de Programar de verdade
- Ensino médio completo ou superior em andamento

## Benefícios

- Plano de Saúde
- VR ou VA

## Contratação

- CLT - A partir de 2.5 mil

## Como se candidatar

Aplique para a vaga [por aqui](https://www.careers-page.com/novare-rh/job/W997RW) .

#### Alocação
- Escritório

#### Regime
- CLT

#### Nível
- Júnior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
