### ISSUE TITLE
[Brasil, Remoto] Chapter Lead @ Climatempo

### ISSUE THREAD

**Issue by feahorita** [frontendbr/vagas#4727]
Quer trabalhar na maior empresa privada de meteorologia do Hemisfério Sul ???

## Descrição da vaga

Estamos em busca desenvolvedor mobile ambicioso, cansado do comodismo e pronto para desafiar seus limites. As tech skills necessárias são React, NodeJS, APIs rest e GraphQL, Redux, Sagas, React Hooks, SQL/NoSQL e OOP.

## Nossa Empresa

Empresa 100% Online

A Climatempo Consultoria é a maior empresa brasileira de meteorologia, com papel fundamental na assistência estratégica de empresas afetadas por riscos climáticos. A excelência em prestação de serviço é voltada para 22 segmentos da economia, por meio de produtos e atendimento personalizados, com monitoramento de meteorologistas certificados pelo CREA. Desde 2019, a Climatempo uniu forças com a norueguesa StormGeo, líder global em inteligência meteorológica e soluções para suporte à decisão com escritórios em mais de 18 países. 

## Dia-a-Dia

* Liderar o Chapter de Backend em conjunto com os demais chapter leads 
* Desenvolver produtos modernos  
* Propor e projetar soluções inovadoras tanto para os problemas cotidianos quanto para as novas funcionalidades
* Participar do fluxo do projeto, desde a elaboração da arquitetura até a entrega em produção
* Dar manutenção em produtos legados 
* Participar de reuniões de alinhamento com o PO, time da TI, Climatempo e StormGeo

### Obrigatórios 

* Desejável graduação em computação ou ambientais e afins
* Experiência com React
* Experiência com SQL/NoSQL 
* Experiência com NodeJS, API
* Experiência com ferramentas de versionamento de código
* Habilidades interpessoais de escrita e de comunicação verbal
* Experiência com liderança de equipes
* Proatividade na busca de soluções e novas formas de desenvolvimento
* Facilidade em debugar e identificar problemas
* Excelente raciocínio lógico
* Ter trabalhado com metodologia ágil/scrum/kanban

### Diferenciais 

* Ter mestrado e doutorado em computação ou ambientais e afins
* Conhecimento com informações meteorológicas, geográficas, ou ambientais 
* Conhecimento com GraphQL, RabbitMQ e Cloud GCP

## Contratação 

* Contratação: PJ

## Benefícios

* Trabalho remoto
* Férias PJ
* Empresa consolidada com potencial global e mobilidade internacional

## Processo Seletivo 

Nosso processo seletivo consiste em quatro etapas sendo apenas a primeira eliminatória: 1) teste técnico; 2) análise comportamental; 3) teste comportamental; e 4) entrevista com Gestor e time. O tempo médio do processo é de 15-20 dias (inclusive teste técnico). Temos por política encaminhar um feedback construtivo e detalhado, além de esperamos que os candidatos aprendam e cresçam ao longo do processo.  

## Como se candidatar

Curtiu? Nós também queremos te conhecer!!! Envie seu currículo em https://forms.gle/wT1NPMx96a8VwiAk7. 

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- 🏢 Remoto
- 👨 Pleno
- ⚖️ PJ

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
