### ISSUE TITLE
[Remoto] Front-end Vue.js Developer na Coodesh

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#4728]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url https://coodesh.com com o pop-up personalizado de candidatura. :wave:
<p>Buscamos <strong>Pessoas Desenvolvedora Front-End Vue.js</strong> para trabalhar em <em><ins>squad </ins></em> 100% remoto.</p>
<p></p>
<p>Como funciona a <em><ins>escale.dev - Coodesh</ins></em> para DEVs:</p>
<ul>
<li>Candidatar-se</li>
<li>Responda ao scorecard de auto avaliação</li>
<li>Participe de uma entrevista de fit</li>
<li>Realize ao teste comportamental&nbsp;</li>
<li>Realize a validação Tech e Apresente ao Especialista Responsável</li>
<li>Onboarding de contrato online + início no projeto&nbsp;</li>
</ul>

## escale.dev (Coodesh): 
 <p>Trabalhe em squads 100% remoto em empresas do exterior ou no Brasil.<br></p>
<h6>Requisitos</h6>
<ul>
<li>CNPJ Ativo (consultar critérios durante o processo)</li>
<li>Ter disponibilidade entre 20 horas a 40 horas por semana para trabalho remoto</li>
<li>Equipamento próprio de trabalho (desktop ou laptop - min. 4GB RAM)</li>
<li>Conexão com internet (min. banda larga 10Mb/s)</li>
</ul>
<h6><br>Como Funciona a <em><ins>escale.dev</ins></em> Para DEVs</h6>
<ul>
<li>Escolha a área tech de atuação de acordo com a sua preferência e candidate-se</li>
<li>Responda ao scorecard de auto avaliação</li>
<li>Realize o Tech Challenge</li>
<li>Apresente o Tech Challenge</li>
<li>Realize a prova comportamental e participe de uma entrevista de fit&nbsp;</li>
<li>Contrato e Onboarding</li>
</ul>

<h6>Contratos</h6>
<ul>
<li>Part-Time (4 horas em sequência / dia) - 20 horas / semana</li>
<li>Part-Time (6 horas em sequência / dia) - 30 horas / semana</li>
<li>Full-Time (8 horas em sequência / dia) - 40 horas / semana</li>
</ul>
<p></p><a href='https://coodesh.com/empresas/coodesh-teams'>Veja mais no site</a>

 ## Habilidades: 
 - HTML 5 
- Javascript 
- Typescript 
- Vue.js 
- CSS 3 
- Nuxt.js 
- Sentry
## Local: 
 100% Remoto
## Requisitos: 
 - Conhecimentos ou experiências em projetos front-end usando Vue.js 
- Bom entendimento de Lean Startup 
- Ser habituado com metodologias ágeis 
- Escreva código bem projetado, testável e eficiente 
- Ser habituado no uso de Webpack e ESLint 
- Conhecimentos ou Experiências ou práticas em projetos de alta performance usando Nuxt.js ou Quasar

## Benefícios: 
 - 📡 100% remoto 
- 🕔 Horário flexível 
- 🎈 Day-off aniversário 
- 📚 Cursos, treinamentos e eventos 
- 📈 Plano de Desenvolvimento Individualizado e Plano de Carreira
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Vue.js Developer na escale.dev (Coodesh)](https://coodesh.com/vagas/frontend-vuejs-developer-parttime-212952?origin=github&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção <b>Pedir Feedback</b> entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa <b>Recruiter</b> responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Nível
Pleno
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
