### ISSUE TITLE
[Remoto] Front-end Angular Developer na Nkey < by Coodesh />

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#4729]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url https://coodesh.com com o pop-up personalizado de candidatura. :wave:
<p>Buscamos <strong><em><ins>Pessoas Desenvolvedoras Front-end ou Fullstack</ins></em></strong>.</p>
<p></p>
<p><strong>ATIVIDADES</strong></p>
<ul>
<li>Desenvolvimento de aplicações front-end SPA com Angular;</li>
<li>Participar ativamente na sugestão e preparação das melhores práticas / soluções    para o aplicativo que estiver desenvolvendo;</li>
<li>Capacidade de gerar um código limpo e de ter boas práticas de desenvolvimento;</li>
<li>Conhecimento em Design Patterns;</li>
</ul>
<p></p>
<p></p>

## Nkey: 
 <p><strong>QUEM SOMOS?</strong></p>
<p>A Nkey é uma empresa de co-criação de soluções digitais inteligentes para nossos clientes. Fundada em 2011, ajudamos nossos clientes a reduzirem custos e aumentarem receitas através de sua digitalização. Entregamos esse valor através da aplicação de tecnologia como meio para otimização de processos, melhoria de experiência e inovação para o negócio.</p><a href='https://coodesh.com/empresas/nkey'>Veja mais no site</a>

 ## Habilidades: 
 - Javascript 
- Typescript 
- Docker 
- Angular 2+ 
- GIT 
- Angular 8 
- Angular 9
## Local: 
 100% Remoto
## Requisitos: 
 - Front-end: Angular (v.5+); 
- Git; 
- Testes unitários com JavaScript; 
- Conhecimentos dos princípios SOLID 
- Inglês avançado/fluente; 
- Ter atuado em projetos ágeis;

## Benefícios: 
 - 100% remoto
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Front-end Angular Developer na Nkey](https://coodesh.com/vagas/frontendfullstack-angular-150341?origin=github&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção <b>Pedir Feedback</b> entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa <b>Recruiter</b> responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Nível
Pleno
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
