### ISSUE TITLE
[Goiás] Front-end Developer na ON GO Company

### ISSUE THREAD

**Issue by mateusschenato** [frontendbr/vagas#4730]
## Nossa empresa

Somos uma empresa de tecnologia que visa melhorar o transporte de cargas e negócios do Brasil com segurança e responsabilidade, a tecnologia está voltada para o desenvolvimento das atividade com foco em redução de custos do processo.

https://ongocargas.com.br

## Descrição da vaga

Nosso projeto é todo em typescript, sendo que o Backend é .NET Core usando serviços Microsoft. No caso do frontend, temos projetos em React Native, Angular e React e estamos em um momento de implementação de uma nova Interface para nossos usuários. É uma boa oportunidade para começar um projeto utilizando as melhores práticas do mercado (Storybook, TDD, etc).

## Local

Nossa empresa fica localizada em Rio Verde - Goiás, tendo opção de trabalhar Presencial ou 100% Remoto mesmo após pandemia.

## Requisitos

**Obrigatórios:**
- 1 ano de experiência com React
- Experiência com Typescript

**Desejáveis:**
- Experiências com Redux
- API Rest

**Diferenciais:**
- Projetos opensource
- Conhecimentos em C#
- Conhecimentos em .net core
- Experiência com React Native

## Contratação

PJ a combinar

## Diferenciais
- Empresa com muito potencial de crescimento
- Stack Moderno, vai trabalhar com as melhores práticas e tecnologias atuais do mercado
- Equipe descontraída, ambiente leve para se trabalhar

## Como se candidatar

Por favor envie um email para vagas@ongo.com.br com seu CV anexado - enviar no assunto: Vaga React

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

#### Alocação
- Remoto/Presencial

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
