### ISSUE TITLE
[São Paulo] Front-end Developer Angular SR  na BEYOND SOLUÇOES

### ISSUE THREAD

**Issue by Mariana9852** [frontendbr/vagas#4731]
[São Paulo] Front-end Developer  Angular SR na BEYOND SOLUÇOES 

> Vaga Remota durante a pandemia

## Nossa empresa

Já pensou em fazer parte de uma empresa que vai ALÉM de uma consultoria tradicional de outsourcing?
Nós da BEYOND estamos presentes nas principais organizações do mercado de investimentos e fintechs. Aqui, você irá atuar no maior Banco de Investimentos da América Latina, presente em 16 países, que preza por um time de alta qualidade e performance para solucionar grandes desafios. 

## Descrição da vaga

Desenvolvedor Front end Angular SR 

Habilidades Técnicas:

• Aplicações em Angular 2+
• Pré processadores SASS
• Foco em desenvolvimento Javascript e Typescript
• Versionamento com Git, GitFlow

Stack utilizada pelo time: AWS, Esteira de CI/CD, Bancos relacionais e não relacionais.

## Local

 Remoto ou Presencial Escritório, [São Paulo], [São Paulo], [Itaim bibi]

## Requisitos

**Obrigatórios:**
• Experiência em desenvolvimento de aplicaçõPI Res com Aest
• Conhecer técnica de teste unitário e desenvolvimento de templates mailmarketing e newsletter
• Domínio em HTML e esterilização de componentes com e sem uso de frameworks

**Diferenciais:**
- conhecimento com Mercado Financeiro e Portais de Internet

## Benefícios

- Beneficios 100% subsidiados pela BEYOND  
- Plano de saúde e odontológico Sul américa 
- Seguro de vida
- R$: 800,00 (podendo ser distribuído em VR ou VA)

## Contratação

CLT

## Como se candidatar

Por favor envie um email para mariana.lemos@imaginebeyond.com.br  com seu CV anexado - enviar no assunto: Vaga Front End Angular 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.
E-mail para contato em caso de não haver resposta: mariana.lemos@imaginebeyond.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível

- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
