### ISSUE TITLE
[Remoto] Desenvolvedor Python na It4us Cyber Security Company

### ISSUE THREAD

**Issue by NerdProgramador-com-br** [frontendbr/vagas#4732]
## Descrição da vaga 
A It4us é uma empresa de segurança cibernética que traz segurança e tecnologia de pequenos à grandes negócios corporativos. Com um histórico de sucesso na preparação e execução de projetos de TI e Ciber Segurança, com profissionalismo, qualidade e principalmente com a parceria com os principais fornecedores, nossa equipe já entregou mais de 800 projetos para clientes de todas as verticais. Fornecemos serviços de consultoria, desde a implementação de soluções complexas de infraestrutura até a criação de grandes SOCs de segurança cibernética. Temos uma base instalada de mais de 100 clientes, representando mais da metade dos serviços de SIEM para grandes empresas. Na IT4US, você trabalhará com talentos excepcionais, uma equipe extremamente técnica que está sempre disposta a compartilhar experiências e conhecimentos, além de ter acesso aos melhores fornecedores e soluções de segurança cibernética.

  

É necessário possuir experiência em Linguagem de programação (Python, Node.js, Java, C#, GO);

  

Desejável conhecimentos em Plataformas de Nuvem (AWS e Azure)
## Local 
REMOTO 
## Como se candidatar 
Accesse a [Vaga de Desenvolvedor Python](https://nerdprogramador.com.br/it4us-desenvolvedor-python/9e1813a7-5758-46d4-a2ab-4ff2a78c9ba4?utm_source=github) para mais informações. 
## Labels 
* Remoto

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
