### ISSUE TITLE
[Florianópolis] Front-end Developer na Binamik

### ISSUE THREAD

**Issue by carolinaantunes-96** [frontendbr/vagas#4734]
[Florianópolis] Front-end Developer na Binamik

> Vaga Remota durante a pandemia

A Binamik Tecnologia é uma startup de soluções tecnológicas que contribuem para a inovação no setor de turismo. A Plataforma Binamik auxilia na construção de um processo de vendas consistente e uma gestão viável de empresas deste segmento. Com o uso das mais modernas tecnologias, nosso objetivo é possibilitar um crescimento sólido e sustentável para nossos parceiros. 

Somos horizontais e independentes, encorajamos ideias e estamos sempre em busca de uma evolução baseada em dados. Aqui você estará em um ambiente que inspira a inovação e a colaboração.

## Descrição da vaga
Desenvolver e manter aplicações web; Desenvolver integração com múltiplas fontes de dados e bancos de dados; Desenvolver as aplicações considerando acessibilidade, capacidade, performance, segurança e demais aspectos que compreendem a qualidade de software.

## Local
Remoto ou Escritório, Florianópolis -SC, Saco Grande

## Requisitos
Experiência:
Desenvolvimento Front end em React Experiência com desenvolvimento front end (HTML, CSS, React.js e Javascript); Experiência com o padrão de arquitetura MVC; Domínio em Programação Funcional; Experiência com Deploy de aplicações web;
Formação: 
Superior completo em Ciências da Computação, Sistemas de Informação ou áreas relacionadas;
Competências Comportamentais:
Foco na qualidade - Pessoa que se preocupa com a qualidade da entrega, que se preocupa com o cliente e em como ele irá receber a informação.
Responsabilidade - Pessoa autogerenciável, que entende suas responsabilidades e se compromete com o que faz.
Flexibilidade - A empresa tem um perfil adaptável, é saudável ter essa competência de adaptação e flexibilidade com as mudanças
Trabalho em equipe - Pessoa que troque a informação, que pense no time. Que saiba focar no seu trabalho, mas compartilhar o conhecimento. Prezam muito também pela sinceridade no time. Se a pessoa errou, admite e resolvem.
Visão Sistêmica - Boa capacidade para olhar o projeto como um todo.

## Benefícios
Plano de saúde sem coparticipação
VR de R$ 20,00/dia
Vale transportes

## Contratação
CLT - salário a combinar

## Como se candidatar
Por favor envie um email seu currículo através do formulário https://forms.gle/Cgvh4CCMGhx6cNxy5

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: laine.martins@binamik.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
