### ISSUE TITLE
[Curitiba] Front-end Developer na DISYS

### ISSUE THREAD

**Issue by Thahcmp** [frontendbr/vagas#4735]
> Vaga Remota durante a pandemia

## Nossa empresa

A DISYS, empresa multinacional em consultoria em TI, presentes em 10 países, com parceria com grandes empresas!

## Descrição da vaga

O Dev Front End é responsável por desenvolver sistemas web e aplicativos híbridos IOS/Android para aplicações IoT e Mobilidade, além de adaptar protótipos em FIGMA para HTML/CSS e cuidar da publicação de aplicativos em Google Play/Apple Store. Esta posição vai atuar em conjunto com nosso time de UX/UI para converter protótipos em aplicações reais.

## Local

Escritório - Pós Pandemia, hibrido, com escritório para o presencial em, [PR/MG/PE], [Curitiba/BH/Recife]

## Requisitos

**Obrigatórios:**
Experiência de 3 anos ou mais como desenvolvedor web;
Experiência de 2 anos ou mais com Angular/IONIC.
JavaScript, AngularJS, Angular 8, Typescript;
Framework Ionic;
Consumo de API RESTs;
HTML5, CSS, SASS, Bootstrap/Material Design;
GIT.

## Benefícios

- VR ;
- VA;
- Gym Pass;
- Auxílio Home Office.
- Seguro de vida;

## Contratação

CLT -  Enviar pretensão salarial.

## Como se candidatar

Por favor envie um email para thais.pereira@disys.com com seu CV anexado - enviar no assunto: Vaga Front-end

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
