### ISSUE TITLE
[Remoto] Front-end Vue.js Developer na Basico&Co < by Coodesh />

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#4736]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url https://coodesh.com com o pop-up personalizado de candidatura. :wave:
<p>A Basico&amp;Co está buscando <strong>Frontend Developer</strong>, para compor seu time!</p>
<p>A Basico&amp;Co é um grupo de marcas nascido digitalmente, composta pela marca Basicamente - startup nascida dentro do Grupo Malwee, basico.com e pela basico.ink. Nós unimos moda com tecnologia através de produtos básicos com atributos e funcionalidades essenciais para o dia a dia e que também possam ser personalizados de maneira livre, possibilitando com que as pessoas se expressem através de produtos únicos.</p>
<p>Fornecemos uma infraestrutura de ponta a ponta para empresas e varejistas de todos os tamanhos criarem produtos e escalarem seu negócio em questão de minutos, com nossas soluções de comércio eletrônico e recursos de produção sob demanda.</p>
<p><strong>Nossa solução:</strong></p>
<p>Nossa solução consiste em uma aplicação completa: e-commerce na Plataforma Shopify com front-end em VueJS, sistema administrativo e integrações que consomem nossa API REST em Laravel, tudo dentro da estrutura de serviços da Amazon AWS.</p>

## Basico&Co: 
 <p>Nosso grupo é formado por três das principais marcas do país:</p>
<ul>
<li><a href="https://basicamente.com/" target="_blank">basicamente.</a> , uma one stop shopping de básicos com qualidade e o melhor custo beneficio, fundada em 2020, para toda a família</li>
<li><a href="https://www.basico.com/" target="_blank">basico.com</a> , marca de lifestyle básico e uma das primeiras DNVBs do Brasil, fundada em 2013, com produtos básicos premium e inovadores.</li>
<li><a href="https://basico.ink/" target="_blank">basico.ink</a>, um hub d e personalização de vestuário, facilitando através da tecnologia marcas e empresas de criarem produtos incríveis.</li>
</ul>
</p>

 ## Habilidades: 
 - HTML 5 
- Javascript 
- Shopify 
- Typescript 
- Vue.js 
- GIT 
- CSS 3
## Local: 
 100% Remoto
## Requisitos: 
 - Conhecimentos ou experiência em desenvolvimento front-end 
- Habituado com Git 
- Habituado com trabalho remoto, times ágeis e scrum 
- Fluente em HTML5 e CSS3 
- Conhecimentos ou experiências em trabalhar com Typescript ou Javascript

## Benefícios: 
 - 100% remoto 
- Plano de saúde (SulAmérica) 
- Plano odontológico (SulAmérica) 
- Vale refeição de R$33,00 por dia (desconto em folha de 20%) 
- Gympass 
- Desconto de 30% em todas as lojas do grupo
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Developer na Basico&Co](https://coodesh.com/vagas/frontend-developer-202213?origin=github&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção <b>Pedir Feedback</b> entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa <b>Recruiter</b> responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Nível
Pleno
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
