### ISSUE TITLE
[Belo Horizonte] Front-end Developer na Montreal Informática

### ISSUE THREAD

**Issue by RHMontreal** [frontendbr/vagas#4738]
## Nossa empresa

Montreal Informática

## Descrição da vaga

Estamos em busca de Desenvolvedor .Net Sr. para atuar em Belo Horizonte presencialmente

Requisitos:

.Net
Banco de dados, preferência por Oracle
Experiência Frontend
Experiência comprovada na área

Escolaridade: Graduação completa na área de informática.

Benefícios: VT + VR + AM + AO

Jornada: Seg a Sex das 09:00 às 18: 00hs

Local: Belo Horizonte / BH - Atividade Presencial

~ Enviar CV para selecao@montreal.com.br com pretensão salarial.

Vaga também destinada a PcD's - Pessoas com Deficiência.

#VemserMontreal

## Local

Escritório, [Belo Horizonte]

## Contratação

CLT

## Como se candidatar

Por favor envie um email para selecao@montreal.com.br com seu CV anexado - enviar no assunto: Vaga .Net

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 20 dias após cada processo.

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível

- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
