### ISSUE TITLE
[JOINVILLE, SÃO PAULO ou RIO DE JANEIRO] Front-end Developer na TOTVS

### ISSUE THREAD

**Issue by brunoromeiro** [frontendbr/vagas#4739]
[JOINVILLE, SÃO PAULO ou RIO DE JANEIRO] Front-end Developer na TOTVS

 > Vaga Remota durante a pandemia

## Nossa empresa

Somos a maior multinacional brasileira de tecnologia, aqui você cria e impulsiona tecnologias que transformam a vida de mais de 30 mil clientes no mundo.

Os desafios são diários e o aprendizado é constante na equipe de Business Intelligence da TOTVS.

Este profissional atuará na TI realizando a administração da ferramenta em um ambiente ágil, repleto de gente boa que é boa gente.

Curtiu? Venha ser um TOTVER!

Conheça o TOTVS Developers: https://developers.totvs.com/

## Descrição da vaga

Buscamos uma pessoa desenvolvedora para participar da modernização dos produtos TOTVS, construíndo uma biblioteca de componentes em Angular, open-source, que já possui muitos componentes. templates e serviços.

Link do projeto: https://po-ui.io

Algumas atribuições e responsabilidades:
- Componentes Web (Angular);
- Testes unitários;
- Páginas Web (em sua maioria documentação técnica);
- Suporte para outros desenvolvedores;
- Compartilhamento de conhecimento (artigos, vídeos, workshops, etc…);
- Pesquisa e inovação;
- Mentoria de desenvolvedores iniciantes.

## Local

Remoto [ATUALMENTE] ou Modelo Flexivel (2 dias por semana em casa) [JOINVILLE], [SÃO PAULO], [RIO DE JANEIRO]

## Requisitos

**Obrigatórios:**
 - Javascript (avançado);
- HTML5 / CSS3 (avançado);
- Git / Github

**Desejáveis:**
- Frameworks Javascript do mercado (Angular será um diferencial);
- RxJS
- Metodologia Ágil

**Diferenciais:**
- projetos open-source

## Benefícios

- Plano de saúde e odontológico;
- Vale refeição;
- Licença maternidade e paternidade estendida;
- Bicicletário;
- Vestiário;
- Seguro de vida;
- Acesso à plataforma da Universidade Corporativa TOTVS;
- Auxílio creche;
- Previdência privada;
- Escritório que estimula a criatividade e produtividade com ambientes para lanches, salas de jogos, mesas de bilhar e poltronas para relaxar;
- Gympass;

## Contratação

CLT

## Como se candidatar

Por favor se cadastrar na vaga: https://totvs.gupy.io/jobs/819735

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by brunoromeiro** [comment]
Esta vaga permanece aberta! Qualquer informação adicional podem me chamar no Twitter.

**Comment by brunoromeiro** [comment]
Esta vaga ainda continua aberta.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
