### ISSUE TITLE
[Curitiba] Vue.js developer na DroneMapp

### ISSUE THREAD

**Issue by cleberzavadniak** [frontendbr/vagas#474]
A princípior, Pleno/Sênior, mas se você for júnior pode "aplicar" também. ;-)

Descrição completa aqui:

https://medium.com/dronemapp/oportunidade-desenvolvedor-vue-js-b604f6f62da8

## Local

Preferência para Curitiba e Região, mas pode ser remoto, também.

## Benefícios

- Plano de saúde com co-participação
- Plano odontológico
- VR
- VT ou estacionmento

#### Diferenciais

- CEO sabe desenvolver mas não fica em cima enchendo o saco.
- CTO é desenvolvedor e faz questão que o processo seja legal e o código tenha qualidade, porque quer que a equipe mantenha a sanidade mental.
- Equipe legal, todo mundo bem competente.

## Requisitos

**Obrigatórios:**
- Conhecimento em Vuejs.

**Desejáveis:**
- Vide a descrição completa lá no Medium!

**Diferenciais:**
- Vide a descrição completa lá no Medium!

## Contratação

Vide a descrição completa lá no Medium!

## Nossa empresa

A DroneMapp é pioneira em prover transferência tecnológica para que outras empresas possam extrair inteligência de dados geográficos.

## Como se candidatar

Envie requisição POST com corpo JSON contendo as chaves `name`, `github` e `linkedin` para `https://dm-marvin.herokuapp.com/api/curriculum/`.

**Comment by kivervinicius** [comment]
Forma de enviar o curriculum criativa :+1:

**Comment by simaodeveloper** [comment]
Nossa podia ser em SP :D

**Comment by cleberzavadniak** [comment]
Pode ser remoto, abiguinho. O "departamento" é *remote-first*.

**Comment by rubenmarcus** [comment]
Brother, essa vaga é dos sonhos. Não só pela cultura e exigências, mas pelo que vocês fazem ( dados geográficos ), mas infelizmente meu conhecimento de vue ainda é bem pequeno, vou terminar meu portfolio feito nele, até setembro, mas se vocês ainda tiverem vagas assim mais pra frente ficarei feliz em me candidatar !!

**Comment by simaodeveloper** [comment]
@cleberzavadniak estou recebendo esse erro: "Error: 500 Internal Server Error"

**Comment by rafaelassumpcao** [comment]
@simaodeveloper  enviou como POST  e como application/json??  pq aqui foi de boa

**Comment by simaodeveloper** [comment]
Agora foi \o/

**Comment by icaioincau** [comment]
Vou encaminhar essa vaga para alguns colegas :)

**Comment by cleberzavadniak** [comment]
Tudo dando certo, sempre teremos novas vagas. Mais pra frente deve aparecer uma para customização do Redash, tanto do UI quanto criação de consultas. Só coisa divertida. :)

**Comment by jhonystein** [comment]
Muito criativo o processo de envio de currículo. Estou "brincando" de Vue a algum tempo, ótima escolha.

**Comment by raloliver** [comment]
Tesão de vaga piá!

**Comment by cicerohen** [comment]
@cleberzavadniak vaga ainda aberta? :)

**Comment by cleberzavadniak** [comment]
Assim que fechar essa issue será resolvida.

**Comment by clmadrazo** [comment]
Ainda a vaga está em aberto?

**Comment by cleberzavadniak** [comment]
Assim que fechar essa issue será resolvida.

**Comment by cleberzavadniak** [comment]
A vaga ainda está em aberto?
Assim que fechar, essa issue será resolvida.

Ainda em aberto está a vaga?
Assim que fechar, essa issue será resolvida.

Está a vaga em aberto, ainda?
Assim que fechar, essa issue será resolvida.

Em aberto a vaga ainda está?
Assim que fechar, essa issue será resolvida.

**Comment by cleberzavadniak** [comment]
Fechô. Vlw. Flw.

**Comment by nandomoreirame** [comment]
😢
