### ISSUE TITLE
[Remoto] Senior Front-end Developer na Nuuvem

### ISSUE THREAD

**Issue by nuuvem-hr** [frontendbr/vagas#4740]
## Nossa empresa

[Nuuvem.com](https://www.nuuvem.com/) é uma das maiores plataformas de distribuição digital da América Latina. Estamos trabalhando para nos tornarmos uma plataforma global para comprar, discutir e interagir sobre jogos.

Estamos à procura de um(a) Senior Front End Developer, para criação e implementação de interfaces web, modernas, resilientes e fáceis de usar e para nos ajudar a manter e desenvolver nossa atual plataforma, e ser um jogador-chave em um novo projeto que lançaremos este ano.

Você se juntará a uma equipe de entusiastas da indústria de jogos altamente qualificados, criando soluções em um ambiente ágil e apaixonado. O **trabalho em equipe** é essencial. Buscamos alguém obcecado em entregar trechos de código de alta qualidade de maneira rápida e estável, imaginando qualquer recurso como parte do valor total da plataforma, sem perder o foco em fazer as coisas. Segurança e desempenho devem ser suas prioridades.

## Local
Esta oportunidade de trabalho é válida para trabalho remoto e está disponível para qualquer lugar do Brasil.

## Responsabilidades
- Criar páginas HTML rápidas, semânticas e responsivas com técnicas de CSS modernas baseadas em layouts e mockups de alta e baixa fidelidade;
- Melhorar as páginas da web existentes de maneira técnica e interna, mas também visando uma melhor experiência do usuário;
- Trabalhar em conjunto com o restante da equipe, diretamente com o código-fonte do sistema, para implementar a interface para novos recursos ou alterações no código existente;
- Melhorar nosso conjunto de ferramentas de construção existente, refinar nosso processo e práticas de desenvolvimento e testes de front-end;
- Migrar as interfaces da web existentes para a interface do usuário baseada em componentes;
- Ser uma referência para outros desenvolvedores front-end menos experientes na equipe, orientar os desenvolvedores juniores e estar disposto a compartilhar conhecimento com a equipe;

## Requisitos
- Pelo menos 3 anos de experiência como desenvolvedor front-end;
- Bom senso de estética de design;
- Usuário autossuficiente de Linux ou macOS e que não tema o Terminal;
- Familiarizado com os conceitos CSS modernos, como layout flexível e de grade e com ferramentas de construção modernas;
- Amplo conhecimento em Javascript e sede por mais conhecimento;
- Experiência com algum framework de frontend de Javascript como Vue (preferencial), React, ou outros...
- Proficiente em inglês escrito e, pelo menos, bom conhecimento prático do inglês falado.

**Diferenciais:**
- Algum conhecimento de protocolo HTTP e APIs da Web;
- Experiência com outras linguagens de programação como Ruby ou Python;
- Algum conhecimento de desenvolvimento de backend, usando Node ou alguma outra linguagem;
- Experiência com UX de e-commerce.
- Capacidade de criar novas UI / UX e criar mockups e layouts;

## Nossas Crenças
- Pair Programming é sempre bem vindo;
- Qualidade e quantidade vivem em equilíbrio - nosso trabalho é encontrar esse equilíbrio.
- Um ótimo produto tem a ver com uma ótima experiência e valor agregado.
- Ouvir é mais importante do que falar. Mostrar é melhor do que contar.

## Benefícios
- Plano de saúde e Odontológico;
- Saldo para cursos de aperfeiçoamento;
- Retirada de 1 jogo por mês na nossa plataforma;

**Diferenciais:**
- Horário Flexível;
- Rico ambiente cooperativo com incríveis jogadores;
- Ambiente com drive para inovação e participação em novas soluções;

## Contratação
PJ a combinar

## Como se candidatar
Por favor, se candidatar em nosso site https://careers.nuuvem.com/o/senior-front-end-developer ou enviar um email para odara.menezes@nuuvem.com com seu CV ou perfil do linkedin atualizados.

## Labels
- Remoto
- PJ
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
