### ISSUE TITLE
[REMOTO] Júnior ou Estagiário - Front-end Developer apaixonado por educação na TutorMundi 

### ISSUE THREAD

**Issue by namenotrequired** [frontendbr/vagas#4745]
## Nossa empresa

Educação cria o futuro da sociedade. Tutoria é de longe o método mais efetivo de ensino. (Pesquise: "Bloom two sigma")

Somos uma pequena startup com grandes ambições. Todos na empresa trabalham com paixão pela missão de trazer um tutor excelente para cada um na América Latina.

O TutorMundi é um aplicativo [web](https://app.tutormundi.com/), [ios](https://apps.apple.com/br/app/tutormundi/id1171236598#?platform=iphone) e [android](https://play.google.com/store/apps/details?id=app.tutormundi.com&hl=pt_BR) de reforço escolar onde alunos de ensino fundamental e médio têm acesso a tutores das melhores universidades na hora, online e sem agendar. A plataforma funciona 24 horas por dia e 7 dias por semana. Em 2020 [foi considerada pela HolonIQ](https://forbes.com.br/forbes-tech/2020/06/estudo-inedito-lista-as-100-edtechs-mais-inovadoras-da-america-latina) uma das 100 edtechs mais inovadoras da América Latina.

Dê uma olhada: https://www.tutormundi.com/

Recebemos investimento no vale do silício e crescemos bastante durante a pandemia. Já foram dadas 2 milhões de minutos de aula na plataforma.

A empresa realmente investe nas pessoas. Por exemplo, eu sou holandês e a empresa arrumou um visto de trabalho para mim. Também apoiou nosso designer a passar 6 meses estudando em Stanford. Ano passado entrou um estagiário que cresceu tanto que hoje já tá liderando uma equipe de 5.

## Descrição da vaga

Você vai usar tecnologias web (HTML, CSS, JavaScript) para melhorar o nosso aplicativo em todas plataformas (web, Android, iOS).

Correções, melhorias, novas funcionalidades, se tiver interesse pode chegar a trabalhar com análise de dados, escalabilidade...

Você vai trabalhar remotamente com bastante apoio e tutoria do time. E ainda temos eventos informais para nos divertir.

## Local

Remoto

## Requisitos

Conhecimento de Git, HTML, CSS, JavaScript.

Paixão por educação.

Aprender rápido.

Atitude proativa.

## Benefícios

**Diferenciais:**

- Remoto, na pandemia e pós-pandemia
- Horário flexível
- Equipe pequena e empolgada
- Empresa que realmente investe nas pessoas
- Aula semanal de conversação em inglês

## Contratação

CLT / PJ / estágio

## Como se candidatar

Você pode se candidatar aqui: https://tutormundi.typeform.com/to/VLPJ13fl

Qualquer dúvida, escreva para bart@tutormundi.com.

#### Alocação
- Remoto

#### Regime
- CLT
- Estágio
- PJ

#### Nível
- Júnior

**Comment by jhefflg** [comment]
Há a possibilidade de part-time?

**Comment by Alex-dll** [comment]
O formulário ficou muito lindo <3, deu ate gosto de preencher ^^
