### ISSUE TITLE
[Brasil - Home Office] Front-end Developer na Topaz

### ISSUE THREAD

**Issue by Re-Honorio** [frontendbr/vagas#4747]
> Vaga Remota durante a pandemia

## Nossa empresa

Somos uma multinacional atuando com soluções bancárias e financeiras, sendo produtos de alta tecnologia. 

## Descrição da vaga

- Experiência em uma das Linguagens de Programação (HTML, CSS, JavaScript, TypeScript, Java Android, Swift)

- Conhecimentos em algum dos frameworks híbridos (Angular, React Native, React Web, Ionic Cordova, Flutter, JQuery)

- Conhecimentos em Metodologias Ágeis (preferencial SCRUM)

- Experiência em Lógica de Programação

- Experiência com Programação Orientada a Objetos

- Conhecimentos em técnicas BDD/TDD

- Conhecimentos em ferramentas de teste unitário

- Conhecimento de Mobile

Ferramentas Obrigatórias: Visual Code, Npm (nodejs)

Desejável: 

- Experiência em frameworks híbridos

- Conhecimentos em publicação nas lojas Apple / Android

- Conhecimentos línguas Inglês e/ou Espanhol

## Benefícios

- Plano de saúde
- Seguro de vida
- VR 
- Auxílio creche
- TotalPass
- Dentre outros 

## Contratação

CLT 

## Como se candidatar

Por favor envie um email para rhonorio@topaz.com.uy com seu CV anexado - enviar no assunto: Vaga Front End Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: rhonorio@topaz.com.uy

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
