### ISSUE TITLE
[São Paulo] Front-End Developer na Just Digital

### ISSUE THREAD

**Issue by daniiell3** [frontendbr/vagas#475]
## Descrição da vaga

Estamos em busca de desenvolvedores apaixonados por construir produtos digitais de qualidade, que estejam atualizados com as melhores práticas e tecnologias, envolvidos e engajados com comunidades de software.

## Local

Escritório, São Paulo - Chácara Sto. Antônio

## Benefícios

- Vale Transporte ou Auxílio Combustível 300,00/mês + Auxílio Estacionamento R$ 170,00/mês (ambos apenas se você realmente vem de carro)
- Vale-refeição de R$ 594,00
- Assistência médica (30% empresa / 70% colaborador)
- Participação no bônus anual com base nos lucros da empresa (PLR)
- Seguro de vida em grupo

#### Diferenciais

- mesa de ping pong
- mesa de bilhar
- 4 home-offices por mês

## Requisitos

**Obrigatórios:**
- HTML5 / CSS3
- Pré/Pós processadores CSS (Less, Sass, PostCSS, etc)
- Task Runners (Gulp, Grunt, etc)
- Javascript (ES5, ES6, Node)
- Grid System (Lost, Gridle)
- Desenvolvimento Responsivo e Adaptativo
- Conhecimento prático do fluxo de versionamento com GIT
- Consumo de API
- Bootstrap / Materialize
- Utilização de padrões e boas práticas para desenvolvimento Front-end

**Desejáveis:**
- Wordpress
- Drupal

**Diferenciais:**
- React / React Native / VueJS / Angular
- Testes unitários e comportamentais
- Inglês

## Contratação

CLT Full

## Nossa empresa

Somos uma empresa de tecnologia, desde 2008 na estrada, especializada em criar software e plataformas digitais com o objetivo de reter e aproximar clientes, parceiros e colaboradores, das empresas que atendemos.

Trabalhamos em parceria com as áreas de TI, Inovação, Marketing e Digital, definindo as melhores estratégias, oferecendo as melhores soluções e desenvolvendo software sob medida. 

Sempre com pensamento ágil e foco na necessidade e experiência do usuário, visamos lançar rápido eliminando desperdício.

Diferente das consultorias de TI e empresas de desenvolvimento de software, prezamos o rápido atendimento, a flexibilidade para adequar nossos processos, a resposta rápida à mudanças e a proximidade com nossos clientes.

#### NOSSOS VALORES

- Ser a mudança para mudar tudo
- Fazer com equilíbrio e com o coração
- Ouvir para ser ouvido
- Democracia
- Transparência
- Integridade e ética
- Honrar nossos compromissos
- Fazer o simples, para fazer mais e mais certo
- Excelência: Experiência incrível e encantadora
- Data Driven

## Como se candidatar

Candidate-se em [Recruiterbox](https://justdigital.recruiterbox.com/jobs/fk0fhfq)

**Comment by daniiell3** [comment]
Labels: Alocado, CLT, Júnior, Pleno, Sênior

**Comment by paulo-campos** [comment]
@daniiell3
A vaga descrita nessa _issue_ não é a mesma apresentada na url para se candidatar.

**Comment by daniiell3** [comment]
@paulo-campos 
Estamos vendo de separar lá no Recruiter, mas são duas vagas, uma front-end e outra back-end, pode ficar tranquilo.

Valeu pelo feedback

**Comment by paulo-campos** [comment]
@daniiell3
Tranquilo!

**Comment by LFeh** [comment]
Bacana!

**Comment by paulo-campos** [comment]
@daniiell3 
Cara vou indicar um amigo Back-End pra essa vaga também

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by daniiell3** [comment]
@LFeh Sim

Ainda estamos buscando.
