### ISSUE TITLE
[Remoto - Brasil] Front-end Developer Pleno/Sênior - Easy2Recruit

### ISSUE THREAD

**Issue by MariEasy2Recruit** [frontendbr/vagas#4750]
Desenvolvedor Fron End Pleno/Sênior

DESCRIÇÃO DA VAGA
Estamos construindo um time com propósito, motivado e com muita vontade de fazer acontecer. Você vai trabalhar com pessoas e para pessoas, com muita autonomia e flexibilidade para desenvolver, afinal não somos apegados a nenhuma tecnologia.

Aqui no Grupo Bari, valorizamos cada história e acreditamos que cada experiência conta. Se você quer fazer a diferença e ajudar a transformar a vida financeira das pessoas, vem com a gente!

RESPONSABILIDADES E ATRIBUIÇÕES
Trabalhar em conjunto com a equipe de design na definição de melhores práticas e soluções;
Participar de decisões tecnológicas, como escolha de bibliotecas;
Cooperar com os membros na definição e criação de novos componentes;
Desenvolver as soluções com a melhor qualidade possível, levando em consideração o cliente e seus colegas desenvolvedores;
Auxiliar membros de sua equipe quanto às melhores práticas de mercado;
REQUISITOS E QUALIFICAÇÕES
Domínio com Javascript;
Domínio do framework React;
Domínio de CSS;
Domínio de HTML;
Domínio no uso de git;
Experiência em metodologias ágeis;
Domínio de algum pré-compilador CSS (LESS/SASS);
Experiência com pipeline de compilação Web;
Experiência com Figma;

Contratação preferencialmente em regime CLT, mas a empresa avalia formato PJ.

Interessados encaminhar currículo com pretensão salarial para mariana@recrutamentofacil.com

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
