### ISSUE TITLE
[Remoto/Porto Alegre] Fullstack Developer na Warren

### ISSUE THREAD

**Issue by lolivei** [frontendbr/vagas#4751]
> Vaga Remota durante a pandemia
## Nossa empresa
A Warren é uma corretora de investimentos autorizada e regulada pela CVM, Anbima e Banco Central, que tem a missão de descomplicar as finanças e transformar o hábito de investir em algo fácil, transparente e eficiente.
Nossa matriz fica em Porto Alegre e temos mais 6 unidades (São Paulo, Rio de Janeiro, Curitiba, Florianópolis, Jaraguá do Sul, Itajaí, Blumenau e Joinville). 

Já somos um time de mais de 380 pessoas, todas dispostas a fazer o Warren acontecer e transformar a forma como o brasileiro investe.

www.warren.com.br

## Descrição da vaga
- Desenvolvimento de melhorias, novas funcionalidades e correções relacionadas ao Front-end das aplicações;
- Participar de decisões sobre novas ferramentas e tecnologias a serem utilizadas;
- Buscar conhecimento de negócio;
- Propor melhorias no funcionamento dos chapters ou área de atendimento.

## Local
Remoto ou Porto Alegre - RS

## Requisitos
**Obrigatórios:**
- Proficiência em Javascript e NodeJS;
- Proficiência em CSS3 (Less);
- Bom conhecimento em Vue ou frameworks como React.js e React;
- Experiência em banco de dados documentais como MongoDB;
- Conhecimento sobre desenvolvimento de APIs;
- Experiência no desenvolvimento de SPA's;
- Experiência com programação assíncrona;
- Ter noções de segurança entre as camadas da aplicação;
- Proficiência em Git;
- Experiência com testes unitários e de integração;

**Desejáveis:**
- Experiência na utilização de Typescript;
- Experiência ou conhecimento em Design System;
- Noções de performance e acessibilidade;
- Docker;
- CI | CD;

**Diferenciais:**
- Experiência em aplicações de serviços financeiros. 

## Benefícios
- RS: Plano de Saúde Unipart: pago pela Warren. Upgrade para Unimax com coparticipação;
- Fora do RS: Sul América Exato: 100% pago pela Warren. Upgrade com coparticipação;
- Benefício flexível (VR/VA) de R$682,00/mês: Para utilizar como preferir!
- Vale transporte: desconto diferenciado;
- Benefício terapia em parceria com a plataforma Vittude: 40% de desconto no valor das sessões;
- Aulas de Yoga semanais: 40% do valor das aulas pago pela Warren;
- RS: Parceria Oka coliving: Te ajudamos com o seu aluguel de quarto;
- Programa de Partnership;
- Bonificação Variável: possibilidade de até 2 salários atrelados ao atingimento de metas coletiva;

**Diferenciais:**
- Área de lazer e entretenimento;
- Chopp artesanal a preço justo;
- Frutas todas segundas-feiras;
- Pão fresquinho todas as manhãs;

## Contratação
CLT

## Como se candidatar
Por favor cadastre seu CV em https://warrenbrasil.gupy.io/jobs/766754

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 5 dias após cada etapa processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
