### ISSUE TITLE
[São Paulo] Front-end Developer na5A Attiva

### ISSUE THREAD

**Issue by helenmatos** [frontendbr/vagas#4753]
> Vaga Remota durante a pandemia

## 5A Attiva

Buscamos por profissionais que gostem de atuar em modelo squad, com profissionais de grande conhecimento técnico. 

## Descrição da vaga
Manutenção e implementação de novas funcionalidades em websites já existentes; - Participação em reuniões de concepção; - Desenvolvimento de novas soluções; - Manter o padrão e bom funcionamento dos códigos; - Trazer ideias, melhorias e sugestões;

## Local

Remoto durante a pandemia 
 Após pandemia ( sem previsão de fim) atuara 2 vezes por semana no Escritório -  São Paulo -  Centro 

## Requisitos
**Obrigatórios:**
- 
Experiência com Angular 6 ou superior; - TypeScript; - HTML 5 - CSS / Sass - JavaScript; - Atuação com integrações entre front-end e API; - Versionamento: Git; - Metodologias Ágeis: Scrum, Kanban;

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um e-mail para ingrid.prudencio@5aattiva.com.br  com seu CV anexado - enviar no assunto: Vaga Front

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
