### ISSUE TITLE
[Guarulhos] Front-end Developer PL na Quality Nextech

### ISSUE THREAD

**Issue by BeaMorais-techrecruiter** [frontendbr/vagas#4754]
> 

## Nossa empresa

Somos uma empresa há mais de 30 anos no mercado brasileiro atuando com as soluções tecnológicas competitivas para grandes clientes.
Com operações em Curitiba, Rio de Janeiro, São Paulo e agora no México, a Quality Nextech é uma empresa em constante crescimento.
Proporcionamos aos nossos colaboradores diferenciais atrativos como incentivos de certificação, #indiqueumamigo e oportunidades para atuar em grandes projetos!
Junte-se a nós e venha conhecer nossos outros incríveis programas de desenvolvimento.

## Descrição da vaga

Profissional Pleno responsável por desenvolvimento de sistemas Web com foco em layout e experiência de navegação do usuário para atuar em escala híbrida (home x office) na região de Guarulhos.

**Atividades:** 
• Desenvolvimento front-end em HTML, CSS e Javascript com React (Typescript).
• Desenvolvimento back-end em Javascript com NodeJS.
• Desenvolvimento de pipelines de deploy automatizado (Git, GitLab-CI ou afins).
• Desenvolvimento em Cloud (experiência em ambientes AWS, Google ou Azure)
• Realizar análises técnicas para propor as melhores soluções para o produto;
• Participar de reuniões com o time de produto para definição de boas práticas de design, usabilidade e interações;
• Manutenção do style guide e design system junto do time de design;
• Trabalhar em equipe utilizando a metodologia ágil SCRUM;
• Criação de POCs (provas de conceito) para validar ideias para implementação no produto;
• Ajudar a construir e manter nossas bibliotecas de componentes front-end;
• Prestar suporte aos usuários durante e após as entregas do projeto;

## Local

Exemplo: Remoto e Escritório, [SP], [Guarulhos]

## Requisitos

**Obrigatórios:** 
- Conhecimento em técnicas de UI e Design, ferramentas de edição de layouts.
- Desenvolvimento ágil em ambiente de integração contínua (Jenkins, Docker, SonnarQube).
- Desenvolvimento orientado a testes, técnicas de stress e security test. 
- Formação superior em Tecnologia, Engenharia ou áreas correlatas 
- Mínimo de 2 anos de experiência nas funções descritas.

## Benefícios

- Plano de saúde
- Seguro de vida
- VR 

## Diferenciais
- Quality Certifica
- Indique um Amigo
- Gympass
- Trilha de Liderança

## Contratação

Salário a combinar

## Como se candidatar

Por favor envie um email para beatriz.morais@quality.com.br com seu CV anexado - enviar no assunto: 2611

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: beatriz.morais@quality.com.br

#### Alocação
- Escala Híbrida (home x office)

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
