### ISSUE TITLE
[Curitiba] Desenvolvedor Front end React Native na uCondo

### ISSUE THREAD

**Issue by NerdProgramador-com-br** [frontendbr/vagas#4755]
## Descrição da vaga 
Descrição da vaga
-----------------

  

Somos apaixonados por tecnologia e acreditamos que o produto possui um papel fundamental nessa jornada! Para chegarmos lá, nossa plataforma precisa estar em constante evolução atendendo a todas as necessidades dos clientes de forma fácil, prática e segura. Com isso, seu objetivo será projetar e desenvolver soluções escaláveis colaborando com as demais pessoas da equipe.

Você fará parte da Squad de Apps como desenvolvedor frontend e irá trabalhar na migração do nosso aplicativo para a tecnologia React Native.

  

[https://www.ucondo.com.br/vagas](https://www.ucondo.com.br/vagas)

  

Local
-----

Remoto ou Escritório, Curitiba - Bigorrilho

  

Benefícios
----------

● Salário Base: Alinharemos de acordo com experiência - de R$ 6k a R$ 10k nos envie sua pretensão salarial junto com seu cv :)

● Vale Refeição: R$ 396,00/mês - sem descontos

● Plano Odontológico - sem descontos

● Plano de Saúde - sem descontos

● Seguro de Vida - sem descontos

● Vale Transporte

● Horário de trabalho: segunda à sexta das 09:00h às 18:00h

  

#### Diferenciais

● Ambiente casual em Curitiba, você pode usar jeans e tênis para trabalhar, no dress code

● Ambiente agradável com puffs, livros, café e chá à vontade, videogame

● Estamos trabalhando de casa neste período de isolamento social, então é provável que continuemos assim por mais alguns meses

  

Requisitos
----------

Obrigatórios:

● Sólidos conhecimentos em desenvolvimento mobile (Android e iOS)

● Conhecimentos avançados em React Native e React Js

● Conhecimento total dos ciclos de um aplicativo (concepção, desenvolvimento e publicação nas stores)

● Sólidos conhecimentos em Git

● Gostar de programar e resolver problemas

● Ser um amante de tecnologia e estar sempre atualizado com as novidades do mercado

● Ter pró atividade em trazer ideias novas e ao mesmo tempo ter um senso de dono do negócio

● Ser didata, possuindo facilidade em compartilhar os conhecimentos

Diferenciais:

● Experiência na criação de aplicativos empresariais do zero

● Conhecimentos em tecnologias como Flutter, Angular, Ionic, VueJs, Dart, Swift, Kotlin, Java, C#

  

---

Nossa empresa
-------------

A uCondo existe porque a comunicação dos condomínios é precária e desorganizada, administradoras de condomínios possuem processos burocráticos, caros e demorados. Nosso propósito é proporcionar economia e comodidade para administradoras, síndicos e moradores, tudo isso alinhado ao nosso sonho grande de tornar todos os condomínios inteligentes.

  

[https://www.ucondo.com.br/vagas](https://www.ucondo.com.br/vagas)

  

Como se candidatar
------------------

  

Acesse [http://bit.ly/ucondoprocessoseletivo](http://bit.ly/ucondoprocessoseletivo) e nos envie seu CV.

O processo seletivo consiste em 3 etapas: primeira conversa, um desafio de projeto e a última sendo uma conversa com a equipe de devs.

  

---
## Local 
Curitiba/PR 
## Como se candidatar 
Accesse a [Vaga de Desenvolvedor Front end React Native](https://nerdprogramador.com.br/ucondo-desenvolvedor-front-end-react-native/e01dea3b-91e9-4965-a219-7cf7646219b7?utm_source=github) para mais informações. 
## Labels 
* Alocado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
