### ISSUE TITLE
[Florianópolis] Front-End Developer na @Neoprospecta

### ISSUE THREAD

**Issue by NEOPROSPECTAPESQUISAECONSULTORIASA** [frontendbr/vagas#4757]
> Vaga Remota durante a pandemia

## Nossa empresa

A Neoprospecta é uma empresa dedicada ao desenvolvimento e comercialização de análises microbiológicas inovadoras, baseadas em sequenciamentos de DNA de nova geração, análises biocomputacionais e técnicas de PCR quantitativo. Também possuímos uma linha de soluções, produtos e serviços voltados às necessidades e desafios, onde o conhecimento e o diagnóstico rápido, sensível e preciso, dos micro-organismos, são cruciais para a tomada de decisões e qualidade operacional.

## Descrição da vaga

Programador(a) Front-end

## Local

Florianópolis/SC.

## Requisitos

**Obrigatórios:**
- Experiência com algum framework Frontend (Angular, React, Vue, etc);
- Experiência com Javascript, Typescript, HTML5, CSS, SASS;
- Experiência com APIs REST;
- Ensino superior em área de sistemas ou afins (ou mínimo de 3 anos de experiência profissional);
- Experiência com Linux e Git;

**Desejáveis:**

- Escrever código organizado e fácil de entender;
- Trabalhar com metologia ágil;
- Pró ativo;
- Ter excelência na leitura em inglês;

**Responsabilidades:**

- Ter princípios como os de crescimento em equipe, foco em gerar resultado, autogerenciamento, e colocando o   cliente sempre em primeiro lugar.
- Desenvolver Frontend para sistemas para suportar fluxos de trabalhos internos e externos com os nossos clientes;
- Desenvolver interfaces dinâmicas para visualização de dados microbiológicos e genéticos;

## Benefícios

- Cozinha comunitária com geladeira, microondas, sanduicheira;
- No dress code;
- Flexibilidade de horários;
- Open café;
- Centro comercial próximo;
- Biblioteca comunitária.
- Kit de boas vindas.

## Como se candidatar

Por favor envie um email para rh@neoprospecta.com com seu CV anexado - enviar no assunto: Vaga Programador(a) Front-end

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
