### ISSUE TITLE
[Santos] Front-End Developer na KBRTEC

### ISSUE THREAD

**Issue by mathvbarone** [frontendbr/vagas#476]
## Descrição da vaga

O profissional vai desenvolver interface de websites e sistemas utilizando HTML5, CSS3, e Javascript, pensando em uma boa manutenibilidade, rankeamento e acessibilidade.

## Local

Escritório na Vila Mathias - Santos.

## Benefícios

- Remuneração compatível
- Vale Transporte
- Ticket Refeição

#### Diferenciais

- Ótimo ambiente de trabalho, equipe jovem com espírito colaborativo.
- Custeio para cursos e eventos técnicos de interesse. 

## Requisitos

- HTML5; 
- CSS 3; 
- Javascript, AJAX, JQuery, JSon; 
- Noções de UX e UI; 
- Responsive Design; 
- Framework CSS (Bootstrap); 
- Wordpress; 
- GULP; 
- SEO; 
- Versionamento (GIT); 
- Email Marketing

**Desejáveis:**
- Familiaridade com Framework Javascript (como Angular); 
- Familiaridade com Scrum;

## Contratação

CLT

## Nossa empresa

Nosso desafio é materializar boas ideias em soluções web de sucesso - práticas e simples, aproveitando ao máximo o potencial da internet. Este é o nosso trabalho e esta é a nossa paixão!

Há mais de treze anos nos dedicamos exclusivamente a isso e acumulamos muitas experiências ao longo desta trajetória.

Somos uma equipe mista, de designers e de programadores. Enquanto um grupo de trabalho se dedica a construir interfaces belas e intuitivas, o outro grupo se preocupa em torná-las funcionais, com tecnologia de ponta.

Sabemos que o investimento em um site profissional precisa gerar resultados concretos, por isso nos preocupamos muito com o seu posicionamento nos buscadores (SEO) e compatibilidade plena com todos os dispositivos móveis (tablets e smartphones).

## Como se candidatar

Por favor envie um email para daniel.alexandrino@kbrtec.com.br com o título "VAGA-FRONT-END".

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by mathvbarone** [comment]
Não, esqueci de fechar a issue, foi mal!
