### ISSUE TITLE
[Remoto] Front-end Developer na Olinga Services

### ISSUE THREAD

**Issue by gregoryfm** [frontendbr/vagas#4760]
# Olinga Services

## ABOUT THIS OPPORTUNITY 

We are looking for technically minded, experienced React developers to join our growing team of engineers.   

You will play an important role in the continuous improvement and evolution of our platforms.   You will work in a collaborative team environment, technically hands-on, develop, manage the design, and build of complex infrastructure, enhance and support software applications and components that facilitate the achievement of business and client outcomes. 

## THE ROLE
Responsibilities will include: 
- Develop and interpret business requirements and develop detailed design specifications 
- Ability to plan, map and code new business requirements 
- Provide estimates on how long development activities would take to deliver
- Learn about the businesses processes and translate these into dashboards and reports which enhances the businesses day to day operating needs
- Engage with the stakeholders to ensure they are informed on the progress of the project. 
- Ensure that the project is continuing to flow through the development pipeline and raise any blockers for discussion
- Execute further development and maintenance of existing applications across the organisation 
- Analyse, design, configure, test, implement and maintain complex functionality enhancements 
- Ensure all code is well documented, tested, updated and reviewed
- Develop and implement new features across products

## ABOUT YOU
The right person for the role must have: 

- Flexibility and willingness to undertake a wide range of tasks and make decisions 
- Demonstrated organisational skills plus attention to detail
- 3+ years’ industry experience with React
- Demonstrated understanding of Jira 
- Good communication skills reading and writing in English
- The ability to adapt to diverse environments, manage multiple priorities and meet deadlines
- Must be able to quickly learn, understand and integrate new technology
- Self-motivated, with demonstrated ability to work autonomously, proactively and within a team

Essential Skills and Experience:  
- Strong React knowledge
- Strong JavaScript experience
- Good CSS experience
- Redux + Redux-Saga
- Styled Components
- APIs REST
- Responsive design
- Ant Design Charts or other react charts lib

**If you are passionate about technology and want to join an innovative company that is going through an exciting period of growth, then this opportunity is for you.  Please email your CV to gregory@vyans.com** 

##  WHO ARE WE

**Olinga Services is an Australian based company** which specialises in providing high-quality commercial cleaning solutions.  We have front line experience in implementing COVID risk reduction strategies, including as a partner to the New South Wales Government for the implementation of their COVID response.

Both before and during the COVID-19 pandemic, our team has worked hard to perfect the very latest and best in sanitisation technology and techniques. 

Through our integrated network, Olinga Services is a one-stop full-service solution to meet our client’s needs and objectives.  Our network includes contract management, labour-hire, cleaning and sanitisation services, data analytics and process improvements, training programs and real-time reporting. 

We create technology and work hard to help our customers transform their businesses through the innovative use of technology. We partner with our clients to solve problems others can't. We do this by hiring the best people out there.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
