### ISSUE TITLE
[Remoto] DEV Angular na MODALGR

### ISSUE THREAD

**Issue by MODALGR** [frontendbr/vagas#4761]
> Vaga Remota durante a pandemia

## Sobre a MODALGR

Somos uma empresa GPTW e um time apaixonado por tecnologia e a entrega de resultados é uma obsessão de nossos consultores.
Venha fazer parte do time da ModalGR, empresa de tecnologia, consultoria e outsourcing, com foco na inovação e apaixonada por tecnologia!

## Descrição da vaga

Projeto de desenvolvimento de portal com usando solução de certificação digital para o meio acadêmico (mais detalhes serão divulgados durante o processo).
Período de alocação mínimo de 6 meses (renovável de acordo com a extensão do projeto).

## Local

- Remoto

## Requisitos

**Obrigatórios:**
- Experiência mínima profissionalmente de 1 ano com Angular;
- Criação e reutilização de componentes;
- Experiência em Git (Git Flow);
- Experiência com HTML 5, CSS, Flex Box, Grid Layout;
- Conhecimento em Javscript/TypeScript;
- Conhecimento das Bibliotecas NgRx e RxJS;
- Conhecimento das Bibliotecas de CSS e componentes como Material Design, Bootstrap;
- Conhecimento em metodologia Ágil Scrum.

**Desejáveis (não é mandatório):**
- Conhecimento em Angular.js;
- Conhecimento com DevOps;
- Conhecmento com Web Design;
- Conhecimento com Java no BackEnd;
- Conhecimento no uso do Framework SpringBoot;
- Portfolio para análise (GitHub, Behance, etc.)

## Benefícios (CLT)
- VR, VT, AM, Seguro de Vida

## Contratação
- CLT ou PJ (a combinar)

## Como se candidatar
- Enviar email para querofazerparted@modalgr.com.br;
- O CV deverá estar anexado na mensagem (links para locais públicos, como pasta do Google Drive não serão aceitos);
- Informar no assunto: Vaga DEV Angular - GitHub frontendbr;
- Informar no corpo: Pretensão CLT e/ou PJ.

## Tempo médio de feedbacks
- Após análise curricular, os candidatos com maior fit para as vagas serão chamados em até 2 semana;
- Todo o candidato que passar na fase de triagem de CVs e for convidado para a entrevista receberá feeback sobre o processo (que será dado pela equipe de RH da empresa);
- Devido ao volume de CVs e vagas sendo tratadas no momento pelo time de recrutamento em seleção, os candidatos que não passarem pela análise curricular não receberão feedback.

#### Regime
- CLT
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
