### ISSUE TITLE
[Remoto] Mid Front-end Engineer na Wedy

### ISSUE THREAD

**Issue by danieltamiosso** [frontendbr/vagas#4762]
## Descrição da vaga

A [Wedy](https://wedy.com) é uma plataforma digital que facilita a jornada do casamento. Nosso dia-a-dia é tornar a experiência dos nossos usuários mais agradável, sem complicações — o casamento já é um momento extremamente delicado para qualquer casal. Com isso em mente, reorganizamos e repensamos alguns conceitos no nosso produto e agora precisamos implementá-los. É nesse ponto que você entra, sendo uma peça fundamental na criação da próxima geração da nossa plataforma. Esta vaga exige um nível maior de criticidade e conhecimentos específicos, uma vez que todas as decisões tomadas agora influenciarão os próximos anos de nossa empresa. Mas não tema, você terá companhia: a Wedy tem muito orgulho do seu time de engenharia e esperamos que em breve você faça parte dele.

## Local
Remoto

## Benefícios

- Horários flexíveis e reduzidos (6h por dia);
- Day-off no aniversário;
- 30 dias de férias remuneradas;
- Vale-alimentação e convênio médico sem descontos;
- 100% remoto;
- Pacote de remuneração competitivo.

#### Diferenciais

- Participações em eventos e incentivos financeiros à leitura e ao desenvolvimento pessoal;
- Wedy Talks;
- Ambiente divertido, colaborativo e rápido;
- Oportunidade de crescimento rápido;
- Confiança e liberdade.

## Requisitos
- Conhecimento sólido em JavaScript;
- Experiência com React em produção;
- Experiência com consumo de APIs em produção;
- Experiência com Figma ou semelhante;
- Saber se comunicar de forma eficiente e clara, sendo ela escrita ou oral;
- Saber gerenciar seu tempo, organizando e priorizando seu trabalho;
- Estar em dia com as últimas novidades de front-end.

## Responsabilidades
- Participar ativamente no desenvolvimento e manutenção das diversas funcionalidades do produto, sempre tomando os cuidados necessários para não gerar dívidas técnicas;
- Participar ativamente na revisão do trabalho de colegas;
- Sugerir e realizar melhorias no código;
- Sugerir e realizar melhorias no produto;
- Ser referência como mentor para engenheiros júnior;
- Manter-se em dia com as últimas novidades de front-end.

## Contratação
PJ a combinar

## Como se candidatar
Aplicar [via Linkedin](https://www.linkedin.com/jobs/view/2524250823/?refId=czdq5WdkQ2upVBpJCIlIpQ%3D%3D) ou enviar e-mail para daniel@wedy.com com Linkedin/Github/etc.

## Labels

- Remoto
- Pleno
- PJ

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
