### ISSUE TITLE
[100% REMOTA] 5 vagas de Full-Stack Angular11 na Target Work

### ISSUE THREAD

**Issue by afonsonsj** [frontendbr/vagas#4764]
3 vagas Programador .Net Core/Angular11 Junior
Perfil:
Boa comunicação, Pró-atividade, com foco em resultado;
Capacidade para assimilar novas informações, tecnologias e ferramentas;
Bom relacionamento interpessoal;
Aptidão na identificação e compreensão de problemas e oportunidades;
Adaptabilidade a mudanças;
Comprometimento;
Disponibilidade para eventuais horas extras.
Perfil técnico:
Experiência com desenvolvimento web utilizando C#, POO, .Net Core, SQL Server;
Experiência com desenvolvimento em SPA (Angular e/ou React);
Desejáveis Conhecimentos em padrões de projetos como MVC;
Local: REMOTO
Email para: vagas@targetwork.com.br
Assunto: Programador .Net Core/Angular11 Junior

-----

2 vagas Programador .Net Core/Angular11 Pleno
Perfil:
Boa comunicação, Pró-atividade, com foco em resultado;
Capacidade para assimilar novas informações, tecnologias e ferramentas;
Bom relacionamento interpessoal;
Aptidão na identificação e compreensão de problemas e oportunidades;
Adaptabilidade a mudanças;
Comprometimento;
Disponibilidade para eventuais horas extras.
Perfil técnico:
Experiência com desenvolvimento web utilizando C#, POO, .Net Core, SQL Server;
Experiência com desenvolvimento em SPA (Angular e/ou React);
Desejáveis Conhecimentos em padrões de projetos como MVC;
Local: REMOTO
Email para: vagas@targetwork.com.br
Assunto: Programador .Net Core/Angular11 Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
