### ISSUE TITLE
[OPORTUNIDADE] [FRONT-END] [SOMOS EDUCAÇÃO]

### ISSUE THREAD

**Issue by izabellaschafhauser** [frontendbr/vagas#4769]
A SOMOS Educação é o maior grupo de Educação Básica do Brasil e faz parte do Grupo Cogna Educação que, com mais de 50 anos de atuação, é uma das maiores empresas do setor de educação do mundo! Oferece um amplo portfólio de soluções educacionais como sistemas de ensino, editoras, além de uma tecnológica plataforma de aprendizado digital e de e-commerce.

Sua missão é transformar e liderar o ecossistema das escolas privadas, unindo educação e gestão de alta qualidade por meio da neurociência aliada à tecnologia em larga escala para facilitar o processo de transformação digital.

Incrível, né? Imagina fazer parte desse time que tem educação, inovação e dinamismo no seu DNA!

Se você está aberto(a) a oportunidades e quer saber um pouco mais sobre o desafio a ser enfrentado, dá uma olhadinha no link:

*https://vagas-emb.byintera.com/2uf*

Não faz sentido para você, mas conhece alguém que pode se interessar? Comenta aqui embaixo, compartilha o link ou me chama no privado e vamos conversar!

Um sorriso de orelha a orelha =)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
