### ISSUE TITLE
[Porto Alegre, RS] Front-End Developer na Superplayer

### ISSUE THREAD

**Issue by robsondealmeida** [frontendbr/vagas#477]
## Descrição da vaga

Buscamos um Front-end Developer capaz de arquitetar e construir interfaces que proporcionem a melhor experiência em SPAs (Single Page Applications) de música para Web, que seja apaixonado por aprender e codificar (em JavaScript, CSS e HTML) e que goste de pensar no produto além das linhas de código.

Ela/ele será responsável por pensar, contribuir no planejamento e desenvolver novas funcionalidades no Superplayer para plataforma Web, trabalhar junto com nosso time de engenheiros na arquitetura e definição de soluções de alta escala e alta disponibilidade e utilizar as melhores práticas e tecnologias para escrever código que se orgulhará de ler amanhã. :)
<br/>

## Benefícios

- Plano de saúde
- Seguro de vida
- VR/VA
- FIFA, [Tower Fall](http://www.towerfall-game.com/) e [Overcooked](https://www.playstation.com/en-us/games/overcooked-ps4/) 😜 
<br/>

## Responsabilidades

- Pensar, contribuir no planejamento e desenvolver novas funcionalidades no Superplayer para Web.
- Garantir, junto com nosso time de designers, a melhor experiência em aplicações de música da plataforma.
- Utilizar as melhores práticas e tecnologias para escrever código em JavaScript, CSS e HTML.
- Trabalhar junto com nosso time de engenheiros na arquitetura e definição de soluções de alta escala e alta disponibilidade.
- Resolver problemas e defeitos no Superplayer para Web e cuidar para que eles nunca cheguem em ambiente de produção.
- Ajudar seus colegas nerds a resolver problemas complexos.
- Definir, junto com todo o time do Superplayer, os caminhos de nossos produtos e nosso processo de desenvolvimento.
<br/>

## Requisitos

- Paixão em escrever código e pela plataforma Web.
- Graduado(a) ou graduando(a) em alguma faculdade de informática: engenharia de software, ciências da computação, sistemas de informação, processamento de dados, análise de sistemas ou qualquer outra que ensine que 1 + 1 não é 2.
- Vivência com desenvolvimento de SPAs.
- Domínio de conceitos de OOP e conhecimento em conceitos de Functional Programming.
- ♡ Git.
- Habilidade de desenvolver aplicações do seu início ao fim (desde New File project até publicar em produção).
- Capacidade de planejar e desenvolver seu trabalho focando os objetivos estabelecidos em conjunto.
- Se sentir confortável com arquiteturas de desenvolvimento, tais como, MVP, MVC, MVVM, MVQC (MV Qualquer Coisa).
- Vivência com desenvolvimento em ambientes e times ágeis.
- Disponibilidade para trabalho em tempo integral.
<br/>

## Bônus

- Proficiência e/ou vontade de aprender frameworks e bibliotecas como React, Handlebars e Bootstrap.
- Vivência com mais de uma linguagem de programação (de preferência em diferentes plataformas).
- Gostar de resolver as coisas direto no Terminal.
- Experiência em escrever testes unitários e funcionais.
- Saber o que é Lean Startup e porque isso é importante mesmo sendo um desenvolvedor.
- Paixão por aprender e empreender.
- Tocar algum instrumento ou ser um rouxinol.
<br/>

## Contratação

CLT
<br/>

## Como se candidatar

Se você se interessou, manda seu currículo, LinkedIn e/ou GitHub para **jointheband@superplayer.fm** com o assunto **Front-end Developer**.

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
