### ISSUE TITLE
[Remoto] Front-end React na IT Lab Brasil

### ISSUE THREAD

**Issue by Nayara-leite** [frontendbr/vagas#4770]
> Vaga Remota durante a pandemia

## Nossa empresa

Utilizamos um modelo de operações baseado nas melhores práticas e metodologias de mercado, como CMMI, PMI, ITIL e RUP, porém com uma abordagem bastante prática e focada no equilíbrio entre controle efetivo, gestão de projetos e agilidade nos processos de desenvolvimento de software.

## Desenvolvedor Front-end React

Como será o dia a dia:
Atuará no desenvolvimento de uma plataforma para construção de um broker para negociação online, construindo a versão web e mobile.

## Requisitos

**Obrigatórios:**
React + Redux
Javascript e Typescript
CSS e SASS
Consumo de API REST + JWT

**Desejáveis:**
NextJs
NodeJs

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para vagas@itlab.com.br com seu CV anexado - enviar no assunto: Vaga Front-end React

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias uteis após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
