### ISSUE TITLE
[Remoto] Front-end na Joyjet Digital / França (HTML, CSS, WP, React)

### ISSUE THREAD

**Issue by dilsonalexandre** [frontendbr/vagas#4771]
#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
