### ISSUE TITLE
[Remoto] Pessoa Desenvolvedora na Intmed Software

### ISSUE THREAD

**Issue by glairtonsantos** [frontendbr/vagas#4773]
> Vaga Remota mesmo depois da pandemia

## Nossa empresa

A **Intmed Software** uma startup que se preocupa em desenvolver o cenário da saúde no Brasil. Dentro do ecossistema das healthtechs, nos destacamos pela nossa competência em pesquisa e inovação, trabalhando com frameworks ágeis e grande proximidade com os clientes, entregando valor de forma contínua e iterativa.

Nossos produtos já melhoram a realidade de 46 hospitais e 116 clínicas em vários locais do país. Um dos nossos principais produtos, o Medflow, já ajudou a realizar mais de 5 milhões de atendimentos, melhorando a conduta médica, reduzindo custos e principalmente garantindo o bem estar dos pacientes.

Assim como o Medflow, nossos outros produtos tem como objetivo principal garantir que o paciente tenha o cuidado e a atenção que ele merece. Seja no acompanhamento de uma gravidez, seja ao laudar um exame, seja na emergência ou no consultório médico. Fazemos tudo isso através de tecnologia, parcerias internacionais com outras startups e pessoas excelentes.

São essas pessoas que formam nossos times, cujo propósito principal é salvar vidas. Todos com expertise e amor por tecnologia. Estamos crescendo rapidamente e sempre procurando pessoas boas que se identifiquem com nossa cultura de proatividade e autonomia

## Descrição da vaga

- Ser responsável pela implementação técnica de funcionalidades
- Estimar esforços das atividades
- Garantir qualidade no código e testes
- Sugerir e implementar melhora nos processos técnicos
- Ajudar a identificar e realizar correções de bugs em produção
- Realizar consumo de API
- Realizar revisão de código de colegas (Pull Requests) e programação em par (pair programming) quando necessário

## Local

Remoto

## Requisitos

**Obrigatórios:**

- Ter disponibilidade para trabalhar de forma remota
- Ter pelo menos 2 anos de experiência em desenvolvimento (Angular ou/e Django) no mercado
- Ter experiência em Deploy (colocou ou ajudou a colocar alguma ferramenta em produção)
- Ter experiência com GIT
- Ter experiência com consumo de APIs

**Desejáveis:**

- Conhecimento Django/DRF
- Experiência com AWS
- Noção de SQL
- Experiência com PostgreSQL e/ou Oracle
- Conhecimento sobre Deploy Contínuo
- Experiência com React, React Native
- Conhecimento em metodologias ágeis

**Diferenciais:**
- Participação na comunidade open source
- Experiência na área da saúde
- Perfil Full Stack

## Benefícios

- Horário flexível;
- Auxílio para setup de home office
- Férias remuneradas e 13º salário
- Ajuda de custo para capacitação profissional
- Ajuda de custo para saúde e apoio psicológico
- Licença maternidade
- Folga no aniversário

## Contratação

PJ a combinar

## Processo Seletivo

- Análise de currículo
- Desafio Angular + consumo de API Django Rest Framework
- Entrevista

## Como se candidatar

Envie currículo e pretensão salarial para o e-mail **talentos@intmed.com.br**, com título **Seleção Pessoa Desenvolvedora - (Nome)**

Ah! Se você recebeu essa vaga por indicação de um amigo da Intmed, informe no e-mail o nome do(a) amigo(a).

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
