### ISSUE TITLE
[Remoto] Desenvolvedor Angular na Contratar.dev

### ISSUE THREAD

**Issue by contratar-dev** [frontendbr/vagas#4774]
## Descrição da vaga 
Essa vaga é um convite para você, desenvolvedor, se cadastrar na contratar.dev. Uma única candidatura é suficiente para que você participe de vários processos seletivos e seja encontrado por dezenas recrutadores.

  

**Tecnologias**

  

*   HTML
*   CSS / SCSS
*   Javascript / Typescript
*   Angular
## Local 
REMOTO 
## Como se candidatar 
Accesse a [Vaga de Desenvolvedor Angular](https://vaga.contratar.dev//apply/full/1fe671d8-ce1c-49da-94ad-948c8236742b) para se candidatar. 
## Labels 
* Remoto 
* Javascript 
* Angular 
* SCSS 
* CSS 
* TypeScript 
* HTML 
## Sobre a contratar.dev 
O contratar.dev é uma plataforma de recrutamento e seleção automatizada de Desenvolvedores. Ao se candidatar a uma vaga do contratar.dev, você estará participando automaticamente de dezenas de processos seletivos para vagas similares, aumentando em MUITO as suas chances de mudar de vida 😉

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
