### ISSUE TITLE
[100% 🌎 Remoto] Front-end Lead: UX, automação, DevOps, IaC, GitOps, produto SaaS prestes a ser lançado

### ISSUE THREAD

**Issue by jfoliveira** [frontendbr/vagas#4777]
> Vaga Remota - PERMANENTEMENTE REMOTA, Seja fera de onde cê quiser ser fera

## Nossa empresa

Estamos desenvolvimento plataforma SaaS - ainda não lançada - que almeja ser um produto inovador no segmento de DevOps, IaC e GitOps, tendo devs e sysadmins como público alvo, e com inúmeros desafios de usabilidade e performance.

Acreditamos que há alguma chance de brilharmos no cenário global e você terá a chance de participar dessa história desde o pré-lançamento. :-)
- Queremos influenciar a maneira que desenvolvedores de todo o mundo gerenciam aplicações e infraestrutura na nuvem em 2025.
- Queremos que a galera faça deploy de dentro do busão indo pro trampo se algum dia o mundo ainda quiser devs nos escritórios e não apenas ralando remoto.
- Queremos que o nômade digital viajando pela América do Sul e alterando um cronjob ou variáveis de ambiente, enquanto o busão dele passa por um túnel na Bolívia, onde nem 3G existe, e por isso testaremos nossa app web com conexão 2G, pra garantir performance mesmo em cenários mais hostis.

> Buscamos alguém que queira se envolver em desafios ambiciosos como esses.

Nossa equipe é pequena, bem humorada e altamente qualificada, com trajetória de entregas em experiências anteriores, tendo cada fundador o mínimo de 10 anos de atuação no setor de tecnologia e desenvolvimento de software.

## Descrição da vaga

Atuar diretamente com os fundadores que criaram e implementaram esse produto do zero, da idealização ao pré-beta (fase atual) em menos de 2 (dois) anos.

Buscamos pessoa empreendedora, com iniciativa, com foco em resultados, que busca crescimento pessoal e profissional, apaixonada por desenvolvimento front-end, e os desafios de oferecer uma interface amigável que simplifique a vida dos usuários.

Se você tem bom conhecimento de arquitetura de software e excelente compreensão das interações entre front-end e back-end, com capacidade e interesse em atuar e influenciar o futuro de um produto inovador, essa pode ser uma boa oportunidade.

Se você adora entrar em discussões que falam mal de linguagem de programação A ou B, ou em briguinhas de framework X vs Y, e crê que a tech stack que você utiliza é a única que importa no mercado, **essa oportunidade não é pra você. Sorry!**

Utilizamos múltiplas linguages de programação e frameworks, e nosso público alvo utiliza inúmeras stacks, portanto nosso produto se integrará com diversas tecnologias, por isso preferimos ter em nossa equipe profissionais que tem empatia com as decisões tecnológicas tomadas por outros desenvolvedores e que se sentem motivados em resolver problemas do mundo real e não tem tempo a perder com discussões improfícuas.

Trabalho inicial com remuneração por hora/free-lancer com possibilidade de demanda contínua caso o trabalho seja bem executado. Exigência de qualidade das entregas é alta. Não há exigência de horário ou local de trabalho.

## Local

Não há exigência de horário ou local de trabalho. Nossa equipe já era remota mesmo antes da pandemia.
Nos comunicamos de maneira assíncrona via `Slack` e ferramentas de gestão de projetos.

## Requisitos

**Essencial:**
- Interesse em contribuir para tornar a vida dos devs mais simples, feliz e produtiva do que ela é em 2021;
- Ter ao menos 20 (vinte) horas disponíveis semanalmente para atuação como free-lancer remoto
- Cê manja muito de desenvolvimento web. E espero que cê manje bem mais do que eu
- Conhecer muito bem arquitetura de frontend, se possível conhecer bem `React.js`:
  - Se você é fera em `Vue.js` ou outro framework será bem vindo também. Não precisa morrer de amores pelo `React`, mas é o que tem pra hoje e vamos evoluir sobre a base atual do produto e mudar framework não é uma opção nos próximos 12 meses, e não consideraremos perder tempo em análises de substituição de tecnologia base antes do produto se tornar rentável e conseguirmos ter receita pare re-investir;
- Experiência com detecção e correção de erros em apps web
- Desejo de atuar em plataforma global de DevOps e automação que será utilizada por seus colegas de profissão :-)

**Desejáveis:**
- Experiência com Design System e organização de galeria de componentes
- Vivência com Storybook
- Vivência com TypeScript
- Automação de testes no front-end

**Diferenciais:**
- Ser ou ter sido responsável por manter aplicação web em produção (em qualquer tecnologia), reagindo a bugs e instabilidades, com boa vivência com ciclo de vida de desenvolvimento de software e deployment de aplicações em produção;
- Ter boa comunicação e desejo de influenciar outros desenvolvedores da equipe na adoção de boas práticas de desenvolvimento de software;
- Ser, ou desejar se tornar, uma referência no desenvolvimento front-end
- Almejar ter em seu portfólio uma plataforma global inovadora que será lançada simultaneamente em múltiplos idiomas e tem devs como público alvo;

## Benefícios
- Liberdade de trabalhar na hora que cê quiser de onde cê quiser. Desde que entregue as tarefas com as quais cê se comprometeu, tudo certo.
- Equipe pequena, altamente técnica, bem humorada, e principalmente obstinada e orientada a resultados. Sem perda de tempo em discussões inúteis. A gente ama o que faz e foca na entrega de resultados.

## Contratação

PJ, por hora. Valor a combinar

### Sobre o processo seletivo:

1. Um bate papo via texto no LinkedIn, cerca de 15 minutos
2. Uma conversa ao telefone, entre 30 e 60 minutos
3. Envio de um teste técnico de programação que muitos já conseguiram resolver em menos de 4 horas. No entanto a pessoa terá 24 horas para entregar uma solução
4. Ligação para revisão do teste, cerca de 15 minutos.
5. Se pessoa foi aprovada já passamos a primeira tarefa, remunerada

## Como se candidatar

Por favor candidate-se via LinkedIn: https://www.linkedin.com/jobs/view/2528911076/

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias úteis após iniciado o processo seletivo.

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
