### ISSUE TITLE
[Remoto] Front-end Developer na VipCommerce(Magazine Luiza)

### ISSUE THREAD

**Issue by Laisiemma** [frontendbr/vagas#4780]
[Remoto] Front-End Developer na VipCommerce (Magazine Luiza)

> Vaga Remota 

## Nossa empresa

A VipCommerce, através de uma plataforma white-label e um modelo logístico criados exclusivamente para o varejo alimentar, permite aos varejistas integrarem um novo canal online à operação já existente com rapidez e eficiência.
Empresa de crescimento acelerado, que preza pela qualidade de seus produtos e por um time colaborativo. 
Recentemente adquirida pela Magazine Luiza

## Descrição da vaga

Você irá desenvolver front-end Web e Mobile utilizando Angular e Ionic. 

## Local

[Remoto]

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Node
- 2 anos de experiência com mongodb e express

**Desejáveis:**
- ANGULAR 2+ Javascript, teste unitário, HTML, CSS, Typescript; 
-Essencial Trabalhar em Ambiente Linux

**Diferenciais:**
- ANGULAR 8+; IONIC, Consumir API Rest; Flutter;

## Benefícios

- Plano de saúde
- Plano Odontológico
- VR de R$ 22,70/dia
- Auxílio home office (R$300,00 a partir do segundo mês)
- ...

## Contratação

CLT

## Como se candidatar

Por favor envie um email para lais.i@redpillrh.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 20 dias após cada processo.

#### Alocação

- Remoto

#### Regime
- CLT

#### Nível

- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
