### ISSUE TITLE
[São Paulo] Front-end Developer na Infobase

### ISSUE THREAD

**Issue by rqsakai** [frontendbr/vagas#4783]
Descrição da vaga

Infobase, a empresa que ganhou o premio de Rising Stars da Adobe em 2020 está com vagas permanentes para desenvolvedores Magento Frointend e Frontend Junior, Pleno e Senior em São Paulo.

!IMPORTANT Se você é um bom proramador de Frontend e não conhece o magento ou não se acha apto o suficiente, venha aprender com agente no dia a dia do trabalho, estamos dispostos a te treinar.

Estamos oferecendo como benefício o treinamento da plataforma Magento e é claro a formação interna na empresa em outros recursos como infraestrutura, arquitetura de software, etc...

Somos muito exigentes com a qualidade do trabalho, e o salário será proposto de acordo com o seu desempenho nas estrevistas. (A média pode variar entre 3k [Jr] e 12k [Sr])

Modelo de trabalho

- Hibrido São Paulo/SP - Somenta após fim da Pandemia
- Remoto
Benefícios

- Plano de saúde
- Treinamentos internos
Diferenciais

- Horario flexivel baseado em entregas
- BYOD (Bring your own device) - trabalhe com a sua máquina
- Linux people - não usamos windows somente linux
- Ambiente descontraído
- Treinamentos com os seniors
Requisitos

Obrigatórios:
- Experiência com:
	- HTML
	- jQuery
	- ES6
	- LESS
	- GIT
	- Conhecimento de Design patterns de frontend
- Experiencia com Magento
	- Aceitamos desenvolvedores frontend sem experiencia com Magento para treinamento

Desejáveis:
- Conhecimentos em knockout
- Conhecimentos em react
- Inglês
- Experiencia com Magento Cloud
- Conhecimento de Metodologias Ageis (Agile)

Diferenciais:
- Conhecimento em arquitetura de aplicações frontend
Contratação

- PJ
- Sócio Quotista
- CLT

OBS: O valor proposto pode variar de acordo com o modelo de contratação desejado

Nossa empresa

A Infobase é uma empresa com mais de 22 anos de mercado e quase 500 colaboradores.

Hoje trabalhamos com projetos globais de grandes corporações, o nosso principal projeto foi implementado em 65 países com mais de 240 sites e 600 lojas. e temos muitos mais chegando.

Como se candidatar

Por favor envie um email para curriculos_sp@infobase.com.br com seu CV anexado - enviar no assunto: Vaga Frontend/Magento

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
