### ISSUE TITLE
[Remoto] Desenvolvedor Front end React native na uCondo

### ISSUE THREAD

**Issue by NerdProgramador-com-br** [frontendbr/vagas#4785]
## Descrição da vaga 
**Desenvolvedor React Native - Sênior**

Vagas abertas em: Curitiba(PR) ou trabalho remoto

  

A uCondo existe porque a comunicação dos condomínios é precária e desorganizada, administradoras de condomínios possuem processos burocráticos, caros e demorados. Nosso propósito é proporcionar economia e comodidade para administradoras, síndicos e moradores, tudo isso alinhado ao nosso sonho grande de tornar todos os condomínios inteligentes.

  

Somos apaixonados por tecnologia e acreditamos que o produto possui um papel fundamental nessa jornada! Para chegarmos lá, nossa plataforma precisa estar em constante evolução atendendo a todas as necessidades dos clientes de forma fácil, prática e segura. Com isso, seu objetivo será projetar e desenvolver soluções escaláveis colaborando com as demais pessoas da equipe.

  

Você fará parte da Squad de Apps como desenvolvedor frontend e irá trabalhar na migração do nosso aplicativo para a tecnologia React Native.

  

**Resumindo, sua missão no dia a dia é:**

● Definir do zero uma arquitetura para o app que utilize as melhores práticas de mercado e que atenda a todos os requisitos negociais

●Recriar todas as telas do aplicativo atual em React Native fazendo pequenas melhorias visuais

● Implementar esteira CI/CD para atualizações as do app

● Desenvolver códigos limpos, de fácil entendimento e manutenção

● Ser pró-ativo visando diminuir a demanda de suporte, seja em melhorias nos processos, software e/ou na vida do cliente

● Co-criar a melhor solução diante das dores e sintomas declarados pelo cliente

  

Requisitos:

● Sólidos conhecimentos em desenvolvimento mobile (Android e iOS)

● Conhecimentos avançados em React Native e React Js

● Conhecimento total dos ciclos de um aplicativo (concepção, desenvolvimento e publicação nas stores)

● Sólidos conhecimentos em Git

● Gostar de programar e resolver problemas

● Ser um amante de tecnologia e estar sempre atualizado com as novidades do mercado

● Ter pró atividade em trazer ideias novas e ao mesmo tempo ter um senso de dono do negócio

● Ser didata, possuindo facilidade em compartilhar os conhecimentos Diferenciais:

● Experiência na criação de aplicativos empresariais do zero

● Conhecimentos em tecnologias como Flutter, Angular, Ionic, VueJs, Dart, Swift, Kotlin, Java, C# O que eu vou aprender com essa experiência?

● Utilização das melhores e mais recentes tecnologias de desenvolvimento do mercado

● Conhecimento e prática sobre administração de condomínios (lhe daremos um curso com certificado e tudo mais :D)

● Desenvolvimento de habilidades como resiliência, objetividade, resolução de problemas, rapidez de raciocínio e empatia

● Aprender e aplicar metodologias de empresas em crescimento acelerado, afinal, você vivenciará muitas mudanças e de forma rápida. O universo de Saas, métricas, startup será seu novo mundo

  

**Salários e Benefícios**

● Salário Base: Alinharemos de acordo com experiência - nos envie sua pretensão salarial junto com seu cv :)

● Vale Refeição: R$ 396,00/mês - sem descontos

● Plano Odontológico - sem descontos

● Plano de Saúde - sem descontos

● Seguro de Vida - sem descontos

● Vale Transporte

● Horário de trabalho: segunda à sexta das 09:00h às 18:00h

● Ambiente casual em Curitiba, você pode usar jeans e tênis para trabalhar, no dress code

● Ambiente agradável com puffs, livros, café e chá à vontade, videogame

● Estamos trabalhando de casa neste período de isolamento social, Então é provável que continuemos assim por mais alguns meses.

  

Você se enxerga dentro deste ambiente e deseja fazer parte do time uCondo?

Nós queremos te conhecer =)
## Salário 
R$6000 - R$10000 
## Local 
REMOTO 
## Como se candidatar 
Accesse a [Vaga de Desenvolvedor Front end React native](https://vaga.contratar.dev/apply/full/36068c80-a21c-4f5a-85c8-6f70085062be) para se candidatar. 
## Labels 
* Remoto 
* Ionic 
* Flutter 
* React 
* Kotlin 
* Dart 
* C# 
* Angular 
* Swift 
* Java 
* Git 
## Sobre a contratar.dev 
O contratar.dev é uma plataforma de recrutamento e seleção automatizada de Desenvolvedores. Ao se candidatar a uma vaga do contratar.dev, você estará participando automaticamente de dezenas de processos seletivos para vagas similares, aumentando em MUITO as suas chances de mudar de vida 😉

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
