### ISSUE TITLE
[São Paulo] Front-end Developer na Olos

### ISSUE THREAD

**Issue by spolidorio** [frontendbr/vagas#4791]
<p align="center">
  <a href="https://www.olos.com.br/">
      <img src="https://www.olos.com.br/wp-content/uploads/2020/02/olos_logo_branco.png" alt="Olos" width="300px"/>
  </a>
</p>

> Vaga Remota durante a pandemia

## A Olos

A Olos Tecnologia nasceu em 2010 com a visão de criar uma plataforma de atendimento ao cliente para o mercado de relacionamento entre empresas e clientes e contact centers. Atualmente, somos a principal e mais premiada plataforma de contatos ativos do Brasil, além de estar conquistando um importante espaço no segmento de atendimento Omnichannel.

Uma empresa brasileira multinacional já presente em 8 países.

## Descrição da vaga

- Desenvolvimento de interface da plataforma Olos: a solução Olos está em constante evolução, dê vida as novas funcionalidades do Olos desenvolvendo interfaces únicas e inovadoras.
- Planejamento UX/CX: acompanhe todo o processo criativo para criação de funcionalidades da plataforma.
- Novos canais: Desenvolva interface para novos canais de comunicação de nossos clientes.
- Documentação: formalize e passe conhecimento aos seus colegas e clientes.

## Local

Remoto ou Presencial Escritório, [São Paulo], [São Paulo], [Casa Verde]

## Requisitos

**Obrigatórios:**
- HTML5 / CSS3
- JavaScript / ES6
- React / Redux
- Webpack
- Node / NPM
- Preprocessors (Stylus, Less, Sass)
- Task managers (Gulp / Grunt)
- Controle de versão (GIT / SVN)

**Diferenciais:**
- GraphQL
- Material Design

## Benefícios

- Benefícios comuns como VR, VT e Convênio Médico.
- Benefício de viagem de descanso durante a férias: https://pinx.travel/
- Comunicação direta e fluida entre todos os colaboradores.
- Autonomia.
- Trabalho remoto/home office.

**Diferenciais:**
- Programa de inovação (crie o que quiser, seja dono do seu projeto e dispute com seus colegas uma premiação que pode chegar até R$70.000,00).

## Contratação

CLT 

## Como se candidatar

Por favor envie um email para giovanni.sabino@olos.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Developer

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- Estágio

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by felipemimoura** [comment]
Currículo Enviado.
