### ISSUE TITLE
[Remoto] Sênior Front-end Developer na HANZO

### ISSUE THREAD

**Issue by crispossa** [frontendbr/vagas#4792]
### Sobre a HANZO

Somos um time de pessoas apaixonadas por **tecnologia** e **inovação**. Acreditamos no potencial da **tecnologia** para trazer solução e capacitar empresas e indivíduos em uma verdadeira **transformação digital**.
A **HANZO** oferece soluções de **e-commerce**, **fidelidade**, **promoções** e **pagamentos** em uma plataforma **Saas**. Além disso, apoiamos nossos clientes em desenvolvimentos sob-demanda nos seus projetos de **transformação digital**.
Somos responsáveis pelo programa de incentivos global Surpreenda, da **Mastercard** e por várias soluções na **Petz**, só para citar 2 clientes.
A **HANZO** é certificada PCI DSS (certificação exigida para fintechs e relacionadas) e levamos a sério o **alto padrão** em tudo que tocamos.
Ah! Somos **acelerados** pela própria **Mastercard**!

### Sobre a vaga

Estamos atualmente buscando uma pessoa desenvolvedor(a) Front-end Sênior para compor o nosso time de estrelas. Procuramos uma pessoa com alto senso crítico, comprometimento e que não tenha medo de errar.
Você vai trabalhar ao lado de uma equipe top que entrega soluções para um grande player de e-commerce do segmento Pet, desenvolvendo soluções que vão impactar milhões de donos e pais de Pets no Brasil e no mundo.

### Local

Do seu quarto, seu sofá ou do topo de uma montanha (que tenha internet claro), ou seja, de onde você quiser. A vaga é 100% remota.

### Requisitos

**Obrigatórios:**

- Experiência comprovada com ReactJS
- Experiência com HTML/CSS/JS
- Experiência com ES6
- Experiência com pré processadores CSS, de pref SASS

**Desejáveis:**

- Experiência com Jest, Testing Library, CyPress
- Experiência prévia com PWA

### Contratação

PJ ou CLT, a combinar.

### Como se candidatar

Se você acredita que a vaga tem tudo a ver com você e o seu momento, envia um e-mail para cristiano@hanzo.com.br com o seu LinkedIn, CV e/ou GitHub para continuarmos.

### Tempo médio de feedbacks

Geralmente respondemos no dia seguinte ao recebimento do e-mail com CV.

### Labels

**Alocação**

- Remoto

**Regime**

- CLT
- PJ

**Nível**

- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
