### ISSUE TITLE
[Home Office] Front-end Developer na Performa_It

### ISSUE THREAD

**Issue by TacianySouza** [frontendbr/vagas#4797]
Desenvolvedor(a) Front End - Pleno/Sênior 

Estamos à procura de um desenvolvedor Web front-end motivado a combinar a arte do design com a arte da programação. Que seja apaixonado por novos desafios, com disposição de descobrir e aprender todos os dias; que contribua com o time; que atue com autonomia, usando a liberdade para opinar em processos e questões relacionadas ao cliente quando for preciso.  

O que você vai fazer: 
Incluir a conversão dos wireframes de design da UI/UX para o código real que produzirá elementos visuais do aplicativo. Você trabalhará com o designer e fazendo a ponte entre o design gráfico e a implementação técnica, assumindo um papel ativo de ambos os lados e definindo a aparência e o funcionamento do aplicativo.   

Suas principais responsabilidades: 
Desenvolver recursos visuais da aplicação; 
Criar códigos e bibliotecas reutilizáveis; 
Garantir a viabilidade técnica dos designs de UI/UX; 
Otimizar o aplicativo para velocidade e escalabilidade máximas; 
Certificar de que toda a entrada do usuário seja validada antes de enviar para o back-end; 
Colaborar com outros membros da equipe e partes interessadas. 

Você precisa ter: 
Proficiente entendimento das ferramentas de versão de código como Git; 
Proficiente conhecimento de HTML5 e CSS3; 
Compreensão básica das plataformas de pré-processamento CSS do lado do servidor como LESS e SASS; 
Proficiente entendimento de scripts do lado do cliente e estruturas JavaScript;
Bom entendimento de Angular 2+; 
Bom entendimento do processamento de solicitações assíncronas.   

Você vai se destacar se tiver: 
Entendimento dos problemas de compatibilidade entre navegadores e formas de contorná-los; 
Conhecimento básico das ferramentas de criação de imagens, para poder cortar, redimensionar ou executar pequenos ajustes em uma imagem. A familiaridade com ferramentas como Photoshop é uma vantagem; 
Habilidades para apoiar a equipe de UI/UX em pequenos ajustes quando necessário; 
Conhecimento em ferramentas de teste automatizados (Selenium/Jasmine).   

O que você pode aprender com a gente: 
Web assembly 
PWA 
Web components 
Firebase 
GraphQL 
Estrutura de microfront-end    

Nós te oferecemos: 
Jornada de Trabalho: 40h semanais 😍
Convênio Médico (sem descontos)🩺
Vale Refeição/Ajuda de custo 🍽
Descanso Remunerado 🏝
Bônus Anual  💸
Horário flexível 😎  

Aqui você vivenciará uma cultura de desenvolvimento, dinâmico, colaborativo, gestão horizontal e com um ótimo relacionamento entre colegas e clientes. 

E-mail para envio de CV: taciany.souza@performait.com
Assunto: Dev Front-end

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
