### ISSUE TITLE
[ANYWHERE OFFICE] Front-End Developer [Angular] na Code7

### ISSUE THREAD

**Issue by marcelaggm** [frontendbr/vagas#4798]
Quer trabalhar em uma empresa TECH que se destaca em seu segmento de negócio, não para de inovar em suas soluções utilizando tecnologia de ponta e com uma equipe incrível? ​Venha ser um(a) Coder! #BeACoder

Para essa vaga você atuara com o nosso produto Omni Channel, que é 100% on Cloud!  

Atividades
Analisar a viabilidade de demandas apresentadas pelos usuários a serem implementadas nos programas/sistemas existentes;
Participar de reuniões técnicas e com usuários para análise e levantamento de requisitos;
Desenvolver, testar e implantar programas e sistemas customizados;
Providenciar a documentação funcional e técnica dos programas e sistemas customizados;
Pesquisar, analisar, sugerir e contribuir na implementação de novas tecnologias associadas com aplicações corporativas;
Projetar, construir e otimizar interfaces web;
Implementar layouts intuitivos e responsivos utilizando princípios ergonômicos de usabilidade.

Requisitos
Ensino Superior completo ou em andamento (Ciência da Computação, Engenharia da Computação, Sistemas de Informação ou graduação equivalente em TI);
Experiência com desenvolvimento em Angular;
Conhecimento em HTML5, Angular, CSS3, Javascript, Saas.

Contratação CLT 
Benefícios: VA/VR, Plano de Saúde, Plano Odontológico, Auxilio Home Office.

Se inscreva:  https://code7.com/beacoder/desenvolvedor-frontend-angular/

Conheça mais sobre nós:   https://youtu.be/QV3dwaP5hbs

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by marcelaggm** [comment]
Devs e Devas a vaga está em abertas!!!
São 6 vagas.
Seja um Coder!!!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
