### ISSUE TITLE
[São Paulo] Estágio - Javascript & Friends

### ISSUE THREAD

**Issue by rturk** [frontendbr/vagas#48]
## Descrição da vaga

Estágio para trabalhar com projeto de Aplicativo incluindo o FrontEnd + App + Backend. 
Todo o projeto criado com Javascript & friends (NodeJS, React, Relay). 

Vale reforçar que o escopo é para trabalhar em um único App, ou seja dá para explorar bastante novas tecnologias e garantir um código de qualidade, o qual você irá se orgulhar e poderá acrescentar no seu portfolio.
## Local

Escritório, São Paulo - Zona Sul
http://plug.co/bkln
## Benefícios
- Ambiente legal para trabalhar 
- Sem frescuras para horário de trabalho.
- Localizado na Plugg Coworking (zona sul de SP)
- Sim nós sabemos que você tem provas e vai precisar de alguma flexibilidade com isto
## Requisitos

**Obrigatórios:**
- Noções em Javascript
- Estar cursando cursos relacionados (Informática, Ciencias da Computação, etc..)
- Muita vontade de aprender

**Desejáveis:**
- Experiência com Node
- Experiência com Mongodb 
- Alguma noção de Design (por favor!)
- Relay
- React Native
- Machine Learning
## Contratação

Estágio
## Nossa empresa

A Entria (https://www.entria.com.br) é uma empresa focada em Apps de alta complexidade. É liderada por um ex-Amazon.com com experiência no Brasil e no Exterior. Somos ambiciosos e estamos crescendo muito.
## Como se candidatar

Por favor envie um email para vagas@entria.com.br com seu CV anexado - enviar no assunto: Eu sou o seu candidato(a) me contrate porque eu sou o cara!

**Comment by LFeh** [comment]
Boa sorte @rturk

**Comment by eduardojmatos** [comment]
@rturk aqui também, se não estiverem procurando ainda, avisa a gente!

**Comment by rturk** [comment]
@eduardojmatos estamos sempre contratando! Se pudesse pinava e deixava esta issue no topo!

**Comment by willrsousa94** [comment]
Ainda estão contratando?

**Comment by rturk** [comment]
@willrsousa94 SIM. Temos 10 posições de full-stack & Friends abertas

**Comment by mtmr0x** [comment]
@rturk a fim de manutenção, preciso ver se a vaga ainda esta aberta, para fecharmos ou mantermos aqui. Precisamos fazer isso a cada 15 dias para garantir que candidatos não mandem emails para vagas ja preenchidas

**Comment by X-X-Xavito** [comment]
Ainda tem vaga aberta?

**Comment by rturk** [comment]
@X-X-Xavito sim!

**Comment by rturk** [comment]
@X-X-Xavito atualizamos os detalhes aqui https://github.com/entria/jobs

**Comment by X-X-Xavito** [comment]
Enviado!

**Comment by brunooomelo** [comment]
Enviado! 

Obs.: É necessario fazer o teste antes de mandar o email?

**Comment by rturk** [comment]
@brunooomelo o email serve mesmo para anotarmos seu github e mandar o link para o teste!

**Comment by RafaelaCassianoCampos** [comment]
@rturk a vaga ainda está aberta?

**Comment by jgcmarins** [comment]
Galera, ainda estamos contratando. São 10 vagas pra trabalhar na **Entria**!
Qualquer dúvida, me procurem no Slack do React Brasil: http://react-brasil-slack.herokuapp.com/ @jgcmarins

**Comment by gkal19** [comment]
Adorei a vaga, porém sou de outro estado 😢

**Comment by jgcmarins** [comment]
@gkal19 manda um ping pra mim lá no Slack do React Brasil, por favor :)

**Comment by vinyguedess** [comment]
@mateusguedess

**Comment by LFeh** [comment]
Aberto ainda?
