### ISSUE TITLE
[São Paulo] Front-End Developer na eokoe/AppCívico

### ISSUE THREAD

**Issue by robsonsobral** [frontendbr/vagas#480]
## Descrição da vaga

Procuramos (mais uma) pessoa desenvolvedora front-end, mas não apenas para programar. Precisamos de alguém que não só programe bem, como também seja organizada, se importe com a legibilidade de seu código e com a colaboração de seus colegas e se expresse com clareza.

Não somos uma fábrica de software. Oferecemos o produto completo, desde o projeto. Aqui, quem desenvolve também colabora no processo criativo: discutindo, rabiscando, antecipando dificuldades e sugerindo soluções, **antes** de colocar o código no repositório.

Além de trabalhar nos produtos da Eokoe, você terá a oportunidade de atuar em projetos com impacto social positivo.

## Local

(geralmente) no escritório, no bairro do Paraíso, em São Paulo

#### Diferenciais

- horário flexível
- no dress code
- chefia que já desenvolveu, portanto ciente do esforço necessário

## Requisitos

**Obrigatórios:**

- _vanilla_ Javascript
- _vanilla_ CSS
- integração com API
- _responsive web_
- noção de segurança em navegadores
- atenção à performance
- inglês para leitura
- controle de versão

**Desejáveis:**

- compulsão por testes
- desenvolvimento de PWA
- familiaridade com Linux ou MacOS
- noções sobre acessibilidade
- integração contínua
- automatização utilizando o NPM
- Static Site Generators
- Git
- alguma familiaridade com o WordPress (para ajudar a enterrar projetos legados)
- alguma familiaridade com PHP (para ajudar a enterrar projetos legados)
- Agile
- saber o que é DNS, HTTP e TLS
- inglês para conversação

**Diferenciais:**

- paz de espírito

## Contratação

PJ por valor a combinar e por prazo indeterminado

## Nossa empresa

Aqui na **eokoe** acreditamos que ótimos softwares saem das mentes de bons times, não apenas por ótimos desenvolvedores. Precisamos de um time variado. Queremos que você traga suas cores, formas e ideias para encontrarmos soluções inovadoras, de um jeito que não somos capazes sozinhos. Por isso, queremos aumentar a participação de mulheres em nosso time.

## Como se candidatar

Por favor envie um email para trampos(at)eokoe.com com seu CV anexado - enviar no assunto: Vaga Front-End

**Comment by ygorlazaro** [comment]
Muito legal, pena ser em São Paulo 😢

**Comment by robsonsobral** [comment]
@diogomoretti , por favor, adicione as tags "Junior" e "Pleno". Muito obrigado.

**Comment by robsonsobral** [comment]
Ainda procurando, pessoal.

**Comment by rafaelassumpcao** [comment]
A vaga é exclusivamente para o gênero feminino? Ou homens tbm podem se candidatar?

**Comment by robsonsobral** [comment]
@rafaelassumpcao , a preferência é por mulheres, porque já há homem demais na empresa.

**Comment by rafaelassumpcao** [comment]
Ah ok, obrigado. Excelente iniciativa em movimentar a diversidade na empresa.

**Comment by Edipoesn** [comment]
@robsonsobral,

Estou super disposto. Quando liberar para homens, please! Keep me up.

**Comment by robsonsobral** [comment]
@Edipoesn , envie seus dados. Lerei com atenção.

**Comment by robsonsobral** [comment]
Duas contratações. Uma por aqui. Estão em período de experiência.

Obrigado, gente.

**Comment by LFeh** [comment]
Sensacional 👏👏👏
