### ISSUE TITLE
[Remoto] Front-end Developer Sênior no Grupo Afya

### ISSUE THREAD

**Issue by BrunaAzevedo2020** [frontendbr/vagas#4801]
Afya é o Maior Grupo de Educação e Saúde do País, reconhecido internacionalmente (IPO na Nasdaq) e em pleno crescimento. Temos em nosso grupo algumas das healthtechs referência no mercado, entre elas a ICLINIC, MEDCEL, MEDICINAE, MEDPHONE e PEBMED.

Para essa oportunidade buscamos você que é fera em Desenvolvimento Front-end sênior (react.js).

ESPONSABILIDADES E ATRIBUIÇÕES

> Desenvolver aplicações web por meio das linguagens de programação utilizadas nas soluções digitais da empresa, concretizando escopos de projeto prototipados pela área de Design ou de negócios, compondo os times de desenvolvimento na construção e manutenção dos sistemas;

- Implementando soluções de front-end, dando suporte aos usuários das aplicações visando o cumprimento das necessidades operacionais dos clientes internos e externos da empresa como um todo.

REQUISITOS E QUALIFICAÇÕES
Perfil da pessoa que buscamos:

- Lógica de programação;

- Versionamento de código React, Usabilidade, Experiência do Usuário.

Benefícios:

Vale Refeição ou Vale Alimentação
Assistência Médica
Convênio Odontológico
Seguro de Vida
Gympass
Vale Transporte
Participação em Lucros e Resultados (PLR)
Acesso a cursos gratuitos através da plataforma da UCA - Universidade Corporativa Afya
Auxílio cursos.

Regime de contratação: CLT
Local de trabalho: Home-office
Horário de trabalho: Flexível

Cadastre agora mesmo em nosso portal: https://afya.gupy.io/jobs/801973?jobBoardSource=gupy_public_page
Ou encaminhe seu currículo ou perfil do LinkedIn pra gente com seu telefone para contato e e-mail: afyaoportunidades@yahoo.com

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
