### ISSUE TITLE
[Remoto] Front-end Vue.js Developer na Before TI

### ISSUE THREAD

**Issue by Victorhcr-pot** [frontendbr/vagas#4802]
Já pensou em trabalhar com o propósito de fazer a diferença em projetos incríveis, em grande escala, para empresas multinacionais, por meio da tecnologia? Fazer parte de uma empresa que foca no seu desenvolvimento profissional e pessoal? Trabalhar com times de desenvolvimento completos, tecnologias com interface em inteligência artificial e oportunidade de grandes desafios? Se a resposta é SIM, confere essa vaga aqui:

Desenvolvedor(a) Front-end

Responsabilidades:

Desenvolver o código de front end e interface do programa de acordo com o protótipo desenhado, utilizando código limpo e as boas práticas de programação e facilitar a interação e melhorar a experiência do cliente cumprindo o prazo estabelecido para atividade, evitando erros em produção.

Requisitos:

JavaScript
Git
Commit semântico
Vuejs
Vuex
Sass
Metodologias css - CSSOO, BEM, SMACSS
Vue mixins, plugins.
Comunicação com api rest.
Monorepo + Yarn workspaces 
Clean code

Perfil:
Pleno
Sênior

Você pode saber mais sobre nós no site https://before.com.br/
Caso queira se candidatar imediatamente, acesse: https://jobs.kenoby.com/before

**Comment by mateusavila** [comment]
Qual é o range da vaga?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
