### ISSUE TITLE
[Remoto] Software Developer III {Angular} na eSales

### ISSUE THREAD

**Issue by NerdProgramador-com-br** [frontendbr/vagas#4806]
### RESPONSABILIDADES E ATRIBUIÇÕES

*   Desenvolver soluções tecnológicas, garantindo funcionalidade, manutenibilidade, velocidade por meio das boas práticas de desenvolvimento de sistemas.
*   Testar suas soluções, preferencialmente a partir de práticas automatizadas e/ou codificadas.
*   Garantir que as soluções técnicas estejam alinhadas a estratégia do negócio/produto e as diretrizes da Arquitetura Corporativa.
*   Entender os OKRs e iniciativas relacionadas ao produto.
*   Entender o impacto das soluções que o time desenvolve no usuário final.
*   Ajudar o time no desenho de soluções com arquitetura evolutiva.
*   Investigar constantemente novas tecnologias e formas de trabalho, discutindo a adoção pela organização como um todo a partir do debate/experimentação junto à Arquitetura Corporativa.
*   Colaborar com a evolução das skills técnicas do time e esforços de melhoria contínua que impactam os demais times.
*   Monitorar o desempenho e performance dos produtos/sistemas em que seu time é responsável.
*   Estar atendo a oportunidades e eventuais problemas, agindo com rapidez e eficácia, desenvolvendo soluções de forma preventiva.
*   Auxiliar na orientação dos desenvolvedores mais novos ou menos seniores.

  

### REQUISITOS E QUALIFICAÇÕES

**Requisitos**

*   Experiência em desenvolvimento Angular, Spring Framework, Java, React, Git, Docker, PostgreSQL.
*   Habilidade em desenvolver e implementar APIs.
*   Embasamento teórico, habilidade e preocupação com a excelência técnica e boas práticas de desenvolvimento (DDD, TDD, arquitetura distribuída, design de código, paradigmas, pipeline CI/CD, etc.).
*   Familiaridade com metodologias ágeis.
*   Pragmatismo para resolução de problemas.

  

**Será um diferencial se você tiver as seguintes vivências:**

*   Participação ativa em comunidades de Tecnologia (palestras, meetups, eventos, tech talks, blogs) como forma de obter e disseminar conhecimento.
*   Conhecimentos em algumas das tecnologias a seguir: Angular, Java Spring Framework, .NET Core, Swagger, RabbitMQ, PostgreSQL, ELK, Cloud, Jenkins, Selenium, RunDesk, Redis, SonarQube, Kubernetes, Mobile Native, Liquibase, etc.
*   Certificações em alguma das linguagens dos requisitos ou dos diferenciais acima.
*   Conhecimento em configuração de infraestrutura: Chef, Puppet, Ansible, Terraform

  

### INFORMAÇÕES ADICIONAIS

**O que nos torna um ótimo lugar para trabalhar?**

Horário flexível;

Cultura de feedback 1:1 e PDI Contínuo;

Possibilidade de atuar de forma remota;

Auxílio para Graduação, Pós-Graduação e demais especializações;

Convênio com Alura (a eSales auxilia na metade da mensalidade); 

Ginástica Laboral online;

Day Off de aniversário;

No dress code.

Benefícios flexíveis em apenas um cartão! ✨

  

**Demais benefícios:**

Vale Refeição/ Alimentação

Vale Cultura

Auxílio Home Office mensal

Plano de Saúde (Sem desconto de mensalidade no plano básico)

Plano Odontológico Metlife (Cobertura nacional, sem coparticipação, incluindo procedimentos estéticos)

Seguro de Vida Metlife

Convênio academia TotalPass (Incluindo as academias SmartFit, BioRitmo e NÓS)

Convênio ZenKlub e New Value

Vale Transporte de acordo com a necessidade
## Local 
REMOTO 
## Como se candidatar 
Accesse a [Vaga de Software Developer III {Angular}](https://vaga.contratar.dev/apply/full/0c16014f-c218-4a9c-9ab6-8411cde2d9c5) para se candidatar. 
## Labels 
* Remoto 
* SQL 
* TDD 
* React 
* Kubernetes 
* .NET 
* PostgreSQL 
* Angular 
* Docker 
* RabbitMQ 
* Selenium 
* Redis 
* Java 
* Git 
* Spring 
* Swagger 
## Sobre a contratar.dev 
A contratar.dev é uma plataforma de recrutamento e seleção automatizada de Desenvolvedores. Ao se candidatar a uma vaga da contratar.dev, você estará participando automaticamente de dezenas de processos seletivos para vagas similares, aumentando em MUITO as suas chances de mudar de vida 😉

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
