### ISSUE TITLE
[Remoto] Software Developer {React} na eSales

### ISSUE THREAD

**Issue by NerdProgramador-com-br** [frontendbr/vagas#4808]
### DESCRIÇÃO DA VAGA

Construir produtos e serviços com as melhores práticas de mercado além de garantir a aderência ao modelo de Arquitetura Corporativa da organização.

  

### RESPONSABILIDADES E ATRIBUIÇÕES

*   Desenvolver soluções tecnológicas, garantindo funcionalidade, manutenibilidade, velocidade por meio das boas práticas de desenvolvimento de sistemas.
*   Garantir que as soluções técnicas estejam alinhadas a estratégia do negócio/produto e as diretrizes da Arquitetura Corporativa.
*   Entender o impacto das soluções que o time desenvolve no usuário final.
*   Ajudar o time no desenho de soluções com arquitetura evolutiva.
*   Investigar constantemente novas tecnologias e formas de trabalho, discutindo a adoção pela organização como um todo a partir do debate/experimentação junto à Arquitetura Corporativa.
*   Colaborar com a evolução das skills técnicas do time e esforços de melhoria contínua que impactam os demais times.
*   Monitorar o desempenho e performance dos produtos/sistemas em que seu time é responsável.
*   Estar atento a oportunidades e eventuais problemas, agindo com rapidez e eficácia, desenvolvendo soluções de forma preventiva.
*   Auxiliar na orientação dos desenvolvedores mais novos ou menos seniores.

  

### REQUISITOS E QUALIFICAÇÕES

**Hard Skills**

*   Experiência com desenvolvimento em React; 
*   Formação ou Cursos ou Certificações em Ciência da Computação, Sistemas de Informação, Análise de Sistemas e afins;
*   Familiaridade com metodologias ágeis;
*   Conhecimento de Frameworks.

  

**Soft Skills**

*   Foco
*   Capacidade Analítica
*   Pragmatismo para resolução de problemas
*   Colaboração e Espírito de Equipe
*   Capacidade de se atualizar rapidamente
*   Mindset Ágil.

  

### INFORMAÇÕES ADICIONAIS

**O que nos torna um ótimo lugar para trabalhar?**

Horário flexível;

Cultura de feedback 1:1 e PDI Contínuo;

Possibilidade de atuar de forma remota;

Auxílio para Graduação, Pós-Graduação e demais especializações;

Convênio com Alura (a eSales auxilia na metade da mensalidade); 

Ginástica Laboral online;

Day Off de aniversário;

No dress code.

Benefícios flexíveis em apenas um cartão de bandeira Mastercard! **✨**

  

**Demais benefícios:**

Auxílio Home Office

Vale Refeição/ Alimentação

Vale Cultura

Plano de Saúde (Sem desconto de mensalidade no plano básico)

Plano Odontológico Metlife (Cobertura nacional, sem coparticipação, incluindo procedimentos estéticos)

Seguro de Vida Metlife

Convênio academia TotalPass (Incluindo as academias SmartFit, BioRitmo e NÓS)

Vale Transporte de acordo com a necessidade

  

**Todos candidatos são considerados para as nossas posições, independentemente de raça, religião, gênero e identidade de gênero, orientação sexual, nacionalidade, deficiência ou idade.**
## Local 
REMOTO 
## Como se candidatar 
Accesse a [Vaga de Software Developer {React}](https://vaga.contratar.dev/apply/full/225600cd-eb90-4b4c-9ada-f89345fbb3ea) para se candidatar. 
## Labels 
* Remoto 
* React 
## Sobre a contratar.dev 
A contratar.dev é uma plataforma de recrutamento e seleção automatizada de Desenvolvedores. Ao se candidatar a uma vaga da contratar.dev, você estará participando automaticamente de dezenas de processos seletivos para vagas similares, aumentando em MUITO as suas chances de mudar de vida 😉

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
