### ISSUE TITLE
[Remoto] Senior Front-End Engineer na Cyza (California)

### ISSUE THREAD

**Issue by cyzainc** [frontendbr/vagas#481]
**BEFORE APPLYING, PLEASE MAKE SURE THAT:**

**1.** YOU CAN COMMIT MINIMUM 25 HOUR PER WEEK (ALTHOUGH  WE PREFER FULL-TIME)
**2.** MUST HAVE SOLID EXPERIENCE AND AT LEAST 1 (ONE) YEAR OF CODING WITH EACH OF THE FOLLOWING TECHNOLOGIES: SASS, HTML5, JQuery, ES5/ES6 JavaScript, Gulp, and Webpack.

We are a startup based in Newport Beach, California, developing an incredible and innovative online marketplace platform (web & mobile based).

We are interested in hiring talented and experienced frontend engineers. Must have solid experience and knowledge of the following front-end technologies:

CSS3, SASS, HTML5, JQuery, ES6 JavaScript, Gulp, and Webpack.

Our current backend is in Golang web API and frontend consists of above technologies. So it would great if you like Golang or even better if you have some knowledge of it already!

This is a remote position, you will be working from your own home/office and requires a longer-term commitment of at least part-time (realistic 25 hours) but we prefer full-time. Basic conversational English is enough to work with our team and you do not need to be fluent. Good and reliable internet connection is a must.

Must have strong interpersonal and communication skills and be comfortable with a fast paced working environment. Able to work independently and also be productive in a team. Implement new features and work with existing code. Analysis of bugs and optimization issues. Help in establishing new development frameworks and systems.

We look forward to learning about you and your knowledge. Please apply by emailing to jobs@cyza.com and including the following:
1- Basic resume that describes your current and past jobs and education/training
2- Describe your availability and preference for full-time or part-time (min 25 hours a week)

**Comment by vinyguedess** [comment]
Vaga aberta ? Job still open ?
