### ISSUE TITLE
[Rio de Janeiro] Front-end Developer Pleno na ED3 Digital

### ISSUE THREAD

**Issue by ed3digital** [frontendbr/vagas#4810]
Front-end Developer Pleno na ED3 Digital

## Nossa empresa

Somos especializados em soluções e implementações de lojas virtuais na plataforma VTEX. Desenvolvemos incríveis experiências de navegação e compras, focadas no usuário e em sua jornada na loja. Para isso tratamos nossos clientes, suas marca e seus consumidores de forma personalizada e entendendo ao máximo suas necessidades na transformação digital do negócio e inovação.

## Descrição da vaga

* Engajamento com as metas junto aos clientes;
* Atuação na área de desenvolvimento da empresa junto aos demais membros do time com o foco em front end e implantação das e-commerces em plataforma VTEX e outras;
* Em seu dia a dia atuará com o HTML5, CSS3 e JS5 (ES5 OU ES6) desenvolvimento de funcionalidades e telas, resolução de Bug’s, consumo de API’s e integração entre sistemas via front-end, por isso é necessário o conhecimento intermediário de aplicação dessas tecnologias;
* Será um diferencial ter conhecimento e/ou experiência com a plataforma VTEX
* Será um diferencial ter conhecimento em React

## Local

Escritório, Rio de Janeiro, Barra da Tijuca (Downtown)

## Requisitos

**Obrigatórios:**
- experiência comprovada com HTML5, CSS3 e JS5 (ES5 OU ES6) e derivados

**Desejáveis:**
- já ter atuado com implantação em e-commerce

**Diferenciais:**
- já ter atuado com VTEX

## Contratação

CLT ou PJ (a combinar)

## Como se candidatar

Por favor envie um e-mail para luiz.felipe@ed3.com.br com seu CV anexado - enviar no assunto: Desenvolvedor Front End Pleno e realize nosso desafio: https://github.com/ed3digital/frontend-test

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 4 dias após cada processo.
E-mail para contato em caso de não haver resposta: luiz.felipe@ed3.com.br

#### Alocação
- Alocado

#### Regime
- CLT
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
