### ISSUE TITLE
[São Paulo] Front-end na Accenture

### ISSUE THREAD

**Issue by carolinermouratechrecruiting** [frontendbr/vagas#4811]
> Vaga Presencial

## Nossa empresa

A Accenture é uma empresa global feita de pessoas apaixonadas pelo novo. De gente curiosa, investigativa, que não tem medo de arriscar e propor soluções fora dos padrões. Somos uma das maiores empresas de Consultoria, especializada em serviços profissionais do mundo! Realizamos entregas relevantes que impactam diretamente diversos mercados e a vida de milhares de pessoas. Atuamos em conjunto com as maiores empresas do cenário mundial e com ferramentas de ponta, aproveitando o que existe de mais atual no campo tecnológico.

Aqui é possível trocar de trabalho sem precisar mudar de empresa. Que tal trabalhar em uma empresa que proporciona este tipo de mudança? Você vai ganhar mais conhecimento nos próximos seis meses do que nos últimos anos.

Se você gosta de desafios, tecnologia, tendências apaixonantes e um ambiente de trabalho instigante, seu lugar é aqui! 

Um dia é diferente do outro. Somos mais de 500 mil pessoas, em mais de 120 países, engajados em fazer o novo todos os dias e transformar o mundo em um lugar melhor para as pessoas.

Nosso principal valor é o respeito pelo indivíduo. Não fazemos distinção de gênero, cor, orientação sexual, posição social ou deficiências. Todos tem oportunidades iguais de construir sua carreira em uma empresa inclusiva e diversificada.

Se você também é apaixonado pelo que faz, venha conhecer o desafio que a Accenture está te oferecendo!

## Descrição da vaga

Desenvolvimento Front-end/Full-Stack.
Projeto Angular, HTML, CSS, Javascript, React e/ou API.

## Local

 [SÃO PAULO], [SÃO PAULO]

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com Angular
- Experiência com desenvolvimento Front-end/Full-Stack.
- Experiência em HTML, CSS, Javascript, React e/ou API.
Superior completo ou cursando Engenharia e Ciências da Computação, ou áreas afins.

## Benefícios

- Plano de saúde e odontológico
- Seguro de vida
- VR ou VA
- Gympass

## Contratação

CLT 

## Como se candidatar

Por favor entre no link: https://www.linkedin.com/jobs/view/2505063393/

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após cada processo.

#### Alocação
- Alocado SÃO PAULO

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
