### ISSUE TITLE
[Joinville] Front-end Developer na weKnow

### ISSUE THREAD

**Issue by Emmelimp** [frontendbr/vagas#4817]
> Vaga Remota durante a pandemia

## Nossa empresa

Somos a primeira healthtech brasileira que desenvolve soluções de inteligência de negócios de forma simples, ágil e acessível.

## Descrição da vaga

Buscamos profissional para atuar no desenvolvimento de aplicações web. Seu desafio será, junto ao time, melhorar as propostas atuais e evoluir os projetos. Esperamos o uso das melhores técnicas visando a agilidade e qualidade nas aplicações.

## Local

Exemplo: Escritório, [SANTA CATARINA], [JOINVILLE], [ATIRADORES]

## Requisitos

**Obrigatórios:**
– Interesse em desenvolver suas habilidades na área de tecnologia;
– Conhecimento em desenvolvimento web;
– Experiência com JavaScript básico (OO, Modules, Async);
– Curiosidade e vontade de aprender.

**Desejáveis:**
– Conhecimento/Experiência com AngularJS.

**Diferenciais:**
- Essa é uma vaga Júnior, ótima oportunidade para quem está iniciando, pois pretendemos desenvolver.

## Benefícios
- Atuação 100% remota durante a pandemia e posteriormente em regime híbrido;
– Ambiente moderno que proporciona crescimento e aprendizado constante;
– Vale refeição ou alimentação;
– Vale transporte;
– Programa de bônus conforme atingimento de metas;
– Seguro de vida;
– Regime de contratação via Cooperativa.

## Contratação

Cooperado

## Como se candidatar

Por favor envie um email para rh@weknowbi.com.br com seu CV anexado - enviar no assunto: Vaga Dev Fron-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.
E-mail para contato em caso de não haver resposta: emeli.pavanello@weknowbi.com.br

#### Alocação
- Híbrido
- Remoto

#### Regime
- Cooperado

#### Nível
- Júnior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
