### ISSUE TITLE
[Joinville SC] - Desenvolvedor Web FullStack -NEXT IDEA

### ISSUE THREAD

**Issue by AllanD1** [frontendbr/vagas#482]
## JOB DESCRIPTION

Mais clientes significa mais trabalho e precisamos reforçar a nossa equipe. Estamos com uma vaga aberta para desenvolvedor full stack. Veja se seu perfil se encaixa com o que buscamos e venha fazer parte do nosso time :)

## Local

Rua São Paulo, 31, Sala 110, Joinville / SC

## Benefícios

• Ambiente descontraído para trabalhar;
• Metodologia de Inbound Marketing, conceito diferenciado no mercado;
• CLT + VA + VT.
• Plano de Saúde. (após 180 dias)

## Requisitos

**Obrigatórios:**
- Residir em Joinville/SC ou disponibilidade para mudar para a cidade rapidamente;
- Domínio ou sólidos conhecimentos em PHP (versão 7 de preferência);
- Domínio de arquitetura MVC;
- Domínio do Wordpress;
- Domínio no framework LARAVEL ou capacidade para aprender e tornar-se produtivo rapidamente;
- Conhecimento DRUPAL 8
- Domínio na ferramenta de controle de versão GIT / GITLAB;
- Conhecimento em SQL, preferencialmente MySQL;
- Conhecimento em HTML5, CSS3, SASS ou Less;
- Conhecimentos sólidos em JavaScript (melhores práticas, frameworks);
- Experiência com Bootstrap;
- Conhecimento da estrutura de servidores e processos de Deploy (DevOps)
- Atenção a detalhes;
- Facilidade para participar de reuniões co-criativas durante a fase de planejamento e criação;
- Organização e documentação no processo de trabalho;

**Desejáveis:**
- Conhecimento em arquitetura REST;
- Conhecimento em integração de APIs de terceiros: Facebook Open Graph, Twitter, GoogleMaps, YouTube, etc;
- Conhecimento em design responsivo;
- Boas práticas de SEO;

## Contratação

CLT-full

## Nossa empresa

Sempre Pensando a frente 

## Como se candidatar
Clique no Link a baixo 
https://careers.jobscore.com/careers/nextidea/jobs/desenvolvedor-web-fullstack-asIcIiFIur54NCdG1ZS6tF?detail=facebook&remail=&rfirst=&rlast=&sid=161

**Comment by LFeh** [comment]
Aberto ainda?
