### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor C# na Sofis Tecnologia

### ISSUE THREAD

**Issue by NerdProgramador-com-br** [frontendbr/vagas#4822]
## Descrição da vaga 
**Para participar você precisa:**

·        Excelente lógica de programação;

·        Linguagem SQL intermediária a avançada;

·        Padrões de orientação a objetos e versionamento de código;

·        Html, javascript, Asp.Net (c# ou vb.net);

·        Pro atividade, comprometimento e trabalho em equipe;

·        Ensino Superior completo ou cursando em Ciência da Computação, Tecnologia da Informação ou áreas afins.

**Aqui você vai poder:**

·        Atuar com desenvolvimento evolutivo e corretivo de sistemas desktop e web;

·        Trabalhar com consultas e rotinas em banco de dados SQL Server e construção de reports, com predomínio atual das linguagens C# e Vb.Net;

·        Crescer e se desenvolver técnica e profissionalmente;

·        Participar de um ambiente descontraído e com práticas de qualidade de vida.

**Serão diferenciais:**

·        Aplicações desktop (winforms), webservices, api rest, frameworks de persistência, angular, metodologias ágeis.

  

**O que oferecemos:**

*   Vale Transporte;
*   VR/VA;
*   Plano de Saúde e Odontológico;
*   Convênio com instituições de ensino;
*   Day off no dia do seu aniversário!

A Sofis é uma empresa que preza pela excelência. Valorizamos a ética, a camaradagem e a diversidade em todos os nossos ambientes. Para participar envie seu currículo com pretensão salarial para [rh@sofis.com.br](mailto:rh@sofis.com.br)
## Local 
Rio de Janeiro/RJ 
## Como se candidatar 
Accesse a [Vaga de Desenvolvedor C#](https://vaga.contratar.dev/apply/full/1def44d0-60b5-4c8d-9b43-6562ad54de87) para se candidatar. 
## Labels 
* Alocado 
* SQL 
* Javascript 
* C# 
* Angular 
* Rest 
* HTML 
## Sobre a contratar.dev 
A contratar.dev é uma plataforma de recrutamento e seleção automatizada de Desenvolvedores. Ao se candidatar a uma vaga da contratar.dev, você estará participando automaticamente de dezenas de processos seletivos para vagas similares, aumentando em MUITO as suas chances de mudar de vida 😉

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
