### ISSUE TITLE
[Remoto] Front-end Developer na Convenia

### ISSUE THREAD

**Issue by Arkanius** [frontendbr/vagas#4824]
## Nossa empresa

Somos o maior clube de benefícios do Brasil com mais de 15 milhões de usuários!

## Descrição da vaga

Procuramos pessoas apaixonadas por desenvolver soluções, que curtam trabalhar com foco em qualidade, em um time onde você irá aprender muito e ensinar caso queira.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência com Vue.js
- Experiência em consumo de API's;
- GIT;
- HTML;
- CSS;
- Javascript avançado

**Desejáveis:**
- Testes
- GraphQl

## Benefícios

 - Benefícios flexíveis (você escolhe o que melhor se encaixa para ti):
 - Vale refeição e/ou alimentação;
 - Plano odontológico;
 - Convênio saúde;
 - Auxílio academia;
 - Cartão de despesas;

**Diferenciais:**
- Horário flexível;
- Clube de descontos;
- Chef's Club;

## Contratação

CLT

## Como se candidatar

Por favor envie um email para victor.gomes@kaledo.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: victor.gomes@kaledo.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by Gabri3el** [comment]
Enviado \o/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
