### ISSUE TITLE
[100% Remoto - US] Senior Web Developer na Dialpad

### ISSUE THREAD

**Issue by cassianodialpad** [frontendbr/vagas#4827]
Pessoal, eu trabalho na Dialpad há mais de 2 anos como gerente de engenharia para o time de iOS. Em Outubro do ano passado recebemos um funding de 100 milhões de dólares, e estamos dobrando o time de engenharia, com expansão forte no Brasil! Já contratamos 4 desenvolvedores remotos do Brasil, e estamos abrindo vagas para todas as áreas da engenharia. Quem quiser mais informações fique à vontade pra me adicionar no meu [LinkedIn](https://www.linkedin.com/in/cassianomonteiro/) e bater um papo!

## Empresa
Dialpad é uma empresa que fornece soluções de *business communications* para outras empresas, incluindo ligações voip, mensageria, video conferência, call center, etc. O diferencial do produto é a plataforma de telefonia totalmente cloud, permitindo transferir ligações da rede comum de telefonia (operadoras de celular por exemplo) para ligações voip de maneira instantânea. Isso permite (por exemplo) atender uma ligação no meu celular e continuar no computador sem a outra pessoa perceber a transferência. Além disso, temos forte AI integrada à plataforma, o que permite *speech-to-text* em tempo real. O nosso foco é o mercado de pequenas e médias empresas, mas já temos grandes clientes como Uber, TED e Motorola.

## Com quem você vai trabalhar
Uma galera boa pra caramba, vários devs com 7+ anos de experiência!

## Como aplicar
Obviamente é necessário inglês nível profissional.
Link para aplicar: https://grnh.se/a69774bf2us

## Tipo de contratação
CLT

## Contato
Para mais informações, podem me mandar [email](mailto:cmonteiro@dialpad.com) ou através do meu [LinkedIn](https://www.linkedin.com/in/cassianomonteiro/). Mais detalhes da vaga em inglês abaixo.

## About the company

Dialpad is the most modern business communications company in the industry.  Our products range from conferencing calling, to phone systems to contact center solutions that are all built with the end-user in mind.  We allow workers to be productive from anywhere on any device and have moved all the power of an on-premise phone system or contact center to the cloud to be accessed and used by modern workers in today’s Work from Anywhere environment.

## Who We Are

At Dialpad, work isn’t a place you go, it's a thing you do. We don’t just build products for everywhere workers, we are everywhere workers. With offices in the Bay Area, Austin, Raleigh, Vancouver, Waterloo, Tokyo, London, Sydney, and Bangalore, along with remote workers around the world, we are committed to building a diverse workforce, where each person is welcomed and valued for their personhood and contribution.

With a $1.2 billion valuation and over $250 million in funding from Google Ventures, Andreessen Horowitz, OMERS Growth Equity, ICONIQ Capital, Felicis Ventures, Work-Bench, Scale Ventures, and other top VCs, Dialpad attracts top talent from leading tech companies, and every member of our team plays an essential role in creating dynamic products that enable workers to collaborate and be productive from anywhere.

### In your first 30 days: 

As Dialpad’s newest web developer you’ll have made a direct impact on our web presence with your first set of updates, changes and enhancements
This all starts with your onboarding, learning the tools we use, setting up your environment and getting familiar with the code base
You will also spend time becoming familiar with our UberConference website, help centers, landing pages, international sites and personalizations 
You’ll create new landing pages for campaigns, A/B testing these pages and optimizing for improved conversion rates

### In your first 60 days: 

You’ll have started the process of working with other stakeholders in the organization, including our design team, content creators and product managers
Regularly taking on tasks ranging from front end visual enhancements to building our new pages and sections of the website 
You will review other team members work; visually reviewing pages to make sure they align with the design to pixel perfection; performing browser compatibility tests and doing code reviews 
You will play a part in maintaining our web properties including performing regular maintenance, applying updates and fixes
You will deliver exceptional customer service by resolving urgent requests and responding to requests for help

### By 90 days: 

You’ll have become fully immersed in the different Dialpad web properties and are able to address questions, make fixes or tackle new projects as they arise
At this point you will have had an opportunity to take ownership of projects, bring prototypes, content and designs to life with well crafted and well tested web pages 
Estimate timelines, develop plans and make recommendations on new projects 
You will be experienced with and regularly involved in deploying website updates
You will start developing a firm understanding of building well optimized web pages, working closely with our SEO team to insure well structured pages, optimizing images, adding analytics tracking, focusing on quick load times and website usability

## Who you are

You’re a Senior Web Developer who will help us design and develop the next generation of features for the Dialpad website. You have an excellent analytical and technical aptitude with proven ability to solve complex problems. You have specialized or advanced expertise and are up on the latest web trends and technologies. Additionally, you’ve worked on large projects with multiple cross functional teams where you regularly contribute ideas to meet business objectives. You will play a critical part in defining and building our website, while working closely with a team of designers, product managers and other engineers.  

Necessary skills to be successful in this role include a minimum of 5+ years professional web development experience.  Expert use of Front End UI using JavaScript, JQuery, HTML5, CSS 3.0, LESS/SCSS. Experience with server side development and templating using TWIG, PHP, Python or similar language. Strong grasp and experience with responsive web design and Bootstrap.  Experience with cross-browser and cross-platform (Desktop, Mobile, etc.) development and testing.  Experience optimizing front-end code for peak performance using speed and optimization testing tools (Pagespeed Insights, Lighthouse, Webpagetest, etc).  Solid familiarity with modern front-end build pipelines and tools.  Ability to understand business requirements and translate them into technical requirements. Previous experience with Version control with Git.

Join us, and have a huge direct impact on the quality of Dialpad’s growing products and services from day one!

## Culture

We’ve been named a Top Workplace seven times because we truly live and breathe our culture. In alignment with one of our core values, “Skill & Will,” we strive to bring on only the most passionate and talented people to our team. Collectively, Dialers work together to solve problems that help the everyday worker. We foster a collaborative environment where people are elevated, wins are celebrated, and development is encouraged. 

## Compensation

Teamwork makes the dream work. Recognizing that our talented and committed team members drive our success, Dialpad offers competitive rates.

## Equity, Balance, and Belonging

At Dialpad, we value the humanity that makes each of us unique. We strive to ensure everyone is supported equitably, and Dialers are free to bring their full selves to work each day, and celebrate others doing the same. We champion the intersectionality that exists between gender identity, ethnicity, age, disability status, and the many other aspects of our greater humanity.

*Dialpad is an equal opportunity employer; we believe in creating a community of inclusion and an environment free from discrimination or harassment.*

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
