### ISSUE TITLE
[São Bernardo do Campo, SP] Front-end Developer na Canaltech

### ISSUE THREAD

**Issue by airtonlimajr** [frontendbr/vagas#4829]
## Nossa empresa

Canaltech é um portal vertical com foco no mercado de software, tecnologia, games e entretenimento. De uma forma simples e direta, o Canaltech informa as pessoas sobre o que está acontecendo no mundo da tecnologia, mostra os lançamentos do mercado com análises dos produtos, dá dicas de navegação e descomplica termos que passaram a fazer parte da rotina de todos que precisam lidar com equipamentos e botões no dia-a-dia.

## Descrição da vaga

Estamos em busca de um desenvolvedor front-end para agregar em uma nova fase do Canaltech! Se você tem verdadeiro amor por tecnologia, se interessa por celulares, games, computadores venha se juntar a nós!

**Responsabilidades**

Participar do desenvolvimento das integrações de sistema consumindo APIs REST;
Desenvolver e manter componentes, telas e fluxos de funcionalidades desenhados pela equipe de UX/UI;
Valer-se de boas práticas de desenvolvimento front-end.

## Local

- São Bernardo do Campo, SP.: Possibilidade de trabalho em home-office integral. 

## Requisitos

- Ter experiência com desenvolvimento de PWA’s, usando rotas abertas e fechadas (sessões controladas);
- Desenvolver código responsivo e fiel às interfaces projetadas pelo UX;
- Dominar HTML5, CSS3, JavaScript, SASS;
- Conhecer SEO Semântica e Performance (PageSpeed Insights / Audits / Gtmetrix);
- Utilizar versionamento GIT.

## Benefícios

- VT
- VR (R$ 20,00/dia)
- 13º e férias
- PLT 1 Salário (condicionado a metas)
- Plano de Saúde regional
- Cheque-mãe de R$ 422,00 para colaboradorAs com filhos ate 05 (cinco) anos
- Seguro de vida coletivo
- Clube de compras Magalu com descontos de 10%
- Faixa salarial para a vaga: de R$ 6.000,00 a R$ 9.000,00 (a depender da senioridade do candidato)
- Em breve teremos outros beneficios após integração da folha ao modelo Magalu.

## Contratação

- CLT

#### Alocação

- Alocado com possibilidade de remoto.

#### Nível

- Pleno
- Sênior
- Especialista

## Como se candidatar

Clicando [aqui.](https://www.linkedin.com/jobs/view/2496350843/?alternateChannel=search&refId=eekGYrpjWpJvREbd0OG8sQ%3D%3D&trackingId=RKhYuuIKJBhMdNJ9EO2%2BOg%3D%3D)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by airtonlimajr** [comment]
@felipefialho a vaga segue mantida em aberto.
