### ISSUE TITLE
[Recife/PE - Remoto] PL/SR Front-End Developer @ N3urons

### ISSUE THREAD

**Issue by andregomesoliveira** [frontendbr/vagas#4831]
> Vaga Remota durante a pandemia

## Nossa empresa

Somos uma startup focada em soluções web/mobile inovadoras relevantes para o mercado que atuamos. Nosso diferencial é aplicar inteligência artificial com foco em automação e inteligência de negócios, com laboratórios incubados em empresas reais para validação dos nossos produtos. 

## Descrição da vaga

Estamos buscando profissionais de desenvolvimento que tenham capacidade de trabalhar em um time multidisciplinar entendendo a cultura de união e propósito do que fazemos, integrados como um só organismo assim como os neurônios que representam nossa startup. 
Compartilhamento de conquistas e conhecimentos, soluções em conjunto, busca de melhoria contínua e sede de inovar são imprescindíveis. **Na N3urons valorizamos estas _soft skills_ antes de tudo!**
Você irá participar da concepção de novos produtos como otimização das versões correntes, desde desenvolvimento mobile, web e participação dos projetos de UI/UX.

## Local

Vagas presenciais em Recife/PE e full Remoto. (02 vagas para início imediato)

## Requisitos

**Obrigatórios:**
- 2+ anos de experiência com desenvolvimento frontend web/mobile.
- Conhecimento intermediário em React Native/ReactJS e JavaScript.
- Experiência com APIs REST
- Experiência com times de desenvolvimento
- Conhecimento nas Metodologias Ágeis

**Desejáveis:**
- Conhecimento em TypeScript
- Javascript/React avançado
- Conhecimento intermediário em Redux/Redux Saga, Codepush, Styled Components.
- Conhecimento em Banco de Dados mobile ( Realm )

## Benefícios

- Horário flexível (40hs semanais)
- Plano de saúde 100% custeado pela empresa, sem descontos!
- VR/VA mensal
- Incentivos para participação em treinamentos, eventos, palestras e cursos
- Envolvimento no propósito do projeto e não somente codar um escopo pré-definido

## Contratação

CLT ou PJ, podemos te oferecer a modalidade que melhor se adequar a você!

## Como se candidatar

Por favor envie um email para andre.oliveira@n3urons.com com seu CV e LinkedIn informado - enviar no assunto: Vaga Frontend

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior

#### Tecnologias
- React
- RESTful
- API
- Javascript
- MongoDB
- Realm

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by SahRecruiter** [comment]
Gente, boa tarde. Acabei de chegar no Github, eu queria saber como que eu consigo deixar etiquetas, por favor

**Comment by tuliopxavier** [comment]
> Gente, boa tarde. Acabei de chegar no Github, eu queria saber como que eu consigo deixar etiquetas, por favor

Essa funcionalidade fica disponível apenas para pessoas donas e contribuidoras do repositório (owner / contributor).
É uma forma de evitar que pessoas aleatórias atribuam labels errados e "baguncem" as categorias.

No entanto, no final do template da issue, tem um espaço onde você sugere as labels:

```
## Labels
<!-- retire os labels que não fazem sentido à vaga -->

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- Estágio
- Freela
- PJ

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista
```

* Não sei se esse é o local indicado pra esse tipo de dúvida. De qualquer forma, sinta-se a vontade pra me perguntar diretamente (email / redes sociais) caso surjam novas dúvidas.
