### ISSUE TITLE
[Rio de Janeiro/RJ] Front-end Developer na Oliveira Trust

### ISSUE THREAD

**Issue by davicervo** [frontendbr/vagas#4838]
## Nossa empresa

A Oliveira Trust é uma das maiores empresas do setor Financeiro com muito orgulho, desde 1991, realizamos as maiores transações do mercado de Títulos e Valores Mobiliários.

Somos uma empresa em que valorizamos o nosso colaborador em primeiro lugar, sempre! Alinhando isso com a nossa missão "Promover a satisfação dos nossos clientes e o desenvolvimento pessoal e profissional da nossa equipe", estamos construindo times excepcionais em Tecnologia, Comercial, Engenharia de Software, Produto, Financeiro, Jurídico e Data Science.

## Descrição da vaga

Estamos buscando uma pessoa que seja movida a desafios, que saiba trabalhar em equipe e queira revolucionar o mercado financeiro!

## Local

Barra da Tijuca - Rio de Janeiro/RJ

## Requisitos

**Obrigatórios:**
- Trabalhar com frameworks/libs (Vuejs, Jquery, Bootstrap)
- Conhecimento com Javascript (VanillaJs) e novas features do EcmaScript
- Bons conhecimentos em CSS3: Grid-layout, flexbox, animações, responsivo
- Implementar API's com nossas interfaces
- Conhecer alguma ferramenta para teste de requisição (Postman, insomnia)

**Diferenciais:**
 - VueJs
 - SASS
 - Webpack
 - Conhecimento e interesse em UX / UI.

## Benefícios

- Salário compatível com o mercado;
- Bônus por meta e entrega de projetos;
- Vale Refeição;
- Vale Alimentação;
- Vale Transporte ou Vale Combustível;
- Plano de Saúde e Odontológico;
- Seguro de vida;
- PLR Semestral;
- Horário Flexível;
- Parcerias em farmácias

## Contratação

CLT

## Como se candidatar

Acesse o nosso desafio para saber mais detalhes: https://github.com/Oliveira-Trust/desafio-frontend/blob/master/VAGA.md
Para saber todos os detalhes da vaga acesse: https://github.com/Oliveira-Trust/desafio-frontend/blob/master/README.md

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.

## Labels
CLT, JR, PLENO, SENIOR

#### Alocação
- Presencial e Remoto Parcial

#### Regime
- CLT

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by arcmarcos** [comment]
@davicervo Tudo bem? Gostaria de saber se o processo ainda está aberto. Mandei o pull request há algumas semanas e o e-mail com currículo mas não sei se receberam.

**Comment by arcmarcos** [comment]
> @arcmarcos tudo bem por aqui e espero que por ai também! Recebemos o seu PR e sim, ainda estamos com a vaga em aberto! Você receberá um feedback, desculpa o atraso na resposta!

Ah sim, obrigado pelo retorno, estou disponível para qualquer esclarecimento e fico no aguardo!
