### ISSUE TITLE
[São Paulo] Front End Engineer na Zx Ventures

### ISSUE THREAD

**Issue by drdpedroso** [frontendbr/vagas#484]
## Description

We're looking for a front-end engineer (Jr/Pl/Sr) with solid base in JavaScript, HTML and CSS to work in a global project with a very diverse team (so English it's a MUST). Our Tech Stack is React, GraphQl, Lodash and Python with a Serverless Architecture.

## Local

São Paulo - SP (Vila Nova Conceição)

## Benefits

- Attractive compensation package
- Health, dental and life insurance
- GymPass
- Meal allowance

## Requirements

**Must have:**
- 1+ year working with SPA (Angular, React, BackBone)
- HTML5, CSS3
- Modern JavaScript ES6+
- Webpack/Browserify
- GIT/SVN
- Responsive Layout
- Good practices and front-end pattern knowledge

**Nice if you have:**
- React
- React Native
- Flexbox
- GraphQL
- Some functional programming knowledge
- Python/Ruby/Java/Scala

## Contract

CLT Full

## About our company

We are a global disruptive growth group, incubator, and venture capital team backed by one of the largest multinational companies in the world, AB InBev. Our trade is dreaming up what the future looks like, today. We are a small army of futurists, dreamers, doers, designers, engineers, scientists, marketers, brewers, builders, and data geeks. For us, the future is now.

## How to Apply

https://zx-ventures.workable.com/j/2355DDAC69

**Comment by devEdipo** [comment]
Can I send my resume? I'm looking for a Front End Junior position, but I'm a Q.A

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by CesarNobre** [comment]
Sim! Ainda estamos buscando fronts! :)

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
