### ISSUE TITLE
[Rio de Janeiro] Analista de Sistemas Pleno na Azul Seguros

### ISSUE THREAD

**Issue by NerdProgramador-com-br** [frontendbr/vagas#4840]
## Descrição da vaga 
Descrição da área:

A área de sistemas é responsável por desenvolver projetos e novas

funcionalidades em sistemas, manutenções evolutivas e corretivas, assim

como as respectivas integrações entre sistemas da Azul e parceiros.

  

Pré-requisitos:

  

 Ensino Superior em Tecnologia da Informação ou cursos afins.

 Bons conhecimentos em Tecnologias Web: HTML5, CSS e

Frameworks JavaScript, como Angular e Node.js.

 Conhecimento de Arquiteturas Web e Serviços (HTTP, SOAP, REST,

JSON e AJAX).

 Integração de Microsserviços Java, TypeScript, REST, Spring

 Familiaridade com arquiteturas SOA/RestFul.

 Conhecimentos nas ferramentas: GIT e Maven.

 Conhecimentos em Bancos de Dados relacionais: MYSQL, SQL

Server.

 Experiência com algum framework Java: JSF, Spring ou Hibernate.

 Conhecimentos em, pelo menos, uma linguagem server-side: como

Java Web e C.

 Filosofia DevSecOps, Agile / Scrum e Kanban.

 Ambiente: Wildfly (J2EE, EJB 3.0, OSS) e Spring Boot
## Local 
Rio de Janeiro/RJ 
## Como se candidatar 
Accesse a [Vaga de Analista de Sistemas Pleno](https://vaga.contratar.dev/apply/full/67558db0-63a2-49b5-b40e-bef796dc4509) para se candidatar. 
## Labels 
* Alocado 
* SQL 
* Javascript 
* JSF 
* Scrum 
* MySQL 
* Maven 
* Angular 
* CSS 
* Rest 
* TypeScript 
* HTML 
* Java 
* Git 
* SOAP 
* Spring 
* Microsserviços 
## Sobre a contratar.dev 
A contratar.dev é uma plataforma de recrutamento e seleção automatizada de Desenvolvedores. Ao se candidatar a uma vaga da contratar.dev, você estará participando automaticamente de dezenas de processos seletivos para vagas similares, aumentando em MUITO as suas chances de mudar de vida 😉

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
