### ISSUE TITLE
[Porto Alegre] Front-end Developer Junior na Vnda Ecommerce

### ISSUE THREAD

**Issue by isadoracribeiro** [frontendbr/vagas#4842]
## Nossa empresa

A Vnda é uma empresa de tecnologia para varejo, com um SaaS (software como serviço), oferecemos soluções de digitalização do varejo, por meio de uma plataforma de e-commerce própria, com visão Omnichannel.

Acreditamos que marcas devem inspirar pessoas e que as relações vão além das transações. 

Defendemos o ideal de um varejo emocional, que vai além do foco nas características funcionais dos produtos, explorando também a diferenciação em conceito e em experiência de cada marca.

Nossa sede fica em Porto Alegre - RS, mas nossa base de clientes é composta por negócios do Brasil inteiro, dos mais diversos segmentos do varejo.  

## Descrição da vaga

Acreditamos que todos podem colaborar para que os projetos tenham a melhor qualidade possível, por isso montamos um processo de criação onde todos os envolvidos no projeto tem liberdade para ter ideias e tomar decisões que melhorem os projetos.

Na Vnda você fará parte de um de nossos squads, onde desenvolverá projetos completos de e-commerce,  a partir da demanda de nossos clientes por intermédio do nosso time de Product Owners.

Será instigado a contribuir com ideias para projetos, primando sempre pela qualidade estética e técnica do resultado final, desenvolvendo layouts web através de Wireframes desenvolvidos pelo nosso time de Designers. 

Também trabalhará no suporte e melhoria de lojas ativas junto ao nosso time de Customer Success.

## Local

Remoto ou Escritório, [Rio Grande do Sul], [Porto Alegre], [Auxiliadora]

## Requisitos

**Obrigatórios:**

# Competências pessoais

- Vontade de aprender e crescer;
- Paixão pelo que faz;
- Compromisso com qualidade e agilidade;
- Comunicação com o time afim de buscar sempre a melhor solução para nossos clientes;
- Senso de design e estética;
- Estar por dentro das novas tecnologias de mercado;
- Organização e cultura criativa.
 
# Competências técnicas

- HTML semântico;
- CSS Intermediário (SASS, transições, animações e design responsivo);
- Javascript Intermediário;
- Noções de Design e UX;
- Codificação de layouts web partir de wireframes.

**Diferenciais:**
- Conhecimento sobre alguma linguagem de template (liquid, twig, mustache, handlebars...);
- Conhecimento sobre alguma plataforma/ferramenta de e-commerce;
- Conhecimento sobre jQuery;
- Conhecimento sobre performance;
- Conhecimento sobre metodologias ágeis;
- Conhecimento sobre alguma linguagem de back-end;
- Conhecimento em frameworks JS (React, Vuejs, Angular ...);
- Conhecimento sobre SEO;
- Conhecimento sobre banco de dados;
- Inglês técnico (leitura);

## Benefícios

- Salário compatível com mercado e nível de desenvolvimento técnico;
- Plano de carreira com avaliações trimestrais;
- Plano de Saúde Unimed;
- Plano Odontológico Uniodonto;
- Vale Alimentação / Vale Refeição;
- Possibilidade de regime de trabalho Presencial, Home Office ou Híbrido.

## Contratação

CLT

## Como se candidatar

Por favor, preencha o formulário no link https://docs.google.com/forms/d/e/1FAIpQLSdpjsj-H9bxzVFvpT7gwOl0O-4eRE7yn6uT6Um0ZE-D3dyIHQ/viewform

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: pp@vnda.com.br

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Júnior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
