### ISSUE TITLE
[Remoto] Founding Front-end Developer na Livus

### ISSUE THREAD

**Issue by lucianoks** [frontendbr/vagas#4843]
## Nossa empresa

A Livus é uma startup em fase inicial inserida no universo da Creators Economy, que se propõe a empoderar criadores de conteúdo para que consigam viver do que amam. 

Estamos buscando os primeiros membros para montar um Founding Team fora de série, que vai criar produtos de altíssima qualidade, sempre com foco em entregar o máximo de valor para os clientes, e que também vai ser parte fundamental da criação da cultura da empresa.

Ser parte de um Founding Team é uma experiência única, em que se pode por em prática tanto a excelência técnica quanto a capacidade de liderança e participação na elaboração dos produtos, além de se tornar sócio da empresa com plano de stock options.

Sobre os founders: somos 4 empreendedores apaixonados pelo que fazemos, todos ex-sócios na Neon em posições de liderança, e individualmente com passagens por Ambev, Revmob, UseBike, WhatsApp e Facebook.

Conheça mais sobre nossos valores:
[Purpose, Mission and Core Values](https://www.notion.so/Purpose-Mission-and-Core-Values-a60b4ebfaf664f89a72e052fb6b29905)

## Descrição da vaga

- Liderar o início do desenvolvimento da aplicação web com React e melhores práticas
- Intensa colaboração com Founding Engineers para definição de tecnologias, integrações e processos
- Intensa colaboração com product designers para criação de features
- Criação de interfaces que fazem brilhar os olhos dos usuários

## Local

- Remoto
- Futuramente, escritório opcional em São Paulo

## Requisitos

**Obrigatórios:**
- 3+ anos de experiência em frontend
- 2+ anos de experiência com aplicações React
- Inglês para leitura/escrita

**Desejáveis:**
- Liderança técnica de projetos
- Gestão de times

## Benefícios

- Plano de saúde Amil, hospitais: SantaCatarina, Samaritano, Oswaldo Cruz, Beneficência Portuguesa Mirante, São Camilo, HCor, 9 de Julho, São Luiz Santo Amaro/Morumbi
- Cartão Flash: R$ 700,00

**Diferenciais:**
- Salário competitivo
- Plano de Stock Options
- Entrar em uma empresa no comecinho, só com gente fera, e fazer parte do crescimento e construção da cultura e do negócio.
 
## Contratação

CLT

## Como se candidatar

Mande um email para luciano@livus.com.br com o assunto "Founding Frontend Engineer", com a pretensão salarial atual e o link parar seu perfil no LinkedIn.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada etapa.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by emirdeliz** [comment]
Somente CLT?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
