### ISSUE TITLE
[100% home office ou Campinas] Tech Lead na I.Systems

### ISSUE THREAD

**Issue by Kahfiod** [frontendbr/vagas#4844]
## Descrição da vaga

A posição de Tech Lead tem como objetivo trabalhar de forma estratégia na equipe de Tecnologia, participando do ciclo de vida dos produtos, fornecendo soluções de alta qualidade que atendam às melhores práticas de padrões de codificação e design. Além disso, liderar e conduzir tecnicamente as equipes de back-end e front-end, com foco em Python, infraestrutura Cloud, Angular e React.

## Local

Remoto ou Escritório, Campinas - SP

## Benefícios

- Vaga presencial ou 100% home office;
- PLR (com mais de 3 meses de empresa);
- Seguro de Vida (Porto Seguro);
- Assistência Médica (Unimed - sem desconto para o funcionário e dependentes);
- Assistência Odontológica (Uniodonto);
- Vale Alimentação ou Refeição;
- Licença Maternidade e Paternidade estendida;
- Auxílio Creche;
- Gympass;
- Ginástica Laboral;
- Horas de estudos (4horas/semana);
- Horários flexíveis;
- Auxílio para estudos de idiomas;
- Monetus (consultoria financeira);
- Creditas (crédito consignado);
- Cursos Alura.

## Requisitos

**Obrigatórios:**

- Experiência na atuação com o time de Produto e Inteligência Artificial para alinhamento e desenvolvimento desde o Discovery até entrega;
- Experiência profissional relevante com as tecnologias Python/Docker/Kubernets (se o background for Back-end) E/OU JavaScript/Angular/React (se o background for Front/End), bancos de dados relacionais, testes automatizados e arquitetura de microsserviços;
- Domínio sólido de princípios e patterns de programação orientada a projetos (design patterns);
- Conhecimento de infraestrutura Cloud (AWS, Azure, GCP ou similares);
- Inglês técnico.

**Diferenciais:**

- Graduação concluída em Ciência da Computação, Engenharia de Computação ou cursos similares;
- Experiência com microservices, CI/CD, infrastructure as code e Kafka;
- Proficiência em tecnologias como AWS, Docker e Git;
- Noções avançadas de Python.

## Contratação

CLT

## Nossa empresa

A I.Systems fornece soluções de controle avançado e otimização de processos para diversos segmentos da indústria com produtos de tecnologia exclusiva e patenteada, baseados em inteligência artificial. Com mais de 100 projetos realizados em mais de 40 grupos distintos, estamos caminhando para nos tornar uma empresa global e cada vez mais próxima do objetivo de aumentar a eficiência do mundo.

## Como se candidatar

Por favor envie um email para recrutamento@i.systems.com.br com seu CV anexado - enviar no assunto: Vaga -Tech Lead

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
