### ISSUE TITLE
[Blumenau] Front-end Developer na Serasa Experian

### ISSUE THREAD

**Issue by rodrigopoi** [frontendbr/vagas#4845]
> Vaga Remota durante a pandemia

## Nossa empresa

Somos formados por gente inquieta, inconformada, que acorda todos os dias para mudar a realidade do crédito no Brasil.
Corremos em um ritmo próprio e transformamos o impossível em mais um case de sucesso.

**Nosso propósito é revolucionar o acesso ao crédito no Brasil!**

## Local

Escritório, Santa Catarina, Blumenau

## Requisitos

**Obrigatórios:**
- Experiência com ReactJS.
- Experiência com TypeScript.
- Experiência com JavaScript, HTML, CSS e SASS.
- Experiência com API Rest.

**Desejáveis:**
- Experiência com Angular
- Experiência com serviços Cloud (AWS).
- Experiência com SEO.
- Experiência com Google Analytics.

## Benefícios

- Horário Flexível
- No dress code
- Plano Médico e Odontológico (Para você e seu dependente 😍)
- Vale Alimentação + Refeição (Beneflex)
- Seguro de Vida
- PLR anual
- Previdência privada
- Gympass
- Vale-Transporte

**Diferenciais:**
- Metas claras e muita autonomia para desenvolver estratégia e obter resultados
- Produtos com a possibilidade de fazer história e deixar legado
- Ferramentas de alta performance para trabalhar
- Ambiente desafiador e High Performance
- Times multidisciplinares e multiculturais

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um email para rodrigo.junqueira@br.experian.com com o link do seu Linkedin - enviar no assunto: Vaga Front-end 
ou pelo site https://serasa.gupy.io/jobs/752086

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: rodrigo.junqueira@br.experian.com

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
