### ISSUE TITLE
[Remoto] Front-End React Developer na Jet Soluções Web

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#4846]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url https://coodesh.com com o pop-up personalizado de candidatura. :wave:
<p>A Jet Soluções Web, está buscando <strong>Front End Developer</strong> em nível júnior. Você Irá trabalhar no desevolvimento de front-end e na comunicação com o back-end.</p>

## Jet Soluções Web: 
 
</p>undefined</p>

 ## Habilidades: 
 - Bootstrap 
- HTML 5 
- React.js 
- React Native 
- Typescript 
- GIT 
- CSS 3 
- RESTful
## Local: 
 100% Remoto
## Requisitos: 
 - Conhecimentos em React.js e React Native 
- Conhecimentos em CSS e HTML 
- Conhecimentos em Typescript e Javascript 
- Habituado com Git

## Benefícios: 
 - Ajuda de Custo 
- Seguro de Vida
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Front-End React Developer na Jet Soluções Web](https://coodesh.com/vagas/frontend-114042?origin=github&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção <b>Pedir Feedback</b> entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa <b>Recruiter</b> responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Nível
Júnior
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
