### ISSUE TITLE
[Belo Horizonte] Android Developer na Dti Digital

### ISSUE THREAD

**Issue by victorldavila** [frontendbr/vagas#4848]
Venha ser dti!

Estamos buscando pessoas que amam tecnologia, são apaixonadas pelo que fazem, querem se devolver profissionalmente e aprender sempre mais! Que tal fazer parte dos nossos times?

Se liga nas vagas abertas:
- Tech Lead Mobile: Conhecimento em desenvolvimento mobile nativo, nas tecnologias JAVA, Kotlin e Swift 
- Pessoa Desenvolvedora Mobile: Conhecimento em desenvolvimento mobile nativo, nas tecnologias JAVA, Kotlin e Swift

Ficou interessado(a)? Manda seu currículo pra gente! tayna.brandao@dtidigital.com.br e/ou samuel.paiva@dtidigital.com.br

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
