### ISSUE TITLE
[Rio de Janeiro] Front-End Developer na [TOTVS]

### ISSUE THREAD

**Issue by yosephcsantos** [frontendbr/vagas#485]
## Descrição da vaga
Projeto Inovação da TOTVS.
Estamos criando um produto do zero com novas tecnologias. 
A equipe foi formada em abril desse ano e é um projeto muito ambicioso no ponto de vista de negócio e desenvolvimento!
Já dominamos o mercado com um produto antigo em desktop e agora queremos lançar essa nova aplicação Web e aplicativos também, oferecendo a melhor experiência para os nossos clientes e os futuros também... 
O mercado do ramo que atuamos aqui no Brasil já é dominado pela TOTVS, agora estamos querendo dominar o mundo. O projeto já está nascendo internacionalizado, muitos desafios técnicos, qualidade e performance é o que buscamos!

Tecnologias usadas:
* Angular 4
* Testes unitários com Jasmine
* HTML
* CSS
* Webpack

## Local
Alocado no centro do Rio de Janeiro, perto da estação Uruguaiana.

## Benefícios

- Plano de saúde
- Plano de odontológico
- Seguro de vida
- VR de R$ 24/dia
- VA de R$ 80/mês
- Vale transporte 

#### Diferenciais
- Lounges com café, chocolate e outras bebidas FREE
- Sala de Jogos
- PDI(Plano de Desenvolvimento Individual)
- Equipe unida
- Palestras, meetups e estamos abertos sempre a novas idéias para o time crescer

## Requisitos
**Obrigatórios:**
- Possuir conhecimentos de integração utilizando API RESTful;
- Conhecer e ter experiência com testes unitários
- Ter facilidade para trabalhar em equipe(pair programming, code review...)
- Saber escrever código limpo e legível;
- Saber trabalhar com ferramentas de controle de versão;

**Desejáveis:**
- Amar Javascript
- Saber CSS/HTML para criar componentes pois nosso projeto é 100% componentizado
- Ter disponibilidade de horário
- Ter disponibilidade para viajar para outros estados e mais pra frente outros países
- Ter sede de aprender e passar conhecimento para equipe

**Diferenciais:**
- Contribuição em projetos opensource
- Angular 2
- React

## Contratação

CLT - Júnior, Pleno ou Sênior

## Nossa empresa

A TOTVS é uma empresa brasileira de software, serviços, plataforma e consultoria. É líder absoluta no Brasil e na América Latina e está entre as maiores desenvolvedoras de sistemas de gestão integrada do mundo.

## Como se candidatar

Por favor envie um email para yoseph.santos@bematech.com.br com seu CV anexado e com o link do seu linkedin - Enviar no assunto: Vaga FrontEnd na TOTVS

**Prazo para se candidatar: até o dia 10/12/2017**

**Comment by ribeiroevandro** [comment]
A vaga é bem irada e só fiquei confuso com o VA de R$ 80,00 por mês, esse benefício não é o que se usa geralmente para fazer compras em mercado. O que se compra com esse valor?

**Comment by fejaum** [comment]
@ribeiroevandro Você consegue comprar 40 pacotes de bolacha ou biscoito (depende da sua crença), dura 20 dias, um no almoço e um na janta!

**Comment by LFeh** [comment]
Devem ter errado, rs

**Comment by yosephcsantos** [comment]
É mais simbólico esse valor rs
