### ISSUE TITLE
[Remoto] Estágio Full-Stack Developer na Whats

### ISSUE THREAD

**Issue by gabrielalmeida** [frontendbr/vagas#4852]
![untitled](https://user-images.githubusercontent.com/310382/41541952-19c8bf76-72ea-11e8-88e7-bfe702bf4187.png)

Procuramos um(a) estagiário(a) dev para ajudar a compor a nossa equipe. Somos uma empresa jovem que tem como missão otimizar o relacionamento de grandes marcas com seus consumidores, através de tecnologia e comunicação. Você trabalhará em componentes para clientes como: GSK, L'Oréal, Globo, Itaú, Coca-Cola e outros.

Buscamos uma pessoa que tenha uma breve experiência com as tecnologias listadas abaixo e esteja bem interessada em aprender novas soluções.

Acompanharemos e auxiliaremos o desenvolvimento de cada etapa da rotina de trabalho, mas proatividade e autonomia são características importantes que necessitamos na equipe.

As responsabilidades são:

- Trabalhar na criação de componentes web prezando fidelidade aos aspectos gráficos/funcionais
- Consumir APIs para implementação dos componentes
- Trabalhar na entrega de protótipos, POCs
- Buscar seguir boas práticas de desenvolvimento: convenções, guidelines, reviews
- Ter interesse em aprender novas tecnologias, encarar desafios
- Ser engajado, somos uma equipe enxuta e todos participam de tomadas de decisões
- Ser consistente: o ótimo é o bom feito repetidamente

## Local

Remoto

### Obrigatórios:
Muita vontade de aprender, interesse em interfaces web e em tecnologia. 
Se sentir confortável com HTML/CSS, Javascript & Git

> Be a worker… and be prepared to show it! Everyone is responsible for making awe-something, building product, owning decisions, selling something, hustling. You can’t just show up at the meetings.

### Desejáveis:
- React
- JS ES6 (Promises, Async/await, etc)
- Typescript
- GraphQL
- FP
- Linux
- Se sentir confortável em usar CLIs

## Contratação
Estágio

Tipo de vaga: Estágio 6h/d
Flexibilidade de horário
No dress code
Bolsa: R$1.500,00 /mês

## Como se candidatar
Acesse https://whats.ws/jobs

Nossa política de feedbacks está anexada no link acima. 

#### Alocação
- Remoto

#### Regime
- Estágio

**Comment by RutielyMiranda** [comment]
Boa noite, essa vaga ainda está disponível?

**Comment by leviermonaites** [comment]
Não está sendo possível fazer o processo pois a vaga não aparece para ser escolhida no preenchimento.

**Comment by Al3xsandro** [comment]
Mesmo problema aqui, a vaga não aparece escolhida no preenchimento.

**Comment by temppone** [comment]
Aqui também não consigo finalizar o cadastro pra vaga

**Comment by gabrielalmeida** [comment]
Olá, pessoal! Peço desculpas pelo problema no formulário, foi realizada a correção. 

Ainda temos vagas disponíveis para essa posição.

**Comment by Leveditor** [comment]
Boa noite, essa vaga ainda está disponível?

**Comment by gabrielalmeida** [comment]
Boa noite, vaga ainda aberta

**Comment by Leveditor** [comment]
Ok Obrigado. Currículo encaminhado

Em qua., 7 de jul. de 2021 11:43 PM, Gabriel Almeida <
***@***.***> escreveu:

**Comment by wellbenicio** [comment]
A vaga ainda está aberta? @felipefialho

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
