### ISSUE TITLE
[REMOTO] Front-end Developer na Softmakers

### ISSUE THREAD

**Issue by dheysonalves** [frontendbr/vagas#4853]
## Nossa empresa

Somos um time colaborativo, curioso, enfrentamos desafios diariamente e valorizamos a liberdade, autonomia e responsabilidade. Se você se identifica com esses valores e gosta de criar soluções com impacto positivo na vida das pessoas, queremos te conhecer, traga seu talento para nosso time!

[Website da Softmakers](https://www.softmakers.com.br/)
[Github da Softmakers](https://github.com/BrSoftMakers)

## Local

Remoto ou Escritório em Caruaru, Pernambuco

## Requisitos

**Obrigatórios:**
* HTML
* CSS
* JavaScript
* ReactJS
* React Native
* REST API

**Desejáveis - Não obrigatórios:**
- conhecimentos em PHP
- conhecimentos em Node.Js

**Diferenciais:**

Habilidades que aumentam as suas chances:

* Conhecimento sobre Jenkins, GIT, CI/CD, Github Actions, Docker e Redis;
* Ter participado de um time Scrum;
* Conhecimento de biblioteca do Jquery

## Benefícios

* Benefícios: VA, Amazon Prime, Youtube Premium

**Diferenciais:**
* Ambiente de trabalho saudável e dinâmico

## Contratação

CLT e Estágio pelo CIEE

## Etapas

O processo será dividido em 2 etapas simples, que são:

- 1º Análise técnica do projeto apresentado

- 2º Análise comportamental, análise de sinergia com a essência da SoftMakers;

## Como se candidatar

Por favor se cadastrar a partir do link a seguir e tipo de vaga: [Formulário das vagas](https://linktr.ee/softmakersbr)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: lillyane.oliveira@softmakers.me

#### Alocação
- Remoto para Júnior/Pleno
- Presencial em Estágio

#### Regime
- CLT
- Estágio

#### Nível

- Estágio
- Júnior
- Pleno

Caso não tenha todas as habilidades, não tem problema, somos um time que valorizamos o conhecimento e crescimento da equipe.

**Comment by WendelSantosNunes** [comment]
O estágio é remoto ?

**Comment by dheysonalves** [comment]
Olá @WendelSantosNunes , apenas junior/pleno são remotos :/
