### ISSUE TITLE
[Remoto] Front-end Developer na Dotz

### ISSUE THREAD

**Issue by danielasantosrh** [frontendbr/vagas#4855]
> 
## Nossa empresa

Dotz (https://www.dotz.com.br/), uma das empresas líderes em programas de fidelização da América Latina, busca em parceria com a Tecer (https://tecer.us/), umx profissional que atue com protagonismo e engajamento.

A empresa está presente em diversas cidades do Brasil, atua com uma postura jovem e dinâmica, e conta com uma equipe colaborativa e apaixonada pela sua causa: ser a moeda que faz a vida render mais – para as pessoas e para as empresas.

## Descrição da vaga

Você poderá contribuir em projetos grandes com tecnologia de ponta e oportunidades de crescimento.
Você também terá:
- Flexibilidade para atuar em diferentes projetos
- Autonomia
- Desafios
- Valorização pessoal e profissional: aqui a sua sugestão é bem-vinda e as decisões são tomadas em conjunto

Remuneração compatível com o mercado

**O que você irá fazer?**
Codificar sistemas de média/alta complexidade;
Codificar testes unitários;
Documentar código fonte / sistemas;
Planejar, organizar e reportar atividades (tarefas);
Desenvolver cenários de testes;
Desenhar protótipos (storyboard);
Diagnosticar problemas de aplicativos;
Elaborar fluxogramas;
Elaborar modelos de dados (MER/DER);
Homologar sistemas, treinar usuários.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 4 anos de experiência em desenvolvimento web
- Conhecimento em HTML, CSS, JavaScript, Angular 7+
- Inglês Técnico
- Superior cursando ou completo

**Desejáveis:**
- React ou React Native.

## Benefícios

PJ + férias, 13°, PLR, benefícios flexíveis (R$ 820,00) + programa render mais (https://www.vagasdotz.com/programa-render-mais)

## Contratação

PJ 

## Como se candidatar

Por favor envie um email para f.selecaorh@gmail.com com seu CV anexado - enviar no assunto: Dev Front End

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: f.selecaorh@gmail.com

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by danielasantosrh** [comment]
Ainda temos vaga :)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
