### ISSUE TITLE
[Pelotas-RS] Front-End Developer na [Atlas Technologies]

### ISSUE THREAD

**Issue by join-atlastechnol** [frontendbr/vagas#4858]
**Atlas Technologies:**

https://jobs.kenoby.com/atlastechnol

## Descrição da vaga

**Atuar:**

Atuar com programação e desenvolvimento de interfaces WEB utilizando Blade Templates e **Vue.js Framework.**
Trabalhar em pequenos times que utilizam metodologias ágeis para entregar valor constante aos nossos clientes.

**Necessário:**

Forte capacidade de trabalhar colaborativamente como parte de uma equipe.
Conhecimento em HTML e CSS.
Conhecimento Javascript moderno(ES6) e JQuery.
Conhecimento em Design Responsivo.
Conhecimento em padrões de CSS como BEM ou SMACSS.
Conhecimento do uso básico de versionamento GIT.
Conhecimento no consumo de APIs.

**Diferencial:**

Conhecimento e experiência no framework Laravel (PHP) e Blade Templates.
Conhecimento em pré-processador SASS e Webpack.
Conhecimento em frameworks como Vue.js e React.
Conhecimento em pattern de gerenciamento de estado como Vuex e Redux.
Habilidade e preocupação com a excelência técnica e boas práticas de desenvolvimento.

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para join@atlastechnol.com com seu CV anexado - enviar no assunto: Vaga VueJS

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
