### ISSUE TITLE
[REMOTO][São Paulo] Front-end Developer na Mccann Health

### ISSUE THREAD

**Issue by w3solution** [frontendbr/vagas#4859]
## Mccann Health

A McCann Health é a comunidade de especialistas em saúde e bem-estar mais conectada do mundo e unida por um propósito: ajudar as marcas de nossos clientes a desempenhar um papel significativo na vida das pessoas. Esse compromisso concentra nossos 1.900 funcionários em todo o mundo na geração de ideias que mudam a vida e que melhoram a saúde das pessoas.

Temos 60 escritórios em 20 países e em seis continentes, que abrangem uma variedade de serviços especializados no segmento Healthcare, incluindo consultoria estratégica em comunicação, campanhas de marcas e de produtos, estratégia de acesso e de valor, marketing para profissionais de saúde, educação médica, promoção de medicamentos Rx e OTC, campanhas de awareness e de conscientização sobre doenças e formas de prevenção, campanhas de suporte e adesão de pacientes.

A McCann Health faz parte do McCann Worldgroup e do Interpublic Group (IPG).

## Descrição da vaga

Responsável pelas entregas de sites, landing pages, CMSs, e-mail marketing, banners com animação HTML5, entre outras plataformas.

## Local

São Paulo[Remoto]

## Requisitos

**Obrigatórios:**

- Amplos conhecimentos em: HTML5, CSS3, JavaScript (jQuery), SASS;
- Noção de UX/UI;
- Controle de versão (Git/Bitbucket);
- Experiência em desenvolvimento web front-end;
- Boas práticas de códigos e detalhes, padronização, documentação, QA e segurança da informação;
- Conhecimento de SEO, aplicação de tageamento, ferramentas de performance de código;
- Integração com APIs públicas (Facebook, Google Maps);
- Wordpress.

**Desejáveis:**

- ReactJS e/ou React Native;
- Noções de NodeJS e/ou PHP;
- Desenvolvimento em diferentes tipos de CMS;
- Olhar construtivo, busca constante pela entrega de excelentes projetos;
- Busca por inovações que agreguem valor ao trabalho (novas tendências de linguagens de programação, ferramentas que tragam melhorias no ciclo de entrega etc).

**Diferenciais:**

- Consideraremos um diferencial conhecimentos em: Vue.Js; GreenSock.

## Contratação

PJ ou CLT à combinar

## Como se candidatar

Enviar para rh@mccannhealth.com.br
Assunto do email: Vaga Front Pleno - SEU NOME

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
