### ISSUE TITLE
[São Paulo] Front-End Developer na RoutEasy

### ISSUE THREAD

**Issue by williamknn** [frontendbr/vagas#486]
## Descrição da vaga

Se você é motivado por desafios técnicos, mais especificamente sobre desenvolvimento de aplicações de alto impacto no cotidiano das empresas, gostaríamos muito de falar com você!

Procuramos desenvolvedores com alta capacidade analítica, automotivados, que se preocupem com a qualidade e organização do código e que seja bom no FIFA 2013. Sim, gostamos dessa versão do FIFA :) 
PS: _atualmente_ estamos jogando mais CS.

Seu desafio será ajudar a criar a melhor solução de otimização logística para ajudar empresas a reduzirem custos e crescerem de forma sustentável!

Nós utilizamos MEAN Stack em toda a nossa solução. Você trabalhará principalmente na parte de frontend (AngularJS) apoiando no desenvolvimento de novas funcionalidades, novas telas e comunicação com nossa API REST.

## Local

Escritório, São Paulo - Próximo ao metrô Saúde
## Benefícios
- Salário compatível com mercado, regime PJ.
- Ambiente de Startup: convivência com pessoas automotivadas em aprender e se desenvolver mais.
- Todos os dias temos uma competição para ver quem é o Rei do FIFA!
- Participar da fase de expansão de uma das empresas de tecnologia mais promissoras do Brasil!

## Requisitos

- AngularJS
- JavaScript (puro)
- HTML5
- CSS3
- SASS
- RWD
- Grunt / Gulp
- Bower / NPM
- Bootstrap / Angular UI Bootstrap
- GIT e Github
- Consumo de API REST

**Diferenciais:**
- Alta capacidade analítica e raciocínio lógico;
- Conhecimentos na escrita de códigos de qualidade;
- Disposição para aprender muito e escrever muitas linhas de código;

## Contratação

PJ a combinar

## Nossa empresa

![routeasy-horizontal_180](https://cloud.githubusercontent.com/assets/3988151/17674989/32f6b60e-62fe-11e6-8f63-6bbed84a1025.png)

A RoutEasy é uma startup na área de logística. Nossa solução ajuda empresas no trabalho diário de planejamento da distribuição, otimizando a construção das cargas e o roteiro dos veículos. Nosso algoritmo de otimização é proprietário, desenvolvido pelos fundadores e o nosso histórico é de 10% à 40% do custo de transporte.
## Como se candidatar

Preencha o formulário em "Apply for this opening" nesta página: https://routeasy.recruiterbox.com/jobs/fk0fh5p

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by williamknn** [comment]
@LFeh tinha esquecido da issue, pode fechar!
