### ISSUE TITLE
[REMOTO] Front-end Developer na TUNTS

### ISSUE THREAD

**Issue by Rafa3407** [frontendbr/vagas#4860]
Vaga Remota, empresa localizada em Curitiba. 

Estamos vivendo momentos incríveis, estamos crescendo em um ritmo muito acelerado. O motivo para isso é a nossa equipe, e gostaríamos que os melhores se juntem a nós. Buscamos pessoas que tenham comprometimento e que sejam apaixonadas por tecnologia. Se você possui essa paixão e quer se sentir desafiado, motivado e valorizado todos os dias, faça parte do nosso Time!!!

Trabalhar com desenvolvimento front-end de projetos inovadores e desafiadores, utilizando as técnicas mais modernas de desenvolvimento front-end.

**Main responsibilities**
JavaScript Avançado
Bom conhecimento em Angular ou React JS
HTML/CSS
Bibliotecas e componentes NPM
Padrões de projeto e arquitetura (Design Patterns)
Web APIs Rest
Metodologias ágeis como Scrum

**Obrigatórios**
Facilidade de comunicação e proatividade
Perfil autodidata
+6 meses de experiência profissional
Metodologias ágeis como Scrum
Padrões de projeto e arquitetura (Design Patterns)
Web APIs Rest
Conhecimento de Design patterns de web components

**Desejáveis**
Conhecimento em Selenium ou equivalente
UnitTest com Jest ou Jasmine
Conhecimento de Design patterns de web components

**Benefícios**
Vale Alimentação/Refeição
Plano de Saúde/Odontológico
Seguro de vida

Venha para Tunts!!!!

## Como se candidatar

Por favor envie um email para julliana.possenti@tuntscorp.com com seu CV anexado - enviar no assunto: [REMOTO] Front-end Developer na TUNTS

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
