### ISSUE TITLE
[Remoto] Front-end Developer na Approvata

### ISSUE THREAD

**Issue by kvilela** [frontendbr/vagas#4862]
## Local

Remoto

## Requisitos
HTML, CSS e JS

## Diferencial
Experiência com plataforma Vtex. 

## Contratação
CLT  + benefícios

## Como se candidatar

Por favor envie um email para karina.vilela@approvata.com.br com seu CV anexado - enviar no assunto: Front End Developer GitHub

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Junior

**Comment by joao160197** [comment]
Ain está aberta a vaga ?

**Comment by kvilela** [comment]
sim

Karina Parise Vilela

Em seg, 14 de jun de 2021 20:06, joao160197 ***@***.***>
escreveu:

**Comment by joao160197** [comment]
É necessário ter experiência prévia ?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
