### ISSUE TITLE
[BH-Remoto] Front-end Developer na Rumo Soluções

### ISSUE THREAD

**Issue by brunoheringer** [frontendbr/vagas#4863]
## Nossa empresa [Rumo Soluções](https://www.rumosolucoes.com)
QUEM SOMOS NÓS? :)
A Rumo Soluções é uma empresa com mais de 20 anos de experiência no mercado. Fundada em 1997, a empresa construiu uma trajetória de sucesso em importantes áreas do setor privado e se tornou uma das grandes empresas em solução digital do estado de Minas Gerais. Desde 2004, a Rumo se especializou como fábrica de software, atuando com serviços ágeis, desenvolvimento de software e outsourcing.  

Hoje buscamos novos talentos que apostam na inovação, sejam comprometidos, engajados com a sua carreira e que valorizem relações verdadeiras. Você se identificou com a gente? Faça parte do nosso time e conheça os motivos pelos quais somos uma das empresas de TI com a melhor nota de avaliação orgânica no Glassdoor. 

## Descrição da vaga
**É necessário que você tenha sólidos conhecimentos em:**
- `React Native` , `JavaScript` `TypeScript`. `CSS / HTML`  
- Banco de Dados (Preferência: SQL-Server);
- 2 anos de experiência com desenvolvimento React Native
- 3 anos de experiência com desenvolvimento React Js

**Será relevante se você conhecer também sobre:**
- Análise, design e codificação;
- WebAPI – Rest/Restfull;
- Princípios SOLID.

**Diferenciais:**
- Firebase;
- Conhecimentos práticos em TDD (Test Driven Design) / Teste Unitário;
- Práticas DevOps (CI/CD/Code Review ...);
- Conhecimento no Azure DevOps;
- Conhecimento de Docker /Kubernetes;
- Conhecimento em .Net Core;
- Projetos Open Source.

## Formação 
Desejável em algumas das áreas abaixo:
- Engenharia de Software
- Ciência da Computação;
- Sistemas de Informação
- Tecnólogo em ciência da Computação
- Áreas correlatas.

### Para o bolso:
- Salário compatível com a experiência (Envie sua pretensão);
- PL (Participação nos Lucros); 
- Todos os benefícios sem desconto em salário.
     
### Para a alimentação:
- Vale Refeição;
- Vale Alimentação.

### Para a locomoção:
- Vale Transporte ou vale combustível.
 
### Para a saúde:
- Plano Odontológico SulAmérica;
- Plano de Saúde SulAmérica;
- Seguro de Vida.

### Para o bem-estar:
- Carga Horário de 40h semanais (Segunda a sexta);
- Horário Flexível;
- Convênio com SESC; 
- Benefícios, inclusive nas férias.

### Para o conhecimento atualizado:
- Parceria no aprendizado de Idiomas;
- Workshops Técnicos (temas variados);
- Auxílio Educação (graduação e pós graduação).

## Contratação
- CLT - Home Office ou Híbrido conforme sua escolha

## Nossa empresa

QUEM SOMOS NÓS? :)
A Rumo Soluções é uma empresa com mais de 20 anos de experiência no mercado. Fundada em 1997, a empresa construiu uma trajetória de sucesso em importantes áreas do setor privado e se tornou uma das grandes empresas em solução digital do estado de Minas Gerais. Desde 2004, a Rumo se especializou como fábrica de software, atuando com serviços ágeis, desenvolvimento de software e outsourcing.  

Hoje buscamos novos talentos que apostam na inovação, sejam comprometidos, engajados com a sua carreira e que valorizem relações verdadeiras. Você se identificou com a gente? Faça parte do nosso time e conheça os motivos pelos quais somos uma das empresas de TI com a melhor nota de avaliação orgânica no Glassdoor. 

## Como se candidatar
Acesse nosso site e se cadastre na vaga desejada. 
www.rumosolucoes.com.br

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@rumosolucoes.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
