### ISSUE TITLE
[Remoto] Front-end Developer Senior na Tweak

### ISSUE THREAD

**Issue by ericaprieto** [frontendbr/vagas#4867]
## Nossa empresa

Tweak is an Irish tech-company founded in 2008. We are a B2B company that focus on automating brand management with online editing for medium and large companies.We have pioneered the future of highly efficient workflows for online design, brand management and the curation, sharing and storage of digital assets critical to organizations.

## Descrição da vaga

- Design, implement, deploy, and maintain front-end systems that are the backbone of the company business
- Develop tools which facilitate the work of other teams and make them go faster.
- Develop and monitor platforms on which we concentrate our current production stack.
- Detect and fix problems in the production environment.
- Contribute to the best practices of development, reliability, and availability of our systems.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- +5 years experience as a front-end engineer
- +3 years Commercial experience with ReactJS
- JavaScript, CSS and Semantic HTML
- Webpack or any other bundler
- Fluent English

**Desejáveis:**
- HTML Canvas/FabricJS
- Commercial experience with AngularJS
- Knowledge in NodeJS

## Contratação

PJ a combinar

## Como se candidatar

Please send a copy of your CV to stephen@tweak.com.

## Tempo médio de feedbacks

We usually send feedback within 3 days.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
