### ISSUE TITLE
[Porto Alegre] Front-end Developer Pleno na Vnda Ecommerce

### ISSUE THREAD

**Issue by isadoracribeiro** [frontendbr/vagas#4868]
## Nossa empresa

A Vnda é uma empresa de tecnologia para varejo, com um SaaS (software como serviço), oferecemos soluções de digitalização do varejo, por meio de uma plataforma de e-commerce própria, com visão Omnichannel.

Acreditamos que marcas devem inspirar pessoas e que as relações vão além das transações. 

Defendemos o ideal de um varejo emocional, que vai além do foco nas características funcionais dos produtos, explorando também a diferenciação em conceito e em experiência de cada marca.

Nossa sede fica em Porto Alegre - RS, mas nossa base de clientes é composta por negócios do Brasil inteiro, dos mais diversos segmentos do varejo.  

## Descrição da vaga

Acreditamos que todos podem colaborar para que os projetos tenham a melhor qualidade possível, por isso montamos um processo de criação onde todos os envolvidos tem liberdade para ter ideias e tomar decisões que os aperfeiçoem.

Na Vnda você fará parte de um de nossos squads, onde desenvolverá projetos completos de e-commerce,  afim de entregar a melhor experiência de marca para nossos clientes por intermédio do nosso time de Project Owners.

Será instigado a contribuir com ideias para projetos, primando sempre pela qualidade estética e técnica do resultado final, codificando layouts web através de Wireframes desenvolvidos pelo nosso time de Designers. 

Também trabalhará no suporte e melhoria de lojas ativas, atendendo a demandas de clientes e criando soluções junto ao nosso time de Customer Success.

Você terá a oportunidade de contribuir com o desenvolvimento de componentes em React dependendo do seu nível de conhecimento, criando e testando funcionalidades, performance e usabilidade, em troca constante com nosso time de Infraestrutura.

Além disso, você terá a oportunidade de vir a se tornar um líder técnico dentro de nossos squads, trabalhando na organização e direcionamento de demandas, além de auxiliar no desenvolvimento técnico e pessoal dos membros de sua equipe.

## Local

Remoto ou Escritório, [RS], [Porto Alegre], [Auxiliadora]

## Requisitos

**Obrigatórios:**
# Competências pessoais

- Vontade de aprender e crescer;
- Paixão pelo que faz;
- Compromisso com qualidade e agilidade;
- Comunicação com o time afim de buscar sempre a melhor solução para nossos clientes;
- Senso de design e estética;
- Estar por dentro das novas tecnologias de mercado;
- Organização e cultura criativa;
- Capacidade de liderança.
 
# Competências técnicas

- HTML semântico;
- CSS Avançado (SASS, transições, animações e design responsivo sem o uso de frameworks);
- Javascript Intermediário (Vanilla JS, JSON, AJAX, manipulação do DOM);
- Vivência em projetos com foco em Design e UX;
- Codificação de layouts web partir de wireframes;
- Git;
- Inglês técnico (leitura);

**Diferenciais:**
- Experiência com desenvolvimento de projetos em e-commerce utilizando alguma linguagem de template;
- Experiência em desenvolvimento de componentes ou aplicações em React;
- Experiência em melhorias de performance;
- Experiência com metodologias ágeis;
- Conhecimento sobre alguma linguagem de back-end;
- Conhecimento sobre SEO;
- Conhecimento sobre banco de dados;

## Benefícios

- Salário compatível com mercado e nível de desenvolvimento técnico;
- Plano de carreira com avaliações trimestrais;
- Plano de Saúde Unimed;
- Plano Odontológico Uniodonto;
- Vale Alimentação / Vale Refeição;
- Possibilidade de regime de trabalho Presencial, Home Office ou Híbrido.

## Contratação

CLT / PJ

## Como se candidatar

Por favor, preencha o forms através do link: https://docs.google.com/forms/d/e/1FAIpQLScadi2S-rxjcNbPG4veHyFaM3ykFk2SjbTsexKi2-TSeB3MDA/viewform?gxids=7628

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: pp@vnda.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
