### ISSUE TITLE
[Porto Alegre] Front-End Developer  na HOLDEN

### ISSUE THREAD

**Issue by jokapoa** [frontendbr/vagas#487]
## Descrição da vaga

Holden   TI ( www.holdenrh.com.br). Consultoria especializada em recrutamento e seleção para a área de tecnologia seleciona para empresa de grande porte localizada na região de Porto Alegre - RS

## Local

Escritório  - Porto Alegre - Rio Grande do Sul

## Benefícios

- Plano de saúde
- Seguro de vida
- Refeitório
- Aux Educação ( 80%) para graduação
- 40% para pós graduação

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com AngularJs, NodeJs, 
- 2 anos de experiência com mongodb e express

**Desejáveis:**
- conhecimentos em Oracle, PL-SQL
- conhecimentos em desenvolvimento  para mobile

## Contratação

CLT

## Nossa empresa

Área de tecnologia de empresa de grande porte

## Como se candidatar

Por favor envie um email para jonask@holdenrh.com.br com seu CV anexado

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by jokapoa** [comment]
Olá  Felipe,
Estou com  2 vgas sim :)

2018-01-23 14:06 GMT-02:00 Felipe Fialho <notifications@github.com>:

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
