### ISSUE TITLE
[Remote] Front-end Developer na Ipanema.Tech [12k-15k]

### ISSUE THREAD

**Issue by givigier** [frontendbr/vagas#4870]
## Ipanema.Tech

We are a software development company focused on Financial products that help businesses to create/maintain great products to support their business. We are focused on Ruby on Rails and JavaScript and most of our clients are from North America and Europe. For this position, you're gonna work for a company of the Silicon Valley.

We believe that code quality is extremely important to create a successful project in the long term and we value crafting beautiful UIs. We value a peaceful work environment and we don't expect developers to work more than 8 hours/day. Also, weekends are to have fun and to relax.

We are a remote-only company, so we expect you to feel comfortable to work from home/coworkings.

## Descrição da vaga

We are looking for Mid Senior and Senior JavaScript developers with good knowledge about React. On this project, you will be part of a Silicon Valley startup that values awesome UIs. So you'll need to work and also suggest improvements on beautiful UIs. We expect you to create a well-organized React project following all the best practices from the industry. If you have more questions about the job, feel free to reach us, we're welcome to answer your questions.

## Local

Remote only

## Requisitos

**Obrigatórios:**
- JavaScript: 4+ years of experience
- CSS
- React: 3+ years of experience

**Desejáveis:**
- Automated Tests

## Contratação

- PJ

## Como se candidatar

Please send an email to contact@ipanema.tech with your Github, Linkedin, and a brief description of you.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: contact@ipanema.tech

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by lucasalmeida92** [comment]
Just sent an email @givigier ! ;]

**Comment by givigier** [comment]
Thanks @lucasalmeida92 !
