### ISSUE TITLE
[Todos os Estados] Full Stack Developer (Java/Angular) na MJV Tecnologia e Inovação

### ISSUE THREAD

**Issue by Ys2801** [frontendbr/vagas#4873]
> Vaga 100 % Remota 

## Nossa empresa

Somos a MJV uma empresa focada em tecnologia e inovação, com mais de 21 anos no mercado, com escritórios no Rio de Janeiro, São Paulo, Curitiba, Roma, França, Londres, Colômbia e Estados Unidos. Atuando dentro dos maiores clientes como Bradesco Seguros, Santander, Sulamérica, Safra.

Somos colaboradores, ágeis, plurais, criativos e inovadores.
Somos pessoas transformando negócios! 💡
Somos MJV!

## Descrição da vaga

Estamos buscando um Desenvolvedor FullStack (Java/Angular) para transformar o mercado!

Sobre o desafio �

Será responsável por por criar a interface de utilização de um site ou aplicação web. A camada visual das aplicações web, na qual os usuários interagem; criar websites, landing pages, hotsites, blogs ou aplicações web otimizadas e responsivas; realizar a manutenção e melhoria constante dessas plataformas; garantir que plataformas funcionem bem em diferentes navegadores e dispositivos; trabalhar juntamente com desenvolvedores Back-end e Web Designers para garantir os melhores visuais e funcionabilidade; e criar mockups e protótipos de qualidade.

## Local

100% remoto

## Requisitos

**Obrigatórios:**
- Conhecimento em workflow e mapeamento de processos com ferramentas de BPM (Camunda), mecanismos de integrações entre processos e sistemas com Java, utilizando SpringBoot, JPA, Hibernate, webservice e arquivos JSON. 
- Desenvolvimento com Angular 2+
- Conhecimentos em: 
· Java 8, XML, WSDL, Web Service SOAP e JAX-WS,
· JBOSS,
· JEE - MVC,
· Spring Boot,
· Spring Data, Spring, API Restfull e manipulação de arquivos JSON.
· Banco de dados Oracle, etc.

## Benefícios

- Plano de saúde
- Seguro de vida
- VR 
- VA
- Plano odontológico

## Contratação

CLT

## Como se candidatar

Por favor envie um email para yasmin.ferreira@mjv.com.br com seu CV anexado - enviar no assunto: Vaga Full Stack

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: yasmin.ferreira@mjv.com.br

#### Alocação

- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
