### ISSUE TITLE
[Remoto] Front-end Developer iOS na Klever

### ISSUE THREAD

**Issue by tiagobk** [frontendbr/vagas#4876]
## About us:

Klever app is a simple, secure p2p crypto wallet for blockchain with support for Bitcoin (BTC), TRON (TRX), Ethereum(ETH), and other top tokens, coins, and cryptocurrency assets. 

## Responsibilities:

Improving system quality by identifying issues and common patterns, and developing standard operating procedures;
Enhancing applications by identifying opportunities for improvement, making recommendations, and designing and implementing systems;
Maintaining and improving existing codebases and peer review code changes;
Liaising with colleagues to implement technical designs;
Investigating and using new technologies where relevant;
Providing written knowledge transfer material.

## Local:

Work from wherever you want!

## What do we expect from you:

+2 years of hands-on experience Javascript
Advanced knowledge of ReactJS, Redux, Hooks, Vue
Advanced HTML5, CSS3
Strong knowledge of JavaScript and data structures
Ability to learn quickly and operate in a fast-pasted environment
Experience and proven ability with developing and/or designing web applications with high fidelity to the design
Creative problem solvers
Excellent communication skills

## What we offer:

- Freedon to work when and from everywherre 
- Monthly allownce  BRL 1.200,00
- A collaborative, respectfull and free work enviroment

## Contract:

-Legal entity

## How to apply:

https://klever.gupy.io/jobs/649798

Join us!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
