### ISSUE TITLE
[São Paulo] Front-End Enginner na PEDDI

### ISSUE THREAD

**Issue by ghost** [frontendbr/vagas#488]
## Descrição da vaga

A Peddi está desenvolvendo um projeto que vai mudar a forma como as pessoas fazem pedidos e pagamentos em restaurantes. Para isso, estamos montando um time de desenvolvimento com muito potencial de crescimento dentro da empresa.

## Local

Av. Jandira, 295 - São Paulo, SP - Indianópolis

#### Diferenciais

- Participação nos lucros da empresa
- Aumento da remuneração em dois meses
- Bônus por resultado
- Alto potencial de crescimento

## Requisitos

- Experiência com Node.js, Angular 2 e Ionic 2
- Experiência com mongoDB

## Contratação

PJ a combinar

## Nossa empresa

A Peddi é uma empresa de tecnologia formada por pessoas apaixonadas pelo que fazem e que, acima de tudo, estão dedicadas a mudar a vida das pessoas que se alimentam fora do lar.

## Como se candidatar

Por favor envie um email para contato@peddi.com.br com seu CV anexado - enviar no assunto: Vaga Peddi

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
