### ISSUE TITLE
[Indaiatuba] Front-end Software Engineer (Banco John Deere) 

### ISSUE THREAD

**Issue by leticiamourawyser** [frontendbr/vagas#4881]
**Nossa empresa**

Empresa americana, líder mundial em seu segmento no Brasil e Mundo atuando com manufatura/indústria focada em construção de soluções digitais e financeiras, busca Frontend Software Engineers (Plenos e Seniores) para atuar com soluções globais e locais para o banco da Instituição.

·Oportunidade fulltime remota durante a pandemia e parttime remoto após.

Descrição da vaga:

Serão responsáveis por construir uma nova cultura de software, arquitetura e tecnologia de uma operação bancaria, sustentando e desenvolvendo novos produtos digitais que impulsionarão o crescimento e a inovação da empresa no mercado. Trabalhando com tecnologia de ponta e estruturando o conceito de desenvolvimento do zero. #serverless #microservices #aws #cloud #refactoring #javascript #typescript #react #microfrontend

Responsabilidades:

Como Software Engineer, você projetará e desenvolverá software para os produtos e estará envolvido com a implementação técnica dos pontos de integração de sistemas.

Além disso, você vai;

- Operar dentro de uma equipe Ágil e participar de todos os aspectos do trabalho dessa equipe em relação à análise, desenvolvimento, teste e suporte de software;
- Membro ativo da equipe na contribuição para as práticas técnicas da equipe, alavancando os padrões do setor para as práticas de desenvolvimento;
- Colaborar / contribuir com membros da equipe na arquitetura do produto, escalabilidade e integrações;
- Colaborar com outros grupos da empresa sobre as integrações entre os sistemas;
- Trabalhar em conjunto com outros membros da equipe no desenvolvimento de uma cultura DevSecOps . As práticas incluem, mas não se limitam a TDD, Testes Automatizados, CI/CD, Monitoramento e Suporte.

Local
Oportunidade fulltime remota durante a pandemia e parttime remoto após em Indaiatuba - SP.

Requisitos

- Formação Superior completo em Engenharia de Computação, Ciência da Computação ou relacionado;
- Inglês no mínimo de intermediário para conversação, pois terá forte interação com times de engenharia internacionais;
- Experiência atuando como Paring Code, XP e outras ações/metodologias para desenvolvimento em time;
- Conhecimento e experiência com Arquitetura desde cloud (AWS), segurança à IaC;
- Experiência em ambientes de metodologia Ágil, princípios de DevOps e CI/CD;
- Experiência em desenvolvimento para frontend, usando, Javascript React, jQuery, HTML e CSS, incluindo APIs RESTful ou SOAP;
- Domínio em tecnologias de banco de dados Relacional e/ou noSQL;
- Conhecimento em práticas de teste automatizado e Test Driven Development TDD;
- Experiência colaborando com stakeholders para solucionar problemas através de soluções digitais;
- Certificações ágeis, Certified Scrum Master e outras. [Diferencial]

Benefícios

- Oportunidade de criar do zero uma estrutura digital e produtos, com aplicação prática + gerenciamento + estratégia de um ambiente internacional com um time global.
- Trabalhar na maior e mais rentável empresa do segmento no mundo, morando em Indaiatuba, uma das cidades c/ maior índice de qualidade de vida do Brasil, perto de São Paulo - SP em um ambiente de trabalho que acredita no equilíbrio entre carreira e vida pessoal.
- Contrato CLT + VA no valor de R$ 609,00/mês + VR de R$ 35,00/dia (+- R$ 770,00/mes) + Fretado (Saindo de Campinas) ou VT dentro de Indaiatuba + PLR entre 2 salários e 3 salarios/ano atrelado ao desempenho da empresa.
- Previdencia Privada + AM Unimed + AO Bradesco + Auxilio Farmácia + Reembolso de 40% na compra de lentes de contato ou lentes de óculos de grau ou de sol + Campanha de Vacinação da Gripe anualmente sem custo ao funcionário preço competitivo p/ dependentes, entre outros.

Como se candidatar
Clicando aqui: https://br.wyser-search.com/job/information-technology-digital/frontend-software-engineer-sao-paulo/?ref=725

Labels: 

CLT 
Pleno
Senior
Indaiatuba
Parttime Remoto

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
