### ISSUE TITLE
[Remoto] Front-end Developer na RD Station

### ISSUE THREAD

**Issue by antonelliandre** [frontendbr/vagas#4883]
## Nossa empresa

**Ajudamos pessoas a crescerem seus negócios e países a crescerem suas economias.**

🚀 Somos uma das maiores empresas SaaS do Brasil. Desenvolvemos uma plataforma 100% brasileira de automação de marketing digital e vendas;

🌎 Temos desafios de expansão nacional (onde somos líderes) e de penetração internacional na América Latina e Europa. Atendemos + 25.000 clientes de todos os portes em +20 países;

⭐ Nossos RDoers, como chamamos as +650 pessoas do time, nos elegeram 7 vezes uma das melhores empresas para se trabalhar no país e nos deram 4.5 estrelas no Glassdoor.

## Descrição da vaga

O desafio de Front dentro do nosso time de Marketing é usar linguagens de programação para criação e desenvolvimento de soluções web amigáveis e de alta relevância para clientes, leitores e usuários das interfaces da Resultados Digitais.

**Suas principais entregas:**

- Proporcionar uma experiência positiva para quem acessa nossas landing pages;
- Colaborar com desenvolvedores de back-end e web designers para melhorar a usabilidade dos ativos digitais da RD;
- Garantir padrões gráficos de alta qualidade e consistência da marca;
- Prestar suporte dos sites (documentação, tickets de suporte) para clientes internos e externos garantindo análise e solução definitiva do problema/dúvida.
- Monitorar a operação dos diversos sites (monitoramento de uso, tuning, insights de problemas, etc) e, quando necessário, atuar em incidentes.

## Local

Remoto ou Florianópolis 

## Requisitos

**Obrigatórios:**
- Experiência com uso de linguagens JavaScript, WordPress, HTML e CSS.
- Vivência com criação web;
- Conhecimento em performance de carregamento sobre os ativos front-end e construção de componentes reutilizáveis.

**Diferenciais:**
- Foco na experiência de quem acesso nossos sites;
- Pensamento critico sobre a lógica por traz do nosso site e como isso impacta diretamente a conversão de novos clientes;
- Gostar de atuar em diferentes projetos simultaneamente;

## Benefícios

- Plano Médico: Temos duas opções de plano para sua escolha de acordo com rede de atendimento da  sua cidade. Eles são extensivos a dependentes legais (filhos e cônjuges) sem custo. UNIMED Nacional Enfermaria ou SulAmerica Clássico Enfermaria
- Seguro de Vida Coletivo
- Plano Odontológico
- Tele Medicina Dr. Alper: Atendimento médico, sem custo para RDoers e dependentes, através de 
- aplicativo.
- Vittude: Subsídio de 50% em atendimento psicológico para RDoers e  dependentes.
- Vale Refeição ou Alimentação: R$ 700,00 mensais (Pago no Caju)
- Vale transporte: De acordo com o deslocamento
- Auxílio Home Office: R$ 120,00/mês (para Full Remote e durante a pandemia para quem atuar em 
- Home Office)
- Setup de Home Office: R$ 600,00 na contratação

**Diferenciais:**
- Horário 100% flexível 
- Excelente cultura (duvidando? Olhe nosso Glassdoor)

## Contratação

CLT

## Como se candidatar

Basta acessar nosso [link](https://boards.greenhouse.io/rdstation/jobs/5265498002).

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após aplicação.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by Gabri3el** [comment]
Mandei \o/

**Comment by EzioMora** [comment]
Ainda tem vagas front end disponíveis?

**Comment by ezequielbrilhantedev** [comment]
Boa noite. Não encontrei essa vaga de frontend no site. Ainda está
disponível?

Em sex., 14 de mai. de 2021 às 15:47, antonelliandre <
***@***.***> escreveu:

**Comment by EzioMora** [comment]
![image](https://user-images.githubusercontent.com/73040782/120871746-e7c01180-c572-11eb-95c0-3ff679824f86.png)

Não esta disponivel a vaga para Frontend Junior, se tiver um email onde possa encaminhar meu curriculum agradeço.

**Comment by hlorenalopes** [comment]
Olá! Não encontrei a vaga no site, conforme os colegas já comentaram aqui. Caso ainda esteja disponível, me avisa como posso enviar meu currículo? Obrigada!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
