### ISSUE TITLE
[Remoto] Front-end Developer na Meta

### ISSUE THREAD

**Issue by sara-nmonteiro** [frontendbr/vagas#4884]
Desenvolvedor Front-End \o/

> Vaga 100% Remota 

A Meta é uma empresa focada em soluções tecnológicas ágeis que simplificam e geram valor real no dia a dia das organizações. Trabalhamos para evoluir o seu negócio de forma rápida, consistente e compatível com as mudanças cada vez mais aceleradas do nosso tempo.

Acreditamos que os indivíduos e suas interações fazem o seu e o nosso negócio. Este é o nosso jeito de fazer: com tecnologia e simplicidade.

Nosso propósito é promover o Crescimento Humano com Tecnologia.

Atualmente ganhamos o prêmio GPTW, e estamos no ranking das 20 melhores empresas de TI para se trabalhar.

**Front-End com conhecimento em Javascript**

Nível
- Pleno
- Sênior

Requisitos Obrigatórios:
- Quatro anos ou mais de experiência em desenvolvimento de software (não contabilizar períodos em outras atividades, como suporte ou consultoria).
- Três anos ou mais de experiência em desenvolvimento em JavaScript.
- Conhecer e aplicar conceitos de VanillaJS e EcmaScript (ES6 e ES8).
- Conhecer e aplicar padrões de design no frontend.
- Ter sólidos conhecimentos em HTML e CSS.
- Experiência com pré-processadores CSS (SAS ou SCSS).
- Dois ou mais anos de experiência em desenvolvimento usando Java 8 ou superior.
-Conheça e aplique padrões de design no back-end.
- Conhecimento / experiência com bancos relacionais.

Requisitos Desejáveis: 
- Conhecimento / experiência com testes de unidade no frontend. 
- Conhecimento / experiência com AngularJs

Benefícios
- Notebook;
- VA ou VR;
- Plano de Saúde;
- Plano odontológico;
- Seguro de Vida;
- Participação de Lucros.

Contratação (PJ ou CLT) a combinar.

**Como se candidatar
>> Por favor envie um email para sara.didio@meta.com.br com seu CV anexado com pretensão salarial - enviar no assunto: Vaga Front-End.**

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
