### ISSUE TITLE
[Remoto] Frontend React Developer na GuruHotel (EUA)

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#4886]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url https://coodesh.com com o pop-up personalizado de candidatura. :wave:
<p>We are looking for <strong><em><ins>Frontend ReactJs Developers</ins></em></strong>.</p>
<h6></h6>
<h6><strong>Responsibilities</strong></h6>
<p>As a Frontend Developer, we are looking for proactive people, capable of executing tasks and contributing ideas to improve our platform.</p>
<h6></h6>
<h6><strong>GuruHotel</strong></h6>
<p><em>Nuestro equipo esta compuesto por profesionales en la industria hotelera que han trabajado para agencias de viajes online, cadenas hoteleras en México y LATAM, así como en empresas que lideran el sector de desarrollo tecnológico en el mundo entero.</em></p>
<p><strong><em><ins>GuruHotel es además parte de Y Combinator, la aceleradora de negocios más importante del mundo</ins></em></strong><em>, y está por cerrar su primera ronda de capital, misma que le permitirá seguir expandiéndose a más países y volverse un aliado clave para el crecimiento y la digitalización de los hoteles independientes de Latinoamérica.</em></p>

## GuruHotel: 
 <p>Hotels using GuruHotel can build a real e-commerce website in less than 30 minutes with multiple payment options and start selling their rooms directly.&nbsp;</p>

<p>Also they can connect with distribution apps like Booking.com, Expedia, Airbnb and marketing, ads, analytics, and hospitality apps.</p><a href='https://coodesh.com/empresas/guruhotel'>Veja mais no site</a>

 ## Habilidades: 
 - HTML 5 
- Javascript 
- React.js 
- React Native 
- Typescript 
- GIT 
- CSS 3 
- GraphQL
## Local: 
 100% Remoto
## Requisitos: 
 - Fluent Spanish or English 
- Development with React / NextJS 
- Knowledge in GraphQL (Queries, Mutations ...) 
- Knowledge in Redux 
- Good sense of aesthetics 
- Knowledge of HTML, CSS, Sass, and Less

## Benefícios: 
 - 100% remote company, before the pandemic and after it 
- Flexible schedule 
- Perks 
- Stock options plans
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend React Developer na GuruHotel](https://coodesh.com/vagas/frontend-react-developer-180958?origin=github&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção <b>Pedir Feedback</b> entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa <b>Recruiter</b> responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
