### ISSUE TITLE
[Remoto/São Paulo/Curitiba] Front-end Senior Developer na Porto Seguro

### ISSUE THREAD

**Issue by rlechetaup** [frontendbr/vagas#4888]
## Nossa empresa

A Livetouch é lider no setor de aplicativos e atua desde 2007. Estamos em pleno crescimento e nosso setor de Transformação Digital está buscando um profissional front-end Senior com foco em Angular, mas é desejável o conhecimento de outras tecnologias como React, Vue.js, e Next.js também.

## Descrição da vaga

Projeto de grande porte para o mercado financeiro, sobre investimentos em renda fixa, privada, etc.

## Local

A Livetouch possui escritórios em SP e Curitiba, o cliente é de SP: Remoto ou Escritório, [SP-PR], [São Paulo-Curitiba].

## Requisitos

**Obrigatórios:**
- 5 anos de experiência com front-end
- 3 anos de experiência com Angular
- experiência em trabalho em equipe e com metodologias ágeis

**Desejáveis:**
- conhecimentos em React, Vue.js, Next.js
- profissional que busque sempre estar estudando e evoluindo
- Git/Git Flow

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ 22/dia

**Diferenciais:**
- Equipe fantástica
- Pretendemos seguir o modelo híbrido voltando da pandemia, mas gostamos de remoto.
- 2 workshops semanais com temas diversos com nossos engenheiros e a equipe de tecnologia
- Possibilidade de crescimento profissional e trabalhar em muitos projetos.
- ...

## Contratação

CLT

## Como se candidatar

Por favor envie um email para rlecheta@livetouch.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Senior Developer 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
