### ISSUE TITLE
[Remoto] Software engineer na Divisio

### ISSUE THREAD

**Issue by rodrigowpl** [frontendbr/vagas#4889]
## Nossa empresa

A Divisio é empresa especializada em desenvolver software customizado, mobile apps, web apps utilizando as tecnologias React.js, React Native, Node.js, GraphQL e API REST. Trabalhamos com projetos de todos os tamanhos, desde pequenos até arquiteturas de aplicações de larga escala. Somos um time de especialistas, apaixonados por qualidade de código e trabalhamos em conjunto para lidar com os problemas de software mais difíceis e transformando ideias em realidade.

Trabalhamos duro para promover uma cultura de apoio com uma hierarquia horizontal, onde todos podem aprender uns com os outros. Todos têm a oportunidade de crescimento e participação em decisões diárias. Você poderá trabalhar remotamente de qualquer lugar, desenvolvendo novas aplicações, features e mantendo sistemas existentes para empresas que variam de tamanho, desde startups até grandes empresas. Quando você não estiver trabalhando em um projeto de um cliente, terá a oportunidade de contribuir com o desenvolvimento de nossos processos e produtos internos, sempre tendo voz para sugerir melhorias e oportunidade de contribuir para projetos open-source.

Mais informações por favor acesse: https://p.divisio.pro/company/careers

## Descrição da vaga

Procuramos um desenvolvedor(ra) com experiência profissional para atuar em projetos de pequeno a grande porte. Temos um time super unido onde todos sempre estão acessíveis para compartilhar conhecimento. Procuramos por pessoas que prezam pela cultura, seja proativo e tenha uma comunicação assertiva.

## Local

Remoto ou Escritório, Minas Gerais - Belo Horizonte

## Requisitos

**Obrigatórios:**
- Ter 1 ano ou mais de experiência com desenvolvimento web frontend.
- Proficiência em React, Typescript, CSS3 a HTML5.
- Ser genuinamente interessado em tecnologia e adorar experimentar coisas novas.
- Ter 1 ano ou mais de experiência com desenvolvimento backend usando Node.js.
- Ter 1 ano ou mais de experiência com GraphQL.
- Inglês avançado: Leitura, escrita e conversação.
- Ponto bonus: Amplify & AWS: Lambda functions, Cognito, DynamoDB, CloudFormation.

## Benefícios

- 20 dias de descanso remunerado por ano
- Auxilio com cursos
- Horário flexível

## Contratação

PJ a combinar

## Como se candidatar

https://p.divisio.pro/jobs/software-engineer

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Senior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
