### ISSUE TITLE
[São Paulo] Desenvolvimento Front-end na Isquik

### ISSUE THREAD

**Issue by Willycasarini** [frontendbr/vagas#489]
[VAGA] Desenvolvimento Front-end (PJ a combinar)

## Descrição da vaga
Desenvolvimento de novos aplicativos Web
Análise e levantamento de requisitos
Manutenção em sistemas em operação
Suporte a usuários

## Local
Escritório, São Paulo - Barra Funda (próximo a estação Barra Funda de metrô)

## Benefícios
1,5 hora de almoço
Férias remuneradas

## Requisitos
JavaScript
AngularJS
HTML
CSS

## Contratação
PJ a combinar

## Nossa empresa
Isquik é uma startup de desenvolvimento de aplicações empresariais para automatizar demandas internas, em plataforma própria. Fundada em 2015, utiliza tecnologias de ponta, amplamente reconhecidas no mercado.

## Como se candidatar
Por favor envie um email para rh@isquik.com com seu CV anexo - enviar no assunto: Vaga Desenvolvimento Front-end.

**Comment by devEdipo** [comment]
@Willycasarini

Júnior? Posso realizar um teste?

**Comment by Willycasarini** [comment]
Pode sim @devEdipo, qual seu e-mail?

**Comment by devEdipo** [comment]
@Willycasarini,

Meu e-mail é edipoesn@gmail.com

Obrigado, por responder.

**Comment by RicardoWEBSiTE** [comment]
tem possibilidade de ser remoto?

2017-08-17 10:56 GMT-03:00 Édipo Nascimento <notifications@github.com>:

**Comment by Willycasarini** [comment]
@devEdipo , te enviei a prova técnica por e-mail. 
Aguardo suas respostas. 
Obrigado.

**Comment by Willycasarini** [comment]
@RicardoWEBSiTE, infelizmente não. Precisamos do profissional junto a equipe de desenvolvimento.

**Comment by ldrbraga** [comment]
Bom dia! Se possível, também gostaria de realizar a prova técnica. ldrbraga@gmail.com

**Comment by Willycasarini** [comment]
Olá @ldrbraga , enviei a prova para seu e-mail. 
Obrigado pelo interesse.

**Comment by ecouto** [comment]
@Willycasarini  não querendo ser chato mas já sendo, envie pra mim tb =D  ecouto123@gmail.com

**Comment by Willycasarini** [comment]
Olá @ecouto , segue no seu e-mail.
Obrigado.

**Comment by vmarcosp** [comment]
@Willycasarini por gentileza, gostaria de realizar a prova também. Envie para o e-mail contato@vmarcosp.com.br

**Comment by Willycasarini** [comment]
@vmarcosp , segue anexo no seu e-mail.
Obrigado.

**Comment by zecafeitosa** [comment]
Pode me enviar também?  feitosazeca@gmail.com

Obrigado =]

**Comment by rafaelrf** [comment]
@Willycasarini se possível, também gostaria de realizar o teste. =D 
rafaelrfontenele@gmail.com

Obrigado.

**Comment by manzettidenis** [comment]
@Willycasarini gostaria de realizar o teste. 
manzetti.denis@gmail.com

Obrigado!

**Comment by ygorlazaro** [comment]
@Willycasarini Eu tambem gostaria de fazer o teste. Meu e-mail é ygor@gatoninja.com.br.

Obrigado!

**Comment by genorchiomento** [comment]
Também gostaria de fazer o teste @Willycasarini : genor.chiomento@gmail.com

**Comment by adrianokg** [comment]
Me envie o teste também por gentileza. Obrigado.
adrianokgroff@gmail.com

**Comment by DawTaylor** [comment]
Me mande também, por favor. adalbertotaylor84@gmail.com

**Comment by AlcidesA** [comment]
Olá, gostaria de fazer o teste!  aaugusto.kd@gmail.com

**Comment by hugodemoraes** [comment]
@Willycasarini gostaria de realizar o teste também. Se puder me enviar por email hugoc.bmoraes@gmail.com

**Comment by wfs19** [comment]
Boa tarde, estou em busca de uma oportunidade. Sou iniciante na área, estudo a alguns meses e caso ainda estejam precisando gostaria de tentar fazer o teste pelo menos. Obrigado wfs19@live.com

**Comment by FernandoBaiao26** [comment]
Boa tarde , eu gostaria de fazer um teste obrigado meu email: fernando.provisorio@outlook.com

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by FernandoBaiao26** [comment]
Não entendi ,,

Sent from my iPhone

On 23 Jan 2018, at 14:06, Felipe Fialho <notifications@github.com<mailto:notifications@github.com>> wrote:


Aberto ainda?

**Comment by LFeh** [comment]
Essa vaga está aberta?
