### ISSUE TITLE
[Remoto] React Native Developer na Fluke

### ISSUE THREAD

**Issue by izabela-am** [frontendbr/vagas#4890]
## Nossa empresa

A Fluke oferece a conectividade que você precisa com a experiência que vc merece.
Somos muito mais que uma operadora de celular, estamos aqui para mostrar que existe uma nova - e melhor! - maneira de se fazer telefonia no Brasil. Tudo o que encontra nas operadoras tradicionais - lojas, descaso e musiquinhas de espera - você não encontra aqui.
Somos uma empresa de tecnologia, ainda no comecinho da trajetória, e justamente por isso procuramos as mais dispostas para construir tudo isso com gente! 💚

## Descrição da vaga

**Na Fluke você:**

- Terá a oportunidade de aprender muito com um time de alto nível
- Terá autonomia para tomar decisões sem precisar investir tempo e energia em reuniões desnecessárias
- Trabalhará em um ambiente colaborativo com time super engajado que trabalha e se diverte junto :)

**No Time de Tecnologia você vai:**

- Criar/dar manutenção em todas as telas e componentes do nosso aplicativo
- Interagir com Banco de Dados não relacional
- Realizar integrações para consumir APIs REST
- Implementar melhorias de UX/UI no nosso aplicativo
- Aplicar melhores práticas de codificação e documentação de código
- Trabalhar com metodologias ágeis

## Local

Remoto

## Requisitos

Não exigimos cursos específicos. Acreditamos muito em pessoas dispostas a aprender o que for preciso e buscamos pessoas curiosas que querem causar impacto através do seu trabalho.

Os requisitos são:
- Javascript
- Typescript
- Versionamento Git
- Experiência de desenvolvimento com React Native
- Trabalhar com animações no React Native
- Conhecer e aplicar boas práticas de desenvolvimento
- Familiaridade com bases de dados não relacionais (Ex.: Cloud Firestore, MongoDB)
- Ser você mesmo

**Diferenciais:**
- Experiência com testes automatizados

## Salário e Benefícios

- Regime de contratação PJ (entre R$3-8mil) ou estágio (R$1.500)
- Caju Benefícios: R$600 em saldo livre mensal para diversas categorias
- Aulas de inglês
- Ambiente de crescimento acelerado e com time que muito engajado que trabalha e se diverte junto

## Contratação

- PJ

## Como se candidatar

Candidaturas através [DESTE ](https://fluke.recruitee.com/o/desenvolvedora-frontend-react-native) link

## Contato

E-mail para contato: izabela@flukeoperadora.com.br

#### Alocação
- Remoto

#### Regime
- Estágio
- PJ

#### Nível
- Estagiário
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
