### ISSUE TITLE
[100% remoto ou Campinas] Pessoa Desenvolvedora Front-end Senior (CLT) na I.Systems

### ISSUE THREAD

**Issue by Kahfiod** [frontendbr/vagas#4893]
## Nossa empresa

A I.Systems fornece soluções de controle avançado e otimização de processos para diversos segmentos da indústria com produtos de tecnologia exclusiva e patenteada, baseados em inteligência artificial. Com mais de 100 projetos realizados em mais de 40 grupos distintos, estamos caminhando para nos tornar uma empresa global e cada vez mais próxima do objetivo de aumentar a eficiência do mundo.

## Descrição da vaga

A pessoa desenvolvedora Front-End Senior irá atuar no desenvolvimento de aplicações e funcionalidades que interagem diretamente com os usuários dos produtos em plataformas web. Além disso, contribuir na arquitetura de aplicações robustas e responsivas, propondo soluções e uso de tecnologias que atendam ao resultado esperado. Irá fazer parte do seu dia a dia conduzir tecnicamente subprojetos/prototipações de forma independente, mantendo a comunicação com time de back-end e Produto, entendendo e solucionando problemas.

## Local

Remoto (mesmo depois da pandemia) ou no escritório de Campinas 

## Requisitos

**Obrigatórios:**

- Experiência em HTML, CSS e JavaScript;
- Domínio em pelo menos um framework de interfaces (React, Angular, Vue ou similar);
- Experiência em gerenciamento de estado;
- Experiência em implementação de Design Systems;
- Domínio em protocolos de autenticação (HTTP, token, OAuth, certificados);
- Experiência com práticas de build, deploy, bundlers e monitoramentos;
- Domínio e boas práticas em pelo menos uma ferramenta de testes (Jest, Karma, Cypress, Jasmine, Protractor ou similar);
- Domínio em TypeScript e paradigmas de desenvolvimento (TDD, BDD ou similar);
- Domínio com pré processadores (SASS, LESS ou similares), boas práticas de CSS (BEM, ITCSS, SMACSS ou similar);
- Experiência em criação de páginas responsivas;
- Domínio de padrões de projeto;
- Domínio do funcionamento dos browsers (armazenamento, localização, service workers);
- Contribuir na arquitetura de aplicações robustas e responsivas, propondo soluções e uso de tecnologias que atendam ao resultado esperado.

**Diferenciais:**

- Conhecimento sobre SVG

## Benefícios

- Vaga presencial ou 100% home office;
- PLR (com mais de 3 meses de empresa);
- Seguro de Vida (Porto Seguro);
- Assistência Médica (Unimed - sem desconto para o funcionário e dependentes);
- Assistência Odontológica (Uniodonto);
- Vale Alimentação ou Refeição;
- Licença Maternidade e Paternidade estendida;
- Auxílio Creche;
- Gympass;
- Ginástica Laboral;
- Horas de estudos (4horas/semana);
- Horários flexíveis;
- Auxílio para estudos de idiomas;
- Monetus (consultoria financeira);
- Creditas (crédito consignado);
- Cursos Alura.

## Contratação

CLT

## Como se candidatar

Por favor envie um email para recrutamento@i.systems.com.br com seu CV anexado - enviar no assunto: Vaga - Front-end Senior

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: karina.fiod@i.systems.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
