### ISSUE TITLE
[Remoto] Senior Software Engineer na Divisio

### ISSUE THREAD

**Issue by rodrigowpl** [frontendbr/vagas#4896]
## Nossa empresa

A Divisio é empresa especializada em desenvolver software customizado, mobile apps, web apps utilizando as tecnologias React.js, React Native, Node.js, GraphQL e API REST. Trabalhamos com projetos de todos os tamanhos, desde pequenos até arquiteturas de aplicações de larga escala. Somos um time de especialistas, apaixonados por qualidade de código e trabalhamos em conjunto para lidar com os problemas de software mais difíceis e transformando ideias em realidade.

Trabalhamos duro para promover uma cultura de apoio com uma hierarquia horizontal, onde todos podem aprender uns com os outros. Todos têm a oportunidade de crescimento e participação em decisões diárias. Você poderá trabalhar remotamente de qualquer lugar, desenvolvendo novas aplicações, features e mantendo sistemas existentes para empresas que variam de tamanho, desde startups até grandes empresas. Quando você não estiver trabalhando em um projeto de um cliente, terá a oportunidade de contribuir com o desenvolvimento de nossos processos e produtos internos, sempre tendo voz para sugerir melhorias e oportunidade de contribuir para projetos open-source.

Mais informações por favor acesse: https://p.divisio.pro/company/careers

## Local

Remoto ou Escritório, Minas Gerais - Belo Horizonte

## Descrição da vaga

Procuramos um desenvolvedor(ra) com experiência profissional para atuar em projetos de pequeno a grande porte. Temos um time super unido onde todos sempre estão acessíveis para compartilhar conhecimento. Procuramos por pessoas que prezam pela cultura, seja proativo e tenha uma comunicação assertiva.

## Responsabilidades
- Escrever códigos Javascript/Typescript(Node & React) elegantes, eficientes e testáveis que são fáceis de manter e depurar.
- Como um verdadeiro membro do time, continuamente melhorar os processos do time, debater ideias e comunicar status e progresso.
- Orientar outras pessoas, fornecer feedback e crescer como parte da equipe.
- Cobrir o código de testes sempre que possível e realizar testes manuais das features e correções para garantir a qualidade do que será entregue.
- Revisar o código das pull requests dos colegas de equipe, debater melhorias, e prover feedbacks.

## Requisitos

**Obrigatórios:**
- Ter 3 anos ou mais de experiência com desenvolvimento frontend web.
- Domínio de programação orientada a objetos, código limpo e boas práticas de testes.
- Proficiência em React, JavaScript/Typescript, CSS3 a HTML5.
- Experiência com design responsivo.
- Ser genuinamente interessado em tecnologia e adorar experimentar coisas novas.
- Considerar diversas soluções ao enfrentar problemas complexos, avaliá-las e decidir qual o melhor curso de ação.
- Ter 2 anos ou mais de experiência com desenvolvimento backend usando Javascript/Typescript com Node.js.
- Ter 1 ano ou mais de experiência com GraphQL.
- Inglês avançado: Leitura, escrita e conversação.
- Pontos bonus por familiaridade com CI/CD backend e/ou frontend e AWS.

## Benefícios

- 20 dias de descanso remunerado por ano
- Auxilio com cursos
- Horário flexível

## Contratação

PJ a combinar

## Como se candidatar

Enviar o formulário no final da pagina:
https://p.divisio.pro/jobs/senior-software-engineer

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Senior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
