### ISSUE TITLE
[REMOTO] - FullStack React JS + Node.JS Sênior na Beyond

### ISSUE THREAD

**Issue by mariacristinadeoliveira** [frontendbr/vagas#4897]
## Descrição da vaga

Já pensou em fazer parte de uma empresa que vai ALÉM de uma consultoria tradicional de outsourcing?
Nós da BEYOND estamos presentes nas principais organizações do mercado de investimentos e fintechs.

## Local

- Remoto

## Benefícios 100% subsidiados pela Beyond

- Benefício de R$ 800,00 (podendo ser distribuído em VR, VA).
- Plano de saúde: SulAmérica Saúde
- Plano odontológico: SulAmérica Odonto
- Seguro de Vida.
- Horas extras pagas no mês.

## Requisitos da vaga

- React JS;
- HTML/CSS
- Node.JS (>8);
- Javascript;
- TypeScript;
- Bancos SQL e NoSQL;
- Conceitos e desenvolvimento de API Restful;
- Microsserviços, Arquitetura Distribuída.

**Desejáveis:**
- Cloud (AWS)
- Filas (RabbitMQ)
- Docker, Kubernetes
- Esteiras CI/CD
- Testes unitários

## Contratação

- CLT

## Como se candidatar

Me chame no Whatsapp: (11) 93087-8152 ou pelo link: https://wa.me/message/QD6XFYF6MA32E1 🤞

### NÍVEL

- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
