### ISSUE TITLE
[Sao Paulo] Sr Mobile Developer - ObjectiveC/Swift

### ISSUE THREAD

**Issue by rturk** [frontendbr/vagas#49]
## Descrição da vaga

We are looking for Software Development Engineers that thrive in fast-paced environments and are passionate about working with pre-market technologies. Successful candidates will be much more than just developers, they will bring with them deep technical fundamentals, experience with complex mobile, distributed systems, and a well-rounded software engineering background that spans disciplines.

We are looking for a Sr. Developer for our upcoming Mobile App. This is part of our international expansion plan
## Location

Escritório, São Paulo - Zona Sul
http://plug.co/bkln
## Perks
- Cool working place
- Open schedule. Just deliver your code and you're done
- Based in São Paulo - Zona Sul
## Mandatory Qualifications
- BA/BS in Computer Science or related discipline, or equivalent work experience.
- Strong skill in C/ObjectiveC and/or Swift programming.
- 5+ years of software development experience
- Fluent in English 
## Expected qualifications
- Comfortable in fast-paced, start-up like development environments.
- Experience in software development on devices/products in real-time operation system.
## Contratação

Full time employee
## About us

Entria (https://www.entria.com.br) is a leading Mobile Provider. We make really cool apps
We manage complex projects, and yes we deliver.
## How to apply for this job

Just drop us a note at rh@entria.com.br please attach CV our link to github projects, previous projetcs

**Comment by rwaltenberg** [comment]
Isso não é meio offtopic?
Em 1 de jun de 2016 12:04 PM, "Rafael Turk" <notifications@github.com>
escreveu:

**Comment by Mendrone** [comment]
@rwaltenberg Apesar de não ser uma vaga Frontend, muitos devs que passam por aqui são full stack ou tem/querem ter experiência com aplicações mobile nativas, então digamos que é semi-offtopic hahaha

**Comment by rturk** [comment]
@rwaltenberg @rwaltenberg everything is connected. Nowadays you can't decouple frontend from Mobile. That's why we're posting job offers here.

**Comment by rwaltenberg** [comment]
¯\_(ツ)_/¯

**Comment by LFeh** [comment]
Concordo @Mendrone

**Comment by Xhamps** [comment]
Também concordo com o @Mendrone.
Sou front-end e hoje trabalho somente com mobile (ou era front-end, rss).

**Comment by Mendrone** [comment]
@rturk a vaga foi preenchida?

**Comment by eduardojmatos** [comment]
@rturk aguardando aqui o status da vaga pra mantermos na lista ou não! :)
