### ISSUE TITLE
[Remoto] Fullstack Developer na GuruHotel

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#4902]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/fullstack-developer-152301?origin=github&modal=open) com o pop-up personalizado de candidatura. 👋
<p>We are looking for <strong><em><ins>Fullstack Developers</ins></em></strong>.</p>
<p></p>
<h6>Responsibilities</h6>
<p>As a Fullstack Developer, we are looking for proactive people, capable of executing tasks and contributing ideas to improve our platform.</p>
<p></p>
<h6>GuruHotel</h6>
<p>Nuestro equipo esta compuesto por profesionales en la industria hotelera que han trabajado para agencias de viajes online, cadenas hoteleras en México y LATAM, así como en empresas que lideran el sector de desarrollo tecnológico en el mundo entero.</p>
<p>GuruHotel es además parte de Y Combinator, la aceleradora de negocios más importante del mundo, y está por cerrar su primera ronda de capital, misma que le permitirá seguir expandiéndose a más países y volverse un aliado clave para el crecimiento y la digitalización de los hoteles independientes de Latinoamérica.</p>

## GuruHotel: 
 <p>Hotels using GuruHotel can build a real e-commerce website in less than 30 minutes with multiple payment options and start selling their rooms directly.&nbsp;</p>

<p>Also they can connect with distribution apps like Booking.com, Expedia, Airbnb and marketing, ads, analytics, and hospitality apps.</p><a href='https://coodesh.com/empresas/guruhotel'>Veja mais no site</a>

 ## Habilidades: 
 - HTML 5 
- Javascript 
- PostgreSQL 
- React.js 
- Typescript 
- Docker 
- GIT 
- CSS 3 
- Node.js 
- GraphQL
## Local: 
 100% Remoto
## Requisitos: 
 - Fluent Spanish or English 
- Backend development with Node (Typescript or Javascript) 
- Frontend Development with React / NextJS 
- Knowledge in GraphQL (Queries, Mutations ...) 
- Knowledge in Rest API 
- Good experience with backend projects and microservices 
- Good sense of aesthetics 
- Knowledge of HTML, CSS, Sass, and Less
**Diferenciais:** 
 - Knowledge of UI / UX 
- Experience with AWS, Docker and Kubernetes 
- Domain in another programming language like Ruby or Python
## Benefícios: 
 - USD Dollar (US$) or Real (R$) salary 
- 100% remote company, before the pandemic and after it 
- Flexible schedule 
- Perks 
- Stock options plans
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack Developer na GuruHotel](https://coodesh.com/vagas/fullstack-developer-152301?origin=github&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção <b>Pedir Feedback</b> entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa <b>Recruiter</b> responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
