### ISSUE TITLE
[Remoto] Front-end React Developer (Pleno) na Rumo Soluções

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#4903]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/analista-desenvolvedor-react-pleno-143437?origin=github&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Trabalhar em equipe, colaboração, resiliência, comprometimento, integridade e pró-atividade são requisitos obrigatórios para qualquer vaga correto? Então deixe-nos saber sobre estas qualidades tá bom?</p>
<p>Se você interessa profundamente por tecnologia e desenvolvimento, então dá uma olhadinha nessa vaga:</p>
<p>Vaga para Júnior/Pleno</p>
<p>Requisito principal: Programar por paixão!&nbsp;</p>
<p>Se o seu foco é desenvolvimento <strong>front-end react</strong> <em>#VemPraRumo </em></p>
<p><em>Vaga para trabalho remoto durante o período da pandemia. </em></p>

## Rumo Soluções: 
 <p>A Rumo se especializou como fábrica de software, atuando no desenvolvimento de produto e soluções na área de Tecnologia da Informação para gerenciamento e apoio aos negócios de seus clientes. Rumo também fornece serviços no modelo de Outsourcing, através de uma equipe especializada.</p>

<p style="text-align:justify;"><span style="font-size: 10pt;font-family: Verdana, sans-serif;">Hoje, estamos em busca de novos talentos que apostam na inovação, sejam comprometidos, engajados com a sua carreira e que valorizem as relações verdadeiras. Se você se identificou, venha fazer parte do nosso time e conhecer os motivos que pelos quais somos uma das empresas de TI com a melhor nota de avaliação orgânica no </span><a href="https://www.glassdoor.com.br/Avalia%C3%A7%C3%B5es/Rumo-Solu%C3%A7%C3%B5es-Avalia%C3%A7%C3%B5es-E2487476.htm" target="_self"><span style="color: rgb(12,11,54);background-color: transparent;font-size: 10pt;font-family: Verdana, sans-serif;">Glassdoor</span></a><span style="font-size: 10pt;font-family: Verdana, sans-serif;">.</span>&nbsp;</p><a href='https://coodesh.com/empresas/rumo-solucoes'>Veja mais no site</a>

 ## Habilidades: 
 - CSS 
- HTML 5 
- Javascript 
- React.js 
- Typescript
## Local: 
 100% Remoto
## Requisitos: 
 - React.js;  
- TypeScript; 
- CSS / HTML; 
- Banco de Dados (Preferência: SQL-Server); 
- Sólidos conhecimentos de JavaScript; 
- Análise, design e codificação; 
- WebAPI – Rest/Restfull; 
- Princípios SOLID.
**Diferenciais:** 
 - React Native; 
- Firebase; 
-  Conhecimentos práticos em TDD (Test Driven Design) / Teste Unitário; 
- Práticas DevOps (CI/CD/Code Review ...); 
- Conhecimento no Azure DevOps; 
- Conhecimento de Docker /Kubernetes; 
- Conhecimento em .Net Core.
## Benefícios: 
 - Salário compatível com a experiência (Envie sua pretensão); 
- PL (Participação nos Lucros);  
- Todos os benefícios sem desconto em salário. 
- Vale Refeição; 
- Vale Alimentação. 
- Vale Transporte ou vale combustível. 
- Plano Odontológico SulAmérica; 
- Plano de Saúde SulAmérica; 
- Seguro de Vida. 
- Carga Horário de 40h semanais (Segunda a sexta); 
- Horário Flexível; 
- Convênio com SESC;  
- Benefícios, inclusive nas férias. 
- Parceria no aprendizado de Idiomas; 
- Workshops Técnicos (temas variados); 
- Auxílio Educação (graduação e pós graduação).
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Front-end React Developer (Pleno) na Rumo Soluções](https://coodesh.com/vagas/analista-desenvolvedor-react-pleno-143437?origin=github&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção <b>Pedir Feedback</b> entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa <b>Recruiter</b> responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Nível
Pleno
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
