### ISSUE TITLE
[Remoto] Front-end Angular Developer Senior na Worthix Corp

### ISSUE THREAD

**Issue by tbaragao** [frontendbr/vagas#4905]
> Vaga Remota durante a pandemia

## Nossa empresa

Na Worthix, estamos redefinindo o mercado da Análise Experiência do Cliente. 
Construímos a primeira ferramenta de medição de decisão do cliente do mundo com tecnologia de IA e fornecida em um aplicativo de software simplificado. 
Nascemos no Vale do Silício, e somos uma startup de tecnologia sediada em Atlanta que está crescendo rapidamente no mercado norte-americano, e já atuamos na america central e do sul, europa e asia e temos uma equipe incrível !!!

## Descrição da vaga
Projeto de grande porte multi-nacional que atende clientes de grande porte como DIsney, Blizzard, Mercedez e outros

## Local
- Remoto

## Requisitos

**Obrigatórios:**
- HTML5e CSS3;
- Monorepositório utilizando NX;
- Conhecimento em processadores de estilo (LESS, SASS, SCSS);
- Experiência em Javascript moderno (ES6+) de 3 anos ou mais.
- Typescript;
- Experiência em Node.js;
- Experiência em Angular2+;
- Experiencia NGRX ou alguma biblioteca de gerenciamento de estado;
- Experiência com controle de versão Git;
- Experiênciaem integrações de API Rest via Json;
- Experiênciaem RxJS;
- Experiênciacom testes.

**Desejáveis:**
- Criação de gráficos utilizando D3.js;
- Jest;
- Cypress;

**Diferenciais:**
- Inglês avançado ou Fluente
- Skills de UX /UI
- Portfolio

## Benefícios

- Salário acima da média nacional e beneficios compativeis com o mercado

**Diferenciais:**
- Setup de alto nível completo
- Cultura multiétnica

## Contratação

PJ

## Como se candidatar

Basta enviar o seu curriculo e o link para o seu github para thiago.aragao@worthix.com - enviar no assunto: Vaga Angular Sr

## Tempo médio de feedbacks

Costumamos enviar feedbacks imediato após cada processo.
E-mail para contato em caso de não haver resposta: thiago.aragao@worthix.com

## Labels
Sênior, Pleno, Remoto, PJ, Estados Unidos

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by tbaragao** [comment]
@felipefialho poderia remover algumas tags que goram adicionadas a mais?

Seriam: 
Remoto durante pandemia (a vaga é full remoto, independente da pandemia)
São Paulo (Poderia substituir por Estados Unidos ou USA, pois a empresa é americana)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
