### ISSUE TITLE
[SALVADOR-BA] React Native Developer na Bloxs Investimentos

### ISSUE THREAD

**Issue by lucasayres** [frontendbr/vagas#4906]
## Nossa empresa

A Bloxs Investimentos é uma startup da área financeira (Fintech) que tem como propósito conectar investidores que buscam rentabilidade e diversificação com empreendedores que buscam acesso ao Mercado de Capitais. Tudo isso 100% online e com a segurança de um mercado regulado e autorizado pela CVM. Saiba mais em: https://bloxs.com.br

## Descrição da vaga

A Bloxs busca um(a) desenvolvedor(a) React Native de nível Pleno ou Sênior para atuar no desenvolvimento do nosso aplicativo de investimentos, criando funcionalidades que vão gerar muito valor para nossos usuários! Além disso, você será responsável por todo o processo de desenvolvimento, desde a discussão de tasks até os testes e a entrega de novas soluções, além de liderar equipes.

## Local

Salvador - BA
Remoto

## No dia a dia seus desafios serão

- Fazer mentoring/coaching de pares e team members menos experientes;
- Trabalhar em parceria com outras áreas da empresa, como UX, Produto, Comercial, para garantir que o produto seja o melhor possível para nossos investidores;
- Aplicar melhores práticas de documentação de código desenvolvido;
- Buscar novas ferramentas e técnicas para a melhoria contínua do nosso aplicativo;
- Desenvolver novas features;
- Integrações com APIs de terceiros;
- Colaborar com a melhoria contínua dos nossos processos de desenvolvimento, bem como na melhoraria da nossa arquitetura nas aplicações web;
- Colaborar com a execução e sugerir melhorias nos nossos processos ágeis;
- Liderar equipes;

## Esperamos que você

- Tenha pró atividade em trazer ideias novas e ao mesmo tempo ter um senso de dono do negócio
- Queira aprender sempre e saia da zona de conforto;
- Seja capaz de inspirar e motivar as pessoas ao seu redor para atingir um objetivo comum usando liderança por influência;
- Possua sólidos conhecimentos em programação mobile e react-native;
- Possua sólidos conhecimentos de integração de APIs REST;
- Tenha conhecimentos em Redux;
- Tenha conhecimento em TypeScript;
- Conhecimento total dos ciclos de um aplicativo (concepção, desenvolvimento e publicação nas stores);
- Tenha noções de UX;
- Tenha conhecimento com versionamento de código (GIT);
- Tenha experiência em times com processos ágeis (SCRUM, OKRs, Daily..);
- Possua familiaridade com testes automatizados e outros tipos de automações;
- Desenvolva códigos elegantes, estáveis, confiáveis e fáceis de manter;

## Vantagens e benefícios

- Contratação CLT
- Horário flexível e banco de horas;
- Vale-transporte alinhado com a necessidade de cada pessoa;
- Auxílio alimentação;
- Ambiente de startup em crescimento acelerado;
- Acreditamos muito na cultura do Feedback e trabalhamos isso no nosso dia a dia;

## Como se candidatar

Preencha o seguinte formulário da vaga: https://docs.google.com/forms/d/e/1FAIpQLScuYIPy9RnObBx9iBQ-WHV5g1zMh22lMiZg9OASYcGJnWOUUg/viewform

## Labels

- 🏢 Flexível
- 👨 Pleno
- 👴 Sênior
- ⚖️ CLT
- 💰 3k-6k

**Comment by pedroch4610** [comment]
6k para sênior?!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
