### ISSUE TITLE
[Remoto] Developer ReactJS e/ou ReactNative na RockApps

### ISSUE THREAD

**Issue by erickne** [frontendbr/vagas#4912]
# React JS e React Native

## Descrição da vaga

Buscamos novos desenvolvedores de nível **JÚNIOR**, **PLENO** e **SÊNIOR** para compor o time tecnológico. As vagas serão para React Native e ReactJS. A experiência em ambas tecnologias será um diferencial.

A principais atividades serão:

* Desenvolvimento de novas interfaces web em ReactJS;
* Desenvolvimento de aplicativos híbridos em React Native;
* Desenvolvimento e execução de testes.

## Local

* 100% Remoto
* Horário comercial

## Requisitos

**Obrigatórios:**

* Domínio em ReactJS e/ou React Native
* Domínio em React State Management (Redux)
* Integração de RESTFull APIs
* Boas noções de layout
* Ótima comunicação verbal e escrita
* Lê e escreve em inglês
* Bons conhecimentos em criação e execução de teste em **ReactJS** e/ou **React Native**

**Desejáveis:**

* Conhecimento em CI/CD (Jenkins, Fastlane)
* Conhecimento em gestão de projetos ágeis
* Conhecimento na biblioteca Expo
* Testes Unitários
* Geração de builds com Xcode e Android Studio

**Diferenciais:**

* Experiência em linguagens nativas
* Experiência em utilização do Figma
* Gerenciamento de certificados Apple

## Contratação

* PJ a combinar
* **Remuneração variável a cada 6 meses conforme performance**

## Nossa empresa

Desenvolvimento ágil e profissional de produtos e ideias, utilizando modernas tecnologias através de um modelo de custos acessível e flexível. A atuação de nossa empresa busca personalizar projetos e aplicações integrar soluções aos sistemas pré-existentes de nossos clientes. Sempre atualizados com as novas tecnologias de mercado, trazemos conosco aplicações inovadoras que certamente atenderão sua necessidade. Hoje em dia, a RK se consolidou no mercado, possuindo mais de 50 clientes e mais de 60 softwares e aplicativos criados. Realizações que nos mantém em andamento.

Conheça mais sobre nossa empresa em <https://rockapps.com.br>.

## Como se candidatar

1. Acesse o link <https://github.com/rock-apps/vaga-react/> e faça um fork do projeto.
2. Em seguida, é **fundamental** o preenchimento do formulário <https://link.rockapps.com.br/vaga-dev-react>. 
3. Se necessário, entre em contato com a gente em [carreiras@rockapps.com.br](mailto:carreiras@rockapps.com.br).

## Labels

- 🏢 Remoto

- 👶 Estágio

- 👨 Pleno

- 👴 Sênior

- ⚖️ PJ

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
