### ISSUE TITLE
[Remoto] Front-end Developer na STONE

### ISSUE THREAD

**Issue by anasofia1214** [frontendbr/vagas#4913]
## STONE 

Somos muito mais do que uma empresa de maquininhas!
Atuamos na indústria de pagamentos desde 2012, lutando para servir o nosso cliente e provar que há uma maneira mais justa, pessoal e inteligente de fazer negócio.

Estamos crescendo em um ritmo forte e assumimos desafios cada vez maiores e mais difíceis. Queremos nos tornar os melhores em serviços aos clientes e construir um negócio grande em: receita, colaboradores e pessoas impactadas.

Para isso, contamos com pessoas boas ao nosso lado, em um ambiente dinâmico e informal em que todos se falam e se ajudam. Unimos experiência e agilidade para criar um jeito diferente de fazer negócio.

## Desafio:
Procuramos um desenvolvedor apaixonado por desafios, tecnologia e conhecimento.
Você será responsável por desenvolver e criar sistemas internos, utilizados por toda a operação.

## Local

Possibilidade de trabalho presencial nos escritórios do Rio de Janeiro ou *100% remoto*. Sim, você pode trabalhar de qualquer lugar do Brasil :) 

## Requisitos

**Obrigatórios:**
- Experiência com as linguagens: Node, Python, Javascript / ES6;
- Autogerencimento;
- Autodesenvolvimento;
- Conhecimento de Bancos de dados;
- Conhecimento de Infraestrutura web, Git;

**Desejáveis:**
- Conhecimentos Docker , ReactJS, C# e React Native

## Benefícios

• Plano de Saúde e Odontológico – Bradesco Saúde (titular + 2 dependentes);
• Vale Refeição/ Vale Alimentação - Sodexo;
• Auxílio creche (crianças de até 4 anos);
• Seguro de Vida;
• Plano Academia – Gympass;
• Convênio SESC;
• Vale Transporte ou Auxílio Home/Office

## Contratação

CLT

## Como se candidatar

Por favor envie um email para ana.roche@stone.com.br com seu CV anexado - enviar no assunto: "Vaga Desenvolvedor"

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
