### ISSUE TITLE
[Remoto] Front-end Angular Developer Pleno na Tivia

### ISSUE THREAD

**Issue by pvchip1** [frontendbr/vagas#4914]
## Nossa empresa

Somos uma Startup, atuamos a mais de 10 anos no mercado entregando uma solução totalmente web para segmento de Telecom, desenvolvida em (Ruby, Angular), nossa aplicação dispõe de alguns rescursos: emissão de boletos, carnês, integração com gateways de pagamentos (Pagseguro, Boleto Facíl 'Juno', F2B, Gerencianet, GalaxPay), e roteadores MikroTik.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 3 anos Front-End Angular 8+(PWA, Mobile)
- TDD
- HTML/CSS (Bootstrap e Material Design)
- CI (Bitbucket/Jira)
- Scrum/Kanban

## Contratação

- PJ - 4 ~ 6k
Os valores do contrato serão acordados com base nas experiência, skills de cada prestador.
Valores pagos em horas/executadas.
Você escolher em trabalhar quantas horas quiser, sendo o minimo 35 horas semanais.

## Como se candidatar
- E-mail: rh@tivia.com.br com o assunto [VAGA] Front End Pleno
ou
- Linkedin: https://www.linkedin.com/jobs/view/2540026979/

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação

- Remoto

#### Regime

- PJ

#### Nível
- Pleno
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
