### ISSUE TITLE
[São Paulo] Desenvolvedor Mobile - (React Native) na RAIA DROGASIL

### ISSUE THREAD

**Issue by NayaraDantas** [frontendbr/vagas#4917]
Olá Rede a RaiaDrogasil está com a seguinte oportunidade: 🚀
#vemserRD💚

Desenvolvedor Mobile - (React Native)

Descritivo: 

React, React Native, Typescript, GraphQL

Desejável:
- Experiência com administração das lojas Play Store e App Store.
- Experiência com administração de certificados iOS.
- Experiência com processo de deploy Android e iOS.
- TDD (Test Driven Development).
- Experiência com Apps de e-commerce;
- Experiência com metodologias ágeis; 
- Infraestrutura em nuvem, Amazon AWS.

Modalidade: CLT + Benefícios
Local: Home Office - Hibrido 
Currículos e Indicações: nadsilva@rd.com.br

#vagasdeti #vagasti #ti #oportunidadesti #desenvolvedor  #sistemas #programador #vagasabertas #correntedobem

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
