### ISSUE TITLE
[Rio de Janeiro] Full Stack Developer na Go Dream

### ISSUE THREAD

**Issue by rsaadi28** [frontendbr/vagas#4920]
## Nossa empresa

Go Dream

## Descrição da vaga
Tem OPORTUNIDADE de JOB para DESENVOLVEDOR aqui!

Quer fazer parte de um projeto irado junto a um time incrível de desenvolvimento na nossa Ticketeira?

Nossa missão é revolucionar a experiência de nossos clientes produtores de eventos e consumidores com a possibilidade de entrega de um produto único, totalmente customizável que se adapte as necessidades de cada evento.

Aqui trabalhamos para entregar sonhos! E você vai vivenciar a realidade move fast de uma empresa dinâmica e aprender e se reinventar a todo instante!

O trabalho é remoto e precisamos de uma pessoa que acelere conosco em nossos próximos projetos!

Estamos iniciando um time de desenvolvimento e procuramos devs full-stack acima da média para fazer parte dele. Temos um ambiente descontraído, informal e dinâmico, mas também oferecemos a possibilidade de trabalho remoto. Nossa missão é quebrar um monolito em Yii e migrá-lo para aplicações em Angular e NestJS.

## Local

Remoto, com escritório (opcional) no Rio de Janeiro, em Botafogo

## Requisitos

**Obrigatórios:**
-   Experiência mínima de 2 anos com meios digitais (sites, aplicativos, sistemas)
-   Domínio de HTML, CSS e JavaScript
-   Experiência com sites responsivos/grids fluidos
-   Experiência com bibliotecas/frameworks Javascript (React, Angular, etc)
-   Experiência com PHP
-   Código eficiente, escalável, acessível e reutilizável
-   Facilidade para trabalhar em equipe e contribuir com seus pares
-   Boa comunicação verbal e escrita

**Desejáveis:**
-   Conhecimentos de ES6
-   Experiência com Yii Framework
-   Familiaridade com controle de versão (preferencialmente Git)
-   Familiaridade com linha de comando (Terminal)

**Diferenciais:**
-  Participação em projetos open-source

## Contratação

CLT ou PJ

## Como se candidatar

Por favor, envie um email para [rodrigo.teixeira@entradavip.com.br](mailto:rodrigo.teixeira@entradavip.com.br) com seu CV anexado - enviar no assunto: Vaga Full-Stack Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: rodrigo.teixeira@entradavip.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
