### ISSUE TITLE
[Remoto] Front-end Angular Developer na Inicie Educação

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#4921]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-183149?origin=github&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A vaga para desenvolvedor front-end tem como objetivo nos auxiliar a melhorar a experiência de nossos clientes durante a utilização dos sistemas desenvolvidos.&nbsp;</p>
<p>Procuramos uma pessoa que esteja sempre conectada com as novas tendências e consiga transpor o melhor de nossa cultura para os produtos produzidos e consequentemente para nosso cliente final</p>
<p>Nosso público principal são coordenadores, professores, alunos e colaboradores de instituições de ensino que utilizam o pacote GSuite como parte de sua transformação acadêmica</p>
<p></p>
<h6>Nosso novo colaborador será responsável por:</h6>
<ul>
<li>Desenvolver novas interfaces para nossos produtos</li>
<li>Realizar melhorias e correções de sistemas já existentes</li>
<li>Otimizar as aplicações para garantir uma boa usabilidade</li>
<li>Desenvolver a camada de conexão com nosso back-end</li>
<li>Escrever testes automatizados</li>
<li>Documentar todo o código desenvolvido</li>
<li>Manter os produtos atualizados e utilizando as últimas tendências do mercado</li>
</ul>
<p></p>

## Inicie Educação: 
 <p>Nossa proposta é criar um provedor único que atue em todo o processo de transformação digital da educação, melhorando, de ponta a ponta, a jornada dos usuários. Isso porque a união das operações cria uma sinergia única que junta uma grande base de conhecimento a um grupo altamente qualificado de profissionais, que vão desde a produção e desenvolvimento de sistemas até grandes especialistas em elaboração de conteúdo e metodologias de ensino.</p>

<p>A ideia é proporcionar às instituições educacionais uma experiência única, transformadora e inovadora. Juntas, a  metodologia da Nuvem Mestra, que é referência no processo de transformação digital dentro deste mercado, somada à expertise da Edutt/Youtz, que propõem unidades curriculares inovadoras e em sintonia com as tendências globais de ensino, as três têm o potencial de incrementar a fluência digital de colaboradores e alunos a partir de novas experiências. A boa notícia é que elas tornaram-se uma só.</p><a href='https://coodesh.com/empresas/inicie-educacao'>Veja mais no site</a>

 ## Habilidades: 
 - CSS 
- Google API 
- HTML 5 
- Google Cloud 
- Angular 2+ 
- GIT 
- Less
## Local: 
 100% Remoto
## Requisitos: 
 - experiência no desenvolvimento de aplicações responsivas 
- conhecimento em frameworks de interface e ferramentas de design
**Diferenciais:** 
 - Inglês técnico 

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Front-end Angular Developer na Inicie Educação](https://coodesh.com/vagas/desenvolvedor-183149?origin=github&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção <b>Pedir Feedback</b> entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa <b>Recruiter</b> responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
