### ISSUE TITLE
[Remoto] Tech Lead na VipCommerce (Magazine Luiza)

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#4922]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/tech-lead-112822192?origin=github&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Buscamos uma <strong>Pessoa Tech Lead </strong><ins>com foco em arquitetura de software</ins>. Profissional com perfil de destaque, que seja braço direito do CTO e que possa crescer de maneira acelerada juntamente com a VipCommerce.&nbsp;&nbsp;&nbsp;</p>
<p>A VipCommerce é uma empresa especializada em e-grocery, especificamente e-commercepara supermercados, atacarejos e atacados. Atualmente é Líder no segmento na vertente white-label, integrada e homologada com os maiores ERP´s do segmento.&nbsp;</p>

## VipCommerce (Magazine Luiza): 
 <p>A VipCommerce nasceu dentro de um supermercado e com vários anos de experiência no segmento varejista, entendemos o dia-a-dia do setor. E, prevendo que a venda online seria um progresso natural para os supermercados, transformamos nosso conhecimento em uma solução completa e robusta para habilitar as lojas tradicionais a venderem online.</p>

<p>Nosso compromisso é conduzi-lo, através de uma parceria duradoura, nesta transformação digital. Conte com a gente para vender online e faturar mais de um jeito seguro e descomplicado.<br></p><a href='https://coodesh.com/empresas/vipcommerce'>Veja mais no site</a>

 ## Habilidades: 
 - Docker 
- Microsserviços 
- POO 
- Rest API 
- Microservices 
- Unit Test 
- SOLID
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência como Tech Lead ou Sr. Developer 
- Perfil líder, pragmático e empreendedor 
- Práticas de Code Review em e saiba muito sobre código bem projetado, testável e eficiente 
- Experiência em trabalhar com banco de dados relacionais 
- Experiência em REST APIs 
- Ser engajado em pequenos times, clima de startup e negócios que crescem de maneira acelerada (pouca zona de conforto / Lean Startup) 
- Ser engajado com os ideias do negócio, abraçar as causas da empresa e frequentemente ser "confundido com o dono", pelo aspecto do pensamento comprometido. 
- Ser habituado com metodologias ágeis 
- Experiência em projetos com Unit Tests 
- Experiência e conhecimento em Microservicos, SOLID e  Docker
**Diferenciais:** 
 - Conhecimentos desejáveis TDD 
- Contato com cultura DevOps e CI/CD 
- Conhecimento em AWS (EC2, S3) 
- Conhecimentos em desenvolvimento front-end 
- Habituado com AWS Aurora ou MySQL 
- Conhecimentos em MongoDB, PHP + Laravel 
- Conhecimentos em Laravel ou NodeJS/Nest 
## Benefícios: 
 - Convênio Médico e Odontológico Sul América - Nacional 
- Vale Alimentação / Refeição 
- Horários Flexíveis 
- Auxilio Home Office 
- Participação nos Lucros e Resultados 
- PJ ou CLT
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Tech Lead na VipCommerce (Magazine Luiza)](https://coodesh.com/vagas/tech-lead-112822192?origin=github&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção <b>Pedir Feedback</b> entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa <b>Recruiter</b> responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Categoria
Gestão

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
