### ISSUE TITLE
[Remoto/RJ] Front-end Developer Pleno na Stone Age

### ISSUE THREAD

**Issue by lucas-carneiro** [frontendbr/vagas#4925]
## Nossa empresa

Somos uma empresa provedora de serviços inovadores de TI, voltados para soluações analíticas e Big Data, que há mais de 30 anos vem desenvolvendo e implantando projetos bem sucedidos e altamente eficientes. Desenvolvemos sistemas críticos utilizados por grandes empresas nas áreas de Telecom, Financeira, Varejo e Governo.

Desde 2019 a Stone Age, passou a integrar o time da TIVIT, uma empresa multinacional brasileira de soluções digitais com operações em dez países da América Latina.

## Nosso time

Buscamos antecipar necessidades de negócios e criamos soluções inovadoras, flexíveis e com alto desempenho. Usamos as mais novas tecnologias para solucionar problemas críticos de maneira pragmática.

Como parte da equipe de produtos você participará da concepção, desenvolvimento e manutenção de nossas soluções. Você estará inserido em um ecossistema altamente colaborativo e será constantemente incentivado a aprender e utilizar novas tecnologias que possam agregar valor aos nossos produtos.

Fazer parte da área de Produtos e Inovação da Stone Age é tornar possível a transformação digital de empresas clientes em diferentes nichos, participando e sendo responsável pela concepção, desenvolvimento e suporte das aplicações utilizadas por elas diariamente. Para entregar aplicações com alto desempenho, inovação e de forma ágil temos equipes que respiram as mais atuais tecnologias, sempre realizando estudos que hoje permeiam assuntos em inteligência artificial, escalabilidade com ambientes containerizados e serverless.

## Descrição da vaga

Será parte de seu dia a dia como analista de desenvolvimento front-end:

- Participar de um ambiente com metodologias ágeis, sempre buscando aprimorar o nosso processo de desenvolvimento.
- Desenvolver softwares dentro de uma cultura ágil: fazemos pair programming, testes e code reviews.
- Escrever, revisar e implantar softwares que operem em larga escala e com alta disponibilidade.
- Participar de discussões técnicas proativamente, favorecendo a troca de conhecimento entre a equipe e evolução dos nossos produtos.
- Participar da análise de performance de nossos softwares, otimizar e evoluir nossas ferramentas.
- Estudar continuamente novas tecnologias e arquiteturas.

Procuramos por pessoas com espírito de equipe, preocupadas com qualidade de software e que estejam dispostas a contribuir com o desenvolvimento de nossas aplicações.

## Local

Local de trabalho: home office integral em todo Brasil; home office parcial ou presencial com sede no Rio de Janeiro, Jacarepaguá.

> Todas as entrevistas estão ocorrendo de forma virtual devido à COVID-19. Todos os novos integrantes e a nossa equipe atual continuarão trabalhando em home office até que seja seguro retornar para o nosso escritório.

## Requisitos

**Obrigatórios:**
- Construção de aplicações eficientes utilizando React.
- Experiência com desenvolvimento em Typescript.
- Conhecimento em gerenciamento de estados (Redux, ContextApi).
- Integração com APIs através de REST.
- Desenvolvimento de testes (Jest, React Testing Library).
- Frameworks e pré-processadores de CSS (Material UI e Sass, respectivamente).

**Diferenciais:**
- Experiência com teste end-to-end (Cypress).
- Experiência com UI/UX e prototipação usando Figma.
- Conhecimento de ferramentas para o desenvolvimento de componentes de UI (Storybook).
- Conhecimento sobre o uso de Webpack.
- Conhecimento com comunicação com APIs utilizando GraphQL.

## Benefícios

- Vale Refeição e/ou Alimentação acima da média de mercado através do Flash Benefícios.
- Plano de Saúde sem mensalidade nem coparticipação.
- Plano Odontológico sem mensalidade nem coparticipação.
- Participação dos Lucros (Anual) que tem nos deixado felizes nos últimos anos.
- Vale Transporte ou Auxílio Combustível (quando atuamos presencialmente).

**Diferenciais:**
- Incentivo à participação de eventos.
- Incentivo à treinamentos com especialistas em plataformas online; disponibilizamos cursos EAD (Mobiflix) e licença da Alura para capacitação constante do nosso time.
- Relações de trabalho em um ambiente horizontal.
- Não há dress code formal; você pode usar a vestimenta que mais considera confortável. Pode ir, por exemplo, de bermuda e chinelo para o trabalho!
- Espaço para descontração na sede do RJ: ping-pong, sinuca, videogame, jogo de dardo, dentre outros jogos e também shiatsu para poder relaxar um pouco!
- Aqui valorizamos trocas, inovação e temos foco em pessoas. Acreditamos em relações duradouras, baseadas na transparência e ética. Temos pessoas com 5, 10, 15 e 20 anos de casa.
- Não deixamos passar em branco datas comemorativas. Por isso fazemos ações como entrega de bolo na casa dos aniversariantes do mês.

## Contratação

CLT.

## Como se candidatar

Se cadastre na vaga dentro da plataforma [Kenoby](https://jobs.kenoby.com/tivit/job/analista-de-desenvolvimento-pl-i-front-end/5f52c6d49803e86f24dab081?utm_source=github).

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
Caso não haja resposta, entre em contato com o e-mail do(a) recrutador(a) que prosseguir com o seu processo seletivo.

## Labels
- Alocado
- Remoto
- CLT
- Pleno
- Sênior
- React

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by lucas-carneiro** [comment]
Opa, podemos manter aberta sim, a vaga ainda está disponível.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
