### ISSUE TITLE
[Remoto] Front-end Developer - Vue.js na Clicksign

### ISSUE THREAD

**Issue by FrancieleTuchinski** [frontendbr/vagas#4927]
## Nossa empresa

Já pensou trabalhar em uma empresa em que você pode construir um produto único, que facilita a vida de várias pessoas e empresas e que vem crescendo muito mesmo em meio a pandemia?
E se eu te disser que essa empresa também trabalha com as tecnologias mais atuais e foca sempre na excelência do código e na autonomia dos colaboradores, trabalhando com uma metodologia inovadora e diferenciada, o Shape Up?
Temos tudo isso e mais um pouco aqui na Clicksign!! Somos uma empresa de assinatura eletrônica de documentos e buscamos, cada vez mais, facilitar os processos e reduzir a burocracia das organizações.

## Descrição da vaga

Nesta posição de Front-end Developer você conseguirá fazer a construção visual de um produto de forma consistente, proporcionando uma experiência incrível aos nossos usuários
As principais atividades serão: 
Entregar valor ao produto, interpretando e materializando especificações de UX/UI
Garantir qualidade de código, escrevendo códigos limpos e eficientes
Seguir boas práticas de desenvolvimento visando manutenibilidade do código e documentação
Trazer novas ideias e aplicar técnicas de performance visando o melhor funcionamento da aplicação
Trabalhar em equipe, com base em muita colaboração, utilizando a metodologia ShapeUP

## Local

Remoto

## Requisitos

**Obrigatórios:**
Conhecimento em: 
HTML / CSS / JS
Framework client-side entre: Vue.js, React, Angular (ao menos um desses)
Plataforma Linux / MacOS
Git
Familiaridade com APIs RESTful
Rotina de uma empresa que vive na veia a metodologia ágil centrada no cliente
Autogestão

**Desejáveis:**
Ruby on Rails
Coffeescript/Typescript
Sass ou Less
Vue.js e Vuex
BDD/TDD
Times Remotos
Troca de feedbacks francos

## Benefícios
Período de pausa (Sabemos o quão importante é a pausa você passar um tempo com a família) 
Para nós o Home Office já é padrão há alguns anos, por isso, a vaga seria para ser exercida remotamente, mesmo após a pandemia 
Descontos em aulas de inglês e em sessões de terapia com nossos parceiros, assim você pode buscar a melhoria profissional enquanto cuida da sua saúde mental
Uma cultura de muita confiança, focada em resultados. Sem micro gerenciamento, muita autonomia e transparência
Muito desafio e aprendizado. Buscamos excelência em tudo o que fazemos, por isso estamos sempre aprendendo
Colaboração e empatia, valorizamos muito as pessoas que estão nesse desafio com a gente e adoramos bater um papo e realizar nossos 1:1 quinzenais
Possibilidade de Crescimento real dentro da Clicksign
Um ambiente massa, ou como dizem os Clicksigners, um “Ambiente sensacional” 

## Contratação
PJ 

## Como se candidatar
Interessados cadastrar currículo no portal https://jobs.kenoby.com/clicksign/job/desenvolvedor-front-end/5f52845bcd16b75118283053?utm_source=website

## Tempo médio de feedbacks
Costumamos enviar feedbacks em aproximadamente 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: franciele.pires@clicksign.com

#### Regime
- PJ

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by educbraga** [comment]
Ainda disponível? O link para candidatura não contém informações sobre a vaga.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
