### ISSUE TITLE
[Joinville/SC] - Front-End Developer na ContaAzul (foco em performance) 

### ISSUE THREAD

**Issue by fernahh** [frontendbr/vagas#493]
## Descrição da vaga

Opa, eu aqui de novo :smile: 

Buscamos desenvolvedor front-end sênior com **foco em perfomance**, onde irá trabalhar com projetos como redução de _initial page load_ e otimização de _critical rendering path_.

Estamos desenvolvendo uma das maiores plataformas SaaS do Brasil, onde enfrentamos vários desafios de como escalar uma aplicação e manter consistência de nossas UI em diferentes produtos para micro e pequenos empreendedores.

> https://github.com/contaazul

## Local

Alocado no escritório, em [Joinville, SC](https://contaazul.com/carreiras/sobre-joinville/) (uma das melhores cidades do Brasil pra se viver, só dar uma _googlada_).

> https://contaazul.com/carreiras/sobre-joinville/

## Benefícios

- Um ambiente de trabalho diferente e inovador, com uma cultura que valoriza as pessoas e a entrega de resultados;
- Autonomia e flexibilidade;
- Cozinha sempre abastecida com lanches **ilimitados**;
- Salário compatível, acima da média do mercado;
- Ticket refeição/alimentação;
- Auxílio financeiro para gradução e pós-graduação;
- Ajuda financeira para aprender inglês;
- Afiliação com farmácias;
- Plano de saúde completo e **sem desconto** no seu salário;
- Plano odontológico completo e **sem desconto** em seu salário;
- Ajuda financeira para atividades físicas;
- Uma equipe que tem nossos valores em seu DNA;
- Vivendo em uma das melhores cidades para viver no Brasil;
- Acesso a livros e outros materiais;
- Assistência em Transporte.

> https://contaazul.com/carreiras/beneficios/

## Requisitos

- Conhecimento de padrões de desenvolvimento, como SOLID, Clean Code e Design Patterns e TDD;
- Experiência com arquitetura Front-end, perfomance, desempenho e testabilidade;
- Experiência com tecnologias JavaScript (frameworks, node.js, etc);
- Experiência com CSS, e algum pré-processador de CSS em grande escala;
- Experiência com SPA;
- Experiência com ferramentas de automação front-end como Gulp ou Webpack.

> https://jobs.lever.co/contaazul/860aa08b-d4ba-4f54-86bd-66bd5a37d6b9

## Contratação

CLT.

## Nossa empresa

A ContaAzul é startup que nasceu em 2007 e hoje tem um dos maiores sistemas SaaS do Brasil. Aqui temos especialistas de diversas áreas (front-end, back-end, design, UX, marketing, etc) que trabalham com o objetivo de criar soluções para facilitar a vida dos micros e pequenos empresários. 

Há pouco tempo, ela ficou entre as [10 empresas mais amadas por seus funcionários, segundo a Love Mondays](https://noticias.contaazul.com/ranking-love-mondays-contaazul-entre-as-10-empresas-mais-amadas-por-seus-funcion%C3%A1rios-f11ed6f7ad28). Temos diversas guildas que tem uma forte influência sobre as decisões de nossos produtos. 

Se quiser ler um pouco sobre o que fazemos aqui, recém lançamos o [blog da nossa engenharia](https://engineering.contaazul.com/).

> https://contaazul.com/carreiras/

## Como se candidatar

Só se aplicar na [página da vaga](https://jobs.lever.co/contaazul/860aa08b-d4ba-4f54-86bd-66bd5a37d6b9). Caso queira trocar uma ideia sobre como é trabalhar aqui, sinta-se a vontade pra falar comigo também :)

**Comment by thiagogodoy** [comment]
Show @fernahh só para complementar o ContaAzul essa semana ( 15/08/2017 ) Lançou em parceria com o Banco do Brasil a [primeira parceria de Open Banking no Brasil](http://www.bb.com.br/pbb/pagina-inicial/imprensa/n/56294/BB%20anuncia%20primeira%20parceria%20de%20Open%20Banking%20no%20Brasil#/) a ContaAzul está a todo vapor ;)
