### ISSUE TITLE
[Remoto] Front-end Developer na Zygmus (USD)

### ISSUE THREAD

**Issue by pablonajt** [frontendbr/vagas#4931]
## Nossa empresa

https://zygmus.com

## Descrição da vaga

For a company in the US, we are looking for a freelance 100% remote FrontEnd developer with excellent rates in USD.

## Local

100% Remoto

## Requisitos

**Obrigatórios:**
- 6+ years of experience in IT
- Good English level (B2 or better)
- 2 years of experience with React
- Good experience with HTML, CSS, Javascript / Typescript

**Desejáveis:**
- Unit Testing in FrontEnd (w/JEST or similar)

**Diferenciais:**
- Previous experience working remotely with customers in English.

## Contratação

Freelance

## Como se candidatar

Por favor envie um email para talent@zygmus.com com seu CV anexado - enviar no assunto: Vaga FrontEnd

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 30 dias após cada processo.
E-mail para contato em caso de não haver resposta: talent@zygmus.com

#### Alocação
- Remoto

#### Regime
- Freela

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
