### ISSUE TITLE
[São Paulo] Web Designer & Front-End Developer no Cuponomia

### ISSUE THREAD

**Issue by rafaelpradella** [frontendbr/vagas#494]
## Descrição da vaga

Startup oferece vagas de estágio para alunos cursando entre o 2º e 6º semestre da faculdade, para criar e desenvolver interfaces para o nosso site, além de peças para redes sociais e email marketing.

Interessados mandar currículo e portfólio (pode ser no Github ou Behance, como preferir) para [`rafael@cuponomia.com.br`](mailto:rafael@cuponomia.com.br)

## Local

Escritório na Chácara Santo Antônio, São Paulo/SP. Perto da Est. Granja Julieta da CPTM.

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ 22/dia
- Vale-Transporte

## Requisitos

**Obrigatórios:**
- Desenhar páginas utilizando HTML5 e CSS3
- Noções de Javascript
- Design gráfico básico (software de desenho vetorial e bitmap)

**Diferenciais:**
- Utilizar pré-processadores como LESS/SASS/Stylus
- Noções de SEO e HTML semântico
- Layout responsivo
- Familiaridade com Sketch e/ou Affinity Designer

## Contratação

Estágio com possibilidade de efetivação, com bolsa-auxilio entre R$900-R$1000

## Nossa empresa

O Cuponomia é um site totalmente gratuito que oferece desconto através de cupons e ofertas das principais lojas online nacionais e internacionais. São mais de 20.000 cupons em 2.000 lojas disponíveis, atualizados e testados diariamente.

Nós negociamos com os melhores e-commerces e vasculhamos toda a internet para encontrar e oferecer cupons exclusivos e descontos especiais.

Trabalhamos duro para garantir que todos os cupons da internet brasileira estarão disponíveis no Cuponomia.

**Comment by gadielkalleb** [comment]
o contrato é exclusivamente estagio ou só é um titulo do cargo  ?

**Comment by rafaelpradella** [comment]
@gadielkalleb Isso, essa vaga é exclusivamente para estágio.
