### ISSUE TITLE
[BARUERI/SP] Front-end Developer na Dry Company do Brasil

### ISSUE THREAD

**Issue by caiosalim** [frontendbr/vagas#4941]
## Nossa empresa
Venha trabalhar na Dry, empresa lider no segmento de MVNOs de Futebol do país.

## Descrição da vaga
Procuramos um profissional front-end jr. que venha agregar ao time, sendo além de um profissional de front-end, uma figura de tecnologia dentro da empresa.

## Local
Escritório, [SP], [Barueri], [Bethaville]
(av. anapolis 510)

## Requisitos
Conhecimentos sólidos em HTML, CSS e JS.

**Desejáveis:**
- Wordpress/Woocommerce

## Benefícios
Vale Transporte
- ...

## Contratação

CLT ou PJ

## Como se candidatar
Por favor envie um email para caio@drycompanybrasil.com.br

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 1 dia após cada processo.

#### Alocação
- Alocado

#### Regime
- CLT
- PJ

#### Nível
- Júnior

**Comment by francineh** [comment]
tenho interesse na vaga... acabei de mandar um e-mail com o meu currículo anexado, mas gostaria de deixar o link do meu perfil aqui:
https://github.com/francineh?tab=repositories

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
