### ISSUE TITLE
[Remoto] Front-end Developer Jr na Moodar

### ISSUE THREAD

**Issue by joaovictortinoco** [frontendbr/vagas#4942]
## Nossa empresa

Startup Recifense com objetivo de encontrar seu(a) Psicólogo(a) online e começar a cuidar do seu emocional.
Para mais informações:
https://moodar.com.br/

## Descrição da vaga

Projeto utiliza front end ReactJs e React Native.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Conhecimento em ReactJs
- Conhecimento em React Native
- Boa comunicação;
- Visão centrada no usuário;
- Apreço pela qualidade e clareza do código;
- Abertura para dar e receber feedbacks

**Desejáveis:**
- Conhecimento em Python/Django
- Conhecimento em Firebase
- Conhecimento em AWS

## Benefícios
- Terapia online financiada pela empresa
- Cursos financiados pela empresa- Plano de saúde

## Contratação

Bolsa de R$3.300,00 (líquido R$3.000,00)
CH de 40h/semanais

## Como se candidatar

Por favor envie um email para rh@moodar.com.br com seu CV anexado - enviar no assunto: Vaga Front End

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior

**Comment by francineh** [comment]
Prezado: tenho interesse na vaga, acabei de lhe enfiar um e-mail com meu currículo anexado, mas segue o link daqui do Git: https://github.com/francineh?tab=repositories

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
