### ISSUE TITLE
[100% remoto] Front-end Developer  na Invillia

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#4944]
## Nossa empresa

A Invillia é uma empresa global de Inovação e Tecnologia que possui clientes como iFood, Gympass e 99.

## Descrição da vaga

- O(a) profissional será responsável em prover soluções técnicas para novas features e dar o suporte necessário as features já existentes, afinal, nem tudo são flores.
- Esperamos também que essa pessoa auxilie os outros membros do time em questões técnicas não esquecendo de fornecer a melhor solução para o negócio.
- Algo que prezamos bastante é qualidade, isso inclui um código limpo e legível (clean code).
- Também é desejável que o mesmo tenha um perfil intra-empreendedor, onde seus objetivos estejam alinhados com os objetivos da empresa, afinal, temos muito orgulho do que fazemos aqui!

## Local

100% remoto

## Requisitos

**Obrigatórios:**

- React e Hooks;
- Gerenciamento de Estados (Redux);
- HTML5, CSS3 (Sass), Javascript, JSS, WebSockets e Bootstrap/Material Design;
- Git, Docker, Gulp, Webpack, Gerenciamento de Pacotes (ex: NPM, Yarn) e TDD;
- Soluções e definições de arquitetura (Flux Architecture, SAGA Pattern);
- Conhecimento teórico e prático em microserviços e APIs;
- JWT, RestFull, Rest Hateoas, oAuth2.0;
- Padrões de Projetos (DDD, Solid, Design Patterns);
- Integração e entrega contínua (CI/CD);
- Banco de Dados Relacional e Não-Relacional;
- Desenvolvimento Ágil - Scrum e Kanban;

**Diferencial:**
Ferramentas de monitoramento (Mesos, Splunk. Kibana)

## Benefícios

- Cartão Mastercard com créditos Invillia. Ele concentra seus benefícios fixos e comemorativos relacionados a alimentação, lazer, bem-estar, educação, auxílios, recompensas  e gratificações corporativas, que são potencializados por descontos exclusivos. De cursos de aprimoramento a academias de ginástica, e acompanhados online  por uma plataforma simples e prática. 
- Um valor inicial para investir no seu(s) local(is) de trabalho. 
- Uma recompensa mensal para manter ou variar de ambiente. 
- Auxílio creche até os dependentes  completarem 2 anos. 
- Vale Hello World (livre) de felicitação por  nascimento dos filhos. 
- Plano Saúde de abrangência Nacional. Sem co-participação e com opção para acomodações em apartamentos. E ainda tem  a opção de um plano de saúde odontológico para você e sua família. 
- E muito, muito mais. 

## Contratação

CLT

## Como se candidatar

Estamos com posições abertas para :
- [Pleno ](http://bit.ly/invillia-front-pleno)
- [Sênior](http://bit.ly/invillia-front-sr)

OBS: esta publicação foi feita via [Remotar Jobs](www.remotar.com.br?utm_source=github)

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
