### ISSUE TITLE
[São Paulo/SP] Front-End/Full-Stack (Node.js) Developer na MJV Inovação

### ISSUE THREAD

**Issue by alanjhonnes** [frontendbr/vagas#495]
## Descrição da vaga

Projeto de Inovação utilizando tecnologias bleeding-edge. Aqui você terá vivência constante com tecnologias atuais e terá liberdade para propor novas soluções inteligêntes e inovadoras. Fará parte de um time comprometido com a qualidade do projeto, seguindo metodologia SCRUM com sprints de 3 semanas. 

Projeto utiliza TypeScript de ponta a ponta seguindo regras estritas de qualidade (--strict), então o profissional poderá atuar em ambos os projetos (Front e Back) com facilidade,  de acordo com o perfil que ele estiver melhor familiarizado.

## Stack Frontend:
- Angular 4.3
- Angular Material
- Angular-CLI
- NgRx
- Apollo Client
- SCSS
- Typescript 2.3.4

## Stack Backend:
- Node.js
- Typescript 2.4
- RxJS
- Knex
- OracleDB
- GraphQL (Apollo Server)
- DataLoader

## Local

São Paulo, Zona Sul (Interlagos)

## Benefícios

- Plano de saúde
- Plano Odontológico
- Seguro de vida
- VR de R$ 20/dia
- VT
- VA
- Vale Gasolina

## Requisitos

**Obrigatórios:**
- Experiência com Angular 2+
- Ser fã de TypeScript

**Desejáveis:**
- Conhecimentos em Node.js
- Facilidade em trabalhar com Typescript seguindo melhores práticas (strict mode) 
- Conhecimentos em NgRx / Redux
- Ter trabalhado em times ágeis com metodologia SCRUM

**Diferenciais:**
- Conhecer programação funcional em Javascript
- Experiência com RxJS
- Experiência com NgRx
- Testes unitários com Jasmine
- Conhecer GraphQL
- Conhecer Knex

## Contratação

CLT Full - de R$4000 a R$7000 + Benefícios (De acordo com experiência e senioridade).
Horário 09h às 18h, com flexibilidade +- de 1h.

## Nossa empresa

Unimos a tecnologia aos nossos conhecimentos em Design Thinking, Gamificação, Big Data/Analytics, Metodologia Lean e Estratégia Digital para levar ao mercado soluções inovadoras em produtos e serviços.

## Como se candidatar

Por favor envie um email para alan.sa@mjv.com.br com seu CV anexado - enviar no assunto: "Vaga Front-End" ou "Vaga Full-Stack"

**Comment by victorhcosta** [comment]
Remoto?
Junior?

**Comment by alanjhonnes** [comment]
Há possibilidade de trabalho remoto conforme demanda do projeto ( necessidade de horas extras, etc), mas somente nesse caso.

Preferencialmente profissional Pleno/Sênior, mas estamos buscando diversos profissionais para o time, então se você tem facilidade em aprender coisas novas, não evite de mandar CV!

**Comment by victorhcosta** [comment]
Então, a pergunta foi por que sou do RJ, e no momento me mudar é inviável, infelizmente.
Mas quem sabe em outro momento ;-;

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
