### ISSUE TITLE
[Curitiba-PR] Front-end Developer na @Commcepta

### ISSUE THREAD

**Issue by commcepta** [frontendbr/vagas#4952]
> Vaga Remota durante a pandemia. Após fim da Pandemia será avaliado possibildiade de trabalhar de forma híbrida.

## A Commcepta
Desde 2000 a Commcepta atua na área de Design Management que abrange não somente projetos de Design mas também projetos de Tecnologia. Aplicamos métodos de Design que tornam-se tangíveis através de Projetos Digitais. Se inovação e tecnologia você considerada fundamental para sua carreira, então o convidamos para integrar nossa equipe.

## Atividades e Responsabilidades

// Pesquisa & Benchmark
1. Propor melhorias e estar sempre antenado com o mercado procurando trazer as melhores práticas e soluções
2. Estar sempre em busca de novos desafios e tecnologias

// Perfil
1. Ser minucioso com os detalhes não deixando escapar um ponto e vírgula além de manter o padrão de indentação
2. Enfrentar códigos "cabeludos" e transformar em códigos perfeitos
3. Vontade de crescer e se tornar fundamental para o andamento da empresa
4. Ser inovador e evitar repetição de tarefas manuais
5. Ser responsável e saber autogerenciar o seu tempo, baseado em prazos e priorizações

// Integração com a equipe
1. Compartilhar conhecimentos com a equipe
2. Gostar de solucionar problemas, inovar e saber aceitar a opinião dos outros
3. Trabalhar colaborativamente junto ao Designer UI e à equipe de desenvolvimento Backend
4. Trabalhar com vários projetos simultâneos onde um não interfere no outro e o prazo é cumprido

## Local
Remoto ou Escritório, [PR], [Curitiba], [Centro]

## Requisitos

- Formação Nível Superior em Ciência da Computação, Análise de Sistema, Tecnologia da Informação, Web Design ou afins
- Fluência em HTML(5) + Semântico / CSS(3) / Sass
- Fluência em Javascript
- Domínio no uso do GIT
- Noções de PHP
- Conhecimento de pelo menos um framework (Angular / Vue / React)
- Desenvolvimento Responsivo
- Experiência com webservices (REST, SOAP)
- Conhecimento básico de ferramentas para automação de testes
- Conhecimento básico em ferramentas gráficas como Adobe Photoshop ou XD
- Melhoria de códigos em páginas já desenvolvidas, visando melhor performance ou atualização de tecnologia

## Benefícios
- VR de R$ 17,50/dia
- VT

## Contratação
CLT

## Como se candidatar

Por favor envie um email para vagas@commcepta.com.br com seu CV anexado - enviar no assunto: Vaga Front-End Developer

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 3 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
