### ISSUE TITLE
[Remoto] Desenvolvedor(a) Front-end (Junior e Pleno) na Lad Sistemas

### ISSUE THREAD

**Issue by danielcordeiro** [frontendbr/vagas#4954]
## Nossa empresa

Empresa que atua a mais de 6 anos fornecendo tecnologia para bares e restaurante.

## Descrição da vaga

Atuação como desenvolvedor front-end em projetos relacionados a restaurante, delivery, cardápio digital, etc

## Local

Remoto ou Escritório, GO, Goiânia

## Requisitos

**Desejáveis:**
- conhecimentos em Angular 4+
- conhecimentos em HTML, CSS e Typescript

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para time@ladsistemas.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
