### ISSUE TITLE
[Curitiba] Front-end Developer na Plastika TWY Produtos Digitais

### ISSUE THREAD

**Issue by guilhermegrunberg** [frontendbr/vagas#4956]
Olá! Estamos buscando um profissional com experiência em Front-End React para compor nosso time de desenvolvimento aqui na Plastika TWY Produtos Digitais.

Somos uma consultoria de design e desenvolvimento ágil de produtos digitais. Ajudamos clientes a projetar e desenvolver produtos digitais significativos, seguros e à prova de futuro, centrados nas necessidades dos usuários. 

## Descrição da vaga

Experiência com Javascript e framework React;
Experiência pré-processadores CSS (SASS e LESS)
Experiência com API REST;
Experiência em React/Redux 
Experiência com versionamento de código Git.

## Local

Remota - Curitiba/Paraná

**Obrigatórios:**
2 anos de experiência com Javascript e React

**Desejáveis:**
Experiência com soluções Amazon AWS;
Experiência com processos de deploy;

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para hello@plastikastudio.com.br com seu CV anexado - enviar no assunto: Vaga React
## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.
E-mail para contato em caso de não haver resposta:hello@plastikastudio.com.br

#### Alocação
Remoto

#### Regime
PJ

#### Nível
Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
