### ISSUE TITLE
[São Paulo] Front-end Developer na ZankH

### ISSUE THREAD

**Issue by viczampa** [frontendbr/vagas#4958]
> Vaga alocada no escritório na Av. Chucri Zaidan, 1550.

## Nossa empresa

Exemplo: A ZankH é uma fábrica de e-commerce. Nos responsabilizamos pela implantação total do e-commerce.

## Descrição da vaga

Suporte e manutenção a uma plataforma de e-commerce escrita em Vue.JS.

## Local

Escritório, São Paulo, Capital, Av. Dr. Chucri Zaidan 1550 ( ao lado do shopping morumbi ) 

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com HTML / CSS / JS

**Desejáveis:**
- Conhecimento em Vue.JS
- Angular ou React

**Diferenciais:**
- projetos opensource

## Benefícios

- Salário R$ 2.100,00 / mês
- Auxílio Transporte 
- Auxílio Refeição - Incluso

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para contato@zankh.com.br com seu CV anexado - enviar no assunto: Vaga ZankH - Front END Júnior / Pleno.

Enviar uma mensagem via Whats App, ou ligar para (11) 99163-4788 demonstrando interesse na Vaga  Front END Júnior / Pleno.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

#### Alocação
- Alocado em Escritório

#### Regime

- PJ
 
#### Nível
- Júnior ou Pleno

**Comment by eusousalvi** [comment]
Sério que pede 3 anos de desenvolvimento, possível framework, presencial, PJ, por 2.1k ( já com auxílio transporte ) e o diferencial é ter 1 hora de almoço? Piada?

**Comment by emersonhenriquedev** [comment]
Além de tudo, o salário de 2,1k é um benefício kkk

**Comment by yurimutti** [comment]
R$ 2.100,00 - transporte - contador - imposto. O loko!!! kkkkkk

**Comment by gabok2** [comment]
golpe tá ai, cai quem quer

**Comment by helenapaixao** [comment]
Vaga Arrombada
