### ISSUE TITLE
[Brasil - possibilidade Remoto] Front-end Developer na AutomTech

### ISSUE THREAD

**Issue by AutomTech** [frontendbr/vagas#4959]
> Vaga para todo o Brasil com regiões remotas

## AutomTech IT Solutions

Soluções na área de TI: recruiting, consulting e outsourcing.

## Descrição da vaga

Desenvolvimento Front-End para integrar o time de inovação do segmento bancário.

## Local

Para todos os estados do Brasil, com regiões remota.

## Requisitos

**Obrigatórios:**
- Angular.

**Desejáveis:**
- Linguagem de desenvolvimento: Angular (Preferência 8), CSS, HTML, JavaScript, TypeScript;
- Desenvolvimento de testes unitário TDD;
- Conhecimento de arquitetura Cloud;
- Conhecimento das ferramentas Atlassian (Jira, Bitbucket, Confluence).

## Benefícios

- Assistência Médica, 
- Assistência Odontológica, 
- Seguro de Vida, 
- Vale Refeição/Alimentação,
- Mais benefícios exclusivos.

</div><br class="Apple-interchange-newline">

## Contratação

CLT.

## Como se candidatar

Por favor envie um e-mail para trabalheconosco@automtech.com.br com seu CV e pretensão salarial - enviar no assunto: Vaga Angular OU aplique-se à oportunidade através do link  https://lnkd.in/d7MZmQF. 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
WhatsApp para contato em caso de não haver resposta: 41- 98789-1138

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by DevCleverton** [comment]
Em qui, 27 de mai de 2021 13:39, AutomTech - Soluções em TI <
***@***.***> escreveu:

**Comment by DevCleverton** [comment]
pdf.pdf

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
