### ISSUE TITLE
[Remote] Front-End Developer at Sherpany (Lisbon & Zurich)

### ISSUE THREAD

**Issue by dsalvagni** [frontendbr/vagas#496]
### Fulltime Remote FE Developer

As our core UI Developer you will be working 100% on mission critical projects from the first day on. While cooperating in a small and highly efficient Scrum team you will be responsible for developing the User Interface of the Sherpany Boardroom.

Your skills contribute to the success of the software and enable us to create a perfect product. Together we will move the current UI to the next level. Our goal is to create a User Interface which can compete with any globally renowned application. Finally we will tightly work together to raise the potential of our technologies.

#### Our ambition: Challenge the enterprise world

Our mission is to give time back. We are building the first mobile and web based platform that allows effective decision making by digitally transforming the meeting process of executives and board members. We reduce waste by cutting administrative, organisational and repetitive work and spare resources like paper, shipping and transportation.

With our platform we want to have given back over 2 Mio. hours of extra time to directors within the next 5 years. Therefore we are extending our teams, also in Zurich (Switzerland) Lisbon (Portugal) or worldwide. We are looking for an ambitious Front End Developer to join our company.

### Requirements 

- You are obsessed with apps and you stay up-to-date with mobile UI/UX trends
- You have the aspiration to build one of the best webapp in the world
- Write solid and re-usable HTML, CSS and JavaScript for websites and applications
- You have a strong opinion but no problem to accept other views. Discarding the 20th design, to dig even deeper? No problem for you!
- Strong IT fundamentals with a bachelors or masters in computer science, engineering, or equivalent industry experience.
- 5+ years of experience of web development with HTML , CSS3,  especially Backbone.js and jQuery

### Welcome to our Team!

We offer a young and striving work environment with varied areas of excellence in a a dynamic, goal-oriented team with top prospects for a long-term commitment.

Have a look at our video to learn what it is like to work at Sherpany:
[![Why working at Sherpany is more than a job?](https://img.youtube.com/vi/kRTZW16D1ew/0.jpg)](https://www.youtube.com/watch?v=kRTZW16D1ew)

### How to apply
Please, apply over BambooHR on the following link: https://sherpany.bamboohr.co.uk/jobs/view.php?id=47

I've been working as a Sherpanee for about one year. Feel free to ping me if you any have questions :)

**Comment by dsalvagni** [comment]
Alguém poderia adicionar as _labels_ de **Remoto - Total**, **Senior** e **PJ** (não necessariamente PJ, mas não é CLT). Obrigado!

**Comment by netojose** [comment]
Vaga massa. Exigências não muito altas, e certamente excelentes experiências no decorrer do trabalho.

**Comment by vinyguedess** [comment]
Ainda aberto ?

**Comment by dsalvagni** [comment]
Ainda aberta Vinicius.

**Comment by marciogurka** [comment]
ainda aberta @dsalvagni ???
