### ISSUE TITLE
[Remoto] Senior Front-end Developer Azion Technologies

### ISSUE THREAD

**Issue by Fernandazion** [frontendbr/vagas#4961]
> 

## Nossa empresa

A Azion é uma empresa de produtos de Edge Computing que está em grande expansão. No final de 2020 tivemos fechamento com dois grandes fundos (Qualcomm e Monashees) que já investiram em diversas empresas que tiveram crescimento exponencial. Referências como Gartner apontam Edge Computing como uma das principais tendências em termos de tecnologia/infraestrutura para os próximos anos.

## Descrição da vaga

Você atuará na arquitetura, criação, componentização e manutenção de diversos sistemas, incluindo plataformas de autenticação, Marketplace, gerenciamento de configuração em Edge de clientes, dentre muitos outros desafios. Você terá envolvimento em todo o processo, desde a análise do problema até o desenvolvimento, teste, monitoramento, e sua entrega em ambiente de produção.

## Local

Remoto. Temos escritório em Porto Alegre e São Paulo para quem interessar.

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento frontend (HTML/CSS/JS);
- Experiência com VueJs ou outro framework de mercado (React, Angular);
- Experiência com desenvolvimento em ambiente UNIX;
- Conhecimento de componentização e boas práticas de UI e UX;
- Conhecimento de Client-Side APIs (DOM, Storage, XmlHttpRequest etc);
- Conhecimento de modelos de API REST;
- Conhecimento de requests HTTP;

**Desejáveis:**
- Conhecimento de GIT, fluxos de desenvolvimento em times;
- Conhecimento de fluxos de CI e CD;
- Boa organização de código e conhecimento de boas práticas;
- Conhecimento de ferramentas de teste;
- Inglês intermediário ou avançado.

**Diferenciais:**
- Conhecimento de utilitários e serviços de cloud (AWS, GCP, Digital Ocean etc);
- Conhecimento de containers e conceitos relacionados (Docker, Compose, Kubernetes);
- Conhecimento de banco de dados SQL e NoSQL;
- Conhecimento de API GraphQL;
- Conhecimento de storybook.

## Benefícios

- Plano de saúde
- Plano Odontológico
- Seguro de vida
- VR/VA
- 200 reais para personalizar sua mesa

**Diferenciais:**
- Remoto
- Bebida liberada no escritório
- Sala de jogos
- Happy hour

## Contratação

CLT

## Como se candidatar

Por favor se inscreva através do site https://www.azion.com/en/careers/job/?id=job_20200831145756_W5CENIU8KXDEGFPH ou envie um email para fernanda.azion@gmail.com com seu CV anexado.

#### Nível

- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
