### ISSUE TITLE
[SÃO PAULO] Front-end Developer na @Idwall

### ISSUE THREAD

**Issue by JulianaPiau** [frontendbr/vagas#4962]
A Idwall, startup focada em tecnologia para resolver o problema bilionário das Fraudes de Identidade no Brasil, está buscando Front-end Developer para compor o time. 

Você será parte do squad do produto SDK, juntamente com um time multidisciplinar com pessoas de mobile e dados, buscando otimizar o desempenho dos aplicativos pela adição de funcionalidades a produtos digitais já existentes. O foco majoritário seria em Javascript, mas o conhecimento em Typescript e React também é bem vindo.

Nível: Sênior

Local: São Paulo (próximo a Av. Paulista). 

Requisitos: 
- Mindset colaborativo
- Experiência com cloud computing
- Experiência com React.Js

Diferenciais:
- Conhecimento sobre TDD;
- Conhecer sobre Typescript e Angular.
- Tiver atuado com metodologias ágeis – Kanban, Scrum e XP.

Benefícios:
- Vale Refeição de R$710,00/mês
- Vale Alimentação de R$ 300,00/mês
- Vale Transporte (opcional com desconto de 6% em folha)
- ZenKlub para terapia ou coaching 1x por semana com custo zero
- Auxílio Creche (para filhos de 0 a 5 anos) no valor de R$422,65
- Plano de Saúde
- Plano Odontológico
- Seguro de Vida
- Gympass

Contratação: CLT

A Idwall valoriza a cultura organizacional, a diversidade e a construção em conjunto com seus colaboradores. Quer fazer parte desse time incrível? 

Você encontra mais informações em: https://byintera.in/iwjssl

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
