### ISSUE TITLE
[REMOTO] Fullstack Developer @ Marcadinhu

### ISSUE THREAD

**Issue by NovareRH** [frontendbr/vagas#4963]
## Nossa empresa

A Marcadinhu é um aplicativo  de agenda inteligente que faz a ponte entre profissionais liberais no ramo de beleza e de bem estar com o cliente final. Facilitando, otimizando e agilizando o dia a dia. Conectando buscas de serviços com clientes.
O conceito de negócio da Marcadinhu é oferecer serviços fáceis, amigáveis e seguros, que geram economia de eficiência para as profissões que dependem de agendar e reservar seus clientes ao longo do dia. Apresentam a missão de simplificar o trabalho de seus membros prestadores de serviço, economizando tempo e dinheiro e levar praticidade e bem estar aos nossos clientes.

## Descrição da vaga

- Corrigir bugs existentes na plataforma;
- Propor e desenvolver soluções para o desenvolvimento de novas features previstas no roadmap de produto. 
- Testar e garantir a qualidade das próprias entregas; 
- Build e publicação das novas versões dos aplicativos Android e iOS. (se vc nunca fez isso, blz, o cliente vai te mentorar).
**Desafios:**
- Participará do início de uma startup em processo de MVP e as possibilidades são infinitas;
- Trabalhará com novidades todos os dias;
- A cultura de ownership, onde você se sente dono, é muito valorizada, pois esse profissional será um pilar na empresa e suas opiniões serão importantes para o futuro.

## Local

[REMOTO]

## Requisitos

**Obrigatórios:**

- Linguagens - PHP, HTML, CSS, Javascript
- Framework - Laravel (backend PHP) e Ionic (frontend Angular)
- Banco de Dados - MySQL
- GIT
- Ensino Médio Completo com cursos especializados em tecnologia. 

**Diferenciais:**
- Ser uma pessoa aberta a fazer diferente, a testar novas coisas e fazer parte da construção de algo totalmente novo.
- Experiência nas tecnologias da vaga. 
- Criatividade.
- Foco no Resultado.
- Proatividade.
- Resolução de Problemas.
- Responsabilidade.
- Senso de Urgência.

## Benefícios

- Auxílio Home Office - R$ 350,00.

## Contratação

- PJ - De 4.5 mil até 5.5 mil

## Como se candidatar

Aplique para a vaga [por aqui](https://www.careers-page.com/novare-rh/job/39YV7V) .

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
