### ISSUE TITLE
[Parcialmente Remoto / Salvador, Bahia, Brazil] Frontend Developer (Pleno) na Credifit SCD

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#4965]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-developer-165929271?origin=github&modal=open) com o pop-up personalizado de candidatura. 👋
<h3><strong>Nossa Stack Frontend</strong></h3>
<ul>
<li>Typescript</li>
<li>React com Mobx</li>
<li>Sass</li>
<li>Webpack</li>
<li>Cypress (Testes e2e)</li>
<li>Jest (Testes unitários)</li>
</ul>
<p></p>
<h3><strong>RESPONSABILIDADES E ATRIBUIÇÕES</strong></h3>
<ul>
<li>Participar ativamente das etapas de ideação, planejamento e desenvolvimento dos nossos produtos</li>
<li>Participar de discussão das tecnologias que serão utilizadas / incorporadas nos projetos</li>
<li>Desenvolvimento de aplicações web responsivas com React.js, consumindo web services</li>
<li>Deploy com CI/CD (Continuous Integration / Continuous Deployment)</li>
<li>Ser curioso e estar disposto a se arriscar em novas tecnologias</li>
<li>Disposição para ajudar e compartilhar conhecimento</li>
<li>Pensar / desenhar telas com o auxílio de alguma ferramenta como Zeplin ou Figma, por exemplo</li>
</ul>
<p></p>

## Credifit SCD: 
 <p>A Credifit é uma FinTech do tipo SCD - Sociedade de Crédito Direto. Isto significa que somos uma Instituição Financeira regulada pelo Banco Central, e por isso, não precisamos de intermediários para fazer nossas operações de crédito. Temos o coração Tech e já nascemos com a metodologia ágil no sangue. Queremos mais que desenvolvedores, e sim pessoas que façam parte do nosso negócio, e conheçam sobre as áreas da empresa. Estamos aqui para crescer!</p>
</p>

 ## Habilidades: 
 - Javascript 
- React.js 
- Typescript 
- GIT 
- Sass/Less 
- Webpack
## Local: 
 Salvador, Bahia, Brazil
## Requisitos: 
 - Experiência com React 
- Proficiência em Javascript (ES6+) 
- Proficiência em HTML e CSS 
- Conhecimento em Typescript 
- Conhecimento em versionamento com Git 
- Experiência fazendo interfaces de usuário complexas para a Web 
- Experiência profissional mínima de 2 anos (não necessariamente usando as tecnologias supracidadas)
**Diferenciais:** 
 - Experiência com testes automatizados no frontend 
- Bom domínio em lógica de programação e algorítimos 
- Experiência com back-end, Node em especial 
- Habilidades em padrões de design de interface e experiência de usuário 
- Conhecimento em pré-processadores de CSS (Sass, Stylus, Less, etc) ou CSS in JS (styled-components, emotion, etc) 
- Residir ou ter fácil acesso a Salvador/BA
## Benefícios: 
 - Conta Udemy 
- Flexibilidade de horários 
- Possibilidade de home office ou "flex office" 
- Capacitações quinzenais com a Credifit Academia (Temas abertos)
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Developer (Pleno) na Credifit SCD](https://coodesh.com/vagas/frontend-developer-165929271?origin=github&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção <b>Pedir Feedback</b> entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa <b>Recruiter</b> responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Regime
PJ
#### Nível
Pleno
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
