### ISSUE TITLE
[Remoto] Front-end Developer na BR Media Group

### ISSUE THREAD

**Issue by breim** [frontendbr/vagas#4967]
## Nossa empresa

A BR Media Group é uma consultoria líder no Brasil em Influencer Marketing. Criamos, planejamos e executamos campanhas com influenciadores digitais.

## Descrição da vaga

Você irá atuar em uma plataforma de gerenciamento de campanhas para micro influenciadores.

## Local

Remoto

## Requisitos
**Obrigatórios:**
- React / React Native (TypeScript, Redux, Context API, Styled Components)
- Experiência em consumo de APIs
- Conhecimento em TDD e CI/CD

**Diferenciais:**
- Vuejs
- Nextjs
- Nodejs
- Docker

## Benefícios

- Bônus em cima do faturamento

## Contratação

- PJ
- Salário: R$ 9.000,00

## Como se candidatar

Por favor envie um email para tecnologia@br-mediagroup.com  com seu CV anexado - enviar no assunto: Vaga Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: tecnologia@br-mediagroup.com 

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
