### ISSUE TITLE
[São Paulo - SP] Front-end - Vuejs @hagloo

### ISSUE THREAD

**Issue by giovaniPoletohagloo** [frontendbr/vagas#4968]
Resumo das atividades: 
● Desenvolvimento de novas funcionalidades e manutenção de sistemas web existentes utilizando Vue.js; 
● Especificação e criação de novos sistemas utilizando Vue.js / React alinhado a boas práticas de desenvolvimento de software; 
● Levantamento de novos requisitos junto à equipe de desenvolvimento (utilizando metodologias ágeis). 

Conhecimentos desejáveis:  
● Experiência com Vue e React, sendo o Vue prioritário;
● Javascript, HTML e CSS; 
● Experiência em desenvolvimento web utilizando frameworks Javascript (Vue.js / React); 
● Padrões de projeto e boas práticas de programação; 
● GIT; 
● Noções de UX/UI; 
● Gostar de aprender e compartilhar conhecimento.

Diferenciais: 
● Ter experiência com componentes de gráficos interativos (plotar gráficos);
● Desenvolvimento de sites responsivos; 
● Experiência com mercado imobiliário e/ou crédito; 
● Experiência com Code Review; 
● UX/UI. 

Cursos / Formação (Superior ou Técnico): 
Sistemas para Internet, Ciência da Computação, Sistemas de Informação, Engenharia da Computação, e áreas relacionadas. 

Sobre a vaga:
● Zona Sul - SP;
● Regime: PJ;
● Acesso a plataforma de cursos online e eventos de tecnologia;
● Parceria com o Sesc;
● Trabalho remoto e presencial;
● Café da manhã na empresa.
 
CVs via rh@hagloo.com

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
