### ISSUE TITLE
[São Paulo] Front-End Developer Sênior na FIND HR

### ISSUE THREAD

**Issue by Natassiaperez** [frontendbr/vagas#497]
## Descrição da vaga

•	Esse profissional irá Desenhar, codificar, integrar e manter a aplicação Front End (NodeJS, React e Redux); 
•	Realizar Testes unitários e metodologias de testes;
•	Bons conhecimentos em sistemas de controle de versão (GIT, por exemplo);
•	Web Services (REST, SOAP);
•	Melhores práticas de desenvolvimento, como Design Patterns;
•	Metodologias ágeis (Scrum, Kanban, XP).
Inglês Avançado é muito importante! ;) 

## Local

Escritório -, São Paulo - Centro/Próximo Avenida Paulista

## Benefícios

- VT
- Estacionamento
- VR de R$23,00 
- AM
- AO
- R$65,00 Mês (para consumo dentro da empresa)

#### Diferenciais

- Clima de Startup  
- código de vestimenta flexível
- frigobar sempre cheio :P
- horário flexível
- Happy Hour todas as sextas-feiras. 
- Desconto na compra de Vinhos

**Diferenciais:**
- Conhecimento sobre mecanismos concorrentes e paralelos, como arquiteturas reativas, multithreading e programação assíncrona
- Experiência anterior em empresas de varejo/e-commerce.

## Contratação

CLT 

## Nossa empresa

- A companhia possui uma cultura predominante de Startup e bastante profissionalizada;
- A área é valorizada e a existência da política de portas abertas facilita o trabalho e interações;
- O reporte da posição é o CTO, que possui um perfil de liderança, ownership, team spirit, hands-on e participativo.

## Como se candidatar

Por favor envie um email para nperez@findhr.com.br com seu CV anexado - enviar no assunto: Fron-End Developer

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
