### ISSUE TITLE
[São Paulo] Front-End Developer- Angular na Leega Consultoria e Informática

### ISSUE THREAD

**Issue by Frederico-TMonteiro** [frontendbr/vagas#4973]
> Vaga Remota durante a pandemia

## Nossa empresa

A Leega é uma empresa focada no atendimento eficiente e inovador em seus clientes. 
Isso não poderia ser diferente com o nosso principal combustível: as pessoas!  
Nossa cultura é inspiradora e nossos valores estão presentes no dia a dia: ética e transparência, excelência de qualidade, trabalho em equipe, responsabilidade econômica, social e ambiental, relações humanas e credibilidade.
Buscamos profissionais inovadores que sejam movidos por desafios e focados em resultados.
Se você busca uma empresa dinâmica e parceira e que investe em seus colaboradores através de capacitação constante, a Leega é o lugar para você!
Ficaremos muito felizes em ter você em nosso time. Venha fazer parte da nossa história e da construção do nosso futuro. 
Cadastre-se agora mesmo em nossas vagas!

## Descrição da vaga

Será responsável pela manutenção e desenvolvimento de novas funcionalidades em uma aplicação de gerenciamento de campanhas.
Sugestões de melhorias e otimização de código e interface de navegação/experiência do usuário;
Servidor Compute Engine no ambiente GCP.
Desejável conhecimento em docker

## Local

Remoto com possibilidade de atendimentos presenciais

## Requisitos

**Obrigatórios:**
- Experiência em Angular;
- Experiência com CloudSQL - MySQL;
- Boa organização;
- Perfil proativo e entusiasta de inovação.

**Desejáveis:**
- Conhecimento em Docker e microsserviços;
- Noções de UX e UI;
- Padrões de projeto e boas práticas de programação;
- GIT;

**Diferenciais:**
- UX/UI.
- Desenvolvimento de sites responsivos;

## Contratação

CLT ou PJ

## Como se candidatar

Cadastre-se através do site https://leega.gupy.io/jobs/902246

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
