### ISSUE TITLE
[lisboa] Front-end Developer na Integer Consulting

### ISSUE THREAD

**Issue by AlexandreCarvalho19** [frontendbr/vagas#4978]
> Vaga Remota durante a pandemia

## Nossa empresa

Exemplo: Aqui na Corporação ACME somos líderes em...

## A INTEGER, uma empresa de consultoria na área das tecnologias, com mais de uma década de presença no mercado português, está à procura um Senior Frontend Developer com fortes habilidades de comunicação, sentido de responsabilidade e trabalho em equipa.

Exemplo: Remoto ou Escritório,], [Lisboa ou Porto], 

## Requisitos
   Mínimo 5 anos de experiência em desenvolvimento de software para sistemas embebidos.
   Conhecimentos sólidos de C, C++ e/ou Ada.
   Experiência em áreas de negócio como espaço, aeronáutica, transportes e/ou defesa.
   Inglês é requisito eliminatório.

## Como se candidatar

Se tens o amazINg talent pretendido e queres fazer parte da equipa INTEGER, responde a este anúncio com o teu CV atualizado para alexandre.carvalho@integer.pt

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
