### ISSUE TITLE
(Curitiba) - Front-End Developer - LEADS2B - Alocado

### ISSUE THREAD

**Issue by jeffersonllopes** [frontendbr/vagas#498]
## Descrição da vaga

Esse profissional irá Desenhar, codificar, integrar e manter a aplicação Front End

## Local

Alocado - Curitiba - Bairro Bigorrilho

## Benefícios

- Seguro de vida
- VR de R$ 16,50/dia

#### Diferenciais

- 1 horas de almoço
- ambiente descontraído
- somos uma startup com forte crescimento.

## Requisitos

**Obrigatórios:**
- Conhecimentos avançados em Javascript (preferencialmente ECMAScript 6), Bootstrap

**Desejáveis:**
- Bons conhecimentos em sistemas de controle de versão (GIT)

**Diferenciais:**
- conhecimento em VueJS

## Contratação

- Alocado 
- a combinar

## Nossa empresa
- A Leads2B é uma empresa de Tecnologia em fase expansão, em que você encontra uma plataforma de alta captação de contatos, que permite incorporar novos negócios para área comercial dos mais diversos segmentos.

- Se você possui perfil dinâmico e tem vontade de possuir uma carreira de sucesso. Venha e faça parte de nossa Equipe! 

## Como se candidatar

Por favor envie um email para vagas@leads2b.com - com seu CV anexado - enviar no assunto: Front-End Developer

**Comment by raloliver** [comment]
🔝

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
