### ISSUE TITLE
[São Paulo] Front-end Developer na Poussée Marketing Digital

### ISSUE THREAD

**Issue by poussee** [frontendbr/vagas#4980]
> Vaga Remota durante a pandemia

## Nossa empresa

Somos uma agência de marketing full service ousada e disruptiva, com foco em pessoas e resultados. Nosso objetivo é atuar no crescimento de marcas por meio de uma metodologia própria de alta performance e com time multidisciplinar. Criamos estratégias inovadoras on-line e offline para solucionar os problemas de comunicação de nossos clientes, sempre com empatia, criatividade, conhecimento e proatividade.

Somos especialistas em E-commerce, WebSite de Alta Performance, Branding, Social Media, Inbound Marketing, Vídeo Marketing e Campanhas Patrocinadas.

## Descrição da vaga

Procuramos um parceiro(a) profissional com experiência em desenvolvimento Front End que seja dedicado(a) e proativo(a) para trabalhar com web, e que tenha vontade de crescer na carreira.

O(a) colaborador(a) será focado(a) no desenvolvimento em WordPress, Bootstrap e HTML e precisa ter noções de hospedagem para realização de backups e procedimentos de implementação junto ao servidor.

## Local

Durante o período de pandemia o trabalho irá acontecer em homeoffice.

## Requisitos

**Obrigatórios:**
- Experiência como desenvolvedor(a) web;
- Experiência e ótimos conhecimentos em WordPress;
- Conhecimentos em HTML5, CSS3, JavaScript, PHP e Bootstrap;
- Conhecimentos em Marketing Digital e principalmente em SEO;
- Experiência no tratamento de imagens para web,
- Comprometimento com prazos.

**Desejáveis:**
- Experiência como desenvolvedor(a) web;
- Experiência e ótimos conhecimentos em WordPress;
- Conhecimentos em HTML5, CSS3, JavaScript, PHP e Bootstrap;
- Conhecimentos em Marketing Digital e principalmente em SEO;
- Experiência anterior em agências de marketing digital;
- Noções de PHP;
- Proatividade na resolução de problemas;
- Noções de experiência do usuário (UX);
- Integração com APIs do Facebook, Google Maps, Instagram, LinkedIn, RD Station, entre outras;
- Google Tag Manager,
- Google Search Console.

## Benefícios

- Vt

## Contratação

PJ a combinar

## Como se candidatar

Achou essa vaga a sua cara? Então manda um e-mail com o seu currículo para nós em: vinicius@poussee.com.br

Lembre-se de colocar no assunto do e-mail: Vaga para Front End junto com o seu nome. 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dia após cada processo.
E-mail para contato em caso de não haver resposta: vinicius@poussee.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
