### ISSUE TITLE
[Joinville] Front-end Developer na weKnow

### ISSUE THREAD

**Issue by Emmelimp** [frontendbr/vagas#4987]
## Nossa empresa

Somos a primeira healthtech brasileira que desenvolve soluções de inteligência de negócios de forma simples, ágil e acessível.

## Descrição da vaga
Buscamos profissional para atuar no desenvolvimento de aplicações web. Seu desafio será, junto ao time, melhorar as propostas atuais e evoluir os projetos.
Esperamos o uso das melhores técnicas visando a agilidade e qualidade nas aplicações.

## Local

Remoto

## Requisitos

**Obrigatórios:**
– Experiência de 2 anos com desenvolvimento de aplicações para web;
– Experiência com Angular2+ e  JavaScript avançado (OO, Modules, Async).

**Desejáveis:**
– Experiência com AngularJs e Typescrip;
– Experiência com análise e prototipação de aplicações.

**Diferenciais:**
– Ambiente moderno que proporciona crescimento e aprendizado constante.

## Benefícios
– Programa de bônus conforme atingimento de metas
– Regime de contratação via Cooperativa
- Seguro de vida
- Vale refeição ou alimentação

## Contratação

Cooperado

## Como se candidatar

Por favor envie um email para emeli.pavanello@weknowbi.com.br com seu CV anexado - enviar no assunto: Front-end Developer na weKnow

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@weknowbi.com.br

#### Alocação
- Remoto

#### Regime
- Cooperado

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
