### ISSUE TITLE
[Remoto] Desenvolvedor Front-end Angular na Worthix Corp

### ISSUE THREAD

**Issue by NerdProgramador-com-br** [frontendbr/vagas#4988]
## Descrição da vaga 
Porque escolher a Worthix?

Na Worthix, estamos redefinindo o mercado da Análise Experiência do Cliente. 

Construímos a primeira ferramenta de medição de decisão do cliente do mundo com tecnologia de IA e fornecida em um aplicativo de software simplificado. 

Nascemos no Vale do Silício, e somos uma startup de tecnologia sediada em Atlanta que está crescendo rapidamente no mercado norte-americano, e já atuamos na america central e do sul, europa e asia e temos uma equipe incrível !!!

  

O que você precisa para se candidatar?

HTML5e CSS3;

Monorepositório utilizando NX;

Conhecimento em processadores de estilo (LESS, SASS, SCSS);

Experiência em Javascript moderno (ES6+) de 3 anos ou mais.

Typescript;

Experiência em Node.js;

Experiência em Angular2+;

Experiencia NGRX ou alguma biblioteca de gerenciamento de estado;

Experiência com controle de versão Git;

Experiênciaem integrações de API Rest via Json;

Experiênciaem RxJS;

Experiênciacom testes.

  

Desejáveis: 

  

Criação de gráficos utilizando D3.js;

Jest;

Cypress;

  

Forma de contratação

\- PJ / Home Office
## Salário 
R$11000 - R$14000 
## Local 
REMOTO 
## Como se candidatar 
Accesse a [Vaga de Desenvolvedor Front-end Angular](https://vaga.contratar.dev/apply/full/48a6887b-5734-4297-b07f-37358b3afe19) para se candidatar. 
## Labels 
* Remoto 
* Javascript 
* Angular 
* SCSS 
* CSS 
* Rest 
* TypeScript 
* HTML 
* Git 
## Sobre a contratar.dev 
A contratar.dev é uma plataforma de recrutamento e seleção automatizada de Desenvolvedores. Ao se candidatar a uma vaga da contratar.dev, você estará participando automaticamente de dezenas de processos seletivos para vagas similares, aumentando em MUITO as suas chances de mudar de vida 😉

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
