### ISSUE TITLE
(Curitiba) - Full Stack Web Developer - LEADS2B - Alocado

### ISSUE THREAD

**Issue by jeffersonllopes** [frontendbr/vagas#499]
## Local

Alocado - Curitiba - Bairro Bigorrilho

## Benefícios

- Seguro de vida
- VR de R$ 16,50/dia

#### Diferenciais

- 1 horas de almoço
- ambiente descontraído
- ambiente de startup com forte crescimento

## Requisitos

**Obrigatórios:**
- conhecimentos em PHP (Codeigniter, Lavarel)
- conhecimentos avançados em Javascript (preferencialmente ECMAScript 6), Bootstrap
- conhecimentos em desenvolvimento de APIs Restfull
- bons conhecimentos em sistemas de controle de versão (GIT)
Desejável conhecimento em VueJS, Python, Node.js

**Desejáveis:**
-Desejável conhecimento em VueJS, Python, Node.js-

## Contratação

a combinar

## Nossa empresa

A Leads2B é uma empresa de Tecnologia em fase expansão, em que você encontra uma plataforma de alta captação de contatos, que permite incorporar novos negócios para área comercial dos mais diversos segmentos.
Se você possui perfil dinâmico e tem vontade de possuir uma carreira de sucesso. Venha e faça parte de nossa Equipe! 

## Como se candidatar

Por favor envie um email para vagas@leads2b.com com seu CV anexado - enviar no assunto: Full Stack Web Developer

**Comment by kivervinicius** [comment]
A vaga é para Curitiba mesmo ou São Paulo? favor corrigir o enunciado.

**Comment by jeffersonllopes** [comment]
É para Curitiba, no enunciado e no descritivo da vaga tem esta informação.

Att

Jefferson Lopes

Enviado via iPhone

Em 23 de ago de 2017, às 16:12, Kiver Teixeira <notifications@github.com<mailto:notifications@github.com>> escreveu:


A vaga é para Curitiba mesmo ou São Paulo? favor corrigir o enunciado.

**Comment by jeffersonllopes** [comment]
Corrigido!

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
