### ISSUE TITLE
[Remoto] Dev Fullstack .Net @ SISAND

### ISSUE THREAD

**Issue by NovareRH** [frontendbr/vagas#4994]
## Nossa empresa

A SISAND desenvolve soluções para gestão de concessionárias, descomplicando o controle do negócio de ponta a ponta.

Fundada em 2005, a Sisand nasceu com a união de profissionais com experiência no ramo automotivo e amplo conhecimento na área de tecnologia da informação. Ao longo destes anos vem oferecendo ao mercado excelentes soluções de gestão para concessionárias de moto e carro.

## Descrição da vaga

- Planejar, analisar a implementar um sistema ERP
- Entender o negócio da Sisand
- Descrever as histórias
- Desenvolvimento do sistema
- Montagem de componentes
- Trabalhar dentro da ética e da metodologia Scrum.
- Ser colaborativo para o desenvolvimento de todos.
- Buscar cooperar com propósito de levar melhorias para o sistema.

## Local

[REMOTO]

## Requisitos

**Obrigatórios:**

- Front - Angular 7.0 ou superior, Bootstrap,CSS e HTML
- Back - C# (.NET core)
- Banco de Dados - Conhecimento SQL e modelagem de dados  
- Ensino Médio Completo com cursos especializados em tecnologia ou Ensino Superior em formações ligadas a tecnologia. 

**Diferenciais:**
- Vontade de aprender, 
- Ter afinidade e curiosidade com as tecnologias da vaga, 
- Ser autodidata,
- Experiência prática mínima de 6 meses com desenvolvimento em Angular e .Net ,
- Estudar, estudar e estudar,
- Comprometimento,
- Honestidade,
- Senso de urgência

## Benefícios

- Plano de Saúde
- VR ou VA - R$ 17,00 ao dia

## Contratação

- PJ ou CLT - De 2.5 mil até 3.5 mil

## Como se candidatar

Aplique para a vaga [por aqui](https://www.careers-page.com/novare-rh/job/W997RW) .

#### Alocação
- Remoto

#### Regime
- PJ
- CLT

#### Nível
- Júnior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
