### ISSUE TITLE
[Sao Paulo] Sr Mobile Developer - Java

### ISSUE THREAD

**Issue by rturk** [frontendbr/vagas#50]
## Descrição da vaga

We are looking for Software Development Engineers that thrive in fast-paced environments and are passionate about working with pre-market technologies. Successful candidates will be much more than just developers, they will bring with them deep technical fundamentals, experience with complex mobile, distributed systems, and a well-rounded software engineering background that spans disciplines.

We are looking for a Sr. Developer for our upcoming Mobile App. This is part of our international expansion plan.
## Location

Escritório, São Paulo - Zona Sul
http://plug.co/bkln
## Perks
- Cool working place
- Open schedule. Just deliver your code and you're done
- Based in São Paulo - Zona Sul
## Mandatory Qualifications
- BA/BS in Computer Science or related discipline, or equivalent work experience.
- Strong skill in Java programming.
- 5+ years of software development experience
- Fluent in English 
## Expected qualifications
- Comfortable in fast-paced, start-up like development environments.
- Experience in software development on devices/products in real-time operation system.
## Contratação

Full time employee
## About us

Entria (https://www.entria.com.br) is a leading Mobile Provider. We make really cool apps
We manage complex projects, and yes we deliver.
## How to apply for this job

Just drop us a note at rh@entria.com.br please attach CV our link to github projects, previous projects

**Comment by Mendrone** [comment]
@rturk a vaga foi preenchida?

**Comment by eduardojmatos** [comment]
@rturk já foi preenchida?

**Comment by rturk** [comment]
Caros Vou fechar por hora! Mas estamos sempre contratando

**Comment by camilatigre** [comment]
@rturk 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
