### ISSUE TITLE
[São Paulo] Front-End Developer (EMBER) na Peerdustry

### ISSUE THREAD

**Issue by kavalcante** [frontendbr/vagas#500]
## Descrição da vaga

Ao se juntar à equipe você será responsável por aprimorar um produto que já roda em caráter protótipo. Nossa stack de prototipação é formada por Ember.js no front e o incrível Firebase do Google.

## Local

Escritório, São Paulo - Santa Cecília

## Benefícios

- VT
- VR

#### Diferenciais

Queremos formar um time comprometido, temos alta flexibilidade em horários e um ambiente de trabalho descontraído e informal. Passamos por um momento de aceleração interessante aqui na Peerdustry (recém captamos investimento \o/) e nossos "early employees" já estão se beneficiando disso através de contratos de "vesting" que garantem ações da empresa (e consequentemente participação nos lucros) a funcionários engajados.

## Requisitos

**Obrigatórios:**
- Conhecimento do framework de Javascript Ember
- Forte base de Javascript
- HTML e CSS

**Desejáveis:**
- Testes
- Firebase e bancos NoSQL

**Diferenciais:**
- projetos opensource
- curso do Daciuk

## Contratação

CLT ou PJ a combinar

## Nossa empresa

A Peerdustry é uma Startup de Tecnologia que tem como missão aumentar a competitividade do setor industrial do Brasil, utilizando recursos avançados de tecnologia da informação e os princípios de economia compartilhada. Acreditamos no enorme potencial da criatividade, profissionalismo e inovação da Indústria Brasileira. Nossa visão é a de uma industria bem posicionada globalmente.

## Como se candidatar

Por favor envie um email para thiago@peerdustry.com com seu CV anexado - enviar no assunto: Vaga Ember

**Comment by LFeh** [comment]
```
Diferenciais:

- projetos opensource
- curso do Daciuk
```

HAHAHAHAHAHAHA, @fdaciuk

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by tpetrone** [comment]
Aberto

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
