### ISSUE TITLE
[Remoto] Javascript Engineer na Intellective

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#5006]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/javascript-engineer-184842589?origin=github&modal=open) com o pop-up personalizado de candidatura. 👋
<p>We are looking for JavaScript engineers to join our team and help shape the employee experience for some of the world’s most iconic brands.</p>
<p>&nbsp;</p>
<p>Must haves:</p>
<ul>
<li>Minimum 2 years of javascript development experience</li>
<li>Can do attitude</li>
<li>Proficiency in at least one of the these JavaScript frameworks (angular, angularjs, react or nativescript)</li>
<li>Strong programming basics</li>
<li>Strong HTML and CSS foundation</li>
<li>Attention to detail and design</li>
<li>Ability to problem solve and communicate effectively</li>
<li>Working knowledge of English language</li>
</ul>
<p>&nbsp;</p>
<p>What we offer:</p>
<ul>
<li>Learn from industry veterans and experts</li>
<li>Flexible location and schedule.  Working remotely from Brazil.&nbsp;</li>
<li>Computer to do the work</li>
<li>Opportunity to work with iconic brands and gain invaluable experience</li>
</ul>
<p>&nbsp;</p>
<p>Who we are:</p>
<p>Intellective is a 100% ServiceNow focused development studio. We help our clients make the most of your ServiceNow investment!  We develop tools that provide new capabilities for the ServiceNow platform and specialize in Employee Experience strategy and execution.</p>
<p>For more information visit https://intellective.co</p>

## Intellective: 
 <p>Intellective is a 100% ServiceNow focused development studio. We help our clients make the most of your ServiceNow investment!  We develop tools that provide new capabilities for the ServiceNow platform and specialize in Employee Experience strategy and execution.</p>
<p>For more information visit <a href="https://intellective.co" target="_blank">https://intellective.co</a>&nbsp;</p><a href='https://coodesh.com/empresas/intellective'>Veja mais no site</a>

 ## Habilidades: 
 - Angular.js 
- CSS 
- HTML 5 
- Javascript 
- React.js 
- Typescript 
- Angular 9 
- English
## Local: 
 100% Remoto
## Requisitos: 
 - Minimum 2 years of javascript development experience 
- Proficiency in at least one of the these JavaScript frameworks (angular, angularjs, react or nativescript) 
- Strong programming basics 
- Strong HTML and CSS foundation 
- Attention to detail and design 
- Ability to problem solve and communicate effectively 
- Working knowledge of English language

## Benefícios: 
 - Flexible location and schedule.  Working remotely from Brazil.  
- Learn from industry veterans and experts 
- Computer to do the work 
- Opportunity to work with iconic brands and gain invaluable experience
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Javascript Engineer na Intellective](https://coodesh.com/vagas/javascript-engineer-184842589?origin=github&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção <b>Pedir Feedback</b> entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa <b>Recruiter</b> responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Nível
Júnior
#### Categoria
Full-Stack

**Comment by garcia-art** [comment]
Júnior de no mínimo 2 anos?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
