### ISSUE TITLE
[Florianópolis] Frontend React Developer na CashWay

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#5007]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/react-200022422?origin=github&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong><em><ins>Cashway</ins></em></strong> é uma Techfin, e atua como uma plataforma para instituições financeiras e fintechs desenvolverem seus modelos de negócio.&nbsp;</p>
<p></p>
<p>Estamos em um momento de expansão, e por isso temos novas vagas disponíveis para <strong><em><ins>React Developer</ins></em></strong>.</p>
<p></p>
<p>Se você possui boa experiência com React, é um(a) profissional curioso(a), que está sempre em busca de novos aprendizados e tem senso analítico apurado para tomada de decisões, temos a oportunidade perfeita para você!</p>
<p></p>
<p><strong>RESPONSABILIDADES E ATRIBUIÇÕES</strong></p>
<ul>
<li>Trabalhar em equipe multidisciplinar, usando metodologia ágil para criação e evolução de produtos;</li>
<li>Escrever código limpo, reutilizável e de fácil manutenção;</li>
<li>Ajudar a definir e manter padrões de design e arquitetura dos sistemas;</li>
<li>Se responsabilizar pelo desenvolvimento, deploy, documentação e monitoramento dos sistemas;</li>
<li>Apoiar na integração entre sistemas dentro e fora da equipe, nas discussões de arquitetura e fazendo code review;</li>
<li>Levantamento de requisitos, pesquisa e provas de conceito;</li>
<li>Tomar decisões técnicas quando for preciso, envolvendo e alinhando equipe, clientes e stakeholders;</li>
<li>Atuar como mentor, colaborando com o aprendizado dos desenvolvedores jr.</li>
</ul>

## CashWay: 
 <p>Uma organização com sólida experiência no setor financeiro, que cria soluções inovadoras e customizadas para seus clientes, focada em agregar ainda mais valor para o seu negócio. Assim pode ser descrita a Cashway, uma empresa que transformou seu vasto conhecimento de mercado em soluções especializadas para atender as atuais necessidades de cooperativas rurais, sindicatos, cooperativas de crédito, financeiras, agroindústrias e associações em geral.</p>
</p>

 ## Habilidades: 
 - React.js 
- React Native
## Local: 
 Florianópolis
## Requisitos: 
 - Experiência com React; 
- Experiência no lifecycle completo de desenvolvimento de software; 
- Consciência da necessidade de testes unitários, de integração e aceitação; 
- Engajamento com o time de qualidade, UX/UI, design, arquitetura, devops 
- Espírito de trabalho em equipe, comprometimento e vontade de pôr a mão na massa; 
- Total disponibilidade em horário comercial;
**Diferenciais:** 
 - Experiência com arquitetura de micro-serviços e DDD; 
- Experiencia com desenvolvimento ágil; 
- Conhecimentos de segurança;
## Benefícios: 
 - Assistência médica 50% custeada pela empresa; 
- Vale Refeição; 
- Snacks e bebidas a vontade em nossa sede; 
- Bicicletário no prédio; 
- Sala de descompressão com vídeo-game; 
- Day-off de aniversário; 
- Ambiente descontraído e dinâmico; 
- Parcerias com descontos;
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend React Developer na CashWay](https://coodesh.com/vagas/react-200022422?origin=github&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção <b>Pedir Feedback</b> entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa <b>Recruiter</b> responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
