### ISSUE TITLE
[São Paulo] Front-End Developer na Gaivota Sistemas Inteligentes

### ISSUE THREAD

**Issue by mateusn** [frontendbr/vagas#501]
## Descrição da vaga

Ao se juntar ao time o desenvolvedor ficará responsável pelo desenvolvimento de um projeto em AngularJS e integração do REST API com o front-end. O mesmo também ficará responsável por visualizações utilizando pacotes gráficos como o D3js e utilização/integração de APIs como Google Earth Engine e mapbox.

## Local

Escritório São Paulo e/ou parcialmente remoto

#### Diferenciais

Temos total flexibilidade em horários e um ambiente de trabalho descontraído e flexibilidade de trabalho remoto.

## Requisitos

**Obrigatórios:**
- JavaScript
- AngularJS
- HTML
- CSS

**Desejáveis:**
- Inglês fluente
- Conhecimentos em Python

**Diferenciais:**
- Experiência com visualização de dados
- Experiência na área de desenvolvimento de apps, iOS e Android
- Experiência em React e React Native

## Contratação

PJ a combinar

## Nossa empresa

A Gaivota Sistemas Inteligentes é uma startup realizando data thinking, processamento de dados, e aplicando métodos de inteligência artificial em dados de clima, energia, agricultura, e meio-ambiente.

Fundada no Vale do Silício por um time de brasileiros, a Gaivota chegou recentemente ao Brasil. Mantemos fortes laços com Stanford University, PUC-Rio e Unicamp.

## Como se candidatar

Por favor envie um email para contato@gaivota.ai com seu CV anexado - enviar no assunto: [vaga-front-end]
Se possuir portfólio ou exemplo de projetos opensource, favor anexar.

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
