### ISSUE TITLE
[Remoto] Front-End Coder Warrior⚔ na Fhinck

### ISSUE THREAD

**Issue by michelzf** [frontendbr/vagas#5011]
### Sobre a Fhinck
Através de um software instalado nos computadores, Fhinck faz a leitura da experiência do usuário com a tecnologia utilizada para suas atividades no dia a dia. Quantificando tempos, cliques e navegação em tempo real. Usando modelagens estatísticas e ciência de dados identifica onde existem maiores oportunidades e ganhos para otimizar a operação aumentando a performance dos times e a eficiência operacional das atividades. Acesse [nosso site](https://fhinck.com/sobre-a-fhinck/) para conhecer mais sobre a empresa e os Fhinckers 😀 

### Descrição da vaga
O/A desenvolvedor(a) front-end é responsável pelo desenvolvimento de nosso dashboard, plataforma online em que nossos clientes realizam o acompanhamento de seus indicadores. Além de grande habilidade de desenvolvimento, o/a Desenvolvedor(a) Full Stack deve ter um grande conhecimento na área de design e usabilidade, para a criação de painéis de cadastro intuitivos para nossos clientes.

### Local
Remoto

### Contratação
PJ

### Requisitos
-Experiência em desenvolvimento no framework ReactJS.
-Experiência em desenvolvimento de páginas web, utilizando HTML5, CSS3 e Javascript.
-Experiência de uso da ferramenta Git.
-Inglês intermediário ou avançado.

### Diferenciais
-Experiência na biblioteca Redux.
-Experiência em desenvolvimento na linguagem NodeJS.
-Experiência em tecnologias serverless, como Cloud Functions, AWS Lambda ou Azure Functions.
-Experiência de uso da Google Cloud Platform.
-Experiência em SQL.
-Experiência com a metodologia Git Flow.

### Benefícios
- Plano de saúde.
- Plano odontológico.
- Jornada flexível.
- Home office periódico.
- Desconto em farmácia.

### Como se candidatar
Clicando [aqui](https://www.linkedin.com/jobs/view/2583169797/?capColoOverride=true)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
