### ISSUE TITLE
[Belo Horizonte] Front-end Developer na Base2 Tecnologia

### ISSUE THREAD

**Issue by hvbarros** [frontendbr/vagas#5012]
Vagas na Base2 Tecnologia (www.base2.com.br) - 03/06/2021

Belo Horizonte (MG) - Híbrido (parte em casa, parte na empresa)

Dev
- 2 Vagas de Desenvolvedor Angular  (com experiência mínima de 1 ano na função)
- 1 Vaga de Desenvolvedor React Native (com experiência mínima de 1 ano na função)

Todas nossas vagas são CLT com exceção das vagas de estágio.

Interessados devem se candidatar pelo link: vagas.base2.com.br

**Comment by moderacaofrontendbr** [comment]
@hvbarros por favor, coloque no nosso template.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
