### ISSUE TITLE
[Remoto] Frontend Coder Warrior na Fhinck

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#5013]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-coder-warrior-143048478?origin=github&modal=open) com o pop-up personalizado de candidatura. 👋
<p>O/A desenvolvedor(a) front end é responsável pelo desenvolvimento de nosso dashboard, plataforma online em que nossos clientes realizam o acompanhamento de seus indicadores. Além de grande habilidade de desenvolvimento, o/a Desenvolvedor(a)Front End deve ter um grande conhecimento na área de design e usabilidade, para a criação de painéis de cadastro intuitivos para nossos clientes.</p>

## Fhinck: 
 <p>A Fhinck é uma ferramenta para melhoria contínua de processos, analisa tempos e movimentos entre telas, entende o perfil das atividades que são realizadas, como o tempo é distribuído através da interação das pessoas com os sistemas que utiliza. Somos uma ferramenta para melhoria contínua de processos e não para monitorar funcionários. Esse é nosso website www.fhinck.com.</p>
</p>

 ## Habilidades: 
 - Firebase 
- HTML 5 
- React.js 
- GCP 
- Redux 
- Node.js 
- AWS/GCP
## Local: 
 100% Remoto
## Requisitos: 
 - ReactJS 
- HTML5 
- Firebase
**Diferenciais:** 
 - SQL 
- Git Flow 
- Scrum
## Benefícios: 
 - Horários Flexíveis 
- Plano odontológico 
- Plano de saúde 
- Desconto em farmácia 
- Home office periódico
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Coder Warrior na Fhinck](https://coodesh.com/vagas/frontend-coder-warrior-143048478?origin=github&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção <b>Pedir Feedback</b> entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa <b>Recruiter</b> responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Nível
Sênior
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
