### ISSUE TITLE
[Remoto] Front-end Developer na Domvs

### ISSUE THREAD

**Issue by thaisvilladal** [frontendbr/vagas#5015]
## Nossa empresa

Somos uma consultoria de TI focada em oferecer excelência aos nossos Clientes e desenvolvimento aos nossos Colaboradores, através de soluções, pessoas e processos pensados para cada necessidade de negócio. Buscamos e valorizamos as relações sólidas e a transparência nas ações como nosso maior patrimônio. 
Temos mais de 7 anos no mercado de TI, prezamos pelo engajamento, desenvolvimento e acolhimento das pessoas que trabalham em nosso time.
Buscamos profissionais com sede de tecnologia, que curta muuuito novos desafios e que seja apaixonado pelo que faz! 

## Descrição da vaga

Projeto de desenvolvimento de soluções de atendimento online (omnichanel), com diversos canais de atendimento. Será a construção do 0 de um Módulo Novo, nesse caso um módulo de atendimento de voz com tecnologias novas, para algo inovador. 
O modelo de arquitetura é um modelo atualizado, arquitetura do projeto em nuvem. 

## Local

Exemplo: Remoto 
Aceitamos candidatos de todo o Brasil

## Requisitos

**Obrigatórios:**
Vue js 
Javascript (ES6, ES7, ES8), Typescritpt, Bootstrap, HTML, CSS, SASS;
Conhecimento em gerenciamento de estado (Redux / Vuex);
Git;

**Desejáveis:**
Testes unitários.
Conhecimento com UX (Acessibilidade, otimizações de desempenho e tracking).
Cloud (cache, DNS, hospedagem de estáticos, CDN).

**Diferenciais:**
Será um plus se você conhecer React.

## Benefícios
Férias remuneradas

#### Diferenciais
Aqui você também vai encontrar:
Ambiente descontraído
Oportunidade de Job Rotation para outros projetos da Domvs
Horário flexível
Programa de recompensa para indicar aquele amigo fera como você.
Oportunidade de Crescimento Acelerado
Imersão em Ambiente 100% Ágil
Treinamentos Técnicos

## Contratação

PJ a combinar - remuneração em aberto

## Como se candidatar

Por favor envie um email para thais.villadal@domvs.com.br com seu CV anexado - enviar no assunto: Vaga FRONT INT

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após cada processo.
E-mail para contato em caso de não haver resposta: thais.villadal@domvs.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
