### ISSUE TITLE
[REMOTO] Desenvolvedor Front-End Angular na Rethink

### ISSUE THREAD

**Issue by PedroNankran** [frontendbr/vagas#5016]
## Nossa empresa
**Sobre a Rethink:** Somos especialistas em transformação digital e atendemos grandes empresas do Brasil e do exterior. Usamos a tecnologia, o design e a estratégia para criar produtos digitais que as pessoas amam usar. Como gostamos de criar soluções digitais inovadoras, nosso time é formado por pessoas curiosas, criativas, que adoram fazer a diferença.

## Breve descrição
**Desenvolvedor Front-End Angular na RETHINK**

## Descrição da vaga

**Suas principais responsabilidades**

- Analisar a viabilidade de demandas apresentadas pelos usuários a serem implementadas nos programas/sistemas existentes;
- Participar de reuniões técnicas e com usuários para análise e levantamento de requisitos;
- Desenvolver, testar e implantar programas e sistemas customizados;
- Providenciar a documentação funcional e técnica dos programas e sistemas customizados;
- Pesquisar, analisar, sugerir e contribuir na implementação de novas tecnologias associadas com aplicações corporativas;
- Projetar, construir e otimizar interfaces web.

## Requisitos

**Obrigatórios:**

- Possua excelente conhecimento técnico em JavaScript;
- Mínimo de 2 anos de experiência em desenvolvimento Angular;
- Experiência com SASS, CSS, HTML, NPM, Angular Material e Typescript;
- Experiência com ferramentas de versionamento de código e desenvolvimento colaborativo (ex.: GitHub, Bitbucket etc);
- Estar atualizado com as principais arquiteturas e boas práticas para desenvolvimento;
- Preocupar com a abstração de código, quebrando grandes módulos em componentes reutilizáveis;
- Gostar de trabalhar em equipe;
- Prezar por um código limpo e bem estruturado.

**Diferenciais:**

- Possuir inglês fluente;
- Conhecimento em testes unitários e testes de integração;
- Continuous Integration, Deployment em OpenShift e GCP;
- Conhecimento em UX;
- Deploys em Kubernetes, considerando monitoramento/observability (diferencial);
- Armazenamento diversificado: PostgreSQL, Oracle, Google Cloud DataStore.

## Benefícios

- Remuneração compatível com o seu nível de conhecimento;
- Ferramentas de apoio que facilitam o seu trabalho e a comunicação no dia-a-dia da empresa como Jira, Confluence, Discord, Git, AWS,...
- No Dress Code;
- Plano de saúde Bradesco;
- Excelente ambiente de trabalho;
- Treinamentos de desenvolvimento profissional;
- Office / Home Office.

## Contratação
CLT

## Como se candidatar
Por favor envie um email para vagas@rethink.dev com seu CV anexado - enviar no assunto: Desenvolvedor Front-end Angular
**Acesse pelo site:** https://secure.collage.co/jobs/rethink/22110

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
