### ISSUE TITLE
[Floripa] Front-End Developer na Chaordic

### ISSUE THREAD

**Issue by ailinalbertoni** [frontendbr/vagas#502]
## Descrição da vaga

Linx+Neemu+Chaordic uniram suas forças para mudar ainda mais o mundo do ecommerce e do varejo como um todo. Proporcionamos a cada usuário uma experiência única e personalizada no momento de fazer suas compras. Para isso, temos em mãos uma das maiores bases de dados de comportamento de compra online da América Latina, e a usamos para construir recomendações para milhões de pessoas que hoje navegam nos sites dos nossos clientes. o/

Então, você está procurando algo legal para fazer? Bom ... precisamos conversar!

Se você é aquele desenvolvedor que se interessa não só pelas linguagens da sua área, mas em sair do seu quadrado e gosta de trabalhar com integrações e serviços, bem... é por você que estamos procurando. 

Aqui estão alguns sinais de que teríamos um bom "match":

- Domínio de Javascript;
- Conhecimento de HTML e CSS;
- Conhecimento em PHP;
- Conhecimento em Git;
- Noções técnicas de inglês: A língua padrão de comunicação dentro do código é o inglês.

E aqui alguns pontos que seriam diferenciais:

- Conhecimento Node ou Python;
- Experiência com o padrão de arquitetura MVC;
- Escrever testes para validar o código;
- Já ter trabalhado com metodologias ágeis;
- Falar Inglês fluentemente.

Tá afim?

## Local

Lagoa da Conceição, Florianópolis - SC

## Benefícios

- Plano de saúde
- Plano odontológico
- Seguro de vida
- VR / VT
- Café da manhã
- Café da tarde (bolos, cucas, pao de queijo, etc..)

#### Diferenciais

- Horário Flexível
- Cozinha(bar) comunitária
- Happy hours frequentes dentro da própria sede (é bem legal aqui)
- Sede irada! Dá uma espiada nas [fotos](http://bit.ly/2u9238I), e fica na Lagoa da Conceição em Floripa, vê as [fotos](http://bit.ly/2u94eJp) tb . ;) 

## Requisitos

**Obrigatório:**
- Pelo menos 5 anos de experiência com JavaScript, HTML e CSS

**Desejável:**
- Experiência com PHP, Node ou Python

## Contratação

CLT

## Nossa empresa

[http://www.chaordic.com.br](http://www.chaordic.com.br)

## Como se candidatar

[https://linxneemuchaordic.recruiterbox.com/jobs/fk0mt82/](https://linxneemuchaordic.recruiterbox.com/jobs/fk0mt82/)

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by ailinalbertoni** [comment]
Sim Felipe! Aguardamos tua inscrição  =]

Em 23 de jan de 2018 14:07, "Felipe Fialho" <notifications@github.com>
escreveu:

Aberto ainda?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/frontendbr/vagas/issues/502#issuecomment-359839713>,
or mute
the thread

**Comment by LFeh** [comment]
Só to fazendo a auditoria, hehe, valeu 👊

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
