### ISSUE TITLE
[Remoto] Frontend ReactJs Developer na Mobiplus

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#5020]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/fullstack-developer-foco-frontend-165441960?origin=github&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A MobiPlus está buscando pessoa desenvovedora <strong>Fullstack com foco frontend react.js</strong> em nível sênior para compor sua equipe.</p>
<p><strong>Nosso caminho passa por: </strong>Pessoas, Felicidade e Satisfação pessoal e profissional, Excelência, Ética, Transparência e Negócios. Respeitando esta ordem.</p>
<p>Investidores e grandes empreendedores dizem que uma das coisas mais importantes nas startups é o TIME. Então nós decidimos começar pelo TIME.&nbsp;</p>
<p>Nascemos para mudar o status quo de como se criam empresas de sucesso!</p>
<p><strong>O que nosso time técnico domina: </strong>Android e iOS nativo, React Native, Flutter, React.js, Vue.js, Typescript, Angular, Node.js, Golang, Java, Firebase, AWS, Testes, Testes, Testes e o principal, desenvolvimento de produtos.</p>
<p><strong>Fora tecnologia, acreditamos em:</strong> Agilidade, MVP, User Discovery, Product Discovery, Negócios de sucesso com vida saudável, Equipes de alta performance.</p>

## Mobiplus: 
 <p>A Mobiplus nasce em 2017 com uma ideia bem clara: prestar serviço de alta qualidade para viabilizar a montagem de um TIME de alta performance e, em um segundo momento, gerar resultados importantes para todos os envolvidos na empreitada, com produtização de serviços e desenvolvimento de produtos (SaaS).</p><p>Nosso caminho passa por: Pessoas, Felicidade e Satisfação pessoal e profissional, Excelência, Ética, Transparência e Negócios. Respeitando esta ordem.</p><a href='https://coodesh.com/empresas/mobiplus'>Veja mais no site</a>

 ## Habilidades: 
 - HTML 5 
- Javascript 
- React.js 
- Typescript 
- CSS 3 
- Node.js 
- SSR 
- SEO
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência mínima de 3 anos em colocação igual ou similar; 
- Domínio de React e testes unitários; 
- Conhecimento em SEO e SSR 
- Sólidos conhecimentos em HTML5, CSS3, JavaScript
**Diferenciais:** 
 - Desejável conhecimento em node.js e typescript
## Benefícios: 
 - Trabalho 100% remoto 
- Ambiente descontraído, colaborativo e extremamente desafiador 
- Horário flexível (limitações de janela de horário dependendo do contexto/cliente) 
- Possibilidade de trabalhar com um time de capacidade acima da média 
- Possibilidade de trafegar entre diferentes tecnologias e stacks 
- Contratação PJ com benefícios similares à CLT (Incluímos os benefícios no valor do salário PJ) 
- Possibilidade real de acordar todos os dias para construir algo seu de verdade  
- Stock Options (médio prazo)
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend / Fullstack Developer na Mobiplus](https://coodesh.com/vagas/fullstack-developer-foco-frontend-165441960?origin=github&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção <b>Pedir Feedback</b> entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa <b>Recruiter</b> responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Nível
Sênior
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
