### ISSUE TITLE
[REMOTO] Front-end Developer Angular (freela) na 200 Systems

### ISSUE THREAD

**Issue by cmarqs** [frontendbr/vagas#5021]
> Freelance 100% remoto (terminar projeto iniciado)

## Nossa empresa

Sou um PJ (http://200.systems) e faço projetos freelance, mas meu parceiro está momentaneamente incapacitado (motivos de saúde) de seguir comigo no projeto, mas precisamos terminar, por isso estou buscando alguém para me ajudar finalizar.

## Descrição da vaga

Projeto desenvolvido em Node (Backend) e Angular (Front). Estamos usando um template pronto re-desenvolvendo um sistema de registro de leis, empresas e planos de ação para ajudar empresas seguirem corretamente as leis, normas e requisitos legais e não serem autuadas em auditorias.

Você (interessado) fará o fronte e se possível backend (API Node express). Tem liberdade para tomar quaisquer decisões técnicas, o importante é o sistema funcionando para o cliente final. Meu papel no projeto é interface com o cliente. Faço as reuniões, levantamento e tiro qualquer dúvida (sua ou do cliente) e tenho que gerar relatórios de entrega e no final documentar tudo pra entrega (parte do contratado). 

Estamos em aproximadamente 80% prontos. Faltam as seguintes features:
- Cadastro de acompanhamento de auditoria: é uma tela CRUD com 6 campos. A cada edição neste formulário grava um histórico em uma grid com o nome do usuário, data e hora e um comentário.
- Cadastro de plano de ação: é uma tela CRUD com 4 ~ 6 campos para informar uma atividade a ser executada e indicado o responsável (nome, email) e a data limite para execução. Deve enviar e-mail ao responsável cadastrado.
- Cadastro de responsáveis: CRUD de pessoas (nome, email) associados a uma unidade (empresa) que receberá e-mails quando um determinado item no registro é alterado.
- Cadastro de usuários e acessos: CRUD de usuários para acesso ao sistema e associar o tipo de acesso (admin ou cliente). Se cliente, indicar qual. Usuários do tipo cliente, só tem acesso a registros da própria empresa. Usuários do tipo admin, tem acesso a tudo.
- Relatório de logs: Lista das alteracoes que foram feitas em formulários.
- Dashboard: Tela com gráficos simples (barra, pizza) mostrando alguns contadores.

## Local

100% remoto. Estou no ABC (só por curiosidade).

## Requisitos

**Obrigatórios:**
- Boa experiência com Angular (não tem requisito mínimo em tempo, tem que saber fazer).

**Desejáveis:**
- Conhecimentos em NodeJs (Express)

**Diferenciais:**
- Experiência comprovada

## Benefícios

- Dinheiro na conta, não precisa emitir nota, faço depósito ou PIX direto.

## Contratação

Freelance (valor hora entre R$100 a R$120 a hora).

## Como se candidatar

Por favor envie um email para cleiton.marques@200.systems com seu contato, ou pode me chamar direto no telegram @c_marqs

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Pleno
- Sênior

**Comment by cmarqs** [comment]
Parceiro encontrado! lol

**Comment by cmarqs** [comment]
O parceiro não foi encontrado :(

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
