### ISSUE TITLE
[São Paulo] Front-end Developer na RaiaDrogasil

### ISSUE THREAD

**Issue by Monique-Tech-Recruiter** [frontendbr/vagas#5022]
Que tal fazer parte da maior empresa do varejo farmacêutico do país?
🚀A RaiaDrogasil está com uma oportunidade Incrível! 🚀

**Desenvolvedor(a) Front end | Sênior**

_Experiência necessária:_
- Mínimo de 5 anos atuando como desenvolvedor para camadas de Frontend
- Conhecimentos avançados sobre utilização de React, REDUX e SAGA
- Fluência na utilização dos verbos HTTP e consumo de API's
- Fluência na utilização de Typescript, Less CSS (variáveis e mixins)

_Principais Responsabilidades:_
- Atuar ativamente como principal desenvolvedor na camada de frontend, sugerir inovações e soluções apropriadas para o produto a ser desenvolvido, tanto para novas funcionalidades  como também dar sustentação em produtos já entregues.
-  Trabalhar de perto com os colegas backend, na definição dos formatos e modelo de dados na criação de API's, boa fluência na utilização dos verbos HTTP e consumo de API's, manter informados todos os envolvidos nos projetos em que atua, sobre novas necessidades ou mudanças de escopo, complexidade e prazos.
- Garantir a qualidade e performance de suas entregas por meio de processos e técnicas adequadas de análise desenvolvimento, identificar e sanar problemas técnicos assim como facilitar a transferência de conhecimento para com os colegas de menor senioridade (juniores e plenos).

**Horário:** Flexível
**Contratação:** CLT - 100% remoto durante a pandemia e modelo remoto ou híbrido pós pandemia
Nossa matriz está localizada no bairro do Butantã e temos um fretado da estação Butantã até a empresa e vice versa

**Benefícios:** assistência médica e odontológica, seguro de vida, gympass, clube de benefícios, PLR anual, univers (desconto em farmácias), ambulatório de atenção primária Clínica Einstein Conecta, refeitório no local, vale transporte ou estacionamento.

**Diferenciais:**  short friday, programa de acompanhamento a gestante, presente de casamento, presente de maternidade, programa minha melhor versão e universidade RD

- Você é apaixonado pelo o que faz?
- Busca sempre novos conhecimentos?
- Gosta de desafios?

Então, vem inovar com a gente! 
#vemserRD💚

**Para concorrer a vaga** envie o currículo com o título da posição para o número de whatsapp: (11) 94366-4107

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
