### ISSUE TITLE
[Remoto] React + Node.js Developer na BairesDev

### ISSUE THREAD

**Issue by rafael-novezero** [frontendbr/vagas#503]
## Descrição da vaga

Você será dono de uma porção do desenvolvimento de novos produtos e melhorias em produtos existentes. Você enfrentará diversos desafios e irá trabalhar com outros monstros do JS para resolver problemas de performance, interatividade e compatibilidade. Ao longo do trajeto, você também ajudará a melhorar a qualidade do código, irá conhecer e propor novas tecnologias, participar de code reviews com seus pares a converter “bagunças” em componentes modulares reutilizáveis.
Além de tudo isso, você também poderá participar de pet projects e propor soluções para problemas que nós nem sabemos que temos.

## Local

Remoto

## Benefícios

- Flex time (8h por dia que podem ser feitas dentro da janela de 8h - 20h, no fuso local)
- 2 semanas de férias pagas por ano
- Folga paga em feriados locais / nacionais

#### Diferenciais

- Trabalhar com um time talentoso de Designers e Engenheiros apaixonados por software
- Aprender e participar de outras disciplinas, como UX, design e desenvolvimento back-end
- Fazer a diferença em projetos realmente grandes
- Horário flexível
- Trabalho remotamente

## Requisitos

- 4+ anos de experiência em desenvolvimento de Front-End, com fortes skills em JavaScript (ES6/ES7), CSS3 e HTML5
- 1.5+ anos de experiência desenvolvendo aplicações usando React + Flux, Redux, Relay, etc.
- 2.5+ anos de experiência com Node.js
- Confortável com conceitos chave de programação e JavaScript
- Confortável usando browser debuggers, analisando código, e rastreando dados por toda a stack
- Habilidade para completar testes unitários com Jasmine ou similares
- Bom nível de inglês, para interagir com um time espalhado pelo mundo

## Contratação

- Contractor (similar a PJ)
- Long-term / tempo indeterminado

## Nossa empresa

BairesDev is an innovative technology services company that employs the Top 1% Talent in Latin America and specializes in Software Development, Software Outsourcing, Testing, Maintenance & IT Staff Augmentation solutions.

To find more information about BairesDev, please visit https://www.bairesdev.com/careers

## Como se candidatar

Por favor envie um email para rafael.silva@bairesdev.com com seu CV anexado.

**Comment by vinyguedess** [comment]
Mandei
