### ISSUE TITLE
[Remoto] Front-End Developer (ReactJS Angular) na Qintess

### ISSUE THREAD

**Issue by rtakara** [frontendbr/vagas#5032]
EMPRESA
Com 30 anos no mercado, somos uma multinacional brasileira entre as maiores integradoras de TI do Brasil.
Valorização dos talentos, seriedade, compromisso no atendimento aos clientes, agilidade e qualidade nos projetos são algumas das premissas que nos diferenciam.
São mais de 2000 clientes – grandes empresas nacionais e globais – que nos reconhecem pela excelência e inovação, o que só é possível pelo trabalho de uma equipe altamente qualificada e engajada. Reunimos diferentes programas de qualidade de vida e oportunidades de carreira, além de ações para proporcionar um ambiente de trabalho motivador e colaborativo, com incentivo à diversidade e à inovação. Tudo isso, baseado nos princípios ESG – Environmental, Social and Governance (em português: Ambiental, Social e de Governança), uma prática global que tem ganhado força no mundo dos negócios e que é composta por três fatores centrais que atuam na medição da sustentabilidade e do impacto social de uma empresa.
Mais de 3.500 profissionais altamente capacitados compõem a nossa equipe em mais de 151 cidades no Brasil e na América Latina. Estamos na era da mudança permanente e, nesse cenário, trabalhamos para suportar as empresas à alcançarem um novo patamar de desempenho e alavancarem à transformação digital.
Somos uma fonte de geração de ideias, que trabalha de forma colaborativa, que transforma pessoas e estas transformam o jeito de fazer negócios.

Para mais informações, acesse: www.qintess.com

DESCRIÇÃO DA VAGA
FrontEnd Developer - Angular e ReactJS

LOCAL
Home Office

BENEFÍCIOS
• Plano de saúde AMIL Apto
• Convênio Odontológico - AMIL DENTAL
• Seguro de vida
• Vale refeição
• Auxílio creche
• Convenio Farmácia

REQUISITOS
Obrigatórios

Linguagens: HTML, CSS, Javascript, React, Angular 4+
Webservices: SOAP e REST
Controle de Versão: Git, GitFlow
Testes Unitários
Design Patterns
Orientação à Objetos
Inglês técnico

Diferencial: Conhecer ferramentas/frameworks de testes automatizados
Sólidos conhecimentos em utilização de nuvem ( AWS, Azure, etc ). 
Integração Contínua
Portal CMS
Vtex IO

Como se candidatar
Por favor envie um email para roger.takara@qintess.com com seu CV anexado - enviar no assunto: [Front-End Developer (ReactJS Angular)] [Seu nome completo]

Contratação:
CLT

Nível:
Pleno
Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
