### ISSUE TITLE
[Remoto] Front-end Developer na Lyncas

### ISSUE THREAD

**Issue by jananessi** [frontendbr/vagas#5038]
## Nossa empresa

Trabalho em uma empresa de recrutamento humanizado que se chama HunterCo, possuímos várias vagas e consultores que acompanham os candidatos no recrutamento, auxiliando-o e dando feedback's.

## Descrição da vaga

Desenvolver novas funcionalidades do produto;
Dar manutenção em funcionalidades já existentes.

## Local

Remoto

## Requisitos

**Obrigatórios:**
-Experiência profissional com VueJS;
Experiência em CSS3 e HTML5;
Experiência em consumir API Rest;
Conhecimento básico em versionamento com GIT;
Criação de projeto que utilizem JavaScript;
Amplo entendimento e experiência com desenvolvimento web;
Conversação em inglês, habilidade de entender e se comunicar.

**Desejáveis:**
Conhecimento de Infra Google Cloud ou AWS;
Comprometimento com prazos e metas;
Buscar sempre inovar e melhorar processos já existentes;
Habilidade para escrever códigos limpos;

## Benefícios

Academia Lyncas
Acolhimento psicológico
Ambiente descontraído de trabalho
No-dress code
Bônus indicação
Horário flexível
Happy hour online

## Contratação

PJ ou CLT

## Como se candidatar

https://vagas.hunterco.com.br/job/609c69c682fd3d001dd8463a?c=4034

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.
E-mail para contato em caso de não haver resposta: janaina.nessi@parceirohunterco.com.br

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
