### ISSUE TITLE
[Remoto] Front-end Developer na @voxy

### ISSUE THREAD

**Issue by icaroseara** [frontendbr/vagas#5040]
## Nossa empresa

Voxy é uma empresa com sede na cidade de Nova York que está mudando a forma com que o mundo aprende inglês. Nossa tecnologia de personalização proprietária e parcerias exclusivas com produtores líderes de conteúdo nos possibilita fornecer uma solução única para mais de 2,5 milhões de alunos de inglês em todo o mundo. Nosso aplicativo para celular e aplicação web torna possível para qualquer pessoa aprenda com o mundo ao seu redor, transformando experiências e conteúdo do dia-a-dia em atividades divertidas e semelhantes a jogos.

## Descrição da vaga

- Você estará por trás da reestruturação da nossa Single Page Application para torná-la mais reativa, acessível e responsiva.
- Construir um framework inovador de jogos/atividades para engajar os estudantes de uma maneira cientificamente validada que aprimore a aprendizagem.
- Criar códigos bem estruturados que possam ser testados e implantados, incluindo A/B testing de novos recursos para eficácia e usabilidade.
- Nós somos globais! Por isso, nossa interface também precisa ser global. O front end é internacionalizado para estudantes com diferentes culturas, pontos de vista e métodos de aprendizagem de idiomas.
- Não ter medo de enfrentar um desafio ocasional de back end. 
- Colaborar com nosso designer de produto, engenheires de software e gerentes de produto para construir códigos bem estruturados, testáveis e que possam ser feitos deploy sem downtime. 
- Participar ativamente de code reviews, discussões e decisões de tecnologia e arquitetura de front end.
- Construir sistemas e componentes de front end de forma eficiente e reutilizável que permita aplicações complexas de front end.
- Compartilhar conhecimentos, difundir as melhores práticas e colaborar com pessoas desenvolvedoras incríveis.

## Local

Remoto.

## Requisitos

**Obrigatórios:**

- 5+ de experiência construindo serviços front end para a produção de aplicação web.
- Conhecimento das tecnologias e práticas de front end mais recentes, como: Vue, React e Angular.
- Curiosidade e conhecimento sobre tecnologias e padrões de arquitetura de engenharia de software em toda a stack com foco em front end (por exemplo: CSS, javascript, html5, etc.).
- Conhecimento e experiência na criação de testes unitários de acordo com as melhores práticas de testagem. 
- Experiência em trabalho com REST APIs para criar aplicações Single-page App em larga escala.
- Pragmatismo no entendimento de quando construir uma solução que se estende para 1 milhão de usuários ou que funciona para 100 usuários.

**Desejáveis:**

- Vue.js que é o framework oficial para o desenvolvimento de aplicações front end na Voxy. Mas, também temos algumas aplicações legadas com outros frameworks.
- Experiência em Python seria ótima para decifrar códigos de back end.
- Conhecimento em AWS também seria legal, mas sem problemas se você não possuir familiaridade.
- Bacharelado ou graduação superior em Ciência da Computação, Engenharias, ou alguma formação equivalente.

## Benefícios

- Plano de saúde
- VR de R$ 30/dia
- Salário competitivo e opção de compra de ações;
- Excelentes benefícios: plano de saúde, reembolso de fatura de celular e wifi, orçamento para gastos com home office e bem-estar, eventos de equipe;
- Política de trabalho remoto;
- Orçamento de desenvolvimento profissional;
- Aulas de idiomas;

**Diferenciais:**
- Experiência de trabalho com uma equipe internacional incrível, composta por indivíduos brilhantes, criativos, talentosos e apaixonados, baseados nos EUA e em todo o mundo.

## Contratação

CLT

## Como se candidatar
Link para candidatura: https://grnh.se/5b21e0d41us

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
