### ISSUE TITLE
[Remoto] Tech Lead / Desenvolvedor Front-end ReactJs na Softo

### ISSUE THREAD

**Issue by fseixas** [frontendbr/vagas#5044]
## Softo

Somos um atelier de desenvolvimento de software focado na criação de sistemas que geram valor para nossos clientes. Nossos valores são capacidade de pensar como o cliente, foco na geração de resultado acima da simples implementação de tecnologia de qualidade e espírito de parceria. Somos agnósticos de tecnologia e nossos pilares de atuação são (1) desenvolvimento de aplicações web, mobile e micro-serviços, (2) planejamento, operação e otimização de infraestrutura na nuvem - DevOps e (3) soluções baseadas em blockchain, smart contracts e DLT. http://sof.to

## Descrição da vaga

Estamos à procura de um tech lead / desenvolvedor front-end sênior em ReactJs, interessado em trabalhar na criação de sistemas web de alto desempenho e que tenha pelo menos 4 anos de experiência nesse framework e pelo 8 anos de experiência em desenvolvimento de software.

Você será responsável por desenvolver interfaces web a partir de especificações realizadas pelo time de design primariamente utilizando ReactJs mas também atendendo demandas de desenvolvimento e manutenção em sistemas desenvolvidos com React Native. Será responsável também por liderar tecnicamente times de desenvolvimento em front-end.

## Local

100% remoto

## Requisitos

**Obrigatórios:**
- Pelo menos 4 anos de experiência em ReactJs e pelo 8 anos de experiência em desenvolvimento de software em geral.
- Grande conhecimento em desenvolvimento ReactJs
- Habilidade para desenvolver em Typescript
- Experiência em desenvolvimento React Native
- Capacidade de escrever código limpo e bem documentado
- Conhecimento em Hooks, TDD, Clean Architecture, SOLID

**Desejáveis:**
- Experiência de desenvolvimento mobile em React Native
- Conhecimento em operação de sistemas em ambiente cloud
- Conhecimento de AWS

## Benefícios

- Curso de inglês gratuito (interno)
- Horário flexível de fato
- Programa de bonificação
- Programa de partnership

**Diferenciais:**
- Empresa orientada ao desenvolvimento das pessoas
- Empresa organizada e com forte senso de melhoria contínua
- Programa de feedback estruturado e implementado
- Cultura saudável com ambiente colaborativo e alegre
- Estrutura de trabalho inovadora baseada na metodologia ágil Fluxo Unificado

## Contratação

De R$9.000,00 a R$ 11.000,00 dependendo da experiência e senioridade, por contrato de prestação de serviço ou cooperativa.

## Como se candidatar

Enviar CV aqui: https://airtable.com/shruSfs2Ji2HNwzAT

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada etapa do processo de seleção.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
