### ISSUE TITLE
[Remoto] Front-End React Developer (Sênior) na Funnel Guard

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#5045]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-react-developer-senior-121613224?origin=github&modal=open) com o pop-up personalizado de candidatura. 👋
<p>FunnelGuard is looking for Senior Level <strong>Front-End React Developer</strong> to compose its globalized team!</p>
<p>We automatically map and monitor customers' marketing funnels to provide relevant, actionable, and up-to-the-minute information so they can identify and resolve issues that stop them from acquiring customers and waste marketing budget. You can think of us as Uptime Monitoring + Incident Response and Awareness for Marketers.&nbsp;</p>
<p>You will join a small, tightly-knit team as the fourth team member to help our customers excel in their digital marketing operations. Our focus is to combine several different types of digital experience monitoring into a turn-key service built for marketers.</p>
<p>As an engineer, you will work hand-in-hand with our team of product managers, designers, and software engineers. Together, we will develop and maintain the backend and front-end applications that power our services. We are looking for engineers who are not only excellent technically but also have a keen eye for UI and a proven track record in delivering delightful UX.</p>
<p><strong>Responsibilities:</strong></p>
<p>1. Own the software and systems you are responsible for: design, develop, test, deploy, monitor, and maintain&nbsp;</p>
<p>2. Build and maintain UI/UX for product features&nbsp;</p>
<p>3. Build and maintain re-usable UI component library&nbsp;</p>
<p>4. Provide UI/UX Design Feedback&nbsp;</p>
<p>5. Collaborate with Designers, Product Managers, and other Devs&nbsp;</p>
<p>6. Production incident response&nbsp;</p>
<p>7. Serve your customers - external and internal&nbsp;</p>
<p>8 .Embody best software engineering practices and mentor others in them: code and design reviews, simple and maintainable APIs, automation and testing&nbsp;</p>
<p>9. Manage individual/team project priorities, deadlines and deliverables&nbsp;</p>
<p>10. Interface with other teams to incorporate ideas and features to meet our customers' requirements and company goals</p>
<p></p>

## Funnel Guard: 
 <p>FunnelGuard is an automated turn-key monitoring solution that maps your conversion funnels, sets up monitors as quickly as you can create campaigns, and shows you the most important things you can do to improve your Brand Uptime and protect your bottom line.&nbsp;</p>
</p>

 ## Habilidades: 
 - React.js 
- Typescript 
- UI 
- UX 
- GraphQL 
- DDD (Domain Driven Design)
## Local: 
 100% Remoto
## Requisitos: 
 - Minimum 6/8 Years a Software Developer  
- Building reusable UI component libraries 
- Experience with React 
- 4 hour overlap with Pacific Timezone working hours (8am - 6pm PT) 
- Experience with Design Systems Experience 
- Minimum 2 Years  with Typescript  
- English for communication (Reading, writing and speaking) proficient
**Diferenciais:** 
 -  Fluent English
## Benefícios: 
 - Academy voucher 
-  Profit sharing 
- Scholarships 
-  Flexible Schedules 
- 100% Home Office 
- Possibility of working in a global team
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Front-End React Developer (Sênior) na Funnel Guard](https://coodesh.com/vagas/frontend-react-developer-senior-121613224?origin=github&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção <b>Pedir Feedback</b> entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa <b>Recruiter</b> responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Nível
Sênior
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
