### ISSUE TITLE
[São Paulo] Front-end Developer na Pronto Combustíveis

### ISSUE THREAD

**Issue by evandro-prontocombustiveis** [frontendbr/vagas#5047]
> Vaga Remota durante a pandemia

## Nossa empresa

Estamos construindo algo muito significante aqui no PRONTO. 
Podemos dizer que é **a primeira e maior plataforma do Brasil para cotações, implantação de pedidos, serviço de crédito e entrega de combustíveis para postos Bandeira Branca.**

Mas o que estamos fazendo aqui é maior que isso. Estamos causando uma grande disrupção no mercado de combustíveis do Brasil, aumentando a eficiência de vários elos da cadeira e levando prosperidade para todo o nosso ecossistema.

Vamos juntos construir essa história de sucesso! 🦄🚀🚀

Buscamos pessoas apaixonadas por criar soluções que resolvam problemas reais e que facilitam a vida de nossos clientes

## Descrição da vaga

- Escrever código limpo, de fácil manutenção, utilizando as melhores práticas de desenvolvimento de software;
- Apresentar melhorias nos sistemas existentes e garantir a qualidade nas entregas;
- Ajudar e compartilhar sua experiência com os membros da equipe.

## Local
Remoto

## Requisitos

**Obrigatórios:**
- React
- HTML/CSS/JS
- Typescript
- Node
- GraphQL
- Material UI

**Desejáveis:**
- Domínio de engenharia de software, princípios, boas práticas e padrões de arquitetura
- Experiência com métodos ágeis e times multidisciplinares
- Experiência em desenvolvimento de sistemas complexos, detectar oportunidades e soluções, resolver problemas do dia-a-dia
- Habilidade para conversar com a equipe de negócios e operacional
- Habilidade de trabalhar em equipe, alinhamento de trabalho, gestão de tarefas, divisão de trabalho
- Perfil empreendedor, "visão de dono"

## Benefícios
- Férias remunerada
- Subsidio de 50% do plano médico para o titular
- 13º salário

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para evandro.demuth@prontocombustiveis.com.br com seu CV anexado - enviar no assunto: Front-end Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: evandro.demuth@prontocombustiveis.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by Pedroabreu155** [comment]
enviei no email!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
