### ISSUE TITLE
[Berlim][Remoto] Front-end Developer at Tendermint

### ISSUE THREAD

**Issue by luciorubeens** [frontendbr/vagas#5052]
## Nossa empresa

Formed in 2014, Tendermint is the creator of Cosmos, an ecosystem of interoperable blockchains. We are a software engineering company that focuses on the Cosmos SDK and Starport, state-of-the-art frameworks for blockchain development. Over USD 100 billion worth of digital assets is secured by the 200+ blockchains built with the Cosmos SDK. 

## Descrição da vaga

This role is a full-time remote position, and you’re free to work from anywhere. Be advised that most team meetings occur between 8 am and 12 pm Pacific Time (UTC-8/-7).  If you're applying from a location where these hours are outside your usual working hours, we expect you to adapt to our meeting times.

## Local

Remote

## Requisitos

**Obrigatórios:**
- Exceptional proficiency in building websites in TypeScript using Vue 3, Nuxt, and VuePress. Working experience in client-side state management tools, specifically Vuex. Good understanding of a component-based architecture.
- Clear and concise written and oral English communication skills.

**Desejáveis:**
- Experience implementing visualizations and animations using webGL and Canvas-based libraries.
- A keen eye for visual and interaction details when translating designs (prototypes and mockups) to code – we use Figma for handoff.

**Diferenciais:**
- Experience using cryptocurrencies, crypto wallets, decentralized exchanges, lending protocols, etc.
- Broad knowledge of blockchain technologies

## Benefícios

- Health insurance
- Educational budget
- Computer/office budget
- Flexible work schedule

## Contratação

- Competitive salary, including equity
- Salary based in USD
- CLT

## Como se candidatar

[Apply for this job](https://jobs.lever.co/tendermint/cefc4eee-a598-4217-a57f-597ec87c7f24?lever-via=BdiiWsgGce)

#### Alocação
- Exterior
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
