### ISSUE TITLE
[REMOTO] Front-end Developer na Softplan

### ISSUE THREAD

**Issue by brunatech** [frontendbr/vagas#5054]
> Vaga Remota durante a pandemia

## Nossa empresa

Exemplo: Aqui na Softplan a empresa especialista em traduzir conhecimento e tecnologia em soluções que simplificam e geram mais valor aos mercados da Gestão Pública, Justiça e Indústria da Construção. 

## Descrição da vaga

Exemplo: Projetos de evolução no SAJ 06
## Requisitos

**Obrigatórios:**
- JavaScript (CommonJS, ES Modules)
-React (15+)
Conhecimento avançado em Webpack.
Conhecimento avançado em Babel, criação de plugins e árvore AST.
Styled Component / JSS / Emotion
Material-UI
Conhecimento avançado em GraphQL
Conhecimento avançado de Apollo (React)
Conhecimento avançado em i18next
Conhecimento em react-hooks-forms
Conhecimento em Micro FrontEnd
Conhecimento avançado de eslint
Conhecimento avançado em prettier
Conhecimento em Design System
Conhecimento avançado em Testing Library e Enzyme
Conhecimento em princípios de design de interação, UX e Design System;
Conhecimento das diretrizes de interfaces da Google (Material Design) e Apple;
Conhecimento em Acessibilidade na Web
Gitlab
DevOps
Docker
Kubernetes (HelmChart)
NodeJS 8+

**Diferenciais:**
- Conhecimento em .Net ou outras linguagens similares de back-end;
- Conhecimento em bancos de dados relacionais e não relacionais;

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ 26/dia
- Programa de desenvolvimento (certificações, especializações e cursos) 
- ...

**Diferenciais:**
- horário flexível 
- plano de carreira em Y.
- PDI (plano desenvolvimento individual) 

## Contratação

CLT Full 

https://jobs.kenoby.com/softplan/job/front-end-specialist-cd-2364-segmento-justia/609999c4e443667fa0b15c38?utm_source=linkedin&utm_campaign=kenoby&utm_medium=post (basta se candidatar por esse link) Como se candidatar

Por favor envie um email para email@email.com.br com seu CV anexado - enviar no assunto: Vaga Frontend Developer

03 a 05 dias Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após cada processo.
E-mail para contato em caso de não haver resposta: bruna.almeida@softplan.com.br

#### Alocação
-100% Remoto

#### Regime
- CLT Full

#### Nível
- Pleno
- Sênior
- Especialista
- Estamos com 03 oportunidades em aberto, Pleno, sênior e especialista.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
