### ISSUE TITLE
[Remoto e Recife] Front-end Developer na Bleu Empreendimentos

### ISSUE THREAD

**Issue by luizpaulogodoy** [frontendbr/vagas#5056]
## Descrição da vaga

É desenvolvedor Front-end e está procurando um job?

Estamos buscando um desenvolvedor(a) Front-end, de todos os níveis, para somar à nossa equipe e que goste de trabalhar em um ambiente dinâmico, aprendendo novas tecnologias.

Se você gosta de trabalhar com inovação, é antenado, auto-didata, pro-ativo, possui um bom relacionamento interpessoal e gosta ou tem interesse de trabalhar em uma empresa com foco em **Blockchain** entre em contato conosco.

## Local

- Remoto
- Presencial (regime híbrido)

## Benefícios

- Plano de saúde integral para o colaborador, incluindo cônjuge e filhos;
- Plano odontológico;
- Vale-refeição;
- Assistência na aquisição de óculos;
- Assistência Home Office;
- Seguro de vida;
- Auxílio creche/escola;
- Auxílio doença/invalidez;
- Auxílio combustível para deslocamento residência-empresa (quando presencial);
- Auxílio com despesas em viagens à serviço da empresa;
- Day Off no aniversário;
- Assistência Funeral;
- Descontos especiais em parceiro comerciais;
- Participações de lucros eventuais.

#### Diferenciais para o trabalho presencial ou em dias presenciais

- Geladeira aberta
- Café à vontade
- Chocolate e lanches livres

#### Diferenciais para quem trabalha Home Office ou em Regime Híbrido
- Auxílio financeiro para Home Office

### **Obrigatórios:**

- HTM5, CSS3 e Javascript
- Pelo menos um framework (Vuejs, Angular 4 ou ReactJS)
- REST API
- Testes unitários
- GIT
- Docker
- SCRUM

### **Desejáveis:**
- NodeJS
- Pré-processadores CSS e Typescript
- Blockchain

## Contratação

- CLT

## Nossa empresa

A Bleu Empreendimentos é uma empresa voltada para criação e desenvolvimento de tecnologia em Blockchain. Combinamos a inovação e descontração para o desenvolvimento de projetos.

## Como se candidatar

Por favor envie um email para rh@bleu.com.br - enviar no assunto: [Front-end]

## Labels

- Remoto
- Presencial
- Pleno
- Sênior
- Júnior
- CLT

**Comment by Cristianojr9** [comment]
Enviado.

**Comment by Gabri3el** [comment]
Enviado!!!

**Comment by Luizgustavo358** [comment]
E-mail enviado!

**Comment by edinelsonslima** [comment]
Enviado!

**Comment by Emilly-horta** [comment]
enviado!

**Comment by Rodskeil** [comment]
Enviado!

**Comment by francineh** [comment]
Prezado: tenho interesse na vaga, acabei de lhe enfiar um e-mail com meu currículo anexado, mas segue o link daqui do Git: https://github.com/francineh?tab=repositories

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
