### ISSUE TITLE
[REMOTO] Vue.js Developer @ Orbital

### ISSUE THREAD

**Issue by wallaceerick** [frontendbr/vagas#5057]
## Empresa
Somos a [Orbital](https://orbital.company), parceiros de grandes agências de comunicação e startups que não possuem um time de desenvolvimento. 
Valorizamos muito e somos fiéis aos nossos parceiros, admiramos a criatividade e o trabalho em equipe. Nascemos remotos para combinar estratégia com criatividade e expertise, buscando soluções inovadoras do planejamento até o resultado.

## Vaga
Estamos procurando developers com bastante experiência em Vue.js e dominem totalmente HTML, CSS e JS.

## Local
100% Remoto (temos um escritório na Vila Olímpia que pode ser utilizado)

## Requisitos

**Obrigatórios:**
- Mínimo de **6 anos** de experiência com HTML, CSS e JS;
- Experiência de pelo menos **2 anos** com Vue.js;
- Experiência com o desenvolvimento de aplicações complexas;
- Consumo de APIs Restfull;
- Git Workflow.

**Desejáveis:**
- Noções de PHP para trabalhar dentro do Laravel.

**Diferenciais:**
- Wordpress
- Flutter
- Node.js

## Contratação
- PJ

## Candidatos
Por favor, [preencham esse pequeno formulário](https://recrutamento.orbital.company/index.php?page=view_vacancy&id=7) com suas informações pessoais e entraremos em contato com os candidatos selecionados.

## Feedbacks
-  2 ou 3 dias

## Nível
- Sênior
- Especialista

## Labels
Especialista, PJ, Remoto, Sênior, Vue, Front, Orbital

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
