### ISSUE TITLE
[Araraquara] Front-end Developer na Corbee

### ISSUE THREAD

**Issue by Rodskeil** [frontendbr/vagas#5058]
**Descrição da Empresa**

Somos uma empresa jovem, que trabalha com tecnologia voltada as instituições financeiras, somos uma família reunida em torno de um sonho e queremos deixar nossa marca, dando espaço para que cada um expresse seu potencial!

**Sobre a Vaga**

DESENVOLVEDOR Javascript | Node.js | PHP (SENIOR)

É você que colocara tudo em pratica, que vai fazer a mágica acontecer! As equipes de negócios e produtos trabalham na concepção de funcionalidades e ferramentas demandadas pelo mercado. Esses projetos se transformam em realidade nas suas mãos.

Buscamos construir nosso time com pessoas de alta performance, que mostrem vontade, energia, proatividade, ambição, autonomia, protagonismo, dinâmico, que tenha comunicação clara e objetiva e que queira aprender e crescer junto com a gente. Prezamos pela satisfação pessoal, saúde e felicidade, e queremos que você encontre esses objetivos inclusive por meio do crescimento da Corbee.

**Requisitos**

- Experiência em programação;
- Experiência em HTML / Javascript;
- Experiência em Laravel 7 ou superior;
- Conhecimento em Javascript ou PHP orientado a objeto;
- Conhecimento em REST / WEBSERVICE;
- Conhecimento em análise de sistemas ou requisitos;

**Desejáveis:**
- Conhecimento em automação de processos;
- Conhecimento em NodeJS;
- Conhecimento em Linux;
- Criação de testes automatizados;

**Contratação**

Salário Inicial R$6.000,00 podendo subir de acordo com a experiência do candidato. 
PJ e Vesting a combinar

Vesting que consiste em oferecer um direito a esses funcionários, os quais passam a ser investidos em um direito de adquirir participação societária na empresa. Ou seja, esses funcionários possuem o direito de adquirir ações ou quotas da empresa. Ao adquirir ações ou quotas, o funcionário torna-se sócio da empresa, ainda que na qualidade de minoritário.

**Como se candidatar**

Envie um email para recrutamento@corbee.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor Front
Entrar em contato também via whatsapp: (11) 99760-2482

**Tempo médio de feedbacks**

Costumamos enviar feedbacks em até 02 dias após cada processo.

**Alocação**
- Alocado
- Remoto

**Regime**
-Pj  
-Vesting

**Nível**
- Pleno
- Sênior

VENHA FAZER PARTE DESTE TIME E MUDE O FUTURO COM A GENTE!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
