### ISSUE TITLE
[São Paulo] Front-end Developer na ITERATIVE

### ISSUE THREAD

**Issue by giovannacocco** [frontendbr/vagas#5059]
> Vaga Remota 

## Nossa empresa

Na Itera atendemos as maiores e mais consolidadas startups do mercado, o que resulta em uma cultura ágil, ambiente disruptivo e gestão próxima, super linear com as culturas digitais! Nossos times tem um mindset que eleva qualquer projeto e demanda de nossos clientes, não só por suas habilidades técnicas, mas pelo forte traço de co criação que é fomentado em toda a empresa.

## Descrição da vaga

Estamos a procura de um(a) profissional que já tenha uma experiência robusta com front, alguém que se preocupe com a satisfação do cliente final nas questões visual e funcional e com a usabilidade da plataforma em si!
Essa posição será focada no desenvolvimento e melhorias de um app (plataforma de prêmios das maiores marcas do mercado!)

## Local

Remoto 

## Requisitos

**Obrigatórios:**

• Desenvolvimento em ambiente mobile (IOS e Android)

• Experiência robusta com a stack REACT Native

• Habilidades CSS, HTML 

• Experiência com ferramentas de versionamento de código (GITLAB) 

• Conhecimento em metodologias ágeis (Scrum/Kanban) 

**Desejáveis:**

• Conhecimentos em REACT.Js (pois tem alguns ajustes nos componentes do site)

## Benefícios

- 12 dias de recesso remunerado, após 1 ano de casa

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para giovanna.cocco@iterative,com.br com seu CV anexado - enviar no assunto: Vaga REACT.js

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
