### ISSUE TITLE
[Remoto] Fullstack Developer na SolarView

### ISSUE THREAD

**Issue by quetlinkober** [frontendbr/vagas#5060]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/fullstack-developer-161109707?origin=github&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong><em>SolarView</em></strong> está buscando uma <strong>pessoa</strong> <strong>desenvolvedora Fullstack.</strong></p>
<p>Somos uma empresa de Tecnologia, Inovação e monitoramento de usinas de energia Fotovoltáica.</p>
<p>Estamos no mercado desde 2013 e somos uma empresa consolidada.&nbsp;</p>
<p>Buscamos um profissional que tenha ambição por sempre obter novos conhecimentos e queira atuar neste segmento de mercado.&nbsp;</p>
<p>Trabalhamos com as seguintes tecnologias: Node.js, React.js, Reactive Native, PHP: CodeIgniter, Laravel e SGBD MYSQL.</p>
<p>Estamos a procura de um candidato que já tenha experiência com alguma destas tecnolgias. Alguém que se julgue´capaz de atuar e se sinta seguro em alguma destas.</p>
<p>Nesse momento estamos procurando um candidato que tenha no mínimo um ano de experiência comprovada.&nbsp;</p>
<p>Temos várias frentes de atuação em nosso time de desenvolvimento, por isso lidamos com inúmeras tecnologias.</p>
<p>Estamos a procura de um profissional que saiba trabalhar em equipe. Um profissional auto-gerenciável, organizado, pontual e que tenha ambição de realizar entregas de valor.</p>
<p>Utilizamos metodologias ágeis de desenvolvimento de software.&nbsp;</p>
<p>Se você quer se candidatar a esta oportunidade, seja bem vindo, vamos bater um papo e desejo boa sorte.&nbsp;</p>
<p>Obrigado.&nbsp;</p>

## SolarView: 
 <p>SolarView é a solução completa para a gestão de dados e informações relacionadas ao consumo e à produção de energia elétrica a partir de sistemas fotovoltaicos.</p>

<p>A SolarView é uma empresa do Grupo AWC, que desde 2013 dedica-se ao desenvolvimento de tecnologia nacional para mercados inovadores no país, como é o caso do mercado de geração distribuída fotovoltaica.</p><a href='https://coodesh.com/empresas/solarview'>Veja mais no site</a>

 ## Habilidades: 
 - Laravel 
- MySQL 
- PHP 
- React.js 
- React Native 
- GIT 
- Node.js
## Local: 
 100% Remoto
## Requisitos: 
 - 1 ou mais anos de experiência em posição similar 
- Sólidos conhecimentos em lógica e programação orientada a objetos 
- Experiência em construir Back-end / Rest API Node.js ou PHP Laravel 
- Domínio em SQL 
- Habituado com scrum 
- Habituado com Git e controle de versão 
- Conhecimentos em React.js
**Diferenciais:** 
 - Conhecimentos em React Native
## Benefícios: 
 - Horários Flexíveis 
- 100% Home office
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack Developer na SolarView](https://coodesh.com/vagas/fullstack-developer-161109707?origin=github&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção <b>Pedir Feedback</b> entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa <b>Recruiter</b> responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Nível
Pleno
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
