### ISSUE TITLE
[Remoto ou presencial] Front-end Developer no iFood

### ISSUE THREAD

**Issue by glaydsonarantesp** [frontendbr/vagas#5062]
## Nossa empresa

O iFood é a maior e mais inovadora empresa FoodTech da América Latina, operando no Brasil e Colômbia. Nosso objetivo é revolucionar o universo da alimentação por meio de tecnologia. Como uma pessoa Engenheira de Software, você irá projetar, codificar, testar serviços que impactam as principais áreas do iFood. Além disso, você também nos ajudará a construir estruturas e ferramentas para identificar gargalos de desempenho, medindo, monitorando e otimizando nosso desempenho, para garantir alta disponibilidade, escalabilidade e tolerância a falhas, impactando diretamente a vida de milhões de pessoas, diariamente.

## Descrição da vaga

- Desenvolver e evoluir produtos web, garantindo sempre qualidade e performance;
- Integração com backend;
- Participar da priorização da evolução do produto, sempre buscando o melhor valor para o negócio.

## Local

- Remoto 
- Presencial (Quando reabrir #:pray:)
- Temos parceria com diversos coworkings espalhados pelo Brasil ;)

## Requisitos

**Obrigatórios:**
- Ser uma pessoa apaixonada por desenvolvimento de software;
- Gostar de autonomia e ter atitude em buscar oportunidades de melhorias;
- Ter interesse em compartilhar conhecimentos e ajudar seus pares quando precisam;
- Ter ótimos conhecimentos em Javascript, HTML e CSS;
- Possuir sólida experiência com pelo menos um framework Javascript moderno (ex: React, Angular, Vue);
- Possuir experiência com testes automatizados;
- Ter habilidade com ferramentas de controle de versão, preferencialmente Git;
- Se identificar com a cultura e metodologias de desenvolvimento ágil;

## Benefícios e Diferenciais:

Veja [em nosso site de Carreiras](https://carreiras.ifood.com.br/) tudo o que o iFood tem a te oferecer :)

## Contratação

CLT

## Como se candidatar

Por favor envie um email para glaydson.arantes@ifood.com.br com o link do seu LinkedIn - enviar no assunto: Vaga Front

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by joaovitorzv** [comment]
@glaydsonarantesp Libera uma vaguinha pro juninho aqui full motivado pode ser até em troca de cupom :)
