### ISSUE TITLE
[Remoto] Senior Front-end Developer no Grupo Fcamara - React Native

### ISSUE THREAD

**Issue by lucasmelo20** [frontendbr/vagas#5066]
### Em busca de novos desafios e oportunidades de evolução na sua carreira?
o **Grupo FCamara** está com uma oportunidade para um dos maiores players de e-commerce do pais
https://www.fcamara.com.br/

Sobre a FCamara:

Somos uma consultoria em tecnologia que é referência em transformação digital para as maiores empresas de e-commerce, turismo, varejo, saúde, logística e operações portuárias do Brasil. Nosso maior diferencial está no nosso culture code e em como selecionamos e formamos talentos, com interdisciplinaridade e criando times de alta performance. Para continuarmos sempre crescendo, buscamos pessoas com seu perfil e trajetória profissional para fazer parte do nosso time escrevendo essa história de sucesso.

Estamos buscando os melhores profissionais para fazer parte do nosso time, se você tem perfil inovador, gosta de ambientes dinâmicos, é direcionado a resultados de alta performance e possui experiência com automação de testes, esta oportunidade é para você! #VenhaSerSangueLaranja

### Requisitos e Responsabilidades:
Atuando com **desenvolvimento front end - react native**

- Fluência em HTML, CSS, JavaScript e TypeScript
- Sólidos conhecimentos em React e React Native
- Testes (Jest, Enzyme)
- Experiência com GIT e GitFlow
- Arquiteturas de estilo (CSS-IN-JS, SCSS)
- Redux
- Experiência com ferramentas de build (webpack)

Será um diferencial:
- Conhecimento em desenvolvimento Android e IOS
- Conhecimento em EXPO

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

Interessados ou indicações, envie seu currículo para: nathalia.carlana@fcamara.com.br ou marcelo.mazini@fcamara.com.br

https://www.fcamara.com.br/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
