### ISSUE TITLE
[Remoto] Senior Front-end Software Engineer na Pier

### ISSUE THREAD

**Issue by josianepenachio** [frontendbr/vagas#5069]
## Nossa empresa

A Pier nasceu pra levar leveza pra vida das pessoas e queremos que elas vivam a vida do jeito que elas mais gostam! Somos um seguro sem desconfiança, que as pessoas têm porque gostam de ser livres para serem elas mesmas. Oferecemos coberturas inteligentes, criadas com tecnologia Pier: menos papelada, menos preocupação, mais agilidade e capacidade de entregar produtos que cumprem o que prometem e ainda te arrancam suspiros de alegria.

No que acreditamos:
- Ter um time de excelência, com alto nível de autonomia e com sentimento de dono, mais de 35% da empresa possui stock options
- Transparência, temos uma cultura forte de compartilhamento de informação, dados de salários e stocks são 100% visíveis para qualquer um na empresa, escrevemos Memorandos para debater a estratégia, temos os OKRs de todos os times abertos
- Velocidade e inovação, fomos a primeira seguradora digital do Brasil no modelo sandbox pela SUSEP, lançamos o Pier Bolt, inteligência artificial para pagamento instantâneo de claims

Conheça mais sobre nós no nosso blog: https://blog.pier.digital/

## Descrição da vaga

Missão: Manter a qualidade de código e engenharia num nível invejável de excelência sem abrir mão da autonomia e produtividade.

- Escrever código (Rails, Node, Python) para implementar, junto com times de produto, novas funcionalidades nas nossas plataformas e construir uma nova maneira de oferecer seguros no mundo
- Ter abertura para trabalhar com Frontend, App, o que o time precisar (T-shaped model)
- Manter o backend resiliente, testado, e capaz de suportar o nosso crescimento (já crescemos 10x a quantidade de hits desde janeiro e devemos crescer mais umas 10x até o fim do ano)
- Ajudar a construir decisões de arquitetura dos nossos serviços

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Tiver conhecimento de tecnologias de front-end e bibliotecas como React e React Native
- Conseguir garantir qualidade de código seguindo padrões que garantem agilidade e revisando PRs
- Buscar promover legibilidade escrevendo código de qualidade que será lido por outros desenvolvedores da equipe, assim disseminando conhecimento do framework
- Escrever código para implementar novas soluções para nossos membros e construir uma nova maneira de oferecer seguros no mundo
- Aumentar nossa eficiência e produtividade!
- Tiver curiosidade e humildade intelectual, autonomia para tomada de decisão e cooperação
- Valorizar aprendizado constante

## Benefícios

- Plano de saúde e odontológico da SulAmérica 100% custeados pelo Pier
- Gympass e Zenklub pra você cuidar da sua saúde, física e mental
- Benefício flexível no cartão Caju de R$ 1.380,00 por mês para cultura, mobilidade, refeição, alimentação e saúde
- Infraestrutura de trabalho remoto + R$ 150,00 por mês
- Incentivos à educação
- Possibilidade de se tornar sócio(a)
- Remuneração a combinar

**Diferenciais:**
- Agenda livre: faça seus blocks como quiser, tire days off, aumente seu horário de almoço!
- Não controlamos férias: você tem direito a mais de 30 dias por ano e pode tirar quando e como quiser

## Contratação

CLT a combinar

## Como se candidatar

Por favor acesse https://jobs.lever.co/pier/182db30e-c4e9-41e0-a613-fb06cb44cb51 e se inscreva!

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 20 dias após cada processo.
E-mail para contato em caso de não haver resposta: josiane.penachio@pier.digital

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
