### ISSUE TITLE
[Porto Alegre - RS] Front-End Developer Junior/Pleno na Warren Brasil

### ISSUE THREAD

**Issue by jonatassalgado** [frontendbr/vagas#507]
Descrição da vaga
====================
Sem restrições de curso ou universidade, estamos à procura de pessoas alinhadas com a nossa cultura (get shit done, coragem, humildade e otimismo) e que tenham vontade e motivação para participar do crescimento de uma empresa que busca mudar a forma como as pessoas cuidam do seu dinheiro.

__A vaga é para ser pai/mãe do webapp do Warren!__ No seu dia a dia, você será responsável por implementar novas funcionalidades, propor melhorias, manter a qualidade do código, versionamento, deploy, participação na priorização de funcionalidades e tudo que envolver o desenvolvimento do app.

_Candidatos são considerados pelas habilidades envolvidas no trabalho proposto, sem distinção de gênero ou qualquer outra característica._

Requisitos
===================
_Obrigatórios_
* Portfólio com algum app criado do zero ou github com contribuição relevante. Não exigimos que você seja formado ou que tenha experiência trabalhando em alguma empresa, mas queremos ver o que você é capaz de fazer. Show me the code, not tell me (mandatório).

* Conhecer o [oiwarren.com](https://oiwarren.com). Acesse o site do Warren e crie uma conta. Assim você já conhece boa parte do desafio ;)

_Valorizamos_

* Cuidado com UX/UI e guidelines da plataforma.
* Conhecimento em __Angular__.
* Bom conhecimento em __JavaScript__.
* Gosto por aprender.
* Motivação no dia a dia em fazer as coisas acontecerem.

A empresa 
==============
A Warren é uma fintech localizada em __Porto Alegre__ que tem como principal objetivo descomplicar o obscuro mundo dos investimentos e convencer as pessoas de que cuidar de suas finanças pessoais pode ser algo leve, simples e até divertido. Somos uma plataforma on-line que incentiva nosso usuário a criar objetivos e investir neles, mostrando que seu primeiro milhão ou viagem ao redor do mundo podem estar mais próximos do que imagina. 

Existimos para facilitar a vida de quem quer investir bem o seu dinheiro, sem o blá-blá-blá, gravatas e taxas que os bancos oferecem. Nossa proposta envolve um investimento com transparência, agilidade e empatia. Já são mais de 10 mil pessoas que confiaram seus sonhos e metas ao Warren e é por isso que precisamos estar disponíveis em todas as plataformas possíveis: queremos que todos tenham acesso ao Warren e possam acompanhar seus investimentos onde quer que estejam. 

O Warren já tem um app para iOS/Android e versão Web, agora estamos buscando alguém para abraçar a continuação do nosso webapp, e fazer parte da construção desse mundo com menos preocupações e mais sonhos alcançados. 

Posição
================
Desenvolvedor Front End (Junior/Pleno)

Tipo de contratação
====================
Presencial em Porto Alegre, PJ.

Oferecemos
=====================
Um ambiente de startup legal com pessoas comprometidas, horário flexível, bastante café, ambiente dev rodando com práticas ágeis (kanban, priorização, scrum, etc) e uma baita oportunidade de crescimento profissional e aprendizado.

Com quem você vai trabalhar
===============
Você irá trabalhar com uma equipe multidisciplinar (designers, desenvolvedores, marketing, etc) que desenvolve toda experiência inovadora de investir com o Warren. O site já está no ar mas existe um mundo de coisas novas a fazer.

Como aplicar
=========================
Envie um email para __staff@oiwarren.com__ com o assunto __Vaga Front End até 01/10__ falando sobre você em até 3 linhas e com links do portfólio, github ou apps. Mas não deixe para amanhã, pois assim que encontrarmos o candidato ideal encerraremos a vaga. Se você foi indicado por alguém, informe no email o nome de quem o indicou. Vamos lá?
 
Dúvidas?
=============================
staff@oiwarren.com

**Comment by rodrigosaling** [comment]
Oi @LFeh ! Acho que a label CLT foi adicionada por engano, porque na descrição da vaga consta que a contratação é por PJ.

**Comment by theuves** [comment]
> Presencial em Porto Alegre, PJ.

[@jonatassalgado] Hehe, aceitariam remoto?

**Comment by jonatassalgado** [comment]
@theuves Para esta vaga em específico não :/

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by chroda** [comment]
Vaga segue aberta?

**Comment by clautercarlos** [comment]
De acordo com o site deles, sim. [Trabalhe com o Warren](https://oiwarren.com/vagas/)

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
