### ISSUE TITLE
[Remoto] Senior Front-end Developer na SupplyLabs

### ISSUE THREAD

**Issue by godois** [frontendbr/vagas#5076]
## Nossa empresa

A SupplyLabs foi criada com o propósito de entregar uma experiência 100% digital na gestão de risco de cadeias de fornecimento.
Nossa plataforma é utilizada por grandes empresas, para garantir o compliance de seus fornecedores e prestadores de serviço.
Nosso time é composto por gente bacana, qualificada e amigável.
Nossos desafios como plataforma de software são imensos, desde qualidade de software, escalabilidade, reproveitamento de código, análise de dados, entre outros.
Como time, esperamos que os membros sejam disciplinados, colaborativos, humildes e honestos.
Esta é uma posição que exige dedicação exclusiva, e disponibilidade integral durante nosso horário de trabalho.

## Descrição da vaga

Estamos à procura de uma pessoa referência em desenvolvimento de frontend, que será o ponto focal nas decisões e mentoria do time nesta disciplina.
Codificar o frontend será sua principal responsabilidade, bem como mentorar os demais integrantes do time, através de code review e demais processos.
Você terá total liberdade para aplicar as suas escolhas técnicas.
Ajudar na prototipação de produto.
Participar de discussões para levantamento de hipóteses de solução, nos ajudando a pensar novos produtos e novos módulos.
Participar ativamente de decisões de tecnologias, infraestrutura, etc.

## Local

Vaga Remoto, mas escritório disponível no bairro Paraíso em São Paulo

## Requisitos

**Obrigatórios:**

Ter trabalhado como referência técnica em projetos utilizando javascript e ReactJS, e que seja um produto digital.
Ser fluente com tecnologias como HTML, CSS e Javascript.
Saiba consumir APIs REST e GraphQL de forma otimizada.
Saiba versionar código e interagir com GIT.
Ter experiência em build, deploy e CI e CD para aplicações frontend.
Gostar de trabalhar em grupo, ter empatia e humildade para liderar discussões.
Ser curioso e estudioso.
Ter lado analítico, preocupado com a ciência por trás das decisões.
Que tenha noções de testes automatizados em aplicações javascript.

## Contratação

PJ a combinar

## Como se candidatar

Envie um e-mail para rh@supplylabs.com.br, com assunto: Vaga Desenvolvedor ReactJs;
Inclua portfolio, repositório Github, currículo, Linkedin e todo material que demonstre seu nível técnico e histórico profissional e acadêmico;
Conte na mensagem o quê lhe interessou na vaga;
Informe sua pretensão salarial;

## Tempo médio de feedbacks

Processo Seletivo 100% online;
Análise do material enviado ou referenciado no e-mail de candidatura;
Conversa para conhecer a(o) candidata(o), e para apresentar a empresa;
Conversa sobre engenharia de software;
Teste de codificação;
Conversa com os gestores e o time dev;

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
