### ISSUE TITLE
[São Paulo] Desenvolvedor Front-end Reactjs, Vuejs e Cloud na @Hagloo

### ISSUE THREAD

**Issue by giovaniPoletohagloo** [frontendbr/vagas#5077]
Resumo das atividades:
● Desenvolvimento de sistema web com funções análiticas para mercado financeiro e imobiliário utilizando React;
● Especificação e criação de novos sistemas utilizando React / Vue.js  alinhado a boas práticas de desenvolvimento de software;
● Levantamento de novos requisitos junto à equipe de desenvolvimento (utilizando metodologias ágeis).

Conhecimentos desejáveis:  
● Experiência com React e Vue;
● Java Script, HTML e CSS;
● Experiência em desenvolvimento web utilizando frameworks Java Script (React / Vue.js);
● Padrões de projeto e boas práticas de programação;
● GIT;
● Noções de UX/UI;
● Gostar de aprender e compartilhar conhecimento.

Diferenciais:
● Ter experiência com componentes de gráficos interativos (plotar gráficos);
● Desenvolvimento de sites responsivos;
● Experiência com mercado imobiliário e/ou crédito;
● Experiência com Code Review;
 - Nossos de desenvolvimento em plataforma Azure ou AWS.
● UX/UI.

Cursos / Formação (Superior ou Técnico):
Sistemas para Internet, Ciência da Computação, Sistemas de Informação, Engenharia da Computação, e áreas relacionadas.

Sobre a vaga:
● Regime: PJ;
● Acesso a plataforma de cursos online e eventos de tecnologia;
● Trabalho remoto e presencial.

CVs via rh@hagloo.com

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
