### ISSUE TITLE
[Remoto ou Porto Alegre] Angular Specialist na Aegro

### ISSUE THREAD

**Issue by wellingtoncosta** [frontendbr/vagas#5079]
## Nossa empresa

Nascemos do campo para o campo, sabendo que ninguém conhece uma fazenda como o seu produtor. Portanto, entendemos que é entregando as ferramentas certas nas mãos de quem produz que nós ajudamos a agricultura a evoluir.

Unimos a rotina da lavoura à gestão financeira, centralizando informações para tornar a vida do profissional rural mais eficiente. Desta forma, aprimoramos o controle de processos produtivos e entregamos soluções para a gestão de fazendas.

A Aegro é uma empresa apaixonada por evoluir o estado-da-arte da tecnologia para a agricultura. Nós contratamos pessoas com um conjunto de habilidades amplo que estão prontas para enfrentar desafios que impactam a vida de mais de cinco milhões de produtores rurais de todo Brasil.

## Descrição da vaga

Estamos buscando uma pessoa especialista em frontend, que tenham interesse em trabalhar com Angular e queiram encarar conosco o desafio de construir o primeiro unicórnio agtech brasileiro, nos ajudando nas principais decisões técnicas e seus impactos no produto no médio/longo prazo.

## Local

Remoto ou Escritório em Porto Alegre.

## Requisitos

**Obrigatórios:**
- Conhecimentos sólidos de arquitetura de software;
- Ter escrito código em AngularJS e/ou Angular, ou vontade de aprender;
- Conhecimento de APIs RESTful;
- Capacidade de produzir código limpo e de fácil manutenção;
- Nível médio de leitura e escrita em inglês;
- Motivação por aprendizado e desenvolvimento contínuos;
- Capacidade de se comunicar de forma concisa, franca e clara (também por escrito);

**Desejáveis:**
- Experiência com design system;
- Experiência com frontend híbrido;
- Experiência com micro frontends;
- Experiência com metodologias ágeis (Scrum e Kanban);
- Experiência com diferentes metodologias de desenvolvimento (DDD, TDD, BDD);
- Conhecimentos sobre desenvolvimento backend com Java/Spring;
- Contribuições em projetos open source;
- Participação em comunidades de tecnologia com palestras e afins;

## Benefícios

- Plano de Saúde Unimed Seguros
- Plano Odontológico Unimed Seguros
- VR ou VA
- Flexibilidade de horário
- Acesso a plataforma da Alura para cursos de atualização
- Oportunidade de realizar 8 horas de treinamento/cursos/capacitações no horário de trabalho por mês

## Contratação

CLT

## Como se candidatar

Por favor, faça sua aplicação através do Kenoby. Basta acessar este link: https://jobs.kenoby.com/aegro/job/angular-specialist/605cf42ec1e9454fac6875c3?utm_source=website

## Tempo médio de feedbacks

O nosso feedback costuma não levar mais do que 2 dias para cada etapa do processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
