### ISSUE TITLE
[Rio de Janeiro] Front-End Developer Sênior na Wooza

### ISSUE THREAD

**Issue by dulcetti** [frontendbr/vagas#508]
## Descrição da vaga
O candidato será responsável pelo desenvolvimento/suporte às páginas/componentes web de média/alta complexidade, implementação de alta performance front-end visando transformar o material produzido pela área de design em páginas HTMLs que serão utilizados pelos clientes.

Dar suporte ao pessoal pleno e júnior na implementação de código e implantação de padrões definidos pela equipe.

Nossos projetos são feitos com Angular 1.6, vários componentes e estamos iniciando a implementação de Angular 2/4 e React.

## Local
Shopping Downtown, Barra da Tijuca - Rio de Janeiro/RJ

## Benefícios

 * Plano de saúde Bradesco
 * Assistência odontológica Amil
 * Seguro de vida
 * VR de R$ 26/dia
 * Vale Transporte

## Diferenciais

 * Fliperama
 * Máquina de doces com um preço sagaz
 * Frutas e pipoca (essa é somente às 16h)
 * Horário flexível

### Obrigatórios:
 * Inglês técnico;
 * Domínio do HTML5, JavaScript, CSS3 e seus pré-processadores (SASS/LESS);
 * TDD (Karma/Jasmine básico/intermediário);
 * ES6 (básico/intermediário);
 * Conhecimento intermediário/avançado de AngularJS e do funcionamento de uma SPA;
 * Domínio de versionamento de código (Git/Git Flow/PR);
 * Automatização de tarefas (Gulp/Webpack).

### Desejáveis:
 * Perfil de Liderança;
 * Contribuição em Projetos Open Source (GitHub);
 * Integração Contínua (TFS)

## Contratação
 * CLT

## Nossa empresa
Somos a Wooza.

Oferecemos soluções e potencializamos o fluxo de vendas digitais através de um olhar diferenciado no design das páginas dos nossos clientes. O resultado dessa expertise aplicada é uma maior conversão dos acessos online em vendas.

Promovemos, simultaneamente, interações multicanais via mídia online, e-mail marketing, atendimento ao cliente, cross sales, SMS ou chat. Tudo para que o usuário tenha uma experiência de compra encantadora.

## Como se candidatar

Por favor, envie um e-mail para camilla.alves@wooza.com.br com seu CV anexado e o perfil do Linkedin - enviar no assunto: `[Vaga] Front-End Developer Sênior`

**Comment by RaphaAmericano** [comment]
Há vaga para estagiário ou júnior?

**Comment by ygorlazaro** [comment]
Aceita PJ?

**Comment by dulcetti** [comment]
@ygorlazaro somente CLT

**Comment by dulcetti** [comment]
@RaphaAmericano no momento não, assim que surgir alguma eu posto por aqui ;)

**Comment by RaphaAmericano** [comment]
@dulcetti beleza, valeu!

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by dulcetti** [comment]
@LFeh Oi Felipe, abriram novas vagas sim, temos mais 5

**Comment by juansaintclair** [comment]
<3 Vale a pena.

**Comment by LFeh** [comment]
@dulcetti Boa

**Comment by vititu** [comment]
Somente Sênior? Não rola Júnior?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
