### ISSUE TITLE
[Remoto] Front-end React Native Developer na AZ Energy | Ez.Devs

### ISSUE THREAD

**Issue by LaraEJAlves** [frontendbr/vagas#5080]
## Nossa empresa

**Sobre a ez.devs**
Nosso propósito e missão

A EZ é uma empresa que tem o objetivo de transformar negócios através de pessoas, cultura e tecnologia. A gente acredita que esses motores são capazes de mudar o rumo de organizações inteiras. 

Então para fazer esse objetivo acontecer, nós temos a missão de conectar talentos de tecnologia a Startups e Scale-ups em um marketplace gerenciado.

Conheça um pouco mais sobre nós visitando [nosso site](https://talentos.ezdevs.com.br/)😉
 
**Sobre o cliente**
A AZ Energy é uma startup que possui foco em mobilidade elétrica e, desde 2013, é pioneira em carregadores de carros elétricos, ajudando as pessoas a recarregarem seus veículos e contribuírem de forma segura para a diminuição das emissões de CO2.

Fundada em 2011, a AZ Energy faz parte do grupo AZ Business e tem como propósito trazer ao mercado soluções para eficiência energética.

## Descrição da vaga

**Responsabilidades e Atribuições**

- Atuar no desenvolvimento e evolução dos produtos/tecnologias mobile (iOS e Android);
- Definir padrões arquiteturais, convenções e infraestrutura necessária para desenvolvimento do app com React Native;
- Desenvolver componentes em código nativo quando necessário (iOS e Android);
- Se manter atualizado em relação a novas tecnologias e empregá-las internamente quando apropriado.

## Local

Remoto

## Requisitos

**Obrigatórios:**

- Experiência atuando com React Native;
- Domínio em JavaScript;
- Domínio em versionamento de código (GIT).

**Diferenciais:**
- Experiência atuando em projetos com Scrum;
- Conhecimento em testes automatizados em mobile.

## Benefícios

- Aulas de inglês;
- Descanso remunerado;
- Gympass;

## Contratação

PJ

## Como se candidatar

Candidate-se a vaga pelos links:
[Nível Sênior](https://talentos.ezdevs.com.br/vaga/pessoa-desenvolvedora-react-native-senior-n7q4jwne?utm_source=github&utm_campaign=v_rn_senior)
[Nível Pleno](https://talentos.ezdevs.com.br/vaga/pessoa-desenvolvedora-react-native-pleno-wg64pj34?utm_source=github&utm_campaign=v_rn_pleno)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
Em caso de dúvidas, envie para lucas.carvalho@ezdevs.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
