### ISSUE TITLE
[Remoto] Front-end React Native Developer na Quero Delivery | Ez.Devs

### ISSUE THREAD

**Issue by LaraEJAlves** [frontendbr/vagas#5081]
## Nossa empresa

**Sobre a ez.devs**
Nosso propósito e missão
A EZ é uma empresa que tem o objetivo de transformar negócios através de pessoas, cultura e tecnologia. A gente acredita que esses motores são capazes de mudar o rumo de organizações inteiras. 

Então para fazer esse objetivo acontecer, nós temos a missão de conectar talentos de tecnologia a Startups e Scale-ups em um marketplace gerenciado.

Conheça um pouco mais sobre nós visitando [nosso site](https://talentos.ezdevs.com.br/) 😉

 
**Sobre o cliente**
A Quero Delivery é uma startup de foodtech que nasceu em Lagarto/Sergipe, e desde então vem crescendo cada dia mais e se encontra em diversos estados do Brasil.

Hoje, já possui uma legião de fãs que carinhosamente o chamam de roxinho ou de "notificação preferida". Esses são os QDlovers.

Mais do que apenas um aplicativo de delivery, o Quero existe para fazer com que seus usuários usem o tempo para o que realmente importa, e o resto o Quero Delivery entrega!

## Descrição da vaga

- Atuar no desenvolvimento e evolução dos produtos/tecnologias mobile (iOS e Android);
- Definir padrões arquiteturais, convenções e infraestrutura necessária para desenvolvimento do app com React Native;
- Desenvolver componentes em código nativo quando necessário (iOS e Android);
- Se manter atualizado em relação a novas tecnologias e empregá-las internamente quando apropriado.

## Local

Remoto

## Requisitos

**Obrigatórios:**

- Experiência atuando com React Native;
- Domínio em JavaScript;
- Domínio em versionamento de código (GIT).

**Diferenciais:**
- Experiência atuando em projetos com Scrum;
- Conhecimento em testes automatizados em mobile.

## Benefícios

- Aulas de inglês;
- Descanso remunerado;
- Gympass;

## Contratação

PJ

## Como se candidatar

Candidate-se a vaga através [desse link.](https://talentos.ezdevs.com.br/vaga/pessoa-desenvolvedora-mobile-react-native-pleno-eja5c25t?utm_source=github&utm_campaign=v_rn_pleno_qd)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
Em caso de dúvidas, envie para lucas.carvalho@ezdevs.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
