### ISSUE TITLE
[Remoto] Full Stack Developer na Kovi | Ez.Devs

### ISSUE THREAD

**Issue by LaraEJAlves** [frontendbr/vagas#5082]
## Nossa empresa

**Sobre a ez.devs**
Nosso propósito e missão
A EZ é uma empresa que tem o objetivo de transformar negócios através de pessoas, cultura e tecnologia. A gente acredita que esses motores são capazes de mudar o rumo de organizações inteiras. 

Então para fazer esse objetivo acontecer, nós temos a missão de conectar talentos de tecnologia a Startups e Scale-ups em um marketplace gerenciado.

Conheça um pouco mais sobre nós visitando [nosso site](https://talentos.ezdevs.com.br/) 😉

 
**Sobre o cliente**
A Kovi é uma startup de mobilidade movida pela paixão de mudar vidas. Diariamente, quebram barreiras por meio da tecnologia para melhorar a vida dos motoristas de aplicativo oferecendo a melhor experiência de aluguel de carros.

A Kovi acredita em um mundo sem trânsito, onde as pessoas se deslocam de forma barata e no menor tempo possível. E por isso, buscam constantemente formas mais eficiente de locomoção.

## Descrição da vaga

**Responsabilidades e Atribuições**

- Criar e manter as melhores API's Serverless;
- Manter uma arquitetura coesa em projetos com uma rápida evolução;
- Implementar estratégias de integração simples, extensíveis com tecnologias e serviços de terceiros;
- Construir soluções incrementais que são compatíveis com versões anteriores;
- Garantir a conformidade com os planos do projeto e os padrões do setor;
- Apresentar ideias e abordagens complexas em termos simples e comunicáveis nos níveis de engenharia e gerenciamento.

**Remuneração**
R$ 16.000,00 ~ R$ 20.000,00

## Local

Remoto

## Requisitos

**Obrigatórios:**
Buscamos uma pessoa que tenha uma ampla compreensão do desenvolvimento web como um todo (perfil T-Shaped):

- Profunda experiência com pelo menos uma das seguintes tecnologias: NodeJS, ReactJS, Typescript e JavaScript;
- Bancos de dados relacionais e não-relacionais;
- Desenvolvimento orientado a testes;
- Sólido conhecimento de GIT.

**Diferenciais:**
- Conhecimento em arquitetura Serverless;
- Experiencia atuando com ferramentas como Twilio;
- Conhecimento em mensageria;
- Conhecimento em AWS;
- Conhecimento prático de integração contínua e implantação contínua (CI / CD).

## Benefícios

- Aulas de inglês;
- Descanso Remunerado;
- Gympass.

## Contratação

PJ

## Como se candidatar

Candidate-se a vaga através [desse link](https://talentos.ezdevs.com.br/vaga/pessoa-desenvolvedora-full-stack-seniorespecialista-5ctydp5s?utm_source=github&utm_campaign=v_fs_senior).

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
Em caso de dúvidas, envie para lucas.carvalho@ezdevs.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
