### ISSUE TITLE
Home Office - SP-  Angular Developer na Capco

### ISSUE THREAD

**Issue by Tai-Morena** [frontendbr/vagas#5083]
**** Vagas de Desenvolvedor (a)  Front end - ANGULAR -***

Oi pessoal!! Falo da Capco, somos uma multinacional do Reino Unido, e atuamos em 32 países, especialmente no Ramo Financeiro.
Estamos com algumas vagas pra atuar com Desenvolvimento Front End - Angular.

No momento estamos atuando 100% Home Office, com salário competitivo no mercado + Cartela de Benefícios que incluem:
VR+VA+Auxilio Combustivel+PLR+Previdência Privada+ Auxilio Creche+ Gym Pass+ Descontos em Pós e Faculdades, entre outros.

Quem tiver interesse, me enviar o cv com a pretensão salarial para: 

tainan.nogueira@capco.com

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
