### ISSUE TITLE
[Híbrido Santa Catarina] Full Stack Developer (React/Node) na Ahgora | Ez.Devs

### ISSUE THREAD

**Issue by LaraEJAlves** [frontendbr/vagas#5084]
## Nossa empresa

**Sobre a ez.devs**
Nosso propósito e missão
A EZ é uma empresa que tem o objetivo de transformar negócios através de pessoas, cultura e tecnologia. A gente acredita que esses motores são capazes de mudar o rumo de organizações inteiras. 

Então para fazer esse objetivo acontecer, nós temos a missão de conectar talentos de tecnologia a Startups e Scale-ups em um marketplace gerenciado.

Conheça um pouco mais sobre nós visitando [nosso site](https://talentos.ezdevs.com.br/) 😉

**Sobre o cliente**
A Ahgora cria soluções em nuvem nas áreas de Gestão de Pessoas, Recursos Humanos, Controle de Acesso e outras atividades que tornam a gestão empresarial mais dinâmica e eficaz. 

A Ahgora tem compromisso com a inovação! Em sua trajetória, está sempre em busca contínua pelo desenvolvimento e soluções que promovam a transformação! Para compor esse time, procuramos pessoas desenvolvedoras que irão zelar pela segurança das aplicações desenvolvidas.

## Descrição da vaga

**Responsabilidades e Atribuições**

- Colaborar com todo o time, tornando-se um integrante importante no desenvolvimento do produto;
- Escrever códigos com alta cobertura de testes automáticos;
- Participar de concepção de melhorias de produto, buscando sempre trazer simplicidade e praticidade ao usuário.

## Local

Híbrido - Santa Catarina

## Requisitos

**Obrigatórios:**
- Conhecimento na construção de interfaces de usuário amigáveis com Javascript/HTML/CSS;
- Experiência com javascript moderno, testes unitários e de integração, debugging e automações;
- Experiência com Node;
- Experiência com React, Angular, Vue ou outro framework frontend.

**Diferenciais**

- Interesse pelas tecnologias emergentes da plataforma web;
- Experiência com C#;
- Atuação em times realmente ágeis e domina os termos Kanban, Scrum, XP, Lead Time, Throughput, Monte Carlo, etc;
- Atuação próxima a designers para desenvolver experiências de usuário incríveis.

## Benefícios

- Descanso remunerado;
- Gympass;
- Aulas de inglês;

## Contratação

PJ

## Como se candidatar

Candidate-se a vaga através [desse link](https://talentos.ezdevs.com.br/vaga/pessoa-desenvolvedora-full-stack-javascript-node-pleno-itxwj025?utm_source=github&utm_campaign=v_fs_pleno)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
Em caso de dúvidas, envie para lucas.carvalho@ezdevs.com.br

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
