### ISSUE TITLE
[Remoto] Tech Lead Frontend Engineer (Runa HR)

### ISSUE THREAD

**Issue by hugodias** [frontendbr/vagas#5085]
## Nossa empresa

Runa is changing the way people work in Latin America. The first step in that mission was to create an automated payroll product for the 17.5MM SMBs that rely on Excel. Moving forward, Runa will expand its product offering to include an ecosystem of financial services and benefits that will improve how companies operate and how employees work. With a recent valuation of $75MM, Runa is backed by Ribbit Capital, Salesforce Ventures, and Y-Combinator.

## Descrição da vaga

As Tech Lead, you will lead Agile, cross-functional squads to scope, design, and build scalable, performant, and secure web applications. You will code, create, and review pull requests daily. You will provide mentorship for all Engineers on your team to help them grow in their technical responsibilities and remove blockers. You will constantly partner with the Product Manager, Delivery Leads, and Quality Assurance engineers in the planning and execution of Runa’s product roadmap focused on delivering continuous value in HR and payroll software areas. You will push for best practices and good engineering standards across your team.

### Who you are
As our Tech Lead Frontend Engineer, you have deep knowledge of the JavaScript language and experience working with modern React and common React packages. 

You have a thorough understanding of the options and tools available for managing an application’s state and its underlying functional programming concepts. You can start a greenfield project and explain the reasons behind each technology or methodology decision based on your experience and data.

You can partner with Product Leads to plan the long-term vision for the project. You keep in sync with other engineers on your team sharing the long-term technical vision about the project.

You constantly create projects for the engineering team to improve product quality, security, and performance that have a particular impact across your team.

You are a great communicator and are active in your development community. 

### Responsibilities
* Write clean, efficient, performant, and secure code to build web applications in sprint dev cycles.
* Help to define and improve our internal standards for style, maintainability, and best practices for a high-scale web environment. Maintain and advocate for these standards through code review.
Solve technical problems of the highest scope and complexity for your team.
* Proactively seeks out difficult impediments to our efficiency as a team ("technical debt"), propose and implement solutions that will enable the entire team to iterate faster
* Help improve the overall experience of our product by improving the quality of the Front-end features both in your group and features that benefit other groups.
* Help to define and improve our internal standards for style, maintainability, and best practices for a high-scale web environment. Maintain and advocate for these standards through code review.
* Consistently ship large features and improvements with minimal guidance and support from other team members. Collaborate with the team on larger projects.
* You can start greenfield projects defining best practices, tooling, and standards.
* You’ll work with Product Management and other stakeholders (Backend, UX, etc.) to iterate on new features within the Runa HR products.
* Collaborate on building out Runa’s library of front-end reusable code and libraries for future use.
* Exert influence on the overall vision and long-range goals of your team. This could be technical and/or product-focused.
* Provide mentorship for all Engineers on your team to help them grow in their technical responsibilities and remove blockers.

## Local

Remoto

## Benefícios

- Plano de saúde
- Seguro de vida
- VR

## Requisitos

* Bachelor’s degree in Computer Science or equivalent work experience (10 years)
* 8+ years of experience working as a software engineer, 3+ years as a senior engineer.
* 4+ years of Senior-level experience with Javascript, React, Redux, Websockets, Async/Await
* Ability to create clean, modern, testable, well-documented code
* English fluency, verbal and written
* Personality traits: Professional, problem solver, proactive, passionate, team player.
* Experience with Agile process, primarily Scrum
* Experience building and delivering customer-facing front-end web applications.
* Experience working with UI/UX tools such as Figma, Adobe XD or Axure RP and translating them effectively into HTML/CSS and Javascript.

## Contratação

CLT - _Runa is a company in Mexico but it has Office in Brazil (São Paulo)_

## Como se candidatar

https://www.ycombinator.com/companies/runa/jobs/ovzpbXC-sr-software-engineer-fe

## Labels

- 🏢 Remoto
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ CLT

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
