### ISSUE TITLE
[Curitiba ou Remoto] Jr. Full Stack Dev. na NZN (Baixaki)

### ISSUE THREAD

**Issue by kavalcante** [frontendbr/vagas#5086]
## Descrição da vaga
A NZN tem mais de 20 anos de expertise além de ser um dos principais players para soluções de publicidade e comunicação online. Proprietária das verticais TecMundo, VOXEL, The BRIEF, Mega Curioso, Minha Série, Baixaki e Click Jogos, a NZN veicula campanhas de mídia e de conteúdo de alto impacto para seus clientes entre marcas e agências de publicidade digital, de forma direta e em parceria com redes programáticas. Além disso, possui 23 milhões de usuários únicos mensais, alcançando 1 em cada 5 usuários da internet brasileira.

Para dar continuidade a esse trabalho, nós buscamos um(a) profissional com capacidade de traduzir a necessidade dos nossos clientes e entregar valor, apoiando nosso time de executivos em nossas campanhas de mídia e conteúdo. Se você quer trabalhar conosco, está alinhado aos nossos valores e possui capacidade técnica, então queremos te conhecer! 

A NZN, tendo a Diversidade como um de seus sete valores, oferece oportunidades iguais em seus processos seletivos. A candidatura de todas as pessoas é incentivada, independentemente de orientação sexual, identidade de gênero, cultura, cor, etnia, religião, formação ou limitação. Caso você faça parte de algum grupo diverso, pedimos que faça seu cadastro nesta vaga.

#### Qual é o perfil de Desenvolvedor(a) Full Stack JR?

Perfil dinâmico, pró-ativo, auto gerenciável, comprometido e em constante aprendizado. Terá atuação importante em projetos de diversos portes, para grandes clientes da NZN, e o compromisso com os prazos e entendimento das demandas é essencial.

Muita disponibilidade para interagir com o time, aprender, compartilhar conhecimento, usar a criatividade em brainstorms e agilidade nas tomadas de decisão técnicas para não bloquear as entregas do projetos

## Local

Remoto ou Curitiba.

#### O que o(a) Desenvolvedor(a) Full Stack JR faz na NZN?

- Desenvolve plataformas e serviços na área de conteúdo para web;
- Faz manutenção e melhorias em projetos já existentes;
- Acompanhamento das entregas monitorando desempenho da aplicação;
- Enxerga oportunidade de aprimoramento a cada novo projeto;
- Desenvolve integrações com APIs e ambientes em nuvem;
- Corrige eventuais bugs e propõe evolução de software;
- Trabalha em uma equipe multidisciplinar, com Product Manager, Product Design, Customer Success, além de outros desenvolvedores.

#### O que o(a) Desenvolvedor(a) Full Stack JR traz em sua mochila para a NZN?

- Experiência com desenvolvimento de sistemas: .NET Core, Node.js;
- Conhecimento em frameworks e bibliotecas: angular, react native e react;
- Conhecimento em arquitetura de microserviços;
- Experiência em desenvolvimento web: HTML, CSS;
- Experiência em bancos relacionais e não relacionais: Sql Server, Mysql, MongoDB.

## Benefícios da NZN

- Assistência Médica Seguros Unimed - Apartamento com extensão para dependentes legais e com a possibilidade de consultas online durante a pandemia;
- Assistência odontológica Metlife com extensão para dependentes legais;
- Vale Refeição ou Vale Alimentação – ambos sem desconto em folha;
- Auxílio creche;
- Seguro de vida;
- PLR;
- Horário flexível;
- Política de Aprimoramento (ajuda de custo em cursos, treinamentos e livros);
- Home Office até que o retorno para os escritórios seja seguro.

#### Durante o período de Home Office devido à pandemia de COVID-19, a NZN garante aos colaboradores:

- Notebook, periféricos e empréstimo de cadeira da empresa;
- Testes rápidos de COVID-19 disponíveis semanalmente e utilização de Uber corporativo para eventual necessidade de ida ao escritório;
- Opção de crédito de VR ou VA em folha de pagamento.

#### Ao retomarmos à rotina no escritório, o colaborador também poderá contar com:

- Vale Transporte com desconto de 1% na folha de pagamento;
- Pães, frios, cereais, café e frutas à vontade;
- Desconto em restaurantes próximos;
- Ajuda de custo com mensalidade de qualquer academia;
- Happy Friday – evento com um almoço todo especial oferecido mensalmente.

## Contratação

CLT a combinar

## Como se candidatar

Aplique-se através do link: [https://nzn.gupy.io/jobs/963687](https://nzn.gupy.io/jobs/963687
)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Júnior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
