### ISSUE TITLE
[São Paulo] Front-End Developer na EcoStage

### ISSUE THREAD

**Issue by mpivaa** [frontendbr/vagas#509]
## Descrição da vaga

Buscamos developers apaixonados por tecnologia e trabalhar com o que há de melhor, pessoas que queiram crescer e aprender com a gente.

Temos um time de alto nível, nosso stack é moderno e está sempre em constante evolução. Valorizamos o desempenho e comprometimento da equipe.

## Local

Presencial - Próximo à Av. Paulista (Ao lado da estação brigadeiro)

## Benefícios (CLT)

- VR
- VT
- Plano de saúde

#### Diferenciais

- Horários flexíveis
- Ambiente descontraído
- Possibilidade de home office alguns dias da semana

## Requisitos

**Obrigatórios:**

- Experiência com desenvolvimento Javascript(ES6)
- React / Redux
- TDD
- Ser comprometido com o projeto e a qualidade do código.
- Espírito empreendedor e pró-atividade
- Experiência com times auto-gerenciáveis e metodologias ágeis (XP, SCRUM, Kanban, Lean).

**Desejáveis:**

- Ruby ou Elixir
- Functional & Reactive Programming

**Diferenciais:**

- Participar da comunidade open source

## Contratação

PJ ou CLT

## Nossa empresa

A EcoStage é líder no desenvolvimento de plataformas sócio-ambientais. Nossos projetos têm grande impacto em políticas e estratégias sobre o tema.

Somos uma empresa com ambiente descontraído e horários flexíveis. Você trabalhará em uma equipe pequena, multi-disciplinar e auto-gerenciável.

## Como se candidatar

Através do link: https://ecostage.breezy.hr/p/e599e2233364-desenvolvedor-front-end

**Comment by simaodeveloper** [comment]
@mpivaa quais as labels? E uma dica, acho que Elm deveria estar em desejáveis, me parece algo muito recente e galera pode aprender codando.

**Comment by mpivaa** [comment]
@simaodeveloper PJ, CLT, Alocado, Pleno e Sênior.
Ali seria `ou`, vou alterar para deixar mais claro.

**Comment by paulo70** [comment]
@mpivaa A vaga ainda está aberta?

**Comment by mpivaa** [comment]
@paulo70 Sim, ainda está aberta.
