### ISSUE TITLE
[Remote/Florianópolis] Front-end Developer at Brick Abode

### ISSUE THREAD

**Issue by rodrigodmartinez** [frontendbr/vagas#5090]
> Vaga Remota durante a pandemia

## About Brick Abode

Brick Abode believes in software engineering: validating with the client that we are building the right thing, and then using the best tools from computer science to verify that our solutions are correct. This is why we are so dedicated to functional programming, automated testing, and paying our people very well.

Our founder, Todd Lewis, had a multi-decade career in investment banking and information security in New York and Singapore. He came to Brazil because he was convinced that we have some of the best talent in the world, and our rapid growth since then suggests that he was right!

Our growth allows us to find and bring in the very best programmers in Brazil. People who want to build great solutions and use the very best systems to do so. Tools like type theory, reactive programming, automated testing, and rock-solid transactional integrity for distributed systems. We don't think you'll find better pay or more personal growth as a developer anywhere else in Brazil, and we hope that you'll join us.

## About the job

We are looking for a senior front-end engineer to help us build scalable React applications.  Clients served by this team include an online marketplace that has moved more than $90M in sales.

In your day-by-day, you will work with the product, design, and engineering teams to plan and implement new features, evolve the software, and guide less-experienced developers. The team is Brazil and USA based, and all communication is in English.

## Location

Remote work from anywhere in Brazil; coworking space is available in Florianopolis, SC.

## About you
- Loves programming
- Communicates clearly and effectively
- Takes initiative to talk and contribute on meetings where new features are discussed
- Is (at least partly) self-taught - learn by reading and from online materials
- Wants to to grow as a technologist and knows that hard work is necessary to do so 
- Can read, write, understand, and maintain a conversation in English

## Minimum Qualifications
- JavaScript experience, including React, testing, and concepts like asynchronous programming, types, and ES6. Experience with Cypress and Jest are a bonus
- HTML/CSS experience, including concepts like layout, specificity, and open graph
- Client-server communication experience, including REST APIs and WebSockets. Experience with GraphQL and SSR are bonus

## Preferred Qualifications
- BS/MS in Computer Science or a related technical field
- 3+ years of experience as a front end developer
- DevOps experience, including CI/CD pipelines and PaaS/CaaS providers

## Benefits
- Work with international clients
- Opportunity for growing as a leader
- Possibility to move between teams
- Speak in English with your coworkers
- 2 weeks of vacation per year
- National holidays
- Parenthood leave
- Working with a company that cares about our people and their personal growth
- Reimbursements for online courses
- Remote work
- Attractive salary

## Interested?
Send an email to jobs@brickabode.com with the subject: "[Application] Senior Front End Developer (React) - yourNameHere" and all available information below:

1. Link to your LinkedIn and GitHub profiles
2. Link to projects from your portfolio and articles you have written
3. Describe the most challenging project from your career so far

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
