### ISSUE TITLE
[100% REMOTE] Front-end Developer @ Prediktive

### ISSUE THREAD

**Issue by majobonel7** [frontendbr/vagas#5091]
We are looking for a **  Developer** based in **Latin America** to work on a long-term project for one of our clients, an internet company that empowers organizations to fully personalize and integrate their -to- digital workplace, based on the East Coast, US.

Our client is an experience-focused enterprise solution that provides a rich and engaging employee experience through personalization, campaigns, marketing, analytics, and omni-channel capabilities.

The person in this role will work along with the   Lead, QA and Client Success team, towards creating components using a set of predefined blue prints.

**Responsibilities**
- Build new features
- Maintain our client's employee experience for their digital workplace

**Requirements**
- Advanced Level of English
- 5+Years of experience building web applications using , , , 
- 5+Years of experience working with  frameworks like 
- Strong understanding of  tooling like webpack, babel and gulp
- Experience developing multiple large production applications using modern  and web development technologies
- Experience writing extensive web applications with complex dependencies and infrastructure
- Excellent understanding of  performance
- Excellent communication skills
- Solid grasp of  and related tools

**Bonus Points**
- Bachelor’s Degree in Computer Science, Systems Engineering or related fields
- Experience with 

**What we Offer**
- Long term positions
- Work from anywhere in the world
- Compensation in USD
- Paid time off
- Cool clients and products
- Work with great engineers
- Once-a-year trips to the US to meet your team 

### If you’re fluent in English create your profile here https://bit.ly/3pRBi6B
**Please include my name, Maria Bonel, when applying and I'll get back to you as soon as possible!**

**#RemotePosition #FrontEndDeveloper #HTML #CSS #Javascript #Bootstrap #Sitecore**

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
