### ISSUE TITLE
[Remoto] Front-end Developer (Designer) na Maxihost

### ISSUE THREAD

**Issue by claudiafeijo-hr** [frontendbr/vagas#5097]
We believe there is a better way to work with technology. By building cutting-edge internet infrastructure products, our goal is to help make the internet faster and safer. That is why we take a different approach to infrastructure.

Our automated platform combines the flexibility of bare metal with the automation capabilities of the cloud, allowing our customers to deploy a dedicated server in minutes across different locations around the world.

Despite having several technical features and differentiators, we know that what makes our products and services great is our team and the people behind every single one of our achievements. Based on that, talent is something we are always looking for.

**Frontend Development and Design at Maxihost**

At Maxihost, we are passionate about making the cloud more straightforward and faster. We work at the physical infrastructure layer, building products and solutions that automate the deployment and management of bare metal servers.

We don’t use strict methodologies or copy industry standards. We’ve created our own workflow, which allows us to work calmly and productively. This workflow is public and can be found [here](https://www.notion.so/How-we-work-51df61186a924e97ad4c05a4a5106c96).

We work in an agile and highly collaborative environment, with many members of the Engineering team working remotely. You will also have the option to work from our offices in São Paulo or Florianópolis.

**About the team and role**

We love building beautiful, accessible, and intuitive experiences, mostly for our [website](https://www.maxihost.com/) and dashboards. We are now working on a whole new dashboard experience, which will completely change how customers interact with our product. While at it, you will also have the opportunity of working on open-source projects like [Metal UI](https://github.com/maxihost/metal-ui).

You might be a fit for this role if you consider yourself an enthusiastic and resourceful **Front-end Developer, with a background in design**, and passionate about building great products. We expect that you love being part of a team, whilst enjoying the autonomous nature of working remotely.

Also, we're looking for someone who wants to shape and determine how the different assets of the Maxihost brand will look now and in the years to come, and delivers exceptional experiences. So, that's why the so the job requires expertise in UX, UI, and front-end development (Javascript/React). 

**About the job**

We are getting ready for some significant changes, and you will be leading those efforts to make sure that when it's time to shake things up, we have a concise and robust brand supporting that.

- You will make Metal UI, our Design System, the backbone of Maxihost's design. Your responsibilities here reside in working alongside frontend engineers to extend and improve Metal UI.
- You will lead the design efforts of our new dashboard by prototyping, coding, and guiding the Engineering team on the user experience and interface.
- Sometimes work on very broadly defined, loose concepts, and sometimes on narrowly defined, tactical deliverables.
- Participate in design reviews and share your work regularly with the company leadership.
- Understand the array of technical constraints, user goals, and business requirements that shape a product.

**You might be a fit for this role if**

- You love giving simple solutions to challenging problems and cringe at complex and confusing products.
- A good understanding of the formal elements of design, not just limited to the web and including typography, layout, balance, and proportion.
- Have experience in UI, UX, or visual design
- Have experience with web front-end development or creative technology experience.
- You have led or was an instrumental part of the design process of a consumer or enterprise product used at scale.
- You have experience building React components and can collaborate by coding the development of high-fidelity prototypes in production-grade code.
- You care about details and are excited to keep pushing your work until it is pixel-perfect.
- Bonus points if you have worked at a known startup before.

[Please include a link to your design or code portfolio with your resume. ](https://www.maxihost.com/careers?jobId=7qLfgHbSSzkN&ft_source=Github_4000128629&ft_medium=Free%20Advertisement_4000121128)

---------------------------

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

Enviar o currículo + portfolio através [deste link](https://www.maxihost.com/careers?jobId=7qLfgHbSSzkN&ft_source=Github_4000128629&ft_medium=Free%20Advertisement_4000121128).

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
