### ISSUE TITLE
[Remoto] Front-end Developer Pleno & Sênior na Redspark | Vagonetas

### ISSUE THREAD

**Issue by maiconkf** [frontendbr/vagas#5098]
## Nossa empresa

A redspark é um grupo empresa que a 10 anos cria experiências em produtos e projetos digitais alinhando tecnologia e design.

Com cases de projetos em empresas como Hospital Albert Einsten, Sesc, Claro, Banco Mercedes Benz. Buscamos sempre a inovação com a perspectiva de construir soluções que sejam aderentes aos negócios e principalmente desejável para as pessoas.

## Descrição da vaga

Exemplo: Projeto bazinga em NodeJS, etc.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- React.js e Angular

**Desejáveis:**
- Javascript ES6/ES7
- HTML5, CSS3, PRÉ PROCESSADORES (SASS)
- SPA, DESIGN RESPONSIVO WEB
- NPM, GULP, WEBPACK
- React com Redux
- Styled-components

**Diferenciais:**
- Saber outros frameworks do mercado

## Contratação

CLT a combinar

## Como se candidatar

Preencher o formulário neste link: [Vaga na Redspark via Vagonetas](https://www.vagonetas.com.br/vagas/frontend-pleno-snior--bba3327cb8012535)

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
