### ISSUE TITLE
[Sao Paulo] Sr Full Stack Developer - React

### ISSUE THREAD

**Issue by rturk** [frontendbr/vagas#51]
## Descrição da vaga

We are looking for Software Development Engineers that thrive in fast-paced environments and are passionate about working with pre-market technologies. Successful candidates will be much more than just developers, they will bring with them deep technical fundamentals, experience with complex mobile, distributed systems, and a well-rounded software engineering background that spans disciplines.

We are looking for a Sr. Developer that will help us with our international expansion.

## Location

Escritório, São Paulo - Zona Sul
http://plug.co/bkln

## Perks

- Cool working place
- Open schedule. Just deliver your code and you're done
- Based in São Paulo - Zona Sul

## Mandatory Qualifications

- BA/BS in Computer Science or related discipline, or equivalent work experience.
- Strong skill in Javascript, NodeJS, CSS, Less, React.
- 5+ years of software development experience
- Fluent in English 

## Expected qualifications 

- Some sort of design skills
- Comfortable in fast-paced, start-up like development environments.
- Experience in software development on devices/products in real-time operation system.

## Contratação

Full time employee

## About us

Entria (https://www.entria.com.br) is a leading Mobile Provider. We make really cool apps
We manage complex projects, and yes we deliver.

## How to apply for this job

Just drop us a note at rh@entria.com.br please attach CV our link to github projects, previous projects

**Comment by LFeh** [comment]
Good luck!

**Comment by rturk** [comment]
closed! Team Hired via this forum! Amazing!!

**Comment by LFeh** [comment]
Awesome! :smile:

**Comment by idlua** [comment]
Awesome!!² 🎉
