### ISSUE TITLE
[São Paulo] Front-end - Freela/Tempo indeterminado - SP/Butantã - CarGuru

### ISSUE THREAD

**Issue by juulhao** [frontendbr/vagas#510]
## Descrição da vaga

Novo App em Ionic (uso interno)

## Local

Local - Butantã (5 mins do metrô Butantã)

## Benefícios

- Freela mas com direito a café, lanchinhos e tudo mais.

## Requisitos

**Obrigatórios:**
- Conhecimento mínimo em IONIC;
- Js
- CSS (Muitas telinhas pra seguirmos a risca o proposto pelo UX)
- GIT

**Desejáveis:**
- Angular 4
- SASS

## Contratação

Freela a combinar!

## Nossa empresa

Startup em lavagem e outros paranauês de carros.

## Como se candidatar

Por favor envie um email para jrodrigues@carguru.com com seu CV anexado - enviar no assunto: Vaga FRONT

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
