### ISSUE TITLE
[Niterói] Front-end Developer na Internit

### ISSUE THREAD

**Issue by Fredpeixoto** [frontendbr/vagas#5100]
> Vaga Remota durante a pandemia

## Nossa empresa
A Internit é empresa localizada em Niterói que há 24 anos desenvolve sistemas, sites, lojas virtuais, portais e intranets .

## Descrição da vaga
Estamos abrindo 2 vagas de estágio remunerado para Front-end para desenvolvimento e manutenção dos projetos da empresa para clientes como a Gafisa, Mozak, Accor, dentre tantas outras empresas de grande, médio e pequeno porte.

## Local
Pós pandemia 2 dias remoto e 3 dias no escritório, [RJ], [Niterói].

## Requisitos

**Obrigatórios:**
- Vivência em Html, CSS, Java Script com JQuery e implantação de sites em Wordpress. 
- O candidato deve estar na faculdade. 
- O candidato deve ter seu currículo cadastrado no nosso site.

## Benefícios
- Bolsa
- Passagem
- Seguro contra acidentes pessoais

**Diferenciais da empresa:**
Ótimo ambiente de trabalho somado à desafios constantes.
Durante a pandemia, somente vai ao escritório quem se sentir à vontade. Depois da pandemia, possibilidade de trabalhar 2 dias na semana de home office e 3 dias na empresa.
Estamos situados em Niterói em uma rua tranquila do bairro de Santa Rosa, com facilidade de estacionamento além de termos um bicicletário na empresa.

## Como se candidatar

Se tiver interessado e se encaixa nos requisitos acima, gostaria que acessasse https://internit.com.br/curriculo e cadastrasse seu currículo.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 30 dias após cada processo.
E-mail para contato em caso de não haver resposta: vagas@internit.com.br

#### Regime
Estágio

**Comment by joao160197** [comment]
Necessário estar cursando faculdade ?

**Comment by Fredpeixoto** [comment]
Oi João,

Para vaga de estágio sim. Mas se você não estiver na faculdade, você pode
se cadastrar no nosso site. Assim, quando tivermos uma vaga que não seja de
estágio, contactamos você.

Abs

*www.internit.com.br
<https://mailtrack.io/trace/link/913e2b9900557a96a7da5a0cfa1051b0b7a3c7ec?url=http%3A%2F%2Fwww.internit.com.br%2F&userId=393368&signature=296b852ef8dc26d5>www.incenadigital.com.br
<https://mailtrack.io/trace/link/8e3fcd714754ca8708e7d8886e27a1b015eee376?url=http%3A%2F%2Fwww.incenadigital.com.br&userId=393368&signature=db2ba1c0ad898956>*

[image: Internit]
*Frederico Peixoto*
Diretor Comercial
***@***.*** ***@***.***>
(21) 2621-7788 | (21) 98123-2303
[image: Acompanhe a Internit no Facebook]
<https://mailtrack.io/trace/link/253a1b6a8a61ce85f3eb89e458b2d47076e9d92c?url=http%3A%2F%2Fwww.facebook.com%2Fsejainternit&userId=393368&signature=988aba04a5383d1e>
[image:
Siga a Internit no Linkedin]
<https://mailtrack.io/trace/link/98df197f3961ec21f8306a6addf9c8e5ff624af6?url=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F3283804%3Ftrk%3Dtyah%26trkInfo%3Dtas%253Ainternit%2520LTD%252Cidx%253A1-1-1&userId=393368&signature=8767cf7f11be3668>


Em ter., 29 de jun. de 2021 às 17:00, 'joao160197' via Vagas <
***@***.***> escreveu:

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
