### ISSUE TITLE
[Remoto] Angular Developer na Zup Innovation

### ISSUE THREAD

**Issue by vgsants** [frontendbr/vagas#5101]
## Nossa empresa

Nós criamos tecnologia!
Desenvolvemos uma stack de tecnologia para melhorar a developer experience, facilitando e diminuindo o tempo entre a concepção de uma ideia e o código em produção. Trazendo ainda mais eficiência para profissionais de desenvolvimento e times de tecnologia.
O sucesso de qualquer empresa no mundo digital, seja uma startup ou de grande porte, está ligado com a sua capacidade em ser ágil para colocar produtos no ar, pivotar uma estratégia, adicionar features e atender bem seu cliente, e é claro mantendo a segurança necessária.
Nosso foco é desenvolver tecnologia para apoiar nossos clientes com essas estratégias. Mais do que isso, nosso propósito é transformar o Brasil em um polo de tecnologia global.

## Descrição da vaga

Atuação em projeto com Angular 11

## Local

Full remoto.

## Requisitos

**Obrigatórios:**
Experiência em Typescript;
SASS/LESS;
Bower
NPM

## Benefícios

💰 - PLR
💊 - Plano de Saúde SulAmérica
🦷 - Plano Odontológico SulAmérica
🍝 - VR/VA Flash R$1045,00
📚 - Capacitação anual (Ajuda de custo)
📱 - Plano de celular
🏡 - Auxílio Home Office
👶 - Auxílio creche
⭐ - Seguro de vida
💪 - Gympass
💵 - Bônus por indicação
🏖️ - Liberdade para trabalhar de onde quiser
🍻 - Happy Hours e Confraternizações
🔀 - Trilha de Carreira em W
👨‍🦽 - Diversidade e Inclusão
✅ - Telavita (psicólogo online)

## Contratação

CLT

## Como se candidatar

Podem me chamar no LinkedIn: https://www.linkedin.com/in/vit%C3%B3ria-gomes-santos/ ou enviar CV para vitoria.santos@zup.com.br

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias úteis após cada processo.

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
![Apresentação sem título](https://user-images.githubusercontent.com/70250442/122218000-56ab3d80-ce84-11eb-9ae5-cd2b3b6b0ad0.jpg)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
