### ISSUE TITLE
[Remoto] Fullstack Javascript Developer na Associação Brasileira de Startups (Abstartups)

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#5102]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/fullstack-javascript-developer-185707799?origin=github&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Nós, da Abstartups, acreditamos que as Startups são o futuro e a nossa missão é apoiar e fomentar esse ecossistema de inovação! Estamos sempre em busca do melhor para o ecossistema, pensando “fora da caixa”, tendo muita autonomia e obstinados, somos promotores de mudanças e adoramos desafios!</p>
<p>Como fazemos isso dentro da nossa área de PRODUTO:</p>
<p>Essa área tem como missão, ajudar o time e a empresa a entregar o produto certo para seus usuários. Acompanhar e executa projetos de desenvolvimento de produtos, cronogramas e lançamentos.</p>
<p></p>
<p><strong>Como será seu dia a dia?</strong></p>
<ul>
<li>Responsável por influenciar e gerir o processo de desenvolvimento de um ou mais produtos da empresa;</li>
<li>Priorizar soluções de problemas elaborando soluções escaláveis;</li>
<li>Coordenar a sua equipe usando metodologias ágeis e dividir grandes projetos em lançamentos pequenos e frequentes. Planejar datas de lançamento, documentar as entregas semanais e coletar feedbacks.</li>
<li>Avaliar e analisar a eficiência do seu produto com números de dados, entender o comportamento do usuário e buscar melhoria contínua do produto.</li>
<li>Aplicar a metodologia CLEAN em produtos e eventuais soluções.</li>
<li>Alinhar os objetivos estratégicos / KPIs da empresa com as necessidades dos usuários (internas e externas);</li>
<li>Estar antenado no ecossistema de produtos digitais e realizar benchmarks;</li>
<li>Garantir as entregas do produto no melhor ritmo possível, equilibrando o fator tempo e qualidade;</li>
<li>Elaborar conceitos de interface garantindo uma boa experiência para o usuário;</li>
<li>Integrações com multiplataformas;</li>
<li>Monitorar e melhorar a plataforma e a performance das nossas APIs;</li>
<li>Garantir segurança das aplicações e adequações a LGPD;</li>
<li>Criar e implementar arquiteturas eficientes;</li>
<li>Gerir squads;</li>
<li>Estar antenado ao ecossistema de startups e as tendências do mercado para conhecimento das necessidades e aplicação do público-alvo;</li>
</ul>
<p><strong>Ser capaz de liderar e ajudar no desenvolvimento do seu time, queremos crescer juntos!</strong></p>

## Associação Brasileira de Startups (Abstartups): 
 <p>Na Abstartups, acreditamos na força da diversidade para gerar Inovação e Impacto, por isso, não fazemos distinção para candidatos com deficiência, gênero, orientação sexual, raça/etnia, idade, origem, constituição familiar e estética. Todos são bem vinde!! #AllTogether</p>
<p>Quer ajudar fomentar a inovação Brasileira?</p><a href='https://coodesh.com/empresas/abstartups'>Veja mais no site</a>

 ## Habilidades: 
 - HTML 5 
- React.js 
- React Native 
- CSS 3 
- Node.js 
- Rest API 
- SOLID 
- Design UI 
- Design UX
## Local: 
 100% Remoto
## Requisitos: 
 - Conhecimento em conceitos de UX e UI 
- Conhecimento de métricas de produto 
- Boa resolução de problemas e priorização de atividades 
- Conhecimento em ferramentas de monitoramento de análise de dados 
- Boas práticas de OO (Orientação a Objetos), design patterns, refatoração e princípios de design (como SOLID); 
- Conhecimentos em programação funcional; 
- Construção de APIs REST; 
- Bancos de Dados (MySQL e NoSQL) 
- JavaScript (Es5 *>) Typescript - ReactSJ , ReactNative e NODEJS; 
- Conhecimento sólido de HTML5, CSS3; 
- Conhecimento em NODEJS - Serverless e ExpressJS 
- Conhecimentos em Github;
**Diferenciais:** 
 - Conhecimento sólidos em arquitetura de soluções AWS; 
- Experiência com metodologias ágeis (Scrum, Kanban)
## Benefícios: 
 - 100% remota
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack Javascript Developer na Associação Brasileira de Startups (Abstartups)](https://coodesh.com/vagas/fullstack-javascript-developer-185707799?origin=github&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção <b>Pedir Feedback</b> entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa <b>Recruiter</b> responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Nível
Pleno
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
