### ISSUE TITLE
[Remoto] Front-end Vue.js Developer na Weni

### ISSUE THREAD

**Issue by dyohan9** [frontendbr/vagas#5107]
## A WENI
Nascemos Ilhasoft e nos unimos às marcas dos produtos Push e Bothub para formarmos Weni. Atuamos desde 2012, com o propósito de otimizar serviços e causar impacto social por meio de tecnologias inteligentes e intuitivas que se adequem às necessidades de organizações dos mais variados segmentos.

Queremos fazer a diferença na vida das pessoas, levando a transformação digital para os lugares mais remotos do mundo.

Conheça os nossos produtos!

- Weni Plataforma

A Weni Plataforma é uma ferramenta intuitiva para a criação de chatbots robustos que demandam integrações e inteligência artificial complexas. Os chatbots Weni são personalizados e facilmente integráveis a outros sistemas por meio de API.

Esta é a ferramenta ideal para automatizar e gerenciar crises na comunicação de empresas, governos e ONGs.

Nossa plataforma tem o poder do Weni NLP, sistema de processamento de linguagem natural, campo da Inteligência Artificial responsável por fazer com que as máquinas compreendam as intenções das pessoas através do treinamento de frases.

- Weni WhatsApp Business

Oferecemos integração oficial com a API do WhatsApp Business.

- Integração com sistemas de atendimento

Integramos uma plataforma que conecta o atendimento humano a diversos outros sistemas para otimizar a comunicação das organizações internamente e com o público.

## Descrição da vaga

Como Pessoa Desenvolvedora Front-End, você terá como missão desenvolver aplicações, features ou resolver bugs de aplicações mantidas pela Weni. Irá definir a arquitetura e funcionalidades das aplicações, nos ajudando nas principais decisões técnicas e seus impactos no produto no médio/longo prazo.

Uma semana comum conosco pode incluir sprint planning, sprint review, revisão de código do time, tech talks e execução de tasks.

No fundo, nós queremos você no time para:

Crescer conosco à medida que desbravamos novos projetos
Ter orgulho do trabalho que desenvolve
Melhorar a cada dia
Ter a certeza de ter contribuído para problemas de nossos clientes após um dia de trabalho desafiador
Ajudar todos seus colegas de trabalho a completar o check list acima

Vem com a gente!

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência com HTM5, CSS3 e Javascript
- Experiência com Frameworks Javascrit (Vuejs)
- Experiência fazendo build/deploy de aplicações frontend
- Conhecimento prévio com JWT
- Conhecimentos de REST API
- Conhecimentos de Testes unitários
- Experiência com State Management - Vuex
- Experiência com git
- 2+ anos de experiência em desenvolvimento de software front-end
- Nível de Inglês Intermediário

**Diferenciais:**
- Já tiver trabalhado com projetos open-source
- Já tiver conhecimento em Micro Frontend
- Estar cursando ou ser graduado em Análise de Sistemas, Ciências da Computação, Engenharia da Computação ou áreas afins
- Já tiver trabalhado num time ágil

## Benefícios

- Plano de saúde
- Vale Alimentação ou Refeição

**Diferenciais:**
- 2 horas de almoço

## Contratação

CLT ou PJ a combinar

## Como se candidatar

https://weni.gupy.io/jobs/934778

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
