### ISSUE TITLE
[São Paulo] Front-end Developer na Spread Tecnologia

### ISSUE THREAD

**Issue by milenavieira554** [frontendbr/vagas#5108]
• Capacidade de propor e construir soluções criativas de Font-end para atender aos requisitos definidos pelo Product Owner;
• Javascript;
• ReactJS;
• Utilização de APIs REST;
• Testes unitários;
• CSS;
• Algum State Manager (Mobx, Redux etc.);
• Git;
• Trabalho em equipe ágil.
Requerimentos Técnicos
• Typescript
• Material-UI
• Vivência com Hooks
• GraphQL
• Apollo
• React Testing Library
• Arquitetura Monorepo
• JSX
• Conhecimentos da cultura DEVOPS (CI / CD - Jenkins, Pipeline scripts)

São Paulo, Remoto

## Benefícios

- Plano de saúde
- Plano Odontológico
- GymPass
- Seguro de vida
- VR de R$ 19,45 por dia 
- Auxílio creche
- Auxílio Home Office 

## Contratação

CLT -  valor a combinar

## Como se candidatar

Por favor envie um email para milena.vieira@spread.com.br com seu CV anexado - enviar no assunto: Vaga React

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by Kaedh** [comment]
Enviado

**Comment by joao160197** [comment]
Ainda está aberta ?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
