### ISSUE TITLE
[Vitória - ES] Front-End Developer na Eventplace

### ISSUE THREAD

**Issue by LeandroSNunes** [frontendbr/vagas#511]
## Descrição da vaga

A vaga está aberta para pessoas apaixonadas por tecnologia e que tenham vontade e motivação para participar do crescimento de uma startup que busca melhorar o setor de realização de eventos, pessoas que queiram crescer e aprender com a gente em um ambiente de grandes oportunidades de crescimento profissional e aprendizado.

## Local

Presencial - Av. Reta da Penha em Vitória - ES

## Benefícios
- VR
- VT

#### Diferenciais
- Horários flexíveis
- Ambiente descontraído

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento Javascript(ES6)
- Conhecimentos de PWA
- Conhecimentos de Vue.js
- HTML, CSS

**Desejáveis:**
- conhecimentos em ruby on rails

**Diferenciais:**
- projetos opensource

## Contratação
- CLT

## Nossa empresa

Queremos que você faça seu evento sem preocupação e sem complexidade. Por isso, estamos criando uma plataforma inovadora para digitalizar o mercado de eventos. Nela, reuniremos os espaços, fornecedores e produtores de eventos para te ajudar a fazer a escolha ideal para sua festa com praticidade, qualidade e segurança.

Não importa o tipo de evento que você quer realizar, nossa ferramenta será fundamental para tornar seu sonho possível, dentro do orçamento que você planejar e tornando sua experiência prática e inesquecível.

## Como se candidatar

Por favor envie um email para dev@eventplace.me com seu CV anexado - enviar no assunto: Vaga Front-End Developer

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by LeandroSNunes** [comment]
@LFeh no momento não!
