### ISSUE TITLE
[Remoto] Front-end Developer na SIS Consultoria | Vagonetas

### ISSUE THREAD

**Issue by maiconkf** [frontendbr/vagas#5111]
## Nossa empresa

A SIS Consultoria é uma empresa provedora de serviços e soluçoes integradas de sistemas, alinhadas com as principais estratégias corporativas através de uma equipe altamente qualificada. Nossa experiência e comprometimento traduzem o alto nível de satisfação e reconhecimento dos nossos clientes.

## Descrição da vaga

Estamos com vaga para desenvolvedor Front-End com React Web e/ou React Native

## Local

Exemplo: Remoto

## Requisitos

**Obrigatórios:**
- React
- Redux
- Redux-Saga
- Typescript

**Diferenciais:**
- 100% Home-office

## Contratação

7 a 9k PJ

## Como se candidatar

Preencher o formulário neste link: [Vaga na SIS Consultoria via Vagonetas]( https://www.vagonetas.com.br/vagas/frontend-developer-pleno-react-web-eou-native-abd45c1129cfbf62)

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
