### ISSUE TITLE
[Belo Horizonte] Front-end Developer na Rosso Consultoria

### ISSUE THREAD

**Issue by Priscilagraziela** [frontendbr/vagas#5112]
> Vaga Remota durante a pandemia

## Nossa empresa

Somos uma empresa líder de mercado em soluções de empregabilidade. Ajudamos as empresas a encontrarem talentos, ajudamos as instituições de Ensino Superior a preencherem as lacunas de habilidades e ajudamos recém-formados a iniciarem suas carreiras. Utilizado por mais de 30 milhões de estudantes em todo o mundo, nosso abrangente conjunto de produtos toca o ciclo de vida completo de um aluno: desde a admissão até o envolvimento de ex-alunos, nossos produtos abrangem serviços de carreira, aconselhamento, conduta dos alunos e vida no campus.

Somos certificados Great Place To Work.

## Descrição da vaga
- Nossa equipe de projeto desenvolve pesquisas centradas no usuário, design de experiência e desenvolvimento de interface do usuário em estreita colaboração com equipes de gerenciamento de produto, engenharia, sucesso do cliente e vendas.
- Ser responsável pela interface e experiência do usuário.
- Desenvolver a interface do produto com o uso de HTML, CSS / SASS, JavaScript.
- Contribuir para a criação e manutenção de documentação para sistemas de design em suporte a desenvolvedores das equipes de toda a empresa;
- Pesquisar e recomendar o uso de componentes e bibliotecas de software livre que atendam às especificações da interface do usuário;
- Codificar experiências de usuário universalmente acessíveis que sejam compatíveis com WCAG 2.0 AA;
- Realizar o desenvolvimento orientado a testes.

 
## Local

 Temporariamente remoto devido a pandemia da Covid-19 [Belo Horizonte]

## Requisitos

**Obrigatórios:**

- Formação superior concluída no curso de Ciências da Computação, Sistemas de Informação, Engenharias ou área afim;
- Experiência de mercado no desenvolvimento de Web ou UI;
- Habilidade em HTML / CSS, JavaScript;
- Conhecimento de Angular e controle de versão (preferencialmente Git);
- Experiência anterior em equipes de desenvolvimento de produtos em um ambiente Ágil;
- Inglês para colaboração com membros de nossa equipe de design dos EUA.

## Benefícios

- Plano de Saúde Allianz (cobertura nacional, apartamento, sem coparticipação - extensível a cônjuges e filhos)
- Plano odonto (sem  coparticipação - extensível a cônjuges e filhos)
- Vale Alimentação ou Refeição via Sodexo - R$600,00 por mês
- Vale Transporte ou Vale Gasolina - com desconto de 6% em folha
- Ginástica Laboral
- GymPass
- Programa de Inglês - sem descontos
- 40 horas semanais flexíveis
- Birthday Off

## Contratação
CLT a combinar

## Como se candidatar

Por favor envie seu currículo para vagas@rossoconsultoria.com.br com - enviar no assunto: Vaga Desenvolvedor Front-End

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by Priscilagraziela** [comment]
Vaga encerrada

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
