### ISSUE TITLE
[SALVADOR-BA] Front-end Developer (UI/UX) na Bloxs Investimentos

### ISSUE THREAD

**Issue by lucasayres** [frontendbr/vagas#5113]
## Nossa empresa

A Bloxs é uma fintech de investimentos alternativos! Estamos crescendo de forma acelerada e queremos que você venha participar disso!

Nascemos com o intuito de democratizar o acesso ao mercado de capitais para empreendedores e para os investidores.

Saiba mais em: https://bloxs.com.br

## Descrição da vaga

A Bloxs busca um(a) desenvolvedor(a) Front-End - UI/UX para atuar na nossa Plataforma de Investimentos. Desenvolvimento sistemas Web com foco em layout e experiência de navegação do usuário.

## Local

Salvador - BA
Remoto

## No dia a dia seus desafios serão

- Trabalhar em parceria com outras áreas da empresa, Produto, Comercial, para garantir que o produto seja o melhor possível para nossos investidores;
- UX/UI - Como você irá trabalhar no “Front” dos nossos produtos, procuramos pessoas que consigam dar sugestões construtivas de melhorias de experiência do usuário.
- Criação de POCs (provas de conceito) para validar ideias para implementação no produto;
- Realizar prototipações e validações
- Aplicar melhores práticas de documentação de código desenvolvido;
- Buscar novas ferramentas e técnicas para a melhoria contínua do produto;
- Realizar análises técnicas para propor as melhores soluções para o produto;
- Participar de reuniões com o time de produto para definição de boas práticas de design, usabilidade e interações;
- Colaborar com a execução e sugerir melhorias nos nossos processos ágeis;

## Esperamos que você

- Tenha pró atividade em trazer ideias novas e ao mesmo tempo ter um senso de dono do negócio
- Queira aprender sempre e saia da zona de conforto;
- Identifique e implemente melhores e mais atuais práticas de desenvolvimento, frameworks e tecnologias web, e disseminá-las no time;
- Colabore na definição de padrões a serem seguidos pelo time Front-end;
- Saiba criar Wireframes
- Esteja atento ao design, acessibilidade e desempenho.
- Tenha experiência com ferramentas como Figma
- Tenha conhecimento em HTML, CSS, Sass, JavaScript, Bootstrap..
- Possua experiência com algum framework para desenvolvimento frontend (Angular/React/VueJs/Bootstrap..);
- Tenha conhecimento com versionamento de código (GIT);
- Tenha experiência em times com processos ágeis (SCRUM, OKRs, Daily..);
- Desenvolva códigos elegantes, estáveis, confiáveis e fáceis de manter;

## Diferenciais

- Desenvolvimento mobile (React Native)
- Experiência com a implementação e manutenção de design systems;

## Vantagens e benefícios

- Contratação CLT
- Horário flexível e banco de horas;
- Vale-transporte alinhado com a necessidade de cada pessoa;
- Auxílio alimentação;
- Ambiente de startup em crescimento acelerado;
- Acreditamos muito na cultura do Feedback e trabalhamos isso no nosso dia a dia;

## Como se candidatar

Preencha o seguinte formulário da vaga: https://docs.google.com/forms/d/e/1FAIpQLSdcI9jxf4NnYG-b0V0590X4IgPLl9pE-TtkDlLgWI8rDtheIg/viewform

## Labels

- 🏢 Flexível
- 👨 Pleno
- 👴 Sênior
- ⚖️ CLT

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
