### ISSUE TITLE
[Remoto] Front-end Developer Pleno Angular na Trakto

### ISSUE THREAD

**Issue by jorgehsrocha** [frontendbr/vagas#5114]
## Nossa empresa

Olá, nós somos a Trakto (https://trakto.io)! O primeiro editor online da América Latina. Ajudamos o empreendedor a vender mais através da criação de minisites, artes para redes sociais, e-books, e muito mais, com apenas alguns cliques! Fundada em 2013, a Trakto e vem crescendo exponencialmente, fomos a primeira startup do mundo a ter um documentário produzido pelo Google for Startups! E aí? Se interessou? Então vem ser #Trakteiro!  

## Descrição da vaga

Nosso objetivo com você é cuidar do frontend das nossas plataformas de edição e templates na Trakto. Nosso produto envolve muita criatividade e liberdade de criação. Por isso, essas serão algumas das suas responsabilidades: 

- Sugerir e estruturar a arquitetura front-end das nossas aplicações; 
- Sugerir novas ferramentas, tecnologias e arquiteturas que possam melhorar as aplicações e serviços; 
- Componentizar itens de UI e features globais entre as aplicações; 
- Criar testes automatizados de UI a fim de garantir fidelidade para views e experiência de uso; 
- Garantir qualidade de processamento e performance da camada de front-end; 
- Implementação e manter novas e antigas funcionalidades.

## Local

Remoto

## Requisitos

- Experiência com aplicações reativas, uso de controle de estado reativo;
- Pensamento crítico quanto a perfomance de aplicações web e UX;
- Conhecimento em componentização e “npm packages”;
- Experiência com padrões arquiteturais de projeto, como por exemplo DDD;
- Experiência em criação de testes de integração e/ou E2E;
- Experiência com Angular 6 ou superior;
- Domínio do HTML5, CSS3 e JS Moderno (ES6+)/Typescript;
- Conhecimento e uso do GIT;

**Desejáveis:**
- Experiência com aplicações em escala e de alta disponibilidade;

**Diferenciais:**
- Oportunidade de participar da criação de uma plataforma de design;
- Produto em grande escala;
- Componentização de recursos;

## Contratação

PJ a combinar

## Como se candidatar

Por favor, candidate-se em https://jobs.kenoby.com/trakto/job/desenvolvedor-front-end-remoto/60ca80e487279d61384ba0b0

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: marina@trakto.io

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
