### ISSUE TITLE
[Remoto] Front-end Developer Vue.JS  - Pleno e Sênior na ITeam

### ISSUE THREAD

**Issue by VivianeRHTI** [frontendbr/vagas#5115]
## Local

Home Office (Horário comercial)

## Requisitos

Imprescindível domínio de Javascript;
Experiência com o framework Vue.JS, SCSS ou SASS.

## Desejável
Conhecimento em Angular e React;
Experiência com Webpack
Fundamentos sobre experiência de usuário;
Design patterns.

## Contratação

Tempo indeterminado
CLT

## Nossa empresa

Há mais de 15 anos presente no mercado, a ITeam oferece o comprometimento com o cliente.
Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 
O relacionamento da ITeam é baseado no amplo comprometimento com os valores e objetivos dos nossos Clientes, fornecendo soluções e serviços de TI que contribuam para a realização de seus objetivos.

## Como se candidatar

Envie um e-mail para viviane.pereira@iteam.inf.br com seu currículo atualizado e pretensão CLT - enviar no assunto: Vaga no GITHUB - Front Vue.js

## Labels

- 🏢 Horário comercial
- 🏢 Home-Office
- 👨 Pleno e Sênior
- ⚖️ CLT

**Comment by Gabri3el** [comment]
Tenho as experiencias, porém sou junior posso me candidatar ?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
