### ISSUE TITLE
[Hibrido - Brusque] Dev React na Maior Loja de Departamentos do #BRASIL 🗽

### ISSUE THREAD

**Issue by CiciK2607** [frontendbr/vagas#5117]
Estou com uma SUPER oportunidade para atuar como Desenvolvedor React na MAIOR loja de departamentos do #BRASIL 🗽 com um ambiente inovador e transformador 
==================================================

## Descrição da vaga

Se você curte tecnologia, programação e novos desafios a vaga é para você! Somos um time de profissionais voltados para diversas áreas da tecnologia como Data Science, DevOps, User Experience, Database entre muitas outras frentes focadas na inovação digital de uma das gigantes varejistas do Brasil.
Nosso objetivo é desenvolver soluções inovadoras para clientes, fornecedores e os mais de 20 mil colaboradores. Aqui descomplicamos tudo através de uma metodologia ágil e juntos já fizemos acontecer centenas de projetos com reconhecimento nacional e internacional de RFID, Inteligência Artificial, aplicativos entre outros.

## Local

Remoto, mas contamos com um espaço exclusivo no Centro de Inovação, em Brusque (SC).

## Requisitos

**Obrigatórios:**
- ReactTypescript e Javascript
- AJAX e jQuery
- Consumo de APIs 
- REST (Json) e protocolo HTTP
- Git

**Diferenciais:**
- .NET e capacidade de fazer integração de Front End com Back End.

## Benefícios

- Vale refeição ou alimentação - R$410,00 ALELO - desconta 20%
- Ajuda de Custo Home Office - R$100,00;
- Vale transporte - 6% previsto lei
- PPR - anual - corresponde ao 14º salário
- Convênio SESC
- Convênio com escola
- Plano Unimed (Por adesão) - plano regional e nacional - coparticipação de 50%
- Empresa cidadã (licença maternidade de 6 meses e paternidade de 20 dias)
- Banco de horas
- Oportunidades de crescimento

## Contratação

CLT

## Como se candidatar

Por favor envie um email para cintia.kleine@gruposelecionar.com.br com seu CV anexado
Me chame no linkedin [Cintia Kleine](https://www.linkedin.com/in/cintiakleine2607/)
Ou me adicione no [Whats](https://api.whatsapp.com/send?phone=5547997653031)

## Tempo médio de feedbacks

Costumamos enviar feedbacks entre 3 a 5 dias após cada processo.

## Labels

- 🏢 Flexível
- 🏢 Presencial
- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
