### ISSUE TITLE
[Rio de Janeiro/RJ] Front-end Developer na Oliveira Trust

### ISSUE THREAD

**Issue by davicervo** [frontendbr/vagas#5118]
[Rio de Janeiro/RJ] Front-end Developer na Oliveira Trust

## Nossa empresa

A Oliveira Trust é uma das maiores empresas do setor Financeiro com muito orgulho, desde 1991, realizamos as maiores transações do mercado de Títulos e Valores Mobiliários.

Somos uma empresa em que valorizamos o nosso colaborador em primeiro lugar, sempre! Alinhando isso com a nossa missão "Promover a satisfação dos nossos clientes e o desenvolvimento pessoal e profissional da nossa equipe", estamos construindo times excepcionais em Tecnologia, Comercial, Engenharia de Software, Produto, Financeiro, Jurídico e Data Science.

## Descrição da vaga

Estamos buscando uma pessoa que seja movida a desafios, que saiba trabalhar em equipe e queira revolucionar o mercado financeiro!

## Local

Barra da Tijuca - Rio de Janeiro/RJ

## Requisitos

**Obrigatórios:**
- Trabalhar com frameworks/libs (Vuejs, Jquery, Bootstrap)
- Conhecimento com Javascript (VanillaJs) e novas features do EcmaScript
- Bons conhecimentos em CSS3: Grid-layout, flexbox, animações, responsivo
- Implementar API's com nossas interfaces
- Conhecer alguma ferramenta para teste de requisição (Postman, insomnia)

**Diferenciais:**
 - VueJs
 - SASS
 - Webpack
 - Conhecimento e interesse em UX / UI.

## Benefícios

- Salário compatível com o mercado;
- Vale Refeição;
- Vale Alimentação;
- Vale Transporte ou Vale Combustível;
- Auxílio Creche;
- Plano de Saúde e Odontológico;
- Seguro de vida;
- PLR Semestral;
- Horário Flexível;
- Parcerias em farmácias;

## Contratação

CLT

## Como se candidatar

Acesse o nosso desafio para saber mais detalhes: https://github.com/Oliveira-Trust/desafio-frontend/blob/master/VAGA.md
Para saber todos os detalhes da vaga acesse: https://github.com/Oliveira-Trust/desafio-frontend/blob/master/README.md

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.

## Labels
clt, jr, pleno, senior

#### Alocação
- Presencial e Remoto Parcial

#### Regime
- CLT

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
