### ISSUE TITLE
[São Paulo] Front-End Developer no Canal da Peça

### ISSUE THREAD

**Issue by Crazydevil0** [frontendbr/vagas#512]
## Descrição da vaga

Precisamos de um Front-end que seja realmente 1337, um cara que manje de seus códigos mais do que manja do seu deck de Magic, que mande tão bem no front quanto mata cara na faca no CS 1.6.

## Local

Escritório, São Paulo - Jardins

#### Diferenciais

- Open de Alura, pluralSight, codeschool.
- Frigobar pra galera
- Counter Strike todo dia
- Só developer zica

## Requisitos

**Obrigatórios:**
- Experiência com boas práticas de desenvolvimento
- Experiência com SEO e CRO.

**Desejáveis:**
- Conhecimento de grails
- Conhecimento de ReactJS

## Contratação
PJ a combinar

## Como se candidatar

Por favor envie um email para fernando.frizzatti@canaldapeca.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
