### ISSUE TITLE
[Remoto] Front-end Developer na Trezo | Vagonetas

### ISSUE THREAD

**Issue by maiconkf** [frontendbr/vagas#5120]
## Nossa empresa

Somos uma das principais empresas da América Latina especialista na implantação e manutenção da plataforma Adobe Commerce.

Com mais de uma década de experiência, temos muito orgulho de sermos reconhecidos pela nossa expertise técnica e ter desenvolvido grandes projetos de renome nacional e internacional.

Fazemos parte do Adobe Solution Partner Program, um dos mais altos níveis de parceria de empresas implementadoras da plataforma Adobe Commerce, reforçando nossa autoridade nesta que é a melhor plataforma de e-commerce do mundo.

## Descrição da vaga

Desenvolvimento e correções de funcionalidades na plataforma Magento, entregando com qualidade as demandas alinhadas com o cliente.

**ATIVIDADES:**

- Correção de bugs (erros);
- Manutenção de segurança e performance;
- Desenvolvimento de novas funcionalidades;
- Instalação, implementação e personalização de módulos adquiridos pelos clientes;
- Consultoria de melhores práticas de desenvolvimento, diagramação/layout, usabilidade e performance;
- Consultoria e treinamento dos clientes nos assuntos referentes ao e-commerce e/ou suas demandas;
- Desenvolvimento e correções de funcionalidades na plataforma Magento. Atuando na criação de módulos, integrações, etc. 

## Local

Remoto

## Requisitos

**Obrigatórios:**

- Experiência com desenvolvimento de sistemas utilizando JAVA 1.6 ou superior (Struts 1.2, Hibernate, JPA, EJB)
- Conhecimento em webservices REST e SOAP
- Conceitos bem consolidados de Orientação a Objeto
- Servidores de aplicação Glassfish e/ou Jboss
- Experiência com Javascript, CSS e JQuery.
- Queries em Banco de dados

**Diferenciais:**

- Cultura baseada em Valores e Propósito;
- Trabalho Remoto: prezamos pela saúde, segurança, autonomia e confiança junto ao #trezoteam; 
- Horário Flexível: disponibilidade de 8 horas diárias;
- Day Off Aniversário: você merece uma pausa e curtir momentos especiais;
- Boteco Trezo (Happy Hour Virtual)  e celebrações diversas: criamos laços e comemoramos juntos;
- Política de Incentivo às Certificações: conhecimento e excelência caminham juntos;
- Férias Remuneradas: ter um momento para você recarregar as energias e cuidar de si;
- Indicação Premiada: reconhecimento por indicar novos #trezoteam;
- Desconto em Parceiros: usufruir de clube de vantagens e descontos;
- Reconhecimento por Tempo de Colaboração: mimos e giftworks que valorizam nossa parceria;
- Cartão Flash Benefícios Flexíveis: aceito em todo país, funciona na função crédito;
- Desenvolvimento & Carreira: Feedback, PDI, Trilhas de Capacitação, Trezo Talk;

## Contratação

R$8000 ~ R$12000

## Como se candidatar

Preencher o formulário neste link: [Vaga na Trezo via Vagonetas](https://www.vagonetas.com.br/vagas/frontend-developer-magento-14b7e35202c0cc3e)

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
