### ISSUE TITLE
[São Carlos/SP] Front-end Developer no Santander Tecnologia do Brasil

### ISSUE THREAD

**Issue by CinthiaBergamin** [frontendbr/vagas#5121]
DESCRIÇÃO DA VAGA
Já pensou em trabalhar em um lugar em constante transformação digital, inovação, colaboração e crescimento? Aqui é o lugar!

Se você tem paixão por tecnologia e pessoas, empatia, foco em resultados e gosta de mudanças, faça parte de tudo isso!

Estamos sempre inovando e buscando trabalhar com as melhores tecnologias do mundo. Nosso time de tecnologia conta com Agile coach, desenvolvedores Mobile, profissionais full stack, BPM, DevOps, Cloud e outros.

Nosso compromisso com a valorização da Diversidade está presente em todas as nossas oportunidades. Acreditamos no potencial humano para desenvolver talentos e gerar inovação para nossos clientes. Aqui você pode ser quem você é!

Se você se identificou #deumatch!

RESPONSABILIDADES E ATRIBUIÇÕES
- Responsável pela análise e desenvolvimento de sistema em Angular, incluindo a criação de testes automatizados;

- Configuração Build e Deploy nos ambientes;

- Acompanhamento de implantação e suporte aos consumidores;

- Prever questões envolvendo performance e confiabilidade da aplicação, atuando na solução.

REQUISITOS E QUALIFICAÇÕES
- Conhecimento em Angular, Bootstrap e JQuery;

- Experiência no ciclo completo de desenvolvimento de sistemas, desde análise de processos, requisitos, desenho arquitetural, construção, testes e implantação;

- Conhecimento em Integração de Sistemas utilizando Serviços e/ou APIS;

- Conhecimento em DevSecOps (Integração contínua com Maven, Jenkins, GitLab, Sonar, FortFy, ArtiFactory);

- Conhecimento em ferramentas colaborativas (Jira e Confluence);

- Conhecimento metodologia Ágil.

SANTANDER TECNOLOGIA - SÃO CARLOS/SP
Somos, antes de mais nada, uma empresa de tecnologia. No Onovolab, nosso hub de tecnologia, as equipes contam com a estrutura ideal para permitir um trabalho ágil, eficiente e inovador em um ambiente aberto e flexível. Junte-se a nós e trabalhe com profissionais referência no mercado.

Você pode enviar o seu CV para cinthia@hprojekt.com.br com o título Front End ;)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
