### ISSUE TITLE
[Remoto] Front-End Developer na Skeelo Editora

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#5125]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-frontend-191602966?origin=github&modal=open) com o pop-up personalizado de candidatura. 👋
<p>- Criar e fazer a manutenção de projetos desenvolvidos em VueJS e Angular 6+;</p>
<p>- Participar do processo criativo e apoiar a construção de sistemas;</p>
<p>- Buscar novas ferramentas e técnicas para a melhoria contínua dos sistemas existentes.</p>

## Skeelo Editora: 
 <p>O Skeelo está impactando milhões de pessoas trazendo o hábito da leitura para o cotidiano dos brasileiros através de tecnologia e dos conteúdos mais vendidos no Brasil. Estamos totalmente inseridos no mundo digital e a inovação é nosso principal pilar.</p>
<p>Se você quer atuar em um ambiente de trabalho descontraído, porém desafiador, com espaço para contribuir com ideias e experiências e ainda aprender muito com um time de profissionais de ponta, o Skeelo é pra você.</p><a href='https://coodesh.com/empresas/skeelo-editora'>Veja mais no site</a>

 ## Habilidades: 
 - Javascript 
- Vue.js 
- Node.js
## Local: 
 100% Remoto
## Requisitos: 
 - Seja apaixonadx por criação de layouts fora do comum; 
- Tenha conhecimentos avançados em CSS3/HTML5/JavaScript; 
- Possua experiência com VueJS e Angular 6+; 
- Tenha conhecimentos em Node.js; 
- Saiba sobre Git; 
- Tenha algum conhecimento de UI/UX e animações.

## Benefícios: 
 - Assistência Médica Porto Seguro Prata para titular e Dependentes, sem desconto em folha; 
- Assistência Odontológica Porto Seguro opcional, com custo 100% do colaborador; 
- Seguro de Vida sem desconto em folha; 
- Vale-refeição de R$770,00 por mês sem desconto em folha; 
- Auxílio-creche para filhos com até 60 meses de vida no valor de R$470,00 
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Front-End Developer na Skeelo Editora](https://coodesh.com/vagas/desenvolvedor-frontend-191602966?origin=github&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção <b>Pedir Feedback</b> entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa <b>Recruiter</b> responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Front-End

**Comment by GabrielLeandroBS** [comment]
Vaga JR?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
