### ISSUE TITLE
[Remoto] Frontend Angular Developer na Coodesh 🥇

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#5126]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/sr-frontend-angular-developer-230903884?origin=github&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Buscamos Pessoas para atuar como <strong><ins>Front-end Angular Developer </ins></strong>em nível <strong><em><ins>Sênior</ins></em></strong>.&nbsp;</p>
<p></p>
<h6>👋 Como Funciona / Processo</h6>
<ul>
<li>Candidate-se fornecendo as informações solicitadas;</li>
<li><a href="https://coodesh.com/dashboard/account/edit-profile" target="_blank"><strong>Complete o seu perfil na plataforma</strong></a>;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>
<li>Responda ao scorecard;</li>
<li>Responda ao teste de mapeamento comportamental disponível na plataforma;</li>
<li>Fique atento(a) aos convites para entrevistas de fit ou entrevista técnica.</li>
</ul>

## 🥇 Vagas Premium & Selected: 
 <p>A Coodesh é uma plataforma que conecta pessoas desenvolvedoras de software em oportunidades 100% remotas. Em nossa plataforma você encontrará oportunidades part-time ou full-time com modelos de contratações: CLT, PJ, Freelance e Squad.&nbsp;</p>
<p>Cadastre-se gratuitamente para ter acesso a <strong><ins>mais de 150 empresas contratando agora</ins></strong>!</p><a href='https://coodesh.com/empresas/vagas-premium'>Veja mais no site</a>

 ## Habilidades: 
 - Ionic 
- Javascript 
- Typescript 
- SEO 
- Angular 8 
- Design de Front-End
## Local: 
 100% Remoto
## Requisitos: 
 - Fluente em trabalhar com Angular 2+, Angular 8 ou Angular 9 
- Habituado as boas práticas de SEO 
- Conhecimentos em Microfrontend 
- Conhecimentos ou experiência como Front-end Developer 
- Habituado em ler endpoints com Swagger (consumo de APIs) 
- Escreva código bem projetado, testável e eficiente 
- Habituado em trabalhar com programação orientada a objetos 
- Domínio em Javascript ou Typescript 
- Ter disponibilidade para participar do processo de seleção 100% online 
- Conhecimentos e boas práticas com HTML5 / CSS3
**Diferenciais:** 
 - Envolvimento em contribuições open source, comunidades ou meetups 
- Ser habituado com metodologias ágeis 
- Conhecimentos em SSR
## Benefícios: 
 - PJ ou CLT 
- Horários Flexíveis 
- 100% remoto
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Sr. Frontend Angular Developer na 🥇 Vagas Premium & Selected](https://coodesh.com/vagas/sr-frontend-angular-developer-230903884?origin=github&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção <b>Pedir Feedback</b> entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa <b>Recruiter</b> responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Nível
Sênior
#### Categoria
Front-End

**Comment by moderacaofrontendbr** [comment]
Olá @gabrielhws essa vaga é para trabalhar na própria Coodesh?

**Comment by gabrielhws** [comment]
Para front-end em geral, temos interno, em squads e tem 2 empresas em conjunto com vaga no mesmo perfil.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
