### ISSUE TITLE
[São Paulo] Front-End Developer na NerdMonster (Pleno)

### ISSUE THREAD

**Issue by nerdmonsterdigitalretail** [frontendbr/vagas#513]
## Descrição da vaga
O time de desenvolvimento da NerdMonster está procurando um programador frontend que adora e tem experiência com sites responsivos atuando no conceito de mobile-first.

Nós somos uma empresa com uma missão bastante clara: Empoderar varejistas pequenos, médios e grandes redes a terem o controle de sua reputação digital e centralizar seu marketing digital em um único lugar.

Buscamos ativamente desenvolvedores capazes, motivados a procura de novos desafios através da programação. Valorizamos profissionais pelo seu portfólio e com comprovação de experiência. 

## Local
Pinheiros - São Paulo (ao lado do metrô Pinheiros)

## Requisitos

**Obrigatórios:**
- Bons conhecimentos em HTML5 e CSS3;
- Bons conhecimentos em JavaScript e jQuery;
- Bootstrap CSS;
- Utilização de padrões e boas práticas para desenvolvimento front-end.
- GIT;

**Desejáveis:**
- Experiência em otimização e performance;
- Boas noções de UX;
- Boas práticas de SEO;
- Código organizado;
- Consumo de API REST;
- SASS.

**Diferenciais:**
- Proatividade para resolução de problemas;
- Espírito de equipe;
- Gosto por aprender.

## Contratação
Freelancer alocado para projeto com escopo fechado

## Como se candidatar
Por favor envie um email para contact@nerdmonster.com com seu CV e Portfólio. 
Enviar no assunto: Front-End Developer (Pleno) - SP.

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by nerdmonsterdigitalretail** [comment]
Sim!

Em 23 de jan de 2018 14:08, "Felipe Fialho" <notifications@github.com>
escreveu:

Aberto ainda?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/frontendbr/vagas/issues/513#issuecomment-359840098>,
or mute
the thread

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
