### ISSUE TITLE
[São Paulo] Front-end Developer na Enext Consultoria

### ISSUE THREAD

**Issue by yagosenhorini** [frontendbr/vagas#5133]
## Nossa empresa

A Enext é uma consultoria e agência digital, premiada em 2016 e 2017 pelo GREAT PLACE TO WORK. Nós fazemos parte do grupo WPP, a maior empresa de publicidade do mundo em termos de receita. Trabalhamos com vários clientes desafiadores, cujo alguns deles são: Suvinil, L’Oréal, Bauducco, Malwee.

Nosso time tem hoje aproximadamente 200 pessoas, focadas no nosso principal valor: Transformar a vida das pessoas para o futuro. E é esse pensamento que nos torna referências nas melhores tecnologias do mercado de desenvolvimento de e-commerce como: Salesforce, Oracle, Magento e Vtex.

Nosso time de tecnologia hoje, é um dos melhores do Brasil quanto a desenvolvimento WEB, tanto na stack front-end quanto na back-end. Além disso, somos parceiros de grandes empresas de cloud computing como AWS, Microsoft e Oracle. Usamos largamente os seus serviços e investimos no treinamento da equipe para atuar com elas.
Como se candidatar

## Descrição da vaga

Trabalhar no desenvolvimento de e-commerce para grandes empresas como:

   - Avon
   - Bauducco
   - Loreal Paris
   - Malwee
   - Drogaria Araújo

## Modelo de contratação

    (VR ou VA)
    VT 
    Convênio médico
    GymPass
    Alocação remota
    Oportunidades PJ e CLT

## Requisitos

Obrigatórios (JR):

    Conhecimento básico JavaScript, HTML e CSS
    Saber como funciona um Controle de versão - Git
    Saber como funciona consumo de APIs - Ajax
    Boas práticas: reutilização de código

Diferenciais:

    ECMAScript 2015
    Linters
    Conceitos de data-bind
    Experiência com plataformas de e-commerce
    SEO
    Liquid Template
    Metodologias CSS - BEM, SMACSS, ITCSS e etc.
    Task Runners / Module Bundler
    Modularização e Componentização
    Template engine - Pug
    React

As vagas estão disponíveis nos seguintes links:

Junior: https://enext.solides.jobs/vacancies/74594#vacancyDescription
Pleno: https://enext.solides.jobs/vacancies/66086#vacancyDescription
Sênior: https://enext.solides.jobs/vacancies/42024#vacancyDescription

## Labels

    CLT
    Estágio
    Júnior
    PJ
    Pleno
    Senior
    Remoto

**Comment by Gabri3el** [comment]
Enviado o/

**Comment by joao160197** [comment]
Enviado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
