### ISSUE TITLE
[Porto Alegre] Junior Front-end Developer na Muv Recursos Humanos

### ISSUE THREAD

**Issue by robertafonseca** [frontendbr/vagas#5139]
>

## Nossa empresa

A MuvRH está com 03 vagas para Junior Front-end Developer para atuar em uma empresa de Tecnologia. 

De maneira customizada, a empresa apoia clientes com soluções inovadoras no processo de transformação digital.

Você atuará em um dos clientes da empresa, do segmento do varejo, auxiliando o time de arquitetura para definições de novos projetos e implantação destes. Estará inserido em um Time Ágil, com sprints e demais rotinas definidas.

## Descrição da vaga
- Programar, desenvolver e implantar sistemas em linguagem HTML, CSS, TypeScript; 
- Realizar correções em sistemas, análise e desenvolvimento de performance;
- Conduzir configuração e gerenciamento de microsserviços com Docker, Kubernetes, Jenkins, GitLab.

## Local

Exemplo: Remoto e alocado no cliente (1 a 2x por semana). A sede da empresa contratante fica em Porto Alegre, mas o cliente deles localiza-se na Grande Porto Alegre.

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento Front-end em HTML, CSS e TypeScript;
- Disponibilidade para atuar em Porto Alegre ou Região Metropolitana (1 a 2x por semana).

**Desejáveis:**
- Conhecimento prévio em tecnologia de Container e em Metodologias Ágeis, SOA e Micro Front-End.

**Diferenciais:**
- Será um diferencial ter conhecimento em: RxJs, React ou Angular.

## Benefícios

- Auxílio deslocamento (via fretado ou com veículo próprio);
- Refeitório no local ou ressarcimento da alimentação quando estiver trabalhando Home Office.

## Contratação

Valor CLT: R$ 3.800,00 - pode ter variação de acordo com o conhecimento técnico do candidato(a).
Valor PJ: R$35,00/hora - pode ter variação de acordo com o conhecimento técnico do candidato(a).

## Como se candidatar

Por favor envie um email para cv@muvrh.com.br com seu CV anexado - enviar no assunto: Vaga Junior Front-end Developer.

## Tempo médio de feedbacks

Costumamos enviar feedbacks a todos os candidatos(as) que passam por processo seletivo. E apreciamos todos os cvs recebidos. E-mail para contato em caso de não haver resposta: roberta@muvrh.com.br

#### Alocação
-  Alocado e Remoto - Híbrido

#### Regime
- CLT ou PJ

#### Nível
- Júnior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
