### ISSUE TITLE
[São Paulo] Front End Sênior Developer na BRQ

### ISSUE THREAD

**Issue by ReAnne123** [frontendbr/vagas#514]
São Paulo- Front End Sênior Developer na BRQ

Empresa de grande porte localizada na Faria Lima busca profissional com experiência em programação front end, Angular, CSS, SASS, javascript, responsividade.
Início imediato e prazo indeterminado.
Contratação CLT, salário a combinar mais atrativo pacote de benefícios.
Vaga presencial. 
Local: Faria Lima (Itaim Bibi)- São Paulo.
Horário comercial.

Caso tenha interesse, envie seu cv para a Renata (ryokota@brq.com)

Um pouco sobre a BRQ:

Fundada em 1993, a BRQ é uma das maiores empresas de serviços de TI do país. Conta com 3000 profissionais distribuídos nas filiais de São Paulo, Alphaville, Rio de Janeiro, Curitiba, Recife, Salvador, Brasília, Natal e Nova Iorque.

**Comment by LFeh** [comment]
Aberto ainda?
