### ISSUE TITLE
[Remoto] Consultor Digital PJ na Disys

### ISSUE THREAD

**Issue by alvaropsc** [frontendbr/vagas#5141]
## Descrição da vaga

Projeto de 06 meses com chance de renovar.
Trabalho remoto.

Javascript, HTML5, CSS3, Sass, Grunt, Sharepoint (2013, 2016 e Online)
ASP.NET (Webforms e MVC)

## Local

Remoto

## Requisitos

**Desejáveis:**
O365 (Forms, Flow, Power Apps), DevOps Azure, SQL Server

**Diferenciais:**
PowerShell,
UI e UX,
PHP,
Wordpress, Drupal

## Contratação

PJ/Cooperado - Negociável dependendo do nível do candidato.

## Como se candidatar

Por favor envie um email para alvaro.luiz@yolorecruit.com com seu CV anexado - enviar no assunto: Consultor Digital

## Tempo médio de feedbacks

Costumamos enviar feedbacks imediatos.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
