### ISSUE TITLE
[Remoto] Desenvolvedor(a) Ruby on Rails / Vue.js - Júnior/Pleno na Meu Fornecedor

### ISSUE THREAD

**Issue by NerdProgramador-com-br** [frontendbr/vagas#5144]
### Descrição da empresa

O [Meu Fornecedor](https://meufornecedor.com.br/?utm_source=rubyjobsbrazil) é um portal dedicado ao food service, agilizando o dia a dia de toda a cadeia de fornecedores, distribuidores, restaurantes, minimercados e demais atores. Estamos em estágio de pré-lançamento, concluindo os últimos detalhes do sistema.

  

### Atividades e Responsabilidades

A vaga é para um desenvolvedor com experiência em Ruby on Rails (nosso backend), mas que também consiga trabalhar em um frontend Vue.JS. Além disso, utilizamos testes automatizados, com RSpec e Cypress.

### Requisitos

\*\*Obrigatórios:\*\*

\- 1 ano de experiência em Ruby on Rails

\- 1 ano de experiência com algum framework de frontend JS (de preferência Vue.JS, mas pode ser Angular, React etc)

\- conhecimento de testes automatizados (de preferência RSpec e Cypress)

\- SQL

\- domínio pleno de português e inglês

\- ótima capacidade de comunicação

### O que nós oferecemos

\- 6h/dia

\- horário livre entre 8h e 18h

\- não precisa bater ponto

\- equipe e chefia divertidas e amigáveis =D
## Salário 
R$3000 - R$5000 
## Local 
REMOTO 
## Como se candidatar 
Accesse a [Vaga de Desenvolvedor(a) Ruby on Rails / Vue.js - Júnior/Pleno](https://vaga.contratar.dev/apply/full/114e0a3a-ba65-4e83-b9dd-d8fb4aca8ab6) para se candidatar. 
## Labels 
* Remoto 
* SQL 
* React 
* Ruby 
* Angular 
## Sobre a contratar.dev 
A contratar.dev é uma plataforma de recrutamento e seleção automatizada de Desenvolvedores. Ao se candidatar a uma vaga da contratar.dev, você estará participando automaticamente de dezenas de processos seletivos para vagas similares, aumentando em MUITO as suas chances de mudar de vida 😉

**Comment by julianasm** [comment]
A label eh de estagio mas a vaga eh de junior? Nao entendi

**Comment by allysonthales** [comment]
> A label eh de estagio mas a vaga eh de junior? Nao entendi

Muita vaga aqui tem essas tag erradas, eu não sei se pode reportar para corrigirem, se puder, eu faria isso sempre pq entro quase todo dia aqui procurando vagas de estágio, mas tem pleno e JS com tag de estágio...

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
