### ISSUE TITLE
[São Paulo] Flutter Developer na Fastcash

### ISSUE THREAD

**Issue by Claudio-Ebeneze** [frontendbr/vagas#5146]
> 

## Nossa empresa

A Fastcash é uma empresa de Banking as a Service, crescendo 300% ao ano nos últimos 3 anos e preparando a infra estrutura para crescer 10X Yoy.

## Local

Remoto

## Requisitos

**Obrigatórios:**

- Conhecimento em Flutter e Dart;
- Experiência avançada em desenvolvimento Mobile;
- Experiência em automatização de testes em múltiplos devices;
- Tuning de desenvolvimento e gerenciamento de memória em dispositivos móveis;
- Criação de componentes customizados.

## Suas atribuições serão:

Participar de discussões sobre arquitetura e estratégias de desenvolvimento dos aplicativos da empresa;
Participar de melhorias em processos (desenvolvimento, qualidade, agilidade e infraestrutura) dentro do time;
Escrever códigos eficientes, reutilizáveis e de fácil manutenção;

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para Leonardo@Fastcash.com.br com seu CV anexado - enviar no assunto: Vaga Flutter

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
