### ISSUE TITLE
[REMOTO] Tech Lead Front-end React na @Maitha Tech

### ISSUE THREAD

**Issue by Patricia-MaithaTech** [frontendbr/vagas#5148]
## Nossa empresa

Somos uma empresa digital, com experiência em tecnologia e inspirada pela inovação. Atuamos na aceleração, transformação e ideação de novas soluções e times de alta performance.
Atuamos tanto na construção de times de tecnologia, quanto em frentes de negócio, na co-criação de produtos, levantamento de requisitos, resolução de problemas, entre outros.

## Descrição da vaga

É para atuar na Maitha como Tech Lead prestando serviço ao nosso cliente, a empresa cliente foi fundada no Brasil, atualmente conta com operações em alguns dos principais países da América Latina e mais de 1200 profissionais. Referência em projetos Full Service, B2C e B2B, é responsável pelos e-commerces de marcas como Ambev, Armani Exchange, Nike, Mondelez e Unilever, entre outros grandes players.
Projeto: atuar na construção de uma solução de automatização na criação de novos sites de e-commerce para clientes da IFC. O sistema terá um marketplace de templates e layouts, e possibilitará a disponibilização mais ágil de novas lojas online para a companhia. Atualmente a criação de uma nova loja dura em média 2 meses, com esse projeto a empresa busca disponibilizar uma nova operação na metade do tempo e sem a necessidade de escalar a operação. Estamos montando 3 novas squads para eles, será uma de Vitrine, uma Checkout e uma de Conteúdo.
A posição inicialmente é como PJ pela Maitha, 100% remoto e após 6 meses, eles tem a intenção de internalizar como CLT, mantendo 100% remoto.

## Local

REMOTO

## Requisitos

**Obrigatórios:**
- React
- HTML
- CSS
- Javascript
- Git
- API RESTful
- Jest ou React Testing Library
- Styled Components
- Visão Arquitetural
- Cloud
- Devops

## Benefícios (após o período de 6 meses, apenas quando se tornar CLT)

- Home-office completo;
- Horário flexível;
- Plano médico com coparticipação Sulamérica;
- Plano odonto;
- VR R$ 600,00;
- Aux creche para filhos até 5 anos;
- Gympass;
- Zen klub;
- Aux home office - R$ 70,00 reais;
- Convênio farmácia;
- Seguro de vida;
- Plr até 2 salários;

## Contratação

PJ por 6 meses, após este período será CLT

## Como se candidatar

Contato via Linkedin: https://www.linkedin.com/in/patriciapcarrillo/ ou envie um e-mail para patricia@maitha.com.br com seu CV anexado - enviar no assunto: Vaga Tech Lead Front End React

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
