### ISSUE TITLE
[ Vitória/ES 100% Remoto ] Front-end Developer na Conexos Consultoria e Sistemas 

### ISSUE THREAD

**Issue by isa811556** [frontendbr/vagas#5151]
> 

## Nossa empresa

Nós somos a Conexos e fomos feitos para entregar à você o melhor em automação e inovação tecnológica, muito mais que as tão genéricas soluções que existem no mercado. Para isso nos tornamos uma equipe aficionada por fazer um bom dever de casa. Estudamos muito, erramos e aprendemos para hoje, com orgulho, sermos uma das melhores empresas de softwares ERPs do Brasil. 

## Descrição da vaga

- Buscamos um talento para compor nosso time que tope o desafio de mudar o nosso framework de desenvolvimento e embarque nesse desafio com a gente. Buscamos pessoas que trabalhem felizes e, por isso, procuramos sempre proporcionar um ambiente alto astral para que você dê sempre o seu máximo. 
- Você vai desenvolver em HTML, CSS, JavaScript e Angular os layouts digitais feitos pelo time, criando interatividade entre os elementos da página. Além de ajudar na criação e manutenção de componentes e plugins internos.

## Local

100% Remoto 

## Requisitos

- Experiência com desenvolvimento em front end nas linguagens ou framework de desenvolvimento web. Ex: HTML, CSS, JavaScript, AngularJS, ReactJS, etc;

- Conhecimento básico de padrões de projeto e boas práticas de programação, performance de usuário das páginas.

**Diferencial:**

- -Experiência com ReactJS, Angular 2+ e VueJs
-Noções de UX/UI.

## Contratação

- PJ
- Salário a combinar (trabalhamos com pretensão)

## Como se candidatar

Por favor envie um email para isabela.rocha@conexos.inf.br com seu CV anexado - enviar no assunto: Vaga Front-end

**Comment by isa811556** [comment]
Oii @VitorMiguelPS, alterei o e-mail. Me desculpe, tivemos um probleminha com o outro. Pode enviar novamente, por favor.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by isa811556** [comment]
Ainda está aberta!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
