### ISSUE TITLE
[São Paulo] Front-end Developer na ANBIMA

### ISSUE THREAD

**Issue by webdthiago** [frontendbr/vagas#5153]
> Vaga Remota durante a pandemia

## Nossa empresa

Somos a Associação Brasileira das Entidades dos Mercados Financeiro e de Capitais. Representamos as instituições como bancos, gestoras, corretoras, distribuidoras e administradoras.

Vem fazer parte desse time!

## Descrição da vaga

Front-end Developer Pleno: ReactJS, React Hooks, Javascript, ES6, HTML, CSS/SASS.
Analisar, entender demandas de negócio, prototipar e implementar o front-end.
Analisar tecnicamente a performance, qualidade de codificação, cobertura de testes, preparação para deploy e outros aspectos técnicos de front-end.

## Local

Exemplo: Escritório, [SP], [São Paulo], [Pinheiros]

## Requisitos

**Obrigatórios:**
- Experiência em desenvolvimento Javascript, ES6, React, RESTful APIs, Git, Jenkins, HTML, CSS/SASS, Webpack, Babel, Node.js.
- Inglês avançado.
- Ensino superior em TI ou áreas correlatas concluído.

## Benefícios

- Salário Competitivo ao mercado
- Vales Refeição e Alimentação
- Vale Transporte
- Plano de Saúde e Odontológico
- Previdência Privada com participação da Associação
- Auxílio Creche/Babá

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um email para kioma.silva@anbima.com.br com seu CV anexado - enviar no assunto: Vaga FrontEnd

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
