### ISSUE TITLE
[Remoto] Front-end Developer na PetLove

### ISSUE THREAD

**Issue by natalia-sborges** [frontendbr/vagas#5155]
Pessoa Desenvolvedora Front-End Senior [REMOTO] @ Petlove

Descrição: A Petlove é o maior petshop online e clube de assinaturas para pets do Brasil. Com uma trajetória de mais de 20 anos e portfólio de mais de 15 mil itens do universo pet, incluindo marcas próprias e exclusivas, a empresa passou a oferecer uma experiência completa, sendo a primeira a lançar aplicativo para celular e serviço de assinatura. Hoje é a maior empresa de tecnologia na indústria brasileira de pets, recebendo os melhores fundos de venture capital do país. Mais recentemente a empresa adicionou ao seu portfólio empresas estratégicas como DogHero, VetSmart, Vetus e Health para animais de estimação. E só cresce! Atualmente, buscamos uma pessoa Desenvolvedora Front-End para compor o time! Gostaria de fazer parte desse desafio? Vou deixar aqui o link com os detalhes da vaga na nossa página para facilitar a visualização:

Local: 100% REMOTO
Contratação: CLT + Benefícios
Benefícios: Plano de saúde, Plano odontológico, Vale refeição, PLR, parcerias com descontos e descontos em produtos no Site, gympass, etc
Requisitos: Angular; desenvolvimento web; Javascript.

Mais informações, benefícios e interesse em participar basta fazer cadastro no seguinte site para darmos continuidade ao processo:
https://byintera.in/comuptlvfe

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
