### ISSUE TITLE
[Campo Largo/PR] Front-end Developer na Exitoinf

### ISSUE THREAD

**Issue by Jociel-Adachi** [frontendbr/vagas#5158]
> Vaga Remota durante a pandemia

## Exitoinf

Aqui na Exitoinf trabalhamos com sistemas web para Gestão de postagens e envios de agências dos correios, transportadoras e entregas próprias.

## Descrição da vaga

Desenvolvedor Frontend

- Análise e desenvolvimento de novas funcionalidades para Sistemas Web, assim como correções de possíveis erros;
- Reuniões cíclicas de feedback e de levantamento de RF, RNFs e Regras de Negócios;
Forma de trabalho: Home Office

## Local

Remoto, 100% home office.

## Requisitos

**Obrigatórios:**
- Experiência em desenvolvimento em PHP, JavaScript e NodeJS.
- Frameworks React, React Native.

**Desejáveis:**
- conhecimentos na Plataforma ClickUp e metodologia SCRUM.
- conhecimentos em versionamento com GitHub e Azure;

**Diferenciais:**
- Horário flexível, porém obrigatoriedade em comparecer em reuniões.

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para gerenciaprojetos@exitoinf.com.br com seu CV anexado - enviar no assunto: Vaga Frontend Jr.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dias após primeira entrevista.

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
