### ISSUE TITLE
[Remota] Front-end Developer na Fliper

### ISSUE THREAD

**Issue by Aa-app** [frontendbr/vagas#5159]
Front-End Developer na @FLIPER
==================================================
 Vaga Remota 

## Nossa empresa

**Sobre a Fliper**
Quer ajudar as pessoas a realizar seus sonhos e se tornar referência no mercado? 
O Fliper busca candidatos apaixonados por buscar soluções de quebra-cabeças lógicos e que esteja afim de desenvolver algo inovador com um real propósito de impactar a vida das pessoas!

Nosso jeito de ser: 

- Foco no Cliente sempre!
- Mentalidade Empreendedora com foco nas melhorias e inovação constante.
- Diversidade e Inclusão: no Fliper você terá espaço para ser você mesmo e usufruir ao máximo de um ambiente plural cheio de oportunidades. 

## Descrição da vaga

Pessoa Programadora Front-end ReactJS Senior

## Requisitos

- Sólida experiência no desenvolvimento de front-end com uso de ReactJS.
- Conhecimento em Typescript.
- Conhecimento em GraphQL.
- Conhecimento avançado em HTML5 e CSS3.
- Sistema de controle de versão (Git).
- Testes Cross Browser.
- Noções de testes de usabilidade e interface.

**Diferenciais:**

-  Já ter trabalhado com Hooks do ReactJS.

## Benefícios

- Plano de saúde e odontológico sem custos para o titular e dependentes
- Vale Alimentação
- Vale Refeição
- Assistência médica e odontológica
- Bônus de acordo com o atingimento das metas

## Contratação

CLT

## Como se candidatar

Por favor envie um email para aline.arruda@fliper.app com seu CV anexado - enviar no assunto: Vaga NodeJS. Ou se candidate: 
https://carreiras.revelo.com.br/empresa/fliper

#### Nível

- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
