### ISSUE TITLE
[Itajubá] Front-end Developer na Wattio

### ISSUE THREAD

**Issue by anafaine** [frontendbr/vagas#5165]
> Vaga Remota durante a pandemia

## Nossa empresa

Somos uma plataforma inteligente para operacionalizar a gestão de clientes para consórcios, cooperativas, gestão em autoconsumo e gestão de clientes cativos.

Fazemos todo o processo ponta a ponta, da coleta da fatura de energia ao paramento, tudo de forma integrada e automatizada.

Buscamos candidatos que gostem de aprender e serem desafiados. Com forte atuação na construção de crawler e extratores inteligentes, as principais atividades serão em desenvolvimento e automação em Python. Nosso desafio é se tornar referência na leitura e gestão de contas de energia, contratos de energia e gestão de usinas, proporcionando a nossos clientes uma experiência única na sua gestão energética e operação! Venha fazer parte desse time!

## Descrição da vaga
Trabalhar com o time de desenvolvimento web, realizar a manutenção da plataforma e captação de dados.

## Local

Itajubá/MG
Remoto

## Requisitos

**Obrigatórios:**
- Experiência em Angular e Node JS
- Experiência em desenvolvimento web
- Conhecimento em Javascript
- Experiência em PostgreSQL, API rest e versionamento Git

**Desejáveis:**
- Conhecimento em Python

## Benefícios

- Horário flexível
- Trabalho remoto
- Day-off de aniversário
- Short friday

## Contratação

PJ a combinar (R$3.500 a R$5.000)

## Como se candidatar

Por favor envie um email para vagas@wattio.com.br com seu CV anexado - enviar no assunto: Front-end Developer

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
