### ISSUE TITLE
[Remoto] Front-end Angular na 5AAttiva

### ISSUE THREAD

**Issue by Isabelacarrasco** [frontendbr/vagas#5168]
> Vaga Remota durante a pandemia

## Descrição da vaga
 Foco em desenvolvimento, mas espera-se que a partir das reuniões o profissional consiga levantar alguns requisitos técnicos. Atuará em um projeto que já está em andamento e podem surgir demandas novas

## Local

Remoto

## Requisitos

Angular 2 ou superior. Versionamento de código utilizando Git. Conhecimentos em técnicas e ferramentas para testes automatizados (unitário e integrado). Fluência com Git Flow. Conhecimento de arquitetura de micro-serviços. Conhecimento de Ruby On Rails e/ou .NET. Docker. Linux . Inglês. Boa comunicação e relacionamento interpessoal para interagir com usuário e área de negócios

## Contratação

PJ 

## Como se candidatar

Por favor envie um email para ingrid.prudencio@5aattiva.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by az1nn** [comment]
Bom dia, a vaga aceita Jrs?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
