### ISSUE TITLE
[São Paulo] Front-End Developer na Mandaê (Pleno e Sênior)

### ISSUE THREAD

**Issue by MandaeBR** [frontendbr/vagas#517]
## Descrição da vaga

Você será responsável pelo desenvolvimento do front-end dos sistemas da Mandaê, tanto os internos quanto os utilizados pelos nossos clientes. No seu dia a dia você estará envolvido em decisões importantes relacionadas UX e produto, além de ferramentas, frameworks e infraestrutura que suportam as nossas aplicações. Irá trabalhar diretamente com os product managers, o CTO e aos times de desenvolvimento, e terá a oportunidade de desempenhar um papel chave na construção de uma startup que está em crescimento acelerado e de desenvolver software inovador no segmento de logística, e que usa tecnologia de ponta. 

O candidato ideal tem sólida experiência em desenvolvimento para a web, está a par dos frameworks mais recentes, dos novos paradigmas de programação e outras novidades na área de front-end. Conhece tópicos avançados em engenharia de software e já trabalhou com metodologias de desenvolvimento ágeis. Precisa prezar pela qualidade do software que desenvolve, deve ter segurança para tomar decisões complexas de arquitetura de sistemas e iniciativa para promover e influenciar mudanças no processo de desenvolvimento.

## Local

São Paulo - Vila Leopoldina

## Benefícios

- Plano de saúde
- VR de R$ 26/dia
- VA
- Vale Transporte ou estacionamento ou vale combustível
- Seguro de vida em grupo
- Auxílio creche

#### Diferenciais

- stock options
- monte a sua máquina como desejar

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com HTML5, CSS3 e Javascript
- 1 ano de experiência com Angular.js
- Experiência com gulp, webpack, less, NodeJS e SASS
- Já ter desenvolvido aplicações web para desktop e para mobile
- Sólidos conhecimentos em padrões de projeto e engenharia de software (MVC, MVVM, etc.)
- Proatividade, um espírito mão na massa, e estar confortável com o ambiente dinâmico de uma startup são atributos essenciais

**Desejáveis:**
- Experiência com SEO e ferramentas de analytics, ex. GA e Mixpanel
- Experiência com React ou outros frameworks 
- Conhecimentos em AWS, especialmente Cloudfront

## Contratação

CLT

## Nossa empresa

A Mandaê (www.mandae.com.br) está usando uma combinação de tecnologia, logística e excelente serviço de atendimento ao consumidor para tornar mais simples para pessoas e empresas enviarem diversos tipos de objetos para qualquer lugar.  

Vencedora do desafio 1776 Challenge Cup na categoria Smart Cities, a Mandaê foi selecionada para o programa Startup Network da Endeavor, maior ONG de empreendedorismo do mundo. Nossos investidores incluem Monashees Capital, Qualcomm Ventures, Valor Capital, Kima Ventures e Hans Hickler, o ex-CEO da DHL Express-USA. 

## Como se candidatar

Por favor envie um email para vagafrontend@mandae.com.br com seu CV anexado ou link para o perfil do Linkedin, colocando no  assunto: Vaga Front-end developer

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
