### ISSUE TITLE
[FRONT-END] [SÊNIOR] [IGNIÇÃO DIGITAL] [REMOTO] 

### ISSUE THREAD

**Issue by giuliahuoya** [frontendbr/vagas#5170]
[FRONT-END] [SÊNIOR] [IGNIÇÃO DIGITAL] [REMOTO]
#vagasbyintera #realocação #frontend #Vagas #VagasT

 INSCRIÇÃO : https://byintera.in/ront11

A @IGNIÇÃO DIGITAL é uma empresa inovadora por implementar técnicas altamente eficazes de Marketing Digital! O impacto consiste no incentivo ao empreendedorismo no Brasil, a partir da criação de conteúdos conteúdos criativos em redes sociais, Blogs, Cursos, Workshop, Eventos, Newsletters! Atualmente, mais 100 colaboradores, acreditam no impacto positivo que o Marketing pode causar no nosso país. Os números que o Empreendedorismo Digital vem alcançando nas redes são surpreendentes. O time Tech está evoluindo, e o profissional de Desenvolvimento Front-End poderá suprir sua vontade de aprender, se comunicar e trabalhar em equipe, visando a reverberação do propósito em mais brasileiros. Venha fazer parte desse movimento!

>> Requisitos importantes: HTML5, CSS3, Git, HTML, CSS (SASS/Less/Stylus)

>> Diferenciais: Metodologias Ágeis, JavaScript avançado, conhecimento em algum framework Javascript, automatizadores de tarefas, outras linguagens (Ruby, Python, PHP, Go)
>>Modelo de contratação: CLT

 >> Local de trabalho: Home Office
>> Para inscrição e mais informações : [https://byintera.in/ront11]
>> Para tirar dúvidas sobre a oportunidade: [https://www.linkedin.com/in/giulia-huoya-8ab1501a6/]
Se essa desafio não te atende, entra em contato conosco com a indicação de um profissional da área! Um sorriso de orelha a orelha. :D

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
