### ISSUE TITLE
[Remoto] Fullstack Developer na Gupy

### ISSUE THREAD

**Issue by FabianaSN** [frontendbr/vagas#5173]
A Gupy é uma startup fundada por profissionais de RH e de Tecnologia, com o objetivo de transformar a maneira como são feitos processos seletivos no Brasil. Afinal, quem nunca participou de um processo seletivo bem bagunçado em sua carreira?

A Gupy desenvolveu s a primeira inteligência artificial para recrutamento e seleção do Brasil, permitindo que empresas encontrem rapidamente os candidatos que têm maior afinidade com suas vagas.

Atualmente estamos em busca de uma Pessoa Desenvolvedora Fullstack que queira nos ajudar a evoluir ainda mais nossa arquitetura de serviços de forma escalável, suportando centenas de milhares de requisições por minuto.

**Vaga:** Pessoa Desenvolvedora Fullstack
**Nível:** Pleno/Sênior
**Modelo de contratação:** CLT
**Requisitos:** Experiência com **React.js e Node.js**, computação em nuvem (preferencialmente AWS) e banco de dados.

**Para mais informações:** https://byintera.in/gupyfsgt

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
