### ISSUE TITLE
 Front-end Developer na Autobem Brasil 

### ISSUE THREAD

**Issue by Rhautobembrasil** [frontendbr/vagas#5175]
**Front-end Developer
Desenvolvedor Front-end**

Nossa empresa
Autobem Brasil

**Local**
Remoto

**Requisitos:**

Conhecimentos necessários em Angular 9
HTML
CSS
Bootstrap
JQuery
Git
Javascript

**Benefícios**
Plano de saúde
Plano Odontológico
VR de R$ 25 dia
...
**Contratação**
CLT
PJ a combinar

**Como se candidatar**
Por favor envie um email para rh@autobembrasil.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor Back-end

**Alocação**
Remoto

**Nível**
Pleno
Sênior
Especialista

**Comment by VitorMiguelPS** [comment]
De acordo com a descrição, o título do e-mail deve ser "Vaga Desenvolvedor Back-end", mas o titulo, e os requisitos da vaga é para Front-end, esté certo?

**Comment by Rhautobembrasil** [comment]
Esses são os requisitos para a vaga! Mas temos vagas para Front-end e Back-end.

**Comment by Rhautobembrasil** [comment]
> De acordo com a descrição, o título do e-mail deve ser "Vaga Desenvolvedor Back-end", mas o titulo, e os requisitos da vaga é para Front-end, esté certo?
