### ISSUE TITLE
[Remoto] PHP Developer na GPS Sat

### ISSUE THREAD

**Issue by gpssat** [frontendbr/vagas#5179]
## Descrição da vaga

Programador(a) para atuar no time de desenvolvimento, manutenção de projetos e banco de dados.

## Local

Remoto

## Requisitos

- Domínio em programação PHP e framework Laravel;
- Domínio de linguagem SQL, em SGBD PostgreSql, incluindo Stored Procedures;
- Familiaridade com CSS, HTML, JavaScript, JQuery;
- Capacidade analítica, compreensão de regras de negócio;
- Domínio de GIT.

**Desejáveis:**

- Conhecimento em banco de dados PostgreSQL;
- Conhecimento básico de HTML/CSSLinguagens e Frameworks de Programação (PHP/Laravel).

**Diferenciais:**
- Experiência em REST APIs usando PHP.
- Inglês Avançado.

## Contratação

- PJ a combinar.
- Horário comercial.

### Experiência

- Júnior
- Pleno

## Nossa empresa

Estamos há 10 anos atuando no desenvolvimento de soluções para gestão e monitoramento de máquinas e veículos.

## Como se candidatar

Por favor envie um email para rh@gpssat.com.br com seu CV anexado e pretensão salarial - enviar no assunto: Vaga PHP

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
