### ISSUE TITLE
[Remoto] Front-End Developer (Sênior/Pleno/Júnior) na oneRhino (Estados Unidos)

### ISSUE THREAD

**Issue by derevandal** [frontendbr/vagas#5183]
## Nossa empresa

oneRhino é uma empresa situada em Crozed, VA. Atende demandas de desenvolvimento web em geral (planejamento e desenvolvimento), trabalhando terceirizado para clientes.

## Descrição da vaga

A vaga é para full-time como front-end júnior/pleno/sênior com experiência avançada em algum framework js, independente de qual.

Hoje há projetos em WordPress e alguns legados, mas as coisas novas estão sendo feitas em Vue também.

Somos bem abertos a tecnologia.

## Local

Remoto, a empresa fica no EUA, tem mais BRs trabalhando também.

## Requisitos

**Obrigatórios:**
- Experiência avançada com algum framework JS (React, Vue, etc)
- Experiência com CSS e HTML avançado, mas não precisa ser um mago do CSS hehe
- Pessoa confiavel
- Boa comunicação
- Inglês intermediário, o necessário para se comunicar. Não precisa ser fluente.
- Saber trabalhar em equipe

**Desejáveis:**
- conhecimentos em backend em qualquer stack.

**Diferenciais:**
- conhecimentos básicos de PHP e WordPress.
- pessoas que estão dispostas a aprender e ajudar os colegas
- pessoa talentosa em seu trabalho

## Benefícios

**Diferenciais:**
- Sem loucura de muitas horas por semana. Conciliar sua vida pessoal e profissional é mais saudável.
- Horário flexivel
- Trabalho estável, garantido e consistente
- Todos se ajudam, respeitam e são amigáveis ​​uns com os outros. Sem grandes egos.

## Contratação

PJ, como é internacional, não tem contrato...
Estou na empresa faz 1 ano, tem gente aqui a 11 anos... Confiável e o pagamento sempre vem certinho.
Tu pode receber pela TransferWise... Estamos tentando ver se rola USDC.
Mesmo assim, a empresa cobre o custo de te mandar a grana do EUA pro BR.

## Como se candidatar

Por favor envie um email para andre.v@onerhino.com com seu CV anexado - enviar no assunto: Front-End Developer Job

Em inglês, ok?

Quem vai ter avaliar é o boss e ele é americano. XD

## Tempo médio de feedbacks

Somos 14 pessoas na empresa, então é rápido o feedback... O DP é o chefe.

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by amandagdev** [comment]
olá, nas label tem junior mas na descrição está pleno/sênior somente

**Comment by derevandal** [comment]
> olá, nas label tem junior mas na descrição está pleno/sênior somente

oi, obrigado por me avisar! hehe
corrigi já, pode júnior também... XD

**Comment by joao160197** [comment]
Pro estágio é obrigado a estar cursando faculdade ?

**Comment by joao160197** [comment]
Em quanto tempo mais o menos vem a resposta  depois de enviar o currículo ?
