### ISSUE TITLE
[Remoto] Front-end Developer na K2Improving

### ISSUE THREAD

**Issue by gabrielbortone** [frontendbr/vagas#5184]
## Nossa empresa

A K2 Improving Performance Consultoria nasceu do sonho de jovens empreendedores obstinados, loucos por mudar o mundo e fazer algo melhor, provar que é possível sim entregar valor, surpreender o cliente, transformar o comum no especial.

De lá para cá é um sucesso atrás do outro, financeiras, seguradora, Governo do Estado de São Paulo e construtoras vem se beneficiando das multiplas atividades empreendidas pela K2iP em seus negócios.

K2 Improving Performance Consultoria de valor - "Nossa companhia está sempre pronta para fornecer a melhor solução para os desafios de nossos clientes ... "​

## Descrição da vaga

Irá atuar com desenvolvimento react native e fará integrações com APIs Restfull

## Local

100% Remoto

## Requisitos

**Obrigatórios:**
- 1 ano de experiência com React Native
- 3 anos de experiência com desenvolvimento
- Bom conhecimento em CSS 3 e HTML 5

**Desejáveis:**
- conhecimentos em TDD
- conhecimentos em Sqlite
- Estrutura de cache de dados

## Benefícios
- Tempo indeterminado

**Diferenciais:**
- 1 hora de almoço

## Contratação
PJ a combinar

## Como se candidatar

Por favor envie um email para rh@k2ip.com.br com seu CV anexado - enviar no assunto: Vaga React Native

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dia após cada processo.
E-mail para contato em caso de não haver resposta: gabriel.bortone@k2ip.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
