### ISSUE TITLE
[REMOTO] Front-end Developer @KaBuM!

### ISSUE THREAD

**Issue by dani10kabum** [frontendbr/vagas#5185]
>

## KaBuM!

Somos pioneiros no comércio eletrônico brasileiro, há 18 anos construindo uma história de sucesso e hoje somos o maior e-commerce do segmento de tecnologia na América Latina!

Somos EQUIPE, somos AGILIDADE, somos TODOS NINJAS!

Somos um time diverso, formado por mais de 1.200 pessoas, obcecados por qualidade, velocidade de entrega e respeito pelo consumidor.

#somostodosninjas #somoskabum #VemproKaBuM

## Descrição da vaga

Grande desafio de trazer novas frentes de sistemas para as operações de E-commerce, trazendo inovação e excelência de entrega. Nosso objetivo no KaBuM! é está sempre se atualizando a frentes de novas tecnologias e ferramentas, integrando o valor mais importante que é a Experiência do Cliente.

## Local

100% Remoto
Escritório, Matriz - Limeira - SP

## Requisitos

**Obrigatórios:**
- Superior completo na área de Tecnologia da Informação
- Linguagem de programação voltado a WEB
- Banco de dados
- Orientação Objeto
- Sólidos conhecimentos em:  JavaScript, React, Redux, Node, CSS, HTML, GIT e SCRUM
- Criação de código limpo, legível e cross-browser
- Experiência com desenvolvimento de sites responsivos

**Desejáveis:**
- Levantar requisitos de software com os envolvidos nos projetos de sistemas
- Desenvolver sistemas de informação visando atender necessidades das áreas da empresa
- Implementação e boas práticas de SEO
- Analisar requisitos e modelar a arquitetura do sistema a ser desenvolvido
- Otimizar e manter sistemas legados
- Estudar e levantar propostas de melhorias para sistemas legados e novos sistemas
- Testar os sistemas desenvolvidos visando garantir sua qualidade
- Participar do processo de implantação de sistemas, visando garantir seu pleno funcionamento
- Descrever funcionalidades dos sistemas através de documentações e garantir a integridade dos sistemas
- Desenvolver layouts baseado nos assets enviado pelo time UX/UI

**Diferenciais:**
- Projetos opensource em Styled-component, SSR, SASS, Redux-Sagas

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ 15/dia
- Plano Odontológico

**Diferenciais:**

- Prime Ninja: Com descontos exclusivos

## Contratação

CLT - salário a combinar 

## Como se candidatar

Por favor entre em contato por [LinkedIn Danilo](https://www.linkedin.com/in/danilooscarjustino/) e [LinkedIn Leticia](https://www.linkedin.com/in/leticiacunhag/) ou envie um e-mail para danilo.justino@kabum.com.br seu CV anexado - enviar no assunto: Vaga DEV Frontend

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: danilo.justino@kabum.com.br

#### Alocação

- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
