### ISSUE TITLE
[Remoto] Front-end Developer Vue.js na BEYOND SOLUÇOES

### ISSUE THREAD

**Issue by Mariana9852** [frontendbr/vagas#5188]
## BEYOND SOLUÇOES

Já pensou em fazer parte de uma empresa que vai ALÉM de uma consultoria tradicional de outsourcing?
Nós da BEYOND estamos presentes nas principais organizações do mercado de investimentos e fintechs. Aqui, você irá atuar no maior Banco de Investimentos da América Latina, presente em 16 países, que preza por um time de alta qualidade e performance para solucionar grandes desafios. 

## Descrição da vaga

Desenvolvedor Front end Vue.js

Requisitos:

	• Experiência com Front End com VueJS
	• Experiência com JavaScript, HTML, CSS
	• Integrações com API REST, back end em ASP.NET MVC
	• Habilidades com layouts responsivos
	• Testes Unitários

## Local

 Remoto 

## Requisitos

**Obrigatórios:**

 Experiência com Front End com VueJS
Experiência com JavaScript, HTML, CSS

## Benefícios

- Benefícios 100% subsidiados pela BEYOND  
- Plano de saúde e odontológico Sul américa 
- Seguro de vida
- R$: 800,00 (podendo ser distribuído em VR ou VA)

## Contratação

CLT ou PJ

## Como se candidatar

Por favor envie um email para mariana.lemos@imaginebeyond.com.br  com seu CV anexado - enviar no assunto: Vaga Front End Vue.js

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 04 dias após cada processo.
E-mail para contato em caso de não haver resposta: mariana.lemos@imaginebeyond.com.br

## Labels

- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
