### ISSUE TITLE
[Remoto] Front-End Developer ReactJs Vuejs na Muvz 

### ISSUE THREAD

**Issue by BrendonHenrique** [frontendbr/vagas#5190]
## Nossa empresa

A [Muvz](http://www.muvz.com.br/) tem a missão de antecipar o futuro através de soluções digitais para um presente melhor.
Atuamos na construção de soluções que criam realidades através do design, inovação e tecnologia para acelerar os processos de transformação.
Acreditamos que nos colocar no lugar do outro nos ajuda a compreender melhor os problemas e as necessidades para, então, colaborar em busca de soluções melhores com dinâmicas de trabalho modernas baseadas na descoberta.

## Descrição da vaga

A vaga é destinada aos devs que possuam conhecimentos sólidos em Vuejs 
e ReactJs. 
A Muvz é uma consultoria e nela prestamos serviços digitais para outras empresas, essa vaga é destinada para trabalhar na [Omint](https://www.omint.com.br/en/), cujo é uma empresa do ramo da saúde. Ela oferece planos de saúde para pessoa física e jurídica, e é vitalmente focada em clientes classe A ( o ticket médio dos planos é de 2k+/mês).
A equipe desse cliente é rasoavelmente pequena, logo estamos buscando expandir, trazendo novos devs pra equipe.

Temos dois projetos, um já estável e o outro em fase de desenvolvimento, o primeiro é um PWA com Vue e o outro é um SSR feito com Nuxtjs.

O PWA é feito com Vue CLI
o SSR é feito usando JSX(render functions) + Typescript + Nuxt + Vue Styled Components.

## Local

Remoto

## Requisitos

**Obrigatórios:**

- Experiência com Vuejs && React 
- Experiência com HTML
- Experiência com CSS e algum pré-processador 
- Experiência com Eslint/Prettier  
- Experiência com Typescript e ES6
- Experiência com Nuxtjs || NextJs
- Experiência com Webpack / Babel 
- Experiência com Styled Components 
- Saber como usar Figma
- Consumo de API Restfull ( Usamos Axios )

**Diferenciais:**

- Conhecimento em Flutter 
- Bom conhecimento em arquitetura de software
- Conhecer Clean Code 
- Entender o que é Solid

## Contratação

PJ ou CLT ( a combinar )

## Como se candidatar

Clique aqui para se cadastrar https://lnkd.in/dr6cTEP e seja um Muvzee 👽

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta:  recrutador@muvz.com.br ou bhssilva@inf.ufpel.edu.br

#### Alocação

- Remoto

#### Regime

- CLT
- PJ

#### Nível

- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
