### ISSUE TITLE
[Remoto ] Front-end Developer React, React Native e Node perfil Pleno/Sênior na Iventis

### ISSUE THREAD

**Issue by cimerio** [frontendbr/vagas#5194]
Frontend React, React Native e Node perfil Pleno/Sênior
100% Remoto - PJ
CV para recrutamento@iventis.com.br

HTML, CSS e JavaScript;
jQuery;
ES6;
Pré processadores CSS, de preferência SASS;
CSS-In-JS (Styled Components);
Integrações de APIs REST;
Otimização de performance (semantic code, best practices);
Versionamento via git

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
