### ISSUE TITLE
[Remoto] Front-End Developer (Vue e React) na Stefanini

### ISSUE THREAD

**Issue by lorealmeida** [frontendbr/vagas#5195]
> Vaga 100% Remota

## Nossa empresa

Aqui na #Stefanini, acreditamos que para cocriar é necessário existir diferentes formas de pensamento! Entendemos que as diferenças tornam as pessoas únicas e, por isso, não fazemos qualquer distinção entre nossos candidatos. 

## Descrição da vaga

Profissional fará parte de um projeto fresquinho em um novo cliente, com equipe auto gerenciável, dinâmica e com sede de fazer o melhor!

## Local

- Remoto

## Requisitos

**Obrigatórios:**
- Graduação completa em TI
- Experiência sólida com Vue
- Experiência sólida com React native
- Bootstrap
- Javascript
- CSS
- HTML 5

**Desejáveis:**
- Conhecimento com back-end Java
- Certificação na área de atuação

**Diferenciais:**
- DevOps
- Jenkins
- Openshift
- Conceito de CI/CD

## Benefícios

- Plano de saúde - extensivo à dependentes
- Plano odontológico - extensivo à dependentes
- Seguro de vida
- VR/VA vide CCT do estado de residência

**Diferenciais:**
- Horário flexível
- Reembolso certificação
- Academia interna com mais de 300 cursos
- Convênios com Gympass, Alura, entre outros...

## Contratação

- CLT

## Como se candidatar

Por favor envie um e-mail para lsalmeida@stefanini.com com seu CV anexado - enviar no assunto: DEV Front-end Vue React

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
