### ISSUE TITLE
[ São Paulo ] IOS Developer na DescompliTI

### ISSUE THREAD

**Issue by Descompli** [frontendbr/vagas#5196]
> Vaga totalmente remota

## Descrição da vaga

Nativo 0 Cliente C&A, 100% remoto, exp com swift.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência com Swift

## Contratação

PJ ou Cooperado

## Como se candidatar

Por favor envie um email para hunting@descompliti.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor IOS
## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.

- Remoto

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
