### ISSUE TITLE
[Remoto] Front-end Developer na Pegaki

### ISSUE THREAD

**Issue by KellyKuhn** [frontendbr/vagas#5197]
`[REMOTO] Front-End Developer na PEGAKI`

## Nossa empresa

A Pegaki é uma startup de tecnologia que conecta transportadoras, centros de distribuição, embarcadores e pontos de coleta. Com a nossa tecnologia logística, ajudamos o mercado a reduzir custos de frete, contribuindo para criar uma distribuição mais eficiente e um mundo mais sustentável.
Em 4 anos de operação já impactamos a vida de MILHÕES de pessoas, e a nossa missão de descomplicar e melhorar a experiência logística, de quem compra ou vende pela Internet, está apenas começando. 
Em 2021, para acelerar o nosso crescimento, iniciamos um movimento de consolidação como grupo, com a fusão com a Intelipost, scale-up brasileira de tecnologia que está transformando a logística no país! 

## Descrição da vaga

Sua missão como Frontend Engineer Sr será propor e desenvolver soluções inovadoras, com o objetivo de tornar a Pegaki a empresa líder em tecnologia inteligente para logística no mundo.

## Local

Remoto 

## Requisitos

**Obrigatórios:**
- Experiência consolidada com Framework Javascript, ES6, HTML5, CSS3/SASS (VueJS and Flutter seria um plus);
- Trabalhar com gerenciadores de tasks como Webpack;
- Conhecer e estar disposto a aplicar novos conceitos como Microfrontend, Jamstack e PWA;
- Experiência significativa com aplicações Web modernas e APIs REST (JSON), ferramentas de testes como Jest e outras;
- Experiência em metodologias ágeis de desenvolvimento (Scrum, Kanban);
- Estar alinhado com conceitos de aplicações responsivas.

**Desafios:**
- Criação de componentes e bibliotecas modulares reutilizáveis;
- Arquitetura eficiente e reusável para entregar web application complexos;
- Implementação de testes automatizados integrados aos fluxos de trabalho de desenvolvimento e manutenção;
- Trabalhar próximo do time de UI/UX;
- Colaboração com os outros times para entender como entregar uma ótima experiência para nossos clientes;
- Participar ativamente no desenvolvimento da plataforma de analytics;
- Manter-se atualizado com todos os desenvolvimentos recentes no espaço JavaScript e Vue.js.

**Tecnologias utilizadas para esta posição:**
- Vue - Frontend Applications & SPA

## Benefícios

- Plano de saúde (para você e quem você ama);
- Convênio odontológico; 
- VR/VA Flex (sem desconto em folha);
- Seguro de vida;
- Auxílio Creche;
- Day off no mês do aniversário;
- Além disso, temos um ambiente totalmente aberto, com oportunidade de muito aprendizado e crescimento!

**Diferenciais:**
- Flexibilidade de horário;
- Trabalho 100% remoto.

## Contratação

CLT

## Como se candidatar

Por favor candidate-se pelo link https://pegakicarreiras.gupy.io/jobs/992977?jobBoardSource=gupy_public_page

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.
E-mail para contato em caso de não haver resposta: kelly.kuhn@pegaki.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
