### ISSUE TITLE
[Remoto] Front-end Developer foco em BigCommerce na App Masters com 

### ISSUE THREAD

**Issue by TiagoGouvea** [frontendbr/vagas#5199]
## Nossa empresa

A App Masters é uma empresa focada no desenvolvimento de aplicações web e mobile. Temos uma equipe pequena mas altamente capacitada, que busca entregar produtos sempre com alta qualidade e grande valor agregado.

Preferimos trabalhar com poucos projetos em paralelo, dois ou três no máximo para toda a equipe. Somos ágeis portanto um dos nossos diferenciais é o tempo curto de entrega. Nosso foco é trabalhar apenas com clientes de fora do Brasil.

Amamos a stack JavaScript e utilizamos um grande leque de ferramentas deste ecossistema. Gostamos que nossos desenvolvedores estudem e aprendam continuamente, por isso temos alguns "side projects" (esta plataforma que você está usando, por exemplo), que vamos criando e melhorando de tempos em tempos.

Somos muito envolvidos com a comunidade de desenvolveres, já realizamos diversos treinamentos gratuitos de React, e estamos sempre apoiando iniciativas para novos programadores.

#### Você encontra aqui

Para os desenvolvedores, a empresa busca ser a melhor opção de trabalho para aprender, ensinar, crescer e se divertir enquanto atendemos as demandas dos clientes.

Queremos manter o time com alta motivação, interesse e capacidade constante para resolver problemas. Para isso provemos um ambiente descontraído e tranquilo para trabalhar, com computadores de última geração, café e biscoito a vontade!

## Descrição da vaga

Nesta oportunidade você trabalhará diretamente conosco e uma **empresa parceira do Canadá**, desenvolvendo e-commerces utilizando a plataforma **BigCommerce**.

Para esta vaga em específico, é preciso estar disposto a aprender como funciona o BigCommerce.

O BigCommerce oferece um grande leque de recursos para criação das lojas online sem precisar começar do zero. As customizações se dão através dos "temas" e "apps". Os temas são desenvolvidos usando Stencil e Handlebars, para manter a lógica de view bem separada. Os Apps podem serem feitos com React e Node.

As primeiras semanas serão totalmente focadas em estudo e experimentação, com o objetivo de alcançar a **certificação em BigCommerce**. Te daremos total suporte para isso e comemoraremos 🎉 quando você se certificar.

Investiremos também no seu inglês, com professores brasileiros e nativos americanos, para que possa alcançar um nível ainda melhor.

Nosso foco é ter candidatos que queiram seguir na empresa por um longo período, que busquem ter um trabalho estável e duradouro. Buscamos programadores realmente interessados em aprender sempre, que valorizem um ambiente de trabalho livre de stress e de cobranças desnecessárias, e que queiram voar conosco!

## Local

- Remoto forever, com encontros anual da empresa

## Requisitos

**Obrigatórios:**
- Nível avançado de inglês escrito e falado
- Prática trabalhando com e-commerces, em qualquer tipo de plataforma ou linguagem

**Diferenciais:**
- conhecimentos em Shopify ou BigCommerce

## Benefícios

- Plano de saúde
- VR de R$300,00
- 14º Salário
- Co-participação em consultas médicas
- Bonus de final de projeto

**Diferenciais:**
- Empresa livre de stress
- Incentivo para certificações
- Ajuste de tempo (em dias de provas ou outras necessidades)
- Plano de carreira para crescimento contínuo

## Contratação

- CLT - Remuneração entre De R$4.300 até R$6.000

## Como se candidatar

Acessar a plataforma [Programadores em Juiz de Fora](https://programador.emjuizdefora.com/oportunidade/desenvolvedor-fullstack-javascript-com-foco-em-e-commerce), se registrar, e se candidatar na vaga em seguida.

## Tempo médio de feedbacks

- Em até 48 horas você será entrevistado, por whatsapp ou video;
- Nas 48 horas seguintes você saberá se irá avançar ou não no processo de seleção;
- Em no máximo 5 dias você saberá se foi o escolhido ou não.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by TiagoGouvea** [comment]
Alô Felipe. Já podemos fechar por aqui.
Valeu!
