### ISSUE TITLE
[San Francisco] - Full Stack - Sr. Software Development Engineer

### ISSUE THREAD

**Issue by rturk** [frontendbr/vagas#52]
## Descrição da vaga

We are looking for Software Development Engineers that thrive in fast-paced environments and are passionate about working with pre-market technologies. Successful candidates will be much more than just developers, they will bring with them deep technical fundamentals, experience with complex mobile, distributed systems, and a well-rounded software engineering background that spans disciplines.

We are looking for a Sr. Developer that will help us with our international expansion.

## Location

San Francisco -  901, Mission street #suite 12

## Perks

- Cool working place
- Open schedule. Just deliver your code and you're done

## Mandatory Qualifications

- BA/BS in Computer Science or related discipline, or equivalent work experience.
- Strong skill in Javascript, NodeJS, CSS, Less, React.
- 7+ years of software development experience
- Fluent in English 

## Expected qualifications 

- This position will work with designers, however we expect exceptional design skills
- Comfortable in fast-paced, start-up like development environments.
- Experience in software development on devices/products in real-time operation system.

## Contratação

Full time employee

## About us

Entria (https://www.entria.com.br) is a leading Mobile Provider. We make really cool apps
We manage complex projects, and yes we deliver.

## How to apply for this job

Just drop us a note at rh@entria.com.br please attach CV our link to github projects, previous projects

**Comment by rturk** [comment]
Clarifying some questions received from candidates. This job offer includes relocation package.

**Comment by rturk** [comment]
Closed! Fantastic! Thanks for all the candidates that applied!!!! 
**More openings soon!**

**Comment by LFeh** [comment]
\o/

**Comment by Mendrone** [comment]
:confetti_ball:

**Comment by renatogalvones** [comment]
👏 👏 👏

**Comment by camilatigre** [comment]
@rturk 

FrontEndBR is trying to mesure how many job offers are being close by this issue. If you can help, answer this:

The person hired for the position was found on this issue?
a) Yes
b) No
c) Not sure
