### ISSUE TITLE
[Remoto] Frontend React Developer (Pleno) na Confitec

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#5200]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedora-react-pleno-194128261?origin=github&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Desenvolvimento de sistemas da nova plataforma de um de nossos principais clientes.</p>

## Confitec: 
 <p>A Confitec possui fábrica de Software que trabalha com as mais reconhecidas metodologias de desenvolvimento.</p>
<p>Através de processos e procedimentos, nossos produtos são gerados e controlados em todas as fases do processo de construção, levando como ponto principal o atendimento dos requisitos técnicos e funcionais, visando sempre a qualidade e cumprimento dos prazos. Nosso processo de desenvolvimento passa por criteriosas validações de requisitos, baseado em planos de testes bem definidos, bem como um code review dos códigos desenvolvidos por nossos profissionais. Com todo este processo temos obtidos excelentes resultados de qualidade no desenvolvimento.</p><a href='https://coodesh.com/empresas/confitec'>Veja mais no site</a>

 ## Habilidades: 
 - HTML 5 
- Javascript 
- React.js 
- Redux
## Local: 
 100% Remoto
## Requisitos: 
 - React + Redux 
- Sólido conhecimento em HTML e CSS 
- JavaScript Avançado (ES6 + ES7) 
- Familiaridade com APIs RESTFull
**Diferenciais:** 
 - GIT. 
- Web API’s. 
- AWS. 
- SASS 
- Metodologia BEM CSS 
- Conhecimento em metodologia ágil. 
- Material-UI
## Benefícios: 
 - Vale Refeição ou Alimentação ( Você escolhe) 
- Vale Transporte 
- Plano de Saúde 
- Plano Odontológico 
- PLR 
- Day off 
- Prezamos pelo aprendizado e especialização, através do Programa de Treinamentos e diversas parcerias com Instituições de Ensino. 
- Possibilidade de home office
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend React Developer (Pleno) na Confitec](https://coodesh.com/vagas/desenvolvedora-react-pleno-194128261?origin=github&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção <b>Pedir Feedback</b> entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa <b>Recruiter</b> responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Nível
Pleno
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
