### ISSUE TITLE
[Home Office] Front-end Developer na NTConsult

### ISSUE THREAD

**Issue by 1975-2004** [frontendbr/vagas#5202]
Javascript ES6 +
• CSS e SCSS
• Conhecimento de Frameworks JS (React, Angular ou Vue)
• Publicar pacotes NPM
• Rollup e Webpack
• Dactilografado
• CSS em JS (Emotion, Styled Components)
• Módulos CSS
• Jenkins
Diferencial:
• Docker
• Kubernetes

Local
Remoto 100%

Benefícios
Plano de saúde
Seguro de vida
VR de R $ X / dia
Requisitos
Diferenciais:
Docker
• Kubernetes

Contratação
▶ Modelo de contratação: CLT, PJ ou Cooperado.

Nossa empresa
A NTconsult é uma empresa com 18 anos no mercado, global de tecnologia presente em 8 Países com parceria e selo Platinum CAMUNDA.
▶Trabalho 100% remoto, em qualquer lugar do Brasil.
▶ Modelo de contratação: CLT, PJ ou Cooperado.
▶Currículos: Luciana.prudente@ntconsult.com.br
▶ Vem não o que é: (21) 99090-9434

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
