### ISSUE TITLE
[Remoto] Front-end Developer na ABYX HAUS

### ISSUE THREAD

**Issue by taedennis** [frontendbr/vagas#5204]
## Nossa empresa

A ABYX HAUS é uma agência digital fundada em 2012 focada em soluções tecnológicas para empresas, incluindo desenvolvimento de websites, e-commerce, sistemas e aplicativos, atendendo pequenas, médias e grandes empresas principalmente em São Paulo/SP.

## Descrição da vaga

Estamos em busca de jovem talentoso para fazer parte da nossa equipe de desenvolvedores para aplicação de layout em Wordpress, plataformas de e-commerce e sistemas, além de auxiliar em atendimento à chamados para atualizações.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Conhecimentos fundamentais em HTML, CSS, JS
- Experiência em Wordpress

**Desejáveis:**
- Noções em PHP e banco de dados MySQL

**Diferenciais:**
- Noções em software de edição de imagens
- Experiência em desenvolvimento de websites

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para rh@abyx.haus com seu CV anexado - enviar no assunto: Vaga Front-end Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias úteis após cada processo.
E-mail para contato em caso de não haver resposta: tae.dennis@abyx.haus

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
