### ISSUE TITLE
[Remoto] Front-end Mobile React Native na Nave.rs

### ISSUE THREAD

**Issue by BrunaSouzaPaes** [frontendbr/vagas#5205]
Remoto durante ou após pandemia 
> 

## Nossa empresa

O time da Nave é experiente e atua como uma consultoria em todos os momentos do desenvolvimento das soluções. Somos especialistas na construção de produtos digitais utilizando o que há de mais inovador no mercado de aplicativos e sistemas.

## Descrição da vaga
Pensou em trabalhar em um ambiente colaborativo, dinâmico, com muito aprendizado e autonomia? Neste momento estamos buscando uma pessoa com experiência para atuar na área de Mobile. Você irá atuar desenvolvendo aplicativos utilizando o React Native. Além de aprender as melhores praticas que são utilizadas no desenvolvimento de aplicativos. 

## Local

100% Remoto 

## Requisitos

**Obrigatórios:**
- Javascript;
- ReactJS;
- React Native;
- Styled Components;
- Boa comunicação

**Diferenciais:**
- Context API;
- Hooks;
- Conhecimento básico na stack iOS e Android para o desenvolvimento com React Native

## Benefícios

- Plano de saúde (Cooperação com o plano da Unimed, 60% é pago pela empresa 40% é pago pelo membro)
- Plano de Carreira
- VR / VA de R$ 23/dia
- Acesso a plataforma Alura Cursos
- Aulas de Inglês
- Acesso a Vittude, auxilio psicológico direto na plataforma  

**Diferenciais:**
- Horários Flexíveis 
- 100% Remoto
- Plano de carreira estruturado
- Hierarquia Horizontal 

## Contratação

CLT ( faixa salarial de R$1.571,55 até R$2.640,21 + benefícios) 

## Como se candidatar

inscreva-se através desse link: [link aqui ](https://nave-team.gupy.io/jobs/1016584)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
-  Mobile Júnior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
