### ISSUE TITLE
[Campo Largo/PR] FullStack Developer na Exitoinf

### ISSUE THREAD

**Issue by Jociel-Adachi** [frontendbr/vagas#5206]
> Vaga Remota durante a pandemia

## Nossa empresa

Na Exitoinf desenvolvemos sistemas para gestão de postagens e envios de AGFs, Transportadoras, Marketplaces e E-commerce.

## Descrição da vaga
- Análise, correção e desenvolvimento de novas funcionalidades para Sistemas Web e Mobile em NodeJS, ReactJS e React Native
- Reuniões cíclicas de feedback e de levantamento de RF, RNFs e Regras de Negócios;

## Local

Remoto ou Escritório, Paraná, Campo Largo, Vila Bancária

## Requisitos

**Obrigatórios:**
- Forte experiência em desenvolvimento em NodesJS, React, React Native e Banco de Dados Mysql, versionamento com GitHub.

**Desejáveis:**
- conhecimentos em C#, PHP.
- Plataforma de gerenciamento de projetos ClickUp
-  Framework SCRUM.

## Contratação

- PJ a combinar
- Início imediato
- Salário varia de acordo com experiência do Dev.

## Como se candidatar

Por favor envie um email **com a pretenção salarial** para gerenciaprojetos@exitoinf.com com seu CV anexado - enviar no assunto: Vaga Fullstack

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dias após cada processo.

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
