### ISSUE TITLE
[Remoto] Full Stack Rails Developer na Worldpackers

### ISSUE THREAD

**Issue by joaomm** [frontendbr/vagas#5207]
> Vaga Remota (maior parte do time próximo a São Paulo)

## Nossa empresa

Nosso objetivo na Worldpackers é ajudar o máximo de pessoas a viajar, viver experiências transformadoras e impactar o mundo positivamente através do voluntariado. Somos uma comunidade de mais de 2.500.000 viajantes e anfitriões trocando habilidades por acomodação ao redor do mundo. São milhares de NGOs, fazendas orgânicas, hostels e projeto sociais e ecológicos em mais de 140 países.

Temos um time de tecnologia enxuto e bem experiente focado em boas práticas de programação, código limpo e melhoria contínua. Buscamos lançar atualizações todos os dias e acompanhar os dados e feedbacks dos nossos usuários.

## Descrição da vaga

Buscamos alguém para focar em Ruby/Rails em toda nossa stack e desenvolver nossa plataforma WEB e APIs para nossos aplicativos. Trabalhamos com ElasticSearch, Solr, Rspec, Capybara, Interactors, Heroku.

## Local

Remoto (maior parte do time em torno de São Paulo)

## Requisitos

**Essa vaga é perfeita para você, se você tecnicamente:**
- Tem fluência com Ruby / Rails
- Pira quando vê uma enorme bateria de testes automatizados verdes
- Ama fazer muitos deploys por dia
- Respira código limpo
- Quer fazer/saber de tudo um pouco (front, back, APIs,  infra, etc)
- Gosta de participar ativamente das decisões técnicas de produto, priorização de débitos técnicos, definição de arquitetura e melhoria contínua do processo ágil de desenvolvimento.

**Também é perfeita para você, você pessoalmente**
- Acredita em colaboração, diversidade e aprendizado contínuo.
- Gosta de trabalhar remotamente, mas sempre quer se sentir próximo do time.
- É apaixonadx pela ideia de usar tecnologia para impactar a vida de milhões de pessoas ao redor do mundo
- Trabalha com autonomia & responsabilidade, participando ativamente das decisões do time
- Toma decisões baseadas em dados e feedback de usuários
- Tem um mindset de melhoria contínua, sempre desenvolvendo seus skills e entendimento do mercado & negócio
- Gosta de compartilhar conhecimento e aprender com o time
- Quer trabalhar com propósito com gente realmente boa!
- Gosta de trabalhar em uma empresa menor em que você sente todos os dias seu impacto na vida dos usuários

## Contratação

PJ a combinar

## Como se candidatar

Por favor, preencha esse formulário: [](https://forms.gle/PzWKUCnYYKVwyK2v5)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em torno de 1 ou 2 dias.
E-mail para contato em caso de não haver resposta: tech@worldpackers.com

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
