### ISSUE TITLE
[Remoto] Front-end Developer na Mercafacil PL/SR

### ISSUE THREAD

**Issue by Mirelle104** [frontendbr/vagas#5208]
A Mercafacil está buscando um super profissional para compor nosso time de Desenvolvimento! Se você é ligadx em tecnologia, não tem medo da inovação e quer dominar o mundo, seu lugar é aqui! 

Sua missão será participar do desenvolvimento de todas as interfaces Web de as aplicações e produtos da Mercafacil, irá desenvolver componentes reutilizáveis com testes automatizados para garantir a estabilidade do sistema. Deverá também participar ativamente nas decisões técnicas e de designer sobre ferramentas e abordagens que visam otimizar a performance do sistema e a experiência do usuário.

Responsabilidades e atribuições:

* Desenvolvimento em VueJS;
* Desenvolvimento em React e React Native Web;
* Desenvolvimento usando Apollo para interagir com os backends em GraphQL;
* Desenvolvimento de componentes reutilizáveis e integrados com ferramentas como o Storybook;
* Desenvolvimento de testes automatizados para os componentes/telas;
* Manutenção, evolução e otimização das telas atuais de todos os produtos da Mercafacil.

Experiência:

* Experiência em desenvolvimento de SPAs em VueJS ou React/React Native;
* Experiência em desenvolvimento de componentes reutilizáveis;
* Experiência em testes automatizados.
 
Habilidades Técnicas:

* Desenvolvimento de aplicações WEB com alguma das tecnologias acima citadas;
* Integração com APIs REST (manutenção nas definições OpenApi/Swagger);
* Integração com APIs GraphQL.

Desejável:

* Desenvolvimento com Apollo e GraphQL;
* Construção de componentes utilizando o Storybook.

Ressaltamos que não temos posição em exclusivo para PCD, pois todas as nossas posições são para todxs!
Então candidate-se na que mais combina contigo (:

Benefícios:

CLT;

Plano de saúde;

Plano odontológico;

Seguro de vida;

Benefícios flexíveis - Cartão Caju:

VR / VA / Mobilidade (combustível e uber);

Day off;

Parcerias exclusivas;

Home-office;

Carga horária flexível.

## Como se candidatar

Por favor envie um email para mirelle.lima@mercafacil.me com seu CV anexado - enviar no assunto: Front-end Developer ;
Ou se candidate pelo https://jobs.quickin.io/mercafacil/jobs/60ad6928a55c950012c9a2d5

**Comment by Mirelle104** [comment]
#vempramerca

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
