### ISSUE TITLE
[Remoto] Full-Stack Developer na Mercafacil

### ISSUE THREAD

**Issue by Mirelle104** [frontendbr/vagas#5209]
A Mercafacil tem o objetivo de dominar o mundo e a gente sabe que não tem como fazer isso sem um produto que funcione (quase) perfeitamente, que só conquistamos com os melhores mestres no desenvolvimento.

Como full stack aqui na Mercafacil, sua missão será trabalhar em sistemas que auxiliem nossos processos internos, casa bem arrumada é sinônimo de sucesso. O sistema de integração e processamento de dados da merca opera com quantidades massivas de dados e trata informações de maneira generalizável, portanto, os desenvolvedores da nossa equipe monstra de EngOps irão construir sistemas full stack para auxiliar nesse processo! 
Legal né? Quer fazer parte da revolução no varejo? Então vem pra merca!

Principais atividades:

* Desenvolver APIs em GraphQL para configuração do sistema;
* Desenvolver aplicações em VueJS para interagir com as APIs;
* Desenvolver automatizações em Python para auxiliar na investigação de problemas;
* Desenvolver aplicações na Google Cloud;
* Desenvolver sistemas de monitoramento e alertas;
* Desenvolver DAGs no Apache Airflow;
* Evolução dos bancos de dados em MongoDB e Clickhouse;
* Operação de sistemas Linux e Windows;
* Automatizações com VPNs;

Requisitos
Requisitos / Diferenciais:

Desenvolvimento em NodeJS:
* Express
* Apollo-Server

Desenvolvimento na linguagem Python utilizando as seguintes bibliotecas/frameworks:
* SQLAlchemy
* Pandas

Conhecimento em Docker;
Desenvolvimento em APIs GraphQL;
Conhecimentos em SOs (Linux e Windows);

Diferencial conhecimento nos seguintes banco de dados:
* MongoDB
* Clickhouse

Diferencial conhecimento em monitoramento de aplicações:
* Stack Statsd ou equivalente
* Grafana
* Jaeger

Diferencial conhecimento nos serviços da Google Cloud:
* Kubernetes
* Cloud Storage

Diferencial conhecer o Apache Airflow;

Habilidades Técnicas:

* Experiência com desenvolvimento de aplicações Python e NodeJS;
* Experiência com desenvolvimento Front-End em React/Vue;
* Experiência com manutenção em sistemas operacionais Linux e Windows.

Habilidades Comportamentais:

* Proatividade nas etapas de levantamento de requisitos, desenvolvimento e testes de sistemas;
* Comunicabilidade;
* Habilidades em difusão de conhecimento;
* Comprometimento com prazos.

Ressaltamos que não temos posição em exclusivo para PCD, pois todas as nossas posições são para todos... 
Então candidate-se na que mais combina contigo ;)

Benefícios:
CLT;

Plano de saúde;

Plano odontológico;

Seguro de vida;

Benefícios flexíveis - Cartão Caju:

VR / VA / Mobilidade (combustível e uber);

Day off;

Parcerias exclusivas;

Home-office.

## Como se candidatar

Por favor envie um email para mirelle.lima@mercafacil.me com seu CV anexado - enviar no assunto: Vaga Full-stack Developer ;
Ou no link: https://jobs.quickin.io/mercafacil/jobs/60ad3061a55c950012c97ce2

**Comment by Mirelle104** [comment]
#vempramerca

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by Mirelle104** [comment]
#vempramerca

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by Mirelle104** [comment]
#vempramerca

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
