### ISSUE TITLE
[Home Office] Angular Developer na Segundo Andar

### ISSUE THREAD

**Issue by lfavery** [frontendbr/vagas#521]
FORMATO: 100% HomeOffice (CLT ou PJ)
. HORAS DE TRABALHO: mínimo de 4 horas diárias
. SALÁRIO: à combinar

SOBRE A VAGA / EMPRESA
Somos uma Agência Digital de pequeno porte em crescimento e estamos contratando um desenvolvedor(a) com sólidos conhecimentos em Angular 2 ou 4. Buscamos alguém que possa trabalhar no formato Home Office, Work hard but play harder!!

Estamos focados no desenvolvimento de produtos e por isso um perfil pró-ativo, focado em projetos de e-commerce serão considerados diferenciais. Estar disposto a encarar os desafios e ter perfil hands-on são bem-vindos.

QUALIFICAÇÕES
. Conhecimento avançado em Angular 2 ou 4 com TypeScript e Nodejs (com experiencia comprovada)
. Conhecimento em Angular 2 ou 4 Universal para robots
. Consumo de dados via RESTful web services
. Ambiente linux para desenvolvimento e deployment de projetos
. GIT
. Nginx 

RESPONSABILIDADES
. Escrever códigos estruturados e escalonáveis que possam ser facilmente integrados e distribuídos
. Executar possíveis melhorias e correções em códigos já escritos
. Participar do desenvolvimento de integrações com outras interfaces de aplicações
. Reportar-se ao Líder de Projetos

DESEJÁVEL

. Flexibilidade para trabalhar em time
. Espírito de Equipe, estar apto a colaborar com skills complementares
. Agilidade para realizar ações corretivas
. Atenção e foco nas atividades para evitar erros e distrações
. Boa comunicação e habilidades de apresentar pontos de vista.

## COMO SE CANDIDATAR
Por favor candidate-se pelo link https://www.freelancermap.com/it-projects/projects/development/1406381-projekt-desenvolvedora-angular-2-4-remote-job.html

**Comment by ygorlazaro** [comment]
Eu tenho background em Angular 1, Vue.JS e React no front (além de JS puro), e .NET e NodeJS no backend. Poderia me candidatar?

**Comment by lfavery** [comment]
Oi @ygorlazaro, eu estou ajudando a divulgar a vaga, mas não participo do processo de seleção. Eu acredito que não custa nada se candidatar e mostrar que você topa o desafio e está disposto a assumir as responsabilidades descritas na vaga.

**Comment by ygorlazaro** [comment]
@lfavery perfeito, obrigado!

**Comment by victorhcosta** [comment]
@lfavery você teria alguma forma de contato, de algum membro do time da Segundo Andar?

**Comment by vinyguedess** [comment]
A vaga ainda está aberta ?

**Comment by lfavery** [comment]
@vinyguedess A vaga ainda esta aberta na plataforma e da para se candidatar, mas vou entrar em contato com o cliente hoje para ver se ele fechou com alguem.

**Comment by GigaMax13** [comment]
@lfavery "This project is archived and not active any more." 👎

**Comment by netstart** [comment]
cv: https://www.linkedin.com/in/claytonpassos

**Comment by netstart** [comment]
Angular 2+, IONIC 3, Java, NodeJS, to disponível.

**Comment by LFeh** [comment]
@lfavery ta ativo?

**Comment by lfavery** [comment]
@LFeh Nao esta!
