### ISSUE TITLE
[Joinville] Front-end Developer na SoftExpert Excellence Suite

### ISSUE THREAD

**Issue by TbuenoSoftExpert** [frontendbr/vagas#5211]
Exemplo: [Joinville] Front-End Developer na SoftExpert Excellence Suite 

> Vaga 100% Remota 

## empresa
A SoftExpert é líder de mercado em soluções para a excelência na gestão, fornecendo software e serviços para o aprimoramento de processos de negócio, conformidade regulamentar e governança corporativa, sendo solução mais abrangente do mercado, assegurando a seus clientes o máximo de retorno sobre seus investimentos.

## Atividades
Desenvolver e manter código frontend web;
Criar testes e executar os mesmos para garantir qualidade e conformidade dos requisitos desenvolvidos;
Auxiliar equipe de serviços no suporte a clientes, orientando-os quando as suas dúvidas e problemas a respeito do funcionamento dos sistemas e ambientes;
Estimar esforço para desenvolvimento de requisitos;
Entregar requisitos acordados livre de bugs e dentro do prazo;
Revisar códigos da equipe garantindo boas práticas e qualidade do código;
Participar da definição de planejamento de entregas (sprints) e validação de entregas (sprint review);
Realizar pequisa e avaliação de novas tecnologias e componentes para desenvolvimento de software;
Interagir com equipe para feedback constante (sprint retrospect);
Participar do entendimento da necessidade de clientes e planeja tarefas técnicas (desenvolvimento).
 
 Remoto, híbrido ou Escritório, [Santa Catarina], [Joinville], [América]

## Requisitos
Domínio de JavaScript, -HTML e -CSS;
Amplo conhecimento da biblioteca ReactJS (conhecimento em classes, hooks, lifecycle);
Conhecimento de GIT e pipelines/automação de rotinas;
Senso crítico, agilidade e foco em resultados (entrega de valor);
Capacidade de buscar conhecimento e solucionar problemas;
Diferencial ter conhecimento de SPA (Single Page Application);
Diferencial conhecer processo de Desenvolvimento Ágil de Software;
Habilidade com testes unitários;
Clean code e padrão de código;
Experiência com -Redux.
 

## Desejável
Conhecimento em Module bundlers, task runners e package managers;
Superior completo ou em andamento em Sistemas de Informação, Tecnologia ou afins;
Idioma Inglês;
Conhecimento em Docker, Node, Nest.js.
 
## Benefícios Experts
Confira abaixo algumas das vantagens em fazer parte do nosso time:

Plano de Saúde LifeDay (sem mensalidade para o titular);
Bônus anual (em média 2 salários, pagos semestralmente);
Vale-Refeição ou Vale-Alimentação (sem desconto em folha);
Auxílio Educação;
Plano Odontológico Nacional - PRODENT (três opções de planos);
Vale-transporte;
Quem indica amigo é! (Valor total de R$1.000,00 pagos no VA ou VR);
Parcerias com instituições de ensino;
Convênio Farmácia (Catarinense, Pró-Fórmula, Panvel, Droga Raia com desconto em folha);
Convênio Livraria A Página (desconto em folha em até 4x);
Seguro de Vida (sem desconto);
Cursos online 100% gratuitos e produzidos pela SoftExpert;
Capacitações internas e externas;
Máquina de café com todas as bebidas liberadas;
Máquina de snacks;
Estacionamento para bicicletas, motos e carros (Convênio empresa; pagamos até 50% da sua mensalidade);
Grêmio SoftExpert - GSE (festas, eventos, e confraternizações, além de diversos presentes/brindes);
Ginástica laboral.

## Contratação

- PJ ou CLT a combinar

## Como se candidatar

Anexar o Currículo neste link: https://softexpert.recruiterbox.com/jobs/fk0682k?source=

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: tbueno@softexpert.com

## Regime
- CLT
- PJ

 ## Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
