### ISSUE TITLE
[REMOTO] Front-end Developer na Dinheirow

### ISSUE THREAD

**Issue by jvitormelo** [frontendbr/vagas#5212]
Fala Pessoal, tudo bem?

A dinheirow (https://dinheirow.com.br/), fintech focada em empréstimos, está crescendo e estamos buscando programadores.
Hoje nosso time de devs tem mais de 10 programadores e estamos buscando:
•	Programador FRONT-END
•	Nível de experiência: Pleno
•	Faixa salarial: A partir de R$ 7000  PJ (a empresa paga um salário como férias)
•	Período: integral

Requisitos:
•	Pelo menos 2 anos de experiência em:
•	- Vue (preferencialmente) / React;
•	- Git;
•	- Programação Orientada a Objetos;
•	- Princípios SOLID.

O que irá fazer:

- Colaborar com product managers, designers e software engineers para identificar oportunidades e implementar soluções;
- Melhorar o nível técnico dos nossos serviços e sistemas atuais, resolvendo dívidas técnicas, problemas de arquitetura e design dos sistemas;
- Se envolver ativamente na construção de funcionalidades do começo ao fim, desde a experimentação, design, implementação e deploy;
- Trabalhar em conjunto com todo o time de tecnologia, revisando o trabalho de outras pessoas, participando de decisões importantes de produto e tecnologia, e garantindo a saúde dos nossos serviços.

Envie seu currículo para: contato@dinheirow.com.br ou me chamem no privado.

Labels:
 #PJ
 #PLENO
 #REMOTO

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
