### ISSUE TITLE
[Remoto] Front-end Tech Lead na 5A Attiva

### ISSUE THREAD

**Issue by Isabelacarrasco** [frontendbr/vagas#5216]
> Vaga Remota 

## Nossa empresa

5A Attiva

## Descrição da vaga

Aumente e gerencie uma equipe local e remota de engenheiros de software e especialistas em controle de qualidade; 
Influencie a ideação, lide com conversas sobre viabilidade e conceitos de protótipo em colaboração com outros engenheiros e designers;
Recomendar às partes interessadas internas de tecnologia e clientes (técnicos e não técnicos) o processo, a arquitetura de tecnologia e a estrutura de front-end adequados para dar vida às experiências;
Gerencie o processo de sprint, as tarefas diárias e a carga de trabalho da equipe de maneira eficiente, enquanto comunica o progresso, os bloqueadores e as metas claramente para a equipe maior; 
Realize revisões regulares de código, aplique as melhores práticas de codificação, controle de origem e resultados;
Aplique as diretrizes de segurança em relação à escrita de código, documentação, acordos de não divulgação e confidencialidade do cliente em todos os momentos;
Imponha constantemente códigos de front-end modernos, bem elaborados, de alta qualidade e de ponta de cada engenheiro de sua equipe.

## Local

100% Remoto

## Requisitos

**Obrigatórios:**
Imprescindível Inglês fluente;  
Experiência de nível de domínio com tecnologias front-end (HTML, CSS e JS);
Experiência de nível de domínio com AEM - Adobe Experience Manager;
Experiência de nível de domínio na implementação de soluções web responsivas e adaptáveis;
Experiência de nível de domínio integrando serviços da Web RESTful e APIs de terceiros;
Experiência de nível de domínio no desenvolvimento com frameworks front-end modernos (React, VueJS, Angular JS, Vanilla JS). 
Experiência de nível de maestria com Git e Jira;
Experiência em trabalhar com equipes remotas (cidade a cidade / país a país);
Experiência com linguagens de programação do lado do servidor, como NodeJS e / ou Python; Experiência em integração de experiências front-end com plataformas CMS / eCommerce como Contentful, Adobe Experience Manager, Shopify, Magento. Conhecimento de linguagens de desenvolvimento de aplicativos móveis, como Swift, Kotlin, Flutter.

## Contratação

PJ 

## Como se candidatar

Por favor envie um email para leticia.vasconcelos@5aattiva.com.br com seu CV anexado - enviar no assunto: Vaga Tech Lead 

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
