### ISSUE TITLE
[São Paulo] Front-end Developer na @EDESOFT

### ISSUE THREAD

**Issue by carolinepistore** [frontendbr/vagas#5217]
## Descrição da vaga

EDESOFT CONTRATA:
DESENVOLVEDOR .NET
Local:  Vila Bertioga-SP
Horário: de segunda a sexta feira das 08hrs as 18hrs
Início: IMEDIATO 
Principais atividades: Desenvolvimento de aplicações 
Requisitos Necessários:
Linguagem:
C#
.NET Core
Diferencial: Entender sobre Middleware logger e disponibilidade para atuar presencial 

## Local

Escritório, São Paulo, capital, Vila Bertioga

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para caroline.pistore@edesoft.com.br com seu CV anexado - enviar no assunto: Vaga .net

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

**Comment by az1nn** [comment]
a vaga é para front ou back end?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
