### ISSUE TITLE
[Remoto] Analista UX/UI Pleno ou Sênior na @Hagloo

### ISSUE THREAD

**Issue by giovaniPoletohagloo** [frontendbr/vagas#5218]
O que você fará: 

Produzir protótipos/layouts navegáveis para sites Web e Mobile e garantir a implementação de alta qualidade de seus projetos;
Criação de conteúdo (UX Writer) para as páginas;
Estar atualizado com técnicas, tecnologias e as melhores práticas de UX/UI;
Atuar com gerente de produto e membros dos squads de desenvolvimento para atingir os objetivos de negócios e convertê-los em soluções de design centrados no usuário;
Elaborar métricas de UX para medir, testar e coletar informações com base na utilização dos clientes, visando garantir melhoria contínua de fluxos e protótipos;
Fazer a gestão do Design System, revisar e documentar componentes e garantir excelência de sua aplicação junto à equipe de TI.

  Para esta vaga você precisa ter:

Graduação nas áreas de Comunicação, Publicidade e Propaganda, Marketing, Design gráfico ou Desenho Industrial.
Experiência com storytelling: Desenvolvimento de ideias de forma oral ou por meio de entregáveis, como apresentações, storyboards, blueprints, diagramas, entre outros;
Vivência com design de interfaces para plataformas web e mobile;
Experiência com softwares de prototipação como Figma;
Experiência com a construção e evolução de Design System;
Desejável conhecimento em metodologia ágil e Jira.

Nós respeitamos e valorizamos as diferenças com oportunidades iguais de emprego, independentemente de raça, religião, gênero, orientação sexual, idade, cultura, condições físicas ou status social.
Prezamos pela diversidade e criamos um ambiente cada vez mais inclusivo.

 

Contratação CLT

Horário: De segunda a sexta das 09 às 18h (Remoto)

Benefícios:  Vale-Transporte, Vale-Refeição, Auxílio Home Office, Assistência Médica (sem coparticipação), Odontológica, Auxílio Creche, Parceria com escolas de idiomas e faculdades, Gympass e Participação nos lucros.

CVs via rh@hagloo.com

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
