### ISSUE TITLE
[Remoto] Front-end Web na 5A Attiva

### ISSUE THREAD

**Issue by Isabelacarrasco** [frontendbr/vagas#5219]
> Vaga Remota

## Nossa empresa

5A Attiva

## Local
Remoto

## Requisitos

**Obrigatórios:**
Foco em html para landing pages. 
Ser bem técnico em front end, com foco emperformance. 
Ter noção de design é ideal.

## Contratação

PJ 

## Como se candidatar

Por favor envie um email para ingrid.prudencio@5aattiva.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
