### ISSUE TITLE
[São Paulo/SP] NodeJS Developer Pleno no SuperAgendador

### ISSUE THREAD

**Issue by jbaladao** [frontendbr/vagas#522]
#  Descrição da vaga

A startup SuperAgendador.com é um SaaS para prestadores de serviços. Procuramos um profissional com pelo menos 1 ano de experiência com Node.JS e MongoDB. Alguma experiência com PHP e MySQL também são desejados!

## Local

Próximo ao metro Jabaquara, São Paulo - SP

## Benefícios

- 1 hora de almoço
- café da manhã, bebidas no frigobar
- PS4 liberado com vários jogos para descontrair

## Obrigatórios:

1 ano de experiência com NodeJS e MongoDB pelo menos!
2 anos de experiência com programação JavaScript.
mais de 1 ano de experiência com qualquer outra linguagem de programação back end.

## Desejáveis:

ter trabalhado em alguma startup
ter trabalhado com algum sistema online no modelo SaaS
alguma experiência com Cloud Computing
alguma experiência com metodologias ágeis de desenvolvimento

## Contratação

PJ ou CLT a combinar

# Nossa empresa

O SuperAgendador.com é um dos maiores sistemas de gestão para Prestadores de Serviços do Brasil, nossos clientes movimentaram juntos aproximadamente 25 milhões de reais em dezembro de 2016. A empresa já foi acelerada em 2016 no evento InvestorsDay da CampusParty (anjos via Broota) e agora em 2017 recebeu um novo investimento do grupo Bossa Nova (pré-seed).
Estamos naquela fase incrível onde uma pequena startup pode evoluir rapidamente para um empresa com mais de 100 funcionários. Esse é o sonho, se quiser participar dele, venha trabalhar conosco. Vivenciar o nascimento e transformação de uma Startup é incrível e as oportunidades de crescimento e aprendizado são muitas!

# Como se candidatar

Por favor envie um email para jbaladao@superagendador.com com seu CV anexado - enviar no assunto: Vaga NodeJS/MongoDB

# Outras vagas

Também estamos procurando por um Front-end AngularJS. Toda indicação será super bem vinda...

Muito obrigado!

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by jbaladao** [comment]
finalizada
