### ISSUE TITLE
[Remoto] Desenvolvedor SharePoint Fullstack Pleno/Sênior - Home Office

### ISSUE THREAD

**Issue by NerdProgramador-com-br** [frontendbr/vagas#5223]
## Descrição da vaga 
**Aceitamos candidatos de todo o Brasil**
-----------------------------------------

  

Buscamos profissional para a área de Desenvolvimento SharePoint Fullstack com perfil Pleno para Sênior, que seja engajado, motivado, que goste de estudar/aprender novas tecnologias, que seja comprometido com a empresa.

  

\*\* Conhecimento Dev SharePoint:

  

1\. Linguagem C#;

2\. Plataforma .Net

3\. Javascript

4\. Banco de Dados Relacional;

5\. SQL Server – E-SQL, Modelagem, Procedures, Views;

6\. Atuação com melhorias de Performance de aplicações com utilização de ferramentas

de mercado;

7\. Realização de code-review;

8\. AngularJS

9\. ReactJS

10\. TypeScript

11\. SharePoint SPFX

12\. GIT/TFS

13\. Conhecimento de arquitetura de Solução SharePoint no VisualStudio

14\. Realização de Orçamento

15\. Construção e publicação de soluções do zero

16\. Domínio de desenvolvimento para SharePoint Online

  

**Experiência anterior requerida:** 4 a 6 anos na função

**Idiomas:** Inglês técnico

**Regime de Contratação:** PJ
## Local 
REMOTO 
## Como se candidatar 
Accesse a [Vaga de Desenvolvedor SharePoint Fullstack Pleno/Sênior - Home Office](https://vaga.contratar.dev/apply/full/82186c9a-fdac-4b0f-96b3-b62af9a7799d) para se candidatar. 
## Labels 
* Remoto 
* SQL 
* Javascript 
* React 
* Angular 
* Git 
## Sobre a contratar.dev 
A contratar.dev é uma plataforma de recrutamento e seleção automatizada de Desenvolvedores. Ao se candidatar a uma vaga da contratar.dev, você estará participando automaticamente de dezenas de processos seletivos para vagas similares, aumentando em MUITO as suas chances de mudar de vida 😉

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
