### ISSUE TITLE
[Remoto] Desenvolvedor(a) Front end (Pleno e Sênior) - PJ

### ISSUE THREAD

**Issue by NerdProgramador-com-br** [frontendbr/vagas#5224]
## Descrição da vaga 
Aceitamos candidatos de todo o Brasil.

  

Produtora de software, especilizada no mercado de comunicação digital, contrata Desenvolvedor(a) para atuar no time de desenvolvimento e manutenção de projetos envolvendo **AngularJS.**

  

**REQUISITOS**

• 2 anos de experiência em projetos no framework.

• Angular 4+ CSS e HTML.

• Conhecimentos Typescript, React JS, HTML5, CSS3, ES6.

• Noções de Design e Usabilidade;

• Domínio em implementações de APIs restfull.

• MVC e orientação a objetos.

• Bootstrap.

• Experiência com versionamento (GIT);

  

**FORMAÇÃO**

• Superior concluído ou em andamento

• Inglês Intermediário

  

**CONTRATAÇÃO**

• Remoto / Home Office

• Remuneração à combinar. Contratação PJ - 8h/dia.

  

**BENEFÍCIOS**

• Vale refeição

• Vale alimentação

• Plano de saúde regional

• Oportunidade de crescimento profissional, contando com equipes multidisciplinares em squads.

• Equipe com mais de 20 anos de experiência profissional no desenvolvimento de produtos digitais, atuando na co-criação, usabilidade, gestão de projetos e produção de software. Clientes como Google, Nike, RedBull, TicketLog, Danone, GloboNews e etc.

  

**ENVIAR PRETENSÃO SALARIAL**
## Local 
REMOTO 
## Como se candidatar 
Accesse a [Vaga de Desenvolvedor(a) Front end (Pleno e Sênior) - PJ](https://vaga.contratar.dev/apply/full/29579742-0966-483a-a377-fd557b5453c1) para se candidatar. 
## Labels 
* Remoto 
* React 
* Angular 
* CSS 
* TypeScript 
* HTML 
* Git 
## Sobre a contratar.dev 
A contratar.dev é uma plataforma de recrutamento e seleção automatizada de Desenvolvedores. Ao se candidatar a uma vaga da contratar.dev, você estará participando automaticamente de dezenas de processos seletivos para vagas similares, aumentando em MUITO as suas chances de mudar de vida 😉

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
