### ISSUE TITLE
[Remoto] Desenvolvedor(a) Wordpress (Pleno e Sênior) - PJ

### ISSUE THREAD

**Issue by NerdProgramador-com-br** [frontendbr/vagas#5225]
## Descrição da vaga 
**Aceitamos candidatos de todo o Brasil.**
------------------------------------------

  

  

**REQUISITOS**

• Wordpress

• HTML

• CSS

• Javascript – JQUERY / AngularJS

• GIT

  

**FORMAÇÃO**

• Ensino médio completo

  

**CONTRATAÇÃO**

• Remoto / Home Office

• Remuneração à combinar. Contratação PJ - 8h/dia.

**BENEFÍCIOS**

• Vale refeição

• Vale alimentação

• Plano de saúde regional

• Oportunidade de crescimento profissional, contando com equipes multidisciplinares em squads.

• Equipe com mais de 20 anos de experiência profissional no desenvolvimento de produtos digitais, atuando na co-criação, usabilidade, gestão de projetos e produção de software. Clientes como Google, Nike, RedBull, TicketLog, Danone, GloboNews e etc.

  

ENVIAR PRETENSÃO SALARIAL
## Local 
REMOTO 
## Como se candidatar 
Accesse a [Vaga de Desenvolvedor(a) Wordpress (Pleno e Sênior) - PJ](https://vaga.contratar.dev/apply/full/5dcaedab-4aa0-4e47-8af3-c1af8c5773a2) para se candidatar. 
## Labels 
* Remoto 
* Javascript 
* JQuery 
* Angular 
* CSS 
* HTML 
* Git 
* WordPress 
## Sobre a contratar.dev 
A contratar.dev é uma plataforma de recrutamento e seleção automatizada de Desenvolvedores. Ao se candidatar a uma vaga da contratar.dev, você estará participando automaticamente de dezenas de processos seletivos para vagas similares, aumentando em MUITO as suas chances de mudar de vida 😉

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
