### ISSUE TITLE
[Remoto] Fullstack Developer na Catho

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#5226]
## Nossa empresa

Mudar vidas é a nossa razão de existir. Ao unir as pessoas com as oportunidades de trabalho, a Catho possibilita a elas atender não só suas necessidades básicas e de suas famílias, como também ter a chance de crescer, produzir e realizar sonhos.

Além disso, somos parte do grupo Seek, líder global no segmento de recrutamento online, com atuação na Austrália, China, Índia e outros países.

## Descrição da vaga

Como Desenvolvedor(a) Fullstack Pleno, você irá atuar em uma equipe multidisciplinar em formato de squad, com a responsabilidade de desenvolver soluções que auxiliem os outros times nas entregas dos produtos, usando o melhor da tecnologia para disponibilizar features com qualidade e rapidez.

## Local

100% remoto

## Requisitos

**Obrigatórios:**

- Experiência em linguagens com o foco em desenvolvimento web, sendo diferencial experiência em Node, Typescript e PHP;
- Experiência com linguagens de marcação e formatação Web (HTML e CSS);
- Experiência com utilização de framework de front-end (ex.: React, Angular, etc)
- Experiência com APIs REST;
- Familiaridade com boas práticas de programação (refatoração, code review, testes unitários, teste de integração, design patterns, CI/CD, documentação);
- Utilização de banco de dados SQL e NoSQL;

**Desejáveis:**

- Controle de versionamento de código via Git;
- Familiaridade com metodologias ágeis;

## Benefícios

- Cartão multibenefícios;
- PPR
- Assistência médica;
- Assistência odontológica;
- Seguro de vida;
- Day off de aniversário;

**Diferenciais:**

- Programa Lado a Lado (você pode apadrinhar uma pessoa que receberá uma assinatura da Catho);
- Programa de Braços Abertos (contamos com o apoio de profissionais especializados em bem-estar mental para você e sua família);
- Somos uma empresa cidadã;
- Já fomos reconhecidos como GPTW diversas vezes;
- Horário flexível
- Não temos dress code.

## Contratação

CLT

## Como se candidatar

Basta acessar [este link](https://portal.kenoby.com/catho/cadastrar/6099745d07cff02c34167e72?1=1&utm_source=remotar) para efetuar a candidatura

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
