### ISSUE TITLE
[Remoto] Desenvolvedor (a) Front-End (Angular) - Sênior

### ISSUE THREAD

**Issue by NerdProgramador-com-br** [frontendbr/vagas#5227]
## Descrição da vaga 
**Aceitamos candidatos de todo o Brasil.**
------------------------------------------

  

**Descrição da vaga:**

*   No seu dia a dia irá trabalhar com desenvolvimento de funcionalidades e telas de sistema web. Com o apoio de outros membros do squad.
*   Irá ajudar na tomada de decisões de novas features e resoluções de bugs e dívidas técnicas.
*   Fazemos parte de um grupo criador de produtos, de acordo com o desenvolvimento em alguns momentos você irá transitar pelo mesmo stack de desenvolvimento de diversos.
*   O candidato deverá enviar o seu github.

**Requisitos Obrigatórios:**

*   Angular, Typescript, HTML5, CSS3, ES6.
*   Controle de versão com GIT.
*   Integração com API REST.
*   RXJS

**Diferenciais**

*   Noções de UX/UI.
*   Metodologia ágil, como o Scrum.
*   Testes unitários.
*   Conhecimento de design patterns.
*   Clean code.
*   Gerenciamento de estado com NGRX.
*   Cursando ou graduado na área de tecnologia
*     
    

**Benefícios**

*   Plano de saúde
*   Assistência odontológica
*   Day off de aniversário 
*   Vale alimentação
*   Ajuda de custo
*   Auxílio atividade física
*   Consignado
*   Plataforma de cursos
*   Seguro de vida
## Local 
REMOTO 
## Como se candidatar 
Accesse a [Vaga de Desenvolvedor (a) Front-End (Angular) - Sênior](https://vaga.contratar.dev/apply/full/80a62271-0439-494c-a700-e99d0d2fdd76) para se candidatar. 
## Labels 
* Remoto 
* Scrum 
* Angular 
* CSS 
* Rest 
* TypeScript 
* HTML 
* Git 
## Sobre a contratar.dev 
A contratar.dev é uma plataforma de recrutamento e seleção automatizada de Desenvolvedores. Ao se candidatar a uma vaga da contratar.dev, você estará participando automaticamente de dezenas de processos seletivos para vagas similares, aumentando em MUITO as suas chances de mudar de vida 😉

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
