### ISSUE TITLE
[REMOTO] Front-end Developer na Cubos Tecnologia

### ISSUE THREAD

**Issue by AdeSegundo** [frontendbr/vagas#5228]
A Cubos Tecnologia existe para transformar a realidade ao seu redor. Temos um desejo pujante de criar, impactar, aprender e causar uma diferença significativa na vida das pessoas através da tecnologia. Se você é uma pessoa que deseja criar tecnologia com significado, a Cubos é o lugar para você. Somos um Hub que atua em três caminhos: construção de negócios, impacto nas empresas e educação das pessoas. Temos bastante energia e leveza para encarar os desafios de cada caminho. E, principalmente, sabemos que estamos com mentes e corações excepcionais lado a lado.

Para participar do desafio da Cubos como Front-End Developer, auxiliando negócios e transformação digital (outsourcing), é necessário:
- Experiência com Typescript; 
- Experiência com React;
- Proficiência em Javascript ES6+;
- Proficiência em HTML e CSS. 

A oportunidade é remota e o modelo de contratação é PJ.

Essa oportunidade brilhou seus olhos? Então não se acanhe e se inscreva no link abaixo!
https://byintera.in/32y

Não faz sentido pra você, mas conhece alguém que pode se interessar? Compartilhe o link!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
