### ISSUE TITLE
[Remoto] Desenvolvedor (a) NodeJS/React

### ISSUE THREAD

**Issue by NerdProgramador-com-br** [frontendbr/vagas#5230]
## Descrição da vaga 
**Requisitos:**

*   Desenvolvedor NodeJS com experiência de frontend em React e conhecimentos básicos de Angular.
*   Conhecimento de PostgreSQL (banco de dados) é um plus.
## Local 
REMOTO 
## Como se candidatar 
Accesse a [Vaga de Desenvolvedor (a) NodeJS/React](https://vaga.contratar.dev/apply/full/9aadf3ee-e87a-4144-abd1-b661b406a4be) para se candidatar. 
## Labels 
* Remoto 
* SQL 
* React 
* NodeJS 
* PostgreSQL 
* Angular 
## Sobre a contratar.dev 
A contratar.dev é uma plataforma de recrutamento e seleção automatizada de Desenvolvedores. Ao se candidatar a uma vaga da contratar.dev, você estará participando automaticamente de dezenas de processos seletivos para vagas similares, aumentando em MUITO as suas chances de mudar de vida 😉

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
