### ISSUE TITLE
[Remoto] Programador Full-Stack PHP Sênior + Wordpress

### ISSUE THREAD

**Issue by NerdProgramador-com-br** [frontendbr/vagas#5231]
## Descrição da vaga 
**Aceitamos candidatos de todo o Brasil.**
------------------------------------------

  

**Experiência Comprovada em :**

*   PHP e Wordpress
*   HTML, CSS, SASS e Bootstrap
*   Javascript, jQuery e AJAX
*   MySQL

  

 **Em Wordpress, pedimos as seguintes experiências:**

*   ACF e Custom Post Types
*   AJAX e Nonces
*   Formulários de Contato
*   Criação de Temas do Zero

**Não trabalhamos com o uso de Builders**

**Conhecimento em Wordpress VIP é um diferencial**
## Local 
REMOTO 
## Como se candidatar 
Accesse a [Vaga de Programador Full-Stack PHP Sênior + Wordpress](https://vaga.contratar.dev/apply/full/defc4106-4a6f-49d7-a731-a0305358aa68) para se candidatar. 
## Labels 
* Remoto 
* SQL 
* Javascript 
* JQuery 
* CSS 
* HTML 
* PHP 
* WordPress 
## Sobre a contratar.dev 
A contratar.dev é uma plataforma de recrutamento e seleção automatizada de Desenvolvedores. Ao se candidatar a uma vaga da contratar.dev, você estará participando automaticamente de dezenas de processos seletivos para vagas similares, aumentando em MUITO as suas chances de mudar de vida 😉

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
