### ISSUE TITLE
[Remoto] Desenvolvedor (a) Front-end (Angular) - Pl/SR

### ISSUE THREAD

**Issue by NerdProgramador-com-br** [frontendbr/vagas#5232]
## Descrição da vaga 
Aceitamos candidatos de todo o Brasil.
--------------------------------------

  

**Conhecimentos:**

*   Experiência em desenvolvimento front-end;
*   Angular 7 e posteriores;
*   Consumo de serviços REST;
*   HTML5;
*   CSS3;
*   Bootstrap;
*   JavaScript
*   Json.

  

**Atribuições:**

*   Participar do desenvolvimento de uma nova plataforma para instituições de pagamentos;
*   Codificar sistemas e aplicações de acordo com os padrões e metodologias estabelecidas;
*   Codificar e aplicar testes unitários.

**Requisitos:**

*   Experiência de no mínimo 2 anos nas atribuições;
*   Comprometimento com os prazos acordados;
*   Comprometimento com a qualidade do produto final;
*   Pró-atividade.
## Local 
REMOTO 
## Como se candidatar 
Accesse a [Vaga de Desenvolvedor (a) Front-end (Angular) - Pl/SR](https://vaga.contratar.dev/apply/full/2be1c224-b8e4-4662-ad86-dbfc3a2058b7) para se candidatar. 
## Labels 
* Remoto 
* Angular 
* CSS 
* Rest 
* HTML 
* Java 
## Sobre a contratar.dev 
A contratar.dev é uma plataforma de recrutamento e seleção automatizada de Desenvolvedores. Ao se candidatar a uma vaga da contratar.dev, você estará participando automaticamente de dezenas de processos seletivos para vagas similares, aumentando em MUITO as suas chances de mudar de vida 😉

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
