### ISSUE TITLE
[Remoto] Desenvolvedor (a) JavaScript

### ISSUE THREAD

**Issue by NerdProgramador-com-br** [frontendbr/vagas#5234]
## Descrição da vaga 
**Descrição da vaga:**

*   Nível de experiência: Pleno a Sênior
*   Setor: Tecnologia da Informação – Serviços
*   Local de trabalho: Vila Olímpia – SP (Regime: 50% on-site e 50% home office)

**Requisitos Necessários:**

*   Formação superior cursando na área da tecnologia (desenvolvimento, sistemas, ciência da computação e áreas correlatas).
*   Experiência ou conhecimento com desenvolvimento em JavaScript e Banco de Dados Mongo DB

  

**Atividades:**

*   Atuar no desenvolvimento de Sistemas em JavaScript e Banco de Dados MongoDB

  

**Ambiente de Trabalho:**

*   Dress code free;
*   Flexibilidade de horário;
*   Sala de descompressão com Playstation 5;
*   Máquina Café, bebidas, salgados, doces (livre consumo);
*   Happy Hour 1 vez por mês;

  

**Benefícios**

*   Vale Alimentação
*   Vale Refeição
*   Vale Transporte
## Local 
REMOTO 
## Como se candidatar 
Accesse a [Vaga de Desenvolvedor (a) JavaScript](https://vaga.contratar.dev/apply/full/fc18f730-3fb6-4cda-904c-6a86d30686dd) para se candidatar. 
## Labels 
* Remoto 
* Javascript 
* Java 
## Sobre a contratar.dev 
A contratar.dev é uma plataforma de recrutamento e seleção automatizada de Desenvolvedores. Ao se candidatar a uma vaga da contratar.dev, você estará participando automaticamente de dezenas de processos seletivos para vagas similares, aumentando em MUITO as suas chances de mudar de vida 😉

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
