### ISSUE TITLE
[REMOTO] Pessoa Desenvolvedora Front-end na Foton

### ISSUE THREAD

**Issue by clarabsa1** [frontendbr/vagas#5236]
### Se você tá cansado de:

- Ambiente **desorganizado**;
- Cobrança **excessiva**;
- Falta de **trabalho em equipe**;
- Falta de **reconhecimento**;
- Falta de **perspectiva de crescimento;**
- Ter que trabalhar finais de semana ao invés de descansar

Convido você a conhecer a **FOTON** [[https://cutt.ly/wnuVf7T](https://cutt.ly/wnuVf7T)]**,** aqui pessoas vêm em primeiro lugar e não limitamos seu crescimento!

**Para vaga os requisitos são:**

- No mínimo 1 ano de experiência profissional com React;
- No mínimo 1 ano de experiência profissional com Javascript;
- Inglês avançado para conversação.

**Diferencias:** 

- Gostar de café

**Interessados mandar CV (em inglês), linkedin e github para clara@fotontech.io**

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
