### ISSUE TITLE
[REMOTO] Front-End Developer React na Americanas

### ISSUE THREAD

**Issue by alicepantoja97** [frontendbr/vagas#5237]
## Nossa empresa

Nossa história resume bem o que somos: uma combinação entre nosso potencial e a dedicação de quem acredita que limites existem para serem superados.

Sabemos que para ganhar o jogo precisamos dos melhores talentos e estamos aqui para jogar a longo prazo. Por isso, procuramos pessoas que queiram evoluir continuamente e se desafiar a construir algo relevante para nossos clientes.

Se identificou? Então venha fazer parte do nosso time!

## Descrição da vaga

Desenvolvimento de aplicações web (responsivo) utilizando o framework React para o frontend e o Node.JS (javascript) como backend bem como integrações utilizando APIs RESTful.

## Requisitos

**Obrigatórios:**
- Ser proficiente em  Next e/ou React 
- Ser capaz de criar uma aplicação com estado global com Redux
- Ser proficiente em Node.Js
- Conhecimento de banco de dados relacionais e não relacionais - mysql, sqlserver, oracle e mongodb

**Desejáveis:**
- Saber React Native

**Diferenciais:**
- Conhecimento em MS Azure 

## Benefícios

- Auxílio refeição
- Plano de Saúde e Odontológico 
- Seguro de vida 
- Descontos em produtos das lojas físicas e online
- Convênio com diversas instituições em todo Brasil

## Contratação

CLT - REMOTO

## Como se candidatar

Se inscreva 👉 https://lasa.gupy.io/jobs/940399

#### Alocação

- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
