### ISSUE TITLE
[REMOTE] Web Developer at Kobe - International Project

### ISSUE THREAD

**Issue by patriciagueds** [frontendbr/vagas#5239]
_At Kobe, we believe that a diverse environment enhances our culture, adds value to our team, and positively affects the services we provide. We make no distinction for candidates regarding sexual orientation, gender, disability, race/ethnicity, aesthetics, age, origin or family constitution._

**BE PART OF OUR TEAM!**

What if you could **impact millions of people lives** by taking part in the **development of a growth & innovation project** for one of **the world's biggest leaders** in consumer goods industry?

Kobe is looking for **middle and senior level web developers** to join the team. In this position you will have the opportunity **to join the expansion project of a company that is a reference in brewery.** You will be working alongside a highly qualified international team to develop a global platform that aims to transform people's beer experience.

As a Kober, you will be in an agile environment recognized as Great Place to Work in 2018, 2019 and 2020. In the last two years we have been in the top 3 of the best small companies to work for in RS and in the top 9 of the same ranking in Brazil.

Kobe has **remote-first policies**. No matter where you are, our culture comes to you!

## ABOUT THE CHALLENGE

Your main responsibilities will be:

- Develop web applications using technologies such as **Vtex.io, React.io. GraphQL, Unit Testing** etc;

- **Analyze, understand and discuss technical and functional requirements**, proposing the best approach for development and testing;

- Follow specific deliveries with an **innovative spirit, continuous improvement and obsession with exceeding customer expectations**, with whom you will have direct contact;

- **Support the entire application lifecycle**: conception, design, testing, release and support for new and existing features;

- **Propose new codes, components and processes** to improve our development practice.

## Labor Benefits

- **Your Way Holidays**: 40 days of paid rest per year to enjoy as you wish;

- **Health Insurance**: 100% covered health, dental and life insurance;

- **Flexible Time**: start working anytime in the morning and stop whenever you want;

- **Remote-First**: home office culture with activities dedicated to remote professionals;

- **Kobe Growth**: Individual Development Plan for each Kober;

- **Legendary Happy Hours**: Periodic Instragramable Integration Activities;

- **International Immersion**: international culture with projects and office outside BR;

- **The Right Tools**: the best equipment for a Kobe-level work structure.

## The challenge will be more natural if you have:

- At least **3 years of experience** with web application development;
- Knowledge developing with **Vtex.io technology**;
- Acting at **different stages of development**;
- Experience with **Unit Testing**;
- **Interpersonal communication** skills to interact with clients and team members;
- Autonomy in **decision making**;
- Guidance for **UX**.

Extra points that can make your profile stand out:

- Experience at international projects that had English as the official language of communication;
- Experience with Node.js;
- Knowledge in AWS;
- Previous performance with Redis and Elastic Search.

## How to get in contact with us

Please, add at [Linkedin](https://www.linkedin.com/in/patriciaguedes/) or send us an e-mail for patricia.guedes@kobe.io showing interest. We're looking forward to know you!

## Labels

- 🏢 Remote

- 🏢 Flexible hours

- 🏢 International Project

- 👨 Medium

- 👴 Senior

- ⚖️ PJ

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
