### ISSUE TITLE
[Floripa] Front-End Developer na Trust Code

### ISSUE THREAD

**Issue by ConsultoriaContato** [frontendbr/vagas#524]
Vaga CLT para Florianópolis, Santa Catarina.

**Atividades:**
Desenvolver e-commerce, sites, layouts de relatório e demais aplicações web para os clientes da Trust Code.

**Conhecimentos necessários:**
- JavaScript;
- HTML;
- CSS;
- Experiência em e-commerce.

**Conhecimentos desejáveis:**
- Básico de Design.

**Sobre a empresa:** 
A Trust Code é startup inovadora, com uma cultura participativa, transparente e que aposta em seus colaboradores.

**Comment by RicardoWEBSiTE** [comment]
Remoto?

Em 05/09/2017 4:36 PM, "ConsultoriaContato" <notifications@github.com>
escreveu:
