### ISSUE TITLE
[Remote - Portugal] iOS Developer @ INTEGER Consulting

### ISSUE THREAD

**Issue by FilipeGM** [frontendbr/vagas#5240]
## INTEGER Consulting

INTEGER is a technology consulting company, focused on Outsourcing Services and Development of Software and Product, with over a decade of presence in the Portuguese market!

## Role

We're looking for an iOS Developer with strong communication skills, sense of responsibility who is a teamplayer for a digital transformation project (Nearshore)!

**Portugal - Remote (The desire to come to Portugal after the pandemic will be appreciated)

## Requirements

- Bachelor’s Degree in Informatics Engineering or similar;
- Minimum of 2 years of experience in IOS Development (Swift);
- Experience in Front-end frameworks (React Native, Angular) - plus;
- Knowledge with CI/CD development methodologies and tools;
- Agile mindset and methodologies such as Scrum and Kanban.
- Ambition to be continuously learning and to become a leader in your domain of expertise;
- Fluent in English - written and spoken - it's a plus

## Benefits

Training Plan;
Health Insurance;
Full access to company's partnerships

## How to apply for this vacancy

If you have the amazINg talent and want to be part of the INTEGER team, drop me an e-mail with your CV filipe.marques@integer.pt
 
Participating in this project means integration in a solid company and in a young and dynamic team. #jumpIN
To know more about how we protect your privacy, check out our GDPR Policy at www.integerconsulting.pt

## Average feedback time

You'll normally get feedback in 1 week, after the interview
If you don't get any feedback please send an e-mail to filipe.marques@integer.pt

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
