### ISSUE TITLE
[São Paulo] Senior Front-end Developer no Banco ABC

### ISSUE THREAD

**Issue by danielasantosrh** [frontendbr/vagas#5242]
> Vaga Remota durante a pandemia

## Nossa empresa

Com mais de 30 anos de mercado e listado na Bolsa, o Banco ABC Brasil é reconhecido por essas três características: consistência, segurança e eficiência. Acreditamos que o sucesso é fruto de uma cultura que promove relações colaborativas, visa o resultado e abre espaço para o diálogo. Nesse sentido, atuamos visando sempre a competência em tudo o que nos propomos a fazer, o profundo conhecimento do nosso mercado, a credibilidade dos nossos clientes, a agilidade na busca por soluções adequadas e inovadoras, o compromisso com bons resultados e o investimento contínuo em tecnologia, processos e pessoas.

## Descrição da vaga

Requisitos:
•	Angular 7/8
•	Mercado financeiro
•	Git,
•	HTML5
•	CSS3
•	JSON
•	REST
•	Javascript e TypeScript
•	Conhecimentos em otimização de bundle, configuração de webpack;
•	Conhecimentos em web-components / princípios de Micro-frontends;
•	Conhecimentos em programação reativa e gerenciamento de estado;
•	Experiência com autenticação de usuário (manipulação de tokens);
•	Experiência em consumo de APIs Rest;
•	Versionamento com GitHub;
•	Conhecimentos em Gitflow;

•	Desejável: Azure Devops, Plataforma MS Azure, API Gateway (Axway), Ferramentas de teste (SOAPUI, Postman), Git Flow, SQL Server (Transact-SQL), Metodologias ágeis (Scrum/Kanban).

•	Responsável por especificação, desenvolvimento e acompanhamento de projetos em sistemas frontend baseados em APIs/Web Application para aplicações WEB e Mobile

## Local

[SÃO PAULO], [SÃO PAULO], [FARIA LIMA]

## Benefícios

•	PLR (2.2 salários + 5k de abono)
•	VR+ VA (1.480,00)
•	Assistência médica: Bradesco (apenas para se usar (coparticipação) / sem desconto mensal)
•	Odonto: Omint (desconto a partir de 35 reais de acordo com seu plano escolhido)
•	PPR: até 1,7 salários (desempenho)
•	Auxílio creche (R$ 500,00 até 5 anos)
•	Seguro de vida
•	Gympass

## Contratação

CLT a combinar

## Como se candidatar

Link para se candidatar e que tem mais informações sobre a empresa, ambiente e desafios: https://yuri.jornadayu.com/j/desenvolvedores-abc/src/git
Obs.: a candidatura é bem diferente, parece um bate papo no whats, vc vai gostar :)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: daniela@jornadayu.com

#### Alocação
- Híbrido

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
