### ISSUE TITLE
[São Paulo - SP] Front-End Developer SR na Raiadrogasil S.A (Startup) 

### ISSUE THREAD

**Issue by ErickPolasse** [frontendbr/vagas#5243]
Spin off do Grupo Raiadrogasil e estamos construindo uma nova plataforma de Saúde, que será lançada em breve no mundo físico e digital. Nosso objetivo, assim como de todo o grupo, é facilitar uma vida saudável com experiências incríveis, por meio de produtos e serviços.

Descrição:
- Construir plataforma de backoffice utilizada pelo time de operações e pelas frentes de farmácias;
- Participar das definições de APIs;
- Implementar integrações com nosso backend de microsserviços;
- Implementar testes para garantir manutenção;
- Manter documentação para compartilhamento com o time;
- Avaliar, levantar e discutir requisitos junto ao time de produtos.

Posição:
Sênior

Tipo de contratação:
Remoto e presencial, CLT

Requisitos:
- Javascript (ES5, ES6), HTML e CSS;
- Domínio em React.js (ou outras frameworks);
- Domínio em yarn (ou outros gerenciadores de pacotes);
- Domínio em GraphQL e BFF;
- Desenvolvimento orientado a testes;
- Versionamento utilizando Git;
- Atenção para qualidade de código;
- Domínio em Component Driven Design.

Contato:
erick.polasse@rdsaude.com.br
Linkedin: https://www.linkedin.com/in/erickpolasse/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
