### ISSUE TITLE
[Remoto] Front-end Angular 9+ na Toutbox

### ISSUE THREAD

**Issue by toutboxrj** [frontendbr/vagas#5246]
## Nossa empresa

A toutbox é uma empresa de gestão de logística que está a mais de 5 anos no mercado, atuamos com gerenciamento de pacotes dos big players do mercado de ecommerce, realizando integrações com diversas transportadoras e ajudando no pós venda / controle de logística para o cliente final.

## Descrição da vaga

O candidado vai atuar como desenvolvedor frontend, utilizando angular 9+ para criar a funcionalidades necessárias ao projeto e git para versionamento / deploy de suas tarefas. 

## Local

100% Remoto

## Requisitos

**Obrigatórios**

- HTML 5 / CSS 3 / Bootstrap / Typescript 

- Sólida experiência em Angular 9+

- Npm

- Experiência com versionamento utilizando Git

- Atenção com qualidade e clareza de código

## Etapas

O candidato participará de uma breve entrevista online, seguido de um teste técnico para mensurar seu conhecimento.
 
## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um e-mail para atendimento@toutbox.com.br com seu CV anexado - enviar no assunto: Vaga Angular 9+ - frontendbr

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

#### Alocação
- Remoto 100%
#### Regime
- PJ
#### Nível
- Pleno

Conhece alguém que pode se interessar? Por favor compartilhe o link dessa oportunidade!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
