### ISSUE TITLE
[Remoto] Front-end Vue Developer na Reportei.com

### ISSUE THREAD

**Issue by TiagoGouvea** [frontendbr/vagas#5247]
## Nossa empresa

O [Reportei](https://reportei.com/) é uma ferramenta de comunicação de resultados de marketing digital por meio de relatórios, com foco em mídias sociais. O software conta com relatórios de Facebook, Ads, Instagram, YouTube, LinkedIn e Google Analytics.

O Reportei para agiliza processos que antes eram feitos manualmente. Reunindo tudo num só relatório, o especialista em mídias sociais tem maior facilidade para analisar e propor otimizações do marketing digital.

Por ser uma empresa que cresce muito rápido a oportunidade de aprendizado e crescimento é ímpar. Atualmente atendemos diretamente milhares de clientes todos os dias e o resultado do seu trabalho pode ser visto de forma direta na satisfação de cada um deles.

## Descrição da vaga

Você está procurando uma oportunidade para trabalhar com autonomia, liberdade para propor melhorias e ter grandes desafios? Então temos a vaga para você no Reportei onde você terá um ambiente dinâmico com muitas oportunidades de crescimento!

O Reportei é uma plataforma online que auxilia profissionais de marketing comunicar resultados de marketing digital a seus clientes através de relatórios.

Estamos procurando um profissional de Tecnologia que seja organizado, proativo e motivado para atuar em nossa equipe de desenvolvimento de sistemas trabalhando em inúmeras melhorias em nossa ferramenta. Além disso, é esperado do profissional participação na estruturação de projetos e processos da área de desenvolvimento.

O profissional será responsável pelo desenvolvimento e planejamento de novas funcionalidades em VueJs, além da manutenção do código já existente e apoio ao desenvolvimento do time Junior, visando o aprimoramento da experiência do usuário como um todo.

#### Responsabilidades:

- Criar novas funcionalidades para a ferramenta por meio das técnicas de desenvolvimento de software;
- Identificar problemas e reparar as funcionalidades existentes por meio das técnicas de desenvolvimento de software;
- Construir e dar manutenção em arquiteturas de software que otimizem o produto, por meio de melhoria contínua;
- Identificar pontos de melhoria em código e funcionalidades que impactem nos resultados de negócio, por meio de análises e dados;
- Ajudar o Suporte com as questões técnicas da ferramenta que podem surgir dos clientes por meio das tarefas abertas pelo time de Suporte;
- Estudar técnicas e ferramentas que melhorem a qualidade do código por meio de cursos, livros e afins;
- Guiar Desenvolvedores Junior que irão precisar de ajuda pelo código e revisar seus trabalhos através de conversas ou sessões de pair programing;
- Garantir qualidade de código de desenvolvedores júnior por meio de code review.

#### Desafios:

- Encontrar partes da ferramenta que, mesmo funcionando, poderiam ser melhoradas;
- Manter qualidade e velocidade da entrega individual, mesmo apoiando no desenvolvimento de outros programadores;
- Estudar constantemente para melhorar a qualidade do trabalho.

## Local

Remoto

## Benefícios

- Vale Alimentação;
- Horas flexíveis;
- Notebook da empresa para trabalho;
- Grandes oportunidades de crescimento;
- Possibilidade de ver o impacto do trabalho diretamente na satisfação do cliente.

## Contratação

- CLT entre R$4.000 e R$5.000 mensais + vale alimentação

## Como se candidatar

Acesse a plataforma [Programadores em Juiz de Fora](https://programador.emjuizdefora.com/oportunidade/desenvolvedor-vuejs/), e se candidate na vaga.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
