### ISSUE TITLE
[BR-REMOTO] Especialista em Front-end no @Descomplica

### ISSUE THREAD

**Issue by anaclaracae** [frontendbr/vagas#5249]
**Sobre o Descomplica**
Aprender É Pra Todo Mundo! Começamos em 2011 como uma startup de educação online ajudando estudantes de todo o Brasil a passar no Enem e principais vestibulares do país. Desde 2016, começamos a olhar para outras fases da vida do aluno. Hoje, nosso negócio é focado em 6 categorias: Escola, Vestibulares, Concurso, Graduação e Pós-graduação. 🥇 

**Benefícios**

- Bônus anual de até 3 salários atrelado ao desempenho e resultados da empresa;
- Plano de Saúde com cobertura médica, hospitalar e desconto em farmácia para você e seus dependentes diretos (cônjuge e filhos) sem coparticipação ou cobrança de mensalidade ao funcionário;
- Plano Odontológico;
- Desconto farmacêutico;
- Happy day no aniversário;
- Seguro de Vida em Grupo;
- Vale Refeição;
- Incentivo ao estudo;
- Licença Maternidade de 06 (seis) meses;
- Auxílio-creche.

**Diferenciais**

- Fará parte de um projeto que afeta a vida de milhões de brasileiros;
- Trabalhar com um time de alto nível, usando boas práticas e as melhores ferramentas do mercado;
- Terá a oportunidade de aprender muito;
- Trabalhará em um ambiente informal que não se prende à hierarquia tradicional, com um time super dinâmico e colaborativo que trabalha e também se diverte junto.

**Requisitos**

Obrigatórios:
- Possuir pelo menos 5 anos de experiência escrevendo código;
- Necessário expertise em Javascript (React e/ou VueJS)
- Experiência com testes automatizados (unit, integration e E2E testing);
- Experiência no desenvolvimento de soluções escaláveis;
- Forte aptidão analítica e excelente atenção aos detalhes (você deve ser capaz de criticar e propor designs/arquiteturas existentes);
- Experiência em integração com APIs RESTful e/ou GraphQL, preferencialmente com arquitetura de microsserviços;
- Ter muita vontade de aprender e interesse em conhecer novas tecnologias.

Não é necessário, mas vamos curtir se você:
- Já trabalhou ou contribuiu ativamente para o desenvolvimento de design systems;
- Já trabalhou ou tem familiaridade com UML e técnicas/padrões de projeto (design patterns);
- Se formou em Ciência/Engenharia da Computação (ou equivalente).

**Contratação**
CLT

Como se candidatar
Quer enviar seu currículo? 📧 @ana.caetano@descomplica.com.br ou através da [página de carreiras](https://boards.greenhouse.io/descomplica/jobs/4439514003)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
