### ISSUE TITLE
[São Paulo] Front-End Developer Junior na Octadesk

### ISSUE THREAD

**Issue by houstondapaz** [frontendbr/vagas#525]
![](https://octadeskstorage.blob.core.windows.net/public/Post-Vagas_Junior_Frontend.png)

## Descrição da vaga

Cansado de trabalhar em empresas quadradas? Gosta de desafios? Gosta de tecnologia?

A Octadesk é a startup que você está procurando.

Somos uma equipe fascinada por marketing digital, tecnologia, UX, startup, empreendedorismo e acima de tudo, atendimento ao cliente. 

Estamos atrás de gente curiosa, comprometida, proativa, que adore desafios, seja autodidata e goste muito de tecnologia e resolver problemas.

Procuramos pessoas para fazer parte de um time fora de série, que viva o nosso sonho de desenvolver produtos de alto impacto, focados em atendimento ao cliente. 

## Local

Escritório, São Paulo - Granja Julieta

### CLT

- VT
- VR de R$ 21/dia

#### Diferenciais

Nosso ambiente é bem informal, descontraído e flexível favorecendo o aprendizado constante de várias áreas de negócio!

## Requisitos

Trabalhamos com as seguintes tecnologias e conceitos (desejável conhecer o maior número delas):

- AngularJS
- VueJS
- Node
- Html 5
- CSS3
- Javascript
- Git
- Gulp
- Bower
- Tdd

## Contratação

PJ ou CLT a combinar

## Nossa empresa

Octadesk é uma plataforma de sistemas voltada para a gestão de relacionamento com cliente.

O objetivo principal da startup é, além de facilitar o trabalho das equipes, suportar qualquer etapa da jornada do cliente e aumentar seu nível de satisfação e fidelidade.

## Como se candidatar

[Se candidatar via Hipster.Jobs](https://hipsters.jobs/job/1541/front-end-jr/)

**Comment by LFeh** [comment]
Vaga bacana hein?

**Comment by vinirossi** [comment]
Currículo enviado @houstondapaz

**Comment by Anselmo17** [comment]
posso enviar o cv para você Houston?

**Comment by simaodeveloper** [comment]
@sdq-sts da uma olhada

**Comment by houstondapaz** [comment]
Ainda estamos na procura, podem me enviar o curriculo @Anselmo17 @simaodeveloper

**Comment by Anselmo17** [comment]
onde posso enviar meu cv , porque Hipster.Jobs está dizendo que a vaga foi apagada?

**Comment by suspecie** [comment]
Também gostaria de me candidatar mas o link diz que foi apagada.

**Comment by LFeh** [comment]
@houstondapaz Encerrou?

**Comment by houstondapaz** [comment]
Pessoal fechou a vaga pelo Hipster (nao sei pq) mas está no trampos
https://trampos.co/oportunidades/134442-desenvolvedor-front-end-junior?locale=pt-BR
@Anselmo17 @suspecie

**Comment by Anselmo17** [comment]
ok, já me escrevi obrigado pela oportunidade .

**Comment by gabriel-brito** [comment]
Mandei meu curriculum lá pelo trampos!

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by houstondapaz** [comment]
Estamos sempre abertos na verdade, tanto senior/pleno/junior, só entrar em contato

**Comment by LFeh** [comment]
Boa!

**Comment by gadielkalleb** [comment]
Tentei vê a vaga pelo trampos mas não rs disponível queria me candidatar

**Comment by houstondapaz** [comment]
@gadielkalleb estão fechando um processo, por isso tiraram do ar, manda seu curriculum pra mim houston.diego@octadesk.com

**Comment by HaluDeCassia** [comment]
@houstondapaz sem chance de remoto total? Acredito que essa forma combina bem com o espírito da empresa. Adoraria poder me candidatar

**Comment by houstondapaz** [comment]
@HaluDeCassia claro que pode ser remoto total, eu mesmo to mudando pra ser remoto full

**Comment by HaluDeCassia** [comment]
@houstondapaz ótimo ouvir isso, vou enviar meu currículo então, tudo bem? Valeu :smile:

**Comment by houstondapaz** [comment]
@LFeh já que pos essa label, pode por que são todos os niveis tb?

**Comment by gadielkalleb** [comment]
Show mandei @houstondapaz

**Comment by osamuca** [comment]
a vaga ainda está disponível?

**Comment by lumarega** [comment]
@houstondapaz também não consegui encontrar a vaga nos sites acima, ainda está aberta?

**Comment by mathloureiro** [comment]
A vaga ainda está aberta? :D

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
