### ISSUE TITLE
[Rio de Janeiro] Front-end Developer na DCLICK

### ISSUE THREAD

**Issue by andrezapereira** [frontendbr/vagas#5251]
[Rio de Janeiro] Front-End Developer na DCLICK

> Vaga 100% Remota

DClick Desenvolvimento de Softwares

Nosso objetivo é desenvolver as melhores Rich Internet Applications do mercado, ou seja, aplicativos com o melhor da Internet e do desktop: alcance, disponibilidade, performance e Interface de usuário agradável e intuitiva. Ao longo destes anos atendemos a grandes clientes no Brasil e exterior e aprimoramos nosso conhecimento em Engenharia de Software, Interfaces de Usuário e Design de Interfaces e Desenvolvimento de Produtos. Hoje utilizamos a nossa expertise através das mais variadas tecnologias.

## Descrição da vaga
- Nível Superior em TI
- Experiência em Angular 6 com material UI

## Local

- Remoto

## Benefícios

- Plano de saúde
- VR ou VA

## Como se candidatar

Por favor envie um e-mail para andreza.pereira@dclick.com.br com seu CV anexado - enviar no assunto: Front-end Developer

## Regime
- Cooperativa
- PJ

## Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
