### ISSUE TITLE
[Remoto] Front-end Developer Senior na @Projuris

### ISSUE THREAD

**Issue by vanessaliebl** [frontendbr/vagas#5252]
## Nossa empresa

A Projuris é a única plataforma de inteligência legal do Brasil. Ao longo de mais de uma década, buscamos cumprir com o propósito de modificar os resultados de milhares de profissionais e empresas.
Em toda nossa história, nos tornamos uma ponte que conecta nossos clientes a todo ecossistema de tecnologia voltada a serviços de assuntos legais.
Diariamente são mais de 2.000 clientes e 20 mil profissionais em todo o Brasil que acreditam no poder deste sonho.
Vamos expandir o desempenho humano juntos?

## Descrição da vaga

**Como pessoa desenvolvedora Front End, esperamos que você:**

Participe das cerimônias do time (planning, review, retrospectiva)
Realize a estimativa após o entendimento das funcionalidades;
Construa as funcionalidades descritas nas épicas e histórias;
Crie estruturas para atender novas funcionalidades de forma otimizada e organizada;
Corrija bugs apontados pelos clientes ou pela equipe de qualidade
Realize testes da funcionalidade criada, garantindo assim sua qualidade;
Insira os códigos criados no repositório de armazenamento de códigos fonte;
Siga os procedimentos internos na ferramenta de controle de projetos/chamados (Jira);
Crie códigos limpo e bem estruturado;

## Local

Joinville/SC  / Remoto

## Requisitos

**Para se juntar a nós, é importante conhecer**

Lógica de programação
Orientação a Objetos
Desenvolvimento de sistemas WEB  
Javascript
HTML e CSS
Testes unitários  

**Você vai se diferenciar se conhecer**

Angular 2+  
Bootstrap;
NodeJS;
NgRx e/ou NgXs (gerenciamento de estado)
Java 8+
Git
Docker
Testes e2e  

## Benefícios

Para isso contamos com diversos benefícios como: 

 🥪 Vale refeição valor de R$520,00 (sem custo)
🩺 Plano de saúde Unimed ou Bradesco Nacional adesão imediata sem custo ao colaborador;
🦷 Plano odontológico;
✔Convênio Farmácia;
💻Acessos a curso da Udemy;
💰PPR;
📚Bolsa de estudos (Para graduação, Pós graduação e Idiomas);
 ✔Seguro de vida; 

O que você vai encontrar aqui? 😀 

🎉Ótimo clima interno;
🍇Disponibilidade de frutas na sede;
🎶Happy Hour;
🚀Um ambiente trabalho dinâmico com pessoas engajadas com os valores da empresa;
⏱Horário flexível;
🕶️ No dress code;
📣Incentivo a feedbacks ;
🎁Mimos em datas especiais ;
🎈Aqui seu aniversário não passa em branco;

## Contratação

CLT OU PJ

## Como se candidatar

Acesse nosso site: projuris.com.br/talentos

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
