### ISSUE TITLE
[Remoto] Front-end pleno na Stefanini

### ISSUE THREAD

**Issue by ThaisKerolyn** [frontendbr/vagas#5253]
> Vaga Remota 

##Stefanini

Aqui na #Stefanini, acreditamos que para cocriar é necessário existir diferentes formas de pensamento!
Entendemos que as diferenças tornam as pessoas únicas e, por isso, não fazemos qualquer distinção entre nossos candidatos. Para nós, não importa idade, gênero, raça/etnia, deficiência, orientação sexual, origem, estética ou constituição familiar. Nós queremos te conhecer. Ser diferente torna as pessoas únicas!

## Requisitos:

Conhecimentos em 
SASS
Angular 2+ (Componentização,)
Bootstrap
HMTL5
CSS
javaScript
Api Rest
Prototipação

## Contratação

CLT a combinar 

## Como se candidatar

Por favor envie um email para tksilva@stefanini.com seu CV anexado - enviar no assunto: Vaga Front End 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT
- 

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
