### ISSUE TITLE
[REMOTO] RPA Developer na TO Brasil 

### ISSUE THREAD

**Issue by jadecasal** [frontendbr/vagas#5254]
Alô alô galera de RPA !! 

Sabe aquela oportunidade de participar de um ótimo projeto para dar aqueeeele UP nas suas experiências?
Sua chance chegou!! E fresquinha! 

O que você precisa?
Ter experiência em desenvolvimento RPA, leitura de PDF estruturado e automation anywhere.

E o que mais sobre a vaga??
CLT+ benefícios + home office full
Nível Pleno

Curtiu?
Envie o seu CV por e-mail então: 
marlene.souza@to-brasil.com

#RPA #vagas #TI #job

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
