### ISSUE TITLE
[Remoto] Desenvolvedor(a) Front-end (Angular) Pleno na Giganti

### ISSUE THREAD

**Issue by darrudanoo** [frontendbr/vagas#5255]
## Descrição da vaga
Experiência em desenvolvimento front-end;
Angular;
Consumo de serviços REST;
HTML5;
CSS3;
Bootstrap;
JavaScript / Jquery
Json.
Conhecimento em  NodeJS

## Local
100% Remoto

## Requisitos

**Obrigatórios:**
- 3 anos de experiência como front End
- 2 anos de experiência com Angular
- 1 ano de experiência com Node.JS

## Contratação
PJ, salário a combinar de acordo com experiência.

## Como se candidatar
Por favor envie um email para atendimento@giganti.com.br com seu CV anexado - enviar no assunto: Front

## Tempo médio de feedbacks
Feedback trimestal

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
