### ISSUE TITLE
[Curitiba] Full-Stack Developer na PetraGroup

### ISSUE THREAD

**Issue by armondlais** [frontendbr/vagas#5256]
**Job Role Summary**

Exhibits functional proficiency in each domain (front-end, back-end & infrastructure);
Creates responsive front-end web pages wich scale across many different device sizes and browsers;
Considers the advantages/disadvantages of SQL and NoSQL databases and other storing relationships for each application use case and chooses accordingly;
Understands when to use each OAuth2.0 authentication protocol to properly protect an API;
Creates and suppports Continuous Integration / Continuous Delivery (CI/CD) pipelines for the solutions they create;
Deploys simple software architectures (e.g. N-tier) to the cloud using Platform-as-a-Service computing;
Actively conducts application threat modeling against a solution to close security gaps;
Well-versed in both business logic and user experience, meaning they are not only well-equipped to get hands on, but can also guide and consult on strategy too;
Helps mentor younger associates, including connecting them to the developer communities.

**Job Role Responsabilities**

A full-stacker developer is responsible of the design and development of end-to-end software solutions. A full-stack developer is not a super developer who can do anything, but rather, a developer who understands everything. To get to this breadth and depth of knowledge, most full-stack web developers will have spent many years working in a variety of different roles.
Full-stack web developers are capable of working on both the front-end and back-end portions of an application while also managing full hosting enviornments. Front-end development is generally comprised of implementing visual and interactive elements that users see and engage with in web-based applications. Back-end development is generally comprised of developing and maintaining server-side logic, integrating application elements, and exposing data through API endpoints. Hosting management is generally comprised ok knowing how to configure and manage the infrastructure (like Microsoft Azure) that serves the website to the user. Full-stack web developers are capable of owning any aspect of product development while also effectively comunicating with all members of tha application stack. Full-stack web developers are typically found within smaller projects, but their skills are still applicable within larger projects, although it’s uncommon due to the potential scale of each component involved in large projects. An intermediate full-stack web developer is able to execute intuitive web designs.

Positioning text, images, buttons, and so on inside a complex layout;
While also wrinting back-end-server code to receive information inputted from the user and store it securely in a database. Na intermediate full-stack web developer would be capable of changing configuration settings to any of the underlying web application, API, or database services.

**Expected Level Of Proficiency
Technical Skills**

Fluent in English;
Full-stack developers;
React/Typescript/JavaScript (must have);
.NET Core/C# (must have);
Azure services – Storage/SQL, Dashborards, Azure DevOps;
Authentication, Unit Test Framework, and Entity Framework Core;
SQL;
Data/analytics visualization skills (optional);
Knowledge of and experience in general Lean-Agile principles;
Knowledge of and experience with Scrum process and data;
Experience in Design, Usability Testing, User Experience;
API Management;
Git Repositories;
CI/CD.

**Soft Skills**

Experience interfacing with customers and ideating on solutions based in customer interactions (problems, bugs, enhancements) (must have);
Effective communication and pair-based teamwork (must have);
Ability to influence and convey difficult/tchnical concepts and work across layers of the organization to drive understanding; Presenting solutions in a demo setting;
Ability to maintain flexibility and patience with team members and customers;
Passion for learning.

**Send CV with salary claim to lais.armond.corporativo@gmail.com**

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
