### ISSUE TITLE
[Remoto] Front-end Developer (Vue.JS) na HeroSpark

### ISSUE THREAD

**Issue by oleandroviegas** [frontendbr/vagas#5257]
## Nossa empresa

Somos uma plataforma de empreendedorismo digital que já impactou mais de 6 milhões de alunos, temos a missão de transformar conhecimento em negócios digitais de alto impacto e por isso, acreditamos que todas as pessoas possuem algo especial que as fazem ser especialista em algum assunto!

Por isso, estamos buscando alguém para trabalhar no nosso time de Desenvolvimento para que possa nos ajudar cada vez mais a despertar essa faísca. 

## Descrição da vaga

- Tecnologia utilizada: Vue.JS
- Desenvolvimento e manutenção nos produtos HeroSpark (plataformas de e-commerce, ensino, entre outros);
- Aplicação de templates;
- Criação e customização de páginas;
- Otimização de páginas para SEO;
- Aplicar melhorias de performance relacionadas ao front-end.

## Local

Exemplo: Remoto (100% remoto)

## Requisitos

**Obrigatórios:**

- Ampla experiência como desenvolvimento de websites (Prototipação de layout com HTML5 , flex layout, CSS3, SASS, Bootstrap e Materialize);
- Amplo conhecimento em Javascript e JQuery;
- Experiência com bower, gulp, webpack;
- Experiência com Angular ou VueJS;

**Desejáveis:**

- Experiência com liquid template language;
- Experiência com Amazon AWS S3;
- Experiência com Ruby e Ruby on Rails;
- Experiência com processos de deploy, CI/CD e monitoramento de aplicações front-end;

**Diferenciais:**
- Experiência em projetos opensource;

## Benefícios

- Plano de saúde
- VR/VA de R$ 510,00 por mês
- GymPass
- Auxílio HomeOffice
- Subsídio English in Company

## Contratação

CLT ou PJ à combinar

## Como se candidatar

Por favor envie um email para leandro.viegas@herospark.com ou me mande uma mensagem no Linkedin @oleandroviegas

## Tempo médio de feedbacks

Nosso processo possui apenas 3 etapas e foi criado para durar no máximo 7 dias. Os feedbacks são passados em geral no mesmo dia ou no máximo no dia seguinte à entrevista. 

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
