### ISSUE TITLE
[Remoto] IOS Developer @HunterCo

### ISSUE THREAD

**Issue by jananessi** [frontendbr/vagas#5258]
##Nossa Empresa
Trabalho em uma empresa de recrutamento humanizado que se chama HunterCo, possuímos várias vagas e consultores que acompanham os candidatos no recrutamento, auxiliando-o e dando feedback's.

Descrição da vaga

Você que tem vivência com iOS nativo, desenvolvimento de aplicações mobile e quer fazer a diferença com aquilo que sabe entregar de melhor: programar, então candidate-se nessa super oportunidade!

Local

Remoto

Benefícios

-Salário/Remuneração fixa
-Acolhimento Psicológico
-15 dias de férias (PJ)
-Happy Our On Line
-Academia do Conhecimento

Requisitos

Obrigatórios:

Domínio de Swift;
Boa vivência com desenvolvimento mobile;
Experiência em desenvolvimento com XCode.

Desejáveis:

Domínio de Objective-C;
Experiência com geração de ambiente de publicação Apple para apps.

Contratação

CLT/PJ

Como se candidatar

Acessar o link: https://vagas.hunterco.com.br/job/60ccd07ae01d37001d24fcf8?c=3822
E clicar em "QUERO PARTICIPAR"

Eiiii e se quiser se candidatar em outras vagas que achar interessante, pode ficar a vontade.

Labels

🏢 Remoto

👴 Sênior

⚖️CLT/ PJ

💰 6,5k-11k

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
