### ISSUE TITLE
[REMOTO] iOS Developer na Kobe - Creative Software House

### ISSUE THREAD

**Issue by patriciagueds** [frontendbr/vagas#5259]
E se você pudesse impactar a vida de milhões de pessoas fazendo parte de uma Software House **reconhecida pela Apple como um case de sucesso** e que atua fortemente em **projetos de grande expressão mundial**?
 
Vem pra Kobe! 🎯
 
Acessa o link pra ver nossa [página de carreiras dedicada a iOS](www.kobe.io/careers-ios).
Ou me chama no [Linkedin](https://www.linkedin.com/in/patriciaguedes/) para conversarmos sobre a empresa!
 
#developer #ios #swiftUI

## Nossa empresa

Somos uma startup que ajuda empresas a desenhar, criar e lançar produtos digitais. Temos 7 anos de história e uma mentalidade jovem e ambiciosa. Com uma equipe criativa, empática e apaixonada por tecnologia, criamos apps, plataformas e consultorias que trazem ideias à vida. 

A Kobe vive seu mundo por stacks e o iOS é um mundo à parte. Sendo uma das nossas principais tecnologias, o iOS está no nosso DNA desde o início da nossa história no Apple Developer Academy e permanece com uma parceria com a Apple Inc.  Ao longo do caminho já impactamos mais de 40.000.000 de pessoas com as nossas soluções. E este é só o início. Quer fazer parte desta história?  

Como uma pessoa desenvolvedora iOS na Kobe, você contribuirá para a construção de experiências que aliam alta tecnologia a um design surpreendente. Você fará parte do nosso time de Engenharia, trabalhando ao lado de pessoas talentosas em projetos desafiadores que elevarão a sua carreira a um novo patamar. 

Você estará em um ambiente ágil reconhecido como Great Place to Work em 2018, 2019 e 2020. Nos últimos dois anos estamos no top 3 das melhores pequenas empresas para se trabalhar no RS e no top 9 do mesmo ranking em território nacional. 

A Kobe possui políticas remote-first. Não importa onde você estiver, nossa cultura chega até você!

## Descrição da vaga

Suas principais responsabilidades serão:

- Desenvolver aplicativos iOS (**SwiftUI**);
- **Dar suporte a todo ciclo de vida de aplicações**: concepção, design, teste, release e suporte a novas e existentes funcionalidades;
- **Analisar, compreender e discutir os requisitos técnicos e funcionais**, propondo a melhor abordagem para o desenvolvimento e testes;
- Acompanhar entregas específicas com um **espírito inovador, melhoria contínua e obsessão por superar as expectativas do cliente**;
- Contribuir com um time em constante crescimento propondo **novos códigos, componentes e processos para melhorar nossa prática de desenvolvimento**.

## ABOUT YOU

O desafio vai ser mais natural se você tiver:

- Experiência de **3+ anos no desenvolvimento de aplicativos iOS (Swift)**;
- Atuação nas **diferentes etapas do ciclo de vida** de um app;
- Experiência em **testes unitários e de integração**;
- Vivência atuando em **times ágeis**;
- Orientação para UX.
 
Pontos extra que poderão fazer teu perfil se destacar:

- Vivência em equipes de grande porte;
- Experiência liderando times;
- Desenvolvimento de diferentes projetos pessoais e colaborativos;
- Habilidade de comunicação interpessoal, com clientes e team members;
- Autonomia para a tomada de decisões;
- Conhecimento e boas práticas em acessibilidade.

## Local

A Kobe possui **políticas remote-first**. Não importa onde você estiver, nossa cultura chega até você!

## Benefícios

- Plano de saúde e odontológico
- Seguro de vida
- Plano de Desenvolvimento Individual
- Férias Remuneradas

## Contratação

PJ (mais CLT que você já viu!)

## Como se candidatar

Envie um email para patricia.guedes@kobe.io demonstrando interesse na vaga ou me chama no [Linkedin](https://www.linkedin.com/in/patriciaguedes/).

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
