### ISSUE TITLE
[São Paulo] Front-End Developer Sênior na Robert Half

### ISSUE THREAD

**Issue by FernandoMoset** [frontendbr/vagas#526]
## Descrição da vaga

Profissional front end com foco em javascript e node.js para atuar com produtos voltados para soluções de crédito e meios de pagamento em startup europeia.

## Local

Escritório na Vila Olimpia, zona sul de SP.

## Benefícios

- Plano de saúde
- Seguro de vida
- Vale Refeição
- Vale Transporte
- Remuneração acima do mercado

#### Diferenciais

- horário flexível
- startup (clima informal)
- networking com startups europeias
- treinamentos na Bulgaria

## Requisitos

**Obrigatórios:**
- 4 anos ou mais de experiência com desenvolvimento frond end
- inglês fluente

## Contratação

CLT full

## Nossa empresa

Aqui na Corporação ACME somos líderes em...

## Como se candidatar

Por favor envie um email para fernando.bezerra@roberthalf.com.br com seu CV anexado - enviar no assunto: Vaga FE-DEV

Obrigado!

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
