### ISSUE TITLE
[Remoto] Front-end Vue Developer na eureciclo

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#5260]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-vue-developer-200017503?origin=github&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Buscamos <strong><em><ins>Pessoas Desenvolvedoras Front-end Vue.js</ins></em></strong> em nível pleno.</p>
<h6><strong>SOBRE NÓS</strong></h6>
<p>O selo eureciclo foi criado em 2016 pela New Hope Ecotech, com o objetivo desenvolver e transformar o setor de reciclagem numa cadeia sustentável através de inovação e tecnologia.</p>
<p>Fazemos a compensação ambiental das embalagens de empresas de bens de consumo através de nossa plataforma e com o apoio de centrais de triagem parceiras. Hoje já são mais de 2.000 empresas que contribuem financeiramente e recebem o selo eureciclo em suas embalagens, mostrando seu compromisso ambiental para os consumidores 😊♻️</p>

## eureciclo: 
 <p>Surgimos para solucionar dois grandes problemas: a destinação final de embalagens geradas por empresas e a marginalização dos agentes da cadeia de reciclagem.&nbsp;</p>
<p>Pensando nisso, a New Hope Ecotech, empresa líder em tecnologias para gestão de resíduos sólidos no Brasil, desenvolveu uma plataforma capaz de rastrear e armazenar dados da cadeia de reciclagem, garantindo Certificados de Reciclagem robustos e transparentes, a partir dos investimentos direcionados ao setor. Trouxemos para a América Latina o conceito de compensação ambiental de embalagens, e somos hoje a maior certificadora de logística reversa do Brasil.&nbsp;</p><a href='https://coodesh.com/empresas/eureciclo'>Veja mais no site</a>

 ## Habilidades: 
 - HTML 5 
- Javascript 
- Vue.js 
- GIT 
- CSS 3 
- Vuex
## Local: 
 100% Remoto
## Requisitos: 
 - Conhecimentos ou experiências em front-end Vue.js 
- Experiência na criação de páginas web responsivas e landing-pages integradas com backend via APIs 
- Entusiasmo por design UI/UX, sem medo de HTML/CSS/Javascript 
- Familiaridade com sass ou scss 
- Raciocínio lógico, capacidade analítica e boas práticas de programação
**Diferenciais:** 
 - Experiência com Angular 6 ou AngularJS 
- Conhecimentos em Nuxt.js
## Benefícios: 
 - Bônus trimestral de 25% do salário pj 
- VR / VA 
- R$280 reembolso de convênio
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Front-end Vue Developer na eureciclo](https://coodesh.com/vagas/frontend-vue-developer-200017503?origin=github&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção <b>Pedir Feedback</b> entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa <b>Recruiter</b> responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Nível
Pleno
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
