### ISSUE TITLE
[REMOTO] Front-end Engineer na T10

### ISSUE THREAD

**Issue by zizg-reen** [frontendbr/vagas#5261]
## Nossa empresa

A **[T10](https://www.t10.digital/)** é uma startup de consultoria e desenvolvimento que empodera parceiros para a transformação digital. Foi criada por devs e para devs, e hoje reúne um time interdisciplinar, ágil e curioso. Nascemos do sonho de construir diariamente um ambiente de trabalho **plural**, **criativo**, **transparente** e **livre**.

## Descrição da vaga

Oportunidade para integrar o time de desenvolvimento **Front-end** da T10 & colaborar em projetos desafiadores e de alto nível técnico. Buscamos pessoas motivadas por estarem em uma posição de autonomia na solução de problemas, trabalhar em equipe e criar soluções escaláveis. 

Na T10, você será peça central no desenvolvimento do time, parte de uma equipe talentosa e com opiniões bem formadas sobre como softwares devem ser desenhados, modelados e implementados.

**Esperamos que a pessoa seja capaz de:**

- Reproduzir UI/UX com alta fidelidade;
- Desenhar e modelar arquiteturas front-end híbridas;
- Implementar, manter e entregar aplicações web;
- Manter e evoluir pipelines de testes;
- Gerenciar prioridades individuais, deadlines e entregáveis nos projetos;
- Adotar boas práticas de programação e.g. Clean Code, legibilidade e abstrações eficientes.

## Local

100% Remoto

## Requisitos

**Experiência e conhecimentos**

- Mínimo 3 anos de experiência atuando profissionalmente na área;
- Conhecimento de computação, conceitos e fundamentos;
- Fluência em JavaScript e bibliotecas de Front-end (ênfase em `React`);
- Conhecimento e experiência na implementação de CI/CD;
- Experiência com testes unitários e e2e (`Jest`, `Cypress`, `Puppeteer`);
- Experiência com `NextJS` (SSG e SSR);
- Experiência com deploy e infraestrutura;
- Experiência com `TypeScript`;
- Familiaridade com Git Flow (Pull Requests e Code Reviews).

**Bônus**

- Functional Approach;
- Experiência com ReScript;
- Experiência com AWS (S3, Route 53, CloudFront).

## Benefícios

- VA/VR
- Auxílio Saúde Mental
- Auxílio Home Office
- Bradesco Saúde
- Equipamento
- Gympass

**Diferenciais**

- Faixa salarial de 7K
- Ambiente descontraído
- Time colaborativo
- Startup que prioriza o desenvolvimento pessoal/profissional dos talentos
- Excelente perspectiva de crescimento para a T10

## Contratação

CLT

## Como se candidatar

Pelo link: https://t10.gupy.io/jobs/1011138

## O processo na T10

**1. Triagem Inicial**
Verificamos se seu perfil é compatível com o que buscamos
**2. Bate-papo Inicial**
As pessoas recrutadoras da T10 conduzirão uma troca de ideias rápida para contextualizar você sobre a T10 e a vaga
**3. Avaliação Técnica - Desafio, Live Coding ou White Board**
Eat, Sleep, `Code`, Repeat
**4. Entrevista Técnica**
Nossas lideranças técnicas conduzem uma troca de ideias mais profunda para identificar o match técnico e alinhar expectativas
**5. Proposta**
Tudo certo? Faremos uma call para comunicar a proposta e esclarecer detalhes da contratação
**6. Contratação**
Por último, entramos em contato para acertar detalhes finais da contratação (data de início, documentação necessária, etc)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 30 dias após cada processo.
E-mail para contato em caso de não haver resposta: talents@t10.digital

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by zizg-reen** [comment]
ainda disponível

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
