### ISSUE TITLE
[Curitiba] Front-end Developer na Weon

### ISSUE THREAD

**Issue by Janaina-Lima** [frontendbr/vagas#5262]
**Atividades:**

Como desenvolvedor, irá atuar em novas features, além de realizar manutenções.

Atuar em plataforma de desenvolvimento de supervisor, em squad de percepção de valor para agregar valor nas informações para o usuário, com telas de monitoramento em tempo real e construção de ferramentas como gráficos e dashboard.

**Requisitos:**

Dois anos de experiência em desenvolvimento web;
Conhecimento em JavaScript; 
Experiência no desenvolvimento de aplicações SPA em Vue.js. 
Conhecimento em Vuex, Vuetify, CSS, GIT .

**Diferencial**

Qualquer experiência com desenvolvimento web com outros frameworks
Noção de funcionamento de API
Material Design
UX
Integração com APIs
Responsividade

**Benefícios:**

Plano de saúde Unimed após período de experiência
Plano Odontológico após período de experiência
Auxílio em % do pagamento de capacitação ou cursos de graduação ou pós-graduação
VA ou VR de R$ 25,00 por dia.
Horário de trabalho: comercial das 8:00 às 18:00 horas – em pandemia será modelo híbrido, uma semana no escritório e uma semana em home office.

**Tipo de contratação:** CLT

Interessados encaminhar cv para contato@icontalent.com.br - enviar no assunto: Vaga Desenvolvedor Frontend Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
