### ISSUE TITLE
[São Paulo] Front-end Developer na Lambda3

### ISSUE THREAD

**Issue by AmorimRob** [frontendbr/vagas#5263]
## Sobre nós

A Lambda3 é uma consultoria de desenvolvimento de software sob medida que se organiza de forma colaborativa para buscar as melhores soluções de tecnologia para as empresas que trabalham conosco. Nossos times são formados por pessoas que são curiosas e que adoram resolver problemas. Somos pessoas desenvolvedoras, agile coaches, designers, pessoas consultoras e analistas de negócio que buscam entregar valor de maneira contínua e com excelência técnica.

## Descrição da vaga

A gente já te adianta de antemão que essa vaga é para oportunidade remota (complementar com full-time/temporária durante o período de pandemia) ou presencial no escritório da Lambda3 aqui em São Paulo, afinal, você escolhe o que for melhor, e o que esperamos da Pessoa Desenvolvedora Frontend é que ela esteja disposta e goste de desafios técnicos, e por isso recrutamos pessoas que queiram aprender em todos os momentos e que possa contribuir com times autogerenciáveis.

 
### Aqui você terá a oportunidade de:
- Participar desde a ideação e concepção de produtos e serviços, até sua entrega e sustentação;
- Fazer escolhas e/ou discussões das tecnologias que serão empregadas em projetos;
- Participar e contribuir com projetos que utilizam metodologias de entrega ágil, integração contínua e desenvolvimento guiado por testes (TDD), comportamento (BDD), técnicas de modelagem e pair programming;
- Atuar nos projetos com ritmo sustentável, entendendo sempre como entregar os melhores resultados sem sobrecarregar o time,
- Contribuir com a evolução dos nossos projetos sendo parte de um time de alta performance que atua diretamente com empresas de relevância nacional e internacional.

### Experiências relevantes em desenvolvimento:
- Design Responsivo;
- Acessibilidade;
- Testes automatizados;
- Versionamento de código com Git e/ou TFVC;
- Conhecimento em algumframework SPA com JavaScript/TypeScript

### Outras coisas que valorizamos dentro da Lambda3:
- Conhecimento diversificado;
- Conhecimento em tecnologias de nuvem;
- Conhecimento de automação de processos de Build e Release;
- Experiência com práticas ágeis como Scrum, Kanban e XP;
- Participação em comunidades de tecnologia.

## Local

Exemplo: Remoto ou Escritório, São Paulo, SP, Consolação

## Contratação

CLT

## Como se candidatar

Basta nos enviar seu currículo através deste endereço https://lambda3.recruiterbox.com/jobs/fk0uclf/ 

#### Alocação
- No escritório
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
