### ISSUE TITLE
[REMOTO] Senior Front-end Engineer na Mosaic (USA)

### ISSUE THREAD

**Issue by rodrigoreis22** [frontendbr/vagas#5264]
Olá meu nome é Rodrigo e sou Tech Lead na Mosaic, uma startup americana no setor de construção civil. A vaga é para pagamento em Dólar $$, nível sênior e Inglês é necessário pois toda equipe é americana (eu sou o primeiro brasileiro da equipe). Mesmo que você ache que não possua todos os requisitos eu recomendo aplicar. Também estou a disposição para analisar o seu currículo/linkedin e também o seu inglês, é só me enviar um email que marcamos uma conversa de 15 minutos: rodrigo@mosaic.us 

Segue abaixo a vaga em inglês:

## Nossa empresa

Mosaic is a construction technology company focusing on homebuilding. We serve as a turn-key general contractor for medium-sized homebuilders while also developing a software platform that we use to automate and streamline our construction operations. Our vision is to leverage our platform to create the world’s most scalable homebuilding operation and to empower home builders everywhere.

Today, with our [Series A led by Andreessen Horowitz](https://a16z.com/2020/09/02/investing-in-mosaic/), $24M+ in total funding, and a recent [$100M partnership](https://therealdeal.com/2020/09/02/tech-startup-inks-100m-deal-to-help-build-400-homes/) with a best-in-class, innovative homebuilder, we’re launching our platform to build better communities together with our partner towards our [mission](https://mosaic.us/blog/breaking-new-ground-the-mosaic-story/) of making places people love and making them widely available.

We have one speed at Mosaic: full speed. With over 100 homes under active construction, we have an incredible advantage over the rest of the construction technology industry. Our ability to move quickly, stay nimble, and embrace change is critical to maintaining that advantage. Our strategy, projects, titles, and focus may change. But what will not change is our speed. Individuals who exhibit and resonate with these values are likely to find success with us. You can read more about Mosaic and our mission [here](https://mosaic.us/blog/).

## Descrição da vaga

As a Senior Software Engineer on our team, you will use an open-source technology stack to build an industry-first suite of construction management applications, services, and tools. These technologies are a critical component to Mosaic's growing differentiation in construction operations.

## Local

**Remote**, D.C., Phoenix, San Francisco

## Requisitos

**Obrigatórios:**

- Bachelor’s degree in Computer Science, Engineering, or equivalent experience
- 5+ years of experience in front-end engineering: Javascript, CSS, and React expertise is required
- Ability to recognize and contribute to high-quality product design
- Experience linking to backend services via RESTful APIs
- Strong communicator, particularly for technical writing
- Exceptional teamwork skills and partnering with remote teams
- Attention to detail and ability to write well-tested, well-structured code
- A healthy curiosity for new technology, but a deep understanding of proven technology

**Desejáveis:**
- Experience with responsive and mobile web application engineering
- Experience working in an Agile team and understanding of Agile processes
- Experience integrating with and across ERP systems
- Experience with GraphQL or Hasura
- Experience with business intelligence tools such as Tableau
- Experience with 3D web graphics such as ThreeJS or WebGL
- Track record of working autonomously and being comfortable with ambiguity, particularly in a fast-paced environment like a startup
- Experience in the construction management and operation space
- Interest in construction, architecture, or affordable housing 

## Benefícios

- Plano de saúde
- Férias ilimitadas
- Viagens para os EUA para conhecer a equipe

**Diferenciais:**
- Equipamento: MacBook novo fornecido pela empresa

## Contratação

PJ (pagamento será feito em Dólar através de um sistema de pagamentos para times remotos globais)

## Como se candidatar

Use o link [https://bit.ly/SrFrontEndMosaic](https://bit.ly/SrFrontEndMosaic) e clique em Apply. 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: rodrigo@mosaic.us
I encourage you to apply even if you feel like you don't have all the requirements.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
