### ISSUE TITLE
[Remoto] Front-end Developer na T.Group

### ISSUE THREAD

**Issue by Simonetgroup** [frontendbr/vagas#5265]
Sobre nós:

A Lomadee é pioneira no mercado de marketing de afiliados e está sempre inovando e trazendo diferenciais ao mercado.

Com um novo cenário e um e-commerce cada vez mais maduro, estamos com novos planos estratégicos para 2021 e com previsão de crescimento acelerado. Por isso, buscamos uma pessoa que esteja engajada a identificar oportunidades e que goste de inovar. Na Lomadee, também respeitamos a diversidade, temos uma cultura totalmente inclusiva que busca a equidade e valoriza as diferenças. Por esse motivo, as nossas posições também são destinadas a pessoas com deficiência.

Você gosta de desafios? Então aqui é o seu lugar!

Nesse cargo, você vai:

Entender a proposta do negócio e a experiência do cliente esperada;

Implementar e testar códigos e interfaces eficientes;

Rodar testes junto com os demais membros do time de backend.

Gostou? Então vem com a gente, se você é uma pessoa que:

 
Possui colaboração virtual, ou seja, tem facilidade em trabalhar remotamente (a vaga é 100% remota);
É flexível e adaptável, uma vez que os desafios de tecnologia mudam ao longo do tempo, é preciso estar disposto a conhecer e trocar experiencias;

Tem a organização como qualidade;

Faz a gestão adequada do tempo.

O que você precisa para participar do processo:

Possuir formação sólida em Ciências da Computação ou áreas relacionadas;

Experiência no desenvolvimento de aplicações front end;

Conhecer ferramentas de desenvolvimento de software e linguagens específicas (React, Angular);

Conhecimento de ferramentas de controle de versão (GIT);

Estar disposto a se atualizar e conhecer novas tecnologias.

Será um diferencial, caso você tenha:

Inglês intermediário/avançado;

Conhecimento em ferramentas de testes automatizados.

Oferecemos os seguintes benefícios:

Participação nos lucros e resultados - PLR;

Vale-Refeição ou Vale Alimentação**;

Auxílio creche para crianças até 5 anos;

Seguro de Vida em grupo;

Cartão Multibenefícios – (com desconto na compra de diversos itens na rede credenciada, incluindo medicamentos em diversas redes de farmácias);

Sesc;

Política educacional para graduação e pós-graduação;

Assistência Médica – Amil (convênio coparticipativo) **;

Convênio Odontológico (Amil)*.

Local de Trabalho: 100% remoto

Horário: Flexível (9h – 18h)

Salário: A combinar

Interessados encaminhar currículo para Simone.dantas@tgroup.com.br

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
