### ISSUE TITLE
[Remoto] Gerente de Desenvolvimento Front - End na Studio Sol 

### ISSUE THREAD

**Issue by tguimaraes13** [frontendbr/vagas#5271]
## Nossa empresa
 A Studio Sol é uma empresa mineira líder em download de aplicativos e possui os maiores portais de música do Brasil.

Nosso propósito é criar produtos inovadores para o maior número de pessoas viverem experiências transformadoras e queremos que você construa isso com a gente.

Estamos buscando pessoas que cuidem com muito carinho e atenção de nossos nossos sites desktop e mobile. React, Sass, REST, GraphQL, CSS Modules são alguns recursos que utilizamos.

Usabilidade, com código otimizado e performático é o nosso foco. 💪🏼

## Descrição da vaga
As principais funções e responsabilidades que os líderes aqui exercem são:
- Monitorar a performance e estabilidade dos sites;
- Acompanhar KPIs; 
- Gerenciar e desenvolver a carreira de pessoas desenvolvedoras frontends;
- Dar feedbacks; 
- Reuniões de 1:1; 
- Criação de PDIs;
- Planejar tarefas alinhadas com os objetivos;
- Comunicar com demais equipes envolvidas no produto;
- Acompanhar ponto de funcionários;
- Participar ativamente de processos seletivos;
- Avaliar desempenho;
- Mentorar e assessorar tecnicamente a equipe;

Se identificou? Vem trabalhar com a gente! 😄

## Local

 Remoto

## Requisitos

**Obrigatórios:**
- Domínio de Javascript, CSS e HTML;
- Performance  (tanto do Javascript, quanto do CSS. Sim CSS!);
- Design responsivo;
- Conhecimentos em SEO;
- React;
- Typescript;
- Controle de versão Git;
- Ferramentas de automação e build (webpack);
- Consumo de APIs REST;
- Padrões de projeto, 
- Experiência com liderança de equipes,
- Conhecimento em metodologias ágeis.

**Desejáveis:**
- Experiência com testes unitários e testes ponta a ponta (e2e);
- Experiência em desenvolvimento Front-end de pelo menos 5 anos;

## Benefícios

- Plano de saúde;
- VR e VA de R$ 35/dia;
- Licença Maternidade estendida; 
- Auxílio Home Office; 
- Plano Odontológico; 
- Temos ginástica laboral;
- Livre acesso à cursos variados pela Alura. 

**Diferenciais:**
- Horário Flexível e banco de horas. 

## Contratação

Regime CLT - 40 horas semanais 

## Como se candidatar

Por favor envie um email para tamyris.guimaraes@studiosol.com.br com seu CV anexado - enviar no assunto: Vaga Gerente Front - End.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@studiosol.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
