### ISSUE TITLE
[Remoto] Front-End Developer em Grupo Gera, Salário : 6.5K

### ISSUE THREAD

**Issue by tiagolisalves** [frontendbr/vagas#5273]
## Grupo Gera

Somos uma empresa que está transformando o mercado de energia e o mundo! Atuamos em projetos de geração por meio de fontes renováveis, gestão, inovação e eficiência energética para algumas das maiores empresas do país e queremos ir cada vez mais longe. Acreditamos que só é possível alcançar o sucesso com uma equipe incrível, valorizando o bem-estar e capacitando nossos colaboradores. 

## Descrição da vaga

- Implementar o frontend dos produtos digitais;
- Desenvolver testes unitários com foco em aumentar a segurança no desenvolvimento;
- Implementar interfaces utilizando o Design System da empresa;
- Participar e contribuir no processo de desenvolvimento;
- Ter aptidão para atuar no backend se necessário. 

## Local

Remoto, RJ, Botafogo

## Requisitos

**Obrigatórios:**
- Desenvolvimento com o ecossistema do Angular ou do React;
- Reactive Programming utilizando RxJs;
- Criação de páginas com CSS/SCSS/HTML;
- Typescript e Orientação a objetos.

**Diferenciais:**
- Experiência em testes unitários;
- Bom conhecimento em metodologias para CSS como BEM e SMACSS;
- Programação funcional;
- Node.js e Banco de Dados.

## Benefícios

- Salário : 6.5K 
- Reembolso plano de saúde
- VR/VA de R$ 27,5/dia
- Férias

## Contratação

PJ

## Como se candidatar

Caso tenha interesse, por favor, enviar currículo para recrutamento@grupogera.com, com o assunto: Seu Nome - Vaga de Desenvolvimento Frontend Pleno. 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by tiagolisalves** [comment]
@felipefialho RJ

**Comment by tiagolisalves** [comment]
A empresa fica no RJ

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
