### ISSUE TITLE
[Remoto] Front-end Developer na Central do Frete

### ISSUE THREAD

**Issue by xandyalexandrec** [frontendbr/vagas#5274]
## Nossa empresa

A Central do Frete veio para transformar a maneira como empresas contratam fretes, sempre pensando em formas de descomplicar processos, encantar pessoas e inovar o setor. Chegamos para questionar cenários, liderar mudanças e ser uma marca referência em tudo que se propõe a fazer.

[https://centraldofrete.com](https://centraldofrete.com)

## Descrição da vaga

- Sprints semanais usando Jira
- Código armazenado no Github
- Comunicação via Discord
- Equipe pequena
- Frontend em React utilizando Material
- Backend em PHP com Laravel usando GraphQL

## Local

100% Remoto

## Requisitos

- Experiência comprovada de pelo menos 3 anos com React;
- Habituado a extrair e desenvolver layout a partir do Figma;
- Habituado a utilizar Material UI;
- Conhecimentos com GraphQL;
- Ótima percepção de UX/UI;

## Contratação

Contratação via PJ, sem exigência de horário fixo. Combinamos as demandas da semana em comum acordo e você executa durante o horário que você tem melhor performance. Funcionando como prestação de serviço sem vínculos.

## Como se candidatar

Envie um e-mail para alexandre@centraldofrete.com com:
- Assunto: Vaga Frontend Developer
- Uma pequena carta de apresentação
- CV anexado
- Link do seu Github
- Link do seu LinkedIn

## Tempo médio de feedbacks

Média de até 5 dias úteis.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
