### ISSUE TITLE
[Remoto] Front-end React Developer(Remoto) na Evolux Sistemas

### ISSUE THREAD

**Issue by jeanpereiraa** [frontendbr/vagas#5277]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedora-frontend-pleno-ou-senior-remoto-112018?origin=github&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A empresa Evolux está buscando <strong>Front-End React Developer </strong>em nível Pleno ou Sênior!</p>
<p>Somos uma empresa certificada GPTW e precisamos de pessoas que sejam curiosas, proativas e em constante aprendizado, de comunicação direta e clara, seja via email ou conferência online.&nbsp;</p>
<p><strong>Sua missão na Evolux: </strong></p>
<ul>
<li>Além de naturalmente programar, a pessoa desenvolvedora frontend na Evolux tem o incentivo de contribuir em diversos projetos (até mesmo free sources) e desafios diversos e únicos, como aplicações realtime, tecnologias WebRTC, melhorias de usabilidade, implementação de design systems, migração de projetos legado e interação com times estrangeiros.&nbsp;</li>
<li>Na Evolux você terá oportunidade de modificar abertamente o dia a dia da empresa, sugerindo novos projetos, experimentando ferramentas, adaptando metodologias, colaborando com comunidades locais de tecnologia, participando de eventos nacionais, organizando treinamentos internos e colaborando com os OKRs do setor.</li>
<li>Caso integre os times de outsourcing, irá ter contato direto com os clientes de fora do país, atuando desde a coleta de requisitos até a interoperabilidade com outros desenvolvedores e eventos ao redor do mundo.</li>
</ul>

## Evolux Sistemas: 
 <p>A Evolux desenvolve uma plataforma robusta 100% web para operações de médio e grande porte com DAC, Discador e URA. Todos os painéis e relatórios são atualizados em tempo real para que seja possível gerir com precisão a experiência que o seu cliente tem ao entrar em contato com você.&nbsp;</p>
<p>Todas as interfaces, servidores, aparelhos IP e software estão inclusas no preço da PA (Call Center como Serviço | CCaaS). Dessa maneira garantimos o pleno funcionamento da operação e você pode se preocupar com o mais importante do seu negócio: o Atendimento ao Cliente.</p><a href='https://coodesh.com/empresas/evolux-sistemas'>Veja mais no site</a>

 ## Habilidades: 
 - CSS 
- Javascript 
- React.js 
- React Native 
- Redux 
- Preact
## Local: 
 100% Remoto
## Requisitos: 
 - HTML e CSS; 
- JavaScript (ECMAScript); 
- Git (ou Mercurial); 
- Ecossistema React e Redux/MobX; 
- Familiaridade com testes;  
- Leitura e escrita em inglês;  
- Boa comunicação técnica com sua equipe em português.
**Diferenciais:** 
 - Fluência geral em inglês; 
- Participação em projetos free source; 
- Conhecimentos básicos de usabilidade; 
- Habituado com a Metodologia Ágil; 
- Conhecimento em desenvolvimento Python. 
- Experiência em Trabalho remoto; 
- Arquitetação e manutenção de aplicações reais em React;  
- Vivência com antecipação e depuração de problemas dessa stack.
## Benefícios: 
 - Envio de equipamento de trabalho 
- Subsídios para cursos, certificações, eventos 
- Pelo menos R$ 924 em benefícios de alimentação (R$ 924), cultura (R$ 100) e auxílio de plano saúde 
- Bônus por trabalho remoto R$ 300
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Front-end React Developer(Remoto) na Evolux Sistemas](https://coodesh.com/vagas/desenvolvedora-frontend-pleno-ou-senior-remoto-112018?origin=github&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção <b>Pedir Feedback</b> entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa <b>Recruiter</b> responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by jeanpereiraa** [comment]
bom dia, eu fechei está vaga, pelo menos para mim está aparecendo como
fechada

Em sex., 10 de set. de 2021 às 21:24, Felipe Fialho <
***@***.***> escreveu:
