### ISSUE TITLE
[Remota] Front-end Angular Developer na BTG Pactual

### ISSUE THREAD

**Issue by alvaropsc** [frontendbr/vagas#5278]
## Nossa empresa

O BTG Pactual é o maior banco de investimentos da América Latina, somos
meritocráticos com uma equipe versátil. Valorizamos quem tem cabeça de dono, sonha grande e é apaixonado em aprender e ensinar.
A área de tecnologia do Banco tem crescido a cada dia e temos certeza que ela protagonizará os novos modelos de negócios do banco. Diante dessa grande missão, prezamos por um time de alta qualidade para solucionar importante desafios.
Área responsável pela plataforma que controla toda a captura de dados de mercado de instrumentos financeiros de diferentes fontes, bem como os sistemas que permitem toda a governança destes dados desde o cadastro até a distribuição dos mesmos para demais áreas do banco. Atuamos no suporte a produção e desenvolvimento de projetos interagindo diretamente com usuários do time de BackOffice bem como os demais times de IT para permitir a integração dos dados via sistema, usando plataforma de integração diversificada como filas, APIs, serviços na nuvem, arquivaria e mensageria.

## Descrição da vaga

- Desenvolvimento e manutenção de módulos web utilizando Angular 8+ e Typescript;
- Perfil empreendedor, com alto nível de energia e aptidão para encarar novos desafios;
- Acompanhar junto do cliente a validação das novas funcionalidades e sua posterior disponibilização em ambiente produtivo;
- Entendimento dos fluxos de negócio de nossos clientes e desenvolver propostas de soluções;
- Participar das dinâmicas do desenvolvimento de software ágil;
- Relacionamento próximo com as áreas de negócio e outras equipes de IT de todas as localidades do Grupo BTG Pactual.

## Local

100% Remoto

## Requisitos

**Obrigatórios:**
- Bons conhecimentos: Angular 8+ e Typescript
- Alguma experiência em: RXJS, SASS, graphQL, NPM/Yarn

**Desejáveis:**
- Microfrontends e Jenkins (Pipeline)

**Diferenciais:**
-Formação completa, preferencialmente em Tecnologia da Informação, Engenharia ou áreas relacionadas;
-Capacidade de organização com múltiplas atividades e requisições simultâneas;
-Capacidade de comunicação e relacionamento interpessoal para apresentar os casos e discuti-los com demais áreas envolvidas;
-Raciocínio lógico e capacidade analítica;
-Paixão em aprender novas habilidades, linguagens e tecnologias, capazes de impulsionar novos modelos de negócios. -Acreditamos em usar a melhor ferramenta para resolver cada problema e o aprendizado contínuo não deve ser um empecilho;
- Desejável conhecimento em mercado financeiro.

## Contratação

CLT - Remuneração Compatível com o Mercado 

## Como se candidatar

Por favor envie um email para alvaro.luiz@yolorecruit.com com seu CV anexado - enviar no assunto: Frontend Angular

## Tempo médio de feedbacks

Costumamos enviar feedbacks imediatos.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
