### ISSUE TITLE
[Remoto] Front-end Developer na Beon

### ISSUE THREAD

**Issue by GusPrado** [frontendbr/vagas#5279]
### TIME BEON STUDIO

Sua função será produzir e manter as interfaces das aplicações Beon, assim como criar e desenvolver as arquiteturas necessárias destas aplicações de acordo com as atividades de negócio envolvidas. Sua capacidade de manter-se atualizado com as melhores práticas do mercado de Frontend será de fundamental importância nesta posição. Consideramos também que você tenha experiência profissional comprovada na área de no mínimo 1 (um) ano de atuação trabalhando com as tecnologias exigidas.

## O Beon

No Beon somos focados em Experiência do Consumidor. Nós aplicamos a Personalização para obter incrementos significativos na conversão e outras métricas importantes do e-commerce e muito em breve iremos atuar além do e-commerce, em novas frentes.

Em 2020 aconteceram duas coisas importantes, crescemos nossa base de clientes em 500%, e descobrimos uma vocação para o trabalho remoto que não acreditávamos ter.

[Conheça mais sobre o Beon](https://www.beon.com.br)

## Local

100% REMOTO

## Requisitos
- Conhecimento profundo de HTML, CSS e Javascript (ES6+).
- Domínio da lib ReactJS e conhecimento do seu ecossistema, assim como gerenciamento de estado e do ciclo de vida de componentes (via Hooks e Classes).
- Conhecimento da arquitetura Flux – Redux, Context API, etc.
- Conhecimento básico sobre técnicas de UX/UI.
- Experiência com ferramentas de controle de versão, como Git.

**Obrigatórios:**
- 1 ano de experiência com React.JS

**Desejáveis:**
- Desenvolvimento de testes unitários e de integração.
- Utilização de mecanismos de CI/CD.
- Experiência prévia com RESTful APIs.

## Benefícios

- Auxílio alimentação
- Treinamentos técnicos
- Incentivos extras

**Diferenciais:**
Aqui sua opinião realmente importa. Temos uma cultura inclusiva onde as opiniões dos colaboradores são escutadas ao nível do CEO.

## Contratação

PJ R$4.000,00.

## Como se candidatar

Por favor acesse o link: https://usebeon.enlizt.me/vagas/desenvolvedor_front-end_react.js-070721

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

**Comment by jon-by** [comment]
Opa @GusPrado tudo bem? 
qual a forma de monitoramento do trabalho? vocês usam clockfy ou alguma ferramenta do gênero?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
