### ISSUE TITLE
[São Paulo/SP] Dev. Front-end Junior/Pleno no SuperAgendador.com

### ISSUE THREAD

**Issue by jbaladao** [frontendbr/vagas#528]
#  Descrição da vaga

A startup SuperAgendador.com é um SaaS para prestadores de serviços. Procuramos um profissional com pelo menos 1 ano de experiência com AngularJS.

## Local

Próximo ao metro Jabaquara, São Paulo - SP

## Benefícios

- 1 hora de almoço
- café da manhã, bebidas no frigobar
- PS4 liberado com vários jogos para descontrair

## Obrigatórios:

1 ano de experiência com Angular, qualquer versão!
2 anos de experiência com programação JavaScript.
Conhecimentos avançados em HTML e CSS.

## Desejáveis:

ter trabalhado em alguma startup
ter trabalhado com algum sistema online no modelo SaaS
alguma experiência com aplicativos mobile
alguma experiência com metodologias ágeis de desenvolvimento

## Contratação

PJ a combinar

# Nossa empresa

O SuperAgendador.com é um dos maiores sistemas de gestão para Prestadores de Serviços do Brasil, nossos clientes movimentaram juntos aproximadamente 25 milhões de reais em dezembro de 2016. A empresa já foi acelerada em 2016 no evento InvestorsDay da CampusParty (anjos via Broota) e agora em 2017 recebeu um novo investimento do grupo Bossa Nova (pré-seed).
Estamos naquela fase incrível onde uma pequena startup pode evoluir rapidamente para uma empresa de grande porte. Este é o nosso sonho, se quiser participar dele venha trabalhar conosco. Vivenciar o nascimento e transformação de uma Startup é incrível e as oportunidades de crescimento e aprendizado são muitas!

# Como se candidatar

Por favor envie um email para jbaladao@superagendador.com com seu CV anexado - enviar no assunto: Vaga Dev Front-end (ênfase em Angular)

# Outras vagas

Também estamos procurando por um Dev. NodeJS. Toda indicação será super bem vinda...

Muito obrigado!

**Comment by jbaladao** [comment]
Local.

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by jbaladao** [comment]
Reabrimos esta vaga!

**Comment by jbaladao** [comment]
fechada
