### ISSUE TITLE
[Remoto] Front-end Developer React / Redux na Gedanken

### ISSUE THREAD

**Issue by Caue15** [frontendbr/vagas#5282]
## Nossa empresa

Somos uma startup em crescimento exponencial que revoluciona a forma como grandes empresas se relacionam com seus fornecedores. Temos muito orgulho de formar um time de profissionais que atua em colaboração e que é cada vez mais incentivado a buscar soluções que estejam fora dos padrões.

## Descrição da vaga

Buscamos pessoas com vontade, disponibilidade e espírito de dono para trabalhar em um ambiente sem fronteiras.

Incentivamos a progressão de carreira por mérito, tendo como base o nosso principal valor: Respeito ao Indivíduo. Abraçamos a diversidade e vivemos sem distinção de gênero, cor, orientação sexual, crença religiosa, posição social ou deficiências. Nossos Gedankers possuem oportunidades iguais para se desenvolverem, dessa forma, atuamos com as melhores pessoas que, desde o primeiro momento, trazem valor para os clientes.

Se você é analítico, apaixonado por tecnologia, sabe gerenciar seu tempo e acima de tudo tem facilidade na resolução de problemas, essa vaga é para você

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Javascript (ES6)
- React
- Redux e Redux Saga
- HTML5
- CSS
- Estilizar componentes com styled-components
- Comprometimento com qualidade de código e planejamento.
- Integração com APIs REST

**Desejáveis:**
- Git
- Análise e levantamento de requisitos funcionais

**Diferenciais:**
- Conhecimento em GraphQl (Apollo) é um diferencial

## Contratação

PJ.

## Como se candidatar

Candidate-se no site: https://frontjobs.com.br/job/desenvolvedor-frontend-react-redux-gedanken-e545a037/

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
