### ISSUE TITLE
[Remoto] Front-end Developer na TGroup

### ISSUE THREAD

**Issue by Caue15** [frontendbr/vagas#5283]
## Nossa empresa

Com origem na maior empresa de antifraude do Brasil, Clearsale, que está há mais de 20 anos no mercado, nosso grupo reúne uma poderosa combinação de soluções na construção de confiança, usando como partida a jornada de compra do cliente final no processo de pré-venda, venda e pós venda. Conta com o Movimento Compre e Confie, que certifica e garante a confiabilidade dos e-commerces parceiros através do Selo de reputação e Banner de pesquisas, que também lidera as operações do Vipy, aplicativo que ajuda o consumidor digital de ponta a ponta, a Neotrust, empresa de pesquisa e inteligência de mercado, a aftersale, que atua na automatização de processos de logística reversa para o e-commerce, e a Lomadee, empresa com foco em marketing de afiliados. Através da transparência e da tecnologia, incentivamos a transformação e o talento, para ir além do que se é esperado.

## Descrição da vaga

Para este cargo de Analista de Frontend é necessário uma formação sólida em Ciência da Computação ou área relacionada e experiência no desenvolvimento de aplicações front end. Além do conhecimento já adquirido nas linguagens atuais, este profissional deve estar disposto a se atualizar e conhecer novas tecnologias.
As atribuições do cargo são:
- Entender a proposição do negócio e a experiência do cliente esperada
- Implementar e testar códigos e interfaces eficientes
- Rodar testes junto com os demais membros do time de backend

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Conhecer ferramentas de desenvolvimento de software e linguagens específicas (React)
- Conhecimento de ferramentas de controle de versão (GIT)
- Deploy de aplicações em containers

**Desejáveis:**
- Inglês intermediário ou superior
- Conhecimento em ferramentas de testes automatizados

## Contratação

PJ

## Como se candidatar

Candidate-se pelo site: https://frontjobs.com.br/job/dev-front-senior-react-tgroup-fd6c4225/

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
