### ISSUE TITLE
[Remoto ou São Paulo] Front-end Developer na Badaró Studio Design

### ISSUE THREAD

**Issue by Caue15** [frontendbr/vagas#5284]
## Nossa empresa

Estamos em busca de uma pessoa desenvolvedora, que já possua certa experiência e que esteja disposta a novos desafios. Ela chegará para somar a um timaço que já existe hoje na Badaró.

Queremos alguém que queira evoluir e que consiga ajudar na evolução técnica do nosso time, com conhecimentos em Inglês.

DIVERSIDADE E PLURALIDADE
Acreditamos que para promover maior equidade em nosso time, precisamos gerar mais oportunidades e sermos intencionais em nossas ações. Há preferência para contratação de profissionais negras e negros ou LGBTQI+ para esta vaga.

## Descrição da vaga

Aqui, o(a) Desenvolvedor Front-end é responsável pelo desenvolvimento de interfaces, criando códigos limpos, bem documentados e sempre seguindo as boas práticas do mercado. Além disso, atuará junto com o time de designers para criar a melhor experiência possível para os nossos clientes.

## Local

Remoto ou em São Paulo.

## Requisitos

**Obrigatórios:**
- Ter mais de 2 anos de experiência
- Detalhista e meticuloso
- Conhecimento em Angular OU React
- Conhecimento em desenvolvimento de componentes visuais
- Conhecimento em SASS/LESS
- Conhecimento em versionamento GIT
- Conhecimento em Storybook

**Diferenciais:**
- Inglês intermediário
- Experiência com Design System
- Conhecimentos em UI e ferramentas Figma e Adobe XD.
- Conhecimento em Python

##Diferenciais:
- Trabalho remoto 100% do tempo
- 30 dias de descanso remunerado (após 1 ano de Badaró)
- Cultura de inovação e aprendizado contínuo
- Investimento em capacitação
- Incentivo a participação em eventos
- Day-off no aniversário

## Contratação

PJ

## Como se candidatar

Mande um e-mail com seu currículo ou portifolio para tech@badaro.design
https://frontjobs.com.br/job/desenvolvedor-front-end-pleno-badaro-studio-design-ec8823c1/

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
