### ISSUE TITLE
[Remoto ou São Paulo] Front-end Developer na Badaró Studio Design

### ISSUE THREAD

**Issue by Caue15** [frontendbr/vagas#5286]
## Nossa empresa

Somos um Estúdio de Design e Tecnologia que há 8 anos coloca as pessoas no centro de experiências digitais impactantes.
No nosso programa de Alocação de Talentos, selecionamos profissionais com alta excelência técnica para compor e somar ao time de grandes empresas.

## Descrição da vaga

Estamos em busca de uma pessoa Desenvolvedora Front-end Senior para alocação em uma grande empresa de tecnologia e comunicação, com forte espírito de equipe, que busque por desafios e de trabalhar com novas tecnologias.

Acreditamos que para promover maior equidade em nosso time, precisamos gerar mais oportunidades e sermos intencionais em nossas ações. Há preferência para contratação de profissionais negras e negros ou LGBTQI+ para esta vaga.

## Local

Remoto ou em São Paulo.

## Requisitos

**Obrigatórios:**
- Flux
- Redux
- Hooks
- Class Components / Function Components
- React patterns (Smart/Dumb, render props, HOC, Context API)
- Management statement
- Life cycle
- Styled-components
- Web-components (design-system)
- RxJS
- Testes unitários (react-library-testing, Karma, Jest)
- Git, GitFlow
- OOP
- JavaScript (XMLHttRequest, Fetch, ES6 / ES2015)
- Typescript
- Linting

**Diferenciais:**
- Cloud (AWS, Azure ou GPC)
- Outras linguagens de programação (NodeJS, Java, etc)
- Experiência prévia em ambientes complexos
- Experiência prévia com portais ou sistemas de ecommerce
- Angular 14

## Diferenciais:
- Trabalho remoto 100% do tempo
- 30 dias de descanso remunerado (após 1 ano de Badaró)
- Cultura de inovação e aprendizado contínuo
- Investimento em capacitação
- Incentivo a participação em eventos
- Day-off no aniversário

## Contratação

PJ

## Como se candidatar

Mande um e-mail com seu currículo ou portifolio para tech@badaro.design
https://frontjobs.com.br/job/desenvolvedor-front-end-badaro-studio-design-0ddf0c77/

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
