### ISSUE TITLE
[São Paulo] Estágio em Front-End na Editora Segmento

### ISSUE THREAD

**Issue by raulfernando** [frontendbr/vagas#529]
## Descrição da vaga

Estamos buscando talentos para trabalhar como Front-End Developer.

## Local

Escritório, São Paulo - Pinheiros

## Benefícios

- VR de R$ 20,00/dia
- VT

## Requisitos

**Obrigatórios:**
- HTML5 e CSS3
- Noções de Javascript 

**Diferenciais:**
- Algum conhecimento em WordPress

## Contratação
- Estágio
- R$ 988,00
- 6 hrs/dia

## Nossa empresa

Nascida no ano de 1993 tendo como principais características a aposta no bom jornalismo, o senso empreendedor e uma fina percepção do mercado, a Editora Segmento é, hoje, uma das principais referências brasileiras na produção de conteúdos sobre educação e gestão de pessoas.

## Como se candidatar

Por favor envie um email para raul@editorasegmento.com.br com seu CV anexado - enviar no assunto: Vaga Estágio

**Comment by jonatasbueno** [comment]
Apenas estágio mesmo?

**Comment by raulfernando** [comment]
Sim, apenas estágio.

**Comment by vinirossi** [comment]
Currículo enviado.

**Comment by raulfernando** [comment]
Foi mau @vinirossi fechamos a vaga na sexta-feira só não deu tempo de postar aqui.

Closed!

**Comment by vinirossi** [comment]
@raulfernando Bom dia, realmente não tem como aceitar meu currículo?

**Comment by Blackbel** [comment]
A vaga ainda esta aberta?.Ainda esta aceitando currículo?

**Comment by vinyguedess** [comment]
@mateusguedess
