### ISSUE TITLE
[Remoto] Front-end Líder Técnico na 5A Attiva

### ISSUE THREAD

**Issue by Isabelacarrasco** [frontendbr/vagas#5290]
> Vaga Remota 

## Nossa empresa

5A Attiva

## Descrição da vaga
 Líder técnico front end, para uma grande empresa, atuar com equipe 100% focada em bons resultados.

## Local

100% Remoto 

## Requisitos

**Obrigatórios:**
Buscamos profissionais com experiência em tecnologias front-end (HTML, CSS e JS). 
Experiência de nível de domínio com AEM; implementação de soluções web responsivas e adaptáveis; 
Experiência de nível de domínio no desenvolvimento com frameworks front-end modernos (React, VueJS, Angular JS, Vanilla JS) 

## Contratação

PJ 

## Como se candidatar

Por favor envie um email para Helen.matos@5aattiva.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

O processo será 100% remoto e terá apenas 2 etapas: entrevista com alguma das nossas tech recruiter e entrevista técnica com cliente. vamos falar sobre a oportunidade?

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
