### ISSUE TITLE
[São Paulo] Front-end Developer na Leega

### ISSUE THREAD

**Issue by Rmoreau1** [frontendbr/vagas#5291]
## Nossa empresa

A LEEGA é referência em consultoria e outsourcing para soluções de Data Analytics .

Temos 10 ANOS de mercado e mais de 20 ANOS de experiência em soluções de Business Intelligence, Data Integration e Analytics, atendendo grandes empresas dos mais diversos segmentos do mercado e contamos com mais de 300 colaboradores.

Conquistamos capacidade técnica e reunimos as melhores pessoas para proporcionar aos nossos clientes a melhor experiência.

Brasileiros, com escritório de projetos, fábrica de software e centro de treinamento em São Paulo (capital) , atuação internacional com escritório também em Portugal, somos conhecidos por viver e respirar Analytics e Big Data, inovando nossa tecnologia, compartilhando conhecimento, evoluindo talentos e entregando VALOR.

Em nosso porftólio de serviços ofertamos consultoria especializada, alocação de profissionais, treinamento e desenvolvimento de soluções customizadas para Cloud Computing, Business Intelligence, Big Data, Data Analytics, Machine Learning, Inteligência Artificial, Data Quality, MDM, Governança de Dados e demais soluções de dados

## Descrição da vaga

Projeto Interno Leega para diversos clientes do segmento financeiro.

## Local
> Vaga Remota durante a pandemia.
Após presencial na [Avenida Paulista] [São Paulo] [Brasil]

## Requisitos

**Obrigatórios:**
- HTML / CSS (responsivo)
- Single Page Application (SPA)
- Angular 5, Vue.JS ou React
- Javascript
- GIT
- Consumo de APIs

**Desejáveis:**
- C#
- .Net Core
- TFS
- Linux
- Docker

## Contratação

PJ a combinar

## Como se candidatar

Por favor, envie um e-mail para reinihel.moreau@leega.com.br com seu CV anexado - enviar no assunto: VAGA FRONT. No corpo do e-mail, inserir sua pretensão salarial no valor hora e disponibilidade de inicio.
Se preferir, me chame aqui: https://bit.ly/3wrghCh

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dias após cada processo.
E-mail para contato em caso de não haver resposta: reinihel.moreau@leega.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
