### ISSUE TITLE
[100% remoto] FrontEnd Developer Níveis Pleno e Sênior (2 vagas) - HrSoul Consultoria

### ISSUE THREAD

**Issue by hrsoul1221** [frontendbr/vagas#5292]
## Nossa empresa

A HRSoul foi criada visando atender as necessidades do mercado de TI, Telecom e Engenharia, suprindo a carência de consultorias com expertise na área, assim como inovar os processos de Recursos Humanos para os demais segmentos. 

## Descrição da vaga

- Sólida experiência em desenvolvimento de sistemas FrontEnd;
- Imprescindível experiência com Flutter;
- Desejável disponibilidade para início imediato;
- Projeto com duração de 1 ano e 6 meses, com possibilidade de extensão;
- Atuação 100% remota.

## Local

Atuação 100% remota.

## Requisitos

**Obrigatórios:**
- Sólida experiência em desenvolvimento de sistemas FrontEnd;
- Imprescindível experiência com Flutter.

**Desejáveis:**
- Desejável disponibilidade para início imediato.

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para ftoledo@hrsoul.com.br com seu CV anexado - enviar no assunto: Vaga Front End.

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Níveis
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
