### ISSUE TITLE
[100% Remote] Front-end Developer (React) na Infleet

### ISSUE THREAD

**Issue by RodolfoSilva** [frontendbr/vagas#5296]
## Nossa empresa

A Infleet é o primeiro Hub integrador para gestão de frotas do Brasil com o foco em relacionar informações de diversos sistemas. Fornecemos visibilidade e assertividade na tomada de decisão do gestor de frota integrando qualquer fonte de dados envolvida no processo logístico. Com mais de 10 prêmios de inovação e de logística, somos uma logtech membro do Cubo Itaú com grandes clientes no mercado de coletas de resíduos, distribuição e transportes em geral. Nós nascemos na indústria através de renomados programas de aceleração na Renault, Inovativa, Vale do Dendê, Senai/Cimatec e Qintess, bem como editais de inovação como Fundeci do Banco do Nordeste, CREA-BA e Indústria 4.0 da ABDI. Potencializamos contribuições individuais com um time talentoso, diverso e aficionado por tecnologia de ponta. Vamos sempre além do possível e previsível através da colaboração, e o nosso objetivo é transformar o mercado de logística e gestão de frotas no mundo.

## Filosofia

*1% better every day.* Seja em relação ao software, processos ou até simples relações de trabalho, sempre podemos nos aprimorar. A melhoria contínua é um valor que utilizamos como norte nas nossas atividades do dia-a-dia e modelagem organizacional. Admiramos proatividade e agilidade, aprendemos rápido e ouvimos o nosso cliente. A Infleet é assim.

*De humano para humano (H2H).* Nós levamos realmente a sério a história de que absolutamente tudo é sobre pessoas. Vemos muitas siglas atualmente - B2B, B2C, B2B2C etc. - que se forem interpretadas de forma estritamente literal para definirmos nossa atuação, caímos numa armadilha perigosa. Com simplicidade nos processos, software de ponta e design centrado no ser humano buscamos resultados extraordinários e, para nós, só funciona de verdade se for H2H.

*Liberdade para ser e fazer*. Acreditamos que não existe inovação sem liberdade e nós temos a responsabilidade para errar rápido e aprendermos na velocidade da luz. No nosso dia-a-dia valorizamos a autonomia em busca de resultados para o time como um todo, e contamos com a diversidade ao nosso favor presente em nosso DNA.

## Descrição da vaga

Trabalhamos com ReactJS, Typescript e GraphQL em toda nossa stack do frontend. Naturalmente, proficiência nessas tecnologias é requerida. Além disso, capacidade analítica para identificar potenciais gargalos de performance, comportamentos inesperados e preocupação com escala é importante e esperado neste papel. Uma boa base de fundamentos de software é indispensável para lidar com questões típicas do dia-a-dia e da especificidade de problemas não tão comuns dado o domínio do software que nos encontramos. Acreditamos que estes são fatores técnicos importantes para construirmos uma interface que dê uma melhor experiência para os usuário e de fácil manutenção para os engenheiros.

## Local

100% Remoto

## Requisitos

**Obrigatórios:**

- Typescript
- HTML/CSS
- ReactJS
- TDD

**Desejáveis:**

- GraphQL
- Docker
- Noções de UI/UX

**Diferenciais:**

- Inglês
- Participação na comunidade
- Projetos OpenSource

## Benefícios

- Plano de saúde
- Auxílio alimentação
- Auxílio internet

## Contratação

CLT

## Como se candidatar

Por favor envie um email para rodolfo.silva@infleet.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Developer Pleno

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by RodolfoSilva** [comment]
@felipefialho finalizamos a contratação. Fecharei a issue, obrigado pelo lembrete! :D
