### ISSUE TITLE
[100% Remote] Front-end Developer Sênior (React.js / E-comm) na Enext Consulting

### ISSUE THREAD

**Issue by cedrykaugusto94** [frontendbr/vagas#5299]
## Nossa empresa

A Enext é uma consultoria e agência digital, premiada em 2016 e 2017 pelo GREAT PLACE TO WORK. Nós fazemos parte do grupo Wunderman Thompson, agência de comunicações de marketing global com sede em Nova York, mais de 200 escritórios em 90 países. Trabalhamos com vários clientes desafiadores, cujo alguns deles são: C6 Bank, Unilever, BASF, Suvinil, L’oreal, Sephora, Nespresso, The North Face e Bauducco.

Nosso time tem hoje aproximadamente 200 pessoas, focadas no nosso principal valor: TRANSFORMAR AS PESSOAS PARA O FUTURO. E é esse pensamento que nos torna referências nas melhores tecnologias do mercado de desenvolvimento de e-commerce e marketing digital, tendo como parceiros a Salesforce, Oracle, e Vtex.

Nosso time de tecnologia hoje, é um dos melhores do Brasil quanto a desenvolvimento WEB, tanto na stack front-end quanto na back-end. Além disso, somos parceiros de grandes empresas de cloud computing como AWS, Microsoft e Oracle. Usamos largamente os seus serviços e investimos no treinamento da equipe para atuar com elas.

## Descrição da vaga

Precisamos de um desenvolvedor Front-end Sênior que nos ajude a impulsionar o mercado digital brasileiro e mundial através do desenvolvimentos de e-commerces em plataformas VTEX ([O únicórnio brasileiro](https://olhardigital.com.br/2020/09/29/pro/startup-de-e-commerce-vtex-e-o-mais-novo-unicornio-brasileiro/?gfetch=2020%2F09%2F29%2Fpro%2Fstartup-de-e-commerce-vtex-e-o-mais-novo-unicornio-brasileiro%2F)) e Oracle Commerce Cloud.

Para esse nível, experamos que você possua experiência e se sinta confortável com as linguagens de programação que utiliza, com as ferramentas de trabalho, ambiente de desenvolvimento, Sistema Operacional, etc. Que você tenha uma boa noção de prazos e consiga estimar isso muito bem. Você também deverá ser capaz de coordenar projetos, organizar um time, delegar tarefas, avaliar as tarefas concluídas por outros membros e responder precisamente à dúvidas de clientes, GPs, Scrum Masters e etc.

Esperamos que você seja capaz de formar outros profissionais, direcioná-los e ajudá-los a cumprir suas metas. E o mais importante: curtir o processo, afinal de contas nossa missão é **transformar pessoas para o futuro**.

Ser Sênior para nós não está ligado somente ao tempo que você trabalha, mas ao seu conhecimento adquirido nesse tempo e às suas atitudes como profissional.

## Modelo de contratação
* Alocação 100% remota
* PJ salário à combinar

## Benefícios
* Férias remuneradas
* Convênico médico
* Acesso à plataforma de e-learning corporativo com cursos de todas as áreas da empresa
* Investimento em certificações feito pela empresa

## Requisitos

**Obrigatórios:**
- Conhecimento avançado JavaScript, HTML e CSS
- Dominido da ferramenta de Controle de versão - Git
- Dominiode de consumo de APIs
- Boas práticas: reutilização de código
- Escalabilidade
- Manutenibilidade
- Padrões de Projetos aplicado ao Javascript (GoF) e ao CSS (básico do, pelo menos)
- Experiência com  Framework JS/CSS ReactJS
- Pré processadores CSS (SASS/LESS)
- Sabe criar testes unitários
- Sabe a importância dos Linters (JS, CSS, Commits, etc.) e segue à risca suas regras
- Entende alguns paradigmas de programação (Ex.: OOP e/ou Funcional)
- Atende aos múltiplos navegadores e suas diferenças (Cross Browser)
- Criar um ambiente de desenvolvimento ou um Boilerplate para iniciar seus projetos facilmente
- Pensa em performance (tanto do Javascript, quanto do CSS)
- Entende os conceitos de SEO (estruturação do HTML, nós semânticos, resolver a lista do PageSpeed, Schema.org)
- Conhece os conceitos de Acessibilidade e Usabilidade (E manipular ferramentas de UI)

**Diferencial:**
- Ter experiência com a plataforma de e-comm VTEX

## Como se candidatar

Vaga disponível no link:

*Senior:*  <https://enext.solides.jobs/vacancies/42024#vacancyDescription>

Ou pode enviar um email para cedryk.augusto@enext.com.br

## Labels

- PJ
- Sênior
- Remoto

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by cedrykaugusto94** [comment]
Vaga ainda aberta

**Comment by cedrykaugusto94** [comment]
Vaga ainda aberta!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
