### ISSUE TITLE
[São Paulo] Desenvolvedor Front-End - Pl / Sr

### ISSUE THREAD

**Issue by mpivaa** [frontendbr/vagas#53]
## Descrição da vaga

Estamos contratando desenvolvedor front-end pleno com experiência ou vontade de trabalhar com React / Redux.

Procuramos alguém com paixão por desenvolvimento e trabalhar com o que há de melhor.

## Local

Pinheiros - São Paulo ou Guarulhos

## Benefícios

- Horários flexíveis e home office
- Ambiente aberto e em constante evolução
- Time de alto nível
- Valorizamos o desempenho e comprometimento da equipe

## Requisitos

- Experiência com desenvolvimento Javascript.
- React / Redux
- TDD
- CSS / PostCSS
- Ser comprometido com o projeto e qualidade do código.

**Desejáveis:**

- UX / UI
- Functional & Reactive Programming
- Experiência com times auto-gerenciáveis e metodologias ágeis(XP, SCRUM, Kanban, Lean).

**Diferenciais:**
- Participar da comunidade open source

## Nossa empresa

A EcoStage é líder no desenvolvimento de plataformas sócio-ambientais. Nossos projetos são inovadores e desafiadores.

Somos uma empresa com ambiente descontraído e horários flexíveis. Você trabalhará em uma equipe pequena, multi-disciplinar e auto-gerenciável. Buscamos pessoas que nos ajudem a continuar evoluindo.

[EcoStage](http://www.ecostage.com.br)

## Como se candidatar

Acha que se encaixa na nossa vaga? Envie um email para jobs@ecostage.com.br com cv / linkedin / github e o escritório com disponibilidade.

**Comment by LFeh** [comment]
Boa sorte ;)

**Comment by Mendrone** [comment]
@mpivaa a vaga foi preenchida?

**Comment by mpivaa** [comment]
@Mendrone a vaga continua aberta

**Comment by LFeh** [comment]
Agora foi? \o

**Comment by mpivaa** [comment]
Esse foi, mas já abri outra!

**Comment by camilatigre** [comment]
@mpivaa 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by mpivaa** [comment]
a)

**Comment by camilatigre** [comment]
Aee! Que legal. Obrigada por responder e ajudar.

Em 24 de nov de 2016 10:39, "Marcelo Piva" <notifications@github.com>
escreveu:
