### ISSUE TITLE
[São Paulo] Front-End Developer na Looqbox (Pleno/Sênior)

### ISSUE THREAD

**Issue by rodrigomurta** [frontendbr/vagas#530]
Descrição da vaga
--
Procuramos um profissional com pelo menos 1 ano de experiência com AngularJS e conhecimentos avançados de JavaScript.

Local: [CUBO](https://cubo.network/) - [Rua Casa do Ator, São Paulo - SP](https://goo.gl/maps/BcLfmmemGF42)

Obrigatórios
--
1 ano de experiência com AngularJS pelo menos!
2 anos de experiência com programação JavaScript.
Conhecimentos avançados em HTML,  CSS e JavaScript

Desejáveis:
--
ter trabalhado em alguma startup
alguma experiência com aplicativos mobile

Contratação
--
CLT ou PJ

Nossa empresa
--
![Looqbox](https://demo.looqbox.com/webclient/icon/delph_web@2x.png)
O Looqbox torna a busca de dados na empresa uma atividade extremamente simples, dispensando longos treinamentos e agilizando a tomada de decisões. Sua interface, extremamente clean, permite que os usuários utilizem Linguagem Natural para interagir com os dados da empresa. Como uma ferramenta de Insight Engine, o Looqbox vai além das respostas de um BI tradicional e pode dar como resposta qualquer informação da empresa, seja ela uma tabela, um gráfico, um arquivo ou uma apresentação. 
Hoje já trabalhamos com grandes contas, e procuramos por profissionais que estejam animados para transformar conosco o mercado de BI no Brasil e no Mundo.

Site: [www.looqbox.com](http://www.looqbox.com)
Instagram: [@looqbox](https://www.instagram.com/looqbox/)

Como se candidatar
--

Por favor envie um email para code@looqbox.com com seu CV anexado - enviar no assunto: Vaga AngularJS / JavaScript

Muito obrigado!

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
