### ISSUE TITLE
Brasil Front-end Developer SR - Topaz 

### ISSUE THREAD

**Issue by Re-Honorio** [frontendbr/vagas#5301]
==================================================
-->

> Vaga Remota durante a pandemia

## Topaz

Somos uma multinacional focada em soluções bancárias e atuamos com desenvolvimento de produtos.

Enxergamos na tecnologia a chave para mantermos a inovação, otimização, performance e qualidade em tudo que executamos.

Nossos times utilizam diversas tecnologias em todas as areas de engenharia de software, desde a concepção, design, desenvolvimento e testes dos produtos que construímos garantindo a melhor performance e aderência aos diversos mercados em que atuamos.

Consideramos que além dos skilss técnicos, nossos colaboradores busquem sempre a visão de solução de problemas, entendimento do impacto social aplicado as nossas soluções e a busca constante por excelência.
Somos hoje os melhores no que fazemos e buscamos pessoas que busquem excelência em suas carreiras.

## Descrição da vaga

Participar do time de desenvolvimento de software, visando prover soluções com alta qualidade e confiabilidade, interagindo com equipes multifuncionais profissionais de todas as áreas de conhecimento

 - Experiência em uma das Linguagens de Programação (HTML, CSS, JavaScript, TypeScript, Java Android, Swift)

 - Conhecimentos em algum dos frameworks híbridos (Angular, React Native, React Web, Ionic Cordova, Flutter, JQuery)

 - Conhecimentos em Metodologias Ágeis (preferencial SCRUM)

- Experiência em Lógica de Programação

- Conhecimentos em técnicas BDD/TDD - Conhecimentos em ferramentas de teste unitário - Conhecimento de Mobile

- Experiência em frameworks híbridos

 - Conhecimentos em publicação nas lojas Apple / Android

-> Ferramentas: - Jenkins - Jasmine - Mocha - Appium - Firebase - TestFlight

## Local

Atuação Remota. 

## Benefícios

- Plano de saúde
- Seguro de vida
- VR
- Auxílio creche
- Subsídio Espanhol (100% pago pela empresa)

## Contratação

Modalidade CLT Full ou Flex

## Como se candidatar

Por favor envie um email para rhonorio@topaz.com.uy com seu CV anexado - enviar no assunto: Vaga Front-End SR

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
