### ISSUE TITLE
[Florianópolis/SC] Front-end Developer na Dynamox

### ISSUE THREAD

**Issue by marketing-dynamox** [frontendbr/vagas#5302]
## Dynamox

Empresa de alta tecnologia que desenvolve sistemas de monitoramento e aquisição de dados de vibração e temperatura. Somos empresa certificada ISO 9001 e GPTW!

Especialista em análise de vibrações e monitoramento da condição de ativos industriais. Solução ideal para a manutenção preditiva. Todas as soluções são desenvolvidas na própria empresa, desde o hardware até a aplicação web. Nossa equipe de P&D conta com desenvolvedores de hardware, firmware, mobile (android e ios) e web (backend e frontend), além de engenheiros especializados na área de processamento de sinais para vibração e acústica.

## Descrição da vaga

Estamos contratando - Desenvolvedor Front End - para empresa de alta tecnologia que desenvolve sistemas de monitoramento e aquisição de dados de vibração e temperatura.

**Suas atividades principais serão:**

- Desenvolver páginas web multiplataforma (computador e mobile);
- Adequar e melhorar site institucional atual;
- Realizar a manutenção do site;
- Pesquisar novas tecnologias para propor melhorias no processo de desenvolvimento do site;
- Realizar integração de API de ferramentas de analytics;
- Criar ferramentas e elementos que melhorem a interação com o site em qualquer dispositivo ou navegador para melhorar a usabilidade do utilizador;
- Aplicar técnicas de SEO;
- Seguir as WEB standards, ou seja, as normas para uma web universal;
- Desenvolver códigos limpos e bem documentados;
- Contribuir com o cumprimento das políticas de segurança da informação.

## Local

Escritório, [SANTA CATARINA ], [FLORIANÓPOLIS], [JOÃO PAULO]

## Requisitos

**Obrigatórios:**

- Conhecimento avançado em desenvolvimento Front-End para produção de sites;
- Conhecimento avançado em Linguagens de Programação (JavaScript, CSS, HTML);
- Conhecimento avançado em Bibliotecas e frameworks React (Gatsby);
- Conhecimento avançado em técnicas de SEO;
- Conhecimento intermediário em servidores (Netlify, Wordpress e Git);
- Conhecimento de ferramentas de gestão Ágil (Trello/ Jira);
- Ser Pró Ativo, autodidata e auto gerenciável;
- Ter atenção aos detalhes e elementos visuais;
- Ser analítico e detalhista;
- Desejável Técnico ou Superior Completo em Análise e Desenvolvimento de Sistema, Sistemas de Informação ou correspondentes;
- Experiência com desenvolvimento de site para projetos publicitários.

**Diferenciais:**

- Conhecimento Básico em linguagens de programação Back-End (Python, Java);
- Conhecimento em Bibliotecas e frameworks React NextJS
- Conhecimento básico banco de dados (SQL, NoSQL);
- Conhecimento em desenvolvimento de E-commerce.

## Benefícios

- Plano de saúde
- VR/VA/Vale transporte ou combustível em formato flexível

**Diferenciais:**
- App GoGood
- Atendimento individual in company com fisioterapeuta, osteopata com formação no método McKenzie.

## Contratação

CLT

## Como se candidatar

Inscreva-se pelo Enlizt, no link https://dynamox.enlizt.me/vagas/desenvolvedor_front_end-060721

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após cada processo.
Contatos diretamente pela plataforma Enlizt.

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
