### ISSUE TITLE
[100% REMOTE] Front-end Developer Senior @ nalu.fyi

### ISSUE THREAD

**Issue by mcarrica** [frontendbr/vagas#5303]
## Nossa empresa

Check us out: https://nalu.fyi

Creating and finding documentation is a huge issue! Confluence is terrible, GDocs are hard to organize and Notion/ Almanac/Coda is hard to implement from scratch.
Nalu is the best GDocs experience ever made, drawing learnings from Notion and Coda into GDocs.

The MVP of Nalu is live and, against all odds, there are DAUs spending 10+ hours in Nalu.
We are now heading to build Nalu 1.0 from scratch.

## Descrição da vaga

FrontEnd Senior. You will lead the re-factor of all the app, including selecting technologies and planning architecture along with us.
Currently the product is packaged as an electron app that runs chromium and we use Javascript for the Nalu properties.

## Requisitos

**Obrigatórios:**
- Ability to demonstrate seniority as an engineer (best are projects you built on the side!)
- Passion for productivity tools
- Eagerness to work in products that have the potential to be massive

**Diferenciais:**
- We speak Spanish, Portuguese and English. Although perfect English is not a must, some English is needed.

## Benefícios

- Compensation well above Brazil market, paid in US or Brazil (your choice)
- If you like the project and the team, we are looking for a late founder/ early employee to grow with us with Front-End tech

**Diferenciais:**
- 1 billion people use GDocs. The market opportunity is massive. Work on something with impact
- work from whereever makes you happier
- balanced lifestyle

## Contratação

PJ a combinar

## Como se candidatar

Please send an email to martin@nalu.fyi. Include a 2-3 min loom video (loom.com) :
- Short introduction of yourself
- What projects you've done that excite you most (show us!)
- What you think Nalu can do to be more awesome (there is a lot here!)

## Tempo médio de feedbacks

We usually answer in less than 24hs, unless it is a weekend (maybe even then...)

#### Alocação

- Remoto

#### Regime

- Freela
- PJ

#### Nível

- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
