### ISSUE TITLE
[São Paulo] Front-end Developer Níveis Pleno e Sênior (2 vagas) - Atuação 100% remota

### ISSUE THREAD

**Issue by hrsoul1221** [frontendbr/vagas#5305]
`[São Paulo] Front-End Developer Níveis Pleno e Sênior (2 vagas) - Atuação 100% remota`

> Vaga Remota 100% remota

## Descrição da vaga

Sólida experiência em desenvolvimento de sistemas FrontEnd;
Imprescindível experiência com React;
Desejável disponibilidade para início imediato;
Projeto por período indeterminado;
Atuação 100% remota.

## Local

Remoto [SP]

## Requisitos

**Obrigatórios:**
- Experiência com React
- Sólida experiência em desenvolvimento de sistemas FrontEnd

**Desejáveis:**
- Disponibilidade para início imediato

## Contratação

PJ 

## Como se candidatar

Enviar e-mail para ftoledo@hrsoul.com.br ou cadastre seu CV em nosso Site -  https://oportunidades.hrsoul.com.br/

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
