### ISSUE TITLE
[Remoto] Front-end Developer Pleno na SMU

### ISSUE THREAD

**Issue by fabio-smu** [frontendbr/vagas#5309]
## Nossa empresa

[A SMU é a maior empresa de Crowdfunding de Investimentos do Brasil.](https://smu.com.vc/)

Para os investidores, somos a porta de acesso para a diversificação dos investimentos na economia real e no mundo de inovações.

Para os empreendedores, oferecemos o acesso ao smart money dado pela interconexão de empresas, fundos, investidores profissionais e investidores-clientes engajados.

## Descrição da vaga

Desenvolvimento e manutenção da plataforma de investimentos e da dashboard administrativa.
Ambos os projetos utilizam VueJS, Typescript e Bootstrap.

## Local

Exemplo: Remoto ou Escritório em São Paulo.

## Requisitos Técnicos
- Fluência em Javascript Nativo (incluindo features ES6)
- Experiência em algum framework javascript (Angular, Vue ou React)
- Experiência na construção de layouts responsivos
- Experiência com alguma biblioteca de UI (Bootstrap, Bulma ou Tailwind)
- Experiência com Sass
- Experiência em consumir APIs REST
- Git e Github (ou similares como Gitlab)
- NPM ou Yarn

## Personalidade
- Autodidata: capaz de seguir documentações.
- Pró-ativo: capaz de sugerir melhorias.
- Organizado: que ache imprescindível a documentação de suas tarefas.

## Diferenciais
- Experiência com VueJS e NuxtJS
- Experiência com Typescript
- Experiência com NodeJS
- Experiência com alguma ferramenta de CI/CD

## Benefícios

- Plano de saúde
- VR
- VT caso necessário.

**Diferenciais:**
- Horário de trabalho flexível.

## Contratação

CLT com remuneração de R$ 3000 à R$ 5000 dependendo do nível do candidato.

## Como se candidatar

Por favor envie um email para saulo.triani@startmeup.com.br  com seu CV anexado - enviar no assunto: Vaga Front-end Developer [Pleno]

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by messiasdias** [comment]
🤩

**Comment by danielbonifacio** [comment]
Somente para deixar claro, ontem esta vaga foi postada no Facebook.

O autor do post, ao ser questionado sobre salário, lançou essa pala aí do print.

Após perceber a merda, apagou o post.

Fiz questão de vir aqui para deixar os candidatos cientes do perfil do seu possível novo "chefe".

Abs

![Screenshot_2021-07-15-08-18-38-960_com facebook katana](https://user-images.githubusercontent.com/19931838/125781737-ffe86bfd-be5b-4dc1-8095-2a9d2b870bcc.jpg)

**Comment by fabio-smu** [comment]
Obrigado a todos que enviaram currículo pessoal! Abs
