### ISSUE TITLE
[Porto Alegre - RS] Front-end developer no Dietbox

### ISSUE THREAD

**Issue by educosta** [frontendbr/vagas#531]
Buscamos um(a) desenvolvedor(a) Front-end capaz de construir interfaces para nosso software de nutrição, que curta aprender e codar (em JavaScript, CSS e HTML) e que goste de pensar no produto além do código.
 
A pessoa será responsável por pensar, contribuir no planejamento e desenvolver novas funcionalidades no Dietbox para plataforma Web, trabalhar junto com nosso time na arquitetura e definição de soluções e utilizar as melhores práticas e tecnologias para escrever código.
 
Requisitos
 
Paixão em escrever código.
Vivência com desenvolvimento de aplicações Web de grande volume.
Domínio de conceitos e arquiteturas de desenvolvimento de software como OPP, DDD e etc.
Habilidade de desenvolver aplicações do seu início ao fim.
Se sentir confortável com arquiteturas de desenvolvimento, tais como, MVVM, MVC.
Vivência com desenvolvimento em ambientes e times ágeis.
Disponibilidade para trabalho em tempo integral.
 
Diferenciais
 
Conhecimento em frameworks e bibliotecas como Knockout, Vue, Angular e Bootstrap.
Alguma experiência com tecnologias Microsoft e linguagem C#
Vivência com mais de uma linguagem de programação.
Experiência em escrever testes unitários e funcionais.
Paixão por aprender e empreender.
 
Local
 
Porto Alegre, RS
 
Como se candidatar
Se você se interessou, manda seu currículo, LinkedIn e/ou GitHub para contato@dietbox.me

**Comment by LFeh** [comment]
PJ ou CLT?

**Comment by educosta** [comment]
As duas opções

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by educosta** [comment]
Vaga em aberto novamente pessoal
