### ISSUE TITLE
[Remoto] Desenvolvedor(a) Fullstack JavaScript Pleno III (Remoto) na GoBacklog

### ISSUE THREAD

**Issue by glaydston** [frontendbr/vagas#5312]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedora-fullstack-javascript-pleno-iii-remoto-194802442?origin=github&modal=open) com o pop-up personalizado de candidatura. 👋
<h2>Sobre a GoBacklog</h2>
<p>A GoBacklog é uma empresa jovem, ágil, dinâmica e divertida, que idealiza e desenvolve produtos e soluções digitais para todos os segmentos do mercado (finance &amp; trading, health &amp; care, e-sports, energy, loyalty, music, education, etc...). Somos movidos por inovação e geralmente contratados para transformar negócios através da tecnologia.</p>
<p>Nosso processo de design e desenvolvimento é muito focado no negócio e na geração de valor para o cliente, e não no sistema ou aplicação em si, pois enxergamos a tecnologia como meio, e não fim. A jornada se inicia na etapa de Product Discovery, com uma profunda pesquisa do cliente, do seu mercado e das personas, passando então pela etapa de Prototype, para só então escrevermos os códigos (Product).</p>
<p>Assim, conseguimos criar produtos e soluções inovadoras e sustentáveis, com a melhor qualidade e usabilidade possíveis, e que realmente transformem negócios, mercados e, principalmente, a vida das pessoas para melhor. Se você também gosta de construir coisas legais e inovadoras, vem com a gente transformar o mundo! ;)</p>
<h2>Atividades principais</h2>
<ul>
<li>Criar produtos digitais do zero a partir de protótipos de alta fidelidade</li>
<li>Melhoria e sustentação de sistemas existentes</li>
<li>Analisar o escopo, definir estratégia, dimensionar o projeto e estimar o tempo de desenvolvimento necessário para implementá-lo.</li>
<li>Implementar integrações entre sistemas</li>
<li>Identificar e resolver bugs e problemas de performance e escalabilidade cedo, evitando gargalos e promovendo a qualidade do produto</li>
<li>Criar e manter documentação técnica do produto</li>
</ul>
<h2>Requisitos técnicos</h2>
<h4><strong>Front-end</strong></h4>
<ul>
<li>Experiência na construção de soluções digitais em produção com JavaScript há pelo menos 3 anos</li>
<li>Experiência na implementação de frontend com React</li>
<li>Conhecimentos profundos em HTML5 e CSS3</li>
</ul>
<h4><strong>Back-end</strong></h4>
<ul>
<li>Experiência em Node.js, inclusive na construção de APIs</li>
<li>Experiência no uso de Arquitetura REST</li>
<li>Experiência com bancos de dados NoSQL e SQL</li>
</ul>
<h3><strong>Mobile</strong></h3>
<ul>
<li>Experiência na construção de aplicativos em React Native</li>
</ul>
<h4><strong>DevOps</strong></h4>
<ul>
<li>Docker e Docker Compose</li>
<li>Conhecimentos em CI/CD (actions, ou pipelines)</li>
<li>Git&nbsp;</li>
</ul>
<h2>Requisitos comportamentais</h2>
<ul>
<li>Responsabilidade e pontualidade</li>
<li>Organização e autogestão</li>
<li>Boa comunicação e proatividade</li>
<li>Vontade de aprender e senso de resolução</li>
<li>Ética e transparência</li>
</ul>

## GoBacklog: 
 <p>A GoBacklog é uma empresa jovem, ágil, dinâmica e divertida, que idealiza e desenvolve produtos e soluções digitais para todos os segmentos do mercado (finance &amp; trading, health &amp; care, e-sports, energy, loyalty, music, education, etc...). Somos movidos por inovação e geralmente contratados para transformar negócios através da tecnologia.</p>
<p>Nosso processo de design e desenvolvimento é muito focado no negócio e na geração de valor para o cliente, e não no sistema ou aplicação em si, pois enxergamos a tecnologia como meio, e não fim. A jornada se inicia na etapa de Product Discovery, com uma profunda pesquisa do cliente, do seu mercado e das personas, passando então pela etapa de Prototype, para só então escrevermos os códigos (Product).</p><a href='https://coodesh.com/empresas/gobacklog'>Veja mais no site</a>

 ## Habilidades: 
 - HTML 5 
- Javascript 
- React.js 
- React Native 
- SQL 
- Docker 
- GIT 
- CSS 3 
- Node.js 
- NoSQL
## Local: 
 100% Remoto
## Requisitos: 
 - Disponibilidade de responder dúvidas pontuais da equipe em horário comercial (manter a comunicação em um ambiente 100% remoto é importante) 
- Possuir experiência profissional plena com desenvolvimento de softwares em produção de pelo menos 3 anos 
- Experiência com a utilização de microsserviços
**Diferenciais:** 
 - Testes no front-end 
- Material UI 
- MySQL 
- GraphQL 
- Digital Ocean
## Benefícios: 
 - Férias remuneradas 
- Day off no aniversário 
- Horário flexível 
- 100% remoto
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Desenvolvedor(a) Fullstack JavaScript Pleno III (Remoto) na GoBacklog](https://coodesh.com/vagas/desenvolvedora-fullstack-javascript-pleno-iii-remoto-194802442?origin=github&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção <b>Pedir Feedback</b> entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa <b>Recruiter</b> responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
