### ISSUE TITLE
[REMOTO] Front-end React na Nave.rs

### ISSUE THREAD

**Issue by BrunaSouzaPaes** [frontendbr/vagas#5313]
> Vaga Remota durante a pandemia ou após a pandemia

## Nave.rs

O time da Nave é experiente e atua como uma consultoria em todos os momentos do desenvolvimento das soluções. Somos especialistas na construção de produtos digitais utilizando o que há de mais inovador no mercado de aplicativos e sistemas.

## Descrição da vaga

Pensou em trabalhar em um ambiente colaborativo, dinâmico, com muito aprendizado e autonomia? Neste momento estamos buscando uma pessoa com experiência e conhecimento para área de Front-End React.

## Responsabilidades e Atribuições
- Capacidade de adquirir e repassar conhecimento através dos colegas;
- Capacidade em aprender através da revisão do trabalho do grupo;
- Executar tarefas bem definidas e estruturadas pelo grupo;
- Foco em aprender sobre princípios da área em que trabalha, ferramentas, melhores práticas, buscando o domínio com a visão de ser mais autossuficiente;

## Local

100% Remoto

## Requisitos

**Obrigatórios:**
- HTML;
- CSS;
- Javascript;
- Experiência no desenvolvimento de aplicações web utilizando React;

## Benefícios

- Plano de saúde (Cooperação com o plano de saúde da Unimed, 60% a empresa paga, 40% o emprego paga)
- Plano de carreira estruturado
- VR / VA de R$ 23/dia
- Acesso ao Alura Cursos e Línguas
- Auxilio Psicológico na plataforma Vittude 

**Diferenciais:**
- Vaga 100% Remota
- Plano de Carreira estruturado
- Hierarquia Horizontal
-  2h de estudo por semana 

## Contratação

CLT ( faixa salarial de R$1.833,48 até R$3.168,25 + benefícios) 

## Como se candidatar

inscreva-se atraves do link: [link aqui](https://nave-team.gupy.io/jobs/1043957)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 6 dias após cada processo.

## Labels
 
CLT
REMOTO
JUNIOR
PLENO

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by hmassareli** [comment]
Já acabou o processo seletivo

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
