### ISSUE TITLE
[Remota] Front-end Developer na Siteware

### ISSUE THREAD

**Issue by yslland** [frontendbr/vagas#5315]
Vaga remota

A equipe Siteware está crescendo e estamos à procura de uma pessoa para compor o nosso time como Front-End Developer! Aqui você irá contribuir com o desenvolvimento de interfaces e criação de componentes dinâmicos para um produto distribuído em mais de 20 países.

No dia a dia você irá:
Garantir a construção do software Stratws One com qualidade e dentro de parâmetros pré estabelecidos para cada produto. 
Criar e manter testes automatizados, visando a qualidade do produto. 
Atuar na correção de bugs de média e alta complexidade do sistema.
Desenvolver as telas para serem responsivas
Participar de reuniões mensais de Contexto de Novos Objetivos e Alinhamento de Road Map.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Conhecimento Avançado em Angular e/ou React;
- Domínio em CSS3 e Pré-Processadores de CSS (SASS, LESS, etc...);
- Domínio nas linguagens: HTML5, Typescript e Javascript;

**Desejáveis:**
- Conhecimento em Padrões de Projetos (Design Patterns);
- Conhecimento em integração e entrega contínua de forma automatizada.

**Diferenciais:**
- Conhecimento em Test Driven Development (TDD) e Domain Driven Development (DDD).

## Benefícios

- Vale Alimentação e Vale refeição: integrados em um único cartão, no valor de R$ 37,00 por dia útil.
- Plano de Saúde Bradesco Top Nacional: cobertura nacional e acomodação quarto, sem coparticipação e 100% custeado pela empresa. Desconto para dependente é negociado através da faixa etária.
- Plano odontológico SulAmerica.
- Curso de inglês Aliança América: 100% custeado pela empresa, sem nenhum tipo de desconto.
- Décimo quarto salário. Caso a empresa atinja as metas definidas, o colaborador recebe o valor correspondente aos critérios do programa.
- Somos uma empresa cidadã: licenças maternidade e paternidade estendidas: o benefício de licença maternidade que é de 4 meses se estende para 6 meses e a paternidade de 5 dias estende para 20 dias.
- PLR Anual: valor definido anualmente pelo sindicato da classe.
- Meditação corporativa: meditação diária é essencial para estar em dia com a nossa saúde mental.
- Programa de Indicação Interna: caso o indicado venha a ser contratado e seja efetivado após o contrato de experiência, a Siteware bonifica o colaborador em um valor significativo.
- Flexibilidade no horário de trabalho.
- Seguro de vida em grupo no valor de R$ 50.000.
- Treinamentos, capacitações e parcerias: somos conveniados da Assespro e Fumsot. Isso nos dá condições especiais na Escola de Engenharia de Minas Gerais (EMGE), oferecendo 60% de desconto na mensalidade de graduação e pós graduação.

## Diferenciais:

Vaga 100% remota.
Plano de carreira estruturado.

## Contratação

CLT pretensão a negociar.

## Como se candidatar

Por favor envie um email para talentossw@siteware.com.br com seu CV anexado - enviar no assunto: Vaga Front end  ou em https://bityli.com/frontendsw

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: talentossw@siteware.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
