### ISSUE TITLE
[Palhoça-SC] Front-end Developer Angular na Peopleplan

### ISSUE THREAD

**Issue by SauloGandolfi** [frontendbr/vagas#5322]
[Palhoça-SC] Front-End Developer Angular na Peopleplan

> VAGA PRESENCIAL

## Peopleplan

Consultoria em gestão de pessoas.

## Descrição da vaga

Participar das cerimônias junto ao time de desenvolvimento;

Desenvolvimento e manutenção de aplicações web em Angular;

Analisar, codificar, testar, preparar documentação além de acompanhar homologações;

Trabalhar ativamente com revisão de código; Identificar e resolver eventuais gargalos de desempenho e segurança;

Respeitar os prazos determinados para entrega das tarefas e/ou projetos;

Realizar as entregas com qualidade, testando seu software a nível de código, principalmente de regras de negócio.

## Local

Escritório em Palhoça/SC – Bairro Pedra Branca

## Requisitos

Ter capacidade analítica para interpretar e/ou sugerir possíveis soluções;

Conhecimento em metodologias ágeis (Scrum, Kanban);

Possuir conhecimento na ferramenta de controle de versões GIT;

**Desejáveis:**
Experiência em desenvolvimento Back-end em linguagem Java;

Conhecimentos no uso de APls REST;

Conhecimento em SQL.

## Contratação

PJ ou CLT

## Como se candidatar

Link para candidatar-se: https://jobs.recrutei.com.br/PeoplePlan/vacancy/10400-desenvolvedor-front-end-angular 
#### Regime
- CLT
- PJ
### Salário
R$ 8.000,00
#### Nível
- Júnior
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
