### ISSUE TITLE
[Remoto] Front-end Developer na Vista Sofware

### ISSUE THREAD

**Issue by tainacusinato** [frontendbr/vagas#5324]
> Vaga Remota 

## Nossa empresa
Prazer, somos a Vista Software!

Nosso propósito é facilitar a vida das pessoas no mercado imobiliário com atuação nacional, atendendo +2.000 clientes, +100 empresas parceiras. Uma plataforma de gestão para imobiliárias. Aqui você trabalhará de forma ágil e flexível e terá a oportunidade de se desenvolver e crescer junto com a empresa.

## Descrição da vaga
-Desenvolver novas telas no sistema em conjunto com nosso Designer UX
-Refatorar interfaces e aplicar nossa identidade visual em locais do sistema que ainda não tem

-Manter e otimizar a estrutura de front-end do sistema
– Propor novas soluções e tecnologias

## Local

 Remoto 

## Requisitos
Requisitos:
Experiência e conhecimento de HTML, CSS e JS
Bom conhecimento de ferramentas como SASS, NPM, bibliotecas Jquery e Bootstrap

## Benefícios
• Cartão Flash (você escolhe como quer usar o crédito, que pode ser em mercado, restaurantes, uber ou até mesmo de bicicleta!);
• Plano de saúde e odontológico Sulamérica (aceito no Brasil sem co-participação) ;
• Plano de participação nos resultados (mediante a meta anual, pagamento semestral);
• PDV – Auxilio em cursos e eventos para o seu desenvolvimento pessoal e profissional;

**Diferenciais:**
• Ambiente de trabalho descontraído com oportunidade de aprendizagem, buscamos constante inovação, rodeados de uma equipe unida, sempre dispostos a atender e encantar nossos clientes;
• Somos transparentes em nossas decisões e atitudes, prezamos a nossa cultura de Feedback e 1 on 1.

## Contratação
CLT

## Como se candidatar

Por favor envie um email para taina@vistasoft.com.br com seu CV anexado - enviar no assunto: Front

- Remoto

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
