### ISSUE TITLE
[Remoto] Pessoa SRE - Site Reliability Engineer na Siteware

### ISSUE THREAD

**Issue by yslland** [frontendbr/vagas#5325]
A Siteware está crescendo e estamos em busca de talentos para compor o nosso time de Produto. Aqui você vai trabalhar com uma equipe extremamente qualificada, engajada e ágil. Além do mais, terá contato com equipes interdisciplinares em um ambiente altamente colaborativo.
 
Quem somos?
 
Um time de Produto multidisciplinar que valoriza a qualidade das entregas através do aprendizado contínuo e de aplicação de práticas que diminuem o ciclo de feedback (TDD, Pareamento, Integração contínua). Valorizamos as pessoas tendo sempre foco em construir e manter um ambiente seguro para que todos tenham liberdade e oportunidade para se desenvolver.

## Descrição da vaga

Quem procuramos?

Alguém que para analisar e desenvolver soluções técnicas para atender aos requisitos da infraestrutura
Garantir a construção  e manutenção da infraestrutura com qualidade e dentro de parâmetros pré estabelecidos para cenários diversos. 
Participar do planejamento do esforço da equipe para a execução de cada tarefa referente à impactos na infraestrutura, comprometendo-se com o resultado final e com as entregas no prazo determinado com o cliente. 
Criar e manter testes automatizados, visando garantir a eficiência da infraestrutura.
Manter e administrar ambientes nas plataformas cloud, garantindo a disponibilidade e o bom desempenho nesses ambientes.
Atuar junto ao time na estimativa de recursos necessários para o desenvolvimento de melhorias acordadas com os Clientes.

## Local

Remoto 

## Requisitos

Ensino Superior em Tecnologia da Informação ou áreas afins.
Experiência em projetar arquiteturas de software.
Experiência com desenvolvimento de produto.
Domínio em Infraestrutura como Código (Ansible, CloudFormation, Chef, Puppet, Terraform)
Domínio em Metodologias ágeis.
Domínio em ferramentas como: Azure Devops e Cloud, Amazon Cloud, Docker, Kubernetes, Linux,
Domínio em SQL Server.

## Benefícios

- Vale Alimentação e Vale refeição: integrados em um único cartão, no valor de R$ 37,00 por dia útil.
- Plano de Saúde Bradesco Top Nacional: cobertura nacional e acomodação quarto, sem coparticipação e 100% custeado pela empresa. Desconto para dependente é negociado através da faixa etária.
- Plano odontológico SulAmerica.
- Curso de inglês Aliança América: 100% custeado pela empresa, sem nenhum tipo de desconto.
- Décimo quarto salário. Caso a empresa atinja as metas definidas, o colaborador recebe o valor correspondente aos critérios do programa.
- Somos uma empresa cidadã: licenças maternidade e paternidade estendidas: o benefício de licença maternidade que é de 4 meses se estende para 6 meses e a paternidade de 5 dias estende para 20 dias.
- PLR Anual: valor definido anualmente pelo sindicato da classe.
- Meditação corporativa: meditação diária é essencial para estar em dia com a nossa saúde mental.
- Programa de Indicação Interna: caso o indicado venha a ser contratado e seja efetivado após o contrato de experiência, a Siteware bonifica o colaborador em um valor significativo.
- Flexibilidade no horário de trabalho.
- Seguro de vida em grupo no valor de R$ 50.000.
- Treinamentos, capacitações e parcerias: somos conveniados da Assespro e Fumsot. Isso nos dá condições especiais na Escola de Engenharia de Minas Gerais (EMGE), oferecendo 60% de desconto na mensalidade de graduação e pós graduação.
- No dress code: vista-se e você!

**Diferenciais:**

Horário flexível
Plano de carreira
Vaga 100% remota

## Contratação

CLT pretensão a negociar.

## Como se candidatar

Por favor envie um email para talentossw@siteware.com.br com seu CV anexado - enviar no assunto: Vaga SRE

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: talentossw@siteware.com.br

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
