### ISSUE TITLE
[São Paulo] Front-End Sênior na FTD

### ISSUE THREAD

**Issue by Robertaramunno** [frontendbr/vagas#533]
## Descrição da vaga

Buscamos profissionais Front End com sólida experiência com Angular.

## Local

Escritório - São Paulo - SP

## Benefícios

Contratação PJ

## Requisitos

**Obrigatórios:**
- Javascript, JQuery, testes unitários e funcionais.
- Angular
- Laravel

**Desejáveis:**
HTML
CSS
PHP
MYSQL

## Contratação

PJ a combinar

## Nossa empresa

BK CONSULTORIA

## Como se candidatar

Por favor envie um email para roberta.ramunno@bkconsultoria.com.br com seu CV anexado - enviar no assunto: Vaga: ANGULAR/LARAVEL

**Comment by LFeh** [comment]
É para trabalhar na propria BK Consultoria?

**Comment by Robertaramunno** [comment]
Será contratado BK na FTD.

De: Felipe Fialho [mailto:notifications@github.com]
Enviada em: sexta-feira, 8 de setembro de 2017 12:15
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: Roberta Tura Ramunno <roberta.ramunno@bkconsultoria.com.br>; Author <author@noreply.github.com>
Assunto: Re: [frontendbr/vagas] Front-End Sênior (#533)


É para trabalhar na propria BK Consultoria?

**Comment by LFeh** [comment]
Aberto ainda?
