### ISSUE TITLE
(Contagem) Front-End Sênior @Partner Consultoria 

### ISSUE THREAD

**Issue by PartnerConsultoria** [frontendbr/vagas#5330]
ATIVIDADE
- Conhecer os elementos e formas de interações entre os diversos dispositivos.

O QUE PRECISA TER
- Sólida experiência no desenvolvimento front-end com uso de frameworks como: Angular e React
- Conhecimento avançado de linguagens como Javascript e TypeScript
- Conhecimento avançado em tecnologias e ferramentas como HTML5, CSS3 ( Sass,  Less), pré- processadores ( Gulp, Grunt, etc), Frameworks ( Bootstrap, Foundation, etc.)
- Sistemas de controle de versão (Git, Mercurial, etc.), testes Cross Br...

HORÁRIO DE TRABALHO: Flexível

LOCAL DE TRABALHO: Home Office 

Pretensão Salarial
 
Enviar currículo para selecaoprh@gmail.com

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
