### ISSUE TITLE
[Remoto/São Paulo] Front-end Developer Sr na Telefonica-Vivo

### ISSUE THREAD

**Issue by victorkulcsar** [frontendbr/vagas#5333]
> Vaga Remota durante a pandemia (e provavelmente depois dela)
enviar currículo para victor.santos@telefonica.com
Mais informações: https://vivo.gupy.io/jobs/1021242

RESPONSABILIDADES E ATRIBUIÇÕES
·        Ter conhecimento técnico médio para alto;

·        Dominar os recursos da linguagem e programação e conhecer bem a maioria dos frameworks base da plataforma;

·        Linguagens/tecnologias: JavaScript, Angular, React, Vue, NodeJs, SASS, Docker, Jest;

·        Development & Testing: tem um nível de codificação e teste muito bom (código bem documentado e seguindo boas práticas) com foco no desenvolvimento de backlog técnico (mecanismos arquiteturais e funcionalidades mais críticas);

·        Promover uma cultura de melhoria contínua;

REQUISITOS E QUALIFICAÇÕES
·        Superior completo;

·        Necessário conhecimento técnico de aplicações Web e Mobile;

·        Necessário experiência em projetos utilizando metodologia ÁGIL;

·        Conhecimento de sistemas de autoatendimento de clientes;

 

Desejável Inglês ou Espanhol Intermediário.

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
