### ISSUE TITLE
[Remoto ou Recife] Front-end Developer na Bleu Empreendimentos Digitais

### ISSUE THREAD

**Issue by BLEU-Empreendimentos** [frontendbr/vagas#5334]
## Nossa empresa

A Bleu é uma empresa voltada para criação e desenvolvimento de tecnologia em Blockchain. Combinamos a inovação e descontração para o desenvolvimento de projetos.

## Descrição da vaga

É desenvolvedor Front-end e está procurando um job?
Estamos buscando desenvolvedores para somar à nossa equipe!

## Local

- 100% Home Office ou Híbrido

## Requisitos

**Obrigatórios:**
- Ter conhecimento em linguagem de programação;
- Pelo menos um framework javascript;
- Ter experiências anteriores.

**Desejáveis:**
- NodeJS; 
- Pré-processadores CSS e Typescript; 
- Blockchain.

## Benefícios

- Plano de saúde integral;
- Plano odontológico;
- Seguro de vida;
- Vale-refeição;
- Auxílio creche;
- Assistência na aquisição de óculos (lentes de grau);
- Assistência Home Office;
- Auxílio doença/invalidez;
- Auxílio combustível para deslocamento residência-empresa (quando presencial);
- Day Off no aniversário;
- Assistência Funeral;
- Descontos especiais em parceiro comerciais;
- Participações de lucros eventuais.

**Diferenciais para o trabalho presencial ou em dias presenciais:**
- Geladeira aberta;
- Café à vontade;
- Chocolate e lanches livres.

**Diferenciais para quem trabalha Home Office ou em Regime Híbrido:**
- Auxílio financeiro para Home Office.

## Como se candidatar

Por favor envie um email para rh@bleu.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
