### ISSUE TITLE
[Remoto] Front-end Developer na Bluemond

### ISSUE THREAD

**Issue by biaberbert** [frontendbr/vagas#5335]
[Remoto] Front-end Developer na Bluemond

> Vaga Remota 

## Nossa empresa

A Bluemond cria e gerencia equipes remotas de desenvolvimento para empresas, nós não temos um setor específico de atuação, e trabalhamos desenvolvendo principalmente atualizações e novos módulos para aplicativos web e mobile já lançados no mercado.

## Descrição da vaga

Precisamos de um desenvolvedor para trabalhar conosco nos melhores projetos para empresas do ramo financeiro e bancos digitais

## Local

 Remoto 

## Requisitos

**Obrigatórios:**
- React Native (Avançado)
- React (Avançado)
- TypeScript (Intermediário)
- Redux (Intermediário)
- Redux-saga (Intermediário)
- Hooks (Intermediário)
- Desenvolvimento de aplicação-web responsiva (Intermediário)

## Contratação

R$ 8.000 fixo mensal (Bônus de +R$5.600 mensal no segundo projeto)
Modelo: PJ

## Como se candidatar

Por favor envie um email para beatriz@bluemond.com.br ou bfrberbert@gmail.com com seu CV anexado - enviar no assunto: Vaga React/ReactNative

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: beatriz@bluemond.com.br

#### Alocação

- Remoto

#### Regime

- PJ

#### Nível

- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
