### ISSUE TITLE
[Remoto] Front-end Developer - React na Peopleplan

### ISSUE THREAD

**Issue by SauloGandolfi** [frontendbr/vagas#5337]
[Remoto] Front-End Developer - React na Peopleplan
==================================================
-->
> Vaga Remota 

## Nossa empresa
Faça parte de um time com pessoas espetaculares e extremamente experientes para trabalhar no desenvolvimento de planos de bem-estar corporativo.
Quer conhecer o que nos motiva, como trabalhamos, e efetivamente o que fazemos? Maravilha! Dá uma olhada no nosso manifesto.
 
Unidos pela crença de que as pessoas têm um desejo natural de levar a vida de maneira saudável e equilibrada e que podemos apoiá-las nesta jornada. Criamos mais do que uma empresa, criamos uma comunidade, na qual colaboramos com usuários, empresas e parceiros, para oferecer uma nova geração de benefícios integrados que demonstra um real comprometimento em apoiar as pessoas na conquista do bem-estar.
 
Quer saber quando começamos e como evoluímos? Ok, vamos lá!
 
Fundamos a empresa no de ano 2000 e temos apoiado milhões de pessoas a terem vidas mais saudáveis ao longo de nossa história. Ao mesmo tempo, essas pessoas nos ensinaram muito e evoluímos para sermos a maior “WellTech” do Brasil! Abraçamos o conceito “WellTech” por ser a evolução humanizada de uma “HealthTech”. Combinamos excelência em tecnologia, saúde e capacidade analítica com o entendimento que os objetivos de cada pessoa e de cada empresa são únicos e podem variar ao decorrer do tempo. Entender estas necessidades das empresas e dos colaboradores e desenhar a melhor solução para maximizar o bem-estar é o que nos diferencia. Por isso, dentro de nosso Plano de Bem-Estar temos como benefícios corporativos coberturas que incluem desde preços exclusivos na compra de alimentos saudáveis e produtos naturais, serviços focados em melhorar a saúde mental, e subsídios de mais de 50% em medicamentos. E vem muito mais por aí. Esse é só o início de uma série de outras inovações previstas para ampliar a oferta de serviços do Plano de Bem-Estar, reforçando o compromisso da empresa em fazer o bem, ao ampliar o acesso à qualidade de vida a milhões de brasileiros.

## Descrição da vaga
• Buscamos um desenvolvedor front-end criativo, com facilidade para aprender e sugerir novas tecnologias e frameworks voltados ao desenvolvimento web.
• Entre as responsabilidades, esperamos alguém com grande conhecimento em HTML5, Javascript e CSS3.
• Garantir a qualidade e a manutenibilidade de todo código produzido por você e seus pares;
• Otimizar a aplicação para melhor velocidade e escalabilidade;
• Escrever testes unitários e automatizados;
• Criar código e bibliotecas reutilizáveis para uso futuro;
• Identificar os débitos técnicos quando necessário, resolver débitos técnicos sempre que possível;
• Documentar e compartilhar toda e qualquer solução implementada;
• Colaborar com outros membros da equipe, product owner, scrum master e Qualidade para resolver os desafios existentes;
• Ter atitude de dono/ser responsável por suas entregas.
• Entre as responsabilidades do candidato, é esperado especial preocupação com a utilização adequada das guidelines e padrões de cada linguagem.

## Local

Remoto

## Requisitos
• Dominar profundamente HTML 5;
• CSS 3 (bootstrap e/ou materialize) com less, OO CSS;
• Javascript (JQuery e React JS);
• Conhecimentos em edição de imagem com Photoshop;
• Conhecimentos sobre guidelines de performance, SEO, Web Semantica e Google Analytics;

**Desejáveis:**
 Webpack, Redux, Styled Components, Hooks, Context API;
• Gitlab (ci/cd) e VS TFS;
• Conhecimento na IDE Visual Studio/Visual Studio code;
• Banco de dados Oracle, programação .NET e Web Essentials.

## Contratação

A combinar

## Como se candidatar

https://jobs.recrutei.com.br/PeoplePlan/vacancy/11131-desenvolvedor-front-end-react

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
