### ISSUE TITLE
[Remoto/Híbrido - Portal Alegre] Front-end Developer @Target.IT

### ISSUE THREAD

**Issue by davidrtpereira** [frontendbr/vagas#5339]
## A Empresa

A Target.IT é uma empresa que atua como fabrica de software no desenvolvimento Web, utilizando tecnologias modernas e avançadas no seguimento fiscal. Seu cargo chefe é o software  para o gerenciamento e emissão de documentos fiscais como: NF-e, CT-e, NFC-e, MDF-e. 
Além disso possuímos parceria SAP e desenvolvimento Protheus para integração dos serviços fiscais.
A empresa fica localizada na Av. Cristovão Colombo, próximo ao hospital militar no bairro Floresta.

## A Vaga

**Possuímos 2 vagas! Total front-end**

### Perfil profissional
Buscamos uma profissional determinado, que esteja **disposto a aprender a regra de negócio da empresa**, para que possa não apenas contribuir com seu conhecimento técnico, mas também com sugestões e melhorias no desenvolvimento. Aqui você terá  liberdade para atuar nas demandas, que exigi um nível alto de pró-atividade e conhecimento do negócio.

### Conhecimentos e Habilidades
Em constante atualização, está em desenvolvimento a nova versão da aplicação da empresa, que irá substituir a atual aplicação comercializada pela empresa. A nova aplicação já é usado em produção por já possuir a maior parte dos recursos previstos na aplicação atual. Com a atualização de tecnologias, possuímos um alto volume de novas _features_ que vem agregando cada vez mais valores para a nova aplicação. Necessitamos então de profissional comprometido, apaixonado por tecnologia e com perfil pró-ativo.

Com este cenário, precisamos de alguém que consiga adaptar-se com as diferenças de versão e tecnologias.

### A equipe
Equipe ótima! Com um maravilhoso ambiente de trabalho e descontraído. Aqui você terá espaço para aprender e ensinar!

#### Principais requisitos (Não são necessariamente obrigatórias)

- PHP (Versões 5.5.38 e 7.0 >);
- JavaScript;
- NodeJS;
- Git;
- Saber integrar com Web Service arquitetura REST;
- Angular JS (5 >); ou algum Framework javascript;
- Socket.IO;
- HTML
- CSS
- Gostar de verdade de Frontend

#### Habilidade/Experiência que serão consideradas como diferenciais

- Experiência/Conhecimento na área fiscal
- Git Flow;
- Laravel (5 >);
- TypeScript
- Metologias ágeis;
- Sass;
- Bootstrap;
- UX
- Design

## Contratação
**Totalmente remoto**, para quem está fora então seja você de qualquer Estado, bora trabalhar a gente!

- Contratação regime CLT ou PJ;
- Plano de saúde (CLT);
- VR e VA de R$ 32,50/dia (CLT);
- Remuneração (Negociável de acordo com seu conhecimento, possuímos plano de carreira) ;

Interessado? Envie seu currículo para selecao@targetit.com.br, com o título desta vaga no assunto do e-mail, junto com sua pretensão salarial e modalidade de contratação.

## Labels

- Alocado
- Híbrido
- Remoto
- Total remoto
- CLT
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
