### ISSUE TITLE
[São Paulo] Front-End Developer na Ventron

### ISSUE THREAD

**Issue by Dani-Ventron** [frontendbr/vagas#534]
## Descrição da vaga

Manage & further develop our CMS and different websites in React
Integrate with internal or 3rd party RESTful APIs
Develop responsive sites (web based / mobile apps) built on different backends.
Able to manage, coach and provide support for small development team.
Communicate technical solutions to clients.
Interact with design and product teams.
Define best practices
What we appreciate in you:

Strong knowledge of React.js.
Practical experience with ES2015+ APIs and language features
Proficient in CSS/3 with deep knowledge of browser compatibility (IE9+) and responsive design.
Team player, able to communicate openly
Languages: French/preferred, English/must, written & spoken

## Local

Itaim Bibi

#

## Requisitos

**Obrigatórios:**
- React
- Inglês

**Desejáveis:**
- Francês

## Contratação

PJ ou CLT

## Nossa empresa

A VENTRON, empresa do grupo CADMUS, com  20 anos no mercado

## Como se candidatar

Por favor envie um email para daniele.silva@ventron.com.br com seu CV anexado - enviar no assunto: Vaga Front End

**Comment by joshi-mehul** [comment]
Is it a remote role?  I would love to take a test.  Mail me on mehul0923@gmail.com

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by joshi-mehul** [comment]
Yes

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
