### ISSUE TITLE
[São Paulo/SP] Java Developer na TO Brasil

### ISSUE THREAD

**Issue by MaahTechRecruiter** [frontendbr/vagas#5340]
NOSSA EMPRESA

Há mais de 15 anos, a TO Brasil combina experiências em Soluções de Negócios e Tecnologia da Informação. Nosso portfólio conta com clientes em diversos segmentos como Telecom, óleo e gás, finanças, transportes, varejo, instituições de ensino, entre outros. Possuímos uma fábrica de desenvolvimento de software própria e somos especializados em projetos orçamentários, financeiros e de BI. Nossos processos garantem maturidade e eficiência para aplicar as melhores práticas no desenvolvimento e na manutenção de nossas soluções.
Contamos com uma equipe de 700 Colaboradores e investimos em treinamentos para ratificar a qualidade de nosso time. Nossas parcerias com gigantes mundiais do setor de TI garantem o reconhecimento em soluções EPM e no portfólio de projetos em BI.
Por isso, acreditamos que o respeito e a confiança em Colaboradores, Clientes e Parceiros são os nossos diferenciais – é no material humano que a TO Brasil faz o seu principal investimento.
A perseverança define a história da TO Brasil.

DESCRIÇÃO DA VAGA

Desenvolvedor Java Pl/Sr

LOCAL DA VAGA

Hibrido em São Paulo/SP zona sul 

REQUISITOS OBRIGATÓRIOS

Java
Angular
Spring Boot
Micros serviços
Metodologia Ágil

BENEFÍCIOS

Plano de saúde
Plano odontológico
VR/VA
Seguro de vida
Vale transporte

REGIME CLT 

COMO SE CANDIDATAR

Caso se identifique com a vaga me envie seu CV para: marlene.souza@to-brasil.com ou pelo WhatsApp: 11 947850149 com o título da vaga.  

TEMPO MÉDIO DE FEEDBACK

Costumo dar feedback imediato.

LABELS

Alocação: 
Híbrido

Regime
CLT

Nível
Pl/Sr

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
