### ISSUE TITLE
[São Paulo/SP] Front-end Developer na Suprevida

### ISSUE THREAD

**Issue by gabernardi** [frontendbr/vagas#5341]
## Nossa empresa
A Suprevida é uma startup de saúde e tecnologia (Healthtech) fundada em 2018 que tem a missão de facilitar o acesso a serviços e produtos para que as pessoas possam prevenir, preservar e recuperar a saúde.

Fazemos parte do Hub Distrito InovaHC - Plataforma inovadora de conexão entre os agentes da saúde - corporações e startups.

## Descrição da vaga

Front-end Developer no squad interno da Suprevida - com missão crítica de sustentação e desenvolvimento de novos projetos e reengenharia.

## Local

Primeiro momento: Escritório, [SP], [São Paulo], [Cerqueira César]

## Requisitos

**Obrigatórios:**
- Conhecimento em HTML, CSS.
- Conhecimento em Typescript e Javascript. 
- Conhecimento em React

**Desejáveis:**
- Experiência com Next.js

## Benefícios

- Plano de saúde sem desconto.
- Vale Transporte ou Vale Combustível
- Vale Refeição ou Alimentação de R$ 30/dia
- Plataforma Distrito Network com acesso a mentorias, cursos e descontos.

**Diferenciais:**
- Ambiente de trabalho agradável
- Equipamentos modernos
- Inovação constante
- Autonomia

## Contratação

CLT

## Como se candidatar

Por favor envie um email para gabriel.bernardi@suprevida.com.br com seu CV e LinkedIn  - enviar no assunto: Vaga Front-end ou candidate-se pelo link: https://vagas.revelo.com.br/suprevida/frontend-developer

## Tempo médio de feedbacks

2 dias.

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
