### ISSUE TITLE
[Remoto] Front End React Developer na Delivery Center

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#5343]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-a-front-end-react-153327762?origin=github&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Aqui na Delivery Center, você terá a oportunidade de criar e implementar as melhores soluções, em um ambiente que proporciona aprendizados diários. Utilizamos algumas ferramentas para resolver e superar diferentes desafios do nosso negócio.</p>
<p></p>
<p>Buscamos <strong>Pessoas Desenvolvedoras Front-end React.js</strong>.</p>
<p></p>
<h6><strong>Como será o seu dia a dia: </strong></h6>
<ul>
<li>Trabalhar em equipe no desenvolvimento das soluções</li>
<li>Desenvolvimento de novas funcionalidades</li>
<li>Manutenção e refactoring em funcionalidades existentes</li>
<li>Garantir o alinhamento entre os requisitos de design(UX/UI) e técnicos</li>
<li>Traduzir wireframes de design de UI/ UX para código</li>
<li>Escrever códigos e bibliotecas reutilizáveis</li>
<li>Elaboração da documentação dos sistemas</li>
</ul>

## Delivery Center: 
 <p>Somos uma startup de tecnologia que está criando o ecossistema de varejo mais significativo da América Latina, conectando lojistas, canais de vendas e entregadores em uma única plataforma e oferecendo aos varejistas as soluções mais avançadas e eficientes para criar canais de vendas e entregar seus produtos em minutos, em todo o Brasil!</p>
<p>Bem-vindo à revolução do Varejo. Bem-vindo ao Delivery Center.</p><a href='https://coodesh.com/empresas/delivery-center'>Veja mais no site</a>

 ## Habilidades: 
 - HTML 5 
- Javascript 
- React.js 
- Typescript 
- Next.js 
- GIT 
- CSS 3
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência com frameworks e bibliotecas front-end (React) 
- Experiência com HTML, CSS (SASS ou LESS), JavaScript ou TypeScript 
- Experiência com versionamento de código (Git, GitHub, ou Gitlab) 
- Conhecimento em design responsivo e adaptativo 
- Conhecimento em integração com API's
**Diferenciais:** 
 - Experiência com framework AngularJs 
- Conhecimento em testes (unitários, componentes) 
- Conhecimento em Storybook, Design System  
- Conhecimento em ESlint, Prettier, Husky
## Benefícios: 
 - Vale Refeição e/ou Alimentação 
- Convenio Médico 
- Convenio Odontológico 
- Gympass 
- PPR 
- Descontos em instituições de Ensino 
- Day off de aniversário 
- Licença Maternidade e Paternidade estendida
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Front End React Developer na Delivery Center](https://coodesh.com/vagas/desenvolvedor-a-front-end-react-153327762?origin=github&modal=open)

[object Object],[object Object],[object Object],[object Object],[object Object]
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
