### ISSUE TITLE
Belo Horizonte Front-end Developer Outsystems na Rosso Consultoria

### ISSUE THREAD

**Issue by Priscilagraziela** [frontendbr/vagas#5344]
## Nossa empresa

Rede supermercadista mineira reconhecida pelo atendimento diferenciado, variedade e sofisticação do mix de produtos. Nossa missão: "Tornar uma compra de supermercado um ato de emoção, prazer e diversão, oferecendo produtos variados e diferenciados, surpreendendo sempre as expectativas dos nossos clientes.”

## Descrição da vaga

Desenvolver novos produtos e serviços utilizando a tecnologia Outsystems.

Pesquisar e identificar tecnologias e soluções oferecidas pelo mercado.

Realizar manutenção evolutiva e corretiva de produtos e serviços existentes.

Contatar fornecedores de equipamentos e softwares, esclarecendo dúvidas técnicas diversas, repassando necessidades, especificações e solicitando orçamentos.

Monitorar o desempenho e a performance dos produtos e serviços desenvolvidos.

Realizar reuniões de acompanhamento dos projetos, alinhando atividades realizadas x planejadas avaliando o cumprimento de etapas.

## Local

Minas Gerais, Belo Horizonte, Funcionários

## Requisitos

**Obrigatórios:**
• Linguagem de Programação Outsystems
• Lógica de Programação
• HTML
• CSS
• JavaScript
• WebService
• Inglês Avançado
• Banco de Dados
• C#

## Benefícios
- Plano de saúde
- Seguro de vida
- Alimentação na empresa
- Convênio odontológico

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um email para vagas@rossoconsultoria.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor Outsystems

## Labels
CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
