### ISSUE TITLE
[São Paulo] Front-End Developer React Native na Sacola VIP

### ISSUE THREAD

**Issue by guimc** [frontendbr/vagas#5345]
## Nossa empresa

A Sacola VIP é uma startup focada em comércio atacadista para pequenos players do ramo têxtil. Estamos em busca de um(a) Programador para compor o nosso time e crescermos juntos.

## Descrição da vaga

- Desenvolvimento de aplicativo mobile híbrido (preferencialmente em React focado em Android e iOS);
- Desenvolvimento de soluções específicas em linguagem nativa para Android e iOS;
- Gerenciamento de banco de dados;
- Noções de API Rest;

## Local

São Paulo/SP - Centro

## Requisitos

- Conhecimento de PHP, HTML, CSS;
- Conhecimento em React Native, Objective-C, Java;
- Portfólio no GitHub e LinkedIN;
- Desejável curso superior em ciência da computação, engenharia e desenvolvimento de softwares e cursos similares;
- Desejável 2 anos de experiência profissional;

## Benefícios

- Vale Transporte
- Vale Refeição

## Contratação

Regime CLT

## Como se candidatar

Por favor envie um email para contato@sacolavip.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor de Aplicativo

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: contato@sacolavip.com.br

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
