### ISSUE TITLE
[Remoto] Front-End Developer na Mindbe

### ISSUE THREAD

**Issue by VictorMayrink** [frontendbr/vagas#5347]
## Mindbe

Nascemos para trazer de volta a satisfação e a confiança das pessoas nas marcas e produtos que estão no mercado. Aqui na Mindbe somos antes de tudo criativos. Nosso trabalho é encontrar soluções que geram eficiência para as empresas, lançando um olhar estratégico para os processos do negócio, mas sem deixar de ver as reais necessidades e desejos das pessoas. 

Para saber mais: www.mindbe.com.br

## Descrição da vaga:

O profissional será responsável por:

- Implementar aplicações Web em HTML5, JavaScript, Vue.JS e RESTFul para aplicações desenvolvidas em arquitetura de MICROSERVIÇOS.
- Trazer novidades sobre as tecnologias que sejam benéficas para o negócio.
- Capacidade analítica para arquitetura de soluções, utilizando boas práticas compatíveis com o mercado.
- Trabalhar com facilidade com os membros da equipe na busca da melhor solução.
- Ser protagonista, sempre se colocando à frente de situações e buscando o melhor para a Mindbe.
- Gerenciamento e flexibilidade de horário de acordo com as demandas.

## Local:

100% Remoto.

## Requisitos:

**Obrigatórios:**

Conhecimentos nas linguagens abaixo:

- Vue.JS (Avançado/Experiente)
- HTML e HTML5
- Javascript
- CSS3
- Bootstrap
- Protocolo HTTP
- Integração com API REST
- Notação JSON
- Superior Incompleto/Completo nas áreas de Tecnologia

**Desejáveis:**

- Controle de Versão (Git/Subversion)
- Banco NoSQL (MongoDB)
- Arquitetura de Sistemas

**Diferenciais:**

- Gerenciamento de Container (Docker)

## Benefícios

- Horários Flexíveis

## Contratação

PJ a combinar

## Como se candidatar

Por favor se cadastre nesse link: https://mindbe.empregare.com/pt-br/vaga-desenvolvedor-web-especialista-em-vue-js_22026

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 25 dias após cada processo.
E-mail para contato em caso de não haver resposta: talentos@mindbe.com.br

#### Alocação

- Remoto

#### Regime

- PJ

#### Nível

- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
