### ISSUE TITLE
[Remoto] Front-end Developer Jr. na MGB

### ISSUE THREAD

**Issue by fabiofcos** [frontendbr/vagas#5348]
> Vaga Remota

## Nossa empresa

Somos movidos pela paixão por inovar e transformar a vida das pessoas pela educação e gestão aquática!

Vamos conversar?

## Descrição da vaga

Desenvolvimento Frontend
Manutenção de sistemas para correção de falhas/erros
Preocupação com fidelidade das telas em relação aos protótipos
Boa modularização e reuso de código
Implementação de melhorias
Atuar como parte da equipe ágil e cultura DevOps
Otimizar a aplicação para melhor velocidade e escalabilidade
Garantir a validação dos dados fornecidos pelos usuários
Criar código e bibliotecas reutilizáveis para uso futuro
Atuar no desenvolvimento de aplicações com foco em performance, qualidade e usabilidade
Participar de todas as etapas da criação do produto, desde o planejamento, passando pelo desenvolvimento, até a entrega e documentação
Discutir ideias, ferramentas e metodologias que possam otimizar o desenvolvimento do produto

## Requisitos

**Obrigatórios:**
Experiência em desenvolvimento frontend e capacidade em aplicá-la a problemas práticos
Bons conhecimentos em JavaScript,  frameworks, Bootstrap
Conhecimento de tecnologias como HTTP, DOM, CSS, HTML5, JSON, etc.
Conhecimento de SOLID, CleanCode e Cultura de teste
Conhecimento em bancos de dados
Conhecimento aplicado de padrões de design modernos
Experiência prática com integração contínua, implantação automatizada e testes
Conhecimento dos princípios ágeis e suas aplicações práticas

**Desejáveis:**
Conhecimentos em Vue.js

**Diferenciais:**
Formação em tecnologia
Inglês técnico

## Contratação

PJ a combinar

## Como se candidatar

Por favor, envie um e-mail para fabiofranco@metodologiagb.com.br com seu CV anexado. Enviar no assunto: _Vaga Front-end Jr._

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
