### ISSUE TITLE
[REMOTO] Front-end Developer nível ESTÁGIO (PJ) na Unlimited Bubbling

### ISSUE THREAD

**Issue by vini-brito** [frontendbr/vagas#5349]
## Nossa empresa

Empresa focada em criar novos poderes para os usuários da plataforma [Bubble](https://www.bubble.io).

## Descrição da vaga

**Vaga para quem busca primeira oportunidade profissional de programar comercialmente.**

Não trabalhamos com React nem frameworks similares e sim uma plataforma que de longe lembra o wordpress, é a Bubble, o foco é em Vanilla JS, lógica e manipulação da DOM, além da iniciação em interpretação de requisitos, documentação do projeto e outros.

Tenho um material de treinamento robusto que ensina não só a parte de interagir com a plataforma Bubble como também a parte de requisitos e preparo de documentação.

Tem espaço para você criar algo baseado em tecnologias do seu interesse que possa beneficiar a empresa, por exemplo algo que não seja o nosso trabalho de rotina porém que ajudaria a organizar nosso Github, que atualmente está com bem pouco uso porém precisamos de administrar melhor o código dos nossos projetos. 
Isso te permitiria aprender mais sobre Git e Github, caso seja seu interesse.

Ou uma ferramenta programada via biblioteca NodeGUI para desktop, é algo que seria útil.

Expectativa é de passar de 3 meses a no máximo 6 meses neste formato.

## Local

Remoto.

## Requisitos

**Obrigatórios:**

HTML, CSS e JS essenciais
Disposto a aprender a plataforma Bubble (bubble.io)
Inglês intermediário, suficiente para compreender textos em inglês e conseguir produzir textos em inglês. Você terá bastante tempo para produzir cada texto, caso precise, porém é necessário já ter familiaridade com inglês.

## Contratação

PJ, pode ser MEI, não precisa estar cursando em universidade.
Carga horária e responsabilidades flexíveis.
R$600 a R$1100, dependendo do aprendizado atual e da carga horária que deseja.

## Como se candidatar

Email para support@unlimitedbubbling.dev falando um pouco dos seus estudos, sua familiaridade com inglês e experiência caso tenha.

## Tempo médio de feedbacks

Até 2 semanas.

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Estagiário

**Comment by Emilly-horta** [comment]
enviado!

**Comment by opablosantos** [comment]
Enviado!

**Comment by arthurcant** [comment]
Sent!

**Comment by thiagogabbi** [comment]
enviado

**Comment by Stadlinger** [comment]
Sent!

**Comment by ad-costa** [comment]
Enviado!

**Comment by CiceroLino** [comment]
Enviado!

**Comment by thiagoDeviner** [comment]
Sent!

**Comment by nicolemachado** [comment]
Sent

Em dom, 25 de jul de 2021 13:13, thiagovcardoso ***@***.***>
escreveu:
