### ISSUE TITLE
[São Paulo] React Native Developer

### ISSUE THREAD

**Issue by jgrossineto** [frontendbr/vagas#535]
## Descrição da vaga
Experiência na criação de apps com React Native para as plataformas Android e iOS. É preciso ter experiência com a adaptação do layout para diferentes resoluções e plataformas.

## Necessário
React Native, Javascript, ES6, CSS, FlexBox e boa lógica de programação.

## Desejável
Redux, APIs Rest, Firebase, Objective C/Java para o desenvolvimento de módulos nativos e Selenium.

## Local
Remoto ou Escritório, São Paulo - Vila Gertrudes (próximo ao shopping morumbi)

## Tipo de contratação
PJ. Freela de aproximadamente 3 semanas. 

## Candidaturas
jose.grossi@candowell.com

**Comment by ribeiroevandro** [comment]
Enviado

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
