### ISSUE TITLE
[Remoto] Front-end Developer Sênior ReactJS na @Xgrow

### ISSUE THREAD

**Issue by geekrootbr** [frontendbr/vagas#5352]
Somos uma empresa de tecnologia de edução em crescimento, com foco em ajudar criadores de conteúdo, professores e escolas a terem seus cursos disponibilizados na Internet com uma experiência de aprendizado diferenciada. 

Descrição da vaga

Você estará junto com a equipe no desenvolvimento do front-end da nossa ferramenta, criando interfaces web, áreas de aprendizagem, aplicativos móveis. Procuramos programadores com vontade de aprender, que desejem crescimento na carreira, que busquem uma visão de longo prazo na nossa empresa. Queremos pessoas que entendam e vivam nossa missão de transformar o ensino e usem seus talentos nessa empreitada.

Local
REMOTO

Requisitos

Obrigatórios:
JavaScript (ES6, ES7, ES8), Typescritpt
HTML, CSS, SASS
Experiência de 3 anos+ ReactJS
Experiência com ferramentas de versionamento (GitHub)

Desejáveis:
	• conhecimento em NextJS
	• conhecimento em ReactNative

Contratação
PJ a combinar

Como se candidatar:
Por favor envie um email para rh@xgrow.com com seu CV anexado - enviar no assunto: FRONT END DEV

Tempo médio de feedbacks
Costumamos enviar feedbacks em até 2 dias após cada processo.

Regime
	• PJ

Nível
	• Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
