### ISSUE TITLE
[Florianópolis] Front-end Developer na Altoqi

### ISSUE THREAD

**Issue by Steporto** [frontendbr/vagas#5353]
## Descrição da vaga
- Discutir a estratégia de codificação com o Analista da equipe
- Codificar a solução de software necessária para atender o recurso definido para o produto
- Utilizar as ferramentas de depuração para identificar as causas de erros e realizar as correções necessárias.
- Realizar testes básicos da implementação efetuada
- Documentar as alterações no código escrito e demais diagramas aplicáveis
- Utilizar a ferramenta e os procedimentos estabelecidos no Processo de Desenvolvimento da empresa para reportar problemas encontrado

## Local

Remoto, Escritório em Florianópolis/SC

## Benefícios

- Trabalhe em home office.
- Auxílio home office durante a pandemia.
- Opções de Vale alimentação e/ou Vale refeição.
- Parceria com Planos de Saúde.
- Parceria com Assistência Odontológica.
- Não precisa se preocupar com o look. Aqui, a gente investe no conforto. Não há códigos para se vestir, desde que se sinta bem!
- Também temos parcerias com o SESC, ACATE, redes de farmácia e restaurantes.
- Mães e pais que estão esperando por seu filho, participam do programa bebê a bordo, com cursos e brindes.

#### Diferenciais

- Horário flexível
- Equipamento completo, para trabalho home office

## Requisitos

**Obrigatórios:**
- Graduação completa ou cursando a em áreas da Computação, Sistemas ou Automação.
- Experiências com alguma programação, exemplo: PHP, Javascript, Dotnet ou Javaspring.

**Desejáveis:**
- *

**Diferenciais:**
- Experiência com programação em C++

## Contratação

CLT 

## Nossa empresa

O Grupo AltoQi é uma empresa com soluções de software altamente especializadas para a construção civil. Estamos, em crescimento e buscando novos talentos. 

## Como se candidatar

Por favor realize seu cadastro em nosso site https://altoqivagas.enlizt.me/vagas/desenvolvedor-a-_de_software-220621, em caso de dúvidas entre em contato através stefanie.bentzviller@altoqi.com.br

### Alocação:
- Remoto

### Contratação:
- CLT

### Experiência
- Jr
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
