### ISSUE TITLE
[REMOTO] Front-end Developer na CRM Intelligence Services

### ISSUE THREAD

**Issue by ccaiolopes** [frontendbr/vagas#5354]
## Nossa empresa

Somos uma empresa de Consultoria em Softwares de Gestão, nascemos em 2009 e desde então ocupamos todo Brasil. Somos movidos por inovação, provocamos rupturas e transformações, ampliando a capacidade de gestão e desempenho nas empresas. 

Site: crmservices.com.br
Instagram: @somoscrmservices

## Descrição da vaga

Procuramos programadores que já possuem conhecimento com .Net Core para realizar as integração com o Angular. 
De preferência que sejam FullStack.

O trabalho será realizado remotamente de segunda a sexta. 

Em torno de 170 horas mês.

## Local

Trabalho Remoto

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Angular
- 3 anos de experiência com .Net Core
- JavaScript (ES6, ES7, ES8), Typescritpt
- HTML, CSS, SASS
- Experiência com ferramentas de versionamento (GitHub)

**Desejáveis:**
- Jira
- AWS

**Diferenciais:**
- Perfil Dinâmico
- Proativo

## Contratação

PJ a combinar de acordo com a experiencia.

## Como se candidatar

Por favor envie um email para edna.queiroz@crmservices.com.br com seu CV anexado - enviar no assunto: Vaga Angular

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dia após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
