### ISSUE TITLE
[São Paulo] Front-End Developer na Jüssi

### ISSUE THREAD

**Issue by tayanebruno** [frontendbr/vagas#536]
## Front-End Developer JR/PL/SR [3 vagas]

Buscamos desenvolvedor front end para trabalhar na estrutura da Produtos Digitais da Jüssi, com foco em desenvolvimento para e-commerce. Trabalhará em conjunto com designers e analistas de dados para fornecer a melhor experiência para nossos usuários.

## Local

Escritório, São Paulo - Itaim Bibi

## Benefícios

- Assistência Médica Sulamerica
- Assistência Odontológica Odontoprev
- VR de R$ 31,00/dia útil
- VT

#### Diferenciais

- horário flexível
- cerveja liberada toda sexta feira à partir das 17h
- café da manhã toda segunda feira
- day off de aniversário

## Requisitos

- Capacidade para escrever código consistente, eficiente, minimalista, reutilizável e escalável
- Desenvolver código semanticamente correto e otimizado para seo
- Javascript, html5, css3
- Sass e/ou less
- Task runners (grunt / gulp)
- Controle de versão (git / svn)
- Experiência com bibliotecas de javascript, como jquery
- Experiência com grids fluidos e sites responsivos
- Pacote adobe, em especial photoshop
- Facilidade de trabalho em equipe
- Proatividade

**Desejáveis:**
- Conhecimento avançado em javascript (sem plugins ou bibliotecas)
- Experiência em construção de e-commerce na plataforma vtex
- Wordpress

## Contratação

CLT 

## Nossa empresa

A Jüssi é uma agência digital com foco na geração de negócios, que leva performance a sério. Para nós, performance é o ar que respiramos, é a cultura da empresa, é a molécula principal do nosso DNA. Fazemos parte do grupo WPP e temos aproximadamente 300 pessoas trabalhando com a gente. 

## Como se candidatar

Por favor envie um email para tayane.bruno@jussi.com.br com seu CV anexado - enviar no assunto: Vaga Front-End

**Comment by hillarysousa** [comment]
Pode se candidatar remotamente? No caso seria para trabalhar
presencialmente.

Em 11 de set de 2017 3:14 PM, "tayanebruno" <notifications@github.com>
escreveu:

**Comment by rafaelnai** [comment]
Poderiam enviar um teste?

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by danieladuarteng** [comment]
enviado

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
