### ISSUE TITLE
[REMOTO] - Pessoa Desenvolvedora React Pleno

### ISSUE THREAD

**Issue by thearis** [frontendbr/vagas#5363]
## Descrição da vaga
Nosso propósito e missão
A EZ é uma empresa que tem o objetivo de transformar negócios através de pessoas, cultura e tecnologia. A gente acredita que esses motores são capazes de mudar o rumo de organizações inteiras. 

Então para fazer esse objetivo acontecer, nós temos a missão de conectar talentos de tecnologia a Startups e Scale-ups.

Você pode conhecer melhor nossas ofertas para o mercado no nosso site 😉

**Sobre o cliente**
A Linx é uma empresa brasileira especialista em tecnologia para o varejo, que possui o propósito de aproximar pessoas e tecnologia por meio de experiências de compra apaixonantes mundo afora!

É líder no mercado de software de gestão, com 45,6% de market share do mercado varejista, conforme atesta o IDC. 

A Linx também se tornou a primeira empresa brasileira de software com capital aberto na NYSE, em 2019. A empresa possui mais de 3,5 mil colaboradores distribuídos entre sua sede em São Paulo, 15 filiais pelo Brasil e 5 países da América.

## Local
Vaga totalmente remota.

## Requisitos
- Experiência com JavaScript, React e seu ecossistema;
- Conhecimento com bancos de dados relacionais e não-relacionais;
- Sólido conhecimento em Git.

**Desejáveis:**
- Conhecimento em React Native;
- Conhecimento com MongoDB.

## Benefícios
- Aulas de inglês;
- Descanso remunerado;
- Gympass.

## Contratação
Modelo de contratação PJ.

## Como se candidatar
Acesse o site e se cadastre! Link: https://ezdevs.yaap.tech/vaga/pessoa-desenvolvedora-front-end-react-pleno-fri3674a

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
