### ISSUE TITLE
[Home Office] Front-end Developer na ZUKK

### ISSUE THREAD

**Issue by ANARABELLO** [frontendbr/vagas#5364]
> Vaga Remota 

## Nossa empresa

Zukk é uma empresa de geotecnologia e inovação com mais de 2 anos no mercado e que utiliza o poder da localização na construção de um futuro próspero e sustentável. Apaixonados por inovação, unimos no time especialistas em GIS, sensoriamento remoto e tecnologia da informação, para acelerar o uso da tecnologia geoespacial e levar cada projeto rumo a liderança da inovação e transformação digital dos negócios.

## Descrição da vaga

Desenvolver códigos reutilizáveis, testáveis e eficientes;
Utilizar boas práticas de desenvolvimento;
Participar e colaborar com os Squads Ágeis em seus rituais;
Definir soluções de forma propositiva, apresentar as suas recomendações e ideias;
Atuar em colaboração com desenvolvedores back-end e POs;

## Local

100% REMOTO

## Requisitos

**Obrigatórios:**

Linguagens de programação que você vai usar: Javascript e React JS.
Conhecimentos que você precisa ter: Conhecimento básico de UI/UX e design patterns e versionamento de código com GIT.

**Desejáveis:**

conhecer métodos ágeis (Scrum e Kanban) e boas práticas de qualidade como TDD 

## Benefícios

- Plano de saúde Porto Seguro
- Plano odontológico
- 15 dias uteis de férias 

**Diferenciais:**
- Folga no aniversário

## Contratação

PJ 
Salário até 5,5K

## Como se candidatar

Por favor envie um email para anacbrabello1@gmail.com com seu CV anexado - enviar no assunto: Vaga FRONT 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: anacbrabello1@gmail.com

#### Alocação
- Alocado
- Remoto

#### Regime

- PJ

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
