### ISSUE TITLE
[São Paulo] Front-end Developer Reactjs na ATLAS GOV

### ISSUE THREAD

**Issue by MaurilioTechfor** [frontendbr/vagas#5369]
> Vaga Remota 

## ATLAS GOV

Atuar em projeto 100% home office, em renomado cliente do segmento de Governança Corporativa, sendo o maior portal de governança da América Latina.

## Descrição da vaga

Perfil com sólidos conhecimentos em React (ES6, hooks, context api ou redux) para desenvolvimento e manutenção de aplicações; Integração com APIs; Criação de interfaces avançadas; Desenvolvimento de código limpo; 
DIFERENCIAIS: Já ter atuado com metodologia ágil ou conhecimentos de Azure Devops

## Local

Remoto 

## Requisitos

**Obrigatórios:**
Conhecimentos em React (ES6, hooks, context api ou redux)

**Desejáveis:**
Integração com APIs; 
Criação de interfaces avançadas; 
Desenvolvimento de código limpo; 

**Diferenciais:**
Já ter atuado com metodologia ágil ou conhecimentos de Azure Devops

## Benefícios

13o salário 
Vale refeição 
Auxílio Saúde 
Auxílio Coworking 
Fornecimento de equipamento para trabalho 
Gympass 
Aulas de Espanhol

## Contratação
Contratação Modelo Cooperativa

## Como se candidatar

Por favor envie um email para mdoliveira@techforti.com.br com seu CV anexado - enviar no assunto: Vaga Frontend Reactjs

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.
E-mail para contato em caso de não haver resposta: mdoliveira@techforti.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- Cooperativa

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
