### ISSUE TITLE
[Remoto] Front-end React Developer na Foton Tech

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#5370]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-react-145703737?origin=github&medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Se você tá cansado de:</p>
<ul>
<li>Ambiente desorganizado.</li>
<li>Cobrança excessiva.</li>
<li>Falta de trabalho em equipe.</li>
<li>Falta de reconhecimento.</li>
<li>Falta de perspectiva de crescimento.</li>
<li>Ter que trabalhar finais de semana ao invés de descansar.</li>
</ul>
<p>Convido você a conhecer a FOTON. Aqui pessoas vêm em primeiro lugar e não limitamos seu crescimento!</p>

## Foton Tech: 
 <p>Me responde uma coisa:</p>
<p>Você tá cansado(a) de ser visto apenas como mais um(a) <strong>digitador(a) de código</strong>?</p><a href='https://coodesh.com/empresas/foton-tech'>Veja mais no site</a>

 ## Habilidades: 
 - Javascript 
- React.js
## Local: 
 100% Remoto
## Requisitos: 
 - No mínimo 2 anos de experiência profissional com React 
- No mínimo 2 anos de experiência profissional com Javascript 
- Inglês avançado para conversação

## Benefícios: 
 - 100% remota
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Front-end React Developer na Foton Tech](https://coodesh.com/vagas/frontend-react-145703737?origin=github&medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Nível
Pleno
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
