### ISSUE TITLE
[Remoto] Front-end Engineer na T10

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#5371]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-engineer-132339549?origin=github&medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Esta é uma oportunidade para integrar nosso time de Desenvolvimento Backend e ser protagonista em um projeto inovador e de alto nível técnico.</p>
<p>Na T10, você será peça central no desenvolvimento do time, parte de uma equipe talentosa e com opiniões bem formadas sobre como softwares devem ser desenhados, modelados e implementados.</p>
<p>Se identificou? 🚀</p>

## T10: 
 <p>Nós nascemos da paixão pela <strong>tecnologia</strong> e do desejo de construir o ambiente de trabalho que queremos e acreditamos ser possível: <strong>plural</strong>, <strong>criativo</strong>, <strong>transparente</strong> e <strong>livre</strong>. Ah, e full remoto!&nbsp;</p>
<p>Buscamos a excelência e priorizamos otimizar os serviços que agregam real valor: estratégia para transformação digital, IA, análise de dados, design e desenvolvimento ágil. Tudo isso colocado em prática por meio de estudos e decisões de pessoas com mentes inquietas e curiosas. Somos abastecidos pelo seguinte propósito:</p><a href='https://coodesh.com/empresas/t10'>Veja mais no site</a>

 ## Habilidades: 
 - HTML 5 
- Javascript 
- React.js 
- React Native 
- Typescript 
- Next.js 
- CSS 3 
- Jest
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência atuando profissionalmente na área; 
- Conhecimento de computação, conceitos e fundamentos; 
- Fluência em JavaScript e bibliotecas de Frontend (ênfase em React); 
- Conhecimento e experiência na implementação de CI/CD; 
- Experiência com testes unitários e e2e (Jest, Cypress, Puppeteer); 
- Experiência com NextJS (SSG e SSR); 
- Experiência com deploy e infraestrutura; 
- Experiência com TypeScript; 
- Familiaridade com Git Flow (Pull Requests e Code Reviews).
## Diferenciais: 
 - Functional Approach; 
- Experiência com ReScript; 
- Experiência com AWS (S3, Route 53, CloudFront).
## Benefícios: 
 - Cartão VR + VA 
- Auxílio Home Office 
- Notebook 
- Home office 
- Plano de saúde 
- Plano odontológico 
- Auxílio Saúde 
- Horário Flexíveis
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Front-end Engineer na T10](https://coodesh.com/vagas/frontend-engineer-132339549?origin=github&medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
