### ISSUE TITLE
[Remoto] Front-end Developer na ICOMM Group

### ISSUE THREAD

**Issue by wesleyalmd** [frontendbr/vagas#5375]
## Descrição

**Vaga para**: Desenvolvedor Frontend (Pleno ou Sênior) na ICOMM Group
**Carga horária**: full time

O Desenvolvedor Front-end será responsável por auxiliar no desenvolvimento de módulos javascript. O profissional deverá comunicar com o time técnico e stakeholders do projeto.

### Obrigatórios

- Conhecimento avançado em JavaScript, HTML e CSS;
- Experiência com PWA e serviceWorker;
- Experiência com React;
- Experiência com git;

### Desejáveis

- Conhecimento em GraphQL;
- Conhecimento de desenvolvimento ágil (SCRUM);
- Experiência com CI/CD;

### Diferenciais

- Experiência com e-commerce;
- Disposição para ensinar;

## Contratação

- PJ a combinar
- Pleno, Sênior

## Como se candidatar

Envie um e-mail para wesley.almeida@mcx.com.br com seu CV anexado, github ou portfolio.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
