### ISSUE TITLE
[Blumenau] Full stack Delphi Developer na HunterCo

### ISSUE THREAD

**Issue by jananessi** [frontendbr/vagas#5376]
## Nossa empresa

Contribuir para o desenvolvimento sustentável e transparente das organizações públicas, através da gestão das informações de forma integrada com tecnologia avançada e inovadora.

## Descrição da vaga

Desenvolver e entregar código dentro das melhores práticas de programação;
Realizar as manutenções e adequações legais dentro do sistema tributário;
Identificar problemas na base de código existente e aplicar melhorias;
Realizar entregas de forma autônoma e/ou em equipe, dentro do prazo acordado;
Dentre outras atividades pertinentes à função.

## Local

Blumenau/SC

## Requisitos

**Obrigatórios:**
Experiência em desenvolvimento de sistemas utilizando Delphi e Banco de dados.

## Benefícios

Vale alimentação;
Plano de saúde integral (inclusive coparticipação);
Seguro de vida;
Auxílio educação;
Convênio com farmácia (descontos especiais) e subsídio para medicamentos com receita médica.
Outras parcerias com estabelecimentos.

## Contratação

CLT

## Como se candidatar

Por favor cadastre-se no link: https://vagas.hunterco.com.br/job/60f081b4a8ea60001d8c9e88?c=3822

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após cada processo.

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
