### ISSUE TITLE
[São José] Front-end Developer na @Intelbras

### ISSUE THREAD

**Issue by ElisaLimaIntelbras** [frontendbr/vagas#5377]
Sobre a Intelbras

Nós somos a Intelbras! Uma empresa de tecnologia com unidades em São José (SC), Santa Rita do Sapucaí (MG) e Manaus (AM). A gente trabalha pra levar soluções que protegem, conectam, aproximam e transformam a vida de milhões de pessoas, no Brasil e no mundo. E nós temos tanta gente incrível trabalhando aqui! Gente que tem a vontade de evoluir sempre, e que sabe a importância de estar em uma empresa que valoriza pessoas e acredita no potencial de cada uma delas.
Somos uma empresa diferente. Nosso clima é único e quem trabalha aqui sabe disso. Para colocar em prática alguns de nossos valores como simplicidade e empresa feliz, oferecemos um ambiente de trabalho aberto, alegre e descontraído, que acreditamos ser fundamental para ter o engajamento e o melhor das pessoas. Nós investimos em ações que promovem a parceria, a integração e o trabalho em equipe.

Sobre nosso time de EAG (DVR Veicular)

Trabalhar na área de Desenvolvimento no time de Software (Produto DVR – gravadores de imagem – Veicular) será um desafio considerando que estamos montando a squad, as atividades eram realizadas por terceiros, a proposta será essa cadeira de Front-end se aliar a duas novas posições de Back-end, estruturando toda arquitetura desse novo projeto. Serão os mentores e nossa proposta é estruturar inicialmente e após agregar novos INlovers nesse time.

Missão do cargo

Como Front-end, você fará parte das squads de aplicação nesse novo projeto e será responsável por gerar valor ao negócio, estar disposto a encarar esse grande desafio na área de Segurança Eletrônica. Seu dia a dia será desenvolver e arquitetar SPA e websites para a principal solução de software da sua categoria de produtos, não atuando apenas no desenvolvimento de aplicações para o cliente externo, mas também no desenvolvimento de ferramentas para áreas da própria organização. 

Responsabilidades

Captar as necessidades envolvidas em um projeto e transformá-las em interfaces funcionais, responsivas, amigáveis e atuais. 
Conhecimentos necessários
Domínio em HTML, CSS, JavaScript.
Experiência com alguns desses frameworks: ReactJS, Material-UI.
Desenvolvimento de plataformas SPAs.
Conhecimento e atuação com testes, otimização de código para diferentes plataformas e manutenção em aplicações.
Desenvolvimento de protótipos para validação de ideias, vivência com Git. 

Conhecimento diferencial

Redux, Hulks.
Metodologia ágil de desenvolvimento.

Benefícios

Plano de Saúde Unimed.
Seguro de vida.
Restaurante no local.
Banco no local.
Lanchonete no local.
Farmácia no local.
Academia no local.
Auxílio creche.
Financiamento de Estudos.
Participação nos Lucros semestral.
Transporte Fretado.
Um belo desconto nos produtos da Intelbras!

Local

Híbrido - Escritório São José- Santa Catarina

Contratação

CLT

Como se candidatar

Por favor envie um email para elisa.lima@intelbras.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Developer
Tempo médio de feedbacks
Costumamos enviar feedbacks em até 02 dias após cada processo.
E-mail para contato em caso de não haver resposta: elisa.lima@intelbras.com.br

Nível

Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
