### ISSUE TITLE
[Remoto] Fullstack Developer @TOTVS

### ISSUE THREAD

**Issue by jananessi** [frontendbr/vagas#5378]
## Nossa empresa

Somos a maior empresa de tecnologia do Brasil e nosso poder de transformação faz com que nossos softwares estejam presentes em mais de 40mil empresas no Brasil e no mundo.
O nosso grande segredo para estar sempre um passo a frente do mercado é a ousadia e a transformação que nossos TOTVERS promovem todos os dias.

Ousadia para movimentar 25% do PIB brasileiro por meio dos clientes que usam os nossos softwares.
Ousadia para ser a primeira empresa de tecnologia do Brasil a ser listada na Ibovespa.
Ousadia para fazer da mudança a nossa rotina, com mais de 40 aquisições ao longo de nossa história.

Nossa curiosidade nos impulsiona e, o melhor, todo mundo colabora com todo mundo, não importa quem deu a ideia: todos estão dispostos a ajudar e se envolvem legitimamente para fazer dar certo e entregar resultados.

## Descrição da vaga

Desenvolverá soluções baseadas em microsserviços/cloud;
Utilizará técnicas como TDD e DDD e metodologia Ágil;
Desenvolverá soluções técnicas de alta complexidade foco na usabilidade do produto;
Garantirá a utilização e aplicação de boas práticas no desenvolvimento de testes;
Fará estudos com clientes e áreas envolvidas no projeto;
Contribuirá com a disseminação do conhecimento adquiridos sobre técnicas e tecnologias;
Irá propor inovações que se apliquem ao roadmap;
Participará de discussões táticas e de definição de metas da área;
Orientará e capacitará o time de desenvolvimento para aplicação das soluções arquitetadas.

## Local

Remoto

## Requisitos

**Obrigatórios:**
JAVA Avançado;
Spring Avançado;
Angular avançado;
HTML;
CSS;
Javascript/Typescript;
Performance de Front-end– Avançado;
Domínio em arquitetura web;
Testes unitários e end to end (e2e);
Integração e Entrega contínua;

**Desejáveis:**
Métodos ágeis de desenvolvimento de software;
Software de edição de imagens e prototipação de interface – básico;
Sistemas distribuídos e escalabilidade – intermediário;
Ionic;
Formação superior na área de TI;
Conhecimento do mercado de logística.

## Benefícios
Plano de saúde
Plano odontológico
Vale refeição/alimentação
Licença maternidade e paternidade estendida
Seguro de vida
Previdência privada
Gympass
Universidade corporativa com conteúdo e certificações gratuitos para os nossos TOTVERS
Cuidamos dos nossos TOTVERS com o Programa +Saudáveis, com assessoria e ações voltadas para o bem estar em corpo, mente e finanças pessoais
Programa +Vantagens, a maior rede de descontos da América Latina, exclusivos para nossos TOTVERS

**Diferenciais:**
Valorizamos a diversidade e inclusão, consideramos todos os candidatos para as nossas vagas independente de cor, raça, religião, gênero e identidade de gênero, nacionalidade, deficiência, orientação sexual, ascendência, idade, etc

## Contratação

CLT

## Como se candidatar

Por favor cadastre-se no link: https://vagas.hunterco.com.br/job/60dc5630791415001d51bbee?c=4145

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.
E-mail para contato em caso de não haver resposta: janaina.nessi@parceirohunterco.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
