### ISSUE TITLE
[Remoto] Mobile Developer na HunterCo

### ISSUE THREAD

**Issue by jananessi** [frontendbr/vagas#5379]
## Nossa empresa

Somos uma empresa jovem que busca atendimento de excelência para seus clientes, respeitando cada parceiro de negócio, seja um profissional do time, fornecedor ou cliente.
Inconformados com um mercado que preza por volume, buscamos padrões de excelência para conectar pessoas e sistemas e promover uma jornada digital incrível!

## Descrição da vaga

Desenvolver novas funcionalidades para o um aplicativo comercial B2B;
Realizar manutenção em funcionalidades já existentes no produto atual;
Realizar tarefas de debug quando necessário ou quando houver problemas.

## Local

Remoto

## Requisitos

**Obrigatórios:**
Domínio de Swift;
Boa vivência com desenvolvimento mobile;
Experiência em desenvolvimento com XCode.

**Desejáveis:**
Domínio de Objective-C;
Experiência com geração de ambiente de publicação Apple para apps.

## Benefícios
Salário/Remuneração fixa
Acolhimento Psicológico
15 dias de férias (PJ)
Happy Our On Line
Academia do Conhecimento

## Contratação

CLT/PJ a combinar

## Como se candidatar

Por favor cadastre-se no link: https://vagas.hunterco.com.br/job/60ccd07ae01d37001d24fcf8?c=3796

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
