### ISSUE TITLE
[Rio de Janeiro] Front-End Developer Junior na .Original+GTX

### ISSUE THREAD

**Issue by guilhermemarconi** [frontendbr/vagas#538]
![.Original+GTX Expandindo experiências](http://gtxcode.com.br/Capa-Face-2070109.png)

## Descrição da vaga

Estamos em busca de um front-end developer júnior com sangue nos olhos, vontade de aprender e coragem para encarar desafios.

## Local

Escritório, Centro - Rio de Janeiro

## Benefícios

- Plano de saúde
- VR de R$ 30,00/dia
- VT

#### Diferenciais

- Equipe multidisciplinar
- Ambiente descontraído

## Requisitos

**Obrigatórios:**
- Conhecimento moderado em JavaScript
- Conhecimento moderado em Sass (SCSS)
- APIs REST
- Organização (afinal, HTML é organização 😉 )

**Desejáveis:**
- React
- Testes Unitários

**Diferenciais:**
- Webpack
- Interesse em aprender linguagens back-end (tornar-se fullstack)
- Projetos open source

## Contratação

- Presencial
- CLT
- Junior

## Salário

À combinar

## Nossa empresa

A Original e a GTX são agências com expertise em experiências de compra no meio digital que se fundiram para unir forças e tornarem-se referência no mercado, atendendo clientes como Uber, Grupo Boticário, Grupo Technos, Sky e Nestlé, entre outros.

## Como se candidatar

Por favor envie um email para cv@originalmedia.com.br com seu CV anexado, além de usuário do GitHub/Bitbucket (caso tenha contribuído em projetos open source) e portfolio (se tiver).

Enviar com o assunto _Vaga Front-end Developer Jr_

**Comment by iamfelipemattos** [comment]
nao existe nenhuma possibilidade de trabalho remoto?

**Comment by rubenmarcus** [comment]
conhecimento avançado em JS é junior?

**Comment by guilhermemarconi** [comment]
@rubenmarcus eu editei. isso era de outra vaga que eu acabei esquecendo de alterar. obrigado!

@iamfelipemattos como estamos ainda no processo de união das duas equipes, fica complicado de fazer trabalho remoto agora. temos pretensão de fazer num futuro próximo, mas ainda está um pouco complicado, infelizmente.

**Comment by guilhermemarconi** [comment]
@gmmoraes não temos deadline, pois é sempre interessante ter uma boa base de currículos, mas, nesse caso, em específico, estamos precisando de alguém asap.

**Comment by gmmoraes** [comment]
@guilhermemarconi  obrigado pela informação! Vou mandar o meu curriculo sem falta até o final da semana.

**Comment by angelilton** [comment]
essa vaga ainda está aberta?

**Comment by guilhermemarconi** [comment]
@angelilton está sim. Estou separando alguns CVs antes de seguir para o próximo passo.

**Comment by renan-ramos** [comment]
Na vaga nao informa o salario...

**Comment by guilhermemarconi** [comment]
@renan-ramos não informei porque seria à combinar. Mas posso adicionar na vaga, sem problemas.

**Comment by Pedro-Souza** [comment]
@guilhermemarconi Acho que seria bacana informa para as pessoas ter uma base...

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by guilhermemarconi** [comment]
@LFeh estamos sempre recebendo currículos, por estarmos em processo de expansão.
Se achar melhor, posso publicar vagas semper que estivermos, de fato, recrutando alguém novamente.

**Comment by antoniotex** [comment]
Bom dia. É difícil surgir uma vaguinha de estagiário? Preciso de um pouco de experiência pra me chamarem de Júnior.

**Comment by simaodeveloper** [comment]
@antoniotex só no Rio ou pode ser em SP, eu vi essa https://enext.gupy.io/jobs/5033

**Comment by antoniotex** [comment]
@simaodeveloper Legal a vaga, mas por enquanto tô atrelado ao RJ em razão da minha bolsa. Obrigado pela informação.

**Comment by simaodeveloper** [comment]
@antoniotex tu tem linkedin? vi outra vaga e lembrei de tu, mas é melhor eu passar para ti por la no linkedin.

**Comment by antoniotex** [comment]
Opa valeu @simaodeveloper. Meu Linkedin http://bit.ly/2nagG9w. Obrigado pela lembrança.

**Comment by angelilton** [comment]
essa vaga ainda está aberta? porque mandei em setembro e não tive nem um retorno

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
