### ISSUE TITLE
[São Paulo] Front-end Developer na 5A Attiva

### ISSUE THREAD

**Issue by CarolinaRCerqueira** [frontendbr/vagas#5384]
## Descrição da vaga

Estar envolvido com desenvolvimento Ágil; Cultura de Squads; participação de cerimônias; senso de dono do produto e colaboração; Pair Programming/XP; Cultura Devops; Busca por automação, CI/CD

## Local

Brooklin Paulista - São Paulo

## Requisitos

Atuar com React; AngularJS/Angular 2+; javascript, css e html, possuir vivência em metodologias ágeis.

## Contratação

PJ 

## Como se candidatar

Por favor envie um email para carolina.cerqueira@5aattiva.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor Front-end

#### Alocação

 Remoto durante a pandemia, após a pandemia será híbrido 

#### Regime

- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
