### ISSUE TITLE
[100% REMOTO] Líder Técnico na 5A Attiva

### ISSUE THREAD

**Issue by CarolinaRCerqueira** [frontendbr/vagas#5386]
## Descrição da vaga

Gerenciar uma equipe local e remota de engenheiros de software e especialistas em controle 
de qualidade. Lidar com conversas sobre viabilidade e conceitos de protótipo em 
colaboração com outros engenheiros e designers. Gerenciar o processo de sprint, as tarefas diárias e a carga de 
trabalho da equipe de maneira eficiente, enquanto comunica o progresso, os bloqueadores e as metas
claramente para a equipe maior. Realizar revisões regulares de código, aplicar as melhores práticas de 
codificação, controle de origem e resultados. Usar a codificação prática para ajudar os desenvolvedores 
da equipe a realizar as tarefas e remover bloqueadores. Impor documentação técnica clara, coesa, 
abrangente e bem escrita. Impor constantemente códigos de front-end modernos, bem elaborados e de alta qualidade.

## Requisitos

Experiência em gerenciamento de equipe de engenharia ou liderança de projetos.
PossuiR experiência com tecnologias front-end (HTML, CSS e JS) e no desenvolvimento com frameworks front-end modernos (React, VueJS, Angular JS, Vanilla JS). Experiência com Git e Jira. Experiência com NodeJS e / ou Python. Bons conhecimentos de 
plataformas em nuvem como AWS, Google Cloud Platform ou Azure. Experiência em integração de experiências front-end com plataformas CMS / eCommerce como Contentful, Adobe Experience Manager, Shopify, Magento. Conhecimento de linguagens de desenvolvimento de aplicativos móveis, como Swift, Kotlin, Flutter. 

## Contratação

PJ

## Como se candidatar

Por favor envie um email para carolina.cerqueira@5aattiva.com.br com seu CV anexado - enviar no assunto: Vaga NodeJS

#### Alocação
100% Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
