### ISSUE TITLE
[REMOTO] Front-end Developer PLENO Zallpy 

### ISSUE THREAD

**Issue by julianakraemer** [frontendbr/vagas#5387]
> Vaga Remota durante a pandemia

## Vaga para atuar na Zallpy Digital, 100% remoto

Remuneração: Até R$50/hora

## Descrição da vaga

Oportunidade para atuar como dev Front End Pleno para você que está iniciando no mundo do front, integre um time colaborativo em um ambiente moderno!
## Local

Home Office 

## Requisitos

**Obrigatórios:**
 Precisamos que você tenha em torno 3+ de experiência com desenvolvimento front end, vivencia com VueJS, VueRouter, Vuex, Vuetify e TypeScript.

**Desejáveis:**
Desejável conhecimento e vivência com desenvolvimento PHP. Diferencial: experiência com React ou VueJS.

## Benefícios

Aceita Home Office
Plano de saúde
Plano Odontológico
Previdência privada
Seguro de Vida
Ajuda de Custo
Horário flexível
- ...

## Contratação

PJ ou Cooperado

## Como se candidatar

Por favor envie um email para juliana@bemfacilcontrate.com.br 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

#### Regime

- Cooperado
- PJ

#### Nível

- Pleno

**Comment by angelilton** [comment]
olá juliana tudo bem! estão aberto para júnior remoto tbm, com foco em React?

**Comment by julianakraemer** [comment]
Boa tarde, no momento estamos trabalhando com vagas nivel Pleno!

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
