### ISSUE TITLE
[REMOTO] ARQUITETO DE SOFTWARE SÊNIOR - NODE.JS/REACT NA SOUTH SYSTEM

### ISSUE THREAD

**Issue by Ivone-Marchi** [frontendbr/vagas#5388]
A SOUTH SYSTEM está em busca de pessoas da área de ARQUITETURA DE SOFTWARE que desejam fazer parte do nosso propósito de impulsionar pessoas para inovar o mundo.

Para embarcar conosco, há algumas habilidades que valorizamos muito e não estamos falando apenas de tecnologia, nós valorizamos profissionais que respeitem o próximo e suas diferenças, que sejam leais e responsáveis ​​com as entregas e com as pessoas.

A colaboração e engajamento devem fazer parte do dia a dia para que o resultado seja eficaz e que tenha sede de treinamento para trabalhar com inovação contínua. 🧡

📌LOCAL DE TRABALHO

✳ Remoto

📌OS PRINCIPAIS BENEFÍCIOS:

✳Ajuda de custo para montar seu Home Office;
✳Bônus ao completar 1 ano de empresa;
✳Parcerias exclusivas para nosso profissionais, por exemplo Udemy (+ de 4 mil cursos gratuitos), Vitalk (plataforma de saúde mental e acompanhamento psicológico, gratuito), Money Mind (Consultoria financeira gratuita)
✳Entre outros.

📌NESSA OPORTUNIDADE VOCÊ TRABALHARÁ COM:

✳Soluções de arquitetura utilizando JavaScript (Node.js e React)
✳Micro Serviços;
✳Desing Patterns;
✳Banco de dados NoSQL MongoDB;
✳Cloud Azure

📌DESEJÁVEL (NÃO É UMA EXIGÊNCIA)

✳Pró-atividade e boa comunicação para buscar elucidar dúvidas de regras de negócios e funcionamento do software com a equipe;
✳Vivência em projetos do ramo financeiro ;
✳Familiaridade com metodologias ágeis e trabalho no formato de squad;

📌DIFERENCIAIS:

✳Avaliação de Performance
✳Plano de Desenvolvimento Individual
✳Feedbacks constantes
✳Ambiente flexível e aberto inovações, sugestões para novas ideias e criatividade.

Nossa empresa
📌SOBRE A EMPRESA

A South System está há 7 anos no mercado de tecnologia atuando com foco em Outsourcing em Projetos Fintechs que estão em transformações digitais.
Recentemente recebemos o Selo GPTW como uma das melhores empresas para se trabalhar.
Aqui na Corporação XPTO somos líderes em...

📌COMO SE CANDIDATAR?
Por favor envie um email para atracaodetalentos@southsystem.com.br com seu CV anexado - Enviar no assunto: Vaga ARQUITETO DE SOFTWARE.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
