### ISSUE TITLE
[São Paulo] Front-end sênior na SMDATA

### ISSUE THREAD

**Issue by Kevinlykarla** [frontendbr/vagas#5389]
## SMDAT - GY

Cliente na ária de energia sustentável.

## Descrição da vaga

Experiência muito boa em Angular 2 + (Utilizamos o 11);
Entendimento muito bom da linguagem JavaScript em combinação TypeScript;
Entendimento muito bom de RxJs;
Conhecimento sólido em HTML e CSS;
Bom conhecimento de controle de versão (Git);
Conhecimento do processo de CI/CD de uma aplicação (deploy, releases, builds);
Conhecimento básico em Azure ou equivalente.

## Local

Remoto, disponibilidade para presencial quando necessário.[São Paulo],[Alameda Santos]

## Requisitos

- 3 anos de experiência trabalhando com projetos de desenvolvimento de software e habilidades de comunicação e influência;

**Desejáveis:**
- conhecimento em Angular 2+
- conhecimento em JavaScript em combinação com TypeScript;
- conhecimentos em HTML e CSS
- conhecimento em RxJs
- conhecimento em Git
- conhecimento em CI/CD.

## Contratação

PJ a combinar e compatível com o mercado;
15 dias no ano de descanso remunerado

## Como se candidatar

Por favor envie um email para rh@smdata.com.br com seu CV anexado - enviar no assunto: FRONT END
 

## Labels

- Remoto
- Angular 2+
- JavaScript e TypeScript

#### Regime

- PJ

#### Nível

- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
