### ISSUE TITLE
[São Paulo]  - Front-End Developer na Wappa

### ISSUE THREAD

**Issue by jaquelinedamasco** [frontendbr/vagas#539]
Buscamos um profissional de alta performance, motivado, interessado e engajado à buscar desenvolvimento de uma carreira na área ....
Se você atua na área ... possuí experiência  em empresas de tecnologia ou serviços queremos conhecê-lo!

Local:
Escritório, São Paulo - Vila Olímpia

Diferenciais:
Diversos Benefícios como Massagens, Happy Hours, Bolsas de Estudo, Presente de Aniversário, Casamento, Nascimento de Filhos, Coaching entre outros.
Está no Ranking das Melhores Empresas do GPTW e Segunda Melhor Avaliação no site LoveMondays.

Requisitos:
• HTML (avançado)
• CSS (avançado)
• JavaScript (avançado)
• HTTP, Rest e consumo/integração de APIs (avançado)
• Conhecimento sólido em algum framework JS (Ember, Angular, React.js, etc) (avançado)
• Sistema de versionamento de código (Git) (avançado)
• Edição de imagem (photoshop) (básico)
• Aplicação de técnicas de SEO (Search Engine Optimization)
• Conhecimento em algum framework de testes (Karma, Mocha, Jasmine, etc..)
• Gulp,Bower
• Conhecimento em alguma linguagem backend (NodeJS, PHP, Python, etc…)
• Vivência em métodos ágeis
• Design Patterns
• Design responsivo e adaptativo

Contratação CLT mais Benefícios.

Por favor envie um e-mail para jaqueline@mazza.tech com seu CV anexado e pretensão salarial CLT - enviar no assunto: Vaga Front-End Vila Olímpia.

**Comment by LFeh** [comment]
Qual o nome da empresa?

**Comment by jaquelinedamasco** [comment]
Boa tarde Felipe,

 

É para a Wappa.

 

Obrigada.

 

 








 

Jaqueline Damasco


 

Human Resources.







jaqueline.marie.damasco




(11) 2532.2992 | (11) 997569.0652




Rua Alexandre Dumas, 1601 | Edifício Stelvio Mazza, 10º andar - SP







 

 

De: Felipe Fialho [mailto:notifications@github.com] 
Enviada em: quarta-feira, 13 de setembro de 2017 14:12
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: Jaqueline Damasco <jaqueline@mazza.tech>; Author <author@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [São Paulo] - Front End (#539)

 

Qual o nome da empresa?

**Comment by LFeh** [comment]
Aberto ainda?
