### ISSUE TITLE
[REMOTA] Front-End Developer Senior - Angular na SOUTH SYSTEM

### ISSUE THREAD

**Issue by Ivone-Marchi** [frontendbr/vagas#5390]
## Nossa empresa

A South System está há 7 anos no mercado de tecnologia atuando com foco em Outsourcing em Projetos Fintechs que estão em transformações digitais. Recentemente recebemos o Selo GPTW como uma das melhores empresas para se trabalhar.

## Descrição da vaga

A SOUTH SYSTEM está em busca de pessoas da área de ARQUITETURA DE SOFTWARE que desejam fazer parte do nosso propósito de impulsionar pessoas para inovar o mundo.

Para embarcar conosco, há algumas habilidades que valorizamos muito e não estamos falando apenas de tecnologia, nós valorizamos profissionais que respeitem o próximo e suas diferenças, que sejam leais e responsáveis ​​com as entregas e com as pessoas.

A colaboração e engajamento devem fazer parte do dia a dia para que o resultado seja eficaz e que tenha sede de treinamento para trabalhar com inovação contínua. 🧡

## Local

Remoto

## Requisitos

✳Desenvolvimento com Angular 4+
✳HTML5 e CSS
✳Java Script
✳React.js

**Desejáveis:**
✳Ferramentas Jira e Bitbucket
✳Conhecimento e Jenkins; 
✳Experiência com ferramenta de versionamento de código (GIT)

**Diferenciais:**
✳Avaliação de Performance
✳Plano de Desenvolvimento Individual
✳Feedbacks constantes
✳Ambiente flexível e aberto inovações, sugestões para novas ideais e criatividade 

## Benefícios
✳VR/VA no cartão Flex
✳Plano de Saúde com 100% de Cobertura 
✳Ajuda de custo para montar seu Home Office;
✳ Bônus ao completar 1 ano de empresa;
✳Parcerias exclusivas para nosso profissionais, por exemplo Udemy (+ de 4 mil cursos gratuitos), Vitalk (plataforma de saúde mental e acompanhamento psicológico, gratuito), Money Mind (Consultoria financeira gratuita)
✳Entre outros.

## Contratação

CLT 

## Como se candidatar

Por favor envie um email para atracaodetalentos@southsystem.com.br com seu CV anexado - Enviar no assunto: Vaga Front-End Developer. 

👀👀👀👀 Ah! E não esquece de dar uma olhadinha no nosso site https://southsystem.com.br/carreiras/ .

Vamos te apoiar durante toda sua jornada conosco e ao final, você entenderá o motivo da nossa nota de 4,9 no Glassdoor e Indeed.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

E-mail para contato em caso de não haver resposta: ivone.marchi@southsystem.com.br

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
