### ISSUE TITLE
[Remoto] Full Stack Ênfase em Front  na Vista Sofware

### ISSUE THREAD

**Issue by tainacusinato** [frontendbr/vagas#5391]
> Vaga 100 %  Remota

## Descrição da vaga

Desenvolver novas telas no sistema em conjunto com nosso Designer UX;
Manter códigos já existentes, criar documentações, solucionar problemas e adicionar novas funções;
Manter e otimizar a estrutura de front-end do sistema;

## Local

Remoto

## Requisitos
Experiência com desenvolvimento em projetos web com PHP
Experiência e conhecimento de HTML, CSS e JS
Conhecimento em banco de Dados MySQL
Experiência com versionamento com GIT

## Benefícios
• Cartão Flash (você escolhe como quer usar o crédito, que pode ser em mercado, restaurantes, uber ou até mesmo de bicicleta!);
• Plano de saúde e odontológico Sulamérica (aceito no Brasil sem co-participação) ;
• Plano de participação nos resultados (mediante a meta anual, pagamento semestral);
• PDV – Auxilio em cursos e eventos para o seu desenvolvimento pessoal e profissional;

**Diferenciais:**
• Ambiente de trabalho descontraído com oportunidade de aprendizagem, buscamos constante inovação, rodeados de uma equipe unida, sempre dispostos a atender e encantar nossos clientes;
• Somos transparentes em nossas decisões e atitudes, prezamos a nossa cultura de Feedback e 1 on 1.

## Contratação

CLT

## Como se candidatar

Por favor envie um email para queroserumvimaker@vistasoft.com.br com seu CV anexado - enviar no assunto: Vaga Full Stack

#### Regime
- CLT
- Estágio
- Freela
- PJ

#### Nível
- Júnior

**Comment by mateussilvasouza** [comment]
Não seria possível disponibilizar um pequeno desafio para entender a extensão dos conhecimentos necessários?
