### ISSUE TITLE
[Remoto] Front-end Developer na GX2 Tecnologia

### ISSUE THREAD

**Issue by apaulacosta** [frontendbr/vagas#5394]
## GX2 Tecnologia

Vem atuar em uma empresa que valoriza o colaborador com programas de desenvolvimento e acesso a plataformas de estudos.
Estamos te esperando, vem com a gente, vem pra GX ❤

## Descrição da vaga

Estamos buscando uma pessoa desenvolvedora em REACT!

## Local

100% Remoto

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com React

## Benefícios

- Férias
- Seguro de vida
- Acesso a plataformas Udemy, Allura e Rockseat
- Desconto em redes associadas

## Contratação

PJ ou Cooperado

## Como se candidatar

Por favor envie um email para oportunidades@gx2.com.br com seu CV anexado - enviar no assunto: Vaga React

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: anapaula.russo@gx2.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- Cooperado
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
