### ISSUE TITLE
[Curitiba PR - Home Office] Engenheiro DevOps na AVANTTi

### ISSUE THREAD

**Issue by victoriatechrecruiter** [frontendbr/vagas#5396]
NOSSA EMPRESA

AVANTTi é uma empresa focada em projetos de Dados & Analytics  com time especialista para desenvolver projetos em diversos segmentos (industrial, serviços). Contamos também com uma estrutura de Atendimento funcional SAP e ABAP para atendimento em projetos em diversos ambientes e versões.Atuamos na modalidade Outsourcing nas principais posições de Tecnologia com uma dinâmica de Formação de Talentos, chamamos de Outsourcing Colaborativo onde preparamos o profissional para o onboarding em nossos clientes.

DESCRIÇÃO DA VAGA
Engenheiro DevOps

LOCAL DA VAGA
Home Office / Mas, a empresa localiza-se em Curitiba - Pr

REQUISITOS OBRIGATÓRIOS
Inglês avançado
Experiência com ferramentas DevOps: Github, Chef, Puppet, Semaphore, Jenkins, Test Automation.
Experiência com lean/Metodologias de desenvolvimento ágil.
Experiência em public cloud, como Azure, AWS ou Google Cloud.

BENEFÍCIOS

Atuação remota, porém, para projetos Internacionais possibilidade de mudança para o projeto origem (regiões possíveis EUA/ARGENTINA/CANADÁ/ EUROPA); Brasil (SP, RJ, MG e PE), nas capitais iremos adotar o modelo híbrido. Para o interior e demais estados 100% remotos.
O equipamento do profissional será fornecido por nós.
Iremos trabalhar primeiramente com pretensão salarial para o modelo CLT Full – sem limites de valores, precisamos do melhor candidato possível.
Plano de Saúde, VR/VA, Plano Odontológico
Previdência Privada e outros

REGIME CLT

COMO SE CANDIDATAR: Caso se identifique com a vaga me envie seu CV para: victoriaaolv@gmail.com ou pelo WhatsApp: 86 99937-2919 com o título da vaga.

TEMPO MÉDIO DE FEEDBACK

Costumo dar feedback imediato.

LABELS

Alocação:
Home Office

Regime
CLT

Nível
Pl/Sr

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
