### ISSUE TITLE
[Juiz de Fora] Front-end Developer Pleno na RHeserva Consultoria

### ISSUE THREAD

**Issue by matheusfgalvao** [frontendbr/vagas#5397]
## Descrição da vaga

Procuramos um profissional para integrar o time de uma empresa em desenvolvimento e expansão.

## Local

Híbrido, [MINAS GERAIS], [JUIZ DE FORA]

## Requisitos

**Obrigatórios:**

- Angular

**Desejáveis:**

- Node.js
- MongoDB

## Benefícios

- Plano de saúde
- Vale alimentação
- Vale transporte (indo ao escritório)

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um email para matheus.fajardo@rheserva.com.br com seu CV anexado - enviar no assunto: [VAGA - FRONT-END ANGULAR]

## Remuneração

Procuramos, preferencialmente, um profissional pleno, mas estamos analisando outros perfis e trabalhando com pretensão salarial de acordo com a expertise do candidato.

#### Alocação

- Híbrido

#### Regime

- CLT

#### Nível

- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
