### ISSUE TITLE
[REMOTO] Freelancer

### ISSUE THREAD

**Issue by edpichler** [frontendbr/vagas#54]
## Descrição da vaga

Projeto freelancer de um Dashboard, onde o FrontEnd terá que usar de protótipos de tela e requisitos para desenvolver uma interface usando o Bootstrap (template pronto).

## Local
Remoto

## Benefícios
- Liberdade de horários.
- Projeto pequeno.

## Requisitos

**Obrigatórios:**
- Experiência comprovada.

## Contratação

Freelancer.

## Nossa empresa

Projeto pessoal.

## Como se candidatar

Por favor envie um email para edpichler@gmail.com com seu CV anexado - enviar no assunto: Vaga FrontEnd Dashboard.

**Comment by fejaum** [comment]
Currículo Enviado.

**Comment by ednilsonamaral** [comment]
E-mail enviado! :smile:

**Comment by jcdourado** [comment]
E-mail enviado!

**Comment by LFeh** [comment]
Conseguiu?

**Comment by edpichler** [comment]
@LFeh na verdade não. Estão demorando muito pra responder com um orçamento. O trabalho eh pequeno, optei por fazer eu mesmo dessa vez, pois já estava atrasando. O pessoal está demorando nas respostas por estar com medo de pegar uma "buxa", eu acho.

No entanto, vou precisar de um Freelancer nos próximos meses, pois o trabalho eh constante, vai ir aumentando, até chegar a hora de ter um contrato fixo PJ. 

Recebi muitos currículos bons postando aqui, classifiquei-os pro meu controle. 

Agradeço à todos.

**Comment by LFeh** [comment]
Show de bola! Boa sorte @edpichler :D

**Comment by ribeiroevandro** [comment]
Vou mandar o email, estou com umas horas livres, quem sabe fazemos alguns jobs juntos 😄
