### ISSUE TITLE
[São Paulo] Front-End Developer na RH Software

### ISSUE THREAD

**Issue by felipelomba** [frontendbr/vagas#540]
**Descrição da Vaga**

Buscamos desenvolvedores apaixonados por tecnologia, que queiram crescer com a empresa e aumentar a qualidade de nossos produtos.
Temos um time em crescimento e nossa stack está em evolução. Valorizamos o desempenho e comprometimento de todos do time.

**Responsabilidades**

Desenvolva recursos robustos, escaláveis e seguros
Escreva um código limpo, sustentável e eficiente
Participe de todas as etapas do ciclo de vida do desenvolvimento
Implementar melhores práticas de desenvolvimento orientado a testes, integração contínua, SCRUM, refatoração e padrões de código, e assim por diante
Mantenha-se informado sobre as novas tecnologias relevantes e promova sua adoção e integração contínuas no design

**Local**: Escritório, Arujá - SP

**Benefícios**:

Restaurante na empresa
Vale Transporte
Estacionamento

**Requisitos**

_Obrigatórios_:
2 anos de experiência em desenvolvimento com Frameworks frontend (AngularJS/VueJS) e HTML/CSS/Javascript
Habilidade de escrever código simples, limpo e eficiente
Excelente conhecimento de análise e design orientado a objeto
Conhecimentos desenvolviemento de aplicações api-only com Ruby on Rails

_Diferenciais_
Conhecimento em Ruby
Conhecimento em Elixir/Phoenix
Conhecimento em AWS

**Contratação**:
CLT a combinar

**RH Software:** 

Há 20 anos no mercado, com excelência em programas para gerenciamento de consultórios e clínicas, a RH Software possui hoje milhares de clientes no Brasil e no exterior.

Criamos softwares para a área da saúde que oferecem:

> mobilidade, tecnologia e praticidade;
> proporcionam mais controle e gestão otimizada do tempo;
> aumento da produtividade e do lucro para profissionais da saúde.

Por favor envie um email para felipe.lomba@rhsoftware.com.br com seu CV anexado - enviar no assunto: Vaga Front-End Developer

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
