### ISSUE TITLE
[Cidade] Front-end Flutter Developer na Jurema

### ISSUE THREAD

**Issue by malungo** [frontendbr/vagas#5400]
## Descrição da vaga
Estamos procurando um[a] desenvolvedor[a] mobile para juntar-se a nossa equipe e nos ajudar no desenvolvimento de novos produtos para nosso parceiro do mercado financeiro. Atuamos como uma equipe ágil de descoberta de novos produtos junto a este cliente e o[a] desenvolvedor[a] terá oportunidade de criar plataformas do zero (Greenfield Project), ajudando a definir arquitetura e tecnologias deste stack, além de ter a chance de colaborar com idéias e soluções junto aos designers de produto e serviços.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Desenvolver de forma fiel as interfaces criadas pela equipe de UX/UI para plataformas android e iOS
- Colaborar com designers para juntos encontrarem melhores caminhos para problemas de usabilidade e interações
- Trabalhar com desenvolvedores backend na definição das apis que melhor atendam as necessidades das interfaces
- Domínio de Dart.js
- Experiência mínima de 2-3 anos trabalhando com desenvolvimento mobile.
- Experiência com integração de APIs REST

**Desejáveis:**
- Experiência com desenvolvimento nativo Android e/ou iOS
- Experiência com testes automatizados de interface
- Interesse por aplicativos de alta qualidade de UX e UI

## Contratação

PJ a combinar

## Nossa empresa

Desde 2010, a Jurema busca criar soluções que tornem o dia a dia das pessoas mais simples ou divertido. Combinando design e desenvolvimento de software concebe produtos e serviços que rompem os limites entre a web e o mundo físico, ajudando junto com seus parceiros - empreendedores, corporações e governo - a criar o futuro da web.

## Como se candidatar

Por favor envie um email para jobs+flutter@jurema.la com seu CV anexado - enviar no assunto: Vaga FrontEnd Flutter

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 4 dias após cada processo.
E-mail para contato em caso de não haver resposta: ping@jurema.la

## Labels
- PJ
- Pleno
- Remoto

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
