### ISSUE TITLE
[REMOTO] FullStack Developer (Pleno/Sênior) no VAGALUME

### ISSUE THREAD

**Issue by lafraia** [frontendbr/vagas#5402]
## Descrição da vaga

É muito provável que você já tenha buscado alguma letra ou tradução no site, chegou a hora de poder contribuir com o projeto. Estamos, mais uma vez, abrindo esta oportunidade e buscando profissionais que possam fazer parte de uma equipe remota para vários desafios no [Vagalume](https://www.vagalume.com.br/).

O ambiente é super tranquilo com prazos flexíveis e focando **sempre** no longo prazo. Aqui no @vagalume temos a qualidade do código em primeiro lugar. É importante lembrar que a empresa, criada há 20 anos, mantém sua característica de startup buscando alta performance nos serviços em nuvem (AWS) e nas tecnologias utilizadas. É um ambiente ideal para aprender, mas infelizmente não temos espaço para dev júnior neste momento.

O foco é encontrar pessoas **bem** proativas, experientes, autodidatas, auto-motivadas e que possam executar as tarefas com bastante paixão, rapidez e com qualidade técnica. 💪

**Existem várias outras oportunidades de frontend e backend em outra uma startup, envie seu CV!**

## Local

100% Remoto! 🙏

## Requisitos

**Obrigatórios:**
- 4 anos de experiência com Web (avançado)
- 4 anos de experiência com PHP (outra startup do grupo não precisa de PHP, envie seu CV!)
- 3 anos de experiência com Javascript / NodeJS
- 1-2 anos de experiência com VueJS
- Experiência anterior com trabalho remoto
- Foco em qualidade do resultado final
- Experiência com sites responsivos

**Desejáveis:**
- conhecimentos sólidos na [semântica do html5](https://www.semrush.com/blog/semantic-html5-guide/) (leia também [este artigo](http://html5doctor.com/avoiding-common-html5-mistakes/))
- conhecimentos AWS e Docker

## Contratação

PJ

## Como se candidatar

Por favor envie um email para rh@vagalume.com.br com seu CV anexado - enviar no assunto: **Vaga Frontend** e responder as perguntas abaixo:

* Qual experiência anterior com trabalho remoto?
* O que você busca no seu desenvolvimento profissional?
* Qual sua experiência com (favor elaborar a resposta):
    * AWS (detalhar, por favor)
    * Javascript
    * PHP
    * VueJS
    * Sites responsivos
    * PHP
* Por que você acha que deve ser escolhido?
* Tem algum projeto pessoal que vale a pena mencionar?
* Como é o seu ambiente de desenvolvimento? SO, conexão, ambiente calmo, etc?
* Qual sua pretensão de valor mensal para dedicação tempo integral?

Se achar interessante compartilhar outras informações, pode mandar.

## Labels

- Remoto
- Freela
- PJ
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
