### ISSUE TITLE
[REMOTO] Pessoa Desenvolvedora Javascript/Angular na CRP Tecnologia

### ISSUE THREAD

**Issue by JulianaBNunes** [frontendbr/vagas#5404]
**JOB DESCRIPTION**

Estamos em busca de uma Pessoa Desenvolvedora, para executar o desenvolvimento de sistemas informatizados adequando-os às necessidades das áreas e clientes de uma grande fábrica de Software, visando racionalizar ou automatizar processos e rotinas de trabalho. 

**Farão parte do seu escopo de trabalho:**

- Receber a demanda do sistema detalhado pelo Analista determinando as atividades e desenvolver os softwares executando o tratamento dos dados, criando “scripts”, empregando técnicas e linguagens específicas, visando a aplicação necessária para a coleta dos dados de entrada, processamento e obtenção dos dados de saída desejados. 

- Manter registro das horas trabalhadas por projeto, para controle do superior e clientes. 

- Realizar os testes do sistema desenvolvido em simulações da operação verificando o atendimento das necessidades especificadas no projeto e seu desempenho.

- Avaliar erros e os corrigir, observando o eventual impacto em outros sistemas e liberar para a implantação providenciando a documentação técnica necessária para registro e controle do superior e clientes

- Acompanhar, junto com o Analista de Sistemas, a implantação do novo sistema participando na orientação dos usuários ou sugerindo melhorias no processo evidenciadas nesse momento. 

- Executar a manutenção preventiva ou corretiva de sistemas, conforme solicitações de clientes através da área de Atendimento, alterando o processamento, base de dados e fluxos, gerenciando versões dos produtos (criação de “branches” e “tags”) e bancos de dados etc. adaptando-os às novas necessidades dos usuários, atualização de tecnologia, correção de erros, melhor desempenho etc. 

- Atualizar a documentação técnica evidenciando as alterações para controle e ciência do superior e cliente. Participar, quando necessário, de reuniões junto a clientes para uma melhor compreensão das demandas de novos sistemas, melhorias e manutenções, orientação a usuários etc. colhendo subsídios para o trabalho de desenvolvimento. 

- Executar o desenvolvimento de sistemas informatizados adequando-os às necessidades das áreas e clientes visando racionalizar ou automatizar processos e rotinas de trabalho. 

- Receber a demanda do sistema detalhado pelo Analista determinando as atividades e desenvolver os softwares executando o tratamento dos dados, criando “scripts”, empregando técnicas e linguagens específicas, visando a aplicação necessária para a coleta dos dados de entrada, processamento e obtenção dos dados de saída desejados. 

**REQUIREMENTS AND SKILLS**

Escolaridade:Superior Completo ou Cursando Ciência da Computação, Sistemas de Informação ou cursos similares. 
Tecnologia: Java Script - Type Script  
Banco de Dados:SQL Server, MySQL, PostgreSQL 
Clouds - já ter trabalhado com pelo menos 1 destes: Google Cloud; Amazon AWS; Microsoft Azure.  
Diferenciais / Conhecimentos Desejáveis: Experiência com metodologias ágeis.

**ADDITIONAL INFORMATION**

Formato de trabalho: Presencial (Palmas-TO, Araguaína-TO ou Goiânia-GO) ou Remoto.
Modalidade de contratação: PJ ou CLT ·
Benefícios (se CLT): Vale Alimentação , Plano de Saúde / Odontológico e Seguro de Vida. ·
﻿Carga Horária: 40h semanais - Segunda a Sexta, das 08:00 às 12:00 / 14:00 às 18:00

Inscreva-se através do link: https://domdhtech.gupy.io/jobs/1067877?jobBoardSource=gupy_public_page

Ou envie seu currículo para: recrutamento.juliananunes@gmail.com

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
