### ISSUE TITLE
[São Paulo - SP] Desenvolvedor (a) JavaScript - GDW

### ISSUE THREAD

**Issue by vagnerGDW** [frontendbr/vagas#5405]
## Descrição da vaga

- Nível de experiência: Pleno a Sênior
- Setor: Tecnologia da Informação – Serviços

## Local
Vila Olímpia – SP (Regime: 50% on-site e 50% home office)

## Requisitos Necessários:

- Formação superior completa em Ciência da Computação ou áreas correlatas;
- Experiência em Node.js e do ecossistema de ferramentas (npm);
- Experiência em conhecimento de JavaScript, web stacks, bibliotecas e frameworks;
- Experiência em construção de serviços de back-end e front-end;
- Experiência em criação e consumo de APIs REST e SOAP;
- Experiência em banco de dados (SQL e NOSQL - MongoDB);
- Experiência em ferramentas de controle de versão de código, como Git;
- Conhecimento com HTML5 e CSS3;
- Conhecimento em troca de informações utilizando JSON;

## Atividades:

- Desenvolver códigos de alto nível conforme as boas práticas de mercado;
- Propor melhorias que tornem os sistemas/processos mais eficazes;
- Otimizar o desempenho e a segurança de nossos sistemas;
- Suportar as fases de desenvolvimento;
- Garantir a qualidade e a manutenção do código;
- Participar das etapas de análise e especificação;
- Criar, evoluir e dimensionar APIs;
- Liderar de projetos; Atuar no desenvolvimento de Sistemas em JavaScript e Banco de Dados MongoDB

## Ambiente de Trabalho:

- Dress code free;
- Flexibilidade de horário;
- Sala de descompressão com Playstation 5;
- Máquina Café, bebidas, salgados, doces (livre consumo);
- Happy Hour 1 vez por mês;

## Benefícios

- Vale Alimentação
- Vale Refeição
- Vale Transporte

## Contratação
PJ a combinar pretensão salarial

## Como se candidatar
**Por favor envie um email informando sua pretensão salarial para vagner.lemos@grupodreamwork.com.br com seu CV anexado - enviar no assunto: Vaga [São Paulo - SP] Desenvolvedor (a) JavaScript**

**Ou candidatar-se através do link: https://jobs.recrutei.com.br/grupo-dream-work/vacancy/8277-dw1070-desenvolvedor-a-javascript**

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
