### ISSUE TITLE
[ REMOTO ] Desenvolvedor Front end na [ Mirante Tecnologia ] 

### ISSUE THREAD

**Issue by LuanaXimenes** [frontendbr/vagas#5406]
Dev. Front End pleno 🚀

🎯 Skills obrigatórios:  
- Ferramentas de controle de versão (GIT, SVN e etc); 
- Gerenciador de dependência NPM; 
- JavaScript; 
- Redux (NGRX); 
- HTML 5; - CSS 3; 
- Angular 9+; 
- Testes automatizados;

💡 Atuação na maior cooperativa financeira do Brasil!

💻 100% home office e contratação CLT (a combinar) + benefícios 

 Envie o seu currículo para: luana.ximenes@mirante.net.br ou me chama no WhatsApp: 61 99623-3457

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
