### ISSUE TITLE
[Campinas-SP/Home Office] Analista Desenvolvedor Sênior na Kaffa

### ISSUE THREAD

**Issue by PriscilaSG** [frontendbr/vagas#5409]
## Nossa empresa

A Kaffa é uma empresa do grupo Imagem, especialista em soluções de mobilidade para o setor elétrico, seja no uso de recursos espaciais para a gestão de ativos ou no controle da execução de serviços em campo. Estamos em busca de profissionais para Desenvolvimento em várias senioridades a fim de somar no time para trabalhar em formato Home Office.

## Local

 Remoto 

## Requisitos

**Obrigatórios:**
•	Formação Superior na área  de Tecnologia da Informação;
•	Inglês Intermediário/avançado;
•	Experiência com duas ou mais das seguintes tecnologias: Java, Kotlin, Android, Node.js, React, SQL;
•	Análise Critica e capacidade em resolução de problemas;
•	Experiência com arquitetura de soluções;
•	Liderança de times de desenvolvimento de Softwares/Produtos.

**Desejáveis:**

•	Conhecimento em Node.Js, React e outros frameworks de mercado;
•	Experiência com integração contínua e TDD;
•	Experiência com Modelagem e consumo de APIs REST.

**Diferenciais:**
•	Experiência com desenvolvimento de soluções GIS;
•	Micro Serviços;
•	Banco NoSQL.

## Contratação

CLT

## Como se candidatar

Por favor envie um e-mail para rh@kaffa.com.br com seu CV anexado - enviar no assunto: Vaga Analista Desenvolvedor Sênior.

#### Alocação

- Remoto

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
