### ISSUE TITLE
[São Paulo] Front-End Developer na GSN Tecnologia

### ISSUE THREAD

**Issue by gsntecnologia** [frontendbr/vagas#541]
**Atividades:**
- Montagem de telas;
- Animação;

**Requisitos:**
- Angular 1;
- CSS;
- Landing pages.

**Local** - Zona Sul

 **Contratação** - PJ a combinar

**Nossa empresa**
Mais de 18 anos no mercado atuando com Desenvolvimento de Sistemas Web, Bodyshop e Hunting

**Como se candidatar**
Por favor envie um email para rh@gsn.com.br com seu CV anexado - enviar no assunto: Front-End

**Comment by clmadrazo** [comment]
aceita remoto?

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
