### ISSUE TITLE
[São Paulo/Remoto] Senior Fullstack Developer (React/GraphQL)

### ISSUE THREAD

**Issue by rhayasidajr** [frontendbr/vagas#5415]
> Vaga Remota durante a pandemia

## Nossa empresa

A LEGITI é uma startup criada por dois ex-alunos da Stanford University com grande expertise em big data e artiﬁcial intelligence, ambos com passagens bem sucedidas na Palantir Technologies. Estamos construindo a plataforma de fraude transacional mais eﬁcaz da América Latina, contando fortemente com arquitetura de dados de última geração, aplicativos serverless em um ambiente altamente disponível e escalável e técnicas avançadas em inteligência artiﬁcial.

## Descrição da vaga

Responsabilidades:
- Ser responsável pela arquitetura geral dos nossos Apps e APIs;
- Colaborar com Product Designer/Product Manager na deﬁnição de escopo, avaliação de viabilidade e esforço, e planejamento de novas features;
- Ser responsável pelo ciclo completo (desde o desenho arquitetural, passando pelo desenvolvimento em si, testes, deploy até o acompanhamento em produção) de novas features nos nossos Apps e APIs;
- Ser responsável pela observabilidade e monitoramento, com suporte do nosso time de SRE;
- Manutenção e melhoria das features existentes;
- Ser voz ativa no estabelecimento de melhores práticas e protocolos usados pelo time.

Mais informações: https://shorturl.at/kmoBV

## Local

Somos um time distribuído, portanto a posição é ﬂexível quanto a localização. Devido a pandemia do Covid-19,
estamos operando completamente remoto. Assim que as circunstâncias permitirem, voltaremos para presencial
opcional na sede da empresa, localizada em Pinheiros, São Paulo.

## Requisitos

**Obrigatórios:**

- Desenvolvimento de apps React (Typescript) (+3 anos de experiência)
- Desenvolvimento de APIs GraphQL (Node.js/MongoDB)
- Ferramentas de testes (Jest, React Testing Library)

**Diferenciais:**

- Experiência com monorepos (NX, Lerna)
- Interesse por UX/UI Design
- Experiência com Design Systems e Storybook
- Familiaridade com AWS (S3, Lambdas, Cognito) e Serverless

## Benefícios

- Plano de saúde e dental
- VA/VR
- Reembolso Cultural
- Reembolso Educacional
- Reembolvo Saúde Mental

## Contratação

CLT

## Como se candidatar

Por favor envie um email para roberto@legiti.com com seu LinkedIn ou CV anexado - enviar no assunto: Vaga Fullstack Sênior

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: roberto@legiti.com

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
