### ISSUE TITLE
[REMOTO]  DEV FULLSTACK - SÊNIOR na SOUTH SYSTEM

### ISSUE THREAD

**Issue by Ivone-Marchi** [frontendbr/vagas#5416]
## Nossa empresa

A South System está há 7 anos no mercado de tecnologia atuando com foco em Outsourcing em Projetos Fintechs que estão em transformações digitais. Recentemente recebemos o Selo GPTW como uma das melhores empresas para se trabalhar.

## Descrição da vaga

✳Conhecimentos e Habilidades em NODE utilizando React.js como Front 
✳Conhecimentos e Habilidades em Java para processos de BackEnd 
✳Conhecimentos e Habilidades em SQL para integração dos dados das bases da companhia par ao Projeto ao qual será alocado(a). 
✳Experiência com ferramentas de controle de versão e integração contínua (GIT)

## Local

Remoto

## Requisitos

**Obrigatórios:**

✳Experiência em NODE utilizando React.js como Front;
✳Experiência em Java para processos de BackEnd;
✳Experiência com SQL para integração dos dados das bases da companhia par ao Projeto ao qual será alocado(a). 
✳Experiência com Ferramentas de controle de versão e integração contínua (GIT)

**Desejáveis:**

✳Habilidades de conversação e direcionamento técnico para time mais júnior;

**Diferenciais:**

✳Avaliação de Performance;
✳Plano de Desenvolvimento Individual;
✳Feedbacks constantes;
✳Ambiente flexível e aberto inovações, sugestões para novas ideais e criatividade;
✳Horário Flexível;

## Benefícios

✳Ajuda de custo para montar seu Home Office;
✳Bônus ao completar 1 ano de empresa;
✳Parcerias exclusivas para nosso profissionais, por exemplo Udemy (+ de 4 mil cursos gratuitos), Vitalk (plataforma de saúde mental e acompanhamento psicológico, gratuito), Money Mind (Consultoria financeira gratuita)
✳Entre outros.

## Contratação

PJ ou Cooperado

## Como se candidatar

Por favor envie um email para ivone.marchi@southsystem.com.br com seu CV anexado - Enviar no assunto: Vaga FullStack Sr

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: ivone.marchi@southsystem.com.br

## Labels

- Senior
- Node
- Java
- React.js

#### Alocação
- Remoto

#### Regime
- Cooperado
- PJ

#### Nível
- Sênior
- Especialista

👀👀👀👀 Ah! E não esquece de dar uma olhadinha no nosso site https://lnkd.in/dZmrerD

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
