### ISSUE TITLE
[Rio de Janeiro] Front-end Developer na Fattoria

### ISSUE THREAD

**Issue by CarolPimentel** [frontendbr/vagas#5419]
> Vaga Remota durante a pandemia

> ## Descrição da vaga
> Se você busca uma vaga em Programação Front-End, busca constante desenvolvimento, e deseja participar de projetos web e mobile em campanhas diversas, envie o seu currículo!
> 
> ##Centro -Rio de janeiro
> 
> ## Benefícios
> * Plano de saúde e odontológico Golden Cross
> * Seguro de vida
> * Vale Refeição
> * Vale Transporte (após retomada presencial)
> 
> ## Requisitos
> Experiência mínima de 1 ano em:
> HTML
> CSS
> Javascript (Básico)
> JQuery (Básico)
> Muita vontade de aprender
> 
> **Diferenciais:**
> Experiência em Adobe XD ou Sketch
> Experiência com Node.JS
> Experiência com Angular, React ou Vue
> 
> ## Contratação
> CLT a combinar
> 
> ## Nossa empresa
> A Fattoria é uma empresa com conhecimento sólido do mercado digital.
> Atuamos da criação da marca, planejamento da campanha de marketing digital, outsourcing até o desenvolvimento de sistemas escaláveis e aplicativos mobile.
> 
> ## Como se candidatar
> Por favor envie um email para [rh@fattoriaweb.com.br](mailto:rh@fattoriaweb.com.br) com seu CV anexado, pretensão salarial e link do portfólio - enviar no assunto: Vaga Front-RJ
> 
> ## Tempo médio de feedbacks
> Costumamos enviar feedbacks em até 15 dias após a entrevista.

Boa sorte!!

**Comment by igorpinhh** [comment]
enviado!

**Comment by leorjr** [comment]
enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
