### ISSUE TITLE
[Remoto] Front-end Developer Angular Sr. na Solutis

### ISSUE THREAD

**Issue by fernandajesus** [frontendbr/vagas#5424]
**Responsabilidades e atribuições:**
Para mandar bem nessa oportunidade você precisa manjar das tecnologias:

Conhecimentos sólidos de arquitetura de software;
Sólido conhecimento em NodeJS;
Conhecimento Avançados em desenvolvimento Assíncrono e Baseado em eventos (Asynchronous and Event Driven)
Conhecimento de APIs RESTful;
Capacidade de produzir código limpo e de fácil manutenção;
Capacidade de se comunicar de forma concisa, franca e clara (também por escrito);

**O que aumentam suas chances**

Experiência com arquitetura de Microservicos;
Experiência com Expert e NextJs;
Experiência com Pattern BFF;
Experiência com metodologias ágeis (Scrum e Kanban);
Experiência com diferentes metodologias de desenvolvimento (DDD, TDD, BDD);
Contribuições em projetos open source;
Participação em comunidades de tecnologia com palestras e afins;

**Informações adicionais
﻿Para esta posição oferecemos:**

Salário CLT Full;
Vale Refeição ou Alimentação (Alelo);
Vale Transporte (sempre que houver o deslocamento);
Auxílio Home Office (proporcional aos dias em que atuará nesta modalidade);
Assistência Médica Sulamérica;
Assistência Odontológica Sulamérica;
Gympass;
Clube de benefícios Allya;
Seguro de Vida;
Parcerias (Curso de idiomas, ensino, livraria, restaurante);
Inside Out (Ocorre todas as sextas-feiras. Evento voltado para troca de conhecimento);
Oportunidade de crescimento profissional.

**Candidate-se**
https://solutis.gupy.io/jobs/1071003

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
