### ISSUE TITLE
[Remoto] Front-end Developer at ConsumerAffairs

### ISSUE THREAD

**Issue by amandavilela** [frontendbr/vagas#5425]
## Nossa empresa

ConsumerAffairs is a “managed marketplace” for life’s hardest purchases. Our mission is to help consumers make smart buying decisions in a moment of need.

Every month millions of consumers turn to ConsumerAffairs for help with their considered (often emotional), need-based purchases and we connect hundreds of thousands of them directly to brands. These brands use our SaaS tools to manage their reviews, their presence on ConsumerAffairs, communicate with consumers and generate revenue.

We are a diverse team located remotely across the U.S. and internationally. We are fast-paced and “GRIND-ing out” our core values: Generate Ownership, Resolve Through Data, Invent with Grit, Network to Win and Deliver Impact Daily.

## Descrição da vaga

The (Frontend) Software Engineer designs, builds and maintains seo-friendly, accessible, performant web apps using modern web technologies. They support multiple audiences including internal users, brands and consumers, and work in a small, cross-functional team to deliver value through regularly shipped code.

## Local

Remoto

## Requisitos

- 5+ years’ experience of HTML, SCSS and modern CSS
- 5+ years’ experience vanilla Javascript (not jQuery)
- Strong knowledge of version control (i.e. git, svn, etc.)
- Command of the english language (written and spoken)

_You are an expert in:_

- Clean, semantic HTML markup
- CSS pre-processing (e.g., SCSS and/or CSS post-processing)
- JavaScript, especially ES6 with OOP, and unit testing
- Git and GitHub
- Optimizing page load, animation and rendering performance
- Creating clean CSS with BEM methodology
- Consuming RESTful APIs
- Handling cross-browser and cross-device compatibility

_You have experience with:_

- SEO best-practices and implementation
- Responsive web development best practices
- Accessibility best practices and implementation
- Testing tools and unit testing
- Designing modular, object-oriented JavaScript
- The complete Software Development Life Cycle (e.g., planning, design, testing, releases, etc.)

_The ideal candidate would also have:_

- Experience with modern JavaScript tools (npm, webpack, yarn)
- Ability to work core working hours of 9am - 2pm CT (GMT-5)

## Contratação

Salary based in USD

## Como se candidatar

[Apply for this job](https://apply.workable.com/consumeraffairs-1/j/C6BA11EA2B/)

#### Alocação
- Remoto

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by amandavilela** [comment]
@felipefialho essa vaga é remota e a empresa não tem sede no Brasil, você poderia por favor remover a label `São Paulo`? Obrigada!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
