### ISSUE TITLE
[Remoto] Front-end Developer na Montebravo

### ISSUE THREAD

**Issue by BruDalmolin** [frontendbr/vagas#5427]
Nossa empresa
Somos o escritório número no G20 dos escritórios XP, uma Fintech em crescimento e expansão com muito espaço para crescer como liderança técnica e/ou gerencial, atuando em projetos novos e dinâmicos.

## Descrição da vaga

Requisitos:
- Conhecimento em HTML, CSS, Javascript
- Experiência com framework Angular versão acima de 8

Diferenciais:
- Projetos em Angular no Github
- Experiência com Scrum e Métodos Ágeis

Atividades:
- Irá trabalhar desenvolvendo novas features para sistema interno da empresa escrito em Angular

## Local
Remoto.

## Requisitos

**Obrigatórios:**
- 3 anos de experiência como Desenvolvedor Frontend
- 3 anos de experiência com Angular

## Benefícios

- Bônus semestral atrelado a performance
- R$ 1.000,00 no cartão VEE

## Contratação

PJ Associado

## Como se candidatar

Por favor envie um email para recruiter4@planuscarreiras.com.br com seu CV anexado - enviar no assunto: Vaga Frontend

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após cada processo.
E-mail para contato em caso de não haver resposta: recruiter@planuscarreiras.com.br

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
