### ISSUE TITLE
[Remoto] Front-end Developer Magento na Pasquali Solution

### ISSUE THREAD

**Issue by Recrutas** [frontendbr/vagas#5432]
**Descrição da vaga**
Estamos procurando pessoas que tenha uma vasta experiência em desenvolvimento Front-end com conceitos de Magento

**Local**
Remoto

**Requisitos**

Obrigatórios:
- HTML
- CSSJavaScript
- Magento PHP Front-end

**Desejáveis**
- Adobe Cloud/Commerce
- E-commerce Magento

**Contratação**

PJ

**Nossa empresa**
A Pasquali Solution é uma consultoria com foco em Alocação de profissionais de TI reconhecida pelo seu trabalho rápido e com excelência.
Estamos há mais de 18 anos no mercado e somos altamente especializada em Tecnologia da Informação.

•	Parceria com a Alura para cursos
•	Gratificação no mês de aniversário

**Como se candidatar**

Envie seu currículo https://cutt.ly/ubjZX1f
Envie seu currículo: danyela.silva@pasqualisolution.com.br

Labels
•	Alocado
•	PJ
•	Sênior

**Sobre a Pasquali**

A Pasquali Solution é uma consultoria com foco em Alocação de profissionais de TI reconhecida pelo seu trabalho rápido e com excelência.
Estamos há mais de 18 anos no mercado e somos altamente especializada em Tecnologia da Informação.
Vantagens
•	Parceria com a Alura para cursos
•	Gratificação no mês de aniversário

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
