### ISSUE TITLE
[Curitiba] Front-end Developer na Gazeta do Povo

### ISSUE THREAD

**Issue by AlexdeOliveiraSilva** [frontendbr/vagas#5435]
Estamos com uma oportunidade para desenvolvedor Front-end. 

A oportunidade é para participar de um time com o desafio de continuar evoluindo uma plataforma desenvolvida em nextJS utilizada milhares de usuários.

Descrição do cargo:

- Executar melhoria contínua no produto para atender ou exceder as especificações de disponibilidade, qualidade e experiência do usuário e d produto;
- Implementação de serviços utilizando nodeJS e react;
- Gerenciamento de banco de dados relacional;
- Auxiliar equipe no desenvolvimento de aplicações diversas

Competências desejadas:
- Autodidata e ser curioso, buscando sempre novas tecnologias e ideias, aprendendo rapidamente.
- Hands on foco em entrega e resolução de problemas, atrelado a alta capacidade técnica.
- Comunicação e trabalho em equipe

Desejável:
- Ensino superior completo
- Conhecimento em linux

Nível de experiência- Junior/Pleno

Tipo de contratação:
PJ

Carga horária:
40 horas semanais

Empresa localizada em Curitiba - PR

Para se candidatar utilize o formulário: https://forms.office.com/r/1Wq55hxdiy

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
