### ISSUE TITLE
[Remote] Software Engineer - Frontend at Voltz 🛵🔋

### ISSUE THREAD

**Issue by stanete** [frontendbr/vagas#5436]
## Vision 👀 

Redefine the mobility ecosystem to enable different models for insurance, credit, security & sustainability.

## Mission 🚩

Create a smart mobility ecosystem through smart electric vehicles and smart shared energy sources to achieve safe environments resulting in affordable prices, no pollution, lower finance interests and cheaper products with no maintenance.

## Why join us 🤔

Check [voltzmotors.com](https://voltzmotors.com/) to see what we've been doing until now. We are building a team from scratch and establishing a culture of operational excellence to learn through fast feedback loops focused on outcomes.

We value [product minded](https://blog.pragmaticengineer.com/the-product-minded-engineer/) people, [eXtreme programming](https://stanete.com/extreme-programming) principles and practices and a high collaborative DevOps culture.

We have huge challenges ahead. From creating new business models and empowering our operations teams to connecting thousands of electric motorbikes and harnessing the power of all that data.

To apply [go here](https://www.linkedin.com/jobs/view/2669258610/), write to me [directly on LinkedIn](https://www.linkedin.com/in/stanete/) or just [send me a DM on Twitter](https://twitter.com/stanete).

## What your day will be like 📅

You will explore, ideate and measure solutions in a collaboration with Product Designers and Product Managers.

You will design, build and deploy systems focused on quality and reliability. Testing, monitoring and observability are not optional.

You will improve the day to day processes, practices and systems to improve the team's engineering excellence.

You will have dedicated time to learn and help others learn. You will mentor other engineers to help them grow.

## What we are looking for 🔎

Strong expertise in Javascript or Typescript and experience with any modern frontend frameworks like React or Vue. Some knowledge about CSS frameworks like Tailwind is nice.

Some experience with modern frontend practices like web components, progressive web apps, server side rendering and static site generation.

Theoretical and practical background, ability and concern with technical excellence and good practices (TDD, pair programming, refactoring, design patterns, paradigms, etc.).

Familiarity working in a product team collaborating with Product Designers and Product Managers to investigate, ideate, design, build and measure iterative solutions that add value. 

Familiarity with the DevOps culture. You build it, you run it.

Pragmatism for problem-solving assuming every problem has a simple solution.

Structured communication based on facts and data.

 Excellent level of English; spoken and written.

## How to apply 🚀

To apply [go here](https://www.linkedin.com/jobs/view/2665883201/), write to me [directly on LinkedIn](https://www.linkedin.com/in/stanete/) or just [send me a DM on Twitter](https://twitter.com/stanete).

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
