### ISSUE TITLE
[São Paulo] Front-End Developer na [RADAR Profissional]

### ISSUE THREAD

**Issue by RADARProfissional** [frontendbr/vagas#544]
## Descrição da vaga

Vaga - Front-End Pleno, para atuação em cliente do segmento de tecnologia, especializada em plataformas web e mobile. Vaga fixa (não é projeto de tempo determinado). 
Grande possibilidade de plano de carreira.

## Local

Alphaville - SP

## Beneficio

15 dias de férias remuneradas ao ano.

## Requisitos

**Obrigatórios:**
- De 3 a 4 anos de experiência com Front-End
- Conhecimentos em HTML, CSS e JAVA SCRIPT; 

**Diferenciais:**
- HTML5, SPRITE e XSLT.

## Contratação

PJ salário a combinar

## Consultoria de Recrutamento e Seleção de Profissionais.
RADAR é uma consultoria de R&S e Alocação de Profissionais - A vaga é para atuar em cliente de segmento de tecnologia, especializado em desenvolvimento de plataformas web e mobile.

## Como se candidatar

Por favor envie um email para recrutadora@radarprofissional.com.br com CV anexo e pretensão salarial PJ.

**Comment by clmadrazo** [comment]
aceita remoto?

**Comment by RADARProfissional** [comment]
Para essa posição, infelizmente não.

 

 



 

Esta mensagem pode conter informações confidenciais e/ou privilegiadas. Se você não for o destinatário ou a pessoa autorizada a recebê-la, não pode usar, copiar ou divulgar as informações nela contidas ou tomar qualquer ação baseada nelas. Se você recebeu esta mensagem por engano, por favor, avise imediatamente o remetente, e em seguida, apague-a. Comunicações pela Internet não podem ser garantidas quanto à segurança ou inexistência de erros ou de vírus. O remetente, por esta razão, não aceita responsabilidade por qualquer erro ou omissão no contexto da mensagem decorrente da transmissão via Internet. "ECONOMIZE PAPEL - PENSE ANTES DE IMPRIMIR!"

 

De: Carlos Madrazo Reyes [mailto:notifications@github.com] 
Enviada em: quinta-feira, 14 de setembro de 2017 16:39
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: RADAR Profissional - Consultoria de Recrutamento & Seleção <cristiane@radarprofissional.com.br>; Author <author@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [São Paulo] Front-End Developer na [RADAR Profissional] (#544)

 

aceita remoto?

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by RADARProfissional** [comment]
fechado

 

 



 

Esta mensagem pode conter informações confidenciais e/ou privilegiadas. Se você não for o destinatário ou a pessoa autorizada a recebê-la, não pode usar, copiar ou divulgar as informações nela contidas ou tomar qualquer ação baseada nelas. Se você recebeu esta mensagem por engano, por favor, avise imediatamente o remetente, e em seguida, apague-a. Comunicações pela Internet não podem ser garantidas quanto à segurança ou inexistência de erros ou de vírus. O remetente, por esta razão, não aceita responsabilidade por qualquer erro ou omissão no contexto da mensagem decorrente da transmissão via Internet. "ECONOMIZE PAPEL - PENSE ANTES DE IMPRIMIR!"

 

De: Felipe Fialho [mailto:notifications@github.com] 
Enviada em: terça-feira, 23 de janeiro de 2018 14:10
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: RADAR Profissional - Consultoria de Recrutamento & Seleção <cristiane@radarprofissional.com.br>; Author <author@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [São Paulo] Front-End Developer na [RADAR Profissional] (#544)

 

Aberto ainda?
