### ISSUE TITLE
[Brasil Remoto] Front-end Developer na OLX Brasil

### ISSUE THREAD

**Issue by LuannaMiranda1** [frontendbr/vagas#5440]
## Nossa empresa
Quer fazer parte de uma das mais relevantes empresas 100% digitais do mercado brasileiro? Nós, da OLX Brasil, estamos de portas abertas para você.

Agora nós somos uma holding com duas business units (unidades de negócio): a OLX e o Zap+. Somamos nossa expertise em tech e produto para continuarmos desenvolvendo tecnologia feita em casa e nos tornando cada vez mais uma referência no segmento de anúncios online. Só nosso time de tecnologia conta com quase 400 pessoas com grandes desafios. Afinal, conectamos milhares de pessoas diariamente, com mais de 500 mil  anúncios publicados todos os dias, que recebem mais de 70 milhões de visitas por mês.

Se você gosta de aprender e quer fazer parte desse desafio, essa oportunidade é  a sua chance, Desenvolvedor(a) de Software, nessa posição você vai somar no time de Tecnologia. 

Na OLX entendemos que desenvolvimento de software vai além de programação. Buscamos pessoas que sejam apaixonados por tecnologia e entendam a importância de usarmos boas práticas (Engenharia de Software, Arquitetura, Algoritmos, Cultura Agil, etc) no desenvolvimento de um produto.

## Descrição da vaga
No seu dia a dia, você deve ir além dos códigos e trabalhar em conjunto com os demais times de engenharia para construir e manter produtos que colocam os nossos clientes no centro das decisões - que é o que nos diferenciam das demais empresas de tecnologia. Uma pessoa desenvolvedora  de sucesso na OLX Brasil, prima pela excelência do software, aliando o seu conhecimento técnico e experiência, com uma postura de dono(a) e um viés de ação. Você terá autonomia, mas com a responsabilidade de entregar um software que atenda um volume massivo de requisições, com alta disponibilidade e que gere um impacto ressonante para o nosso negócio. 

## Local
Remoto ou Escritório (São Paulo e Rio de Janeiro)

## Requisitos

**Obrigatórios:**
Experiência prévia com desenvolvimento de software front-end;
Conhecimento em arquitetura de software e boas práticas de desenvolvimento;
Conhecimento em JavaScript e DOM;
Atenção com a qualidade e padronização do código, garantindo legibilidade, escalabilidade e performance;
Capacidade de elaborar testes unitários e de integração;
Conhecimento em CI/CD com preprocessors, transpilers, bundles etc.

**Desejáveis:**
Vivência próxima com sistemas em produção e experiência em performance e testes A/B;
Conhecimento sobre semântica e SEO;
Conhecer BEM ou outras metodologias de organização de CSS;
Experiência prévia realizando testes e2e;
Ter experiência com algum framework SPA.

## Benefícios
- Assistência Médica e Odontológica
- Apoio Psicológico
- Atividades para o bem estar (aulas de yoga, meditação, ginástica laboral)
- Incentivo ao Esporte
- Day off de aniversário e tempo de casa
- Vale Refeição/Alimentação
- Previdência Privada
- Licença maternidade /adotante e paternidade/adotante estendida 
- Auxílio Criança
- Seguro de vida
- Assistência domiciliar
- Auxílio Home Office
- Desenvolvimento Financeiro
- Acesso a cursos gratuitos em parceiros como a Udemy
- Anuncio gratuito em nossas plataformas
- Vale transporte

## Contratação
CLT 

## Como se candidatar
Sua candidatura poderá ser realizada através do link: 
https://jobs.smartrecruiters.com/OLXBrasil/743999760133762-pessoa-desenvolvedora-de-software-front-end-olx-zap-

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 4 dias após cada processo.
E-mail para contato em caso de não haver resposta: luanna.miranda@olxbr.com

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by Gabri3el** [comment]
Enviei, vocês sempre passam o feedback do processo ?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
