### ISSUE TITLE
[Brasil Remoto] Front-End Developer na Smart Research

### ISSUE THREAD

**Issue by andersonmadeira** [frontendbr/vagas#5441]
## Nossa empresa

Somos uma startup de pesquisa de mercado e experiência de usuário e trabalhamos com projetos em todos os continentes do mundo. Fomos destacados recentemente na Acquisition International Magazine como melhor agência global de pesquisa de mercado da América Latina.

Estamos crescendo muito e buscamos por pessoas que amam tecnologia, versáteis e que pensam fora da caixa para compor nosso time de tecnologia.

## Descrição da vaga

Projeto relacionado diretamente a melhoria de experiência do usuário, frontend usando React. Um time pequeno que está crescendo e na fase de desenvolvimento do MVP. Algumas das principais atividades:

- Desenvolver interfaces web usando HTML, CSS e JavaScript
- Desenvolver componentes reutilizáveis usando React
- Criação de landing pages
- Apresentar e defender ideias para melhorias de interfaces do usuário

## Local

Remoto no Brasil

## Requisitos

**Obrigatórios:**

- HTML, CSS, JavaScript (ES6+)
- TypeScript
- React
- Redux
- CSS in JS: Emotion / Styled Components
- Storybook
- Testes com Jest (Testing Library ou Enzyme)
- Acessibilidade
- Consumir APIs REST

**Diferenciais:**

- GraphQL
- GitHub Actions
- AWS

## Benefícios

- Horário flexível
- Auxílio Home Office
- Vale Alimentação/Refeição
- Plano de Saúde

**Diferenciais:**

- Projeto muito inovador
- Horários realmente flexíveis

## Contratação

CLT, Tempo Integral

## Como se candidatar

Candidatar-se usando o LinkedIn: https://www.linkedin.com/jobs/view/2671339325/

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: ericapereira@smartmresearch.com

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
