### ISSUE TITLE
[São Paulo] Front-end Developer Jr na Intelipost

### ISSUE THREAD

**Issue by Pedro-IP** [frontendbr/vagas#5447]
> Vaga Remota 

## Desafios

Como Frontend Engineer os seus desafios serão:
- Desenvolvimento de aplicações web;
- Manutenção de sistemas para correção de falhas/erros;
- Construir uma base sólida para o desenvolvimento de novos produtos de forma ágil;
- Acompanhar a disponibilidade do nosso sistema, visando antecipar possíveis GAPs, aumentando assim, a confiabilidade da solução;
- Colaborar com outros membros da equipe, Engenheiros, PO, QA, Designers, Scrum Master e Tech Leader para resolver os desafios existentes.
- Desenvolver sistemas escaláveis, sustentáveis​​e orientadas ao usuário.

## Local

- Remoto 

## Requisitos

**Obrigatórios:**
- Graduação completa ou cursando em Tecnologia, Análise de Sistemas, Sistemas da Informação, Engenharia de Software ou cursos de áreas correlatas;
- Experiência com desenvolvimento de aplicações WEB, utilizando Vue.js, GraphQL, Typescript, CSS, HTML;
- Conhecimento básico de arquitetura de sistemas de alta escala e tolerância que rodem em ambiente AWS;

**Diferenciais:**
- Conhecimento em Backend para integração com a equipe.

## Benefícios

- Plano de saúde (para você e quem você ama);
- Plano odontológico; 
- TotalPass;
- Flexibilidade de horário (escolha entrar às 08h, 09h ou 10h);
- VR/VA Flex: R$ 630,00 (mês); 
- Auxílio Creche;
- PLR semestral;

## Contratação

CLT

## Como se candidatar

Por favor se cadastre pelo link: https://intelipost.gupy.io/jobs/1072362

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
