### ISSUE TITLE
[São Paulo] Front-End Developer no Portal R7.com

### ISSUE THREAD

**Issue by andersonrpinto** [frontendbr/vagas#545]
## Descrição da vaga

O R7.com está em busca de desenvolvedor Frontend com proficiência em HTML5, CSS3 e Javascript. Nossa equipe é multidisciplinar, com projetos envolvendo integrações de múltiplas aplicacões nas mais diversas linguagens e tecnologias. 

O profissional que buscamos deve ser dinâmico, pro-ativo, responsável, e acima de tudo com atitude positiva e paixão pelo que faz. 

## Local

Nosso escritório fica na Barra Funda, dentro da Record TV, ao lado da estação de metrô "Barra Funda" (linha vermelha).

## Benefícios

- Vaga CLT-FULL
- Plano de saúde
- VR de R$ 21,50 /dia
- VA de 106,00 / mês
- Férias

## Requisitos

* Experiência com HTML5, CSS3 e Javascript
* Trabalhar com sistemas UNIX
* HTML semântico
* Pré Processadores CSS (SASS/ Less/Stylus)
* Experiência com utilização de Libs de javascript (Jquery, underscore, lodash)
* Experiência com templates engines (underscore, mustache, handlebars)
* Experiência com Backbone, Angular ou React
* Boas noções de alguma linguagem backend (Ruby de preferência)
* Recortes em .psds 
* Task Runners (Grunt/ Gulp)
* Experiência com GIT e ambientes onde a integração contínua, automação de ambientes e releases é prioridade*
* Experiência com boas práticas de desenvolvimento
* Experiência com melhorias em peso e velocidade de carregamento das páginas desenvolvidas
* Inglês Técnico

**Diferenciais:**
* Performance de carregamento de páginas
* Teste unitário (Jasmine) 
* Teste funcional (selenium/nightwatch)
* Linguagem Backend (Ruby, Nodejs)

## Contratação

- Vaga CLT-FULL

## Nossa empresa

[R7.com](https://www.r7.com)

## Como se candidatar

Por favor envie um email para apinto@rederecord.com.br com seu CV anexado e pretensão salarial para vaga CLT - **enviar no assunto: Oportunidade Front-End**

**Comment by victorhcosta** [comment]
Aceita remoto?
Junior?

**Comment by LFeh** [comment]
Aberto ainda?
