### ISSUE TITLE
[remoto] Pessoa Desenvolvedora Fullstack PHP e JS – Pleno na Feedz

### ISSUE THREAD

**Issue by larissaaguiar** [frontendbr/vagas#5452]
🚀 A FEEDZ:
Nosso propósito é criar ambientes de trabalho mais felizes! Por isso, começar pelo nosso próprio ninho é tão importante! Somos Parrots determinados e que se importam uns com os outros, a sede de resultado é latente e o feedback sincero é rotina.

Aqui temos um ambiente de trabalho focado na cooperação entre Devs, confiamos no trabalho de nossos colaboradores e por isso acreditamos que nossos desenvolvedores devem ter autonomia!

Prezamos pela liberdade de falar o que se pensa e pelos feedbacks constantes, além de ter um time realmente diverso 💙 sabia que nosso time de produto é composto 42% por mulheres e 42% por pessoas negras?

Temos também flexibilidade de horários. Tem que ir ao banco? Precisa sair mais cedo para pegar os filhos na escola? Sem problema.

Estamos buscando uma pessoa para o cargo de Pessoa Desenvolvedora Fullstack Pleno(PHP e JS) que irá atuar no nosso time de Produto, dentro do squad de engajamento. Esse squad cuida de todos os módulos de engajamento dentro da nossa plataforma, como eNPS, pesquisas, termômetro de humor, gamificação, trazendo melhorias, correções e desenvolvimento de novas features.

📚 RESPONSABILIDADES E ATIVIDADES:
Desenvolvimento backend com PHP;
Desenvolvimento de frontend com CSS, HTML e JavaSccript(porém o foco é em backend);
Criar códigos coerentes, coesos, claros e alinhados ao Clean Code;
Aplicar boas práticas alinhadas com o time no desenvolvimento (desenvolvimento seguro, patterns, automação, etc);
Trabalhar com o desenvolvimento de módulos de engajamento de pessoas do software (eNPS, pesquisas, termômetro de humor, gamificação);
Desenvolvimento e aplicação de testes automatizados;
Desenvolvimento de API sob demanda;
Fazer a gestão da informação das demandas atualizando o status dos projetos.

🥇 PRÉ-REQUISITOS:
3 anos de experiência em desenvolvimento web com PHP;
3 anos de experiência em desenvolvimento web com Javascript, HTML, CSS;
Experiência com testes e API;
Estar trabalhando atualmente com as tecnologias de nossa stack;
Experiência com banco de dados relacional;
Gostar de trabalhar em time. Pessoa Desenvolvedora sozinha não faz verão!

🎯DIFERENCIAIS:
Ter trabalhado em empresas SaaS;
Ter trabalhado com empresas com mais de 10 mil usuários.

✨ BENEFÍCIOS:
Vale Comida (R$600)
Plano de Saúde com Coparticipação Unimed
Plano odontológico Nacional da Bradesco Dental
Auxílio Parrot Feliz (R$100/mês de investimento no desenvolvimento pessoal, saúde física ou mental do Parrot)
Auxílio Contas (R$80/mês)
Happy Bird(day) (um dia de folga no mês de aniversário)
Ifood Office

💰 SALÁRIO A COMBINAR (CLT)
Candidate-se em: https://enliztjob.app.link/XhsZDpfXtib

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
