### ISSUE TITLE
[Remoto] VTEX IO Front-end Developer na Performa_it

### ISSUE THREAD

**Issue by TacianySouza** [frontendbr/vagas#5456]
No tático, o Dev Front-end é a pessoa responsável por integrar e implementar layouts pixel perfect, tendo como pares o UX e o UI, além de integrar projetos em plataformas como VTEX, Drupal e outras, utilizando JavaScript puro ou abstrações e linguagens como NodeJS e React. 

 **Suas principais responsabilidades:** 
- Implementar layouts responsivos, aplicando os princípios de Mobile First quando necessário; 
- Realizar integrações usando as APIS da VTEX; 
- Criar códigos semânticos, levando em consideração os princípios de SEO e principalmente de Acessibilidade; 
- Trabalhar com GIT, utilizando Pull Requests para fazer avaliações e Coding Review dos pares. 

**Você precisa ter:** 
- JavaScript (ES6, NodeJS, React, JQuery, CoffeeScript) 
- VTEX  
- CSS (SASS) 
- HTML (Semântico, com princípios de acessibilidade e SEO aplicados) 
- Conhecer e usar testes unitários em seus projetos (usando qualquer framework ou biblioteca de testes conhecidos); 
- Profundos conhecimentos de JavaScript puro; 
- Integração com APIs via JS; 
- Produzir sites que sejam performáticos, priorizando carregamento e utilizando os princípios de performance de código; 
- Escrever código semântico e preparado para acessibilidade. 

**Você vai se destacar se tiver:**   
- Já contribuiu para projetos opensource; 
- Tem certificação VTEX; 
- Já trabalhou ou fez qualquer projeto (mesmo que seja um side-project) com VTEX-io; 
- Já trabalhou com NodeJS; 
- Já trabalhou em projetos usando React; 
- Já trabalhou em projetos usando Graphql. 

**Nós te oferecemos:**
- Convênio Médico (sem descontos)
- Ajuda de Custo R$600,00
- Descanso Remunerado 🏝
- Bônus Anual 💸
- Horário flexível 😎
- Jornada de 40h semanais 😍

Aqui você vivenciará uma cultura de desenvolvimento, dinâmico, colaborativo, gestão horizontal e com um ótimo relacionamento entre colegas e clientes.

E-mail para envio de CV: taciany.souza@performait.com
Assunto: VTEX IO

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
