### ISSUE TITLE
[São Paulo] Front-end Developer na Yube

### ISSUE THREAD

**Issue by Raffesmind** [frontendbr/vagas#546]
## Descrição da vaga

Queremos uma pessoa de nível Junior ou Pleno  para ajudar no desenvolvimento do Front da nossa aplicação, feita com React e Graphql (implementado com Apollo), ligando-a com um Backend desenvolvido com Elixir :) 

## Local

Escritório, São Paulo - Vila Olímpia
Rua Ministro Jesuíno Cardoso 454

#### Diferenciais

- Bônus na entrada para comprar ou dar um upgrade na sua máquina

## Requisitos

**Obrigatórios:**
- Conhecimento aplicado em Javascript, CSS3 e HTML5 (+2 anos de experiência)
- Desenvolvimento responsivo e sistemas de versionamento (Ex.: Github)

**Desejáveis:**
- Ter trabalhado com algum framework de javascript (:

**Diferenciais:**
- Ter aprendido e aplicado algo novo no último mês
- Ser capaz de trabalhar de forma livre e autônoma
- Tomar cerveja e discutir sobre fractais (figuras da geometria não-Euclidiana) ;)

## Contratação

PJ

## Nossa empresa

A Yube quer revolucionar a forma que a pessoa é contratada nas empresas, oferecendo uma plataforma de facilidades para que o candidato faça o processo sem burocracias ou papeladas!

## Como se candidatar

Por favor envie um email para vitor@yube.com.br com o link do seu Linkedin - enviar no assunto: Vaga Front-end na Yube

**Comment by Raffesmind** [comment]
As tags da vaga seriam Presencial, PJ, Junior e Pleno!
Caso algum candidato tenha dúvida, ou interesse ou queria saber mais, podem me chamar para conversar (:

**Comment by jadir-junior** [comment]
No caso de Apollo você quis dizer GraphQl né?

**Comment by Raffesmind** [comment]
Corretor @jadir-junior, estou corrigindo na descrição, valeu pelo toque :)

**Comment by LFeh** [comment]
Boa!
