### ISSUE TITLE
[Remoto][Curitiba] Front-end Developer Sênior na Contabilizei

### ISSUE THREAD

**Issue by contabilizei** [frontendbr/vagas#5466]
## Nossa empresa

Através da tecnologia, a [Contabilizei](https://www.linkedin.com/company/contabilizei/) está transformando a maneira como mais de 30 mil micro e pequenos empreendedores gerenciam o seu negócio no Brasil. Por aqui, continuamos a crescer rapidamente, criando novos produtos que proporcionam que o nosso cliente seja o contador de sua própria história.

Aqui na Contabilizei, as oportunidades são para todos! Queremos que você seja a melhor versão de si e se sinta bem onde estiver. Valorizamos as diferenças e temos um ambiente onde todos são mais que bem-vindos, independente de deficiência, gênero, etnia, orientação sexual, origem, entre outras diversidades, pois entendemos que JUNTOS construímos a Contabilizei do nosso jeito.

**Essa oportunidade permite trabalho totalmente remoto. :)**

## Descrição da vaga

**Responsabilidades e Atribuições**

Ao integrar o **Squad Aquisição**, você terá como missão, apoiar a área de Growth por meio da tecnologia em nosso site, blogs, landing pages de campanhas, construindo novos canais de aquisição e identificando oportunidades que direcionam as decisões do dia a dia, garantindo principalmente que os clientes tenham uma experiência encantadora com a Contabilizei desde a primeira interação.

**Um dia típico de um(a) Desenvolvedor(a) Front-end em nosso foguete inclui:**

- Desenhar a solução, desde a arquitetura, modelagem até o design de código;
- Entregar e revisar um código testável, assegurando qualidade das entregas da equipe;
- Identificar problemas e aplicar melhorias na base de código existente e de arquitetura;
- Idealizar sistemas e funcionalidades do lado do cliente (front-end);
- Projetar e construir componentes de aplicativos front-end;
- Apoiar no desenvolvimento técnico do time;
- Disseminar e compartilhar conhecimento com as comunidades interna e externa.

## Local

Totalmente Remoto ou Presencial/Híbrido em Curitiba/PR após a pandemia. 

## Requisitos e Qualificações

**Para nos ajudar a vencer a burocracia por meio da tecnologia, você precisa de:**

- **Graduação completa ou cursando em**: Análise de Sistemas, Engenharia da Computação ou áreas afins, **ou experiência equivalente.**
- **Javascript e framework** **Vue.js e/ou React** e bibliotecas de gerenciamento de estado global;
- **DevOps;**
- **Foco em UX:** 
- **Foco em Abordagens de Qualidade;**
- **Arquitetura de software;**
- **Arquitetura Web.**

**Pontos a mais se você possui vivência com:**

- Nuxt.js;
- WordPress;
- PHP;
- SEO;
- Web Analytics.

## Contratação

CLT

## Como se candidatar

Por favor, realize sua candidatura simplificada através da vaga no Linkedin: https://www.linkedin.com/jobs/view/2645782268

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.

#### Nível

Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
