### ISSUE TITLE
[São Paulo] Sr. Front-end/Full-stack Developer na Easy Carros

### ISSUE THREAD

**Issue by brunocramos** [frontendbr/vagas#547]
## Descrição da vaga

Buscamos profissionais ambiciosos para fazer parte do nosso time aqui na Easy Carros.
Estamos em um crescimento acelerado e, por isso, precisamos de pessoas dedicadas e excepcionais para trabalhar em nossos novos produtos.
Trabalhamos com React, React-Native, GraphQL, Node.js, GO, AWS, MongoDB, entre outros.

## Local

Escritório, São Paulo - Pinheiros

## Diferenciais

- Salário competitivo
- Possibilidade de equity (dependendo da senioridade)

## Requisitos

**Obrigatórios:**
- Experiência sólida e comprovada com Javascript
- Sólidos conhecimentos em HTML/CSS3, POO, Design Patterns, Sass, API RESTful, Git
- Experiência com ao menos uma da seguintes tecnologias: React, React-Native, Angular, GraphQL
- Bons conhecimentos em Redux
- Bons conhecimentos em MongoDB

**Desejáveis:**
- Conhecimento em GraphQL
- Conhecimento em Redux/Saga
- Conhecimento em testes unitários
- Ser formado em Ciência da Computação ou relacionados

**Diferenciais:**
- Conhecimentos sólidos em GraphQL, Redux/Saga
- Conhecimentos sólidos em React e React-Native
- For fluente em inglês
- Bons conhecimentos em AWS

## Contratação

PJ a combinar

## Nossa empresa

A Easy Carros está mudando a forma com que as pessoas se relacionam com seus veículos. Estamos no mercado há dois anos, já conquistando mais de 13 estados do Brasil e em forte expansão. Atuamos conectando nossos clientes aos melhores prestadores de serviço para os seus carros, como lavagem a seco, polimento, troca de óleo, etc, realizando o serviço na casa ou no trabalho. Também atendemos grandes frotas do Brasil, otimizando sua operação e controle sobre os veículos.

## Como se candidatar

Aplique em: https://easycarros.com/vagas/dev-full-stack

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by brunocramos** [comment]
@LFeh sim!

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
