### ISSUE TITLE
[Barcelona] Front-End Developer na Akuaro (CANCELADA)

### ISSUE THREAD

**Issue by italomouzinho** [frontendbr/vagas#548]
## Descrição da vaga

Buenas galera!

Sou consultor de posições de TI aqui em Barcelona e estou trabalhando com um cliente que oferece Sponsorship. 

Como sei da qualidade do nosso pessoal achei que seria interessante apresentar esta oportunidade por aqui.

_"We are busy disrupting the election industry by making voting more accessible, efficient, transparent and secure. We are continuously looking for talented individuals who will share our passion for designing and building great software that powers democracy around the world."_

Buscam um engenheiro FrontEnd para ajudar a desenvolver e otimizar aplicações robustas e seguras utillizadas por milhões de usuarios e realizar entrega de uma interface de alto nivel que permita que o voto seja mais acessivel e os processos eleitorais, mais eficientes.

## Local

Escritório sede em Barcelona, Espanha. 

## Benefícios

- Horário flexível: Entre 8 e 10 da manhã.
- Ticket restaurante
- Aulas de Ingles, Espanhol ou Francês.

#### Diferenciais

- **Visto de trabalho indefinido na Espanha (_sponsorship_)**
- **Trabalhar para um propósito real:** **impulsionar a democracia.**
- Empresa líder do mercado.
- Equipe talentosa com conhecimentos de classe mundial desenvolvendo aplicativos usados ​​por milhões de eleitores no mundo todo.
- Ambiente de trabalho internacional.
- Salario competitivo.
- Excelente localização no centro de Barcelona.

## Requisitos

**Obrigatórios:**
- Mestre em Javascript. Não só bibliotecas e frameworks. O bom, velho e poderoso Javascript!
- Experiencia com HTML5 e CSS3.
- Experiencia com GIT.
- Detalhista
- Conhecimentos de Padrões de projeto (Design patterns)
- 3-4 anos de experiencia com desenvolvimento de software.
- Inglês avançado/fluente
- Diploma em Ciencia da Computação ou equivalente.

**Desejáveis:**

- Experiencia com  AngularJS e Ionic.
- Experiencia com  Jasmine/Mocha, Grunt/Gulp, npm.
- Conhecimentos de Node.js.

**Diferenciais:**

- Experiencia com projetos críticos com systemas de alta carga e alta segurança.
- Experiencia com empresas e ou/projetos para o governo.
- Espanhol avançado/fluente

## Contratação

Contrato de trabalho fixo e indefinido. 
**Tem que ter disponibilidade para começar com eles entre o fim de dezembro e inicio de Janeiro.**

## Nossa empresa

A Scytl é líder mundial em soluções de votação eletrônica segura, gestão eleitoral e modernização de eleições. As nossas soluções incorporam protocolos criptográficos únicos que garantem segurança máxima, transparência e possibilidade de auditoria em todos os tipos de eleições. A tecnologia de segurança eleitoral inovadora da Scytl é protegida por patentes internacionais e permite às organizações realizar eletronicamente todos os tipos de processos eleitorais de forma totalmente segura e possível de auditoria, posicionando a empresa como líder global do setor.  

## Como se candidatar

Por favor envie um email para italo@akuaro.com com seu CV em **Inglês** anexado - enviar no assunto: Vaga FrontEndBR.

No corpo do email por favor mencione também, o melhor dia e horario para falarmos. (Entre 7h - 13h, Brasilia).

Abraços!

PS: Se não tiver a experiencia desejada eu vou te responder da mesma forma com um feedback mas não vou poder marcar uma conversa até o mes que vem. Não deixe de escrever no entanto porque será um prazer estar em contacto para o futuro.

**Comment by rodrigues882013** [comment]
Enviado.

**Comment by italomouzinho** [comment]
Esta on Hold ate Fevereiro 2018.

**Comment by italomouzinho** [comment]
A vaga continua em _Standby._

**Comment by kivervinicius** [comment]
Alguma possibilidade em contratação sem inglês fluente (somente inglês técnico)?

**Comment by italomouzinho** [comment]
Galerinha do mal, infelizmente a vaga foi cancelada. Talvez haja uma reorganizaçao no segunddo trimestre (sabem como sao estas coisas) mas por hora nao buscam mais. 

Se quiserem me add no [Linkedin ](linkedin.com/in/italomouzinho)a gente mantem contacto pra futuras oportunidades!
