### ISSUE TITLE
[REMOTO] Mobile Developer na Trinto

### ISSUE THREAD

**Issue by psirafaella** [frontendbr/vagas#5487]
## Mobile Developer 📲
CLT - Pleno

Atuação 100% remota e de início imediato na Trinto 💜

Funções e responsabilidades:                        
- Desenvolvimento mobile em React Native como parte do time para construção do app do Shop Samsung;
- Realização da programação do UX/UI do aprovado pelo cliente, conhecendo os controles necessários da tecnologia a ser configurada;
- Conhecimento avançado em React Native, fluência em JavaScript e versionamento de código (git).

Requisitos:
- Desenvolvimento mobile em React Native como parte do time para construção do app do Shop Samsung;
- Fluência em JavaScript;
- Versionamento de código (Git).

Tempo de experiência:
A partir de 2 anos atuando na área.

Conhecimentos técnicos:
GitHub, Jquery, Bootstrap, HTML, CSS, JavaScript, Google, W3C, PHP, .NET e React.                                                                                            
 
Nível de escolaridade: 
Desejável nível superior completo.

Benefícios:
- Plano de Desenvolvimento Individual (PDI) e acompanhamento de evolução mensal;
- Treinamentos e talks mensais para capacitação e desenvolvimento;
- Acesso à cursos online de marketing digital e tecnologia - Rock Content;  
- Possibilidade de participação em eventos e palestras junto ao Google e demais parceiros de negócio da Trinto;
- Vale refeição R$ 24,10 p/dia, disponibilizado em cartão de benefício flexível;
- Vale transporte (no momento estamos trabalhando no modelo remoto);
- 40h semanais (horário de segunda à sexta das 09h às 12h e das 13h às 18h);
- Notebook 24/7;
- Convênios de descontos (academia, psicoterapia, restaurantes, entre outros).

💰 Salário competitivo.

Gostou? 
Entre em contato direto através do meu e-mail: rafaella.silva@trinto.com.br.

Acesse também o nosso site para conhecer cases e clientes: www.trinto.com.br

Aguardo o seu contato! 😊

Vamos juntos! 🚀🚀

## Nossa empresa: 

A Trinto | Digital Partners faz parte do grupo CoreBiz, maior integradora de Omnichannel da América Latina e Most Valluable Partner do quadrante VTEX.

Somos globais e o nosso time conta com mais de 500 colaboradores e 150 clientes ativos em 40 países.

4 sedes de operação próprias:

- Rio de Janeiro
- São Paulo
- Franca
- Porto Alegre

Presença física em 5 países:

- Brasil
- Espanha
- México
- Argentina
- Chile

Acesse também o nosso site para conhecer cases e clientes: www.trinto.com.br

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
