### ISSUE TITLE
[Curitiba] Front-End Developer no EBANX

### ISSUE THREAD

**Issue by danielnass** [frontendbr/vagas#549]
![EBANX](https://ebanx-newsite-1-assets.s3.amazonaws.com/assets/ebanx-4fca78579628c614f393c05f93494dab66719087ec85438d458b7aa81bb6e280.svg)

Buscamos um [Front End Developer para trabalhar na nossa equipe de DEV](https://ebanx.recruiterbox.com/jobs/fk0mgkp/) (no centro de Curitiba, presencial, CLT) que seja expert em HTML, CSS, goste (muito) de Javascript, e que transforme layouts em experiências incríveis para os nossos clientes. O EBANX está cheio de desafios — temos 10+ projetos de alto impacto — e procuramos alguém com vontade de fazer acontecer, então se este é o seu momento, junte-se a nós!

### Além de Sonhar Grande, as suas atividades serão:

- Desenvolver um produto do zero, e/ou dar suporte para produtos já existentes;
- Trabalhar em conjunto com um time multidisciplinar (Design, Conteúdo, Back-end, e outros);
- Desenvolver landing pages, email marketing, interatividade e animações fluidas (User Interface), etc;
- Trabalhar em um ambiente diversificado e dinâmico que utiliza diferentes ferramentas e linguagens de programação;
- Tomar posse de projetos e fazer as coisas acontecerem;

### O que é indispensável para a vaga?

- Você deve ter uma boa experiência com JavaScript;
- Deve entregar uma página fiel ao layout e semanticamente correta;
- Você se sente confortável em usar ferramentas como Sketch ou Photoshop;
- Mobile First;
- Você tem um ótimo conhecimento em pre ou pós processadores CSS;
- Você é um viciado em browsers — Sempre busca aplicar a melhor experiência em todos os browsers;
- Experiência em Git (de preferencia GitHub);
- Ser curioso — Aplicar e entender métricas para melhorar os produtos do EBANX;
- Inglês;

### O que mais a gente adoraria ver?

- Conhecimento em frameworks/bibliotecas como: React, VueJS, Ember ou Angular;
- Habilidades em User Interface e/ou User Experience;
- Sabe como desenvolver um site com boas práticas de SEO;
- Inglês Avançado
- Que você tenha um bom espanhol - estamos expandindo para LatAm.

### O que oferecemos?

- Um ambiente de autonomia para crescimento e realizações;
- Escritório informal e descontraído - frutas e snacks saudáveis, chuveiros no escritório, uma Bulldog Francês que adora correr e morder (entre outros visitantes fofos), patinete, nerf, drones, nespressos e ótimas festas;
- Language Center: Inglês e Espanhol dentro do EBANX;
- WAVES - Programa de Objetivos e Resultados Chave;
- EBANX Education - Até R$300/mês;
- EBANX Play - Bem Estar e Performance (Gympass, e-Sports, SESC);
- Horário Semi-Flexível (8 horas de segunda à sexta);
- Plano de Saúde e Odontológico Bradesco Top Nacional;
- Vale Refeição;
- Vale Transporte.
 
### Quem somos

O EBANX é um grupo financeiro global com atitude do Vale do Silício. A gente acredita que todas as pessoas devem ter o poder de escolher e de chegar mais longe. Por isso, colocamos meios de pagamento locais e seguros (boleto bancário, transferências, cartões de crédito nacionais) nos principais sites do mundo. Somos líderes no Brasil e estamos conquistando a América Latina. Tudo para que as pessoas tenham acesso ao que desejam sem burocracia, sem preocupação e sem sair de casa.

Já alcançamos mais de 24.000.000 de consumidores finais, temos empresas como AirBnB, Spotify, AliExpress, PlayStation, Wish.com trabalhando com a gente .

Para saber um pouco mais, veja a nossa [Career Page](http://www.ebanx.com/br/carreiras) e procure as fotos tiradas pelos ebankers no nosso [Instagram](https://www.instagram.com/ebanxlife/) - #ebanxlife.

Come join us! Se inscreva pelo link ~> [https://ebanx.recruiterbox.com/jobs/fk0mgkp/](https://ebanx.recruiterbox.com/jobs/fk0mgkp/)

**Comment by raloliver** [comment]
olho pra essa vaga e apenas sonho...

**Comment by netstart** [comment]
Ainda usam o hackerrank como ferramenta de avaliação?
Aquilo é chato d+ e muito longe do que se faz no dia a dia na vida real.

**Comment by ebanxdevtests** [comment]
@netstart a primeira etapa sim, na segunda etapa agora temos um projeto 😄

**Comment by JCMais** [comment]
Ebanx é uma excelente oportunidade, boa sorte para quem se candidatar.

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
