### ISSUE TITLE
[Remoto] Front-end Developer na HST Card Technology

### ISSUE THREAD

**Issue by DaniAbade** [frontendbr/vagas#5494]
## Nossa empresa

**Somos protagonistas na transformação digital dos meios de pagamento, somos a HST!** 

Desvendamos os desafios mais complexos e desde a nossa fundação temos a **missão de tornar as transações eletrônicas mais seguras.**

Estamos presentes em **+18 Países** e, dentre os nossos Clientes, estão os **10 Bancos mais importantes do Brasil e da América Latina**! 

São +50.000 terminais de autoatendimento; +1.000.000 autenticações de transações de compras eletrônicas ao mês; +800.000 cartões bancários com chip disponibilizados ao mês em lojas e agências bancárias; e só em 2020, foram +40 bancos utilizando nossa wallet digital e sistemas de emissor que permitem a tokenização de cartões Cof (Card on File) e eCommerce. Isso é só uma parte dos nossos resultados, mas também é só começo!  

Nos bastidores de todas as nossas conquistas está o nosso Time, que conta com **+150 Pessoas envolvidas no desenvolvimento das nossas soluções**. Pessoas questionadoras, curiosas, criativas, proativas, colaborativas e abertas a novas experiências!

## Descrição da vaga

**Buscamos Front-end Developer para se unir ao nosso time de Development para:**
- Atuar no desenvolvimento front-end de aplicações para soluções de emissão de cartão;
- Definir a arquitetura de sistemas, desenvolvendo nossos Produtos e Soluções atendendo aos requisitos e especificações estabelecidos;
- Identificar e corrigir vulnerabilidades nos Produtos, provendo suporte para ocorrências reportadas pelos Círculos de Operations e Products;
- Promover a evolução tecnológica, através de pesquisa e desenvolvimento de novas tecnologias;
- Contribuir para difundir os conhecimentos técnicos dos Produtos e das tecnologias utilizadas.

## Local

Remoto ou Escritório [SP-Campinas-Bairro Guanabara]

## Requisitos

**Obrigatórios:**
- Técnico completo, Superior completo ou cursando;
- Lógica de Programação, com códigos que sejam legíveis e passíveis de manutenção;
- Experiência na área de desenvolvimento de software utilizando React.js, CSS e JavaScript.

**Desejáveis:**
- Vivência em Arquitetura de Microsserviços;
- Conhecimento em linguagem SQL (PostgreSQL, Oracle e/ou SQLServer).
- Atuação com times multidisciplinares utilizando metodologia ágil;
- Conhecimento de produtos, ou com os conceitos relacionados a meios de pagamento.

## Benefícios

A HST é uma empresa certificada GPTW! Temos um ambiente flexível, permitindo que os nossos colaboradores escolham se querem trabalhar do escritório com um ambiente que inspira colaboração, 100% remoto, ou ainda alguns dias no escritório e outros dias remoto. 

-Contratações em regime CLT;
-Horário flexível;
-Oportunidade de crescimento, através do contínuo desenvolvimento, tanto técnico quanto pessoal;
-Temos programas de desenvolvimento destinado às novas lideranças;
-10% das horas mensais, podem ser dedicadas para aprender algo novo;
-Plataforma de cursos on-line (Alura);
-Day-Off no mês do aniversário;
-Auxílio Home-Office;
-Participação nos Lucros e Resultados;
-Gympass;
-Programa de Assistência ao Empregado (inclui assistência psicológica, orientação jurídica, consultoria financeira e serviço social, com atendimento telefônico).
-Convênio médico;
-Convênio odontológico;
-Vale Alimentação/Refeição;
-Vale Transporte ou estacionamento;
-Auxílio Creche;
-Seguro de Vida.

## Contratação

CLT 

## Como se candidatar

Por favor envie um e-mail para vagas@hst.com.br com seu CV anexado - enviar no assunto: Vaga Front-End

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.
E-mail para contato em caso de não haver resposta: daniela_abade@hst.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
