### ISSUE TITLE
[Remoto] Front-end Developer Analista Desenvolvedor Pleno na Imagem Geosistemas

### ISSUE THREAD

**Issue by luanasantosog** [frontendbr/vagas#5496]
## Nossa empresa

A Imagem Geosistemas faz parte do Grupo Imagem. Somos uma empresa brasileira de tecnologia líder em Sistemas de Informações Geográficas, distribuidora oficial no Brasil da plataforma ArcGIS, da norte-americana Esri.

## Descrição da vaga

Experiência trabalhando com serviços restfull e microserviços;
Html5, CSS3, node.js, angular, vue e react;
Python e JavaScript;.
SQL e Análise de Dados;
Vivência em metodologias ágeis.

## Local

Remoto

## Requisitos

- Graduação completa em Ciência ou Engenharia da Computação, ou área relacionada a TI.

**Desejáveis:**
- Conhecimento na plataforma ArcGIS.

## Contratação

CLT a combinar

## Como se candidatar

Interessados e dentro do perfil, enviar currículo atualizado, e pretensão salarial para recrutamento@img.com.br informando
no assunto Analista Desenvolvedor Pleno - Github

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
