### ISSUE TITLE
[Remoto] Front-end Developer na YEZO

### ISSUE THREAD

**Issue by yezocapitale** [frontendbr/vagas#5497]
> Vaga Remota 

## Nossa empresa
Somos um empresa de tecnologia, jovem, dinâmica e a procura de pessoas do bem, esforçadas e que queiram crescer junto com a gente!

## Descrição da vaga

Estamos a procura de um desenvolvedor Front-end, que tenha experiência em:

- Desenvolvimento Web com VUEJS, VUEX, BOOTSTRAP, HTML, CSS e Java Script.

- Metodologia Agil - Scrum

- Azure Devops (diferencial)

## Local

Exemplo: Remoto 

## Requisitos

**Obrigatórios:**

-  Experiência em Desenvolvimento Web com VUEJS, VUEX, BOOTSTRAP, HTML, CSS e Java Script.

- Metodologia Agil - Scrum

- Azure Devops (diferencial)

## Contratação

CLT ou PJ a combinar

## Como se candidatar

Por favor envie um email para TALENTO@YEZO.COM.BR com seu CV anexado - enviar no assunto: Vaga FRONT

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
