### ISSUE TITLE
[Rio de Janeiro] Front-End - Estágio/Jr.

### ISSUE THREAD

**Issue by nathaliabruno** [frontendbr/vagas#55]
## Descrição da vaga

Estamos procurando umx estagiárix ou júnior para desenvolvimento front-end afim de encarar uns desafios legais e dispostx a aprender muita coisa com uma equipe gente boa e paciente. =P
## Local

TUUT - Ipanema - RJ
## Benefícios
- Bolsa auxílio
- VT
## Requisitos

**Obrigatórios:**
- Ter atenção aos detalhes(saber respeitar o layout);
- Sacar um pouco de jQuery;
- Experiência com WordPress (desenvolvimento de temas);
- Já ter usado Git;
- PHP e MySQL(para WordPress);
- Queremos alguém com disposição e muita vontade de aprender!

**Diferenciais:**
- Pré-processadores CSS (preferência por SASS);
- Task runners (preferência por Gulp);
- AJAX;
## Contratação

Estágio ou PJ com possibilidade de entrar no contrato social da empresa(sócio).
## Nossa empresa

Um lugar de ideias e de ação, onde estratégia e criatividade andam juntas. http://tuut.com.br
## Como se candidatar

Por favor envie um email para nathalia.bruno@tuut.com.br com seu CV || Linkedin && Portfolio || Links de Jobs (pode ser acadêmico). Fala um pouco de você no e-mail, me diz porque eu devo contratar você ;) - enviar no assunto: Vaga Front-End.

**Comment by LFeh** [comment]
\o

**Comment by eduardojmatos** [comment]
@nathaliabruno a vaga já foi preenchida? Já podemos retirar ou mantemos por aqui?
