### ISSUE TITLE
[Campinas/SP] ou [Maringá/PR] - Front-End Developer na MATERA Systems

### ISSUE THREAD

**Issue by gss-patricia** [frontendbr/vagas#550]
## Descrição da vaga
Precisamos de front-end developers Jr / Pl / Sr para a <a href="http://www.matera.com/br/" target="_blank">MATERA Systems</a>, para atuar com análise e desenvolvimento de Front-end em projetos para clientes internos e externos.

## Local
- Campinas, São Paulo -  Parque II do Polo de Alta Tecnologia;
- Maringá, Paraná - Novo Centro (Zona 07).

## Benefícios
- Horário de trabalho flexível (40 h semanais);
- Pacote de Benefícios Flexíveis + PLR (Plano de participação nos lucros e resultados).

## Requisitos
**Obrigatórios:**
- Experiência com XML/HTML/CSS/JavaScript;
- Experiência Angular e Ionic 3+;
- Inglês avançado/fluente (se internacional);
- Disponibilidade para eventuais viagens (nacionais e internacionais);
- Flexibilidade para se adaptar a novas tecnologias.

**Desejáveis:**
- Experiência NodeJS;
- Testes Unitários; 
- Familiaridade com SVN, Git e com ferramentas como Jira, Confluence, Jenkins e Stash;
- Conhecimento em Scrum.

**Diferenciais:**
- Projetos opensource;
- Conhecimento de Java e serviços REST.

## Contratação

CLT

## Nossa empresa

A MATERA Systems, desde 1987, atua como fornecedora de soluções e serviços de TI para o mercado financeiro e corporativo, além de realizar o desenvolvimento de aplicativos e projetos. São marcas registradas da empresa investir constantemente em inovação e capacitação de seus profissionais e aliar a excelência técnica ao conhecimento de negócios. Possui mais de 400 profissionais e desde 2008 está no ranking da GPTW. Sedes: Campinas­ - SP, São Paulo - ­SP, Niterói - ­RJ e Maringá­ - PR

## Como se candidatar

Por favor envie um email para recrutamento@matera.com com seu CV anexado - enviar no assunto: Vaga Front-End Developer.

**Comment by vinirossi** [comment]
Boa noite @gss-patricia teria uma vaga e estágio front-end? Não manjo de tudo que está ai. Nem para júnior eu consigo.

**Comment by gss-patricia** [comment]
Bom dia @vinirossi, blz?
Para Front-End não temos previsão ainda de estagio.
Mas temos em aberto essa vaga:
http://www.matera.com/cv/vaga/vaga.xhtml?id=1861
[]'s

**Comment by degaus** [comment]
@gss-patricia quem não tem a Formação Acadêmica , mas tem o conhecimento pode se candidatar para a vaga de UX / UI?

**Comment by gss-patricia** [comment]
Olá @degaus, a vaga é para estágio, então precisa estar cursando superior.

**Comment by degaus** [comment]
A sim , obrigado! @gss-patricia

**Comment by gabrielferreiraa** [comment]
@gss-patricia não há interesse por remoto?

**Comment by gss-patricia** [comment]
@gabrielferreiraa, temos alguns remotos, temos interesse sim!

**Comment by gss-patricia** [comment]
@gabrielferreiraa, temos alguns remotos, temos interesse sim!

**Comment by vinirossi** [comment]
@gss-patricia Boa noite Patricia, currículo enviado para vaga estágio, Muito obrigado pela dica.

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by gss-patricia** [comment]
Feshow! Tks, vou finalizar!
