### ISSUE TITLE
[Remoto] Front-end Developer Angular/JavaScript na Tivix

### ISSUE THREAD

**Issue by guilehm** [frontendbr/vagas#5501]
## Nossa empresa

Somos uma consultoria global de software, com uma equipe de mais de 90 pessoas, com sede no Vale do Silício (São Francisco) e outros escritórios em Nova York, Portland, Wroclaw e Londres.

A paixão de nossa equipe se manifesta em cada envolvimento com o cliente. Nossos clientes são uma mistura de novos empreendimentos, marcas da Fortune 500 e ONGs inovadoras em uma variedade de setores. Trabalhamos com diferentes tecnologias e temos muitas oportunidades de aprender.

## Descrição da vaga

Front-end Developer - Angular/JavaScript.

Queremos outro membro-chave na equipe de engenharia, para trabalhar próximo de nosso time e clientes, para entregarmos produtos de alta qualidade.

Trabalhamos bem com pessoas que aprendem continuamente e que levam o profissionalismo a sério (enquanto se divertem).

## Local

Remoto

## Requisitos

**Obrigatórios:**
Mínio de dois anos de experiência em:
- Javascript / ES6
- Angular. React / Vue / Svelte é um plus
- Consumir APIs REST e transpiladores ES2015+
- Design patterns
- Pré-processadores CSS

**Desejáveis:**
- Experiência em testes automatizados como Cypress ou similares
- Testes unitários
- Contribuições em projetos open-source
- Graduação em Ciências da Computação ou àreas correlatas

## Benefícios

- Reembolso de celular
- Reembolso de internet

## Como se candidatar

Se candidatar na vaga através deste [link](https://jobs.lever.co/tivix/48921a78-a55a-4c6c-8d9d-c5e7e6589342?lever-origin=applied&lever-source%5B%5D=vagas).

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
