### ISSUE TITLE
[São Paulo] Front-End Developer na Kunumi

### ISSUE THREAD

**Issue by vFragosop** [frontendbr/vagas#551]
## Descrição da vaga

Estamos em busca de um desenvolvedor front-end com espírito de equipe, pró-ativo, hands-on e que queria trabalhar com tecnologia de ponta em produtos de inteligência artificial.

## Local

Escritório, São Paulo - Vila Madalena

## Benefícios

- Horários flexíveis
- Home office alguns dias da semana
- Vale refeição
- Vale transporte
- Estacionamento no local

#### Diferenciais

- Ambiente informal e sem dress-code
- Escritório em uma casa com jardim e pôr-do-sol garantido
- No coração de um dos bairros mais bacanas de SP
- Bastante café, frutas e cerveja (ocasional)
- Pode trazer seu pet

## Requisitos

**Obrigatórios:**
- Sólidos conhecimentos de UI/UX
- Frameworks CSS (UIKit, Bootstrap, Foundation ou Semantic UI)
- Frameworks SPA (Vue, React, Angular ou Polymer)
- Ferramental Node.JS (NPM, Webpack, Browserify, Grunt/Gulp)
- Conhecimentos de ECMA6 ou TypeScript

**Desejáveis:**
- Experiência com liderança de times
- Experiência com metodologias ágeis
- Testes de aceitação/funcionais (Webdriver, Selenium, Nightwatch)
- Testes de integração/unitários (Karma, Mocha, Chai, Jasmine)
- Libraries gráficas (D3.js, Raphaël, Two.js ou Three.js)

**Diferenciais:**
- Linguagens da JVM (Java, Kotlin ou Scala)
- Linguagens dinâmicas (PHP, Ruby, Python)
- Frameworks MVC (Play, Laravel, Ruby on Rails)

## Contratação

CLT. Salário a combinar.

## Nossa empresa

A Kunumi é uma empresa que usa o estado-da-arte em inteligência artificial para fazer previsões em negócios, saúde e cidades. É uma empresa brasileira, com atuação global. Kunumi significa 'criança' em tupi guarani. Para mais informações consulte o [nosso site](http://www.kunumi.com/). Também pode nos encontrar no [LinkedIn](https://www.linkedin.com/company/10452401/) e no [Facebook](https://www.facebook.com/kunumilab/).

A equipe de engenharia da Kunumi recebe cada vez mais desafios. Estamos em contato com diversas áreas e podemos presenciar e aprender com profissionais que transbordam conhecimento. Nos envolvemos em trabalhos que vão de seguros e construção civil, até a medicina, acompanhados pelos mais experientes especialistas da área. O espírito de coletividade é o que mais se destaca. Todos crescemos juntos, aprendemos e compartilhamos o que sabemos para produzirmos com mais qualidade aquilo que gostamos, concordando com o lema da empresa: "Juntos, com propósito e elegância!"

## Como se candidatar

Por favor envie um email para vinicius@kunumi.com com seu CV anexado.
Enviar no assunto: `Vaga Front-End`.

**Comment by Edipoesn** [comment]
@vFragosop, boa tarde!

Qual nível?

**Comment by vFragosop** [comment]
@Edipoesn pleno para sênior, apto para trabalhar sem supervisão e/ou liderando time.

**Comment by Edipoesn** [comment]
@vFragosop,

Entendi.

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by vFragosop** [comment]
@LFeh , na verdade até temos uma vaga em aberto ainda, mas essa Issue deve estar nas últimas páginas e ninguém mais envia currículo.

Vamos conversar aqui sobre a possibilidade de abrir uma nova vaga. @wcmjunior, @jjviana ^
