### ISSUE TITLE
[REMOTO] Front-end Developer na DietSystem

### ISSUE THREAD

**Issue by thiagoferreira123** [frontendbr/vagas#5514]
## Nossa empresa

O DietSystem é software voltado para profissionais da saúde, somos uma pequena startup com um grande potencial de crescimento. 

## Descrição da vaga

Se você nunca teve a oportunidade de trabalho, pelo fato de não ter nenhuma experiência comprovada com uma empresa de verdade, venha aprender a com a gente!

## Requisitos

- Conhecimento básico em JavaScript
- Conhecimento básico em HTML
- Conhecimento básico em CSS
- Conhecimento básico em site responsivo.

## Benefícios

- Aprendizado
- Possível contratação no futuro
- Indicação para outras empresas

## Como se candidatar

Por favor envie um e-mail para nutricionistathiagoferreira@gmail.com com seu CV anexado - enviar no assunto: Vaga de estágio DietSystem

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Nível
- Estudante 
- Junior

**Comment by matheusmcz** [comment]
Acho um vacilo anunciar a vaga como Júnior, mas na descrição de contratação informar "Estágio (Possível remuneração e contratação futura como CLT ou PJ)"...

**Comment by thiagoferreira123** [comment]
> Acho um vacilo anunciar a vaga como Júnior, mas na descrição de contratação informar "Estágio (Possível remuneração e contratação futura como CLT ou PJ)"...

**Comment by thiagoferreira123** [comment]
> Acho um vacilo anunciar a vaga como Júnior, mas na descrição de contratação informar "Estágio (Possível remuneração e contratação futura como CLT ou PJ)"...

Olá amigo, a vaga está anunciada é para estágio, quem tem interesse em aprender,, a tag de Junior é automática! E sim, já contratamos estagiários que se encaixaram na filosofia da empresa. Abraços!

**Comment by thiagoferreira123** [comment]
> ## Nossa empresa
> O DietSystem é software voltado para profissionais da saúde, somos uma pequena startup com um grande potencial de crescimento.
> 
> ## Descrição da vaga
> Se você nunca teve a oportunidade de trabalho, pelo fato de não ter nenhuma experiência comprovada com uma empresa de verdade, venha aprender a com a gente!
> 
> ## Requisitos
> * Conhecimento básico em JavaScript
> * Conhecimento básico em HTML
> * Conhecimento básico em CSS
> * Conhecimento básico em site responsivo.
> 
> ## Benefícios
> * Aprendizado
> * Possível contratação
> 
> ## Contratação
> * Estágio
> 
> ## Como se candidatar
> Por favor envie um e-mail para [nutricionistathiagoferreira@gmail.com](mailto:nutricionistathiagoferreira@gmail.com) com seu CV anexado - enviar no assunto: Vaga de estágio DietSystem
> 
> ## Tempo médio de feedbacks
> Costumamos enviar feedbacks em até 2 dias após cada processo.
> 
> #### Nível
> * Júnior



> ## Nossa empresa
> O DietSystem é software voltado para profissionais da saúde, somos uma pequena startup com um grande potencial de crescimento.
> 
> ## Descrição da vaga
> Se você nunca teve a oportunidade de trabalho, pelo fato de não ter nenhuma experiência comprovada com uma empresa de verdade, venha aprender a com a gente!
> 
> ## Requisitos
> * Conhecimento básico em JavaScript
> * Conhecimento básico em HTML
> * Conhecimento básico em CSS
> * Conhecimento básico em site responsivo.
> 
> ## Benefícios
> * Aprendizado
> * Possível contratação
> 
> ## Contratação
> * Estágio
> 
> ## Como se candidatar
> Por favor envie um e-mail para [nutricionistathiagoferreira@gmail.com](mailto:nutricionistathiagoferreira@gmail.com) com seu CV anexado - enviar no assunto: Vaga de estágio DietSystem
> 
> ## Tempo médio de feedbacks
> Costumamos enviar feedbacks em até 2 dias após cada processo.
> 
> #### Nível
> * Júnior

**Comment by diasbala** [comment]
enviado! obrigado pela oportunidade de inscrição

**Comment by nicolemachado** [comment]
Enviado :D

**Comment by fffilipi** [comment]
#enviado

**Comment by hmarcio143** [comment]
Enviado

**Comment by AndersonMoura333** [comment]
Enviado :P

**Comment by KayPina** [comment]
Enviado

**Comment by daniszcode** [comment]
Enviado!

**Comment by othongonzaga** [comment]
Enviado!

**Comment by Leandra1** [comment]
Ainda está aberto?
