### ISSUE TITLE
[São Paulo ou 100% Remoto] Front-End Developer - React  na Enki Labs

### ISSUE THREAD

**Issue by Odare** [frontendbr/vagas#5517]
## Nossa empresa

Aqui na Enki Labs desenvolvemos sistemas para comunicação de atendimento. 
Se você procura um lugar onde você quer ser ouvido, tem um pessoal legal, e uma equipe parceira. Vem falar com a gente.

## Descrição da vaga

Arquitetar e Desenvolver a parte front-end da nossa plataforma de serviço SaaS, juntamente com equipe multidisciplinar.

## Local

Remoto, ou na Al Santos em São Paulo

## Requisitos

**Obrigatórios:**
- HTML/CSS (Ou expansões como SCSS)
- Javascript
- Typescript
- React
- Redux
- SPA (Single Page Application)
- Automação de testes
- Builders (WebPack)
- Comunicação com APIs (REST/Json)
- Orientação Objetos + SOLID
- Versionamento de código (Usamos Git)
- Inglês (Código em inglês)

## Benefícios

- Férias remuneradas

## Contratação

PJ a partir de R$5.000,00 a R$13.000,00(de acordo com a sua experiência)

## Como se candidatar

Por favor envie um email para vagas[arroba]encontact.com.br com seu CV anexado - enviar no assunto: Front-End Developer - React

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: atendimento[arroba]encontact.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
