### ISSUE TITLE
[São José dos Campos/SP] Front-End Developer na Focusnetworks

### ISSUE THREAD

**Issue by danilovaz** [frontendbr/vagas#552]
## Descrição da vaga

As pessoas que passarem na vaga, atuarão em projetos de uma das nossas unidades de negócio a: [Interactive](http://interactive.focusnetworks.com.br/). Estarão alocados dentro das empresas de nossos clientes. Nossa atual stack é Angular 1.x (seguindo os padrões do John Papa), porém, para nossos novos projetos serão em [Ember.js](https://emberjs.com/). Somos um time ágil, prezamos por testes automatizados de código garantindo no mínimo 80% de cobertura. Então vivência com testes é desejável. Não precisa necessariamente de experiência com Ember, mas é essencial entender as bases e essência do JavaScript. Você trabalhará com outros integrantes: UI/UX, Back-End, QA, Scrum.

## Local

Escritório da empresa: Av. Cassiano Ricardo, 601 - Ed. The One - 12.andar, São José dos Campos - Jd. Aquárius

## Benefícios

- Bônus por indicação de outros profissionais;
- Academia (R$ 45,00)
- Auxílio creche
- DayOff (tire 1 dia de descanso no mês do seu aniversário)
- Convênio médico e odontológico (50% para a pessoa e dependentes)
- Subsídio para estudos
- VT
- VR (R$ 440,00)

## Requisitos

**Obrigatórios:**
- Conhecimento de JavaScript (ES6);
- Conhecimento de Metodologias CSS;
- Experiência com JavaScript (ES5);
- Experiência com consumo de API's REST;
- Experiência com algum Framework JS (Ember.js, React ou Angular);
- Experiência com Design Responsivo;
- Experiência com Pré-Processador CSS (de preferência Stylus);
- Experiência com Task Runners (de preferência Gulp);
- Experiência com Controle de Versão (Git ou BitBucket);
- Experiência com Desenvolvimento Ágil (Kanban/Scrum);
- Domínio de Semântica HTML;

**Desejáveis:**
- Conhecimento de Design Patterns com JavaScript;
- Conhecimento de Testes Automatizados com JavaScript;

**Diferenciais:**
- Contribuição em projetos Open Source;
- Participação e colaboração em comunidades Front-End;
- Artigos técnicos (blog pessoal, blog de comunidade, livros, e-pub);
- Conhecimento de PWAs;
- Conhecimento de consumo de API's [JSONAPI](http://jsonapi.org/);
- Experiência com Ember.js;

## Contratação

CLT

## Nossa empresa

A Focusnetworks possui unidades de negócios especializadas em serviços que transformam a maneira como as pessoas interagem com os negócios através da internet. Criamos soluções sob medida e atuamos com análise de requisitos, prototipação, desenvolvimento e suporte.

## Como se candidatar

Por favor, envie um email para danilo.vaz@focusnetworks.com.br com seu CV anexado - enviar no assunto: Vaga Front-End Pleno

**Comment by danilovaz** [comment]
Vaga aberta, ainda!

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by danilovaz** [comment]
Sim, aberto ainda @LFeh

**Comment by LFeh** [comment]
boa!

**Comment by villander** [comment]
@danilovaz coloca uma label de Remoto total mano haha

**Comment by danilovaz** [comment]
@villander bem que eu queria ter esse poder ❤️  hauhauhau infelizmente, só presencial 😢
