### ISSUE TITLE
[São Paulo] Front-end Developer na AMcom

### ISSUE THREAD

**Issue by AmandaElena** [frontendbr/vagas#5526]
## Nossa empresa
VEM SER UM MAKER NA AMCOM!
O propósito da AMcom é Conectar pessoas à tecnologia para transformar vidas. Esse objetivo tem como foco nossos clientes e ainda mais a nossa equipe!

Estamos há mais de 20 anos no mercado da tecnologia sempre inovando e trabalhando para:

Aumento de produtividade e receita
Otimização de custo
Inovação contínua
Experiência do usuário

No entanto acreditamos que alcançar tudo isso só é possível com uma equipe engajada, por isso, nossa sede foi construída para ser uma extensão da sua casa, de forma que você passe horas agradáveis aqui. Um lugar que inspira produtividade, criatividade e inovação, feito para pessoas que são apaixonadas por tecnologia e por fazer acontecer.
Somos movidos por grandes desafios e precisamos de pessoas que amem aprender constantemente, que sonhem grande e que tenham muita vontade em nos ajudar a transformar e crescer.
Estamos expandindo nossos horizontes e por isso procuramos pessoas que amem tecnologia, que sejam fascinadas por aprender coisas novas e que queiram fazer parte do nosso time!

## Descrição da vaga
O profissional será responsável junto com o time scrum em entregar as histórias priorizadas na sprint referente a novas funcionalidades do sistema de gestão pedagógica.
Especificamente responsável pela construção das telas do sistema.

## Local
Exemplo: Hibrido, [São Paulo], [Zona Sul]

## Requisitos
**Obrigatórios:**
-Ensino superior completo
-Experiência profissional com ReactJS
-Domínio de tecnologias essenciais ao front-end (HTML, CSS e JS)
-Sólidos conhecimentos em JS (ES6)
-Conhecimento em versionamento de código com Git e Redux
-Vivência com desenvolvimento de Single Page Applications
-Experiência em desenvolvimento responsivo com e sem Bootstrap

**Desejáveis:**
-Experiência com pré-processadores como Less, Sass ou Stylus
-Vivência com banco de dados relacional - PostgreSQL e metodologias ágeis
-Experiência com Docker
-Conhecimento em .NET
-Conhecimento em Flutter e Ant Design

## Benefícios
💳 R$ 1.500,00 mensal em cartão de crédito para utilização em qualquer estabelecimento com bandeira Mastercard
🏥 Plano de saúde de sua escolha: Unimed ou Notre Dame - (mensalidade 100% paga para você, apenas com coparticipação de 50%)
🦷 Plano odontológico da Uniodonto gratuito para colaborador
🆘 Seguro de vida gratuito
🇱🇷 Curso de inglês gratuito
🎓 Incentivo aos estudos (Graduação/Pós/MBA) – reembolso de 50% do valor da mensalidade em folha para o colaborador 
🎯 Incentivo ao desenvolvimento profissional – certificações, reembolso de 100% em caso de aprovação
📚 Investimento em capacitação profissional - treinamentos e patrocínio para participação em eventos como TDC
🏖️ Day-off no mês de aniversário – esse dia é todo seu!
🕦 Horário flexível
🏡 Modalidade de trabalho 100% home-office - para sempre se você preferir!
🧑‍🍼 Licença paternidade estendida de 10 dias
💰 Programa de indicação premiada – R$1.000,00 para profissionais indicados por você e contratados
🎉 Premiação por tempo de casa – aqui celebramos sua trajetória conosco 1, 3, 5, 7, 10, 15 e 20 anos 
🏫 Convênios com universidades
🥳 Muitas celebrações! Aqui celebramos datas especiais mas as conquistas do time também
💡Respeito a abertura
📈 Plataforma Feedz - voltada para comunicação, estruturação do seu PDI e feedbacks
🖥️ Participação no programa jovem programador, incentivando o desenvolvimento de jovens talentos

## Contratação
CLT

## Como se candidatar
Por favor envie uma mensagem para o Nº 47 991274061 com seu CV anexado - enviar no assunto: Vaga React

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 02 dias após cada processo.
Email para contato em caso de não haver resposta: amanda.almeida@amcom.com.br

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
