### ISSUE TITLE
[Goiânia/GO] Front-End Developer no PortalProvi

### ISSUE THREAD

**Issue by JoaoPauloCMarra** [frontendbr/vagas#553]
## Descrição da vaga

Estamos em busca de 2 Front-end Developer residentes de Goiânia.

## Local

Escritório em Goiânia - GO

## Benefícios

- auxilio refeição
- auxílio transporte
- segunda a sexta
- sempre tem café!
- gratificação por produtividade

## Requisitos

**Obrigatórios:**
- De 3 a 4 anos de experiência com Front-End;
- Conhecimentos em HTML, CSS e JS;
- De 1 a 2 anos de experiência com frameworks SPA(Angular, Ember, React, etc)

**Desejáveis:**
- conhecimentos em Laravel
- conhecimentos em NodeJs

**Diferenciais:**
- projetos opensource

## Contratação

PJ a combinar

## Nossa empresa

https://www.portalprovi.com.br/

## Como se candidatar

Por favor envie um email para rh@portalprovi.com.br com seu CV anexado - enviar **pretensão salarial** e no assunto: `Vaga Front-end`

**Comment by ygorlazaro** [comment]
Boa tarde, vocês tem oportunidades para desenvolvedor remoto? Sou do Rio

**Comment by JoaoPauloCMarra** [comment]
Sim, podemos negociar Remoto com a empresa, só enviar CV para o email do anúncio.

**Comment by jpmsegurado** [comment]
Só PJ? Existe chance de CLT também?

**Comment by JoaoPauloCMarra** [comment]
Existe sim, depende do candidato.

**Comment by Bilusca** [comment]
Bom dia, ainda está aberta a vaga ?

**Comment by JoaoPauloCMarra** [comment]
contrataram já, obrigado.
