### ISSUE TITLE
[São Paulo] Sr. Front-end developer na Mosaico (Nova fintech da egenius Founders com foco em blockchain)

### ISSUE THREAD

**Issue by ythalos** [frontendbr/vagas#554]
## Descrição da vaga

Estamos buscando um front-end developer sênior para se juntar ao time da Mosaico, uma nova fintech da venture builder eGenius (www.egenius.com.br) que trabalhará com blockchain/cryptocurrencies.

## Local

Escritório, São Paulo - Pinheiros

#### Diferenciais

- Ajudar a criar uma fintech totalmente do zero
- Trabalhar com tecnologias de ponta e com blockchain
- Salário competitivo
- Alto desafio tecnológico

## Requisitos

**Obrigatórios:**
- Domínio em lógica de programação, orientação de objeto e padrões de design
- Conhecimento forte em HTML / CSS / Javascript
- Experiência com frameworks JavaScript MVC (AngularJS, ReactJS ...)
- Experiência com preprocessors (less, sass, stylus ...)
- Experiência com testes unitários em js (Karma, Protractor, Jasmine ...)
- Alto senso de urgência e extremo ownership
- Atitude positiva, abordagem consultiva e auto-motivação

**Desejáveis:**
- Conhecimento ou interesse em blockchain/cryptocurrencies
- Conhecimento de práticas de segurança, backend e infra-estrutura
- Boas práticas de SEO
- Experiência com produtos financeiros

## Contratação

PJ a combinar

## Nossa empresa

A Mosaico Digital Assets é uma holding fundada por especialistas em mercados financeiros e tech empreendedores que visa dar acesso ao mercado institucional a novas classes de ativos, como cryptocurrencies, através de produtos financeiros com alto profissionalismo e segurança, seguindo padrões de mercado financeiro.

## Como se candidatar

Basta preencher o formulário: https://mosaico.typeform.com/to/ei8J60

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
