### ISSUE TITLE
[Remoto] Desenvolvedor Web na Codex Agro

### ISSUE THREAD

**Issue by luanasantosog** [frontendbr/vagas#5541]
> Vaga Remota durante a pandemia

## Nossa empresa

A Codex Agro, é especialista em soluções de inteligência em diagnóstico, prognóstico, monitoramento e inteligência comercial, reunindo grande capacidade em geração e gestão de dados estratégicos para o Agronegócio no Brasil.

## Descrição da vaga

Perfil: Fullstack, Backend ou Frontend.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Formação Superior na área de TI;
- Experiência em projetos de desenvolvimento Web;
- Experiência em projetos de desenvolvimento com arquitetura corporativa; 
- Experiência em desenvolvimento de projetos com banco de dados.

**Conhecimentos:**
- Conhecimento em uma ou mais tecnologias: Javascript/Vue/Java/ Springboot;
- Conhecimento GIS e conhecimento na plataforma ArcGIS (Diferencial).

## Contratação

A combinar

## Como se candidatar

Interessados e dentro do perfil, enviar currículo atualizado com pretensão salarial para recrutamento@img.com.br 
informando no assunto: Desenvolvedor Web - Github

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
