### ISSUE TITLE
[Remoto] Front-end Developer na Incentivar

### ISSUE THREAD

**Issue by mylenasantos** [frontendbr/vagas#5542]
## Nossa empresa

Somos a primeira incentivetech do Brasil, com o melhor e mais completo software do mercado. Desenvolvemos campanhas de incentivos, de premiação e de engajamento de forma adaptável, escalável e eficiente.

A Incentivar.io é fruto da Askme, agência de publicidade com 12 anos de expertise no mercado de incentivo e experiências, contando em seu histórico com alguns dos maiores cases do mercado e ganhadora de inúmeros prêmios.

A Incentivar é uma startup pertencente ao ecossistema do Cubo Itaú desde 2019.

Nosso site: https://incentivar.io/
LinkedIn: https://www.linkedin.com/company/incentivar/

## Descrição da vaga

Buscamos uma pessoa de desenvolvimento Front-end que nos ajude na sustentação e evolução do nosso produto no time de tecnologia da Incentivar.

## Local
Remoto

## Requisitos

**Obrigatórios:**
- ReactJS
- CSS com Styled Components e JSS
- Redux e organização com Duck Pattern e Redux Sauce
- Redux Saga
- ESlint
- Versionamento de código com git
- Boa lógica em integração com APIs e identificação de problemas
- Preocupação com a experiencia do usuário,
- Espírito de dono.

**Desejáveis:**
- Conhecimento em Gatsby, React Hooks e testes unitários
- Conhecimento em Material-UI
- Conhecimento em subir aplicativos Android na Google Store

## Benefícios
- 30 dias de ferias remunerados
- Auxilio Home Office de R$680 Cartão de credito Pré pago

**Diferenciais:**
- Feriados na quinta emendamos a sexta e feriados na terça emendamos a segunda.
- Horário de almoço flexível
- Time animado e dinâmico

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para rh@incentivar.io com seu CV anexado  - enviar no assunto: Vaga Front-end Pleno

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dia útil após cada processo.
E-mail para contato em caso de não haver resposta: alvaro@incentivar.io

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
