### ISSUE TITLE
[Remoto] Desenvolvedor na KAFFA

### ISSUE THREAD

**Issue by luanasantosog** [frontendbr/vagas#5543]
> Vaga Remota durante a pandemia

## Nossa empresa

A Kaffa é especialista em sistemas de mobilidade corporativa, com foco nas demandas espaciais (Mobile GIS), a Kaffa busca solucionar as deficiências inerentes aos sistemas corporativos tradicionais.

## Descrição da vaga

Experiência com duas ou mais das seguintes tecnologias: Java, Kotlin, Android, Node.js, React, SQL;
Análise crítica e capacidade em resolução de problemas.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Formação Superior na área de Tecnologia da Informação;
- Inglês intermediário/avançado.

**Desejáveis:**
- Conhecimento em Node.Js, React e outros frameworks de mercado; 
- Experiência com integração contínua e TDD; 
- Experiência com modelagem e consumo de APIs REST.

**Diferenciais:**
- Experiência com desenvolvimento de soluções GIS; 
- Micro serviços; 
- Bancos NoSQL.

## Contratação

A combinar

## Como se candidatar

Interessados e dentro do perfil, enviar currículo atualizado, e pretensão salarial para rh@kaffa.com.br
informando no assunto: Desenvolvedor - Github

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by felixxguilherme** [comment]
olá Luana, enviei currículo.
Muito obrigado!
