### ISSUE TITLE
[REMOTO] Front-end Developer na Onesight

### ISSUE THREAD

**Issue by kamiarc** [frontendbr/vagas#5544]
## Nossa empresa

A Onesight é uma multi-nacional com foco em desenvolvimento de tecnologias disruptivas e bleeding edge, atuamos com diversos clientes em múltiplos mercados e tecnologias.
No Brasil nossas atividades se concentram em e-commerces e plataformas customizadas.

## Descrição da vaga

Desenvolvimento e melhoria de funcionalidades de um e-commerce do setor de moda na plataforma VTEX, utilizando VTEX CMS e futura conversão para VTEX IO.

Desenvolvimento da parte de FrontEnd focada em HTML+CSS+JAVASCRIPT com os blocos dinâmicos de frontend da VTEX.

## Local

Remoto (empresa situada em São Paulo, SP)

## Requisitos

**Obrigatórios:**
- Desenvolvimento web (HTML5/CSS3, Javascript)
- Sistemas de templates

**Desejáveis:**
- Conhecimento da plataforma VTEX, principalmente CMS e VTEX IO
- Conhecimento em GraphiQL
- Noções de Javascript dinâmico (sync,async,fetch...)

**Diferenciais:**
- Ter trabalhado com VTEX

## Contratação
PJ ou estágio, a combinar

## Como se candidatar

Por favor envie um email para trampos@onesight.com.br com seu CV anexado - enviar no assunto: Vaga DAZ Front

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: contato@onesight.com.br

#### Alocação
- Remoto

#### Regime
- Estágio
- Freela
- PJ

#### Nível
- Júnior
- Pleno

**Comment by israelcena** [comment]
Obrigado pelo anuncio da vaga,
Tenho uma pergunta:
Tem noção de valores ?

**Comment by erickmacena1** [comment]
Que projeto incrível! As oportunidades ainda estão de pé?

**Comment by kamiarc** [comment]
Olá, infelizmente acabamos de entrar na segunda fase do projeto e vamos
finalizar as candidaturas.

Porém envie o seu currículo assim mesmo, temos 2 projetos novos para
iniciarem em breve :)

Il gio 9 set 2021, 20:30 Erick Macena ***@***.***> ha scritto:

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
