### ISSUE TITLE
[Remoto] Front-end Javascript Engineer (Senior) na Intellective

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#5562]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/senior-javascript-engineer-170554910?origin=github&medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Vaga para Fullstack Javascript Engineer com 4+ ano ou mais de experiência.</p>
<p></p>
<p><strong>O profissional deverá ter:</strong></p>
<ul>
<li>Conhecimento de Javascript e já ter trabalhado com frameworks como React, Angular or Vue;</li>
<li>Conhecimento em CSS e HTML</li>
</ul>
<p><strong>O que oferecemos:</strong></p>
<ul>
<li>Aprenda com veteranos da indústria;</li>
<li>Trabalho remoto, com flexibilidade de horário e local.</li>
<li>Equipamentos necessários para trabalhar;</li>
<li>Oportunidade de trabalhar com marcas Iconicas e ganhar uma experência única;</li>
</ul>
<p><strong>Quem somos</strong></p>
<p>A Intellective é uma empresa 100% focada na Servicenow. Nós ajudamos nossos clientes a extrair o máximo de seu investimento na plataforma ServiceNow. Criamos ferramentas que adicionam novas funcionalidades expecializadas na experiência do funcionário e estratégia e execução.</p>
<p>Para mais informações acesse: https://intellective.co</p>

## Intellective: 
 <p>Intellective is a 100% ServiceNow focused development studio. We help our clients make the most of your ServiceNow investment!  We develop tools that provide new capabilities for the ServiceNow platform and specialize in Employee Experience strategy and execution.</p>
<p>For more information visit <a href="https://intellective.co" target="_blank">https://intellective.co</a>&nbsp;</p><a href='https://coodesh.com/empresas/intellective'>Veja mais no site</a>

 ## Habilidades: 
 - Angular.js 
- Backbone.js 
- HTML 5 
- Gulp Experts 
- Javascript 
- CSS 3 
- Webpack
## Local: 
 100% Remoto
## Requisitos: 
 - 4+ anos de experiência em Javascript 
- Conhecimento em CSS e HTML 
- Conhecimento em frameworks como React, Angular ou Vue 
- Experiência trabalhando em times que usam SCRUM/Kanban 
- Capacidade de resolver problemas
## Diferenciais: 
 - Inglês escrita / conversação 
- AngularJS 1.+ 
- Conhecimento na plataforma ServiceNow
## Benefícios: 
 - Horários Flexíveis; 
- Oportunidade de trabalhar com grandes Players no mercado; 
- Trabalhar em uma startup no Vale do Silicio;
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Senior Javascript Engineer na Intellective](https://coodesh.com/vagas/senior-javascript-engineer-170554910?origin=github&medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Nível
Sênior
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
