### ISSUE TITLE
[Recife-PE] Full stack Delphi Developer na 3LMINFORMATICA 🏢 Locado 👨 Pleno ⚖️ CLT

### ISSUE THREAD

**Issue by PereiraAmorim** [frontendbr/vagas#5563]
Descrição
A 3LM INFORMATICA está em busca de um(a) Desenvolvedor Delphi. Se você tem interesse em ingressar em um time de feras com ambiente dinâmico, é movido(a) a desafios e tem muito a acrescentar ao nosso negócio essa vaga é pra você!<br>
Descrição da vaga
Realizar manutenção de projetos , integrações webservices SOAP e REST, API  e Gateway, demandas front-end em DELPHI,  .

Requisitos:
Obrigatórios:

- Object Pascal (DELPHI), 
- Programação Orientada a Objetos, conhecer padrões de projetos, artefatos para construção e manipulação (XML, JSON), artefatos para documentação, testes unitários, controle de versão tortoise, git, subversion ou equilaventes

<br>
Interessados enviar CV para selecao@3lminformatica.com.br início imediato

Benefícios: Ajuda de Custo.

Labels:
🏢 Locado
⚖️ A-Combinar
👨 Pleno
⚖️ CLT

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
