### ISSUE TITLE
[REMOTE] Pessoa Desenvolvedora React Native - Middle | Kobe Global Software House

### ISSUE THREAD

**Issue by mariazepe** [frontendbr/vagas#5564]
## Sobre o desafio 📱

Nessa posição, você terá a oportunidade de fazer parte de um de um **projeto de uma startup que é referência no mercado fitness impactando a vida de milhares de usuários em todo o Brasil**. Você trabalhará com produtos complexos que envolvem streaming de video, contato com cloud e diversos APIs. Além disso, terá autonomia para desenvolver e implementar novas soluções pensando nas necessidade dos usuários e oferecendo a melhor experiência.

## Local 🌍

Remoto

## Benefícios 🚀

- **Food Voucher:** R$25/dia
- **Your Way Holidays**: 10 dias de recesso de final de ano sem desconto no tempo de férias
- **Health Insurance:** plano de saúde, odontológico e seguro de vida 100% coberto e sem coparticipação
- **Flexible Time:** possibilidade de gerenciar sua agenda com autonomia (e claro, responsabilidade!) 
- **Kober Remote Experience**: cultura remote first com atividades de integração periódicas para Kobers 
- **Kobe Growth:** Plano de Desenvolvimento Individual (PDI) para cada Kober
- **International Immersion**: cultura internacional com projetos e escritórios fora da BR
- **The Right Tools**: equipamento de alto nível para sua estrutura de trabalho

## Requisitos ☝️

**O desafio vai ser mais natural se você já tiver**
- 2 anos de experiência com framework React Native
- Conhecimento do processo end to end de desenvolvimento 
- Habilidade de comunicação interpessoal 
- Ownership e autonomia na tomada de decisões

**Desejáveis:**
- Conhecimento em **Redux Saga**
- Experiência com **Testes Unitários**
- Experiência com **IAP** (In App Purchases)

## Contratação ⚖️

CLT

## Sobre a Kobe

Somos uma empresa que cria apps usando tecnologia, design e empatia. Ajudamos empresas a desenhar, construir e lançar produtos digitais. Alguns cases de sucesso são: Tok & Stok, Agibank, Warren, Decathlon & muitos outros!

Para mais info acesse: https://www.kobe.io/cases

## Curtiu? 💥

Só se candidatar através do link: https://kobe.gupy.io/jobs/1125735

Ou enviar um email para: maria.zepeda@kobe.io com o CV anexado.

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👨 Pleno
- ⚖️ CLT
- 💰 5k-10k

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
