### ISSUE TITLE
[São Paulo] Front-End Developer Sr. em Startup

### ISSUE THREAD

**Issue by octaconsulting** [frontendbr/vagas#557]
## Descrição da vaga
Análise e desenvolvimento do front-end de plataforma de telefonia VoIP,
baseada em sistema operacional Linux, Ruby e Ruby on Rails, PostgreSQL,
Sidekiq e Redis.

## Local

Escritório, São Paulo - Vila Olímpia

## Benefícios
-Vale refeição: R$ 25/dia útil (com desconto de 20% do valor na fonte);
-Plano de saúde: Bradesco Saúde – Top Nacional (100% gratuito para titular e dependentes
elegíveis);
-Vale transporte;
-Seguro de vida corporativo

#### Diferenciais

- Horário flexível;
- Cultura startup;

## Requisitos

**Obrigatórios:**
- Domínio de HTML, JS, CSS/SASS
- Conhecimento profundo de React;
- Experiência com framework de testes;

**Desejáveis:**
- Conhecimentos de Ruby on Rails;
- Conhecimentos de Typescript;
- Familiaridade com Docker;
- Conhecimento de patterns de desenvolvimento;
- Experiência com versionamento Git (ou similar);
- Experiência com testes unitários, integrados e de aceitação;

## Contratação

CLT;

## Nossa empresa

Uma startup que busca gerar disrupção no mundo de call-centers.
Normalmente call-centers usam telefonia dedicada e hardware dedicado, além
de locais físicos dedicados.

A proposta da empresa é viabilizar operações de call center só com um web-
browser e acesso a internet. Entre outras coisas, viabiliza operações de callcenter em que todo mundo pode ficar em casa.
Estamos montando uma equipe de desenvolvimento de produtos, com
investimento de longo prazo, e a vaga é nesta equipe.
Estamos trabalhando com software livre na veia, Ruby/PostGreSQL,
Debian/Docker, integração contínua e outras práticas interessantes.
Desejamos conhecer profissionais que sejam apaixonados por tecnologia, que
queiram trabalhar com tecnologias de ponta em aplicações desenhadas para a
nuvem, e dispostos a trabalhar em equipe em um ambiente com cultura de
start-up.

## Como se candidatar

Por favor envie um email para mayara@octarh.com com seu CV anexado - enviar no assunto: Vaga Front-End Sr.

**Comment by LFeh** [comment]
E qual o nome da Startup?

**Comment by octaconsulting** [comment]
@LFeh você tem interesse?

**Comment by LFeh** [comment]
Não. 

Mas todas as vagas cadastradas precisam ter o nome da empresa contratante. Essa informação não pode ser omitida.

**Comment by octaconsulting** [comment]
Nós abriremos o nome da empresa para os profissionais que se interessarem e entrarem no processo seletivo, @LFeh!

**Comment by netojose** [comment]
Tenso, o cara não sabe a cidade, o que a vaga pede, quem está contratando, etc. Assim é difícil...

**Comment by mayaraneudl** [comment]
Oi, @netojose! Nós temos essa informação, porém somos uma consultoria que temos um contrato de confidencialidade com as empresas que são nossas clientes, pois muitas vagas são de substituição. Imagine que chato o profissional que trabalha nessas empresas, ver seu cargo anunciado publicamente, e seus colegas concorrendo-o! Pedimos compreensão perante nossa obrigação de manter o que está no contrato, e respeitamos a posição de vocês não conhecerem a oportunidade antes de ter as informações que desejam. Desejamos uma boa tarde a todos, e nos desculpamos por qualquer possível inconveniente!

**Comment by octaconsulting** [comment]
Oi, @netojose! Nós temos essa informação, porém somos uma consultoria que temos um contrato de confidencialidade com as empresas que são nossas clientes, pois muitas vagas são de substituição. Imagine que chato o profissional que trabalha nessas empresas, ver seu cargo anunciado publicamente, e seus colegas concorrendo-o! Pedimos compreensão perante nossa obrigação de manter o que está no contrato, e respeitamos a posição de vocês não conhecerem a oportunidade antes de ter as informações que desejam. Desejamos uma boa tarde a todos, e nos desculpamos por qualquer possível inconveniente!

**Comment by netojose** [comment]
Sim, @octaconsulting , eu entendo bem seu ponto de vista. Até já vi isso acontecer várias vezes e sei que é normal. Obrigado pelo feedback.
