### ISSUE TITLE
[REMOTO] Front-end Developer na DietSystem

### ISSUE THREAD

**Issue by thiagoferreira123** [frontendbr/vagas#5572]
## Nossa empresa

Aplicação web feita em JS puro no frontend, PHP puro no backend e MYSQL como banco de dados.

## Descrição da vaga

Procuramos um desenvolvedor para nos ajudar a finalizar o desenvolvimento de alguma funcionalidades na plataforma.

## Local

Remoto.

## Requisitos

**Obrigatórios:**
- Experiência em JS, PHP e MYSQL.
- Experiência em versionamento de código (utilizando bitbucket)
- Experiência em CSS e HTML.
- Desenvolver códigos limpos, organizados, fácil manutenção e escalável.

**Desejáveis:**
- Conhecimentos em figma.
- Já ter trabalhado em aplicações semelhantes

## Contratação

Temporário (3 meses) com contrato de freelancer, com possível renovação dependendo do desempenho.

## Como se candidatar

Desenvolvemos um teste online, aonde o candidato deverá replicar o layout usando CSS, HTML e JS. [Está nesse link. ](https://www.figma.com/file/Lwg846g5Dq4b4ejYMJp7xF/Login?node-id=0%3A1)Após terminar de construir o layout, os arquivos deverão ser enviados através de um arquivo zip para contato@dietsystem.com.br

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dia após cada processo.

#### Alocação

- Remoto

#### Regime

- Freela, 4 horas diárias (de Seg a Sexta-feira), nos envie sua prentensão de recebimento R$.

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
