### ISSUE TITLE
[REMOTO] Front-end Developer na 5A Attiva

### ISSUE THREAD

**Issue by CarolinaRCerqueira** [frontendbr/vagas#5574]
## Descrição da vaga

Desenvolvedor Front End PL e SR
Home office durante a pandemia e após 4 dias remoto e 1 dia presencial.

## Requisitos

Necessário vivência com Angular 2+ ou superior. 

## Contratação

PJ

## Como se candidatar

Por favor envie um email para carolina.cerqueira@5aattiva.com.br com seu CV anexado - enviar no assunto: Vaga Dev. Frontend 

#### Alocação

Home office durante a pandemia e após 4 dias remoto e 1 dia presencial.

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
