### ISSUE TITLE
[SÃO PAULO] Front-end Developer na NAVA

### ISSUE THREAD

**Issue by Alanmabar** [frontendbr/vagas#5578]
Front-End Developer

> Vaga Hibrida Durante a pandemia [2 dias na empresa x 3 dias homeoffice] 

## Nossa empresa

Exemplo: Somos uma empresa de tecnologia e Cultura Lean voltada a negócios, formada por profissionais apaixonados por desafios e comprometidos com resultados. Há quase 25 anos no mercado, conectamos talentos, habilidades e oportunidades para entregar soluções tecnológicas alinhadas aos propósitos dos nossos Clientes.

## Descrição da vaga

Exemplo: Análise e desenvolvimento de sistemas atuando em equipes ágeis do segmento financeiro.

## Local - Avenida Interlagos [Santander] - 2x na semana. 
São Paulo 

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Angular 2+ [7,8] 
- Integrações/Protocolos (Soap, Rest, WSDL, XSD, XSLT, XQuery, JSON)
- DevOps Git, Jenkins ou Cloudbees 
- Linux e/ou Windows 
- Metodologias ágeis: Scrum/Kanban 

**Desejáveis:**
- Experiência no segmento financeiro 

## Benefícios

- Plano de saúde [Med e Odont Sul América] 
- Seguro de vida
- VR de R$ 506,00
- Auxílio creche para crianças de 0 a 5 anos.
- 

## Contratação
CLT a combinar 

## Como se candidatar

Por favor envie um email para alan.barros@nava.com.br com seu CV anexado - enviar no assunto: Vaga Front-End Developer 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após cada processo.
E-mail para contato em caso de não haver resposta: alan.barros@nava.com.br

#### Alocação
- Alocado
- HIBRIDO

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
