### ISSUE TITLE
Vaga Inválida

### ISSUE THREAD

**Issue by octaconsulting** [frontendbr/vagas#558]
## Descrição da vaga

Front-End nível Sr. com experiência em HTML, CSS, Java Script e Framework React.

## Local

São Paulo

## Benefícios

- Plano de saúde SulAmerica
- VT
- VR

## Requisitos

**Obrigatórios:**
Senioridade em HTML, CSS, Java Script e Framework React.

## Nossa empresa

Há 15 anos desenvolve soluções tecnológicas e presta serviços especializados para a disponibilização de conteúdos digitais em múltiplos dispositivos, pioneira absoluta no mercado brasileiro e líder consolidada no segmento. É provedora de soluções robustas e flexíveis em criação, digitalização, enriquecimento, comercialização, distribuição e consumo interativo de conteúdo e atende ao mercado como um todo, nos segmentos educacional, empresarial e editorial.

## Como se candidatar

Por favor envie um email para mayara@octarh.com com seu CV anexado - enviar no assunto: Vaga Front-End Developer Sr.

**Comment by LFeh** [comment]
Qual o nome da empresa contratante?

**Comment by octaconsulting** [comment]
Abriremos para os profissionais com interesse na oportunidade.

**Comment by netojose** [comment]
Tenso, o cara não sabe a cidade, o que a vaga pede, quem está contratando, etc. Assim é difícil...

**Comment by octaconsulting** [comment]
Oi, @netojose! Nós temos essa informação, porém somos uma consultoria que temos um contrato de confidencialidade com as empresas que são nossas clientes, pois muitas vagas são de substituição. Imagine que chato o profissional que trabalha nessas empresas, ver seu cargo anunciado publicamente, e seus colegas concorrendo-o! Pedimos compreensão perante nossa obrigação de manter o que está no contrato, e respeitamos a posição de vocês não conhecerem a oportunidade antes de ter as informações que desejam. Desejamos uma boa tarde a todos, e nos desculpamos por qualquer possível inconveniente!

**Comment by netojose** [comment]
Sim, @octaconsulting , eu entendo bem seu ponto de vista. Até já vi isso acontecer várias vezes e sei que é normal. Obrigado pelo feedback.
