### ISSUE TITLE
[REMOTO] Front-end Developer na SumUp

### ISSUE THREAD

**Issue by hingridcruzeiro** [frontendbr/vagas#5583]
## Nossa empresa

QUEM SOMOS
Nós crescemos muito desde a nossa origem como startup. Hoje, somos uma grande fintech global, com mais de 2000 SumUppers espalhados por 3 continentes. E estamos crescendo e nos diversificando como nunca antes.

O QUE FAZEMOS
Nossos leitores de cartão são usados por milhões de clientes, processando pagamentos em mais de 30 países. Enquanto construímos um mundo onde esses pequenos negócios podem ter sucesso fazendo o que amam, nós continuamos expandindo o nosso número de produtos e serviços.

## Descrição da vaga

Na cadeira de Frontend Engineer, buscamos uma pessoa desenvolvedora com sólida experiência pra fazer o design e implementar melhorias nas aplicações de frontend. Algumas das tecnologias que estamos usando por aqui incluem React, JavaScript, GraphQL, Apollo, Storybook, AWS e Docker. 

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Sólida experiência com desenvolvimento front, desejável ter atuado com Javascript e / ou React;
- Inglês avançado;

**Diferenciais:**
- projetos opensource
- conhecimentos em ruby on rails
- conhecimentos em Golang
- conhecimentos em Elixir

## Benefícios

-Seguro Saúde: SulAmérica Especial, cobertura nacional, seguro viagem incluso. 
-Seguro odontológico (opcional).
-Seguro de vida: Tokio Marine.
-Vale Refeição: R$660 / mês, sem desconto em folha de pagamento (Benefício flexível - você poderá transferir qualquer parte desse valor para outras categorias de benefícios disponíveis - Mobilidade, Alimentação, Cultura, Saúde e outros - por meio do app do cartão Caju flex).
-Auxílio à infraestrutura: R$635, no seu primeiro mês conosco para montar uma infraestrutura ergonômica de home office.
-Auxílio Home Office: R$150 / mês, para custear despesas relacionadas ao home office.
-Voucher de estacionamento ou transporte.
-Gympass.
-Auxílio creche.
-Plano de Previdência Privada da SumUp.
-Auxílio estudo e educação.
-Bônus anual

## Contratação

CLT

## Como se candidatar

Candidatar-se exclusivamente através da [Página de Carreiras da SumUp](https://sumup.com/careers/positions/são-paulo-brazil/engineering/specialist-frontend-engineer-/5343054002/)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
