### ISSUE TITLE
[Rio de Janeiro] Front-end Developer na Legalcloud

### ISSUE THREAD

**Issue by cesarlegal** [frontendbr/vagas#559]
## Descrição da vaga

Vaga para desenvolvedor front-end em uma das startups legal tech de maior destaque do país. A Legalcloud  já tem mais de 75 mil advogados utilizando nosso serviço, sendo recomendada pelo Tribunal de Justiça do Rio de Janeiro e a OAB. Estamos crescendo cerca de 10% ao mês e com planos ambiciosos de utilizar a massa de dados (mais de 1 milhão de processos ao ano) para análise preditiva e big data. Estamos localizados no Largo do Machado, no Rio de Janeiro.

## Local

Largo do Machado, Rio de Janeiro

## Benefícios

- Auxílio Refeição
- Auxílio Transporte
- Plano de saúde

#### Diferenciais

- Horário flexível
- Pizza toda semana
- Pipoca e outras gordices
- Cervejas na geladeira
- Terraço para relaxar
- Pode vir de bermuda, blusa, saia, etc. Sabemos do calor do Rio.
- Do lado do metrô

## Requisitos

**Obrigatórios:**
- HTML5 avançado, CSS 3 avançado e JavaScript avançado (utilizados em +1 projeto profissional)
- Conhecimento intermediário em React/RiotJS/Vue/Angular; utilizados em ao menos 1 projeto profissional, utilizando router e Redux/Vuex/sistema de store equivalente.
- Experiência em integração com serviços

**Desejáveis:**
- Experiência com serviços REST e JWT (microservices), Git,
- MongoDB/PostgreSQL/MySQL, Java 8 (Jersey/Resteasy, JEE 7, Hibernate, Wildfly), queues (RabbitMQ/ActiveMQ), BDD, DDD, TDD, Linux, Python (Django).

## Contratação

PJ a combinar, podendo virar CLT e fazer parte do plano de stock options.

## Nossa empresa

Em menos de 1 ano, a Legalcloud impactou positivamente o sistema judiciário brasileiro, sendo um aplicativo recomendado pela OAB e tribunais ao redor do Brasil. Mais de 50 mil usuários utilizam mensalmente nosso produto.

Queremos pessoas que nos ajudem a acelerar ainda mais o nosso crescimento e estejam doidas para deixar um impacto no mundo, fazendo parte de algo inovador desde o início. 

## Como se candidatar

Preencha o questionário: https://legalcloud.typeform.com/to/EDFWFY

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by cesarlegal** [comment]
Aberto ainda. Continuamos procurando profissionais de frontend

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
