### ISSUE TITLE
[Remoto] Front-end Developer @ My Love Stars

### ISSUE THREAD

**Issue by alexandrebodi** [frontendbr/vagas#5590]
## Nossa empresa

Somos uma start-up recentemente incorporada na Califórnia, financiada por grupos de investimento e com um grande potencial de valorização no curto prazo.

## Descrição da vaga

Estamos desenvolvendo uma **PWA** que utiliza **React.js** (e **Chakra UI**) no front-end, Node.js e Firebase (pelo menos, por enquanto) no back-end. Estamos hoje com um time bastante reduzido, e precisamos de mais gente para dar celeridade ao processo de desenvolvimento.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento web em geral
- Experiência com Git

**Desejáveis:**
- Experiência com React.js
- Experiência com Firebase (Authentication, Firestore, Storage) e/ou AWS (Amplify, S3)
- Experiência com desenvolvimento de PWAs

**Diferenciais:**
- Experiência com Node.js

## Benefícios

- Remuneração em USD

## Contratação

PJ

## Como se candidatar

Por favor envie um email para abodi@mylovestars.com com a frase "Vaga Front-End publicada no GitHub" no campo assunto, seu CV anexado, e respondendo às seguintes perguntas:
- Tempo de experiência com React.js: 
- Tempo de experiência com Firebase: 
- Tempo de experiência com AWS: 
- Tempo de experiência com PWA: 
- Tempo de experiência com desenvolvimento web em geral: 
- Tempo de experiência com Git: 
- Pretensão salarial (em USD): 
- Disponibilidade (full-time ou part-time): 
- Em quanto tempo consegue iniciar: 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 semana após cada processo.

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
