### ISSUE TITLE
[São Paulo] Front-end Developer Designer/UX na Gendo.com.br

### ISSUE THREAD

**Issue by jbaladao** [frontendbr/vagas#5598]
Vaga 100% Remota

## Nossa empresa

A startup [Gendo](https://www.gendo.com.br) já está entre os maiores sistemas de gestão para Prestadores de Serviços do Brasil, nossos clientes movimentaram juntos aproximadamente 67 milhões de reais em dezembro de 2019. A empresa já foi acelerada em 2016 no evento InvestorsDay da CampusParty (anjos via Broota) e, no ano de 2017 recebeu um novo investimento do grupo Bossa Nova (pré-seed). Desde 2020 está em processo de expansão acelerado com aporte de novo investidor com ampla experiência de mercado.
Se quiser participar desse sonho, integrar uma equipe independente e de alta performance, venha trabalhar conosco. Vivenciar o nascimento e transformação de uma Startup é incrível e as oportunidades de crescimento e aprendizado são muitas!

## Descrição da vaga

A startup [Gendo](https://www.gendo.com.br) é um SaaS para prestadores de serviços. Procuramos um profissional com pelo menos 2 anos de experiência com criação design e usabilidade de sistemas web/mobile!

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com design usando as ferramentas Photoshop, Gimp ou similares;
- 1 ano de experiência com prototipação usando Figma ou Adobe XD;
- conhecimentos sólidos em usabilidade (UX) de sistemas web/mobile;
- noções em HTML e CSS.

**Desejáveis:**
- alguma experiência com metodologias ágeis de desenvolvimento.

**Diferenciais:**
- ter trabalhado com algum sistema online no modelo SaaS.

## Contratação
PJ a combinar

## Como se candidatar

Por favor, envie um email para [jbaladao@gendo.com.br](mailto:jbaladao@gendo.com.br) com seu CV anexado - enviar no assunto: "Vaga Front-end Developer Designer/UX"

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

## Labels
designer usabilidade ux remoto figma photoshop web mobile

#### Alocação
- Remoto, com escritório em São Paulo/SP.

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
