### ISSUE TITLE
[Rio de Janeiro] FrontEnd Estágio/Jr

### ISSUE THREAD

**Issue by fredericksilva** [frontendbr/vagas#56]
## Descrição da vaga

Estamos precisando de alguém que saiba se virar, que tenha curiosidade e vontade de aprender, para trabalhar na área de Experiências Digitais. Essa coordenação é responsável por mirabolar, planejar, desenvolver e manter as plataformas e canais virtuais de participação na gestão municipal. Se você vier pro que der e vier com a gente, vai trabalhar diretamente com desenvolvedores, gerentes de projetos e designers na criação de novas tecnologias de participação cidadã na prefeitura.

### E o que vai fazer um desenvolvedor de Front-End no LAB.Rio?
- Desenvolver o front-end dos projetos do LAB.Rio, com foco em Usabilidade,  Acessibilidade e Responsividade;
- Criar interfaces que sejam modernas, acessíveis e responsivas.
-Criar landing pages em parceria com a galera do Design

## Local

 LAB.Rio (Palácio da Cidade, Botafogo), com possibilidade de participar de reuniões externas e para atender aos projetos em outras localidades

## Requisitos

**Principais habilidades:**
- Muita proatividade;
- Conhecimento intermediário em HTML5, CSS3 e JavaScript;
- Saber o que é GIT/Github;
- Organização e código limpo;
- Boa comunicação (verbal e escrita);
- Conhecimento razoável em Linux ou Mac.
- Desenvolver com foco no usuário e se envolver no processo e estratégia

**Habilidades desejáveis:**
- Experiência com Software Livre / Código Aberto
- Algum conhecimento de metodologias ágeis (Scrum, Lean, Kanban, etc);
- Algum conhecimento ou curiosidade em aprender UX;
- Algum conhecimento em análise de dados e métricas;
- Familiaridade com ferramentas de gestão de tarefas (Trello, Slack, etc);
- Conhecimento de - ou interesse em aprender -  Ruby on Rails;
- A familiaridade com Photoshop, Illustrator, e / ou esboço é um plus
- Interesse em gestão pública/urbana participativa.

**Educação:**
- Autodidatas, estudantes, curiosas e curiosos são bem vindos.

## Detalhes da vaga

- Salário: R$1.500,00;
- Carga horária: 30h/semana (flexíveis e de acordo com o que for combinado e a necessidade);
- Benefícios:  cartão alimentação ou refeição (R$240,00)

## [ LAB.rio](http://lab.rio)

Conhece o LAB.Rio? Quer trabalhar com a gente? 
Precisamos de alguém pra nossa equipe focada em desenvolver Experiências Digitais de Participação. 
Interessou? Detalhes abaixo!

###  O que faz o LAB.Rio?

Cria, testa e aplica projetos de participação cidadã. Foi criado para aproximar as pessoas do poder público e permitir que todos e todas participem da tomada de decisão sobre a cidade que queremos. Entendemos que a cidade pode e deve ser uma construção coletiva. Por isso, trabalhamos com o objetivo de criar experiências digitais e presenciais que possam se tornar modelo de engajamento e participação.

### Exemplo concreto de produto da área: 

O LAB.Rio lançou o [Mapeando](http://mapeando.rio.gov.br), uma plataforma colaborativa da Prefeitura do Rio criada para que as cidadãs e os cidadãos cariocas possam apontar diretamente no mapa as suas demandas por serviços públicos municipais

## Como se candidatar

Para se candidatar à vaga, envie seu currículo para fred@labrio.cc com o assunto “**[Vaga] [Estágio Front-End]**”  e um parágrafo com o porquê de você querer trabalhar com a gente! Até 18h do dia 20/06.

ps: Se você já enviou seu currículo, ele está em nosso banco de dados e iremos considerá-lo também.

**E aí? Vem com a gente?**

**Comment by LFeh** [comment]
Boa vaga @fredericksilva, espero que achem um bom estagiário ;)

**Comment by vitroz** [comment]
Quem me dera morar no Rio rsrs
Boa vaga!

**Comment by fredericksilva** [comment]
@LFeh, @vitroz  Valeu amigos, compartilhe com a rede de vocês :)

**Comment by LFeh** [comment]
@fredericksilva Compartilhei ontem :)

**Comment by willianjusten** [comment]
Grande Fred! Trabalhamos juntos uma semana ahuahuahua
Tomara que consiga alguém legal =D

**Comment by fredericksilva** [comment]
Não exagera foram quase 3 semanas huahua @willianjusten

**Comment by stoque** [comment]
Currículo enviado ;)

**Comment by thallesmarchetti** [comment]
Bom dia,

Vaga ainda está em aberto?

**Comment by freeboxd** [comment]
Ainda de pé? Só pra confirmar: precisa ensino superior?

**Comment by fredericksilva** [comment]
Galera! Essa vaga Fechou!

**Comment by LFeh** [comment]
\o

**Comment by camilatigre** [comment]
@fredericksilva 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
