### ISSUE TITLE
[Rio de Janeiro] Estágio Front-End no ESTUDIO CRU

### ISSUE THREAD

**Issue by pedro-rivera** [frontendbr/vagas#560]
## Descrição da vaga

Estamos buscando uma pessoa para nos ajudar no front-end aqui no ESTUDIO CRU!

## Local e Horário

**Apenas presencial.**
Gávea, Rio de Janeiro. Das 10h às 17h.

## Requisitos

**Obrigatórios:**
- Aquele básico de HTML + CSS + JS
- Se sentir confortável com WordPress

**Desejáveis:**
- Querer se aprofundar em JavaScript e/ou trabalhar com Python

## O ESTUDIO CRU

Através do design, desenvolvemos soluções visuais e criamos engajamento com pessoas, marcas e projetos. Nossa filosofia de trabalho é baseada em simplicidade, clareza e solução inteligente de problemas. Enxergamos o cliente como um parceiro e acreditamos que um trabalho bem sucedido é fruto desta colaboração. Buscamos sempre novos desafios e estamos sempre abertos a novos projetos.

## Como se candidatar

Envie um e-mail para contato@estudiocru.com com o assunto _[Front-End] SEU NOME_ com portfolio, links de projetos e o que mais achar interessante que a gente saiba sobre você e seu trabalho.

.
labels: estágio

**Comment by hillarysousa** [comment]
Tem vaga pra junior também?

--
*Hillary Sousa*
*Web Designer & Front-End Developer*

Em 26 de setembro de 2017 09:32, pedro-rivera <notifications@github.com>
escreveu:

**Comment by pedro-rivera** [comment]
@hillarysousa o foco no momento é pra estágio mesmo, mas não vamos fechar as portas pra ninguém :)

**Comment by hillarysousa** [comment]
Perfeito! Vou enviar meu currículo então, mas eu sou junior rs

--
*Hillary Sousa*
*Web Designer & Front-End Developer*

2017-09-26 10:33 GMT-03:00 pedro-rivera <notifications@github.com>:

**Comment by andreyazevedo** [comment]
Para fazer o estágio é necessário estar cursando alguma graduação?

**Comment by pedro-rivera** [comment]
@LFeh pode fechar aqui, conseguimos um guri que achou a vaga por aqui mesmo ;)

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by LFeh** [comment]
Agora que vi @pedro-rivera, sensacional!
