### ISSUE TITLE
[Remoto] Front-end Developer na TRACTIAN

### ISSUE THREAD

**Issue by Wenderson-P** [frontendbr/vagas#5606]
![image](https://user-images.githubusercontent.com/52503774/131387320-9ec522c6-82bb-4026-8659-7210e897ae1a.png)

## Nossa empresa

A TRACTIAN é a startup industrial de mais rápido crescimento no Brasil. 
Facilitamos a vida dos gestores de manutenção a eliminar rotinas de planilhas intermináveis e quebras inesperadas. 
Somos como um Shazam, escutamos a condição das máquinas e prevemos anomalias. 

**Aqui você vai ter:**
- A oportunidade de aprender muito com um time de alto nível
- Autonomia para tomar decisões sem precisar investir tempo e energia em reuniões desnecessárias
- Foco em desafios para chegar cada vez mais longe
- Plano de Carreira, metas e recompensas

## Descrição da vaga

- Desenvolver produtos e serviços que atendam as necessidades dos nossos clientes com as melhores tecnologias front-end do mercado
- Dar vida a gráficos na plataforma que os gerentes de manutenção usam diariamente
- Criar páginas intuitivas para os usuários

## Local
- Remoto ou no Escritório na Vila Mariana, SP

## Requisitos

- Experiência com HTML e SCSS
- Experiência com Javascript (ReactJS)
- Experiência desenvolvendo aplicações responsivas

**Diferenciais** 
- Conhecimento em Redux/Recoil, Typescript e Clean Architecture

## Compensação e Benefícios

- Salário competitivo e bônus em stock options
- Caju de R$500/mês para você gastar com seu  bem-estar, entretenimento e crescimento pessoal
- Horário de trabalho flexivel 
- Gympass

Mais detalhes em: https://careers.tractian.com/

## Contratação

PJ a combinar

## Como se candidatar

https://airtable.com/shrGmOQJdnP8PjAAo

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
