### ISSUE TITLE
SP Front-end Developer na @DIGI

### ISSUE THREAD

**Issue by logeraldi** [frontendbr/vagas#5607]
**Vaga Desenvolvedor Fullstack** 

A Digi é uma das principais e mais relevantes fornecedoras de marketing de incentivo do País. Oferecemos plataformas tecnológicas e consultoria estratégica para campanhas de Loyalty e Incentivo. 
Nossos clientes são as maiores multinacionais do mundo e oferecem desafio de alto nível para grandes talentos. 

Nossa vaga é para atuar em um projeto bem legal, com a Stack 100% Javascript, e o desenvolvedor precisa ter a cultura de pensar fora da caixa, as tecnologias usadas são: 

React JS 

Styled Components 

GraphQL 

Typescript 

Node JS 

Npm 

Mongo DB 

Você tem o que é preciso? 
Você consegue perceber oportunidades de melhoria nos projetos e na equipe? 
Você é orientado a resultado? 

Então venha pra Digi! 

Onde você vai trabalhar? 

Nosso escritório está localizado na Faria Lima em São Paulo, mas o Trabalho é Remoto 

Quando você começa? 

O Início é Imediato 

 Modelo de Contratação: Regime PJ 

Salário a combinar 

Início imediato 
Vaga PJ/ Home Office 
Remuneração: A combinar 
Benefícios: 

Recesso Remunerado 

Day off de aniversário 

Licença Maternidade 

Licença Paternidade 

Terapias online Zenklub 

 
Interessados enviar CV para: lorraine@grupodigi.com.br 

**#InspiramosSuperação**

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
