### ISSUE TITLE
[São Paulo] Front-End Developer na Fast Shop

### ISSUE THREAD

**Issue by MiltonQuirino** [frontendbr/vagas#561]
## Descrição da vaga

Estamos montando um time para desenvolver aplicações Web App, o candidato tem que ter experiência em  Angular, Bootstrap 4, Sass, TDD, Mobile First, Git, etc.

## Local

Próximo ao metro Santana, Zona norte, São Paulo

## Benefícios

- Plano de saúde
- Seguro de vida
- VR

#### Diferenciais

- 1:30 hr de almoço
- Descontos em promoções internas somente para funcionários

## Requisitos

- Angular;
- Sass;
- Bootstrap 4
- Jasmine
- Karma

**Obrigatórios:**
- 3 anos de experiência com desenvolvimento Web
- Javascript avançado
- TDD
- Angular 2 ou 4
- CSS, Sass, Less
- HTML5
 
**Desejáveis:**
- Git
- HTML5
- Typescript

**Diferenciais:**
-  NodeJs, Java, C#, RoR, CI/CD

## Contratação

CLT

## Nossa empresa

A rede Fast Shop começou a operar em 1986 como uma concessionária autorizada Yamaha. Alguns anos mais tarde, em 1991, a empresa tomou novas diretrizes e deu início a operação de logística de entrega de eletrodomésticos aos contemplados das grandes administradoras de consórcio. Rapidez e bom atendimento foram o foco principal nessa etapa que fez a diretoria da Fast Shop entender que estava pronta para entrar no mercado de varejo.

Em 1996, a Fast Shop inaugurou sua primeira loja dentro de um shopping center. A loja do Shopping Ibirapuera, na capital paulista, focava no atendimento diferenciado. No ano de 2000, a rede inaugurou seu site de vendas pela internet. Hoje, o endereço da empresa (www.fastshop.com.br) recebe mais de 5 milhões de visitantes por mês e oferece a possibilidade do Brasil inteiro comprar pela web.

Paralelamente, ao lançamento da site da Fast Shop, a expansão das lojas físicas continuou. Hoje, além de São Paulo, a Fast Shop está presente em grandes capitais como: Belo Horizonte/MG, Curitiba/PR, Porto Alegre/RS, Rio de Janeiro/RJ e Salvador/BA e outras cidades importantes do Brasil.

Em março de 2008, a Fast Shop lançou a primeira Apple Premium Reseller do Brasil, batizada de A2YOU. Uma Apple Premium Reseller é uma loja local, independente e certificada pela Apple, por ser altamente qualificada em produtos da marca. 

O foco da rede é Encantar o cliente, por isso as lojas tem design arrojado, ambiente acolhedor e layout ergonômico que oferecem aos consumidores: exposição, experimentação, entretenimento, pós-venda e serviços diferenciados.

## Como se candidatar

Por favor envie um email para miltonlq@fastshop.com.br com seu CV anexado - enviar no assunto: Vaga Front-End Developer Angular

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
