### ISSUE TITLE
[Remoto] Front-end Developer @ RD Station

### ISSUE THREAD

**Issue by assisjoao** [frontendbr/vagas#5612]
## Nossa empresa

🚀 Somos uma das maiores empresas SaaS do Brasil. Desenvolvemos uma plataforma 100% brasileira de automação de marketing digital e vendas que hoje tem mais de 30.000 clientes;

🌎 Temos desafios de expansão nacional (onde somos líderes) e de penetração internacional na América Latina;

⭐ As +750 pessoas do nosso time (RDoers, como chamamos por aqui) nos elegeram 7 vezes uma das melhores empresas para se trabalhar no país e nos deram 4.5 estrelas no Glassdoor.

## Descrição da vaga

- Desenvolver novas features para as soluções principalmente em React (conheça todas as nossas linguagens [aqui](https://stackshare.io/resultados-digitais/rd-station); 

- Participar do discovery técnico de novas features, trazendo a visão de engenharia para a solução proposta;

- Executar e medir experimentos no cenário de desenvolvimento em alguns projetos;

- Seguir nossos princípios de Engenharia (Loose Coupling, High Cohesion; Design your code to be easier to understand, not easier to write; Reducing global complexity is more important than reducing local complexity; Automate Everything).

## Local

100% remoto de qualquer lugar do mundo, mesmo após a pandemia ou na nossa sede em Florianópolis/SC, ao lado do Shopping e a 15 min da praia 🏖️

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento frontend, principalmente em React;
- Vivência com boas práticas de desenvolvimento, como Clean Architectures, TDD, BDD, DDD;
- Conhecimento sobre desenvolvimento de software escalável e performático.

**Desejáveis:**
- Experiência trabalhando com micro front-ends;
- Experiência com Design System;
- Atuação com Sidekiq, ElasticSearch;
- Boas noções de desenvolvimento backend, principalmente em Ruby ou Golang;
- Experiência com arquitetura em nuvem (AWS, GCP ou Azure);
- Conhecimento sobre ferramentas de análise de produto, como Mixpanel, Gainsight PX, Amplitude, Hotjar, Google Analytics ou Segment;
- Inglês ou Espanhol a partir do nível intermediário (fala, leitura e escrita);

**Diferenciais:**
- Ser (ou querer se tornar) uma pessoa ativa na comunidade, que compartilha conhecimento dentro e fora da empresa em eventos, artigos, mentorias, iniciativas voluntárias, projetos open source, etc.

## Benefícios

- Plano de saúde sem coparticipação. (Unimed ou Sulamérica)
- Valor adicional de R$ 700/mês pago no Caju, um cartão de crédito flexível, pré-pago e aceito em todo lugar!
- Cultura remote first movida por autonomia e confiança, ajuda de custo de R$ 120/mês durante a pandemia (para sempre em vagas remotas) + R$ 600 para personalizar seu espaço.
- Plano médico e odontológico com cobertura nacional e sem custos em procedimentos, auxílio terapia, auxílio academia, desconto em farmácias, ginástica laboral online, horário flexível, ambiente leve e sem dress code.

Veja a lista completa dos benefícios [aqui](https://talent.rdstation-tm.com/beneficios-rdstation)!

**Diferenciais:**
- Onboarding de ~1 mês, 1:1s com a liderança, ciclos de feedback 360º, carreira em W (especialista, projetos ou gestão), programas e objetivos de desenvolvimento.
- ﻿Plano médico e odontológico com cobertura nacional e sem custos em procedimentos, auxílio terapia, auxílio academia, licença parentalidade estendida para RDMoms e RDaddies, seguro de vida e auxílio funeral.
- Áreas de alimentação com café da manhã, comidinhas e frutas; espaços para descompressão com área de jogos, cochilo, massagem e tobogã; ambientes que promovem a colaboração; ao lado do Shopping e 15 min da praia.

## Contratação

CLT

## Como se candidatar

Candidate-se em: [https://grnh.se/8b31fa292us](https://grnh.se/8b31fa292us)

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
