### ISSUE TITLE
[REMOTE] Front-end Developer na Nash

### ISSUE THREAD

**Issue by lucianoengel** [frontendbr/vagas#5614]
## Nossa empresa

Bitcoin is reaching new all-time highs, but the real crypto revolution hasn't even begun. Distributed ledger technology has the potential to radically change the infrastructure of the global economy – from banking to payments, from trading to saving and investing. These deep changes will be coming over the next decade, and Nash wants to be the company that shapes the new blockchain-based financial space.

Our technology is already leading the industry. You can help us shape our growth trajectory and achieve our goal.  How about being part of the real crypto revolution?

 - Nash is a high growth FinTech startup that uses blockchain technology as infrastructure for the digital finance space. Nash lets users invest in, hold, trade and accept payments with digital currencies. 

 - Our products form an integrated financial services platform that is decentralized and non-custodial, including a revolutionary Digital Assets Exchange, Wallet (iOS and Android), Nash fiat on/off ramp and Nash Link (crypto payments platform).

- Nash is an entirely remote company and our setup allows for flexible hours and time management.

- Nash is a genuinely global company that employs people from across the globe and everyone works remotely. We are seeking a senior front end developer that wants to help us further develop the future killer app for the crypto space.

## Descrição da vaga

We are looking for someone that has at least 3 years experience in designing, building and deploying highly scalable and maintainable client facing UI systems. You are passionate about your craft and have built apps that users love.  

The ideal candidate has experience with the FinTech, cryptocurrency and/or DeFi space, and wants to help us solve the UI/UX challenges so often associated with DeFi applications today.

## Local

Remoto

## Requisitos

**Obrigatórios:**

- English
- 3+ years of experience creating/developing widely adopted UI/UX mobile apps
- Experience creating complex react-native apps
- Good eye for UX/design
- Strong interest or experience in the FinTech, cryptocurrency and/or decentralized finance space
- Ability to work independently in a fast paced work environment

**Desejáveis:**

- Experience developing something using web3 or ethers.js, or deployed a smart contract
- Experience working in remote teams

## Benefícios

-NEX tokens to be received with a vesting period
-Cash allowance for the purchase of equipment and home office supplies
-Unlimited days vacation policy
-Parental leave policy

**Diferenciais:**

-Work from home with flexible hours

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para luciano@nash.io com seu CV anexado - enviar no assunto: Vaga RN

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível

- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
