### ISSUE TITLE
[Rio de Janeiro] UX Designer na Benext

### ISSUE THREAD

**Issue by benextleader** [frontendbr/vagas#5615]
## Nossa empresa

Somos focados em IA (inteligência artificial) e acreditamos que a interação por voz já revoluciona a maneira como acessamos informações. Falar com o celular não é coisa de loucos e comprar também não será. Começar um serviço ou uma relação muito menos. Fortalecer marcas, gerar venda, reter e conhecer seus clientes. Tem muita coisa legal por fazer e a Benext quer ajudar a sua marca a construir relações usando assistentes de voz.

## Descrição da vaga

Buscamos profissionais criativos(as), dedicados(as) e dispostos(as) a encarar diariamente os desafios de serem os(as) melhores parceiros(as) para os nossos clientes. Aqueles(as) que querem incrementar seu portfólio de projetos com grandes marcas, encontram na Benext o lugar ideal. Irá integrar a equipe de UX na criação de experiências em voz (Google Assistente e Amazon Alexa).

## Local

3 dias presenciais, no escritório na Barra da Tijuca - RJ e 2 dias remotos.

## Requisitos

- Perfil criativo, flexível e cooperativo;
- Atencioso com relação aos detalhes;
- Ser organizado.
- Conhecimentos avançados em design, como tipografia, diagramação e teoria das cores;
- Conhecimentos no pacote Adobe (Photoshop, Illustrator e XD);

**Diferenciais:**
- Experiência em Game Design
- Conhecimento de Adobe After Effects

## Contratação

MEI ou PJ

## Como se candidatar

Por favor envie um email para dev+designer@agenciabenext.com com Pretensão e seu CV / Linkedin / Portfólio. 
Enviar no assunto: Vaga UX Designer.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
