### ISSUE TITLE
[REMOTO] Front-end Desenvolvedor na Codex Agro

### ISSUE THREAD

**Issue by luanasantosog** [frontendbr/vagas#5616]
## Nossa empresa

A Codex Agro, é especialista em soluções de inteligência em diagnóstico, prognóstico, monitoramento e inteligência comercial, reunindo grande capacidade em geração e gestão de dados estratégicos para o Agronegócio no Brasil.

## Local

Remoto

## Requisitos

**Formação:**
- Formação Superior na área de TI

**Desejáveis:**
- Conhecimento em Javascript + Vue.JS
- Experiência em projetos de desenvolvimento web
- Experiência em projetos de desenvolvimento com arquitetura corporativa
- Experiência em desenvolvimento com banco de dados Postgres

**Diferenciais:**
- Conhecimento em Java + Springboot

## Contratação

A combinar

## Como se candidatar

Interessados e dentro do perfil, enviar currículo atualizado com pretensão salarial para recrutamento@img.com.br 
informando no assunto: Desenvolvedor Front-end - Github

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
