### ISSUE TITLE
[São Carlos] Front-End Developer no sigalei

### ISSUE THREAD

**Issue by DaniloOliveira28** [frontendbr/vagas#562]
## Descrição da vaga

Estamos buscando um desenvolvedor(a) FrontEnd, com experiência, para nos ajudar a melhorar nossa plataforma web que é utilizada por diversas grandes instituições no Brasil. Nós gostamos de desenvolvedores que se preocupam com a qualidade e eficácia do seu código, buscando sempre desenvolver um código cada vez melhor.

## Local

Escritório, São Carlos

## Benefícios
- à negociar

#### Diferenciais
- startup com alto impacto em acelerado crescimento

## Requisitos

**Obrigatórios:**
- Mínimo de 1 ano de experiência com HTML, CSS, Javascript em projetos digitais complexos, não apenas websites.
- Bom conhecimento em boas práticas de programação sempre pensando em criar componentes reutilizáveis e testáveis.
- Controle de versão (.git)
- PostgreSQL

**Desejáveis:**
- Experiência em desenvolvimento ágil (SCRUM)

**Diferenciais:**
- NodeJs
- Elastic Search
- React Native
- Graphql/Relay
- Webpack e pré-processadores (SASS, LESS)
- Experiência com bibliotecas de gráficos (Chartjs, D3, Sigmajs)

## Contratação
PJ a combinar

## Nossa empresa

Nós somos uma Startup em acelerado crescimento que está ajudando a construir um novo Brasil melhorando a forma como fazemos política.

Acreditamos em uma nova política, mais profissional, transparente e republicana onde os mais diversos grupos podem e devem monitorar e influenciar a política.

Nós temos um equipe extremamente capacitada em diversas áreas da computação. É uma oportunidade excelente para quem almeja ajudar a construir uma empresa inovadora e ao mesmo tempo se tornar um excelente desenvolvedor Full Stack no futuro.

## Como se candidatar

Acessar: sigalei.com.br/vaga

**Comment by DaniloOliveira28** [comment]
@LFeh Obrigado por colocar as labels. Poderia somente, ao invés de sênior, colocar júnior? Gracias

**Comment by ericmadureira** [comment]
O Danilo é gente fina e inteligente, essa vaga é boa.
