### ISSUE TITLE
[Remoto] Pessoa Engenheira de Software - Mobile (React Native) @ Z1

### ISSUE THREAD

**Issue by vagas-Z1** [frontendbr/vagas#5620]
## Nossa empresa

A Z1 é uma conta digital para adolescentes. Nosso propósito é dar autonomia financeira para adolescentes que não podem ter conta no banco nem cartão. A Z1 atua através da educação financeira, ou seja, criamos funcionalidades para adolescentes aprenderem a ter responsabilidade financeira e acesso à economia digital com independência.
 
Começamos a nossa história em 2019 e lançamos o nosso app em janeiro de 2021. Desde então, estamos crescendo a uma taxa de 30% por semana e 200% por mês, e já recebemos mais de R$18 milhões em aportes de investidores de primeira linha, como a aceleradora [Y Combinator](https://www.ycombinator.com/) e os fundos de venture capital [MAYA Capital](https://www.maya.capital/), [Homebrew](https://homebrew.co/), [Mantis](https://www.mantisvc.com/) e [Clocktower](https://www.clocktowerventures.com/), entre outros.
 
Saiba mais em [http://z1.app/](http://z1.app/) e nessas matérias no [Brazil Journal](https://braziljournal.com/z1-o-banco-teen-que-quer-crescer-com-o-cliente), [Exame](https://exame.com/pme/z1-a-fintech-da-geracao-z-recebe-aporte-da-y-combinator/) e [Estadão](https://link.estadao.com.br/noticias/inovacao,fintech-z1-chega-ao-mercado-com-conta-digital-para-adolescentes,70003513832).

Falando sobre diversidade, essa é uma das principais batalhas da Z1. A diversidade e a luta pela equidade é um pilar central da Z1. Queremos ser a empresa mais diversa do Brasil. Por isso, todes são bem vindes!

Usamos a linguagem neutra e respeitamos os pronomes escolhidos por cada pessoa. A linguagem neutra é utilizada para evitar generalizações no masculino e incluir quem não se sente confortável em se associar a limitação masculina e feminina da língua portuguesa tradicional.

## Descrição da vaga

Manutenção e desenvolvimento de novas funcionalidades no app da Z1.
Apesar do nosso crescimento acelerado, ainda estamos no começo, então é uma oportunidade para participar do projeto como um todo, e não apenas o desenvolvimento de códigos isolados que você não sabe muito o impacto que terá para o cliente final.
Você conseguirá ver o resultado do seu trabalho fazendo a diferença no dia a dia dos nossos uzers.

## Local

Durante a pandemia estamos trabalhando de forma 100% remota. 
Quando a pandemia terminar, teremos um escritório em São Paulo/SP, mas a presença será sempre opcional.
Você pode se candidatar de qualquer lugar do Brasil. :)

## Requisitos

Nossa stack para Mobile é composta por Typescript, GraphQL com Apollo, Expo, Jest e Appium. 
Para trabalhar com a gente, você precisa de:

- Conhecimento em typescript;
- Pelo menos 2 anos de experiência com Mobile - React Native;
- Conhecimento com uso de Hooks;
- Conhecimento em Git, testes unitários e integrações

## Benefícios

- Plano de saúde (a Z1 paga 100% do plano Sulamérica, mesmo você sendo PJ)
- 22 dias úteis de férias, que você pode tirar como quiser, válidos desde o seu 1º dia
- Bolsa terapia para pessoas minorizadas
- Programa RetificaZ1 para pessoas trans

## Contratação

- Faixa salarial entre 8k e 12k, contratação PJ

## Como se candidatar

Você pode se candidatar [clicando aqui](https://jobs.lever.co/z1.app/649e2162-39ae-4423-97af-3abc65b3bc5a)
ou enviando seu currículo para vagas.z1.app@gmail.com, colocando no assunto Mobile PL

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
