### ISSUE TITLE
[REMOTO] UX|UI Designer na Conquer (ByIntera)

### ISSUE THREAD

**Issue by AdeSegundo** [frontendbr/vagas#5625]
**UX|UI Designer na Escola Conquer**

**Inscreva-se em https://bit.ly/3kIJWlx**

A **Conquer** nasceu da nossa **insatisfação com as instituições tradicionais** – faculdades e pós-graduações. Nossa missão é **transformar a educação no Brasil**, ajudando nossos alunos e empresas parceiras no **desenvolvimento das habilidades fundamentais para todo profissional de alta performance**. Portanto, **se você não se contenta com o médio, esse é o lugar certo para você!**

## FICHA TÉCNICA

**Cargo: UX|UI Designer
Nível: Sênior
Modelo de contratação: CLT**

## REQUISITOS

Sólida experiência desenhando UX para sistemas complexos (plus se for de ensino);
Conhecimento dos fundamentos em Design Gráfico (cores, tipografias e composição visual);
Experiência com protótipos navegáveis a partir de ferramentas;
Vivencia com analise de comportamentos e interação com usuários.;
Defesa do Design: estar apto a justificar didaticamente e tecnicamente as decisões de design tomadas

## DIFERENCIAIS

Parâmetros quantitativos e qualitativos de pesquisa;
Experiência com desenvolvimento;

**Saiba mais em https://bit.ly/3kIJWlx**

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
