### ISSUE TITLE
[Remote] Freelance TypeScript Engineer na Thoughtful

### ISSUE THREAD

**Issue by cjroth** [frontendbr/vagas#5626]
> Vaga Remota durante a pandemia

## Nossa empresa

[Thoughtful](https://www.thoughtfulcompany.io/) is an botique international product studio based in New York City that builds and launches beautiful technology products. Currently we have seven active products.

## Descrição da vaga

We currently have multiple freelance openings for projects using React and React Native. Our preferred frontend web stack is Next.js, Blitz.js, Ant Design, Vercel, GraphQL, and styled-components, although we consider all possibilities when starting new projects.

## Local

Remote

## Requisitos

**Obrigatórios:**
We consider all skill levels, although we prefer a minimum of 2 years of professional experience and at least 6 months of experience working remotely as a freelancer.

- Fluent English
- TypeScript Proficiency
- **Minimum of 15 hours per week**

**Desejáveis:**
- Some backend experience - at least enough to communicate effectively with backend engineers and understand how backends work.

**Diferenciais:**
- Set your own hours
- Minimal meetings - we have a strong async culture
- Work with new tech stacks
- Work with US startups

## Contratação

PJ a combinar

## Como se candidatar

Please email careers+frontendbr@thoughtfulcompany.io

## Tempo médio de feedbacks

1-2 weeks

#### Alocação
- Remoto

#### Regime
- Freela

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
