### ISSUE TITLE
[REMOTO] Desenvolvedor Mobile na Codex Agro

### ISSUE THREAD

**Issue by luanasantosog** [frontendbr/vagas#5628]
## Nossa empresa

A Codex Agro, é especialista em soluções de inteligência em diagnóstico, prognóstico, monitoramento e inteligência comercial, reunindo grande capacidade em geração e gestão de dados estratégicos para o Agronegócio no Brasil.

## Local

Remoto

## Requisitos

- Formação Superior na área de TI
- Experiência com linguagens nativas utilizadas em mobiles (Java e Swift);
- Experiência com ReactNative com plataformas iOS e Android;
- Experiência com Flutter;
- Experiência com padrões de interface móvel;
- Experiência com testes de integração de aplicativos móveis com plataformas web;
- Experiência em banco de dados (Postgres).

## Contratação

A combinar

## Como se candidatar

Interessados e dentro do perfil, enviar currículo atualizado com pretensão salarial para recrutamento@img.com.br 
informando no assunto: Desenvolvedor Mobile - Github

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
