### ISSUE TITLE
[São Paulo] Front-End Developer Sênior na Callix

### ISSUE THREAD

**Issue by octaconsulting** [frontendbr/vagas#563]
## Descrição da vaga

Análise e Desenvolvimento do front-end de plataforma de telefonia VoIP,
baseada em sistema operacional Linux, Ruby e Ruby on Rails, PostgreSQL,
Sidekiq e Redis.

## Local

Escritório, São Paulo - Vila Olímpia

## Benefícios

- Plano de saúde Bradesco Top Nacional;
- Vale Refeição compatível com região (Vila Olímpia).

#### Diferenciais

- Horário de trabalho flexível;
- Cultura startup.

## Requisitos

**Obrigatórios:**
- Experiência consistente, sênior, como Front-End!
• Domínio de HTML, JS, CSS / SASS
• Conhecimento profundo de pelo menos um framework
client-side JS (React, Ember, Aurelia, Angular, etc)
• Preocupação com organização, legibilidade e reuso de
código
• Experiência com pelo menos um framework de testes
(Karma, Jasmine, Mocha etc)
• Leitura técnica fluente de inglês

**Desejáveis:**
• Experiência em React, Ember ou Aurelia;
• Conhecimento de Ruby e Ruby on Rails;
• Conhecimento de Typescript;
• Familiaridade com Docker;
• Conhecimento de patterns de desenvolvimento;
• Desejável experiência com DevOps;
• Experiência com versionamento Git ou similar;
• Experiência com testes unitários, integrados e de
aceitação.

**Diferenciais:**
Software livre na veia, Ruby/PostGreSQL, Debian/Docker, integração contínua, tecnologia de ponta em aplicações desenhadas para nuvem.

## Contratação

CLT (não contratantes de PJ)

## Nossa empresa

A Callix é uma startup que busca gerar disrupção no mundo de call-centers.
Normalmente call-centers usam telefonia dedicada e hardware dedicado, além
de locais físicos dedicados.

A proposta da Callix é viabilizar operações de call center só com um web-
browser e acesso a internet. Entre outras coisas, viabiliza operações de call

center em que todo mundo pode ficar em casa.
Estamos montando uma equipe de desenvolvimento de produtos, com
investimento de longo prazo, e a vaga é nesta equipe.
Estamos trabalhando com software livre na veia, Ruby/PostGreSQL,
Debian/Docker, integração contínua e outras práticas interessantes.
Desejamos conhecer profissionais que sejam apaixonados por tecnologia, que
queiram trabalhar com tecnologias de ponta em aplicações desenhadas para a
nuvem, e dispostos a trabalhar em equipe em um ambiente com cultura de
start-up.

## Como se candidatar

Por favor envie um email para mayara@octarh.com com seu CV anexado, e enviar no assunto: Vaga Front-End Developer.

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
