### ISSUE TITLE
[Remoto / EUA] Fullstack Python/Angular Developer and Front-end Angular na ENER

### ISSUE THREAD

**Issue by matheuskingston** [frontendbr/vagas#5633]
Se junte a a mais nova Startup dos EUA, caso tenha interesse em trabalhar em um projeto internacional e ganhar em dólar, mande seu cv!!

Local
Remoto!🌎

Requisitos
 Angular, JavaScript, AngularJS and Python
Inglês avançado/fluente

Como se candidatar
Enviar cv para recrutamento@qualiconsultoria.com

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
