### ISSUE TITLE
[Remota] Full Stack Developer  PL (JavaScript (AngularJS /JAVA) na Stefanini

### ISSUE THREAD

**Issue by BARBOSALARISSA** [frontendbr/vagas#5634]
> Vaga Remota

## Nossa empresa

Somos a maior multinacional brasileira de TI e estamos entre as 100 maiores empresas no mundo no ramo da TI 💻, presente em 41 países com +25k colaboradores global 🌎

Visamos sempre o nosso propósito de co-criar soluções para um futuro melhor e acreditamos no respeito, nos princípios éticos e íntegros, assim como, na humildade em aprender!

É importante ressaltar o respeito a diversidade, pois entendemos que as diferenças tornam as pessoas únicas, por isso, não fazemos qualquer distinção entre nossos candidatos. Para nós, não importa idade, gênero, raça/etnia, deficiência, orientação sexual, origem, estética ou constituição familiar. 

Acreditamos no potencial dos nossos colaboradores! ✨

Se identificou? Então venha para a Stefanini, nós estamos ansiosos para te conhecer! 🤩

## Descrição da vaga

- Java

  - HTML 5

   - CSS 3

   - JavaScript (AngularJS)

   - Swagger

   - REST

   - Sistema Operacional Linux

   - Jenkins

   - NPM
   
   - Maven

   - Docker

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com JavaScript e/ou AngularJS
- 2 anos de experiência com Java

## Benefícios

- VA / VR
- Gympass
- Plano de saúde
- Plano Odontológico
- Parceria AWS
- Descontos Alura
- Go Integro (Plataforma de descontos em sites)
- Rosetta Stone (Software de ensino de Lingua)
- Allpoints (Plataforma de moeda de viagens)
- SESC
- YALO

## Contratação

CLT 

## Como se candidatar

Por favor envie um email para lsbarbosa@stefanini.com com seu CV anexado - enviar no assunto: Full Stack Java PL

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: lsbarbosa@stefanini.com

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
