### ISSUE TITLE
[Remoto] Front-End Developer na SHAKACODE

### ISSUE THREAD

**Issue by marcusvmsa** [frontendbr/vagas#564]
## Descrição da vaga

Você irá trabalhar em uma empresa global com developers de várias partes do mundo. Temos nosso produto interno: [www.friendsandguests.com](http://www.friendsandguests.com) e também prestamos serviços de consultorias para várias empresas ao redor do globo.

## Local

Remoto

#### Diferenciais

- Trabalho remotamente
- Horário flexível

## Requisitos

**Obrigatórios:**
- fluencia em ingles
- conhecimentos em React/Redux/React Navite e JS

**Desejáveis:**
- conhecimentos em ruby on rails

**Diferenciais:**
- projetos opensource

## Contratação

Independent contractor

## Nossa empresa

A global web development software consultancy and product company. We’re focused on what we believe to be the best technologies for web development. Today, those are Ruby on Rails and React. But it’s not just us, we like to think that it’s the larger WE in the open source community that loves collaborating on beautiful code.
More info, please visit: [http://www.shakacode.com/2015/09/17/who-is-shaka-code.html](http://www.shakacode.com/2015/09/17/who-is-shaka-code.html)

## Como se candidatar

Por favor envie um email para marcus@friendsandguests.com falando um pouco sobre você e sua experiencia e também informando sua pretensão em U$/hora.

**Comment by LFeh** [comment]
Aberto ainda?
