### ISSUE TITLE
[REMOTO] Front-end Developer Angular na Trakto

### ISSUE THREAD

**Issue by jorgehsrocha** [frontendbr/vagas#5640]
## Nossa empresa
<img width="1597" alt="Captura de Tela 2021-09-03 às 09 41 02" src="https://user-images.githubusercontent.com/5194011/132008814-6d8610f3-36d0-46a2-9e70-2c71e7480866.png">

A Trakto é uma startup uma startup para criação de "design's" digitais e impressos (https://www.youtube.com/watch?v=FLEMUC1peqs). Atuamos no Brasil e outros países, contamos com mais de 30k usuários ativos na plataforma.

## Estudos de caso do Google sobre a Trakto
**Google Cloud** - https://cloud.google.com/customers/trakto
**Google For Startups** - https://startup.google.com/stories/trakto/
**História e valores da Trakto** - https://www.youtube.com/watch?v=Vet268jSUVQ

## Descrição da vaga

Como pessoa desenvolvedora Frontend na Trakto você terá como responsabilidades:

- Implementar e manter novas e antigas funcionalidades;
- Componentizar itens de UI e features globais entre as aplicações;
- Garantir qualidade de processamento e performance da camada de front-end;
- Criar testes automatizados de UI a fim de garantir fidelidade para views e experiência de uso;
- Estruturar novas UI com qualidade para manter UX compatível com nossos clientes;
- Sugerir e estruturar a arquitetura front-end;
- Sugerir novas ferramentas, tecnologias e arquiteturas que possam melhorar as aplicações e serviços;

## Local

100% Remoto

## Requisitos

- CSS3 e HTML5;
- Git e metodologia utilizando GitFlow ;
- Experiência consolidada com Typescript e Javascript;
- Experiência profissional com produtos reais utilizando o Angular 5+, VueJS ou React;
- Experiência com componentização e reuso de estruturas front-end;
- Noções ou experiência com padrões de projeto que possam garantir integrações utilizando API’s;

**Desejáveis:**
- Conhecimento em testes automatizados;
- Experiência com ferramentas de análise de perfomance a nível de frontend;

## Benefícios
- Time off;
- Ajuda de custos com cursos;

**Diferenciais:**
- Uso de stack de grande escala;
- Percepção do impacto do seu trabalho num grande número de usuários;

## Contratação
PJ 

## Como se candidatar
Por favor, realizar a **candidatura para vaga em: https://trakto.io/carreiras**

## Tempo médio de feedbacks
Costumamos enviar **feedbacks em até 15 dias** após cada processo.
E-mail para contato em caso de não haver resposta: marinatorres@trakto.io

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
