### ISSUE TITLE
[Remoto] Front-end Developer na Mout'S

### ISSUE THREAD

**Issue by carinerh** [frontendbr/vagas#5643]
## Nossa empresa

A Mouts'S Soluções em TI oferece à empresas de diversos portes e segmentos, serviços e soluções inovadoras em tecnologia da informação. Nosso foco é proporcionar maior competitividade, agilidade e sustentabilidade para nossos clientes diante de um mercado cada vez mais desafiador e complexo. Acreditamos na importância das pessoas e por isso continuamente investimos no engajamento e no aumento da performance de seu time. Desenvolvimento humano é foco, e hoje temos orgulho e confiança em apresentar uma equipe formada por colaboradores autônomos, líderes de suas próprias decisões, plenos em realizar entregas assertivas e com maturidade para gerenciar prazos de forma responsável.
## Descrição da vaga

O que você vai fazer?
 Desenvolver códigos bem estruturados utilizando padrões, estáveis, confiáveis e fáceis de manter.
- Desenvolver códigos e soluções sempre pensando em eficiência, escalabilidade e estabilidade. 
- Realização de code reviews 
-  Atuação em equipes ágeis 

## Local

100% remoto

## Requisitos

**Obrigatórios:**
- Conhecimento e sólida experiência em Angular e/ou React
- Conhecimento de Git e GitFlow
- Experiencia em Cloud Computing principalmente serviços da Azure ou AWS
- Experiencia em arquiteturas de API e Microserviços (Container Docker e AKS - Azure Kubernetes Service)
- Conhecimento avançado e experiência em Banco de Dados Relacionais (MySQL e/ou Maria DB) 
- Conhecimento sólido e experiência na utilização de padrões de projeto e design de desenvolvimento bem como melhores práticas (Design Patterns, Clean Code, S.O.L.I.D)

**Diferenciais:**
- Experiencia em NextJS
- Experiencia em desenvolvimento PHP (framework Laravel)
- Conhecimento em TDD;
- Experiencia em automação de testes e testes Unitários (PHPUnit)
- Já ter trabalhado com metodologias ágeis (e.g Scrum, Kanbam)
- Conhecimento de Azure DevOps

## Contratação

PJ ou Cooperado

## Como se candidatar

Por favor envie um email para carine.machado@mouts.info seu CV anexado - enviar no assunto: Vaga Front-End

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 4 dias após cada processo.
E-mail para contato em caso de não haver resposta: carine.machado@mouts.info
#### Alocação
- Remoto

#### Regime
- PJ
- Cooperado

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
