### ISSUE TITLE
[Remoto] Front-end React/RN Developer na Agriness

### ISSUE THREAD

**Issue by jananessi** [frontendbr/vagas#5644]
## Nossa empresa

Nós, da Agriness, somos tech e somos agro. Nascemos no agro e colocamos a tecnologia a serviço das pessoas, construindo soluções em conjunto e estabelecendo relações duradouras e de confiança com nossos clientes. Nosso desafio é escalar nossas soluções para o mundo, fortalecendo ainda mais as nossas relações. Para isso, precisamos ter com a gente as melhores pessoas. Vamos juntos? Vem ser Agriness!

Trabalhamos muito para tornar o agronegócio mais produtivo e rentável, não somente no Brasil, mas no mundo, atualmente realizamos a gestão de 95% da suinocultura do mercado brasileiro. Buscamos constantemente o crescimento e a expansão, hoje estamos presentes em 23 países. Nosso desafio é escalar a Agriness para o mundo! Para isso, precisamos ter com a gente as melhores pessoas!

## Descrição da vaga

Interagir com os desenvolvedores e integrantes da sua Squad para definição e implementação das soluções planejadas;
Implementar código seguindo os padrões de qualidade definidos pela área, por meio de uso de testes automatizados, processos de integração contínua, revisão de código, buscando disseminar boas práticas;
Desenvolver soluções multicamadas em uma arquitetura de micro serviços, utilizando para isso tecnologias já adotadas pela empresa como React Native, NodeJS, JavaScript, entre outras;
Prezar pela otimização de processos de forma a evitar atividades manuais e repetitivas;
Dev mais sênior terão como missão apoiar o crescimento dos menos experientes, servindo como referência em conhecimentos e boas práticas;
Atuar junto ao PO, Designers e Analistas de Negócio para a construção dos melhores caminhos para a criação dos produtos.

## Local

Remoto

## Requisitos

**Obrigatórios:**
Formação na área de tecnologia;
Experiência com React ou React Native, NodeJS, Git;
Experiência com desenvolvimento de aplicativos móveis;
Prática de code review/pull request;
Experiência com testes automatizados;
Experiência em integração com API’s REST.

**Desejáveis:**
Conhecer boas práticas de Devops e Continuous Integration;
Possuir conhecimento em Typescript, RxJS, Redux Saga, Expo, Offline-first;
Ter experiências anteriores com Apps ligados a IoT, Analytics, AI, entre outras tecnologias.
Possuir inglês intermediário.

## Benefícios

-Ginástica Laboral duas vezes por semana.
-Previdência Privada.
-Folga no dia do aniversário.
-Parcerias de descontos com convênios.
-Pacote de benefícios tradicionais: VR/VA, Auxílio Home Office, Plano de Saúde
-Possibilidade de trabalhar 100% remoto.
-Remuneração variável

## Contratação

CLT

## Como se candidatar

Por favor cadastre-se no link: https://vagas.hunterco.com.br/job/611d86a6bc83ad001e09f437?c=3795

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.
E-mail para contato em caso de não haver resposta: janaina.nessi@parceirohunterco.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
