### ISSUE TITLE
[Itaperuna - RJ] Front-end Developer na iNova

### ISSUE THREAD

**Issue by carlosmoliv** [frontendbr/vagas#5645]
## iNova

Somos o grupo iNova. A maior transformadora digital da América Latina. A iNova nasceu da expertise de transformar pessoas e empresas em influenciadores digitais, através do melhor que elas têm a oferecer. 

## Descrição da vaga

Estamos formando uma equipe Dev para um projeto que vai possuir as seguintes stacks: React, React Native, Node e MongoDB. 

## Local

Exemplo: Remoto ou Escritório, RJ, Itaperuna, Aeroporto

## Requisitos

**Obrigatórios:**
- Experiência com React ou React Native
- Conhecimentos em consumir API em GraphQL
- Conhecimentos em TypeScript

## Contratação

A combinar

## Como se candidatar

Por favor envie um email para tequero@inovany.com.br com seu CV anexado ou portfolio de projetos já desenvolvidos - enviar no assunto: Vaga ReactJS ou React Native

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: carlosoliveira@inovany.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- Freela
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
