### ISSUE TITLE
[São Paulo] Front-End Developer em Empresa de Soluções Tecnológicas e Conteúdos Digitais

### ISSUE THREAD

**Issue by octaconsulting** [frontendbr/vagas#565]
## Descrição da vaga

Projeto em framework React.

## Local

Escritório, São Paulo - Zona Norte

## Benefícios

- VT; 
-VR;
-Plano de Saúde (Sul América).

**Diferenciais:**
- Como a empresa - que já atende grandes clientes, como Estado de S. Paulo, Folha de S. Paulo, PWC, Etapa, O Globo, Mercedes Benz, Globo, Grupo de Mídia São Paulo, Editora Saraiva, Pão de Açúcar, Editora Globo, Honda, Tetra Pak, Tecnica, Pearson, Mackenzie, Caras, Editora Melhoramentos, Abril, Valor Econômico, Anglo Editora de Ensino, e muitos outros - está em um momento de total expansão, essa circunstância será excelente para o profissional que a acompanhar, contando que a visibilidade já é grande, e a tendência e objetivo é crescer cada vez mais, incluindo também o aprendizado constante principalmente pela atuação forte no ramo educacional.

## Requisitos

**Obrigatórios:**
- Experiência sênior em HTML, CSS, Javascript e framework React.

## Contratação

CLT;

## Nossa empresa
A oportunidade é para uma empresa de soluções tecnológicas, e disponibilização de conteúdos digitais. A marca registrada deles são as soluções parrudas e flexíveis em criação, digitalização, enriquecimento, comercialização, distribuição e consumo interativo de conteúdo também. É a líder nos segmentos educacional, empresarial e editorial, há 15 anos! A ideia principal é promover a melhor experiência ao usuário, e gerar novas oportunidades pra quem cria, ou distribui o conteúdo. (Nós somos uma consultoria que está os assessorando nessa oportunidade, não temos permissão contratual para divulgar e publicar o nome da empresa antes da inserção do profissional no processo seletivo, pedimos compreensão.)

## Como se candidatar

Por favor, se se encontra dentro do perfil, envie um email para mayara@octarh.com com seu currículo anexo, com "Front-End Developer Sênior" no assunto. 

(Pedimos também, por gentileza, que envie somente em caso de possuir a experiência descrita.)

**Comment by LFeh** [comment]
Qual o nome da empresa?

**Comment by talitapagani** [comment]
@octaconsulting Pessoal, conforme as regras do repositório (https://github.com/frontendbr/vagas/blob/master/README.md), não são aceitas vagas sem o nome da empresa contratante. Caso vocês não possam mesmo disponibilizar esta informação, não podem publicar vagas neste fórum, infelizmente, ok?

**Comment by nandosangenetto** [comment]
@LFeh eles já criaram uma vaga aqui: https://github.com/frontendbr/vagas/issues/557#issuecomment-332307396

E citaram tal comentário sobre o nome da empresa:
> Nós somos uma consultoria que está os assessorando nessa oportunidade, não temos permissão contratual para divulgar e publicar o nome da empresa antes da inserção do profissional no processo seletivo, pedimos compreensão.

**Comment by octaconsulting** [comment]
Solicitamos um breve aguardo sobre tal impossibilidade, contatamos o RH da empresa pedindo permissão para essa abertura, e estamos aguardando retorno!

**Comment by LFeh** [comment]
Ok, nos avise

**Comment by LFeh** [comment]
@nandosangenetto vou fechar essa
