### ISSUE TITLE
[Campinas] Back-end Developer NodeJS na ART IT

### ISSUE THREAD

**Issue by TechAngelica** [frontendbr/vagas#5653]
### Nossa empresa
Há 18 anos, a ART IT, transforma negócios em experiências digitais. Por meio de um ecossistema de serviços que alia tecnologia da informação, inovação, design e metodologia, leva à frente iniciativas que empoderam os clientes, tornando-os mais competitivos e possibilitando a eles criar novos modelos de negócios.

## Descrição da vaga
- Experiência com Node JS

- Express JS

- Experiência com teste unitário utilizando o JEST

- Experiência em projetos com SCRUM

- Banco de dados relacional

-API REST, Filas

- Git

- Boas práticas de desenvolvimento

 Projeto em NodeJS, etc.

## Local

 Remoto 

**Obrigatórios:**
- 4 anos de experiência com Node

## Benefícios
- 1/3 de férias

## Contratação

PJ 

## Como se candidatar

Por favor envie um email para amachado@artit.com.br com seu CV anexado - enviar no assunto: Vaga NodeJS

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: amachado@artit.com.br

#### Alocação
- Alocado
- Remoto

#### Regime

- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by TechAngelica** [comment]
Bom dia!
Tudo bem?

Não esta mais aberta essa oportunidade.

Obrigada
Atenciosamente,

Angélica Muniz Aparecido
***@***.***


Em qua., 10 de nov. de 2021 às 21:26, Felipe Fialho <
***@***.***> escreveu:
