### ISSUE TITLE
[Remoto] Front-end Developer na LibreCode coop

### ISSUE THREAD

**Issue by vitormattos** [frontendbr/vagas#5654]
## Nossa empresa

[<img src="https://raw.githubusercontent.com/LibreCodeCoop/jobs/main/assets/logo.png" width="150px"/>](https://librecode.coop)

A [LibreCode](https://librecode.coop) é uma cooperativa de devs de software livre em busca de uma forma de trabalhar diferente das que já experimentamos no mundo corporativo.

## Descrição da vaga

Primeira demanda será finalizar implementação [deste milestone](https://gitlab.com/librecodecoop/libresign/libresign/-/milestones/4). Atuará principalmente na implementação e manutenção do app LibreSign e outros apps para Nextcloud.

## Local

100% remoto

## Requisitos

**Obrigatórios:**
* VueJS
* Docker e Linux
* Prototipação de telas seguindo guia de estilo previamente definido

**Desejáveis:**
* projetos opensource
* Implementação de sites com base em design previamente definido

**Diferenciais:**
* Experiência com aplicativos mobile

## Benefícios

- Plano de saúde
- Seguro de vida
- Participação nos lucros
- Remuneração inicial variando entre 4 a 10k / mês

**Diferenciais:**
- Ser sócio da cooperativa

## Contratação

Cooperado (sócio)

## Como se candidatar
Entre no grupo https://t.me/LibreCodeCoop e diga que tem interesse em participar da vaga.

Mais informações no repositório [jobs](https://github.com/LibreCodeCoop/jobs)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em poucas horas após contato no grupo público da coop.

E-mail para contato em caso de não haver resposta: vagas@librecode.coop

#### Alocação
- 100% remoto

#### Regime
- Sócio

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by vitormattos** [comment]
@felipefialho pode remover o label de remoto durante a pandemia? Acabei deixando por acidente esta frase e entrou este label.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by vitormattos** [comment]
Olá @felipefialho permanece aberta sim.

**Comment by vitormattos** [comment]
@felipefialho coloquei por acidente o label remoto durante a pandemia mas é remoto forever.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by vitormattos** [comment]
Vaga em aberto

**Comment by vinicius73** [comment]
Vaga em aberto.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by vitormattos** [comment]
Vaga em aberto

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
