### ISSUE TITLE
[Home-Office] Front-end Developer Angular na EVERIS Group NttData

### ISSUE THREAD

**Issue by msrmarcio** [frontendbr/vagas#5655]
> Vaga 100% Remota e temos Vagas Remota durante a pandemia

## Nossa empresa: Everis

Na everis provemos um ambiente muito colaborativo. Também incentivamos o crescimento profissional, estimulando seu desenvolvimento.  A empresa fornece um grande pacote de beneficios, sendo muito atrativo.

## Descrição da vaga

•	Fazer a ponte entre a parte visual e a implementação técnica fornecida pelos desenvolvedores Back-end, consumindo serviços e implementando o uso e a geração de dados no Front-End;  
•	Forte atuação em desenvolvimento Javascript;  
•	Domínio de pelo menos um dos frameworks Angular (4+),  
•	Vivencia em HTML5, CSS e JS (ES6 e TypeScript); 
•	Entender controle de versão
•	Entender NPM
•	Conhecimento em versionamento: Git;  
•	Responsável por criar e integrar as APIs do projeto;  
•	Participar de forma engajada em toda as cerimonias do SCRUM como Sprint Planning, a Daily Meeting, a Sprint Review e a Sprint Retrospective.  
•	Desenvolver com qualidade o próprio código. 

## Local

REMOTO HOME OFFICE

## Requisitos

**Obrigatórios:**
- a partir de 1 anos de experiência com Angular
- conhecer Javascript, Css e Html 5
- Ter noções de otimização 
- Conhecer Injeção de dependência
- Git ou outro versionador
 

**Diferenciais:**
- conhecimentos em C#

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ X/dia
- Auxílio creche (conforme regra)
- ...e outros a ser informado na entrevista

## Contratação

CLT FULL

## Como se candidatar

Por favor envie um email para msantrod@everis.com com seu CV anexado - enviar no assunto: Vaga Front-End Angular

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo. 

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT 

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
