### ISSUE TITLE
[HOME OFFICE] Back-end Developer na EVERIS

### ISSUE THREAD

**Issue by msrmarcio** [frontendbr/vagas#5656]
> Vaga 100% Remota e temos Vagas Remota durante a pandemia

## Nossa empresa: Everis

Na everis provemos um ambiente muito colaborativo. Também incentivamos o crescimento profissional, estimulando seu desenvolvimento.  A empresa fornece um grande pacote de benefícios, sendo muito atrativo.

## Descrição da vaga

- Habilidades Imprescindíveis: 
· Conhecimento avançados em .NET C# 
· Conhecimento avançados em .NET C# Core 
· Conhecimento avançados em .NET ASP.NET 
· Conhecimento avançados em .NET ASP.NET CORE 
· Conhecimento avançado em ASP.Net Web API (REST) (Micro Serviços) 
· Conhecimento avançado em ORM (Entity Framework e Nhibernate) 
· Conhecimento avançado em Padrões de desenvolvimento (MVC) 
· Conhecimento avançados de SQL SERVER (TRANSACT SQL) 
· Conhecimentos em HTML, CSS, BOOTSTRAP e JavaScript 
· Formação Superior em TI 
· Mínimo de 1 anos de experiência atuando como desenvolvedor .NET 
 
Habilidades Desejáveis: 
· Conhecimento em metodologia Ágil (SCRUM) 
· Conhecimento de TFS | GIT | ou outro software de controle de versão
· Conhecimento em Padrões de desenvolvimento (CQRS, DDD)  

## Local

REMOTO HOME OFFICE

## Requisitos

**Obrigatórios:**
- a partir de 1 anos de experiência com Angular
- conhecer principalmente .Net Core | .Net framework desejável
- Ter noções uso de ADO, ORM e Micro-ORM
- Conhecer Injeção de dependência 
- Conhecer Asp.Net Mvc e Razor Page
 

**Diferenciais:**
- conhecimentos em C#
- Conhecimento das versões mais novas do C#
- Entender o funcionamento do .Net Core

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ X/dia
- Auxílio creche (conforme regra)
- ...e outros a ser informado na entrevista

## Contratação

CLT FULL

## Como se candidatar

Por favor envie um email para msantrod@everis.com com seu CV anexado - enviar no assunto: Vaga Back-End Angular

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo. 

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT 

#### Nível - Buscamos todos os níveis atualmente
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
