### ISSUE TITLE
[LONDON] Pleno Front-end Developer na CodeLeap

### ISSUE THREAD

**Issue by viniroth** [frontendbr/vagas#5658]
Introdução:
Olá! Tudo bem? Somos uma pequena agência de desenvolvimento de software com sede e clientes em Londres (Reino Unido).
Estamos procurando um jovem saiyajin para se juntar ao nosso time e auxiliar nossos Guerreiros Z em diversas batalhas para defender a Terra contra qualquer vilão que aparecer, seja um extraterrestre ou um deus! Brincadeiras à parte, somos uma empresa focada em desenvolver soluções incríveis para empreendedores da Europa que possuem ou estão em busca de abrir seus próprios negócios, em sua maioria do Reino Unido.

A vaga é para um desenvolvedor pleno experiente (entre 2 a 4 anos de experiência), que tem como objetivo se juntar a uma empresa promissora e crescer a longo prazo junto dela. Algumas de suas atividades são ajudar no desenvolvimento de produtos dos clientes e construir a identidade da nossa empresa no longo prazo. Você terá grandes responsabilidades e a oportunidade de tomar decisões importantes dentro da empresa em conjunto com outros desenvolvedores de diferentes níveis.

O candidato ideal é alguém que curte tecnologia, websites, aplicativos, minimalismo e é apaixonado pela arte da programação. Com relação ao inglês, exigimos nível intermediário (leitura e escrita). Cada projeto exige um approach diferente e traz novos desafios, sempre temos algo diferente para fazer! No médio e longo prazo temos interesse em desenvolver nossos próprios produtos, então se você gosta da ideia de experimentar internamente e criar coisas novas, você encontrou o lugar certo!

Local:
- Remoto - Central em Londres, Reino Unido.

Remuneração:
- Salário baseado na média do mercado, varia de acordo com a experiência.

Diferenciais:
- Liberdade: não existe horário ou local de trabalho, o que importa é fazer acontecer!

- Equipe flexível: espaço para crescimento na empresa.

- Gostamos bastante da engenharia em si e tentamos manter tudo organizado.

Requisitos obrigatórios:
- React e/ou React Native, JavaScript, HTML e CSS - você tem conhecimento e experiência o bastante nestas tecnologias para conseguir implementar um projeto do zero junto de outros desenvolvedores;

- Desejo pelo ensino e aprendizado - É necessário que você goste de aprender coisas novas para conseguir lidar com os desafios e que curta passar conhecimento para desenvolvedores menos experientes;

- Boa comunicação - Nós precisamos fazer muitas coisas e contamos com nossos companheiros para isso. Não há problema em sentir dificuldades nos projetos, mas você deve ser o tipo de pessoa que pede ajuda quando não consegue resolver um problema;

- Inglês intermediário - nossos clientes são falantes da língua inglesa e toda documentação da empresa é escrita em inglês.

Contratação:
- PJ a combinar, somos flexíveis

- Início nas próximas semanas

- Período full-time (você monta seu horário de trabalho, mas a produtividade precisa ser equivalente a dedicação full-time)

Nossa empresa:
- Interessado? Dê uma olhada em nosso site: https://codeleap.co.uk/

Como se candidatar:
-> Para se candidatar, clique no link do formulário abaixo.
https://forms.gle/zxHjd1k3cwEVBoKr7

Labels:
- Remoto

- Pleno

- PJ

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
