### ISSUE TITLE
[Porto- Portugal] Front-end Developer na MULTIVISION- Consulting 

### ISSUE THREAD

**Issue by msls19** [frontendbr/vagas#5659]
> Inicialmente remoto com realocação a curto prazo para Portugal

**A MULTIVISION:**

Somos uma equipa multidisciplinar, especializada na prestação de serviços de consultoria – Outsourcing, Time and Materials, Turnkey Projects - nas áreas de Telecomunicações e Informática. 

Procuras novas oportunidades na área de IT?🚀 Esta oportunidade é para ti 👇

**Descrição da vaga**

Projeto internacional com React.js;
Importante- Ser apaixonado, autodidata e trabalhar com pouca supervisão para uma equipe comum ou propósito da empresa;

**LOCAL**

Porto, Portugal

**REQUISITOS**

**Obrigatórios:**

-Mínimo de 3/4 anos de experiência;
- Fluência ou bom nível de conservação em inglês;
-Vanilla Javascript e estruturas e plataformas modernas como ReactJS;
- Documentos semânticos usando HTML;
- Desenvolver ótimas interfaces de usuário;
- Criar código testável e tornar o teste uma prioridade;
- Metodologias ágeis como Scrum e Kanban;

**Desejáveis:**

- Experiência com Redux, MobX e / ou outro;
- Webpack, Parcel, Rollup, Browserify, Grunt ou Gulp;
- Pré / pós-processadores CSS como PostCSS, Styled Components, LESS, SASS e / ou outros;
- Ter experiência com Automação de Teste;

**BENEFÍCIOS** 

- Seguro de saúde
- Pacote salarial completo
- Equipa multicultural; disciplinar e descontraída 
- "Lots of fun"

**CONTRATAÇÃO**

Similar a CLT

## Como se candidatar

Por favor envie um email para mariana.santos@multivision.pt com o CV em inglês anexado - enviar no assunto: Oportunidade Frontend

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
