### ISSUE TITLE
[REMOTO] Front-End Developer Pleno (Vue.js) @ Possible 

### ISSUE THREAD

**Issue by TaisaTech** [frontendbr/vagas#5660]
#### Alocação
- Remoto

#### Regime
- CLT

#### Nível

- Pleno

**Comment by andresilva-cc** [comment]
@TaisaTech Como se inscrever para esta vaga?

**Comment by TaisaTech** [comment]
> @TaisaTech Como se inscrever para esta vaga?

@andresilva-cc Por favor envie um email para taisa.oliveira@wundermanthompson.com com seu CV anexado ou LinkedIN - Enviar no assunto: Vaga do Front-End (Vue.js)
Candidatar através do link: https://jobs.quickin.io/possiblebrasil/jobs/612e3e575f30d9001af5f548

**Comment by andreblb** [comment]
Em qua., 8 de set. de 2021 09:34, Taísa Oliveira ***@***.***>
escreveu:
