### ISSUE TITLE
[REMOTO] Senior Front-End Developer na Wunderman 

### ISSUE THREAD

**Issue by TaisaTech** [frontendbr/vagas#5662]
## Nossa empresa

Somos uma consultoria digital-first com DNA de agência criativa e espírito transformador parte Wunderman Thompson Company.

## Descrição da vaga

Quem estamos buscando:

Proativo;
Adepto (a) novas tecnologias;
Habituado a trabalhar de forma colaborativa e em ambiente dinâmico;
Boa comunicação;

O que você irá fazer:

Desenvolver softwares de alta qualidade e performance utilizando práticas ágeis;
Desenvolver soluções responsivas para múltiplas plataformas;
Disponibilidade para aprender e crescer com a equipe;

## Local

Remoto

## Requisitos
Experiência trabalhando em ambientes que utilizam Git / Git Flow;
Proficiência em HTML5 / CSS3 / VanillaJS;
Experiência profissional trabalhando com plataformas CMS (AEM / Drupal);
Experiência profissional com React ou Vue;
Esteja confortável criando soluções personalizadas usando Javascript, bem como usando outros frameworks Javascript;
Inglês em nível avançado;

## Benefícios
● Benefício Flexível (Flash)

● Convênio Médico

● Auxílio línguas ou pós-graduação

● Gympass

● Licença maternidade e paternidade estendida

● Acesso aos cursos na Udemy

● Day off no dia do aniversário

## Contratação

CLT

## Como se candidatar

Por favor envie um email para taisa.oliveira@wundermanthompson.com com seu CV anexado ou LinkedIN - Enviar no assunto: Vaga de Senior Front-End Developer
Candidatar através do link: https://jobs.quickin.io/possiblebrasil/jobs/60e343ac40a9fd001291fb60

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
