### ISSUE TITLE
[REMOTO] React Developer PL/SR na Vortigo

### ISSUE THREAD

**Issue by laratodes-vortigo** [frontendbr/vagas#5663]
## Descrição da vaga!

Buscamos por **Devs Reactjs Pleno/Sênior** que tenham a mesma paixão que a gente: criar soluções incríveis que encantem as pessoas! 

## Local

Somos 100% Remoto (;

## Requisitos

Experiência em HTML5, CSS, JavaScript/TypeScript;
React.js;
APIs RESTfull;
Git;
Layouts responsivos e Mobile-Friendly;
Vivência com processo agile / scrum;
Quality assurance e code review de projetos.

## Contratação

PJ, CLT ou COOP a combinar.

## Como se candidatar

Por favor, envie um email para LARA.TODESCHINI@VORTIGO.COM.BR com seu CV anexo - enviar no assunto: Vaga Reactjs;
OU se candidatar pelo link https://vortigodigital.compleo.com.br/Visualizar/92609

## Nossa empresa

Aqui na Vortigo, nosso propósito é encantar as pessoas com experiências digitais. Começamos focados em desenvolvimento de apps em 2012 e, atualmente, implementamos a inovação digital de ponta-a-ponta.

Na Vortigo procuramos desenvolver um ambiente que seja desafiador, de alto desempenho e extrema colaboração, onde o nosso time é o ponto principal para o sucesso da empresa. Procuramos agir com responsabilidade, atitude e comprometimento, perante os nossos clientes e colegas, e esperamos o mesmo de todos que entram na empresa. Buscamos incentivar a autonomia das equipes para poderem desempenhar seus trabalhos, porém mantemos um alinhamento interno para que possamos garantir a qualidade das entregas que fazemos aos nossos clientes.

Se um ambiente assim te motiva, acesse nosso site e descubra um pouco mais sobre a Vortigo: http://vortigo.digital

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
