### ISSUE TITLE
[Remoto] Front-End React Developer na Gove

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#5664]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/dev-front-end-react-113442659?origin=github&medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Buscamos alguém que goste de trabalhar em ambiente colaborativo, tenha capacidade analítica e interesse em crescer na empresa.</p>
<h6><strong>Responsabilidade: </strong></h6>
<p>A pessoa terá como objetivo desenvolver e manter a plataforma em React consumindo uma API.</p>
<p></p>

## Gove: 
 <p>Somos uma GovTech que trabalha para transformar o jeito que gestores públicos municipais tomam suas decisões diárias e aumentar a eficiência das finanças públicas.</p>
<p>Nossa missão é permitir que gestores públicos municipais acessem num único local todos os dados necessários para suas decisões, possibilitando maior agilidade na tomada de decisão, mais eficiência da gestão pública e melhor qualidade de vida para a população.</p><a href='https://coodesh.com/empresas/gove'>Veja mais no site</a>

 ## Habilidades: 
 - React.js 
- API 
- JSON 
- HTML 5 
- CSS 3
## Local: 
 100% Remoto
## Requisitos: 
 - Ter alguma experiência (mesmo que freelancer ou de projetos de estudo) usando React 
- Espírito de equipe, gostar de trabalhar de maneira colaborativa 
- O candidato deve gostar de novos desafios e ambiente dinâmico 
- Desejável que o candidato deve esteja alinhado ao propósito da empresa de transformar o setor público 
- Conhecimento pelo menos intermediário de HTML e CSS

## Benefícios: 
 - Gympass 
- Seguro saúde 
- Seguro de vida 
- VA 500/mês 
- Trabalho Remoto 
- Horários Flexíveis
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Front-End React Developer na Gove](https://coodesh.com/vagas/dev-front-end-react-113442659?origin=github&medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
