### ISSUE TITLE
Senior React Developer | Nearshore Project | Winprovit

### ISSUE THREAD

**Issue by martabmartins** [frontendbr/vagas#5666]
Winprovit is recruiting a **Senior React Developer** (m/f) for a Nearshore Project on Telecom sector client that is being developed in our headquarters in **Lisbon or Oporto (Portugal).**

**Profile:**

- Degree in Computer Science, Engineering or similar field;
- More than 5 years of experience in similar roles;
- Experience with React;
- Experience with JavaScript, HTML and CSS;
- Experience with Angular, VueJS and Linux (Plus);
- Fluent in English (mandatory).

**We offer:**

- Remuneration according to the knowledge demonstrated;
- Participation in attractive and motivating projects;
- Career development with integration in technologically, advanced environments and dynamic teams.
- Send your CV to jobs@winprovit.pt with the reference "React4129MM"

enjoy IT with us
www.winprovit.pt

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
