### ISSUE TITLE
[Brasília] Front-end Pleno Developer na DEVEL BLOCKCHAIN

### ISSUE THREAD

**Issue by DevelBlockchain** [frontendbr/vagas#5667]
## Nossa empresa

Somos uma fabrica de software voltada para aplicações com blockchain, contratos inteligentes, inteligência artificial e sistema financeiros. Estamos fazendo um trabalho incrível de tecnologia no Brasil e no mundo.

## Descrição da vaga

Aqui na @DevelBlockchain você vai trabalhar com:
 
- Desenvolver APPs mobile utilizando React Native;
- Desenvolver Web APPs utilizando ReactJS + Bootstrap;
- Criar Landing pages;
- Realizar manutenção em aplicações existentes;
- Criar testes automatizados;

## Local

Horário flexível, 100% Remoto

## Requisitos

**Obrigatórios:**
- Experiência com HTML5;
- Experiencia com ReactJS;
- Experiencia com React Native;
- Experiencia com Java Android;
- Experiencia com Xcode/IOS;
- Experiência com Git;
- Inglês técnico - Todos os códigos são em inglês;

**Diferenciais:**
- Conhecimento sobre mercado financeiro e criptomoedas

## Benefícios

- Plano de saúde
- Vale Refeição
- Horário Flexível
- 🚀🚀🚀 Participações nos Lucros
- Ambiente de trabalho acolhedor, colaborativo, (agitado também kkkk)
- Ótima oportunidade para crescer profissionalmente e ganhar novas skills

## Contratação

CLT

## Como se candidatar

Por favor envie um email para vagas@develblockchain.com com seu CV anexado - enviar no assunto: **Front-end Developer**

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: vagas@develblockchain.com

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
