### ISSUE TITLE
[São Paulo] Front-End Developer na CBYK Consultoria

### ISSUE THREAD

**Issue by roliveira-com** [frontendbr/vagas#567]
## Descrição da vaga

Por aqui, você vai trabalhar com diversos projetos, atuando desde a concepção de interfaces até a implementação e integração com APIs. 

## Local

Alocado em Escritório, São Paulo - Vila Olímpia

## Requisitos

**Obrigatórios:**
- Web responsiva
- HTML5 / CSS3 / Bootstrap
- Javascript e Jquery
- AngularJS

**Desejáveis:**
- Conhecimentos em Angular 2 / Angular 4

## Contratação

PJ a combinar

## Nossa empresa

A [CBYK ](http://www.cbyk.net)é uma consultoria em TI  criada por um grupo de especialistas que reúnem uma vasta experiência nos segmentos financeiro, telecomunicações, seguros, linhas aéreas, farmacêutica e varejo, compartilhando conhecimento e promovendo mudanças com foco em resultados relevantes em nossos clientes.

## Como se candidatar

Por favor envie um email para vagas@cbyk.com.br com seu CV anexado.

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by roliveira-com** [comment]
Pode deixar fechado man! Valeu!
