### ISSUE TITLE
[PORTO, PORTUGAL] Front-end Developer at @PTCGroup

### ISSUE THREAD

**Issue by marcelamn-PTCGroup** [frontendbr/vagas#5670]
## Nossa empresa

Desenhamos soluções para atender às necessidades de nossos clientes. Atuamos em Engenharia, Consultoria, Tecnologia da Informação e Formação.

## Descrição da vaga

Projeto de grande e-commerce para Front-end Developers com no mínimo 02 anos de experiência.

## Local

[PORTO] [PORTUGAL] [PRESENCIAL] - Vaga para mudança.

## Requisitos

- 02 anos de experiência com ReactJS, VueJS ou Angular;
- Inglês avançado.

## Benefícios

Custeio da expatriação, Auxílio de Custo.

## Como se candidatar

Por favor envie currículo ou mensagem no LinkedIN.

E-mail: marcela.nogueira@ptcgroup.com.br 
LinkedIN: https://www.linkedin.com/in/marcelamnogueira/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
