### ISSUE TITLE
[Curitiba-Remoto] Frontend SR React Developer na Wiser Educação ( Holding do Flávio Augusto)

### ISSUE THREAD

**Issue by Marcialove** [frontendbr/vagas#5671]
Já pensou em contribuir com uma das maiores EdTechs do país e fazer a diferença na educação de milhares de pessoas? 
Somos a Wiser Educação, uma holding que está há mais de 26 anos gerando valor por meio da educação, na vida de nossos alunos e colaboradores. Você já deve conhecer nossas marcas: Wise Up, Wise Up Online, Wiser Sales Platform, Number One, meuSucesso.com, Power House, Buzz Editora e Conquer. 
 
 **Descrição da vaga - 100% HOME OFFICE**

**Responsabilidades** 

Desenvolver aplicações em Javascript e React;
Construir módulos, libs, componentes e projetos; 
Analisar e propor soluções de software; 
Auxiliar na estimativa de prazos; 
Realizar report de status; 
Atuar com time multidisciplinar; 
Atuar em entregas sempre fazendo uso de boas práticas;

**Requisitos **
Sólidos conhecimentos em HTML5 e pré processadores CSS; 
JavaScript moderno (ES6+); 
React; 
Hooks; 
Context API; 
Git; 
Experiência em desenvolvimento de aplicações web e habilidades associadas (REST, HTTP, web services); 
Conhecimento em Git Flow; 
Redux & Redux Saga; 
Styled Components e React Router. 

**É um diferencial se você tiver** 
Conhecimento em SSR e NextJS; 
Automatização de testes; 
TDD; 
Padrões de projeto e arquitetura (Design Patterns) Clean Architecture, SOLID; 
Google AMP (AMP Project);
Progressive Web App (PWA); 
Experiência em desenvolvimento de sistemas de alta disponibilidade; 
Webpack/Gulp; 
Ter construído / trabalhado com Design System.

**Benefícios**
Contratação CLT
Auxílio Home Office; 
Auxílio de equipamento de trabalho;
Plano de saúde e odontológico Amil, sem coparticipação;
½ dia de folga no aniversário;
Vale refeição ou alimentação;
Seguro de vida;
Acesso ao Gympass.

Como se **candidatar**
Por favor se inscreva em nossa página de carreiras: https://jobs.kenoby.com/wiser                                                                  
Podemos falar pelo Watts  (14) 98803-1462 ou envie um e-mail para: recrutec@wisereducacao.com 

#### Alocação
- Remoto

#### Regime
- CLT
 
#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
