### ISSUE TITLE
[Curitiba-Remoto] Backend Node Developer na Wiser Educação ( Holding do Flávio Augusto)

### ISSUE THREAD

**Issue by Marcialove** [frontendbr/vagas#5672]
**Nossa Empresa**
Já pensou em contribuir com uma das maiores EdTechs do país e fazer a diferença na educação de milhares de pessoas?
Somos a Wiser Educação, uma holding que está há mais de 26 anos gerando valor por meio da educação, na vida de nossos alunos e colaboradores. Você já deve conhecer nossas marcas: Wise Up, Wise Up Online, Wiser Sales Platform, Number One, meuSucesso.com, Power House, Buzz Editora e Conquer.
 

## Descrição da vaga
Desenvolver aplicações, módulos, libs, serviços e micro serviços em NodeJS;
Analisar e propor soluções de software entregando valor aos nossos clientes;
Auxiliar na estimativa de prazos e ser responsáveis por eles junto com seu time;
Atuar com time multidisciplinar;
Atuar com boas práticas e práticas de arquitetura de Backend;
Realizar entregas de valor junto com seu time;
Ajudar na formação de desenvolvedores Juniors;

## Requisitos
Experiência com Javascript;
Experiência com NodeJS;
Experiência com Typescript;
Experiência com Express;
Experiência com Bancos de Dados SQL, principalmente PostgreSQL;
Conhecimento com Frameworks como NestJS ou Adonis;
Conhecimento em Docker;
Conhecimento em alguma cloud (AWS, GCP, Azure)
Conhecimento em Metodologias Ágeis como Scrum, Kamban

**Diferenciais:**
Conhecimento em NoSQL;
Experiência com TDD;
Experiência com Clean Architecture, SOLID e Arquitetura de Microserviços;

## Local
100% Remoto  

## Benefícios
Contratação CLT; 
Auxílio Home Office; 
Auxílio de equipamento de trabalho;
Plano de saúde e odontológico hAmil, sem coparticipação;
½ dia de folga no aniversário;
Vale refeição ou alimentação;
Seguro de vida;
Acesso ao Gympass.

Após 3 meses de experiência, você terá acesso a: 
Acesso gratuito à plataforma Wise Up Online 
Descontos na BuzzEditora e meuSucesso.com 
 

## Como se candidatar

Por favor se inscreva em nossa página de carreiras: https://jobs.kenoby.com/wiser
Podemos falar pelo Watts (14) 98803-1462 ou envie um e-mail para: recrutec@wisereducacao.com
Linkedin: linkedin.com/in/marciarh-segura

#### Alocação
- Remoto

#### Regime
- CLT
 
#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
