### ISSUE TITLE
[Brasília/Remoto] Front-end Developer na Novatics Tecnologia

### ISSUE THREAD

**Issue by MaEduardaL** [frontendbr/vagas#5673]
[Brasília] Front-end Developer na Novatics Tecnologia

> Vaga 100% Remota 

## Nossa empresa

Somos um estúdio de software que ajuda empresas de todo o mundo a criar produtos digitais personalizados para a Web e dispositivos móveis.

## Descrição da vaga

Estamos procurando um Front End Engineer para nos ajudar no desenvolvimento de nossos projetos. Esperamos encontrar em você boa comunicação, para trabalhar com equipes multidisciplinares. Organização para gerir suas tarefas do dia a dia e empenho para buscar evoluir sempre entregando sempre o melhor possível.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 3 anos ou + de experiência com ReactJS
- 3 anos ou + de experiência em conceitos e camadas do front
- Experiência com testes automáticos
- Inglês para conversação: Intermediário, Avançado ou Fluente

## Benefícios

-Salário compatível com o mercado;
-Horário flexível e home office;
-Benefício flexível para saúde, educação, alimentação, transporte e cultura;
-Participação nos lucros e correção anual da remuneração;
-Cobertura de atestados e licença para emergências;
-Days off remunerados;
-Licença paternidade, maternidade e casamento;
-Cultura de trabalho que prioriza: transparência, autonomia e colaboração;
-Oferecemos os recursos para desenvolver a sua carreira de forma global. 10% do tempo conosco é dedicado ao seu desenvolvimento. Também te acompanhamos nesse processo oferecendo mentoria individualizada.

**Diferenciais:**
-Tempo para estudo e desenvolvimento da carreira (PDI e Plano de Carreira);
-Oportunidades 100% remoto.

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para maria.eduarda@novatics.cm.br com seu CV anexado - enviar no assunto: Vaga Front-End

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
