### ISSUE TITLE
[São Paulo / 2x na semana no escritório] Dev Angular (Nível Pleno) no Banco ABC

### ISSUE THREAD

**Issue by danielasantosrh** [frontendbr/vagas#5676]
## Sobre o Banco ABC

Com mais de 30 anos de mercado e listado na Bolsa, o Banco ABC Brasil é reconhecido por essas três características: consistência, segurança e eficiência. Acreditamos que o sucesso é fruto de uma cultura que promove relações colaborativas, visa o resultado e abre espaço para o diálogo. Nesse sentido, atuamos visando sempre a competência em tudo o que nos propomos a fazer, o profundo conhecimento do nosso mercado, a credibilidade dos nossos clientes, a agilidade na busca por soluções adequadas e inovadoras, o compromisso com bons resultados e o investimento contínuo em tecnologia, processos e pessoas.

## Descrição da vaga

Requisitos:
• Angular 7/8
• Git,
• HTML5
• CSS3
• JSON
• REST
• Javascript e TypeScript

## Local

Faria Lima - SP

## Benefícios

• PLR (2.2 salários + 5k de abono)
• Bônus: até 1,7 salários (desempenho)
• VR+ VA (1.480,00)
• Assistência médica: Bradesco (apenas para se usar (coparticipação) / sem desconto mensal)
• Odonto: Omint (desconto a partir de 35 reais de acordo com seu plano escolhido)
• Auxílio creche (R$ 500,00 até 5 anos)
• Seguro de vida
• Gympass

## Contratação

CLT a combinar

## Como se candidatar

Por favor responder ao chatbot no link abaixo (você vai levar menos que 5 minutos)
https://yuri.jornadayu.com/j/desenvolvedores-abc/src/gh

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
