### ISSUE TITLE
[Curitiba - PR] Desenvolvedor Full Stack Senior na Matrixcargo

### ISSUE THREAD

**Issue by Anapiccoli** [frontendbr/vagas#5679]
==================================================
-->
> Vaga presencial e/ou híbrida
Vaga PJ ou CLT para Desenvolvedor Full  Stack Sênior - para Curitiba - PR
Sua missão será fornecer uma PLATAFORMA DIGITAL de alta tecnologia para soluções logísticas colaborativas com evolução constante, proporcionando sinergias operacionais por otimização de recursos e lucro para todos agentes envolvidos no processo logístico.

Confira as facilidades que só a Matrixcargo te oferece:

﻿Café refrigerantes e energéticos liberados á vontade para você recarregar suas energias;
Área de descompressão;
Ótima localização com várias opções de restaurantes e outros comércios com desconto;
Programa Amigos Chevrolet que vai te dar um forcinha na compra do seu carro novo;
Programa Liberty Seguros que te ajuda a deixar o seu carro ou residência seguros;
Convênio com Universidades e parcerias para cursos diversos;
Facilidade para o empréstimo consignado;
Programa Felizes para Sempre;
Licença remunerada à maternidade no último mês de gestação;
Descontos em farmácias e drogarias;

Demais benefícios:

Vale Refeição ou vale Alimentação
Plano de Saúde
Plano Odontológico
Seguro de Vida
PLR

Se inscreva através do link: 

https://matrixcargo.gupy.io/job/eyJqb2JJZCI6MTE3NTA1Nywic291cmNlIjoiZ3VweV9wdWJsaWNfcGFnZSJ9?jobBoardSource=gupy_public_page

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
