### ISSUE TITLE
[REMOTO] Dev Front-end Drupal Pleno na JUST Digital

### ISSUE THREAD

**Issue by DeboraSquadra** [frontendbr/vagas#5682]
> Vaga Remota durante a pandemia

## Nossa empresa

Acreditamos no Design para criar experiências memoráveis em tudo o que fazemos e na engenharia de software para tornar isso possível. Queremos mostrar ao mundo que entregar resultado para hoje e amanhã pode ser mais simples do que se imagina, mais divertido do que se espera, e inesquecível para gerar laços e conexões duradouras entre pessoas.
Gostamos de pessoas proativas que somem ao time de desenvolvimento auxiliando na arquitetura da solução e preze pela qualidade do software como um todo.

Todas as vagas da JUST são trabalhadas com o propósito de promover a diversidade e inclusão, seja ela de gênero, idade, pessoas com necessidades especiais, religião e LGBTQ +.

## Descrição da vaga

Apoio à equipe interna do cliente em questão na manutenção e evolução do portal em Drupal da companhia. Desenvolvimento de módulos, temas e integrações com outros sistemas utilizando site studio!

## Local
Remoto 

## Requisitos

**Obrigatórios:**
HTML
CSS
JavaScript
Drupal (Site Building)
Git

**Desejáveis:**
PHP
Docker

## Benefícios

Vale Refeição ou Alimentação com cartão CAJU
Assistência Médica e Odontológica
Horário Flexível
Desconto em todas as modalidades FIAP
Credencial Plena do SESC
Parceria com o English Live
Terapia e grupos de conversa/apoio
Auxilio Creche, para crianças até 5 anos

**Após a pandemia, caso você esteja em São Paulo - SP:**

Vale Transporte ou Vale Combustível
Política de revezamento
Frutas no escritório e café da manhã toda sexta feira

## Contratação

CLT

## Como se candidatar

Por favor cadastre-se no link > https://justdigitalbr.recruitee.com/o/dev-front-end-drupal-pleno-chacara-santo-antonio-sp

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
