### ISSUE TITLE
[São Paulo - Híbrido] Front-end Developer na @Suzano

### ISSUE THREAD

**Issue by katrine-souza** [frontendbr/vagas#5683]
> 

## Nossa empresa

Prazer, somos a Suzano!

Aqui a gente acredita que inovação e sustentabilidade caminham juntas. Dessa união, nasce uma atitude plena de significado: a inovabilidade. Pautados por ela, pensamos fora da caixa e enxergamos longe para lidar com os desafios do século 21. Nós plantamos e cultivamos árvores para transformar essa matéria-prima renovável em Bioprodutos para o dia a dia de mais de 2 bilhões de pessoas. Cultivamos a vida na folha do caderno que alfabetiza as crianças, na fralda que protege os bebês, no copo de café que não prejudica o meio ambiente, em papéis absorventes e na comodidade do uso de uma embalagem sustentável.

 VÍDEO Suzano em 2 Minutos : https://youtu.be/pQemxK-lBTM

##PLURAL

Iguais e diferentes. Singulares e plurais. Acreditamos que a diversidade nos fortalece, por isso, não fazemos distinção para candidatos com deficiência, gênero, orientação sexual, raça/etnia, idade, origem, constituição familiar e estética. Aqui você pode descobrir novos desafios, novos horizontes, novos objetivos e até mais sobre você mesmo.

##O QUE VOCÊ ENCONTRARÁ NESSA NOVA JORNADA?

Somos a Suzano DigitalTech, renovar e transformar as pessoas e os negócios através da tecnologia e inovação, é o nosso propósito. Fazemos isso através de um time feliz, colaborativo e em constante aprendizagem. Que busca por excelência no presente e tem olhos para o futuro. Que desafia o status quo e provoca a pensar diferente e que junto constrói um ambiente seguro que encoraja novas ideias e a experimentação.

## Descrição da vaga

- Construção de interface amigável e fiel ao time de design, construção de menus e componentes responsivos
(adaptáveis a todo tipo de tela), seções de texto e imagens, fontes, cores.
- Desenvolver e realizar manutenções em aplicações web responsivas e performáticas.
- Implementar protótipos recebidos do time de UX/UI
- Trabalhar com versionamento de código (git).

## Local

Exemplo: Remoto ou Escritório, [ESTADO], [CIDADE], [BAIRRO]

## Requisitos

**Obrigatórios:**
- 3 anos de experiência 
- Javascript ,HTML5, CSS,
- ReactJS, NextJS, VueJS ou NuxtJS.
- Gerenciadores de pacotes, como: NPM e Yarn.
- “minificação” e compilação, como: Webpack, babel, grunt, gulp.
- Biblioteca de terceiros

**Desejáveis:**
- Conhecimento em designer
- Contêineres (Docker)

## Benefícios

- Plano de saúde
- Seguro de vida
- VR
- VA
- Kit material escolar
- PPR
- Bônus anual
- Gympass

## Contratação
CLT

#### Nível
- Sênior

## Como se candidatar

Por favor candidate-se por meio do link:
https://ShareRH.compleo.com.br/Visualizar/94713

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
