### ISSUE TITLE
[Remote] Fullstack Developer (foco em Front-end) na GeekHunter 

### ISSUE THREAD

**Issue by LeticiaCQ** [frontendbr/vagas#5684]
## DESCRIÇÃO DA [VAGA](https://geekhunter.gupy.io/jobs/1101855) ##

Estamos crescendo de forma acelerada em busca de um time incrível para participar da melhoria e construção do maior Marketplace de pessoas desenvolvedoras da América Latina!

Nessa posição sua missão principal será realizar melhorias e implementar novas funcionalidades na plataforma da GeekHunter, numa abordagem full-stack com ênfase em Frontend.

Hoje nossa plataforma usa especialmente Ruby on Rails e Angular, além de alguns módulos utilizando outras tecnologias, como: Python e React. Nossa infra-estrutura fica na AWS e utilizamos tecnologias como PostgreSQL, MongoDB, entre outras.

## [MOTIVOS PARA TRABALHAR NA GEEKHUNTER](https://bit.ly/2X7M0eR) ##

**_Alguns mandamento do nosso time de Produto:_**

- Sabe aquele time cooperativo e alto astral, você vai encontrar conosco!
- Usamos a metodologia de Pair Programming no nosso dia-a-dia, pois acreditamos que na troca é que mais se aprende!
- Usamos metodologias ágeis.
- Para nós, uma boa entrega é aquela que resolve o problema do cliente.
- Tudo que programamos é orientado a testes, TUDO mesmo!
- Somos um time que acredita que a tecnologia é o meio que utilizamos para conquistar nossos objetivos.

## RESPONSABILIDADES E ATRIBUIÇÕES ##

**_Você atuará em projetos ligados a:_**

- Implementação de novas funcionalidades da plataforma;
- Identificação e correção de erros em funcionalidades já existentes;
- Suporte a experimentos;
- Entender muito bem os requisitos e escrever código claro, simples e orientado a testes;
- Trabalhar para melhorar as soluções existentes da GeekHunter;
- Aprender e aplicar novas tecnologias para otimizar nossos processos e produtos.

## REQUISITOS E QUALIFICAÇÕES ##

**_Esperamos tecnicamente de você:_**

- Experiência em desenvolvimento web full-stack;
- Conhecimentos em AngularJS, React ou equivalente;
- Ser capaz de transformar artefatos de Design em Front-End;
- Saber sobre consumo de APIs REST ou GraphQL;
- Conhecer framework de testes;
- Saber "se virar" no Back-End.

**_Quais características serão esperadas de você:_**

- Pragmatismo no dia-a-dia;
- Focar na raiz dos problemas;
- Gostar de verdade de desafios;
- Se identificar com o valor: cliente sempre em primeiro lugar!
- Gostar de trabalhar em equipe e com bastante autonomia.

## Faixa Salarial

- Nossa faixa para vaga Sr começa em **R$8.100!**

## 😋 ALÉM DISSO, AINDA OFERECEMOS: ##

- Vale-refeição/alimentação de R$ 600,00;
- Plano de saúde (Bradesco Saúde Nacional);
- Benefício de Inglês - Slang
- Assistência odontológica;
- Gympass;
- Vale Padawan de R$130,00 mensais (benefício precioso para você utilizar no seu desenvolvimento educacional ou cultural);
- Home Office Setup no valor de R$ 600,00, em uma parcela única após seu período de experiência!
- Auxílio Internet no valor de R$ 125,00 mensal;
- Parcerias e convênios: Conquer, SkillHub, SESC-SC, Convênio Jurídico ;
﻿- Atividades de Bem-estar: Yoga e Meditação ;
- Um ambiente flexível e descontraído. Queremos que você se sinta motivado(a) para vir trabalhar até mesmo nas segundas de manhã :)

### Labels

Sênior

Remoto

CLT

TDD

## OLÁ, EU SOU A [GEEKHUNTER!](https://www.geekhunter.com.br/sobre) 👋 ##
Eu nasci com com o propósito de **transformar o dia a dia de empresas e a vida das pessoas desenvolvedoras**!

A minha plataforma já conta com milhares de candidatos e empresas, que se beneficiam do sistema que mais cresce no Brasil na área de RH tech.

O que me move é poder proporcionar uma ferramenta revolucionária para a contratação de profissionais de tecnologia conectando as melhores mentes desenvolvedoras às melhores empresas.

Eu sou cult, sou nerd, sou gamer, sou transformadora e conectada em um ambiente descontraído permitindo que tenhamos muitos insights e possamos resolver as coisas com criatividade e muito embasamento em dados. Enfim, sou Geek!

Até o final do ano de 2021, meu time crescerá de forma nunca vista! 
 
Além disso, eu cuido bastante desse time! Incluí diversos benefícios para desenvolvimento e bem-estar dos geeks. Acompanho nosso clima semanalmente pela Pulses e também pela pesquisa do GPTW (Great Place to Work), onde certifiquei em Junho/2021. Sei que estou no caminho certo, aliando o rápido crescimento do negócio ao cuidado que tenho com o bem estar e carreiras do meu time! 
 
Aliás, foi pensando nisso que me tornei Remote First! Assim, cada ser humano maravilhoso do meu time tem a liberdade de decidir onde deseja estar! 
 
👉 Para se tornar um Geek, aspectos como: trabalho em time, apreço por mudanças, desenvolvimento constante, melhorias contínuas, visão data-driven e foco no resultado, são características que não podem faltar! 
 
Tenho um grande apreço pela diversidade das pessoas, então todas as pessoas são mais que bem-vindas em nossas oportunidades, independentemente de seu credo, classe social, cor, sexualidade e etnia! Por aqui tenho trabalhado para desenvolver uma empresa cada vez mais diversa em todas as minhas ações e em conjunto com o meu time de Diversidade.
 
Aqui você pode esperar por muitos desafios e problemas a serem solucionados, com o suporte de um time acolhedor e que adora construir em conjunto! Sou adepta ao costume de comemorar e vibrar a cada pequena conquista e, quando as coisas não saem como eu gostaria, aprendo ainda mais para evoluir no meu dia a dia! E claro, também vibro e muito nas grandes conquistas, já até pulamos de paraquedas para comemorar um marco histórico, acredita?!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
