### ISSUE TITLE
[Remoto] Front-end Developer na Solfácil

### ISSUE THREAD

**Issue by Mariadafne** [frontendbr/vagas#5687]
## Nossa empresa 💛

A Solfácil é a **primeira Fintech de energia solar do Brasil**, criada para democratizar o acesso à geração de energia fotovoltaica e destravar este mercado em todo o Brasil.

Estamos revolucionando a forma como a energia solar é operacionalizada e nos posicionando como a principal solução de um setor que tem e continuará tendo um crescimento exponencial no país.

## Descrição da vaga

**ATIVIDADES PRINCIPAIS**

- Participar da priorização dos produtos, pensando em agregar valor para os negócios se baseando em dados
- Produzir código limpo de de fácil manutenção
- Definir junto ao time qual será a melhor abordagem para a execução e evolução dos projetos e processos
- Realizar Code Review de outros desenvolvedores
- Realizar Deploys nos ambientes de Homologação, Stage ou Produção
- Integrar com serviços terceiros
- Analisar e corrigir bugs

## Local

Remoto 

## Requisitos

**Obrigatórios:**

- HTML5 / CSS3 (SASS e Flexbox)
- Javascript (ES6+)
- Vue.js / Vuex
- Consumo de API's RESTful (Fetch, Axios)
- Práticas de Clean Code e Design Patterns
- Git / Gitflow
- Code review
- Pixel Perfect

**Desejáveis:**

- Motivado por aprendizado e desenvolvimento contínuo
- Facilidade de trabalhar em grupos
- Capaz de se comunicar de forma clara (online e offline)

## Benefícios

**🥗Vale-refeição
🚈Vale-transporte
🏃‍♂️ Gympass
⏰Horário flexível
🤩Plano de saúde
😁Plano odontológico
🤑Bônus Anual - até 2 salários**

## Contratação

CLT

## Como se candidatar

Para se candidatar e/ou saber mais sobre a vaga, acesse: **https://bit.ly/3nivVxW**

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Venha fazer parte dessa revolução com a Solfácil!**

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
