### ISSUE TITLE
[Híbrido/SP] Angular Developer na Orbital

### ISSUE THREAD

**Issue by wallaceerick** [frontendbr/vagas#5688]
## Empresa
Somos a [Orbital](https://orbital.company), empresa de tech & inovation que atua diretamente na concepção e construção de produtos inovadores para startups e multinacionais.

## Vaga
Estamos recrutando ninjas com bastante experiência em Angular para atuar alocado em empresa de comércio exterior que possui foco na criação de produtos e serviços inovadores para potencializar negócios internacionais entre associados.

## Local
Híbrido - Escritório (Av. Paulista) e Home Office.

## Requisitos

**Obrigatórios:**
- Mínimo de **6 anos** de experiência com HTML, CSS e JS;
- Experiência de pelo menos **3 anos** com Angular, hoje usamos o 10;
- Angular Material, Flex Layout, Typescript, Flux (NgRX)
- Consumo de APIs Restfull;
- Arquitetura, Padrão de Projeto e código limpo;
- DNA Inovador;
- Scrum e Metodologias Ágeis;
- Git Workflow.

**Diferenciais:**
- Noções de Cloud AWS

## Contratação
- PJ

## Candidatos
Por favor, preencha o formulário para [Pleno ](https://recrutamento.orbital.company/index.php?page=view_vacancy&id=15) ou [Sênior ](https://recrutamento.orbital.company/index.php?page=view_vacancy&id=16) com suas informações pessoais e entraremos em contato com os candidatos selecionados.

## Feedbacks
-  3 ou 7 dias

## Nível
- Pleno
- Sênior

## Labels
Sênior, Pleno, Angular, Orbital, Híbrido, PJ

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
