### ISSUE TITLE
[REMOTO] Full-Stack Developer (Junior) @Orx - Startup

### ISSUE THREAD

**Issue by bkip1** [frontendbr/vagas#5689]
## Nossa empresa

Startup com MVP rodando e participando de aceleradora no exterior

## Descrição da vaga

Atualmente trabalhamos com PHP/Laravel e Go

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência em alguma linguagem de programação

**Desejáveis:**
- PHP
- GO

**Diferenciais:**
- Flutter

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para orxyip@outlook.com

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
