### ISSUE TITLE
[Rio de Janeiro] Front-End Developer na Brave Investments

### ISSUE THREAD

**Issue by ricardokdz** [frontendbr/vagas#569]
### Sobre a Empresa

Atuamos na construção de novos negócios digitais, tirando projetos do papel até o MVP com recursos próprios.

Após o modelo estar provado, estruturamos a equipe operacional dedicada e captamos investimentos para o novo negócio avançar.

### Descrição da vaga

Estamos em busca de um(a) profissional capaz de trabalhar tanto em grupo desenvolvendo partes de uma aplicação, quanto sozinho desenvolvendo uma aplicação por completo. Inicialmente atuará no desenvolvimento de interfaces e consumos de API's.

### Requisitos

  * React
  * Node
  * Javascript / ES 6
  * HTML e CSS
  * MySQL (ou equivalente)
  * Git e Gitflow
  * Experiência com API's

### Diferenciais

  * React Native
  * Frameworks PHP
  * Ruby
  * Workflow das lojas de aplicativos (Google Play e iTunes)

Tipo de contratação: Prestação de serviços

Salário: Baseado na experiência

Local: https://goo.gl/maps/5jEgqkuEDAk

Aplicação: Enviar curriculo com pretensão salarial para ricardo@braveinvest.com.br

**Comment by LFeh** [comment]
Aberto ainda?
