### ISSUE TITLE
[REMOTO] Front-end Developer NutriDiet

### ISSUE THREAD

**Issue by thiagoferreira123** [frontendbr/vagas#5694]
## Nossa empresa

Uma plataforma web para uso pessoal, que coleta, armazena e trata dados de pacientes.

## Descrição da vaga

Correção de bugs/refatoração/criação de novos layouts.

## Local

Exemplo: Remoto

## Requisitos

**Obrigatórios:**
- Experiência em PHP/JS/jQuery/MysQL

**Desejáveis:**
- Comprometimento

**Diferenciais:**
- ter portfolio, ser acessível 

## Contratação

Freelancer.

## Como se candidatar

Por favor envie um email para nutricionistathiagoferreira@gmail.com

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dia.

#### Alocação
- Remoto

#### Regime
- Freela

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
