### ISSUE TITLE
[REMOTO] Front-end Developer na JetBov

### ISSUE THREAD

**Issue by CassioRecruiter** [frontendbr/vagas#5696]
![Precisamos de você](https://user-images.githubusercontent.com/74560568/133304767-b1baa5a4-3c31-4a9e-925e-c17925258980.jpeg)
## JetBov

A JetBov é uma Startup que está transformando a pecuária de corte no mundo. Usamos a tecnologia de inteligência artificial e armazenamento de dados com o objetivo de digitalizar a cadeia produtiva da bovinocultura de corte. Nosso propósito é empoderar o(a) pecuarista, através de informação e oportunidades, agregando maior valor a cadeia de forma sustentável.

Quer saber como é ser um JetBover? Acesse o link:

https://jobs.quickin.io/jetbov

## Descrição da vaga

Você fará parte de um time experiente e inovador em uma empresa em constante crescimento! Praticamos uma cultura de autonomia, responsabilidade, velocidade, qualidade de entrega e meritocracia.

Responsabilidades:

- Desenvolver código FrontEnd;
- Desenvolver código Mobile;
- Participar ativamente de uma equipe usando processo de desenvolvimento Ágil;
- Realizar atividades de garantia de qualidade (ex.: TDD).

## Local

Remoto.

## Requisitos

**Obrigatórios:**
- Experiência em desenvolvimento e serviços Cloud / SaaS;
- Proficiência em linguagens (HTML, CSS, JS) e framework de FrontEnd (Angular, React, e preferencialmente com Vue.JS);
- Habilidade com testes automatizados e modelo TDD;
- Habilidade com ferramenta e modelo GIT para versionamento de código;
- Habilidade de trabalhar em equipe com autonomia e responsabilidade.

**Desejáveis:**
- Graduação em Ciência da Computação, Sistemas Aplicativos ou experiência equivalente;
- Experiência com metodologia ágil (Scrum / Kanban);
- Habilidade com práticas ágeis de programação (ex.: Pair programming, testes unitários, code review);
- Inglês intermediário.

## Benefícios

- Atuar com as mais modernas tecnologias incluindo IA, ML e IoT;
- Ambiente casual que estimula e valoriza atitudes inovadoras;
- Poder participar da transformação da vida de pessoas que trabalham e vivem da Pecuária de Corte no Brasil e no Mundo;
- Plano de saúde com cobertura nacional, sem desconto em folha para titular (*);
- Vale refeição ou alimentação (*);
- Vale transporte (*);
- Horário flexível.
(*) Para contratações no modelo CLT.

## Contratação

CLT, PJ ou Cooperativa

## Como se candidatar

Interessados podem se cadastrar no site: https://jobs.quickin.io/jetbov/jobs/60c36ba0b832bc001a0ea5db
Ou enviar um e-mail para talentos@jetbov.com

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT
- PJ
- Cooperativa

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
