### ISSUE TITLE
[Remoto] Front-end Developer Pleno na DIWE

### ISSUE THREAD

**Issue by glauberbrack** [frontendbr/vagas#5699]
## Nossa empresa

Venha ser um Diwer e participar de uma empresa em constante crescimento, com certificado GPTW 2021 e foco no desenvolvimento das pessoas.

O desenvolvedor(a) front-end é quem entende e executa toda a estrutura de desenvolvimento. Esse (a) profissional plana sobre múltiplos projetos, apoiando pontualmente cada um deles, sugerindo soluções, protegendo o produto e processos, e dedicando o tempo a resolver demandas do dia-a-dia.

Deve estar atento a novas tecnologias e produtos. Deve participar ativamente do dia a dia da operação e se relacionar com as frentes de Planejamento, Negócios e Desenvolvedores. Só dessa forma poderá ser um ponto focal e referência para as ações de Engenharia.

Uma das atribuições mais importantes e esperadas do desenvolvedor júnior é sua evolução, tanto técnica quanto em relação a soft skills. O ambiente de trabalho da DIWE irá prover espaço e desafios para esse desenvolvimento.

## Descrição da vaga

E o que é Parceiro da Construção?

O Pdc é uma oportunidade excelente para participar de um projeto inovador em um mercado que começou a mergulhar em tecnologia a pouco tempo, o mercado da Construção Civil. O Parceiro da Construção é uma startup incubada na Saint-Gobain, player global deste ramo que vem através desta e de outras iniciativas promovendo uma transformação digital disruptiva. Você será um dev (e consultor) com voz no projeto, ajudando a definir as tecnologias, regras e acima de tudo, o rumo e o futuro deste projeto.

Você pode conhecer (e se cadastrar) na plataforma em www.parceirodaconstrucao.com.br.

Neste vídeo (https://www.loom.com/share/64c0ee5f2a84424a9b2b37ef8f3b1bec?t=300) apresentamos alguns detalhes sobre o projeto, e também conhecerá uma das pessoas que lidera as iniciativas de tecnologia neste projeto

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Sólidos conhecimentos em HTML5 e CSS3;
- Conhecimento front-end JavaScript (ES6/7/8);
- Conhecimentos em desenvolvimento front-end utilizando os frameworks: VueJS, Nuxt e/ou React, Next;
- Conhecimento em GIT e suas boas práticas;
- Conhecimentos em consumo de APIs REST;
- Ter experiência em criação de componentes isolados em frameworks React, Angular ou Vue.Js;
- Experiência em medir e otimizar o desempenho do front-end;
- Forte experiência com mobile-first e responsive design;
- Organização;
- Pontualidade;
- Inteligência Emocional;
- Comunicação;
- Raciocínio lógico.

**Desejáveis:**
- Experiência com pré-processadores CSS (LESS, SASS);
- Experiência com os ritos e de Agile/Scrum;
- Conhecimentos em VueX ou Redux;
- Forte experiência em desenvolvimento de layouts e componentes pixel-perfect;
- Conhecimento nas ferramentas Grunt ou Gulp;
- Conhecimento em React Native ou Quasar para desenvolvimento de aplicativos;
- Conhecimento na metodologia Atomic design;
- Typescript;
- Conhecimento em testes unitários;
- Conhecimentos de Cloud Computing (AWS, Google Cloud, etc).

## Benefícios

 Seguro de vida;
 Ajuda de custo Home-office;
 Certificações e cursos para desenvolvimento constante;
 Academia de treinamento DIWE.

## Contratação

PJ (R$ 4.500 a R$ 5.000)

## Como se candidatar

Por favor envie um email para edgar.fonseca@diwe.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Developer Pleno na DIWE

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: edgar.fonseca@diwe.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
