### ISSUE TITLE
[Campinas] Desenvolvedor Front-End e Wordpress

### ISSUE THREAD

**Issue by gabriel-ribeiro-ir** [frontendbr/vagas#57]
## Descrição da vaga

Estamos em busca de um novo desenvolvedor front-end para atuar no desenvolvimento de novos projetos e na manutenção de projetos já existentes, principalmente de sites. É muito importante que você manje de sites responsivos e também de Wordpress. Para maiores informações sobre nós, acesse o nosso [site](http://www.princiweb.com.br/) ;-)

## Local

Campinas

## Benefícios

- Ida a eventos da área de front-end;
- Material (livros e cursos) para estudo;
- Tempo livre para projetos experimentais.

## Requisitos

**Obrigatórios:**
- Boa experiência em HTML5 e CSS3;
- Wordpress;
- jQuery;
- Já ter tido contato com Git;
- Task Runners (Preferencialmente Gulp);
- Photoshop Básico;
- Encarar bem serviços de manutenção (tem bastante);
- Pique para aprender novas tecnologias de desenvolvimento web;
- Hábito de leitura e escrita (você irá escrever em nosso Blog);
- Desenvoltura para trabalho em equipe;
- Ser bastante organizado e responsável.

**Diferenciais:**
- Saber o básico de JavaScript puro;
- Já ter ouvido falar sobre novos frameworks JS;
- Já ter ouvido falar sobre metodologias ágeis;
- Já ter ouvido falar sobre Integração contínua.

## Contratação

CLT com salário a combinar, de acordo com a experiência e nível de conhecimento do candidato.

## Nossa empresa

Somos movidos por projetos web e acreditamos que o seu desenvolvimento, de forma ágil e comprometida, pode trazer excelentes resultados às pessoas (e também muitas horas de diversão para nós).

## Como se candidatar

Envie um e-mail para [trabalhe@princiweb.com.br](mailto:trabalhe@princiweb.com.br) com título/assunto Vaga – Front-End. Ah, de preferência, envie junto os seus últimos trabalhos ou o perfil do GitHub para avaliarmos o seu código!

**Comment by LFeh** [comment]
A vaga é CLT?

**Comment by BielRibeiro** [comment]
Opa! é sim @LFeh. Atualizei na issue. Valeu!

**Comment by LFeh** [comment]
Boa!

**Comment by gusribeiro** [comment]
Estão abertos a pessoas de fora do estado com planos de mudança para SP?

**Comment by fejaum** [comment]
Currículo enviado ;)

**Comment by BielRibeiro** [comment]
@gusribeiro por enquanto não podemos ajudar na mudança, mas se você já está vindo pra Sp ou Campinas manda o cv pra gente!

**Comment by BielRibeiro** [comment]
@fejaum valeu!

**Comment by gabriel-ribeiro-ir** [comment]
Vaga fechada pessoal. Obrigado a todos que enviaram os cvs!

**Comment by LFeh** [comment]
\o/

**Comment by camilatigre** [comment]
@gabriel-ribeiro-ir 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by gabriel-ribeiro-ir** [comment]
@camilatigre 
b) Não
Mas recebemos bastante que vieram daqui :)

**Comment by camilatigre** [comment]
Que pena. Mas obrigada por responder!

Em 24 de nov de 2016 10:39, "Gabriel" <notifications@github.com> escreveu:
