### ISSUE TITLE
[Joinville] Front-End Developer na Studio Bluechip

### ISSUE THREAD

**Issue by studiobluechip** [frontendbr/vagas#570]
## Descrição da vaga

Projeto de Jogo em HTML5 e WebGL

## Local

Remoto ou Joinville/Santa Catarina

## Benefícios

- Horário flexível

## Requisitos

**Obrigatórios:**
- experiência em desenvolvimento de jogos com Javascript
- experiência com WebGL
- experiência com Websocket

**Diferenciais:**
- projetos envolvendo jogos de casinos ou similares

## Contratação

Freelancer, CLT ou a combinar

## Nossa empresa

A Studio Bluechip é fornecedora de software de entretenimento e atende clientes situados na América Latina e União Européia.

## Como se candidatar

Envie dúvidas e portfólio para reginaldo@studiobluechip.com

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
