### ISSUE TITLE
[REMOTO] Front-end Developer na Bitwise.ltda

### ISSUE THREAD

**Issue by mendesbarreto** [frontendbr/vagas#5700]
## [Bitwise.ltda](https://bitwise.ltda)

Somos Humanos e amamos trabalhar com pessoas humanas, pode parecer estranha essa frase, mas pense bem nas empresas que você já trabalhou e em algum momento você foi tratado como um robô ou pior como recurso, aqui sabemos que nossos 'wisers' são a nossa assinatura, cultura e o motivo pelo qual nossa empresa existe.

Nosso modelo de negócios combina projetos de valor compartilhado com consultoria nas tecnologias mais avançadas. Esse desafio é uma oportunidade para fazer parte do nosso time em uma jornada de aprendizado e desenvolvimento!

## Descrição da vaga

Fala pessoal sou o [Douglas Mendes](https://github.com/mendesbarreto) atualmente sou o CTO da Bitwise e estou procurando pessoas capazes de produzir conteúdo Front-End para nossos projetos, no momento não procuro por conhecimento em tecnologias especificas como Angular ou React, se você é desenvolvedor, é Web e é fera em alguma tecnologia que está sendo utilizada na atualidade mande seu CV.

## Local

REMOTO

## Requisitos

Que tipo de pessoas buscamos?

Buscamos pessoas que gostem de aprender, que não tenham medo de falhar e que não fiquem presas em paradigmas de programação, pois acreditamos que linguagens, frameworks o SDK's precisam ser escolhidas baseadas na necessidade de cada projeto. E o que isso quer dizer? Simples, quer dizer que nós amamos trabalhar com tecnologias de ponta e quem decidirá as ferramentas a serem utilizadas assim como a composição tecnológica será o time envolvido.

**Desejáveis:**
- Conhecimento em alguma das libs contemporáneas (ReactJS, Angular,  Vue.JS e etc.)
- HTML / CSS
- CSS
- JavaScript
- RESTful services
- SASS
- PNPM, NPM ou yarn (para gerenciamente de pacotes/bibliotecas javascript)
- Repositórios: GIT (Hub/Lab/Flow);
- Saber criar testes unitários
- Frameworks de interface (ex: bootstrap).

**Diferenciais:**
- projetos opensource

## Contratação

- PJ a combinar

## Como se candidatar

Por favor envie um email para vagas@bitwise.ltda. com seu CV anexado e linkedIn profile - enviar no assunto: Nome do candidato + Vaga Front-End

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- Estágio
- Freela
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

## Labels
- PJ
- Freela
- Júnior
- Pleno
- Remoto
- Sênior

**Comment by Darlley** [comment]
Há estágio também ou foi por engano?

**Comment by afoliveira** [comment]
Tentei enviar meu currículo, mas a caixa se encontra cheia

**Comment by mendesbarreto** [comment]
> Há estágio também ou foi por engano?

Não estamos contratando todos os LVLs =)

**Comment by mendesbarreto** [comment]
> Tentei enviar meu currículo, mas a caixa se encontra cheia

Opa, @afoliveira , vou dar uma olhada o que pode estar acontecendo, me mandar direto no meu então: douglas@bitwise.ltda por enquanto.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
