### ISSUE TITLE
[FULL REMOTE, USA] Principal Front-end Developer at @PTCGroup

### ISSUE THREAD

**Issue by marcelamn-PTCGroup** [frontendbr/vagas#5703]
## Nossa empresa

Desenhamos soluções para atender às necessidades de nossos clientes. Atuamos em Engenharia, Consultoria, Tecnologia da Informação e Formação.

## Descrição da vaga

Projeto de contato direto com os Estados Unidos.

## Local

Remoto.

## Requisitos

- Angular;
- Javascript;
- CSS;
- JavaScript;
- Azure DevOps, GitFlow & source control best practices;
- Design Systems & Atomic Design principles knowledge;
- Advanced English (Direct contact with USA).

## Benefícios

- Pagamento em Dólar ou Euro.

## Contratação

PJ.

## Como se candidatar

- E-mail para marcela.nogueira@ptcgroup.com.br com seu CV em inglês anexo - enviar no assunto: Vaga Front-end EUA;
- LinkedIN: https://www.linkedin.com/in/marcelamnogueira/.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
