### ISSUE TITLE
[Porto Alegre] Front-end Developer na Muv Recursos Humanos

### ISSUE THREAD

**Issue by robertafonseca** [frontendbr/vagas#5704]
> 

## Nossa empresa

Nosso cliente atua de maneira customizada apoiando outras empresas do segmento do varejo em soluções inovadoras no processo de transformação digital. Atua com novas tecnologias e possui um ambiente descontraído, com flexibilidade e aprendizado contínuo.

## Descrição da vaga

- Programar, desenvolver e implantar sistemas em linguagem HTML, CSS, TypeScript;
- Realizar correções em sistemas, análise e desenvolvimento de performance;
- Conduzir configuração e gerenciamento de microsserviços com Docker, Kubernetes, Jenkins, GitLab.

## Local

Profissional atuará no modelo híbrido, no Cooworking em Porto Alegre ou Home Office e no cliente em Eldorado do Sul (por volta de 2x na semana).

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento Front-end em HTML, CSS e TypeScript;
- Ferramentas de Build utilizadas no projeto: npm e yarn;
- Outras tecnologias utilizadas: ES6, NgRx ou Redux, Babel, webpack, Web Components, Polyfills;
- CI Jenkins e/ou Gitlab Runner;
- Ter conhecimento em RxJs, React Js ou Angular 5;
- Disponibilidade para atuar em Porto Alegre ou Região Metropolitana ao menos 2x na semana.

**Desejáveis:**
- 
- Conhecimento prévio em tecnologia de Container e em Metodologias Ágeis, SOA e Micro Front-End.

**Diferenciais:**
- Atuação com novas tecnologias;
- Rotina flexível de trabalho;
- Ambiente descontraído;
- Projetos em clientes significativos, com grandes trocas de conhecimentos.

## Benefícios

- Refeição no local e auxílio alimentação;
- Deslocamento fretado ou auxílio deslocamento;
- Remuneração de R$ 6.300,00 a R$ 7.200,00 no regime PJ ou R$ 3.800 (inicial) no regime CLT (a remuneração será avaliada de acordo com as skills técnicas e capacidade de entrega do profissional).

## Como se candidatar

Por favor envie um email para cv@muvrh.com.br com seu CV anexado - enviar no assunto: Front-end Developer.

## Tempo médio de feedbacks

Todos os cvs recebidos recebem retorno em tempo médio de uma semana e todos os candidatos avaliados recebem retorno positivo ou negativo dentro até o prazo de encerramento do processo. WhatsApp para contato em caso de não haver resposta ou para qualquer dúvida em relação a vaga: (51) 99337-9492 - Roberta Fonseca

#### Alocação
- Alocado e Remoto (Híbrido)

#### Regime
- CLT ou PJ

#### Nível
- Júnior
- Pleno

**Comment by robertafonseca** [comment]
@felipefialho É possível excluir a label São Paulo? Profissional atuará em modelo híbrido, sendo 2x na semana aqui com disponibilidade para estar em Poa no escritório ou cliente deles em Eldorado do Sul.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
