### ISSUE TITLE
[REMOTE, USA] Senior Front-end Developer at IOInsure

### ISSUE THREAD

**Issue by gmenegatti** [frontendbr/vagas#5705]
## Descrição da vaga

Olá, pessoal, tudo bem?

Estou ajudando uma empresa dos EUA no recrutamento de 3 desenvolvedores front-end sênior e 1 UX/UI sênior. O trabalho será 100% remoto, seguindo o horário comercial do Brasil. Existe a possibilidade realocação para os EUA ou Austrália, caso a pessoa tenha interesse.

As vagas para pra desenvolvimento são para profissionais com mais de 7 anos de desenvolvimento profissional em front-end e pelo menos 2 anos utilizando Vue.js ou React.

A vaga para UX/UI é para alguém realmente muito sênior, com experiência de pelo menos 5 anos em UX/UI em projetos grandes e onde o UX/UI foi ou é o fator diferencial do produto/projeto.

Em termos de remuneração:
- Desenvolvedores: entre USD 3,500 a USD 5,000 mês, dependendo do nível técnico e comportamental.
- UX/UI: entre USD 4,500 USD a USD 6,000 mês, dependendo do nível técnico e comportamental.

Por favor, se alguém se interessar e/ou tiver alguma indicação, peço gentilmente que me mande o CV para: 
ioinsure@simbioseventures.com

Muito obrigado! 😊

## Local

100% Remoto

## Requisitos

**Obrigatórios:**
- pelo menos 7 anos de experiência com desenvolvimento front-end
- pelo menos 2 anos de experiência Vue.js ou React

## Contratação

- Inicialmente como PJ.
- Mudança para o modelo CLT em 2022.

## Como se candidatar

Por favor envie um email para ioinsure@simbioseventures.com com seu CV anexo.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Sênior
- Especialista

**Comment by vncscoelho** [comment]
Importante para os pretensos candidatos saber desse detalhe bastante importante sobre o modo de contratação dessa empresa:
![image](https://user-images.githubusercontent.com/8714865/135356823-62fa4961-1a62-4aa4-8c62-baf6bc49dc6b.png)

**Comment by jhefflg** [comment]
Ou seja, a pessoa já entra com uma divida na casa de milhar, falta colocar os correntes e levar pro tronco receber chicotiadas.

**Comment by CarlosHenriqueRC** [comment]
Furada total !

******************************************
* Carlos Henrique Ramos Carvalho
* Analista de Sistemas Sênior
* MCP.Net
******************************************


Em qua., 29 de set. de 2021 às 19:29, Jefferson de Lima <
***@***.***> escreveu:

**Comment by victorbiasibetti** [comment]
Não parece tão ruim, se pegar um salario de 4k dólar, no fim da 20k real
240k ano pra 36k de "Multa" é quase nada...isso se o valor se manter o mesmo no CLT

**Comment by cfdavidpetter** [comment]
Pq mudança para o modelo CLT em 2022? E pq essa multa?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
