### ISSUE TITLE
[Remoto] Front-end developer specialist na 5A Attiva

### ISSUE THREAD

**Issue by thaynateixeiras** [frontendbr/vagas#5706]
> Vaga100%  Remota 

## Descrição da vaga

 Foco em desenvolvimento, atuará em um projeto que já está em andamento e podem surgir demandas novas. 

## Requisitos

**Obrigatórios:**
Sólida Viviência com Angular 2 ou superior, Versionamento de código utilizando Git, conhecimentos em técnicas e ferramentas para testes automatizados (unitário e integrado), Fluência com Git Flow, conhecimento de arquitetura de microserviços, Docker  e Linux. 

**Desejáveis:**
-  Scrum 
- Conhecimento de Ruby On Rails e/ou .NET 

## Contratação

PJ - Após 6 meses receberá proposta CLT

## Como se candidatar

Por favor envie um email para thayna.silva@5aattiva.com.br com seu CV anexado - enviar no assunto: Vaga Especialista Angular

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
