### ISSUE TITLE
[Remoto] Full Stack Web na Right Balance

### ISSUE THREAD

**Issue by yohanlimapo** [frontendbr/vagas#5708]
## Nossa empresa

- What are your typical clients?
The majority of our clients are venture-backed startups at the growth stage. Usually, at this stage, the company already achieved a product-market fit and is looking to expand rapidly.
That’s where we bring the best engineering practices, strong architecture, and the latest technologies to help companies scale.
- What is the length of your projects?
Most of our long-term full-time engagements last multiple years.
- What’s your company size?
The Right Balance team is 15 engineers and growing to 25 by the end of the year. The current client size team is 20 people rapidly expanding to 50 people.
- What happens if the engagement is completed?
Most of our engagements are long-term in nature. That said, if the current project is ramping
down, we’ll present you with more long-term opportunities to transition into.
- What are your core values?
We value autonomy, grind, empathy, mastery, and giving back to the community. We expect you to be autonomous, working directly with the client to build the best product. 

## Descrição da vaga

As a full stack web developer, you’ll be responsible for developing robust, scalable full-stack deployment of Serverless web applications using Vue.js, AWS Lambda, Node.js, and FastAPI. Also, want to get your hands dirty with writing some data massaging code using R or Python?

## Local

Remoto

## Requisitos

**Obrigatórios:**
1. 3+ years of full-time hands-on full-stack (backend and front-end) web development experience using Javascript.
2. 2+ years of full-time hands-on experience with modern web technologies (Vue / React / latest Angular, Express / Koa).
3. The proven history of being productive with multiple languages the right idiomatic way.
4. Working knowledge of UI/UX best practices and clear understanding of what makes good UX.
5. Advanced verbal level of English.
6. Experience working with AWS.
7. Ability to lead by example, understand client’s goals, create and implement solutions to achieve them in a team setting.
8. Experience working directly with a Product Manager, Designer, QA Engineer, Data Scientists, and Data Engineers in a highly collaborative and proactive way.
9. Strong knowledge of scalable front end and backend API architecture, best practices, and tools.
10. Use best practices for writing secure and reliable web applications.
11. Passion for innovation and execution.
12. Expert level problem solver.
13. Commitment to quality engineering.
14. Ability to think and act strategically and proactively.

**Desejáveis:**
1. 1+ year of hands-on Python.
2. Develop interactive data science visualizations (includes the opportunity to learn the power of R Shiny).
3. Experience with API integration.
4. Degree in Computer Science, Software Engineering, or related technical field from a top-tier university (or equivalent industry experience at a major technology company).
5. Expertise in ensuring cross-browser and cross-device compatibility.
6. Experience in an Agile work environment with automated tests, and CI/CD.
7. AWS Lambda experience.
8. Serverless framework experience.
9. Automated testing.
10. Runtime complexity analysis using Big O notation.

## Benefícios

- Payment in dollar

## Contratação

PJ a combinar

## Como se candidatar

Further details and to apply [click here](https://lnkd.in/dQWV5Rn5)
Contact: Yohan - yohan.limapo@kstack.com.br

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: yohan.limapo@kstack.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
