### ISSUE TITLE
[Rio de Janeiro] Front-End/Full-Stack Developer no Hotel Urbano

### ISSUE THREAD

**Issue by zanaca** [frontendbr/vagas#571]
## Descrição da vaga

Como faz para encontrar diárias possíveis em uma base de aproximadamente alguns gigas de dados e tendo que trabalhar com variações de atributos como: tipo de quarto, alimentação, atividades extras entre outras. Para complicar o problema ainda temos que entregar no menor tempo possível pois o usuário não esperará por muito tempo essa resposta.

Se vc gostou do problema, venha fazer parte do time. Nossa arquitetura esta organizada em microserviços e os projetos de front se concentram em: NodeJS e Python

Níveis: Júnior, pleno e sênior

## Local

Escritório, Barra da Tijuca - Rio de Janeiro

## Benefícios

- Plano de saúde Amil 500 (com coparticipação)
- Seguro de vida
- VR e/ou VA, R$495,00 mensal 
- VT ou Auto Combustível
- Auxílio Funeral
- Auxílio creche 
- Convênio Farmácia
- Convênio Academias
- Política Educacional
- Inglês Corporativo

#### Diferenciais

- folga no dia ou na semana do seu aniversário ou no do seu filho :)
- sala de jogos
- café da manhã todos os dias, de 8h às 9h
- shiatsu 2x na semana
- Dia Internacional da Cerveja! Toda sexta é garantido ;)

## Requisitos

**Obrigatórios:**
- Experiência com NodeJS ou Python;
- Precisa ser apaixonado por desenvolvimento e tecnologia;
- Deve entender que o trabalho em equipe é o diferencial para o sucesso;
- Escreve código com testes por padrão;
- Domina uma linguagem de Programação
- Tem Experiência com desenvolvimento WEB (HTML, CSS, Javascript, etc);
- É capaz de colocar uma aplicação em ambiente de produção;
- Já fez uso de Sass, Less, jQuery, Bootstrap, HTML5.

**Desejáveis:**
- 2 anos de experiência com NodeJS ou Python;
- Experiência em Jasmine, Underscore.js, Angularjs;
- Conhece Gulp/Grunt, Ember, Backbone, Bower, NPM, NodeJS;
- Conhecimentos em Docker;
- Conhecimentos de React;
- Experência com práticas de XP (TDD, pair programming, refactoring, continuous integration, etc);
- Conhecimento de técnicas cross-browser, SEO, HTML5 e CSS3;
- Experiência com metodologias ágeis, como Kanban Scrum;
- Experiência com infra-estrutura de aplicações web de alta escala;
- Conhecimento de orquestração de deploy;
- Ser poliglota em linguagens de programação e linguagens naturais;

**Diferenciais:**
- projetos opensource

## Contratação

PJ ou CLT

## Nossa empresa

Uma das maiores agências de turismo online do mundo precisa do seu talento.

Procuramos pessoas inteligentes e ágeis como você para nos ajudar a resolver desafios de escalabilidade e performance. Trabalhamos com diversas linguagens, como Python, Go, NodeJS e PHP, além de tecnologias como Elastic Search, Redshift e Docker, acreditamos na filosofia "release early, release often". Aqui não tem embromação. 🔪💀

A visão do Hotel Urbano é realizar o match dos nossos usuários com a viagem dos sonhos.

Números do Hotel Urbano:

mais de 150.000 hotéis ao redor do mundo;
18 milhões de viajantes cadastrados;
1 diária vendida a cada 8 segundos;
20 milhões de pessoas buscando viagens todo mês;
12 milhões de fans no facebook;

## Como se candidatar

Por favor preencha o nosso formulário através do link http://viajar.hu/gentehu ou abra uma issue em https://github.com/HotelUrbano/vagas/branches

**Comment by vinyguedess** [comment]
Aceita remoto ?

**Comment by JonasEmanuel** [comment]
Formulário preenchido

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by ruanmer** [comment]
@LFeh Sim, ainda aberto

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
