### ISSUE TITLE
[São Paulo] Front-end Developer na UOL

### ISSUE THREAD

**Issue by AnaFeitosa** [frontendbr/vagas#5712]
> Vaga Remota durante a pandemia

## Descrição da vaga

Conhecimentos técnicos:

 

- Superior completo ou em andamento em Ciência da Computação, Engenharia, Sistemas da Informação ou áreas correlatas;

- Bons conhecimentos de desenvolvimento de lógica e algoritmos;

- Experiência no desenvolvimento de aplicações com serviços RESTful e micro serviços;

- HTML/HTML5, CSS3, JavaScript, React;

- Design responsivo, media query, mixins, functions e extends;

- Ter conhecimentos dos conceitos Mobile First e SEO;

- Inglês intermediário;

- Experiência em controle de versionamento de códigos (git, svn);

 

Desejável:

 

- Conhecimentos DevOps (Kubernets, AWS)

## Local

Exemplo: Remoto ou Escritório, SÃO PAULO

## Requisitos

**Desejáveis:**
Conhecimentos DevOps (Kubernets, AWS)

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para anafeitosa.rj@gmail.com com seu CV anexado - enviar no assunto: Front End Pleno

#### Alocação
 Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
