### ISSUE TITLE
[REMOTO] Estágio em Desenvolvimento na Codex Agro 

### ISSUE THREAD

**Issue by luanasantosog** [frontendbr/vagas#5714]
## Nossa empresa

A Codex Agro, é especialista em soluções de inteligência em diagnóstico, prognóstico, monitoramento e inteligência comercial, reunindo grande capacidade em geração e gestão de dados estratégicos para o Agronegócio no Brasil.
Conheça mais sobre nossa empresa em: https://www.vegamonitoramento.com.br/

## Local

Remoto.

## Requisitos

**Formação:**
- Curso superior em andamento em TI (Ciência da Computação, Sistemas de Informação, Engenharia da Computação) ou áreas similares.

**Conhecimentos Desejáveis:**
- Conhecimento em programação;
- Conhecimento básico de GIT.

**Diferenciais:**
- Conhecimento básico em ReactJs / ReactNative / Java / Javascript / VueJS

**Responsabilidades:**
- Desenvolver novas funcionalidades para produtos da CODEX;
- Realizar a análise e manutenção de sistemas desenvolvidos;
- Participar dos ritos de SCRUM em conjunto com sua equipe;
- Documentar códigos e funcionalidades desenvolvidas;
- Criar testes de unidade com apoio de um tutor;
- Avaliar os riscos e impactos nos desenvolvimentos; 
- Administrar tarefas, prioridades, prazos e tempos estimados de desenvolvimentos; 
- Aprimorar conhecimentos sobre regras de negócio dos sistemas atendidos.

## Contratação

Estágio

## Como se candidatar

Interessados e dentro do perfil, enviar currículo atualizado com pretensão salarial para recrutamento@img.com.br 
informando no assunto: Estágio em Desenvolvimento - Github

#### Alocação
- Remoto

#### Regime
- Estágio

#### Nível
- Júnior

**Comment by devdavidos** [comment]
Enviado, só contratar agora usahus.

**Comment by alexn4ow** [comment]
- [ x ] Enviar currículo;

**Comment by remoteck** [comment]
public Curriculo(File curriculo) {
      Console.WriteLine("Currículo enviado com sucesso!");
}

**Comment by luanargolodev** [comment]
Enviado!

**Comment by luansilvae** [comment]
Currículo enviado!

**Comment by Emersons93** [comment]
Currículo enviado.

**Comment by nJadson** [comment]
Currículo enviado :)

**Comment by vanessawin** [comment]
Currículo enviado

**Comment by caiquefds** [comment]
Enviado!

**Comment by M4teusPrado** [comment]
Enviado!!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
