### ISSUE TITLE
[BRASIL/100% REMOTO] Front-end/Angular Developer Pl/SR na BRQ Digital Solutions

### ISSUE THREAD

**Issue by ReAnne123** [frontendbr/vagas#5716]
FRONT ANGULAR PLENO/SÊNIOR

Ei Front Angular, chegou o momento de encarar um novo desafio em sua carreira! Venha ser um #ferabrq  

O que procuramos?
Buscamos #feras com espírito empreendedor e que sabe que é o verdadeiro protagonista do seu sucesso! Queremos em nosso time pessoas motivadas por desafios, constante evolução e, claro, que são apaixonadas por tecnologia e transformação! 

O que você deve ter?
Experiência com aplicações web com AngularJS e Angular 2+
Metodologia Agil: Scrum
Testes unitários com: Jasmine ou Jest
Noções de web-pack, Node.js, Jenkins, Kubernates, Docker, Docker Compose, NGINX.
Atuação em cliente da BRQ multinacional do setor bancário.
100% Remoto e CLT full.

O que temos pra te oferecer? 
Mais do que um plano de carreira! 

A BRQ acredita que cada fera deve ser protagonista do seu crescimento, tendo autonomia para criar seu próprio plano de desenvolvimento profissional. Nosso plano de carreira é dividido em 4 etapas: 
- Carreira técnica: Você pode seguir a trilha de crescimento técnico, se o seu objetivo for se desenvolver cada vez mais em diferentes tecnologias. Oferecemos diversos treinamentos!
- Mobilidade Interna: Você quer um novo rumo profissional? Aqui dentro de casa temos diversas opções diferentes e o programa de mobilidade interna, que te permite mudar de área, por exemplo.
- Experiência internacional: Estamos crescendo cada vez mais fora do Brasil e você tem possibilidade de atuar em projetos para outros países, ou diretamente nos países onde a BRQ tem sede.
- Empreendedorismo: De funcionário para sócio! Temos o Innovation Hub, a Corporate Venture que investe em ideias de profissionais que tenham sinergia com nosso negócio. 

E os benefícios? 
Plano de Saúde; Plano Odontológico; Seguro de Vida; Vale Refeição; Vale Alimentação; Horário Flexível; Home Office; Gympass, Telemedicina, Telenutrição, Canal de suporte emocional 24h e muito mais! 

Como é trabalhar na BRQ? 
Temos um clima descontraído, diversos programas e eventos internos. Adoramos comemorar! E fazemos isso muito bem! Veja aqui no Youtube: youtube.com/brqdigitalsolutions 

Curtiu? Então inscreva-se e venha para o melhor da Transformação Digital com a gente! 🚀
**Envie seu cv  para Renata (ryokota@brq.com).**

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
