### ISSUE TITLE
[REMOTO] Front-end Developer na C&A

### ISSUE THREAD

**Issue by yohanlimapo** [frontendbr/vagas#5717]
> Vaga Remota durante a pandemia e após

## Nossa empresa

Somos uma empresa inovadora, divertida e, acima de tudo, apaixonada pelas pessoas. Ao longo de mais de 170 anos de história, atuamos com ética e foco para que você e todos os nossos clientes estejam sempre satisfeitos.

## Descrição da vaga

Desenvolvimento de sistemas Front End (WEB) utilizando React

## Local

Remoto

## Requisitos

**Obrigatórios:**

- Experiência com plataforma Vtex.
- Sólidos conhecimentos em utilização de nuvem ( AWS, Azure, etc ).
- Linguagens: HTML5, CSS3, SASS, ReactJS , Javascript ou Typescript.
- Webservices: SOAP e REST
- Controle de Versão: Git, GitFlow
- Integrações com serviços web (APIs Rest).
- Testes Unitários
- Ter trabalhado com sistemas web, preferencialmente:
- ecommerce, pagamentos, etc...
- Experiência em sistemas de alta disponibilidade.
- Conhecimento em delivery contínuo.
- Experiência de +5 anos de experiência com desenvolvimento de software.
- Atuação em times com metodologia ágil.

**Desejáveis:**

- Outras linguagens de programação (AWS, Azure, NodeJS, Java, etc)
- Experiência prévia em ambientes complexos
- Experiência prévia com portais ou sistemas de ecommerce
- Conhecer ferramentas/frameworks de testes automatizados
- Conhecimentos em TDD
- Noções de programação back-end (NodeJS)
- Conhecimento em AngularJS
- Conhecimento em React Native
- Conhecimentos em UX/UI Design

**Diferenciais:**

- Outras linguagens de programação (AWS, Azure, NodeJS, Java, etc)
- Experiência prévia em ambientes complexos
- Experiência prévia com portais ou sistemas de ecommerce
- Conhecer ferramentas/frameworks de testes automatizados
- Conhecimentos em TDD
- Noções de programação back-end (NodeJS)
- Conhecimento em AngularJS
- Conhecimento em React Native
- Conhecimentos em UX/UI Design

## Benefícios

- 100% Remoto

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para yohan.limapo@kstack.com.br com seu CV anexado - enviar no assunto: Vaga Front-End

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: yohan.limapo@kstack.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
