### ISSUE TITLE
[Remoto] Fullstack Developer na Pix Force

### ISSUE THREAD

**Issue by jeanpereiraa** [frontendbr/vagas#5718]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/pessoa-desenvolvedora-full-stack-135221690?origin=github&medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Buscamos <strong><ins>Fullstack Developer </ins></strong>com conhecimento em python ou node.js e react ou vue.js, para compor nosso time.</p>
<p>A Pix Force desenvolve soluções utilizando tecnologias de visão computacional e inteligência artificial.&nbsp;</p>
<p><strong><em>1 no ranking da 100 open startups em 2020. </em></strong></p>
<p>Estamos em total expansão e com planos de internacionalizar em 2021.</p>
<p>Estamos crescendo e buscando talentos para fortalecer o nosso time.&nbsp;</p>
<p>Você irá atuar em projetos de desenvolvimento para web com soluções em visão computacional e desenvolvimento de software.</p>
<p>Vamos juntos?</p>

## Pix Force: 
 <p>A Pix Force desenvolve soluções utilizando tecnologias de visão computacional, inteligência artificial e machine learning. Fornecemos informações valiosas para os nossos clientes através de aquisição e interpretação automática de imagens e vídeos.</p>
<p>Startup #1 em visão computacional no Brasil e multipremiada.</p><a href='https://coodesh.com/empresas/pix-force'>Veja mais no site</a>

 ## Habilidades: 
 - Python 
- Node.js 
- Vue.js 
- React.js
## Local: 
 100% Remoto
## Requisitos: 
 - Graduação (ou em andamento) na área de ciências da computação e áreas correletas; 
- Experiência em linguagens Python no Backend; 
- Experiência com frameworks de Frontend como VueJS (preferencial) ou React.
## Diferenciais: 
 - Conhecimento em Docker, Linux, Git e Bitbucket. 
- Experiência de 1 ano em desenvolvimento de software.
## Benefícios: 
 - Horários flexíveis
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack Developer na Pix Force](https://coodesh.com/vagas/pessoa-desenvolvedora-full-stack-135221690?origin=github&medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
