### ISSUE TITLE
[REMOTO] Front-end Developer Senior na Atlas Governance

### ISSUE THREAD

**Issue by Bruhraposo** [frontendbr/vagas#5719]
> A Atlas é uma Startup de Software, que traz segurança e inovação em todos os processos de um conselho de administração.
Todas nossas ações são tomadas baseadas em quatro valores: Capital Humano, Clientecentrísmo, Qualidade e Segurança. Onde o nosso principal valor é o Capital Humano.
> Somos feitos de pessoas apaixonadas, inquietas, questionadoras e ousadas que nos ajudam a buscar soluções de impacto que aceleram o nosso crescimento. Unindo tecnologia, infraestrutura, desenvolvimento, respeito, diversidade e construindo relações significativas.
> Estamos em uma fase de crescimento acelerado, buscando por pessoas que tenham brilho nos olhos por esses desafios e que queiram fazer parte da construção de um mundo melhor. Você terá a oportunidades de analisar, propor e implementar iniciativas que estejam conectadas à nossa Cultura.

**O que você vai fazer no seu dia a dia:

• Fazer a ponte entre a parte visual e a implementação técnica, consumindo serviços e implementando a integração entre o Front-End e o Back-End
• Desenvolver as funcionalidades de contato com o usuário
• Garantir a viabilidade técnica dos designs de UI/UX produzidos
• Otimizar a aplicação para melhor velocidade e escalabilidade
• Garantir a validação dos dados fornecidos pelos usuários antes de enviá-los ao Back-End
• Criar códigos e bibliotecas reutilizáveis para uso futuro
• Colaborar com outros membros da equipe

**O que estamos procurando na pessoa que vai fazer parte do time:

• Experiência com desenvolvimento em alguma das tecnologias web como:
• Framework React JS • Gerenciamento de estado com Redux • Utilização de Hooks • Integração com API Rest • HTML e CSS

**Além disso… o que mais você pode ter?

• React Native • Sass • Azure Devops • Experiência com metodologia Ágil

Informações adicionais:

Formato contratação: Cooperativa (valor cai líquido para o desenvolvedor, não há descontos)
Modelo: Trabalho remoto / home office
Localidade: Qualquer
Benefícios: Aulas de Espanhol; Gympass; Plano de saúde; 13° salário; Vale refeição; Recesso remunerado; Folga no aniversário.

Interessados, pode mandar CV para bruna.oliveira@atlasgov.com

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
