### ISSUE TITLE
[Remoto] Software Developer Full Stack na Delivery Direto

### ISSUE THREAD

**Issue by LeandraNicolau** [frontendbr/vagas#5720]
## Nossa empresa

Ajudamos restaurantes e pequenos negócios a terem uma operação do dia-dia mais fluida e a se conectarem com clientes. O nosso primeiro produto é o Delivery Direto, a maior plataforma white label de delivery online do Brasil. Somos dos mesmos fundadores do Guia Kekanto, temos uma cultura forte de produto (ganhamos vários prêmios do Google e Apple) e nossos investidores têm raízes fortes no Vale do Silício (Kaszek Ventures, Accel Ventures - dos mesmos investidores do Facebook e outros) e hoje fazemos parte do grupo Locaweb, uma empresa com centenas de milhares de clientes e capital aberto na B3.

## Descrição da vaga

Buscamos Engenheiros e Engenheiras de Software que gostem de aprender e encarar novos desafios para surpreender os clientes do Delivery Direto com um produto robusto e encantador. Você vai ajudar na arquitetura e implementação de sistemas complexos participando de projetos em todas as fases, desde sua concepção até a manutenção.

# **O que vou fazer?**

- Integrar um time apaixonado por tecnologia com muita fome de aprendizado;
- Evoluir um produto à frente do mercado, incorporando tecnologias modernas que nos ajudam a escalar;
- Implementar sistemas e funcionalidades que fazem a diferença no Delivery Direto;
- Garantir a qualidade e robustez do código produzido de acordo com os padrões acordados pelo time;
- Ter autonomia para resolver problemas.

## Local
- Remoto ou no espaço de trabalho Locaweb/SP (opcional)

## Requisitos

**Obrigatórios:**
- Conhecimento avançado em banco de dados relacionais
- Algumas das tecnologias que usamos em nossa stack: JavaScript, HTML, CSS, PHP, Kotlin, Flutter, Vue.js
- Conhecimento de padrões de código e boas práticas de desenvolvimento
- Escrita e manutenção de testes unitários e de integração
- Conhecimento Intermediário em Inglês

## Benefícios
- Plano de saúde e odontológico Sul América
- Seguro de vida MeetLife
- VA/VR
- Auxílio home office
- Gympass
- Horário de trabalho flexível

## Contratação
- CLT

## Como se candidatar

Através da página [Desenvolvedor(a) de Software - Web Full Stack](https://deliverydireto.notion.site/Desenvolvedor-a-de-Software-Web-Full-Stack-329375c34f464a39a51d6eda7a6f2468)

#### Alocação
- Remoto

#### Regime
- CLT
- Estágio

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
