### ISSUE TITLE
[Remoto] Front-end Vue.js Developer @ Fácil Consulta

### ISSUE THREAD

**Issue by KrishnaXavier** [frontendbr/vagas#5722]
## Descrição da vaga

Estamos buscando alguém com experiência com Vue.js e Bootstrap, podendo ser Júnior, inicio de Pleno ou Pleno. Queremos alguém para incrementar o time de forma contínua, queremos que essa pessoa fique por tempo indeterminado.

Prezemos antes de tudo alguém com muita vontade, potencial e paixão pelo Front-end.

## Local

100% Remoto 

## Benefícios

- Crescimento rápido
- Oportunidades de se tornar líder da área de Front-end  ou de algum time

#### Diferenciais

- Horário flexível
- Cultura jovem e aberta
- Foco no resultado
- Jogos online e dinâmicas divertidas
- Cultura transparência, dados do negócio 100% abertos

## Requisitos

**Obrigatórios:**
- Vue.js
- Bootstrap

**Desejáveis:**
- Experiência com HTML, CSS3 e JS
- Experiência com Vue.js e Bootstrap
- Web Design Responsivo
- Perfil Resiliente, Inovativo, Humildade, Apaixonado por Front-end, Focado nos resultados

**Diferenciais:**
- Experiência com: Sass, Blade templates, Figma, Git e Comunicação com APIs
- Experiência com: Metodologias Ágeis, como SCRUM e Squad

## Contratação

PJ, tempo integral. Queremos alguém por tempo indeterminado, que fique no Fácil Consulta para sempre

## Nossa empresa

O Fácil Consulta é uma Startup com base tecnológica que resolve o problema de milhares de pessoas que procuram por um médico!

Somos um marketplace de agendamentos de consultas médicas e estamos em 11 cidades. Nossa meta é chegar a 100 cidades.

**Aqui usamos:**
- Vue.js
- Bootstrap
- HTML, CSS, JavaScript
- PHP
- Laravel
- AWS

## Como se candidatar

# [Link para inscrição](https://bit.ly/front-end-vuejs-gi) 

#### Alocação
- Remoto

#### Experiência
- Júnior
- Inicio de Pleno
- Pleno

#### Regime
- PJ

**Comment by droid95** [comment]
Fala @KrishnaXavier , o form está sem o botão de enviar currículo. Existe a possibilidade de te enviar o currículo completo por email? Gostaria de fazer parte do processo seletivo aí na Fácil Consulta.

**Comment by robinndev** [comment]
Enviei o form, não havia pedido de currículo, o fiz completo, caso necessitem, posso enviar por e-mail, desde já agradeço!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
