### ISSUE TITLE
[REMOTO] Front-end Developer na Imagem Sistemas

### ISSUE THREAD

**Issue by luanasantosog** [frontendbr/vagas#5723]
A CODEX é uma empresa do Grupo Imagem, com foco em desenvolvimentos especializados que combinam sistemas de informação, consultoria setorial, especialistas em tecnologia e melhores práticas de gestão para apoiar nossos clientes de forma integrada, atendendo aos mais diversificados processos de negócios.
Conheça mais sobre nossa empresa em: www.imgsistemas.com.br

## Local

Remoto

## Requisitos

**Formação:**
- Formação em curso superior de ciências da computação, análise de sistemas e/ou sistemas de informação.

**Temos alguns requisitos importantes nessa vaga::**
- Domínio Angular 8+;
- Conhecimento em Typescript;
- Amplo Conhecimento em Javascript;
- Conhecimento em CSS.

**Desejável:**
- Conhecimento em GIT;
- Vivência em Desenvolvimento Ágil;
- Conhecimento em padrões e boas práticas para web;
- Experiência com CI/CD.

## Contratação

A combinar

## Como se candidatar

Interessados e dentro do perfil, enviar currículo atualizado, e pretensão salarial para recrutamento@img.com.br
informando no assunto: Front-end Developer - Github

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
