### ISSUE TITLE
[REMOTO] Front-end Developer na BLUEMOND

### ISSUE THREAD

**Issue by biaberbert** [frontendbr/vagas#5726]
> Vaga Remota 

## Nossa empresa

> A BLUEMOND é uma empresa que nasceu em 2017, sempre aprimorando nosso serviço a partir do feedback das empresas que atendemos, construindo uma relação de longo prazo, graças ao excelente serviço que nossos desenvolvedores prestam. Promovemos a cultura das startups em seus serviços, você encontrará desenvolvedores que se adaptam e adotam a mentalidade da sua empresa, assumindo junto a você e o seu time os principais desafios do seu projeto, superando eles das formas mais eficientes e eficazes.
> Nosso sucesso está em conectar diversas habilidades e experiências, os principais talentos do mercado junto a empresas que estão transformando os seus mercados com tecnologia.

## Local

 Remoto  [Minas Gerais], [Belo Horizonte]

## Requisitos

**Obrigatórios:**
React (Pleno/Sênior)
React Native (Pleno/Sênior)
Redux (Pleno)
Redux Saga (Pleno)
Integração do Front com APIs Rest (Pleno)
Hooks (Pleno)
Graphql (Pleno)
Formik (Pleno)
TypeScript (Pleno)

## Contratação
Valor: A combinar até R$ 10.500 fixo mensal (+Bônus no segundo projeto)
Modelo: PJ
Dedicação: Até 40 horas semanais (Segunda a sexta-feira em horário comercial)

## Como se candidatar

Por favor envie um email para beatriz@bluemond.com.br com seu CV anexado - enviar no assunto: Vaga ReactNative
Ou se cadastre no nosso banco de talentos em nosso site https://bluemond.com.br/trabalhe-com-a-bluemond/

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: beatriz@bluemond.com.br

## Labels
PJ
Remoto
Sênior
Belo Horizonte

#### Alocação

- Remoto

#### Regime

- PJ

#### Nível

- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
