### ISSUE TITLE
[REMOTO] Seja Front-end Developer na Lello!

### ISSUE THREAD

**Issue by Mariadafne** [frontendbr/vagas#5727]
## Nossa empresa ❤

A **Lello Imóveis** é uma empresa que atua desde 1954 no mercado imobiliário Paulistano, com Vendas de Imóveis Prontos, Locação e Administração. Possui uma rede de atendimento com **22 unidades** e tem quase **1.000 colaboradores**. Trabalhe na Lello e encontre o lugar certo para seus clientes!

## Descrição da vaga

**O QUE ESPERAMOS DE VOCÊ**

Espírito de dono, paixão pelo que faz e colaboração com um time multidisciplinar
focado no desenvolvimento de uma solução inovadora, democrática e escalável que
contribua para a transformação do mercado imobiliário e ajude as pessoas a ter a
melhor experiência na jornada de busca pela sua moradia e bem estar.

## Local

Remoto🖥

## Requisitos

**Obrigatórios:**

- HTML/CSS;
- Sass/Less/Jss;
- Desenvolvimento de sites responsivos;
- Javascript ES6+;
- Typescript;
- System design;
- SEO;
- React;
- Git;
- Consumo de APIs REST;
- Testes (Jasmine, Mochajs, Cypress, Jest, outros);
- State containers (Redux, MobX);
- Bundlers (Webpack, Parcel, outros).

**Desejáveis:**

- Programação funcional;
- Gatsby;
- NodeJS;
- Docker;

**Diferenciais:**

- AWS;
- Alguma linguagem back-end.

## Benefícios 🤑

🥗Vale Refeição
😍Assistência Médica
💕Seguro de Vida
👍Auxílio Farmácia

## Contratação

CLT

## Como se candidatar

Para se candidatar e/ou saber mais sobre a vaga, acesse: **https://bit.ly/3EylBrO**

#### Alocação

- Remoto

#### Regime

- CLT

#### Nível

- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
