### ISSUE TITLE
[Remoto | Portugal] Django Senior Developer @ PROMPTEQUATION

### ISSUE THREAD

**Issue by eesteves-odoogap** [frontendbr/vagas#5728]
## Nossa empresa

Aqui na **PROMPTEQUATION** somos especialistas em Odoo e Ready Partners para os Estados Unidos no entanto estamos
expandido a nossa area de negócio eCommerce e outros Productos.

_Aqui usamos:_
- Vue.js
- Python
- AWS
- Odoo
- Apache Airflow

## Descrição da vaga

We are looking for a passionate Python / GraphQL / REST developer to join our team of senior developers to help us build an exciting Health Care solution.

A good candidate would be familiar with writing good quality and tested **Django**/Python code and would be well-versed with **API development** and some minor DevOps skills.

## Local

Remoto ou Escritório - Portugal (Viseu ou Aveiro)

## Requisitos

**Obrigatórios:**
- 2 ano de experiência com Django/Python
- 2 anos de experiência com GraphQL
- 2 anos de experiência com REST

**Desejáveis:**
- DevOps skills

**Diferenciais:**
- Opensource projects
- GDPR / HIPAA Compliance Knowledge
- Advanced verbal English communication skills

## Contratação

PJ a combinar.

## Como se candidatar

Para se candidatar e/ou saber mais sobre a vaga, acesse: 
https://erp.odoogap.com/jobs/detail/django-senior-developer-remote-13

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- Freelancer
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
