### ISSUE TITLE
[Presencial Jardim Paulista] Desenvolvedor Front-end na Hagloo

### ISSUE THREAD

**Issue by giovaniPoletohagloo** [frontendbr/vagas#5729]
Responsabilidades:
•	Desenvolvimento de plataforma;
•	Programar em Javascript;
•	Trabalhar em colaboração com a equipe.
Requisitos:
•	Experiência com React; 
•	Experiência com Javascript;
•	Inglês avançado.
Formação:
•	Superior Completo em TI ou cursos correlatos.
Diferencial:
•	Conhecimentos no mercado imobiliário e finanças;
•	Experiência com Typescript;
•	Experiência com React Native.
SOBRE A VAGA:
•	Regime de contratação: PJ ou Cooperado
•	Escala: Presencial - segunda a sexta, das 09h às 18h
•	Benefícios: café da manhã na empresa, day-off no dia ou mês do aniversário, parceria com o SESC, parceria com faculdades e cursos, descontos em restaurantes da região.

CVs via: rh@hagloo.com

**Comment by giovaniPoletohagloo** [comment]
Ainda em aberto!

**Comment by victorbiasibetti** [comment]
presencial onde?

**Comment by victorbiasibetti** [comment]
não, eu moro em florianópolis

**Comment by giovaniPoletohagloo** [comment]
Entendi!

Aparecendo uma 100% home office, posso lhe avisar?

**Comment by victorbiasibetti** [comment]
claro

**Comment by giovaniPoletohagloo** [comment]
Vaga ainda em aberto!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
