### ISSUE TITLE
[Hibrido / São Paulo, São Paulo, Brazil] Fullstack Developer (Sênior) na Elumini S.A.

### ISSUE THREAD

**Issue by jeanpereiraa** [frontendbr/vagas#5731]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/senior-fullstack-developer-171023600?origin=github&medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>Elumini S/A</strong> está buscando <strong><ins> Fullstack Developer nível sênior</ins></strong> para atuar em projeto de Digital TV, Aplicação e 2 way Messaging de forma remota, mas com possibilidade de eventuais reuniões no escritório em São Paulo.</p>
<p><strong>Atividades:</strong></p>
<ul>
<li>Portar sistema legado responsável pela criação/aprovação de mensagens a serem enviadas para decodificadores de TV (hoje em ASP.NET) acessando SQL Server,  rodando em servidor dedicado para ambiente Cloud.&nbsp;</li>
<li>Integrar (via REST API) o sistema com um serviço de envio de mensagens que utiliza protocolo MQTT.</li>
</ul>
<p></p>
<p></p>
<p></p>

## Elumini S.A.: 
 <p>A Elumini é uma consultoria de TI no mercado desde 2004, que hoje atua como parceira tecnológica na Transformação Digital de empresas dos mais variados setores. (indústrias, bancos, seguradoras, telecomunicações, logísticas etc.).</p>
<p>Com processos certificados ISO 9001:2015 e escritórios no Brasil, Portugal e EUA, opera a nível internacional, mantendo o padrão no atendimento e na qualidade nas entregas.</p><a href='https://coodesh.com/empresas/elumini-sa'>Veja mais no site</a>

 ## Habilidades: 
 - Javascript 
- HTML 5 
- CSS 
- React.js 
- Rest API 
- GIT 
- GitLab 
- .NET Core 
- Programação Orientada a Objetos (POO) 
- AWS Lambda
## Local: 
 São Paulo, São Paulo, Brazil
## Requisitos: 
 - Experiência como Desenvolvedor Fullstack; 
- Conhecimento de JavaScript, HTML5, CSS, React JS, Rest API; 
- Git, GitLab Flow, GitLab CI/CD; 
- .Net (Core + Asp.Net); 
- Object Oriented Programing (básico); 
- Elastic Beanstalk e Lambda (básicos); 
- Inglês.
## Diferenciais: 
 - Node JS; 
- Data Modeling with relational databases; 
- AWS: DB(Aurora/ DynamoDB), Cloud Formation; 
- Networking:FTP, MQTT.
## Benefícios: 
 - Assistências Médica e Odontológica SulAmérica;  
- Seguro de Vida Prudential;  
- Vales Transporte e Refeição; 
- Gympass;  
- Programa de Incentivo a Plataforma Alura, com mais de 1.200 cursos em tecnologia digital.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack Developer (Sênior) na Elumini S.A.](https://coodesh.com/vagas/senior-fullstack-developer-171023600?origin=github&medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Regime
CLT
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
