### ISSUE TITLE
[Remote] Senior Frontend Engineer @ Nomad Homes

### ISSUE THREAD

**Issue by gfrancischelli** [frontendbr/vagas#5732]
## Nossa empresa

[Nomad](https://workat.nomadhomes.co/) is looking for a Senior Frontend Software Engineer to help in our mission to make buying homes in EMEA ridiculously easy. While we can trade stocks, order cars, or book short-term stays seamlessly online, the process of buying a home across the region remains slow, paper-driven, and inefficient. We’re building an end-to-end experience to empower buyers to search, transact, and finance under one roof.

Our founding team consists of operational, engineering, and real estate professionals from Uber, Addepar, UberEats, and PeerStreet. We are also ex-Blackstone, Goldman Sachs, Gilt, General Assembly and Jump. We launched in 2020 and now have operations in both Dubai and Paris. We are a Series A company with rockstar investors including Comcast Ventures, Partech, Abstract Ventures, Precursor Ventures, WndrCo, and Class 5 Global.

As a Frontend Software Engineer you will work on core user-facing product for multiple markets and back-office tools. Joining our small development team at such an early stage means you will have significant impact on our product and engineering with many opportunities to learn and grow.

## Descrição da vaga

- Be at the source of bringing change to real estate market in EMEA region
- Build frontend applications for Dubai, Paris and future markets
- Take an ownership on building new features on Nomad platform
- Collaborate with design and product peers to build world-class level product

## Local

Remote

## Requisitos

- You have 4+ years of software development experience
- Eager to solve complex engineering problems
- Can lead a project from design stage to release
- Can find balance between shipping things fast and maintaining right level of quality
- Cares about the end-user experience and value product delivers
- Have experience with React, Typescript
- Know how to build really smooth animation
- Can choose between REST and GraphQL in different cases
- Tried to setup webpack from scratch
- Have excellent communication skills
- Would be a plus, if you build SSR apps with Next.js

## Benefícios

- Competitive salary and employee stock options
- Flexibility to work from any of our current and future operating markets ✈️
- Health insurance
- Unlimited vacation policy - work hard and take time off when you need it
- The opportunity to create foundational impact that will shape the future of our business as we grow into new countries and cities

## Contratação

PJ a combinar

## Como se candidatar

If this sounds like you, reach out to andrii@nomadhomes.co with your resume, and a note on why you think this is the role for you.

## Tempo médio de feedbacks

Usually 3 days.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by gfrancischelli** [comment]
Podemos tirar a label `São Paulo` e adicionar `React` e `GraphQL` ? :blue_heart:

**Comment by gfrancischelli** [comment]
We are still hiring!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
