### ISSUE TITLE
[Remoto - Brasil] Front-end Developer @ WhatsGood

### ISSUE THREAD

**Issue by alcferreira** [frontendbr/vagas#5735]
## Nossa empresa

Fundada em 2014, WhatsGood é um marketplace que fortalece a economia local conectando diversos produtores de uma região diretamente aos clientes; nos EUA o WhatsGood está disponível em diversos estados e processa milhares de pedidos para delivery ou pickup toda semana; no Brazil está disponível em Ribeirão Preto - SP no momento

## Descrição da vaga

Trabalhando em nosso time como Frontend Developer, você trabalhará num ambiente ágil, arquitetando e desenvolvendo nosso webapp de maneira escalável, segura e performática.

Você vai escrever código, abrir e revisar pull requests diariamente, abrir e analisar tasks de novas features, cuidar da entrega ponta a ponta sempre tendo em vista qualidade e escalabilidade.

Esperamos, ainda, que você consiga ter um bom equilíbrio entre vida pessoal e trabalho; nós desencorajamos horas extra e expediente de fim de semana para que você consiga ter tempo de qualidade com sua família

## Local

Exemplo: Remoto

## Requisitos
- 4 anos trabalhando com desenvolvimento de software
- Boa experiência com desenvolvimento frontend, idealmente com single-page applications e microfrontends
- Conceitos sólidos de vanilla JavaScript
- Experiência com todo o ecossistema React
- Familiaridade com sistemas legados e suas arquiteturas
- Ter colaborado em um ambiente focado em qualidade onde teste e review são parte do dia-a-dia
- Escrita de html semântico e familiaridade com boas práticas de acessibilidade web
- Ter trabalhado em times distribuídos é um bônus

**Diferenciais:**
- Ter proficiência na sua área de atuação e mesmo assim topar desafios fora da sua área de atuação
- Colaborar com os pares e em múltiplas áreas
- Ver um feedback como uma oportunidade de reflexão e melhoria
- Estar sempre aprendendo e melhorando suas capacidades tanto técnicas quanto de liderança
- Não conseguir trabalhar com ambiguidade e questionar todos os pontos que precisam de clareza
- Não ter medo de falhar e pedir ajuda para resolver algum problema

## Benefícios
- 20 dias úteis de descanso remunerados por ano
- 5 dias de licença médica remunerados por ano
- Plano de carreira claramente definido e validado onde você terá a oportunidade de desenvolver suas habilidades, além de feedbacks constantes e 1-1s temos reviews semestrais para acompanhamento do plano de carreira - é nesse momento que você tem a chance de ter sua primeira promoção
- Ajuste anual pela inflação (índice IPCA)
- Macbook Pro
- R$2500 para compra de equipamentos de ergonomia para seu escritório
- Acréscimo no valor hora baseado no tempo de contrato a partir do primeiro ano podendo chegar a até 20%

## Contratação
PJ

## Como se candidatar

Se aplique pelo [workable](https://apply.workable.com/whatsgood/j/C5263D6FFC/)

## Tempo médio de feedbacks
Nosso processo seletivo conta com 3 entrevistas e pode durar até 2 semanas

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
