### ISSUE TITLE
[ São Paulo] NodeJS Developer -BeeTech

### ISSUE THREAD

**Issue by alexkawaharadatech** [frontendbr/vagas#574]
Descrição da vaga

Estamos em busca de desenvolvedores que, assim como a gente, tenha um perfil ousado e empreendedor: gente ligada em tecnologia, com brilho nos olhos, que goste de evoluir com novas experiências, e principalmente, queira construir produtos e soluções incríveis. 

Para isso temos um nível de exigência alto com qualidade e buscamos um desenvolvedor que tenha atenção aos mínimos detalhes, tenha uma boa base em orientação a objetos, design patterns e principalmente que se preocupa em criar código legível e escalável

Local

Escritório- São Paulo - Pinheiros ( Próximo a Praça Benedito Calixto )

...
Diferenciais

- Ambiente colaborativo e super informal
- Se estiver com problemas de logística de animais, traga para cá, todos são bem vindo aqui!
- Curte cerveja? Temos aqui também!

...
Requisitos

Obrigatórios:

Criar novas APIs seguindo o padrão restful em Node.js
Ser capaz de propor soluções usando banco de dados relacional (PostgreSQL, MySQL, Oracle) e não relacional (MongoDB, MariaDB, DynamoDB)
Escrever testes unitários e de integração
Manter e evoluir a arquitetura dos projetos de backend

Difrerenciais

Experiência em ambiente AWS (EC2, LoadBalancer, VPC)
Experiência com cache (memcache, redis…)
Experiência com sistemas de alta disponibilidade
Ter trabalhado em projetos com a abordagem de micro serviços
Serverless

Contratação

PJ a combinar

Nossa empresa

A BeeTech quer mudar o mercado financeiro usando tecnologia. Nossa missão é simplificar processos, aproximar distâncias e facilitar a relação de todas as pessoas com a troca de moedas e transferências internacionais. Queremos encurtar as distâncias entre o mundo e nossos clientes.

Como se candidatar

Se você gostou da descrição acima, se identificou com o perfil da vaga e busca desafios que te deem a oportunidade de crescer muito, e muito rápido, envie seu currículo e um breve parágrafo contando o porquê você é o candidato ideal para a vaga. Buscamos pessoas que não se conformam facilmente, que acreditam em processos escaláveis e estejam confortáveis com um ambiente em que o crescimento é completamente baseado na sua evolução no trabalho. Vem pra Bee! #GoBee

Sugestão de assunto para o email: 
Vaga: FrontEnd Engineer | [nome do candidato]
Currículo para: 
vagas@beetech.global

**Comment by vinyguedess** [comment]
Aceita remoto ?

**Comment by alexkawaharadatech** [comment]
Oi Vinicius, tudo bem? 

Para essa vaga é importante para nós o profissional estar presente. Estamos num momento onde a comunicação e a interação do time é super importante e também do profissional ambientar a nossa cultura.

Qualquer dúvida, estou a disposição.

**Comment by vinyguedess** [comment]
@alexkawaharadatech Obrigado

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
