### ISSUE TITLE
[Remoto - Brasil] Front-end Developer na Globo (Globoplay)

### ISSUE THREAD

**Issue by rafaelrmagalhaes** [frontendbr/vagas#5741]
> Vaga Remota durante a pandemia

## Nossa empresa

O Hub Digital faz parte da nossa área de Estratégia e Tecnologia, tendo papel de destaque na nossa transformação em uma empresa de tecnologia de mídia e D2C. Aqui cuidamos da gestão de dados e do desenvolvimento dos nossos produtos digitais, visando a melhor experiência de consumo, interação e relacionamento com os nossos usuários. Trabalhamos com uma variedade de tecnologias e linguagens para atingir nossos objetivos, além de estabelecermos uma relação contínua e crescente de compartilhamento de soluções com a comunidade de tecnologia.

Buscamos o novo e o diferente. Queremos a dúvida, a tentativa, o debate. Quando erramos, aprendemos com nossos erros e compartilhamos nosso aprendizado.

O real aprendizado acontece quando conhecemos novas ideias, novas pessoas, novas tecnologias. Estar aberto ao outro e à diversidade é fundamental para a criatividade, para a tomada de decisões, para o crescimento. Na Globo, estimulamos a diversidade de pensamento e de representatividade. Todas as pessoas são bem-vindas nos nossos processos e nos nossos times.

## Descrição da vaga

Você fará parte da equipe de desenvolvimento do SDK para plataformas nativas do Globoplay, atuando na implementação de novas features e evolução do código já existente. Será responsável por estimar prazos para execução das tarefas e deverá contribuir para melhoria do time como um todo.

Procuramos alguém que goste de desafios e que queira fazer parte de um projeto de inovação, desenvolvendo novas tecnologias. Esperamos que goste muito de aprender, e de compartilhar o conhecimento. Que preze por qualidade nas entregas e consiga estabelecer uma comunicação ativa e saudável com a equipe.

## Local

Remoto ou se preferir pós pandemia, Rio de Janeiro.

## Requisitos

**Obrigatórios:**
- Conhecimento sólido do funcionamento do React
- Conhecimentos sólidos em HTML, CSS e JS Vanilla
- Experiência com fluxos de desenvolvimento como git-flow e code-review

**Desejáveis:**
- Experiência com testes automatizados (unitário, integração e e2e)
- Conhecimento de boas práticas de desenvolvimento (Clean Code, AHA, SOLID)
- Compreensão de arquiteturas para manutenção e escalabilidade do código

**Diferenciais:**
- Conhecimento em Canvas API
- Conhecimento em Webpack
- Experiência com TypeScript
- Conhecimento em melhorias de performance
- Conhecimento sobre React Fiber e Reconciler API
- Experiência desenvolvendo para Smart TV

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ 30/dia

## Contratação

CLT

## Como se candidatar

Acesse https://vempraglobo.recruiterbox.com/jobs/fk0u5v3/ e envie seu currículo. Tanto Pleno quanto Senior.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
