### ISSUE TITLE
[Remoto - Brasil] Front-end Developer na Mainô

### ISSUE THREAD

**Issue by fabianoleittes** [frontendbr/vagas#5742]
## [Mainô](https://github.com/mainosistemas)

A Mainô é uma startup que oferece um sistema de gestão em nuvem especializado nas operações de importação, exportação e distribuição de mercadorias, com emissão e monitoramento de notas fiscais, controle de estoque, emissão de boleto e SPED Fiscal.

## Descrição da vaga

Esperamos que em 1 mês você seja capaz de desenvolver o front dos novos microsserviços que estão sendo desenvolvidos em Rails API.
Esperamos que em até 3 meses você seja capaz de dar manutenção pontualmente na interface do sistema legado, além do desenvolvimento de novas interfaces para as novas funcionalidades.
Esperamos que em até 6 meses você seja capaz de refatorar ou extrair telas existentes no monolito, adequando a nova estrutura de microsserviços que está sendo desenvolvida.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência trabalhando com frameworks JS em nível pleno;
- Experiência com frameworks SPA, como ReactJS;
- Escrever um código que tenha orgulho, simples, limpo e eficiente;
- Estar habituado com versionamento de código utilizando Git (preferencialmente com a plataforma do Github);
- Disciplina na cobertura dos testes e entrega de um produto de qualidade;
- Estar habituado com o processo de pull requests/code review;
- Conhecimentos aprofundados de JavaScript, incluindo aspectos de desempenho e segurança;

**Desejáveis:**
- Ter noções de Design Patterns;
- Experiência e conhecimento em Ruby on Rails;
- Conhecimento em CI/CD;
- Experiência profissional sólida no uso de estruturas de testes unitários com Node.js (por exemplo, Jasmine, Mocha, Jest);
- Capacidade de escrever código estruturado, bem documentado e fácil manutenção;
- Conhecimentos ou experiência em projetos web com GraphQL;
- Coesão das mensagens dos commits;
- Vivência com boas práticas de desenvolvimento, como Clean Architectures, TDD, BDD, DDD;

## Benefícios

- Plano de saúde SulAmérica;
- Seguro de vida;
- VR de R$ R$26,86;
- Auxílio Home Office;
- Ginástica Laboral;
- Crédito consignado da Creditas;
- Cultura: Eventos internos de confraternização;
- Alura cursos Online;

## Contratação

CLT R$6,000.00 - R$8,200.00

## Como se candidatar

Curtiu? Nós também queremos te conhecer!!! Por favor envie um email para processoseletivo@maino.com.br, com seu CV anexado e LinkedIn profile - enviar no assunto: Nome do candidat@ + Vaga Front-End

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
