### ISSUE TITLE
[Remoto] Developer Front-End React.js | Ambizzion IT.

### ISSUE THREAD

**Issue by NicolasDurazzo** [frontendbr/vagas#5743]
## Ambizzion IT

É uma empresa provedora de serviços e soluções integradas de sistemas, alinhadas com as principais estratégias corporativas através de uma equipe altamente qualificada. Nossa experiência e comprometimento traduzem o alto nível de satisfação e reconhecimento dos nossos clientes.

## Descrição da vaga

Front-end React.js Developer PJ/CLT

## Local

100% Remoto - Home Office.

## Requisitos

**Obrigatórios:**
- 3+ anos de experiência trabalhando com práticas ágeis de
desenvolvimento de software;
- Conhecimento de boas práticas como Clean Code e Design
Patterns;
- Experiência com React.js + Typescript;
- Familiaridade com construção de arquitetura de software;
- Familiaridade com infraestrutura, deployment e servidores;

**Atividades e responsabilidades:**
- Ajudar a entender problemas, analisar soluções, desenvolvê-las e testá-las;
- Mentorear outros desenvolvedores através de revisão de código e pair
- Implementar novas funcionalidades e corrigir bugs;
- Ser independente e proativo, puxando ou refinando tarefas e mantendo o quadro de tarefas organizado;
- Colaborar com gerentes de produto, engenheiros, designers e profissionais de saúde para uma construção iterativa de produtos e serviços;
- Participar das cerimônias de gestão ágil;
- Monitorar o desempenho, disponibilidade, segurança e erros da solução enquanto ela estiver em produção.

## Benefícios

- Vale Refeição
- Vale Alimentação
- Vale Transporte
- Plano de Saúde
- Plano Odontológico
- Academia/Gympass
- Bônus

**Diferenciais:**
- Auxilio Creche/Baba 
- Auxilio Home Office

## Contratação

CLT / PJ

## Como se candidatar

Por favor envie um email para nicolas.durazzo@ambizzion.com.br com seu CV anexado - enviar no assunto: Vaga React.js Github

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 48 horas após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
