### ISSUE TITLE
[Remoto] Frontend Developer (Pleno) na Mainô

### ISSUE THREAD

**Issue by quetlinkober** [frontendbr/vagas#5747]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-developer-pleno-121348790?origin=github&medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>Mainô</strong> está buscando <strong><ins>Frontend Developer </ins></strong>nível pleno para compor sua equipe!</p>
<p>A Mainô é uma startup que oferece um sistema de gestão em nuvem especializado nas operações de importação, exportação e distribuição de mercadorias, com emissão e monitoramento de notas fiscais, controle de estoque, emissão de boleto e SPED Fiscal.</p>
<p>O que esperamos de você:</p>
<ol>
<li>Esperamos que em 1 mês você seja capaz de desenvolver o front dos novos microsserviços que estão sendo desenvolvidos em Rails API.</li>
<li>Esperamos que em até 3 meses você seja capaz de dar manutenção pontualmente na interface do sistema legado, além do desenvolvimento de novas interfaces para as novas funcionalidades.</li>
<li>Esperamos que em até 6 meses você seja capaz de refatorar ou extrair telas existentes no monolito, adequando a nova estrutura de microsserviços que está sendo desenvolvida.</li>
</ol>

## Mainô: 
 <p>A Mainô é uma startup que oferece um sistema de gestão em nuvem especializado nas operações de importação, exportação e distribuição de mercadorias, com emissão e monitoramento de notas fiscais, controle de estoque, emissão de boleto e SPED Fiscal.&nbsp;</p>
<p>Através do nosso sistema de gestão transformamos processos complexos e burocráticos em tarefas <ins>simples e rápidas</ins>. Nossos principais benefícios, detalhadamente, são:&nbsp;</p><a href='https://coodesh.com/empresas/maino'>Veja mais no site</a>

 ## Habilidades: 
 - React.js 
- GIT 
- Javascript 
- Ruby on Rails
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência trabalhando com frameworks JS em nível pleno; 
- Experiência com frameworks SPA, como ReactJS; 
- Escrever um código que tenha orgulho, simples, limpo e eficiente; 
- Estar habituado com versionamento de código utilizando Git (preferencialmente com a plataforma do Github); 
- Disciplina na cobertura dos testes e entrega de um produto de qualidade; 
- Estar habituado com o processo de pull requests/code review; 
- Conhecimentos aprofundados de JavaScript, incluindo aspectos de desempenho e segurança;
## Diferenciais: 
 - Ter noções de Design Patterns; 
- Experiência e conhecimento em Ruby on Rais 
- Conhecimento em CI/CD; 
- Experiência profissional sólida no uso de estruturas de testes unitários com Node.js (por exemplo, Jasmine, Mocha, Jest); 
- Capacidade de escrever código estruturado, bem documentado e fácil manutenção; 
- Conhecimentos ou experiência em projetos web com GraphQL; 
- Coesão das mensagens dos commits; 
-  Vivência com boas práticas de desenvolvimento, como Clean Architectures, TDD, BDD, DDD;
## Benefícios: 
 - Plano de Saúde SulAmérica; 
- Vale refeição: R$26,86; 
- Auxílio Home Office; 
- Ginástica Laboral; 
- Crédito consignado da Creditas.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Developer (Pleno) na Mainô](https://coodesh.com/vagas/frontend-developer-pleno-121348790?origin=github&medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
