### ISSUE TITLE
[Joinville] Front-end Developer na Kstack

### ISSUE THREAD

**Issue by yohanlimapo** [frontendbr/vagas#5748]
## Nossa empresa

A nossa cliente é uma empresa voltada para o segmento de prestação de serviços de Meios de Pagamento para o setor da Indústria e Varejo.

## Descrição da vaga

Desenvolvedor Front-end React.

## Local

Remoto e Escritório, [Santa Catarina], [Joinville]

## Requisitos

**Obrigatórios:**
- 1 ano com React, HTML, CSS

**Desejáveis:**
- Perfil de liderança. Essa pessoa será uma das principais responsáveis pela parte de do front-end da empresa.

**Diferenciais:**
- Mais tempo de experiência em React.

## Benefícios

- VR

**Diferenciais:**
- Cumprir 8h de trabalho, como desejar - exceto de madrugada.
- Após 3-5 meses de treinamento estará na liderança.

## Contratação

CLT ou PJ

## Como se candidatar

Por favor envie um email para yohan.limapo@kstack.com.br com seu CV anexado - enviar no assunto: Vaga React Joinville

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7dias após cada processo.
E-mail para contato em caso de não haver resposta: yohan.limapo@kstack.com.br

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
