### ISSUE TITLE
[São Paulo] Oportunidade para Front-End Developer Sênior com foco em Mobile na ACESSO

### ISSUE THREAD

**Issue by Marksys** [frontendbr/vagas#575]
## Sobre a Empresa
Quantas empresas brasileiras recusariam uma proposta de compra da Google?
Somente uma que tenha propósito forte e profunda crença em seus sonhos. Nós somos essa empresa! Diariamente trabalhando para que os brasileiros andem sem seus documentos físicos.

## O desafio
A [ACESSO ](http://www.acesso.io)está desenvolvendo um novo produto voltado para o consumidor final que tem como objetivo acabar com a burocracia entre pessoas e empresas. Acreditamos que as transações e acordos serão mais simples que pedir um Uber. Estamos procurado um Front-End Developer Sênior que tenha vontade de criar algo de valor. Essa pessoa vai ficar responsável pela criação de todo o front do produto e trabalhará lado a lado com os Designers, ajudando a criar uma experiência incrível para os usuários.

## Requisitos obrigatórios: 
Saber desenvolver:
* HTML, CSS, Javascript
* ReactJS, React-Native
* Sass, Less
* Git e Gitflow
* Angular 2+, Material Design, Bootstrap
* Experiência com API’s

## Sobre a vaga: 
Regime de contratação: CLT
Remuneração: Competitiva com o mercado
Horário de Trabalho: De segunda a sexta-feira, horário comercial (mas somos flexíveis!)
Local de trabalho: Brooklin Novo, Zona Sul de São Paulo - próximo à Avenida Berrini.

## Benefícios: 
Vale alimentação
Vale Refeição
Seguro de Vida
Assistência Médica
Assistência Odontológica
Vale Transporte ou Estacionamento

## Diferenciais
Autonomia para desenvolver
Horário Flexível
Ambiente Descontraído
Happy Hour na empresa
Geladeira com cerveja todos os dias
Video Game e Mesa de Ping e Pong

## Como se candidatar
Enviar currículo para bruno.freitas@acesso.io
Cel: 11 942071967

www.acesso.io
www.acesso.io/talentos

**Comment by vinyguedess** [comment]
Aceita remoto ?

**Comment by Marksys** [comment]
vinyguedess a vaga é presencial, apesar de fazermos alguns dias Home Office.

Abraço

**Comment by michelribeiro** [comment]
Parabéns pela vaga, o brasil precisa de escopo de empresa como há de vocês! Espero muito sucesso e uma boa contratação!

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
