### ISSUE TITLE
[São Paulo] Dev Front-End (Angular) na [TOTVS]

### ISSUE THREAD

**Issue by diegosdomingos** [frontendbr/vagas#5750]
A TOTVS está buscando desenvolvedores front end para atuar com Angular.

Os interessados devem se candidatar no link da vaga: [https://totvs.gupy.io/jobs/1060244](url)

**Os detalhes da vaga estão no link.**

> Vaga Remota durante a pandemia

## Empresa
TOTVS 

## Descrição da vaga
Desenvolvimento de rotinas (front end) em Angular, utilizando PO-UI (Biblioteca de componentes da TOTVS) e testes unitários em Jasmine.

## Local
O trabalho é remoto durante a pandemia.
A empresa está estudando modelo híbrido após a liberação de volta aos escritórios.
O escritório de atuação fica na Zona Norte de São Paulo, bairro de Santana.

São Paulo - SP, Bairro: Santana

## Requisitos
Mais detalhes no link: [https://totvs.gupy.io/jobs/1060244](url)

## Benefícios
Mais detalhes no link: [https://totvs.gupy.io/jobs/1060244](url)

## Contratação
CLT + Benefícios

## Como se candidatar

Se increva no link da vaga: [https://totvs.gupy.io/jobs/1060244](url)

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
