### ISSUE TITLE
[Remoto] Senior Front-end Developer (React) @ Motrix

### ISSUE THREAD

**Issue by tregismoreira** [frontendbr/vagas#5751]
## Apresentação

Estamos buscando uma pessoa desenvolvedora front-end com muita experiência em React para nos ajudar a construir produtos digitais de alto impacto e escala global voltados à educação na era pós-COVID.

## Você vai se dar bem se

- Tem paixão por entregar soluções de alta qualidade;
- Tem auto-motivação e capacidade de trabalhar de forma autônoma em um time diverso e distribuído;
- Sabe se comunicar de forma clara e objetiva em Português e Inglês;
- Valoriza mais os itens à esquerda do [Manifesto Ágil](https://agilemanifesto.org/) do que os da direita;
- Busca compreender as reais motivações de uma tarefa antes de executá-la;
- Tem uma mentalidade LEAN e está constantemente procurando cortar desperdícios;
- Tem iniciativa e proatividade; Busca não ser apenas um(a) "escrevedor(a) de código";
- Consegue comunicar de forma clara as decisões complexas de arquitetura;
- Gosta de trabalhar em equipe e busca sempre contribuir para a melhoria de todo o time;
- É capaz de discutir de forma construtiva sobre soluções, abordagens ou tecnologias mesmo que não concorde com elas de primeira.

## Você precisa ter

- Pelo menos 5 anos de experiência comprovada com desenvolvimento de aplicações web;
- Pelo menos 2 anos de experiência prática diária com React;
- Sólidos conhecimentos em JavaScript, TypeScript, ES6+;
- Experiência trabalhando com APIs REST e GraphQL;
- Domínio de alguma biblioteca para gerenciamento de estado global da aplicação (Redux, MobX etc);
- Experiência com APIs REST e GraphQL;
- Capacidade de explicar a diferença entre SSR (server-side rendering) e SSG (static site generation);
- Trabalhado com algum framework React como Gatsby ou Next.

## É muito interessante que você

- Tenha experiência com bibliotecas de testes em Javascript (Jest, Mocha etc);
- Tenha experiência com AWS Amplify ou Firebase;
- Tenha um olhar para Design e saiba usar Figma, Sketch, Adobe XD ou similar;
- Tenha capacidade de "se virar" escrevendo código backend (Node.js, Python) quando necessário;
- Tenha empatia e um carinho especial com os usuários das aplicações que você estiver trabalhando;
- Tenha muita atenção aos detalhes e lembre-se de incluir a palavra "bazinga" no email de aplicação à vaga;
- Já tenha contribuído com front-end em algum projeto open-source (código, plugin, componente etc);
- Já tenha trabalhado em uma Startup SaaS.

## Oferecemos

- Salário de 9 a 18 mil reais de acordo com a experiência;
- Trabalho remoto - trabalhe de qualquer lugar;
- Autonomia, responsabilidade, flexibilidade;
- Ambiente de trabalho de startup (estrutura horizontal com muita colaboração entre todas as áreas);
- **A oportunidade de contribuir para a transformação da educação no Brasil e no mundo, juntamente com uma equipe de ponta com muita experiência em educação e tecnologia**.

## Forma de contratação

A combinar.

## Como se candidatar

Envie um email para jobs@motrix.global com:
- Assunto: **Senior React Developer**;
- Seu CV anexado e/ou LinkedIn;
- Link para seus perfis no Github e StackOverflow.

#### Alocação
- Fulltime
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Sênior
- Especialista

**Comment by tregismoreira** [comment]
A vaga ainda está disponível ;)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
