### ISSUE TITLE
[Remoto][Node][React] FullStack Developer na Gupy

### ISSUE THREAD

**Issue by AdeSegundo** [frontendbr/vagas#5754]
### **FullStack Developer na Gupy**

**Inscreva-se em https://bit.ly/3u7Nmmd**

A **Gupy** é uma startup fundada por profissionais de RH e de Tecnologia, com o objetivo de **transformar a maneira como são feitos processos seletivos no Brasil**, responsável por desenvolver a primeira inteligência artificial para recrutamento e seleção do país, para que empresas encontrem rapidamente os candidatos que têm maior afinidade com suas vagas.

**FICHA TÉCNICA**
Cargo: **Desenvolvedor(a) Full Stack**
Nível: **Sênior**
Modelo de contratação: **CLT**
Local de trabalho: **Remoto**

**REQUISITOS**
📌Experiência como pessoa desenvolvedora de software;
📌Bom conhecimento em testes unitários / funcionais / integração;
📌Hábito de aplicar boas práticas de engenharia de software, como clean code, orientação a objetos, TDD, CI/CD
📌Hábito de fazer refatoração no dia a dia;

**BENEFÍCIOS**
🍽 Vale Refeição
🏥 Assistência Médica e Odontológica
🏋️‍♂️ Gympass
🏡 Política de Home Office
👶Licença maternidade e paternidade estendida
🧾 Auxílio Escritório Remoto
🧘‍♀️ Zenklub

**Saiba mais em https://bit.ly/3u7Nmmd**

Não se identificou com a vaga?
Cadastre-se no nosso Banco de Talentos "Dream Job" e informe qual tipo de desafio que procura: https://byintera.in/3-f

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
