### ISSUE TITLE
[Curitiba] Front-end Developer na Houseasy

### ISSUE THREAD

**Issue by HouseasyRH** [frontendbr/vagas#5755]
## Nossa empresa

A Houseasy é uma startup de tecnologia residencial, no segmento de IoT. Temos como missão atuar de maneira ampla e acelerada na geração de conforto à população em geral, otimizando tarefas, reduzindo custos e democratizando o acesso a automação para o lar. Realizando isso de forma simples, prática e eficaz. 

## Descrição da vaga

Buscamos pessoas que... 

São conectadas com a transformação digital, pacientes, que gostam de compartilhar e aprender novas tecnologias. Bem como, ter match cultural com os nossos Easiers, respeitando as diferenças, trabalhando de forma centrada e colaborativa. 

 
 
O que vou fazer? 

- Implementar e manter telas do aplicativo desenvolvidas utilizando o framework Flutter; 

- Atuar junto ao time de tecnologia de forma ágil, solucionando problemas. 

 

Principais responsabilidades: 

- Implementar telas funcionais e sem erros para o aplicativo mobile, entendendo as dores do cliente e os objetivos de negócios que gerem valor. 

## Local

-Remoto
-Escritório [Paraná], [Curitiba], [Centro Cívico]

## Requisitos

**Obrigatórios:**
- Cursando ou formado em áreas relacionadas à tecnologia. 
- Conhecimento avançado em Lógica de Programação; 
- Conhecimento avançado em Orientação à Objetos; 
- Conhecimento no framework Flutter; 
- Conhecimentos avançados em HTML, CSS, GIT, Firebase e Javascript; 
- API Rest (habilidades com Insomnia e Postman); 
- Conhecimento em gerenciamento de estados; 
- Experiência em desenvolvimento de aplicações web. 

**Diferenciais:**
- Ter atuado com metodologias ágeis. 

## Benefícios

Alura Cursos Online 
Plano Odontológico Dentaluni 
Plano Médico Unimed 
Seguro De Vida Itaú 
Frutas Fresquinhas 
Coffee Mensal Temático 
Ginástica Laboral 
Ambiente Acolhedor E Divertido 
Horário Semi Flexível 
Kit Boas Vindas 

## Contratação

CLT

## Como se candidatar

Interessados deverão encaminhar o currículo para rh@houseasy.net até o dia 15/10/21 e no título do e-mail inserir o nome da vaga.

Para que possa conhecer mais a respeito da Houseasy e da energia do time #toeasy, segue abaixo link que traz como é o nosso dia a dia aqui, nossa cultura, valores e ações internas <a href="https://site.houseasy.net/trabalhe-conosco/">aqui</a>.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
