### ISSUE TITLE
[Remoto][React][Next.js] Front-end/Full-stack Developer na Yo! Inglês (startup nascente)

### ISSUE THREAD

**Issue by th1menes** [frontendbr/vagas#5756]
## Yooooo! é você nossa nova parceria?

![Yo! Inglês — template anúncio de vaga_front-end e full-stack - 04_set21](https://user-images.githubusercontent.com/84396578/134593035-a5fbefd3-c67a-4c70-a649-1108c8c81952.png)

topa colaborar com a gente, ou ainda entrar pro time de vez e integrar a sociedade futuramente? 😁
 
a Yo! Inglês é uma startup sergipano-baiana nascente, de tecnologia educacional. nossa grande parada é contribuir pra difusão da comunicação em inglês no Brasil. a gente quer botar esse povo pra falar pelos cotovelos! 🤩

somos um projeto bootstrapping (sem investimento), com uma equipe super reduzida, o que significa muita ralação, comprometimento e aprendizado, então precisamos de alguém que queira colaborar pra fazer acontecer. se você também tiver ambição e visão de negócio, é um grande diferencial pra gente. nunca sabemos como essa relação poderá evoluir... mas queremos que evolua.

## Descrição da vaga

pra nos ajudar com a criação e viabilização da nossa estrutura, estamos em busca de uma pessoa desenvolvedora que faz frontend, pra desenvolver o website/plataforma e integrar com a API backend, bem como se encarregar de outras funcionalidades front definidas pelo time.

você que é full e quer se candidatar, apesar do foco de execução agora ser a demanda front apenas, esse é um diferencial pra nós, porque precisamos de alguém pra assumir o back daqui a um tempo. além disso, precisamos também de alguém capaz e que queira tomar conta da área de desenvolvimento da empresa e, idealmente, formar nossa futura equipe. esperamos que a pessoa que entre agora no projeto (front ou full), nessa fase inicial, possa ocupar essa posição mais à frente e, com tudo alinhado, comece a caminhar pra uma possível entrada na sociedade do negócio. legal, né? mas, por ora, mantenha em mente que, independente se full ou front, você será contratado(a) exclusivamente pra executar nossas demandas front atuais. todo o resto será discutido e negociado mais adiante.

quanto à senioridade, estamos construindo o alicerce e esquentando os motores ainda, então precisamos de experiência de execução. buscamos dev de nível pleno ou sênior pra dar conta de nossas demandas atuais.

## Requisitos

frontend:

**Obrigatórios:**
- CSS, HTML
- Javascript
- TypeScript
- React
- Next.js	                                           
- versionamento com Git
- testes automatizados

**Desejáveis:**
- WebSocket (importante)
- WebRTC (importante)
- consumo de APIs GraphQL (Apollo ou Relay)                                    
- styled-components

**Diferenciais:**
- Amazon AWS
- Adobe XD/Figma
- arquivos SVG (escalonamento/responsividade) (importante)
- ux/ui (importante)
- efeitos e animações (versões de parallax, entre outros)

backend (pra você que é full e quer assumir nossas demandas back mais à frente):

**Obrigatórios:**
- JavaScript
- TypeScript                                        
- criação de APIs RESTful/GraphQL 	                  
- Node.js                                 
- GraphQL (Apollo Server/Express GraphQL) (GraphQL.js/GraphQL JIT) 
- práticas de gestão de projeto SOLID e Clean Code
- testes automatizados   

**Desejáveis:**
- WebSocket (importante)
- WebRTC (importante)
- Redis                                                 
- PostgreSQL	

**Diferenciais:**
- DevOps (CI/CD, AWS, Kubernetes, Monitoramento)

## Contratação

nossa proposta consiste em

- contrato inicial de 3 meses (provável e desejável extensão)
- 100% remoto
- em regime PJ
- com oferta inicial mínima de 8.500,00 (mínimo de 120/h mês; trabalhou mais, ganhou mais)

se você tem nível pleno ou sênior com experiência comprovada, bota pra quebrar de verdade no desenvolvimento, domina nossa stack, se interessou pela proposta, se adequa ao perfil que buscamos e quer contrapropor a oferta de remuneração, estamos super abertos a isso. só venha!  🤑

## Como se candidatar

pra saber um pouco mais e se candidatar, acesse e preencha https://forms.office.com/r/EBygDBrhny, e não esqueça de enviar seu currículo pra vagas@yoingles.com. qualquer coisa, envie um yo pra esse mesmo endereço e responderemos logo, logo. 

peace and success! 😎

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
