### ISSUE TITLE
[Remoto] Front-end  Developer (Sênior) na ConsuTI 

### ISSUE THREAD

**Issue by quetlinkober** [frontendbr/vagas#5757]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-senior-183418417?origin=github&medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A ConsuTI está buscando <strong><ins>Frontend Developer</ins></strong> nível sênior!</p>
<p><strong><em>Já pensou em trabalhar somente 4 dias na semana? </em></strong>No ConsuTI você pode,  trabalho 4x por semana (segunda à quinta) com a remuneração de mercado mantida, não será reduzida proporcional às horas.</p>
<p>Somos uma software house que busca transformar sonhos em realidade por meio da tecnologia. Afinal, acreditamos que a inovação tecnológica inspira a evolução.</p>
<p>Aqui valorizamos a diversidade e inclusão, acreditamos que um time diverso é capaz de gerar mais valor e ser resiliente, por isso, nossas vagas estão abertas para todas as pessoas.</p>
<p></p>
<p>Se identificou? Bora se candidatar e fazer parte do nosso Time!</p>
<p>📌Pra gente dar match, buscamos pessoas que:</p>
<ul>
<li>Apoie boas práticas de programação, como escrever código limpo e reusável usando práticas como TDD, princípios SOLID, design orientado a objetos e programação pareada;</li>
<li>Sugerir novas tecnologias e processos;</li>
<li>Levantar requisitos para novas implementações, avaliando o impacto nas funcionalidades já existentes;</li>
<li>Tomar decisões de maneira autônoma e de se comunicar com nossos clientes traduzindo suas necessidades e problemas;</li>
<li>Executar a manutenção dos sistemas, fazendo eventuais correções, visando melhorar a performance dos usuários;</li>
<li>Assumir a propriedade e a responsabilidade além das entregas individuais, sempre indo além para entregar resultados incríveis para nossos clientes;</li>
<li>Disseminar conhecimentos técnicos, tornando-se um multiplicador das inovações.</li>
</ul>

## ConsuTI : 
 <p>A ConsuTI é uma software house que busca transformar sonhos em realidade por meio da tecnologia. </p><p>Afinal, acreditamos que a inovação tecnológica inspira a evolução.</p><a href='https://coodesh.com/empresas/consuti'>Veja mais no site</a>

 ## Habilidades: 
 - React.js 
- Vue.js 
- Angular.js 
- GIT
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência nas linguagens de desenvolvimento (JS 6+, React, Vue, Angular, Junit, Mockito, GIT.); 
- Experiência e/ou interesse em trabalhar com ágil, Entrega Contínua e Integração Contínua (CI/CD), TDD e Infraestrutura como código; 
- Aptidão para escrever código limpo e de alta qualidade em uma variedade de linguagens e também é capaz de reconhecer (e melhorar) um código ruim; 
- Apaixonado por promover inovações e por desenvolver; 
- Tenha um bom pensamento lógico e muita vontade de aprender e crescer.
## Diferenciais: 
 - Metodologias Ágeis: Lean, Kanban, SCRUM; 
- Conhecimento em testes unitários; 
- Conhecimento em DevOps; 
- Conhecimento de tecnologia de nuvem, como AWS, Docker e Kubernetes será um diferencial;
## Benefícios: 
 - Trabalhe 4 dias na semana. (segunda-feira à sexta-feira) 
- 100% teletrabalho + no dress code 
- Horário flexível (salvando as reuniões pré-agendadas) 
- Vale-refeição dinâmico (R$22,70 por dia trabalhado) 
- Ajuda de custo mensal para teletrabalho (R$100,00 por mês) 
- Prêmios por resultados 
- Participação nos lucros 
- Plano de saúde (cooparticipativo) 
- Plano odontológico (cooparticipativo) 
- Day-Off aniversariante (no mês de aniversário) 
- Subsídio para cursos, treinamentos e certificações 
- Plano de cargos e salários dinâmico pela evolução no trabalho (feedbacks de 6 em 6 meses) 
- Acesso aos mentores, padrinhos/madrinhas e consultores nas áreas a serem desenvolvidas 
- Participação nos programas e eventos do ecossistema de empreendedorismo e inovação 
- Ambiente dinâmico, colaborativo e desafiador 
- Promoção do bem-estar 
- Tempo para criar 
- Pagamento de transporte (se necessário)
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Front-end  Developer (Sênior) na ConsuTI ](https://coodesh.com/vagas/frontend-senior-183418417?origin=github&medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
