### ISSUE TITLE
[São Paulo] Front-end Developer na Appnovation

### ISSUE THREAD

**Issue by andraderafaela** [frontendbr/vagas#5758]
> Vaga Remota durante a pandemia

## Nossa empresa

Somos uma empresa Global com sede no Canadá, Brasil, EUA, Ásia, Europa, etc. Oferecemos grande diversidade cultural nos projetos. A tecnologia é fundamental para todas as ofertas da Appnovation, desde consultoria até inovação digital de produtos e serviços. Temos como principais clientes: Pfizer, MetLife, Disney, Fox, Reebok, Johnson & Johnson, American Express, Samsung, Intel, etc...

## **Descrição da vaga**

- Construir relacionamentos e se tornar um consultor confiável para clientes e negócios da Appnovation;
- Fazer parceria com outras equipes para definição de proposta e entregas inovadoras ao cliente de classe mundial.
- Educar os membros da equipe por meio de treinamento e suporte individual.

## Local

Remoto durante a pandemia. Retorno ao escritório no modelo híbrido a partir de Março/22. Escritório, São Paulo, São Paulo, Centro.

## Requisitos

**Obrigatórios:**
- Experiência em desenvolvimento de interface de usuário móvel e / ou web, desenvolvendo em várias plataformas e entrega de projetos como parte de uma equipe
- Forte conhecimento de HTML5 e CSS3, design responsivo, flexbox, SCSS ou LESS;
- Experiência em trabalhar com framework PHP - Laravel;
-  Experiência de trabalho com microarquitetura, APIs SOAP e REST;
- Experiência em trabalhar com metodologias de entrega

**Desejáveis:**
- PWA, Service Workers, Webpack.

## **Benefícios**
- VR R$30 (por dia útil)
- VT
- Seguro de vida
- Plano de saúde
- Plano odontológico

## **Contratação**

CLT a combinar

## **Como se candidatar**

Por favor se cadastre na plataforma The Bonding: https://app.thebonding.cl/es/JobsBrasil/Login.

Nome da Vaga: Front End Developer 
Appnovation Brazil

_Como se cadastrar:_
1. Crie um usuário com seu e-mail e senha.
2. Procure a posição Front End Developer
3. Responda aos 4 blocos de perguntas.
4. Anexe seu currículo e clique no botão "Finalizar"

Ao final, você verá uma mensagem confirmando sua inscrição.

Se você tiver alguma dúvida ou problema, entre em contato: rafaelaandrade@the-bonding.com

## **Tempo médio de feedbacks**

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: rafaelaandrade@the-bonding.com

#### **Regime**
- CLT

#### **Nível**
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
