### ISSUE TITLE
[São Leopoldo e Porto Alegre/RS] Front-End Developer na CWI Software

### ISSUE THREAD

**Issue by alereisdoerfer** [frontendbr/vagas#576]
## Descrição da vaga

Desenvolver aplicações para diferentes áreas atendendo cliente de grande porte.

## Local

São Leopoldo/RS; Tecnosinos; Sede da empresa.

## Benefícios

- Plano de saúde;
- Seguro de vida;
- VT;
- VR;
- Apoio educação;
- Apoio certificação;
- Benefícios flexíveis.

#### Diferenciais

- Possibilidade de trabalhar com as mais diversas tecnologias;
- Nossos times são compostos por profissionais de alta performance, referência na área. 

## Requisitos

**Obrigatórios:**
- Experiência com AngularJS;
- Necessário conhecimento avançado em HTML5, CSS3 e Sass;
- Conhecimento de TypeScript, Angular e BootStrap;
- Conhecimento de Bower, NPM e Gulp;
- Prática de desenvolvimento de Layouts Responsivos;
- Conhecimento dos padrões Web (W3C);

**Desejáveis:**
- Integrações entre sistemas via API (REST e WEBSERVICE);
- Desenvolvimento cross-browser;
- SEO (Otimizações para mecanismos de busca).

**Diferenciais:**
- Conhecimento de Java e Spring.

## Contratação

CLT

## Nossa empresa

Desenvolvemos soluções e sistemas de TI com base nas necessidades específicas de empresas de médio a grande porte em âmbito global, desde 1991.

Possuímos o selo CMMI nível 3 e temos como missão produzir soluções que contribuam decisivamente para o sucesso de nossos clientes.

Com o slogan "O software que você procura talvez não exista, mas a empresa que irá fabricá-lo sim”, buscamos excelência em oferecer serviços como Fábrica de Software, Fábrica de Projetos, Fábrica de Testes e Outsourcing.

## Como se candidatar

Por favor envie um e-mail para work@cwi.com.br com seu CV anexado - enviar no assunto: Vagas Front-End. Você ainda pode cadastrar o currículo através do site https://cwi.com.br/Oportunidades

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
