### ISSUE TITLE
[Remoto] [Vue] Front-end Developer na Dacxi

### ISSUE THREAD

**Issue by Soonas** [frontendbr/vagas#5760]
## Nossa empresa

A [Dacxi](https://dacxi.com/home) é uma empresa que atua no mercado de cripto-economia e tokenização de ativos.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Javascript
- Vue
- Inglês Intermediário;
- Experiência com ferramentas de versionamento de código (GIT,...);

**Desejáveis:**
-  Conhecimento em blockchain e hyperledger;

**Diferenciais:**
- Tailwind

## Benefícios
- Participar do mercado de tecnologia mais promissor do século: cripto-economia.
- Aulas de inglês.

## Contratação

Contratação PJ:
Pl: 4k - 7k
Sr: +7k

## Como se candidatar

Por favor envie um email para luana@dacxi.com com seu CV anexado - enviar no assunto: [Seu nome] + [Vaga]
Dentro do email favor informar salário pretendido.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: luana@dacxi.com

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by paulrick32** [comment]
Tentei enviar para o email informado, mas retornou com erro:

"Endereço não encontrado
--
A mensagem não foi entregue para luana@dacxi.com.br porque o domínio dacxi.com.br não foi encontrado. Verifique se há erros de digitação ou espaços desnecessários e tente novamente."

Com isso enviei para o email luana@dacxi.com, é esse email ?

Obrigado.

**Comment by Soonas** [comment]
Obrigada
