### ISSUE TITLE
[BRASIL] Front-end Developer  na Code7

### ISSUE THREAD

**Issue by YureHenrique** [frontendbr/vagas#5763]
> Vaga Remota 

## Nossa empresa
Somos uma empresa que visa criar, revolucionar e codificar o futuro de nossos parceiros, proporcionando soluções e melhoria nas interações entre empresas e consumidores. Estamos desenvolvendo algo inovador e queremos grandes talentos fazendo parte desse incrível projeto.

## Descrição da vaga

Front-end Developer PLENO com foco em Angular8

Analisar a viabilidade de demandas apresentadas pelos usuários a serem implementadas nos programas/sistemas existentes;
Participar de reuniões técnicas e com usuários para análise e levantamento de requisitos;
Desenvolver, testar e implantar programas e sistemas customizados;
Providenciar a documentação funcional e técnica dos programas e sistemas customizados;
Pesquisar, analisar, sugerir e contribuir na implementação de novas tecnologias associadas com aplicações corporativas;
Projetar, construir e otimizar interfaces web;
Implementar layouts intuitivos e responsivos utilizando princípios ergonômicos de usabilidade.

## Local
Home Office para TODO o território Nacional

## Requisitos

**Obrigatórios:**
Ensino Superior completo ou cursando (Ciência da Computação, Engenharia da Computação, Sistemas de Informação ou graduação equivalente em TI) com previsão de conclusão para segundo semestre de 2022;
Experiência de no mínimo um ano com desenvolvimento em Angular;
Conhecimento avançado em Angular8, HTML e CSS

**Desejáveis:**
Conhecimento em Saas, Javascript e mongodb.

## Benefícios

- Plano de saúde (pago pela empresa depois de 1 ano)
- Plano Odontológico
- Equipamentos p/ Home Office
- VR ou VA

**Escala:**
- Segunda a Sexta
- Horário Flexível (8h00 até 17h48) com 1 hora de almoço

## Contratação

CLT 
Salário: Trabalharemos com sua pretensão e de acordo com seus conhecimentos.

## Como se candidatar

Por favor envie um email para yure@neoempregosrh.com.br com seu CV anexado - enviar no assunto: Vaga Frontend Angular

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.
E-mail para contato em caso de não haver resposta:  yure@neoempregosrh.com.br 

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
