### ISSUE TITLE
[São Paulo][React] Front-end Developer Pleno na Dasa

### ISSUE THREAD

**Issue by caioorg** [frontendbr/vagas#5769]
## Dasa

Somos mais de 40 marcas de laboratórios, hospitais e centros médicos. Somos uma rede de saúde integrada e completa, nossos serviços estão alinhados para cuidar melhor da saúde de quem está conosco e ser uma opção de confiança para seus investimentos. Temos como marcas: Delboni, Lavosier, Deliberato e etc

## Descrição da vaga

Exemplo: Estamos com um desafio muito legal para atuarmos no desenvolvimentos de sistemas na area da saude que aceleram o atendimento do paciente e garantem a melhor condução do cuidado. Como tecnologia usamos: React com Typescript, Redux, Jest, Material-Ui e Cypress

## Local

Diante essa fase que estamos, a principio será Remoto, porém no futuro entraremos para um modelo híbrido. Nosso escrito fica localizado em São Paulo no Bairro de Pinheiros ao lado da estação.

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com **ReactJS**
- Testes Unitários usando **Jest** (testing-library e testing-library/hooks)
- Testes **E2E** (Cypress)
- Typescript
- Redux
- Material-UI
- Context Api
- React Hooks

**Desejáveis:**
- Conhecimentos em React Native
- Conhecimentos em Micro-Front usando Single-SPA

**Diferenciais:**
- Conhecimento diverso em DevOps

## Contratação

PJ a combinar, podendo haver internalização para CLT

## Como se candidatar

Por favor envie um email para caio.almeida@dasa.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Developer Pleno na Dasa

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.
E-mail para contato em caso de não haver resposta: caio.almeida@dasa.com.br

## Labels

- Remoto
- CLT
- PJ
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
