### ISSUE TITLE
[São Paulo ] Front End Engineer - BeeTech Global

### ISSUE THREAD

**Issue by alexkawaharadatech** [frontendbr/vagas#577]
## Descrição da vaga

Estamos em busca de desenvolvedores que, assim como a gente, tenha um perfil ousado e empreendedor: gente ligada em tecnologia, com brilho nos olhos, que goste de evoluir com novas experiências, e principalmente, queira construir produtos e soluções incríveis. 

Para isso temos um nível de exigência alto com qualidade e buscamos um front-end que tenha atenção aos mínimos detalhes, que se preocupa com o pixel que está no lugar errado, com a animação que não está tão smooth, enfim, que ama o que faz. 

## Local

São Paulo - Pinheiros ( Próximo a praça Benedito Calixto )
- ...

#### Diferenciais

- Oportunidade de estudos e desenvolvimento
- Ambiente colaborativo voltado aos propósitos da empresa
- Não ligamos para vestimentas, desde que você se sinta confortável. 
- Problemas de logística com o seu Pet? Traga para cá! Todos são bem vindos!
- Curte uma cerveja? Vamos tomar umas aqui e trocar idéias!

## Requisitos

**Obrigatórios:**
Trabalhar com o framework React criando novos componentes e integrando com API 
Sólidos conhecimentos em HTML/CSS/JavaScript para a construção de novas telas, sempre com o viés de mobile first.
Criar testes unitários para as novas features
Estar próximo ao time de design auxiliando/direcionando o desenvolvimento de novas features e projetos
Manter e evoluir os projetos da BeeTech
Vivência com metodologias ágeis ( XP, Kanban, Scrum…) 

## Contratação

PJ a combinar

## Nossa empresa

A BeeTech quer mudar o mercado financeiro usando tecnologia. Nossa missão é simplificar processos, aproximar distâncias e facilitar a relação de todas as pessoas com a troca de moedas e transferências internacionais. Queremos encurtar as distâncias entre o mundo e nossos clientes.

## Como se candidatar

Se você gostou da descrição acima, se identificou com o perfil da vaga e busca desafios que te deem a oportunidade de crescer muito, e muito rápido, envie seu currículo e um breve parágrafo contando o porquê você é o candidato ideal para a vaga. Buscamos pessoas que não se conformam facilmente, que acreditam em processos escaláveis e estejam confortáveis com um ambiente em que o crescimento é completamente baseado na sua evolução no trabalho. Vem pra Bee! #GoBee

Sugestão de assunto para o email: 
Vaga: FrontEnd Engineer | [nome do candidato]
Currículo para: 
vagas@beetech.global

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
