### ISSUE TITLE
[REMOTE] Freelancer Front-end Developer at Braintrust (Full-Time or Part-time)

### ISSUE THREAD

**Issue by drdpedroso** [frontendbr/vagas#5770]
## Nossa empresa

Braintrust’s mission is to build the world’s most impactful talent network — one that is user-owned, aligns incentives, and redistributes value to Talent and Organizations.

The platform is crypto-based and has an amazing team and clients.

## Descrição da vaga

The position is to work for one of Braintrust's clients (we have Nike, Twitter, Forbes, Uber and so many more), working Full-Time or Part-time. We're looking for both React, Angular or Vue engineers. We also have positions for Node and other languages.

## Local

Remote

## Requisitos

**Obrigatórios:**
- 3+ years of professional experience with any Front-End framework.
- Can speak good English.

**Desejáveis:**
- Experience with Freelancing is good but not required.

## Benefícios

- Flexible working hours (both Full-Time or Part-Time)

**Diferenciais:**
**- High paying hourly rates (can go up to $150 USD per hour)**
- Change to get BTRST tokens if you engage with our community (https://coinmarketcap.com/pt-br/currencies/braintrust/)

## Contratação

PJ

## Como se candidatar

https://bit.ly/2ZwkHfu

Signup, create your profile, and ask for a profile review (there's a button after you complete the profile)

## Tempo médio de feedbacks

Normally 1-2 weeks

#### Alocação
- Remote

#### Regime
- Freelancer
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by jhefflg** [comment]
Poxa é uma oportunidade muito boa, até me animei, porém não tenho inglês suficiente para comunicação verbal. :/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
