### ISSUE TITLE
[Remoto] Front-end Developer na Start by WGSN

### ISSUE THREAD

**Issue by rubiadias** [frontendbr/vagas#5773]
> Vaga Remota durante a pandemia

## Start by WGSN

Empresa especializada em informações, dados e análises que ajuda as empresas mais ambiciosas do mundo a vencer na economia digital. Nossas informações, insights, conexões, dados e ferramentas digitais resolvem os problemas do cliente em quatro disciplinas principais:
- Projeto de produto através do serviço de previsão de tendências globais
WGSN;
- Marketing por meio de referências globais de excelência e eficácia criativas, Lions e WARC e consultoria estratégica empresa MediaLink;
- Comércio digital via dados, análises e serviços gerenciados das marcas Edge by Ascential, Yimian e Flywheel Digital; e
- Varejo e Serviços financeiros por meio dos principais pagamentos do mundo e do congresso FinTech Money20 / 20, setor de varejo global cúpula, Congresso Mundial de Varejo e Semana do Varejo.
A Ascential também capacita as marcas de produtos de inteligência política, de construção e ambiental DeHavilland, Glenigan e Groundsure - juntos compreendendo o Ambiente Construído; Unidade de negócios de política. 

## Descrição da vaga
Desenvolverá exclusivamente novas features para o nosso sistema utilizando nossa arquitetura.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- JavaScript (Vanilla)
- HTML
- CSS

**Desejáveis:**
- OOP
- Funcional

**Diferenciais:**
-  Conhecer ecossistema do React, Angular e Vue.

**Diferenciais:**
- Horário flexível

## Contratação

PJ a combinar

## Como se candidatar

Por favor acesse o [link](https://forms.gle/KWQ5Ht8WUepY2S8o6) e responda o formulário.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dia após cada processo.
E-mail para contato em caso de não haver resposta: cleber.goncalves@ascential.com

#### Alocação
- Remoto

#### Regime
- Freela

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by Wesleychavesdeveloper** [comment]
que pena.. estou no inicio do REACT

**Comment by carloscmarcelino** [comment]
junior?

**Comment by dev99pedro** [comment]
Bom dia, estou interessado na vaga de front-end. Poderia lhe enviar meu CV?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
