### ISSUE TITLE
[Remoto][Pleno] Front-end Developer Pleno na Ramper

### ISSUE THREAD

**Issue by Fer-Ramper** [frontendbr/vagas#5774]
> Vaga Remota durante a pandemia

## Nossa empresa

A Ramper é uma empresa de Software de B2B, e o nosso objetivo é entregar uma solução digital para impulsionar vendas e potencializar resultados sem perder a humanização. Desde 2017 nós ajudamos milhares de profissionais de vendas a gerar, conectar e engajar mais leads com menos esforço, possibilitando que apliquem energia no que realmente importa. 
Nossa missão é revolucionar a cultura de vendas B2B no Brasil, para isso construímos diariamente uma empresa de pessoas que usa e cria tecnologia para melhorar processos. Nossa plataforma é líder nas categorias "geração de leads" e "pré-vendas" no portal B2B Stack, e recebemos pelo terceiro ano consecutivo o prêmio B2B Awards.
Na Ramper temos uma cultura forte de pessoas que compartilham ideias para criação de soluções inovadoras. Aqui você vai encontrar:
Ambiente descontraído;
No dress code;
Autonomia;
Valorização de Pessoas;
Ambiente diverso e inclusivo;
E bastante espaço para inovação.

### Suas principais responsabilidades serão:
Codar e fazer code review;
Estudar e apresentar soluções novas;
Prezar pela qualidade do código e da entrega é fundamental;
O foco atual é construir novas funcionalidades e produtos, mas precisamos eventualmente dar manutenção no que já temos em produção

## Local

Remoto. 
Escritório fica em [SP], [São Paulo], [Santana]

## Requisitos

**Obrigatórios:**
- AngularJs
- Angular
- Git
- HTML 5
- CSS 3

**Desejáveis:**
- Teste Unitários
- TypeScript
- Metodologias Ágeis
- Cultura de Passagem de Conhecimento
- Saas
- Responsividade

**Diferenciais:**
- Conhecimentos em cloud (preferencialmente AWS)
- Demais tipos de testes (e2e, contrato etc)
- Noções de bancos relacionais
- Noções de bancos não-relacionais
- React e/ou Vue
- Conhecimento sobre SSR, SSG
- Acessibilidade
- Docker
- Git Flow

## Benefícios

- Plano de saúde: Porto Seguro
- Seguro de vida
- VR de R$20,00 por dia
- Auxílio creche
- VT ou Auxílio de R$200,00 para locomoção (após retorno do trabalho híbrido)

**Diferenciais:**
- sala de jogos
- Clima descontraído
- Comunicação transparente
- Espaço para inovação

## Contratação

CLT

## Como se candidatar

Por favor envie um email para fernanda.oliveira@ramper.com.br com seu CV anexado - enviar no assunto: Vaga Frontend Angular

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
