### ISSUE TITLE
[Remoto] ID Verification Specialist @ My Love Stars

### ISSUE THREAD

**Issue by alexandrebodi** [frontendbr/vagas#5775]
## Nossa empresa

Somos uma start-up recentemente incorporada na Califórnia, financiada por grupos de investimento e com um grande potencial de valorização no curto prazo.

## Descrição da vaga

Estamos desenvolvendo uma **PWA** que utiliza **React.js** (e **Chakra UI**) no front-end, Node.js e Firebase (pelo menos, por enquanto) no back-end.

Temos um **requisito crítico** em nossa solução que envolve **verificação do histórico criminal** do usuário durante o cadastro, bem como aferir a **identidade** do mesmo (usando biometria). Tudo isso no **mercado americano**.

Estamos buscando um especialista que já tenha trabalhado com isso e que nos ajude a integrar uma solução – paga – de prateleira.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento web em geral
- Experiência com integração de alguma solução de **verificação de histórico criminal** e de **confirmação de identidade**
- Experiência com Git

**Desejáveis:**
- Experiência com React.js
- Experiência com Firebase (Authentication, Firestore, Storage) e/ou AWS (Amplify, S3)
- Experiência com desenvolvimento de PWAs

## Benefícios

- Remuneração em USD

## Contratação

PJ ou Freelance

## Como se candidatar

Por favor envie um email para abodi@mylovestars.com com a frase "Vaga ID Verification Specialist publicada no GitHub" no campo assunto, seu **CV anexado**, e respondendo às seguintes **perguntas**:
- Nome (e link) da plataforma de verificação de histórico criminal que já integrou: 
- Tempo que estima para integrar a solução acima: 
- Tempo de experiência com desenvolvimento web em geral: 
- Tempo de experiência com Git: 
- Pretensão salarial (em USD): 
- Preferência por contratação (se PJ ou Freelance): 
- Em quanto tempo consegue iniciar: 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 semana após cada processo.

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
