### ISSUE TITLE
[POA/Remoto] Pessoa Desenvolvedora Flutter (Pleno) na Kobe

### ISSUE THREAD

**Issue by raquelallegretti** [frontendbr/vagas#5776]
> Vaga Remota! 😄 

**## Sobre a Kobe** 📱 

Somos uma empresa que cria apps usando tecnologia, design e empatia. Ajudamos empresas a desenhar, construir e lançar produtos digitais. Alguns cases de sucesso são: Tok & Stok, Agibank, Warren, Decathlon & muitos outros!
Para mais info acesse: https://www.kobe.io/cases

**## Responsabilidades** ☑️ 

- Desenvolver aplicações em Flutter dando suporte a todo o ciclo de vida: concepção, design, teste, release e suporte a novas e existentes funcionalidades;
- Analisar, compreender e discutir os requisitos funcionais e técnicos, propondo a melhor abordagem para desenvolvimento e testes;
- Acompanhar entregas específicas com um espírito inovador, melhoria contínua e obsessão por superar as expectativas do cliente.

**## Local** 📍 

Remoto ou Escritório, [RS], [Porto alegre], [MOINHOS DE VENTO]

**## Requisitos** 👍 

**Obrigatórios:**
- Experiência de 2+ anos em desenvolvimento Mobile;
- Desenvolvido anteriormente projetos em Flutter;
- Experiência nas diferentes etapas do ciclo de desenvolvimento de um app.

**Diferenciais:**
- Experiência atuando com times SCRUM;
- Vivência em projetos desenvolvidos em Flutter de grande porte ou com impacto em um número expressivo de usuários.

**## Benefícios** 🚀 

- **Food Voucher:** R$25/dia
- **Your Way Holidays**: 10 dias de recesso de final de ano sem desconto no tempo de férias
- **Health Insurance:** plano de saúde, odontológico e seguro de vida 100% coberto e sem coparticipação
- **Flexible Time:** possibilidade de gerenciar sua agenda com autonomia (e claro, responsabilidade!)
- **Kober Remote Experience**: cultura remote first com atividades de integração periódicas para Kobers
- **Kobe Growth:** Plano de Desenvolvimento Individual (PDI) para cada Kober
- **International Immersion**: cultura internacional com projetos e escritórios fora da BR
- **The Right Tools**: equipamento de alto nível para sua estrutura de trabalho

**## Contratação** ⚖️ 

CLT 

**## Como se candidatar** 👏 

Só se candidatar através do link: https://kobe.gupy.io/jobs/1110614?jobBoardSource=gupy_public_page
Ou enviar um email para: raquel.allegretti@kobe.io com o CV anexado.

**#### Nível** 🏢 
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
