### ISSUE TITLE
[Remot] Front-end Developer @ Kobe

### ISSUE THREAD

**Issue by patriciagueds** [frontendbr/vagas#5777]
## Sobre o desafio 📱
Nessa posição, você terá a oportunidade de fazer parte de um **projeto do maior e-commerce de móveis do Brasil**! 
Você trabalhará com a atualização de um forte produto da empresa, juntamente com um time de especialistas no assunto. 
Além disso, terá autonomia para desenvolver e implementar novas soluções pensando nas necessidade dos usuários e oferecendo a melhor experiência.

## Local 🌎
Remoto

## Benefícios 🚀
- **Food Voucher:** vale-alimentação ou refeição Caju (cartão de bandeira Visa com grande abrangência nacional)
- **Your Way Holidays**: 10 dias de recesso de final de ano sem desconto no tempo de férias
- **Health Insurance:** plano de saúde, odontológico e seguro de vida 100% coberto e sem coparticipação
- **Flexible Time:** possibilidade de gerenciar sua agenda com autonomia (e claro, responsabilidade!)
- **Kober Remote Experience**: cultura remote first com atividades de integração periódicas para Kobers
- **Kobe Growth:** Plano de Desenvolvimento Individual (PDI) para cada Kober
- **International Immersion**: cultura internacional com projetos e escritórios fora da BR
- **The Right Tools**: equipamento de alto nível para sua estrutura de trabalho

## Requisitos 👆
**O desafio vai ser mais natural se você já tiver**
- 2 anos de experiência com framework **React.js** ou **Vue.js**
- Experiência com **HTML5** e **CSS3**
- Conhecimento do processo end to end de desenvolvimento
- Habilidade de comunicação interpessoal
- Ownership e autonomia na tomada de decisões

**Desejáveis:**
- Conhecimento em **PWA** (Progressive Web Apps) e **AMP** (Accelerated Mobile Pages)
- Experiência com **Testes Unitários**
- Experiência com liderança de times de alta performance

## Contratação ⚖️
CLT

## Sobre a Kobe
Somos uma empresa que cria apps usando tecnologia, design e empatia. Ajudamos empresas a desenhar, construir e lançar produtos digitais. Alguns cases de sucesso são: Tok & Stok, Agibank, Warren, Decathlon & muitos outros!
Para mais info acesse: https://www.kobe.io/cases

## Curtiu? 💥
Só se candidatar através do link: https://kobe.gupy.io/jobs/1170987
Ou enviar um email para: patricia.guedes@kobe.io com o CV anexado.

## Labels
- 🏢 Flexível
- 🏢 Remoto
- 👱‍♂️ Pleno
- 👱‍♂️ Senior
- ⚖️ CLT
- 💰 7k-12k

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
