### ISSUE TITLE
[Remoto] Front-end Developer na Nave.rs

### ISSUE THREAD

**Issue by BrunaSouzaPaes** [frontendbr/vagas#5778]
> Vaga Remota 

## Nossa empresa

Trabalhar com a nave.rs significa que você conhece e colabora com as pessoas que realmente fazem o trabalho. Unimos tecnologia e criatividade para criar soluções digitais efetivas que se tornam memoráveis e impactam positivamente a vida das pessoas.

Nossa missão é ajudar empresas a entender antes de agir, a agir com precisão e a lucrar a partir de mudanças.

## Descrição da vaga

A Nave.rs está procurando uma pessoa com perfil de nível júnior a pleno, que tenha experiência na área de desenvolvimento Front-End, com clientes e projetos. Essa experiência pode ser através de frellas ou trabalho empresarial.

Como pessoa desenvolvedora para a área de Front-End, você irá utilizar linguagens como JavaScript e Framework React. Na empresa trabalhamos com a metodologia ágil Scrum, sendo assim, temos cerimonias como planning, weekly e retro. O seu dia a dia irá basear-se nas cerimonias e nos projetos, então procuramos uma pessoa comprometida com sua evolução, tendo ideias inovadoras e pensando fora da caixa.

É importante que você goste de se comunicar e trabalhar em equipe, já que aqui temos um ambiente super colaborativo. Ao mesmo tempo, valorizamos que cada membro do time seja autônomo para gerir suas demandas.

## Local

 Remoto 

## Requisitos

**Obrigatórios:**
- Ter experiência profissional na área de desenvolvimento front-end
- HTML
- CSS
- JavaScript
- Experiência no desenvolvimento de aplicações web utilizando React

**Diferenciais:**
- trabalhar bem em equipe
- ser uma pessoa comunicativa
- gostar de autonomia

## Benefícios

- Assistência Média e Odontológica
- Auxilio Psicológico
- VR / VA de R$ 24,10/dia
- Aulas de Inglês
- Acesso a plataforma de cursos Alura

**Diferenciais:**
- Horário Flexível
- Totalmente home office
- Hierarquia Horizontal
- 2h de estudo por semana

## Contratação

CLT + Benefícios 

## Como se candidatar

Inscreva-se através do link: [link aqui](https://nave-team.gupy.io/job/eyJqb2JJZCI6MTIxNDMyNCwic291cmNlIjoiZ3VweV9wdWJsaWNfcGFnZSJ9?jobBoardSource=gupy_public_page)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

#### Salario
- 1K a 3K

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
