### ISSUE TITLE
[São Paulo] Front End Developer na Udacity

### ISSUE THREAD

**Issue by arturts** [frontendbr/vagas#578]
![udacity](https://user-images.githubusercontent.com/9158970/31155875-cd163aaa-a887-11e7-8a40-a6da4436ded6.png)

## Descrição da vaga

Procuramos pessoas com experiência em desenvolvimento front end que queiram fazer parte de uma empresa cuja missão é democratizar a educação!

## Local

Escritório em São Paulo - Vila Olímpia (mas pode fazer home-office de vez em quando!)

#### Diferenciais

- horário flexível 🕚
- macbook pro 💻
- temos uma máquina de nespresso ☕️
- podemos cursar os Nanodegrees de graça!

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com desenvolvimento front end (JavaScript, HTML, CSS, consumo de APIs, etc).
- Inglês (Udacity é uma empresa global, conversamos com desenvolvedores do mundo todo diariamente)

**Desejáveis:**
- já ter trabalhado com React ou Angular
- conhecer ES6 ou TypeScript

**Diferenciais:**
- já ter feito algum curso livre ou Nanodegree na Udacity
- projetos pessoais ou participar de algum projeto open source

## Contratação

CLT

## Nossa empresa

Nossa missão é trazer para o mundo um ensino superior acessível, envolvente e altamente eficaz. Acreditamos que a educação superior é um direito humano básico, e buscamos capacitar nossos alunos para evoluírem em seus estudos e carreiras

A educação deixou de ser um evento único e hoje é uma experiência constante ao longo de toda a vida. A educação precisa ser menos passiva (sem longas palestras) e mais prática e dinâmica. Ela deve capacitar os alunos para terem sucesso não só na sala de aula, mas na vida.

## Como se candidatar

Preencha o [formulário](http://grnh.se/ga3vdf2) (não se esqueça do github!)

Se houver dúvidas, pode comentar nesse issue ou me mandar um email! artur@udacity.com

**Comment by hillarysousa** [comment]
Pode enviar o currículo em português, ou precisa ser inglês?

--
*Hillary Sousa*
*Web Designer & Front-End Developer*

Em 3 de outubro de 2017 22:25, Artur de Oliveira Tsuda <
notifications@github.com> escreveu:

**Comment by arturts** [comment]
@hillarysousa pode ser em português mesmo!

**Comment by hillarysousa** [comment]
Enviei! Tem problema ser do RJ? Pretendo me mudar pra SP :)

--
*Hillary Sousa*
*Web Designer & Front-End Developer*

2017-10-03 22:34 GMT-03:00 Artur de Oliveira Tsuda <notifications@github.com

**Comment by arturts** [comment]
Valeu Hillary! Tem problema não!

**Comment by lucascavalcante** [comment]
Enviado.

Eu moro em Fortaleza, mas sou paulistano. Se der certo, volto na mesma hora para SP! :) Gosto bastante de projetos educacionais, e sou fã da Udacity.

**Comment by arturts** [comment]
Valeu @lucascavalcante!

**Comment by paulo70** [comment]
Enviando CV agora!

**Comment by emanuellarini** [comment]
People of color.. como faço pra saber se sou people of color?

**Comment by arturts** [comment]
@emanuellarini Lá no fim do formulário (logo acima do botão `SUBMIT APPLICATION`) você tem a opção de completar alguns campos a mais (confidenciais, entrevistadores nem tem acesso à esse tipo de informação). Do lado da opção `Race` tem um ícone, clica nele que tem essas informações 👍

**Comment by DawTaylor** [comment]
@arturts, acho que a questão de mais filosófica do que técnica.

@emanuellarini, o preenchimento desses dados é opcional, não passa de uma mera pesquisa.

Alias, bela vaga.

**Comment by arturts** [comment]
Seguindo as regras do repositório, só comentando aqui que o processo de seleção pra essa vaga continua rolando 👍

**Comment by renanrboliveira** [comment]
Olá @arturts, qual o nível do inglês que vocês exigem?

**Comment by arturts** [comment]
@renanrboliveira precisa ter o inglês bom o suficiente pra se comunicar num nível técnico (não digo "avançado" ou "intermediário" por que eu acredito que isso é totalmente relativo). O motivo disso é que precisamos conversar diariamente com pessoas de outros países (EUA, China, Índia, Alemanha, Egito, etc), tanto por escrito quanto por hangouts.

**Comment by ygorlazaro** [comment]
bom dia @arturts , vocês contratam via PJ também?

**Comment by arturts** [comment]
@ygorlazaro Não, apenas CLT

**Comment by arturts** [comment]
Processo de seleção continua rolando, pessoal. Estamos migrando do Lever para o Greenhouse, então alterei o link na descrição do Issue. Pra quem já enviou o formulário no link antigo, não se preocupem pois os dados da plataforma antiga estão sendo migrados para a nova!

**Comment by GigaMax13** [comment]
Olá @arturts, tudo bem?

Existe a possibilidade de ser uma contratação "Remoto - Total"?

**Comment by arturts** [comment]
@GigaMax13 tudo certo!

Infelizmente não. O home-office é bem flexível (não temos uma regra oficial que diga que precisamos estar no escritório X dias por semana), mas a pessoa precisa dar as caras de vez em quando.

**Comment by paulo70** [comment]
@arturts Bom dia, 
O processo continua aberto, ok. Mas preenchemos o formulário, enviamos o cv etc.. Teremos feedback quanto ao processo no caso de reprovação?
Não terá um teste técnico sera apenas o envio do cv?
Um abraço.

**Comment by arturts** [comment]
@paulo70 Bom dia, tudo certo?

O time de recrutamento está migrando de plataforma, e isso está causando alguns atrasos nos processos de seleção. Todos os candidatos recebem um email avisando se passaram para a próxima fase ou não.

Há testes sim, uma lição de casa (bem curtinha) e uma entrevista técnica.

**Comment by Rachc** [comment]
@arturts Essa vaga é muito boa (: 
Mandei meu curriculo para tentar uma vaga de junior

**Comment by gdsrosa** [comment]
Júnior também pode mandar? 😄

**Comment by felipecarvalho** [comment]
Applied 😉

**Comment by arturts** [comment]
@gdsrosa A gente não usa a classificação de Júnior/Pleno/Sênior, essas labels foram colocadas pelos admins do repositório 😛.

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by arturts** [comment]
@LFeh Opa, tinha esquecido de atualizar aqui! A posição ainda está aberta sim.
