### ISSUE TITLE
[REMOTO] Front-end Developer na BEYOND SOLUÇOES

### ISSUE THREAD

**Issue by Mariana9852** [frontendbr/vagas#5780]
[REMOTO] Front-end Developer na BEYOND SOLUÇOES

> 

## Nossa empresa

Já pensou em fazer parte de uma empresa que vai ALÉM de uma consultoria tradicional de outsourcing?
Nós da BEYOND estamos presentes nas principais organizações do mercado de investimentos e fintechs. Aqui, você irá atuar no maior Banco de Investimentos da América Latina, presente em 16 países, que preza por um time de alta qualidade e performance para solucionar grandes desafios. 

## Descrição da vaga

Participar no ciclo de vida de desenvolvimento de sistemas, analisando e implementando componentes visuais, realizando integração com APIs e desenvolvendo testes unitários. Trabalhar de acordo com as melhores práticas e padrões (metodologias ágeis, CI/CD, code reviews)

## Local

 Remoto 

## Requisitos

	• Inglês Fluente 
	• Experiência em desenvolvimento Frontend
	• Sólidos conhecimentos em ReactJS e seu ecossistema (redux, graphql, etc) 
	• Sólidos conhecimentos em HTML5, CSS, LESS e similares, ferramentas de design responsivo.
	• Javascript (ES5,ES6,ES7), Typescript, Nodejs
	• Habilidade de criar interfaces limpas a partir de layouts predefinidos
	• Habilidade de trabalhar de maneira independente com times nacionais e internacionais

## Benefícios

para Contratação CLT 
*Benefícios* (100% subsidiados pela Beyond)
- Benefício de R$ 800,00 (podendo ser distribuídos em VR, VA).
- Plano de saúde: SulAmérica Saúde
- Plano odontológico: SulAmérica Odonto
- Seguro de Vida.

PJ = Sem benefícios 
- ...

## Contratação

PJ Ou CLT

## Como se candidatar

Por favor envie um e-mail para mariana.lemos@imaginebeyond.com.br com seu CV anexado - enviar no assunto: Vaga React 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.
E-mail para contato em caso de não haver resposta: mariana.lemos@imaginebeyond.com.br

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível

- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
