### ISSUE TITLE
[Remoto] Front-end Developer na Zallpy Digital

### ISSUE THREAD

**Issue by jessicalains** [frontendbr/vagas#5781]
## Nossa empresa

Buscamos Desenvolvedor Front-end para atuar projeto de cliente do ramo financeiro.
Você realizará constantemente a construção e melhoria de um produto, portanto viverá na prática todas as etapas do ciclo de desenvolvimento de um novo produto.
Para isso é necessário que você tenha muita iniciativa, vontade de aprender e ensinar.
Valorizamos o trabalho em equipe, as interações humanas e prezamos pela nossa autonomia como time e como produto.

## Descrição da vaga

O profissional irá participar do processo de modernização, reestruturação do Front.

## Local

Presencial ou Remoto 

## Requisitos

**Obrigatórios:**
Profissional com conhecimento SÊNIOR em React.
Experiência sólida com tecnologias da WEB, incluindo HTML5, CSS3, Bootstrap, JavaScript, Frameworks JS (React);
Entendimento de manipulação de Estado de aplicação com Redux, Flux, ou MOBX;
Compreensão completa sobre design responsivo, layouts fluídos e posicionamentos;
Entendimento sobre melhores práticas para performance, desenvolvimento cross-browser e otimização;
Experiência com ferramentas de versionamento de código como o Git;
Experiência com testes unitários para JavaScript ;
Conhecimento sobre organização de projetos e arquitetura limpa (clean architecture) e código (clean code);
Experiência com metodologias ágeis;

**Desejáveis:**
Angular 6+;
Vue.js;
RXJS;
Design System.

## Benefícios

- Plano de saúde
- Seguro de vida
- ...

## Contratação

PJ ou CLT a combinar

## Como se candidatar

Você pode enviar o seu currículo através do e-mail: talentos@zallpy.com ou realizar o cadastro através do site: https://zallpy.gupy.io/jobs/254817?jobBoardSource=gupy_public_page

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: talentos@zallpy.com

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível

- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
