### ISSUE TITLE
[REMOTO] Desenvolvedor Sênior na Imagem Geosistemas

### ISSUE THREAD

**Issue by luanasantosog** [frontendbr/vagas#5782]
A Imagem Geosistemas faz parte do Grupo Imagem. Somos uma empresa brasileira de tecnologia líder em Sistemas de Informações Geográficas, distribuidora oficial no Brasil da plataforma ArcGIS, da norte-americana Esri.

Fomos certificados pelo GPTW como um “Excelente Lugar para Trabalhar”. Venha fazer parte do nosso time!

Conheça mais sobre nossa empresa em: https://www.img.com.br/pt-br/home

## Local

Remoto.

## Requisitos

**Formação:**
- Graduação completa em Ciência ou Engenharia da Computação, ou área relacionada a TI.

**Experiências e Conhecimentos:**
- Experiência trabalhando com serviços restfull e microserviços;
- Html5, CSS3, node.js, angular, vue e react;
- Python e JavaScript;.
- SQL e Análise de Dados;
- Vivência em metodologias ágeis.

**Conhecimentos Desejáveis:**
- Conhecimento na plataforma ArcGIS.

## Benefícios

- Plano de saúde;
- Seguro de vida;
- VR ou VA;
- Assistência Odontológica;
- Auxílio Home Office. 

**Diferenciais:**
- Um ambiente de trabalho saudável e humanizado, com espaço para inovação e autenticidade.

## Contratação

A combinar

## Como se candidatar

Interessados e dentro do perfil, enviar currículo atualizado, e pretensão salarial para recrutamento@img.com.br informando
no assunto: Desenvolvedor Sênior - GitHub

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
