### ISSUE TITLE
[Florianópolis] Front-end Developer na AltoQi

### ISSUE THREAD

**Issue by Steporto** [frontendbr/vagas#5783]
Vaga Remota durante a pandemia

## Nossa empresa

A AltoQi é uma holding com soluções de software altamente especializadas para a construção civil. Somos movidos por grandes desafios e estamos em busca de pessoas que estejam dispostas a trabalhar com propósito, tecnologia e estar em constante aprendizagem.

Estamos em crescimento e buscando novos talentos. Procuramos alguém que esteja disposto a embarcar nessa trajetória conosco e gerar impactos positivos na vida das pessoas. E por isso, procuramos pessoas para nosso time de desenvolvimento, para nos ajudarem à crescer, atuando nos projetos da área.

## Descrição da vaga

- Validar, sob supervisão, os resultados obtidos pela implementação de novas funcionalidades ou correção de funcionalidades existentes, tendo como base planilhas, nomes e outros recursos para garantir que os resultados do software produzido sejam corretos e compatíveis com as especificações recebidas.
- Criar e manter scripts de teste automatizado, atualizando a base de testes do produto, de forma a permitir que as implementações futuras possam ser verificadas através de testes de regressão completos do sistema.
- Utilizar a ferramenta e os procedimentos estabelecidos no Processo de Desenvolvimento da empresa para reportar problemas encontrados, indicar o progresso das suas atividades, apontar horas trabalhadas e demais informações aplicáveis.
- Atualizar, quando necessário e sob supervisão, o material de documentação para o usuário, com respeito às funcionalidades que foram desenvolvidas.
- Contribuir na estimativa de novas funcionalidades e na avaliação do impacto de novos requisitos a projetos em andamento, com relação à complexidade e viabilidade do esforço de teste envolvido.
- Apoiar a elaboração das especificações para desenvolvimento dos recursos que fazem parte do projeto.
- Ministrar treinamentos técnicos internos do setor, quando requerido.
- Contribuir nas demais atividades do Departamento.

## Local

Escritório: São José/Santa Catarina

## Requisitos

**Obrigatórios:**

- Ensino Superior completo em áreas relacionadas a Computação, Sistemas ou Automação;
- Experiência em testes manuais e automatizados;
- Conhecimento intermediário em Inglês (leitura e escrita).

## Benefícios

- Opções de Vale alimentação e/ou Vale refeição.
- Parceria com Assistência Odontológica.
- Também temos parcerias com o SESC, ACATE, redes de farmácia e restaurantes.
- No dress code (investimos no conforto, não há códigos para se vestir, desde que se sinta bem!)
- Oportunidade de trabalhar com profissionais que são referência no mercado.
- Faça parte de uma equipe que acredita na diversidade e inclusão. Aqui você pode ser você mesmo;
- Salário compatível com o mercado (negociável).
- Todas as nossas vagas são abertas para PCD.

## Contratação

CLT

## Como se candidatar

Por favor realizar o cadastro em nosso site: https://grupoaltoqi.solides.jobs/vacancies/96126#vacancyDescription

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: stefanie.bentzviller@altoqi.com.br

#### Alocação
- Remoto em durante a pandemia

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
