### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor(a) Node Pleno (IA + Assistentes de Voz - Alexa e Google)

### ISSUE THREAD

**Issue by benextleader** [frontendbr/vagas#5785]
## Nossa empresa

Somos focados em IA (inteligência artificial) e acreditamos que a interação por voz já revoluciona a maneira como acessamos informações. Falar com o celular não é coisa de loucos e comprar também não será. Começar um serviço ou uma relação muito menos. Fortalecer marcas, gerar venda, reter e conhecer seus clientes. Tem muita coisa legal por fazer e a Benext quer ajudar a sua marca a construir relações usando assistentes de voz.

## Descrição da vaga

- Desenvolver projetos e produtos para Assistentes de Voz (Alexa e Google Assistente).
- Participar do processo criativo, trazendo novidades, ideias e soluções aos projetos.
- Estar pronto a especificar, prototipar, testar, aprender, crescer e publicar!
- Pronto para um novo caminho sendo construído que oferece grandes chances de aprendizado e destaque no mercado.

## Local

3 dias presenciais, no escritório na Barra da Tijuca - RJ e 2 dias remotos.

## Requisitos

- Conhecimento em arquitetura de software
- 3 anos de experiência com desenvolvimento
- Node (JavaScript e TypeScript)
- Banco de dados MySQL
- AWS (Lambda, SQS, RDS) e/ou Google Cloud (Functions, etc)
- Facilidade de debugar e criar rotinas de teste

**Diferenciais:**
- Ter experiência anterior em desenvolvimento de produtos
- Microserviços
- Arquitetura/Deploy em Cloud
- Domain-Driven Design
- Bancos não relacionais NoSQL

Obs.: Para quem é da cidade do Rio, são 3 dias presenciais + 2 dias em home office.

## Contratação

PJ - R$6.500

## Como se candidatar

Por favor envie um email para vaga@benext.ai com Pretensão e seu CV e/ou Linkedin. 
Enviar no assunto: Vaga Dev Pleno.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

#### Nível
- Pleno / Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
