### ISSUE TITLE
[Rio Claro-SP ou Remoto] Front-end Developer na Mindpool

### ISSUE THREAD

**Issue by luizlahr** [frontendbr/vagas#5786]
## Nossa empresa

Mindpool é uma Startup Dinamarquesa na area de Inteligência Coletiva, que recentemente abriu um escritório em Rio Claro - SP

Somos uma empresa de tecnologia de crescimento rápido, com sede em Copenhagen na Dinamarca. Nossa missão é fornecer para as empresas ferramentas de ponta para extrair o máximo de benefícios da inteligência coletiva. A Mindpool foi formada após décadas de pesquisas.

## Descrição da vaga

Procuramos developers para atuar 100% focado no frontend, implementando features baseadas nos designs de nosso UI/UX Designer. Participar de reuniões diárias com a equipe da Dinamarca (StandUp, Planning, Demo, etc). E nos ajudar na criação de novas features, desde o planejamento até a execução.

## Local

A vaga pode ser tanto remota ou em nosso escritório no interior de São Paulo (Rio Claro - Centro). Onde também fazemos nossos happy hours toda sexta.

## Requisitos

**Obrigatórios:**
- ReactJs (senior)
- NextJS
- ContextAPI
- Redux
- CSS
- TypeScript

**Desejáveis:**
- Testes Automatizados
- GraphQL 

**Diferenciais:**
- Chakra UI
- Vercel
- Inglês
- AWS
- Scrum

## Benefícios
- Férias Pagas

**Diferenciais:**
- FridayBar
- Evento Extra-Oficce Mensal
- Vivencia com equipe internacional
- Snacks
- Refrigerante

## Contratação
PJ a combinar

## Como se candidatar
Pelo Linkedin no link https://www.linkedin.com/jobs/view/2722799657
ou Currículo atualizado para o e-mail luiz@mindpool.com

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: luiz@mindpool.com

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
