### ISSUE TITLE
100% home office] Desenvolvedor Front-end ReactJs @ Hagloo 

### ISSUE THREAD

**Issue by giovaniPoletohagloo** [frontendbr/vagas#5787]
Será o responsável por desenvolver novas características de frontend para a aplicação, garantindo sempre uma aplicação estável e com uma boa qualidade de código e arquitetura.

Responsabilidades

● Evolução: realizar o desenvolvimento de novas características do frontend complexo sempre um código limpo e organizado
● Manutenção: resolver e acompanhar incidentes no sistema
● Refatorar: sempre que necessário refatorar aprimorando e organizando a estrutura código
● Usabilidade: como qualificado Microsoft sempre a melhor implementar usabilidade para nossos clientes
● Layout: responsável por criar novos layouts e aprovar junto ao solicitante para realizar um pedido
● Implementar: acompanhar os deploys de novas releases, garantindo a qualidade da entrega e a validação do que estamos subindo em produção. Tentando também automatizar sempre que for possível
● P&R: realizar testes de ponta a ponta em todas as implementações realizadas garantindo assim a qualidade da entrega
● Infraestrutura: contribuir com o tempo de infraestrutura para qualquer configuração referente ao projeto, tentando automatizar sempre que for possível.
● Stack: ReactJS, ReactNative, Angular, Bootstrap, Material, Docker, Kubernetes e outras ferramentas que a empresa venha a implementar

100% home office.

Modelo: PJ por tempo indeterminado.

CVs via: rh@hagloo.com

**Comment by diegofullstackjs** [comment]
Ja mandei meu CV

**Comment by giovaniPoletohagloo** [comment]
Muito obrigado!

**Comment by giovaniPoletohagloo** [comment]
Vaga aberta

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
