### ISSUE TITLE
[REMOTO] Front-end Developer na @Méliuz

### ISSUE THREAD

**Issue by Folks-Meliuz** [frontendbr/vagas#5789]
## Descrição da vaga

O Méliuz é uma empresa que desbloqueia relações inteligentes de consumo. Estamos em uma busca constante de melhorar a forma que nossos usuários fazem suas compras em nossas lojas parceiras, de maneira que todos saiam ganhando. Queremos que nossos parceiros continuem conosco para toda a vida e, para isso, estamos sempre levando inovações até eles. Tudo isso aliado ao nosso espírito empreendedor nos tornou uma grande empresa de cashback no Brasil e tem nos proporcionado um crescimento consistente.

Temos escritórios em Belo Horizonte e Manaus, mas podemos trabalhar remotamente. Nossa equipe fora da curva está espalhada pelo Brasil, impactando positivamente a vida de milhões de pessoas.

Precisamos de uma pessoa especialista em desenvolvimento front-end para ser responsável por guiar nossas decisões arquiteturais e evoluir nossos talentos.

Lidamos diariamente com diversas tecnologias Web, incluindo, React.js, Next.js, Redux, Node.js, PHP, Laravel e serviços da AWS.

**RESPONSABILIDADES E ATRIBUIÇÕES**

- Criação de soluções escaláveis, resilientes, altamente disponíveis e que suportam picos de acesso;
- Mentoria técnica de outros desenvolvedores;
- Desenvolvimento, manutenção e monitoramento do nosso novo site em React.js;
- Manutenção, monitoramento e desativação do nosso antigo site em PHP;
- Desenvolvimento e manutenção de aplicações de uso interno;
- Configurações de serviços da AWS incluindo, caches, lambdas, fallbacks e análise de logs.

## Local
Remoto 

## Requisitos

- HTML, CSS, JavaScript, PHP;
- React.js, Redux, Next.js;
- Uso e design de REST.API;
- Noções de AWS ou Google Cloud.
- 

**Diferenciais:**

- Desenvolvimento de soluções escaláveis, resilientes e altamente disponíveis;
- Serviços da AWS, incluindo, CloudFront, Caches, Edge@Lambdas, CloudWatch;
- Boas práticas relacionadas a SEO, Service Workers e PWA;
- Desenvolvimento backend, por exemplo, em Node.js, Python, Java, etc.

## Benefícios
🥗 Vale refeição / alimentação (R$60,00 por dia útil);
🤩Plano de saúde;
😁 Plano odontológico;
⏰ Horário flexível;
💰 Premiação por atingimento de metas coletivas;
💵 Participação nos Lucros e Resultados (PLR)
📚 Subsídio para treinamentos
🏊‍♀ Convênio com Sesc;
🤑 Cashback online em dobro;
🤰 Licença Maternidade/Paternidade estendida;
💻 Ajuda de custo mensal para o teletrabalho;
🪑 Empréstimo / Reembolso de cadeira e mesa de escritório
✝ Auxílio luto.

## Contratação
CLT

## Como se candidatar
Clique [AQUI](https://meliuz.gupy.io/jobs/646034?jobBoardSource=gupy_public_page) para se candidatar

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
