### ISSUE TITLE
[Remoto] Front-end Developer VTEX na 5A Attiva

### ISSUE THREAD

**Issue by thaynateixeiras** [frontendbr/vagas#5790]
> Vaga Remota durante a pandemia

## Descrição da vaga
Desenvolvimento de estórias que entrarem na squad; • Participação nas cerimônias da metodologia, incluindo daily, planning entre outros; • Conhecer a plataforma de e-commerce da empresa e suas principais funcionalidades; • Conseguir ter uma visão sistêmica para elaborar soluções práticas e performáticas com base em conhecimentos técnicos.

## Local

Remoto

## Requisitos
Desenvolvimento plataforma VTEX, HTML, NodeJS, Typescript, PHP,React,consumo de APIs REST, Git, Desenvolvimento Mobile de Páginas Responsivas.  

**Diferenciais:**
conhecimento com VTEX IO, Experiência com integrações de plataformas de ecommerce (Shopify, Magento, dentre outras). Familiaridade com o mercado de marketplace / e-commerces.

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para thayna.silva@5aattiva.com.br com seu CV anexado - enviar no assunto: Vaga Vtex

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
