### ISSUE TITLE
[REMOTO] Front-end Developer na ÓRAMA INVESTIMENTOS

### ISSUE THREAD

**Issue by brunacamposb** [frontendbr/vagas#5793]
## Órama Investimentos
https://www.orama.com.br/

A Órama foi a primeira plataforma Digital de Investimentos do Brasil e esse foi só o começo, viemos revolucionar o Mercado Financeiro tradicional, afinal, desde que nascemos estamos antecipando o futuro!
Entre tantos prêmios conquistados até hoje, temos convicção que a nossa maior conquista é o nosso time! Nossos visionários tem brilho nos olhos, inovação na alma e uma vontade enorme de realizar o impossível, porque quando estamos juntos, sabemos que conseguimos chegar lá!

E a cultura? Ah… não acreditamos em valores que só ficam na parede!
Somos focados em construir um ambiente altamente colaborativo, vivenciando os nossos valores no dia a dia:

Juntos realizamos o impossível! - Mais que um time, nossa conexão é nossa força
Confiança é a nossa base! Transparência, ética e integridade em todas as nossas relações
Fanáticos por nossos clientes! Entregamos mais que resultados, aceleramos sonhos.
Antecipamos o futuro! Transpiramos agilidade e respiramos inovação.
Buscamos sempre mais! Eficiência para atingir objetivos cada vez maiores
Fazer a diferença vale a pena! Resultados exponenciais geram oportunidades extraordinárias.

## Descrição da vaga

REQUISITOS E QUALIFICAÇÕES
HTML
CSS
Javascript e pelo menos um dos frameworks a seguir: Vuejs ou React  

## Local

Remoto

## Requisitos

**Obrigatórios:**
- HTML
- CSS
- Javascript e pelo menos um dos frameworks a seguir: Vuejs ou React  

## Benefícios

- Plano de saúde
-Seguro de vida
- VR de R$ 34/dia
- Vale Alimentação R$ 495/mês
- Auxílio creche R$1.100/mês
- Auxílio Home Office R$ 150,00/mês
- Gympass
- PLR Semestral

## Contratação

CLT

## Como se candidatar

Por favor envie um email para bruna.barbosa@orama.com.br com seu CV anexado - enviar no assunto: Vaga Frontend ou se candidatar pelo link: https://orama.gupy.io/jobs/1191948

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

#### Regime
- CLT

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by afoliveira** [comment]
Vocês aceitam PJ e também só é full-time ?

**Comment by Sneezi** [comment]
@afoliveira pelo visto é clt mesmo =3

**Comment by brunacamposb** [comment]
Apenas CLT :)

**Comment by thaygrance** [comment]
tentei mandar e-mail, mas, retornou como "não encontrado". Tem algum endereço alternativo? @brunacamposb ?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
