### ISSUE TITLE
[São Jose dos Campos - SP] Front-end Developer na Acosta Aerospace

### ISSUE THREAD

**Issue by hr-acosta** [frontendbr/vagas#5794]
`[São José dos Campos] Front-End Developer na Acosta Aerospace`
==================================================

## Nossa empresa (Acosta Aerospace)

**Acosta Aerospace** é uma start-up e oferece uma oportunidade para desenvolvedor FrontEnd (web)

Esta oportunidade é uma BOLSA DE TREINAMENTO TÉCNICO TT-4, integrante de nosso projeto de pesquisa tecnológica financiado pela FAPESP

A bolsa TT-4 possui requisitos e valores definidos pela FAPESP, que podem ser encontrados em: 

- https://fapesp.br/3098/niveis-de-bolsas-tt; 
- https://fapesp.br/valores/bolsasnopais.

## Descrição da vaga

**O PROJETO**
Plataforma WEB (desktop/mobile) para apresentação de dashboards a gerentes de produção agrícola

**LOCAL DE TRABALHO**
Incubadora de empresas do ITA (Instituto Tecnológico de Aeronáutica), Campus do DCTA, São José dos Campos – SP

**REGIME**
Bolsa de pesquisa (Não é CLT)

**DURAÇÃO**
12 meses

**ATRIBUIÇÕES ESPECÍFICAS**
Este trabalho consiste em implementar um sistema de gerenciamento, recuperação e exibição de informações e exibir os resultados de interesse via WEB/mobile.

Algumas das atividades previstas:
•	Geração de conceitos/Design de dashboards, visualizações e desenvolvimento da interface com o usuário;
•	Programação/codificação.
•	Implementação da visualização.
•	Desenvolvimento e manutenção da interface do usuário.
•	Implementação de design em sites mobile.
•	Criação de ferramentas que melhoram a interação com o site, independentemente do navegador.
•	Testes de usabilidade/correções
•	Conexão com bancos de dados locais;

## Local

Escritório, [SP], [SÃO JOSÉ DOS CAMPOS], [ITA]
Incubadora de empresas do ITA (Instituto Tecnológico de Aeronáutica), Campus do DCTA, São José dos Campos – SP

## Requisitos

**Obrigatórios:**
•	Especialista em Tecnologia de Informação (TI), com pelo menos dois anos de experiência após a graduação (ensino superior) ou título de mestrado na área de TI (Regras da bolsa TT4 da FAPESP)
•	Capacidade de trabalhar de forma eficaz em um ambiente de equipe multidisciplinar dinâmico.
•	Experiência com linguagens e conceitos de programação modernos (micro serviços, contêiner, etc.)

**Desejáveis:**
•	Vibração profissional! Gostar de tecnologia e ciência da informação! Gosto pelo estudo e atualização profissional.
•	Experiência com desenvolvimento web/móvel.
•	Experiência com banco de dados, análise e manipulação de dados.
•	Noções de estratégia de desenvolvimento de software. 

## Benefícios
Bolsa de pesquisa. Não é CLT.
Valor da bolsa: 3k

## Contratação

Bolsa

## Como se candidatar

https://acosta-aerospace.com/careers

## Labels
<São José dos Campos>

#### Alocação
- Presencial

#### Regime
- Bolsa 12 meses

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by hr-acosta** [comment]
Olá Felipe. boa tarde.
Sim está aberta, aceitando candidatos. Obrigado.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by hr-acosta** [comment]
Olá Felipe. Vaga está aberta. Obrigado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
