### ISSUE TITLE
[Juatuba/MG (BH e região)] Front-end Developer @ Palácio dos Leilões

### ISSUE THREAD

**Issue by santos-jp7** [frontendbr/vagas#5796]
# Palácio dos Leilões - Sobre

O Palácio dos Leilões exerce uma das maiores atividades leiloeiras da América Latina, com atuações em todo o Brasil. Atuando no ramo desde 1.951, o Palácio dos Leilões atualmente dispõe de uma equipe de aproximadamente 250 (duzentos e cinquenta) funcionários, todos altamente especializados, com treinamentos periódicos, sempre prontos para atender com eficiência tanto os seus comitentes (empresas públicas e privadas, instituições financeiras e seguradoras), como os arrematantes dos bens.

A história do Palácio dos Leilões começou nos anos 50, com o Senhor Antônio Ferreira Rocha Filho que, ao longo dos anos, foi construindo uma brilhante carreira mediante a realização de inúmeros e grandiosos leilões. Com todo esse trabalho, a atividade foi crescendo e firmando seu nome no mercado com ética e profissionalismo. Com o passar dos anos, toda essa tradição foi transformando-se numa sólida e experiente vivência de mercado que, aliadas às novas e modernas perspectivas, resultou na estrutura como hoje conhecemos.

A principal estrutura funcional do Palácio dos Leilões, fica na cidade de Juatuba, região metropolitana de Belo Horizonte/MG, sede própria, com área de 1.000.000 de metros quadrados, situada próxima à BR 381 e MG 050. Após amplos estudos de viabilidade, o terreno foi escolhido por ter sido caracterizado como sendo um local privilegiado por importantes vias de acesso, facilitando tanto a remoção de bens, quanto o acesso do público em geral. A sede foi construída de forma totalmente planejada e inaugurada no ano de 2016, tornando-se o maior parque de leilões da América Latina.

# Descrição da vaga

Como parte do time de desenvolvimento do Palácio dos Leilões, você atuará com o desenvolvimento de novos projetos, manutenção do sistema atual, arquitetura de sistemas, infraestrutura e banco de dados.

# Local

Juatuba/MG, porém, a vaga está disponível para BH e região.

# Requisitos

## Obrigatórios:

* Experiência com VueJS (um ano pelo menos)
* Habilidade analítica e realização de trabalho em equipe
* Experiência com Javascript/Typescript

## Diferenciais:

* Bootstrap
* Arquitetura
* Padrão de projetos
* Infraestrutura

# Benefícios

* Plano de saúde e plano odontológico
* Vale refeição
* Vale transporte
* Bônus empresarial

# Contratação

CLT

# Como se candidatar

Envie um e-mail para vagas@palaciodosleiloes.com.br (fique a vontade para adicionar Github, Linkedin, CV e outros)

Colocar no assunto: Vaga Front-end Developer - [${seuNome}]

# Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: vagas@palaciodosleiloes.com.br ou assistente.rh@palaciodosleiloes.com.br

# Labels

## Alocação

* Presencial

## Regime 

* CLT

## Nível

* Pleno

## Tecnologias

* Javascript
* Typescript
* Vue
* Nuxt
* FrontEnd
* Express

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
