### ISSUE TITLE
[REMOTO] Desenvolvedor na Codex Utilities

### ISSUE THREAD

**Issue by luanasantosog** [frontendbr/vagas#5797]
## Nossa empresa

 A Codex é uma organização que atende diversos segmentos do mercado, oferecendo soluções completas e especializadas em tecnologia, desenvolvimento de sistemas de informação, consultoria setorial e práticas de gestão corporativa. 
Conheça mais sobre nossa empresa em: www.imgsistemas.com.br 

## Local

Remoto.

## Requisitos

**Formação:**
- Formação em curso superior de ciências da computação, análise de sistemas e/ou sistemas de informação.

**Requisitos:**
- Domínio em C# (.NET Core e .NET Framework);
- Amplo conhecimento em Javascript;
- Conhecimento em AngularJS e Angular 8+;
- Utilização de padrões de desenvolvimento de software;
- Conhecimento em SQL (Consultas e Desenvolvimento de Procedures PL/SQL);
- Conhecimento em criação de APIs REST;
- Versionamento com GIT.

**Desejável:**
- Experiencia com CI/CD com Azure Devops;
- Vivência em Desenvolvimento ágil;
- Conteinerização com Docker e Kubernets;
- Gerenciamento de banco de dados Oracle e SQL Server;
- Conhecimento em padrões e boas práticas para web;
- Desenvolvimento com Python;
- Experiência com desenvolvimento de sistemas de informação geográfica.

## Contratação

A combinar

## Como se candidatar

Interessados e dentro do perfil, enviar currículo atualizado, e pretensão salarial para recrutamento@img.com.br informando
no assunto: Desenvolvedor - GitHub

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
