### ISSUE TITLE
[REMOTO] Front-end Developer React Native na DB1 Global Software

### ISSUE THREAD

**Issue by CamilaFFelix** [frontendbr/vagas#5799]
## Nossa empresa

A DB1 Global tem uma base de mais de 3000 clientes, sendo 13 deles internacionais.
As entregas contam com 97,1% de assertividade, para garantir este resultado cada cliente possui um squad totalmente dedicado ao seu projeto.
Hoje a empresa tem em seu portfólio, fintechs, grandes empresas e consultorias, além de clientes internacionais.
A DB1 Global faz parte do ranking da Great Place To Work, há 10 anos está entre as 150 melhores empresas para se trabalhar, na última avaliação ela teve aprovação de 91% dos funcionários.

## Descrição da vaga

A DB1 Global Software que está a mais de 20 anos no mercado desenvolvendo soluções e produtos para grandes empresas, hoje ela está selecionando algumas pessoas para compor o time de Mobile na posição de Desenvolvedor React Native para atuar em um projeto de uma Fintech Brasileira.

## Local

Remoto

## Requisitos

**Obrigatórios:**

- Mínimo 2 anos de experiência com desenvolvimento em React Native
- Conhecimento em Mobile
- Conhecimento em Git
- Conhecimento em Cloud Computing

## Benefícios

- Horário Flexível
- Vale Refeição ou Vale Alimentação
- Plano de Saúde
- Plano Odontológico (Opcional)
- Seguro de Vida (Opcional)
- Auxilio Home Office
- Gympass (Opcional)
- Convênio com farmácia Droga Raia - Desconto para Colaboradores

**Diferenciais:**
A DB1 Global hoje é uma gigante e isto se deve aos fortes valores culturais implementados: liberdade para contribuir com novas idéias, aprendizado através de programa de mentoria e do lema Ao infinito e Além (evolução, errar faz parte, um problema pode ser uma bela oportunidade) e desafios propostos no programa mestre dos códigos.

## Contratação

CLT

## Como se candidatar

Se você quer transformar o futuro e gerar impacto positivo com seu trabalho é só clicar neste link: https://bit.ly/39Tw7vG

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
