### ISSUE TITLE
[São Paulo] - Desenvolvedor(a) Front-End - Jussi

### ISSUE THREAD

**Issue by DouglasAmarelo** [frontendbr/vagas#58]
## Descrição da vaga

Buscamos pessoas que tenham experiência em desenvolver produtos digitais, que queiram melhorar a vida das pessoas através de produtos inovadores, criativos, bem feitos, com códigos bem escritos e eficientes. Produtos capazes de afetar a vida de milhares de pessoas ao redor do mundo.
Aqui, você será desafiado e será responsável pelo desenvolvimento de projetos para grandes empresas.
Se você gosta de desafios, quer crescer profissionalmente e sonha em fazer parte de uma grande empresa com grandes clientes, essa é a sua oportunidade.

Site da empresa: http://jussi.com.br/

## Local

Rua Bandeira Paulista, São Paulo - Itaim Bibi

## Benefícios
- Excelente ambiente de trabalho
- Oportunidade de crescimento profissional
- Oportunidade de trabalhar com grandes clientes
- Vale refeição
- Vale transporte
- Assistência médica
- Assistência odontológica

## Requisitos

**Obrigatórios:**
- Capacidade para escrever código consistente, eficiente, minimalista, reutilizável e escalável
- Desenvolver código semanticamente correto e otimizado para SEO
- JavaScript, HTML5, CSS3
- SASS e/ou LESS
- Task runners (Grunt / Gulp)
- Controle de versão (Git / SVN)
- Wordpress
- Experiência com bibliotecas de Javascript, como jQuery
- Experiência com grids fluidos e sites responsivos
- Pacote Adobe, em especial Photoshop
- Facilidade de trabalho em equipe
- Proatividade

**Desejáveis:**
- Portfólio
- Experiência de pelo menos 2 anos com produtos digitais
- Lidar bem com pressão e desafios constantes

**Diferenciais:**
- Conhecimento avançado em javascript (sem plugins ou bibliotecas)
- Experiência em construção de e-commerce na plataforma VTEX

## Contratação

CLT
Alocado
Salário a combinar

## Vagas disponíveis
4 

## Como se candidatar

**Obrigatório:**
Por favor envie um email para douglas.lopes@jussi.com.br com o assunto: "[ frontendbr ] - Vaga Desenvolvedor(a) Front-end"

No email deve conter: 
- Telefone pra contato
- Pretensão salarial
- LinkedIn
- Link do portfólio
- Link de trabalhos feitos
- curriculo-com-seu-nome.pdf

**Comment by diegoemerique** [comment]
Eu sei que está são paulo e tudo, mas como tem 4 vagas queria saber se não existe alguma possibilidade de trabalho remoto?

**Comment by LFeh** [comment]
Ótima vaga.

boa sorte ;)

**Comment by DouglasAmarelo** [comment]
Oi @LFeh Muito obrigado!

**Comment by DouglasAmarelo** [comment]
Pessoal.. importante saber que a vaga é para profissionais "Alocados".
Infelizmente não temos a possibilidade de trabalhar remotamente.

Boa sorte a todos!

**Comment by LFeh** [comment]
Rolou?

**Comment by victor-castro** [comment]
Rolou?

**Comment by camilatigre** [comment]
@DouglasAmarelo 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
