### ISSUE TITLE
[remoto] Pessoa Desenvolvedora Fullstack Sênior - PHP e Vue.JS | Feedz

### ISSUE THREAD

**Issue by larissaaguiar** [frontendbr/vagas#5800]
🚀 A FEEDZ:
Nosso propósito é criar ambientes de trabalho mais felizes! Por isso, começar pelo nosso próprio ninho é tão importante! Somos Parrots determinados e que se importam uns com os outros, a sede de resultado é latente e o feedback sincero é rotina.

Aqui temos um ambiente de trabalho focado na cooperação entre Devs, confiamos no trabalho de nossos colaboradores e por isso acreditamos que nossos desenvolvedores devem ter autonomia!

Prezamos pela liberdade de falar o que se pensa e pelos feedbacks constantes, além de ter um time realmente diverso 💙 sabia que nosso time de produto é composto 42% por mulheres e 42% por pessoas negras?

Temos também flexibilidade de horários. Tem que ir ao banco? Precisa sair mais cedo para pegar os filhos na escola? Sem problema.

Estamos buscando uma pessoa para o cargo de Pessoa Desenvolvedora Fullstack Sênior(PHP e JS) que irá atuar no nosso time de Produto, trabalhando diretamente com nosso gerente de produto em um time de alta performance, desenvolvendo sistemas que impactam mais de 100 mil usuários diretamente.

📚 RESPONSABILIDADES E ATIVIDADES:
Desenvolver backend com PHP_(Com conhecimentos no framework Laravel);
Desenvolver frontend com CSS, HTML e JS (Com forte conhecimento em Vue.JS e aplicando nosso design system);
Aplicar boas práticas alinhadas com o time no desenvolvimento (Códigos coerentes e alinhados ao Clean Code; Desenvolvimento com foco em segurança, patterns, automação, etc);
Desenvolver novos módulos na plataforma;
Desenvolver e aplicar testes automatizados;
Fazer a gestão da informação das demandas atualizando o status dos projetos.

🥇 PRÉ-REQUISITOS:
4 anos de experiência em desenvolvimento web com PHP;
3 anos de experiência em desenvolvimento web com Vue.JS, HTML, CSS;
Experiência com TDD;
Estar trabalhando atualmente com as tecnologias de nossa stack;
Experiência com banco de dados relacional (Atualmente usamos MySQL 8);
Gostar de trabalhar em time. Pessoa Desenvolvedora sozinha não faz verão!

🎯DIFERENCIAIS:
Ter trabalhado em empresas SaaS;
Ter trabalhado com empresas com mais de 10 mil usuários.

✨ BENEFÍCIOS:
Vale Comida (R$600)
Plano de Saúde com Coparticipação Unimed
Plano odontológico Nacional da Bradesco Dental
Auxílio Parrot Feliz (R$100/mês de investimento no desenvolvimento pessoal, saúde física ou mental do Parrot)
Auxílio Contas (R$80/mês)
Happy Bird(day) (um dia de folga no mês de aniversário)
Licença paternidade estendida
Descontos nas empresas conveniadas com a ACATE
Ifood Office

💰 SALÁRIO ENTRE R$6.000 A R$7.174(CLT)*

A depender do tempo de experiência
Candidate-se em: https://enliztjob.app.link/QDQFhGOYYjb

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
