### ISSUE TITLE
[Remoto] Front-end Developer na Devellop Labs

### ISSUE THREAD

**Issue by obrunoalbano** [frontendbr/vagas#5802]
## Nossa empresa

A Devellop Labs é uma empresa que oferece outsourcing de T.I para empresas de desenvolvimento e agências digitais.

O candidato(a) fará parte de uma equipe multidisciplinar, onde todos colaboram com postura entusiasta, paixão por tecnologia e inovação, e ampla experiência em desenvolvimento web.

## Descrição da vaga

A Devellop Labs está procurando uma pessoa com perfil de nível júnior a pleno, que tenha experiência na área de desenvolvimento Front-End, com clientes e projetos. Essa experiência pode ser através de projetos frellas ou trabalho empresarial.

É importante que você goste de se comunicar e trabalhar em equipe, já que aqui temos um ambiente super colaborativo. Ao mesmo tempo, valorizamos que cada membro do time seja autônomo para gerir suas demandas.

## Requisitos

**Obrigatórios:**
- Conhecimento prático em HTML5 e CSS3 Responsivo
- Conhecimento avançado de JavaScript
- Desenvolvimento cross-plataforma e testes cross-browser
- Confortável trabalhando com o controle de versão (Git)
- Capacidade de trabalhar de forma independente com uma supervisão mínima
- Experiência de trabalho com APIs, ou integrar uma API de terceiros ou criar o seu próprio, quando necessário.
- Conhecer pré-processadores CSS como Less, Sass e Stylus;
- Conhecer os frameworks JS como React, React Native, ou VueJS;
- Atenção à detalhes na implementação de layouts;

**Desejáveis:**
- Experiência com sistemas de build (Bash, Grunt, Make, Ant)
- Conhecimento básico de pelo menos uma linguagem server side (Python, PHP, Node.js, Ruby, Go, etc)
- Experiência com UI e UX;
- Experiência com magento;

## Contratação

PJ a combinar

## Como se candidatar
Pelo link: https://devellop.com.br/trabalhe-conosco ou envie um email para rh@devellop.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by obrunoalbano** [comment]
Vagas ainda disponíveis

**Comment by Yago-M-A** [comment]
Se existir uma oportunidade para quem pretender entrar nessa área de Dev Front End, estou a disposição, rs.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
