### ISSUE TITLE
[Remoto] Pessoa Desenvolvedora FrontEnd Pleno na 1STi

### ISSUE THREAD

**Issue by tibraga** [frontendbr/vagas#5805]
## Nossa empresa

A 1STi é uma empresa de consultoria de Deep Tech, composta por uma equipe descentralizada formada por inovadores, desenvolvedores, engenheiros, empreendedores, designers e cientistas de dados comprometidos com a crença de que o nosso trabalho é uma síntese de arte, humanidade e ciência.

## Descrição da vaga

Atuação em projeto de grande porte e longo prazo nas áreas de saúde, seguradora de saúde e educação. Além da possibilidade de atuar em outras startups do ecossistema.

Desenvolvimento de funcionalidades usando react.js e de layouts usando styled-components.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- CSS, Javascript, React, API e ES6
- Integração das aplicações com APIs Restful

## Benefícios

- Plano de saúde

**Diferenciais:**
- flexibilidade de horário

## Contratação

CLT ou PJ a combinar

## Como se candidatar

Por favor envie um email para vagas@1sti.com.br com seu CV anexado - enviar no assunto: Vaga Frontend Pleno

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
