### ISSUE TITLE
[Remoto] Pessoa Desenvolvedora Mobile Senior na 1STi

### ISSUE THREAD

**Issue by tibraga** [frontendbr/vagas#5806]
## Nossa empresa

A 1STi é uma empresa de consultoria de Deep Tech, composta por uma equipe descentralizada formada por inovadores, desenvolvedores, engenheiros, empreendedores, designers e cientistas de dados comprometidos com a crença de que o nosso trabalho é uma síntese de arte, humanidade e ciência.

## Descrição da vaga

Atuação em projeto de grande porte e longo prazo nas áreas de saúde, seguradora de saúde e educação. Além da possibilidade de atuar em outras startups do ecossistema.

Criação e definição da arquitetura de apps mobiles usando as melhores práticas.
Ideal ter desenvoltura para liderar um time e guiá-lo durante o projeto auxiliando em code review, passagem de conhecimento, refactor.
Ajudar a fazer pair programming com os desenvolvedores menos experientes do time para elevar o nível técnico da equipe.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 5 anos de experiência desenvolvendo software
- 3 anos de experiência em react-native
- Javascript (Estrutura de dados, ES6, Async, Promises)
- React.js (state, props, lifecycle, hooks, redux/mobx)
- Rest e GraphQL
- Testes de integração e end-to-end (react-native-testing-library, detox)

## Benefícios

- Plano de saúde

**Diferenciais:**
- flexibilidade de horário

## Contratação

CLT ou PJ a combinar

## Como se candidatar

Por favor envie um email para vagas@1sti.com.br com seu CV anexado - enviar no assunto: Vaga Mobile Senior

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Senior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
