### ISSUE TITLE
[REMOTO] Full Stack Developer - Ruby on Rails [Pleno] | STANT

### ISSUE THREAD

**Issue by RosannePlech** [frontendbr/vagas#5809]
> ### Requisitos:
Formação superior em andamento/completa em Sistema de Informação, Análise de Sistemas, Ciências da Computação ou áreas afins;
Inglês: Intermediário;
Conhecimento em PostgreSQL;

> ### Conhecimentos Necessários:
Conhecimento intermediário em Ruby e JavaScript;
Conhecimento em Ruby on Rails;
Experiência básica com Git;
Experiência básica com Docker;
Conhecimento em Rspec (TDD)

> ### Diferenciais:
Experiência com outras linguagens (principalmente outros paradigmas);
Processamento em background com Delayer Job ou Sidekiq;
Conhecimentos sobre AWS;
Experiência/conhecimento em Elixir será um diferencial;
Conhecimento em padrões de projeto;
Conhecimento intermediário em Metodologia Ágil (SCRUM);

> ### Benefícios
🥗VR ou VA (Cajú Benefícios)
🚗VT ou Vale Mobilidade (Caso escolha modalidade Presencial)
🕐 Flexibilidade de horário
🎈Day off de aniversário
😃Time colaborativo
✅Ótimo ambiente para trabalhar
📱Modelo de trabalho remoto ou presencial (Maceió-AL)

> ### Contratação
PJ.

> ### O Stant
Somos o Stant, uma plataforma SaaS (Software como Serviço) nas versões Web e Mobile de gerenciamento de obras que está revolucionando o mercado da Construção Civil.
Nosso time é formado por profissionais experientes em diferentes áreas, verdadeiros amantes da tecnologia e engenharia, apaixonados por superar expectativas. 
Contamos com a inovação e velocidade de uma startup para oferecer aos nossos clientes uma experiência diferenciada para acompanhamento e gestão de obras.

Vamos juntos? 🤝🚀🧡

> ### Como se candidatar 
Para se candidatar e / ou saber mais sobre a vaga, acesse: https://jobs.solides.com/stant/vaga/85913

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by RosannePlech** [comment]
Ainda temos vagas abertas

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
