### ISSUE TITLE
Desenvolvedor web .NET URGENTE

### ISSUE THREAD

**Issue by Pmirandaricardo** [frontendbr/vagas#581]
## Descrição da vaga

Precisamos de profissionais curiosos, que anseiam por crescimento e conhecimento de novas tecnologias, que queiram agregar ideias e conhecimentos, para atuar em nosso projeto de desenvolvimento de Reconhecimento Facial, Biometria para obtenção da CNH e processo de Reciclagem de CNH.

## Local

Escritório próximo à estação São Judas - São Paulo/SP

## Benefícios

- Plano de saúde
- Plano Odontológico
- Seguro de vida
- VR de R$ 27 ao dia
- Auxílio creche
- Convênio farmácia
- VT

## Requisitos
**Obrigatórios:**
Experiência com ASP Core;
ASP NET;
Angular JS;
Entity;
Rest;
Nhibernate;
Banco SQL;
Utilizar padrões e boas práticas para desenvolvimento;
Experiência com desenvolvimento em C# em plataforma Web.

**Desejáveis:**
- Conhecimentos em Biometria

## Contratação

Apenas CLT

## Nossa empresa

Grupo Pioneiro no segmento de Tecnologia de Trânsito, presente em quase todos os estados do Brasil, com 30 anos de mercado.

## Como se candidatar

Por favor envie um e-mail para pmiranda@tecnowise.com.br com seu CV anexado. Grata =)

**Comment by Emanuelmeira** [comment]
Olá, 
Possibilidade pra remoto ?

**Comment by Pmirandaricardo** [comment]
Olá, @Emanuelmeira , agradeço por seu interesse.
Não há possibilidade de trabalho remoto, apenas presencial.
Abraços,
Pamela.

**Comment by Emanuelmeira** [comment]
Muito Obrigado pelo retorno, sucesso na contratação.

**Comment by Pmirandaricardo** [comment]
@Emanuelmeira, se tiver indicações, serão muito bem vindas. Gratidão.

**Comment by kivervinicius** [comment]
@Pmirandaricardo acredito que terá mais sucesso postando aqui @backend-br/vagas

**Comment by LFeh** [comment]
Só vagas front-enders aqui

**Comment by Pmirandaricardo** [comment]
Obrigada =)
