### ISSUE TITLE
[São Paulo] Front-end Developer na [BANCO ALFA]

### ISSUE THREAD

**Issue by jeehand** [frontendbr/vagas#5810]
**Vaga Remota durante a pandemia**

## Nossa empresa

O Conglomerado Financeiro Alfa teve início em 1925, com a Fundação do Banco da Lavoura de Minas Gerais. Em 1972, o Banco da Lavoura alterou sua denominação para Banco Real S/A e posteriormente criou outras empresas financeiras que constituiriam o Conglomerado Financeiro Real. Em 1998, o Banco Real S/A teve seu controle acionário vendido ao ABN Amro Bank.
As empresas financeiras não vendidas (então Banco Real de Investimento, Real Financeira, Real Arrendamento Mercantil e Corretora Real) deram origem ao Alfa.
Com mais de 95 anos, o Alfa vem desenvolvendo sua atuação nos segmentos de wealth management, fusões e aquisições, asset management, private bank, previdência privada, seguros, crédito para pessoas jurídicas (PJ) e físicas (PF).

## Descrição da vaga

• Atuar em conjunto com as squads de Canais Digitais de produtos financeiros;
• Criar novas funcionalidades e manutenção dos nossos sites, baseadas nos designs de nosso UI/UX Designer;
• Analisar e implementar componentes visuais;
• Realizar integração com APIs e desenvolver testes unitários.

## Local

Híbrido, [SP], [SÃO PAULO], [CERQUEIRA CESAR - AV PAULISTA]

## Requisitos

**Obrigatórios:**
• Superior completo em cursos relacionadas à Tecnologia e áreas correlatas;
• Conhecimentos: HTML5, CSS3 (Sass), JavaScript (Vue, Nuxt, Typescript, NodeJS), Git (Fluxo Gitflow), SEO, Jest, Integração com backend via APIs REST, Metodologia Ágil;

**Diferenciais:**
• Experiência com serviços financeiros.

## Benefícios

Conheça nossos benefícios:
• Salário compatível com mercado;
• Assistência Médica e Odontológica, as opções serão apresentadas na fase admissão;
• Vale Transporte (opcional);
• Vale Alimentação e Vale Refeição;
• Auxilio Creche ou Babá;
• GymPass;
• Possiblidade de subsídio em cursos, pós-graduação ou MBA;
• AlfaClub - Clube de descontos em lojas, lazer, restaurantes, etc; 
• Portal Alfa Educação - Site com diversos cursos online gratuitos;
• PPR - Participação por Resultado.

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um e-mail para fernanda.resende@alfa.com.br com seu CV anexado - enviar no assunto: Front-End ou cadastre-se na vaga https://alfa.gupy.io/job/eyJqb2JJZCI6MTIyNjIwMywic291cmNlIjoiZ3VweV9wdWJsaWNfcGFnZSJ9?jobBoardSource=gupy_public_page 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@alfa.com.br

## Labels
- Alocado

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
