### ISSUE TITLE
[BRASÍLIA] Front-end Developer na Carto

### ISSUE THREAD

**Issue by rpbraga61** [frontendbr/vagas#5811]
## Carto.com.br

Somos uma Fintech especializada em Payments e Banking.

## Descrição da vaga

A opotunidade é um novo projeto web / wpa de conta digital feito em React ou Vue.js.

## Local

Remoto e horário flexível. 

## Requisitos

Esperiência forte em Front-end usando React ou Vue. 

**Desejáveis:**
-Conhecimento em backend e APIs.

**Diferenciais:**
- Conhecimento em Adquirencia, Payments e Banking.

## Contratação

PJ a combinar com pagamento por Sprint.

## Como se candidatar

Por favor envie um email para ricardo.braga@carto.com.br ou WA para https://wa.me/5561992713302

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dia após cada processo.

#### Regime
- Freela
- PJ

#### Nível
- Pleno
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
