### ISSUE TITLE
[Remoto] [Internacional] Front-end Developer na BHS

### ISSUE THREAD

**Issue by vvoa99** [frontendbr/vagas#5812]
> Oportunidade 100% remota.

## Nossa empresa
Nós somos a BHS!

Reconhecida desde 2015 como uma das melhores empresas para se trabalhar, temos mais de 25 anos de experiência, somos parceiros Gold da Microsoft e oferecemos soluções modernas de TI.

## O que a gente espera de você?

Buscamos uma pessoa de fácil relacionamento, com boa comunicação, que seja curioso, goste de pensar fora da caixa e trabalhar em equipe. Alguém que queira fazer parte de projetos incríveis e tenha muita vontade de aprender, ensinar e crescer junto com a BHS.

Buscamos uma pessoa que possua experiências com:

- React.js

- React Native

- Inglês avançado ou fluente

## Local

Remoto

## O que você pode esperar de nós?

- Plano de saúde Unimed;

- Assistência Odontológica

- Vale transporte ou auxílio no estacionamento.

- Vale Refeição, sem desconto

- Incentivo para Pós-Graduação, Especializações e MBA’s;

- Incentivo de certificações que você for aprovado;

- Incentivo a treinamentos;

- Incentivo ao curso de inglês

- Parcerias e convênios diversos

- Licença Maternidade/Paternidade estendida

- PLR

- Programas de conteúdo, como o Deu Match!, e uma rotina com aprendizado constante

## Contratação

CLT

## Como se candidatar

Basta se candidatar na nossa página de carreiras: https://jobs.kenoby.com/bhs/job/react-developer/61433e0e024c594d542b106a?utm_source=website

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by vvoa99** [comment]
Oportunidade INTERNACIONAL, com desafios incríveis, alta remuneração e a possibilidade de trabalhar em umas das 3 melhores empresas de Minas Gerais segundo o GPTW.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
