### ISSUE TITLE
[Remoto] Full-Stack/Techlead Developer na BikeHero

### ISSUE THREAD

**Issue by Fator3** [frontendbr/vagas#5816]
## Nossa empresa

A BikeHero trouxe a Internet das Coisas (IOT) para o mundo de duas rodas, utilizando a mesma tecnologia dos bancos digitais na validação de identidades e certificação de posse, não importa onde você esteja.

## Descrição da vaga

A BikeHero está apresentando crescimento consistente e com isso está começando a aumentar sua equipe de tecnologia. O(a) desenvolvedor(a)/techlead terá muita oportunidade de crescimento, pois entrará no início dessa jornada. Precisamos de uma pessoa que seja mais que um(a) executor(a) de tarefas e ajude a discutir, pensar e propor soluções inovadoras para os diversos desafios da startup!
Como a startup é enxuta, o(a) candidato(a) terá bastante autonomia (e com grandes poderes vêm grandes responsabilidades) e deve ser auto-gerenciável.
A BikeHero conta com o apoio de uma aceleradora de startups (Fator 3 Ventures) para ajudar na discussão das soluções.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- VueJS
- Java (Spring Boot)
- SQL

**Desejáveis:**
- conhecimentos em desenvolvimento mobile
- capaz de propor/pesquisar soluções inovadoras
- pensamento crítico

**Diferenciais:**
- interesse em tecnologias novas (blockchain, nft, machine learning)

## Contratação

a combinar

## Como se candidatar

Por favor envie um email para app@bikehero.com.br com seu CV anexado - enviar no assunto: Vaga Full-Stack/Techlead Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 14 dias após cada processo.

#### Alocação
- Remoto

#### Nível
- Pleno
- Sênior

![vaga_dev_bikehero_2021](https://user-images.githubusercontent.com/57358412/135872381-f50abe4b-459c-4f88-95a5-32205fd9b2e3.png)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
