### ISSUE TITLE
[São Paulo] Front-end React Developer Pleno na Hi Platform

### ISSUE THREAD

**Issue by alexsandercamargo** [frontendbr/vagas#5817]
## Nossa empresa

Esta vaga é para você integrar um de nossos times de desenvolvimento aqui na Hi Platform. Temos uma grande variedade de produtos direcionados a Customer Care.
A principal missão dos Devs na Hi é evoluir, com novas funcionalidades, os produtos que compõem nossa plataforma. Para isso, eles contam com um Roadmap criado em conjunto com os POs.
Nós seguimos a filosofia ágil na empresa, e as sprints costumam ter 3 semanas de duração. Os times são compostos por back-ends, front-ends e analistas de testes.

## Descrição da vaga

Buscamos um profissional engajado, disposto a explorar e aprender novas tecnologias. Nosso desafio para essa vaga é construir um produto com excelente usabilidade.

Você será responsável por:

- Planejar o trabalho de modo que sua entrega não sobrecarregue ou prejudique outras pessoas do time;
- Colaborar com outros desenvolvedores para destravar desafios técnicos;
- Participar de forma engajada em todos os rituais do SCRUM: sprint planning, reuniões de 15', retrospectiva, feedbacks;
- Desenvolver com qualidade o próprio código;
- Reportar de forma transparente e rápida as dificuldades técnicas que estejam bloqueando as entregas.

Você pode trabalhar em nosso escritório depois da pandemia ou, se desejar, pode ficar remoto 100% do tempo.

## Local

Remoto ou Escritório, [São Paulo], [São Paulo], [Berrini]

## Requisitos

**Obrigatórios:**
- 2 anos de experiência React JS
- Conhecimento avançado de protocolos HTTP e APIs Rest
- Conhecimentos avançados em Javascript e CSS

**Desejáveis:**
- Testes unitários
- Git
- Docker
- AWS

## Benefícios
-Cartão Caju R$ 900,00
-Notebook e fone de ouvido para Home Office
-Assistência médica Unimed | Cobertura nacional (apartamento) - estendido a dependentes e 100% pagos pela Hi 
-Assistência Odontológica Porto Seguro | Cobertura nacional - estendido a dependentes e 100% pagos pela Hi
-Auxílio Creche
-Auxílio a filho com deficiência 
-Seguro de Vida
-Licença maternidade de 6 meses e paternidade de 1 mês
-Emenda entre Natal e Ano Novo, sem descontar das férias (ou seja, temos um total 40 dias de férias aqui na Hi!)
-Becare e (acompanhamento médico, psicológico, nutricional e com personal trainer para promoção do bem- estar do Hier)
-Gympass

**Diferenciais:**
-Parceria com a USP e FIAP para pós-graduação e outros cursos
-Flexibilidade de horário (cenário atual com 100% de home office)
-Happy Hier Day: Ganhe 1 Day Off no mês do seu aniversário 🎉
-Revezamento nos feriados locais, de acordo com a dinâmica do time e momento da empresa
-Convênio Pleno com o Sesc
- Parceria com a escola de idiomas ROCKFELLER

## Contratação

CLT

## Como se candidatar

Candidate-se pelo nossa página na Gupy:
[https://hiplatform.gupy.io/jobs/1182411](https://hiplatform.gupy.io/jobs/1182411)

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
