### ISSUE TITLE
[REMOTO] Front-end Developer no KaBuM!

### ISSUE THREAD

**Issue by dani10kabum** [frontendbr/vagas#5818]
## Desenvolvedor Front-end no KaBuM!

Grande desafio de trazer novas frentes de sistemas para as operações de E-commerce, trazendo inovação e excelência de entrega. Nosso objetivo no KaBuM! é está sempre se atualizando a frentes de novas tecnologias e ferramentas, integrando o valor mais importante que é a Experiência do Cliente e melhoria de processos de negócios.

## Local

100% Home-Office
Escritório - Matriz , Limeira -SP

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ 15/dia
- Plano Odontológico

#### Diferenciais

- Prime Ninja: Com descontos exclusivos no Site.

## Requisitos

**Obrigatórios:**
- Superior completo na área de Tecnologia da Informação
- Linguagem de programação voltado a WEB
- Banco de dados
- Orientação Objeto
- Sólidos conhecimentos em:  JavaScript, React, Redux, Node, CSS, HTML, GIT e SCRUM
- Criação de código limpo, legível e cross-browser
- Experiência com desenvolvimento de sites responsivos

**Desejáveis:**
- conhecimentos em Styled-component, SSR, SASS, Redux-SagaS

**Diferenciais:**
- projetos opensource
- Inglês (Técnico)
- Experiência com metodologia ágil integração contínua de software

## Contratação

CLT - salário a combinar

## Sobre o KaBuM!

Somos pioneiros no comércio eletrônico brasileiro, há 18 anos construindo uma história de sucesso e hoje somos o maior e-commerce do segmento de tecnologia na América Latina!

Somos EQUIPE, somos AGILIDADE, somos TODOS NINJAS!

Somos um time diverso, formado por mais de 1.200 pessoas, obcecados por qualidade, velocidade de entrega e respeito pelo consumidor.

## Como se candidatar

Por favor entre em contato por [LinkedIn Danilo](https://www.linkedin.com/in/danilooscarjustino/) e [LinkedIn Leticia](https://www.linkedin.com/in/leticiacunhag/) ou envie um email para danilo.justino@kabum.com.br com seu CV anexado - enviar no assunto: Vaga DEV FRONTEND

## Labels

- JavaScript 
- React
- Redux
- Node
- CSS,
- Mysql
- NodeJS
- ReactJS
- JQuery
- JavaScript
- Angular
- GIT
- SCRUM

### Alocação:
- REMOTO

### Contratação:
- CLT

### Experiência

- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
