### ISSUE TITLE
[FORTALEZA]Developer PYTHON PLENO na Vector

### ISSUE THREAD

**Issue by Glaice1987** [frontendbr/vagas#5819]
> Vaga Remota durante a pandemia

## Nossa empresa

A Vector é uma empresa especializada em criação, implantação e gestão de Call Center, BPO e IA, que conta com serviços exclusivos e sob medida para atender a necessidade dos nossos clientes.

## Descrição da vaga
 Oportunidade para Desenvolvedor(a) Python Pleno

## Local

Exemplo: Remoto ou Escritório, [Fortaleza], [Fortaleza], [Centro]

## Requisitos
⦁	Graduação de nível superior completo em ciência da computação, análise de desenvolvimento de sistemas ou afins.

⦁	Conhecimento e experiência em desenvolvimento de software utilizando linguagem Python.
⦁	Conhecimento e experiência com Linguagem SQL (DDL e DML). 
⦁	Familiaridade com desenvolvimento utilizando Angular, JavaScript e HTML5 para front-end.

**Desejáveis:**

⦁	Conhecimento e experiência em desenvolvimento .NET Core. 
⦁	Conhecimento e experiência em desenvolvimento PHP. 
⦁	Conhecimento e experiência com ASP (para manutenção em sistemas legados). 
⦁	Conhecimento e experiência com desenvolvimento para Plataformas Mobile.
⦁	Conhecimento de VBScript 6 (para manutenção em sistemas legados). 
⦁	Conhecimento e experiência em projetos de Ciência de Dados. 
⦁	Conhecimento em Testes (Ferramentas, Metodologias e Processos).
⦁	Conhecimento em ferramentas de BI (preferencialmente PowerBi)

**Diferenciais:**

## Benefícios

⦁	Salário compatível com o mercado;
⦁	Plano de Saúde (Opcional);
⦁	Plano Odontológico;
⦁	Vale Transporte;
⦁	Vale Alimentação.

- ...

**Diferenciais:**

## Contratação

CLT

## Como se candidatar

Por favor envie um e-mail para rh@souvector.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor Pleno
(85)99901-5657 (Whatsapp - Glaice)

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
