### ISSUE TITLE
[São Paulo] Front-End Developer na Sciensa

### ISSUE THREAD

**Issue by machad0** [frontendbr/vagas#582]
## Descrição da vaga

Estamos em busca de profissionais que realizem a concepção e implementação de telas. O objetivo é realizar o entendimento e desenvolvimento dos produtos dos nossos clientes.

## Local

Escritório em São Paulo - Paraíso (5 min de distância da estação Paraiso)

## Benefícios

- Subsídio para Plano de saúde e Alimentação (em dinheiro)

#### Diferenciais

- Ambiente Descontraído
- Treinamentos
- Processo de Trabalho Ágil
- Plano de Carreira
- Oportunidade de Aprendizado
- Palestras e Eventos
- Trabalho em Equipe
- Projetos de Relevância
- Escritório e Notebooks de Qualidade
- Tecnologia de Ponta
- Desafios
- Reconhecimento
- Massagem
- Lounge & Vídeo Game
- Frigobar
- Cozinha

## Requisitos

**Obrigatórios:**
- GIT
- Ao menos 3 anos de experiência com Javascript
- Ao menos 3 anos de experiência HTML/CSS

**Desejáveis:**
- ES6+
- EmberJS
- React
- NodeJS
- Modelagem de Serviço (Rest)

**Diferenciais:**
- projetos pessoais e/ou opensource

## Contratação

PJ, salário a combinar

## Nossa empresa

Nós da Sciensa ajudamos as empresas a alcançar novos desafios, repensar seu modelode negócios usando a tecnologia como meio. Transformamos empresas tradicionais em Digitais, áreas de TI em Inovação e Criação. Criamos softwares poderosos com as tecnologias de ponta do Vale do Silício e construímos estratégias de negócio orientadas a software. Nós acreditamos que bem feito é melhor que bem explicado, e que o software pode trazer um incremento real no modelo de negócios das companhias. Nós somos a Sciensa, apaixonados por desenvolvimento de software, uma boutique de software com os melhores talentos do país.

## Como se candidatar

É só se inscrever por esse formulário aqui: https://sciensa.recruitee.com/o/frontend-developer-sao-paulo

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
