### ISSUE TITLE
[SÃO PAULO] Front-end Developer Sênior (React) na Quero 2 Pay

### ISSUE THREAD

**Issue by Mariadafne** [frontendbr/vagas#5821]
## Nossa empresa 💙

Faça parte de uma das fintechs que **mais crescem** no Brasil! 🚀

Somos uma **fintech** que oferece tecnologia de pagamentos para alavancar negócios. Ajudamos lojistas a vender mais e facilitamos o acesso aos recebíveis. Estamos criando um novo ecossistema em que nossos clientes compartilham de nossos ganhos e crescimento.

## Descrição da vaga 📊

Precisamos de desenvolvedores que queiram atuar de **forma disruptiva**, com objetivo de mudar o mercado de meios de pagamentos. Este profissional deverá estar sempre em busca de crescimento, tanto pessoalmente como de seus pares. É importante ser proativo e ter um ótimo comportamento trabalhando em **times de alta performance**. Se você é uma pessoa que ama código, ama tecnologia, adora criar soluções inovadoras e quer construir um grande projeto de carreira, **esta vaga é para você!**

## Local

São Paulo - Franca

## Requisitos

**Obrigatórios:**
- Dominio da linguagem React
- Conhecer HTML5, CSS, JS, ES5, ES6, Javascript Vanilla
- Javascript Template Engines, Javascript Framework
- Pré-processadores CSS (SASS, Less, PostCSS)
- Experiência com alguma metodologia atual de padrões de CSS/HTML (BEM, Atomic, outros)
- Criação de código limpo, legível e cross-browser. Nossa régua é IE8+
- Experiência com desenvolvimento de sites responsivos
- Conhecimento em API RESTful
- Experiência com controle de versão usando GIT
- Conhecimento em padrões de design e arquitetura de código (Clean architecture, Microservices)
- Experiência em desenvolvimento ágil de projetos (vivência em metodologias ágeis – Scrum, Kanban ou outros)
- Produzir documentação de alta qualidade.

**Diferenciais:**
- Continuous Integration e Continuous Deployment
- Desenvolvimento orientado a testes (mochajs, jasmine, jest
- Experiência com UI e UX
- Experiência com ambiente cloud (especialmente AWS, GCP)
- Conhecer NodeJs, Angular, Dust, Vue.js
- Usabilidade e padrões de web design

## Contratação

PJ 

## Como se candidatar

Para se candidatar e/ou saber mais sobre a vaga, acesse: **https://bit.ly/3BbFNOe**

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
