### ISSUE TITLE
[São Paulo/ Barueri]Desenvolvedor FullStack (ANGULAR e NODE JS) @ddrtech.com.br 

### ISSUE THREAD

**Issue by Douglasdechiare** [frontendbr/vagas#5822]
Sobre a empesa: 

Somos uma empresa especializada no fornecimento de Soluções de CRM - Customer Relationship Management e Ominichannel – integração de canais de voz, chat e mídias digitais, com larga experiência em customização e integração de soluções.

Sobre a nossa Plataforma: 

•	Nossa plataforma chamada Blueone (B1) tem como o objeto de fazer o gerenciamento e controle de toda a jornada de uma interação & atendimento de um cliente;
•	A plataforma Blueone (B1) é moderna, com UX/UI elaborado, trazendo rápido aprendizado aos usuários, com estrutura de dados 100% em Cloud;
•	A plataforma Blueone (B1) oferece flexibilidade de customização e escalabilidade de processos monitorados, através de alertas e workflow de regras de negócios;
•	A plataforma Blueone (B1) hoje é utilizada por grandes clientes no Brasil e nos USA. 

Descrição da Vaga: 

Desenvolvedor FullStack (ANGULAR e NODE JS).

Buscamos pessoas que estão em busca de aprender constantemente e aprimorar suas habilidades com desenvolvimento de Software. Foco em inovação e tecnologia. 

Responsabilidades e atribuições
	Trabalhar com metodologia ágil (SCRUM);
	Utilizar boas práticas de desenvolvimento e documentação;
	Desenvolver e dar manutenção nas features do projeto;
	Excelentes habilidades de comunicação e trabalho em equipe;
	Ótima atenção aos detalhes;
	Habilidades organizacionais;
	Mente analítica;
	Formação em Ciência da Computação, Estatística ou área relacionada

Qualificação
	Experiência comprovada como desenvolvedor full stack ou função similar
	Familiaridade com os conjuntos de tecnologia (“tech stacks”) mais comuns.
	Conhecimento de múltiplas linguagens de front-end e bibliotecas (Angular, React, HTML/ CSS e JavaScript);
	Conhecimento de múltiplas linguagens back-end (Node.js)
	Familiaridade com bancos de dados (Postgres, MongoDB);
	Docker;
	Github
	AWS Cloud
	API 
	Microservices

Nossos benefícios:
	Contratação PJ a combinar + Benefícios, presencial ou 100% home office;  
	Aprendizado contínuo;
	Avaliação estruturada;
	Acompanhamento de carreira;
	Oportunidade de transição de carreira;

## Como se candidatar

Por favor envie um email para ddr@ddrtech.com.br com seu CV anexado - enviar no assunto: Vaga FullStack

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
