### ISSUE TITLE
[REMOTO] Estágio na Imagem Geosistemas

### ISSUE THREAD

**Issue by luanasantosog** [frontendbr/vagas#5823]
## Nossa empresa

Nosso Programa de Estágio 2022 está oficialmente aberto!

Ajudamos empresas e governos a construírem um futuro de sucesso e liderança, e para isso contamos com um time brilhante de pessoas singulares e protagonistas, trabalhando em máxima sinergia. Agora, queremos você ao nosso lado, também.
Somos uma empresa brasileira de tecnologia líder em Sistemas de Informações Geográficas, distribuidora oficial no Brasil da plataforma ArcGIS, da norte-americana Esri.

Há 35 anos ajudamos nossos clientes a visualizar, questionar, analisar e interpretar atributos dos dados através de apps, funcionalidades, dashboards e mapas.

Somos certificados pelo GPTW como um “Excelente Lugar para Trabalhar”, o que significa que nos importamos com a nossa equipe e trabalhamos duro para que o clima na empresa seja sensacional!

## Local

Remoto.

## Requisitos

**Quais as habilidades e conhecimentos você precisa ter para fazer parte da nossa empresa?:**
- Estar matriculado em alguns desses cursos de graduação:
Engenharia da Computação, Ciência da Computação, Redes, Análise e Desenvolvimento de Sistemas, Gestão da Tecnologia da Informação, Banco de dados, Sistemas de Informação e cursos afins;
Administração, Economia, Ciências Atuariais, Gestão Comercial e cursos afins;
Marketing, Publicidade e Propaganda, Jornalismo, Design e cursos afins.
- Ter previsão de conclusão da graduação entre julho de 2023 a julho de 2024;
- Desejável possuir inglês técnico ou intermediária;

**Soft skills:**
- gostar de aprender, proatividade, protagonismo, comunicação clara, facilidade de estabelecer conexões com outras pessoas.

Bora se inscrever?

## Benefícios

- Plano de saúde
- Seguro de vida
- VR
- Auxílio Home Office
- Bolsa Auxílio

**Diferenciais:**
- Mentoria
- Horário flexível e trabalho hibrido 
- Um ambiente de trabalho saudável e humanizado, com espaço para inovação e autenticidade;

## Contratação

Estágio

## Como se candidatar

E aí, se interessou?
Acesse o link https://bit.ly/3FhLIn5 para conferir mais informações e se inscrever!

#### Alocação
- Remoto

#### Regime
- Estágio

#### Nível
- Júnior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
