### ISSUE TITLE
[São Paulo] Front-End Game Developer na PushStart

### ISSUE THREAD

**Issue by wnitsch** [frontendbr/vagas#583]
## Descrição da vaga
Nós estamos procurando um(a) programador(a) que tenha experiência com JavaScript e que queira programar games. 

#### O que você fará aqui
•	Codificar;
•	Ler e entender os requisitos;
•	Fazer gestão das próprias tarefas e reportar de forma clara;
•	Trabalhar em equipe com outros programadores, designers e artistas;
•	Estar atento a qualidade do produto e do código;
•	Conversar com clientes e parceiros (em inglês);
•	Propor melhorias de processo e ferramentas utilizadas;

## Local
São Paulo - Lapa

## Benefícios

•	CLT Full;
•	Vale-Refeição / Vale-Alimentação (R$25/dia);
•	Vale-Transporte;
•	Convênio Médico Bradesco Saúde;
•	Convênio farmácia;

#### Diferenciais

•	Ambiente e dress-code descontraídos;
•	Vídeo-game / HTC Vive
•	Snacks

## Requisitos

**Obrigatórios:**
•	Formado em Ciência da Computação, Engenharia de Computação ou áreas relacionadas;
•	Experiência profissional em codificação JavaScript;
•	Experiência em ferramentas de controle de versão;
•	Inglês avançado (escrita e conversação);
•	Disponibilidade para trabalhar fisicamente em São Paulo/SP;

**Desejáveis:**
•	PIXI.JS
•	GSAP
•	ES6

**Diferenciais:**
Conhecimento em algumas das tecnologias:
•	Node
•	TypeScript
•	GSAP
•	Frameworks modernos (angular, react, vue, aurelia...)
•	React-native
•	Webpack
•	Firebase

## Contratação

CLT-Full

## Nossa empresa
A PushStart é um estúdio de conteúdo interativo! Criamos Games, Apps, Sites, Animações.... Somos apaixonados por inovação e desafios! Trabalhamos com projetos empolgantes e divertidos! 
A PushStart é um estúdio dinâmico e procuramos quem queira crescer com a gente!

## Como se candidatar

Por favor envie um email para jobs@pushstart.com.br com seu CV anexado - enviar no assunto: Vaga Game JS

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
