### ISSUE TITLE
[REMOTA] Senior Front-end Developer (Design Systems) na Datum (Projeto Renner)

### ISSUE THREAD

**Issue by sofia-kroeff** [frontendbr/vagas#5838]
> Vaga Remota 

## Nossa empresa

Sua stack é desenvolver front-end? A @Datum quer adicionar você!

Na nossa rede você encontra:

Pessoas conectadas na vida real;
Inovação que vai além das telas;
Um mundo cheio de desafios;
Ética e transparência nas relações;
Ambiente ágil, do tipo visualizado e respondido! 😉

## Descrição da vaga

Você pode se conectar com a oportunidade se possuir experiência em:

Este perfil ficara responsável pelo planejamento, execução e desenvolvimento no Design System de um de nossos clientes. Irá atuar em conjunto a equipes de design e UX para construção de novos componentes e também em conjunto com outras squads as quais irão utilizar o Design System, mantendo contado direto para coletar feedback e melhorias necessárias.

Este perfil participa ativamente do processo de planejamento e criação dos componentes que compõem o nosso Design System, auxiliando na tomada de decisões e garantindo a qualidade do desenvolvimento desde a concepção do componente até a sua entrega e correções de possíveis problemas. Além disto esta pessoa também auxiliará em provas de conceitos de novas ideias que podem ajudar o produto a crescer ainda mais de forma escalável e performática.

## Local

Exemplo: Remoto

## Requisitos

**Obrigatórios:**
Experiência comprovada em ReactJS com Typescript
Sólidos conhecimentos HTML, CSS e JS (Utilizamos a lib Emotion)
Conhecimento sobre a ferramenta Storybook
Conhecimento sobre publicação de pacotes NPM
Conhecimento em ferramentas de bundle (webpack/rollupjs)
Conhecimento básico em arquitetura de monorepo com yarn workspaces
Conhecimento básico CI/CD (gitlab)
Consistência e qualidade de código
Capacidade de tomada de decisões

**Desejáveis:**
Experiência com metodologias ágeis
Test Driven Development (TDD)
Análises de performance em componentes ReactJS
Já trabalhou em produtos que possuem Design System

## Benefícios

Vale transporte
Vale refeição/alimentação
Auxílio Home Office
Gympass
Plano de saúde
Plano odontológico
Seguro de vida
Cíngulo (saúde mental)
Assessoria financeira, jurídica e psicológica para funcionários
 
Aqui na Datum, você também vai ter:

Protagonistas (game de incentivo à carreira do colaborador)
Datum Academy (programa de capacitação e treinamentos)
English Class
Ginástica Laboral
Rock Leader (programa de formação de liderança)
+Felicidade (iniciativa que visa a felicidade do colaborador)
**Diferenciais:**
- 2 horas de almoço

## Contratação

PJ, CLT ou Cooperado

## Como se candidatar

https://datum.gupy.io/jobs/1159538?jobBoardSource=gupy_public_page

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: sofia.kroeff@datum.inf.br

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ
- Cooperado

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
