### ISSUE TITLE
[Rio de Janeiro] Estágio Front-end na Marlin

### ISSUE THREAD

**Issue by perlalima** [frontendbr/vagas#584]
## Descrição da vaga
Estamos à procura de estagiário de front-end com o seguinte perfil para integrar a nossa equipe.
• Cursando Ciência da Computação, Sistemas para Internet, Análise de Sistemas ou áreas relacionada a Tecnologia.

## Local
Centro, Rio de Janeiro

## Benefícios
Bolsa à combinar, VT e VR

## Requisitos
- HTML5/ CSS3
- JAVASCRIPT
- Conhecimento WEBSTANDARDS
- Validação de documentos de requisitos

## Noções
- Framework JS ( JQuery ou Knockout ou AngularJS)
- Framework CSS (Bootstrap ou Foundation)
- Framework CMS (Wordpress ou Drupal)
- MVC Visual Studio
- Linguagem de programação (PHP, C#)
- Photoshop

## Aspectos comportamentais
Organizado, responsável, comprometido, pontual, ter boa comunicação verbal e escrita, saber trabalhar em equipe, atencioso, vontade constante de aprender e melhorar suas técnicas, calmo para lidar com momentos de cobrança de resultados

## Como se candidatar

Acesse http://www.marlin.com.br/faca-parte, preencha o formulário e envie o seu currículo e/ou portfólio.

labels: estágio, alocado

**Comment by antoniotex** [comment]
Enviado 👍

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
