### ISSUE TITLE
[Remoto] [Internacional] Scala Developer na BHS

### ISSUE THREAD

**Issue by vvoa99** [frontendbr/vagas#5853]
> Vaga 100% remota

## Nossa empresa
Nós somos a BHS!

Reconhecida desde 2015 como uma das melhores empresas para se trabalhar, temos mais de 25 anos de experiência e oferecemos soluções modernas de TI..

## O que a gente espera de você?

Buscamos uma pessoa de fácil relacionamento, com boa comunicação, que seja curioso, goste de pensar fora da caixa e trabalhar em equipe. Alguém que queira fazer parte de projetos incríveis e tenha muita vontade de aprender, ensinar e crescer junto com a BHS

**Buscamos uma pessoa que possua experiências com:**
- TDD (Test Driven Development) 

- Microsserviços

- Akka

- ElasticSearch

- Cassandra

- MongoDB

- RabitMQ

- Postgresql.

- Inglês avançado ou fluente

**Será um diferencial se possuir conhecimento em:**
- Ecossistema Typelevel

- Cats, http4s, fs2, doobie, etc.
## O que você pode esperar de nós?

- Plano de saúde Unimed;

- Assistência Odontológica

- Vale transporte ou auxílio no estacionamento.

- Vale Refeição, sem desconto

- Incentivo para Pós-Graduação, Especializações e MBA’s;

- Incentivo de certificações que você for aprovado;

- Incentivo a treinamentos;

- Incentivo ao curso de inglês

- Parcerias e convênios diversos

- Licença Maternidade/Paternidade estendida

- PLR

- Programas de conteúdo, como o Deu Match!, e uma rotina com aprendizado constante

## Como se candidatar

Basta se inscrever na nossa página de carreiras: https://jobs.kenoby.com/bhs/job/scala-developer/61433fb6024c594d542b3eea?utm_source=website

#### Modo de trabalho
- Alocado
- Remoto
- CLT

#### Níveis Desejáveis
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
