### ISSUE TITLE
[Fortaleza] Developer BI Sênior na VECTOR

### ISSUE THREAD

**Issue by Glaice1987** [frontendbr/vagas#5854]
> Vaga Remota durante a pandemia

## Nossa empresa

A Vector é uma empresa especializada em criação, implantação e gestão de Call Center, BPO e IA, que conta com serviços exclusivos e sob medida para atender a necessidade dos nossos clientes.

## Descrição da vaga

Desenvolvedor(a) BI Sênior

## Local

Presencial [Ceara], [Fortaleza], [Fátima]

## Requisitos

**Obrigatórios:**
- Graduação Nível superior completo em ciência da computação, analise de desenvolvimento de sistemas ou afins;
- Experiência anterior na função.
- Conhecimento em linguagens de programação para IA;
- Conhecimento em ciência de dados e BI;
- Conhecimento em ferramentas de extração, transformação e carga de dados.

## Benefícios

- Salário compatível com o mercado;
- Plano de Saúde(Opcional)
- Plano Odontológico
- Vale transporte
- Vale Alimentação
- ...

## Contratação

CLT

## Como se candidatar

Por favor envie um email para rh@souvector.com.br  com seu CV anexado - enviar no assunto: Desenvolvedor BI Sênior
Whatsapp: (85)99901-5657

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível

- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
