### ISSUE TITLE
[Remoto] [Internacional] Developer Sênior na BHS

### ISSUE THREAD

**Issue by vvoa99** [frontendbr/vagas#5855]
## Nossa empresa

Nós somos a BHS!

Reconhecida desde 2015 como uma das melhores empresas para se trabalhar, temos mais de 25 anos de experiência e oferecemos soluções modernas de TI.

## O que a gente espera de você?

Buscamos uma pessoa de fácil relacionamento, com boa comunicação, que seja curioso, goste de pensar fora da caixa e trabalhar em equipe. Alguém que queira fazer parte de projetos incríveis e tenha muita vontade de aprender, ensinar e crescer junto com a BHS.

**Buscamos uma pessoa que possua experiências com:**
-  3 anos com desenvolvimento de produto;

- Desenvolvimento de software utilizando programação orientada a objetos;

- Desenvolvimento em C++/C;

- Conhecimento de programação/API em um dos, e familiaridade geral com os sistemas operacionais: Linux, Microsoft Windows;

- Controle de versão de código, como SVN ou Git;

 - Práticas Agile (Scrum, Kanban, etc.); 

- Inglês avançado ou fluente

**Será um diferencial se possuir conhecimentos em:**

- Desenvolvimento uma ou mais das tecnologias: Python, C#/.NET, Web/HTML/JS/React;

- Redes IP e protocolos de comunicação (TCP, UDP etc.);

- Testes unitários e teste de integração;

- Sistemas georreferenciados;

- Tópicos em robótica móvel;

- Middleware ROS;

- Plataformas de simulação V-REP, Gazebo, etc.;

- Desenvolvimento de jogos (Unreal, Unity, etc.);

- Modelagem de cenas/objetos 3D;

- Formação técnica em eletrônica/automação e afins

## O que você pode esperar de nós?

- Plano de saúde Unimed;

- Assistência Odontológica

- Vale transporte ou auxílio no estacionamento.

- Vale Refeição, sem desconto

- Incentivo para Pós-Graduação, Especializações e MBA’s;

- Incentivo de certificações que você for aprovado;

- Incentivo a treinamentos;

- Incentivo ao curso de inglês

- Parcerias e convênios diversos

- Licença Maternidade/Paternidade estendida

- PLR

- Programas de conteúdo, como o Deu Match!, e uma rotina com aprendizado constante

## Modalidade Trabalho
- Contratação CLT
- Alocado
- Remoto

## Como se candidatar

Basta se candidatar na nossa página de carreiras: https://jobs.kenoby.com/bhs/job/developer-senior/6155c93ed0267c41fea8b782?utm_source=website

## Labels
- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ CLT
- 🌎 Oportunidade Internacional

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
