### ISSUE TITLE
[Remoto] Pessoa Desenvolvedora Front-end Javascript  Sênior na BHS

### ISSUE THREAD

**Issue by vvoa99** [frontendbr/vagas#5856]
## Empresa
 Nós somos a BHS!

Reconhecida desde 2015 como uma das melhores empresas para se trabalhar, temos mais de 25 anos de experiência e oferecemos soluções modernas de TI.

## O que a gente espera de você?
Buscamos uma pessoa de fácil relacionamento, com boa comunicação, que seja curioso, goste de pensar fora da caixa e trabalhar em equipe. Alguém que queira fazer parte de projetos incríveis e tenha muita vontade de aprender, ensinar e crescer junto com a BHS.

###### Buscamos uma pessoa que possua experiências com:
-  Desenvolvimento de sistemas Front End (HTML5, CSS3, SASS, ReactJS , Javascript ou Typescript)

- Plataforma Vtex / Portal CMS / Vtex IO

- Utilização de nuvem ( AWS, Azure, etc )

- Sistemas de alta disponibilidade

- Integrações com serviços web / APIs: (SOAP / REST)

- Testes Unitários

- Integração Contínua

- Design Patterns

- Atuar dentro da metodologia ágil

-Conhecimento em delivery contínuo

-Controle de Versão: Git, GitFlow

- Experiência de +5 anos com desenvolvimento de software

###### Será um diferencial se possuir algum conhecimento em:
-  Testes automatizados

- Outras linguagens de programação (AWS, Azure, NodeJS, Java, etc)

- Experiência prévia com portais ou sistemas de ecommerce

- Conhecimentos em TDD

- Noções de programação back-end (NodeJS)

- AngularJS

- React Native

- UX/UI Design

## O que você pode esperar de nós?
- Plano de saúde Unimed;

- Assistência Odontológica

- Vale transporte ou auxílio no estacionamento.

- Vale Refeição, sem desconto

- Incentivo para Pós-Graduação, Especializações e MBA’s;

- Incentivo de certificações que você for aprovado;

- Incentivo a treinamentos;

- Incentivo ao curso de inglês

- Parcerias e convênios diversos

- Licença Maternidade/Paternidade estendida

- PLR

- Programas de conteúdo, como o Deu Match!, e uma rotina com aprendizado constante

## Como aplicar
Basta de inscrever na nossa página de carreira: https://jobs.kenoby.com/bhs/job/pessoa-desenvolvedora-front-end-java-script-senior/612fb1f174a0bf6b5320ce64?utm_source=website

## Modo de trabalho
- CLT
- Alocado
- Remoto

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
