### ISSUE TITLE
[São Paulo] Front-End Developer na IBM

### ISSUE THREAD

**Issue by guto-gomes** [frontendbr/vagas#586]
## Descrição da vaga

Projeto tempo indeterminado

## Local

Escritório, São Paulo - Vila Olímpia

## Benefícios

Vale Refeição - 25 reais por dia
Vale Alimentação - 230 reais por mês
Seguro de Vida
Plano de Saúde Bradesco
Plano Dentário Saúde Bradesco
Cartão Vidalink - Melhor benefício rsrs, cartão que dá desconto de até 80% em remédios com receita.

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Front

**Desejáveis:**
- Angular

**Diferenciais:**
- projetos opensource

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um email para augusto.gomes@br.ibm.com seu CV anexado - enviar no assunto: Vaga Front End

**Comment by ericprieto** [comment]
"ibm.comcom", tá certo isso?

**Comment by guto-gomes** [comment]
@ericprieto obrigado, alterado

**Comment by nandosangenetto** [comment]
O que seria "Muitosssss"?

**Comment by guto-gomes** [comment]
@nandosangenetto 

Vale Refeição - 25 reais por dia
Vale Alimentação - 230 reais por mês
Seguro de Vida
Plano de Saúde Bradesco
Plano Dentário Saúde Bradesco
Cartão Vidalink - Melhor benefício rsrs, cartão que dá desconto de até 80% em remédios com receita.

Quem trabalha em alguns clientes tem ajuda de custo de 299 reais com transporte.

Ufa acho que é isso, ahhh e tem um previdência da IBM que vale muito a pena também.

**Comment by LFeh** [comment]
@guto-gomes adicionei na descrição ;)

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
