### ISSUE TITLE
[Rio de Janeiro] Front-End Developer na IBLUE CONSULTING

### ISSUE THREAD

**Issue by linikerdev** [frontendbr/vagas#587]
## Descrição da vaga

Oportunidade de trabalhar em projetos inovadores, com novas tecnologias para desenvolvimento de aplicações web e mobile.

## Local

Escritório, Rio de Janeiro - Centro

## Benefícios

- Plano de saúde
- Plano Odontológico
- VR
- VT

## Diferenciais

- Ambiente ótimo (pode bermuda)
- frigobar liberado após as 16h (quinta e sexta)

## Requisitos

**Obrigatórios:**

- ionic 2x e 3x
- WebPack
- Cordova
- Phonegap
- NodeJs
- Mongodb e express
- Angular 2x e 4x

**Desejáveis:**
- conhecimentos em React
- Conhecimento em AWS (S3, Lambda, Kinesis, SQS, SNS, etc.)
- Vontade de aprender novas tecnologias

## Contratação

PJ ou CLT

## Como se candidatar

Por favor envie um email para rhrio@iblueconsulting.com.br com seu CV anexado - enviar no assunto: Vaga Front-End Developer in GitHub

**Comment by LFeh** [comment]
É para trabalhar na IBlue Consulting?

**Comment by linikerdev** [comment]
Sim, trabalhar aqui no escritório no RJ.
