### ISSUE TITLE
[São Paulo] Front-End Developer no Banco Pine

### ISSUE THREAD

**Issue by CristianeChapin** [frontendbr/vagas#588]
DISYS, LLC é uma consultoria global de serviços com mais de 20 anos de atuação e presença em 
mais de 35 países,está contratando profissionais para atuar como desenvolvedor em um projeto 
com duração prevista de 3 a 4 meses e possibilidade de ser estendido. 

O profissional será responsável pela manutenção e sustentação de sistemas. 
 
Requisitos: 
Necessário conhecimento em Vue.JS, Javascript, CSS, HTML 
Experiência em SPA (Single Page Application). 
 
Início Imediato 

Local: Pinheiros (Ao lado do shopping Eldorado)-Horário Segunda a Sexta – Horário Comercial 

Contratação Pessoa Jurídica

Por favor encaminhar currículo com CNPJ e pretensão salário hora para: cristiane.chapin@disys.com

Venha fazer parte desse time!

**Comment by felipecesr** [comment]
Não seria Back-End Developer?

**Comment by valniria** [comment]
Esse email está correto?

**Comment by CristianeChapin** [comment]
Front-End

Cristiane Chapin
HR Analyst
Digital Intelligence Systems, LLC (DISYS)
Alameda Santos, 2480 – 5º Andar / Conjunto 52
São Paulo/ SP / 01418-200
+ 55 (11) 4766-3036 | www.disys.com<http://www.disys.com/>
Skype ID: cristianechapin

[cid:image001.png@01CE1699.6FF81620]<http://www.disys.com/>[cid:image002.png@01CE1699.6FF81620]<https://www.facebook.com/DISYS>[cid:image003.png@01CE1699.6FF81620]<http://www.youtube.com/disysglobal>[cid:image004.png@01CE1699.6FF81620]<http://www.linkedin.com/company/disys>[cid:image005.png@01CE1699.6FF81620]<https://twitter.com/disysglobal>

De: Felipe César [mailto:notifications@github.com]
Enviada em: sexta-feira, 6 de outubro de 2017 16:32
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: Chapin, Cristiane de Oliveira <Cristiane.Chapin@DISYS.COM>; Author <author@noreply.github.com>
Assunto: Re: [frontendbr/vagas] Front-End Developer (#588)


Não seria Back-End Developer?

**Comment by CristianeChapin** [comment]
Sim

Cristiane Chapin
HR Analyst
Digital Intelligence Systems, LLC (DISYS)
Alameda Santos, 2480 – 5º Andar / Conjunto 52
São Paulo/ SP / 01418-200
+ 55 (11) 4766-3036 | www.disys.com<http://www.disys.com/>
Skype ID: cristianechapin

[cid:image001.png@01CE1699.6FF81620]<http://www.disys.com/>[cid:image002.png@01CE1699.6FF81620]<https://www.facebook.com/DISYS>[cid:image003.png@01CE1699.6FF81620]<http://www.youtube.com/disysglobal>[cid:image004.png@01CE1699.6FF81620]<http://www.linkedin.com/company/disys>[cid:image005.png@01CE1699.6FF81620]<https://twitter.com/disysglobal>

De: Valniria Bandeira [mailto:notifications@github.com]
Enviada em: sexta-feira, 6 de outubro de 2017 16:34
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: Chapin, Cristiane de Oliveira <Cristiane.Chapin@DISYS.COM>; Author <author@noreply.github.com>
Assunto: Re: [frontendbr/vagas] Front-End Developer (#588)


Esse email está correto?

**Comment by LFeh** [comment]
É para trabalhar na propria DISYS, LLC?

**Comment by simaodeveloper** [comment]
@LFeh pede por favor pede para alterarem o título da vaga conforme as demais, exemplo:  [Cidade/Estado] <Nome da vaga> na <nome da Empresa>

**Comment by CristianeChapin** [comment]
É para trabalhar em um cliente da Disys em um projeto. A atuação é em Pinheiros.

Atenciosamente,
Cristiane Chapin
HR Analyst
Digital Intelligence Systems, LLC (DISYS)
Alameda Santos, 2480 – 5º Andar / Conjunto 52
São Paulo/ SP / 01418-200
+ 55 (11) 4766-3036 | www.disys.com<http://www.disys.com/>
Skype ID: cristianechapin

[cid:image001.png@01CE1699.6FF81620]<http://www.disys.com/>[cid:image002.png@01CE1699.6FF81620]<https://www.facebook.com/DISYS>[cid:image003.png@01CE1699.6FF81620]<http://www.youtube.com/disysglobal>[cid:image004.png@01CE1699.6FF81620]<http://www.linkedin.com/company/disys>[cid:image005.png@01CE1699.6FF81620]<https://twitter.com/disysglobal>

De: Felipe Fialho [mailto:notifications@github.com]
Enviada em: segunda-feira, 9 de outubro de 2017 11:22
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: Chapin, Cristiane de Oliveira <Cristiane.Chapin@DISYS.COM>; Author <author@noreply.github.com>
Assunto: Re: [frontendbr/vagas] Front-End Developer (#588)


É para trabalhar na propria DISYS, LLC?

**Comment by LFeh** [comment]
@simaodeveloper Primeiro preciso descobrir se a vaga vai continuar ativa. Preciso do nome do cliente :)

**Comment by CristianeChapin** [comment]
O cliente é o Banco Pine.

**Comment by LFeh** [comment]
Beleza ;)

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
