### ISSUE TITLE
[Porto Alegre/Remoto] Front-end Developer na Ubots

### ISSUE THREAD

**Issue by keyllagaitkoski** [frontendbr/vagas#5888]
**Descrição**

A Ubots é uma empresa que desenvolve soluções que propiciam experiências de marca incríveis. Para isso, estamos procurando desenvolvedores que saibam escrever um bom código (clean code) e possuam experiência com desenvolvimento ágil para compor o nosso time. Buscamos bons desenvolvedores mais que especialistas em linguagens e frameworks.
A oportunidade é para trabalhar com chatbots e produtos de software que aplicam inteligência artificial.

**Seu dia-dia será:**

- Vai participar da concepção de novas funcionalidades e da arquitetura dos softwares.
- Irá atuar com projetos web e front-end
- Escrever código reutilizável, testável e eficiente
- Concepção e implementação de aplicações de baixa latência, alta disponibilidade e desempenho

**Você terá a oportunidade de, entre outras tecnologias, trabalhar com:**

- Javascript/NodeJS
- AWS
- Ansible
- Git
- Postgresql
- Docker
- Redis
- AngularJS e React

**O que buscamos**

- Conhecimento sólido em NodeJS e Javascript
- ﻿Experiência de trabalho no desenvolvimento de webapps escaláveis;
- Pessoas com curiosidade e vontade de aprender novas ferramentas, plataformas e tecnologias

**E quais são os benefícios?**

- Anywhere office: política totalmente flexível de contratação em outros Estados, Regiões e Países para trabalho full remoto;
- Onboarding de boas vindas!! =)
- Dress Code: trabalhe como se sentir melhor;
- Ambiente dinâmico, diverso e inclusivo;
- Time que valoriza o feedback e o desenvolvimento profissional;
- Benefício flexível Flash
- Plano de saúde nacional;
- Saúde emocional e suporte psicológico;
- Auxílio mensal para despesas AnywhereOffice;

**Resumo da Vaga**
Home Office: Sim
Tipo de Contrato: A Combinar
Plano de saúde: Sim
Auxílio Home Office: Sim
Flexibilidade de horários: Sim

Quer fazer parte de uma das melhores startups de Customer Service do Brasil que não para de crescer? Então essa oportunidade é para você! 💛

**Enviar currículo para oportunidades@ubots.com.br
Conheça um pouco mais sobre a Ubots: [Nosso site](https://ubots.com.br/)**

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
