### ISSUE TITLE
[REMOTO] Front-end Developer na @Conta Simples

### ISSUE THREAD

**Issue by Contasimples** [frontendbr/vagas#5890]
> VAGA REMOTA

## A CONTA SIMPLES
Gestão de despesas e conta corrente em um só lugar, com plataforma inteligente de múltiplos cartões. Feita para as empresas da nova economia assumirem o controle dos gastos e ganhar eficiência nas operações do dia a dia.
Somos, atualmente, uma das melhores empresas para se trabalhar no Brasil. Fomos certificados com o selo Great Place to Work! Além de reconhecida como uma das melhores pelos nossos Simplers, a Conta Simples é também uma das scale-ups que mais se destaca no cenário de fintechs voltadas para empresas. Conquistamos o reconhecimento como a segunda startup brasileira a ser investida pela Y Combinator, estamos na lista das 100 Startups to Watch (PEGN) e entre as 50 Startups que mudam o Brasil (Exame).
www.contasimples.com

## Descrição da vaga
Contribuir com o time na implementação de boas práticas de desenvolvimento e code design;
Definir e implementar a melhor arquitetura para novos projetos e melhorias nos projetos atuais;
Colaborar com a melhoria contínua dos nossos processos de desenvolvimento, bem como na melhoria da nossa arquitetura nas aplicações web;
Colaborar com a execução e sugerir melhorias em nossos processos ágeis.

## Local

REMOTO

## Requisitos

- Proficiência em POO (conhecimento em Javascript e react);
- Sólidos conhecimentos em desenvolvimento de testes automatizados utilizando frameworks (como Jest, Testing Library, Jasmine, Mocha, etc;);
- Conhecimento de boas práticas de desenvolvimento de software (design patterns, SOLID, Clean code);
- Conhecimentos de cloud computing (desejável AWS) e arquitetura serverless;
- Conhecimentos em diferentes protocolos de comunicação e sólidos conhecimentos no protocolo HTTP e API Rest.

**Diferenciais:**
- Experiência em empresas em alto crescimento.

## Benefícios

- VR + VA
- Plano de Saúde (rede nacional, acomodação apartamento, sem desconto de mensalidade e sem coparticipação para o titular e + 2 dependentes);
- Plano Odontológico sem custos (rede nacional);
- Gympass e TotalPass;
- Auxílio creche para recém nascidos.

**Diferenciais:**
- Day off no aniversário;
- 1 day off por mês.

## Contratação

- PJ flex (com direito a 30 dias de férias remuneradas)

## Como se candidatar

Favor enviar o seu cv por email: vagas@contasimples.com com o assunto: [NOME VAGA] + GITHUB

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05/10 dias após cada processo.
E-mail para contato em caso de não haver resposta: vagas@contasimples.com

#### Alocação
- Remoto

#### Regime
- PJ FLEX

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
