### ISSUE TITLE
[Remoto] Fullstack Developer na Pling

### ISSUE THREAD

**Issue by felipekm** [frontendbr/vagas#5892]
A [PLING](https://pling.pro/) é uma startup focada em plataforma e comunidades para o mundo da saúde.

## Descrição da vaga

Vaga para Fullstack developer para atuação em diversos projetos distribuídos que utilizam diversas tecnologias, trabalhando conosco você terá acesso a tecnologias como:

* NodeJS
* ReactJS/NextJS
* Golang
* Linux
* AWS Services (ACM, Cloudfront, CodeDeploy, EC2, Lambda, Route53, S3)
* MongoDB
* PWA
* Docker
* Elasticsearch
* IMAP/STMP Server
* RabbitMQ
* Git/Github

## Requisitos

**Obrigatórios**

- Experiência em HTML, CSS e  javasript;
- Mínimo de 3 anos de experiência com desenvolvimento de softwares;
- Experiência com Reactjs ou outro framework Javascript;
- Experiência com Rest Apis;

**Requisitos adicionais**

- Conhecimentos em MongoDB, RabbitMQ e/ou Elasticsearch;
- Conhecimentos em Shell e Linux;

## Contratação

- PJ;

## Como se candidatar

**Envie um email para**: recrutamento@pling.pro com seu CV anexado.
**Enviar no assunto**: Vaga Fullstack Pleno/Sênior.

Tempo máximo de resposta: 2 dias úteis

## Labels

- PJ
- Home office full
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
