### ISSUE TITLE
[REMOTO] Front-end Developer na Atonit Digital

### ISSUE THREAD

**Issue by bruniatonit** [frontendbr/vagas#5894]
## Nossa empresa

A Atonit é uma startup que entrega experiências digitais inovadoras através de 3 pilares:

- atonit.academy - Nossa área de capacitação de pessoas

- atonit.agency - Nossa área de projetos de Customer Experience

- atonit.labs - Nossa área de produtos, onde criamos soluções customizadas na plataforma Salesforce.

Nosso principal produto é uma plataforma de gestão de marketplace que conecta varejistas ao e-commerce dos nossos clientes.

Além disso, temos uma visão inovadora sobre como administrar empresas: Todos podem tomar qualquer decisão.

Valorizamos e confiamos nas pessoas e queremos construir juntos a melhor empresa de tecnologia para se trabalhar.

## Descrição da vaga

Fará parte do seu dia-a-dia desenvolver, escrever testes e documentar o front-end de websites responsivos (sempre sendo bem cuidadoso em relação ao layout proposto), fazer estimativas, analisar layouts (de forma a identificar possíveis problemas de implementação e/ou usabilidade) e trazer melhorias para o nosso fluxo de trabalho (como um todo, mas em especial, voltado ao front-end).

Além disso, você participará de palestras / treinamentos (assim como poderá preparar e apresentar os seus) e reuniões em conjunto com a equipe técnica, revisará o código de outros desenvolvedores e (potencialmente) tomará muito café. :)

Valorizamos pessoas que saibam trabalhar em equipe, comprometidas, e que queiram crescer em uma empresa.

Se viu nessa descrição? Então, venha fazer parte do time Atonit!

## Local

Home Office (mesmo pós pandemia)

## Requisitos

**Obrigatórios:**
- Atuação como front-end por pelo menos 3 anos;

- Experiência em desenvolvimento front-end + codificação de layout responsivos utilizando pré-processadores (sass, stylus e less);

- Experiência em automação de tarefas utilizando Gulp, Grunt ou webpack;

- Confortável com desenvolvimento Javascript vanilla ou com frameworks/bibliotecas

- Inglês (imprescindível para leitura e escrita).

**Desejáveis:**
- Análise de layouts;

 - Conhecimento em ionic;

- Boas noções de usabilidade;

- Visualmente perfeccionista;

- Experiência em JS server-side (Node);

## Benefícios

- Convênio Médico SulAmérica (Plano Exato apartamento, sem desconto)

- Convênio odontológico SulAmerica (Plano Odonto Mais, sem desconto)

- VR/VA R$ 28,00 dia (Sem desconto)

- PLR

- Day Off

- Seguro de Vida

- Auxilio creche

- Auxilio Home office

- Licença maternidade e paternidade estendida

- Horário Flexível

- Home Office (mesmo pós pandemia)

- Cursos na Atonit Academy para todos os colaboradores sem custo

- Totalpass 60% de desconto Smartfit nível Brasil

- Zenbluk15% de desconto em todas as sessões (terapia online com rede com + de 250 psicólogos, psicanalistas, coach e terapeutas)

- Cultura voltada para pessoas em primeiro lugar

- Ambiente descontraído e colaborativo.

## Contratação

CLT a combinar

## Como se candidatar

Basta acessar o [link da vaga](https://jobs.quickin.io/atonit/jobs/613184f6861d740013cb54fc
), preencher seus dados e enviar!
https://jobs.quickin.io/atonit/jobs/613184f6861d740013cb54fc

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
