### ISSUE TITLE
[REMOTO] Fullstack Developer @AmbizzionIT

### ISSUE THREAD

**Issue by NicolasDurazzo** [frontendbr/vagas#5895]
## Nossa empresa

É uma empresa provedora de serviços e soluções integradas de sistemas, alinhadas com as principais estratégias corporativas através de uma equipe altamente qualificada. Nossa experiência e comprometimento traduzem o alto nível de satisfação e reconhecimento dos nossos clientes.

## Descrição da vaga

Fullstack developer .NET VueJS com framework Bootstrap Vuetify

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 5+ anos de experiência
- Bootstrap
- Vuetify
- .NET
- VueJS

## Contratação

- Fulltime

## Como se candidatar

Por favor envie um email para nicolas.durazzo@ambizzion.com.br com seu CV anexado - enviar no assunto:
Vaga Fullstack Developer - Github

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 48 horas após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
