### ISSUE TITLE
[Remoto] Frontend React/React Native Developer na C2S - Contact2sale

### ISSUE THREAD

**Issue by mateu5-francisco** [frontendbr/vagas#5896]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-reactreact-native-developer-121422848?origin=github&medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Acreditamos que as soluções <strong>simples são as melhores. São mais intuitivas, mais fáceis de usar e consequentemente mais efetivas! </strong>Mas, diferentemente do que as pessoas pensam em geral,<strong> a simplicidade não é o primeiro passo</strong>. Para chegar a uma <strong>solução simples e efetiva, é preciso compreender profundamente o processo e a complexidade</strong>.</p>
<p></p>
<p>As responsabilidades serão vinculadas ao desenvolvimento voltado para sistemas web e mobile que usam<strong> React e React Native (expo).</strong></p>
<p>Além disso também ajudar a evoluir e refazer algumas telas do sistema legado usando Ruby on Rails, HTML e jQuery</p>
<p></p>
<p><strong>O que é necessário:</strong></p>
<p>Experiência em projetos profissionais usando <strong>React.js e React Native</strong></p>
<p>Seja curioso e esteja sempre pesquisando sobre novas tecnologias;</p>
<p>Pense de forma arquitetural, sempre se preocupando com escala e evoluções futuras;</p>
<p>Possua capacidade de desenvolver sistemas do zero e também evoluir sistemas atuais;</p>
<p>Gostar de fazer <strong>Clean Code e soluções simples</strong></p>
<p>Conhecimento em <strong>GIT;</strong></p>
<p></p>

## C2S - Contact2sale: 
 <p>Acreditamos que as soluções simples são as melhores. São mais intuitivas, mais fáceis de usar e consequentemente mais efetivas! Mas, diferentemente do que as pessoas pensam em geral, a simplicidade não é o primeiro passo. Para chegar a uma solução simples e efetiva, é preciso compreender profundamente o processo e a complexidade.</p>
<p>Acreditamos que as soluções simples são as melhores. São mais intuitivas, mais fáceis de usar e consequenteEm 2016, Fernando Vallocci e Bruno Yukihara fundaram o Gestor de Leads C2S (Contact2sale). Ambos foram executivos de grandes empresas como: Apple, Bain &amp; Co, Booz Allen, Telefônica, Lexmark e ImovelWeb. mente mais efetivas! Mas, diferentemente do que as pessoas pensam em geral, a simplicidade não é o primeiro passo. Para chegar a uma solução simples e efetiva, é preciso compreender profundamente o processo e a complexidade.</p><a href='https://coodesh.com/empresas/c2s-contact2sale'>Veja mais no site</a>

 ## Habilidades: 
 - React.js 
- React Native 
- GIT 
- HTML 5 
- Javascript
## Local: 
 100% Remoto
## Requisitos: 
 - Conhecimento e experiência em React, React Native e GIT 
- Gostar de trabalhar em time 
- Conhecimento em metodologias agéis (Scrum) 
- Habilidade e auto motivação para trabalhar remoto 
- Ter conhecimento em HTML, CSS e Javascript.
## Diferenciais: 
 - Conhecimento em Ruby on Rails 
- Experiência ou conhecimento em Firebase, Docker 
- EXPO (React Native) 
-  Habilidades de design 
- Ter desenvolvido algum produto ou projeto por conta própria 
- Capacidade de aprender novas tecnologias de forma rápida 
- Ter participado de eventos de tecnologia.
## Benefícios: 
 - Horários Flexíveis 
- Remoto 
- Oportunidade de crescimento
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend React/React Native Developer na C2S - Contact2sale](https://coodesh.com/vagas/frontend-reactreact-native-developer-121422848?origin=github&medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
