### ISSUE TITLE
[REMOTO] Fullstack Senior Java + Angular 5 Developer @Ambizzion IT

### ISSUE THREAD

**Issue by NicolasDurazzo** [frontendbr/vagas#5898]
## Nossa empresa

É uma empresa provedora de serviços e soluções integradas de sistemas, alinhadas com as principais estratégias corporativas através de uma equipe altamente qualificada. Nossa experiência e comprometimento traduzem o alto nível de satisfação e reconhecimento dos nossos clientes.

## Descrição da vaga

- Realizar manutenção de aplicações web/mobile por meio de análise funcional do sistema e de impacto do desenvolvimento;
- Fazer o entendimento das solicitações de requisitos demandados à área de TI através de documentação interna, sistemas,  formulários de solicitações e entrevistas;
- Definir/implementar a solução técnica para a funcionalidade solicitada;
- Orientar/acompanhar a implementação de outros membros da equipe;
- Definir novas maneiras que padronizem/agilizem o trabalho do time de desenvolvimento, tais como: estudo de novas ferramentas, implementação de frameworks e automação de processos de desenvolvimento;
- Disponibilizar/acompanhar novas versões do sistema no ambiente de produção;
- Garantir o funcionamento dos servidores que abrigam as aplicações da companhia, realizando tunning, analisar mensagens de erro, criando scripts de monitoramento etc.;

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Graduação completa em Tecnologia da Informação, Engenharia, Computação ou Análise de sistemas;
- 5 anos de Experiência;
- Java EE, JavaScript, XML, CSS, HTML e XHTML;
- *Angular 5+*, Spring, JPA, Hibernate, Struts2, Tiles, iBatis e Quartz; REST/ SOAP Web Services
- Oracle, PL-SQL;
- iReport; Jenkins (ou similares), Tomcat, MyEclipse;
- Windows e Linux
- Shell scripts

**Desejáveis:**
- Conhecimentos de Appcelerator;
- conhecimentos em titanium sdk.

**Diferenciais:**
- projetos opensource

## Benefícios

- VR/VA Mínimo - 655,93
- Plano de Saúde;
- Plano de desenvolvimento individual;
- Universidade Corporativa (estamos dando os primeiros passos);
- Acompanhamento paternidade e licença paternidade;
- Programa de desenvolvimento para futuras lideranças;
- Investimento em certificações;
- Acompanhamento maternidade e licença maternidade;
- Aulas de Inglês.

## Contratação

Fulltime

## Como se candidatar

Por favor envie um email para nicolas.durazzo@ambizzion.com.br com seu CV anexado - enviar no assunto:
Vaga Fullstack Senior Java + Angular 5 - Github

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 48 horas após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
