### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor Front-End na Mongeral Aegon

### ISSUE THREAD

**Issue by hugodutra** [frontendbr/vagas#59]
## Desenvolvedor Front-End na Mongeral Aegon

Fala, pessoal!

Tá tendo duas vagas pra front-end na área de novos negócios digitais da Mongeral Aegon aqui no Rio.

Apesar da idade da empresa (180 anos!!!!), nossa equipe é uma equipe ~xovem~ e ~descolada~. Temos tentado aplicar várias coisas novas por aqui e você vai ter abertura para propor e entregar projetos bacanas.

Curtimos muito metodologias ágeis, fazemos tech talks às sextas-feiras e temos uma cestinha de basquete pra você praticar caso desista de ser programador.

Temos vários projetos de diferentes segmentos, desde imobiliárias à um instituto de longevidade e, claro, projetos relacionados a seguradora.

**Coisas não tããão legais:**

- Precisa usar roupa social ou camisa polo da empresa.
- Não rola ser home office.

## Local

Rio de Janeiro - Centro

## Benefícios

- Vale Transporte
- Vale Refeição (R$ 27,46 ao dia)
- Vale Alimentação (R$ 469,85)
- Auxílio café da manhã em uma padaria perto do trabalho
- Plano de saúde e dental
- Participação nos lucros
- Fundo Multipatrocinado (previdência)

## Requisitos (Júnior ou Pleno)

**O que você PRECISA saber:**

- Javascript
- Algum pré-processador
- Algum task runner
- HTML5
- Versionar seu código (usamos GIT)
- Saber trabalhar com Linux

**Aquele famoso ~plus a mais~:**

- Algum framework Javascript (Angular, Ember, React, backbone, etc…)
- ES6
- PostCSS
- Participar da comunidade, ir a eventos e tal
- Ter interesse por novos negócios

## Contratação

CLT

## Como se candidatar

Se tu curtiu e tá afim de trabaio dê um fork no nesse respositório e faça o nosso  teste
https://github.com/MongeralAegonDigital/front-end-trabalhe-na-mad

Manda também um currículo/Linkedin com pretenção pra nós. hadutra@mongeralaegon.com.br

Se você tiver um portfólio maneiro ou Github pode mandar junto.

**Comment by LFeh** [comment]
Boa! Vou divulgar.

**Comment by hugodutra** [comment]
Valeu, @LFeh !

**Comment by juliocarneiro** [comment]
pena q sou de sampa ;(

**Comment by diegoos** [comment]
Muito bom! Divulgando também. 👍

**Comment by hugodutra** [comment]
Valeu, @diegoos!

**Comment by oliveirajunior90** [comment]
Ainda da tempo de enviar o meu código ou as vagas já foram preenchidas ?

**Comment by paulo101977** [comment]
Boa noite a todos. @hugodutra postei o meu teste. Vou lhe enviar o meu curriculum.

Abs.

**Comment by hugodutra** [comment]
@oliveirajunior90 dá tempo sim, manda ae.

Valeu, @paulo101977! Vamo dar uma olhada aqui

**Comment by paulo101977** [comment]
@hugodutra Obrigado!

**Comment by diegomart1ns** [comment]
Fala, @hugodutra! Tá rolando ainda?

**Comment by hugodutra** [comment]
Tá sim @diegomart1ns, manda o currículo ae pra gente

**Comment by vedovelli** [comment]
@hugodutra Até que enfim um anuncio de vaga bem escrito, sem exigências absurdas e direto ao ponto! Obrigado!

**Comment by donnes** [comment]
Pena que sou do RS :/

**Comment by diegocandido** [comment]
Estou tmb no RS, e aqui o mercado de TI está encolhendo, ou é impressão
minha?


Em terça-feira, 12 de julho de 2016, Donald Silveira <
notifications@github.com> escreveu:

> Pena que sou do RS :/
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/frontendbr/vagas/issues/59#issuecomment-232119656>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABr1hkJLiuzl0zKJXU_U_Mw2p3C5b1D8ks5qU8_ZgaJpZM4I_LXz>
> .
>


-- 
Enviado do meu iPhone

**Comment by donnes** [comment]
@diegocandido Também sinto isso. Estamos bem atrasados comparado com o restante do mercado brasileiro, tanto em questão salarial quanto em aceitar novas tecnologias. Pelo menos aqui é o que sinto aqui em Poa, posso estar enganado.

**Comment by ftonato** [comment]
@donnes @diegocandido vivo na região metropolitana (São Leopoldo) e percebo a mesma situação =(

@hugodutra Boa sorte no encontro do colaborador =)

**Comment by LFeh** [comment]
@donnes e @diegocandido. Ta aí um bom assunto pra discutir :) 

https://github.com/frontendbr/forum/issues/222

**Comment by ftonato** [comment]
@LFeh verificarei ;)

**Comment by douglasgornimello** [comment]
@hugodutra Está rolando ainda?

**Comment by hugodutra** [comment]
Tá sim @douglasgornimello , mas preciso que vc entregue o teste até sexta-feira. Você consegue?

**Comment by hugodutra** [comment]
Pessoal, ainda temos vaga!

Podem mandar ae pra nós!

**Comment by hugodutra** [comment]
@LFeh Fechamos a vaga. Pode fechar a issue.

**Comment by marciogurka** [comment]
Nem recebi resposta 😢

**Comment by hugodutra** [comment]
Eita @marciogurka 

Me desculpa, cara. Agora que vi seu PR lá no repositório. Por algum motivo passou totalmente em branco por nós.

Quando tiver um vaga novamente a gente fala contigo.

**Comment by camilatigre** [comment]
@hugodutra 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by hugodutra** [comment]
a) sim

**Comment by camilatigre** [comment]
Aee! Que legal. Obrigada por responder e ajudar.

Em 24 de nov de 2016 10:24, "Hugo Dutra" <notifications@github.com>
escreveu:
