### ISSUE TITLE
[Belo Horizonte] Front-end Angular Developer na VipCommerce - Red Pill RH

### ISSUE THREAD

**Issue by RedPillRH** [frontendbr/vagas#5910]
**Vaga Remota**

## Nossa empresa

A VipCommerce, através de uma plataforma white-label e um modelo logístico criado exclusivamente para varejo alimentar, permite aos varejistas integrarem um novo canal online à operação já existente com rapidez e eficiência. A VipCommerce cresceu mais de 500% no último ano, recentemente comprados pela Magalu estão revolucionando o mercado antigo!

## Descrição da vaga

Você irá desenvolver Front-End Web e Mobile utilizando Angular e Ionic.

## Local

Remoto, [BELO HORIZONTE]

## Requisitos

**Obrigatórios:**

> ANGULAR 2+ Javascript, teste unitário, HTML, CSS, typescript;
> Essencial trabalhar em ambiente Linux

**Diferenciais:**

> Desenvolvimento orientado a objetos, ANGULAR 8+; IONIC, Consumir API Rest; Flutter;
DDD; DOCKER;
> Angularjs (frente); conehcimentos de javascript e HTML; Microsserviços;
> Experiência com CAKEPHP, LUMEN, NESTJS; Cultura DEVOPS e CI / CD; SCRUM, vibração.

## Como se candidatar

Por favor envie seu currículo no nosso portal https://jobs.quickin.io/redpillrh/jobs/613f90a6d32bf700133815a6?src=GitHub após se cadastrar.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após o recebimento do seu e-mail.
E-mail para contato: tamires.m@redpillrh.com.br

#### Alocação
- Remoto

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
