### ISSUE TITLE
[Remoto] React-Native Fullstack Developer na Ser Educacional

### ISSUE THREAD

**Issue by juliancorrea** [frontendbr/vagas#5914]
## Nossa empresa

>Gente criando o futuro.
>Essa é a nossa razão de existir.
>Nosso propósito.

Seu propósito também é transformar as vidas das pessoas através da educação?

Para ser gente criando um futuro é preciso estabelecer um objetivo, uma estratégia de sucesso e foi com esse propósito que surgiu o grupo Ser Educacional. Transformar por meio da educação tem sido uma missão ao mesmo tempo desafiadora e compensadora, ao ver o sucesso dos nossos alunos e ex-alunos.

Trabalhamos todos os dias para proporcionar uma experiência de educação, transformadora, duradoura e inovadora para os nossos mais de 200 mil alunos, em nossas instituições e polos de educação presentes em todas as regiões do Brasil.

Com esse desafio, nossas equipes são constantemente encorajadas a aprimorar nossos processos e a inovação é nossa aliada neste caminho. Aplicar nossas habilidades e competências diariamente, dentro dos valores de qualidade, criatividade, respeito, honestidade e diversidade, que representam tudo aquilo que acreditamos.

A missão de ser gente criando o futuro pede estar atento a todas as mudanças, sejam elas no plano acadêmico, tecnológico ou administrativo. Olhar cada resolução e tarefa como oportunidade de crescimento pessoal, profissional e de fazer a diferença na trajetória de nossos alunos.

É essa vontade de transformar que você quer para sua vida e sua carreira?

## Descrição da vaga

Procuramos um Desenvolvedor pleno/sênior React-Native Fullstack para atuar em aplicativo de rede social em videos.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com React-Native
- 3 anos de experiência com Node JS
- 2 anos de experiência com Mongo DB
- 2 anos de experiência com  React JS

## Benefícios

- Plano de saúde
- Plano Odontológico
- VR de acordo com a localidade
- Bolsa para fazer faculdade nas faculdades do grupo

## Contratação

CLT a combinar

## Como se candidatar

Acessar o link https://sereducacional.gupy.io/jobs/1220838

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

## Labels
React-Native
Node
Mongo
React

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
