### ISSUE TITLE
[Home Office] Senior Front-end Developer no Grupo Easy

### ISSUE THREAD

**Issue by Bruno-Silva2021** [frontendbr/vagas#5916]
> Full Home Office

## Descrição da vaga

Trata-se de uma vaga para atuação PJ em atuação Full Home Office. É um projeto do ministério da educação (SISU), um projeto com previsão de 6 meses, podendo ser prorrogado por mais 6 meses e com possibilidade de efetivação.

## Local

Full Home Office

## Requisitos

**Obrigatórios:**
- Javascript
- Angular 6+
- Git
- Experiência com análise de desempenho de aplicações.
- Conhecimento sobre boas práticas em desenvolvimento seguro.
- Experiência com desenvolvimento para nuvem.

**Desejáveis:**
- Experiência com Containers e Kubernetes.
- PHP / Laravel

**Diferenciais:**

## Benefícios

Atuação será na modalidade PJ, portanto sem benefícios.

**Diferenciais:**

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para bruno.silva@grupoeasytech.com.br com seu CV anexado - enviar no assunto: CV FrontEnd

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.
E-mail para contato em caso de não haver resposta: bruno.silva@grupoeasytech.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
