### ISSUE TITLE
[São Paulo/SP] Front-end Developer (React) na Woke

### ISSUE THREAD

**Issue by ruanavallandro** [frontendbr/vagas#5917]
> Vaga Remota durante a pandemia

## Nossa empresa

A  Woke é uma startup de tecnologia que quer mudar a relação de trabalho entre as pessoas e as empresas. Como uma people tech, atuamos ao lado das pessoas com programas de desenvolvimento, instigando novas competências e o foco em suas carreiras. Já com as empresas, temos programas de advisory que atuam em cultura e liderança. Além disso, somos excelentes  em recrutamento de alta gestão, serviço em que unimos todos esses conhecimentos de pessoas e empresas para transformar os resultados das companhias com altíssima performance. E já não estamos restritos apenas no Brasil! Atuamos também nos Estados Unidos, além de outros clientes na América Latina.

## Descrição da vaga

Buscamos um Desenvolvedor React para fazer parte dessa transformação na carreira das pessoas! 

Sua missão será colaborar na construção de plataformas altamente escaláveis que entregam soluções digitais, transformando a relação entre empresas e pessoas!

## Local

Híbrido (São Paulo/SP)

## Requisitos

**Obrigatórios:**
- Entendimento de arquitetura e experiência em implementação das mesmas (SOLID, DDD e similares)
- Familiaridade com computação em nuvem (se for AWS melhor ainda!)
- Conhecimento em React para aplicações escaláveis
- Experiência com metodologias ágeis

**Diferencial:**
- Conhecimentos no framework de spring boot para Kotlin e/ou Java 

**Dia a Dia:**
- Opinar, analisar e aplicar arquitetura do software 
- Codar as funcionalidades dos produtos garantindo a manutenção das entregas 
- Colaboração para a construção da plataforma com utilização de tecnologias mais recentes 
- Olhar crítico para o pilar de qualidade (testes) e de segurança no desenvolvimento 
- Trabalhar com mindset de inovação trazendo as o mercado

## Benefícios

- Horário flexível 
- Pacote de benefícios flexível

## Contratação

CLT

## Como se candidatar

Por favor envie um WhatsApp para Ruana Vallandro: (11) 97293-4986.

#### Alocação
- Alocado 
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
