### ISSUE TITLE
[REMOTO] Software Engineer na Woke

### ISSUE THREAD

**Issue by ruanavallandro** [frontendbr/vagas#5918]
## Nossa empresa

A  Woke é uma startup de tecnologia que quer mudar a relação de trabalho entre as pessoas e as empresas. Como uma people tech, atuamos ao lado das pessoas com programas de desenvolvimento, instigando novas competências e o foco em suas carreiras. Já com as empresas, temos programas de advisory que atuam em cultura e liderança. Além disso, somos excelentes  em recrutamento de alta gestão, serviço em que unimos todos esses conhecimentos de pessoas e empresas para transformar os resultados das companhias com altíssima performance. E já não estamos restritos apenas no Brasil! Atuamos também nos Estados Unidos, além de outros clientes na América Latina.

## Descrição da vaga

Buscamos um Engenheiro de Software para fazer parte dessa transformação na carreira das pessoas! 

Sua missão será colaborar na construção de plataformas altamente escaláveis que entregam soluções digitais, transformando a relação entre empresas e pessoas!

## Local

Remoto

## Requisitos

- Entendimento de arquitetura e experiência em implementação das mesmas (SOLID, DDD e similares)
- Familiaridade com computação em nuvem (se for AWS melhor ainda!)
- Conhecimentos no framework de spring boot para Kotlin e/ou Java 
- Conhecimento em React para aplicações escaláveis
- Experiência com metodologias ágeis

## Dia a Dia
- Opinar, analisar e aplicar arquitetura do software 
- Codar as funcionalidades dos produtos garantindo a manutenção das entregas 
- Colaboração para a construção da plataforma com utilização de tecnologias mais recentes 
- Olhar crítico para o pilar de qualidade (testes) e de segurança no desenvolvimento 
- Trabalhar com mindset de inovação trazendo as o mercado

## Benefícios

- Horário flexível 
- Pacote de benefícios flexível

## Contratação

CLT

## Como se candidatar

Por favor envie um WhatsApp para Ruana Vallandro: (11) 97293-4986 ou se candidate em: https://recruitcrm.io/apply/59519508 

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by JulianaNepomuceno** [comment]
Essa posição se encontra em aberto! Caso tenha interesse se aplique no link acima ou entre em contato diretamente comigo:

Juliana Nepomuceno
+55 11 94798-2650
juliana.nepomuceno@wokepeople.com.br

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
