### ISSUE TITLE
[Remoto] QA/Automation JS Developer na Finetune - Ingles nao necessario

### ISSUE THREAD

**Issue by tyagow** [frontendbr/vagas#5919]
## Nossa empresa

"Leading the way in AI-Human hybrid solutions for learning."
Aqui na Finetune buscamos inovar o setor da educacao utilizando IA e humanos "experts".

Mais em: [Finetune](https://www.finetunelearning.com/)

## Descrição da vaga

Buscamos um Desenvolvedor / QA / Automatizador com habilidades fprtes em Cypress e JS, alguem que nao tenha medo de abrir o codigo e adicionar os recursos necessarios para automatizar o maximo do processo de QA.
Muito importate  ter um grande senso de UI e **UX**.

Tu seras responsavel por garantir que novas features nao tenham bugs alem de automatizar todo o processo de tests nas features ja desenvolvidas.
Iras trabalhar junto ao um time de Brasileiros em uma empresa internacional e ter a oportunidade de participar de projetos nunca vistos no mercado utilizando IA.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 2 anos de experiência comprovada escrevendo tests com Cypress (E2E) 
- 1 anos de experiência com tests the UI e UX (Tests manuais)
- Ler e escrever em Ingles

**Desejáveis:**
- experiencia profissional com React
- Entender alguem falando em Ingles

**Diferenciais:**
- Experiencia com tests the integracao e de unidade (Unit tests)
- React testing library
- NextJS
- Experiencia em empresa internacional
- Se comunicar em Ingles (Menos valorizado que os requisitos acima)

## Benefícios

- Auxílio Educacao $500 dolares / Ano

**Diferenciais:**
- Horario flexivel
- Foco no valor gerado
- Cultura sem ingual, lugar incrivel para avancar tua carreria no exterior
- Pagamento em dolar

## Contratação

PJ a combinar

Range da vaga: $1500 USD - $4000 USD

## Como se candidatar

Por favor envie um email para tiago@finetunelearning.com com seu CV anexado - enviar no assunto: Vaga QA/Automation Engineer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até XX dias após cada processo.
E-mail para contato em caso de não haver resposta: feedbacks@empresasuperlegal.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
