### ISSUE TITLE
[Home Office] Front-End Developer na Upnid

### ISSUE THREAD

**Issue by pedromergulhao** [frontendbr/vagas#592]
## Descrição da vaga

Somos um marketplace para venda de produtos físicos ou digitais. Projeto rodando a um ano e meio com um time jovem e multidisciplinar. Não nos baseamos em horas mas sim em resultado. Buscamos um desenvolvedor com experiência, e que esteja antenado as novas tecnologias. É necessário experiência com algum framework SPA, como React, Vue, Angular.

## Local

Remoto - (Caso opte por trabalhar em escritório, possuímos frente em SP, BH e RJ).

## Benefícios

- Possibilidade de PL.

#### Diferenciais

- Trabalho remoto
- Monte seu horário
- Cresça junto
- Contato direto com toda equipe

## Requisitos

**Obrigatórios:**
- Proficiência em JavaScript (puro)
- Experiência com algum framework SPA, como React, Vue, Angular.

**Diferenciais:**
- projetos opensource
- Node

## Contratação

PJ  ou CLT a combinar

## Nossa empresa

Somos um marketplace para venda de produtos físicos e digitais. Estamos a um ano e meio no mercado crescendo a cada mês. Temos como sócios do projetos executivos de grandes empresas do ecommerce brasileiro.

## Como se candidatar

Por favor envie um email para pedro@upnid.com com seu Git - enviar no assunto: Vaga Dev Upnid.

**Comment by netojose** [comment]
Curti pra caramba essa vaga e a filosofia da empresa! E já sei para quem indicar.

**Comment by pedromergulhao** [comment]
Obrigado @netojose =)

**Comment by flaviocoder** [comment]
Enviado, let's put the hopes up! hahaha

**Comment by svjp** [comment]
Enviado!

**Comment by paulitolinhares** [comment]
Enviado!

**Comment by tdex** [comment]
Enviado!

**Comment by ribeiroevandro** [comment]
Enviado!

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
