### ISSUE TITLE
´[Brasilia ] ✔Desenvolvedores JR/Pl/SR  [Digisystem]

### ISSUE THREAD

**Issue by alinemelonah** [frontendbr/vagas#5920]
<!-- 
✔Desenvolvedores JR/Pl/SR
Procuramos todas as linguagens ❣
Local de Trabalho:
Híbrido/ Brasília
Contratação:
CLT
Benefícios:
·         VT (Conforme o Deslocamento)
·         VR/VA- Cartão Alelo Tudo Flex
·         Plano de Saúde Unimed –Enfermaria/Apartamento ou Absoluto
·         Aqui tem a liberdade de escolher!
·         Assistência Odontológica –Porto Seguro (Extensível a dependentes)
·         Seguro de Vida- Porto Seguro
·         PAE- Psicológica , Financeira ,Jurídica ( Parceria Alelo)
·         Reembolso Anual de Material Escolar- Ensino Infantil (maternal) até Ensino Fundamental (9ºano).
·         Cartão de Credito Emergencial Sorovale
·         Empréstimo Consignado
·         Gympass
·         Sams Club(Desconto)
·         Digi Teca
·         Digi Indique
Cv com pretensão salarial para aline.santos@digisystem.com.br com o nome do cargo no assunto .
Somos certificada pela GPTW como uma das melhores empresas para se trabalhar 🧡💙
Conheça mais sobre a gente no site: https://lnkd.in/d-9E5f35

**Comment by Rannya7x** [comment]
Ué, cadê a vaga?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
