### ISSUE TITLE
[São Paulo/SP] Front-end Developer na Suprevida

### ISSUE THREAD

**Issue by grasielegoncalves** [frontendbr/vagas#5924]
> VAGA PARA ATUAÇÃO PRESENCIAL - [SP], [São Paulo], [Cerqueira César]

## Nossa empresa

A Suprevida é uma startup de saúde e tecnologia (Healthtech) fundada em 2018 que tem a missão de facilitar o acesso a serviços e produtos para que as pessoas possam prevenir, preservar e recuperar a saúde.

Fazemos parte do Hub Distrito InovaHC - Plataforma inovadora de conexão entre os agentes da saúde - corporações e startups.

## Descrição da vaga

Front-End Developer no squad interno da Suprevida - com missão crítica de sustentação e desenvolvimento de novos projetos e reengenharia.

## Local

Vaga presencial - [SP], [São Paulo], [Cerqueira César]

## Requisitos

**Obrigatórios:**
Conhecimento em HTML; CSS; JavaScript; Git; GitHub.

**Desejáveis:**
Experiência com React.JS; NextJS; JSP - Java Server Pages; Typescript.

**Diferenciais:**
Ambiente de trabalho agradável
Equipamentos modernos
Inovação constante
Autonomia
Contratação
CLT

## Benefícios

Plano de saúde sem desconto
Vale Transporte
Vale Refeição de R$ 30/dia
Plataforma Distrito Network com acesso a mentorias, cursos e descontos.

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um e-mail para grasiele.goncalves@suprevida.com.br com seu CV, Linkedin e pretensão salarial - enviar no assunto: Vaga Front-End ou candidate-se pelo link: https://vagas.revelo.com.br/suprevida/frontend-developer-presencial

## Tempo médio de feedbacks

2 dias

## Labels

- Alocado
- Presencial
- CLT
- Pleno
- São Paulo

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno

**Comment by ericcoutinho** [comment]
Favor remover a label de vaga remota...
