### ISSUE TITLE
[Remoto] Front-End Developer na Sequor

### ISSUE THREAD

**Issue by ferhanauer** [frontendbr/vagas#5929]
## Nossa empresa

A Sequor é uma Multinacional de engenharia de sistemas de Canoas/RS. Na Sequor, o propósito é tornar as empresas lugares melhores. Melhores para trabalhar, melhores para viver, melhores para realizar sonhos e preservar nosso planeta. 

## Descrição da vaga

Dentre os diversos clientes que a Sequor possui, a vaga é para um cliente específico da França, ou seja, um projeto internacional!
O projeto é novo e embora a equipe já esteja bem estruturada, estão buscando mais profissionais para fazer parte do time! 
No back-end utilizam Java como linguagem principal e no front-end é JavaScript/Typescript com Angular!

Algumas tecnologias do projeto:
- Angular, HTML, CSS, JavaScript, Typescript e ECMAscript 6;
- IOC – Inversão de Controle, Programação Orientada Objetos, Design Patterns, Clean Code, Programação Funcional, Design de APIs REST, Microservices, API Gateway, Protocolo HTTP, SOLID,
Jasmine, Karma, Cypress; TDD & BDD.

## Local

Remoto ou Escritório, [RS], [Canoas], [Centro]

## Benefícios

- Plano de saúde - Unimed (80%);
- Plano Odontológico - Unimed;
- Seguro de vida
- VR/VA de R$ 23/dia
- Bonificação Anual;
- ...

**Diferenciais:**
- Horário flexível, liberdade para sugerir tecnologias, propor melhorias, etc. e time super colaborativo.

## Contratação

CLT a combinar.

## Como se candidatar

Por favor envie um email para rhti@iniciativa.com.br com seu CV anexado - enviar no assunto: Vaga Angular.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 01 dias após cada processo.
Telefone para contato em caso de não haver resposta: (51) 9 9246-7799

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
