### ISSUE TITLE
[São Paulo] Front-End Developer na Kanamobi

### ISSUE THREAD

**Issue by xdougx** [frontendbr/vagas#593]
## Descrição da vaga

Trabalhar em um ambiente informal de hierarquia horizontal, desenvolvendo aplicações Front-end com as tecnologias de ponta com PWA, Angular, React, Vue.js entre outras, participando desde a concepção da ideia até a entrega final e manutenção da versão.

## Local
Escritório, São Paulo - Barra Funda - a 600 metros do Metro

## Requisitos

**Obrigatórios:**
- Lógica de programação, arquitetura e OOP
- Conhecimento intermediário em desenvolvimento JavaScript
- Conhecimento das principais bibliotecas de JavaScript
- Conhecimento em desenvolvimento de Service Worker (PWA)
- Conhecimento em Angular (1,2 e 4) e ES6
- Conhecimento nas gerenciadores de pacote GRUNT, Gulp, Web Packer, NPM
- Habilidades intermedário com HTML5, CSS3
- Conhecimento das principais bibliotecas de UI/UX
- Conhecimento em criar e montar gráficos com Javascript e CSS

**Desejável**
- Conhecimento do Git Flow
- Conhecimento em desenvolviment com React
- Familiaridade com o ambiente Linux e Mac
- Experiência com desenvolvimento para outras plataformas/linguagens
- Graduação em Design, Desenvolvimento de Software ou cursos afins

## Contratação
PJ

## Benefícios
- Plano de saúde
- Bonificação
- Horário flexível
- Arcade na Empresa
- Lojinha com Guloseimas

## Como se candidatar
Por favor envie um email para douglas@kanamobi.com.br com seu CV anexado - enviar no assunto:
Vaga Desenvolvedor Front-End Kanamobi

**Comment by raloliver** [comment]
🔝

**Comment by jadir-junior** [comment]
muito bacana empresa com essa mentalidade "hierarquia horizontal".

Só uma observação GRUNT, Gulp não são gerenciadores de pacotes, são tasks runners. Gerenciador de pacotes são npm e yarn

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
