### ISSUE TITLE
[Remoto] Front-end Developer na Grupo Plan Marketing

### ISSUE THREAD

**Issue by ferhanauer** [frontendbr/vagas#5930]
## Nossa empresa

A Grupo Plan Marketing é uma empresa moderna de Marketing Digital que trabalha com a criação de portais, e-commerce, games, aplicativos, hotsites, branding, realidade aumentada, etc. Possui um amplo portfolio de projetos super inovadores! 

## Descrição da vaga

Responsabilidades:
· Responsável pela criação UI, design system e diagramação;
· Contatos recorrentes com as atendimentos e time comerciais;
· Interação direta com o time de criação sênior, time de desenvolvimento back-end;
· Garantia de opções de funcionalidade e design em linha com as determinações dos Designers de UX/UI;
· Desenvolvimento de recursos para aprimorar a Experiência do Usuário;
· Encontro de equilíbrio entre design funcional e estético.
· Garantir que o design das páginas Web seja otimizado para dispositivos móveis;
· Construção de código reutilizável para uso futuro;
· Otimização das páginas Web para velocidade e escalabilidade máximas;
· Manutenção da consistência da marca em todas as páginas Web produzidas;
· Utilização de boas práticas para o bom funcionamento do SEO;
· Capacidade de organização, responsabilidade e dinamismo;
· Participar de reuniões internas e com clientes;
 
## Local

Remoto ou Escritório, [Rio Grande do Sul], [Novo Hamburgo], [Operário]

## Requisitos

- Conhecimentos em HTML, CSS e Javascript;
- Experiência com frameworks de front end (React e/ou Angular e/ou Vue, etc.);
- Compreensão de princípios de SEO e performance de carga e exibição de páginas Web;
- Conhecimento do pacote Office e Google Drive.

**Desejáveis:**
- Conhecimentos em Git e AWS;
- Bom domínio na língua inglesa.

## Benefícios
- Descanso remunerado.

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para rhti@iniciativa.com.br com seu CV anexado - enviar no assunto: Vaga Angular.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 01 dias após cada processo.
Telefone para contato em caso de não haver resposta: (51) 9 9246-7799

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
