### ISSUE TITLE
[São Leopoldo] Front-end Developer na W3K

### ISSUE THREAD

**Issue by ferhanauer** [frontendbr/vagas#5931]
## Nossa empresa

A W3K tecnologia tem 10 anos de atuação no segmento de tecnologia da informação. Desenvolve e comercializa aplicações de negócio em nuvem, que focam em prover governança da informação e escalabilidade aos processos de gestão de seus clientes. 

São fabricante do software Greendocs e CapX que atua no mercado desde 2011.

Juntamente com a comercialização e implantação do software, a empresa também oferece serviços em regime de BPO, personalizados conforme a necessidade do cliente (exemplos: digitalização, arquivista, etc.)

A W3K possui em sua carteira de clientes algumas das maiores empresas do Brasil, entre elas Gerdau, Suzano, Klabin, Hapvida, Itaipu Binacional e Unilever.  

## Descrição da vaga

- Participará do processo de desenvolvimento de aplicações Front-End. 
- Eles possuem 02 times principais, pois existe uma nova versão do software com tecnologias mais novas e a versão “legada”. A vaga é para o projeto atual. O projeto já iniciou, porém ainda estão estruturando a squad.  

## Local

Escritório, [Rio Grande do Sul], [São Leopoldo], [Centro]

## Requisitos

**Obrigatórios:**
- Experiência com os frameworks Angular e/ou React.js e/ou Vue.js, além da base JavaScript/Typescript, HTML e CSS;
- Experiência na utilização de APIs REST. 

**Desejáveis:**
- conhecimentos em ruby on rails
- conhecimentos em C#

**Diferenciais:**
- SASS e/ou LESS, Git e User Experience Design (UX).

## Benefícios
- Bônus Mensal de R$ 1.500,00;
- Plano De Saúde Unimed Nacional sem coparticipação – desconto fixo de R$ 168,64;
- Plano Odontológico MetLife – desconto fixo de R$ 13,96
- Vale-Alimentação ou Refeição no valor de R$ 530,00, (desconto de R$106,00);
- Treinamento completo nos produtos, sistemas e processos da W3K.
- Opção de vale transporte;
- GYMPASS.

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um email para rhti@iniciativa.com.br com seu CV anexado - enviar no assunto: Vaga Angular.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 01 dias após cada processo.
Telefone para contato em caso de não haver resposta: (51) 9 9246-7799

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
