### ISSUE TITLE
[Remoto] Front-end Vue.js Developer @Cotabox

### ISSUE THREAD

**Issue by Turbiani** [frontendbr/vagas#5933]
## Descrição da vaga

Temos como desafio construir nosso novo dashboard em Vue3 enquanto damos manutenção no legado em Nuxt2. Para isso, abrimos vagas para todos os níveis, JR PL e SR.

Também estamos desenvolvendo um styleguide novo, e criando nossos componentes, para aos poucos irmos saindo do Element. Se tiver afim deste desafio, seu lugar é conosco!

## Local

Remoto

## Benefícios

- VR de R$ 330,00.
- Auxílio Home Office de R$ 120,00.
- Auxílio Notebook de R$ 260,00.
- Remuneração: R$ 2116,00 a R$9000,00

#### Diferenciais

- Monte a sua máquina como desejar
- Acesso a plataforma [Zenklub](https://zenklub.com.br/) com 2 sessões gratuitas por mês para praticar meditação, sessões de coach de carreira, terapeutas e psicólogos.
- Dayoff todo mês para focarem em inovação. A cada 3 meses os projetos são avaliados em conjunto com o time e absorvidos pela empresa. Atualmente estamos trabalhando com Linguagem Natural em um projeto de precificação, que analisa a nossa base de dados e consegue inferir a média de preço praticada na plataforma.
- Dayoff a cada 2 meses para focarmos em projetos sociais, atualmente estamos trabalhando em um aplicativo para auxiliar pessoas que querem adotar um animal a se conectarem com centros de adoções.
- **Obs:** Os Dayoff são os dias oficiais travados no calendário, mas não impedimos que ocorram outros encontros que o time se organize. Só criamos esses marcos para poderem alinhar escopo e definir entregáveis. 

## Requisitos

**Obrigatórios:**
- Conhecimento em VueJS2, e VueJS3.
- Conhecimento em boas práticas de organização de código.
- Conhecimento em testes unitários e integração, usando Cypress, Jest ou similares.
- Saber consumir dados de API usando Axios ou similares.
- Autenticação via Bearer Token ou similares.

**Desejáveis:**
- Experiência com consumo de APIs GraphQL.
- Conhecimento em Typescript.

**Diferenciais:**
- Projetos open-source.
- Artigos e palestras em eventos.

## Contratação

CLT

## Nossa empresa

Aqui na [Cotabox](http://cotabox.com.br) desenvolvemos uma plataforma SaaS para times de compras de empresas de médio e grande porte. Focamos em ajudar o setor de compras em ter melhor fluidez e clareza no processo de inicio ao fim, desde a necessidade de comprar algo, escolher o fornecedor, passar pela alçada de aprovação dos seus gestores e enviar o pedido ao ERP.

Temos um ambiente criativo, muito aberto a sugestões com foco em se tornar a melhor plataforma do mercado. Para atingir isso, entendemos que o meio deve ser tecnologia de ponta, sendo assim, escolhemos uma stack moderna e temos pautas de inovação mensalmente para atuarmos em frentes que trabalhem com linguagem natural, machine learning e desenvolvimento mobile.

**Aqui usamos:**
- Vue.js
- NodeJS
- GraphQL
- AWS Serverless
- AWS SQS
- MongoDB

## Como se candidatar

 - **Primeira etapa**, envie um email para rodrigo@cotabox.com.br, com o assunto: Vaga Front-end. No corpo do email, envie o link do seu github e/ou seu linkedIn.
 - **Segunda etapa** será uma entrevista com o RH, a fim de validar o fit cultural com a empresa.
 - **Terceira etapa** será enviado um desafio técnico.

#### Alocação
- Flexível
- Remoto

#### Nível
- Júnior
- Pleno
- Sênior

#### Regime
- CLT
- PJ a Combinar

**Comment by FelipeBastosxj** [comment]
Eu me encaixo bem nos requisitos pelo que vejo, enviei o currículo espero algum retorno se possivel. Posso fazer o desafio tecnico tranquilamente se necessário

**Comment by Turbiani** [comment]
> Eu me encaixo bem nos requisitos pelo que vejo, enviei o currículo espero algum retorno se possivel. Posso fazer o desafio tecnico tranquilamente se necessário

Oi @FelipeBastosxj, tudo bem meu caro? Já iniciamos ontem as entrevistas, logo logo será chamado! Obrigado por participar do nosso processo seletivo. Abs
