### ISSUE TITLE
[Remoto] Desenvolvedor React ( Pleno / Senior / Lead ) @ Post2B

### ISSUE THREAD

**Issue by lfalcao** [frontendbr/vagas#5935]
## Nossa empresa

A Post2B é um marketplace que conecta influenciadores a marcas e agências. Hoje temos em torno de 70000 influenciadores cadastrados e estamos desenvolvendo novas soluções para esse público 😄 

## Descrição da vaga

Estamos buscando desenvolvedores full-time ou part-time/freelancer com experiência em desenvolvimento frontend (React) ou backend (Ruby/Python) para ajudar com nosso sistemas. Nossa stack hoje se resume a uma API em Ruby on Rails, um front em React e um aplicativo em React Native (ios e android).

Idealmente, a pessoa deve ter disponibilidade de 4 à 8 horas diárias (horário flexível).

## Local

Remoto.

## Requisitos

**Obrigatórios:**
- conhecimento em javascript
- experiência com react
- layout responsivo
- testes automatizados
- consumo de apis
- git

**Desejavel:**
- experiência em ruby on rails
- experiência com react native
- inglês intermediário
- firebase

## Contratação

- PJ/Freelancer
- Remuneração: R$ 5,000 a R$ 12,000 a depender da experiência e horas disponibilizadas.
- Benefícios (dependendo da contratação): Cartão Benefícios e Plano de Saúde.

## Como se candidatar

Por favor envie um email com pretensão, disponibilidade e currículo/linkedin para vagas(arroba)post2b.com com seu CV anexado - enviar no assunto: Vaga Dev

Não temos interesse em empresas de desenvolvimento/outsourcing/terceirização.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.

## Labels

- Remoto
- Freela
- PJ
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
