### ISSUE TITLE
[Remoto] Frontend Vue.js Developer na Juros Baixos

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#5937]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-frontend-vuejs-174635038?origin=github&medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A<strong> Juro Baixos</strong> está buscando <strong><ins>Frontend Vue.js nível Sênior</ins></strong> para ajudar na profissionalização de sua plataforma. Estamos na fase em que superamos a versão inicial do nosso sistema e temos outros planos maiores para a empresa.</p>
<p>Como Desenvolvedor de Front End Sênior, você se tornará parte da equipe de produto e será responsável por atualizar nosso produto atual, implementar APIs de parceiros, implementar novos produtos e serviços de maneira testada, segura, com alto desempenho e com a melhor UX possível.&nbsp;</p>
<p>Você será considerado o especialista em seu trabalho e analisado para tomar decisões de implementação e arquitetura: qual estrutura, quais padrões de design e quais frameworks / bibliotecas aplicar. Além de realizar o trabalho, é importante que você esteja disposto a ensinar outros desenvolvedores como melhorar suas habilidades, alertá-los sobre as armadilhas em que você caiu, além do que considera as melhores práticas.</p>

## Juros Baixos: 
 <p>O Juros Baixos foi fundado em 2017 com o objetivo principal de contribuir para um Brasil financeiramente saudável até 2050. Somos uma plataforma de bem estar financeiro que, através da oferta e comparação de produtos financeiros, potencializa a experiência de compreensão, escolha e aquisição do mesmo de uma forma 100% online.&nbsp;</p>

<p>Começamos com empréstimos pessoais e nos primeiros 4 anos já originamos mais de R$80 milhões junto com nossos +30 bancos e fintechs parceiros.&nbsp;</p><a href='https://coodesh.com/empresas/juros-baixos'>Veja mais no site</a>

 ## Habilidades: 
 - Vue.js 
- React.js 
- Angular.js 
- Redux 
- Vuex 
- Webpack 
- Sass/Less 
- MochaJS 
- GIT
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência com Vue, Svelte, React ou Angular 
- Experiência com Redux, Vuex 
- Experiência com Webpack 
- Experiência com SCSS/SASS 
- Experiência com Jet, Mocha ou Cypress 
- Tem olho para a qualidade do código e leva tempo / é paciente o suficiente para fazer revisões de código 
- Tem > ~ 5 anos de experiência profissional em programação em várias empresas / ambientes 
- Não tem medo de se pronunciar (em inglês, não precisa ser perfeito) 
- Possui clareza em como um projeto pode ser dividido em pedaços menores gerenciáveis 
- Está sempre aprendendo e brincando com coisas novas 
- Acostumado com Git (não apenas clicando na GUI)
## Diferenciais: 
 - Bazel 
- Implementação de Design Systems 
- Desenvolvimento e contribuição open source 
- Progressive Web Applications (PWA)
## Benefícios: 
 - 100 % Remota 
- Horários Flexíveis
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Vue.js Developer na Juros Baixos](https://coodesh.com/vagas/desenvolvedor-frontend-vuejs-174635038?origin=github&medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
