### ISSUE TITLE
[Remoto] Software Engineer na CondoLivre [ByIntera]

### ISSUE THREAD

**Issue by biarogerio** [frontendbr/vagas#5940]
A  Livre Soluções Financeiras está montando um time para fazer parte de um novo produto lançado pela empresa. 

A Livre é especializada em soluções estruturadas de crédito, para pessoas jurídicas e pessoas físicas. O desafio agora é fazer parte da CondoLivre, uma fintech da Livre baseada em alta tecnologia.

Nesse desafio você vai participar do desenvolvimento das soluções financeiras da empresa, **com toda a liberdade para colocar sua cara no negócio e o melhor, com a oportunidade de trabalhar 100% home office!** 

**Saiba mais em: https://bit.ly/3lOnWaZ**

### FICHA TÉCNICA

Cargo: **Software Engineer**
Departamento: **Fullstack**
Nível: **Pleno/Sênior**
Modelo de contratação: **PJ ou CLT**
Local de trabalho: **Remoto**

## Requisitos

**Obrigatórios:**
- Experiência trabalhando com práticas ágeis de desenvolvimento de software;
- Conhecimento de boas práticas como Clean Code, SOLID e Design Patterns;
- Experiência com JavaScript e React;
- Experiência com Node.js;
- Conhecimento em Firebase e familiaridade com ferramentas Google Cloud.

## Como se candidatar
**Candidate-se em: https://bit.ly/3lOnWaZ**

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
