### ISSUE TITLE
[Remoto] Desenvolver (a) React JS Pleno no @DB1 GROUP

### ISSUE THREAD

**Issue by alissongusmao** [frontendbr/vagas#5942]
## Nossa empresa

Somos um grupo empresas de tecnologia, nascido no interior do Paraná, com 21 anos de experiência em desenvolvimento de software voltado para soluções de grandes empresas. Atuamos em Diversas frentes de Mercado: com Produtos ( ANYMARKET , CONSIGNET ,  Eive ) e TAMBÉM COM Serviços e Projetos Personalizados atraves da Nossa Fábrica de Software - DB1 global Software  . 

Somos mais de 700 colaboradores em todo o Brasil e até na Argentina, com escritório em Maringá / PR, Campo Grande / MS e Presidente Prudente / SP e atuação remota (home office) desde 2017. Há 12 anos consecutivos entre as Melhores Empresas para Trabalhar , segundo o GPTW.

Somos movido por desafios diários, sempre buscando uma forma de melhorar o que já existe e criar coisas novas com qualidade! Todos (as) aqui tem autonomia e voz para dar feedbacks, testar coisas novas e ser parte dessa mudança. Aqui aprendemos uns com os outros diariamente, com um forte senso de tempo. DB1 é pra quem não quer ser mais um!

## Descrição da vaga

Buscamos um (a) profissional apaixonado (a) por tecnologia, que desenvolva em frontend com React JS e busque entregar soluções de qualidade aplicando as melhores práticas de programação, tais como SOLID, código limpo. Sua responsabilidade será apoiar um projeto de um de nossos parceiros a alavancar seus negócios!

Por isso essa vaga se destina a profissionais antenados, interessados ​​em evolução contínua, sejam curiosos e acompanhem as melhores tendências em desenvolvimento.

## Local

Remoto 

## Requisitos

**Obrigatórios:**
Experiência com HTML5, CSS3;
Experiência com Javascript;
Conhecimento em ES6;
Conhecimento em pré-conhecimento CSS (SASS, LESS, PostCSS);
Experiência com alguma metodologia atual de padrões de CSS / HTML (BEM, Atomic, outros);
Conhecimento em Git;
Criação de código limpo, legível e cross-browser;
Ser uma pessoa flexível e por dentro das novidades tecnológicas; 
Grande capacidade de aprendizado para novas práticas, tecnologias, linguagens de programação e culturas de engenharia.

**Diferenciais:**
Conhecimento em usabilidade de usuário e boas práticas de UX e UI;
Experiência com desenvolvimento de sites responsivos;
Testes Automatizados (mochajs, jasmim, jest);
Redux / Flux;
Conhecimentos com Server Side Rendering;
Conhecimentos em GraphQL.

## Benefícios

Vale alimentação e / ou vale refeição;
Plano de Saúde Unimed - Com mensalidade 100% paga pela DB1;
Gympass;
Home office como modelo de contratação. Atuamos com essa possibilidade desde 2017.
Home office Auxílio
Horários flexíveis !;
Plano odontológico (opcional);
Seguro de Vida (opcional)
Convênio com farmácia Droga Raia, com desconto para colaboradores;
Para celebrar a vida de quem amamos, é possível  sair um pouco mais cedo no dia do aniversário de conjugue e filhos! :)
Uma trilha de carreira com Plano de Desenvolvimento Individual (PDI) e feedbacks constantes para te ajudar na sua evolução profissional;
Aqui você terá a oportunidade de aprender coisas novas - seja no dia-a-dia, em um  Programa de Mentoria  ou em um desafio do  Mestre dos Códigos.
Comitês para você participar e contribuir com as melhorias dos processos do Grupo DB1 ou contribuir com a comunidade: Comitês de Boas Práticas de Gestão de Pessoas (CBPGP), Comitê técnico, Comitê de Responsabilidade e Desenvolvimento Socioambiental (CORDS)

## Contratação

CLT

## Como se candidatar

Sentiu interesse na oportunidade? [Clique aqui e cadastre o seu currículo!](vagasdb1.recruiterbox.com/jobs/17a87d84e30f43e89f137ada658e9189?referred_by=350760) 

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
