### ISSUE TITLE
[Remoto] Front-end Developer na Malagueta/Br

### ISSUE THREAD

**Issue by dessimoni** [frontendbr/vagas#5944]
## Nossa empresa

A Malagueta/Br é uma agência de comunicação completa, atendendo desde 2006 empresas nacionais e internacionais de diversos portes e segmentos.

## Descrição da vaga

Estamos a procura de pessoas para ampliar nossa rede de fornecedores atuando como freelancers. Temos oportunidade para desenvolvimento de websites institucionais e landing pages para campanhas de produtos ou serviços de nossos clientes.

## Local

Remoto

## Requisitos

- HTML
- CSS
- Layouts responsivos

**Desejáveis:**
- Bootstrap / Tailwind
- Wordpress
- Figma / XD
- Git

**Diferenciais:**
- UI/UX caso queira atuar também criando layouts

## Contratação

Freelancer por demanda

## Como se candidatar

Por favor envie um email para info@malaguetabr.com.br contando um pouco da sua experiência nos enviando alguns links para trabalhos executados.

# Labels

#### Alocação
- Remoto

#### Regime
- Freela

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by Riquecelo** [comment]
Olá, vocês ainda estão aceitando candidaturas para vaga de Júnior?

**Comment by medenirodrigues** [comment]
> Olá, vocês ainda estão aceitando candidaturas para vaga de Júnior?
**Também tenho interesse em saber**

**Comment by vanessawin** [comment]
Currículo enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
