### ISSUE TITLE
[Remoto] Frontend React Developer  na ClubPetro

### ISSUE THREAD

**Issue by mateu5-francisco** [frontendbr/vagas#5945]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-developer-172315812?origin=github&medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>O <strong>ClubPetro</strong> está buscamos <strong><ins>Frontend Developer</ins></strong> para compor seu time. Buscamos pessoas apaixonadas por desenvolver e promover inovações, que possuam bom raciocínio lógico e saibam trabalhar em equipe.</p>
<p>Somos uma aceleradora de resultados para Postos de Combustíveis. Nosso propósito é escrever a mudança da história do mercado de combustíveis, colocando o revendedor como protagonista.</p>
<p>Ao atuarmos com transparência e valorizando as necessidades dos clientes, promovemos resultados expressivos, principalmente na promoção do volume de vendas e da rentabilidade do revendedor, além da criação de vantagens para os consumidores que abastecem.</p>
<p>Estamos presentes em mais de 1.100 postos de combustíveis do Brasil, revolucionando a maneira como o revendedor se relaciona com o seu cliente.</p>

## ClubPetro: 
 <p>Aceleradora de resultados para Postos de Combustíveis.&nbsp;</p>
<p>Somos companheiros do revendedor  e trabalhamos dia e noite para melhorar o resultado, levar informação e conhecimento de gestão aos nossos parceiros por meio de nossas ferramentas e tecnologias. Nosso trabalho gera resultado a curto prazo e sustentabilidade a longo prazo.&nbsp;</p><a href='https://coodesh.com/empresas/clubpetro'>Veja mais no site</a>

 ## Habilidades: 
 - React Hooks 
- React.js 
- Typescript 
- CSS 
- Rest API
## Local: 
 100% Remoto
## Requisitos: 
 - Conhecimento em ReactJS, Typescript, CSS 
- API Rest 
- Git 
- Experiência na utilização de React Hooks 
- Boa experiência na criação design responsivos
## Diferenciais: 
 - Experiência com testes automatizados usando: Cypress, Jest 
- Experiência na construção de páginas usando componentes
## Benefícios: 
 - 100% Remoto 
- Horários Flexíveis
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend React Developer  na ClubPetro](https://coodesh.com/vagas/frontend-developer-172315812?origin=github&medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
