### ISSUE TITLE
[Remoto] Front-end Developer (React) na Celerative 🇺🇸

### ISSUE THREAD

**Issue by maplessmann** [frontendbr/vagas#5949]
## About Celerative

Celerative helps you get customized remote job opportunities. We’re not just another freelance hiring platform.
We help you work on projects you want and get paid what you deserve. No matter where you live.

- We'll connect you to a global network of experts to meet, organize events and share experiences.
- A personal success manager will be assigned to you for mentorship and career advice.
- Get full visibility on your payments and collect them in the payment method of your choice.

## About The Role

> 💵  &thinsp; This is a 100% remote, full-time, long-term position, with monthly payments in USD

We are looking for a great JavaScript developer who is proficient with React.js. Your primary focus will be on developing user interface components and implementing them following well-known React.js workflows (such as Flux or Redux). You will ensure that these components and the overall application are robust and easy to maintain. You will coordinate with the rest of the team working on different layers of the infrastructure. Therefore, a commitment to collaborative problem solving, sophisticated design, and quality products are important.

## Responsibilities
- Developing new user-facing features using React.js
- Building reusable components and front-end libraries for future use
- Translating designs and wireframes into high-quality code
- Optimizing components for maximum performance across a vast array of web-capable devices and browsers

## Skills
- Experience with Web3.js
- Strong proficiency in JavaScript, including DOM manipulation and the JavaScript object model
- Thorough understanding of React.js and its core principles
- Experience with popular React.js workflows (such as Flux or Redux)
- Familiarity with newer specifications of EcmaScript
- Experience with data structure libraries (e.g., Immutable.js)
- Knowledge of isomorphic React is a plus
- Familiarity with RESTful APIs
- Knowledge of modern authorization mechanisms, such as JSON Web Token
- Familiarity with modern front-end build pipelines and tools
- Experience with common front-end development tools such as Babel, Webpack, NPM, etc.
- Ability to understand business requirements and translate them into technical requirements
- A knack for benchmarking and optimization
- Familiarity with code versioning tools such as Git

## Payment

You can set your own hourly-rate depending on the expertise and experience you have. You can also decide the amount of hours you would like to work, therefore you will earn according to these two variables.

## How To Apply

Apply exclusively through the Celerative platform at the following link: 👉 &thinsp; [Create your profile at Celerative](https://www.celerative.com/referral/dc2f087b-8d04-4900-9398-8c4b334bcee5).

After creating your account via the above link, you will receive an email with the next steps.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
