### ISSUE TITLE
Vaga inválida

### ISSUE THREAD

**Issue by fwfreitas** [frontendbr/vagas#595]
## Descrição da vaga

Atuar com desenvolvimento front-end, na criação e design para sistemas de informação, 

## Local

São Paulo - Vila Leopoldina 

## Benefícios

- Plano de saúde
- Convenio odontológico 
- Seguro de vida
- Vale Refeição
- Estacionamento

## Requisitos

**Desejáveis:**
- conhecimentos em HTML5, CSS3, Javascript avançado, Node e npm, Angular, React, VueJS, LIB de mapas, integração de APIS Rest e GIT. 

**Diferenciais:**
- Pré-processador CSS ( Sass, Stylus)

## Contratação

CLT

## Nossa empresa

Em seu 10º ano de atuação, a PSM Company é referência de mercado nos serviços especializados de Recrutamento e Seleção, Terceirização de Mão de Obra e Gestão de Pessoas.

A nossa história de sucesso, esta baseada em nosso modelo de negócios que proporcionam assertividade e qualidade no processo seletivo, baixo Turn Over e isenção de riscos e passivos trabalhistas.

Somos especializados na identificação de Talentos para as áreas de TI / Telecom como também para as áreas operacionais e administrativas.

## Como se candidatar

Por favor envie um email para vanessa.almeida@psmcompany.com.br com seu CV anexado - enviar no assunto: Front-End Developer

**Comment by LFeh** [comment]
Amigo. 
Siga os padrões na hora de criar a vaga.

`[CIDADE] Front-End Developer na [NOME DA EMPRESA]`

É a segunda vaga dessa empresa que preciso editar.

Todas as instruções estão na descrição do repositorio - https://github.com/frontendbr/vagas

**Comment by LFeh** [comment]
Outra coisa, a vaga é para trabalhar **NA** PSM Company ou é uma consultoria?

**Comment by fwfreitas** [comment]
Bom dia Felipe,

 

Peço desculpas, vou me atentar as instruções.

 

Atenciosamente,

 

 

Descrição: Francisco Freitas (2)

 

De: Felipe Fialho [mailto:notifications@github.com] 
Enviada em: quarta-feira, 11 de outubro de 2017 11:24
Para: frontendbr/vagas
Cc: fwfreitas; Author
Assunto: Re: [frontendbr/vagas] Front-End Developer (#595)

 

Amigo.
Siga os padrões na hora de criar a vaga.

[CIDADE] Front-End Developer na [NOME DA EMPRESA]

É a segunda vaga dessa empresa que preciso editar.

Todas as instruções estão na descrição do repositorio - https://github.com/frontendbr/vagas

**Comment by fwfreitas** [comment]
Bom dia Felipe,

 

A PSM Company é uma consultoria.

 

É apara atuar em um de nossos clientes, mas por normas do cliente, não podemos revelar seu nome.

 

Qualquer dúvida, á disposição.

 

Atenciosamente,

 

Descrição: Francisco Freitas (2)

 

De: Felipe Fialho [mailto:notifications@github.com] 
Enviada em: quarta-feira, 11 de outubro de 2017 11:24
Para: frontendbr/vagas
Cc: fwfreitas; Author
Assunto: Re: [frontendbr/vagas] Front-End Developer (#595)

 

Outra coisa, a vaga é para trabalhar NA PSM Company ou é uma consultoria?

**Comment by LFeh** [comment]
Entendi. Apenas vagas com nome do cliente final pode ser divulgado.

Valeu ;)

**Comment by fwfreitas** [comment]
Felipe,

 

Mas a contratação é pela PSM.

 

Dessa forma, mesmo assim, não podemos divulgar dessa forma?

 

Att.

 

Descrição: Francisco Freitas (2)

 

De: Felipe Fialho [mailto:notifications@github.com] 
Enviada em: quarta-feira, 11 de outubro de 2017 11:33
Para: frontendbr/vagas
Cc: fwfreitas; Author
Assunto: Re: [frontendbr/vagas] [São Paulo] Front-End Developer na PSM Company (#595)

 

Entendi. Apenas vagas com nome do cliente final pode ser divulgado.

Valeu ;)

**Comment by LFeh** [comment]
Não. Convencionamos na concepção desse repositório que todas as vagas deveriam ser transparentes quanto onde o candidato trabalharia.

Entendo o ponto de vocês, mas é uma coisa importante pra gente,

**Comment by fwfreitas** [comment]
Tudo bem,

 

Para as próximas, vamos nos atentar a isso.

 

Obrigado Felipe.

 

 

Descrição: Francisco Freitas (2)

 

De: Felipe Fialho [mailto:notifications@github.com] 
Enviada em: quarta-feira, 11 de outubro de 2017 11:47
Para: frontendbr/vagas
Cc: fwfreitas; Author
Assunto: Re: [frontendbr/vagas] Vaga inválida (#595)

 

Não. Convencionamos na concepção desse repositório que todas as vagas deveriam ser transparentes quanto onde o candidato trabalharia.

Entendo o ponto de vocês, mas é uma coisa importante pra gente,

**Comment by LFeh** [comment]
@fwfreitas Vamos liberar vagas como essa agora.

Desde que a contratação seja feita pela empresa anunciada :)

**Comment by fwfreitas** [comment]
Bom dia, que ótimo!

 

Geralmente nossas vagas são para contratação conosco mesmo.

 

Mas obrigado pela informação.

 

Agradeço imensamente pela ajuda.

 

Atenciosamente,

 

Descrição: Francisco Freitas (2)

 

De: Felipe Fialho [mailto:notifications@github.com] 
Enviada em: terça-feira, 14 de novembro de 2017 11:02
Para: frontendbr/vagas
Cc: fwfreitas; Mention
Assunto: Re: [frontendbr/vagas] Vaga inválida (#595)

 

@fwfreitas <https://github.com/fwfreitas>  Vamos liberar vagas como essa agora.

Desde que a contratação seja feita pela empresa anunciada :)
