### ISSUE TITLE
[Remoto] Full Stack Developer na [T2Ti.COM]

### ISSUE THREAD

**Issue by alberteije** [frontendbr/vagas#5950]
A T2Ti abriu um processo de seleção para contratar 3 Full Stack Developer no esquema Sprint Work (trabalha 3 semanas e folga 1 semana). Confira: http://t2ti.com/carreira/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
