### ISSUE TITLE
[Remoto] Front-end Developer na CWI Software

### ISSUE THREAD

**Issue by wendelgiovani** [frontendbr/vagas#5954]
> Vaga Remota durante a pandemia

## Nossa empresa

A Engenharia de Software CWI faz parte da nossa cultura e engloba o entendimento do negócio, compreensão do problema, definição de estratégia e implementação da solução para a entrega de valor.

##  Projeto Front-end em React.JS

=

## Remoto

Exemplo: Remoto ou Escritório, [ESTADO], [CIDADE], [BAIRRO]

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento Front End;
- Sólida experiência em Javascript, HTML e CSS;
- Experiência em Next.JS, React.Js

**Desejáveis:**
- Testes com Jest
- conhecimentos em cultura de code review

**Diferenciais:**
- Ter vivência em React Native

## Benefícios

- Plano de saúde
- VR de R$ 25,50/dia
- Cartão flexível
- ...

**Diferenciais:**
- Home Office
- ...

## Contratação

CLT

## Como se candidatar

Por favor envie um email para work@cwi.com.br com seu CV anexado - enviar no assunto: Vaga React aos cuidados de Wendel Dorneles

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: wendel.dorneles@cwi.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível

- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
