### ISSUE TITLE
[Remoto] Full Stack Developer na Celerative

### ISSUE THREAD

**Issue by maplessmann** [frontendbr/vagas#5955]
## About Celerative

Celerative helps you get customized remote job opportunities. We’re not just another freelance hiring platform. We help you work on projects you want and get paid what you deserve. No matter where you live.

- We'll connect you to a global network of experts to meet, organize events and share experiences.
- A personal success manager will be assigned to you for mentorship and career advice.
- Get full visibility on your payments and collect them in the payment method of your choice.

## About The Role

> 💵 &thinsp; This is a 100% remote, full-time, long-term position, with monthly payments in USD

At Celerative we make remote really work. We developed a one-stop solution that is helping software engineering companies to grow and achieve their goals. At the same time, we are a community of hackers building the future of remote work.

Right now, we are looking for a Full Stack Developer to help us to improve our platform and to develop new features, in order to make Celerative even more exciting for our customers and our expert community.

## Requirements

- Having around 1 year of frontend development experience with React.js and CSS is a must, and at least 1 year of experience with Node.js is ideal. 
- GraphQL experience would be nice but is not a hard requirement. 
- The only requirement is to take our certification in Node.js OR React.

## How To Apply

Apply exclusively through the Celerative platform at the following link: 👉 &thinsp; [Create your profile at Celerative](https://www.celerative.com/referral/dc2f087b-8d04-4900-9398-8c4b334bcee5).

After creating your profile via the above link, you will receive an email with the next steps.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
