### ISSUE TITLE
[Santa Catarina] React Native Developer na @Riderize

### ISSUE THREAD

**Issue by fabriciosautner** [frontendbr/vagas#5956]
## Nossa empresa

Somos uma plataforma esportiva para Ciclistas. Desenvolvemos todo o ecossistema através de experiências importantes para quem é ciclista. Estamos nos preparando para o lançamento mundial.

## Descrição da vaga

Participar do time de Front-ends responsáveis pela aplicação React Native que move a plataforma. E ser protagonista na primeira empresa brasileira com Gravador de Atividades (pedaladas) no próprio App.

Como será seu dia a dia:
Participar de planejamento SCRUM junto com o time de desenvolvimento
Implementar tecnologias modernas dentro de um App
Conhecer todo o ecossistema de um aplicativo
Entregar features usadas por milhares de pessoas todos os dias
Evoluir na carreira de desenvolvedor trocando experiências com outros desenvolvedores
Sentir a experiência de programar lado a lado com pessoas incríveis e divertidas

## Local

Escritório em Rio do Sul/Santa Catarina

## Requisitos

**Obrigatórios:**
- Conhecimentos em React Native

**Desejáveis:**
- Certificado Rocketseat

**Diferenciais:**
- GraphQL
- Relay/Suspense
- Recoil
- Typescript
- Realm
- AppCenter

## Salário

- De 3k a 9k de acordo com a experiência

**Diferenciais:**
- No dress-code;
- Horário flexível;
- Mac de trabalho exclusivo;
- Cidade segura (entre as 30 melhores de se viver no país)
- Custo de vida baixo
- Cidade tecnológica com frequência de eventos importantes, como o Ted Talks
- Auxílio Mudança

## Contratação

CLT ou PJ

## Como se candidatar

Por favor envie um email para contato@riderize.com com seu CV anexado - enviar no assunto: Vaga React Native

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 14 dias após cada processo.
E-mail para contato em caso de não haver resposta: fabricio.sautner@riderize.com

#### Alocação
- Alocado

#### Regime
- CLT
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by fabriciosautner** [comment]
Ainda temos vagas abertas :D

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
