### ISSUE TITLE
[Remoto] Senior / Lead Front-end React Developer @ Vigil 🇬🇧

### ISSUE THREAD

**Issue by renato-obst** [frontendbr/vagas#5957]
## Our company

Vigil is a UK-based technology consultancy and software product development company serving the UK, Mainland Europe and North America. We also have a dedicated office in Amsterdam, Netherlands, a development centre in Lisbon, Portugal and a base in São Paulo, Brazil. For some customers, we provide the talent and teams they need to strengthen their in-house development capability. For others, we offer a complete end-to-end service, providing the right strategy and execution to help them achieve their business goals.

## Job Description

You will be joining our engineering team and be a valued member working closely in a collaborative, autonomous, cross-functional team delivering relevant end-user applications to one of the biggest media companies from the United Kingdom. You will help with:
- Design, develop and deploy user experiences with a focus on usability, high availability, low latency and scalability.
- Operational responsibility for the services that are owned by your team in a DevOps culture.
- Assist in story grooming and estimation.
- Write performant and thoroughly tested code  (unit and/or functional tests as appropriate).
- Propose technical decisions and contribute to the project using software development best practices and tools.

## Local

This is a 100% remote, full-time, long-term position, with monthly payments in EUR

## What we a looking for:

- 7+ years of mobile/web UI development experience
- 3+ years of ReactJS
- Large experience with Typescript
- Expert with Redux, Hooks, and Context
- Experience with Styled Components or other CSS frameworks
- Experience in developing enterprise web applications
- Experience in frontend automated tests
- Strong English skills

**Awesome but not required:**
- OpenAPI (swagger)
- Cypress
- CI/CD pipeline
- React Testing Library
- React-Query

**What is in it for you:**

- Be part of our collegial environment where responsibility and authority is shared equally amongst colleagues and help create our company culture 
- A culture in which we don’t criticize failure but ensure we learn  from our mistakes
- An Agile environment where your ideas are welcome 
- The possibility to grow and experience different projects 
- Possibility to work from anywhere
- Ongoing Training & Mentoring
- The possibility to travel (when we are allowed)

## Hiring model and $

- PJ with a fixed value in Euros
- 20 days of paid vacation
- Value range: 3.5K to 5.5K Euros

## How to apply

Just fill a quick form here and you are done! 👉  https://www.vigil.global/seniorlead-frontend-engineer-react 

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Tech Lead
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
