### ISSUE TITLE
[Floripa/SC] Front-end Developer na ESSS

### ISSUE THREAD

**Issue by Esss0102** [frontendbr/vagas#5958]
> Vaga Remota durante a pandemia

## Nossa empresa
A ESSS é uma multinacional brasileira sediada na cidade de Florianópolis/SC. Disponibilizamos ao mercado as mais avançadas ferramentas de CAE na área de fluidodinâmica, análise estrutural, eletromagnetismo e multifísica, além de customização e desenvolvimento de softwares sob medida de acordo com a necessidade de cada cliente. Estamos presentes no Brasil e no exterior, incluindo Argentina, Chile, Colômbia, Peru, Portugal, Espanha, México e Estados Unidos.

Se você acredita que suas habilidades, talento e experiências são diferenciados para trabalhar em um time de alta performance, responsável pela resolução de problemas por meio da tecnologia e desenvolvimento de softwares, faça sua inscrição no link: https://esss.gupy.io/jobs/164807

Cultura e valores são muito importantes para a ESSS. Elas nos informam quem somos e como agimos. São crenças compartilhadas/orientações que todos seguimos quando enfrentamos um desafio ou uma decisão. Nossos valores são cruciais para promover uma cultura de sucesso para nossa empresa, sendo eles:

• Respeito integral às pessoas,
• Excelência,
• Inovação,
• Saúde corporativa e
• Foco no cliente. 

## Descrição da vaga

Se você é um entusiasta por inovação e tecnologia e busca uma empresa onde possa compartilhar ideias, conquistas e trabalhar em um ambiente saudável, onde possa se desenvolver pessoal e profissionalmente, estamos sempre com oportunidades em aberto para **Desenvolvedor de Software**. 

Você se inscreve e seu perfil ficará armazenado em nosso banco de talentos e entraremos em contato assim que surgir uma nova oportunidade alinhado com o que você traz de experiências e com o que você busca.

## Local

Floripa/SC

## Benefícios

Licença maternidade e paternidade estendidas.
Plano de Saúde com subsídio integral e sem co-participação (melhor operadora da região);
Auxílio idiomas.
Oportunidade para contribuição em projetos open source.
Incentivo a educação continuada através de cursos, treinamentos e especializações.
Incentivo a publicações, participações em eventos de tecnologia relevantes para seu trabalho.
Office com ambiente silencioso, ergonômico e moderno: salas com 4 a 6 pessoas (sem open-office).
Mais de 20 outros benefícios: vale alimentação, vale refeição, horário flexível, entre outros.

## Contratação

CLT

## Como se candidatar

Se inscreva no link: https://esss.gupy.io/jobs/164807

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
