### ISSUE TITLE
[REMOTO] Front-end Engineer na Ambizzion IT.

### ISSUE THREAD

**Issue by NicolasDurazzo** [frontendbr/vagas#5959]
## Nossa empresa

É uma empresa provedora de serviços e soluções integradas de sistemas, alinhadas com as principais estratégias corporativas através de uma equipe altamente qualificada. Nossa experiência e comprometimento traduzem o alto nível de satisfação e reconhecimento dos nossos clientes.

## Local
Remoto

## Requisitos

**Obrigatórios:**
- mínimo de 3 anos de experiência com programação
- Inglês para conversação
- React JS
- Typescript
- Javascript

## Contratação
PJ - 21k 

## Como se candidatar

Por favor envie um email para nicolas.durazzo@ambizzion.com.br com seu CV anexado - enviar no assunto:
Vaga Front-End Engineer - Github.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 48 horas após cada processo.

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
