### ISSUE TITLE
[Rio de Janeiro] Front-End Developer na Nexaas

### ISSUE THREAD

**Issue by cenoura** [frontendbr/vagas#596]
## Descrição da vaga

A Nexaas (http://www.nexaas.com) procura pessoas capazes de criar excelentes interfaces para nossos produtos, na web e no celular. Temos projetos já iniciados e também outros ainda no forno que precisam de desenvolvedores frontend para criar e implementar a experiência do usuário do início ao fim.

## Local

Escritório, Rio de Janeiro - Centro

#### Diferenciais

- Ambiente de trabalho descontraído
- Possibilidade de crescimento junto com a empresa
- Liberdade para trabalhar com as ferramentas (hardware e software) que lhe agradam
- Tempo para adequar-se ao nosso processo de desenvolvimento, com iterações semanais e acompanhamento direto de outros membros da equipe
- Benefícios (plano de saúde, vale refeição, vale transporte)
- Possibilidade de home office.

## Requisitos

**Obrigatórios:**
- ter experiência com desenvolvimento em HTML, CSS e Javascript;
- ter experiência com os frameworks jQuery, Foundation e Bootstrap;
- ter experiência com API's RESTFUL e termos relacionados (resources, AJAX, XML, JSON, HATEOAS);
- conhecer o sistema de controle de versão GIT;
- conhecer os pré-processadores SASS e LESS;
- seguir à risca os padrões web, visando manter correta a semântica dos elementos e compatibilidade entre navegadores;
- trabalhar bem em equipe, interagindo com os programadores para transformar as visões de UX em realidade
- Inglês - Intermediário

**Diferenciais:**
- Conhecer os frameworks React e AngularJS;
- Experiência com design responsivo;
- Experiência com sistemas web desenvolvidos em Ruby;

## Contratação

CLT

## Nossa empresa

A Nexaas é uma empresa de desenvolvimento de softwares em nuvem para gestão empresarial. Esqueça as velhas tecnologias e formas de pensar, aqui nós ditamos tendências e desenvolvemos soluções disruptivas que oferecem a melhor experiência para nossos usuários. Para isso aliamos tecnologia de ponta a um time de pessoas que não se conformam com a zona de conforto. Somos apaixonados pelo que fazemos, viciados em resolver problemas reais e curiosos por conhecer pessoas que tenham essa mesma garra e determinação.

## Como se candidatar

https://jobs.kenoby.com/nexaas-trabalhe-conosco/job/desenvolvedor-web-front-end/59ceae9be6dade4c6f698d2a

**Comment by talitapagani** [comment]
Vaga recomendadíssima!

**Comment by antigui22** [comment]
@cenoura o Kenoby está dando para preencher os campos vermelhos, mas não aparece nada vermelho. Tem outra maneira de aplicar?

**Comment by talitapagani** [comment]
Oi, @antigui22, qual seria este problema que está ocorrendo no Kenoby, não consegui identificar

**Comment by cenoura** [comment]
@antigui22 fizemos alguns testes e não identificamos problemas. você poderia tentar novamente, por favor? verifique também se o javascript do seu navegador está habilitado e você não está usando nenhum adblock, por favor :)
qualquer dúvida, basta entrar em contato!

**Comment by antigui22** [comment]
@talitapagani estava dizendo para preencher os campos em vermelho, e não tinham campos em vermelho, não consegui resolver nem inspecionando porém reiniciei o navegador e funcionou.

@cenoura já foi, obrigado. Consegui aplicar ontem, porém como sai da sala de aula, acabei não comentando que consegui aqui. grato a todos.

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
