### ISSUE TITLE
[Remoto] Fullstack node.js/React.js Developer na Catho Online

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#5960]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/pessoa-desenvolvedora-fullstack-pleno-130038396?origin=github&medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>Sobre o nosso propósito:</strong></p>
<p>A Catho está presente na vida das pessoas em um momento fundamental: o de conseguir um novo emprego. Afinal, o emprego muda vidas e a nossa plataforma conecta milhões de currículos a empresas cadastradas.&nbsp;</p>
<p>Mudar vidas é a nossa razão de existir. Ao unir as pessoas com as oportunidades de trabalho, a Catho possibilita a elas atender não só suas necessidades básicas e de suas famílias, como também ter a chance de crescer, produzir e realizar sonhos.&nbsp;</p>
<p>Além disso, somos parte do grupo Seek, líder global no segmento de recrutamento online, com atuação na Austrália, China, Índia e outros países.&nbsp;</p>
<p>E você, também quer ajudar a transformar vidas? Dá uma olhada na vaga abaixo:</p>
<p><strong>O que você vai fazer (além de mudar vidas, é claro): </strong></p>
<p>Como  Pessoa Desenvolvedor(a) Fullstack Sênior você irá colaborar com o time responsável por refazer uma parte do site e trabalhar com a experiência do usuário da Catho. Você terá, junto com esse time, a missão de reformular a forma que a Catho lida com usuário, garantindo que estamos prontos para o futuro mantendo as coisas atuais funcionando.</p>
<p><strong>Tecnologias que usamos:</strong></p>
<p>Grande parte das nossas aplicações são construídas  em  Node.js e React.  Valorizamos as boas práticas de programação, e buscamos sempre trabalhar com testes e monitoramento. Trabalhamos com Scrum e Kanban.&nbsp;</p>

## Catho Online: 
 <p>A Catho está presente na vida das pessoas em um momento fundamental: o de conseguir um novo emprego. Afinal, o emprego muda vidas e a nossa plataforma conecta milhões de currículos a empresas cadastradas.&nbsp;</p>
<p>Mudar vidas é a nossa razão de existir. Ao unir as pessoas com as oportunidades de trabalho, a Catho possibilita a elas atender não só suas necessidades básicas e de suas famílias, como também ter a chance de crescer, produzir e realizar sonhos.&nbsp;</p><a href='https://coodesh.com/empresas/catho-online'>Veja mais no site</a>

 ## Habilidades: 
 - Node.js 
- React.js 
- Javascript
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência com alguma linguagem focada em desenvolvimento web, com  JavaScript(Node.Js e React); 
- Conhecimento em testes (unitários, automatizados e de integração); 
- Conhecimento em  Metodologia ágil, Scrum ou Kanban; 
- Experiência com sistemas de controle de versionamento de código (ex.: Git ou outros) 
- Conhecimento em boas práticas de desenvolvimento  (SOLID, Clean Code, TDD e etc).. 
- Conhecimento em criação e configuração de pipelines CI/CD;
## Diferenciais: 
 - Conhecimentos em Docker; 
- Conhecimentos em cloud, sendo diferencial, AWS;
## Benefícios: 
 - Assistência médica (sua mensalidade fica por nossa conta e você pode estender aos seus dependentes); 
- Assistência odontológica; 
- Seguro de vida; 
- Vale transporte ou estacionamento; 
- Day off de aniversário; 
- Cartão multibenefícios; 
- Programa Lado a Lado (você pode apadrinhar uma pessoa que receberá uma assinatura da Catho); 
- Programa de Braços Abertos (contamos com o apoio de profissionais especializados em bem-estar mental para você e sua família); 
- Somos uma empresa cidadã; 
- Já fomos reconhecidos como GPTW diversas vezes; 
- Horário flexível e home office; 
- Não temos dress code.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack node.js/React.js Developer na Catho Online](https://coodesh.com/vagas/pessoa-desenvolvedora-fullstack-pleno-130038396?origin=github&medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
