### ISSUE TITLE
[Remoto] Senior Front-end Developer

### ISSUE THREAD

**Issue by andretrevas** [frontendbr/vagas#5962]
## Sobre o cargo
Como desenvolvedor front-end, você irá trabalhar na criação e desenvolvimento de uma nova plataforma, dividida em duas partes:
Pública -> Serão apenas algumas páginas, porém a tela de checkout que é a mais importante do sistema estará aqui;
Privada -> Área logada (next auth para login, já implementado), cadastro de produto, integração com outras plataforma, dashboards, entre outros;

Toda a parte de infraestrutura e back-end será desenvolvido por outro time, ou seja, o desenvolvedor front-end será responsável apenas pelo projeto do front-end. Utilizamos métodos ágeis, principalmente Scrum.
Ambiente descontraído, equipe enxuta, time focado em entregar valor para empresa e que se preocupa com o cliente.

## Procuramos alguém que
- Seja uma pessoa proativa para identificar e propor melhorias;
- Preze pela qualidade de cada entrega:
- Tenha facilidade em aprender;
- Queira fazer a diferença:
- Busque se atualizar constantemente sobre melhores práticas e formas de desenvolver o produto;
- Foque em um código limpo e bem estruturado.

## Responsabilidades
- Desenvolver soluções tecnológicas, garantindo funcionalidade, manutenibilidade, qualidade e velocidade por meio das boas práticas de desenvolvimento de sistemas;
- Conversar com a equipe de back-end/front-end e designer/UX para construir ou alterar funcionalidades de front-end com React, consumindo as APIs disponibilizadas no back-end;
- Padronizar (definir normas) e manter limpo o código front-end da aplicação.

## Requisitos

**Obrigatórios:**
- Conhecimentos avançados em Javascript e biblioteca React (principal foco de trabalho)
- Experiência com desenvolvimento web
- Experiência consolidada e comprovada com desenvolvimento front-end
- Experiência com o framework Next
- Experiência com SPA
- Conhecimento em pré-processadores CSS (Sass, Less)
- Inglês avançado para **leitura**

**Desejáveis:**
- Experiência em alguma linguagem e framework web para back-end (**PHP/Laravel**, Python/Django, Ruby/Rails e etc);
- Experiência com Server-Side Rendering (SSR), Static Site Generation (SSG), Incremental Static Regeneration (ISR)
- Experiência com Redux ou React Context API
- Experiência com componentes funcionais
- Experiência com CI/CD para melhorar o que já está implementado
- Experiência com Docker

## Contratação

PJ

## Benefícios

- Remuneração anual bem acima do teto da MEI -> Tem que ser ME

**Diferenciais:**
- horário flexível, sem ponto, dias de trabalho acordados
- equipe pequena, sem horas e horas de reuniões
- scope do projeto bem definido e elaborado por pessoas técnicas

## Como se candidatar

Por favor envie um email para andre@etecdigital.com.br com seu CV anexado - enviar no assunto: Vaga Front-end.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by andretrevas** [comment]
@felipefialho acabei de atualizar a vaga, alterando para pleno ou senior, ajustando a descrição e colocando o nome da empresa.
Na primeira postagem estávamos abrindo a empresa e acabou levando mais tempo, só ficando operacional agora em janeiro. Poderia reativar a vaga e atualizar as labels, por favor?
