### ISSUE TITLE
[Palhoça] Java/Angular - Full Stack Developer  na Peopleplan

### ISSUE THREAD

**Issue by SauloGandolfi** [frontendbr/vagas#5966]
> Vaga Presencial em Palhoça/SC
 
## Peopleplan
 
Faça parte de um team com pessoas espetaculares e extremamente experientes para trabalhar no desenvolvimento de sistemas ERP.
Estamos buscando pessoas para construir uma parceria longa e duradoura. Valorizamos sua personalidade, sua dedicação e onde você quer chegar junto com a gente.
Se curtiu e acha que esta vaga é para você, candidate-se.
 
 
## Descrição da vaga
 
Aqui na empresa o Desenvolvedor Full Stack é responsável por:
 
- Desenvolver funcionalidades e aplicações no back-end utilizando Java EE;
 
- Desenvolver funcionalidades e aplicações no front-end utilizando Angular 10;
 
- Desenvolver APIs em Java para ofertar serviços a serem consumidos por terceiros;
 
- Realizar integrações com parceiros através do consumo de APIs REST ou SOAP;
 
- Montar/Melhorar consultas SQL para otimizar determinadas funcionalidades existentes ou para novas funcionalidades;
 
- Realizar merge das versões de desenvolvimento com a versão de produção quando necessário; 
 
- Gerar versões de teste e de produção das aplicações;
 
- Manter a estrutura do GIT organizada.
 
## Local
 
Presencial, Palhoça/SC - Pedra Branca
 
## Requisitos
- Nível Superior Completo/Incompleto em Ciência da Computação, Sistemas de Informação ou áreas afins;
 
- Desenvolvimento fullstack utilizando linguagem java EE e Angular 10;
 
- Gerenciamento de controle de versões usando o GIT;
 
- Banco de dados PostgreSQL;
 
- Conhecimento em SQL;
 
- Perfil Comunicativo, dinâmico e com habilidades para trabalho em equipe;
 
- Disponibilidade para trabalhar presencialmente.
 
**Desejáveis:**
 
-Noções de boas práticas de Desenvolvimento de software;
- Noções de Android nativo;
- Conhecimentos básicos em Linux;
- Estar disposto a estudar/conhecer ferramentas e tecnologias novas, conforme necessidade da empresa, para contribuir com sua constante evolução a fim de oferecer cada vez mais serviços e produtos de excelência a seus clientes.
 
 
 
## Benefícios
 
Vale refeição
Vale transporte ou combustível
## Contratação
 
PJ ou  CLT a combinar
 
## Como se candidatar
 
Por favor envie um email para rhvagas@peopleplan.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor Full Stack
 
## Tempo médio de feedbacks
 
Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: adm@peopleplan.com.br
 
#### Alocação
- Alocado
 
#### Regime
- CLT
- PJ
 
#### Nível
 
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
