### ISSUE TITLE
[SÃO PAULO] Front-end Developer na FCAMARA

### ISSUE THREAD

**Issue by JacquelineTeixeira** [frontendbr/vagas#5971]
> Vaga Remota durante a pandemia

## Nossa empresa

Somos apaixonados por criar história.

Líder no desenvolvimento de soluções digitais, o Grupo FCamara é constituído por uma premiada empresa de tecnologia e uma Venture Builder que já fundou 8 startups, atingindo escala global.

Venha ser protagonista da sua própria história.

## Descrição da vaga

 HTML

- Javascript (ES6+)

- Experiencia com frameworks VueJs

- CSS - Pré processamento em Sass

- Teste unitário (Jest)

- Boas práticas de UX

- Ferramenta de requisições de API (Postman)

- Gerenciamento de estado (Vuex/Redux)

- Git

## Local

Remoto 

## Requisitos

**Obrigatórios:**
- HTML
- Javascript (ES6+)
- Experiencia com frameworks VueJs
- CSS - Pré processamento em Sass
- Teste unitário (Jest)
- Boas práticas de UX
- Ferramenta de requisições de API (Postman)
- Gerenciamento de estado (Vuex/Redux)
- Git

**Diferenciais:**
- Sólida experiência em Angular e React
- Experiência com backend em java
- CI/CD (Jenkins)
- SonarQube
- Configuração de Bundle utilizando Webpack

## Contratação

PJ

## Como se candidatar

Por favor envie um email para jacqueline.teixeira@fcamara.com.br com seu CV anexado - enviar no assunto: Vaga Frontend Sr

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
