### ISSUE TITLE
[REMOTO] Front-end Developer na Atlas Technologies

### ISSUE THREAD

**Issue by pedrocantarellicosta** [frontendbr/vagas#5974]
# Desenvolvedor Front End -  VueJS

Perfil preferido: Pleno e Sênior

Regime: PJ
100% Remoto - Base em Pelotas / Rio Grande do Sul

## Requisitos:
• Forte capacidade de trabalhar colaborativamente como parte de uma equipe.
• Conhecimento em HTML e CSS.
• Conhecimento Javascript moderno(ES6) e JQuery.
• Conhecimento em Design Responsivo.
• Conhecimento em padrões de CSS como BEM ou SMACSS.
• Conhecimento do uso básico de versionamento GIT.
• Conhecimento no consumo de APIs.

## Diferencial:
• Conhecimento e experiência utilizando Template Engine Blade (Laravel).
• Conhecimento em pré-processador SASS e Webpack.
• Conhecimento em frameworks como Vue.js / React.
• Conhecimento em pattern de gerenciamento de estado como Vuex / Redux.
• Habilidade e preocupação com a excelência técnica e boas práticas de desenvolvimento.
• Noções de SEO.

## Atividades
• Atuar com programação e desenvolvimento de interfaces WEB utilizando Blade Templates e Vue.js Framework.
• Trabalhar em pequenos times que utilizam metodologias ágeis para entregar valor constante aos nossos clientes.

## Benefícios
• Jornada flexível
• Day off no aniversário

## Nossa empresa
**Organizamos mercados globais através da inovação e do desenvolvimento de tecnologias.**
Nascemos em 2017, com o objetivo de inovar o mercado global por meio de tecnologias e pessoas. Buscamos entender as necessidades e as tendências do mercado para gerar valor aos consumidores através do desenvolvimento de softwares de impacto global.

Certificado no início de 2021 como Great Place to Work, a Atlas é uma empresa com altos indicativos nos aspectos de clima organizacional, remuneração, benefícios, oportunidade de crescimento, infraestrutura, transparência na gestão e autonomia dos colaboradores.

## Como se candidatar
Entre no site [clicando aqui](https://atlastechnol.com) e efetue o cadastro na plataforma kenoby selecionando a vaga da sua escolha.

Tempo médio de feedbacks: Após ser dada o inicio do processo, o processo se da em no máximo 3 etapas sendo elas com intervalo de, no máximo, 3 dias.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by pedrocantarellicosta** [comment]
Ainda está aberta!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
