### ISSUE TITLE
[REMOTO] Front-end Developer na ProjectMark 🇺🇸 💵

### ISSUE THREAD

**Issue by thiagovictorino** [frontendbr/vagas#5975]
## Nossa empresa

We are an early-stage construction tech startup with a mission to connect the construction community by providing a multi-faceted, portfolio-driven platform that allows Companies, Owners and Professionals to build industry relationships, source project teams and highlight industry accomplishments.

## Descrição da vaga
We are looking for a Senior Frontend Javascript Developer who is dedicated to the craft, writes code that they are proud of and can hit the ground running.

## Local

Exemplo: Remote

## Requisitos

**Obrigatórios:**
- Strong knowledge JavaScript, HTML, CSS with 5+ years of proven experience.
- Proficiency with SCSS and responsive and adaptive design.
- Knowledge of typescript
- Strong Experience with VueJS, React or some other Javascript framework.
- Experience working with TailwindCSS.
- Experience integrating 3rd party APIs.
- Experience working with collaborative version control.
- Excellent verbal and written communication skills in English.

**Desejáveis:**
- Laravel

## Contratação

- PJ
- Full time
- Salary: Negotiable

## Como se candidatar

Por favor envie um email para thiago@projectmark.com com seu CV anexado - enviar no assunto: Vaga Senior Frontend Javascript Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias úteis após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
