### ISSUE TITLE
[REMOTO] Front-end Developer em Crypto/Web3 na Cobogo.social

### ISSUE THREAD

**Issue by rafaelp** [frontendbr/vagas#5976]
## Nossa empresa

A cobogo.social é um dApp web3 para o DEV Protocol em que YouTubers podem monetizar o seu canal por meio de stake compartilhado.

## Descrição da vaga

Desenvolvedor para trabalhar na dApp do cobogo.social, um projeto open-source hospedado aqui:
https://github.com/cobogo-social

Pode ser *part-time*

## Local

Exemplo: Remoto.

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com Node
- next.js

**Desejáveis:**
- strapi
- vercel
- heroku

**Diferenciais:**
- google apis
- web3.js

## Benefícios
- Pagamento integral em ETH

**Diferenciais:**
- Time de 4 pessoas
- dApp internacional
- Trabalho remoto
- 1 reunião por semana
- Pagamento em ETH
- Espaço pra codar em Solidity também

## Como se candidatar

Por favor envie um email para hi@cobogo.social com suas referências

ou entrar no telegram https://t.me/cobogosocial e enviar DM para o Rafa.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
