### ISSUE TITLE
[REMOTO] Front-end Developer na HiPlatform

### ISSUE THREAD

**Issue by arthurfanti** [frontendbr/vagas#5977]
## Nossa empresa

Olá! Somos a única plataforma de Customer Experience e Gestão de Jornadas do Brasil. Transformamos interações em processos escaláveis, flexíveis e vantajo$o$ para os envolvidos, elevando as experiências entre marcas e seus consumidores por meio da nossa tecnologia. 

Aqui compartilhamos uma paixão genuína por transformar a forma como marcas e pessoas se relacionam. E com a nossa cultura, baseada nos princípios do profissionalismo, da constante evolução, da colaboração e da franqueza, já fomos reconhecidos no GPTW como uma das melhores empresas de tecnologia para se trabalhar. 💙

Atualmente, nosso time já conta com mais de 220 Hiers espalhados remotamente por todo o Brasil (e esse número segue crescendo)! 

## Descrição da vaga

Temos diversos produtos, a grande maioria em **React**. O gerenciamento de estado depende da necessidade e particularidades de cada produto, temos de tudo um pouco aqui :)

Você será responsável por:

- Planejar o trabalho de modo que sua entrega não sobrecarregue ou prejudique outras pessoas do time;
- Colaborar com outros desenvolvedores para destravar desafios técnicos;
- Participar de forma engajada em todos os rituais do SCRUM: sprint planning, reuniões de 15', retrospectiva, feedbacks;
- Desenvolver com qualidade o próprio código;
- Reportar de forma transparente e rápida as dificuldades técnicas que estejam bloqueando as entregas.

## Local

Remoto

## Requisitos

**Obrigatórios:**

- Protocolo HTTP
-  (response, request, cabeçalhos);
- Consumo de APIs REST;
- Javascript/ES6+;
- Conhecimento em algum Framework (damos preferência para React);
- HTML/CSS;
- Git.

**Desejáveis:**
- Testes unitários/integração/E2E;
- Redux/MobX/State containers;
- Bundlers (Webpack, Parcel, outros);
- Programação funcional;
- Docker.

## Benefícios

- Cartão Caju R$ 900,00
- Notebook e fone de ouvido para Home Office
- Assistência médica Unimed | Cobertura nacional (apartamento) - estendido a dependentes e 100% pagos pela Hi 
- Assistência Odontológica Porto Seguro | Cobertura nacional - estendido a dependentes e 100% pagos pela Hi
- Auxílio Creche
- Auxílio a filho com deficiência 
- Seguro de Vida
- Licença maternidade de 6 meses e paternidade de 1 mês
- Emenda entre Natal e Ano Novo, sem descontar das férias (ou seja, temos um total 40 dias de férias aqui na Hi!)
- Becare (acompanhamento médico, psicológico, nutricional e com personal trainer para promoção do bem- estar do Hier)
- Gympass

**Diferenciais:**

- Parceria com a USP e FIAP para pós-graduação e outros cursos
- Flexibilidade de horário (cenário atual com 100% de home office)
- Happy Hier Day: Ganhe 1 Day Off no mês do seu aniversário 🎉
- Revezamento nos feriados locais, de acordo com a dinâmica do time e momento da empresa
- Convênio Pleno com o Sesc
-  Parceria com a escola de idiomas ROCKFELLER

## Contratação

CLT

## Como se candidatar

Por favor envie um email para arthur.fanti@hiplatform.com com seu CV e github - enviar no assunto: Vaga Frontend

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
