### ISSUE TITLE
[REMOTO] MOBILE DEVELOPER na Agribusiness

### ISSUE THREAD

**Issue by LuciaPetrelli** [frontendbr/vagas#5979]
**DESENVOLVEDOR MOBILE
(React, React Native, NodeJs)
PLENO & SÊNIOR
CLT - REMOTO**

Estamos em busca de um(a) Dev Mobile para nos ajudar a criar produtos digitais espetaculares, com dados de IoT, push-notification, interação via QRCode e RFID, entre outras tecnologias incríveis que ajudem produtores e empresas do agro, em todos os continentes. Se deseja realmente fazer a diferença no mundo, envie seu currículo para nós!

**Experiência necessária **
Sênior - acima de 4 anos de experiência
Pleno - de 2 a 3 anos de experiência

O que você precisa conhecer
Formação na área de tecnologia;
Experiência com React ou React Native, NodeJS, Git;
Experiência com desenvolvimento de aplicativos móveis;
Prática de code review/pull request;
Experiência com testes automatizados;
Experiência em integração com API’s REST.

Pra ter aquela vantagem extra
Conhecer boas práticas de Devops e Continuous Integration;
Possuir conhecimento em Typescript, RxJS, Redux Saga, Expo, Offline-first;
Ter experiências anteriores com Apps ligados a IoT, Analytics, AI, entre outras tecnologias.
Possuir inglês intermediário.
ra isso tecnologias já adotadas pela empresa como React Native, NodeJS, JavaScript, entre outras;
Prezar pela otimização de processos de forma a evitar atividades manuais e repetitivas;
Dev mais sênior terão como missão apoiar o crescimento dos menos experientes, servindo como referência em conhecimentos e boas práticas;
Atuar junto ao PO, Designers e Analistas de Negócio para a construção dos melhores caminhos para a criação dos produtos.

Benefícios
-Ginástica Laboral duas vezes por semana.
-Previdência Privada.
-Folga no dia do aniversário.
-Parcerias de descontos com convênios.
-Pacote de benefícios tradicionais: VR/VA, Auxílio Home Office, Plano de Saúde
-Possibilidade de trabalhar 100% remoto.
-Remuneração variável

**Para se candidatar**
https://vagas.hunterco.com.br/job/611d86a6bc83ad001e09f437?c=4739

**Ou mande seu currículo para **
lucia.petrelli@parceirohunterco.com.be

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
