### ISSUE TITLE
[Porto Alegre] Front-End Developer na Pulsus.mobi

### ISSUE THREAD

**Issue by plentz** [frontendbr/vagas#598]
## Descrição da vaga

Somos uma empresa inovadora e com crescimento muito rápido, atendendo clientes de abrangência nacional e internacional, e nosso time está precisando de reforços.

Procuramos um(a) profissional com experiência em desenvolvimento front end, muito interesse em aprender e sangue frio para lidar com um software que afeta diretamente o trabalho de milhares de pessoas todos os dias! :-)

## Local

Escritório em Porto Alegre

#### Diferenciais

- oportunidade de trabalhar numa empresa em franco crescimento; com amplas oportunidades de crescimento profissional;
- trabalhar lado-a-lado com um time experiente, atendendo clientes de renome nacional e internacional e lidando com sistemas críticos para a operação do dia-a-dia;
- trabalhar com tecnologias bem recentes e as melhores práticas em desenvolvimento de software, incluindo desenvolvimento ágil, integração contínua, testes automatizados etc;
- um ambiente transparente, amigável e informal.

## Requisitos

**Obrigatórios:**
- Domínio em prototipagem
- Conhecimento de HTML5, CSS3
- Dominar conceitos e tendências do design para web e mobile, identidade visual, entendimento de padrões de cores, usabilidade (UX e UI).
- experiência em desenvolvimento, especialmente alguma experiência com aplicações web;
- capacidade de comunicação, habilidade de trabalhar e construir um relacionamento com o resto do time e com os clientes, entendendo o impacto do seu trabalho no negócio;

**Desejáveis:**
- conhecimentos em ruby on rails
- conhecimentos em javascript/react

**Diferenciais:**
- projetos opensource

## Contratação

PJ ou CLT a combinar

## Nossa empresa

Somos uma startup inovadora e com crescimento muito rápido, atendendo clientes de renome nacional e internacional, e nosso time está precisando de reforços.

Montamos um sistema completo de gerenciamento de dispositivos móveis - o http://pulsus.mobi - e já temos milhares de celulares e tablets na rua que confiam em nós para executar as mais variadas tarefas. Estamos começando a dar o próximo passo: organizar e aprender com essa quantidade enorme de dados para extrair informações relevantes.

## Como se candidatar

Por favor envie um email para diego.plentz@pulsus.mobi com seu CV anexado - enviar no assunto: Vaga Frontend UX/UI

**Comment by plentz** [comment]
Favor colocar as tags Alocado, CLT, Estágio, Júnior, PJ, Pleno, Sênior

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
