### ISSUE TITLE
[Remoto] Front-End Developer na ASAP Log

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#5980]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-developer-215303904?utm_origin=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Buscamos um Desenvolvedor Front-End para entregar o desenvolvimento das nossas aplicações do lado do cliente.</p>
<p>Se você é tecnicamente proficiente e tem um olho aguçado para o design e UI/UX, queremos você. Nesta função, você fará uma contribuição significativa para traduzir as nossas necessidades e as expectativas dos usuários em aplicações web interativas.</p>
<p>Está buscando crescimento na carreira e consolidar as suas habilidades? Então, vem com a ASAP Log!</p>

## ASAP Log: 
 <p>Somos uma logtech especializada em logística, tecnologia e varejo com a missão de revolucionar o delivery brasileiro!</p>
<p>A ASAP cresceu 36 vezes o seu tamanho após entrar para o Grupo Via. Com isso, já absorvemos mais de 60% das entregas de marcas como Casas Bahia, Ponto, Extra.com entre outras varejistas.</p><a href='https://coodesh.com/empresas/asap-log'>Veja mais no site</a>

 ## Habilidades: 
 - Javascript 
- CSS 
- RESTful
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência sólida em HTML / CSS / JavaScript 
- Consumir APIs RESTful 
- Conhecimento em controle de versões (Git, Bitbucket, Travis ou Jenkins)
## Diferenciais: 
 - Conhecimento técnico em plataformas em nuvem (AWS, DigitalOcean, Google Cloud Plataform, Azure, etc.) 
- Experiência com a metodologia SCRUM/Agile 
- Conhecimento em Jira 
- Experiência em startups ou negócios digitais
## Benefícios: 
 - Home office 
- Vale refeição 
- Vale transporte 
- Planos médico e odontológico 
- Participação nos lucros da Via 
- Gympass/Total Pass 
- Licença maternidade estendida 
- Enxoval do bebê 
- Previdência privada 
- Seguro de vida 
- Empréstimo consignado 
- SEST/SENAT 
- Benefícios e descontos em e-commerces e lojas Via e parceiros 
- Ambiente descontraído: recarregue o seu nerf, smoka o CT e paga uma rodada aí pra nós! 
- Suporte, estabilidade e oportunidades de uma gigante do varejo 
- Agilidade, simplicidade e crescimento rápido de uma startup
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Front-End Developer na ASAP Log](https://coodesh.com/vagas/frontend-developer-215303904?utm_origin=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
