### ISSUE TITLE
[Remoto] Frontend React Developer na TeamHub

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#5981]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-developer-145735852?utm_origin=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Somos um Hub de tecnologia que DESCOMPLICA a gestão de cultura para CONECTAR pessoas e MULTIPLICAR resultados.<br>O nosso foco é criar um ambiente onde a gestão da cultura seja fácil, acessível, dinâmica e de todos.</p>

## TeamHub: 
 <p>Somos um Hub de tecnologia que <strong>DESCOMPLICA </strong>a gestão de cultura para <strong>CONECTAR </strong>pessoas e <strong>MULTIPLICAR </strong>resultados.</p>
<p>O nosso foco é criar um ambiente onde a gestão da cultura seja fácil, acessível, dinâmica e de todos.</p><a href='https://coodesh.com/empresas/teamhub'>Veja mais no site</a>

 ## Habilidades: 
 - React.js 
- Rest e Restful APIs
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência no desenvolvimento frontend, aplicativos web e integração de APIs REST 
- Experiência em HTML5, SCSS (de preferência SASS), Bootstrap, JAVASCRIPT (es6) 
- Experiência em integração e testes unitários
## Diferenciais: 
 - Noções em Devops (uso de terminal linux, containers docker, processos de build e deploy automatizados, monitoria) 
- Noções de modelo de testes unitários e integrados 
- Noções de boas práticas de Engenharia de Software 
- Noções em infra-estrutura em nuvem na AWS ou equivalente
## Benefícios: 
 - Horário Flexível 
- Vale Alimentação ou Vale Refeição 
- Auxílio Home Office mensal 
- Plano de Saúde 
- Seguro de Vida 
- Equipamento ou auxílio equipamento mensal
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend React Developer na TeamHub](https://coodesh.com/vagas/frontend-developer-145735852?utm_origin=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
