### ISSUE TITLE
[São Paulo] Fullstack na Antena 1

### ISSUE THREAD

**Issue by FelixButzbach** [frontendbr/vagas#5985]
## Descrição da vaga

We need an experienced programmer that is reasonably good in front end and has a good understanding of back end stuff, and has some experience with the setup and maintenance of Linux servers.
We do all of our server management by our selfs, so in case of problems with the page, the candidate should NOT PANIC, but rather have a good understanding of where to search for the problem, how to find and analyze log files and know when a server restart is really necessary.
Our main page is on a javascript only stack using React for the front end and Node (with express) on the backend ([www.antena1.com.br](https://www.antena1.com.br)). The database is currently mysql but we might change to Mongo or similar in the future. We have some other pages that are written in PHP, mostly Wordpress (with woocommerce), but you would not directly be responsible for them. A basic understanding of PHP will be of help, nevertheless.
The next big project will be a (subscription based) members section on the page (that will also be available in the mobile apps) that offers new additional and features for the users. 

### Tasks:

- Develop and maintain new pages and features for our main page and other pages, mostly using javascript (react, node)
- Maintenance of the existing pages.
- Optimization of existing pages (Frontend+Backend+Database)
- Integration with Mobile Apps
- Development of embeddable widgets (so other pages can integrate our content)
- Development and maintenance of APIs, for example to communicate with our mobile Apps.
- Eventually development and maintenance of our mobile Apps
- Communication with third party developers (for example of our mobile Apps)
- Server maintenance and optimization, updates of software and eventually upgrades of the infrastructure
- Rescue tasks in case of server/page/software failure
- Management tasks (communication with the team, deciding task priority, implementation details, eventually business related tasks)

### Salary:

- to be combined, based on skills and experience

## Local

Presencial em São Paulo, Cidade Jardim 

## Benefícios

- Probably the best table soccer table in São Paulo
- Engaged and motivated, young team
- A LOT of work ;)
- Flexible working hours
- High degree of autonomy
- Participation in most decisions (features, tools, hardware, ...)
- Many different projects to work on
- Fun work environment
- PJ contraction

## Requisitos

**Obrigatórios:**
- Fluid in English (speaking and writing)
- 3+ years of (hands on) experience in related areas
- Experience with Node
- Experience with React
- Experience with MySql
- Experience with Javascript
- Experience with Webpack
- Experience with html and css
- Basic understanding of web security standards
- Version control
- Desire to evolve your skills and stay up to date with (web) technologies
- Strong commitment to quality (clean and readable code)
- Responsibility for your own solutions

**Desejáveis:**
- Knowledge of Linux servers (setup and maintenance)
- Knowledge of Apache and or NGINX
- Server administration via Plesk
- Git and Github
- Code testing
- Experience mentoring junior team members
- Experience leading a team
- SASS
- ES6
- Sense of creating nice UX and UI
- Experience with Agil (or similar) concepts

**Diferenciais:**
- Experience with cloud services (like AWS, google cloud, ...)

## Contratação

PJ a combinar

## Nossa empresa

We are mostly Antena 1, a Brazilian radio station with a huge online audience and several affiliates in Brazil. But besides that we have other projects that we are taking care of.

Our biggest project is our homepage [www.antena1.com.br](https://www.antena1.com.br) (React + Redux) and is served by node (+ express). We have more than 40.000 simultaneous listeners during the peak hours and we have a news section with up to date news about music and also integrate the Reuters API.
We do all the developing in house and also take care of the server.

Apart of our main page we have some side projects that use wordpress, woocommerce and codeigniter.

And we have one of the best table soccer tables here where we practice every day during lunch break.

## Como se candidatar

Por favor envie um email para felix@antena1.com.br com seu CV anexado - enviar no assunto: Vaga Fullstack

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias.

## Labels

- 🏢 Presencial
- 👨 Pleno
- 👴 Sênior
- ⚖️ PJ
- 💰 5k-10k

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
