### ISSUE TITLE
REMOTO (FRONT END DEVELOPER) KIRIHUB

### ISSUE THREAD

**Issue by gabrielanatascha** [frontendbr/vagas#5986]
FRONT END PLENO OU SENIOR

Local: 100% Remoto
Tipo de Contratação:
• Pessoa Jurídica (PJ)
• Horário Flexível

Nossa empresa - kirihub.com.br

A Kirihub é uma empresa dedicada ao desenvolvimento de soluções de inovação digital de 
maneira compartilhada e colaborativa. Somos especialistas em desenvolvimento web e cloud, 
ajudando organizações a criar e sustentar sua inovação digital. Nosso propósito é utilizar modelos 
modernos de gerenciamento para atingir os objetivos potenciais dos projetos que atuamos. 
Procuramos entender o ambiente onde estamos envolvidos, valorizando a cultura e as pessoas de 
cada organização.

O que você vai encontrar?
Você vai participar do desenvolvimento de produtos inovadores, atuando na construção de 
softwares de alta performance. No seu dia a dia, irá participar de discussões sobre as soluções de 
arquitetura de sistemas, analisar os melhores métodos para resolver problemas, avaliando 
impactos, riscos e esforço previsto. Você também irá atuar no desenvolvimento de testes para 
redução de bugs e retrabalho, automatizando processos manuais quando necessário.

Requisitos:
• Experiência com Javascript, HTML5, CSS;
• Experiência em desenvolvimento utilizando framework Angular, React e/ou Vue;
• Experiência no consumo de APIs REST;
• Experiência no uso do Git;

Desejáveis:
• Ter conhecimento prático de metodologias ágeis de desenvolvimento de software;
• Experiência em arquiteturas distribuídas, escaláveis e de alta performance;
• Conhecimento em arquitetura de microsserviços;
• Conhecimento em melhores práticas de qualidade de software, como testes automatizados, 
segurança, monitoramento e documentação técnica;
• Atuar proativamente na identificação e resolução de problemas;
• Boa capacidade de autogerenciamento;

Como se candidatar: envie um e-mail com seu currículo para gabriela@escolhacertarh.com.br

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
