### ISSUE TITLE
[Remoto] Desenvolvedor(a) Frontend Pleno em @DB1 Group

### ISSUE THREAD

**Issue by alissongusmao** [frontendbr/vagas#5988]
## Nossa empresa

Somos um grupo empresas de tecnologia, nascido no interior do Paraná, com 20 anos de experiência em desenvolvimento de software voltado para soluções de grandes empresas. Atuamos em Diversas frentes de Mercado: com Produtos ( ANYMARKET , CONSIGNET ,  Eive ) e TAMBÉM COM Serviços e Projetos Personalizados atraves da Nossa Fábrica de Software - DB1 global Software  . 

Somos mais de 500 colaboradores em todo o Brasil e até na Argentina, com escritório em Maringá / PR, Campo Grande / MS e Presidente Prudente / SP e atuação remota (home office) desde 2017. Há 11 anos consecutivos entre as Melhores Empresas para Trabalhar , segundo o GPTW. 

Somos movido por desafios diários, sempre buscando uma forma de melhorar o que já existe e criar coisas novas com qualidade! Todos (as) aqui tem autonomia e voz para dar feedbacks, testar coisas novas e ser parte dessa mudança. Aqui aprendemos uns com os outros diariamente, com um forte senso de tempo. DB1 é pra quem não quer ser mais um!

## Descrição da vaga

Buscamos um(a) profissional apaixonado(a) por tecnologia, próativo, comprometido em entregar software com qualidade, contribuindo com conhecimentos e experiências. Atuará como desenvolvedor(a) angular para customizar e evoluir um  sistema de referência no segmento financeiro no Brasil.

## Local

Remoto

## Requisitos

**Obrigatórios:**
Experiência em front de no mínimo 2 anos;
HTML;
Javascript;
CSS;
Angular 2 +;
Angularjs;
Restful API;
Conceitos de componentização;
Boas praticas de desenvolvimento.

**Desejáveis:**
Conhecimento em aplicativos financeiros;
Experiência com testes unitários. 

## Benefícios

Vale alimentação e / ou vale refeição;
Plano de Saúde e plano odontológico;
Uma trilha de carreira com Plano de Desenvolvimento Individual (PDI) e feedbacks constantes para te ajudar na sua evolução profissional;
Horários flexíveis !;
Convênio com farmácia Droga Raia, com desconto para colaboradores;
Pra celebrar seu aniversário, é possível sair um pouco mais cedo no dia para comemorar com quem quiser e organizar o que for necessário :)
Aqui você terá a oportunidade de aprender coisas novas - seja no dia-a-dia, em um Programa de Mentoria ou em um desafio do Mestre dos Códigos.
Home office como modelo de contratação. Atuamos com essa possibilidade desde 2017. Além de viabilizar a nossos colaboradores trabalhar de casa em algum dia da semana quando necessário :)

## Contratação

CLT

## Como se candidatar

Sentiu interesse na oportunidade? Envie o seu currículo no link: https://bit.ly/3GlqMMv  

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
