### ISSUE TITLE
[Remoto] React Front-end Developer na Argyle

### ISSUE THREAD

**Issue by vmesel** [frontendbr/vagas#5989]
## Descrição da vaga

We’re a remote-first, Series A fast-growing tech startup that has reimagined how employment data can be used.

Renting an apartment, buying a car, refinancing a home, applying for a loan. The first question that is asked of you is "how do you earn your money?" Wouldn’t you think that information foundational to our society would be simple to manage, transfer and control? Well, it’s not! 

Argyle is now on a mission to rebuild access into employment records. We provide businesses with a single global access point to employment data. From that access point, any business can process work verifications, gain real-time transparency into earnings and view worker profile details. 

We are a fun and passionate group of people, all working remotely from over 19 different countries.

We are scaling our engineering teams throughout 2021 and currently looking for Senior Frontend Engineers to come and join our global team.

## Local

Remote

## Requisitos

Requirements:

- 4+ years of professional experience with JavaScript and CSS

- Deep understanding of JavaScript frameworks, must include React

- Capability to contribute to the full stack development: NodeJS in the backend, React in the frontend, Jest in the test environment

- Experience with programming in Typescript is a plus

- Highly self-driven, responsible and able to function autonomously to solve problems

- Ability to effectively communicate via written and spoken in English

**Diferenciais:**
- Remote first company. Do you want to work at a beach or a mountain? As long as you have good wifi, then go for it!
- Stock Options
- Flexible holiday leave
- $1000 after a month of employment to set up your home office.
- MacBook

## Contratação

PJ a combinar

## Como se candidatar

Entre em: https://pluo.jobs/jobs/senior-front-end-engineer-argyle-3498a932/

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
