### ISSUE TITLE
[Remoto] Front-End Developer na Ambizzion IT

### ISSUE THREAD

**Issue by NicolasDurazzo** [frontendbr/vagas#5993]
## Nossa empresa

É uma empresa provedora de serviços e soluções integradas de sistemas, alinhadas com as principais estratégias corporativas através de uma equipe altamente qualificada. Nossa experiência e comprometimento traduzem o alto nível de satisfação e reconhecimento dos nossos clientes.

## Local

Remoto, mesmo após a pandemia.

## Requisitos

**Obrigatórios:**
- 3+ anos de experiência na área;
- Desenvolvimento Angular 2+ preferencialmente 7/8;
- Bons conhecimentos de CSS, HTML, API/Swagger;
- Biblioteca Liquid;
- Bitbucket, Git e Bamboo. 

## Stacks
-Angular 2+
-Ionic

## Benefícios

Para CLT:
Cartão Flash R$700,00
Auxílio Educação R$1650,00
Auxílio Home Office R$500,00
Plano de Saúde e odontológico SulAmérica.

Para CLT Flex:
Cartão Flash R$500,00
Auxílio Educação R$500,00
Auxílio Home Office R$350,00
Plano de Saúde odontológico SulAmérica.

## Contratação

CLT e CLT Flex

## Como se candidatar

Por favor envie um email para nicolas.durazzo@ambizzion.com.br com seu CV anexado - enviar no assunto:
Vaga 3 Front-End Engineer - Github.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 48 horas após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT
- CLT Flex

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
