### ISSUE TITLE
[Remoto] Mobile Developer na Ambizzion IT

### ISSUE THREAD

**Issue by NicolasDurazzo** [frontendbr/vagas#5994]
## Nossa empresa

É uma empresa provedora de serviços e soluções integradas de sistemas, alinhadas com as principais estratégias corporativas através de uma equipe altamente qualificada. Nossa experiência e comprometimento traduzem o alto nível de satisfação e reconhecimento dos nossos clientes.

## Local

Remoto, mesmo após a pandemia.

## Requisitos

**Obrigatórios:**
- 3+ anos de experiência na área;
- Proeficiência em Redux e Redux Saga ou Context API;
- Proeficiência em TDD;
- Proeficiência em TypeScript.

## Stacks
- React Native
- TypeScript
- JavaScript

## Contratação

PJ 

## Como se candidatar

Por favor envie um email para nicolas.durazzo@ambizzion.com.br com seu CV anexado - enviar no assunto:
Vaga 4 Front-End Engineer - Github.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 48 horas após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
