### ISSUE TITLE
[DESAFIOAFYA] [PESSOA DESENVOLVEDORA FRONT-END] [REMOTO] 

### ISSUE THREAD

**Issue by LuisEduardoMoraes** [frontendbr/vagas#5995]
🎯 PESSOA DESENVOLVEDORA FRONT-END 🎯

Para essa oportunidade buscamos você que é fera na área de: Desenvolvimento Front-End

**Atribuições**
Desenvolver aplicações web e mobile híbrido por meio das linguagens de programação utilizadas nas soluções digitais da empresa de forma;
Concretizar escopos de projeto prototipados pela área de Design ou de negócios;
Implementar soluções desde o front-end até o back-end;
Fornecer suporte aos usuários das aplicações, visando o cumprimento das necessidades operacionais dos clientes internos e externos;
Desenvolver utilizando métodos ágeis;
Atuar em conjunto com o time de processamento de dados.

Local
Full remoto

**Benefícios**
Convênio de saúde
Seguro de vida
Vale refeição ou vale alimentação
Auxílio creche
Participação em Lucros e Resultados (PLR)
Convênio odontológico
Gympass

**Requisitos
Obrigatórios:**
2 anos desempenhando a função de desenvolvedor de software profissionalmente

**Desejáveis:**
Conhecimentos específicos;
Lógica de programação;
Versionamento de código;
API Rest;
Design Responsivo;
HTML;
Javascript;
CSS;
React;
Redux;
Usabilidade;
Experiência do Usuário.

Contratação CLT

**Nossa empresa**
Com mais de 20 anos de história, a Afya é o maior grupo de educação e serviços em saúde do país. Nossa trajetória começou com o desejo de tornar o ensino médico mais acessível à população. Desde então, o trabalho de toda a nossa equipe foi e continua sendo em prol de um mundo com mais (e melhor!) educação, saúde e bem-estar.

Optamos por realizar em 19 de julho de 2019 uma oferta pública de ações (IPO, na sigla em inglês) na Nasdaq, bolsa de valores norte americana, que tem como principal característica reunir empresas especializadas em alta tecnologia. Foi um passo coerente com o propósito de aliar educação médica de qualidade com uso intensivo de tecnologia.

O IPO da Afya foi o primeiro, no ano, feito por uma empresa brasileira naquela bolsa, e a empresa se destacou como a primeira empresa especializada em educação médica, em termos globais, a negociar ações na Nasdaq.

Como se candidatar
Envie um email para luis.eduardo@afya.com.br com seu CV anexado - enviar no assunto: VAGA DEV FULLSTACK ou se candidate no: https://afya.gupy.io/jobs/1210068

#venhaserafya #sejaafya #afyaeducacional #souafya 

🏢 Flexível
🏢 Remoto
👨 Pleno
👴 Sênior
⚖️ CLT
💰 8k-10k

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
