### ISSUE TITLE
[SP] Desenvolvedor Full Stack @DIGI

### ISSUE THREAD

**Issue by logeraldi** [frontendbr/vagas#5998]
O Grupo Digi está em busca de um Desenvolvedor Full Stack - Pleno/Sênior
Programador com experiência em Laravel PHP 6+ seguindo os padrões do framework e utilizando o poder que o mesmo oferece (Eloquent, Queues, Jobs, Events, Listeners, Commands e etc)
Requisitos:
Experiência em projetos utilizando PHP 7+
Experiência em projetos utilizando Laravel Framework 6+
Sólido conhecimento utilizando MySQL
Bons conhecimentos em HMTL, CSS e Javascript
São considerados diferenciais os conhecimentos em:
 
Tailwind Css
Vue js
Inertia js
Node js
MongoDB
Redis
**Enviar pretensão salarial no PJ.**
Benefícios: Recesso remunerado, Teleterapias online, Day off e Licença Paternidade.
Trabalho: Home office
Interessados: Enviar CV para lorraine@grupodigi.com.br

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
