### ISSUE TITLE
[REMOTO] Tech Lead Front-end na Ally Hub

### ISSUE THREAD

**Issue by LauraGual** [frontendbr/vagas#5999]
## Nossa empresa

Criada com essa missão de conectar o mundo através da educação internacional, a Ally Hub é uma Startup de Ribeirão Preto em plena expansão e que está passando por grandes mudanças, sendo o nosso time de Dev a parte central! Estamos em um momento de construção de um novo projeto do zero, que pode mudar a forma de se promover intercâmbio no Brasil e no mundo. E pra isso precisamos de alguém que encabece esse projeto com a gente. Bora nessa?
Com uma cultura de muita proximidade e colaboratividade, mesmo sendo 100% home office, a gente dá boas risadas e trabalha juntos com gosto. Bora dale!

## Descrição da vaga

Delinear estratégias para criação de novo projeto, contribuindo ativamente com ideias, estratégias, e tecnologias, junto ao nosso CEO e CTO
Escrever códigos com autonomia e relativa independência
Escrever códigos e bibliotecas reutilizáveis de acordo com um padrão que torna rápida e fácil a manutenção do código no futuro;
Resolver os bugs identificados;
Programar interfaces Web com autonomia;
Fazer code reviews de juniores seguindo as boas práticas;
Coordenar e promover suporte aos juniores da área;
Sentar-se com o P.O  e CTO para discutir as propostas a serem implementadas;
Otimizar aplicações para a melhoria de performance;

## Local

Exemplo: Remoto 

## Requisitos
React.js (jsx, hooks, UseEffects, props, fragments, react-router)
HTML5, CSS (Sass, Less, PostCss)
Styled-Component (javaScript Styled)
Experiência com Design System (Ant Design / Material UI)
Práticas de SEO, responsividade de interface(flex/ grid. Mobile first). Uso de unidades responsivas (vmax, vmin, rem, em)
Arquitetura FrontEnd (Store: Redux-Saga)
Conhecimento na Linguagem JavaScript
Conhecimento Linguagem TypeScript
Consumo e Design de API Rest (tools: Swagger, Postman, Insommia)
TDD (Jest, Enzime, React Test library)
Design Patterns (MVP, MVVM, MVC, Duck pt.)

**Obrigatórios:**
- 3 anos de experiência com ReactJs

**Diferenciais:**
- Experiência com liderança
- Conhecimentos em Laravel
- Inglês intermediário
- Conhecimentos básicos de design (UX/ UI)
- Portfólio de projetos atualizado

## Benefícios e Diferenciais

- 100% Homeoffice
- Clima descontraído e colaborativo
- Contato próximo com os fundadores
- Possibilidade de crescimento
- Contratação CLT 40 horas semanais (estamos abertos a contratação PJ)
- Salário + Vale Alimentação/Refeição (Flash) + Convênio Saúde (Bradesco)

## Contratação

PJ ou CLT (a combinar)

## Como se candidatar

Por favor envie um email para laura@allyhub.co com seu CV anexado - enviar no assunto: Vaga Tech Lead
Ou, faça sua inscrição no link: https://allyhub.co/tech_lead_frontend.html 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.
E-mail para contato em caso de não haver resposta: laura@allyhub.co

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
