### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor Front-End Pleno

### ISSUE THREAD

**Issue by viniciusdocanto** [frontendbr/vagas#6]
## Descrição da vaga

Vaga de desenvolvedor front-end para projetos e manutenção de sites em wordpress.

## Local

Alocado: Flamengo, Rio de Janeiro - RJ

## Benefícios

- Vale-transporte
- Flexibilidade de horário, respeitando à jornada de trabalho. (Sim, aqui você NÃO será escravo e NÃO precisará trabalhar 10 ou mais horas por dia.)
- Perspectiva de aumento com base no desempenho e produtividade.
- gratuidade nos cursos próprios da M2BR Academy.

## Requisitos

Obrigatórios
- Domínio completo de HTML/CSS, criando códigos semânticos a partir de PSDs.
- Domínio de WordPress para construção e adaptação de temas
- Forte conhecimento em Javascript, tanto nativo quanto JQuery.

Desejáveis
- Experiência com Mobile, noções de PHP.
- Experiência com versionamento (git)
- Trabalhar bem em equipe, ter boa comunicação e grande atenção a detalhes.

## Contratação

CLT (salário compatível com o mercado)

## Como se candidatar

Acesse este link e preencha o formulário. http://vagas.m2br.com/vagas/vaga-front-developer/

**Comment by eduardojmatos** [comment]
:+1:

**Comment by charlescarrari** [comment]
:+1:

**Comment by Mendrone** [comment]
:+1:

**Comment by LFeh** [comment]
A vaga foi preenchida?

**Comment by viniciusdocanto** [comment]
@LFeh a vaga foi congelada.

**Comment by LFeh** [comment]
Deixa aberto ou fecha por enquanto?

**Comment by viniciusdocanto** [comment]
@LFeh pode fechar.

**Comment by LFeh** [comment]
Beleza, se retomar a vaga me avisa que eu abro novamente ;)

**Comment by camilatigre** [comment]
@viniciusdocanto 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

**A pessoa que preencheu a vaga foi encontrada através desta issue?**
a) Sim
b) Não
c) Não tenho certeza

**Comment by viniciusdocanto** [comment]
@camilatigre a vaga foi congelada, não foi preenchida.
