### ISSUE TITLE
[Remoto] Senior Front-end Developer @ SparkPost (a MessageBird company) 

### ISSUE THREAD

**Issue by AurelienArnouxSRE** [frontendbr/vagas#6000]
Please apply directly through this link: [https://grnh.se/8b03fe472us](url)

Senior Front-end Developer @ SparkPost (a MessageBird company)  

🏢 Remoto
🗣️ In English 
👴 Sênior
⚖️ CLT

Atribuições
You will work within an agile software engineering team to create high quality & compelling front-end user experiences that delight our customers. Software development includes single-page apps, content management systems (CMS) and technical infrastructure. 
Collaboration within the team and with our partners is essential (Product, Project Management, other teams) for all activities: requirements analysis, prototyping, architecture, estimates, documentation, coding, and peer reviews. Unit, functional, and performance testing.
Automation of development, build, testing, and deployment & operations processes.
Operational support of team services, including building, managing, monitoring and supporting infrastructure necessary for team services.

Full remoto

Requisitos
4+ years of professional experience building and maintaining a production application using a modern web framework (React, Vue, etc.)
a Bachelor's degree in Computer Science (or related field) from an accredited college or university or relevant work experiences
2+ years of professional experience building and maintaining a production website using a content management system (Wordpress, Contentful, etc.)
1+ year of experience working in the open or contributing to open source software
Experience working in an Agile environment using Kanban for process tracking
You value continually improving yourself, your environment, your team and your customer's experience. You have an urge to produce high quality production web applications and to learn from, teach and grow with us.
You will have an enduring interest in producing customer-centric user experiences, strong working knowledge of HTML, CSS and component-based UI architectures. 
You will have some experience with popular content management systems, search engine optimization, and modern APIs. 

Contratação CLT

SparkPost is the industry’s most trusted email optimization platform. SparkPost helps senders reliably reach the inbox with powerful solutions to help them plan, execute and optimize their email programs. The SparkPost platform is powered by the industry’s largest data network, a team of email experts to help brands elevate every aspect of their email program, and a security and compliance posture to support even the most regulated industries. SparkPost is the world’s largest sender, delivering 40% of all commercial email - 4-5 trillion sends annually - and also boasts the world’s largest data footprint to help enterprise-level brands make data-driven decisions to improve their email performance. The world’s most sophisticated senders, including The New York Times, Zillow, Adobe and Booking.com trust SparkPost to elevate their email.

Please apply directly through this link: [https://grnh.se/8b03fe472us ](url)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
