### ISSUE TITLE
[Florianópolis/SC] Full-stack Developer na ESSS

### ISSUE THREAD

**Issue by Esss0102** [frontendbr/vagas#6006]
> Vaga Remota durante a pandemia

## Nossa empresa

A ESSS é uma multinacional brasileira sediada na cidade de Florianópolis/SC. Disponibilizamos ao mercado as mais avançadas ferramentas de CAE na área de fluidodinâmica, análise estrutural, eletromagnetismo e multifísica, além de customização e desenvolvimento de softwares sob medida de acordo com a necessidade de cada cliente. Estamos presentes no Brasil e no exterior, incluindo Argentina, Chile, Colômbia, Peru, Portugal, Espanha, México e Estados Unidos.

## Descrição da vaga

Estamos com uma oportunidade em aberto para Desenvolvedor Back/Front Pleno em Florianópolis - SC.

O profissional irá trabalhar na equipe de IT, provendo soluções internas para melhorar os processos da operação e integração entre sistemas, que incluem as seguintes atividades:

Levantamento de requisitos de software;
Customizações no CRM;
Desenvolvimento, manutenção e integração de software;
Suporte a clientes internos;
Habilidades de comunicação verbal e escrita para trabalhar com diferentes áreas da empresa;

Tecnologias que utilizamos:

Salesforce (Apex, SOQL, trigger, schedule, classes, VisualForce Pages etc);
PHP, Javascript, MySQL, SQL Server, Rest APIs;
Testes automatizados (unitários, integração e end-to-end);
Jira, Jenkins;

## Local

Florianópolis/SC

## Requisitos

Desejável experiência prévia de 3 anos;
Conhecimento de Banco de Dados;
Vivência em análise e mapeamento de processos;
Disposição para aprender e estar aberto a novas linguagens e tecnologias;
Não é necessário conhecimento avançado nas tecnologias listadas acima, entretanto experiência prévia será considerada.

## Benefícios

Disponibilizamos:

Home-office híbrido, alternando o trabalho em ambiente remoto e no escritório (durante a pandemia estamos completamente remotos).
Licença maternidade e paternidade estendidas.
Plano de Saúde com subsídio integral e sem co-participação (melhor operadora da região);
Auxílio idiomas.
Oportunidade para contribuição em projetos open source.
Incentivo a educação continuada através de cursos, treinamentos e especializações.
Incentivo a publicações, participações em eventos de tecnologia relevantes para seu trabalho.
Office com ambiente silencioso, ergonômico e moderno: salas com 4 a 6 pessoas (sem open-office).
Mais de 20 outros benefícios: vale alimentação, vale refeição, horário flexível, entre outros.

Se você acredita que suas habilidades, talento e experiências são diferenciados para trabalhar em um time de alta performance, responsável pela resolução de problemas por meio da tecnologia e desenvolvimento de softwares, faça sua inscrição no link: https://esss.gupy.io/jobs/1281649

## Contratação

CLT

## Como se candidatar

Link de inscrição: https://esss.gupy.io/jobs/1281649

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
