### ISSUE TITLE
[Remoto] Frontend Angular Developer na Lastlink

### ISSUE THREAD

**Issue by quetlinkober** [frontendbr/vagas#6008]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-angular-developer-194754591?utm_origin=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>Lastlink</strong> está buscando <strong><ins>Frontend Angular Developer</ins></strong> para compor seu time!</p>
<p>Olá, somos inovadores, respiramos a economia da paixão, e ajudamos criadores de conteúdo a impactar a vida de seus fãs. ��</p>
<p>Nascemos para oferecer soluções digitais que permitam tornar ainda mais próxima a conexão entre o produtor de conteúdo e suas comunidades. Estamos transformando o mercado de trabalho brasileiro, permitindo que pessoas possam empreender fazendo o que mais amam.</p>
<p>Nesta função, você fará uma contribuição significativa para traduzir as necessidades de nossos clientes e as expectativas dos usuários em aplicações web interativas, utilizando como framework o Angular 11.</p>

## Lastlink: 
 <h6><strong>LASTLINK</strong></h6>
<p><strong><em>CRIANDO CONEXÕES CONSCIENTES</em></strong></p>
<p>Conexão e proximidade é o que nos move.</p><a href='https://coodesh.com/empresas/lastlink'>Veja mais no site</a>

 ## Habilidades: 
 - Javascript 
- HTML 5 
- CSS 3 
- GIT 
- Angular 11 
- Typescript
## Local: 
 100% Remoto
## Requisitos: 
 - Javascript, HTML5 e CSS3 (Bootstrap, Sass e Less);  
- Ter conhecimento em versionamento de código (GIT); 
- Ter experiência com Angular, Bootstrap, CSS e Typescript; 
- Ter boa comunicação e capacidade de trabalho em equipe; 
- Seguir as tendências do mercado e que ser capaz de se adaptar rapidamente a novas tecnologias; 
- Ter senso de organização, atenção a detalhes e foco; 
- Inglês técnico intermediário (capaz de ler e escrever, será utilizado principalmente para estudo e leitura de documentações).
## Diferenciais: 
 - Tiver noções de docker e linux; 
- Tiver noções de cloud e bancos No-SQL; 
- Já tenha trabalhado em uma equipe ágil.
## Benefícios: 
 - Liberdade, flexibilidade e poder de escolha = eu sendo eu, trabalhando de onde eu quiser; 
- Auxilio home-office (R$ 120,00), vale cultura (R$ 50,00) e cuidados com saúde e bem-estar; 
- Vale refeição e/ou alimentação (sem desconto – R$ 30,00 por dia); 
- Plano de saúde subsidiado pela empresa; 
- Cultura que valoriza o 1:1; feedback; diversidade; inclusão; causas sociais e valores humanos; 
- Meditação semanal; 
- Salário competitivo / CLT.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Angular Developer na Lastlink](https://coodesh.com/vagas/frontend-angular-developer-194754591?utm_origin=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
