### ISSUE TITLE
[São Paulo] Front-End Developer Pleno na CARGOBR 

### ISSUE THREAD

**Issue by allangrds** [frontendbr/vagas#601]
## Descrição da vaga
O profissional será responsável pelo front-end de uma startup de tecnologia no ramo de logística.

## Local
**100% Presencial**(São Paulo,  Av. Paulista, 171 - Bela Vista, São Paulo - SP)

## Benefícios
- Vale transporte;
- Vale refeição de R$ 18,50 ao dia;
- Plano de saúde;
- Refeitório no local.

## Requisitos
**Obrigatórios:**
- Javascript;
  - NPM;
  - React;
  - Gulp;
  - Webpack;
  - ES6;
- Integração com API's Rest;
- Controle de versionamento com GIT.

**Desejáveis:**
- Saber prototipar telas;
- Saber analisar problemas dos usuários e encontrar melhor forma de introduzir tecnologia para resolvê-lo;
- Testes unitários;
- Testes E2E.

## Contratação
CLT.

## Nossa empresa
Somos uma startup pioneira em cotação e contratação de frete online no Brasil! Nossa grande paixão é tecnologia e nossa vocação é unir embarcadores com transportadoras, desburocratizar o processo e facilitando a comunicação entre eles. Nós vamos digitalizar todo o processo logístico! Sabemos disso porque acordamos e vamos dormir pensando em como vamos melhorar a vida dos nossos parceiros, não por obrigação, mas porque realmente gostamos disso. Aliás, fazemos sempre o que gostamos, afinal, a coisa mais importante é ser feliz e acreditamos que ninguém é feliz fazendo algo que não gosta.

## Como se candidatar
Enviar o CV ou portfolio para ti@cargobr.com com o assunto "Vaga Front-end - CARGOBR".

**Comment by Finacio** [comment]
Galera o e-mail está voltando

**Comment by allangrds** [comment]
@Finacio Tente novamente, por favor. Estávamos com problema nele.

**Comment by Finacio** [comment]
@allangrds  Enviei

**Comment by allangrds** [comment]
@Finacio pedimos perdão. Mudamos o email para ti@cargobr.com

**Comment by gabriel-brito** [comment]
Pô, que vaga bacana! Chegando em casa eu já mando o curriculum! 😄

**Comment by allangrds** [comment]
@LFeh Mudei o título para "Pleno". Se puder

**Comment by allangrds** [comment]
Vaga encerrada.
