### ISSUE TITLE
[Remoto] Front-end KnockoutJS Developer na Ília

### ISSUE THREAD

**Issue by fagnerpelicioni** [frontendbr/vagas#6010]
## Nossa empresa

Você terá a oportunidade de fazer um trabalho que impacta a vida das pessoas. É a chance de resolver problemas reais, com diversos desafios que irão trazer crescimento para você e sua carreira.
Temos um ambiente amigável, solidário e aventureiro. Aqui todo mundo anda lado a lado. Errar, aprender e evoluir em conjunto é algo intrínseco da nossa cultura.
Gostamos de trabalhar com gente diferente. Aqui você irá conviver com pessoas de diversas origens, experiências, habilidades e perspectivas.
Na ília, todo mundo tem as mesmas oportunidades de crescer e compartilha um mesmo objetivo: tornar o mundo surpreendente mais simples.

## Descrição da vaga

Como desenvolvedor Front-end, você irá auxiliar na escolha da tecnologia mais adequada no front-end. Auxiliar na validação de novas libs e serviços. Desenvolvimento de novas funcionalidades. Aplicar melhores práticas de desenvolvimento e disseminar conhecimento e melhores práticas.

## Local

Full Remoto.

## Requisitos

**Obrigatórios:**
- Desenvolver utilizando KnockoutJS, HTML, CSS, etc
- Experiência profissional com desenvolvimento de frontend
- Design Patterns
- Domínio com Git
- Design System
- Testes unitários

**Diferenciais:**
- Metodologias ágeis, de preferência Scrum
- OCC da Oracle

## Benefícios

- Contrato de Trabalho CLT - 40h semanais;
- Assistência Médica e Odontológica extensivo aos dependentes;
- Vale Refeição/Alimentação;
- Seguro de vida;
- Gympass
- Language Academy com aulas, atividades e mentoria para estudar línguas;
- Programa de premiação a indicação de outros profissionais;
- Fóruns Técnicos: Neles o time compartilha práticas, estudos, projetos e ideias;
- Grupos de Chapter: Reúnem pessoas com skills similares para compartilhamento de ideias, práticas e experiências;
- Seu Niver, seu bolo!
- Byod: Alugamos o seu notebook pessoal (valor mensal) ou disponibilizamos uma máquina da empresa (livre escolha).

## Contratação

CLT

## Como se candidatar

https://boards.greenhouse.io/ilia/jobs/4156402004?gh_src=eb869e8c4us

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
