### ISSUE TITLE
[Remoto] Front-end Tech Lead na Ília

### ISSUE THREAD

**Issue by fagnerpelicioni** [frontendbr/vagas#6011]
## Nossa empresa

Você terá a oportunidade de fazer um trabalho que impacta a vida das pessoas. É a chance de resolver problemas reais, com diversos desafios que irão trazer crescimento para você e sua carreira.
Temos um ambiente amigável, solidário e aventureiro. Aqui todo mundo anda lado a lado. Errar, aprender e evoluir em conjunto é algo intrínseco da nossa cultura.
Gostamos de trabalhar com gente diferente. Aqui você irá conviver com pessoas de diversas origens, experiências, habilidades e perspectivas.
Na ília, todo mundo tem as mesmas oportunidades de crescer e compartilha um mesmo objetivo: tornar o mundo surpreendente mais simples.

## Descrição da vaga

Como Desenvolvedor Frontend (Design System), você fará parte do time de Enablers de Frontend, um time cross funcional dedicado a criação de componentes e padrões que aceleram o processo de desenvolvimento das squads da Livelo.

Nós criamos recursos e guidelines para designers e desenvolvedores para criação de sistemas consistentes, escaláveis e com experiência padronizada e acessível.

Estamos em busca de um desenvolvedor para se juntar ao nosso time e ajudar-nos a criar nossa biblioteca de componentes reutilizáveis e positivamente impactar o desenvolvimento das demais equipes.

## Local

Full remoto.

## Requisitos

**Buscamos por alguém com:**
- Entendimento das demandas de negócio e implementação do front-end buscando prover a melhor experiência digital e encantar os usuários;
- Desenvolver componentes reutilizáveis (no Design System) que sirvam como base para as demais equipes de desenvolvimento;
- Transformar componentes de design em código com alta fidelidade e qualidade;
- Validar e garantir a performance, boas práticas de desenvolvimento, qualidade do código, cobertura de testes, preparação para deploy e outros aspectos técnicos da camada de front-end;
- Escrever documentações e changelogs de fácil entendimento; 
- Definir soluções de forma propositiva, documentar e apresentar as suas sugestões/ideias;
- Atuar em colaboração com a equipe e cliente buscando atingir juntos os melhores resultados possíveis;
- Participar e colaborar com os Squads Ágeis em seus rituais;
- Participar do processo de code review.

**Diferencial:**
- Experiência no desenvolvimento front-end utilizando React ou React Native;
- Experiência em desenvolvimento com JavaScript avançado;
- Experiência em desenvolvimento com Typescript;
- Experiência no desenvolvimento front-end utilizando HTML5, SASS/SCSS e Styled Components;
- Experiência no desenvolvimento front-end responsivo e/ou escalável;
- Familiaridade com consumo de API´s;
- Conhecimentos em boas práticas para reutilização de código, componentes e clean code;
- Conhecimentos de ferramentas de versionamento de código e geração de changelogs;
- Conhecimentos em metodologia ágil para o desenvolvimento de software;
- Forte entendimento de como criar componentes de alta qualidade, reutilizáveis e acessíveis;
- Familiaridade com tecnologias, práticas e ferramentas de Design System (Storybook, Style-Dictionary);
- Conhecimentos em Atomic Design;
- Experiência com outras linguagens ou frameworks front-end ou back-end;
- Experiência com testes automatizados e code coverage para front-end (Jest + RTL);
- Experiência com CI/CD (Jenkins);
- Experiência com configurações avançadas das ferramentas (Webpack, Metro, Jest). 

## Benefícios e Incentivos

- Contrato de Trabalho CLT - 40h semanais com jornada flexível, sendo executado 100% de forma remota;
- Assistência Médica e Odontológica extensivo aos dependentes;
- Vale Refeição/Alimentação;
- Seguro de vida;
- Gympass
- Language Academy: Programa de incentivo ao aprendizado de outras línguas, com atividades de mentoria e na plataforma Go Fluent;
- Programa de premiação a indicação de outros profissionais;
- Fóruns Técnicos: Neles o time compartilha práticas, estudos, projetos e ideias;
- Grupos de Chapter: Reúnem pessoas com skills similares para compartilhamento de ideias, práticas e experiências;
- Seu Niver, seu bolo!
- Byod: Alugamos o seu notebook pessoal (valor mensal) ou disponibilizamos uma máquina da empresa (livre escolha).

## Contratação

CLT

## Como se candidatar

https://grnh.se/32d643d24us

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
