### ISSUE TITLE
[REMOTO] Front-end Developer Sr na TownSq

### ISSUE THREAD

**Issue by RecrutamentoTownSq** [frontendbr/vagas#6016]
## Nossa empresa

Na TownSq queremos que as pessoas se sintam realmente parte da comunidade que vivem. Nos dedicamos a conectar síndicos, vizinhos e todos os integrantes do condomínio, através de ferramentas e serviços.

## Descrição da vaga

Estamos buscando Dev front-end  para fazer parte de nossa comunidade. Se você tem paixão por web, é incansável na busca pela experiência do usuário perfeita e quer transformar a vida em comunidade através de produtos digitais, vem para a TownSq!

**Como será seu dia a dia:**

- Arquitetar e desenvolver nossos produtos web (Angular, RxJs, Nx workspaces, NgRx, Jest, Cypress);
- Trabalhar de perto com o time de Design e Produto para entregar novos produtos e funcionalidades;
- Colaborar com times pequenos em um ambiente ágil;
- Ser responsável pela saúde do código dos nossos projetos através de boas práticas de desenvolvimento.

## Local

100% remoto. 
Escritório disponível para utilização híbrida (sem obrigatoriedade) em Porto Alegre/RS.

## Requisitos

**O que esperamos de você:**

- Experiência com framework Angular;
- Fluência em engenharia de software e design patterns;
- Sólidos conhecimentos de JS;
- Inglês avançado – principalmente para conversação.

**Você vai se destacar se tiver:**

- Experiência com framework React;
- Unit Tests com Jasmine/Jest.

## Benefícios (contrato CLT)

- Plano de saúde Unimed (opcional)
- Plano odontológico Unimed (opcional)
- VR/VA Caju Benefícios de R$ 24,10/dia
- Auxílio creche (regras específicas para aderir)
- Creditas (Crédito consignado, antecipação de salário)

**Diferenciais:**

- Comunicação horizontal;
- Liberdade para ser quem você é e expor suas ideias;
- Carga horária reduzida para 40h semanais, com horários flexíveis de entrada, saída e intervalo ;
- Oportunidade para se desenvolver e criar;
- Equilíbrio entre vida pessoal X trabalho;
- Incentivo diário para você se arriscar e crescer;
- Boas risadas;
- Metas desafiadoras;
- E muito senso de comunidade.

## Contratação

CLT ou PJ.

## Como se candidatar

Por favor envie um e-mail para sejaumninja@townsq.com.br com seu CV anexado - enviar no assunto: Front End Sr. 
Ou, através de nosso site https://www.townsq.com.br/sobre-nos/

#### Regime
- CLT
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
