### ISSUE TITLE
[REMOTO] Front-End Developer React.js na FOHAT

### ISSUE THREAD

**Issue by NovareRH** [frontendbr/vagas#6018]
## Nossa empresa

A Fohat eTech Global é uma energytech brasileira que transforma inteligência energética em produtos digitais com o propósito de virar a chave do Mercado de Energia, trazendo a geração e a comercialização 100% do modelo analógico para o digital. Concentra o desenvolvimento das soluções de inovação com base tecnológica avançada da Fohat Corporation, think thank de energy intelligence que atua globalmente. Para entregar as soluções que ajudam a gerar uma energia mais barata, um mercado mais democrático e preservação de recursos naturais, a Fohat eTech Global oferece um ambiente de trabalho super preparado para o seu time de profissionais transformar inquietude, diferentes pontos de vista e criatividade em inovação dentro de um clima de acolhimento nas relações.

## Descrição da vaga

Desenvolver e dar manutenção nas aplicações para o produto.

## Local

Remoto

## Requisitos

Experiência em:
﻿- React.js;
﻿- Bibliotecas de interface - Bootstrap, MaterialUI, Tailwind, Bulma, etc;
﻿﻿- HTML5, Javascript ES6 e CSS3;
﻿﻿- APIs (Rest e/ou Angular).
﻿﻿
Conhecimento em:
﻿﻿- TypeScript;
﻿﻿- Frameworks - Vue.js e/ou Angular;
﻿﻿- Git e melhores práticas de versionamento;
﻿- Metodologia e ferramentas ágeis: Scrum, Kanban, Jira.﻿
﻿
⚠  Mínimo de 5 anos de experiência nas tecnologias da vaga.

**Desejáveis:**
- Ter participado de projetos com desenvolvimento de sistemas Web para ambientes críticos como: Internet Banking, Plataformas de Investimentos, E-commerce, Plataforma de Criptoativos ou Home Brokers.  

**Diferenciais:**
- Inglês para área técnica.
- Git e as melhores práticas de versionamento (Gitflow)

## Benefícios

- Empresa investe em treinamentos de inovação, agilidade e Gestão de Pessoas. 
- Conta também com programas de qualidade de vida como Ioga, meditação e saúde mental.
- Fornece equipamento para trabalho remoto.

## Contratação

- PJ - A partir de 10k

## Como se candidatar

Aplique para a vaga [por aqui](https://www.careers-page.com/novare-rh/job/3X5358) .

#### Alocação
- Remoto

#### Regime
- PJ 

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
