### ISSUE TITLE
[Remoto] Front-end Developer na @Ewally

### ISSUE THREAD

**Issue by EderMiola** [frontendbr/vagas#6019]
> Vaga Remota

## Ewally
Somos agentes de transformação no setor de serviços financeiros. Oferecemos soluções inovadoras de forma ágil, prático e segura.

## Descrição da vaga
Atuará no desenvolvimento de novas features e manutenção das já existentes em nosso sistema, passando por APIs, integrações com parceiros do setor financeiro e ferramentas internas. Deverá projetar e implementar recursos e componentes de frontend. Trabalhará em sistemas altamente escaláveis que devem ser rápidos e seguros. Interagir com a equipe de produto para entender melhor os requisitos. Estudar e aprender novas tecnologias para melhorar nossos sistemas e processos.

## Local
Remoto

## Requisitos
**Obrigatórios:**
React.js
Metodologias ágeis

**Desejáveis:**
Arquitetura de micros serviços e Serverless
Nuvem AWS
Bancos de dados não-relacionais (DynamoDB)
Bancos de dados relacionais (MySQL)
TDD

## Benefícios
Plano de saúde Sulamérica 100% pago pela Ewally
Férias remuneradas

## Contratação
PJ

## Como se candidatar
Inscrições no link:
https://ewally.solides.jobs/vacancies/96640

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
