### ISSUE TITLE
[Remote] Mid-level Front-end Developer at Eduplaytion

### ISSUE THREAD

**Issue by analistacarlosh** [frontendbr/vagas#6020]
## Eduplaytion
Today, there is a rising demand for quality education with a modern and interactive approach. This gave birth to Eduplaytion – a Norwegian-based EdTech company made up of experienced teachers and skilled game developers on a mission to create high-end, game-based learning solutions for the international B2C and B2B market
You can know more about us: https://numetrygame.com/
https://www.linkedin.com/company/eduplaytion-as/about/

## Descrição da vaga
The ideal candidate will be responsible for designing, developing, testing, and debugging responsive web and mobile applications for the company. Using JavaScript, HTML, and CSS, this candidate will be able to translate user and business needs into functional frontend design.

## Responsibilities
Designing, developing, and testing UI for mobile and web applications
Build reusable code and libraries for future use
Accurately translate user and business needs into functional frontend code

## Local
Remote in any Brazilian location.

## Requisitos

2+ years' experience in frontend development
Experience building web applications in JavaScript ES6+, Typescript, HTML, and CSS with ReactJs or VueJs.
Distributed version control systems: Git and GitFlow.
Familiarity with internationalization, page load performance, and Mobile-first accessibility.
Familiarity with using Scrum/Agile development methodologies.
Good team player.
English: Intermediate level that is able to understand and communicate clearly.
Bachelor's degree or equivalent in Computer Science.

##Desejáveis:
* Ability to communicate technical concepts to non-technical audiences;
* Agile metodolgies experience (Scrum, Kambam);
* Evidence of working on cross-functionally;
* Experience of Startups environment;

## Benefícios
Competitive salary and annual paid vacation.

## Contratação
Long term contract - PJ

## Como se candidatar
Apply for this job by sending your Linkedin to: carlos@eduplaytion.no

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 3-5 dias após cada processo.
E-mail para contato em caso de não haver resposta: carlos@eduplaytion.no

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by analistacarlosh** [comment]
Olá, ainda estamos com 1 vaga em aberto pra inicio em Janeiro.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
