### ISSUE TITLE
[REMOTO] Desenvolvedor na Codex Agro

### ISSUE THREAD

**Issue by luanasantosog** [frontendbr/vagas#6022]
## Nossa empresa

A Codex Agro, é especialista em soluções de inteligência em diagnóstico, prognóstico, monitoramento e inteligência comercial, reunindo grande capacidade em geração e gestão de dados estratégicos para o Agronegócio no Brasil.

## Local

Remoto

## Requisitos

**Quais as habilidades e conhecimentos você precisa ter para fazer parte da nossa empresa?**
- Formação Superior na área de TI;
- Conhecimento GIS e conhecimento na plataforma ArcGIS.
- Conhecimento em Python, Model Builder e AppBuilder ArcGIS;
- Experiência em projetos de desenvolvimento com arquitetura corporativa;
- Experiência em desenvolvimento de projetos com banco de dados.

## Contratação

PJ a combinar

## Como se candidatar

Inscreva-se em: https://jobs.kenoby.com/codex-agro/job/analista-desenvolvedor-arcgis-codex-agro/617c38b4577300072782c66f?utm_source=website

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
