### ISSUE TITLE
[Remoto] Mobile Developer na Vetta

### ISSUE THREAD

**Issue by clarabsa** [frontendbr/vagas#6026]
## Nossa empresa

Somos um **centro de excelência em digitalização industrial** e nossa missão é transformar indústrias e empresas através da digitalização e da eficiência energética. 

Atuamos em conjunto com a SMS group, empresa líder mundial no segmento de metais. Utilizamos tecnologia de última geração para produzir soluções com agilidade, entregando projetos em mais de 14 países pelo mundo.   

 Queremos fazer a diferença e acreditamos com toda nossa fibra, que **através da tecnologia é possível deixar o mundo mais sustentável e inovador.**

 O que não falta aqui na Vetta, são oportunidades de crescimento em um ambiente acolhedor e colaborativo. Se você tem interesse em deixar uma contribuição positiva no mundo, aprender sobre as tecnologias mais avançadas no mercado e aplicá-las em seu dia a dia profissional, vem com a gente!

A Vetta promove a inclusão e valoriza a diversidade em toda a sua multiplicidade e, também, todas as nossas oportunidades estão abertas para pessoas com deficiência e beneficiários reabilitados da previdência social.

## Descrição da vaga

A missão da Vetta é ajudar a transformar o mundo em um lugar melhor através da tecnologia.  
Por isso nosso time é composto por pessoas engajadas que querem contribuir com a revolução digital! 
Convidamos você a se juntar à nossa equipe, com o objetivo de construirmos juntos um mundo mais sustentável e inovador. 
Vale a pena mencionar que todas as nossas vagas são inclusivas e abertas para pessoas com deficiência (PCD).

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Conhecimento em orientação à objetos
- Experiência em desenvolvimento mobile GIT
- Angular 6+
- Javascript
- Ionic 4+
- Inglês Avançado

**Desejáveis:**
- Cordova
- NGXS

## Benefícios

- Vale Alimentação/Refeição de R$22,70/dia
- Vale transporte conforme necessidade
- Plano de Saúde
- Plano Odontológico
- Seguro de Vida
- Auxílio Creche
- PLR
- Auxílio Home Office no valor de R$100,00
- Desconto em Academias – Total Pass
- Desconto em Terapias Online – ZenKlub
- Clube de Descontos Online – New Value

**Além de:**

- Day Off de Aniversário
- No Dress Code
- Programa de Incentivo a Formação Contínua
- Programa de Indicação de Talentos
- Jornada Híbrida de Trabalho

## Contratação

CLT

## Como se candidatar

Por favor envie um email para clarisse.azevedo@vetta.digital com Linkedin ou CV

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
