### ISSUE TITLE
[REMOTO] Developer na Imagem Geosistemas

### ISSUE THREAD

**Issue by luanasantosog** [frontendbr/vagas#6027]
## Nossa empresa

A Imagem Geosistemas faz parte do Grupo Imagem. Somos uma empresa brasileira de tecnologia líder em Sistemas de Informações Geográficas, distribuidora oficial no Brasil da plataforma ArcGIS, da norte-americana Esri.

## Local

Remoto

## Requisitos

**Quais serão as responsabilidades para o cargo?**
- Analisar, planejar e executar desenvolvimento e/ou manutenção de soluções de GIS/TI nas fases de Design, Construção, Tecnologia, Requisitos, Teste, Infraestrutura, Configuração e Qualidade.

**O que você precisará fazer durante sua jornada na Geosistemas?**
- Escrever códigos de desenvolvimento dos sistemas seguindo padrões de nomenclatura e práticas da empresa;
- Identificar, avaliar e definir frameworks, componentes e softwares para desenvolvimento, através da conceituação, documentação e experimentação, buscando aprimorar as soluções desenvolvidas;
- Realizar avaliações de segurança e performance de soluções.

**Quais as habilidades e conhecimentos você precisa ter para fazer parte da nossa empresa?**
- Graduação completa em Ciência ou Engenharia da Computação, ou área relacionada a TI;
- Experiência trabalhando com serviços restfull e microserviços;
- Html5, CSS3, node.js, angular, vue e react;
- Python e JavaScript;.
- SQL e Análise de Dados;
- Vivência em metodologias ágeis;
- Conhecimento na plataforma ArcGIS.

## Benefícios

- Plano de saúde
- Seguro de vida
- VR ou VA
- Assistência Odontológica
- Auxílio Home Office;
- Salário compatível com o mercado e vários benefícios.

## Contratação

A combinar

## Como se candidatar

https://jobs.kenoby.com/imagem-geosistemas/job/analista-desenvolvedor-pleno-geosistemas-solucoes/617c3e9b9aaf044090e12d4e?utm_source=website

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
