### ISSUE TITLE
[São Paulo] Senior Front-end Developer na Maplink

### ISSUE THREAD

**Issue by bchagas** [frontendbr/vagas#603]
## Descrição da vaga

A Maplink está a procura de um Senior Front-end Developer que será o responsável pelo desenvolvimento de interfaces e plataformas, além de dar continuidade no processo evolutivo de projetos digitais. 

## Local

Escritório da Maplink, São Paulo - Vila Olímpia

## Benefícios

- Assistência médica;
- Assistência odontológica;
- Seguro de Vida em Grupo;
- Vale refeição;
- Vale transporte;
- PLR, conforme política da empresa;
- Auxílio creche;

#### Diferenciais

- Café da manhã e massagem;
- Curso de inglês In Company ou reembolso no caso de curso em outra escola ou para outras línguas;
- Temos bicicletário e vestiário no prédio para quem vem de bicicleta.

## Requisitos
**Obrigatórios:**

- Conhecimentos avançados em Javascript, HTML e CSS;
- Experência em diferentes stacks e Frameworks e.x.:
- ReactJS, Angular.JS (1x e 2x), Node.JS, Backbone.JS
- Webpack, Grunt, Gulp, Jasmine, Mocha, Handlebars, SASS
- Experiência em times Agile / Scrum ou Kanban;
- Conhecimentos de Clean Code.
- Conhecimentos de sistemas de controle de versão Git;
- Experiência com APIs REST;
- Conhecimentos em Responsive Web Design;
- Vontade de sempre estar aprendendo;

**Desejáveis:**
- Experiência no desenvolviemtno de APIs Rest;
- Compreensão sólida de Back-end e sua interação com Front-end;
- Programação Funcional;

## Contratação

CLT

## Nossa empresa

Somos a maior revendedora da API do Google Maps na América Latina e está entre as maiores empresas do setor no mundo. Desde 2014, faz parte do Movile, um líder global em desenvolvimento de comércio e plataformas de conteúdo móvel, e em 2016 adquiriu uma empresa de tecnologia francesa chamada Optilogistic, referência mundial em logística.

Venha fazer parte do time do fornecedor global de tecnologia de logística em nuvem e produtos de geolocalização. Com clientes em mais de 18 países nas Américas, Europa e África, a empresa tem sede em São Paulo e tem escritórios na América Latina e na Europa. Há mais de 17 anos, a Maplink investiu em inovação e oferece soluções para mais de 3.200 empresas de diferentes portes e tamanhos.

## Como se candidatar

Por favor envie um email para marilia.kurdyk@lbslocal.com com seu CV em anexo com o assunto: Vaga Front-End Developer

**Comment by bchagas** [comment]
Vaga fechada já contratamos um candidato que **veio por este canal**, obrigado!

**Comment by LFeh** [comment]
Nois Brunão!

**Comment by bchagas** [comment]
@LFeh eu preciso abrir a vaga novamente, eu crio um novo tópico ou você reabre esse aqui? Valeu!
