### ISSUE TITLE
[Remoto] Front-end Developer (React Native) na Portolab

### ISSUE THREAD

**Issue by Mendrone** [frontendbr/vagas#6030]
## Nossa empresa

O Portolab é o laboratório de tecnologia e inovação da Portocred, uma financeira com mais de 25 anos de mercado. O time do lab, hoje dividido entre Brasil e Israel, é responsável pelo desenvolvimento de diversas aplicações multiplataforma e tem uma cultura baseada em liberdade e responsabilidade. Você será livre para testar e implementar novas soluções e tecnologias em um ambiente dinâmico de startup, com o suporte de uma empresa de grande porte e de um time formado por developers, designers e QAs com vasta experiência nacional e internacional.

## Descrição da vaga

Nesse papel você fará parte do time de desenvolvimento do nosso aplicativo mobile, o que inclui a implementação de novas features e manutenção em features já existentes. Você terá participação direta nas discussões e decisões envolvendo o aplicativo e demais assets de tecnologia da empresa. Esperamos que você tenha proficiência trabalhando com Javascript ou Typescript, assim como React ou React Native e seus respectivos ecossistemas. Também esperamos que você seja uma pessoa atenciosa a detalhes de UI como micro-interações, espaçamentos, etc.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência com Javascript e/ou Typescript
- Experiência com Git
- Experiência com React ou React Native
- Experiência com Tooling de Javascript 

**Desejáveis:**
- Conhecimento em APIs GraphQL (Apollo Client)
- Conhecimento em programação funcional 
- Experiência prévia implementando bibliotecas de UI / Design Systems

**Diferenciais:**
- Projetos open source
- Participação na comunidade
- Conhecimento em desenvolvimento mobile nativo (Android e/ou IOS)

## Benefícios

- Bônus Por Resultados

Além do básico/mínimo (mas nem sempre incluso) em vagas PJ que vemos por ai:

- Ferias Remuneradas
- 13º pagamento
- Plano de saúde (Incluindo dependentes, sem descontos)

## Contratação

PJ

## Como se candidatar

Por favor envie um email para mendrone@portolab.com.br com seu Linkedin ou CV - enviar no assunto: Vaga Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: tech@portolab.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
