### ISSUE TITLE
[REMOTO] Front-end Pleno e Sênior Developer na SEIDOR BRASIL

### ISSUE THREAD

**Issue by FF-FC-FS** [frontendbr/vagas#6033]
Front-End Developer"
"Desenvolvedor Front-End" \o/

> Vaga Remota

## Local
Remoto 

## Requisitos
**Obrigatórios:**
- 2 anos de experiência com React
- Experiência com : HTML, CSS, Javascript, jquery, TypeScript, Testes unitários e integração automatizados; Conhecimento de pacotes (npm, webpack, etc..); Web APIs; Git;
Experiência com bibliotecas Frontend de mercado: Ex: Angular, React e/ou Vue.js

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um e-mail para  rhbrasil@seidor.com.br com seu CV anexado - enviar no assunto: #Front-end Pleno e Sênior

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta:  rhbrasil@seidor.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by FF-FC-FS** [comment]
Olá, boa tarde!

Ainda está em aberto!!!!





Fernanda Cândida

***@***.***


Rua Grão Pará, 466 - Bairro Santa Efigênia
Belo Horizonte – MG - CEP 30150-341 - Brasil / +55 (31) 3273.0899



seidor.com<http://www.seidor.com>


***@***.***         Antes de imprimir este mensaje, asegúrese de que sea imprescindible. Proteger el medio ambiente está a nuestro alcance.


La información que contiene este correo electrónico es confidencial y compete exclusivamente al destinatario. Si Vd ha recibido esta comunicación por error, por favor, notifíquelo inmediatamente al remitente y borre el mensaje junto con sus ficheros anexos sin leerlo, copiarlo, grabarlo, distribuirlo o divulgarlo o hacer cualquier otro uso de la información sin el consentimiento de la empresa. El correo electrónico vía Internet no permite asegurar la confidencialidad o correcta recepción de los mensajes, por lo que la Empresa no asume responsabilidad alguna por los daños causados. Sus datos personales serán tratados por empresas del Grupo SEIDOR. para responder a sus consultas. De acuerdo con el artículo 6.1.f del RGPD, la base jurídica del tratamiento de datos personales es la operación y gestión de los servicios y actividades propias del negocio de las empresas del Grupo SEIDOR. Sus datos no se cederán a terceros, salvo obligación legal. Puede ejercer sus derechos en materia de protección de datos (acceder, rectificar y suprimir sus datos, entre otros) enviando un e-mail a ***@***.*** Para conocer nuestra política de privacidad en mayor detalle pinche aqui.<http://www.seidor.es/content/seidorweb/es/politica.html>.

The information contained in this communication is confidential, may be privileged and is intended for the exclusive use of the above named addressee. If you receive this communication in error, please notify the sender immediately and delete it, and all its attached documents. If you are not the intended recipient, you are expressly prohibited from reading, copying, distributing, disseminating or, in any other way, using any of the information without the company consent. Please note that Internet e-mail guarantees neither the confidentiality nor the proper receipt of the message sent, so that the Company shall not be liable for any damages caused. Your personal data will be processed by our Group Companies to answer your queries. According to article 6.1.f of the GDPR, the legal basis for the personal data processing is the operation and management of the services and activities inherent to the business of the SEIDOR Group´s companies. Your data will not be transferred to third parties, except legal obligation. You can exercise your rights in terms of data protection (access, rectification and cancellation of your data, among others) by sending an e-mail to the following address ***@***.*** To learn more about our privacy policy, click Here.<http://www.seidor.es/content/seidorweb/en/politica.html>
De: Felipe Fialho ***@***.***>
Enviada em: segunda-feira, 3 de janeiro de 2022 21:30
Para: frontendbr/vagas ***@***.***>
Cc: Fernanda Cândida ***@***.***>; Author ***@***.***>
Assunto: Re: [frontendbr/vagas] [REMOTO] Front-end Pleno e Sênior Developer na SEIDOR BRASIL (Issue #6033)


Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

—
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffrontendbr%2Fvagas%2Fissues%2F6033%23issuecomment-1004446416&data=04%7C01%7Cfernanda.candida%40seidor.com.br%7Ce3f523aa416144acd8d508d9cf195533%7C654623d615044f22a146b7c72637766a%7C0%7C0%7C637768529984022038%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QO7GZzCc9gfMDvqq%2BoOB5ZQMsoKJMpkYEQDx8Ueoeg4%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWLDUPXRV2S5LDIZQJ3KRKTUUI5QFANCNFSM5HMF3H3A&data=04%7C01%7Cfernanda.candida%40seidor.com.br%7Ce3f523aa416144acd8d508d9cf195533%7C654623d615044f22a146b7c72637766a%7C0%7C0%7C637768529984022038%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=m5ABX1jbIZ8a%2FKapmC6g7yde%2B1%2FgDQ9cboFyMfKdhh4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cfernanda.candida%40seidor.com.br%7Ce3f523aa416144acd8d508d9cf195533%7C654623d615044f22a146b7c72637766a%7C0%7C0%7C637768529984031988%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=N%2FAQ4qXcLjOAl%2F4oUXKfYZn%2FtEkPZnQmQU0Mw4EemSM%3D&reserved=0> or Android<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cfernanda.candida%40seidor.com.br%7Ce3f523aa416144acd8d508d9cf195533%7C654623d615044f22a146b7c72637766a%7C0%7C0%7C637768529984031988%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0RNco6KtuqAlu4%2FpZZjXp%2F3ljQD3QVQ0NGxSQ87kEvY%3D&reserved=0>.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
