### ISSUE TITLE
[Presencial/Remoto-Manaus] Front-end Developer na FPF Tech

### ISSUE THREAD

**Issue by ANACLAUDETE** [frontendbr/vagas#6034]
> Vaga Remota durante a pandemia

## A FPF Tech é um centro tecnológico com mais de 23 anos transformando conhecimento em inovação.

A FPF Tech conta com mais de 290 techers (nossos incríveis colaboradores) altamente qualificados e com uma infraestrutura adequada, visando sempre evoluir na qualidade de seus serviços.

Inovação, comprometimento, experimentação e atitude de vencedor são conceitos que fazem parte de todo o processo de criação, pesquisa e desenvolvimento da FPF.

## Descrição da vaga

Pessoas apaixonadas por tecnologia com os seguintes valores:

- Experimentação
- Atitude de vencedor
- Responsabilidade Social
- Multidisciplinaridade
- Colaboração

## Local

Exemplo: Híbrido mas com residência em Manaus. [Amazonas], [Manaus]

## Requisitos

**Obrigatórios:**
- Vivência na área

**Desejáveis:**
- Javascript
- Html

**Diferenciais:**
- Angular

## Benefícios

- Plano de saúde

**Diferenciais:**
- Programa de Idiomas
- Programa qualidade de vida
- Programa de qualificação profissional
- Benefícios flexíveis

## Contratação

CLT

## Como se candidatar

Por favor envie um email para pessoas@fpf.br com seu CV anexado - enviar no assunto: Vaga Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: ana.ferreira@fpf.br

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
