### ISSUE TITLE
[Remoto] Vue.js Developer @ TBDC

### ISSUE THREAD

**Issue by cesarzagonel** [frontendbr/vagas#6036]
## Descrição da vaga

Buscamos um desenvolvedor Vue.js sênior comunicativo que tenha facilidade em trabalhar em equipe.

## O que você irá fazer:
Como parte do nosso time de engenharia, você irá desenvolver soluções para problemas no agronegócio, projetando, desenvolvendo e mantendo aplicações móveis que serão utilizadas por nossos clientes. Irá liderar e ser uma referência técnica dentro da equipe, direcionando-a para a utilização de práticas modernas de desenvolvimento de software como a utilização de testes automatizados.

## Local
Remoto

## Responsabilidades
- Participar de reuniões de planejamento
- Entender o escopo do negócio e apontar soluções técnicas
- Direcionar o time observando parâmetros de qualidade
- Escrever código observando as boas práticas

## Requisitos

**Obrigatórios:**
- 4+ anos de experiência com Vue.js
- Experiência em projetar, desenvolver e manter aplicações web
- Experiência com testes (Unitários, integração e E2E)

**Desejáveis:**
- Experiência desenvolvendo aplicativos móveis
- Experiência com Ionic

## Benefícios

- Férias remuneradas
- Décimo terceiro salário

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para zagonelcesar@gmail.com com seu CV anexado - enviar no assunto: Vaga Vue.js

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
