### ISSUE TITLE
[Remoto] Front-end Developer na ASAP Log

### ISSUE THREAD

**Issue by ogermanoferreira** [frontendbr/vagas#6037]
## Nossa empresa

Somos uma logtech especializada em logística, tecnologia e varejo com a missão de revolucionar o delivery brasileiro!

A ASAP cresceu 36 vezes o seu tamanho após entrar para o Grupo Via. Com isso, já absorvemos mais de 60% das entregas de marcas como Casas Bahia, Ponto, Extra.com entre outras varejistas. 

Acolhemos também 300 mil entregadores por 18 estados do país, mais o Distrito Federal. Em breve, devemos abraçar todos os estados e atender qualquer empresa, das pequenas às grandes, que necessitam de um serviço rápido, eficiente e barato.

## Descrição da vaga

A ASAP Log assumiu o projeto de desenvolver o primeiro super app do Brasil. Por isso, vamos montar um dream team de tecnologia e queremos que você faça parte disso.

Hoje o nosso time está dividido em squads para tocar o desenvolvimento de várias frentes de logística do aplicativo. Delegamos a gestão de cada um desses squads para Product Owner, que são especialistas em Jira e metodologias ágeis.

A sua rotina será dividida em sprints semanais para agregar valor de forma ágil, reuniões diárias para controlar o andamento das tarefas e, obviamente, executá-las. Abaixo você encontrará as habilidades necessárias para a realização do job.

Além disso, é importante destacar que, à parte da cobrança, o nosso dia a dia se divide em momentos de descontração e eventos de capacitação do time. Afinal, somos uma startup!

Por fim, esses são alguns dos mantras que costumamos repetir nas reuniões e conversas de corredor:

-  O simples funciona;
-  Parceria;
-  Construímos juntos; e
-  Mão na massa.

## Local

Remoto ou Escritório, [PARANÁ], [CURITIBA], [ÁGUA VERDE]

## Requisitos

**Obrigatórios:**
 
- Experiência sólida em HTML / CSS / JavaScript;
-  Consumir APIs RESTful; e
-  Conhecimento em controle de versões (Git, Bitbucket, Travis ou Jenkins).

**Desejáveis:**
- Conhecimento técnico em plataformas em nuvem (AWS, DigitalOcean, Google Cloud Plataform, Azure, etc.);
- Experiência com a metodologia SCRUM/Agile;
- Conhecimento em Jira; e
- Experiência em startups ou negócios digitais.

**Diferenciais:**
 - Autossuficiência para identificar problemas e focar em soluções;
 - Senso de urgência e gerenciamento do tempo;
 - Comunicação pessoal para se fazer claro, interpretar as mensagens dos colegas de time e adaptar-se ao estilo de cada um;
 - Inteligência emocional para aceitar críticas e trabalhar bem em equipe;

## Benefícios
-Home office;
- Vale refeição;
- Vale transporte;
- Planos médico e odontológico;
- Participação nos lucros da Via;
- Gympass/Total Pass;
- Licença maternidade estendida;
- Enxoval do bebê;
- Previdência privada;
- Seguro de vida;
- Empréstimo consignado;
- SEST/SENAT; e
- Benefícios e descontos em e-commerces e lojas Via e parceiros.

**Diferenciais:**
- Ambiente descontraído: recarregue o seu nerf, smoka o CT e paga uma rodada aí pra nós!
- Suporte, estabilidade e oportunidades de uma gigante do varejo; e
- Agilidade, simplicidade e crescimento rápido de uma startup.

## Contratação

CLT a combinar

## Como se candidatar

Envie os seus dados em https://asaplog.com.br/trabalhe-conosco/

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@asaplog.com.br

#### Alocação
- Alocado em Curitiba
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
