### ISSUE TITLE
[Remoto - USA] Full-stack Engineer na WorkOS

### ISSUE THREAD

**Issue by vcapretz** [frontendbr/vagas#6039]
## Nossa empresa

WorkOS is growing rapidly and building out our core team of full-stack engineers!

We’re searching for passionate engineers who obsess over developer tools and documentation. We’re also looking for teammates who have profound empathy with other developers, and actively seek different perspectives and feedback to inform the products you’ll help build.

Successful candidates will love taking ideas from zero to one, creating beautiful software experiences with modern tools, and care deeply about creating the best possible products.

## Descrição da vaga

- Scope projects, document decisions, and flesh out epics and stories
- Build new SDKs and third-party integrations
- Spearhead development of tooling and instrumentation that improves our API reliability
- Debug user issues and adapt product to remove points of friction
- Write technical blog posts (e.g., “How to implement SSO with Node.js”)
- Speak with developers regularly to get feedback on new product development
- Help recruit and assess future engineering team members 

## Local

Full remote com fuso horário dos EUA.

## Requisitos

- 3+ years of industry software development experience
- Intellectually curious, independently driven, and passionate about great products
- Expert-level skill in at least one programming language and familiarity with others
- Experience working on small teams in fast-paced environments
- Excellent prioritization skills
- Experience building and shipping web applications and/or API services end-to-end
- Our stack is TypeScript, React, and Postgres (bonus points if you are familiar with these, but it's not required)
- A growth mindset, high emotional intelligence, and strong communication skills

## Benefícios

- Full-remote
- Health-care plan
- US holidays (you're able to change the dates in case you want to take one in Brazil instead)

## Contratação

PJ, recebido em USD 

## Como se candidatar

Envie um email para vitor@workos.com pra batermos um papo sobre a empresa 😄 

## Tempo médio de feedbacks

Respondemos em até 3 dias

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
