### ISSUE TITLE
[São Paulo] Front-End Developer na Lyra Network

### ISSUE THREAD

**Issue by henriqueleandro** [frontendbr/vagas#604]
## Descrição da vaga

Front-End Developer -  REACT

## Local

Escritório, São Paulo - Jaguaré

## Benefícios

A Combinar

#### Diferenciais

- Ambiente descontraído
- Flexibilidade de horário 

## Requisitos

**Obrigatórios:**
- Experiência com REACT
- Experiência com HMTL
- Experiência com CSS

**Diferenciais:**
- conhecimentos em C#
- conhecimentos Inglês e francês 

## Contratação

PJ/CLT a combinar

## Nossa empresa

Operadora internacional, Lyra Network oferece um portfólio completo de serviços especializados em pagamentos eletrônicos concebidos para otimizar as vendas de seus clientes, qualquer que seja o canal : Internet, terminais POS ou TEF, aplicativos mobile e cobrança de faturas.

## Como se candidatar

Por favor envie um email para leandro@cardtrue.com com seu CV anexado - enviar no assunto: Vaga Front-End

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
