### ISSUE TITLE
[REMOTO] Developer na Codex Utilities

### ISSUE THREAD

**Issue by luanasantosog** [frontendbr/vagas#6042]
## Nossa empresa

A Codex Utilities é especialista em sistemas de mobilidade corporativa, com foco nas demandas espaciais (Mobile GIS), a Codex busca solucionar as deficiências inerentes aos sistemas corporativos tradicionais.
Conheça mais sobre nossa empresa em: http://www.kaffa.com.br/

## Local

Home Office

## Requisitos

**Formação:**
- Formação Superior na área de Tecnologia da Informação;
- Inglês intermediário/avançado.

**Habilidades Necessárias::**
- Experiência com duas ou mais das seguintes tecnologias: Java, Kotlin, Android, Node.js, React, SQL;
- Análise crítica e capacidade em resolução de problemas.

**Habilidades Desejáveis:**
- Conhecimento em Node.Js, React e outros frameworks de mercado; Experiência com integração contínua e TDD; 
- Experiência com modelagem e consumo de APIs REST.

**Diferenciais:**
- Experiência com desenvolvimento de soluções GIS; 
- Micro serviços; 
- Bancos NoSQL.

## Contratação

A combinar

## Como se candidatar

Interessados e dentro do perfil, enviar currículo atualizado, e pretensão salarial para rh@kaffa.com.br
informando no assunto: Desenvolvedor - GitHub

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
