### ISSUE TITLE
[Remoto] Front-end React Sênior na Flexcode Software

### ISSUE THREAD

**Issue by mateu5-francisco** [frontendbr/vagas#6048]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-react-senior-143511760?utm_origin=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>Flexcode</strong> está buscando <strong>Front-end React Sênior</strong> nível sênior para compor sua equipe!</p>
<p>A nossa equipe é estrategicamente pequena, mas formada por profissionais dedicados à web que se reúnem para criar resultados poderosos. Resultados efetivos emergem do nosso foco e colaboração, à medida que nos dedicamos a um pequeno número de projetos de cada vez, gerando maior impacto. Com uma equipe inteiramente constituída por pessoas desenvolvedoras, web seniores, designers e criativo(a)s de todos os tipos, trabalhamos em conjunto para enfrentar um desafio de cada vez.</p>
<p><strong>Responsabilidades:</strong></p>
<ul>
<li>Desenvolvimento e manutenção de front-end de aplicações web;</li>
<li>Realizar a manutenção e criação de novas funcionalidades;</li>
<li>Aplicar melhores práticas de documentação de código desenvolvido;</li>
<li>Desenvolver e sustentar integrações;</li>
<li>Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas;</li>
</ul>

## Flexcode Software: 
 <p>A nossa equipe é estrategicamente pequena, mas formada por profissionais dedicados à web que se reúnem para criar resultados poderosos. Resultados efetivos emergem do nosso foco e colaboração, à medida que nos dedicamos a um pequeno número de projetos de cada vez, gerando maior impacto. Com uma equipe inteiramente constituída por programadores web seniores, designers e criativos de todos os tipos, trabalhamos em conjunto, para si, para enfrentar um desafio de cada vez.</p>
</p>

 ## Habilidades: 
 - Javascript 
- React.js 
- Sass/Less 
- Redux
## Local: 
 100% Remoto
## Requisitos: 
 - Inglês obrigatório. 
- Experiência com JavaScript moderno, CSS/SASS, React, Redux, MobX etc; 
- Conhecimento em metodologias ágeis (Scrum/Kanban); 
- Experiência com ferramentas de versionamento de código (GIT,...); 
- Experiência em PHP Desejável
## Diferenciais: 
 - Experiência com Javascript moderno, CSS/SASS, React, Redux, MobX etc;
## Benefícios: 
 - Day off no aniversário 
- Jornada flexível 
- Assinatura Mensal de Vinho 
- Assinatura Mensal de Café 
- Auxílio Financeiro para Home Office
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Front-end React Sênior na Flexcode Software](https://coodesh.com/vagas/frontend-react-senior-143511760?utm_origin=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
