### ISSUE TITLE
[São Paulo] Front-End Developer na Nexaas

### ISSUE THREAD

**Issue by talitapagani** [frontendbr/vagas#605]
## Descrição da vaga

A Nexaas (http://www.nexaas.com) procura pessoas capazes de criar excelentes interfaces para nossos produtos, na web e no celular. Temos projetos já iniciados e também outros ainda no forno que precisam de front-end developers para criar e implementar a experiência do usuário do início ao fim.

## Local

Escritório, São Paulo - Vila Olímpia, entre a estação da CPTM e o Shopping Vila Olímpia.

## Benefícios

- Plano de saúde
- VR de R$ 24,30/dia
- VT

#### Diferenciais

- Ambiente de trabalho descontraído
- Possibilidade de crescimento junto com a empresa
- Liberdade para trabalhar com as ferramentas (hardware e software) que lhe agradam
- Tempo para adequar-se ao nosso processo de desenvolvimento, com iterações semanais e acompanhamento direto de outros membros da equipe
- Possibilidade de home office

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento em HTML, CSS e Javascript;
- Experiência com a biblioteca jQuery e os frameworks Foundation e Bootstrap;
- Experiência com API's RESTFUL e termos relacionados (resources, AJAX, XML, JSON, HATEOAS);
- Conhecer o sistema de controle de versão GIT;
- Conhecer os pré-processadores SASS e LESS;
- Seguir à risca os padrões web, visando manter correta a semântica dos elementos e compatibilidade entre navegadores;
- Trabalhar bem em equipe, interagindo com developers e designers para transformar as visões de UX em realidade;
- Inglês - Intermediário.

**Diferenciais:**
- Conhecer os frameworks React e AngularJS;
- Experiência com design responsivo;
- Experiência com sistemas web desenvolvidos em Ruby.

## Contratação

CLT

## Nossa empresa

A Nexaas é uma empresa de desenvolvimento de softwares em nuvem para gestão empresarial. Esqueça as velhas tecnologias e formas de pensar, aqui nós ditamos tendências e desenvolvemos soluções disruptivas que oferecem a melhor experiência para nossos usuários. Para isso aliamos tecnologia de ponta a um time de pessoas que não se conformam com a zona de conforto. Somos apaixonados pelo que fazemos, viciados em resolver problemas reais e curiosos por conhecer pessoas que tenham essa mesma garra e determinação.

## Como se candidatar

https://jobs.kenoby.com/nexaas-trabalhe-conosco/job/desenvolvedor-web-front-end/59e4f17ce1933b0c2c105e55

**Comment by talitapagani** [comment]
Tags: Alocado, CLT, Pleno

**Comment by talitapagani** [comment]
Seguindo as regras do repositório, informo que as vagas continua aberta

**Comment by talitapagani** [comment]
Seguindo as regras do repositório, informo que as vagas continua aberta, já iniciamos as entrevistas do processo seletivo, mas ainda dá tempo de se inscrever. Ah, estamos com duas vagas abertas aqui em SP ;)

**Comment by LFeh** [comment]
Boa @talitapagani. Boa sorte!

**Comment by talitapagani** [comment]
Recebemos muito currículos legais e estamos agora avaliando os testes e fazendo as entrevistas para fechar a contratação. Obrigada a todas as pessoas que se candidataram!
