### ISSUE TITLE
[Home Office] Front-end Developer na @Contabilizei

### ISSUE THREAD

**Issue by M-Celina** [frontendbr/vagas#6050]
**Front-End Developer na Contabilizei**

> 

## 
Nossa empresa através da tecnologia, a Contabilizei está transformando a maneira como mais de 30 mil pessoas que empreendem gerenciam seu negócio no Brasil. Por aqui, continuamos a crescer rapidamente, criando novos produtos que proporcionam que nossos clientes sejam contadores de suas próprias histórias.

Ao integrar o Squad Aquisição como Desenvolvedor(a) Front-end, você terá como missão, apoiar a área de Growth na construção de novos canais de aquisição e identificando oportunidades que direcionam as decisões do dia a dia, garantindo principalmente que os clientes tenham uma experiência encantadora com a Contabilizei desde a primeira interação.

Aqui na Contabilizei, as oportunidades são para todos e todas! Queremos que você seja a melhor versão de si e se sinta bem onde estiver. Valorizamos as diferenças e temos um ambiente onde todos e todas são mais que bem-vindos, por isso buscamos diversidade em identidade de gênero, cor e etnia, orientação sexual, origem, pessoas com deficiência, entre outras diversidades, pois entendemos que JUNTOS construímos a Contabilizei do nosso jeito.

## Descrição da vaga

RESPONSABILIDADES E ATRIBUIÇÕES

Um dia típico inclui:
Analisar as exigências e especificações dos sistemas;
Entregar um código testável com qualidade;
Identificar problemas e aplicar melhorias na base de código existente;
Desenvolver e propor melhorias em sistemas e funcionalidades do lado do cliente (front-end);
Construir componentes de aplicativos front-end e incluir scripts a serem executados em navegadores web de diversos dispositivos do lado do cliente;
Poderá apoiar no desenvolvimento técnico do time.

REQUISITOS E QUALIFICAÇÕES

Você precisa de:
Experiência com Framework e bibliotecas (Vue.js e bibliotecas de gerenciamento de estado global);
Experiência com linguagens e melhores práticas (JavaScript, TypeScript, paradigmas funcional e orientação a objetos);
Experiência com DevOps (Bitbucket pipelines, Google Cloud Plataform, Firebase e Netlify);
Experiência com UX (tracking, acessibilidade e otimizações de desempenho);
Experiência com abordagens de qualidade (testes de unidade, integração, snapshot e E2E);
Experiência com arquitetura de software (Clean Architecture, MVC, Controller-Service-DAO, Flux);
Experiência com arquitetura web (modelo cliente-servidor, cache, DNS, hospedagem de estáticos, CDN, servidor de aplicação).

Pontos a mais se você possui:
Experiência com Nuxt.js;
Experiência com WordPress;
Experiência com PHP;
Experiência com SEO;
Experiência com Web Analytics.

## Local

Essa oportunidade permite trabalho totalmente remoto. :)

## Contratação

CLT. 

## Como se candidatar

Você pode se candidatar diretamente pelo linkedin em: https://www.linkedin.com/jobs/view/2784616304/ ou em nosso site https://contabilizei.gupy.io/jobs/1057031

#### Regime
- CLT.

#### Nível

- Pleno / Sênior.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
