### ISSUE TITLE
[Remoto] Senior Frontend Developer na Pipefy

### ISSUE THREAD

**Issue by laracmportugal** [frontendbr/vagas#6053]
## Nossa empresa

A Pipefy é uma das empresas de tecnologia do fundo de investimento da OpenView que mais cresceu recentemente, além de ter sido reconhecida pelo Gartner como “Intelligent Business Process Management” de 2020. Nosso software é uma plataforma “cloud-based/ no-code/low-codelow code” que empodera negócios e profissionais ao redor do mundo, possibilitando a automação de fluxos de trabalho de forma inteligente. Tudo isso acontece através de uma interface do tipo Kanban, onde empresas podem arquivar seus processos sem a necessidade de uma equipe de TI, habilidades técnicas, ou serviços profissionais.

Desde que foi fundada em 2015, a Pipefy já ajudou milhares de empresas a resolver problemas de negócio por conta própria, e seguimos com o nosso propósito de empoderar profissionais do mundo todo. Atualmente mais de 3000 empresas em mais de 150 países utilizam o Pipefy, de startups até líderes de mercado, como a Accenture, Visa, GE e Volvo.

## Descrição da vaga

Como uma pessoa para a vaga de Software Front-End Engineer, você será responsável por empoderar usuários para que realmente façam uma revolução de produtividade em suas empresas. Portanto, sua missão será resolver os problemas! Pode ser desenvolvendo novas features, aperfeiçoando features existentes, apoiando colegas de time, dando feedback ou ou corrigindo bugs.
Você terá a oportunidade de conduzir e participar de experimentos, fazer sugestões para melhorar a nossa arquitetura e o nosso produto, e usar muitos dados para tomar as melhores decisões.
Além disso, como nosso trabalho é totalmente remoto, você terá a oportunidade de trabalhar com pessoas do mundo todo.

->Principais Responsabilidades:

- Desenvolver novas features do início ao fim: desde a concepção do projeto, pesquisa, implementação até a manutenção, bem como aprimorar as já existentes;
- Ajudar a melhorar a performance, escalabilidade e confiabilidade dos nossos componentes;
- Trabalhar junto à equipe de Produto para descobrir melhores formas de resolver os problemas de nossos clientes;
- Compartilhar conhecimento com o time e aprender juntos.

## Local

Remoto

## Requisitos

**Obrigatórios:**

- Sempre colocar pessoas em primeiro lugar: nossa meta principal é ajudar usuários e garantir que a experiência com o Pipefy seja excepcional. Não nos contentamos com o bom, queremos ser extraordinários;
- Resolução de Problemas: Identificar o problema, analisar as causas, gerar uma gama de alternativas, avaliar as melhores soluções e a sua efetividade;
- Familiaridade com back-end;
- Habilidade e vontade de aprender: Você aprenderá por conta própria e também com seus e suas colegas todos os dias;
- Rapidez em priorizar e tomar decisões: As coisas mudam muito rápido em nosso ambiente, então precisamos que você pense rápido para identificar, priorizar e tomar decisões por conta própria;
- Orientação por dados: Na Pipefy, estamos sempre buscando maneiras de melhorar nosso trabalho, e fazemos isso analisando e interpretando dados. O que não é medido não pode ser melhorado, por isso precisamos que você tenha obsessão por dados;
- Keep it simple: Soluções simples e diretas mais do que over-engineering;
- Business-oriented: Suas decisões e o que você constrói têm impacto em nosso negócio. Você deve focar no que é necessário para alcançarmos nossas metas, ao invés de escolhas com base no que é cool ou hype em tecnologia;
- Experiência em entregar interfaces de qualidade para os clientes: Você irá criar e manter user interfaces de qualidade, usando tecnologias Web como HTML, CSS, JavaScript e React;

**Desejáveis:**

- Proficiência em JavaScript, incluindo manipulação de DOM e JavaScript object model;
- Pleno entendimento do estilo de programação de Component Model;
- Experiência com gerenciamento de estados em React;
- Familiaridade com APIs RESTful e GraphQL;
- Conhecimento em mecanismos de autorização modernos, como JSON Web Token;
- Familiaridade com build pipelines front-end e suas ferramentas;
- Experiência em ferramentas de desenvolvimento front-end como Babel, Yarn, NPM, etc.;
- Excelente comunicação verbal e escrita em inglês;
- Experiência com Scrum e Kanban.

## Benefícios

Plano Saúde
Seguro de Vida
Plano Odontológico
Vale Alimentação/Refeição Flexível
Auxílio Psicológico
Yoga & Meditação
Plano de Academia
Aulas Laborais
Auxílio Funeral Individual
Licença Maternidade e Paternidade
Auxílio Creche/Babá
Auxílio Veterinário
Folga de Aniversário
Auxílio Educacional
Espaço Coworking
Ajuda de Custo

## Contratação

CLT

## Como se candidatar

Por favor envie um email para lara.portugal@pipefy.com com seu LinkedIn ou CV anexado - enviar no assunto: Vaga Frontend na Pipefy ou [aqui](https://app.pipefy.com/public/form/WU-UKh3o)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: lara.portugal@pipefy.com

## Labels

- CLT
- Sênior
- Remoto

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
