### ISSUE TITLE
[REMOTO] Pessoa Analista de Sistemas Pleno @GrupoTiradentes

### ISSUE THREAD

**Issue by MundoJix** [frontendbr/vagas#6054]
Imaginou trabalhar na maior instituição de ensino superior de Sergipe?

O Grupo Tiradentes vem contribuindo para o desenvolvimento da população sergipana a mais de 50 anos, formando e educando pessoas através de sua metodologia de ensino. Ele, através do Mundo Jix, está abrindo uma vaga para Pessoa Analista de Sistemas Pleno na modalidade Home Office.

A pessoa contratada receberá o **salário de R $4.673,48 mais benefícios** como Assistência Odontológica, Convênio com Farmácia, parceria com a Alura para desenvolvimento técnico, equipamento para trabalho, ajuda de custo para trabalho remoto, entre outros.

**Para concorrer à vaga, a pessoa candidata deverá ter:**
- Graduação completa em cursos da área de Tecnologia da Informação;
- Conhecimento em metodologia de desenvolvimento ágil ou Lean 
- Participação em projetos de desenvolvimento de Software num período de, no mínimo, 2 anos. 

**Seria um diferencial:** 

- Ter nível de Inglês Intermediário; 
- Conhecer pelo menos 2 módulos do sistema Magister.

**A missão** do Analista de Sistemas Pleno será: 

- Realizar análise e desenvolvimento de sistemas, efetuar manutenção em softwares desenvolvidos internamente, utilizando os conceitos atuais da Engenharia de Software aplicando tecnologias e metodologias atuais, visando atender às necessidades da Instituição;

- Especificar e construir soluções de software de forma a atender aos processos organizacionais;

- Implementar e propor evoluções de infraestrutura tecnológicas e processuais, de forma a oferecer maior segurança, qualidade e eficiência aos processos acadêmicos e administrativos da instituição.

Inscreva-se através do link: https://forms.gle/rqtiq9wnq77twCLy8

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
