### ISSUE TITLE
[VAGA FECHADA] [REMOTE] Shopify Developer na BinaryFuture

### ISSUE THREAD

**Issue by Naralopes** [frontendbr/vagas#6055]
## Nossa empresa

BinaryFuture é uma empresa Ucraniana de TI que possui uma equipe de jovens profissionais que recentemente se ramificou de uma empresa maior e decidiu trilhar o seu próprio caminho em TI. São especializados em trabalhar com a plataforma Shopify e tudo relacionado a ela, especialmente apps. É uma empresa que buscam pessoas de mente aberta e que expandam os horizontes. 
## Descrição da vaga

Desenvolvimentos de projetos relacionados com a plataforma Shopify.

## Local

Full remote

## Requisitos

**Obrigatórios:**
- Shopify (Liquid),
- Shopify API,
- JavaScript - vanilla/jquery/basic React/Vue
- PHP - version 7 (preferable 8 )
- Database - any SQL database (MySql or MariaDB, Postgresql)
- HTML 5,
- CSS 3 (SASS, LESS good to have)
- Responsive design,
- GIT (at least basic commands)
- Good English
**Desejáveis:**
- Cache - Redis/Memcached (preferably but not mandatory)
- Worked with Figma before 

**Diferenciais:**

## Benefícios

**Diferenciais:**
- Horário flexível
## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para vagastech.lopes@gmail.com com seu CV anexado - enviar no assunto: Vaga Shopify Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias úteis após cada processo.
E-mail para contato em caso de não haver resposta: vagastech.lopes@gmail.com

#### Alocação

- Remoto

#### Regime

- PJ

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by Naralopes** [comment]
Olá, esta vaga está fechada. Pelo que tinha entendido, não era para deletar
e sim apenas editá-la colocando como vaga fechado
a. É isso mesmo?
Obrigada,

Nara

Em sáb., 19 de fev. de 2022 às 21:38, Felipe Fialho <
***@***.***> escreveu:
