### ISSUE TITLE
[Remoto] Front-end Developer na WA Project

### ISSUE THREAD

**Issue by KrevvyB** [frontendbr/vagas#6067]
## Nossa empresa
OLÁ! BEM-VINDO A WARRIORLAND!

Saiba mais sobre nós!

Somos uma software house que nasceu e atua 100% remota com todas as soluções que um projeto precisa para ser desenvolvido da melhor maneira possível.

Como uma empresa jovem que atua em um mercado aquecido com alta demanda por desenvolvimento de tecnologia, buscamos pessoas que acreditem que o comprometimento independente do espaço físico e que grandes especialistas conectados constroem projetos incríveis.

Nossa equipe é comunicativa, colaborativa e receptiva a pessoas, ideias e conceitos.

Trabalhamos de forma horizontal, com organização total, transparência e a liderança está sempre presente apoiando a equipe. Nosso foco é garantir a melhor experiência com um ambiente onde seja possível o requerimento obrigatório sempre de crescimento.

Ah! Somos apaixonados por tecnologia!

E então, você está pronto para ser um Guerreiro?

## Descrição da vaga
Os nossos Desenvolvedores atuam na criação de soluções para produtos que impactam inúmeros de usuários e para isso:
- Valorizamos a autonomia no processo de desenvolvimento;
- Trabalhamos num ambiente de cooperação, portanto buscamos sempre dar e receber feedback o tempo todo;
- Terá contato com o cliente para conseguir compreender o projeto;
- Irá atuar com desenvolvimento de sistemas, sites e apps;
- Atuará em equipe composta por Analista de sistemas e designer.

## Local
100% Remoto 

## Requisitos
- Linguagens: HTML; CSS; Javascript; Typescript;
- Frameworks: React (utilizando Hooks e ContextAPI); Nextjs;
- Bibliotecas essenciais: Material-ui; Rxjs; Formik;
- Skills: Conhecimento em padrão REST e GIT;
- Diferencial: Conhecimento de integração em Websocket; Experiência com React Native; SASS;
- Entrega ágil, usando Scrum e/ou Kanban;
- Ensino Superior Completo ou em andamento em Ciência da Computação ou afins (Desejável);

## Benefícios
- 100% Remoto;
- Contratação PJ;
- Férias (15 dias);
- Presentes em datas comemorativas;
- Licenças para o trabalho;
- Grupo no Discord para curtir e jogar fora do horário do trampo (interação é tudo);
- Bate-papo toda quarta-feira durante 30 minutos com a empresa toda para falar sobre TUDO menos trabalho!

## Contratação
PJ

## Como se candidatar

Candidate-se através do link https://www.linkedin.com/jobs/view/2789366508/ ou pode me chamar no WhatsApp: https://lnkd.in/d6cWg-w2

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
