### ISSUE TITLE
[Austria] Senior Front-end Developer na DeepOpinion

### ISSUE THREAD

**Issue by victorpantoja** [frontendbr/vagas#6068]
## Nossa empresa

A [DeepOpinion](https://deepopinion.ai/) é uma start-up com sede em Innsbruck, na Áustria e com escritório em Munique (Alemanha) e, em breve, Viena cujo main business é a automação de processos através do uso de AI (ML and NLP). Temos clientes na Europa, EUA e Dubai.

Nós estamos crescendo e contratando bastante gente! Acredito ser uma oportunidade muito boa de trabalhar em um time qualificado e com uma enorme possibilidade de desenvolvimento profissional.

## Descrição da vaga

Precisamos de uma pessoa para liderar nosso time de frontend e atuar junto ao time de backend e ML para propor e executar soluçoes criativas que melhorem o dia a dia de nossos clientes.

A vaga completa esta em [nosso site](https://deepopinion.ai/careers-frontend-developer).

## Local

Como temos pressa, a idéia é um contrato remoto de trabalho com a possibilidade de patrocionar o visto de trabalho.

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com React
- experiência com UI e UX
- nivel de ingles suficiente para trabalhar (alemao não é necessario)

## Benefícios

- salario inicial de 60.000 EUR por ano (12 meses + 13o e 14o) podendo ser maior dependendo da qualificacao

## Como se candidatar

Basta mandar um email para victor.pantoja@deepopinion.ai com perfil do linkedin, CV, github profile... o que mais voce achar que vale a pena :). Vale colocar no titulo algo como "Vaga Frontend".

## Tempo médio de feedbacks

Eu acho muito ruim quando o recruiter demora para responder então eu prometo uma resposta rapida!

#### Alocação
- Alocado
- Remoto

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by victorpantoja** [comment]
Ela ainda esta aberta.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
