### ISSUE TITLE
[Joinville - SC ou remoto] Frontend Developer na Coderockr

### ISSUE THREAD

**Issue by viniciusdacal** [frontendbr/vagas#607]
## Descrição da vaga

A Coderockr procura Frontend developer que seja sedento(a) por conhecimento. Alguém que traz críticas em relação as ferramentas utilizadas, com o objetivo de melhorar o processo de desenvolvimento. Pesquisador(a) nas horas vagas, trazendo novidades que podem ser realmente aplicadas nos projetos. Senso crítico, disciplina e organização são fundamentais.

## Local

Remoto ou Escritório, Joinville - Santa Catarina

## Benefícios

- Ambiente descontraído e inovador em Joinville/SC ou trabalho remoto
- [Cultura de inovação e crescimento](https://blog.coderockr.com/culture-code-da-coderockr-17f1789e7731#.n7eyj57j0)
- Budget anual para participação em eventos ou aquisição de livros/cursos
- [Plano de carreira](https://blog.coderockr.com/o-plano-de-carreiras-da-coderockr-aaf10de29c14)
- Plano de saúde
- Eventos internos

## Requisitos

**Obrigatórios:**
- Conhecimento prático em HTML e CSS;
- Conhecimento avançado de JavaScript;
- Desenvolvimento cross-plataforma e testes cross-browser;
- Confortável trabalhando com o controle de versão (Git);
- Capacidade de trabalhar de forma independente com uma supervisão mínima;
- Experiência de trabalho com APIs, ou integrar uma API de terceiros ou criar o seu próprio, quando necessário;
- Conhecer pré-processadores CSS como PostCSS, Sass e Stylus;
- Conhecer frameworks JS como React e React Native;
- Experiência com gerenciador de dependências como NPM e Yarn;
- Experiência com UI e UX.

**Desejáveis:**
- Experiência com sistemas de build (Bash, Grunt, Webpack, Make, Ant, etc);
- Conhecimento básico de pelo menos uma linguagem server side (Python, PHP, Node, Ruby, Go, etc).
- Noções de TDD e testes automatizados.

## Contratação

- Contrato CLT com salário compatível com a experiência
- Contratação Imediata

## Nossa empresa

A Coderockr, sediada em Joinville, Santa Catarina, está no mercado desde 2010 trabalhando com clientes de diversos portes como startups nacionais e internacionais, corporações, agências de publicidade e instituições de ensino. Nosso propósito é criar softwares incríveis e ajudar outras empresas e desenvolvedores a fazerem o mesmo. Fazemos isso porque acreditamos que o desenvolvimento de software é uma arte, que deve ser feita com paixão, dedicação, e organização.

## Como se candidatar

Se você atende os requisitos acima mande um e-mail com seu currículo/conta no Github para jobs@coderockr.com

Ps: Eu escrevi um post compartilhando a experiência de como foi trabalhar dois anos na code, a quem interessar: [Dois Anos de Coderockr](https://blog.coderockr.com/dois-anos-de-coderockr-f9ce3f4891a5)

**Comment by rodrigonehring** [comment]
Bela vaga, empresa parece ser muito boa!
Tem um typo ali em "ferramentas utilizandas"

**Comment by viniciusdacal** [comment]
Thanks @rodrigonehring, já atualizei :)
Eu trabalhei dois anos com eles! A empresa é muito boa mesmo. Eles trabalham com projetos bem bacanas e o Elton Minetto é um ótimo mentor.  

Aproveitei pra incluir um post falando sobre como foi trabalhar com eles.

**Comment by leonantvrs** [comment]
Email enviado...

Conta participação nos projetos open source frontendbr(acompanha) e trainig center(pupilo) ? :joy:

**Comment by juniorabranches** [comment]
show de vaga!

**Comment by viniciusdacal** [comment]
@leonantvrs tenho certeza que envolvimento com projetos open source contará pontos 😆

**Comment by ygorlazaro** [comment]
bom dia @viniciusdacal , vocês contratam PJ?

**Comment by raloliver** [comment]
Vou deixar essa vaga no meu radar... acabei de iniciar num novo projeto, mas vou ficar "stalkeando" essa aqui <3

**Comment by viniciusdacal** [comment]
@ygorlazaro CLT ou PJ

**Comment by jvgm** [comment]
Enviado :)

**Comment by netojose** [comment]
Vaga massa! Boa sorte aos que aplicarem!

**Comment by MacgyverMartins** [comment]
Ainda esta aberta a oportunidade @viniciusdacal ?

**Comment by viniciusdacal** [comment]
@eminetto ainda está recebendo currículos?

**Comment by eminetto** [comment]
Fechamos a fase de coleta de curriculos hoje :)
Estamos nas entrevistas e devemos finalizar a contratação na próxima semana.
Quero aproveitar e dar parabéns por esse espaço. Recebemos curriculos incríveis e está sendo bem difícil de escolher alguém :) É um problema bom
A comunidade é foda!!

**Comment by viniciusdacal** [comment]
Sendo assim, vou fechar a issue :)
