### ISSUE TITLE
[Remoto] Front-End Developer Angular na DQR TECH

### ISSUE THREAD

**Issue by DaianeMFirmiano** [frontendbr/vagas#6070]
> Vaga 100% Remota.

## Nossa empresa

SOBRE NÓS
Nascemos de uma parceria de mais de 10 anos entre seus sócios, somando a paixão por tecnologia à vontade de construir uma empresa diferente, investindo na proximidade com nossos parceiros e clientes. Somos uma consultoria especializada em Arquitetura de TI, Outsourcing de Profissionais e Hunting..

## Descrição da vaga

CONTRATAÇÃO:
Pessoa Jurídica - Relação por longo prazo por tempo indeterminado!  
Atuação 100% remota / 160h mês. 
Senioridade: Pleno até 15k

DESAFIO:  
Atuará junto a DQR Tech numa Squad nova, construída do zero, atendendo demandas do nosso cliente, sendo este uma instituição financeira, maior banco de investimentos da América Latina. 

## Local

Atuação 100% remota.

## Requisitos

Typescript  
Angular  
HTML  
CSS 

**Desejáveis:**
Ter atuado com produtos financeiros.

**Diferenciais:**

## Benefícios

Pessoa Jurídica - Relação por longo prazo por tempo indeterminado!  
Atuação 100% remota / 160h mês. 
Senioridade: Pleno até 15k

- ...

## Contratação

PJ a combinar

## Como se candidatar

Opção 01)  E-mail para daiane.firmiano@dqrtech.com.br
Opção 02) Chame no Whatsapp: (51) 989678273
Opção 03) Acesse o link: https://www.dqrtech.com.br/vagas/

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 01 dia após cada processo.

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
