### ISSUE TITLE
[Remoto] Frontend Developer  na Wetask

### ISSUE THREAD

**Issue by mateu5-francisco** [frontendbr/vagas#6071]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-developer-195609354?utm_origin=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>Wetask</strong> está buscando <strong>F</strong><strong><ins>rontend Developer </ins></strong>para compor seu time!</p>
<p>A Wetask é um marketplace de serviços para viabilizar a operação de grandes empresas, sejam eles de trade marketing ou vendas. A dinâmica é simples, basta a empresa indicar o que precisa ser feito que nós captamos e capacitamos pessoas que estejam dispostas a executar a tarefa por uma renda extra em todo território nacional. Com isso, para a empresa geramos um enorme ganho de capilaridade bem como uma redução global nos custos da operação. já para o Tasker democratizamos a distribuição de renda no país e oferecemos oportunidade de renda para uma população que hoje 51% vive com menos de 500 reais por mês.</p>

## Wetask: 
 <p>A Wetask é um marketplace de serviços para viabilizar a operação de grandes empresas, sejam eles de trade marketing ou vendas. A dinâmica é simples, basta a empresa indicar o que precisa ser feito que nós captamos e capacitamos pessoas que estejam dispostas a executar a tarefa por uma renda extra em todo território nacional. Com isso, para a empresa geramos um enorme ganho de capilaridade bem como uma redução global nos custos da operação. já para o Tasker democratizamos a distribuição de renda no país e oferecemos oportunidade de renda para uma população que hoje 51% vive com menos de 500 reais por mês.</p>
</p>

 ## Habilidades: 
 - Javascript 
- HTML 5 
- CSS 3 
- Vue.js
## Local: 
 100% Remoto
## Requisitos: 
 - Conhecimento em desenvolvimento Frontend, preferencialmente me Vue.js 
- Conhecimento de métodos ágeis / scrum 
- Conhecimentos ou experiência com MongoDB 
- Escreva código bem projetado, testável e eficiente 
- Habituado em trabalhar com programação orientada a objetos 
- Conhecimentos e boas práticas com HTML5 / CSS3
## Diferenciais: 
 - Conhecimento em desenvolvimento em Node.js, Typescript e Next.js
## Benefícios: 
 - 100% Remoto
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Developer  na Wetask](https://coodesh.com/vagas/frontend-developer-195609354?utm_origin=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
