### ISSUE TITLE
[Remoto] Front-end Developer na EQI Investimentos

### ISSUE THREAD

**Issue by jessizanelato** [frontendbr/vagas#6072]
## Nossa empresa

Somos uma holding de serviços financeiros em expansão, composta por escritório de assessoria e gestora de investimentos.
Atualmente contamos com mais de 45 mil clientes, R$11 bilhões em ativos sob custódia e mais de 710 pessoas no game!

Nosso propósito é dar autonomia para as pessoas investirem nas próprias escolhas. Acreditamos que isso só é possível com um time formado pelos melhores profissionais do mercado. 🧡

Desde a formação da EQI, a empresa dobra de tamanho a cada ano, com amplas oportunidades de crescimento a todos envolvidos. Em breve nos tornaremos uma das maiores Corretoras de Valores do Brasil e você pode ser parte desta construção. 

## Descrição da vaga

Buscamos profissional para atuar como Front-end Developer 👨‍💻👩‍💻com o objetivo de produzir soluções de software escaláveis.

Este profissional fará parte de uma equipe multidisciplinar responsável por todo o ciclo de vida de desenvolvimento de software, desde a concepção até a implantação. Atuamos em formato de Squad focados na implementação de soluções escaláveis que atendam as necessidades do nosso negócio.

Esta pessoa deve se sentir confortável com prototipação de telas, linguagens de codificação front-end, ferramentas de desenvolvimento e bibliotecas de terceiros.

## Local

Remoto ou Escritório em São Paulo, Florianópolis e Balneário Camboriú.

## Requisitos

**Obrigatórios:**
- Experiência comprovada como desenvolvedor frontend ou função similar;
- Experiência no desenvolvimento de aplicações para web e/ou aplicativos para dispositivos móveis;
- Experiência no uso de ferramentas de prototipação de telas como Figma;
- Familiaridade com os conjuntos de tecnologia mais comuns como Git, IDEs, etc;
- Experiência com HTML/CSS e JavaScript.

**Desejáveis:**
- Experiência com pelo menos um framework de frontend, tal como ReactJs, Angular e/ou Vue.js;
- Formação em Design, ADS, Publicidade, Ciência da Computação, Engenharia ou área relacionada.

## Benefícios

- Bônus variável mensal

## Contratação

PJ a combinar

## Como se candidatar

[Cadastro no Gupy](https://eqiinvestimentos.gupy.io/jobs/1315806)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: jessica.soares@euqueroinvestir.com

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
