### ISSUE TITLE
[Remoto] Fullstack Node.js Developer na Hubla

### ISSUE THREAD

**Issue by quetlinkober** [frontendbr/vagas#6073]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/fullstack-nodejs-developer-180248071?utm_origin=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>Hubla </strong>está buscando <strong><ins>Fullstack  Developer</ins></strong>!</p>
<p>A Hubla é uma empresa de tecnologia líder na Passion Economy / Creator Economy no Brasil. Lançada em 2020, permite aos criadores administrar sua própria comunidade paga usando uma plataforma de gerenciamento inteligente e rápida.</p>
<p>Estamos transformando talentos em comunidades ao possibilitar que qualquer pessoa crie um negócio online por meio de plataformas de chat em grupos como WhatsApp ou Telegram. Nossa missão é permitir que as pessoas tenham liberdade para trabalhar fazendo o que amam e ganhar a vida compartilhando seus talentos e experiências com o mundo.</p>
<p><em>Se você se identificou, vem para Hubla!</em></p>

## Hubla: 
 <p>A Hubla é uma empresa de tecnologia líder na Passion Economy / Creator Economy no Brasil. <br>Lançada em 2020, permite aos criadores administrar sua própria comunidade paga usando uma plataforma de gerenciamento inteligente e rápida.<br>Estamos transformando talentos em comunidades ao possibilitar que qualquer pessoa crie um negócio online por meio de plataformas de chat em grupos como WhatsApp ou Telegram. <br>Nossa missão é permitir que as pessoas tenham liberdade para trabalhar fazendo o que amam e ganhar a vida compartilhando seus talentos e experiências com o mundo.</p>
</p>

 ## Habilidades: 
 - Node.js 
- Javascript 
- Typescript 
- HTML 5 
- CSS 3 
- Firebase 
- Microsserviços
## Local: 
 100% Remoto
## Requisitos: 
 - Sólida Experiência em Node.js e Typescript 
- Experiência no frontend com javascript, preferencialmente react 
- Experiência com ferramentas de versão de código 
- Habilidades interpessoais de escrita e de comunicação verbal 
- Proatividade na busca de soluções e novas formas de desenvolvimento 
- Excelente raciocínio lógico 
- Ter trabalhado com metodologia ágil / scrum / kanban 
- Pessoa auto gerenciável, que busca conhecimento e seja resolutivo nos problemas
## Diferenciais: 
 - Conhecimento em Firebase e microsserviços
## Benefícios: 
 - R$ 700,00 de vale Alimentação/Refeição 
- R$ 150,00 de auxílio home office ou transporte 
- Plano de Saúde Nacional sem co-participação 
- Aula de inglês subsidiada 
- Gympass 
- Seguro de vida 
- Consultor executivo da empresa a disposição do colaborador 
- Auxílio Creche
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack Node.js Developer na Hubla](https://coodesh.com/vagas/fullstack-nodejs-developer-180248071?utm_origin=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
