### ISSUE TITLE
[REMOTO] Estagiário - Front-end Developer apaixonado/a por educação na TutorMundi

### ISSUE THREAD

**Issue by namenotrequired** [frontendbr/vagas#6074]
## Nossa empresa

Educação cria o futuro da sociedade. Tutoria é de longe o método mais efetivo de ensino. (Pesquise: "Bloom two sigma")

Somos uma pequena startup com grandes ambições. Todos na empresa trabalhamos com paixão pela missão de trazer um tutor excelente para cada um na América Latina.

O TutorMundi é um aplicativo [web](https://app.tutormundi.com/), [iOS](https://apps.apple.com/br/app/tutormundi/id1171236598#?platform=iphone) e [Android](https://play.google.com/store/apps/details?id=app.tutormundi.com&hl=pt_BR) de reforço escolar onde alunos de ensino fundamental e médio têm acesso a tutores das melhores universidades na hora, online e sem agendar. A plataforma funciona 24 horas por dia e 7 dias por semana. Em [2021](https://labsnews.com/pt-br/noticias/negocios/100-edtechs-mais-promissoras-da-holoniq-brasil/) e [2020](https://forbes.com.br/forbes-tech/2020/06/estudo-inedito-lista-as-100-edtechs-mais-inovadoras-da-america-latina) foi considerada pela HolonIQ uma das 100 edtechs mais inovadoras da América Latina.

Dê uma olhada: https://www.tutormundi.com/

Recebemos investimento no vale do silício e crescemos bastante durante a pandemia. Já foram dadas 2 milhões de minutos de aula na plataforma.

A empresa realmente investe nas pessoas. Por exemplo, eu sou holandês e a empresa arrumou um visto de trabalho para mim. Também apoiou nosso designer a passar 6 meses estudando em Stanford. Ano passado entrou um estagiário que cresceu tanto que hoje já tá liderando uma equipe de 10.

## Descrição da vaga

Você vai usar tecnologias web (HTML, CSS, JavaScript) para melhorar o nosso aplicativo em todas plataformas (web, Android, iOS).

Correções, melhorias, novas funcionalidades, se tiver interesse pode chegar a trabalhar com análise de dados, escalabilidade...

Você vai trabalhar remotamente com bastante apoio e tutoria do time. E ainda temos eventos informais para nos divertir.

## Local

Remoto

## Requisitos

Ser estudante (estar matriculado/a em uma faculdade)

Conhecimento de Git, HTML, CSS, JavaScript.

Paixão por educação.

Aprender rápido.

Atitude proativa.

## Benefícios

- Remoto, na pandemia e pós-pandemia
- Horário flexível
- Equipe pequena e empolgada
- Empresa que realmente investe nas pessoas
- Aula semanal de conversação em inglês

## Contratação

estágio (30h, 12 meses)

## Como se candidatar

Você pode se candidatar aqui: https://tutormundi.typeform.com/to/fM747DN4

Qualquer dúvida, escreva para bart@tutormundi.com.

#### Alocação
- Remoto

#### Regime
- Estágio

#### Nível
- Júnior

**Comment by matheusnogueiracamargo** [comment]
Feito! :grin:

**Comment by fcoiuri** [comment]
Enviado.

**Comment by Andre-Luis-Correa** [comment]
Enviado, obrigado😁

**Comment by mpfdev** [comment]
Enviado! 👍

**Comment by joaovitoroliv** [comment]
Enviado!!

**Comment by robinndev** [comment]
Enviando!

**Comment by Fabio-sudo-apt** [comment]
Enviado!!
