### ISSUE TITLE
[Remoto]Senior React Developer na CI&T

### ISSUE THREAD

**Issue by laichirolli** [frontendbr/vagas#6078]
## Nossa empresa

CI&T é uma digital specialist, parceira na transformação digital de ponta a ponta. Nativos digitais, temos um histórico de mais de 26 anos acelerando o impacto de negócios por meio de soluções digitais completas e escaláveis. Com a presença global de mais de 5.000 profissionais em estratégia, pesquisa, ciência de dados, design e engenharia, desbloqueamos o crescimento de receita, impulsionamos a experiência do cliente e aumentamos a eficiência operacional.

## Descrição da vaga

Temos oportunidade de atuação como Developer Frontend Senior para trabalhar em um dos nossos maiores clientes, numa plataforma empolgante e não-convencional utilizada ao redor do mundo por milhares de pessoas.

## Local

100% Remoto

## Requisitos

- Clean Code;
- Javascript, React, HTML e CSS;
- Conhecimento em conceitos de performance de aplicações front-end;
- Controle de código-fonte com GIT, usando Bitbucket ou Github;
- Acreditem em testes automatizados em todos os aspectos da codificação, como testes unitários, de segurança, estáticos, de performance e testes funcionais;
- Que não se importem de se aventurar numa base de código Java e fazer pequenas tarefas;
- Se sente confortável em colaborar com um time distribuído onde haverão pessoas trabalhando em partes diferentes do mundo e em fuso-horários diferentes.

**Obrigatórios:**
- 3 anos de experiência com React
- 5 anos de experiência com Front-End
- Inglês avançado

**Desejáveis:**
- conhecimentos em ruby on rails
- conhecimentos em C#

**Diferenciais:**
- Conhecimento em Jest ou Mocha, Chain, Sinon ou Jasmine;
- TypeScript e SASS;

## Benefícios

- Plano de saúde
- Seguro de vida
- VR/ VA
- Auxílio creche
- Gympass
- PLR

**Diferenciais:**

- Horário flexível

## Contratação

CLT

## Como se candidatar

Opção 01) Link https://jobs.lever.co/ciandt/48936b08-b456-4056-860d-3da1157f364a
Opção 02) E-mail lailachirolli@ciandt.com

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após aplicação

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
