### ISSUE TITLE
[Campinas - SP] Front-end Developer | Ingresso Rápido 

### ISSUE THREAD

**Issue by Giaoki** [frontendbr/vagas#608]
**Requisitos:**
·   Linguagens de programação de uso geral, incluindo, mas não limitado a, Java, C/C++, Python, C# ou Go;
·   jQuery e framework AngularJS 1.x;
·   Versionamento de código em plataformas GIT;
·   Ferramentas de gestão de dependências, como NPM, Bower ou Yarn.

**Diferencial:**
· Já ter trabalhado como Back-end Developer.
 
**Local:** 
· Campinas - SP, com flexibilidade de horário e home office.

**Benefícios:**
· Vale-refeição;
· Reembolso de 50% no valor do estacionamento;
· Convênio médico
· Convênio odontológico
· Gympass
· Seguro de vida
· Bônus (PLR)

**Diferenciais:**
· Sala de jogos;
· Frigobar;
· Flexibilidade de horário;
· Ambiente descontraído.

**Contratação:**
· CLT

**Sobre a Ingresso Rápido:**
·  A Ingresso Rápido é uma empresa do ramo de entretenimento especializada na divulgação, venda de ingressos, gerenciamento de bilheterias e controle de acesso para eventos culturais, esportivos e entretenimento em todo o Brasil. É a plataforma de entretenimento mais democrática do país, possuindo abrangência nacional e conteúdos diversificados para todas as faixas de renda e público!

**Como se candidatar:**
· Favor enviar o currículo atualizado no e-mail: giselle.aoki@ingressorapido.com.br

  

-

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
