### ISSUE TITLE
[London - UK] Front-end Developer @ Trainline

### ISSUE THREAD

**Issue by viniciusml** [frontendbr/vagas#6080]
## Nossa empresa
Trainline is the leading independent rail and coach travel platform selling rail and coach tickets to millions of travellers worldwide.  Via our highly rated website and mobile app, people can seamlessly search, book and manage their journeys all in one place. We bring together millions of routes, fares and journey times from 270+ rail and coach carriers across 45 countries.  We offer our customers the best price for their journey and smart, real time travel information on the go.  Our aim is to make rail and coach travel easier and more accessible, encouraging people to make more environmentally sustainable travel choices.
 
Technology @ Trainline 🚄
Over half of our staff are technologists who are making an impact on how people travel through the use of high-quality software.

At Trainline we have a modern and scalable tech platform that is built for volume and feature growth. Our mission is to find the perfect journey for our customer, and to do it in a fast, intuitive, reliable, and economic way. In a highly dynamic industry and with the ever-changing needs of our users, we must be ready to act, test, and measure quickly, in a way that only extensive and focused use of technology can enable us to. We have the power to revolutionise our customers’ travel experience through technology innovation.

## Descrição da vaga
Introducing the Channels team 👋
The Channels department are a collection of engineering clusters that own various applications that are central to the success of Trainline. These applications range from our highly rated web and mobile apps that are used by millions, contact centre and agent booking flow tooling to ensure customers receive the support and flexibility they need, B2B and B2C APIs to allow for seamless flows, and growth/acquisition to bring new customers into our product.

As a Mid Level Front-End Engineer at Trainline, here are some things you'll be working on... 

- Join a high performing, inclusive team - inspire people, own results
- Work on checkout and payment pages for one of the largest eCommerce sites in the UK
- Contribute to process improvements, iterating along the way
- Operate in a full-stack environment with a focus on clean, quality code
- Improve upon, and build solutions for web performance, accessibility, web analytics, localisation, multi-currency support, and browser compatibility.

## Local
Office - London, UK.

## Requisitos
We'd love to hear from you if you... 🔎
- Consider yourself reliable, transparent and considerate
- Thrive in a diverse, open and collaborative environment
- Have a strong understanding of functional programming and associated design patterns

And you've worked on...
- Highly scalable web applications, or high traffic websites
- Frontend and Backend systems
- React, or significant JavaScript experience with other libraries

## Benefícios
But why should you join?🤔
You will be working in a high performing and collaborative multi-cultural team. We have over 40 nationalities across our 3 offices in London, Paris and Edinburgh who work closely together.

We want our people to stretch their minds, abilities, and share their knowledge. Each year we hold The Trainline Tech Summit, which provides Trainliners with an opportunity to stand up and share their story, learnings, or new skills with their colleagues in a safe environment.

We've always paid special attention to flexible working as we value a strong work/life balance. The pandemic has taught us that a balance between remote working and being in a collaborative office environment leads to productive teams.

Our Culture 🤗
Everything begins with great people, as well as aptitude we put a heavy emphasis on attitude.
Coaches Over Heroes
·       We prioritise the focus on being one team over elevating the heroics of an individual, for us the true heroes are those who are excellent at nurturing, coaching and generous in sharing their knowledge with others.
Well-being
·       Everything that we do takes into account the morale of every member of our team, their opportunities for growth and for participation in exciting challenges.
Mentoring and Learning
·       We have a mentoring community that is constantly growing, we provide people with mentors or buddies from various teams.
Trust
·       We hire awesome people capable of making smart decisions - empowerment is a great enabler of agility. It is within a supportive team that you will feel the strength to thrive and try new things knowing that everyone will be there for you along the way. 

## Contratação
Full-time

## Como se candidatar
https://jobs.lever.co/thetrainline/41bc5007-7643-45b6-a023-92e8d3a98d76

#### Alocação
- Alocado

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
