### ISSUE TITLE
[Remoto]  Frontend React Developer (Sênior) na Mutual

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#6082]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-react-developer-senior-190222152?utm_origin=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A Mutual está buscando Frontend React Developer <strong><em><ins>nível sênior</ins></em></strong> para compor sua equipe!</p>
<p></p>
<p>Como desenvolvedor frontend (React) Sênior você terá a oportunidade de trabalhar com um frontend moderno usando tecnologias como React, React Native, Next.JS, Redux, Typescript. Inserido em uma equipe ágil, comprometida com qualidade nas entregas, e sempre buscando excelência técnica.</p>
<p></p>
<p>Para ser considerado para essa vaga você precisa ter pelo menos 5 anos de experiência profissional em React ou React Native&nbsp;</p>

## Mutual: 
 <p>Estamos entre as principais empresas de tecnologia do mercado financeiro nacional, desenvolvendo soluções que democratizam o acesso ao crédito e oferecem modelos de investimento nos setores mais promissores da economia brasileira.</p>
<p>Somos evolução do crédito digital no Brasil, permitindo que mais pessoas melhorem suas vidas financeiras de forma simples e justa. Aqui a gente entende e resolve o problema financeiro das pessoas de forma rápida e descomplicada. Ajudamos a tornar sonhos e objetivos financeiros em ações reais.</p><a href='https://coodesh.com/empresas/mutual'>Veja mais no site</a>

 ## Habilidades: 
 - React Native 
- Next.js 
- Redux 
- Typescript 
- CI/CD 
- SSR 
- Node.js
## Local: 
 100% Remoto
## Requisitos: 
 - Conhecimentos em Typescript 
- Conhecimentos em React.js 
- Conhecimentos em HTML 5 e CSS 3

## Benefícios: 
 - Horários Flexíveis  
- Trabalho 100% Remoto SEMPRE; 
- Contratação PJ; 
- Férias remuneradas; 
- Plano de saúde e odontológico (cobertura nacional); 
- Auxílio Home office; 
- Ambiente informal; 
- Evolução profissional acelerada.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [ Frontend React Developer (Sênior) na Mutual](https://coodesh.com/vagas/frontend-react-developer-senior-190222152?utm_origin=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
