### ISSUE TITLE
[Portugal] Front-end Developer React JS na Ambizzion IT 

### ISSUE THREAD

**Issue by NicolasDurazzo** [frontendbr/vagas#6083]
## Nossa empresa

É uma empresa provedora de serviços e soluções integradas de sistemas, alinhadas com as principais estratégias corporativas através de uma equipe altamente qualificada. Nossa experiência e comprometimento traduzem o alto nível de satisfação e reconhecimento dos nossos clientes.

## Local
 Remoto [Portugal]

## Requisitos

**Obrigatórios:**
- Superior completo/Técnico ou cidadania  
- 4 anos de experiência.
- Interesse e disponibilidade de mudança para Portugal.

## Benefícios

- Salário
- Plano de Saúde
- Plano Odontológico
- Seguro de Vida
- Todo equipamento para o trabalho
- Auxilio Internet
- Vale Alimentação
- 15 dias gratuitos em um Hotel para ambientação e adaptação
- Trabalhar em Lisboa ou Porto.

## Contratação

"CLT de Portugal"

## Como se candidatar

Por favor envie um email com a sua pretensão para nicolas.durazzo@ambizzion.com.br com seu CV anexado - enviar no assunto:
Vaga 42 Front-end Developer React JS - Github.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 48 após cada processo.

#### Alocação
- Remoto

#### Regime
- "CLT de Portugal"

#### Nível
- Pleno
- Sênior.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
