### ISSUE TITLE
[REMOTO] Front-end Developer Pleno na GOING 2 Mobile

### ISSUE THREAD

**Issue by brusecco** [frontendbr/vagas#6087]
> Vaga Remota durante a pandemia

## Nossa empresa
A Going2 Mobile - uma empresa de tecnologia da informação, focada em criar produtos que buscam facilitar a vida das pessoas e empresas, está com VAGAS ABERTAS PARA TRABALHO REMOTO 💻 

## Descrição da vaga
Estamos com vagas abertas para Front-End Developer Pleno. O Dev atuará em projetos de Software House para clientes e produtos internos.

## Local

100% remoto em horário comercial

## Requisitos
Conhecimento em HTML, CSS, JS, ReactJS e Axios

**Desejáveis:**
- conhecimentos em ruby on rails
- conhecimentos em C#

**Diferenciais:**
Será um diferencial se possuir conhecimento em NextJS

## Contratação

PJ a combinar

## Como se candidatar
Se você se encaixa no perfil desejado, acesse o link e cadastre seu currículo:
https://app.pipefy.com/public/form/iohJOGAI

## Labels
🏢 Remoto
👨 Pleno
⚖️ A-Combinar
⚖️ PJ

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
