### ISSUE TITLE
[Portugal] Lead Angular Developer

### ISSUE THREAD

**Issue by bernardoafonso** [frontendbr/vagas#6088]
Lead Angular Developer

4/5 anos de experiência com angular
Inglês Fluente

## Como se candidatar

Por favor envie um email para bafonso@primeit.pt com seu CV anexado - enviar no assunto: Vaga Lead Angular.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível

- Especialista

**Comment by VictorAndrade11** [comment]
teria outras oportunidades na parte de front? ou ciências de dados (AWS por exemplo)...

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
