### ISSUE TITLE
[Remoto] Front-end Developer na NTConsult

### ISSUE THREAD

**Issue by BruDalmolin** [frontendbr/vagas#6089]
## Nossa empresa

Somos uma empresa global de tecnologia comprometida em fazer a diferença nas organizações e na vida das pessoas. Em nossa trajetória de quase duas décadas, desenvolvemos soluções digitais de ponta que agregam valor aos nossos clientes e resolvem seus desafios de negócios, trabalhando com uma ampla gama de linguagens de programação.

## Descrição da vaga

- Desenvolvimento de funcionalidades no Front-End;
- Migração do sistema que está em angular para React;
- Transformação digital.

## Local

100% Remoto 

## Requisitos

**Obrigatórios:**
HTML5/CSS;
Javascript;
Angular;
React;
conhecimento em NodeJS;
SASS;
Frameworks responsivos (ex: Bootstrap);
Programação reativa;
Experiência com Task Runners (GULP, Grunt, WebPack)

## Benefícios

- Plano de saúde
- Plano Odontológico
- Benefícios Flexíveis

## Contratação

CLT

## Como se candidatar

Por favor envie um email para bruna.berbosa@ntconsult.com.br com seu CV anexado - enviar no assunto: Vaga Frontend

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
