### ISSUE TITLE
[São Paulo/SP] Desenvolvedor (a) PHP Backend - Grupo Padrão

### ISSUE THREAD

**Issue by GrupoPadrao** [frontendbr/vagas#609]
**# Descrição da vaga**
•	DESENVOLVER SISTEMAS WEB.
•	DESENVOLVER PORTAIS.
•	ESTRUTURAÇÃO DE BANCO DE DADOS.
•	INTEGRAÇÃO COM API’S.
•	TESTAR PROJETOS CRIADOS.
•	DAR SUPORTE PARA TODAS AS ÁREAS DA EMPRESA NO QUE DIZ RESPEITO A DESENVOLVIMENTO DE FERRAMENTAS.
•	REALIZAR CODIFICAÇÃO DE INTERFACES PARA SITES RESPONSIVOS.

**EXPERIÊNCIAS E CONHECIMENTOS (OBRIGATÓRIO)**
CONHECIMENTO EM:
- JSON
- HTML / CSS BOOTSTRAP
- BANCO DE DADOS MYSQL
- PHP 
- JAVASCRIPT JQUERY
- NODEJS
- GULP
- SEO E OTIMIZAÇÃO DE SITES.
- SABER TRABALHAR COM LAYOUT RESPONSIVO
- NOÇÕES DE API’S: GOOGLE, FOURSQUARE, INSTAGRAM, ETC.

**EXPERIÊNCIAS DESEJADAS (DIFERENCIAL)**
•	DESENVOLVIMENTO DE APP NATIVO.
•	CONHECIMENTO EM PLATAFORMA DE E-COMMERCE.
•	 JAVASCRIPT: ANGULAR, EMBER.JS, ETC).
•	NOÇÕES DE UX 

**HABILIDADES:** 
•	HABILIDADES PARA CRIAR UM CÓDIGO LEGÍVEL E DE FÁCIL MANUNTENÇÃO.
•	HABILIDADE PARA TRABALHAR EM EQUIPE.

 Local: SP/SP - Bairro Pacaembu

## Benefícios

- Plano de saúde e odontológico - opcional
- VT
- Forma de contração CTL ou PJ

#### Diferenciais

- Horário flexivel 
- Jornada de 40 horas semanais
- Banco de Horas 
- Possibilidade de Home Office
- Café, chá, frutas, bolachas a vontade 
- sala de jogos e descanso
- Happy Hour na empresa
- A empresa possui parceria com diversas instituições de ensino/cursos/lazer, desconto de 10% a 50%.

Por favor envie um e-mail para currículos@gpadrao.com.br com seu CV anexado e pretensão salarial - enviar no assunto: Vaga Programador

**Comment by LFeh** [comment]
Só Front-End

**Comment by Pedro-Souza** [comment]
@GrupoPadrao poste aqui: https://github.com/backend-br/

**Comment by GrupoPadrao** [comment]
Que pena!! Mas vi uma vaga com a mesma descrição que a minha....

SAMARA SANT’ANA
Gerente de Recursos Humanos
(+55) 11 3125.2212
[http://gpadrao.com.br/assinatura/gpadrao-assinatura.png]<http://www.gpadrao.com.br/>
IDEIAS QUE TRANSFORMAM NEGÓCIOS
www.gpadrao.com.br<http://www.gpadrao.com.br/>
Avenida Pacaembu, 1.613 – Pacaembu
Brasil – São Paulo – SP – 01234-001 <https://www.google.com.br/maps/place/Av.+Pacaembu,+1613+-+Pacaembu,+S%C3%A3o+Paulo+-+SP,+01234-001/@-23.5405435,-46.6661096,17z/data=!3m1!4b1!4m5!3m4!1s0x94ce5822682bc7f9:0x371ba64ac1d9ee10!8m2!3d-23.5405435!4d-46.6639209>
Telefone.: (+55) 11 3125.2244


De: Felipe Fialho [mailto:notifications@github.com]
Enviada em: quarta-feira, 18 de outubro de 2017 10:29
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: Samara Sant'ana - Grupo Padrão <samara@gpadrao.com.br>; Author <author@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [São Paulo/SP] Desenvolvedor (a) PHP Backend - Grupo Padrão (#609)


Só Front-End

**Comment by LFeh** [comment]
Qual?
