### ISSUE TITLE
[Remoto/Belo Horizonte] Front-end Developer (React) @ RockContent

### ISSUE THREAD

**Issue by henriqueweiand** [frontendbr/vagas#6090]
[Remoto/Belo Horizonte] Front-end Developer (React) @ RockContent

## RockContent

A Rock Content é líder global em marketing de conteúdo e existimos para possibilitar oportunidades de crescimento para nossos clientes, funcionários e parceiros. Oferecemos uma solução de marketing de conteúdo ponta a ponta, combinando SaaS, serviços e nosso mercado de talentos.

Somos 500 Rockers remotos e diversos distribuídos ao redor do mundo, cada um único e agregando à nossa cultura dinâmica, bem como promovendo crescimento, apoio e contribuição por meio de grupos de diversidade e inclusão. Triplicamos nosso crescimento nos últimos 2 anos e, conforme crescemos na América do Norte, as oportunidades de aprender e causar um grande impacto são infinitas. Junte-se à nossa jornada para o IPO! Confira estas notícias recentes sobre nosso financiamento da Série B: https://rockcontent.com/blog/series-b-funding/

Um pouco mais sobre nossos valores & culture code voce pode ver no site de carreiras: https://rockcontent.com/careers/

## Descrição da vaga

Estamos procurando um Desenvolvedor Front-End Sênior para nos ajudar a construir e desenvolver um de nossos produtos globais, criando a melhor experiência do usuário. É importante unir as discussões técnicas para solucionar os desafios do dia a dia, além de auxiliar nossa equipe por meio do compartilhamento constante de conhecimento.

## Local

Esta é uma posição remota, se você não mora no local definido, isso não é um problema.

## Requisitos

**Obrigatórios:**
- Experience with React.js Frameworks;
- REST APIs
- Git (via Github)
- Javascript and Jquery
- HTML/CSS
- Rest APIs
- Git
- Intermediate or Advanced English skills;

**Desejáveis:**
- conhecimento TypeScript

**Diferenciais:**
- projetos opensource
- NextJS

## Contratação

PJ ou CLT conforme preferir

## Como se candidatar

Acessar o link desta vaga no site de carreiras da Rock https://jobs.lever.co/rockcontent/cc998805-7b3f-4d9e-8e31-b7017b5417b6

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até uma semana dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Senior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
