### ISSUE TITLE
[Remoto ou POrto Alegre] Front-end Developer Pleno na Aegro

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#6091]
## Nossa empresa

E a Aegro **recebeu mais uma rodada de investimentos**, novos desafios e frentes de negócio estão sendo construídos. Para fazer parte disso, estamos procurando novos aegers para integrar o time que vai formar o primeiro unicórnio Agtech do Brasil. E ainda fazer tudo isso na melhor empresa para se trabalhar no Rio Grande do Sul e a 3ª a nível Brasil (reconhecida em 2020 pelo GPTW).

## Descrição da vaga

A área de Engenharia de Software tem várias missões para encarar esse desafio da construção do primeiro unicórnio, e para isso, estamos buscando uma pessoa Front-End Engineer apaixonada por tecnologia e movida a desafios.

Nossa stack é baseada principalmente em Java/Kotlin e Spring no backend, Angular no frontend, bancos de dados MongoDB, stack ELK para logs, Kubernetes e cloud AWS.

**Serão as suas responsabilidades...**
- Trabalhar junto com o time de produto e design para construir novas soluções e melhorar a experiência de usuário;
- Transformar protótipos criados no Figma em aplicações de alta fidelidade;
- Desenvolver aplicações web com uso intensivo de dados via APIs REST
- Participar das cerimônias de engenharia onde debatemos boas; práticas, arquiteturas, novas tecnologias e muito mais.

## Local

100% Remoto ou Escritório em Perto Alegre

## Requisitos

**Obrigatórios:**
- Tiver mínimo de 3 anos de experiência no desenvolvimento de aplicações web;
- Sólida experiência em JavaScript, HTML, CSS, Angular 2+ e AngularJS;
- Conhecimento em versionamento de código (Git);
- Familiaridade com linux.

**Diferenciais:**

- Experiência em Metodologias Ágeis (Scrum);
- Conhecimento em ferramentas de desenvolvimento: Webpack, Lint, Angular CLI, Npm;
- Conhecimento em princípios de design de interação, UX/UI e Design System;
- Padrões de projeto e arquitetura - Design Patterns, Clean Architecture, SOLID;

## Benefícios

- Plano de Saúde Unimed Seguros
- Plano Odontológico Unimed Seguros
- VR ou VA
- Auxílio Home-Office
- Flexibilidade de horário
- Acesso a plataforma da Alura para cursos de atualização
- Oportunidade de realizar 8 horas de treinamento/cursos/capacitações no horário de trabalho por mês

## Contratação

CLT

## Como se candidatar
Você pode se candidatar através [deste link](https://bit.ly/3np8SRS). Mas se preferir, poderá também enviar seu CV para o email tatiana@remotar.com.br que o mesmo será enviado diretamente para a Aegro. A [Remotar](https://remotar.com.br/?utm_source=github) é parceira da Aegro e contribui apenas para a divulgação da vaga, no entanto, todo o processo seletivo será feito diretamente com a Aegro :)

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
