### ISSUE TITLE
[REMOTO] Front-end Developer na Nibo

### ISSUE THREAD

**Issue by robertaebani** [frontendbr/vagas#6092]
> Vaga Remota durante a pandemia

## Nossa empresa

O NIBO é uma empresa de tecnologia de ponta focada em desenvolver ferramentas que visam revolucionar a rotina de milhares de empresários contábeis pelo Brasil. Cerca de 2 mil empresas vão à falência por dia no Brasil. A solução? Bons contadores. Por isso, abraçamos a missão de resgatar o valor do profissional contábil no país e não vamos descansar até alcançarmos nosso objetivo.

## Descrição da vaga

Desafios e responsabilidades

Será parte integrante da nossa Squad Donos da Grana, uma squad focada na reconstrução de um dos nossos produtos mais importantes.
Desenvolvendo ao lado de outros desenvolvedores as soluções necessárias para atingir os objetivos, incluindo a manutenção do código e correção de bugs.

Sua atuação é abrangente e inclui projetos em .NET MVC e novas SPAs.

Ajudar o time a tomar decisões, demonstrando técnicas e ferramentas.

Junto com a guilda de Front-end, definir os padrões a serem utilizados.

Junto com o time, arquitetar soluções robustas, escaláveis e performáticas.

## Local

Remoto

## Requisitos

**Obrigatórios:**
Experiência com Angular 2+
Sólida experiência com aplicações ricas em HTML5
Desenvolvimento com pré-processadores CSS como SASS
Fundamental conhecimento sobre Gulp, Grunt, NPM, Bower (urgh!), Yarn…
Noções básicas de design, coerência e coesão visual
Familiaridade com metodologias ágeis e GIT
Ser viciado em tecnologia, querendo aprender todos os dias
Ser proativo, possuir um ótimo raciocínio lógico, possuir alto nível de comprometimento e atencioso com os detalhes

**Desejáveis:**
Aplicações com Angular.js, React ou Vue.js
Conhecimentos aprofundados de jQuery
Desenvolvimento em C# .NET
ES6+ com Typescript 
Conhecimento em Bootstrap

## Benefícios

-Plano de Saúde: Bradesco Saúde
-Plano Odontológico: Bradesco Dental –Cobertura para todos os membros da família
-Seguro de Vida - SulAmérica Seguros
-Assistência Funeral - Cobertura para Cônjuge, Filhos, Pais e Sogros
-Auxílio Creche - Para as mães e pais
-Vale Refeição ou Alimentação
-Indica Aí! - Programa de Indicação
-Bônus por performance
-Consignado com desconto em folha

**Diferenciais:**
-Ajuda de custo mensal para capacitação
-Licença Paternidade de 30 (trinta) dias remunerados
-Ajuda de Custo - Mensal, pago em conta corrente para você investir numa boa internet e ajudar na conta de luz!

## Contratação

CLT - Nosso range é de 4.6-10.8k, mas o que define seu salário é o seu conhecimento e suas competências. Nos conte a sua pretensão!

## Como se candidatar

Por favor envie um e-mail para roberta.manhaes@nibo.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: roberta.manhaes@nibo.com.br

#### Alocação
- Remoto

#### Regime
- CLT

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
