### ISSUE TITLE
[Remoto] Front-end Developer Pleno Angular na Nibo

### ISSUE THREAD

**Issue by nicholasess** [frontendbr/vagas#6095]
## Nossa empresa

O NIBO é uma empresa de tecnologia de ponta focada em desenvolver ferramentas que visam revolucionar a rotina de milhares de empresários contábeis pelo Brasil. Cerca de 2 mil empresas vão à falência por dia no Brasil. A solução? Bons contadores. Por isso, abraçamos a missão de resgatar o valor do profissional contábil no país e não vamos descansar até alcançarmos nosso objetivo.

## Local

Remoto

### Requisitos

Experiência com Angular 2+
Sólida experiência com aplicações ricas em HTML5
Desenvolvimento com pré-processadores CSS como SASS
Fundamental conhecimento sobre Gulp, Grunt, NPM, Bower (urgh!), Yarn…
Noções básicas de design, coerência e coesão visual
Familiaridade com metodologias ágeis e GIT
Ser viciado em tecnologia, querendo aprender todos os dias
Ser proativo, possuir um ótimo raciocínio lógico, possuir alto nível de comprometimento e atencioso com os detalhes

### Desejaveis

Aplicações com Angular.js, React ou Vue.js
Conhecimentos aprofundados de jQuery
Desenvolvimento em C# .NET
ES6+ com Typescript 
Conhecimento em Bootstrap

### Beneficios

Aqui no Nibo, buscamos o que há de melhor para os nossos colaboradores. Seus pedidos e indicações são ouvidos e analisados pelo nosso Time de Pessoas! Vocês fazem parte desta construção!

Plano de Saúde : Bradesco Saúde 
Plano Odontológico: Bradesco Dental –Cobertura para todos os membros da família
Seguro de Vida – SulAmérica Seguros
Assistência Funeral – Cobertura para Cônjuge, Filhos, Pais e Sogros
Auxílio Creche – Para as mães e pais
Vale Refeição ou Alimentação 
Ajuda de Custo – Mensal, pago em conta corrente para você investir numa boa internet e ajudar na conta de luz!
Indica Aí! – Programa de Indicação 
Bônus por performance 
Consignado com desconto em folha 
Licença Paternidade de 30 (trinta) dias remunerados
Ajuda de custo mensal para capacitação

## Contratação

CLT

## Como se candidatar

Acesse o link e se inscreva na devsAcreditar para se candidatar a vaga: https://devsacreditar.com.br/o/front-end-angular-vYKs4

## Tempo médio de feedbacks

Avaliação do Curriculo
O recrutador terá 3 dias para responder

Teste Técnico
O recrutador terá 3 dias para responder

Entrevista Técnica
O recrutador terá 5 dias para responder

Entrevista com RH
O recrutador terá 5 dias para responder

## Labels
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
