### ISSUE TITLE
[Goiânia/GO ou Remoto] Pessoa Desenvolvedora Flutter Pleno | Biscoint

### ISSUE THREAD

**Issue by AugustoResende** [frontendbr/vagas#6097]
## Nossa empresa

Biscoint é uma fintech startup brasileira que está num estágio de plena tração e com grande potencial de crescimento!

Com o Bitcoin e as criptomoedas chegando a novas altas históricas nos últimos meses, milhões de pessoas ao redor do mundo passaram a se interessar pelo mundo cripto.

Por isso, após receber uma nova rodada de investimento recentemente, estamos expandindo nosso time em várias áreas.

O Biscoint tem a missão de permitir que qualquer pessoa consiga entender e comprar Bitcoin de forma simples.

## Descrição da vaga

_O time de Dev's do Biscoint está crescendo! Recebemos um aporte e agora estamos buscando novos reforços para apoiar nos desafios que estão por vir!_
Atualmente somos um time enxuto com sete full-stacks, atuando em modalidade remota. Prezamos por um ambiente leve e colaborativo, e cultivamos uma comunicação aberta. Stack moderno: Blockchain, Lightning Network.

Te convidamos a fazer parte de uma equipe inovadora, transparente e apaixonada por desafios. Como nosso (a) colega, você participará do desenvolvimento da plataforma mais completa e eficiente para negociar bitcoins no Brasil, crescendo e partilhando muitas experiências!

## Local

Remoto ou Escritório Goiânia, Goiás

## Requisitos

Obrigatórios
- Mais de 1 ano trabalhando com Flutter
- Arquitetura modular
- Experiência com sockets e real-time
- Desenvolvimento nativo em Kotlin (Android) ou Swift (iOS)
- Desenvolvimento de interfaces
- Testes, (automatizados, guiados ou não, com robos, suites, etc)
- Firebase
- Saber trabalhar APIs de camera (pra selfies, QrCodes, etc)
- Noções de Design e UI/UX

Diferenciais
- Conhecimentos em blockchain e BTC
- Conhecimentos em mobx ou qualquer pacote de gerenciamento de estados
- Banco de dados NoSQL
- Docker
- Code Magic ou qualquer ferramenta de automação de Builds
- Qualquer familiaridade com programação Back-end (Node.js, TS)
- Qualquer linguagem front (Ex.: React.js)

## Benefícios

- Auxílio Home-Office
- Vale Alimentação e/ou Refeição
- Vale Cultura
- Benefícios flexíveis creditados em um cartão de crédito Martercard {Vee/Swile}
- Plano de saúde e Odontológico {100% subsidiado pela empresa}
- Aulas de Inglês
- Convênio com academias Totalpass
- Convênio com Zenklub {Saúde Emocional}
- Finclass {Saúde Financeira}
- Day Off no aniversário
- Trabalho Remoto com horários flexíveis {Trabalhe de onde quiser!}
- E o melhor: Um ambiente de trabalho descontraído com colegas dispostos a te ajudar e a compartilhar conhecimento

## Contratação

A combinar

## Como se candidatar

Acesse: https://biscoint.gupy.io/jobs/1320600

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
