### ISSUE TITLE
[REMOTO/Internacional] Front-end Engineer @ HomeLight

### ISSUE THREAD

**Issue by nandosangenetto** [frontendbr/vagas#6098]
<p align="center"><img src="https://d1xt9s86fx9r45.cloudfront.net/assets/hl-production/assets/v4/logos/hl-logo-hr-color-light-49c88ce23dc887a90db89404e741f935ec7a475dfaf49fa73cd47e8e0697cc7c.png" /></p>

## Sobre a HomeLight
A HomeLight é uma startup de tecnologia que está revolucionando o setor imobiliário de US$ 1 trilhão. Nossa missão é simples - capacitamos as pessoas a alcançar melhores resultados durante um dos eventos mais importantes da vida: comprar ou vender sua casa.

A tecnologia da HomeLight analisa milhões de transações de casas para determinar qual corretor de imóveis ou comprador é certo para você. Também oferecemos soluções inovadoras de financiamento e fechamento, criando uma experiência imobiliária de ponta a ponta que é simples, certa e satisfatória.

Temos orgulho da cultura de nossa empresa - mas não apenas acredite em nós. Fomos reconhecidos como um dos melhores lugares para trabalhar pela [Forbes](https://www.forbes.com/americas-best-startup-employers/#44087aaa6527), [Inc. Magazine](https://www.inc.com/best-workplaces/2020.html) e pelo [San Francisco Business Times](https://www.bizjournals.com/sanfrancisco/news/2020/04/24/check-out-the-best-places-to-work-in-the-bay-area.html). Nossa equipe quebra barreiras todos os dias enquanto permanece comprometida com os objetivos e valores essenciais da empresa, que é um elemento crucial para o nosso sucesso.

## O que você vai fazer
- Adotar uma abordagem inovadora para criar novas features, ao mesmo tempo em que aprimora nossas features principais.
- Criar novos aplicativos web, adicionar recursos e funcionalidade aos nossos aplicativos principais que vão diretamente para as mãos dos usuários, compradores, vendedores e corretores de imóveis em todo o país americano.
- Contribuir para nossa biblioteca de componentes.
- Colaborar com o time de design e produto para entregar a melhor solução.

## Local
Remoto para sempre

Obs: Temos escritórios em San Francisco, New York, Phoenix e Seattle. Você pode visitar quando quiser.

## Requisitos

**Obrigatórios:**

- ⚛️ 💻  3+ anos de experiência com React.JS, com boas habilidades com arquitetura de componentes.
- 🖼  Domínio de CSS e HTML/Javascript.
- 📡  Experiência consumindo e transformando API's internal ou externas.
- 📏  Ser analítico e detalhista: ​Prezamos pela melhor experiência possível para nossos usuários (usuário sempre acima);
- 🇺🇸🇬🇧  Inglês intermediário (fala e escuta);
- 🇺🇸🇬🇧  Inglês avançado (leitura e escrita);

**Desejável:**
- 🔨 Experiência com *Next.js*, automação de testes (*Cypress*, Jest);
- 🔧 Experiência com acessibilidade, usabilidade, Node.js/Express, Heroku
- 👤 Experiência trabalhando em um time pequeno, idealmente em uma startup. 
- 📊 Familiaridade com web analytics, A/B testing, e metodologias ágeis
- 🇺🇸🇬🇧  Inglês fluente

**Diferenciais:**
- 🔴💎  Expertise com Ruby on Rails.

## Nossas principals tecnologias para a vaga
- Next.js (React)
- TypeScript
- Styled-Components
- React-Query
- Axios
- Cypress
- Jest

## Benefícios

- 📈 Stock options
- 🛫 Férias pagas de 15 dias *úteis* no primeiro ano
- ✈️ Férias pagas de 20 dias *úteis* no segundo ano
- 🚀 Mês sabático no quarto ano de empresa. SIM! Além das férias você ganha +30 dias corridos de férias.
- 🏝 Feriados flutuantes
- 🏥 Reembolso para Plano de saúde e(ou) plano dental.
- 💪 Reembolso para exercícios um valor mensal para você gastar com academia, natação, crossfit, etc
- ☕️ Reembolso coworking. Cansado de ficar em casa? Quer trabalhar 1x por semana em um escritório na sua cidade e ver seus colegas? Use este vale.
- 💰 5k USD para cada indicação de desenvolvedor que entre na empresa e fique por 90 dias
- 🕰 Horário de trabalho flexível

## Contratação
É uma contratação internacional, com pagamento em dólar, portanto é PJ.

## Como se candidatar
Acesse a página da vaga, neste endereço: https://boards.greenhouse.io/homelight/jobs/3609671

Caso tenha alguma dúvida, sinta-se a vontade de conversar comigo pelo [Telegram](https://t.me/nandosang) ou [Twitter](https://twitter.com/nandosang)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
Contato em caso de não haver resposta: [Telegram](https://t.me/nandosang) ou [Twitter](https://twitter.com/nandosang)

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by nandosangenetto** [comment]
Vaga fechada ontem.
