### ISSUE TITLE
[Rio de Janeiro ou Remoto] Desenvolvedor Fullstack com foco em Front-End AngularJS

### ISSUE THREAD

**Issue by aj07mm** [frontendbr/vagas#61]
## Descrição da vaga

Estamos procurando um full stack developer para o desenvolvimento de nossas plataformas produto da empresa.
Você terá a oportunidade de participar de projetos desafiadores em um ambiente descontraído e cooperativo, com uma equipe multidisciplinar.
Você participará de um movimento das chamadas Fintechs, empresas inovadoras no mercado financeiro que estão substituindo os bancos, com bastante inovação, serviços e tecnologia!
## Local

Remoto ou Escritório, Rio de Janeiro - Gávea
## Requisitos

**Obrigatórios:**
- HTML + CSS 
- JS
- AngularJS

**Desejáveis:**
- Que você ame desenvolver;
- Que você seja perfeccionista com seu código e não se furte de melhora-lo sempre que possível;
- Que seja comprometido com os prazos acordados;
- Que goste de entender profundamente como as coisas funcionam;
- Que estude sempre;
## Contratação

PJ a combinar
## Nossa empresa

Sobre a Órama:
Desde 2011 a Órama está no mercado suportada por 5 pilares que
descrevem o seu papel como instituição e a sua missão com seus clientes.
● Seleção criteriosa de Investimentos
● Tecnologia
● Educação Financeira
● Inovação
● Segurança
Estamos presentes em todo o Brasil com uma estrutura 100% online e comprometidos com a entrega do melhor serviço para que o brasileiro possa investir de forma consciente e transparente.
Primeira plataforma digital de investimentos no Brasil, premiada pela Amazon Web Services como uma das empresas mais inovadoras em Serviços Financeiros.
Os fundadores da Órama são os mesmos fundadores da Ágora Corretora, instituição reconhecida como uma das maiores corretoras do Brasil e uma das cinco maiores corretoras online do mundo, vendida para o Bradesco em 2008. Dando continuidade ao histórico de inovações, eles se uniram para criar a Órama.
## Como se candidatar

Envie seu currículo para anderson.carneiro@orama.com.br

**Comment by LFeh** [comment]
Boa vaga!

**Comment by gkal19** [comment]
Ainda esta procurando?

**Comment by eduardojmatos** [comment]
@aj07mm a vaga já foi preenchida? Nos avise pra mantermos ou removermos da lista :)

**Comment by chicojunior** [comment]
A vaga já foi preenchida?

**Comment by eduardojmatos** [comment]
@aj07mm se puder nos dar um status da vaga, seria bacana! :)

**Comment by nei** [comment]
Achei que estivesse respondido já. Sim foi preenchida. Obrigado galera.
