### ISSUE TITLE
[Joinville-SC] Front-End Developer na Simplustec

### ISSUE THREAD

**Issue by FernandoMueller** [frontendbr/vagas#610]
## Descrição da vaga

Oportunidade para trabalhar em uma Startup com um projeto com propósito único e inovador.
A Simplustec está procurando alguém  para fortalecer o time de desenvolvimento, ajudando o time nos desafios tecnológicos.

## Local

 Escritório, Joinville-Centro

## Desejáveis

- Experiência com HTML, CSS e JavaScript
- Experiência em desenvolvimento web com  AngularJS 1.x
- Controle de versionamento (Git)
- Automatizador de tarefas (WebPack, Gulp...)
- Gerenciador de Pacotes NPM
- Conhecimentos sólidos com Angular2, VueJs, ES6 ou TypeScript
- Autodidata
- Capacidade de aprender novas tecnologias e entregar valor a curto prazo
- Testes unitários

**Diferenciais:**

- Ter trabalhado com Scrum ou metodologias ágeis 
- Pesquisador(a) nas horas vagas

## Responsabilidades

- Desenvolver observando patterns, performance e escalabilidade
- Propor constantes melhorias no código afim de afinar performance do produto
- Ser 100% focado no resultado, garantindo as entregas e a produtividade do time

## Contratação

CLT

## Nossa empresa

Venha conhecer a Startup que vai mudar o varejo e seus fornecedores no mundo. https://www.youtube.com/watch?v=srBrcu75BHE

## Como se candidatar

Por favor envie um email para rh@simplustec.com.br com seu CV anexado - assunto: Vaga Front-End

**Comment by FernandoMueller** [comment]
@LFeh adicionar labels, perfil Pleno.

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
