### ISSUE TITLE
Remote - Angular Engineer (M/F) in Spark X

### ISSUE THREAD

**Issue by yoovanr** [frontendbr/vagas#6101]
**About us**
Spark X is your caring software development partner from Ukraine. Experienced outstaff team with Web & Mobile Development professionals that provides solutions both for startups and small/medium-sized businesses all over the world.

**What we are looking for**
We are looking for Angular Engineer (M/F) to join our team on full-time, long-term and hourly basis. If you have more than 3+ years of experience as a Front-End Engineer and 2+ years of experience working with Angular Framework, read more, and send your CV! Hourly rate range is between 15-22 USD per hour based on your skills.

**Location**
Fully remote, our company is located in Mykolaiv, Ukraine

**Requirements**
- 3+ years hands-on experience as a Front-End Engineer
- At least 2+ years of experience working with Angular Framework
- Strong knowledge of HTML, CSS and JavaScript
- Аbility to tune Webpack, Grunt and Gulp
- At least an upper-intermediate level of English
- Good communication skills, willing to learn, be a good team player
- Proficient understanding of cross-browser compatibility issues and ways to work around them
- Proficient understanding of code versioning tools, such as Git

**Responsibilities**
- Developing applications with Angular Framework
- Developing new features for existing applications
- Supporting existing applications
- Collaborate with other team members, leads and stakeholders

**What we offer?**
- Professional and career growth promotion
- Very good working atmosphere in a young & motivated team
- Exciting and challenging projects which offer room for your creative ideas
- Flexible working hours
- And a vibrant international team

**Seniority**
- Middle
- Strong Middle
- Senior

**How to submit?**
Please contact us by these contacts via email hr@sparkx.team, artem.misiura@sparkx.team or glen@sparkx.team.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
