### ISSUE TITLE
[Curitiba] Front-end Developer na CargOn

### ISSUE THREAD

**Issue by Francielli-Cristina** [frontendbr/vagas#6104]
# CargOn

Queremos fazer a diferença e para isso estamos em busca de um Desenvolvedor Front-end com excelente capacidade analítica, visão sistêmica e habilidade para resolução de problemas. Disposto a traduzir regras de negócio em soluções disruptivas, participar do desenvolvimento de produtos com alta performance, participar de discussões de arquitetura e criar inovação em um ambiente humano e criativo. Nosso objetivo é gerar impacto!
Temos Benefícios atrativos e salário compatível com o mercado.

## Requisitos:

Formação: Ciência da Computação, Engenharia ou áreas correlatas.

• 3 anos de experiência na área;

• Aptidão para resolver problemas;

• Excelente capacidade de raciocínio e execução de tarefas;

• Conhecimento de CSS, ReactJS, Javascript, e Lógica de programação.

## Responsabilidades:

• Implementação das telas propostas pelos designers;

• Desenvolver melhorias visuais para as telas já existentes no sistema;

• Criar componentes de ReactJS com o intuito de reutilizar esses componentes dentro do sistema;

• Buscar novas tecnologias e ferramentas Front-End que possam ser aplicados no nosso sistema;

## Diferencial: 

- Gostar de trabalhar em Equipe de forma colaborativa;

- Ter Flexibilidade e Adaptabilidade profissional;

- Maturidade de desenvolvimento técnico;

- Agilidade de execução com qualidade processual;

- Inteligência emocional;

- Comunicação clara e efetiva;

- Alto nível de conhecimento de CSS/Estilização.

## Local 

Curitiba

Escritório, [Paraná], [Curitiba], [Prado Velho]

## Contratação

CLT

## Como se candidatar

Por favor envie um email para vagas@cargon.com.br com seu CV anexado - enviar no assunto: Vaga Front end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 20  dias após cada processo.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
