### ISSUE TITLE
[Remoto] React Developer na Vetta Digital

### ISSUE THREAD

**Issue by clarabsa** [frontendbr/vagas#6107]
## Nossa empresa

Somos um centro de excelência em digitalização industrial e nossa missão é transformar indústrias e empresas através da digitalização e da eficiência energética. 

Atuamos em conjunto com a SMS group, empresa líder mundial no segmento de metais. Utilizamos tecnologia de última geração para produzir soluções com agilidade, entregando projetos em mais de 14 países pelo mundo.   

Queremos fazer a diferença e acreditamos com toda nossa fibra, que através da tecnologia é possível deixar o mundo mais sustentável e inovador.

O que não falta aqui na Vetta, são oportunidades de crescimento em um ambiente acolhedor e colaborativo. Se você tem interesse em deixar uma contribuição positiva no mundo, aprender sobre as tecnologias mais avançadas no mercado e aplicá-las em seu dia a dia profissional, vem com a gente!

A Vetta promove a inclusão e valoriza a diversidade em toda a sua multiplicidade e, também, todas as nossas oportunidades estão abertas para pessoas com deficiência e beneficiários reabilitados da previdência social.

## Descrição da vaga

- Desenvolvedor Front-End que trabalhará em projetos criando interfaces claras e modernas respeitando ao máximo os protótipos fornecidos pelo timo de design;
- Utilizar boas práticas e metodologias para manter um código limpo e legível;

## Local

Remoto

## Requisitos

**Obrigatórios:**

- Formação em Ciência da Computação, Sistemas de informação ou afins;
- Ter domínio para utilizar React Hook, State, Components, Redux e TypeScript;
- Conhecimento em framework React;
- Seja proativo em buscar novos conhecimentos e disseminar ao time;

## Benefícios

- Vale Alimentação/Refeição de R$22,70/dia
- Plano de Saúde
- Plano Odontológico
- Seguro de Vida
- Auxílio Creche
- PLR
- Auxílio Home Office no valor de R$100,00
- Desconto em Academias – Total Pass
- Desconto em Terapias Online – ZenKlub
- Clube de Descontos Online – New Value
- Day Off de Aniversário
- No Dress Code
- Programa de Incentivo a Formação Contínua
- Programa de Indicação de Talentos

## Contratação

CLT

## Como se candidatar

Por favor envie um email para clarisse.azevedo@vetta.digital com CV ou Linkedin - enviar no assunto: Desenvolvedor React

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
