### ISSUE TITLE
[remoto] Pessoa Desenvolvedora Frontend Pleno - VUE.JS @ Feedz

### ISSUE THREAD

**Issue by larissaaguiar** [frontendbr/vagas#6108]
🚀 A FEEDZ:
Nosso propósito é criar ambientes de trabalho mais felizes! Por isso, começar pelo nosso próprio ninho é tão importante! Somos Parrots determinados e que se importam uns com os outros, a sede de resultado é latente e o feedback sincero é rotina.

Aqui temos um ambiente de trabalho focado na cooperação entre Devs, confiamos no trabalho de nossos colaboradores e por isso acreditamos que nossos desenvolvedores devem ter autonomia!

Prezamos pela liberdade de falar o que se pensa e pelos feedbacks constantes, além de ter um time realmente diverso 💙 sabia que nosso time de produto é composto 42% por mulheres e 42% por pessoas negras?

Temos também flexibilidade de horários. Tem que ir ao banco? Precisa sair mais cedo para pegar os filhos na escola? Sem problema.

Estamos buscando uma pessoa para o cargo de Pessoa Desenvolvedora Frontend Pleno que irá atuar no nosso time de Produto, dentro da plataforma Feedz.

📚 RESPONSABILIDADES E ATIVIDADES:
Desenvolver com HTML, CSS(SASS ou Less), bootstrap e Javascript(VUE.JS) usando os melhores patterns, práticas e clean code;
Trabalhar com o desenvolvimento de módulos do software;
Entregar as experiências do time de design para nosso frontend;
Contribuir para o UX do produto;
Evoluir nosso ambiente de desenvolvimento com as melhores práticas e recursos;
Melhorar a performance e segurança do frontend;
Ajudar na construção e evolução de nosso Design System;
Implementar testes no frontend e realizar testes A/B;
Desenvolver tecnicamente seus pares;
Atualizar bibliotecas de desenvolvimento;
Estimar prazos das suas tarefas;
Conectar o frontend com o backend(não vai desenvolver em PHP, necessário apenas ter uma noção);

🥇 PRÉ-REQUISITOS:
3 anos de experiência no desenvolvimento frontend com JavaScript(VUE.JS), HTML e CSS;

✨ BENEFÍCIOS:
Vale Comida (R$600)
Plano de Saúde com Coparticipação Unimed
Plano odontológico Nacional da Bradesco Dental
Auxílio Parrot Feliz (R$100/mês de investimento no desenvolvimento pessoal, saúde física ou mental do Parrot)
Auxílio Contas (R$160/mês)
Auxílio Parrot Casamenteiro(R$250 quando Parrots casam)
Auxílio Ninhada(R$250 no nascimento ou adoção de pequenos Parrots)
Happy Bird(day) (um dia de folga no mês de aniversário)
Licença paternidade estendida(21 dias)
Licença maternidade estendida(6 meses)
Descontos nas empresas conveniadas com a ACATE
Ifood Office

💰 SALÁRIO R$ 4.400 A 5.390(CLT)*
*A DEPENDER DO TEMPO DE EXPERIÊNCIA

Candidate-se em: https://enliztjob.app.link/cIAxLdnhilb

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
