### ISSUE TITLE
[Remoto] Front-end Developer na Data Machina

### ISSUE THREAD

**Issue by evafurtado** [frontendbr/vagas#6109]
## Data Machina

Somos uma Startup na área de Análise de Dados com um perfil de pesquisa e inovação, ágil e eficaz! Nossa equipe tem o espírito de pesquisador que também tem vontade de transformar a teoria em ação (pesquisa aplicada), com um viés prático de quem quer resolver problemas concretos dos clientes - gostamos de problemas difíceis! Queremos transformar a realidade das cidades brasileiras e latinoamericanas, usando para isso ferramentas de Big Data, IA, Machine Learning, IoT, RA.

Conheça um pouco mais sobre nós: [www.datamachina.com.br](url)
Linkedin: [www.linkedin.com/company/datamachina](url)

## Descrição da vaga

Nesta posição, você irá nos ajudar na construção da experiência e interface de painéis interativos de visualização e tratamento de dados. Dentre suas responsabilidades, estarão a construção de fluxos e interfaces em processos de cocriação com os clientes, zeladoria da identidade e da coerência entre os diversos meios de entrega da unidade de negócios e articulação com a equipe de design.

O trabalho será realizado de forma remota. Procuramos pessoas que possam se dedicar de 20h a 40h por semana. Salário a combinar, de acordo com a experiência e disponibilidade. Oferecemos estágios!

## Local

Sempre remoto. 

## Requisitos

**Obrigatórios:**
- Conhecimento em HTML, CSS, Javascript e webdesign

**Desejáveis:**
- Python, NodeJS, VueJS, Firebase/Firestore, Firebase/Cloudfuncion, MongoDB, AWS, GCP, bibliotecas de construção de API
- É desejável, mesmo para quem se candidata para estágio, que já tenha tido uma experiência anterior, ou em outro estágio ou dentro da universidade.

**Diferenciais:**
- Ter um portfolio bem construído
- Navegar facilmente por conceitos de design

## Contratação

A combinar.

## Como se candidatar

Por favor, responda o questionário a seguir com suas informações. O formulário também pedirá para você anexar um currículo: https://lnkd.in/eXPkVebz

**Comment by BrunoCarolino7** [comment]
estágio com experiência?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
