### ISSUE TITLE
[São Paulo] Dev JavaScript (Redux, React.JS, Node.js) na Celebryts

### ISSUE THREAD

**Issue by stavarengo** [frontendbr/vagas#611]
_`Sugestão de labels: Alocado, CLT, PJ, Sênior`_
## Descrição da vaga

Estamos em busca de desenvolvedores FODAS para trabalhar em nossa Startup. Não importa a formação, o que importa é o talento e a vontade de fazer parte de um time para desenvolver uma plataforma super inovadora para o mercado. Estamos desenvolvendo uma plataforma completa para agências e grandes anunciantes encontrarem e contratarem influenciadores. Hoje, entre os nossos leads, estão as principais agências do Brasil, além de termos saído em grandes veículos da área, como meio&mensagem, mundo do marketing, globo news, etc.

Estamos crescendo e acabamos de levantar uma rodada de investimento para montar um time muito foda de tecnologia.

Veja mais sobre a startup: www.celebryts.com
## Local
Nosso escritório fica no co-work da IMasters, do lado do metro Sumaré.
Como estamos no mesmo prédio da IMasters, a gente tem acesso a todos os eventos fodas que eles fazem sem contar o networking com as outras startup do co-work e com a galera que frequenta aqui.
[Rua Oscar Freire, 2379 - Pinheiros](https://goo.gl/maps/3pW1PXokRP72)

## Benefícios
- Vale refeição
- Vale transporte
- Em alguns casos, você pode entrar no modelo de stock option da empresa
- A nosso office, é da hora!

#### Diferenciais
- Você faz o seu horário
- Máquinas de fliperama espalhados por todo o prédio \o/
- Linux, PC ou MAC, é só escolher ou se preferir pode trazer o seu ;)
- Todos os nossos robôs de busca tem nomes de personagens do Tolkien hahaha
- Trabalhar no prédio da IMasters é tesão.
- Frigobar, máquina de expresso, etc, etc, etc...

## Requisitos

**Obrigatórios:**
- Experiência com ReactJS e ES6:

**Desejáveis:**
- Experiência com NodeJS e/ou Redux e/ou ExpressJS.
- Que já tenha feito projetos bacanas, queremos ver portfólio, projetos...

## Contratação

CLT ou PJ (você escolhe)
## Nossa empresa

O Celebryt's é uma plataforma que ajuda as empresas/agências a encontrar influenciadores (Youtubers, instagrammers, snaps...) para suas campanhas de marketing. Tudo é "self service", o cliente faz as buscas, os planos e a contratação. Nossos robôs de buscas analisam constantemente uma grande quantidade de informação de cada perfil das redes sociais mais populares para conseguir encontrar os melhores influenciadores, entregando relatórios muito mais completos do que as redes socais onde os influenciadores atuam. E o mais legal: Todas essas informações são coletadas organicamente. É um projeto muito desafiador.
## Como se candidatar

Envie um email com o assunto `Job JS - frontendbr` para rafael@celebryts.com.

**Comment by stavarengo** [comment]
Primeira vaga fechada.  **Ainda temos mais duas vagas!!!!**

**Comment by Vitao18** [comment]
Tem vaga pra Júnior com experiência em React? 
@stavarengo

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante

**Comment by stavarengo** [comment]
@Vitao18, tem sim. 
Envie um email com o assunto `Job JS - frontendbr` para rafael@celebryts.com.
