### ISSUE TITLE
[Remoto] Front-end Developer (Angular) na Objetive

### ISSUE THREAD

**Issue by BrunaCarolineCarneiro** [frontendbr/vagas#6115]
## Nossa empresa
Somos formados por uma equipe de criadores, fanáticos por código, métodos ágeis, movidos pelo aprendizado e focados em compartilhar conhecimento. Vemos a tecnologia como liberdade e poder de transformação. Gostamos de questionar, aprender e encontrar caminhos inovadores, sempre baseados em dados. 📊

Respeitamos as diferenças e acreditamos que pensamentos, culturas e perspectivas distintas resultam em soluções melhores e aprendizado contínuo. E em meio aos desafios, com métricas e excelentes resultados, gostamos de nos divertir. 🎮 📚

Com unidades em São Paulo, Curitiba, Maringá e Chicago, estamos sempre em busca de talentos que queiram fazer parte e crescer com a gente! 👊

Algumas informações que você precisa saber:
- +400 colaboradores
- Uma das melhores empresas para se trabalhar no Paraná em 2019, segundo o GPTW
- Uma das empresas de TI que melhor remuneram no Brasil, segundo o Glassdoor
- Escritórios em São Paulo, Maringá, Curitiba e Chicago
- Referência em desenvolvimento ágil, com um case relatado no livro ‘The Scrumban [R]Evolution: Getting the Most Out of Agile, Scrum, and Lean Kanban’ do autor Ajay Reddy

Quer saber mais sobre a Objective?[ Visite nossa página.](https://www.objective.com.br/)
Aproveite e veja os nossos benefícios [aqui.](url)

#VemSerObj 😏

## Descrição da vaga
Buscamos pessoas desenvolvedoras Front end, em níveis de carreira pleno e sênior , que queiram trabalhar conosco em um ambiente descontraído e animado, no escritório de Maringá, Curitiba ou remotamente, que aqui chamamos de anywhere office.

## Local
Remoto

## Requisitos

**Obrigatórios:**
- Conhecimentos sólidos em Angular
- Padrões Web
- CSS3 / HTML5
- Integração Rest API's
- Aderência ao uso de TypeScript
- Desenvolvimento aplicando Padrões de projeto e Código limpo
- Conhecimento em Metodologias Ágeis

**Diferenciais:**
WordPress
Angular Universal
SEO
Algolia
ElasticSearch
Testes End-to-End utilizando Cypress
conhecimento em CI/CD
GitFlow

## Benefícios
- Cartão flexível (VR/VA);
- Plano de Saúde;
- Plano Odontológico;
- Estacionamento;
- Vale Transporte;
- PLR;
- Seguro de vida;
- Auxílio home office;
- Auxílio academia;
- Programa de indicação de funcionários;
- Convênios de descontos com universidades, escolas de idiomas e restaurantes.

## Contratação
CLT

## Como se candidatar
Você pode se candidatar a vaga clicando[ aqui.](https://objective.gupy.io/jobs/1330475)

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
