### ISSUE TITLE
[São Paulo/Hibrido] Front-end Developer na Ideal CTVM

### ISSUE THREAD

**Issue by IdealCorretora** [frontendbr/vagas#6116]
## Nossa empresa

Start up do setor financeiro de investimentos, atualmente liderando o ranking de contratos negociados no segmento de BMF da B3 e entre as 5 primeiras posições em volume financeiro negociado no segmento de Bovespa. 

A Ideal está no mercado desde fevereiro de 2019 e registra lucro desde seu segundo mês de operação. Por conta disto, recebeu interesse de diversos VCs onde recebeu uma das maiores rodadase de investimentos Series A da América Latina pelo fundo Kazek.

## Descrição da vaga

Estamos em busca de uma pessoa criativa, com cultura de colaboração e mente empreendedora para atuar em novos projetos que visam a criação de produtos diferenciados para nossos clientes, fazendo uso das principais tecnologias do mercado na atualidade. 

## Local

Hibrido, [SP], [SAO PAULO], [ITAIM BIBI]

## Requisitos

**Obrigatórios:**

- Git / SVN
- Graphql
- React
- Hooks (useState, useMemo, useEffect)
- CSS
- Material-UI
- Javascript / Typescript

**Desejáveis:**
conhecimentos em: 
- WebAPI (REST);
- SASS;
- UX / UI;
- Testes Unitários / Integração (jest);
- Cultura Devops;
- Container (Docker / Kubernetes); e
- Nuvem (Aws / Gcp / Azure).

## Benefícios

Salário compatível com o mercado
participação nos lucros
vale transporte / estacionamento
auxílio refeição
auxílio alimentação
seguro de vida

## Contratação

CLT

## Como se candidatar

Por favor envie um email para rh@idealctvm.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Pleno

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@idealctvm.com.br

#### Alocação
- Alocado
- Hibrido

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
