### ISSUE TITLE
[Remoto] Front-end Developer na Crosoften

### ISSUE THREAD

**Issue by marcellagenaro** [frontendbr/vagas#6123]
> Vaga Remota 

## Nossa empresa

Somos uma empreiteira de projetos digitais com quase duas décadas de solidez no mercado. Uma empresa de inovação e tecnologia que oferece soluções de estratégia, negócios, desenvolvimento e manutenção de aplicações tecnológicas.

## Descrição da vaga
Buscamos profissionais engajados, proativos, bons comunicadores e que estejam em busca de trabalhar com projetos novos e desafiadores.

## Local

Remoto
## Requisitos

**Obrigatórios:**
-Java ou Kotlin
-Integração API REST
-Experiência de 1 ano

**Desejáveis:**
-Experiência em projetos com bluetooth

## Benefícios
-Assistência Médica
-Assistência Odontológica
-Gympass
-Auxílio Terapia
- Auxílio Cultura
- Auxílio Internet
- Entre outros

## Como se candidatar

Envie um email para talentos@crosoften.com seu CV anexado - enviar no assunto: Vaga Android

#### Alocação
- Remoto

#### Regime
- CLT
ou
- PJ

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
