### ISSUE TITLE
[Remoto] Front-end Developer na Xgrow 

### ISSUE THREAD

**Issue by geekrootbr** [frontendbr/vagas#6124]
Somos uma empresa de tecnologia de edução em crescimento, com foco em ajudar criadores de conteúdo, professores e escolas a terem seus cursos disponibilizados na Internet com uma experiência de aprendizado diferenciada. 

Descrição da vaga

Você estará junto com a equipe no desenvolvimento do front-end da nossa ferramenta, criando interfaces web, áreas de aprendizagem, aplicativos móveis. Procuramos programadores com vontade de aprender, que desejem crescimento na carreira, que busquem uma visão de longo prazo na nossa empresa. Queremos pessoas que entendam e vivam nossa missão de transformar o ensino e usem seus talentos nessa empreitada.

Local
REMOTO

Requisitos

Obrigatórios:
Experiência de 3 anos+ ReactJS
JavaScript 
Typescritpt
HTML, CSS, SASS
Experiência com ferramentas de versionamento (GitHub)

Desejáveis:
	• conhecimento em NextJS

Contratação
PJ a combinar
Com diversos benefícios.

Como se candidatar:
Por favor envie um email para rh@xgrow.com com seu CV anexado - enviar no assunto: FRONT END DEV.

Tempo médio de feedbacks
Costumamos enviar feedbacks em até 2 dias após cada processo.

Regime
	• PJ

Nível
	• Sênior
	• Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
