### ISSUE TITLE
[Remoto] Desenvolvedor Shopify  na Flexcode Software

### ISSUE THREAD

**Issue by mateu5-francisco** [frontendbr/vagas#6126]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-shopify-201927234?utm_origin=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Bom conhecimento de UI, compatibilidade entre navegadores, design responsivo, funções gerais da web e padrões;</p>
<p>Analisar o código HTML existente enquanto constrói novos recursos que se integram perfeitamente com o código existente</p>
<p>Ter excelentes chops Shopify e Liquid</p>
<p>Promover o crescimento da equipe de desenvolvimento e criar soluções de comércio eletrônico interativas de alta qualidade</p>
<p>Criar sites com códigos personalizados através do Shopify (não apenas instale temas)</p>
<p>Garantir a viabilidade técnica dos designs de IU</p>
<p>Liderar o processo de descoberta no lado do desenvolvimento para novos projetos de construção de comércio eletrônico</p>
<p>Traduzir requisitos técnicos e modelos para sites totalmente funcionais usando HTML / CSS / JS</p>
<p>Procure continuamente maneiras de melhorar as taxas de conversão e implementar testes A / B</p>
<p>Eduque-se rigorosamente com as mais recentes técnicas de desenvolvimento e práticas recomendadas</p>
<p>Implementar novas tecnologias digitais ou técnicas de desenvolvimento que ajudem a cumprir as metas do cliente e objetivos de negócios</p>
<p>Crie código reutilizável e bibliotecas para uso futuro, otimização e escalabilidade</p>
<p>Realize a manutenção contínua do site, incluindo mudanças funcionais nas vitrines de comércio eletrônico</p>

## Flexcode Software: 
 <p>A nossa equipe é estrategicamente pequena, mas formada por profissionais dedicados à web que se reúnem para criar resultados poderosos. Resultados efetivos emergem do nosso foco e colaboração, à medida que nos dedicamos a um pequeno número de projetos de cada vez, gerando maior impacto. Com uma equipe inteiramente constituída por programadores web seniores, designers e criativos de todos os tipos, trabalhamos em conjunto, para si, para enfrentar um desafio de cada vez.</p>
</p>

 ## Habilidades: 
 - Ajax 
- Amazon EC2 
- Amazon S3
## Local: 
 100% Remoto
## Requisitos: 
 - + de 3 anos de experiência com Frontend Development 
- experiência com desenvolvimento de Shopify 
- Conhecimento em  HTML, JavaScript, AJAX, and maintainable/scalable CSS 
- Inglês fluente 

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Desenvolvedor Shopify  na Flexcode Software](https://coodesh.com/vagas/desenvolvedor-shopify-201927234?utm_origin=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
