### ISSUE TITLE
[Remoto] Frontend React Native Developer na N3urons

### ISSUE THREAD

**Issue by mateu5-francisco** [frontendbr/vagas#6131]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-react-native-developer-165324445?utm_origin=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>N3urons</strong> está buscando <strong><ins>Frontend Developer nível sênior </ins></strong>para compor seu time!&nbsp;</p>
<p>Buscamos profissionais que tenham capacidade de trabalhar em um time multidisciplinar entendendo a cultura de união e propósito do que fazemos, integrados como um só organismo assim como os neurônios que representam nossa startup.</p>
<p>Somos uma startup focada em soluções web/mobile inovadoras relevantes para o mercado que atuamos. Nosso diferencial é aplicar inteligência artificial com foco em automação e inteligência de negócios, com laboratórios incubados em empresas reais para validação dos nossos produtos.</p>
<p>Compartilhamento de conquistas e conhecimentos, soluções em conjunto, busca de melhoria contínua e sede de inovar são imprescindíveis. Na N3urons valorizamos estas soft skills antes de tudo!</p>
<p>Você irá participar da concepção de novos produtos como otimização das versões correntes, desde desenvolvimento mobile, web e participação dos projetos de UI/UX.</p>

## N3urons: 
 <p>Somos uma startup focada em soluções web/mobile inovadoras relevantes para o mercado que atuamos. Nosso diferencial é aplicar inteligência artificial com foco em automação e inteligência de vendas, com laboratórios incubados em empresas reais para validação dos nossos produtos.</p>
</p>

 ## Habilidades: 
 - React.js 
- React Native 
- Javascript 
- Rest e Restful APIs 
- Typescript 
- HTML 5 
- CSS 3
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência com desenvolvimento frontend web/mobile 
- Conhecimento avançado em React Native e JavaScript 
- Experiência com consumo de APIs REST 
- Experiência em times de desenvolvimento 
- Conhecimento nas Metodologias Ágeis 
- Conhecimento em TypeScript
## Diferenciais: 
 - Conhecimento avançado em Redux/Redux Saga, Codepush, Styled Components. 
- Conhecimento em Banco de Dados mobile ( Realm ) 
- Domínio em Javascript/React 
## Benefícios: 
 - Horário flexível (40hs semanais) 
- Plano de saúde 100% custeado pela empresa, sem descontos! 
- VR/VA mensal 
- Incentivos para participação em treinamentos, eventos, palestras e cursos 
- Envolvimento no propósito do projeto e não somente codar um escopo pré-definido
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend React Native Developer na N3urons](https://coodesh.com/vagas/frontend-react-native-developer-165324445?utm_origin=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
