### ISSUE TITLE
[Remoto] Front-end Developer na TotalPass

### ISSUE THREAD

**Issue by RecruTotalPass** [frontendbr/vagas#6133]
## Nossa empresa

A TotalPass é uma empresa que oferece benefícios corporativos para o bem estar, proporcionando acesso à diversos serviços como academias, estúdios especializados em corrida, boxe, yoga, ciclismo, treinos funcionais coletivos e desenvolvimento muscular. Temos prazer em descomplicar a vida dos nossos clientes com as nossas soluções e fazemos isso de uma forma colaborativa, em um ambiente desafiador. Estamos em expansão na América Latina e a área de tecnologia protagonizará grandes evoluções no negócio, diante dessa missão, valorizamos quem tem cabeça de dono, sonha grande e é apaixonado em aprender e ensinar.

## Descrição da vaga

● Desenvolver focado em entregas de software de qualidade com testes automatizados;
● Trabalhar em conjunto com o time de back-end para definição de APIs e modelo de dados;
● Garantir a aplicação de boas práticas durante o desenvolvimento do código

## Local

Remoto 

## Requisitos

**Obrigatórios:**
● Boa capacidade de comunicação e trabalho em equipe;
● Experiência em algum framework JS moderno (ex: React/Vue/Angular/Svelte);
● Experiência com gerenciamento de estado (ex: Redux/Vuex);
● Experiência em escrita de testes unitários;
● Experiência em utilização de frameworks CSS como Bootstrap, Bulma ou Tailwind CSS;
● Conhecimento de pré-processadores como Sass, Less ou Stylus;
● Conhecimento básico de bundlers e build tools: Webpack, Babel, NPM, Yarn;
● Seguir padrões de escrita de código conforme documentação dos frameworks;

**Diferenciais:**
● Espanhol e/ou inglês;
● Styled Components;
● Conhecimento básico de UI/UX;
● Experiência em escrita de testes E2E;

## Benefícios

● ✍️ Regime de contratação CLT;
● 😷 Assistência Médica | Bradesco Saúde;
● 🦷 Assistência Odontológica | Amil Saúde;
● 🚌Vale Transporte ou Home Office;
● 🍔Vale Refeição e Alimentação | Swile Benefícios Flexíveis
● 💰 Bonificação: 2 salários/ano | 1 por semestre – mediante entrega coletiva;
● 💻 Equipamentos para ter um espaço de trabalho em casa;
● 📚 Incentivo aos estudos | EduPass
● 󰙤 Plano TP5 TotalPass (+ inclusão de 10 dependentes) | Acesso aos serviços incluindo as academias do grupo Bio Ritmo, Smartfit e Queima Diária;
● 💸 TP Clube | Clube de descontos com marcas incríveis;
● 󰩋 Serviço de Saúde Mental | Parceria Psicologia Viva
● ⏰ Horário de trabalho flexível;
● ❤️ Seguro de Vida;

## Contratação

CLT

#### Como se candidatar

Por favor envie um email para dayanne.santos@totalpass.com.br com seu CV anexado

#### Regime
- CLT

#### Nível

- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
