### ISSUE TITLE
[Campinas - SP] Front-End Developer no Galoá

### ISSUE THREAD

**Issue by zsanmartin** [frontendbr/vagas#614]
**[Saiba mais no nosso blog](https://galoa.com.br/blog/vaga-para-desenvolvedores-front-end)**

## Descrição da vaga

Vaga para front-end, para trabalhar com Sass para web desktop e apps mobile, em ambiente Angular e PHP.

Nós temos um ambiente de trabalho tranquilo, porém somos super exigentes quanto a qualidade do código e dos produtos desenvolvidos. Temos uma cultura que privilegia o aprendizado, a colaboração e o comprometimento.

## Local

Barão Geraldo, Campinas - SP (próximo à Unicamp)

## Benefícios

* Plano de saúde
* Plano odontológico
* Vale refeição
* Vale alimentação

#### Diferenciais

* Um ambiente de trabalho confortável e focado no seu crescimento
* Horário flexível

## Requisitos

**Obrigatórios:**

Estamos procurando uma pessoa:

* Honesta, Comprometida e Organizada
  * Saiba como trabalhar com foco e eficiência
  * Preste atenção nos detalhes
* Que se importe com a qualidade do seu trabalho e seus resultados
* Que adora programar
  * Que está sempre aprendendo
  * Tenha a mente aberta
  * Goste de conhecer novas técnicas e tecnologias
* Que tenha experiência prévia com Desenvolvimento Front-end
  * Você já desenvolveu o front-end de alguns sites
  * Você tem desenvoltura com o CSS
  * Saiba utilizar pré-processadores CSS (LESS ou SASS)

**Desejáveis:**

* conhecimentos em Javascript
* conhecimentos em Angular
* conhecimentos em PHP

**Diferenciais:**

* projetos opensource

## Contratação

CLT

## Nossa empresa

Aqui no Galoá, desenvolvemos produtos para o mercado científico-acadêmico, sendo que as nossas ferramentas são utilizadas por mais de 200 mil pesquisadores, professores e estudantes brasileiros.

Nossa metodologia de desenvolvimento é ágil e fazemos diversos deploys diariamente para produção. Assim, trabalhamos com Integração Contínua (CI) em todos nossos produtos e Entrega Contínua (CD) em muitos dos nossos produtos.

## Como se candidatar

[Candidate-se aqui](https://chuva-inc.workable.com/jobs/595264)

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
