### ISSUE TITLE
[Remoto] Front-end Developer Pleno na Colored Byte

### ISSUE THREAD

**Issue by lucascredie** [frontendbr/vagas#6141]
> Vaga Remota durante a pandemia

## Nossa empresa

Somos uma agencia jovem que cria e-commerces usando a plataforma Shopify. Trabalhamos apenas com clientes internacionais e nosso time é composto por pessoas da America do Norte e do Sul!

www.coloredbyte.com 

somos pessoas de boa, jovens e que querem criar e-commerces foda e valorizam um ambiente sem ego. Vamos construir algo foda juntos? 

## Descrição da vaga

Como front end, você usaria html,css, js e liquid (Shopify) para criar componentes reutilizáveis, novas funcionalidades em lojas e designs criados no figma.

## Local

100% remoto, para sempre

## Requisitos

**Obrigatórios:**
- Ingles escrito fluente a falado medio-avançado
- 2 anos de experiência com Javascript
- 2 anos de experiência com CSS puro, na raça! 

**Desejáveis:**
- Conhecimentos em Shopify (sei que é raro!)

**Diferenciais:**
- Animações js/css com svg, ui design com figma/xd 

## Benefícios
como somos uma empresa americana contratamos como PJ, maaas oferecemos
- Horario Flexivel
- 2 semanas por ano de férias remuneradas
- Sempre remoto
- Ingles no dia a dia
- Incentivos educativos como cursos

## Contratação

PJ entre 8-12 mil reais/mês dependendo da experiencia

## Como se candidatar

Por favor complete o formulário abaixo:
https://admin757219.typeform.com/to/ADoSEJ4W

Como portfolio por favor poste exemplos live, não só seu code num repo :) 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em 1 semana depois das entrevistas, nosso plano é contratar alguem para começar ano que vem! 
E-mail para contato em caso de não haver resposta: admin@coloredbyte.com

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
