### ISSUE TITLE
[Hibrido / Belo Horizonte] Frontend Vue.js Developer na Onfly

### ISSUE THREAD

**Issue by mateu5-francisco** [frontendbr/vagas#6142]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-vuejs-160755236?utm_origin=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>Onfly</strong> está buscando <strong>Frontend Vue.js Developer</strong> para compor sua equipe!</p>
<p>Estamos buscando pessoa desenvolvedora frontend pleno, com conhecimentos em Vue.js, Javascript, Html e CSS3 com muita sede de aprender e se desenvolver na carreira técnica. Este profissional irá ajudar na evolução e manutenção da nossa plataforma.</p>
<p>Somos uma travel tech em acelerado crescimento, certificada como uma das melhores empresas para se trabalhar (GPTW), focada em ajudar as empresas a viajar melhor, com mais de 200 clientes (e crescendo).</p>
<p></p>

## Onfly: 
 <p>A Onfly oferece uma solução "all-in-one" com gestão de viagens (aéreo, hotel e carros), despesas e cartão corporativo em uma única plataforma digital. Com intensivo uso de tecnologia e uma boa dose de calor humano, elevamos ao máximo a gestão de viagens das empresas, trazendo conforto e produtividade para os colaboradores e segurança e economia para as empresas.  Simplifique, vá de Onfly!</p>
</p>

 ## Habilidades: 
 - Microfrontends 
- Javascript 
- Vue.js 
- Vuetify
## Local: 
 Belo Horizonte
## Requisitos: 
 -  Experiência com front-end, incluindo CSS e HTML; 
- Conhecimento em JavaScript; 
- Experiência com frameworks JS (React, React Native, Angular). 
- Integração com APIs, caches e performance;

## Benefícios: 
 - Horário Flexível 
- No dress-code 
- Cartão benefícios Flash
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Vue.js Developer na Onfly](https://coodesh.com/vagas/frontend-vuejs-160755236?utm_origin=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
