### ISSUE TITLE
[Híbrido Osasco - SP] Front-end Developer - Sr Software Engineer @ Uber

### ISSUE THREAD

**Issue by Cami-recrut** [frontendbr/vagas#6144]
## About Uber 

At Uber, we ignite opportunity by setting the world in motion. We take on big problems to help drivers, riders, delivery partners, and eaters get moving in more than 600 cities around the world!

We welcome people from all backgrounds who seek the opportunity to help build a future where everyone and everything can move independently. If you have a curiosity, passion and collaborative spirit, work with us, and let's move the world forward, together!

## About the role 

Partners with stakeholders and leads team efforts to design, develop, and maintain complex user interfaces and features for web applications that meet the design, functionality, and complexity needs of end users.

## Local

Híbrido Osasco - São Paulo

## Requisitos

**Obrigatórios:**

* PhD or equivalent in Computer Science, Engineering, Mathematics or related field OR 3-years full-time Software Engineering work experience, WHICH INCLUDES 2-years total technical software engineering experience in one or more of the following areas:

 - Programming language (e.g. JavaScript, CSS, Node.js)
 - Architecting, building, and maintaining web applications

* Note the 2-years total of specialized software engineering experience may have been gained through education and full-time work experience, additional training, coursework, research, or similar (OR some combination of these). The years of specialized experience are not necessarily in addition to the years of Education & full-time work experience indicated.

* API design
* Modern javascript
* Modern js framework
* UX

**Desejáveis:**

* Static typing systems

## Como se candidatar

Se inscreva na vaga [aqui](https://www.uber.com/global/en/careers/list/109937/)

## Sobre o processo seletivo 

Estamos realizando este processo em formato Hiring Event, [aqui](https://brazilengineeringhiringweek.splashthat.com/) você poderá checar mais informações sobre ele. 

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
