### ISSUE TITLE
[Remoto] Seja Front-end Developer na Capco!  [ByIntera]

### ISSUE THREAD

**Issue by biarogerio** [frontendbr/vagas#6147]
## Descrição da vaga
**[ByIntera]
Front-end Developer na Capco**

Cargo: **Desenvolvedor(a) Front-End**
Departamento: **Front-End**
Nível: **Pleno e Sênior**
Modelo de contratação: **CLT**
Local de trabalho: **Remoto**

**Candidate-se: https://bit.ly/32AnJ3J**

## Local

Remoto 

## Requisitos

**Obrigatórios:**

 📌 Experiência no desenvolvimento de aplicativos usando Angular 6/7/8/9; 
📌Experiência com a ferramenta de teste Transferidor;
📌Compreensão de trabalho de Angular-CLI e NodeJS;
📌Fundamentos sólidos de CSS;
📌Disposto a trabalhar com a equipe e outros desenvolvedores em toda a empresa para melhorar continuamente nossa abordagem de desenvolvimento;
📌Garanta uma documentação clara da funcionalidade criada / modificada;
📌Compreensão proficiente de ferramentas de controle de versão de código, como Git, Mercurial e / ou SVN;
📌Experiência em um ambiente de desenvolvimento Agile (Scrum).

## Benefícios

👍Plano de Previdência modelo PGBL/VGBL
🩺Assistência Médica
🦷Assistência Odontológica
💌Seguro de Vida e Acidentes Pessoais
📈PLR
🍔Vale Refeição
🛒Vale Alimentação
🚗Auxílio Deslocamento
🏃🏿‍♀️Gympass
👶🏾Auxílio Creche
📊Plano de Desenvolvimento Pessoal
🗣️Coaching

## Como se candidatar

Candidate-se através do link: **https://bit.ly/32AnJ3J**

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
