### ISSUE TITLE
[Remoto] Front-end Developer na Corebiz

### ISSUE THREAD

**Issue by hugocostadev** [frontendbr/vagas#6150]
## Nossa empresa

A [Corebiz ](https://www.linkedin.com/company/corebiz-brasil/) atua em toda jornada digital do usuário. Desde a configuração de plataformas, implementações e integrações, até a entrega de uma excelente experiência de consumo.

Juntamente com toda a equipe de marketing trabalhando para uma melhor performance digital, o que qualifica ainda mais a entrega da jornada do usuário.

## Descrição da vaga

Estamos procurando Desenvolvedor para atuar em um projeto internacional com contato direto com parceiros e clientes dos Estados Unidos e de outros países. 
O projeto é para trabalhar no ecommerce de uma grande empresa fabricante de Smartphones e outros eletrônicos com abrangência mundial, contando com mais de 50 websites.

**Atribuições da vaga:**

- Develop UI based components on provided designs or mockups
- Develop UI components that can be customized by the client through the VTEX Site Editor
- Code driven for performance, quality, and SEO
- Ensure that your code works in every browser and device required
- Keep the project’s documentation up-to-date
- GitFlow and CI/CD workflow in all the development process
- Support the QA team during the testing process.

## Local

 Remoto

## Requisitos

**Obrigatórios:**

- React and React Hooks
- JavaScript and TypeScript
- SASS and front-end frameworks like Tailwind and Tachyons
- Good verbal and written communication in English

**Desejáveis:**

- VTEX IO and VTEX APIs
-  NodeJS

**Diferenciais:**

- Jest or Cypress
- GraphQL
- Babel and Webpack

## Benefícios

- Plano de saúde
- Cartão Flash
- Day off no aniversário

## Contratação

CLT

## Como se candidatar

Por favor envie um email para hugo.costa@corebiz.ag com seu CV anexado e o link para o Linkedin - enviar no assunto: Front-end Developer na Corebiz

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
