### ISSUE TITLE
[REMOTO] Software Engineer na Flash Benefícios

### ISSUE THREAD

**Issue by Mariadafne** [frontendbr/vagas#6154]
Pessoa Engenheira de Software na Flash Benefícios

Inscreva-se: https://bit.ly/31gjzxV

FICHA TÉCNICA

Cargo: Pessoa Engenheira de Software
Nível: Sênior
Modelo de contratação: CLT
Local de trabalho: Remoto

REQUISITOS

Experiência em NodeJS, ReactJS e outros frameworks de Javascript;
Experiência com APIs REST, RPC ou Graphql (de preferência!);
Pessoas que buscam aprender e fazer parte de uma solução de alto impacto, entregando software de alta qualidade, orientado por dados e sempre focado no cliente;
Conhecimentos em Inglês (nossos códigos, documentações e ferramentas são frequentemente estruturados em Inglês. Eventualmente nos comunicamos com fornecedores de outros países).
Entende que o trabalho está em constante evolução. Estamos sempre nos preocupando e tentando evoluir os nossos serviços e a nossa forma de trabalhar.

BENEFÍCIOS

Vale Refeição
Vale Alimentação
Mobilidade
Educação e Cultura
Saúde e Bem-estar
PLR

Lembrou de alguém? Compartilhe: https://bit.ly/31gjzxV

**Comment by joatha** [comment]
A vaga ainda se encontra aberta ?
