### ISSUE TITLE
[Florianópolis] PHP Developer @ BRy

### ISSUE THREAD

**Issue by NovareRH** [frontendbr/vagas#6155]
## Nossa empresa

Há 20 anos no mercado, a BRy na aplicação de protocolos criptográficos para tornar operações e negociações digitais mais seguras. Apostam constantemente em parcerias e no desenvolvimento de tecnologia, são referência em soluções para carimbo do tempo, assinatura e certificação digital, infraestrutura de chaves públicas e biometria.

A ﻿﻿BRy ﻿destaca se por ser a única fabricante do Sistema de Carimbo do Tempo homologado pela ICP-Brasil e Observatório Nacional. Apresentaram um crescimento CAGR (taxa de crescimento anual composta) de 30% entre 2013 e 2018.

Hoje, são mais de 20 mil clientes atendidos, 2 bilhões de assinaturas digitais realizadas em nossas aplicações e mais de 100 milhões de carimbos do tempo emitidos.

﻿Atuam na aplicação de protocolos criptográficos para tornar operações e negociações digitais mais seguras. Com a tecnologia de carimbo do tempo, assinatura e certificação digital, a BRy auxilia na transformação paperless, a digitalização de processos e a otimização de tempo para grandes e pequenas empresas públicas e privadas que processam altos volumes de dados e documentos.

## Descrição da vaga

Dev Full Stack PHP - PL/SR - Florianópolis - SC

## Local

Remoto

## Requisitos
- Ensino médio completo ou superior cursando em áreas de tecnologia.
- Como a senioridade da vaga é PL/SR solicitamos uma boa bagagem de conhecimento dentro das tecnologias que nosso cliente usa.

## Tarefas

- Desenvolver APIs REST e micro serviços, voltados para o meio da certificação digital;
- Desenvolvimento de sistemas com escalabilidade e alto desempenho;
- Monitoramento e análise de consumo de recursos para otimizações dos produtos e soluções;
﻿﻿- Auxílio no suporte técnico em ambientes de homologação e produção.

## Tecnologias que você vai trabalhar:

- PHP 7 (Preferencialmente Laravel 5+);
- Angular 8+;
- JavaScript;
- Git;
- Kubernetes;
- Continuous Integration/Deployment(CI/CD);
- Docker;
- PostgreSQL;
- Redis;
- Testes automatizados.

## Responsabilidades﻿﻿

- ﻿Interesse em arquitetura com micro serviços, containers e mensageria;
- Foco na segurança de documentos eletrônicos;
- Auxílio na criação de rotinas de CI/CD;
- Interesse nas Normas da ICP BRASIL;
- Trabalho em equipe e metodologia de desenvolvimento Ágil.

## Benefícios

- Plano de Saúde Unimed e Odontológico Bradesco
- ﻿Vale Alimentação/Refeição ﻿- R$ 600,00 /mês

## Contratação

- De 8 a 10k - CLT

## Como se candidatar

Aplique para a vaga [por aqui](https://www.careers-page.com/novare-rh/job/67YXW5) .

#### Alocação
- Presencial

#### Regime
- CLT 

#### Nível
- Sênior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
