### ISSUE TITLE
[São Paulo] Analista de Suporte Front-end JR CLT R$2.500

### ISSUE THREAD

**Issue by gustaum** [frontendbr/vagas#6156]
> 

## Descrição da vaga

iCasei site de casamento

Jornada: Período Integral (40h Semanais)

Vínculo: CLT R$2.500,00

Salário: (até 15 salários) 

## Local

Local de trabalho: 100% REMOTO

Sede: Av. Chucri Zaidan 1550, 31º andar - São Paulo - CEP:04711-130 - Próximo ao Shopping Morumbi

## Requisitos

- Conhecimento básico em HTML

- Conhecimento básico em CSS

- Conhecimento básico em JavaScript

- Conhecimento básico em SQL

## Benefícios

• Alimentação (R$399,00)

• Vale-transporte;

• Participação nos lucros (até 2 salários baseados em metas);

• Seguro saúde (Omint);

• Ajuda de custo para cursos, livros e palestras (Até R$500,00 mês);

• Horário Seg a Sex (8h as 17h)

• Ambiente de trabalho sensacional;

• Gympass;

## Contratação

CLT

## Como se candidatar

É só preencher o nosso teste **https://forms.gle/pJbUPNtQXzq4fsWz5**

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior

**Comment by gustaum** [comment]
Muito importante fazer a candidatura através do link https://forms.gle/CU9YiGDVrBemXo7X9

Obrigado

**Comment by web-Matheus** [comment]
Qual o nome da empresa ? Quais as responsabilidade de quem for contratado? eu fiquei sem entender muito bem a vaga

**Comment by KLLYAR** [comment]
Olá boa noite. A vaga ainda está aberta?

**Comment by danii1290** [comment]
deveriam dar um feedback ao pessoal, mesmo pra quem ñ passou😔
