### ISSUE TITLE
[100% 🌎 Remoto] Lead Frontend Developer: React, TypeScript, Storybook, DevOps, CI/CD

### ISSUE THREAD

**Issue by jfoliveira** [frontendbr/vagas#6157]
> Vaga Remota - PERMANENTEMENTE REMOTA, Seja fera de onde cê quiser ser fera

## TL; DR

- Cê quer ser a pessoa de referência do frontend, tomadora de decisões, e criar algo que cê vai ter orgulho de contar pra todo mundo `eu sou parte dessa equipe`
- Você verá o produto que ajuda a construir causar impacto na comunidade de desenvolvedores e sys admins em todo o planeta
- Você fará parte na construção de uma plataforma inovadora de DevOps, CI/CD, multi-cloud que será utilizada por você e por seus colegas de profissão em todo o planeta
- Você terá papel de decisão na arquitetura, automação de testes e boas práticas no desenvolvimento de app web usando React, TypeScript, Redux, SWR e com foco em alta performance e excelente usabilidade
- Você se orienta por resultados, quer ver seus projetos serem concluídos e bem sucedidos, valoriza autonomia, reuniões objetivas, e entende o valor de automação, documentação e comunicação assíncrona via texto

## Nossa empresa

Estamos desenvolvimento plataforma CI/CD - ainda não lançada - que almeja ser um produto inovador no segmento de DevOps, IaC e GitOps, tendo devs e sysadmins como público alvo, e com inúmeros desafios de usabilidade e performance.

Nossa equipe é pequena, bem humorada e altamente qualificada, com trajetória de entregas em experiências anteriores, tendo cada fundador o mínimo de 10 anos de atuação no setor de tecnologia e desenvolvimento de software.

## Descrição da vaga

Buscamos pessoa apaixonada por desenvolvimento front-end, e com iniciativa e ousadia para enfrentar os desafios de oferecer uma interface amigável que simplifique a vida de nossos usuários, que são desenvolvedores de software como nós.

## Local

Não há exigência de horário ou local de trabalho. Nossa equipe já era remota mesmo antes da pandemia.
Nos comunicamos de maneira assíncrona via `Slack` e ferramentas de gestão de projetos.

## Benefícios
- Liberdade de trabalhar na hora que cê quiser de onde cê quiser. Desde que entregue as tarefas com as quais cê se comprometeu, tudo certo
- Equipe pequena, altamente técnica, bem humorada, e principalmente obstinada e orientada a resultados. Sem perda de tempo em discussões inúteis. A gente ama o que faz e foca na entrega de resultados
- Participar de todo o ciclo de vida de um produto SaaS, influenciando seu futuro

## Contratação

PJ, valor a combinar

## Como se candidatar

Por favor candidate-se via LinkedIn: https://www.linkedin.com/jobs/view/2811156190/

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias úteis após iniciado o processo seletivo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by brunosantanarj** [comment]
URL do linkedin do está para a parte de contratação, caindo numa tela de sem acesso. 
O ideal seria trocar para https://www.linkedin.com/jobs/view/2811156190/ pois candidatos menos atentos podem sair sem olhar a vaga.

**Comment by jfoliveira** [comment]
Boa sacada @brunosantanarj
Link atualizado.
Brigadão pelo toque!

**Comment by jfoliveira** [comment]
@brunosantanarj 
P.S.: aguardamos sua candidatura lá, caso se interesse pela vaga :)
