### ISSUE TITLE
[REMOTO] Front-end REACT

### ISSUE THREAD

**Issue by JCPBarbosa** [frontendbr/vagas#6158]
##REACT (Pleno/Sênior) 

## Descrição da vaga
DESENVOLVEDOR REACT Pleno/Sênior

## Local
Remoto

## Requisitos
- Experiência com React
- Experiência com Next 
- Experiência com TypeScript
- Experiência com Node

## Contratação
PJ 

## Como se candidatar
Por favor envie um e-mail para jefferson.cpires.ext@espm.br com seu CV anexado - enviar no assunto: Vaga React

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

#### Período
- Full time

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
