### ISSUE TITLE
[Santa Catarina] React Native Developer na @Riderize

### ISSUE THREAD

**Issue by fabriciosautner** [frontendbr/vagas#6159]
## Nossa empresa

Somos uma plataforma esportiva para Ciclistas. Desenvolvemos todo o ecossistema através de experiências importantes para quem é ciclista. Estamos nos preparando para o lançamento mundial.

## Descrição da vaga

Participar do time de Front-ends responsáveis pela aplicação React Native que move a plataforma. E ser protagonista na primeira empresa brasileira com Gravador de Atividades (pedaladas) no próprio App.

Como será seu dia a dia:
Participar de planejamento SCRUM junto com o time de desenvolvimento
Implementar tecnologias modernas dentro de um App
Conhecer todo o ecossistema de um aplicativo
Entregar features usadas por milhares de pessoas todos os dias
Evoluir na carreira de desenvolvedor trocando experiências com outros desenvolvedores
Sentir a experiência de programar lado a lado com pessoas incríveis e divertidas

## Local

Escritório em Rio do Sul/Santa Catarina

## Local

- R$ 15.000,00 - PJ

## Requisitos

**Obrigatórios:**
- Sólidos conhecimentos em React Native

**Desejáveis:**
- Experiência com Mapas/GPS

**Diferenciais:**

- GraphQL
- Relay/Suspense
- Recoil
- Typescript
- Realm
- AppCenter

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para contato@riderize.com com seu CV anexado - enviar no assunto: Vaga Sênior React Native

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: fabricio.sautner@riderize.com

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
