### ISSUE TITLE
[Belo Horizonte] Front-End Developer na Maxcast

### ISSUE THREAD

**Issue by danalchemist** [frontendbr/vagas#616]
## Descrição da vaga

Venha fazer parte de uma equipe inovadora. Se você é um developer Front-End apaixonado por interfaces, estamos esperando você!

## Local

Escritório, Belo Horizonte -MG (Buritis)

## Benefícios

- Plano de saúde
- Participação nos Lucros
- VR de R$ 22.00/dia
- VT

## Requisitos

**Obrigatórios:**
- Experiência com HTML5, CSS3, JavaScript, JQuery, NPM, Angular e Vue.JS
- Conhecimentos avançados em bootstrap
- Integrações com API Rest
- Controle de versionamento Git

**Diferenciais:**
- Node.js

## Contratação

CLT de R$ 3.000,00 a 5.000,00 (de acordo com o nível do candidato).

## Nossa empresa

A Maxcast é a lider nacional no mercado de streaming para rádios. 
Contamos com uma equipe de bons desenvolvedores e profissionais de rádio e marketing. Trabalhamos com projetos ambiciosos nesse setor. Venha inovar com a gente!

## Como se candidatar

Por favor envie um email para eduardolarbac@maxcast.com.br com seu CV anexado - enviar no assunto: Vaga Front-End Developer

**Comment by tidias17** [comment]
enviado :)

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
