### ISSUE TITLE
[Mogi Mirim/SP] Front-end Developer na Iniciativa

### ISSUE THREAD

**Issue by Priscilagraziela** [frontendbr/vagas#6160]
## Nossa empresa

Nosso propósito é trazer prosperidade para a Industria brasileira.
 
Nossa missão é ajudar nossos clientes, do pequeno ao grande, a viver o pleno potencial da gestão de negócios, através de uma plataforma que resolve a complexidade dos processos e é simples, intuitiva e eficiente, provendo educação empreendedora e serviços financeiros.
 
Nossa visão é juntos, liderarmos a transformação digital, servindo empreendedores e contadores e contadores para impulsionar a eficiência da indústria do Brasil.
 
Nossa cultura é de Startup, ritmo acelerado de desenvolvimento, altos desafios, uma galera incrível e muitas possibilidades de crescimento! :)

## Descrição da vaga

- Irá atuar no desenvolvimento e manutenção da plataforma e integrações;
- Automatização de processos dentro da plataforma;
- Conhecimento em desenvolvimento serverless;
- Irá atuar no desenvolvimento da aplicação utilizando framework padrão mercado;
- Apoio ao suporte técnico na identificação de problemas e mapeamento de solução.

## Local

Exemplo: Presencial, [São Paulo], [Mogi Mirim]

## Requisitos

**Obrigatórios:**

- Experiência em desenvolvimento de aplicações Web. 
- Back-end PHP com Laravel
- Front-end HTML, CSS e Bootstrap
- Experiência com ferramenta de versionamento de código (GitHub);
- Boa comunicação, bom humor, focado, e com alta capacidade de resolver problemas.

**Desejáveis:**
Conhecimento mySQL

## Benefícios

Vale Transporte
Vale Combustível
Auxilio Despesas

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um email para vagas@rossoconsultoria.com.br seu CV anexado - enviar no assunto: Vaga PHP

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.
E-mail para contato em caso de não haver resposta: priscila@rossoconsultoria.com.br

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by DanielHe4rt** [comment]
A vaga não faria mais sentido ser fullstack? Ia mandar pra um amigo mas fiquei confuso.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
