### ISSUE TITLE
[Remoto] React Developer na CI&T

### ISSUE THREAD

**Issue by analepechak** [frontendbr/vagas#6163]
**React Developer** 

**Quem somos**

Somos especialistas digitais impactando as marcas mais valiosas do mundo. Mais de 5 mil profissionais de estratégia, design e engenharia de software com presença com escritórios nos EUA, Brasil, Canadá, Reino Unido, Portugal, Japão, China e Austrália.

**Descrição da Vaga**

Projeto com cliente americano para atuar com **Reactjs.**

**Benefícios**

Plano de Saúde - sem coparticipação
Plano Odontológico
Zenklub | Plataforma de saúde mental e psicoterapia online
Gympass
Yoga
Vale Alimentação
Vale Refeição
Auxílio Home Office
Auxílio Creche
Auxílio Dependente PCD's
Seguro de Vida
Indicação Premiada
Programa Participação de Lucros

**Contratação**

CLT

**Como se candidatar**

Através da nossa página de carreiras: https://jobs.lever.co/ciandt/250cbda3-8ee9-4af7-af5b-14fe814ad979

**Tempo médio de feedbacks**

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: ana.lepechak@ciandt.com

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
