### ISSUE TITLE
[Remoto] Frontend React Developer na MPI Sistemas

### ISSUE THREAD

**Issue by bernardosaltiel** [frontendbr/vagas#6164]
## Descrição da vaga

Estamos no processo de desenvolvimento de um sistema ERP WEB e procurando pessoas que possa vir acrescentar na nossa equipe que hoje é formada por uma pessoa que faz tanto BACK-END/FRONT-END com isso dividido o trabalho e gerando resultado de forma mais rápida e estruturando uma equipe boa para crescimento desse projeto

## Local

Remoto

## Requisitos
- Javascript, React/Redux;
- Conhecimento com integração via API's;
- Boas práticas, commits explicativos, Clean Code;
- Design system;
- Noções de CI/CD;
- Qualidade técnica do código escrito (PR);
- WebComponents;
- SOLID;
- Ser organizado e ter conhecimento de boas práticas ageis;
- Conhecimento de SSR (next.js, gatsby..);
- Conhecimento de SPA; 
- Microfrontend;
- MaterialUI components;

## Como se candidatar

Por favor envie um WhatsApp para (51)99826-5585 com seu CV e seus projetos

## Labels

- 🏢 Flexível
- 🏢 Remoto
- ⚖️ A-Combinar

**Comment by miltonbolonha** [comment]
tks @bernardosaltiel
