### ISSUE TITLE
[Remoto] Front-end Developer na BoltInvest (React Native obrigatorio)

### ISSUE THREAD

**Issue by fernando-git-2021** [frontendbr/vagas#6165]
> 

## Nossa empresa

Somos uma plataforma de investimentos que tem a missao de democratizar alguns tipos de investimento que somente podem ser realizados através de tecnologia espcializada.

## Descrição da vaga

Estamos a procura de um desenvolvedor front-end  freelancer para nos ajudar a construir todo o front-end de nosso app de investimento a partir de nosso design no Figma. Aqui voce terá espaço para dar idéias e trazer novas soluções. A principio a vaga é de caráter temporario até o final da construção do app mas isto pode ser revisto ao decorrer do projeto.

## Local
Remoto

## Requisitos

**Obrigatórios:**
- React Native
-ReactJS
-Conhecimento em NextJS
-Typescript
-Consumo de API
-Conhecimento de GIT
-Conhecimento em autenticaçao com JWT

**Desejáveis:**
-SASS
-Prettier e ESLint para padronizaçao de codigo
-Uso de UseHooks e Hooks nativos do react

**Diferenciais:**
- Experiencia em React com uso de Typescript é um diferencial.
- Experiencia comTailwind
- Experiencia com a biblioteca Jotai seria um grande diferencial podendo ser substituido por Redux

## Benefícios

A combinar.

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para fernando.mtn.esteves@gmail.com com seu CV anexado - enviar no assunto: Vaga React Native

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
