### ISSUE TITLE
[Remote] Front-end Developer na Rocket.Chat

### ISSUE THREAD

**Issue by NataliaVillain** [frontendbr/vagas#6168]
## Rocket.Chat

Today one of the largest open-source projects in the world with more than 1000 developers, Rocket.Chat has advanced as a communication platform that empowers people to collaborate with others, while empowering individual teams to fully customize their platform to meet their unique needs.

## Descrição da vaga

Sr. Frontend Developer com foco em React e experiência com RESTful API, nível avançado de Inglês.

Descrição completa: https://rocket.chat/job?jobid=4051407004

## Local

Remoto

## Requisitos

**Obrigatórios:**
- > 4 anos de experiência com React
- Inglês Avançado
- RESTful API

**Diferenciais:**
- Projetos opensource;
- Times globais.

## Benefícios

- Plano de Saúde e Odontológico
- VR / VA
- Auxílio creche
- iTalki
- Stockoptions

## Contratação

CLT

## Como se candidatar

Por favor, envie um email para natalia.villain@rocket.chat com o assunto: Vaga Sr. Frontend
Ou, pelo LinkedIn: https://www.linkedin.com/in/nataliavillain/

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
