### ISSUE TITLE
[REMOTO] Desenvolvedor React Native Sênior na BUILDERS

### ISSUE THREAD

**Issue by RaissaBaltazar** [frontendbr/vagas#6171]
Somos uma comunidade de pessoas que desejam aprender, evoluir, empreender e construir iniciativas que gerem valor. Nosso propósito é te ajudar a construir o seu legado e te dar insumos para solucionar problemas reais na prática. Trabalhe com autonomia e em qualquer lugar do mundo, o momento para se tornar Builder é agora! 💪

Ao ingressar na Builders, você fará parte de um movimento que idealiza, cocria e conecta pessoas. Desfrutando de um ambiente colaborativo que propicia oportunidade de crescimento exponencial. Se você está em busca de autonomia, liberdade e curte desafios, aqui é o seu lugar.

Aqui você terá espaço para expor suas ideias e dar opiniões, desafiando o status quo todos os dias! 😉

**Tecnologias que vão gerar valor nos projetos 💻:**

- React (Redux/Mobx);
- Fluência em TypeScript;
- APIs REST;
- Trabalhar com diferentes dimensões de dispositivo (tablet, celular, etc)
- Conhecimento geral do ambiente móvel;
- Versionamento de código com Git;
- Conhecimento em arquitetura de software;
- Metodologias ágeis.

**O que te aproxima de ser uma Pessoa Builder 💪:**

- Conhecimento em CI/CD (App Center, Fastlane);
- Conhecimento em Firebase (Analytics, Crashlytics, etc);
- Experiência em linguagens nativas e construção de bridges.

**Como Builder, você terá acesso a 👀:**

- Oportunidades reais de empreender e impactar;
- Fazer parte de uma comunidade de empreendedores; de ponta, o Movimento;
- Inovação e criação liberados;
- Participar de um processo único de geração de valor;
- Contribuir na criação de métodos disruptivos;
- Colocar suas ideias no mercado, na prática!;
- Possibilidade de Profit share em novos Negócios;
- Prestador de Serviços (PJ)

Junte-se ao Movimento: https://jobs.kenoby.com/sejabuilder/job/senior-react-native-developer-cod-544-remoto/619d7de51dc119073ae61505?utm_source=website

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
