### ISSUE TITLE
[Remoto] Angular Developer na Tech For TI

### ISSUE THREAD

**Issue by Marco-Antonio-Recruiter** [frontendbr/vagas#6175]
## Introdução
A Tech For, Consultoria de Tecnologia da Informação desde 2008 no mercado e especializada em soluções inteligentes e referência na entrega de serviços de alta qualidade está com oportunidade para Devs Front-End com conhecimentos em Angular.

Para essa oportunidade estamos contratando para os seguintes clientes:
Cateno **(PJ)**
Clever TI **(PJ)**
123 Milhas **(CLT)** 

## Descrição da vaga

Oportunidades nacionais e internacionais para Dev Angular experientes.

## Local

**100% remoto**

## Requisitos

**Obrigatórios:**

- Angular 
- NodeJs/Typescript
- Java 
- Jquery
- React
- Bootstrap
- SQL e/ou NOSQL 
- UX
- Cloud (Azure ou AWS) 
- GIT
- Docker e Kubernetes 
- Metodologias ágeis 

**Desejáveis:**
- Prometheus ou Grafana
- Modelagem para Microsserviços
- DDD 
- Inglês Fluente (Conversação) 
- PSRS 
- Automação 

**Diferenciais:**
- Crawlers/Spiders 
- Graduação na área

Com base nos requisitos que o candidato possui  será direcionado uma ou mais oportunidades

## Como se candidatar

Enviar E-mail para: mpereira@techforti.com.br com o assunto "Angular Developer - Github" com seu CV anexado e sua pretensão salarial 

## Tempo médio de feedbacks

1º Entrevista - Imediato - 3 dias 
2º Entrevista - 7 dias - 15 dias.

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
