### ISSUE TITLE
[Remoto] Front-end Vue.JS na Panda Video

### ISSUE THREAD

**Issue by lafraia** [frontendbr/vagas#6177]
## Nossa empresa

A [Panda Video](https://pandavideo.com.br/) está chegando no mercado de hospedagem de vídeos focado no marketing digital, EAD e infoprodutos. Queremos em poucos meses ser referência neste mercado aqui no Brasil, retirando o Vimeo da jogada. Estamos construindo excelentes ferramentas com o foco neste público.

## Descrição da vaga

Ajudar no desenvolvimento do dashboard do usuário com controle de arquivos/vídeos, interface de produtos e vários outros projetos relacionados. Tudo com VueJS e backend em NodeJS (a maioria rodando em AWS Lambda), mas o foco para esta vaga aqui é mais frontend (VueJS).

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 2 anos de experiência avançada com VueJS

**Desejáveis:**
- conhecimentos em AWS
- conhecimentos em Node

**Diferenciais:**
- projetos pessoais públicos

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para daniel@pandavideo.com com seu CV anexado - enviar no assunto: Vaga Front-end

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by lafraia** [comment]
Não é remoto somente durante a pandemia, é remoto pra sempre :-) Desconsiderar o label.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by nerdstarcode** [comment]
Teriam vaga para algum estagiário??
