### ISSUE TITLE
[REMOTO] Front-end Developer na Flow Finance

### ISSUE THREAD

**Issue by fernandomoraes** [frontendbr/vagas#6179]
## Nossa empresa

The Next-Gen Platform For Automated Digital Lending - We’re Changing How Lenders Launch Amazing Products.

A Flow Finance é uma TechFin que fornece infraestrutura para FinTechs de crédito em dois formatos distintos:

**Credit Platform**: Infraestrutura para as fintechs criarem as suas próprias soluções de crédito automatizadas.

**Credit as a Service**: Soluções de crédito plug'n'play para grandes empresas ofertarem produtos customizados a sua base de clientes e parceiros.

## Descrição da vaga

Estamos iniciando alguns projetos, e para isso precisamos de front-end developers com experiência em React para nos ajudar a tirar alguns projetos do papel. 

## Local

Exemplo: Remoto

**Diferenciais:**
- 
- Ambiente totalmente green field de projetos, oportunidade para começar tudo do zero!
- Ambiente com pouca burocracia e bastante foco na entrega
- Salário competitivo 
- Trabalhar de onde quiser

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para fernando@flowfinance.com.br com seu CV anexado - enviar no assunto: Vaga Front-End

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: andre@flowfinance.com.br

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
