### ISSUE TITLE
[São Paulo] Full-Stack Developer na Cerensa

### ISSUE THREAD

**Issue by anibalwanderley** [frontendbr/vagas#618]
## Descrição da vaga

Projeto Cerensa - desenvolvimento de novas suítes da aplicação
Há posições para SENIOR e PLENO

## Local

Escritório no CUBO, São Paulo - Vila Olímpia

## Benefícios

- VR de R$ 20/dia

#### Diferenciais

- Possibilidade de participar de todos os treinamentos realizados no CUBO sem custos
- Frigobar eventualmente free

## Requisitos

**Obrigatórios:**
Sólida experiência com desenvolvimento de software de alta disponibilidade e escalabilidade;
- Profundo conhecimento de orientação a objetos;
- Afinidade com metodologias e paradigmas de desenvolvimento ágil;
- Profundo conhecimento de bancos de dados SQL (MySQL);
- Sólida experiência com frameworks Java (VRaptor/Spring/Hibernate);
- Prévia experiência com linguagens Javascript, Typescript, HTML5, CSS3;
- Sólida experiência com desenvolvimento Front-End utilizando frameworks (Angular2/4 ou React);

**Desejáveis:**
- Desejável experiência com os frameworks PrimeNG e Angular Material;
  Conhecimento de ferramentas de teste unitário como JUnit;
- Conhecimentos sólidos em Linux e Git;
- Inglês avançado para leitura e escrita.
- Espanhol

**Diferenciais:**
- Experiência em desenvolvimento rápido

## Contratação

PJ, valor a combinar

## Nossa empresa

CERENSA desenvolve inovações tecnológicas para empresas que desejam elevar seus padrões de governança em sustentabilidade e meio ambiente.
Nossas soluções auxiliam empresas a coletar, gerenciar, planejar e reportar informações com precisão. Asseguram conformidade com a legislação, minimizam riscos e elevam a lucratividade com o uso de novas tecnologias.
Trata-se de um dos negócios ais promissores na economia internacional com excelentes oportunidades no mercado brasileiro. 
Esta contratação é parte de um projeto de longo prazo onde a CERENSA busca profissionais que desejem participar desta iniciativa, expandindo a equipe de desenvolvimento pessoas que tenham interesse em aprender e crescer junto com a nossa empresa. 

## Como se candidatar

Caso esteja interessado, envie seu currículo para contato@cerensa.com com o Assunto: VAGA DEV FULL STACK JAVA SENIOR. 
Favor enviar pretensão salarial e disponibilidade de horário

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
