### ISSUE TITLE
[Remote] Front-end Engineer @ Constructor

### ISSUE THREAD

**Issue by shagabutdinov** [frontendbr/vagas#6180]
## About the company

Constructor is at the forefront of e-commerce search. We empower the biggest online retailers across the globe (such as Sephora, Backcountry, and Bonobos) with a state-of-the-art search engine that utilizes data and machine learning for personalization. Our search engine indexes hundreds of millions of products and serves billions of search requests to end-users each month. We are still a startup, but we've more than doubled our profits, company size, and clients over the last year - and we need your help to fuel this growth!

Our leaders are ex-engineers from a technology company in Silicon Valley and they've brought their learnings and experience to cultivate a great engineering culture. We are building our team on principles of care for each individual by being inclusive and people-focused.

## About the product

We are looking for an engineer to join the team behind the application that our customers use to drive search quality, run marketing campaigns, and launch new products. Our application provides tools for understanding search performance and user behavior.

Our main technologies are React and Typescript. We write tests using Jest, use Chakra and Figma as a design system, and use Emotion for styling components. We use Ruby On Rails as a backend framework, MySQL, and Elasticsearch as a data storage and analytic system.

## Responsibilities

* Developing features for the frontend applications with React and Typescript
* Developing API features using Ruby On Rails
* Developing automatic tests for the frontend and backend applications
* Code review
* Ensuring the application runs smoothly in the production environment
* Help in defining tasks

## Requirements

* Frontend experience with React
* Experience or willingness to work on the backend using Ruby On Rails
* Decent level of English proficiency

## Benefits

* Unlimited PTO
* A competitive compensation package including stock options
* Remote work with flexible hours
* MacBook provided by the company
* Coverage for flights for onsite whole-company gatherings

## Position

Fulltime employment, middle and senior level of experience, PJ type of contract, Fully remote position.

## How to apply

Use [our workable apply link](https://apply.workable.com/constructor-1/j/BB74B706C5/apply) or contact us directly through email leonid@constructor.io to schedule a chat. Note that most of our team don't speak Portuguese so be prepared to use English to talk to us.

## Contact

Drop a message to leonid@constructor.io if you have any questions.

## Labels

* Remote
* Fulltime
* Medium, Senior
* PJ

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
