### ISSUE TITLE
[remoto] Pessoa Desenvolvedora Fullstack Júnior PHP e JS(Exclusiva para Mulheres) na Feedz

### ISSUE THREAD

**Issue by larissaaguiar** [frontendbr/vagas#6181]
🚀 A FEEDZ:
Nosso propósito é criar ambientes de trabalho mais felizes! Por isso, começar pelo nosso próprio ninho é tão importante! Somos Parrots determinados e que se importam uns com os outros, a sede de resultado é latente e o feedback sincero é rotina.

Aqui temos um ambiente de trabalho focado na cooperação entre Devs, confiamos no trabalho de nossos colaboradores e por isso acreditamos que nossos desenvolvedores devem ter autonomia!

Prezamos pela liberdade de falar o que se pensa e pelos feedbacks constantes, além de ter um time realmente diverso 💙 sabia que nosso time de produto é composto 42% por mulheres e 42% por pessoas negras?

Temos também flexibilidade de horários. Tem que ir ao banco? Precisa sair mais cedo para pegar os filhos na escola? Sem problema.

Estamos buscando uma pessoa para o cargo de Pessoa Desenvolvedora Fullstack Pleno (PHP e JS) que irá atuar no nosso time de Produto, dentro da plataforma Feedz.

📚 RESPONSABILIDADES E ATIVIDADES:
Desenvolvimento backend com PHP;
Desenvolvimento de frontend com CSS, HTML e JavaScript;
Implementar códigos coerentes, coesos, claros e alinhados ao Clean Code;
Aplicar boas práticas alinhadas com o time no desenvolvimento (desenvolvimento seguro, patterns, automação, etc);
Trabalhar com o desenvolvimento de módulos dentro da plataforma;
Desenvolvimento e aplicação de testes automatizados;
Desenvolvimento de API sob demanda;
Fazer a gestão da informação das demandas atualizando o status dos projetos.

🥇 PRÉ-REQUISITOS:
1 ano de experiência em desenvolvimento web com PHP;
1 ano de experiência em desenvolvimento web com Javascript, HTML, CSS;
Experiência com testes e API;
Estar trabalhando atualmente com as tecnologias de nossa stack;
Experiência com banco de dados relacional;
Gostar de trabalhar em time. Pessoa Desenvolvedora sozinha não faz verão!

🎯DIFERENCIAIS:
Ter trabalhado em empresas SaaS;
Ter trabalhado com empresas com mais de 10 mil usuários.

✨ BENEFÍCIOS:
Vale Comida (R$600)
Plano de Saúde Unimed
Plano odontológico Nacional da Bradesco Dental
Auxílio Parrot Feliz (R$100/mês de investimento no desenvolvimento pessoal, saúde física ou mental do Parrot)
Auxílio Contas (R$160/mês)
Auxílio Parrot Casamenteiro(R$250 quando Parrots casam)
Auxílio Ninhada(R$250 no nascimento ou adoção de pequenos Parrots)
Happy Bird(day) (um dia de folga no mês de aniversário)
Licença paternidade estendida(21 dias)
Licença maternidade estendida(6 meses)
Descontos nas empresas conveniadas com a ACATE
Ifood Office

💰 SALÁRIO R$3.500 A R$4.000* (CLT)
*A DEPENDER DO TEMPO DE EXPERIÊNCIA
Candidate-se em: https://enliztjob.app.link/eDiERx0dPlb

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
