### ISSUE TITLE
[REMOTO] Frontend React Native Jr - Projeto fumico [vapes]

### ISSUE THREAD

**Issue by slimesaur** [frontendbr/vagas#6184]
[REMOTO] Frontend React Native Jr - Projeto fumico

## Descrição da vaga

Benchmark: PUFF BAR | EAZE | JUUL | Zé Delivery
Concorrentes: NIKBAR | Black Sheep

Projeto de desenvolvimento de uma plataforma de vendas B2C de cigarros eletrônicos - conceito minimal / clean / on-off
Buscamos um desenvolvedor free lancer para desenvolvimento deste case. Nosso interesse posterior é em manter continuidade no trabalho como dev fixo para novas implementações com planos arrojados de remuneração e stock options.

## Local

Work anywhere [Remoto]
Temos um escritório em Curitiba-PR, Centro Cívico.

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento frontend web/mobile;
- Conhecimento em React Native e JavaScript;
- Experiência com consumo de APIs REST;
- Conhecimento nas Metodologias Ágeis;
- Conhecimento em TypeScript.

**Diferenciais:**
- Conhecimento avançado em Redux/Redux Saga, Codepush, Styled Components;
- Domínio em Javascript/React.

## Contratação

PJ a combinar

## Nossa empresa

Projeto operacional de 5 meses de venda de cigarros eletrônicos, mercado em amplo crescimento com gaps ainda não explorados. O faturamento dobra mês à mês com previsão de elevar a tração. Buscamos criar um canal digital B2C e B2B para venda omnichannel dos produtos mobile, não é um marketplace. Visite nosso site atual onde roda o MVP: fumico.online

## Como se candidatar

Envie um email para guilhermerochasilva@gmail.com com seu CV anexado - enviar no assunto: Vaga React Native

Processo em 2 etapas: 

I) entrevista online para apresentar o projeto e entender o fit cultural
II) resolução de case em React

## Labels

- 🏢 Remoto
- 👨 Pleno
- ⚖️ PJ
- 💰 3k-6k

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
