### ISSUE TITLE
[São Paulo] Front-End Developer na Cerensa

### ISSUE THREAD

**Issue by anibalwanderley** [frontendbr/vagas#619]
## Descrição da vaga

Desenvolvimento de novas suítes da Plataforma Cerensa
Utiliza Angular

## Local

Escritório no CUBO, Rua Casa do Ator 919, São Paulo - Vila Olímpia

## Benefícios

- VT
- VR de R$ 20/dia

#### Diferenciais

Possibilidade de participar de todos os treinamentos realizados no CUBO sem custos
Frigobar eventualmente free

## Requisitos

**Obrigatórios:**
Preferencialmente Graduação em Engenharia; Tecnólogo em processamento de dados ou formação semelhante.
- Sólida experiência com desenvolvimento de software de alta disponibilidade e escalabilidade;
- Prévia experiência com linguagens Javascript, Typescript, HTML5, CSS3;
- Sólida experiência com desenvolvimento Front-End utilizando frameworks (Angular2/4 ou React);
- Desejável experiência com os frameworks PrimeNG e Angular Material;
- Afinidade com metodologias e paradigmas de desenvolvimento ágil;
- Domínio de chamadas assíncronas utilizando JSON como formato de transporte e REST.
- Conhecimentos sólidos em Linux
- Conhecimento em ferramentas de versionamento, preferencialmente Git;
- Inglês avançado para leitura e escrita.

**Desejáveis:**

- Experiência com design responsivo é desejável;
- Espanhol

**Diferenciais:**
- Conceitos avançados de UI e UX;

## Contratação

PJ 
Salário a combinar

## Nossa empresa

CERENSA desenvolve inovações tecnológicas para empresas que desejam elevar seus padrões de governança em sustentabilidade e meio ambiente.
Nossas soluções auxiliam empresas a coletar, gerenciar, planejar e reportar informações com precisão. Asseguram conformidade com a legislação, minimizam riscos e elevam a lucratividade com o uso de novas tecnologias.
Trata-se de um dos negócios ais promissores na economia internacional com excelentes oportunidades no mercado brasileiro. 
Esta contratação é parte de um projeto de longo prazo onde a CERENSA busca profissionais que desejem participar desta iniciativa, expandindo a equipe de desenvolvimento pessoas que tenham interesse em aprender e crescer junto com a nossa empresa. 

## Como se candidatar

Caso esteja interessado, envie seu currículo para contato@cerensa.com com o Assunto: VAGA DEV FRONT END.

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
