### ISSUE TITLE
[Recife] Pessoa Desenvolvedora React/React Native na Mobix Software Studio

### ISSUE THREAD

**Issue by joaovictortinoco** [frontendbr/vagas#6190]
## Nossa empresa
Olá! Somos uma software house com sede em Recife, Pernambuco, Brasil. 

A Mobix trabalha com desenvolvimento de aplicações Mobile e Web em tecnologias como React/React Native/NodeJs ...
Ambiente de trabalho leve, com empatia, aprendizado constante e cultura de sempre buscar o melhor para todos é o que nos move.

Se tu acha que faz sentido participar do processo seletivo, você pode mandar um alô para dev-team@mobixtec.com
E se tu quiser saber como a gente trabalha, se liga em http://github.com/mobixsoftwarestudio e em http://mobixtec.com

## Local

Remoto.  Caso seja do seu interesse, temos possibilidade de alocação para Recife (e ajuda de custo de aluguel se tu vier morar aqui, visse?)

## Requisitos

# React Native:
- Conhecimento em algoritmos e estrutura de dados
- Conhecimento de arquitetura mobile
- Experiência sólida em React Native - deve ter participado da entrega de pelo menos um App para a Play Store/App Store
- Conhecimento em testes e2e

# React Js:
- Conhecimento em algoritmos e estrutura de dados
- Conhecimento de arquitetura web e padrão de projetos
- Experiência sólida em ReactJs - deve ter experienciado ao menos o deploy de um produto em produção 
- Conhecimento em testes e2e

## Benefícios

- 50% do Plano de Saúde c/ cobertura nacional
- Plano dentário: 100% coberto pela Mobix
- Cartão Alimentação + Auxílio Home Office + Premiação
- Horário de trabalho super flexíveis
- Folga no dia do teu aniversário
- Cobertura para cursos como línguas ou especialização
- Material de escritório e acessórios (Laptop, mouse, teclado etc)
- Ambiente de trabalho super leve (No dress code)
- Happy Hour mensais pagos pela empresa (suspensos durante pandemia)
- Acesso a comunidades, bibliotecas/repositórios e cursos pagos pela empresas
- Vale transporte (Para os que moram em Recife e optarem pelo benefício)
- Auxílio mudança para quem reside fora do Grande Recife (RMR)
- 30 dias corridos de férias

## Contratação

PJ nos primeiros 3 meses, CLT em seguida.
CLT até R$8.180,00 (nível do cargo é avaliado durante o processo)

## Como se candidatar

Por favor envie um email para dev-team@mobixtec.com com seu CV anexado - enviar no assunto: [Github] Vaga Frontend

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by brd3v** [comment]
Tem vaga ainda?

**Comment by aquelefelipe** [comment]
> Tem vaga ainda?

estamos sempre recebendo interessados em fazer parte do nosso time, so mandar email mandando um alô

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
