### ISSUE TITLE
[Remoto] Fullstack Developer na Pix Force

### ISSUE THREAD

**Issue by mateu5-francisco** [frontendbr/vagas#6191]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/pessoa-desenvolvedora-full-stack-144656036?utm_origin=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A Pix Force desenvolve soluções utilizando tecnologias de visão computacional e inteligência artificial. #1 no ranking da <em>100 Open Startups em 2021</em>. Estamos em total expansão e com planos de internacionalizar em 2021. Vamos juntos?</p>
<p></p>
<p><strong>Atividades</strong></p>
<p>- Atuar em projetos de desenvolvimento para web com soluções em visão computacional.</p>
<p>- Desenvolvimento de software Full Stack.</p>

## Pix Force: 
 <p>A Pix Force desenvolve soluções utilizando tecnologias de visão computacional, inteligência artificial e machine learning. Fornecemos informações valiosas para os nossos clientes através de aquisição e interpretação automática de imagens e vídeos.</p>
<p>Startup #1 em visão computacional no Brasil e multipremiada.</p><a href='https://coodesh.com/empresas/pix-force'>Veja mais no site</a>

 ## Habilidades: 
 - Python 
- React.js 
- Vue.js
## Local: 
 100% Remoto
## Requisitos: 
 - Graduação (ou em andamento) na área de ciências da computação e áreas correletas; 
- Experiência em linguagens Python no Backend; 
- Experiência com frameworks de Frontend como VueJS (preferencial) ou React.
## Diferenciais: 
 - Conhecimento em Docker, Linux, Git e Bitbucket. 
- Experiência de 1 ano em desenvolvimento de software.
## Benefícios: 
 - Ambiente desafiador, colaborativo e exponencial 
- Startup #1 em Inteligência Artificial no Ranking 100 Open Startups 
- Jornada flexível 
- Home Office 
- Contrato PJ ou CLT
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack Developer na Pix Force](https://coodesh.com/vagas/pessoa-desenvolvedora-full-stack-144656036?utm_origin=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
