### ISSUE TITLE
[Florianópolis/SC] Back/Front Developer na ESSS

### ISSUE THREAD

**Issue by Esss0102** [frontendbr/vagas#6192]
> Vaga Remota durante a pandemia

## Nossa empresa

A ESSS é uma multinacional brasileira sediada na cidade de Florianópolis/SC. Disponibilizamos ao mercado as mais avançadas ferramentas de CAE na área de fluidodinâmica, análise estrutural, eletromagnetismo e multifísica, além de customização e desenvolvimento de softwares sob medida de acordo com a necessidade de cada cliente. Estamos presentes no Brasil e no exterior, incluindo Argentina, Chile, Colômbia, França, Espanha, Estados Unidos, México, Peru e Portugal.
Se você acredita que suas habilidades, talentos e experiências são diferenciados para trabalhar em um time de alta performance, responsável pela resolução de problemas por meio da tecnologia e desenvolvimento de softwares, faça sua inscrição.

## Descrição da vaga

Se você é um entusiasta por inovação e tecnologia e busca uma empresa onde possa compartilhar ideias, conquistas e trabalhar em um ambiente saudável, onde possa se desenvolver pessoal e profissionalmente, estamos com oportunidades em aberto para Desenvolvedor de Software. 

Para essa posição seus principais desafios serão: 

Desenvolver softwares de simulação computacional para engenharia.
Desenvolver aplicações Web com testes automatizados (testes unitários e de aceitação).
Integrar as bibliotecas desenvolvidas pelo nosso time de desenvolvimento numérico e científico em aplicações gráficas para o usuário final.

Tecnologias que Utilizamos:

Python 3 e JavaScript.
Aplicações Web em Angular.
Back-end utilizando Flask, SQLAlchemy, Celery.
Infraestrutura com Docker.
Testes automatizados (unitários, integração e end-to-end).
Metodologias Ágeis (Integração Contínua, Revisão de Código, SCRUM).

## Requisitos

Não é necessário conhecimento nas tecnologias listadas acima, entretanto experiência prévia será considerada para definição do nível do cargo (júnior, pleno, sênior).
Inglês intermediário.

## Benefícios

Disponibilizamos:

Plano de saúde nacional com subsídio integral sem coparticipação (melhor operadora da região).
Cartão de benefícios flexíveis.
Licença maternidade e paternidade estendidas.
Oportunidade para contribuição em projetos open source.
Incentivo a educação continuada através de cursos, treinamentos e especializações e auxílio idiomas.
Incentivo a publicações, participações em eventos de tecnologia relevantes para seu trabalho.
Mais de 20 outros benefícios.

## Contratação

CLT

## Como se candidatar

Se inscreva pelo link https://esss.gupy.io/jobs/1337969 ou envie email para selection@esss.co

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
