### ISSUE TITLE
[Florianópolis/SC] Desenvolvedor Numérico na ESSS

### ISSUE THREAD

**Issue by Esss0102** [frontendbr/vagas#6193]
> Vaga Remota durante a pandemia

## Nossa empresa

A ESSS é uma multinacional brasileira sediada na cidade de Florianópolis/SC. Disponibilizamos ao mercado as mais avançadas ferramentas de CAE na área de fluidodinâmica, análise estrutural, eletromagnetismo e multifísica, além de customização e desenvolvimento de softwares sob medida de acordo com a necessidade de cada cliente. Estamos presentes no Brasil e no exterior, incluindo Argentina, Chile, Colômbia, França, Espanha, Estados Unidos, México, Peru e Portugal.
Se você acredita que suas habilidades, talentos e experiências são diferenciados para trabalhar em um time de alta performance, responsável pela resolução de problemas por meio da tecnologia e desenvolvimento de softwares, faça sua inscrição.

## Descrição da vaga

Se você é um entusiasta por inovação e tecnologia e busca uma empresa onde possa compartilhar ideias, conquistas e trabalhar em um ambiente saudável, onde possa se desenvolver pessoal e profissionalmente, estamos com oportunidades em aberto para Desenvolvedor Numérico.

Para essa posição seus principais desafios serão: 

Participar da análise e modelagem de problemas de engenharia por meio de abstrações computacionais e métodos numéricos;
Desenvolver núcleo numérico para softwares de simulação com testes automatizados (testes unitários e de aceitação);
Análise e projeto de arquitetura de software;
Realizar correções e aperfeiçoamentos em softwares existentes.

Tecnologias que utilizamos:

Desenvolvimento multi-plataforma Linux e Windows;
Metodologias Ágeis (Integração Contínua, Revisão de Código, SCRUM);
Numpy, Scipy, Pandas, Reaktoro, Eigen, Jupyter, Git.

## Requisitos

Requisitos exigidos:

Desenvolvimento multi-linguagem C++ e/ou Python 3;
Inglês intermediário;
Trabalho em equipe.

Conhecimento prévio em alguns destes itens são valorizados:

Modelagem de equilíbrio químico envolvendo eletrólitos;
Cálculo e métodos numéricos;
Termodinâmica
C++ moderno/avançado;
Boas práticas em design e arquitetura de software;
Inglês avançado.

## Benefícios

Disponibilizamos:

Plano de saúde nacional com subsídio integral sem coparticipação (melhor operadora da região).
Cartão de benefícios flexíveis.
Licença maternidade e paternidade estendidas.
Oportunidade para contribuição em projetos open source.
Incentivo a educação continuada através de cursos, treinamentos e especializações e auxílio idiomas.
Incentivo a publicações, participações em eventos de tecnologia relevantes para seu trabalho.
Mais de 20 outros benefícios.

## Contratação

CLT

## Como se candidatar

Se inscreva no link ou envie [email](https://esss.gupy.io/jobs/1380452) para selection@esss.co 

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
