### ISSUE TITLE
[Florianópolis/SC] Front-end Developer na ESSS

### ISSUE THREAD

**Issue by Esss0102** [frontendbr/vagas#6194]
> Vaga Remota durante a pandemia

## Nossa empresa

A ESSS é uma multinacional brasileira sediada na cidade de Florianópolis/SC. Disponibilizamos ao mercado as mais avançadas ferramentas de CAE na área de fluidodinâmica, análise estrutural, eletromagnetismo e multifísica, além de customização e desenvolvimento de softwares sob medida de acordo com a necessidade de cada cliente. Estamos presentes no Brasil e no exterior, incluindo Argentina, Chile, Colômbia, França, Espanha, Estados Unidos, México, Peru e Portugal.
Se você acredita que suas habilidades, talentos e experiências são diferenciados para trabalhar em um time de alta performance, responsável pela resolução de problemas por meio da tecnologia e desenvolvimento de softwares, faça sua inscrição.

## Descrição da vaga

Se você é um entusiasta por inovação e tecnologia e busca uma empresa onde possa compartilhar ideias, conquistas e trabalhar em um ambiente saudável, onde possa se desenvolver pessoal e profissionalmente, estamos com oportunidades em aberto para Desenvolvedor de Software com foco em front-end. 

Para essa posição seus principais desafios serão: 

Desenvolver softwares de simulação computacional para engenharia.
Desenvolver aplicações Web com testes automatizados (testes unitários e de aceitação).

Tecnologias que Utilizamos:

Foco em JavaScript/Typescript.
Aplicações Web em Angular.
Back-end utilizando Python 3, Flask, SQLAlchemy.
Infraestrutura com Docker.
Construção e estrutura de stylesheet utilizando SCSS.
Testes automatizados (unitários, integração e end-to-end).
Metodologias Ágeis (Integração Contínua, Revisão de Código, SCRUM).

## Requisitos

Requisitos Exigidos:

Desejável experiência prévia mínima de 3 anos.
Experiência com algum framework JavaScript moderno (preferência para Angular, Vue.js ou React)
Experiência com Desenvolvimento de aplicações com Design Responsivo.
Nível intermediário de CSS.
Inglês intermediário.

## Benefícios

Disponibilizamos:

Plano de saúde nacional com subsídio integral sem coparticipação (melhor operadora da região).
Cartão de benefícios flexíveis.
Licença maternidade e paternidade estendidas.
Oportunidade para contribuição em projetos open source.
Incentivo a educação continuada através de cursos, treinamentos, especializações e auxílio idiomas.
Incentivo a publicações, participações em eventos de tecnologia relevantes para seu trabalho.
Mais de 20 outros benefícios.

## Contratação

CLT

## Como se candidatar

Se inscreva no [link ](https://esss.gupy.io/jobs/1395924) ou envie email para selection@esss.co

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
