### ISSUE TITLE
[Remoto] Sr. React Front-end Developer na Vigil 🇬🇧

### ISSUE THREAD

**Issue by renato-obst** [frontendbr/vagas#6196]
## Nossa empresa

A Vigil é uma consultoria de tecnologia europeia com presença no Brasil e que atende exclusivamente clientes da Europa em projetos estratégicos onde um alto nível técnico é necessário.

## Descrição da vaga

Esta é uma oportunidade rara que reúne:

* Trabalho 100% remoto
* Projeto internacional / English-First (Reino Unido)
* Time de alto nível técnico
* Ótimo ambiente de trabalho, que preza pelo equilibrio Vida / Trabalho
* Ótimo salário fixado em Euros e no modelo PJ - Faixa de 4.5K a 5.5k de Euros
* Contrato de longo termo

Estamos procurando Senior React Frontend Engineer que possua interesse nesta oportunidade e esteja qualificado(a) para assumir a responsabilidade de:

* Fazer parte de um time de alto nível técnico trabalhando em parceria com uma das maiores empresas de mídia do Reino Unido
* Contribuir com a criação de um produto global altamente estratégico
* Liderar o processo de prova de conceito e definição arquitetural da principal aplicação frontend do produto
* Colocar a mão na massa e contribuir com a execução da aplicação planejada
* Definir e implementar toda a pipeline de CI/CD da aplicação, incluindo deploy automatizado para todos os ambientes

## Local

100% Remoto

## Requisitos

**Obrigatórios:**

- 4+ years of web application development experience
- 3+ years of ReactJS - Proven end to end experience
- Strong Javascript knowledge
- Experience in developing enterprise web applications consuming internal APIs
- Experience with Agile and leading agile teams
- Experience in frontend automated tests
- Strong English communication skills - Reading, Listening and Speaking

**Desejáveis:**
- GraphQL
- Cypress
- GO CD
- AWS

## Benefícios

- Modelo PJ com 20 dias úteis de férias remuneradas
- Feriados do Brasil
- Salário fixo em Euro

## Contratação

PJ - Faixa salarial - 4.5K a 5.5k de Euros

## Como se candidatar

É só aplicar para a oportuniade aqui: https://www.vigil.global/frontend-engineer-react

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by victorbiasibetti** [comment]
o e-mail é qual?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
