### ISSUE TITLE
[Remoto] ReactJS Front-end Developer na Ambizzion

### ISSUE THREAD

**Issue by 500544542** [frontendbr/vagas#6197]
> Vaga Remota 

## Nossa empresa

É uma empresa provedora de serviços e soluções integradas de sistemas, alinhadas com as principais estratégias corporativas através de uma equipe altamente qualificada. Nossa experiência e comprometimento traduzem o alto nível de satisfação e reconhecimento dos nossos clientes.
## Descrição da vaga

Exemplo: Projeto bazinga em NodeJS, etc.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com ReactJS

## Contratação

PJ 

## Como se candidatar

Por favor envie um email para mateus.bastiani@ambizzion.com.br seu CV anexado - enviar no assunto: Vaga ReactJS

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 48 horas após cada processo..
E-mail para contato em caso de não haver resposta: mateus.bastiani@ambizzion.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível

- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
