### ISSUE TITLE
[Joinville / SC] Engenheiro de Software - Front-end 

### ISSUE THREAD

**Issue by 21051307** [frontendbr/vagas#62]
Como um engenheiro da ContaAzul você vai trabalhar com grandes desafios de escalabilidade provocadas por enormes quantidades de dados e uma população rapidamente crescente de usuários, em um ambiente altamente divertido e colaborativo!

Nós precisamos de alguém que tenha paixão por resolver problemas complexos. Um profissional com fortes competências em estruturas de dados e algoritmos, juntamente com um fascínio técnico de como as coisas se encaixam.

Um engenheiro de software motivado a experimentar e arriscar, afim de fazer a diferença em sua área, que não tem medo de defender suas idéias e aceitar mudanças, ao lado de pessoas altamente capacitadas e motivadas a melhorar cada vez mais.

RESPONSABILIDADES
Codificar sistemas elegantes que exigem pesquisa, interatividade e curiosidade;
Escrever testes automatizados que garantam a qualidade da solução desenvolvida;
Analisar e melhorar a eficiência, escalabilidade e estabilidade de vários recursos do sistema.

REQUISITOS E QUALIFICAÇÕES NECESSÁRIAS
Bons conhecimentos de SOLID (Object-oriented design), Clean Code e Design Patterns e TDD;
Conhecimento em arquitetura Front End, usabilidade, performance e testabilidade;
Conhecimento em tecnologias JavaScript (AngularJS, Node.js, jQuery, etc);
Conhecimento em CSS em larga escala, LESS e prototipação de telas;
Conhecimento em grandes Single Page Apps utilizando APIs backend.Experiência com frameworks Javascript MV*;
Conhecimento em ferramentas de automação front-end como Grunt, Gulp ou Webpack.

BENEFÍCIOS
Um ambiente de trabalho diferente e inovador com uma cultura que valoriza as pessoas e a entrega de resultados;
Autonomia e flexibilidade;
Comida e bebida à vontade;
Salário compatível acima da média do mercado;
Vale refeição/alimentação de R$400;
Auxílio educação e pós graduação;
Auxílio idioma;
Convênio com farmácias;
Plano de saúde integral e sem desconto em folha;
Plano odontológico integral e sem desconto em folha;
Auxílio atividade física e aula de yoga;
Um time que tem os nossos valores em seu DNA;
Morar em uma das melhores cidades para viver no Brasil;
Acesso a livros e materiais;
Vale transporte;
Muitos desafios e aprendizados;
Oportunidade de eventos e cursos que deixem você mais próximo dos melhores do mercado;
Os melhores happy hours da cidade!

O cadastro para a vaga é realizado através da nossa página de carreira:
https://contaazul.com/carreiras/vagas#vagas-abertas

**Comment by LFeh** [comment]
Boa sorte ;)

**Comment by eduardojmatos** [comment]
@21051307 a vaga já foi preenchida? Nos avise pra mantermos ou removermos da lista :)

**Comment by fernahh** [comment]
@eduardojmatos e @LFeh vocês podem fechar essa vaga? Provavelmene isso aqui foi um BOT. Em seguida foi abrir um issue com vagas que estão em aberto aqui na ContaAzul.

Obrigado!

**Comment by eduardojmatos** [comment]
@fernahh vou fechar, valeu por avisar!
