### ISSUE TITLE
[REMOTO] Desenvolvedor(a) Front-end React - Pleno @ZAHIRHEADHUNTER

### ISSUE THREAD

**Issue by ZaHiRHeaDHuNTeR** [frontendbr/vagas#6201]
Desenvolvedor(a) Front-end React - Pleno (Remoto)
Requisitos
•	Experiência com desenvolvimento React;
•	Conhecimento em JavaScript e TypeScript;
•	Clean Code;
•	Metodologia Ágil;
•	Framework Scrum.
Atividades:
•	Atuar com desenvolvimento Reac;
•	Trabalhar com desenvolvimento de novos produtos;
•	Em conjunto com a equipe definir e executar o melhor fluxo para desenvolvimento de novas tarefas;
•	Participar de plannings, retrospectivas e outras reuniões com o time;
•	Colaborar com o aprendizado de outros desenvolvedores e outras pessoas da equipe;
•	Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas.
Oferecemos:
•	Oportunidade de crescimento
•	Cultura colaborativa, de gestão horizontal e incentivo à troca de feedbacks
•	Remuneração compatível com a nível mercado.
•	Vale Refeição/Alimentação (Cartão Flash)
•	Benefício de saúde com Gympass 
•	Nossa universidade corporativa com trilhas de aprendizagem em parceria com a Alura;
•	Day-off e vale compras no aniversário;
•	Vittude - Plataforma de terapia online.

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um e-mail para zahir.headhunter@gmail.com com seu CV anexado - enviar no assunto: Front-end React

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
