### ISSUE TITLE
[Remoto] Front-end ReactJs Developer na AltoQi

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#6205]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedora-front-end-182751357?utm_origin=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>O Grupo AltoQi é uma empresa com soluções de software altamente especializadas para a construção civil. Somos movidos por grandes desafios e estamos em busca de pessoas que estejam dispostas a trabalhar com propósito, tecnologia e estar em constante aprendizagem.</p>
<p>Estamos em crescimento e buscando novos talentos. Procuramos alguém que esteja disposto a embarcar nessa trajetória conosco e gerar impactos positivos na vida das pessoas.</p>
<p>Por isso, procuramos uma <strong><em><ins>Pessoa Desenvolvedora Front-end (Pleno/Sênior)</ins></em></strong> para somar à nossa equipe e nos ajudar a crescer, ajudando a desenvolver nossas propriedades web e fazer a manutenção das mesmas.</p>
<p></p>
<h6><strong>Quais os principais desafios dessa função?</strong></h6>
<ul>
<li>Participar do desenvolvimento de nossas propriedades web como site, e-commerce, Landing Pages e outros projetos ligados ao desenvolvimento web.</li>
<li>Prezar pela manutenção de nossas propriedades web.</li>
</ul>
<p></p>
<p><strong><ins>Porque a AltoQi?</ins></strong></p>
<ul>
<li>Oportunidade de começar uma nova era e contribuir para a alavancagem da empresa;</li>
<li>Oportunidade de trabalhar com profissionais que são referência no mercado.</li>
</ul>
<p></p>
<p>Faça parte de uma equipe que acredita na diversidade e inclusão. Aqui você pode ser você mesmo.</p>

## AltoQi: 
 <p>Em 30 anos de mercado, o Grupo AltoQi tem transformado a vida dos projetistas, executores, corporações e moradores, levando inovação, acesso à tecnologia e ao conhecimento</p>
<p>Acreditamos que o trajeto profissional que traçamos em nossas vidas, é parte fundamental daquilo que somos. Nosso desejo é que nossos colaboradores se desenvolvam e construam um caminho de sucesso. Buscamos pessoas que tenham brilho nos olhos e vontade de fazer acontecer. A igualdade e o respeito são valores fundamentais para nós, nosso ambiente incentiva a empatia, o trabalho colaborativo e o aprendizado.&nbsp;</p><a href='https://coodesh.com/empresas/altoqi'>Veja mais no site</a>

 ## Habilidades: 
 - React.js 
- Javascript 
- Styled Components 
- HTML 5 
- CSS 3
## Local: 
 100% Remoto
## Requisitos: 
 - Desenvolvimento Front-end em React/JavaScript 
- Ensino Superior Completo em Ciências da Computação, Engenharia da Computação, Sistemas de Informação ou graduação equivalente em TI 
- Conhecimentos em Styled Components
## Diferenciais: 
 - Conhecimentos em Next.js 
- Conhecimentos em metodologias ágeis
## Benefícios: 
 - Horários Flexíveis 
- Opções de Vale alimentação e/ou Vale refeição 
- Convênio com a ACATE e SESC 
- Plano de saúde com mensalidade paga pela AltoQi 
- Parceria com Assistência Odontológica 
- Auxílio home office durante a pandemia 
- Disponibilização de equipamentos para o home office 
- Parcerias com redes de farmácia, restaurantes e faculdades 
- No dress code (investimos no conforto, não há códigos para se vestir, desde que se sinta bem!)
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Front-end ReactJs Developer na AltoQi](https://coodesh.com/vagas/desenvolvedora-front-end-182751357?utm_origin=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
