### ISSUE TITLE
[REMOTO] Front-end Developer @Conta Simples

### ISSUE THREAD

**Issue by Contasimples** [frontendbr/vagas#6206]
SOBRE A @Contasimples

Gestão de despesas e conta corrente em um só lugar, com plataforma inteligente de múltiplos cartões. Feita para as empresas da nova economia assumirem o controle dos gastos e ganhar eficiência nas operações do dia a dia.
Além disso, a Conta Simples carrega na sua história um crescimento exponencial, sendo uma das scale-ups que mais se destaca no cenário de fintechs voltadas para empresas, conquistamos o reconhecimento como a segunda startup brasileira a ser investida pela Y Combinator, estamos na lista das 100 Startups to Watch (PEGN) e entre as 50 Startups que mudam o Brasil (Exame).
E não para por aí, nossos simplers já nos reconhecem como um dos melhores lugares para trabalhar, mas agora somos oficialmente considerados um "Great Place to Work", certificados pela GPTW em 2021.
www.contasimples.com
https://contasimples.gupy.io/

## Descrição da vaga

Participar ativamente definindo, desenvolvendo, implantando, acompanhando e mantendo soluções com qualidade e escaláveis. Auxiliar na evolução e desenvolvimento do time e seus processos de desenvolvimento de software.

## Local

REMOTO

## Requisitos

- Conhecimento em Javascript e React;
- Conhecimentos em desenvolvimento de testes automatizados utilizando frameworks (como Jest, Testing Library, Jasmine, Mocha, etc);
- Conhecimento de boas práticas de desenvolvimento de software (design patterns, SOLID, Clean code);
- Conhecimentos de cloud computing (desejável AWS) e arquitetura serverless;
- Conhecimentos em diferentes protocolos de comunicação e sólidos conhecimentos no protocolo HTTP e API Rest.
- Diferenciais:
- Experiência em empresas em alto crescimento.

## Benefícios

VR + VA

- Auxilio Home Office
- Plano de Saúde/ Odontológico (rede nacional, acomodação apartamento, sem desconto de mensalidade e sem coparticipação para o titular e + 2 dependentes);
- Gympass e TotalPass;
- Auxílio creche para recém nascidos.

**Diferenciais:**

- Day off no aniversário;
- 01 day off por mês;
- Acréscimo remunerado (bonificação)

## Contratação

PJ flex (com direito a 30 dias de recesso remuneradas)

## Como se candidatar

Favor enviar o seu cv por email: vagas@contasimples.com com o assunto: [NOME VAGA] + GITHUB

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05/10 dias após cada processo.
E-mail para contato em caso de não haver resposta: vagas@contasimples.com

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
