### ISSUE TITLE
[REMOTO] Front-end React Developer na TQI - Technology and Quality on Information

### ISSUE THREAD

**Issue by alvaropsc** [frontendbr/vagas#6207]
## Nossa empresa

Que incrível que você está aqui e tem interesse em fazer parte dos nossos times. A TQI é feita para você, sim você que quer ousar sem receio e vivenciar grandes desafios. Você fará parte de times multidisciplinares e de alta performance, em um ambiente descontraído, dinâmico e colaborativo que te proporcionará constantes aprendizados e desenvolvimento.

Aqui, você encontrará liberdade e autonomia, atuando com metodologias ágeis em projetos inspiradores. Sua voz e sua contribuição são muito importantes para nós, para a construção dos nossos produtos e também para nossas tomadas de decisões.

Não tenha receio em pedir ajuda e compartilhar novas ideias, é assim que conseguimos transformar insights em soluções extraordinárias, somos um time e juntos respiramos inovação.

E ainda vamos além do código, aqui você aprende e também tem a oportunidade de ensinar, construir e evoluir, na TQI você será protagonista da sua carreira.

Conheça mais sobre nossa empresa: https://www.tqi.com.br/

## Descrição da vaga

Escrever código limpo, de fácil manutenção, utilizando as melhores práticas de desenvolvimento de software;
Apresentar melhorias nos sistemas existentes e garantir a qualidade nas entregas;
Ajudar e compartilhar sua experiência com os membros da equipe.

## Local

100% Remoto para Sempre!

## Requisitos

**Obrigatórios:**

JavaScript, CSS e HTML;
ReactJs, React Router, ContextApi e Hooks para contrução de interfaces de usuário;
Ferramentas de testes unitários tais como: Jest, Testing Library, Enzyme ou Cypress;
Usar ferramentas de empacotamento como Webpack, Rollup ou parcel;
Criar páginas web responsivas;
Usar e conhecer o que são pré-processadores e padrões de CSS;
O que é Styled Components e seu uso;
Git e como é o Git flow.

**Desejáveis mas não eliminatório:**

TypeScript e versões mais recentes do ECMA Script;
NextJs, Redux (Thunk/Saga) ou MobX;
Conhecimento de Docker, Pipelines, CI/CD (AWS, Google Cloud);
Experiência em utilizar e/ou publicar pacotes NPM;
Conhecimento da Arquitetura do Front-end e como é o Microfrontend;
Domínio de ferramentas de monitoramento como Sentry; logrocket, entre outros.

## Benefícios

Jornada de Trabalho: 

⏰ Horário comercial, 8h diárias, Segunda a Sexta;
🎒 Trabalho 100% remoto;
⌚ Horário flexível.

Lista de Benefícios CLT:

- Ticket Alimentação 1012,00 no cartão Flash;
- Auxilio Home Office mensal;
- Convênio Médico Apartamento e Odontológico sem coparticipação (valor apenas para dependentes conforme faixa etária);
- 14º Salário
- Gympass para você e mais 3 dependentes;
- Seguro de Vida
- Acesso ilimitado a plataforma Alura para cursos e capacitação;
- Parceria com descontos em faculdades e escolas de idiomas.

Lista de Benefícios PJ:

- 20 dias de férias remunerados;
- Clube de Benefícios Lincard
- DIT - Seguro de Vida (Auxilio de 7.500,00 mensal caso precise se afastar do trabalho por motivo de saúde pelo tempo que ficar afastado);
- Gympass para você e mais 3 dependentes;
- Seguro de Vida
- Acesso ilimitado a plataforma Alura para cursos e capacitação;
- Parceria com descontos em faculdades e escolas de idiomas.

## Contratação

PJ ou CLT

## Como se candidatar

Por favor envie um email para talentos@tqi.com.br com seu CV anexado - enviar no assunto: Front-end React - GitHub.

## Tempo médio de feedbacks

Temos um fluxo de contratação contínua, e TODOS candidatos recebem feedback de forma contínua durante o processo seletivo.
E-mail para contato em caso de não haver resposta: alvaro.santos@tqi.com.br

## Remuneração

Temos um budget flexível, olhamos o candidato em sua totalidade, experiência, vivência, modalidade de contratação para formalização da proposta.

#### Categoria

- React

#### Alocação

- Remoto

#### Regime

- CLT
- PJ

#### Nível

- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
