### ISSUE TITLE
[Belo Horizonte] Front-End Developer na Getrak.com

### ISSUE THREAD

**Issue by plantaz** [frontendbr/vagas#621]
## Descrição da vaga

Integrar um time de desenvolvimento de soluções B2B de rastreamento veicular com foco em ferramentas da segurança e redução de custos operacionais para empresas do segmento.

Precisamos de um front-end developer que se sinta desafiado a utilizar novas tecnologias que  possibilitem valor agregado a experiência do produto indo de interfaces mais comuns como web e mobile ate devices de rastreamentos e wearables.

## Local

Bairro Belvedere (Próximo ao BH shopping) - Belo horizonte/MG

## Benefícios

- Plano de saúde
- VR
- VT

#### Diferenciais

- Jornada flexível
- Ambiente descontraído
- Investimento em capacitação
- Fliperama, quick massage, frutas e confraternizações mensais

## Requisitos

**Obrigatórios:**
- Mínimo de 2 anos na área de front-end.
- Conhecimento avançado em Front-application/Javascript(suficiente para trabalhar bem com as tecnologias desejadas) e mediano em CSS, HTML5 e GIT.

**Desejáveis:**
- Tecnologias desejadas: React.js, Node.js, AngularJs 1 e AngularJs 2, webpack, babel, teste unitário e linux.
- Conhecimentos desejados: Ferramentas de automação e gerência de pacotes (Grunt, Gulp entre outras), Lean development, Performance Tuning e Responsive webdesign.
- Comprometimento com entregas, Engajamento com objetivo da empresa
- Auto-gerenciável, atitude e responsabilidade sobre os atos, trabalho em equipe.
- Acompanhamento de novas tecnologias, abertura a testar novas abordagens.
- Trabalho em equipe, facilidade em se comunicar com colegas e debater sobre soluções buscando a melhor solução.

**Diferenciais:**
- Dominar bem o React.js

## Contratação

CLT a partir de R$ 3702,60 (de acordo com o nível do candidato).

## Nossa empresa

Referência internacional em tecnologia e infra-estrutura para empresas de rastreamento. Responsável pela maior base de veículos rastreados da América Latina e uma das maiores em BIG DATA deste segmento em todo mundo.

A Getrak é uma empresa que desenvolve soluções m2m e lbs, soluções web de georeferenciamento no modelo SaaS em plataformas convergentes.

## Como se candidatar

Por favor envie um email para alexandre@getrak.com.br com seu CV anexado - enviar no assunto: Vaga developer Front-End.

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
