### ISSUE TITLE
[Remoto] Fullstack  Developer (Júnior) na HubLocal

### ISSUE THREAD

**Issue by mateu5-francisco** [frontendbr/vagas#6213]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/fullstack-junior-191730397?utm_origin=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Buscamos um programador <strong>Fullstack Developer Júnior </strong>(Node JS + React) para desenvolvimento de um produto web tipo SaaS, para gerenciamento de mapas, listas e diretórios na web.</p>
<p><strong>Atividades:</strong></p>
<ul>
<li>Desenvolvimento e manutenção de aplicações web;</li>
<li>Construção de API (REST/JSON);</li>
<li>Sustentar e desenvolver integrações;</li>
<li>Aplicação das melhores práticas de teste unitário;</li>
<li>Contribuir com desenho de arquitetura de soluções de software;</li>
<li>Sugerir novas tecnologias para melhoria contínua do produto;</li>
</ul>

## HubLocal: 
 <p>A HubLocal quer democratizar o acesso a tecnologias para o posicionamento local e atração de clientes pela internet para empresas.</p>
<p>A plataforma conecta clientes que pesquisam a todo tempo na internet por segmentos, produtos ou serviços, com empresas que tem tudo que eles precisam.&nbsp;</p><a href='https://coodesh.com/empresas/hublocal'>Veja mais no site</a>

 ## Habilidades: 
 - React.js 
- Node.js 
- PostgreSQL 
- Javascript 
- MySQL 
- NoSQL
## Local: 
 100% Remoto
## Requisitos: 
 - Conhecimento em react e node 
- Proatividade e atualização constante com novas tecnologias 
- Docker - Swagger - Nest JS - Amazon web service (S3, Cloundfont, Elastic, Beanstalk, Route 53, Amazon SES, IAM) 
- Conhecimentos em metodologias ágeis: SCRUM e AGILE
## Diferenciais: 
 - Inglês técnico
## Benefícios: 
 - Assistência médica e odontológica 
- Assistência psicológica para terapia 
- Creditas consignado 
- Auxílio academia 
- Auxílio alimentação através de cartão de benefícios corporativos. Cartão CAJU. 
- PCCR - Plano de cargos, carreira e remuneração 
- Rocketseat Academy
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack  Developer (Júnior) na HubLocal](https://coodesh.com/vagas/fullstack-junior-191730397?utm_origin=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
