### ISSUE TITLE
[Remoto] Senior Vue.js Developer na Bentley Systems

### ISSUE THREAD

**Issue by igasparetto** [frontendbr/vagas#6216]
## Nossa empresa

Bentley Systems (Nasdaq: BSY) is the infrastructure engineering software company. We provide innovative software to advance the world's infrastructure – sustaining both the global economy and environment. Our industry-leading software solutions are used by professionals, and organizations of every size, for the design, construction, and operations of roads and bridges, rail and transit, water and wastewater, public works and utilities, buildings and campuses, mining, and industrial facilities. Our offerings include MicroStation-based applications for modeling and simulation, ProjectWise for project delivery, AssetWise for asset and network performance, Seequent's leading geosciences software portfolio, and the iTwin platform for infrastructure digital twins. Bentley Systems employs more than 4,000 colleagues and generates annual revenues of more than $800 million in 172 countries.

www.bentley.com

## Descrição da vaga

Bentley Systems is looking for a Senior Vue.js Front-End Developer to become a valued member of our Software Development Team in Brazil. As a member of this team, you’ll have the opportunity to work with cutting-edge technologies that enable our users to solve mission critical problems, save time, and greatly reduce costs related to construction and infrastructure. You will be instrumental in building robust and reusable Vue.js components and integrate with backend APIs. In this exciting and challenging role, you will work with a global team of engineers to provide our user with excellent UI and a stable and scalable infrastructure. 

## Local

Remoto 

## Requisitos

**Obrigatórios:**

- BS in Computer Science, Software Engineering or closely related field or relevant experience
- Minimum 3-year software development experience
- Working experience of Git and Agile Development methodologies like SCRUM.
- Strong programming concepts and knowledge of JavaScript and Vue.js
- Strong conceptual and practical foundation of core Computer Science concepts including Algorithms, Data Structures, Web Browsers and Functional Programming.
- Knowledge of distributed version control system like git.
- Excellent knowledge of HTML and CSS
- Excellent problem-solving ability.
- Good verbal and written communication skills in English.
- Independent, Self-motivated and goal-orientation. Good verbal and written communication skills in English language 
- Ability to learn and adapt quickly to maximize productivity 
- Self-motivated person with the ability to work individually and as part of a team

**Desejáveis:**

- Experience with automated testing tools such as Jest and Selenium.
- Experience with any of the following frameworks or libraries:  
- VueJS
- Vuex
- Babel
- CSS/SCSS/SASS
- ES5-ES6
- TDD
- Jest
- HTML5
- CSS Bootstrap
- Experience in consumption of cloud services and REST Interfaces
- Experience with any of the following tools: VS Studio, VS Code, Chrome Dev tools, and Postman.

## Benefícios
- Plano de saúde
- Vale refeição

**Diferenciais:**
- Valuable experience on latest technologies and specializing in a technology that interests you
- Friendly, collaborative and supportive team environment.
- Being an integral part of a world-leading software company providing solutions for architecture, engineering and construction.
- The opportunity to work with a global and diverse international team.
- Opportunity to guide your own career path
- Challenging and interesting tasks at work every day, opportunity to work with highly skilled professionals on next generation software
- Work environment that suits concentration, as well as, teamwork
- Helpful colleagues to guide you along your journey

## Contratação
CLT

## Como se candidatar
Para see cadastrar, [siga este link](https://bit.ly/3IH1YQw)

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
