### ISSUE TITLE
[REMOTO] Senior Angular Developer na DB1

### ISSUE THREAD

**Issue by JhonatanMachado-DB1** [frontendbr/vagas#6217]
## Nossa empresa

Somos um grupo empresas de tecnologia, nascido no interior do Paraná, com 20 anos de experiência em desenvolvimento de software voltado para soluções de grandes empresas. Atuamos em diversas frentes de mercado: com produtos (ANYMARKET, CONSIGNET, EIVE) e também com serviços e projetos personalizados através da nossa Fábrica de Software - DB1 Global Software . 

Somos mais de 700 colaboradores em todo o Brasil e até na Argentina, com escritório em Maringá/PR, Campo Grande/MS e Presidente Prudente/SP e atuação remota (home office) desde 2017. Há 12 anos consecutivos entre as Melhores Empresas Para Trabalhar, segundo o GPTW. 

Somos movidos por desafios diários, sempre buscando uma forma de melhorar o que já existe e criar coisas novas com qualidade! Todos(as) aqui tem autonomia e voz para dar feedbacks, testar coisas novas e ser parte dessa mudança. Aqui aprendemos uns com os outros diariamente, com um forte senso de time.

## Descrição da vaga

Já pensou em codar usando Angular em um projeto internacioal e multicultural evoluindo uma aplicação usada no mundo todo por mais de 65 mil usuários?

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência com Angular (nível Senior); 
- Experiência com Clean Code; 
- Inglês avançado (o projeto é internacioanl e você terá contato direto com o cliente); 
- Habilidade de trabalhar independente e colaborar com outros em diferentes níveis técnicos; 
- Ser uma pessoa proativa; 

**Desejáveis:**
- Experiência com e-commerce;  
- Experiência com RESTful; 
- Bom entendimento das práticas agile  

## Benefícios

- Vale alimentação e/ou vale refeição;
- Plano de Saúde Unimed - Com mensalidade 100% paga pela DB1;
- Gympass;
- Home office como modelo de contratação. Atuamos com essa possibilidade desde 2017.
- Auxílio home office
- Horários flexíveis!;
- Plano odontológico (opcional);
- Seguro de Vida (opcional)

**Diferenciais:**
- Convênio com farmácia Droga Raia, com desconto para colaboradores;
- Para celebrar a vida de quem amamos, é possível sair um pouco mais cedo no dia do aniversário de cônjuge e filhos! :);
- Uma trilha de carreira com Plano de Desenvolvimento Individual (PDI) e feedbacks constantes para te ajudar na sua evolução profissional;
- Aqui você terá a oportunidade de aprender coisas novas - seja no dia-a-dia, em um Programa de Mentoria ou em um desafio do Mestre dos Códigos;
- Comitês para você participar e contribuir com as melhorias dos processos do Grupo DB1 ou contribuir com a comunidade: Comitês de Boas Práticas de Gestão de Pessoas (CBPGP), Comitê técnico, Comitê de Responsabilidade e Desenvolvimento Socioambiental (CORDS)

## Contratação

CLT

## Como se candidatar

Clique [aqui](https://vagasdb1.hire.trakstar.com/jobs/fk0szew?referred_by=415114)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: talentos@db1.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
