### ISSUE TITLE
[Juatuba/MG] Front-End VueJS Developer na Palácio dos Leilões

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#6218]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-front-end-vuejs-232123499?utm_origin=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Buscamos pessoas desenvolvedoras frontend vue.js.&nbsp;</p>

## Palácio dos Leilões: 
 <p>O Palácio dos Leilões exerce uma das maiores atividades leiloeiras da América Latina, com atuações em todo o Brasil.</p>
<p>Atuando no ramo desde 1.951, o Palácio dos Leilões atualmente dispõe de uma equipe de aproximadamente 250 (duzentos e cinquenta) funcionários, todos altamente especializados, com treinamentos periódicos, sempre prontos para atender com eficiência tanto os seus Comitentes (empresas públicas e privadas, instituições financeiras e seguradoras), como os Arrematantes dos bens.</p><a href='https://coodesh.com/empresas/palacio-dos-leiloes'>Veja mais no site</a>

 ## Habilidades: 
 - Javascript 
- API 
- Vue.js 
- Bootstrap 
- Rest e Restful APIs 
- Docker 
- Automação de Testes 
- CSS 
- CSS 3 
- HTML 5
## Local: 
 Juatuba/MG
## Requisitos: 
 - Construir Front-end VueJS consumindo API REST. 
- Diagramar fluxo de navegação e rotas.  
- Descrever os componentes criados.  
- Experiência em Javascript. 
- Experiência com Vue.js. 
## Diferenciais: 
 - Experiência com Bootstrap;  
- Conhecimentos de consumo e escrita de serviços (REST);  
- CSS e HTML para construção de sites leves e responsivos para desktop e mobile;  
- Conhecimento de escrita de testes automatizados;  
- Experiência com Docker;
## Benefícios: 
 - Assistência Médica / Medicina em grupo 
- Assistência Odontológica 
- Tíquete Refeição 
- Tíquete Alimentação 
- Transporte Fornecido pela empresa 
- Vale Transporte
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Front-End VueJS Developer na Palácio dos Leilões](https://coodesh.com/vagas/desenvolvedor-front-end-vuejs-232123499?utm_origin=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Regime
CLT
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
