### ISSUE TITLE
[Santa Barbara D'Oeste] Front-End Developer na Acruxx

### ISSUE THREAD

**Issue by santoja** [frontendbr/vagas#622]
## Descrição da vaga
- Criar aplicativos front-end de web; 
- Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas; 
- Participar do processo criativo e auxiliar na construção dos sistemas; 
- Nos deixar impressionados com sua capacidade criativa.

## Local

Remoto ou Escritório, Santa Barbara D'Oeste

## Benefícios

- VA
- Reembolso de viagens caso seja remoto e venha para a empresa esporadicamente.
- No caso de home office, ou caso o profissional deseje trabalhar com seu proprio equipamento, há um reembolso mensal pelo uso.

#### Diferenciais

- Area de descanso
- Frutas no escritório
- Café expresso ou coado
- Chá
- Cachorro no ambiente de trabalho

## Requisitos

**Obrigatórios:**
- Experiência relevante em front-end 
- Bons conhecimento em JavaScript/CSS frameworks 
- Boa experiência em HTML5/CSS e na construção de websites responsivos/adaptáveis para mobile 

**Desejáveis:**
- Conhecimento em React.JS
- Conhecimento em Semantic-UI

**Diferenciais:**
- projetos opensource

## Contratação

CLT presencial ou remoto

## Como se candidatar

Por favor envie um email para kaue@acruxx.com.br com seu CV anexado - enviar no assunto: Vaga Front-End

**Comment by degaus** [comment]
Enviei @santoja :smiley:

**Comment by michelgefuni** [comment]
Enviado @santoja    =)

**Comment by danlaurent** [comment]
Enviado! @santoja :)

**Comment by Vitao18** [comment]
Sou Júnior e tenho experiência com React e com projetos Open Source. Posso enviar meu cv?

**Comment by jvgm** [comment]
Enviado mestre, sou de Americana sp @santoja  :)

**Comment by santoja** [comment]
@Vitao18 Pode sim =)

**Comment by paulitolinhares** [comment]
Enviado @santoja!

**Comment by felipetrova** [comment]
Enviado @santoja 😃 !
