### ISSUE TITLE
[Remoto] Desenvolvedor Full Stack Pleno

### ISSUE THREAD

**Issue by MundoJix** [frontendbr/vagas#6224]
A pessoa contratada trabalhará como PJ (Pessoa Jurídica), com uma remuneração de até R$6.000,00 (mas estamos dispostos a negociar um valor para esta vaga), desenvolvendo novos projetos e fazendo a manutenção daqueles que foram entregues.

Para concorrer à vaga, a pessoa deverá:

- Experiência de nível com NodeJS, React, PostgreSQL e MongoDB.

Será um diferencial ter conhecimento na utilização de Docker, GitFlow, Adonis JS, Express, TDD  e/ou DevOps.

***Precisamos de pessoas que tenham mais vivência no Front que em Back.**

Inscreva-se através do link: https://forms.gle/jo5VPvgDBLSSJ7hK9

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
