### ISSUE TITLE
[Remoto] Dev React ou Fullstack na marvin.

### ISSUE THREAD

**Issue by marcos-marvin-com-vc** [frontendbr/vagas#6226]
## Nossa empresa

A marvin. é uma fintech super recente. Começamos a construção em março/2021 e entramos em produção em junho/2021. Temos o foco de ajudar os empreendedores a destravarem seus pagamentos, criando um novo método de pagamento para tentar melhorar as taxas do mercado de cartões.

Tivemos uma rodada seed muito legal, e temos com a gente a Mauá Capital e a Canary, mesmo fundo que investe na Alice, Buser, Loft, Caju e outras empresas bacanas. Dá uma olhadinha nos nossos aportes [da Mauá](https://exame.com/exame-in/marvin-fintech-fundada-em-marco-e-avaliada-em-r-65-mi-em-aporte-da-maua/) e [da Canary](https://exame.com/exame-in/marvin-fintech-recebiveis-canary-cielo/) :)

## Descrição da vaga

Estamos querendo crescer mais o time para engatar mais nosso momento de crescimento. Estamos buscando pessoas de nível Pleno, Sênior ou Especialista. Contratação CLT ou PJ (a negociar). Hoje, a engenharia sênior toda é PJ, então não temos ainda limites de CLT, mas a vaga PJ deve ser entre 15 e 20K.

Falando da nossa stack, usamos ReactJS com Typescript. O foco desta vaga é para desenvolvedores front-end, mas full stacks são bem vindos também!

Acabamos de criar uma lib que será nosso design system no futuro e, com isso, estamos migrando de SASS para Styled Components. Fora isso, no front-end também temos:

- Zustand para guardar estado
- Axios para requisições

## Local

Full Remoto ou Escritório, São Paulo - Itaim Bibi. Temos alguns eventos no escritório e gostamos de convidar a todos nesses dias, mas a presença não é obrigatória.

## Requisitos

**Obrigatórios:**
- Typescript: queremos alguém que, não só saiba usar, como também entenda bem de Generics e já tenha usado TS com Styled Components.
- ReactJS: usamos hooks em tudo e também nos preocupamos muito com re-renders.
- Testes: seja Cypress, Jest ou o que for, precisa saber testar os componentes que desenvolve.
- Auto-aprendizagem: queremos alguém que aprenda muito por conta própria e vá atrás. A gente adora ensinar e divulgar conhecimento e por isso queremos gente, como nós, que também traz coisas novas!
- Gostar de empreender: somos uma empresa muito nova. Temos muito o que fazer e muita coisa a definir. Você precisa gostar de entender e resolver problemas e deve conviver bem com cenários pouco definidos e ambíguos. Você terá muita gente pra discutir e questionar para podermos chegar do outro lado, mas esperamos muita interação da sua parte também!

## Benefícios

- 21 dias úteis de folga remunerada por ano
- Auxílio saúde
- VR de R$ ~30/dia
- Temos um programa de Stock Options em estruturação. Todas as posições sêniores são elegíveis para entrar no programa. Depende de você :)

**Diferenciais:**
- Flexibilidade de horário total: oficialmente, começamos nosso dia às 10h30 com a Daily, mas fazemos pausas ao longo do dia e trabalhamos como quisermos. Tem gente que resolve problemas pessoais no meio da tarde e fica até mais a noite trabalhando. Não temos problema quanto a isso. Quem quiser folgar um dia na semana e compensar no fim de semana, sem problemas. Nosso foco é a entrega. Como trabalhamos com sprints de duas semanas, combinamos as entregas no começo da sprint e, quando vemos que não podemos entregar, negociamos novas datas de entregas.
- Time altamente engajado: todo mundo fala o que pensa e contribui o melhor possível para construção da tecnologia. Ninguém tem mais voz que ninguém. Ao mesmo tempo, a equipe inteira é muito disponível, possibilitando uma interação e aprendizagem excelente!
- Qualidade levada a sério: seguimos nosso processo de desenvolvimento a risca. Se o código não passou na revisão por critérios de qualidade sério, no mínimo, fazemos um card no nosso board do Azure DevOps para refatorar depois. Nós não deixamos débitos técnicos para trás e sempre puxamos tarefas desse tipo para resolver.
- 100% remoto mesmo.

## Contratação

CLT ou PJ a combinar

## Como se candidatar

Envie um email para [oportunidades@marvin.com.vc](mailto:oportunidades@marvin.com.vc) com seu CV anexado. Pode ser LinkedIn. Se tiver algum outro portfólio, como um site ou Github, pode enviar no corpo da mensagem também!

Envie com assunto: [Github-Frontend-BR] Vaga Dev React

## Tempo médio de feedbacks

Nosso processo são 4 ou 5 conversas:
1. Conversa com nosso RH para que você conheça a gente melhor
1. Entrevista técnica: para devs só react, é uma conversa só que vamos perguntar e avaliar seu conhecimento em React e Typescript. No caso de dev full stack, temos duas conversas, para avaliar profundidade no backend também.
1. Entrevista de cultura
1. Conversa com nossos fundadores

No máximo, até o final da semana seguinte damos uma resposta do processo. Caso tenha demora, você pode entrar em contato diretamente com seu entrevistador. O e-mail sempre vai nos nossos invites :)

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by RafaPalau** [comment]
Nossa, uma vaga assim que eu queria. :heart_eyes:
Quem sabe daqui uns anos?! 
Só faltou GraphQL pra Stack perfeita.  TS :blue_heart:
