### ISSUE TITLE
[Lisboa] Front-end Engineer Senior na Zahir

### ISSUE THREAD

**Issue by rafaelritacarvalho** [frontendbr/vagas#6227]
**Vaga 100% Home Office para ganhar em Euro.**

Temos vagas presenciais e remotas você escolhe.

Sendo que presencial temos mais benefícios.

Procuramos um Engenheiro de Front-End Sênior, para trabalhar remotamente em um ambiente muito amigável e energético e fazer parte de uma equipe incrível. Se você adora aprender, compartilhar conhecimento e se preocupa em criar um impacto real em cada recurso que oferece, usando as últimas tecnologias e se divertindo fazendo isso, esta é uma oportunidade que você não pode perder.

O que você vai fazer

Criar, construir, melhorar e otimizar nossas aplicações web, implementando novas práticas de integração e entrega contínuas.
Crie recursos voltados para o cliente que aumentarão a receita de vendas e criarão ótimas experiências para nossos viajantes.
Garanta a qualidade de nossos produtos e trabalhe junto com nossa equipe de produtos para estabelecer soluções escaláveis.
Trabalhe em uma equipe que apoia o seu crescimento individual, proporcionando-lhe tarefas desafiadoras e a liberdade de aproveitar novas oportunidades.

RQUISITOS OBRIGATÒRIO 

Quem é você

Mais de 6 anos de trabalho de desenvolvimento de produtos.
Conhecimento sólido da arquitetura de aplicativos da web e todas as suas camadas.
Estruturas de trabalho experientes, como **Node.js**, Typescript, Javascript, **Vue.js**, componentes e outras estruturas semelhantes.
Desfrute da construção de produtos e codificação.
Conhecedor da arquitetura REST API.
Reporte-se diretamente ao nosso Chefe de Engenharia e se comprometa com o aprendizado e o aprimoramento constantes.
**Fluente em inglês.**
Experiência em trabalhar com metodologias Scrum ou Kanban é uma vantagem;
Conhecimento em melhorias de velocidade, Google Web Core Vitals, SEO e ferramentas analíticas é uma vantagem.

Contratação em PJ 
100% Home Office 
Ganhar em Euro.

E-mail para contato: zahir.headhunter@gmail.com
WhatsApp: (92) 98134-0709

**Comment by rafaelritacarvalho** [comment]
Ainda no aguardo de candidatos para essa incrível oportunidade.
temos algumas vagas disponíveis ainda.

Tanto presenciais como remota em Front-end ou Full-stack.

Todas para trabalhar em uma empresa de Portugal e receber em EURO.

**Comment by regyeduardo** [comment]
Esse inglês fluente aí é uma exigência pouquíssima abrangente

**Comment by rafaelritacarvalho** [comment]
Cara, o suficiente para  ler, escrever e conseguir desenrolar uma entrevista em inglês

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
