### ISSUE TITLE
[Lisbon or Porto/Portugal] Frontend Developer @Integer Consulting

### ISSUE THREAD

**Issue by brunoalexandrecarvalho** [frontendbr/vagas#6228]
# Integer Consulting
Integer is a Portuguese consulting company specialized in Technology and Information Systems. Our core business is IT outsourcing services, software, nearshore projects, and tailor made solutions. We are partners with the main technology players worldwide and we work with national and multinational companies from several industries. Most of the projects we participate are in Portugal, Brazil, and throughout Europe. What set us apart is the experience of our team and our tech talent.
Are you looking for new opportunities in the IT field? 👀 We have news for you!

## Requirements:
- Graduated in Information Systems or related field;
- 4+ years of professional experience in software development;
- Experience with Angular and/or React;
- Experience working in Agile teams;
- Knowledge in JavaScript, Typescript, HTML & CSS;
- Fluency in English (mandatory);

If you have the desired amazINg tech talent and want to be part of the INTEGER team, respond to this ad with your updated CV to bruno.carvalho@integer.pt.

To learn more about how we protect your privacy, please see our Policy at www.integerconsulting.pt

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
