### ISSUE TITLE
[Nova Lima/MG] Front-End Developer

### ISSUE THREAD

**Issue by rhcontamobi** [frontendbr/vagas#623]
## Descrição da vaga

•    Implementação e manutenções front-end de websites;
•    Garantir a estabilidade e a performance de sites em Wordpress;
•    Atuar no desenvolvimento dos produtos da empresa.

## Local

Escritório em Nova Lima/MG (próximo ao BH Shopping)

## Benefícios

•	VT;
•	Estacionamento;
•	Vale Refeição ou Alimentação;
•	Plano de Saúde;
•	Plano Odontológico;
•	Seguro de Vida. 

## Requisitos

Conhecimentos
•	Wordpress avançado;
•	PHP para Wordpress;
•	CSS, HTML5 e Javascript;
•	SASS / Compass;
•	Bootstrap ou outra solução responsiva;
•	Gulp / Grunt;
•	Controle de versão GIT e desenvolvimento em ambiente Linux;

Diferenciais:
•	React Native;
•	Ionic;
•	Vue.js;
•	Elaboração de layouts de aplicações web e mobile;
•	Conhecimento de usabilidade (UI) e experiência do usuário (UX);
•	Formação na área de Tecnologia da Informação, preferencialmente em Desenvolvimento de Software.

## Contratação

CLT Efetivo

## Nossa empresa
A conta.MOBI é uma Startup do ramo financeiro que fornece uma Conta Digital, dentre outros serviços, para quem é Microempreendedor Individual (MEI).

## Como se candidatar

Interessados enviar currículo para: rh@conta.mobi com o assunto – Dev Front End

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by rhcontamobi** [comment]
Olá Felipe, sim! 

 

DESENVOLVEDOR FRONT END 

Responsabilidades:

*	Confeccionar o novo site da empresa e realizar as manutenções;
*	Elaboração de layouts de aplicações web;
*	Atuar no desenvolvimento dos produtos da empresa.

 

Conhecimentos

*	Wordpress avançado;
*	PHP para Wordpress;
*	CSS, HTML5 e Javascript;
*	SASS / Compass;
*	Bootstrap ou outra solução responsiva;
*	Gulp / Grunt;
*	Controle de versão GIT e desenvolvimento em ambiente Linux;

 

Diferenciais:

*	React Native;
*	Ionic;
*	Vue.js;
*	Elaboração de layouts de aplicações web e mobile;
*	Conhecimento de usabilidade (UI) e experiência do usuário (UX);
*	Formação na área de Tecnologia da Informação, preferencialmente em Desenvolvimento de Software.

 

Salário: a combinar

Benefícios: 

*	VT;
*	Estacionamento;
*	Vale Refeição ou Alimentação;
*	Plano de Saúde;
*	Plano Odontológico;
*	Seguro de Vida. 

 

Interessados enviar currículo para: rh@conta.mobi <mailto:rh@conta.mobi> 

 

Qualquer dúvida estou à disposição!

 

Atenciosamente;

 




 

Paula Valle
Analista de Recursos Humanos

Tel.: (31) 3972-0105 

 

 

De: Felipe Fialho [mailto:notifications@github.com] 
Enviada em: terça-feira, 23 de janeiro de 2018 14:27
Para: frontendbr/vagas <vagas@noreply.github.com>
Cc: RH da conta.MOBI <paula.valle@conta.mobi>; Author <author@noreply.github.com>
Assunto: Re: [frontendbr/vagas] [Nova Lima/MG] Front-End Developer (#623)

 

Aberto ainda?

**Comment by marimeireles** [comment]
Boa tarde,
Sou de Belo Horizonte, mas, ainda estudo o que torna inviável pra mim estar na empresa todos os dias.
Há interesse em contratação semi presencial?
Sou júnior.

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
