### ISSUE TITLE
[Porto Alegre] Dev Angular na DBServer

### ISSUE THREAD

**Issue by PessoasDBServer** [frontendbr/vagas#6230]
## O que vamos construir juntos?

Nosso time é preocupado em propor as melhores soluções baseado em excelência técnica, pensando em alternativas que agreguem valor, com mindset ágil e cultura de colaboração. Nós respeitamos a diversidade e acreditamos que times diversos contribuem para construir ideias mais inovadoras.

## Nos ajude a desenhar a solução!

Se você gosta de trabalhar com qualidade, aprecia muito desafios, curte implementar soluções baseadas em boas práticas e topa trabalhar em times que respeitam quem você é e as suas opiniões, você está MUITO perto de integrar nosso time DB. Esse projeto você atuará em um cliente que conecta empresas e pessoas a uma mobilidade mais inteligente, com o propósito de valorizar o tempo para aproveitar mais e melhor a vida.

## Local
Porto Alegre.

## Requisitos para se candidatar a vaga:

- Experiência com Angular;
- Experiência com HTML5, CSS, SASS, JavaScript, Responsive Design.;
- Experiência com Testes unitários e integração;
- Conhecimentos em metodologias ágeis.

**Conheça também nossas vagas em: https://jobs.kenoby.com/dbserver**

## A DBServer

Somos uma softwarehouse que constrói entregas sob medida. Há 28 anos trabalhamos com foco nas pessoas, guiados por nossos valores, crescendo lado a lado com nossos colaboradores. Nosso lema é fazer a coisa certa do jeito certo através do design e do build.

Nos últimos anos, iniciamos uma caminhada em direção a diversidade e a inclusão e após o lançamento do nosso Marco Ético temos agora um norteador dos princípios que irão trilhar a nossa trajetória.

Estamos orgulhosos de promover um ambiente de trabalho livre de discriminação. Acreditamos que a diversidade de experiências, perspectivas e histórico transforma nosso ambiente de trabalho. Estamos empenhados a construir esse legado com a sua parceria! 

**Conheça nosso Marco ético: http://www.dbserver.com.br/marcoetico/**

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
