### ISSUE TITLE
[Remoto] Front-end Developer Jr na Yapoli

### ISSUE THREAD

**Issue by felipefrancesco-yapoli** [frontendbr/vagas#6237]
## Nossa empresa

A Yapoli é uma startup de tecnologia baseada em São Paulo criada para transformar a gestão de ativos digitais no mundo corporativo em escala mundial com visão focada na indústria 4.0. Vem fazer parte dessa transformação com a gente. Estamos em franco crescimento e em busca de novos integrantes para levarmos a outro patamar tecnológico.

## Descrição da vaga

Yapoli está em busca de um desenvolvedor frontend.

Você irá integrar a nossa equipe de produtos para evolução de nossa solução para gestão e processamento de arquivos digitais.

Você irá:
- Definir e desenvolver nossas interfaces junto com a equipe e especialista UI/UX
- Fazer peer-review junto com a equipe
- Contribuir na evolução da qualidade
- Integrar com a evolução do nosso produto e de nossa equipe Scrum

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Algum conhecimento e/ou experiência em desenvolvimento com React.JS (básico de manipulação do DOM, CSS para layout responsivo (SASS) e consumo de APIs)
- GIT

**Desejáveis:**
- Conhecimento de testes de unidade
- Conhecimentos e experiência em PHP ou Node.JS

## Benefícios

**Diferenciais:**
- Férias e 13o proporcionais
- Ajuda de custo para a infraestrutura e equipamentos
- Gympass
- 
## Contratação

PJ a combinar

## Como se candidatar

Interessados enviar currículo com pretensão salarial para felipe.francesco@yapoli.com com assunto: #Frontend - JR#

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: adalberto@yapoli.com

## Labels

- frontend
- react

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior

**Comment by Antoni0Carlos** [comment]
Meu nome é Antônio Carlos dos Santos Barbosa, sou  apaixonado por inovação e tecnologia, quanto maior o Desafio maior é minha vontade de Participar do Time.

Tenho experiência com desenvolvimento Web. 
Meu objetivo aplicar meus estudos em Análise e Desenvolvimento de Sistemas no desenvolvimento de soluções críticas.
Desenvolver minha carreira sob a supervisão e estímulo de uma empresa comprometida com inovação.

Amo trabalhar em equipe, sou comunicativo, sou pró-ativo  e  gosto de aprender coisas novas e ensinar para meus amigos coisas que aprendi.

**Comment by marcell0lopes** [comment]
Currículo enviado! :)
