### ISSUE TITLE
[Curitiba] Desenvolvedor Front-End (Angular 2) PL [CINQ Technologies]

### ISSUE THREAD

**Issue by WagnerJarsceski** [frontendbr/vagas#624]
**Descrição da vaga**

- [ ] O profissional vai atuar em projeto internacional, junto com UI/UX Designer para definir, validar e implementar uma nova aplicação WEB. 

**Local**

- [ ] Curitiba - PR

**Benefícios**

- [ ] Vale Alimentação, Vale Refeição, Plano Médico Unimed, Plano Odontológico DentalUni, Seguro de Vida, Previdência privada e auxílio estudo.

**Requisitos**

_Obrigatórios:_

- [ ] Experiência com CSS, HTML5, Angular 2 ou posterior.

_Desejáveis:_

- [ ] Conhecimento em Angular 4

**Contratação**

- [ ] CLT presencial ou PJ

**Como se candidatar**

Por favor envie um email para jobs@cinq.com.br com seu CV anexado - enviar no assunto: Desenvolvedor Front-End (Angular 2) PL

**Comment by LFeh** [comment]
Aberto ainda?
