### ISSUE TITLE
[Remoto] Frontend Vue.js Developer na cuidar.me

### ISSUE THREAD

**Issue by mateu5-francisco** [frontendbr/vagas#6240]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-vuejs-develope-140311159?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A  <strong>Cuidar.me</strong> está buscando <strong><em><ins>Frontend Developer</ins></em></strong>, para compor seu time!</p>
<p>Somos uma Operadora de Saúde (Plano de Saúde) Digital que oferece planos variados na Grande SP e em algumas cidades próximas. Nosso foco está no acesso à saúde, então nossa operação é enxuta e utilizamos tecnologia para reduzir custos operacionais bem como para realizar um acompanhamento de saúde mais eficiente dos nossos clientes, o que nos permite oferecer preços baixos com alta qualidade - o que você pode confirmar por nossa rede de hospitais parceiros.</p>
<p>Não buscamos um profissional que saiba tudo, queremos que você evolua junto com a gente!</p>

## cuidar.me: 
 <p>Operadora de Saúde digital que oferece Planos de Saúde modulares, simples de contratar e de usar!</p>
<p><strong>Digital</strong></p><a href='https://coodesh.com/empresas/cuidarme'>Veja mais no site</a>

 ## Habilidades: 
 - HTML 5 
- CSS 3 
- Javascript 
- Typescript 
- Vue.js 
- GIT
## Local: 
 100% Remoto
## Requisitos: 
 - Conhecimentos ou experiência em desenvolvimento front-end usando Vue.js 
- Habituado com Git 
- Habituado com trabalho remoto, times ágeis e scrum 
- Fluente em HTML5 e CSS3 
- Conhecimentos ou experiências em trabalhar com Typescript ou Javascript
## Diferenciais: 
 - Conhecimentos em VueX e Nust
## Benefícios: 
 - 100% remoto 
- Plano de saúde 
- Horários Flexíveis
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Vue.js Developer na cuidar.me](https://coodesh.com/vagas/frontend-vuejs-develope-140311159?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
