### ISSUE TITLE
[Remoto] Front-end Engineer Pleno na Aegro

### ISSUE THREAD

**Issue by helenarmuller** [frontendbr/vagas#6241]
## Nossa empresa

O mundo agtech não para! 🚀
E a Aegro recebeu mais uma rodada de investimentos, novos desafios e frentes de negócio estão sendo construídos.

Para fazer parte disso, estamos procurando novos aegers para integrar o time que vai formar o primeiro unicórnio Agtech do Brasil. E ainda fazer tudo isso na melhor empresa para se trabalhar no Rio Grande do Sul e a 3ª a nível Brasil (reconhecida em 2020 pelo GPTW).

A área de Engenharia de Software tem várias missões para encarar esse desafio da construção do primeiro unicórnio, e para isso, estamos buscando uma pessoa Front-End Engineer apaixonada por tecnologia e movida a desafios.

Nossa stack é baseada principalmente em Java/Kotlin e Spring no backend, Angular no frontend, bancos de dados MongoDB, stack ELK para logs, Kubernetes e cloud AWS.

## Descrição da vaga

- Trabalhar junto com o time de produto e design para construir novas soluções e melhorar a experiência de usuário;
- Transformar protótipos criados no Figma em aplicações de alta fidelidade;
- Desenvolver aplicações web com uso intensivo de dados via APIs REST
- Participar das cerimônias de engenharia onde debatemos boas; práticas, arquiteturas, novas tecnologias e muito mais. 

## Local

Remoto 

## Requisitos

**Obrigatórios:**
- Tiver mínimo de 3 anos de experiência no desenvolvimento de aplicações web;
- Sólida experiência em JavaScript, HTML, CSS, Angular 2+ e AngularJS;
- Conhecimento em versionamento de código (Git);
- Prezar pela qualidade do código: clean code.

**Desejáveis:**

- Familiaridade com linux;

**Diferenciais:**

- Experiência em Metodologias Ágeis (Scrum);
- Conhecimento em ferramentas de desenvolvimento: Webpack, Lint, Angular CLI, Npm;
- Conhecimento em princípios de design de interação, UX/UI e Design System;
- Padrões de projeto e arquitetura - Design Patterns, Clean Architecture, SOLID;

## Benefícios

- Plano de Saúde Unimed Seguros
- Plano Odontológico Unimed Seguros
- VR ou VA
- Auxílio Home office
- Flexibilidade de Horário
- Enviamos os equipamentos necessários (notebook, tela, mouse, teclado..)

**Diferenciais:**

- Summer Hours
- Acesso a plataforma da Alura para cursos de atualização
- Oportunidade de realizar 8 horas de treinamento/cursos/capacitações no horário de trabalho por mês

## Contratação

CLT

## Como se candidatar

Neste [link](https://jobs.kenoby.com/aegro/job/front-end-engineer-pleno-remoto/61b908eb6a40d5441ba2945f?utm_source=website)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: helena.muller@aegro.com.br

#### Alocação

- Remoto

#### Regime

- CLT

#### Nível

- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
