### ISSUE TITLE
[REMOTO] Front-end Developer JÚNIOR na NAVITA

### ISSUE THREAD

**Issue by rayanmarcus** [frontendbr/vagas#6244]
## Local

Remoto/São Paulo

## Requisitos e Atribuições (APLIQUE A VAGA MESMO QUE NÃO ATENDA A TODOS OS REQUISITOS!)

- Participar dos planejamentos das Sprints, realizando a estimativa após o entendimento das funcionalidades;
- Construir as funcionalidades descritas nas tarefas/atividades;
- Construir telas amigáveis e responsivas a partir de especificação do U.X;
- Corrigir os bugs apontados pelos clientes ou pela equipe de qualidade;
- Realizar testes da funcionalidade criada, garantindo assim sua qualidade;
- Criar testes unitários das regras de negócios existentes garantindo assim a qualidade da entrega;
- Inserir os códigos criados no repositório de armazenamento de códigos fonte;
- Seguir os procedimentos internos na ferramenta de controle de projetos/chamados (Jira);
- Apoiar a equipe de qualidade na realização de testes quando necessário;
- Apoiar times de Sustentação e CS para saneamento de dúvidas, participando de chats de comunicação e reuniões, se necessário;
- Apoiar no incremento de informações em manuais técnicos, junto ao time de UX e PO;
- Elaborar prova de conceito (pesquisa de novas tecnologias);
- Criar códigos limpos e bem estruturados;
- Criar dados para medir a aplicação em ferramentas de Web Analytics;
- Manter-se atualizado às tecnologias emergentes;

## REQUISITOS E QUALIFICAÇÕES

_**Competências técnicas**_:

- Ensino superior/Cursando - em ciência/engenharia da computação, sistemas de informação ou afins;
- Conhecimento sobre arquitetura de microsserviços;
- Conhecimento e/ou experiência com Angular/VueJS +2, JavaScript e comunicação com WEB API’s REST;
- Conhecimento em estilização e conceitos modernos de UX/UI, como HTML, CSS, Bootstrap e responsividade de layout;
- Versionamento com Git/Bitbucket;
- Conhecimento de banco de dados relacional Postgres SQL / Sql Server;
- Consciência da necessidade de testes unitários e integração;
- Conhecimento de metodologias ágeis de desenvolvimento como Scrum, Kanban e XP;
- Conhecimento dos conceitos de Cloud Computing e Amazon Web Services, como ECS, EC2, ECR, ELB, S3;
- Conhecimento dos conceitos de aplicações em Cluster, Docker.

**_Diferenciais técnicos_**:

Experiência com NodeJS;
Ter atuado como desenvolvedor Fullstack ou back-end Java;
Certificação W3 CSS/JavaScript.

_**Perfil Comportamental:**_

Disciplinado e organizado;
Curioso, investigativo, persistente;
Facilidade de comunicação e criação de relacionamento;
Foco em resultado;
Responsabilidade (cumpre prazos e atividades).

## Benefícios

🏥 Assistência Médica Bradesco;
🦷 Assistência Odontológica Porto Seguro; 
🎒 Auxílio Creche; 
☕ Chá e café à vontade (presencial);
🥳 Day off (mês de aniversário);
🕒 Horário de trabalho flexível;
👗👕 No dress code;
📝 Parceria com Instituto FEPAF;
📈 Plano de Carreira Individual;
💰 PLR; 
👥 Programa de Indicação (novos colaboradores);
✨ Seguro de Vida;
🖥️ Trabalho Remoto e Equipamentos (fornecidos pela Navita);
📚 Trilha de Desenvolvimento/Capacitação (Alura Business);
🍝 Vale Refeição;
🚌 Vale Transporte; 

## Como se candidatar

🔗 Se inscreva [aqui](https://navita.gupy.io/job/eyJqb2JJZCI6MTM4MjI5OSwic291cmNlIjoiZ3VweV9wdWJsaWNfcGFnZSJ9?jobBoardSource=gupy_public_page)

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior

**Comment by rayanmarcus** [comment]
@felipefialho, não consegui remover as labels "pleno" e "sênior". Pode remover, por favor?
Obrigado!

**Comment by marcell0lopes** [comment]
Currículo enviado! :)

**Comment by AnaMickaelly** [comment]
boa noite! não estou conseguindo me candidatar!

**Comment by rayanmarcus** [comment]
> boa noite! não estou conseguindo me candidatar!


@AnaMickaelly me adiciona no LinkedIn e me chama lá, por favor.
https://www.linkedin.com/in/rayanmarcus

**Comment by AnaMickaelly** [comment]
Enviei pedido pra conectar lá no linkedin.

**Comment by rayanmarcus** [comment]
Não recebi aqui, Ana.
Talvez você clicou em "seguir" e não em "conectar".
O botão "conectar" do meu perfil se não me engano, tá ficando no botão
cinza "mais" depois do botão "seguir".


Em qua., 12 de jan. de 2022 às 11:30, Ana Mickaelly <
***@***.***> escreveu:

**Comment by AnaMickaelly** [comment]
certo, já está lá
