### ISSUE TITLE
[Remoto] Fullstack Javascript Developer na CTWLK

### ISSUE THREAD

**Issue by mateu5-francisco** [frontendbr/vagas#6248]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedora-front-end-remoto-174131447?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Catwalk é uma startup de A.I. para o varejo de moda que oferece soluções simples para melhores negócios. Nossos serviços são disponibilizados através de uma plataforma de serviços SaaS para nossos clientes por meio de serviços modulares, fáceis e intuitivos. Nossa A.I. é capaz de fazer combinações de roupas que chegam a um volume de 1 trilhão de resultados por ano, apresentar peças similares, sugerir combinações de acordo com cada pessoa e encantar os clientes com uma experiência completa.</p>
<p><strong>Atividades</strong></p>
<p>• Operar, manter e atualizar interfaces de exibição de dados em AngularJS;</p>
<p>• Propor melhorias contínuas para manter ou melhorar o SLA dos serviços, tempo de requisições, latência e consumo de memória das aplicações;</p>
<p>• Monitorar, rastrear e diagnosticar falhas de dados em repouso ou em trânsito, de maneira a otimizar painéis de visualização de dados, adaptando novas informações aos objetos existentes;</p>
<p>• Manter e atualizar uma arquitetura de escala, capaz de lidar com milhões de requisições por segundo, em ambiente com alto SLA;</p>
<p>• Poderá ter que manter e atualizar um conjunto de APIs estruturadas existentes, manipulando dados e uniformizando informações de forma padronizada e previsível;</p>
<p>• Se preocupar em manter e estruturar requisições de dados em um banco de dados com milhões de entradas, de forma ágil e segura, obedecendo políticas de acesso;</p>
<p>• Desenvolver um raciocínio lógico aguçado, para prever situações, agir sobre elas e propor alternativas viáveis e estruturadas respeitando processos, de modo a manter a integridade do sistema e sua escalabilidade;</p>
<p>• Tratar dados como números e matrizes ou mapas de informação, em algumas situações específicas e pré-determinadas;</p>
<p>• Pode ser solicitado a estruturar algoritmos prototipados dentro de uma interface, que possua vínculos entre APIs para exibição de dados em versões pré-operacionais, entendendo o impacto em uma determinada seção da plataforma.</p>

## CTWLK: 
 <p>Catwalk é uma startup de A.I. para o varejo de moda que oferece soluções simples para melhores negócios. Nossos serviços são disponibilizados através de uma plataforma de serviços SaaS para nossos clientes por meio de serviços modulares, fáceis e intuitivos. Nossa A.I. é capaz de fazer combinações de roupas que chegam a um volume de 1 trilhão de resultados por ano, apresentar peças similares, sugerir combinações de acordo com cada pessoa e encantar os clientes com uma experiência completa.</p>
</p>

 ## Habilidades: 
 - Node.js 
- Angular.js 
- API 
- Banco de dados não-relacionais (NoSQL) 
- HTML 5 
- CSS 3
## Local: 
 100% Remoto
## Requisitos: 
 - Domínio em RESTful API utilizando Node.js; 
- Domínio em algum framework JavaScript para aplicações Web, preferencialmente AngularJS;  
- Familiaridade com requisições de API com objetos estruturados, requisições, autenticações e manipulação de elementos básicos para atualização, manutenção ou edição de objetos que impactem o front-end;

## Benefícios: 
 - Vale-Refeição 
- Dia de folga no aniversário;
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack Javascript Developer na CTWLK](https://coodesh.com/vagas/desenvolvedora-front-end-remoto-174131447?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
