### ISSUE TITLE
[Remoto] front-end developer na aiqfome

### ISSUE THREAD

**Issue by monicapio** [frontendbr/vagas#6249]
## Nossa empresa ##

aiqfome
Somos a primeira e a maior plataforma de delivery online para restaurantes 100% brasileira, levando tecnologia e a melhor experiência em entrega pra todo o interior do Brasil!

Somos parte do Grupo Magazine Luiza, compartilhando o sonho de digitalizar todo o Brasil e trazer tecnologia pra todo mundo!

A gente se reinventa a todo momento e estamos revolucionando o mercado local de delivery, sem abrir mão de um valor inegociável: tratamos os outros como gostaríamos de ser tratados, criando soluções únicas e proporcionando a melhor experiência possível sempre, pra todo mundo envolvido!

Ah, e o mais importante: nos divertimos MUITO enquanto fazemos tudo isso!

Por isso, atenção: só contratamos pessoas legais 😉💜

## Descrição da vaga ##

Principal missão: Fazer parte do nosso time de magos do frontend capaz de tranformar códigos na melhor experiência de delivery que esse BR já viu. Ser um verdadeiro cientista em nosso laboratório, testando novas ideias constantemente, sem medo de errar! Unimos neurônios e memes diariamente para entregar um produto que amamos, sem deixar de compartilhar as últimas novidades do universo Dev e do zapzap.

**Coisas que você precisa fazer pra mandar muito bem aqui:**

- Participar de análises junto ao time, quanto as sugestões de melhorias dadas por fominhas, restaurantes, fomers e hunters;
- Contribuir com ideias e sugestões junto ao time de ui/ux;
- Construir novas telas com a nossa carinha, pensando em desempenho, experiência de usuário e design;
- Usar boas práticas de desenvolvimento para entregar software de qualidade;
- Contribuir com nosso design system;
- Pesquisar e se atualizar sempre sobre novas tecnologias.

**Requisitos**
**Antes de qualquer coisa, você precisa ser MUITO gente boa e teamplayer!**
**Mas também é importante que tenha:**

- Conhecimento em Javascript, CSS, React/Vue e Git;
- Experiência em construir e integrar páginas com dados vindos do backend;
- Transformar protótipos em lindas páginas funcionais;
- Proatividade para encontrar soluções, otimizações e novas ferramentas/libs;
- Costume de pesquisar e se atualizar sobre novas tecnologias e frameworks;
- Experiência com desenvolvimento front-end.

**Será um diferencial se:**

- Tiver experiência prática em construir aplicações com dados em real-time;
- Já ter trabalhado com frameworks como React ou Vue;
- Manjar de testes para front-end;
- Já tiver trabalhado com métodos ágeis como Scrum ou Kanban;
- Tiver experiência em usar ou desenvolver um design-system.

**Contratação**
- CLT

**Benefícios**

- Opção de trampo full remoto
- Bônus por metas atingidas
- Cupons mensais pra pedir no aiq
- Descontos em cursos
- App de saúde mental (terapia online)
- Plano odontológico
- Plano de saúde
- Vale alimentação
- Vale transporte
- Seguro de vida
- Dois monitores pra trabalho
- Cafézin expresso e moído na hora
- Uma cultura de autonomia e diversidade
- Não temos nenhum dress code
- E a chance de você crescer aqui dentro é imensa!

**Nível**
- Júnior
- Pleno

**Como se candidatar**
Se inscreva na vaga [aqui](https://aiqfome.gupy.io/jobs/1407132)

**Comment by nerdstarcode** [comment]
Olá! Vocês estariam com alguma vaga pra estagiário? Estou iniciando nesse caminho agora e não sei se estaria num nível Júnior, mas sou comprometido com minha aprendizagem e estou sempre disposto a ouvir e sou bem proativo também, garanto que não irão se arrepender caso tenham essa vaga 😁

**Comment by Yagasaki7K** [comment]
Vaga encerrada!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
