### ISSUE TITLE
[Joinville] Software Engineer - Front-End na Conta Azul

### ISSUE THREAD

**Issue by MartinaCarvalho** [frontendbr/vagas#625]
## Descrição da vaga

As a software engineer at ContaAzul you will work with big challenges of scalability caused by huge quantity of datas and fast growth number of users, in an environment highly fun and collaborative. We need someone that has a passion in solving complex problems.
A professional with strong skills in dataand algorithm structures,along with a technical fascination of how things work. A motivatedsoftware engineer willing to experience and risk, in order to make a difference within his area, who is not afraid of defending his ideas and accept changes, next to highly trained people and motivated to improve day by day.

RESPONSIBILITIES
Elegant system code that requires search, interactivity and curiosity;
Write automated test to ensure the quality of the developed solution;
Analyse and improve the efficiency, scalability and stability of systems resources.

## Local

Joinville / SC

## Benefícios

- Compatible salary, above the market average;
- Meal ticket;
- Financial Aid for extented education and graduate;
- Financial Aid for learning english;
- Affliliation with pharmacies;
- Full health plan and without a discount on your paycheck;
- Full dental plan and without a discount on your paycheck;
- Financial Aid for physical activities;
- Transportation Assistance.

#### Diferenciais

- A different work environment and innovative, with a culture that values people and the delivery of results;
- Autonomy and flexibility;
- Kitchen’s always stocked with unlimited snacks;
- A team that has our values in their DNA;
- Living in one of the best cities to live in Brazil;
- Access to books and other materials.

## Requisitos

**Obrigatórios:**
- Knowledge SOLID (object oriented design), Clean Code and Design Patterns and TDD;
- Experience with Front End architecture, usability, performance and testability;
- Experience with JavaScript technologies (AngularJS, Node.js, jQuery, etc);
- Experience with large-scale CSS, LESS and prototyping screens;
- Experience with large Single Page Apps using backend. Experience with JavaScript frameworks MV *;
- Experience with front-end automation tools like Grunt, Gulp or Webpack.

## Contratação

CLT a combinar

## Nossa empresa

A ContaAzul é uma empresa de tecnologia sediada em Santa Catarina que nasceu em 2011 no Vale do Silício. Nosso propósito é impulsionar o sucesso das pequenas empresas brasileiras. Hoje fazemos isso através de um software na nuvem que ajuda milhares de pequenos empresários na gestão de seus negócios. 

## Como se candidatar

Ficou interessado na vaga? Cadastre-se em https://jobs.lever.co/contaazul/d1858a6c-976f-4666-a2d6-16e5b692d8c3?=source=github 
Dúvidas ou comentários, podem contatar Martina Carvalho no e-mail: recrutamento@contaazul.com

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by raduq** [comment]
Vagas abertas ainda.

**Comment by MartinaCarvalho** [comment]
Sim!!

2018-02-02 14:39 GMT+01:00 Raduan Silva dos Santos <notifications@github.com

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
