### ISSUE TITLE
[Remoto] Front-end Developer na Goomer

### ISSUE THREAD

**Issue by KaDaGoomer** [frontendbr/vagas#6250]
## Nossa empresa

A Goomer nasceu em 2014 com o propósito de ser parte da evolução dos restaurantes, encontrando a perfeita harmonia entre a tecnologia e o ser humano.

Para isso, desenvolvemos diversos produtos que servem de motor de crescimento próprio para ajudar os restaurantes a proporcionarem a melhor experiência de atendimento. Nossos produtos estão presentes em várias grandes marcas pelo país todo que confiam em nossa tecnologia para atender o que eles possuem de mais precioso: pessoas clientes.

Você já deve imaginar, mas temos um baita orgulho de ver nosso produto na mão de milhões de pessoas mensalmente. Como time de Engenharia, é um orgulho quando alguém da família, pessoas amigas, parceiras de trabalho ou até mesmo uma pessoa desconhecida usa e compartilha a experiência incrível dos nossos produtos. Já pensou ter sua assinatura nestes produtos?

Procuramos pessoas que amam trabalhar nesse mundo e que não tenham medo de enfrentar os desafios de escala que uma startup de alto crescimento demanda, que se identifique com nosso propósito e se encante com o desafio e a responsabilidade que a líder de autoatendimento em restaurantes no Brasil tem para oferecer: revolucionar o mercado de foodservice. 💙
Quer fazer parte do nosso time dos sonhos? Vem pra Goomer! 💙

## Descrição da vaga

- Desenvolver aplicações web integradas ao backend com qualidade, implementando códigos testáveis e escaláveis;
- Analisar e manter softwares já existentes na Goomer;
- Realizar definições e análises técnicas;
- Detectar e solucionar problemas do seu time;
- Ser responsável por todo o ciclo de desenvolvimento de software - design, desenvolvimento, testes e deploy em produção;
- Ajudar o time com boas práticas de desenvolvimento, padrões de projeto, testes automatizados e revisão de código.

## Local

Remoto, [São Paulo], [Sorocaba], [Jardim America]

## Requisitos

**Obrigatórios:**
- Que você saiba trabalhar em equipe e tenha senso de responsabilidade;
- Que você já tenha programado utilizando React, Redux, Redux-saga, Styled-components;
- Ter conhecimentos com testes unitários (React Testing Library ou Jest);
- Que você tenha boas noções de UX, Design e UI;
- Ter conhecimentos com versionamentos de projetos utilizando git.

**Diferenciais:**
- Ter paixão pelo desenvolvimento, mas também por entender mais sobre o negócio;
- Proatividade para solucionar problemas e propor melhorias;
- Experiência com projetos Server-side Rendering (SSR) utilizando NextJs;
- Experiência com automação de testes com Cypress.

## Benefícios

- Plano de Saúde Nacional sem custo para você!
- Plano Odontológico da MetLife sem custo para você!
- Seguro de vida
- VR da Flash de R$ 550,00 por mês
- Bem-estar Goomer de R$ 120,00 por mês para você investir no seu bem!
- Licença Maternidade de 6 meses
- Licença Paternidade de 2 meses
- Parceria com academias (Gympass)
- Day off de aniversário
- Goomer anywhere (trabalhe de onde quiser!)

## Como se candidatar

Candidaturas através do Link: https://goomer.gupy.io/jobs/1404664

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
