### ISSUE TITLE
[REMOTO] React.js Front-end Developer na Dataseed

### ISSUE THREAD

**Issue by alvarogomes** [frontendbr/vagas#6251]
VAGA

Desenvolvedor react para manutenção em aplicação react, class components

- freelance
- inicio imediato
- com possibilidade de integrar o time para mais projetos.

enviar github e valor/hora e disponibilidade.

Contratação

Freelance por hora.
Nível
Pleno ou Senior

E-mail para se candidatar: alvaro.brito@dataseed.de

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
