### ISSUE TITLE
[Remote] Front-end Developer na Passport 🇧🇷

### ISSUE THREAD

**Issue by abrilb14** [frontendbr/vagas#6252]
## Our company

Passport is an US-based technology financial software company serving Latam. We also have a team in Australia, the United Kingdom, Macedonia, Mexico, and the United States. We are building the future of Open Banking. Our goals are to eat ice cream, drink tea and/or beer, enjoy awesome take-out food, delight customers, code amazing scalable software, go skiing, hiking and play golf (or learn how to play golf). Order of priorities to be determined after you accept the offer to work with us.

## Project Summary 

Working with an engineering team, product team and eventually a design team to design and build front-end web services for a fresh fintech company. Duties will include designing and implementing dashboards for customers, internal developers and users of the overall system. A focus on localization, internationalization and the upcoming accessibility rules for websites will be required. Should be highly experienced with typescript and javascript frameworks.

## Job Description
Designing and implementing dashboards and systems to enable B2B integrations for customers (fintechs and banks), internal developers and final users of the overall system. Focus on localization, internationalization and the upcoming accessibility rules for websites will be required, will use javascript and typescript frameworks on a daily basis, focus on development and end to end testing of products

## Local
This is a 100% remote, full-time, long-term position. 

## What we a looking for:
-7 years of experience with Javascript, typescript and python, preferable experience using databases like PostGres, experience using frameworks like vue.js, node.js, angular.js, experience using UI frameworks like backbone, JQuery, react, vue, angular, experience using agile as a methodology, experience using end to end testing tools.

**Programming languages:**

-Javascript, Typescript and Python (7 years)

**Frameworks:**

-Vue.js, Angular,js, Node.js, Backbone, JQuery (7 years)

**Additional qualifications: **
-Knowledge of Docker, Kubernetes and AWS is a plus
-Databases Postgres (preferably)

**What is in it for you:**
-Be part of a highly experienced team where responsibility and authority is shared equally amongst colleagues and help create our company culture
-A culture in which we don’t criticize failure but ensure we learn from our mistakes
-An Agile environment where your ideas are welcome
-The possibility to grow and experience different projects in different countries and regions
-Possibility to work from anywhere
-Ongoing Training & Mentoring
-The possibility to travel (when we are allowed)

**Hiring model and $**
-Full time in local currency 
-Law benefits
-Stock options

**Languages **
-Portuguese (required)
-Spanish (required)
-English (nice to have)

**How to apply**
Por favor envie um email para  abril@getpassport.co com seu CV anexado or Linkedin - enviar no assunto: Vaga NodeJS

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- Full-time 
- Stock options

#### Nível
- Sênior
- Especialista

**Comment by Adonis11300522** [comment]
Hello. Abril Benhumea. Happy New Year.
My name is Alex Dean based in Toronto. 
I am in Moscow now.
I have a goal to work as a remote frontend developer for a reputed tech company. 
My background in bachelor’s degree in Computer Science and bachelor’s degree in Business Administration  taught  me how to work with programming languages. 
Diplomas in Web Development and Web designing taught me how to work with React, TypeScript, JavaScript, PHP, Python and database. 
And I have rich experience dealing with AWS.
It would be great if I could help you on a remote opportunity!
Thanks

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
