### ISSUE TITLE
[Remoto] Front-end Developer Vue.js na Dietbox

### ISSUE THREAD

**Issue by educosta** [frontendbr/vagas#6253]
## Descrição da vaga

Trabalhar no site do Dietbox, envolvendo-se na concepção de novas funcionalidades, testando provas de conceitos, desenvolvendo novas funcionalidades e principalmente migrando nosso stack de tecnologias legadas.

Queremos e trabalhamos com as tecnologias mais atuais possíveis, porém sempre teremos código legado para manter e evoluir, por isso é fundamental que você se sinta confortável com isso.

## Local

Remoto (Empresa de Porto Alegre / RS)

## Benefícios

VR (Cartão Flash, tanto VA quanto VR) – R$26,00 por dia;
50% da Unimed (Unipart) a Dietbox paga;
Salários competitivos;
Cultura que preza por individualizar cada pessoa, com foco no bem-estar e desenvolvimento profissional/pessoal;
Aqui trabalhamos com auto-gestão e flexibilidade, ou seja, você pode ir longe!
Cultura do Home Office;
Licença paternidade estendida;
Empresa com gestão moderna, horizontal e enxuta, que promove a oportunidade de participação ativa em todos os níveis organizacionais;
Ambiente informal, voltado para o bem-estar das pessoas;
Cultura do Feedback cada vez mais presente;

## Requisitos

**Obrigatórios:**
Tenha sede por conhecimento;
Tenha bons conhecimentos e habilidades em algoritmos e estruturas de dados;
Tenha domínio de engenharia de software, princípios, boas práticas e padrões de arquitetura;
Experiência com layouts responsivos;
Experiência com frameworks front-end (Bootstrap);
Experiência com pré-processadores CSS;
Experiência com frameworks reativos (preferencialmente Vue.js);
Familiaridade com Javascript ESNext (syntax, modules, promises, classes e etc.);
Experiência com sistemas de controle de versões (Git);

**Diferenciais:**
Conhecimento em .NET e Azure;
Conhecimento em Stylus;
Conhecimento em Pug;
Experiência com ferramentas de tooling ( Gulp é um diferencial );
Conhecimento em SEO;
Habilidade com ferramentas de design (preferencialmente Figma);

## Contratação

PJ a combinar.

## Nossa empresa

Startup líder no mercado de software de Nutrição do Brasil, em pleno crescimento e estamos em processo de expansão internacional. Nosso propósito é fortalecer e transformar o mercado do profissional de Nutrição através da tecnologia com foco em relacionamento, se mantendo como uma peça-chave para isso. Com um modelo de gestão moderna, horizontal e enxuta, buscamos valorizar ao máximo as pessoas.

## Como se candidatar

https://www.linkedin.com/jobs/view/2867169897

#### Alocação
- Remoto

#### Experiência
- Pleno
- Sênior

#### Regime
- CLT
- PJ

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
