### ISSUE TITLE
[UK REMOTE] Front-end Developer na EHAB.co

### ISSUE THREAD

**Issue by fmoura-ehab** [frontendbr/vagas#6254]
> Vaga Remota sempre!

## EHAB (https://ehab.co)

EHAB is a fast moving startup, founded in the UK but now working 100% remotely. We combine distributed ledger technology, parametric insurance and advanced weather modelling to help the construction industry tackle rising weather and climate risk. We're on a mission to re-write the way risk is dealt with in the construction industry and help build climate resiliency.

As an employer we will give you the opportunity to work on cutting edge tech, invite you to contribute to product, company strategy and, most importantly, we want you to develop personally and professionally as the team and company does.

## Descrição da vaga

We're looking for a Senior full-stack developer with solid experience in Typescript, JavaScript, React, Python experience, Google Stack (Firebase, Firestore, Functions), DevOps (Docker, servers configuration), knowledge of or experience in design and UI/UX is a huge bonus. 

More importantly, we're looking for someone who's comfortable navigating between multiple technologies, and open to working with whichever tool/framework/language is best suited to a given problem. Must also be comfortable with having a high level of autonomy and rapid problem solving.

As a company we want to empower people to live their best life, to be curious and to flourish. We don’t want to work you to the bone, but we also expect high performance to be the norm. We want to be as flexible as we can to enable your way of life, as the happier you are the the happier we are.

Ultimately we want to create an environment which is equal parts; fun, challenging, and supportive. We want to make a difference and cause a positive impact in the world, and we know we can't do that alone. We need a community of motivated and curious people to help us all get there.

## Local

Remoto

## Requisitos
**Obrigatórios**
- Highly concerned with user experience, not just with code quality

**Desejáveis:**
- Fluent in Typescript and JavaScript
- Expert knowledge of React
- Experience with Google Apps stack (Firebase, Firestore, Functions)

**Diferenciais:**
- Solid knowledge of DevOps (Docker, server configuration, etc.)
- Takes initiative
- Professional, versatile and comfortable with agile methodologies

## Benefícios

- Fully remote
- Flexible working
- Plenty of learning and career progression
- Stock options

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para filipe.moura+frontend@ehab.co com seu CV anexado - enviar no assunto: Vaga Front-end Developer na EHAB.co

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: filipe.moura+frontend@ehab.co

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
