### ISSUE TITLE
[Home Office] Front - End Developer Java Sênior na Foursys

### ISSUE THREAD

**Issue by ShirleySantosFoursys** [frontendbr/vagas#6258]
> Vaga Remota

A Foursys nasceu em 2000 com o propósito de revolucionar o mercado de TI e promover soluções inovadoras e perenes para o crescimento dos negócios de nossos clientes. Somos um time que pensa e respira o Lean Digital, que valoriza o comprometimento, a criatividade, a busca incessante por superar os limites e, principalmente, o trabalho em equipe. De nossos escritórios localizados no Brasil, EUA e Portugal atendemos grandes clientes nacionais e internacionais.

## Requisitos

Desenvolvedor Java - Sênior

Conhecimentos necessários:
✅ Linguagem de Programação: Java com Spring Boot;
✅ Conhecimento em:  SQL Server e MongoDB;
✅ Experiência com REST;
✅ Desenvolvimento de testes: unitário TDD / junit;
✅ Conhecimento de arquitetura Cloud (Azure), Clean Architecture
✅ Conhecimento em: Atlassian (Jira, Bitbucket, Confluence, Bamboo), Docker, Docker compose, kubernetes, Istio, Visual Studio Code, SonarQube, Jenkins, Soapui;
✅ Conhecimentos em Frameworks: Java 11 AFI, JUnit 5, Lombok, Maven, Cucumber, Postman, JWT.  

Responsabilidades:
✅ Codificar os programas conforme requisitos;
✅ Realizar testes unitários e/ou integrados dos programas; 
✅ Acompanhar a implantação do sistema.

Horário: Seg á sex - 09h ás 18h
Cliente: Bravve

## Benefícios

- Plano de saúde (opcional);
- Seguro de vida;
- Gympass;
- VR/VA Ifood - R$660,00.

## Contratação

CLT Benefícios.

## Como se candidatar

Por favor envie um e-mail para shirley.santos@foursys.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor Java Sênior.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: shirley.santos@foursys.com.br

#### Alocação
- Remoto

#### Regime
- CLT Beneficios

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
