### ISSUE TITLE
[remoto] Front-end Developer React Native na ITeam

### ISSUE THREAD

**Issue by VivianeRHTI** [frontendbr/vagas#6260]
## Local

100% Remoto - Horário comercial

## Requisitos

Experiência em React Native, JavaScript/TypeScript, Redux-Saga, Integração do APIs, CSS3, Jest, Fastlane, Firebase, GIT, Android Studio: SDK, AVD, Gradle. XCode: Schemes, Simulator, Arquive;
Metodologia SCRUM.

## Atividades

Atividades: Construção/Melhorias de aplicativo transacional bancário, envolvendo Pix.

## Contratação

Contratação: 6 meses
PJ 

## Nossa empresa

Há mais de 15 anos presente no mercado, a ITeam oferece o comprometimento com o cliente.
Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 
O relacionamento da ITeam é baseado no amplo comprometimento com os valores e objetivos dos nossos Clientes, fornecendo soluções e serviços de TI que contribuam para a realização de seus objetivos.

## Como se candidatar

Envie um e-mail para viviane.pereira@iteam.inf.br com seu currículo atualizado e pretensão de taxa/hora - enviar no assunto: Vaga no GITHUB - React Native

## Labels

- Horário comercial
- Remoto
- Pleno e Sênior
- PJ

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
