### ISSUE TITLE
[Florianópolis ] Front-end Developer na Yungas

### ISSUE THREAD

**Issue by gomeslucasm** [frontendbr/vagas#6262]
# Empresa

A Yungas é uma plataforma de tecnologia pioneira e líder em transformação digital de franqueadores no mercado brasileiro e está em busca de pessoas com vontade de crescer e de fazer parte desse time incrível!

- https://www.linkedin.com/company/yungas/
- https://yungas.com.br/

# Descrição da vaga

Estamos desenvolvendo web apps com tecnologia de ponta, e procuramos um desenvolvedor que possa agregar com sua experiência em UI/UX, best practices e capacidade de solucionar problemas. Você irá trabalhar no dia-a-dia com Svelte, um framework de Javascript que está, assim como nós, decolando. Não se preocupe, sabemos que poucos devs possuem experiência com Svelte, por isso experiência com Vuejs, React ou Angular são nossos requisitos.

 

## Requisitos

- Autodidata, espírito empreendedor e mindset ágil;

- Prezar pelo desenvolvimento de código limpo, com foco em performance e manutenção;

- Prezar pela experiência do usuário e legibilidade da interface.

- Domínio profundo de alguma solução de front-end (Angular, Vue ou React, mas de preferência React+Redux) ou Svelte;

- Familiaridade com sistemas de design como Lightning System, Material UI ou outro;

- Conhecimento em GIT e Docker.

## Diferenciais

- Svelte;

- RxJS;

- Ramda;

- React+Redux+(Redux-saga ou Redux-observable);

- Programação funcional com Javascript;

- Domínio de Rollup ou webpack;

- Conhecimento de conceitos como tree-shaking e code-splitting;

## Benefícios

- Oportunidade de fazer a diferença numa empresa que está crescendo em ritmo acelerado e mudando o segmento de franchising do Brasil;

 - Vale Refeição e Vale Alimentação (Ifood Benefícios);

- Gympass;

- Ambiente descontraído no coworking Lemonade, no escritório em Florianópolis-SC (Itacorubi),  com open café, frutas e happy hour;

- Horários flexíveis em modelo híbrido ou remoto.

# Como se candidatar

- https://jobs.quickin.io/yungas/jobs/61c1d9ab2d8f440015afc24e?src

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
