### ISSUE TITLE
[Campinas/SP] Estágio front-end Developer na BHUT

### ISSUE THREAD

**Issue by tmsouza** [frontendbr/vagas#6263]
## Descrição da vaga

Desenvolvimento de novas funcionalidades para a aplicativo de pagamentos.

## Local

Escritório, Campinas/SP - Centro

## Requisitos

**Obrigatórios:**
- Técnico ou faculdade em áreas relacionadas a tecnologia.

**Desejáveis:**
- Interessado e rápido aprendizado.

## Contratação

Contrato de estágio

## Como se candidatar

Por favor envie um email para vagas@bhut.com.br com seu CV anexado.

**Comment by SrTesch** [comment]
possibilidade de estagiar remotamente?

**Comment by Rstork18** [comment]
Gostaria de saber a possibilidade de estagio remoto

**Comment by tmsouza** [comment]
@SrTesch @Rstork18 infelizmente para essa vaga não temos essa opção.
