### ISSUE TITLE
[REMOTO] Front-end Developer @ CARUPI

### ISSUE THREAD

**Issue by robertocosta-carupi** [frontendbr/vagas#6264]
SOBRE A CARUPI

Startup de tecnologia de alto crescimento, reinventando a forma de se comprar e vender carros com um modelo de negócios nunca antes tentado.

- Acelerada pelo Y Combinator, que lançou empresas como Airbnb e Dropbox;
- Investida por fundos de prestígio do Vale do Silício;
- Mencionada no Valor Econômico, na Folha de São Paulo, no Estadão dentre outros;
- Composta por um time de aproximadamente 350 pessoas; e
- Com a meta agressiva de entrar nos Estados Unidos em 2022 e em pelo menos outros 4 países até 2023.

 

NOSSA MISSÃO

Carros fazem parte da nossa história. Por isso, nossa missão é fazer da compra e venda do seu veículo, um momento importante, simples e seguro.

 

SOBRE O TIME

O time de Tecnologia é chave para o nosso crescimento e, como consequência, repleto de desafios e oportunidades. Ele é responsável pelo desenvolvimento das plataformas CARUPI de Web e App, além de cuidar do desenvolvimento e conexão de algumas ferramentas utilizadas, internamente, pelos times comerciais.

 

O QUE VOCÊ VAI FAZER

- Desenvolver componentes visuais e implementação de layout e interações projetadas pelo UI/UX;
- Tratar problemas e bugs apontados por clientes internos e externos;
- Programar soluções para problemas complexos; e
- Solicitar testes e garantir qualidade na entrega.

REQUISITOS

- Conhecimento avançado de React (Redux, Gatsby, NextJS);
- Capacidade de ler códigos e resolver erros e bugs resultantes do código;
- Capacidade de programar usando boas práticas de clean code visando clareza e desacoplamento; e
- Capacidade de desenhar soluções para problemas complexos.

DIFERENCIAIS

- Capacidade de pensar em implicações e impactos das modificações feitas em outras frentes;
- Experiência com UI/UX;
- Habilidade em Testes automatizados; e
- Capacidade de resolver problemas abstratos. 
 

DETALHES

Em caso de necessidade, espera-se disponibilidade para correção de problemas que aconteçam fora do horário comercial.

## Como se candidatar

Para se candidatar, basta acessar o link: https://carupi.applytojob.com/apply/Il2OdoyAho/Desenvolvedor-Front-End?source=LINK

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: roberto.costa@carupi.com

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
