### ISSUE TITLE
[Porto Alegre] Front-End Angular na AIORIA

### ISSUE THREAD

**Issue by gbtagliari** [frontendbr/vagas#627]
## Descrição da vaga

Estamos procurando um estagiário para compor nosso time de desenvolvimento. O candidato precisa ter experiência em projetos desenvolvidos em Angular 4, saber trabalhar em equipe e ter vontade de aprender e crescer profissionalmente!

## Local

Bairro Petrópolis, Porto Alegre.
Próximo à PUC e da Av. Ipiranga.

## Benefícios

- VR
- VT

#### Diferenciais

- horário flexível
- fliperama e simulador de corrida
- ambiente descontraído

## Requisitos

**Obrigatórios:**
- Angular 4 e Angular CLI
- git

**Desejáveis:**
- node.js
- javascript/typescript
- Mobile First

**Diferenciais:**
- PWA
- express.js
- mongodb

## Contratação

Estágio

## Nossa empresa

- A AIORIA é uma empresa com DNA de programador e espírito inovador;
- Estamos no mercado desde 2009;
- Trabalhamos com startups e com projetos próprios;
- Nosso site: https://aioria.com.br
- Sim, AIORIA é o nome do Cavaleiro de Leão dos Cavaleiros dos Zodíacos;

## Como se candidatar

Por favor envie um email para contato@aioria.com.br com seu CV anexado

**Comment by gbtagliari** [comment]
Favor colocar as tags Estágio, Júnior

**Comment by danilosilvadev** [comment]
"Noções" significa que só precisa saber o que é, e não exatamente como programar em angular? E qual versão do angular? não ficou muito claro isso.

**Comment by gbtagliari** [comment]
@danilosilvadev o candidato deve ter alguma experiência em projetos Angular 4 e estar a fim de aprender!

**Comment by kivervinicius** [comment]
<3 pelo nome.

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by gbtagliari** [comment]
@LFeh já fizemos a contratação.
