### ISSUE TITLE
[Remoto] Young Guns - Trainee na Pipefy

### ISSUE THREAD

**Issue by laracmportugal** [frontendbr/vagas#6271]
## Nossa empresa

A Pipefy é uma empresa Tech do segmento SaaS (software como solução de negócio) que faz parte do fundo de investimento da OpenView.
Nascemos em 2015, e atualmente mais de 3000 empresas em mais de 150 países utilizam o Pipefy, de startups até líderes de mercado, como a Accenture, Visa, GE e Volvo. Contamos com um time de +480 pessoas trabalhando remotamente de vários lugares do mundo.

## Descrição da vaga

O Young Guns é o principal programa de porta de entrada da Pipefy. Ele oferece a oportunidade de iniciar sua carreira trabalhando em um ambiente global e remoto dentro de uma das empresas de tecnologia que mais crescem no Brasil.
Esse trabalho inclui participar ativamente de projetos estratégicos e desenvolver as habilidades interpessoais e técnicas necessárias para impulsionar sua carreira se tornar um dos próximos líderes da Pipefy.

_Software Engineering Stack:_
Frontend: React e Typescript
Backend: Ruby on Rails e Elixir
Mobile: Kotlin e Swift
Metodologias: Lean, Agile, Tribes, Squads, Kanban e Scrum
_Importante frisar que não exigimos nem avaliamos esse conhecimento prévio, para o programa de Young Guns são bem vindas pessoas que conhecem qualquer linguagem._

## Local

Remoto

## Requisitos

**Obrigatórios:**
• Ensino médio completo.
• Disponibilidade para atuar em regime de contratação CLT (Remoto ou híbrido, você escolhe).
• Atitudes positivas.
• Desejo de participar ativamente na criação de algo maior, com propósito.
• Lógica de programação básica

## Benefícios

- Plano de saúde e odontológico
- Seguro de vida
- Horário flexível (40h/semana)
- Vale alimentação/refeição flexível
- Auxílio home office mensal
- Subsídio de mobília
- Assistência psicológica (para você ou dependentes legais)
- Yoga e Meditação
- Gympass
- Aulas de ginástica laboral
- Licença maternidade / Paternidade (6 e 3 meses respectivamente)
- Auxílio para contratação de babá / Escola primária
- Auxílio para nutrição complementar
- Plano veterinário
- Folga de aniversário
- Licença de casamento (7 dias)
- Licença de luto pessoas amadas (10 dias)
- Licença de luto animal de estimação (2 dias)
- Auxílio funeral (individual)
- Auxílio educação continuada
- Empréstimo consignado
- Consultoria financeira
- Udemy
- Espaço de coworking

## Contratação

CLT

## Como se candidatar

Se inscreva na nossa posição no link [Young Guns - Tech](https://app.pipefy.com/public/form/62qDlV11)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: lara.portugal@pipefy.com

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior

**Comment by Wildmarks-Passos** [comment]
Formulário respondido. Aguardando ansiosamente pelo resultado!

**Comment by VanessaMainara** [comment]
🤞🏻

**Comment by EzequielRT** [comment]
Top demaisss

**Comment by GuilhermeLaraRusso** [comment]
Formulário respondido. 🤞🏻

**Comment by LucianoEGuimaraes** [comment]
Obrigado pela oportunidade, no aguardo! 👍🏻

**Comment by willianslc** [comment]
Formulário respondido e enviado, no aguardo de resposta 🙂

**Comment by Vitaopb** [comment]
Formulário enviado, no aguardo!

**Comment by samarafarias** [comment]
Formulário enviado!

**Comment by GuilhermeCarluz** [comment]
Formulário enviado!

**Comment by renatoknot** [comment]
Nossa que sonho! Form enviado.

**Comment by aramisic** [comment]
Que oportunidade é essa! Nunca estive tão ansioso!!

**Comment by JohnCMello** [comment]
Formulário enviado. Aguardando o retorno. Desde já agradeço a oportunidade.

**Comment by NicholasWM** [comment]
Formulário respondido, aguardando retorno o/

**Comment by Djamess** [comment]
Formulário enviado!
