### ISSUE TITLE
[São Paulo] Front-End Developer na IGS - International Global Solutions

### ISSUE THREAD

**Issue by RafhaelaFranco** [frontendbr/vagas#6276]
Aqui na IGS somos líderes em desenvolvimento de software para jogos de cassino, trabalhamos com diversas filiais na Europa e América Latina.

Descrição da vaga:
Desenvolvedor front-end. - Implementação de métodos de UX/UI.
Local: Presencial – São Paulo – SP - Moema

Requisitos:
Conhecimento Vue.Js, Node.js, Docker, JavaScript, Docker-compose, Git.
Queremos alguém com facilidade em aprender e principalmente gostar de aprender ferramentas novas.

Idioma:
Inglês

Nossos benefícios são:
- VR R$ 814,00 mês
- Assistência Médica Bradesco
- Bonificação por Desempenho
- Seguro de Vida
- Sistema Híbrido de trabalho
- Vale Transporte

Regime:
- CLT

Nível: 
- Pleno/Sênior

Como se candidatar:
Por favor, envie um e-mail para genteegestao@igs-software.com.br com seu CV anexado – ao enviar, colocar no assunto: Vaga Front-End.

Costumamos entrar em contato assim que recebemos o CV no perfil da vaga para dar continuidade no processo.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
