### ISSUE TITLE
[Belo Horizonte] Front-End Developer no Grupo Monetizze

### ISSUE THREAD

**Issue by brunopulis** [frontendbr/vagas#628]
## Descrição da vaga

* Atuar no desenvolvimento dos produtos da empresa
* Implementação e manutenção nos diversos produtos;
* Análise e identificação de problemas.

## Local

Bairro Ouro Preto - (próximo ao Shopping Del Rey) - Belo Horizonte/MG

## Benefícios

- Participação nos lucros, 
-  Assistência Médica 
- Assistência Odontológica, 
- Vale Alimentação, 
- Seguro de Vida, 
- Vale Transporte\Combustível, 
- Convênio Farmácia, 
- Almoço na empresa, 
- Café da manhã, lanche da tarde, frutas.

## Requisitos 

Conhecimentos

- Javascript,
- JQuery, 
- HTML5, 
- CSS/Sass, 
- Git
- Layout responsivo/mobile.

Diferenciais
- Experiência com responsive design;
- Web Standards;
- Noções básicas de Sketch/Zeplin;
- Metodologias ágeis;
- SEO.

Diferenciais
- No Dress Code
- 1:30 de almoço
- Horário Flexível
- Frutas

## Contratação

CLT Efetivo.

## Nossa empresa

Somos uma empresa de tecnologia super antenada com as tendências e inovações do mercado. Possuímos um clima organizacional descontraído e amigável. Prezamos pelo bem estar dos nossos funcionários bem como pelos resultados do trabalho. Transparência, honestidade e franqueza são alguns de nossos valores.

Procuramos profissionais alinhados com nosso "jeito de ser", que querem ser donos do próprio caminho e sejam responsáveis e comprometidos com suas entregas.

## Como se candidatar

Por favor envie um email para rh@vianetbrasil.com.br com seu CV anexado - enviar no assunto: Vaga de Frontend

**Comment by lucazweb** [comment]
Enviado :)

**Comment by brunopulis** [comment]
Vaga preenchida.
