### ISSUE TITLE
[Indaiatuba - SP] Software Developer Intern na Linked RH

### ISSUE THREAD

**Issue by mateu5-francisco** [frontendbr/vagas#6280]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/estagio-em-desenvolvimento-de-software-140659445?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>O que esperamos de você?</strong></p>
<p>- Boa lógica de programação.</p>
<p>- Muita vontade de aprender e estudar.</p>
<p></p>
<p><strong>Principais atividades do estágio:</strong></p>
<p>- Aprender a desenvolver sistemas utilizando a linguagem de programação adotada pela empresa.</p>
<p>- Aprender a analisar tecnicamente as tarefas de desenvolvimento e preparar especificações técnicas.</p>
<p>- Aprender a automatizar testes unitários.</p>
<p></p>
<p>Aqui você aprenderá a utilizar codificar utilizadando as melhores práticas de arquitetura e programação.</p>
<p>Somos uma empresa apaixonada pelo que fazemos, trazendo transformação e inovação. São mais de 20 anos de experiência em desenvolvimento de software.&nbsp;</p>
<p>Oferecemos apoio par</p>
<p><strong>IMPORTANTE: </strong>É obrigatório residir em Indaiatuba, Salto, Monte Mor ou Elias Fausto.&nbsp;</p>

## Linked RH: 
 <p>Oferecemos apoio para que as pessoas se desenvolvam profissionalmente, através de plano de carreira, programa de mentoria, ambiente desafiador e oportunidades de aprendizados constantes.</p>
<p>Você utilizará metodologias ágeis, ferramentas/tecnologias de última geração, computação em nuvem e muito mais.</p><a href='https://coodesh.com/empresas/linked-rh'>Veja mais no site</a>

 ## Habilidades: 
 - Angular 11 
- Ionic 
- Java
## Local: 
 Indaiatuba - SP

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Software Developer Intern na Linked RH](https://coodesh.com/vagas/estagio-em-desenvolvimento-de-software-140659445?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Regime
Estágio
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
