### ISSUE TITLE
[Hibrido / São Paulo, São Paulo, Brazil] Fullstack PHP Developer na ECOASSIST 

### ISSUE THREAD

**Issue by mateu5-francisco** [frontendbr/vagas#6282]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/programador-web-143541719?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Criar e realizar manutenção no código da empresa, responsável por fazer o backup do banco de dados diariamente, acompanhar as tarefas de desenvolvimento e utilizar a ferramenta de versionamento, criar e consumir API's internar e externas, levantar requisitos de sistema junto a equipe de clientes.</p>

## ECOASSIST : 
 <p>Você ama sustentabilidade e meio ambiente? Quer ajudar a fazer a diferença construindo um mundo mais verde? A EcoAssist é para você!</p>
<p>Somos uma empresa de logística reversa que auxilia seguradoras, empresas e consumidores a realizar o descarte correto de resíduos como sofás, geladeiras, eletrônicos e muito mais. A Ecoassist existe desde 2009 e vem crescendo a cada dia.</p><a href='https://coodesh.com/empresas/ecoassist'>Veja mais no site</a>

 ## Habilidades: 
 - PHP 
- Rest e Restful APIs 
- Banco de dados relacionais (SQL)
## Local: 
 São Paulo, São Paulo, Brazil
## Requisitos: 
 - Formação em Análise de desenvolvimento de sistemas, Ciência da computação, sistema da informação ou cursos de desenvolvimento de sistemas 
- Capacidade analítica para problemas e soluções adequadas 
- Conhecimento em PHP 5.3 para realizar manutenção do sistema antigo e PHP 7.0 ou maior para o sistema novo 
- Conhecimentos em Javascript, CSS e MySQL 
- Conhecimentos GIT e Github.
## Diferenciais: 
 - Conhecimento em Python ou Node.js e em banco de dados não relacional(MongoDB)

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack PHP Developer na ECOASSIST ](https://coodesh.com/vagas/programador-web-143541719?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Regime
CLT
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
