### ISSUE TITLE
[Remoto] Front-end Developer na Plus-it Tech (Alocação Jamef encomendas urgentes)

### ISSUE THREAD

**Issue by PRI2021plus** [frontendbr/vagas#6284]
Front-End Developer (React Pleno/Sênior) na Plus-it Tech (Alocação Jamef encomendas urgentes)

> Vaga Remota 100%

Plus-it Tech 
Empresa de desenvolvimento de software com mais de 14 anos de mercado

Desenvolvimentos Web utilizando React.JS com Redux
Projeto  com Jamef encomendas urgentes
Vaga 100% Remoto 

## Requisitos
**Obrigatórios:**
- React.JS com Redux
- Capacidade de desenvolvimento utilizando pré-processadores de CSS como LESS e SAAS;
**Desejáveis:**
- HTML 5; CSS 3; Javascript (VanillaJS) e Pré-processadores de CSS (SASS ou LESS);
**Diferenciais:**
- Serviços da Nuvem ( AWS) para Impementação Web

PJ a combinar
Por favor envie um email para priscila.ferreira@plus-it.com.br com seu CV anexado - enviar no assunto: Vaga Frontend

Costumamos enviar feedbacks em até 5 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ
- clt

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
