### ISSUE TITLE
[REMOTO] Tech Lead Fullstack na Cubos Academy

### ISSUE THREAD

**Issue by eliprovesi** [frontendbr/vagas#6285]
## Nossa empresa

➡ A **Cubos Academy** é uma escola de **formação de profissionais da área de tecnologia**. Fomentamos o mercado de tecnologia, qualificando novos profissionais e intermediando sua entrada no mercado de trabalho, contando com uma área especializada na empregabilidade dos nossos alunos.
 
## Descrição da vaga

🏃‍♀️ Buscamos uma pessoa para atuar como **Liderança Técnica de Desenvolvimento** em nossa área de **Residência de Software**. Essa pessoa terá o incrível papel de ser a guardiã das boas práticas e uma referência para o nosso time de desenvolvimento, formado por estudantes que concluíram os nossos cursos e estão tendo a primeira experiência profissional no mercado de trabalho.
 
➡ Dentre a suas responsabilidades estão o acompanhamento, desenvolvimento e inspiração de desenvolvedores Jr em projetos de **baixa complexidade**. Contribuindo para a inclusão e diversidade no mercado de tecnologia.

Se você acredita que podemos transformar a realidade através da educação, é um amante de tecnologia e quer trabalhar com propósito e impacto, vamos amar ter você em nosso time 🧡
 
#VemPraCubosAcademy🚀

## 🌎Local

Remoto 

## 📚 Responsabilidades e atribuições: 

◾ Liderar e supervisionar pequenos squads de desenvolvimento de software de projetos de baixa complexidade formado por desenvolvedores Juniores; 
◾ Ajudar na codificação _(handson)_ liderando a responsabilidade do projeto;
◾ Planejar e acompanhar as sprints aplicando os rituais técnicos (planning, dailys, code reviews, testes, etc) e comportamentais (1:1, feedbacks, etc) necessários para o sucesso do projeto e aceleração do time;
◾ Facilitar e orientar discussões de arquitetura, considerando variáveis técnicas e não-técnicas;
◾ Dimensionar o squad e o tempo de desenvolvimento de um projeto de acordo com o seu escopo;
◾ Entender as necessidades do cliente, acompanhar tendências do mercado e usar o melhor da tecnologia para disponibilizar features com qualidade e agilidade.

## 🏅Requisitos

**Obrigatórios:**
◾ Experiência em desenvolvimento web fullstack: React + Hooks + Material UI; Nodejs + express + postgres (knex).
◾ Conhecimento do padrão MVC, Repository Pattern e Injeção de dependência, testes de integração com jest + supertest
◾ Experiência com testes e code review;
◾ Experiência com metodologias ágeis (Scrum e Kanban);
◾ Experiência 360º no ciclo de desenvolvimento de um software em escopo fechado (planejamento, desenvolvimento e entrega);
◾ Habilidade em resolução de problemas e redução de esforços;
◾ Ótima capacidade comunicativa e organizacional;
◾ Amar desafios e compartilhar conhecimento;
◾ Aproximadamente 3 anos de experiência como fullstack.
 
**Diferenciais**
◾ Possuir experiência como liderança técnica fullstack;
◾ Conhecimento em Flutter;
◾ Projetos pessoais em produção.

**🧡Nossos Benefícios**
◾ Plano de Saúde Bradesco (custeado 100% por nós) (CLT)
◾ Plano Odontológico Bradesco (CLT)
◾ Cartão de benefícios Flexíveis Flash: para você escolher onde usar (CLT)
◾ Day Off para o aniversariante em qualquer dia do mês para curtir como quiser (CLT + PJ)
◾ Gympass: para você cuidar do seu corpo e saúde (CLT + PJ)
◾ Licença Parental estendida (CLT + PJ)
◾ Licença Casamento estendida (CLT + PJ)

🔎 **O que mais você encontra aqui:**
◾ Participação em Trilhas de Conhecimento;
◾ Programa Pause: para ao longo do dia você não se esquecer de respirar novos ares, se alongar e dar uma pausa;
◾ Horário semi-flexível: dentro do horário comercial;
◾ Home-office permanente;
◾ Segurança Psicológica;
◾ Oportunidade de trabalhar em um ambiente colaborativo, desafiador e que valoriza a diversidade.

👣 **Etapas do Processo Seletivo:**
◾ Inscrição
◾ Desafio Técnico
◾ Entrevista Comportamental e Técnica
E só! 😉
 
🧡 A Cubos tem o compromisso de tornar o mundo do trabalho mais diverso e inclusivo. Por conta disso, durante o processo priorizaremos mulheres (cis ou trans), pessoas com deficiência, pessoas negras, indígenas ou quilombolas;

## Contratação

PJ | CLT | a combinar

## Como se candidatar

Se inscreva no link 👉 https://cubosacademy.gupy.io/jobs/1429574 

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

**Comment by joaoreisjpk** [comment]
Oi meu nobre, é pra júnior, pleno, senior? Qual o nível requirido?

**Comment by thaylorcs** [comment]
João, a vaga é para tech lead. Acredito que Sênior seja o mínimo

**Comment by eliprovesi** [comment]
Oiee!! Então, geralmente para de líder não tem senioridade. Mas é esperado um tempo razoável de experiência. Para essa vaga pedimos aproximadamente uns 3 anos de experiência como fullstack 😊

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by eliprovesi** [comment]
Olá! 😊 
Obrigada por informar, a vaga ainda está aberta.
