### ISSUE TITLE
[Remoto] Fullstack React/Node Developer na Samba Tech

### ISSUE THREAD

**Issue by mateu5-francisco** [frontendbr/vagas#6287]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/pessoa-desenvolvedora-fullstack-pleno-node-react-125839075?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A Samba está buscando uma pessoa Desenvolvedora Fullstack Pleno para agregar ao nosso time!</p>
<p>Para essa oportunidade buscamos uma pessoa para atuar em regime CLT e 100% remoto.</p>
<p>Procuramos alguém com propósito forte e que esteja disposta a trabalhar em ambiente colaborativo e dinâmico, pronto para crescer profissionalmente junto com a nossa equipe fora da curva!</p>
<p>A Samba gosta de fazer a diferença sempre e nosso time é o responsável para que isto aconteça! Por isso, a gente espera que você seja uma pessoa apaixonada por tecnologia, assim com a gente!</p>
<p>Todas as nossas vagas também se aplicam a pessoas PCD, então fique à vontade para se candidatar!</p>
<p></p>

## Samba Tech: 
 <p>A Sambatech é uma das empresas mais inovadoras do mundo, segundo a Fast Company, e é referência no mercado de vídeos online. Nossa empresa garante infraestrutura de alta qualidade para venda, distribuição, gerenciamento e armazenamento de vídeos e ajuda pessoas e empresas a terem mais sucesso, independentemente do seu objetivo.</p>
<p>Com suas soluções, a Samba atende diferentes tipos de necessidades relacionadas aos conteúdos audiovisuais e possui uma equipe totalmente focada em assegurar que nossos clientes tenham acesso ao que há de melhor em tecnologia para vídeos online.&nbsp;&nbsp;&nbsp;</p><a href='https://coodesh.com/empresas/samba-tech'>Veja mais no site</a>

 ## Habilidades: 
 - Node.js 
- React.js 
- SOLID
## Local: 
 100% Remoto
## Requisitos: 
 - JavaScript feat NodeJs; 
- React; 
- SOLID; 
- Typescript; 
- REST.
## Diferenciais: 
 - PHP; 
- GraphQL; 
- Aplicações SOAP; 
- Docker.
## Benefícios: 
 - Ambiente criativo e inovador; 
- Clima leve e descontraído; 
- Horário flexível; 
- Home office 
- Auxílio home office 
- Plano de Saúde; 
- Plano Odontológico; 
- Vale refeição/alimentação; 
- Gym Pass;  
- Day off no dia do aniversário 
- Seguro de vida; 
- Ways Education - Atividades extracurriculares para os filhos; 
- Previdência privada.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack React/Node Developer na Samba Tech](https://coodesh.com/vagas/pessoa-desenvolvedora-fullstack-pleno-node-react-125839075?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
