### ISSUE TITLE
[Remoto] Front-end React na Nave.rs

### ISSUE THREAD

**Issue by BrunaSouzaPaes** [frontendbr/vagas#6288]
> Vaga Remota

## Nossa empresa

Trabalhar com a nave.rs significa que você conhece e colabora com as pessoas que realmente fazem o trabalho. Unimos tecnologia e criatividade para criar soluções digitais efetivas que se tornam memoráveis e impactam positivamente a vida das pessoas.
Nossa missão é ajudar empresas a entender antes de agir, a agir com precisão e a lucrar a partir de mudanças.
Não é somente sobre produtos digitais, é sobre marcar positivamente a vida das pessoas

## Descrição da vaga

A Nave.rs está procurando uma pessoa com perfil de nível júnior a pleno, que tenha experiência na área de desenvolvimento Front-end, domínio da linguagem React, experiência com clientes e projetos.

Como pessoa desenvolvedora para a área de Front-end, você irá utilizar a linguagem React . Na empresa trabalhamos com a metodologia ágil Scrum, sendo assim, temos cerimônias como planning, weekly e retro. O seu dia a dia de trabalho irá basear-se nas cerimônias e no projeto que você irá entrar.

Você irá atuar como Front-end em aplicações web utilizando react . Dessa forma, procuramos uma pessoa que seja comprometida com sua evolução, que tenha ideias inovadoras, tenha proatividade e pense fora da caixa. É importante que você goste de se comunicar e trabalhar em equipe, já que aqui temos um ambiente super colaborativo. Ao mesmo tempo, valorizamos que cada membro do time seja autônomo para gerir suas demandas.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- HTML
- CSS
- JavaScript
- Experiência no desenvolvimento de aplicações web utilizando React;
- Experiência com projetos
- Boa comunicação
- Bom gerenciamento de tempo

**Diferenciais:**
- projetos outsourcing 

## Benefícios

- Assistências médica e odontológica;
- Auxilio psicológico;
- VR / VA de R$ 24,10/dia
- Aulas de inglês;
- Auxilio Educação (acesso a plataformas de cursos)
- Horário flexível e possibilidade de home office.

**Diferenciais:**
- plano de carreira estruturado
- hierarquia minima

## Contratação

CLT + benefícios. 

## Como se candidatar

Inscreva-se através do link: https://nave-team.gupy.io/jobs/1446937

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by raf2019** [comment]
Inscrições encerradas:

Cronograma do processo seletivo:

(12/01 - 15/01)) - Inscrições na gupy

(12/01 - 16/01) - Teste técnico

(17/01 - 20/01) - Entrevista de cultura

(24/01 - 27/01) - Entrevista técnica

(31/01- 04/02) - Contratação

**Comment by EriickFraga** [comment]
Nossa que pena, encontrei a vaga hoje. Me encaixo nos requisitos mas... deixa pra uma próxima oportunidade.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
