### ISSUE TITLE
[Remoto] Pessoa Coordenadora de Desenvolvimento de Software na Méliuz

### ISSUE THREAD

**Issue by Folks-Meliuz** [frontendbr/vagas#6290]
## Descrição da vaga
Somos uma marca global, certificada pelo ranking GPTW e comprometida em criar produtos, serviços e parcerias alinhadas à nossa Cultura. Estendemos o compromisso às pessoas colaboradoras, investindo no desenvolvimento e satisfação das pessoas Meliantez (ou pessoas que trabalham no Méliuz).
Temos orgulho de onde viemos e queremos contar para o mundo onde chegamos - e para onde iremos.
Quer ver o seu trabalho impactar a vida de mais de 20 milhões de pessoas usuárias, atuar de qualquer parte do Brasil com horários flexíveis e outros benefícios exclusivos?

**Temos 4 posições em aberto de Coordenação para as áreas de:** 

Operações: Cuidar de das interfaces próprias de contato do usuário com o Méliuz. Cuidas das ferramentas necessárias pro nosso time de CS atender bem nossos usuários

Cartão: Estudar, pesquisar, implementar melhorias que aumentem nossa receita com cartão, sempre prezando pela satisfação do usuário, sua retenção e os resultados de longo prazo

Shopping: Estudar, pesquisar, implementar melhorias que aumentem nossa receita com e commerce, Nota Fiscal e serviços recorrentes, sempre prezando pela satisfação do usuário, sua retenção e os resultados de longo prazo

Conta: Garantir infraestrutura para cliente cadastrar, logar, utilizar e recuperar conta do Méliuz (desde a conta do shopping até a conta digital). Garantir uma experiência segura do uso da conta. Desenvolver soluções que alavanquem open-banking.

Descubra mais detalhes sobre esta vaga e seja parte da nossa história!

**RESPONSABILIDADES E ATRIBUIÇÕES**

- Será responsável pela gestão de time de engenharia responsável por desenvolver e operar serviços que compõem o produto de cartões do Meliuz;
- Atuar como liderança técnica e de pessoas dentro do time;
- Gestão do dia a dia do time, conduzindo cerimônias, processos e acompanhamento das atividades do time;
- Gestão e desenvolvimento das pessoas do time, conduzindo cerimônias de 1-1, plano de desenvolvimento entre outras;
- Gerenciar e otimizar nossos processos de desenvolvimento;
- Responsável pelo desenvolvimento de soluções escaláveis e de qualidade;
- Atuar como mentor técnico dos integrantes do time.

## Local
Remoto 

## Requisitos

- Ter experiência atuando em desenvolvimento de software como Pessoa Desenvolvedora Sênior e/ou Especialista;
- Experiência projetando arquiteturas para serviços escaláveis;
- Ter atuado como líder técnico ou gestor de pessoas na área de desenvolvimento de software;
- Bom conhecimento em metodologias ágeis de desenvolvimento de software;
- Boa comunicação e experiência gerindo interface com outras áreas como gerentes de produto, designers e customer success.

**Desejáveis:**

- Ter atuado em cenários/sistemas de alto desempenho / missão crítica;
- Sólidos conhecimentos das plataformas AWS ou GCP;
- Ter atuado em empresas que operam soluções em escala de internet;
- Ter experiência com serviços financeiros/cartão, E-commerce ou Operações.

## Benefícios
🥗 Vale refeição / alimentação (R$60,00 por dia útil);
🤩Plano de saúde;
😁 Plano odontológico;
⏰ Horário flexível;
💰 Premiação por atingimento de metas coletivas;
💵 Participação nos Lucros e Resultados (PLR)
📚 Subsídio para treinamentos
🏊‍♀ Convênio com Sesc;
🤑 Cashback online em dobro;
🤰 Licença Maternidade/Paternidade estendida;
💻 Ajuda de custo mensal para o teletrabalho;
🪑 Empréstimo / Reembolso de cadeira e mesa de escritório
✝ Auxílio luto.

## Contratação
CLT

## Como se candidatar
Clique [AQUI](https://meliuz.gupy.io/job/eyJqb2JJZCI6MTM3ODE0Miwic291cmNlIjoiZ3VweV9wdWJsaWNfcGFnZSJ9?jobBoardSource=gupy_public_page) para se candidatar

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
Tech Lead

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
