### ISSUE TITLE
[Remoto] FullStack Java/React Developer na Samba Tech

### ISSUE THREAD

**Issue by mateu5-francisco** [frontendbr/vagas#6292]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/pessoa-desenvolvedora-fullstack-java-react-130229012?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A Samba está buscando uma pessoa Desenvolvedora Fullstack Pleno para agregar ao nosso time!</p>
<p>Para essa oportunidade buscamos uma pessoa para atuar em regime CLT e 100% remoto.</p>
<p>Procuramos alguém com propósito forte e que esteja disposta a trabalhar em ambiente colaborativo e dinâmico, pronto para crescer profissionalmente junto com a nossa equipe fora da curva!</p>
<p>A Samba gosta de fazer a diferença sempre e nosso time é o responsável para que isto aconteça! Por isso, a gente espera que você seja uma pessoa apaixonada por tecnologia, assim com a gente!</p>
<p>Todas as nossas vagas também se aplicam a pessoas PCD, então fique à vontade para se candidatar!</p>
<p><strong>Responsabilidades:</strong></p>
<p>Desenvolver e manter soluções de software.</p>
<p>Escrever códigos limpos e funcionais no front-end e no back-end;</p>
<p>Participar dos ritos do projeto e propor novas soluções.</p>
<p>Acompanhar o levantamento de requisitos.</p>
<p>Trabalhar em conjunto com outros membros de equipe que fazem parte do projeto.</p>
<p>Apoiar a realização de atividades dos profissionais de menor domínio técnico, repassando conhecimentos e atuando no desenvolvimento dos mesmos.</p>
<p>Realizar integrações com APIs externas.</p>
<p>Utilizar e modelar bancos de dados relacionais e/ou não-relacionais.&nbsp;</p>

## Samba Tech: 
 <p>A Sambatech é uma das empresas mais inovadoras do mundo, segundo a Fast Company, e é referência no mercado de vídeos online. Nossa empresa garante infraestrutura de alta qualidade para venda, distribuição, gerenciamento e armazenamento de vídeos e ajuda pessoas e empresas a terem mais sucesso, independentemente do seu objetivo.</p>
<p>Com suas soluções, a Samba atende diferentes tipos de necessidades relacionadas aos conteúdos audiovisuais e possui uma equipe totalmente focada em assegurar que nossos clientes tenham acesso ao que há de melhor em tecnologia para vídeos online.&nbsp;&nbsp;&nbsp;</p><a href='https://coodesh.com/empresas/samba-tech'>Veja mais no site</a>

 ## Habilidades: 
 - Java 
- Javascript 
- React.js 
- Spring Boot
## Local: 
 100% Remoto
## Requisitos: 
 - Java 1.8. 
- Spring Boot 
- Arquitetura de micro-serviços 
- Java Script (ES6)  
- React 
- REST 
- MVC
## Diferenciais: 
 - SQL, Python ou Node 
- Cloud Computing (AWS, GCP) 
- Jest, e Enzyme ou RTL 
- SASS, CSS-in-JS 
- Redux

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [FullStack Java/React Developer na Samba Tech](https://coodesh.com/vagas/pessoa-desenvolvedora-fullstack-java-react-130229012?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
