### ISSUE TITLE
[Remoto] FRONTEND PROGRAMMER - PROJETO INTERNACIONAL - INFOVAGAS

### ISSUE THREAD

**Issue by patyandreolli** [frontendbr/vagas#6293]
**VAGAS FRONTEND PROGRAMMER - PROJETO INTERNACIONAL**
Experiência em programação front-end, com uso dos seguintes frameworks: AngularJS, React ou Bootstrap
Conhecimentos em JavaScript, HTML 5 e CSS3
Experiência em API REST
**Inglês Avançado/Fluente - O projeto é nos USA, com interação de 100%  com a equipe fora do Brasil**

Prazo: Indeterminado.
Contratação: PJ 
Local: 100% Remoto

Interessados enviar currículo para recrutamento@infovagas.com indicando no assunto "Frontend Programmer- HX"

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
