### ISSUE TITLE
[São Paulo - Remoto] Front-End Developer na [App7Sistemas]

### ISSUE THREAD

**Issue by elvislourenco** [frontendbr/vagas#6296]
**Descrição da vaga**
A App7 Sistemas esta contratando desenvolvedores front-end e full stack para trabalhar Home Office no desenvolvimento e manutenção de sistemas web, usando HTML5, JS, Bootstrap e AngularJS.
Local ou Remoto (Home office)

**Requisitos:**
Necessário conhecimento em desenvolvimento front-end com HTML5, Javascript, CSS, Bootstrap, Jquery e Angular Desejavel conhecimento em Transact-SQL (Microsoft SQL Server) Desejavel conhecimento em API's RestFull para integração de sistemas Desejavel conhecimento na linguagem Microsoft .Net C#

**Candidato:**
Comprometimento e responsabilidade com seus deveres e prazos .
Desejo de crescer junto com a empresa, sempre se atualizando e aprendendo novas tecnologias
 Não é necessário ter ensino superior ou estar cursando cursos de T.I., apenas ter o conhecimento que procuramos 
 Pro atividade para sugerir e pesquisar melhorias em nossos sistemas

**Contratação**
A vaga é para trabalhar Home Office em qualquer lugar do Brasil.
entre R$4.000 a R$7.000 PJ (dependendo do nível de experiência) + Auxílio Internet + Bolsa para cursos e especializações (Udemy,Alura,RocketSeat).

**Como se candidatar**
Por favor envie um email para elvis@app7sistemas.com com seu CV anexado - enviar no assunto: Vaga Front End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
