### ISSUE TITLE
[REMOTO/UBERLÂNDIA] React Native Freelancer

### ISSUE THREAD

**Issue by viniciusz42** [frontendbr/vagas#6297]
## Descrição da vaga

Projeto para ser startado do zero em react native. No MVP não terá nenhum recurso especial/complexo. Layout está pronto e foi utilizado o adobe XD para criá-lo, onde está disponível todos os assets.

## Local

Remoto ou Uberlândia

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento React Native

## Contratação

Freelancer ou PJ a combinar

## Como se candidatar

Por favor envie um email para viniciusdevep@gmail.com com seu CV ou linkedin - enviar no assunto: Freelancer We Live
## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by rodgomesc** [comment]
possibilidade de partial time?

**Comment by viniciusz42** [comment]
@rodgomesc sim

**Comment by Marco-oli** [comment]
Vaga aberta ainda?
