### ISSUE TITLE
[REMOTO] DevOps @ Fohat

### ISSUE THREAD

**Issue by NovareRH** [frontendbr/vagas#6299]
## Nossa empresa

A Fohat eTech Global é uma energytech brasileira que transforma inteligência energética em produtos digitais com o propósito de virar a chave do Mercado de Energia, trazendo a geração e a comercialização 100% do modelo analógico para o digital. Concentra o desenvolvimento das soluções de inovação com base tecnológica avançada da Fohat Corporation, think thank de energy intelligence que atua globalmente. Para entregar as soluções que ajudam a gerar uma energia mais barata, um mercado mais democrático e preservação de recursos naturais, a Fohat eTech Global oferece um ambiente de trabalho super preparado para o seu time de profissionais transformar inquietude, diferentes pontos de vista e criatividade em inovação dentro de um clima de acolhimento nas relações.

## Local

Remoto

## Requisitos

Experiência em:
- Cloud (Azure ou  AWS)
- Linux
- Elaboração de scripts (PowerShell, Shell Scripts e Python)
- CI/CD (Jenkins, AWS CodePipeline, Bitbucket Pipeline)
- DevOps
- Cultura DevOps

Conhecimento em:
- Contêineres e orquestração (Docker)
- Versionamento de código (Git e Gitflow)
- Metodologia e ferramentas ágeis: Scrum, Kanban, Jira
﻿
⚠  Tempo de experiência: 1 ano como Analista de Infraestrutura Cloud ou DevOps.

**Desejáveis:**
- Ter participado de projetos com desenvolvimento de sistemas Web para ambientes críticos como: Internet Banking, Plataformas de Investimentos, E-commerce, Plataforma de Criptoativos ou Home Brokers.  
- Possuir Certificação DevOps e ou Certificação AWS

**Diferenciais:**
- Inglês para área técnica.
- Git e as melhores práticas de versionamento (Gitflow)

## Benefícios

- Empresa investe em treinamentos de inovação, agilidade e Gestão de Pessoas. 
- Conta também com programas de qualidade de vida como Ioga, meditação e saúde mental.
- Fornece equipamento para trabalho remoto.

## Contratação

- PJ - A partir de 7k

## Como se candidatar

Aplique para a vaga [por aqui](https://www.careers-page.com/novare-rh/job/6RYV6R) .

#### Alocação
- Remoto

#### Regime
- PJ

**Comment by riancarlosdev** [comment]
???????????

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
