### ISSUE TITLE
[Joinville / SC] Software Engineer - Back-end

### ISSUE THREAD

**Issue by 21051307** [frontendbr/vagas#63]
As a software engineer at ContaAzul you will work with big challenges of scalability caused by huge quantity of datas and fast growth number of users, in an environment highly fun and collaborative. We need someone that has a passion in solving complex problems. A professional with strong skills in data and algorithm structures, along with a technical fascination of how things work. A motivated software engineer willing to experience and risk, in order to make a difference within his area, who is not afraid of defending his ideas and accept changes, next to highly trained people and motivated to improve day by day.

RESPONSIBILITIES
Elegant system code that requires search, interactivity and curiosity;
Write automated test to ensure the quality of the developed solution;
Analyse and improve the efficiency, scalability and stability of systems resources.

SKILLS & REQUIREMENTS
BS in Computer Science, Information Systems, related fields or equivalent experience;
[Desirable] Knowledge in Web development;
Our stack is mainly in Java - It is desirable that you have solid experience in this stack or be willing to learn quickly;
Solid knowledge in TDD, Clean Code and Design Patterns;
Knowledge of distributed Systems and high availability;
Desirable knowledge in other Web programming technologies: Ruby on Rails, Node.js. Desirable knowledge in Cloud, mainly AWS services;
Desirable knowledge in Agile methodologies and good communication skills,  essential for teamwork;
Ability to communicate in english, both written and verbally.

BENEFITS
A different work environment and innovative, with a culture that values people and the delivery of results;
Autonomy and flexibility;
Lunches, plus kitchen’s always stocked with unlimited snacks;
Compatible salary, above the market average;
R$ 400,00 meal tickets;
Financial Aid for extented education and graduate;
Financial Aid for learning english;
Affiliation with pharmacies;
Full health plan and Full dental plan without a discount on your paycheck;
Financial Aid for physical activities and yoga class;
A team that has our values in their DNAs
Living in one of the best cities to live in Brazil;
Access to books and other materials;
Transportation vouchers;
Great challenges and constant learning;
Events and courses that push you closer to the best on the market.

Cadastrar currículo - https://contaazul.com/carreiras/vagas#vagas-abertas

**Comment by eduardojmatos** [comment]
@21051307 a vaga já foi preenchida? Nos avise pra mantermos ou removermos da lista :)

**Comment by fernahh** [comment]
@eduardojmatos e @LFeh vocês podem fechar essa vaga? Provavelmene isso aqui foi um BOT. Em seguida foi abrir um issue com vagas que estão em aberto aqui na ContaAzul.

Obrigado!
