### ISSUE TITLE
[Joinville] Front-End Developer na Treasy Planejamento e Controladoria

### ISSUE THREAD

**Issue by treasyplanejamento** [frontendbr/vagas#630]
## Descrição da vaga

Se você adora desafios, não se contenta em fazer mais do mesmo todos os dias e entende que escalar uma aplicação SaaS traz desafios extremamente divertidos de serem resolvidos, nós temos algo fantástico para você crescer muito profissionalmente!

A Treasy vem mudando a maneira como as empresas brasileiras fazem gestão orçamentária, simplificando o processo e liberando horas para a controladoria atuar de forma estratégica nas organizações e precisamos da sua ajuda com nossos desafios de escala para garantir que a Treasy simplifique a gestão orçamentária de ainda mais empresas brasileiras.

O core do Treasy é construído em Java e nosso front-end está todo baseado em AngularJS, mas nada disso impede que nossos microservices rodem nodeJS, go, phyton ou o que ajudar a entregar valor de forma mais rápida aos nossos clientes.

Topa o desafio?

## Local

Treasy Planejamento e Controladoria - Rua Otto Boehm, 48, América - Joinville/SC

## Benefícios

Contratação CLT
Remuneração compatível com seu conhecimento e experiência
Vale transporte ou combustível
Vale refeição ou alimentação
Plano de saúde

#### Diferenciais

Ambiente de trabalho amigável e descontraído
No dress code. Vista-se como se sentir bem!
Free snacks
Cultura de feedback constante e aprendizado acelerado

## Requisitos

**Obrigatórios:**
Formação acadêmica na área de Tecnologia da Informação
Experiência em desenvolvimento web com AngularJs
Experiência com os padrões JSON e REST
Ser viciado em tecnologia
Transformar xícaras de café em linhas de código
Residir em Joinville - SC ou ter disponibilidade para mudança
Inglês avançado

**Desejáveis:**
Gulp
Docker
TDD
AWS

## Contratação

CLT Efetivo

## Como se candidatar

Cadastre seu currículo diretamente no link da vaga: https://treasy.recruiterbox.com/jobs/fk0mtia/ e aguarde nosso contato :).

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by treasyplanejamento** [comment]
Olá, está sim.

[image: Treasy]
<https://mailtrack.io/trace/link/7908467e78c2dee1ff3ed520b0857523a4891880?url=http%3A%2F%2Fwww.treasy.com.br%2F&userId=807614&signature=f2fccc099c3b2458>
*www.treasy.com.br
<https://mailtrack.io/trace/link/7908467e78c2dee1ff3ed520b0857523a4891880?url=http%3A%2F%2Fwww.treasy.com.br%2F&userId=807614&signature=f2fccc099c3b2458>*

*Ailly Orjana De Marco*
rh@treasy.com.br <ailly.marco@treasy.com.br>
(47) 3431-7322
*[image: facebook]
<https://mailtrack.io/trace/link/803ba3f3b682c9eda8d84f3f5ea7a96996382102?url=https%3A%2F%2Fwww.facebook.com%2FtreasyPlanejamento&userId=807614&signature=13c3242e901e392f>
[image:
twitter]
<https://mailtrack.io/trace/link/2a78644b5e5c7084502d20aab3736e0c3b38cf73?url=https%3A%2F%2Ftwitter.com%2FtreasyPlan&userId=807614&signature=0af8a5fe09553c9d>**
[image:
linkedin]
<https://mailtrack.io/trace/link/20cd1126f274b0cb8a568fbca530376d85244505?url=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2Ftreasy&userId=807614&signature=3c9994e0d6a8503c>*
 [image: google+]
<https://mailtrack.io/trace/link/47cd45842e732d5a6a0f6dfe1f7afb16592d486b?url=https%3A%2F%2Fplus.google.com%2Fu%2F0%2F%2BTreasyBr&userId=807614&signature=e0c324cba94e90c2>
 [image: youtube]
<https://mailtrack.io/trace/link/f0f2849a46ae9b5bb976a0e76198906f4b6b806c?url=https%3A%2F%2Fwww.youtube.com%2Fchannel%2FUCqblfZb5w3TiwSITUY8G73Q&userId=807614&signature=9e0ff8f39483efbc>

2018-01-23 14:26 GMT-02:00 Felipe Fialho <notifications@github.com>:

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
