### ISSUE TITLE
[REMOTO] React Native Developer na Dataseed

### ISSUE THREAD

**Issue by alvarogomes** [frontendbr/vagas#6303]
VAGA

Desenvolvedor react para manutenção ou criação em aplicação react, class components.
Frameworks: React Native, Redux ou Redux-toolkit, Axios.

freelance
inicio imediato
com possibilidade de integrar o time para mais projetos.
Enviar github.

Contratação

Freelance por hora = R$ 30 / h.

Nível
Pleno ou Senior

E-mail para se candidatar: alvaro.brito@dataseed.de

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
