### ISSUE TITLE
[CURITIBA] Front-end Developer no Clube Gazeta do Povo

### ISSUE THREAD

**Issue by AlexdeOliveiraSilva** [frontendbr/vagas#6306]
A oportunidade é para participar de um time com o desafio de continuar evoluindo um aplicativo/plataforma utilizado por cerca de 50 mil usuários.

Descrição do cargo:
- Executar melhoria contínua no produto para atender ou exceder as especificações de disponibilidade, qualidade e experiência do usuário do produto;
- Implementação de serviços utilizando nodeJS, nextJS e similares
- Gerenciamento de banco de dados relacional
- Auxiliar equipe no desenvolvimento de aplicações diversas

Competências desejadas:
- Autodidata e ser curioso, buscando sempre novas tecnologias e ideias, aprendendo rapidamente.
- Hands on foco em entrega e resolução de problemas, atrelado a alta capacidade técnica.
- Comunicação e trabalho em equipe

Desejável:
- Ensino superior completo
- Conhecimento em linux

Diferencial:
- Conhecimento em front-end (React, html puro, css)
- Conhecimento em AWS
- Conhecimento em react-native

Nível de experiência
- Junior/Pleno

Tipo de contratação:
PJ

Carga horária:
40 horas semanais

Empresa localizada em Curitiba - PR

## Como se candidatar

Por favor preencher o formulário https://forms.office.com/r/k3m7ASCiDT

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 30 dias após cada processo.
E-mail para contato em caso de não haver resposta: asilva@clubegazetadopovo.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
