### ISSUE TITLE
[Florianópolis] Full-Stack Developer na Chaordic

### ISSUE THREAD

**Issue by fabiomoreiragit** [frontendbr/vagas#631]
## Descrição da vaga

Linx+Neemu+Chaordic​ uniram suas forças para mudar ainda mais o mundo do e-commerce e do
varejo como um todo. Proporcionamos a cada usuário uma experiência única e personalizada no
momento de fazer suas compras. Para isso, temos em mãos uma das maiores bases de dados de
comportamento de compra online da América Latina, e a usamos para construir produtos para
milhões de pessoas que hoje navegam nos sites dos nossos clientes.

Como um desenvolvedor backend do time de Data Collection você será responsável por coletar um
gigantesco volume de dados tanto dos usuários quanto de nossos clientes, que fazem uso dos
nossos produtos. Para isto construímos serviços escaláveis e de alto desempenho utilizando como
principais linguagens NodeJS, Python e Scala. Embora maior parte do desenvolvimento seja
backend, alguns de nossos códigos que coletam comportamento do usuário rodam no browser e
para isto precisamos de algum conhecimento de frontend.

Nosso fluxo de desenvolvimento é fortemente baseado em testes automatizados, aplicação de boas
práticas de desenvolvimento de sistemas distribuídos e cultura devops. A infraestrutura utilizada para
implantação desses sistemas é a Amazon (AWS).

Se você é aquele desenvolvedor que se interessa não só pelas linguagens da sua área, mas em sair
do seu quadrado, novos desafios, e além de desenvolvimento, também de alguma (oper)ação, bem...
é por você que estamos procurando.

## Local

Lagoa da Conceição, Florianópolis - SC

## Benefícios

- Plano de saúde
- Plano odontológico
- Seguro de vida
- VR / VT
- Café da manhã
- Café da tarde (bolos, cucas, pao de queijo, etc..)

#### Diferenciais

- cozinha(bar) comunitária
- Happy hours frequentes dentro da própria sede (é bem legal aqui)
- Sede irada da uma espiada nas fotos, e fica na Lagoa da Conceição em Floripa, ve as fotos tb . ;) )

## Requisitos

**Obrigatórios:**
- Tem conhecimento aprofundado em Javascript e desenvolvimento para browsers (cookies,
local storage, same origin policy, etc.);
- Domínio de NodeJS;
- Domínio de Python ou Java ou Scala;
- Conhece Linux. Expertise na montagem de scripts shell e em ferramentas como grep, awk,
sed, etc. é uma grande vantagem;
- Se interessa pela stack inteira. Quando detecta um problema investiga tudo o que for
necessário para encontrar a causa raíz.

**Desejáveis:**
- É um programador poliglota e pragmático. Linguagens utilizadas no time são: NodeJS,
Python, Scala e Java
- Já trabalhou com metodologias ágeis;

## Contratação

CLT

## Nossa empresa

http://chaordic.com.br

## Como se candidatar

https://linxneemuchaordic.recruiterbox.com/jobs/fk0fxzr/

**Comment by fabiomoreiragit** [comment]
Tags:
Alocado
CLT
Pleno

**Comment by oPauloChaves** [comment]
Vaga top!

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
