### ISSUE TITLE
[Remoto] Front-end Developer na AM53 Tech

### ISSUE THREAD

**Issue by 2611Fer** [frontendbr/vagas#6310]
> 

## Nossa empresa

Exemplo: Aqui na AM53 Tech somos líderes em rect e Vue

## Local

Exemplo: Remoto 

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com React
- 2 anos de experiência com Teste Automatizado

**Desejáveis:**
-

**Diferenciais:**

## Benefícios

**Diferenciais:**
- 

## Contratação

PJ a combinar
CLT

## Como se candidatar

Por favor envie um email para fernanda@am53tech.com.br com seu CV anexado - enviar no assunto: Vaga Front End

#### Alocação

- Remoto

#### Regime
- CLT

- PJ

#### Nível

- Pleno
- Sênior
- Especialista

**Comment by riancarlosdev** [comment]
??????????????
