### ISSUE TITLE
[Remoto] Júnior Front-End Developer React na Proteína Digital

### ISSUE THREAD

**Issue by eduardorph** [frontendbr/vagas#6312]
Proteína Digital contrata Front-End Developer React junior. Não é necessário ter experiência, mas é fundamental que tenha certificado de conclusão de cursos voltados para a área e a tecnologia pedida.

Quer sua primeira oportunidade? 
Se encaixa no perfil? 

Então encaminhe seu currículo e venha fazer parte da proteína Digital!	

#### Requisitos: 
- Javascript ES6
- React
- HTML
- CSS
- Git	

#### Conhecimento em:
- Docker	

#### As Principais atividades: 

Dar manutenção e criar novos componentes para a plataforma de cms utilizada. 

#### Soft Skills
- Proatividade;
- Organização
- Boa comunicação
- Inteligência Emocional 

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior

#### Contato:
rh@proteina.digital
Esperamos seu e-mail com o assunto [Vaga de Dev React]

**Comment by afoliveira** [comment]
Boa tarde, é full-time ?

**Comment by Djamess** [comment]
acabei de enviar o currículo

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
