### ISSUE TITLE
[REMOTO] Front-end Developer Angular na Theos Sistemas

### ISSUE THREAD

**Issue by carlaprates** [frontendbr/vagas#6313]
## Nossa empresa

Somos uma empresa de tecnologia com mais de 20 anos de experiência em desenvolvimento de software voltado para Sistemas Eclesiais.
Somos em torno de 100 colaboradores em todo o Brasil com sede em Maringá/PR e polo em Campo Grande/MS.
Nossa missão é facilitar o dia a dia das instituições católicas, oferecendo sempre produtos inovadores, intuitivos e muito fáceis de usar.
Temos como foco disseminar para o cliente externo e interno nossos valores, carinho e dedicação.

#### Obrigatórios:

- Ensino Superior Completo/Cursando na área de TI.

#### Experiência em desenvolvimento utilizando:

- Javascript;
-  Angular8+;
-  Git;
- SASS;
- Métodos Ágeis;
- API Rest.

## Local

Remoto ou Escritório em Maringá/PR e Campo Grande/MS.

## Benefícios

- Plano de Saúde – Mensalidade 100% paga pela empresa;
- Vale Alimentação ou Refeição;
- Seguro de Vida;
- Plano Odontológico Uniodonto – Mensalidade 100% paga pela empresa;
- Modelos de contratação: Presencial Maringá/PR e Campo Grande/MS; Home Office ou Híbrido.
- Funcional e Ginástica Laboral duas vezes por semana na empresa (opcional);
- Área de Lazer com Piscina na Sede Maringá/PR (para uso das equipes e funcionários);
- Estacionamento Próprio Monitorado na Sede Maringá/PR;
- No Dress Code (não fazemos exigências sobre vestimentas);
- Frutas e Café da Tarde na Sede Maringá/PR (preparados com muito carinho por nossa equipe);
- Aqui você terá a oportunidade de desenvolvimento profissional com programas desenvolvidos pela empresa como o ACELERA THEOS.

## Como se candidatar

Por favor envie um email para carla.ferreira@theos.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Developer Angular.

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
