### ISSUE TITLE
[Remoto] Senior React Developer na Builders

### ISSUE THREAD

**Issue by laisbgebara** [frontendbr/vagas#6317]
Somos uma comunidade de pessoas que desejam aprender, evoluir, empreender e construir iniciativas que gerem valor. Nosso propósito é te ajudar a construir o seu legado e te dar insumos para solucionar problemas reais na prática. Trabalhe com autonomia e em qualquer lugar do mundo, o momento para se tornar Builder é agora! 💪

Ao ingressar na Builders, você fará parte de um movimento que idealiza, cocria e conecta pessoas. Desfrutando de um ambiente colaborativo que propicia oportunidade de crescimento exponencial. Se você está em busca de autonomia, liberdade e curte desafios, aqui é o seu lugar.

Aqui você terá espaço para expor suas ideias e dar opiniões, desafiando o status quo todos os dias! 😉

**Tecnologias que vão gerar valor nos projetos 💻:**

- React (Redux/Mobx);

- Fluência em TypeScript;

- APIs REST;

- Trabalhar com diferentes dimensões de dispositivo (tablet, celular, etc)

- Versionamento de código com Git;

- Conhecimento em arquitetura de software;
- Metodologias ágeis.

**O que te aproxima de ser uma Pessoa Builder 💪:**

- Conhecimento em Firebase (Analytics, Crashlytics, etc).

**Como Builder, você terá acesso a 👀:**

Oportunidades reais de empreender e impactar;

Fazer parte de uma comunidade de empreendedores; de ponta, o Movimento;

Inovação e criação liberados;

Participar de um processo único de geração de valor;

Contribuir na criação de métodos disruptivos;

Colocar suas ideias no mercado, na prática! :)

Possibilidade de Profit share em novos Negócios;

Prestador de Serviços (PJ).

Junte-se ao Movimento: https://jobs.kenoby.com/sejabuilder/job/senior-react-developer-cod-495-remoto/616d2f30dbc80926bb09daeb?utm_source=website

💛🖤

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
