### ISSUE TITLE
[Remoto] Frontend Developer (Pleno) na Samba Tech

### ISSUE THREAD

**Issue by mateu5-francisco** [frontendbr/vagas#6318]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/pessoa-desenvolvedora-frontend-pleno-124110631?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A Samba está buscando uma<strong> Pessoa Desenvolvedora Frontend</strong>  para agregar ao nosso time!</p>
<p>Para essa oportunidade buscamos uma pessoa para atuar em regime <strong>CLT e 100% remoto.</strong></p>
<p>Procuramos alguém com propósito forte e que esteja disposta a trabalhar em ambiente colaborativo e dinâmico, pronto para crescer profissionalmente junto com a nossa equipe fora da curva!</p>
<p>A Samba gosta de fazer a diferença sempre e nosso time é o responsável para que isto aconteça! Por isso, a gente espera que você seja uma pessoa apaixonada por tecnologia, assim com a gente!</p>
<p>Todas as nossas vagas também se aplicam a pessoas PCD, então fique à vontade para se candidatar!</p>

## Samba Tech: 
 <p>A Sambatech é uma das empresas mais inovadoras do mundo, segundo a Fast Company, e é referência no mercado de vídeos online. Nossa empresa garante infraestrutura de alta qualidade para venda, distribuição, gerenciamento e armazenamento de vídeos e ajuda pessoas e empresas a terem mais sucesso, independentemente do seu objetivo.</p>
<p>Com suas soluções, a Samba atende diferentes tipos de necessidades relacionadas aos conteúdos audiovisuais e possui uma equipe totalmente focada em assegurar que nossos clientes tenham acesso ao que há de melhor em tecnologia para vídeos online.&nbsp;&nbsp;&nbsp;</p><a href='https://coodesh.com/empresas/samba-tech'>Veja mais no site</a>

 ## Habilidades: 
 - React.js 
- HTML 5 
- Sass
## Local: 
 100% Remoto
## Requisitos: 
 - Desenvolvimento em Frontends e aplicativos web e integração de APIs REST 
- TML5, SCSS (de preferência SASS), Bootstrap, JAVASCRIPT (es6), 
- Linguagens de programação de fonte aberta como React, VueJS Git - Ambientes de nuvem 
- Integração e testes unitários.
## Diferenciais: 
 - Noções em Devops (uso de terminal Linux, containers Docker, processos de build e deploy automatizados, monitoria); 
- Noções de modelo de testes unitários e integrados 
- Noções de boas práticas de Engenharia de Software 
- Noções em infra-estrutura em nuvem na AWS ou equivalente; 
- Inglês intermediário
## Benefícios: 
 - Ambiente criativo e inovador; 
- Clima leve e descontraído; 
- Horário flexível; 
- Home office 
- Auxílio home office 
- Plano de Saúde; 
- Plano Odontológico; 
- Vale refeição/alimentação; 
- Gym Pass;  
- Day off no dia do aniversário 
- Seguro de vida; 
- Ways Education - Atividades extracurriculares para os filhos; 
- Previdência privada.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Developer (Pleno) na Samba Tech](https://coodesh.com/vagas/pessoa-desenvolvedora-frontend-pleno-124110631?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
