### ISSUE TITLE
[Americana - São Paulo] Front-End Developer na Retina Web

### ISSUE THREAD

**Issue by degaus** [frontendbr/vagas#632]
## Descrição da vaga
<ul>
<li> Desenvolver Temas em Wordpress; </li>
<li> Criação de E-commerce (woocommerce);</li>
<li>Hotsites;</li>
<li>Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sites; </li>
</ul>

## Local

Rua Gabriel Idálio de Camargo, 330 - Sala 05 - Vila Pavan - Americana / São Paulo

## Benefícios

- Plano de saúde
- VR 
- VT

## Requisitos

**Obrigatórios:**
- Experiência relevante em front-end
- Bons conhecimento em JavaScript/CSS frameworks
- Entender lógica do PHP
- Boa experiência em HTML5/CSS e na construção de websites responsivos/adaptáveis para mobile
- Conhecer o Básico de Wordpress
- Pacote Adobe

**Desejáveis:**
- conhecimento em criação de temas para wordpress
- SEO

**Diferenciais:**
- dominar o php
- NodeJS
- Gulp
- Bower

## Contratação

CLT

## Nossa empresa

Entendemos do mercado que atuamos, por isso, temos a confiança em dizer que oferecemos produtos com alto padrão de qualidade, linguagem moderna, leve, objetiva e acessível a todas as tecnologias, 

## Como se candidatar

Por favor envie um email para luis@retinaweb.com.br com seu CV anexado - enviar no assunto: Dev. Front

**Comment by degaus** [comment]
Tags:
CLT
Alocado
Júnior
Pleno

**Comment by LFeh** [comment]
Americana ❤️

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
