### ISSUE TITLE
[Remoto] Fullstack Developer na Solubio Tecnologias Agrícolas

### ISSUE THREAD

**Issue by mateu5-francisco** [frontendbr/vagas#6320]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-senior-full-stack-191918023?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>Sobre a SoluBio: </strong>A SoluBio é uma spin-off da Agroplan, empresa de serviços focada em consultorias, assessorias e agricultura de precisão que atua desde 2007 e em meados de 2012 iniciou o MVP do que em 2016 se tornaria a Solubio. Desde o início, o foco do projeto foi levar a seus clientes alternativas mais sustentáveis e econômicas na atividade rural Com o aprendizado constante no campo, o feedback dos produtores e a parceria com doutores, institutos de pesquisas e universidades a SoluBio criou um sistema integrado de Manejo Biológico OnFarm®️​ com padrão industrial chamado Solubio Experience: LabFarm, BioFábrica OnFarm, SoluFarm e Suporte OnFarm.</p>
<p>Nossa tecnologia de produção de biodefensivos na fazenda permitiu que nossos produtores reduzissem seus custos em até 40% nos cultivos de soja, milho, trigo, algodão, cana, café e horti-fruti.<br></p>
<p><strong>Sobre a pessoa Fullstack Developer e suas principais atividades:</strong> Desenvolvimento de soluções Mobile, WEB, back end, Front end e IOT das plataformas de tecnologia e inovação SoluBio. Demais atividades inerentes ao cargo.<br></p>
<p><strong>Quais Soft Skills buscamos em você: </strong>Que seja focado e orientado a metas e resultados. Que saiba trabalhar em ambientes acelerados e sob pressão. Que tenha habilidade de comunicação para interagir com outras áreas e pessoas. Que seja entusiasta e comprometido. Que tenha foco em trazer soluções e vislumbrar oportunidades. Que seja organizado.&nbsp;</p>
<p><strong>Sonho Grande: </strong>Se proporcionar sustentabilidade ao agronegócio garantindo a preservação do planeta e das futuras gerações faz sentido para você, venha fazer parte do nosso Sonho Grande.</p>

## Solubio Tecnologias Agrícolas: 
 <p>A Solubio é uma spin-off da Agroplan, empresa de serviços focada em consultorias, assessorias e agricultura de precisão que atua desde 2007 e em meados de 2012  iniciou o MVP do que em 2016 se tornaria a Solubio. Desde o início, o foco do projeto foi levar a seus clientes alternativas mais sustentáveis e econômicas na atividade rural.</p>
<p>Com o aprendizado constante no campo, o feedback dos produtores e a parceria com doutores, institutos de pesquisas e universidades  a Solubio criou um sistema integrado de manejo biológico OnFarm com padrão industrial chamado Solubio Experience: (i) LabFarm, (ii) BioFábrica OnFarm, (iii), SoluFarm e (iv) Suporte OnFarm.</p><a href='https://coodesh.com/empresas/solubio-tecnologias-agricolas'>Veja mais no site</a>

 ## Habilidades: 
 - Test Driven Development 
- Java 
- Typescript
## Local: 
 100% Remoto
## Requisitos: 
 - Bacharelado em Ciência da Computação ou áreas correlatas; 
- Requisitos Backend: NodeJS, Typescript Nest.JS, Mocha Jest. 
- Requisitos de Frontend: HTML/CSS Angular ou React. 
- Desejável: Design Patterns Microservices, Devops, Apps Services, Kubernetes.
## Diferenciais: 
 -  Experiência com HTML, Typescript, TDD, CSS, Node JS. Java, Mocha, Nestjs, Ionic e Flutter, testes unitários, TDD, SOLID, hexagonal ou clean archtecture, desenvolvimento Mobile, Android e IOS, forte conhecimento em front end e back end.
## Benefícios: 
 - Cartão Beneficio  
- Plano de Saúde Nacional 
- Previdência Privada (Não Obrigatório)
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack Developer na Solubio Tecnologias Agrícolas](https://coodesh.com/vagas/desenvolvedor-senior-full-stack-191918023?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Categoria
Back-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
