### ISSUE TITLE
[REMOTO] Pessoa Instrutora de Ensino Front-end na Cubos Academy

### ISSUE THREAD

**Issue by eliprovesi** [frontendbr/vagas#6321]
## Nossa empresa

➡ A **Cubos Academy** é uma escola de **formação de profissionais da área de tecnologia**. Fomentamos o mercado de tecnologia, qualificando novos profissionais e intermediando sua entrada no mercado de trabalho, contando com uma área especializada na empregabilidade dos nossos alunos.

## Descrição da vaga

🏃Buscamos uma pessoa com **experiência em Frontend,** em níveis de carreira: **Júnior, Pleno ou Sênior,** que goste de compartilhar conhecimento e acredite no potencial transformador da educação na vida das pessoas! Essa pessoa irá compor nosso time da **área de Pedagógico** e estará em constante comunicação com o time e acompanhando o desenvolvimento e evolução dos nossos alunos.
 
➡ Se você gosta de ensinar e contribuir para o desenvolvimento das pessoas essa vaga é pra você! 💪🏻

#VempraCubosAcademy🚀

## 🌎 Local
Remoto

## 📚 Responsabilidades e atribuições: 

◾ Impactar diretamente na formação de novas pessoas desenvolvedoras através da instrução dos conteúdos de Front-end;
◾ Criar, projetar e resolver exercícios e projetos que serão praticados durante o processo de aprendizagem de nossos estudantes; 
◾ Sanar dúvidas dos estudantes e orientá-los nos projetos e desafios propostos pelo curso;
◾ Preparar materiais e conteúdos, aulas ao vivo focando em pontos que o mercado realmente valoriza em uma pessoa desenvolvedora;
◾ Preparar aulas de revisão para os estudantes, com o intuito de sanar dúvidas que foram recorrentes durante as aulas anteriores;
◾ Mentorear e acompanhar o desempenho e o desenvolvimento da turma;
◾ Participar das reuniões de acompanhamento da turma junto ao time de experiência do estudante;
◾ Acompanhar e dar suporte às pessoas monitoras ao longo do curso;
◾ Participação na idealização e estruturação de novos cursos da Cubos Academy.

## 🏅Requisitos

**Obrigatórios:**

◾ Boa comunicação oral e escrita;
◾ Gostar de ensinar e aprender;
◾ Conhecimento em HTML, CSS e Javascript (ES6+);
◾ Experiência com React, Vue.js, Angular ou Svelte;
◾ Experiência consumindo bancos de dados relacionais;
◾ Conhecimento em versionamento com Git;
◾ Disponibilidade de dedicação de 40 horas semanais.
 
  
🍒**Cerejas do bolo, mas tudo bem se não tiver, nem todo bolo tem cereja:**
 
◾ Experiência anteriores ministrando aulas (qualquer área);
◾ Gostar de ensinar e desenvolver pessoas;
◾ Já ter trabalhado com algum produto de educação;
◾ Experiência sólida com React;
◾ Conhecimento em Typescript;

## ❤ Nossos Benefícios

◾ Plano de Saúde Bradesco (custeado 100% por nós) (CLT)
◾ Plano Odontológico Bradesco (CLT)
◾ Cartão de benefícios Flexíveis Flash: para você escolher onde usar (CLT)
◾ Day Off para o aniversariante em qualquer dia do mês para curtir como quiser (CLT + PJ)
◾ Gympass: para você cuidar do seu corpo e saúde (CLT + PJ)
◾ Licença Parental estendida (CLT + PJ)
◾ Licença Casamento estendida (CLT + PJ)

🔎 **O que mais você encontra aqui:**

◾ Participação em Trilhas de Conhecimento
◾ Programa Pause: para ao longo do dia você não se esquecer de respirar novos ares, se alongar e dar uma pausa.
◾ Horário semi-flexível: dentro do horário comercial
◾ Home-office permanente
◾ Oportunidade de trabalhar em uma startup com um ambiente colaborativo, dinâmico e repleto de desafios.

👣 Etapas do Processo Seletivo:
◾ Inscrição
◾ Desafio Técnico
◾ Entrevista Comportamental e Técnica
E só! 😉

🧡 A Cubos tem o compromisso de tornar o mundo do trabalho mais diverso e inclusivo. Por conta disso, durante o processo priorizaremos mulheres (cis ou trans), pessoas com deficiência, pessoas negras, indígenas ou quilombolas;

## Contratação

PJ | CLT: você escolhe 😊

## Como se candidatar

Se inscreva no link 👉 https://cubosacademy.gupy.io/jobs/1458968 

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by Djamess** [comment]
acabei de me inscrever
