### ISSUE TITLE
[Remoto] Software Engineer Frontend - Angular na Nuvemshop

### ISSUE THREAD

**Issue by RafaMagal** [frontendbr/vagas#6323]
## Nossa empresa

**Sobre Nuvemshop**
Somos a plataforma de e-commerce líder na América Latina que, desde 2010, trabalhamos com um propósito muito claro: potencializar e motivar pessoas empreendedoras que querem transformar seus sonhos em histórias que transcendem.

Sim, o desafio é enorme, porque gostamos de pensar grande!

Para isso, priorizamos o bem-estar de clientes e de todas as pessoas que fazem parte da Nuvemshop, desde Argentina, Brasil e México.
Nossa cultura é sobre pessoas e é a alma do nosso negócio. Temos uma cultura muito forte, na qual cuidamos todos os dias e valorizamos a excelência, transparência, autonomia, a diversidade e a colaboração.

Devido ao compromisso de todo o time, clientes e parceiros. Em 2021, nos tornamos a 5ª startup mais valiosa da América Latina, atingindo um valor de mais de 3 bilhões de dólares. Isso nos leva a continuar trabalhando para reduzir ao máximo as barreiras ao empreendedorismo em toda a América Latina.

## Descrição da vaga

**O tamanho do seu desafio**
- Desenvolver garantindo funcionalidade, manutenibilidade e velocidade, além de práticas de teste e qualidade;
- Empregar boas práticas na construção do software, buscando otimizar e medir a performance do projeto e das funcionalidades que estão sendo desenvolvidas;
- Garantir que todas as soluções técnicas estejam alinhadas a estratégia do negócio, OKRs e iniciativas relacionadas ao ecossistema;;
- Ajudar o time no desenho de soluções com arquitetura evolutiva, além de investigar constantemente novas tecnologias e formas de trabalho;
- Construir e manter novas funcionalidades visando desenvolver uma aplicação segura e escalável.

**O que buscamos**
- Estamos contratando para diferentes senioridades: júnior, pleno e sênior;
- Experiência com desenvolvimento Frontend. Nossas principais tecnologias utilizadas são React.js e Angular. Você não precisa necessariamente ter experiência com essas stacks, mas valorizamos muito o interesse em aprender;
- Experiência com Redux ou algum modelo de dados semelhante;
- Experiência com SCSS/CSS Modules ou outras ferramentas para construção de layouts e interfaces gráficas para web;
- Vivência em desenvolvimento de microsserviços distribuídos;
- Experiência com boas práticas de desenvolvimento (DDD, TDD, arquitetura, design de código, paradigmas, etc.) e preocupação com a excelência técnicas das soluções;
- Conhecimento de metodologias ágeis;
- Pragmatismo para resolução de problemas;
- Consideramos um diferencial se você participar de comunidades de tecnologia (palestras, meetups, eventos, tech talks, blogs, etc.), porque valorizamos muito a troca de conhecimentos e experiências!

## Local
Remoto

## Requisitos
- Experiência com desenvolvimento Frontend. Nossas principais tecnologias utilizadas são React.js e Angular. Você não precisa necessariamente ter experiência com essas stacks, mas valorizamos muito o interesse em aprender;
- Experiência com Redux ou algum modelo de dados semelhante;
- Experiência com SCSS/CSS Modules ou outras ferramentas para construção de layouts e interfaces gráficas para web;
- Vivência em desenvolvimento de microsserviços distribuídos;
- Experiência com boas práticas de desenvolvimento (DDD, TDD, arquitetura, design de código, paradigmas, etc.) e preocupação com a excelência técnicas das soluções;
- Conhecimento de metodologias ágeis;
- Pragmatismo para resolução de problemas;
- Consideramos um diferencial se você participar de comunidades de tecnologia (palestras, meetups, eventos, tech talks, blogs, etc.), porque valorizamos muito a troca de conhecimentos e experiências!

## Benefícios
- Plano de Saúde, Plano Odontológico e Seguro de Vida;
- Flash Benefícios: Plataforma que reúne vale alimentação, vale refeição e outras categorias como educação, entretenimento, cultura, saúde, bem-estar, auxílio home office e muito mais;
- Vale Transporte ou Vale combustível - atualmente estamos 100% remotos, por isso esse benefício está suspenso até a volta para o escritório;
- Aulas de espanhol semanais gratuitas;
- Licença de família estendida para 21 dias corridos para pessoas não grávidas ou adotantes. A licença maternidade é de 4 meses e a licença parental de 21 dias. O benefício também vale para famílias que adotarem ou obtiverem a guarda judicial da criança e para casais homoafetivos;
- Uma Nuvemshop gratuita para você ou pessoa próxima;
- Um ambiente com muito aprendizado, propósito e autonomia - Aqui você é livre para ser você!

## Contratação
CLT

## Como se candidatar

Para se candidatar acesse: https://bit.ly/3fI7MMd

## Tempo médio de feedbacks
**Nosso processo**
Na Nuvemshop temos como propósito criar a melhor plataforma de e-commerce e por isso, precisamos formar time de alto impacto. Dessa forma, investimos muito tempo e atenção em nosso processo seletivo.

Após a inscrição, seu perfil será avaliado pela equipe de Talent Acquisition e enviaremos feedback independente do resultado desta etapa. Os tempos e as etapas do nosso processo são flexíveis de acordo com cada área, mas não se preocupe, pois sempre o manteremos informado do andamento da sua inscrição por e-mail.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by TheAleSch** [comment]
Se a vaga é para senior e especialista porque colocou a tag junior?

**Comment by heltonWilekeDarosci** [comment]
No longer available!

**Comment by mrsants** [comment]
nao tem essa vaga no link

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
