### ISSUE TITLE
[Remoto] Front-End Developer (VTEX) na Enext Consultoria

### ISSUE THREAD

**Issue by Techrecruiterenext** [frontendbr/vagas#6328]
## Nossa empresa

A Enext é uma consultoria e agência digital, formada por um time super engajado que tem hoje aproximadamente 200 pessoas, extremamente competentes e focadas nas entregas com excelência para alcançar os melhores resultados para os nossos clientes. É esse comprometimento que nos torna referência nas melhores tecnologias do mercado de desenvolvimento de e-commerce como: Salesforce, Oracle, Magento e Vtex!

Temos como base a missão de ser referência no desenvolvimento do mercado digital, oferecendo oportunidades para os nossos colaboradores e entregando resultados excelentes para nossos clientes!

Você está em busca de desenvolvimento e quer aprender através de projetos DESAFIADORES? Aqui na Enext Consultoria, nós TRANSFORMAMOS as PESSOAS para o FUTURO! Vem crescer com a gente!

## Descrição da vaga
Programar demandas complexas dentro dos clientes do seu núcleo;
Realizar a análise de métricas e fazer o report à coordenação;
Desenvolvimento e manutenção de lojas virtuais em diversas plataformas (VTEX, OCC, Magento, etc);
Criação e programação de landing pages;
Consumo de serviços de terceiros (ex. API de catálogo de produtos);
Ajuste de features existentes nos projetos;
Criar e realizar a manutenção de conteúdos dinâmicos via CMS;
Implementar tags de GTM
Realizar integração entre sistemas (ex. landing pages com ferramentas de CRM, sistemas de e-commerce com ERPs).

## Local
[Remoto]

## Requisitos

**Obrigatórios:**
 Experiência com a plataforma VTEX

## Benefícios

- Vale Refeição ou Vale Alimentação (você escolhe o que é melhor!);
- Seguro Saúde Porto Seguro Bronze: a empresa custeia 100% e não tem co-participação por utilização;
- Auxílio Home Office;
- Seguro Odontológico - Porto seguro (opcional);Horário Flexível;
- Parceria com universidades para descontos e vantagens exclusivas;
- Descontos e vantagens em academias, agências de turismo, clínicas de beleza e estética, escolas de idiomas, restaurantes e em diversos outros serviços e estabelecimentos;
- Acesso gratuito à plataforma Enext College (Programa de aperfeiçoamento e conhecimento disponível para todos os colaboradores Enext
- PAE (Programa de Apoio ao Empregado) de auxílio com questões jurídicas, sociais, administração financeira e psicológicas;
- Acesso gratuito à Plataforma ILearn (WPP) com cursos internos e vínculo com o Linkedin Learning, Interface com outras empresas do grupo e oportunidades internacionais.
- Auxílio para Certificações em plataformas parceiras (Salesforce, Vtex, Google, Amazon, MeLi, etc.).

## Contratação

CLT

## Como se candidatar

Link da nossa página de carreiras: https://jobs.kenoby.com/enext/job/desenvolvedor-front-end-pleno-remoto/61e5ada053bd501eb57a1f03?utm_source=website

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
