### ISSUE TITLE
[Curitiba] Desenvolvedor Full Stack Sênior - Vue.js - na Leads2b -  Alocado

### ISSUE THREAD

**Issue by jeffersonllopes** [frontendbr/vagas#633]
## Descrição da vaga

Irá trabalhar em sinergia com os demais desenvolvedores, auxiliando nas melhorias e correções da plataforma. 

## Local

**Alocado** - Curitiba - PR - Bairro Bigorrilho 

## Benefícios

- Seguro de vida
- VR de R$ 16,50/dia
- VT

#### Diferenciais

- 1:30 hora de almoço
- ambiente informal
- equipe extremamente jovem

## Requisitos

**Obrigatórios:**
Domínio de Javascript ECMAScript 6
- Conhecimentos avançados em VueJS 2
- Conhecimentos em NodeJS (Loopback, GraphQL)
Desejável conhecimento em Python
Conhecimentos em frameworks híbridos será um diferencial (Ionic, Quasar)
Mysql, MongoDB

**Diferenciais:**
- Projetos avançados em VueJS 2
- Google BigQuery 

## Contratação

CLT ou PJ (a combinar)

## Nossa empresa

Somos uma empresa Jovem que esta alcançando um grande espaço no mercado, desenvolvendo produtos com máxima tecnologia, nossa equipe é composta de um time apaixonado por tecnologia.

## Como se candidatar

Por favor envie um email para jefferson.lopes@leads2b.com com seu CV anexado - enviar no assunto: Vaga Desenvolvedor Full Stack Vue.js

**Comment by LFeh** [comment]
Aberto ainda?
