### ISSUE TITLE
[Remoto] Front-end Developer na Viaflow

### ISSUE THREAD

**Issue by Viaflow-Tech** [frontendbr/vagas#6335]
> Vaga Remota durante a pandemia

## Nossa empresa

Na Viaflow, somos um time apaixonado por tecnologia. E somos GPTW!

Isso é resultado de um time que acredita que TODOS somos responsáveis por construir um ambiente cada vez mais incrível para se trabalhar.

Aqui, nós acreditamos que empresas de sucesso se diferenciam pelos seus talentos e uso de tecnologias inovadoras. Acreditamos que as pessoas são a chave para a transformação.

Por isso, trabalhamos com muita energia, respeitamos as diferenças e estimulamos a diversidade! A nossa palavra predileta é COLABORAÇÃO.

 A Viaflow é sem fronteiras e isso também nos torna ainda mais especiais.

## Descrição da vaga

Você gosta de inovação e curte resolver demandas complexas? Nós também! Por isso, estamos em busca de profissionais inovadores e criativos, que gostem de atuar em times de alta performance e busquem grandes desafios nas suas carreiras. Aqui, na Viaflow, temos um lugar especial esperando por você!

Essa oportunidade é para atuação em um dos nossos clientes, uma empresa brasileira de emissão de passagens aéreas . Unindo tecnologia avançada à uma excelente equipe, a empresa está crescendo e demonstra a necessidade de inovar e oferecer bons preços e atendimento de qualidade para os clientes.

## Local

Remoto enquanto pandemia. Pós em Belo Horizonte- MG
## RESPONSABILIDADES E ATRIBUIÇÕES
Desenvolvimento de software aplicando as boas práticas de codificação e padrões de projeto sempre pensando em sustentabilidade, segurança, escalabilidade e custo;
 Auxiliar na análise e elaboração de arquitetura dos requisitos que serão desenvolvidos no projeto;
Apoiar o desenvolvimento profissional de juniores do time de front-end;
 Documentação das arquiteturas propostas;
 Realização de revisões de código para garantir artefatos padronizados e de qualidade;
 Orientação nas implementações de testes automatizados;
 Sugestão de modelos de desenvolvimento que aumente a qualidade dos produtos e a agilidade dos times.
 Aplicar e difundir as boas práticas de segurança no projeto
 Garantir que as soluções propostas sejam adequadas a política de custos de projetos da companhia.
## Requisitos
Conhecimento de NextJS
Experiência com AngularJS
Experiência com Typescript
Experiência com Bundlers e module federation (webpack, rollup, gulp ...)
Experiência em ecommerce / aplicações B2C
Boas noções de UX
Experiência com CI/CD. (github actions, dangerjs, linting, chromatic)
Experiência com SEO
Sólido conhecimento em HTML, CSS, e ReactJs.
Conhecimento em mais de um framework frontend (Vanilla, AngularJS, Angular, Vue, etc)
Experiência com projetos de arquitetura de software.
Boa experiência no desenvolvimento de aplicações responsivas.
Conhecimento de testes unitários
Conhecimento e experiência com web vitals

## Benefícios

Diferenciais:
Carreira Acelerada
#Liberdade: Trabalhe de onde quiser
Horários flexíveis
Vitalk
Auxílio UYOD
Programa Finder
Indicação Premiada
DIT
Happy hours e festas com atrações;
Dress Code livre;
Day off de aniversário.
Descanso remunerado.

## Contratação

Cooperativa 3%

## Como se candidatar

Cadastre-se em nossa página de carreira: https://viaflow.gupy.io/jobs/1473047

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.
E-mail para contato em caso de não haver resposta: gestaodepessoas@viaflow.com.br
#### Alocação
- Alocado
- Remoto durante pandemia

#### Regime
Cooperativa

#### Nível

- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
