### ISSUE TITLE
[Híbrido- São Paulo] Front-end Developer na BRQ Digital Solutions

### ISSUE THREAD

**Issue by ReAnne123** [frontendbr/vagas#6339]
Sobre a BRQ Digital
Há 28 anos no mercado, a BRQ Digital Solutions se consolidou como uma das maiores empresas de transformação digital do país. Com uma plataforma de serviços end to end, oferecemos as mais eficientes e inovadoras soluções, tecnologias e metodologias, promovendo uma jornada de transformação para grandes marcas, de diferentes segmentos, no Brasil e no exterior. Nossos 3 mil funcionários atuam no modelo de trabalho Anywhere Office e a empresa é destaque como um dos melhores lugares para trabalhar pelo GPTW e Glassdoor.

Descrição da vaga
Front End Developer 
ANGULAR 8
- SPA / Angular / cloud (noções – Paas e Iaas) / microserviço / comunicação entre APIs / rest api / GIT / HTML / Javascript / Node / CSS 
Vivência em projetos com metodologia Ágil.
Profissional trabalhará em uma Squad que fará desenho e desenvolvimento de um novo portal.

CLT pela BRQ para integrar o time de um grande banco.

Local
Até 3 x presencial em Interlagos- São Paulo (estação de trem Jurubatuba) e 2 remoto.

Requisitos
Obrigatórios:
- SPA / Angular / cloud (noções – Paas e Iaas) / microserviço / comunicação entre APIs / rest api / GIT / HTML / Javascript / Node / CSS 

Benefícios
Plano de saúde Bradesco
Seguro de vida
VR e Vale Alimentação
Previdência privada
Plano odonto
Gympass
Telemedicina
Telenutrição
Programa de incentivo a certificações

Contratação
CLT pela BRQ para integrar o time de um grande banco.

Como se candidatar
Por favor envie um email para Renata (ryokota@brq.com) com seu CV anexado - enviar no assunto: Vaga Angular Híbrida.

Tempo médio de feedbacks
Costumamos enviar feedbacks em até 20 dias após cada processo.
E-mail para contato em caso de não haver resposta: ryokota@brq.com

Alocação
Alocado
Remoto

Regime
CLT

Nível
Pleno
Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
