### ISSUE TITLE
[Curitiba] Front-End Developer na Bluefoot

### ISSUE THREAD

**Issue by jamirmachado** [frontendbr/vagas#634]
## Descrição da vaga

Se você é apaixonado por desenvolvimento web e consegue resolver problemas lógicos de maneira ágil e inteligente, como front-end developer aqui na Blue você vai ter a oportunidade de imaginar, prototipar e desenvolver aplicações para um dos mais parrudos ecossistemas de ecommerce da América Latina para atender grandes marcas do mercado brasileiro no Chile e nos Estados Unidos.

## Local

Curitiba

## Benefícios

- Plano de saúde
- Plano odontológico
- VT/VR
- Horário semi flexível

#### Diferenciais

- Ambiente descontraído com dress code informal (você pode vir trabalhar de bermuda se quiser)
- Sala de jogos com PS4 e uma máquina de fliperama para tirar uns contras
- Máquina de espresso livre
- Happy hours, festas e churrascos estão no nosso dia-dia

## Requisitos

**Obrigatórios:**
- Sólidos conhecimentos de ES6 e React
- Experiência com WS e API's
- Experiência com Git
- Boa comunicação e gostar de trabalhar em equipe

**Desejáveis:**
- Experiência com Agile
- Experiência com NodeJS e Redux

## Contratação

CLT

## Como se candidatar

Por favor envie um email para front@bluefoot.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Developer JS

**Comment by jamirmachado** [comment]
Tags:
Alocado
CLT
Pleno

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
