### ISSUE TITLE
[Híbrido - São Paulo] Angular Developer na Avanade

### ISSUE THREAD

**Issue by whoisphilip** [frontendbr/vagas#6343]
## Nossa empresa

A Avanade é a consultoria líder em soluções inovadoras de digital e nuvem, soluções de negócios e experiências que levam design aos nossos clientes, entregues por meio do poder das nossas pessoas e do ecossistema Microsoft. Fazemos tudo aquilo que você espera de uma empresa líder em inovação digital, mas é o que você não espera o que nos torna diferente.  Somos 36.000 pessoas conectadas em 24 países, construindo histórias e fazendo acontecer. 

Sabemos que o trabalho não é sua única paixão e colocamos nosso valor em você - sua carreira, seus objetivos e seu desenvolvimento, para que você possa ser a sua melhor versão. 

## Descrição da vaga
Nesse cargo, você contribuirá...

Na melhoria e suporte dos produtos de softwares existentes para adicionar novas funções, desempenho e usabilidade do produto. Além de ser responsável pela leitura de requisitos de negócios, criação de casos de testes, bibliotecas de scripts de testes, acompanhamento de bugs. Você também irá auxiliar na criação de frameworks de testes e no ciclo de vida do desenvolvimento de sistema.

## Local
Híbrido, São Paulo - região de Interlagos

## Requisitos

**Obrigatórios:**
Você irá trabalhar com desenvolvimento front-end focando principalmente em Angular  e JavaScript. Também trabalhará com tecnologias como HTML5, DOM, CSS3, Sistemas de Controle de Versões (Git e SVN) e estar ambientado com testes unitários, seguindo metodologias de gestão de projetos incluindo Ágil. Além disso, ter uma boa comunicação é um fundamental pois você irá interagir muito com os nossos clientes e seus colegas de trabalho no dia a dia.

**Diferenciais:**
Tiver conhecimento com Sistemas de Controle de Versões (Git e SVN) e consumo de API’s RESTful. Além de Node.js e Javascript (ES6 e TypeScript). Inglês intermediário também seria um diferencial, somos uma empresa Global e você pode ter interação com pessoas do mundo todo! Mas, caso você não possua esses desejáveis, fica tranquilo(a), você pode desenvolver tudo isso aqui dentro.

## Benefícios

- Vale refeição ou alimentação;
- Vale transporte ou fretado;
- Assistência médica e odontológica;
- Telemedicina; 
- Telepsicologia;
- Seguro de Vida;
- Previdência Privada;
- EF – Inglês;
- Avababy: acompanhamento da gestação e kit para os novos pais e mães Avanade; 
- Horários flexíveis; 
- Participação nos resultados da empresa; 
- Gympass; 
- Auxílio creche;
- Avaliação formal de performance e carreira;
- Buddy – aquela pessoa que irá te ajudar nos seus primeiros meses e na fase de adaptação à nossa cultura;

**Diferenciais:**
- Career Advisor (um braço direito para orientar a sua carreira);
- Exposição com times globais a depender do projeto;
- Job Rotation (possibilidade de rotacionar entre projetos, conhecer mais tecnologias e diversos segmentos de mercado);
- Certificações da Microsoft 100% gratuitas; 

## Contratação

CLT

## Como se candidatar

Por favor se cadastre no nosso site de carreiras: https://careers.avanade.com/jobsenusurl/JobDetail/Desenvolvedor-a-Angular-Pleno/42645

## Dúvidas 
Caso surjam dúvidas, estes são os contatos da equipe da Avanade: 
[Linkedin 
](https://www.linkedin.com/in/fellipe-brancaccio/)
[Email](mailto:fellipe.da.silva@avanade.com)

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
