### ISSUE TITLE
[Remoto] Mobile React Native na Nave.rs

### ISSUE THREAD

**Issue by BrunaSouzaPaes** [frontendbr/vagas#6347]
> Vaga Remota durante a pandemia

## Nossa empresa

Trabalhar com a nave.rs significa que você conhece e colabora com as pessoas que realmente fazem o trabalho. Unimos tecnologia e criatividade para criar soluções digitais efetivas que se tornam memoráveis e impactam positivamente a vida das pessoas.

Nossa missão é ajudar empresas a entender antes de agir, a agir com precisão e a lucrar a partir de mudanças.

Não é somente sobre produtos digitais, é sobre marcar positivamente a vida das pessoas

## Descrição da vaga

A Nave.rs está procurando uma pessoa com perfil de nível júnior a pleno, que tenha experiência na área de desenvolvimento mobile react native, experiência com clientes e projetos.

Como pessoa desenvolvedora para a área de Mobile, você irá utilizar linguagem React . Na empresa trabalhamos com a metodologia ágil Scrum, sendo assim, temos cerimônias como planning, weekly e retro. O seu dia a dia de trabalho irá basear-se nas cerimônias e no projeto que você irá entrar.

Dessa forma, procuramos uma pessoa que seja comprometida com sua evolução, que tenha ideias inovadoras, tenha proatividade e pense fora da caixa. É importante que você goste de se comunicar e trabalhar em equipe, já que aqui temos um ambiente super colaborativo. Ao mesmo tempo, valorizamos que cada membro do time seja autônomo para gerir suas demandas.

## Local

Remoto 

## Requisitos

**Obrigatórios:**
- Javascript
- ReactJS
- React Native
- Styled Components
- Boa comunicação
- Experiências com Projetos

**Diferenciais:**
- Context API;
- Hooks;
- Conhecimento básico na stack iOS e Android para o desenvolvimento com React Native
- Flutter

## Benefícios

- Assistências médica e odontológica;
- Auxilio psicológico;
- VR \ VA de R$ 24,10/dia
- Aulas de inglês;
- Auxilio Educação (acesso a plataformas de cursos)
- Horário flexível e possibilidade de home office.

**Diferenciais:**
- Plano de carreira
- Horário Flexível 

## Contratação

CLT + Benefícios 

## Como se candidatar

Inscreva-se através do link: https://nave-team.gupy.io/jobs/1477238

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: bruna.paes@nave.rs 

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by nerdstarcode** [comment]
Estariam procurando algum estagiário? Estou começando na área agora, cheguei a fazer umas pesquisas na área e criei um app To do list, mas como estou iniciando não sei se estaria no nível Júnior, mas aprendo rápido e sou bem comprometido com minha aprendizagem

**Comment by Djamess** [comment]
pode fechar a vaga se já esta encerrada as inscrições...

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
