### ISSUE TITLE
[VAGA FECHADA] [Home office] Front-end Developer na ASSESSO

### ISSUE THREAD

**Issue by RecrutamentoAssesso** [frontendbr/vagas#6349]
## Nossa empresa

A Assesso é uma empresa de tecnologia com mais de 40 anos de atuação no mercado brasileiro.

Inicialmente operou como desenvolvedora de sistemas sob medida, tendo se especializado em projetos com grande volume de dados e necessidade de grande performance.

A partir de 1985, por meio de profunda parceria com a Editora Abril, passou a operar na gestão de cadastros e nos processos de qualidade da informação.

Em 1999, lançou no mercado seu software de Qualidade de Dados – o DataCare – hoje líder neste mercado, que está instalado e operando em mais de 100 grandes empresas brasileiras e multinacionais dos mais variados setores.

A partir de 2002, criou metodologia própria, após a certificação obtida pelo seu Presidente Flávio de Almeida Pires nas técnicas do TDQM – Total Data Quality Management, ministrado pelo MIT – Massachusetts Institute of Technology, instituição com a qual mantém até hoje forte relacionamento.

Atualmente, a Assesso é referência no mercado brasileiro de Qualidade e Governança de Dados, aí incluídas as áreas de Big Data e MDM – Master Data Management, tendo evoluído à frente do mercado com a moderna visão da informação como um valioso ativo das empresas, merecendo estrutura especializada para a sua contínua evolução e qualidade.

Nossa Missão
Prover soluções eficientes e inovadoras para a gestão e a qualidade da informação, permitindo sua utilização como diferencial estratégico e competitivo, de modo a agregar valor aos negócios dos nossos clientes.

Nossa Visão
Ser reconhecida como a melhor empresa provedora de soluções de gestão e qualidade da informação do mercado brasileiro, e contribuir de forma efetiva para a eficiente utilização das informações pelos nossos clientes, visando o incremento dos seus negócios.

Nossa Valores
Ética, transparência e integridade;
Respeito no tratamento com clientes, colaboradores e parceiros;
Conhecimento técnico e experiência.

Site
http://www.assesso.com.br

## Descrição da vaga

Estamos em busca de uma Pessoa Desenvolvedora Frontend React para realizar a manutenção, evolução e desenvolvimento de novos módulos da plataforma DataCare.

## Local

Home office

## Requisitos

**Obrigatórios:**
•	Experiência com ReactJS
•	Experiência com HTML, JavaScript, CSS e TypeScript
•	Experiência com integração REST
•	Utilização de boas práticas de desenvolvimento e testes 
•	Conhecimento em Maven e Git.
•	Idioma: inglês técnico
•	Superior Completo em Ciência da Computação, Análise de Sistemas, Engenharias e afins

**Desejável conhecimento em:**
•	Conhecimentos das bibliotecas Material-UI, Ant Design, Redux e Axios
•	Experiência em conversão de sistemas monolíticos para arquitetura de microsserviços
•	Conhecimentos básicos em desenvolvimento Java EE (JSP, JSF, JPA, Web Service, etc).
•	Framework Spring Boot
•	CI – Integração Contínua / CD – Delivery Contínuo
•	Containers e microservices
•	Experiência em desenvolvimento de aplicações com layout responsivo

**Diferenciais oferecidos:**
- Gympass
- Seguro de vida
- MDS (Plataforma de seguros com descontos especiais para os integrantes do time da Assesso)
- Oportunidade de desenvolvimento profissional

## Contratação

PJ

## Como se candidatar

Por favor envie um email para rh@assesso.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@assesso.com.br

#### Alocação
- Home office

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
