### ISSUE TITLE
[São Paulo/SP] Fullstack Front-End Developer | GTCON

### ISSUE THREAD

**Issue by rosepereira01** [frontendbr/vagas#635]
## Descrição da vaga
Experiência no desenvolvimento de aplicações IOs e Android híbridos, utilizando Ionic com Cordova para integrações com funcionalidades nativas dos dispositivos. Experiência com notificações via Push, cache de requests REST, utilização de banco local/localstorage. 

## Local

Cliente na Av. Paulista - São Paulo

## Benefícios

- Plano de saúde e Odontológico - AMIL
- VR de R$ 20/dia
- VA de R$495,00

## Requisitos
Conhecimentos necessários: AngularJS 2 Restangular ou similares Ionic (preferencialmente Ionic 2) Ferramentas de build, preferencialmente Gulp Bower/npm Temas Bootstrap ou similares Git HTML5, SASS, Javascript Typescript e orientação a objetos Cordova APIs Rest SQLite, indexedDB, WebSQL e similares.

**Obrigatórios:**
- 3 anos de experiência com Mobile

**Desejáveis:**
Conhecimentos em:
Java 1.6 e superior 
Spring IoC, Security, MVC 
Spring Boot 
JPA / Hibernate 
APIs Rest 
Webservices SOAP

## Contratação
CLT

## Nossa empresa
GTCON Empresa de Tecnologia da Informação 

## Como se candidatar

Por favor envie um email para rose.pereira@email.com.br com seu CV anexado - enviar no assunto: Vaga FULLSTACK

**Comment by LFeh** [comment]
Qual o nome da empresa que a pessoa ficará alocada?

**Comment by rosepereira01** [comment]
Olá Felipe! 
Obrigada pelo contato. 
Por enquanto não posso abrir o cliente, mas fica bem próximo do metrô da consolação. 
Muito obrigada 



De: "Felipe Fialho" <notifications@github.com> 
Para: "frontendbr/vagas" <vagas@noreply.github.com> 
Cc: "rosepereira01" <rose.pereira@gtcon.com.br>, "Author" <author@noreply.github.com> 
Enviadas: Terça-feira, 31 de outubro de 2017 17:15:15 
Assunto: Re: [frontendbr/vagas] [São Paulo/SP] Fullstack Front-End Developer | GTCON (#635) 



Qual o nome da empresa que a pessoa ficará alocada?

**Comment by LFeh** [comment]
Apenas vagas com o nome do cliente podem permanecer :)
