### ISSUE TITLE
[Remoto] Pessoa Engenheira de Software Frontend @ Telavita

### ISSUE THREAD

**Issue by rafaelcanovas** [frontendbr/vagas#6350]
![](https://media-exp1.licdn.com/dms/image/C4D16AQGGPdSOp6j9JA/profile-displaybackgroundimage-shrink_350_1400/0/1625079992821?e=1648684800&v=beta&t=88eBuNy7NlegwA8_srTfGl5uxXqPY53JOWfAWZeh6f4)

A Telavita está simplificando a distribuição de atendimentos de alta qualidade para solucionar o desafio do século: saúde emocional. Como clínica digital, conectamos psicólogos e psiquiatras a pacientes em todo território nacional de forma rápida, acessível e integrada. Atualmente atendemos uma população de mais de 4 milhões de vidas. Com nossos Programas de Saúde Emocional democratizamos o acesso ao cuidado e apresentamos engajamento e desfecho clínico acima da média do mercado.

## A tecnologia na Telavita:
Tecnologia é nosso principal agente transformador e como uma pessoa engenheira de software você será responsável por desenvolver soluções que garantem que – pacientes tenham acesso a informação e programas de saúde emocional que melhoram sua vida e de todos ao seu redor – psicólogos e psiquiatras possam trabalhar em conjunto por uma sociedade mais saudável – empresas e seguradoras possam oferecer programas que melhoram a saúde emocional dos seus beneficiários.

Trabalhamos com times ágeis, pipelines de deployment e integração contínua, pair programming e code review, tecnologias open source, análise estática de qualidade de código, arquitetura multicloud com orquestração de conteineres. Contamos com times multidisciplinares que participam desde a concepção das soluções até a execução e monitoramento do resultado.

### Seus principais desafios serão:

- Escrever código seguindo as melhores práticas de segurança e qualidade
- Sugerir soluções novas para as principais dores dos nossos stakeholders
- Interagir com seu time para estimar a execução de tarefas
- Colaborar na documentação e difusão de conhecimento
- Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas

### Experiências necessárias :

- Desenvolvimento utilizando as linguagens de programação JavaScript e TypeScript
- Desenvolvimento e manutenção de aplicações utilizando o framework React com Redux
- Utilização de protótipos do Adobe XD como referência para construção de interfaces acessíveis e intuitivas
- Documentação de componentes de interface utilizando Storybook
- Escrita de testes unitários utilizando Jest
- Criação de estilos utilizando CSS e Sass

### Diferenciais:

- Experiência com NextJS
- Experiência com micro frontends
- Gerenciamento de contexto com Context API

## Contratação

PJ a combinar

### Como se candidatar

Por favor envie um email para pessoas@telavita.com.br com seu CV anexado - enviar no assunto: Vaga Frontend

### Alocação
- Remoto

### Regime
- PJ

### Nível
- Pleno
- Sênior

### Remuneração
R$7,350.00 a R$16,100.00

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by rafaelcanovas** [comment]
Bom dia @felipefialho, a vaga ainda está aberta :)
