### ISSUE TITLE
[100% Remoto]  Front-End Developer  (Angular) Pleno - Red Pill RH

### ISSUE THREAD

**Issue by Kethlynaraujog** [frontendbr/vagas#6351]
A Code7 desenvolve softwares para facilitar a comunicação entre as empresas e os seus consumidores. Fundada em 2020, com escritórios em São Paulo e Florianópolis, hoje possui mais de 250 clientes e mais de 200 profissionais.Com a missão de transformar digitalmente a forma como os negócios atendem seus clientes, em apenas um ano, teve 1 bilhão de conexões entre marcas e consumidores, 1500 robôs de chat e voz e 400 milhões de mensagens trocadas via WhatsApp e SMS. Tudo isso a partir de suas soluções de mensagens de texto via SMS ou WhatsApp, e-mail, telefonia, discadores, URAs, CRMs, chatbots ou voicebots inteligentes e muito mais.

Respirar e viver tecnologia é o que motiva desde sempre. Idealizando novos projetos com o propósito de inovar a forma como as marcas se relacionam com o seu consumidor. Na Code7, o trabalho é intenso! Por isso, buscamos pessoas que gostem de desafios e que, com ideias criativas, ajudem-nos a construir um futuro diferente. A filosofia é pensar sempre em como fazer diferente e melhor e, na Code7, buscamos evoluir diariamente, em todos os sentidos.

Se você tem o propósito de fazer a diferença na vida das pessoas, estamos em busca de você para desenvolver os próximos códigos da Code7.

**A Red Pill juntamente com a Code7 está em busca de Desenvolvedor(a) Front-End (Angular)!**

****Quer** trabalhar em uma empresa TECH que se destaca em seu segmento de negócio, não para de inovar em suas soluções utilizando tecnologia de ponta e com uma equipe incrível?

Como Desenvolvedor(a) Front- End trabalhará desenvolvimento de layouts intuitivos e responsivos em nossas soluções corporativas. Para isso precisamos de uma pessoa analítica e que contribua sempre com novas ideias dentro do time.**

**O que você fará:**

- Desenvolver e implementar novas features do sistema omni;
- Pesquisar, analisar, sugerir e contribuir na implementação de novas tecnologias associadas com aplicações corporativas;
- Projetar, construir e otimizar interfaces web;
- Implementar layouts intuitivos e responsivos utilizando princípios ergonômicos de usabilidade.

**O que buscamos:**

- Desejável conhecimento da plataforma cloud AWS (Code Commit e S3);
- Conhecimento em versionamento GIT;
- Entendimento do protocolo HTTP e comunicação Rest Full;
- Ensino Superior completo ou em andamento em TI;
- Experiência com desenvolvimento em Angular 9 ou superior;
- Conhecimentos sólidos na linguagem TypeScript;
- Domínio de HTML5, CSS3, Javascript e processadores de estilo;
- Noções de UI &UX.

## Contratação

- PJ 

## Como se candidatar

- Por favor envie um e-mail para kethlyn.araujo@redpillrh.com.br com seu CV anexado - enviar no assunto: Vaga Angular

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dia após cada processo.
E-mail para contato em caso de não haver resposta: kethlyn.araujo@redpillrh.com.br 

#### 
- Remoto
- PJ
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
