### ISSUE TITLE
[Porto Alegre] Pessoa Desenvolvedora Front-end Angular Júnior ou Pleno na Muv Recursos Humanos

### ISSUE THREAD

**Issue by robertafonseca** [frontendbr/vagas#6354]
>

## Nossa empresa

A MuvRH está com 02 vagas para Desenvolvimento Front-end Júnior e/ou Pleno para atuar em uma empresa de Tecnologia, que oferece soluções inovadoras e customizadas no processo de transformação digital em desenvolvendo de software para demandas de omnichannel e varejo.

Você atuará poderá atuar com diferentes projetos e novas tecnologias para os diferentes clientes da cia. Estará inserido em um Time Ágil, com sprints e demais rotinas definidas respondendo tanto para um PO do cliente no qual o projeto esteja sendo desenvolvido, como para as lideranças técnicas da empresa contratada.

## Descrição da vaga

• Programar, desenvolver e implantar sistemas com as seguintes stacks: Angular 10+, Reactive Programming, Modules, Components, Directive, Guard, Interceptor, Reactive Form, Angular Material, NGRX, Test;
• Realizar correções em sistemas, análise e desenvolvimento de performance;
• Conduzir configuração e gerenciamento de microsserviços com Docker, Kubernetes, Jenkins, GitLab.

## Local

Híbrido, atuando alguns dias da semana no escritório [Rio Grande do Sul], [Porto Alegre], [Zona Norte]

## Requisitos

**Obrigatórios:**
- Experiência ou conhecimento com desenvolvimento Front-end Angular (Angular 10+);
- Disponibilidade para atuar na Zona Norte de Porto Alegre em alguns dias da semana;
- Conhecimento prévio em tecnologia de Container e em Metodologias Ágeis, SOA e Micro Front-End.

**Desejáveis:**
- Cypress;
- AWS ou Azure experience;
- OAuth 2;
- Inglês;
- CI/CD.

**Diferenciais:**

- Dress Code flexível;
- Ambiente de coworking com várias salas disponíveis para trabalho;
- Treinamento constante oferecido pelas lideranças técnicas;
- Possibilidade de trabalhar em diferentes projetos e com diferentes clientes e stacks.

## Contratação

PJ

## Remuneração

Faixa salarial de R$ 30,00/h a R$ 40,00/h – R$ 5.400,00 a R$ 8.100,00 (180h/mês) – será avaliada as competências técnicas para a negociação salarial.

## Como se candidatar

Por favor envie um email para cv@muvrh.com.br com seu CV anexado - enviar no assunto: Vaga 0946 - Pessoa Desenvolvedora Front-end. Qualquer dúvida pode acionar a Roberta Fonseca no seguinte WhatsApp: (51) 99337-9492

## Tempo médio de feedbacks

Costumamos enviar retornos em até 10 dias após o profissional ter passado por alguma das etapas aqui na MuvRH.

#### Nível
- Júnior
- Pleno

**Comment by robertafonseca** [comment]
Seria possível @felipefialho remover a label São Paulo? Pois essa vaga será híbrida. O profissional precisa ter a disponibilidade de ir algumas vezes na semana no escritório local, aqui em Porto Alegre, na Zona Norte. Mas não teria problema algum avaliar profissionais não só de Porto Alegre, como região Metropolitana ou profissionais com total disponibilidade de vir para Porto Alegre de vez.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
