### ISSUE TITLE
[Remoto] Full Angular Developer na Pasquali Solution

### ISSUE THREAD

**Issue by Recrutas** [frontendbr/vagas#6356]
**Descrição da vaga:**

Estamos procurando pessoas que tenha uma vasta experiência em desenvolvimento Front End com conceitos de Angular.

 **Local:**

Remoto

**Requisitos Obrigatórios:**

- Vivência de programação para Front-end;
- Vivência no framework Angular 2+

**Diferenciais:**

- GIT
- AWS
- Metodologia Scrum
- AngularJS
- UI/UX

 **Contratação**

PJ - Valor á combinar.

**Como se candidatar?**

Envie seu currículo: danyela.silva@pasqualisolution.com.br
Envie seu currículo: https://cutt.ly/ubjZX1f

 **Labels**

- Pleno

 **Alocação**
 
- Alocado
- Remoto

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
