### ISSUE TITLE
[Remoto] Front-end [React || Angular] Engineer na RightBalance

### ISSUE THREAD

**Issue by JampaUchoa** [frontendbr/vagas#6357]
## Nossa empresa

A Right Balance é uma empresa que conecta talento ao redor do mundo com startups de alto crescimentos nos Estados Unidos. Essas empresas requerem pessoas seniors (pra ontem) mas há muitas burocracias para contratarem global. É aí que entra nosso papel. 

**Não somos empresa de gerenciar freelancer, nem de contrato em projetos de curta duração.** Os contratos com a empresa de lá duram anos e você pode crescer com a empresa, e continuar 100% remoto, pois elas também são.

Se você for contratado voce trabalhará em uma empresa alocada nos EUA (Bay Area, Nova York entre outros), e terá toda a rede de desenvolvedores da Right Balance, o bom de trabalhar conosco é que simplificamos a burocracia de trabalhar para fora para que mais empresas possam ter acesso ao talento internacional, então se voce não estiver feliz conseguimos achar sempre outra empresa da nossa rede para voce trabalhar, sem passar por outro processo de entrevista longo.

## Descrição da vaga

Temos várias vagas abertas para pessoas senior com Angular e React (+3 anos com uma delas e +5 anos em desenvolvimento web full time). Todas elas são para trabalhar com startups nos EUA. Precisamos de pessoas com conhecimento de arquitetura pois irão trabalhar em ambientes de alto crescimento aonde o desenvolvedor terá bastante autonomia de desenvolver soluções.

## Local

Time 100% remoto, qualquer lugar do mundo, se quiser mudar de país só se atentar a manter o time zone.

## Requisitos

**Obrigatórios:**
- Ingles conversacional e escrito (voce vai usar Ingles o tempo todo, desde a primeira entrevista)
- 4+ anos de experiencia profissional (não pode ser projetos paralelos ou de faculdade). Se voce fundou empresa ou passou mais de 30 horas semanais desenvolvendo no projeto é OK.
- 2+ anos de experiencia profissional em React ou Angular.
- Conhecimentos em arquitetura de projetos, boas práticas, gerenciamento de estados.
- 
**Desejáveis:**
- Experiencia profissional com back-end, abre mais o leque de vagas. 

**Diferenciais:**
- Projetos opensource
- Trabalhos em startup

## Benefícios

- Pagamento em USD, acima do mercado brasileiro
- Feriados locais
- Ferias de 2 semanas pagas

**Diferenciais:**
- Trabalhar com startups de alto crescimento com colegas ao redor do mundo.

## Contratação

PJ

## Como se candidatar

Preencha o form com as informações mais exatas possível. Vamos tentar achar o job mais com seu perfil baseado nele.

https://docs.google.com/forms/d/e/1FAIpQLSf5ExrNb0hDfP4PLceVXhvfaGLcopZCJ_GtoINlTZxtrvnGFg/viewform

## Tempo médio de feedbacks

**Somos uma empresa feito 100% de devs desde o CEO, o feedback é logo ao fim da entrevista**, se voce passar na nossa entrevista as próximas são com as empresas, e queremos que voce se der bem, então damos vários pontos para entrevistas no futuro, se não passar nelas também devolvemos o que nos deram. 
Ao contrario de outras empresas realmente sempre nos mantemos em contato com as pessoas que passaram no nosso processo, e chamamos pra outra entrevistas.

E-mail para contato em caso de não haver resposta: hiring@rightbalance.io (mande em ingles)

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
