### ISSUE TITLE
[100% remoto] React Developer Pleno ou Senior @DQR Tech

### ISSUE THREAD

**Issue by gsabreudev** [frontendbr/vagas#6358]
## SOBRE NÓS

Nascemos de uma parceria de mais de 10 anos entre seus sócios, somando a paixão por tecnologia à vontade de construir uma empresa diferente, investindo na proximidade com nossos parceiros e clientes. Somos uma consultoria especializada em Arquitetura de TI, Outsourcing de Profissionais e Hunting.

## CONTRATAÇÃO: 

PJ Clássico - Projeto Indeterminado
Atuação 100% remota
Senioridade: Pleno ou Senior

## DESAFIO: 

Atuará junto a DQR Tech numa Squad nova, projeto sendo construído do zero, atendendo demandas do nosso cliente, sendo este uma instituição financeira, maior banco de investimentos da América Latina. 
REQUISITOS: 
Profissional com alto nível de conhecimento/desenvolvimento Web (React);
Saiba construir telas (Noções de UX/UI). (se tiver portfolio - enviar o link do mesmo)
Ter ótima comunicação e relacionamento com equipe.

## DIFERENCIAL: 
Conhecimento sobre mercado financeiro.

## VALORES: Até 15k PJ

Enviar seu CV para: gabriela.abreu@dqrtech.com.br
Contatar via whats 51 99763-3298 (se preferir)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
