### ISSUE TITLE
[Remoto] Front-end Vue.js Developer Senior @ Robert Half

### ISSUE THREAD

**Issue by LiviaMaron** [frontendbr/vagas#6359]
## Nossa empresa

A Robert Half combina profissionais de TI com algumas das melhores empresas em caráter temporário, de projeto ou em período integral. Desde funções em software e aplicativos até infraestrutura e operações de TI, fornecemos acesso sem paralelo a emocionantes oportunidades de carreira. Nossa abordagem personalizada, tecnologia inovadora de correspondência e rede global com experiência no mercado local ajudam a encontrar rapidamente os trabalhos de tecnologia que correspondem às suas habilidades e prioridades. Ao trabalhar conosco, você tem acesso a oportunidades desafiadoras, remuneração e benefícios competitivos e treinamento para aprimorar seu conjunto de habilidades.

## Descrição da vaga
 
Oportunidade para atuar alocado na maior gateway de pagamentos da América Latina, com processamento de mais de 20 bandeiras no mundo.

Profissional atuará em um novo projeto na área de meios de pagamento, sendo o desenvolvedor Front end, em parceria com mais 2 dev Backend.

## Local

100% remoto 

## Requisitos

Desenvolvimento através da linguagem Vuejs, Javascript (Vanilla e E6) e Typescript.
Experiência também com linguagem Node js para apoiar a equipe de backend.
Responsável por codificar o resultado do trabalho da equipe de UX para a criação do novo produto que ainda está em fase de protótipo.
 
Requisitos necessários:
Javascript (Vanilla e E6+), HTML e CSS;
VueJS, VueX e NuxtJS;
NodeJs e NPM;
SASS;
Clean Code;
Integração com APIs (Rest);
Figma e AdobeXD;
Google Analytics;
Azure Devops;
 
Seria ótimo se conhecesse:
CI/CD;
LazyLoading;
Segurança, (ex: OAuth2);
Responsividade;
Testes Unitários (ex: Jest);
Testes de Integração (ex: Cypress);
TypeScript;
 
## Benefícios

- Assistência Médica (s/ dependente) e Odonto Executivo (s/ dependente)
- Seguro de Vida
- Vale Refeição 

## Contratação

Contratado como CLT Robert Half

## Como se candidatar

Interessados deverão enviar o currículo para livia.mello@roberthalf.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

## Labels

- 🏢 Remoto
- 👴 Sênior
- ⚖️ CLT

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
