### ISSUE TITLE
[São Paulo] Front-End Developer na [R&S Holmes]

### ISSUE THREAD

**Issue by RaphaYehudah** [frontendbr/vagas#636]
Vaga: Desenvolvedor Front-End
Nível: Júnior e Pleno (2 vagas)
Empresa: DT+Seekr (Hi Platform)
Ramo de atuação: Tecnologia
Localidade: Região da Berrini, São Paulo - SP
Atividades: O principal desafio desta vaga é o desenvolvimento e gerenciamento de projetos de Interfaces.
Requisitos:
Desejáveis
● Protocolo HTTP (response, request, cabeçalhos);
● ES6 (Babel, Typescript ou afins)
● Sistemas avançados de build e deploy
● HTML/CSS Design Patterns;
● O profissional deve desenvolver códigos sustentáveis e saber testá-los;
● Saber usar sistema de controle de versões (SVN, GIT); e
● Photoshop (Básico - corte de imagens).

Diferenciais
● Mobile;
● AngularJS, React, Bootstrap e Material Design;
● AMD ou CommonJS
● Cross-domain (same-origin policy, post messaging)
● Conhecimento de Metodologia Ágil.
Escolaridade: Ciência da Computação, Engenharia da Computação ou outros similares na área de exatas.
Salário: A combinar (Regime de contratação CLT)
Benefícios:
• Vale Refeição ou Alimentação no valor de R$24,00 reais ao dia. 
• Plano de Saúde com Assistência Médica e Odontológica. 
• Vale Flex: benefício no valor de R$250,00 - este valor pode ser destinado ao Vale Refeição, Alimentação ou para o estacionamento aqui na DT, ou seja, você pode destinar o valor para uma destas três opções. 
• Vale transporte ou Vale Fretado (com 6% de desconto no salário) + 
• Política de Leitura e cursos. 
• Seguro de vida
Interessados enviar currículo para raphael.siqueira@rsholmes.com.br com o assunto “Desenvolvedor Front End - GitHub”.

**Comment by sdq-sts** [comment]
Curso superior é obrigatório?

**Comment by RaphaYehudah** [comment]
Olá Sadraque,

Como é a primeira vaga que trabalhamos com esse cliente, não sei dizer.
Mas, no geral, nossos clientes não pedem curso superior como algo imprescindível para vaga de tecnologia,
Envie seu currículo para darmos uma olhada =)

Atenciosamente,

 

 


Raphael Ben Yehudah Siqueira | Analista de R&S
11 954 882 796  -  11 2772 8152
Skype:raphyehudah   <mailto:raphael.siqueira@rsholmes.com.br> raphael.siqueira@rsholmes.com.br
Al. Santos, 1800 – 8º andar – São Paulo SP

Visite: www.rsholmes.com.br   



 

 

 

 

 

 

De: Sadraque Santos [mailto:notifications@github.com] 
Enviada em: terça-feira, 31 de outubro de 2017 18:36
Para: frontendbr/vagas
Cc: RaphaYehudah; Author
Assunto: Re: [frontendbr/vagas] [São Paulo] Front-End Developer na [R&S Holmes] (#636)

 

Curso superior é obrigatório?

**Comment by DawTaylor** [comment]
É para trabalhar na R&S Holmes ou na DT+Seekr?

**Comment by vinirossi** [comment]
currículo enviado.

**Comment by RaphaYehudah** [comment]
Olá Adalberto!




É para trabalhar na DT+Seekr que agora é Hiplatform.

 

Abs,

 

 


Raphael Ben Yehudah Siqueira | Analista de R&S
11 954 882 796  -  11 2772 8152
Skype:raphyehudah   <mailto:raphael.siqueira@rsholmes.com.br> raphael.siqueira@rsholmes.com.br
Al. Santos, 1800 – 8º andar – São Paulo SP

Visite: www.rsholmes.com.br   



 

 

 

 

 

 

 

De: Adalberto Taylor [mailto:notifications@github.com] 
Enviada em: sexta-feira, 3 de novembro de 2017 17:47
Para: frontendbr/vagas
Cc: RaphaYehudah; Author
Assunto: Re: [frontendbr/vagas] [São Paulo] Front-End Developer na [R&S Holmes] (#636)

 

É para trabalhar na R&S Holmes ou na DT+Seekr?

**Comment by vinyguedess** [comment]
@mateusguedess

**Comment by LFeh** [comment]
Aberto ainda?
