### ISSUE TITLE
[Barueri, São Paulo, Brazil] Frontend React Developer na Assesso

### ISSUE THREAD

**Issue by mateu5-francisco** [frontendbr/vagas#6362]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-frontend-react-171731662?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Estamos em busca de uma <strong>Pessoa Desenvolvedora Frontend React</strong> para realizar a manutenção, evolução e desenvolvimento de novos módulos da plataforma DataCare.</p>
<p></p>
<p><strong><ins>💼 Contratação PJ</ins></strong></p>
<p>🏋️ Gympass</p>
<p>🏥 MDS (Plataforma de seguros com descontos especiais para os integrantes do time da Assesso),</p>
<p>🏫 Oportunidade de desenvolvimento profissional.</p>
<p></p>

## Assesso: 
 <p>A Assesso é uma empresa de tecnologia com mais de 40 anos de atuação no mercado brasileiro.</p>
<p>Inicialmente operou como desenvolvedora de sistemas sob medida, tendo se especializado em projetos com grande volume de dados e necessidade de grande performance.</p><a href='https://coodesh.com/empresas/assesso'>Veja mais no site</a>

 ## Habilidades: 
 - Java 
- NoSQL 
- React.js
## Local: 
 Barueri, São Paulo, Brazil
## Requisitos: 
 - Experiência com ReactJS 
- Experiência com HTML, JavaScript, CSS e TypeScript 
- Experiência com integração REST 
- Utilização de boas práticas de desenvolvimento e testes  
- Conhecimento em Maven e Git. 
- Inglês Técnico 
- Superior Completo em Ciência da Computação, Análise de Sistemas, Engenharias e afins
## Diferenciais: 
 - Conhecimentos das bibliotecas Material-UI, Ant Design, Redux e Axios 
- Experiência em conversão de sistemas monolíticos para arquitetura de microsserviços 
- Conhecimentos básicos em desenvolvimento Java EE (JSP, JSF, JPA, Web Service, etc). 
- Framework Spring Boot 
- CI – Integração Contínua / CD – Delivery Contínuo 
- Containers e microservices 
- Experiência em desenvolvimento de aplicações com layout responsivo

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend React Developer na Assesso](https://coodesh.com/vagas/desenvolvedor-frontend-react-171731662?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
