### ISSUE TITLE
[Remoto] Frontend React Developer na MPI Sistemas

### ISSUE THREAD

**Issue by bernardosaltiel** [frontendbr/vagas#6363]
## Descrição da vaga

Estamos no processo de desenvolvimento de um sistema ERP WEB e procurando pessoas que possa vir acrescentar na nossa equipe que hoje é formada por uma pessoa que faz tanto BACK-END/FRONT-END com isso dividido o trabalho e gerando resultado de forma mais rápida e estruturando uma equipe boa para crescimento desse projeto

## Local

Remoto

## Requisitos
- Experiência frameworks JS ( React, Next)
- Experiência (CI/CD)
- Style components / material UI
- Conhecimentos em: Arquitetura baseada em Microsserviços, Docker
- APIs REST e/ou GraphQL
- Experiência em projeto de Design System
- Experiência em versionamento com Git

## Como se candidatar

Por favor envie um WhatsApp para (51)99826-5585 com seu CV e seus projetos

## Labels

- 🏢 Flexível
- 🏢 Remoto
- ⚖️ A-Combinar

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
