### ISSUE TITLE
[Remote- Latin America Only] Front-end Developer na Jobsity

### ISSUE THREAD

**Issue by luzsemoIT** [frontendbr/vagas#6366]
Hi GitHub community!
At Jobsity we´re looking for Senior developers (+3 years of experience) with a good English level. We currently have many frontend openings, so any techs and languages are welcome!
We offer 100% remote positions, very good salaries in USD and some more benefits:
-15 working days of paid vacations
-3 extra off days per year
-Paid local holidays
-Paid time off
-Budget for e-learning courses
-Financing program for equipment
-Bonuses for referrals

If you´re interested, don´t hesitate to contact me via email at luz.semo@jobsity.com or [LinkedIn](https://www.linkedin.com/in/luz-semo/) :)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
