### ISSUE TITLE
[Remoto] Front-end Angular Developer no Zenklub

### ISSUE THREAD

**Issue by cleandersonlobo** [frontendbr/vagas#6367]
## Nossa empresa

O **[Zenklub](https://zenklub.com.br/)** tem o propósito de promover saúde mental para as pessoas e resultados para as empresas. 

Estamos no mercado desde 2016, somos transformadores sociais, especialistas em cuidado emocional e saúde emocional corporativa. Nossa abordagem é baseada em ciência, dados e tecnologia para potencializar organizações e seus indivíduos.

Somos a maior plataforma de saúde emocional e desenvolvimento pessoal do Brasil e acreditamos que a saúde mental é um caminho inevitável para o desenvolvimento corporativo sustentável, entregando o desenvolvimento da empresa potencializado pelo desenvolvimento pessoal de seus funcionários.

### Estamos procurando você para se juntar ao nosso time, com foco em

- Criar aplicações cliente para web, focando em alta performance, UI lindas & qualidade de código;
- Desenhar, desenvolver e deployar de ponta a ponta pipelines de dados que atendam a requisitos de negócio;
- Colaborar com todas as pessoas da área de tech, produto e design, para identificar e resolver problemas desafiantes e criar uma experiência incrível para usuários no mundo inteiro.

## Local

Remoto

## Requisitos

- Sabe trabalhar em equipe, e acredita que pessoas trabalhando em conjunto para entregar valor é mais importante do que processos ou frameworks (por mais que eles possam ajudar bastante); 
- Tem interesse em trabalhar em ambientes dinâmicos, com mudanças constantes e incertezas de uma fase de crescimento da empresa; 
- Tem experiência trabalhando com times multidisciplinares para entender, documentar e desenvolver software para atender requisitos de vários stakeholders; 
- Tem um entendimento profundo de arquitetura de sistemas, estrutura de dados e algoritmos; 
- Trabalhou com Angular 2+ e concorda a frase ‘Typescript arrebenta’;
- Conhece as últimas tendências e boas práticas no que diz respeito a estilizar aplicações; 
- Se importa com a aparência das coisas; 
- Testes são parte da sua zona de conforto; 
- Gosta de criar sistemas mais eficientes, escaláveis e estáveis;
- Se orgulha de entregar código do mais alto nível e de gerenciar todo o ciclo de produção.

## Benefícios

- Plano de Saúde e Odonto SulAmérica sem coparticipação;
- Pensando na saúde emocional e desenvolvimento dos nossos Zens, você terá acesso gratuito à terapia (4 sessões/mês), além disso até 3 familiares terão desconto de 25% para utilizar a plataforma;
- Benefício flexível no Cartão Caju Visa R$800/mês;
- Contrato PJ com pausa remunerada e com 13º salário;
- Liderança e founders com expertise de mercado;
- Time 100% remoto, em vários lugares do Brasil e do mundo;
- Horário flexível;
- Times produzindo com alta performance;
- Ideias ousadas são adoradas;
- Títulos não significam muito, você conquista respeito sendo quem você é;
- Colaboração, colaboração, colaboração!

## Contratação

PJ a combinar

## Como se candidatar

Acesse [aqui](https://bit.ly/3H8VRTT)  para se candidatar.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by cleandersonlobo** [comment]
@felipefialho a vaga segue aberta!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
