### ISSUE TITLE
[Remoto] Senior Android Developer na Pasquali Solution

### ISSUE THREAD

**Issue by Recrutas** [frontendbr/vagas#6368]
**Descrição da vaga**
Estamos procurando profissionais que tenham uma vasta experiência em desenvolvimento Android.

**Local**
Remoto

**Requisitos Obrigatórios:**

•	Java/Kotlin
•	Recycler View 
•	Fragment 
•	Broad cast
•	Webview
•	Mustache
•	Realm
•	MVP
•	Publicação de app no google e pagamentos

**Diferencial:**

•	Threads
•	Retrofit
•	Firebase
•	Git hub

**Contratação**
PJ - Valor a combinar.

**Como se candidatar?**

Envie seu currículo: https://cutt.ly/bxmAzBE
Envie seu currículo: carolina.ugolini@pasqualisolution.com.br

**Labels**

•	Alocado
•	PJ
•	Sênior

**Sobre a Pasquali**
A Pasquali Solution é uma consultoria com foco em Alocação de profissionais de TI reconhecida pelo seu trabalho rápido e com excelência.
Estamos há mais de 18 anos no mercado e somos altamente especializada em Tecnologia da Informação.
Vantagens
•	Parceria com a Alura para cursos
•	Gratificação no mês de aniversário

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
