### ISSUE TITLE
[REMOTO] Front-end Developer na Farma Ponte (Alocação KLB Group)

### ISSUE THREAD

**Issue by KevinMarcelOriginal** [frontendbr/vagas#6371]
## A KLB Group
A KLB Group é uma empresa multinacional francesa, com sede em Paris. Tem presença em mais de vinte países, atuando no segmento de Engenharia, Energia, TI, Supply Chain, Qualidade e Compras
A KLB Group atua com três modelos de negócios: implementação de projetos, serviços de outsourcing e serviços de hunting.

## A Farma Ponte
Uma das maiores redes de farmácias do interior do estado de São Paulo, com
mais de 40 anos de mercado.Com um forte projeto de expansão e crescimento
constante, a empresa possui mais de 1 mil colaboradores e mais de 115 lojas
distribuídas por diversas cidades do interior do estado de São Paulo.

Possui sistemas de Disk Delivery e E-commerce que facilitam a compra,
independente da localização. Trabalha com produtos de higiene,
medicamentos e produtos de beleza, nacionais e importados.

## Local

100% Remoto

## Requisitos

**Desejáveis:**
-HTML
-CSS
-JAVASCRIPT
-JSON,  consumo de API Rest, Fetch, CORS
-BootStrap / TailWind
-Boa noção de SQL ANSI

**Diferenciais:**
- Angular, NextJs ou React seria um destaque

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um e-mail para kmarcel@klbgroup.com com seu CV anexado - enviar no assunto: Vaga FrontEnd

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

**Comment by Djamess** [comment]
Acabei de enviar

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
