### ISSUE TITLE
[Remoto] Full Infrastructure Analyst na Pasquali Solution

### ISSUE THREAD

**Issue by Recrutas** [frontendbr/vagas#6372]
**Descrição da vaga**

Estamos procurando pessoas que tenha uma vasta experiência em Analista de Infraestrutura. 

**Local**

Remoto

**Requisitos Obrigatórios:**

•	Ensino Superior completo na área de T.I.;
•	Experiência em Docker;
•	Experiência com sistemas operacionais Linux;
•	Configuração de servidores web Apache/Nginx;
•	Windows Server;
•	AWS ou GCP;
•	Inglês técnico ;
•	Conhecimento em ferramentas de monitoramento (Grafana/Prometheus/Cloud Watch);
•	VPN;

**Diferencial:**

•	Shell Script;
•	Python;
•	Azure;

**Contratação**

PJ - Valor a combinar.

**Como se candidatar?**

Envie seu currículo: https://cutt.ly/IQazBFs 
Envie seu currículo: adilma.santos@pasqualisolution.com.br

**Labels**

•	Alocado
•	PJ
•	Pleno

**Sobre a Pasquali**

A Pasquali Solution é uma consultoria com foco em Alocação de profissionais de TI reconhecida pelo seu trabalho rápido e com excelência.
Estamos há mais de 18 anos no mercado e somos altamente especializada em Tecnologia da Informação.
Vantagens
•	Parceria com a Alura para cursos
•	Gratificação no mês de aniversário

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
