### ISSUE TITLE
[REMOTO] Engenheiro de Software Front-end na PROPZ

### ISSUE THREAD

**Issue by carolribeiro2209** [frontendbr/vagas#6374]
## **PROPZ**

A **Propz** é uma empresa de CRM e Inteligência Analítica que atua como parceira estratégica de Varejistas na rentabilização de seus negócios, entregando uma unidade de negócio completa de CRM por meio de consultoria, software e soluções. 

Somos pioneiros na aplicação de tecnologias que entendem, predizem e influenciam o comportamento de consumo em tempo real e de forma automatizada. Com sede no Brasil e presença na Rússia, na Polônia e no Peru, a empresa tem como clientes os líderes em varejo e serviços financeiros do país. Dados de mais de 126 milhões de consumidores são processados, proporcionando um aumento de até 3% de receita incremental com margens sustentáveis. 

**Queremos construir a mais poderosa máquina de relacionamento com o cliente com a capacidade de aprender, adaptar e agir, independente de controle humano.** 

## Descrição da vaga

Para a posição de **Engenheiro de Software (Frontend Lead)** é esperado que o profissional tenha capacidade de assegurar, através da equipe liderada, a aplicação por parte desta de boas práticas em desenvolvimento de interfaces de usuário, entregando uma experiência de uso para o consumidor final em linha com as melhores referências do mercado e guiando-o até as tomadas de ação desejadas. Preocupar-se com a melhoria contínua baseada em números, para o que a captura de métricas nas interfaces que desenvolver são fundamentais para a tomada de decisão. 

Deve assegurar a atenção da equipe aos detalhes, pois os cenários do mundo real são repletos de pormenores que fazem toda a diferença na experiência dos clientes se bem endereçados pela experiência de uso que se entrega. Ao mesmo tempo, deve garantir soluções escaláveis, robustas e seguras, haja visto que nossa missão passa por democratizar o CRM inteligente e rentável, o que requer implantá-lo com máxima produtividade (em menor tempo possível e nenhum atrito) em dezenas de varejista. 

Por fim, avaliar criticamente documentos escritos pela equipe e ser capaz de explicar e defender aspectos técnicos da solução é uma característica que o profissional deve ter para ser capaz de construir soluções em conjunto nossas equipes internacionais e apresentar às equipes dos varejistas (quer da área de tecnologia ou de negócios), razão pela qual a boa comunicação tanto em português quanto em inglês faz-se relevante. 

**PRINCIPAIS ATRIBUIÇÕES**

- Liderar o projeto de soluções em software contendo, mas não se limitando a; 
         Casos de uso cobertos (quais necessidades de negócio a solução deverá satisfazer); 
         Casos de uso não cobertos (quais necessidades - ou potenciais necessidades - de negócio a solução não deverá satisfazer), justificando da ótica de negócio e/ou técnica a motivação da não cobertura de casos (quando houver); 
         Requisitos funcionais (como a solução irá satisfazer os casos de uso), utlizando-se de: 
Fluxogramas (para ilustrar comunicação entre entes); 
Pseudocódigo (para descrever algoritmos); 
Diagramas entidade-relacionamento (para representar informação a ser persistida e suas relações); 
Wireframes (para tangibilizar telas); 
Bullet points (para sintetizar ideias em frases curtas); 
         Requisitos não funcionais 
                      Performance (velocidade); 
                      Segurança da informação; 
                      Logs para debugs e auditorias. 
         Riscos identificados e ações mitigadoras. 

- Garantir escalabilidade, robustez e retro compatibilidade com versões anteriores; 
         Garantir que produtos sejam entregues em linha com as boas práticas do desenvolvimento web, revisando o código escrito pelos integrantes da equipe e a adoção de boas práticas de desenvolvimento; 
         Orientar a equipa na construção de soluções com arquitetura escalável para entrega da proposta de valor definida pelo Product Owner a dezenas de varejistas; 
         Assegurar que haja planos de testes e que estes sejam seguidos por profissionais de QA e pela própria equipe de Produtos quando do processo de homologação do software; 
         Definir métricas para acompanhamento da estabilidade da solução; 
         Apresentar e discutir a solução com desenvolvedores; 

- Assegurar que documentações técnicas e manuais de uso de soluções sejam desenvolvidas; 
         Disponibilizar conteúdo online para utilização por terceiros técnicos e/ou não técnicos; 
         Atualizar documentações regularmente quando identificado tópico não coberto e/ou não claro o bastante; 
         Redigir e-mails em resposta a solicitações de clientes que clarifiquem dúvidas acerca da aplicação do software a suas necessidades; 

- Participar de reuniões técnicas com equipes de clientes e parceiros para orientação na utilização de soluções tecnológicas existentes e/ou construção de soluções em conjunto. 

## Local

100% Remoto

## Requisitos

- Conhecimento avançado em desenvolvimento de Progressive Web Apps; (PWA) 
         Foco em alto desempenho (avaliado por ferramentas como PageSpeed do Google); 

- Conhecimento avançado e aplicação padrões, convenções e estratégias modernas de HTML5, CSS3 e JavaScript. Alguns exemplos: 
         Exploração do uso de cabeçalhos HTTP (Expires, Cache-Control, etc); 
         Uso adequado da semântica do HTTP; 
         Utilização de bibliotecas de manipulação do DOM; 
         Aplicação de recursos como cache, pre-fetching, lazy loading, post loading;  
         Uso de bibliotecas JS MVC (AngularJS, em especial); 
         Uso de pre-processadores CSS; 
         Minificação de códigos etc.; 

- Conhecimento avançado em linguagem de programação orientada a objetos;  

- Conhecimento avançado de uso de Web Services (REST e SOAP);  

- Conhecimento avançado em controle de versão (e.g., GIT); 

- Experiência intermediária com ferramentas de qualidade de código (e.g., SonarQube); 

- Experiência intermediária com ferramentas de gestão de erros (e.g., Airbrake); 

- Compreensão aprofundada de arquitetura de sistemas, e.g.: 
         Client-Server; 
         Model-view-controller (MVC); 
         Service Oriented Architecture (SOA). 

**Desejáveis:**

- Conhecimentos em Shell script; 

- Conhecimento avançado do funcionamento de ambientes em nuvem (AWS / Azure / GCP); 

- Uso de aplicativos Office (Word, Excel e PowerPoint); 

- Conhecimento em desenvolvimento de projetos de TI (metodologias ágeis e clássica); 

- Experiência com ferramentas de BI (PowerBI, Tableau, Qlike, etc);  

- Atuação junto ao mercado varejista. 

## Benefícios

Plano de Saúde;
Plano Odontológico;
Seguro de Vida;
Vale-Refeição e/ou Alimentação;
Trabalho Remoto (Home-office)
Day-off no seu aniversário;

## Contratação

CLT

## Como se candidatar

Favor se candidatar através do site [](https://propz.recruitee.com/o/engenheiro-de-software-frontend-lead) ou enviando currículo para o e-mail carreiras@propz.com.br

#### Nível

- Sênior
- Lead

**Comment by carolribeiro2209** [comment]
[](https://propz.recruitee.com/o/engenheiro-de-software-frontend-senior-tech-lead)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
