### ISSUE TITLE
[REMOTO] Front-End Developer VTEX IO na Framework Digital

### ISSUE THREAD

**Issue by felipe-ssilva** [frontendbr/vagas#6375]
> Vaga Remota durante ou após a pandemia

## Framework Digital

A Framework é uma empresa com mais de 11 anos de mercado, com sólida experiência em tecnologia e serviços na transformação digital.

Parceria é a palavra que define a nossa relação com nossos clientes.
É uma empresa completa, pois além de atuar com uma gama de serviços tem seus produtos digitais!

Agregar valores reais aos negócios de nossos clientes através da tecnologia é o principal objetivo da Framework.

Somos ágeis e entregamos com eficiência, qualidade e segurança.

## Sobre o desafio
Desenvolver novas interfaces VTEX IO (backend e frontend);
Realizar manutenção corretiva ou evolutiva das interfaces dos produtos;
Manter um padrão de layout para os produtos;
Atualizar catálogo de componentes de interfaces e frameworks de desenvolvimento;

## Local

Remoto (mesmo após a pandemia) ou Escritório, Minas Gerais - BH, funcionários.

## Requisitos

**Obrigatórios:**
- Node
- Typescript
- GraphQL
- VTEX IO

**Desejáveis:**
- Cypress
- TDD
- Scrum / Kanban

**Diferenciais:**
- Projetos VTEX em produção

## Benefícios

CLT:
- Assistência médica e odontológica
- VR de R$ 30/dia
- VA de R$ 400/mês
- Gympass

PJ:
- À combinar

## Contratação

PJ ou CLT, você escolhe!

## Como se candidatar

Por favor envie um email para felipedasilva@frwk.com.br com seu CV anexado - enviar no assunto: Front-End Developer VTEX IO Sênior

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
