### ISSUE TITLE
[Remoto] CTO - Chatbot na Guide121

### ISSUE THREAD

**Issue by mateu5-francisco** [frontendbr/vagas#6376]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/cto-chatbot-005300670?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Olá!</p>
<p>Somos uma startup de Assistência Digital e proporcionamos ao nosso cliente a possibilidade de entregar o melhor chat-experience aos seus usuários. Em 2021 chegamos ao marco de faturar 1MM e vamos triplicar em 2022!&nbsp;</p>
<p></p>
<p><strong>O que buscamos?</strong></p>
<p>Um(a) Chief Technology Officer que:</p>
<p>- GOSTE de trabalhar com assistência digital! Então, se vc entende o valor de uma boa experiência conversacional para atrair um cliente, fechar uma venda ou dar suporte no atendimento ao cliente, vc tem um grande ponto em comum com nosso negócio!&nbsp;</p>
<p>- Se IMPORTE com o desenvolvimento das PESSOAS e faça isso acontecer! Aqui você terá um time ávido por conhecimento, desenvolver o time para que todos crescem junto com a empresa faz parte do nossa cultura.&nbsp;</p>
<p>- Seja INOVADOR, que pense fora da caixa novas soluções para os nosso clientes e ao mesmo tempo seja HANDS ON, que esteja disposto a codar também.&nbsp;</p>
<p>- Represente nossa empresa no mercado! Eventualmente você terá a oportunidade de estar em eventos, sendo responsável pelo pitch do nosso negócio.&nbsp;&nbsp;</p>
<p></p>
<p><strong>Quais serão suas atividades aqui: </strong></p>
<p>- Gestão da equipe de desenvolvedores, fomentando sempre o desenvolvimeno e crescimento profissional dos Guiders.&nbsp;</p>
<p>- Manutenção e aprimoramento da nossa plataforma.&nbsp;</p>
<p>- Liderar o lançamento de dois novos produtos.&nbsp;</p>
<p>- Trabalhar na construção de novas tecnologias que sustentem o negócio.&nbsp;</p>
<p></p>
<p><strong>O que oferecemos?</strong></p>
<p>- Contrato pode ser PJ ou CLT.</p>
<p>- Possibilidade de vesting.</p>
<p>- Trabalho 100% remoto, com eventuais viagens para evento ou encontro com o time.</p>
<p></p>
<p>Se identificou? Vem com a gente, aplique-se nesta oportunidade!&nbsp;</p>

## Guide121: 
 <p>A Guide121 nasceu com o propósito de transformar Assistência Digital. Levamos inteligência artificial para experiência do cliente. Otimizar processos, reduzimos custos e geramos vendas diretas através de chatbots, com uma super <em>chatexperience</em>!&nbsp;</p>
<p>Vou te contar um pouco de como nós somos e agimos:&nbsp;</p><a href='https://coodesh.com/empresas/guide121'>Veja mais no site</a>

 ## Habilidades: 
 - PHP 
- Laravel 
- Docker 
- Vue.js 
- Arch Linux 
- PostgreSQL 
- Rest e Restful APIs
## Local: 
 100% Remoto
## Requisitos: 
 - Saber criar e gerenciar servidores de php, nginx, loadbalancer, mysql, redis, etc   
- Inglês Fluente 
- Experiência em gestão de times de tecnologia - de todos os níveis - juniores e seniores.    
- Conhecimento na plataforma BLIP 
- PHP / Laravel 
- Postgresql /MySQL  
- VueJS  
- Docker  
- Familiaridade com Linux  
- Estar acostumado a trabalha com apis rest 
## Diferenciais: 
 - Desenvolver pessoas 
- Ter trabalhado com produtos conversacionais 
- Tailwindcss  
- Inertiajs  
- CI Pipelines, github, gitlab
## Benefícios: 
 - Possibilidade de vesting
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [CTO - Chatbot na Guide121](https://coodesh.com/vagas/cto-chatbot-005300670?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
