### ISSUE TITLE
[REMOTO] Svelte/SvelteKit Developer na SEVN

### ISSUE THREAD

**Issue by kazzkiq** [frontendbr/vagas#6377]
## SEVN

<br>
<br>
<p align="center">Prazer, somos a <a href="https://sevn.technology/">SEVN</a>.</p>
<br>
<br>

<p align="center">
<img width="800" alt="Frame 2@2x" src="https://user-images.githubusercontent.com/1953194/151902767-d2961d40-05f0-44bd-978c-dc7f14f76736.png">
</p>

<br>
<br>

Olá, somos a SEVN! Uma empresa jovem, versátil, que não tem medo de adotar novas tecnologias para entregar o melhor produto a clientes exigentes!

Atuamos na criação de apps mobile, sites, PWAs, sistemas web e serviços backend para clientes de pequeno, médio e grande porte em todo o Brasil.

## Descrição da vaga

Temos um projeto de grande porte que será feito em [SvelteKit](https://kit.svelte.dev/) e estamos procurando devs para esse desafio!

Esse projeto é dividido em dois módulos front-end: um portal de notícias, e um sistema de gerenciamento desse portal, ambos construídos do zero em SvelteKit.

Você irá atuar junto da equipe em ambos os projetos, porém com foco principal no segundo módulo: o sistema de gerenciamento do portal.

Se você não tem extensiva experiência com Svelte ou SvelteKit, **não tem problema**. Conhecimento prévio em React ou Vue te permitem se familiarizar rapidamente com Svelte, e experiências passadas com Next.js te permitem trabalhar com SvelteKit em pouco tempo.

Então se você se julga proficiente em React, Vue, ou Next.js, você também deve considerar essa vaga.

A duração do projeto é de, no mínimo, **5 meses**. 

## Local

100% Remoto

## Requisitos

**Obrigatórios:**
- 3+ anos de experiência com desenvolvimento.
- Conhecimento em React, Vue, Next.js e/ou Svelte.
- Conhecimento básico de GIT.
- Conhecimento em SASS/SCSS.

**Desejáveis:**
- Bom conhecimento em Svelte.
- Bom conhecimento em SvelteKit ou Next.js.
- Bom conhecimento em criação de componentes e outros frameworks como React ou Vue.
- Capacidade de gerar layouts responsivos.

**Diferenciais:**
- Conhecimento aprofundado em Svelte.
- Conhecimento aprofundado em SvelteKit.

## Benefícios
- Horário flexível (a combinar com você, mas sempre levando em conta daily e checkpoints).
- Poucas reuniões!
- 100% remoto.

## Contratação

PJ a combinar (disponibilizamos duas modalidades: escopo por horas trabalhadas ou pacote de horas mensal fechado)

## Como se candidatar

Por favor envie um email para vagas@sevn.technology com seu CV anexado - enviar no assunto: `Vaga Front Svelte`

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até **48 horas** após cada processo.
E-mail para contato em caso de não haver resposta: contato@sevn.technology

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by VictorPubh** [comment]
![image](https://user-images.githubusercontent.com/5835796/163854258-746bf001-87a7-423f-b786-b09a3054ba7b.png)

Enviei um desafio para a Sevn e não recebi retorno há 7 dias, o e-mail secundário simplesmente não existe.
