### ISSUE TITLE
[Remoto] Front-end Developer na Mercafacil

### ISSUE THREAD

**Issue by lucasportolima** [frontendbr/vagas#6382]
## Nossa empresa

A Mercafacil foi feita para fazer a diferença na transformação do varejo.

Temos certeza que podemos fazer isso quando tornamos possível entender as individualidades de cada um que estão no comportamento de compra e traduzir isso em conversão de vendas para o varejista.

Vamos muito além de sistemas, somos uma empresa feita por pessoas e para pessoas, que utiliza a tecnologia como um meio de sempre melhorar a experiência de consumo e diariamente aperfeiçoar o varejo de maneira criativa e funcional.

Ainda temos muito a fazer para melhorar a experiência do consumidor do varejo, e você pode fazer parte dessa história. Vem fazer história com a gente!

## Responsabilidades e atribuições

O Que Buscamos
Decisões orientadas a lógica
Senso de dono
Curiosidade e interesse de aprender
Trabalho em equipe
Seu Dia a Dia Será

Como Desenvolvedor (a) Front End sua missão será participar do desenvolvimento das interfaces Web e de todas as aplicações e produtos da Mercafacil, irá desenvolver componentes reutilizáveis com testes automatizados para garantir a estabilidade e reusabilidade do sistema. Deverá também participar ativamente nas decisões técnicas e de designer sobre ferramentas e abordagens que visam otimizar a performance do sistema e a experiência do usuário. Venha transformar o varejo conosco!

## Algumas De Suas Responsabilidades

- Desenvolvimento em VueJS;
- Desenvolvimento em React e React Native Web;
- Desenvolvimento utilizando Apollo para interagir com os backends em GraphQL;
- Desenvolvimento de componentes reutilizáveis e integrados com ferramentas como o Storybook;
- Desenvolvimento de testes automatizados para os componentes/telas;
- Manutenção, evolução e otimização das telas atuais de todos os produtos da Mercafacil.

## Requisitos e qualificações

Nosso Match Será Perfeito Se Você Tiver
- Experiência em desenvolvimento de SPAs em VueJS ou React/React Native;
- Experiência em desenvolvimento de componentes reutilizáveis;
- Experiência em testes automatizados.
- Diferenciais
- Experiência com GraphQL
- Experiência com arquitetura de microfrontend
- Experiência com bibliotecas de componentes compartilhados em StoryBook
﻿- Inglês intermediário

## Benefícios

🩺Saúde Em Primeiro Lugar

O que vamos te oferecer:
- Assistência médica Sulamérica;
- Assistência odontológica;
- Seguro de vida
- Gympass
- Licença maternidade/paternidade estendidas
😉Acreditamos Que Cada Pessoa é Única
- Benefícios flexíveis com o cartão Caju | VR/VA e mobilidade.
- Birthday-off para você comemorar seu niver
- Day-off para mudança de casa
👩💻Respeitamos Seu Jeito De Trabalhar
- Formato de trabalho híbrido: home office aqui é realidade!
- No Dress Code
🚀Queremos Que Sua Carreira Voe
- Avaliação de Desempenho duas vezes ao ano;
- Convênios corporativos
- Cultura de Feedback e 1:1 frequentes
#VemserMerca

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

Link para se candidatar: https://lnkd.in/dqDv26rJ

**Comment by eu-taua** [comment]
Olá me chamo Tauã, a vaga me despertou interesse, conheço uma boa parte das tecnologias necessárias e estou disposto a aprender o que ainda não domino. 
Ps: a vaga n tinha detalhe de por onde entrar em contato, se n for por esse email peço desculpas.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
