### ISSUE TITLE
[São Paulo] Front-End Developer Junior na Mccann Health

### ISSUE THREAD

**Issue by marciomaccann** [frontendbr/vagas#6386]
Características

• Média de 0 a 3 anos de experiência como programador;

• Paixão por aprender coisas novas;

• Comprometimento pela qualidade acima da média;

• Conhecimento teórico de TI de forma geral, em constante evolução;

• Interesse e conhecimentos sobre tecnologias mais recentes;

• Domínio dos recursos básicos da linguagem.

Responsabilidades:

• Projetos web ligados a comunicação;

• Corrigir bugs pequenos;

• Ajudar os desenvolvedores mais experientes (Site, LP, CMS, E-mkt etc);

• Ajudar em documentos e guias de requisitos funcionais;

• Noção de UX/UI;

• Controle de versão (Git/Bitbucket);

• Boas práticas de códigos, documentação, QA e segurança da informação.

Dia a dia:

• HTML5, CSS3, JavaScript (jQuery), SASS;

• Experiência em desenvolvimento web front-end;

• Integração com APIs

• ReactJS e/ou React Native;

• NodeJS / PHP;

• Wordpress;

• Vue.Js;

• GreenSock;

• Plataforma Veeva;

• Banco de dados;

• Deploy

Inglês é um diferencial.

Topa? Divide seu perfil com a gente no e-mail rh@mccannhealth.com.

Assunto: MH – Vaga Dev Jr – Seu nome

**Comment by vanessawin** [comment]
Candidatura  enviada, não tenho todos os pré requisitos mas acredito que para começar com E-mkt já será ótimo

**Comment by joaoreisjpk** [comment]
Olá boa tarde! A vaga é presencial ou remota?

**Comment by Djamess** [comment]
Enviei

**Comment by stiven104** [comment]
Enviei meu currículo. Eu não tenho todos os requisitos, PHP tive muito pouco no curso técnico que fiz, aliás não sei como faz funcionar PHP. Javascript só tive uma aula no meu curso técnico, mas pesquisei um pouco sobre está linguagem na Internet. React e ReactJS, não sei.

**Comment by BiaMLCastro** [comment]
Candidatura enviada! 

Ficaria muito feliz de ter uma chance de ter um bate papo com vocês!

Caso necessário, posso mandar meu CV também em inglês.

Desde já, obrigada!

**Comment by MellonFive** [comment]
Enviei um e-mail para concorrer a vaga de emprego. Obrigado pela a sua atenção.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
