### ISSUE TITLE
[São Paulo] Fullstack Developer Pleno na Mccann Health

### ISSUE THREAD

**Issue by marciomaccann** [frontendbr/vagas#6387]
Modelo Híbrido - São Paulo - SP

Características

Média de 5 anos como programador;
Disposição para ensinar o que sabe e aprender coisas novas;
Tem experiência em projetos dos mais variados tipos;
Iniciativa e busca maneiras diferentes de resolver problemas;
Foco em códigos, mas também nos principais aspectos do negócio

Responsabilidades

Projetos web ligados a comunicação (Site, LP, CMS, E-mkt etc);
Ajudar em documentos e guias de requisitos funcionais;
Noção de UX/UI;
Controle de versão (Git/Bitbucket);
Boas práticas de códigos, documentação, QA e segurança da informação.
Trabalhar sozinho ou em equipe como um líder;
Criação de código legível para outros desenvolvedores;
Habilidades de otimização de código para torná-lo mais eficiente;
Capacidade de quebrar as tarefas em tarefas menores;
Testes;
Revisar o código em detalhes;
Encontrar bugs e propor plano de ação para correção;
Domínio das principais linguagens da stack;
Orientar os desenvolvedores juniores.
Dia a dia:

Configurar o ambiente de desenvolvimento;
HTML5, CSS3, JavaScript (jQuery), SASS;
Integração com APIs;
ReactJS e/ou React Native;
NodeJS / PHP;
Wordpress;
Vue.Js;
GreenSock;
Plataforma Veeva;
Banco de dados;
Deploy

Inglês é um diferencial.

Topa? Divide seu perfil com a gente no e-mail rh@mccannhealth.com.

Assunto: MH – Vaga Dev Pl – Seu nome

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
