### ISSUE TITLE
[REMOTO] Estágio em Suporte na Codex Utilities

### ISSUE THREAD

**Issue by luanasantosog** [frontendbr/vagas#6388]
## Nossa empresa

Somos uma empresa do Grupo Imagem, com foco em desenvolvimentos especializados que combinam sistemas de informação, consultoria setorial, especialistas em tecnologia e melhores práticas de gestão para apoiar nossos clientes de forma integrada, atendendo aos mais diversificados processos de negócios.

## Local

Home Office

## Requisitos

**Formação:**
- Ensino Superior Cursando em Ciência da Computação, Engenharia da Computação, Engenharia Controle e Automação, Análise e Desenvolvimento de Sistemas e afins.

**Habilidades Desejáveis:**
- Conhecimentos em banco de dados SQL Server e Oracle;
- Automatização de rotinas de sistemas;
- Sistemas operacionais Windows, Linux e Android;
- Contato com linguagens de programação e Metodologia SCRUM.

**Responsabilidades:**
- Monitorar os alarmes das aplicações;
- Realizar a triagem de chamados, analisando cada solicitação e se necessário acionar o próximo nível de atendimento;
- Desenvolver soluções paliativas e definitivas dos sistemas (Front-End e Back-End);
- Desenvolvimento de scripts em SQL Server;
- Suporte remoto para solução e/ou orientação ao usuário final dos clientes;
- Apoiar na elaboração de material de indicadores para relatórios gerenciais;
- Aprender novas tecnologias e propor melhorias para os processos.

## Benefícios

- Alelo Refeição ou Alimentação;
- Seguro de vida.

## Contratação

Estágio

## Como se candidatar

Cadastre-se em: https://jobs.kenoby.com/codex-utilities/job/estagiario-nivel-superior-codex-utilities/61fa74440de1fd02b3328e08?utm_source=website

#### Alocação
- Remoto

#### Regime
- Estágio

#### Nível
- Júnior

**Comment by JailsonPaiva** [comment]
Candidatura enviada.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
