### ISSUE TITLE
[São Paulo] Front-End Developer Senior na DFO | eManage Development

### ISSUE THREAD

**Issue by eManageDevelopmentBr** [frontendbr/vagas#639]
## Descrição da vaga

A DFO busca um profissional com experiência no desenvolvimento de FrontEnd para liderar um time de desenvolvimento local de eCommerce e colaborar no desenvolvimento de projetos globais com equipes e NYC e Vancouver.

## Local

Escritório, São Paulo - Pinheiros

## Benefícios

- VR e VT

#### Diferenciais

- Flexibilidade de horário
- Home office 2x por semana
- sala de jogos 

## Requisitos

**Obrigatórios:**
- Conhecimentos avançados de html 5 e css
- Domínios de frameworks para uso responsivo como foundation ou bootstramp;
- Experiência com uso de pré-processadores de css como less, stylus, etc
- Experiência no desenvolvimento de frameworks e bibliotecas mv * / mvc modernas como angularjs
- Atenção aos detalhes e capacidade para escrever código para fronend otimizado, limpo e cross-browser;
- Experiência com a automatização de tarefas diárias (grunt / gulp / etc).
- Experiência em desenvolvimento de single page applications utilizando técnicas de front-end routing, client-side templating, consumo de json-baseado restful apis utilizando angularjs;

**Desejáveis:**
- Formação superior em engenharia da computação ou sistemas da informação;
- Inglês fluente

**Diferenciais:**
- Headless CMS

## Contratação

PJ a combinar

## Nossa empresa

Direct Focus Online, a DFO é uma empresa de marketing e tecnologia em rápida expansão. Através de nossas subsidiárias eManage Development, construímos plataformas de CRM e comércio eletrônico. Nós combinamos especialistas marketing, design, performance e tecnologia de machine learning e AI para construir o futuro do marketing digital. Queremos pessoas incríveis para nos ajudar com o nosso crescimento contínuo. O DFO é uma empresa global, contamos com escritórios no Canadá, Estados Unidos, Holanda, Hong Kong, Filipinas e Brasil. Se você gosta de tecnologia e marketing, junte-se a nós.

## Como se candidatar

Por favor envie um email para recrutamento@emanagecrm.com com seu CV anexado - enviar no assunto: Vaga Front End Developer Senior

**Comment by LFeh** [comment]
Aberto ainda?
