### ISSUE TITLE
[Remoto] Frontend Developer na ilove.me

### ISSUE THREAD

**Issue by mateu5-francisco** [frontendbr/vagas#6391]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-developer-193616087?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Como<strong> Front-end Develope</strong>r na ilove.me você vai:</p>
<p>● Criar software utilizado diariamente por milhares de utilizadores;</p>
<p>● Suporte às soluções, identificação de potenciais problemas e resolução dos</p>
<p>mesmos</p>
<p></p>

## ilove.me: 
 <p>ilove.me é uma plataforma one-stop-shop para o setor de Beleza, Estética e Bem-Estar com ERP completo e de fácil utilização, ferramentas de marketing e pagamentos integrados.</p>
<p>Ajudamos centenas de clientes a gerir as suas operações e a aumentar o seu faturamento, processando +100.000 agendamentos e +R$4.000.000 por mês</p><a href='https://coodesh.com/empresas/iloveme'>Veja mais no site</a>

 ## Habilidades: 
 - Ember.js 
- Rest e Restful APIs 
- UX 
- SPA - Single Page Application 
- CI/CD 
- Vue.js
## Local: 
 100% Remoto
## Requisitos: 
 - Ember.js 
- Experiência com conceitos de UX/UI 
- Experiência com Restful APIs 
- Bons conhecimentos em ferramentas de controle de versões (GIT) 
- Autonomia e sentido de responsabilidade 
- Forte motivação espírito de equipe
## Diferenciais: 
 - Experiência em desenvolvimento Front-end 
- Experiência com CI/CD, e bases de dados relacionais 
- Experiência em vue.js

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Developer na ilove.me](https://coodesh.com/vagas/frontend-developer-193616087?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
