### ISSUE TITLE
[Remoto] Tech Lead | Frontend Developer na Codeby

### ISSUE THREAD

**Issue by mateu5-francisco** [frontendbr/vagas#6392]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/tech-lead-or-desenvolvedor-frontend-150142464?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>rO seu dia a dia:</strong></p>
<p>Atuar no Front-end,  estruturação de requisitos de negócio para requisitos técnicos, análise de   dados,   gerenciamento   do   tempo,   aplicações   web,   componentes,   funcionalidades, sistemas e muito mais que envolve o mercado de Retail Tech. Você  será  responsável  pelo  auxílio  técnico  do  time  e  clientes, report  de  incidentes  e resultados  aos  líderes,  análise  de dados  e  estruturação  de  requisitos  de  negócio  para requisitos técnicos, além de desenvolver features para projetos de implementação de novos e-commerces e dar suporte/ manutenção em lojas VTEX (CMS &amp; IO).</p>
<p>Em VTEX CMS utilizará principalmente de JavaScript, HTML e CSS, enquanto em VTEX IO, poderá utilizar das mesmas linguagens além também do React Js</p>
<p></p>
<p><strong>O que buscamos:</strong></p>
<p>Buscamos  um  perfil  proativo  que  goste  de  estudar,  <strong>possua skill de  liderança,</strong>  tenha excelentes habilidades de comunicação verbal e escrita e saiba exemplificar de forma didática o conteúdo técnico.</p>
<p></p>
<p><strong>Aqui você tem oportunidade de se desenvolver e crescer profissionalmente.</strong></p>
<p><strong>Somos um Time! Se quer fazer parte de uma empresa na qual o bem mais valioso são as pessoas, aqui é o seu lugar..</strong></p>
<p><a href="https://coodesh.com/empresas/codeby" target="_blank"><strong><ins>Acesse nosso perfil para conhecer por quais VALORES somos guiados! </ins></strong></a>&nbsp;</p>

## Codeby: 
 <p>Há quase 7 anos no mercado de tecnologia, o Grupo Codeby contribui diariamente para o crescimento de negócios online de diversos segmentos e portes.</p>
<p>Somos uma empresa apaixonada por tecnologia, motivada a buscar constantemente as melhores e mais completas soluções para negócios digitais.</p><a href='https://coodesh.com/empresas/codeby'>Veja mais no site</a>

 ## Habilidades: 
 - GraphQL 
- Rest e Restful APIs 
- PostgreSQL 
- Java 
- React Native 
- React.js 
- Redux
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência com VTEX CMS, VTEX IO, VTEX APIs 
- Programação Orientada a objetos 
- Capacidade de modularização de desenvolvimento 
- Comunicação com o cliente para auxílio técnico 
- GraphQL | Utilização de GraphQL para consumo de APIs 
- Banco de Dados | Conhecimento em banco de dados PostgreSQL ou equivalente 
- Componentização | Criar componentes que possam ser reaproveitados 
- Orientação a objetos | Criação de classes reutilizáveis com Javascript 
- Conhecimento em React | Redux 
- Webpacker | Utilização da lib para uglify e minify de arquivos; automatização de rotinas; etc 
- Gulp | Utilização da lib para uglify e minify de arquivos; automatização de rotinas
## Diferenciais: 
 - Inglês
## Benefícios: 
 - Seguro de Vida 
- Assistência Odontológica 
- Assistência Médica 
- Day off no aniversário 
- Voucher Ifood mensal para Happy Hour
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Tech Lead | Frontend Developer na Codeby](https://coodesh.com/vagas/tech-lead-or-desenvolvedor-frontend-150142464?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
