### ISSUE TITLE
[REMOTO] Front-end React Developer na SQUADRA DIGITAL

### ISSUE THREAD

**Issue by CandiceTorres** [frontendbr/vagas#6394]
## Nossa empresa

Criamos negócios digitais de sucesso através de um mergulho profundo na experiência do cliente e com entregas ágeis durante todo o processo de criação e evolução de serviços e produtos digitais.

Somos apaixonados por tecnologia e por boas experiências, energizados por mudanças, movidos por gente. 

Você está pronto para fazer parte do nosso ecossistema digital? Vem ser Squader!

## Descrição da vaga

Desenvolvimento Front-end React 

## Requisitos
Experiência atuando no Frontend React com microfrontend;
Javascript;
Testes unitários no react;
Conhecer GIT / CI e CD;
Conhecimentos básicos de SQL;
Boas práticas de desenvolvimento (Solid, Design pattern);

## Benefícios
- Cuidado com a saúde física: Assistência Médica
- Sua saúde mental também é essencial: Parceria com a PlenaVi para consultas individuais de psicoterapia;
- Alimentar-se bem faz a diferença: Vale-refeição ou alimentação;
- Trabalhe de onde quiser: Auxílio Home Office;
- Horário flexível: jornada de 40h semanais, de segunda a sexta, alinhado com o projeto e time;
- Desenvolva-se mais: Acesso a cursos on-line da Udemy e Allura e auxílio certificação;
- Aproveite seu tempo livre: clube de benefícios com diversas parcerias e descontos exclusivos nos segmentos de bem-estar, educação, idiomas, gastronomia, serviços e produtos;
- SQ MATCH: Nosso programa de indicação de talentos que você é gratificado por cada indicação que for contratada;
- Participação em comunidades internas: apoio na jornada, troca de experiências, grupos de estudo e trilhas de aprendizado;
- Participação nos Lucros Anual: Conforme alcance de resultados da empresa
- One a one: Alinhamentos de expectativas de carreira e objetivos, momento de troca, safeplace;
- Interação entre colaboradores: Eventos internos periódicos;

## Como se candidatar
Por favor envie um email para candice.torres@squadra.com.br com seu CV anexado - enviar no assunto: Vaga REACT

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: candice.torres@squadra.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
