### ISSUE TITLE
[REMOTO] Front-end Developer React Sênior na Sysmap

### ISSUE THREAD

**Issue by mariacristinadeoliveira** [frontendbr/vagas#6395]
## Descrição da vaga

Será o responsável pela evolução e desenvolvimento de novas features e servirá de apoio técnico nas decisões; Possuirá papel fundamental na Squad, participando ativamente em ritos, tais como dailys, refinamentos de backlog, plannings, retros e reviews.

## Local

Remoto

## Benefícios

- Plano de saúde
- Plano Odontológico (Opcional) 
- VR

## Requisitos

- Javascript
- Vivência com React e seu ecossistema além de conceitos sólidos de componentização
- CSS e seus compiladores
- Integrações de APIs Rest e GraphQL
- CI/CD, entregas contínuas, deploy de aplicação em ambiente cloud, validação de código (Sonar) e versionamento de código (GIT)
- Desejável conhecimento em desenvolvimento orientado a testes (TDD/BDD)
- Desejável experiência com Azure DevOps
- Vivência com framework Scrum e cultura Agile com times multidisciplinares.

## Contratação

PJ ou CLT + Benefícios 

## Como se candidatar

Me chame no whats: (11) 971433182 https://wa.me/message/ZFKCG7H7JFYEF1 🤞
Ou se preferir envie seu CV para o email: maria.oliveira@sysmap.com.br

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
