### ISSUE TITLE
[Remoto] Senior React Developer na Onesight

### ISSUE THREAD

**Issue by kamiarc** [frontendbr/vagas#6396]
## Nossa empresa

A Onesight é uma multi-nacional com foco em desenvolvimento de tecnologias disruptivas e bleeding edge, atuamos com diversos clientes em múltiplos mercados e tecnologias.
No Brasil nossas atividades se concentram em outsourcing, e-commerces e plataformas customizadas.

## Descrição da vaga

Temos 1 vaga para senior (ou pleno quase senior) aberta :)
Atuação em múltiplos projetos com foco em React.JS e Javascript, interessante também conhecimento em backend (mesmo que mais básico), utilizaremos MeteorJS no projeto!

## Local

Remoto

## Requisitos

**Obrigatórios:**
- CSS3
- HTML5
- Avançado: Javascript
- Frameworks: React.JS

**Desejáveis:**
- MeteorJS e Node.JS
- Noções de Javascript dinâmico (sync,async,fetch...)
- Noções básicas de design e ux

**Diferenciais:**
- Ter algum projeto em MeteorJS
- Italiano básico (não é necessário, mas é um diferencial devido aos devs envolvidos no projeto)

## Contratação

PJ

## Como se candidatar

Por favor envie um email para trampos@onesight.com.br com seu CV anexado - enviar no assunto: SENIOR Meteor
**Importante**: Enviar: Nível, pretensão salarial e disponibilidade para início.
_Enviar também Github/lab com projetos realizados ou links de exemplos caso tenha algum online._

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias para devs aprovados ao menos para a segunda fase.
E-mail para contato em caso de não haver resposta: responder o e-mail do teste

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Senior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
