### ISSUE TITLE
[Remoto] Front-end Developer PL/SR no Letras.mus.br

### ISSUE THREAD

**Issue by rhletras** [frontendbr/vagas#6399]
## Nossa empresa

Somos uma empresa de tecnologia fundada em 2003 e feita por pessoas que amam música, novas tecnologias e desafios. Trabalhamos com intensidade, unindo criatividade e inovação para desenvolvermos, juntos, produtos incríveis, de alto padrão de qualidade e longevidade. Nosso site Letras é líder em audiência na América Latina e, hoje, mais de 40 milhões de pessoas de todos os lugares e gostos musicais acessam e compartilham letras de músicas, traduções, álbuns e muito mais.

Estamos crescendo e queremos ir ainda mais longe: o Letras Academy nasceu para que milhares de pessoas possam aprender idiomas de um jeito descomplicado e divertido com a ajuda da música. Com este novo projeto, buscamos nos tornar uma grande EdTech. 

E você, quer fazer parte dessa jornada com a gente?

## Descrição da vaga

Procuramos pessoas com grande experiência em Desenvolvimento Frontend para fazer parte do time Letras!

O time de Frontend do Letras cuida de produtos que são visitados por milhões de pessoas todos os dias! Por isso, precisamos ir além dos frameworks e dominar os fundamentos das linguagens. Nosso trabalho é feito com foco em performance e atenção a cada detalhe, e baseado na colaboração e compartilhamento de conhecimento.

Como parte do time, você irá contribuir com o desenvolvimento de novas features e manter o Letras.mus.br, o Letras Academy  (nossa mais nova plataforma de ensino) e o Ouvir música. Buscamos sempre utilizar tecnologias de ponta, por isso você estará em constante aprendizado e evolução.

## Local

Remoto 

## Requisitos

**Obrigatórios:**
- Experiência relevante em aplicações feitas em React, experiência usando hooks;
- Experiência em testes (React Testing Library);
- Conhecimento em Javascript (ES6+);
- Experiências com CSS componentizado. (Stitches e/ou similares);
- Conhecimento e/ou experiência com GraphQL;
- HTML semântico;
- Experiências com Flexbox e Grid Layout;
- Técnicas de performance, SEO e acessibilidade.

**Diferenciais:**
- Conhecimento em Next.js;
- Conhecimento em GraphQL/Apollo;
- Conhecimento em Cypress;
- Conhecimento Typescript.

## Benefícios

- Salário compatível com o mercado, de acordo com o nível de senioridade;
- Vale-refeição ou vale-alimentação (R$39,20/dia de trabalho);
- Plano de saúde Unimed - pagamos toda a mensalidade de seu plano de saúde e parte da coparticipação em consultas, exames e procedimentos médicos;
- Plano odontológico;
- Auxílio-home office
- Flexibilidade para controlar o seu horário de trabalho;
- No dress code! Vista-se como se sentir confortável; 

**Carreira:**
- Participação em cursos, eventos e treinamentos custeados pela empresa, para você poder se desenvolver cada vez mais;
- Oportunidades reais de crescimento de carreira;
- Trilha de desenvolvimento personalizada para você;
- Ambiente informal com muita horizontalidade! 

## Contratação

CLT

## Como se candidatar

A inscrição para a oportunidade deve ser feita exclusivamente através do link: https://bit.ly/3L4C3Dx

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
