### ISSUE TITLE
[São Paulo] Desenvolvedor Front-End -  Viajanet

### ISSUE THREAD

**Issue by victorgsouto** [frontendbr/vagas#64]
## Descrição da vaga

Buscamos um desenvolvedor Front-End afim de encarar alguns desafios e vontade de aprender.

## Local

Alocado, São Caetano do Sul- SP 

## Benefícios

- Horário Flexível

## Requisitos

**Obrigatórios:**
- HTML
- CSS (LESS/SASS)
- JavaScript
- Utilizar padrões e boas práticas para desenvolvimento
- Experiência com Controle de Versão 

**Desejáveis:**
- Angular 1
- Automatizadores

**Diferenciais:**
- Angular 2
- conhecimentos em C#
- Perfil Dinâmico

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para vqsouto@viajanet.com.br com seu CV anexado - enviar no assunto: Desenvolvedor Front-End

**Comment by LFeh** [comment]
\o

**Comment by brugomes** [comment]
A vaga é temporária ou é fixa? CLT ou PJ  como descrito?

**Comment by victorgsouto** [comment]
@brugomes A vaga é fixa, e PJ. =)

**Comment by brugomes** [comment]
Legal, @victorgsouto. Vou enviar meu cv... moro praticamente do lado. =)

**Comment by LFeh** [comment]
Boa sorte @brugomes ;)

**Comment by victorgsouto** [comment]
@brugomes estou passando os cvs pro RH, não recebi o seu. =)

**Comment by brugomes** [comment]
@victorgsouto acabei de enviar! =)
Obrigada, @LFeh!!

**Comment by grippado** [comment]
@LFeh a vaga é PJ como o @victorgsouto comentou, troca o label CLT que ta ai, que pode confundir a galera! =)

**Comment by LFeh** [comment]
;)

**Comment by matheusmpessoa** [comment]
@victorgsouto acabei de enviar :)

**Comment by wgleen** [comment]
@victorgsouto cv enviado o/

**Comment by LFeh** [comment]
Conseguiu @victorgsouto ?

**Comment by victorgsouto** [comment]
Consegui @LFeh, valeu pela força!!!

**Comment by LFeh** [comment]
Parabéns e boa sorte ;)

**Comment by camilatigre** [comment]
@victorgsouto 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by victorgsouto** [comment]
@camilatigre foi por aqui Sim.
