### ISSUE TITLE
[São Paulo] Front-end Developer Senior na Arizona

### ISSUE THREAD

**Issue by raymonsanches** [frontendbr/vagas#640]
## Descrição da vaga

- Criar uma base sólida para os novos produtos e iniciativas;
- Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas;
- Participar do processo criativo e auxiliar na construção dos sistemas;

## Local

Remoto / Chácara Santo Antônio - São Paulo, SP

## Requisitos

**Obrigatórios:**
- Experiência com HTML5, CSS3 e JavaScript
- Habilidade em participar de todas as etapas do desenvolvimento das interfaces
- Manjar de git
- Ter trabalhado com metodologias ágeis
- Trabalhar com pré-processadores CSS

**Desejáveis:**
- Conhecimento em algum framework JS (Ember, Angular, Backbone, React)
- Já ter interagido com sistemas em PHP

**Diferenciais:**
- Alguma vivência com desenvolvimento mobile (usando Ionic, Cordova, Phonegap)

## Contratação

CLT

## Como se candidatar

Manda um e-mail para ramon.sanches@arizona.global com seu CV anexado - enviar no assunto: Vaga Front-end

Qualquer dúvida podem mandar para o mesmo e-mail também que eu respondo.

**Comment by XLucifer** [comment]
A vaga ainda está aberta?

**Comment by raymonsanches** [comment]
Está sim @XLucifer ;)

**Comment by ribeiroevandro** [comment]
Enviado!

**Comment by darlanmendonca** [comment]
feras, a vaga é alocado ou remoto?

**Comment by camilatigre** [comment]
@darlanmendonca eu acho que vai depender do nível e da negociação, to chutando. pelo menos foi assim quando entrei.

**Comment by darlanmendonca** [comment]
@camilatigre verdade, pode ser mesmo.
Brigadão!!

**Comment by raymonsanches** [comment]
Isso mesmo @darlanmendonca, tem possibilidade de remoto total/parcial ou alocado (tem quem prefira). Depende da negociação mesmo.

**Comment by darlanmendonca** [comment]
@raymonsanches super bacana!!

**Comment by lucas-lopes** [comment]
Só pra tirar uma dúvida! A vaga é pra sênior, mas se um júnior achar que tem esses requisitos e alguma coisa dos diferenciais tbm pode se candidatar? rsrsrs Ou a casca é mais grossa em relação a conhecimento do que está parecendo para esse trampo?

**Comment by jvgm** [comment]
@raymonsanches  está aberta a vaga? Enviei :+1:

**Comment by raymonsanches** [comment]
Moderadores, podem fechar essa issue? Vou abrir outra, please.

**Comment by lucasfernandes** [comment]
Enviado!

**Comment by santoja** [comment]
@raymonsanches você pode fechar a vaga clicando em "Close issue" do lado do botão "Comment" embaixo da caixa de comentários =)

**Comment by raymonsanches** [comment]
caraca, comi bola aqui @santoja valeu ;)
