### ISSUE TITLE
[REMOTO] Front-end Developer na Datum ✨ | VEM FAZER PARTE DO PLANETA ROXO  💜 

### ISSUE THREAD

**Issue by julianakraemer** [frontendbr/vagas#6400]
## Nossa empresa

A Datum é uma empresa GPTW (Great Place to Work) pelo segundo ano consecutivo e a nossa principal proposta é ativar o protagonismo, por isso investimos pesado no desenvolvimento dos nossos colaboradores.

## Descrição da vaga

oportunidade para atuar como Dev Front-end React Sênior
## Local

100% Remoto
## Requisitos

- HTML5, CSS3,
-  Pré Processadores (Sass),
-  JavaScript ES6,
- React Js,
- Next.js,
- Typescript,
- Automatização de Builds (Npm, Yarn, Gulp, Webpack),
- Design Responsivo Web,
- Controle de Versionamento (Git);

**Diferenciais:**
Conhecimento em E-commerce, ter trabalhado com metodologia ágil;

## Benefícios

Vale transporte
Vale refeição/alimentação
Auxílio Home Office
Gympass
Plano de saúde
Plano odontológico
Seguro de vida
Cíngulo (saúde mental)
Assessoria financeira, jurídica e psicológica para funcionários
 
Aqui na Datum, você também vai ter:

Protagonistas (game de incentivo à carreira do colaborador)
Datum Academy (programa de capacitação e treinamentos)
English Class
Ginástica Laboral
Rock Leader (programa de formação de liderança)
+Felicidade (iniciativa que visa a felicidade do colaborador

## Como se candidatar

Por favor envie um email para juliana.kraemer@datum.inf.br com seu CV anexado - enviar no assunto: Vaga React

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
