### ISSUE TITLE
[Remoto] DevOps Pleno na @AmbizzionIT

### ISSUE THREAD

**Issue by NicolasDurazzo** [frontendbr/vagas#6401]
## Nossa empresa

É uma empresa provedora de serviços e soluções integradas de sistemas, alinhadas com as principais estratégias corporativas através de uma equipe altamente qualificada. Nossa experiência e comprometimento traduzem o alto nível de satisfação e reconhecimento dos nossos clientes.

## Local

100% remoto

## Requisitos

**Obrigatórios:**

✅ Conhecimento de sistemas operacionais Linux e Windows e suas distribuições;

✅ Conteinerização de Aplicações (Docker);

✅ Conhecimento em ferramentas para provisionamento de Infraestrutura (Terraform);

✅ Execução de projetos básicos de infraestrutura, redes e sistemas em cloud;

✅ Implementação de jobs e pipelines básicos em ferramentas de entregas contínuas utilizando automação de processos CI/CD (Git, Jenkins, CodePipeline, CodeBuild, Azure DevOps);

✅ Elaborar e/ou Auxiliar em planos de migração de aplicações e infraestruturas tradicionais para Cloud Computing;

✅ Domínio dos pilares AWS Well-Architected;

✅ Mínimo de 1 ano de experiência;

✅ Metodologia Ágil.

## Contratação

PJ 

## Como se candidatar

Por favor envie um email para nicolas.durazzo@ambizzion.com.br com seu CV anexado - enviar no assunto:
- Vaga DevOps

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 48 horas após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
