### ISSUE TITLE
[Cidade] Senior QA Analyst na Pasquali Solution 

### ISSUE THREAD

**Issue by Recrutas** [frontendbr/vagas#6402]
**Descrição da vaga**

Estamos procurando pessoas que tenha uma vasta experiência em Analista de QA.

**Local**

Remoto

**Requisitos Obrigatórios:**

•	Compreensão das principais práticas de teste de software
•	Experiência com testes de API para a executar testes manuais e automatizados 
•	Experiência com detalhamento de casos teste com Gherkin
•	Experiência na realização de testes pós-lançamento / pós-implementação 
•	Experiência com Cypress ou Selenium 

**Diferencial:**

•	Alguma vivência com testes automatizados
•	Experiência com Java
•	Rest-assured
•	Spring Boot
•	Test
•	Junit
•	BDD

**Contratação**

PJ - Valor a combinar.

**Como se candidatar?**

Envie seu currículo: https://bit.ly/3AmEvAd 
Envie seu currículo: danielle.luciano@pasqualisolution.com.br

**Labels**

•	Alocado
•	PJ
•	Sênior 

**Sobre a Pasquali**

A Pasquali Solution é uma consultoria com foco em Alocação de profissionais de TI reconhecida pelo seu trabalho rápido e com excelência.
Estamos há mais de 18 anos no mercado e somos altamente especializada em Tecnologia da Informação.
Vantagens
•	Parceria com a Alura para cursos
•	Gratificação no mês de aniversário

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
