### ISSUE TITLE
[Remote - LATAM] React Native Developer na Podopolo - USD 75k-100k

### ISSUE THREAD

**Issue by TheAleSch** [frontendbr/vagas#6403]
## Descrição da vaga

As a Senior Front End React Native Developer with Podopolo, you will be responsible for delivering the best digital mobile app user experience in collaboration with colleagues and other contributors. Working mainly on the front-end of our react native application you will build user-facing components and implement them through an agile workflow and collaborative process.

Your primary task is to contribute to the development of a stable, robust, aesthetic and maintainable product. Outstanding Podopolo team members are research and user driven, accountable, trustworthy, transparent in communication, collaborative, and able to build lasting relationships with their teams.

This position will report to the Director of Development.

In order for your application to be considered, you must have contributed to the development of a native mobile app.

## Local

Remoto

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ X/dia
- Auxílio creche
- ...

#### Diferenciais

-Competitive base salary
-Excellent health benefits
-Accelerated career growth & investment in your learning
-Work from home
-Emphasis on results not how or where you get it done
-Great people!
-A big mission to do good in the world!

## Requisitos

**Obrigatórios:**
-Minimum 5 years of experience with Javascript, Typescript, React and React Native.
-Minimum 2 years Swift experience and frontend Kotlin/Java experience.
-Expert experience with HTML & CSS including deep understanding of best practices.
-Experience with object-oriented design & development.
-Prior experience in a similar role with an early stage, fast paced start-up in an agile environment is required.
-Proven expertise with consumer apps, ideally with social and gamification features.
-Experience working with social apps.
-Ability to work both collaboratively and independently with excellent communication and interpersonal skills.
-Ability to work fast and efficiently, minimizing error while maximizing output.
-Experience with Jira and Confluence is preferred, but not required.
-A portfolio of professional react native app development work for mobile apps.
-A collaborative workflow and decision making process.

**Desejáveis:**
-Experience with blockchain development
-Experience with AR/VR and associated technology
-Knowledge of spatial audio
## Contratação

Contrato direto com a empresa, te ajudamos em todo o processo.

## Nossa empresa

Podopolo is a mission-driven interactive multimedia company dedicated to democratizing discovery, engagement, and monetization of podcast audio + video content, shifting the balance of power for independent content creators globally and advancing a social impact mission for world-changing outcomes.

This is a fast-scaling, dynamic company with a big vision and game-plan to offer innovative and differentiated products that meet the needs and wants of all our customers – podcasters, advertisers, and consumers. Across Podopolo, we’re building a creative, joyful, and “think different” culture where collaboration is essential, diverse voices are heard, and inclusion and innovation are the keys to our success.
## Como se candidatar

https://www.linkedin.com/jobs/view/2590719734/?refId=I6AwF6ucQTijfNrUFm7V8w%3D%3D

#### Alocação

- Remoto

#### Regime
- Outro
- PJ

#### Nível
- Sênior
- Especialista

**Comment by TheAleSch** [comment]
I worked on this company last year and it was def. a great experience.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
