### ISSUE TITLE
[Uberlândia-MG/Campinas-SP] Front-End Developer na Zup

### ISSUE THREAD

**Issue by isacjunior** [frontendbr/vagas#641]
## Descrição da vaga

A Zup procura pessoas apaixonadas por tecnologia, inovadoras, proativas, loucas por desafios e que queiram transformar o mundo em um lugar mais digital!

Aqui na Zup o Desenvolvedor Front End é responsável pelo desenvolvimento dos produtos mais inovadores do mercado atuando no desenvolvimento de telas manutenção preventiva e evolutiva, além de trazer críticas, novas ideias e ferramentas, com o objetivo de melhorar o desenvolvimento e experiência do usuário.

## Local

Campinas - SP e Uberlândia - MG

## Benefícios

- Plano de saúde
- Seguro de vida
- PLR
- Plano Odontológico
- Vale Alimentação
- Vale Transporte
- Bônus para treinamentos e cursos

## Requisitos

**Obrigatórios:**
- Boa comunicação e gostar de trabalhar em equipe.
- Experiência com desenvolvimento em HTML, CSS, e principalmente JavaScript.
- Experiência com Angular ou React.
- Experiência com REST e Integração de API.
- Git

**Desejáveis:**
- ES6/7/8
- Clean Code
- Flexbox
- Redux

**Diferenciais:**
- Projetos Opensource
- Graphql

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie me um email para isac.junior@zup.com.br com seu CV anexado - enviar no assunto: Vaga Front-End

**Comment by isacjunior** [comment]
Labels:
Júnior, Pleno, Sênior, CLT, Alocado.

**Comment by LFeh** [comment]
Aberto ainda?
