### ISSUE TITLE
[100% Remoto] Senior Front-End Developer (React.js) na Seven Apps

### ISSUE THREAD

**Issue by LuizaVilaca** [frontendbr/vagas#6411]
**Descrição da Vaga**
Está em busca de novos desafios?! E se você pudesse atuar em um projeto internacional incrível, e ainda receber todo o suporte de colegas brasileiros de alta performance?

Na Seven, você vai estar próximo das melhores tecnologias do mercado, trabalhar em projetos desafiadores e em um ambiente rico em aprendizado. Estamos procurando devs proativos, experientes e que estejam em busca de vivenciar essa imersão na cultura do mercado norte-americano.

Nessa posição, você poderá atuar em projetos de grandes empresas clientes nacionais e internacionais, e terá autonomia e liberdade para trabalhar 100% remoto, com flexibilidade de horário. Os seus desafios irão envolver o desenvolvimento front-end web (React.js); Você terá um time altamente capacitado para implementar essas soluções com você.

Nós acreditamos que a Tecnologia tem o poder de transformar o mundo e melhorar a maneira como vivemos e enfrentamos os desafios. Se você também acredita nisso, vem fazer parte do nosso time!

**Local**
100% remoto com horário flexível

**Requisitos**
Experiência comprovada de pelo menos 3 anos em React.js ou desenvolvimento web
Conhecimento em styled-components ou semelhantes
Conhecimento em Typescript
Conhecimento em Git
Conhecimento com algum gerenciador de estado global(redux, mobx, zustand, recoil… ou outros)
Conhecimento em SEO
Familiaridade com SSR(next js, Gatsby ou razzle)
Familiaridade com jest, Testing Library
Familiaridade com algum CI/CD
Experiência com metodologias ágeis (SCRUM)
Profissional proativo e organizado, comunicativo;
Inglês avançado (para oportunidades internacionais)

**Contratação**
PJ (no caso de alocações internacionais, recebimento em dólar pela sede de Miami da Seven Apps, com redução de impostos, quando comparado à tributação PJ do Brasil)

**Benefícios**
_Revisão salarial periódica:_ revisão a cada 6 meses;
_15 Dias de descanso remunerado:_ férias remuneradas por 15 dias corridos
_Horário Flexível:_ trabalhe no horário que se sentir mais produtivo
_Workshops periódicos:_ momentos com todo o time, gerando uma comunidade de trocas de conhecimento e desenvolvimento entre os nossos top 1% devs;
_Acompanhamento semanal:_ reuniões semanais com os Teach Leads e gestores dos projetos;
_Imersão Internacional:_ cultura internacional com projetos fora do Brasil;
_Bônus por indicação:_ nos ajude a trazer os melhores devs para nosso time

**Como se candidatar:**
Envie um e-mail para: [rh@sevenapps.com.br](mailto:rh@sevenapps.com.br)

**Nossa empresa**
Somos mais que uma empresa, somos um estilo de vida baseado na paixão em solucionar problemas usando design, usabilidade e tecnologia. Nosso propósito é unir os melhores profissionais do mercado em projetos nacionais e internacionais, com um crescimento de carreira e troca interna de alta velocidade. Nosso time aprende, evolui e compartilha.

Com um escritório administrativo em Belo Horizonte e uma sede em Miami, já crescemos mais de 300% no último ano e ajudamos nossos clientes a crescerem mais de 120% com alocação dos nossos profissionais sênior e/ou desenvolvimento de aplicativos e softwares de alta performance.

Conheça mais o nosso código Seven Apps: https://www.sevenapps.tech/

**Comment by pedroch4610** [comment]
Olá! O Inglês avançado é requisito obrigatório para a a vaga? Obrigado!

**Comment by LuizaVilaca** [comment]
Boa tarde, Pedro! Tudo bem?

Ficamos contentes com o seu interesse em fazer parte da SevenApps!

Para a vaga que ainda temos de React.js, não é exigido inglês avançado, mas
é recomendado que o candidato saiba/entenda pelo menos um pouco. O
requisito exigido é que tenha no mínimo 4 anos de experiência.

Atenciosamente,



Em seg., 7 de fev. de 2022 às 08:57, Pedro Francisco <
***@***.***> escreveu:
