### ISSUE TITLE
[Remoto - Atlanta, United States] Senior Python/Django Developer @ Pinestraw

### ISSUE THREAD

**Issue by VinPinestraw** [frontendbr/vagas#6412]
[Remoto] Senior Python/Django Developer

Vaga para trabalho remoto full-time na [Pinestraw](https://www.pinestraw.enterprises/) (localizada em Atlanta/US).

Não é uma vaga freelancer, é para trabalho full-time, de segunda a sexta, em horário comercial, 40h por semana. O contrato de trabalho pode ser W-2 (se você tiver cidadania americana), contrato PJ ou como funcionar melhor para você (pode ser até por bitcoin).

Abaixo seguem os detalhes da vaga em inglês, caso deseje mais informações sobre a vaga ou se candidatar envie um e-mail para [vin@pinestraw.org](mailto:vin@pinestraw.org) com sua pergunta e /ou currículo EM INGLÊS.

### Senior Python/Django Developer

Technologies:
- Django
- Python
- MySQL
- Heroku

Years of experience: 5+

Required knowledge: 
- Advanced English speaking ability
- Team lead ability (you would be leading over 2 devs)

Plusses:
- Able to start now
- Has some frontend experience
- ML would be a plus but definitely not required

Benefits:
- USD Salary
- Equipment as needed (mac payback program as well)
- Fully remote

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
