### ISSUE TITLE
[REMOTO] Front-End Developer na @TRUSTLY

### ISSUE THREAD

**Issue by Trustly-br** [frontendbr/vagas#6416]
## Você conhece a Trustly?

Fundada em 2008, a Trustly é líder global em Open Banking Payments, e estamos em rápida expansão no mercado dos EUA! Hoje atendemos 10.000 clientes, conectando-os com mais de 650 milhões de consumidores e 7.600 bancos em mais de 30 países. Em 2021, processamos mais de US$ 20 bilhões em volume de transações em nossa rede global!
 
Nossa plataforma digital conta a conta redefine a velocidade, simplicidade e segurança dos pagamentos. Os consumidores pagam pelas compras simplesmente entrando em suas contas bancárias, ignorando as redes de cartões e nunca saindo do site ou aplicativo de um cliente - sem necessidade de números de cartão de crédito ou configuração de conta separadamente.
 
Com escritórios em Vitória, Brasil, Vale do Silício nos EUA e sede global em Estocolmo, Suécia, somos uma equipe culturalmente diversificada, e em todo o Brasil, adotamos a política de trabalho remoto em casa!
 
É um ótimo momento para ingressar na Trustly, pois a equipe das Américas está crescendo rapidamente. Se você prospera em um ambiente de trabalho com espírito empreendedor, ritmo acelerado, casual, profissional, positivo e gratificante, esse é o seu lugar!

## Sobre o time que você trabalhará:

A equipe de Customer Experience é responsável por toda a camada de apresentação da Trustly para nossos clientes. Nosso foco é oferecer a melhor experiência com uma plataforma simples, eficiente e acessível!

## No seu dia a dia, você irá:

- Trabalhar no desenvolvimento e manutenção de código do lado do cliente para produtos baseados na web usando tecnologias como JavaScript e React.
- Otimizar aplicativos da Web para maximizar a velocidade e a escala.
- Atuar ativamente no planejamento de sprints e reuniões de scrum com equipes em Vitória, São Francisco (sede) e outras localidades.

## O que esperamos de você:

- Graduação em Ciência da computação ou áreas relacionadas;
- Experiência em desenvolvimento de sistemas de software;
- Compreensão da estética do layout e iniciativa para criar experiências de UX pensadas e páginas da Web perfeitas em pixels;
- Boas habilidades de codificação em Javascript (ES6), HTML e CSS;
- Experiência com React Framework.
- Habilidade de codificação e compreensão dos conceitos OO;
- Experiência anterior com controle de origem.

## Local

100% Remoto, mas temos um escritório em Vitória/ES. 

## Nossos benefícios e mimos são:

- Plano de saúde e odontológico Bradesco - pra você e seus dependentes, sem custo de coparticipação;
- Seguro de vida Sulamérica com coberturas diferenciadas; 
- Vale refeição e Vale alimentação;
- Gympass - Plataforma que dá acesso a espaços de atividades físicas e aulas on-line;
- Ginástica laboral online;
- Trustly Club - Desconto em instituições de ensino e lojas parceiras;
- Happy hours mensais com cupom iFood - A gente contrata uma banda pra fazer um show só pra gente, viu?
- Programa de inglês - Aqui você tem espaço pra desenvolver o seu inglês, e além das lições, pode fazer aulas quinzenais de conversação;
- Licença maternidade e paternidade estendidas;
- Flexibilidade de horário;
- Welcome Kit - Trabalhamos com equipamentos Apple (Macbook Pro, Iphone) e enviamos mais vários mimos! Alerta de spoiler: Os equipamentos podem ser adquiridos por você de acordo com os critérios internos!
- Prêmio anual - Como integrante do nosso time, você se qualifica para o recebimento de um bônus anual, a critério da empresa, baseado no atingimento dos nossos KPI's. 

## Contratação

CLT

## Como se candidatar

Por favor, cadastre-se nesse link: https://jobs.lever.co/trustly/7c447533-2325-41b7-a4ab-9afd2039721c?lever-via=LODm9ZrsKt

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: cherryne.zambon@trustly.com

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
