### ISSUE TITLE
[São Paulo-SP] Front-End Developer Netsuite Pleno na LaPLuS PM&C Gestão Empresarial Ltda

### ISSUE THREAD

**Issue by fbis42** [frontendbr/vagas#6418]
## Descrição da vaga ##

Front-End Developer Netsuite - Pleno

Requisitos: 
- Experiência mínima de 3 anos trabalhando com serviços baseados em SOAP / RESTful e XML; 
- Experiência no desenvolvimento de aplicações web utilizando: Node.js, JavaScript, Vue.js e /ou React.js; 

Diferenciais: Experiência no desenvolvimento usando SuiteScript – Oracle NetSuite; WorkFlow e formulários PDF;

- Formação: Tecnologia da Informação ou similares;
- Idiomas: Inglês (avançado) | Espanhol (básico) 

- Contratação: PJ/Cooperado
- Trabalho: 100% Home-office
- Local: 100% remoto [São Paulo- SP]

## Como se candidatar
Por favor envie um email para rh@laplus.com.br com seu CV anexado, informando sua disponibilidade para inicio imediato e pretensão salarial. Enviar no assunto: Vaga Front-End

#5825

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
