### ISSUE TITLE
Front-end Developer na Nexmuv

### ISSUE THREAD

**Issue by Isabelacarrasco** [frontendbr/vagas#6420]
## Descrição da vaga

Atuar na construção e manutenção de aplicações de alta escalabilidade e criticidade para o negócio com foco no produto Carteira de Cupons.
Desenvolver e sustentar aplicações de alta disponibilidade e escalabilidade;
Cooperar no desenho de arquiteturas, evolução e construção de sistemas robustos para o contexto de carteira digital;
Participar em definições de estratégia técnica do contexto de carteira digital - cupons 
Apoiar demais membros do time no desenvolvimento e evolução técnica;
Propor e aplicar a substituição de sistemas legados por novas soluções que se alinham a estratégia da empresa;

## Local
Remoto 

## Requisitos

**Obrigatórios:**
Experiência em desenvolvimento frontend com framework ReactJS;
Experiência de integração com APIs REST e arquiteturas em micro-serviços;
Experiência de desenvolvimento em containers (Docker, K8S);
Experiência com ferramentas de qualidade de código e testes automatizados;
Conhecimento da cultura DevOps;
Experiência com troubleshooting e tracing de erros;
Experiência com cerimônias e métodos ágeis;
 Experiência com desenvolvimento em sistemas Linux ou Mac;

## Contratação

PJ 

## Como se candidatar

Por favor envie um email para email isabela.padilha@nexmuv.com.br

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
