### ISSUE TITLE
[100% remoto] Front-end Developer na Unbox

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#6421]
## Nossa empresa

A Unbox desenvolveu um SaaS para ajudar pequenos ecommerces a vender e construir sua presença no ambiente online. Com mais de 4.000 clientes, a empresa está crescendo cada vez mais. 

Para algumas vagas do time de Produto e Tecnologia, como esta, a Unbox está focando as contratações em grupos ainda minoritários nestas áreas, especialmente mulheres, pessoas pretas e pessoas LGBTQIA+.

**Se você não faz parte desses grupos, indique alguém!**

## Descrição da vaga

Criar interfaces e sistemas para milhares de lojistas e seus clientes, prezando sempre pela qualidade do código, alta cobertura de testes e capacidade de escala. Participar ativamente das discussões de arquitetura, desenvolvimento do produto como um todo.

## Local

Remoto

## Requisitos

**Obrigatórios:**

- Trabalha bem com Git
- Conhece Next.js
- Tem experiência profissional com testes unitários, React e com a maior parte dessas ferramentas: React Hooks, React Context API e GraphQL (apollo)
- Tem familiaridade com construção de telas a partir de prototipos em ferramentas como Figma

**Desejáveis:**

- CSS in JS (Styled Components)
- Webpack / Babel
- Conceitos de acessibilidade, UI e UX
- Escrita de testes de integração com Cypress

**Diferenciais:**

- TypeScript
- PWA
- Google Web Vitals / Web Performance
- Otimizações para SEO

## Benefícios

- Salário compatível com o mercado em contratação PJ
- Plano de Saúde com cobertura nacional (Allianz, sem co-participação)
- Trabalho totalmente remoto
- Cartão de Benefícios Flash
- Gympass

## Contratação

PJ a combinar

## Como se candidatar

Clique aqui para [preencher o formulário](https://form.jotform.com/211945946053662). Se preferir, envie seu CV com Github para o email tatiana@remotar.com.br, que o mesmo será encaminhado diretamente para a Unbox.

Obs: a Unbox é cliente da [Remotar](https://remotar.com.br/), que esta auxiliando na divulgação da vaga. No entanto, todo o processo seletivo ocorrerá diretamente com a Unbox. 

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
