### ISSUE TITLE
[Remoto] Frontend Mobile Developer na Similar Souls

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6424]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-mobile-developer-115628222?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>Similar Souls </strong>criadora do<strong> Veggly </strong>está buscando <strong>Frontend Mobile Developer</strong> para compor seu time!</p>
<p>A Similar Souls é uma startup fundada em 2019 por 2 engenheiros de computação da USP com o objetivo de usar a tecnologia para aproximar pessoas com valores e estilos de vida similares. Para isso, a empresa desenvolve apps que permitem encontrar parceiros ou novos amigos. Somos membros da incubadora Cubo Itaú e recebemos investimento do fundo canadense Loyal VC.</p>
<p>O Veggly é o maior app de namoro vegano e vegetariano do mundo, com mais de 600 mil usuários em dezenas de países. O app ajuda a conectar pessoas que se preocupam com os animais ou que buscam um estilo de vida mais sustentável e saudável. Se estima hoje que de 5% a 10% da população mundial é vegetariana e é um estilo de vida que cresce dia após dia. Estamos também em fase de lançamento de um novo app e com outros em fase de planejamento.</p>
<p>O profissional será responsável por ajudar a levar o <strong>Veggly</strong> para o próximo patamar, através de:</p>
<ul>
<li>Um roadmap robusto de novas funcionalidades e novo UX/UI.</li>
<li>Desenvolvimento de aplicativos móveis Android/iOS de acesso em larga escala por usuários globais.</li>
<li>Elaboração e execução de scripts de testes.</li>
<li>Intenso trabalho em equipe com os diretores no desenho de novas funcionalidades e na garantia do bom funcionamento do app.</li>
</ul>
<p></p>

## Similar Souls: 
 <p>A Similar Souls é uma startup fundada em 2019 por 2 engenheiros de computação da USP com o objetivo de usar a tecnologia para aproximar pessoas com valores e estilos de vida similares. Para isso, a empresa desenvolve apps que permitem encontrar parceiros ou novos amigos. Somos membros da incubadora Cubo Itaú e recebemos investimento do fundo canadense Loyal VC.</p>
<p>O Veggly é o maior app de namoro vegano e vegetariano do mundo, com mais de 600 mil usuários em dezenas de países. O app ajuda a conectar pessoas que se preocupam com os animais ou que buscam um estilo de vida mais sustentável e saudável. Se estima hoje que de 5% a 10% da população mundial é vegetariana e é um estilo de vida que cresce dia após dia. Estamos também em fase de lançamento de um novo app e com outros em fase de planejamento.</p><a href='https://coodesh.com/empresas/similar-souls'>Veja mais no site</a>

 ## Habilidades: 
 - HTML 5 
- CSS 3 
- Angular 2+ 
- Ionic 
- Apache Cordova
## Local: 
 100% Remoto
## Requisitos: 
 - Graduação em Engenharia ou Ciências da Computação ou áreas similares. 
- Sólida experiência no desenvolvimento Frontend 
- Conhecimento em HTML/CSS, Javascript 
- Experiência e conhecimento preferencialmente na stack de Angular, Ionic e Cordova. 
- Espírito empreendedor. Buscamos alguém entusiasmado em nos ajudar a evoluir o app e fazer de nossa visão uma realidade e que tenha interesse em evoluir com a empresa. 
- Inglês intermediário.
## Diferenciais: 
 - Experiência prévia em desenvolvimento híbrido de Apps 
- Conhecimento ou interesse em UX/UI
## Benefícios: 
 - Plano de Saúde Bradesco, sem coparticipação 
- Flexibilidade de horários 
- 100% Remota 
- Oportunidade de atuar em uma empresa com abrangência global
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Mobile Developer na Similar Souls](https://coodesh.com/vagas/frontend-mobile-developer-115628222?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
