### ISSUE TITLE
[Remoto] Front-end Developer na Konfetti GmbH

### ISSUE THREAD

**Issue by renatodompieri** [frontendbr/vagas#6425]
## Nossa empresa

A Konfetti é uma startup alemã que está criando uma plataforma para a venda de eventos de diversas categorias - degustação, pintura, workshops, etc. 

Você pode nos conhecer pelo link do novo website: https://gokonfetti.com

## Descrição da vaga

A vaga é principalmente para funções front-end, trabalhando quase exclusivamente com Vue.js / Nuxt.

Preferencialmente o regime é **FULL-TIME**.

A plataforma é nova e cheia de desafios e features interessantes que devemos implementar num futuro próximo, portanto é interessante que o candidato esteja interessado em não só seguir o que lhe é passado mas também ter interesse pelo sistema e dar suas próprias ideias para nos ajudar a crescer.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência com Nuxt e Vue.js
- Experiência com tecnologias front-end em geral (HTML, CSS, Webpack, etc)
- Inglês avançado (conversação)
 
**Desejáveis:**
- Conceitos básicos de Docker
- Conceitos básicos de Git
- Conhecimento básico de Laravel

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para renato@gokonfetti.com com seu CV anexado - enviar no assunto: Frontend Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até XX dias após cada processo.
E-mail para contato em caso de não haver resposta: feedbacks@empresasuperlegal.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
