### ISSUE TITLE
[Remoto] Senior Outsystems Developer na Pasquali Solution

### ISSUE THREAD

**Issue by Recrutas** [frontendbr/vagas#6426]
**Job Description**

We are looking for people who have extensive experience in Front-End development.

**Place**

Remote

**Mandatory Requirements:**

•     Outsystems (traditional or reactive)
•     API's REST or SOAP
•     HTML 
•     CSS
•     SQL database
•     Fluent English 

**Hiring**

PJ - Value to be agreed.

**How to apply?**

Submit your resume: https://cutt.ly/LRngnV1
Send your resume: janaina.ramos@pasqualisolution.com.br

**Labels**

• Allocated
• PJ
• Senior

**About Pasquali**

Pasquali Solution is a consultancy focused on Allocation of IT professionals recognized for its fast and excellent work.
We have been in the market for over 18 years and are highly specialized in Information Technology.
Benefits
• Partnership with Alura for courses
• Birthday month bonus

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
