### ISSUE TITLE
[REMOTO] Desenvolvedor na Codex Agro

### ISSUE THREAD

**Issue by luanasantosog** [frontendbr/vagas#6428]
## Nossa empresa

A Codex Agro, é especialista em soluções de inteligência em diagnóstico, prognóstico, monitoramento e inteligência comercial, reunindo grande capacidade em geração e gestão de dados estratégicos para o Agronegócio no Brasil.

## Local

Home Office

## Requisitos

**Formação:**
- Ensino Superior Completo na área de TI.

**Experiência em desenvolvimento utilizando:**
- C# .NET Core (ou .NET Framework);
- ORM (preferencialmente Entity Framework);
- Web services (preferencialmente em REST);
- Repositório de arquivos (preferencialmente Git).

**Conhecimentos Desejáveis:**
- Conhecimento em banco de dados (preferencialmente PostgreSQL);
- Conhecimento em metodologias ágeis;
- Diferencial: experiência em framework Javascript (preferencialmente React JS).

##Contratação

A combinar

## Como se candidatar

Inscreva-se em: https://jobs.kenoby.com/codex-agro/job/76-desenvolvedor-back-end/61a516444f82ce51b6d0c595?utm_source=website

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
