### ISSUE TITLE
[Remoto] Senior Java Software Engineer @ AmbizzionIT

### ISSUE THREAD

**Issue by NicolasDurazzo** [frontendbr/vagas#6429]
## Nossa empresa

É uma empresa provedora de serviços e soluções integradas de sistemas, alinhadas com as principais estratégias corporativas através de uma equipe altamente qualificada. Nossa experiência e comprometimento traduzem o alto nível de satisfação e reconhecimento dos nossos clientes.

## Descrição da vaga

✅ 100% Remota;

✅ Necessário proficiência em inglês;

✅ Benefícios de férias e possibilidade de fazer intercâmbio.

## Local

100% remoto

## Requisitos

**Obrigatórios:**

- 7+ years of experience as software engineer;
- 5+ years direct experience with Java, RDBMS (MySQL or similar), Spring / Spring Boot;
- Strong mastery of data structures, algorithms, and with experience troubleshooting issues.
- Excellent understanding of software architecture and OOP concepts;
- Detail-oriented with emphasis on writing clean code and employing test-driven development.
- Expertise in building APIs;
- Unit Testing and Test-Driven Development;
- Solid written and spoken communication skills;
- Detail-oriented with emphasis on writing clean code.
- Exposure to Microservices, continuous integration (CI/CD), Docker, Kubernetes, and AWS is a plus;
- Bachelors / Master’s degree in Computer Science, Computer Engineering or equivalent combination of technical education and experience.

## Contratação

PJ

## Como se candidatar

Por favor envie um email para nicolas.durazzo@ambizzion.com.br com seu CV anexado - enviar no assunto:
- Vaga Senior Java Engineer Github

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 48 horas após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
