### ISSUE TITLE
[São Paulo - SP] Front-End Developer Pleno na UOL

### ISSUE THREAD

**Issue by pablosoares** [frontendbr/vagas#643]
## Descrição da vaga

Construção de páginas web, Desenvolvimento Front-end utilizando HTML, CSS e principalmente Javascript (jquery).

## Local

Alocado na UOL, São Paulo - Faria Lima ou Barão de Limeira.

## Benefícios

 Somente salário.

## Requisitos

Experiência em desenvolvimento de páginas web utilizando Javascript, JQuery, HTML 5, CSS, XHTML, Canvas. 
Experiência Grunt, Git/SVN
Bons conhecimentos em SEO
Inglês técnico

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para debora.lemos@pppro.com.br com seu CV anexado - enviar no assunto: Vaga Front-End PJ - Indicação - Pablo Soares

**Comment by tunnes** [comment]
@pablosoares Qual o valor\hora e qual o produto? Tenho familiaridade com canvas e Js puro:
https://github.com/tunnes/hotline-fatec-bs

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by pablosoares** [comment]
Nope!
