### ISSUE TITLE
[Remoto] Full-Stack PHP/Laravel  Developer (Sênior) na Cargo Sapiens

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6433]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/full-stack-senior-phplaravel-130709967?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>Cargo Sapiens</strong> está buscando <strong><ins>Fullstack PHP/Laravel Developer</ins></strong>!</p>
<p>Somos uma Startup que está revolucionando o mercado de logística internacional.</p>
<p>Estamos entre as TOP 10 Log Techs do Brasil segundo o Ranking da 100 Open Startups, e entre as Top 10 Startups de BH segundo a Câmara de Comércio Americana (AMCHAM), com um portfólio consolidado de grandes empresas, e ainda temos muito o que crescer!</p>
<p>Se você se identifica com uma cultura horizontal, de meritocracia, aonde você pode fazer a diferença, e crescer junto conosco, será um prazer tê-lo(a) abordo!</p>
<p>Estamos buscando um colaborador(a) para apoio ao Time de Tecnologia:</p>
<ul>
<li>Desenvolvimento de novas funcionalidades no Software (SaaS)</li>
<li>Desenvolvimento de aplicações internas e integrações (APIs)</li>
</ul>

## Cargo Sapiens: 
 <p>Cargo Sapiens é uma startup que está revolucionando o mercado de logística internacional, transformando o processo de compra do frete internacional, aéreo, marítimo e multimodal.</p>

<p>Estamos entre as TOP 10 Log Techs do Brasil segundo o Ranking da 100 Open Startups, e entre as Top 10 Startups de BH segundo a banca da Camará de Comércio Americana (AMCHAM), com um portfolio consolidado de grandes empresas, e ainda temos muito o que crescer!</p><a href='https://coodesh.com/empresas/cargo-sapiens'>Veja mais no site</a>

 ## Habilidades: 
 - CSS 
- HTML 5 
- Laravel 
- PHP 
- Bootstrap
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência em desenvolvimento web com PHP e Laravel, HTML5, CSS, Javascript e MYSQL; 
- Experiência em desenvolvimento de APIs. 
- Bootstrap, Git, Nginx 
- Tenham alto nível de comprometimento e engajamento; 
- Tenha uma postura ética e colaborativa; 
- Seja proativo e organizado.
## Diferenciais: 
 - Experiência em Microserviços

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Full-Stack PHP/Laravel  Developer (Sênior) na Cargo Sapiens](https://coodesh.com/vagas/full-stack-senior-phplaravel-130709967?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
