### ISSUE TITLE
[Hibrido / Barueri, São Paulo, Brazil] Frontend React/UI Developer (Sênior) na Yssy Holding 

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6434]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-sr-uireact-124855547?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>Yssy Holding </strong>busca pessoa <strong>Frontend React/UI Developer (Sênior) </strong>para compor seu time!!</p>
<p>Nós transformamos empresas em Empresas Inteligentes e sabemos que, para isso, é preciso sair do lugar comum. Por essa razão, abraçamos os desafios da inovação, deixando de lado o jogo seguro que não alavanca negócios que desejam se diferenciar no mercado.&nbsp;</p>
<p>A pessoa contratada será responsável por nós ajudar na parte de Desenvolvimento de soluções de Frontend para aplicativos web e móveis. Utilizando como base<strong><em> React e JavaScript. </em></strong></p>
<p></p>

## Yssy Holding : 
 <p>Do Tupi, Yssy é trazer ordem e integração para o mundo. É isso que fazemos por mais de 180 clientes de todo o país.</p>
<p>Nós transformamos empresas em Empresas Inteligentes e sabemos que, para isso, é preciso sair do lugar comum. Por essa razão, abraçamos os desafios da inovação, deixando de lado o jogo seguro que não alavanca negócios que desejam se diferenciar no mercado.</p><a href='https://coodesh.com/empresas/yssy-holding'>Veja mais no site</a>

 ## Habilidades: 
 - Code Review 
- Java 
- React.js
## Local: 
 Barueri, São Paulo, Brazil
## Requisitos: 
 - Conhecimento e experiência em react, javascript e visual studio code 
- Conhecimento e experiência em UI/UX e Design System

## Benefícios: 
 - Vale refeição  
- Convênio Saúde 
- Convênio Odontológico  
- Auxilio Creche 
- PLR
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend React/UI Developer (Sênior) na Yssy Holding ](https://coodesh.com/vagas/desenvolvedor-sr-uireact-124855547?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
