### ISSUE TITLE
[Belo Horizonte] Fullstack C# / Angular Developer na BrunSker Tecnologia

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6435]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-frontend-angular-133054740?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>BrunSker</strong> busca pessoa <strong><em>Fullstack C# / Angular Developer</em></strong> para compor seu time!!</p>
<p>A <strong>BrunSker</strong> nasceu do desejo de desenvolver soluções em tecnologia que fossem inteligentes, práticas e inovadoras em um modelo de negócio jovem e dinâmico.</p>
<p>Atuamos nas áreas de gerenciamento, monitoramento e suporte a banco de dados, desenvolvimento de sistemas, consultoria e assessoria em soluções de infraestrutura e projetos de TI.</p>
<p><strong><em>Estamos à procura de pessoas inovadoras, comprometidas e com desejo de crescimento.</em></strong></p>
<p><strong>Suas Atividades:</strong></p>
<ul>
<li>Realizar o desenvolvimento de programas de software a partir da análise de suas especificações, aplicando as melhores práticas de codificação e os padrões estabelecidos, para que o software se torne um produto de fácil manutenção e evolução;</li>
<li>Participar do processo de criação do projeto de software, visando melhorar características como: estrutura escalar, performance, segurança e usabilidade;</li>
<li>Atuar junto aos líderes técnicos e apoiar o time de desenvolvimento na condução das tarefas alocadas por projetos</li>
</ul>

## BrunSker Tecnologia: 
 <p>A BrunSker nasceu do desejo de desenvolver soluções em tecnologia que fossem inteligentes, práticas e inovadoras em um modelo de negócio jovem e dinâmico.</p>
<p>Atuamos nas áreas de gerenciamento, monitoramento e suporte a banco de dados, desenvolvimento de sistemas, consultoria e assessoria em soluções de infraestrutura e projetos de TI.</p><a href='https://coodesh.com/empresas/brunsker-tecnologia-ltda'>Veja mais no site</a>

 ## Habilidades: 
 - Angular 9 
- Rest e Restful APIs 
- .NET Core 
- C# .NET Core
## Local: 
 Belo Horizonte
## Requisitos: 
 - Conhecimento e experiência como back: C#, .NET; 
- Conhecimento e experiência como front: Angular; 
- Conhecimento em SQL (MySQL); 
- Conhecimento e experiência em WebAPis.
## Diferenciais: 
 - Mensageria; 
- Docker; 
- Experiência com ferramentas de controle de versão, como Git;
## Benefícios: 
 - Plano Odontológico 
- Plano de Saúde  
- Vale Transporte ou Auxílio Combustível  
- Vale alimentação (R$ 25,07 por dia) 
- Seguro de Vida
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack C# / Angular Developer na BrunSker Tecnologia](https://coodesh.com/vagas/desenvolvedor-frontend-angular-133054740?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Regime
CLT
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
