### ISSUE TITLE
[Remoto] Full React.JS Developer na Pasquali Solution

### ISSUE THREAD

**Issue by Recrutas** [frontendbr/vagas#6436]
**Descrição da vaga**

Estamos procurando pessoas que tenha uma vasta experiência em desenvolvimento React.JS.

**Local**

Remoto

**Requisitos Obrigatórios:**

•	React.JS
•	Front-end
•	WEB

**Contratação**

PJ - Valor a combinar.

**Como se candidatar?**

Envie seu currículo: https://cutt.ly/bxmAzBE 
Envie seu currículo: carolina.ugolini@pasqualisolution.com.br

**Labels**

•	Alocado
•	PJ
•	Pleno

**Sobre a Pasquali**

A Pasquali Solution é uma consultoria com foco em Alocação de profissionais de TI reconhecida pelo seu trabalho rápido e com excelência.
Estamos há mais de 18 anos no mercado e somos altamente especializada em Tecnologia da Informação.
Vantagens
•	Parceria com a Alura para cursos
•	Gratificação no mês de aniversário

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
