### ISSUE TITLE
[Remoto] Especialista Front-end Developer (React) na @Mutual

### ISSUE THREAD

**Issue by Vinirm1777** [frontendbr/vagas#6437]
Sobre a Mutual
A Mutual é uma Fintech que surgiu para revolucionar a forma de realizar investimentos e empréstimos no Brasil, utilizando tecnologia, simplificando a circulação de dinheiro entre pessoas, com maior rentabilidade ao investidor e juros menores ao tomador. Aqui trabalhamos com tecnologia de vanguarda, em ambiente horizontal e colaborativo, com autonomia e foco nas entregas, sem burocracia e enrolação!

Descrição da vaga
Como Pessoa Especialista Frontend (React) você terá a oportunidade de trabalhar com um frontend moderno usando tecnologias como React, React Native, Next.JS, Redux, Typescript. Inserido em uma equipe ágil, comprometida com qualidade nas entregas, e sempre buscando excelência técnica. Vai ser a referencia técnica do time, coordenando e liderando outros desenvolvedores e pensando as estratégias a longo prazo.

Local
100% Remoto

Requisitos
Pelo menos 5 anos de experiência profissional em React ou React Native 
Experiência com coordenação de pessoas 
HTML / CSS
Experiência profissional em React com Typescript
Conhecimento em técnicas de estruturação de estado. Exemplos: Redux, MobX, XState, Context
Experiência profissional com javascript moderno (ES6+)
React moderno (hooks)

Diferenciais:
 CI/CD (Appcenter, Fastlane, Codepush)
Desenvolvimento backend (Node.JS)
Desenvolvimento nativo (IOS / Android)
SSR (Next.JS)

Benefícios
Trabalho 100% Remoto;
Contratação PJ;
Férias remuneradas;
Plano de saúde e odontológico (cobertura nacional);
Auxílio Home office;
Flexibilidade de horário;
Ambiente informal;
Evolução profissional acelerada.

Contratação PJ

Por favor envie um email para [vinicius.medeiros@mutual.club](mailto:vinicius.medeiros@mutual.club) com seu CV anexado, ou se inscrever diretamente pelo link:
https://vagas.mutual.club/

Tempo médio de feedbacks
Costumamos enviar feedbacks em até 2 dias após cada processo.

Nível
Especialista

![facebook e slack - desenvolvedor](https://user-images.githubusercontent.com/99297663/153301981-af90292a-7b1c-451b-83b3-feb1fc9e6caa.png)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
