### ISSUE TITLE
[Remoto] Pessoa Desenvolvedora Web Sênior (Fullstack com vivência em PHP) @ Feedz

### ISSUE THREAD

**Issue by larissaaguiar** [frontendbr/vagas#6438]
🚀 A FEEDZ:
Nosso propósito é criar ambientes de trabalho mais felizes! Por isso, começar pelo nosso próprio ninho é tão importante! Somos Parrots determinados e que se importam uns com os outros, a sede de resultado é latente e o feedback sincero é rotina.

Aqui temos um ambiente de trabalho focado na cooperação entre Devs, confiamos no trabalho de nossos colaboradores e por isso acreditamos que nossos desenvolvedores devem ter autonomia!

Prezamos pela liberdade de falar o que se pensa e pelos feedbacks constantes, além de ter um time realmente diverso 💙 Temos também flexibilidade de horários. Tem que ir ao banco? Precisa sair mais cedo para pegar os filhos na escola? Sem problema.

Estamos buscando uma pessoa para o cargo de Pessoa Desenvolvedora Fullstack Sênior(vivência com PHP) que irá atuar no nosso time de Produto, trabalhando diretamente com nossos tech leads e CTO, resolvendo desafios que impactam mais de 100 mil usuários diretamente e nos ajudando a evoluir a senioridade do time.

📚 RESPONSABILIDADES E ATIVIDADES:
Aplicar boas práticas alinhadas com o time no desenvolvimento (criando códigos coerentes e alinhados ao Clean Code; desenvolvendo com foco em segurança, patterns, CI/CD, automação, etc);
Desenvolver novos módulos na plataforma e auxiliar nas definições de arquitetura;
Identificar pontos de melhoria na performance da base instalada;
Desenvolvimento e aplicação de testes automatizados;
Mentorear o time de desenvolvimento em parceria com tech leads;
Fazer a gestão da informação das demandas atualizando o status dos projetos.

🥇 PRÉ-REQUISITOS:
10 anos de experiência com desenvolvimento web (Fullstack com vivência em PHP);
Experiência com sistemas de alto volume de dados;
Vivência com implantação de testes automatizados(unitários, integração e/ou aceitação);
Gostar de trabalhar em time. Pessoa Desenvolvedora sozinha não faz verão!

🎯DIFERENCIAIS:
Experiência com e-commerce ou SaaS;
Vivência em processos de DevOps(Bitbucket, Gitlab, CI/CD ou relacionados;).

✨ BENEFÍCIOS:
Auxílio Parrot Feliz (R$100/mês de investimento no desenvolvimento pessoal, saúde física ou mental do Parrot)
Auxílio Contas (R$160/mês)
Auxílio Parrot Casamenteiro(R$250 quando Parrots casam)
Auxílio Ninhada(R$250 no nascimento ou adoção de pequenos Parrots)
Happy Bird(day) (um dia de folga no mês de aniversário)
Descontos nas empresas conveniadas com a ACATE
Ifood Office

💰 SALÁRIO A COMBINAR (PJ)
Candidate-se em: https://enliztjob.app.link/qhbLXN0Csnb

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
