### ISSUE TITLE
[São Paulo] Front-end Developer na F1Sales :purple_heart: 

### ISSUE THREAD

**Issue by marciok** [frontendbr/vagas#6439]
## Descrição da vaga

A F1Sales esta em busca de uma pessoa desenvolvedora (pleno ou senior) para dar o kick start em um novo projeto, utilizando tecnologias de chat e real-time.

## Local

Escritório, [SP], [São Paulo], [WeWork Jardim das Perdizes]

## Requisitos

**Obrigatórios:**
- Experiência profissional em: React, GraphQL e Jest
- TDD

**Desejáveis:**
- Typescript
- Rails

**Diferenciais:**
- projetos opensource :+1: 

## Benefícios

- Verba para desenvolvimento profissional 

**Diferenciais:**
- Kicks-start um projeto do zero.
- Empresa com technical founder. 
- Oportunidade de montar uma equipe

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para contato@f1sales.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: contato@f1sales.com.br

## Labels
- Sênior
- PJ

#### Alocação
- Hibrido 

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

[Desenvolvedor Front-end _2.pdf](https://github.com/frontendbr/vagas/files/8042216/Desenvolvedor.Front-end._2.pdf)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
