### ISSUE TITLE
[Remoto]  BI Full Analyst na Pasquali Solution

### ISSUE THREAD

**Issue by Recrutas** [frontendbr/vagas#6447]
**Descrição da vaga**

Estamos procurando pessoas que tenha uma vasta experiência em Analista de BI.

**Local**

Remoto

**Requisitos Obrigatórios:**

•	Arquitetura de soluções analíticas e de dados, incluindo experiência com Grandes Dados, Bancos de Dados Relacionais, NoSQL, OLAP, streaming e processamento de dados em lote;
•	Ajuste e desenvolvimento de SQL incluindo instruções SQL, Stored Procedures, Views, pacotes ETL e pipelines;
•	Cloud em atividades de movimentação, transformação e recuperação de dados;
•	Coleta de requisitos comerciais e complexos e na identificação de necessidades de dados;
•	DBS de grande escala ou grandes sistemas de dados como Snowflake, Redshift, etc.
•	Análise de dados para identificar resultados, lacunas e inconsistências;
•	Linguagens de programação de análise de dados (R, Python e SQL);
•	Fórmulas DAX;
•	Data Mining 

**Diferencial:**

•	Data lake;
•	Scala e spark;
•	SAS e/ou SPSS;
•	Infraestrutura de Big Data (Hadoop, MapReduce e Spark);
•	Conhecimento em Estatística;
•	Machine Learnign; 
•	Álgebra Linear.

**Contratação**

PJ - Valor a combinar.

**Como se candidatar?**

Envie seu currículo: https://cutt.ly/bxmAzBE 
Envie seu currículo: carolina.ugolini@pasqualisolution.com.br

**Labels**

•	Alocado
•	PJ
•	Pleno

**Sobre a Pasquali**

A Pasquali Solution é uma consultoria com foco em Alocação de profissionais de TI reconhecida pelo seu trabalho rápido e com excelência.
Estamos há mais de 18 anos no mercado e somos altamente especializada em Tecnologia da Informação.
Vantagens
•	Parceria com a Alura para cursos
•	Gratificação no mês de aniversário

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
