### ISSUE TITLE
[Remoto] Frontend Engineer Developer (Sênior) na Croct

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6449]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/backend-engineer-developer-senior-135008452?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>Croct</strong> está buscando <strong><ins>Frontend Engineer Developer </ins></strong>para compor sua equipe!</p>
<p>Se você é um programador, trabalha com a React, e procura uma startup com potencial global, gostará do que lhe estamos a oferecer.</p>
<p>Como Engenheiro de Frontend, irá lidar com desafios como implementar um bom design e aprender novas tecnologias para garantir a melhor experiência do utilizador. Trabalhará diretamente com os fundadores da Croct e abordará questões relacionadas com o desempenho, optimização, e escalabilidade das soluções</p>
<p><strong>Responsabilidades:</strong></p>
<ul>
<li>Assegurar a entrega de projetos ambiciosos com um impacto significativo no negócio enquanto trabalha lado a lado com os fundadores da Croct</li>
<li>Participar no planeamento do projeto para responder às necessidades atuais e futuras das empresas, antecipando e removendo barreiras</li>
<li>Colaborar com outras equipas para compreender os problemas, analisar oportunidades e explorar as melhores soluções</li>
<li>Desenvolver e implementar a plataforma Croct, onde os clientes gerem as suas experiências personalizadas</li>
<li>Documentar e mapear os processos relacionados com a área</li>
</ul>

## Croct: 
 <p>Croct is a SaaS for the customization of web applications in real-time. Through a JS SDK, we provide a solution for developers to create natively personalized applications, as well as for marketing and product professionals to offer unique experiences to users according to their behavioral profile, interests, and browsing history. Briefly, we provide a way to turn data into actions in real-time.</p>
</p>

 ## Habilidades: 
 - React 
- GraphQL 
- Javascript 
- Typescript 
- HTML 5 
- CSS 3 
- Sass/Less 
- Jest 
- Cypress
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência em React, GraphQL, Javascript, Typescript, HTML5, CSS3, e LESS / SASS 
- Conhecimento sobre bibliotecas/framework/ferramentas para frontend: Relay, Storybook, Jest, Cypress, e Emotion 
- Capacidade com unidade, integração e testes de ponta a ponta quando aplicável ao processo de desenvolvimento 
- Base teórica, habilidade e concentração na excelência técnica e nas melhores práticas de desenvolvimento (TDD, BDD, design de código, arquitetura, etc.) 
- Experiência com ferramentas de versioning (GitHub) e linting (ESLint) 
- Capacidade com gestores de pacotes como o NPM 
- Experiência em Integração Contínua e Entrega Contínua
## Diferenciais: 
 - Experiência em alguma da linguagens de backend (PHP, Node, Java, Python, Golang)
## Benefícios: 
 - Liberdade para trabalhar em qualquer lugar 
- Horário de trabalho flexível 
- Oportunidade de crescimento numa start-up com potencial escala global 
- Flexibilidade para trabalhar com a stack da sua escolha 
- Trabalhar lado a lado com os fundadores e uma equipe incrível 
- Liberdade para trabalhar e contribuir para projetos de código aberto 
- R$ 1.000,00 de ajuda de custo 
- Salário competitivo com o mercado
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Engineer Developer (Sênior) na Croct](https://coodesh.com/vagas/backend-engineer-developer-senior-135008452?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
