### ISSUE TITLE
[Brasília] Front-End Developer na [EFOR]

### ISSUE THREAD

**Issue by marciomgomes** [frontendbr/vagas#645]
## Descrição da vaga

Estamos recrutando 1 (um) desenvolvedor para compor a equipe atual, com sólidos conhecimentos em front-end, a fim de participar de um projeto de médio e longo prazo.

O projeto já existe e está em fase de construção.

## Local
O trabalho poderá ser Remoto ou em nosso Escritório de Brasília.

## Benefícios
Contratação CLT ou PJ
Valor de contratação R$ 40,00 / hora (*)

<b>(*) Analisaremos valores de hora maiores que o ofertado, porém a experiência deverá ser condizente e coerente.</b>

## Requisitos Obrigatórios

* Ter tido experiência com linguagens de marcação HTML5, CSS3 e SASS. 
* Um bom nível de conhecimento em JavaScript. 
* Experiência com Angular 2 e posterior. 
* Entender de chamadas assíncronas utilizando JSON como formato de transporte e REST. 
* Versionamento de código GIT. 
* Experiência com frameworks de teste unitário. 
* Conceitos básicos de UX. 
* Entender pelo menos o básico de segurança web. 
* Já ter tido contato ou trabalhado com times e gestão ágil. 
* Saber que trabalho REMOTO exige igual ou mais comprometimento que presencial.

## Requisitos Desejáveis
- conhecimentos em ruby on rails
-conhecimento em Postgree

## Como se candidatar

Por favor envie um email para marcio@efor.com.br com seu CV anexado - enviar no assunto: Vaga AngularJS 2 / GITHUB

**Comment by ygorlazaro** [comment]
Boa tarde, essa vaga é para full-time ou part-time?

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
