### ISSUE TITLE
[São José dos Campos] Developer Jr na Oncar

### ISSUE THREAD

**Issue by amandaalmeida08** [frontendbr/vagas#6451]
## Nossa empresa

A OnCar surgiu dentro de uma das lojas de seminovos do Brasil e lidera um laboratório de inovação em gestão que tem como objetivo maior eficiência para as lojas de carro de todo o país por meio de tecnologia, dados e excelência de operação.

Para o lojista?
Imagine uma base que pode oferecer todo tipo de informação sobre um cliente potencial e um relacionamento direto e constante com seus clientes atuais.
Aliada a captação para vendas, imagine que essa mesma tecnologia te capacite a aumentar o repor seu estoque, a ter uma gestão eficiente também para assuntos financeiros, soluções administrativas para seu negócio e ainda crédito facilitado para garantir a reposição do estoque.

Para o cliente?
Asseguramos variedade de veículos, preço rápido na compra e troca de veículos, velocidade de venda e acesso ao crédito rápido, fácil e sem burocracias também para negativado.

## Descrição da vaga

Uma pessoa Desenvolvedora FullStack está em uma transformação tecnológica e está disposta a aprender diariamente.
Está? Fique tranquilo temos um tempo incrível para te ajudar a aprender!

Sobre o desafio:

Participar de discussões técnicas para oferecer soluções rápidas e criativas tais como visualização de dados, implementação e implementação e integrações de ferramentas externas.
Desenvolvimento de micro serviços;
Análise e benchmarks de tecnologias e ferramentas;
Refatoração de serviços legados.

## Local

Presencial em São José dos Campos.

## Requisitos

Antes de tudo, você precisa identificar com nossos propósitos depois ter conhecimento ou interesse com:

Linguagem de programação (Python, Node.JS ou Similares.)
Framework de Front-End (React, Angular ou Similares)
Banco de dados relacionais

## Benefícios

- Plano de saúde
- Cartão Flash (Benefícios Flexíveis)
- Oportunidade de construção de uma empresa;
- Flexibilidade de horário

**Diferenciais:**

- Frigobar sempre cheio :P
- Sala de jogos

## Contratação

PJ a combinar

## Como se candidatar

Por favor se candidate na nossa plataforma: https://people.talentbrand.com.br/jobs/tony-veiculos-desenvolvedor-junior-d157

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@oncar.com.br

#### Alocação
- Alocado

#### Regime

- PJ

#### Nível
- Júnior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
