### ISSUE TITLE
[Florianópolis - SC] Front-end Developer (REACT) na Alibin

### ISSUE THREAD

**Issue by giufiorenzano** [frontendbr/vagas#6453]
## Nossa empresa

Somos uma empresa especializada em soluções de arrecadação e pagamentos. Nós estamos entre as empresas adquirentes e o cliente final, a ideia é facilitar para os estabelecimentos comerciais a cobrança de seus clientes, independente do meio de pagamento escolhido, seja ele crédito, débito, boleto.

## Descrição da vaga

Estamos a procura de um Dev. Front End - React para nos ajudar a enfrentar os enormes desafios em desenvolver projetos. :) 
Procuramos alguém com perfil Pleno (ou Junior que já tenha feito projetos e consiga se virar bem sozinho!)

Nesta função você irá:

- Desenvolver interfaces para aplicações web (seguindo os layouts que já vêm definidos - mas sugestões de UI/UX são bem vindas);
- Implementar as lógicas necessárias para deixar o front das aplicações web funcionais;
- Consumo de API;
- Manutenção do nosso pacote de componentes;
- Utilizar sempre as melhores práticas e entregar um código limpo e funcional.

## Local

Presencial em Floripa (bairro Estreito)

Jornada:
De segunda a sexta, das 8:00 às 17:00 com intervalo de 1 hora para almoço.

## Requisitos

**Obrigatórios:**
- Vivência com HTML5; 
- Experiência com CSS3; 
- Conhecimento de JavaScript;
- Prática com ReactJS (preferencialmente já tendo desenvolvido alguma aplicação web);
- Conhecimento em Typescript;
- Testes Automatizados (preferencialmente Jest e Cypress);

**Desejáveis:**
 - Conhecimento de Git;
- Testes: Jest, React Testing Library, Cypress (ou alguma outra ferramenta de testes como Enzyme, Mocha);
- Pré-processador de CSS: SASS;
- Conhecimento em Angular;
- React Native (ou alguma outra tecnologia mobile);
- Metodologias ágeis (aqui utilizamos Scrum);

## Contratação

PJ a combinar

## Como se candidatar

Por favor se candidate neste link https://jobs.recrutei.com.br/PeoplePlan/vacancy/20646-desenvolvedor-front-end-react

#### Alocação
- Alocado

#### Regime
- PJ (cooperativa)

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
