### ISSUE TITLE
[Florianópolis] Python Developer na ESSS

### ISSUE THREAD

**Issue by Esss0102** [frontendbr/vagas#6454]
> Vaga Remota durante a pandemia

## Nossa empresa

A ESSS é uma multinacional brasileira sediada na cidade de Florianópolis/SC. Disponibilizamos ao mercado as mais avançadas ferramentas de CAE na área de fluidodinâmica, análise estrutural, eletromagnetismo e multifísica, além de customização e desenvolvimento de softwares sob medida de acordo com a necessidade de cada cliente. Estamos presentes no Brasil e no exterior, incluindo Argentina, Chile, Colômbia, França, Espanha, Estados Unidos, México, Peru e Portugal.
Se você acredita que suas habilidades, talentos e experiências são diferenciados para trabalhar em um time de alta performance, responsável pela resolução de problemas por meio da tecnologia e desenvolvimento de softwares, faça sua inscrição no link https://esss.gupy.io/jobs/1525628

## Descrição da vaga

Se você é um entusiasta por inovação e tecnologia e busca uma empresa onde possa compartilhar ideias, conquistas e trabalhar em um ambiente saudável, onde possa se desenvolver pessoal e profissionalmente, estamos com oportunidades em aberto para Desenvolvedor Python. 

**Para essa posição seus principais desafios serão:** 

- Desenvolver softwares de simulação computacional para engenharia.
- Desenvolver GUIs multi-plataforma com testes automatizados (testes unitários e de aceitação).
- Desenvolver algoritmos e estruturas de dados para visualização 2D e 3D.

**Tecnologias que Utilizamos:**

- Python 3.
- C++ (Opcional) usado pontualmente para performance.
- Aplicações desktop Linux e Windows.
- GUI em Python com Qt e VTK.
- Forte foco em testes automatizados (unitários, integração e end-to-end).
- Integração Contínua.
- Revisão de Código.
- Buscamos sempre criar e contribuir com projetos open source (acesse https://github.com/ESSS).

## Local

Florianópolis/SC ou Remoto

## Benefícios

**Disponibilizamos:**

- Plano de saúde nacional com subsídio integral sem coparticipação (melhor operadora da região).
- Cartão de benefícios flexíveis.
- Licença maternidade e paternidade estendidas.
- Oportunidade para contribuição em projetos open source.
- Incentivo a educação continuada através de cursos, treinamentos e especializações e auxílio idiomas.
- Incentivo a publicações, participações em eventos de tecnologia relevantes para seu trabalho.
- Mais de 20 outros benefícios.

## Contratação

CLT

## Como se candidatar

Se cadastre no link: [](https://esss.gupy.io/jobs/1525628)

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
