### ISSUE TITLE
[REMOTO] Software Architect Front-end na Datum✨| VEM FAZER PARTE DO PLANETA ROXO

### ISSUE THREAD

**Issue by julianakraemer** [frontendbr/vagas#6455]
## Nossa empresa

A Datum é uma empresa GPTW (Great Place to Work) pelo segundo ano seguido e nossa principal proposta é ativar o protagonismo, por isso investimos pesado no desenvolvimento de nossos colaboradores.

## Descrição da vaga

oportunidade para atuar como Arquiteto Front-end React 

## Local

Remoto

## Requisitos

Você pode se conectar com a oportunidade se possuir experiência em:

Sólida experiência em arquitetura de software;
Sólida experiência com React;
Sólida experiência com JavaScript;
BFF
Microserviços;
Git;
Testes unitários.

Diferenciais:

Padrões de desenvolvimento, Spring Batch e Open Shift.
## Benefícios

Vale transporte
Vale refeição/alimentação
Auxílio Home Office
Gympass
Plano de saúde
Plano odontológico
Seguro de vida
Cíngulo (saúde mental)
Assessoria financeira, jurídica e psicológica para funcionários

Aqui na Datum, você também vai ter:

Proagonistas (game de incentivo à carreira do colaborador)
Datum Academy (programa de formação e treinamentos)
English Class
Ginástica Laboral
Leader Leader (programa de liderança de
iniciativa) +Felicidade que visa a felicidade do colaborador

## Como se candidatar

Por favor envie um email para juliana.kraemer@datum.inf.br com seu CV anexado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
