### ISSUE TITLE
[REMOTO] Front-end Developer na Nave.rs

### ISSUE THREAD

**Issue by BrunaSouzaPaes** [frontendbr/vagas#6456]
> Vaga Remota durante a pandemia

## O que fazemos?

Trabalhar com a [nave.rs](http://nave.rs/) significa que você conhece e colabora com as pessoas que realmente fazem o trabalho. Unimos tecnologia e criatividade para criar soluções digitais efetivas que se tornam memoráveis e impactam positivamente a vida das pessoas.

Nossa missão é ajudar empresas a entender antes de agir, a agir com precisão e a lucrar a partir de mudanças.

Não é somente sobre produtos digitais, é sobre marcar positivamente a vida das pessoas

## Descrição da vaga

A [Nave.rs](http://nave.rs/) está procurando uma pessoa com perfil de nível pleno, que tenha experiência na área de desenvolvimento Front-end, domínio da linguagem React, experiência com clientes e projetos.

Como pessoa desenvolvedora para a área de Front-end, você irá utilizar linguagem React. Na empresa trabalhamos com a metodologia ágil Scrum, sendo assim, temos cerimônias como planning, weekly e retro. O seu dia a dia de trabalho irá basear-se nas cerimônias e no projeto que você irá entrar.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- HTML
- CSS
- JavaScript
- No mínimo 2 anos de experiência na área de front-end 
- Experiência no desenvolvimento de aplicações web utilizando React;
- Experiência com projetos/clientes
- Conhecimento básico de ferramentas de gestão de tarefas
- Conhecimento básico-intermediário de editores de texto, necessário para escrever código
- Conhecimento básico de Git
-Conhecimento intermediário em lógica de programação

**Diferenciais:**
- Boa Comunicação
- Senso de gerenciamento de tempo
- Conhecimento básico de pair programming

## Benefícios

- Assistências médica e odontológica;
- Auxilio psicológico;
- VR / VA de R$ 24,10/dia
- Aulas de inglês;
- Auxilio Educação (acesso a plataformas de cursos)
- Horário flexível e possibilidade de home office.

**Diferenciais:**
- Horário Flexível
- Plano de carreira

## Contratação

CLT + beneficios

## Como se candidatar

Inscreva-se atraves do link: https://nave-team.gupy.io/jobs/1505106

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: bruna.paes@nave.rs

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
