### ISSUE TITLE
[Remoto] Front-end Developer na Ei, Beleza?

### ISSUE THREAD

**Issue by hmaesta** [frontendbr/vagas#6458]
Ei, Beleza? 👋

### Buscamos uma pessoa para codar páginas de vendas para e-commerce.

Como **Front-end Developer** você será responsável por transformar os protótipos de alta fidelidade feitos por um UI/UX Designer, além de prestar manutenção para páginas já existentes.

## ✨ Sobre a Ei Beleza

Somos um grupo engajado em mudar a vida das pessoas elevando sua autoestima. Hoje temos diversas marcas de cosméticos e cursos profissionalizantes na área de beleza.

Criamos soluções para dores reais, de gente como eu e você. Tudo isso com muita tecnologia, carinho e foco no cliente. Cosméticos são ótimos, mas melhor ainda é fazer o bem e se sentir linda/o!

Alguns de nossos produtos:

- [Hidratei](https://hidratei.com.br/)
- [Óleo de Yasmin](https://yasminbeauty.com.br/)
- [Bumbum Cream](https://bumbumcream.com.br/)
- [BeautyClass PRO](https://www.beautyclasspro.com.br/p/reconstrutor-capilar/)

*(Seu principal trabalho será codar páginas como essas acima!)*

# 📚 Responsabilidades

- Codificar páginas de vendas e prestar manutenção para outras páginas da empresa
- Contato direto com o/a Designer/a que irá criar os projetos
- Identificar oportunidades de melhoria através de análises de dados (Google Analytics, Hotjar, etc)
- Interagir com diferentes áreas da empresa para apresentar e discutir propostas com diferentes pontos de vista

# 🥇 Requisitos

- 2 anos de experiência como Front-end Develiper
- HTML, CSS e Javascript (Vue, React ou Svelte)
- Extrema atenção aos detalhes
- Boa comunicação verbal e escrita
- Portfólio

# 🎯 Diferenciais

- Experiência com Figma (se já usou XD, Sketch, Framer ou InVision também vale)
- Experiência com e-commerce e marketing digital
- Experiência na área de cosméticos
- Experiência com Design Systems
- Inglês
- Tailwind CSS

# 🧑‍💻 Trabalho remoto

Como não trabalharemos juntos fisicamente, é importante ter uma boa comunicação (verbal e escrita). Apesar de não fazermos reuniões todos os dias, é importante que você possa participar de videoconferências.

Oferecemos horários flexíveis, mas, assim como em um escritório, trocamos informações durante todo o dia e você precisa estar disponível em horário comercial.

---

# 📃 Quero me candidatar!

- Faixa de remuneração: entre **R$ 4.000 e R$ 5.100 💰**
- Dedicação full-time 🕑
- Contrato PJ 💼
- Férias remuneradas 💆🏻‍♂️
- Acesso ilimitado a cursos na [Alura](https://www.alura.com.br/) 🧠

### **Para se candidatar, preencha o formulário:**

| → | [Ei Beleza - Vaga Time Tech](https://forms.gle/vfj3YZcD2ARJhnJHA?1) |
|---|-----|

**Dúvidas?** Envie um e-mail para `tech.vagas@eibeleza.com.br`

---

### Outras vagas

Temos outras vagas abertas, veja também:

- [Vaga: UI/UX Designer na Ei Beleza](https://www.notion.so/Vaga-UI-UX-Designer-na-Ei-Beleza-61bf01f1c4e9442ab8a0c0b437241424)
- [Vaga: Designer Who Codes na Ei Beleza](https://www.notion.so/Vaga-Designer-Who-Codes-na-Ei-Beleza-e3cd41d614454f4a91e5ad860e6f6cd8)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
