### ISSUE TITLE
[Remoto] BPMN Specialist Camunda na Pasquali Solution

### ISSUE THREAD

**Issue by Recrutas** [frontendbr/vagas#6459]
**Descrição da vaga**

Estamos procurando pessoas que tenha uma vasta experiência em BPMN Camunda.

**Local**

Remoto

**Requisitos Obrigatórios:**

•	Desenvolver projeto de compra e venda de veículos através da automação de processos utilizando a ferramenta de BPMN Camunda.
•	Dominar a ferramenta em todos os recursos BPMN, DMN, BPMS.

**Contratação**

PJ - Valor a combinar.

**Como se candidatar?**

Envie seu currículo: https://cutt.ly/YQD04zv
Envie seu currículo: eliene.martins@pasqualisolution.com.br

**Labels**

•	Alocado
•	PJ

**Sobre a Pasquali**

A Pasquali Solution é uma consultoria com foco em Alocação de profissionais de TI reconhecida pelo seu trabalho rápido e com excelência.
Estamos há mais de 18 anos no mercado e somos altamente especializada em Tecnologia da Informação.
Vantagens
•	Parceria com a Alura para cursos
•	Gratificação no mês de aniversário

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
