### ISSUE TITLE
[São Paulo - SP] Front-End Developer Sênior na MedPass 

### ISSUE THREAD

**Issue by jnevesmedpass** [frontendbr/vagas#646]
Descrição da MedPass
A MedPass é uma empresa de tecnologia que desenvolve diferentes tipos de projetos web, rotina não está no nosso portfólio. 
Buscamos você, "FERA" no desenvolvimento para início imediato! Se você não pode iniciar imediatamente, por favor não se candidate.

Local de trabalho:
Rua Gomes de Carvalho, número 1069 - Vila Olímpia

#### Diferenciais
- participação em projetos de aplicações web desenvolvidas em angularJS

## Requisitos

**Obrigatórios:**
- no mínimo, 2 anos de experiência com AngularJS
- Proatividade
- Javascript (jquery e **angularjs**)**
- Adobe photoshop e adobe illustrator
- Html, css
- Desenvolvimento responsivo
- Sistemas de controle de versão git
- Cross platform/browser (ie, firefox, safari, opera, chrome)

**Desejáveis:**
- Inglês avançado
- Ionic e cordova
- Pré-processadores css: sass, less, stylus
- Task runners: gulp, grunt, make, npm scripts
- Css frameworks/libraries: bootstrap, semanticui, foundation, uikit, yui, susy

## Contratação
PJ - R$ 6.000 a R$ 9.000,00

## Como se candidatar

Por favor envie um email para jneves@medpass.com.br com seu CV anexado - enviar no assunto: Vaga AngularJS

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
