### ISSUE TITLE
[REMOTO] Front-end Developer na Superare

### ISSUE THREAD

**Issue by lucas-superare** [frontendbr/vagas#6466]
## Nossa empresa

A Superare hoje é a startup de tecnologia do Grupo WE, uma das maiores agências full-service totalmente nacional e, mesmo no período de pandemia, estamos em expansão e precisamos de novos integrantes.

## Descrição da vaga

Atuar juntamente ao time de design e back-end, para desenvolver aplicações do zero e dar suporte aos desenvolvedores juniores.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Mínimo de 3 anos de experiência atuando como Front-End
- Conhecimento sólido em JavaScript
- Conhecimento sólido em performance web
- Ter vasta experiência utilizando React ou outro framework similar de mercado (Ex.: Angular, Vue)

**Desejáveis:**
- Conhecimento em PHP
- Conhecimento em Node.js

## Benefícios

- Horário flexível e home-office
- Ajuda de Custo

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para **lucas@superare.co** com seu Linkedin ou CV anexado - enviar no assunto: Vaga Front-end Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias úteis após cada processo.
E-mail para contato em caso de não haver resposta: weare@superare.co

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
