### ISSUE TITLE
[Remoto] Frontend React & React Native Developer na TeamHub

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6467]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-react-and-react-native-developer-134927333?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Somos um Hub de tecnologia que DESCOMPLICA a gestão de cultura para CONECTAR pessoas e MULTIPLICAR resultados.</p>
<p>O nosso foco é criar um ambiente onde a gestão da cultura seja fácil, acessível, dinâmica e de todos.</p>

## TeamHub: 
 <p>Somos um Hub de tecnologia que <strong>DESCOMPLICA </strong>a gestão de cultura para <strong>CONECTAR </strong>pessoas e <strong>MULTIPLICAR </strong>resultados.</p>
<p>O nosso foco é criar um ambiente onde a gestão da cultura seja fácil, acessível, dinâmica e de todos.</p><a href='https://coodesh.com/empresas/teamhub'>Veja mais no site</a>

 ## Habilidades: 
 - React.js 
- React Native 
- Rest e Restful APIs 
- HTML 5
## Local: 
 100% Remoto
## Requisitos: 
 - Sólida experiência em React Native e Typescript 
- conhecimento em Expo 
- Conhecimento em publicação de apps na Play Store e Apple Store 
- Consumir APIs RESTful 
- Conhecimento em controle de versões (Git, Bitbucket)
## Diferenciais: 
 - Conhecimento em Animações 
- Conhecimento em Figma 
- Conhecimento em Jira 
- NodeJs 
- MongoDB 
- Conhecimento em IaaS Cloud (AWS) 
- Git Flow
## Benefícios: 
 - Horário Flexível 
- Vale Alimentação ou Vale Refeição 
- Auxílio Home Office mensal 
- Plano de Saúde 
- Seguro de Vida 
- Equipamento ou auxílio equipamento mensal
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend React & React Native Developer na TeamHub](https://coodesh.com/vagas/frontend-react-and-react-native-developer-134927333?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
