### ISSUE TITLE
[REMOTO] Front-end Developer na ClearSale

### ISSUE THREAD

**Issue by recrutamentoclearsale** [frontendbr/vagas#6469]
## Descrição da vaga

- Desenvolvimento do frontend, participando de todo o ciclo de desenvolvimento;
- Desenvolvimento em JavaScript e TypeScript utilizando React;
- Monitoração e análise de incidentes em ambiente produtivo;
- Atuação em projetos que envolvem grande escalabilidade.

## Local

**REMOTO**

## Requisitos

**Conhecimentos necessários:**

-  HTML5 e CSS3;
-  JavaScript e Typescript;
-  Git e GitHub;
-  React (Principais conceitos e Top-Level API);
-  Node.js
-  Leitura e persistência de dados em banco NoSQL;
-  React (Principais conceitos e Top-Level API);
-  Desenvolvimento utilizando arquitetura monorepo;
-  Desenvolvimento de testes unitários e de integrações utilizando Jest e React Testing Library;
-  Metodologias ágeis.

**Diferencial:**

- Node.js;
- React;
- Storybook;
- TailwindCSS;
- Nx Workspaces;
- ESLint & Prettier;
- Git;
- Jest;
- Mongoose;
- AWS (Secrets Manager, SQS, SNS, S3 e Lambda);
- Koa;
- Serverless Framework;
- Terraform;
- Jira;
- Electron;

## Benefícios

- PLR (Participação nos Lucros e Resultados);
- Vale-Refeição ou Vale Alimentação;
- Auxílio creche para crianças até 4 anos e 11 meses;
- Seguro de Vida;
- GymPass;
- Aulas de teatro;
- Sesc;
- Cartão Multibenefícios – (com desconto na compra de diversos itens na rede credenciada, incluindo medicamentos em diversas redes de farmácias);
- Assistência Médica – Amil;
- Convênio Odontológico (Amil)*.
* custo integral do colaborador

**Diferenciais:**
- Flexibilidade de horário;
- Política educacional para graduação e pós-graduação;
- Programa Eu Saudável (Acompanhamento de Saúde e Bem-Estar);
- Programa Primeiros Laços (Acompanhamento Gestacional);
- Consultas médicas remotas;
- Palestras de desenvolvimento pessoal e profissional.

## Contratação

CLT

## Como se candidatar

Por favor envie um email para thais.brandi@clear.sale com seu CV anexado - enviar no assunto: Vaga FrontEnd

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
