### ISSUE TITLE
[Niterói] Front-End Júnior na [WPENSAR]

### ISSUE THREAD

**Issue by mathvaleriano** [frontendbr/vagas#647]
## Local

Presencial, Capitão Zeferino, nº 13, Niterói - RJ

## Benefícios

- Seguro de vida
- VR de R$ 24,30/dia
- Vale Transporte

#### Diferenciais

- sala de jogos
- horário flexível
- ambiente descontraído

## Requisitos

**Obrigatórios:**
- HTML
- CSS
- JS

**Diferenciais:**
- Typescript
- AngularJS
- Ionic

## Contratação

CLT full
Não é necessário ter graduação concluída

## Sobre a Empresa

Fundada em 2011 a WPensar tem como objetivo mudar a educação do país. O grupo conta com soluções tecnológicas de ponta com o objetivo de auxiliar gestores escolares na otimização de tempo e recursos focando no que é mais importante, a educação.

## Como se candidatar

Por favor envie um email para rh@wpensar.com.br com seu CV anexado - enviar no assunto: Quero mudar a educação no DEV

**Comment by mathvaleriano** [comment]
Pode mudar a label só pra junior por favor? Pq a vaga e so pra junior

**Comment by filippobarcellos** [comment]
Olá. A vaga já foi preenchida?

**Comment by mathvaleriano** [comment]
essa sim... mas já abrimos **[outra](https://github.com/frontendbr/vagas/issues/708)** ;)

**Comment by HaluDeCassia** [comment]
Cara, não há nenhuma possibilidade de remoto? Ajudaria muito rs

**Comment by mathvaleriano** [comment]
oi @HaluDeCassia manda no email que vc tem pretensão pra remoto... estamos aceitando currículo pra remoto nessa vaga  -> https://github.com/frontendbr/vagas/issues/708

**Comment by HaluDeCassia** [comment]
@mathvaleriano muito obrigada. Já havia mandado para a vaga que você me indicou :smile:
