### ISSUE TITLE
[Curitiba] Front-end Developer Angular na Gestran

### ISSUE THREAD

**Issue by DannyGestran** [frontendbr/vagas#6475]
[Curitiba] Front-End Developer Angular na Gestran Software

> Vaga Hibrida

## Nossa empresa

A mais de 20 anos a Gestran desenvolve ferramentas e soluções que fortalecem as estruturas e aprimoram os processos auxiliando no crescimento das empresas.

## Descrição da vaga

•	Atuar no desenvolvimento e correções de soluções de software Front-End em plataforma Web;
•	Desenvolver código limpo, testável e de fácil manutenção;
•	Aplicar as melhores práticas de documentação de código desenvolvido;
•	Conhecimento em Angular 6 ou superior.
•	Desenvolvimento e correções em plataforma Web;
•	Experiência comprovada em projetos no mínimo em 3 anos como angular;

## Local

Exemplo: Escritório, [Paraná], [Curitiba], [Água Verde]

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Angular

## Benefícios

- Plano de saúde após 90 dias (CLT)
- Plano odontológico após 90 dias (CLT)
- VR de R$ 25,00/dia
- ...

**Diferenciais:**
- Horário Flexível;
- Espaço descolado com puffs;
- Clube da Fruta;
- Sala de jogos;
- Aniversariantes do mês.

## Contratação

PJ a combinar
CLT

## Como se candidatar

Por favor envie um e-mail para recrutamento@gestran.com.br com seu CV anexado - enviar no assunto: Vaga Front-End Angular

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: recrutamento@gestran.com.br

#### Alocação
- Alocado
- Hibrido

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by DannyGestran** [comment]
Bom dia!

Ainda estou com essa vaga aberta, está bem difícil de fechar!!

Grata,

***@***.***
DANIELLE RODRIGUES ALVES

Coordenadora de Gestão de Pessoas
***@***.*** (41) 3330-5400
***@***.***

***@***.***<https://www.facebook.com/gestran> ***@***.*** <https://www.linkedin.com/company/gestran/>  ***@***.*** <https://www.instagram.com/gestranoficial/>

gestran.com.br<https://gestran.com.br/>


De: Felipe Fialho ***@***.***>
Enviada em: sábado, 16 de abril de 2022 21:44
Para: frontendbr/vagas ***@***.***>
Cc: Danielle Alves ***@***.***>; Author ***@***.***>
Assunto: Re: [frontendbr/vagas] [Curitiba] Front-end Developer Angular na Gestran (Issue #6475)


Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
