### ISSUE TITLE
[REMOTO] Front-end Developer na Brisanet

### ISSUE THREAD

**Issue by DebsMaier** [frontendbr/vagas#6476]
## Brisanet

Somos uma empresa do segmento de telecomunicações (banda larga, tv a cabo, telefonia fixa e móvel), criada em 1998 pelo empreendedor José Roberto Nogueira, em Pereiro, sua cidade natal, localizada na região semiárida cearense. Nascemos do sonho de prover internet de qualidade e com preço acessível, onde nenhum outro provedor imaginava levar: o interior nordestino. Contribuímos para o desenvolvimento de regiões carentes de oportunidades e de investimentos, por meio da inclusão digital, movimentação da economia e geração de empregos.

Ano após ano, inovamos em tecnologia e ampliamos a nossa atuação. Contamos, hoje, com mais de 7 mil colaboradores, estando presente em mais de 200 cidades nos estados do Ceará, Paraíba, Pernambuco, Rio Grande do Norte, Alagoas, Piauí e Sergipe.

Já são mais de 700 mil assinantes utilizando a nossa conexão de alta qualidade, com velocidade três vezes maior do que a média brasileira, compatível aos padrões dos Estados Unidos e da Coréia do Sul. Já somos líder no somatório de clientes que usam banda larga fixa nos estados em que atuamos e seguimos em plena expansão pelo Nordeste, tanto em novas cidades do interior, como também nas capitais nordestinas.

## Descrição da vaga

Vaga com contrato vitalício para atuação com as stacks TypeScript e JavaScript, além dos frameworks React e Angular 8+

## Local
Remoto, apenas candidatos dos estados [CEARÁ], [PARAÍBA], [ALAGOAS], [PERNAMBUCO], [PIAUÍ] e [SERGIPE] 

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com TypeScript, JavaScript, React e Angular 8+
- Superior completo em TI 
- Certificação/curso de Architeture 
- Conhecimento em
Segurança de aplicações web.
Testes unitários, integração e carga em aplicações web.
Revisão de códigos;
Banco de dados relacional (Postgres);
Segurança da informação;
Inglês Técnico.

**Desejáveis:**
- Pós graduação em andamento ou concluída 

## Benefícios
- Plano de Saúde coparticipativo;

- Plano Odontológico;

- Seguro de Vida;

- Desconto na mensalidade de internet (após o período de experiência);

- Cartão de benefícios flexíveis no valor total mensal de R$ 1.000,00

**Diferenciais:**
- Oportunidade de atuação na empresa de banda larga mais bem pontuada dentre as empresas do Nordeste
- Cultura inclusiva por natureza, com autonomia e autodesenvolvimento

## Contratação
CLT 

## Como se candidatar

Por favor envie um email para deboramaier1997@gmail.com com seu CV anexado - enviar no assunto: Vaga Frontend - Brisanet

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: deboramaier1997@gmail.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
