### ISSUE TITLE
[Remoto] Desenvolvedor(a) Mobile React Native (Pleno ou Senior)

### ISSUE THREAD

**Issue by fernando-git-2021** [frontendbr/vagas#6477]
> Vaga Remota

## Nossa empresa

Somos um aplicativo de investimentos que tem a missao de democratizar o acesso a instrumentos financeiros de alta rentabilidade que podem ser apenas acessados atraves de uma tecnologia especializada.

## Descrição da vaga

Estamos a procura de um desenvolvedor mobile com experiencia em React Native para construir o front end de nosso aplicativo de investimento. Aqui voce terá todo o apoio de nosso time e tambem tera espaço para sugerir idéias. A principio a vaga é de caráter temporario até o final da construção do app mas isto pode ser revisto ao decorrer do projeto.

## Local

Remoto

## Requisitos

**Obrigatórios:**
-React Native
-ReactJS
-Conhecimento em NextJS
-Typescript
-Consumo de API
-Conhecimento de GIT
-Conhecimento em autenticaçao com JWT

**Desejáveis:**
-SASS
-Prettier e ESLint para padronizaçao de codigo
-Uso de UseHooks e Hooks nativos do react

**Diferenciais:**
- Experiencia em React com uso de Typescript é um diferencial.
- Experiencia comTailwind
- Experiencia com a biblioteca Jotai seria um grande diferencial podendo ser substituido por Redux

## Benefícios

- A combinar

## Contratação

- A combinar

## Como se candidatar

Por favor envie um email para fernando.mtn.esteves@gmail.com com seu CV anexado - enviar no assunto: Vaga React Native

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
