### ISSUE TITLE
[Remoto] Sênior React Front-end Developer na Pasquali Solution

### ISSUE THREAD

**Issue by Recrutas** [frontendbr/vagas#6478]
**Descrição da vaga**

Estamos procurando pessoas que tenha uma vasta experiência em desenvolvimento Front-End.

**Local**

Remoto

**Requisitos Obrigatórios:**

•	Magento;
•	HTML;
•	CSS;
•	Bootstrap;
•	JavaScript
•	Fortes conhecimentos em React 

**Contratação**

PJ - Valor a combinar.

**Como se candidatar?**

Envie seu currículo: https://cutt.ly/YQD04zv
Envie seu currículo: eliene.martins@pasqualisolution.com.br

**Labels**

•	Alocado
•	PJ
•	Sênior

**Sobre a Pasquali**

A Pasquali Solution é uma consultoria com foco em Alocação de profissionais de TI reconhecida pelo seu trabalho rápido e com excelência.
Estamos há mais de 18 anos no mercado e somos altamente especializada em Tecnologia da Informação.
Vantagens
•	Parceria com a Alura para cursos
•	Gratificação no mês de aniversário

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
