### ISSUE TITLE
[Alphaville] Front-End Developer na Ventron

### ISSUE THREAD

**Issue by Dani-Ventron** [frontendbr/vagas#648]
Front-End Developer
==================================================

## Descrição da vaga
Programador Front End

## Local

Alphaville

## Benefícios

a combinar, contratação CLT ou PJ

#### Diferenciais

-Projeto de tempo indeterminado

## Requisitos

**Obrigatórios:**
-	Conhecimento avançado em HTML5/CSS3/JavaScript
-	Experiência com pré-processadores CSS: SASS/LESS
-	Frameworks: Angular 1/2/4, ReactJS, Bootstrap
-	Experiência com serviços RESTful e API's
-	Conhecimento em conceitos de responsividade e design mobile
-	Desenvolvimento cross-browser
-	Controle de versionamento GIT
-	Práticas em testes de UI
-	Capacidade de resolução de problemas
-	

**Desejáveis:**
Diferencial: LESS, ReactJS e Bootstrap

## Contratação

PJ ou CLT

## Nossa empresa

A Ventron é uma consultoria do Grupo Cadmus, está recrutando para uma empresa de grande porte do segmento de benefícios.

## Como se candidatar

Por favor envie um email para daniele.silva@ventron.com.br com seu CV anexado - enviar no assunto: Front End

**Comment by LFeh** [comment]
É para trabalhar em que empresa?

**Comment by Dani-Ventron** [comment]
Será contratado pela Ventron
