### ISSUE TITLE
[Lisboa/Portugal] Frontend Developer @Integer Consulting

### ISSUE THREAD

**Issue by brunoalexandrecarvalho** [frontendbr/vagas#6482]
# Integer Consulting
A Integer Consulting é uma empresa portuguesa de consultoria em tecnologias de informação. Somos especialistas em serviços de IT outsourcing, software, projetos de nearshore e desenvolvimento à medida. Somos parceiros dos principais players tecnológicos a nível mundial e trabalhamos com empresas nacionais e multinacionais de diversos setores de atividade. A maioria dos projetos em que participamos são em Portugal, no Brasil e um pouco por toda a Europa. O que nos diferencia é o talento tecnológico e a experiência das pessoas que fazem parte da equipa e que integram os nossos projetos.

Estás à procura de novas oportunidades na área de IT? Temos novidades para ti!

## Este pode ser o desafio perfeito, se tiveres:

- Licenciatura e/ou Mestrado em Engenharia Informática ou similar;
- +4 anos de experiência profissional em desenvolvimento Frontend;
- Experiência com Angular e/ou React;
- Experiência em JavaScript, Typescript, HTML & CSS;
- Familiaridade com metodologias Agile;
- Inglês fluente (obrigatório). 

Se tens o amazINg tech talent pretendido e queres fazer parte da equipa INTEGER, responde a este anúncio com o teu CV atualizado para bruno.carvalho@integer.pt

Para saber mais como protegemos a tua privacidade, consulte a nossa Política em www.integerconsulting.pt

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
