### ISSUE TITLE
[Remoto] FullStack (React/Node) Developer na Legit.Art

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6490]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/fullstack-pleno-para-developer-br-reactnodemysql-203141733?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>Legit.art</strong> is looking for a <strong><ins>FullStack (React/Node) Developer</ins></strong> to join its technology team!</p>
<p>We're a Digital Art marketplace for Latin American markets</p>
<p><strong>Responsibilities:</strong></p>
<ul>
<li>Will work on a daily basis on delivering the backlog tasks&nbsp;</li>
<li>Agile Scrum Knowledge (will have daily, planning and review meetings)&nbsp;</li>
<li>Proactive work attitude</li>
</ul>

## Legit.Art: 
 <ul>
<li>We're a Digital Art marketplace for Latin American markets</li>
</ul>
</p>undefined</p>

 ## Habilidades: 
 - React.js 
- Node.js 
- MySQL
## Local: 
 100% Remoto
## Requisitos: 
 - 100% remote availability  
- Fluent in English  
- Team Player  
- Flexible thinker  
- Getting Shit Done attitude 
- Experience and knowledge in node and react
## Diferenciais: 
 - solidity 
- web3.js 
- blockchain 
- typescrypt

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [FullStack (React/Node) Developer na Legit.Art](https://coodesh.com/vagas/fullstack-pleno-para-developer-br-reactnodemysql-203141733?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
