### ISSUE TITLE
[Limeira - SP] Assistente de Suporte Pleno na Pasquali Solution

### ISSUE THREAD

**Issue by Recrutas** [frontendbr/vagas#6495]
**Descrição da vaga**

Estamos procurando pessoas que tenha uma vasta experiência em Assistente de Suporte Pleno.

**Local**

Presencial: Limeira - SP

**Requisitos Obrigatórios:**

•	Redes/telecom: TCP/IP, Ethernet, SSH , FTP, SFTP, Telnet, DNS, Proxy, rede Wi-Fi, Bluetooth, Roteadores , Switch, Modem 4G,  Ping, Traceroute, conceitos de  DHCP.
•	Protocolos: http, Https
•	Ingles fluente.

**Diferencial:**

•	Conhecimentos pratico com sistemas operacionais: Linux, Microsoft Windows tais como  processos, thread, shell script, Acesso remoto, leitura de  logs.
•	Facilidade de comunicação ( fluência oral  e escrita)

**Contratação**

PJ - Valor a combinar.

**Como se candidatar?**

Envie seu currículo: https://cutt.ly/YQD04zv
Envie seu currículo: eliene.martins@pasqualisolution.com.br

**Labels**

•	Alocado
•	PJ
•	Pleno

**Sobre a Pasquali**

A Pasquali Solution é uma consultoria com foco em Alocação de profissionais de TI reconhecida pelo seu trabalho rápido e com excelência.
Estamos há mais de 18 anos no mercado e somos altamente especializada em Tecnologia da Informação.
Vantagens
•	Parceria com a Alura para cursos
•	Gratificação no mês de aniversário

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
