### ISSUE TITLE
[Remoto] Front-end Developer @Nelogica

### ISSUE THREAD

**Issue by gabrielarochayy** [frontendbr/vagas#6498]
**SOBRE A NELOGICA:**
Desenvolvemos soluções de alta performance com o objetivo de construir o futuro do mercado financeiro!
Somos líderes de mercado em plataformas de negociação no Brasil e estamos expandindo nossos horizontes para o mercado de criptomoedas e bolsas internacionais.
Ao trabalhar na Nelogica, você se torna parte de um time composto pelos melhores talentos, interage com as maiores personalidades do mercado financeiro e seu trabalho impacta diretamente milhares de usuários.
No início do ano passado lançamos a versão web e mac da nossa plataforma de criptomoedas que está em constante crescimento. Ainda em 2022 visamos lançar muitos novos produtos inovadores para traders do mundo inteiro.

**O que é essencial que você apresente:**
- Ensino Superior completo ou em andamento em Ciência da Computação, Engenharia da Computação, Análise e Desenvolvimento de Sistemas ou áreas afins de Tecnologia da Informação;
- Experiência com desenvolvimento Front-end.

// Trabalhamos de forma remota 😀

**Curtiu?** Te candidata pelo nosso site: https://jobs.kenoby.com/nelogica/job/desenvolvedora-web-front-end/60afcd4d3ff98b380eff4773?utm_source=website
**Ou me envia teu currículo:** garocha@nelogica.com.br

Vou adorar te conhecer!

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/99677632/155007517-b72f9c86-bc62-42f9-8f6a-5aef7c57b88a.png)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
