### ISSUE TITLE
[100% REMOTO!] Front-end Developer (React.js/ Angular) na Redspark

### ISSUE THREAD

**Issue by MonicaRodrigues19** [frontendbr/vagas#6499]
Frontend Developer

**100% REMOTO**

O que você precisa ter?

- Conhecimentos em Javascript ES6/ES7
- HTML5, CSS3, 
- PRÉ PROCESSADORES (SASS)
- SPA, DESIGN RESPONSIVO WEB
- NPM, GULP, WEBPACK
- Styled-components 

**Forma de contratação**
CLT

**Benefícios**
Cartão de Benefícios Flexíveis Caju (VA/VR)
Assistência Médica e Odontológica Bradesco
Convênio SESC
Convênio FIAP
Convênio Udemy
Ajuda de custo para Inglês de até R$189,00/ mês
Auxilio Creche para filhos até 5 anos
Day Off
100% Home office flexível (Mesmo após pandemia)

**Como se candidatar**

Envie seu CV para o e-mail: pessoas@redspark.io com o assunto: Vaga Frontend _ou_ caso queira conversar direto com a gente só [chamar](https://abre.ai/areadepessoasredspark) 😊

**Sobre a empresa**

A redspark é uma empresa que a 15 anos cria experiências em Produtos Digitais alinhando tecnologia e design.
Com cases de projetos em empresas como Hospital Albert Einsten, Sesc, Claro, Banco Mercedes Benz. Buscamos sempre a inovação com a perspectiva de construir soluções que sejam aderentes aos negócios e principalmente desejável para as pessoas.

E o que você vai encontrar aqui?
Um ambiente descontraído, com muito aprendizado, desenvolvimento e desafios! 🚀

Vem ser sparker!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
