### ISSUE TITLE
[Amsterdam] Desenvolvedor Back-End (PHP) na Twitter Counter

### ISSUE THREAD

**Issue by guilhermepontes** [frontendbr/vagas#65]
## About the role
**We currently have 2 positions available - one for Senior! Feel free to send us your CV!**

As a backend developer you will be instrumental in developing new features, maintaining the current codebase, squashing bugs, optimising performance and managing DevOps.

You will also be helping us keep our edge by pushing the code to its outermost limits with as little lines as possible, and investigating and implementing big data solutions.

## Local
Amsterdam, Netherlands
Currently in: [WeWork Metropool](https://www.google.nl/search?q=WeWork+Metropool&tbm=isch)

## Benefits
- Working in the heart of Amsterdam
- A swanky, new laptop of your choice. The best tools money can buy.
- A small, international (11 different nationalities till now!) and FUN team.
- Great personalized lunch delivered by the really fantastic [de Buurtboer](https://www.debuurtboer.nl/).
- Free unlimited beer everyday after 16h30. 🍻 
- Free unlimited 6 types of coffee.
- Lots of parties! 
- We focus on performance, not hours, and so you would be able to occasionally work remotely or at flexible hours.

## Who we think will be a great fit

**Required:**
- Good english communication skills - just the enough, don't worry about it!
- 3+ years experience in backend web development
- Native to PHP and MySQL
- Experience with Linux command line utilities and LAMP configuration/maintenance.
- Good knowledge of version control (Git)
- Lean and agile development as a second nature
- Independently and responsible; Works well with little supervision
- Living or want to live in or near Amsterdam

**Desirable:**
- Very fast learner, eager to explore and innovate
- Owning a relevant academic degree or an interesting story
- A good team player who is fun to work with

**Big plus:**
- NoSQL / Big data experience
- Experience working with Twitter, Facebook or LinkedIn API’s

## Our company
Twitter Counter was founded by the same founders of [The Next Web](http://thenextweb.com) back in 2008 and right now is the most popular provider of Twitter user statistics and a leading service for Twitter Analytics.

As we're tracking almost 200M Twitter accounts, a multitude of user stats are generated daily and are added to our ever growing database of unique user statistics and trends. This gives us amazing opportunities to deliver value to our users and customers. 

## How to apply
Please send an email to guilherme@twittercounter.com. In the subject state that you are applying for the BackEnd Developer position, attach your CV, links of work (Github) and tell us about who you are and why this position may be right for you.

We would love to hear from you!
<br>
[Checkout more jobs avaiable on Twitter Counter, invite your friends!](http://twittercounter.com/pages/jobs)

**Comment by fejaum** [comment]
Only BackEnd? None position for FrontEnd?

**Comment by guilhermepontes** [comment]
@fejaum tem vaga de FrontEnd sim! Mas estamos dando prioridade para pessoas da Europa!

**Comment by fejaum** [comment]
Bom, mandei meu currículo, se agradarem podem entrar em contato ;)

**Comment by eduardojmatos** [comment]
@guilhermepontes mano, a vaga já foi preenchida? Nos avise pra mantermos ou removermos da lista :)

**Comment by guilhermepontes** [comment]
@eduardojmatos sim! Vou fechar, valeu!

**Comment by eduardojmatos** [comment]
@guilhermepontes boa! :)

**Comment by camilatigre** [comment]
@guilhermepontes 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by guilhermepontes** [comment]
@camilatigre nope.

**Comment by camilatigre** [comment]
Blz. Obrigada por responder

Em 24 de nov de 2016 12:33, "Guilherme Pontes" <notifications@github.com>
escreveu:
