### ISSUE TITLE
[São Paulo] Front-End Developer na PSM Company

### ISSUE THREAD

**Issue by fwfreitas** [frontendbr/vagas#650]
## Descrição da vaga

Desenvolvimento de soluções de conteúdos digitais para aplicativos.
HTML5, CSS3, Java script e React.

## Local

São Paulo - Chácara Sto. Antonio 

## Benefícios

- Plano de saúde
- Vale Transporte
- Vale Refeição 

## Contratação

CLT

## Nossa empresa

A PSM Company é uma empresa líder em serviços integrados de Recrutamento e Seleção em TI e Telecom, resultado de mais de 25 anos de experiência profissional. O alicerce de sua sólida história de sucesso está nos diferenciais competitivos como inovação, postura consultiva e excelência operacional. Empresa que possui 10 anos no mercado de tecnologia, atuando com processos de alocação (terceirização) e hunting (contratação própria do cliente). Possuímos uma equipe de gestão de pessoas focada em dar o suporte necessário aos nossos clientes e colaboradores, onde conseguimos acompanhar o desenvolvimento de cada profissional alocado.

## Como se candidatar

Por favor envie um email para vanessa.almeida@psmcompany.com.br com seu CV anexado - enviar no assunto: Front-End Developer

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
