### ISSUE TITLE
[REMOTO] Desenvolvedor Júnior na Codex Utilities

### ISSUE THREAD

**Issue by luanasantosog** [frontendbr/vagas#6501]
## Nossa empresa

A CODEX é uma empresa do Grupo Imagem, com foco em desenvolvimentos especializados que combinam sistemas de informação, consultoria setorial, especialistas em tecnologia e melhores práticas de gestão para apoiar nossos clientes de forma integrada, atendendo aos mais diversificados processos de negócios.

## Local

Remoto

## Requisitos

**Requisitos:**
- Formação em curso superior de ciências da computação, análise de sistemas e/ou sistemas de informação;
- Experiência em C# (.NET Core e .NET Framework);
- Conhecimento em Javascript;
- Conhecimento em AngularJS e Angular 8+;
- Utilização de padrões de desenvolvimento de software;
- Conhecimento em SQL (Consultas e Desenvolvimento de Procedures PL/SQL);
- Versionamento com GIT.

**Desejáveis:**
- Conhecimento em criação de APIs REST;
- Experiência com CI/CD com Azure Devops;
- Vivência em Desenvolvimento ágil;
- Gerenciamento de banco de dados Oracle e SQL Server;
- Conhecimento em padrões e boas práticas para web;
- Desenvolvimento com Python;
- Experiência com desenvolvimento de sistemas de informação geográfica.

## Contratação

 CLT a combinar

## Como se candidatar

Cadastre-se em: https://jobs.kenoby.com/codex-utilities/job/1138-analista-desenvolvedor-junior-codex-utilities/61cc7c95dcf8272cd8fba984?utm_source=website

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior

**Comment by heltonWilekeDarosci** [comment]
Are you guys sure that it's for a Júnior position?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
