### ISSUE TITLE
[Full Remote] Frontend Software Engineer Sr na Cobli

### ISSUE THREAD

**Issue by guilhermepiza** [frontendbr/vagas#6502]
Para se candidatar: https://bit.ly/front-cobli

**### COBLI**
Somos uma startup de tecnologia para logística que acredita que esse setor será totalmente conectado - chega de troca de mensagens desencontradas pelo WhatsApp, é hora de concentrar tudo em um só lugar. Os dados vão deixar tudo mais eficiente e, dessa forma, pessoas, bens e serviços chegarão cada vez mais rápido, de maneira mais barata e na hora correta.

Por isso, todos os dias, criamos tecnologia IoT e plataformas de inteligência que levam inovação às frotas que circulam pelo país em um serviço de gestão de frotas que pode ser acessado por um painel web e aplicativos de celular.
Com milhares de clientes, centenas de milhões de quilômetros dirigidos e mais de U$100 milhões em investimento, as possibilidades com os dados gerados só aumentam.

Fomos a primeira empresa da América Latina a vencer o Harvard New Venture Competition da Universidade de Harvard, em 2016. Desde então, crescemos exponencialmente. Sendo 450%+ só no ano passado.
Planejamos uma performance ainda mais desafiadora e próspera para os próximos anos.

**POR QUE ENGENHARIA DE SOFTWARE É O CORAÇÃO DA COBLI?**
Nosso produto inteiro nasce, se transforma e evolui literalmente nas mãos do nosso time de engenharia. Entregamos uma solução completa de hardware e software para tornar a operação dos nossos clientes muito mais eficiente. Para isso, todos aqui buscam entregar a melhor experiência de usuário possível, e isso só é sustentável quando a experiência de desenvolvimento também é uma das melhores possíveis.

**O QUE SERÁ ESPERADO DE VOCÊ COMO PARTE DO TIME?**
Como Frontend Software Engineer, você irá participar do planejamento e implementação de funcionalidades e melhorias no painel da Cobli, prezando pela organização do código e performance. 

Somos adeptos de métodos ágeis e pair programming e esperamos que você possa dar continuidade com a gente nessa cultura. Acreditamos que velocidade e qualidade não são mutuamente exclusivas, e esperamos o mesmo de você. 

Gostaríamos que você ajudasse a avaliar a arquitetura end-to-end, sendo capaz de propor melhorias desde os métodos de deploy até a experiência do usuário, estando atento para critérios como complexidade, qualidade, escalabilidade, latência, integridade, consistência, entre outros.

**O dia-a-dia:**
- Colaborar com todo o processo de desenvolvimento de software: arquitetando, desenvolvendo, revisando e mantendo código eficiente, e buscando a mais alta qualidade;
- Interagir dentro de um time multidisciplinar para construir e entregar continuamente um produto que cada vez mais faça os olhos dos nossos usuários brilhar;
- Trabalhar próximo às diversas áreas da empresa, como PMs e UX Designers, encontrando novas formas de transformar seu conhecimento em valor para nossos clientes e internamente para a Cobli.
- RESPONSABILIDADES E ATRIBUIÇÕES
- Bastante experiência em JavaScript (ES6+, ESNext) e TypeScript;
- Excelentes habilidades desenvolvendo código claro, eficiente e organizado, visando a manutenibilidade e escalabilidade do código;
- Sólida experiência em compreensão e design de algoritmos, estruturas de dados, padrões de projeto e arquiteturas de sistemas;
- Experiência trabalhando com as principais APIs do React, bibliotecas de controle de estado como Redux;
- Conhecimento de desenvolvimento de aplicações que comunicam com serviços RESTful e GraphQL;
- Experiência em diversos tipos de testes automatizados (unitários, integração, ...);
- Conhecimento da arquitetura BFF;
- Experiência com ferramentas de build e bundle (Webpack), e gerenciamento de dependências (yarn, npm, lerna, etc...).
- REQUISITOS E QUALIFICAÇÕES

**Será diferencial se você tiver:**
- Experiência com profiling e debugging de aplicações frontend, identificando e removendo gargalos de execução em Javascript e criando CSS otimizado;
- Experiência no gerenciamento de mono-repos;
- Ser capaz de criar layouts responsivos;
- Estar familiarizado com técnicas de organização de CSS (SMACSS, BEM, CSS Modules);
- Experiência com métricas de experiência [Web Vitals](https://web.dev/i18n/pt/vitals/) (LCP, FID e CLS);
- Senso de web design, familiarizado com as melhores práticas para acessibilidade e internacionalização;
- Ser capaz de contribuir em discussões filosóficas do tipo, mas não limitado a:
- HOCs X Hooks
- Eslint X Prettier
- Tabs X Spaces
- Atom X VSCode X WebStorm
- GitLab X Github
- DC x Marvel

**Nossa contratação é CLT e oferecemos:**
- Vale refeição;
- Vale alimentação;
- Plano de saúde; 
- Auxílio creche;
- Seguro de vida;
- Bônus semestral baseado em performance;
- Ajuda de custo mensal para home office;
- Horário flexível e trabalho 100% remoto;

**AQUI VOCÊ VAI ENCONTRAR:**
- Feedback recorrente e focado no crescimento profissional;
- Ciclo de avaliação de performance;
- Plano de carreira e oportunidade de crescimento;
- Oportunidade de ganhar stock options (ações da empresa);
- Liberdade para sugerir mudanças independente da área ou nível hierárquico;
- Um time de excelência técnica, focado em melhoria contínua e inovação; 
- Ambiente de trabalho leve, descontraído e flexível;
- Liberdade para ser você mesmo: nos importamos com o que você faz, não como se veste;
- Oportunidade de contribuir efetivamente com a construção de uma startup em crescimento acelerado.

**POR QUE TRABALHAR NA COBLI? 🚀**

Trabalhamos para ser a melhor startup do Brasil, com um produto excelente.

Para atingir esses resultados expressivos, prezamos pelo trabalho em equipe, pela cultura de feedback e por desenvolver estruturas que evoluam no longo prazo.

Somos impulsionados por times compostos por pessoas com quem temos orgulho de conviver, aprender e contrastar. Prezamos por um ambiente produtivo e repleto de pessoas tecnicamente excelentes e inspiradoras. E, para equilibrar, incentivamos que a descontração faça parte do dia a dia.

Aqui, os Coblers são responsáveis pela direção e pela velocidade de suas carreiras. Como forma de apoiá-los nesse desenvolvimento, proporcionamos ritmo de aprendizado intenso, com projetos desafiadores e de alta performance.

Asseguramos benefícios úteis, compensação justa e criamos estruturas para que os melhores desempenhos sejam reconhecidos e recompensados exponencialmente.

Nosso desejo é que você possa ser completamente você na Cobli. Você é livre para ser você porque focamos no seu desenvolvimento e carreira. O respeito ao outro é um ato inegociável para nós e a valorização profissional é independente de gênero, etnia, religião, orientação sexual, classe social e outras diferentes realidades. Nos orgulhamos em ser uma empresa transparente que proporciona uma escuta ativa, oportunidades iguais e um ambiente seguro e acolhedor.

Gostou? https://bit.ly/front-cobli

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
