### ISSUE TITLE
[Remoto] Frontend Developer  na RBR DIGITAL LTDA

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6506]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-002151688?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>RBR Digital </strong>busca pessoa <strong>Frontend Developer</strong> para compor seu time!</p>
<p>A RBR Digital é uma Agência Web centrada em soluções de alta performance e segurança para clientes de nível empresarial orientados a resultados.</p>

## RBR DIGITAL LTDA: 
 <p>A RBR Digital é uma Agência Web centrada em  soluções de alta performance e segurança para clientes de classe empresarial orientados a resultados.</p>
</p>

 ## Habilidades: 
 - React.js 
- Next.js 
- HTML 
- CSS
## Local: 
 100% Remoto
## Requisitos: 
 - Conhecimento sólido de Javascript, ReactJS 
- Conhecimento sólido do funcionamento e integração de APIs REST 
- Conhecimento básico em segurança de APIs (auth tokens, jwt, auth0 (diferencial))
## Diferenciais: 
 - Experiência com desenvolvimento orientado a Testes (TDD, BDD) 
- Conhecimento em desenvolvimento em NextJS (SSG, SSR e ISR)
## Benefícios: 
 - Horário Flexivel
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Developer  na RBR DIGITAL LTDA](https://coodesh.com/vagas/frontend-002151688?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
