### ISSUE TITLE
[REMOTO] Front-end Developer Sênior na CI&T

### ISSUE THREAD

**Issue by lpnavarro** [frontendbr/vagas#6508]
> Vaga Remota 

## Nossa empresa

CI&T is a digital specialist, partner in end-to-end digital transformation. As digital natives, we bring a 26-year track record of accelerating business impact through complete and scalable digital solutions. With a global presence of more than 5.000 professionals in strategy, research, data science, design and engineering, we unlock top-line growth, improve customer experience and drive operational efficiency.

## Descrição da vaga

- Escrever código com qualidade e de fácil evolução, utilizando as melhores práticas de desenvolvimento.
- Apto a efetuar code-reviews e definir melhores práticas dentro da engenharia de software.
- Definir novas soluções e evoluir a arquitetura atual.
- Ser uma pessoa comunicativa e bem integrada com o cliente.
- Criar e manter documentações de software.
- Ser responsável por manter e escalar as aplicações.
- Trabalhar dentro de esteiras de desenvolvimento mínimo de maturidade DevOps (SCM, CI/CD, Quality Gate)

## Local

 Remoto

## Requisitos

**Obrigatórios:**

- Conhecimento consolidado em React Native
- Experiência em desenvolvimento em arquitetura de micro-serviços

**Diferenciais:**
- Experiência NodeJs
- Experiência Cloud. Desejável: AWS

## Benefícios

- Plano de saúde
Plano de Saúde integral
Plano Odontológico
Plataforma de saúde mental e psicoterapia online
Gympass

Vale Alimentação ou  Vale Refeição 
Auxílio Home Office 
Seguro de Vida
Programa Participação de Lucros

**Diferenciais:**
100% remoto
Horário Flexível
Plano de Carreira
Feedback 360°
Guildas/grupos para compartilhar conhecimento. 

## Contratação

CLT

## Como se candidatar

Acesse: https://bit.ly/33LgOWn

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 20 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
