### ISSUE TITLE
[Amsterdam] Front-End Developer na Bitvavo

### ISSUE THREAD

**Issue by lucasbento** [frontendbr/vagas#6509]
## Nossa empresa

In 2018, Bitvavo launched the first version of its digital assets trading platform, to bridge the gap between traditional currencies and digital assets. By offering transparent fees, a wide range of assets and an easy to use platform, Bitvavo is making the currency of the future accessible for everyone.

In two years time, Bitvavo has established itself as the market leader in the Netherlands, with hundreds of thousands of users exchanging over **two billion euros** worth of digital assets a year.

Our team, located in Amsterdam, is looking for self-driven, talented people who can help us with making digital assets available for everyone. Become a part of one of the fastest growing tech companies in the Netherlands, on the eve of European expansion.

## Descrição da vaga

Improve and maintain the most user-friendly digital asset exchange in the Netherlands and work on products that are used by hundreds of thousands of Bitvavo users. 

- Work closely with the design team, experienced frontend developers, marketing team and back-end developers
- Launch new Bitvavo products and features
- Contribute to the Bitvavo user experience by suggesting and improving features

## Local

Amsterdam - The Netherlands

## Requisitos

**Obrigatórios:**
- Have deep understanding of web development with HTML, JavaScript, CSS and React
- Have substantial knowledge of front-end technologies
- Like to write quality code and follow (as well as improve) coding standards
- Have a keen eye for detail when implementing designs and writing code
- Have experience with TypeScript, Redux and Jest

**Desejáveis:**
- Experience with Redux architectures with Redux-Saga or Redux-Thunks, WebSockets, Cypress, Docker and Kubernetes
- Experience with Fintech services and startups

## Benefícios

- Relocation package (we help you relocate to The Netherlands)
- Work at our office in one of the best locations in Amsterdam
- Work remotely up to 4 days per week from The Netherlands
- Excellent employment terms, including a competitive salary and an employee profit-sharing scheme
- Be actively involved with the latest technologies and innovations
- 26 days of annual leave
- Budget for external trainings and courses
- A position in a unique, young and fast growing Fintech company

## Como se candidatar

Apply [here](https://jobs.bitvavo.com/detail/4019779101/front-end-developer), specify `Front-End Brasil` in the referral field.

#### Alocação
- Alocado

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
