### ISSUE TITLE
[Jaú-sp e Região] Front-End Developer na StartUp Alboom

### ISSUE THREAD

**Issue by Quima** [frontendbr/vagas#651]
## Descrição da vaga

Trabalhar no time de desenvolvimento que cuida da plataforma de sites profissionais da Alboom. Nossa missão é entregar um produto de qualidade que seja simples e direto, visando sempre o usuário. Este profissional estará trabalhando diretamente com o painel de controle do site e o visual final, podendo entender e atuar em todo o ecossistema de funcionamento deste produto. Também será responsável por todas novas implementações e correções.

## Local

Jaú ou região preferencialmente, porém também aceitamos remotos

## Benefícios

- Auxílio transporte
- Seguro de vida
- VA ou VR de R$ 350/mês

#### Diferenciais

- horário flexível
- Incentivo e auxilio eventos
- sala de jogos e descanso
- ambiente descontraído e 
- happy hour sempre

## Requisitos

**Obrigatórios:**
- Ser apaixonada(o) por desenvolvimento de software e tecnologia;
- Ter facilidade para trabalhar dentro de times multi-disciplinares;
- Saber escrever codigo limpo e legível por humanos;
- Ter experiência com React e Redux;
- Possuir conhecimentos de integração utilizando API RESTful;
- Saber trabalhar com ferramentas de controle de versão Git;
- Conhecimentos de design de interface e experiência do usuário;

**Desejáveis:**
- Pelo menos 1 ano de experiência com React e Redux
- Ter experiência em Ionic

**Diferenciais:**
- Ter conhecimento de práticas de XP (TDD, pair programming, refactoring, continuous integration, etc);
- Conhecer e ter experiência com testes unitários, de aceitação, mocks, etc;
- Conhecimentos de desenvolvimento WEB (HTML, CSS, Javascript, jQuery, etc);
- Experiência com métodos ágeis (Scrum, Kanban, Lean, etc);
- Experiência em mentoring/coaching de pares e team members menos experientes;

## Contratação

CLT ou PJ,  a combinar

## Nossa empresa

A Alboom é hoje a maior plataforma de serviços digitais para fotógrafos e artistas visuais da América Latina. A Alboom engloba a maior diversidade de produtos e serviços para fotógrafos, contando com sites profissionais, aprovação de fotos, aprovação de álbum, aprovação de vídeos, criação de galerias, CRM para fotógrafos e muito mais. Além disso temos como missão ser uma plataforma de multi aplicação que trás uma camadas gigantesca de micro-serviços que fazem com que a plataforma funcione e entregue a melhor experiência para nossos usuários.

## Como se candidatar

Por favor envie um email para recruit@alboom.com.br com seu CV anexado - enviar no assunto: Vaga Front-End

**Comment by raloliver** [comment]
Enviado!

**Comment by inodaf** [comment]
Salve @Quima. Haha

Uma correção da seção _Desejáveis_:
> Pelo `menor` > `menos` 1 ano de experiência com React e Redux

**Comment by Quima** [comment]
Salve @inodaf 

Corrigido.

Abraços

**Comment by paulitolinhares** [comment]
Enviado!

**Comment by allansp9** [comment]
Ainda está aberta a vaga?

**Comment by HaluDeCassia** [comment]
Enviado

**Comment by ribeiroevandro** [comment]
Enviado!

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by Quima** [comment]
Boa tarde Felipe

Ainda está aberto. Contratamos 2, porém já precisamos de mais 3

Abraços

**Comment by vinyguedess** [comment]
Enviado

**Comment by lumarega** [comment]
enviado!

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
