### ISSUE TITLE
[Liberdade - SP] Infrastructure Analyst na Pasquali Solution

### ISSUE THREAD

**Issue by Recrutas** [frontendbr/vagas#6511]
**Descrição da vaga**

Estamos procurando pessoas que tenha uma vasta experiência em Analista de Infraestrutura. 

**Local**

Presencial : Liberdade - SP

**Requisitos Obrigatórios:**

•	Administração Base de Dados SQL Server
•	Instalação, Configuração e Monitoramento de servidores.
•	Performance, troubleshooting, Tunning e Migração de Banco de Dados
•	Monitoramento ambientes de alta disponibilidade e performance.
•	Concessão de acesso do Sysadmin File e Server/Active Directory
•	Plano de Backup e Restore/software ARCServe e Fitas LTO;
•	Deploy e adm. de ambientes Web, Internet Information Services
•	Windows Server 2016: Failover Clustering, Hyper-V, AD, IIS e DNS
•	Adm. de ambientes on-premises 
•	Excel

**Diferencial:**

•	Cloud AZURE

**Contratação**

PJ - Valor a combinar.

**Como se candidatar?**

Envie seu currículo: https://cutt.ly/GjcZYfq 
Envie seu currículo: barbara.silva@pasqualisolution.com.br

**Labels**

•	Alocado
•	PJ

**Sobre a Pasquali**

A Pasquali Solution é uma consultoria com foco em Alocação de profissionais de TI reconhecida pelo seu trabalho rápido e com excelência.
Estamos há mais de 18 anos no mercado e somos altamente especializada em Tecnologia da Informação.
Vantagens
•	Parceria com a Alura para cursos
•	Gratificação no mês de aniversário

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
