### ISSUE TITLE
[REMOTE] Full Stack Engineer @BetaAcid

### ISSUE THREAD

**Issue by thismarcoantonio** [frontendbr/vagas#6513]
Como a vaga é para uma empresa sediada em NY, inglês é necessário, por isso a descrição em inglês.

## Our company

Build Software like a Startup even if you aren’t one.
Beta Acid is a software development agency based in New York City and we are looking to add four to five full stack engineers to our team.

## Responsibilities

- Participate in all aspects of agile software development including rituals, design, implementation, and deployment
- Architect and provide guidance on building end-to-end systems optimized for speed and scale
- Work primarily with TypeScript/JavaScript and React
- Engage with designers and front end engineers to develop reactive and responsive front ends.
- Help write APIs and 3rd party integrations

## Required Skills and Qualifications
- 5+ years of full stack experience building web applications
- Ability to understand business requirements and translate them into technical requirements
- Strong proficiency in HTML, CSS, TypeScript and JavaScript, including DOM manipulation and the JavaScript object model
- Thorough understanding of React.js and its core principles
- Unit/integration testing experience, including Jest
- Experience with common front-end development tools such as Babel, Webpack, NPM, Git, etc.
- Experience designing and integrating APIs
- Experience designing and integrating SQL databases
- Excellent debugging and optimization skills
- Knowledge of modern authorization mechanisms, such as JSON Web Token
- Familiarity with modern front-end build pipelines and tools

## Preferred Qualifications
- Experience with Storybook & Chromatic
- Experience with Gatsby
- Experience designing serverless web applications and integrating caches, queues and NoSQL databases
- Shopify, SendGrid, Twilio, Stripe & GraphCMS integration experience
- AWS Lambda, SQS, API Gateway, CloudFront & IAM experience
- Experience with Terraform

## How to apply
Please apply through Linkedin:
https://www.linkedin.com/jobs/view/2928605880

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
