### ISSUE TITLE
[Remoto] Frontend React Developer na YOURS BANK

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6514]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/front-react-pleno-201354710?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>YOURS BANK </strong>busca pessoa<strong> Frontend React</strong> para compor seu time!</p>
<p>A YOURS é uma fintech que tem por propósito Ensinar Educação Financeira para crianças e adolescentes, e fazemos isso sendo a sua primeira instituição financeira. O projeto iniciou em 2020 e hoje caminha em expansão para todo o Brasil.</p>
<p><strong>Atividades:</strong></p>
<ul>
<li>Trabalhar com a equipe no desenvolvimento das novas funcionalidades da aplicação mobile e web e na manutenção e melhorias do sistema.</li>
</ul>

## YOURS BANK: 
 <p>Banco digital para crianças e adolescentes.</p>
</p>

 ## Habilidades: 
 - React 
- React Native 
- Redux
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência com React, React native e Redux 
- Experiência comprovada com Frontend

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend React Developer na YOURS BANK](https://coodesh.com/vagas/front-react-pleno-201354710?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
