### ISSUE TITLE
[Florianópolis - SC] Front-End Developer Sênior (React.js) na Conpass

### ISSUE THREAD

**Issue by osnysantos** [frontendbr/vagas#652]
## Local

Florianópolis - SC

## Benefícios

- Descontos em escolas de Idioma, Universidades, Academias, entre outros serviços
- Vale-transporte
- Vale Refeição
- Frutas à vontade no headquarters
- Conhecer o ecossistema de startups e empresas de software do Brasil e Mundo
- Ser um dos primeiros funcionários de uma empresa global com crescimento rápido
- Desenvolvimento pessoal acelerado
- Desenvolver habilidades em Startups e User Onboarding
- Seminários semanais para aprendizado
- Trabalhar com pessoas super talentosas
- Bom ambiente de trabalho
- No dress code

## Requisitos
- Alto conhecimento em HTML5 e CSS3
- Forte proficiência em JavaScript, incluindo manipulação de DOM
- Compreensão completa de React.js e seus princípios fundamentais
- Experiência com React.js (como o Redux)
- Familiaridade com as novas especificações do EcmaScript
- Familiaridade com APIs RESTful
- Experiência com ferramentas comuns de desenvolvimento de front-end como Babel, Webpack, NPM, etc.
- Capacidade de entender os requisitos de negócios e traduzi-los em requisitos técnicos
- Habilidade para benchmarking e otimizações
- Familiaridade com as ferramentas de controle de código (Git)
- Familiaridade com testes de navegador e depuração
- Familiaridade com o Agile

**Desejáveis:**
- Conhecimento em UI e UX
- Experiência com Node / Mongo

## Contratação

CLT

## Nossa empresa

Se você é apaixonado por tecnologia, tem sede de aprendizado, gosta de trabalhar com autonomia e deseja fazer parte de uma startup de rápido crescimento, você é a pessoa certa para nosso time de Produto!
 
A Conpass aumenta vendas em trial, retenção de clientes e reduz custos de suporte para empresas de software por meio do user onboarding. Simplificamos a experiência do usuário por meio de tutoriais guiados, notificações, suporte automatizado e campanhas de engajamento personalizadas em seu software. Solução configurada e integrada em minutos, sem precisar programar.
Com uma metodologia própria, já ajudou empresas como Totvs, Linx e Softplan, e guiou mais de 400 mil pessoas a atingirem sucesso dentro dos sistemas de seus clientes.
 
Responsável pelo maior Portal de User Onboarding da América Latina, com vários cases de sucesso , dentre eles o da Loja Integrada, que teve um aumento de 60% em suas vendas em trial e redução de 33% em seus chamados de suporte, e o da Projuris, que reduziu seu churn em 30% e aumentou suas vendas em 20%, após aplicação da Conpass.
 
A empresa possui uma estrutura horizontal, incentivando o empoderamento do time, a criatividade, a colaboração e a co-criação. Somos focados em resultados e guiados a dados. Vem dominar o mundo conosco!

## Como se candidatar

http://trabalheconosco.conpass.io/o/desenvolvedor-frontend-senior-reactjs

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by osnysantos** [comment]
Por enquanto sim, mas em breve fecharemos.

**Comment by osnysantos** [comment]
Essa vaga já foi preenchida.
