### ISSUE TITLE
[Remoto] Front-end Developer Angular na HunterCo

### ISSUE THREAD

**Issue by LuciaGpires** [frontendbr/vagas#6525]
> Vaga 100% Remota 

## Nossa empresa

Somos uma empresa jovem que busca atendimento de excelência para seus clientes, respeitando cada parceiro de negócio, seja um profissional do time, fornecedor ou cliente.
Inconformados com um mercado que preza por volume, buscamos padrões de excelência para conectar pessoas e sistemas e promover uma jornada digital incrível!

## Descrição da vaga

Desenvolver novas funcionalidades do produto; Dar manutenção em funcionalidades já existentes; Procuramos alguém que queira fazer parte de um time multidisciplinar (UX, UI, QA, PO, Devs), trabalhar numa cultura ágil, onde a pró-atividade é muito bem vista, com responsabilidade.

## Local

Remoto

## Requisitos

**Obrigatórios:**
Experiência profissional como Dev a pelo menos 6 anos, e 3 com Angular;
Experiência no lifecycle completo de desenvolvimento frontend;
Bons conhecimento em bancos de dados relacional;
Experiência com integrações de sistemas e APIs.

**Desejáveis:**
Conhecimentos em segurança de aplicações;
Experiência com arquitetura de microserviços;
Experiência com testes automatizados;
Conhecimentos de cloud, delivery (entrega contínua).

**Diferenciais:**
N/A

## Benefícios

Acolhimento psicológico
Ambiente descontraído de trabalho
No-dress code
Horário flexível
Happy hour online

## Contratação

PJ 

## Como se candidatar

Por favor envie um email para lucia.pires@parceirohunterco.com.br com seu CV anexado - enviar no assunto: Vaga Angular

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: lucia.pires@parceirohunterco.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
