### ISSUE TITLE
[REMOTE] Full Stack Software Engineer at ChangeX

### ISSUE THREAD

**Issue by robsonmafra** [frontendbr/vagas#6526]
## About ChangeX

We are ChangeX. We have built a platform to connect communities to proven innovations and finance.

Our mission? To empower people everywhere to change their communities for the better by making it easy for them to access the innovations, funding and support they need. So far, more than 17,000 community projects have started through ChangeX, scaling almost 100 innovations and benefitting over 600,000 people.

Our business model is called Impact as a Service. We make it easy for funders to invest in the innovations they want to spread in regions they care most about. Our partners include Microsoft, Accenture, Lego Foundation and AWS. 

We are in an exciting growth phase, as we prepare to launch in multiple new regions. And we are growing our team across all functions to deliver on this growth.

### Our team and how we work:

We are simplifying and accelerating the way people fund, start and grow projects in their communities. We’re looking for engineers who share our belief in the power of great technology to transform lives.

Remote working is part of our company’s DNA. For example, our development team currently works remotely, with team members in Dublin and Mayo in Ireland, Barcelona in Spain and Joinville in Brazil.

As a development team, we run a lightweight process that focuses on feature-based delivery on a weekly basis. Our coordination and communication are mostly through daily ‘catch-up meetings’ and use of appropriate tools such as Trello for backlog management, Slack for communication and Git(GitHub) for source control and feature deployment through PRs and Milestones.

We make use of peer review for all design and development work. In general, we strive for an approach that empowers and trusts individuals to ‘do the right thing’.

You can find more about our team here: https://www.changex.org/pages/about

## Job Description

The Full Stack Software Engineer is an opportunity for mid to senior level developers to be part of the core team that scales ChangeX over the coming years.

We are currently going through an exciting growth phase, evolving from a traditional RoR architecture to additionally support a modern “single page application” approach. This evolution exposes our application as a set of APIs consumed by React to provide a rich interactive experience.

As part of this project, you will work on re-building the fund-management UI in our application.

## Location

Remote. We are remote-first for many years and we have team members in Brazil, Ireland, the US and Spain.

## Requirements

**Must have:**
- Strong experience with React or similar Javascript-based libraries
- Experience working across the entire stack (Ruby on Rails, Javascript, PostgreSQL), ideally
- Strong UX and design sensibilities
- Strong programming skills with a focus on clean design, well-refactored code and automated testing
- Confidence playing a significant role in the vision and development direction of the product
- A demonstrated commitment to social change
- Strong empathy and ethical fibre

**Technologies we use:**
- React
- Ruby on Rails is our primary server framework
- Deployed using Heroku for managing infrastructure
- PostgreSQL Database
- GitHub for source code management and process support
- Travis for continuous integration

## Benefits

- Flexible working options: remote, in office or a hybrid of the two;
- 25 holiday days plus flexible hours;
- Master new skills from those around you with onsite/online talks and networking at our hubs;
- Access to a great work environment and facilities at Dogpatch Labs in Dublin, our New York hub or a co-working space convenient for you.

## Type of role

Permanent contract (PJ)

## How to apply?

As a first step, please send your resume and examples of your work (e.g. GitHub repositories, blog articles, etc) to Katie at jobs@changex.org by Friday February 25th. If you do not have suitable examples to share, we can work on something together.

You can see the full job description here: https://www.changex.org/blog/full-stack-software-engineer/

## Recruitment process

We will shortlist several candidates for a series of interviews with a cross-section of our team. We like candidates to talk to as many of our team as possible to allow us – and you – to make the best decision possible. If you have any question, please email us at: jobs@changex.org 

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
