### ISSUE TITLE
[Remoto] Front-end Developer na SPRYLIFE

### ISSUE THREAD

**Issue by felp1402** [frontendbr/vagas#6528]
## Spry Life

Sprylife é uma startup do mercado fitness que tem por objetivo conectar alunos e personal trainers. A SpryLife oferece uma plataforma online em que os profissionais se cadastram,  divulgam suas especialidades e precificam seus trabalhos para alunos de todo o Brasil.

## Descrição da vaga

- Desenvolver novas funcionalidades;
- Manter e otimizar os projetos de front-end;
- Criar interfaces e novas experiências de usuário;
- Propor soluções de UX/UI;
- Manter e interagir com repositório GIT;
- Interagir com sistema de chamados JIRA.

## Local

100% Remoto.

## Requisitos

**Obrigatórios:**
- Angular 8
- TypeScript

**Desejáveis:**
- HTML, CSS e JavaScript/TypeScript;
- Experiência em publicação de APPS Android e iOS;

**Diferenciais:**
- Conhecimento em metodologias de UX;
- Experiência com softwares de prototipagem (Ex: Figma, Adobe XD etc.);
- Portfólio de web design (web, mobile...);
- Experiência com frameworks de gráficos;
- Docker

## Benefícios

- Horário Flexível

## Como se candidatar

Por favor, envie seu currículo em anexo para fflorido@j2lrecruitment.com
**Enviar no assunto: Vaga SpryLife**

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
