### ISSUE TITLE
[Vila Olímpia/SP] Front End Developer na eWave do Brasil

### ISSUE THREAD

**Issue by roquimvanessa** [frontendbr/vagas#653]
## Descrição da vaga

Responsável pelo desenvolvimento Web, traduzindo protótipos em implementações JavaScript ES6 (React.js e SASS), CSS 3, HTML5 e JQuery.

Vivência em projetos ágeis (Kanban), biblioteca de manipulação de dados (underscore d3), .NET e Photoshop serão considerados como diferenciais.

## Local

Escritório, São Paulo - Vila Olímpia

## Benefícios

• Vale Transporte ou Vale Combustível;
• Vale Refeição ou Alimentação;
• Assistência Médica;
•  Seguro de Vida;
•  Assistência Odontológica (com co-participação);

#### Diferenciais

•  Horário Flexível; e
• Excelente ambiente de trabalho.

## Requisitos

**Obrigatórios:**
• Proficiência em HTML5 e CSS3;
• CSS pré-processado (SASS ou LESS);
• jQuery avançado;
• React."
- Javascript ES6

**Desejáveis:**
Conhecimento nas Tecnologias:
• Photoshop básico
• Bibliotecas para manipulação de dados será um diferencial (underscore, d3)"
• Conhecimento com Kanban

**Diferenciais:**
• Criatividade em resolução de problemas e de forma eficiente e colaborativa;
• Comprometimento;
• Ter necessidade em destinar mais atenção as soluções do que aos problemas; 
• Bom Humor; e
• Construir e inspirar confiança.

## Contratação

CLT Full

## Nossa empresa

Estamos apoiando o processo seletivode uma start up fornecedora de soluções para a gestão de cadeia de suprimentos e demanda. Este profissional irá trabalhar em conjunto com os times de Web e BI.

## Como se candidatar

Por favor envie um email para vanessa.roquim@ewave.com.br com pretensão salarial seu CV anexado - enviar no assunto: Vaga Front End PL

**Comment by LFeh** [comment]
Aberto ainda?
