### ISSUE TITLE
[Remoto] Sr. Front-end Developer na Rocket.Chat

### ISSUE THREAD

**Issue by NataliaVillain** [frontendbr/vagas#6530]
## Nossa empresa

Rocket.Chat é uma plataforma de comunicação open source, um dos maiores projetos open source do mundo com mais de 1000 desenvolvedores, e nossa equipe é 100% remota de mais de 26 países diferentes. Classificada entre as 100 empresas de tecnologia mais transparentes de 2021 pela The Org.

## Descrição da vaga

Frontend com React, JS e Type;
Equipe internacional;
Nível Sênior.

## Local

Remoto

## Requisitos

**Obrigatórios:**
React
JS 
Type
Inglês Avançado

**Diferenciais:**
- projetos opensource

## Benefícios

- Plano de Saúde/Odont.
- VR de R$ 28/dia 
- Gympass
- Stockoptions
- PLR
- Remote Benefit (R$ 200/mês)
- iTalki
- ...

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um email para natalia.villain@rocket.chat com seu CV anexado ou perfil de rede social. Ou entre em contato: https://www.linkedin.com/in/nataliavillain

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após cada processo.
E-mail para contato em caso de não haver resposta:  natalia.villain@rocket.chat 

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
