### ISSUE TITLE
[Remoto] Fullstack .NET Developer (Júnior) na Aqua Tecnologia

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6532]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/full-stack-developer-230632739?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>Aqua Tecnologia</strong> busca pessoa<strong> Fullstack .NET Developer (Júnior)</strong> para compor seu time!</p>
<p>A Aqua nasceu há 10 anos com o objetivo de transformar a experiência do usuário na interação com quiosques digitais. Hoje, a empresa é referência nacional no setor e está se expandindo para novos mercados. Faça parte da nossa equipe e trabalhe remotamente com pessoas amigáveis e receptivas em uma estrutura organizacional horizontalizada.&nbsp;</p>
<p>Showcase é um software de apresentação para quiosques digitais interativos. É composto por um módulo web (Studio) e um módulo desktop (Player). Showcase é usado por algumas das maiores empresas do Brasil para informar e promover produtos e serviços em locais públicos.</p>
<p>Showroom é uma versão web do mesmo conceito voltada para atendimento à distância.</p>
<p><strong>Sobre as atividades</strong></p>
<ul>
<li>O candidato participará do desenvolvimento de novas features e correção de bugs nas plataformas Showcase e Showroom da Aqua.</li>
</ul>

## Aqua Tecnologia: 
 <p>A Aqua desenvolve soluções interativas para atender melhor e vender mais. A empresa é especialista em equipamentos e aplicações touchscreen. Nosso principal foco é em grandes formatos. Usamos tecnologias inovadoras no dia a dia das pessoas. Levamos informações e serviços digitais a todos os lugares, a partir de soluções interativas prontas para uso.</p>
<p>Confira o que temos para eventos, marketing, lojas, autoatendimento. Atendemos a setores como varejo, imóveis, veículos, turismo, corporativo, entre outros.</p><a href='https://coodesh.com/empresas/aqua-tecnologia'>Veja mais no site</a>

 ## Habilidades: 
 - C# .NET Core 
- HTML5 / CSS3 
- Javascript 
- SQL 
- GIT 
- C#
## Local: 
 100% Remoto
## Requisitos: 
 - Conhecimentos em APIs RESTFull usando C# 
- Conhecimentos em frontend React.js 
- Conhecimentos em Entity Framework
## Diferenciais: 
 - Conhecimentos em AngularJS 
- Conhecimentos em Microsoft WPF 
- Conhecimentos em Microsoft LINQ 
- Conhecimentos em MaterialUI 
- Conhecimentos em Programação assíncrona (async/await) 
- Conhecimentos em Arquitetura CQRS 
- Conhecimentos em Arquitetura MVVM, TDD (test driven development) e Plataforma AWS
## Benefícios: 
 - Vale-alimentação 
- Plano de saúde 
- Horários flexíveis
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack .NET Developer (Júnior) na Aqua Tecnologia](https://coodesh.com/vagas/full-stack-developer-230632739?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Full-Stack

**Comment by srjheam** [comment]
Processo seletivo encerrado.
