### ISSUE TITLE
[Rio de Janeiro] Front-end Developer na SuperUber

### ISSUE THREAD

**Issue by Vamoss** [frontendbr/vagas#6535]
## SuperUber

Empresa referência nacional e internacional em projetos que combinam Arte e Novas Tecnologias.
São mais de 300 projetos pelo mundo, destacando-se projetos como Museu do Amanhã e Museu da Lingua Portuguesa.
A SuperUber é uma empresa que busca sempre inovar. Criando projetos que misturam Arte, Arquitetura, Design e Tecnologias para criar experiências.
Nosso portfolio tem uma diversidade ampla, destacam-se projetos imersivos, interativos e uso de projeção e interfaces tangíveis.

## Descrição da vaga

A vaga é para estágio, procuramos pessoas com disposição para aprender mais sobre desenvolvimento em geral.
São bem vindos perfis de pessoas interessadas em desenvolver em programação criativa.
Durante o período de estágio, queremos incentivar o domínio no desenvolvimento Web.
Posteriormente este conhecimento pode ser estendido para outras plataformas como Unity3D.

## Local

Estamos trabalhando de forma mista, alguns dias da semana são presenciais, e outros são remotos.
Nosso escritório fica na Rua Silvino Montenegro, 78, Gamboa, Rio de Janeiro.

## Requisitos

**Obrigatórios:**
- Conhecimentos básicos em Javascript, CSS, HTML e Github.

**Desejáveis:**
- Conhecimentos em ReactJS
- Conhecimentos em Wordpress

**Diferenciais:**
- Ter bom senso de organização.
- Ter bom senso de gestão de tempo e tarefas.
- Ter portfolio de projetos que misturam arte e tecnologia.
- Inglês básico.

**Diferenciais:**

- Temos em nosso laboratório equipamentos disponíveis para experimentação (Projetores, Oculos VRs, Playstation etc)

## Contratação

Contrato de Estágio e posteriormente PJ

## Como se candidatar

Por favor envie um email para carlos@superuber.com com seu CV anexado - enviar no assunto: Vaga Estágio Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

#### Alocação

- Alocado

#### Regime

- Estágio

#### Nível

- Júnior

**Comment by IsabelyDev** [comment]
tenho interesse

**Comment by Vamoss** [comment]
Boa, recebi seu curriculo. Vou entrar em contato assim que terminar de analisar todos os demais.

**Comment by ANDRERSANTOS** [comment]
Tenho interesse!

**Comment by EriickFraga** [comment]
Tenho interesse, acabei de enviar o meu currículo.
