### ISSUE TITLE
[Remoto] Fullstack Javascript Developer na Deep ESG

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6537]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/fullstack-javascript-developer-192858758?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>DeepESG</strong> está buscando <strong><ins>Fullstack Javascript Developer</ins></strong> para compor seu time!</p>
<p>Medir os impactos que importam hoje, para mudar o mundo amanhã: esse é o propósito da DEEP.&nbsp;&nbsp;</p>
<p>Acreditamos que as métricas de sustentabilidade são essenciais para mensurar a extensão do que o capital investido produz na sociedade.&nbsp;</p>
<p>Nosso compromisso é solucionar um dos maiores desafios da sustentabilidade: como calcular e reportar métricas de sustentabilidade de forma uniforme e em escala global.</p>
<p>Somos uma empresa de tecnologia jovem, movida pela busca da inovação, que respeita e valoriza os seus colaboradores, a diversidade e a ética.&nbsp;&nbsp;</p>
<p>No último ano crescemos acima da nossa meta de aquisição de clientes e precisamos que nosso time acompanhe esse crescimento.&nbsp;&nbsp;</p>
<p>Por isso, estamos atrás de novos Deepers que também queiram mudar o mundo com a gente. Vamos?</p>
<p></p>

## Deep ESG: 
 <p>Medir os impactos que importam hoje, para mudar o mundo amanhã: esse é o propósito da DEEP.&nbsp;&nbsp;</p>

<p>Acreditamos que as métricas de sustentabilidade são essenciais para mensurar a extensão do que o capital investido produz na sociedade.&nbsp;</p><a href='https://coodesh.com/empresas/deepesg'>Veja mais no site</a>

 ## Habilidades: 
 - HTML 5 
- CSS 3 
- Typescript 
- Node.js 
- NestJS 
- Vue.js
## Local: 
 100% Remoto
## Requisitos: 
 - Sólida experiência em Javascript Moderno, preferencialmente Vue ou conhecimento de Angular e/ou React 
- Conhecimento e habituado a atuar com Typescript 
- Conhecimento NestJS ou outro framework de backend em Node.js 
- Experiência com banco de dados relacionais (Postgres, preferencialmente) 
- Experiência com bibliotecas para criação de gráficos (D3.js, Google Charts, …) 
- Experiência com testes unitários e e2e 
-  Git e Gitflow
## Diferenciais: 
 - Conhecimento em arquitetura de software 
- Experiência com modelagem e consumo de API
## Benefícios: 
 - Flexibilidade de horários
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack Javascript Developer na Deep ESG](https://coodesh.com/vagas/fullstack-javascript-developer-192858758?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
