### ISSUE TITLE
[Florianópolis-SC] Front-end Developer  (Angular 4)  na [CoolCoffee]

### ISSUE THREAD

**Issue by ferlintec** [frontendbr/vagas#654]
## Descrição da vaga

A demanda é para assumir o desenvolvimento do front-end de um projeto em andamento.
Projeto usa MEAN stack: Mongoose.js 4.x (MongoDB): database Express.js 4.x, Angular 4.x, Node.js 6+.
Após conclusão desta etapa do projeto, há grande possibilidade de continuidade neste e em outros projetos.

## Local

Trabalho remoto total. Preferência por profissionais da Grande Florianópolis.

#### Diferenciais

- Trabalho remoto total

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com front-end
- Domínio de Angular

**Desejáveis:**
- Angular 4.x
- Node.js
- MongoDB

## Contratação

PJ a combinar

## Nossa empresa

A CoolCoffee é uma empresa foca no desenvolvimento de solução para terceiros, buscando sempre trazer tecnologias de ponta, dando grande autonomia para os desenvolvedores. 

## Como se candidatar

Por favor envie um email para contato@coolcoffee.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

Labels:
Remoto total, PJ, Pleno, Sênior

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
