### ISSUE TITLE
[Remoto] Full Stack Developer na KIS Solutions

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6540]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/full-stack-developer-015100834?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>KIS Solutions</strong> busca pessoa<strong> FullStack Develope</strong>r para compor seu time!</p>
<p>A KIS Solutions é uma consultoria de tecnologia que oferece soluções de alta qualidade para empresas e startups no Brasil e nos Estados Unidos (temos escritórios nos dois países).</p>
<p>Na KIS você fará parte de uma equipe internacional muito talentosa que está em constante crescimento.</p>
<p>Se você tem paixão em solucionar problemas com tecnologia para levá-la a outro patamar, a KIS é o lugar certo para você.</p>
<p><strong>A pessoa contratada terá responsabilidades como:</strong></p>
<ul>
<li>Consiga construir, montar a estrutura, testar, documentar e fazer a manutenção dos códigos;</li>
<li>Garanta a maior performance, qualidade e responsividade do software;</li>
<li>Identifique bugs proativamente e trabalhe na solução deles;</li>
<li>Faça o design e a manutenção de uma infraestrutura em cloud (Azure, AWS, etc);</li>
</ul>
<p></p>

## KIS Solutions: 
 <p>Somos uma consultoria global, nascida e consolidada nos Estados Unidos e que, recentemente, passou a atender pequenas e grandes empresas no Brasil e na América Latina.</p>

<p>Entregamos projetos para empresas Fortune 500 e desenvolvemos startups desde suas concepções até operações em larga escala.</p><a href='https://coodesh.com/empresas/kis-solutions'>Veja mais no site</a>

 ## Habilidades: 
 - Java 
- Angular 2+ 
- Angular 8 
- MySQL 
- Spring Boot 
- Inglês 
- GitHub
## Local: 
 100% Remoto
## Requisitos: 
 - Inglês intermediário (para conseguir participar de reuniões com nossos clientes americanos também); 
- Sólida experiência na área de desenvolvimento, com experiência em Java Spring Boot e Angular 2+; 
- Domínio de desenvolvimento WEB Full Stack; 
- Controle de versionamento usando o Git; 
- Experiência de envolvimento com desenvolvimento e lançamento de um projeto web em produção.
## Diferenciais: 
 - Trabalhar com uma mentalidade de DevOps; 
- Conhecimento de metodologias ágeis: Scrum; 
- Experiência de trabalho com Jira.
## Benefícios: 
 - Horários Flexíveis
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Full Stack Developer na KIS Solutions](https://coodesh.com/vagas/full-stack-developer-015100834?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
