### ISSUE TITLE
[Liberdade/São Paulo] Front-End Developer na Athos Informática

### ISSUE THREAD

**Issue by AthosRH** [frontendbr/vagas#655]
**Descrição da vaga:**
Profissional com sólidos conhecimentos em desenvolvimento Front-end utilizando JavaScript e frameworks como Vue.js e React.js para desenvolvimento de aplicações.
Conhecimentos em Photoshop UI/UX serão considerados como diferenciais.

**Local**
Rua Tamandaré, 796 - Liberdade - São Paulo - SP

 **Benefícios**
- Plano de saúde
- Seguro de vida em grupo
- VR 
- VT

**Requisitos**

**Obrigatórios:**
Conhecimentos avançados HTML5 e CSS3;
Conhecimentos de pré-processado CSS (SASS, LESS, STYLUS);
Conhecimentos em framework SPA: Vue.js e/ou React.js
Conhecimentos de consumo APIS RESTful;
Versionamento de código TFS e GIT.

**Desejáveis:**
Photoshop 
Conhecimento em UX/UI
C#

 **Contratação**
CLT

**Nossa empresa**
Somos uma empresa inovadora e líder em aplicações para o mercado condominial.

 **Como se candidatar**
Por favor envie um e-mail para rh@athos.com.br  com seu CV anexado e pretensão salarial - enviar no assunto: Vaga Front-End

**Comment by LFeh** [comment]
Aberto ainda?
