### ISSUE TITLE
[REMOTO] Front-end Developer Pleno - VUEJS @RELEVO

### ISSUE THREAD

**Issue by RelevoLab** [frontendbr/vagas#6555]
## Descrição da vaga

Como Desenvolvedor Web, você irá atuar no nosso time de desenvolvimento que atende a um cliente de grande porte, desenvolvendo projetos, melhoria e atualizações em sistemas.

## Local

Vaga 100% Remoto

## Benefícios
**CLT**
- Plano de saúde
- Plano Odontológico
- VR/VA
- Auxilio Home Office
- Vale Cultura
- Seguro de vida
- Auxílio creche
- Bônus por performance.

**PJ**
- Ferias Remunerada após 12 meses de contrato
- Auxilio Home Office
- Bônus por performance.

## Requisitos

**Obrigatórios:**
•	Conhecimento e/ou experiência com VueJS, JavaScript, Bootstrap e comunicação com WEB API’s REST;
•	Conhecimento em HTML, CSS, Bootstrap e responsividade de layout;
•	Conhecimento Metodologia Agile, Scrum.

**Desejáveis:**
•	Conhecimento em Azure Devops;

## Contratação

PJ ou CLT a combinar.

## Nossa empresa

Somos uma empresa de tecnologia com mais de 5 anos de atuação, vivemos e respiramos tecnologia, batalhamos incansavelmente para ser um lugar incrível para se trabalhar, onde as pessoas são tratadas com igualdade, gostem de trabalhar, se sintam em casa e esse é certamente o lugar onde queremos estar.
Estamos à procura de pessoas do bem, esforçadas e que queiram crescer junto com a gente!
Se você se enquadra neste perfil, é você que queremos!

**SUPER IMPORTANTE:**
Se os seus conhecimentos forem aderentes à vaga, é tudo o que importa.
Aqui nós abraçamos a diversidade e contratamos pessoas com capacidade e vontade de transformar, independente de qual seja a sua localização, idade, raça, cor, religião, identidade de gênero, orientação sexual ou formação.
Seu perfil e valores casam com os nossos? Então venha fazer parte!

## Como se candidatar

Acesse nova Página de Carreiras pelo endereço:

https://jobs.kenoby.com/relevolab

#### Alocação
- Remoto

#### Experiência
- Pleno
- Sênior

#### Regime
- CLT
- PJ

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
