### ISSUE TITLE
[Remoto] Front-end Developer na REVELO NETWORK

### ISSUE THREAD

**Issue by gludtke-recruiter** [frontendbr/vagas#6557]
## Nossa empresa

Empresa localizada em Nova Iorque/EUA, cujo objetivo é aumentar a produção de conhecimento da humanidade. É um delineador de código aberto que funciona em cima de Markdown de texto simples.

## Descrição da vaga

Parceiro Recrutador da Revelo Network anuncia vaga para Engenheiro de Front-End Pleno.

## Local

100% REMOTO - Sede da Empresa em New York (USA)

## Requisitos

**Obrigatórios:**
- Inglês avançado (verbal e escrito);
- +4 anos de React;
- Experiencia com produto design;
- UX/IX usando Figma

## Contratação

PJ a combinar

## Como se candidatar

Por favor, se inscreva no Linkedin no Link > https://www.linkedin.com/jobs/view/2938156422

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: recrutamentohunter13@gmail.com

#### Nível

- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
