### ISSUE TITLE
[Remoto] CTO - Front-end Developer na Adaflow

### ISSUE THREAD

**Issue by amanda-orteega** [frontendbr/vagas#6558]
Olá pessoal 😃

Sou a Amanda, CEO e Fundadora da Adaflow e estou a procura de um CTO e sócio fundador.

## Sobre a empresa e o desafio 📈
Nós estamos construindo uma plataforma SaaS que automatiza os processos de contabilidade para profissionais de tecnologia que trabalham como PJ dentro do Brasil ou para startups do exterior. 

Na prática, estamos automatizando emissões de notas fiscais, pagamentos de impostos e toda a burocracia que o seu contador provavelmente faz na mão, um a um. Esse trabalho gera muito erro humano que siginifica basicamente impostos, multas e muita dor de cabeça.

Deixamos para o nosso time de contadores apenas o que são atividades essenciais da contabilidade permitindo que eles foquem onde realmente importa e tenham a tecnologia da nossa plataforma como aliado.

## Tecnologias 🧠
- Ruby on Rails 7 (Minitest, Stimulus.js, Hotwire)
- Sidekiq / Redis
- Tailwind CSS
- Heroku

## Remuneração 💸
Sabemos que a remuneração de um Engenherio de Software Senior está entre R$ 20.000,00 ($4k USD) - R$ 40.000,00 (8k USD). 

Todo mundo tem que ser remunerado adequadamente, isso é fato. Estamos nessa para ganhar dinheiro e viver bem, sem demagogia.

Para isso, montamos uma proposta alinhada ao nosso crescimento.

Fase 1) R$ 5.000,00, inicialmente. Temos 50 usuários.
Fase 2) R$ 10.000,00 (300+ usuários)
Fase 3) R$ 15.000,00 (500+ usuários)
Fase 4) R$ 20.000,00 (1000+ usuários)
Fase 5) R$ 30.000,00 (5000+ usuários)

Participação entre 5-10% em stock options na empresa.

Essa é uma posição PJ.

## Como aplicar ✍️
https://www.linkedin.com/jobs/view/2953068616/

## Help e Muito obrigado ❤️
Se a vaga não for para você e conhecer alguém, fico feliz pela indicação. 

Como agradecimento, me coloco a disposição para ajudar a comunidade oferecendo  consultoria gratuita sobre contabilidade para o trabalho remoto como PJ.

Se você estiver descontente com a sua contabilidade atual ou perdido sobre como abrir a sua empresa, pode me chamar por DM que a gente resolve pra você. 😉

WhatsApp: https://bit.ly/3HCP04y
Telegram: https://t.me/amandaorteega
Site: https://Adaflow.com.br

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
