### ISSUE TITLE
[São Paulo (Vila Mariana)] Frontend Developer na Intelipost

### ISSUE THREAD

**Issue by lucastex** [frontendbr/vagas#656]
## Descrição da vaga

Procuramos um (ou uma) Senior Frontend Developer para integrar nosso time!

## Local

Estamos em São Paulo! Nosso escritório fica na Vila Mariana, na [Rua Dr. Amâncio de carvalho, 182](https://www.google.com.br/maps/place/Intelipost/@-23.5830751,-46.6510927,17z/data=!3m1!4b1!4m5!3m4!1s0x94ce5a2449e388d1:0x50ac48563220899c!8m2!3d-23.58308!4d-46.648904).

## Benefícios

- Remuneração competitiva + Bônus
- Assistência Médica: Amil Saúde (One Health)
- Assistência Odontológica: Metlife
- Seguro de Vida: Itaú Seguro
- Aulas de Inglês
- VT ou 50% do valor para estacionamento
- VR: 22,00 dia

## Responsabilidades:

- Inovar trazendo tecnologias recentes e de mercado para a equipe
- Desenhar a arquitetura dos novos projetos de frontend jutamente com o restante da equipe de backend
- Desenvolver a lógica de frontend de aplicações web, definindo e customizando as interfaces de backend
- Implementação técnica do design do produto
- Intensa colaboração com a equipe do produto para garantir que tudo está sendo implementado de acordo com o especificado
- Criar e codificar testes automatizados
- Análise de possíveis fontes de erros e sempre corrigir os bugs de forma eficientes

## Requisitos

- Experiência significativa com  Node.JS, AgularJS, HTML5, CSS3/SASS
- Estar antenado e ligado em outros frameworks como React, Vue, Ember, MIthril, etc
- Trabalhar com gerenciadores de tasks como Gulp, Grunt
- Conhecer e estar disposto a aplicar novos conceitos como PWA, AMP, SWs e etc
- Experiência significativa com aplicações web modernas e APIs REST (json), ferramentas de testes - como Jasmine, JS Mock e outras
- Experiência significativa com GIT/SVN + Métodos ágeis como Kanban ou Scrum
- Estar alinhado com conceitos de aplicações responsivas, mobile first e pixel perfect concepts

## Contratação

CLT

## Nossa empresa

A Intelipost é uma startup de tecnologia que está revolucionando a logística no Brasil, um mercado de R$ 300B por ano com muitas ineficiências e desafios. Temos um sistema inovador que gerencia a logística para empresas do e-commerce. Já recebemos R$11 milhões de investimento até o momento, e em pouquissimo tempo já estamos colhendo grandes resultados: Em 2016 fomos selecionados como uma empresa Promessas Endeavor, também ganhamos a competição [IBM Smartcamp](https://www.ibm.com/blogs/robertoa/2016/11/intelipost-e-nazar-vencem-o-ibm-smartcamp-brasil-2016/)  com foco de Big Data e data analysis, o que nos rendeu a [realização de um Hackathon sobre Blockchain junto a IBM](https://www.ibm.com/blogs/robertoa/2017/09/intelipost-e-ibm-realizam-o-primeiro-hackathon-de-blockchain-em-startup-do-brasil/) e em 2017 fomos selecionados pela Oracle para sermos acelerados por eles no programa Oracle Startup Cloud Accelerator.

## Como se candidatar

Enviar um e-mail para lucas.teixeira@intelipost.com.br para marcarmos de conversar por telefone ou presencialmente. Um passo do processo será resolver nosso deste repositório: https://github.com/intelipost/job-frontend-developer. Mas se quiser fazer o teste antes de entrar em contato, sem problemas.

**Comment by lucastex** [comment]
@LFeh Poderia por favor adicionar o label `CLT` ?

**Comment by lucastex** [comment]
Oi pessoal! Continuamos em busca para esta oportunidade!

**Comment by ygorlazaro** [comment]
Bom dia @lucastex , você aceitaria uma proposta para PJ remoto?

**Comment by lucastex** [comment]
Oi @ygorlazaro  tudo bem?

Muito obrigado pelo contato sobre a vaga! Infelizmente neste momento a necessidade é presencial, pois será uma pessoa importante no processo que temos hoje, será uma referência para os outros frontends. Futuramente para outras posições no time, estudaremos a possibilidade de remoto.

Seria a única alternativa para você?

**Comment by ygorlazaro** [comment]
@lucastex infelizmente sim, eu não tenho possibilidade de ir para São Paulo no momento. Sou do RJ. Mas agradeço o feedback!

**Comment by lucastex** [comment]
Valeu @ygorlazaro ! Se tiver alguém para indicar, fique a vontade!

Obrigado!

**Comment by lucastex** [comment]
Oi pessoal, fizemos a contratação e a vaga está fechada.

Obrigado pela ajuda!
