### ISSUE TITLE
[Remoto] Frontend Developer na ilove.me

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6565]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/developer-frontend-qa-195343733?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>ilove.me</strong> busca pessoa<strong> Frontend Developer (Suporte de QA) </strong>para compor seu time!</p>
<p>ilove.me é uma plataforma one-stop-shop para o setor de Beleza, Estética e Bem-Estar com ERP completo e de fácil utilização, ferramentas de marketing e pagamentos integrados.</p>
<p>Atualmente, estamos trabalhando para adicionar um grande conjunto de novas funcionalidades ao nosso app. O nosso objetivo é permitir que o utilizador possa gerir todo o seu negócio a partir do seu smartphone (ex: checkouts, pagamentos, colaboradores, ...) e para isso precisamos da sua ajuda!</p>

## ilove.me: 
 <p>ilove.me é uma plataforma one-stop-shop para o setor de Beleza, Estética e Bem-Estar com ERP completo e de fácil utilização, ferramentas de marketing e pagamentos integrados.</p>
<p>Ajudamos centenas de clientes a gerir as suas operações e a aumentar o seu faturamento, processando +100.000 agendamentos e +R$4.000.000 por mês</p><a href='https://coodesh.com/empresas/iloveme'>Veja mais no site</a>

 ## Habilidades: 
 - Automação de Testes 
- Javascript 
- Ember.js 
- Vue.js 
- React.js 
- Unit Tests 
- GIT 
- REST APIs
## Local: 
 100% Remoto
## Requisitos: 
 - Automação de Testes 
- Experiência com JavaScript 
- Conhecimentos bases em frameworks javascript como: Ember.js, Vue.js ou React.js 
- Conhecimento em testes unitários e/ou end-to-end 
- Experiência com GIT
## Diferenciais: 
 - Experiência em Cypress 
- Experiência em desenvolvimento de API RESTful 
- Experiência com metodologia ágil, trabalho em sprints e times organizados em squads 
- Conhecimento de boas práticas de qualidade como TDD 
- Estar habituada à cultura de code review 
- Vivência com CD (Entrega contínua) 
- Conhecimento de bancos de dados relacionais e tecnologias SQL (MySQL)

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Developer na ilove.me](https://coodesh.com/vagas/developer-frontend-qa-195343733?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
