### ISSUE TITLE
[REMOTO] Front-end Developer - ANGULAR 12 Sênior na Hoop Global

### ISSUE THREAD

**Issue by jadebf** [frontendbr/vagas#6569]
> Vaga Full Remota 

## Hoop Global
Aqui somos a maior aplicação do segmento nos mercados em que atuamos: Brasil, México, Estados Unidos e Canadá. Nosso ambiente é 100% colaborativo e incentivamos o desenvolvimento profissional de nossos colegas. A Staff tem 9 pessoas e usamos metodologias ágeis para facilitar nossas entregas.

## Descrição da vaga

Desenvolvimento de novas features, otimizações e melhorias do produto core da empresa, operante no mercado americano. 

## Local
Vaga remota, com ambiente internacional. Somos uma multinacional brasileira.
## Requisitos

**Obrigatórios:**
- 4 anos de experiência com Angular
- Trabalhar com gerenciadores de estado, preferencialmente NgRx. 
- Inglês técnico 

**Desejáveis:**
- conhecimentos em HTML, CSS, TypeScript
- conhecimentos em testes automatizados com JEST ou Jasmine

**Diferenciais:**
- projetos opensource
- Já ter atuado em StartUps produtizadas
- Inglês para conversação

## Benefícios

- Plano de saúde e odontológico Unimed
- VR de R$ 24,10/dia CAJU
- Auxílio creche R$ 371
- Convênio Creditas
- Auxílio Home Office
- Equipamento para trabalho
- Day off no aniversário
- Hackathons 
- Ambiente colaborativo

## Contratação
Depende da preferência da pessoa:
PJ a combinar podendo chegar até R$15 mil.
CLT + beneficios a partir de R$10.000,00

## Como se candidatar

Por favor envie um email para jade@hoop.global com seu CV anexado - enviar no assunto: Vaga Angular Sênior

## Tempo médio de feedbacks: 2 dias

Costumamos enviar feedbacks em até 02 dias após cada processo.
E-mail para contato em caso de não haver resposta: jade@hoop.global

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by jadebf** [comment]
Oi pessoal! Essa vaga ainda está aberta e aceitando candidaturas.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
