### ISSUE TITLE
[Remoto] Fullstack Ruby + VueJs Developer (Freelancer - 30H) na SeuPC

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6570]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/fullstack-ruby-on-rails-vue-035618342?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong> SeuPC</strong> busca pessoa<strong> Fullstack Ruby + VueJs Developer </strong>para seu time!</p>
<p>Aqui na seupc.com estamos desenvolvendo um sistema que permite que o usuário que precisa encontrar o notebook ideal, encontre através de filtros como curso universitário, jogos e softwares específicos.</p>
<p>O projeto está em fase de lançamento e precisamos de uma pessoa que desenvolva algumas funcionalidades, resolva bugs, e possivelmente continue pós lançamento. Para esse momento, expectativa de 30h de execução, PJ e Part time.</p>
<p></p>

## SeuPC: 
 <p>O usuário nos fala como pretende usar o notebook, seja para o curso de faculdae, jogos, softwares específicos e recomendamos o notebook mais adequado para suas necessidades junto com os melhores preços online.&nbsp;</p>
</p>

 ## Habilidades: 
 - Ruby on Rails 
- Vue.js 
- PostgreSQL
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência em Rub on Rails 
- Experiência em Vue.js
## Diferenciais: 
 - Python 
- AWS

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack Ruby + VueJs Developer (Freelancer - 30H) na SeuPC](https://coodesh.com/vagas/fullstack-ruby-on-rails-vue-035618342?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
