### ISSUE TITLE
[Remoto & Com códigos no grau] Senior React Native Developer | Builders

### ISSUE THREAD

**Issue by RaissaBaltazar** [frontendbr/vagas#6571]
Papo reto: aqui na Builders você irá se deparar com uma cultura voltada ao empreendedorismo. Os projetos, as pessoas e seu dia a dia serão norteados pela vontade de fazer acontecer. Suas ideias não serão descartadas, você poderá liderar pessoas incríveis e ser agente de transformação, além de vivenciar uma estrutura de frontend idealizada apenas aqui na Builders. 👀 **E aí, bora ser Builder?**

**Tecnologias que se você dominar, vão gerar valor nos projetos 💻:**
- Fluência em TypeScript;
- React (Redux/Mobx);
- APIs REST;
- Trabalhar com diferentes dimensões de dispositivo (tablet, celular, etc)
- Conhecimento geral do ambiente móvel;
- Versionamento de código com Git;
- Conhecimento em arquitetura de software;
- Metodologias ágeis.

**Como Builder, você terá acesso a:**
- Oportunidades reais de empreender e impactar;
- Fazer parte de uma comunidade de empreendedores;
- Inovação e criação liberados;
- Participar de um processo único de geração de valor;
- Contribuir na criação de métodos disruptivos;
- Colocar suas ideias no mercado, na prática! :)
- Possibilidade de Profit share em novos Negócios;

Junte-se ao movimento: https://jobs.kenoby.com/sejabuilder/job/senior-react-native-developer-cod-579-remoto/61c5d7914438b24692881c20?utm_source=website

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
