### ISSUE TITLE
[Remote] Senior Software Engineer Front-End @Nomah by Loft

### ISSUE THREAD

**Issue by MartinaCarvalho** [frontendbr/vagas#6573]
## Nossa empresa

NOMAH oferece apartamentos residenciais para quem precisa de flexibilidade, praticidade e conforto na experiência. Um lugar pra ficar ou morar, seja por 1 dia ou pelo tempo que precisar. Queremos revolucionar a gestão de ativos imobiliários por meio da tecnologia, transformando espaços e oferecendo consistentes experiências de conforto e praticidade em estadias e moradias flexíveis.

## Descrição da vaga

Como Senior Software Engineer você será responsável por criar e manter serviços e soluções robustas e escaláveis que irão dar suporte à questões Core da Nomah, e aos demais times de engenharia da companhia.
 
**Principais atividades**

- Participar ativamente das discussões e decisões táticas e operacionais de produto e/ou design;
- Apoiar na construção do playbook de referências de arquitetura e boas práticas de engenharia;
- Participar ativamente das discussões e definições de arquitetura dos produtos e/ou serviços do seu time/squad;
- Projetar e desenvolver produtos e/ou serviços seguindo as referências de arquitetura e boas práticas de engenharia, garantindo um alto nível de qualidade, performance e segurança;
- Apoiar e orientar tecnicamente as outras pessoas desenvolvedoras;
- Contribuir ativamente para reduzir a complexidade e as dependências no processo de delivery e sustentação;
- Criar documentações técnicas e garantir observabilidade dos produtos e/ou serviços do seu time;
- Atuar no suporte/operação/resolução de incidentes e problemas dos produtos e/ou serviços;
- Participar do processo de contratação de pessoas.

## Local

Remoto

## Requisitos

**Obrigatórios:**

- Qualidade: Se esforça para reduzir a complexidade. Estabelece padrões. E ajuda o time a evoluir por meio de revisões de código;
- Design e Arquitetura: Muitas vezes assume a responsabilidade de conduzir revisões de documentos de design para o time;
- Comunicação e Influência: Capaz de equilibrar as necessidades de negócio e os requisitos do time, influenciando e orientando seus colegas;
- Planejamento e Processos: Ajuda o time a evoluir por meio de revisões de código e melhoria de processos. Participa no processo de recrutamento, entrevistas e orientação;
- Queremos pessoas que entendem, respeitam e valorizam as diferenças;
- Queremos pessoas que atuam de forma colaborativa, perseguindo o resultado do todo;
- Queremos pessoas que buscam a excelência, atuando com disciplina, compromisso e agilidade;
- Queremos pessoas proativas e adeptas a mudança, atuando com senso de urgência, propriedade e responsabilidade;
- Queremos pessoas que buscam ser autônomas, eliminando ou otimizando quaisquer dependências;
- Formação em Ciência da Computação ou Análise de Sistemas;
- Sólido conhecimento em JavaScript, React, Node.js;
- Design System, Design Pattern;
- Notação big-O para análise de complexidade de tempo e espaço;
- Testes automatizados;
- Jest, Jasmine, JUnit, Pytest, TestProject, Selenium, Cypress;
- Arquitetura de software: camadas, microsserviços;
- Banco de dados relacional, não relacional. Diferencial: data warehouse, data lake;
- Observabilidade: logs, traces e métricas;
- Soluções em nuvem;
- Scrum, Kanban.

**Desejáveis:**

- Conhecimento em .Net, Java, Go, Python

**Diferenciais:**
- Buscamos pessoas que queiram contribuir com a construção da nossa cultura e que estejam dispostas a encarar novos desafios e aprender: você! Acreditamos na diversidade de talentos com diferentes histórias, formações, experiências e habilidades.

## Benefícios

Já imaginou decidir o quanto do seu benefício você vai gastar em alimentação, gasolina, farmácia e muitas outras categorias? Na Nomah isso é totalmente possível. Somos gente de verdade e sabemos que cada pessoa tem gostos e necessidades diferentes, por isso oferecemos benefícios flexíveis. Com eles, você escolhe onde investir seu dinheiro! Alguns dos nossos benefícios:

Benefícios

- Vale Refeição/Alimentação;
- Plano de Saúde - com subsídio para dependente;
- Plano Odontológico;
- Seguro de vida;
- Subsidiamos uma parceria com o Zenklub, uma plataforma de psicólogos e coaches online, para focarmos no bem estar e saúde mental;
- Gympass com ótimo subsídio para manter mente e corpo são;
- Auxílio home-office;
- Auxílio mobilidade - de acordo com a utilização;
- Auxílio educação;
- Auxílio creche - para crianças de até 60 meses;
- Licença maternidade e paternidade estendidos;
- Birthday Off - você ganha o dia do seu aniversário para aproveitar como quiser;
- Flexibilidade de horários;
- Short friday mensal: em uma sexta do mês trabalhamos por meio período.

## Contratação

CLT

## Como se candidatar

Por favor cadastre-se em https://bit.ly/NomahSRFrontEnd

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 8 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by MartinaCarvalho** [comment]
Aberta

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
