### ISSUE TITLE
[Remoto] Engenheiro ReactJS - Pleno/Sênior (Vaga Internacional)

### ISSUE THREAD

**Issue by TacianySouza** [frontendbr/vagas#6574]
Requisitos:
● Inglês avançado (verbal e escrito)
● Javascript, TypeScript, HTML, CSS
● +2 anos em ReactJS
● Conhecimento de tecnologias como GraphQL, Next.js
● Proficiência na implementação de designs da Web responsivos e na escrita de testes de unidade e integração de FE

Desejáveis:
● Vercel

Sobre a empresa:
Empresa de São Francisco na Califórnia, o objetivo é fornecer a plataforma líder para a observabilidade da primeira milha. Fundada por criadores e mantenedores do Fluentd e Fluent Bit, o objetivo é permitir que organizações de todos os tipos e tamanhos obtenham o máximo de insights e valor de seus pipelines de dados.

Candidatura: https://forms.gle/vYdFL7fhMVujyPS16

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
