### ISSUE TITLE
[REMOTO] Front-end Developer Reactjs - Middle Level na HOOP GLOGAL

### ISSUE THREAD

**Issue by jadebf** [frontendbr/vagas#6575]
#### Alocação
- Alocado em cliente terceiro
- Remoto

#### Regime
- PJ tradicional

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
