### ISSUE TITLE
[Remoto] Desenvolvedor Sênior  Wordpress e React (Vaga Internacional)

### ISSUE THREAD

**Issue by TacianySouza** [frontendbr/vagas#6576]
Requisitos:
● Inglês Fluente - Escrito e oral.
● 3+ anos de experiência em desenvolvimento front-end
● 2+ anos de experiência em desenvolvimento WordPress
● 1+ anos de experiência usando React
● Experiência de trabalho em produtos de consumo de alto tráfego
● Experiência com HTML5, CSS3, JavaScript, PHP e outras tecnologias usadas para web e mobile
● Experiência de trabalho em um ambiente ágil

Sobre a empresa:
Nosso cliente é uma empresa líder em empréstimos de dinheiro para estudantes em São Francisco, Califórnia. Fundado em 2013.

Diferencial:
- Conhecimento e experiência em AWS

Responsabilidades:
Definir padrões de codificação, compartilhe as melhores práticas e implemente processos de desenvolvimento eficazes em torno do desenvolvimento do Wordpress.
Mentorear  membros da equipe júnior.
Reunir requisitos de negócios, criar roteiro técnico e entregar projetos no prazo.
Criar sites WordPress totalmente funcionais, incluindo experiências compatíveis com dispositivos móveis.
Modificar sistemas existentes e sugerir novas tecnologias.
Criar critérios de teste e participe de testes de sistemas quando necessário.

Candidatura: https://forms.gle/J8oy9k1SkiLnHpKUA

**Comment by mrangel-jr** [comment]
@felipefialho , A tag tá "Júnior" mas o titulo da vaga está "Sênior"

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
