### ISSUE TITLE
[São Paulo / Remoto] Front-end Developer Pleno na Take 5

### ISSUE THREAD

**Issue by alexpvieira** [frontendbr/vagas#6577]
## A Empresa

Take 5 LMS (www.take5.com.br), uma empresa de comunicação corporativa com base no Brasil e nos EUA.

## Descrição da vaga

Exemplo: Projeto bazinga em NodeJS, etc.

## Local

Exemplo: Hibrido (não temos previsão / intenção de retorno ao escritório), São Paulo, São Paulo, Berrini (ao lado da estação CPTM Berrini)

## Requisitos

**Obrigatórios:**
- Pelo menos 3 anos com desenvolvimento de aplicações frontend + experiência com SPAs (preferencialmente Vue)
- Experiência com CSS Extension Languages (Stylus, SASS, LESS), JavaScript (ES6/ES7) e bundlers (webpack)
- Controle de versão (GIT)

**Desejáveis:**
- Noções de AWS / Firebase / Analytics
- Conhecimentos em desenvolvimento de aplicativos hibridos (Cordova / Capacitor)

## Benefícios

- Modelo híbrido de trabalho
- Excelente clima organizacional
- Empresa em franca expansão, com oportunidades de crescimento
- Remuneração atrativa
- VT, VR
- Plano de Saúde
- Ajuda de custo para atuação home-office (auxílio internet, itens de mobiliário)

## Contratação

CLT

## Como se candidatar

Enviar CV para alex.vieira@take5.com.br .

## Tempo médio de feedbacks

Todos os CVs recebidos por email serão analisados e respondidos em até 1 dia útil.

#### Alocação
- Remoto (pessoa deve residir em São Paulo)

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
