### ISSUE TITLE
[REMOTO] React.js Front-end Developer na CIBERNIX

### ISSUE THREAD

**Issue by alvarogomes** [frontendbr/vagas#6578]
VAGA

Precisamos de 2 Desenvolvedores react para manutenção em aplicação react, class components.
 Frameworks: Next.js, Chakra, Redux ou Redux-toolkit, axios.

 inicio imediato
 com possibilidade de integrar o time para mais projetos.
 Enviar github e disponibilidade.

Contratação
PJ = 4K

Nível 
Pleno ou Senior

E-mail para se candidatar: alvaro.brito@cibernix.com

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
