### ISSUE TITLE
[Remoto] Front-end Developer na Quaent

### ISSUE THREAD

**Issue by Jmenottiquaent** [frontendbr/vagas#6579]
## Nossa empresa

Saas para sistema da qualidade na área da saúde.

## Descrição da vaga

Freelancer Front-end em Angular.

15 a 20h/semana, home office e em qualquer dia/horário da semana, totalizando umas 60-80 horas/mês contínuo.

## Local

Remoto.

## Requisitos

**Obrigatórios:**
- 4 anos de experiência em dev.
- conhecimentos em Angular.

## Benefícios

- Renda extra ao seu trabalho atual.
- 20/horas por semana, no dia e horário que quiser.
- trabalho contínuo (+- 80 horas mensais)

## Contratação

PJ/MEI (precisa emitir NF)
Valor/hora: R$ 60,00

## Como se candidatar

Por favor envie um email jmenotti@quaent.com.br com seu CV anexado 
- enviar no assunto: Vaga Front
- enviar seu numero whats
- fornecer seu perfil do linkedin.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
