### ISSUE TITLE
[Salvador] React Native Developer na Convergence Works

### ISSUE THREAD

**Issue by diegocosta** [frontendbr/vagas#658]
Você gosta de programação e de desenvolvimento de software?  Gosta de novas tecnologias e de desafios? Tem espírito de equipe e é comprometido? Você gostaria de colocar tudo isto em prática numa empresa?

**A Convergence Works** 
Somos a Convergence Works, somos a convergência entre os desafios das empresas e as ideias pra vencê-los. Desenvolvemos plataformas para o mundo digital, com foco em comunicação. Somos especialistas na criação de sites e aplicativos para plataformas de comunicação. Integramos sistema de gestão de conteúdo, aplicativo, disparo de email, solução para clube de assinantes, implantação de editoriais em múltiplas plataformas. 

**Local**
Rua Rubens Guelli, 134 - Sala 309 - Itaigara, Salvador – BA

**Conhecimentos necessários:**
- Conhecimento avançado em Javascript 
- Conhecimento intermediário em React Native 

**Desejáveis:**
Conhecimento em Android, Objective-C, HTML e alguma experiência com backend web (PHP preferencialmente). 

**Benefícios**
- Vale transporte
- Vale refeição
- Plano de Saúde
- Excelente ambiente de trabalho 
- Oportunidades de crescimento 
 
**Contratação**
CLT
Informe a sua pretensão salarial

**Essa vaga é pra você ? Venha fazer parte do nosso time!!!**
Envie seu currículo para vagas@convergenceworks.com.br com seu CV anexado e pretensão salarial,  enviar no assunto: Vaga Analista Desenvolvedor Mobile

**Comment by ribeiroevandro** [comment]
Home office não rola, rola?

**Comment by diegocosta** [comment]
@ribeiroevandro Infelizmente não.

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by diegocosta** [comment]
@LFeh Vaga fechada.
