### ISSUE TITLE
[SÃO PAULO] Desenvolvedor Fullstack Sênior na Sioux

### ISSUE THREAD

**Issue by philippecapouillez** [frontendbr/vagas#6581]
## Nossa empresa

Sioux - somos uma agência consultiva. Entendemos desafios, criamos e implementamos estratégias sob medida que geram resultados de negócio para nossos clientes promovendo experiências digitais relevantes para as pessoas.

## Descrição da vaga

Procuramos um fera com sólidos conhecimento em Java, Springboot, Angular e microserviços que nos ajude a levar inovação e tecnologia para nosso cliente do ramo financeiro.

## Local

Hibrido: 2 Escritório [SP], [SÃO PAULO], [ZONA SUL]

## Requisitos

**Obrigatórios:**
- Experiência sólida em Java 7, Java 8, Microserviços, Framework, Spring boot, banco de dados relacional e não relacional
- Conhecimentos sólidos em Angular 7 e 8, Front-end (HTML5, CSS3, Javascript, XML, Javascript)
- Experiência com ferramentas de versionamento de código: Git com Git flow, Maven ou Gradle; Metodologia ágeis: Scrum, Jira; Testes Unitários, Sonar

**Diferenciais:**
- Conhecimento em DevOps

## Benefícios

🙋Acesso a plataforma Alura de treinamento.
🏋🏾Swile com Totalpass e New Value.
📙Auxílio a cursos, certificações e eventos: Nos importamos com o seu desenvolvimento!
💥Faça parte da Sioux e do SX Group que tem várias empresas (Go Gamers, [Diaspora.Black](http://diaspora.black/), Ludos Pro, etc.)
🍱Vale refeição e/ou alimentação: Você pode escolher o que for melhor para você.
👩‍⚕️Assistência médica e odontológica: É importante se cuidar e estar bem.
🚆Vale transporte e/ou vale-combustível: A escolha de como você se move é sua.
🚑Seguro de vida: A sua segurança também é a nossa.
📙Auxílio a cursos, certificações e eventos: Nos importamos com o seu desenvolvimento!

## Contratação

CLT

## Como se candidatar

Se cadastre no site https://bit.ly/362Vz3l

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: cv@sioux.com.br

#### Alocação
- Hibrido

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
