### ISSUE TITLE
[Remoto] Front-end Developer na LOOP3

### ISSUE THREAD

**Issue by cassio-z** [frontendbr/vagas#6582]
## Nossa empresa
A [LOOP3](https://www.loop3.com.br/) é uma software house que atua no desenvolvimento de soluções personalizadas.

## Local
Remoto

## Requisitos
Obrigatórios:

* Javascript
* React
* React native
* Inglês Básico (escrita);
* Experiência com ferramentas de versionamento de código (GIT,...);

Desejáveis:

* C#
* Asp.Net Core
* Docker

## Contratação
Júnior: 1.5k - 3k 
Pleno: 3k - 7k 
Sênior: +7k

## Como se candidatar
Entrar em contato, envie seu nome completo, currículo/linkedin e informe sua experiência >>[whatsapp](https://wa.me/554792052220).

#### Alocação
* Remoto

#### Regime
* PJ

#### Nível
* Junior
* Pleno
* Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
