### ISSUE TITLE
[Remoto] Front-end Developer na FLEXPAG

### ISSUE THREAD

**Issue by MauroModesto** [frontendbr/vagas#6585]
## Empresa

A FLEXPAG é uma Fintech especializada em soluções de pagamento, líder no setor de Utilities, com escritórios presentes em Recife/PE e São Paulo/SP.

## Atribuições da vaga:

- Pesquisar e estudar novas ferramentas disponíveis no mercado, visando manter e melhorar a qualidade dos serviços prestados pela área, bem como otimizar o uso dos recursos técnicos e financeiros destinados;
- Atuar na manutenção e atualização das implantações, codificando, testando, especificando, identificando problemas técnicos e operacionais, visando o atendimento das necessidades dos usuários;
- Solucionar possíveis problemas na implantação de novos recursos e programas WEB com uma visão sistêmica, visando dotar a aplicação com uma performance de longo prazo, sustentável e que atinja as metas e os objetivos propostos;
- Selecionar, criar e definir um padrão executável e lógico no desenvolvimento das aplicações WEB para a uniformidade e consistência técnica;
- Codificação em Angular com TypeScript.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Angular

**Desejáveis:**
- conhecimentos em TypeScript
- conhecimentos em JavaScript

**Diferenciais:**
- Boas práticas de programação

## Benefícios

- VA ou VR;
- Aux. Creche;
- Reembolso Lente;
- VT (Desconto de 6% sob a Folha de Pagamentos)
- Gympass;
- Day-off + voucher restaurante (aniversario)
- Saúde Amil Copart. (100% custeado pela empresa para titular e 80% de custeio para dependentes)
- Odonto Amil Copart. (100% custeado pela empresa para titular e dependentes até 18 anos)
- Política de Certificações/Cursos (100% custeado pela empresa)
- Política de Convênios (Empresas parceiras com desconto)
- Universidade Flex (50% do valor pago na sua mensalidade de Graduação ou Pós Graduação)
- PLR;
- Férias (Acrescimo de 40% sob férias + benefício alimentação continuo)
- Plano de Cargos e salários
- Alura cursos ilimitados;
- Opção jornada FullHome Offic
- Cesta Natalina (Cartão ALimentação)

## Contratação
CLT
PJ a combinar

## Como se candidatar

Por favor envie um email para recrutamento@flexpag.com com seu CV anexado ou o link do seu perfil Linkedin - enviar no assunto: Vaga Angular

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@flexpag.com

#### Alocação
- Remoto

#### Regime
- CLT
ou
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
