### ISSUE TITLE
[Remoto] Frontend Developer  na GIC Brasil

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6586]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-java-front-end-131438822?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p style="text-align:justify;">A <strong>Gic </strong>procura pessoa <strong>Frontend Developer</strong> para compor seu time!</p>
<p style="text-align:justify;">A GIC é uma empresa de inovação e tecnologia, que atua no mercado desde a década de 1990 para oferecer soluções em gestão da cadeia de suprimentos para o varejo alimentar. A partir do laboratório de Inovação, Pesquisa e Desenvolvimento da GIC, o GIC Lab nascem as soluções que a empresa cria para as necessidades do mercado, conectando o futuro e as tendências que identifica para o setor.</p>
<p style="text-align:justify;"><strong>A pessoa contratada terá responsabilidades como:</strong></p>
<ul>
<li>Desenvolver sistemas web;</li>
<li>Manter interface web dos sistemas legados;</li>
<li>Realizar testes nas interfaces.</li>
</ul>
<p style="text-align:justify;"></p>

## GIC Brasil: 
 <p><strong>Quem somos</strong></p>
<p>A GIC é uma empresa de inovação e tecnologia, que atua no mercado desde a década de 1990 para oferecer soluções em gestão da cadeia de suprimentos para o varejo alimentar.</p><a href='https://coodesh.com/empresas/gic-brasil'>Veja mais no site</a>

 ## Habilidades: 
 - Vue.js 
- Javascript/Typescript 
- GIT
## Local: 
 100% Remoto
## Requisitos: 
 - Ensino Médio Completo Desejável Ensino Médio Técnico ou Graduação na área de Desenvolvimento Programação 
- Experiência com VueJS e  Desenho de tela  
- Conhecimentos em TypeScript e GIT
## Diferenciais: 
 - Experiência com UX
## Benefícios: 
 - Vale Alimentação ou Refeição de R$ 30,00 por dia; 
- Vale transporte, combustível ou fretado; 
- Aula de Espanhol; 
- Voucher de aniversário; 
- Aulas de RPG; 
- GymPass; 
- ZenKlub; 
- Plano de Saúde Amil One S1500
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Developer  na GIC Brasil](https://coodesh.com/vagas/desenvolvedor-java-front-end-131438822?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
