### ISSUE TITLE
[100% Remoto] Sr. Front-end Developer na Mindera

### ISSUE THREAD

**Issue by Stefany-Passos** [frontendbr/vagas#6588]
## Nossa empresa

As a Frontend Software Engineer you will be responsible for building fluid and responsive user interfaces for multiple platforms and devices.

## Descrição da vaga

- Developing and maintaining features in a collaborative, Agile environment;
- Writing testable code and ensuring the test coverage stays at the agreed level;
- Documenting your code;
- Take ownership of your code every step of the way – from development to deployment and maintenance;
- Diagnose issues in production and devise solutions for them;
- Work both autonomously and collaboratively to complete tasks;
- Be an integral part of solutions design and implementation;

## Local

100% Remote, but you can also work in one of our offices:
Porto, Portugal | Aveiro, Portugal | Coimbra, Portugal | Leicester, UK | San Diego, USA | San Francisco, USA | Chennai, India | Bengaluru, India | Cluj-Napoca, Romania | Blumenau, Brazil

## Requisitos

**You’re great at**

- Vanilla Javascript and modern frameworks and platforms such as AngularJS, Ember, ReactJS, VueJS and/or Node.js;
- Semantic documents using HTML;
- Creating testable code and make testing a priority;

**It also would be cool if you**

- Use state management like Redux, MobX and/or other;
- Know module bundlers and task runners such as Webpack, Parcel, Rollup, Browserify, Grunt or Gulp;
- Use of CSS pre/post-processors like PostCSS, Styled Components, LESS, SASS and/or others;
- Have experience with Test Automation

## We offer

-  No corporate speak or middle managers;
- Competitive salary;
- Choose your laptop,
- Training and Conferences,
- Health insurance for you and your dependents,
- Child care voucher,
- Unlimited Paid Time Off,
- Flexible Working Hours,
- Meal Allowance Card,

## Como se candidatar

Você poderá se candidatar através [deste link ](https://bit.ly/3pUs8HM) ou, se preferir, envie um email para tatiana@remotar.com.br.
OBS: esta vaga está sendo divulgada pela [Remotar](https://remotar.com.br/?utm_source=github) em nome da Mindera, cliente de nossa empresa. No entanto, todo o processo seletivo será diretamente com a Mindera, sem gargalos.

#### Alocação
- Remoto

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
