### ISSUE TITLE
[Salvador] Estágio React Native Developer na Convergence Works

### ISSUE THREAD

**Issue by diegocosta** [frontendbr/vagas#659]
Você gosta de programação e de desenvolvimento de software?  Gosta de novas tecnologias e de desafios? Tem espírito de equipe e é comprometido? Você gostaria de colocar tudo isto em prática numa empresa?

**A Convergence Works** 
Somos a Convergence Works, somos a convergência entre os desafios das empresas e as ideias pra vencê-los. Desenvolvemos plataformas para o mundo digital, com foco em comunicação. Somos especialistas na criação de sites e aplicativos para plataformas de comunicação. Integramos sistema de gestão de conteúdo, aplicativo, disparo de email, solução para clube de assinantes, implantação de editoriais em múltiplas plataformas. 

**Local**
Rua Rubens Guelli, 134 - Sala 309 - Itaigara, Salvador – BA

**Conhecimentos necessários:**
- Conhecimento básico em Javascript 
- Conhecimento básico em React e/ou React Native 
- Conhecimento básico para desenvolvimento Android e iOS
 
**Desejáveis:**
- Conhecimento básico de Redux; 
- Conhecimento em consumo de API´s RESTful.
 
**Carga Horária** 
- 6 horas/dia 

**Benefícios**
- Bolsa no valor de R$ 1.000,00
- Alinhamento de horário 
- Excelente ambiente de trabalho 
- Oportunidades de crescimento e contratação 
 
**Essa vaga é pra você ? Venha fazer parte do nosso time!!!**
Envie seu currículo para vagas@convergenceworks.com.br com seu CV anexado,  enviar no assunto: Vaga Estágio Desenvolvedor Mobile

**Comment by xeromole** [comment]
a vaga ainda esta disponivel?

**Comment by diegocosta** [comment]
Olá @xeromole, a vaga ainda está aberta, pode mandar seu CV para vagas@convergenceworks.com.br

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by diegocosta** [comment]
@LFeh Vaga fechada!
