### ISSUE TITLE
[BARUERI / REMOTO] Front-end Developer na @DRY TELECOM

### ISSUE THREAD

**Issue by caiosalim** [frontendbr/vagas#6590]
## Nossa empresa
Dry Telecom é uma start up de telecom, que deseja realizar a mesma transformação digital que os bancos digitais fizeram.
Transformamos pessoas e marcas em empresas de telecom. Você já ouviu falar da LariCel?

## Descrição da vaga
Precisamos de um front-end jr que irá:

Construir páginas HTML, CSS e JS
E sabendo bem esses 3 tópicos acima, o céu é o limite!

## Local
Remoto ou Alocado em Barueri

## Requisitos
**Obrigatórios:**
- Real conhecimento em HTML, CSS e Javascript

**Desejáveis:**
- Conhecimento em Wordpress/PHP (básico)

## Benefícios
- Vale Transporte
- Descontos na Rede e Restaurante

## Contratação
PJ / CLT a combinar

## Como se candidatar
Por favor envie um email para caio@drycompanybrasil.com.br com seu CV anexado - enviar no assunto: Vaga Dry Telecom

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 01 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Júnior
- Pleno

**Comment by saviocunha2** [comment]
já enviei e-mail, tenho interesse.

**Comment by RafaelGomesXavier** [comment]
Olá, gostaria de pedir uma oportunidade de emprego, pois estou passando por um momento difícil. Sou uma pessoa proativa, que gosta de aprender e possui muita dedicação!

**Comment by fernandodoc** [comment]
opa... enviei um email tb :)

**Comment by HeitorUrbanetz** [comment]
Enviei um email ;)

**Comment by Eduhenrique1** [comment]
Enviei meu currículo, apesar de ter cerca de 01 mês de divulgação, valeu!!

**Comment by guifferrari** [comment]
Não sei se a vaga ainda está disponível, mas enviei meu Curriculo!!

**Comment by saviocunha2** [comment]
nem resposta vocês deram
