### ISSUE TITLE
[Remoto]  Frontend Developer na Trezo

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6592]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/pessoa-desenvolvedora-frontend-magento-adobe-commerce-184037431?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A<strong> Trezo</strong> busca pessoa <strong>Frontend Developer</strong> para compor seu time!</p>
<p>Nós somos a Trezo, uma das principais empresas da América Latina especialista na implantação e manutenção da plataforma Adobe Commerce.</p>
<p>Com mais de uma década de experiência, temos muito orgulho de sermos reconhecidos pela nossa expertise técnica e ter desenvolvido grandes projetos de renome nacional e internacional.</p>
<p><strong>A pessoa contratada será responsável por:</strong></p>
<p></p>
<ul>
<li>Desenvolver e fornecer soluções técnicas utilizando Magento 2 Framework</li>
<li>Participar ativamente de vários estágios do ciclo de vida de desenvolvimento Front-end de plataformas e-Commerce,&nbsp;</li>
<li>Design, desenvolvimento, teste, implantação de projetos</li>
</ul>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>

## Trezo: 
 <p>Nós somos a Trezo, uma das principais empresas da América Latina especialista na implantação e manutenção da plataforma Adobe Commerce.</p>
<p>Com mais de uma década de experiência, temos muito orgulho de sermos reconhecidos pela nossa expertise técnica e ter desenvolvido grandes projetos de renome nacional e internacional.</p><a href='https://coodesh.com/empresas/trezo'>Veja mais no site</a>

 ## Habilidades: 
 - MySQL 
- PHP 
- Magento 
- Bootstrap
## Local: 
 100% Remoto
## Requisitos: 
 - Vivência em Plataforma Adobe Commerce/ Magento  
- Criação e manutenção de módulos/patches 
- Desenvolvimento de soluções, extensões, e otimização personalizadas em e-commerce; 
- Inglês técnico. 
- Conhecimento avançado de JavaScript (nativo) e bibliotecas JavaScript, incluindo jQuery 
- Domínio de PHTML e LESS codificados manualmente, aderindo aos padrões de codificação W3C 
- FE Frameworks (e.g. React, Angular, Vue, Spring Boot) 
- Arquitetura de software (preferencialmente Clean Architecture, MVC, Controller-Service-DAO, Flux). 
- Docker e controle de versão GIT;
## Diferenciais: 
 - Certificação em Adober Commerce / Magento 2
## Benefícios: 
 - Adobe Commerce com os grupos de estudos e voucher de desconto na compra da certificação; 
- Adobe Commerce com um upgrade no salário de 10% a cada certificação conquistada. 
- Day-off de aniversário 
- Férias remuneradas 
- Integração da equipe como Boteco Trezo, Trezo Talk e diversas outras ações internas.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [ Frontend Developer na Trezo](https://coodesh.com/vagas/pessoa-desenvolvedora-frontend-magento-adobe-commerce-184037431?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
