### ISSUE TITLE
[REMOTO] Front-end Developer Javascript na Atlas Technologies

### ISSUE THREAD

**Issue by MaluFrontino** [frontendbr/vagas#6593]
[REMOTO] Front-End Developer  Javascript na Atlas Technologies

Nossa empresa
Organizamos mercados globais, através de times incríveis.
Nascemos em 2017, com o objetivo de inovar o mercado global por meio de tecnologias e pessoas. Buscamos entender as necessidades e as tendências do mercado para gerar valor aos consumidores através do desenvolvimento de softwares de impacto global.

Adoramos pessoas com estes princípios:

Paixão e Empreendedorismo: Que valorizam o entusiasmo, comprometimento e a coragem para assumir riscos, transformando os desafios em resultados surpreendentes.

Colaboração e Diálogo Aberto: Que cultivam em todas as relações a transparência e o trabalho em equipe, respeitando a diversidade de opiniões.

Inovação e Resiliência: Que acreditam que tudo pode ser feito de forma diferente e melhor, entendem o erro como processo de aprendizado e persistem frente à velocidade das mudanças.

Humildade e Lealdade: Que são humildes para estar em constante aprendizado, sendo confiantes sem parecer arrogantes. Têm lealdade aos nossos princípios para construir um círculo de confiança em nossas relações, com ética e respeito.

Resultado e Visão de Longo Prazo: Que entregam resultados consistentes de alta performance, garantindo a escalabilidade e sustentabilidade do negócio.

Descrição da vaga

Organizamos mercados globais, através de times incríveis.
Nascemos em 2017, com o objetivo de inovar o mercado global por meio de tecnologias e pessoas. Buscamos entender as necessidades e as tendências do mercado para gerar valor aos consumidores através do desenvolvimento de softwares de impacto global.

Adoramos pessoas com estes princípios:

Paixão e Empreendedorismo: Que valorizam o entusiasmo, comprometimento e a coragem para assumir riscos, transformando os desafios em resultados surpreendentes.

Colaboração e Diálogo Aberto: Que cultivam em todas as relações a transparência e o trabalho em equipe, respeitando a diversidade de opiniões.

Inovação e Resiliência: Que acreditam que tudo pode ser feito de forma diferente e melhor, entendem o erro como processo de aprendizado e persistem frente à velocidade das mudanças.

Humildade e Lealdade: Que são humildes para estar em constante aprendizado, sendo confiantes sem parecer arrogantes. Têm lealdade aos nossos princípios para construir um círculo de confiança em nossas relações, com ética e respeito.

Resultado e Visão de Longo Prazo: Que entregam resultados consistentes de alta performance, garantindo a escalabilidade e sustentabilidade do negócio.

Local

Exemplo: Escrito localizado em Pelotas, Rio Grande do Sul, porém todas as oportunidades são Remotas.

Requisitos
Forte capacidade de trabalhar colaborativamente como parte de uma equipe;
Conhecimento em HTML e CSS;
Conhecimento Javascript moderno(ES6) e JQuery;
Conhecimento em Design Responsivo;
Conhecimento em padrões de CSS como BEM ou SMACSS;
Conhecimento do uso básico de versionamento GIT;
Conhecimento no consumo de APIs.

Desejáveis:
Conhecimento e experiência no framework Laravel (PHP) e Blade Templates;
Conhecimento em pré-processador SASS e Webpack;
Conhecimento em frameworks como Vue.js e React;
Conhecimento em pattern de gerenciamento de estado como Vuex e Redux;
Habilidade e preocupação com a excelência técnica e boas práticas de desenvolvimento.

Benefícios
Oportunidade 100% remota;
Jornada de trabalho flexível – Maior controle sobre as horas de trabalho e outras atividades;
Day Off – Na semana do seu aniversário você pode escolher um dia de folga;
Plano de carreira – Aqui temos espaço para crescer e se desenvolver;
Melhoria continua – Diversas plataformas com cursos disponíveis e caso você encontre algo legal para aprender, ajudamos financeiramente;
Grande final de semana – A cada 6 meses você tem direito à uma semana de folga;
Integração mensal – Integração com Vale Ifood e e jogos liberados todo mês;
Acolhimento à mãe e pais – Para novos papais e mamães temos uma  politica de benefícios (válido para adoção também);
Day off  de casamento (ou de união estável), você tem direito à dois dias folgas remunerados;
Parceria Studio Lais Vargas – Aulas de funcional, pilates, musculação e treinamento online;
Entre outros.

Contratação
PJ 

Como se candidatar

Por favor envie um email para malu.frontino@tecer.us com seu CV anexado - enviar no assunto: Vaga Javascript

Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.
E-mail para contato em caso de não haver resposta: malu.frontino@tecer.us 

Alocação
- Remoto

Regime
- PJ

Nível
- Pleno
- Sênior

**Comment by HeitorUrbanetz** [comment]
Enviei um email! :)
