### ISSUE TITLE
[REMOTO] Front-End Developer (VTEX.io)  International Project na Kobe - Creative Software House

### ISSUE THREAD

**Issue by Teachrecruiter** [frontendbr/vagas#6595]
## Nossa empresa

A Kobe é uma empresa jovem, cheia de criatividade e talento. O que nos move é melhorar a vida das pessoas desafiando a forma como vivemos. Para isso, unimos pessoas apaixonadas por solucionar problemas usando tecnologia, design e empatia.

## Descrição da vaga

E se você pudesse impactar a vida de milhões de pessoas, atuando no projeto de desenvolvimento com growth & inovação para uma das maiores líderes mundiais de bens de consumo?

A Kobe está procurando pessoas desenvolvedoras web de nível pleno e sênior para se juntarem à equipe. Nesta posição você terá a oportunidade de participar do projeto de expansão de uma empresa que é referência em cervejaria. Você trabalhará ao lado de uma equipe internacional altamente qualificada para desenvolver uma plataforma global que visa transformar a experiência de cerveja das pessoas.
Nessa posição, você atuará em uma cultura de liberdade e autonomia para desenvolver e implementar soluções ao lado de um time altamente capacitado.

## Local
Remoto 

## Requisitos

**Obrigatórios:**
Pelo menos 2 anos de experiência com desenvolvimento de aplicações web;
Conhecimento desenvolvendo com a tecnologia [Vtex.io](http://vtex.io/);
Experiência com Testes Unitários;
Atuação nas diferentes etapas do desenvolvimento;
Habilidade de comunicação interpessoal;
Autonomia na tomada de decisões;
Orientação para UX.

**Desejáveis:**

Experiência em projetos internacionais;
Experiência com [Node.js](http://node.js/);
Conhecimento em AWS;
Atuação prévia com Redis e Elastic Search.## Benefícios

Health Insurance: plano de saúde Bradesco, plano odontológico e seguro de vida 100% cobertos e sem coparticipação;
Flexible Time: possibilidade de gerenciar sua agenda com autonomia (e claro, responsabilidade!);
Kober Remote Experience: cultura remote first com atividades de integração periódicas para Kobers;
Kobe Growth: Plano de Desenvolvimento Individual (PDI) para cada Kober;
International Culture: cultura internacional com projetos fora do Brasil e vinda periódica de intercambistas de diferentes locais do mundo;
Kober+1: bônus por indicação por trazer pessoas talentosas como você para a Kobe; 
The Right Tools: equipamento de alto nível para sua estrutura de trabalho.
## Contratação

CLT

## Como se candidatar

Acesse: https://kobe.gupy.io/job/eyJqb2JJZCI6MTU3Mzc4NCwic291cmNlIjoiZ3VweV9wdWJsaWNfcGFnZSJ9?jobBoardSource=gupy_public_page ou CV para o e-mail: eduarda.damiani@kobe.io

## Tempo médio de feedbacks - 7 DIAS

Costumamos enviar feedbacks em até 4 dias após cada processo.
E-mail para contato em caso de não haver resposta: eduarda.damiani@kobe.io

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
