### ISSUE TITLE
[São Paulo] Sr Full-stack JS Front-end Dev - React, React Native

### ISSUE THREAD

**Issue by andrefranco** [frontendbr/vagas#66]
## Descrição da vaga

Desenvolvedor senior JavaScript full-stack (React, React Native, Node.js).
Experiente em desenvolvimento de plataformas complexas, white labels, usando técnicas de TDD, XP, programação funcional e metodologias ágeis.
Comprovar experiência, exibir portfólio online e informar contatos de referência.
## Local

Escritório (ideal), São Paulo, Itaim ou Remoto
## Benefícios
- PC ou Mac;
## Requisitos

**Obrigatórios:**
- 3 anos de experiência com JS;
- 5 anos de experiência com desenvolvimento para web;
- Trabalho em equipe;

**Desejáveis:**
- Graduação em exatas;
- Experiência com NoSQL e Express;
- Experiência com Ruby on Rails;

**Diferenciais:**
- Trabalhar in loco, no escritório no Itaim
## Contratação

PJ
## Nossa empresa

A Critical Mass é uma agência de experiência digital canadense, com 20 anos de história e 850 funcionários ao redor do mundo. Temos clientes como Nike, Adidas, PepsiCo, Ambev e Unilever. Iniciamos operações no Brasil em Dez/2015 e temos ainda apenas 6 funcionários, todos seniors.

Temos um DNA bastante inovador. Criamos e desenvolvemos experiências digitais, desde plataformas web e apps até processamento de linguagem natural e instalações físicas com realidade aumentada.
## Como se candidatar

Envie um e-mail para andre.franco@criticalmass-br.com com seu LinkedIn e link de portfólio, idealmente explicando sua contribuição nos principais projetos listados. Enviar no assunto: Vaga JS full-stack

**Comment by willianjusten** [comment]
Opa @andrefranco , eu deixei alocado/remoto porque pelo que eu entendi, pode remoto também. Apesar de a preferência ser alocado, certo?

Boa sorte =)

**Comment by andrefranco** [comment]
Certo, @willianjusten. Tks :)

**Comment by eduardojmatos** [comment]
@andrefranco já preencheu a vaga? Nos avise pra mantermos ou removermos da lista :)

**Comment by andrefranco** [comment]
Oi Eduardo,

Ainda temos a vaga aberta.

tks
André

**Comment by eduardojmatos** [comment]
@andrefranco blz! :)
