### ISSUE TITLE
[Remoto] Fullstack Developer

### ISSUE THREAD

**Issue by atilarec** [frontendbr/vagas#660]
## Descrição da vaga

Reimplementação de plataforma de diagnósticos por imagem existente para tecnologias mais recentes como electron e couchdb.
Vaga para trabalho remoto como programador Javascript.

## Local

Trabalho remoto total.

#### Diferenciais

- Flexibilidade de horário;
- Aberto ao uso tecnologias inovadoras;
- Processo de desevolvimento construtivo e participativo (baseado em scrum);
- Trabalhar com equipe com mais de 10 anos experiência em desenvolvimento de software.

## Requisitos

**Obrigatórios:**
- JavaScript, HTML5, CSS3;
- Node JS, Jquery, Ajax;
- Git.

**Desejáveis:**
- Couchdb;
- React, Angular, Vue;
- Amazon AWS.

**Diferenciais:**
- Electron;
- Python, Django;
- Scrum;
- REST;
- Comprometido, criativo, proativo e colaborativo.

## Contratação

A combinar

## Nossa empresa

- A Orbitta é uma empresa especializada em desenvolvimento de sistemas de diagnósticos médicos;
- Focada nas pessoas, tanto nossos clientes como nossos coloboradores;
- Formada por pessoas apaixonadas por tecnologia e dos benefícios que ela traz para nosso clientes e população em geral.

## Como se candidatar

Por favor envie um email para Átila Bezerra: atila@diagnes.com.br com seu CV anexado - enviar no assunto: Vaga Programador JavaScript

**Comment by danielswater** [comment]
Enviado

**Comment by atilarec** [comment]
Fechado para envio de currículos a vaga.
Aos que enviaram o currículo, continuaremos com o processo de seleção.
