### ISSUE TITLE
[Hibrido / São Paulo/SP] Fullstack Node/React Developer na PMK Advogados

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6603]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/fullstack-nodereact-developer-122830050?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>PMK Advogados</strong> está buscando <strong><ins>Fullstack Node/React Developer</ins></strong><strong> </strong>para compor seu time em um novo desafio!</p>
<p>Somos uma startup patrocinada por um escritório de advocacia com forte atuação em operações estruturadas no mercado imobiliário e aqui você encontrará um ambiente organizado, desafiador e altamente voltado para negócio e soluções criativas onde você poderá fazer a diferença.&nbsp;</p>
<p>Seu desafio será ajudar a construção do projeto da <strong>RevoluTI</strong>, uma startup que tem como missão revolucionar as transações imobiliárias por meio da sua solução Saas.&nbsp;</p>

## PMK Advogados: 
 <p>Escritório de advocacia com atuação na área de Real Estate, Corporate e Mercado de Capitais, desenvolvendo em conjunto com os clientes operações estruturadas no mercado imobiliário, incluindo transações imobiliárias, fusões e aquisições (M&amp;A), securitizações, fundos de investimento e financiamento de projetos imobiliários em geral.&nbsp;</p>
</p>

 ## Habilidades: 
 - HTML 
- CSS 
- Javascript 
- React.js 
- Node.js 
- MySQL
## Local: 
 São Paulo/SP
## Requisitos: 
 - Conhecimento em HTML, CSS, javascript, React.js, Node.js 
- Habituado a trabalhar com banco de Dados MySQL 
- Noções de autenticação JWT, API REST, OCR, Google Storage 
- Vontade de aprender e construir um projeto duradouro 
- Habituado a metodologia ágil
## Diferenciais: 
 - Conhecimento em Next.js e Nest,js 
- Noções de Prisma ORM
## Benefícios: 
 - Horários Flexíveis 
- Possibilidade de crescimento com a startup e participação nos lucros 
- Maior Parte do Trabalho via Home Office 
- Possibilidade de 100% Home Office após período de adaptação (3 meses)
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack Node/React Developer na PMK Advogados](https://coodesh.com/vagas/fullstack-nodereact-developer-122830050?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Regime
PJ
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
