### ISSUE TITLE
[Remoto] Frontend Developer na @Datum✨| VEM FAZER PARTE DO PLANETA ROXO 💜

### ISSUE THREAD

**Issue by julianakraemer** [frontendbr/vagas#6605]
## Nossa empresa

A Datum é uma empresa GPTW (Great Place to Work) pelo segundo ano seguido e nossa principal proposta é ativar o protagonismo, por isso investimos pesado no desenvolvimento de nossos colaboradores.
## Descrição da vaga
Oportunidade Sênior para atuar como Desenvolvedor Front React na construção de um novo projeto e auxiliar na definição da arquitetura em conjunto com o restante do time!  
## Local

Remoto 
## Requisitos

Você pode se conectar com a oportunidade se possuir experiência em:

• HTML5, CSS3,

• Pré Processadores (Sass),

• JavaScript ES6,

• React Js,

• Next.js,

• Typescript,

• Automatização de Builds (Npm, Yarn, Gulp, Webpack),

• Design Responsivo Web,

• Controle de Versionamento (Git);

 

Desejável:

• Conhecimento em E-commerce, ter trabalhado com metodologia ágil;

## Benefícios

Vale refeição/alimentação
Auxílio Home Office
Gympass
Plano de saúde
Plano odontológico
Seguro de vida
Cíngulo (saúde mental)
Assessoria financeira, jurídica e psicológica para funcionários

Aqui na Datum, você também vai ter:

Proagonistas (game de incentivo à carreira do colaborador)
Datum Academy (programa de formação e treinamentos)
English Class
Ginástica Laboral
Rock Leader (programa de liderança de
iniciativa) +Felicidade que visa a felicidade do colaborador

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para [juliana.kraemer@datum.inf.br](mailto:juliana.kraemer@datum.inf.br) com seu CV anexado - enviar no assunto: Vaga React

**Comment by venturion** [comment]
Anuncie em https://devance.com.br 👍

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
