### ISSUE TITLE
[Remoto] Frontend/Tech Lead Developer na Condofy

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6606]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-react-developer-tech-lead-120858159?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>Condofy </strong>está buscando <strong><ins>Frontend React Developer</ins></strong> nível pleno/sênior, para assumir a posição de <strong>Tech Lead</strong>!</p>
<p>Nosso desafio é ser uma startup com um modelo único e inovador, que acredita no impacto que a tecnologia pode causar na administração de condomínios.&nbsp;</p>
<p>Vamos trabalhar juntos resolvendo os principais desafios! Somos uma startup em fase de expansão e precisamos de um(a) desenvolvedor(a) que goste de encarar desafios complexos no back end e em nossos bancos de dados - sempre de olho na experiência de usuários.&nbsp;</p>
<p>Estamos sempre querendo melhorar nosso tech stack, e você será parte fundamental desse processo.&nbsp;</p>
<p>Se você se motiva por grandes desafios, essa vaga é pra você!</p>

## Condofy: 
 <p>Administradora de condomínios inteligente feita para você.</p>
<p>Somos a primeira administradora 100% digital que veio para descomplicar a gestão de condomínios.</p><a href='https://coodesh.com/empresas/condofy'>Veja mais no site</a>

 ## Habilidades: 
 - React.js 
- Google Cloud Platform (GCp) 
- GitHub 
- HTML 5 
- CSS 3
## Local: 
 100% Remoto
## Requisitos: 
 - Sólida experiência no frontend utilizando react.js 
- Sólido conhecimento em HTML, CSS e Javascript 
- Experiência com gestão de equipe ou projetos (Tenha conduzido um projeto de ponta a ponta) 
- Conhecimento em google cloud -GCP e Github 
- Noções de desenvolvimento em .Net Core 
- Hands-on work 
- Vontade de crescer e construir um projeto duradouro junto a empresa 
- Habituado a trabalhar com a metodologia ágil
## Diferenciais: 
 - Conhecimento e/ou experiência em .Net Core
## Benefícios: 
 - Horários flexíveis 
- Auxílio home-office 
- Cartão Flash 
- Grandes chances de crescimento 
- 100% remoto 
- Oportunidade de contribuir efetivamente e crescer junto com a startup 
- Possibilidade de stock options 
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend/Tech Lead Developer na Condofy](https://coodesh.com/vagas/frontend-react-developer-tech-lead-120858159?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
