### ISSUE TITLE
[Remoto] Front-end Developer Vue.js @Ília

### ISSUE THREAD

**Issue by fagnerpelicioni** [frontendbr/vagas#6608]
## Nossa empresa

Você terá a oportunidade de fazer um trabalho que impacta a vida das pessoas. É a chance de resolver problemas reais, com diversos desafios que irão trazer crescimento para você e sua carreira.
Temos um ambiente amigável, solidário e aventureiro. Aqui todo mundo anda lado a lado. Errar, aprender e evoluir em conjunto é algo intrínseco da nossa cultura.
Gostamos de trabalhar com gente diferente. Aqui você irá conviver com pessoas de diversas origens, experiências, habilidades e perspectivas.
Na ília, todo mundo tem as mesmas oportunidades de crescer e compartilha um mesmo objetivo: tornar o mundo surpreendente mais simples.

## Descrição da vaga

Desenvolver em Vue JS;
Coordenar e automatizar processos de criação do projeto White Label;
Aplicar melhores práticas de desenvolvimento;
Disseminar conhecimento e melhores práticas.

## Requisitos

- Conhecimento em Vue JS ou React JS (SPA);
- Conhecimento sólido em chamadas de API Rest ou HTTP;
- Conhecimento de banco de dados;
- Disposição e flexibilidade para trabalhar em projetos diferentes (tecnologias diferentes);
- CMS;
- Github;
- HTML, CSS, Sass/Less [desejável], Javascript;
- Lógica de programação avançada;
- SOLID, Clean Code, Cloud;
- Conhecimento sólido em HTML, CSS, Sass/Less, Javascript. 
- O que poderia ser um diferencial:
- Codificar testes de regressāo automatizados;
- Conhecimentos em Node.js;
- Conhecimentos de arquitetura;
- Conhecimento em ferramentas de CI/CD.

## Benefícios

- Contrato de Trabalho CLT - 40h semanais com jornada flexível, sendo executado 100% de forma remota;
- Assistência Médica e Odontológica extensivo aos dependentes;
- Vale Refeição/Alimentação;
- Seguro de vida;
- Language Academy com aulas, atividades e mentoria para estudar línguas;
- Programa de premiação a indicação de outros profissionais;
- Fóruns Técnicos: Neles o time compartilha práticas, estudos, projetos e ideias;
- Grupos de Chapter: Reúnem pessoas com skills similares para compartilhamento de ideias, práticas e experiências;
- Seu Niver, seu bolo!
- Byod: Alugamos o seu notebook pessoal (valor mensal) ou disponibilizamos uma máquina da empresa (livre escolha).

## Contratação

CLT

## Como se candidatar

https://grnh.se/853dcf454us

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
