### ISSUE TITLE
[Remoto] Frontend Developer na Consulta Remédios

### ISSUE THREAD

**Issue by giulianovarriale** [frontendbr/vagas#661]
## Descrição da vaga

Procuramos um desenvolvedor pleno ou sênior capaz de transformar protótipos em interfaces ricas e funcionais através de um código legível e reutilizável. O desenvolvedor irá atuar tanto na resolução de bugs, melhorias e novas features em projetos que já estão em produção quanto no desenvolvimento de novos projetos.

## Local
Remoto. Trabalhe no conforto de sua casa :)

## Requisitos

**Obrigatórios:**
* Conhecimentos sólidos em Javascript, HTML, CSS;
* Experiência com Pre/Post processors e metodologias de CSS (BEM, SMACSS, ...);
* Experiência com versionamento de arquivos Git;
* Bom Entendimento dos conceitos de componentização de libs como React, Vue, Ember e etc;
* Experiência ou familiaridade com a escrita de testes unitários e testes de aceitação;

**Desejáveis:**
* Experiência com desenvolvimento focado em componentes;
* Experiência com Ruby on rails;
* Experiência em projetos de grande escala;
* Programação funcional;

## Contratação
PJ ou CLT, você escolhe.

## Sobre a Consulta Remedios
O [CR](https://consultaremedios.com.br/) é um portal de comparação de preços de produtos farmacêuticos (tudo o que você encontra na farmácia, encontra aqui) que atua com diversos serviços e em nível nacional.

Ajudamos as pessoas com tecnologias e soluções, que simplificam e descomplicam a vida, sempre buscando melhorar as práticas na área de saúde. 
Trabalhamos continuamente para crescer e se manter como o site líder no Brasil em relevância, mas queremos ser também referência na experiência oferecida para os usuários.

Somos os líderes disparados no segmento, com mais de 7.000.000 de usuários mensais entre paciente, profissionais de saúde, profissionais da indústria e farmácias. Entendemos que nosso trabalho é contínuo e também muito urgente, saúde não pode esperar. Se você quer fazer parte de um negócio que realmente possa mudar a sua vida e a vida e milhões de pessoas, queremos você!

## Como se candidatar
Por favor envie um email com o assunto "Vaga Frontend Developer" para giuliano@consultaremedios.com.br com seu perfil do github e linkedIn que entrarei em contato.

**Comment by danielswater** [comment]
Enviado

**Comment by danlaurent** [comment]
Enviado. :)

**Comment by paulitolinhares** [comment]
Enviado!

**Comment by samuelsilvadev** [comment]
Sent :D

**Comment by ribeiroevandro** [comment]
Enviado.

**Comment by ygorlazaro** [comment]
Enviado!

**Comment by raloliver** [comment]
Enviado!
