### ISSUE TITLE
[Remoto] Lead Frontend React Native na Builders

### ISSUE THREAD

**Issue by RaissaBaltazar** [frontendbr/vagas#6614]
Papo reto: aqui na Builders você irá se deparar com uma cultura voltada ao empreendedorismo. Os projetos, as pessoas e seu dia a dia serão norteados pela vontade de fazer acontecer. Você poderá liderar pessoas incríveis e ser agente de transformação, além de vivenciar uma estrutura de frontend idealizada apenas aqui na Builders. 👀 **E aí, bora ser Builder?**

**Como Builder, esse será o seu Desafio 😎:**
- Buscar maneiras de amadurecer e evoluir o time, coletivamente e individualmente
- Discernir métricas técnicas de sucesso e qualidade, e procurar maneiras de melhorá-las
- Colaborar na evolução das boas práticas técnicas, como desenvolvimento de bibliotecas reaproveitáveis de código;
- Elaborar e registrar feedbacks construtivos para o time;
- Manter constantes 1:1s com os membros da equipe;
- Planejar e executar estratégias de curto e longo prazo que beneficiem a maturidade técnica do time e das entregas de produto;
- Se envolver em resolver bugs e entregas de funcionalidades em projetos, quando e se necessário para garantir a entrega;

**Tecnologias que vão gerar valor nos projetos 💻:**
- Fluência em TypeScript;
- React Native (Redux/Mobx);
- APIs REST;
- Trabalhar com diferentes dimensões de dispositivo (tablet, celular, etc)
- Conhecimento geral do ambiente móvel;
- Versionamento de código com Git e Github;

**O que te aproxima de ser uma Pessoa Builder 💪:**
- Colaborar e se comunicar eficientemente com todos
- Atingir consenso entre diferentes envolvidos em situações de conflito
- 5 anos ou mais de experiência técnica
- 2 anos ou mais em uma posição de liderança técnica
- Profunda compreensão em diferentes tecnologias Frontend (JS, TS, React, React Native, outras)
- Excelente comunicação verbal e escrita

**Junte-se ao Movimento! 💛🖤** https://jobs.kenoby.com/sejabuilder

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
