### ISSUE TITLE
[Remoto] Senior React Native Developer na Builders

### ISSUE THREAD

**Issue by RaissaBaltazar** [frontendbr/vagas#6615]
Somos uma comunidade de pessoas que desejam aprender, evoluir, empreender e construir iniciativas que gerem valor. Um lugar para você se desenvolver, crescer e alcançar resultados exponenciais, é essa oportunidade que te espera aqui, **o momento para se tornar Builder é agora! 😎**

**Tecnologias que vão gerar valor nos projetos 💻:**
- Fluência em TypeScript;
- React (Redux/Mobx);
- APIs REST;
- Trabalhar com diferentes dimensões de dispositivo (tablet, celular, etc)
- Conhecimento geral do ambiente móvel;
- Versionamento de código com Git;
- Conhecimento em arquitetura de software;
- Metodologias ágeis.

**O que te aproxima de ser uma Pessoa Builder 💪:**
- Conhecimento em CI/CD (App Center, Fastlane);
- Conhecimento em Firebase (Analytics, Crashlytics, etc);
- Experiência em linguagens nativas e construção de bridges.

**Como Builder, você terá acesso a 👀:**
- Oportunidades reais de empreender e impactar;
- Fazer parte de uma comunidade de empreendedores; de ponta, o Movimento;
- Inovação e criação liberados;
- Participar de um processo único de geração de valor;
- Contribuir na criação de métodos disruptivos;
- Colocar suas ideias no mercado, na prática! :)
- Possibilidade de Profit share em novos Negócios.

**Junte-se ao Movimento! 💛🖤** https://jobs.kenoby.com/sejabuilder

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
