### ISSUE TITLE
[Remoto] Ionic Developer na Linked RH

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6616]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-ionic-114225355?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>A Linked RH</strong> procura pessoa<strong> Ionic Developer</strong> para compor seu time!</p>
<p>Oferecemos apoio para que as pessoas se desenvolvam profissionalmente, através de plano de carreira, programa de mentoria, ambiente desafiador e oportunidades de aprendizados constantes. Somos uma empresa apaixonada pelo que fazemos, trazendo transformação e inovação. São mais de 25 anos de experiência em desenvolvimento de software.&nbsp;</p>
<p>&nbsp;A pessoa contratada utilizará IONIC 5 e as melhores práticas de arquitetura e programação.</p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>

## Linked RH: 
 <p>Oferecemos apoio para que as pessoas se desenvolvam profissionalmente, através de plano de carreira, programa de mentoria, ambiente desafiador e oportunidades de aprendizados constantes.</p>
<p>Você utilizará metodologias ágeis, ferramentas/tecnologias de última geração, computação em nuvem e muito mais.</p><a href='https://coodesh.com/empresas/linked-rh'>Veja mais no site</a>

 ## Habilidades: 
 - Ionic 
- Typescript 
- REST APIs
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência sólida em desenvolvimento com IONIC 
- Conhecimento em API REST 
- Conhecimento em testes automatizados.

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Ionic Developer na Linked RH](https://coodesh.com/vagas/desenvolvedor-ionic-114225355?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
