### ISSUE TITLE
[Remoto  Internacional - 60 FullStack Senior Developers:]

### ISSUE THREAD

**Issue by arturbr97** [frontendbr/vagas#6622]
VanHack está buscando mais de 60 FullStack Senior Developers: a canadense VanHack, ganhadora do prêmio “LinkedIn Talent Awards 2021”, está contratando mais de 60 profissionais FullStack para trabalhar em Winnipeg e Calgary no Canadá. Todas as vagas oferecem patrocínio de visto de trabalho, onde você começa remotamente e depois realoca para o Canadá. Os salários variam entre CAD$100.000,00 e CAD$120.000,00 por ano, além de outros benefícios. O processo seletivo, conduzido pela VanHack, é 100% gratuito para o candidato. Aplique hoje para seu emprego dos sonhos:

 https://vanhack.com/candidates?invite=arturpere

**Comment by venturion** [comment]
Anuncie em https://devance.com.br

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
