### ISSUE TITLE
[Remoto] Frontend React (Sênior) na Basement

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6623]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/senior-react-frontend-191556432?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>Basement</strong> busca pessoa <strong>Frontend React</strong> para compor seu time!</p>
<p>Somos uma startup criada para facilitar a gestão de participações acionárias e a consequente democratização do equity, para que mais pessoas participem do crescimento dos negócios que ajudaram a criar e, assim, possamos contribuir para a redução das desigualdades. Desde 2018, <strong>somos pioneiros e líderes na construção de uma infraestrutura tecnológica para o gerenciamento de equity de startups e grandes companhias</strong>, através de uma solução SaaS (software as a service) que digitaliza e organiza as participações societárias de milhares de empreendedores, investidores e colaboradores.</p>
<p>Para nosso time de tecnologia, buscamos uma pessoa Developer experiente com foco em React e com muita vontade em contribuir e aprender com uma empresa em alto crescimento. Valorizamos muito a autonomia, a liberdade para trazer novas ideias, o clima de colaboração e a transparência sobre a empresa. Sabemos da importância de construir juntos.</p>
<p><strong><ins>Quais serão suas responsabilidades?</ins></strong></p>
<ul>
<li>&nbsp;Participar da concepção do produto junto com a equipe de Design;</li>
<li>&nbsp;Gerenciar projetos multidisciplinares;</li>
<li>&nbsp;Construir interfaces com React e Next.JS ;</li>
<li>&nbsp;Escrever códigos com cobertura de teste;</li>
<li>&nbsp;Ajudar o time a monitorar a estabilidade dos sistemas;</li>
<li>&nbsp;Abertura para colaborar também no back-end (Ruby on Rails);</li>
<li>Assistir ao desenvolvimento do time com interações constantes;</li>
<li>Manutenção da infraestrutura dos projetos (ex.: CI/CD).</li>
</ul>

## Basement: 
 <p>Somos uma startup criada para que empreendedores, investidores e colaboradores assumam o controle das suas participações societárias de forma simples e digital. Desde 2018, somos <strong>pioneiros e líderes na construção de uma nova infraestrutura própria para o gerenciamento de equity de startups e PMEs</strong>, e nossa solução SaaS (software as a service) digitaliza e organiza a vida societária de milhares de empreendedores, investidores e colaboradores com stock options.</p>
<p><em>“Estamos na missão para construir um futuro com mais donos e donas, e entendemos que ajudar empreendedores, investidores e colaboradores a saberem quem é dono do que é uma parte fundamental dessa jornada.” Frederico Rizzo, CEO e Co-Founder do Basement<br></em></p><a href='https://coodesh.com/empresas/basement'>Veja mais no site</a>

 ## Habilidades: 
 - React.js 
- Typescript 
- React Hooks
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência Sólida com React; 
- Git, Github actions; 
- React e/ou Next.JS; 
- Webpack, Babel; 
- React Hooks, State management (ex.: Recoil, API Context, Redux); 
- Testes automatizados (Jest, React testing library); 
- Consciência e empatia com os usuário do produto; 
- Paixão em co criar com outros times; 
- Typescript; 
- Styled-components e SASS; 
- Design System;

## Benefícios: 
 - Trabalho remoto e com total flexibilidade de horários. 
- Auxílio Saúde; 
- Gympass (clube de assinatura de academias e atividades físicas); 
- Bolsa desenvolvimento (utilizada para cursos, eventos, livros); 
- Auxílio Remoto 
- Day-Off no mês de aniversário; 
- Short Friday (trabalhamos apenas 6h nas sextas-feiras) 
- Plano de Stock Options;
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend React (Sênior) na Basement](https://coodesh.com/vagas/senior-react-frontend-191556432?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
