### ISSUE TITLE
[Remoto Las Vegas, Nevada] Front Developer VUE.js pl/sr @dqr.tech

### ISSUE THREAD

**Issue by gsabreudev** [frontendbr/vagas#6624]
## SOBRE NÓS
Nascemos de uma parceria de mais de 10 anos entre seus sócios, somando a paixão por tecnologia à vontade de construir uma empresa diferente, investindo na proximidade com nossos parceiros e clientes.
Somos uma consultoria especializada em Arquitetura de TI, Outsourcing de Profissionais e Hunting.

## DESAFIO: 
A DQR TECH está em busca de um profissional para atuar nas Squads Ágeis em nosso cliente, uma Edtech sustentável e inovadora de Las Vegas - Nevada, que busca combinar e conectar estudantes com universidades adequadas e suas futuras carreiras.

## ATIVIDADES:
-Analisar, projetar, desenvolver, configurar, implantar, manter e aprimorar aplicações responsivas para a web.

## REQUISITOS:
 -Desenvolvimento com foco no front-end de aplicações web
 -Javascript, HTML e CSS
 -Vue.js
 -Teste de software (unitário, integração, ponta-a-ponta, etc)
 -Jest, Puppeteer, Cypress e similares
 -Metodologia scrum 
 -Inglês intermediário ou avançado.

## REQUISITOS DESEJÁVEIS:
-Node.js
-Typescript
-DevOps
-Docker
-Serverless
-AWS

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
