### ISSUE TITLE
[REMOTO] FullStack Developer na ACCT Global 

### ISSUE THREAD

**Issue by Ednaratorres** [frontendbr/vagas#6625]
## Nossa empresa

Somos a ACCT Consulting & Technology, atualmente possuímos projetos de implementação, operação e evolução de e-commerce em 19 países e desde 2020 certificados pelo Great Place To Work (GPTW) como uma das melhores empresas de TI para se trabalhar.

## Descrição da vaga

- Irá desenvolver um código de alta qualidade, garantindo a funcionalidade, usabilidade, manutenibilidade e performance, além do uso de práticas de teste e qualidade;
- Atuará junto com o time para entender o impacto das soluções que o time desenvolve nos nossos clientes e no usuário final;
- Irá trabalhar em um ambiente colaborativo com um time de ponta, em que práticas de feedbacks e motivação para se desenvolver estão sempre presentes.

## Local

REMOTO

## Requisitos

**Desejáveis:**
- Conhecer javascript vanilla, jquery, React e Node.js;
- Tiver conhecimento com API's (REST, SOAP);
- Possuir familiaridade com metodologias ágeis.

**Diferenciais:**
- Tiver experiência com plataformas de e-commerce (VTEX, Magento, etc);
- Inglês avançado ou fluente;
- Participação ativa em comunidades de Tecnologia (palestras, meetups, eventos, tech talks, blogs) e projetos open source como forma de disseminar o conhecimento.

## Benefícios

- Política de home office;
- Benefício All remote, para montar seu espaço de trabalho em casa;
- Vale transporte;
- Vale alimentação e/ou vale refeição;
- PLR;
- Auxílio creche;
- Assistência médica e odontológica;
- Seguro de vida em grupo;
- Convênio com farmácias e academias;
- Benefício terapia (nesse momento de pandemia e isolamento social);
- Parceria com o SESC.

## Contratação

CLT

## Como se candidatar

Por favor envie um e-mail para recrutamento@acct.global com seu CV anexado - enviar no assunto: Vaga Fullstack
Ou acessar nossa página de vagas > https://jobs.kenoby.com/acct?utm_source=website

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
