### ISSUE TITLE
Pessoa Desenvolvedora Frontend Pleno (React) na SAMBATECH (FECHADA)

### ISSUE THREAD

**Issue by daiaoli** [frontendbr/vagas#6627]
## Descrição da vaga

A Samba está buscando uma pessoa Desenvolvedora Frontend Pleno (React) para agregar ao nosso time! Para essa oportunidade buscamos uma pessoa para atuar em regime CLT e 100% remoto. Procuramos alguém com propósito forte e que esteja disposta a trabalhar em ambiente colaborativo e dinâmico, pronto para crescer profissionalmente junto com a nossa equipe fora da curva!

A Samba gosta de fazer a diferença sempre e nosso time é o responsável para que isto aconteça! Por isso, a gente espera que você seja uma pessoa apaixonada por tecnologia, assim com a gente! Todas as nossas vagas também se aplicam a pessoas PCD, então fique à vontade para se candidatar.

## Responsabilidades

- Desenvolver e manter soluções de software.
- Escrever códigos limpos e funcionais no front-end e no back-end;
- Participar dos ritos do projeto e propor novas soluções.
- Acompanhar o levantamento de requisitos.
- Trabalhar em conjunto com outros membros de equipe que fazem parte do projeto.
- Apoiar a realização de atividades dos profissionais de menor domínio técnico, repassando conhecimentos e atuando no desenvolvimento dos mesmos.
- Realizar integrações com APIs externas.
- Utilizar e modelar bancos de dados relacionais e/ou não-relacionais.

**Requisitos Obrigatórios:**

- Desenvolvimento em Frontends e aplicativos web e integração de APIs REST;
- Linguagens: JavaScript / TypeScript /;
- TML5, SCSS (de preferência SASS), Bootstrap, JAVASCRIPT (es6);
- Linguagens de programação de fonte aberta como React, VueJS Git - Ambientes de nuvem;
- Integração e testes unitários.

**Diferencial:**

- Noções em Devops (uso de terminal linux, containers docker, processos de build e deploy automatizados, monitoria);
- Noções de modelo de testes unitários e integrados;
- Noções de boas práticas de Engenharia de Software;
- Noções em infra-estrutura em nuvem na AWS ou equivalente;
- Inglês intermediário.

## Local

Remoto - Brasil.

## Benefícios

- Ambiente criativo e inovador;
- Clima leve e descontraído;
- Horário flexível;
- Home office;
- Auxílio home office;
- Plano de Saúde;
- Plano Odontológico;
- Vale refeição/alimentação;
- Gym Pass;
- Day off no dia do aniversário;
- Seguro de vida;
- Ways Education - Atividades extracurriculares para os filhos;
- Previdência privada.

## Contratação

CLT e 100% remoto.

## Nossa empresa

Você já se imaginou sendo uma pessoa reconhecida por trabalhar em um dos times mais inovadores do planeta Terra? Aqui é exatamente o que acontece com quem compõe o nosso time!

Em terra onde o time participa dos resultados e é reconhecido por isso, cliente é Rei e Rainha! Mas não somos meros súditos. Aqui na Samba, somos as pessoas que fazem parte do Conselho Real!

A cultura da Sambatech faz brilhar os olhos de quem vê e enche o coração de quem faz parte! Nossa liderança é engajada com o time e a inovação transborda pelos poros de todo mundo que veste essa camisa!

Assista o nosso vídeo institucional para ter uma ideia do que é ser Samba!
https://www.youtube.com/watch?v=zK4nCF7ywtg

LINK PARA CANDIDATURA
**https://portal.kula.jobs/jobs?alias=sambatech**

**Comment by venturion** [comment]
anuncie em https://devance.com.br 👍
