### ISSUE TITLE
[Remoto] Full Stack Developer (NodeJS + ReactJS)

### ISSUE THREAD

**Issue by GiuButtenbender** [frontendbr/vagas#6628]
## Nossa empresa

A Feel Tech é uma consultoria de atração, seleção e desenvolvimento de pessoas COM FOCO em inovação e resultados, E COM MUITO AMOR pelo que faz!

Estamos com uma oportunidade para uma empresa que você consegue apoiar clientes de toda América Latina, e ainda atuar com tecnologias de ponta, e em uma empresa que aposta no desenvolvimento dos seus profissionais. 

## Descrição da vaga

Pessoa Desenvolvedora Full Stack para atuar em projetos dinâmicos com inovação e inteligência de mercado. 

Sobre as responsabilidades deste profissional:

Desenvolver código limpo e funcional, no back-end e front-end das aplicações;
Participar ativamente dos momentos de planejamento, revisão, diárias do time junto com Product Managers e Product Designers para construir aplicações aderentes à proposta de valor;
Desenvolver aplicações front-end seguindo as diretrizes de design da companhia;
Testar as aplicações para garantir performance, responsividade e eficiência;
Escrever documentação técnica dos produtos e processos;
Trabalhar na evolução do produto, em especial, buscando escalabilidade do mesmo e a exploração de novos modelos de negócio.

## Local

Remoto

## Requisitos

- Experiência em desenvolvimento Web (Javascript, HTML e CSS);
- Experiência em desenvolvimento front-end (Vue,js, React, Angular);
- Experiência em construção de APIs e serviços (Node.js e express.js);
- Conhecimento em banco de dados relacional (Postgres, MySQL, Oracle, SQL Server, etc);
- Conhecimento em banco de dados não relacional (MongoDB, Redis, Dynamo DB, etc);
- Conhecimento consumindo dados do Data Warehouse BigQuery (diferencial);
- Conhecimento em arquitetura de software (microsserviços, aplicações monolíticas, etc) (diferencial);
- Conhecimento em CI/CD, Jenkins (diferencial);
- Conhecimento em Arquitetura, padrões de projeto e código limpo (diferencial);
- Conhecimento em Testes Automatizados (unitário, E2E, integração, entre outros) (diferencial);
- Conhecimento em Arquitetura Cloud, AWS (Elastic Beanstalk, Lambda Functions, EC2, S3, etc) (diferencial);
- Noções de metodologias ágeis, em especial na concepção de produtos (diferencial);
- Uso de design systems em construção de produtos digitais (diferencial);
- Conhecimento em Design de produtos digitais, principalmente aplicações para visualização de dados (diferencial).

Soft skills que serão valorizadas:

- Foco no resultado;
- Boa comunicação;
- Trabalho em equipe.

## Benefícios

- Plano de saúde
- Plano Odontológico
- Seguro de vida
- VR/VA

## Contratação

CLT a combinar

## Como se candidatar

Fale direto com a nossa Central da Pessoa candidata junto a nossa GabyBot e encontre os desafios mais alinhados ao seu momento profissional! 

Chama no link e conheça a nossa GabyBot:  https://bit.ly/3LZlNEc

Também visite nosso site, conheça essas e muitas outras oportunidades.

https://feeltechrh.com.br/sou-profissional/

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by venturion** [comment]
anuncie em https://devance.com.br 👍

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
