### ISSUE TITLE
[Remoto] Fullstack Developer (Pleno) na Melhor Plano

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6629]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/pessoa-desenvolvedora-fullstack-pleno-remoto-180250874?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>A Melhor Plano</strong> busca pessoa <strong>Fullstack Developer</strong> para compor seu time!</p>
<p>Como o nosso negócio tem crescido muito, buscamos entusiastas de tecnologia, com bons fundamentos de algoritmos e padrões de desenho, que estejam sempre em busca de conhecimento e que consiga contribuir com excelentes insights técnicos para melhorar e otimizar sistemas novos e existentes.</p>
<p><strong>Responsabilidades:</strong></p>
<ul>
<li>Atuar na tomada de decisão em soluções técnicas a partir de uma boa base nos conceitos fundamentais de algoritmos, estrutura de dados e arquitetura de softwares.</li>
<li>Programar um sistema web de ponta a ponta a partir do direcionamento macro de uma pessoa desenvolvedora sênior ou arquiteta;</li>
</ul>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>

## Melhor Plano: 
 <p>Nossa missão aqui no <strong>Melhor Plano</strong> é ajudar milhões a economizar bilhões, encontrando o plano mais adequado ao seu perfil.</p>
<p>Já somos os líderes em comparação de telecom no Brasil, estamos expandindo para produtos financeiros e queremos ser referência também na comparação de outros serviços. Fazemos isso em alinhamento com os nossos valores, sendo transparentes com todos que se relacionam conosco e entregando resultados acima da média.</p><a href='https://coodesh.com/empresas/melhor-plano'>Veja mais no site</a>

 ## Habilidades: 
 - Code Review 
- GIT 
- Node.js 
- React.js 
- REST APIs 
- AdobeXD 
- Typescript
## Local: 
 100% Remoto
## Requisitos: 
 - Compreender bem todos elementos que compõem um sistema e como eles se conectam, desde o banco de dados, passando por APIs e chegando no frontend; 
- Ter uma boa noção e compreensão dos conceitos base do fluxo de desenvolvimento de software; 
- Conhecimento em tecnologias como AWS / EC2 / Lambda / CDNs. 
- Ter alguma experiência com Node.js e React; 
- Conhecer o protocolo HTTP e APIs Rest; 
- Conhecer ferramentas de versionamento como o git e seu uso para revisão de código; 
- Ter experiência na revisão de código.
## Diferenciais: 
 - Conhecimento em padrões de desenho (Design Patterns); 
- Conhecimento em práticas de Clean Code; 
- Conhecimento sobre melhores práticas de programação funcional ou SOLID; 
- Conhecimento de modularização, setup de projetos de integração contínua (CI/CD) e ambientes de teste; 
- Experiência em produtos web para consumidores com milhões de visitas mensais;
## Benefícios: 
 - 🥗 Vale-alimentação/refeição  
- 📚 Vale educação  
- 💻 Ajuda de custo caso use seu próprio computador; 
- 🏡 Auxilío home-office 
- 🏥 Plano de Saúde SulAmerica 100% coberto pela empresa; 
- 👪 Licença maternidade estendida;  
- 🤑 Cashback online em dobro na Méliuz; 
- 💰 Premiação por atingimento de metas coletivas; 
- 🏢 Trabalho 100% remoto (no território brasileiro) e acesso a coworkings no Brasil inteiro;  
- ⏰ Horário flexível.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack Developer (Pleno) na Melhor Plano](https://coodesh.com/vagas/pessoa-desenvolvedora-fullstack-pleno-remoto-180250874?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Full-Stack

**Comment by venturion** [comment]
anuncie em https://devance.com.br 👍

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
