### ISSUE TITLE
[Rio de Janeiro - RJ] Javascript (React.js / Node.js) Developer na BSConsult

### ISSUE THREAD

**Issue by helioricardo** [frontendbr/vagas#663]
## Descrição da vaga

Vaga para dev com foco em front com conhecimentos de backend (nodeJS)

## Local

Escritório, Rio de Janeiro - Centro

## Benefícios

- VR de R$ 19/dia
- VT

#### Diferenciais

Somos flexíveis quanto à linguagem, horário de trabalho, quanto à vestimenta (bermudas permitidas)... E isso é só o começo da conversa... Temos um ótimo ambiente de trabalho.

## Requisitos

**Pessoal:**
- Auto-gerenciamento e proatividade para lidar com demandas e prioridades num ambiente ágil
- Ame código limpo e segue boas práticas de programação
- Estime o tempo do seu próprio trabalho e levante riscos quando solicitado
- Trabalhe de forma integrada com o time de design
- Curioso por natureza e que ame desafios
- Tenha foco no usuário final
- Experiência comprovada em pelo menos 2 projetos ReactJS

**Obrigatórios:**
- Tradução PSDs para HTML sem nenhum problema
- React.JS
- Node.js / Express
- Git
- SASS
- Alto conhecimento em HTML5 e CSS3 - Dããã
- Confortável com linha de comando
- Consumo de APIs RESTful
- Conhecimento de mecanismos de autenticação, como JWT
- BaaS (Parse, Firebase, Graphql Cool...)

**Desejáveis:**
- ES6
- Redux
- WordPress

**Diferenciais (para impressionar):**
- React Native
- Laravel
- Projetar e construir aplicações distribuídas usando arquitetura de micro-serviços
- ElasticSearch
- MongoDB
- Figma

## Contratação

PF ou PJ a combinar

## Nossa empresa

[BSCONSULT - web & mobile dev.](http://www.bsconsult.com.br)

A BS planeja e desenvolve websites, webapps e apps para agências, startups, pequenas e médias empresas, sempre focando no cliente final e na qualidade técnica do projeto.

## Como se candidatar

Por favor envie um email para vagas@bsconsult.com.br com seu CV anexado - enviar no assunto: Vaga REACT+NODE.

**Comment by joordas** [comment]
Ainda está aberta? Bem, de qualquer forma, mandei lá!

**Comment by LFeh** [comment]
Aberto ainda?
