### ISSUE TITLE
[REMOTO] React.js Front-end Developer na CIBERNIX

### ISSUE THREAD

**Issue by alvarogomes** [frontendbr/vagas#6639]
VAGA

Desenvolvedor react para manutenção em aplicação react, class components.
Frameworks: React, Redux-toolkit, axios.

freelance
inicio imediato
com possibilidade de integrar o time para mais projetos.
enviar github e valor/hora e disponibilidade.

Contratação

Freelance por hora = R$ 40 / h.

Nível
Pleno ou Senior

E-mail para se candidatar: [alvaro.brito@cibernix.com](mailto:alvaro.brito@cibernix.com)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
