### ISSUE TITLE
[São Paulo] Estágio Front-end na BovControl 

### ISSUE THREAD

**Issue by FernandaAbreu** [frontendbr/vagas#664]
## Descrição da vaga

O time de desenvolvimento da BovControl está procurando um programador front-end apaixonado por desafios envolvendo programação.
Nós somos uma empresa inovadora que cria mudanças na conexão entre o mundo agrícola e a tecnologia de ponta. Em outras palavras, ajudamos o agricultor a gerenciar melhor seus rebanhos diretamente da ponta dos dedos.
Nossa solução combina a coleta de dados e a análise de dados. Os dados são coletados usando o aplicativo BovControl, que está disponível em todos os dispositivos Android e os dados podem ser analisados através de um dashboard que pode ser acessado a partir de qualquer computador ou dispositivo com a Internet. Buscamos alcançar todos os criadores de gado do planeta e aumentar a eficiência e a produtividade. Combater a fome global através deste método motiva muito nossa equipe.
Buscamos ativamente desenvolvedores capazes, motivados que desejam melhorar a vida no mundo através da codificação. Acredite em mim, isso é possível! Agora é sua chance de codificar um mundo melhor.

## Local

Escritório, São Paulo - Berrini

## Benefícios

-Ambiente descontraído
-Tecnologia de Ponta
-Macbook Pro para você desenvolver
-Ambiente de startup 
-Code Review para te ajudar a evoluir
-Meetups internos sobre tecnologias usadas na empresa
-Trabalhar em conjunto com escritórios nos EUA

## Requisitos

**Obrigatórios:**
- Conseguir se comunicar em inglês
- Ter conhecimento em alguma linguagem de programação orientada a objetos
- Javascript

**Desejáveis:**
- node.js
- VueJs
- react
- firebase
- elasticsearch
- mongoDB
- Git

## Como se candidatar
Siga as instruções da página a seguir https://jobs.bovcontrol.com/mern-intern

**Comment by renanoliveira0** [comment]
Tem remuneração?

**Comment by FernandaAbreu** [comment]
Tem Sim @renanoliveira0

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by FernandaAbreu** [comment]
A vaga ainda está aberta @LFeh !

**Comment by LFeh** [comment]
Boa!

**Comment by Feekira** [comment]
o link para candidatar está fora do ar :/, vaga ainda aberta?

**Comment by joaopdto** [comment]
Ainda está aberta?
