### ISSUE TITLE
[REMOTO] Pessoa Desenvolvedora Front-end @ Letrus

### ISSUE THREAD

**Issue by may-letrus** [frontendbr/vagas#6643]
## Nossa empresa

A Letrus é uma empresa que usa tecnologia para impactar a educação. Oferecemos o primeiro programa de letramento do País que une inteligência artificial com conhecimento linguístico e acompanhamento pedagógico humano. Nosso grande objetivo é gerar impacto social, reduzindo as desigualdades, tornando o letramento universal.

## Nossa área de Tech

Com a missão de construir nosso produto, o nosso time de tech é o responsável por fazer acontecer a nossa aplicação em tempo real. No coração do que fazemos está a área da inteligência artificial que trabalha linguagem - a linguística computacional. A Letrus está na fronteira, no estado da arte da utilização da NLP (Processamento de Linguagem Natural).

🪄E as tecnologias?
No Back-End, você irá encontrar Phyton, Djang, API REST e OOP. Nosso banco de dados é o MySQL.
No nosso Front-End a gente utiliza JavaScript (ES6), ReactJS, Redux, React Native, framework de testes Jest, Cypress.

## Descrição da vaga
A Pessoa Desenvolvedor(a) Front-End terá como missão enfrentar desafios técnicos com o design e a implementação de soluções inovadoras, integradas a um sistema com tecnologias de ponta. Você terá experiências com um time multidisciplinar e promoverá o desenvolvimento de sistemas altamente inovadores, pioneiros no uso do processamento de linguagem natural, além da possibilidade de trilhar carreira como especialista ou em papéis gerenciais.

Principais responsabilidades:

- Desenvolver interfaces web e mobile;
- Implementar, testar e manter funcionalidades da plataforma;
- Interagir de perto com nossos designers, engenheiros de back-end e front-end para garantir a implementação sem erros e rápida de aplicações complexas;
- Resolver problemas técnicos e comunicar claramente soluções aos membros da equipe;
- Criar documentação técnica para equipes internas;
- Realizar revisões de código, com feedback valioso e orientação, para os outros desenvolvedores;
- Pesquisar e comunicar as melhores práticas de front-end.

Terá o desafio de atuar com o maior acervo digital de redações escolares do Brasil, pesquisando e desenvolvendo produtos inovadores, além de aplicar seus conhecimentos na construção de um negócio com impacto transformacional na sociedade.

🔎Quem estamos procurando
- Pessoas desenvolvedoras que são curiosas por natureza, desbravadoras, porque os nossos próximos passos envolvem a inovação, o pensar o que ainda não foi pensado.
- Pessoas colaborativas, que tenham foco no negócio. Afinal, nossa ambição é gigante.

😬O que não vai dar um bom match

- Se você se prende demais nos detalhes e é altamente perfeccionista, provavelmente a Letrus não é o melhor lugar pra você. A gente entende a vontade de entregar tudo no estado da arte, mas, para nós, a necessidade e velocidade do negócio precisam ser consideradas nessa equação também. E sabe como é, né? Melhor a gente contar isso logo agora, porque o match precisa fazer sentido pra você também. :)

✨Aquela boa notícia

- Nosso cenário é de expansão, novos desafios e novos projetos - então o espaço para crescer e se desenvolver com a gente é gigante.

## Local

Temos um escritório em Pinheiro/São Paulo e você poderá ir quando quiser. Mas essa vaga é 100% remota. 

## Requisitos

- Experiência com JavaScript (ES6+) e tecnologias como ReactJS, Redux e React Native;
- Experiência com framework de teste como jest, cypress;
- Experiência com programação assíncrona;

## Benefícios

- Plano de Saúde
- Vale Refeição e Alimentação - R$700,00/mês
- Auxílio Home Office - R$185,00/mês
- Auxilio Educação - R$996,00/ano
- Auxílio Creche - até R$638,00, dependendo da faixa etária, por mês
- Licenças Maternidade (6 meses) e Paternidade (1 mês) estendidas

## Contratação

CLT
Faixa salarial entre 6k e 8,5k

## Como se candidatar

Se interessou? Então #vemserLetrer
Para saber mais sobre a Letrus, [clique aqui](https://letrus.breezy.hr/)
Para se candidatar, [clique aqui](https://letrus.breezy.hr/p/8e962adbcee0-pessoa-desenvolvedora-front-end/apply)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
