### ISSUE TITLE
[Remoto] Front-end Developer na Codeminer42

### ISSUE THREAD

**Issue by iagodahlem** [frontendbr/vagas#6649]
## Nossa empresa

A Codeminer42 é uma butique de software brasileira focada em entregar o melhor valor a seus clientes. Começando suas operações em Setembro de 2011 com os melhores profissionais e desenvolvedores do país.

## Descrição da vaga

Na Codeminer42 você terá a oportunidade de trabalhar com os mais diversos tipos de projetos, com tecnologias variadas e um time de pessoas incríveis que estarão sempre prontas a te ajudar no que você precisar. Incentivamos o diálogo e o compartilhamento de conhecimento e apoiamos o desenvolvimento open-source.

Alguns desafios farão parte dessa trajetória:

- Trabalhar juntamente com times diversificados;
- Buscar novos conhecimentos e tecnologias;
- Não ter medo de se adaptar. Buscamos e incentivamos o aprendizado;
- Saber se comunicar é de extrema importância.

## Local

Remoto ou em algum dos nossos escritórios físicos (listados na página de vagas).

## Requisitos

**Obrigatórios:**

- Pelo menos 1 ano de experiência em desenvolvimento com JavaScript moderno backend (NodeJS) e frontend (React, React Native, Vue ou Angular), ou ter finalizado um curso superior relacionado à area de desenvolvimento em uma faculdade de primeira linha. Nesta denominação não se encaixam bootcamps;
- Experiência com testes automatizados;
- Conhecimentos de bancos de dados SQL;
- Conhecimentos em HTML, CSS e Javascript;
- Interesse em aprimorar suas habilidades através da prática em diferentes projetos, incluindo projetos de clientes e open source;
- Disposição para trabalhar em um ambiente de organização horizontal onde o "sim, senhor" não é aceito e as críticas proativas são sempre bem-vindas;
- **Inglês avançado**. Temos clientes internacionais e uma boa compreensão e conversação são fundamentais. O inglês é de extrema importância e será parte do processo seletivo.
- Para candidatos ainda sem experiência, possuímos um [programa de trainee](https://trainee.codeminer42.com/);

**Diferenciais:**

- Experiência com TypeScript;
- Conhecimentos em UI/UX;
- Conhecimentos em Ruby e Ruby on Rails;
- Conhecimentos em arquitetura de software;
- Experiência com CI/CD;
- Conhecimentos de infra-estrutura. Heroku e AWS são amplamente utilizados no dia a dia.

## Benefícios

- Plano de saúde e dental;
- Vale-refeição;
- Vale-transporte;
- Ambiente de trabalho informal;
- Curso de inglês para aperfeiçoamento;
- Acesso a livros e cursos de programação.
- Reembolso para atividade física;

## Contratação

CLT ou PJ a combinar.

## Como se candidatar

Através do site: https://www.codeminer42.com/careers/front-end-software-engineer?locale=pt-BR

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

#### Alocação

- Alocado
- Remoto

#### Regime

- CLT
- Estágio
- PJ

#### Nível

- Júnior
- Pleno
- Sênior

**Comment by elionaimelo** [comment]
"frontend" kkkkk

**Comment by JonathasGit** [comment]
Opa, li tudo, só não tenho 1 ano de experiência em carteira, estou em buscar de ser Junior. Inglês a melhorar.

**Comment by iagodahlem** [comment]
> Opa, li tudo, só não tenho 1 ano de experiência em carteira, estou em buscar de ser Junior. Inglês a melhorar. 

Opa, não deixe de entrar em contato de qualquer forma. Dependendo da tua experiência já rola se candidatar tranquilo.

**Comment by JonathasGit** [comment]
> > Opa, li tudo, só não tenho 1 ano de experiência em carteira, estou buscando de ser Junior. Inglês a melhorar.
> 
> Opa, não deixe de entrar em contato de qualquer forma. fácil da tua experiência já rola se candidatar tranquilo.

Me candidatei lá, muito obrigado pela força.

**Comment by DevJ-Andrade** [comment]
Opa me candidatei lá também. Não tenho 1 ano de experiência porém possuo inglês avançado. Espero que de tudo certo

**Comment by josuelustosadev** [comment]
Olá, finalizei a facul final de 2021, juntamente o estágio de 1 ano e 8 meses em desenvolvimento de software web. Estou estudando vue.js há quase um ano desde que tive contato com o framework nesse estágio que acabei de citar.

Não tenho familiaridade com Ruby e Ruby on Rails, mas possuo conhecimento em node.js, ux e heroku, além de está aprimorando meu inglês na parte de conversação.

Estou disposto a topar qualquer desafio e aberto às oportunidades :)

**Comment by JonathasGit** [comment]
Obrigado por me enviarem e-mail, no momento não em trainee, só mês de Junho.

**Comment by anabeatrizzz** [comment]
Na opção de escritório, devo selecionar "Outro" se pretendo trabalhar remotamente? E o que posso escrever no campo mensagem?

**Comment by iagodahlem** [comment]
> Na opção de escritório, devo selecionar "Outro" se pretendo trabalhar remotamente? E o que posso escrever no campo mensagem?

Isso mesmo, pode selecionar "Outro" e descrever na mensagem que você deseja remoto  e legal citar sua cidade atual e experiência.

**Comment by FelipeHFO** [comment]
Me candidatei lá! Espero que possamos trabalhar juntos!

**Comment by gustta03** [comment]
Me candidatei e me responderam com um "sem formação"

**Comment by iagodahlem** [comment]
> Me candidatei e me responderam com um "sem formação"

@gustta03 isso foi um erro de comunicação interna. Pedimos desculpas pelo mal entendido.

**Comment by WolfgangVing** [comment]
Posso me canditadar para vaga de estágio mesmo não tendo experiência ? Meus estudos vem sendo focado no ecossistema Javascript, tenho até um registro de um package na npm á 3 semanas. Também estou fazendo meu portfolio em React-TS, mas ainda não tive oportunidade de primeiro emprego.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
