### ISSUE TITLE
[São Paulo] Front-End Developer na Shawee

### ISSUE THREAD

**Issue by wendelnascimento** [frontendbr/vagas#665]
## Descrição da vaga

Procuramos um dev front-end que queira participar da próxima etapa da Shawee, um sistema para organizar hackathons em ao redor do mundo. Nosso maior desafio hoje é criar uma arquitetura internacionalizável e escalável e customizável para a plataforma atual.

## Local

Escritório, São Paulo - Barra Funda (Próximo ao metrô).

## Benefícios

- Ambiente de startup (afinal, somos uma!)
- Time viciado em aprendizado e share de conhecimento
- Presença nos melhores e maiores hackathons do Brasil, logo logo do mundo
- Trabalhe junto com vários líderes de comunidades, recebemos e vamos em muitos eventos da comunidade

## Requisitos

**Obrigatórios:**
- Experiência com React
- Boas noções de UX
- Inglês (conseguindo conversar bem já basta)

**Desejáveis:**
- Conhecimentos de GraphQL
- Ter trabalhado com react-apollo

**Diferenciais:**
- Presença na comunidade
- Ter trabalhado com bibliotecas de internacionalização no React

## Contratação

PJ a combinar

## Nossa empresa

Nascida dentro da Horizon Four, a Shawee é uma plataforma de organização de hackathons. Cuidamos desde a fase de planejamento do evento, sua execução e até mesmo o pós hackathon.

## Como se candidatar

Por favor envie um email para wendel.nascimento@shawee.io com seu CV anexado - enviar no assunto: Vaga Front-End

**Comment by phsantiago** [comment]
Já trabalhei com o @wendelnascimento e com outros membros da Shawee! O pessoal é bom mesmo!

**Comment by wendelnascimento** [comment]
@phsantiago nosso time é só amor!

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by wendelnascimento** [comment]
@LFeh não, fechando a issue!
