### ISSUE TITLE
[Remote] IOS React Native Senior Developer  @ International opportunity

### ISSUE THREAD

**Issue by TacianySouza** [frontendbr/vagas#6650]
Company Details:
Real estate technology client based in Toronto, Canada, founded in 2018 and recognized in 2021 in the Great Places to Work Canada program!

Desirable requirement:
Help improve the development experience through documentation, process improvements, insightful introduction of new technologies, and guidance from other developers.

Responsibilities:
Build apps for leading mobile workflows that solve problems for users in your neighborhood and home discovery process
Combine user-centric features and long-term business goals – influence the course of our product through the Lean UX style team's product design.
Take a lead role in technical design and implement product design iterations and experiments on mobile platforms
You will be a technical contributor on a team with several teammates with backgrounds in complementary areas. You will bring experience with a variety of mobile technologies and work with systems through API design and refinement.

Technical requirements:
- Fluent English
- + 5 years developing with React Native.
- Experience in an iOS development environment
- Competence in designing effective APIs for use in a mobile context

Application: https://forms.gle/scuwnAw48hv7qR9JA

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
