### ISSUE TITLE
[São Paulo] Angular Front-end Developer na Ágile Couch

### ISSUE THREAD

**Issue by lucasmpm** [frontendbr/vagas#6653]
## Nossa empresa
Ágile Couch

## Descrição da vaga

Desenvolvedores Front End Angular - Sem inglês
Plenos (10k a 12k BRL) e Seniors (13k a 15k BRL)

# # O que precisa?
Conhecimento de pelo menos 2 anos com Angular

 
o   WebComponent (conhecimento obrigatório)
 
o   Versão angular 8+
 
o   Versionamento de código (Git, bitbucket)
 
o   Conhecimento e experiência na construção de serviços RESTful;
 
o   Conhecimento de Domain Driven Design;
 
o   Conhecimento de Arquitetura Distribuída;
 
o   Conhecimento de Arquitetura Orientada a Eventos e Microservices;
 
o   Conhecimento de soluções de banco de dados relacionais e não relacionais;
 
o   Conhecimento de Cloud Computing, especialmente Azure e AWS;
 
o   Conhecimento de GitFlow e políticas de gestão de configuração;
 
o   Conhecimento de Testes automatizados, Integração Contínua e Entrega Contínua;
 
o   Conhecimento de Soluções de API Gateway;
 
o   Devops (padrões SONAR, testes unitários, análise de erros em esteiras cloudbees)
 
o   Conhecimento em métodos ágeis e processos de desenvolvimento de software;
 
o   Conhecimento de técnicas eficazes de logging, troubleshooting e monitoramento.
 
o   Perfil proativo para resolução de problemas e comunicação com demais áreas;

Empresa
Atuar num grande banco por uma consultoria internacional.

## Local

Escitório, São Paulo - Interlagos

## Requisitos

**Obrigatórios:**
 - Minimo 2 anos de experiência com Angular
 - Java,  Kafka, Elastic, RabbitMQ 
 
## Benefícios

 - R$ 1.5000,00 cartão Flex mensal.
 - Assistência Médica;
 - Seguro de vida;
 - Assistência Odontológica;
 - Academia
 - Seguro de vida

## Contratação

CLT
Plenos: R$ 10 mil a R$ 12 mil
Seniors: R$ 13 mil a R$ 15 mil

## Como se candidatar

Por favor envie um email para lucas.maciel@hunterhunter.com.br com seu CV anexado - enviar no assunto: Vaga Angular. O contato também pode ser feito por WhatsApp / Telegram:  27 9 9754 5497 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo. 
E-mail para contato em caso de não haver resposta: lucas.maciel@hunterhunter.com.br

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
