### ISSUE TITLE
[Remoto] Fullstack Engineer  na RBR DIGITAL LTDA

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6654]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/full-stack-engineer-231845433?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>A RBR DIGITAL</strong> busca pessoa <strong>Fullstack Engineer</strong> para compor seu time!</p>
<p>Somos uma agência da web centrada no desempenho que se preocupa em entender o seu negócio e, em seguida, criar uma solução personalizada para ajudar a atender às suas necessidades.&nbsp;</p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>

## RBR DIGITAL LTDA: 
 <p>We’re a performance-centered web agency that cares about understanding your business, then crafting a custom solution to help meet your needs. We approach every project with a performance mindset, ensuring that your project performs for you, your user, and your team.</p>
</p>

 ## Habilidades: 
 - React Native 
- React.js 
- MongoDB 
- Node.js 
- Express.js 
- Javascript/Typescript 
- REST APIs
## Local: 
 100% Remoto
## Requisitos: 
 - Conhecimento sólido de Javascript, ReactJS, React Native, NodeJS + Express; 
- Conhecimento em TypeScript; 
- Conhecimento em banco de dados não-relacionais (MongoDB); 
- Conhecimento sólido em segurança de APIs (auth tokens, Jwt, rotas, middleware); 
- Conhecimento sólido do funcionamento de APIs REST;
## Diferenciais: 
 - Experiência com desenvolvimento orientado a Testes (TDD, BDD) 
- Conhecimentos em integração com API de autenticação auth0; 
- Experiência com a biblioteca NativeBase;

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack Engineer  na RBR DIGITAL LTDA](https://coodesh.com/vagas/full-stack-engineer-231845433?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Mobile

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
