### ISSUE TITLE
[Remote] Front-end Developer na Feel Tech

### ISSUE THREAD

**Issue by GiuButtenbender** [frontendbr/vagas#6656]
## Nossa empresa

Feel Tech é uma consultoria de pesquisa e desenvolvimento de pessoas com foco em inovação, E COM MUITO AMOR pelo que faz!

Estamos com uma oportunidade INCRÍVEL para atuar no time de outsourcing para um cliente focado na área de pesquisa, inovação e desenvolvimento de novas tecnologias. Atuando com tecnologias de ponta de mercado na área de front-end

## Descrição da vaga

Exemplo: Projeto bazinga em NodeJS, etc.

## Local

Pessoa Especialista Front End para atuar em uma empresa com ambiente colaborativa e aberto as pessoas. Você realizará constantemente a construção e melhoria de um produto, portanto viverá na prática todas as etapas do ciclo de desenvolvimento de um novo produto.

## Requisitos

Experiência em Front-end React/Next.js;
Experiência com TypeScript;
Experiência com GraphQL;
Experiência com Git e Versionamento de Código;
Experiência com Metodologias Ágeis;
Conhecimento em arquitetura BFF (Back-end for Front-end) (diferencial);
Conhecimento de arquitetura Headless (diferencial);
Conhecimento em Esteiras/Pipelines de Deploy (diferencial);
Conhecimento em Cloud (diferencial);
Conhecimento em Arquitetura de Microsserviços (diferencial).

Soft skills que serão valorizadas:

Iniciativa;
Trabalho em equipe;
Entusiasmo em aprender e ensinar.

## Contratação

Cooperado a combinar!

## Como se candidatar

Aqui na Feel Tech temos um processo seletivo ágil, sem burocracias para ajudar você a conhecer as oportunidades mais interessantes para o seu perfil!

Fale direto com a nossa Central da Pessoa candidata e encontre os desafios mais alinhados ao seu momento profissional!

Chama no WhatsApp e conheça a nossa GabyBot: 📲 (51) 9 9018-0935
Link: https://bit.ly/3LZlNEc

Também visite nosso site, conheça essas e muitas outras oportunidades.

(https://feeltechrh.com.br/

#### Alocação
- Remoto

#### Regime
- Cooperado
- PJ

#### Nível
- Especialista

**Comment by JonathasGit** [comment]
Visitei o site e gostei das vagas

**Comment by GiuButtenbender** [comment]
> Visitei o site e gostei das vagas

Opa! Se tiver interesse em alguma vaguinha ou quiser ficar em contato para futuros desafios! Chama ali no link :)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
