### ISSUE TITLE
[REMOTO] Front-end Developer

### ISSUE THREAD

**Issue by DHWork9** [frontendbr/vagas#6657]
**Requisitos necessários:**

- Experiência com GIT, Linguagem Phyton, CSS, SCSS, ReactJS ou Angular;

- Inglês será um grande diferencial (não obrigatório);

Buscamos alguém para fazer parte de uma equipe que está em constante desenvolvimento no mundo da tecnologia!  

Vaga 100% remota + Regime de contratação PJ com direito a férias 

VAGA NÍVEL PLENO

Interessados devem encaminhar currículos no site: https://jobs.recrutei.com.br/dh-work/vacancy/21415-desenvolvedor-front-end-pl

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
