### ISSUE TITLE
[Remoto] Front-end Developer na Mercafacil

### ISSUE THREAD

**Issue by EBMerca** [frontendbr/vagas#6658]
> 

## Nossa empresa

 A Mercafacil foi feita para fazer a diferença na transformação do varejo.
Temos certeza que podemos fazer isso quando tornamos possível entender as individualidades de cada um que estão no comportamento de compra e traduzir isso em conversão de vendas para o varejista.

Vamos muito além de sistemas, somos uma empresa feita por pessoas e para pessoas, que utiliza a tecnologia como um meio de sempre melhorar a experiência de consumo e diariamente aperfeiçoar o varejo de maneira criativa e funcional.

Ainda temos muito a fazer para melhorar a experiência do consumidor do varejo, e você pode fazer parte dessa história. Vem fazer história com a gente!

## Descrição da vaga

Seu Dia a Dia será:

Como Desenvolvedor (a) Front End sua missão será participar do desenvolvimento das interfaces Web e de todas as aplicações e produtos da Mercafacil, irá desenvolver componentes reutilizáveis com testes automatizados para garantir a estabilidade e reusabilidade do sistema. Deverá também participar ativamente nas decisões técnicas e de designer sobre ferramentas e abordagens que visam otimizar a performance do sistema e a experiência do usuário. Venha transformar o varejo conosco!

Algumas de suas responsabilidades:

Desenvolvimento em VueJS;
Desenvolvimento em React e React Native Web;
Desenvolvimento utilizando Apollo para interagir com os backends em GraphQL;
Desenvolvimento de componentes reutilizáveis e integrados com ferramentas como o Storybook;
Desenvolvimento de testes automatizados para os componentes/telas;
Manutenção, evolução e otimização das telas atuais de todos os produtos da Mercafacil.

## Local

 Remoto 

## Requisitos

**Obrigatórios:**
Experiência em desenvolvimento de SPAs em VueJS ou React/React Native;
Experiência em desenvolvimento de componentes reutilizáveis;
Experiência em testes automatizados.

**Desejáveis:**
Experiência com GraphQL
Experiência com arquitetura de microfrontend
Experiência com bibliotecas de componentes compartilhados em StoryBook
﻿Inglês intermediário

## Benefícios

🩺Saúde em primeiro lugar!

Assistência médica Sulamérica para você e seus dependentes 100% custeados pela gente;
Assistência odontológica para você e seus dependentes 100% custeado pela gente;
Seguro de vida.
Gympass
Licença maternidade e paternidade estendida 

😉Acreditamos que cada pessoa é única!

Benefícios flexíveis com o cartão Caju | VR/VA, mobilidade, educação e Cultura;
Birthday-off para você comemorar seu niver.
Day-off para mudança de casa
 
👩‍💻Respeitamos seu jeito de trabalhar!

Remote First: home office aqui é realidade!
No Dress Code. 

🚀Queremos que sua carreira voe!

Avaliação de Desempenho duas vezes ao ano;
Convênios corporativos;
Cultura de Feedback e 1:1 frequentes.
Universidade Corporativa

## Contratação

CLT

## Como se candidatar

Por favor envie um email para people.mf@mercafacil.com com seu CV anexado e um link para seu Github - enviar no assunto: Vaga Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível

- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
