### ISSUE TITLE
[REMOTO] Sênior Javascript +Canvas Front-end Dev na Onesight

### ISSUE THREAD

**Issue by kamiarc** [frontendbr/vagas#6662]
## Nossa empresa

A Onesight é uma multi-nacional com foco em desenvolvimento de tecnologias disruptivas e bleeding edge, atuamos com diversos clientes em múltiplos mercados e tecnologias.
No Brasil nossas atividades se concentram em outsourcing, e-commerces e plataformas customizadas.

## Descrição da vaga

Temos 1 vaga para sênior aberta, o foco inicial é trabalhar com projetos avançados em JS, principalmente CANVAS, image e edge detection 

## Local
Remoto

## Requisitos

**Obrigatórios:**
- Avançado: Javascript
- Canvas
- Image/edge detection
- CSS3
- HTML5

**Desejáveis:**
- Conhecimento em design e ux

**Diferenciais:**
- Ter algum projeto exemplo em Canvas com detecção de parte da imagem
- Inglês fluente

## Contratação
PJ

## Como se candidatar
Por favor envie um email para trampos@onesight.com.br com seu CV anexado - enviar no assunto: SENIOR Canvas
**Importante**: Enviar: Nível, pretensão salarial e disponibilidade para início.
_Enviar também Github/lab com projetos realizados ou links de exemplos caso tenha algum online._

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 7 dias para devs aprovados ao menos para a segunda fase.
E-mail para contato em caso de não haver resposta: responder o e-mail do teste

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
