### ISSUE TITLE
[Remoto] Software Engineer Front-End - Sr na Birdie

### ISSUE THREAD

**Issue by DaanMoura** [frontendbr/vagas#6664]
## Nossa empresa

A [Birdie](https://birdie.ai/) é uma Product Intelligence Cloud que ajuda empresas a inovarem com mais velocidade e eficácia, gerando insights de mercado e produto em tempo real a partir da análise semântica de milhões de fontes de dados sobre consumidores e concorrência, permitindo que times de produto e estratégia desenvolvam, lancem e vendam produtos mais alinhados com as expectativas dos consumidores.

A empresa foi criada em 2018 e é sediada no Vale do Silício, possui um time distribuído entre diversos estados do Brasil e Estados Unidos e atende a clientes como HP, Microsoft e Midea. A Birdie foi listada pela Crunchbase como uma “Startup to Watch” em 2020 e pela Techcrunch como uma das “boas novidades” no cenário de startups. Fomos também selecionados para o programa de Growth da 500 Startups em 2020 e para o Programa Scale-up Endeavor B2B em 2021.

Estamos orgulhosos de estar construindo uma empresa global com alma brasileira, como gostamos de enfatizar em nossos valores:

- Colaboração: Somos mais fortes como um time;
- Paixão: Gostamos e damos melhor no que fazemos;
- Accountability: Somos donos do que fazemos e temos foco em gerar impacto;
- Coragem: Aceitamos e abraçamos desafios;
- Diversidade: Valorizamos e respeitamos diferentes opiniões e pessoas.

## Descrição da vaga

Buscamos uma pessoa Software Engineer para integrar o time e ter acesso a diferentes projetos web utilizando conhecimentos em frontend e UI/UX.

Você será responsável por desenvolver e manter funcionalidades do produto, intermediando a camada de dados com a camada de aplicação da maneira mais eficiente.

Trabalhamos diariamente com tecnologia de ponta voltadas a criação de interfaces, utilizando como por exemplo Vue.js, React, TypeScript e Node.js.

Suas principais responsabilidades serão:
- Desenvolver módulos e telas para o produto interno e externo;
- Monitorar os processos que nutrem a aplicação;
- Mentorar o time técnico em decisões de tecnologias e metodologias utilizadas;
- Testar e corrigir erros ou outros problemas de codificação.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Formação em Ciência da Computação, Engenharia da Computação, Sistema de Informação, Estatística ou algum outro curso relacionado;
- Experiência com HTML/CSS/Javascript/Typescript;
- Experiência com Vue.js/React e layouts responsivos;
- Conhecimento em UX/UI;
- Experiência com CI/CD;
- Conhecimento em Design Patterns
- Conhecimento em metodologia Ágil;

**Desejáveis:**
- Experiência com ambientes em Cloud AWS/Azure;
- Inglês intermediário.

## Benefícios

- Regime de contratação CLT;
- Vale Refeição/Alimentação flexível – Swile Food;
- Ajuda com custos pessoais – Swile Utilities;
- Plano de saúde;
- Plano odontológico;
- Seguro de vida;
- Horário de trabalho flexível
- Trabalho remoto permanente – Anywhere office
- Ambiente descontraído, de alto crescimento, com foco em resultado e inovação;
- Para o home office:
  - Auxílio home office + computador
- Para o bem estar:
  - Mindfulness Sessions
  - Desconto na plataforma de saúde emocional Zenklub
  - Desconto na rede de academias TotalPass
- Possibilidade de Intercâmbio para o Vale do Silício

## Contratação

Regime de contratação CLT

## Como se candidatar

Preencha [este formulário](https://joinbirdie.gupy.io/job/eyJqb2JJZCI6MTYxMjU4Niwic291cmNlIjoiZ3VweV9wdWJsaWNfcGFnZSJ9?jobBoardSource=gupy_public_page) para se candidatar e o nosso time irá entrar em contato.

## Tempo médio de feedbacks

Usualmente dura em média 30-40 dias, considerando desde a aplicação até a finalização da avaliação. Passando pelas seguintes etapas:
- Triagem dos formulários de aplicação
- Entrevista com a Mari, nossa Tech Recruiter
- Entrevista com a liderança + convidados do time
- Entrevista final com o nosso CTO
- Proposta

E-mail para contato em caso de não haver resposta: mariana.nastri@birdie.ai

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
