### ISSUE TITLE
[Remoto]  Full Stack Developer na Aoop

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6666]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-full-stack-193738931?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>Aoop</strong> busca pessoa <strong>Fullstack Developer</strong> para compor seu time!</p>
<p>Somos especialistas em Transformação Digital. Nos tornamos autoridade e temos a liderança em consultoria e implementação  na  plataforma SERVICENOW, soluções que estão revolucionando os processos e serviços digitais nas empresas ao redor do mundo, por meio de uma experiência totalmente intuitiva e de autoconsumo.</p>
<p><strong>Responsabilidades:</strong></p>
<ul>
<li>Desenvolver e Automatizar processos e serviços de negócios na plataforma Servicenow.</li>
<li>Desenvolver aplicações com HTML5, CSS, JavaScript / Angular JS entre outras linguagens.</li>
<li>Utilizar métodos ágeis para desenvolvimento no dia a dia.</li>
</ul>

## Aoop: 
 <p>Somos especialistas em Transformação Digital.</p>
<p>Nos tornamos autoridade e temos a liderança em consultoria e implementação  na  plataforma SERVICENOW, soluções que estão revolucionando os processos e serviços digitais nas empresas ao redor do mundo, por meio de uma experiência totalmente intuitiva e de autoconsumo.</p><a href='https://coodesh.com/empresas/aoop'>Veja mais no site</a>

 ## Habilidades: 
 - Calabash 
- Fortran 
- Linguagem C
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência comprovada em Desenvolvimento de Sistemas. 
- Experiência em desenvolvimento com: HTML5, CSS, JavaScript / Angular JS. 
- Inglês intermediário.
## Diferenciais: 
 - Inglês fluente. 
- Experiência em metodologia Agile (SCRUM).
## Benefícios: 
 - Vale refeição / Vale Alimentação. 
- Seguro Saúde - sem coparticipação e 100% custeado. 
- Plano Odontológico. 
- Auxílio Home Office. 
- Por aqui #temqueserfeliz, então focamos em apoiar a sua saúde mental e bem estar - através de nossos benefícios com o Zenklub 
- Anywhere Office (100% remoto).
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [ Full Stack Developer na Aoop](https://coodesh.com/vagas/desenvolvedor-full-stack-193738931?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
