### ISSUE TITLE
[Remoto] Front-end Developer na @Projuris

### ISSUE THREAD

**Issue by vanessaliebl** [frontendbr/vagas#6667]
## Nossa empresa

Nascemos para fazer a diferença na vida dos profissionais que precisam lidar com burocracia em suas rotinas.

Somente com tecnologia de ponta e proximidade é que podemos, verdadeiramente, concretizar nosso propósito ousado e desafiador.

## Descrição da vaga

Você vai atuar em um projeto de migração de um produto legado para uma stack atual, com alguns desafios interessantes no processo. 
O produto legado não é SaaS nem multitenant e o novo é. Todas as decisões técnicas foram e estão sendo planejadas durante o projeto para que essa mudança seja possível.
A base de clientes do produto legado não é compartilhada com a nova versão do produto.
Os processos de desenvolvimento e produto são ágeis e há colaboração entre as áreas e stakeholders para que o roadmap esteja sempre priorizado de forma a entregar valor aos usuários.
Reservamos capacidade para manter a qualidade do produto enquanto o projeto avança. As equipes cuidam do que entregam, atuando no seu backlog de bugs e débitos técnicos com tranquilidade. Também possuímos um cronograma recorrente de atualização de tecnologias.
Os times são remotos e possuímos uma cultura remote first. Promovemos a comunicação assíncrona e poucas reuniões, que são focadas na tomada de decisão.

Vamos crescer juntos?

## Local

Remoto

## Requisitos

Como pessoa desenvolvedora Front End, esperamos que você:

Participe das cerimônias do time (planning, review, retrospectiva)
Realize a estimativa após o entendimento das funcionalidades;
Construa as funcionalidades descritas nas épicas e histórias;
Crie estruturas para atender novas funcionalidades de forma otimizada e organizada;
Corrija bugs apontados pelos clientes ou pela equipe de qualidade
Realize testes da funcionalidade criada, garantindo assim sua qualidade;
Insira os códigos criados no repositório de armazenamento de códigos fonte;
Siga os procedimentos internos na ferramenta de controle de projetos/chamados (Jira);
Crie códigos limpo e bem estruturado;
REQUISITOS E QUALIFICAÇÕES
Para se juntar a nós, é importante :

 

 

Desenvolver códigos elegantes, estáveis, confiáveis e, não menos importante, fáceis de manter. Queremos código limpo, que funcione bem e bem testado;
Desenvolver códigos e soluções sempre pensando em eficiência, escalabilidade e estabilidade. Queremos garantir nosso crescimento super acelerado;
Conhecimento profundo em algum desses frameworks JavaScript: Angular2+, Vue, ou Ember. Utilizamos Angular v11 e estamos atualmente atualizando para v13;
Conhecimento em CSS e pré-processadores como LESS, Sass ou PostCSS; Utilizamos Sass.
Conhecimento em arquitetura front-end, usabilidade, performance e testabilidade;
Desenvolver testes automatizados e fazer code reviews pois fazemos vários deploys por dia e queremos sempre garantir a máxima qualidade das nossas entregas; Utilizamos Jest para testes unitários e Cypress para testes e2e.
Conhecimento em TDD, Clean Code e Design Patterns.
Trabalhamos com velocidade e autonomia no dia-a-dia.
Se sentir confortável realizando pair programming e gostar de compartilhar conhecimento.
Conhecimento em Single Page Apps integrando com apis RESTful

Você vai se diferenciar se conhecer:

Aplicações orientadas a componentes. Utilizamos atomic design.
Conhecimento em algum monorepo: TurboRepo, Nx; Utilizamos Nx.
Ferramentas de build de frontend. Utilizamos Webpack em conjunto com Nx.
Metodologias ágeis e excelente comunicação
Utilizar conceitos do Jira, Epic, História, Tarefa, etc.
Conhecimento em gitflow
Inglês básico (leitura e escrita)

## Benefícios

Para isso contamos com diversos benefícios como: 

🥪 Vale refeição valor de R$520,00 (sem custo)
🩺 Plano de saúde Unimed ou Bradesco Nacional adesão imediata sem custo ao colaborador;
🦷 Plano odontológico;
✔Convênio Farmácia;
💻Acessos a curso da Udemy;
💰PPR;
📚Bolsa de estudos (Para graduação, Pós graduação e Idiomas);
✔Seguro de vida; 

- ...

## Contratação

CLT

## Como se candidatar

projuris.com.br/talentos

#### Alocação

- Remoto

#### Regime
- CLT

#### Nível

- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
