### ISSUE TITLE
[Hibrido / Belo Horizonte, Brazil] Fullstack Developer na Onfly

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6668]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/php-laravel-pleno-2-020956227?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>A Onfly </strong>busca pessoa <strong>Fullstack Developer</strong> para compor seu time!</p>
<p>Somos um dos melhores lugares para se trabalhar no Brasil (inclusive somos uma das empresas do Great Place to work)!</p>
<p>Para que alcancemos a meta de crescer exponencialmente, buscamos pessoas que sejam apaixonadas por tecnologia, que desejam estar em um time de alta performance e que queiram crescer muuuuito.</p>
<p>Para a vaga de Fullstack Developer, buscamos uma pessoa que vá ficar a frente de um de nossos squads de alta performance, será ponto central no gerenciamento e organização das tarefas e que irá impactar de forma central no time.</p>
<p></p>
<p></p>
<p></p>

## Onfly: 
 <p>A Onfly oferece uma solução "all-in-one" com gestão de viagens (aéreo, hotel e carros), despesas e cartão corporativo em uma única plataforma digital. Com intensivo uso de tecnologia e uma boa dose de calor humano, elevamos ao máximo a gestão de viagens das empresas, trazendo conforto e produtividade para os colaboradores e segurança e economia para as empresas.  Simplifique, vá de Onfly!</p>
</p>

 ## Habilidades: 
 - PHP 
- Laravel 
- MySQL 
- Vue.js
## Local: 
 Belo Horizonte, Brazil
## Requisitos: 
 - PHP 7 
- Conhecimento avançado em orientação à objetos 
- Frameworks Laravel 
- Armazenamento de dados em MySQL 
- Atenção para qualidade de código e design patterns 
- Experiência em Cloud Computing (Azure, AWS, GCP e etc) 
- Versionamento de códigos utilizando Git 
- Experiência em API rest 
- Experiência com bibliotecas front-end (Vue) 
- Experiência com metodologias de desenvolvimento ágil Scrum ou Kanban
## Diferenciais: 
 - Experiência com Frameworks de Node.js (Ex: NestJS, Restify ou similares) 
- Experiência com criação de bibliotecas 
- Inglês avançado
## Benefícios: 
 - Horário flexível 
- Plano de Saúde Bradesco, sem coparticipação (por nossa conta) 
- Cartão de alimentação e transporte flexível (gaste como quiser, ok?) 
- No dress code - Bermuda e chinelo? Sem problemas 
- DayOff Birthday 
- Pagamos Metade da sua terapia on-line (através do Zenklub) 
- É fitness? Pagamos metade da sua academia (através do TotalPass) 
- Bolsa de 50% para estudos de idiomas
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack Developer na Onfly](https://coodesh.com/vagas/php-laravel-pleno-2-020956227?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
