### ISSUE TITLE
[RECIFE] Front-end Developer na Nutcache

### ISSUE THREAD

**Issue by SahRecruiter** [frontendbr/vagas#6669]
## Nossa empresa:

Nutcache é um software de produtividade orientado para negócios que gerencia qualquer tipo de projeto do início ao fim. Isso inclui a estimativa inicial, orçamento do projeto, controle de tempo, gerenciamento de despesas e faturamento.
O time de desenvolvedores trabalha com a criação e aprimoramento de funcionalidades para o nosso software.
Nosso compromisso com a valorização da diversidade está presente em todas as nossas oportunidades. Acreditamos no potencial humano para desenvolver talentos e gerar inovação para
nossos clientes.

## Descrição da vaga
Estamos em busca de pessoas responsáveis pelo desenvolvimento full stack, solucionando bugs encontrados em fase de desenvolvimento e defeitos em produção que envolvam aspectos
funcionais. Procuramos fazer pequenas entregas constantes e com qualidade, seguindo os preceitos de
gestão ágil e da ferramenta Scrum.

## Local

Remoto ou Escritório, [PERNAMBUCO], [RECIFE], [BAIRRO DE BOA VIAGEM]

## Requisitos

**Obrigatórios:**
● Formação em Ciência da computação ou cursos relacionados;
● Experiência em React Js e Redux;
● Experiência em HTML, CSS e Javascript;
● Experiência com desenvolvimento de aplicações em ASP.NET com C# e SQL;
● Inglês Intermediário ou Avançado;
● Entendimento de métodos ágeis e ferramentas Scrum e Kanban.

**Desejáveis:**
● Experiência com ferramentas como Git e Visual Studio Code;
● Noções básicas de UI/UX;
● Experiência com React Hooks;
● Experiência na liderança de times.

## Benefícios
● Plano de Saúde - Bradesco Saúde Top Nacional (100% custeado pela empresa);
● Plano Odontológico - Bradesco Odonto (100% custeado pela empresa);
● Seguro de vida - Prudential;
● Benefício de bem-estar físico e mental - Gympass;
● Vale refeição/alimentação - Flash benefícios flexíveis (Bandeira Mastercard);
● Gratificação por indicação de novos colaboradores;
● Material de trabalho completo;
● Day off no mês de aniversário;
● Horário e formato flexível;
● Auxílio idiomas;
● Auxílios de capacitação técnica;
● Clima colaborativo e flexível.

## Contratação

● CLT

## Como se candidatar

Por favor, envie um email para ssilvappacheco@gmail.com com seu CV anexado - enviar no assunto: Vaga Front-End Developer.

## Tempo médio de feedbacks

Costumamos finalizar o processo inteiro no prazo de 2 semanas. Prazo médio para feedbacks entre um processo e outro: 1 ou 2 dias.

#### Alocação
● Alocado
● Remoto

#### Nível
● ****Pleno (III ou IV)
● Sênior****

****OBS. Estamos priorizando profissionais de Pernambuco, Alagoas, Paraíba e Rio Grande do Norte :)
O local físico se encontra em Recife/PE.****

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by SahRecruiter** [comment]
Obrigada pelo aviso.

Att.
Sabrina Pacheco

Enviado do meu Samsung Mobile da Claro
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
