### ISSUE TITLE
[Florianópolis, SC] Desenvolvedor(a) Front-End

### ISSUE THREAD

**Issue by ConsultoriaContato** [frontendbr/vagas#667]
**Atividade da Vaga:**
Desenvolver Interface Web (Front-End) em Java com foco em e-commerce.

**Requisitos da Vaga:**
- Experiência em HTML, CSS e JavaScript;
- Conhecimento da biblioteca jQuery;
- Conhecimento em framework Bootstrap;
- Conhecimento em grid e design responsivo;
- Utilização de padrões e boas práticas para desenvolvimento.

**Conhecimentos desejáveis:**
- Sass ou Less;
- Familiaridade com sistemas de controle de versão (SVN e Git);
- Plataforma de e-commerce VTEX.

**Sobre a empresa:**
A Avanti! é uma agência especializada em e-commerce e em Marketing Digital que possui escritórios em Campinas, Florianópolis e São Paulo. Reúne profissionais das áreas de Tecnologia e Marketing preparados para contribuir na entrada e permanência do cliente no mercado digital.

**Site da empresa:** http://www.penseavanti.com.br

**Como candidatar-se:**
Cadastrar CV em www.selecaodevagas.com.br e candidatar-se à vaga!

**Comment by davidcostadev** [comment]
Essa cara abriu um monte de vagas, é trolagem Bloqueia esse cara

**Comment by LFeh** [comment]
Essa foi a única de front e mesmo assim super estranha.
