### ISSUE TITLE
[Hibrido / Belo Horizonte] Frontend Javascript Developer na BeTruck

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6670]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-javascript-developer-122340840?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>BeTruck</strong> busca pessoa <strong>Frontend Javascript Developer</strong> para compor seu time!</p>
<p>A BeTRuck é uma empresa especializada em aplicação de tecnologias para o segmento logístico de transporte. Atuamos de forma personalizada, alinhada com as demandas de cada cliente, focando sempre nos objetivos a serem alcançados.</p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>

## BeTruck: 
 <p>• Colaboramos muito, uns com os outros. Troca de conhecimento é o nosso lema, e geramos crescimento e inovação;</p>
<p>• Nosso time é dinâmico e ágil;</p><a href='https://coodesh.com/empresas/betruck'>Veja mais no site</a>

 ## Habilidades: 
 - SQL 
- PostgreSQL 
- HTML 
- CSS 
- React.js
## Local: 
 Belo Horizonte
## Requisitos: 
 - Conhecimento e/ou experiência em HTML, CSS, Javascript 
- Conhecimento e/ou experiência em react.js 
- Conhecimento PorgreSQL 
- Conhecimento SCRUM 
- Bom relacionamento interpessoal e comunicação 
- Conhecimento material UI
## Diferenciais: 
 - Formação em Ciência da Computação, Sistemas de Informação ou Engenharias; 
- Conhecimento em node.js e nest.js
## Benefícios: 
 - Vale Alimentação
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Javascript Developer na BeTruck](https://coodesh.com/vagas/frontend-javascript-developer-122340840?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
