### ISSUE TITLE
VAGA FECHADA [Remoto] Front-end Developer Web e DevOps Pleno e PJ na WDS WEDO Services 

### ISSUE THREAD

**Issue by larissabazzo** [frontendbr/vagas#6675]
## Nossa empresa

Com mais de 7 anos no mercado, a WEDO Services Informática fornece soluções completas para a automação de processos de TI, acompanhando a demanda dos principais segmentos do mercado na implantação de soluções de Gerenciamento de Serviço de TI e Ciclo de Vida dos Ativos de TI, além de indicadores de desempenho e relatórios.

## Descrição da vaga

- Para profissionais com experiência em sistemas Web (HTML/HTML5, CSS3, JavaScript, React, Node.js;) e conhecimentos DevOps (Kubernets, AWS).
- Responsável pelo desenvolvimento das interfaces em sistemas WEB.
- A vaga será alocada na UOL.

## Local

100% Remoto. 

## Requisitos

-Superior completo ou em andamento em Ciência da Computação, Engenharia, Sistemas da Informação ou áreas correlatas;
-Experiência no desenvolvimento de aplicações com serviços RESTful e micro serviços;
-Design responsivo, media query, mixins, functions e extends;
-Ter conhecimentos dos conceitos Mobile First e SEO;
-Experiência em controle de versionamento de códigos (Git / SVN);
-Experiência com metodologias ágeis (Scrum e/ou Kanban);
-Inglês intermediário / avançado;
-Experiência no desenvolvimento e publicação de aplicativos em Flutter;
-Conhecimento em ferramentas de medição de crash, audiência e uso de recursos de servidores.

## Contratação

Pessoa Jurídica.

## Como se candidatar

Saiba mais sobre essa grande oportunidade e se candidate no site (basta fazer login e inserir seus contatos): https://vagas.hunterco.com.br/job/622b80cc1830db001ee5da60?r=nvgt&c=4740

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias úteis após cada processo. Depois candidatura no site, entraremos em contato para alinhamento e marcar entrevista.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by larissabazzo** [comment]
Vaga ainda aberta!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
