### ISSUE TITLE
[São Paulo] Front-end Developer na Avanade

### ISSUE THREAD

**Issue by JehRecruiter** [frontendbr/vagas#6676]
## Sobre a Avanade

A Avanade surgiu de uma Join Venture entre Accenture e Microsoft e hoje atuamos em mais de 24 países!! Aqui no Brasil temos unidades em Recife, São Paulo, Belo Horizonte e Rio de Janeiro (o que é super bacana, pois gera um fluxo enorme de troca de conhecimentos e possibilidade de atuação em times globais).

## Descrição do Job

Projeto em Angular 2+

## Local

Híbrido, [SÃO PAULO], [SÃO PAULO], [INTERLAGOS]

## Requisitos

Typescript (generics, módulos, interfaces, classes, tipagem estática)
Javascript Ecmascript 6+ (destructuring, spread, arrow functions, funções anônimas)
Gerenciamento de estados simples
Comunicação entre componentes (Cold e Hot observables)
Service Workers para PWA
Reactive forms
Testes (Aplicar os conceitos de TDD ou testes unitários utilizando Jest, Mocha ou Jasmine)
Web workers
Performance (estar preocupado com a performance da app, evitar laços de repetição (map, filter e reduce, foreach, etc)
REST (entender os conceitos de API REST, utilizar corretamente os verbos HTTP)
SOLID (saber explicar como utilizar os princípios do SOLID)

## Benefícios

•        Vale refeição ou alimentação 
•        Assistência médica e odontológica; Bradesco
•        Certificações e treinamentos; Microsoft
•        Seguro de Vida;
•        Previdência Privada;
•        EF – Inglês;
•        Avababy: acompanhamento da gestação e kit para os novos pais e mães Avanade;
•        Horários flexíveis;
•        Participação nos resultados da empresa;
•        Gympass;
•        Auxílio creche;
•        Career Advisor (um braço direito para orientar a sua carreira);
•        Exposição com times globais a depender do projeto;
•        Avaliação formal de performance e carreira;
•        Buddy – aquela pessoa que irá te ajudar nos seus primeiros meses e na fase de adaptação à nossa cultura;

## Contratação

CLT

## Como se candidatar

Entre em contato através do [WhatsApp](https://api.whatsapp.com/send?phone=5511988050160&text=Ol%C3%A1%2C%20gostaria%20de%20falar%20sobre%20a%20vaga%20de%20Angular)

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
