### ISSUE TITLE
[Remoto] Fullstack Developer na Rede Magic

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6677]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/fullstack-developer-203001357?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>Rede Magic</strong> está buscando <strong><ins>Fullstack Developer</ins></strong> para compor seu time!</p>
<p>Executamos a promoção comercial completa: planejamento, jurídico, concepção do KV (key visual), tecnologia, produção, comunicação, mídia e premiação. Nossas campanhas podem ter elementos interativos como games, mecanismos de gamificação, quizzes e redes sociais internas.</p>
<p>Buscamos pessoa FullStack Developer para trabalhar no desenvolvimento web em agência especializada em comunicação integrada e marketing digital, dentro de equipe multifuncional.</p>
<p></p>
<p></p>

## Rede Magic: 
 <p>Unimos expertises de digital e live marketing para a realização de campanhas com produção impecável.</p>

<p>Executamos a promoção comercial completa: planejamento, jurídico, concepção do KV (key visual), tecnologia, produção, comunicação, mídia e premiação. Nossas campanhas podem ter elementos interativos como games, mecanismos de gamificação, quizzes e redes sociais internas.</p><a href='https://coodesh.com/empresas/rede-magic'>Veja mais no site</a>

 ## Habilidades: 
 - PHP 
- SQL 
- Javascript 
- GIT 
- Wordpress 
- Laravel 5 
- HTML5 / CSS3 
- React
## Local: 
 100% Remoto
## Requisitos: 
 - Domínio de programação em 7+ e 8+ orientado a objeto 
- Conhecimento no framework Laravel 5+ ou similares 
- Código legível e habilidades de comunicação oral e escrita 
- Domínio de código HTML5, CSS3, SCSS, RWD (responsive web design) e JavaScript. 
- Assegurar a compatibilidade cross-browser e cross-platform 
- Conhecimento em tratamento e otimização de imagens para web (GIF, JPG, PNG, SVG e WEBP) 
- Produzir um código limpo, bem documentado e estruturado 
- Saber utilizar gerenciadores de pacotes, como NPM e YARN 
- Ter conhecimento da utilização de GIT. 
## Diferenciais: 
 - Conhecimento de WordPress e React; 
- Conhecimento em SEO; 
- Conhecimento em PWA; 
- Desenvolvimento de Testes;
## Benefícios: 
 - Horários Flexíveis 
- 100% Remoto
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack Developer na Rede Magic](https://coodesh.com/vagas/fullstack-developer-203001357?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Back-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
