### ISSUE TITLE
[Rio de Janeiro] Programação Criativa na SuperUber

### ISSUE THREAD

**Issue by Vamoss** [frontendbr/vagas#6678]
## SuperUber

Empresa referência nacional e internacional em projetos que combinam Arte e Novas Tecnologias.
São mais de 300 projetos pelo mundo, destacando-se projetos como Museu do Amanhã e Museu da Lingua Portuguesa.
A SuperUber é uma empresa que busca sempre inovar. Criando projetos que misturam Arte, Arquitetura, Design e Tecnologias para criar experiências.
Nosso portfolio tem uma diversidade ampla, destacam-se projetos imersivos, interativos e uso de projeção e interfaces tangíveis.

## Descrição da vaga
Procuramos pessoas fluentes em algorítimos, com pensamento Computacional de nivel médio para avançado, ou seja, que sejam capazes de traduzir problemas em soluções de código.
Esta vaga compreende a stack de desenvolvimento web(HTML, CSS, JavaScript), porém não se restringe a ela. A pessoa que ocupar esta vaga trabalhará também com Unity3D (C#) e OpenFrameworks (C++).
A Programação Criativa implica uma abordagem mais experimental do código. Na SuperUber trabalhamos com prototipagem rápida.

## Local

Rua Silvino Montenegro, 78, Gamboa, Rio de Janeiro.

Ficamos na região portuária, perto do AquaRio e da Roda Gigante.

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com JavaScript.
- 2 anos de experiência com Unity3D.

**Desejáveis:**
- Ter conhecimentos em C# e C++.
- Ter conhecimentos com WebGL, ReactJS.
- Ter bom senso de organização.
- Ter bom senso de gestão de tempo e tarefas.
- Ter portfolio de projetos que misturam arte e tecnologia.
- Inglês básico.

**Diferenciais:**
- Temos em nosso laboratório equipamentos disponíveis para experimentação (Projetores, Oculos VRs, Playstation etc)

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para carlos@superuber.com com seu CV e/ou portfolio anexado - enviar no assunto: Vaga Programação Criativa

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
