### ISSUE TITLE
[REMOTO] Front-End Vue.js Pl/Sr @DQR.TECH (Cliente Internacional)

### ISSUE THREAD

**Issue by gsabreudev** [frontendbr/vagas#6680]
Front-End Vue.js Pl/Sr

SOBRE NÓS
Nascemos de uma parceria de mais de 10 anos entre seus sócios, somando a paixão por tecnologia à vontade de construir uma empresa diferente, investindo na proximidade com nossos parceiros e clientes.
Somos uma consultoria especializada em Arquitetura de TI, Outsourcing de Profissionais e Hunting.

CONTRATAÇÃO:  Contrato PJ / tempo indeterminado - 40 hrs - 100% Remoto

DESAFIO: 
A DQR TECH está em busca de um profissional para atuar nas Squads Ágeis em nosso cliente, uma Edtech sustentável e inovadora de Las Vegas - Nevada, que busca combinar e conectar estudantes com universidades adequadas e suas futuras carreiras.

ATIVIDADES:
-Analisar, projetar, desenvolver, configurar, implantar, manter e aprimorar aplicações responsivas para a web.

REQUISITOS:
 -Desenvolvimento com foco no front-end de aplicações web
 -Javascript, HTML e CSS
 -Vue.js
 -Teste de software (unitário, integração, ponta-a-ponta)
 -Jest, Puppeteer, Cypress e similares
 -Metodologia SCRUM 
 -Inglês intermediário ou avançado.

REQUISITOS DESEJÁVEIS:
-Node.js
-Typescript
-DevOps
-Docker
-Serverless
-AWS

OBS.: O material para desempenhar as atividades é por conta do colaborador.

PJ até 13k (Conversão de moeda)
E-mail: gabriela.abreu@dqrtech.com.br

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
