### ISSUE TITLE
[Remoto] Front-end Developer Vue.js Pl/Sr na Invillia

### ISSUE THREAD

**Issue by gihhlazaro** [frontendbr/vagas#6681]
- **INVILLIA**

Aproxime-se. A Invillia não apenas transformou a forma como as empresas mais revolucionárias do mundo criam e desenvolvem estratégias, negócios e produtos digitais.
Inovou também a maneira como pessoas apaixonadas por tecnologia, de qualquer lugar do planeta, podem interagir, evoluir, mais conectados do que nunca.
Para a Invillia, não importa onde você está. Se é um país grande. Ou uma cidade pequena. E sim a sua vontade. As suas ideias. O seu potencial.

O tamanho do seu talento_

- **REQUISITOS**

Vue.js Avançado;
HTML5, CSS3 (Sass), Javascript, JSS;
Git, Docker, Gulp, Webpack, Gerenciamento de Pacotes (ex: NPM, Yarn) e TDD;
Padrões de Projetos (DDD, Solid, Design Patterns);
Integração e entrega contínua (CI/CD);
Desenvolvimento Ágil - Scrum e Kanban;

- **DIFERENCIAIS**

Banco de Dados Relacional e Não-Relacional; 
Conhecimento teórico e prático em microserviços e APIs; - Diferencial;
Soluções e definições de arquitetura (Flux Architecture); - Diferencial;
Ferramentas de monitoramento (Google Data Studio, Mesos, Splunk. Kibana) - Diferencial;
Criação de gráficos (Highcharts ou outros) - Diferencial;
Beautify/Material Design/Bootstrap, Styled components e Design System - Diferencial;
Microfront-end - Diferencial.

- **RESPONSABILIDADES**

Será responsável em prover soluções técnicas para novas features e dar o suporte necessário as features já existentes, afinal, nem tudo são flores.

Esperamos também que essa pessoa auxilie os outros membros do time em questões técnicas não esquecendo de fornecer a melhor solução para o negócio.

Algo que prezamos bastante é qualidade, isso inclui um código limpo e legível (clean code).

Também é desejável que o mesmo tenha um perfil intra-empreendedor, onde seus objetivos estejam alinhados com os objetivos da empresa, afinal, temos muito orgulho do que fazemos aqui!

- **LOCAL**

Full remoto 

- **REGIME**

CLT

- **COMO SE CANDIDATAR**

Enviar o currículo atualizado para giovanna.lazaro@invillia.com ou pelo LinkedIn: https://www.linkedin.com/jobs/view/2978653681

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
