### ISSUE TITLE
[REMOTO- BRASIL] Front-end Developer Pleno na Deliver IT

### ISSUE THREAD

**Issue by arthurdepauli** [frontendbr/vagas#6682]
## **DELIVER IT:**

A Deliver IT é uma consultoria de serviços de tecnologia da informação. Nossa missão é entregar valor aos nossos clientes, através de serviços de tecnologia de informação, dentro de uma relação de parceira.

Nascemos em 2014, a partir da união das atividades da Absoluta. Net com a experiência de mercado de dois profissionais sêniores, em áreas complementares! Acreditamos em equipes multidisciplinares, que possuem confiança em suas relações e sobretudo transparência. Nosso time se caracteriza pelo engajamento, comprometimento e foco na qualidade das entregas.

Acreditamos que a qualidade dos nossos processos se deve a todas as pessoas que fazem parte da Deliver, e por isso prezamos por um ambiente de trabalho agradável, leve e muito amigável. Aqui os colaboradores têm espaço para o seu desenvolvimento profissional, oportunidade de trabalhar em projetos globais e para empresas de reconhecimento a nível nacional.

Nosso portfólio de serviço utiliza tecnologias vanguardistas dentre as seguintes linhas: Fábrica de Software, Business Intelligence, Mobile e Outsourcing.

## **DESCRIÇÃO DA VAGA**

**Você se considera uma pessoa que tem sede por aprendizado, gosta de trabalhar em equipe e curte compartilhar conhecimento? Então essa oportunidade é para você!**

Estamos em busca de um(a) Desenvolvedor Front-End Angular Pleno, para atuar no desenvolvimento de uma nova plataforma para instituições de pagamentos. Fará a codificação de sistemas e aplicações de acordo com os padrões e metodologias estabelecidas e realizará testes unitários.

**RESPONSABILIDADES E ATRIBUIÇÕES**

Na sua rotina de trabalho, você vai se deparar com as seguintes atividades:**

- Desenvolvimento (Sustentação e projetos);

REQUISITOS E QUALIFICAÇÕES
Confere abaixo o que você vai precisar saber pra se dar bem nessa oportunidade!

**CONHECIMENTOS EXIGIDOS**

- Angular 7 e posteriores ;
- HTML5;
- CSS3;
- Bootstrap;
- JavaScript e Json;
- Consumo de serviços REST;
- Git Flow;
- Testes unitários.

**CONHECIMENTOS DESEJÁVEIS**

- Conhecimentos em TDD e BDD.

## **INFORMAÇÕES ADICIONAIS**
A Deliver IT vai deixar a digital nesse projeto e quer convidar você para fazer parte dessa construção! 🙆‍♀️

Temos uma cultura leve, descontraída, colaborativa e diversa, além de um ambiente enriquecedor, com muitos colegas feras em diversos segmentos e muitos desafios. Aqui você vai encontrar projetos inovadores, conexão e muita troca de conhecimento! 😊

Todas as nossas posições seguem o modelo de contrato **CLT em 44h/semanais - Flexíveis.**

## **CONFIRA NOSSOS BENEFÍCIOS**

- Modalidade: 100% Remoto;
- VA e/ou VR;
- Programa Bem-Estar: apoio psicológico, apoio jurídico, apoio social, apoio financeiro e ginástica laboral;
- Plano de Saúde e Plano Odontológico;
- Seguro de Vida;
- Incentivo ao inglês;
- Workshops mensais
- Parcerias que te dão desconto: Sucesu, Target Trust, Sesc e Seprorgs
- Premiação por aniversário de empresa;
- Premiação por indicação contratada

## Como se candidatar

ACESSE: https://deliverit.gupy.io/jobs/1584898

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 a 3 dias após cada processo.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
