### ISSUE TITLE
[São Paulo] Front-end Developer na Codeby a Keyrus Company

### ISSUE THREAD

**Issue by Peoplecodeby** [frontendbr/vagas#6683]
**Nossa empresa**
Há quase 7 anos no mercado de tecnologia, a Codeby uma empresa Keyrus contribui diariamente para o crescimento de negócios online de diversos segmentos e portes.
Somos uma empresa apaixonada por tecnologia, motivada a buscar constantemente as melhores e mais completas soluções para negócios digitais.
A Codeby uma empresa Keyrus orgulha-se de ser uma empresa criativa e está sempre desenvolvendo produtos e características inéditas no mercado, isso porque temos a melhor equipe, com profissionais inovadores que respiram novas tendências tecnológicas e são entusiasmados por desafios.
Nosso principal objetivo como empresa de tecnologia é desenvolver canais digitais que não apenas expressem o que nosso cliente inspira, mas também a torne uma experiência incrível para seu cliente final.
A Codeby uma empresa Keyrus é fundada por desenvolvedores que amam desafios, então espere ser desafiado constantemente, e ter uma evolução profissional rápida.

Como é trabalhar aqui?
Temos pensamento jovem, somos sonhadores e idealizadores, inovação e criatividade é o que respiramos!
Nosso clima de trabalho é descontraído e temos uma cultura forte sobre o trabalho em equipe, afinal cada esforço individual e coletivo é válido para atingirmos nosso objetivo final.
Nossos benefícios são para todos os Codebyers, temos muito espaço para crescimento profissional, salário competitivo com o mercado e modelo de trabalho híbrido/ remoto.

**Descrição da vaga**
Como Pessoa Desenvolvedora Front End aqui na Codeby, você irá:

Atuar como Front-end,  estruturação de requisitos de negócio para requisitos técnicos, análise de dados, gerenciamento do tempo, aplicações web, componentes, funcionalidades, sistemas e muito mais que envolve o mercado de Retail Tech.
Você será responsável por desenvolver features para projetos de implementação de novos e-commerces e dar suporte/ manutenção em lojas VTEX (CMS & IO).
Em VTEX CMS utilizará principalmente de JavaScript, HTML e CSS, enquanto em VTEX IO, poderá utilizar das mesmas linguagens além também do React J

**Requisitos**
Experiência com:
Estruturação de requisitos de negócio para requisitos técnicos;
Análise de dados;
Gerenciamento do tempo.
 
Conhecimento em:
GraphQL | Utilização de GraphQL para consumo de APIs;
Banco de Dados | Conhecimento em banco de dados PostgreSQL ou equivalente;
Componentização | Criar componentes que possam ser reaproveitados;
Orientação a objetos | Criação de classes reutilizáveis com Javascript;
React | Redux
Webpacker | Utilização da lib para uglify e minify de arquivos; automatização de rotinas; etc;
Gulp | Utilização da lib para uglify e minify de arquivos; automatização de rotinas.
 
Buscamos um perfil proativo que goste de estudar, seja curioso que queira se desenvolver e crescer profissionalmente, tenha excelentes habilidades de comunicação verbal e escrita, e saiba exemplificar de forma didática o conteúdo técnico.

**Desejáveis:**
Experiência com Wordpress, VTEX CMS / IO.
Inglês avançado.

**Como se candidatar**
Por favor envie um email para people@codeby.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Developer

**Alocação**
- Remoto

**Regime**
- PJ

**Benefícios**
Voucher Ifood mensal para Happy Hour, Day off no aniversário, Assistência Médica, Assistência Odontológica e Seguro de Vida.
Aqui você tem oportunidade de se desenvolver e crescer profissionalmente.
Somos um Time! Se quer fazer parte de uma empresa na qual o bem mais valioso são as pessoas, aqui é o seu lugar..

**Nível**
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
