### ISSUE TITLE
[Cidade] Front-end Developer na Nome da Empresa

### ISSUE THREAD

**Issue by VeronicaDante** [frontendbr/vagas#6684]
## Nossa empresa

Somos uma aceleradora de soluções digitais e buscamos Desenvolvedor Frontend para fazer parte dessa jornada.
Fomos certificados como uma das melhores empresas para se trabalhar pelo Great Place To Work, e a cada dia criamos ações que melhoram ainda mais o ambiente de trabalho.

## Descrição da vaga

A Verity está buscando novos talentos!

Olha só quais são as experiências e conhecimentos que você precisa ter para acelerar e transformar com a gente:

## Local

Remoto 

## Requisitos

**Obrigatórios:**
- Desenvolvimento de aplicações web responsivo
- HTML, CSS, SASS, Java Script
- Angular 10+

**Diferenciais:**
- Testes utilizando Karma e Jasmine
- Versionamento Git e Bitbucket
- Práticas DevOps
- Nginx
- Conteinerização (docker)

## Benefícios

- Vale refeição
- Vale alimentação
- Auxílio home office
- Assistência médica
- Assistência odontológica
- Seguro de vida
- Parcerias de descontos
- Convênios em estabelecimentos e instituições de ensino
- Licenças Alura

**Diferenciais:**
- Treinamentos de agilidade recorrentes
- Verity Coffee
- #VerityComVocê
- Verity Game Room

## Contratação

CLT

## Como se candidatar

Por favor envie um email para veronica.dante@verity.com.br com seu CV anexado - enviar no assunto: Vaga Angular

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: sejaveriter@verity.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
