### ISSUE TITLE
[Remoto/São Paulo] Wordpress Developer at Zipia

### ISSUE THREAD

**Issue by danpossa** [frontendbr/vagas#6686]
## Our Company

Zipia is a Brazilian startup that span out of QuinStreet, Inc (NASDAQ: QNST), a Silicon Valley company founded in 1999 and the world leader in Digital and Performance Marketing. We use technology to match consumers with the offers that best suit their needs. With more than 10 years of experience in the Brazilian market, Zipia works directly with clients like Porto Seguro, Youse, Bradesco, Minuto Seguros, Qualicorp and many other big and small players in the Financial Services scene in Brazil.

## Job Description

We’re looking for a technically-minded Wordpress Developer that can manage, optimize, troubleshoot and develop our portfolio of websites and forms. The ideal profile is a good technical generalist, who is comfortable working with both back-end and front-end technologies. You should be able to interact with a remote English-speaking technical team and be able to work closely with the design team.

**Please send your CV in English - Interviews are in English.** (Please only sign up if your English level matches this requirement.)

## Local

Zipia is based in São Paulo (SP). We provide the essential so you can work from anywhere you like!

## Skills

**Essential:**
- HTML, CSS (Intermediate)
- PHP (Intermediate)
- JavaScript (Intermediate)
- My SQL
- Wordpress
- Hosting and performance optimization
- Trouble Shooting skills
- Intermediate level spoken English (or above)

**Valuable:**
- UI/UX design experience
- JavaScript frameworks experience (e.g. jQuery, Angular, ...)
- AB testing
- Technical SEO

## Benefits

- Health Plan
- Dental Plan
- Life Insurance
- VR - R$ 40/dia

## Work Regime

CLT (Brazilian law)

## How to apply

We'd love to tell you more and hear it from you, send your CV to careers@smartia.com.br - subject: "Wordpress Developer"

#### Alocação
- Remoto
#### Regime
- CLT
#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
