### ISSUE TITLE
[Remoto] Senior React Native Developer | PJ - Builders

### ISSUE THREAD

**Issue by Patriiciabrito** [frontendbr/vagas#6691]
Somos uma comunidade de pessoas que desejam aprender, evoluir, empreender e construir iniciativas que gerem valor. Nosso propósito é te ajudar a construir o seu legado e te dar insumos para solucionar problemas reais na prática. **O momento para se tornar Builder é agora!** 💪

**Tecnologias que se você dominar, vão gerar valor nos projetos 💻:**

- Fluência em TypeScript;
- React (Redux/Mobx);
- APIs REST;
- Trabalhar com diferentes dimensões de dispositivo (tablet, celular, etc)
- Conhecimento geral do ambiente móvel;
- Versionamento de código com Git;
- Conhecimento em arquitetura de software;
- Metodologias ágeis.

**Como Builder, você terá acesso a:**

- Oportunidades reais de empreender e impactar;
- Fazer parte de uma comunidade de empreendedores;
- Inovação e criação liberados;
- Participar de um processo único de geração de valor;
- Contribuir na criação de métodos disruptivos;
- Colocar suas ideias no mercado, na prática! :)
- Possibilidade de Profit share em novos Negócios;
- Prestador de Serviços (PJ).

**Junte-se ao movimento:** https://jobs.kenoby.com/sejabuilder

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
