### ISSUE TITLE
[100% Remoto] Front-end Developer [Angular 11] @Lastlink

### ISSUE THREAD

**Issue by Stefany-Passos** [frontendbr/vagas#6692]
## Nossa empresa

Nascemos para oferecer soluções digitais que permitam tornar ainda mais próxima a conexão entre o produtor de conteúdo e suas comunidades. 

## Descrição da vaga

Nesta função, você fará uma contribuição significativa para traduzir as necessidades de nossos clientes e as expectativas dos usuários em aplicações web interativas, utilizando como framework o Angular 11.

## Local

Remoto

## Requisitos

- Javascript, HTML5 e CSS3 (Bootstrap, Sass e Less);
- Versionamento de código (GIT);
- Ter experiência com Angular, Bootstrap, CSS e Typescript;
- Seguir as tendências do mercado e que seja capaz de se adaptar rapidamente a novas tecnologias;
- Inglês intermediário (capaz de ler e escrever, será utilizado principalmente para estudo e leitura de documentações).

#### Diferencial

- Noções de docker e linux;
- Noções de cloud e bancos No-SQL;
- Já ter trabalhado em uma equipe ágil.

## Benefícios

- Auxilio home-office, vale cultura e cuidados com saúde e bem-estar;
- Vale refeição e/ou alimentação (sem desconto);
- Plano de saúde subsidiado pela empresa;
- Cultura que valoriza o 1:1; feedback; diversidade; inclusão; causas sociais e valores humanos;
- Salário competitivo dentro dos maiores mercados do Brasil;
- Programa de Stock Options.

## Como se candidatar

Você poderá se candidatar através [deste link ](https://bit.ly/3uWMou7) ou, se preferir, envie um e-mail para [tatiana@remotar.com.br](mailto:tatiana@remotar.com.br).
OBS: esta vaga está sendo divulgada pela [Remotar](https://remotar.com.br/?utm_source=github) em nome da Lastlink, cliente de nossa empresa. No entanto, todo o processo seletivo será diretamente com a Lastlink, sem gargalos.

#### Alocação
- Remoto

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
