### ISSUE TITLE
[São Paulo] Front End Developer na Huntz

### ISSUE THREAD

**Issue by HuntzITJObs** [frontendbr/vagas#6693]
#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by VictorAndrade11** [comment]
pode dar mais detalhes sobre a vaga?

**Comment by HuntzITJObs** [comment]
Oi Victor, 
Estamos apoiando uma MediaTech chamada Brasil Paralelo (https://www.brasilparalelo.com.br/) que está em um momento de transformação digital e construindo seu primeiro time de tecnologia (squads) para atuar diretamente em  projetos de streaming, comunicação, documentários. Toda área de pagamentos está também sendo estruturada. 
Te convido a entrar no site e conhecer o trabalho deles. 
Você poderá atuar como full stack ou como Front ou Back end, principalmente em React.
Existe um bom espaço para novas tecnologias. O CTO é ex-Nubank e está construindo uma cultura dev mais flexível no local.
Te ajudei com mais informações? 
Quer participar?
Abs
Renata
11- 99820-1358

**Comment by carvalho-code** [comment]
Oi renata, eu gostaria de conhecer.

**Comment by HuntzITJObs** [comment]
Joao me chame no whats 11 99820 1358

Em qua., 30 de mar. de 2022 11:28, João Pedro de Carvalho <
***@***.***> escreveu:

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
