### ISSUE TITLE
[Porto Alegre] Front-end Developer na Personallizze

### ISSUE THREAD

**Issue by Personallizze** [frontendbr/vagas#6695]
Analista de Suporte – Sistema MES 

Superior Completo, experiência em implementação ou suporte aos sistemas MES, ERP ou PLM.
Bons conhecimentos em C#, T-SQL, .NET e X++
Inglês avançado 
Vivência na área de Manufatura 
Interessados enviar CV para: [contato@personallize.com.br](mailto:contato@personallize.com.br)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
