### ISSUE TITLE
[REMOTO/ITÁLIA] Pleno/Senior React Developer @Hashtag.be

### ISSUE THREAD

**Issue by valentim-guilherme** [frontendbr/vagas#6696]
## Descrição da vaga

Buscamos desenvolvedores com um perfil pleno/sênior para integrar o nosso time de desenvolvimento, e esperamos que você:

- Desenvolver código limpo, testável e de fácil manutenção.
- Contribuir com todo o processo de desenvolvimento de software.
- Implementar features novas e investigar problemas existentes.
- Contribuir nas discussões técnicas sobre os desafios encontrados.

## Local

100% remoto, empresa com base na Itália, horário flexível.

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com Javascript, React.js, TypeScript.
- Experiência com HTML/CSS/Javascript/Typescript;
- Experiência com testes unitários e de integração. 
- Experiência em projetos utilizando componentes de classe.
- Conhecimento em Design Patterns;

**Desejáveis:**
- Experiência com firebase.
- Experiência com styled components.
- Habituado com principios de CI/CD;
- Inglês avançado.
- Experiência com Cypress.
- Experiência com Jest.

**Diferenciais:**
- Perfil de liderança.

## Contratação
PJ entre [€1600 - €2000] líquido sendo os impostos do modelo empresarial brasileiro sendo pagos além deste valor.

## Como se candidatar
Por favor envie um email para guilherme@hashtag.be com o título "Vaga React Pleno/Senior" com seu GitHub e linkedin.

## Tempo médio de feedbacks

Costumamos enviar feedbacks no máximo até 2 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
