### ISSUE TITLE
[Remoto] Front-end Developer na Apus

### ISSUE THREAD

**Issue by vcromeiro** [frontendbr/vagas#6697]
## Nossa empresa

A Apus – Soluções em TI nasce da junção de empresas de tecnologia da informação e consultoria, com o propósito de construir e propor soluções personalizadas, criativas e eficientes, que gerem maior qualidade e precisão no trato das informações de seus clientes.

Especializados em Gestão Educacional, porém, criando soluções para um universo cada mais plural de clientes, temos diferentes soluções perante a gestão, ensino à distância e avaliação tanto para a educação pública, quanto a privada, além de trabalhos de assessoramento e consultoria.

## Descrição da vaga

Desenvolvimento de aplicações Web utilizando Javascript com Typescript.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Desenvolvimento de aplicações para Web.
- Sólido conhecimento em Javascript com Typescript;
- Sólido conhecimento em desenvolvimento utilizando orientação a objetos;

**Desejáveis:**
- Estar familiarizado com os principais padrões de desenvolvimento com Javascript e Typescript;
- Saber trabalhar com versionamento de código (Git);
- Saber trabalhar com conteinerização utilizando Docker e Docker Compose.

**Diferenciais:**
- Conhecimento em React JS é um diferencial.

## Atividades
- Trabalhar em implementações de novas aplicações utilizando de Javascript com Typescript;
- Ajudar nas decisões de impacto na experiência do usuário dentro de nossas plataformas;
- Consumir diversas APIs internas na construção dinâmica das telas, seguindo as regras de negócio definidas pelo projeto.

## Contratação

PJ a combinar

## Como se candidatar

Enviar e-mail com pretensão salarial utilizando o assunto: Desenvolvedor(a) Front-End Pleno
Para: desenvolvimento@apus.info

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
