### ISSUE TITLE
[Remote] Full Stack Developer na Totvs

### ISSUE THREAD

**Issue by Felipepirova** [frontendbr/vagas#6698]
## Nossa empresa
Você sabia que as tecnologias da TOTVS impactam o dia a dia de milhões de pessoas e contribuem para o crescimento de mais de 40 mil empresas no Brasil e no mundo?

O desafio da área comercial é de levar soluções especializadas aos nossos clientes de diversos segmentos do mercado.

Entendemos que nossas soluções farão a diferença para que o cliente transforme e cresça seu negócio.

Se você é focado(a) em resultados e gosta de um ambiente colaborativo, dinâmico e de aprendizado diário, venha fazer parte do nosso time!

Venha ser TOTVER!

Venha ousar e transformar na maior empresa de tecnologia do Brasil.

#ouseetransforme

#sejaTOTVER

## Descrição da vaga

- Desenvolver soluções técnicas de média e alta complexidade, com baixo nível de supervisão e pouco apoio, através do desenvolvimento de requisitos de softwares utilizando-se das tecnologias envolvidas no projeto;
- Conhecer a fundo a arquitetura do software e ser capaz de atuar nela através da análise de seus componentes, organização e funcionalidades; 
- Criar testes de alta complexidade, sejam estes manuais ou automatizados, que cubram o comportamento desejado dos componentes técnicos desenvolvidos utilizando os requisitos e ferramentas de testes;
- Documentar as etapas de desenvolvimento realizando o registro do desenvolvimento nas ferramentas de versionamento e documentação;
- Orientar e trabalhar com o time de desenvolvimento para encontrar soluções de negócio, arquitetura e desenho através da comunicação e trocas de conhecimento;
- Manter a qualidade do software verificando os processos, ferramentas e boas práticas disponíveis para o produto e tecnologia utilizados;
- Orientar desenvolvedores de menor senioridade apoiando suas dúvidas, disseminando seu conhecimento, desenhando e arquitetando soluções ou indicando documentação de apoio;
- Detalhar requisitos de média e alta complexidade através do contato com clientes e áreas envolvidas no projeto/atendimento.

## Local
Remoto

## Requisitos
- Java 11
- Spring Boot
- Profunda experiência com padrões de orientação a objeto, estrutura de dados,
- design de algoritmos e análises complexas;
- Aplicação, monitoria e qualidade com automação e testes (Junit, Mockito);
- Conhecimento de Git e Maven;
- JPQL e elaboração de queries nativas.
- Banco de Dados PostgreSQL;
- Servidor de aplicação Undertow
- Desenvolvimento de WebServices REST;
- DDD - Domain Driven Design;
- Experiência com arquitetura em nuvem;
- SOLID;
- TDD;
- CQS/CQRS;
- Microserviços;
- Containers com Docker e Kubernetes;
- Conhecimentos em mensageria utilizando RabbitMQ;
- DevOps;
- Continuous Integration (CI) /Continuous Deployment (CD);
- Conhecimento de boas práticas de desenvolvimento de software.

## Benefícios

- Universidade em Rede TOTVS, uma universidade Corporativa com conteúdos e certificações gratuitos para cada TOTVER;
- Programa +Saudáveis, que cuida de cada TOTVER com assessoria e ações voltadas para o bem estar em corpo, mente e finanças pessoais;
- Programa +Vantagens, a maior rede de descontos da América Latina, exclusivos para TOTVERS;
- Programa + Cuidado, programa de apoio pessoal para TOTVERS e familiares, com orientações em diversas especialidades como: psicologia, serviço social, pet consultoria...
- Einstein Conecta, benefício de orientação médica online pelos médicos do Hospital Israelita Albert Einstein, totalmente gratuito;
- Plano de saúde e odontológico;
- Vale refeição e / ou alimentação;
- Vale transporte e fretados em algumas estações do metrô;
- Licença maternidade e paternidade estendida;
- Espaço de lactário;
- Bicicletário;
- Vestiário;
- Seguro de vida;
- Auxílio creche;
- Previdência privada;
- Escritório que estimula a criatividade e produtividade com ambientes para lanches, salas de jogos, mesas de bilhar e poltronas para relaxar;
- Gympass.

**IMPORTANTE:** Os benefícios podem alterar conforme a unidade e/ou adquirida TOTVS.

## Contratação

CLT

## Como se candidatar

Por favor envie um email para felipe.pirovano@totvs.com.br com seu CV anexado.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após cada processo.
#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by mrsants** [comment]
Não é uma vaga de frontend

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
