### ISSUE TITLE
[Remoto/Itália] - React Native Developer Senior na Hashtag.be

### ISSUE THREAD

**Issue by valentim-guilherme** [frontendbr/vagas#6699]
## Descrição da vaga

Buscamos desenvolvedores com um perfil pleno/sênior para integrar o nosso time de desenvolvimento, e esperamos que você:

- Desenvolver código limpo, testável e de fácil manutenção.
- Contribuir com todo o processo de desenvolvimento de software.
- Implementar features novas e investigar problemas existentes.
- Contribuir nas discussões técnicas sobre os desafios encontrados.

## Local

100% remoto, empresa com base na Itália, horário flexível.

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com React Native, TypeScript.
- Experiência com o processo de build e disponibilização de aplicacoes iOS & Android.
- Experiência com Expo.
- Experiência com testes unitários e de integração. 
- Conhecimento em Design Patterns;

**Desejáveis:**
- Experiência com firebase.
- Habituado com principios de CI/CD;
- Inglês avançado.

**Diferenciais:**
- Perfil de liderança.

## Contratação
PJ entre [€1600 - €2000] líquido sendo os impostos do modelo empresarial brasileiro sendo pagos além deste valor.

## Como se candidatar
Por favor envie um email para guilherme@hashtag.be com o título "Vaga React Native Pleno/Senior" com seu GitHub e linkedin.

## Tempo médio de feedbacks

Costumamos enviar feedbacks no máximo até 2 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by SrBrahma** [comment]
Oi @valentim-guilherme, é full time?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
