### ISSUE TITLE
[São Paulo] Front-End 

### ISSUE THREAD

**Issue by lucasalbuquerque** [frontendbr/vagas#67]
## Descrição da vaga

Pra você, tá tranquilo: 
- Personalizar lojas virtuais baseadas em templates
- Realizar alterações em front-end
- Fazer rotinas para teste antes da publicação
- Instalar e configurar domínios
- Realizar o gerenciamento do conteúdo

Domina HTML5 e CSS3?

Se estiver de acordo.

Vem trampar com a gente.

## Local

Av Brigadeiro Luiz Antonio.

## Benefícios
 Vale-refeição
 Bônus
 Plano de saúde e odontológico
 Oportunidade de comprar ações da empresa com desconto
 Auxílio creche
 Fundo de pensão
 Cortesia de lentes

## Requisitos

**Obrigatórios:**
- HTML5 
- CSS3

**Desejáveis:**
- Javascript
- Jquery

## Contratação

CLT

## Nossa empresa

GLASSES 4 YOU - Somos uma startup de uma multinacional.

## Como se candidatar

http://trampos.co/oportunidades/126958?lc=glasses

**Comment by LFeh** [comment]
A vaga é pleno?

**Comment by lucasalbuquerque** [comment]
Junior, desconsidere estar no trampos "saber tudo" de html e css e se virar bem em Javascript, isso é coisa do rh.

As tarefas no dia a dia são bem simples, como criar html para e-mail marketing, adicionar e remover produtos em loja virtual, coisas assim.

**Comment by LFeh** [comment]
Boa ;)

**Comment by SeuZeRicardo** [comment]
É necessário experiência na área mais de 1 ano e é em qual período ?

**Comment by renanrider** [comment]
Qual horário?

**Comment by Finacio** [comment]
Olá, eu estudo de tarde das 13 as 18h, para a vaga tenho horário das 7 ao 12, tem algum problema?

**Comment by lucasalbuquerque** [comment]
Vaga fechada galera! E era full time.

Me passam seus e-mails que aviso sobre novas vagas.

Abs

**Comment by camilatigre** [comment]
@lucasalbuquerque 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
