### ISSUE TITLE
[Remoto] Developer Outsystems SR na Tech For TI

### ISSUE THREAD

**Issue by amandakarenm** [frontendbr/vagas#6702]
## Nossa empresa

Somos uma empresa genuinamente brasileira e referência em qualidade na entrega de serviços por meio de um time altamente capacitado e certificado.

O histórico de projetos desenvolvidos em nossa fábrica de software, outsourcing de sistemas, alocação de profissionais através do RH especializado na seleção de profissionais de TI e gestão de ambientes e infraestrutura por meio de uma equipe certificada, nos credencia como uma ótima opção para empresas de todos os segmentos de mercado.

Nossa política de qualidade inclui a adoção de padrões e metodologias aderentes em todos os processos de serviços da empresa.

E o resultado desse trabalho é a completa satisfação de nossos clientes.

**Topa compor o time e se realizar? Vem comigo!**

## Descrição da vaga

A Tech For, Consultoria de Tecnologia da Informação, há 13 anos no mercado e especializada em soluções inteligentes e referência na entrega de serviços de alta qualidade está com oportunidade para Developer Outsystems SR, para empresa tecnológica portuguesa focada na prestação de serviços de desenvolvimento, teste e suporte de software através de centros de competência localizados em Portugal.

## Local
Remoto

## Requisitos

**Obrigatórios:**
- Certificado pela Outsystems. 

**Desejáveis:**
- Conhecimentos em negócios para banco, seguros, utilities, com experiências mais complexas do ponto de vista aplicacional;
- Desejável e não obrigatório: experiência prévia como Developers em Java, C#, PHP e Javascript/CSS. 

## Contratação

PJ

## Como se candidatar

Por favor envie um e-mail para amsilva@techforti.com.br com seu CV anexado - enviar no assunto: Vaga Developer Outsystems SR

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
