### ISSUE TITLE
[100% Remoto] Pessoa Programadora Frontend II @ Locaweb

### ISSUE THREAD

**Issue by Stefany-Passos** [frontendbr/vagas#6703]
## Nossa empresa

Somos a Tray Corp, a plataforma de e-commerce da Locaweb que transforma vidas, experiências e negócios por meio da tecnologia

## Descrição da vaga

- Desenvolver interfaces amigáveis seguindo os protótipos montados por um profissional de UI/UX;
- Consumir APIs Rest e/ou GraphQl;
- Realizar otimações de renderização e carregamento;
- Realizar code-reviews e refactorings;
- Desenvolver testes unitários
- Pesquisar e propor soluções para as necessidades dos clientes.

## Local

Remoto

## Nosso Stack

As principais tecnologias que usamos são: Css, HTML, Javascript, React JS, Redux, Git, Sass, Mterial UI

⚠️ Você não precisa dominar todas, mas precisa estar confortável com o ecossistema.

## Requisitos

- Experiência em desenvolvimento de software
- Conhecimentos sólidos e práticos em assuntos relacionados ao desenvolvimento web: estrutura de dados,como funciona um navegador, comunicação http, tipos de renderização;
- Graduação concluída ou em andamento em uma área STEM (Science, Technology, Engineering or Mathematics);
- Inglês técnico;

## Benefícios

- Salário compatível com o mercado;
- Horário Flexível (8 horas de segunda à sexta);
- Plano de Saúde Unimed e Plano Odontoprev 100% pago pela empresa para o funcionários e sem co participação
- Vale Refeição ou Vale Alimentação – R$ 25,00 ao dia;
- Vale Transporte;
- Day Off;
- PPR (Programa de Participação de Resultados)
- Gympass
- Licença Maternidade 6 meses
- Seguro de Vida em Grupo

## Como se candidatar

Você poderá se candidatar através [deste link ](https://bit.ly/3uJJloD) ou, se preferir, envie um e-mail para [tatiana@remotar.com.br](mailto:tatiana@remotar.com.br).
OBS: esta vaga está sendo divulgada pela [Remotar](https://remotar.com.br/?utm_source=github) em nome da Locaweb, cliente de nossa empresa. No entanto, todo o processo seletivo será diretamente com a Locaweb, sem gargalos.

#### Alocação
- Remoto

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
