### ISSUE TITLE
[Florianópolis] Front-end Developer @ Keeps

### ISSUE THREAD

**Issue by NovareRH** [frontendbr/vagas#6707]
## Nossa empresa

﻿﻿A Keeps é uma EdTech focada em trazer ao mercado de educação corporativa soluções disruptivas e de alto impacto nos negócios. Suas soluções utilizam inteligência artificial, colaboração e mobilidade para potencializar o conhecimento dos colaboradores.

Nos últimos três anos foram premiados entre as 6 melhores EdTechs no Brasil.

Possuem o propósito de Desenvolver e Impulsionar o conhecimento, sendo referência em inovação, tecnologia e serviços para área de educação.

Para fazer parte de time da Keeps ﻿precisa gostar muuuuito de aprender. Estudar e manter um conhecimento continuo é um dos valores da Keeps.

## Local

Florianópolis

## Responsabilidades
- Desenvolvimento de novas funcionalidades;
- Fazer manutenções e eventuais correções necessárias;
- Elaboração de documentação ﻿e guias de requisitos funcionais, conforme os projetos.
- Verificação dos códigos através de testes unitários. 
- Garantir qualidade e agilidade das entregas;
- Ser proativo em relação a dúvidas quanto ao produto;
- Garantir qualidade do sistema entregue ao cliente.

## Desafios

A Keeps acaba de receber um aporte e está em crescimento acelerado. Seu time de desenvolvimento trabalha com tecnologia de ponta; é essencial que a mentalidade dos programadores que chegarem esteja focada em desenvolvimento profissional com aquisição de novos conhecimentos.

## Competências

- Experiência com Angular +2;
- Conhecimento em TypeScript, Angular Material, SCSS, CSS, Material Design e APIs REST;
- Conhecimento em metodologias ágeis;
- Noções de UX/UI;
- Inglês intermediário (necessário para leitura de documentação); 
- Conhecimento em testes unitários.﻿

## Requisitos

- Angular
- Typescript
- SCSS
- Tailwind CSS
- NGRX
- React e React Native

- Ensino médio completos com cursos especializados em tecnologia.

## Benefícios

▫ CLT:
﻿﻿- VA ou VR: 22,00/dia
﻿- Bolsa de Estudos R$ 200,00
﻿- PLR

▫﻿PJ:
﻿- Bolsa de Estudos R$ 200,00
﻿﻿- PLR
﻿﻿- Ajuda de Custo R$ 150,00
﻿- Férias 20 dias remuneradas.

## Contratação

- A partir de R$ 2.000,00. Possibilidade de contratação PJ ou CLT﻿

## Como se candidatar

Aplique para a vaga [por aqui](https://www.careers-page.com/novare-rh/job/QX969R7R) .

#### Alocação
- Presencial

#### Regime
- CLT 
- PJ

#### Nível
- Pleno 
- Júnior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
