### ISSUE TITLE
[São Paulo] Front-End Developer na Netshoes

### ISSUE THREAD

**Issue by tagliati** [frontendbr/vagas#671]
## Descrição da vaga

Buscamos  front-end developers com experiência de no mínimo 3 anos. Trabalho presencial em horário comercial.

### Local

Escritório em São Paulo - próximo ao metrô Vergueiro.

### Ambiente

Time multidisciplinar focado em produto.
Equipe dinâmica e motivada.
Voz ativa e participação nas decisões de negócio.

### Obrigatório
- Linguagens: NodeJS, Javascript;
- SASS, HTML5, CSS3
- Versionamento: Git (GitFlow, PR, etc)

### Desejável
- Testes: Jasmine, Mockito
- AngularJS, React, Dust
- Metodologias ágeis.
- Inglês Intermediário (Leitura, Escrita e Conversação);

### Diferencial
- Sólidos conhecimentos em TDD e BDD.
- Experiência com implementação de testes A/B.
- Back-end: Java 8, Spring Cloud.

### Contratação
CLT Full - 44h Semanais, VR, VA, VT, Assistência Médica e Odontológica, Benefício Farmácia, Seguro de Vida, Plano de Previdência de Privada, Bolsa de estudos, Participação Proporcional ao Resultado.

### Nossa empresa
Somos nós que construímos cada história de sucesso, cada inovação que leva à melhor experiência de compra para nossos clientes.
Estamos constantemente quebrando recordes e ampliando a nossa atuação. Não somos mais apenas esporte. Somos moda. Somos estilo de vida. E seremos muito mais.
E é dessa incansável vontade de fazer mais e melhor que pautamos nossos novos valores, missão e visão para continuarmos sempre à frente.
Somos Netshoes. Somos Zattini. Somos Shoestock. Somos o Grupo Netshoes!

# Como se candidatar
Por favor envie um email para marcelo.paparelli@netshoes.com - enviar no assunto: Vaga Desenvolvedor Front-End Sênior.

**Comment by Finacio** [comment]
A vaga é pra pleno e sênio?

**Comment by LFeh** [comment]
Pela descrição sim `Buscamos front-end developers com experiência de no mínimo 3 anos. `

**Comment by kvnol** [comment]
A issue #684 que o @victorgutierre aceitava CVs de junior, essa também?

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
