### ISSUE TITLE
BRASIL | Front-end Developer ReactJS | Escalate Technology 

### ISSUE THREAD

**Issue by JoseCastellaniNeto** [frontendbr/vagas#6711]
**ReactJS - Escalate Technology** 

Para a posição de Front-End - ReactJS, são necessárias algumas habilidades para ter sucesso, dentre elas: HTML5, CSS, JavaScript (ES6), React

Também seria interessante ter conhecimento e/ou desejo de se aprofundar em: Testes automatizados, Arquitetura (Webpack, Babel, ESLint, stylelint, Micro Frontend), RESTful, GraphQL, WebSocket

interessados enviar cv para: jose.neto@escalate.com.br
In: https://www.linkedin.com/company/escalate-technology/

![logo azul BRANCO](https://user-images.githubusercontent.com/91694294/161107072-8ba9ddd7-0f28-459c-9b8b-06516d01f976.png)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
