### ISSUE TITLE
[Remoto] Fullstack C# Developer (Pleno) na Supply4Med

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6712]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/fullstack-c-developer-pleno-131116638?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>Supply4med</strong> está buscando <strong><ins>Fullstack C# Developer </ins></strong>para compor seu time de desenvolvimento.</p>
<p>Somos uma empresa de soluções para a cadeia de suprimentos da saúde agregando inovação para alcançar excelência e otimização dos processos de compra e venda, logística, finanças, compliance e inteligência de dados, entre outros.</p>
<p>Buscamos otimizar a cadeia de suprimentos do setor da saúde para aumentar a eficiência de todo o processo e contribuir para a melhoria da prestação de serviços médico-hospitalares e para os resultados financeiros de nossos clientes.</p>
<p>A pessoa será responsável por desenvolver novos projetos e melhorar/qualificar os produtos existentes com tecnologia para WEB baseadas no Framework Microsoft.NET.</p>

## Supply4Med: 
 <p>Somos uma empresa de soluções para a cadeia de suprimentos da saúde agregando inovação para alcançar excelência e otimização dos processos de compra e venda, logística, finanças, compliance e inteligência de dados, entre outros.</p>
<p>Buscamos otimizar a cadeia de suprimentos do setor da saúde para aumentar a eficiência de todo o processo e contribuir para a melhoria da prestação de serviços médico-hospitalares e para os resultados financeiros de nossos clientes.</p><a href='https://coodesh.com/empresas/supply4med'>Veja mais no site</a>

 ## Habilidades: 
 - Entity Framework 
- C# 
- .NET 
- MVC 
- Microsoft SQL Server 
- JSON
## Local: 
 100% Remoto
## Requisitos: 
 - Ser habituado em metodologias agéis 
- Essencial experiência em programação WEB e boa lógica de programação. 
- Conhecimento e experiência em C# .Net 
- Conhecimento em MVC, SQL Server e Json

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack C# Developer (Pleno) na Supply4Med](https://coodesh.com/vagas/fullstack-c-developer-pleno-131116638?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
