### ISSUE TITLE
[Remoto] Full Stack Developer Angular/Typescript/Node.js - MG

### ISSUE THREAD

**Issue by Recruiterpsi22** [frontendbr/vagas#6714]
> Vaga  “Home Office”

Empresa atua com Ensino, Pesquisa e Desenvolvimento de tecnologias, sediada em Minas Gerais, foi a primeira instituição de ensino superior de Engenharia de Telecomunicações do Brasil.  

## Descrição da vaga

Responsabilidades:

- Realizar o desenvolvimento de aplicativos desktops multiplataformas, web, webservices e integração de sistemas, envolvendo diferentes meios e protocolos de comunicação, com múltiplas regras de negócios,  volume elevado de usuários/dados na aplicação e que possuam integração com dispositivos/equipamentos;
- Codificação de bancos de dados relacionais e não relacionais;
- Depuração de códigos em diferentes ferramentas;
- Especificar e documentar APIs;
- Desenvolver testes automatizados e uso de ferramentas para essa finalidade;
- Preparar, configurar e disponibilizar ambientes de desenvolvimento e testes;
- Realizar testes em ambiente de desenvolvimento;
- Atuar em correções/ajustes da solução;
- Revisar códigos desenvolvidos;
- Apoiar tecnicamente o time do projeto;
- Elaborar documentação de projeto.

## Local

100% Remota 

## Requisitos

**Desejáveis:**
- Formação superior completa em Engenharia, Ciência da computação, Sistemas de Informação ou áreas correlatas;
- Domínio em desenvolvimento orientado a objeto e lógica de Programação;
- Experiências em: Typescript, Angular, React, NodeJS, Bancos de dados relacionais e não relacionais, Cultura DevOps, Servidor de Aplicação, Princípios, boas práticas e padrões de codificação;
- Conhecimentos em: Docker, Automatização de testes, Serviços de mensageria de alta performance, Protocolos de comunicação HTTP e MQTT.

**Diferenciais:**

- Conhecimentos em: Microserviços, Desenvolvimento e documentação de APIs REST, Principios SOLID, MongoDB, Swagger e SOAP UI, Servidor de Mensageria RabbitMQ.
- Atuação como fullstack.
- Adaptabilidade a novas tecnologias e organização.

## Benefícios

- Plano de saúde
- Seguro de vida
- VR/VA
- Descontos em cursos de graduação

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um e-mail para recruiter.psycho@yahoo.com com seu CV anexado - enviar no assunto: Vaga Dev Full Stack

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: recruiter.psycho@yahoo.com

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

#### Linguagens

- Angular
- React
- Typescript
- Node.Js

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
