### ISSUE TITLE
[ REMOTO ]  REACT/ FLUTTER @Meta 💙💙💙

### ISSUE THREAD

**Issue by techrhrj** [frontendbr/vagas#6715]
Hey, Devs!! Estamos em busca de Desenvolvedores para atuar aqui na META https://www.meta.com.br/

## Quem Somos Nós:

Somos uma empresa com foco em soluções tecnológicas ágeis que simplificam e geram valor real no dia a dia das organizações. Nos últimos 30 anos, trabalhamos para que a tecnologia estivesse a serviço do que é mais humano, contribuindo para o desenvolvimento das organizações e seus processos de transformação digital. Acreditamos que esse desenvolvimento só é possível devido as nossas pessoas, que fazem o nosso negócio e de nossos clientes. O nosso propósito é promover o Crescimento Humano com Tecnologia.

## Requisitos

**Obrigatórios:**
- 4 anos no mínimo de experiência com Flutter
- 4 anos no mínimo de experiência com React
- Conhecimentos avançados em HTML e CSS;
- Conhecimento de APIs REST;
- Conhecimentos em Swagger - Conhecimento de Microsserviços e Microfrontends
- Experiência com Continuous Deployment (Azure DevOps);

## Benefícios

- Plano de saúde e Odontológico
- Seguro de vida
- PLR 
- VR/ VA
- Ajuda de Custo
- Plataforma Alura
- Plataforma Vittude
- English Club
- Meta Academy

## Contratação

CLT

## Como se candidatar

Por favor envie um email para thais.franco@meta.com.br com seu CV anexado + Pretensão Salarial

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
