### ISSUE TITLE
[100% Remoto] Desenvolvedor Full Stack Sênior @ Zenvia

### ISSUE THREAD

**Issue by Stefany-Passos** [frontendbr/vagas#6716]
## Nossa empresa

Se você já alterou uma data de pagamento de fatura por meio de um chatbot ou interagiu com um canal de suporte em redes sociais, nós estamos por trás da solução.

## Descrição da vaga

Buscamos um Full Stack Sênior para nos ajudar a desenvolver novos recursos e integrar produtos de empresas adquiridas para a Plataforma Zenvia.

## Local
 Remoto

## Requisitos

- Análise técnica de requisitos de suporte;
- Suportar a definição da arquitetura, com base nos requisitos e necessidades dos usuários;
- Desenvolver software de acordo com a definição da equipe;
- Desenvolver e projetar APIs;
- Desenvolva aplicativos e serviços usando métodos de desenvolvimento Agile.
- Conhecimento sólido em Node.js – Typescript será um diferencial;
- Conhecimento em Vue, Angular ou outro framework web;
- Experiência com arquitetura de microsserviços;
- Experiência com containers (Docker);
- Código limpo;
- Capacidade analítica e atitude de resolução de problemas;
- Grande jogador de equipe com capacidade de trabalhar com supervisão mínima.

**Diferenciais:**

- Kubernetes;
- Integração contínua;
- Automação de testes de software;
- Arquitetura limpa.

## Benefícios

- Horário flexível
- Você entra e ganha R$1.500,00 para auxiliar nos equipamentos do seu escritório em casa
- Auxílio home office mensal (permanente) de R$250,00 e parceria com Beer & Coffee para co-workings no Brasil inteiro
- Pacote completo de benefícios: vale alimentação e refeição (você pode escolher o valor a ser alocado em cada), plano de saúde e odontológico, seguro de vida
- Plano de saúde 100% custeado pela empresa para o colaborador + possibilidade de incluir dependentes
- Programa de idiomas e acesso a um Hub de Aprendizagem para seu desenvolvimento e para que você possa ativar todo o seu potencial e desenhar sua carreira na ZENVIA
- Birthday off e flexibilidade para tirar suas férias
- Parceria com Gympass e aula de Yoga ao vivo, online!
- Participação nos resultados, porque você ajudou a construí-los
- Descontos em várias instituições de ensino

## Contratação

CLT

## Como se candidatar

Você poderá se candidatar através [deste link ](https://bit.ly/3wZY5To) ou, se preferir, envie um email para [tatiana@remotar.com.br](mailto:tatiana@remotar.com.br).
OBS: esta vaga está sendo divulgada pela [Remotar](https://remotar.com.br/?utm_source=github) em nome da Zenvia, cliente de nossa empresa. No entanto, todo o processo seletivo será diretamente com a Zenvia, sem gargalos.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível

- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
