### ISSUE TITLE
[100% Remoto] Front-End Developer – Angular @Aegro

### ISSUE THREAD

**Issue by Stefany-Passos** [frontendbr/vagas#6717]
## Nossa empresa

A Aegro foi fundada por quatro cientistas da computação e é uma empresa apaixonada por evoluir o estado-da-arte da tecnologia para a agricultura.

## Descrição da vaga

Estamos buscando Pessoas Engenheiras de Software que atuem com Angular na construção e manutenção do nosso Design System e queiram encarar conosco o desafio de construir o primeiro unicórnio agtech brasileiro, nos ajudando nas principais decisões técnicas e seus impactos no produto no médio/longo prazo.Exemplo: Projeto bazinga em NodeJS, etc.

## Local

100% Remoto, com opção de trabalhar presencial em Porto Alegre/Florianópolis.

## Requisitos

- Ter escrito código em AngularJS e/ou Angular (TypeScript);
- Capacidade de produzir código limpo e de fácil manutenção;
- Nível médio de leitura e escrita em inglês;
- Experiência com design system.

**O que aumentam suas chances:**

- Conhecimentos em Design Patterns;
- Conhecimentos sólidos de arquitetura de software;
- Conhecimento de APIs RESTful;
- Experiência com frontend híbrido;
- Experiência ou conhecimento com testes de frontend;
- Experiência com metodologias ágeis (Scrum e Kanban);
- Contribuições em projetos open source;
- Participação em comunidades de tecnologia com palestras e afins.

## Benefícios

- Plano de Saúde Unimed Seguros;
- Plano Odontológico Unimed Seguros;
- Auxílio Home Office;
- VR ou VA;
- Gympass;
- Flexibilidade de horário;
- Acesso a plataforma da Alura para cursos de atualização.

## Contratação

CLT

## Como se candidatar

Você poderá se candidatar através [deste link ](https://bit.ly/3qSICAD) ou, se preferir, envie um email para [tatiana@remotar.com.br](mailto:tatiana@remotar.com.br).
OBS: esta vaga está sendo divulgada pela [Remotar](https://remotar.com.br/?utm_source=github) em nome da Aegro, cliente de nossa empresa. No entanto, todo o processo seletivo será diretamente com a Aegro, sem gargalos.

#### Alocação
- Remoto

#### Regime
- CLT

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
