### ISSUE TITLE
[Remoto] Desenvolvedor Front-end Pl/Sr @ Unidas

### ISSUE THREAD

**Issue by jsantosrh** [frontendbr/vagas#6720]
## Nossa empresa

 Unidas é a segunda maior locadora de veículos do Brasil e líder em locação de frotas para empresas. Possui grande paixão pelo seu trabalho, e aplica nele toda a inovação e a simplicidade que estão gravadas em seu DNA.

Buscam de maneira constante a melhoria da qualidade dos serviços ofertados, a satisfação de seus clientes e a valorização das pessoas que fazem parte da Companhia.

## Descrição da vaga

- Desenvolver e implantar sistemas baseados em requisitos e funcionalidades, com qualidade técnica;
- Atuar em SQUADs multidisciplinares de desenvolvimento ágil de software baseado em SCRUM / Kanban;
- Apoiar na administração dos ambientes dos produtos, prestar suporte técnico ao cliente, elaborar documentação técnica;
- Desenvolver softwares através do levantamento de dados e estudos das regras de negócios inerentes ao sistema e aplicação, dimensionando requisitos e funcionalidades de sistemas, prevendo taxas de crescimento, alternativas físicas de implantação e montando protótipos do sistema;
- Trabalhar junto a outros desenvolvedores e parceiros nos melhores moldes de desenvolvimento com foco nos objetivos dos produtos de software;
- Ser motivado por resultados e alcance de metas.

## Local

 Remoto 

## Requisitos

**Obrigatórios:**

- Conhecimentos de metodologias ágeis (SCRUM, Kanban), estimativas de software, técnicas de priorização, story points, User Storys;
- Conhecimentos de stacks tecnológicas, Javascript com Angular ou React;
- Conhecimentos sobre arquitetura de software (Frontend);
- Conhecimentos em HTML5, CSS3, Bootstrap4, Components, SASS;
- Conhecimentos sobre padrões de projeto como BDD, TDD, Clean, SOLID;
- Conhecimento de versionamento com Git / Azure DevOps.

## Benefícios

- Plano de Saude
- Plano Odontológico
- Seguro de Vida
- Gympass
- PLR
- VA
- VR
- Cursos
- Bônus Trimestral
- Cartão Farmácia
- GifCard Natal
- Material escolar
- Brinquedo

## Contratação

CLT

## Como se candidatar

Por favor envie um email para jnogueira@acelerarh.com.br com seu CV anexado - enviar no assunto: Desenvolvedor Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: jnogueira@acelerarh.com.br; ksouza@acelerarh.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
