### ISSUE TITLE
[BRASIL - REMOTO] Front-end Developer (REACT) PL na Sambatech [FULL-TIME]

### ISSUE THREAD

**Issue by daiaoli** [frontendbr/vagas#6723]
## Nossa empresa

A Sambatech está buscando uma pessoa **Front-end Developer Pleno (REACT)** para agregar ao nosso time! Procuramos alguém com propósito forte e que esteja disposta a trabalhar em ambiente colaborativo e dinâmico, pronto para crescer profissionalmente junto com a nossa equipe fora da curva!

A Samba gosta de fazer a diferença sempre e nosso time é o responsável para que isto aconteça! Por isso, a gente espera que você seja uma pessoa apaixonada por tecnologia, assim com a gente! Todas as nossas vagas também se aplicam a pessoas PCD, então fique à vontade para se candidatar.

## Descrição da vaga

Responsabilidades:

- Desenvolver e manter soluções de software.
- Escrever códigos limpos e funcionais no front-end;
- Participar dos ritos do projeto e propor novas soluções.
- Acompanhar o levantamento de requisitos.
- Trabalhar em conjunto com outros membros de equipe que fazem parte do projeto.
- Apoiar a realização de atividades dos profissionais de menor domínio técnico, repassando conhecimentos e atuando no desenvolvimento dos mesmos.
- Realizar integrações com APIs externas.
- Utilizar e modelar bancos de dados relacionais e/ou não-relacionais.

## Local

Remoto, Brasil.

## Requisitos

**Obrigatórios:**

- JS, React.js, Next.js, Typescript.
- Context API, Redux
- Jest, React testing library e Cypres
- REST, GraphQL
- TDD e SOLID

**Diferenciais:**

- Noções em Devops (uso de terminal linux, containers docker, processos de build e deploy automatizados, monitoria);
- Noções de modelo de testes unitários e integrados
- Noções de boas práticas de Engenharia de Software
- Noções em infra-estrutura em nuvem na AWS ou equivalente;
- Inglês intermediário

## Benefícios

- Ambiente criativo e inovador;
- Clima leve e descontraído;
- Horário flexível;
- Home office
- Auxílio home office
- Plano de Saúde;
- Plano Odontológico;
- Vale refeição/alimentação;
- Gym Pass;
- Day off no dia do aniversário
- Seguro de vida;
- Ways Education - Atividades extracurriculares para os filhos;
- Previdência privada.

## Contratação

CLT e 100% remoto [FULL-TIME].

## Como se candidatar

Por favor envie um email para stefany.gouveia@sambatech.com.br com seu CV anexado + pretensão salarial - enviar no assunto: Vaga Front-End Pleno 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.
E-mail para contato em caso de não haver resposta: stefany.gouveia@sambatech.com.br 

#### Alocação
- Remoto
#### Regime
- CLT
#### Nível
- Pleno

**Comment by JonathasGit** [comment]
Tem pra Junior?

**Comment by daiaoli** [comment]
Neste momento apenas Pleno Jonathas, mas neste link você consegue se inscrever no nosso banco de talentos! https://portal.kula.jobs/detail/460

**Comment by JonathasGit** [comment]
> Neste momento apenas Pleno Jonathas, mas neste link você consegue se inscrever no nosso banco de talentos! https://portal.kula.jobs/detail/460

Obrigado por informar.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
