### ISSUE TITLE
[100% Remoto] Senior React Native Developer | PJ - Builders 🤘🚀

### ISSUE THREAD

**Issue by Patriiciabrito** [frontendbr/vagas#6724]
Papo reto: aqui na Builders você irá se deparar com uma cultura voltada ao empreendedorismo. Os projetos, as pessoas e seu dia a dia serão norteados pela vontade de fazer acontecer. Suas ideias não serão descartadas, poderá ser agente de transformação, além de vivenciar uma estrutura de frontend idealizada apenas aqui na Builders. 👀 E aí, bora ser Builder?

**Tecnologias que se você dominar, vão gerar valor nos projetos 💻:**

- React Native (Redux/Mobx);
- TypeScript;
- APIs REST;
- Trabalhar com diferentes dimensões de dispositivo (tablet, celular, etc)
- Conhecimento geral do ambiente móvel;
- Versionamento de código com Git e Github;

**Como Builder, você terá acesso a:**

- Oportunidades reais de empreender e impactar;
- Fazer parte de uma comunidade de empreendedores; de ponta;
- Inovação e criação liberados;
- Participar de um processo único de geração de valor;
- Contribuir na criação de métodos disruptivos;
- Colocar suas ideias no mercado, na prática! :)
- Possibilidade de Profit share em novos Negócios;
- Prestador de Serviços (PJ).

**Como se candidatar:**

https://jobs.kenoby.com/sejabuilder

#remoto #reactnative #mobile

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
