### ISSUE TITLE
[Curitiba] Front-end Developer na Agência CUPOLA

### ISSUE THREAD

**Issue by Cupola001** [frontendbr/vagas#6725]
> Vaga Remota 

## Oiê!!
Que bom te ver aqui, espero que esteja bem!! 😃

Já pensou em trabalhar em uma empresa que está a cada dia transformando o mercado imobiliário, ajudando clientes a encontrarem a moradia dos sonhos?

**Prazer, nós somos a Agência CUPOLA.**

Vou te contar um pouquinho mais sobre a Cupola, para que possa se sentir em casa, blz?!

Primeiro de tudo, somos uma empresa Great Place to Work e estamos entre as 6 melhores empresas para se trabalhar no Paraná e uma das 50 melhores do Brasil. Ficamos muito felizes com essas posições, mas sempre gostamos de ir além e fomos consideradas pelo GPTW, ocupando o 1° lugar, como uma das melhores agências de comunicação do Brasil para se trabalhar.

Legal, né?! 😊

Nosso objetivo é transformar sonhos em realidade e transformar a vida de muitas pessoas. Há mais de 14 anos, estamos atuando como no mercado imobiliário, e somos referência nisso, viu?!

A cada dia estamos crescendo mais e mais e hoje, estamos em busca de um novo talento para ocupar a vaga de Pessoa Front-end Developer Pleno/Sênior.

Se você manda muito bem com Front-end Developer e quer transformar sonhos em realidade, vem com a gente!!

Vamos adorar conhecer tua história.

## Descrição da vaga

Nosso time de Desenvolvimento está precisando de reforço, e acreditamos que você possa nos ajudar!!
Dá uma olhada no que você irá fazer 😉~

- Desenvolver novas funcionalidades e componentes de forma fiel ao layout;
- Refatorar e otimizar a base de código, mantendo o débito técnico sob controle;
- Trabalhar em conjunto com a equipe visando desenvolver a plataforma com qualidade, (designer, back-end, BI, product owner, customer success);
- Corrigir bugs do sistema e trabalhar junto com a analista de customer success para dar suporte, tirando dúvidas e apoiando na resolução de problemas dos clientes.

## Local

Vaga remota

## Requisitos

- Experiência com HTML, CSS/SASS, Javascript / ES6+;
- Conhecimento do Framework JavaScript Vue.js 2;
- Conhecimento em consumo de APIs e Protocolo HTTP;
- Experiência em Git (de preferência GitHub);
- Familiaridade com metodologias ágeis, principalmente Scrum;

**_Você ganha pontos se tiver:_**

- Conhecimento na biblioteca de componentes Vuetify;
- Conhecimento com o Framework JavaScript Nuxt;
- Conhecimento de CI (Integração contínua) via GitHub Actions;
- Conhecimento/experiência com testes automatizados E2E com Cypress;
- Experiência usando o Figma, para inspecionar o layout e exportar os assets.
- Conhecimento das boas práticas de programação (Clean Code, SOLID, Revisão de código);

## Benefícios

- Vale refeição: R$450,00;
- Auxílio Home Office: R$100,00;
- Plano odontológico;
- Plano de Saúde - após o período de experiência;
- Programa de incentivo a educação;
- Hora do desenvolvimento;
- Dayoff de aniversário;
- Squad de Diversidade&Inclusão;
- PLR;
- Seguro de vida
- Licença maternidade e paternidade estendida & Cesta Natalidade
- E muitos outros.

## Contratação

- CLT

## Como se candidatar

Nossa vaga está na Gupy, clica no link e se candidata aí 😉
https://lnkd.in/e2zFbyru

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
