### ISSUE TITLE
[Campinas-SP] Front-end developer na ProScore

### ISSUE THREAD

**Issue by kevenjesus** [frontendbr/vagas#673]
## Descrição da vaga

A Proscore perdeu seu braço em front-end e não se deu muito bem com freelas e prestadores de serviço, agora está disposta a contratar um dev JR para fazer parte do time e resolver alguns problemas principalmente responsivo.

## Local

Presencial: Rua Frei Manoel da Ressurreição, 1488, Campinas - SP

## Benefícios

- Vale transporte
- Vale refeição

## Requisitos

**Obrigatórios:**
- Conhecimentos em HTML/CSS (design responsivo, Flexbox, organização)
- Noções básicas de Javascript (DOM)

**Desejáveis:**
- Experiência com PHP
- Consumo de API.

## Contratação

R$ 3.000 CLT ou R$ 4.000 PJ

## Nossa empresa

ProsScore é uma empresa existente a 17 anos no mercado, concorrente do Serasa e atua com seu time de tecnologia em Campinas/SP.

## Como se candidatar

Interessados enviar um email para falecom@keven.com.br

**Comment by danilosilvadev** [comment]
CV enviado.

**Comment by LFeh** [comment]
Ótima vaga :)

**Comment by kevenjesus** [comment]
Obrigado @LFeh realmente vaga bem legal... @danilosilvadev  obrigado vou analisar :)

**Comment by kevenjesus** [comment]
@LFeh vaga para backend node pode aqui ne?

**Comment by Pedro-Souza** [comment]
@kevenjesus posta aqui [backend-br](https://github.com/backend-br/vagas/)

**Comment by kevenjesus** [comment]
Valeu @Pedro-Souza vou postar 3 vagas lá :)

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
