### ISSUE TITLE
[São Paulo - Metrô Faria Lima] Front-end / Full Stack Developer @ Influu

### ISSUE THREAD

**Issue by influu** [frontendbr/vagas#6732]
## Nossa empresa

A Influu é uma agência de marketing de influência digital. Somos uma agência de atuação internacional que oferece soluções de ponta a ponta para empresas e influencers que querem ir mais longe.  Os melhores publis acontecem aqui!

## Descrição da vaga

Desenvolvimento da nova plataforma tecnológica da Influu. 
Sustentação, manutenção e implementação de melhorias em sistemas legados.

## Local

Escritório próximo ao metrô Faria Lima - Pinheiros

## Requisitos

**Obrigatórios:**
- Experiência em desenvolvimento com Vue.js
- Experiência com Node.js (Javascript / Typescript)
- Experiência em desenvolvimento web responsivo e adaptativo
- Experiência na construção e manutenção de APIs escaláveis 
- Experiência com bancos de dados relacionais como MySQL ou PostgreSQL
- Conhecimento de ferramentas de versionamento de código, como Git
- Capacidade de escrever código testável e eficiente aplicando as melhores práticas de desenvolvimento de software como S.O.L.I.D., Clean Code e design patterns

**Desejáveis:**
- Conhecimentos em cloud computing (AWS)
- Bom entendimento de metodologias ágeis 
- Bom entendimento da arquitetura MVC 
- Boas habilidades de resolução de problemas 
- Boas habilidades organizacionais (gerenciamento de tarefas)

**Diferenciais:**
- Docker
- Arquitetura de micro serviços
- AWS

## Contratação

PJ full time (presencial de segunda a sexta das 09:00 às 18:00)

## Como se candidatar

Por favor envie um email para ti@influu.me com seu CV anexo - enviar no assunto: Vaga front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Alocado (presencial)

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
