### ISSUE TITLE
[REMOTO] Pessoa desenvolvedora front-end na Evnts

### ISSUE THREAD

**Issue by evnts-dev** [frontendbr/vagas#6737]
## Nossa empresa

A Evnts é uma empresa de tecnologia para o setor de eventos, que se reinventou na pandemia para substituir com rapidez e eficiência sua tecnologia para eventos corporativos presenciais em uma tecnologia para eventos digitais que permite que agências e grandes empresas criem, gerenciem o dia a dia e administrem através de relatórios incríveis todos seus eventos em um só lugar. Com isto, conseguimos não apenas "sobreviver" e "passar por isto", mas fizemos o melhor ano de toda nossa história em todas as métricas financeiras e de negócio.

Cuidamos uns dos outros e entendemos que transparência, respeito e lealdade são características inalienáveis. Possuímos um ambiente de trabalho flexível, transparente e justo, onde todas as ideias são sempre bem-vindas ❤️. Medimos resultados por entregas e o mais importante, prezamos pelo equilíbrio entre vida pessoal e profissional. Isso é imprescindível para sermos nossas melhores versões e fazermos nossas entregas aos clientes com excelência.

Para conhecer mais da Evnts, acesse nosso site https://evnts.com.br/ e entenda o que fazemos e como colaboramos para que grandes empresas atinjam seus resultados. Você pode também escutar o podcast sobre a Evnts no canal “O Primo Rico” onde contamos um pouco de nossa história e como chegamos onde estamos https://spoti.fi/2LQ7BDq. Caso queira conhecer um pouco mais nossas ideologias e o que nos define: https://docs.google.com/document/d/1RDGuAd4FsScXlDI0oyvqRVpALra1Qk5OQ86vrOv85xw/edit?usp=sharing
 

## Descrição da vaga

Como um(a) Evnter do time de Desenvolvedores Front-end, você atuará com o desenvolvimento de novos projetos (utilizando React) e manutenção do atual, sendo responsável pelas boas práticas de Javascript/React, performance e usabilidade. Você será medido pela qualidade das suas entregas, preocupação com o código, responsabilidade e compromisso com as entregas feitas e com os testes feitos por você e por sua equipe.

## Local

Remoto

## Requisitos

**Obrigatórios**

- Habilidade analítica e realização de trabalho em equipe
- Experiência com React (framework javascript)
- Conhecimento em HTML e CSS

**Diferenciais**

- Gestão/cursos de metodologia ágil (SCRUM, XP entre outros)
- Arquitetura frontend
- Conhecimento de backend (node)
- Experiência com Javascript (com orientação a objetos)

## Benefícios

- Integrará um time composto por excelentes profissionais com diversos backgrounds
- Liberdade para propor e ver acontecer melhorias contínuas no seu dia-a-dia de trabalho e na operação
- Plano de Saúde e Odonto Sulamérica
- Vale Refeição e Vale Alimentação
- Ambiente informal e descontraído
- Cultura forte de feedback

## Contratação

CLT ou PJ a combinar (preferência por CLT)

## Como se candidatar

Por favor envie um email para [vagas@evnts.com.br](mailto:vagas@evnts.com.br) com seu CV ou LinkedIn (fique a vontade para adicionar Github, Portifólios, ou outros se quiser) com o título:  \`Pessoa desenvolvedora Front-End | Evnts - [${seuNome}]\` 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: [vagas@evnts.com.br](mailto:vagas@evnts.com.br) ou [contato@evnts.com.br](mailto:contato@evnts.com.br)

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

#### Tecnologias
- React
- Node
- MongoDB
- Firebase

**Comment by JonathasGit** [comment]
Top a vaga.

**Comment by dericparra** [comment]
Opa, ja me candidatei

**Comment by GuScarpim** [comment]
Muito bom!

**Comment by Juninhoww2** [comment]
like

**Comment by saymondamasio** [comment]
Mandei lá

**Comment by gpmotta21** [comment]
Enviei minhas informações, espero que ainda estejam aceitando candidatos.

**Comment by CleitonRReis** [comment]
Mandei minha candidatura! 🙌🏻

**Comment by volpatocode** [comment]
Enviado
