### ISSUE TITLE
[Amsterdã - Holanda] Front-end developer at Booking.com

### ISSUE THREAD

**Issue by henriquehsv** [frontendbr/vagas#674]
## Job description

Our guiding principle is that by helping our users we help our business. As a Developer in the Front End team you’ll be a key part of the idea generation process, working in small startup-like teams that take full ownership of their part of our platform. You’ll work side by side with designers, back end developers, product owners, copywriters and user researchers to conceive, analyze, hand code & test your ideas. You’ll be given the freedom to make meaningful and measurable improvements impacting millions of users.

## Local

Full-time position, Amsterdã - Holanda

## B.offered - Benefits and Perks

We are a performance-based company that offers career advancement and lucrative compensation, including bonuses and stock potential.  We offer what we call the “Booking Deal” with other competitive perks and benefits.  IT also has regular tech talks, training and attends/speaks at global conferences.

This position is open to worldwide candidates and in the case of relocation, we will assist you with a generous relocation package, ensuring a smooth transition to working and living in Amsterdam.  We have successfully relocated 200+ IT professionals to Amsterdam in the last year!

## B.skilled - Desired Skills

- 4+ years of experience in a relevant role, preferably in a commercial environment
- Expert understanding of core front-end web technologies (JavaScript, HTML, CSS)
0 Experience with JavaScript libraries such as JQuery
- Experience with templating languages
- Ability to write high-performance, reusable code
- Experience troubleshooting cross-browser compatibility issues
- Experience with data-driven product development: analytics, A/B testing, etc
- Knowledge of version control systems
- Comfortable working on a command line
- Excellent English communication skills, both written and verbal

## About Booking.com

Booking.com is looking for Front End Developers all around the globe! Join us at our beautiful headquarters in Amsterdam and work on planet Earth’s #1 accommodation website with some of the industry’s smartest people!

## How to apply

You can submit your CV through this link: http://grnh.se/s8gdj41
#

*P.S. Estou a disposição para tirar dúvidas sobre a vaga por email ou Hangouts*

**Comment by matheusiacono** [comment]
The link to apply is broken.

**Comment by henriquehsv** [comment]
Fala @matheusiacono. Isso quer dizer que não estão mais aceitando currículos pra essa vaga. Vou fechar a issue.

**Comment by henriquehsv** [comment]
A vaga pra front-end developer está aceitando currículos novamente.

**Comment by henriquehsv** [comment]
Vaga aceitando currículos mais uma vez!

**Comment by henriquehsv** [comment]
Se alguém chegar a vir pra entrevista presencial pode me mandar um email ou hangouts que a gente sai pra tomar um café :)

**Comment by DawTaylor** [comment]
@henriquehsv consegue me confirmar o recebimento da minha aplicação?
Enviei por um link que tinha salvo e to em dúvida se não era um link antigo e se preciso enviar de novo.

**Comment by henriquehsv** [comment]
@DawTaylor sua aplicação foi recebida sim, uns três dias atrás. O link é o mesmo, o pessoal do RH desativa quando não tá aceitando currículo.
