### ISSUE TITLE
[Remoto] Frontend Developer na Leadlovers

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6740]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/pessoa-desenvolvedora-frontend-190546153?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>A Leadlovers</strong> busca pessoa <strong>Frontend Developer </strong>para compor seu time!</p>
<p>Em mais de 47 países, impactamos mais de 13.000 empreendedores, ajudando a tornar seus projetos digitais ainda mais rentáveis. Nossas ferramentas para automação de marketing digital oferecem funcionalidades para dar início e escalar estratégias de venda. Temos orgulho de fazer parte da transformação digital em diversos segmentos.</p>
<p>Certificados pela Great Place to Work Brasil como um excelente lugar para trabalhar, buscamos proporcionar qualidade de vida para todos os llovers, que diariamente colocam a mão na massa em busca dos melhores resultados. Celebramos nossa cultura descontraída, colaborativa e que valoriza as pluralidades.&nbsp;&nbsp;</p>

## Leadlovers: 
 <p>Em mais de 47 países, impactamos mais de 13.000 empreendedores, ajudando a tornar seus projetos digitais ainda mais rentáveis. Nossas ferramentas para automação de marketing digital oferecem funcionalidades para dar início e escalar estratégias de venda. Temos orgulho de fazer parte da transformação digital em diversos segmentos.</p>
<p>Certificados pela Great Place to Work Brasil como um excelente lugar para trabalhar, buscamos proporcionar qualidade de vida para todos os llovers, que diariamente colocam a mão na massa em busca dos melhores resultados. Celebramos nossa cultura descontraída, colaborativa e que valoriza as pluralidades.&nbsp;&nbsp;</p><a href='https://coodesh.com/empresas/leadlovers'>Veja mais no site</a>

 ## Habilidades: 
 - React.js 
- Javascript 
- CSS 
- HTML
## Local: 
 100% Remoto
## Requisitos: 
 - Sólido conhecimento em JavaScript, CSS e HTML 
- Desenvolvimento front-end utilizando ReactJS 
- Conhecimentos em desenvolvimento responsivo 
- Noções de usabilidade UX e UI 
- Conhecimentos em GIT 
- Conhecimento em micro front-ends
## Diferenciais: 
 - Experiência com material-UI 
- Conhecimento em princípios de design system
## Benefícios: 
 - Benefícios flexíveis com saldo em cartão corporativo (educação, mobilidade, saúde, bem-estar, cultura e entretenimento) 
- Plano de saúde e odontológico com cobertura nacional para você e cônjuge 
- Vale-refeição ou vale-alimentação 
- Seguro de vida sem descontos 
- Horários flexíveis 
- Auxílio creche 
- Clube de descontos 
- Terapia e meditação online 
- Convênio com universidades 
- Day off durante seu mês de aniversário
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Developer na Leadlovers](https://coodesh.com/vagas/pessoa-desenvolvedora-frontend-190546153?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
