### ISSUE TITLE
[Remoto] Frontend React Developer (Sênior) na Palqee Technologies

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6741]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/senior-frontend-developer-react-graphql-085615560?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>At Palqee, we are changing the way companies operationalise Privacy, Data Protection and Data Governance, helping them build trusted relationships with their customers and partners to grow their businesses.</p>
<p>We're obsessed with easy data protection controls, ethical data management and responsible innovation. We are backed by some of Europe's and Brazil's best investors and have been named one of the best Privacy Technology companies to buy from and work for in the UK. We are experiencing impressive growth with a solid product-market fit, clients in the UK &amp; Brazil and an amazing team! 🚀🚀🚀</p>
<p>We are seeking an exceptional Front-end engineer who wants to be part of bringing innovation, creativity, and security to the data privacy world. You are motivated in delivering well documented, clean, and efficient code with a passion and curiosity for the art of programming. You enjoy living by the code of your craft and developing mind-blowing solutions for complex problems. You are a true techie at heart.</p>
<p>As one of the first key hires to grow our teach team, you will report directly to the CTO and have influence and real impact in an early stage start-up on the expansion of our engineering team to build products and features that accelerate our traction.</p>
<p>You enjoy collaborating with different Team members and can turn ideas into tangible solutions but can also work independently with speed and efficiency.</p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>

## Palqee Technologies: 
 <p>At Palqee, we are changing the way companies operationalise Privacy, Data Protection and Data Governance, helping them build trusted relationships with their customers and partners to grow their businesses.</p>
<p>We're obsessed with easy data protection controls, ethical data management and responsible innovation. We are backed by some of Europe's and Brazil's best investors and have been named one of the best Privacy Technology companies to buy from and work for in the UK. We are experiencing impressive growth with a solid product-market fit, clients in the UK &amp; Brazil and an amazing team! 🚀🚀🚀</p><a href='https://coodesh.com/empresas/palqee-technologies'>Veja mais no site</a>

 ## Habilidades: 
 - React.js 
- GraphQL 
- Amazon AWS 
- HTML 
- CSS 
- Typescript
## Local: 
 100% Remoto
## Requisitos: 
 -  Related professional experience in a structured, process-driven environment 
- Experience coding HTML, CSS, Javascript and other UI technologies with a portfolio of your work 
- Experience developing in React 
- Experience working with GraphQL 
- Experience with a variety of JavaScript frameworks and libraries such as: Apollo Client, NextJS, Typescript and testing with Jest, Cypress, and Chai 
- Experience with Agile development process and lean methodology 
- Experience with GIT and workflows (Gitlab) 
- Experience implementing web applications from a provided list of requirements and design mock-ups 
- Outstanding verbal and written communication in English 
- Great interpersonal skills - experience working with, mentoring and collaborating with international team members 
- Must be responsive, detail oriented and have a strong sense of appropriate planning for meeting deadlines 
- Strong sense of ownership and accountability 
- Experience in bringing multiple viewport responsive and adaptive web designs to life 
- Awareness and practice of UI performance best practices 
- Able to bridge communication between technical and non-technical stakeholders and customers 
- Enjoy working in a cross-functional team 
- Excellent autonomous problem-solving ability 
- Work efficiently in an environment where not everything is organized and structured

## Benefícios: 
 - Health Insurance 
- Stock Options 
- Be a part of a fast-growing technology startup and shape the future of privacy and data protection 
- Remote work + Flexi-hours 
- Annual Palqee Employees Summit 
- Monthly get togethers 
- Tickets for the best conferences in the industry 
- Budget for training, material and development 
- Opportunity to enrich our Spotify playlist
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend React Developer (Sênior) na Palqee Technologies](https://coodesh.com/vagas/senior-frontend-developer-react-graphql-085615560?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
