### ISSUE TITLE
[Remoto] Front-end Developer React Sr na Invillia

### ISSUE THREAD

**Issue by gihhlazaro** [frontendbr/vagas#6743]
- **INVILLIA**
Aproxime-se. A Invillia não apenas transformou a forma como as empresas mais revolucionárias do mundo criam e desenvolvem estratégias, negócios e produtos digitais.
Inovou também a maneira como pessoas apaixonadas por tecnologia, de qualquer lugar do planeta, podem interagir, evoluir, mais conectados do que nunca.
Para a Invillia, não importa onde você está. Se é um país grande. Ou uma cidade pequena. E sim a sua vontade. As suas ideias. O seu potencial.

O tamanho do seu talento_

- **REQUISITOS**
- Git
- Javascript
- Estilização e layout de páginas web (Sass, styled-components, tailwind)
- Acessibilidade
- React
- Gerenciamento de estado da aplicação (Redux, Context, VueX, RxJS, react-query, recoil, jotai, etc)
- Testes automatizados (ex: unitário, integração, E2E, Jest, @testing-library)
- Experiência de desenvolvimento (ESLint, Prettier, Typescript, Readme, Docs, CI/CD, onboarding, automations, git hooks.)
- Boas práticas de qualidade de código (Clean Code, S.O.L.I.D, Design patterns, dumb e smart components, etc)
- Tipos de renderização (Client-side rendering, Server-side rendering, Static generation, ou abordagens mistas)
- Monitoramento de erros e coleta de dados (TrackJS, Sentry, Datadog, Google Analytics, etc)

- **Competências desejáveis:**
- Linguagens tipadas (ex: Flow/TypeScript)
- Análise de performance (Métricas de performance, ferramentas como lighthouse e sonar, boas práticas como lazy loading, cache, CDN, memory leaks, bundle optimizations etc)
- Escalabilidade

- **RESPONSABILIDADES**
Será responsável em prover soluções técnicas para novas features e dar o suporte necessário as features já existentes, afinal, nem tudo são flores.
Esperamos também que essa pessoa auxilie os outros membros do time em questões técnicas não esquecendo de fornecer a melhor solução para o negócio.
Algo que prezamos bastante é qualidade, isso inclui um código limpo e legível (clean code).
Também é desejável que o mesmo tenha um perfil intra-empreendedor, onde seus objetivos estejam alinhados com os objetivos da empresa, afinal, temos muito orgulho do que fazemos aqui!

- **LOCAL**
Full remoto

- **REGIME**
CLT

- **COMO SE CANDIDATAR**
Enviar o currículo atualizado para [giovanna.lazaro@invillia.com](mailto:giovanna.lazaro@invillia.com)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
