### ISSUE TITLE
[REMOTO] DESENVOLVEDOR ANGULAR NO INFOVAGAS

### ISSUE THREAD

**Issue by patyandreolli** [frontendbr/vagas#6744]
**DESENVOLVEDOR ANGULAR**
Experiência com: Angular JS e Angular 9+
Conhecimentos avançados em: Javascript, Typescript, Consumo de API's em Nodejs
Experiência com embbeded de ferramentas de BI capturando conteúdo serializado ou binário de páginas. 
Conhecer API's de ferramentas de BI e construção de telas dinâmicas. 

Prazo: Indeterminado
Contratação: PJ
Local: Home Office 

Interessados enviar currículo para recrutamento@infovagas.com  indicando no assunto "Desenvolvedor Angular"

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
