### ISSUE TITLE
[Hibrido / Rio de Janeiro - RJ] Fullstack Developer na Deepservice 

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6745]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-174152615?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>A Deepservice</strong> busca pessoa <strong>Fullstack Developer</strong> para compor seu time!</p>
<p>A Deepservice está no mercado há mais de 7 anos, entregando resultados em consultoria em diversas organizações e empresas. Atuando de forma contínua, com excelência junto aos clientes e parceiros.</p>
<p><strong><ins>Responsabilidades e atribuições:</ins></strong></p>
<ul>
<li>Manutenção e ajustes do site da empresa</li>
<li>Descritivo e fotos de produtos&nbsp;</li>
<li>Alteração, sempre que necessário do banner do site</li>
<li>Propor melhorias para o site (funcionalidade, navegação etc.)</li>
<li>Manutenção, ajustes e funcionalidade do painel de sellers: plataforma desenvolvida exclusivamente para a empresa&nbsp;</li>
<li>Gerenciamento da área de tecnologia da empresa, estruturando e compondo a área de acordo com as necessidades e demandas da empresa.&nbsp;</li>
</ul>
<p></p>
<p></p>
<p></p>

## Deepservice : 
 <p>A Deepservice está no mercado há mais de 7 anos, entregando resultados em consultoria em diversas organizações e empresas. Atuando de forma contínua, com excelência junto aos clientes e parceiros.</p>
<p>Nossa consultoria é abrangente, oferendo soluções com tecnologia e eficiência, em processos de gestão de pessoas, recrutamento e seleção e demais consultorias na área de pessoal.</p><a href='https://coodesh.com/empresas/deepservice'>Veja mais no site</a>

 ## Habilidades: 
 - .NET Core 
- Vue.js 
- MySQL 
- Magento
## Local: 
 Rio de Janeiro - RJ
## Requisitos: 
 - Perfil de uma pessoa Empreendedora; 
- Pessoa Auto-gerenciável; 
- Pró-ativo(a)

## Benefícios: 
 - Horários Flexíveis 
- Autonomia de trabalho e decisão 
- Gerenciamento de melhorias e manutenção 
- Possibilidade de stock options
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack Developer na Deepservice ](https://coodesh.com/vagas/desenvolvedor-174152615?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Regime
PJ
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
