### ISSUE TITLE
[Remoto] Frontend Developer  na Let's Comunicação e desenvolvimento

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6746]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-front-end-182737847?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>A Let's Comunicação</strong> busca pessoa <strong>Frontend Developer</strong> para compor seu time!</p>
<p>Nível Pleno.</p>
<p>Conhecimentos em react, react hooks, html, css, integração com API REST, typescript. Desejável: redux</p>
<p>Contratação PJ.</p>
<p>Jornada de 8h diárias.</p>
<p>Contrato inicial de 3 meses (8h/dia), renovação de acordo com desempenho.</p>
<p></p>

## Let's Comunicação e desenvolvimento: 
 <p>Soluções de Desenvolvimento Web/Mobile, em páginas ou sistemas, desenvolvimento de Marca, comunicação e design, dentre outros serviços.</p>
</p>

 ## Habilidades: 
 - Web API 
- Javascript/Typescript 
- React Hooks 
- React.js 
- React Native 
- CSS 
- HTML5 e CSS3 
- Redux
## Local: 
 100% Remoto
## Requisitos: 
 - Ser habituado com metodologias ágeis 
- Ser habituado com times distribuídos remotamente 
- Gerir o próprio tempo

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Developer  na Let's Comunicação e desenvolvimento](https://coodesh.com/vagas/desenvolvedor-front-end-182737847?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
