### ISSUE TITLE
[Remoto] Front-End Developer na RBR DIGITAL LTDA

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6747]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-211305260?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>A RBR DIGITAL </strong>busca pessoa <strong>Frontend Developer </strong>para compor seu time!</p>
<p>Somos uma agência da web centrada no desempenho que se preocupa em entender o seu negócio e, em seguida, criar uma solução personalizada para ajudar a atender às suas necessidades.&nbsp;</p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>

## RBR DIGITAL LTDA: 
 <p>We’re a performance-centered web agency that cares about understanding your business, then crafting a custom solution to help meet your needs. We approach every project with a performance mindset, ensuring that your project performs for you, your user, and your team.</p>
</p>

 ## Habilidades: 
 - Javascript 
- React.js 
- REST APIs
## Local: 
 100% Remoto
## Requisitos: 
 - Conhecimento em Javascript, ReactJS; 
- Conhecimento do funcionamento e integração de APIs REST; 
- Conhecimento básico em segurança de APIs.
## Diferenciais: 
 - Experiência com desenvolvimento orientado a Testes (TDD, BDD) 
- Conhecimento em desenvolvimento em NextJS (SSG, SSR e ISR)
## Benefícios: 
 - Horário Flexivel 
- Aulas de Inglês 
- Chances de crescimento  
- Ambiente Colaborativo. 
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Front-End Developer na RBR DIGITAL LTDA](https://coodesh.com/vagas/frontend-211305260?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
