### ISSUE TITLE
[Remoto] Frontend React Developer na Docsie.io

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6749]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-react-developer-121102258?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Docsie.io está buscando <strong>Frontend React Developer</strong> nível júnior e pleno para compor sua equipe!</p>
<p>Reunimos equipes e ferramentas de produto, suporte e desenvolvimento em um único sistema de gerenciamento de conhecimento alimentado por IA. Para quebrar silos e criar um fluxo de trabalho fluido de captura, criação e compartilhamento do conhecimento alimentado por IA.&nbsp;</p>

## Docsie.io: 
 <p>Reunimos equipes e ferramentas de produto, suporte e desenvolvimento em um único sistema de gerenciamento de conhecimento alimentado por IA. Para quebrar silos e criar um fluxo de trabalho fluido de captura, criação e compartilhamento do conhecimento alimentado por IA.&nbsp;</p>

</p>

 ## Habilidades: 
 - React.js 
- HTML5 / CSS3 
- Typescript 
- Javascript
## Local: 
 100% Remoto
## Requisitos: 
 - Bons conhecimentos em HTML5, CSS3 
- Conhecimento em javascript Frontend 
- Conhecimento em framework ReactJS 
- Conhecimento em TypeScript

## Benefícios: 
 - Oportunidade de atuar em uma empresa internacional 
- Horários Flexíveis 
- 100% Remota
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend React Developer na Docsie.io](https://coodesh.com/vagas/frontend-react-developer-121102258?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
