### ISSUE TITLE
[São Paulo] Front-End Developer no Grupo KRS

### ISSUE THREAD

**Issue by amandamussio** [frontendbr/vagas#675]
## Descrição da vaga
Tá a fim de criar e desenvolver para diversos nichos, é proativo, trabalha bem em equipe e quer entrar em contato com diversas tecnologias? 
Então manda pra gente um currículo e vem bater um papo com a gente.

## Atividades
Procuramos um desenvolvedor júnior e um pleno para atuar na resolução de bugs, melhorias e novas features em projetos que já estão em produção e no desenvolvimento de novos projetos.

## Local
Rua Diamantina, 538 - Vila Maria, São Paulo - SP

## Benefícios
- Vale Transporte;
- Restaurantes conveniados;
- Projeto qualidade de vida;
- Festinha final do mês;

#### Diferenciais
- monte a sua máquina como desejar

## Requisitos

**Obrigatórios:**
- HTML5 
- CSS3
- Javascript
- Bootstrap 3 ou 4
- Design Responsivo
- Mobile First
- Git
- Gulp
- SASS

**Desejáveis:**
- React
- Wordpress (Configuração de temas)

## Contratação
Regime CLT. 
Faixa salarial Pleno - R$3.600,00 a R$5.000,00

## Nossa empresa
http://www.grupokrs.com.br

## Como se candidatar
Por favor envie um email para curriculos.ti@grupokrs.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Pleno

**Comment by LFeh** [comment]
Parabéns por divulgar a faixar salarial 👏

**Comment by danilosilvadev** [comment]
@amandamussio fazem entrevista via skype?

**Comment by amandamussio** [comment]
Júnior contratado. Precisamos apenas de pleno agora.

**Comment by amandamussio** [comment]
@danilosilvadev Por procedimentos burocráticos da empresa, como preenchimento de papelada e testes infelizmente não. Obrigada!

**Comment by sdq-sts** [comment]
Marcaram uma entrevista comigo pra amanhã sendo que já contrataram uma pessoa. Então tá, né. 👍

**Comment by DawTaylor** [comment]
@sdq-sts acho que tua entrevista é pra pleno não?

`Precisamos apenas de pleno agora.`
https://github.com/frontendbr/vagas/issues/675#issuecomment-347562636

**Comment by amandamussio** [comment]
@sdq-sts Consideramos seu currículo e seus conhecimentos como nível pleno. Sua entrevista é para essa faixa salarial.

**Comment by amandamussio** [comment]
@DawTaylor Obrigada pelo possível esclarecimento!

**Comment by sdq-sts** [comment]
@amandamussio @DawTaylor Eu conversei com a Daniele e ela me explicou, obrigado pela resposta super rápida.

**Comment by amandamussio** [comment]
Ambos contratados. Obrigada pessoal!
