### ISSUE TITLE
[Remoto] Front-end Developer Senior na Gupy

### ISSUE THREAD

**Issue by Karolynnenogueira** [frontendbr/vagas#6750]
## Nossa empresa

Na Gupy nós somos comprometidos em ter um ambiente seguro para que todas as pessoas sejam livres para serem elas mesmas e fazemos de tudo para que cada uma consiga dar o seu melhor de forma saudável com um bom equilíbrio de vida.

Somos apaixonados por fazer o que gostamos e seguir o caminho para nossos sonhos, ajudando e colaborando para mudar a vida de milhões de pessoas para melhor.

Se você deseja encontrar um lugar para se desafiar e amadurecer profissionalmente você está no lugar certo, temos vários desafios e oportunidades de amadurecimento onde exige que você busque criatividades, inovações, aprendizados e novas maneiras de resolver os mesmos problemas.

Diversidade

Na Gupy, a gente acredita que só alcançaremos o nosso propósito de ter cada vez mais gente realizada em suas jornadas profissionais com um time diverso e um ambiente inclusivo. Afinal, queremos que Gupiers também sejam pessoas realizadas por aqui! Por isso, reforçamos que todas as nossas vagas estão abertas para pessoas de grupos de diversidade e/ou minorizados e também para qualquer região do Brasil (ou fora!).

Assim, mantemos compromisso com o nosso propósito e ainda podemos construir produtos mais acessíveis e inclusivos que alavanquem a empregabilidade do Brasil.

## Descrição da vaga

- Desenvolvimento de novas telas utilizando HTML, CSS, JavaScript, React e SASS;
- Monitorar a saúde das nossas aplicações;
- Contribuir com evoluções arquiteturais;
- Ajudar com resoluções e melhorias em débitos técnicos;
- Propor novas ideias e soluções arquiteturais reutilizáveis;
- Identificar melhorias no design de nossos componentes;
- Participação na direção estratégica no time de engenharia;
- Mentorar e ajudar pessoas a crescerem e evoluírem na carreira;
- Identificar gargalos e melhorias de performance em nossas páginas;
- Ser referência em relação a boas práticas durante a construção e componentização;
- Garantir que nosso bundle carrega aquilo que precisa e continua enxuto;
- Garantir que nossas telas continuem ou melhorem a responsividade;
- Garantir que nossas telas continuem ou melhorem a acessibilidade;
- Experiência com Webpack;
- Experiência com Babel;

Desafios

- Melhorias em nossas métricas atuais, diminuindo tempo de carregamento das nossas páginas;
- Escalabilidade de aplicações web;
- Separação de nosso monólito para uma arquitetura micro front-ends e componentização;
- Próximos passos com nossa evolução e sonho arquitetural;
- Times autônomos e independentes com baixo acoplamento, custo de coordenação e gargalos de comunicação.

## Local

Exemplo: 100% remota 

## Requisitos

- Experiência como profissional de tecnologia;
- Experiência com arquitetura e design de aplicações web;
- Experiência com testes.

**Diferenciais:**

- +3 anos de experiência como profissional de tecnologia;
- +3 anos com desenvolvimento em aplicações React;
- Experiência com gerenciamento de estados;
- Experiência com processos ágeis;
- Experiência com responsividade;
- Experiência com acessibilidade;
- Experiência com design system;
- Experiência com micro front-end.

## Benefícios

- Flexibilidade nos seus horários (sim, mesmo no Home Office);
- Vale Refeição no cartão Caju;
- Plano médico totalmente custeado pela Gupy para você e dependentes;
- Plano odontológico;
- Auxílio Home Office;
- Focamos em apoiar a saúde mental através de nossos benefícios com o Zenklub;
- Focamos em apoiar a saúde física através de nossos benefícios com a Gympass;
- Licença Maternidade de 6 meses;
- Licença Paternidade de 6 meses;
- Licença Casamento de 5 dias;
- Oportunidade de sociedade;
- Gupy Coin com resgate de prêmios (Vale Netflix, Vale Spotify, Vale Pizza, Vale Gamer, Vale Jantar Romântico);
- Dayoff para aniversários.
- Short Friday - Nas sextas trabalhamos só por meio período;
- Crédito Consignado Creditas: parcelas descontadas direto na folha de pagamento e juros baixos
- Educação Financeira Creditas: conteúdos para você focar na sua educação financeira
- Creditas Store: uma loja para você comprar produtos ou adquirir serviços efetuando o pagamento direto na sua folha de pagamento! 
- Subsidiamos uma parte da mensalidade com o Férias&Co: Créditos anuais para você organizar suas viagens de férias comprando hospedagens e passagens pelo Brasil e pelo mundo via assinatura! Lembrando que você quem decide se quer contratar a assinatura

## Contratação

CLT
## Como se candidatar

Você pode se candidatar através da nossa página de carreiras: [https://tech-career.gupy.io/job/eyJqb2JJZCI6MTY4ODE0Miwic291cmNlIjoiZ3VweV9wdWJsaWNfcGFnZSJ9?jobBoardSource=gupy_public_page](

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

## Labels
- Remoto
- CLT
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
