### ISSUE TITLE
[Remoto] Front-end / back / Fullstack Developer na WeOpen

### ISSUE THREAD

**Issue by Tuanesds** [frontendbr/vagas#6751]
> Vaga Remota

## Nossa empresa
WeOpen, empresa de tecnologia CRM em crescimento

## Descrição da vaga

Desenvolverá softwares  voltados para o seguimento de CRM, necessário para execução das atividades propostas dentro dos desenvolvimentos dos sistemas é necessário conhecer as linguagens abaixo focado em Frontend:
Front End: Asp.net web.forms, asp.net mvc, html, java script (jquery), css3 com bootstrap e
windows forms e C#
Back End: Criação de webservices, apis rest, serviços windows, entity framework, dapper
banco de dados: conhecimento de programação de procedures em oracle e sql
Desejável conhecimentos em framework de front-end,
Diferencial automação usando Selenium.

## Local

Vaga Home Office

## Requisitos

- Possuir experiência com Frontend, back e Fullstack
- Ter conhecimento do C# CSS, Javascript
- Ter atuado com desenvolvimento de plataformas web

## Benefícios

- Férias remuneradas
- Auxílio equipamento de HO
- VR ou VA
- Bonificação Anual

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um e-mail para recrutamento@weopen.com.br com seu CV anexado - enviar no assunto: Vaga DEV

#### Alocação

- Remoto

#### Regime

- PJ

#### Nível

- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
