### ISSUE TITLE
[REMOTO] Desenvolvedor(a) Front-end na Olery B.V.

### ISSUE THREAD

**Issue by hugomelo** [frontendbr/vagas#6752]
## Nossa empresa
Olery B.V. é uma empresa holandesa que coleta, analisa e distribui dados focados em turismo. A empresa tem hoje 2 desenvolvedores brasileiros. Por a empresa ser européia, nosso horário de começo de trabalho costuma ser mais cedo. 
https://olery.com/

Nós desenvolvemos diferentes ferramentas para a indústria do turismo no mundo. Vendemos dados para governos (secretarias de turismo), empresas de viagens (destinos) e redes de hotéis que querem fazer administração de sua reputação. Temos APIs de dados, paineis com análises, fazendo análise automática de sentimento de textos de reviews e geramos relatórios.

## Descrição da vaga
Atualmente, temos usado bastante o VueJS para reescrever nossos dashboards e precisamos de mais braços :smile: 
Temos uma API que serve dados para o frontend, que é feita em Ruby/Sinatra.
Temos reuniões de standup 7:30 da manhã. Fora isso, o ritmo de trabalho é bastante flexível e o pagamento feito mensalmente pelas horas trabalhadas.

## Local
Remoto

## Requisitos

**Obrigatórios:**
- 3 anos de experiência em JS
- Experiência em estilização e layout de páginas web (Sass)
- Git básico
- Inglês fluente

**Desejáveis:**
- Desejável alguma experiência em VueJS
- Conhecimentos em Ruby
- Experiência em Testes automatizados

**Diferenciais:**
- Projetos opensource
- ElasticSearch
- PostgreSQL

## Benefícios
- Horas flexíveis

## Contratação
PJ

## Salário
15 euros por hora

## Como se candidatar
Por favor, envie um email para jobs@olery.com com seu CV anexado ou Linkedin. Importante, coloque o seu perfil no Github

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 4 dias úteis após recebimento de CV.

#### Alocação
Remoto

#### Nível
Júnior ou Pleno

**Comment by thismarcoantonio** [comment]
Como o nível pode ser júnior se precisa ter 3 anos de experiência?
