### ISSUE TITLE
[BRASIL - REMOTO] Front-end Developer Angular | Hit-Game

### ISSUE THREAD

**Issue by JoseCastellaniNeto** [frontendbr/vagas#6753]
## Nome da Empresa 

Hit-Game
https://hit-game.com/

Setor: Entretenimento Esportivo

## Descrição 
A nossa equipe está crescendo e você terá a oportunidade de participar de uma equipe multidisciplinar do Hit - uma nova plataforma social que conecta fãs de esportes para dar suas opiniões, precificá-las e transformá-las em emoção! - Você terá que solucionar problemas desafiantes para trazer eventos reais para o ambiente digital onde as pessoas possam usar seus conhecimentos para se desafiarem.

## Responsabilidades 
Atuar nos projetos de desenvolvimento dos sistemas Web da empresa e na montagem de documentação e manuais.

## Local

Brasil

## Requisitos

**Obrigatórios:**
- 1 ano de experiência com Angular

**Desejáveis:**
- conhecimentos em NodeJS

## Contratação

PJ 

## Como se candidatar

Por favor envie um email para jose.neto@escalate.com.br com seu CV anexado - enviar no assunto: Vaga Angular

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.

## Labels
Angular

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
