### ISSUE TITLE
[REMOTO] Front-end Developer na Reclame AQUI

### ISSUE THREAD

**Issue by mateusalexandre** [frontendbr/vagas#6754]
## Descrição da vaga

O Reclame AQUI é a maior plataforma de solução de conflitos entre consumidores e empresas da América Latina! Durante 20 anos de história, temos ajudado a tornar mais simples, fácil e transparente esse relacionamento. 

Somos uma grande vitrine para as empresas. São 1,5 bilhão de page views/ano no site
Atualmente, estão cadastrados no site mais de 30 mil consumidores e 500 mil empresas
O Reclame AQUI é o 5º site brasileiro mais acessado, segundo o [alexa.com](https://alexa.com/)

E estamos em busca de Front-end Developer para fazer parte do nosso time

## Trabalhamos com pessoas que:

Gostam de mudar o mundo, assim como nós, e ajudar as pessoas
Pensam diferente, mas respeitam as diferenças
Sejam criativas para solucionar e superar os desafios do dia-a-dia
Não têm medo de mudanças
Sabem o seu valor e são gratas
Acreditam que através da ética, reputação e transparência é possível melhorar as relações de consumo

## O que esperamos de você:
- Implementação de software focado na camada de apresentação

- Implementação de aplicações responsivas e adaptativas usando Sass ou similar

- Implementação da camada de negócio usando patterns atuais (Spa, Components, etc) usando as frameworks Angular, React, Vue ou similar

- Implementar testes unitários

- Implementar integração com APIs públicas e privadas fazendo uso de modelos diversos de autenticação (Basic, Oauth, Session based, cookie based, Token based, etc.)

- Implementar configuração de task management para automação de empacotamento (webpack, Gulp, Grunt, etc)

- Implementar automação de implantação (salt, ansible, docker, kubernetes, etc)

**Diferenciais:**
- projetos opensource

## Local

Remoto

## Benefícios

- Auxílio Creche: Porque mamães e papais precisam!
- Auxílio Home Office: Liberdade para escolher como utilizar.
- Day off no aniversário: para nossas Ervilhas celebrarem a vida!
- Empréstimo Consignado: Se precisar daquela ajudinha!
- Home Office: Flexibilidade e confiança para nossas Ervilhas trabalharem de onde estiverem.
- Horário Flexível: Aqui trabalho Remoto pode!
- Personal Trainner: Todos tem direito a ginástica laboral e academia online todos os dias
- Plano de Saúde Bradesco: É importante se cuidar, cuidar dos seus e estar bem.
- Plano Odontológico Sulamérica: Para deixar seu sorriso mais bonito!
- PLR: Para trabalhar com propósito e realizar sonhos.
- Seguro de Vida: Cuidado e prevenção está em nosso DNA.
- Universidade Reclame AQUI: Disseminação do nosso propósito de Mudar o Mundo!
- Vale Alimentação: Um beneficio que contribui para toda a sua casa!
- Vale Refeição: Para comprar comida onde e como preferir.

## Como se candidatar

Para se candidatar é simples, basta inserir suas informações [nesse link](https://jobs.jobconvo.com/pt-br/careers/job/MTcyNDA5MQ-analista-de-software-fron-end-pl/23f69adf-453c-4f81-af71-0a690e43815a/)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

#### Categoria
- Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
