### ISSUE TITLE
[Remoto] Frontend Developer na FINBOOSTER

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6755]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-developer-142250020?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>FINBOOSTER</strong> busca pessoa <strong>Frontend Develope</strong>r para compor seu time!</p>
<p>Somos uma holding que atua no mercado financeiro-tecnológico oferecendo consultoria estratégica, mentoria de crescimento e aporte para acelerar o crescimento de negócios do segmento de meios de pagamentos, aliando tecnologia, expertise humana e gestão inovadora.</p>
<p>Estamos estruturando e criando um novo time, se você se identifica com desafios, essa oportunidade é para você</p>
<p><strong>Responsabilidades:</strong></p>
<ul>
<li>Desenvolvimento e manutenção de aplicações Web;</li>
<li>Montar páginas responsivas;</li>
<li>Organização de código.</li>
</ul>

## FINBOOSTER: 
 <p>Somos uma holding que atua no mercado financeiro-tecnológico oferecendo consultoria estratégica, mentoria de crescimento e aporte para acelerar o crescimento de negócios do segmento de meios de pagamentos, aliando tecnologia, expertise humana e gestão inovadora.</p>
</p>

 ## Habilidades: 
 - React.js 
- React Hooks 
- HTML 
- CSS 
- Javascript 
- Typescript 
- GIT 
- Web API
## Local: 
 100% Remoto
## Requisitos: 
 - Saber consumir APIs REST 
- Organização de código 
- Montar páginas responsivas
## Diferenciais: 
 - TypeScript 
- Inglês técnico

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Developer na FINBOOSTER](https://coodesh.com/vagas/frontend-developer-142250020?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
