### ISSUE TITLE
[Remoto] Angular Front-end Developer @Meta 💙

### ISSUE THREAD

**Issue by techrhrj** [frontendbr/vagas#6756]
Oi, Devs!! Estamos em busca de Desenvolvedores para atuar aqui na META https://www.meta.com.br/

Quem Somos Nós:
Somos uma empresa com foco em soluções tecnológicas ágeis que simplificam e produzem valor real no dia a dia das organizações. Nosso propósito é promover o Crescimento Humano com Tecnologia!

100% Remoto

## Local

Remoto 

## Requisitos

**Obrigatórios:**
- Conhecimento avançado em Desenvolvimento com HTML5 e CSS3;
- Conhecimento avançado em Angular 5-9;
- Habilidade com versionamento GIT e utilização GIT-FLOW;

**Desejáveis:**
- Conhecimento em desenvolvimento PWA;

## Benefícios

- Plano de Saúde e Odontológico
- Seguro de vida

## Contratação

PJ a combinar ( necessário já ter empresa aberta )

## Como se candidatar

Por favor envie um email para thais.franco@meta.com.br com seu CV anexado 

#### Alocação
- Alocado
- Remoto

#### Regime

- PJ

#### Nível

- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
