### ISSUE TITLE
[Remoto] React Native Developer na YOURS BANK

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6757]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-react-native-130350249?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>YOURS BANK</strong> busca pessoa<strong> Frontend React Native</strong> para compor seu time!</p>
<p>A YOURS é uma fintech que tem por propósito Ensinar Educação Financeira para crianças e adolescentes, e fazemos isso sendo a sua primeira instituição financeira. O projeto iniciou em 2020 e hoje caminha em expansão para todo o Brasil.</p>
<p><strong>Atividades:</strong></p>
<p>Trabalhar com a equipe no desenvolvimento das novas funcionalidades da aplicação mobile e na manutenção e melhorias do sistema. Aqui você utilizara o que há de mais moderno no React Native e em padrão de projetos.&nbsp;</p>
<p></p>

## YOURS BANK: 
 <p>Experiência única para pais e filhos!</p>
<p>Somos uma plataforma que introduz nas famílias o processo de independência financeira. Com o Yours Bank, você tem a liberdade na palma da mão. Definitivamente os jovens precisam ter mais autonomia! Com o Yours eles passam a ter liberdade para gerenciar seu próprio dinheiro.</p><a href='https://coodesh.com/empresas/yours-bank'>Veja mais no site</a>

 ## Habilidades: 
 - React Native 
- Redux Saga 
- Automação de Testes
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência com React, React native, Redux e Clean Code 
- Ser habituado com metodologias ágeis 
- Ser fascinado por user experience
## Diferenciais: 
 - Conhecimento de NodeJs 
- Conhecimentos em Swift / Java 
- Inglês avançado

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [React Native Developer na YOURS BANK](https://coodesh.com/vagas/desenvolvedor-react-native-130350249?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Mobile

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
