### ISSUE TITLE
[Remoto] Fullstack .NET/Angular Developer na NETResíduos

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6758]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/fullstack-netangular-developer-130741131?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>NETResíduos </strong>está buscando <strong><ins>Fullstack .Net/Angular Developer</ins></strong> para compor seu time de desenvolvimento!</p>
<p>Somos a NETResíduos, uma plataforma prática, intuitiva e acessível para gerir e armazenar dados e documentos de ponta a ponta, desde a geração até a destinação dos resíduos.</p>

## NETResíduos: 
 <p>Há 6 anos, observamos que eram raras as empresas que realizavam um registro dos dados de geração de resíduos, e ainda mais raras as que copiavam essas informações afim de obter algum resultado.</p>
<p>Logo, sentimos a necessidade de transformar esta dor em uma solução escalável. E fizemos isso aplicando a tecnologia como um facilitador do Gerenciamento de Resíduos.</p><a href='https://coodesh.com/empresas/netresiduos'>Veja mais no site</a>

 ## Habilidades: 
 - .NET 
- Angular 8 
- REST APIs 
- HTML 5 
- CSS 3 
- GIT
## Local: 
 100% Remoto
## Requisitos: 
 - Sólido conhecimento em C# .NET WEB API 
- Integração de APIs REST 
- Conhecimento em HTML, CSS, Angular 8 
- Banco de dados MYSQL 
- Versionamento de código Git 
- Noções de Cloud Microsoft Azure

## Benefícios: 
 - !00% Remota 
- Bonus semestral de permanência na empresa 
- Gympass 
- Day Off no aniversário
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack .NET/Angular Developer na NETResíduos](https://coodesh.com/vagas/fullstack-netangular-developer-130741131?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by marcosferrarijr** [comment]
Está aberta 

Enviado do meu iPhone

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
