### ISSUE TITLE
[REMOTO] Front-end Jr. Developer na ISAT

### ISSUE THREAD

**Issue by pauloisat** [frontendbr/vagas#6759]
> Vaga Remota durante a pandemia

## Nossa empresa

Somos uma empresa de Tecnologia voltada para a área Educação a Distância e Comunicação Digital!

Para não ficar muito longo aqui, vou deixar o endereço do nosso site: www.isat.com.br, para que você consiga ver um pouco mais a fundo nossos serviços e história nesse mercado.

## Descrição da vaga

Entendemos que ter plataformas tecnológicas e processos de negócio otimizados são fundamentais para vencer na era digital. Para melhorar continuamente a experiência de seus clientes, contamos com um time multidisciplinar que faz da sua busca por resultados uma obstinação diária.

Somos próximos dos clientes, flexíveis para entender as demandas, velozes para entregá-las e apaixonados por tecnologia e eficiência.

Estamos buscando os melhores profissionais para fazer parte do nosso time de Desenvolvimento, se você tem perfil de entrega de projetos com foco em eficiência em gestão e processos, analise abaixo as demais responsabilidades e requisitos para a vaga.

Procuramos por pessoas que:

• Sejam apaixonados por tecnologia e eficiência;
• Flexíveis para entender as demandas;
• Velozes para entregar os serviços/resultados;
• Próximas dos clientes;
• Busquem constantemente a inovação e excelência técnica;
• Valorizem o trabalho em equipe e a troca de experiências.
• Que sejam proativas e comprometidas.

## Local

Remoto

## Requisitos

**Obrigatórios:**
• HTML, CSS
• Javascript, Ajax
• Pré-processadores de CSS (SASS ou Less)
• Conhecimento em web design responsivo

**Desejáveis:**
• Noções de design de interação e usabilidade

**Diferenciais:**
•  Vue.js, Git e .NET, MVC

## Benefícios
• Assistência médica
• Assistência odontológica
• Auxílio Home Office
• Vale Refeição
• Vale Transporte
• Seguro de vida

**Diferenciais:**
• Ambiente descontraído, grandes desafios, muita autonomia para realizar as tarefas, oportunidade de crescimento, feedbacks e 1:1;
• Pessoas curiosas, objetivas, inteligentes, que sonham grande e são abertas ao novo;
• Remuneração competitiva ao mercado;

## Contratação

A combinar

## Como se candidatar

Por favor envie um email para paulo.carvalho@isat.com.br com seu CV anexado e link de seu portóflio e/ou github - enviar no assunto: [2022] Vaga Front End Jr. Aceitamos currículos até dia 15/04/21.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo. E-mail para contato em caso de não haver resposta: paulo.carvalho@isat.com.br

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Júnior

**Comment by Fabio-sudo-apt** [comment]
Ainda está aberto?

**Comment by pauloisat** [comment]
> Ainda está aberto?

Sim, vamos receber currículos até amanhã.

Até!

**Comment by josuelustosadev** [comment]
@pauloisat boa noite, apesar de constar no tópico "Como se candidatar" que vocês estão aceitando os currículos até dia 15/04/**21**, enviei o meu currículo após ler seu comentário acima... suponho que tenha sido um erro de digitação.

Por fim, fiquei bastante entusiasmado com a vaga e gostaria muito de poder fazer parte da equipe.

Atenciosamente.
