### ISSUE TITLE
[Belo Horizonte] Front-End Developer no ClippingCACD

### ISSUE THREAD

**Issue by bielcapanema** [frontendbr/vagas#676]
# Descrição da vaga

Buscamos front-end developers com experiência de no mínimo 1 ano. Trabalho ou estágio presencial em horário comercial.

# Local

Escritório em Belo Horizonte - BH-TEC (Parque Tecnológico de Belo Horizonte), próximo a UFMG

# Ambiente

Time multidisciplinar focado em produto.
Equipe dinâmica e motivada.
Voz ativa e participação nas decisões de negócio.

# Requisitos

## Obrigatório

Linguagens: NodeJS, Javascript;
SASS, HTML5, CSS3, React, redux
Versionamento: Git (GitFlow, PR, etc)

## Desejável

AngularJS, Redux-sagas, Firebase, Functions, hapi
Metodologias ágeis.
Inglês Intermediário (Leitura, Escrita e Conversação);

## Diferencial

Sólidos conhecimentos em TDD e API's backend.
Experiência com implementação de testes A/B.

## Contratação

CLT Full - 40h Semanais, VR,  VT.
Estágio - 30h Semanais, VR,  VT.

# Como se candidatar

Por favor envie um email para lucas@clippingcacd.com.br - enviar no assunto: Vaga Desenvolvedor Front-End - Indicação Gabriel Capanema.

**Comment by bielcapanema** [comment]
Vaga em aberto ainda!

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
