### ISSUE TITLE
[Remoto] Mid/Senior Front-end Engineer na Wedy

### ISSUE THREAD

**Issue by danieltamiosso** [frontendbr/vagas#6760]
## Nossa empresa

A [Wedy](https://wedy.com/) é uma plataforma digital que facilita a jornada do casamento. Nosso dia-a-dia é tornar a experiência dos nossos usuários mais agradável e sem complicações — o casamento já é um momento extremamente delicado para qualquer casal. Com isso em mente, reorganizamos e repensamos alguns conceitos no nosso produto e agora precisamos implementá-los. É nesse ponto que você entra, sendo uma peça fundamental na criação da próxima geração da nossa plataforma. Esta vaga exige um nível maior de criticidade e conhecimentos específicos, uma vez que todas as decisões tomadas agora influenciarão os próximos anos de nossa empresa.
## Descrição da vaga

> Você vai atuar em uma stack moderna — Next.js, Tailwind, Prisma, PlanetScale, GraphQL e Vercel — em uma rotina de trabalho tranquila, com autonomia e protagonismo. Não há dailys, scrum masters, métodos ágeis, Jira, deadlines falsos, code reviews maçantes, etc. Buscamos trabalhar de forma assíncrona através do Discord e do Notion.

**Responsabilidades**
- Participar ativamente no desenvolvimento e manutenção das diversas funcionalidades do produto, sempre tomando os cuidados necessários para não gerar dívidas técnicas;
- Sugerir e realizar melhorias no código;
- Sugerir e realizar melhorias no produto;
- Ser referência como mentor para pessoas engenheiras iniciantes;
- Manter-se em dia com as últimas novidades de front-end.

## Local
Remoto

## Requisitos

- Conhecimento sólido em JavaScript;
- Experiência com React em produção;
- Experiência com consumo de APIs em produção;
- Experiência com Figma ou similar;
- Saber se comunicar de forma eficiente e clara, sendo ela escrita ou oral;
- Saber gerenciar seu tempo, organizando e priorizando seu trabalho;
- Estar em dia com as últimas novidades de front-end.
- 
## Benefícios
- 100% remoto: trânsito nunca mais;
- 6h por dia: mais tempo pra fazer o que você gosta;
- Trabalho assíncrono: pode silenciar as notificações, não tem problema;
- Horários flexíveis: a vida é corrida e a Wedy não vai ficar no caminho;
- Day-off no aniversário: um presentinho nosso;
- Vale-alimentação: nada mais justo.

## Contratação
Salário entre R$ 8.000 e R$ 10.000 (PJ)

## Como se candidatar

Aplicar via LinkedIn ou enviar e-mail para [daniel@wedy.com](mailto:daniel@wedy.com) com Linkedin/Github/etc.
## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 semana após cada processo.
E-mail para contato em caso de não haver resposta: engineering@wedy.com

#### Alocação
- Remoto

#### Regime

- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
