### ISSUE TITLE
[Curitiba, Paraná, Brazil] Fullstack Java Developer na Topdata

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6766]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-java-full-stack-182529629?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>Topdata</strong> busca pessoa<strong> Fullstack Developer</strong> para compor seu time!</p>
<p>Somos uma empresa brasileira, fabricante de relógios de ponto eletrônico e catracas para controle de acesso, fundada há mais de 26 anos. Com a proposta de ser uma empresa de tecnologia de ponta, utilizamos os mais modernos conceitos de administração de forma a garantir uma equipe de funcionários motivados, alta qualidade dos produtos e custos de produção otimizados.</p>
<p><strong><ins>Atividades a serem desenvolvidas:</ins></strong></p>
<ul>
<li>Programação Web, Análise (Front-End e Back-End);</li>
<li>Suporte de Sistema (atendimento a dúvidas);</li>
<li>Correções de Bugs;</li>
<li>Criação de Scripts SQL;</li>
<li>Melhorias de SistemaFront-End – AngularJs 1.xx, JavaScript, Bootstrap 4, HTML 5/CSS 3;</li>
<li>Back-End - Spring Boot/Spring Data/Spring Security, API RestFull Jersey, ORM/Hibernate, Java EE;</li>
<li>Banco de dados: SQL Server, Instruções SQL.</li>
</ul>
<p></p>

## Topdata: 
 <p>Somos uma empresa brasileira, fabricante de relógios de ponto eletrônico e catracas para controle de acesso, fundada há mais de 26 anos. Com a proposta de ser uma empresa de tecnologia de ponta, utilizamos os mais modernos conceitos de administração de forma a garantir uma equipe de funcionários motivados, alta qualidade dos produtos e custos de produção otimizados.</p>

<p>Fabricamos diversas linhas de produtos: relógios de ponto, catracas para controle de acesso, controle de acesso e bastões de ronda, produtos reconhecidos no Brasil e no mundo por sua qualidade, alta tecnologia e excelente relação custo benefício, atendendo as mais variadas finalidades em diversos empreendimentos de sucesso.</p><a href='https://coodesh.com/empresas/topdata-sistemas-de-automacao-ltda'>Veja mais no site</a>

 ## Habilidades: 
 - HTML 
- Java 
- Microsoft SQL Server
## Local: 
 Curitiba, Paraná, Brazil
## Requisitos: 
 - Conhecimento em orientação a objetos 
- Experiência em desenvolvimento WEB

## Benefícios: 
 - VR + VT    
-  PLR  
- Plano de Saúde (Unimed) 
- Plano Odontológico (Dental Uni) 
- Estacionamento 
- Auxílio Farmácia 
-  Club Gazeta do Povo
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack Java Developer na Topdata](https://coodesh.com/vagas/desenvolvedor-java-full-stack-182529629?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Regime
CLT
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
