### ISSUE TITLE
[Remoto] Frontend Developer na ESL Sistemas

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6767]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-front-end-pleno-iii-202856367?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>ESL Sitemas</strong> busca pessoa <strong>Frontend Developer</strong> para compor seu time!</p>
<p>A ESL nasceu para ser uma ponte entre a tecnologia e o transporte. Com uma visão atenta para as necessidades das transportadoras, a ESL está focada no mercado logístico.</p>
<p><strong>Principais atividades:</strong></p>
<ul>
<li>Desenvolvimento de componentes de interface</li>
<li>Manutenção de códigos já existente</li>
<li>Revisar features a serem implementadas</li>
<li>Atualização de componentes já existentes</li>
<li>Sugestões de melhoria no design e usabilidade da aplicação<br></li>
</ul>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>

## ESL Sistemas: 
 <p>Quem somos?</p>

<p>Uma ponte entre a tecnologia e o transporte.</p><a href='https://coodesh.com/empresas/esl-sistemas'>Veja mais no site</a>

 ## Habilidades: 
 - HTML5 / CSS3 
- Javascript 
- Bootstrap 
- Vue.js
## Local: 
 100% Remoto
## Requisitos: 
 - Conhecimento em HTML, CSS; 
- Conhecimento JavaScript 
- Boas práticas de codigo 
- Conhecimento em Vue 
- Bootstrap 
- Layout responsivo 
- UX/UI 
- Git
## Diferenciais: 
 - Rails
## Benefícios: 
 - VR ou VA (para CLT) 
- PLR  
- Parcerias com Universidades 
- Convênio Médico (para CLT)  
- Seguro de vida  
- 15 dias de férias remuneradas (para PJ)
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Developer na ESL Sistemas](https://coodesh.com/vagas/desenvolvedor-front-end-pleno-iii-202856367?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
