### ISSUE TITLE
[Remoto / Híbrido] Front-end Developer na ZBRA Solutions

### ISSUE THREAD

**Issue by spliner** [frontendbr/vagas#6769]
## Nossa empresa - ZBRA Solutions

Já imaginou uma empresa onde você trabalha com tecnologias modernas em um ambiente tranquilo e colaborativo?

Entregamos soluções de software usando o estado da arte de tecnologia, buscando encantar e empoderar tanto desenvolvedores como clientes. Queremos garantir que as nossas equipes tenham ambiente, ferramentas e prazos adequados para entregar resultados de alta qualidade.

Na ZBRA, você trabalhará com pessoas apaixonadas por desenvolvimento e terá autonomia e suporte para crescer e se desenvolver em sua carreira pois incentivamos melhoria contínua, ouvir e ser ouvido e muita colaboração. Somos uma equipe comprometida mas com grande foco no equilíbrio pessoal-profissional!

Não são muitas as empresas que têm valores que se refletem na cultura. Os nossos estão presentes e são constantes no dia a dia!

Se você é uma pessoa que também tem esses valores, venha trabalhar com a gente! \o/

## Descrição da vaga

Como membro da nossa equipe, você:
- Faz parte de uma equipe ágil dentro de um ambiente colaborativo, onde se valoriza a troca de idéias e evolução como grupo;
- Tem a possibilidade de trabalhar e aprender novas tecnologias mesmo que você não tenha experiência com elas;
- Usa as melhores práticas e ferramentas do mercado;
- Pode experimentar com novos processos, técnicas, frameworks e linguagens;
- Participa de workshops internos para discutir experiências passadas e ideias para projetos futuros;
- Desenvolve projetos desafiadores com pessoas criativas;
- Pode participar dos nossos eventos e encontros: Z-Talks, Game Night, Z-Burger, Z-Movies, entre outros.

## Requisitos - obrigatórios e desejáveis

Como Front-End Developer aqui na ZBRA, você não precisa necessariamente ter proficiência em todas as atividades e/ou tecnologias listadas a seguir pois, como empresa, damos suporte para que você aprenda e cresça.

De qualquer forma, aqui você vai:
- Desenvolver front-end com React, Angular, TypeScript, PWA, Less, Saas;
- Participar em todo o ciclo de desenvolvimento de projetos, desde a conceptualização, UI/UX, análise dos requisitos, concepção da arquitetura, implementação, testes e release;
- Trabalhar com arquiteturas evolutivas e cloud-first;
- Aplicar no dia a dia conceitos de SOLID, DRY, YAGNI, DDD, OO, Design Patterns entre outros;
- Contribuir com boas práticas de DevOps: CI/CD, automated tests, build e release pipelines, configuration management.

## Local
Remoto ou híbrido, você escolhe! Temos escritórios em São Paulo e Recife :)

## Benefícios
- Plano de saúde sem co-participação para você e sua família;
- Férias remuneradas;
- Horários flexíveis;
- Auxílio academia;
- Bolsa de estudo para idiomas e tecnologias;
- Ajuda com certificações;
- Kindle para os seus estudos;
- Auxílio para compra de livros;
- Atendimento psicológico.

## Contratação
PJ a combinar

## Como se candidatar
Envie um e-mail pra gente em vagas@zbra.com.br com seu currículo em anexo e assunto `Vaga Front ZBRA` ou se candidate por meio da nossa página de carreiras: https://jobs.quickin.io/zbrasolutions/jobs.

## Tempo médio de feedback
De 1 a 3 dias!

## Nível
- Pleno
- Sênior

## Labels
- PJ
- Remoto
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
