### ISSUE TITLE
[São Paulo] Desenvolvedor Front-End Junior no Cuponomia

### ISSUE THREAD

**Issue by rafaelpradella** [frontendbr/vagas#677]
## Descrição da vaga

O [Cuponomia](https://www.cuponomia.com.br) está procurando um Desenvolvedor Front-End Junior para ajudar a compor a nossa equipe de Design/Desenvolvimento Web. Trabalho local c/ Contrato CLT e horário flexível. 

Interessados mandar currículo e portfólio/link do GitHub para [`rafael@cuponomia.com.br`](mailto:rafael@cuponomia.com.br)

## Local

Escritório na Chácara Santo Antônio, São Paulo/SP. Perto da Est. Granja Julieta da CPTM.

## Benefícios

- Plano de saúde;
- Seguro de vida;
- VR de R$ 22/dia;
- Vale-Transporte;

## Requisitos

**Obrigatórios:**
- LESS/SASS, HTML5, CSS;
- Estar confortável em usar ferramentas de versionamento (nós utilizamos o GitHub);
- Utilizamos jQuery, mas é importante saber o Javascript puro;
- Design Responsivo;

**Diferenciais:**
- Vue e/ou React;
- Javascript ES6;
- Customização de temas de Wordpress;
- Noções de C#;

## Nossa empresa

O Cuponomia é um site totalmente gratuito que oferece desconto através de cupons e ofertas das principais lojas online nacionais e internacionais. São mais de 20.000 cupons em 2.000 lojas disponíveis, atualizados e testados diariamente.

Nós negociamos com os melhores e-commerces e vasculhamos toda a internet para encontrar e oferecer cupons exclusivos e descontos especiais.

Trabalhamos duro para garantir que todos os cupons da internet brasileira estarão disponíveis no Cuponomia.

**Comment by kvnol** [comment]
Eu iria na vaga, hein, o problema para mim é a distância mesmo. De Santo André para a Chácara Sto. Antônio é uma caminhada.

**Comment by danilosilvadev** [comment]
@rafaelpradella fazem entrevista via skype?

**Comment by rafaelpradella** [comment]
@danilosilvadev A vaga é presencial, mas podemos fazer a entrevista via Skype sem problemas.

**Comment by danilosilvadev** [comment]
@rafaelpradella cv enviado. Obg amigo!

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by rafaelpradella** [comment]
@LFeh Ainda está aberto. :)
