### ISSUE TITLE
[Remoto] Frontend Angular Developer na SpotSales

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6771]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-angular-developer-194615030?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>SpotSales</strong> está buscando <strong><ins>Frontend Angular Developer</ins></strong>!</p>
<p>Somos uma empresa mineira, que atua em todo o território nacional.&nbsp;</p>
<p>Em nossa essência trazemos o investimento em novas tecnologias e inovação, tudo para oferecer maior praticidade, controle e as melhores soluções para nossos clientes.</p>

## SpotSales: 
 <p>Somos uma empresa mineira, que atua em todo o território nacional.&nbsp;</p>
<p>Em nossa essência trazemos o investimento em novas tecnologias e inovação, tudo para oferecer maior praticidade, controle e as melhores soluções para nossos clientes.</p><a href='https://coodesh.com/empresas/spotsales'>Veja mais no site</a>

 ## Habilidades: 
 - Angular 
- API 
- Javascript 
- HTML5 e CSS3
## Local: 
 100% Remoto
## Requisitos: 
 - Conhecimentos ou experiência como Front-end Developer 
- Habituado em ler endpoints com Swagger (consumo de APIs) 
- Conhecimentos ou experiência em desenvolvimento Front-end usando Angular 
- Escreva código bem projetado, testável e eficiente 
- Habituado em trabalhar com programação orientada a objetos 
- Domínio em Javascript ou Typescript 
- Ter disponibilidade para participar do processo de seleção 100% online 
- Conhecimentos e boas práticas com HTML5 / CSS3

## Benefícios: 
 - 100 % Remoto 
- Horário Flexível
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Angular Developer na SpotSales](https://coodesh.com/vagas/frontend-angular-developer-194615030?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
