### ISSUE TITLE
[100% Remoto]Lead Frontend React Native | PJ - Builders 🤘🚀

### ISSUE THREAD

**Issue by Patriiciabrito** [frontendbr/vagas#6774]
Papo reto: aqui na Builders você irá se deparar com uma cultura voltada ao empreendedorismo. Os projetos, as pessoas e seu dia a dia serão norteados pela vontade de fazer acontecer e desafios. Suas ideias não serão descartadas, você poderá liderar pessoas incríveis e ser agente de transformação, além de vivenciar uma estrutura de frontend idealizada apenas aqui na Builders. 👀 E aí, bora ser Builder?

**Como será sua rotina de Lead Frontend React Native:**

- Buscar maneiras de amadurecer e evoluir o time, coletivamente e individualmente
- Discernir métricas técnicas de sucesso e qualidade, e procurar maneiras de melhorá-las
- Colaborar na evolução das boas práticas técnicas, como desenvolvimento de bibliotecas reaproveitáveis de código;
- Elaborar e registrar feedbacks construtivos para o time;
- Manter constantes 1:1s com os membros da equipe;
- Planejar e executar estratégias de curto e longo prazo que beneficiem a maturidade técnica do time e das entregas de produto;
- Se envolver em resolver bugs e entregas de funcionalidades em projetos, quando e se necessário para garantir a entrega;

**Tecnologias que se você dominar, vão gerar valor nos projetos 💻:**

- Fluência em TypeScript;
- React Native (Redux/Mobx);
- APIs REST;
- Trabalhar com diferentes dimensões de dispositivo (tablet, celular, etc)
- Conhecimento geral do ambiente móvel;
- Versionamento de código com Git e Github;

**Como Builder, você terá acesso a:**

- Oportunidades reais de empreender e impactar;
- Fazer parte de uma comunidade de empreendedores; de ponta;
- Inovação e criação liberados;
- Participar de um processo único de geração de valor;
- Contribuir na criação de métodos disruptivos;
- Colocar suas ideias no mercado, na prática! :)
- Possibilidade de Profit share em novos Negócios;
- Prestador de Serviços (PJ).

**Acesse a nossa página de carreira para se candidatar:**
https://jobs.kenoby.com/sejabuilder

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
