### ISSUE TITLE
[Remoto] Full-stack Java e Angular Developer (Sênior)  na Translucent Computing

### ISSUE THREAD

**Issue by natalianobres** [frontendbr/vagas#6777]
## Translucent Computing Inc

Translucent Computing ([www.translucentcomputing.com](url)) é uma empresa canadense que se baseia em criar relações que se tornam verdadeiras parcerias.

Translucent Computing é sua parceira na transformação digital, oferecendo serviços completos orientados a dados. Nossos principais serviços são aplicações em nuvem, microsserviços, DevOps e Machine Learning.

 Isso começa com uma boa conversa, identificando os valores que podemos fornecer para as pessoas, clientes e parceiros.

Nos empenhamos para criar soluções de alta qualidade enquanto compreendemos os problemas reais.

Trabalhando e treinando os melhores talentos nas tecnologias mais estáveis e avançadas disponíveis - Verdadeira Inovação!
 
Nossa equipe é composta por um grupo dedicado, trabalhador, orientado a resultados, independente e divertido. Trabalhar remotamente em todo o mundo nos permite ter diversidade tanto na cultura quanto no talento. Atualmente estamos crescendo e estamos ansiosos para construir o futuro com você!

## Descrição da vaga

- Trabalho remoto - Trabalhe em Casa com uma empresa Canadense Internacional.
- Capacidade de trabalhar com as tecnologias mais avançadas
- Treinamento ministrado internamente e externamente com o suporte da empresa
- Tempo dedicado para o treinamento dos funcionários durante o horário de trabalho
- Temos uma mentalidade de sempre melhorar e aprender
- Empresa privada
- Baixa rotatividade
- Trabalhando com uma equipe internacional
- Equipe culturalmente diversificada
- Ambiente flexível e orientado a resultados
- Pessoas boas, divertidas e realistas
- Benefícios oferecidos à equipe em todo o mundo
- Roteiro de carreira para crescer a longo prazo
- Promovemos internamente primeiro!
- Equipe de liderança atenciosa e compreensiva

**Divisão das funções em % de tempo:**

40% Java backend - microsserviços - API’s - design de banco de dados - Integração
25% Angular frontend
20% DevOps
15% Reuniões & Scrum

 **Educação / Certificações:**  Bacharel em  Ciência da Computação  - ou experiência equivalente
**Local:**   Trabalho remoto com uma Empresa Canadense Internacional	
**Faixa salarial:**  Dependendo da experiência
 **Data de ocupação do cargo:**  O mais rápido possível 
**Horas:**  40 hours semanais -das  9 horas da manhã até às  5 horas da tarde (EST – Fuso horário de Toronto ) horas principais – Nós somos flexíveis aqui com algum motivo 

## Requisitos

**Obrigatórios:**

-  Proficiência Sênior com Java – 4+ ou mais anos de experiência
-  Hibernate
-  Proficiência em Spring boot framework
-  Design de APIs (RESTful APIs)
-  Nível intermediário ou avançado em design de banco de dados relacionais ou não relacionais (MySQL, PostGres)
-  Arquitetura de software & design patterns
-  Habilidade intermediária ou superior com arquitetura de microsserviços
-  2+ anos de experiência sólida com Angular – Angular 2 ou acima
-  Conhecimento sólido em padrões de código JavaScript
-  Proficiência na escrita de HTML semântico e bem formatado
-  Proficiência na escrita de CSS/SCSS modular
-  Proficiência com a linguagem JavaScript
-  Proficiência com Sass, NPM, AngularJS/Angular ou frameworks similares
-  Proficiência com a linguagem Typescript
-  Proficiência com controle de versão de projetos (GIT)
-  Boa compreensão e experiência com testes unitários (Jest, Jasmine/Karma)
-  Boa compreensão de design e UX
-  Boa compreensão de compatibilidade entre plataformas

**Se você não tem as experiências exatas listadas acima, mas ainda assim se sente qualificado baseado em experiências com outras tecnologias, nós ainda queremos ouvir sobre você**

**Desejáveis:**

- Pensamento crítico
-  Bom gerenciamento de tempo e prioridades
-  **Boa comunicação em inglês - 7 em 10 (7/10) ou melhor nível dessa habilidade (muito necessário)**
- Orientado a processos e procedimentos
- Capacidade de pular para diferentes tarefas conforme necessário
- Proatividade
-  Capacidade de trabalhar de forma independente ou como parte de uma equipe
- Flexibilidade de tarefa - Capacidade de pular para diferentes tarefas conforme necessário, por exemplo: quando um problema de suporte aparece.
-  Boa ética de trabalho
- Conhecimento das expectativas do cliente
-  Seguir os requisitos do cliente
- Constantemente aprendendo e crescendo com a tecnologia

**Diferenciais:**

- Experiência com ferramentas de testes automatizados (Cypress, TestCafe)
- Boa compreensão de RxJS
- Boa compreensão de Ngrx
- Boa compreensão de React
- Boa compreensão de arquiteturas de microsserviços
- Aplicações móveis para dispositivos celulares e tablets
- Experiência com gestão e liderança
- Grande diferencial ter experiência com Angular 9 ou acima

- Experiência com DevOps :

1. Build and Deployment - utilizando ferramentas de CI / CD 
2. Gerenciamento de Release 

- Kubernetes com as seguintes competências:

1. Orquestração de containers de aplicações Web
2. Configuração dos gráficos do Helm

- Docker

**Ambiente**:  Docker, Linux, Windows, Mac
**Metodologia:**  Agile Scrum
**Servidores / Banco de dados:** MySQL ou (PostgreSQL)- ElasticSearch ou (mongo DB ou Solr)  preferência por bancos de dados hospedados na nuvem
**Linguagens:** Java, Angular, React
**Serviços Web:**   Design de  API (APIs RESTful)
**Serviços em nuvem:**  GCP ou (AWS), Kubernetes
**Ferramentas:** Spring (boot, data rest, HATEOAS, MVC) - hibernate (JPA), Testes - (JUnit, Gatling, Mockito) - RabbitMQ/Kafka - Maven, GIT
 

## Benefícios

-  Participação nos lucros e resultados  
- 1 semana de folga no fim de ano
- Programa de reembolso trimestral de trabalho remoto;
- Brasileiros ganham 10 dias remunerados de folga nos feriados canadenses
- Mais 10 dias de férias
- 5 dias de folgas pessoais
- Auxílios de saúde, transporte e alimentício

## Contratação

PJ e Salário (depende da experiência)

## Como se candidatar

Por favor, se cadastre aqui nesse formulário: [Formulário para Fullstack ](https://forms.gle/VBfCFiaHc2C7UeSy7) 
Certifique-se de informar os seus horários disponíveis em blocos, por exemplo: SEG (14h - 17h) | TER (19h - 21h) | QUA (18h - 20h)** 

#### Alocação

- Remoto

**Regime**

- PJ

 **Nível**

- Sênior

**Categoria**

- Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by natalianobres** [comment]
continua aberta

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by natalianobres** [comment]
Olá, pode fechar a vaga. Obrigada
