### ISSUE TITLE
[Remoto] Fullstack Web Developer  na AltoQi

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6778]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-web-fullstack-205956455?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>A AltoQI</strong> busca pessoa <strong>Fullstack Developer</strong> para compor seu time!</p>
<p>A AltoQi é uma holding com soluções de software altamente especializadas para a construção civil. Somos movidos por grandes desafios e estamos em busca de pessoas que estejam dispostas a trabalhar com propósito, tecnologia e estar em constante aprendizagem.</p>
<p>Estamos em crescimento e buscando novos talentos. Procuramos alguém que esteja disposto a embarcar nessa trajetória conosco e gerar impactos positivos na vida das pessoas. E por isso, procuramos pessoas para nosso time de desenvolvimento, para nos ajudarem à crescer, atuando nos projetos da área.</p>
<p><strong>Quais são as funções?</strong></p>
<ul>
<li>Definir e documentar a estrutura e a forma dos sistemas a serem desenvolvidos, para melhorar a escalabilidade e a manutenibilidade dos mesmos;</li>
<li>Definir requisitos técnicos, para a contratação de equipes de desenvolvimento terceirizadas e revisar as soluções apresentadas por essas equipes;</li>
<li>Coordenar a aplicação de testes automatizados;</li>
<li>Será responsável por novos projetos web (site e e-commerce), validar esses projetos e comunicar se com o terceirizados;</li>
</ul>
<p></p>

## AltoQi: 
 <p>A AltoQi, grupo empresarial brasileiro de tecnologia fundado em 1989, é líder nacional em soluções tecnológicas para projetos de edificações. Desenvolve soluções completas e integradas, facilitando o trabalho de mais de 60 mil profissionais de Arquitetura, Engenharia e Construção (AEC).</p>
<p>Com  foco na transformação suas soluções, AltoQi Eberick, Builder, Visus e Cloud, são voltadas para projetistas, engenheiros e arquitetos, simplificam e aprimoram o trabalho de profissionais, escritórios de projetos, construtoras, governos e universidades, facilitando também a gestão de empreendimentos em todas as fases, pré-obra, obra e pós-obra, durante todo o ciclo de vida de uma edificação – projeto, construção e manutenção.</p><a href='https://coodesh.com/empresas/altoqi'>Veja mais no site</a>

 ## Habilidades: 
 - Node.js 
- Python 
- React.js 
- Angular
## Local: 
 100% Remoto
## Requisitos: 
 - Graduação completa em áreas da Computação, Sistemas ou Automação; 
- Gestão de equipes pode ser um diferencial; 
- Experiência com desenvolvimento fullstack em aplicações web complexas; 
- Conhecimento em todas as etapas do desenvolvimento de software; 
- Arquitetura, container (Docker), integração. 
- Jenkins; 
- Fluxos de trabalho GIT.
## Diferenciais: 
 - Conhecimento em C#;  
- Conhecimento em Java;  
- Conhecimento em React Native. 
## Benefícios: 
 - Opção de Vale alimentação e/ou Vale refeição; 
- Convênio com a ACATE (Associação Catarinense de Tecnologia); 
- Convênio com o SESC; 
- Plano de saúde com mensalidade do titular paga pela AltoQi; 
- Parceria com Assistência Odontológica; 
- Auxílio home office; 
- Parcerias com redes de farmácia, restaurantes e faculdades; 
- Oportunidade de trabalhar com profissionais que são referência no mercado; 
- Faça parte de uma equipe que acredita na diversidade e inclusão. Aqui você pode ser você mesmo; 
- Salário compatível com o mercado (negociável).
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack Web Developer  na AltoQi](https://coodesh.com/vagas/desenvolvedor-web-fullstack-205956455?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
