### ISSUE TITLE
[Amsterdã - Holanda] Front-end Developer & Team Lead at Booking.com

### ISSUE THREAD

**Issue by henriquehsv** [frontendbr/vagas#678]
## Job Description
As a Team Lead in the Booking.com Technology Department, you will be supporting and facilitating the work of a multidisciplinary development team.

You are hands-on, you are technical and you understand that behind any technical decision there is a business need to be fulfilled.

You are focused on developing and growing the people in your team, you lead by example and care about the team performance.

### B.responsible
- Facilitate an agile development team (small team of 4 – 6 people)
- Identify and grow talents, provide feedback and look after people’s personal development
- Assess individual and team performance, recognize and promote excellent performance, and address underperformance
- Focus on supporting the business priorities, be pragmatic about technology choices
- Collaborate with the team and Product Owner to prioritize the projects
- Rapidly develop next-generation scalable, flexible, and high-performance client side code
- Solve issues with the site and internal systems, prioritizing based on customer impact
- Contribute to Booking.com’s growth through interviewing, on-boarding, or other recruitment efforts

## Place
Full-time job, Amsterdam - The Netherlands

## Perks - B.offered
We are a performance-based company that offers career advancement and lucrative compensation, including bonuses and stock potential.  We also offer the “Booking Deal” with other competitive perks and benefits.  The Technology department has tech talks and exploration days, allowing you to extend your knowledge and skills outside of your everyday scope of work. We are active in the tech community and often host and attend meetups. Our employees speak at global conferences and arrange hackathons all over the world.

We offer personal and professional development opportunities through both internal and external training programs. Additionally, we offer a conference budget to each tech employee.  

You will be given the freedom to experiment and make your own decisions, impacting millions of travelers worldwide.

***This position is open to worldwide candidates and in the case of relocation, we will assist with a generous relocation package, ensuring a smooth transition to working and living in Amsterdam.  We have successfully relocated 300+ Technology professionals and their families to Amsterdam in the last year!***

## Required Skills - B.skilled

- Experience with managing development teams, with at least one year in a leadership role
- Minimum of 3 years Front End development experience with JavaScript/HTML/CSS
- Excellent communication, collaboration, and influencing skills
- Independent, pragmatic and proactive work attitude
- Experience of working on products that impact a large customer base is an advantage
- Experience with data-driven product development: analytics, A/B testing, etc is an advantage
- Preferably a university degree in Mathematics or Software Engineering

## Hiring

Full-time job, indefinite contract. Offers Visa sponsorship for the Netherlands.

## About Booking.com

We are one of the biggest e-commerce companies in the world. To create the ultimate travel experience, we build and improve great products for both travelers and the accommodation partners.Our Technology Department is more than 100 teams of four to six people each. We operate on a scrum-based agile development methodology, we are data-driven and do extensive A/B testing on both user and partner facing platforms.We deploy code multiple times per day our own 30,000+ servers across our multiple data centers around the world, we have freedom, end-to-end access, and authority to make meaningful and measurable improvements empowering millions of people to experience the world.

## How to apply

Submit your CV through this link: http://grnh.se/sm6tyl1
#
*P.S. Estou a disposição para tirar dúvidas sobre a vaga ou sobre a empresa por e-mail ou Hangouts* ***(henriquehsv@gmail.com)***

**Comment by henriquehsv** [comment]
Essa não é a mesma vaga da issue #674 :). Essa deve ficar aberta até o fim de novembro.

**Comment by DawTaylor** [comment]
Faltou colocar o email @henriquehsv. Ou estou cego demais?

**Comment by henriquehsv** [comment]
@DawTaylor Achei que tinha meu e-mail no perfil do github. Adicionei agora :).
De qualquer forma: henriquehsv@gmail.com

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by henriquehsv** [comment]
@LFeh Está aberta sim, pode aplicar pelo link.

**Comment by danielsidev** [comment]
Aplicado pelo link! Obrigado peal oportunidade @henriquehsv !

**Comment by henriquehsv** [comment]
Sem problemas, Daniel! Atualmente a área de TI está fervilhando de oportunidades, as empresas estão precisando de bons profissionais e estão dispostas a oferecer realocação. 👍

**Comment by henriquehsv** [comment]
Vaga atualmente fechada, aviso se abrir de novo.
