### ISSUE TITLE
[Brasil - Remoto] Front-end Developer (React) na @BeerOrCoffee

### ISSUE THREAD

**Issue by Leticiapsi2021** [frontendbr/vagas#6781]
> 

## BeerOrCoffee
Você já sonhou em trabalhar de forma 100% remota e poder viver toda a liberdade e flexibilidade que esse modelo de trabalho oferece?
Imagina ter +1.000 espaços ao redor do Brasil e poder trabalhar de onde quiser?
Se você ainda não conhece, somos uma plataforma que conecta empresas a espaços de trabalho em todo Brasil proporcionando maior liberdade, eficácia e inteligência na forma de trabalhar.

## Front end Developer Pleno (React)
Local
100% remoto #anywhereoffice

## Requisitos
Experiência profissional com framework web JavaScript moderno (React, Angular, VueJS e etc).
Experiência usando Git em um ambiente profissional/local de trabalho.
Experiência com Pré-processador CSS (LESS/SASS).
Experiência com ferramentas de automatização (GULP, WebPack e afins).
Uma sólida compreensão dos conceitos básicos de web e browser.
Uma sólida compreensão dos conceitos semânticos de HTML, CSS e JavaScript.
Experiência com problemas de desempenho e otimização e uma capacidade demonstrada de diagnosticar e prevenir esses problemas.
Estar atualizado no desenvolvimento de aplicações web, boas práticas e padrões da comunidade de desenvolvimento.
Experiência em trabalhar com processo de desenvolvimento de software ágil.
Realização de revisões de código.
GitFlow.
Experiência com conceito e consumo de API's.
Experiência com migração de projetos com stack JavaScript antiga para frameworks JavaScript moderno.
Conhecimento avançando em Webpack para customização de processos de build e automatização.

Legal saber:
Experiência em uma organização de alto desempenho, de preferência uma startup de tecnologia.
Cloud AWS
Docker
NodeJS

Exemplo: Projeto bazinga em NodeJS, etc.

## Benefícios
✈️ Trabalho Remoto (Be #anywhere);
🎒 Kit Anywhereoffice (Você pode adquirir mochila, mouse, teclado, headset que desejar para o seu conforto no remoto);
🔑 OfficePass (Remoto não precisa ser apenas homeoffice, você terá acesso ilimitado a mais de 1000 coworkings);
🛫 BeerOrCoffee Wings (ajudamos no custo das suas viagens);
☕ Caju (Nosso cartão contempla as categorias: 🥗 alimentação, 🍴 refeição, ⛽mobilidade, 📚 educação e 🏠 ajuda de custo homeoffice);
🏥 Plano de Saúde & Odontológico;
👶🏽 Auxílio Creche;
💖 Head of Love (cuidando do bem-estar dos nômades);
🏖️ Annual BeerOrCoffee Retreat (Nosso encontro presencial dos nômades);
💰 Bonificação trimestral (exceto áreas que tenham comissão);
🥪 Snack Time (quando estiver trabalhando de algum dos nossos espaços, peça um lanche por nossa conta);
📖 12 minutos (app de livros);

## Contratação

CLT ou alguns casos PJ

## Como se candidatar

Por favor enviar cv para leticia.franca@beerorcoffee.com

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após o encerramento do processo seletivo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by odntht** [comment]
@Leticiapsi2021 ficou confuso, é 100% remoto só durante a pandemia ou vocês possuem planos pra 100% remoto mesmo após a pandemia?

**Comment by Leticiapsi2021** [comment]
@odntht a oportunidade é 100% remoto mesmo após a pandemia. Nós não temos escritórios ou sede fixa, temos colaboradores em varias regiões do Brasil e no exterior também. Somos um marketplace de coworkings então nossos colaboradores podem utilizar os coworkings cadastrados dentro da plataforma quando desejar trabalhar fora de casa ou quando estiver viajando.

**Comment by odntht** [comment]
@felipefialho poderia então ajustar os labels?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
