### ISSUE TITLE
[Remoto] Magento Front-end Developer na @ DevellopLabs

### ISSUE THREAD

**Issue by devellop-labs** [frontendbr/vagas#6784]
## Nossa empresa

A Devellop Labs é uma empresa que oferece outsourcing de T.I para empresas de desenvolvimento e agências digitais.

O candidato(a) fará parte de uma equipe multidisciplinar, onde todos colaboram com postura entusiasta, paixão por tecnologia e inovação, e ampla experiência em desenvolvimento web.

## Descrição da vaga

A Devellop Labs está procurando uma pessoa com perfil de nível pleno/sênior, que tenha experiência na área de desenvolvimento Front-End Magento ( M2 ). Essa experiência pode ser através de projetos freelas ou trabalho empresarial.

É importante que você goste de se comunicar e trabalhar em equipe, já que aqui temos um ambiente super colaborativo. Ao mesmo tempo, valorizamos que cada membro do time seja autônomo para gerir suas demandas.

A pessoa contratada será responsável por:

- Analisar, projetar, codificar, depurar, testar, documentar e implantar sites de e-Commerce usando Magento
- Criar e modificar Themas
- Criar e modificar componentes
- Implementando boas praticas de performance.

## Local

Remoto (Full time)

## Requisitos

**Obrigatórios:**
- Excelência técnica e boas práticas de desenvolvimento
- Boas práticas e estratégias de versionamento com Git;
- Conhecimento na Plataforma Adobe Commerce/ Magento 2
- Domínio de PHTML e LESS/SASS codificados manualmente, aderindo aos padrões de codificação W3C
- Desenvolvimento de soluções, extensões, e otimização personalizadas em e-commerce;
- Conhecimento avançado de JavaScript (nativo) e bibliotecas JavaScript, incluindo jQuery

**Desejáveis:**
- Conhecimento em Docker
- Conhecimento em JSON
- Conhecimento em React/Angular/Vue/Next
- Possuir familiaridade com metodologias ágeis. (SCRUM)

**Diferenciais:**
- inglês avançado ou fluente

## Benefícios

- Auxilio Home Office
- Cursos
- Flexibilidade de horários
- Day-off de aniversário

## Contratação

PJ a combinar

## Como se candidatar

Envie um email para [rh@devellop.com.br](mailto:rh@devellop.com.br) com seu CV anexado - enviar no assunto: Vaga Magento Back-end Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by devellop-labs** [comment]
Continua aberta

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
