### ISSUE TITLE
[Remoto] Front-end Developer na Cosmobots 👩‍🚀🚀

### ISSUE THREAD

**Issue by samaramfurlanetto** [frontendbr/vagas#6785]
## Nossa empresa

Aqui na Cosmobots, tudo começou com o Big Bang.. ☄️💥

E hoje somos uma Startup que acredita num mundo cada vez mais tecnológico e com cada vez mais automatização no atendimento aos clientes!

🪐Somos pioneiros no desenvolvimento de Inteligência Artificial para chatbot

🌍Impactamos mais de 80 clientes pelo Brasil

🚀Referência na qualidade de atendimento e tecnologia própria

Não sabemos dizer onde estaremos daqui a 5 anos-luz, mas sabemos que novas galáxias nos esperam. Que tal fazer parte dessa história? 👨‍🚀💜

## Descrição da vaga

**Como Cosmonauta, você terá o desafio de:**

- Desenvolver novas features do front da plataforma;
- Desenvolver melhorias nas features existentes;
- Desenvolver provas de conceito para validar ideias de novos produtos;
- Atuar na resolução de problemas e gestão de incidentes.

## Local

100% remoto

## Requisitos

**Obrigatórios:**

- Experiência com desenvolvimento: React JS, HTML, CSS;
- Experiência com integrações: REST API, SOAP. E com padrões de autenticação;
- Experiência gerenciando desenvolvimentos no Git;
- Experiência em projetos que possuem contato direto com o cliente;
- Conhecimento em banco de dados não relacional;
- Conhecimento em programação orientada a objeto.

**Diferenciais:**

- Conhecimento sobre infra AWS: EC2, ECS, Lambda, RDS, DynamoDB, Cognito;
- Experiência com front React: Redux, AWS Request, Fomik, Yup;
- Experiência com back end: NodeJS, TypeScript, Python, NestJS, Serverless, REST, WebSockets;
- Experiência na construção de ChatBots;
- Conhecimento sobre Linux;
- Experiência com Scrum;
- Domínio da língua inglesa.

## Benefícios

- Benefícios flexíveis (cartão Caju).

**Diferenciais:**

- Cultura de liberdade e autonomia;
- Time colaborativo;
- Startup com muitos desafios e oportunidades.

## Contratação

Contratação de trabalho PJ.

## Como se candidatar

Se você se interessou pela oportunidade, envie seu currículo para [people@cosmobots.io](mailto:people@cosmobots.io)

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
