### ISSUE TITLE
[100% Remoto] Staff Frontend Engineer no DB1 Group

### ISSUE THREAD

**Issue by alissongusmao** [frontendbr/vagas#6786]
## Nossa empresa

Somos um grupo de empresas de tecnologia, nascido no interior do Paraná, com mais de 20 anos de experiência em desenvolvimento de software voltado para soluções de grandes empresas. Atuamos em diversas frentes de mercado, como na DB1 Global Software (DGS), que é a nossa SoftwareHouse.

Aqui trabalhamos com a transformação digital alinhada a uma entrega de valor aos nossos clientes. Aqui, entendemos que o profissional e pessoal andam juntos, por isso, cultura importa tanto quanto conhecimento técnico. A DB1 é uma empresa de tecnologia com padrão global de qualidade, mas a nossa principal preocupação vai além do software: queremos melhorar a vida das pessoas. 

## Descrição da vaga

Seu papel na DGS:

Ser a referência técnica do time, ajudar o time evoluir suas habilidades, ser responsável sobre a qualidade do trabalho desenvolvido pela equipe e responder (ser o porta-voz) tecnicamente pela DB1

Suas principais entregas:

Garantir que os projetos estão saudáveis tecnicamente.
Garantir bom desempenho de métricas de código que apontam qualidade, confiabilidade, segurança, entre outros requisitos não funcionais.
Empregar boas práticas de desenvolvimento de software.
Garantir que soluções técnicas complexas estão adequadas ao cenário.
Trazer inovações que gerem valor na atuação, além do dia-a-dia operacional.
Garantir que o trabalho que está sendo executado reflete em ganhos reais para o(s) time(s) que está envolvido
Garantir que haja direcionamento técnico de carreira para o(s) Lead Engineer(s) com quem está envolvido.
Entender cenários do cliente e propor solução para problemas complexos na evolução do software.
Buscar novas maneiras de melhorar o desenvolvimento de software que praticamos.
Ajudar na evolução da maturidade técnica dos projetos da DB1.
Tomar decisões técnicas que empregam boas práticas visando um software com arquitetura e design saudáveis. 

## Local

100% Remoto em qualquer lugar do mundo ou presencial em Maringá/PR

## Requisitos

**Obrigatórios:**
Vivência em aplicações distribuídas e com cenários críticos de alta disponibilidade.
Conhecer, ao menos, dois dos frameworks à seguir: React, Angular, VueJS, Laravel/Symfony.
5 anos ou mais de experiência em desenvolvimento de software, liderando projetos tecnicamente, com portfólio e cases que possa apresentar.
Conhecimento sólido (prático) em um grande cloud provider (aws, azure ou gcp), SPAs, aplicações offline-first, internacionalização.

**Desejáveis:**
Pós Graduação em área de tecnologia
Inglês (para conversação)
Conhecer mais de duas das linguagens à seguir: React, Angular, VueJS, Laravel/Symfony.
Conhecer Progressive Web Apps.
Experiência em desenvolvimento de apps híbridos.

**Diferenciais:**
Comunicação assertiva
Gestão do Tempo
Autonomia e responsabilidade
Autogerenciamento
Liderança
Negociação
Orientação para resultados

## Benefícios

Plano de saúde
Participação sobre Resultados
Gympass
Cartão de Benefícios Flexíveis com bandeira Mastercard
.Auxílio Home Office
Horários Flexíveis
Plano Odontológico (opcional)
Plano de Vida (opcional)
Universidade Corporativa
Possibilidade de Mudança de Carreira dentro do Grupo DB1
Atuação com grandes marcas do mercado, inclusive Trilha de carreira estruturada internacional
desde a entrada (DRD, ADM, PDI e feedbacks de evolução)
Dentre outros.

Diferenciais:
Qualidade em todos os aspectos.
Oportunidade de Crescimento.
Liberdade e autonomia, para sugerir, criar e mudar.
Atuação em soluções globais.

## Contratação

CLT

## Como se candidatar

Por favor envie um email para alissonl.gusmao@db1.com.br com seu CV anexado - enviar no assunto: Vaga Frontend Engineer 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: talentos@db1.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Especialista

**Comment by jeanmalves** [comment]
Olá, fui enviar meu CV pelo email informado mas recebi um email de volta dizendo que foi bloqueado. Sabe dizer o que pode ter ocorrido?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
