### ISSUE TITLE
[São Paulo] Front-End Developer na Editora Abril

### ISSUE THREAD

**Issue by mpilao** [frontendbr/vagas#679]
## Descrição da vaga

Procuramos desenvolvedor(a) Front-End Developer para compor nossa equipe!

## Local

Escritório, São Paulo - Pinheiros, ao lado da estação do metrô.

#### Diferenciais

- Horário flexível
- Home office
- Local descontraído
- Video game
- Traje informal
- Café

## Requisitos

**Obrigatórios:**

- Inglês ( Avançado ou Fluente )
- Ser graduado ou estar matriculado em algum curso superior nas áreas de Engenharia de Computação, Ciência da Computação, Sistemas de Informação, Análise de Sistemas e afins.

Conhecimento em:
- HTML5, CSS3, Javascript, SASS, Bootstrap e PHP ou linguagem similar;
- Responsive / Adaptative Web Design;
- Ferramentas de gerenciamento de dependências (Ex: Grunt, Bower, etc.);
- Fazer recortes de layout em alguma ferramenta de edição de imagens;
- Processo de desenvolvimento, desde o levantamento de requisitos até a entrega;
- Sistemas de versionamento de código;
- Lógica de programação ;    
- Cross-Browser / Cross-Platform Development 

Comportamental:
- Ter perfil pró-ativo, ser curioso e demonstrar constante aprendizado;
- Ter atenção aos detalhes, ser persistente e se preocupar com a qualidade de suas entregas;
- Ter atitude colaborativa;
- Dar suporte à manutenção e evolução do processo;
- Compartilhar conhecimentos adquiridos para além de sua equipe;

**Desejáveis:**

Conhecimento em:
- Plataforma WordPress, plugins e templates;
- Metodologias ágeis;

## Contratação

PJ a combinar, com possibilidade de contratação CLT dependendo do desempenho;

## Nossa empresa

O Grupo Abril é um dos maiores e mais influentes grupos de Comunicação e Distribuição da América Latina.

Com mais de 60 anos de história, a Abril está presente na vida de milhões de pessoas, disseminando conteúdo de credibilidade em diversas plataformas. Com negócios baseados em informação, tecnologia e infraestrutura, faz parte da indústria que mais cresce no mundo: a indústria do conhecimento.

Buscamos talentos inovadores, comunicativos, abertos a mudanças e cheios de energia para escrever agora o sucesso do futuro. Se você tem esse perfil, venha trabalhar com a gente.

## Como se candidatar

Por favor, envie um email para alessilva@abril.com.br, com seu CV anexado - enviar no assunto: Vaga Front-End Developer

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by mpilao** [comment]
Pode fechar, por favor!
