### ISSUE TITLE
[Híbrido] Full Stack Developer React + PHP na Loop Brasil

### ISSUE THREAD

**Issue by williamespindola** [frontendbr/vagas#6792]
## Nossa empresa

Pra quem compra ou vende um veículo, existe sempre a busca pelo bom negócio. Somos tecnologia, processos e pessoas dedicados a melhorar nossos serviços para que o seu negócio aconteça. Fazemos tudo: Remoção, vistoria, anúncio, negociação, transferência, documentação, financiamento, seguro, logística, recebimento e pagamento.  
A Loop é uma empresa da Webmotors com a Estapar fundada em 2014, já efetuamos a venda de mais de 70 mil veículos e realizamos mais de 1500 eventos de comercialização com presença em todo o Brasil com mais de 10 lojas e 7 pátios. Com esta estrutura podemos atender todos os públicos tanto empresas na composição de estoque e desmobilização de frotas ou pessoas físicas em busca de comprar ou vender veículos.

## Descrição da vaga

Construir tecnologia na Loop é conectar processos e pessoas tornando a venda e compra de veículos um mecanismo eficiente e escalável, precisamos de pessoas famintas por inovações e eficiência para manter um ecossistema de sistemas distribuídos eficientes sempre atento a segurança e requisitos que fazem da empresa excelência.   
Evoluir os sistemas legados que já estão em processo de substituição por tecnologias novas e mais eficientes.  
Estar sempre atento a qualidade do código aplicando boas práticas de design, documentação e testes.

## Local 
Híbrido. O trabalho na Loop inclui funções remotas e no escritório em São Paulo/SP - Vila Olímpia.  

## Requisitos

- OOP e boas práticas relacionadas como SOLID e Object Callisthenics
- PHP 7.4+ com algum framework (preferencialmente Zend, symfony)
- Conhecimento front-end (NextJs + ReactJS + SSR + RectQuery + JSS)
- Experiência com Web Standards (HTML5, CSS3)
- Interessado em criar uma bela interface do UI/UX com atenção cuidadosa à perspectiva do usuário final
- Conhecer os conceitos de uma API REST/JSON e Protocolo HTTP
- Capacidade de escrever código de alto desempenho, limpo e reutilizável para componentes da interface do usuário
- Experiência com frameworks de tetes unitários e funcionais
- Git, só fazer commit não vale, tem que saber o que é rebase e usar no dia a dia
- Banco de dados relacional e documental
- Experiencia com aplicações de alta disponibilidade
- JWT

## Desejável

- Conhecimento profundo do ecossistema de front-end (Webpack, etc.)
- DDD (Se for senior é requisito)
- Docker (Se for senior é requisito)
- Material UI
- Programação Funcional
- Experiência com WebSockets ou qualquer outra api assíncrona
- Redux

## Diferenciais

- Projetos open source
- Conhecer e participar de comunidades
- Inglês básico

## Benefícios
- Descanso remunerado de 30 dias

# Contratação
PJ

## Como se candidatar

Por favor envie um email para t.william.espindola@loopbrasil.com com seu CV anexado ou Linkedin atualizado, link do github se tiver e proposta de salário - enviar no assunto: Full Stack Developer

### Tempo médio de feedbacks
Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: t.william.espindola@loopbrasil.com

### Alocação:
- Híbrido

### Contratação:
- PJ

### Experiência
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
