### ISSUE TITLE
[Remoto] Front-end Developer ( React / Flutter ) na @Meta

### ISSUE THREAD

**Issue by techrhrj** [frontendbr/vagas#6793]
Confie em quem entende de Tecnologia e venha com a META!!! Conheça nosso site https://www.meta.com.br/ 

"Front-End Developer ( React/Flutter ) "

## Requisitos

**Obrigatórios:**

- Experiência de no mínimo de 4 anos com React e Flutter;
- Conhecimentos avançados em HTML e CSS;
- Conhecimento de APIs REST;
- Conhecimentos em Swagger - Conhecimento de Microsserviços e Microfrontends
- Experiência com Continuous Deployment (Azure DevOps);

## Benefícios

- Plano de saúde
- Plano odontológico
- Seguro de vida
- PLR
- Alura
- Plataforma da Vittude
- Ajuda de Custo
- VA/VR

## Contratação

CLT + benefícios

## Como se candidatar

Envie seu CV para thais.franco@meta.com.br 

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
