### ISSUE TITLE
[Remoto] Senior Front-end Developer (React/Next) @ Motrix

### ISSUE THREAD

**Issue by tregismoreira** [frontendbr/vagas#6796]
## Apresentação
Somos uma EdTech com a missão de apoiar as escolas na sua nova realidade híbrida, desenvolvendo uma plataforma de aprendizagem baseada em evidências, ciência e tecnologia.

Estamos buscando uma pessoa desenvolvedora front-end com muita experiência em React/Next para nos ajudar no desenvolvimento de produtos digitais que vão contribuir para a **transformação da educação no Brasil e no mundo**.

## Você vai se dar bem se

- Tem paixão por entregar soluções de alta qualidade;
- Tem auto-motivação e capacidade de trabalhar de forma autônoma em um time diverso e distribuído;
- Sabe se comunicar de forma clara e objetiva em Português e Inglês;
- Valoriza mais os itens à esquerda do [Manifesto Ágil](https://agilemanifesto.org/) do que os da direita;
- Busca compreender as reais motivações de uma tarefa antes de executá-la;
- Tem uma mentalidade LEAN e está constantemente procurando cortar desperdícios;
- Tem iniciativa e proatividade; Busca não ser apenas um(a) "escrevedor(a) de código";
- Consegue comunicar de forma clara as decisões complexas de arquitetura;
- Gosta de trabalhar em equipe e busca sempre contribuir para a melhoria de todo o time;
- É capaz de discutir de forma construtiva sobre soluções, abordagens ou tecnologias mesmo que não concorde com elas de primeira.

## Você precisa ter

- Pelo menos 5 anos de experiência comprovada com desenvolvimento de aplicações web;
- Pelo menos 2 anos de experiência prática diária com React;
- Sólidos conhecimentos em JavaScript, TypeScript, ES6+;
- Experiência trabalhando com APIs REST e GraphQL;
- Domínio de Recoil para gerenciamento de estado global da aplicação;
- Experiência com APIs REST e GraphQL;
- Capacidade de explicar a diferença entre SSR (server-side rendering) e SSG (static site generation);
- Trabalhado com algum framework React como Gatsby ou Next.
- Tenha experiência com bibliotecas de testes em Javascript (Jest, Mocha etc);

## É muito interessante que você

- Tenha experiência com AWS (API Gateway, Lambda, DynamoDB, Cognito);
- Tenha um olhar para Design e saiba usar Figma, Sketch, Adobe XD ou similar;
- Tenha capacidade de "se virar" escrevendo código backend (Node.js, Python) quando necessário;
- Tenha empatia e um carinho especial com os usuários das aplicações que você estiver trabalhando;
- Tenha muita atenção aos detalhes e lembre-se de incluir a palavra "bazinga" no email de aplicação à vaga;
- Já tenha contribuído com front-end em algum projeto open-source (código, plugin, componente etc);
- Já tenha trabalhado em uma Startup SaaS.

## Oferecemos

- Salário bruto de R$ 14.000~20.000, de acordo com a experiência;
- Equipamento corporativo (se necessário)
- 30 dias de descanso por ano
- Verba anual de R$4.500 para educação e/ou bem-estar
- Trabalho remoto - trabalhe de qualquer lugar;
- Autonomia, responsabilidade, flexibilidade;
- Ambiente de trabalho de startup (estrutura horizontal com muita colaboração entre todas as áreas);
- **A oportunidade de contribuir para a transformação da educação no Brasil e no mundo, juntamente com uma equipe de ponta com muita experiência em educação e tecnologia**.

## Forma de contratação

- PJ

## Como se candidatar

Envie um email para jobs@motrix.global com:
- Assunto: **Senior React Developer**;
- Seu CV anexado e/ou LinkedIn;
- Link para seus perfis no Github e StackOverflow.

#### Alocação
- Fulltime
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by miltonbolonha** [comment]
Sou especialista em GatsbyJS: https://boilerplate-blog.netlify.app/
O código: https://github.com/nuktpls/gatsby-theme-boilerplate-blog

**Comment by miltonbolonha** [comment]
@tregismoreira tks

**Comment by tregismoreira** [comment]
@miltonbolonha aplica à vaga lá ;)

**Comment by miltonbolonha** [comment]
@tregismoreira aplicado ;)

**Comment by miltonbolonha** [comment]
@tregismoreira Enviado, mas nenhum sinal de vida do outro lado.

**Comment by miltonbolonha** [comment]
Então tá bom, muito obrigado a todos.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by miltonbolonha** [comment]
Esse @tregismoreira acha q a vida é BRINCADEIRA ? IRRESPONSÁVEL !!!
