### ISSUE TITLE
[Remoto/Florianópolis] Front-end Developer na Softplan

### ISSUE THREAD

**Issue by patriciasaramela** [frontendbr/vagas#6797]
## Softplan

Somos uma das maiores desenvolvedoras de software do país e atuamos diariamente para promover transformações fundamentais na vida de milhares de pessoas que são beneficiadas por nossas soluções nos mercados da Gestão Pública, Justiça e Indústria da Construção. Vem ser Softplayer e fazer parte de uma empresa GPTW!

## Descrição da vaga

Essa vaga é ideal pra quem ainda está começando mas tem muita vontade de aprender.

### Seu desafio será:
Desenvolvimento de protótipos funcionais de aplicações web para testes com usuários.

### O que você traz:
- Conhecimento em JavaScript e na biblioteca ReactJs, incluindo componentização e ES6+;
- Conhecimentos avançado em HTML e CSS, incluindo conceitos de layout, compatibilidade entre browsers e acessibilidade;
- Conhecimento básico em GIT;
- Ter um perfil proativo, boa comunicação, raciocínio lógico, responsabilidade e comprometimento.

### Você irá se destacar se conhecer:

- Conhecimento em princípios de design de interação, UX e Design System;
- Conhecimento em gerenciadores de estados, incluindo Redux e seus padrões de arquitetura;
- Conhecimento de técnicas e práticas de Clean Code;
- Conhecimento das diretrizes de interfaces da Google (Material Design);
- Habilidade em desenvolvimento de animações e micro-interações com Javascript/CSS3/SVG/etc;
- Proatividade e autogerenciamento;
- Conhecimentos sólidos em responsividade e Grid Layout.

## Local

O modelo de trabalho conta com as opções de home&office (modelo híbrido - parte remoto e parte presencial com média de 2x por semana no escritório) ou anywhere office (100% remoto). Esta vaga aceita candidaturas nos dois modelos.

## Benefícios

- Vale-alimentação/Vale-refeição; 
- Plano de saúde e odontológico; 
- Vale-transporte; 
- Bônus anual por resultados; 
- Programa de promoção à saúde e bem-estar;
- Programa Desenvolve Softplan: apoio para realizar cursos e certificações; 
- Parcerias e descontos.

Um dos nossos pilares é a valorização das pessoas e temos orgulho de dizer que somos uma empresa que apoia a diversidade e inclusão. Sendo assim, consideramos todos os candidatos para as nossas vagas, sem distinção de raça, cor, religião, gênero e identidade de gênero, nacionalidade, deficiência, orientação sexual, ascendência, idade, etc.

## Contratação

CLT

## Como se candidatar

Por favor se cadastrar nesse link https://jobs.kenoby.com/softplan/job/pessoa-desenvolvedora-react-jr-cod-3187-segmento-justica/62580832b9550971d15175ad,

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by higorrfa** [comment]
A vaga já foi preenchida? O link de cadastro tá redirecionando pro site principal

**Comment by patriciasaramela** [comment]
Recebemos vários currículos, e a vaga foi pausada pra podermos a alisar os
currículos

Em sex., 22 de abr. de 2022 08:49, Higor Roberto ***@***.***>
escreveu:

**Comment by DanielKitanaxiFilipe** [comment]
enviado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by patriciasaramela** [comment]
A vaga já foi preenchida, obrigada.
