### ISSUE TITLE
[Remoto] Pessoa Desenvolvedora WordPress Sênior no C6 Bank (Atom Team - C6 Sites)

### ISSUE THREAD

**Issue by gabrigcl** [frontendbr/vagas#6798]
### DESCRIÇÃO DA VAGA

Procuramos uma pessoa para ajudar na evolução de nossas plataformas de Gerencimanto e Disponibilização de Conteúdo e impulsionar cada vez a presença digital do C6 Bank.

E para alcançar estes objetivos, contamos com uma arquitetura de CMS Headless ligado a aplicações [Next.js.](http://next.js./)

### O Atom Team C6 Sites

A equipe que cuida dos Sites do C6 preza por um ambiente cheio de bom humor, colaboração e transparência. Nosso desafios técnicos giram em torno de entregar, com agilidade e qualidade, páginas e aplicações.

### RESPONSABILIDADES E ATRIBUIÇÕES

- Criação, evolução e manutenção de aplicações WordPress
- Guiar o projeto para as melhores práticas de desenvolvimento e segurança (Hardening e OWASP Top 10)
- Design e documentação de APIs

### O que é necessário ter:
- Conhecimentos sólidos em WordPress e a sua arquitetura
- Conhecimento da arquitetura Headless
- Conhecimento básicos em React (ou outro framework/lib)
- Conhecimento em testes (unitários, integração e E2E)
- O que é interessante ter:
- Noções de Docker
- Noções de GraphQL
- Noções de CI/CD
- Conhecimento básico em [Node.js](http://node.js/)
- Conhecimento em estratégias de renderização front-end (SPA, SSR, SSG e JAMStack)

### O BANCO DA VIDA DE 14 MILHÕES DE PESSOAS

Somos um banco completo, lançado em 2019, e já superamos a marca de 14 milhões de clientes no Brasil. Atendemos pessoas físicas, MEIs e PMEs e estamos presente em 100% dos municípios brasileiros. Sem agências físicas, oferecemos produtos financeiros acessíveis para todos os perfis de clientes.

Com sede em São Paulo, temos no grupo mais de 2.500 colaboradores. Em poucos mais de dois anos de operação, recebemos diversos reconhecimentos. Fomos eleitos pelo Glassdoor como empresa mais amada (2019), com base na opinião dos colaboradores, e, em 2019 e 2020, fomos reconhecidos como o banco digital com melhor experiência de abertura de conta, segundo pesquisa da idwall. Também em 2020 fomos escolhidos como o melhor banco digital pelo Prêmio Canaltech. Além disso, ficamos em 1º lugar no LinkedIn Top Startups 2021, a lista das startups em que os brasileiros mais desejam trabalhar.

Aqui no C6 Bank, valorizamos o diálogo, a abertura e, acima de tudo, o respeito. Estamos construindo, em nosso dia a dia e nos nossos processos seletivos, uma cultura de respeito à diversidade e inclusão. Aqui vale o poder do autor. Todo mundo deve ter liberdade e autonomia para propor novas ideias e construir coisas incríveis.

Queremos mudar a experiência das pessoas com os serviços financeiros. Quer participar dessa jornada com a gente? Confira nossas vagas e cadastre seu currículo no nosso banco de talentos!

### Contratação
CLT

### Como se candidatar
Através da nossa página no Gupy, [clique aqui](https://c6bank.gupy.io/job/eyJqb2JJZCI6MTcxNDA4NCwic291cmNlIjoiZ3VweV9wdWJsaWNfcGFnZSJ9?jobBoardSource=gupy_public_page)

### Labels

**Alocação**
Remoto

**Regime**
CLT

**Nível**
Sênior

**Comment by VictorPubh** [comment]
Opa, é minha. xD

**Comment by DevCleverton** [comment]
up!

**Comment by VictorPubh** [comment]
Você tem noção de quanto tempo vai durar este processo?
