### ISSUE TITLE
[REMOTO/Curitiba] Front-end Developer na Mercado Radar

### ISSUE THREAD

**Issue by beniciodaniel** [frontendbr/vagas#6799]
## Nossa empresa

Dizem que “dados são o novo petróleo”, e aqui na [Mercado Radar](https://www.linkedin.com/company/mercadoradar/) nós levamos essa frase a sério: Ajudamos os vendedores do Mercado Livre a venderem mais através de dados e inteligência de mercado. Em 2020, nossos clientes movimentaram mais de R$ 600 milhões em vendas. O e-commerce foi o setor no mundo que mais cresceu, mesmo com a pandemia de COVID-19. 

Temos grandes objetivos e estamos recrutando talentos para essa jornada!

## Descrição da vaga

- Construir interfaces a partir de mockups
- Desenvolver testes unitários para garantir a funcionalidade dos componentes
- Projetar e desenhar códigos que sejam confiáveis e reutilizáveis
- Participar de revisões de design com equipe e partes interessadas para decidir entre as tecnologias disponíveis
- Integração com APIs
- Revisar e refatorar os códigos existentes
- Revisar o código desenvolvido por outros desenvolvedores e fornecer feedbacks para garantir as melhores práticas
- Garantir o melhor desempenho e usabilidade das aplicações
- Fazer a triagem de problemas do produto ou do sistema e depurar, rastrear e resolver analisando as fontes dos problemas e o impacto na qualidade do serviço
- Contribuir com a documentação

## Local

Remoto ou Escritório (Centro de Curitiba/PR)

## Requisitos

**Obrigatórios:**
- Experiência comprovada de pelo menos 2 anos como Frontend Developer e pelo menos 5 anos como desenvolvedor
- Conhecimento prático em HTML / CSS
- Conhecimento em pré-processadores CSS como Sass
- Conhecimento avançado em JavaScript
- Confortável trabalhando com o controle de versão (Git)
- Conhecimento em Vue.js e Vuex
- - Caso não tenha, pelo menos com React.js e Redux / Recoil e/ou, no mínimo, com ContextAPI
- Experiência com gerenciador de dependências como NPM e Yarn
- Experiência com testes automatizados
- Experiência com Bootstrap (BootstrapVue)

**Desejáveis:**

- Conhecimento em TDD

**Diferenciais:**
- Ter experiência com refatoração de arquitetura em projetos complexos ou grandes
- Ter experiência com projetos complexos em Vue.js
- Ter trabalhado com Typescript
- Ter trabalhado com testes de integração e2e como Cypress
- Experiência com backend

## Benefícios

- Ambiente de trabalho descontraído e informal no Centro de Curitiba-PR
- Comida liberada
- Horário flexível
- Plano de saúde e odontológico
- Vale-Refeição de R$ 450/mês
- Happy Hours internos
- 1 Friday-Off / mês (geralmente na última sexta-feira do mês)

## Contratação

- CLT

## Como se candidatar

Se candidate por [aqui](https://docs.google.com/forms/d/e/1FAIpQLSdC5CiahJU7Slu5KJy1yPg_SJZAXgWCXqYnqThdH8FCNihhjQ/viewform)

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
