### ISSUE TITLE
[Florianópolis/SC] Desenvolvedor Java Full Stack 

### ISSUE THREAD

**Issue by Segware** [frontendbr/vagas#68]
## Descrição da vaga

Atividades: atuar no desenvolvimento em Java (back e front-end) dos produtos da Segware.

## Local

Rodovia SC 401, 8600
Corporate Park - Bloco 2 - Sala 7
Santo Antônio de Lisboa, Florianópolis - SC
CEP: 88050-001

## Benefícios

- Vale alimentação/refeição (sem desconto em folha)
- 1h30 de almoço
- Lanche da tarde na empresa / espaço lounge com videogame 
- Unimed e Uniodonto
- Seguro de Vida
- Ginástica Laboral
- VT ou estacionamento pago pela empresa
- Auxílio educação
- Cursos de Idiomas in company

## Requisitos

Conhecimentos necessários em: 
- Java (avançado)
- Spring / Hibernate
- HTML
- CSS (Bootstrap)
- Frameworks javascript (Angular JS e JQuery)

Conhecimentos desejáveis em:
- Flex, utilização de controle de versão e metodologias ágeis.
- Inglês e/ou espanhol.

* Experiência necessária com desenvolvimento em Java front e back-end.

## Contratação

CLT a combinar

## Nossa empresa

A Segware é uma empresa multinacional responsável pelo desenvolvimento e comercialização do sistema de monitoramento de alarmes SIGMA, software mais completo da sua categoria, com mais de 70% das contas monitoradas no Brasil. Fundada em 2001, em Florianópolis/ SC atendendo a demanda de uma empresa de serviços de segurança e hoje líder absoluta no segmento de software de monitoramento de alarme.

## Como se candidatar

Por favor envie um email para gestaorh@segware.com.br com seu CV anexado - enviar no assunto: Vaga Full Stack.

**Comment by LFeh** [comment]
;)

**Comment by eduardojmatos** [comment]
@Segware a vaga ainda existe? Nos avise pra mantermos ou removermos da lista :)

**Comment by Segware** [comment]
A vaga já foi preenchida :)

**Comment by eduardojmatos** [comment]
@Segware :)

**Comment by camilatigre** [comment]
@Segware 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
