### ISSUE TITLE
[Remote] Front-end Developer at Jobsity

### ISSUE THREAD

**Issue by LourdesSanchis** [frontendbr/vagas#6800]
**Hello GitHub community!**
I am Lourdes Sanchis, sourcer at Jobsity. We´re looking for Sr Frontend Developers with +3 years of experience and a good English level.
We have some benefits, such us remote wokr and very good salaries in USD. Also: 

-15 working days of paid vacations
-3 extra off days per year
-Paid local holidays
-Paid time off
-Budget for e-learning courses
-Financing program for equipment

If you are interested or you know someone who could be interested, please contact me at lourdes.sanchis@jobsity.com or at [Lourdes Sanchis](https://www.linkedin.com/in/lourdes-sanchis-192a58148/)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
