### ISSUE TITLE
[Remoto] Front-end Angular Developer (Sênior) na Translucent Computing

### ISSUE THREAD

**Issue by natalianobres** [frontendbr/vagas#6802]
## Translucent Computing Inc

Translucent Computing ([www.translucentcomputing.com](https://github.com/frontendbr/vagas/issues/url)) é uma empresa canadense que se baseia em criar relações que se tornam verdadeiras parcerias.

Translucent Computing é sua parceira na transformação digital, oferecendo serviços completos orientados a dados. Nossos principais serviços são aplicações em nuvem, microsserviços, DevOps e Machine Learning.

Isso começa com uma boa conversa, identificando os valores que podemos fornecer para as pessoas, clientes e parceiros.

Nos empenhamos para criar soluções de alta qualidade enquanto compreendemos os problemas reais.

Trabalhando e treinando os melhores talentos nas tecnologias mais estáveis e avançadas disponíveis - Verdadeira Inovação!

Nossa equipe é composta por um grupo dedicado, trabalhador, orientado a resultados, independente e divertido. Trabalhar remotamente em todo o mundo nos permite ter diversidade tanto na cultura quanto no talento. Atualmente estamos crescendo e estamos ansiosos para construir o futuro com você!

## Descrição da vaga

- Trabalho remoto - Trabalhe em Casa com uma empresa Canadense Internacional.
- Capacidade de trabalhar com as tecnologias mais avançadas
- Treinamento ministrado internamente e externamente com o suporte da empresa
- Tempo dedicado para o treinamento dos funcionários durante o horário de trabalho
- Temos uma mentalidade de sempre melhorar e aprender
- Empresa privada
- Baixa rotatividade
- Trabalhando com uma equipe internacional
- Equipe culturalmente diversificada
- Ambiente flexível e orientado a resultados
- Pessoas boas, divertidas e realistas
- Benefícios oferecidos à equipe em todo o mundo
- Roteiro de carreira para crescer a longo prazo
- Promovemos internamente primeiro!
- Equipe de liderança atenciosa e compreensiva

**Divisão das funções em % de tempo:**

85%  em Angular Front end
15%  em reuniões, Scrum, pesquisa e treinamento

**Educação / Certificações:**  Bacharel em  Ciência da Computação  - ou experiência equivalente
**Local:**   Trabalho remoto com uma Empresa Canadense Internacional	
**Faixa salarial:**  Dependendo da experiência
 **Data de ocupação do cargo:**  O mais rápido possível 
**Horas:**  40 hours semanais -das  9 horas da manhã até às  5 horas da tarde (EST – Fuso horário de Toronto ) horas principais – Nós somos flexíveis aqui com algum motivo 

## Requisitos

**Obrigatórios:**

- Ter uma sólida experiência de mais de 4 anos em Angular - Angular 2 ou acima 
- Ter um conhecimento sólido em Padrões de código JavaScript 
- Proficiência na escrita de HTML semântico e bem formatado
-  Proficiência na escrita de CSS/SCSS modular
-  Proficiência com a linguagem JavaScript
-  Proficiência com Sass, NPM, AngularJS/Angular ou frameworks similares
-  Proficiência com a linguagem Typescript
-  Proficiência com controle de versão de projetos (GIT)
-  Boa compreensão e experiência com testes unitários (Jest, Jasmine/Karma)
- Experiência com ferramentas de testes automatizados (Cypress, TestCafe)
- Boa compreensão de design e UX
-  Boa compreensão de compatibilidade entre plataformas
- Boa compreensão de RxJS

**Desejáveis:**

- Pensamento crítico
-  Bom gerenciamento de tempo e prioridades
-  **Boa comunicação em inglês - 7 em 10 (7/10) ou melhor nível dessa habilidade (muito necessário) **
- Orientado a processos e procedimentos
- Capacidade de pular para diferentes tarefas conforme necessário
- Proatividade
-  Capacidade de trabalhar de forma independente ou como parte de uma equipe
- Flexibilidade de tarefa - Capacidade de pular para diferentes tarefas conforme necessário, por exemplo: quando um problema de suporte aparece.
-  Boa ética de trabalho
- Conhecimento das expectativas do cliente
-  Seguir os requisitos do cliente
- Constantemente aprendendo e crescendo com a tecnologia

**Diferenciais:**

- Grande diferencial ter experiência com Angular 9 ou acima
- Boa compreensão de Ngrx
- Boa compreensão de React
- Boa compreensão de arquiteturas de microsserviços
- Aplicações móveis para dispositivos celulares e tablets
- Experiência de trabalho com Java e Spring/boot 
- Experiência com gestão e liderança

**Responsabilidades:**

- Desenvolvimento de Websites and aplicações Web em variados projetos de diferentes tamanhos
- Desenvolvimento de sistemas e padrões para o presente e  projetos futuros
- Participação ativa em reuniões diárias de Scrum 
- Participação ativa no nosso canal no Slack
- Colaboração ativa para a nossa documentação de projetos 
- Colaboração com os projetos da equipe para desenvolver os planos e as estimativas dos projetos 
- Colaboração com a equipe de design durante todo o ciclo de vida do software de um projeto.
- Colaboração com o analista de Qualidade de Software para acessar, testar e consertar os problemas em qualidade de software 

## Benefícios

- Participação nos lucros e resultados  
- 1 semana de folga no fim de ano
- Programa de reembolso trimestral de trabalho remoto;
- Brasileiros ganham 10 dias remunerados de folga nos feriados canadenses
- Mais 10 dias de férias
- 5 dias de folgas pessoais
- Auxílios de saúde, transporte e alimentício
 

## Contratação

PJ a combinar

## Como se candidatar

Por favor, se cadastre aqui nesse formulário: [Formulário para Frontend](https://forms.gle/GaB5FKyS5FVZT2Yq8)
Certifique-se de informar os seus horários disponíveis em blocos, por exemplo: SEG (14h - 17h) | TER (19h - 21h) | QUA (18h - 20h) 

#### Alocação

- Remoto

#### Regime

- PJ

#### Nível

- Sênior

#### Categoria

- Frontend

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by natalianobres** [comment]
Olá, pode fechar a vaga

Natalia Nobre
Translucent Growth Team
Email:  ***@***.***
LinkedIn: https://www.linkedin.com/in/nataliasnobre/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
