### ISSUE TITLE
[Remoto] Front-end Developer (VueJS) no Casar.com

### ISSUE THREAD

**Issue by rcpires** [frontendbr/vagas#6803]
## Nossa empresa

Prazer, somos o Casar.com! O maior player diversificado (online e offline) do mercado de casamentos do Brasil, e nascemos do propósito de tornar a jornada do casamento a melhor, mais fácil e encantadora experiência para nossos clientes. Acreditamos em realizar sonhos, e celebrar os momentos especiais da vida - e cá entre nós, casamento é um dos maiores deles, né?

Somos referência em credibilidade no mercado, e por conta disso, conseguimos reunir os melhores parceiros que compartilham dos nossos valores, para oferecermos serviços incríveis e elevar a régua do mercado com nossa excelência operacional, de forma sempre transparente e humanizada - de quebra, nos divertimos muito no processo!

Tudo isso é consequência do nosso propósito - no final das contas, o nosso foco sempre será o brilho nos olhos de nossos clientes e nosso time.

**Como é trabalhar aqui?**

- Um clima bem informal, legal, acolhedor e leve - leveza é um de nossos valores.
- Autonomia para trabalhar e criar em projetos inovadores no mercado tech.
- Colegas de trabalho fora da curva que irão acompanhar você em aprendizados diários.
- Muita celebração! Afinal, essa é a essência do nosso negócio!

## Descrição da vaga

Desenvolver e suportar aplicações Vue.js

## Local

Remoto ou Híbrido, São Paulo/SP - Pinheiros

## Requisitos

**Obrigatórios:**
- Experiência (mínimo 3 anos) com desenvolvimento de software utilizando frameworks em Javascript, principalmente Vuejs;
- Conhecimentos de HTML e CSS, usando as melhores práticas e ferramentas, como SASS, SCSS, PostCSS e Stylus;
- Conhecimento de testes unitários e metodologias de testes;
- Utilizado o Git para controlar o versionamento de seu código;
- Trabalhado com APIs e Web Services;
- Experiência com desenvolvimento de aplicações SPA.

**Desejáveis:**
- Entender sobre metodologia Scrum;
- Possuir noções de docker/containers e node.js.

## Benefícios

- Plano de saúde
- VR de R$ 40/dia (flash)
- Bônus

**Diferenciais:**
Horário flexível (o que importa são as entregas e a interação com o time)

## Contratação

CLT.

## Como se candidatar

Por favor, envie um e-mail para rodrigo@casar.com com seu CV anexado. Enviar no assunto: _Vaga Frontend_

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
