### ISSUE TITLE
[Remoto] Front-end Developer na ZIPIA

### ISSUE THREAD

**Issue by jsantosrh** [frontendbr/vagas#6804]
-->[Remoto] Front-End Developer na ZIPIA

## Zipia

Exemplo: Nosso cliente é uma insurtech que digitaliza vendas de seguros, oferecendo uma plataforma para que corretores e seguradoras possam encontrar clientes interessados em seguros e consórcios. A empresa já ajudou mais de 300 corretoras a fazer 8.000 vendas, com crescimento de mais de 50% em seu primeiro ano.

## Descrição da vaga

- Desenvolvimento e manutenção de sistemas;

- Participar de reuniões chave para direcionamento do produto;

- Codificação de interfaces de usuário e ferramentas interativas em HTML / CSS / JavaScript usando frameworks como jQuery, ReactJS, AngularJS.

## Local
Remoto

## Requisitos

**Obrigatórios:**
-HTML, CSS (Intermediário)
-JavaScript (Intermediário) 
-MySQL
-Wordpress
-Hospedagem e otimização de desempenho
-Habilidades de solução de problemas
-Pronúncia em Inglês nível intermediário (ou superior)

**Desejáveis:**
-Experiência em design de UI/UX
-Experiência em frameworks JavaScript (por exemplo, jQuery, Angular, ...)
-Teste AB
-SEO técnico

**Diferenciais:**
- Raciocínio Logico 

## Benefícios

-Vale Alimentação-R$40,00
-Participação em Lucros e Resultados
-Plano Odontológico
-Vale Farmácia

## Contratação

CLT

## Como se candidatar

Por favor envie um email para jsantos@acelerarh.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: asouza@acelerarh.com.br

#### Alocação
- Remoto

#### Regime
- CLT
#### Nível
- Júnior
- Pleno

**Comment by pablojr17** [comment]
Enviado

**Comment by pablotelles** [comment]
enviado

Em ter., 19 de abr. de 2022 às 10:12, Pablo Gomes ***@***.***>
escreveu:

**Comment by pablotelles** [comment]
Oi
Tudo bem sim e com você?

Acabei de me cadastrar via plataforma, obrigado pelo retorno.

Abraço,

Em ter., 19 de abr. de 2022 13:31, jsantosrh ***@***.***>
escreveu:

**Comment by MateusMontenegro** [comment]
Enviado !

**Comment by victorscarmo** [comment]
Enviado, e obrigado pela oportunidade.

**Comment by victoralmeida23** [comment]
Enviado!

**Comment by rxistodev** [comment]
já mandei, vamo dentro! Sz

**Comment by Lorena-Mattos** [comment]
Enviado

**Comment by DanielKitanaxiFilipe** [comment]
Enviado.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
