### ISSUE TITLE
[Remoto] Frontend React Developer na Marketex

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6806]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/backend-node-developer-185057560?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>Marketex </strong>está buscando <strong>Frontend React Developer</strong> para compor seu time!</p>
<p>Somos uma escola e plataforma de profissões e de carreiras digitais. Há 7 anos ajudamos os profissionais e as empresas a se posicionarem no mercado e na economia digital de forma descomplicada e rápida, instigante e personalizada o aprendizado mais atual que existe,</p>
<p>Acreditamos que a Educação e o Empreendedorismo Digital são grandes caminhos de transformação e que qualquer pessoa ou empreendedor pode conquistar a liberdade para divulgar seus negócios e ter uma nova profissão usando através das mídias e universo digital.</p>
<p><strong>Responsabilidades:</strong></p>
<ul>
<li>Planejar, desenvolver e testar novas funcionalidades de nossas aplicações web e aplicativos mobile.</li>
<li>Colaborar com UX designers e outros desenvolvedores na avaliação de viabilidade técnica de designs e protótipos UI/UX.</li>
<li>Desenvolver código responsivo e fiel às interfaces projetadas pelos UX designers.</li>
<li>Projetar, implementar, documentar e testar código, componentes e bibliotecas reutilizáveis.</li>
<li>Avaliar desempenho e resultados de soluções, buscando melhoria contínua de nossos produtos e serviços.</li>
<li>Trazer sua visão e experiência para a equipe de desenvolvimento.</li>
</ul>
<p></p>

## Marketex: 
 <p>Somos uma escola e plataforma de profissões e de carreiras digitais. Há 7 anos ajudamos os profissionais e as empresas a se posicionarem no mercado e na economia digital de forma descomplicada e rápida, instigante e personalizada o aprendizado mais atual que existe,</p>
<p>Acreditamos que a Educação e o Empreendedorismo Digital são grandes caminhos de transformação e que qualquer pessoa ou empreendedor pode conquistar a liberdade para divulgar seus negócios e ter uma nova profissão usando através das mídias e universo digital.</p><a href='https://coodesh.com/empresas/marketex'>Veja mais no site</a>

 ## Habilidades: 
 - MySQL 
- PostgreSQL 
- REST APIs 
- React.js
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência com ReactJS (mínimo 1 ano) 
- Experiência com consumo de API REST 
- Conhecimento com HTML5 e CSS (principalmente usando styled components) 
- Experiência usando Git 
- Sólidos conhecimentos de JavaScript 
- Conhecimentos de conceitos e boas práticas de desenvolvimento FrontEnd, principalmente responsividade
## Diferenciais: 
 - Experiência com Redux 
- Experiência com React Contexts e React Hooks 
- Conhecimentos em SQL, MySQL e PostgreSQL
## Benefícios: 
 - 100% Remoto
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend React Developer na Marketex](https://coodesh.com/vagas/backend-node-developer-185057560?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by RafaelMouraFrontend** [comment]
Queria aplicar, mas parece que fechou em 3 dias :(

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
