### ISSUE TITLE
[Remoto] Front-End Developer React Pleno na Proteína Digital

### ISSUE THREAD

**Issue by eduardorph** [frontendbr/vagas#6807]
Proteína Digital contrata Front-End Developer React Pleno para atuar no desenvolvimento e manutenção de páginas e aplicações, construindo componentes para serem utilizados no CMS da empresa.

Se encaixa no perfil? 

Então encaminhe seu currículo e venha fazer parte da Proteína Digital!	

#### Requisitos: 
- Javascript ES6
- React
- HTML
- CSS
- Git	

#### Conhecimento em:
- Docker
- Prismic
- NextJS

#### As Principais atividades: 

Dar manutenção e criar novos componentes para a plataforma de cms utilizada. 

#### Soft Skills
- Proatividade;
- Organização
- Boa comunicação
- Inteligência Emocional 

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

#### Contato:
rh@proteina.digital
Esperamos seu e-mail com o assunto [Vaga de Dev React Pleno]

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
