### ISSUE TITLE
[Recife-PE] Front-end Developer na Nutcache

### ISSUE THREAD

**Issue by wilmaolegario7** [frontendbr/vagas#6808]
> Vaga Remota durante a pandemia

## Nossa empresa

Exemplo: Aqui na Corporação ACME somos líderes em...

## Descrição da vaga
Na Nutcache o time de desenvolvedores trabalha com a criação e aprimoramento de funcionalidades para o nosso software.

##Responsabilidades:
● Criação e manutenção de funcionalidades na aplicação web;
● Criação das telas e ações de acordo com a descrição solicitada nas tarefas e exemplificadas
em mock-ups fornecidos;
● Análise, planejamento e desenvolvimento da funcionalidade;
● Colaborar ativamente com o SCRUM Master e o Product Owner nas entregas;
● Participar da análise e arquitetura necessária ao desenvolvimento das tarefas;
● Seguir o método Scrum, utilizada pelos times para gestão das atividades diárias;
● Manter boa comunicação com o time de desenvolvimento discutindo e opinando sobre os
direcionamentos a serem tomados, buscando ajudar na solução de problemas com os pares quando necessário.

## Recife-PE

Híbrido , [PERNAMBUCO], [RECIFE], [PINA]

## Requisitos

**Obrigatórios:**
● Formação Ciência da computação ou cursos relacionados; 
● Experiência (2 anos) em React Js e Redux;
● Experiência em HTML, CSS e Javascript;
● Inglês intermediário / avançado / fluente;
● Entendimento de métodos ágeis e ferramentas Scrum e Kanban.

**Desejáveis:**
● Experiência com ferramentas como Git e Visual Studio Code;
● Noções básicas de UI/UX;
● Experiência com React Hooks;
● TypeScript;
● Redux Toolkit;
● REST API.

## Benefícios
● Plano de Saúde - Bradesco Saúde Top Nacional (100% custeado pela empresa);
● Plano Odontológico - Bradesco Odonto (100% custeado pela empresa);
● Seguro de vida - Prudential;
● Benefício de bem-estar físico e mental - Gympass;
● Vale refeição/alimentação - Flash benefícios flexíveis (Bandeira Mastercard);
● Gratificação por indicação de novos colaboradores;
● Material de trabalho completo;
● Day off no mês de aniversário;
● Horário e formato flexível;
● Auxílio idiomas;
● Auxílios de capacitação técnica;
● Clima colaborativo e flexível.
#site: [www.nutcache.com](http://www.nutcache.com/)

**Diferenciais:**
🥳Salário diferenciado;
🇨🇦Empresa do Canadá;
🗣Oportunidade de praticar o inglês;
🌇Escritório moderno com espaços inovadores;
😌Possibilidade de mudança para o Canadá;
🤓Clima colaborativo e flexível.
- ...

## Contratação
CLT

## Como se candidatar

Por favor envie um email para rhbrasil@nutcache.com seu CV anexado - enviar no assunto: Vaga Front-end Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.

## Labels
🏢 Flexível
🏢 Híbrido
🏢 Remoto
👨 Pleno
👴 Sênior
⚖️ A-Combinar
⚖️ CLT
💰 Em média damos 25% de aumento em cima do salário atual.
#### Alocação
- Híbrido

#### Regime
- CLT
- 
#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by wilmaolegario7** [comment]
Temos muitas vagas!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
