### ISSUE TITLE
[São Paulo] Front-End Especialista no UOL

### ISSUE THREAD

**Issue by Leticiacoelho25** [frontendbr/vagas#681]
## Descrição da vaga

Desenvolvimento de aplicações web utilizando JavaScript e jQuery, CSS 

## Local

Presencial - São Paulo - Região de Pinheiros

## Requisitos

Javascript avançado (OO, herança, prototipação, design pattern).
Experiência na criação de páginas responsivas, web e mobile.
CSS Avançado e CSS3

**Diferenciais:**
Conhecimentos em (gzip, minify, quantidade de requests)

## Contratação

PJ a combinar

## Nossa empresa

Fundada em 2004, somos uma empresa multinacional brasileira provedora de serviços especializados em Tecnologia da Informação, Consultoria, Integração de Sistemas e Inovação. Possuímos soluções de ponta a ponta, adequadas a empresas de todos os portes e perfis de negócios. Presente nos principais mercados da economia brasileira e no mercado internacional, operamos no modelo de empresa de consultoria focada no crescimento dos negócios dos nossos clientes

## Como se candidatar

Por favor envie um email para leticia.coelho@deal.com.br com seu CV anexado - enviar no assunto: Vaga Fron End Especialista

**Comment by AllanD1** [comment]
@Leticiacoelho25 tem alguma chance de trabalho Remoto?

**Comment by Leticiacoelho25** [comment]
@AllanD1 olá Allan, infelizmente não. =/

**Comment by fernando-Jesus** [comment]
Qual produto no UOL?

**Comment by Leticiacoelho25** [comment]
@fernando-Jesus Olá Fernando, Pagseguro.
