### ISSUE TITLE
[São Paulo SP] Front-end Developer Pleno na Beplix

### ISSUE THREAD

**Issue by joaoabdalla** [frontendbr/vagas#6811]
**Descrição da empresa:**

Não somos uma Exchange, não somos uma conta digital, não somos uma tokenizadora, não somos uma Mesa de OTC

Somos o melhor de tudo isso, em um aplicativo transformando Criptomoedas em um cafezinho depois de uma reunião de negócios ou até mesmo pagando a mensalidade da academia.

**Atividades e responsabilidades**

- Desenvolver aplicações mobile em React Native utilizando boas práticas de código econtrole de versionamento.
- Participar da elaboração de novos produtos e suas experiências do usuário
- Auxiliar desenvolvedores juniores no dia a dia

**Requisitos**

- Experiência mínima de 2 anos com React Native
- Conhecimento em git e boas práticas
- Inglês básico (compreensão de textos)

Remuneração

- Salário CLT R$ 6.000,00

Benefícios:

- Vale transporte
- Vale refeição
- Plano de saúde

Oportunidade para trabalho presencial no bairro do Brooklin, São Paulo,SP.

Interessados ou mais informações entre em contato pelo email joao.abdalla@beplix.com

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
