### ISSUE TITLE
[REMOTO] Front-end React Developer @ Meta 

### ISSUE THREAD

**Issue by jenniferaqn** [frontendbr/vagas#6813]
## Nossa empresa

Somos uma empresa com foco em soluções tecnológicas ágeis que simplificam e geram valor real no dia a dia das organizações. Trabalhamos para evoluir o seu negócio de forma rápida, consistente e compatível com as mudanças cada vez mais aceleradas do nosso tempo. Acreditamos que os indivíduos e suas interações fazem o seu e o nosso negócio. Este é o nosso jeito de fazer: com tecnologia e simplicidade.

## Local

Atuação 100% remota.

## Requisitos

**Obrigatórios:**
• Experiência em React
• Experiência em HTML, CSS e Javascript
• Experiência com Git e Git workflows
• Experiência em criar animações, scrolljacking e outras páginas da Web personalizadas complexas
• Experiência trabalhando com TypeScript ou JavaScript (ES6 e acima)
• Experiência com qualquer framework de teste unitário (Jasmine, Jest, Mocha, etc)
• Experiência desenvolvendo componentes web
• Inglês avançado/fluente

**Diferenciais:**
• Conhecimento em experiência do usuário e/ou design
• Firebase
• Familiaridade com programação do lado do servidor (por exemplo, C# e Node.js)
• Familiaridade com banco de dados No-SQL (MongoDB)

## Benefícios

- Assistência Médica e Odontológica
- Seguro de Vida
- VR e VA
- Auxílio home office | Ajuda de custo
- Parceria com Alura
- Parceria com Vittude (40% de desconto em sessões de terapia)
- English Club
- Meta Academy (plataforma interna de treinamentos)

## Contratação

CLT ou PJ, o que você preferir!

## Como se candidatar

Mandar seu cv + pretensão por email: jennifer.silva@meta.com.br

#### Alocação
- Alocado de maneira 100% remota

#### Regime
- CLT
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
