### ISSUE TITLE
[REMOTO] Front-end Angular Developer @ Meta

### ISSUE THREAD

**Issue by jenniferaqn** [frontendbr/vagas#6814]
## Nossa empresa

Somos uma empresa com foco em soluções tecnológicas ágeis que simplificam e geram valor real no dia a dia das organizações. Trabalhamos para evoluir o seu negócio de forma rápida, consistente e compatível com as mudanças cada vez mais aceleradas do nosso tempo. Acreditamos que os indivíduos e suas interações fazem o seu e o nosso negócio. Este é o nosso jeito de fazer: com tecnologia e simplicidade.

## Descrição da vaga

- Atuar com desenvolvimento novas aplicações e manutenções de aplicações já existentes;
- Participar das reuniões diárias, contribuindo com a construção de solução do time;
- Contribuir com a escolha, avaliação e implementação de novas tecnologias.

## Local

Atuação 100% remota

## Requisitos

**Obrigatórios:**
- Conhecimento avançado em Desenvolvimento com HTML5 e CSS3;
- Conhecimento avançado em Angular 5-9;
- Habilidade com versionamento GIT e utilização GIT-FLOW;
- Desejável conhecimento em desenvolvimento PWA;

## Benefícios

- Assistência Médica e Odontológica
- Seguro de Vida

## Contratação

PJ

## Como se candidatar

Envio de cvs por email: jennifer.silva@meta.com.br

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
