### ISSUE TITLE
[[São Paulo]] Front End Developer na [7COMm]  

### ISSUE THREAD

**Issue by Thais7comm** [frontendbr/vagas#682]
## Descrição da vaga

Front End Developer SR
 
Desenvolvimento de sistemas web e front-end (HTML, Javascript, CSS);
Experiência em desenvolvimento PHP;
Conhecimento avançado em Arquitetura de Software;
Desenvolvimento de sistemas web e front-end (HTML, Javascript, CSS);
Conhecimento Design Patterns;
Vivência em metodologias ágeis.

## Local

Presencial com possibilidade remoto em alguns dias da semana: Berrini - Zonal Sul - SP

#### Diferenciais

- horário flexível
- video game
- café da manhã e da tarde
- revistas
- sala de jogos
- ...

## Requisitos

**Obrigatórios:**
Ampla experiência em front (telas/layout) com html, css, javascript

**Desejáveis:**

**Diferenciais:**

## Contratação

PJ a combinar, informe seu valor hora

## Nossa empresa

7COMm há mais de 30 anos no mercado, atuando com serviços e soluções, foi classificada pela revista Exame através do site Love Mondays como umas das 30 melhores empresas para se trabalhar na categoria médias empresas. E acaba de entrar no Ranking no GPTW entre as 110 melhores empresas para se trabalhar na opinião dos nos nossos colaboradores.

## Como se candidatar

Por favor envie um email para thais.carvalho@7comm.com.br  com seu CV anexado - enviar no assunto: Vaga Front-end

**Comment by Finacio** [comment]
Quantos anos de experiência?

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
