### ISSUE TITLE
Pessoa Desenvolvedora Full Stack PL-SQL/WEB Junior

### ISSUE THREAD

**Issue by nicholasess** [frontendbr/vagas#6824]
## Dia a dia do Profissional

Atuar como DEV em uma squad de HUB de Serviços Financeiros voltada para o mercado de cartões com as tecnologias mais avançadas do mercado com projetos desafiadores, além de atuar com profissionais experientes em empresa com mais de 30 anos no mercado de tecnologia.

  
O que usamos aqui: Oracle Pl/Sql, JavaScript, Html, Html5, Css. _Será considerado um diferencial o conhecimento no Framework Web – Oracle Application Express (APEX)._

  
## Requisitos

* Experiência de 02 anos como desenvolvedor e conhecimento em APEX
* Superior Completo em Análise de Sistemas, Sistemas da Informação, Ciência da Computação ou Engenharia da Computação.

## Desejáveis

Conhecimento no Framework Web -Oracle Application Express (Apex)

## Contratação

CLT

## Local

Remoto

## Nossa empresa

Atuando no mercado de tecnologia desde 1987, a INFOX oferece soluções flexíveis, consultores especializados e uma completa infraestrutura de atendimento. Atuando com Soluções de Gestão para o Varejo e Processamento para Meios de Pagamentos, disponibiliza atendimento e treinamento para seus clientes e suas respectivas equipes.

## Benefícios

**_BENEFÍCIOS_** 

* Assistência médica
* Assistência odontológica
* Vale-transporte
* Vale-Refeição/ Vale-Alimentação
* Seguro de Vida
* Auxílio-Creche para filhos até 5 anos completos
* Cartão de Natal
* Subsídio Home Office
* Participação Lucros e Resultados
* Política de desenvolvimento e capacitação profissional

  
**_VANTAGENS_** 

* Laboratório de Inovação
* Programa de Ideias/Inovação
* Programa de Indicação de Novos Colaboradores com bônus em dinheiro
* Homenagem Tempo de Casa
* Kit Casamento / Kit Nascimento Bebê
* Sala de Descompressão, Meet ups, Webinars

## Como se candidatar

Você se identificou com a vaga? Clique [Aqui](https://devsacreditar.com.br/o/pessoa-desenvolvedora-full-stack-pl-sqlweb-junior-CDdgu) para participar do processo seletivo <3

Se você não for compatível com essa vaga, você será avisado na plataforma de futuras vagas que darão match com seu perfil.

## Labels

\- Remoto

\- 👦 Júnior

\- ⚖️ CLT

\- 💰 3K-5K

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
