### ISSUE TITLE
[São Paulo] FullStack Node.js Developer na Yube

### ISSUE THREAD

**Issue by Raffesmind** [frontendbr/vagas#683]
## Descrição da vaga

Queremos uma pessoa para ajudar no desenvolvimento de nossa aplicação, não importando se é Junior, Pleno ou Sênior, para construir e melhorar nossas APIs em Node.js :)

## Local

Rua Ministro Jesuino Cardoso 454 , São Paulo - Vila Olímpia
Parcial Remoto

## Benefícios

- Bônus ao ser contratado para customizar sua máquina da forma que preferir :)

#### Diferenciais

- Parcial remoto, fazemos apenas cerimonias ao vivo, o resto do tempo pode-se trabalhar da forma e de onde preferir :)

## Requisitos

**Obrigatórios:**
- Ter trabalhado mais de 1 ano com Node.js;
- ES2015/2016;
- Conhecimentos em TDD/BDD;
- Ter trabalhado com NOSQL e bancos relacionais;
- Ter trabalhado com versionamento; 

**Desejáveis:**
- Ter trabalhado com Postgresql;
- Ter desenvolvido ou atuado com micro-serviços;
- GraphQL;

**Diferenciais:**
- projetos opensource;
- React.js;
- Ter aprendido e aplicado algo novo no último mês;
- Ser capaz de trabalhar de forma livre e autônoma

## Contratação

PJ a combinar

## Nossa empresa

 Yube quer revolucionar a forma que a pessoa é contratada nas empresas, oferecendo uma plataforma de facilidades para que o candidato faça o processo sem burocracias ou papeladas!

## Como se candidatar

Por favor envie um email para dev@yube.com.brcom seu CV ou Linkedin - enviar no assunto: Vaga NodeJS
Caso tenha dúvidas, pode entrar em contato por email (rafael@yube.com.br), redes sociais, sinais de fumaça ou o que preferir :)

**Comment by Raffesmind** [comment]
Se possível coloquem as tags de Júnior, Pleno e Sénior, com parcial remoto :)

**Comment by brunooomelo** [comment]
Estágio?

**Comment by kavalcante** [comment]
Se eu fosse vocês iria logo trabalhar com o Ventura <3

**Comment by kavalcante** [comment]
@brunooomelo pela descrição:

> Queremos uma pessoa para ajudar no desenvolvimento de nossa aplicação, não importando se é Junior, Pleno ou Sênior

**Comment by lucianopf** [comment]
Boa vaga mano! 

@Raffesmind seu email ta errado aqui `um email para dev@yube.com.brcom seu CV ou Linkedin`

**Comment by Raffesmind** [comment]
@brunooomelo infelizmente hoje não temos condições dessa vaga ser para estágio por estarmos ainda montando o time base de tecnologia, mas quando tivermos a oportunidade de estágio postarei aqui também :)
Mas se houver algo que eu possa te ajudar em relação a dúvidas na área ou da vaga, só falar :)

@kavalcante  ❤️

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by Raffesmind** [comment]
@LFeh desculpa a demora, poderiam fechar a issue? 
Conseguimos fechar a vaga :)
