### ISSUE TITLE
[Remoto/ Híbrido para BH] Full Stack Developer na Devnology

### ISSUE THREAD

**Issue by fabioeilert** [frontendbr/vagas#6832]
## Descrição da vaga

Esta posição tem como objetivo principal em trabalhar no desenvolvimento e manutenção de aplicativos web, utilizando React, Flutter, NodeJS e Laravel.

## Local

Remoto ou Escritório, Belo Horizonte

## Requisitos
Conhecimento em desenvolvimento frontend com React ou Flutter
Conhecimento em desenvolvimento backend com Javascript/Typescript (NodeJS) e PHP (Laravel)

## Contratação

Salário competitivo com o mercado baseado em suas habilidades.
Possibilidade de PJ;
Modelo de trabalho híbrido ou 100% remoto.

## Nossa empresa

Se você é apaixonado por programação, está afim de ser desafiado em projetos top das galáxias e atuar em uma equipe F0d@?

Temos a melhor oportunidade pra você.

Na Devnology trabalhamos com profissionais alinhados aos nossos objetivos, então se o que te atrai é:

Aplicações de alta complexidade;
Possibilidade de atuar com diversas tecnologias;
Trabalhar em um time experiente e multidisciplinar, trocando habilidades e conhecimento para superar os desafios apresentados;
Melhorar constantemente aquilo que você faz;
Essa vaga pode ser sua, se você merecer!

A Devnology está trabalhando em uma série de sistemas e vai formar novas equipes para absorver uma demanda crescente. Esses sistemas estão distribuídos em RESTFul API, integrações, crawlers, automações, sites, sistemas web, apps, análise de dados e muito mais, dê uma olhadinha no nosso site.

Utilizar métodos de boas práticas de programação para o seu código.
Apresentar soluções criativas e eficientes para os problemas do dia a dia.
Garantir uma boa entrega de nossos projetos, com qualidade e consistência.
Manter o constante funcionamento de nossos projetos.

## Como se candidatar

Por favor envie um email para fabio.perin@in8.com.br com seu CV anexado - enviar no assunto: Vaga Fullstack

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: fabio.perin@in8.com.br

## Labels

- Alocado
- CLT
- Júnior
- PJ
- Pleno
- Remoto
- Sênior

**Comment by DanielKitanaxiFilipe** [comment]
Enviado

**Comment by HUDEVBR** [comment]
Feito

**Comment by fabioeilert** [comment]
Obrigado a todos que enviaram seus cvs, a vaga foi preenchida.
