### ISSUE TITLE
[São Paulo] Frontend React Native Developer na BEPLIX

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6833]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-frontend-react-native-212006064?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>A BEPLIX</strong> busca pessoa<strong> Frontend React Native</strong> para compor seu time!&nbsp;</p>
<p>Somos o melhor de tudo isso, em um aplicativo transformando Criptomoedas em um cafezinho depois de uma reunião de negócios ou até mesmo pagando a mensalidade da academia.</p>
<p><strong>Responsabilidades:</strong></p>
<ul>
<li>Desenvolver aplicações mobile em React Native utilizando boas práticas de código e controle de versionamento;</li>
<li>Participar da elaboração de novos produtos e suas experiências do usuário;</li>
<li>Auxiliar desenvolvedores juniores no dia a dia.</li>
</ul>

## BEPLIX: 
 <p>Não somos uma Exchange de criptomoedas, não somos apenas uma conta digital, não somos uma tokenizadora, não somos uma Mesa de OTC.</p>
<p>Somos o melhor de tudo isso, em um aplicativo transformando Criptomoedas em um cafezinho depois de uma reunião de negócios ou até mesmo pagando a mensalidade da academia.</p><a href='https://coodesh.com/empresas/beplix'>Veja mais no site</a>

 ## Habilidades: 
 - React Native 
- React.js 
- Python
## Local: 
 São Paulo
## Requisitos: 
 - Experiência sólida com React Native; 
- Conhecimento em git e boas práticas; 
- Inglês básico (compreensão de textos)
## Diferenciais: 
 - Conhecimentos com Blockchain e criptoativos
## Benefícios: 
 - Vale Transporte 
- Vale refeição 
- Plano de Saúde
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend React Native Developer na BEPLIX](https://coodesh.com/vagas/desenvolvedor-frontend-react-native-212006064?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Regime
CLT
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
