### ISSUE TITLE
[Hibrido / São Paulo, Brazil] Frontend React Developer na Yssy Holding 

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6834]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-react-120130734?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>A Yssy Holding</strong> busca pessoa<strong> Frontend React Developer</strong> para compor seu time!</p>
<p>Nós transformamos empresas em Empresas Inteligentes e sabemos que, para isso, é preciso sair do lugar comum. Por essa razão, abraçamos os desafios da inovação, deixando de lado o jogo seguro que não alavanca negócios que desejam se diferenciar no mercado.</p>
<p></p>

## Yssy Holding : 
 <p>Do Tupi, Yssy é trazer ordem e integração para o mundo. É isso que fazemos por mais de 180 clientes de todo o país.</p>
<p>Nós transformamos empresas em Empresas Inteligentes e sabemos que, para isso, é preciso sair do lugar comum. Por essa razão, abraçamos os desafios da inovação, deixando de lado o jogo seguro que não alavanca negócios que desejam se diferenciar no mercado.</p><a href='https://coodesh.com/empresas/yssy-holding'>Veja mais no site</a>

 ## Habilidades: 
 - React.js 
- Javascript 
- Design UI
## Local: 
 São Paulo, Brazil
## Requisitos: 
 - Ser habituado com metodologias ágeis 
- Flexível 
- Comunicativo
## Diferenciais: 
 - Conhecimento em Visual Studio Code
## Benefícios: 
 - Vale Transporte; 
- Fretado; 
- VR; 
- Assistência Médica; 
- Assistência Odontológica; 
- Seguro de Vida; 
- Previdência Privada; 
- Gympass; 
- Apoiopass; 
- Auxilio Creche; 
- PLR; 
- Stock Options.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend React Developer na Yssy Holding ](https://coodesh.com/vagas/desenvolvedor-react-120130734?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
