### ISSUE TITLE
[REMOTO] Front-end Developer na Plan Marketing Digital

### ISSUE THREAD

**Issue by lrhernandes** [frontendbr/vagas#6836]
## Nossa empresa

Somos um grupo completo. Uma empresa full service, que combina inovação, tecnologia e inteligência para proporcionar experiências digitais relevantes e trazer os melhores resultados há mais de 20 anos.

O Grupo Plan Marketing conta com a Plan Marketing Digital, a Full.Up Publicidade e a Plan XP. 

Com as 3 empresas trabalhando de forma independente, mas integradas, conseguimos unificar as comunicações online e offline dos nossos clientes, em diferentes plataformas e linguagens. 

## Descrição da vaga

O time da Plan está crescendo!

VAGA DESENVOLVEDOR FRONT-END

Que tal participar desses 20 anos de história?

## Requisitos

**Obrigatórios:**
- Javascript
- CSS
- HTML
- Git
- Design Responsivo
- Conhecimento do pacote Office e Google Drive;
- Sentido de urgência;

**Desejáveis:**
- Experiência em cargos ou áreas semelhantes;
- JQuery
- SCSS
- Bootstrap

**Diferenciais:**
- Conhecimentos em frameworks para SPA (Vue e React)

## Contratação

PJ a combinar
Tempo Integral (De segunda à sexta-feira. das 08h30 às 18h18)

## Como se candidatar

Por favor envie um email para rh@planmkt.com.br seu CV anexado - enviar no assunto: Vaga Front-end

#### Alocação
- Remoto
- PJ
- Júnior

**Comment by victorscarmo** [comment]
Enviei meu CV, obrigado pela oportunidade!

**Comment by lrhernandes** [comment]
Já tivemos várias respostas então vou fechar a issue por enquanto para que possamos analisar os currículos de quem já mandou. Se for necessário ela será aberta novamente
