### ISSUE TITLE
[Remote ] Front-end Developer (Angular, TypeScript, CSS, and HTML) at @Turing

### ISSUE THREAD

**Issue by leolacoliver** [frontendbr/vagas#6838]
Only candidates with 3+ years of overall software development experience are eligible for this role.

Turing.com is looking to hire a Front-end Developer on behalf of a US-based company that is disrupting the education industry by providing a real-time collaborative learning platform. The selected candidate will be working with cross-functional teams to successfully deploy products and ship code. The company's platform enables easy collaborative creation, automation, sharing, and remixing of instructional content with a focus on technical subjects such as programming. This will be a full-time position requiring significant overlap with the PST/EST/CST time zones.

Here's everything you need to know to become a Remote Front-end Developer at Turing: 
http://turing.com/s/792T2Q

**Job Responsibilities**
- Architect, develop, and maintain the platform's online application, collaborative learning content editor, and real-time browser-based IDE's Angular-based front-end
- Jump in and learn new technologies
- Convert wireframes and design documents into fully functional web front-end functionality
- Have a hands-on approach with the Angular and TypeScript codebase
- Manage, monitor, and refine front-end performance to ensure that real-time interaction-heavy features are fast and responsive on a variety of user devices
- To better support the user base, grow and increase your knowledge as well as your technology stack
- Share knowledge among peers and establish industrys standard practices across the company

**Job Requirements**
- Bachelors/Masters degree in Engineering, Computer Science (or equivalent experience)
- At least 3+ years of relevant experience as a front-end developer
- Demonstrable experience with Angular, TypeScript, CSS, and HTML
- Experience with the whole web stack, including protocols and network security
- Prior experience working with development teams in a lean, agile environment
- Prior experience building real-time interaction-heavy web applications is nice to have
- Nice to have a strong understanding of how to manage a project, work with deadlines, and prioritize between competing demands
- Ability to write clean and beautiful code, with an eye for simplicity and pragmatism is desirable
- Excellent communication skills

**How To Become a Turing Developer**
- Create your account on http://turing.com/s/792T2Q
- Fill in your basic information (name, number, location, previous salary, experience, etc.)
- Solve multiple-choice questions
- Schedule a technical interview
- Final Onboarding

**Perks & Benefits**
- Earn salaries higher than local standards
- Work alongside a community of Google, Facebook, Microsoft engineers
- Experience rapid career growth
- No visa requirements to work with the best US companies
- Better work-life balance

Hear from developers themselves. Read Turing.com reviews here: https://turing.com/BEpMxr

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
