### ISSUE TITLE
[Remote ] Senior Front-end Developer (React, JavaScript, TypeScript, HTML, and CSS) at @Turing

### ISSUE THREAD

**Issue by leolacoliver** [frontendbr/vagas#6839]
Only candidates with 6+ years of software development experience are eligible for this role.

Turing.com is looking to hire a Senior Front-end Developer on behalf of a NASDAQ-listed company enabling developers to add interactive broadcast, voice, and video calls into mobile and web apps. The selected candidate will be tasked with maintaining and optimizing the platform for efficiency and maximum speed. The company's cloud-based communication platform is implementing industry-leading solutions to help change the way people communicate globally. The company has managed to successfully raise more than $125mn in funding so far. This will be a full-time position requiring significant overlap with the IST time zone.

Here is everything you need to know to become a Remote Senior Front-end Developer at Turing:   http://turing.com/s/792T2Q

**Job Responsibilities**
- Help to plan, build and ship new features by collaborating with users, stakeholders, and other teammates
- Build highly-responsive front-end modules in React along with testing and documentation.
- Work closely on PRs and perform code reviews with your team members.
- Keep improving technical skills by reading codes, documentation, and running experiments

**Job Requirements**
- Bachelors/Master's degree in Engineering, Computer Science (or equivalent experience)
- At least 6-7+ years of experience in building front-end web applications using JavaScript, HTML, and CSS
- Must have a minimum of 3 years of experience in writing SPAs using React and TypeScript
- Expertise in building React Native-based applications
- Must possess a solid understanding of Hooks, SSR frameworks like Next.js, and unit testing frameworks like Jest
- Should possess experience in writing custom webpack configs
- Excellent written and verbal communication skills with fluency in English are essential
- Experience in working with GraphQL and on Android/iOS applications will be a plus
- Solid understanding of desktop development like WinRT (C#) / Mac apps (Swift) is preferred

**How To Become a Turing Developer**
- Create your account on http://turing.com/s/792T2Q
- Fill in your basic information (name, number, location, previous salary, experience, etc.)
- Solve multiple-choice questions
- Schedule a technical interview
- Final Onboarding

**Perks & Benefits**
- Earn salaries higher than local standards
- Work alongside a community of Google, Facebook, Microsoft engineers
- Experience rapid career growth
- No visa requirements to work with the best US companies
- Better work-life balance

Hear from developers themselves. Read Turing.com reviews here: https://turing.com/BEpMxr

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
