### ISSUE TITLE
[Remoto] Pessoa Engenheira de Software - Frontend (React) na RD Station

### ISSUE THREAD

**Issue by AdSegundo** [frontendbr/vagas#6842]
### Seja Pessoa Engenheira de Software - Frontend (React) na RD Station

**Ajudamos pessoas a crescerem seus negócios e países a crescerem suas economias.**

🚀 Somos uma das maiores empresas do Brasil no modelo SaaS (software como serviço). Desenvolvemos uma plataforma 100% brasileira que automatiza tarefas de [marketing digital](http://bit.ly/3pQ2KQs) e [vendas](http://bit.ly/2ZTFzdm);

🌎 Temos desafios de expansão nacional (onde somos líderes) e de [penetração internacional](http://bit.ly/3qY0zvo) na América Latina. Atendemos + 30.000 clientes de todos os portes em +30 países;

⭐ As +700 pessoas do nosso time (RDoers, como chamamos por aqui) nos elegeram 8 vezes uma das melhores empresas para se trabalhar no país e nos deram [4.6 estrelas no Glassdoor](https://bit.ly/2ZOdJiK).

**Candidate-se em https://grnh.se/574784a92us**

## Principais entregas da vaga

- Desenvolver novas features para as soluções principalmente em React (conheça todas as nossas linguagens [aqui](http://bit.ly/3aWvPFH));
- Participar do discovery técnico de novas features, trazendo a visão de engenharia para a solução proposta;
- Executar e medir experimentos no cenário de desenvolvimento em alguns projetos; 
- Seguir nossos [princípios de Engenharia](https://bit.ly/39dwSiT) (Baixo acoplamento, alta coesão; Desenhe seu código para ser fácil de entender, não fácil de escrever; Reduzir a complexidade global é mais importante que reduzir a complexidade local; Automatize tudo).

## Benefícios

Para ver todos os benefícios, acesse este [link](https://talent.rdstation-tm.com/beneficios-rdstation)

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento frontend em React;
- Vivência com boas práticas de desenvolvimento, como Clean Architectures, TDD, BDD, DDD;
- Conhecimento sobre desenvolvimento de software escalável e performático.

**Diferenciais:**
- Experiência trabalhando com micro front-ends;
- Experiência com Design System;
- Atuação com Sidekiq, ElasticSearch;
- Experiência com arquitetura em nuvem (AWS, GCP ou Azure);
- Experiência com metodologias ágeis de entrega, Scrum ou Kanban;
- Conhecimento sobre ferramentas de análise de produto, como Mixpanel, Gainsight PX, Amplitude, Hotjar, Google Analytics ou Segment;
- Inglês ou Espanhol a partir do nível intermediário (fala, leitura e escrita);
- Ser (ou querer se tornar) uma pessoa ativa na comunidade, que compartilha conhecimento dentro e fora da empresa através de eventos, artigos, mentorias, iniciativas voluntárias, projetos open source, etc.

**Candidate-se em https://grnh.se/574784a92us**

**Comment by JonathasGit** [comment]
Legal, já mandei um e-mail lá.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
