### ISSUE TITLE
[Remoto] Frontend Developer na Accursed Share

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6845]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-developer-173446825?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>O <strong>Accursed Share</strong> está buscando <strong>Frontend React Developer </strong>para compor seu time.</p>
<p>Somos um estúdio de produção que aproveita a tecnologia de contrato inteligente emergente para alargar os limites da criptologia. Para além da produção de peças e instalações criptográficas, estamos a desenvolver uma plataforma NFT dinâmica sem código para desbloquear o potencial criativo de contratos inteligentes para milhões de artistas digitais.</p>
<p>Temos o apoio da SevenX Ventures e temos anos de experiência a trabalhar em dados na EventBrite, UpLand, e muito mais.&nbsp;</p>
<p>Para cumprir a nossa missão de trazer uma solução sem código para lançar um milhão de projetos NFT, vamos precisar de apoio nativo e intuitivo da Faktura em aplicações web.</p>
<p><strong>Nossa Stack:</strong></p>
<ul>
<li>Ferramentas: Confluence, Jira, Github(Git), Sonar, CircleCI;</li>
<li>Backend: Serverless, Lambda, Dynamodb, Stream AWS, Redshift, Cognito, Pinpoint, Node.js + Python, Docker, Elasticsearch;</li>
<li>Web: Serverless, NextJs, CSS/HTML5;</li>
<li>Mobilel: Flutter.</li>
</ul>

## Accursed Share: 
 <p>Accursed Share é um estúdio de produção que alavanca a tecnologia de contrato inteligente emergente para expandir os limites do que é possível na criptoarte.</p>

<p>Além de produzir peças e instalações de criptografia orientadas por narrativas, estamos nos estágios iniciais de desenvolvimento de uma plataforma que irá desbloquear o potencial criativo de contratos inteligentes para milhões de artistas digitais, permitindo que eles façam NFTs dinâmicos multifacetados sem a necessidade de um desenvolvedor.</p><a href='https://coodesh.com/empresas/accursed-share'>Veja mais no site</a>

 ## Habilidades: 
 - React.js 
- Next.js 
- Typescript
## Local: 
 100% Remoto
## Requisitos: 
 - Conhecimento em um ou mais dos seguintes aspectos: Javascript, TypeScript, React, Webpack, UI design, HTML & CSS, web fundamentals, APIs, REST, frontend unit & integration testing 
- Experiência na construção de aplicações front-end 
- Inglês intermediário para leitura e escrita
## Diferenciais: 
 - Web3 Development 
- NextJs
## Benefícios: 
 - Unlimited paid web3/blockchain courses. 
- Day-off birthday 
- Co-working
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Developer na Accursed Share](https://coodesh.com/vagas/frontend-developer-173446825?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
