### ISSUE TITLE
[REMOTE] React.JS Developer - Upstack

### ISSUE THREAD

**Issue by nagavi90** [frontendbr/vagas#6847]
## Descrição da vaga

The ideal candidate will be responsible for developing high-quality applications. They will also be responsible for designing and implementing testable and scalable code.

**The work**
- Work with a small team of top-tier developers who are designing great user experiences and building truly great applications for web 
- Participate in scrums consisting of cross-functional teams, both software and hardware 
- Ensure that features are being delivered efficiently and on-time 
- In addition to code contribution, you will also participate in architectural review and design 

## Local

100% Remote.
**Job Type:** Full-time schedule.
**Overlap:** Flexible with EST.

## Benefícios

- **USD compensation.**
- Starter pack: Upstack swag (t-shirts, hoodies, stickers, etc.).
- Work set-up: laptop or device as needed based on project's requirements.
- Ability to choose the project and the team.
- Support for personal and professional growth.
- Bonus structure for special events in your live (marriage, having a baby).
- Flexible working hours.
- Remote first - you can work from anywhere you choose.

## Requisitos

**Minimum qualifications**
- Bachelor's degree in Computer Science or equivalent practical experience.
- 5+ years work experience as a software engineer or relevant experience. 

**Preferred qualifications**
- 3+ yrs of experience in developing JavaScript Applications.
- Deep understanding of React.JS framework.
- Proven track record of shipping software and successfully released apps (please include names and links on your resume).
- Strong attention to detail on every line of code, every unit test, and every commit message.
- Comfortable with rapid development cycles and tight schedules. 

## Contratação

Freelace. 

## Nossa empresa

Upstack is a friendly team of the world’s most talented freelance developers, working remotely for some of the coolest start-ups. It’s fun and challenging to join the top 1% of the world’s developers. We have a strong focus on quality clients and developers and try to work on software that we love! Upstack is officially based in New York City and we have offices in NYC and LA. We also have development hubs opening up all around the place with our first in Brasov, Romania. Our developers work from home and co-working spaces and sometimes even on the beach!

https://upstack.co/

## Como se candidatar

Want to know more? Please send your updated resume or LinkedIn profile to nahuel@upstack.co

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👴 Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
