### ISSUE TITLE
[Remoto] Front-end Developer na Let's Code

### ISSUE THREAD

**Issue by leticia-queiroz** [frontendbr/vagas#6848]
## A Let's Code

Somos uma empresa jovem com desejo de fazer diferente. A educação é a melhor ferramenta para mudar o mundo, no entanto, ela pouco evoluiu nas últimas décadas. Currículos desatualizados, baixa aplicação de tecnologia e alguns outros fatores nos incomodam no formato tradicional de educação.

Se você acredita que estes valores e propósito têm match com os seus, venha fazer parte da nossa equipe!

Nosso time cresce todos os meses e precisamos das pessoas certas ao nosso lado. Queremos construir uma nova educação, realmente centrada no aluno e seu aprendizado para quebrar alguns paradigmas da educação tradicional da Era Industrial.

Ficou interessado em fazer parte desse time fora da curva? Conheça um pouco da nossa cultura: https://bit.ly/3rjE1rf

## Descrição da vaga

A Let's está entrando em uma nova fase mais voltada ao mercado B2B, buscando parcerias com outras empresas para fornecer bolsas de estudos por todo Brasil. Precisamos atualizar o site para refletir essa nova perspectiva, passando para uma plataforma que convida pessoas a participar de nossos processos.

Teremos alguns projetos que você poderá ser alocado para desenvolvimento. Os sistemas também estarão em constante evolução e virão a abrigar novos recursos de acordo com necessidades coordenadas pelo Product Owner.

Um deles envolve a criação de novas landing pages para convidar pessoas a participar de processos seletivos específicos, de maneira geral, a funcionalidade destas páginas será bem semelhante, mas com designs únicos. Outro projeto envolve um front-end para sistema administrativo interno que garanta o bom funcionamento do negócio, além de sistemas de uso externo que otimizem a experiência dos nossos alunos.

Também é importante estar em contato com o time responsável pelo back-end para alinhar as rotas que devem ser criadas/modificadas e consumidas pelo front-end.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Formação em engenharia;
- 3 anos de experiência com Desenvolvimento Front-end;
- JS/TypeScript;
- React hooks / React Context API;
- Consumo de API REST;
- Saber controle de versão com Git;
- Muita vontade de ensinar e aprender;
- Identificação com a cultura da Let's Code;

**Diferenciais:**
- Ter atuado em projetos voltados à educação;
- Ter familiaridade com ambiente e cultura de start-up;
- Next.js;
- Styled Components;
- Testes Unitários com Jest;
- Docker;
- Ter conhecimento ou prática com AWS.

## Benefícios

- Vale Refeição/Alimentação + R$ 200,00 flexíveis para alocar onde quiser!;
- Vale Transporte/Estacionamento;
- Plano de Saúde e Odontológico (Porto Seguro);
- Seguro de Vida;
- Descontos em academias (TotalPass);
- Bônus de até 30% do salário semestral.

**Diferenciais:**
- Horários flexíveis;
- Ambiente dinâmico que proporciona inovação;
- Autonomia está no nosso DNA. Gostamos de incentivar o seu protagonismo na sua carreira;
- Gestão horizontal;
- Happy hour por conta da empresa 1x ao mês com nosso mascote Bowie no escritório.

## Contratação

CLT - Faixa salarial: R$7.500,00 a R$10.100,00

## Como se candidatar

Candidate-se através do link: https://letscode.gupy.io/jobs/1743007

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.

## Labels
<CLT>
<Remoto>
<Pleno>
<Sênior>

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by leticia-queiroz** [comment]
@felipefialho poderia ajustar as labels, por gentileza? Deveria aparecer somente CLT, Remoto, Júnior e Pleno.

**Comment by joaocasarin** [comment]
Oi @leticia-queiroz , aqui não aparece uma opção para enviar o arquivo do CV na vaga. É assim mesmo? Lembro que antes podíamos enviar o arquivo tbm.

**Comment by leticia-queiroz** [comment]
> Oi@leticia-queiroz, aqui não aparece uma opção para enviar o arquivo do CV na vaga. É assim mesmo? Lembrar que antes podíamos enviar o arquivo tbm.

Oi @joaocasarin hoje não olhamos com tanta frequência a caixa de e-mail em que os CV eram enviados, por isso preferimos receber os perfis pela Gupy. Assim que você se candidatar por lá, daremos continuidade no seu processo o quanto antes, combinado?

**Comment by brd3v** [comment]
cv enviado <3 admiro muito a let's code

**Comment by joaocasarin** [comment]
> 

Oi @leticia-queiroz ! Sim sim, eu entendo, mas eu comentei sobre um campo para anexar o e-mail pela gupy mesmo! De qualquer forma, no segundo passo da inscrição apareceu esse campo hahahaha! Ansioso pelo processo, admiro muito a let's code assim como o amigo de cima! :)

**Comment by Gabrielm3** [comment]
Oi @leticia-queiroz, mandei cv, espero fazer parte da let's code! =D

**Comment by Thirki** [comment]
Currículo enviado

**Comment by Gabriel4420** [comment]
no link ta pleno e sênior, nada a ver com o descritivo :/

**Comment by Andre-MR** [comment]
> @felipefialho poderia ajustar as labels, por gentileza? Deveria aparecer somente CLT, Remoto, Júnior e Pleno.
Remove "Júnior", porque a vaga é PL/SR.

**Comment by felipefialho** [comment]
Automatização as vezes falha 😅, arrumei aqui

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
