### ISSUE TITLE
[Remoto - Califórnia] Fullstack Developer na @BeiT

### ISSUE THREAD

**Issue by LilianeBeiT** [frontendbr/vagas#6858]
## Nossa Empresa

Multinacional conhecida por construir fintechs e plataformas de dados de negócios para toda América Latina.

## Descrição da vaga

Implementar e melhorar APIs REST
Criação de componentes modulares do React que sejam tão reutilizáveis ​​quanto possível
Atuação colaborativa com nossos designers para garantir uma excelente UX/UI
Criação de componentes modulares do React que sejam reutiizáveis
Auxiliar na construção de um back-end modular e escalável para nossa plataforma de marca branca, para que possa ser usado em vários bancos e países
Gerenciamento da infraestrutura via AWS e provedores relacionados em regiões e clientes
Garanta a integridade, segurança e privacidade dos dados necessários para aplicativos financeiros
Testes para garantir a estabilidade e a capacidade de manutenção do código

## Local

Remoto atendendo a Califórnia

## Requisitos

**Obrigatórios:**
Sólida experiência com Node.js e React
Ótimas habilidades de inglês e comunicação (adoramos Slack e Hangouts)

**Desejáveis:**

Conhecimento e paixão por UX/UI
Experiência com AWS, CircleCI e/ou Docker
Conhecimento de Infraestrutura como Código
Conhecimento em arquitetura de microsserviços
Experiência com Typescript, typeORM (ou outro ORM), controladores de roteamento ou jest
Experiência na criação de soluções whitelabel
Experiência de trabalho remoto e/ou dentro de uma startup
Experiência de trabalho no espaço financeiro ou B2B (pagamentos, empréstimos, dados, etc.)

## Benefícios

Uma empresa remota, para que você possa trabalhar de onde estiver
Remuneração competitiva com base na localização
Horas de trabalho flexíveis
Feriados locais
PTO ilimitado (mínimo 2 semanas)
Oportunidade de ter um grande impacto em uma startup
Projetos desafiadores que levam você a um crescimento contínuo e novas tecnologias

## Contratação

PJ a combinar

## Como se candidatar

Envie um email para [liliane.lima@beit.work](mailto:liliane.lima@beit.work) ou uma mensagem para a Julia Toldo através do link https://api.whatsapp.com/message/GPEJUWL4AEVMI1?autoload=1&app_absent=0

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: [liliane.lima@beit.work](mailto:liliane.lima@beit.work)

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by odntht** [comment]
@felipefialho as labels estão erradas ai... xD

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
