### ISSUE TITLE
[Rio de Janeiro] Front-end Developer no BIT (B2W Digital)

### ISSUE THREAD

**Issue by leonardodavila** [frontendbr/vagas#686]
## Descrição da vaga

Você irá ajudar a criar a melhor experiência de usuário para os maiores e-commerces da América Latina, como Americanas.com, Submarino e Shoptime.

Se você é um entusiasta de tecnologias novas, gosta de aprender e ensinar, e desenvolver produtos que estão no dia a dia da galera. Então tem o perfil que queremos para o nosso time!

## Local

BIT Mauá - Centro RJ
Rua Sacadura Cabral 130, Saúde, Rio de Janeiro.

## Benefícios

- Plano de saúde
- Plano Odontológico
- Seguro de Vida
- Vale refeição ou alimentação de R$ 23,00/dia
- Vale Transporte
- Clube de Compras nos sites da Americanas.com, Submarino e Shoptime

#### Diferenciais

- Ambiente de trabalho descontraído
- Sinuca e video games
- Flexibilidade de Horário
- Trabalhamos com metodologias ágeis (Scrum)
- Estamos sempre em busca de inovação
- Não desenvolvemos apenas software, também desenvolvemos pessoas 😄 

## Requisitos

**Obrigatórios:**
- Sólidos Conhecimentos de JavaScript, HTML5, CSS3;
- Git

**Desejáveis:**
- NodeJS
- RESTFul Apis
- React, AngularJS
- Testes (Unitários, Snapshot, integração...)

**Diferenciais:**
- Amazon AWS
- Docker
- CI / CD
- Functional Programming
- Conhecimentos de UI/UX
- Conhecimentos de alguma linguagem de back-end (NodeJS, Java, Python...)

## Contratação

CLT - a combinar

## Nossa empresa

B2W INOVAÇÃO E TECNOLOGIA

Somos o BIT, a área de tecnologia e serviços digitais da B2W e desenvolvemos os sites da maior empresa de e-commerce da América Latina, além das plataformas Marketplace e Mobile.

## Como se candidatar

Por favor envie um email para leonardo.maia@b2wdigital.com.br ou jeferson.leao@b2wdigital.com seu CV anexado - enviar no assunto: Vaga FrontEnd Developer

**Comment by leonardodavila** [comment]
@eduardojmatos @LFeh  poderiam colocar labels de Junior, Pleno, Senior e Alocado?
Valeu 😄

**Comment by kscastro** [comment]
Enviado 👍

**Comment by danilosilvadev** [comment]
@leonardodavila faz entrevista via skype ou online?

**Comment by leonardodavila** [comment]
Fazemos sim!

**Comment by HaluDeCassia** [comment]
@leonardodavila não há nenhuma possibilidade de trabalho remoto?

**Comment by leonardodavila** [comment]
Infelizmente não @HaluDeCassia

**Comment by joordas** [comment]
Ainda está aberta? De qualquer forma, enviado!

**Comment by MathMesquita** [comment]
Up avisando que ainda está aberta... Venham fazer parte do nosso time ! :D

**Comment by leonardodavila** [comment]
Up

**Comment by MathMesquita** [comment]
Ainda tem vaga

**Comment by leonardodavila** [comment]
Temos muitas vagas abertas ainda galera!!!
Só vem!

**Comment by mariojvr** [comment]
Mandei!

**Comment by eduardomr** [comment]
Enviado!

**Comment by thiagocruzrj** [comment]
Curriculum enviado !

**Comment by re-andrade1987** [comment]
As vagas ainda estão abertas ?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
