### ISSUE TITLE
[REMOTO]  Front-end Developer na Digi

### ISSUE THREAD

**Issue by logeraldi** [frontendbr/vagas#6860]
Vaga – Desenvolvedor Fullstack node Js - Pleno
A Digi é uma das principais e mais relevantes fornecedoras de marketing de incentivo do País. Oferecemos plataformas tecnológicas e consultoria estratégica para campanhas de Loyalty e Incentivo. Nossos clientes são as maiores multinacionais do planeta e oferecem desafio de alto nível para grandes talentos.

Estamos recrutando um Desenvolvedor Fullstack em nível pleno para desenvolver aplicações com qualidade e no prazo estipulado, trazendo sempre soluções inovadoras e diferenciadas que elevem cada vez mais o nível das entregas da Digi.
⭐ Esperamos que você:
- Seja comprometimento(a);
- Curioso(a) ao aprendizado contínuo;
- Gostar de ser desafiado(a);
- Seja automotivado(a) e inteligência emocional;
- Tenha uma ótima comunicação e facilidade para negociação.

💼 Como será sua rotina?

- Atuará com o desenvolvimento ou manutenção, de funcionalidades em softwares relacionados ao seu SQUAD;
- Deve seguir padrões de desenvolvimento previamente definidos pela liderança técnica bem como auxiliar na disseminação desses padrões para outros membros do SQUAD;
- Produzir testes unitários para validação das suas implementações;
- Influenciar nas definições de arquitetura de software para melhor design da solução;
- Acompanhar e auxiliar membros iniciantes do SQUAD;
- Participar das cerimônias de planejamento e organização do seu SQUAD;
- Identificar atividades a serem desempenhadas baseado na leitura de História de usuários;
- Auxiliar na escrita de História de usuários;
- Identificar oportunidades de melhoria da experiência dos usuários dos sistemas.

🎓Venha preparado:

- Ensino superior cursando/completo em análises de sistemas ou áreas relacionadas;
- Conhecimentos em Orientação a Objetos;
- Conhecimento de Design Patterns Gof;
- Desenvolver sistemas seguindo preceitos de Arquitetura e Códigos Limpos;
- Ter experiência em algumas das linguagens de programação, como: Javascript, Typescript;
- Ter proficiência em desenvolvimento de software tanto em backend, quanto em frontend;
- Ter algum conhecimento em ferramentas de mensageira;
- Ter algum conhecimento em algumas das plataformas de Cloud a seguir: Azure, AWS, Google Cloud;
- Experiência de trabalho em times ágeis usando os frameworks Scrum ou Kanban;
- Experiência gestão de código fonte utilizando GIT.
Benefícios:

✔️Auxílio Bem-estar Zenklub (Aqui valorizamos o cuidado com você)
✔️Day Off aniversário (bora comemorar?)
✔️Auxílio Home Office (R$ 200,00 mensais)
✔️Auxílio Capacitação Revelo Up (R$ 600,00 anual)
✔️Clube Digi (Plataforma de descontos em farmácias, supermercados e lojas) 
✔️Recesso Remunerado (30 dias)
✔️Licença Maternidade  
✔️Licença Paternidade 
 
Regime: PJ
Local: 🌍Aqui você trabalha onde quiser, nossa cultura é Remoto First :-) 
Interessados enviar CV para: lorraine@grupodigi.com.br

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
