### ISSUE TITLE
[Lisboa ou Full-Remote] Angular Developer na Bee Engineering 

### ISSUE THREAD

**Issue by DS-BEE-PT** [frontendbr/vagas#6861]
==================================================
**Angular Developer – Bee Engineering** 
==================================================
-->
## BEE ENGINEERING (PORTUGAL)

//Hive motto 
if (motivation.status() == false) {motivation.start(); me.beeAwesome(motivation);} 

Somos uma consultora de tecnologias de informação que apoia, todos os dias, os seus clientes e parceiros a chegar mais longe, em projetos de outsourcing, projetos fechados, serviço gerido, experiências gamificadas e nearshore. A BeeTeam é uma equipa diversa de cerca de 200 profissionais que se movem como um todo para atingir um propósito: o sucesso.  

**## Local**
Remoto ou Híbrido, [Portugal], [Lisboa]

**## Hive needs:** 

**Obrigatórios:**
- Experiência superior a 3 anos com Angular 2+, TypeScript;
- Experiência profissional comprovada superior a 3 anos em desenvolvimento front-end (HTML, CSS, JavaScript);
- Conhecimentos de metodologias Agile;

**Desejáveis:**
- Formação superior em Engenharia Informática ou similar;
- Conhecimento em desenvolvimento backend (Node.js)
- Experiência de desenvolvimento em cultura devops
- Fluência em Inglês (não mandatário).

**## Hive Life** 

Global Mindset | integração numa empresa internacional de rápido crescimento; 
Continuous Learning | plano de formação e certificação gratuitas em tecnologias, metodologias, línguas e soft-skills; 
Infinite Feedback | acompanhamento e progressão de carreira; 
Healthy Hive | Seguro de saúde, dentário e seguro de vida; 
Partnerships| benefícios e descontos em restaurantes, ginásios, viagens, farmácias e muito mais; 
One to one | valorizamos a comunicação aberta entre todos; 
Celebrations| celebramos juntos perto ou longe; 
Special Days| dias especiais festejados em conjunto e com prendas especiais;
Bring a Friend/ Referral Program | programa de referência de colegas e amigos; 
Bee yourserlf, honey| defendemos o equilíbrio entre trabalho e vida pessoal; 
Stack| portátil, pacote de dados e kit de boas-vindas.

**Diferenciais:**

- Consultoria especializada no processo de obtenção de visto (Tech Visa). Aplicável para projetos/vagas que exijam mudança para Portugal.

**## Contratação**

PJ se 100% remoto no Brasil
CLT em Portugal

**## Interessado?**

Por favor, envia a tua candidatura com CV atualizado para **dinis.santana@bee-eng.pt** com a referência – BEE.ANGIT.DMS

Estamos à tua espera para iniciar esta viagem. 😄

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
