### ISSUE TITLE
[Remoto] Desenvolvedor FrontEnd Sênior (React.js, JavaScript, TypeScript, CSS3 e Angular) na Turing.com

### ISSUE THREAD

**Issue by leolacoliver** [frontendbr/vagas#6863]
**Candidate-se para esta vaga aqui: http://turing.com/s/792T2Q**

Trabalhe para empresas dos EUA do conforto da sua casa e ganhe em dólar.

Somente candidatos com mais de 3 anos de experiência em desenvolvimento de software serão elegíveis para esta vaga.

Turing.com está procurando contratar um Desenvolvedor FrontEnd Sênior em nome de uma empresa em rápido crescimento, que está ajudando as empresas a crescerem na era digital e orientando-as nesta jornada. O candidato selecionado será encarregado de construir aplicações de alta qualidade, responsivas e com ótimas interações com os usuários. A empresa está formando uma comunidade focada em aplicações de alta tecnologia e desenvolvimento de equipes remotas. Esta é uma excelente oportunidade para os desenvolvedores que gostam de trabalhar em um ambiente ambicioso e dinâmico.
  
Está pronto para se tornar um desenvolvedor remoto Turing em uma grande empresa? Realize nossos incríveis testes de programação.

**Responsabilidades:**
Implementar, diariamente, as funções de especificações comerciais e funcionalidades
Testar o código e garantir que o código da aplicação tenha um alto nível de cobertura para testes
Usar as melhores decisões para a arquitetura do projeto e para melhorar o fluxo de trabalho
Manter a documentação do front-end do projeto de forma consistente
Trabalhar diariamente com membros muito experientes da equipe, no front-end e em outros setores do projeto

**Requerimentos:**
Bacharelado ou Mestrado em Engenharia, Ciência da Computação (ou experiência equivalente)
Pelo menos 3 anos de experiência relevante como desenvolvedor Front-end
Experiência profunda trabalhando com bibliotecas e frameworks JavaScript, incluindo React.js, Vue.js, Ember, e Angular 2+
Experiência com unit tests, como Karma, Jasmine, Jest e testes de ponta a ponta
Bons conhecimentos de JavaScript (ES5/ES6) e serviços REST
Conhecimento de HTML5/JavaScript, TypeScript, CSS3 (CSS variável etc.), e SCSS
Fluência em Inglês

**Como se tornar um desenvolvedor da Turing:**
**Crie sua conta no site da Turing aqui http://turing.com/s/792T2Q**
Preencha suas informações básicas (nome, número, localização, último salário, experiência, etc.)
Passe no teste de múltipla escolha
Agende uma entrevista técnica
Participe do Onboarding final

**Benefícios:**
Receber salários acima da média do mercado brasileiro como PJ ou PF
Trabalhar com uma comunidade de engenheiros do Google, Facebook e Microsoft
Alavancar o desenvolvimento da sua carreira
Nenhuma exigência de visto para trabalhar com as melhores empresas dos EUA
Melhor qualidade de vida e equilíbrio entre trabalho e vida pessoal

Ouça os próprios desenvolvedores. Leia as análises/reviews da Turing.com aqui: https://turing.com/BEpMxr

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
