### ISSUE TITLE
[Remoto] Desenvolvedor FrontEnd (JavaScript, React, e SQL) na Turing.com

### ISSUE THREAD

**Issue by leolacoliver** [frontendbr/vagas#6864]
### Candidate-se aqui:  http://turing.com/s/792T2Q

Trabalhe para empresas dos EUA do conforto da sua casa e ganhe em dólar.

Somente candidatos com mais de 3 anos de experiência em desenvolvimento de software serão considerados para essa vaga.

A Turing.com está procurando contratar um Desenvolvedor FrontEnd em nome de uma agência de marketing digital em rápido crescimento, especializada na geração de leads online para varejistas e construtores manufaturados. O candidato selecionado será responsável pela construção de uma nova versão do produto existente da empresa. A empresa está oferecendo ferramentas eficientes para ajudar os clientes a descobrir e comprar casas recém-fabricadas, fabricadas de forma modular. Esta é uma excelente oportunidade para os desenvolvedores mostrarem suas habilidades e ganharem alguma experiência prática com os profissionais da indústria.

Está pronto para se tornar um desenvolvedor remoto Turing em uma grande empresa? Realize nossos incríveis testes de programação.

**Responsabilidades:**
Usar JavaScript/React para reconstruir um produto CRM/ERP existente, bem como uma nova versão das ferramentas de construção do site
Trabalhar de forma colaborativa para substituir o sistema OpsWorks
Manter o controle do processo de revisão e apresentação do código
Rever os requisitos e as diretrizes pedidas pelo Gerente de Engenharia de Software
Fornecer orientação especializada e/ou recomendações sobre como atender aos requisitos do projeto e do software
Escrever um código limpo, seguindo as melhores práticas da indústria para garantir a funcionalidade do recurso/solução/produto final
Rever o código antes de submetê-lo para o lançamento final, respeitar as sessões de sprint e permanecer dentro do cronograma autorizado
Comunicar à equipe, através dos canais relevantes, sobre problemas relevantes e compartilhar informações conforme necessário
Colaborar com a equipe de desenvolvimento em um ambiente realmente Agile
Usar uma abordagem holística e orientada a testes para solucionar problemas e atualizar a aplicação

**Requerimentos:**
Bacharelado ou Mestrado em Engenharia ou Ciência da Computação (ou experiência equivalente)
Pelo menos 3 anos de experiência relevante como desenvolvedor de software
Conhecimento sobre JavaScript/Reagir
Sólida experiência em operações de banco de dados relacionais SQL em escala, incluindo otimizações de consultas diretas, mecanismos de cache, clustering de leitura/escrita, etc.
Ótimas habilidades de comunicação - tanto escrita como verbal
Capacidade de compartilhar atualizações conforme solicitado e obter esclarecimentos sobre suas dúvidas, em vez de fazer suposições

**Como se tornar um desenvolvedor da Turing:**
Crie sua conta no site da Turing aqui  http://turing.com/s/792T2Q
Preencha suas informações básicas (nome, número, localização, último salário, experiência, etc.)
Passe no teste de múltipla escolha
Agende uma entrevista técnica
Participe do Onboarding final

**Benefícios:**
Receber salários acima da média do mercado brasileiro
Trabalhar com uma comunidade de engenheiros do Google, Facebook e Microsoft
Alavancar o desenvolvimento da sua carreira
Nenhuma exigência de visto para trabalhar com as melhores empresas dos EUA
Melhor qualidade de vida e equilíbrio entre trabalho e vida pessoal

Ouça os próprios desenvolvedores. Leia as análises/reviews da Turing.com aqui: https://turing.com/BEpMxr

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
