### ISSUE TITLE
[Remoto] Desenvolvedor Frontend (Angular, TypeScript, CSS e HTML) na Turing.com

### ISSUE THREAD

**Issue by leolacoliver** [frontendbr/vagas#6865]
### Candidate-se para essa vaga: http://turing.com/s/792T2Q

Trabalhe para empresas dos EUA do conforto da sua casa e ganhe em dólar.

Somente candidatos com mais de 3 anos de experiência em desenvolvimento de software serão considerados para essa vaga.

A Turing.com está procurando contratar um Desenvolvedor Frontend em nome de uma empresa, em rápido crescimento, que está determinada a revolucionar o setor educacional ao oferecer uma plataforma de aprendizado colaborativo em tempo real. O candidato será responsável por regular, melhorar e lidar com o processo de front-end para garantir que as funcionalidades de interação em tempo real sejam rápidas e responsivas em uma ampla variedade de dispositivos. A empresa possibilita uma suave criação colaborativa, automação, compartilhamento e remixagem de conteúdo instrucional com foco em assuntos técnicos. Essa função requer alguma sobreposição com o fuso horário PST.

Está pronto para se tornar um desenvolvedor remoto Turing em uma grande empresa? Realize nossos incríveis testes de programação.
          
**Responsabilidades:**
Arquitetar, implementar e manter recursos do front-end da aplicação web baseada em Angular 
Gerenciar o editor de conteúdo de aprendizado colaborativo e o IDE baseado em navegador em tempo real
Converter wireframes e documentos de design em recursos web de front-end totalmente funcionais
Gerenciar, monitorar e otimizar o desempenho do front-end para garantir que as funcionalidades de interação em tempo real sejam rápidas e tenham bom desempenho em uma ampla variedade de dispositivos
Aumentar seu conhecimento e stack de tecnologias para atender melhor à base de usuários

**Requerimentos:**
Bacharelado ou Mestrado em Engenharia ou Ciência da Computação (ou experiência equivalente)
Pelo menos 3 anos de experiência relevante como desenvolvedor front-end
Deve ter experiência em Angular, TypeScript, CSS e HTML
Necessário experiência com frameworks web front-end
Desejável experiência com Angular 2+
É recomendável ter familiaridade com todo o stack web, incluindo protocolos e segurança de rede
Será vantajoso ter experiência de trabalho com equipes de desenvolvimento em um enxuto ambiente Agile

**Como se tornar um desenvolvedor da Turing:**
Crie sua conta no site da Turing aqui: http://turing.com/s/792T2Q
Preencha suas informações básicas (nome, número, localização, último salário, experiência, etc.)
Passe no teste de múltipla escolha
Agende uma entrevista técnica
Participe do Onboarding final

**Benefícios:**
Receber salários acima da média do mercado brasileiro
Trabalhar com uma comunidade de engenheiros do Google, Facebook e Microsoft
Alavancar o desenvolvimento da sua carreira
Nenhuma exigência de visto para trabalhar com as melhores empresas dos EUA
Melhor qualidade de vida e equilíbrio entre trabalho e vida pessoal

Ouça os próprios desenvolvedores. Leia as análises/reviews da Turing.com aqui:  https://turing.com/BEpMxr

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
