### ISSUE TITLE
[São Paulo] Front-end Developer na Ewally

### ISSUE THREAD

**Issue by kevenjesus** [frontendbr/vagas#687]
## Descrição da vaga

Ewally está procurando um dev front-end Junior ou Pleno para integrar o time de mais 5 desenvolvedores. O projeto é full Javascript, excelente oportunidade de aprendizado.

## Local

Presencial: Av.Angelica, 2529 (proximo metro paulista)

## Benefícios

- Vale transporte
- Vale Refeição

#### Diferenciais

- Chopp no local
- Empresa descontraida
- Vale transporte
- Vale Refeição (R$ 20/dia)

## Requisitos

**Obrigatórios:**

- HTML/CSS (Design responsivo, Flexbox, organização)
- Javascript/ES6
- Mundo node (mongo, express, template engine)
- Terminal e Git

**Desejáveis:**
- React/Redux
- Typescript

**Diferenciais:**
- projetos opensource

## Contratação

Junior CLT R$ 3.500 ou R$ 4.500 PJ
Pleno CLT R$ 4.500 ou R$ 5.500 PJ

## Nossa empresa

Ewally startup fintech de conta digital, uma das 10 empresas selecionadas entre 550 startups para participar do INOVABRA (2016). Programa de inovação aberto, operado pelo Bradesco.

## Como se candidatar

Enviar github, linkedin, cv tudo para o email falecom@keven.com.br

**Comment by HaluDeCassia** [comment]
Boa noite, nehuma chance de full remoto?

**Comment by kevenjesus** [comment]
Opa Helio, infelizmente não.

**Comment by EdipoNascimento** [comment]
Alguma chance para algúem tentando migrar de Q.A?

**Comment by HenriqueSilverio** [comment]
@kevenjesus A vaga ainda está aberta? Não moro na capital atualmente. A entrevista e/ou teste poderiam ser feitos online? Obrigado.

**Comment by LFeh** [comment]
Aberto ainda?
