### ISSUE TITLE
[REMOTO] Desenvolvedor Júnior na Codex Utilities

### ISSUE THREAD

**Issue by luanasantosog** [frontendbr/vagas#6871]
## Nossa empresa

Somos uma empresa do Grupo Imagem, com foco em desenvolvimentos especializados que combinam sistemas de informação, consultoria setorial, especialistas em tecnologia e melhores práticas de gestão para apoiar nossos clientes de forma integrada, atendendo aos mais diversificados processos de negócios.

## Descrição da vaga

Apoiar na análise, desenvolvimento, manutenção, implantação, sustentação e documentação de software.

## Local

Remoto.

## Requisitos

**Habilidades Necessárias:**
- Conhecimento em uma linguagem de programação;
- Vontade de aprender novas tecnologias.

**Diferenciais:**
- Conhecimento em duas ou mais das seguintes tecnologias: Kotlin, Java, Android, React, TypeScript e SQL;
- Experiência com GIT.

## Contratação

A combinar

## Como se candidatar

Se interessou? Cadastre-se em: https://jobs.kenoby.com/codex-utilities/job/analista-desenvolvedor-junior-codex-utilities/625fe7eb304c7630968e3e2b?utm_source=website

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Júnior

**Comment by lucasmfg7** [comment]
Opa, me candidatei.

**Comment by DanielHott** [comment]
Me candidatei!

**Comment by Sr-Igor** [comment]
👍🏽

**Comment by LeoScripts** [comment]
👍🏽

**Comment by LeoScripts** [comment]
👍🏽

**Comment by wladimirbatista** [comment]
Vou me candidatar. Top!

Em qua., 4 de mai. de 2022 às 14:13, luanasantosog ***@***.***>
escreveu:

**Comment by rafhaelgomes-dev** [comment]
Estou me candidatando a vaga!

**Comment by mgmenezes** [comment]
Me candidatei para a vaga! :+1:

**Comment by DanielKitanaxiFilipe** [comment]
Enviado

**Comment by Diomar** [comment]
Interessante! estou participando

**Comment by HUDEVBR** [comment]
Me candidatei

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
