### ISSUE TITLE
[REMOTO] Estágio na Codex Utilities

### ISSUE THREAD

**Issue by luanasantosog** [frontendbr/vagas#6872]
> Vaga Remota durante a pandemia

## Nossa empresa

Somos uma empresa do Grupo Imagem, com foco em desenvolvimentos especializados que combinam sistemas de informação, consultoria setorial, especialistas em tecnologia e melhores práticas de gestão para apoiar nossos clientes de forma integrada, atendendo aos mais diversificados processos de negócios.

## Descrição da vaga

Estágio na Área de Arquitetura de Soluções e Suporte Comercial.

## Local

Remoto.

## Requisitos

**Quais as habilidades e conhecimentos você precisa ter para fazer parte da nossa empresa?:**
- Graduando em Curso Superior de Tecnologia da Informação (3º ano em diante);
- Capacidade de redigir material técnico em apoio a propostas técnicas e apresentações técnicas;
- Capacidade em preparar ambientes de demonstração de produtos, carga e alterações de massas de dados e outras configurações para apresentações técnicas de produtos;
- Capacidade em realizar documentações de provas de conceito;
- Interesse em apoiar a realização de provas de conceito a partir de tarefas de desenvolvimento de software e testes de soluções.

**Responsabilidades:**
- Atuar junto ao time de Arquitetura de Soluções;
- Interagir com os times de produtos para montagem de ambientes de demonstração;
- Apoiar o time de Desenvolvedores de Negócio;
- Interagir com time de Marketing Técnico;
- Contribuir com a elaboração de documentos técnicos, incluindo propostas e apresentações;
- Montar ambientes de demonstração;
- Participar da elaboração de provas de conceito, incluindo testes e preparação de massa de dados.

## Contratação

Estágio

## Como se candidatar

Se interessou? Cadastre-se em: https://jobs.kenoby.com/codex-utilities/job/estagiario-nivel-superior-codex-utilities/626beb6f73fc1858a1629a14?utm_source=website

#### Alocação
- Remoto

#### Regime
- Estágio

#### Nível
- Júnior

**Comment by aramisSilva** [comment]
Enviado!

**Comment by DanielKitanaxiFilipe** [comment]
enviado

**Comment by eduardosimass** [comment]
Enviado

**Comment by arthursj** [comment]
Enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
