### ISSUE TITLE
[Remote - International company] Technical Lead Front End @ Be IT Overseas

### ISSUE THREAD

**Issue by Camismor** [frontendbr/vagas#6873]
## Job Summary

You will be the one setting the vision for the project. It will be you will make sure that it is successfully delivered while at the same time you will be taking responsibility for creating a future-proofed project architecture. Your team and clients will need to know they can rely on you. You will also have an active role in supporting the team in building maintainable, efficient code.

Your mission on the team will also consist of working closely with innovative thinkers with experience on worldwide projects and guide them so that you ensure the best possible quality, performance, and responsiveness of applications is achieved. Your proactivity and strategic thinking will be a must at all times.

You will work with innovative thinkers with experience on worldwide projects and guide them so that you ensure the best possible quality, performance, and responsiveness of applications is achieved.

Your strategic approach towards planning is a must, and we will much appreciate your proactive approach for the project’s technical improvement.

## Local

Remote, company HQ in Europe

## Benefits

•	Working from home
•	Flexible working hours
•	Referral Bonuses
•	Certifications & access to e-learning platforms

## Requirements

**Mandatory:**
•	You possess the ability to write and maintain understandable technical documentation
•	Proficient understanding of code versioning tools (GIT)
•	Proficient in TypeScript, JavaScript including DOM and JavaScript object model
•	Excellent knowledge of the React framework, its core principles, and advanced concepts
•	Capability to understand and use RxJs frameworks
•	Capability to understand, recognize and properly implement software design principles and patterns
•	Experience in using state management libraries
•	Experience in design and implementing UI/UX
•	Knowledge of the build & release deployment process
•	Strong knowledge in dev testing processes
•	Experience with Agile/Scrum development methodologies
•	Strong knowledge and understanding of the Software development lifecycle process
•	Analytical, problem-solving, and decision-making skills
•	Strong desire to stay on top of the latest developments in web technologies
•	Fluent in written and spoken English

**Desirable:**
•	Experience with using cloud service providers
•	Native or hybrid mobile development skills
•	Consistency in the application of standards and processes

## Hiring

PJ

## Our Client

Founded in 2005, is an international software tech company, specializing in purpose and process-driven teams for high-performance, innovation, transformation, and efficiency. 

## How to apply

Send an email to camilla.moriya@beit.work with your resume - subject: Technical Lead Front End

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👴 Sênior
- ⚖️ PJ
- 💰 15k+

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
