### ISSUE TITLE
[Netherlands] Reactjs Developer @ Be IT Overseas

### ISSUE THREAD

**Issue by Camismor** [frontendbr/vagas#6874]
## Job Description
For this position, we are looking for a Senior developer who will move to the Netherlands to work on client-side projects.
Relocation is required and will be arranged by Software House. 
Visa and work permit will be sponsored for applicants.

## Workplace
Netherlands – hybrid model

## Requiriment

**Mandatory:**
- Experience with ReactJs
- Angular, Vue, Javascript, Typescript, HTML(5), CSS(3), Ionic
- Architecture: MVVM and MVC
- bootstrap
- firebase
- SOAP - APIs
- AWS, Azure or GCP – Certification will be a differentiator
- Messaging: RabbitMQ, AmazonSQS
- Database: NoSQL, Redis, Elasticsearch, PostgreSQL, MySQL, MariaDB, MongoDB, DynamoDB, OracleDB
- DevOps notions

## Hiring
PJ 

## Our client
Dutch Softhouse, which serves a wide range of customers from different sectors. Looking for professionals to work allocated on projects in the Netherlands.

## How to apply
Send your resume to camilla.moriya@beit.work. Subject: Reactjs Netherlands

## Labels
- 🏢 Presencial
- 👴 Sênior
- ⚖️ PJ
- 💰 3k-4k euros

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
