### ISSUE TITLE
[Stockholm, Sweden] Front-end Developer @ Be IT Overseas

### ISSUE THREAD

**Issue by Camismor** [frontendbr/vagas#6875]
## Job Description
We are looking for professionals who have mobility and wants to live in Europe (Sweden). Which why it’s important to:
- Completed higher education
- Minimum advanced English
- European citizenship or valid European visa

## Workplace
Stockholm, Sweden

## Requiriments

- Experience in HTML5, CSS 3 e JavaScript
- Specialist in some of the structures JavaScript: AngularJS, React, Vue.js, Node.js
- Experience in JavaScript Testing Framework: Jasmine, Mocha
- Design Patterns in JavaScript
- GitLab

## Hiring
PJ

## About our client
A Consulting firm that come from two countries: Sweden and Argentina. With the union of these two cultures, they work with a great diversity of professionals at European countries.

## How to Apply
Send an email to camilla.moriya@beit.work with your resume. Subject: Front-End Sweden

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
