### ISSUE TITLE
[100% Remoto] Front-end Developer na Broadfactor

### ISSUE THREAD

**Issue by SuianeHenrichs** [frontendbr/vagas#6882]
## Nossa empresa

Aqui na Broadfactor, somos uma Startup Fintech, pioneira em uma plataforma 100% digital e de multicompradores para o ramo de antecipação de recebíveis.

## Descrição da vaga

Desenvolvedor Front-End Pleno

## Local

100% Remoto

## Requisitos

**Obrigatórios:**
- Angular 9;
- JavaScript;
- HTML;

**Diferenciais:**
- Conhecimento em outros Frameworks JavaScript
- Conhecimento em prototipação de tela de design;
- Desejável noção de UX;
- Trabalhamos também usando GitHub;
- CSS.

## Benefícios

- Plano de saúde
- Plano Odontológico
- Seguro de vida
- VR ou VT
- Day off no mês

## Contratação

CLT ou Cooperado

## Como se candidatar

Por favor envie um email para suiane.lima@broadfactor.com com seu CV anexado - enviar no assunto: Vaga Front-End 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Nível

- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
