### ISSUE TITLE
[REMOTO] Front-end Developer na Nave.rs

### ISSUE THREAD

**Issue by RenataRamiress** [frontendbr/vagas#6884]
> Vaga Remota 100%

## Nossa empresa

Trabalhar com a [nave.rs](http://nave.rs/) significa que você conhece e colabora com as pessoas que realmente fazem o trabalho. Unimos tecnologia e criatividade para criar soluções digitais efetivas que se tornam memoráveis e impactam positivamente a vida das pessoas.

Nossa missão é ajudar empresas a entender antes de agir, a agir com precisão e a lucrar a partir de mudanças.

Não é somente sobre produtos digitais, é sobre marcar positivamente a vida das pessoas.

O pilar principal da nossa cultura é “pessoas em primeiro lugar”, sendo assim, estamos sempre trabalhando na construção de um ambiente seguro, inclusivo e diverso, onde as pessoas gostem de estar e possam ser a sua melhor versão. Sendo assim, independente do cargo e área, focamos na empatia e no bem estar dos membros do time e dos nossos clientes. Pois só assim conseguiremos transformar ideias em soluções.

Estamos todos os dias construindo a [Nave.rs](http://nave.rs/) que gostaríamos de viver, e sabemos que para isso, precisamos de uma diversidade de pessoas talentosas ajudando nessa construção. Então qualquer pessoa é bem-vinda. 

## Descrição da vaga

Já pensou em trabalhar em um ambiente colaborativo, dinâmico, com muito aprendizado e autonomia? Neste momento estamos buscando uma pessoa com experiência e conhecimento para área de Front-End React.

Como na empresa trabalhamos com a metodologia ágil Scrum, nos temos todas as cerimonias como planning, weekly, daily e retro, sendo assim o seu dia a dia irá basear-se nas cerimonias e nos projetos em que estiver.

## Local

REMOTO

## Requisitos

**Obrigatórios:**

- HTML;
- CSS;
- JavaScript;
- No mínimo 2 anos de experiência na área de front-end;
- Experiência no desenvolvimento de aplicações web utilizando React;
- Experiência com projetos/clientes;
- Conhecimento básico de ferramentas de gestão de tarefas;
- Conhecimento básico-intermediário de editores de texto, necessário para escrever código;
- Conhecimento básico de Git;
- Conhecimento intermediário em lógica de programação.

**Diferenciais:**

- Conhecimento básico de pair programming;
- Senso de gerenciamento de tempo;
- Boa Comunicação.

## Benefícios

- Assistências médica e odontológica;
- Auxilio psicológico;
- Vale Refeição e/ou Vale Alimentação;
- Aulas de inglês;
- Auxilio Educação (acesso a plataformas de cursos)

**Diferenciais:**

- Hierarquia horizontal;

- Horário flexível.

## Contratação

CLT + Benefício 

## Como se candidatar

Inscreva-se através do link: https://nave-team.gupy.io/jobs/1759719 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
