### ISSUE TITLE
[Remoto] Fullstack Developer - Todos os níveis @ TKS

### ISSUE THREAD

**Issue by mhbm** [frontendbr/vagas#6889]
## Nossa empresa

A TKS (https://www.linkedin.com/company/tks-tech-knowledge-support) está em plena expansão e está com novas vagas para fazer parte deste time! Somos uma empresa de inovação, tecnologia e automação com foco em assumir os problemas de nossos clientes, solucioná-los e gerar valor aos processos.

Conheça nossa plataforma líder no mercado da saúde (www.beecare.app)

## Descrição da vaga

Fullstack Developer (Junior, Pleno, Senior) 

O profissional atuará com as seguintes tecnologias:

- PHP
- Banco de Dados
- Conhecimento em MVC
- Webservices
- API
- FrontEnd

## Local

100% Remoto

## Requisitos
Estamos procurando todos os níveis.  Com experiência e sem experiência

## Contratação

PJ

## Como se candidatar

Por favor envie um email para rh@tks-br.com com seu CV anexado - enviar no assunto: Vaga Fullstack Developer - Nível escolhido

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@tks-br.com

## Labels
Remoto, Fullstack, PHP

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by JonathasGit** [comment]
Opa, vaga boa. Mandei e-mail já.

**Comment by MazziTocQ** [comment]
Mesmo com pouco tempo de estudos tenho esperança que um dia minha hora chegará ! Na torcida :root !
