### ISSUE TITLE
[Araraquara/SP] Front-End Developer Pleno na S2IT

### ISSUE THREAD

**Issue by fabriciofmsilva** [frontendbr/vagas#689]
## Descrição da vaga

- Desenvolver código através da documentação dos requisitos
- Entender o problema do cliente e propor soluções
- Ser participativo, dar opinião de forma construtiva
- Participar de reuniões do projeto
- Espirito de melhoria continua (processo, produto, equipe e pessoal)
- Seguir e respeitar o planejamento dos projetos
- Corrigir defeitos
- Executar e automatizar testes (unitários, TDD)
- Estar em sintonia aos interesses dos projetos e empresa
- Seguir e respeitar as políticas e processos da empresa
- Ser um profissional com perfil T (conhecimento profundo em Angular, porém desejável no mínimo abertura para conhecer outras áreas de conhecimento)

## Local

Alocado na empresa, Araraquara/SP

## Benefícios

- Vale Transporte
- Vale Refeição
- Assistência Médica
- Assistência Odontológica 
- Participação de Lucros
- Auxilio Creche 
- Apoio a Certificação

#### Diferenciais

- Flexibilidade de Horário
- Apartamento Funcional 
- Sala de descompressão (jogos e relaxamento)

## Requisitos

**Obrigatórios:**
- HTML5
- JavaScript Avançado
- Angular 2+
- Bootstrap
- CSS3
- Sass
- Escrever testes unitários
- Desenvolvimento Ágil - Scrum, Kanban
- Propor soluções e definições de arquitetura

**Desejáveis:**
- Git
- Build tools (Bower, Gulp, Webpack)
- Material Design
- Experiência com banco de dados
- Experiência com webservices REST/SOAP

**Diferenciais:**
- Conhecimento em outros Frameworks (React, Vue)

## Contratação

CLT a combinar.

## Nossa empresa

**Somos** uma empresa formada por mais de duzentas pessoas inquietas e comprometidas, incessantes na busca pela inovação e tecnologia. 

**Oferecemos** sempre a melhor solução para o seu negócio, por isso buscamos a todo momento melhorar nossos serviços e superar as expectativas dos nossos clientes. 

**Aqui** o "nós" sempre prevalece sobre o "eu", pois somos apaixonados por pessoas, movidos pela tecnologia e inspirados pela inovação. 

Nossa unidade: [Araraquara](https://www.youtube.com/watch?v=o92Biux7FXo&feature=youtu.be).

## Como se candidatar

Por favor envie um email para vagas@s2it.com.br com seu CV anexado, link do LinkedIn e GitHub - enviar no assunto: Vaga Front-end

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by fabriciofmsilva** [comment]
Ainda aberto.

**Comment by henriqueblacklion** [comment]
Meus caros, desculpem a demora em responder, estou aprendendo a usar o Git e não vi as notificações...essa posição já está em processo de fechamento, tenho vagas de Front para SP e algumas outras nesse cliente. Podem me mandar email no Henrique.daniel@blacklionconsulting.com.br
