### ISSUE TITLE
[Remoto] Fullstack (PHP, Vue) Developer @ Onesight

### ISSUE THREAD

**Issue by kamiarc** [frontendbr/vagas#6891]
## Nossa empresa
A Onesight é uma multinacional com foco em desenvolvimento de tecnologias disruptivas e bleeding edge, atuamos com diversos clientes em múltiplos mercados e tecnologias.
No Brasil nossas atividades se concentram em outsourcing, e-commerces e desenvolvimento AD-HOC.

## Descrição da vaga
Vaga para desenvolvedor Fullstack com foco em:
PHP: Symfony
JS: Vue
Deploy/CI/CD: Ansistrano e Jenkins
DB: SQL

## Local
Remoto

## Requisitos

**Obrigatórios:**
- Ao menos 3 anos de experiência como desenvolvedor JS e/ou PHP

**Desejáveis:**
- conhecimentos em Ansistrano
- conhecimentos em Jenkins
- conhecimentos em CI/CD

**Diferenciais:**
- Experiência com Symfony
- Inglês

**Diferenciais:**
- Horário flexível
- Férias flexíveis (acumulo mensal estilo Europeu e utilização livre)

## Contratação
PJ

## Como se candidatar

Envie um email para trampos@onesight.com.br com seu CV anexado - enviar no assunto: PHPVUE - Fullstack
Importante: Enviar: Nível, pretensão salarial e disponibilidade para início.
Enviar também Github/lab com projetos realizados ou links de exemplos caso tenha algum online.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
