### ISSUE TITLE
[Cidade] Front-end Developer na Nexmuv

### ISSUE THREAD

**Issue by thaynateixeiras** [frontendbr/vagas#6892]
## Descrição da vaga

Atuação com projeto da área comercial  de cadastro de pedidos, produtos, ordem de compra de um dos maiores e-commerces da América Latina, 

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Reactjs, Javascript, TypeScript - Experiência com frameworks de UI (bootstrap, material, etc), consumo de APIs,Docker, testes unitários (front-end) GitHub.
- 2 anos de experiência com mongodb e express

**Desejáveis:**
- conhecimentos em Python ou outra tecnologia de back-end 
- experiência em alguma plataforma Cloud (AWS, Google, Azure, etc)

**Diferenciais:**
-Experiência com algum banco relacional [SQL Server, MySQL, PostgreSQL, etc].
Ex
## Contratação

PJ
## Como se candidatar

Por favor envie um email para thayna.silva@nexmuv.com.br com seu CV anexado - enviar no assunto: Vaga ReactJS

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
