### ISSUE TITLE
[Remoto] Fullstack Developer ( Node/ React)  Pleno @Meta

### ISSUE THREAD

**Issue by techrhrj** [frontendbr/vagas#6893]
> Vaga Remota durante a pandemia

## Nossa empresa

A Meta é uma empresa de tecnologia brasileira com operação no Brasil e no exterior; Está presente em mais de 100 cidades ao redor do mundo; Somos pessoas servindo pessoas!

Nosso propósito: Crescimento humano com tecnologia;

Toda grande empresa é formada por grandes mentes. Nosso time é diverso e composto por talentos múltiplos, que agregam à área de tecnologia e a tantas outras!

Te convido a fazer parte do nosso MetaTeam!

## Descrição da vaga

Oportunidade de alocação em nosso cliente que é uma multinacional brasileira que atua no setor de alimentos; Atuação em Squad de desenvolvimento do CoE de Chatbots;

## Local

100% Remoto

## Requisitos

**Obrigatórios:**
- Experiência como Desenvolvedor Fullstack ( node/ react) de no mínimo 2 anos.
- Experiência com MongoDB

## Benefícios

- Plano de saúde
- Plano Odontológico
- PLR
- Seguro de vida
- VA/VR
- Ajuda de Custo
- Parceria Alura
- Parceria Vittude
- Plataforma Microsoft Learn para certificações/cursos
- English Club
- Meta Academy

## Contratação

CLT + benefícios Meta

## Como se candidatar

Por favor envie um email para thais.franco@meta.com.br com seu CV anexado

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
