### ISSUE TITLE
[REMOTO] Desenvolvedor(a) Frontend Júnior Vue.js @ Instruct Soluções em Tecnologia

### ISSUE THREAD

**Issue by Elisa2207** [frontendbr/vagas#6895]
> 

## Instruct Soluções em Tecnologia 

Aqui na Instruct nossos times são multidisciplinares e valorizamos a troca de experiência dos colaboradores entre as diversas áreas. Sabemos que os resultados dependem do trabalho em equipe!

Prezamos por um ambiente amigável, inclusivo e seguro e estamos sempre abertos e dispostos a contribuir com a comunidade.

Acreditamos na cultura blameless como forma de melhoria constante dos nossos processos, identificando rapidamente as falhas para corrigi-las, sem deixar de lado as responsabilidades inerentes de cada função.

Compartilhamos as informações e o conhecimento diariamente e acima de tudo, valorizamos a transparência, respeito e honestidade nos relacionamentos. Mesmo de longe!

Sim! Somos 100% remotos! Mas estamos juntos todos os dias.

Venha provar um café de qualidade! Quer saber como? Então participe da nossa equipe!

## O que esperamos de você?

- Esperamos que você tenha bons conhecimentos em desenvolvimento web, criando interfaces, implementando frontend e integrando com backend.
- Sua maior responsabilidade será atuar com interfaces desde o desenho, passando pela implementação do HTML, CSS, JavaScript com Vue.js e integrações com backend.
- Queremos que você aplique seus conhecimentos a cada nova tarefa e reconheça áreas que não tem entendimento para resolver um problema buscando ajuda do time.
- Queremos que você participe de planejamentos e estime o tempo de suas atividades, compartilhando responsabilidades, acertos e aprendizados.

## Conhecimentos e experiências fundamentais

- De 1 a 3 anos de experiência em desenvolvimento frontend.
- Vue.js.
- JavaScript, HTML semântico e CSS.
- Fundamentos de UX e UI.
- Conceitos de integração de interface via APIs REST ou GraphQL.
- Uso de Git para versionamento de seu código.

## Conhecimentos diferenciais

- Docker.
- Figma.
- Jest e Cypress.
- NuxtJS.
- Noções de acessibilidade.

## Sobre a vaga

- Regime de contratação CLT.
- Salário inicial entre R$ 4.000,00 e R$ 6.000,00.
- Horário comercial: das 9h às 18h (40h semanais).
- 100% home office, com viagens ocasionais custeadas pela empresa. Portanto, é fundamental ter disponibilidade para viajar.
- Política flexível para lidar com feriados locais estaduais e municipais de cada colaborador.

## Benefícios

- Vale refeição de R$ 400,00 no cartão Caju.
- Vale alimentação de R$ 700,00 no cartão Caju.
- Ajuda de custo para home office de R$ 250,00.
- Auxílio creche para filhos com idade entre 0 a 5 anos.
- Verbas para investimento em treinamentos e educação.
- Prêmio quando se completa aniversário de empresa.
- Participação nos lucros e resultados.
- Instruct Summit: viagem para encontro presencial do time em algum lugar do Brasil custeada pela empresa.
- Day-off pelo dia do aniversário.
- Plano de saúde e odontológico SulAmérica para o titular e seus dependentes 100% custeado pela empresa e sem coparticipação.
- Seguro de vida corporativo custeado pela empresa.
- Kit boas-vindas com headset JBL Quantum 100 e outros mimos.
- A empresa fornecerá um notebook com as seguintes configurações: Dell Vostro 14 5402 (Core i7-1165G7, RAM 16GB, GeForce MX330, SSD 256GB, Full HD).

## Como se candidatar

Para se candidatar acesse o link: https://instruct.com.br/trabalhe-com-a-gente/vagas/desenvolvedor-frontend-junior/

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior

**Comment by JesseSousa** [comment]
@Elisa2207, não consigo enviar pelo site. Posso enviar por algum email?

**Comment by Elisa2207** [comment]
> @Elisa2207, não consigo enviar pelo site. Posso enviar por algum email?

@JesseSousa Sua inscrição no processo seletivo foi efetivado! =D

**Comment by Elisa2207** [comment]
Retornaremos com a abertura para novas inscrições a partir do dia 01/06.
