### ISSUE TITLE
[Florianópolis/SC] Estágio em desenvolvimento web

### ISSUE THREAD

**Issue by ConsultoriaContato** [frontendbr/vagas#69]
## Descrição da vaga

Atividades: desenvolvimento de sites. 

## Local

Rua Olinda Celestina Lacerda, 170 - Carianos, Florianópolis/SC - Brasil
- Atuação em home office, mas necessário residir na cidade.

## Benefícios

- Vale cultura (R$50,00)

## Requisitos

- Inglês técnico. 
- Conhecimento Básico HTML, CSS, JAVASCRIPT e JQUERY, SQL/Banco de dados (MYSQL). 
- Conhecimentos Intermediários/Avançados em PHP; 
- Conhecimento desejável: Estrutura MVC (Zend Framework); WordPress ou equivalente. 

## Contratação

Estágio.
Bolsa: R$800 (6h/dia)

## Nossa empresa

Empresa CHAG: Somos Especialistas em Sites, consultores em Marketing Digital, Profissionais em E-commerce e Assessores em Ensino a Distância, agimos como Anjos da Guarda dos negócios na internet. Estamos focados na educação continuadas para as pessoas e seus negócios, com o desenvolvimento de soluções digitais em plataforma amigável e intuitiva, que facilitam a adaptação das rotinas operacionais do comerciante e melhora sua adesão às novas tecnologias.

## Como se candidatar

Por favor envie um email para recrutamento@consultoriacontato.com com seu CV anexado - enviar no assunto: Vaga estágio em desenvolvimento. Ou se inscreva na vaga em nosso site: http://www.consultoriacontato.com clicando em 'vagas'.

**Comment by eduardojmatos** [comment]
@ConsultoriaContato  já preencheu a vaga? Nos avise pra mantermos ou removermos da lista :)

**Comment by ConsultoriaContato** [comment]
Sim, a vaga já foi preenchida

**Comment by eduardojmatos** [comment]
@ConsultoriaContato blz!

**Comment by camilatigre** [comment]
@ConsultoriaContato 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
