### ISSUE TITLE
[São Paulo] Front End Developer na BRQ

### ISSUE THREAD

**Issue by ReAnne123** [frontendbr/vagas#690]
Grande instituição financeira busca profissional com boa experiência em programação Front End ( HTML5, CSS3, JavaScript,Angular (desejável angular 2 ou superior), Integração de UI Angular com API Rest. Importante também ter tido contato com Java (JPA, EJB, Jboss, Spring). 
Contratação CLT, salário a combinar mais atrativo pacote de benefícios. 
Horário comercial. 
Local: Itaim Bibi- Zona sul de SP.

Por favor envie um email para ryokota@brq.com com seu CV anexado - enviar no assunto: Vaga Angular.

**Comment by LFeh** [comment]
Aberto ainda?
