### ISSUE TITLE
[Todas Estados/Brasil] Front-End Angular PLENO na NTT DATA p/ Serviços Bancários

### ISSUE THREAD

**Issue by msrmarcio** [frontendbr/vagas#6903]
## NTT DATA - Nossa empresa

A NTT DATA é a sexta maior provedora de serviços de TI do mundo. A empresa com sede em Tóquio, conta com 140 mil profissionais e opera em mais de 50 países. 
Na NTT DATA ajudamos nossos clientes em seu desenvolvimento digital com uma ampla gama de serviços de consultoria e assessoria estratégica e Advisoring, tecnologias de ponta, aplicações, infraestrutura, modernização de serviços de TI e BPOs. Contamos com uma sólida experiência em todos os setores da economia e um grande conhecimento das regiões em que atuamos.
Trabalhamos para construir uma comunidade de pessoas única e aberta, liderada por valores compartilhados, que se transformou em uma grande rede de talento coletivo responsável por multiplicar nossas habilidades e conhecimentos, para responder com agilidade às necessidades em constante mudança de nossos clientes e antecipar o futuro com inteligência. 

Saiba Mais sobre nós: https://br.nttdata.com/

## Descrição da vaga

Projetos focados para mercado Financeiro/Bancário

**Frontend Angular 7+ / nível PLENO**

- Experiência mínima de 2 anos como desenvolvedor Frontend Angular 7 ou 8+
- Imprescindível:                                    
> Javascript, 
> HTML, 
> TypeScript, 
> CSS, 
> Angular 7, 8+, 
> Saber Criar componentes em Angular, 
> Módulos, 
> Injeção de Dependência

- Desejável (não obrigatório):            
- Boas práticas de UX, Noções de C# e SQL Server (Microsoft), Selenium

- Conhecimentos:                                  
> SPA, , 
> HTTP, 
> REST FULL, 
> Metodologia Ágil, 
> Web API

Habilidades:
•	Rest e Restful APIs
•	SOAP
•	JSON
•	HTML 5
•	CSS 3
•	JQuery
•	Angular 7 ou 8+

- Perfil:                                                    
>  Boa comunicação verbal e escrita, pró-ativo, trabalho com autonomia e perfil colaborativo.

Responsabilidades:
•	Evolução de funcionalidades já existente;
•	Desenvolvimento de novas funcionalidades;
•	Realizar a correção de bugs detectados;
•	Apoiar a evolução dos programadores Junior;
•	Apoiar a implantação e execução dos processos de software definidos;

## Local

REMOTO [HomeOffice] - [Estados do Brasil]

## Requisitos

**Obrigatórios:**
- a partir de 2 anos de experiência com Angular 7 ou +
- 2 anos de experiência com SQL/Sql Server

**Desejáveis:**
- conhecimentos em Javascript
- conhecimentos em C# (não atuará com C#)

**Diferenciais:**
- projetos opensource
- Criação de Componentes
- Uso do Angular Material
- Técnicas de UX

## Benefícios (Todos Benefícios serão apresentados no primeiro contato conosco)

- Plano de saúde
- Seguro de vida
- VR de R$ X/dia a negociar
- VA de R$ xx a negociar
- Auxílio creche (dentro das politicas)
- Portal de Benefícios exclusivos como Academia, aplicativos de transportes entre outros)

**Diferenciais:**
- 1 horas de almoço
- Auxilio Home Office (dentro da politica) 
- Férias Flexíveis + Beneficio

## Contratação

CLT

## Como se candidatar

Por favor CV pelo E-Mail:  msantrod@emeal.nttdata.com

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: msantrod@emeal.nttdata.com

#### Alocação 
- Remoto

#### Regime
- CLT 

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
