### ISSUE TITLE
[São Paulo] Front-end Developer na Mazzatech

### ISSUE THREAD

**Issue by CRISCAMPOSC** [frontendbr/vagas#6904]
> Vaga 100% Remota 

## Descrição da vaga

Profissional com sólidos conhecimentos em desenvolvimento de sistemas utilizando javascript, Node, React (react hooks, React router)
Experiência em testes  unitários e de UI utilizando  testing library - react e jest
Dominio do Git

## Local
Remoto

**Obrigatórios:**
- 2 anos de experiência como Front end
- Experiência com javascript; node

## Benefícios

- Contratação PJ 
- ...

**Diferenciais:**
- ter boa capacidade de comunicação;
- possuir espírito colaborativo;
- ser bastante flexível às mudanças e alterações nos projetos;
- Resiliência 
- ...

## Contratação

PJ 

## Como se candidatar

Por favor envie um email para email crislene.campos@mazza.tech com seu CV anexado - enviar no assunto: Vaga  Front-end Developer na Mazzatech

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível

- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
