### ISSUE TITLE
[REMOTO] Front-end Developer kotlin na Edesoft

### ISSUE THREAD

**Issue by carolinepistore** [frontendbr/vagas#6909]
<!-- 
==================================================

!!! Temos 4 regrinhas básicas: https://git.io/JG3Z9 !!!

Não faça distinção de gênero no título da vaga.

Use: "Front-End Developer" ao invés de 
"Desenvolvedor Front-End" \o/

Exemplo: `[São Paulo] Front-End Developer KOTLIN na EDESOFT

==================================================
100% HOME OFFICE
==================================================

## Descrição da vaga

Principais atividades: Desenvolvimento (App e smartwatch), preferencialmente em Kotlin. 

  Requisitos Necessários: Conhecimento em : Kotlin ou Java, Estúdio Android , Padrões de Design (MVVM, MVP), GIT, API, Jetpack (Navegação e Livedata), Injeção de dependência com Koin, conhecimento em sistemas de versionamento de código  

## Local

Exemplo: HOME OFFICE

**Diferenciais:**
- Experiência com metodologia ágil (Scrum e Kanban), Conhecimento em APIs do Google (Google Maps SDK, Firebase

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para caroline.pistore@edesoft.com.br  com seu CV anexado - enviar no assunto: Vaga KOTLIN

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
