### ISSUE TITLE
[Joinville-SC] Front-End Developer na iTFLEX Tecnologia

### ISSUE THREAD

**Issue by rudineirk** [frontendbr/vagas#691]
# Front-End Developer na iTFLEX Tecnologia

Esta é uma oportunidade para uma vaga de desenvolvedor Frontend, que irá atuar na especificação, design e desenvolvimento de uma interface de administração e geração de relatórios de servidores linux de telefonia IP, firewall e email.

Trabalho presencial em Joinville / SC

Empresa com 13 anos de mercado, contato com novas tecnologias, oferece possibilidade de crescimento profissional.

Localizada em Joinville, a maior cidade de Santa Catarina (500 mil habitantes), próximo a diversas praias (até 100Km), e também a capital Florianópolis (180Km) e a capital do Paraná, Curitiba (130Km).

A empresa trabalha com as seguintes tecnologias:

* HTML/CSS
* Javascript ES6+
* Babel
* Webpack
* Vue
* Material Design
* Arquitetura SPA (Single Page Application)
* JWT
* APIs REST

## Benefícios

* Benefícios CLT + Plano de Saúde + Ticket Refeição + Auxílio Faculdade / Pós Graduação
* Sala de descompressão com vídeo game
* Bons equipamentos para trabalho, uso de dois monitores.
* Máquina de café expresso
* Participação em congressos
* Livros e ebooks para estudo
* Utlização da metologia Scrum

## Perfil

* Gostar muito desenvolvimento de software e tecnologia
* Ser participativo na construção do produto, contribuindo com ideias para o negócio
* Ter facilidade de trabalhar dentro de times multi-disciplinares
* Ter iniciativa para estudos
* Acompanhar tendências e inovações que surgem no mercado
* Escrever código limpo e legível
* Ter profunda preocupação com qualidade e performance
* Compreender a importância e praticar versionamento de código

## Requisitos

* Curso superior em andamento ou concluído em Sistemas de Informação, Ciências da Computação ou Engenharia da computação
* Ter experiência com programação em Javascript (VanillaJS)
* Domínio em html5 e css3
* Experiência em sites responsivos
* Entender o funcionamento do protocolo HTTP
* Desenvolvimento de aplicações javascript consultando APIs REST

## Diferenciais

* Conhecimentos de UX
* Conhecimentos de Web Design (utilizando Material Design)
* Conhecimento de ferramentas de criação de protótipos
* Conhecimento de ferramentas de edição de imagens
* Experiência com frameworks SPA (single page applications)
* Já ter utilizado/esteja utilizando o framework VueJS
* Experiência em utilização do Git
* Experiência com metodologias ágeis
* Conhecimento de ferramentas de TDD de javascript (Jasmine, Mocha, etc)
* Conhecimento das novas funcionalidades das versões mais atuais do javascript (ES6+)
* Experiência com async/await em javascript
* Usar/conhecer Linux

Tratamos todas as nossas aplicações como sistemas de missão crítica.
Usamos software livre na grande maioria das aplicações e ferramentas por trás da aplicação.

## Contratação

CLT a combinar

## Como se candidatar

Mais detalhes em https://www.itflex.com.br/vaga/desenvolvedor-front-end/

**Comment by rudineirk** [comment]
A vaga é para Júnior ou Pleno, CLT e Alocado

**Comment by HaluDeCassia** [comment]
@rudineirk sem nenhuma chance de remoto?

**Comment by johanguse** [comment]
Já fechou essa vaga! @LFeh @rudineirk 
Obs. Que bom ver empresas trabalhando com VUE em Jlle. :)

**Comment by danilosilvadev** [comment]
@rudineirk faz entrevista via skype?
