### ISSUE TITLE
[Remoto] React Developer Pleno na @Meta

### ISSUE THREAD

**Issue by techrhrj** [frontendbr/vagas#6912]
## Nossa empresa

Confie em quem entende de tecnologia e venha com a Meta!

## Descrição da vaga

Atuará no desenvolvimento de plataforma de um grande banco!
Conheça nosso site: https://www.meta.com.br/

## Local

Remoto 

## Requisitos

**Obrigatórios:**
• Experiência em React.js / Next.js;
• Experiência em metodologias ágeis
• Conhecimento dos serviços em nuvem da AWS;

## Benefícios

- Plano de saúde
- Plano Odontológico
- PLR
- Ajuda de Custo
- Parceria com a Alura
- Parceria com a Vittude
- Seguro de vida
- VA/VR
- Meta Academy
- Acesso a Plataforma Microsoft para certificações

## Contratação

CLT + benefícios

## Como se candidatar

Por favor envie um email para thais.franco@meta.com.br com seu CV anexado

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
