### ISSUE TITLE
[Remoto] Front-end Developer na Celerative 🇺🇸

### ISSUE THREAD

**Issue by maplessmann** [frontendbr/vagas#6913]
## About Celerative

Celerative helps you get customized remote job opportunities. We’re not just another freelance hiring platform.
We help you work on projects you want and get paid what you deserve. No matter where you live.

- We'll connect you to a global network of experts to meet, organize events and share experiences.
- A personal success manager will be assigned to you for mentorship and career advice.
- Get full visibility on your payments and collect them in the payment method of your choice.

## About The Role

> 💵  &thinsp; This is a 100% remote, full-time, long-term position, with monthly payments in USD

We are looking for a UI Developer who is expected to combine the art of design with the art of programming. Responsibilities will include translation of the UI/UX design wireframes and prototypes to actual code that will produce visual elements of the application. You will work with the UI/UX designer and bridge the gap between graphical design and technical implementation, taking an active role on both sides and defining how the application looks as well as how it interacts with users. 

## Responsibilities
- Develop new user-facing UI features
- Build reusable code and libraries for future use Participate in building Design Systems for our products Maintain existing UI components
- Ensure the technical feasibility of UI/UX designs Collaborate with Designers and Stakeholders 

## Skills
- Proficient understanding of web markup, including HTML5, CSS3
- Solid understanding of Visual TDD methodology and experience with Storybook
- Solid understanding of CSS pre-processing tools, such as SASS
- Experience with at least one of the following frameworks: React, Angular
- Proficient understanding of cross-browser compatibility issues and ways to work around them Proficient understanding of code versioning tools, such as Git
- Good understanding of SEO principles and ensuring that application will adhere to them Experience in implementing unit tests

## How To Apply

Apply exclusively through the Celerative platform at the following link: 👉 &thinsp; [Create your profile at Celerative](https://www.celerative.com/referral/dc2f087b-8d04-4900-9398-8c4b334bcee5).

After creating your account via the above link, you will receive an email with the next steps. If you do not see the email in a few minutes, check your Spam folder.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
