### ISSUE TITLE
🇵🇹[Lisboa/Portugal] Front-end Developer na Eye Candy Solutions🇵🇹

### ISSUE THREAD

**Issue by Rezende-Rita** [frontendbr/vagas#6914]
🎯 Oportunidade Desenvolvedor Front-end Pleno e Sênior
 
Estamos à procura de um desenvolvedor front-end que possa colocar a cereja no topo do bolo. Alguém com um forte senso visual e estético, que entende o impacto de seu trabalho na experiência dos usuários. Procuramos um desenvolvedor com uma mentalidade de resolução de problemas e a capacidade de ver o quadro geral, mas também de se concentrar nos detalhes. O candidato ideal deve ser metódico, responsável e capaz de trabalhar em equipe multidisciplinar.
 
Responsabilidades:
📍 Desenvolver funcionalidades focadas no usuário;
📍 Desenvolver código e bibliotecas reutilizáveis para o futuro;
📍 Otimize aplicativos para velocidade e escalabilidade máximas;
📍 Garantir padrões de qualidade no desenvolvimento de código;
📍 Colaborar com outras equipes de desenvolvimento e partes interessadas;
📍 Garantir a viabilidade técnica dos projetos de UX/UI.
 
Requisitos:
✔️ Experiência mínima de 3 anos em desenvolvimento front-end (JavaScript e/ou Typescript);
✔️ Conhecimento de frameworks (Vue ou Angular) e bibliotecas (React ou JQuery);
✔️ Sólidos conhecimentos de OOP e padrões de arquitetura;
✔️ Experiência em desenvolvimento HTML considerando as diretrizes de acessibilidade ARIA;
✔️ Experiência em CSS e AJAX;
✔️ Experiência em Git ou outras ferramentas de controle de versão;
✔️ Conhecimento de metodologias ágeis (Scrum);
✔️ Conhecimento das melhores práticas de CI/CD;
✔️ Conhecimento de ferramentas e metodologias de UX;
✔️ Inglês Avançado para conversação
Modelo de Contratação: Recibo Verde

Link para cadastro: https://jobs.quickin.io/eyecandy/jobs/625aba0cb3102a001517e112

Qualquer dificuldade no cadastro enviar seu cv para rita.rezende@eye-candy.pt

Obrigada!

Rita Rezende
Eye Candy Solutions

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
