### ISSUE TITLE
[Remote] React Developer na International opportunity

### ISSUE THREAD

**Issue by TacianySouza** [frontendbr/vagas#6918]
**Requisitos técnicos - Obrigatório.**
● +4 anos de experiência com React. JS.
● Inglês fluente.
● Disponibilidade para participar de reuniões em oportunidades pela manhã mas no horário de Londres.

**Sobre responsabilidades:**
Estamos à procura de um engenheiro talentoso que queira levar suas habilidades para o próximo nível, juntando-se a uma pequena equipe que entrega produtos de alto desempenho em um ambiente ágil.
Escolha, possua e implante novos recursos do zero na Web e em aplicativos nativos com o react native
Revise as relações públicas e nos ajude a melhorar a maneira como trabalhamos
Investigue e resolva novos desafios e responda a erros.
Escreva código de alta qualidade e bem testado.

**Desejável:**
● Experiência com React native.

**Sobre a empresa:**
Cliente que desenvolveu uma plataforma online onde as escolas têm acesso a centenas de perfis de professores e funcionários de apoio totalmente avaliados, que podem reservar com o clique de um botão. Pense Uber para professores. Fundada em 2016 em Londres, é uma empresa de Educação de Pessoal e EdTech.

Candidatura: https://forms.gle/i2DXYEQXcACo4CFm6

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
