### ISSUE TITLE
[Remoto] Frontend React Developer na Agenda Edu

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6919]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedora-front-end-205129150?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Em 2022, nossa missão de simplificar as jornada educacionais está ainda mais desafiadora! Procuramos pessoas que amam aprender e ensinar, que tenham vontade de transformar a relação entre escolas e famílias e, claro, que amem educação!</p>
<p>Estamos crescendo sempre e precisamos de pessoas com propósito, brilho nos olhos e muita mão na massa para transformar a Agenda Edu em uma referência como hub de soluções educacionais da América Latina. Vem ser #AgendaLover e fazer parte do nosso time! 😍</p>
<p><strong>RESPONSABILIDADES E ATRIBUIÇÕES:</strong></p>
<ul>
<li>Escrever códigos bem dimensionados, testáveis e eficientes;</li>
<li>Garantir que os projetos estejam em conformidade com as especificações;</li>
<li>Preparar e produzir versões de componentes de software;</li>
<li>Apoiar a melhoria contínua, investigando alternativas e tecnologias e apresentando-as para revisão arquitetural;</li>
<li>Trabalhar com controle de qualidade para testes, acompanhamento para resolver problemas e publicar material acabado do sistema de gerenciamento de conteúdo.</li>
</ul>

## Agenda Edu: 
 <p>A Agenda Edu nasceu em 2014 no Startup Weekend em Fortaleza - CE, com o intuito de engajar os responsáveis na rotina escolar dos alunos. Nosso propósito é Simplificar Jornadas Educacionais. A empresa Agenda Edu hoje tem dois produtos, a própria Agenda Edu (comunicação e engajamento) e o EduPay (pagamentos). </p><p>Temos no nosso hall mais de 3 mil clientes atendidos (escolas) e mais de 2 milhões de usuários.</p><a href='https://coodesh.com/empresas/agenda-edu'>Veja mais no site</a>

 ## Habilidades: 
 - React.js 
- Angular.js 
- CSS 
- HTML
## Local: 
 100% Remoto
## Requisitos: 
 - Orientação a objetos; 
- Conhecimento em banco de dados relacional; 
- AngularJS; 
- React; 
- CSS; 
- Html; 
- Sass; 
- CI/CD; 
- Frameworks de testes unitários.

## Benefícios: 
 - Plano de Saúde e Odontológico 100% custeado pela empresa para o colaborador 
- Day offs sem descontar das férias 
- Vale Refeição (Cartão de Benefícios Flexíveis - CAJU) 
- Auxílio Home Office (Cartão de Benefícios Flexíveis - CAJU)
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend React Developer na Agenda Edu](https://coodesh.com/vagas/desenvolvedora-front-end-205129150?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
