### ISSUE TITLE
[São Paulo] Front-End Developer na CRITICAL MASS

### ISSUE THREAD

**Issue by Luciananadal** [frontendbr/vagas#692]
**Vaga Líder de Desenvolvimento Full Stack - JS / React / React Native / Redux / GraphQL**

**A CRITICAL MASS:**
Somos uma agência canadense há 21 anos focada em UX. Desde então fizemos o e-commerce da Nike, da Mercedes-Benz e, no ano passado, o e-commerce global da Adidas -- além de nos tornarmos agência digital da Apple, com um time dedicado em Cupertino.
Há 2 anos chegamos no Brasil, atuamos como uma startup. Criamos e desenvolvemos 3 apps de comunicação corporativa proprietários que revolucionam a forma como as empresas se comunicam com seus empregados, de forma horizontal e participativa. Temos como clientes a PepsiCo, Unilever, Zurich Santander, TV Record, Som Livre, entre outros. 
Veja mais em: http://www.criticalmass.com
 
**A VAGA:**
Você é apaixonado por experiência do usuário, interface e desenvolvimento de produtos digitais? 
Como desenvolvedor  ou desenvolvedor líder da equipe de front-end da Critical Mass você será responsável pela arquitetura front-end dos projetos e irá protagonizar o desenvolvimento contínuo dos nossos produtos.

As vagas são para trabalho remoto, full time, em modelo PJ, desenvolvendo nossas plataformas white label (SaaS). Procuramos desenvolvedores com perfil inovador, preocupados com a experiência do usuário.

Nosso stack é JS, React, React Native, Redux, GraphQL. (No back temos Node e Rails)
 
Experiência Imprescindível: Git, 5+ anos de desenvolvimento front-end, 1+ anos de desenvolvimento de apps e/ou react;
Experiência desejada: TDD, XP, code review, metodologia agile.
Diferencial: experiência com desenvolvendo de apps white label complexos.
 
Diferenciais: RoR, DevOps (AWS, Dockers, Dokku, Kubernetes, Heroku, Nginx tuning)

**## Como se candidatar**

Por favor envie um email para jobs@criticalmass.com.br com seu CV anexado.

**Comment by Luciananadal** [comment]
As vagas são para trabalho remoto ;)

**Comment by ygorlazaro** [comment]
@Luciananadal oi! Vocês trabalham com PJ também?

**Comment by guilherme90** [comment]
@ygorlazaro 
As vagas são para trabalho remoto, full time, `em modelo PJ` =)

**Comment by guilherme90** [comment]
@ygorlazaro 

As vagas são para trabalho remoto, full time, `em modelo PJ`

**Comment by paulitolinhares** [comment]
Enviado! o/

**Comment by meiraleal** [comment]
Ainda aberto pra aplicações?

**Comment by LFeh** [comment]
Aberto ainda?
