### ISSUE TITLE
[Remote] Front-end Developer na Runrun.it

### ISSUE THREAD

**Issue by assinirecruiter** [frontendbr/vagas#6920]
## Nossa empresa

O Runrun.it é uma plataforma de gestão do trabalho. Um software moderno, em nuvem,

vendido no Brasil e internacionalmente. Estamos em busca de uma pessoa para a posição

de Front-end Developer, o trabalho é 100% remoto #workfromanywhere.

Todes são bem-vindes! 🏳️‍🌈

## Descrição da vaga

Utilizamos Scrum, Github, CI/CD e as telas são especificadas no Figma

pelo nosso time de UX. Você mergulhará em uma jornada ao lado do time de UX e Tecnologia, visando a experiência funcional para os usuários e irá nos ajudar na  identificação e solução de problemas estruturais no código do produto.

 

[Veja o que já fizemos](https://www.google.com/url?q=https%3A%2F%2Frunrun.it%2Fapi%2Fdocumentation&sa=D&sntz=1&usg=AOvVaw1Wk_LUGr04T-12vz6CSFsI)[ - 🔍](https://www.google.com/url?q=https%3A%2F%2Frunrun.it%2Fapi%2Fdocumentation&sa=D&sntz=1&usg=AOvVaw1Wk_LUGr04T-12vz6CSFsI)

Fará parte do seu dia:
Participar na melhoria do workflow de desenvolvimento;

Se preocupar com monitoramento de métricas: técnicas e de negócio;

Desenvolver pensando em qualidade e performance.

## Local

 Remoto (Brasil)

## Requisitos

**Obrigatórios:**
 
Do que você precisa:
Conhecimento e prática em JavaScript e CSS;

Experiência desenvolvendo aplicações web com React.js;

**Desejáveis:**
- conhecimentos em ruby on rails

## Benefícios

Oferecemos pacote atrativo de: 
 
Oportunidade 100% Home Office e CLT💻 🏡
Alimentação e Refeição no cartão Caju 🛒🛍️ 
Plano de Saúde e Odontológico Bradesco ❤️‍🩹 
 Subsídio à educação 📚👨‍🎓
Auxílio à saúde emocional ❤️‍🧠
DayOff 😎🎂
 
O Trabalho remoto é com dedicação diária de 8 horas úteis de forma síncrona com o restante do time que trabalha no fuso de Brasília.
 

## Contratação

CLT: a partir

## Como se candidatar

Inscrição https://ggle.io/52vk

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: people@runrun.it

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
