### ISSUE TITLE
[Remote] Front-End Developer na Dinheirow

### ISSUE THREAD

**Issue by Davispc10** [frontendbr/vagas#6921]
## Dinheirow

Olá, pessoal!
A Dinheirow (https://dinheirow.com.br/)  está em busca de desenvolvedores VUE.js e NEXT.js que desejam fazer parte do nosso propósito de ajudar pessoas a realizarem seus sonhos por meio de empréstimos com juros baixos e educação financeira.

Para embarcar conosco, há algumas habilidades que valorizamos muito e não estamos falando apenas de tecnologia, nós valorizamos profissionais que respeitem o próximo e suas diferenças, que sejam leais e responsáveis ​​com as entregas e com as pessoas. 

A colaboração e engajamento devem fazer parte do dia a dia para que o resultado seja eficaz e que tenha sede de treinamento para trabalhar com inovação contínua.

## Descrição da vaga

- 100% Remoto
- Nível de experiência: Pleno
- Salarial Inicial: R$ 7000 PJ
- Bônus: 1 salário /anual
- Crescimento salarial posteriormente: de acordo com as entregas, desempenho, e outros aspectos.
- Período: integral

## Requisitos

Pelo menos 3 anos de experiência em:
- Vue / Next;
- Typescript;
- Padrão de Projeto;
- Testes end-to-end (Cypress);
- Princípios SOLID.

Para se diferenciar, seria muito bacana se você tiver:
- O básico de DevOps;
- Arquitetura de Software;
- Saber organizar demandas e delegá-las;
- Conhecimento geral sobre consumo de API (Tolerância à falhas, organização e middlewares);
- Microfrontends.

## O que irá fazer:

- Colaborar com product managers, designers e software engineers para identificar oportunidades e implementar soluções;
- Melhorar o nível técnico dos nossos serviços e sistemas atuais, resolvendo dívidas técnicas, problemas de arquitetura e design dos sistemas;
- Se envolver ativamente na construção de funcionalidades do começo ao fim, desde a experimentação, design, implementação e deploy;
- Trabalhar em conjunto com todo o time de tecnologia, revisando o trabalho de outras pessoas, participando de decisões importantes de produto e tecnologia e garantindo a saúde dos nossos serviços.

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para contato@dinheirow.com.br com seu CV anexado, github e linkedin - enviar no assunto: Vaga FrontEnd Pleno

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Vue
- Next
- Javascript

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
