### ISSUE TITLE
[Remoto] Fullstack Java Developer  (Sênior) na Tatic

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6923]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/java-developer-140054755?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A Tatic está buscando uma pessoa <strong><ins>Fullstack Developer Java</ins></strong> para agregar ao time!&nbsp;</p>
<p><strong>Conheça a Tatic:</strong></p>
<p>Com mais de 15 anos de experiência, a Tatic é uma empresa inovadora de tecnologia da informação. Nossos serviços e soluções irão modernizar sua arquitetura de dados e impulsionar a adoção da inteligência artificial na tomada de decisões de negócios: uma verdadeira parceria estratégica para o sucesso.</p>
<p>Os produtos e serviços Tatic atendem às necessidades de tratamento e armazenamento de grandes volumes de dados, potencializando os BSS (Business Support Systems) e a aplicação de Machine Learning, Analytics avançado e muito mais para seu negócio.</p>
<p>Hoje, grandes corporações em nível global já se beneficiam da nossa expertise para otimizar investimentos, reduzir custos operacionais, reter e fidelizar clientes e aumentar receita. Afinal, a eficiência em dados transforma resultados.</p>
<p><strong>#VemPraTatic</strong></p>

## Tatic: 
 <p>Com mais de 15 anos de experiência, a Tatic é uma empresa inovadora de tecnologia da informação. Nossos serviços e soluções irão modernizar sua arquitetura de dados e impulsionar a adoção da inteligência artificial na tomada de decisões de negócios: uma verdadeira parceria estratégica para o sucesso.</p>

<p>Os produtos e serviços Tatic atendem às necessidades de tratamento e armazenamento de grandes volumes de dados (big data e analytics). E hoje, grandes corporações em nível global já se beneficiam da nossa expertise para otimizar investimentos, reduzir custos operacionais, reter e fidelizar clientes e aumentar receita.</p><a href='https://coodesh.com/empresas/tatic'>Veja mais no site</a>

 ## Habilidades: 
 - Java 
- Spring Boot 
- RESTful 
- SQL 
- JUnit 
- Docker 
- Kubernetes
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência com projetos Java (Spring Boot e Spring Cloud) 
- Experiência com frontend 
- Experiência com base de dados Postgres 
- Conhecimento de padrões de microserviços 
- Desejável conhecimento em Docker 
- Desejável conhecimento em Kubernetes
## Diferenciais: 
 - Experiência com desenvolvimento de sistemas distribuídos 
- Conhecimento em GWT
## Benefícios: 
 - 100% Remoto; 
- Horários Flexíveis; 
- Day Off no dia do seu aniversário; 
- Ambiente criativo e inovador; 
- Feedbacks constantes; 
- Sem DressCode; 
- 30 dias de férias remuneradas;  
- Licença Maternidade; 
- Licença Paternidade.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack Java Developer  (Sênior) na Tatic](https://coodesh.com/vagas/java-developer-140054755?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
