### ISSUE TITLE
[Remoto] Frontend Vue.js Engineer na Pilar

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6928]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-vuejs-engineer-194512557?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>A Pilar</strong> busca pessoa <strong>Frontend Vue.Js</strong> para compor seu time!</p>
<p>Trabalhar com o comércio de imóveis não é para qualquer um. Muito além da capacidade de vender, é preciso desenvolver um perfil consultivo: conhecer o mercado, ter uma rede de contatos segura, entender as necessidades de cada cliente, acompanhar leads, sempre saber como anda a realidade do cenário imobiliário e econômico.&nbsp;</p>
<p>Esse é o olhar que somente quem é corretor pode ter - e ele exige muito tempo e dedicação. O problema é que, hoje, quem busca crescimento nesse mercado precisa lidar com diversas tarefas, responsabilidades e gastos operacionais que não são propriamente da sua área. Com tantas demandas do marketing, jurídico e contratos, quase não sobra tempo para investir no mais importante: a especialidade do corretor.&nbsp;</p>
<p>É por isso que a Pilar existe.</p>
<p><strong>Responsabilidade: </strong></p>
<ul>
<li>Planejar, desenvolver e documentar sistemas escritos em Vue.js.</li>
</ul>
<p></p>

## Pilar: 
 <p><span style="font-size: 16px;"><strong>Estrutura para crescer, propriedade para vender.</strong></span></p>
<p><strong>Trabalhar com o comércio de imóveis</strong> não é para qualquer um. Muito além da capacidade de vender, é preciso desenvolver um perfil consultivo: conhecer o mercado, ter uma rede de contatos segura, entender as necessidades de cada cliente, acompanhar leads, sempre saber como anda a realidade do cenário imobiliário e econômico. Esse é o olhar que somente <strong>quem é corretor pode ter</strong> - e ele exige muito tempo e dedicação.</p><a href='https://coodesh.com/empresas/pilar'>Veja mais no site</a>

 ## Habilidades: 
 - REST APIs 
- GIT 
- Vue.js
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência na atuação profissional em Vue.js 
- Git 
- Protocolo TCP/IP 
-  REST APIs 
- Fundamentos de segurança computacional (gestão de senhas, variáveis de ambiente)
## Diferenciais: 
 - Entendimento de bancos NoSQL 
- Atuação em squads de produtos 
- Github Actions ou GitLab CI
## Benefícios: 
 - Salário competitivo 
- Possibilidade de trabalho remoto 
- Day off mensal
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Vue.js Engineer na Pilar](https://coodesh.com/vagas/frontend-vuejs-engineer-194512557?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
