### ISSUE TITLE
[Remoto] Senior Front-end Developer na Solides

### ISSUE THREAD

**Issue by danielasantosrh** [frontendbr/vagas#6932]
## Sobre a Solides

Somos uma RH Tech que vem crescendo exponencialmente nos últimos 5 anos e recentemente recebemos investimento de R$ 530 milhões. Nossa missão é **transformar as empresas por meio das pessoas**. Oferecemos um ambiente descontraído, diverso, recheado de treinamento e desenvolvimento, profissional e pessoal!

**A Sólides é uma empresa #Anormal** por natureza! Aqui dentro, vemos o trabalho como uma presente, uma benção, e é por isso que somos um time **#CanelaGrossa**. Não existe desafio grande demais que nosso time não encare e coloque a **#MãonaMassa** com toda energia para resolver e superar! Aqui não cansamos de aprender, somos **#Learnaholic** e nosso ano vale por 7, o crescimento e o aprendizado são gigantescos!

## Benefícios e Informações

- Carga horária de 40 horas semanais (segunda a sexta);
- Vale-refeição/alimentação de R$37,00, inclusive nas férias (a gente ama comer \o/);
- Vale-Transporte ou Vale-combustível;
- Plano de Saúde: Unimed;
- Plano Odontológico da OdontoPrev;
- Qualifica e Alura: plataformas cheeeeeias de cursos online dos mais variados temas #Learnaholic;
- Gympass, porque para ser #CanelaGrossa tem que se mexer!!
- Pra cuidar da saúde mental, temos a Mental Clean e a Psicologia Viva - temos duas sessões gratuitas de psicoterapia por mês;]
- Temos várias confraternizações ao longo dos meses (online e presenciais) e nosso horário é flexível!

## E se você se cansar do remoto e estiver por perto, olha só o que temos também...

- Dress Code super flexível; pra gente ir trabalhar de chinelo ;)
- Lanches de manhã e a tarde!
- Banda de Solidianxs, que toca de tudo, a todo momento, em qualquer lugar! #MãonaMassa
- Sinuca porque está no nosso sangue, é tradição, e tradição não pode morrer. Temos campeonatos e uma galera que joga fielmente todo almoço e final de dia;
- Vídeo Game e Fliperama, afinal de contas, somos uma empresa de tecnologia certo?
- Ping-Pong pra quem gosta de jogos mais ágeis e divertidos!
- Adoramos crianças e adoramos mais ainda recebê-las no escritório, e é por sabermos o quão especial é ser mamãe ou papai, que nossas licenças de maternidade e paternidade são estendidas.

## Descrição da vaga

Para essa vaga esperamos que você tenha:

- Domínio amplo em React.js
- Conhecimento de Typescript
- Experiência com Redux (SAGA]
- Vivência com CI/CD (Entrega contínua)
- Conhecimento de boas práticas de qualidade como TDD e DDD
- Experiência em arquitetura front-end
- Conhecimento de devops AWS (kubernetes, docker, cloud front)

## Local

Vaga remota ou híbrida/presencial em BH/MG (o que for melhor para você)

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um e-mail para f.selecaorh@gmail.com com o link do seu LinkedIn ou currículo anexado - enviar no assunto: Vaga React Solides

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.
E-mail para contato em caso de não haver resposta: f.selecaorh@gmail.com

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
