### ISSUE TITLE
[Remote + U$D +CLT ] Jobsity is looking for ReactJS / React +Node / React Leads / Ruby + React !!!👾

### ISSUE THREAD

**Issue by OrianaRodriguez** [frontendbr/vagas#6933]
Heyy everybody, I'm Orii, an IT Sourcer at Jobsity, **an Outsourcing Company from NYC** +50 different industries, some of our best-known clients are NBC, Bloomberg, Hearst, USA Today, McGraw Hill Education, Cargill, among others.

I'm very interested in **profiles for the next roles** 🔥 : ReactJS / React +Node / React Leads / Ruby + React 
(**Must have:** +4YOE, located in LATAM and Great English speaking skills)

  🤸🏽‍♀️**We offer** full-time, long-term, 100% remote and contractor positions with USD payments 
   * Local Holidays and Vacations are off and paid
   * 3 Extra OFF/sick days per year (these are also paid)
   * We have weekends off 
   * 3 weeks of paid vacations (15 working days )🌴 
   * Unlimited PTO hours  (4hours max. per day ) 
   * Financing program for equipment
   * 60 USD budget for e-learning courses every three months, like 
      Udemy, Platzi, Pluralsight, and any other platform that you prefer.
   * + Paid commissions if you refer a friend and gets hired👨‍👩‍👦‍👦

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
