### ISSUE TITLE
[Remoto] Sênior Software Engineer na Hubla

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6935]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/senior-software-engineer-191547145?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>A Hubla </strong>busca pessoa <strong>Sênior Software Engineer</strong> para compor seu time!</p>
<p>A Hubla nasceu para dar liberdade para que pessoas trabalhem fazendo o que amam. Nós oferecemos toda a infraestrutura para que criadores de conteúdo possam monetizar e engajar suas comunidades, liberando tempo para o criador prover o melhor conteúdo e experiências únicas para as suas comunidades.</p>
<p>Em novembro de 2021 a Hubla levantou série A de mais de 10M USD pela Kaszek, o que vem nos ajudando a crescer continuamente. Hoje contamos com milhares de criadores dos mais diversos segmentos - saúde, fitness e bem-estar, finanças, investimentos, gastronomia, música, turismo, entre outros.</p>
<p>Mas queremos ir além, criar o futuro do trabalho.</p>
<p>Estamos buscando uma pessoa para atuar como Sênior Software Engineer (fullstack, backend ou frontend) para desenvolver features end-to-end em um dos Squads da Hubla.</p>
<p><strong>RESPONSABILIDADES</strong></p>
<ul>
<li>Desenvolver funcionalidades no produto da Hubla do início ao fim, incluindo definições de arquitetura, testes e rollout em produção</li>
<li>Desenhar a solução técnica de novas funcionalidades ou sistemas, assim como revisar desenhos de outras pessoas</li>
<li>Revisar o código de colegas.</li>
<li>Manter os sistemas existentes, priorizando demandas de melhorias e bug fixes.</li>
</ul>
<p></p>
<p></p>

## Hubla: 
 <p>A Hubla é uma empresa de tecnologia líder na Passion Economy / Creator Economy no Brasil. <br>Lançada em 2020, permite aos criadores administrar sua própria comunidade paga usando uma plataforma de gerenciamento inteligente e rápida.<br>Estamos transformando talentos em comunidades ao possibilitar que qualquer pessoa crie um negócio online por meio de plataformas de chat em grupos como WhatsApp ou Telegram. <br>Nossa missão é permitir que as pessoas tenham liberdade para trabalhar fazendo o que amam e ganhar a vida compartilhando seus talentos e experiências com o mundo.</p>
</p>

 ## Habilidades: 
 - Node.js 
- Typescript 
- React.js 
- Next.js 
- Flutter
## Local: 
 100% Remoto
## Requisitos: 
 - Sólida experiência profissional com desenvolvimento de software; 
- Ter conhecimento de boas práticas de programação e aplicá-las; 
- Consegue decompor problemas complicados em tarefas pequenas e simples; 
- Sente-se à vontade de pedir ajuda quanto tiver dificuldades; 
- Se comunica claramente, sendo ativo em discursões da direção do Squad; 
- Apesar de ter foco em Backend ou Frontend tem noções de como funciona toda a stack; 
- Entende a necessidade de testes automatizados e é capaz de implementá-los; 
- Entende e navega bem os tradeoff entre velocidade vs qualidade; 
- Inglês Intermediário.
## Diferenciais: 
 - Inglês avançado; 
- Familiaridade com a Stack de software da Hubla.
## Benefícios: 
 - Stock options com alto potencial de valorização; 
- Plano de saúde e odontológico nacional sem co-participação; 
- Seguro de vida e Seguro viagem: incluso no plano de saúde tanto nacional como internacional para colaboradores e seus dependentes 
- Vale refeição e alimentação via cartão Caju; 
- Auxílio home office e/ou vale transporte; 
- Gympass; 
- Aulas de inglês online; 
- Horário de trabalho flexível; 
- Modalidade de trabalho flexível e/ou home office; 
- Um ambiente de trabalho e time únicos, que estão trabalhando com paixão e intensidade para ter os melhores resultados nesse momento de hiper crescimento!
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Sênior Software Engineer na Hubla](https://coodesh.com/vagas/senior-software-engineer-191547145?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
