### ISSUE TITLE
[Remoto] Fullstack Javascript/PHP Developer na Greenn

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6936]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/fullstack-javascriptphp-developer-110522842?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>Greenn</strong> está buscando <strong><ins>Fullstack Javascritp/PHP Developer</ins></strong> para compor seu time!</p>
<p>Somos formados por duas empresas, G Digital e Greenn, em ambas disponibilizamos um software que facilita a gestão de empreendedores que possuem negócios digitais. Temos o privilégio em atender clientes de vários lugares do Mundo!</p>
<p>O que nos move e inspira é estar ao lado de pessoas que buscam crescimento contínuo, que não gostam de fazer a mesma coisa, do mesmo jeito, por muito tempo. Pessoas dispostas em lidar com tarefas mais complexas e que possuem afinidade com tecnologia.</p>
<p><strong>Responsabilidades:</strong></p>
<ul>
<li>Criação, manutenção e atualização de sistemas utilizando Lumen, MySQL, MongoDB, RabbitMQ, Redis  de acordo com as especificações e necessidades de cada projeto,</li>
<li>Criação e manutenção de APIs REST;</li>
<li>Interpretar e reproduzir diagramas;</li>
<li>Versionamento de código com Git;</li>
<li>Criação e execução de teste garantindo a qualidade e performance dos sistemas;</li>
<li>Metodologias Ágeis.</li>
</ul>

## Greenn: 
 <p>Somos formados por duas empresas, <strong>G Digital</strong> e <strong>Greenn</strong>, em ambas disponibilizamos um software que facilita a gestão de empreendedores que possuem negócios digitais. Temos o privilégio em atender clientes de vários lugares do Mundo!</p>
<p>O que nos move e inspira é estar ao lado de pessoas que buscam crescimento contínuo, que não gostam de fazer a mesma coisa, do mesmo jeito, por muito tempo. Pessoas dispostas em lidar com tarefas mais complexas e que possuem afinidade com tecnologia.</p><a href='https://coodesh.com/empresas/greenn'>Veja mais no site</a>

 ## Habilidades: 
 - PHP 
- Laravel 
- MySQL 
- MongoDB 
- RabbitMQ 
- Redis 
- GIT
## Local: 
 100% Remoto
## Requisitos: 
 - Sólidos conhecimentos em PHP com Laravel/Lumen; 
- Ótimos conhecimento em Javascript com Vue.js; 
- MySQL; 
- Versionamento de código GIT; 
- Habituado a trabalhar com metodologia ágil.
## Diferenciais: 
 - WordPress Multisite; 
- Experiência no desenvolvimento de SAAS; 
- Experiência no desenvolvimento com Multitenancy.

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack Javascript/PHP Developer na Greenn](https://coodesh.com/vagas/fullstack-javascriptphp-developer-110522842?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
