### ISSUE TITLE
[São Paulo] Front-end Developer na Carreira Preta

### ISSUE THREAD

**Issue by magalicelso** [frontendbr/vagas#6938]
"Front-End Developer"

Vaga Remota

Nós do Carreira Preta buscamos para nosso cliente Cubos uma Pessoa Desenvolvedora Front-end Pleno

RESPONSABILIDADES E ATRIBUIÇÕES
- Participar ativamente das etapas de ideação, planejamento e desenvolvimento dos produtos dos nossos clientes;
- Participar de discussão das tecnologias que serão utilizadas nos projetos;
- Desenvolvimento de aplicações web responsivas com [React.js](http://react.js/), consumindo web services, baseadas em layouts feitos por nossos designers, visando uma UX de excelência;
- Deploy com continuous integration / continuous deployment;
- Ser curioso e estar disposto a se arriscar em novas tecnologias;
- Disposição para ajudar e compartilhar conhecimento.

## Requisitos

**Obrigatórios:**
- Experiência com React;
- Proficiência em Javascript (ES6+);
- Proficiência em HTML e CSS;
- Conhecimento em Typescript;
- Conhecimento em versionamento com Git;
- Experiência fazendo interfaces de usuário complexas para a Web;

**Desejáveis:**
- conhecimentos em ruby on rails
- conhecimentos em C#

**Diferenciais:**
- Experiência com testes automatizados no frontend;
- Experiência com GraphQL;
- Conhecimento em acessibilidade e SEO;
- Experiência com back-end, Node em especial;
- Apresentação de portfólio, Github ou similares;
- Habilidades em padrões de design de interface e experiência de usuário;
- Conhecimento em pré-processadores de CSS (Sass, Stylus, Less, etc) ou CSS in JS (styled-components, emotion, etc)

## Benefícios
- Vale refeição ou alimentação;
- Plano de saúde Bradesco Saúde;
- Plano odontológico Bradesco Saúde ;
- Vale transporte (Auxílio home office);
- Day off aniversário;
- Licença casamento estendida;
- Licença maternidade estendida;
- Licença paternidade estendida;
- Licença Pet;
- Gympass;
- Aulas semanais multidisciplinares;
- Auxílio compra de livros;
- Auxílio curso de inglês;
- Auxílio bem estar.

## Contratação
CLT ou PJ - a combinar

## Como se candidatar
Por favor envie um email para magali@carreirapreta.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Pleno

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 05 dias após cada processo.
E-mail para contato em caso de não haver resposta: ola@carreirapreta.com.br.

#### Alocação
- Remoto

#### Regime
- CLT/ PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
