### ISSUE TITLE
[100% Remoto] Specialist Software Engineer @Creditas 💚

### ISSUE THREAD

**Issue by creditasvagas** [frontendbr/vagas#6939]
A Creditas é uma plataforma digital focada em melhorar a vida das pessoas na América Latina em 3 ecossistemas: auto, imobiliário e benefícios corporativos.

**Com tecnologia desenvolvida 100% dentro de casa, trabalhamos com todas as linguagens de programação do mercado.** Ideal para quem, assim como a gente, ama se desafiar e se desenvolver na resolução de problemas reais.

**As nossas contratações são CLT e 100% remotas, mas você pode ir a um dos nossos polos quando quiser!**

Para saber mais, clique aqui e se inscreva: https://grnh.se/90fd02252us

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
