### ISSUE TITLE
[São Paulo - SP] Desenvolvedor Front-end na NOALVO

### ISSUE THREAD

**Issue by FelipeMonobe** [frontendbr/vagas#694]
## Sobre a NOALVO
* Somos uma startup de mídia off-line com pouco mais de um ano de vida.
* Fomos acelerados pela ACE, melhor aceleradora de startups da América Latina e já recebemos dois grandes aportes de investimento.
* Temos 10 pessoas no nosso escritório aqui na Av. Paulista, dentro do coworking do ACE Campus, junto a dezenas de outras startups, todos os dias. É um ambiente onde você respira conhecimento e inovação.
* Conheça mais sobre nós no nosso BLOG DE ENGENHARIA em http://engenharia.midianoalvo.com.br
* Conheça mais sobre nossa STACK DE DESENVOLVIMENTO em http://stackshare.io/noalvo/noalvo

## Descrição da vaga
Desenvolvedor front-end com experiência em tecnologias JavaScript para desenvolvimento de plataforma web com AngularJS.

# COMO SE CANDIDATAR
http://bit.ly/noalvo-frontend-developer

## Local
Av. Paulista, São Paulo.

## Conhecimentos obrigatórios
* HTML5, CSS3 e Javascript (ES2015+);
* AngularJS;
* Webpack;
* Git;
* Bootstrap 3;
* LESS;

## Diferenciais competitivos
* Metodologia Scrum;
* Testes unitários;
* Typescript ou Flow;
* Webpack 2+;
* AngularJS 2+ ou VueJS 2;
* UX design;
* Responsividade;
* SEO e semântica de HTML;

## Valores pessoais
Proatividade: querer fazer mais ou melhor, sem esperar ordens;
Franqueza: falar o que pensa, sem puxar saco ou ficar engolindo sapo até desmotivar;
Persistência: nunca dizer que algo é impossível até tentar o máximo de soluções possíveis;
Autodidatismo: não é só ver um videozinho no youtube, é ser apaixonado por conhecimento;
Customer-centric: trabalhar pensando no valor ao usuário final;

## Proposta
PJ (valor a combinar)
Full-time
In-loco

**Comment by danielswater** [comment]
Remoto?

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by ggondim** [comment]
Foi reaberta (outra descrição e link para candidatura) na issue #844
