### ISSUE TITLE
[Remoto] Front-end Developer (Jr.) na ONG Safernet Brasil

### ISSUE THREAD

**Issue by manuhalfeld** [frontendbr/vagas#6941]
## Nossa empresa

A ONG SaferNet Brasil se consolidou como entidade referência nacional no enfrentamento aos crimes e violações aos Direitos Humanos na Internet. Nosso ideal é transformar a Internet em um ambiente ético e responsável, que permita às crianças, jovens e adultos criarem, desenvolverem e ampliarem relações sociais, conhecimentos e exercerem a plena cidadania com segurança e liberdade.

Somos reconhecidos como o Safer Internet Center do Brasil e operamos a Central Nacional de Denúncias de Crimes Cibernéticos (https://denuncie.org.br/), o Canal Nacional de Orientação sobre Segurança na Internet (https://helpline.org.br/) e a promoção de ações de educação em cidadania digital. 

Para cumprir nossa missão, trabalhamos colaborativamente com uma rede de parceiros, colaborando com o poder público, entidades internacionais e com grandes empresas de tecnologia no desenvolvimento de projetos inovadores, criativos e de alto impacto. 

## Descrição da vaga

Para a vaga de Desenvolvedor(a) Web Júnior, buscamos alguém movido à desafios, que se conecte com a nossa visão e esteja disposto(a) a crescer, aprender e se desenvolver dentro de nossa organização. A pessoa selecionada terá a oportunidade de trabalhar em projetos de alto impacto, auxiliando no desenvolvimento de aspectos técnicos, websites e softwares, sempre com foco na missão do desenvolvimento de estratégias tecnológicas que reforcem e apoiem Direitos Humanos na Internet brasileira.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 2 anos de experiência prévia com suporte e/ou desenvolvimento de sistemas web
- Conhecimento sobre sistemas web
- Conhecimento sobre APIs REST
- Habilidades de comunicação e escrita intermediárias ou fluente em Inglês

**Desejáveis:**
- Formação concluída ou em andamento na área de tecnologia (Ciência da Computação, Sistemas de Informação, Redes, etc.) e correlatas
- Experiência prévia com desenvolvimento de APIs REST

**Diferenciais:**
- Interesse e engajamento em comunidades de desenvolvedores

## Benefícios

- CLT

**Diferenciais:**
- Flexibilidade no horário de trabalho
- Oportunidade de trabalhar em projetos de grande impacto na área de Direitos Humanos
- Oportunidade de crescimento e aprendizagem dentro da organização
- Política de progressão de carreira bem definida

## Contratação

CLT, remuneração calculada de acordo com Plano de Cargos e Salários da organização

## Como se candidatar

Candidatos que desejem se candidatar devem responder o formulário: https://forms.gle/uZJ3hwDEEyhLbkGx6 até o dia 27/05/2022.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: manu@safernet.org.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior

**Comment by ViniciusEvans** [comment]
não há link para o formulário

**Comment by Guedesou** [comment]
Apaixonado por este impacto, hein! Acredito que vai dar match! Bora conversar, equipe? Mandando meu CV!

**Comment by manuhalfeld** [comment]
O prazo para a inscrição no Edital da vaga foi encerrado em 27/05/2022.
