### ISSUE TITLE
[REMOTO] Front-end Developer na NAVE.RS

### ISSUE THREAD

**Issue by RenataRamiress** [frontendbr/vagas#6942]
> Vaga Remota 100%

## Nossa empresa

Trabalhar com a [nave.rs](http://nave.rs/) significa que você conhece e colabora com as pessoas que realmente fazem o trabalho. Unimos tecnologia e criatividade para criar soluções digitais efetivas que se tornam memoráveis ​​e impactam positivamente a vida das pessoas.

Nossa missão é ajudar a entender as empresas antes de agir, a agir com precisão e o lucro a partir de mudanças.

Não é somente sobre digital, é sobre marcar positivamente a vida dos produtos.

O pilar principal da nossa cultura é “pessoas em lugar”, sendo assim, estamos sempre trabalhando na construção de um ambiente seguro, inclusivo e diverso, onde as pessoas gostam de estar na versão e podem ser a sua melhor. Sendo assim, independente da carga e área, focamos na empatia e no bem estar dos membros do tempo e dos nossos clientes. Pois só assim conseguimos transformar ideias em soluções.

Estamos todos os dias ajudando a construir uma [Nave](http://nave.rs/) . Então qualquer pessoa é bem-vinda.

## Descrição da vaga

Já pensou em trabalhar em um ambiente colaborativo, conseguiu, com muito aprender e autonomia? Neste momento estamos buscando uma pessoa com experiência e conhecimento para área de Front-End React.

Como na empresa temos dia a dia ágil Scrum, nos temos a empresa dia a dia as cerimonias e nos projetos a cerimonias e nos em que iremos.

## Local

REMOTO

## Requisitos

**Obrigatórios:**

- HTML;
- CSS;
- JavaScript;
- No mínimo 2 anos de experiência na área de front-end;
- Experiência no desenvolvimento de aplicações web usando React;
- Experiência com projetos/clientes;
- Conhecimento básico de ferramentas de gestão de tarefas;
- Conhecimento básico-intermediário de editores de texto, necessário para escrever código;
- Conhecimento básico de Git;
- Conhecimento intermediário em lógica de programação.

Diferenciais:

- Conhecimento básico de programação em pares;
- Senso de gerenciamento de tempo;
- Boa Comunicação.

## Benefícios

- Assistências médicas e odontológicas;
- Auxílio psicológico;
- Vale Refeição e/ou Vale Alimentação;
- Aulas de inglês;
- Auxilio Educação (acesso às plataformas de cursos)

**Diferenciais:**

- Hierarquia horizontal;
- Horário de funcionamento.

## Contratação

CLT + Benefício

## Como se candidatar

Inscreva-se através do link: https://nave-team.gupy.io/jobs/1812285

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.

#### Alocação

- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
