### ISSUE TITLE
[100% Remoto] Senior Angular Developer na Datum

### ISSUE THREAD

**Issue by Jeanice-Grivot** [frontendbr/vagas#6943]
Sua stack é desenvolver **front-end Angular**? A **Datum** quer adicionar você!

Na Nossa Rede Você Encontra

- Pessoas conectadas na vida real;
- Inovação que vai além das telas;
- Um mundo cheio de desafios;
- Ética e transparência nas relações;
- Ambiente ágil, do tipo visualizado e respondido! 😉

**Requisitos Obrigatórios**

Você pode se conectar com a oportunidade se possuir experiência em:

- Angular / TypeScript (mínimo 4 anos)
- Microfront end
- AWS (CloudFront, Lambda, Advanced)
- Inglês Fluente **(posição com reporte internacional)**

E aí, quer participar do nosso time? 
É simples, basta clicar e enviar o seu currículo para jeanice.grivot@datum.inf.br ou me adicionar no [Linkedin](https://www.linkedin.com/in/jeanicegrivot/).

Na Datum #TodosAvançamJuntos 💜

## Contratação

CLT, PJ ou Cooperado

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias úteis após a candidatura.
E-mail para contato em caso de não haver resposta: jeanice.grivot@datum.inf.br

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
