### ISSUE TITLE
[Hibrido / São Paulo, Brazil] Fullstack Developer na Deepservice 

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6944]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-full-stack-203022123?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p></p>
<p>A GYRA+ é uma plataforma de capital de giro que tem como propósito ampliar os limites de cada empreendedor, para que cada vez mais pequenas e médias empresas possam existir e concretizar seus sonhos.&nbsp;</p>
<p>Buscamos por pessoa sênior nas ferramentas e tecnologias empregadas pela GYRA+ e também com experiência em liderar squad.  Senioridade para ser exemplo e referência para o time de desenvolvedores da empresa.</p>
<p><strong>Requisitos:</strong></p>
<ul>
<li>Busca incansável e incessante por novas tecnologias. Contribuir com a inovação constante da empresa.</li>
<li>Perfil inovador, empreendedor e hands on</li>
<li>Visionário;7</li>
<li>Excelente relacionamento interpessoal;</li>
<li>Trabalho em equipe.</li>
</ul>

## Deepservice : 
 <p>A Deepservice está no mercado há mais de 7 anos, entregando resultados em consultoria em diversas organizações e empresas. Atuando de forma contínua, com excelência junto aos clientes e parceiros.</p>
<p>Nossa consultoria é abrangente, oferendo soluções com tecnologia e eficiência, em processos de gestão de pessoas, recrutamento e seleção e demais consultorias na área de pessoal.</p><a href='https://coodesh.com/empresas/deepservice'>Veja mais no site</a>

 ## Habilidades: 
 - React.js 
- Node.js 
- MongoDB 
- GraphQL 
- Google Cloud Platform (GCp) 
- Bitbucket
## Local: 
 São Paulo, Brazil
## Requisitos: 
 - Utilize metodologias ágeis; 
- Ter sólida experiência em desenvolvimento com as ferramentas citadas.
## Diferenciais: 
 - Gestão de pessoas
## Benefícios: 
 - Horários Flexíveis 
- Plano de Saúde (mesmo PJ) 
- Cartão Flex (CLT)
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack Developer na Deepservice ](https://coodesh.com/vagas/desenvolvedor-full-stack-203022123?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
