### ISSUE TITLE
[Curitiba/PR - Remoto] Front-end Developer na @Logcomex

### ISSUE THREAD

**Issue by SilviaPetreca** [frontendbr/vagas#6946]
> Vaga Remota

## Nossa empresa

Somos uma ScaleUp apaixonada por tecnologia, inovação e pessoas!

Desenvolvemos a melhor Inteligência de Dados aplicada ao Comércio Exterior do Brasil e, com isso, impactamos diariamente a vida de várias pessoas de forma direta e indireta, como importadores, exportadores e toda a cadeia do COMEX! 

Nossa cultura focada em automação nos dá a segurança de que enquanto escalamos, mantemos a qualidade de nossos dados e nossos clientes satisfeitos.

Trabalhamos de maneira ágil com soluções em PHP (Laravel / Lumen), Node JS, Python, Vue JS / Nuxt, PostgreSQL, ElasticSearch, Prefect, Looker, AWS, Postgres/ElasticSearch, entre outras. 

Nossos bancos de dados recebem milhões de requisições por segundo, trabalhando com um alto volume de dados e utilizamos Machine Learning para a classificação de milhares de dados por dia enquanto mantemos altíssima disponibilidade.

A LogComex está voando!!! Atualmente, somos mais de 1.000 de clientes, mais de 5.000 usuários ativos em 3 continentes e rumo a 350 loggers!

Acreditamos que a tecnologia é o meio para conectar o mundo. Somos experts naquilo que fazemos e usamos todo o nosso conhecimento com um objetivo único: revolucionar o comércio exterior. E aí, topa revolucionar o comércio exterior com a gente?

## Descrição da vaga

Você irá...

Manter a funcionamento dos sistemas em produção;
Realizar manutenções no sistema conforme solicitação do cliente;
Desenvolvimento com testes unitários;
Ajudar a manter e melhorar nosso design system;
Desenvolver e implementar em Javascript/Typescript e NodeJs;
Utilizar ferramentas como VueJS e NuxtJS;
Desenvolver novos produtos utilizando estrutura de micro serviços;
Desenvolvimento de código com alta disponibilidade;
Utilizar Docker para fazer conteinerização de ambiente de desenvolvimento;
Utilizar o Git para versionamento de código;
Trabalhar com o Jira;
Utilizar metodologias ágeis para apoiar as atividades.

## Local

Remoto

## Requisitos

**Obrigatórios:**
Procuramos pessoas com conhecimento em...

CSS, SCSS, HTML, Javascript e Typescript avançado;
VueJS, ou experiência com demais frameworks de componentes;
Experiência com libs de UI, preferencialmente Vuetify;
Docker e Docker Compose;
Experiência com testes automatizados, preferencialmente Jest;
Conceitos arquiteturais intermediário no mínimo;
Conceitos básicos dos design patterns mais utilizados em frameworks de componentes;
Conceitos básicos de design system;
WebSockets.

**Desejáveis:**
Será legal se você conhecer...

Construção de libs internas;
NuxtJS;
Framework Laravel/Lumen;
Banco de dados Postgres;
[node.js](http://node.js/);
AdonisJS.

## Benefícios

Mobilidade ou Auxílio Home Office R$ 250;
Vale refeição de R$ 30;
Vale Cultura de R$ 50;
Plano de saúde;
Plano odontológico;
Inglês in company;
Seguro de vida;
GymPass;
﻿Keiken (Plataforma de apoio psicológico);
Convênio Farmácia Panvel;
Empréstimo Pessoal Creditas.

**Diferenciais:**
Mimos: (sim, porque somos destes!)
 
Horário semi flexível (para estimular sua qualidade de vida);
Desconto em instituições de ensino;
Frutas para consumo na empresa;
Ambiente descontraído, cheio de desafios e campeonatos de videogame;
Sem dress code: aqui você pode ser você;
Massagem in company;
Day off de aniversário;
Presente de aniversário;
Presentes incríveis a cada ano de Logger;
Recruta Loggers (programa de indicação).

## Contratação

CLT

## Como se candidatar

Por favor envie um email para silvia.petreca@logcomex.com com seu CV anexado e, se possível com pretensão salarial e enviar no assunto: Vaga Front-end Developer ou pode se candidatar no link: https://logcomex.gupy.io/job/eyJqb2JJZCI6MTAzODkzNiwic291cmNlIjoiZ3VweV9wdWJsaWNfcGFnZSJ9?jobBoardSource=gupy_public_page

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
