### ISSUE TITLE
[Fortaleza] Front-End Developer na [LeadMark]

### ISSUE THREAD

**Issue by leadmarkapp** [frontendbr/vagas#6947]
<h1 align="center">
    <img alt="GoStack" src="https://github.com/leadmarkapp/vaga-desenvolvedor-full-stack/blob/main/logo-leadmark-app-512.png?raw=true" width="150px" />
</h1>

<h3 align="center">
  Vaga | Front-end
</h3>

<strong>O que buscamos?</strong>

Buscamos pessoas com grande capacidade criativa e raciocício lógico 🤓, capaz de aceitar desafios e desejam trabalhar em projetos de inovação. 🚀✈️🚀

<strong>Habilidades Técnicas:</strong>

- Conhecimentos sólidos em <strong>Javascript</strong> 👨‍💻
- Conhecimentos sólidos em HTML5 e CSS3
- <strong>React JS</strong>
- <strong>Next Js</strong>
- Implementação sobre WebSocket
- Experiência com comunicação via API REST
- Domínio com Git :octocat:
- jQuery
- WordPress
- Práticas de documentação
- Testes

<strong>Diferenciais:</strong>

- Cases / Aplicações desenvolvidas
- React Native
- Conhecimento de UI e boas noções de UX
- Figma / Ilustrator / Photoshop

<strong>Habilidades Interpessoais:</strong>

- Raciocínio lógico 🤓
- Comunicação 🗣️
- Proatividade ☕☕☕...

<strong>Locação e Contratação:</strong>

- Remoto
- CLT ou PJ (à combinar de acordo com a experiência)

<br>
<br>
<strong>Ficou interessado?</strong><br>
Entre em contato conosco enviando email para:<br>
<strong>leadmarkapp@gmail.com</strong>, cópia para <strong>leandro.mendestavares@gmail.com</strong><br>
<strong>Assunto do email:</strong> Vaga Front-end<br>
<strong>Atenção:</strong> anexar currículo

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
