### ISSUE TITLE
[São José dos Campos /SP ou Remoto] Front-end Developer Pleno na Cuponomia

### ISSUE THREAD

**Issue by rafaelpradella** [frontendbr/vagas#6949]
## Nossa empresa

O Cuponomia é um site totalmente gratuito que oferece desconto através de cupons, cashback e ofertas das principais lojas online nacionais e internacionais. Nós negociamos com os melhores e-commerces e vasculhamos toda a internet para encontrar e oferecer cupons exclusivos, descontos especiais e cashback para nossos usuários.

Fundado em 2012 por Antônio Miranda e Vinicius Dornela, o Cuponomia surgiu com a ideia de ajudar as pessoas a economizar em todas as compras online. Fomos pioneiros na divulgação e popularização dos Cupons de Desconto gratuitos no Brasil e em 2019 passamos a oferecer Cashback para todos os nossos usuários. Seguimos focados em nosso propósito:

>"Nós queremos ajudar todos os consumidores a economizar! O que nos move todos os dias é encontrar as melhores oportunidades para gerar economia de verdade!"

## Descrição da vaga

Buscamos um profissional que irá contribuir para os nossos produtos web entregando protótipos e novas funcionalidades, sempre se preocupando com a qualidade do código, impacto na performance da aplicação e SEO, e ajudar no processo de aprendizado dos profissionais mais iniciantes da equipe, com bons Code Reviews.

#### Responsabilidades e Atribuições
- Desenvolver aplicações web utilizando JavaScript, CSS, HTML e outras tecnologias;
- Analisar, compreender e discutir requisitos técnicos e funcionais;
- Dar assistência a todo o ciclo de vida dos projetos: concepção, design, teste e suporte para recursos novos e existentes;
- Propor novos códigos, componentes e processos para melhorar a prática de desenvolvimento.
- Manipulação do DOM com JS vanilla e com suporte cross-browser;
- Escrever HTML semântico.

## Local

Remoto ou [São José dos Campos / SP - Jardim das Colinas](https://goo.gl/maps/gJ9QL6fmvu9hRhHN6)

## Requisitos

**Obrigatórios:**
- Proficiência em JavaScript (ES6+);
- Boas noções de layout, escrevendo CSS sem utilizar frameworks e design responsivo (Flexbox, CSS Grid);
- Noções de SEO;
- Noções de Google Analytics (ler eventos, estatísticas de uso);
- Familiaridade com frameworks JS modernos (Vue, React, Svelte, Angular etc);
- Conhecimento em técnicas de otimização de performance (lazy-loading, code splitting, otimização de assets, etc).

**Desejáveis:**
- Noções de Google Tag Manager (criar scripts, gerenciar timing e triggers);
- Familiaridade com a nossa stack (.NET MVC, LESS/SASS, Vue 2);

## Benefícios

- Plano de Saúde e Odontológico SulAmérica, sem nenhum desconto ou coparticipação para o titular;
- Zenklub (plataforma de suporte emocional com psicólogos e coaches online);
- Vale refeição de R$30,00/dia no cartão Flash;
- Participação nos Resultados;
- Horário flexível;
- Auxílio creche;
- Auxílio para estudo e desenvolvimento (pós-graduação, MBA, inglês, entre outros);
- Budget para cursos e livros;
- Cashback em dobro;
- Ginástica laboral;
- Convênio com o Sesc;
- Seguro de vida.

**Diferenciais:**
- Cashback no aniversário;
- Prêmio de até R$1.000,00 para indicações assertivas de novos integrantes para o nosso Time;
- No dress code.

## Contratação

CLT/PJ a combinar

## Como se candidatar
Preencha sua candidatura via nossa [vaga no Gupy](https://cuponomia.gupy.io/jobs/1208501)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 semanas nas primeiras etapas.
E-mail para contato em caso de não haver resposta: rh@cuponomia.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
