### ISSUE TITLE
[Brasília] Front-End Design na Capgemini

### ISSUE THREAD

**Issue by JosielLima** [frontendbr/vagas#695]
## Descrição da vaga

A empresa está a procura de desenvolvedores frontend com foco em design para compor nosso time.
Vagas para: junior, pleno e senior

## Requisitos

**Obrigatórios:**

-- Superior completo em TI, Designer Gráfico ou  Publicidade e Propaganda.--

- HTML5, CSS3
- Noções de  Javascript (ES2015+);
- Frameworks CSS (Materialize, Bootstrap 3)
- SASS
- Git
- Noções de UX
- Material Design.

**Desejáveis:**
- Conhecimento em algum Framework JS(Vue, Angular ou React)
- Software de UX (Sketch, Figma ou outro)

## Local

Presencial - Full-time, Brasília

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ X/dia
- Auxílio creche
- ...

## Contratação

CLT

## Como se candidatar

Por favor envie um email para daniela.lima@capgemini.com com seu CV anexado + pretensão salarial - enviar no assunto: Vaga UI

PS: Também estão abertas vagas para UX Design com nível superior completo e experiência.

**Comment by HaluDeCassia** [comment]
Nenhuma chsnce de remoto?

**Comment by danilosilvadev** [comment]
Boa tarde faz entrevista via skype? @JosielLima

**Comment by fejaum** [comment]
Enviado!

**Comment by JosielLima** [comment]
@HaluDeCassia Não é possível. Profissionais alocados no cliente.

@danilosilvadev Não. Mas a decisão é do RH. Tenta a sorte.

**Comment by fjeansilva** [comment]
Olá @JosielLima, as vagas ainda estão abertas?

**Comment by JosielLima** [comment]
@fjeansilva e @leandrofigueiredo infelizmente estou sem essa informação.

**Comment by JosielLima** [comment]
Atualização:
Ainda tem uma vaga aberta.
@fjeansilva e @leandrofigueiredo

**Comment by fjeansilva** [comment]
Obrigado @JosielLima!!

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by leandrofigueiredo** [comment]
@JosielLima opa, muito obrigado!

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
