### ISSUE TITLE
[Remoto] Front-end Developer no DietSystem (JavaScript)

### ISSUE THREAD

**Issue by thiagoferreira123** [frontendbr/vagas#6950]
## Nossa empresa

🍏 Aqui no DietSystem, somos uma micro  startup  que criou um software feito para nutricionistas e estudantes de nutrição. Ainda estamos bem no inicio, validando nossa ideía.

Não sabemos aonde seremos daqui alguns meses, mas termos certeza que seremos gigantes!  🙏🏻

Você quer fazer parte desse sonho, e crescer conosco? 

## Descrição da vaga

**No DietSystem você terá os seguintes desafios:**

- Desenvolver novas features do front da plataforma;
- Desenvolver melhorias nas features existente;

## Local

- 100% Remoto;
- 3-4h diárias;
- Você faz os seus horários.

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento: JS, PHP, HTML e CSS (Sem o uso de frameworks)
- Experiência gerenciando desenvolvimentos no Git;
- Conhecimento em banco de dados não relacional;
- Conhecimento em CRUD com PHP orientado a objetos.

**Desejáveis:**
- Conhecimento sobre Linux;
- Já ter trabalho em softwares web com as mesmas tecnologias;
- Portfólio;
- Certificados.

**Diferenciais:**
- projetos opensource

## Contratação

Freelancer.

## Como se candidatar

Por favor envie um email para contato@dietsystem.com.br com seu CV anexado - enviar no assunto: Front-end Developer no DietSystem

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dia após cada processo.

#### Alocação
- Remoto
- JavaScript
- PHP
- CRUD

#### Regime

- Freela

#### Nível
- Júnior
- Pleno

**Comment by luizmagao** [comment]
Desejo me candidatar, domino laravel, vue e js. Entre outras questões.

**Comment by Gardium** [comment]
Enviado

**Comment by gabrielsaintz** [comment]
Desejo me candidatar, consigo desempenhar bem, com banco de dados e js.

**Comment by Vitor545** [comment]
Enviado

**Comment by eduardosimass** [comment]
Enviado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
