### ISSUE TITLE
[Remote] React Developer na International opportunity

### ISSUE THREAD

**Issue by TacianySouza** [frontendbr/vagas#6951]
Requisitos Técnicos
React.js, Javascript, Node.js, Css, Postgresql, Mysql, Python, Aws, Sqs/sns, Graphql, Cms oracle, Api, Rest.api, Next.js
Requisitos comportamentais

Requisitos obrigatórios:
● Mais de 5 anos de experiência em desenvolvimento de software
● Mais de 3 anos de experiência com React
● Bacharelado ou experiência profissional equivalente
● Conhecimento avançado de Javascript e Node.js
● Conhecimento avançado de CSS e HTML
● Experiência com ganchos do React e gerenciamento de estado da interface do usuário
● Experiência na criação de testes unitários e código de perfil.
● Experiência com estruturas ORM
● Experiência em banco de dados com PostgreSQL, MySQL e otimização de consultas
● Conforto com gerenciamento de repositório de código (GitHub, BitBucket)

Requisitos desejáveis:
● Experiência com linguagens de back-end, incluindo Java, JavaScript, Bash, Shell e/ou Python
●Experiência com CMS e gerenciamento de conteúdo.
● Experiência na criação de arquiteturas de sistema altamente escaláveis ​​(cache, filas, notificações)
● AWS uma vantagem, incluindo SQS e Lambda

Sobre a empresa:
É uma empresa de software B2B de rápido crescimento que desenvolveu a solução líder de gerenciamento de jornada do paciente para o setor de fertilidade em rápido crescimento. Quase metade dos pacientes de fertilidade nos EUA usam suas ferramentas de eLearn e eSign e também têm uma presença internacional crescente. As clínicas usam seu software para reduzir tarefas manuais repetitivas e agilizar a jornada do paciente, ajudando-as a aumentar a capacidade e o crescimento, melhorando a experiência do paciente e reduzindo o desgaste do médico e da equipe. Eles são conhecidos por ter uma cultura colaborativa, amigável, de alta energia e movimento rápido e uma atmosfera de start-up focada.

Candidatura: https://forms.gle/8wHHFz8oGTHnFs8q8

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
