### ISSUE TITLE
[Remoto] Front-end Developer React na Stefanini Brasil Group

### ISSUE THREAD

**Issue by DehTech** [frontendbr/vagas#6952]
## Nossa empresa

Somos a maior multinacional brasileira e estamos entre as 100 maiores empresas de TI do mundo. Estamos presentes em 41 países com +31k colaboradores. A Stefanini tem como principal objetivo auxiliar os clientes a encontrar, por meio de soluções personalizadas, a maneira ideal para alcançar seus desafios, impulsionando a inovação digital. E queremos mais!

## Descrição da vaga

Você atuará como Front-end developer em um importante cliente do segmento de tecnologia conhecido mundialmente e se relacionará com time global. 

## Local

Remoto 

## Requisitos

**Obrigatórios:**

- Inglês intermediário /avançado 

- Mais de 5 anos com React/JS

- Mais de 5 anos com TypeScript

- Mais de 5 anos com MobX

- Mais de 5 anos com Jest

- Mais de 5 anos com postCss

## Benefícios
Personalizados conforme o seu interesse pois aqui respeitamos cada indivíduo. Entre os benefícios oferecemos:
- Plano de saúde
- Plano Odontológico
- Seguro de vida
- VR / VA
- Auxílio creche / Reembolso Educação
- Parcerias com instituições de ensino e cursos de idiomas
- SESC
- Ginástica Laboral Online
- Gympass (plataforma de academias em todo Brasil)
- Go Integro (clube de descontos nos melhores estabelecimentos da América Latina)
- Allpoints (Plataforma de moeda de viagens)
- Rosetta Stone (Software de ensino de Línguas)
- Descontos Alura
- Trilha de carreiras na Academia Stefanini
- Mentoring, Inclusive com profissionais de outros países e idiomas
- Desconto em Universidades e Instituições de idiomas

## Contratação

CLT

## Como se candidatar

Por favor envie um email para dsescarlate@stefanini.com com seu CV anexado - enviar no assunto: Vaga React

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.

#### Alocação

- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
