### ISSUE TITLE
[Presencial] Jr. Full Stack Developer na BIZSYS [São Paulo]  

### ISSUE THREAD

**Issue by BizsysTecnologia** [frontendbr/vagas#6955]
## [Presencial] Jr. Full Stack Developer na [BIZSYS](https://bizsys.com.br) [São Paulo]
Somos uma produtora de tecnologia, especializada em exceder os limites da tecnologia para entregar inovação para nossos clientes em qualquer plataforma, canal ou formato.

## Descrição:

Participar de equipes de desenvolvimento com gerentes de projetos para idealizar e executar soluções de software.

Auxiliar na construção de arquiteturas.

## São Paulo 
Rua Dom João V, 432 - Lapa. 

## Requisitos:
    Conhecimento ou experiência comprovada como:
	 - Desenvolvedor
	 - Programação de UI/UX
	Excelentes habilidades de comunicação e trabalho em equipe
	Ótima atenção aos detalhes
	Habilidades organizacionais
	Mente analítica
	Cursando ou Formado em área relacionada de TI

Obrigatórios:
HTML5, CSS, SASS, Javascript, React, PHP, MySql e Git.

Desejáveis:
Unity 3D, QML

## Benefícios

 Estacionamento OU ajuda de custo p/ transporte. 

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um e-mail para hello@bizsys.com.br com seu CV anexado - enviar no assunto: Vaga Jr Full Stack Developer. 

#### Alocação
- Presencial 

#### Regime
- PJ

#### Nível
- Júnior

**Comment by sophiecalixto** [comment]
Já enviei meu currículo 👍🏻

**Comment by Jeecambui** [comment]
Vou enviar meu currículo 😊

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
