### ISSUE TITLE
[Pernambuco] Front-end Developer na @NutcacheBrasil

### ISSUE THREAD

**Issue by Criscampello** [frontendbr/vagas#6957]
[Pernambuco] Front-End Developer na @NutcacheBrasil

## Nossa empresa

Na Nutcache o time de desenvolvedores trabalha com a criação e aprimoramento de funcionalidades
para o nosso software. Procuramos fazer pequenas entregas constantes e com qualidade, seguindo os
preceitos de gestão ágil e da ferramenta Scrum.

## Descrição da vaga

● Criação e manutenção de funcionalidades na aplicação web;
● Criação das telas e ações de acordo com a descrição solicitada nas tarefas e exemplificadas
em mock-ups fornecidos;
● Análise, planejamento e desenvolvimento da funcionalidade;
● Colaborar ativamente com o SCRUM Master e o Product Owner nas entregas;
● Participar da análise e arquitetura necessária ao desenvolvimento das tarefas;
● Seguir o método Scrum, utilizada pelos times para gestão das atividades diárias;
● Manter boa comunicação com o time de desenvolvimento discutindo e opinando sobre os
direcionamentos a serem tomados, buscando ajudar na solução de problemas com os pares
quando necessário.

## Requisitos

**Obrigatórios:**
● Formação Ciência da computação ou cursos relacionados;
● Experiência em React Js e Redux;
● Experiência em HTML, CSS e Javascript;
● Inglês intermediário / avançado / fluente;
● Entendimento de métodos ágeis e ferramentas Scrum e Kanban.

**Desejáveis:**
● Experiência com ferramentas como Git e Visual Studio Code;
● Noções básicas de UI/UX;
● Experiência com React Hooks;
● TypeScript;
● Redux Toolkit;
● REST API.

## Benefícios

● Plano de Saúde - Bradesco Saúde Top Nacional (100% custeado pela empresa);
● Plano Odontológico - Bradesco Odonto (100% custeado pela empresa);
● Seguro de vida - Prudential;
● Benefício de bem-estar físico e mental - Gympass;
● Vale refeição/alimentação - Flash benefícios flexíveis (Bandeira Mastercard);
● Gratificação por indicação de novos colaboradores;
● Material de trabalho completo;
● Day off no mês de aniversário;
● Horário e formato flexível;
● Auxílio idiomas;
● Auxílios de capacitação técnica;
● Clima colaborativo e flexível.

## Contratação

CLT

## Como se candidatar

Por favor envie um email para cristianeferrao2012@gmail.com com seu CV anexado - enviar no assunto: Vaga Frontend Nutcache

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.

#### Alocação

- Híbrido
- Remoto

#### Regime

- CLT

#### Nível

- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
