### ISSUE TITLE
[São Paulo] Fullstack Engineer - Beetech Global

### ISSUE THREAD

**Issue by EduardoRazuk** [frontendbr/vagas#696]
Descrição da vaga

Estamos em busca de desenvolvedores que, assim como a gente, tenha um perfil ousado e empreendedor: gente ligada em tecnologia, com brilho nos olhos, que goste de evoluir com novas experiências, e principalmente, queira construir produtos e soluções incríveis. 

Para isso temos um nível de exigência alto com qualidade e buscamos um full stack que irá trabalhar junto a área de performance da empresa, fazendo novas integrações com sistemas terceiros, implementando features nos sistemas atuais e identificando novas oportunidades que possam se tornar produto. Para isso, é imprescindível o interesse por machine learning e inteligência artificial.

Local

São Paulo - Pinheiros ( Próximo a praça Benedito Calixto )

...
Diferenciais

Experiência em ambiente AWS (EC2, LoadBalancer, VPC)
Experiência com cache (memcache, redis…)
Experiência com sistemas de alta disponibilidade
Ter trabalhado em projetos que utilizam machine learning

Requisitos:

Experiência com Node.js e Python na construção de APIs restful
Sólidos conhecimentos de HTML/CSS/Javascript
Conhecimento de banco de dados relacional (PostgreSQL, MySQL, Oracle) e não relacional (MongoDB, DynamoDB)
Experiência de +2 anos na utilização de frameworks JavaScript MVC e preferencialmente já ter trabalhado em projetos com React
Vivência com metodologias ágeis (XP, Kanban, Scrum…) 
Utilizar TDD

Contratação

PJ a combinar

Nossa empresa

A BeeTech quer mudar o mercado financeiro usando tecnologia. Nossa missão é simplificar processos, aproximar distâncias e facilitar a relação de todas as pessoas com a troca de moedas e transferências internacionais. Queremos encurtar as distâncias entre o mundo e nossos clientes.

Como se candidatar

Se você gostou da descrição acima, se identificou com o perfil da vaga e busca desafios que te deem a oportunidade de crescer muito, e muito rápido, envie seu currículo e um breve parágrafo contando o porquê você é o candidato ideal para a vaga. Buscamos pessoas que não se conformam facilmente, que acreditam em processos escaláveis e estejam confortáveis com um ambiente em que o crescimento é completamente baseado na sua evolução no trabalho. Vem pra Bee! #GoBee

Sugestão de assunto para o email:
Vaga: Fullstack Engineer | [nome do candidato]
Currículo para:
eduardo.razuk@mar.ventures

**Comment by lucasdaiki** [comment]
#GoBee

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by lucasdaiki** [comment]
@LFeh Sim

**Comment by vinyguedess** [comment]
Aceita remoto ?

**Comment by EduardoRazuk** [comment]
É presencial Vinicius.
