### ISSUE TITLE
[Remoto] Front-end Developer ( React/ Sênior ) na @META

### ISSUE THREAD

**Issue by techrhrj** [frontendbr/vagas#6960]
## Nossa empresa
Confie em quem entende de tecnologia e venha com a Meta!
Nosso propósito: crescimento humano com tecnologia.

Acesse nosso site: https://www.meta.com.br/

## Descrição da vaga

Oportunidade de Alocação em multinacional brasileira que atua no segmento de alimentos;

## Local

 Remoto 

## Requisitos

**Obrigatórios:**
- 4 anos (mínimo) de experiência com React
- Vivência com metodologia ágil
-  React Hooks, Context API, Redux.

**Diferenciais:**
- React Native
- Typescript

## Benefícios

- Plano de saúde
- Plano odontológico
- Seguro de vida
- PLR
- Ajuda de Custo
- VR/ VA
- Parceria com a Alura
- Parceria com a Vittude
- Meta Academy
- English Club
- Acesso a plataforma microsoft learn para certificações
- ...

## Contratação

CLT

## Como se candidatar

Por favor envie um email para thais.franco@meta.com.br com seu CV anexado

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
