### ISSUE TITLE
[São Paulo] Front-end Developer com VTEX na Forever Liss

### ISSUE THREAD

**Issue by LuciaSartorio** [frontendbr/vagas#6961]
> Vaga Remota durante a pandemia

## Nossa empresa

Exemplo: Aqui na Forever Liss somos apaixonadas por beleza e inovação!
Cosméticos capilares Cruelty Free com qualidade de salão para uso em casa.

## Descrição da vaga

	1 ano de experiência em front com Vtex	
	Experiencia com JS, React	
	Experiencia em NODE	
	Atenção a Detalhes	
	Ter boa visão estética	
	Conhecimento de Design

## Local

Exemplo: Remoto

## Requisitos

**Obrigatórios:**
-  1 ano de experiência em front com Vtex
- Experiencia com JS, React
- Experiencia em NODE

## Benefícios

- CLT
- Beneficios

## Contratação

CLT

## Como se candidatar

Por favor envie um email para hunter.vagastech@gmail.com com seu CV anexado e pretensão salarial - enviar no assunto: Front-end Developer com VTEX 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: hunter.vagastech@gmail.com

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
