### ISSUE TITLE
[Remoto] Senior React Developer | Sênior | PJ - Builders

### ISSUE THREAD

**Issue by RaissaBaltazar** [frontendbr/vagas#6962]
Se você cansou de viver uma rotina sem desafios, a Builders está aqui para te proporcionar uma jornada empreendedora. Somos um movimento que só cresce (mais de 147% de aumento das contrações em 2022) e com a nossa cultura do empreendedorismo, queremos impactar cada vez mais o mercado. 

**O nosso encontro já está marcado, se você tem:** 

- Conhecimento em Firebase (Analytics, Crashlytics, etc)

**Agora se você entende dos tópicos abaixo, nossos projetos te aguardam:**

- Fluência em TypeScript;
- React (Redux/Mobx);
- APIs REST;
- Trabalhar com diferentes dimensões de dispositivo (tablet, celular, etc)
- Versionamento de código com Git;
- Conhecimento em arquitetura de software;
- Metodologias ágeis.

**E o que você vai ter de vantagem sendo Builder?** 

- Oportunidades reais de empreender e impactar;
- Atuar em contas de grande impacto no mercado;
- Inovação e criação liberados;
- Participar de um processo único de geração de valor;
- Contribuir na criação de métodos disruptivos;
- Colocar suas ideias no mercado, na prática!
- Possibilidade de Profit Share em novos Negócios;
- Prestador de Serviços (PJ).

Junte-se ao movimento: https://jobs.kenoby.com/sejabuilder/job/senior-react-developer-cod-748-remoto/627e60a710f664b88296e3c7?utm_source=website

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
