### ISSUE TITLE
[Remoto] Software Engineer, Frontend Tech Lead (React/Next) na Maxihost

### ISSUE THREAD

**Issue by marianaboaro** [frontendbr/vagas#6963]
<!--
==================================================
Caso a vaga for remoto durante a pandemia deixar a linha abaixo
==================================================

## Nossa empresa
At Maxihost, we are passionate about making the cloud more straightforward and faster. We work at the physical infrastructure layer, building products and solutions that automate the deployment and management of bare metal servers.
We don’t use strict methodologies or copy industry standards. We’ve created our own workflow, which allows us to work calmly and productively. This workflow is public and can be found here.
We work in an agile and highly collaborative environment, with many members of the Engineering team working remotely.

## Descrição da vaga
We love building beautiful, accessible, and intuitive experiences, mostly for our website and dashboards. We are now working on a whole new dashboard experience, which will completely change how customers interact with our product. While at it, you will also have the opportunity of working on open source projects like Metal UI.
You might be a fit for this role if you consider yourself an enthusiastic and resourceful software engineer who is passionate about building great products, someone who loves being part of a team, whilst enjoying the autonomous nature of working remotely.

- Plan, build, test, and release new features and experiments in Javascript and React.
- Collaborate with the Software Engineering team to develop and improve the components that make our website and dashboard. 
- Participate in design reviews and share your work regularly with the Engineering Manager.
- Collaborate with engineers across the department to identify and build on improvements to our processes and systems.
- Lead the Frontend team.
- Hire and manage new employees to your team.
- Sometimes work on very broadly defined, loose concepts, and sometimes on narrowly defined, tactical deliverables.
- Understand the array of technical constraints, user goals, and business requirements that shape a product.

## Requisitos
- You have a strong technical background and consider yourself an expert in HTML, CSS, and Javascript.
- You have solid front-end development experience, building, running, and debugging web applications using modern JS frameworks (React, Next, etc).
- You like to write and run tests and believe stability is instrumental to build great user experiences.
- You have strong verbal and written communication skills in English.
- You are a pragmatic engineer who actively avoids over-engineering of solutions and understands how to maintain a high-quality code in a delivery-focused environment.
- Are someone who wishes to work in a respectful, transparent, and collaborative work environment.
- Are a person who values collaboration with your peers to deliver exceptional experiences.

## Local de trabalho
- Remote

## Contratação
- PJ a combinar ou CLT

## Benefícios CLT
- Plano de saúde e odontológico
- Seguro de vida
- Cartão flexível VR/VA

## Como se candidatar
Want to know more? Please send your updated resume or LinkedIn profile to mariana.boaro@maxihost.com.br

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ PJ
- ⚖️ CLT

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
