### ISSUE TITLE
[Portugal] Senior Web Developer na ClaraNet Portugal

### ISSUE THREAD

**Issue by AlexClaranetPortugal** [frontendbr/vagas#6966]
## Nossa empresa

Fundada em 1996, a Claranet é o maior fornecedor de serviços de tecnologias de informação em Portugal, especialista em soluções de Cloud, Security, Dados e Workplace. 

Hoje, conta mais de 2.500 colaboradores em 10 países (Reino Unido, Portugal, Brasil, França, Alemanha, Holanda, Espanha, Itália, Suíça e USA), 24 escritórios e 45 datacenters, dos quais 2 em Portugal. 

A Claranet tem como missão global construir uma relação de confiança duradoura com cada um dos seus clientes, ajudando-os a focar os seus recursos na inovação e criação de valor para o seu negócio.

Mais informações em www.claranet.pt

## Descrição da vaga

Posição de Senior Web Developer para a ClaraNet UK. É uma vaga para um time de engenharia do Reino Unido que atua com Pesquisa e Desenvolvimento e que está com um projeto grande de desenvolvimento de produtos para acelerar websites e evitar ataques DDoS. 

Essa vaga é baseada em Lisboa e tem como requisito inglês fluente para o dia-a-dia pois o time é composto por profissionais de toda a Europa. Arcamos com os custos de visto e transição do profissional. 

Buscamos profissionais com boa bagagem técnica em Web Fullstack (skills em Python). Preferencialmente experiência dividida em 80% Python Web + 20% Front-end, mas também podendo ser 80% front-end + 20% Python Web.

## Local

[Portugal], [Lisboa]

## Requisitos

**Obrigatórios:**
-Advanced/Fluent English
-3+ years of web application development experience, producing standards compliant HTML5, CSS and JS and VueJS
-3+ years of experience working in a Linux/Unix environment.
-3+ years of experience of writing software in Python.
-Ability to produce reliable, user driven, well-tested, high-quality code.
-Experience in working with software revision control systems (preferably Git).
-Familiar with, or experience in systems driving continuous integration and continuous deployment (e.g. Jenkins)
-Experience implementing High Availability (HA) and distributed systems/platform design.
-Good understanding of modern computer networking, including IPv6.
-Good understanding of HTTP, DNS and SQL

**Desejáveis:**
-Ability (and enthusiasm) in mentoring less experienced developers. 
-Ability (and enthusiasm) to work with new technologies such as ElasticSearch, Docker, Vagrant, InfluxDB, etc. 
-An active understanding and interest in the open source ecosystem. 
-Opinions and willingness to implement good visual design where required. 
-Interpersonal skills and an eagerness to iterate on user feedback. 
-Virtualisation and / or containerisation experience including high availability, performance, monitoring and security. 
-Excellent troubleshooting, analytical skills and attention to detail.

## Benefícios

- Plano de saúde (50% para dependentes)
- VR
- Auxílio benefícios
- Passagem aérea + hospedagem

**Diferenciais:**
- Ambiente que te expõe a empresas de toda a Europa
- Possibilidade de morar no segundo país mais seguro da Europa (e quarto país mais seguro do mundo) com todo o auxílio jurídico e financeiro pra facilitar a transição.
- Um recruiter que fez o mesmo processo e consegue tirar todas as suas dúvidas em tempo real =)

## Contratação

Modelo "CLT" Português

## Como se candidatar

Por favor envie um e-mail para alexander.giffoni@pt.clara.net com seu CV anexado (enviar no assunto: Vaga Web Developer Portugal)

## Tempo médio de feedbacks

Respondo no máximo em 1 dia. Pode me acessar por e-mail ou LinkedIn ( https://www.linkedin.com/in/alexgiffoni/ )

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Sênior/Especialista

**Comment by AlexClaranetPortugal** [comment]
This job is still open!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
