### ISSUE TITLE
[Remoto] Full Stack Engineer na netLex

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6967]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/full-stack-engineer-204255293?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>A netLex</strong> busca pessoa<strong> Fullstack Engineer</strong> para compor seu time!</p>
<p>O time de Desenvolvimento da netLex tem a responsabilidade de lidar com a escalabilidade, manutenibilidade e principalmente implantação de novas features ao nosso produto, atuando de ponta a ponta e propondo soluções para os desafios da empresa.</p>
<p>Para 2022 temos um objetivo ousado de crescimento e por isso estamos em busca de talentos que queiram crescer e aprender muito junto com a gente! ;)</p>
<p><br><strong>Responsabilidades do dia a dia;</strong></p>
<ul>
<li>Implementar novas features para facilitar a rotina de trabalho de nossos clientes, as maiores empresas do Brasil;</li>
<li>Desenvolver código limpo e escalável;</li>
<li>Compartilhar conhecimento e aprender rápido;</li>
<li>Ser participativo na evolução da arquitetura e infraestrutura das soluções;</li>
<li>Criar novos serviços robustos e escaláveis;</li>
<li>Participar da migração de código legado para frameworks modernos.﻿<br></li>
</ul>
<p></p>
<p></p>

## netLex: 
 <p>Os documentos regem todas as relações entre uma empresa e seus stakeholders e têm um grande impacto sobre o sucesso da empresa.&nbsp;</p>

<p>Nós queremos motivar nossos clientes a transformar a maneira como lidam com documentos, para que consigam explorar todo o potencial destes ativos.</p><a href='https://coodesh.com/empresas/netlex'>Veja mais no site</a>

 ## Habilidades: 
 - Clean Architecture 
- PHP 
- Python 
- Angular 
- Javascript
## Local: 
 100% Remoto
## Requisitos: 
 - Curso superior completo ou em andamento em Ciência da Computação, Engenharia de Computação, Sistemas de Informação, Engenharias, etc.; 
- Experiência prévia com alguma das linguagens a seguir: PHP, Python, C# e C++ para Backend; 
- Frontend: Angular com Javascript, HTML e CSS; 
- Experiência com Javascript (ES6+); 
- Experiência com arquitetura de sistema web e bancos de dados relacionais; 
- Conhecimentos de Scrum, Kanban e práticas de desenvolvimento ágil; 
- Capacidade de avaliar e se adaptar rapidamente a novas tecnologias;

## Benefícios: 
 - Horários Flexíveis; 
- Cartão de benefícios flexível ( Cajú ); 
- Bônus anual; 
- Plano de saúde e odontológico; 
- Day off de aniversário; 
- Licença maternidade e paternidade estendida.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Full Stack Engineer na netLex](https://coodesh.com/vagas/full-stack-engineer-204255293?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
