### ISSUE TITLE
[Remoto] Fullstack Developer - Trainee na CuboConnect

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6968]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/primeiro-trabalho-para-desenvolvedora-trainee-165947266?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>A Cuboconnect</strong> busca pessoa<strong> Fullstack Developer (Estágio)</strong> para compor seu time!</p>
<p>A Cuboconnect, empresa atuante na área de T.I. há 22 anos, tem como um de seus alicerces promover o aperfeiçoamento profissional dos seus colaboradores e criar oportunidade do primeiro trabalho através do nosso Programa de Capacitação Profissional.</p>
<p><strong>Atividades: </strong></p>
<ul>
<li>Desenvolvimento e manutenção de aplicações web, através de linguagens como Java e Javascript;</li>
<li>Atuar com bancos de dados relacionais como MySQL e não relacionais como MongoDB;</li>
<li>Interagir com outros membros do time de desenvolvimento.</li>
</ul>
<p></p>
<p></p>

## CuboConnect: 
 <p>A cuboconnect atua no mercado há mais de 20 anos como uma transformadora digital de soluções de tecnologia. São mais de 100 clientes em uma relação de confiança e transparência acrescidos de nossa experiência e profundo conhecimento em diversos segmentos de mercado.</p>
<p>Levamos soluções que resolvem e entregam resultados com inovação, capacidade de entrega e performance em projetos customizados e de alta complexidade.</p><a href='https://coodesh.com/empresas/cuboconnect'>Veja mais no site</a>

 ## Habilidades: 
 - Java 
- Javascript 
- Lógica de Programação
## Local: 
 100% Remoto
## Requisitos: 
 - Dinamismo;  
- Raciocínio lógico; 
- Facilidade em se comunicar; 
- Comprometimento com a evolução profissional; 
- Ser apaixonado (a) por tecnologia. 
- Buscamos pessoas que estão cursando ou tenham concluído recentemente a graduação em tecnologia. 

## Benefícios: 
 - Reembolso de certificações 
- Aperfeiçoamento profissional através de cursos técnicos.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack Developer - Trainee na CuboConnect](https://coodesh.com/vagas/primeiro-trabalho-para-desenvolvedora-trainee-165947266?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Full-Stack

**Comment by Guedesou** [comment]
Me inscrevi! Boa sorte aos aplicantes!

**Comment by thalicelopes** [comment]
Inscrito, boa sorte a todos!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
