### ISSUE TITLE
[Remoto] Founding Front-end Developer na Pannacotta

### ISSUE THREAD

**Issue by fertalib** [frontendbr/vagas#6969]
## Nossa empresa

A Pannacotta se propõe a resolver o maior problema da economia do conhecimento. Perdemos mais tempo alinhando o trabalho a ser feito que fazendo o que importa. Criamos uma solução inovadora a partir do calendário. Times compartilham objetivos e alocam eventos do calendário a eles para ter clareza de quando estão trabalhando no que importa, resultando em alinhamento e foco em toda a empresa. 

## Descrição da vaga

Estamos contratando um Founding Front End Developer para desenvolver nosso produto inicial e levar a empresa aos seus primeiros usuários.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência com frameworks Javascript

**Desejáveis:**
- Experiência com desenvolvimento de Chrome Extensions

**Diferenciais:**
- Experiência em early stage startups

## Benefícios

- Salário competitivo
- VR ou VA

**Diferenciais:**
- Stock Options
- Oportunidade de construir a cia do zero
- Oportunidade de participar nas decisões de tecnologia

## Contratação

CLT

## Como se candidatar

Por favor faça seu application em:
https://pannacotta.breezy.hr/p/70b895fb88ae-founding-front-end-engineer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: jobs@pannacotta.io

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno ou Senior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
