### ISSUE TITLE
[São Paulo] Front-End Developer na Editora Segmento

### ISSUE THREAD

**Issue by editorasegmento** [frontendbr/vagas#697]
## Descrição da vaga

Procuramos desenvolvedor(a) Front-End com experiência em Wordpress para trabalhar alocado.

## Local

Escritório, São Paulo - Pinheiros

## Requisitos

**Conhecimentos obrigatórios:**
 
- HTML5;
- CSS3;
- Javascript;
- PHP;
- Wordpress;

**Desejáveis:**
- Git;
- Scss;
- Gulp;

## Contratação

PJ com salário de R$3500,00

## Nossa empresa

Nascida no ano de 1993 tendo como principais características a aposta no bom jornalismo, o senso empreendedor e uma fina percepção do mercado, a Editora Segmento é, hoje, uma das principais referências brasileiras na produção de conteúdos sobre educação e gestão de pessoas.

## Como se candidatar

Por favor envie um email para thean@editorasegmento.com.br com seu CV anexado - enviar no assunto: Vaga Front-Ender

**Comment by HaluDeCassia** [comment]
Boa noite, sem chance de remoto?

**Comment by danilosilvadev** [comment]
@editorasegmento faz entrevista via skype?

**Comment by editorasegmento** [comment]
@HaluDeCassia somente alocado.

**Comment by editorasegmento** [comment]
@danilosilvadev não, só presencial.

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by editorasegmento** [comment]
@LFeh Sim, ainda em aberto.

**Comment by danieladuarteng** [comment]
enviado
