### ISSUE TITLE
[Remoto] Front-end Developer (Angular 11) na Deal | CLT

### ISSUE THREAD

**Issue by Henriquetechrecruiter** [frontendbr/vagas#6975]
![Angular Pleno](https://user-images.githubusercontent.com/91859149/169408774-2b54cb5b-4669-4220-8231-7595951925ac.jpg)
Olá viajante, você já conhece a Deal?﻿
 
Iniciamos nossa corrida espacial em 2004, já especializada em transformação digital, mesmo quando ninguém falava sobre isso. Através da concepção e estratégia de negócio, até a implementação e evolução tecnológica (end-o-end), aprimoramos o negócio dos nossos clientes em todas as camadas, utilizando métodos ágeis para entregar soluções de TI que mudam a realidade das empresas. Somos reconhecidos pelo GPTW e ISG, e especializados em Transformação Digital, Modelos Ágeis de Gestão, Solução em Sistemas de Dados e Arquiteturas Robustas e facilmente Escaláveis.
 
A cultura Dealmaker é baseada no nosso EVP, ou seja, no compromisso que temos de ser um dos lugares mais incríveis para se trabalhar, um lugar onde as pessoas sejam protagonistas de suas histórias, onde todos tenham oportunidades iguais e onde haja respeito acima de tudo. Incentivamos a diversidade e nossas vagas são acessíveis a todas as pessoas, independente de gênero, orientação sexual, religião ou raça e se estendem ao público PCD.
Estamos em busca de um novo tripulante, para assumir a função de  **Front-end Developer (Angular) Pleno**.

Projeto voltado a implementação e criação de novas interfaces no Internet Banking, utilizando Angular 11 e o conceito Micro front-end. 

• JavaScript
• HTML
• CSS
• Jenkins
• Testes unitários com Jest 
• Experiência com métodos ágeis Scrum ou Kanban
• Feature toggle
• Apigee

Nossos tripulantes com contratação CLT têm diversas vantagens:

• Flash benefícios
• GymPass
• Trilha de carreira
• Assistência Médica
• Assistência Odontológica
• Incentivo a certificação e qualificação
• Home Office: trabalhe de onde quiser!

• Atuação 100% remota
• 2 anos de experiência com Angular

Contato: henrique.oliveira@deal.com.br
Whats App: 11930998984

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
