### ISSUE TITLE
[100% Remoto] Software Engineer Manager | vaga para Mulheres @Creditas 💚 

### ISSUE THREAD

**Issue by creditasvagas** [frontendbr/vagas#6977]
A Creditas é uma plataforma digital focada em melhorar a vida das pessoas na América Latina em 3 ecossistemas: auto, imobiliário e benefícios corporativos.

**Com tecnologia desenvolvida 100% dentro de casa, trabalhamos com todas as linguagens de programação do mercado.** Ideal para quem, assim como a gente, ama se desafiar e se desenvolver na resolução de problemas reais.

**As nossas contratações são CLT, com diversos benefícios e 100% remotas!**

**O que esperamos de você:**
- Gerenciar uma das tribos da Creditas
- Se apoiar em métricas e resultados
- Ajudar na construção de uma tribo de alta performance
- Construir e implementar a visão técnica
- Atuar como "líder dos líderes"

**Para saber mais, clique aqui e se inscreva:  https://grnh.se/40ab2d9b2us**

**A vaga é afirmativa para mulheres**, mas se você não se encaixar, acessa a nossa página de carreiras e veja a vaga que pode dar match com você! 
Link: https://grnh.se/5b3fa5002us

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
