### ISSUE TITLE
[Remoto] Angular Developer @ Oportunidade Internacional

### ISSUE THREAD

**Issue by TacianySouza** [frontendbr/vagas#6978]
Requisitos obrigatórios:
● Pelo menos 4 anos de experiência como desenvolvedor front-end/IU
● Envolvido no desenvolvimento de Angular 4+ (HTML5 e JavaScript) para renderização do lado do cliente e validação de dados do lado do cliente em formulários
● Experiência de trabalho com WordPress e PHP
● Envolvido no consumo de serviços web RESTful para exibir os dados na página principal
● Interpretar os requisitos do usuário e traduzi-los em maquetes.
● Uso do estilo CSS3 e Bootstrap para design responsivo de páginas da web
● Experiência em várias ferramentas de interface do usuário Angular, como Angular Material e NgBootstrap
● Excelentes habilidades de comunicação em inglês (mínimo B2+)

Requisitos desejáveis:
● Conhecimento prévio de trabalho com CMS como Shopify e/ou Magento
● Usa funções da biblioteca jQuerycore para a parte de implementação lógica no lado do cliente

Responsabilidades:
● Identificar e analisar os requisitos do usuário.
● Priorize, atribua e execute tarefas ao longo do ciclo de vida de desenvolvimento de software
● Revise, teste e depure o código dos membros da equipe
● Verifique se nossos aplicativos são seguros e atualizados
● Participar das atividades/cerimônias do time Scrum.
● Fornecer suporte a aplicativos em um ambiente de produção, resolvendo problemas de tickets atribuídos à equipe

Sobre a empresa:
É uma solução de financiamento simples e inovadora que ajuda as pequenas empresas a adquirir os equipamentos de que precisam para crescer. Nossa solução de pagamento inovadora conecta fornecedores de equipamentos a pequenas empresas por meio de planos de pagamento flexíveis e acessíveis.

Candidatura: https://forms.gle/8wHHFz8oGTHnFs8q8

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
