### ISSUE TITLE
[São Paulo] Frontend Engineer - Easy Carros

### ISSUE THREAD

**Issue by EduardoRazuk** [frontendbr/vagas#698]
Descrição da vaga

Buscamos pessoas ambiciosas para integrar a nossa equipe de desenvolvimento e surpreender os nossos clientes e profissionais com produtos incríveis!

Embora busquemos pessoas excepcionais, não diferenciamos profissionais jovens daqueles experientes, pois acreditamos que valor é criado através de inteligência, espírito empreendedor, capacidade de execução e meritocracia. O perfil importa mais que o nível de escolaridade - quanto mais hungry, melhor. Por trás da empresa, está um time incrível de pessoas e investidores com vasta experiência em algumas das empresas mais conhecidas do mercado: Ambev, Easy Taxi, Helpling, Zocprint, Airu, etc. Trabalhamos duro para transformar a maneira com que as pessoas se relacionam com seus carros e se você não está alinhado com essa cultura, por favor, não se inscreva.

Suas responsabilidades

Criar interfaces leves, dinâmicas e responsivas
Criar componentes reutilizáveis
Ter atenção aos detalhes (pixel perfect)
Fazer testes A/B
Saber prototipar para testar novas implementações com nosso UX designer

Local

São Paulo - Pinheiros ( Próximo a praça Benedito Calixto )

...
Diferenciais

Possuir conhecimentos em Redux/Saga
Possuir conhecimentos em React-Native
Possuir conhecimentos em Acessibilidade
Possuir conhecimentos em testes unitários
For formado em Ciência da Computação ou cursos relacionados
For fluente em inglês

Requisitos:

Experiência comprovada como front-end
Sólidos conhecimentos em React, HTML/CSS3, Sass, POO, Design Patterns, Javascript
Bons conhecimentos em SEO
Bons conhecimentos de POO
Residir na cidade de São Paulo ou região
Interesse em aprender constantemente
Seja atento aos detalhes
Inglês técnico

Contratação

PJ a combinar

Nossa empresa

A indústria automobilística está mudando drasticamente. A Easy Carros acredita que o futuro da indústria está na mão de engenheiros de software, não engenheiros mecânicos e que empresas, não indivíduos, serão donos dos veículos. Por isso, estamos mudando a forma que empresas se relacionam com seus veículos, usando tecnologia, big data e inteligência artificial.

Com clientes como Azul Linhas Aéreas, Grupo Bimbo e Fiat, a Easy Carros é um marketplace de serviços para carros, conectando empresas a prestadores de serviço de qualidade em mais de 60 cidades no Brasil. Coletamos dados sobre os veículos e usamos análise preditiva e inteligência artificial para permitir que empresas controlem seus custos das frotas, tenham gestão sobre os serviços,  previsibilidade sobre pagamentos e tornem suas frotas mais eficientes.

Levamos frotas para a era do software.

Como se candidatar

Se você gostou da descrição acima, se identificou com o perfil da vaga e busca desafios que te deem a oportunidade de crescer muito, e muito rápido, envie seu currículo.

Sugestão de assunto para o email:
Vaga: Frontend Engineer | [nome do candidato]
Currículo para:
eduardo.razuk@mar.ventures

**Comment by LFeh** [comment]
Aberto ainda?
