### ISSUE TITLE
[REMOTO] Analista de inovação digital pleno (Dev full stack squad) na Arcadis

### ISSUE THREAD

**Issue by luizacintraf** [frontendbr/vagas#6981]
> Vaga Remota durante a pandemia

## Nossa empresa

Nosso trabalho com os clientes tem impacto direto na vida das pessoas e no planeta. Tornamos a mudança, a moradia e o pertencimento às cidades mais seguros, resilientes e sustentáveis. Em parceria com nossos clientes como guardiões responsáveis dos recursos da nossa terra, podemos criar um planeta sustentável.

Continuamos a pensar em novas maneiras de causar impactos positivos e criar melhores experiências para as pessoas; soluções orientadas a dados e digitais tornaram-se parte do DNA da Arcadis. Trabalhando junto com os clientes e usando técnicas como design thinking, podemos chegar ao cerne dos desafios mais urgentes de nossos clientes e trabalhar juntos para resolvê-los.

Como uma empresa global, temos o compromisso de apoiar cinco dos Objetivos de Desenvolvimento Sustentável da ONU para garantir que nossos projetos contribuam para um futuro melhor e mais sustentável para todos. Mas não é apenas o trabalho que fazemos em projetos de clientes que beneficia as comunidades e nosso planeta. Como uma empresa global, temos o compromisso de causar um impacto positivo na sociedade, apoiando as comunidades locais onde operamos.

Para ajudar a proteger nosso planeta, monitoramos e medimos informações não financeiras para informar as decisões de negócios e reduzir nosso próprio impacto ambiental, como parte de nosso compromisso de ter carbono zero líquido como uma empresa global até 2030.

Nosso compromisso com a igualdade, diversidade, inclusão e pertencimento:

Queremos que você seja capaz de trazer o seu melhor para o trabalho todos os dias, por isso levamos a igualdade e a inclusão a sério e nos responsabilizamos por nossas ações. A nossa ambição é ser o empregador de eleição e proporcionar um excelente local de trabalho para todos os nossos colaboradores. Na Arcadis, reconhecemos, respeitamos e valorizamos as diferenças. Por isso, todas as oportunidades são para todos, todas e todes!

Transforme seu mundo

## Descrição da vaga

Atuar apoiando a equipe de Inovações Digitais no desenvolvimento e entrega soluções e produtos eficientes de tecnologia. As soluções devem ser robustas, escaláveis, seguras e com a melhor experiência ao cliente. Atuar de forma colaborativa dentro de times multidisciplinares da Arcadis Brasil, América Latina e Global, dando suporte às distintas atividades, produtos e serviços das equipes

## Local

Remoto ou Híbrido (São Paulo, Belo Horizonte ou Rio de Janeiro) (a escolha é do candidato)

## Requisitos

**Obrigatórios:**
-Graduação completa em Engenharia, Ciência da Computação, Análise e desenvolvimento de sistemas e áreas correlatas;
-Experiência em Desenvolvimento de Software;
-Boa lógica de programação e estruturação de dados;
-Inglês avançado;
-Vivência com Git e GitHub.

**Desejáveis:**
-Conhecimento de Frameworks de Front-end (React);
-Conhecimento de Linguagens: NodeJs; HTML; CSS; Javascript; Python;

**Diferenciais:**
-Experiência em execução de testes automatizados;
-Conhecimentos/Interesse na área ambiental;
-Experiência com metodologias ágeis.

## Benefícios

-Plano de saúde Bradesco
-Seguro de vida
-Vale Refeição ou alimentação (Alelo tudo)
-Auxílio creche
-Gympass

## Contratação

CLT

## Como se candidatar

Pode se candidatar pelo link: https://www.linkedin.com/jobs/view/3039326139

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
