### ISSUE TITLE
[Belo Horizonte/REMOTO] Fullstack Developer na Yellow.rec

### ISSUE THREAD

**Issue by stergouv** [frontendbr/vagas#6985]
> 

## Nossa empresa

Somos uma empresa de tecnologia com soluções de rastreamento para o mercado B2B e temos como propósito criar soluções para um mundo mais seguro, traduzindo dados em informações confiáveis, transformando tecnologia em prosperidade, assegurando conexões inteligentes e descomplicando a jornada do cliente.

Atuamos em todos os Estados do Brasil e temos, em nossa cultura, o foco no cliente. Com isso, prezamos sempre pela inovação de serviços e produtos que vão impactar diretamente no crescimento e prosperidade de nossos parceiros. Assim, entregamos ao mercado uma solução completa, oferecendo: plataforma, conectividade e equipamento possibilitando que os nossos clientes rastreiem, acompanhem e recuperem seus veículos através de uma jornada descomplicada.

Por aqui somos muitos. Unidos em uma comunidade inovadora com foco em pessoas.﻿

Assim, construímos uma cultura onde somos livres para pensar diferente e sermos protagonistas da nossa jornada incrível. Se você deseja fazer o seu melhor trabalho e contribuir para crescer junto, você está no lugar certo.

## Descrição da vaga

Estamos procurando por uma pessoa para atuar no nosso time de Tecnologia que queira ser livre para pensar diferente e ser protagonista da nossa jornada incrível. Se você deseja fazer o seu melhor trabalho e contribuir para crescer junto, esta oportunidade é para você.

## Local

[REMOTO] [BELO HORIZONTE]

## Requisitos

**Obrigatórios:**

Sólidos conhecimentos em desenvolvimento back end;
Ter trabalhado em projetos com React;
Ter trabalhado em projetos com Node;
Bancos de dados baseados em MySQL (MySQL, SQL Server, MariaDB, etc);
Experiência com ferramentas de gerenciamento de pacotes;
Experiência em desenvolvimento de APIs REST;
Conhecimentos em padrões de código e boas práticas;
Teste Unitários;

**Desejáveis:**
Conhecimento em Go;

## Benefícios

Remuneração compatível com o mercado
Horário flexível e banco de horas;
Plano de Saúde Bradesco com cobertura nacional na modalidade apartamento para você e seus dependentes
Plano Odontológico, também extensivo aos dependentes
Vale Refeição / Alimentação Vee de R$ 25,07 por dia
Indique um futuro Getrakiano: Receba até R$ 2.000,00 em voucher
PLR de acordo com os critérios do sindicato, afinal, se nós tivemos lucro você faz parte disso!
Saúde Mental: Atendimento com Psicólogo parceiro durante a pandemia / Dicas de cuidados e práticas para o corpo e mente / Lista de dicas filmes, séries e livros para dar aquela relaxada
Parceria com a Beetools, Cultura Inglesa e CCAA escola de idiomas.
Ações com foco no seu desenvolvimento (cursos, treinamentos externos e certificações)
Ghack : Encontros virtuais mensais para compartilhamento de conhecimento, trocas de experiências e aprendizado
Reunião de Resultados mensais, porque a transparência é um dos nossos valores
Cultura de Feedback e 1:1 através de uma plataforma amigável de gestão de pessoas
Happy hour virtual constante com lives musicais e voucher para pedir aquele petisco preferido, afinal, celebrar também é preciso!

## Contratação

CLT

## Como se candidatar

Por favor envie um e-mail para stefany.gouveia@yellow.rec.br com seu CV anexado - enviar no assunto: Vaga fullstack pleno

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
