### ISSUE TITLE
[REMOTO] Sênior Front-end Developer na DietSoftware

### ISSUE THREAD

**Issue by thiagoferreira123** [frontendbr/vagas#6986]
## Software de nutrição

Somos um software para profissionais da saúde em processo de construção, que no futuro, se tornará uma grande empresa. Procuramos por Front-end Developer nível Sênior para alavancar o a parte visual do nosso software sem economizar talento 🍏🚀

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência em JS puro (sem framework)
- Experiência em CSS
- Experiência em HTML

**Desejáveis:**
- conhecimentos em php e mysql.
- git
- documentação
- disponibilidade de 3h diárias

## Contratação

- Imediata

## Como se candidatar

Por favor envie um email para nutricionistathiagoferreira@gmail.com com o seu currículo em anexo, e se possível portfólios que foram usados JS. Costumamos enviar feedbacks em até 1 dia após cada processo.

## Labels

- Sênior
- Especialista
- JavaScript

#### Alocação

- Remoto

#### Regime

- Freela

#### Nível

- Sênior
- Especialista

**Comment by DanielKitanaxiFilipe** [comment]
Enviado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
