### ISSUE TITLE
[REMOTO/Florianópolis] (JR/PL/SR) Front-end Developer na Franq Open banking

### ISSUE THREAD

**Issue by rsornellas** [frontendbr/vagas#6987]
## Nossa empresa

🚀 Somos uma fintech que iniciou suas operações em outubro de 2019 e escolhemos Florianópolis/SC, a ilha da magia como nossa casa.

Desenvolvemos uma plataforma financeira digital, disponibilizando produtos de diferentes players do mercado, tendo como parceiros bancos, fintechs, corretoras, seguradoras, administradoras de consórcio, entre outros, facilitando o atendimento dos nossos clientes.

## Descrição da vaga

Dentro do time de Tecnologia, buscamos por perfis que tragam novidades sobre tecnologias de front-end e que sejam benéficas para a Franq. Que criem soluções de front-end utilizando boas práticas e produtos incríveis. Sempre atuando como protagonista, se colocando à frente de situações, trabalhando em equipe com os membros em busca da melhor solução.

## Local

Remoto ou Escritório [Floripa-SC]

## Requisitos

Conhecimento em programação Javascript.
Conhecimento de Clean Code e Design Patterns;
Conhecimento em frameworks de desenvolvimento;
Ter boa comunicação, saber trabalhar com times multidisciplinares em um ambiente dinâmico, com entregas rápidas e metodologias ágeis.

**Desejáveis:**
Conhecimento em Vue 3.
Conhecimento em Vuetify.
Conhecimento em Composition API.
Conhecimento em Web analytics.

**Diferenciais:**
Empresa jovem em franco crescimento com muita oportunidade de crescimento.
Trabalhar em um time de profissionais experientes e renomados do mercado financeiro. 
Desenvolver, evoluir e aprender habilidades com as melhores práticas e novas tecnologias. 
Ser parte de um projeto inovador que impacta vidas financeiras de clientes e novas formas de fazer negócio.  

## Benefícios

Contrato CLT.
R$ 741,80 mensais no cartão de benefícios flexíveis Caju.
Assistência médica e odontológica, sem coparticipação, totalmente subsidiada pela empresa.
Seguro de vida.
No dress code.
Day off de aniversário.

## Contratação

CLT

## Como se candidatar

No site https://franq.gupy.io/job/eyJqb2JJZCI6MTI4ODQ0Mywic291cmNlIjoiZ3VweV9wdWJsaWNfcGFnZSJ9?jobBoardSource=gupy_public_page

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: raphael.ornellas@franq.com.br

## Labels
Junior
Pleno
Senior
Remoto
Hibrido
Presencial

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by JonathasGit** [comment]
Já enviei o CV lá.

**Comment by Icegreeen** [comment]
Também enviei o meu!! 🙂

**Comment by rsornellas** [comment]
Tivemos um grande números de candidaturas, vamos encerrar por enquanto até conseguirmos dar feedback a todos.
Caso a vaga não seja preenchida reabrimos.
