### ISSUE TITLE
[Remoto Brasil] Front-end Developer na Panda Video 🐼 (VueJS)

### ISSUE THREAD

**Issue by lafraia** [frontendbr/vagas#6988]
![](https://user-images.githubusercontent.com/1311402/166702191-fe3c1998-017b-409d-bfff-2c53a65f1580.png)

## Nossa empresa

Oi pessoal!

Somos a [Panda Video](https://pandavideo.com.br/), startup 100% brazuca, começamos recentemente na área de hospedagem de vídeos focado no marketing digital, EAD e infoprodutos (concorrente do Vimeo e outros, resolvendo problemas como [este](https://medium.com/pandavideobr/vimeo-vai-bloquear-sua-conta-8934d218def6) e [este](https://www.youtube.com/watch?v=Ps0cMNti1Pc&t=2379s)). Mal começamos mas já somos referência transacionando cerca de 1PB (1024 terabytes) de vídeos por mês (e até algumas startups copiando nosso frontend ;-) ).

Temos poucas pessoas no time e estamos buscando mais algumas para ajudar a construir um player de vídeo com UX ótima e performance ainda melhor.

Dentro de 3 meses devemos a oferecer o sistema também para o mercado americano (Panda Video USA), já que estamos com preços imbatíveis por aqui.

Trabalhar diretamente com pessoas com mais de 25 anos de experiência com Internet no Brasil. Muito aprendizado.

## Descrição da vaga

A vaga é para trabalhar com Vue.js junto com a equipe desenvolvendo o dashboard de vídeos, nosso player e projetos relacionados. Hoje o produto é todo feito em Vue e Node, boa parte rodando em AWS Lambda... Mas o foco para a vaga é frontend / Vue.

Se você tem experiência com backend (AWS Lambda, Terraform, Node), certamente terá maior interesse.

## Local

100% remoto

## Requisitos

Obrigatórios:

* 2 anos de experiência com Frontend
* Experiência com Vue
* Experiência com ao menos uma plataforma de versionamento (Github, Gitlab, etc)

Desejáveis:

* Prática com AWS e AWS Lambda
* Experiência em Node.js

Diferenciais:

Esses itens a seguir são diferenciais não se preocupe se não tiver nenhum deles, mas se tiver aproveite para se gabar quando mandar o email ;-)

* Experiência com marketing digital, lançamentos, infoprodutos, etc...
* Experiência com performance web
* Experiência com software para vídeos (players, infra, etc)
* Ter colaborado ou manter projetos opensource
* Saber trabalhar em grupo
* Saber pedir ajuda e comunicar quando tem problemas
* Prática com UX/UI

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para [daniel@pandavideo.com](mailto:daniel@pandavideo.com) com seu CV anexado - enviar com o assunto: Vaga Front-end Vue na Panda pode também anexar seu Github, Gitlab ou qualquer outro projeto que ache interessante.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
