### ISSUE TITLE
[Deliver IT] Developer  React Native na Deliver IT 🚀

### ISSUE THREAD

**Issue by arthurdepauli** [frontendbr/vagas#6989]
## Nossa empresa

A Deliver IT vai deixar a digital nesse projeto e quer convidar você para fazer parte dessa construção! 🙆‍♀️

Temos uma cultura leve, descontraída, colaborativa e diversa, além de um ambiente enriquecedor, com muitos colegas feras em diversos segmentos e muitos desafios. Aqui você vai encontrar projetos inovadores, conexão e muita troca de conhecimento! 😊

Todas as nossas posições seguem o modelo de contrato CLT em 44h/semanais - Flexíveis.

**CONFIRA NOSSOS BENEFÍCIOS**

Modalidade: 100% Remoto
VA e/ou VR
Programa Bem-Estar: apoio psicológico, apoio jurídico, apoio social, apoio financeiro e ginástica laboral. 
Plano de Saúde e Plano Odontológico
Seguro de Vida
Incentivo ao inglês
Workshops mensais
Parcerias que te dão desconto: Sucesu, Target Trust, Sesc e Seprorgs
Premiação por aniversário de empresa
Premiação por indicação contratada

**SEJA DELIVER!**

A Deliver IT é uma consultoria de serviços de tecnologia da informação. Nossa missão é entregar valor aos nossos clientes, através de serviços de tecnologia de informação, dentro de uma relação de parceira.

Nascemos em 2014, a partir da união das atividades da Absoluta. Net com a experiência de mercado de dois profissionais sêniores, em áreas complementares! Acreditamos em equipes multidisciplinares, que possuem confiança em suas relações e sobretudo transparência. Nosso time se caracteriza pelo engajamento, comprometimento e foco na qualidade das entregas.

Acreditamos que a qualidade dos nossos processos se deve a todas as pessoas que fazem parte da Deliver, e por isso prezamos por um ambiente de trabalho agradável, leve e muito amigável. Aqui os colaboradores têm espaço para o seu desenvolvimento profissional, oportunidade de trabalhar em projetos globais e para empresas de reconhecimento a nível nacional.

Nosso portfólio de serviço utiliza tecnologias vanguardistas dentre as seguintes linhas: Fábrica de Software, Business Intelligence, Mobile e Outsourcing.

## Descrição da vaga

**Você se considera uma pessoa que tem sede por aprendizado, gosta de trabalhar em equipe e curte compartilhar conhecimento? Então essa oportunidade é para você!**

Estamos em busca de um(a) Desenvolvedor React Native, para atuar no desenvolvimento de melhorias e manutenção em aplicação existente e contribuição para definição de melhorias na arquitetura e padrões dos sistemas.

**RESPONSABILIDADES E ATRIBUIÇÕES
Na sua rotina de trabalho, você vai se deparar com as seguintes atividades:**

Análise, desenvolvimento, testes, documentação e implantação de sistemas;
Contribuir com as decisões de arquitetura da aplicação, buscando uma arquitetura distribuída, flexível, moderna e escalável que acompanhe o crescimento constante;
Ajudar a manter um “espírito” ágil;
Apoiar a construção da solução técnica e da arquitetura de software do projeto;
Revisão de código da equipe;
Acompanhar deploy em ambiente produtivo.

## Requisitos

CONHECIMENTOS EXIGIDOS

React Native;
React;
TypeScript;
Bons conhecimento de FrontEnd;
Consumo de APIs;
[Vue.js](http://vue.js/) e Quasar;
Scrum e Kanban.

CONHECIMENTOS DESEJÁVEIS

Firebase;
Clean Architeture;
Docker e Docker Compose;
Azure.

## Como se candidatar

Acesse:  https://deliverit.gupy.io/jobs/1857584

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
