### ISSUE TITLE
[Remoto] Fullstack Developer na iDinheiro 

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6992]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/pessoa-desenvolvedora-145957248?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>A iDinheiro </strong> busca pessoa <strong>Fullstack Developer</strong> para compor seu time!</p>
<p>Você terá a oportunidade real de trabalhar com diversas tecnologias de ponta que fazem e farão parte da nossa stack, tais como React e NodeJS, criando e mantendo aplicações dentro de uma arquitetura voltada a microsserviços e hospedada na plataforma cloud AWS utilizando as melhores práticas de devops. Atuar em um time multidisciplinar com agilidade e grandes oportunidades de aprendizado fará parte da sua rotina aqui.</p>
<p><strong>Responsabilidades:</strong></p>
<ul>
<li>Atuar junto do time de Produto na concepção, desenvolvimento e manutenção das nossas aplicações e produtos.</li>
<li>Possibilidade real de trabalhar com tecnologias de ponta nas diversas camadas da nossa arquitetura e principais atividades para suportá-las (frontend, backend, infraestrutura cloud, práticas dev</li>
</ul>
<p></p>
<p></p>
<p></p>

## iDinheiro : 
 <h2><span style="font-size: 18px;"><strong>Prosperidade financeira</strong></span></h2>
<p>Idealizada em 2020, somos uma empresa com objetivo de democratizar e simplificar serviços financeiros para as pessoas, por meio de tecnologia e conteúdos educativos. Estamos do seu lado para lhe apresentar as melhores opções sobre contas digitais, bancos, cartões de crédito, seguros, empréstimos, financiamentos e muito mais. A nossa missão é contribuir para a prosperidade financeira dos nossos usuários, fazendo com que eles tomem decisões mais inteligentes e simplificando suas jornadas financeiras.</p>
<p>O iDinheiro traz de forma simples as informações que te darão mais confiança em quais ações você deverá tomar, contando com ferramentas essenciais para sua jornada. Tais como:</p><a href='https://coodesh.com/empresas/idinheiro'>Veja mais no site</a>

 ## Habilidades: 
 - Amazon API 
- Test Driven Development 
- UI
## Local: 
 100% Remoto
## Requisitos: 
 - Proatividade, curva de aprendizado rápida e que esteja sempre buscando aprender coisas novas; 
- Conhecimentos de algoritmos e estrutura de dados; 
- Consiga escrever código limpo e modular; 
-  Experiência desenvolvendo software com Javascript (Preferêncialmente Reactjs ou Nodejs); 
- Conhecimento de APIs Rest; 
- Tenha experiência de trabalho em equipe ágil.
## Diferenciais: 
 -  Experiência em Conteinerização (Docker); 
-  Conhecimento de Typescript; 
-  Conhecimento de TDD; 
-  Experiência com plataformas cloud; 
-  Conhecer APIs GraphQL.
## Benefícios: 
 - Horários flexíveis; 
- Cashback online em dobro; 
- Vale refeição e alimentação; 
- Ajuda de custo para teletrabalho; 
- Plano de saúde e odontológico.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack Developer na iDinheiro ](https://coodesh.com/vagas/pessoa-desenvolvedora-145957248?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
