### ISSUE TITLE
[HIBRIDO EM BH] Front-end Developer na Hypesoft

### ISSUE THREAD

**Issue by Gabihype** [frontendbr/vagas#6993]
> 

## Nossa empresa

Somos a Hypesoft uma empresa de consultoria e serviços de TI.
Atuamos com 3 pilares: Outsourcing, hunting e fabrica de software.

## Descrição da vaga

A Vaga é para atuar como Desenvolvedor Front End Pleno (Acima de 2.5 anos) em uma empresa brasileira de energia renovável com grande expertise no desenvolvimento, construção e operação de usinas de fonte hidráulica.
Estamos à procura de um Desenvolvedor Front End experiente que será referência para outros desenvolvedores na criação de uma plataforma inovadora

Procuramos um desenvolvedor front end com boas skills (hard e soft) para fazer a ponte entre o designer e o backend e desenvolver as telas da aplicação. Há flexibilidade quanto à linguagem e modelo de trabalho caso o candidato seja bem capacitado para compensar o gap;
Criação do produto (plataforma atualmente opera no modelo B2B mas está migrando para o B2C atender também o pequeno consumidor)

## Local

Híbrido - Belo Horizonte (principalmente na etapa inicial do projeto, mas caso não seja possível, é possível flexibilizar);

## Requisitos

**Obrigatórios:**

React JS;
Stack web: Html; Css; Javascript;
Preferencialmente, experiência com UX/UI;

**Desejáveis:**

Inglês

## Contratação

CLT + Beneficios

## Como se candidatar

Por favor envie um email para gabriella.araujo@hypesoft.com.br com seu CV anexado - enviar no assunto: Vaga Front End

#### Alocação
Híbrido - Belo Horizonte (principalmente na etapa inicial do projeto, mas caso não seja possível, é possível flexibilizar);
Horário Flexível, mas preferencialmente um horário que não fuja muito do comercial para disponibilidade da equipe.

#### Regime

CLT

#### Nível

Pleno

**Comment by DanielKitanaxiFilipe** [comment]
Enviado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
