### ISSUE TITLE
[REMOTO] Front-end Developer (React) @ Evino

### ISSUE THREAD

**Issue by pserick** [frontendbr/vagas#6996]
## Nossa empresa

Maior grupo de varejo de vinhos importados do Brasil, Evino + Grand Cru são a única empresa do segmento com forte atuação multicanal, incluindo franquias, lojas de operação própria, live commerce, app, e-commerce, clube de assinaturas e distribuição aos melhores restaurantes, hotéis e bares, além de empórios e supermercados. 

Acreditamos que o vinho é mais do que o se sente na boca, são bons momentos, por isso trabalhamos para construir uma empresa feita por todos, em um ambiente leve, de hierarquia horizontal, sem burocracias desnecessárias, onde novas ideias, curiosidade de descobrir novos caminhos e senso de dono são sempre bem-vindos. Evino e Grand Cru receberam o selo Great Place to Work (GPTW), que reconhece as empresas como uma das melhores para se trabalhar.

## Descrição da vaga

- Trabalhar junto ao time de Produto para construir uma melhoria contínua na experiência entregue no site para os nossos clientes;
- Desenvolver soluções inovadoras trabalhando com o que há de mais moderno em termos de tecnologia de front-end;
- Trabalhar integrado ao time de back-end para desenvolver e integrar novas APIs ao site e aplicações responsivas;
- Atuar com o time de produto para desenvolver de forma ágil e com entregas rápidas e constantes buscando entregar sempre a melhor qualidade e experiência;
- Manter e evoluir o site atual das marcas junto com suas aplicações responsivas;
- Trabalhar de forma pontual na construção de conteúdo estático de acordo com a necessidade dos times de negócios;
- Implementar técnicas de desenvolvimento visando a evolução constante das nossas aplicações e do time.

## Local

Escritório fica na Paulista, mas a contratação é no modelo Remoto.
Porém o escritório é aberto para ir trabalhar presencial caso queira, vai saber no dia que você for não esteja rolando uma degustação de vinhos 🍷 😄 

## Requisitos

- Entenda de forma sólida HTML, CSS e Javascript;
- Tenha conhecimento de [React.js](http://react.js/);
- Tenha conhecimento em empacotadores/automatizadores (webpack, babel);
- Tenha noções de teste unitário e integração/aceitação (cypress etc..);
- Goste de trabalhar junto com o time de produto e UX;
- Tenha noções sobre otimização de páginas web para SEO;
- Tenha conhecimentos em API Rest;
- Tenha noções de GraphQL;
- Aplique conceitos de Design Responsivo/Adaptativo e Mobile First.

**Desejáveis:**

- Conhecimentos em CI/CD;
- Noções de ferramentas como GA, GTM;
- Experiência com testes de aceitação em Cypress;
- Vivência com as boas práticas e busca sempre as melhores soluções utilizando os conceitos de SOLID, Design Patterns, etc.

**E nos surpreenderia se tivesse:**
- projetos opensource

## O que nós ofercemos

- Espaço para criar e colaborar com a área, imprimindo o seu jeito de ser e conhecimentos que deram certo em outros lugares;
- Cultura de crescimento e muita aprendizagem;
- Benefícios como: Vale-transporte, Vale-refeição/Alimentação, Assistência médica e Odontológica, Sesc, Convênio Farmácia, Clube de descontos em produtos Evino e Grand Cru, acesso ao Saldão de Vinhos, subsídio educacional;
- Flexibilidade de horários e atuação 100% remota;
- Ambiente descontraído e divertido;
- All Hands: bate papo com nosso CEO e diretores;
- E sim! Você pode tomar vinho enquanto trabalha!

## Contratação

CLT

## Como se candidatar

Candidatar-se através do link: [Candidatar-se para a vaga](https://evino.gupy.io/job/eyJqb2JJZCI6MTY4NzcxMiwic291cmNlIjoiZ3VweV9wdWJsaWNfcGFnZSJ9?jobBoardSource=gupy_public_page)

Ou entrar em contato comigo através do [linkedin](https://www.linkedin.com/in/pserick/) sou Tech Lead do time que irá atuar! 🍷 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dias após cada processo.
E-mail para contato em caso de não haver resposta: erick.pereira@evino.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by JesseSousa** [comment]
Olá @pserick, é requirido algum tempo mínimo de experiência?

**Comment by pserick** [comment]
Olá @JesseSousa, não tem um tempo específico mas esperasse que o candidato já tenha alguma rodagem de mercado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
