### ISSUE TITLE
[Remoto & Potencial] Senior React Native Developer | PJ - Builders

### ISSUE THREAD

**Issue by RaissaBaltazar** [frontendbr/vagas#6997]
E aí, lenda! 🤘 Aqui na Builders não existe o clima perfeito. Porém nossa cultura ajuda a voltarmos no eixo naqueles dias que nada dá certo, sabe? 🥲 Sem falar que você vai vivenciar o empreendedorismo na prática. Seja em projetos, ajudando seu time com sua liderança ou nas ideias disruptivas que possam vir (e serão escutadas).  🙌

**O que te aproxima de ser uma Pessoa Builder:**
- Fluência em TypeScript;
- React Native (Redux/Mobx);
- APIs REST;
- Trabalhar com diferentes dimensões de dispositivo (tablet, celular, etc)
- Conhecimento geral do ambiente móvel;
- Versionamento de código com Git;
- Conhecimento em arquitetura de software;
- Metodologias ágeis.

**Como Builder, você terá acesso a:**
- Oportunidades reais de empreender e impactar;
- Fazer parte de uma comunidade de empreendedores; de ponta;
- Inovação e criação liberados;
- Participar de um processo único de geração de valor;
- Contribuir na criação de métodos disruptivos;
- Colocar suas ideias no mercado, na prática! :)
- Possibilidade de Profit share em novos Negócios;
- Prestador de Serviços (PJ).

Junte-se ao movimento: https://jobs.kenoby.com/sejabuilder/job/senior-react-native-developer-cod-685-remoto/624c541f5098ff47ec61f4ed?utm_source=website

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
