### ISSUE TITLE
[Remoto] Fullstack Java Developer na Fóton Informática

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#6998]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-java-fullstack-125319923?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Estamos buscando <strong><ins>Fullstack Java Developer</ins></strong> para compor seu time!</p>
<p>A Fóton Informática é uma empresa de tecnologia especializada no mercado financeiro. Há mais de 25 anos, ajudamos a transformar o dia a dia dos bancos e da população brasileira. Fazemos isto criando soluções que permitam uma maior aproximação das instituições bancárias à seus clientes.</p>
<p>Nossas soluções possibilitam que você acesse sua conta bancária através do celular, internet, caixa eletrônico e agência. Tudo isso com total segurança e praticidade.&nbsp;</p>
<p>Além de oferecer nossas próprias soluções, atuamos como parceiros especializados no desenvolvimento e manutenção de produtos e serviços financeiros, desenvolvidos pela Fóton ou de outros fornecedores.&nbsp;&nbsp;</p>
<p><strong><em>Venha fazer parte dessa história conosco!</em></strong></p>

## Fóton Informática: 
 <p>A Fóton Informática é uma empresa de tecnologia especializada no mercado financeiro. Há mais de 25 anos, ajudamos a transformar o dia a dia dos bancos e da população brasileira. Fazemos isto criando soluções que permitam uma maior aproximação das instituições bancárias à seus clientes.</p>
<p>Nossas soluções possibilitam que você acesse sua conta bancária através do celular, internet, caixa eletrônico e agência. Tudo isso com total segurança e praticidade.&nbsp;</p><a href='https://coodesh.com/empresas/foton-informatica'>Veja mais no site</a>

 ## Habilidades: 
 - Java 
- Angular 
- PostgreSQL
## Local: 
 100% Remoto
## Requisitos: 
 - Formação completa na área de tecnologia ou afins 
- Experiência comprovada como desenvolvedor 
- Habituado a trabalhar com metodologias ágeis 
- Conhecimento no Front-end: JSF, Primefaces , CSS, Jquery, Angular 
- Conhecimento no Back-end: Java, Hibernate, JPA 
- Banco de Dados: Postgresql, Oracle 
- Teste Unitário: Junit, Mockito 
- Versionamento: Git
## Diferenciais: 
 - Certificações Java.
## Benefícios: 
 - Vale Refeição/Vale Alimentação 
- Gympass 
- Seguro de vida 
- Plano Odontológico 
- Plano de Saúde 
- Participações nos Lucros 
- Desconto em Farmácias 
- Incentivos Educacionais
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack Java Developer na Fóton Informática](https://coodesh.com/vagas/desenvolvedor-java-fullstack-125319923?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
