### ISSUE TITLE
[Florianópolis] Desenvolvedor frontend

### ISSUE THREAD

**Issue by feliperbroering** [frontendbr/vagas#7]
## Descrição da vaga

Frontend engineer para trabalhar com AngularJS e Angular Material, NodeJS na healfies.com.

## Local

Florianópolis

## Benefícios

- Salário compatível com a senioridade
- Programa de participação em ações da Healfies

## Requisitos e Inscrição na vaga

Detalhes e inscrição no link: http://healfi.es/jedifee

**Comment by LFeh** [comment]
CLT ou PJ?

Junior, Pleno ou Senior? :)

**Comment by feliperbroering** [comment]
Inicialmente PJ.
Em qui, 11 de fev de 2016 às 17:16, Luiz Felipe Tartarotti Fialho <
notifications@github.com> escreveu:

**Comment by rands0n** [comment]
Acredito que seja Sr

> Salário compatível com a senioridade

**Comment by diegocandido** [comment]
Pode ser remoto?

**Comment by feliperbroering** [comment]
Pra essa vaga precisamos de alguém no dia a dia conosco

Em qui, 11 de fev de 2016 às 19:45, Diego Candido <notifications@github.com>
escreveu:

**Comment by Carlosxell** [comment]
@feliperbroering, a vaga já foi preenchida?

**Comment by feliperbroering** [comment]
Foi sim, abs

Em seg, 4 de abr de 2016 às 17:19, Carlos Augusto <notifications@github.com>
escreveu:

**Comment by willianjusten** [comment]
Estou fechando só para evitar que vagas que já foram preenchidas permaneçam aparecendo.

**Comment by LFeh** [comment]
\o/

**Comment by camilatigre** [comment]
@feliperbroering 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

**A pessoa que preencheu a vaga foi encontrada através desta issue?**
a) Sim
b) Não
c) Não tenho certeza

**Comment by feliperbroering** [comment]
a)

só um pouco atrasado 🙄
