### ISSUE TITLE
[Campinas] Desenvolvedora ou Desenvolvedor Front-End ( AngularJS)

### ISSUE THREAD

**Issue by gabriel-ribeiro-ir** [frontendbr/vagas#70]
## Descrição da vaga

Buscamos uma desenvolvedora ou desenvolvedor front-end para atuar no desenvolvimento de novos projetos em AngularJS.

## Local

Campinas/SP

## Porque esta é uma excelente oportunidade:

- Você fará parte de um time referência na Tecnologia.
- Projetos de alta visibilidade no mercado.
- Criação e evolução de novos produtos.
- Liberdade para experimentar novas tecnologias.

## Atividades:

- Desenvolvimento de aplicações web e web mobile;
- Elaboração de arquiteturas de sistemas e produtos;
- Responsável por especificação de documentações;
- Contato com o time de Negócios;
- Acompanhar a evolução dos produtos no mercado;
- Trabalho em equipe.

## Perfil desejado:

- Paixão por tecnologia
- Foco em resultado 
- Conhecimento sólido em Angular e HTML5
- Desejável conhecimento em Web Components, Polymer, Progressive Web Apps, NodeJS, Grunt, JavaEE e Spring MVC.
- Integrações com APIs REST e pré-renderização de páginas no backend.
- Inglês Intermediário

## Contratação

CLT.
Alocado.

## Como se candidatar

Candidate-se pelo pela vaga no [Linkedin](https://www.linkedin.com/jobs2/view/153879301?trk=biz-overview-job-post).

**Comment by eduardojmatos** [comment]
@gabriel-ribeiro-ir sabe se já preencheu a vaga? Nos avise pra mantermos ou removermos da lista :)

**Comment by gabriel-ribeiro-ir** [comment]
Na verdade não foi preenchida @eduardojmatos, mas pode fechar sim pois abrimos outra parecida.
Depois vou postar aqui.

**Comment by eduardojmatos** [comment]
@gabriel-ribeiro-ir blz! :)
