### ISSUE TITLE
[São Paulo] Full Stack Mobile App Developer na PetParker

### ISSUE THREAD

**Issue by georgesebel** [frontendbr/vagas#7000]
## Nossa empresa

Somos uma startup de mobilidade, que utiliza tecnologia e a colaboração de pessoas incríveis para criar caminhos para vidas mais felizes.

Para nós, aproximar o dia a dia das pessoas e pets com a cidade promove um estilo de vida mais sustentável, saudável e feliz para todos. Somos apaixonados por pets!

Aqui na PetParker, queremos construir um mundo onde as pessoas possam se sentir seguras em levar seus pets a todos os lugares.

Fundada em 2018, em São Paulo, a PetParker criou uma nova categoria em inovação com potencial de crescimento global. Foi premiada em 2020 e 2021 pelo ranking 100 Open Startups, e está presente nas mais importantes redes de varejo do Brasil.

Ainda estamos no início dessa jornada, temos muito a fazer para construir essa nossa missão, e você pode fazer parte desse sonho com a gente!

## Descrição da vaga

Buscamos profissionais que tenham conhecimento IOS (Swift) e Android (Java) para implementar e manter funcionalidades do nosso App de forma ágil.

## Local

Presencial, Brooklin, São Paulo - SP

## Requisitos

Dominar Swift e Java

## Contratação

PJ

## Como se candidatar

Por favor envie um email para contato@petparker.com.br com seu CV anexado - enviar no assunto: Vaga Dev Full Stack.

#### Alocação
- Presencial

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
