### ISSUE TITLE
[Curitiba] Front-end Developer ANGULAR no LACTEC

### ISSUE THREAD

**Issue by ebadillo2022** [frontendbr/vagas#7001]
## Nossa empresa

Exemplo: O Lactec é um dos maiores centros de pesquisa, tecnologia e inovação do Brasil. Atuamos fortemente nos mercados de Energia, Meio Ambiente, Indústria, Mobilidade Elétrica e Conectividade. Nossas soluções e serviços atendem às demandas atuais dos diversos setores produtivos da economia brasileira.

## Descrição da vaga

Desenvolvimento em Angular;

Criação de interfaces web em HTML5;

Criação de CSS para deixar o layout aderente ao protótipo previamente desenhado;

Integração do front-end com APIs REST;

Versionamento de código com Git;SQL para bancos de dados relacionais;

Desenvolvimento Javascript com Node.js.

## Local

PARANÁ, CURITIBA, JARDIM BOTÂNICO

## Requisitos

**Obrigatórios:**
- 4 anos de experiência com Front-end;
- 2 anos de experiência com Angular

## Benefícios

Plano de Saúde e odontológico;
Plano Previdência Privada;
Reembolso farmácia;
Seguro de vida;
Vale refeição/alimentação: R$ 948,00 ao mês;
Vale Transporte;
Auxilio creche: R$ 606,00 ao mês
Curso de inglês.

**Diferenciais:**
- Formato hibrido 

## Contratação

CLT

## Como se candidatar

Por favor envie um e-mail para elaine.badillo@lactec.org.br com seu CV anexado - enviar no assunto: Vaga ANGULAR

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: elaine.badillo@lactec.org.br

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
