### ISSUE TITLE
[Curitiba] Estágio Dev Web Full Stack @ Korp

### ISSUE THREAD

**Issue by NovareRH** [frontendbr/vagas#7005]
## Nossa empresa

A Korp é uma empresa especializada no desenvolvimento de sistemas ERP e CRM, ambos atendemas necessidades das indústrias e empresas de distribuição. O Viasoft Korp ERP, desenvolvido por programadores em consjunto com engenheiros de produção, proporciona recursos sofisticados de análises e simulaçoes em tempo real. Assim, as empresas conseguem romper limites com o poder da tecnologia. Jáo O Korp CRM chegou no mercado como uma força de vendas. O sistema de gestão comercial e relacionamento com o cliente auxilia os negócios a impulsionarem seus resultados. 

## Descrição da vaga

- Auxiliar em criação/testes de componentes e telas em Angular
- Auxiliar em criação/testes de componentes e telas em React
- Suporte ao desenvolvimento de serviços REST em C# e .NET Core.

## Responsabilidades

- Agilidade e qualidade no desenvolvimento ou manutenção dos códigos
- Buscar aprendizado contínuo para manter se atualizado nas tecnologias
- Ser proativo em questionar e buscar conhecer o produto que estará desenvolvendo.

## Local

[Curitiba]

## Requisitos

- Já ter tido algum contato com Angular ou React (pode ser em cursos, projetos ou experiências prévias)
- Não buscamos experiência profissional
- Gostar da regra de negócio indústria
- Bom comunicador - Saber se expressar
- Honestidade
- Senso de urgência
- Gostar de tecnologia e de desenvolvimento!

## Tecnologias que você vai APRENDER

- C#
- Angular/React
- NET Core
- Banco de Dados SQL Server
- Conceitos de BDD (Domain Driven Design) e ORM (Object-relational mapping)﻿.

#### Quais são os diferenciais dessa vaga?

- Aprendizagem de conceitos avançados, como padrões de projeto e princípios SOLID
- Utilização de tecnologias de ponta
- Caso você se adapte e curta o desafio, as chances de efetivação são altas!

## Contratação

- R$1.200,00 - Contratação CLT﻿ - 6h diárias flexíveis

## Como se candidatar

Aplique para a vaga [por aqui](https://www.careers-page.com/novare-rh/job/7RRRY5) .

#### Alocação
- Curitiba

#### Regime
- CLT

#### Nível
- Estágio

**Comment by Bianca-sa** [comment]
Aceitam aplicação para trabalhar remotamente?

**Comment by ebadillo2022** [comment]
Oi  Bianca, tudo bem? Você é de qual cidade?

De: Bianca de Sá ***@***.***>
Enviada em: segunda-feira, 30 de maio de 2022 00:39
Para: frontendbr/vagas ***@***.***>
Cc: Subscribed ***@***.***>
Assunto: Re: [frontendbr/vagas] [Curitiba] Estágio Dev Web Full Stack @ Korp (Issue #7005)


Aceitam aplicação para trabalhar remotamente?

**Comment by kelvin-re** [comment]
Olá, eu também tenho interesse na em fazer parte do time, porém sou de Minas Gerais. Se aceitar remotamente estou a disposição.

**Comment by ebadillo2022** [comment]
Poderia responder as perguntas abaixo?

- Quantos anos de experiência com Front-end?
-Quantos anos de experiência com Angular?
-Qual é a sua pretensão salarial?

De: Kelvin Santos ***@***.***>
Enviada em: segunda-feira, 30 de maio de 2022 09:36
Para: frontendbr/vagas ***@***.***>
Cc: Elaine Maria Badillo ***@***.***>; Comment ***@***.***>
Assunto: Re: [frontendbr/vagas] [Curitiba] Estágio Dev Web Full Stack @ Korp (Issue #7005)


Olá, eu também tenho interesse na em fazer parte do time, porém sou de Minas Gerais. Se aceitar remotamente estou a disposição.

**Comment by kelvin-re** [comment]
Eu tenho pouca experiência na área tanto no front-end como com angular, mas, estou fazendo alguns cursos para aprimorar meus conhecimentos. Estou cursando o 5° período de Análise e desenvolvimento de sistemas do Instituto Federal do Norte de Minas Gerais, e preciso de oportunidade de estágio para poder criar experiência na área e me formar um profissional de qualidade.
Pretensão salarial 1.500,00

**Comment by ebadillo2022** [comment]
Oi Kelvin,

No momento estamos trabalhando um posição de especialista em Front/Angular, mas vou ficar aqui com o seu contato para alguma posição de estágio que venha a surgir.

Abraço,

De: Kelvin Santos ***@***.***>
Enviada em: segunda-feira, 30 de maio de 2022 10:24
Para: frontendbr/vagas ***@***.***>
Cc: Elaine Maria Badillo ***@***.***>; Comment ***@***.***>
Assunto: Re: [frontendbr/vagas] [Curitiba] Estágio Dev Web Full Stack @ Korp (Issue #7005)


Eu tenho pouca experiência na área tanto no front-end como com angular, mas, estou fazendo alguns cursos para aprimorar meus conhecimentos. Estou cursando o 5° período de Análise e desenvolvimento de sistemas do Instituto Federal do Norte de Minas Gerais, e preciso de oportunidade de estágio para poder criar experiência na área e me formar um profissional de qualidade.
Pretensão salarial 1.500,00

**Comment by richnei** [comment]
Olá! Essa vaga ainda está aberta?

**Comment by luluntes3001** [comment]
Boa noite
Tenho muito interesse na vaga, sou de Curitiba e acabei de começar a migrar da área de pesquisa em saúde para engenharia de software, mas preciso de uma primeira oportunidade. Vocês aceitam pessoal sem experiência? Aprendo muito rápido, então estou pronto para qualquer desafio!

**Comment by MarceloBxD** [comment]
Boa tarde! Tenho muito interesse na vaga, sou do Rio de Janeiro e estou fazendo graduação em engenharia da computação pela UERJ-IPRJ, já tenho uma noção muito boa nas linguagens de programação em C, Javascript, e na linguagem de marcação HTML e de estilização CSS, já estou no quinto período da faculdade, e por esse estágio ter a possibilidade de horários flexíveis me interessou muito, estou disposto a aprender muito mais!

Segue minha página do github:
https://github.com/MarceloBxD

**Comment by tahaluh** [comment]
Tudo bem? Tenho interesse na vaga, sou um aluno deo IFRN em técnico em informática. Já tenho uma base sólida de programação, React, Node e banco de dados, inclusive no meu perfil aqui do github é possível ver alguns dos meus projetos, se for possível atuar de forma remota estou a disposição!
