### ISSUE TITLE
[REMOTO BR] Front-end Developer VUEJS na Alterdata Software

### ISSUE THREAD

**Issue by AlexiaMarques** [frontendbr/vagas#7006]
## Nossa empresa

A Alterdata é uma empresa que tem como objetivo melhorar a vida das pessoas, fornecendo soluções empresariais através de softwares e serviços.

Temos somente uma regra! Nunca ficamos parados, pois inovação é o que nos inspira a cada dia.

Gosta de aprender e ser desafiado? Esse é o seu lugar! 

## Descrição da vaga

Você integrará nosso time de especialistas, desenvolvendo produtos da área de automação comercial, utilizando as mais diversas tecnologias disponíveis no mercado.

## Local

REMOTO BR

## Requisitos

**Obrigatórios:**
- Bons conhecimentos em HTML, CSS e Javascript
- Conhecimento em pelo menos um framework SPA javascript (preferência por Vue e/ou AnguarJs)
- Conhecimentos em pelo menos um pré processadores CSS (SCSS, SASS, etc)
- Conhecimento em pelo menos um framework CSS (preferência por Bootstrap e/ou Bulma)
- Conhecimento em pelo menos uma lib para gerenciamento de estado (vueX, Redux)

**Desejáveis:**
- Experiência fazendo integrações com API Rest
- Conhecimento em gerenciadores de pacotes (NPM, bower, Yarn)
- Conhecimento em pelo menos uma biblioteca/framework para testes automatizados (Jasmine, Jest, etc)
- Conhecimento em arquiteturas de software (MVC, MVVM, etc)
- Experiência com task runners e/ou module bundlers (gulp, grunt, webpack)
- Metodologias ágeis (Scrum, Kanban)

**Diferenciais:**
- Conhecimentos em testes E2E (Selenium, Cypress, etc)
- Conhecimentos em arquitetura de micro front ends (Single SPA e/ou Module Federation)
- Frameworks para desenvolvimento mobile (React Native, Flutter)
- Conhecimento e aplicação de boas práticas (DDD, SOLID, Clean Code, Clean Architecture)

## Benefícios

Aqui o trabalho é 100% home office - CLT, trabalhamos com plano de cargos e salários e temos como benefícios: vale alimentação ou refeição, assistência médica, seguro de vida, Gympass e assistência odontológica, além da oportunidade de crescimento conforme o seu desenvolvimento e descontos em produtos e serviços em diversas empresas parceiras a nível nacional, como cursos voltados para a área de programação, day off, entre outros...

## Contratação

CLT

## Como se candidatar

Por favor candidate-se na nossa plataforma de carreiras: https://alterdata.software/carreiras ou envie um e-mail para alexia.rh@alterdata.com.br com seu currículo atualizado e pretensão salarial.

## Feedbacks

E-mail para contato em caso de não haver resposta: alexia.rh@alterdata.com.br
LinkedIn para contato https://www.linkedin.com/in/alexia-marques/

## Labels

- Remoto
- CLT
- PJ
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
