### ISSUE TITLE
[BELO HORIZONTE] Front-end Developer na Yellow.rec 

### ISSUE THREAD

**Issue by stergouv** [frontendbr/vagas#7007]
## Nossa empresa

A Yellow.rec é uma HRtech de recrutamento especializado que acredita que contratar pode ser mais simples!

Você se lembra das Páginas Amarelas dos catálogos? Nelas, você encontrava contatos organizados de uma maneira bem simples e tinha informações objetivas no alcance de suas mãos. Assim surgiu o nosso nome: Yellow. Muito mais do que uma cor para se apaixonar, esta é a nossa forma de encontrar os profissionais ideais para a sua equipe: de forma organizada, com informações objetivas e ao alcance do seu clique.

Estamos em busca de um(a) Desenvolvedor(a) Front-end Pleno para compor o nosso time! Se você está procurando um lugar para avançar em sua carreira, aprimorar suas habilidades e desenvolver uma plataforma integrada que vai revolucionar o mercado de recrutamento especializado, esta oportunidade é para você!

 

## Descrição da vaga

Estamos em busca de um(a) Desenvolvedor(a) Front-end Pleno para compor o nosso time! Se você está procurando um lugar para avançar em sua carreira, aprimorar suas habilidades e desenvolver uma plataforma integrada que vai revolucionar o mercado de recrutamento especializado, esta oportunidade é para você!

## Local

Híbrido [MINAS GERAIS], [BELO HORIZONTE]

## Requisitos

**Obrigatórios:**
Experiência comprovada de 3+ anos em Javascript e React.js
Domínio de estado global da aplicação (Redux, Context Provider, Zustand, Recoil)
Domínio de testes unitários (Jest e React Teste Library)
Conhecimento comprovado em HTML + CSS – Styled componentes
Conhecimento em realização de requisições com Apollo GraphQL
Familiaridade com Deploys de aplicações React.js na nuvem (Heroku, Github Actions, AWS Cloud Front e S3)

**Diferenciais:**
Experiência com PWA
Conhecimento em UX
Conhecimento em Git
Familiaridade com SSR
Conhecimento em React Native
Experiência com aplicações híbridas
Conhecimento em SEO

## Benefícios

Férias remuneradas (40 days off/ano);
Gympass;
Horário flexível;
Vale-Alimentação (Flash);
Aulas de inglês in company.

## Contratação

PJ 

## Como se candidatar

Por favor envie um e-mail para stefany.gouveia@yellow.rec.br com seu CV anexado - enviar no assunto: Vaga Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

#### Regime

- PJ

#### Nível

- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
