### ISSUE TITLE
[Remoto] Front-end Developer (AngularJS) na Deal | CLT 

### ISSUE THREAD

**Issue by Henriquetechrecruiter** [frontendbr/vagas#7008]
![Modelo Publicação Vagas - Imagem](https://user-images.githubusercontent.com/91859149/170795383-4c62a8d4-1321-4ad2-bf01-56082177fe44.jpg)
**Olá viajante, você já conhece a Deal?**﻿

Iniciamos nossa corrida espacial em 2004, já especializada em transformação digital, mesmo quando ninguém falava sobre isso. Através da concepção e estratégia de negócio, até a implementação e evolução tecnológica (end-o-end), aprimoramos o negócio dos nossos clientes em todas as camadas, utilizando métodos ágeis para entregar soluções de TI que mudam a realidade das empresas. Somos reconhecidos pelo GPTW e ISG, e especializados em Transformação Digital, Modelos Ágeis de Gestão, Solução em Sistemas de Dados e Arquiteturas Robustas e facilmente Escaláveis.

A cultura Dealmaker é baseada no nosso EVP, ou seja, no compromisso que temos de ser um dos lugares mais incríveis para se trabalhar, um lugar onde as pessoas sejam protagonistas de suas histórias, onde todos tenham oportunidades iguais e onde haja respeito acima de tudo. Incentivamos a diversidade e nossas vagas são acessíveis a todas as pessoas, independente de gênero, orientação sexual, religião ou raça e se estendem ao público PCD.

Estamos em busca de um novo tripulante, para assumir a função de Desenvolvedor Frontend (AngularJS)

- Ampla experiência em design de aplicações web;
- HTML, CSS, HTML5;
- Sólidos conhecimentos em Angular .JS;
- Conhecimentos e experiência prévia em Druppal será um grande diferencial;
- Conhecimento e experiência prévia em Node.JS será diferencial;
- Atuação em Instituições Financeiras será um diferencial

Nossos tripulantes com contratação CLT têm diversas vantagens:

• Flash benefícios
• GymPass
• Trilha de carreira
• Assistência Médica
• Assistência Odontológica
• Incentivo a certificação e qualificação
• Home Office: trabalhe de onde quiser!

Contato: 11930998984
henrique.oliveira@deal.com.br

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
