### ISSUE TITLE
[São Paulo] Front-End Developer & Tech Lead na [Evino]

### ISSUE THREAD

**Issue by evinorecruiter** [frontendbr/vagas#701]
## Descrição da vaga

Como Front End Dev & Tech Lead, seus maiores desafios serão:

- Planejar a arquitetura das nossas aplicações para que sigam as melhores práticas do mercado;
- Implementar técnicas de desenvolvimento visando a evolução constante das nossas aplicações e do time;
- Acompanhar o dia a dia do time de front-end garantindo entregas de qualidade;
- Codificar, integrar e manter nosso site Front-end (NodeJS, React);
- Entregar projetos bem testados, sustentáveis e de alta complexidade;
- Trabalhar com a equipe de Produto para entender os requisitos, antecipando as mudanças para proporcionar uma experiência incrível ao usuário;
- Desenvolver software usando programação funcional (immutability, side effects, high order functions, referential transparency, map/reduce).

## Local

Alocado no escritório na Bela Cintra, próximo à Paulista

## Benefícios

- VT (com desconto de 6%) ou estacionamento no prédio (com desconto de R$43,00/mês)
- VR ou VA (R$28,00/dia)
- Vale Alimand – para consumo interno (R$65,00/mês)
- AM (One Health)
- AO (MetLife)
- Seguro de Vida
- Gympass
- Desconto em vinhos
- Parceria com instituições de ensino e idiomas
- Horário flexível
- HH de vinho toda sexta

## Requisitos

**Para isso, esperamos que você:**

- Tenha experiência com desenvolvimento de software em React e pelo menos outras duas tecnologias em Javascript como: NodeJS, Redux, Angular, Ember, Backbone, etc.
- Tenha conhecimentos sólidos em arquiteturas de HTML e CSS, usando as melhores práticas e ferramentas, assim como Stylus, SASS, SCSS, PostCSS, etc;
- Conheça muito bem testes unitários e metodologias de testes;
- Conheça paradigma funcional em programação e suas features como imutabilidade, curried e currying functions, recursão, closures, side effects, etc;
- Também tenha bons conhecimentos em sistemas de controle de versão (GIT, por exemplo);
- Tenha experiência profissional significante usando Web Services (REST, SOAP);
- Domine as melhores práticas de desenvolvimento, como Design Patterns, TDD;
- Goste de trabalhar com metodologias ágeis e tenha vivência em pelo menos uma delas (Scrum, Kanban, XP);

**Desejáveis:**

- Conhecimento sobre mecanismos concorrentes e paralelos, como arquiteturas reativas, multithreading e programação assíncrona;
- Experiência em liderança de times;
- Experiência anterior em empresas de varejo/ecommerce.

## Contratação

CLT a combinar

## Nossa empresa

Somos apaixonados por vinho e acreditamos que o melhor vinho do mundo é aquele que harmoniza com você. Por isso fazemos de tudo para descomplicar e proporcionar a melhor experiência, sempre. 

Fazemos uma cuidadosa curadoria para levar o melhor rótulo para a sua mesa, onde quer que você esteja. O objetivo aqui é levar a garrafa certa, no preço certo, para agradar seu paladar sem desagradar seu bolso, é claro. 

A gente acredita que novas descobertas sobre o universo do vinho podem deixar tudo melhor. Se você conhece vinho, nossa função é contar algo diferente. Se desconhece, somos a porta de acesso a um mundo cheio de novidades. 

Lembre-se: quando se trata de vinho, tudo pode. Vinho pode com futebol, pode com churrasco no verão. Pode com rock e - por que não? - com samba. Só não pode complicar.

## Como se candidatar

Envie seu cv atualizado ou linkedin para valeria.souza@evino.com.br, com o título "Front Lead - Evino"

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by evinorecruiter** [comment]
@LFeh Aberta ainda. Desculpe a demora. Interessa?

**Comment by LFeh** [comment]
Opa, é para manter aberta aqui no repositório

**Comment by evinorecruiter** [comment]
é, sim. Acabei de atualizar a descrição
