### ISSUE TITLE
[Remoto] Frontend Angular (Estágio) na Centelho Tecnologia

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#7010]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/estagio-desenvolvedor-front-end-angular1-185034647?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>A Centelho</strong> busca pessoa<strong> Frontend Angular (Estágio)</strong> para compor seu time!</p>
<p>A centelho é uma ‘startup’ fundada com o intuito de criar soluções tecnológicas para múltiplos segmentos seja B2B ou B2C, atualmente possuímos 2 ‘softwares’ em desenvolvimento para impacto no mercado de Gestão de pessoas e Gerenciamento imobiliário.</p>
<p><strong>O que você irá fazer aqui na centelho:</strong></p>
<ul>
<li>Participar do desenvolvimento front-end de novas funcionalidades e sustentação;</li>
<li>Componentização e estruturação do projeto front-end;</li>
<li>Adquirir conhecimento a cada dia.</li>
</ul>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>

## Centelho Tecnologia: 
 <p>A centelho é uma ‘startup’ fundada com o intuito de criar soluções tecnológicas para múltiplos segmentos seja B2B ou B2C, atualmente possuímos 2  ‘softwares’ em desenvolvimento para impacto no mercado de Gestão de pessoas e Gerenciamento imobiliário.</p>
<p>Procuramos pessoas apaixonadas por inovação e que não tenham medo de se arriscar, pessoas que queiram fazer a diferença e com espírito empreendedor.&nbsp;</p><a href='https://coodesh.com/empresas/centelho-tecnologia'>Veja mais no site</a>

 ## Habilidades: 
 - Javascript 
- Angular 2+ 
- CSS 
- HTML 5 
- Node.js 
- Flexbox 
- Typescript 
- GIT
## Local: 
 100% Remoto
## Requisitos: 
 - Cursando Graduação na área de TI 
- Conhecimento solido em HTML, CSS, Javascriaca 
- Conhecimento em Angular 2+ 
- Conhecimento em Flexbox 
- Conhecimento em Typescript é essencial
## Diferenciais: 
 - Conhecimento em Node JS 
- Conhecimento em controle de versão (GIT) 
- Conhecimento em integração com API REST 
- Conhecimentos de SQL
## Benefícios: 
 - Seguro de Vida 
- 100% Remoto 
- Day Off no seu aniversário
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Angular (Estágio) na Centelho Tecnologia](https://coodesh.com/vagas/estagio-desenvolvedor-front-end-angular1-185034647?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
Estágio
#### Categoria
Front-End

**Comment by EricoDev-Front** [comment]
Teria vaga Júnior Angular?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
