### ISSUE TITLE
[Remoto BR] Front-end Developer VUEJS na Seducar

### ISSUE THREAD

**Issue by Gabrielmoraesp** [frontendbr/vagas#7012]
## Nossa empresa

A Seducar é uma empresa focada em ensino a distância. Estamos criando uma plataforma SaaS, para empresas que desejam vender cursos de ensino a distância com baixo custo e com funcionalidades personalizadas.

## Descrição da vaga

Você integrará nosso time de especialistas, desenvolvendo produtos da área de automação comercial, utilizando as mais diversas tecnologias disponíveis no mercado.

## Local

REMOTO BR

## Requisitos

**Obrigatórios:**

- Bons conhecimentos em HTML, CSS e Javascript
- Conhecimento em pelo menos um framework SPA javascript (preferência por Vue)
- Conhecimentos em pelo menos um pré processadores CSS (SCSS, SASS, etc)
- Conhecimento em pelo menos um framework CSS (preferência por Bootstrap e/ou Tailwind)
- Conhecimento em pelo menos uma lib para gerenciamento de estado (vueX, Redux)

**Desejáveis:**

- Experiência fazendo integrações com API Rest
- Conhecimento em gerenciadores de pacotes (NPM, bower, Yarn)
- Conhecimento em arquiteturas de software (MVC, MVVM, etc)
- Metodologias ágeis (Scrum, Kanban)

**Diferenciais:**

- Conhecimentos em arquitetura de micro front ends (Single SPA)
- Frameworks para desenvolvimento mobile (Flutter)
- Conhecimento e aplicação de boas práticas (DDD, SOLID, Clean Code, Clean Architecture)

## Contratação

Freela - 2 meses

## Como se candidatar

Por favor envie um e-mail para gabrielmoraesp@gmail.com com seu CV anexado - enviar no assunto: Vaga VueJs

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- Freela

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
