### ISSUE TITLE
[Gaspar] Front-end Developer na [Lince Participações e Empreendimentos Ltda]

### ISSUE THREAD

**Issue by paolasouzaf** [frontendbr/vagas#7013]
## Lince Participações e Empreendimentos Ltda

O Grupo Lince é composto pelas empresas Lince, Circulo e Plasvale.

Fundada em 24 de Junho de 1980, a Lince nasceu para garantir o controle central, manter o DNA e a cultura em todas as empresas do grupo. A Lince gerencia e apoia funções essenciais para o funcionamento dos negócios, buscando impulsionar os resultados através de soluções de tecnologia, assessoria jurídica, intermediação e assessoramento de negócios próprios ou parceiros. As principais empresas do grupo são a Lince, Lince International, Circulo e Plasvale.

## Descrição da vaga

O que faz? 
Desenvolvimento e manutenção de apps multiplataforma e nativos; 
Auxiliar de modelagem de interfaces responsivas para smartphones, tablets e laptops; 

## Gaspar/SC, rua Dr. Nereu Ramos, n° 750, Coloninha

Escritório, [SANTA CATARINA], [GASPAR], [COLONINHA]

**Desejáveis:**

- Conhecimento em lógica de programação e orientação a objetos; 
- Conhecimento básico em controle de versão GIT; 
- Conhecimento em uma ou mais linguagens: DART, Java, Kotlin e Swif; 
- Noções sobre framework Flutter; 
- Conhecimento em banco de dados SQLite e MySQL; 
- Conhecimento sobre protocolos HTTP E webservices; 
- Conhecimento em arquitetura Clean ou MVC;

## Benefícios

- Cartão alimentação/refeição;
- Plano de saúde Unimed;
- Convênio com Uniodonto;
- Incentivo Inglês;
- Disponibilização de treinamentos e certificações;
- Oportunidades de desenvolvimento e crescimento pessoal e profissional;
- Café, biscoitos e frutas a vontade;
- Desconto nas compras de produtos do Grupo (Círculo, Plasvale);
- Convênio SESC;
- Dress code informal;
- Estacionamento no local

## Contratação

a combinar

## Como se candidatar

Você pode conferir mais informações através do site: https://lince.enlizt.me/

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: paola.souza@lince.com.br

#### Regime
- CLT

**Comment by G-campos** [comment]
Olá @paolasouzaf, tudo bem?

Achei interessante a vaga, mas gostaria de fazer alguns apontamento que pode lhe ajudar numa divulgação mais assertiva.

- Em vez de divulgar a vaga como front-end, se divulgar como Mobile Developer pode lhe dar uma resultado melhor.
- Níveis de senioridade. Ex: estagiário/trainee, júnior, pleno, sênior, especialista
- Faixa salária respectiva de cada senioridade

Espero ter ajudado.
Boa sorte e bom trabalho, fica com Deus.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
