### ISSUE TITLE
[SP] Front-end Developer Jr no Grupo GPS

### ISSUE THREAD

**Issue by araujovicthor** [frontendbr/vagas#7018]
[SP] Front-end Developer Jr no Grupo GPS

## Descrição da vaga
Exemplo: Implementar, testar e manter interfaces responsivas focadas na interação do usuário assim como buscar e propor novas soluções e também interagir com pessoas envolvidas para a criação do melhor produto/resultado.

## Local
SP - Home office

## Requisitos
**Obrigatórios:**
- ReactJS
- Javascript ou Typescript (Preferencialmente)
- HTML5, CSS3
- Git
- Preocupação com interfaces e experiência do cliente
- Integração com API's

**Desejáveis:**
- React hooks
- Next.js
- styled-components, SASS ou LESS
- Testes de frontend
- Técnicas de SEO
- PWA
- CI/CD
- Metodologias ágeis

**Ficaríamos impressionados se você soubesse:**
- Micro-frontend
- GraphQL
- Criação de bibliotecas

## Benefícios
- Assistência médica e odontológica
- VR/VA

## Contratação
CLT

## Como se candidatar
Por meio do aplicativo corporativo GPSvc

## Labels
Desenvolvimento de Software, Programação Funcional, Responsividade, Frontend, Interação entre equipes, Métodos ágeis, Testes.

## Alocação
Remoto

## Regime
CLT

## Nível
Júnior

![Front-end](https://user-images.githubusercontent.com/33492333/171279802-763d7aed-8642-4f18-a485-150d2b8ff0a2.png)

**Comment by Luis-Paulo-Silva-Reis** [comment]
Fiquei bastante interessado

Em ter., 31 de mai. de 2022 18:32, Gabriel Borel ***@***.***>
escreveu:

**Comment by santosant** [comment]
Estou buscando vagas com stack Next.js , GraphQL ou Node.js.
Fiz a inscrição no app, mas não sei se corresponde ao que está na imagem, na lista não tinha informações sobre a vaga Front-End. 

De qualquer forma agradeço a disposição em anunciar a vaga e meus contatos estão no perfil, agradeço!

**Comment by J-DouglasLira** [comment]
Acho que seria interessante disponibilizar um e-mail para enviar o curriculum para pessoas que não têm android.

**Comment by Mraimundo** [comment]
Estou interessado na vaga quais são os passos para se candidatar?

**Comment by CaioMendes7** [comment]
Adorei, estou a disposição para se candidatar

**Comment by muricristiano** [comment]
Boa Victhor! @araujovicthor

**Comment by J-DouglasLira** [comment]
> CV para me

Obrigado Victhor! CV Enviado :)

**Comment by Sh4kaa** [comment]
Bom dia
[DarioDev.pdf](https://github.com/frontendbr/vagas/files/8833419/DarioDev.pdf)

segue meu currículo, pois não consegui me candidatar na vaga

**Comment by viniciosragazzi** [comment]
O App esta dando um erro ao tentar confirmar a inscrição. Mas desde já, agradeceria se aceitasse em **_anexo por aqui._** 
[ViniciosRagazzi.pdf](https://github.com/frontendbr/vagas/files/8835822/ViniciosRagazzi.pdf)

**Comment by Vitor545** [comment]
Obrigado pela oportunidade, currículo enviado.
