### ISSUE TITLE
[Remoto] Front-end Developer na Get In, Ambev

### ISSUE THREAD

**Issue by fernandogielfi** [frontendbr/vagas#7019]
## Nossa empresa
A [**Get In**](https://jobs.kenoby.com/getin#sobre) oferece soluções ao mercado de bares e restaurantes. Garantimos a tecnologia necessária para proporcionar aos consumidores uma experiência cada vez melhor. Somos parte da [**Z-Tech**](https://ztech.net/), o hub de inovação da Ab-Inbev. 

## Descrição da vaga
Você será responsável pelo desenvolvimento e manutenção dos projetos frontend e também dos pacotes de componentes, como o nosso próprio design system e demais pacotes que poderão surgir.

Também irá participar de reuniões com o time de design para ajudar a criarmos as melhores experiências para os usuários.

## Local
Remoto ou Escritório (Rua Amauri, 227 - São Paulo/SP)

## Requisitos

**Obrigatórios:**
- Conhecimento em Javascript ES6+.
- Conhecimento em ReactJS e Typescript.
- Conhecimento em HTML Semântico e CSS.
- Experiência com NextJS.
- Experiência com Styled Components.
- Experiência com versionamento de código.
- Experiência em testes utilizando Jest e React Testing Library.

**Desejáveis:**
- Experiência em Redux e Redux Saga.
- Conhecimento em Cypress.
- Experiência em SSR.
- Familiaridade com CI/CD.
- Conhecimento em bibliotecas novas e com potencial, como por exemplo: React Query.

## Benefícios
- Assistência Médica e Odontológica com coparticipação pela Porto Seguro.
- Cartão Flash (R$ 600,00) para utilização em restaurantes e supermercados.
- Seguro de vida.
- Vale-Transporte.
- Estacionamento com coparticipação.
- Gympass.
- Assessoria jurídica, financeira, social e psicológica.
- Descontos em produtos Ambev.

**Diferenciais:**
- 100% remoto para o Brasil todo, e escritório aberto para te receber se preferir aqui no Itaim.
- Frigobar com refrigerante sempre cheio, e frigobar de bebidas alcólicas liberado depois das 6pm todo dia no escritório!
- Sala de jogos .
- Vestiário com chuveiro. 🚴
- Horário flexível.
- No dress code.

## Contratação
CLT.

## Como se candidatar
[Por favor envie seu pelo link.](https://jobs.kenoby.com/getin/job/pessoa-desenvolvedora-front-end-react-pleno/628bf22f6bae7c7caed9dad5?utm_source=website)

## Tempo médio de feedbacks
Costumamos enviar feedbacks toda semana, nas sextas.
E-mail para contato em caso de não haver resposta: fernando.gielfi@ztech.net

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
