### ISSUE TITLE
[Uberlândia] Front-End Developer na [Zup]

### ISSUE THREAD

**Issue by Rodolpho16** [frontendbr/vagas#702]
## Descrição da vaga

Como Front-End Developer na Zup, você será responsável pelo desenvolvimento dos produtos mais inovadores do mercado, desenvolvendo telas que façam brilhar os olhos de milhares de usuários e proporcionar uma experiência única! Para isso, você vai trabalhar com as tecnologias mais atuais em um ambiente colaborativo, cheio de gente boa e inovador ao extremo!  

## O que você precisa saber:

Domínio de HTML, CSS, JS (não é Jquery);
Conhecimentos de SASS, LESS ou outro Pré-Processador de CSS;
Integrações com APIs REST e Webservices;
Style guides;
Padrões de Projeto;
Conhecimento de sistema de GRIDs;
Experiência com versionamento GIT/SVN, preferencialmente GIT;
Conhecimento em algum framework, Angular I/II, React, VueJS, Elm, ...;
Conhecimento em alguma framework de CSS (Boostrap, Foundation, Skeleton, Pure, Material Design ou outro);
Conhecimento de automatizador de tarefas (Grunt, Gulp, Webpack,...);
Experiencia com Design Responsivo (mobile first);
SEO;

## E será um diferencial se tiver:

Experiência em Metodologias ágeis;
Testes Unitários, Jest, Jasmine, AVA e outros;
Conhecimento de UI/UX;
Conhecimento de NodeJS;
Conhecimento de versões de JS, ES5, ES2015, ES6;
Conhecimento de BackEnd (para melhor iteração entre as partes);
Saber manusear algum software de edição de imagem;
Noção de áreas de TI (servidor, banco de dados, redes, etc.);
Conhecimentos de Perfomance;
Conhecimento de padrões de desenvolvimento de CSS (BEM, OOCSS, SMACSS, Atomic CSS);

## Local

Nosso escritório em Uberlândia (MG)! Dá uma olhadinha:
![new-zup-ubt-151](https://user-images.githubusercontent.com/25387136/33903261-fcc60b28-df5e-11e7-9eaa-9d813a906ec2.jpg)
![new-zup-ubt-108](https://user-images.githubusercontent.com/25387136/33903262-fce9d6ca-df5e-11e7-8587-05bc41c7c34f.jpg)

## Benefícios

- Plano de saúde
- Plano Odontológico
- Seguro de vida
- VR de R$ 453,20
- Auxílio creche
- Verba anual de treinamento
- PLR 
- Plano de celular

## Diferenciais

- A sede mais cool do Brasil!
- Sala de jogos

## Contratação

CLT

## Nossa empresa

Quer saber mais sobre nossa empresa? Acesse esse link aqui (jobs.kenoby.com/zup)  **;)**

## Como se candidatar

É só acessar esse link ai em cima e enviar seu currículo. Estamos ansiosos para ver!

**Comment by jvcjunior** [comment]
Possibilidade de remoto?

**Comment by eduardoJoseRibeiro** [comment]
Show!

**Comment by dallington** [comment]
Tem expectativa de vagas para Júnior ?

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by leonardovilarinho** [comment]
Olá@Rodolpho16

você sabe me falar se a empresa tem disponibilidade para contratação remota?

Mesmo que seja por um período. Sou de Ituiutaba, 180KM de Uberlândia, então poderia ir algumas vezes no mês.

Tentei entrar em contato com a empresa mas sem sucesso.

**Comment by Rodolpho16** [comment]
@leonardovilarinho no momento a contratação é apenas CLT :/

**Comment by marlonmleite** [comment]
@LFeh Sim, aqui temos vagas o ano todo hehe

**Comment by dallington** [comment]
Tem expectativa de vagas para Júnior ?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
