### ISSUE TITLE
[São Paulo] Front-end Developer na Tech For Soluções em TI

### ISSUE THREAD

**Issue by renatasaranz** [frontendbr/vagas#7020]
"Front-End Developer" Angular

Exemplo: `[São Paulo] Front-End Developer na NOME DA EMPRESA`
==================================================
-->

> Vaga Remota durante a pandemia

## Tech For Soluções em TI

A Tech For, Consultoria de Tecnologia da Informação, há 13 anos no mercado e especializada em soluções inteligentes e referência na entrega de serviços de alta qualidade.

## Descrição da vaga

Oportunidade para Engenheiro de Sistemas Angular para cliente da rede varejista de eletrodomésticos e eletroeletrônicos.

## Local

Remoto full. 

## Requisitos

**Obrigatórios:**
- 4 anos de experiência com Angular, Javascript, HTML, CSS;
- 3 anos de experiência com Node.js;
- Experiência com SOLID, Clean Code.

**Diferenciais:**
- Familiaridade com Jira, Bitbucket e Confluence.

## Contratação

PJ - Prazo indeterminado

## Como se candidatar

Por favor envie um email para rsaranz@techforti.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Angular

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após cada processo.
E-mail para contato em caso de não haver resposta: rsaranz@techforti.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by DanielKitanaxiFilipe** [comment]
enviado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
