### ISSUE TITLE
[Remoto] Pessoa Desenvolvedora Especialista I Front End (E-commerce) no Grupo Boticário

### ISSUE THREAD

**Issue by neysimoes** [frontendbr/vagas#7021]
## Descrição da vaga

Nosso espírito inquieto nos faz estar sempre de olho nas tendências futuras. A tecnologia é fundamental para revolucionar toda a nossa jornada, da pesquisa e desenvolvimento de produtos até a venda final para nossos consumidores - e é através dela que estamos construindo o maior ecossistema de beleza do mundo.

﻿Cada novo processo, cada novo lançamento e cada nova solução exigem eficiência, habilidade e inovação. Só assim é possível manter a velocidade e o dinamismo do nosso crescimento e entregar beleza em cada canto do Brasil e em mais de 15 países. E é isso que o time do [gb.tech](http://gb.tech/) está fazendo no Grupo Boticário.

## Local
Remoto

## Responsabilidades e atribuições
Responsável por implementar as melhores soluções de frontend para nossos clientes de forma colaborativa, visando sempre a qualidade, performance, melhores práticas de programação, simplicidade e melhor experiência de uso para nossos produtos;
Responsável por desenvolver, realizar testes unitários, implantar e monitorar além de garantir a qualidade e boas práticas de programação;
Aprimorar aplicações identificando oportunidades de melhoria, fazer recomendações, projetar e implementar sistemas; Ter o sentimento de dono participando das decisões na implementação dos produtos;
Melhorar a qualidade do sistema identificando problemas e padrões comuns, além de desenvolver procedimentos operacionais padrões;
Manter, melhorar e revisar códigos existentes através de Code Review e Pair Programming;
Manter bom relacionamento buscando soluções inovadoras para os projetos;
Investigar e usar novas tecnologias quando relevante.. Manter documentação atualizada;
Possuir habilidades de comunicação e capacidade de trabalhar de forma colaborativa;
Paixão por resolver problemas e fornecer soluções viáveis.

### Requisitos e qualificações
- Vasto conhecimento em HTML, CSS, Javascript, React, Node, Git, Design Patterns
- Testes unitários e testes integrados (Jest e Cypress)
- Ferramentas de Build (Webpack)
- Integração via APIs Rest e GraphQL
- Conhecimento em Metodologias Ágeis. Ferramentas de monitoria (ex: New Relic, Sentry)
- Pixel perfect;. HTML semântico
- Conhecimento básico de SEO e acessibilidade

### Diferencial
- Experiência com GraphQL. Design System. Micro FrontEnd. NextJS;
- Conhecimentos avançado em SEO e acessibilidade.

## Benefícios
Nos preocupamos com o bem-estar das nossas pessoas, por isso oferecemos benefícios flexíveis que permitem uma vida mais saudável e completa.

- Jornada de Trabalho tem carga horária flexível e sustentável;
- Day Off de Aniversário;
- Férias Antecipadas;
- Feriados emendados e folgas em feriados judaicos;
- Bônus anual até 3 salários

**Saúde:**
- Licença parental igualitária: Para as mães de 120 dias com possibilidade de ampliação para 180 dias e para pais de 120 dias em decorrência do Programa Empresa Cidadã.
- Plano de Saúde;
- Plano Odontológico;
- Seguro de Vida;
- Previdência;
- Gympass;

**Vales:**
- Vale Alimentação, com um bônus no Natal;
- Vale Refeição;

**Auxílios:**
- Auxílio pet;
- Auxílio babá ou creche ou escola
- Auxílio Home Office;

**Extras:**
- Desconto de até 40% em nossos produtos;

## Regime
CLT

## Nível
Sênior/Especialista

## Inscrições
O Grupo Boticário promove a diversidade e queremos conosco pessoas que mudem o jogo e façam bonito, independente de sexo, raça, orientação sexual, religião, nacionalidade, idade ou deficiência.

Se identifica com o nosso jeito? Então vem fazer beleza com a gente!

Para participar do processo, é importante realizar a aplicação diretamente pelo link da vaga: https://grupoboticario.gupy.io/job/eyJqb2JJZCI6MTI2NjAyMiwic291cmNlIjoiZ3VweV9wdWJsaWNfcGFnZSJ9

Após isso, realizaremos a triagem de perfis e caso o seu esteja aderente, iniciaremos o processo :)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
