### ISSUE TITLE
[Remoto] Front-end Vue.Js Developer (PLENO) na FS GESTÃO RH

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#7028]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-frontend-typescript-javascript-vuejs-pleno-184816626?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>A FS GESTÃO RH</strong> busca pessoa <strong>Frontend Vue.js Developer</strong> para compor seu time!</p>
<p>Somos uma Consultoria de Recursos Humanos com perfil generalista, atuando em todos os subsistemas da área e oferendo soluções para empresas e negócios de pequeno, médio e grande porte.</p>
<p><strong>Atividades e responsabilidades da posição:</strong></p>
<ul>
<li>Trabalhar com equipe de desenvolvimento para idealizar soluções;</li>
<li>Desenvolver novos projetos;</li>
<li>Compartilhar conhecimento e exercer liderança técnica;</li>
<li>Criar testes unitários para novas funcionalidade e legado sempre que possível;</li>
<li>Criar front-end de novas páginas baseado em layout previamente desenvolvido;</li>
<li>Buscar aprimoramentos para os sistemas atuais;</li>
<li>Code Review e estruturas de qualidade de código (clean-code).</li>
</ul>

## FS GESTÃO RH: 
 <p>Somos uma Consultoria de Recursos Humanos com perfil generalista, atuando em todos os subsistemas da área e oferendo soluções para empresas e negócios de pequeno, médio e grande porte.</p>
<p>Nosso FOCO está nas PESSOAS, na ORGANIZAÇÃO e no SUCESSO!</p><a href='https://coodesh.com/empresas/fs-gestao-rh'>Veja mais no site</a>

 ## Habilidades: 
 - Javascript 
- Typescript 
- Vue.js
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência prévia em Typescript, Javascript (ES6/ES7) e Vuejs 2 e 3; 
- CSS e CSS Extension Languages (Stylus, SASS, LESS); 
- State management (VUEX); 
- Vue router; 
- Bundlers (webpack) e LazyLoaders; 
- Teste de software e2e com Cypress; 
- Inglês Intermediário; 
- Experiência com ferramentas de versionamento de código (GIT); 
- Conhecimento em metodologias ágeis (Scrum/Kanban);

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Front-end Vue.Js Developer (PLENO) na FS GESTÃO RH](https://coodesh.com/vagas/desenvolvedor-frontend-typescript-javascript-vuejs-pleno-184816626?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
