### ISSUE TITLE
[Remoto] Front-end Developer Sênior na aiqfome

### ISSUE THREAD

**Issue by monicapio** [frontendbr/vagas#7029]
## Nossa empresa ##
aiqfome
Somos a primeira e a maior plataforma de delivery online para restaurantes 100% brasileira, levando tecnologia e a melhor experiência em entrega pra todo o interior do Brasil!

Somos parte do Grupo Magazine Luiza, compartilhando o sonho de digitalizar todo o Brasil e trazer tecnologia pra todo mundo!

A gente se reinventa a todo momento e estamos revolucionando o mercado local de delivery, sem abrir mão de um valor inegociável: tratamos os outros como gostaríamos de ser tratados, criando soluções únicas e proporcionando a melhor experiência possível sempre, pra todo mundo envolvido!

Ah, e o mais importante: nos divertimos MUITO enquanto fazemos tudo isso!

Por isso, atenção: só contratamos pessoas legais 😉💜

## Descrição da vaga ##

Principal missão: Fazer parte do nosso time de magos do frontend capaz de tranformar códigos na melhor experiência de delivery que esse BR já viu. Ser um verdadeiro cientista em nosso laboratório, testando novas ideias constantemente, sem medo de errar! Unimos neurônios e memes diariamente para entregar um produto que amamos, sem deixar de compartilhar as últimas novidades do universo Dev e do zapzap.

**Coisas que você precisa fazer pra mandar muito bem aqui:**

- Participar de análises junto ao time, quanto as sugestões de melhorias dadas por fominhas, restaurantes, fomers e hunters;
- Prezar por códigos com eficiência e qualidade, com visão macro de possíveis impactos em processos já existentes;
- Transformar protótipos em lindas páginas funcionais;
- Ser a referência técnica dentro do projeto;
- Compartilhar conhecimento e boas práticas de desenvolvimento;
- Colaborar com o planejamento de entregas;
- Se aprofundar em nossos produtos e atuar em colaboração com outras áreas;
- Se envolver no processo de avaliação técnica de novos candidatos;
- Pesquisar e se atualizar sempre sobre novas tecnologias.

**Requisitos**
**Antes de qualquer coisa, você precisa ser MUITO gente boa e teamplayer!**
**Mas também é importante que tenha:**

- Experiência com desenvolvimento front-end;
- Sólidos conhecimentos em JavaScript, CSS, React e Git;
- Experiência em construir e integrar páginas com dados vindos do back-end;
- Manjar de testes para front-end;
- Boas práticas em desenvolvimento de software;
- Gostar de transmitir conhecimento pro restante da equipe;
- Experiência em usar ou desenvolver um design-system;
- Proatividade para encontrar soluções alternativas/eficazes - e não só as saídas mais fáceis!
- Costume de pesquisar e se atualizar sobre novas tecnologias e negócios.

**Será um diferencial:**

- Experiência prática em construir aplicações com dados em real-time;
- Conhecimento em Vue;
- Conhecimento em Next;
- Contato com métodos ágeis como Scrum ou Kanban;
- Inglês básico.

**Contratação**

- CLT

**Benefícios**

- Opção de trampo full remoto
- Bônus por metas atingidas
- Cupons mensais pra pedir no aiq
- Descontos em cursos
- App de saúde mental (terapia online)
- Plano odontológico
- Plano de saúde
- Vale alimentação
- Vale transporte
- Seguro de vida
- Dois monitores pra trabalho
- Cafézin expresso e moído na hora
- Uma cultura de autonomia e diversidade
- Não temos nenhum dress code
- E a chance de você crescer aqui dentro é imensa!

**Nível**

- Sênior

**Como se candidatar**
Se inscreva na vaga [aqui](https://aiqfome.gupy.io/jobs/1985676)

**Comment by DevCleverton** [comment]
Up disponível!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
