### ISSUE TITLE
[DIVERSOS] Front-End Developer na Codeminer42

### ISSUE THREAD

**Issue by abnersajr** [frontendbr/vagas#703]
## Descrição da vaga

Buscamos Front-end developers para atuar nos diversos projetos, inclusive projetos internacionais com clientes estrangeiros. Temos diversos projetos, com diversos frameworks e tecnologias, então entre em contato.
Estamos procurando pessoas de todo os níveis para fazer parte de nosso time, sem diferenças nem preferências. Todos são bem vindos.
## Local

A Codeminer42 está presente atualmente em 10 estados do país. 
Temos vagas para todos eles. 
- São Paulo
- Campinas
- Sorocaba
- Batatais
- Guarapuava
- Novo Hamburgo
- Anápolis
- Goiânia
- Teresina
- Natal
- Santa Maria
- Florianópolis
- Belo Horizonte

OBS: Presencialmente apenas

## Benefícios
1. Plano de saúde e dental;
2. Auxílio transporte;
3. Vale-refeição;
4. Ambiente de trabalho descontraído;
5. Acesso a cursos e portais de educação como Front-end Masters e egghead.io;
6. Curso de inglês para aperfeiçoamento.

#### Diferenciais

- Horário flexível
- Oportunidade de trabalhar em projetos nacionais e internacionais 

## Requisitos

**Obrigatórios:**
- Experiência com React
- Ou React Native
- Ou VueJS
- Ou todos eles
- Testes Unitários
- Inglês Intermediário, temos clientes internacionais, logo o candidato tendo um nível de compreensão e conversação legal podera estar entrando em um projeto internacional. Lembrando que o inglês não precisa ser 100%. Por isso fazemos uma entrevista para ver como você se sai.

**Desejáveis:**
- conhecimentos em ruby on rails
- conhecimentos em NodeJS

## Contratação

CLT, valores depende do seu nível

## Nossa empresa

A Codeminer 42 é uma butique de software brasileira focada em entregar o melhor valor a seus clientes. Nós começamos a operar em Setembro de 2011 e até agora expandimos para 10 cidades diferentes no Brasil com os melhores profissionais do Brasil.

Nossa especialidade é desenvolvimento web com Ruby on Rails e seu ecossistema satélite - que inclui as melhores tecnologias de ponta -, nós temos muita experiência em todos os tipos de produtos de tecnologia como e-commerces, e-learning, redes sociais, gerenciamento de conteúdo, automação de processos.

Trabalhamos para empresas pequenas ou grandes, temos diversos tipos de serviços que vão de ciclo de vida de desenvolvimento de projetos do zero, resgate de projetos legados, terceirização e assim por diante.

Se quiser ter não somente uma boa aplicação web em produção mas também melhorar seus processos de software, garantia de qualidade, podemos ajudar.

## Como se candidatar

Por favor envie um email para become@codeminer42.com com seu CV anexado, github, site pessoal e demais infos.
No Assunto coloque [CIDADE] Vaga para Front-end .
Maiores dúvidas, podem usar a issue ou enviar para abner.alves@codeminer42.com

**Comment by carloshenriqueribeiro** [comment]
Tem vaga pra Jr ?

Carlos Ribeiro

**Comment by abnersajr** [comment]
Opa @carloshenriqueribeiro tem sim cara, tendo os requisitos acima até estagiários são bem vindos.  Não deixe demandar seu email ;)

**Comment by Biciato** [comment]
Tenho experiência em Rails so :/

**Comment by abnersajr** [comment]
@Biciato temos vagas para Rails também, não postem aqui especificamente pois é o grupo do Front-end Brasil, mas pode mandar também Apenas bote Banc-end Developer no lugar 👍

**Comment by phsantiago** [comment]
Já tive oportunidade de trabalhar em conjunto com o pessoal da Codeminer42, até junto com o @abnersajr e eles mandam muito bem!

**Comment by danielswater** [comment]
Angular2/4 tem algo?

**Comment by matheus-rosin** [comment]
Arriscar não custa rs
Tem algo para JS puro, sem experiência?

**Comment by abnersajr** [comment]
@matheus-rosin não temos nada específico para JS puro, pois todos os projetos acabam usando algum framework. E também no momento não temos vaga em Curitiba, apenas em algum dos estados citados acima.

@danielswater hoje não buscamos profissionais com conhecimentos em Angular, mas se você aprendeu Angular, facilmente irá aprender algum dos outros frameworks. ;)

**Comment by igorcap** [comment]
Não moro em nenhuma dessas cidades mas to disposto a me mudar. Mandei lá, vai que :)

**Comment by joordas** [comment]
Mandei lá, tô bastante interessado nessa! hehe

**Comment by eliasmelgaco** [comment]
Opa !

Tem vaga Ember ?

**Comment by abnersajr** [comment]
Opa @eliasmelgaco não temos vaga para framework específico. Temos uma maior demanda de projetos em React, VueJS, mas pode entrar em contato, pode fazer o teste em ember, aqui você tera a oportunidade e material para estudar os demais e estar encaixando em algum dos nossos vários projetos, mande seus dados no e-mail para darmos continuidade se tiver interessado.

**Comment by eliasmelgaco** [comment]
Beleza @abnersajr 

Agora estou em viagem, mas, assim que voltar mandarei o e-mail sim. Valeu!

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by abnersajr** [comment]
@LFeh sim aberto ainda, estamos sempre tem espaço para mais um no nosso time.

**Comment by LFeh** [comment]
Boa

**Comment by thenewbiemaster** [comment]
possibilidade de remoto conforme label?

**Comment by abnersajr** [comment]
Não vi que estava com esse label, na verdade não temos disponibilidade de remoto.

**Comment by abnersajr** [comment]
Galera, passando aqui para movimentar o post e dizer que continuamos com vagas abertas. Não sinta-se acanhado. No mínimo você irá receber um feedback para melhorar caso tenha algo, o que é de extrema importância.

**Comment by abnersajr** [comment]
Galera, estamos buscando pessoas em Florianópolis/SC também. Issue criada hoje #959 
E as vagas dessa issue continuam em aberto.

**Comment by vititu** [comment]
Pena não ter no Rio de Janeiro! 😢

**Comment by dan-liberato** [comment]
Tem vaga para Jr em Sorocaba ou Campinas?

**Comment by abnersajr** [comment]
@dan-liberato tem sim, só mandar e-mail que você será redirecionado para a galera correta e dar continuidade.

**Comment by rafamaiach** [comment]
Boa tarde @abnersajr ao enviarmos para o email usando uma cidade no assunto, é possível receber informações sobre outras localidades também? Obrigado.

**Comment by abnersajr** [comment]
Olá @rafamaiach obrigado pelo interesse desde já.
Todas as cidades que temos oportunidades estão na descrição da vaga.
São as cidades que temos escritórios.
Você pode mandar para become@codeminer42.com seu e-mail de qualquer forma.

**Comment by thiagocruzrj** [comment]
Vaga de Jr. ainda disponível ?

**Comment by abnersajr** [comment]
Ola @thiagocruzrj sim, temos vagas em todos os escritórios citados na vaga :+1: só entrar em contato :)

**Comment by abnersajr** [comment]
Pessoal estamos ainda em busca de pessoas de todos os níveis :+1: qualquer coisa pode entrar em contato com become@codeminer42.com ou mandar para mim abner.alves@codeminer42.com com dúvidas o que for. Só relembrando nossos escritórios estão acima e tem o de **Florianópolis e Santa Maria** que não estão inclusos na lista.

**Comment by abnersajr** [comment]
Ola @EdipoNascimento não temos vaga específica para Q.A.
A Codeminer preza por bons códigos e temos um canal específico para pedir review e ajudar nos reviews em projetos.

Mas não hesite em entrar em contato. Temos diversas oportunidades e com certeza essa sua skill agrega valor :smile: 
Aguardo seu contato mestre.

**Comment by abnersajr** [comment]
Olá @FelipeMD. Dependendo do escritório que tiver interesse temos sim.
Mande seu contato para mim no abner.alves@codeminer42.com
Com Linkedin se tiver e demais infos sobre você :+1:
