### ISSUE TITLE
[São Paulo] FRONT-END MOBILE REACT NATIVE PLENO na Gras Tech

### ISSUE THREAD

**Issue by HenriqueHolzer** [frontendbr/vagas#7031]
## Nossa empresa

Gras Tech é uma startup paulista de tecnologia digital, criada para otimizar a seguinte prestação de serviços: a captura, coleta e distribuição de dados pertinentes a postos de combustíveis.

Dentre esses dados, estão: localização de postos, tipos de combustíveis comercializado por cada posto, pesquisa de preço, qualidade de combustível, índice de confiança do consumidor e amenidades.

Tudo isso, visando a maior área de cobertura e a maior rapidez na atualização dos coletados.

O objetivo principal da Gras Tech é possibilitar à comunidade usuária de postos de gasolina uma maior assertividade em suas escolhas, melhorando a experiência do usuário e a economia do consumidor.

A Gras Tech investe bastante em inovação, buscando sempre as tecnologias mais inovadoras para a coleta e distribuição dos referidos dados.

O time Gras Tech é formado por uma equipe sênior de gestores, especialistas na área de postos de gasolina e uma equipe altamente qualificada na área de tecnologia da informação.

## O que esperamos de você

- Jogar com o time, nossas forças somadas se multiplicam;
- Startup mindset;
- Todo o dia, seremos melhores do que ontem, pensando como podemos ser mais rápidos, satisfazer ainda mais nossos clientes e criar coisas que ninguém ainda não fez;
- Participar das discussões do negócio, não apenas na sua área técnica;
- Vamos trabalhar duro, sermos felizes em um ambiente alegre e com alto nível de entregas e compromissos com nossos clientes;

## Local

Escritório, São Paulo - SP

## Requisitos

**Obrigatórios:**

- Experiência com React ou React Native, NodeJS, Git;
- Experiência com Redux, Redux Persist e Redux Sagas;
- Experiência com desenvolvimento de aplicativos móveis;
- Prática de code review/pull request;
- Experiência com testes automatizados;
- Experiência em integração com API’s REST;
- Experiência com componente funcional (React hooks);
- Utilização de boas práticas de desenvolvimento de software (utilização de design patterns, clean code, segurança, tratamento de erros, reutilização de código);
- Experiência com metodologias ágeis.
- Pragmatismo para resolução de problemas;
- Comunicação estruturada baseada em fatos e dados;

**Diferenciais:**

- Experiência em aplicação de boas práticas e processos de UX
- Experiência com otimização de performance;
- Experiência com Design System;
- Typescript;

## Contratação

PJ

## Como se candidatar

Por favor envie um email para luizgustavo@combux.com.br com seu CV anexado - enviar no assunto: Vaga FRONT-END MOBILE REACT NATIVE

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
