### ISSUE TITLE
[Remoto] Front-End React.js Developer SENIOR na Bix Tecnologia

### ISSUE THREAD

**Issue by igormsg** [frontendbr/vagas#7033]
A BIX Tecnologia está com vagas de trabalho remoto abertas para todo o Brasil! Procuramos pessoas desenvolvedoras React JS Sênior.

#vemprabix

Você fará parte de uma equipe altamente capacitada e participará de projetos de desenvolvimento de sistemas relevantes para empresas líderes de mercado.

O que esperamos ver em você:

- Integridade;
- Cuidado com as pessoas;
- Transparência;
- Facilidade em comunicação - escrita e oral;
- Senso de equipe;
- Responsabilidade;
- Proatividade, analítico e autodidata;
- Raciocínio lógico;
- Resolução de problemas.

O que esperamos que você tenha:

- Mais de 3 anos de experiência com React JS;
- Experiência em arquitetura e design de software;
- Conhecimento de negócios: capacidade de gerar valor e resolver problemas de grandes empresas por meio de tecnologia;
- Conhecimento avançado de frameworks de desenvolvimento web;
- Inglês avançado ou fluente.

O que será um diferencial se você tiver:

- Conhecimentos em Web3.

O que você fará em seu dia a dia:

- Desenvolvimento de software de autenticação em eventos usando tecnologia NFT;
- Integração em squads de projetos multidisciplinares, seguindo processos de gestão de projetos de software definidos;
- Dar e receber code reviews de seus pares / gestores;
- Se você leu até aqui, basta se inscrever nesse link: [https://bit.ly/bix-frontend](https://bit.ly/bix-fronted)
- Contato direto com o cliente e oportunidade de resolver problemas de transformação digital em grandes clientes.

O que oferecemos:

- Cartão de benefícios flexíveis;
- Plataforma com psicólogos, nutricionistas, clínico geral e cursos;
- Trabalho 100% remoto;
- Plano de saúde e Odontológico nacional;
- Plano de carreira acelerado;
- Participação nos resultados;
- Contato direto com líderes de grandes empresas;
- Ambiente diferenciado (Hora BIX, integrações e Happy Hours,
- Programa de Mentoria, Reuniões 1on1);
- Aulas on-line de inglês (cambly);
- Folga no aniversário.

Labels: clt/pj; remoto; senior

**Comment by PedroBarbosaSw** [comment]
Não consegui completar o segundo desafio, aparentemente deu um bug no app e eu não conseguia executar meu código.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
