### ISSUE TITLE
[Curitiba] Dev Javascript PL/SR @ CooperPlace

### ISSUE THREAD

**Issue by NovareRH** [frontendbr/vagas#7034]
## Nossa empresa

﻿ A Coopercarga é um Operador Logístico com mais de 30 anos, voltado para soluções que resultem em sucesso para seus clientes, ao mesmo tempo em que gera produtividade aos associados, promovendo o desenvolvimento da comunidade e preservando o meio ambiente.
﻿A Cooperplace é um braço do grupo Coopercarga que desenvolve o produto de tecnologia para ser um setor de transformação digital da empresa. ﻿

## Local

[Curitiba] [Híbrido]

## Requisitos

 - Conhecimentos e habilidades em algoritmos e estruturas de dados;
 - Domínio de engenharia de software, princípios, boas práticas e padrões de arquitetura;
 - Experiência com desenvolvimento de Aplicações Escaláveis;
 - Liderança 
 - Negociação
 - Pensamento Crítico
 - Paciência
 - Resolução de Problemas
 - Responsabilidade
 - Metodologias Ágeis - Scrum, Kanban

## Tecnologias

 - HTML, CSS, JavaScript, React Native, Node js
 - Banco de Dados: SQL Server
 - Framework: Adonis, Express
 - Typescript
 - Biblioteca: Next js

## Responsabilidades

- Manter a plataforma no ar, e sempre em constante melhoria.﻿

## Tarefas

- Será responsável por liderar e coordenar as atividades e os artefatos técnicos no decorrer do projeto, desenvolver documentações de padrões de arquitetura, estabelecer a estrutura geral de cada visão de arquitetura.
- Antecipar gargalos de performance da aplicação, e problemas de arquitetura que resultam em risco ou improdutividade para o desenvolvimento;
- Contribuir ativamente para a redução de caos, ruído e débito técnico nos sistemas;
- Manutenção em banco de dados SQL Server,
- Tuning de banco de dados;
- CI/CD de aplicações node;
- Deploy de aplicativos Mobile;
- GitFlow;
- Codificação de melhorias e novas funcionalidades na plataforma digital da Coopertech;
- Arquitetar e documentar novas funcionalidades;
- Gestão do time de desenvolvimento.

## Formação
- Ensino médio completo com cursos especializados em tecnologia.

## Contratação

- A partir de 7k - CLT

## Benefícios
- Cartão Flash - R$ 600,00
- Assistência Médica Unimed Nacional com co participação
- Gympass﻿﻿﻿﻿

## Como se candidatar

Aplique para a vaga [por aqui](https://www.careers-page.com/novare-rh/job/8XY6VWV) .

#### Alocação
- Presencial

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
