### ISSUE TITLE
[Niterói-RJ / Remoto] Front-end Developer na VX Comunicação

### ISSUE THREAD

**Issue by diogocaldas** [frontendbr/vagas#7037]
## Sobre a VX

Somos uma agência de publicidade do Rio de Janeiro (aqui de Niterói ou Nikit City), presente no mercado desde 2002. De inovação e planejamento estratégico a gente entende: se você está em busca de uma agência web full service expert em estratégias de marketing digital, vem conversar com a gente!

## Descrição da vaga

O profissional será responsável por codificar o resultado do trabalho da equipe de UX na criação de sites, landing pages e newsletters.

## Local

Remoto

## Requisitos

**Obrigatórios:**

- 5+ anos experiência no desenvolvimento de estruturas modernas e designs responsivos utilizando HTML5 e CSS3
- 3 anos de experiência em Javascript (Vanilla e E6+)
- 3 anos de experiência com o framework VueJS
- 3 anos de experiência em SASS
- Vivência no uso de Task Runner (Gulp/Grunt)
- Vivência no uso de padrões de organização de CSS (BEM, RSCSS, ITCSS, SMACSS)
- Vivência no consumo de APIs (Rest)
- Vivência com recortes layouts no Figma e/ou Photoshop
- Vivência com ferramentas de versionamento de código (GIT)

**Desejáveis:**
- Desenvolvimento de temas para WordPress
- Conhecimentos em PHP/MySql

**Diferenciais:**
- projetos opensource

## Benefícios

- Vale refeição
- Vale transporte
- Plano de saúde
- Seguro de vida
- Zenklub
- Academia/Gympass
- Dress code

## Contratação

CLT / PJ

## Como se candidatar

Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: <a href="https://coodesh.com/vagas/desenvolvedor-webfrontend-pleno-174201220">Front-end Developer Pleno</a>

#### Alocação
- Remoto / Híbrido (Niterói - RJ)

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
