### ISSUE TITLE
[São Paulo] Front-End Developer Jr. / AngularJS

### ISSUE THREAD

**Issue by rodrigonovo** [frontendbr/vagas#704]
## Descrição da vaga

Vaga para trabalhar alocado em um dos clientes da [Sinn Tecnologia](http://www.sinn.com.br/) em São Paulo trabalhando com desenvolvimento de SPAs em Angular.

## Local

Escritório, São Paulo - Centro
Não há disponibilidade para Remoto

## Benefícios

- Horário flexível (respeitando a carga mensal de horas)

## Requisitos

**Obrigatórios:**
- Experiência em Angular

**Desejáveis:**

- Ter trabalhado em outros projetos AngularJS
- Ter trabalhado com Angular Material
- conhecimentos em Java e Spring Framework

**Diferenciais:**
- projetos opensource

## Contratação

PJ a combinar

## Como se candidatar

Enviar e-mail para [rodrigo@sinn.com.br](mailto:rodrigo@sinn.com.br) com o título da Issue e o CV anexado.

**Comment by rodrigonovo** [comment]
@LFeh por favor, adicione as labels PJ, Júnior, Alocado. Vlw!

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by rodrigonovo** [comment]
Sim. Aberto ainda!

Grande abraço
-----------------
Rodrigo Porto

HCE-3900 Hitachi Vantara Certified Expert - Pentaho solutions architect
HCE-5910 Hitachi Vantara Certified Specialist - Pentaho Business Analytics
HCE-5920 Hitachi Vantara Certified Specialist - Pentaho Data Integration

2018-01-23 14:21 GMT-02:00 Felipe Fialho <notifications@github.com>:

**Comment by Allves** [comment]
Só para avisar, foram abertas novas vagas na empresa para frontend.

As especificações continuam as mesmas.
Só ressaltando também para os que forem aplicar, não se preocupem com os desejáveis (principalmente a questão do Java), não é um fator eliminatório / obrigatório.

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
