### ISSUE TITLE
[100% Remoto]- Front End Software Developer na Mercado Diferente

### ISSUE THREAD

**Issue by JuliDiferenteTech1** [frontendbr/vagas#7043]
Sobre a Diferente:
 
A Diferente ≠ é uma foodtech que busca democratizar a alimentação saudável para toda a América Latina, com alimentos até 40% mais baratos que mercados tradicionais, enquanto combate o desperdício de comida.
 
Faça parte da construção de uma empresa que já nasce com impacto na sociedade, além de democratizar o acesso e consumo de produtos orgânicos no Brasil. Nosso time é super mão na massa, comprometido em fazer a diferença, resolvendo problemas e trabalhando em conjunto para oferecer soluções positivas ao planeta.
 
Sobre o desafio:
 
Nossos engenheiros de front-end estão focados em garantir uma experiência de compra única para nossos clientes. Temos como princípio ser mobile first experience. Você usará tecnologias e estruturas modernas, como Typescript, React, Rest, e os mais recentes padrões da Web em HTML, CSS, JavaScript, React e Ruby on Rails, para desenvolver grandes aplicativos da Web front-end que escalam e têm bom desempenho em todos os dispositivos. E você desenvolverá nossa experiência de aplicativo através do React Native.
 
Para nossa web app, nosso time trabalha junto com designers e gerentes de produto para criar e lançar novos recursos para nosso aplicativo. Nossas equipes estão trabalhando com o React Native. Você trabalhará em várias disciplinas e ficará empolgado em criar experiências centradas no ser humano.
 
Algumas coisas que gostaríamos que você tivesse:
 
Conhecimento em Javascript, HTML e CSS ou linguagens utilizadas no desenvolvimento mobile (Swift/Objective C, Java, Kotlin).
Para engenheiros de front-end, proficiência com pelo menos um framework/biblioteca de componentes Javascript (Vue, React, AngularJS ou similar) e um forte conhecimento de CSS3 moderno (Flexbox, Grid).
Paixão e curiosidade em aprender constantemente coisas novas; A Diferente muda rapidamente, e precisamos de pessoas que trabalham aqui para poder mudar e aprender rápido também.
Experiência em trabalhar em um ambiente interdisciplinar com designers e outros engenheiros para produzir e avaliar ideias por meio da prototipagem de conceitos iniciais.
 
Seria bom se você tivesse experiência com:

Para desenvolvedores mobile, a experiência com o React Native é boa, mas não é necessária!

O que a Diferente proporciona?

- Plano de saúde SulAmérica sem desconto;
- Plano odontológico OdontoPrev (opcional);
- Seguro de vida;
- Cartão Caju;
- Auxilio home office;
- Licença maternidade e paternidade estendidas;
- Salário competitivo;
- 13° salário;
- Férias Flexíveis;
- Horário Flexível;
- Dayoff de aniversário.

Ah, nosso modelo de contratação é PJ ou CLT com todos esses benefícios.
Você poderá escolher se vai trabalhar de forma 100% remota ou se preferir também poderá ir ao nosso escritório na Av. Paulista.

- Nível: Sênior
- Como se candidatar: Por favor envie seu pelo link https://www.linkedin.com/jobs/view/3101182542
- Tempo médio de feedbacks: Costumamos enviar feedbacks em até 1 semana após cada etapa
- E-mail para contato em caso de não haver resposta: seja@mercadodiferente.com.br

Somos Diferentes ≠:
 
Está vaga está aberta à aplicação de todas as pessoas - independentemente de suas características ou condições humanas quanto à etnia, gênero, orientação sexual, acessibilidade, cultural, social ou de qualquer outro fator. Todas as nossas vagas estão, e sempre estarão, abertas para pessoas com deficiência (PCDs).

#Fazdiferençaserdiferente #sejadiferente🧡🍉🍓🥑🥕

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
