### ISSUE TITLE
[São Paulo] Front-End Developer na DEVPARTNER

### ISSUE THREAD

**Issue by ulyssesneto** [frontendbr/vagas#705]
## Descrição da Empresa e da Vaga

A DevPartner é uma empresa de TI focada em soluções de Gestão de Relacionamento. Hoje nosso principal segmento é o automotivo, porém atendemos outros segmentos também.
Nossas soluções são moduladas para cada necessidade dos nossos clientes, portanto, não somos uma empresa de desenvolvimento de produtos.
Para os desenvolvimentos, utilizamos a plataforma .net, linguagem c# e banco de dados sql server, ambiente windows. Todos os novos desenvolvimentos estão direcionados em MVC e WEBAPI, utilizando interface em **AngularJS**. 
De qualquer forma, temos projetos que damos manutenção em estrutura .net webforms.

**Como foco para esta vaga, necessitamos de um profissional com competência para atuar nos novos desenvolvimentos frontend (ANGULARJS/jquery/html/css) para nossas soluções.**

Nossa missão é ENTREGAR RESULTADO, e portanto, nossos colaboradores são fundamentais para que possamos atingir nossa meta, tendo ativa participação nos projetos e no dia a dia da operação.

O departamento de TI tem os seguintes perfis:
* Designer/Front-End: profissionais com perfil de criação e programação de front-end. É responsabilidade deste perfil realizar a programação em AngularJS
* Desenvolvedor .net: profissionais com perfil de programação .net, com conhecimentos de banco de dados e de html/css/javascript para atuação quando projetos em estrutura MVC (Razor)
* Banco de Dados: profissionais com perfil específicos de banco de dados para atuação em projetos determinados e/ou apoio em projetos que necessitem de procedimentos em banco de dados
* Suporte: Infraestrutura em geral

## Local

Estamos localizados na região do **Campo Belo**, perto do aeroporto de congonhas, em uma estrutura de casa, sede própria.
Por estarmos em uma casa, o ambiente é extremamente descontraído, não deixando de lado nosso profissionalismo.

## Benefícios

- VT
- VR de R$ 17,50/dia
- Auxílio de 50% do Plano de Saúde

#### Diferenciais

- cozinha: servimos café da manhã até às 09h00; além disso, você pode trazer sua comida (marmita) e almoçar na empresa (temos geladeira e microondas)
- sala de jogos
- café da tarde (20 minutos de pausa geral)

## Requisitos

**Obrigatórios:**
- Experiência em projetos com **AngularJS**. Irá atuar nos desenvolvimentos das interfaces dos projetos web

## Contratação

Nosso regime de contratação é a CLT.

## Como se candidatar

Por favor envie um email para vaga.ti@devpartner.com.br com seu CV anexado - enviar no assunto: Vaga AngularJS

**Comment by LFeh** [comment]
Aberto ainda?

**Comment by ulyssesneto** [comment]
Felipe

Boa tarde.

Gostaria de reabrir a vaga. Devo enviar novamente??

Obrigado


On 9 Mar 2018, at 10:47, Felipe Fialho <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #705<https://github.com/frontendbr/vagas/issues/705>.
