### ISSUE TITLE
[Remoto] Front-end Developer na Cuponomia

### ISSUE THREAD

**Issue by mayaracuponomia** [frontendbr/vagas#7054]
## Nossa empresa
SE EXISTIR UM CUPOM DE DESCONTO, ELE ESTARÁ NO CUPONOMIA!
Fundado em 2012 por Antônio Miranda e Vinicius Dornela, o Cuponomia surgiu com a ideia de ajudar as pessoas a economizar em todas as compras online. Fomos pioneiros na divulgação e popularização dos Cupons de Desconto gratuitos no Brasil e em 2019 passamos a oferecer Cashback para todos os nossos usuários. Seguimos focados em nosso propósito: "Nós queremos ajudar todos os consumidores a economizar! O que nos move todos os dias é encontrar as melhores oportunidades para gerar economia de verdade!"

## Descrição da vaga
O Cuponomia surgiu com a ideia de ajudar as pessoas a economizar em todas as compras online. Fomos pioneiros na divulgação e popularização dos Cupons de Desconto gratuitos no Brasil e em 2019 passamos a oferecer Cashback.
Hoje são mais de 10 milhões de usuários que vivenciam essa experiência de economia, utilizando nossos Cupons e Cashback. No último ano o Cashback cresceu mais de 200%, e estamos avançando rapidamente com nossos três produtos, Site, Extensão e App.
Estamos crescendo rapidamente, por isso estão abertas novas vagas na área de Tecnologia.

## Local
Remoto

## Requisitos

**Obrigatórios:**
Proficiência em Javascript (ES6);
Boas noções de layout, escrevendo CSS sem utilizar frameworks e design responsivo;
Noções de SEO;
Noções de Google Analytics (ler eventos, estatísticas de uso);
Noções de Google Tag Manager (criar scripts, gerenciar timing e triggers);
Familiaridade com a nossa stack (.NET MVC, LESS/SASS, [Vue.JS](http://vue.js/));
Familiaridade com frameworks JS modernos ([Vue.JS](http://vue.js/), React, Svelte, Angular etc);
Conhecimento em técnicas de otimização de performance (lazy-loading, code splitting, otimização de assets, etc).

## Benefícios
Plano de Saúde e Odontológico SulAmérica, sem nenhum desconto ou coparticipação para o titular;
Zenklub (plataforma de suporte emocional com psicólogos e coaches online);
Vale refeição de R$30,00/dia no cartão Flash;
Participação nos Resultados;
Horário flexível;
Auxílio creche;
Auxílio para estudo e desenvolvimento (pós-graduação, MBA, inglês, entre outros);
Budget para cursos e livros;
Cashback em dobro;
Convênio com o Sesc;
Seguro de vida; 
Cashback no aniversário;
Prêmio de até R$1.000,00 para indicações assertivas de novos integrantes para o nosso Time.

## Contratação
CLT ou PJ.

## Como se candidatar

Por favor, cadastre-se através do link >> https://cuponomia.gupy.io/jobs/1208501

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
