### ISSUE TITLE
[FULL REMOTE] Consultor(a) Senior Front-end na Avanade

### ISSUE THREAD

**Issue by marcelaamn** [frontendbr/vagas#7056]
## Nossa empresa

Avanade é uma multinacional do segmento de tecnologia, uma joint venture da Microsoft e da Accenture. 

## Descrição da vaga

- Front-End - Angular 
- Mensageria por meio de Kafka / SQS /SNS / Kinesis 
- Event Driven Architecture 
- Saber equalizar problemas x melhor arquitetura para solucionar problemas 
- LGPD 
- Microfrontends 
- Estimar projetos 
- Liderança  
- Desenho de componentes 
- Conceitos avançados de Design Patterns 
- Gerenciamento do estado da aplicação com ngrx NgZone 
- Orquestrar Lazy Load nos modulos da aplicação 
- Otimização dos bundles da aplicação após build Back-End - C# 
- Inversão de Controle com interface Expression Scaffold Entity Framework
- Conhecimentos sobre processos (DevOps, CI/CD, gestão ágil)
- Conhecimentos de SRE

## Local

Totalmente remoto.

## Benefícios

- Vale refeição ou alimentação;
- Vale transporte ou fretado;
- Convênio médico e odontológico
- Telemedicina;
- Telepsicologia;
- Certificações e treinamentos;
- Seguro de Vida;
- Previdência Privada;
- Inglês;
- Avababy: acompanhamento da gestação e kit para os novos pais e mães Avanade;
- Horários flexíveis;
- Participação nos resultados da empresa;
- Gympass;
- Auxílio creche;
- Career Advisor - Um braço direito para orientar a sua carreira;
- Exposição com times globais a depender do projeto;
- Buddy – Uma pessoa que irá te ajudar nos seus primeiros meses e na fase de adaptação à nossa cultura;
- Para função gerencial ou superior - Veículo corporativo, estacionamento e auxílio combustível.

## Como se candidatar

- WhatsApp: https://wa.me/5531982036319 
- LinkedIN: https://www.linkedin.com/in/marcelamnogueira/

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Consultor Senior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
