### ISSUE TITLE
[Remoto] Desenvolvedor Front-end Angular Pleno - CLT [Ezconet]

### ISSUE THREAD

**Issue by faramacedo** [frontendbr/vagas#7057]
### **Desenvolvedor** Front-end Angular Pleno - CLT
 _(Experiencia mínima de 3 anos como desenvolvedor front-end)_
<HR>

***Enviar CV para vagasti@ezconet.com.br com assunto #Dev Front-End Pleno#*** 
_(não é mandatório, mas se tiver Portifolio/LinkedIn/Git favor enviar para avaliação)_

 **Irá atuar em:** 
- Desenvolvimento e manutenção de aplicações web;
- Integração e funcionalidades para Front-End;
- Contribuindo ativamente para propor e desenvolver melhores soluções de desenvolvimento;
- Aplicar melhores práticas de documentação de código;

 **Hard skill** 
- Domínio das linguagens Web : HTML, CSS/SCSS e JavaScript;
- Domínio em Angular 2+;
- Conhecimento em Consumo de API Rest;
- Boas práticas de programação, SEO e Performance;
- Conhecimento UI/UX;

**Soft skill** 
- Amigável, colaborativo;
- Objetividade e clareza na exposição de ideias para o time;
- Foco em resolução dos problemas como equipe;
- Boa comunicação oral e escrita;

**Será considerado Diferencial desenvolvimento mobile em uma das tecnologias**
- Ionic;
- Flutter;
- React;
- Familiarização com a cultura de testes;

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
