### ISSUE TITLE
[Belo Horizonte / MG] Front-End / FullStack Developer na Virturian

### ISSUE THREAD

**Issue by virturian** [frontendbr/vagas#706]
## Descrição da vaga

Desenvolvimento de app web responsivo para monitoramento de equipamentos. 

## Local

Escritório no Barro Preto, Belo Horizonte, MG

## Benefícios

- Superar metas -> direito de participação

#### Diferenciais

- Startup com crescimento acelerado

## Requisitos

**Obrigatórios:**
- Experiência comprovada com Node 
- Experiência comprovada com React e/ou Angular
* O candidato à vaga será testado em um desafio e serão analisados os projetos já realizados por ele.

**Diferenciais:**
- Domínio de Linux
- Conhecimentos AWS
- Experiência full stack

## Contratação

PJ a combinar

## Nossa empresa

Ajudamos nossos clientes a reduzirem custos e operarem com excelência respondendo antecipadamente o porquê e quais de seus equipamentos falharão. Todos são grandes industrias e líderes da área de atuação.

## Como se candidatar

Inscreva-se em:
https://system.solides.com/pt-BR/crud/curriculo/8ffa85e0-ac98-421d-9bdc-cc9df6fc311c/preencher

**Comment by ygorlazaro** [comment]
Boa tarde, existe a possibilidade de trabalho remoto?

**Comment by virturian** [comment]
Existe a possibilidade de trabalho remoto para outras oportunidades na empresa, mas não para esta vaga. Abraço.

**Comment by ygorlazaro** [comment]
Olá @virturian, eu vi vagas na parte de carreiras do site, mas lá não especifica quais teriam a possibilidade de trabalho remoto. Você tem uma listagem dessas vagas, por favor?

**Comment by marimeireles** [comment]
Há interesse por parte da empresa em contratar estagiário ou júnior?

**Comment by LFeh** [comment]
Aberto ainda?
