### ISSUE TITLE
[REMOTO - Porto Alegre] React.js Developer na SharePrime

### ISSUE THREAD

**Issue by alexsandervasconcelos** [frontendbr/vagas#7061]
Sobre a SharePrime
A SharePrime há oito anos desenvolve soluções que facilitam o dia a dia das organizações, conduzindo-as para transformação digital. Criamos valor por meio de conexões e experiências com tecnologia.
Estamos em pleno crescimento e buscamos talentos como você para integrar nosso time! 💛

Nossos valores são os princípios que nos inspiram e guiam todos os dias
•	Somos incansáveis pelo resultado;
•	Temos foco no cliente;
•	De pessoas, para pessoas;
•	Descomplicamos a tecnologia;
•	E temos coragem para transformar!

Descrição da vaga:
Buscamos profissionais para atuar na customização do front das páginas criadas em SharePoint em nossos projetos, atuamos com diversos clientes de segmentos variados. Atuará principalmente na customização de intranets e sites corporativos.

**Local: 100% remoto.**

**Requisitos**

**Obrigatórios:**
-Vivência prática em Javascript, HTML5 e CSS3
-Prática em desenvolvimento com biblioteca ReactJS, NodeJS e IDE Visual Studio Code
-Integrações com consumo de API e/ou WebService/SOA
-Vivência com Metodologia Ágil
-Formação concluída ou em andamento em Ciências da Computação, Análise de Sistemas ou em Cursos Técnicos de Programação.
-Prática no uso de sistemas de versionamento de código Git ou Repos
-Uso no dia a dia de Gulp/Yeoman/Node

**Desejáveis:**
-Conhecer o SPFx (Sharepoint Framework)
-Conhecer C#

## Benefícios

- Cartão Swile (VA e VR com valor variável por estado) - CLT
- Auxílio Internet (R$ 50,00/mês) - PJ e CLT
- Plano de certificações Microsoft custeados pela empresa (a partir dos primeiros 6 meses) - PJ e CLT

## Contratação

CLT ou PJ, negociável.

**Jornada:**
PJ: De segunda a sexta-feira, das 9:00 às 18:00, 1h de intervalo
CLT: De segunda a sexta-feira, das 9:00 às 18:48, 1h de intervalo

## Como se candidatar

Por favor envie um email para rh@shareprime.com.br com seu CV anexado - enviar no assunto o código: RGT0622

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@shareprime.com.br

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Júnior
- Pleno

**Comment by Cientista-Avogadro** [comment]
Interessado mano muito

**Comment by Cientista-Avogadro** [comment]
Tenho tudo

**Comment by rafael-jordao** [comment]
Currículo enviado

**Comment by ricardomendes95** [comment]
Sent!

**Comment by matheusgb** [comment]
Enviado! 😁

**Comment by Ericckm** [comment]
CV Enviado.

**Comment by calvitoria** [comment]
Enviado! :rocket:

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
