### ISSUE TITLE
[Remoto] Front-end Developer Vue.js Sr na Invillia

### ISSUE THREAD

**Issue by gihhlazaro** [frontendbr/vagas#7068]
**INVILLIA**
Aproxime-se. A Invillia não apenas transformou a forma como as empresas mais revolucionárias do mundo criam e desenvolvem estratégias, negócios e produtos digitais.
Inovou também a maneira como pessoas apaixonadas por tecnologia, de qualquer lugar do planeta, podem interagir, evoluir, mais conectados do que nunca.
Para a Invillia, não importa onde você está. Se é um país grande. Ou uma cidade pequena. E sim a sua vontade. As suas ideias. O seu potencial.
O tamanho do seu talento_

**REQUISITOS**

Vue.js Avançado;
HTML5, CSS3 (Sass), Javascript, JSS;
Git, Docker, Gulp, Webpack, Gerenciamento de Pacotes (ex: NPM, Yarn) e TDD;
Soluções e definições de arquitetura (Flux Architecture);
Conhecimento teórico e prático em microserviços e APIs;
JWT, RestFull, Rest Hateoas, oAuth2.0;
Padrões de Projetos (DDD, Solid, Design Patterns);
Integração e entrega contínua (CI/CD);
Banco de Dados Relacional e Não-Relacional;
Desenvolvimento Ágil - Scrum e Kanban;
Inglês avançado;

**DIFERENCIAIS**

Ferramentas de monitoramento (Google Data Studio, Mesos, Splunk. Kibana)
Criação de gráficos (Highcharts ou outros)
Beautify/Material Design/Bootstrap, Styled components e Design System
Microfront-end
Escalabilidade

**RESPONSABILIDADES**
Será responsável em prover soluções técnicas para novas features e dar o suporte necessário as features já existentes, afinal, nem tudo são flores.
Esperamos também que essa pessoa auxilie os outros membros do time em questões técnicas não esquecendo de fornecer a melhor solução para o negócio.
Algo que prezamos bastante é qualidade, isso inclui um código limpo e legível (clean code).
Também é desejável que o mesmo tenha um perfil intra-empreendedor, onde seus objetivos estejam alinhados com os objetivos da empresa, afinal, temos muito orgulho do que fazemos aqui!

**LOCAL**
Full remoto

**REGIME**
CLT

**COMO SE CANDIDATAR**
Enviar o currículo atualizado para [giovanna.lazaro@invillia.com](mailto:giovanna.lazaro@invillia.com) ou pelo In: https://www.linkedin.com/jobs/view/3119279250

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
