### ISSUE TITLE
[Aquiraz/CE] Js/Cordova Developer na oowlish 

### ISSUE THREAD

**Issue by clmadrazo** [frontendbr/vagas#707]
## Descrição da vaga

Venha fazer parte do time oowlish!
Na oowlish estamos à procura de desenvolvedores Js/Cordova para juntar-se à nossa equipe!

## Local

Escritório, Ceará - Aquiraz

## Benefícios

- Trabalhar na “oowlish Mansion” 😉
- Uso de SCRUM, trabalhar numa das nossas squads.
- Ambiente de trabalho internacional, descontraído e cooperativo
- Trabalhar em produtos de sucesso internacional
- Salário
- Horário flexível

## Requisitos

**Obrigatórios:**

- Amplo conhecimento em JS
- Backbone, requirejs, bower
- Cordova/Phonegap
- Design patterns.
- Experiência em produtos mobile.
- Inglês básico (leitura/escrito)

**Desejáveis:**
- Conhecimentos de Node.js

**Diferenciais:**
- Conhecimentos de Symfony/PHP
- Inglês fluente

## Contratação

CLT

## Nossa empresa
oowlish é uma empresa de desenvolvimento dinâmico com sede no Porto Das Dunas. Nós adoramos móveis, web e excelente trabalho! Ajudamos às empresas a desenvolver e produzir seus produtos de mídia digital.

## Como se candidatar

Por favor envie um email para career@oowlish.com com seu CV anexado - enviar no assunto: Js/Cordova Developer

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
