### ISSUE TITLE
[Campinas/SP - Híbrido] Front-end Developer Pleno na Aptus Teclonogia em informação ❤️ 💻  

### ISSUE THREAD

**Issue by FabianaAptus** [frontendbr/vagas#7071]
ℹ️ Sobre a empresa:

Somos a Aptus: um time que, junto e há 39 anos, constrói soluções para transformar o mundo através da tecnologia!
Com uma gama variada de serviços e produtos, oferecemos soluções globais em sistemas, fábrica de software, infraestrutura e consultoria em TI. Hoje, estamos presentes em 17 países, com mais de 500 empresas atendidas, 750 projetos realizados e 25 serviços e sistemas consolidados. Mais do que um objetivo, nosso êxito é consequência da nossa história e da contribuição de cada uma das pessoas que a constroem dia a dia, através de uma relação de respeito, parceria, muita colaboração e paixão por tecnologia. 
Por isso, somos comprometidos com o desenvolvimento humano e tecnológico. 💯 

**Como desenvolvedor na Aptus, suas atribuições serão:** 👨‍💻 👩‍💻 

- Desenvolvimento e manutenção de aplicações web com foco em C#, ASP.NET MVC, Javascript e Microsoft SQL Server
- Realizar análises, correções, implementações de funcionalidades, integrações com outras plataformas e codificações de novos sistemas;
- Desenvolvimento de funcionalidades no Front-End; 
- Desenvolvimento de funcionalidades no Back-End; 
- Aplicar melhores práticas de documentação de código desenvolvido; 
- Desenvolver e sustentar integrações; Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas.

**Local** 📌 

Modelo de trabalho híbrido, com dias presenciais no escritório situado na cidade de Campinas/SP. 🗺️ 

**O que você precisa ter?** ℹ️ 

- Experiência e 02 a 03 anos como desenvolvedor; 
- Experiência prévia em C#, ASP.NET MVC, Javascript e Microsoft SQL Server; 
- Atitudes de responsabilidade, maturidade e espírito de equipe - fatores fundamentais para evolução na Aptus; 
- Raciocínio lógico; 
- Organização, bom relacionamento e trabalho em equipe; Residir na Região Metropolitana de Campinas (SP); 

**Serão diferenciais se você tiver:** 💡 

- Conhecimento em DHTMLX. 
- Conhecimento em Apache Cordova e Framework 7. 
- Conhecimento em metodologias ágeis (Scrum/Kanban).

**+ Benefícios:** 💳 

- Salário a combinar;
- Plano de Saúde para colaborador, cônjuge e filhos menores de 21 anos;
- Vale Refeição (crédito em cartão de benefícios flexível);
- Day-off na semana do aniversário;
- PLR anual;

**Diferenciais:**

- Day off na semana do aniversário 💯 
- Transparência sempre 🥇 
- Trabalho com alegria 👯 

**Modo de contratação:**
 
Contratação CLT 💼 

**Como se candidatar** 

📧 Por favor envie um email para [rh@aptus.com.br] com seu CV anexado - enviar no assunto: Vaga Dev Pleno

**Tempo médio de feedbacks**

Após a candidatura, costumamos entrar em contato até 07 dias depois. O feedback após a entrevista ocorre em até 03 dias.

E-mail para contato em caso de não haver resposta: rh@aptus.com.br

 **Nível**

- Pleno 🥇

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
