### ISSUE TITLE
[Remoto] Full Stack Java/Angular Developer @ Capgemini

### ISSUE THREAD

**Issue by DaianeCapgeminiTech** [frontendbr/vagas#7072]
Que tal desenvolver a sua carreira em uma das maiores consultorias de TI do mundo?

A Capgemini é uma empresa internacionalmente premiada e reconhecida pela condução da transformação digital.

Somos guiados por sete valores principais: honestidade, audácia, confiança, liberdade, espírito de equipe, modéstia e fun. Se você compartilha dos mesmos valores, aqui é o seu lugar.

 O que esperamos de você:

- Ensino Superior Cursando ou Completo.

Principais Conhecimentos:  Angular8+, Type Script, Java.  

100% Remoto

**Obrigatórios:**
Experiência com Angular8+ , 2 anos
Experiência com  Type Script , 2 anos
Experiência com  Java , 2 anos

Benefícios: 
Assistência Médica, Assistência Odontológica, Vale Refeição, Seguro de Vida, Previdência Privada, Plataforma de curso de Inglês, Gympass, Parceria com Pluralsight e Coursera, 2 anos de gratuidade Veloe, Clube de benefícios e Universidade Corporativa.

Contratação CLT

Link para cadastro https://jobs.capgemini.com/br-pt/job/Bahia-BA/810559401/

Ou por favor envie um email para daiane.amaral@capgemini.com ,  com seu CV anexado - enviar no assunto: Vaga Java/Angular

## Tempo médio de feedbacks

 Costumamos enviar feedbacks em até 10 dias após o processo único.

 Alocação
- Remoto

Regime
- CLT

Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
