### ISSUE TITLE
[REMOTO] Front-end Developer Jr. na Martin Luz

### ISSUE THREAD

**Issue by ggmamarante** [frontendbr/vagas#7073]
Somos apaixonados por boas ideias e pela transformação criativa e procuramos curiosos que busquem aprender e crescer junto conosco. Se você é alguém que acredite que nenhum desafio é pequeno, se ele te mover. Alguém curioso(a) e inquieto(a). Disposto(a) a mergulhar em um mercado em que o relacionamento é a porta de entrada para o sucesso. Essa vaga é para você!!!
Procuramos alguém criativo(a) e com um bom repertório visual para nos ajudar nas demandas de motion e que tenha senso crítico apurado para desenvolver o melhor trabalho possível.

Principais atividades:
● Desenvolver sites e landing pages utilizando boas práticas;
● Se reunir e coletar informações com o cliente;
● Encontrar e solucionar problemas;
● Usar de forma constante o Github.

Principais responsabilidades:
● Trabalhar de maneira colaborativa;
● Traduzir da maneira mais fiel possível os layouts para o código;
● Participar de análises e planejamentos técnicos para encontrar as melhores soluções;
● Acompanhar os projetos em andamento.

Desafios da posição:
● Se manter atualizado com as boas práticas das tecnologias;
● Aprendizado constante;
● Construir e manter boa comunicação entre os colaboradores da agência.

Oportunidade de aprendizado:
● Aprofundamento em SASS e bootstrap;
● Criar temas do zero para Wordpress;
● Desenvolver olhar estético para as interfaces;
● Desenvolvimento de comunicação;
● Boas práticas e novas tecnologias;
● Trabalho em equipe;
● Trabalho estratégico.

Requisitos
- Já ter desenvolvido algum projeto antes;
- Ter noções básicas da área de desenvolvimento;
- Raciocínio lógico.
- Habilidades técnicas:
- Conhecimento em HTML, CSS e JS;
- Conhecimento em Bootstrap;
- Conhecimento em Wordpress.

Desejável
- Interpretação de texto e saber se comunicar bem de maneira escrita;
- Detalhista;
- Gostar de trabalhar em conjunto;
- Autodidata;
- Comunicativo(a);
- Vontade de aprender.

Benefícios
- Cesta Básica;
- Auxílio de custo;
- Um dia off por seu aniversário;
- Parceria Creditas;
- Programa de Bem estar e saúde mental;
- PLR;
- Seguro de vida.

[Candidate-se](https://trampos.co/oportunidades/732491-front-end-junior?locale=pt-BR)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by Pedroporto87** [comment]
@felipefialho como faço pra me candidatar?

**Comment by MacaulayVitor** [comment]
[https://www.canva.com/design/DAFFvG-cp0g/Q2R7ZNwAMlDrIeSsRkyQig/view?utm_content=DAFFvG-cp0g&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink](url)
[https://macaulayvitor.github.io/Portifolio./](url)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
