### ISSUE TITLE
[REMOTO] Front-end Developer Pleno na Martin Luz

### ISSUE THREAD

**Issue by ggmamarante** [frontendbr/vagas#7074]
Somos apaixonados por boas ideias e pela transformação criativa e procuramos curiosos que busquem aprender e crescer junto conosco. Se você é alguém que acredite que nenhum desafio é pequeno, se ele te mover. Alguém curiosx e inquietx. Dispostx a mergulhar em um mercado em que o relacionamento é a porta de entrada para o sucesso. Essa vaga é para você!!!

Principais Atividades:

- Desenvolver sites e landing pages com boas práticas;
- Se reunir e coletar informações com o cliente;
- Encontrar e solucionar problemas;
- Usar de forma constante o Github.

Principais Responsabilidades:

- Evoluir constantemente;
- Trabalhar de maneira colaborativa;
- Análise e indicar pontos de melhorias;
- Traduzir da maneira mais fiel possível os layouts para o código;
- Participar de análises e planejamentos técnicos para encontrar as melhores soluções;
- Acompanhar os projetos em andamento, auxiliando na organização.

Desafios da posição:

- Se manter atualizado com as boas práticas das tecnologias;
- Aprendizado constante;
- Construir e manter boa comunicação entre os colaboradores da agência;

Oportunidade de Aprendizado:

- Aprofundamento em SASS e bootstrap;
- Criar temas do zero para Wordpress;
- Desenvolver olhar estético para as interfaces;
- Desenvolvimento de comunicação;
- Boas práticas e novas tecnologias;
- Trabalho em equipe;
- Trabalho estratégico.

Requisitos

- Escolaridade: não tem obrigatoriedade de curso superior, mas é um diferencial. Completo ou cursando.
- Conhecimentos ou experiências técnicas, cursos desejáveis:
- Raciocínio lógico;
- Portfólio com bons projetos;
- Experiência com Javascript, PHP e Wordpress.
- Habilidades técnicas:
- Conhecimento sólido em HTML, CSS, SASS e JS;
- Conhecimento sólido em Bootstrap;
- Conhecimento sólido em Wordpress;
- Conhecimento em PHP (conhecimento em CodeIgniter é um diferencial).

Desejável

- Interpretação de texto e saber se comunicar bem de maneira escrita;
- Atenção aos detalhes;
- Gostar de trabalhar em conjunto;
- Organização com prazos e projetos;
- Autodidata;
- Comunicação;
- Vontade de aprender.

Benefícios

- Férias remuneradas;
- Seguro de vida.

Candidate-se: https://trampos.co/oportunidades/733544-front-end-pleno?locale=pt-BR

**Comment by saviocunha2** [comment]
como faço para me candidatar ???

**Comment by ggmamarante** [comment]
Ops... Esqueci do link, está aqui: https://trampos.co/oportunidades/733544-front-end-pleno?locale=pt-BR

**Comment by ggmamarante** [comment]
> como faço para me candidatar ???

Ops, esqueci de adicionar o link. Obrigado por perguntar.

https://trampos.co/oportunidades/733544-front-end-pleno?locale=pt-BR

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
