### ISSUE TITLE
[São Paulo] Front-end Developer na Sioux

### ISSUE THREAD

**Issue by philippecapouillez** [frontendbr/vagas#7075]
Somos uma agência consultiva. Entendemos desafios, criamos e implementamos estratégias sob medida que geram resultados de negócio para nossos clientes promovendo experiências digitais relevantes para as pessoas.

**Responsabilidades e atribuições:** 
- Desenvolver com qualidade o próprio código;
- Participar do desenvolvimento de produtos inovadores do mercado, atuando na construção de softwares de alta performance;
- Participar de forma engajada em toda as cerimonias do SCRUM como Sprint Planning, a Daily Meeting, a Sprint Review e a Sprint Retrospective;

**Requisitos**
- Experiência sólida em Java 7, Java 8, Microserviços, Framework, Spring boot, banco de dados relacional e não relacional (MS SQL, Oracle ou Postgree);
- Conhecimentos sólidos em Angular 7 e 8, Front-end (HTML5, CSS3, Javascript, XML, Javascript);
- Experiência com ferramentas de versionamento de código: Git com Git flow, Maven ou Gradle; Metodologia ágeis: Scrum, Jira; Testes Unitários, Sonar.

**Desejável**
- Control+M
- Sonar + Fortify
- Camunda
- Camel

**Diferencial**
- Conhecimento em DevOps

 **Benefícios**
🍱Vale refeição e/ou alimentação: Você pode escolher o que for melhor para você.
👩‍⚕️Assistência médica e odontológica: É importante se cuidar e estar bem.
🚆Vale transporte e/ou vale combustível: A escolha de como você se move é sua.
🚑Seguro de vida: A sua segurança também é a nossa.
📙Auxílio a cursos, certificações e eventos: Nos importamos com o seu desenvolvimento!
🍩Mimo no dia do aniversário;
🏡Auxílio home-office: Para você investir no seu office enquanto está de home.
💻E-learning: Nossos colaboradores possuem acesso à uma trilha de conhecimento para fazerem os cursos de maneira gratuita!
🍼 Auxílio creche: Um apoio para cuidar do seu pequeno;
🎯 Programa de indicação - Nos ajude a encontrar talentos para o nosso time e ainda ganhe um bônus.

**Como ser um candidato**
Se cadastre no site https://jobs.quickin.io/sioux/jobs/628288e69d4725001c06d0ff

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
