### ISSUE TITLE
[Remoto] Front-End Flutter Developer na Rispar

### ISSUE THREAD

**Issue by RecruiterRispar** [frontendbr/vagas#7078]
## Nossa empresa

Rispar, primeira plataforma de empréstimo com garantia cripto do Brasil, busca Mobile Flutter Developer!
Queremos protagonizar a mudança na vida financeira das pessoas e para isso estamos lançando novos produtos inovadores no mercado brasileiro. Saiba mais em: rispar.com.br

## Descrição da vaga

Responsabilidades:
- Desenvolver software (com testes) pronto para produção;
- Gerenciar a publicação do aplicativo na loja;
- Promover a melhoria da usabilidade;
- Explorar e avaliar Tecnologias e ferramentas móveis;
- Trabalhar em conjunto com o Gestor de Produto para satisfazer as necessidades dos clientes.

## Local

 Remoto [mas temos office na Av.Paulista /SP]

## Requisitos

**Obrigatórios:**
- Pelo menos 3 anos de experiência com desenvolvimento Mobile, sendo no mínimo 1 ano em Flutter;
- Conhecimentos de User Experience e User Interface;
- Sólidos conhecimentos em Dart;
- Controle de versão utilizando Git / Gitflow;;
- Interfaces responsivas;
- Que goste de trabalhar em equipe;
- State Management.

**Diferenciais:**

- Experiência com Figma;
- Conhecimento de ferramentas de ads, como appsflyer;
- Conhecimento na infra-estrutura AWS e Google Cloud (Firebase);

## Benefícios

- A partir de 12k - contrato PJ.﻿
- Trabalho 100% Remoto (temos office na Av. Paulista/SP);
- Plano de Saúde sem coparticipação no CLT;
- Vale alimentação/refeição (Cartão Caju) no PJ e CLT;
- Seguro de Vida no CLT;
- Gympass (Academia) e Zenklub (Terapia Online) no CLT.

## Contratação

PJ ou CLT (candidato decide)

## Como se candidatar

Envie Currículo e link do Portfólio para [talentos@rispar.com.br](mailto:talentos@rispar.com.br). Coloque no Assunto: Dev Flutter.

## Tempo médio de feedbacks

Damos feedback em no máximo 2 dias a cada etapa do processo.

#### Nível

- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
