### ISSUE TITLE
[Niterói] Frontender na WPENSAR

### ISSUE THREAD

**Issue by mathvaleriano** [frontendbr/vagas#708]
## Local

Presencial, Capitão Zeferino, nº 13, Niterói - RJ

## Benefícios

- Seguro de vida
- VR de R$ 24,30/dia
- Vale Transporte

#### Diferenciais

- sala de jogos
- horário flexível
- ambiente descontraído

## Requisitos

**Obrigatórios:**
- HTML
- CSS
- JS

**Diferenciais:**
- AngularJS / React e afins
- Noções de REST
- Testes Automatizados

## Contratação

CLT full

## Sobre a Empresa

Fundada em 2011 a WPensar tem como objetivo mudar a educação do país. O grupo conta com soluções tecnológicas de ponta com o objetivo de auxiliar gestores escolares na otimização de tempo e recursos focando no que é mais importante, a educação.

## Como se candidatar

Por favor envie um email para rh@wpensar.com.br com seu currículo anexado, especificando "FRONT END" no assunto

**Comment by igorpinhh** [comment]
necessário ensino superior?

**Comment by mathvaleriano** [comment]
não

**Comment by matheus-rosin** [comment]
não pode ser à distância? sou de Curitiba...

**Comment by mathvaleriano** [comment]
A principio nao. Mas estamos implantando o homeoffice aos poucos

**Comment by matheus-rosin** [comment]
Beleza, valeu!

**Comment by HaluDeCassia** [comment]
@mathvaleriano se quiser experimentar como ficaria o homeoffice, seria um bom momento agora rs. Sou do interior de São Paulo, porém me interesso pela vaga e acredito me enquadrar bem nela

**Comment by mathvaleriano** [comment]
falei com meus chefes e com o rh parece que vão abrir um processo para homeoffice... não sei ao certo qual será o move... então... @HaluDeCassia e @matheus-rosin mandem currículo explicando que podem se candidatar para o homeoffice e vejam qual o procedimento.

**Comment by matheus-rosin** [comment]
Muitíssimo obrigado! :)

**Comment by HaluDeCassia** [comment]
Muito obrigada, @mathvaleriano vou mandar sim :smile:

**Comment by HaluDeCassia** [comment]
@mathvaleriano muito obrigada. Já havia mandado para a vaga que você me indicou :)

**Comment by danielsidev** [comment]
E-mail enviado! Valeu!

**Comment by Morette** [comment]
A vaga ainda está aberta?

**Comment by RenatoAreas** [comment]
@mathvaleriano Há a possibilidade de contratarem um profissional Jr ?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
