### ISSUE TITLE
[Remoto ] Flutter Developer na Meta 

### ISSUE THREAD

**Issue by techrhrj** [frontendbr/vagas#7085]
## Descrição da vaga

Oportunidade de alocação em uma multinacional brasileira que atua no segmento alimentício

## Local

Remoto 

## Benefícios

- Plano de Saúde ( Bradesco )
- Plano Odontológico ( Odontoprev )
- Seguro de Vida
- PLR
- Ajuda de Custo
- VA/VR
- Parceria com a Alura
- Parceria com a Vittude
- Meta Academy
- English Club
- Acesso a plataforma microsoft learn para certificações

## Requisitos

Obrigatórios
- 4 ou + anos de experiência com Flutter
- Experiência com react
- Vivência com metodologia ágil

## Contratação

CLT 

## Nossa empresa

Confie em quem entende de tecnologia e venha com a Meta! 

Nosso propósito: crescimento humano com tecnologia

Conheça nosso site: https://www.meta.com.br/

## Como se candidatar

Por favor envie um email para thais.franco@meta.com.br com seu CV anexado

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
