### ISSUE TITLE
[Rio de Janeiro/Recife] Front-end Developer na Passei Direto

### ISSUE THREAD

**Issue by nathzamberlan** [frontendbr/vagas#7086]
## Sobre a Passei Direto

Prazer, somos a **PD**, parte do ecossistema **UOL EdTech** e orgulhosamente responsáveis por transformar o futuro de milhões de estudantes e produtores de conteúdo a partir do compartilhamento do conhecimento. Legal, né?

Você também pode nos conhecer como a maior rede de estudos do Brasil, pois contamos com 11 milhões de materiais disponíveis, mais de 20 milhões de visitas por mês e somos o app **#1** de Educação.

O nosso propósito é facilitar o acesso ao conhecimento para empoderar as pessoas e transformar o futuro. Na prática, isso significa que conectamos quem quer ensinar com quem quer aprender para conquistar seus sonhos.

## Descrição da vaga
A posição de Pessoa Desenvolvedora de Software Pleno está em nosso time de Tecnologia. O nosso maior desafio é trabalhar em conjunto com nossas equipes multifuncionais para ajudá-las a projetar e construir nossos produtos. Esperamos que você seja apaixonado por programação e arquitetura. Você também deve se sentir confortável trabalhando em um ambiente dinâmico e em ritmo acelerado. 🧡

Aqui na Passei Direto o aprendizado é constante. Contamos com a sua inquietude e colaboração para apoiar o time e suas principais responsabilidades serão:

- Zelar pelo ambiente em produção, prestando cuidados especiais ao uso eficiente dos recursos e à escalabilidade e estabilidade do sistema;
- Escrever código limpo, com baixa proporção de bugs, boa cobertura de testes e respeitando o tempo estimado;
- Contribuir para a construção de soluções em conjunto com o time;

## Local
Flex-Office nas cidades do Rio de Janeiro ou Recife

## Requisitos

**Acreditamos que o nosso time de foguetes nos ajuda a fortalecer a nossa cultura, transformando para melhor a forma que trabalhamos e nos relacionamos na empresa. Para essa oportunidade, estamos buscando um profissional com:** 

- Ser apaixonado por tecnologias e aprender uma nova por si mesmo, sendo capaz de configurar, testar, monitorar, otimizar, escalar e automatizar;
- Conhecer o ecossistema Javascript (VueJs, React, React Native, NodeJs)
- Familiaridade com Design System, Atomic Design e componentização
- Familiaridade com arquitetura de micro frontends e micro serviços
- Conhecimento em pré-processadores CSS e patterns (BEM, SMACSS)
- Conhecimento em HTML semântico e otimização para SEO
- Familiaridade com SSR e CSR
- Familiaridade com CI/CD (integração e entrega contínuas);
- Monitoramento e investigação de bugs e problemas;
- Familiaridade com diferentes tipos de testes automáticos (unitário, integração, componente, ponta a ponta);
- Conhece sobre REST Apis e bancos de dados relacionais;
- Conhecimento de princípios e padrões de qualidade software;
- Conhecimento em desenvolvimento ágil e protótipos rápidos;
- Aprender rápido e se adaptar às mudanças.

**Tecnologias que usamos aqui :) mas não esperamos que você conheça todas elas!**
- AWS (S3, ECS, EC2, RDS, ElastiCache, DynamoDB, CloudFront, Neptune, CloudWatch, Kinesis, Transcribe, Textract);
- Github;
- Python;
- [Vue.js](http://vue.js/);
- React;
- [Node.js](http://node.js/);
- MySQL;
- Elasticsearch;
- Redis;
- Neo4j;
- RabbitMQ.

## Benefícios
- Vale alimentação ou refeição de R$ 815,00 mensais - não descontamos em período de férias!
- Plano de saúde e odontológico Bradesco nacional - sem co-participação e extensível para cônjuges e filhos;
- Seguro de vida.
- Descontos de até 50% em pós graduação e MBA de grandes instituições, como FIA e PUCRS;
- Plano corporativo do Gympass para você praticar o exercício físico que mais curte;
- Mentorias individuais e coletivas para nossas lideranças e time;
- Apoio psicológico, financeiro e jurídico 24 horas;
- Licença maternidade e paternidade estendida;
- Kit maternidade para mamães e papais de plantão;
- Auxílio creche de até R$530,00 por mês para filhos de até 6 anos;
- Happy Day para você poder aproveitar o dia do seu aniversário focando na pessoa mais importante do dia: você!
- Participação nos resultados da empresa (PPR): se a PD e a UOL Ed Tech ganham, você ganha também!
- Ajuda de custo mensal para o home office.

**Diferenciais:**
- Horário de trabalho flexível - aqui na PD não batemos ponto;
- Temos um dia no mês dedicado ao Aprendizado, o nosso Refresh, quando os foguetes compartilham conhecimentos e dedicam tempo para estudar o que preferir!

## Contratação
CLT, com salario a ser definido a partir da senioridade e pretensão salarial.

## Como se candidatar
Sua aplicação é feita por meio de uma ATS e clicando [aqui ](https://passeidireto.gupy.io/jobs/1683892 )você será direcionado para a pagina de aplicação (mas calma, não pedimos nenhum tipo de teste para aplicação!!!)

## Tempo médio de feedbacks

Costumamos enviar feedbacks semanais sobre o andamento do processo seletivo, mas se não haver resposta, você pode procurar via e-mail no [georgia.pessoa@passeidireto.com](mailto:georgia.pessoa@passeidireto.com)

#### Vaga afirmativa
- Essa oportunidade é afirmativa para **mulheres** que desejam fazer parte do time PD, caso você não se identifique com esse grupo, pedimos que confira outras oportunidades na nossa [página de carreiras.](https://passeidireto.gupy.io/)

#### Alocação
- Flex-Office

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
