### ISSUE TITLE
[Remoto] Frontend Engineer na Intelipost

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#7089]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-engineer-170628559?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>A Intelipost </strong>busca pessoa <strong>Frontend Engineer</strong> para compor seu time!</p>
<p>A Intelipost é um TMS embarcador com soluções que integram, de forma inteligente, lojistas (como e-commerce, varejistas, indústrias, marketplaces, operadores logísticos) e transportadoras, proporcionando uma visão completa das entregas e redução de custos logísticos.</p>
<p><strong>Responsabilidades:</strong></p>
<ul>
<li>Desenvolvimento de aplicações web;</li>
<li>Manutenção de sistemas para correção de falhas/erros;</li>
<li>Construir uma base sólida para o desenvolvimento de novos produtos de forma ágil;</li>
<li>Acompanhar a disponibilidade do nosso sistema, visando antecipar possíveis GAPs, aumentando assim, a confiabilidade da solução;</li>
<li>Colaborar com outros membros da equipe: Engenheiros, PO, QA, Designers, Scrum Master e Tech Leader para resolver os desafios existentes;</li>
<li>Desenvolver sistemas escaláveis, sustentáveis​​e orientadas ao usuário.</li>
</ul>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>

## Intelipost: 
 <p>A Intelipost é um TMS embarcador com soluções que integram, de forma inteligente, lojistas (como e-commerce, varejistas, indústrias, marketplaces, operadores logísticos) e transportadoras, proporcionando uma visão completa das entregas e redução de custos logísticos.</p>

<p>Desde a sua fundação em 2014, a Intelipost oferece soluções que simplificam a gestão de todas as informações logísticas por meio de tecnologia em nuvem de alta confiabilidade, garantindo total visibilidade do processo de entrega.</p><a href='https://coodesh.com/empresas/intelipost'>Veja mais no site</a>

 ## Habilidades: 
 - Vue.js 
- GraphQL 
- Javascript 
- CSS 
- HTML
## Local: 
 100% Remoto
## Requisitos: 
 - Graduação completa em Tecnologia, Análise de Sistemas, Sistemas da Informação, Engenharia de Software ou cursos de áreas correlatas; 
- Experiência com desenvolvimento de aplicações WEB, utilizando Vue.js, GraphQL, CSS, HTML; 
- Conhecimento básico de arquitetura de sistemas de alta escala e tolerância que rodem em ambiente AWS;
## Diferenciais: 
 - Conhecimento em Backend para integração com a equipe.

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Engineer na Intelipost](https://coodesh.com/vagas/frontend-engineer-170628559?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
