### ISSUE TITLE
[Campinas] Frontend Developer na CI&T

### ISSUE THREAD

**Issue by gabrielmanara** [frontendbr/vagas#709]
A CI&T preza por um ambiente de respeito para todas as pessoas, independente de gênero, identidade e expressão de gênero, idade, orientação sexual, deficiências, aparência física, dimensões corporais, raça, religião e posicionamento político. Todas as pessoas são consideradas aptas em nosso processo seletivo.

Procuramos alguém que:
- Tenha sólida experiência com desenvolvimento Web
- Tenha prática em Angular, HTML e CSS;
- Goste de compartilhar suas ideias com o time e aplicar novos conhecimentos;

Você será responsável por:
- Construir softwares com qualidade;
- Enfrentar desafios reais do negócio com o cliente e o time;
- Definir e implementar soluções com o time do cliente responsável pelo produto.

Você vai se destacar se:
- Conhecer ou já tiver atuado com Javascript;
- Tiver inglês para leitura e escrita; 

Gostou? Tem mais!

A CI&T oferece : 
- Plano de carreira estruturado;
- Vale alimentação e refeição;
- Seguro de vida e auxílio creche;
- Assistência médica e odontológica;
- Gympass;
- Descontos em estabelecimentos; 
- Ônibus fretado, estacionamento ou transporte intermunicipal, dependendo da base de atuação;; 

Além disso, você pode contar com um ambiente descontraído e uma Academia de Great Coders com cursos online onde você poderá aprender ainda mais.
Prezamos pela diversidade, liberdade, flexibilidade e autonomia!

## Como se candidatar

Por favor envie um email para gmanara@ciandt.com com seu CV, linkedin anexado - enviar no assunto: Vaga Frontend CI&T

**Comment by degaus** [comment]
@gabrielmanara enviado :)

**Comment by HaluDeCassia** [comment]
Boa noite. Não há nenhuma chance de trabalho remoto?

**Comment by gabrielmanara** [comment]
valeu @degaus 
@HaluDeCassia infelizmente não.

**Comment by randhson** [comment]
enviado.
Randson N. dos S. França +55 79 99843 9878+55 79 99138 7628 

    Em segunda-feira, 18 de dezembro de 2017 14:45:23 BRT, Gabriel Manara <notifications@github.com> escreveu:  
 
 
A CI&T preza por um ambiente de respeito para todas as pessoas, independente de gênero, identidade e expressão de gênero, idade, orientação sexual, deficiências, aparência física, dimensões corporais, raça, religião e posicionamento político. Todas as pessoas são consideradas aptas em nosso processo seletivo.

Procuramos alguém que:
   
   - Tenha sólida experiência com desenvolvimento Web
   - Tenha prática em Angular, HTML e CSS;
   - Goste de compartilhar suas ideias com o time e aplicar novos conhecimentos;

Você será responsável por:
   
   - Construir softwares com qualidade;
   - Enfrentar desafios reais do negócio com o cliente e o time;
   - Definir e implementar soluções com o time do cliente responsável pelo produto.

Você vai se destacar se:
   
   - Conhecer ou já tiver atuado com Javascript;
   - Tiver inglês para leitura e escrita;

Gostou? Tem mais!

A CI&T oferece :
   
   - Plano de carreira estruturado;
   - Vale alimentação e refeição;
   - Seguro de vida e auxílio creche;
   - Assistência médica e odontológica;
   - Gympass;
   - Descontos em estabelecimentos;
   - Ônibus fretado, estacionamento ou transporte intermunicipal, dependendo da base de atuação;;

Além disso, você pode contar com um ambiente descontraído e uma Academia de Great Coders com cursos online onde você poderá aprender ainda mais.
Prezamos pela diversidade, liberdade, flexibilidade e autonomia!

Como se candidatar

Por favor envie um email para gmanara@ciandt.com com seu CV, linkedin anexado - enviar no assunto: Vaga Frontend CI&T

**Comment by danilosilvadev** [comment]
@gabrielmanara vcs fazem entrevista via skype?

**Comment by tiagovilasboas** [comment]
Boa sorte manara!

**Comment by rands0n** [comment]
Vocês apoiam a pessoa a se mudar de cidade?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
