### ISSUE TITLE
[Remoto] Front-end Developer at Teamwork

### ISSUE THREAD

**Issue by netoramalho** [frontendbr/vagas#7090]
## Nossa empresa
Teamwork's mission is to make teams who deliver client work become efficient, organized, profitable and happy! Our platform has revolutionized how companies manage their daily workflows for improved automation, productivity, and profitability. It acts as the ‘one-stop-shop’ practice management solution enabling our customers to track, manage, and invoice their projects. Our relentless customer-focus has been rewarded with thousands of amazing customers all across the globe and millions of users who sign in every day. We pride ourselves on creating market leading software, working with outstanding people, and going above and beyond for our customers. Trusted by more than 20,000 teams across 170 countries, Teamwork is in acceleration mode as we set our sights to become the undisputed Project Management platform for teams who deliver client work.

We believe in hiring great people and look to ensure everyone has the best possible experience of work, everyday. We strive to be open and transparent, humble and customer focused. And we thrive on curiosity, getting results and working together relentlessly to deliver excellence. We are a company of action, full of triers and doers: we try things, we make mistakes, and we learn from them. Our personality is unmistakable: we work hard, take joy in our wins and each other's successes and important life events. And we care and support each other when life throws lemons. More than anything we embrace a straightforward approach to getting things done. We are fanatical about our customers: and when talent meets passion, success happens.

We are a remote-first team, with the option to work out of our Cork HQ campus, Belfast or Boston hubs - or fully remotely. At Teamwork we believe that work is what you do, not where you sit.

## Descrição da vaga
We're looking for a freelance Front-End dev to help us in the migration to our new CMS. The assignment should be around 4 months with the potential of extending. As part of the Brand & Comms team, you'll work closely with our Lead Developer and Creative Director to help prioritize the migration strategy and your day to day.

## Local
Remote

## Requisitos

**WHAT GOOD LOOKS LIKE**
- Writing clean, functional, and maintainable code
- Help define, build and maintain Teamwork Design System
- Review team member’s work via code review

**REQUIREMENTS**
- 5+ years of front-end development experience with JavaScript, HTML, and CSS
- 2+ years of professional experience using modern front-end frameworks (Nuxt/Vue.js)
- Proficiency with CSS pre-processors like SCSS
- Experience consuming APIs
- Experience with version control systems such as Git
- Good written and oral communication skills in English
- Experience with headless CMS (E.g. Storyblok, Contentful etc.)
- Passionate about implementing clean and pixel-perfect user interfaces
- Experience with Core Web Vitals optimization
- Knowledge of SEO principles
- Familiarity with Jamstack and Netlify
- Responsive web design using CSS flexbox, and media queries
- Work experience in Agile Scrum methodologies
- Experience with Storybook development practices

## Contratação
PJ

## Como se candidatar
https://www.comeet.com/jobs/teamwork/F6.005/frontend-developer---contractor/1D.F29

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: netto.ramalho@teamwork.com

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
