### ISSUE TITLE
[Remoto] Fullstack C# .Net Developer na Trinks.com

### ISSUE THREAD

**Issue by GabrielaLuz1909** [frontendbr/vagas#7092]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/fullstack-developer-c-net-171733231?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>A Trinks.com </strong>busca pessoa<strong> Fullstack C# Developer </strong>para compor seu time!</p>
<p>O Trinks é uma plataforma completa elaborada para Gestão Online de Negócios de Beleza. Donos de estabelecimentos, redes ou franquias podem administrar e ter domínio sobre todas as frentes, podendo assim, focar no crescimento estratégico do seu negócio.&nbsp;</p>
<p>Os clientes têm suas rotinas muito mais simplificadas; em alguns cliques podem buscar e agendar serviços de beleza e bem-estar, sem se preocupar com ligações em horário comercial.</p>
<p><span style="font-size: 16px;"><strong>Dá uma olhada no seu papel nessa #revolução:</strong></span></p>
<ul>
<li><span style="font-size: 16px;">Atuar em um produto sólido no mercado e com regras de negócios agradáveis;</span></li>
<li><span style="font-size: 16px;">Escrever código limpo, de fácil manutenção, utilizando as melhores práticas de desenvolvimento de software;</span></li>
<li><span style="font-size: 16px;">Procurar sempre criar para o Trinks a melhor experiência de uso para o usuário final, trabalhando de perto com os especialistas de UX;</span></li>
<li><span style="font-size: 16px;">Atuar com um time de desenvolvedores de qualidade e contar com o auxílio de profissionais experientes para implementar as melhores soluções;</span></li>
<li><span style="font-size: 16px;">Estar sempre crescendo e se desenvolvendo tecnicamente e profissionalmente;</span></li>
<li><span style="font-size: 16px;">Participar de times geograficamente distribuídos.</span></li>
</ul>
<p></p>
<p></p>

## Trinks.com: 
 <p><span style="font-size: 14px;">O Trinks é uma plataforma completa elaborada para Gestão Online de Negócios de Beleza.</span></p>
<p><span style="font-size: 14px;">Donos de estabelecimentos, redes ou franquias podem administrar e ter domínio sobre todas as frentes, podendo assim, focar no crescimento estratégico do seu negócio. </span></p><a href='https://coodesh.com/empresas/trinks-servicos-de-internet-sa'>Veja mais no site</a>

 ## Habilidades: 
 - C# 
- Javascript 
- Banco de dados relacionais (SQL) 
- MVVM 
- .NET Framework 
- C# .NET Core
## Local: 
 100% Remoto
## Requisitos: 
 - ⇨ Domínio em uma ou mais linguagens de programação - aqui você trabalhará com C#; 
- ⇨ Conhecimento em um ou mais frameworks MVVM (AngularJS, VueJS, React e/ou similares); 
- ⇨ Experiência no desenvolvimento de API/Rest de alta escalabilidade; 
- ⇨ Saber aplicar padrões de projeto; 
- ⇨ Conhecer práticas de entrega contínua; 
- ⇨ Domínio de um ou mais banco de dados relacionais; 
- ⇨ Gostar de compartilhar conhecimentos e trabalhar em equipe.

## Benefícios: 
 - 💰 Auxílio home office; 
- 🍴 Vale alimentação e vale refeição; 
- 🏥 Plano de Saúde Bradesco Saúde (custo zero para o colaborador); 
- 🏋‍♀ Totalpass (plano academia); 
- 💊 Convênio farmácia; 
- 💰 Bônus por indicação de talentos; 
- 📚 Convênio com faculdade e cursos de idiomas; 
- 🎉 Day off de aniversário e de tempo de casa; 
- ⌚ Possibilidade de Horário flexível.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack C# .Net Developer na Trinks.com](https://coodesh.com/vagas/fullstack-developer-c-net-171733231?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
