### ISSUE TITLE
[Remoto] Front-end Vue Developer @Onesight

### ISSUE THREAD

**Issue by kamiarc** [frontendbr/vagas#7093]
## Nossa empresa
A Onesight é uma multinacional com foco em desenvolvimento de tecnologias disruptivas e bleeding edge, atuamos com diversos clientes em múltiplos mercados e tecnologias.
No Brasil nossas atividades se concentram em outsourcing, e-commerces e desenvolvimento AD-HOC.
Hoje podemos dizer que quase qualquer pessoa no Brasil já usou um produto ou tecnologia desenvolvidos pela gente :)

## Descrição da vaga
Vaga para dev Javascript Frontend com foco em:
Lib/framework: VueJS + VueX
Webpack

## Local
Remoto

## Requisitos
**Obrigatórios:**
- Ao menos 1 ano de experiência com Javascript

**Desejáveis:**
- conhecimentos em VueJS
- conhecimentos em Webpack
- conhecimentos em Docker

**Diferenciais:**
- conhecimentos em PHP (principalmente Symfony)
- Inglês

**Benefícios:**
- Horário flexível
- Férias flexíveis (acumulo mensal estilo Europeu 2.5d/mês e utilização livre)

## Contratação
PJ

## Como se candidatar
Envie um email para trampos@onesight.com.br com seu CV anexado - enviar no assunto: JS - Vue
Ao enviar iremos analisar seu currículo e te chamar para o teste Onesight caso passe para a primeira etapa

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

**Comment by rafhaelcardoso** [comment]
Cv enviado no e-mail!
 🙌🏼  🙌🏼

**Comment by clowdcap** [comment]
CV encaminhado. Sucesso a todos

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
