### ISSUE TITLE
[São Paulo/SP] Desenvolvedor Front-End Pleno

### ISSUE THREAD

**Issue by grippado** [frontendbr/vagas#71]
## Descrição da vaga

Desenvolvedor Front-End Pleno

## Local

Alocado, São Paulo - Vila Olímpia

## Benefícios

- Vale Refeição
- Vale Transporte
- Seguro de Saúde Porto Seguro.
- Horário flexível

## Requisitos

**Obrigatórios:**
- HTML
- CSS (SASS)
- JavaScript
- Git
- task-runners (Gulp / Grunt)
- Testes Cross-Browser
- Photoshop

**Desejáveis:**
- Noção de design e usabilidade
- Experiência com Magento

**Diferenciais:**
- Frameworks M*C (Angular, React, etc)

## Contratação

CLT

## Nossa empresa

A eÓtica.com.br chega ao mercado nacional para trazer comodidade, qualidade e
excelência em atendimento para os usuários de lentes de contato, óculos de sol e óculos
de grau sem sair de casa. 
Fundada por empreendedores e investidores internacionais com vasta experiência no
mercado digital, a eÓtica.com.br tem a missão de ser a principal referência no e-commerce
brasileiro para produtos óticos. 
Junte-se à nossa equipe de colaboradores e faça parte de uma empresa que já é
referencia no mercado óptico digital e que vem crescendo rapidamente.

## Como se candidatar

Por favor envie um email para vagas@eotica.com.br com o assunto: Desenvolvedor Front-End Pleno

**Comment by camilatigre** [comment]
@grippado 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by mhonorio** [comment]
Oi Camila,

A resposta é Sim.

[]s

Marcelo Furusawa Honório
marcelohonorio@gmail.com
Skype: marcelo.honorio
Mobile: +55 11 9 8808 0852

Em 24 de novembro de 2016 10:20, Camila Tigre <notifications@github.com>
escreveu:

**Comment by camilatigre** [comment]
Aee! Que legal. Obrigada por responder e ajudar.

Em 24 de nov de 2016 10:27, "Marcelo Honorio" <notifications@github.com>
escreveu:
