### ISSUE TITLE
[São Paulo] Angular(2+) Front-end Developer na Fast Shop

### ISSUE THREAD

**Issue by TalitaLira** [frontendbr/vagas#710]
## Descrição da vaga

Projeto muito bacana, para ser desenvolvido em Angular(2+)! 

## Local

Vaga 100% PRESENCIAL para zona norte de São Paulo.

## Benefícios

- Salário e benefícios compatíveis com o mercado

#### Diferenciais

- Ambiente de trabalho descontraído e feliz :)
- benefícios internos (divulgados apenas para funcionários)

## Requisitos

**Obrigatórios:**

Conhecimento em:
- Angular 2+
- Git
- HTML5
- CSS3
- SASS
- SEO
- Js

**Diferenciais:**

- Experiência na área
- Testes automatizados

## Contratação

CLT

## Nível
Júnior, pleno e sênior

## Nossa empresa

Somos realizadores de sonhos e temos a missão de cuidar do Cliente por toda a vida. 
Nossas 93 lojas estão espalhadas em oito estados brasileiros e no Distrito Federal, mas através do nosso site, chegamos onde mais gostamos de estar, na casa de nossos milhares de clientes em todo o Brasil.

## Como se candidatar

Envie um email com seu CV anexado para: 
liviamfg@fastshop.com.br 
enviar no assunto: 
Especialista TI - Especialista Frontend Web

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
