### ISSUE TITLE
[Rio de Janeiro] Pessoa Programadora Pleno - JavaScript (Node/React) na Abra Cadabra

### ISSUE THREAD

**Issue by rafaodsd** [frontendbr/vagas#7107]
## Nossa empresa

A Abra está em constante evolução e busca pessoas que queiram sonhar e realizar junto com a gente para que possamos crescer cada vez mais, nos tornando referência nacional no varejo de móveis e decorações.

Nosso time de Desenvolvimento está crescendo e estamos à procura de pessoas que sejam inovadoras, focadas em resultado, amem tecnologia e sejam apaixonadas por desenvolver soluções ágeis e eficazes para o negócio.

## Descrição da vaga

Desenvolvimento de novos processos, melhorias, correção de bugs e outros processos relacionados ao desenvolvimento;
Elaboração de Querys e Desenvolvimento em JavaScript;
Desenvolver, testar e homologar novos processos sistêmicos da empresa.

## Local

Local de trabalho: Taquara (Jacarepaguá)
Regime de trabalho híbrido (Presencial 1 dia na semana)

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Node
- 2 anos de experiência com mongodb e express

**Desejáveis:**
Ensino superior completo em Análise e Desenvolvimento de Sistemas, Gestão de TI ou áreas correlatas;
Conhecimento Avançado em HTML, JavaScript, experiência com webservices, APIs, elaboração de Querys ( Mysql, SQL Server e Oracle);
Conhecimento em Node, React.

**Diferenciais:**
Experiência com o Framework [Adonis.JS](http://adonis.js/) será um diferencial.

## Benefícios

Salário compatível com mercado + VT + Plano de Saúde e Plano Odontológico.

## Contratação

CLT

## Como se candidatar

Por favor envie um email para recursos.humanos@abracadabra.com.br com seu CV anexado e pretensão salarial - enviar no assunto: Vaga JavaScript 

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
