### ISSUE TITLE
[Remoto] Front-end Developer na "Autônomo"

### ISSUE THREAD

**Issue by vini-brito** [frontendbr/vagas#7109]
## Nossa empresa

Olá, sou um desenvolvedor web autônomo e preciso de estagiários temporários em desenvolvimento web para auxiliar com projeto em andamento.

## Descrição da vaga

- Início imediato, urgente.
- Remoto.
- Duração de 30 dias.
- Via contrato de prestação de serviço que irei te enviar. 
- Pagamento de R$1000, pago ao final dos 30 dias.
- Não preciso de nota fiscal e você não precisa ser PJ.
- Carga horária de 4 horas por dia, segunda a sexta.
- 2 vagas.

## Local

Remoto.

## Requisitos

**Obrigatórios:**

É necessário conhecimento básico em HTML, CSS e Javascript, sem frameworks, somente Javascript mesmo, "vanilla" como é chamado pela internet afora. 
Não é necessário inglês.

## Contratação

PF ou PJ via contrato de prestação de serviço.

## Como se candidatar

Responder o formulário em https://forms.gle/8rVrtqdNtgxvfJ2f9

## Tempo médio de feedbacks

O quanto antes.

#### Alocação
- Remoto

#### Regime
- Estágio
- Freela
- PJ

#### Nível
- Júnior
- Estagiário

**Comment by Cientista-Avogadro** [comment]
Ja me inscrevi

**Comment by MiqueiasCS** [comment]
Já me inscrevi tb!

**Comment by RicarGit** [comment]
Tô dentro!

**Comment by flavi2101** [comment]
As vagas já foram preenchidas?

Em qui, 23 de jun de 2022 16:56, Ricardo Gava ***@***.***>
escreveu:

**Comment by RicarGit** [comment]
@flavi2101, a vaga não é minha e ainda não recebi resposta, então ainda deve estar aberta, tenta a sorte :)

**Comment by italoengdev** [comment]
Me inscrevi tbm
