### ISSUE TITLE
[São Paulo/SP] Front-End / FullStack Developer na [Affinibox]

### ISSUE THREAD

**Issue by natanael** [frontendbr/vagas#711]
## Descrição da vaga

Desenvolvimento em React e React Native. Temos uma aplicação whitelabel e temos mais de 20 apps publicados. Os endpoints estão todos em GraphQL há quase um ano e estamos temos abertura para adoção de tecnologias. Nosso back é Kubernetes + Docker + NGINX, rodando na Azure. 

## Local

Escritório, São Paulo - Entre a Oscar Freire e Haddock Lobo, relativamente perto da Paulista, bastante perto da estação em construção Oscar Freire.

## Benefícios

- Plano de saúde (Omint)
- Vale Refeição (~30)
- Vale Alimentação (~450)
- Vale Transporte

#### Diferenciais

- Horário flexível
- Liberdade para novas tecnologias
- Startup bastante pequena, mas com bastante estabilidade, ambiente de trabalho leve e boas amizades
- Decisões rápidas sobre tudo, bastante autonomia

## Requisitos

**Obrigatórios:**
- Experiência com Linux
- Experiência com React e tudo que normalmente o acompanha (webpack, jss, redux, yarn, jest, router, babel, etc)
- Conhecimento de React Native, principalmente das configurações necessárias (setup de Android SDK, XCode, react-native, etc)
- Experiência com NodeJS, express.js, babel, fs, scripts básicos
- Conhecimentos de web, tempos de carregamento, protocolos, SEO e etc

**Desejáveis:**
- Conhecimentos de Azure
- Experiência em design, UX, criação de wireframes
- DevOps e Backend (não é o objetivo final, mas fullstacks são sempre bem vindos)

**Diferenciais:**
- Tenha a capacidade de dialogar com o resto da empresa e propor soluções

## Contratação

CLT, salário a combinar. Não contratamos PJ, mas cogitamos trabalhar com freelancers

## Nossa empresa

A Affinibox é uma plataforma de gestão de clubes de benefícios. Oferecemos uma solução whitelabel para associações e empresas que queiram disponibilizar benefícios a seus colaboradores de forma mensurável e prática. Parte do nosso trabalho é prospectar novas parcerias e temos alguns grandes nomes. 

A composição da empresa é bastante enxuta. Somos em 8 pessoas, apenas 3 desenvolvedores. A gestão é bastante horizontalizada e as decisões são bastante rápidas. Qualquer um no time realmente tem influência em como o produto se desenvolve e como os problemas dos nossos clientes são resolvidos.

## Como se candidatar

Por favor envie um email para `natanael.guerra@affinibox.com.br` com seu CV anexo - enviar no assunto: Vaga Front-End / Fullstack

**Comment by natanael** [comment]
Não consegui adicionar os labels:
Alocado
CLT
Senior

**Comment by Finacio** [comment]
O assunto no envio do e-mail está certo?

**Comment by natanael** [comment]
Olá @Finacio, estava errado, o foco é mais FrontEnd. Trabalho pra Web-FullStack sempre temos, mas o foco pra essa vaga é alguém que consiga segurar bem as pontas de React Native

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
