### ISSUE TITLE
[REMOTO] Front-end Developer Vue.JS na BAG Sistemas

### ISSUE THREAD

**Issue by lmbagolin** [frontendbr/vagas#7113]
> Vaga Remota durante a pandemia

## Nossa empresa

A BAG Sistemas é uma empresa com foco em desenvolvimento de sistemas Web. Mesmo sendo uma pequena empresa, já trabalhamos com grandes instituições como a CNM (Confederação Nacional de Municípios) e atualmente estamos a procura de devs frontend que possam integrar nossa equipe.

## Descrição da vaga

A vaga é para trabalhos em múltiplos projetos e colaborativo com outras empresa com INÍCIO IMEDIATO. Estamos procurando devs JS com experiencia em Vue.JS que sejam PLENO ou que se encontram na transição do JUNIOR para PLENO

## Local

O trabalho é Remoto com horários flexíveis uma vez que trabalhamos sob METAS, [SC], [Florianópolis]

## Requisitos

**Obrigatórios:**
- experiência com VUE
- VUEX
- Consumo de APIs REST
- Versionamento de código com Git
- Habituado a trabalhar com metodologia ágil.

**Desejáveis:**
- PHP Laravel
- MySQL

**Diferenciais:**
- Docker
- Experiências com testes automatizados

## Benefícios

- Trabalhos Remotos
- Horários Flexíveis 

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para lmbagolin@gmail.com com seu CV e/ou experiências - enviar no assunto: Vaga VUEJS

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno

#### Cidade
- Florianópolis

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
