### ISSUE TITLE
[Remoto] Front Developer Júnior/Pleno @ Octos.ai

### ISSUE THREAD

**Issue by lpcinelli** [frontendbr/vagas#7114]
## Nossa empresa

A Octos é uma startup com a missão de construir as mais confiáveis e acessíveis ferramentas de inteligência para monitoramento (respeitando a privacidade!).

O monitoramento de hoje não é efetivo em larga escala. É impossível supervisionar centenas de câmeras e sensores com atenção. No entanto, é assim que tentam resolver o problema. Nós acreditamos que automatizar a parte braçal do trabalho é primordial para alcançar sucesso em larga escala. Os operadores devem se focar em resolver problemas e deixar a análise dos dados e das câmeras para as máquinas, que não cansam.

Nosso propósito é transformar vidas a partir da inteligência de dados e trabalhamos para construir a plataforma mais acessível e abrangente de Inteligência Artificial capaz de integrar câmeras e sensores.

**Stack relevante**: Phoenix Framework, React Typescript, Recoil, Material UI, Jest.

## Descrição da vaga

Como desenvolvedor(a) na Octos, você vai ser responsável pelo frontend (Phoenix) da nossa aplicação web. Buscamos pessoas que gostem de desafios e queiram construir algo novo.

Você vai participar ativamente no desenvolvimento da nossa plataforma, discutindo sobre os impactos das decisões no sistema e como conciliar demandas, restrições e metas. Como membro do time fundador, você terá fundamental importância na construção de todo o negócio e será autoridade no sistema.

**Suas responsabilidades envolvem:**

- Definir arquitetura de client-side
- Definir as regras de negócio e lógica pelo lado do client
- Projetar e implementar user-facing features
- Lidar com o back-end a fim de definir padrões da API
- Zelar pela qualidade com boas práticas, código limpo e alta cobertura de testes
- Corrigir bugs e manter a plataforma
- Participação na priorização de evoluções no produto

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 1 ano de experiência profissional com frontend
- Experiência com CSS, HTML, Javascript e React
- Experiência em framework de testes frontend (Jest, React Testing Library)

**Desejáveis:**
- 2+ anos de experiência profissional com frontend
- Experiência com Material UI
- Forte senso de design e layout UI/UX

**Diferenciais:**
- Conhecimento em arquiteturas em nuvem (AWS)
- Experiência com Phoenix/Elixir ou Ruby/Rails

## Benefícios

- Auxílio home-office
- Bônus anual

## Contratação

PJ (R$ 4.000 - 6.000)

## Como se candidatar

Por favor, preencha [este formulário](https://airtable.com/shr1yVFSyBC066we7?prefill_Position=recbLoZoJHN9LocfE&hide_Position=true).

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: contato@octos.ai

#### Alocação
- Remoto

#### Regime

- PJ

#### Nível
- Júnior
- Pleno

**Comment by Cientista-Avogadro** [comment]
Enviado

**Comment by lpcinelli** [comment]
up

**Comment by raphaelalmeidamartins** [comment]
Enviado :rocket:

**Comment by felipelouzeiro** [comment]
Enviado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
