### ISSUE TITLE
[REMOTO] Front-end Developer na Nave.rs

### ISSUE THREAD

**Issue by RenataRamiress** [frontendbr/vagas#7116]
> Vaga Remota

## Nossa empresa

Trabalhar com a [nave.rs](http://nave.rs/) significa que você conhece e colabora com as pessoas que realmente fazem o trabalho. Unimos tecnologia e criatividade para criar soluções digitais efetivas que se tornam memoráveis ​​e impactam positivamente a vida das pessoas.

Nossa missão é ajudar a entender as empresas antes de agir, a agir com precisão e o lucro a partir de mudanças.

Não é somente sobre digital, é sobre marcar positivamente a vida dos produtos.

O pilar principal da nossa cultura é “pessoas em lugar”, sendo assim, estamos sempre trabalhando na construção de um ambiente seguro, inclusivo e diverso, onde as pessoas gostam de estar na versão e podem ser a sua melhor. Sendo assim, independente da carga e área, focamos na empatia e no bem estar dos membros do tempo e dos nossos clientes. Pois só assim conseguimos transformar ideias em soluções.

Estamos todos os dias ajudando a construir uma [Nave](http://nave.rs/) . Então qualquer pessoa é bem-vinda.

## Descrição da vaga

Já pensou em trabalhar em um ambiente colaborativo, conseguiu, com muito aprender e autonomia? Neste momento estamos buscando uma pessoa com experiência e conhecimento para área de Front-End React.

Como na empresa temos dia a dia ágil Scrum, nos temos a empresa dia a dia ágil Scrum, nos quais vamos ter o dia a dia e nos projetos a cerimonias e nos em que.

## Local

REMOTO

## Requisitos

- Indispensável experiência profissional na área de front-end a partir de 1 ano
- Indispensável experiência com clientes;
- HTML, CSS e JavaScript
- Experiência Profissional com ReactJS
- Desejável conhecimento básico de ferramentas de gestão de tarefas
- Desejável conhecimento básico de Git e Gitflow

## Benefícios

- Assistências médica e odontológica;
- Auxilio psicológico;
- Vale Refeição e/ou Vale Alimentação;
- Aulas de inglês;
- Auxilio Educação (acesso a plataformas de cursos)

**Diferenciais:**

- Hierarquia horizontal;
- Horário flexível 

## Contratação

CLT + beneficios 

## Como se candidatar

Inscreva-se através do link: https://nave-team.gupy.io/job/eyJqb2JJZCI6MjM1NjA5NSwic291cmNlIjoiZ3VweV9wdWJsaWNfcGFnZSJ9?jobBoardSource=gupy_public_page

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.

#### Alocação

- Remoto

#### Regime
- CLT

#### Nível

- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
