### ISSUE TITLE
[Remoto] Front-end Engineer na Peoplefy

### ISSUE THREAD

**Issue by Jonas-buriti** [frontendbr/vagas#7119]
> Vaga Remota durante a pandemia

## Nossa empresa

A [Peoplefy](https://www.peoplefy.com.br/) é uma spinoff da [Simbiox](https://www.instagram.com/simbiox.br/?hl=pt-br), que apesar de ter acesso à expertise de quase 15 anos atendendo milhares de companhias, tem seu próprio DNA e objetivo.
Somos um empresa SaaS, com foco nos problemas que podemos resolver, e não na solução.
Entendemos que os diversos frameworks, metodologias, tecnologias e ferramentas são apenas um meio e não uma finalidade em si.

> Levar a cultura da empresa ao coração das pessoas

_Esse é nosso propósito! E tudo que construímos é o meio de entregar valor aos nossos clientes._

## Descrição da vaga

Em sua carreira como Front-end Engineer, você terá a oportunidade de contribuir diretamente com ambientes de trabalho, no Brasil (e mundo🤘🏼) saudáveis e produtivos.

Você participará de todo processo de concepção de nossos projetos / soluções, interagindo com os outros times desde a criação de novas funcionalidades, até as etapas de arquitetura, desenvolvimento, code-review, teste e deploy 😀

## Local
Remoto ou Escritório, SP, São Paulo, Pinheiros

## Requisitos

**Obrigatórios:**

- Foco em **soluções**, e não em _frameworks ou ferramentas._ O objetivo é entregar valor aos usuários 😉
- Conhecimento de uma ou mais estruturas front-end modernas (preferencialmente Vue.js)
- Conhecimento em TypeScript
- Domínio em HTML5 / CSS3 / SASS / Vanilla Js (ES6+)
- Conhecimento em arquitetura de software e boas práticas de desenvolvimento;
- Conhecimento  em Git & GitFlow
- Experiência com metodologias ágeis (preferencialmente Scrum)

**Desejáveis:**
- Conhecimentos em Atomic Design
- Conhecimentos em UI
- Experiência com testes automatizados e ambientes de CI/CD;
- Conhecimentos em Docker

**Diferenciais:**
- Projetos opensource
- Presença na comunidade dev

## Benefícios

- Opcional: Custeamos 60% de um plano de saúde corporativo GNDI
- Gympass
- Investimento em capacitações de acordo com necessidades do time e programas online de educação;
- Acesso gratuito à academia do prédio;
- Bonificação de aniversário + day-off
- Bonificação para alcance das metas da empresa, ou seja, a união do trabalho de toda equipe. Como falamos, a equipe que atuou em 2019 foi para Disney! Fica o mistério do que teremos para este novo ano. 🎢✨

## Contratação

PJ a combinar
Horário núcleo (100% online): 11:00 às 18:00

## Como se candidatar

Por favor envie um email para jonas@peoplefy.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Engineer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: douglas@peoplefy.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
