### ISSUE TITLE
[Front End React Developer Portugal] 

### ISSUE THREAD

**Issue by ErickaMB** [frontendbr/vagas#7121]
[Front End React Developer Portugal]               PJ/Presential You will have to move to Portugal (Liboa or Aveiro) if you are from another country. All expenses paid by the company. JR/Middle/Senior Obs: JR only from Portugal - Salary
EUR 800,00 up until EUR 3.000,00 negotiable
Company
Software Consulting founded with the mission to inspire the connection of technology with people, fostering the best of our professionals through our expertise in finding and attracting the best talent for the best projects.
What do you need?
Solve technical problems and provide innovative solutions across the
front-end, focusing on the development, customization, and optimization
of digital and cloudbased solutions.
● Translate user stories and technical requirements into functional code.
● Build and deliver software systems with Software Development Life Cycle
(SDLC) best practices including coding standards, code reviews, source
control management, build processes, testing, and operations;
● Contribute to the architecture and design of new and current systems,
including considerations such as security, reliability, and scaling;
● Participate in Agile/Scrum meetings, contributing to a better task
definition, resource allocation and effort estimation.
Experience and requirements
● Technical degree (EQF-6) required (Computer Science background is
highly desired)
● Capability to define solutions and architect mobile apps, required.
● Experience building cloud native/microservices architecture
applications and platforms;
● Experience with SOA Architectures, especially with REST, GraphQL and
SOAP,
● Experience with AWS Cloud desired.
● Experience with containerization technologies such as Docker and
Kubernetes;
● Knowledge of professional software engineering practices and the full
SDLC, including coding standards, code reviews, source control
management, build processes, testing, and operations, required;
● Ability to work with Agile Methodologies like scrum, Kanban and SAFe;
● Experience with Atlassian tools (JIRA, Confluence)
● Strong verbal and written communications skills in both Portuguese and
English
Benefits
Vacation and 13th thirteenth among other benefits Interested and fitting the profile reach me out on linkedin saying what opportunity you want to apply for. [https://www.linkedin.com/in/erickamarquesb/]

**Comment by MacaulayVitor** [comment]
[https://www.canva.com/design/DAFFvG-cp0g/Q2R7ZNwAMlDrIeSsRkyQig/view?utm_content=DAFFvG-cp0g&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink](url)
[https://macaulayvitor.github.io/Portifolio./](url)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
