### ISSUE TITLE
[Remoto] Front-end Developer na Loocal

### ISSUE THREAD

**Issue by dotpegaso** [frontendbr/vagas#7127]
## Sobre
Uma plataforma para conectar pessoas que trabalham com delivery à comércios de pequeno e médio porte. Com mais de 2 mil clientes ativos, a Loocal é uma **startup de tecnologia e logística para supply chains**, localizada em **Santos/SP**, que busca profissionais dedicados para dar suporte aos seus produtos.

Estamos procurando uma **pessoa desenvolvedora frontend** para assumir nossas duas aplicações web (backoffice & cliente) além do nosso app de entregas.

## Descrição da vaga
Nosso time é pequeno, mas bem distribuído. Como desenvolvedor frontend você não terá que se preocupar em lidar com assuntos que fujam do seu ponto de domínio.

Nossos projetos estão construídos em **React** e **React Native**.

## Local
- Remoto
- Presencial em Santos/SP (se desejar)

## Requisitos

**Obrigatórios:**
- Ao menos 1 ano de experiência com **React**
- Experiência com **Redux** e **React Hooks**
- Ao menos 3 anos de experiência com **desenvolvimento frontend**

**Desejáveis:**
- Ter conhecimento em **React Native**
- Ter conhecimento em versionamento de código (GIT)

**Diferenciais:**
- Ter conhecimento em **Styled-components**
- Ter conhecimento em **Sentry**
- Já possua projetos em React Native
- Já tenha trabalhado em uma equipe ágil

## Contratação
- Full-time com horário flexível
- **R$4k ~ R$6k**, de acordo com o nível de experiência
- PJ

## Como se candidatar
Por favor envie um email para diego.franco@loocal.online com seu CV anexado e o que mais desejar, que possa mostrar seu nível de experência - enviar no assunto: **Vaga Frontend Loocal**

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 03 dias após cada processo

#### Alocação
- Alocado (opcional)
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by Cientista-Avogadro** [comment]
Sended
