### ISSUE TITLE
[Front End Pleno ou Senior React ou Vue] 100% Remota - Inglês para conversação

### ISSUE THREAD

**Issue by ErickaMB** [frontendbr/vagas#7128]
[Front End Pleno ou Senior React ou Vue] 100% Remota - Inglês para conversação
Empresa Australiana com 3 anos na área. Salários em torno de 4.500 dólares australianos até 5.500 dólares australianos. Com bonificação anual em torno de 15.000,00 a 20.000,00 dólares Australianos.
Startup de tecnologia tentando se tornar grande, nós na verdade temos a tecnologia em tecnologia.
Estamos à procura de um desenvolvedor de front-end sênior forte, que se orgulha de escrever limpo, código elegante, robusto e eficiente. Alguém que gosta de aprender coisas novas ou descobrir melhores maneiras de fazer as coisas que nós altamente encorajamos. Nossa pilha atual é Svelte e Node.js indo completamente sem servidor, tudo hospedado na AWS usando S3, CloudFront e Lambda. Também estamos procurando
alguém que está muito interessado em aprender Svelte.
* Apenas uma observação que alguns de nossos projetos legados ainda estão em React / Preact, sim, consideramos que estão legados!
Este é um papel crítico na busca pela dominação mundial no espaço tecnológico, você será altamente recompensado pelos seus esforços em termos de salário e satisfação no trabalho.
Habilidades e experiência:
● Gosta de trabalhar com frameworks modernos, por exemplo React, Vue.js, Svelte
● Especialista em JavaScript, especialmente todos os novos recursos do ES6 / 7/8
● Forte em HTML e CSS / SASS / SCSS, pense em flexbox e CSS Grid Layout. (Nota: nós odiamos usar carros alegóricos!)
● Conhece todas as ferramentas inteligentes que ajudam a manter a base de código limpa, como
autoprefixer, babel / buble, eslint, webpack e rollup, apenas para citar alguns
● Um defensor do Test Driven Development (TDD) ou BDD
● Familiarizado com integração contínua e implantação contínua
● Conhece sistemas de controle de versão modernos, como o git
● Programação complexa, depuração de programa, análise de dados, análise de problemas e
resolução de problemas em aplicativos de código aberto.
● Fortes habilidades de comunicação e colaboração no fornecimento de direção técnica e desenvolvimento de software prático para incluir design, desenvolvimento e teste. Deveres e responsabilidades:
● Liderando o desenvolvimento, integração e manutenção de arquiteturas, requisitos,
algoritmos, interfaces e projetos para sistemas de software em tempo real
● Rever planos de teste, testes de unidade, testes funcionais com mais de 90% de cobertura de código para garantir entrega de alta qualidade
● Implementar excelência em engenharia, impondo revisões de código regulares, contínuas
integração, alta cobertura de código de teste, refatoração de código contínua e adequada documentação
● Avaliar, solucionar problemas e conduzir análises de causa raiz para problemas de produção e sistema falhas; determinar a ação corretiva e melhorias para evitar uma recorrência
● Atuar como um especialista no assunto para domínios de software, problemas específicos do sistema, processos e metodologias
● Trabalhar com designers e ferramentas de design (Figma, Zeplin etc.)
● Participar ativamente do planejamento e execução do Sprint. Outras coisas que você precisa saber sobre nós:
● Treinamento e desenvolvimento são nossa prioridade número 1
● Acreditamos no trabalho, descanso e diversão
● Gostamos de viajar de vez em quando
As experiências a seguir não são necessárias, no entanto, serão altamente consideradas:
● Experiência nas versões mais recentes do Node.js, gosta de brincar com novos recursos, como
assíncrono / aguardar
● Experiência com AWS
● Familiarizado com acessibilidade na Web (conformidade com AA)
● Experiência com controle de versão de código-fonte e solicitações pull
● Experiência com Nginx
● Conhecimento de Jasmim, Titereiro, Cipreste
● Experiência em projetar e desenvolver arquiteturas de Software como Serviço (SaaS)
Se tem interesse e com requisitos da oportunidade entre em contato pelo Linkedin informando qual é a oportunidade. [https://www.linkedin.com/in/erickamarquesb/

**Comment by gcdesigner** [comment]
Ola Ericka,  como vai?
Acredita que nivel de ingles B2 seria suficiente?

**Comment by gcdesigner** [comment]
Obs. Nao consigo falar contigo pelo linkedin. 
Se quiser, podemos falar pelo zap tb. 61 98441-7481

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
