### ISSUE TITLE
[Brasil] Front-end Developer (REACTJS) OSF Digital

### ISSUE THREAD

**Issue by talitasaldanha** [frontendbr/vagas#7129]
> Vaga Remota.

## Nossa empresa

Empresa global sólida, com mais de 19 anos de mercado;
Uma das empresas líderes em comércio global e transformação de nuvem digital;
Presença global REAL (clientes na América do Norte, América Latina, Europa e APAC);
Grandes chances de crescimento, através de um efetivo plano de carreira.

## Descrição da vaga

Exemplo: Projeto para Digital Apps (Cliente Global) em REACTJS.

## Local

Remoto.

## Requisitos

**Obrigatórios:**
- Sólidos conhecimentos de HTML 5, CSS 3 e JavaScript (ES6+);
- Sólida experiência com React, incluindo hooks;
- Experiência com pré-processadores CSS (Sass, LESS), módulos CSS e CSS em JS (Styled Components);
- Experiência com webpack 4+
- Experiência com design responsivo e mobile first;
- Experiência Git;
- Conhecimento em práticas de testes unitários;
- Conhecimento de integração de serviços utilizando APIs REST.

**Diferenciais:**
- Jest;
- Biblioteca de testes React;
- Webpack 5;
- Micro frontends;
- Conhecimento de técnicas de programação funcional;
- Experiência com sistemas de design (fonte centralizada de componentes reutilizáveis);
- Experiência com técnicas para otimizar os tempos de build e carregamento de aplicativos;
- Boas habilidades de comunicação.

## Benefícios

- Cartão flash alimentação/refeição - 1.300 por mês; Bônus educação - 150 por mês; Curso de inglês (1h - até 2x por semana) gratuito; Bônus de certificações na área de atuação pago em dólar canadense; Incentivo por entrega de projetos pago em dólar canadense; Bônus de indicação de candidatos (De 3% a 5% do salário anual - Pago em dólar canadense); Bônus de performance; Plano de carreira com avaliações de desempenho; Plano odontológico bradesco (Gratuito para funcionários); Plano de saúde top bradesco apartamento (Gratuito para funcionários e dependentes); Seguro de vida e viagem bradesco; Gympass; Empréstimo consignando; Horário flexível - 40 hrs semanais.

## Contratação

CLT.

## Como se candidatar

Por favor envie um e-mail, com pretensão salarial, para hr@osf.digital com seu CV anexado - enviar no assunto: Front-end Developer (REACTJS).

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: hr@osf.digital.

#### Alocação
- Remoto.

#### Regime
- CLT.

#### Nível
- Sênior;
- Consultor.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
