### ISSUE TITLE
[Belo Horizonte] Front-End Developer na Maxmilhas

### ISSUE THREAD

**Issue by pleaobraga** [frontendbr/vagas#713]
## Descrição da vaga
 Estamos procurando uma pessoa para trabalhar com Desenvolvimento de FronEnd aqui na MaxMilhas! Você acha que você é essa pessoa?

O que a gente precisa:

Que você seja apaixonado por tecnologia, é claro. E Tenha vontade de fazer parte de algo grandioso. Confira alguns de nossos números:

+1.200 acessos simultâneos

+100.000 visitas/dia

+3 milhões de acessos/mês

+800.000 buscas/dia.

+2.000 passagens emitidas/dia

Nosso time de Engenharia conta com pessoas motivadas para entregar um produto de alta qualidade, trabalhando em um ambiente colaborativo e leve <3
Projeto bazinga em NodeJS, etc.

No dia a dia, você será responsável por:

Desenvolver funcionalidades e ferramentas no client-side;
Manutenção e evolução de código de sistemas legados;
Integrar sistemas parceiros com dependência no client-side;
Auxiliar na implantação de testes unitários e funcionais de javascript;
Aprimoramento de usabilidade e performance nas interfaces.

## Local

Maxmilhas, Minas Gerais - Belo Horizonte

## Benefícios

- Plano de saúde
- Plano Odontológico
- Seguro de vida
- VR de R$ 21,00/dia
- 20.000 milhas nas férias

## Requisitos

**Obrigatórios:**

Requisitos técnicos obrigatórios:

 Domínio em HTML5 e CSS3 (SASS).
Conhecimento avançado em Javascript (Vanilla).
Vivência em estimar e analisar interfaces a partir de arquivos PSD e AI.
Conhecimento no task runner Gulp.

**Desejáveis:**

Conhecimento em: Webpack, SPA, React e Angular2.
Conhecimento em teste unitário (Jasmine, Jest, Karma e Selenium).
Conhecimento básico em PHP.
Conhecimento dos conceitos de Startup;
Proatividade e dinamismo ;)

## Contratação

CLT a combinar

## Como se candidatar

Se cadastrar na página https://maxmilhas.gupy.io/jobs/4674

**Comment by Carlosxell** [comment]
Remoto ??

**Comment by marimeireles** [comment]
Há interesse por parte da empresa em estagiário ou júnior?

**Comment by pleaobraga** [comment]
estágio no momento não mas junior sim, faça a inscriçao nesse link https://maxmilhas.gupy.io/jobs/4674  e boa sorte

**Comment by marimeireles** [comment]
Certo, valeu!

**Comment by pleaobraga** [comment]
Pessoal a Maxmilhas está de sede nova, eleita ano passado como Startup do ano pelo Startup Awards 2017. Estamos com vagas de front abertas ainda, bora vir trabalhar aqui.

**Comment by philipsoares** [comment]
Fala @pleaobraga beleza? Cumpro os requisitos da vaga e fiz o meu cadastro já há alguns dias e realizei a etapa 1. Porém após essa etapa não obtive nenhum feedback.

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
