### ISSUE TITLE
[Remoto] Frontend React Developer na @TQI 

### ISSUE THREAD

**Issue by eduardaolivei** [frontendbr/vagas#7130]
## Nossa empresa
Que incrível que você está aqui e tem interesse em fazer parte dos nossos times. A TQI é feita para você, sim você que quer ousar sem receio e vivenciar grandes desafios. Você fará parte de times multidisciplinares e de alta performance, em um ambiente descontraído, dinâmico e colaborativo que te proporcionará constantes aprendizados e desenvolvimento.

Aqui, você encontrará liberdade e autonomia, atuando com metodologias ágeis em projetos inspiradores. Sua voz e sua contribuição são muito importantes para nós, para a construção dos nossos produtos e também para nossas tomadas de decisões.

Não tenha receio em pedir ajuda e compartilhar novas ideias, é assim que conseguimos transformar insights em soluções extraordinárias, somos um time e juntos respiramos inovação.

E ainda vamos além do código, aqui você aprende e também tem a oportunidade de ensinar, construir e evoluir, na TQI você será protagonista da sua carreira.

Conheça mais sobre nossa empresa: https://www.tqi.com.br/

## Local
100% Remoto para Sempre!

Requisitos:

- JavaScript, CSS e HTML
- ReactJs, React Router, ContextApi e Hooks para contrução de interfaces de usuário
- Ferramentas de testes unitários tais como: Jest, Testing Library, Enzyme ou Cypress
- Usar ferramentas de empacotamento como Webpack, Rollup ou parcel
- Criar páginas web responsivas
- Usar e conhecer o que são pré-processadores e padrões de CSS

## Benefícios
Jornada de Trabalho:

⏰ Horário comercial, 8h diárias, Segunda a Sexta;
🎒 Trabalho 100% remoto.

Lista de Benefícios:

- Gympass para você e mais 3 dependentes;
- Seguro de Vida
- Acesso ilimitado a plataforma Alura para cursos e capacitação;
- Parceria com descontos em faculdades e escolas de idiomas.
- Agenda de eventos internos e externos voltados para o seu Desenvolvimento Profissional e Pessoal.

Pra quem é CLT:

- VA/VR: R$1012 /mês no cartão Flash
- Auxilio Home Office e bônus para melhoria do seu espaço de trabalho;
- Convênio Médico Apartamento e Odontológico sem coparticipação e integralmente custeado pela empresa para o Titular;
- PLR.

Pra contratos PJ:

- Contratos por prazo indeterminado e não por projeto
- 20 dias de bônus para descanso remunerado;
- Clube de Benefícios Lincard
- DIT - Seguro Profissional (Auxilio financeiro em caso de afastamento do trabalho por motivo de saúde ou por acidente).
Contratação
- PJ ou CLT

## Como se candidatar
Por favor envie um email para [talentos@tqi.com.br] com seu CV anexado - enviar no assunto: Frontend React Developer - GitHub ou
 contato (34) 8410-9077.

## Tempo médio de feedbacks
Temos um fluxo de contratação contínua, e TODOS candidatos recebem feedback de forma contínua durante o processo seletivo.
Contato em caso de não haver resposta: [alvaro.santos@tqi.com.br](mailto:alvaro.santos@tqi.com.br)

## Remuneração
Temos um budget flexível, olhamos o candidato em sua totalidade, experiência, vivência, modalidade de contratação para formalização da proposta.

## Nível
Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
