### ISSUE TITLE
[Remoto] Senior React Native Developer | PJ ou CLT - Builders

### ISSUE THREAD

**Issue by RaissaBaltazar** [frontendbr/vagas#7132]
E aí, lenda! 🤘 Aqui na Builders não existe o clima perfeito. Porém nossa cultura ajuda a voltarmos no eixo naqueles dias que nada dá certo, sabe? Sem falar que você vai vivenciar o empreendedorismo na prática. Seja em projetos, ajudando seu time com sua liderança ou nas ideias disruptivas que possam vir (e serão escutadas).  🙌

**O que te aproxima de ser uma Pessoa Builder:**

- Conhecimento em CI/CD (App Center, Fastlane);
- Conhecimento em Firebase (Analytics, Crashlytics, etc);
- Experiência em linguagens nativas e construção de bridges.

**Como Builder, você terá acesso a:**

- Oportunidades reais de empreender e impactar;
- Fazer parte de uma comunidade de empreendedores; de ponta;
- Inovação e criação liberados;
- Participar de um processo único de geração de valor;
- Contribuir na criação de métodos disruptivos;
- Colocar suas ideias no mercado, na prática! :)
- Possibilidade de Profit share em novos Negócios;

**[Junte-se ao Movimento! 💛🖤](https://jobs.kenoby.com/sejabuilder/job/senior-react-native-developer-cod-759-remoto/628fa8b1d59f8138e2196bcf?utm_source=website)**

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
