### ISSUE TITLE
[REMOTO] Mid-level Angular Developer I PJ I Pleno I Builders 

### ISSUE THREAD

**Issue by RaissaBaltazar** [frontendbr/vagas#7134]
Somos uma comunidade de pessoas que desejam aprender, evoluir, empreender e construir iniciativas que gerem valor. Nosso propósito é te ajudar a construir o seu legado e te dar insumos para solucionar problemas reais na prática. Trabalhe com autonomia e em qualquer lugar do mundo, o momento para se tornar Builder é agora! 💪

Estamos procurando uma pessoa desenvolvedora Angular para se juntar a nós na mudança que move o mundo, para que a criatividade e o crescimento possam inspirar cada vez mais pessoas a fazer mais daquilo que amam, construindo um roadmap de impacto e valor.

Aqui é o lugar onde suas ideias são bem vindas, frutos da construção do pensamento coletivo, prontas para ganharem vida.

**Tecnologias que vão gerar valor nos projetos 💻:**
- Angular (4+);
- Fluência em TypeScript;
- Forte conhecimento no consumo de APIs RESTful;
- Conhecimento da biblioteca RXJS, e programação reativa;
- Criação de layout responsivo;
- Versionamento de código com Git;
- Metodologias ágeis.

**O que te aproxima de ser uma Pessoa Builder 💪:**
- Conhecimento em Firebase (Analytics, Crashlytics, etc);
- Experiência em linguagens nativas e construção de bridges;
- Animações (Angular Animations).

**Como Builder, você terá acesso a 👀:**
- Empreender e impactar;
- Fazer parte de uma comunidade de empreendedores de ponta, o Movimento;
- Inovar e criar;
- Participar de um processo único de geração de valor;
- Contribuir na criação de métodos disruptivos;
- Colocar suas ideias no mercado :)
- Profit share em novos Negócios.

**[Junte-se ao Movimento! 💛🖤](https://jobs.kenoby.com/sejabuilder/job/mid-level-angular-developer-cod-783-remoto/62b305d52f4a5c3aa9f5fddc?utm_source=website)**

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
