### ISSUE TITLE
[Brasil] Front-end Developer na GlobalTI

### ISSUE THREAD

**Issue by DablioG** [frontendbr/vagas#7137]
> Vaga Remota durante  e após a pandemia

## Nossa empresa

A GLOBAL TI, desde 2001, vem atuando no mercado de Tecnologia da Informação prestando serviços de forma singular e personalizada para clientes de médio e grande porte dos mais variados segmentos.

## Descrição da vaga

Exemplo: Projeto em formato Squad com Java(Spring Boot)

## Local

Exemplo: Remoto para todo Brasil,

## Requisitos

**Obrigatórios:**
- Experiência com Angular2+, JS, HTML, CSS, Bootstrap

**Desejáveis:**
- conhecimentos em Java(integrações)

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para washington@globalti.com.br com seu CV anexado - enviar no assunto: Vaga Angular

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: daniele@globalti.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
