### ISSUE TITLE
[Desenvolvedores Front End Angular Pleno ou Sr] - CLT/hibrido 3 dias no escritório Interlagos - SP e 2 Remoto.

### ISSUE THREAD

**Issue by ErickaMB** [frontendbr/vagas#7138]
[Desenvolvedores Front End Angular Pleno ou Sr] - CLT/hibrido 3 dias no escritório Interlagos - SP e 2 Remoto. Perfil Pleno : R$ 8.000,00 a R$ 11.000,00 / Perfil Senior: R$ 12.000,00 a R$ 15.000,00.
Não tem teste técnico, só uma entrevista técnica com o time do banco
O que precisa?
Conhecimento de pelo menos 2 anos com Angular
Conhecimento em integrações com Java, Kafka, Elastic, RabbitMQ
Possa trabalhar regime híbrido
Experiência e requisitos
Conhecimentos Esperados:
o WebComponent (conhecimento obrigatório)
o Versão angular 8+
o Versionamento de código (Git, bitbucket)
o Conhecimento e experiência na construção de serviços RESTful;
o Conhecimento de Domain Driven Design;
o Conhecimento de Arquitetura Distribuída;
o Conhecimento de Arquitetura Orientada a Eventos e Microservices;
o Conhecimento de soluções de banco de dados relacionais e não relacionais;
o Conhecimento de Cloud Computing, especialmente Azure e AWS;
o Conhecimento de GitFlow e políticas de gestão de configuração;
o Conhecimento de Testes automatizados, Integração Contínua e Entrega Contínua;
o Conhecimento de Soluções de API Gateway;
o Devops (padrões SONAR, testes unitários, análise de erros em esteiras cloudbees)
o Conhecimento em métodos ágeis e processos de desenvolvimento de software;
o Conhecimento de técnicas eficazes de logging, troubleshooting e monitoramento.
o Perfil proativo para resolução de problemas e comunicação com demais áreas;
Empresa
Atuar num grande banco por uma consultoria internacional.
Benefícios
R$ 1.5000,00 cartão Flex mensal.
Assistência Médica;
Seguro de vida;
Assistência Odontológica;
Academia
Seguro de vida.                                                         Se tem interesse e com requisitos da oportunidade entre em contato pelo Linkedin informando qual é a oportunidade. [https://www.linkedin.com/in/erickamarquesb/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
