### ISSUE TITLE
[Brasil] Senior Frontend Developer na Bloxs Investimentos

### ISSUE THREAD

**Issue by lucasayres** [frontendbr/vagas#7140]
## Nossa empresa

A Bloxs é uma fintech de investimentos alternativos! Estamos crescendo de forma acelerada e queremos que você venha participar disso!

Nascemos com o intuito de democratizar o acesso ao mercado de capitais para empresários, parceiros de negócio e investidores.

Saiba mais em: https://bloxs.com.br

## Descrição da vaga

A Bloxs busca um(a) desenvolvedor(a) Senior Front-End para atuar na nossa Plataforma de Investimentos. Desenvolvendo sistemas Web com foco em layout e experiência de navegação do usuário.

## Local

Salvador - BA
São Paulo - SP
Remoto

## Responsabilidades e desafios

- Desenvolvimento front-end (HTML, CSS, JavaScript, Typescript, React);
- Analisar, entender demandas de negócio, prototipar, desenhar e implementar o front-end;
- Analisar tecnicamente a performance, qualidade de codificação, cobertura de testes, preparação para deploy e outros aspectos técnicos de front-end;
- Documentar padrões e processos.

## Habilidades necessárias

- Sólidos conhecimentos em HTML, CSS, JavaScript;
- Noções da linguagem backend Python;
- Noções de UX/UI;
- Noções de SEO e esteja atento ao design, acessibilidade e desempenho
- Experiência com WebServices (REST, SOAP, etc);
- Atuações em times que utilizam frameworks ágeis na gestão dos projetos, tais como, SCRUM, Lean e Kanban;
- Conhecimento com versionamento de código (GIT).

## Diferenciais

- Saber criar Wireframes;
- Conhecimentos em desenvolvimento mobile (React Native);
- Tenha experiência com ferramentas Figma;
- Possua experiência com algum framework para desenvolvimento frontend (React/VueJs/Bootstrap);
- Experiência com a implementação e manutenção de design systems.

## Como se candidatar

Envie um e-mail para jobs@bloxs.com.br com o título "Vaga Senior Frontend Developer", contendo seu currículo/portfólio e pretensão salarial.

## Labels

- 🏢 Flexível
- 👴 Sênior
- ⚖️ PJ

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
