### ISSUE TITLE
[Remoto] Front-end Developer na Visionnaire

### ISSUE THREAD

**Issue by Vilcilaine** [frontendbr/vagas#7144]
## Visionnaire Tecnologia

Visionnaire is a leading Software Development Company with headquarters in Brazil operating around the world.

We are specialized in Custom and Packaged Software Development, Software Development with Market Applications, Websites Development and Corporate Portals, Professional Services and Managed Services.

We have a 25+ years experience in software development combined with a modern lean culture and a Silicon Valley mentality. In our history we delivered more than 2,399 projects for more than 230 clients.

## Descrição da vaga
Buscamos profissional com experiência em desenvolvimento de sistema Web em plataforma Angular.

## Local

Remoto 

## Requisitos

**Requisitos Fundamentais:**

- Bom conhecimento em desenvolvimento Angular nas versões mais recentes;
- Experiência em desenvolvimento Front-end HTML, CSS, JavaScript;
- Conhecimento de APIs;
- Conhecimento de levantamento e refinamento de requisitos de sistema;
- Ter boa comunicação com o cliente para alinhamentos de dúvidas e mudanças visuais e/ou usabilidade.

**Requisito Desejável:**

- Conhecimento em PHP (Laravel).

## Contratação

PJ

## Como se candidatar

Por favor, se candidate através do link https://visionnaire.abler.com.br/vagas/desenvolvedor-a-front-end-angular-333122 ou envie um email para recrutamento_selecao@visionnaire.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Angular

## Tempo médio de feedbacks

Costumamos enviar feedbacks o mais breve possível.
E-mail para contato em caso de não haver resposta: recrutamento_selecao@visionnaire.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
