### ISSUE TITLE
[Remote] Angular Developer na Performa It

### ISSUE THREAD

**Issue by TacianySouza** [frontendbr/vagas#7145]
**Suas principais responsabilidades:**

- Desenvolver recursos visuais da aplicação;
- Criar códigos e bibliotecas reutilizáveis;
- Garantir a viabilidade técnica dos designs de UI/UX;
- Otimizar o aplicativo para velocidade e escalabilidade máximas;
- Certificar de que toda a entrada do usuário seja validada antes de enviar para o back-end;
- Colaborar com outros membros da equipe e partes interessadas.

**Você precisa ter:**
 
- Proficiente entendimento das ferramentas de versão de código como Git;
- Proficiente conhecimento de HTML5 e CSS3;
- Compreensão básica das plataformas de pré-processamento CSS do lado do servidor como LESS e SASS;
- Proficiente entendimento de scripts do lado do cliente e estruturas JavaScript;
- Bom entendimento de Angular 2+;
- Bom entendimento do processamento de solicitações assíncronas.
- Conhecimento básico de firebase e Functions
- Conhecer de node (básico);
- Conhecer de Rxjs.
- Conhecimento de Angular Material
- Conhecimento em Bootstrap.

**Nós oferecemos:**

- Convênio Médico (sem descontos)🩺
- Ajuda de custo🍽
- Day-off no mês de aniversário 🎂
- Descanso Remunerado 🏝
- Bônus Anual 💸
- Horário flexível 😎
- Jornada de Trabalho: 40h semanais 😍

Candidatura: taciany.souza@performait.com
Assunto: Dev FrontEnd

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
