### ISSUE TITLE
[Remoto] Senior Front-end Developer na DietSystem  (JavaScript) 

### ISSUE THREAD

**Issue by thiagoferreira123** [frontendbr/vagas#7150]
## Nossa empresa

Somos um software feito sob medida para atender as demandas dos profissionais nutricionistas! Estamos em fase de crescimento no mercado, procuramos por desenvolvedores para nos ajudar a melhorar a experiência do usuário em algumas partes do software.

## Descrição da vagas

O DietSystem foi desenvolvido usando JS e PHP puro, criamos o nosso próprio mini framework em cima dessas linguagens. Além de fazermos requisições ajAx com jQuey para deixar as telas reativas. 

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência com JS puro (nível senior/pleno)
- Construir e consumir controllers JS
- Experiência para reproduzir protótipos criados no figma utilizando HTML/CSS/bootstrap
- Conhecer PHP para consumir api.

**Diferenciais:**
- projetos sem exclusividade
- você faz seu horário

## Contratação

Freelancer.

## Como se candidatar

Por favor envie um email para contato@dietsystem.com.br com seu CV anexado - enviar no assunto: Vaga DietSystem. Apos receber o seu e-mail será enviado um pequeno teste para passar pela primeira fase. Caso você não esteja disposto a fazer o teste, não encaminhe o seu CV.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

## Labels
- Vanilla
- JavaSctipt

#### Alocação

- Remoto

#### Regime

- Freela

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
