### ISSUE TITLE
[REMOTO] Front-end Developer na @ Kstack

### ISSUE THREAD

**Issue by yohanlimapo** [frontendbr/vagas#7153]
## Nossa empresa

Aqui na Kstack, somos uma consultoria boutique. Atendemos clientes de diversos tamanhos e para diversas áreas da TI. No caso desta posição estamos recrutando para uma multinacional Norte Americana do ramo de TI sediada em Nova Jersey, que atua no Brasil desde 2009. Trabalhamos no formato hunt, portanto a contratação é direta com o cliente!
A posição desta vaga é Front-end, porém precisamos que aceite mexer também com Java no Back-end

## Descrição da vaga

Responsável por criar a interface de utilização de um site ou aplicação web. A camada visual das aplicações web, na qual os usuários interagem.
Criar websites, landing pages, hotsites, blogs ou aplicações web otimizadas e responsivas;
Realizar a manutenção e melhoria constante dessas plataformas;
Otimizar aplicações para garantir usabilidade;
Garantir que plataformas funcionem bem em diferentes navegadores e dispositivos;
Ajudar desenvolvedores back-end no código e solução de problemas;
Trabalhar juntamente com desenvolvedores Back-end e Web Designers para garantir os melhores visuais e funcionabilidade;
Colher feedback e trabalhar em melhorias para usuários e clientes;
Criar mockups e protótipos de qualidade;
Escrever documentações e guias claros, precisos e funcionais para o Front;
Garantir alta qualidade de plataformas e consistência com a marca;
Se manter atualizado às últimas tendências digitais da área.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 4+ anos com JAVA
- 4+ anos com JEE /Spring / Springboot/ Spring Security/ oAuth2 / Security Tokenization
- 4+ anos com Angular com Backend Java/Spring

**Desejáveis:**
- Conhecimento de OpenAPI 3 / Swagger UI / API First / RestFULL Web Services
- Integrações de sistemas e Bancos de dados Oracle 12c adiante
- Desenvolvimento de API’s e integrações com API Gateways
- Conhecimento de conteinerização Docker / Docker Compose / Kubernetes
- Facilidade de aprender e aplicar novas tecnologias sem restrições ou escolhas pessoais
- Bom conhecimento de UML design e interpretação de diagramas
- Desejável Clean Code e melhores práticas de desenvolvimento
- Conhecer Cloud AWS e ter atuado com componentes gerenciados ou não(EC-2, ECS, EKS, S3, etc) em desenvolvimento

## Benefícios

- Suporte no desenvolvimento de sua carreira, portal com diversos cursos online.
- Previdência Privada, 
- Plano Médico e Odontológico, 
- Vale refeição,
- Salário Variável

**Diferenciais:**
- Book de benefícios

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um email para yohan.limapo@kstack.com.br com seu CV anexado - enviar no assunto: Vaga Java e Angular

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@kstack.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
