### ISSUE TITLE
[Remoto] Developer Freelancer Wordpress na Proteína Digital

### ISSUE THREAD

**Issue by eduardorph** [frontendbr/vagas#7156]
Proteína Digital contrata dev Wordpress + Elementor para atuar no desenvolvimento de um novo site para um de seus clientes. É desejável que o candidato tenha experiência com desenvolvimento Wordpress com Elementor e que se sinta a vontade com a plataforma.

Se encaixa no perfil? 

Então encaminhe seu currículo com portfólio e venha fazer parte da Proteína Digital!	

#### Requisitos: 
- Javascript
- HTML
- CSS
- PHP
- Git	

#### Conhecimento sólidos em:
- Wordpress
- Plugin Elementor

#### As Principais atividades: 

Desenvolver a partir do zero um novo site Wordpress utilizando o plugin do Elementor. O layout será fornecido via Figma e o interessado precisará desenvolver as features das páginas utilizando plugins e código PHP quando necessário.

#### Soft Skills
- Proatividade;
- Organização
- Boa comunicação
- Inteligência Emocional 

#### Alocação
- Remoto

#### Regime
- Freelancer

#### Nível
- Pleno
- Senior

#### Contato:
rh@proteina.digital
Esperamos seu e-mail com o assunto [Vaga Freelancer Wordpress]

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by danielcrubens** [comment]
Enviado
