### ISSUE TITLE
[Remoto] Full-stack Developer na SEVN

### ISSUE THREAD

**Issue by kazzkiq** [frontendbr/vagas#7157]
## SEVN

<br>
<br>
<p align="center">Prazer, somos a <a href="https://sevn.technology/">SEVN</a>.</p>
<br>
<br>

<p align="center">
<img width="800" alt="Frame 2@2x" src="https://user-images.githubusercontent.com/1953194/151902767-d2961d40-05f0-44bd-978c-dc7f14f76736.png">
</p>

<br>
<br>

Olá, somos a SEVN! Uma empresa jovem, versátil, que não tem medo de adotar novas tecnologias para entregar o melhor produto a clientes exigentes!

Atuamos na criação de apps mobile, sites, PWAs, sistemas web e serviços backend para clientes de pequeno, médio e grande porte em todo o Brasil.

## Descrição da vaga

Você irá atuar em uma equipe que utiliza Node.js no back-end e SvelteKit no front-end, dentro de projetos que recebem milhões de visitas todos os meses!

Se você é uma pessoa que gosta de escrever código de qualidade, performático e bem organizado, essa vaga é para você!

Se você não tem extensiva experiência com Svelte ou SvelteKit, **não tem problema**. Conhecimento prévio em React te permite se familiarizar rapidamente com Svelte, e experiências passadas com Next.js te permitem trabalhar com SvelteKit em pouco tempo.

Então se você se julga proficiente em React ou Next.js, você também deve considerar essa vaga!

## Local

100% Remoto

## Requisitos

**Obrigatórios:**
- 3+ anos de experiência com desenvolvimento.
- Conhecimento em React, Next.js e/ou Svelte.
- Conhecimento em Express.js ou Koa.
- Conhecimento em Node.js.
- Conhecimento em criação de APIs RESTful.
- Conhecimento em TypeScript.
- Conhecimento em GIT.
- Conhecimento em SASS/SCSS.

**Desejáveis:**
- Bom conhecimento em Svelte.
- Bom conhecimento em SvelteKit ou Next.js.
- Bom conhecimento em criação de componentes e outros frameworks como React ou Vue.
- Bom conhecimento em criação de APIs RESTful bem estruturadas.
- Capacidade de gerar layouts responsivos.

**Diferenciais:**
- Conhecimento aprofundado em Svelte.
- Conhecimento aprofundado em SvelteKit.
- Conhecimento aprofundado em Koa.
- Conhecimento em [Prisma](https://prisma.io).

## Benefícios
- Menos horas de trabalho semanais (6h por dia!)
- Poucas reuniões!
- 100% remoto.

## Contratação

PJ a combinar (Vaga para Pleno/Sênior, 6h por dia, segunda a sexta).

## Como se candidatar

Por favor envie um email para vagas@sevn.technology com seu CV anexado - enviar no assunto: `Vaga Full-Stack SvelteKit`

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até **48 horas** após cada processo.
E-mail para contato em caso de não haver resposta: contato@sevn.technology

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
