### ISSUE TITLE
[Remoto] Software Engineer Frontend Sênior @Creditas 💚

### ISSUE THREAD

**Issue by creditasvagas** [frontendbr/vagas#7158]
A Creditas é uma plataforma digital focada em melhorar a vida das pessoas na América Latina em 3 ecossistemas: auto, imobiliário e benefícios corporativos.

**As nossas contratações são CLT, com diversos benefícios e 100% remotas!**

Para saber mais, clique aqui e se inscreva:  https://grnh.se/88a3b8f12us

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
