### ISSUE TITLE
[São Paulo] Front-End Developer na Monkey Exchange

### ISSUE THREAD

**Issue by shin-monkey** [frontendbr/vagas#716]
## Descrição da vaga

Estamos procurando um Desenvolvedor Frontend pleno/sênior pra fazer parte da equipe! Nossa stack é bem legal!

## Local

Escritório em São Paulo no Spaces Coworking, bem próximo a estação Fradique Coutinho. 

## Benefícios

- Possibilidade de remoto de 2 a 3 vezes por semana.

## Requisitos

**Obrigatórios:**
- HTML semântico / CSS (Flexbox)
- React/ES6 

**Desejáveis:**
- Ecossistema React (React Router, Mobx, Redux)
- Conhecimentos em Testes para aplicações React (cypress.io)
- GraphQL

## Contratação

PJ a combinar

## Nossa empresa

A Monkey aproxima compradores, fornecedores e sponsors para formarem uma grande rede, na qual compradores encontram os melhores recebíveis do mercado, fornecedores conseguem as melhores condições de venda e os sponsors fortalecem seus negócios e suas cadeias produtivas.  

## Como se candidatar

Por favor envie um email para shin@monkey.exchange com seu CV anexado - enviar no assunto: Vaga Front

**Comment by shin-monkey** [comment]
Pessoal os labels são pleno / sênior / remoto parcial.

**Comment by matheusiacono** [comment]
O email não foi enviado com mensagem de endereço não encontrado.

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
