### ISSUE TITLE
[Angular Developer JD - inglês avançado (entrevista em inglês) - 100% Remota]

### ISSUE THREAD

**Issue by ErickaMB** [frontendbr/vagas#7161]
[Angular Developer JD - inglês avançado (entrevista em inglês) - 100% Remota] - R$ 18.000,00 a R$ 22.000,00 mil PJ.
Primary Required Skills:
Minimum years of experience required
Advanced Programmer/ Team Lead (Level 3) – 10+ years of experience
Veteran Programmer (Level 4) – 7 years
Senior Programmer (Level 5) – 5 years
Juniors – not accepted in this model of Nearshore
Experience with angular life cycle hooks, angular framework, Data binding, Observables, Subjects, Behaviour Subjects (RxJS)
Hands-on experience with TypeScript, RxJs Operators, and ability to debug proficiently.
Experience with JavaScript, Jquery, JSON, Ajax.
Experience with Angular forms – Template-driven and Reactive forms
Strong expertise with HTML5, CSS3, SASS, and writing cross-browser compatible code.
Experience with RESTful APIs/SOAP APis and respective UI Integration
Familiarity with Responsive designs and at least one CSS framework (ex. Bootstrap)
Good understanding of AJAX and JavaScript DOM manipulation techniques
Experience with any one of the modern JavaScript MV-VM/MVC frameworks
Hands-on experience with writing extensive Unit Tests using automated TDD tasks
Experience with code versioning tools such as GitHub, TFS
Familiarity with modern front-end build pipelines and tools, creating configuration, build, and test scripts for Continuous Integration environment
Solid debugging experience to troubleshoot functional and performance issues in the code, AWS investigation skills.
Experience in writing complex Splunk queries, AppDynamics, triage
Experience in projects using Agile methodology, Sprint end Demos, retrospectives, KPI driven mindset
Secondary Skills - Nice to have (Full Stack Developer):
Experience in JAVA (Java 11), AWS, Spring framework
Experience in SQL and No SQL DB
Experience in AWS Cloud Platform - AWS S3, Lambda, Caching.                                                              Se tem interesse e com requisitos da oportunidade entre em contato pelo Linkedin informando qual é a oportunidade. [https://www.linkedin.com/in/erickamarquesb/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
