### ISSUE TITLE
[Remoto] Front-end Developer na @Deal 

### ISSUE THREAD

**Issue by Henriquetechrecruiter** [frontendbr/vagas#7162]
![Front Angular Pleno](https://user-images.githubusercontent.com/91859149/178060032-a9fc7352-1cc7-4950-95c7-d07a1e2fe420.jpg)

## Nossa empresa

Olá viajante, você já conhece a Deal?﻿
 
Iniciamos nossa corrida espacial em 2004, já especializada em transformação digital, mesmo quando ninguém falava sobre isso. Através da concepção e estratégia de negócio, até a implementação e evolução tecnológica (end-o-end), aprimoramos o negócio dos nossos clientes em todas as camadas, utilizando métodos ágeis para entregar soluções de TI que mudam a realidade das empresas. Somos reconhecidos pelo GPTW e ISG, e especializados em Transformação Digital, Modelos Ágeis de Gestão, Solução em Sistemas de Dados e Arquiteturas Robustas e facilmente Escaláveis.
 
A cultura Dealmaker é baseada no nosso EVP, ou seja, no compromisso que temos de ser um dos lugares mais incríveis para se trabalhar, um lugar onde as pessoas sejam protagonistas de suas histórias, onde todos tenham oportunidades iguais e onde haja respeito acima de tudo. Incentivamos a diversidade e nossas vagas são acessíveis a todas as pessoas, independente de gênero, orientação sexual, religião ou raça e se estendem ao público PCD.
Estamos em busca de um novo tripulante, para assumir a função de **Desenvolvedor Front-end - Pleno**

## Local

Brasil, atuação Remota

## Requisitos:
• Angular 11 ,Html 5, CSS 
• Micro Front End 
• Conhecimento em alguma das plataformas Cloud: 
• Cloud Pub/Sub, Rabbit MQ 
• Kubernetes 
• Docker, containers 
• API Management (API gateway, APIGEE) 
• Testes: Junit, Mockito, unitário, componente Jest, Cypress, unitario, e2e 
• Mensageria: Consumer/listeners 
• Legado: Struts, Jboss 4, Tomcat 
• Banco de dados : Relacionais e Não relacionais 
• Práticas :Prática de code review 
• Metodologia Ágil

**Obrigatórios:**
- 2 anos de experiência com Angular

**Diferenciais:**
- Atuação em Instituições Financeiras

## Benefícios
Nossos tripulantes com contratação CLT têm diversas vantagens:
• Flash benefícios
• GymPass
• Trilha de carreira
• Assistência Médica
• Assistência Odontológica
• Incentivo a certificação e qualificação

## Contratação

CLT

## Como se candidatar

Por favor envie um email para henrique.oliveira@deal.com.br com seu CV anexado - enviar no assunto: Vaga Angular - Pleno
Wpp: (11) 93099-8984

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
