### ISSUE TITLE
[SENIOR Front End Developer React or Vue with English] - Remote

### ISSUE THREAD

**Issue by ErickaMB** [frontendbr/vagas#7163]
[SENIOR Front End Developer React or Vue with English] - Remote - USD 4k-8k
We’re hiring for a talented and creative Sr. Front Entd Developer with a strong technical foundation in computer science. In this role, you will be working cross functionally with the product, design, and engineering teams on a wide variety of projects that power our unique wholesale, B2B commerce platform.
Our Sr. Front End Developer will help to design, build, and maintain our 2-way ordering platform that helps retailers and brands alike by digitizing and streamlining the buying process and taking selling to the next level.
You're also going to work on other major parts of our growing and blossoming platform, and will be joining an amazing, friendly, and diverse team. You will be responsible for architecting reusable front-end components, application performance, and monitoring. Engineers here work closely with the product and design team, and think about problems from our customers' perspective to devise the best solutions.
Qualifications
5+ years of software development experience on building modern high performance web applications
Strong Computer Science fundamentals (algorithms, data structures, databases, concurrency) - Bachelor’s degree or higher in Computer Science / related Engineering discipline from a top-tier university
Frontend experience with React or Vue - knowledge of TypeScript a plus
Experience with Node.js, Go, Java or similar backend technology.
Good understanding of frontend and backend technologies and architecture - RESTful API design, message driven applications, micro-services, relational/non-relational DBs (PostgreSQL, Mongo).
Proficient in web debugging and profiling tools with an understanding of web performance best practices
Test-driven development experience with mocks, unit and integration tests on large API-driven projects.
Strong communication and collaboration skills, team player, enjoy learning and teaching in an agile environment
Highly motivated with an eagerness to learn and grow both personally and professionally
Experience in startups, SaaS, e-commerce, fintech a plus.                                                                             Se tem interesse e com requisitos da oportunidade entre em contato pelo Linkedin informando qual é a oportunidade. [https://www.linkedin.com/in/erickamarquesb/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
