### ISSUE TITLE
[100% Remoto CLT] UI / UX Designer @ Angular e-Commerce

### ISSUE THREAD

**Issue by reichert** [frontendbr/vagas#7166]
## Vaga remota - para sempre remota
- Vaga remota CLT para fazer parte da nossa equipe
- Vaga para nível Pleno

## Nossa empresa
- Nossa empresa faz um e-commerce de nicho (para academias) e possui diversas interfaces administrativas para nosso SaaS, interfaces para o cliente final, aplicativos desenvolvidos para staff e cliente final. Somos hoje os maiores deste segmento no Brasil e competimos com soluções estrangeiras, superando em qualidade em muitos aspectos.

## Descrição da vaga
- A vaga é exclusiva para Designer UI / UX;
- O novo colaborador será envolvido no desenvolvimento de um novo produto dentro da empresa;
- O novo colaborador será envolvido na melhoria dos processos das interfaces atuais;
- O novo colaborador será envolvido na criação de novas interfaces;
- A vaga é para fazer parte da equipe e ter carteira assinada CLT;
- Nosso desejo é ter você conosco no longo prazo!

## Local
- A sede fica em Barueri - SP
- Site: https://angulare.app/

## Requisitos
**Obrigatórios:**
- já ter participado do desenvolvimento de algum produto (ex: aplicativo);
- ter ampla experiência em Figma;
- Ter ampla experiência em desenvolvimento de interfaces administrativas;

## Contratação
- Exclusivamente CLT

## Como se candidatar
- Por favor, envie um e mail para rh@angular-ecommerce.com - com seu CV anexado - enviar no assunto: Vaga UX / UI Designer

## Tempo médio de feedbacks
- Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Senior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
