### ISSUE TITLE
[São Paulo (Vila Mariana)] Jr Frontend Developer na Intelipost

### ISSUE THREAD

**Issue by lucastex** [frontendbr/vagas#717]
## Descrição da vaga

Procuramos um (ou uma) Junior Frontend Developer para integrar nosso time!

## Local

Estamos em São Paulo! Nosso escritório fica na Vila Mariana, na [Rua Dr. Amâncio de carvalho, 182](https://www.google.com.br/maps/place/Intelipost/@-23.5830751,-46.6510927,17z/data=!3m1!4b1!4m5!3m4!1s0x94ce5a2449e388d1:0x50ac48563220899c!8m2!3d-23.58308!4d-46.648904).

## Benefícios

- Remuneração competitiva + Bônus
- Assistência Médica: Amil Saúde (One Health)
- Assistência Odontológica: Metlife
- Seguro de Vida: Itaú Seguro
- Aulas de Inglês
- VT ou 50% do valor para estacionamento
- VR: 22,00 dia

## Responsabilidades:

- Antenado com tecnologias recentes e de mercado
- Participar das definições junto a equipe de backend
- Desenvolver a lógica de frontend de aplicações web, definindo e customizando as interfaces
- Criar e codificar testes automatizados (Relaxa que vamos te ajudar)
- Análise de possíveis fontes de erros e sempre corrigir os bugs de forma eficientes
- Se preocupar com os padrões de código

## Requisitos

- Experiência com JavaScript (é um plus conhecer o AngularJS), HTML5, CSS3/LESS
- Estar antenado e ligado em outros frameworks como React, Vue, Ember, MIthril, etc
- Trabalhar com gerenciadores de tasks como Gulp, WebPack
- Experiência com GIT + Métodos ágeis como Kanban ou Scrum
- Estar alinhado com conceitos de aplicações responsivas, mobile first e pixel perfect concepts
- Conhecer o conceito de testes automatizados
- Conhecer o conceito de APIs REST (JSON), para integrar as interfaces com o backend
## Contratação

CLT

## Nossa empresa

A Intelipost é uma startup de tecnologia que está revolucionando a logística no Brasil, um mercado de R$ 300B por ano com muitas ineficiências e desafios. Temos um sistema inovador que gerencia a logística para empresas do e-commerce. Já recebemos R$11 milhões de investimento até o momento, e em pouquissimo tempo já estamos colhendo grandes resultados: Em 2016 fomos selecionados como uma empresa Promessas Endeavor, também ganhamos a competição [IBM Smartcamp](https://www.ibm.com/blogs/robertoa/2016/11/intelipost-e-nazar-vencem-o-ibm-smartcamp-brasil-2016/)  com foco de Big Data e data analysis, o que nos rendeu a [realização de um Hackathon sobre Blockchain junto a IBM](https://www.ibm.com/blogs/robertoa/2017/09/intelipost-e-ibm-realizam-o-primeiro-hackathon-de-blockchain-em-startup-do-brasil/) e em 2017 fomos selecionados pela Oracle para sermos acelerados por eles no programa Oracle Startup Cloud Accelerator.

## Como se candidatar

Você deverá acessar este repositório: https://github.com/intelipost/job-frontend-developer e seguir as instruções nele ali contidas para concluir o teste. Depois de feito, basta me chamar no e-mail lucas.teixeira@intelipost.com.br que marcamos a próxima etapa. 

Fique tranquilo, sabemos que é uma vaga para uma posição junior, e iremos avaliar o resultado do teste com isso em mente. Qualquer dúvida, entre em contato com a gente pelo e-mail acima.

**Comment by Finacio** [comment]
Quanto é o salário?

**Comment by Pedro-Souza** [comment]
Tem possibilidade para ser remoto?

**Comment by danilosilvadev** [comment]
@lucastex faz entrevista via skype?

**Comment by lucastex** [comment]
@Finacio Tudo bem? Aqui na Intelipost temos 3 níveis de cada programdor onde o salário varia. Por exemplo, Progarmdor Junior I, Junior II e Junior III, Pleno I, Pleno II e Pleno III, e assim por diante. 

Esta é uma vaga aberta para Programador Junior, e iremos encaixar a pessoa em I, II ou III de acordo com o resultado do teste e os bate papos :) Se você quiser me passar em PVT a sua pretensão salarial, posso te adiantar se os cargos estão cobrindo sua pretensão.

**Comment by lucastex** [comment]
@Pedro-Souza Oi Pedro, para este momento, estamos apenas contratando presencial, quem sabe em um futuro não teremos oportunidades remotas :)

**Comment by lucastex** [comment]
@danilosilvadev Claro Danilo, sem problemas. Podemos sim seguir com as avaliações e entrevistas por skype fazendo uma última conversa presencial apenas :) Já olhou o repositório do teste? Topa tentar o desafio?

**Comment by luizgall** [comment]
@lucastex O Angular mencionado no teste é o AngularJS ou o Angular 2+?  Até quando esse teste pode ser desenvolvido? Obrigado!

**Comment by brunoosilva** [comment]
@luizgall Alterei a descrição da vaga referente ao framework, pode usar o que você se sentir mais confortável, hoje utilizamos o AngularJS 1.x mas não se preocupe com isso.

Referente o prazo, seria até o dia 08/01/2018, após essa data que será analisado os testes.

Boa sorte

**Comment by praganavictor** [comment]
Achei legal vou me candidatar

**Comment by lucastex** [comment]
Legal Victor! Estamos aguardando o envio do seu teste!

**Comment by brunoosilva** [comment]
Galera,

Ainda estamos com a vaga em aberto, aproveite e faça nosso teste. =D

Qualquer dúvida é só chamar!

**Comment by gustavorodarte** [comment]
Vi a vaga só agora, vou tentar correr para dia 8.

**Comment by brunoosilva** [comment]
Fala @gustavorodarte, tudo bem ? 

Não se preocupa se atrasar um pouco, fique a vontade.

Aguardo seu teste e boa sorte!

**Comment by lucastex** [comment]
Valeu pessoal! Fechamos a vaga! Obrigado a todos!
