### ISSUE TITLE
[Florianópolis] Senior Front-end Developer na Dynamox

### ISSUE THREAD

**Issue by rafaelDynamox** [frontendbr/vagas#7171]
## Nossa empresa

Empresa de alta tecnologia que desenvolve sistemas de monitoramento e aquisição de dados de vibração e temperatura. Especialista em análise de vibrações e monitoramento da condição de ativos industriais. Solução ideal para a manutenção preditiva. A Dynamox conta com um departamento de P&D que desenvolve sistemas completos: do hardware ao software.

## Descrição da vaga

Pessoa responsável por projetar, desenvolver, testar e manter soluções de software, realizando integrações com outros sistemas e APIs. Buscamos um pessoa com perfil de liderança técnica, e com habilidade para orientar os desenvolvedores menos experientes.

## Local

Escritório, Santa Catarina, Florianópolis, João Paulo

## Requisitos

- Excelentes habilidades de comunicação;
- Domínio dos frameworks React ou Next.js;
- Domínio de Redux, Redux-Saga e Material UI;
- Experiência implementando testes automatizados com Jest e Cypress;
- Experiência integrando aplicações front-end a APIs (micro-serviços) REST e GraphQL;
- Experiência configurando infraestrutura e ferramentas para CI/CD;
- Experiência na resolução de problemas e tarefas de alta complexidade;
- Inglês técnico avançado ou fluente (conversação, leitura e escrita).

## Benefícios

- Vale transporte OU Auxílio deslocamentos sem desconto em folha;
- Vale alimentação/refeição flexível sem desconto em folha;
- Seguro de vida global;
- Plano de saúde custeado pela empresa após o período de experiência;
- Plano odontológico custeado pela empresa após o período de experiência;
- Convênio com Farmasesi e OdontoSesi;
- Convênio GoGood - Plataforma de bem-estar;
- Atendimento com fisioterapeuta/osteopata na empresa;
- Sala de descompressão com puffs, jogos e videogames;
- Frutas e café à vontade;
- No dress code;
- A vista de nosso escritório é incrível! Empresa situada no parque tecnológico de Florianópolis

## Contratação

VAGA PRESENCIAL - CLT - 44h

## Como se candidatar

Acesse nosso portal de vagas: https://dynamox.solides.jobs/vacancies/160418#vacancyDescription

#### Nível

- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
