### ISSUE TITLE
[Remote] Fullstack Pleno L3/L4 Developer na Airbank

### ISSUE THREAD

**Issue by dbmenezes** [frontendbr/vagas#7175]
## Nossa empresa

O Airbank é uma plataforma unificada de gestão financeira para empresas pequenas e médias. A partir do uso de Open Banking para acessar contas bancárias, nós cobrimos todo o espectro de processos de finanças desde contas a pagar/receber, passando por fluxo de caixa, até a integração com sistemas de contabilidade. 

## Descrição da vaga

**Frontend development**: Você vai colaborar com UX Desingers e criar paginas em VueJS para melhorar a plataforma do Airbank

**Backend development**:  Você vai desenvolver features em NodeJS integrando API's externas e desenvolvendo recursos internos da ecosistema do Airbank

**Time**: Você vai trazer algo novo relacionado a cultura, sua história, ou experiências passadas que podem enriquecer nosso time! Nós crescemos juntos no Airbank, enquanto todos agregam a cultura do time e nós convidamos você a contribuir também!

## Local
Full remote, além do airbank oferecer escritórios presenciais em Vienna , Barcelona e Berlin

## Requisitos

**Obrigatórios:**
- Você possui experiencia com VueJS, Typescript, Postgres,NodeJS,git e integração com API's externas
- Você é altamente comprometido, focado e apaixonado por entregar produtos de alta qualidade. Nós somos uma empresa que está crescendo rápido, e desejamos que você cresca conosco.
- Inglês para comunicação e escrita

**Diferenciais:**
- projetos opensource

## Benefícios

- Remote first, com horário flexível
- Ambiente colaborativo e amigável
- Oportunidade de desenvolvimento pessoal e na carreira.
- Ajuda de custos para fazer o seu setup home office dos sonhos.
-  Salário competitivo em euros, bonus e opções de ações.

## Contratação
PJ 
L3  € 3.000
L4 € 3.750

Seu nivel de pleno vai depender do processo seletivo e resultado do desafio!

## Como se candidatar

Por favor envie um email para daniel@joinairbank.com com seu CV anexado - enviar no assunto: Vaga Fullstack Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by iamrosada** [comment]
Bom dia, esse email é apenas assim ```daniel@joinairbank``` ou ```daniel@joinairbank.com```, não está sendo possivel encontrar o user do email. Acho que está mal escrito. @dbmenezes

**Comment by dbmenezes** [comment]
> Bom dia, esse email é apenas assim `daniel@joinairbank` ? ou `daniel@joinairbank.com` ?, não está sendo possivel encontrar o user do email. Acho que está mal escrito. @dbmenezes

Valeu cara, estava errado mesmo! obrigado
