### ISSUE TITLE
[Cidade] Vaga para desenvolvedor Júnior Full Stack.

### ISSUE THREAD

**Issue by thiagoferreira123** [frontendbr/vagas#7179]
## Descrição da vaga

Trata-se de um projeto pessoal, não somos uma empresa. Precisamos de um freelancer para ajudar a finalizar alguns módulos da aplicação, por tempo indeterminado.

## Local

Remoto.

## Requisitos

**Obrigatórios:**

Certificação e comprovação em:
- PHP
- MySQL
- JS
- Requisições ajAX/jQuery
- HTML
- CSS

**Desejáveis:**
- conhecimentos em figma
- bitbucket
- git

**Diferenciais:**
- Você faz seu horário

## Contratação

Freelancer, por hora de trabalho (18,00 R$).

## Como se candidatar

Por favor envie um e-mail para contato@dietsystem.com.br envie seu portfólio ou projetos no qual já trabalhou usando as mesmas tecnologias, não olharemos currículo. 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dia após cada processo.

#### Alocação

- Remoto

#### Regime

- Freela

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
