### ISSUE TITLE
[Remoto] Lead Front-end Developer na DWS Brazil

### ISSUE THREAD

**Issue by hrdwsbrazil** [frontendbr/vagas#7180]
## Nossa empresa

A Dentsu World Services (DWS) é parte do grupo Dentsu, presente em 143 países e conta com mais de 60.000 pessoas comprometidas com nossa missão. No Brasil, em Porto Alegre/RS, atuamos como centro de tecnologia, inovação e design do grupo. Possuímos parceria com diversas agências do grupo e estamos empenhados em entregar soluções criativas e inovadoras aos nossos clientes, atendendo a projetos de desenvolvimento web e mobile.

O profissional irá se juntar ao time da DWS Brazil, podendo fazer parte de times com Estados Unidos ou com Suíça e Portugal. Nossos times são multiculturais e contam com pessoas de diversos países, levando o trabalho em grupo a um nível mais elevado e significativo. Assim, a diversidade de ideias contribui para a construção de tecnologias que revolucionam o mercado. 

## Descrição da vaga

Estamos em busca de uma pessoa desenvolvedora líder em Front end para apoiar no desenvolvimento de nossas soluções.

**Como será sua rotina?**

Como Lead Front end você será responsável por :

Compor os times com expertise em desenvolvimento front end;
Auxiliar o time nas rampas técnicas em atividades de alta complexidade;
Desenvolver os colegas em questões técnicas;
Mentorar pessoas em termos de hard e soft skills;
Projetar e desenvolver o front end de páginas web e suas aplicações;
Realizar a manutenção de códigos, através de testes e correção de erros;
Apoiar a integração com o back end do sistema.

## Local

Remoto - mas temos um escritório bonitão em Porto Alegre - RS pra quem quiser ir :) E, por vezes rolam umas excursões pra conhecer o office e integrar a galera <3 ps.: não iremos retomar pro presencial, o office é só estrutura de apoio e para quem quiser!

## Requisitos

**Obrigatórios:**

Experiência em tecnologias como HTML, Javascript e Typescript;
Experiência em frameworks de Front end, com ênfase em React;
Experiências nas bibliotecas Redux, Flux e Hooks;
Aplicação de testes unitários, Clean Code e Clean Architecture;
Familiaridade com desenvolvimento ágil;
Conhecimento no idioma inglês, comunicação verbal e escrita em nível avançado.

**Diferenciais:**
Somos uma empresa que preza pela saúde mental, work-life balance, tem programa de mentoria, canal de memes com premiação mensal, cultura de feedback e horizontalidade, budget para desenvolvimento por área. Será legal se você se identificar, participar e propagar a nossa cultura! 

## Benefícios

 Ambiente colaborativo com respeito e confiança!
Projetos globais e times multiculturais com colegas internacionais;
Todo o equipamento necessário para seu trabalho (notebook e periféricos);
Plano de saúde e odontológico;
Seguro de vida;
Mental health program;
VR/VA depositado no cartão de benefícios Flash;
Anywhere office - flexibilidade para trabalhar de onde precisar;
Auxilio home office (durante a pandemia do COVID-19);
Mobilidade;
Programa de mentoria para desenvolvimento e acompanhamento de carreira;
Participação nas tracks de desenvolvimento (com um valor a ser investido para cursos e etc) e acesso a nossa plataforma gratuita com muitos cursos para self Learning;
Aulas de inglês com professor particular;
Awesomeness Committee - envio de mimos temáticos e exclusivos;
Gympass;
Horário flexível (40h semanais)
Atuação 100% remota ou híbrida (se você quiser)

**Diferenciais:**
- trabalhamos com macbook ou Avell
- frigobar sempre cheio para quem quiser ir pro office:P
- sala de jogos + Óculos VR 

## Contratação

CLT

## Como se candidatar

Você pode fazer sua inscrição por esse link: https://jobs.kenoby.com/dwsbrazil/job/lead-front-end-developer-reactjs/62177d479d55f22892fdff50?utm_source=website 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: aline.schorn-ext@dentsu.com

#### Alocação

- Remoto

#### Regime
- CLT

#### Nível
- Especialista
- Lead

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
