### ISSUE TITLE
[REMOTE] Front-end Architect @ McFadyen Digital

### ISSUE THREAD

**Issue by VanessaAlbuquerque** [frontendbr/vagas#7182]
## McFadyen Digital

McFadyen Digital is a global Digital Commerce Agency with a 30-year history of innovation for more than 250 of the world’s top brands. We deliver digital commerce, marketplace, digital marketing, and user experience services from our offices in North America, South America, and India. Across all practices, we help our clients reach their goals by ensuring that technology is implemented strategically and adopted in a way that meets their business objectives.

Through our global delivery model, we offer our clients the competitive advantages of rapid deployment, world-class quality, and reduced costs. We have recruited the highest caliber of staff through internal global talent management team and know how to make agile delivery result in value for our clients.

Learn more about us at our website: www.mcfadyen.com

## Job Description

- Deep understanding of web service technologies (HTTP, REST, JSON) and design principles.
- Knowledge in JavaScript Design & Architectural Patterns.
- Knowledge about basic design principles
- Familiarity with consuming service-oriented architecture layers and APIs.
- Experience with highly scalable applications.
- Ability to research and quickly adopt new technologies in a dynamic working environment.
- Up-to-date with the latest news and technologies about Frontend and Backend
- Familiarity with OWASP security
- Experience in headless commerce implementation

## Local

[REMOTO]

## Qualifications

- Experience on the following core languages: JavaScript, HTML 5 & CSS
- Strong skills in programming structures, algorithms, design patterns, and standard (W3C) Web UI APIs
- Oriented to details and software best practices & patterns
- Experience with RESTful backend applications (like NodeJS/Express)
- Experience with GraphQL tools (like Apollo)
- Knowledge of the following types of frameworks/libraries/languages:
- Web Application Platforms
- Experience with React or other Single Page Application libraries;
- ES6+.
- TypeScript.
- Dependency Injection patterns.
- Async Module Definition (like AMD, requireJS, commonJS).
- CSS Pre-Processors (like SASS, LESS).
- Application state management (like Redux).
- Reactive Programming (like RxJS)
- Build tools like Webpack, Gulp, Grunt
- Minification, Aggregation, and Fingerprinting (Gulp/Grunt)
- Node (NPM)
- Experience with frameworks for Server Side Rendering (_NextJS, Express)
- Server-Side Rendering (like Express)
- API documentation using Swagger

Platforms:

- NoSQL (MongoDB, Cassandra, Redis)
- Testing frameworks (Jasmine, Karma, Protractor)
- Docker & Kubernetes, CircleCI, AWS, Heroku

**Other:**
- Cross-browser techniques.
- Experience with different databases (SQL/NoSQL)
- Experience with PWA (Progressive Web Apps)
- Mobile first implementation
- Debugging with tools like (Chrome Dev Tools, Web Inspector).
- Responsive design implementation across devices, platforms, screens, etc.
- Browser performance auditing and tuning.
- Demonstrated skills using distributed code repositories (Git, Perforce, BitBucket) with code reviews.
- Experience with UNIX systems and terminal
- Experience working within Scrum / Kanban.
- Web Accessibility.

**Mandatory advanced English skills!**

## Contratação

PJ or CLT

## How to apply

Apply now: https://smrtr.io/9WvpW

## Average time for feedback

5 days

#### Regime
- CLT
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
