### ISSUE TITLE
[Remoto] Pessoa Facilitadora em React na Resilia

### ISSUE THREAD

**Issue by Luiza2203** [frontendbr/vagas#7183]
## Nossa empresa
A Resilia é uma edtech que prepara e emprega jovens para as profissões mais quentes do mercado. Questionamos o status quo e constantemente buscamos formas mais rápidas, acessíveis e eficientes de capacitar as pessoas para as profissões mais demandadas pelas empresas. Somos apaixonados por fazer as pessoas aprenderem e por gerar uma real diferença na vida dos nossos alunos e Resilientes. 

Nossa visão é capacitar a América Latina para o século 21. Para chegar lá, precisamos resolver desafios e problemas com tecnologia e gente boa.

## Descrição da vaga
No papel de pessoa facilitadora tech, você terá o desafio de facilitar o aprendizado e desenvolvimento dos nossos estudantes para que eles cheguem preparados no mercado de trabalho. Você será responsável por facilitar o conteúdo tech (já desenvolvido internamente) do módulo, que tem duração de 5 semanas. Você também será responsável por aplicar a metodologia Resilia.

Se você não conhece a nossa metodologia, não se preocupe, todos os aprovados serão formados nela antes de entrarem em sala de aula :)

## Local
Remoto

## Requisitos
**Obrigatórios:**
- Conhecimento em:
    - ReactJS
    - Componentes de classes e eventos
    - Componentes funcionais
    - Hooks e Hooks customizados
    - React Bootstrap
    - Style Components
- Formação ou conhecimento em uma ou mais áreas a seguir: Engenharia da Computação, Tecnologia da Informação, Ciência da Computação, Sistemas para Internet, Análise e Desenvolvimento de Sistemas e/ou áreas relacionadas.
- Experiência mínima de 6 meses no mercado de trabalho
- Paixão por educação e o impacto que ela pode gerar
- Adorar se relacionar com pessoas e apoiá-las no seu desenvolvimento

**Desejáveis:**
- Experiência em monitoria, docência de cursos livres, técnico ou superior

## Contratação
PJ a combinar

## Como se candidatar
Por favor preencha [o formulário](https://docs.google.com/forms/d/e/1FAIpQLSdl1rwO7pWC0vHgzEoGNZtqthifVT6MfVWcFltPEaDkGjt1WQ/viewform)

#### Alocação
- Remoto

#### Regime
- PJ

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by Pedroporto87** [comment]
Bom dia,
Gostaria de me candidatar, sou novo aqui, não sei como vocês fazem essa interação.
Muito obrigado,
Pedro

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
