### ISSUE TITLE
[Presencial/SC] Front-end Developer na RIDERIZE

### ISSUE THREAD

**Issue by fabriciosautner** [frontendbr/vagas#7188]
## Nossa empresa

Somos uma plataforma esportiva para Ciclistas. Desenvolvemos todo o ecossistema através de experiências importantes para quem é ciclista. Estamos nos preparando para o lançamento mundial.

## Descrição da vaga

Participar do time de Front-ends responsáveis pela aplicação React Native que move a plataforma. E ser protagonista na primeira empresa brasileira com Gravador de Atividades (pedaladas) no próprio App.

Como será seu dia a dia:

- Participar de planejamento SCRUM junto com o time de desenvolvimento
- Implementar tecnologias modernas dentro de um App
- Conhecer todo o ecossistema de um aplicativo
- Entregar features usadas por milhares de pessoas todos os dias
- Evoluir na carreira de desenvolvedor trocando experiências com outros desenvolvedores
- Sentir a experiência de programar lado a lado com pessoas incríveis e divertidas

## Local

Escritório em Rio do Sul/Santa Catarina

## Requisitos

**Obrigatórios:**
- Conhecimentos em React Native

**Desejáveis:**
- Experiência com Mapas/GPS
- Typescript

**Diferenciais:**
- GraphQL
- Relay/Suspense
- Recoil
- Realm
- AppCenter

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para [pessoas@riderize.com](mailto:pessoas@riderize.com) com seu CV anexado - enviar no assunto: Vaga React Native

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 14 dias após cada processo.
E-mail para contato em caso de não haver resposta: fabricio.sautner@riderize.com

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

**Comment by robinndev** [comment]
Enviado!

**Comment by clowdcap** [comment]
CV encaminhado. Sucesso a todos
