### ISSUE TITLE
[Curitiba] Front-End Developer na [LS Tech]

### ISSUE THREAD

**Issue by eliasjak** [frontendbr/vagas#719]
## Descrição da vaga

Desenvolvimento de sistema ERP (Vue.js)

## Local

Rua Arthur Staude, 189 - Curitiba - PR

## Benefícios

- Plano de saúde
- VR de R$ 18,00/dia
- VT

#### Diferenciais
- 40 horas semanais

## Requisitos

**Obrigatórios:**
- Experiência com Vue.js, CSS3, HTML5

**Desejáveis:**
- conhecimentos em PHP, Framework Laravel.

## Contratação

CLT

## Nossa empresa

A LS Tech desenvolve sistemas customizáveis e não customizáveis, ERP, Ecommerce, etc.

## Como se candidatar

Por favor envie um email para rh@lstech.com.br com seu CV anexado - enviar no assunto: Vaga Front-End com pretensão salarial.

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
