### ISSUE TITLE
[Remoto] Front-end Developer na Empreender

### ISSUE THREAD

**Issue by serenarhempreender** [frontendbr/vagas#7190]
> Vaga Remota

## Nossa empresa

Somos uma empresa de tecnologia, Desenvolvemos software para pessoas que trabalham com e-commerce. Estamos em busca de novos profissionais para agregar ao nosso time, venha fazer parte!

## Descrição da vaga

Participar do time de Front-end responsáveis ​​por desenvolvimento e manutenção em aplicações React JS.

Como será seu dia a dia:

- Participar do planejamento semanal junto com o time de desenvolvimento

- Implementar tecnologias modernas dentro de um aplicativo

- Conhecer todo o ecossistema de um aplicativo

## Local

Remoto (Home Office).

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com desenvolvimento React JS.

**Desejáveis:**
-  Experiência com HTML, CSS e Javascript;
- Agilidade com SASS/Bootstrap;
- Experiência com Apis Rest;
- Experiência com ReactJS

**Diferenciais:**
- 

## Benefícios

- Plano de férias
- Bônus de natal
- Participação de Lucros
- Aulas de idiomas, Inglês e espanhol.
- ...

**Diferenciais:**
-  horário Flexível 

- ...

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para serena@empreender.com.br com seu CV anexado - enviar no assunto: Vaga React JS.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: daniele@empreender.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by serenarhempreender** [comment]
vaga ativa.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
