### ISSUE TITLE
[Remoto] Frontend React Developer na Samba Tech

### ISSUE THREAD

**Issue by jurussano** [frontendbr/vagas#7194]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/pessoa-desenvolvedora-react-pleno-121432251?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>SambaTech</strong> busca <strong><ins>Frontend React Developer (Pleno)</ins></strong> para agregar ao nosso time!&nbsp;</p>
<p>Procuramos alguém com propósito forte e que esteja disposta a trabalhar em ambiente colaborativo e dinâmico, pronto para crescer profissionalmente junto com a nossa equipe fora da curva! A Samba gosta de fazer a diferença sempre e nosso time é o responsável para que isto aconteça! Por isso, a gente espera que você seja uma pessoa apaixonada por tecnologia, assim com a gente! Todas as nossas vagas também se aplicam a pessoas com deficiência, então fique à vontade para se candidatar!</p>
<p><strong>Responsabilidades:</strong></p>
<ul>
<li>Definir a arquitetura e construir o frontend de sistemas e aplicações web e mobile, utilizando tecnologias atuais e atendendo requisitos de responsividade e acessibilidade na web, implementando códigos que sejam escaláveis, fáceis de manter, eficientes e elegantes;</li>
<li>Participar de projetos de desenvolvimento de novos softwares, avaliando os protótipos entregues pelo designer, planejando e implementando a estrutura e componentes da interface, utilizando para isso o framework de javascript React;</li>
<li>Apoiar e orientar a elaboração de rotinas automatizadas de testes, utilizando-se de ferramentas e padrões para os testes necessários.</li>
</ul>

## Samba Tech: 
 <p>A Sambatech é uma das empresas mais inovadoras do mundo, segundo a Fast Company, e é referência no mercado de vídeos online. Nossa empresa garante infraestrutura de alta qualidade para venda, distribuição, gerenciamento e armazenamento de vídeos e ajuda pessoas e empresas a terem mais sucesso, independentemente do seu objetivo.</p>
<p>Com suas soluções, a Samba atende diferentes tipos de necessidades relacionadas aos conteúdos audiovisuais e possui uma equipe totalmente focada em assegurar que nossos clientes tenham acesso ao que há de melhor em tecnologia para vídeos online.&nbsp;&nbsp;&nbsp;</p><a href='https://coodesh.com/empresas/samba-tech'>Veja mais no site</a>

 ## Habilidades: 
 - React.js 
- Redux 
- REST APIs
## Local: 
 100% Remoto
## Requisitos: 
 - JavaScript e no framework ReactJs; 
- Conceitos de programação assíncrona, definições de escopo (clojures), componentização e ES6+; 
- Gerenciadores de estados, incluindo Redux e seus padrões de arquitetura; 
- Conhecimento avançado em HTML e CSS, incluindo conceitos de layout, compatibilidade entre browsers e acessibilidade; 
- Aradigmas de orientação a objetos e funcional; 
- Versionamento em GIT; 
- APIs REST e testes automatizados; 
- Algumas das bibliotecas Webpack, Gulp ou Grunt; 
- Técnicas e práticas de Clean Code; 
- Equipes dinâmicas e metodologias de desenvolvimento ágeis.
## Diferenciais: 
 - GraphQL 
- Alguma biblioteca de mercado (Apollo, Relay); 
- Princípios de design de interação, UX e Design System; 
- Diretrizes de interfaces da Google (Material Design); 
- Java, Go e outras linguagens backend; 
- Bancos de dados relacionais e não relacionais; 
- Frameworks JavaScript como: Angular, Vue.js, etc.

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend React Developer na Samba Tech](https://coodesh.com/vagas/pessoa-desenvolvedora-react-pleno-121432251?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by VitorRiquelme** [comment]
Uma pergunta, o que seria pleno ?
