### ISSUE TITLE
[REMOTO] Front-end Developer na NAVE.RS

### ISSUE THREAD

**Issue by RenataRamiress** [frontendbr/vagas#7196]
> Vaga Remota durante a pandemia

## Nossa empresa

Trabalhar com a [nave.rs](http://nave.rs/) significa que você conhece e colabora com as pessoas que realmente fazem o trabalho. Unimos tecnologia e criatividade para criar soluções digitais efetivas que se tornam memoráveis ​​e impactam positivamente a vida das pessoas.

Nossa missão é ajudar a entender as empresas antes de agir, a agir com precisão e o lucro a partir de mudanças.

Não é somente sobre digital, é sobre marcar positivamente a vida dos produtos.

O pilar principal da nossa cultura é “pessoas em lugar”, sendo assim, estamos sempre trabalhando na construção de um ambiente seguro, inclusivo e diverso, onde as pessoas gostam de estar na versão e podem ser a sua melhor. Sendo assim, independente da carga e área, focamos na empatia e no bem estar dos membros do tempo e dos nossos clientes. Pois só assim conseguimos transformar ideias em soluções.

Estamos todos os dias ajudando a construir uma [Nave](http://nave.rs/) . Então qualquer pessoa é bem-vinda.

## Descrição da vaga

Já pensou em trabalhar em um ambiente colaborativo, conseguiu, com muito aprender e autonomia? Neste momento estamos buscando uma pessoa com experiência e conhecimento para área de Front-End React.

Como na empresa temos dia a dia ágil Scrum, nos temos a empresa dia a dia as cerimonias e nos projetos a cerimonias e nos em que iremos.

## Local

REMOTO

## Requisitos

**Obrigatórios:**

Experiência profissional de, no mínimo, três anos na área com projetos React
Experiência com Styled Components ou qualquer outra biblioteca de estilos, além de conhecimento avançado de css
Conhecimento do lifecycle do react, bem como boas práticas na utilização de hooks
Entendimento de API's e padrão REST, no que tange integrações com front-end
Experiência na construção de formulários utilizando bibliotecas de gestão de estado e validações. Ex: react-hook-form, formik, etc
Conhecimento de html e do funcionamento do DOM

**Desejáveis:**

Desejável experiência com frameworks server-side, como nextjs
Desejável experiência com testes unitários e e2e
Desejável experiência com clientes

## Benefícios

Assistências médicas e odontológicas;
Auxílio psicológico;
Vale Refeição e/ou Vale Alimentação;
Aulas de inglês;
Auxilio Educação (acesso às plataformas de cursos)

**Diferenciais:**

- Hierarquia horizontal
- Horários flexíveis
- Plano de Carreira 

## Contratação

CLT + Benefícios 

## Como se candidatar

Inscreva-se através do link: https://nave-team.gupy.io/jobs/2645959

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.

#### Alocação

- Remoto

#### Regime
- CLT + beneficios 

#### Nível

- Sênior
- Especialista

**Comment by paulocarmino** [comment]
Apliquei :)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
