### ISSUE TITLE
[São Paulo] Desenvolvedor Front-End Pleno

### ISSUE THREAD

**Issue by nunesdev** [frontendbr/vagas#72]
## Descrição da vaga

Projeto freela 2 ~3 meses, com possível contratação

## Local

Escritório, São Paulo - Moema

## Requisitos

**Obrigatórios:**
- Proatividade
- Flexibilidade
- JavaScript (não estamos falando de jQuery)
- Git
- API Rest
- Gulp
- Less
- Ionic ou similar
- Ter desenvolvido app híbrido

**Desejáveis:**
- AWS / Digital Ocean
- Ter publicado apps (Google Play, Apple Store)

**Diferenciais:**
- Familiaridade com back-end (PHP, Laravel)

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para nunesdev@gmail.com com seu CV anexado ou linkedIn - enviar no assunto: Vaga Frontend

**Comment by LFeh** [comment]
Rolou? :)

**Comment by camilatigre** [comment]
@nunesdev 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
