### ISSUE TITLE
[REMOTO] Front-end React Developer na Meta 💙

### ISSUE THREAD

**Issue by jenniferaqn** [frontendbr/vagas#7204]
## Nossa empresa
A Meta é uma companhia de tecnologia e inovação, focada em transformação digital (DX), que atua da definição da estratégia digital à entrega de soluções tecnológicas completas, colocando o ser humano no centro de todos os projetos. Com mais de 31 anos de mercado, a companhia tem atuação global: são 300 clientes em mais de 8 países, com uma equipe de 2,5 mil colaboradores, em 350 cidades e 14 países.

## O que você fará:
- Implementar as melhores soluções de frontend para nossos clientes de forma colaborativa, visando sempre a qualidade, performance, melhores práticas de programação, simplicidade e melhor experiência de uso para nossos produtos;

- Desenvolver, realizar testes unitários, implantar e monitorar além de garantir a qualidade e boas práticas de programação;

- Aprimorar aplicações identificando oportunidades de melhoria, fazer recomendações, projetar e implementar.

## Local
100% remoto

## Requisitos
**Obrigatórios:**
- Experiência com Reactjs e gerenciamento de estados;
- Testes unitários, integração e regressão;
- Metodologias Ágeis;
- Tooling (webpack, esbuild, vite);
- Integração via APIs Rest e Graphql;
- GitHub, Docker e customizações;
- Performance web, acessibilidadade e SEO.

**Diferenciais:**
- Experiência com Design System;
- Experiência com microfrontend.

## Benefícios:
🏥🦷 Assistência Médica, Odontológica e Seguro de Vida

📚 Capacitações: parceria com Alura, Microsoft Learn, English Club e Meta Academy - plataforma interna de treinamentos, além de parceria com escolas de idiomas

🧘🏻‍♀️ Parceria com Vittude: 40% de desconto em sessões de psicoterapia online

🤩🤑 Programa de Indicação de Talentos

## Contratação

PJ

## Como se candidatar
Conhece alguém ou se identificou com a posição? Se inscreve ou manda seu cv para ✉️: jennifer.silva@meta.com.br e vem ser meta!

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
