### ISSUE TITLE
[REMOTO] Front-end Angular Developer na Meta 💙

### ISSUE THREAD

**Issue by jenniferaqn** [frontendbr/vagas#7205]
## Nossa empresa
A Meta é uma companhia de tecnologia e inovação, focada em transformação digital (DX), que atua da definição da estratégia digital à entrega de soluções tecnológicas completas, colocando o ser humano no centro de todos os projetos. Com mais de 31 anos de mercado, a companhia tem atuação global: são 300 clientes em mais de 8 países, com uma equipe de 2,5 mil colaboradores, em 350 cidades e 14 países.

## O que você fará
- Atuar com desenvolvimento novas aplicações e manutenções de aplicações já existentes;
- Participar das reuniões diárias, contribuindo com a construção de solução do time;
- Contribuir com a escolha, avaliação e implementação de novas tecnologias.

## Local
100% remoto

## Requisitos

**Obrigatórios:**
- HTML5 e CSS3;
-  Angular 5-9;
- Habilidade com versionamento GIT e utilização GIT-FLOW.

**Desejável:**
- Conhecimento em desenvolvimento PWA.

## Benefícios

🏥🦷 Assistência Médica, Odontológica e Seguro de Vida

📚 Capacitações: parceria com Alura, Microsoft Learn, English Club e Meta Academy - plataforma interna de treinamentos, além de parceria com escolas de idiomas

🧘🏻‍♀️ Parceria com Vittude: 40% de desconto em sessões de psicoterapia online

🤩🤑 Programa de Indicação de Talentos

## Contratação
PJ

## Como se candidatar
Conhece alguém ou se identificou com a posição? Se inscreve ou manda seu cv para ✉️: jennifer.silva@meta.com.br e vem ser meta!

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
