### ISSUE TITLE
[REMOTO] Front-end React Developer (pleno) na Meta 💙

### ISSUE THREAD

**Issue by jenniferaqn** [frontendbr/vagas#7206]
## Nossa empresa
A Meta é uma companhia de tecnologia e inovação, focada em transformação digital (DX), que atua da definição da estratégia digital à entrega de soluções tecnológicas completas, colocando o ser humano no centro de todos os projetos. Com mais de 31 anos de mercado, a companhia tem atuação global: são 300 clientes em mais de 8 países, com uma equipe de 2,5 mil colaboradores, em 350 cidades e 14 países.

## Local
100% remoto

## Requisitos
**Obrigatórios:**
- JavaScript Fundamentals + ES6;
- React;
- React Native;
- Metodologias ágeis.

## Benefícios
🏥🦷 Assistência Médica, Odontológica e Seguro de Vida
💳 VA e VR
💻 Auxílio Home Office | Ajuda de Custo
💰 PLR
📚 Capacitações: parceria com Microsoft Learn, Meta Academy (plataforma interna de treinamentos), English Club, além de parceria com escolas de idiomas. 
🧘🏻‍♀️ Parceria com Vittude: 40% de desconto em sessões de psicoterapia online
🤩🤑 Programa de Indicação de Talentos

## Contratação
CLT

## Como se candidatar
Conhece alguém ou se identificou com a posição? Se inscreve ou manda seu cv para ✉️: jennifer.silva@meta.com.br e vem ser meta!

#### Regime
- CLT

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
