### ISSUE TITLE
[Remoto] Front-end Developer no Curseduca

### ISSUE THREAD

**Issue by RafaLopesMelo** [frontendbr/vagas#7207]
<p align="center">
    <img alt="Logo Curseduca"
        src="https://user-images.githubusercontent.com/60680170/95210360-cdeee480-07c1-11eb-85b0-e3db444a7249.png"
        style="max-width: 100%;">
</p>

# Vagas para developer React/NodeJS

## Nossa empresa

O Curseduca é uma empresa especializada em e-learning criada em 2013, oferecendo educação através de soluções
tecnológicas.

Possuímos uma plataforma LMS (EAD) de desenvolvimento próprio com foco na experiência de aprendizado de seus alunos,
podendo ser utilizada por produtores que promovam seus conteúdos digitais e por empresas que queiram ter uma
universidade corporativa para capacitação de colaboradores e/ou clientes.

No Curseduca você encontrará oportunidades de muito aprendizado, junto de uma equipe com forte senso de unidade e um
ambiente informal.

## Descrição da vaga

Estamos procurando um developer React/Node Júnior para iniciar nossa equipe! Este será responsável por participar de
um processo de migração da plataforma de HTML/CSS/JS/PHP para Node + React.

Perceba, com a lista abaixo, que não buscamos grande conhecimento técnico. O principal requisito, na verdade, é que
esteja disposto a aprender ao máximo e a evoluir junto da empresa.

## Requisitos

- HTML/CSS/JS;
- SQL
- Git;
- ReactJS
- NodeJS

## Diferenciais

- TypeScript
- RabbitMQ

## Local:

Vaga totalmente remota

## Contratação:

PJ com faixa salarial de R$2.000,00 a R$3.000,00

## Experiência

Júnior com pelo menos 1 ano de experiência

## Como se candidatar:

Enviar um email com a candidatura para vagas@curseduca.com com assunto "Vaga NodeJS/ReactJS". Costumamos enviar
feedbacks em até 2 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior

**Comment by tascintra** [comment]
Boa noite. O que é preciso enviar na candidatura?

**Comment by Kaiqueliira** [comment]
O Email ta retornando erro. 

We're writing to let you know that the group you tried to contact (vagas) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:

 * You might have spelled or formatted the group name incorrectly.
 * The owner of the group may have removed this group.
 * You may need to join the group before receiving permission to post.
 * This group may not be open to posting.

If you have questions related to this or any other Google Group, visit the Help Center at https://support.google.com/a/curseduca.com/bin/topic.py?topic=25838.

Thanks,

[curseduca.com](http://curseduca.com/) admins

**Comment by RafaLopesMelo** [comment]
Bom dia! Tudo bem?

@Kaiqueliira Ontem enfrentamos um problema na nossa caixa de entrada. Poderia por favor reenviar seu email? Está tudo funcionando corretamente agora :)
Perdão pelo ocorrido

**Comment by RafaLopesMelo** [comment]
Bom dia! Tudo bem?

@tascintra por favor enviar seu currículo junto de um resumo sobre você e portfolio caso tenha, obrigado!

**Comment by rafael-jordao** [comment]
Currículo enviado!

**Comment by carlaleticia** [comment]
Bom dia! Currículo enviado! 😎👩🏻‍💻

**Comment by DevCleverton** [comment]
Mensagem aparecendo no Email,5em como só ver as vagas ? Não os comentários!? notificação!

**Comment by tascintra** [comment]
Enviado! Obrigado!

**Comment by pedroGuimaSena** [comment]
Enviado o currículo

**Comment by adrianonobrega** [comment]
Enviado!

**Comment by clowdcap** [comment]
CV encaminhado. Sucesso a todos

**Comment by alezzott** [comment]
Enviado !

**Comment by RicarGit** [comment]
Só vi a vaga hoje, acabei de enviar o email, espero que ainda tenha vagas ^^

**Comment by osvaldosoares-hub** [comment]
enviado!!!

**Comment by gabrielbugarelli** [comment]
Enviado! Obrigado.

**Comment by sycrot** [comment]
Enviado!

**Comment by Babifbarbosa** [comment]
Enviado!!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by Leonardoozx** [comment]
Já encaminhei meu curriculo :)

**Comment by santos-vinicius** [comment]
Enviado!
