### ISSUE TITLE
[SÃO PAULO] Front-End Developer na BTime

### ISSUE THREAD

**Issue by FelipeBarrosCruz** [frontendbr/vagas#721]
# [Quero ser BTime!](https://github.com/Btime/QueroSerBtime)

Nossa solução é um SaaS de Gestão de Equipes Externas, atuando com PHP e NodeJS (backend), Jquery e Angular 4 (frontend) e Android Nativo e React Native (mobile). Procuramos profissionais que tenham sólidos conhecimentos de arquitetura e capacidade de pensar fora da caixa solucionando problemas de forma simples e rápida, levando-se em conta temas como segurança, tratamento de erros, separação de camadas/responsabilidades, performance, reusabilidade e aderência a padrões de projetos.

## Local

Oxigênio Aceleradora, São Paulo - SP | próximo ao metrô Marechal Deodoro

## Nossa empresa

A Btime é uma startup que está mudando a forma com que as pessoas trabalham. Fomos acelerados pela Liga AutoTech e agora pelo Oxigênio Aceleradora, com investimento da Porto Seguro e Plug and Play, e buscamos formar uma equipe qualificada e multidisciplinar para atender a crescente demanda, com objetivo de construir soluções inovadoras, onde maior valor é o sucesso de nossos clientes.

Nós oferecemos um ambiente descontraído em que todos os membros possuem a liberdade e responsabilidade de criar as melhores soluções possíveis, isso contando com o suporte de todos os membros, do estagiário até o CEO.

Se você quer mudar a vida das pessoas e a forma que elas trabalham, ou melhor, se você quer mudar o mundo =), venha com a Btime e faça parte dessa história.

## Aqui você irá

- Garantir o desenvolvimento de software com qualidade, através de integração contínua, automação de testes e profundos code-reviews;
- Construir plataformas sustentáveis e estáveis para novas ideias de produto; 
- Encontrar soluções simples e elegantes para problemas difíceis; 
- Trabalhar com TDD e Testes Automatizados; 
- Trabalhar com metodologia ágil scrum;
- Trabalhar com APIs REST;
- Trabalhar com time multidisciplinar.

### [Como me candidato?](id:ComoMeCandidato)
1. Forka esse projeto, escolha um dos testes aleatórios do [DojoPuzzle](http://dojopuzzles.com/), resolva-o com sua linguagem favorita e nos envie um e-mail para **team@btime.com.br** com o seu **fork** e o **link do problema** (link para o GitHub, BitBucket, tarball anexada, whatever). Junto do seu e-mail, adicione um link para seu curriculum, portfolio ou linkedin. Avaliaremos seu *fork* o quanto antes.<br />
**Duração:** de 30m à 2h **

2. Com hora marcada, um dos membros do nosso time entrará em contato com você por telefone ou Skype, para uma conversa descontraída sobre suas habilidades.<br />
**Duração:** de 30m à 40m **

3. Visita aqui no escritório, com uma sessão de pair-programming.<br />
**Duração:** de 1h à 1h30m **

`* Este processo pode ser alterado sem prévio aviso. Então, fique esperto com as atualizações deste README!`

`** O tempo de duração é apenas ilustrativo, mas não se prenda a ele, use o tempo que precisar! :-)`

### [Dicas Importantes](id:DicasImportantes)
Para um teste bem sucedido onde garantirá a próxima etapa, tente aplicar:

* Orientação a Objetos;
* Legibilidade de Código;
* Testes Unitários;
* Design Patterns;
* S.O.L.I.D.

### [Requisitos Básicos](id:RequisitosBasicos)
Precisamos de gente que:

* Procure o estado da arte do código, da arquitetura e do design de software, **MAS** que tenha **plena noção** de que nem sempre é possível alcançá-lo em um ambiente ágil =(;
* Tenha experiência com desenvolvimento para web;
* Que reconheça que a linguagem **&lt;escolha sua linguagem favorita&gt;** não é a melhor linguagem/solução para todos os problemas.
* Ter graduação é legal! Mas se você não for formado, não tem problema. Conhecemos vários profissionais plenamente capacitados que não são formados.

## Modelo de contrato

PJ a combinar

#### [Frontend Engineer](id:Qualificacoes-FE)
**Qualificações mínimas**
- JavaScript
- Angular 4
- HTML5
- CSS3
- SASS

**Desejáveis:**
- Git/BitBucket
- Google APIs
- Docker
- Agile/SCRUM

**Diferenciais:**
- TDD
- SOLID (object-oriented design)
- React
- VueJS
----
#### [Mobile Engineer](id:Qualificacoes-ME)
**Qualificações mínimas**
- JavaScript
- React Native
- React

**Desejáveis:**
- Git/BitBucket
- Google APIs
- Agile/SCRUM

**Diferenciais:**
- TDD
- SOLID (object-oriented design)
- Java Android Native
- Swift iOS Native

## [Nossos Links](id:Extra-Links)
* [Btime](https://btime.com.br/)

**Comment by FelipeBarrosCruz** [comment]
Labels: PJ, ALOCADO, PLENO, SÊNIOR

**Comment by FelipeBarrosCruz** [comment]
Ainda disponível!

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
