### ISSUE TITLE
[Híbrido] Desenvolvedor(A) Front-End Angular {9k -15k Clt}  @Dqrtech

### ISSUE THREAD

**Issue by isabellebecker** [frontendbr/vagas#7212]
**Desenvolvedor (A) Front-End Angular Jr, Pl, Sr** 

**Sobre a DQR TECH | Qualidade do começo ao fim**
Nascemos de uma parceria de mais de 10 anos entre seus sócios, somando a paixão por tecnologia à vontade de construir uma empresa diferente, investindo na proximidade com nossos parceiros e clientes. Somos uma consultoria especializada em Arquitetura de TI, Outsourcing de Profissionais e Hunting.

**DE ONDE VOCÊ VAI TRABALHAR?**
No formato híbrido. Precisará eventualmente ir para ao Cliente no Bairro Itaim Bibi, Faria Lima/SP.

**O QUE NOS MOVE:**
Desafios! É por isso que estamos em busca de excelentes profissionais para atuar em nossos times, no seguimento bancário.

**SEU DESAFIO SERÁ:**
Trabalhar com Real Time Bidding (RTB) e pequenas melhorias em um sistema da área financeira/bancária.

**O QUE ESPERAMOS QUE VOCÊ TENHA:**
Angular 9+
Git, Gitflow
Bootstrap
HTML/CSS/SASS/SCSS/CSS3
PostgreSQL; AWS
Testes Unitários

**QUAIS AS SOFT SKILLS SÃO IMPORTANTES VOCÊ TER:**
Comprometimento;
Perfil descontraído;
Perfil Proativo.

**O QUE OFERECEMOS PARA VOCÊ?**
Vale Refeição/Alimentação;
Assistência Médica e Odontológica;
Seguro de Vida;
Acreditamos no desenvolvimento contínuo de nossos colaboradores,
dessa forma oferecemos acesso full aos cursos da plataforma ALURA;
Auxílio-creche;
Aqui a sua indicação vale premiação;
No seu aniversário você recebe mimos;
Horário-flexível (conforme o cliente);
Contrato CLT (40 hrs semanais).

**E-mail: isabelle.becker@dqrtech.com.br**

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
