### ISSUE TITLE
[Remoto] Front-end CodeIgnither & Bootstrap  na Empreender

### ISSUE THREAD

**Issue by serenarhempreender** [frontendbr/vagas#7216]
> 

## Nossa empresa

Somos a maior empresa de dropshipping do Brasil!

## Descrição da vaga

Procuramos um(a) profissional com experiência em CodeIgniter, PHP, JavaScript, HTML, CSS , jQuery, Bootstrap.

## Local

- Remoto

## Requisitos

**Obrigatórios:**
- mais de 2 anos de experiência com desenvolvimento Bootstrap.

**Desejáveis:**
Experiência com HTML, CSS e Javascript;
Agilidade com SASS/Bootstrap;
Experiência com Apis Rest;

**Diferenciais:**
- 

## Benefícios

- Bônus de natal
- Bônus de Férias
- Aulas de Idiomas (inglês e espanhol)
- Participação de Lucros
- Biblioteca de Cursos 

- ...

**Diferenciais:**
- horário flexível
- ...

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para serena@empreender.com.br com seu CV anexado - enviar no assunto: Vaga Front End.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.
E-mail para contato em caso de não haver resposta: daniele@empreender.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by serenarhempreender** [comment]
vaga ativa

**Comment by serenarhempreender** [comment]
Gentileza fechar vaga.
