### ISSUE TITLE
[Remoto] Front-end Developer na RBR DIGITAL LTDA

### ISSUE THREAD

**Issue by jurussano** [frontendbr/vagas#7217]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/front-end-233624863?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>RBR Digital</strong> busca <strong><ins>Front-end Developer</ins></strong> para compor seu time!</p>
<p></p>
<p>Somos uma agência centrada no desempenho. Nos preocupamos em entender o seu negócio e, em seguida, criar uma solução personalizada para ajudar a atender às suas necessidades. Abordamos cada projeto com uma mentalidade de desempenho, garantindo que seu projeto funcione para você, seu usuário e sua equipe.</p>

## RBR DIGITAL LTDA: 
 <p>We’re a performance-centered web agency that cares about understanding your business, then crafting a custom solution to help meet your needs. We approach every project with a performance mindset, ensuring that your project performs for you, your user, and your team.</p>
</p>

 ## Habilidades: 
 - Javascript 
- React.js 
- REST APIs 
- Next.js
## Local: 
 100% Remoto
## Requisitos: 
 - Conhecimento em Javascript, ReactJS; 
- Conhecimento do funcionamento e integração de APIs REST; 
- Conhecimento básico em segurança de APIs (auth tokens, jwt, auth0).
## Diferenciais: 
 - Experiência com desenvolvimento orientado a Testes (TDD, BDD); 
- Conhecimento em desenvolvimento em NextJS (SSG, SSR e ISR).

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Front-end Developer na RBR DIGITAL LTDA](https://coodesh.com/vagas/front-end-233624863?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by CrisleyAlves** [comment]
A página de candidatura não existe
