### ISSUE TITLE
[Remote - London] React Developer (International Position)

### ISSUE THREAD

**Issue by JuliaToldo** [frontendbr/vagas#7220]
## Our Company 

Multinational known for building fintechs and business data platforms for all of Latin America.

## Job Description 

- Implement and improve REST APIs
- Creating modular React components that are as reusable as possible
- Collaborative work with our designers to ensure an excellent UX/UI
- Building React modular components that are reusable
- Assist in building a modular and scalable backend for our white label platform so it can be used across multiple banks and countries
- Infrastructure management via AWS and related providers across regions and customers
- Ensure data integrity, security and privacy required for financial applications
- Tests to ensure code stability and maintainability

## Local

Remote

## Requirements

**Mandatory:**

- Solid experience with Node.js and React
- Great English and communication skills (we love Slack and Hangouts)

**Differentials:**

- Knowledge and passion for UX/UI
- Experience with AWS, CircleCI and/or Docker
- Knowledge of Infrastructure as Code
- Knowledge of microservices architecture
- Experience with Typescript, typeORM (or other ORM), routing controllers or jest
- Experience in creating whitelabel solutions
- Experience working remotely and/or within a startup
- Work experience in the financial or B2B space (payments, loans, data, etc.)

## Hiring

PJ 

## How to apply

Apply for the vacancy through the following link https://forms.clickup.com/31110733/f/xndjd-3263/GXG8V7ZBMVKOYW4IC9

## Average feedback time

Average return in 7 days via application email or phone
 
#### Alocation

- Remote

#### Hiring

- PJ

#### Level

- Senior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
