### ISSUE TITLE
[REMOTO - INTERNACIONAL] Front-end Developer Sênior (Javascript, css) na REVELO

### ISSUE THREAD

**Issue by Jennifergnun** [frontendbr/vagas#7223]
**_OPORTUNIDADE: FRONT - END DEVELOPER SÊNIOR (JAVASCRIPT,CSS) - REMOTO_**
==================================================
-->- 100% REMOTO 
- OPORTUNIDADE INTERNACIONAL
- PJ
- USD A COMBINAR 

> 

**##SOBRE A EMPRESA**
 Empresa do _Texas_, possui uma plataforma que contém um dashboard criado para controlar vários aspectos do negócio. Incluindo a conexão entre empresas e fornecedores, atribuição de tarefas com alerta, pagamento de fatura com fluxo de aprovação e muito mais.

**## Descrição da vaga**
● Você será responsável por criar interfaces com React e JSON. Esta função é 90% Javascript e 10% CSS.

## Local
 Remoto [CANDIDATOS BRASILEIROS/ AMERICA LATINA]

**## Requisitos**
● 6 Anos de experiência na área 
● Inglês avançado (verbal e escrito)
● experiência com: Javascript, CSS e React.JS
● Conhecimento com uso de JSON

**## Contratação**
PJ

**## Como se candidatar**

Por favor envie um email para: jennifernunesrh.tech@gmail.com
 com seu CV 100% em inglês  - enviar no assunto: Vaga(frontend sr - JS/CSS).
 ou linkedin com versão inglês anexado
Linkedin  para contato: [linkedin.com/in/jennifer-nunes-9b1815176](https://www.linkedin.com/in/jennifer-nunes-9b1815176)

**#### Alocação**
- Remoto

**#### Regime de contratação** 
- PJ

**#### Nível**
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
