### ISSUE TITLE
[REMOTO] React.js Frontend Developer na CIBERNIX

### ISSUE THREAD

**Issue by fabricio-cbnx** [frontendbr/vagas#7224]
## Nossa empresa
- Criada em 2013, a Cibernix Tecnologia é uma empresa de integração de soluções e serviços em infraestrutura para Data Centers. A empresa se consolidou como referência no Brasil e na Europa, atuando na prestação de serviços de TI, utilizando soluções Open Source, que promovem melhor governança, gestão e segurança da infraestrutura de TI das corporações. Com profissionais experientes e constantemente capacitados, focamos em transparência, disponibilidade e excelência no desenvolvimento de soluções sob medida para cada mercado de atuação.

## Descrição da vaga
- Estamos buscando 2 (dois) React.js Frontend Developer (Nível Júnior ou Pleno), com pelo menos de 1 a 4 anos de experiência em desenvolvimento de software, para integrarem o nosso time para projetos em nossos sistemas, fazendo manutenção e suporte de frontend em aplicação React com Class components e frameworks Axios e Redux pra requisição, para início imediato. 

## Local
- Remoto

## Requisitos

**Requisitos de conhecimento técnico (intermediário/avançado) obrigatórios:**
- Domínio de React.js
- Javascript
- Domínio de HTML/CSS
- Class components
- Frameworks Axios e Redux pra requisição
- Conhecimento em API REST
- Testes unitários e ambientes de CI/CD: Jest e Enzyme
- Versionamento: Git e Gitlab

**Desejáveis:**
- Experiência com metodologias ágeis (preferencialmente o SCRUM)
- Frameworks: Next.js, Chakra e Redux-toolkit

**Diferenciais:**
- Desejável Formação Superior Completa, preferencialmente em um dos seguintes cursos: Análise de Sistemas, Ciência da Computação, Engenharia da Computação, Processamento de Dados ou Sistemas de Informação.
- Soft Skills:
  - Saber trabalhar em equipe;
  - Comunicação e bom relacionamento interpessoal;
  - Proativo, motivado e disposto a consolidar e desenvolver uma carreira profissional;
  - Pensamento analítico, lógico e crítico;
  - Sólidas habilidades de resolução de problemas;
  - Habilidade especializada para trabalhar de forma independente e gerenciar o próprio tempo;
  - Capacidade de lidar com situações ambíguas;
  - Comprometido e positivo;
  - Habilidades consultivas.

## Benefícios
- Alocação 100% remota com horário de trabalho flexível entre 07h00 e 19h00 de segunda a sexta-feira

## Contratação
- Prestação de serviços PJ Full Time com valor mensal a ser negociado

## Como se candidatar
- Favor enviar o currículo em PDF, Github e/ou Linkedin e disponibilidade para o e-mail rh@cibernix.com com o assunto "Vaga React.js Frontend Developer Remoto na CIBERNIX" para se candidatar.

## Tempo médio de feedbacks
- Costumamos enviar feedbacks em até 5 dias após cada processo.
- E-mail para contato em caso de não haver resposta: feedback@cibernix.com

#### Alocação
- Alocado 100% Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

**Comment by DevCleverton** [comment]
### "Vaga React.js Front-end Developer Remoto na @CIBERNIX"
**Enviado!**

**Comment by SaMatheus** [comment]
Qual o valor minimo do salário que estão dispostos a pagar?

**Comment by adrianonobrega** [comment]
Enviado!

**Comment by clowdcap** [comment]
CV encaminhado. Sucesso a todos

**Comment by alezzott** [comment]
Enviado

**Comment by waldisson** [comment]
Enviado

**Comment by EriickFraga** [comment]
Enviado

**Comment by Kaiqueliira** [comment]
Enviado!

**Comment by Ericckm** [comment]
CV Enviado.

**Comment by icarobteles** [comment]
Currículo enviado, desde já, agradeço imensamente pela oportunidade e aguardo ansiosamente pelo retorno! Até breve,

**Comment by sycrot** [comment]
Enviado!

**Comment by calvitoria** [comment]
Enviado! :rocket:

**Comment by Babifbarbosa** [comment]
Enviado!!

**Comment by lnabesima** [comment]
Currículo enviado!

**Comment by AlekGDEV** [comment]
CV enviado!

**Comment by matheuslei** [comment]
Enviado! 🚀

**Comment by AndersonKeller** [comment]
Enviado, aguardando muito!

**Comment by Thiago-Mota-Santos** [comment]
CV enviado!

**Comment by WelllWas** [comment]
Enviado!

**Comment by sucodelarangela** [comment]
Enviado!

**Comment by JailsonSantos** [comment]
Enviado com sucesso. Obrigado pela oportunidade.

**Comment by joaovictorfs09** [comment]
Enviado com sucesso. Obrigado pela oportunidade.

**Comment by FeRiffo** [comment]
Enviado!

**Comment by rafaelsiqeira** [comment]
Enviado!

**Comment by sucodelarangela** [comment]
Essa vaga ainda se encontra aberta? Foi postada em julho de 2022...

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
