### ISSUE TITLE
[REMOTO] Front-end Developer Senior - Pacifica Continental

### ISSUE THREAD

**Issue by leticiaamf7** [frontendbr/vagas#7229]
## Nossa empresa 🌎

Pacifica Continental é uma empresa de recrutamento global especializada em cargos estratégicos, tais como membros da diretoria, c-suites, gerentes superiores e intermediários. Nossas soluções personalizadas e abordagem consultiva garantem a seleção dos melhores talentos do mercado.

Nossas operações alcançaram mais de 50 países, incluindo mais de 250 cidades ao redor do mundo. Orgulhamo-nos de trabalhar com precisão e conhecimento em uma ampla gama de indústrias. Sempre comprometidos com a obtenção de uma visão industrial contínua, fazemos parcerias com um grande número de empresas multinacionais e locais.
Desenvolvendo uma forte interface entre nossas operações, entregamos soluções globais com uma abordagem local.

## Descrição da vaga 📢

Nosso cliente está procurando um Front-end Developer Sênior para integrar sua equipe de maneira REMOTA. O profissional se concentrará em desenvolver e manter aplicações funcionais a longo prazo, no mercado de pagamentos.

## Local ✈

Trabalho remoto.

## Requisitos ✔

- Bacharelado em Ciência da Computação, Engenharia da Computação, disciplina relacionada ou experiência prática equivalente.

- Compreensão proficiente de HTML5 e CSS3. Entendimento sobre semântica e acessibilidade, pré-processadores CSS, como LESS e SASS e experiência com CSS-in-JS, como styled-components, stitches ou outro;

- Excelente conhecimento sobre JavaScript;

- Conhecimento sobre frameworks e bibliotecas JavaScript, como ReactJS, AngularJS, VueJS;

- Compreensão proficiente sobre os padrões de gerenciamento de estado, como Flux e State Machine;

- Compreensão proficiente sobre design patterns e as melhores práticas de desenvolvimento de software;

- Experiência com desenvolvimento de testes unitários, integração e e2e.

## Contratação ✨

Preferencialmente CLT (PJ negociável) 

## Como se candidatar 💻

Se identificou com a vaga? Você pode se inscrever aqui pelo link: https://recruitcrm.io/apply/16585154488610013316AJV

## Tempo médio de feedbacks ✅

Costumamos enviar feedbacks em até 3 dias após cada processo.

Em caso de dúvidas, ou demora no retorno durante o processo é possível contato via linkedin no perfil: https://www.linkedin.com/in/marcoantoniomaiolino-0826751a7/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
