### ISSUE TITLE
[São Leopoldo/RS] Sr Front-End Developer na CWI Software

### ISSUE THREAD

**Issue by alereisdoerfer** [frontendbr/vagas#723]
## Descrição da vaga

Atuar no desenvolvimento de aplicações para as mais diversas áreas.

## Local

Sede CWI, Rio Grande do Sul - São Leopoldo

## Benefícios

- Plano de saúde;
- Seguro de vida;
- VT;
- VR;
- Apoio educação;
- Apoio certificação;
- Benefícios flexíveis.

#### Diferenciais

- Possibilidade de trabalhar com as mais diversas tecnologias atendendo clientes dos mais variados segmentos;
- Nossos times são compostos por profissionais de alta performance, referência na área.

## Requisitos

**Obrigatórios:**

- Necessário conhecimento avançado em HTML5, CSS3 e Sass;
- Conhecimento de TypeScript, Angular e BootStrap;
- Conhecimento de Bower, NPM e Gulp;
- Prática de desenvolvimento de Layouts Responsivos;
- Conhecimento dos padrões Web (W3C);

**Desejáveis:**

- Integrações entre sistemas via API (REST e WEBSERVICE);
- Desenvolvimento cross-browser;
- SEO (Otimizações para mecanismos de busca).

**Diferenciais:**

## Contratação

CLT

## Nossa empresa

Desenvolvemos soluções e sistemas de TI com base nas necessidades específicas de empresas de médio a grande porte em âmbito global, desde 1991.

O ambiente da CWI é pensado nos mínimos detalhes para que projetos e sonhos de vida sejam colocados em prática, com liberdade criativa e incentivo à inovação.

Na CWI, todos têm liberdade para transmitir seus conhecimentos e competências entre todas as áreas, para que juntos sejam construídos projetos de qualidade superior.

Os projetos da CWI motivam as equipes a darem o seu melhor, pois o crescimento pessoal e profissional se reflete no resultado final para as marcas que atendemos.

## Como se candidatar

Por favor envie um e-mail para work@cwi.com.br com seu CV anexado - enviar no assunto: Vagas Front-End. Você ainda pode cadastrar o currículo através do site https://cwi.com.br/Oportunidades

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
