### ISSUE TITLE
[REMOTO] Fullstack Developer [Pleno ou Sênior] @ C&R (Startup)

### ISSUE THREAD

**Issue by rzorzal** [frontendbr/vagas#7231]
## Nossa empresa

Somos uma startup pequena onde nossa equipe ainda é composta de 4 pessoas onde mantemos 3 projetos ativos. Estamos estruturando uma equipe para tomar conta de todos os projetos da empresa e estruturando novos projetos para novos clientes e projetos próprios onde você pode tomar boa parte das decisões nos projetos. Atendemos clientes de grande porte como a ArcelorMittal (projeto que envolve IA, geolocalização e estruturação de projeto), médias empresas como Máximus Soluções (projeto que nasceu com a C&R e hoje a manutenção e evolução do projeto é o principal foco do cliente) e pequenas empresas com projetos rápidos e bem documentados. Ainda não temos site ou redes sociais, mas contamos com vocês para avançarmos juntos e dominar o mercado de desenvolvimento de sistemas inteligentes usando inteligência artificial e ciência de dados com uma boa interface e fácil manutenibilidade.

## Descrição da vaga

Estamos a procura de um dev que consiga ser organizado e tenha mentalidade de crescimento que ajude a equipe a avançar e criar não uma empresa, mas sim uma comunidade. O foco dessa vaga é alguem que consiga além de codar e ter uma conhecimento nas ferramentas, consiga sugerir mudanças nos projetos e decidir os caminhos que a equipe irá seguir. Não nos importamos em quanto tempo você está em frente do computador, nos importamos nos resultados obtidos e na pessoa que irá seguir conosco. 

## Local

Remoto, empresa possui sede em Vitória, ES

## Requisitos

**Obrigatórios:**
- Nodejs
- AWS
- REACT
- Sequelize
- MongoDB
- PostgreSQL
- Redis
- Git e Github

**Desejáveis:**
- Python
- Heroku
- PWA

**Diferenciais:**
- Projetos opensource

## Benefícios

- Contratação PJ
- Horário de Trabalho flexível
- Sua opinião será levada em consideração pois o time é pequeno
- Líder ainda é um desenvolvedor

## Contratação

PJ, salário entre 4k e 8k dependendo da experiência

## Como se candidatar

Por favor envie um email para admin@cerconsultoria.com com seu LinkedIn e Github - enviar no assunto: Vaga Fullstack Developer
Você receberá um e-mail explicando os próximos passos que serão:

1. Análise dos perfis nas redes sociais passadas (LinkedIn e Github)
2. Desafio offline (coisa de 1 dia você resolve o desafio)
3. Entrevista online com a equipe (Não tomamos a decisão sozinhos e se você passar, sua opinião também será importante nos próximos processos seletivos)
4. Contratação e inicio nos projetos

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: ricardozorzaldavila@gmail.com (e-mail pessoal, somente enviar caso não seja respondido em 2 dias)

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
