### ISSUE TITLE
[Remota] Front-end Developer na Zallpy Digital

### ISSUE THREAD

**Issue by MaluFrontino** [frontendbr/vagas#7233]
[Remota] Front-End Developer na Zallpy Digital

Nossa empresa:

Transformar o futuro de pessoas e empresas com inovação e soluções digitais: esse é o nosso propósito.

Suprimos as necessidades de desenvolvimento de produtos digitais customizados e com alto valor agregado, inovando em processos, ferramentas e conceitos.

 Aliamos tecnologias de alto desempenho e atuais no mercado com a expertise de uma equipe multidisciplinar formada por especialistas no segmento.

Com inovação, a Zallpy Digital traz pra o mercado um espaço de trabalho único onde os times sentem-se à vontade para entregar o seu melhor.

Na Zallpy é possível vivenciar na prática todas as etapas do ciclo de desenvolvimento de um novo produto, para isso é necessário que você tenha muita iniciativa, vontade de aprender e ensinar.

Valorizamos o trabalho em equipe, as interações humanas e prezamos pela nossa autonomia como time e como produto. 

Se você gosta de se desafiar, entregar resultados e sentir o impacto do seu trabalho no mercado global, a dica é: #VemSerZallpy.

Nesta oportunidade, você estará atuando em projeto internacional junto de uma squad ágil de um dos 3 maiores players do setor automotivo.

Se identificou? Queremos te conhecer!

Aproveite para conhecer melhor a Zallpy Digital clicando aqui 👉 https://zallpy.com/ 😉

Descrição da vaga:

**RESPONSABILIDADES E ATRIBUIÇÕES**

- Trabalhar em diferentes aspectos do SDLC para os produtos da área financeira do cliente: Design, desenvolvimento, exploração, testes, análise de requisitos, etc;
- Trabalhar no redesign de websites para uma nova arquitetura em microserviços on cloud;
- Apoiar os diversos desenvolvimentos, integrações, testes e manutenção técnica dos produtos de SW dos serviços financeiros do cliente;
- Desenvolvimento utilizando orquestração de conteiners como Docker e Kubernetes;
- Atuar em ferramentas de CI/CD/DevOps como: GitHub e Bitbucket;
- UX/UI provida por outra equipe do cliente;
- Inglês avançado (conversação e escrita).

**REQUISITOS E QUALIFICAÇÕES**

**Requisitos Frontend**

- Experiência avançada em desenvolvimento de software no FrontEnd;
- Experiência com desenvolvimento Single Page Application utilizando Angular/TypeScript;
- Forte skills HTML/CSS/FrontEnd design com Angular 13 e 14;
- Experiência na integração de frontend com backend, API;
- Experiência convertendo especificações de design em HTML/CSS utilizando Abstract / Figma / Adobe XD;

**Requisitos DevOps**

- Desenvolvimento de aplicações na nuvem em AWS;
- Experiência com orquestração de containers como Docker e Kubernetes.

**INFORMAÇÕES ADICIONAIS**
Será diferencial:

- Experiência criando APIs utilizando .Net (Backend).

## Local: 100% remoto

**Benefícios**

- Plano de saúde
- Plano Odontologico
- Seguro de vida
- VR de R$ 27,00/dia
-  Equipamento fornecido pela empresa

**Contratação**

CLT

## Como se candidatar:

Por favor envie um email para maria.frontino@zallpy.com com seu CV anexado - enviar no assunto: Vaga Front-End Angular

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: maria.frontino@zallpy.com

**Nível:**
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
