### ISSUE TITLE
[Remote - EUA] Senior Full Stack Developer (International Position)

### ISSUE THREAD

**Issue by JuliaToldo** [frontendbr/vagas#7235]
## Our Company

Our client is a crossposting software that was created to solve the daily problems of millions of sellers. 

## Job Description

- Building frontend features using React and Node@latest

- Working directly with product designers, to build, maintain and improve slick user interfaces across devices

- Building backend microservices on GCP

- Pushing our thinking on core architecture choices

- Improving and maintaining our distributed architecture

- Maintaining automated test suites and ensuring quality in your code

- Review your colleagues’ work on pull requests.

- Use your extensive experience to train and mentor other developers on the team.

## Local

Remote

## Requirements

**Mandatory:**

- Solid years of working on both front-end and back-end

- Very strong level of English

- You have experience iterating on products from end-to-end (full feature).

- Working with NoSQL databases: Firestore/MongoDB

- Javascript and UI development, ideally with React JS - unless you have significant Javascript experience with other libraries.

- Working with REST APIs

- Unit testing with Jest

**Differentials:**
- Worked with Ebay, Etsy, or Stripe APIs

- Mobile app development experience

- Worked at a successful startup before

- Having worked with Google Chrome Extensions

## Benefits:

- Profitable and a YC funded company, provide job stability
- Small team size of 30
- 100% Remote
- Health, Dental, Vision Insurance 100% covered by
- Yearly stipend for home office
- $500 yearly educational stipendfor courses of your choice

## Hiring

PJ 

## How to apply

Apply for the vacancy through the following link: https://forms.clickup.com/31110733/f/xndjd-3743/WM2MPI2LZKJ5XKYV0H

## Average feedback time

Average return in 7 days via application email or phone

## Labels
- Full Remote
- PJ
- Senior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
