### ISSUE TITLE
[Remoto] Tech Lead Frontend na Grupo Selpe

### ISSUE THREAD

**Issue by blankapf** [frontendbr/vagas#7236]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/tech-lead-frontend-101056653?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>Grupo Selpe</strong> está buscando <strong><ins>Tech Lead Frontend</ins></strong> para compor seu time! <br> <br>O Desenvolvedor atuará globalmente e ativamente em iniciativas que promovem a transformação digital na empresa e nos seus clientes, dando todo suporte necessário para garantir o correto ciclo de vida dos produtos digitais que são responsabilidade do Squad que participa. <br><br>Desenvolve, acompanha, analisa, controla e dá manutenção nas soluções digitais, sendo estas <em>on premisse</em> ou <em>on the cloud</em>, garantindo desempenho, disponibilidade e confiabilidade, através da atualização dos softwares e da inovação dos recursos tecnológicos e sistemas, contribuindo para o melhor desempenho dos processos produtivos e de negócio.<br><br></p>

## Grupo Selpe: 
 <p>Há 56 anos conectando pessoas e empresas aos seus propósitos.&nbsp;</p>
<p>Somos o elo entre profissionais e empresas, trabalhando com a atração, seleção consultoria e tecnologia em RH das mais diversas formas.&nbsp;</p><a href='https://coodesh.com/empresas/grupo-selpe'>Veja mais no site</a>

 ## Habilidades: 
 - React Hooks 
- Typescript 
- Angular 
- CSS 
- HTML 
- Javascript
## Local: 
 100% Remoto
## Requisitos: 
 - Conhecimento em tecnologias frontend (CSS, HTML, Javascript, Typescript, Angular, React Hooks, Styled components); 
- Conceitos de usabilidade e experiência do usuário (UX/UI); 
- Ensino Superior Completo; 
- Inglês intermediário; 
- Controle de versão – git.
## Diferenciais: 
 - Programação - Tecnologias Mobile (Ionic, Cordova, Flutter, etc); 
- Ferramentas de computação em nuvem, data lake, serverless, big data e integração de dados; 
- CI/CD - Conceitos de tarefas automatizadas, análise de artefatos; 
- Inglês avançado; 
- Metodologias gestão de projetos agéis (Kanban, SCRUM, etc).

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Tech Lead Frontend na Grupo Selpe](https://coodesh.com/vagas/tech-lead-frontend-101056653?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
