### ISSUE TITLE
[Brasil] Front-end Developer Pleno e Senior (React) no BeerOrCoffee

### ISSUE THREAD

**Issue by Leticiapsi2021** [frontendbr/vagas#7237]
> Vaga 100% remota

## BeerOrCoffee - o maior marketplace de coworking da América Latina.
Você já sonhou em trabalhar de forma 100% remota e poder viver toda a liberdade e flexibilidade que esse modelo de trabalho oferece? Imagina ter +1.000 espaços ao redor do Brasil e poder trabalhar de onde quiser?
Se você ainda não conhece, somos uma plataforma que conecta empresas a espaços de trabalho em todo Brasil proporcionando maior liberdade, eficácia e inteligência na forma de trabalhar.

## Descrição da vaga

Se você é um profissional colaborativo, comprometido, criativo, flexível, dedicado, organizado e proativo, estamos te esperando para se juntar ao time de PEDD do BeerOrCoffee. Conosco, você irá aprender, colaborar e ensinar a cada dia com um time fora da curva!

**Antes de tudo, esperamos que você:**
Tenha uma mentalidade positiva e orientada para a solução;
Esteja sempre em busca por desenvolvimento pessoal e ajuda a quem está à sua volta;
Tenha iniciativa para conceber e implementar soluções de todo porte;
Valoriza as diferenças e respeita todas as pessoas;
Se conecta com a missão de construir sonhos para parceiros e clientes do BeerOrCoffee;
Tenha habilidades de comunicação eficazes;
Auto-gerenciamento, auto-motivação e grande capacidade organizacional.

## Local

100 % remoto (pode residir em qualquer localidade do Brasil)

## Requisitos

**Obrigatórios:**
Experiência profissional com framework web JavaScript (React e/ou AngularJs );
Experiência em desenvolvimento de software voltado para qualidade (TDD ou BDD);
Experiência usando Git em um ambiente profissional/local de trabalho;
Experiência com equipes ágeis (Kanban, scrum,XP);
Experiência com Pré-processador CSS (LESS/SASS);
Experiência com ferramentas de automatização (GULP, WebPack e afins);
Sólida compreensão dos conceitos semânticos de HTML, CSS e JavaScript;
Sólida compreensão dos conceitos básicos de web e browser;

**Desejável que esteja familiarizado com:**
Escrita de testes automatizados;
Habilidade em design de aplicações pensando em boas práticas de integração, performance e segurança;
Desenvolvimento mobile usando React Native;
Experiência com mentoria de novos membros do time;
Prévia experiência em startups ou Marketplace.
Inglês para leitura e escrita.

## Benefícios
✈️ Trabalho Remoto (Be #anywhere);
🎒 Kit Anywhereoffice (Você pode adquirir mochila, mouse, teclado, headset que desejar para o seu conforto no remoto);
🔑 OfficePass (Remoto não precisa ser apenas homeoffice, você terá acesso ilimitado a mais de 1000 coworkings);
🛫 BeerOrCoffee Wings (ajudamos no custo das suas viagens);
☕ Caju (Nosso cartão contempla as categorias: 🥗 alimentação, 🍴 refeição, ⛽mobilidade, 📚 educação e 🏠 ajuda de custo homeoffice)
🏋️‍♀️ Gympass (plano de assinatura de academias e diversas atividades físicas);
🏥 Plano de Saúde & Odontológico;
👶🏽 Auxílio Creche;
💖 Head of Love (cuidando do bem-estar dos nômades);
🏖️ Annual BeerOrCoffee Retreat (Nosso encontro presencial dos nômades)
💰 Bonificação trimestral (exceto áreas que tenham comissão);
💰PLR
🥪 Snack Time (quando estiver trabalhando de algum dos nossos espaços, peça um lanche por nossa conta);
📖 12 minutos (app de livros);

## Contratação
CLT ou PJ a combinar

## Como se candidatar

https://beerorcoffee.gupy.io/job/eyJqb2JJZCI6MjYzNTM5Mywic291cmNlIjoiZ3VweV9wdWJsaWNfcGFnZSJ9?jobBoardSource=gupy_public_page

## Tempo médio de feedbacks

Costumamos enviar feedbacks após cada etapa do processo.
E-mail para contato em caso de não haver resposta: leticia.franca@beerorcoffee.com

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
