### ISSUE TITLE
[Hibrido / Florianópolis] Desenvolvedor Front-End na Blendus Tecnologia em Saúde

### ISSUE THREAD

**Issue by blankapf** [frontendbr/vagas#7243]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-frontend-134458623?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>Apresentação</strong></p>
<p>Nossa missão é tornar informações em saúde mais confiáveis. Desenvolvemos soluções para garantir a qualidade dos dados na saúde suplementar (operadoras de planos de saúde) e atender aos requisitos do padrão TISS e IDSS.</p>
<p><strong>Oportunidade</strong></p>
<p>Esta oportunidade é para atuar como desenvolvedor Front End. Irá atuar numa equipe dinâmica, colaborativa e focada na entrega de valor para os clientes através das melhores práticas e tecnologias.&nbsp;</p>
<p></p>
<p><strong>Responsabilidades</strong></p>
<ul>
<li>Colaborar com demais profissionais de TI para definição de padrões e arquitetura de software;</li>
<li>Entender as especificações de requisitos e como elas se traduzem em uma aplicação de software;</li>
<li>Implementar funcionalidades com base nas especificações;</li>
<li>Realizar testes unitários e de integração antes da liberação de versão;</li>
<li>Documentar as decisões de projeto de software e de implementação.</li>
</ul>
<p></p>

## Blendus Tecnologia em Saúde: 
 <p>A Blendus é uma empresa com base tecnológica focada na governança de dados regulatórios em saúde suplementar. Nosso propósito é tornar as informações em saúde mais confiáveis e qualificadas para facilitar a transformação digital no setor, contribuindo para decisões assertivas que possam influenciar a melhoria assistencial à saúde dos beneficiários.</p>
<p>Atuamos na resolução de problemas das operadoras de planos de saúde que precisam melhorar a tratativa das guias de atendimento TISS. Fazemos análise, validação e qualificação destes dados, em conformidade ao Padrão TISS. As avaliações e relatórios gerados pelo Gestor IDSS oferecem transparência e previsibilidade nos resultados de desempenho das operadoras.</p><a href='https://coodesh.com/empresas/blendus-tecnologia-em-saude'>Veja mais no site</a>

 ## Habilidades: 
 - HTML 
- Angular 
- Typescript 
- Javascript 
- CSS
## Local: 
 Florianópolis
## Requisitos: 
 - Experiência em desenvolvimento com HTML, CSS e Javascript; 
- Experiência em desenvolvimento com framework Angular (7+) e Typescript; 
- Conhecimento em RESTful; 
- Formação superior completa em Análise de Sistemas, Sistemas de Informação, Ciência da Computação e afins.
## Diferenciais: 
 - Conhecimento/experiência com PrimeNG e AG Grid.
## Benefícios: 
 - Jornada reduzida; 
- Plano de saúde e odontológico integral (para o colaborador e 1 dependente); 
- Vale Alimentação/Refeição; 
- Auxílio home-office; 
- 1 dia de folga no mês do aniversário.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Desenvolvedor Front-End na Blendus Tecnologia em Saúde](https://coodesh.com/vagas/desenvolvedor-frontend-134458623?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Regime
CLT
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
