### ISSUE TITLE
[Portugal] Front-end Developer na Kwan

### ISSUE THREAD

**Issue by SusanaCS23** [frontendbr/vagas#7247]
KWAN is part of the RUPEAL group.
We’re a company, a.k.a. tech addicts, that specializes in the art of professional fulfillment, making sure that anyone who works with us is on the right path for achieving their career motivations! 

We are currently looking forward to hiring an enthusiastic Frontend Developer to be part of our team!

If you have:

More than 3 years working as a Frontend developer;
Experience with React, Angular and/or VueJS frameworks;
Experience integrating with RESTful APIs;
Hands-on experience on automation processes to build and deploy (CI/CD) through Jenkins/Git.
Experience in testing, documenting and debugging code;
Resident in Portugal or available for relocation;
Fluent english.
What do we offer:

A safe and respectful work environment
A lot of Tech Meetups
Health insurance 
Remote friendly environment 
Team building activities 
Training Budget 
This is the way, a.k.a Custom Career Plan
Contact me via email [susana.silva@kwan.pt]

If this sounds like the right next step for your career, run for the link below!!
https://bit.ly/3je1oxT

#### English
- B2

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
