### ISSUE TITLE
[REMOTO] Tech Lead | Pacifica Continental 

### ISSUE THREAD

**Issue by leticiaamf7** [frontendbr/vagas#7255]
## Nossa empresa 🌎

Pacifica Continental é uma empresa de recrutamento global especializada em cargos estratégicos, tais como membros da diretoria, c-suites, gerentes superiores e intermediários. Nossas soluções personalizadas e abordagem consultiva garantem a seleção dos melhores talentos do mercado.

Nossas operações alcançaram mais de 50 países, incluindo mais de 250 cidades ao redor do mundo. Orgulhamo-nos de trabalhar com precisão e conhecimento em uma ampla gama de indústrias. Sempre comprometidos com a obtenção de uma visão industrial contínua, fazemos parcerias com um grande número de empresas multinacionais e locais.
Desenvolvendo uma forte interface entre nossas operações, entregamos soluções globais com uma abordagem local.

## Descrição da vaga 📢

Nosso cliente está procurando um TECH LEAD para integrar sua equipe.

## Local ✈

Remoto.

## Principais responsabilidades ✅

- Gerenciar o time de desenvolvimento garantindo cadência e qualidade das entregas. 

- Deve ser visto como uma referência técnica pelo seu time e é esperado que desenvolva funcionalidades, revise código e conduza decisões de arquitetura;

- Colaborar ativamente com o Product Manager para avaliar a viabilidade das tarefas, escolher a melhor estratégia em relação esforço vs. prazo na alocação das histórias com o time e priorizar a tarefas e débitos técnicos. 

- Garantir que as cerimônias ágeis aconteçam regularmente sem gargalos no processo de desenvolvimento;

- Fazer a gestão e mentoria direta do time, facilitando e conduzindo sessões regulares de one-one, garantindo que estejam constantemente se desenvolvendo, engajados e motivados. Deve ainda avaliar a performance do time e ajudar na construção de planos de desenvolvimento individual;

- Responsável pela disponibilidade, escalabilidade e níveis de serviço dos sistemas. Ser parte ativa na resolução de problemas e incidentes em produção;

- Garantir um padrão elevado de qualidade, empregando as melhores práticas de engenharia de software, como code review, pair programming, tdd, criando um ambiente que as pessoas desenvolvedoras se orgulhem.

## Requisitos✔

- Mais de 7 anos de experiência em desenvolvimento de software (web/mobile);

- Ter desenvolvido com Typescript por pelo menos 1 ano.

- Fortes habilidades de comunicação;

- Sólida experiência em gerenciamento de times ágeis de desenvolvimento de produto;

- Visão estratégica de negócios;

- Gostar de questionar o status quo e lidar com ideias de diferentes stakeholders.

## Será considerado um plus ✨

- Familiaridade com padrões de acesso a dados CQRS;

- Experiência com AWS;

- Experiência em nosso Tech Stack em geral (typescript, node, nest, python);

- Experiência em pagamentos

- Inglês técnico.

## Contratação💸

Preferencialmente CLT, podendo ser PJ.

## Como se candidatar 💻
Se identificou com a vaga? Você pode se inscrever aqui pelo link: https://recruitcrm.io/apply/16572059510560019299hGD

## Tempo médio de feedbacks 📌
Costumamos enviar feedbacks em até 3 dias após cada processo.

Em caso de dúvidas, ou demora no retorno durante o processo é possível contato via linkedin no perfil: 
https://www.linkedin.com/in/paloma-cavalcante-batista-gomes-46415241/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
