### ISSUE TITLE
[100% Remoto] Front-end Developer Angular na SambaTech

### ISSUE THREAD

**Issue by daiaoli** [frontendbr/vagas#7256]
## Nossa empresa

A Samba está buscando uma **Pessoa Desenvolvedora Frontend Angular (Pleno/Sênior)** para agregar ao nosso time! Para essa oportunidade buscamos uma pessoa para atuar em regime **PJ e 100% remoto**. Procuramos alguém com propósito forte e que esteja disposta a trabalhar em ambiente colaborativo e dinâmico, pronto para crescer profissionalmente junto com a nossa equipe fora da curva! A Samba gosta de fazer a diferença sempre e nosso time é o responsável para que isto aconteça! Por isso, a gente espera que você seja uma pessoa apaixonada por tecnologia, assim com a gente! Todas as nossas vagas também se aplicam a pessoas com deficiência, então fique à vontade para se candidatar!

## Local

Remoto, Brasil.

## Requisitos

**Obrigatórios:**

- Javascript, HTML5 e CSS3 (Bootstrap, Sass e Less); 
- Ter conhecimento em versionamento de código (GIT);
- Angular, Bootstrap, CSS e Typescript;
- Ter boa comunicação e capacidade de trabalho em equipe;
- Seguir as tendências do mercado e que ser capaz de se adaptar rapidamente a novas tecnologias;
- Ter senso de organização, atenção a detalhes e foco.

**Diferenciais:**

- Tiver noções de docker e linux;
- Tiver noções de cloud (AWS) e bancos No-SQL;
- Já tenha trabalhado em uma equipe ágil.

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para **daiana.oliveira@sambatech.com.br** com seu **CV anexado + pretensão PJ** - enviar no assunto: **Vaga Angular**
## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.
E-mail para contato em caso de não haver resposta: **daiana.oliveira@sambatech.com.br**

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
