### ISSUE TITLE
[100% Remoto] Mobile  Kotlin e Java (Pleno/Sênior) na SambaTech

### ISSUE THREAD

**Issue by daiaoli** [frontendbr/vagas#7258]
## Nossa empresa

A Samba está buscando uma pessoa **Desenvolvedora Mobile  Kotlin e Java (Pleno/Sênior)** para agregar ao nosso time! Para essa oportunidade buscamos uma pessoa para atuar em regime **PJ e 100% remoto**. Procuramos alguém com propósito forte e que esteja disposta a trabalhar em ambiente colaborativo e dinâmico, pronto para crescer profissionalmente junto com a nossa equipe fora da curva! A Samba gosta de fazer a diferença sempre e nosso time é o responsável para que isto aconteça! Por isso, a gente espera que você seja uma pessoa apaixonada por tecnologia, assim com a gente! Todas as nossas vagas também se aplicam a pessoas com deficiência, então fique à vontade para se candidatar!

## Local

Remoto, Brasil.

## Requisitos

**Obrigatórios:**

- Kotlin e Java
- Padrõe de Projeto;
- SQL;
- NoSql;
- GIT
- REST;
- Micro Serviços;

**Diferenciais:**

- Metodologias ágeis (preferencialmente, Scrum);
- Noções de UX/UI;
- Tecnologias de vídeos online.

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para **daiana.oliveira@sambatech.com.br** com seu **CV anexado + pretensão PJ**- enviar no assunto: **Vaga Mobile**

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.
E-mail para contato em caso de não haver resposta: **daiana.oliveira@sambatech.com.br**

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
