### ISSUE TITLE
[São Paulo/ Remoto] Front-end Developer na Talentify.io

### ISSUE THREAD

**Issue by Mendesgabrielaa** [frontendbr/vagas#7260]
> Vaga 100% Remota 

## Nossa empresa

Somos uma empresa que conecta de forma inovadora os candidatos aos seus futuros empregos dos sonhos. E, além disso, preparamos os nossos clientes nessa jornada através de nossa plataforma de microlearning.

## Descrição da vaga

Reportando-se ao líder técnico do projeto em que o profissional estiver alocado, o desenvolvedor front-end é responsável por atuar nos componentes e interfaces que integram com nossas APIs, para estruturar as telas da plataforma que serão utilizadas pelos nossos clientes e candidatos.
Além disso, será responsável pelo desenvolvimento de testes unitários automatizados para os componentes individuais, e testes ponta-a-ponta.

## Local

100% Remoto 

## Requisitos

**Obrigatórios:**
- 2 anos ou mais de experiência com Desenvolvimento em Javascript para o Front-End
- Vue.Js
- Nuxt.Js
- Typescript
- Pré processador ou pós processador CSS

**Diferenciais:**
- conhecimentos em Testes Automatizados
- conhecimentos em VueX
- Gestão Horizontalizada
- Inglês técnico

## Benefícios

- Plano de saúde
- Plano Odontológico
- Seguro de vida
- VR de R$26 /dia
- VA de R$250/mês...

## Contratação

CLT ou PJ a combinar

## Como se candidatar

Por favor envie um e-mail para rh@talentify.io com seu CV anexado - enviar no assunto: Vaga Front End

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: gabriela.mendes@talentify.io

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno

**Comment by sycrot** [comment]
Enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
