### ISSUE TITLE
[Remoto] Front-end Developer na SONDA

### ISSUE THREAD

**Issue by Carlosxell** [frontendbr/vagas#7265]
## Nossa empresa

Saiba mais sobre no [nosso linkedin](https://www.linkedin.com/company/sonda/about/)

## Descrição da vaga

Projeto interno com Stack voltada para o VueJs, estamos migrando um sistema antigo para tecnologias web e junto a isso estamos criando um Design system para os futuros projetos internos e identidade própria.

## Local

100% remoto. Nossa squad tem pessoas de todo o Brasil.

## Requisitos

**Obrigatórios:**

- **HTML5 + CSS3** ( **Obs**: Utilizamos HTML semântico e nos preocupamos bastante com leitores de tela e o modo de exibir a informação para todos os usuários, também buscamos alguém antenado a novas especificações do CSS como container queries e semelhantes )
- **Javascript**
- **VueJs** (Versão 2.6, porém já estudamos utilizar a versão 3 no futuro)
- **Vuex e Vue Router**
- **Vuetify**
- **Jest** 
- **GIT**

**Desejáveis:**
- Conhecimento em **Storybook**
- Conehcimento em **TypeScript**
- Um olho atento a **Perfect Pixel**
- Conhecimento em **Docker, Kubernetes e Azure**
- Estar de olho em novos frameworks tais quais **Svelte** ( estamos de olho nele como tecnologia secundária nesse momento )
- **Figma**

**Diferenciais:**
- Vontade de crescer na empresa

## Benefícios

- Plano de saúde
- Plano Dentário
- Seguro de vida
- VR
- VA

## Contratação

CLT.

## Como se candidatar
Por favor, envie um e-mail com CV anexado, link do Linkedin ou portfólio para [carlos.oliveirai@sonda.com](mailto:carlos.oliveirai@sonda.com). Enviar no assunto: Vaga Dev. Front-end [ Nível desejado ], costumamos dar um retorno em até 3 dias úteis.

## Tempo médio de feedbacks

Até 3 dias úteis.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by Carlosxell** [comment]
@felipefialho , vaga atualizada, pode retirar a label de "júnior" por favor ?

**Comment by ViniciusPosssatto** [comment]
@Carlosxell  tu acredita que acabei de te enviar um email para vaga júnior? Quando abri a postagem ainda estava disponível para júnior kk

**Comment by lucaspmarra** [comment]
Enviei e-mail dia 08 e não obtive nenhum retorno, seja negativo ou positivo... acredito que esse período de 3 dias não fez muito jus...

**Comment by Carlosxell** [comment]
Galera, a demanda de currículos enviados terminou sendo maior que o que esperávamos e possivelmente alguns podem ter ficado sem resposta, mas estamos ainda procurando responder a todos, mesmo após esse tempo maior do que o esperado.
