### ISSUE TITLE
[Remoto] Front-end Developer - Shopify - na Binary Future

### ISSUE THREAD

**Issue by rodolfomussio** [frontendbr/vagas#7268]
A Binary Future atua no setor de e-commerce e hoje atende uma gama de clientes espalhada ao redor do mundo, uma empresa ucraniana que possui um pequeno mas dedicado grupo de desenvolvedores que se ajudam mutuamente e entregam resultados amplamente satisfatório aos seus clientes.

É neccessário que o candidato tenha bons conhecimentos com as tecnologias WordPress, ao menos 4 anos de trabalho.

Necessário inglês intermediário +.

## Descrição da vaga
You will have the opportunity to:

🔹Work on various e-commerce projects and see amazing e-stores growing from the ground up, thanks to you.
🔹Get the mentorship of our experienced developers and develop your professional and personal skills.
🔹Meet our incredible team members coming from 4 countries and join a hugely collaborative working environment where every person’s viewpoint is considered.

What are your strongest skills?
🔹Shopify (Liquid), Shopify API, JavaScript
- vanilla/jquery/basic React/Vue PHP
- version 7 (preferable 8 ) Database
- any SQL database (MySql or MariaDB, Postgresql) Cache
- Redis/Memcached (preferably but not mandatory)
🔹HTML 5, CSS 3 (SASS, LESS good to have)
🔹Responsive design,
🔹GIT (at least basic commands) 
🔹Open-mindedness and flexibility

## Local

100% Remoto

## Requisitos

**Obrigatórios:**
- 3/4 anos de experiência com WordPress

Contato:
rodolfomussio@gmail.com

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
