### ISSUE TITLE
[Remoto] ReactJS Developer na Onesight

### ISSUE THREAD

**Issue by kamiarc** [frontendbr/vagas#7269]
## Nossa empresa

A Onesight é uma multi-nacional com foco em desenvolvimento de tecnologias disruptivas e bleeding edge, atuamos com diversos clientes em múltiplos mercados e tecnologias.
No Brasil nossas atividades se concentram em outsourcing, e-commerces e plataformas customizadas.

## Descrição da vaga
Atuação em uma plataforma custom com foco em Next / React.JS, a vaga é principalmente frontend, porém temos preferência por candidatos que desejem seguir um caminho Fullstack.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Frameworks: React.JS ou Next (ou ainda frameworks com engine base em react, como Meteor)
- Web (HTML5/CSS3)
- Git

**Desejáveis:**
- Conhecimentos de Node.JS
- AWS Lambda
- DynamoDB

**Diferenciais:**
- Ter algum projeto concluído em React ou Node
- Utilização de serverless principalmente Lambda

## Contratação
PJ

## Como se candidatar
Por favor, envie um e-mail para trampos@onesight.com.br com seu CV anexado - enviar no assunto: Vaga ReactJS

## Tempo médio de feedbacks
Assim que o candidato concluí o teste necessitamos de em torno de 7 dias para dar a resposta.
Acabamos de inciar um fluxo de contratação mais rápido onde em torno de 10 dias temos o candidato contratado.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Junior
- Pleno
- Sênior

**Comment by minotti21** [comment]
Currículo enviado =)

**Comment by pamellafernandes** [comment]
Currículo enviado !

**Comment by pamellafernandes** [comment]
Currículo enviado !

**Comment by LukeRocha** [comment]
Currículo enviado!
 :D

**Comment by tahaluh** [comment]
Enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
