### ISSUE TITLE
[Blumenau] Front-End Developer na [Hi Platform]

### ISSUE THREAD

**Issue by LopesSara** [frontendbr/vagas#727]
## Descrição da vaga

A ideia é que essa pessoa seja responsável pelo desenvolvimento e gerenciamento dos nossos projetos de Interfaces. 

## Local

Escritório, Blumenau - Itoupava Seca

## Benefícios

- Vale Refeição no valor de R$17,50 reais ao dia;
- Plano de Saúde (Unimed);
- Vale transporte (com 6% de desconto no salário); 
- Política de Leitura e cursos;

#### Diferenciais

- Flexibilidade de horário;
- Home office 1 vez por semana;
- Day off no dia do aniversário;
- Escritório descontraído (risadas, cerveja, pipoca, etc);
- ...

## Requisitos
AngularJS;
React;
Experiência com manutenção de um produto;
Conheça o processo de Build de um produto;
Automatização de tarefas;
Git flow;
Experiência com metodologia ágil;
Bagagem para contribuir para o amadurecimento dos nossos produtos e da stack que temos hoje;

**Obrigatórios:**
Experiência na área;

**Desejáveis:**
- conhecimentos em ruby on rails
- conhecimentos em C#

**Diferenciais:**
- Ter trabalhado efetivamente com Redux;
- Experiencia com sistemas de alto volume de acessos;
- Vue ou outro novo framework para debatermos e melhorarmos expandirmos nosso conhecimento!
- Estar disposto a disseminar seu conhecimento com a equipe;
- Testes unitários;

## Contratação

CLT

## Nossa empresa

Cinco vezes vencedora do Prêmio Great Place To Work como uma das melhores empresas de TI para se trabalhar, queremos mudar o mundo. O "como" escolhido para isso é aproximando empresas e consumidores. Essa é a nossa missão e o ar que respiramos todos os dias por aqui. Somos jovens, inovadores e desenvolvemos produtos SaaS para o mercado de atendimento (SAC), tanto no pré como no pós-venda. Temos hoje produtos que usam as mais modernas tecnologias. Temos o orgulho de contar com uma carteira de clientes brilhantes e que, assim como nós, querem oferecer a melhor experiência no atendimento. Acima de tudo isso, está o nosso time. Gente cheia de coragem, autonomia e que adora o que faz.

## Como se candidatar

Por favor envie um sara.lopes@hiplatform.com - com seu CV anexado+ pretensão salarial - enviar no assunto: Vaga Front-end

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
