### ISSUE TITLE
[Joinville-SC - Híbrido/Presencial] Front-end Developer CLT/PJ JR React/HTML/CSS na CREDINET 

### ISSUE THREAD

**Issue by larissazz** [frontendbr/vagas#7271]
## Nossa empresa

Somos uma empresa de meios de pagamento que vem crescendo muito nos últimos anos. Queremos cada vez mais proporcionar aos nossos clientes um sistema completo que proporcione agilidade e praticidade na gestão de recebíveis.
Nossos valores são: Disciplina Estratégica; Valorização das pessoas; Compromisso com o Crescimento e Resultados; Prática da Inovação.

Com todo esse crescimento, precisamos de profissionais diferenciados para nos ajudar nesse crescimento.
Se você gostou dos nossos valores, vamos conversar!

## Descrição da vaga

Desenvolvedor(a) Front End Junior, com pelo menos um ano de experiência com React, Html e CSS, para integrar nossas equipe de desenvolvimento e manutenção de softwares relacionados a meios de pagamentos e gestão de recebíveis.

## Local

Joinville-SC - Híbrido/Presencial

## Requisitos

O que você precisa conhecer
-React
-HTML
-CSS

Pra ter aquela vantagem extra
-Formação em TI
-Redux/Context
-Hoocks
-AWS
-Ux/UI
-Graphql
-Metodologia Solid

## Benefícios

-Almoço (sem desconto em folha)
-Café da Tarde
-Vale transporte (sem desconto em folha)

## Contratação

CLT ou Pessoa Jurídica

## Como se candidatar

Saiba mais sobre essa grande oportunidade e se candidate no site (basta fazer login e inserir seus contatos): https://vagas.hunterco.com.br/job/62f29e568c6141001eaaa1cb?r=hmshlf&c=4740

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 5 dias úteis após cada processo. Depois da candidatura no site, entraremos em contato para alinhamento e marcar entrevista.

#### Alocação
- Híbrido
- Presencial

#### Regime
- CLT
- PJ

#### Nível
- Júnior

**Comment by EduApps-CDG** [comment]
Feito!

**Comment by larissabazzo** [comment]
> Feito!

Olá Edu, obrigado e boa sorte!

**Comment by GabrielVinhas** [comment]
Enviado!

**Comment by larissabazzo** [comment]
> Enviado!

Oi Gabriel, valeu, boa sorte!!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
