### ISSUE TITLE
[REMOTO] Front-end Developer na VEGA

### ISSUE THREAD

**Issue by luanasantosog** [frontendbr/vagas#7273]
## Nossa empresa

A VEGA, é especialista em soluções de inteligência em diagnóstico, prognóstico, monitoramento e inteligência comercial, reunindo grande capacidade em geração e gestão de dados estratégicos para o Agronegócio no Brasil.
Conheça mais sobre nossa empresa em: https://vegamonitoramento.com.br/

## Local

Remoto.

## Requisitos

**Requisitos:**
- Formação em curso superior de ciências da computação ou similar;
- Boa comunicação com o cliente;
- Capacidade de adaptação (aprender coisas novas);
- Espírito de colaboração com a equipe;
- Boa lógica de programação;
- Código limpo e boas práticas;
- Reutilização e aproveitamento de código;
- Experiência com Vue/Vuex/Nuxt, Node, JavaScript, HTML e CSS.

## Benefícios

- Nossas posições são 100% REMOTAS ou HÍBRIDAS caso sua região seja próxima a nossa Sede (São José dos Campos) ou nossos Hubs (Lavras e Piracicaba);
- Vale Alimentação ou Vale Refeição pelo cartão Alelo, você pode escolher a opção que mais combina com você;
- Plano de Saúde Sul América ou Unimed - sem custos para o colaborador e com a possibilidade de incluir dependentes;
- Seguro de Vida Individual - sem custos para o colaborador;
- Plano Odontológico Sul América com valores diferenciados do mercado;
- Day Off e Voucher Ifood no mês do seu aniversário;
- Flexibilidade de Horário de até 1 hora na sua jornada;
- 1 hora por semana para se dedicar aos seus estudos (cursos/especializações/idiomas);
- Licença Paternidade estendida de 15 dias;
- Programas e Trilhas para o seu Desenvolvimento;
- Um ambiente de trabalho saudável e humanizado, com espaço para inovação e autenticidade.

## Contratação

A combinar

## Como se candidatar

Envie seu currículo atualizado com a pretensão salarial para o e-mail: recrutamento@img.com.br

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by juliabergman** [comment]
currículo enviado :)

**Comment by erickflan100** [comment]
enviado..

**Comment by tahaluh** [comment]
enviado.

**Comment by eddijager** [comment]
Encaminhado

**Comment by alezzott** [comment]
enviado.

**Comment by brunoacev** [comment]
enviado!

**Comment by lucasnwvalladares** [comment]
Enviado

**Comment by Leonardoozx** [comment]
Enchaminhado :)

**Comment by gustavoAlunoFG** [comment]
enviado!

**Comment by pumba-dev** [comment]
Done!

**Comment by GabrielSAMatos** [comment]
Enviado.

**Comment by WelllWas** [comment]
Enviado.

**Comment by PedroRavaglia** [comment]
Enviado

**Comment by FeRiffo** [comment]
Enviado!

**Comment by josephmatheus** [comment]
Enviado!

**Comment by rafaelsiqeira** [comment]
Enviado!

**Comment by krons1996** [comment]
Enviado.

**Comment by flimamcz** [comment]
Enviado! :)

**Comment by hignicao** [comment]
Enviado!

**Comment by rafaelsilva81** [comment]
Currículo Enviado!

**Comment by wendersonjps** [comment]
Currículo enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
