### ISSUE TITLE
[Remoto] Pessoa Desenvolvedora Frontend Pl na Resilia

### ISSUE THREAD

**Issue by Luiza2203** [frontendbr/vagas#7275]
## Nossa empresa

A Resilia é uma *edtech* que prepara e emprega jovens para as profissões mais quentes do mercado. Questionamos o status quo e constantemente buscamos formas mais rápidas, acessíveis e eficientes de capacitar as pessoas para as profissões mais demandadas pelas empresas. Somos apaixonados por fazer as pessoas aprenderem e por gerar uma real diferença na vida dos nossos alunos e Resilientes. 
Nossa visão é capacitar a América Latina para o século 21. Para chegar lá, precisamos resolver desafios e problemas com tecnologia e gente boa.

## Descrição da vaga

Como pessoa desenvolvedora, você terá o desafio de desenvolver soluções e novas funcionalidades para os nossos produtos que engajem e ajudem no sucesso dos nossos alunos.

**Essa vai ser um pouco da sua rotina:**
- Participar das cerimônias junto com o time de tecnologia;
- Executar as atividades das sprints de maneira colaborativa;
- Ajudar na priorização de dividas técnicas;
- Participar ativamente na construção de uma cultura de engenharia de software;
- Propor melhorias de processos e inovações utilizando tecnologia

## Local
Remoto

## Requisitos

**Obrigatórios:**
- Ser apaixonada por programar
- Ter experiência com diversas tecnologias - estamos abertos a sugestões :-)
- Responsabilidade, organização e proatividade
- Ter empatia, criatividade e flexibilidade para resolver problemas
- Entendimento de boas práticas de Engenharia de Software
- Conhecimento de sistemas web e protocolo HTTP/APIs
- Conhecimento em Banco de Dados PostgreSQL e/ou MySQL
- Experiência com JavaScript/TypeScript e React.js

**Desejáveis:**
- Experiência com testes automatizados
- Conhecimentos em docker

## Contratação
PJ a combinar

## Como se candidatar

Interessados preencher o formulário: https://forms.gle/JBqutWTBGhE98RwV7

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by lirbre** [comment]
Olá, apenas pra responder que aparentemente o Link do formulário não funciona!

**Comment by Luiza2203** [comment]
Obrigada por avisar! Corrigido. 

Abs

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
