### ISSUE TITLE
[REMOTO/AUSTRALIA] Front-end Developer na Convincely 🇦🇺

### ISSUE THREAD

**Issue by vncscoelho** [frontendbr/vagas#7277]
## Descrição da vaga:

- Likes working with modern Frameworks e.g. AngularJS, React, Vue.js, Svelte
- Expert in JavaScript, especially all the new features in ES6/7/8
- Strong in HTML and CSS/SASS/SCSS, think flexbox and CSS Grid Layout. (Note: we hate using floats!)
- Knows all the smart tools out there that help with keeping the codebase clean, like autoprefixer, babel/buble, eslint, webpack and rollup just to name a few
- An advocate of Test Driven Development (TDD) or BDD
- Familiar with Continuous Integration and Continuous Deployment
- Knows their way around modern version control systems such as git
- Complex programming, program debugging, data analysis, problem analysis and resolution of issues within open source applications.
- Strong communication and collaborative skills in providing technical direction and hands-on software development to include design, development and testing.

## Nossa empresa

https://careers.convincely.com/

## Benefícios

- Boa remuneração (> $3500) em dólares

## Contratação

- PJ a combinar

## Como se candidatar

Email com Linkedin e currículo em inglês para vinicius at convincely.com

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Senior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
