### ISSUE TITLE
[100% remoto] Front-end Developer Angular (CLT) na DQR Tech

### ISSUE THREAD

**Issue by kerol-barros** [frontendbr/vagas#7279]
## Nossa empresa

Nascemos de uma parceria de mais de 10 anos entre seus sócios, somando a paixão por tecnologia à vontade de construir uma empresa diferente, investindo na proximidade com nossos parceiros e clientes. Somos uma consultoria especializada em Arquitetura de TI, Outsourcing de Profissionais e Hunting.

## Descrição da vaga

O principal desafio da vaga é trabalhar com Real Time Bidding (RTB) e pequenas melhorias em um sistema da área financeira/bancária.

## Local

Remoto ou Híbrido na Av. Faria Lima - SP. (Opcional)

## Requisitos

**Obrigatórios:**
- Angular 9+
- Git, Gitflow
- Bootstrap
- HTML/CSS/SASS/SCSS/CSS3
- PostgreSQL; AWS
- Testes Unitários

**Diferenciais:**
- Flutter.

## Contratação

CLT

**Benefícios:**
- Assistência médica e Odontológica sem coparticipação para colaboradores;
- Vale Refeição/Alimentação;
- Assistência Médica e Odontológica sem coparticipação;
- Seguro de Vida;
- Acreditamos no desenvolvimento contínuo de nossos colaboradores,
dessa forma oferecemos acesso full aos cursos da plataforma ALURA;
- Auxílio-creche;
- Aqui a sua indicação vale premiação;
- No seu aniversário você recebe mimos;
- Material para você desempenhar as suas atividades;
- Horário-flexível (conforme o cliente);
- Contrato CLT (40 hrs semanais).

## Como se candidatar

Se interessou e tem as stacks necessárias? Ou tem alguém para indicar?
Por favor, entre em contato no e-mail: kerolayne.barros@dqrtech.com.br - enviar CV anexo e no assunto colocar: Vaga Angular

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 03 dias após cada processo.

#### Alocação
- 100% Remoto

#### Regime
- CLT

#### Nível
- Pleno/Sênior

**Comment by carolinetech** [comment]
Vem para #DQRTECH!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by DaianeMFirmiano** [comment]
Vaga urgente!!  Ótima oportunidade!!
