### ISSUE TITLE
[Vitória - ES] Estágio - Front End na Code n'App

### ISSUE THREAD

**Issue by PamelaSO** [frontendbr/vagas#7282]
Nossa empresa
Somos uma empresa que é a-pai-xo-na-da por tecnologia, que através do desenvolvimento de software e processos, buscamos soluções inovadoras e totalmente customizadas para cada um dos nossos clientes a fim de alcançar o melhor resultado, independente da tecnologia utilizada.

Além disso, estamos em um ritmo de crescimento a-ce-le-ra-do, então se você curte desafios, busca evoluir e ama tecnologia, temos aqui um time para chamar de seu! Pois o que mais adoramos é reconhecer e potencializar o desenvolvimento dos nossos Codenappers.

#VemPraCode ♥

Descrição da vaga
Com o nosso programa de estágio, iremos potencializar e desenvolver suas habilidades para colaborar na construção de sua jornada profissional.

A pessoa estagiária de desenvolvimento será responsável por apoiar na criação e evolução de interfaces web utilizando HTML/CSS/Javascript e frameworks como Vue JS e React JS.

Local
Vitória - ES

Requisitos
Graduando a partir do 5º período nos cursos de Sistemas de Informação, Ciência da Computação e área correlatas;
Visão analítica;
Gostar de aprender e buscar por novos conhecimentos;
Proatividade;
Ser apaixonado por programação em alguma das tecnologias: React JS ou Vue JS

Benefícios
Nosso ambiente foi preparado para que você que gosta de compartilhar experiências, ama resultados e adora se divertir com os desafios do dia a dia. E mais, pensamos em como melhorar tudo isso com um pacote de benefícios:

No dress-code;
Gympass;
Somos flexíveis: Disponibilizamos um cartão de crédito bandeira Visa para livre utilização do saldo nas categorias de alimentação, restaurante, mobilidade, cultura, saúde e home office;
Vale transporte;
Celebração de datas importantes (Seu aniversário, aniversário Code n’ App, etc.)

Diferenciais:

Programa Indica Code - Indicando um amigo você ganhará um bônus pelo talento em nosso time;

Cafézinho e biscoitinhos à vontade, além de puffs para cochilar nos intervalos;
Assessoria e educação financeira;
Oportunidade de fazer parte de um time de feras e com muitas experiências para compartilhar.

Como se candidatar
Para se candidatar é só seguir o seguinte link https://codenapp.gupy.io/jobs/2782470

**Comment by WendelSantosNunes** [comment]
É possível fazer esse estágio remotamente?
