### ISSUE TITLE
[100% 🌎 Remoto] Lead Frontend Dev Open Source React web app, CI/CD

### ISSUE THREAD

**Issue by jfoliveira** [frontendbr/vagas#7283]
> Vaga Remota - PERMANENTEMENTE REMOTA, Seja fera de onde cê quiser ser fera

## TL; DR

- Vaga ideal para quem quer ter participação ativa em repositório e comunidade open source
- Todos seus commits serão públicos, aumentando em muito a visibilidade do seu perfil do GitHub e contribuições em projetos open source
- Se você é apaixonado por frontend, CI/CD, Release Management, DevOps, SRE (Site Reliability Engineering), cloud computing e automação: essa vaga é pra você :-) 

## Local

100% remoto

## Benefícios
- Equipe pequena, altamente técnica, bem humorada, e principalmente obstinada e orientada a resultados. Sem perda de tempo em discussões inúteis. A gente ama o que faz e foca na entrega de resultados
- Participar de todo o ciclo de vida de um produto SaaS, influenciando seu futuro

## Contratação

PJ, valor a combinar

## Como se candidatar

Por favor candidate-se via LinkedIn: https://www.linkedin.com/jobs/view/3215273362/

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias úteis após iniciado o processo seletivo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
