### ISSUE TITLE
[100% Remote] Senior Engineer, Web Platform at Pulselive.tv

### ISSUE THREAD

**Issue by petrpavlik** [frontendbr/vagas#7284]
PJ contract: salary $60k - $84k / year

**What we're looking for**

Make the most of your one wild and precious life. Passionate about sports? Share the stoke of life with others who share your passion for getting outdoors, live a healthy life, and come help us change the way we share and experience our sports. 🏃‍♂️⛷🧗🏻‍♂️ 

Pulse's goal is to enable any athlete to capture, relive and share their passion with the world, just like they experienced it. Think Twitch, for Sport. 

You will be responsible for building the best possible web interface, as well as take ownership of our desktop streaming too, to deliver on this vision of making outdoor sports experiences accessible to everyone. Think Twitch for sports.

Want to find out more? Check out our app on the App Store and start coming up with ideas for the next version. 

Right now we're are looking for a senior front-end engineer with **React, Javascript/Typescript, and Electro**n experience to join our team.

You will take ownership of our web interface, as well as our desktop streaming tool. Working closely with the rest of the product team to create a kick ass user experience that take advantage of the unique benefits of the web and desktop environments.

You'll be leading development on two of our web based applications:

* Pulse Studio: An electron desktop app that allows creators to review, edit and upload GoPro videos to stream on Pulse.
* Pulse for Web: Our website that allows users to view and interact with video streams on Pulse, without needing to install the app or sign up.

**What do we expect from you in your role at Pulse?**
* Be part of design and product reviews to help identify the right scope, risks, and implementation details for new features.
* Work closely with our design and backend team to deliver impactful features.
* Routinely own and manage desktop releases, and deployment of our web app.
* As this is a senior position, we would expect you to be comfortable to take on full ownership of your platform. This comes with the autonomy to choose the tools and workflow that suit you best, however it also means that you will need to make some important decisions that will also affect new members that join your team.
* Communicating early and often about uncertainties or concerns.
* You're not alone! We'll always work as a team to guide each other and work out the best ways forward.

**Requirements**
* Advanced English
* ≥ 5 years experience in the industry.
* Proficiency writing frontend applications using JavaScript/TypeScript, React and HTML, and you enjoy working with the frontend web stack.
* Experience with automated testing to enable shipping with confidence. Experience managing a CI/CD pipeline.
* Familiarity with the concept of clean architecture and writing testable and reusable code.
* Comfortable with packaging and distributing apps on Electron and the web
* Familiar with integrating with REST API services (OpenAPI and JWT).

**Nice to have**
* Experience with mapbox
* Experience working with BLE/Bluetooth devices, especially GoPros
* Experience with video transcoding and editing, especially using ffmpeg for video processing (Ideally you've worked on video editing/processing services before)

**How to Apply**
https://pulselive-inc.breezy.hr/p/93588e91468c-senior-engineer-web-platform

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
