### ISSUE TITLE
[REMOTO] Estagiárie Front end @DWS BRAZIL

### ISSUE THREAD

**Issue by dwsbrazil** [frontendbr/vagas#7286]
## Nossa empresa
A Dentsu World Services (DWS) Brazil faz parte do Grupo Dentsu, presente em 143 países e com mais de 66.000 pessoas comprometidas com soluções em comunicação, inovação e tecnologia. Em Porto Alegre atuamos como centro de desenvolvimento, inovação e design, colaborando com agências de Marketing Digital do grupo. 
Aqui temos como foco a potencialização de talentos através da criação de um ambiente que visa o equilíbrio entre o desenvolvimento de pessoas e a construção de soluções criativas e inovadoras. Em nosso dia a dia, compartilhamos propósitos e valores através de iniciativas que visam o bem-estar, a confiança e a colaboração, sempre comprometidos com a qualidade do trabalho e o respeito.

## Descrição da vaga

**Hello, Galaxy!**

Nosso programa de estágio tem como objetivo compartilhar conceitos sobre tecnologia e rotina organizacional, além de você ter a oportunidade de vivenciar uma cultura diferente através do contato com colegas de outros países. Então, não se preocupe com requisitos técnicos que estamos preparando tudo com muito carinho pra você.
Nesta edição, contamos com vagas de Estágio para Desenvolvimento Front End e Mobile. No programa de estágio, você inicialmente poderá se experimentar dentro de um modelo Bootcamp, com pessoas mentoras te auxiliando nas rampas de conceitos mais gerais sobre tecnologia, sempre aliados a aplicabilidade prática em projetos que podem ser fictícios ou reais, aprofundando conceitos de acordo com o desenvolvimento e entregas individuais. É importante que você saiba que esse olhar será individualizado e muito focado no desenvolvimento e entregas de cada uma.
A atuação é remota, e o Inglês para conversação é fundamental, pois você será preparado para atuar com time composto por pessoas de nacionalidades diferentes, realizando as cerimônias no idioma.

O Programa de Estágio tem duração 6 meses (setembro à março), podendo ser renovado;

**Como será sua rotina?**

Atuação focada na inserção à Programação;
Participação ativamente de cerimônias ágeis;
Auxílio na comunicação interna com times ágeis;
Estudos direcionados, autoguiados com mentorias constantes para mergulhar no mundo da programação;
Participação em simulados e bootcamps;
Atuação na aplicabilidade prática em projetos reais e/ou fictícios dos conceitos estudados

## Local
Remoto - mas temos um escritório bonitão em Porto Alegre - RS pra quem quiser ir :) E, por vezes rolam umas excursões pra conhecer o office e integrar a galera <3 ps.: não iremos retomar pro presencial, o office é só estrutura de apoio e para quem quiser!

## Requisitos
**Obrigatórios:**
Disponibilidade para atuação remota;
6h diárias em turno a combinar;
Conseguir se comunicar em inglês;
Estar com matrícula aberta em ensino superior a partir do segundo semestre em áreas co-relacionadas;
Noções básicas e/ou vontade de aprender sobre Métodos Ágeis;
Gostar de compartilhar e trabalhar em equipe;
Vontade de se desenvolver e aprender muito sobre o mundo da programação!

**Desejáveis:**
conhecimento teórico e/ou práticas de Programação, 
HTML, 
CSS, 
Javascript

**Diferenciais:**
Somos uma empresa que preza pela saúde mental, work-life balance, tem programa de mentoria, canal de memes com premiação mensal, cultura de feedback e horizontalidade, budget para desenvolvimento por área. Será legal se você se identificar, participar e propagar a nossa cultura!

## Benefícios
Plano de Saúde (Unimed/ Bradesco) Plano odontológico (Uniodonto);
Vale Refeição + Auxílio Home Office + Auxílio mobilidade no cartão flash 
Equipamento (Macbook/Avel e periféricos como mouse, teclado e adaptadores); 
Convênio com Professor de Inglês para aulas particulares ou em grupo; 
Anywhere office - flexibilidade para trabalhar de onde precisar ou híbrido se preferir;
Gympass;
Mental Health Program;
Horário flexível (30h semanais).

**Diferenciais:**
Bolsa auxílio: R$ 1.500,00 + benefícios;
Há possibilidade de efetivação
Trabalhamos com macbook ou Avell
Temos um frigobar sempre cheio para quem quiser ir pro office:P
Possuimos uma sala de jogos + Óculos VR

## Contratação

Estágio com intermediação de agente integrador

## Como se candidatar

Para se inscrever basta clicar aqui https://jobs.kenoby.com/dwsbrazil/job/estagio-desenvolvimento-web-front-end-mobile/62f50cb6ed95aebecfc74b45?utm_source=website

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada etapa do processo.
E-mail para contato em caso de não haver resposta: aline.schorn-ext@dentsu.com

#### Alocação
- Remoto

#### Regime
- Estágio

#### Nível
- Estagiário

**Comment by edgarsanue** [comment]
Estou em um curso de humanas na faculdade, mas estudo wed development por fora. Posso me candidatar?

**Comment by DanielaFehlow** [comment]
Sou formada em Ciências Contábeis e estou tentando migrar de área, estou com cursos completos de HTML, CSS e JS, no momento estudando React, você sabe me dizer se ainda é aplicável? Muito obrigada!

**Comment by HudsonMenezes** [comment]
Inscrição enviada! Estou graduando em Engenharia de Software, cursando também especialização em Desenvolvimento Web e possuo inglês fluente!

**Comment by Luan-Moreno** [comment]
Inscrição enviada! Estou atualmente cursando Ciência da Computação, já tive na faculdade a matéria de Desenvolvimento Web, onde vimos HTML, CSS(Base + Flexbox) e Javascript. Além disso já fiz e estou fazendo cursos sobre frameworks.

**Comment by igo-mgoncalvs** [comment]
Currículo enviado, estudo a anos desenvolvimento Front e estou em busca de uma oportunidade pra entrar na área.

**Comment by arthursj** [comment]
Currículo enviado, sou formado em Tecnologia da Informação e estou em busca da minha primeira oportunidade na área.

**Comment by allbertuu** [comment]
Vaga pelo visto fechada. @felipefialho

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
