### ISSUE TITLE
[Campinas/SP] Front-End Developer na StarCorp

### ISSUE THREAD

**Issue by tmsouza** [frontendbr/vagas#729]
## Descrição da vaga

Desenvolvimento de novas funcionalidades para a plataforma de e-commerce.

## Local

Escritório, Campinas/SP - Centro

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento JQuery, Angular 
- Integração de sistemas internos e de parceiros através de webservices REST/SOAP.
- Conhecimento em GIT ou SVN.

**Desejáveis:**
- CSS ( SASS, LESS)
- Testes unitários
- UX/Design.
- Inglês ou Espanhol.

## Contratação

PJ a combinar

## Nossa empresa

Somos especializados no desenvolvimento de sites, portais, intranets, extranets e APPs.

## Como se candidatar

Por favor envie um email para tiago.mendes@starcorp.com.br com seu CV anexado.

**Comment by felipetrova** [comment]
Enviado 😄  💻

**Comment by tmsouza** [comment]
Pessoal, ainda temos 1 vaga em aberto.
