### ISSUE TITLE
[Remoto] Senior Google Cloud Platform DevOps na [Builders]

### ISSUE THREAD

**Issue by RaissaBaltazar** [frontendbr/vagas#7291]
Hey, se você é DevOps apaixonado por desafios, inovação, e deseja trabalhar de forma colaborativa e dinâmica, essa é a sua chance de dar o PLAY em um ecossistema incrível para crescer e aprender.🤘

Mas atenção: pra essa posição é imprescindível ter uma certificação GCP 📝

**Como Builder, esse será o seu Desafio 😎:**
- Migrar infraestrutura de diferentes players para o Google Cloud Computing (GCP);
- Mostrar o melhor caminho para nossos clientes sem conflito de interesses buscando as melhores decisões com foco no longo prazo;
- Ajudar nas tomadas de decisões técnicas pautadas em dados (data driven);
- Aplicar práticas de engenharia DevOps que vão gerar velocidade, qualidade, segurança no nas entregas de software;

**Conhecimentos que vão gerar valor nos projetos 💻:**
- Experiência com Continuous Delivery & Continuous Integration;
- Experiência infrastructure as code (e.g Terraform, Cloud Formation);
- Experiência em Google Cloud Computing;
- Experiência com Google Kubernetes Engine (GKE);
- Experiência com ferramenta de monitoramentos e observability (e.g Prometheus, NewRelic, Dynatrace, ELK);
- Experiência com Linux;
- Experiência com Cloud SQL;
- Experiência com Scripts Language (e.g Python, Bash);
- Experiência com Git;
- Boa habilidade de análise e troubleshoot;
- Conhecimento prático de Agile e/ou outras metodologias de desenvolvimento de Software.

**O que é imprescindível 💪:**
- Disponibilidade para On-call (sobreaviso) em horários alternativos;
- Ter certificação Google Cloud Computing.

**Como Builder, você terá possibilidade de 👀:**
- Oportunidades reais de empreender e impactar;
- Fazer parte de uma comunidade de empreendedores; de ponta, o Movimento;
- Inovare criar;
- Participar de um processo único de geração de valor;
- Contribuir na criação de métodos disruptivos;
- Colocar suas ideias no mercado :)
- Profit share em novos negócios.

Inscrição através do [Link ](https://jobs.kenoby.com/sejabuilder/job/senior-google-cloud-platform-devops-cod-798-remoto/62c48ac9b31091248d1b0ec0?utm_source=website)! Só bora fazer parte desse movimento 💛

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
