### ISSUE TITLE
[REMOTE] Senior Front-end Developer @ Convincely 

### ISSUE THREAD

**Issue by lucasmota** [frontendbr/vagas#7295]
## Nossa empresa

https://www.convincely.com/

## Descrição da vaga

If you managed to find your way here, you've come to the right place. Convincely is not just another tech startup trying to make it big, we actually get the tech in technology.

After years of research and development, we have come up with very creative and effective ways to capture a user's attention and guide them on to an epic gamified journey. With this breakthrough, we have made a name for ourselves in the industry. This wouldn't be possible if we didn't love what we do as problem solver and the passion to learn and succeed.

We don't believe there can ever be a perfect candidate, but to be successful in this application it's all about having the right mindset. Do you always have an unquenchable thirst for knowledge? We are always experimenting with the latest and greatest of technologies and will require someone to take the initiative to tell us something we don't already know.

We are looking for a strong Senior Frontend Developer, one who prides themselves in writing clean, elegant, robust and efficient code. Someone who likes learning new things, or discovering better ways of doing things which we highly encourage. Our current stack is Svelte and Node.js going completely serverless all hosted on AWS using S3, CloudFront and Lambda. We are also looking for someone who is very keen on learning Svelte. We are also listed on https://svelte.dev/ homepage.

*Just a note that some of our legacy projects are still on React/Preact, yes we consider those to be legacy!

- This is a critical role in the quest for world domination in the tech space, you will be highly rewarded for your efforts in terms of salary and job satisfaction.
- Leading development, integration and maintenance of architectures, requirements, algorithms, interfaces and designs for real-time software systems
- Review test plans, unit tests, functional tests with over 90% code coverage to ensure high-quality delivery
- Implement engineering excellence by enforcing regular code reviews, continuous integration, high test code coverage, ongoing code refactoring and adequate documentation
- Evaluate, troubleshoot and lead root-cause analysis for production issues and system failures; determine corrective action and improvements to prevent a recurrence
- Serve as a subject matter expert for software domains, system-specific issues, processes, and methodologies
- Working with designers and design tools (Figma, Zeplin etc.)
- Actively participate in Sprint planning and execution

## Local

Remote

## Requisitos

- Likes working with modern Frameworks e.g. React, Svelte, Angular, AngularJS, Vue.js
- Expert in JavaScript, especially all the new features in ES6/7/8
- Strong in HTML and CSS/SASS/SCSS, think flexbox and CSS Grid Layout. (Note: we hate using floats!)
- Knows all the smart tools out there that help with keeping the codebase clean, like autoprefixer, babel/buble, eslint, webpack and rollup just to name a few
- An advocate of Test Driven Development (TDD) or BDD
- Familiar with Continuous Integration and Continuous Deployment
- Knows their way around modern version control systems such as git
- Complex programming, program debugging, data analysis, problem analysis and resolution of issues within open source applications.
- Strong communication (English is essential) and collaborative skills in providing technical direction and hands-on software development to include design, development and testing.

**Diferenciais:**

- You can choose which hours of the day you want to work (morning, afternoon, evening, etc.). You can even split some hours during the morning, some hours at night, etc.
- We have bonus twice a year based on KPIs
- Completely remote
- Work closely with the team in Melbourne
- Training and development is our number 1 priority
- We believe in work, rest and play
- We like to travel from time to time

## Contratação

PJ / Contractor with Australia

## Como se candidatar

Send your CV in English to lucas@convincely.com if your salary expectation in Reais.

#### Regime
- PJ / Full-time, exclusivity contract

#### Nível
- Senior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
