### ISSUE TITLE
[Rio de Janeiro - REMOTO] Front-end Developer na GoLab.Rio [Pleno ou superior]

### ISSUE THREAD

**Issue by mundiware** [frontendbr/vagas#7297]
## Nossa empresa

Somos a GoLab.Rio, uma empresa de tecnologia e design para projetos especiais. Criamos soluções inovadoras para o mercado de portais de notícias e mídia em geral. Atuamos com equipes multidisciplinares, trabalhando remotamente de todo Brasil. 

## Descrição da vaga

Criar aplicações web otimizadas com liguagem nativa da plataforma da empresa, foco em portais de notícías;
Empregar boas práticas de programação, priorizando códigos limpos e organizados;
Atuar em conjunto com desenvolvedores back-end e designers para garantir a melhor experiência de uso das aplicações;
Revisar código de outros membros da equipe, de modo a garantir um padrão de qualidade;
Escrever documentações e guias claros, precisos e funcionais;
Se atualizar sobre as tendências de desenvolvimento front-end para refinamento técnico.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 3 anos de experiência Experiência com desenvolvimento front-end 
- Conhecimentos avançados em HTML5 (semântica), CSS3, JS Nativo sem framework
-Noção de UX (User Experience).

**Desejáveis:**
- conhecimentos em ruby on rails
- conhecimentos em C#

**Diferenciais:**
-Experiência com Docker;
-Documentação;
-Conhecimento em Git e GitHub;

## Contratação

CLT / PJ a combinar

## Como se candidatar

Por favor envie um email para rh@golab.rio com seu CV , GIT ou portfolio

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT
- Freela
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by israelcena** [comment]
show !

**Comment by kleitonalbuquerque** [comment]
Enviado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
