### ISSUE TITLE
[São Paulo] Pessoa Desenvolvedora  Pl na LINX (CLT) (REMOTO) 

### ISSUE THREAD

**Issue by leticiamarcolin** [frontendbr/vagas#7298]
> Vaga Remota durante a pandemia

## Nossa empresa
A Linx é uma das melhores empresas de Tecnologia para se trabalhar no Brasil segundo a GPTW e os mais de 4 mil colaboradores que no decorrer desses 37 anos de história são nossos protagonistas na revolução do varejo. Movemos o varejo ao lado do grupo Stone, juntos por um sonho ainda maior!

Lideramos pelo exemplo, inspiramos e desenvolvemos o potencial das nossas pessoas para fazerem sempre mais e melhor. Os nossos times têm flexibilidade e autonomia para assumir grandes projetos porque sabemos que só assim, graças a um time responsável e eficiente que pessoas e tecnologia se aproximam. Fazemos Juntos. E, no processo, aprendemos e crescemos junto com o mercado também. E quem prova isso não somos nós, são os mais de +70 mil clientes que utilizam das nossas soluções para tornar as suas vendas mais apaixonantes e inovadoras. Se você assim como a gente tem o desejo genuíno de melhorar a vida das pessoas e contribuir com a sociedade e o meio ambiente, então a Linx é a sua próxima parada!
Com a gente você terá a chance de construir uma carreira com propósito, sabendo que cada escolha sua reflete na vida de milhares de pessoas no varejo brasileiro. Para começar a impactar positivamente a sociedade, confere os nossos desafios como Pessoa Desenvolvedora Sênior no time de P&D dedicado ao nosso projeto de Conversational Commerce:

#Local
Remoto

#Descrição da vaga
Quais desafios a nossa área tem para você?
Você vai desenvolver um sistema novo para envio e recebimento de mensagens via Whatsapp, Instagram, etc, em que existem robôs (os bots) que interagem com os clientes. Além disso, existirá uma plataforma de atendimento humano centralizada.
Além de interfaces web, você terá a oportunidade de interagir com sistemas complexos, serviços em nuvem, testes automatizados e muito código em typescript.
Estamos desenvolvendo uma solução digital inovadora e eficaz, que irá auxiliar milhares de consumidores em suas jornadas digitais, sempre aplicando o nosso propósito de tornar a tecnologia um agente de mudança para um mundo melhor, #CuidamosHojeDoNossoFuturo!

Como será o seu dia a dia #soulinx:
Atuação full-stack participando ativamente do desenvolvimento do projeto;
Participar e colaborar nas reuniões diárias e no planejamento a cada 15 dias;
Programar e manter o código no Github;
Fazer parte de um ambiente colaborativo: nossa comunicação é assíncrona através do Slack, sempre que precisar é só chamar alguém da equipe para apoio.

#Requisitos
Alguns sinais de que você é a pessoa certa para mover o varejo com a gente:
Experiência com desenvolvimento web com React e Node.js;
Conhecimento de typescript: tipos, domínio em promises, async/await, map/reduce, import/export, destructuring e outras ES6 features;
Conhecimento de Git;
Interesse em fazer programação pareada (programar junto);
Código limpo e simples, sem mágica, o mais importante é que os outros entendam o código do que seja otimizado;
Perfil participativo: busca ajuda e propõe melhoria sempre que achar necessário, tem facilidade com trabalho em equipe e também sozinho quando necessário; 
Perfil curioso: sabe que estudar não tem fim, por isso continua aprendendo e adquirindo novos conhecimentos;

#Diferenciais:
Além disso, o que nos faria brilhar os olhos, mas tudo bem se não tiver:
Já ter utilizado alguma linguagem orientada a objetos tipada, como typescript, C#, Java, entre outros (isso vai te ajudar bastante a adaptação com typescript);
Conhecimento de CSS (sites responsivos) + Styled;
Conhecimento de Dialogflow CX (utilizamos como base das conversas dos bots);
Conhecimento de Next.js e TDD (test driven development);
Conhecimentos de Design/UX e Hasura (graphql);
Conhecimentos DevOps, como Kubernetes ou Docker.
 
## Benefícios
🥗 Vale Alimentação
🥗 Vale Refeição
🥳 Day Off de aniversário
📚 Bolsa de estudos e cursos livres
💰 Participação de lucros e resultados
👶 Bebê #soulinx a Bordo (programa com vários benefícios para nossos papais e mamães)
🎁 Presente de casamento
🩺 Assistência médica
🦷 Assistência odontológica
💼 Seguro de vida
🧑‍⚕ PAC (Programa de apoio ao colaborador)
⭐Parceria com a Allya: super descontos em estabelecimentos ao redor do Brasil
🏥Parceria com a VITTA: o primeiro Hospital Digital do Brasil
💪 Parceria com redes de academia pela TotalPass.

## Como se candidatar
Por favor envie um e-mail para leticia.marcolin@linx.com.br com seu CV anexado - enviar no assunto: Vaga Pessoa Desenvolvedora Pl 

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 15 dias após cada processo.

#### Regime
- CLT

#### Nível
- Pleno

**Comment by Carolinepandolfe** [comment]
Enviado.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
