### ISSUE TITLE
[São Paulo] Desenvolvedor Front-End Pleno/Senior

### ISSUE THREAD

**Issue by herberthenrique** [frontendbr/vagas#73]
## Descrição da vaga

Desenvolvedor Front-End Pleno ou Senior

## Local

Escritório, São Paulo - Novo Brooklin
## Requisitos

**Obrigatórios:**
- Bom conhecimento de HTML, CSS e Javascript
- Conhecimento de padrões front-end 

**Desejáveis:**
- Conhecimentos projetos com vuejs, angular, ember, react e outras frameworks.
- SASS
- Stylus
- BEM
- SMACSS ou Atomic Design

**Diferenciais:**
- Projetos opensource
- Conhecimentos em C#, ASP.NET 
- Já ter utilizando a biblioteca do Kendo

## Contratação

PJ a combinar

## Nossa empresa

Somos uma plataforma de workforce planning, onde nosso diferencial é utilizar tecnologia de ponta e machine learning para atribuir um projeto para as pessoas certas, gerenciar performance, prever futuros talentos e suas necessidades

## Como se candidatar

Por favor envie um email para herbert.henrique@crunchflow.com com seu CV anexado e links para linkedin e gthub - enviar no assunto: Vaga Front End - frontendbr

**Comment by LFeh** [comment]
Rolou? :)

**Comment by herberthenrique** [comment]
Enviei alguns dos currículos que selecionei pro RH.
Eles também estava procurando em outros lugares, agora fecharam e vão fazer algumas entrevistas (se contratarmos alguém daqui eu aviso :D)

**Comment by LFeh** [comment]
\o/

**Comment by camilatigre** [comment]
@herberthenrique 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by herberthenrique** [comment]
Não :(
