### ISSUE TITLE
[São Paulo] Front-End Developer na Valleweb

### ISSUE THREAD

**Issue by afonsopacifer** [frontendbr/vagas#730]
## Descrição da vaga

Mais do que desenvolvedores tecnicamente perfeitos, estamos em busca de pessoas que verdadeiramente se divertem e são felizes aprendendo e compartilhando conhecimento ❤️ .

**Sua missão, caso deseje aceitá-la é:**

Trabalhar no time que irá criar do zero nossos novos produtos (em geral ERP).
Estar disposto a aprender muito.

Ser responsável por ajudar a implementar novas tecnologias baseadas na plataforma Web, como Web Components, CSS Grid Layout, ES[7/8/9], etc...) .

Entregar features/components sempre com qualidade máxima, por isso trabalhamos com tudo muito bem documentado, testado, acessível, escalável e manutenível. Basicamente você terá sempre a responsabilidade de criar um projeto que será fácil e seguro de qualquer pessoa no mundo trabalhar.

Trabalhar tanto em nosso produto interno (a nível de aplicação), quanto em diversos projetos Open Source que compõem nossos produtos.

Criar Web Componentes (com Polymer) reutilizáveis de verdade, independente de projeto, processos de build ou stack.

## Requisitos

**Obs:** Temos vagas para Junior, Pleno e Sênior. (ai depende de quantos requisitos você atende e seu background)

**Técnicos**

- Sólidos conhecimentos em HTML/CSS/Javascript.
- Controle de versão com GIT.
- Entender processos de build e conhecer alguma ferramenta (Grunt, Gulp, Webpback, etc...).
- Consumo de APIs Rest.

**Soft Skills**

- Vontade de aprender novas tecnologias e estar sempre animado com novidades.
- Trabalho em equipe, compartilhar conhecimento e não ter vergonha de admitir que não sabe algo.
- Gostar de Open Source <3.
- Ser ativo na comunidade, seja como participante, organizador ou palestrante.

## Desejável

**Técnico**

- Boas práticas em geral (Semântica, Arquiteturas CSS, Javascript Design Patterns, etc…). 
- Sólidos conhecimentos em Acessibilidade Web  (a11y).
- Testes unitários em componentes Client Side.
- Experiência com internacionalização (118n).
- Saber os problemas que os Frameworks/Libs de componentes resolvem (React, Angular, Vue, etc..).
- Estratégias de performance.
- Estratégias offline.

**Soft Skills**

- Interesse em entrar para core teams de projetos open source grandes. (ou já fazer isso)
- Interesse em palestrar/organizar em eventos de tecnologia. (ou já fazer isso)

## Diferencial

- Conhecimentos em node.js / MongoDB.

## Local

Pinheiros, São Paulo - SP | Em frente ao Shopping El Dorado

Obs: A princípio apenas alocado.

## Contratação

CLT ou PJ com salário a combinar

## Benefícios

**Básico:**

- VR.
- VT.

**Sala dedicada apenas ao time, com:**

- TV grande com apple TV.
- Maquina de café instantâneo com refil a vontade.
- Puffs para programar relaxado.
- Bebedouro com água mineral dedicado.
- Frigobar dedicado.
- Microondas dedicado.
- E todo o resto que um escritório dev precisa ter.

**Apoiamos que você se desenvolva com:**

- Auxílio financeiro para participar de eventos.
- Compra de livros.
- Patrocínio para fazer cursos.
- Tech Talks internas.
- Seções de pair programing.
- Aulas particulares de inglês.
- Plano de carreira.

## Um pouco sobre nossa cultura

**Apoio a comunidade**

Temos interesse em participar da comunidade de desenvolvedores sediando meetups, 
patrocinando conferências ou ajudando no que for possível.

**Roupas no local de trabalho**

Apenas use.

**Horários**

O horário padrão da empresa é das 8h às 17h de segunda a sexta (40h semanais), mas você tem flexibilidade para a hora de chegada e saída, assim como possibilidade de sair mais cedo ou chegar mais tarde e compensar em outro dia.

Após as 18h você é convidado a se retirar e viver sua vida pessoal, se quiser pode ficar e trabalhar em projetos Open Source ou compensar horas de outro dia, mas não será cobrado para ficar até mais tarde como acontece na maioria dos lugares.

**Trabalho remoto**

Possibilidade de ficar remoto quando necessário e posteriormente podemos ter abertura para ficar dias fixos da semana como home office. 

## Como se candidatar

Envie um e-mail (com Linkedin, Github, Site, etc... ou seja, o que tiver de legal p mandar 😄 ) para **afonso.pacifer@vallesistemas.com.br** com o assunto **Vaga Front** e se quiser da um salve aqui na issue ❤️

**Comment by LFeh** [comment]
O sr está morando em SP @afonsopacifer ?

**Comment by danlisboa** [comment]
salve

**Comment by yanmagale** [comment]
<3

**Comment by afonsopacifer** [comment]
@LFeh Sim!, Não tive tempo de dar OI direito pq preciso contratar hahaha, mas amanhã vou lá na cubo p ganhar um abraço de boas vindas ❤️

**Comment by LFeh** [comment]
No Meetup de Angular? 

Tamo junto 👊

**Comment by afonsopacifer** [comment]
@LFeh SIM!

**Comment by randhson** [comment]
enviado.

Randson N. dos S. França +55 79 99843 9878+55 79 99138 7628 

    Em quarta-feira, 10 de janeiro de 2018 13:59:36 BRT, Afonso Pacifer <notifications@github.com> escreveu:  
 
 
@LFeh SIM!

**Comment by danilosilvadev** [comment]
@afonsopacifer faz entrevista via skype?

**Comment by afonsopacifer** [comment]
@danilosilvadev Preferimos pessoalmente, mas podemos bater um papo via Skype sim, sem problemas :)

**Comment by gadielkalleb** [comment]
enviado ;)

**Comment by HaluDeCassia** [comment]
Por favor. Quando a vaga for possível ser full remoto. Avisa a gente, tem um pessoal considerável com interesse em vagas nesse tipo aqui, e essa vaga é tão boa ❤️

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
