### ISSUE TITLE
[São Paulo] Full Stack Developer na Infosys

### ISSUE THREAD

**Issue by KalvinNagano** [frontendbr/vagas#7303]
<!--
==================================================
Caso a vaga for remoto durante a pandemia deixar a linha abaixo
==================================================

## Nossa empresa

Sobre a Infosys:

Somos + de 300 mil profissionais no mundo.
Presente em 46 países
Reportar a pessoas da Índia, Europa, America Latina e EUA
1.626 clientes

Há muitas razões que levam um profissional a trabalhar em uma empresa – bons salários, designações de cargo, uma atuação com desafios constantes ou talvez a reputação da empresa. Na Infosys, de acordo com uma pesquisa junto aos seus colaboradores no mundo, os principais fatores apontados foram:

Equilíbrio e Qualidade de Vida: a Infosys preza pelo equilíbrio entre a vida pessoal e profissional dos seus colaboradores. Flexibilidade para Home Office. Dependendo do modelo de entrega adotado pelo cliente, a Infosys se adapta e flexibiliza a forma de trabalho.

Ambiente de Trabalho: a Infosys possui uma cultura de trabalho dinâmica. Apesar das posições hierárquicas a dinâmica de trabalho é bastante colaborativa e participativa. Incentivamos as atitudes pró-ativas, envolvimento e o “pensar fora da caixa”. Além disso, a participação em projetos globais, com vários públicos envolvidos, de diferentes países, proporciona ao profissional vivências interessantes.

Marca Infosys: A Infosys é uma empresa globalmente respeitada, com um “brand” reconhecido no mundo da Tecnologia da Informação. Sua relação com o mercado abrange empresas de grande porte em vários segmentos de indústria.

Treinamento e Desenvolvimento: a Infosys possui um vasto leque de opções quando o assunto é treinamento e desenvolvimento. Há uma série de plataformas próprias de aprendizagem, com mais de 10.000 conteúdos cursos. Além disso, as parcerias com Microsoft, AWS, Google, SAP, dentre outros, permitindo certificações sem custo.
DIFERENCIAL:  Parceira com a Harvard e Stanford (EUA).

## Descrição da vaga

O que estamos procurando para essa posição:

•	Ter boa base sobre programação orientada a objetos;
•	Saber JSE (JDK - Java Development Kit);
•	Saber Java EE (Enterprise Edition) para desenvolvimento de aplicações Web e webservices;
•	Ter trabalhado com alguns destes servidores de aplicação: Tomcat, Jboss ou Websphere;
•	Ter experiência em algum dos seguintes Back-end Frameworks:
•	Spring ; JPA e Hibernante para Banco de Dados; JUnit ou Log4J para Testes ; React ; Javascript para back-end
•	Ter experiência em algum dos seguintes Front-end Frameworks:
•	Javascript ; JSP; AngularJS ; ReactJS; NextJS; CSS; Bootstrap; JQuery

## Local

Híbrido, [São Paulo], 

## Requisitos

**Diferenciais:**

Será um diferencial ter desenvolvido aplicações para cloud utilizando Dockers ou Kubernetes;
Será um diferencial saber desenvolver serviços Rests;
Será um diferencial saber desenvolver serviços Webservices;

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ X/dia
- Auxílio creche

## Contratação

CLT a combinar

## Como se candidatar

Atraves do LinkedIn, segue link da vaga: https://www.linkedin.com/jobs/view/3225267499/

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.
E-mail para contato em caso de não haver resposta: kalvin.334744@infosys.com

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível

- Especialista
- Coordenador
- Gerente

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
