### ISSUE TITLE
[SÃO PAULO - ATUAÇÃO HÍBRIDA] 08 VAGAS - DESENVOLVEDOR FRONT-END  ANGULAR

### ISSUE THREAD

**Issue by patyandreolli** [frontendbr/vagas#7304]
**DESENVOLVEDOR FRONT-END  ANGULAR**

Expertise em Angular (a partir do 6) com experiência com Web Componentes, Typescript, ES6, Jest e Integração com Microserviços
Diferencial experiência em Cloud (Azure ou AWS)

Sera responsável pelo desenvolvimento em Front End  (Angular10) para empresa do ramo bancário, atividades em Squads, necessário conhecimento em Metodologia Agile.

Vaga: 08 vagas 
Contratação: CLT + Benefícios 
Atuação: Seg a sex - horario comercial   
Modelo de trabalho - Hibrido  - Zona Sul de São Paulo (3 dias presencias e 2 remotos - aberto para discussão)  

Envio de currículo: recrutamento@infovagas.com indicando no assunto "FrontEnd Angular - AT”
WhatsApp: (11) 98129-9574

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
