### ISSUE TITLE
[Remoto e Internacional] Full-stack Developer React/Node @ Lemon.io

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#7308]
**We’re Lemon.io — a marketplace where we match you with hand-picked startups from the US and Europe.** 

## Why work with us:

- We’ll find you a team that respects you. No time-trackers or any micromanagement stuff
- Our engineers earn $5k - $9k / month. We’ve already paid out over $10M.
- Choose your schedule. We have both full- and part-time projects.
- No project managers in the middle — only direct communications with clients, most of whom have a technical background
- Our customer success team provides life support to help you resolve anything.
- You don’t have to look for clients and or negotiate anymore: just do what you do best and leave us the rest.

## Requisitos

- 3+ years of software development experience
- Strong knowledge of JavaScript (Core, DOM APIs)
- 3+ years of experience with Node.js
- Experience with front-end JavaScript frameworks and libraries (React.js preferably)
- Understanding of and practical experience with SOLID principles and GOF patterns
- Understanding of CI principles
- Experience with Typescript and React Native would be a plus
- Good command of English, both written and spoken, as you’ll be communicating with clients directly
- Strong organizational skills — ability to work full-time remotely with no supervision
- Responsibility — we want to trust you
- Soft skills — we don’t ask you find a topic for a small talk, but being just polite is OK

## Salário

U$ 5.000 - U$ 9.000

**Apply today, and our team will get back to you within 2 business days!** 

## Nossa empresa

We’re Lemon.io — a marketplace where we match you with hand-picked startups from the US and Europe. 

## Como se candidatar

Click [here](https://remotar.com.br/job/1384/lemon.io/full-stack-developer-(reactnode)?utm_source=github) to see full description and apply

Obs: esta vaga está sendo anunciada pela Remotar em nome da Lemon.io, cliente de nossa empresa

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
