### ISSUE TITLE
[Remoto] React/React Native Developer na C2S - Contact2sale

### ISSUE THREAD

**Issue by blankapf** [frontendbr/vagas#7309]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-reactreact-native-developer-220105854?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>Contact2Sale</strong> busca <strong><ins>React/React Native Developer</ins></strong> para compor seu time!</p>
<p>Acreditamos que as soluções simples são as melhores. São mais intuitivas, mais fáceis de usar e consequentemente mais efetivas! Mas, diferentemente do que as pessoas pensam em geral, a simplicidade não é o primeiro passo. Para chegar a uma solução simples e efetiva, é preciso compreender profundamente o processo e a complexidade.</p>
<p></p>
<p><strong>Responsabilidades:</strong></p>
<ul>
<li>As responsabilidades serão vinculadas ao desenvolvimento voltado para sistemas web e mobile que usam<strong> </strong>React e React Native (expo);</li>
<li>Além disso, você também ajudará a evoluir e refazer algumas telas do sistema legado usando Ruby on Rails, HTML e jQuery.</li>
</ul>

## C2S - Contact2sale: 
 <p>Acreditamos que as soluções simples são as melhores. São mais intuitivas, mais fáceis de usar e consequentemente mais efetivas! Mas, diferentemente do que as pessoas pensam em geral, a simplicidade não é o primeiro passo. Para chegar a uma solução simples e efetiva, é preciso compreender profundamente o processo e a complexidade.</p>
<p>Acreditamos que as soluções simples são as melhores. São mais intuitivas, mais fáceis de usar e consequenteEm 2016, Fernando Vallocci e Bruno Yukihara fundaram o Gestor de Leads C2S (Contact2sale). Ambos foram executivos de grandes empresas como: Apple, Bain &amp; Co, Booz Allen, Telefônica, Lexmark e ImovelWeb. mente mais efetivas! Mas, diferentemente do que as pessoas pensam em geral, a simplicidade não é o primeiro passo. Para chegar a uma solução simples e efetiva, é preciso compreender profundamente o processo e a complexidade.</p><a href='https://coodesh.com/empresas/c2s-contact2sale'>Veja mais no site</a>

 ## Habilidades: 
 - React.js 
- React Native 
- GIT 
- HTML 5 
- Javascript
## Local: 
 100% Remoto
## Requisitos: 
 - Conhecimento e experiência em React, React Native e GIT; 
- Gostar de trabalhar em time; 
- Conhecimento em metodologias agéis (Scrum); 
- Habilidade e auto motivação para trabalhar remoto; 
- Ter conhecimento em HTML, CSS e Javascript; 
- Seja curioso e esteja sempre pesquisando sobre novas tecnologias; 
- Pense de forma arquitetural, sempre se preocupando com escala e evoluções futuras; 
- Possua capacidade de desenvolver sistemas do zero e também evoluir sistemas atuais; 
- Gostar de fazer Clean Code e soluções simples.
## Diferenciais: 
 - Conhecimento em Ruby on Rails; 
- Experiência ou conhecimento em Firebase, Docker; 
- EXPO (React Native); 
-  Habilidades de design; 
- Ter desenvolvido algum produto ou projeto por conta própria; 
- Capacidade de aprender novas tecnologias de forma rápida; 
- Ter participado de eventos de tecnologia.
## Benefícios: 
 - Horários Flexíveis; 
- 100% Remoto; 
- Oportunidade de crescimento.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [React/React Native Developer na C2S - Contact2sale](https://coodesh.com/vagas/frontend-reactreact-native-developer-220105854?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
