### ISSUE TITLE
[Remoto] Frontend (React) Developer na WTLL

### ISSUE THREAD

**Issue by blankapf** [frontendbr/vagas#7310]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-front-end-react-180902869?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>WTLL</strong> busca <strong><ins>Frontend (React) Developer</ins></strong> para compor seu time!</p>
<p>Buscamos <strong>Desenvolvedores Frontend: Júnior (com alguma experiência React), Pleno ou Sênior</strong> também com experiência em React.</p>
<p>Somos uma empresa focada em entregar exatamente os Softwares que nossos clientes precisam para potencializar ainda mais os seus negócios. Para Apps, Sistemas Web, Desktop  ou basicamente qualquer demanda tecnológica que exija os melhores profissionais do Mercado, conte conosco.</p>

## WTLL: 
 <p>Somos uma empresa focada em entregar exatamente os Softwares que nossos clientes precisam para potencializar ainda mais os seus negócios.&nbsp;</p>
<p>Para Apps, Sistemas Web, Desktop  ou basicamente qualquer demanda tecnológica que exija os melhores profissionais do Mercado, conte conosco.</p><a href='https://coodesh.com/empresas/wtll'>Veja mais no site</a>

 ## Habilidades: 
 - React.js 
- HTML 
- CSS 
- Javascript
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência com react.js.

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend (React) Developer na WTLL](https://coodesh.com/vagas/desenvolvedor-front-end-react-180902869?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by icaroleon** [comment]
Enviado!

**Comment by VitorVeector** [comment]
Enviado!

**Comment by shirator** [comment]
Aplicado!

**Comment by Chuu5** [comment]
Enviado!

**Comment by allbertuu** [comment]
Vaga fechada. @felipefialho @moderacaofrontendbr

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
