### ISSUE TITLE
[Niterói - Híbrido] Front-end Developer na Internit

### ISSUE THREAD

**Issue by Fredpeixoto** [frontendbr/vagas#7315]
## Descrição da vaga

Exemplo: Projeto bazinga em NodeJS, etc.

## Local

Híbrido [RJ], [Niterói], [Santa Rosa]

## Requisitos

**Obrigatórios:**
Boa experiência prática com HTML5, CSS3 e compiladores (SASS ou LESS...), framework Java Script (Next,  Vue ou React) e ter um vasto portfólio para apresentar. É indispensável ter o seu currículo cadastrado no nosso site.

## Benefícios

- Plano de saúde
- Plano dentário
- Vale transporte
- VR 

**Diferenciais:**
Ótimo ambiente de trabalho somado a desafios constantes.
Estamos localizados em uma rua em Santa Rosa - Niterói com facilidade de estacionamento além de termos um bicicletário na empresa. 

## Como se candidatar

Acesse http://www.internit.com.br/curriculo e cadastre seu currículo.

#### Regime
- CLT ou PJ (à combinar)

#### Nível
- Júnior

**Comment by gabrielbugarelli** [comment]
Enviado.

**Comment by LeandroSanto** [comment]
Dados encaminhados.

**Comment by fernandopredes** [comment]
Enviado. 😀

**Comment by Fredpeixoto** [comment]
Obrigado pelo seu retorno. Iremos analisar e qualquer novidade entraremos
em contato.

[image: Internit]
*www.internit.com.br
<https://mailtrack.io/trace/link/90a31874fd90c38b82a4583dc2bb489bc79278b2?url=http%3A%2F%2Fwww.internit.com.br%2F&userId=393368&signature=c6593c9e7c97da5c>**www.incenadigital.com.br
<https://mailtrack.io/trace/link/5a03af4dcad3e23b243c92b4aaeb31c71374792e?url=http%3A%2F%2Fwww.incenadigital.com.br%2F&userId=393368&signature=1cf732dd214ecdff>*
 RJ
<https://mailtrack.io/trace/link/2058a60efbca6fbcea9732b50f2e6936772e8297?url=https%3A%2F%2Fwww.google.com%2Fmaps%2Fplace%2FR.%2BItaperuna%2C%2B100%2B-%2BP%25C3%25A9%2BPequeno%2C%2BNiter%25C3%25B3i%2B-%2BRJ%2C%2B24240-070%2F%40-22.8961089%2C-43.1073818%2C17z%2Fdata%3D!3m1!4b1!4m5!3m4!1s0x9983f238c0e803%3A0x36d8501864605205!8m2!3d-22.8961089!4d-43.1051931&userId=393368&signature=b9b8f19498afee7f>
  SP
<https://mailtrack.io/trace/link/10e201b48923844075239553865df2f50881d343?url=https%3A%2F%2Fwww.google.com%2Fmaps%2Fplace%2FRua%2BNorma%2BPieruccini%2BGiannotti%2C%2B141%2B-%2BV%25C3%25A1rzea%2Bda%2BBarra%2BFunda%2C%2BS%25C3%25A3o%2BPaulo%2B-%2BSP%2C%2B01137-010%2Fdata%3D!4m2!3m1!1s0x94ce580ebf4681b1%3A0xbc9940a345bbe3e6%3Fsa%3DX%26ved%3D2ahUKEwjm9rTIpdvkAhUcK7kGHZ-bDkEQ8gEwAHoECAoQAQ&userId=393368&signature=3611ca8b475b2369>
*Frederico
Peixoto*
Diretor Comercial
***@***.***
(21) 2621-7788 <+55212621-7788> | (21) 98123-2303 <+552198123-2303>
[image: Acompanhe a Incena no Facebook]
<https://mailtrack.io/trace/link/e97a20302c1c72d1b7258729b366d080298f96cc?url=https%3A%2F%2Fwww.facebook.com%2Fincenadigital&userId=393368&signature=502c4cb067021a52>
[image:
Acompanhe a Incena no Facebook]
<https://mailtrack.io/trace/link/695bd4211d38574e1db7599f411b682d87f62fa9?url=https%3A%2F%2Fwww.instagram.com%2Fincenadigital%2F&userId=393368&signature=913ecc113c92d74c>
[image:
Siga-me no Linkedin]
<https://mailtrack.io/trace/link/e8bf96fe561404c0ef98773b2012a5ca1c43c15c?url=https%3A%2F%2Fwww.linkedin.com%2Fin%2Ffredericopeixoto%2F&userId=393368&signature=6a4c90635e049872>


Em qui., 1 de set. de 2022 às 19:36, 'Fernando PREDES' via Vagas <
***@***.***> escreveu:

**Comment by Fredpeixoto** [comment]
Obrigado pelo seu retorno. Iremos analisar e qualquer novidade entraremos
em contato.

[image: Internit]
*www.internit.com.br
<https://mailtrack.io/trace/link/dd5876778523c474ed4268dac93f0b9e0e47b569?url=http%3A%2F%2Fwww.internit.com.br%2F&userId=393368&signature=9d7092c40e212ce8>**www.incenadigital.com.br
<https://mailtrack.io/trace/link/8ef7d0884fcb7a8c5fe1a3e7fe75c13ec1cb9abf?url=http%3A%2F%2Fwww.incenadigital.com.br%2F&userId=393368&signature=108d93f24a07827a>*
 RJ
<https://mailtrack.io/trace/link/c2ff40da3771faeacb4f531187589022217ed619?url=https%3A%2F%2Fwww.google.com%2Fmaps%2Fplace%2FR.%2BItaperuna%2C%2B100%2B-%2BP%25C3%25A9%2BPequeno%2C%2BNiter%25C3%25B3i%2B-%2BRJ%2C%2B24240-070%2F%40-22.8961089%2C-43.1073818%2C17z%2Fdata%3D!3m1!4b1!4m5!3m4!1s0x9983f238c0e803%3A0x36d8501864605205!8m2!3d-22.8961089!4d-43.1051931&userId=393368&signature=23b6f1a2d30cee85>
  SP
<https://mailtrack.io/trace/link/55f7079cac5994168fe83cf976fa71926860f022?url=https%3A%2F%2Fwww.google.com%2Fmaps%2Fplace%2FRua%2BNorma%2BPieruccini%2BGiannotti%2C%2B141%2B-%2BV%25C3%25A1rzea%2Bda%2BBarra%2BFunda%2C%2BS%25C3%25A3o%2BPaulo%2B-%2BSP%2C%2B01137-010%2Fdata%3D!4m2!3m1!1s0x94ce580ebf4681b1%3A0xbc9940a345bbe3e6%3Fsa%3DX%26ved%3D2ahUKEwjm9rTIpdvkAhUcK7kGHZ-bDkEQ8gEwAHoECAoQAQ&userId=393368&signature=f442a5d35805d31c>
*Frederico
Peixoto*
Diretor Comercial
***@***.***
(21) 2621-7788 <+55212621-7788> | (21) 98123-2303 <+552198123-2303>
[image: Acompanhe a Incena no Facebook]
<https://mailtrack.io/trace/link/eb55e30bb8e5f1eced4ad3e2f56cb48f3f7d6d50?url=https%3A%2F%2Fwww.facebook.com%2Fincenadigital&userId=393368&signature=bd6ffae0a1cd6d5d>
[image:
Acompanhe a Incena no Facebook]
<https://mailtrack.io/trace/link/195f83accf66b42f5713988f2516cb832dbb9f32?url=https%3A%2F%2Fwww.instagram.com%2Fincenadigital%2F&userId=393368&signature=9d0db0a81269bec5>
[image:
Siga-me no Linkedin]
<https://mailtrack.io/trace/link/2b712276dd8105283102de8fd334e4aa1260f6bc?url=https%3A%2F%2Fwww.linkedin.com%2Fin%2Ffredericopeixoto%2F&userId=393368&signature=3288ad16c5623a09>


Em sáb., 20 de ago. de 2022 às 17:55, 'Gabriel Fonseca' via Vagas <
***@***.***> escreveu:

**Comment by matheusdamiao** [comment]
Currículo enviado!

**Comment by Alberigi** [comment]
Ainda está aberta ?

**Comment by Fredpeixoto** [comment]
Sim



Em qua., 26 de out. de 2022 às 16:22, 'Mat Alberigi' via Vagas <
***@***.***> escreveu:

**Comment by matheuslei** [comment]
Aplicado! 👩‍💻

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
