### ISSUE TITLE
[ São Paulo ] Front-end Developer na Bars Over Bottles

### ISSUE THREAD

**Issue by robsonss** [frontendbr/vagas#7317]
> Vaga Remota

## Nossa empresa

Somos uma empresa multinacional de cosméticos sólidos que visa reduzir o uso de embalagens, zerar o uso de plástico e acabar com a contaminação de nossas águas.

Bars Over Bottles É assim, com produtos ZERO PLÁSTICO, desenvolvidos com muito carinho e esperança. quer fazer sua parte e ajudar o planeta a ser um lugar bem mais legal no futuro. A gente não sabe quais atitudes você tem tomado para colaborar, mas sejam quais forem, o convite que fazemos é o mesmo: vamos juntos? ☺

## Descrição da vaga

Buscamos Front-end Developer para atuar no time de Desenvolvimento, que irá atuar em conjunto com o time de UX/UI transformando protótipos em códigos precisos e rápidos, para garantir a melhor experiência de nossos clientes em nossos sites no Brasil, Estados Unidos, e Europa.

## Local

São Paulo - Zona Sul

## Requisitos

**Obrigatórios:**
- HTML, CSS, Java Script, Jquery
- Pré-processadores Sass, Less ou outros
- Automatizadores de Tarefas como: (Grunt ou Gulp)
- Não utilizar framworks bootstrap, foundation, ou afins

**Desejáveis:**
- Boas práticas de SEO
- APIs Rest
- React

**Diferenciais:**
- Shopify
- Liquid
- Vue.js
- Experiência com alguma plataforma de ecommerce

## Benefícios

- Plano de saúde
- Vale Transporte ou Combustível
- VR / VA
- Jornada Flexível
- Kit B.O.B uma vez por mês
- Dayoff de Aniversário

## Contratação

CLT

**Observações:
Trabalho no modelo home office, podendo ser hibrido. A escolha fica à seu critério.
Temos dois locais de trabalho em São Paulo. Um escritório localizado na Zona Sul, e outro em Pinheiros. você escolhe aonde deseja trabalhar fisicamente, ou escolhe ficar em casa ☺

## Como se candidatar

Por favor envie um email para [robson@usebob.com.br](mailto:robson@usebob.com.br) com seu CV anexado e Portfolio se possuir - enviar no assunto: Vaga Front-end JR

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Shopify

**Comment by icaroleon** [comment]
Enviado!

**Comment by dandankara** [comment]
Enviado @robsonss

**Comment by hugoleogs** [comment]
Feito @robsonss

**Comment by VitorVeector** [comment]
Enviado!

**Comment by gustavomarim** [comment]
Enviado!

**Comment by israelss** [comment]
Enviado @robsonss!

**Comment by jonatasvaz** [comment]
enviado

**Comment by sycrot** [comment]
Enviado!

**Comment by GabrielVinhas** [comment]
Enviado!

**Comment by andrefhz** [comment]
Enviado

**Comment by brenooliveiranascimento** [comment]
Enviado!

**Comment by calvitoria** [comment]
Enviado, @robsonss 🚀

**Comment by ViniciusEvans** [comment]
enviado!

**Comment by GledsonLucas111** [comment]
enviado!

**Comment by EndersonF** [comment]
Enviado!

**Comment by Chuu5** [comment]
Enviado!

**Comment by LailtonSoares** [comment]
Enviado!

**Comment by AOdachowoski** [comment]
Enviado!!

**Comment by GabrielVinhas** [comment]
Enviado!!!
