### ISSUE TITLE
[Uberaba-MG] Front-End/Full Stack Developer na Grão Direto

### ISSUE THREAD

**Issue by fmarques2** [frontendbr/vagas#732]
[Vagas na Grão Direto](www.graodireto.com.br/vagas)

**Requisitos**

- Superior em Ciência ou Engenharia da Computação, Sistemas da Informação, Eng. de software ou similar.
- Inglês intermediário (leitura e listening).
- Compreensão de texto e saber escrever (ortografia, gramática, concatenação de ideias).
- Lógica de programação (algoritmos e complexidades).
- Banco de dados relacional (modelagem, consultas).
- Programação orientada a objetos.
- Contato/conhecimento em Node, Java ou Javascript. 
- Git/github (commits, branches, tags, repositórios locais e remotos, etc)
- HTML/CSS.
- Boas práticas de arquitetura de soluções (componentização, coesão, acoplamento, padrão MVC, etc).
- Boas práticas de desenvolvimento (Clean Code).

Diferenciais:

- Ionic, angularJs, angular2.
- Amazon Web Services (AWS)
- UX

**O que farei?**
O(a) selecionado(a) fará parte do time de desenvolvedores da Grão Direto, que é reponsável pela criação e manutenção de novos produtos, serviços e funcionalidades, tanto de backend quanto de front-end. O time trabalha com metodologias ágeis e entregas contínuas, gerando código inteligível, limpo, testado e respeitando as melhores práticas de codificação. A imersão no negócio é total e criamos, desde sua concepção, produtos que, além de gerarem valor, são escaláveis, seguros, robustos e que nos dão orgulho!
Espera-se, do(a) selecionado(a), excelente capacidade de trabalho em equipe, capacidade de aceitar mudanças, busca contínua de conhecimento e "paixão por codificar". 

**Detalhes**

- Estamos buscando talentos Júnior , Pleno ou Sênior 
- Salário compatível com a senioridade que será avaliada durante o processo
- Contratação CLT
- Disponibilidade para residir em Uberaba-MG (auxílio mudança caso não resida ainda na cidade)
- **Enviar currículo para time@graodireto.com.br com o assunto [Dev] - seu nome** 

**Sobre a Grão**
Somos uma startup que utiliza a tecnologia para revolucionar a comercialização no agronegócio, um setor que movimenta bilhões por ano e onde o Brasil é referência no mundo!
Para este imenso desafio queremos os melhores talentos juntos com a gente!
Fomos vencedores do Demoday da 15ª edição da Startup Farm, maior aceleradora da América Latina, finalistas do Inovativa Brasil e parceiros da Esalqtech, referência acadêmica no agronegócio brasileiro.
Temos um incrível time de investidores nacionais e internacionais que trazem grande expertise em agro, finanças e tecnologia.
Somos apaixonados por tecnologia e por pessoas incríveis. Acreditamos que é essa combinação que soluciona grandes desafios!

**Cultura**

- Ambiente jovem, aberto, divertido.
- Valorizamos as coisas realmente importantes. (Bullshit free zone)
- Montamos times f* com feedback constante, transparência e colaboração.
- Cultura de aprendizado rápido e contínuo.
- Autonomia e espaço para ideias de todos os colaboradores.
- Somos justos e valorizamos a meritocracia e evolução profissional.

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
