### ISSUE TITLE
[Remoto] Front-end React Developer na Hub Home Box

### ISSUE THREAD

**Issue by blankapf** [frontendbr/vagas#7324]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-developer-react-142738038?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A empresa <strong><ins>Hub Home Box</ins></strong> está procurando um <strong><ins>Front-end Developer React Júnior/Pleno</ins></strong> para compor seu time!</p>
<p>O Hub Home Box é um portal especializado em clubes de assinatura. Cada vez mais populares no Brasil, esses clubes nada mais são do que encomendas que os assinantes recebem mensalmente no conforto de suas casas. A diferença entre o clube de assinatura e uma encomenda comum é que os clubes são um serviço regular e dão aos assinantes experiências personalizadas de recebimento. Desde o detalhe da caixa até a seleção de produtos, a sensação que o cliente tem ao receber seu kit é a de ganhar um presente.</p>
<p></p>

## Hub Home Box: 
 <p>O <strong>Hub Home Box</strong> é um portal especializado em clubes de assinatura. Cada vez mais populares no Brasil, esses clubes nada mais são do que encomendas que os assinantes recebem mensalmente no conforto de suas casas.</p>
<p>A diferença entre o clube de assinatura e uma encomenda comum é que os clubes são um serviço regular e dão aos assinantes experiências personalizadas de recebimento. Desde o detalhe da caixa até a seleção de produtos, a sensação que o cliente tem ao receber seu kit é a de ganhar um presente.</p><a href='https://coodesh.com/empresas/hub-home-box'>Veja mais no site</a>

 ## Habilidades: 
 - SQL 
- Figma 
- UX 
- Javascript
## Local: 
 100% Remoto
## Requisitos: 
 - Conhecimentos em React; 
- Conhecimentos em UX e Figma; 
- Perfil dedicado e envolvido; 
- Gostar de aprender; 
- Conhecimentos em API's.
## Diferenciais: 
 - Conhecimentos em Photoshop; 
- Conhecimento no backend utilizando C# ou PHP.
## Benefícios: 
 - Vale alimentação: R$200~300,00/mês 
- Voucher de benefícios dentro do site: R$150,00
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Front-end React Developer na Hub Home Box](https://coodesh.com/vagas/frontend-developer-react-142738038?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Front-End

**Comment by gustavomarim** [comment]
Enviado!

**Comment by alison0098** [comment]
Olá!
Está fechado para envios.

**Comment by xXshadowbrokerXx** [comment]
O formulário está fechado para envio

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
