### ISSUE TITLE
[Remote] Fullstack Python+Vue Developer at Jobsity

### ISSUE THREAD

**Issue by ninnameister** [frontendbr/vagas#7326]
Winter is coming GitHub community! ❄️ That's why at [Jobsity ](https://www.jobsity.com/) we're looking for Vue+Python Developer with 3+ years of experience and a good English level to to join our pack to defend the Seven Kingdoms!

We offer a fulltime American contract, USD compensation and benefits such as the following:

- 15 working days of paid vacations
- 3 extra off days per year
- Unlimited PTOs (Paid Time Off)
- Paid and flexible local holidays
- Budget for e-learning courses
- Financing program for equipment
- Bonuses for referrals

Would you like to find out more? ⚔️

Drop me a line via [ninna.meister@jobsity.com](ninna.meister@jobsity.com) or [Linkedin](https://www.linkedin.com/in/ninnamonego/) and I can share more info so you can decide if you'd like to apply!❄️⚔️

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
