### ISSUE TITLE
[Remoto] Front-end Developer na Apê11

### ISSUE THREAD

**Issue by vagasape11** [frontendbr/vagas#7327]
## Nossa empresa

Somos uma plataforma digital de compra e venda de imóveis na cidade de São Paulo.
Temos um time de especialistas que conhece cada canto da cidade, por isso, conhecemos o seu bairro e as melhores oportunidades para o seu negócio e para o seu estilo de vida. 
Nosso compromisso é no atendimento com excelência. De pessoa para pessoa, com olho no olho e singularidade.
Conte com a Apê11 uma empresa Santander para comprar ou vender um imóvel na cidade de São Paulo.

Estamos te esperando. É só entrar.

## Descrição da vaga

- Auxiliar no processo de desenvolvimento e manutenção de websites;
- Desenvolvimento e manutenção de aplicações web;
- Realizar a manutenção e criação de novas funcionalidades;
- Aplicar melhores práticas de documentação de código desenvolvido;
- Desenvolvimento de funcionalidades no Front-End;
- Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas;
- Manutenção de páginas;
- Correção de bugs;
- Programar novas funcionalidades;
- Projetar e especificar as interações entre os usuários e a solução/produto, as respostas do sistema, sua estrutura geral e as possíveis interferências.

## Local

Remoto ou modelo híbrido, [SP], [São Paulo], [Bela Vista]

## Requisitos

**Obrigatórios:**
- Experiência em desenvolvimento Front End, com HTML, Javascript, CSS e PHP;
- Experiência de integração de Front End usando APIs REST previamente disponibilizadas pelo time de Backend;
- Definição de padrões de desenvolvimento;
- Vue.js;
- Integração de front end utilizando APIs GraphQL;
- Conhecimentos de HTML, Javascript, PHP;
- Conhecimentos técnicos em design e usabilidade de interfaces, arquitetura da informação;
- Possuir conhecimento em frameworks PHP;

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para karen.fermino@ape11.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: karen.fermino@ape11.com.br

##

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
