### ISSUE TITLE
[São Paulo] Front-End Developer - Angular 2+

### ISSUE THREAD

**Issue by marcosqueiroga** [frontendbr/vagas#733]
## Descrição da vaga

Busco um desenvolvedor front-end freelancer para construção de um site.
A ideia é converter um PSD já existente para HTML e consumir uma API quer será disponibilizada.

## Local

Remoto

## Requisitos

- Experiência com Angular 2+
- Experiência com Bootstrap 3+
- Experiência com conversão de PSD para HTML

## Contratação

Freelancer

## Como se candidatar

E-mail para marcos.queiroga@gmail.com

**Comment by rainerlopez** [comment]
Done (y)

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
