### ISSUE TITLE
[Remoto] Frontend Developer (React) na Samba Tech

### ISSUE THREAD

**Issue by blankapf** [frontendbr/vagas#7331]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/pessoa-desenvolvedora-front-end-react-203608535?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>Samba Tech</strong> busca <strong><ins>Frontend Developer (React)</ins></strong> para compor seu time!</p>
<p>A Samba está buscando uma Pessoa Desenvolvedora Front End  para agregar ao nosso time! Para essa oportunidade buscamos uma pessoa para atuar em regime PJ e 100% remoto. Procuramos alguém com propósito forte e que esteja disposta a trabalhar em ambiente colaborativo e dinâmico, pronto para crescer profissionalmente junto com a nossa equipe fora da curva! A Samba gosta de fazer a diferença sempre e nosso time é o responsável para que isto aconteça! Por isso, a gente espera que você seja uma pessoa apaixonada por tecnologia, assim com a gente! Todas as nossas vagas também se aplicam a pessoas com deficiência, então fique à vontade para se candidatar!</p>
<p><strong>Responsabilidades e atividades:</strong></p>
<ul>
<li>Desenvolvimento de software aplicando as boas práticas de codificação e padrões de projeto sempre pensando em sustentabilidade, segurança, escalabilidade e custo;</li>
<li>Auxiliar na análise e elaboração de arquitetura dos requisitos que serão desenvolvidos no projeto;</li>
<li>Apoiar o desenvolvimento profissional de juniores do time de front-end;</li>
<li>Documentação das arquiteturas propostas;</li>
<li>Realização de revisões de código para garantir artefatos padronizados e de qualidade;</li>
<li>Orientação nas implementações de testes automatizados;</li>
<li>Sugestão de modelos de desenvolvimento que aumente a qualidade dos produtos e a agilidade dos times;</li>
<li>Aplicar e difundir as boas práticas de segurança no projeto;</li>
<li>Garantir que as soluções propostas sejam adequadas a política de custos de projetos da companhia.</li>
</ul>

## Samba Tech: 
 <p>A Sambatech é uma das empresas mais inovadoras do mundo, segundo a Fast Company, e é referência no mercado de vídeos online. Nossa empresa garante infraestrutura de alta qualidade para venda, distribuição, gerenciamento e armazenamento de vídeos e ajuda pessoas e empresas a terem mais sucesso, independentemente do seu objetivo.</p>
<p>Com suas soluções, a Samba atende diferentes tipos de necessidades relacionadas aos conteúdos audiovisuais e possui uma equipe totalmente focada em assegurar que nossos clientes tenham acesso ao que há de melhor em tecnologia para vídeos online.&nbsp;&nbsp;&nbsp;</p><a href='https://coodesh.com/empresas/samba-tech'>Veja mais no site</a>

 ## Habilidades: 
 - Angular 9 
- HTML 
- CSS
## Local: 
 100% Remoto
## Requisitos: 
 - Sólido conhecimento em HTML, CSS, e HTML, e ReactJs; 
- Conhecimento em mais de um framework frontend (Vanilla, AngularJS, Angular, Vue, etc); 
- Experiência com projetos de arquitetura de software; 
- Boa experiência no desenvolvimento de aplicações responsivas; 
- Conhecimento de testes unitários; 
- Conhecimento em cloud computing e orquestração de containers (Docker, Kubernetes...); 
- Conhecimento e experiência com web vitals.
## Diferenciais: 
 - Conhecimento de NextJS; 
- Experiência com AngularJS; 
- Experiência com Typescript; 
- Experiência com Bundlers e module federation (webpack, rollup, gulp...); 
- Experiência em ecommerce/aplicações B2C; 
- Boas noções de UX; 
- Experiência com CI/CD (github actions, dangerjs, linting, chromatic); 
- Experiência com SEO.

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Developer (React) na Samba Tech](https://coodesh.com/vagas/pessoa-desenvolvedora-front-end-react-203608535?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
