### ISSUE TITLE
[Rio de Janeiro] Frontend Developer @ Buus

### ISSUE THREAD

**Issue by aikeda** [frontendbr/vagas#7332]
![](https://buus.s3-sa-east-1.amazonaws.com/images/Facebook+Cover.png)

## Sobre a Buus
> Tenho 3.000 funcionários que precisam chegar até uma fábrica. Qual a menor frota que preciso contratar para fazer todos os deslocamentos em menos de 1h30? Qual o ônibus devo pegar e por onde ele passa?

Organizar e manter a logística do **transporte de passageiros** em áreas mal servidas pelo transporte público, sem tecnologia, é demandante e custoso para as empresas. E o que todos querem é eficiência nos processos e humanidade ao lidar com os passageiros.

Nós da **[Buus](https://www.linkedin.com/company/5020309)**, somos uma empresa de **tecnologia** e **mobilidade** focada na gestão do transporte de colaboradores. E fazemos isso através da nossa plataforma que atende empresas de óleo & gás, manufatura, TI, esportes e outros segmentos. Listadas na Fortune 500, no Brasil e no mundo (LATAM). 

Estamos a procura de um _frontend developer_ com para elevar a barra no setor de transportes.

## O que usamos?

- React &#129488; React Native e Angular

Caso você tenha interesse em se aventurar em outros stacks, vale saber que também usamos:
- Python, Django, DRF, Node;
- Nativo Android e iOS, mas também React Native;
- AWS (Lambda, Athena, EC2, Cloudfront, S3, RDS, Elasticache, Quicksight, etc)
- Slack ;)

## Onde ficamos?
Flamengo, Rio de Janeiro &#127958;

## Onde trabalharei?
Híbrido: a ideia é fazer algo misto entre presencial e remoto.

## O que buscamos?
Pessoas com disposição (!), curiosidade e certa bagagem (pleno). Sem apego à um tecnologia ou linguagem e que buscam um conhecimento amplo sobre a tecnologia e suas práticas (arquiteturas, patterns, testabilidade, algoritmos, DB, etc).

## Modelo de contratação
CLT

## Remuneração & Benefícios
- Remuneração competitiva - gostaríamos de ouvir sua pretensão salarial;
- Trabalho flexível, um híbrido entre remoto e presencial;
- Plano de saúde;
- Vale refeição ou vale alimentação;
- Day off para o seu aniversário.

## Contato
Mande seu e-mail com CV para: vagas@buus.com.br

**Labels**
- Híbrido
- CLT
- Frontend
- React
- Angular
- Javascript
- Pleno

**Comment by guidani** [comment]
Tem a Label Remoto, mas a vaga é Hibrido. Está incorreto.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
