### ISSUE TITLE
[REMOTO] React Native Developer na Eureka Labs

### ISSUE THREAD

**Issue by Marianagana** [frontendbr/vagas#7334]
### EUREKA LABS

Se você busca autonomia e evolução contínua, quer trabalhar em um lugar bom e que te ofereça muitas oportunidades: A Eureka é o lugar para você!

### Descrição da vaga

Requisitos técnicos:

-Conhecimento avançado de Desenvolvimento Mobile

-Conhecimento avançado de **React Native**

-Conhecimento sobre **Typescript**

-Conhecimento básico sobre **Android e IOS**

### Local
REMOTO

### Perfil:
-Boa analise técnica e sistêmica parar propor soluções e autonomia na execução das atividades para entrega-la de acordo com os requisitos.

-Foco na geração de valor para o cliente.

-Comprometimento e proatividade.

### Contratação
PJ.

### Como se candidatar
Por favor envie um email para rh@eurekalabs.com.br

### Alocação
- Remoto

### Regime
- PJ

### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
