### ISSUE TITLE
[Remoto] React/React-Native jr/pl/sr/lead na Post2B

### ISSUE THREAD

**Issue by lfalcao** [frontendbr/vagas#7335]
## A empresa

A Post2B é um marketplace que conecta influenciadores a marcas e agências. Hoje temos em torno de 90000 influenciadores cadastrados e estamos desenvolvendo novas soluções para esse público 😄 

## Descrição da vaga

Estamos buscando desenvolvedores full-time com experiência em desenvolvimento frontend (React), mobile (React-Native) e/ou backend (Ruby/Python) para ajudar com nosso sistemas. Nossa stack hoje se resume a uma API em Ruby on Rails, alguns microserviços, um front em React e um app em React Native (ios e android).

Idealmente, a pessoa deve ter disponibilidade de 8 horas diárias (horário flexível).

## Local

Remoto.

## Requisitos

**Obrigatórios:**
- conhecimento em javascript
- experiência com react
- layout responsivo
- testes automatizados
- consumo de apis
- git

**Desejavel:**
- experiência em ruby on rails
- experiência com react native
- inglês intermediário
- firebase

## Contratação

- PJ/Freelancer
- Remuneração entre 4k a 15k - a depender da experiência.
- Bonificação por resultado (salário extra).
- Cartão Benefícios e Plano de Saúde.

## Como se candidatar

Por favor envie um email com pretensão, disponibilidade e currículo/linkedin para vagas(arroba)post2b.com com seu CV anexado - enviar no assunto: Vaga Dev

**Não temos interesse em empresas de desenvolvimento/outsourcing/terceirização/part-time.**

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.

## Labels

- Remoto
- Freela
- PJ
- Pleno
- Sênior

**Comment by guidani** [comment]
Mandei.

**Comment by Carolinepandolfe** [comment]
Enviado.

**Comment by dsslucas** [comment]
Enviado.

**Comment by jrsousadev** [comment]
Enviado!

**Comment by Ericckm** [comment]
Enviado!

**Comment by Chuu5** [comment]
Enviado.

**Comment by 365rafael** [comment]
Top!

**Comment by melegao** [comment]
Enviado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
