### ISSUE TITLE
[REMOTE] Webflow Developer na Rocket.Chat

### ISSUE THREAD

**Issue by NataliaVillain** [frontendbr/vagas#7337]
## Nossa empresa

Today one of the largest open-source projects in the world with more than 1000 developers, Rocket.Chat has advanced as a platform that empowers people to collaborate with others, while empowering individual teams to fully customize their platform to meet their unique needs.

Ranked among the [100 Most Transparent Tech Companies of 2021](https://t.co/RL445ItG4e) by The Org, Rocket.Chat lives by its core values of dreaming, owning, trusting, and sharing (or as we call them, our DOTS!), taking being open beyond the product into the Rocketeers' daily lives!

## Descrição da vaga

Rocket.Chat is looking for an experienced Webflow Developer to develop, manage, build and maintain the corporate website and landing pages using Webflow. The ideal candidate should have a keen eye for detail, strong communication skills, and work independently. Prior experience building and designing Webflow websites is a must for this role. This role would be directly reporting to the Director of Revenue Marketing.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência com Webflow (aprox. 2 anos)
- Inglês Avançado
- Figma

**Desejáveis:**
- conhecimentos em javascript
- conhecimentos em react

**Diferenciais:**
- projetos open source

## Benefícios

- Plano de saúde / odonto
- VR de R$ 28/dia
- Stockoptions
- iTalki
- Gympass
- Auxílio Home Office / mensal

## Contratação

CLT

## Como se candidatar

Por favor, candidatar-se em https://www.rocket.chat/job?gh_jid=4639436004

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.
E-mail para contato em caso de não haver resposta: natalia.villain@rocket.chat

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

**Comment by NicholasTavares** [comment]
Júnior... 2 anos de experiência. Triste.

**Comment by carlosaflach** [comment]
Júnio com 2 anos de experiência..

**Comment by carlosaflach** [comment]
Júnior com 2 anos de experiência..

**Comment by NataliaVillain** [comment]
Oi Nicholas e Carlos,

Conforme consta na descrição, estamos à procura de uma pessoa Júnior ou Pleno, por isso os 2 anos de experiência. Não significada que iremos avaliar somente esse requisito. Assim como todos os nossos processos, nós avaliamos o candidato em sua totalidade.

**Comment by saviocunha2** [comment]
enviado
