### ISSUE TITLE
[São Paulo] Front-End Developer (Angular) na BRQ Digital Solutions

### ISSUE THREAD

**Issue by ReAnne123** [frontendbr/vagas#734]
Programador Front End Sênior (Angular)

Grande banco localizado na Faria Lima busca profissional com experiência nas seguintes tecnologias: 
HTML, CSS, Angular, SASS, Gulp. Experiência com NPM e gerenciamento de dependências, 
continuos delivery, Scrum, GIT.
Contratação CLT, salário a combinar mais atrativo pacote de benefícios (VR, Vale alimentação, assistência médica e odontológica, seguro de vida, previdência privada).
Vagas presenciais no cliente.
Início em Fevereiro e prazo indeterminado.
Horário comercial.
Local: Faria Lima (próximo a Av, Juscelino Kubitschek).

Fundada em 1993, a BRQ Digital Solutions é uma das maiores empresas de serviços de TI do país. Conta com 3000 profissionais distribuídos nas filiais de São Paulo, Alphaville, Rio de Janeiro, Curitiba, Recife, Salvador, Brasília, Natal e Nova Iorque. 

Por favor envie um email para Renata - ryokota@brq.com com seu CV anexado - enviar no assunto: Vaga Angular.

**Comment by MatheusWTF** [comment]
É apenas para sênior? Não entendi pois têm labels de Junior e Pleno, mas o texto diz "Programador Front End Sênior (Angular)"

**Comment by LFeh** [comment]
My bad

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
