### ISSUE TITLE
[Remoto] Desenvolvedor (a) Front-end (React) Pleno @LIBER

### ISSUE THREAD

**Issue by palomagarcel** [frontendbr/vagas#7341]
## Liber

Estamos à procura de pessoas desenvolvedoras que estejam dispostas a participar da criação, evolução e manutenção de nossos produtos, ajudando a criar a plataforma mais completa de financiamento da cadeia produtiva, impactando milhares de pessoas.

## Descrição da vaga

Você irá trabalhar em um time multidisciplinar, sendo um (a) dos (das) responsáveis pela implementação da interface, mas contribuindo em todas as etapas do desenvolvimento (desde a ideação até a entrega e acompanhamento do uso pelos clientes).

## Responsabilidades

- Implementar toda a parte visual de novas funcionalidades e produtos a partir de protótipos de alta fidelidade, bem como ajustar e melhorar as interfaces já implementadas, escrevendo código em inglês
- Consumir os componentes e ajudar na manutenção do Saltí, nosso Design System
- Entender a dor de nossos clientes e participar da construção das soluções, juntamente com outros desenvolvedores, designers e PM
- Ter o hábito de prezar pela qualidade do código, utilizando boas práticas de desenvolvimento, refatoração e revisando código dos pares

## Local

- Remoto - temos colaboradores de todo canto do Brasil e fornecemos os equipamentos para trabalhar de casa ☺

## Requisitos

- Conhecimento sólido em JavaScript moderno (experiência com TypeScript é um bônus);
- Experiência com React (hooks, gerenciamento de estados, chamadas async, websocket, etc);
- Saber escrever testes para React/JS usando alguma biblioteca (testing-library, Enzyme, etc);
- Conhecimento em estilização (CSS, styled-components, etc), conseguindo replicar fielmente um design especificado em alta fidelidade.

## Benefícios

- Cartão multibenefícios com a Flash
- Horário semi-flexível;
- Ginástica laboral (online);
- Plano de saúde;
- Plano odontológico;
- Seguro de vida;
- Parceria com instituições de idiomas;
- Gympass;
- Zenklub; 

## Contratação

CLT 

## Como se candidatar

[Gupy](https://libercapital.gupy.io/jobs/2913496)

## Etapas

- Entrevista com RH
- Entrevista com Tech Lead
- Carta proposta ou feedback construtivo.

## Tempo médio de feedbacks

1-2 dias. 
Sendo o retorno positivo para trabalhar conosco ou construtivo. 

#### Regime
- CLT
- 40h/semanais

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
