### ISSUE TITLE
Pessoa Desenvolvedora Fullstack Sênior – PHP e JS (Remoto) @ Feedz

### ISSUE THREAD

**Issue by larissaaguiar** [frontendbr/vagas#7344]
🚀 A FEEDZ:
Somos uma HRTech e nosso propósito é criar ambientes de trabalho mais felizes, tudo isso através de um software completo de gestão de pessoas humanizado! Por isso, começar pelo nosso próprio ninho é tão importante! Somos Parrots determinados e que se importam uns com os outros, a sede de resultado é latente e o feedback sincero é rotina.

Estamos conquistando coisas incríveis! Crescemos mais de 400% em 2021 e continuamos evoluindo em 2022, tudo isso através de um clima animado, com muito desenvolvimento e respeito para todos! (Se quiser conhecer melhor nosso ninho, voa pra cá: https://www.feedz.com.br/vagas/) 💙 Quer mais? Estamos no modelo totalmente remoto, então você pode fazer parte do nosso ninho no conforto da sua casa!!

Estamos buscando uma pessoa para o cargo de Pessoa Desenvolvedora Fullstack Sênior(PHP e JS) que irá atuar no nosso time de Produto, trabalhando diretamente com nosso gerente de produto em um time de alta performance, desenvolvendo sistemas que impactam mais de 100 mil usuários diretamente.

Aqui na Feedz valorizamos muito a diversidade e queremos Parrots que queiram voar conosco, independente da etnia, gênero, sexualidade, nacionalidade, idade ou deficiência! Quer crescer com a gente? Vem pro ninho 💛

📚 RESPONSABILIDADES E ATIVIDADES:
Desenvolvimento backend com PHP (Com conhecimentos no framework Laravel) ;
Desenvolvimento de frontend com CSS, HTML e JS (Com conhecimento em Vue.JS aplicando nosso design system)
Aplicar boas práticas alinhadas com o time no desenvolvimento (criando códigos coerentes e alinhados ao Clean Code; desenvolvendo com foco em segurança, patterns, automação, etc);
Desenvolver novos módulos na plataforma;
Desenvolvimento e aplicação de testes automatizados;
Fazer a gestão da informação das demandas atualizando o status dos projetos.
🥇 PRÉ-REQUISITOS:
A partir de 7 anos de experiência em desenvolvimento web com produtos digitais(preferencialmente SaaS);
Experiência a partir de 3 anos com PHP;
Experiência a partir de 1 ano com Javascript;
Experiência com sistema de alto volume de dados;
Experiência com testes unitários ou de integração;
Estar trabalhando atualmente com as tecnologias de nossa stack;
Experiência com banco de dados relacional (Atualmente usamos MySQL 8);
Conhecimento em boas práticas de código e vivência com times de tecnologia ágeis!
🎯DIFERENCIAIS:
Conhecimento com Slim, Laravel ou e Vue.JS.
✨ BENEFÍCIOS:
100% Home Office (não iremos voltar ao trabalho presencial!!)
Vale Comida (R$700)
Plano de Saúde Unimed(subsidiado pela Feedz)
Plano odontológico Nacional da Bradesco Dental(subsidiado pela Feedz)
Auxílio Parrot Feliz (R$100/mês de investimento no desenvolvimento pessoal, saúde física ou mental do Parrot)
Auxílio Contas (R$160/mês)
Auxílio Parrot Casamenteiro(R$250 quando Parrots casam)
Auxílio Ninhada(R$250 no nascimento ou adoção de pequenos Parrots)
Happy Bird(day) (um dia de folga no mês de aniversário)
Licença paternidade estendida(21 dias)
Licença maternidade estendida(6 meses)
Descontos nas empresas conveniadas com a ACATE
Ifood Office(voucher para usar dentro do app em alguns eventos internos)
Para você ter um voo com conforto, na Feedz oferecemos um auxílio de R$1.000 para materiais, como mesa e cadeira, para seu home office e enviamos todos os equipamentos eletrônicos necessários!

💰 SALÁRIO 7.500 A 9.500 (CLT)*
*A depender do tempo de experiência

Candidate-se em: https://enliztjob.app.link/7BuaoOyTUsb

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
