### ISSUE TITLE
[Vila Cordeiro, São Paulo, Brazil] Front-end Javascript/VueJS  (Presencial) na INVESTTY CREDIT 

### ISSUE THREAD

**Issue by blankapf** [frontendbr/vagas#7345]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-developer-javascriptvuejs-presencial-162928922?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong><ins>Investty Credit</ins></strong> busca <strong><ins>Front-end Developer Javascript/VueJS</ins></strong>  para compor seu time!</p>
<p>A Investty Credit é uma empresa de tecnologia voltada para Blockchain, oferecemos diversos serviços relacionados ao mercado cripto, como white label para Exchanges/OTCs e desenvolvimento de Token, NFTs e EaaS.</p>
<p>Também oferecemos serviços de compra e venda de criptoativos através da nossa plataforma.</p>
<p><strong>Responsabilidades e atividades:</strong></p>
<ul>
<li>Desenvolvimento de paginas Web responsiva e layouts de mobile com o foco em UX/UI;</li>
<li>Elaboração e manutenção de projetos gráfico-visuais;</li>
<li>Manter-se informado sobre tendências e novas tecnologias do mercado.</li>
</ul>
<p></p>
<p></p>

## INVESTTY CREDIT : 
 <p>A Investty Credit é uma empresa de tecnologia voltada para Blockchain, oferecemos diversos serviços relacionados ao mercado cripto, como white label para Exchanges/OTCs e desenvolvimento de Token, NFTs e EaaS.</p>
<p>Também oferecemos serviços de compra e venda de criptoativos através da nossa plataforma.</p><a href='https://coodesh.com/empresas/investty-credit'>Veja mais no site</a>

 ## Habilidades: 
 - Vue.js 
- Javascript 
- HTML 
- CSS 3 
- Bootstrap
## Local: 
 Vila Cordeiro, São Paulo, Brazil
## Requisitos: 
 - Bons conhecimentos em Vue.JS e Bootstrap; 
- Bons conhecimentos em HTML5/CSS3; 
- Conhecimentos em Javascript (Interação com api e websocket), Ajax, Jquery, Vue e React; 
- Boa relação para trabalho em equipe; 
- Residir em São paulo nas proximidades da Vila cordeiro.
## Diferenciais: 
 - Conhecimentos em React; 
- Conhecimentos com Git; 
- Pacote Adobe (Photoshop/ Illustrator).
## Benefícios: 
 - Bonificação de 1% de participação nos lucros da empresa mensalmente.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Front-end Javascript/VueJS  (Presencial) na INVESTTY CREDIT ](https://coodesh.com/vagas/frontend-developer-javascriptvuejs-presencial-162928922?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
