### ISSUE TITLE
[Remote - London] React Developer (International Opportunity)

### ISSUE THREAD

**Issue by JuliaToldo** [frontendbr/vagas#7348]
## Our Company 

It is a transformative technology company, which supports producers in the events industry to sell directly to their customers. Works with huge names in the entertainment world, from London’s West End to New York and Las Vegas. 

## Job Description 

- Acting as JavaScript Engineer.
- Conducting and participating in meetings 100% in English.
- Develop features and improvements for the TickX platform
- Craft high-quality, performant code that meets best practices for a modern high-scale web environment.
- Identify improvements in the codebase and actively contribute to making it better.
- Confidently ship small features and improvements with minimal guidance and support from other team members. 
- Collaborate with the team on larger projects.
- Support colleagues in solving technical problems of high scope and complexity.
- Implement CRO Experiments (A/B Tests) across our purchase flows

## Local

Remote

## Requirements

**Mandatory:**

- Node (NestJS, Express)
- React
- Typescript

**Secondary (one or more):**

- State management (Redux & Recoil)
- CSS, & CSS-in-JS (SASS, Emotion, Styled JSX)
- Unit testing (Jest, React Testing Library, Enzyme)
- End-to-end testing (Cypress)
- CI (Github Actions)
- Storybook
- Build tools (Webpack, Babel etc.)
- GraphQL

**Differentials**
- You´ve worked with large complex code bases
- You maintain a personal software project or are an active contributor to open source project
- You've worked in an agency setting but are looking to focus toward a product-led company
- You've built and maintained admin areas for non technical colleagues

## Hiring

PJ 

## How to apply

Apply for the vacancy through the following link: https://forms.clickup.com/31110733/f/xndjd-3243/Q5W58WJM2K7NE1DJ08

## Average feedback time

Average return in 7 days via application email or phone
 
#### Alocation

- Remote

#### Hiring

- PJ

#### Level

- Middle Level

**Comment by shirator** [comment]
Não entendi bem, é para qual nível?

**Comment by JuliaToldo** [comment]
Olá Carlos, tudo bem?

A posição é para pleno.

Em sáb., 3 de set. de 2022 às 09:29, Carlos Mesquita <
***@***.***> escreveu:

**Comment by JuliaToldo** [comment]
Olá Carlos, tudo bem?

A vaga é para pleno, caso tenha interesse vamos bater um papo sobre:
 https://calendly.com/julia-toldo/30min
<https://calendly.com/julia-toldo/30min>

Obrigada!

Em sáb., 3 de set. de 2022 às 09:29, Carlos Mesquita <
***@***.***> escreveu:

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
