### ISSUE TITLE
São Paulo- Front End Developer (Node JS) na BRQ Digital Solutions

### ISSUE THREAD

**Issue by ReAnne123** [frontendbr/vagas#735]
Programador Front End Sênior (Node JS)

Grande banco localizado na Faria Lima busca profissional com experiência em Node JS, integração, delivery contínuos, Jenkins ou similares, Scrum. Vivência em times que tenham atendido requisitos não-funcionais de segurança, como OAuth e com o uso de tokens, auditing, logging, pubsub ou outras funcionalidades mais avançadas.
Contratação CLT, salário a combinar mais atrativo pacote de benefícios (VR, Vale alimentação, assistência médica e odontológica, seguro de vida, previdência privada).
Vaga presencial no cliente.
Início em Fevereiro e prazo indeterminado.
Horário comercial.
Local: Faria Lima (próximo a Av, Juscelino Kubitschek)- São Paulo.

Fundada em 1993, a BRQ Digital Solutions é uma das maiores empresas de serviços de TI do país. Conta com 3000 profissionais distribuídos nas filiais de São Paulo, Alphaville, Rio de Janeiro, Curitiba, Recife, Salvador, Brasília, Natal e Nova Iorque. 

Por favor envie um email para Renata - ryokota@brq.com com seu CV anexado - enviar no assunto: Vaga Node JS.

**Comment by raphaklaus** [comment]
Desculpe, mas essa vaga é a mesma da #734 ?

Se não for, poderia especificar melhor no título?

**Comment by LFeh** [comment]
Pois é, vou excluir essa e deixar só a outra.
