### ISSUE TITLE
[São Paulo, SP] Front-end Developer na BEPLIX

### ISSUE THREAD

**Issue by viczampa** [frontendbr/vagas#7350]
> Vaga Hibrida (2X semana)

## Nossa empresa

A BEPLIX nasceu em 2017 focada em criptoativos no atacado, que nada mais é que ativos digitais utilizados para investir, transferir valores ou acessar serviços. Para tornar a cripto realidade na vida das pessoas, no ano de 2022 se transformou para mudar a forma que as pessoas enxergam esse mercado dando a possibilidade que qualquer pessoa invista e utilize suas criptomoedas de forma fácil, rápido e em qualquer lugar, a qualquer momento, tudo na palma da mão em poucos cliques. Muitos ainda não estão nele por conta da complexidade e das barreiras de entrada, por isso, a Beplix veio para revolucionar e descomplicar 

Com a Beplix você vai pagar desde seu cafezinho até um carro com suas criptomoedas direto da sua conta digital e temos o orgulho de contar que nós somos responsáveis pelo primeiro Pix com Bitcoin da história! Você já percebeu que nossa maior missão é democratizar o uso das criptomoedas no mundo e agora queremos que você faça parte com a gente!  

#VemSerBeplix 

## Descrição da vaga

Buscamos Desenvolvedores Front-End React Native que estejam atualizados com as tecnologias que o mercado oferece, uma excelente comunicação para com o time e já tenha passado por processos mais complexos de front-end como testes automatizados (Jest) e tenha base de conhecimento suficiente para implementar a esteira do CICD para o time de front-end.
Vamos trabalhar em cima de uma nova versão do aplicativo, onde todo padrão da arquitetura front end deve ser respeitada e guiada pelo Sênior. Deverá realizar a gestão de branches, organização do Git e versionamento do aplicativo nas stores, além de seguir o processo de CICD completo também farão parte do seu dia a dia e do time. 

## Local

Híbrido, [SP], [São Paulo], [Jd. das Acácias]

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com React e React Native

**Desejáveis:**
- Kotlin
- Swift
- Versionamento de software Github, Jira, Confluenca
- Familiaridade: Utilização do Expo com bare workflow e Containers Docker
- Conhecimento Técnico: Deploy na Apple Store, Google play e Implementar esteira do CICD

## Contratação

PJ 

## Como se candidatar

Por favor envie um email para perla.mendes@beplix.com com seu CV anexado - enviar no assunto: Vaga - Front-End Developer Senior

#### Alocação
- Hibrido (2x semana)
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
