### ISSUE TITLE
[Remoto] Staff Front-end Developer @Alice

### ISSUE THREAD

**Issue by lucascastori** [frontendbr/vagas#7351]
> Vaga Remota durante a pandemia

Somos a Alice, a primeira gestora de saúde do Brasil. 

Acreditamos em um modelo de saúde inovador e colocamos o nosso membro no centro das decisões por meio da tecnologia, empatia, transparência e simplicidade. 

A nossa missão é tornar o mundo mais saudável e este não é um desafio fácil. Revolucionar a saúde no Brasil requer resiliência, energia e inovação. 

Estamos em constante desenvolvimento e incentivamos Pitayas {como chamamos as pessoas do nosso time} a crescerem junto com a gente.

Para isso, buscamos um profissional Staff Frontend Engineer que nos ajude, cada vez mais, a transformar vidas.

## Descrição da vaga

Na Alice, temos como principal objetivo tornar o mundo mais saudável. E para cumprir nossa missão tendo Tecnologia como core, a equipe de Engenharia precisa estar empoderada a ser consistentemente eficaz na entrega de saúde. Essa tarefa envolve a construção de produtos que abstraem os detalhes técnicos (requisitos não funcionais) e permitem o foco no negócio, como Design Systems, Plataformas de Observabilidade e Ferramentas de Teste.

Na Aliança de Foundation, temos como principais desafios:

- Construir ferramentas de desenvolvimento que permitam que nossa Engenharia seja eficiente na construção de produtos;
- Construir sistemas compartilhados que possam abstrair requisitos importantes para nossos membros (como Privacidade e Segurança);
- Construir, acompanhar e evoluir boas práticas de qualidade que possibilitem aos times serem consistentemente eficazes na entrega de saúde;
- Melhorar significamente a estabilidade das aplicações frontend e evoluir nossos principais produtos: Design System, Arquitetura, Testes e Observabilidade;
- Ser o alicerce para a construção de soluções de tecnologia que aceleram a entrega de saúde no mundo.

Como Staff Frontend Engineer na Alice, você terá entre suas responsabilidades

- Liderar o desenvolvimento e manutenção dos nossos produtos internos de frontend que apoiam nossas equipes de Engenharia;
- Trabalhar em estreita colaboração com pessoas Engenheiras de Software, Designers e Product Managers para entender nossos requisitos de sistema e identificar oportunidades de melhorias;
- Construir uma experiência de desenvolvimento estado da arte;
- Ajudar e orientar pessoas Engenheiras de Software com foco em frontend;
- Colaborar consistentemente com decisões de arquitetura e design de soluções;
- Colaborar na construção e aplicação de roadmaps;
- Garantir alto desempenho e alta disponibilidade de todos os sistemas.

## Local

Remoto

## Requisitos

Você poderá agregar bastante ao nosso time se possuir: 

- Experiência sólida em desenvolvimento frontend;
- Experiência sólida como liderança de projetos técnicos;
- Experiência como liderança de projetos cross em frontend (design system, ferramentas de teste, arquitetura, etc.);
- Entendimento profundo da stack de web: HTML5, CSS3, HTTP, cookies, headers, asset loading / caching;
- Experiência com ecossistema modernos de JavaScript: bibliotecas e ferramentas;
- Experiência com ambientes de cloud computing, como AWS;
- Forte experiência prática com as melhores práticas de desenvolvimento (testes, revisão de código, etc);
- Forte senso de compromisso e foco na entrega.

## Benefícios

Caju Flex (VA/VR) - R$ 1260,00 
Plano de saúde
Plano odontológico
Presença parental
Saúde financeira (Leve)
Auxílio creche
Seguro de vida
Gympass
Stock option (Dependendo da senioridade) 

**Diferenciais:**

Férias (aqui você ganha 30 dias de férias úteis, a partir do seu primeiro dia de Alice); 

## Contratação

Quer revolucionar a saúde no Brasil? Vem com a gente!

Se candidata através desse link: https://alice.com.br/vagas?gh_jid=4933521003

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada etapa do processo.

#### Regime
- CLT

 Nível

- Especialista/Staff

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
