### ISSUE TITLE
[Remoto] Front-end Developer ReactJS Sênior na VeganHive

### ISSUE THREAD

**Issue by lemmks** [frontendbr/vagas#7353]
## Nossa empresa

Somos uma empresa dedicada ao veganismo com a missão de construir um mundo mais compassivo e sustentável. A VeganHive empodera os indivíduos e donos de negócios através de uma plataforma social online com o objetivo de acelerar uma transição global para o estilo de vida vegano.
Junte-se a nós e seja parte desta aventura com uma equipe criativa e com visão de futuro. Para os Animais, o Planeta e Todos Nós.  

## Descrição da vaga

**Atividades e Responsabilidades**
- Implementar métodos de design centrados no usuário e/ou design thinking em todo o ciclo de vida de desenvolvimento do produto
- Colaborar com outras pessoas do time implementando novas funcionalidades e incrementando as existentes
- Diagnosticar, identificar problemas e implementar correções
- Manter-se atualizado sobre tecnologias, tendências e oportunidades relevantes

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Proficiência em tecnologias como JavaScript, ReactJS, GraphQL, REST, HTML5, CSS3
- Profunda compreensão em paradigmas de programação orientada a objetos, funcional, baseada em eventos e reativa
- Conhecimento em padrões comuns de gerenciamento de estado do lado do cliente
- Bom conhecimento em Git, Git Flow, Docker e Web DevOps
- Fortes habilidades analíticas, de testes e de depuração
- Inglês intermediário (conversação, leitura e escuta)
- Altamente motivado(a), flexível e talentoso(a)
- Confiança, proatividade e determinação para concluir as tarefas
- Auto-motivação e independência para trabalhar em uma equipe remota
- Excelente comunicação e empatia

**Desejáveis:**
- Compreensão de metodologias de desenvolvimento de software ágil
- Habilidades de design de produto UI/UX centrado no usuário
- Experiência na criação de testes automatizados unitários e de integração
- Experiência de integração com APIs de terceiros
- Entendimento de padrões de segurança e arquitetura de software

## Benefícios
- Cultura de startup que valoriza a compaixão, a sustentabilidade, a inovação e o crescimento pessoal
- Novas potenciais oportunidades de carreira e aprendizagem em tecnologias de ponta
- Ambiente remoto divertido com ambiente amigável e horário flexível

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para career@veganhive.com com seu CV anexado

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 01 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
