### ISSUE TITLE
[Remoto] Front-end Developer Pleno na Proft

### ISSUE THREAD

**Issue by tarikbc** [frontendbr/vagas#7354]
Site: https://proft.sale

# Descrição da Empresa
Aqui na Proft você vai poder revolucionar o varejo com a gente em um dos ambientes mais inovadores do Brasil, com mentorias constantes que possibilitam uma grande experiência para sua carreira. Atualmente precisamos de alguém com conhecimento em React p/ contribuir na aceleração de nosso produto e fazer parte de nossa história!

# Atividades e Responsabilidades
Estamos resolvendo uma treta que os vendedores do varejo passam diariamente. Para isso será fundamental:
- Desenvolver apps React.JS e React Native
- Fazer um código top
- Estar disposto a aprender e partilhar
- Cuidar do filhote quando algum bug surgir em produção

# Requisitos
- Experiência em CSS3 e HTML5 responsivo
- Erros acontecem, mas você deve saber errar rápido e jogar limpo
- Comprar a briga com a gente nas demandas
- Manjar dos paranauês do git
- Ter tido experiência prévia com desenvolvimento em React e trabalhado em equipe
- Ter bom raciocínio lógico
- Preocupação com a qualidade e clareza do código (Lidamos com muito cálculo, por isso é importante ter em foco um código otimizado)
- Enviar "capivara" no conteúdo do e-mail para que possamos identificar que você leu o anúncio até o final
- Ter trabalhado com Redux
- Conhecimentos básicos em matemática (Rola muita regra de 3, porcentagem, projeções, etc)

# Desejável
- Entendimento de complexidade de algoritmos (Big O Notation) e estruturas de dados (Dicionário, tabela hash, árvore, etc.)
- Experiência em frameworks de testes (Jest, Cypress, etc)
- Experiência em Electron
- Typescript
- Pelo menos 1 ano de experiência profissional
- Noção de UI Design

# Etapas do nosso processo seletivo: 
1. Análise de portifólio, currículo e projetos pessoais
2. Entrevista técnica
3. Teste prático
4. Entrevista com o time

# Remuneração
- Salário: a combinar (precisamos antes avaliar seu nível de experiência)
- PJ
- Vaga 100% remota
- Interessados enviar email com CV, pretensão salarial e algum projeto que você queira que a gente veja para rh@proft.sale

# Labels
- 🏢 Remoto
- 👨 Pleno
- ⚖️ PJ

**Comment by brenooliveiranascimento** [comment]
Feito!
