### ISSUE TITLE
[Remoto] FullStack Developer na @Digifarmz

### ISSUE THREAD

**Issue by gabrielarochayy** [frontendbr/vagas#7356]
**FullStack Developer**

A DigiFarmz continua em ampla expansão e está com vaga aberta no time de Engenharia! 🚀
Somos uma startup do agro que auxilia em decisões de fitossanidade da soja, aumentando a produtividade e a assertividade nas decisões da safra. Atualmente, temos atuação comercial e de pesquisa em todas as regiões do Brasil e Paraguai.
Tecnicamente falando utilizamos diversas fontes de dados de pesquisa tradicional, crowdsourcing, satélites, IoT e outros para transformar ciência agronômica e de dados em inteligência para auxiliar na tomada de decisão.

**Quem procuramos?**
Alguém que gosta de aprender e busque se desenvolver em engenharia de verdade! No time de
plataforma, além de evoluir e manter funcionalidades já existentes, temos melhorias de arquitetura, automações e processos para dar robustez aos produtos. Quer fazer parte da revolução no agro? 🌱

**Suas atividades:**
● Planejar e executar projetos que melhorem a engenharia;
● Assumirá total propriedade dos recursos e do código, desde o início das ideias até a
implantação, manutenção e mantê-lo funcionando.
● Você participará de discussões técnicas com a equipe. Você deve estar pronto para
desafiar nossa arquitetura, propor mudanças e, finalmente, implementá-las.
● Implementar testes, automações e monitoramentos;

**Conhecimentos Desejáveis:**
● Princípios SOLID, Clean Code, Design patterns;
● Conhecimento de testes automatizados;
● Conhecimento de Linux;
● Conhecimento de frameworks reativos de UI;
● Já ter trabalhado em times ágeis;
● Ser uma pessoa comunicativa e autodidata;
Nossa stack:
● PHP (Laravel)
● JavaScript (Vue.js)
● Python (Flask)

**Aqui na DigiFarmz você vai encontrar:**
● Muita imersão de conhecimentos e acesso às principais ferramentas e tecnologias
do mercado.
● Participar de sessões de mentoria com especialistas da Google (a DigiFarmz está sendo
acelerada pelo Google for Startups).
● Oportunidade de desenvolver algo único.
● Ambiente descontraído e inspirador.
● Uma filosofia de desenvolvimento, testes e entregas rápidas, onde mais vale uma
solução rodando do que duas no quadro.
● Um time de tecnologia que trabalha totalmente remoto (mas se preferir pode trabalhar
no nosso escritório).
● Day Off no dia do aniversário
● Gympass

Obs: a vaga é remota com possibilidade de híbrido em Porto Alegre.

**Curtiu?** Envia teu currículo para: gabriela.rocha@digifarmz.com 😊

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
