### ISSUE TITLE
[Remoto] Front End Developer na Grupo Selpe

### ISSUE THREAD

**Issue by blankapf** [frontendbr/vagas#7357]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-de-ui-front-end-174412768?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>O <strong>Grupo Selpe</strong> está em busca de um <strong><ins>Frontend Developer</ins></strong> para compor seu time!</p>
<p>A pessoa desenvolvedora atuará global e ativamente em iniciativas que promovam uma transformação digital na empresa e em seus clientes, dando todo o suporte necessário para garantir o correto ciclo de vida dos produtos digitais que são de responsabilidade do Squad que participa.</p>
<p>Será um ambiente de equipe ágil de execução rápida e será capaz de desenvolver e testar soluções para novas funcionalidades, corrigir soluções de ritmo para novas funcionalidades e implementar soluções bem-sucedidas para novas funcionalidades. O software que você desenvolverá será destinado a serviços a serem implantados em uma arquitetura baseada no uso, como as mais recentes técnicas de desenvolvimento de software.</p>

## Grupo Selpe: 
 <p>Há 56 anos conectando pessoas e empresas aos seus propósitos.&nbsp;</p>
<p>Somos o elo entre profissionais e empresas, trabalhando com a atração, seleção consultoria e tecnologia em RH das mais diversas formas.&nbsp;</p><a href='https://coodesh.com/empresas/grupo-selpe'>Veja mais no site</a>

 ## Habilidades: 
 - Angular.js 
- Typescript 
- HTML 
- CSS
## Local: 
 100% Remoto
## Requisitos: 
 - Conhecimento em tecnologias frontend (Angular.js, CSS, HTML, Typescript); 
- Conhecimento em Teste de unidade; 
- API REST; 
- Habilidades de depuração; 
- Processo de desenvolvimento ágil; 
- Capacidade de entender projetos e requisitos de UX para convertê-los em requisitos técnicos; 
- Inglês avançado ou fluente; 
- Ensino Superior Completo.
## Diferenciais: 
 - ElectronJS; 
- AWS; 
- SonarQube; 
- NPM / webpack.
## Benefícios: 
 - Vale Refeição; 
- Previdência Privada; 
- Seguro de Vida; 
- Plano de Saúde coparticipativo; 
- PLR.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Front End Developer na Grupo Selpe](https://coodesh.com/vagas/desenvolvedor-de-ui-front-end-174412768?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
