### ISSUE TITLE
[SP] Desenvolvedor Full Stack Node JS @digi

### ISSUE THREAD

**Issue by logeraldi** [frontendbr/vagas#7358]
Vaga Desenvolvedor Fullstack Node.Js - Sênior - REMOTO

A Digi é uma das principais e mais relevantes fornecedoras de marketing de incentivo do País. Oferecemos plataformas tecnológicas e consultoria estratégica para campanhas de Loyalty e Incentivo.

Estamos recrutando um Desenvolvedor Full stack sênior para desenvolver aplicações com qualidade e no prazo estipulado, trazendo sempre soluções inovadoras e diferenciadas que elevem cada vez mais o nível das entregas da Digi.

⭐ Esperamos que você:

- Seja comprometido(a);

- Curioso(a) ao aprendizado contínuo;

- Gostar de ser desafiado(a);

- Seja automotivado(a) e inteligência emocional;

- Tenha uma ótima comunicação e facilidade para negociação.

As principais tecnologias usadas são: PHP Laravel, NodeJS, NestJs, Typescript, VueJs, MySql.

🎓 Venha preparado:

- Ensino superior completo em análises de sistemas ou áreas relacionadas;
- Conhecimentos em Orientação a Objetos;
- Conhecimento de Design Patterns Gof;
- Desenvolver sistemas seguindo preceitos de Arquitetura e Códigos Limpos;
- Ter experiência com: Javascript/Typescript, VueJs, Node;
- Ter proficiência em desenvolvimento de software tanto em backend, quanto em frontend;
- Ter algum conhecimento em ferramentas de mensageira;
- Ter algum conhecimento em algumas das plataformas de Cloud a seguir: Azure, AWS, Google Cloud;
- Ter algum conhecimento em CI/CD;
- Ter algum conhecimento em MySql;
- Experiência de trabalho em times ágeis usando os frameworks Scrum ou Kanban;
 
Sua atuação será desde desenvolvimento de novos projetos até manutenção em projetos já existentes, junto a uma equipe completa de todos os níveis e interagindo com CTO e time.

Benefícios:

✔️Auxílio Bem-estar Zenklub (Aqui valorizamos o cuidado com você)
✔️Day Off aniversário (bora comemorar?)
✔️Auxílio Home Office (R$ 200,00 mensais)
✔️Auxílio Capacitação Revelo Up (R$ 600,00 anual)
✔️Clube Digi (Plataforma de descontos em farmácias, supermercados e lojas) 
✔️Recesso Remunerado (30 dias)
✔️Licença Maternidade  
✔️Licença Paternidade 
 
Início Previsto: combinar
Regime: PJ
Faixa salarial: 10 a 12k
Local: 🌍Aqui você trabalha onde quiser, nossa cultura é Remoto First :-) 
Interessados enviar CV: lorraine@grupodigi.com.br 

#InspiramosSuperação

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
