### ISSUE TITLE
[Remoto] Front-end Developer | Vem pra @Datum💜

### ISSUE THREAD

**Issue by julianakraemer** [frontendbr/vagas#7359]
## Nossa empresa

A Datum é uma empresa GPTW (Great Place to Work) pelo segundo ano seguido e nossa principal proposta é ativar o protagonismo, por isso investimos mais pesado no desenvolvimento de nossos colaboradores.

## Descrição da vaga

Oportunidade para atuar como desenvolvedor Front-end em uma das maiores empresas de SaaS do país!

## Local

100% remoto

## Requisitos

Você pode se conectar com a oportunidade se possuir experiência em:

React.
 Google Cloud Platform.
Arquitetura de projetos
Diferencial: entendimento de Ruby on Rails, em função do ambiente ser todo desenvolvido nessa linguagem

## Benefícios

Vale transporte (se necessário)
Vale refeição/alimentação
Auxílio Home Office
Gympass
Plano de saúde
Plano odontológico
Seguro de vida
Cíngulo (saúde mental)
Assessoria financeira, jurídica e psicológica para o funcionário

Diferenciais:
Protagonistas (game de incentivo à carreira do colaborador)
Datum Academy (programa de capacitação e treinamentos trabalhistas
English Class
Ginásticaal
Rock Leader (programa de formação de liderança)
+Felicidade (iniciativa a felicidade do colaborador)

## Contratação

PJ a combinar

## Como se candidatar

 Por favor envie um e-mail para JULIANA.KRAEMER@DATUM.INF.BR

**Comment by willianbatist** [comment]
Mandei email.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
