### ISSUE TITLE
[Remoto] Frontend Developer na Nickelpay

### ISSUE THREAD

**Issue by blankapf** [frontendbr/vagas#7361]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-developer-134243247?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>Nickelpay</strong> busca <strong><ins>Frontend Developer</ins></strong> para compor seu time!</p>
<p>Somos uma fintech focada em fazer diferente. Trazer facilidade, conforto e confiança no processo de gestão de contas é nosso dever. A Nickelpay tem uma proposta forte que atrela Contas Digitais, Gestão Centralizada e BPO Financeiro.&nbsp;</p>
<p></p>

## Nickelpay: 
 <p>Somos uma fintech focada em fazer diferente. Trazer facilidade, conforto e confiança no processo de gestão de contas é nosso dever. A Nickelpay tem uma proposta forte que atrela Contas Digitais, Gestão Centralizada e BPO Financeiro.&nbsp;</p>
<p>Código próprio, em constante desenvolvimento, queremos pessoas que queiram fazer a diferença, pois temos liberdade para criar, desenvolver e implementar.</p><a href='https://coodesh.com/empresas/nickelpay'>Veja mais no site</a>

 ## Habilidades: 
 - React.js 
- GraphQL 
- JIRA 
- SCRUM
## Local: 
 100% Remoto
## Requisitos: 
 - Sólida Experiência com React.JS; 
- Desenho e construção de APIs RestFUL ou GraphQL; 
- Experiência utilização de ferramentas de versionamento: GIT; 
- Experiência na utilização de ferramentas de CI/CD; 
- Conhecimento em alguma ferramenta de gestão de tarefas: Jira, Trello, TFS; 
- Experiência em alguma metodologia ágil: Scrum ou Kanban; 
- Conhecimento em design patterns, refactoring e testes unitários; 
- Experiência na manutenção de códigos legados; 
- Ter participado de projetos de Frontend e Integração com plataformas (APIs).
## Diferenciais: 
 - Conhecimento em Material UI; 
- Conhecimento em MuiDatatables; 
- Conhecimento Redux e Saga; 
- Conhecimento Styled Components; 
- Conhecimento em Cypress.
## Benefícios: 
 - 20 dias de recesso remunerado (após 12 meses); 
- 5 dias entre natal e ano novo; 
- 150 reais de ajuda de internet; 
- Day off aniversário; 
- Ajuda de custo com cursos na área e de Inglês; 
- Incentivo à liderança e desenvolvimento de carreira.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Developer na Nickelpay](https://coodesh.com/vagas/frontend-developer-134243247?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by shirator** [comment]
Vaga front end mas pede Desenho e construção de APIs RestFUL ou GraphQL?

**Comment by Thiagoow** [comment]
Aquele clássico problema de "Essa vaga de Front tá meio FullStack"

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
