### ISSUE TITLE
[REMOTO] Senior React Developer na Builders!

### ISSUE THREAD

**Issue by RaissaBaltazar** [frontendbr/vagas#7363]
**Conhece o Movimento Builders?** 🤟

Você pode pensar que não nos conhece, mas provavelmente já teve contato com uma das nossas diversas soluções criadas especialmente para grandes clientes nacionais de diferentes segmentos. Essas soluções são criadas pelas mãos de pessoas empreendedoras, apaixonadas por inovação que geram valor impactando pessoas e negócios. 

Ao ingressar na Builders, você fará parte de um movimento que idealiza, cocria e conecta pessoas. Desfrutando de um ambiente colaborativo que propicia oportunidade de crescimento exponencial. Se você curte desafios, aqui é o seu lugar! 

**Como será seu dia-a-dia?** 💻

Como React Web Developer na Builders você irá trabalhar em projetos de desenvolvimento de produtos digitais junto com grandes empresas, apoiado por uma equipe de tecnologia, designers e gestores. Irá atuar com desenvolvimento React Native de acordo com arquitetura e boas práticas, avaliação de viabilidade técnica de uma proposta de solução (UI/UX), criação de bibliotecas de códigos reutilizáveis, garantir a documentação de informações do projeto, e fazer acontecer ideias que impactam diariamente milhares de pessoas.

**Para cumprir esse desafio, você precisa dominar:** 
- Fluência em TypeScript;
- React (Redux/Mobx);
- APIs REST;
- Trabalhar com diferentes dimensões de dispositivos (tablet, celular, etc);
- Versionamento de código com Git;
- Conhecimento em arquitetura de software;
- Metodologias ágeis.

**Será um diferencial se você tiver também:** 
- Conhecimento em Firebase (Analytics, Crashlytics, etc).

**O que nós oferecemos?**
- Atuação 100% remota;
- Parceria com coworking em São Paulo;
- Webnars semanais para expandir ainda mais seu conhecimento;
- Participar de um processo único de geração de valor;
- Contribuir na criação de métodos disruptivos;
- Possibilidade de profit share de novos negócios.

[**O momento para se tornar Builder é agora!**](https://bit.ly/3Sf7C13) 🚀

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
