### ISSUE TITLE
[Remoto] React Developer na Augment

### ISSUE THREAD

**Issue by darrendahl** [frontendbr/vagas#7369]
Descrição da vaga
Este trabalho requer inglês, salário muito competitivo

Title: Engineer – Software Development
Frontend Engineer (React)

🧑‍💻 You will:
Build out new products, features, and integrations
Help with the design and implementation of our user interface
Architect robust systems end-to-end to support trading of $100Ms
Own all product deliverables
Contribute to the culture of our team and help with hiring
🧑‍🔬 You'd fit in well if you:
Enjoy building awesome products and engineering infrastructure from the ground up
Have strong CS fundamentals in data structures, algorithms, and systems design
Write clean & robust code with a strong testing discipline
Are comfortable with ambiguity and uncertainty!
👨‍🔧 Skills we love:
Built an entire website/app/product from the ground up
A good eye for design and UX
Written tens of thousands of lines of code in a modern language (Go, React.js, Python, Scala)
Familiar with the public cloud (AWS, GCP)
Solid understanding of relational databases (MySQL)
Interested in fintech & marketplaces
🏭 Our engineering stack & processes:
Frontend: React.js
Backend: Go, Bash, Python
Infrastructure: AWS, Lambda, S3, CloudFront, MySQL
Tons of integrations like SendGrid, Twilio, and 3rd-party data providers
Code reviews
Continuous integration & automated deployment (multiple times per day)
Benefits:
Competitive salary
Equity in an early-stage high growth company
Medical, dental, & vision insurance
Bring your dog to work! Our mascot is a Golden Retriever named Tucker.
About Us
Augment is a remote-first team with an HQ in Austin, TX. We are a small group... nimble & flexible. To stay organized, we have daily stand-ups but minimal process, and believe in doing what it takes to get things done.

The team is "intense but chill", and know how to have a good time. Every quarter, we'll fly you out to Austin to jam with the team. Twice yearly, we'll do a week-long offsite to just enjoy!

Augment aims to bring transparency and liquidity to a space that hasn't seen innovation since the 90s -- we want to be the first and the last mover.

Local
Trabalho de contrato remoto

Como se candidatar
Por favor envie um email para [darren@bluedahl.tech](mailto:darren@bluedahl.tech) com seu CV anexado - enviar no assunto: Vaga ReactJS

Labels
Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
