### ISSUE TITLE
[Remoto] Frontend Developer (Sênior) na OZ Technology

### ISSUE THREAD

**Issue by blankapf** [frontendbr/vagas#7374]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-developer-170502262?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>OZ Technology </strong>busca <strong><ins>Frontend Developer</ins></strong><strong> </strong>para compor seu time!</p>
<p>A OZ Technology garante eficiência, controle da informação e aumento da lucratividade, facilitando a vida de empresas em diversos setores com profissionalismo técnico, know-how e pronto atendimento em qualquer horário. Nossa crença enxerga o crescimento e o avanço como consequência de um ambiente integrado, acessível e open-source, visando transformar isso em realidade para todos.</p>
<p></p>
<p><strong>Atividades:</strong></p>
<p>Como Front End Developer, você irá reportar diretamente para o Chief Architect Office, será responsável pelo o papel de desenvolvedor front-end, assumindo a frente do desenvolvimento, manutenção e criação de layouts para desenvolvimento dos nossos sistemas web e aplicativos.</p>
<p></p>
<p><strong>Atividades e responsabilidades:</strong></p>
<ul>
<li>Espírito de liderança e vontade de ensinar e ajudar os demais desenvolvedores;</li>
<li>Análise e levantamento de requisitos funcionais;</li>
<li>Ser protagonista no desenvolvimento do front-end web e aplicativos, trabalhando em conjunto com o time de design e tecnologia;</li>
<li>Definir práticas de desenvolvimento de front-end, linguagem, sugerir novas arquiteturas ou melhorias pontuais;</li>
<li>Em conjunto com UX, desenvolvedor de aplicativos e back-end definir e executar o melhor fluxo para desenvolvimento de novas tarefas.</li>
</ul>

## OZ Technology: 
 <p>A OZ Technology garante eficiência, controle da informação e aumento da lucratividade, facilitando a vida de empresas em diversos setores com profissionalismo técnico, know-how e pronto atendimento em qualquer horário. Desde sua concepção, a empresa cresceu de forma constante, baseando-se em decisões voltadas à sua missão central: a satisfação total dos nossos clientes, apresentando sempre soluções de alta tecnologia, última geração, baixo custo e que colaborem para o desenvolvimento tecnológico em âmbito nacional e mundial. Nossa crença enxerga o crescimento e o avanço como consequência de um ambiente integrado, acessível e open-source, visando transformar isso em realidade para todos.</p>
</p>

 ## Habilidades: 
 - Vue.js 
- Angular 
- Javascript
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência sólida em HTML, CSS e Javascript; 
- Experiência comprovada em Vue ou AngularJS e bootstrap; 
- Conhecimentos em APIs REST; 
- Experiência pré processadores como LESS, SASS; 
- Conhecimento em GIT; 
- Experiência em FIGMA; 
- Experiência criação de layouts para aplicativos.
## Diferenciais: 
 - Conhecimento em GIT.
## Benefícios: 
 - Welcome Kit + Homeoffice Kit; 
- Gympass (academia); 
- Wellness Coach (mente, corpo e sono); 
- Cíngulo (saúde mental); 
- Assistência Médica; 
- Assistência Odontológica; 
- Seguro de Vida; 
- Custeio de capacitações e certificações (conforme política interna).
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Developer (Sênior) na OZ Technology](https://coodesh.com/vagas/frontend-developer-170502262?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
