### ISSUE TITLE
[Remoto] Front-end Developer na nexmuv

### ISSUE THREAD

**Issue by HelenNexmuv** [frontendbr/vagas#7376]
## nexmuv 
Somos uma empresa de tecnologia que aplica inovação em tudo aquilo que entrega. Existimos para ajudar nossos clientes a se adaptarem a um mundo em constante transformação

## Front-end Developer 

Projeto voltado a inovação digital; desenvolvimento de novos sistemas. 

## Local
100% remoto

## Requisitos

**Obrigatórios:**
- Experiência com React, Nextjs, AngularJS, Javascript Vanilla, HTML5 e CSS3; 
- Experiência com controle de versão (Git); 
- Experiência com testes unitários e interface; 
- Experiência com CI e CD; 
- Experiência com QA - TDD, BDD

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para helen.matos@nexmuv.com.br com seu CV anexado - enviar no assunto: Vaga front end 

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by rafae2k** [comment]
e onde ta o front dessa vaga?

**Comment by HelenNexmuv** [comment]
oie. inclui o perfil da vaga errada, desculpe-me 

perfil atualizado.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
