### ISSUE TITLE
[REMOTO] Front-end Developer na NAVE.rs

### ISSUE THREAD

**Issue by RenataRamiress** [frontendbr/vagas#7378]
> Vaga Remota 

## Nossa empresa

A [Nave.rs](http://nave.rs/) está procurando uma pessoa que tenha experiência na área de desenvolvimento web Front-end React, além de possuir experiência com clientes e projetos. Como pessoa desenvolvedora para a área de Front-end, você irá utilizar principalmente React. Na empresa trabalhamos utilizando metodologias ágeis, logo sua rotina de trabalho será pautada por meio de cerimônias como planning, daily e retro. O seu dia-a-dia de trabalho irá basear-se nas cerimônias e no projeto que você irá entrar.

## Descrição da vaga

Procuramos uma pessoa que seja comprometida com sua evolução, que tenha ideias inovadoras, tenha proatividade e pense fora da caixa. É importante você goste de se comunicar e trabalhar em equipe, já que aqui temos um ambiente super colaborativo. Ao mesmo tempo, valorizamos que cada membro do time seja autônomo para gerir suas demandas e assumir responsabilidades.

## Local

REMOTO

## Requisitos

**Obrigatórios:**
- Experiência profissional de, no mínimo, dois anos na área com projetos React;
- Experiência com Styled Components ou qualquer outra biblioteca de estilos, além de conhecimento avançado de css;
- Conhecimento do lifecycle do react, bem como boas práticas na utilização de hooks;
- Entendimento de API's e padrão REST, no que tange integrações com front-end;
- Experiência na construção de formulários utilizando bibliotecas de gestão de estado e validações. Ex: react-hook-form, formik, etc;
- Conhecimento de html e do funcionamento do DOM;

**Diferenciais:**
- Desejável experiência com frameworks server-side, como nextjs;
- Desejável experiência com testes unitários e e2e;
- Desejável experiência com clientes.

## Benefícios

Assistências médica e odontológica;
Auxilio psicológico;
Vale Refeição e/ou Vale Alimentação;
Aulas de inglês;
Auxilio Educação (acesso a plataformas de cursos);
Home office.

**Diferenciais:**
- Hierarquia horizontal 
- Horário flexível
- Plano de carreira  

## Contratação

CLT + Benefícios 

## Como se candidatar

Inscreva-se através do link: https://nave-team.gupy.io/jobs/3017507

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.
E-mail para contato em caso de não haver resposta: renata.silva@nave.rs

#### Alocação

- Remoto

#### Regime
- CLT

#### Nível

- Pleno
- Sênior

**Comment by abiliobjr** [comment]
Vaga encerrada @felipefialho

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
