### ISSUE TITLE
[São Paulo] Front-End Developer Pleno no Neon

### ISSUE THREAD

**Issue by keitoliveira** [frontendbr/vagas#738]
## Descrição da vaga
Você procurou durante toda a sua vida digital aquela oportunidade de participar de um grupo de pessoas selecionadas entre os mais f*d@s com o objetivo comum de criar o incrível?

Deverá ser capaz de assimilar a identidade visual e a proposta de experiência de uso do Neon e traduzir isso em novas experiências digitais. Ter um olho biônico para pixel perfect será muito apreciado. 

Buscamos alguém com muita vontade de criar o diferente, inusitado, mas sempre ligado nas tendências de design, ux e front.

Se você se sente à vontade em trabalhar em equipe, dando e recebendo feedbacks, é inquieto com a mesmice e seu combustível diário é criar algo novo, o Neon é onde você vai querer estar.

## Local
Escritório, ao lado da futura estação Oscar Freire em Pinheiros - São Paulo

## Contratação
CLT

## Benefícios
Os benefícios são flexíveis, você pode escolher os que mais se enquadram com suas necessidades. Alguns deles são:

- Seguro de vida (obrigatório)
- Plano odontológico
- Plano de saúde
- VT ou estacionamento
- VR ou VA
- Gympass
- Futebol
- Manicure
- Massagem
- Vale Cultura

## Requisitos
**Obrigatórios:**

- Sólidos conhecimentos em **HTML**; Semântica e acessibilidade; Template engine
- Sólidos conhecimentos em **CSS** e pre-processador **SASS**; Componentização, boas práticas e confortável no desenvolvimento com metodologias **BEM** e **Atomic Design**; **Foundation**
- Conhecimentos em **JavaScript**; **ES6**; Lógica de programação, design pattern, componentização
- Sólidos conhecimentos em versionamento com **Git**
- **Inglês** intermediário

**Desejáveis:**
- Conhecimento em **Razor**

**Diferenciais:**
- Conhecimento em **C#**

## Sobre a empresa
Saiba mais sobre o [Banco Neon](http://banconeon.com.br/).

## Como se candidatar
Curtiu? Se cadastre através da nossa página no [Kenoby](https://jobs.kenoby.com/neon/job/front-end-pleno/5a3aa929f96f9111e9b760c1) e boa sorte 🎇

**Comment by LFeh** [comment]
A Kenoby está do nosso lado aqui no Cubo, hehe.

**Comment by keitoliveira** [comment]
@LFeh a vaga foi preenchida, pode fechar 🔝 

Obrigada a galera que entrou em contato conosco  ❤️
