### ISSUE TITLE
[Vitória] Front-end Developer na Code n'App 

### ISSUE THREAD

**Issue by Inglidbarbosa** [frontendbr/vagas#7380]
> Vaga Remota durante a pandemia

## Nossa empresa

Já imaginou trabalhar em um lugar onde você possa ser você mesmo e se desenvolver enquanto participa de grandes projetos? Tudo isso com uma equipe de feras e um ambiente de trabalho divertido e estimulante?
Somos a Code n' App!
Uma desenvolvedora de sistemas e soluções para diversos setores com atuação em todo Brasil.
Ajudamos na transformação digital de negócios levando inovação e tecnologia para melhorar produtos e processos focados em resultados.

## Descrição da vaga

A pessoa desenvolvedora Front End participará de um projeto que desenvolverá jogos utilizando HTML5, javaScript ou Typescript.

## Local

Avenida Nossa Senhora da Penha, Vitória - ES, 29018-080, Brasil

## Requisitos

HTML5, JavaScript/Typescript e CSS
Desenvolvimento de jogos ou aplicações da Web, de preferência usando Typescript ou JavaScript; 
Desenvolvimento orientado a objeto; 
Inglês avançado (conversação).

Será um diferencial se você entender sobre: 

Padrões de projeto e arquitetura; 
Testes unitários para garantir a qualidade do software desenvolvido; 
Ferramentas de depuração de código; 
A importância de manter um relacionamento colaborativo para desenvolvimento e apoio da equipe. 
Informações adicionais: 

## Benefícios

Nosso ambiente foi preparado para que você que gosta de compartilhar experiências, ama resultados e adora se divertir com os desafios do dia a dia. E mais, pensamos em como melhorar tudo isso com um pacote de benefícios:

Horário flexível e possibilidade de home office ou modelo híbrido;
No dress-code;
Gympass;
Celebração de datas importantes (Seu aniversário, aniversário Code n’ App, etc.)

## Contratação

PJ a combinar

## Como se candidatar

https://codenapp.gupy.io/jobs/2918985

Somos uma empresa que enviamos feedback

#### Alocação

- Remoto

#### Regime

- PJ

#### Nível

- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
