### ISSUE TITLE
[Lisboa ou Porto - Portugal] Frontend Developer @Integer Consulting

### ISSUE THREAD

**Issue by brunoalexandrecarvalho** [frontendbr/vagas#7381]
# Estás à procura de projetos internacionais na área de TI? Se o teu objetivo é ser bem-sucedido na Europa, temos novidades para ti!

## Frontend Developer

- Licenciatura e/ou Mestrado em Engenharia Informática ou similar;

- +4 anos de experiência profissional em desenvolvimento;

- Experiência com Angular e/ou React;

- Experiência em HTML, CSS, JavaScript e TypeScript;

- Familiaridade com metodologias Agile;

- Inglês fluente (obrigatório).

Se tens o amazINg tech talent pretendido e queres fazer parte da equipa INTEGER, responde a este anúncio com o teu CV atualizado para bruno.carvalho@integer.pt

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
