### ISSUE TITLE
[Remoto] Frontend JavaScript Developer na Coodesh

### ISSUE THREAD

**Issue by blankapf** [frontendbr/vagas#7383]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-javascript-developer-183715524?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>Peerdustry</strong> busca<strong> </strong><strong><ins>Frontend JavaScript</ins></strong> para compor seu time!</p>
<p>A Peerdustry traz ao mercado o conceito de USINAGEM CONECTADA! Em uma ponta temos os fabricantes de peças usinadas, que por meio da Peer conseguem capturar novos trabalhos e assim utilizar seu maquinário ocioso para atender clientes.</p>
<p><strong>Responsabilidades: </strong></p>
<ul>
<li>Trabalhar diretamente com a equipe de Designer;</li>
<li>Pequenas coisas no Framework Ember.js.</li>
</ul>

## Peerdustry: 
 <p>A Peerdustry traz ao mercado o conceito de USINAGEM CONECTADA! Em uma ponta temos os fabricantes de peças usinadas, que por meio da Peer conseguem capturar novos trabalhos e assim utilizar seu maquinário ocioso para atender clientes.</p>
<p>💡🖥️ No meio está a Peerdustry, para integrar a cadeia de fornecimento de usinagem. Através de nossa plataforma digital nós integramos as demandas de peças usinadas das duas pontas. Unimos empresas com capacidade produtiva com outras que apresentam demanda por fabricação.</p><a href='https://coodesh.com/empresas/peerdustry'>Veja mais no site</a>

 ## Habilidades: 
 - Ember.js 
- Javascript 
-  UX/UI 
- Programação Orientada a Objetos (POO)
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência com Programação Orientada a Objetos; 
- Experiência com JavaScript e pelo menos um de seus frameworks (Ember, React, Vue, etc.); 
- Noções de UI/UX.
## Diferenciais: 
 - Ser de São Paulo, para eventuais encontros.
## Benefícios: 
 - Plano de saúde (Unimed); 
- Vale Refeição; 
- Auxílio home-office no primeiro mês.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend JavaScript Developer na Peerdustry](https://coodesh.com/vagas/frontend-javascript-developer-183715524?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
