### ISSUE TITLE
[Remote] Senior Front-end Developer na Pods Finance

### ISSUE THREAD

**Issue by ggviana** [frontendbr/vagas#7387]
## About Pods
Pods is creating the future of one-click-deposit investment. Financial infrastructure will radically change with DeFi, and you can be part of that change with us.

Pods is backed by Boost VC, Framework Ventures, IOSG, Republic, Tomahawk, and more.
We are a team of 5, remote first.

Although the role is remote-friendly, it is preferred that you are located and working within the GMT-5 / GMT+4 time zones for coordination purposes.

## About the Role
You will play an important role in the future of finance. Some new concepts are starting to become a pattern. At Pods, we highly value the user experience while interacting with our app and we are at the frontier of creating new concepts regarding financial applications.

## What we are looking for
We are looking for a defi-native person to lead the apps at Pods. This person will own all current and future apps created by Pods.
We value a lot of code readability, best practices, and good knowledge about state management. This means that it should be easy to follow and understand the state of the Dapp.

## Qualifications

- DeFi passion
- Like to work in a dynamic environment and is ready to hustle
- Ethers.js
- React / Next.js / Typescript
- BSc/BA in Computer Science, Engineering, or a related field is preferred
- Good knowledge about application state management (Context / Redux)
- D3.js or other graph libraries

## What you'll do
Develop the app for Pods future products.
Be able to help also with integrations between projects.

## Nice to have

- Contribution to open source code is a plus
- Basic knowledge of UI / UX tooling like Figma

## Benefits

- Take vacations when you need it
- International travel with the team to attend DeFi events
- Flexible work schedule
- Competitive global salary

## How to apply

Email [jobs+frontendbr@pods.finance](mailto:jobs+frontendbr@pods.finance?subject=Senior%20Front-end%20Developer) with subject Senior Front-end Developer with your CV attached.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
