### ISSUE TITLE
[Alphaville, SP - HÍBRIDO] Analista de Negócios Sênior | DEAL TECHNOLOGIES

### ISSUE THREAD

**Issue by ThauanySilva7** [frontendbr/vagas#7390]
**Sobre Nós**
Somos a Deal, estamos no mercado desde 2004 e somos referência em Inteligência de Dados e Transformação Digital, desde a estratégia até a execução (end-to-end).
Aqui, cada Dealmaker tem liberdade para:
• Ser quem é, numa cultura que valoriza as pessoas pela sua essência;
• Trabalhar de onde quiser, porque o Anywhere Office é uma realidade por aqui;
• Ser protagonista da sua carreira e escolher aonde quer chegar profissionalmente!

**Pré-requisitos:**
•	Experiência em mercado financeiro. 
•	Experiência em sistemas de pagamentos
•	Conhecimento em integrações de sistemas (via mensageria, troca de arquivos, APIs) 
•	Sólidos conhecimentos em APIs (especificações, ferramentas de teste, elaboração e entendimento de Swagger) 
•	Facilidade em entender e elaborar diagramas de integração de sistemas 
•	Experiência em testes de sistemas (integração, testes de usuários) 
•	Inglês fluente 
•	Excelente comunicação oral e escrita 
•	Perfil Autodidata, com atitude positiva e curiosa, atento a detalhes, excelente senso de organização 
 
 
**Diferencial:**
•	Experiência em segurança em APIs (uso de OAuth, Tokens, Certificados, TLS e mTLS) 
•	Experiência em projetos de pagamentos envolvendo TEDs, DOCs, Boletos, Transferências, PIX 
•	Experiência em projetos waterfall e Scrum

**Local**
Alphaville, SP - HÍBRIDO

**O que oferecemos:**
• Benefícios personalizados
• Parceria com o SESC
• Capacitação e desenvolvimento pelo nosso Núcleo de Inovação Deal
• Programa de mobilidade interna (Deal Moving)
• E muito mais!

**Como se candidatar**
Por favor, envie um e-mail para vemser@deal.com.br
Com seu CV anexado – enviar no assunto: Analista de Negócios Sênior 

**Labels**

Alocação
•	Híbrido

Regime
•	CLT
 
Nível
•	Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
