### ISSUE TITLE
[Remoto] DESENVOLVEDOR FRONTEND SENIOR @Dacxi

### ISSUE THREAD

**Issue by Soonas** [frontendbr/vagas#7391]
## Nossa empresa

A [Dacxi](https://dacxi.com/home) é uma empresa que atua no mercado de cripto-economia e tokenização de ativos.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Javascript
- Vue
- Inglês Intermediário;
- Experiência com ferramentas de versionamento de código (GIT,...);

**Desejáveis:**
-  Conhecimento em blockchain e hyperledger;
- PHP/Laravel
- Docker

**Diferenciais:**
- Tailwind

## Benefícios
- Participar do mercado de tecnologia mais promissor: cripto-economia.
- Aulas de inglês.

## Contratação

Contratação PJ:
Senior: +7 mil (Começa em 7 mil e vai além; Dependendo exclusivamente do conhecimento do desenvolvedor).

## Como se candidatar

Preencher o formulário: https://forms.gle/JE9FZM79q2rcsYcf6

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato caso precise tirar dúvidas: luana@dacxi.com

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
