### ISSUE TITLE
[Remoto] Front-end Developer na Truppe!

### ISSUE THREAD

**Issue by Camila-Goms** [frontendbr/vagas#7392]
**A empresa:**

A [Truppe!](https://truppe.team/) é uma empresa de consultoria de tecnologia com foco em desenvolver e aprimorar talentos referência em recrutamento, seleção e alocação de profissionais de TI. Criada há 3 anos, está em fase de desenvolvimento e crescimento, expandindo seu portfólio de produtos e serviços, trabalhando também com transformação e aceleração digital. 

Sua missão é conectar os melhores profissionais às melhores oportunidades, proporcionando seu crescimento na carreira.

**Descrição da vaga:**

Buscamos uma Pessoa Desenvolvedora Front-end para atuar em uma grande empresa do ramo de tecnologia e logística. 

**Responsabilidades e Atribuições:**

• Propor melhorias no desenvolvimento de novos projetos pensando em 
modelo mobile first;
• Trabalhar com foco em SEO na construção de Portais e aplicações web 
no geral;
• Sustentação de sistemas / aplicações atuais e melhorias;
• Participar de reuniões de novos projetos, para entendimento e 
documentação técnica das necessidades, alinhada à arquitetura proposta 
de frontend;
• Participar das cerimônias ágeis de desenvolvimento, daily, planning, 
review;
• Respeitar a priorização no desenvolvimento de projetos, mudanças e 
manutenções.

**Nível**

PLENO

**Local:**

100% Remoto.

**Requisitos:**

• Nível superior completo em Ciências da Computação ou áreas correlatas
• Mínimo de 2 anos de experiência com desenvolvimento e manutenção de 
sistemas;
• HTML;
• CSS;
• API Rest;
• Angular 6+;
• Javascript;
• Jquery;
• Desenvolvimento de layouts responsivos;
• UX/UI;

**Contratação**

CLT - Pretensão Salarial a combinar

**Como se candidatar**

Por favor, envie um email para **camila.gomes@truppe.team** com seu CV atualizado anexado, link do perfil do Linkedin (se utilizar) e pretensão salarial CLT no corpo do email.

Enviar no assunto: **Vaga Frontend Angular - Pleno**

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
