### ISSUE TITLE
[Budapest, Hungary] React Developer (Pleno) na Coodesh

### ISSUE THREAD

**Issue by blankapf** [frontendbr/vagas#7397]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/junior-react-engineer-135155671?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>Short overview of the company:</strong></p>
<p>Our client now connects over 100,000 industry professionals in all the major studios and leading content makers around the world. Over 5000 film and TV projects have used the system to collaborate more effectively. Making the work better, together.</p>
<p>It is an entertainment technology company that partners with clients to enable creative flow across the production life cycle with a trusted suite of secure communication and content management solutions.</p>
<p>They design, develop, and manufacture software and hardware solutions for studios, broadcasters, and film and video production companies.</p>
<p>This company are passionate about inclusion, we want all employees to feel encouraged to be themselves and believe that this inspires creativity and innovation. It is an equal opportunities employer with a focus on inclusivity and equality for all.</p>
<p></p>
<p><strong>What the job is about:﻿﻿</strong></p>
<p>As a Junior/Middle React Engineer, you will be working on the company applications, which power secure collaboration across the television, film and streaming media industries. You will be responsible for iteratively designing and building product features in close collaboration with other Software Engineers, Designers, and Product Managers. You will provide attention to detail and build-in quality every step of the way. You will contribute to the overall application architecture.</p>
<p></p>
<p>&nbsp;<strong>Duties and responsibilities:﻿</strong></p>
<ul>
<li>Be a key contributing Web developer in a cross-functional team;</li>
<li>Design and implement features on one or more company applications;</li>
<li>Build shared components across applications;</li>
<li>Specify and develop interfaces to the company service backend APIs;</li>
<li>Coordinate with Product teams on feature specification and delivery;</li>
<li>Coordinate &amp; communicate with local and distributed/overseas team members and stakeholders;</li>
<li>Mentor other team members on your areas of expertise.</li>
</ul>
<p>&nbsp;</p>
<p><strong>Team and work organization:</strong> Our client currently have 4 teams with 5 - 10 professionals in each. They are cross-functional and consist of QA, product people, front-end &amp; back-end developers. People are located in Riga, San Francisco, and Toronto.</p>
<p></p>
<p><strong>IT stack:</strong> Git, Jira, Confluence, Jenkins, GraphQL, AppSync, or Amplify,Python, AWS, Encryption and DRM, OAuth2, OIDC, SAML and Federated Authentication, both relational and no-SQL databases.</p>
<ul>
<li>Architechture</li>
<li>Microservice architecture and for iOS TCA</li>
<li>Platform/Web: microservices</li>
<li>80% new development and 20% maintenance and customer support</li>
<li>The methodology by which work is organized (Agile, Scrum, KANBAN, Waterfall)</li>
<li>Agile Scrum with 2-week sprints</li>
</ul>
<p></p>

## International Business Consulting: 
 <p>Na IBC desenvolvemos soluções simples e criativas para melhorar a gestão de Pessoas... em qualquer parte do Mundo!</p>
<p>A International Business Consulting é uma empresa constituída por um grupo de consultores experientes e com percursos consolidados, a nível nacional e internacional. Atualmente, possuímos escritórios em Lisboa e em Luanda.&nbsp;</p><a href='https://coodesh.com/empresas/international-business-consulting'>Veja mais no site</a>

 ## Habilidades: 
 - GIT 
- JIRA 
- Jenkins 
- GraphQL 
- Python 
- AWS
## Local: 
 Budapest, Hungary
## Requisitos: 
 - Experience of building and deploying React Single-Page Applications to production environments, including using Redux for state management; 
- Experience of using JavaScript and TypeScript to build complex applications, including concepts such as asynchronous programming, reactive programming with Observables, and modern language features introduced from ES6 onwards; 
- Experience of using HTML, CSS, and CSS-in-JSS techniques to create performant and accessible user interfaces, preferably using Styled-Components and modern layout APIs such as FlexBox and CSS Grid; 
- Strong written and oral communications.
## Diferenciais: 
 - Working within a Scrum or Agile delivery process; 
- Using GraphQL and REST APIs to power user interfaces; 
- Using HTML5 Media APIs for video playback, ideally with an understanding of browser DRM; 
- Leading a small team of engineers in an Agile process.
## Benefícios: 
 - Competitve Salary; 
- Competitive Benefits; 
- Learning and development support; 
- Welcoming and friendly culture.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [React Developer (Pleno) na International Business Consulting](https://coodesh.com/vagas/junior-react-engineer-135155671?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Regime
CLT
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
