### ISSUE TITLE
[Remote] Desenvolvedor Angular @EmpowerMind

### ISSUE THREAD

**Issue by NatachaNarimatsu** [frontendbr/vagas#7398]
### **EmpowerMind**
Somos uma empresa que oferece consultoria em recrutamento e seleção, benefícios, transformação cultural, mentoria e educação corporativa em todo o Brasil.

### **Descrição da vaga**

É um projeto sobre sanidade animal e vegetal para o setor publico.

**Nessa oportunidade, você trabalhará com:**

Executar teste automatizados e identificar o problema em caso de falhas;
Melhorias no sistema;
API de integração, microserviços;
Desenvolvimento e manutenção de aplicativos;
Ajudar na fabricação de uma solução para digitalizar os cadastros do órgão.

### **Local**
Campo Grande-MS;

### **Requisitos**
**Obrigatório conhecimento em:**

- Angular v2;
- ASP.NET MVC;
- Bootstrap;
- C#; 
- Entity Framework;
- Java Script.

**Diferencial:**

- .NET Core;
- React Native;
- SQL SERVER;
- Testes Automatizados;
- Typescript.

### **Benefícios**
Vale alimentação de 700,00 reais por mês;
Plano de saúde;
Convênio Médico;
Convênio Odontológico;
Seguro de vida;

### **Contratação**
Tipo de vaga: Tempo integral. Para residentes de CG, contratação CLT + benefícios. Residentes de outros Estados e regiões, contratação na modalidade PJ;
Budget de negociação: Entre R$9.000,00 à R$ 12.000,00

### **Como se candidatar**
Por favor envie um e-mail para [natacha@empowermind.com.br](mailto:natacha@empowermind.com.br) com seu CV anexado - enviar no assunto: **Vaga - Desenvolvedor Angular**
Ou, se candidate através do link: https://www.linkedin.com/jobs/view/3275087498

### **Tempo médio de feedbacks**
Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: [natacha@empowermind.com.br](mailto:natacha@empowermind.com.br)

**Alocação**

100% remoto.

**Regime**

PJ;
Jornada de trabalho: 07h30 às 11h30 e das 13h30 às 17h30.

**Nível**

Sênior.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
