### ISSUE TITLE
[Porto Alegre] Desenvolvedor Front-End

### ISSUE THREAD

**Issue by FelipeBortolini** [frontendbr/vagas#74]
## Descrição da vaga

Oportunidade em Porto Alegre para um desenvolvedor Front-End para trabalhar no nosso mais recente projeto em parceria com a ADP Innovation Labs de Nova York. 
Queremos construir uma nova abordagem para a forma e os meios com os quais o usuário interage com os produtos da ADP. Esse profissional vai se envolver principalmente com JavaScript, HTML5, CSS, ES6/ES2015, ReactJS e NodeJS.

## Local

Porto Alegre. Bairro Petrópolis. Av. Soledade, nº 550.

## Benefícios

- Carga horária 40 horas semanais. Horário flexível. Contratação CLT, plano de carreira, planos médico e odontológico, vale transporte ou estacionamento, vale refeição, previdência privada, programa de participação nos resultados, seguro de vida, entre outros.

## Requisitos

**Obrigatórios:**
- Experiência com JavaScript, HTML5 e CSS3.

**Desejáveis:**
- SASS, PostCSS e Webpack ou similar
- ES6/ES2015, ReactJS, NodeJS e Meteor ou similar

**Diferenciais:**
- capacidade de sentir a Força, auto-organizado e que curta trabalhar em equipe. 

## Contratação

CLT

## Nossa empresa

ADP
www.adp.com
Líder mundial em sistemas de folha de pagamento, com 54.000 colaboradores no mundo. Estamos contratando para a ADP Labs, unidade de TI em Porto Alegre. 

## Como se candidatar

Podes entrar em contato diretamente comigo: Felipe.Bortolini@adp.com para dúvidas, envio de CVs ou mesmo indicações para essa vaga. 

Obrigado!

**Comment by LFeh** [comment]
Boa

**Comment by donnes** [comment]
Opa, mandei e-mail pra ti @FelipeBortolini

**Comment by guilhermecomum** [comment]
Essa vaga ainda ta disponível?

**Comment by LFeh** [comment]
Rolou?

**Comment by camilatigre** [comment]
@FelipeBortolini 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
