### ISSUE TITLE
[Feira de Santana e Região] Front-End Developer na HUGGY

### ISSUE THREAD

**Issue by raloliver** [frontendbr/vagas#740]
## Descrição da vaga

O frontend vai trabalhar na área de marketing da Huggy. Tendo como principais atividades: manutenção do website, desenvolvimento de landing pages, email marketing (a partir de layouts criado por nossos designers), análise de performance e conversão, customização de temas e plugins, criação de páginas para endomarketing e campanhas sazonais.

## Local

Feira de Santana - BA no Club4Work Coworking

## Benefícios

- Horário flexível (8 horas entre as 08:00 e 20:00)
- Oportunidade de crescimento num ambiente em constante mudança
- Ambiente diferenciado (Você vai curtir!)
- Bolsa 50% em Curso de Inglês

#### Diferenciais

- Pode trabalhar de bermuda e crocs
- Cafezinho livre
- Lanches livre
- Frutinhas sempre frescas
- Jogatina garantida no final da tarde
- NerfTime (venha preparado pra batalha)

## Requisitos

**Obrigatórios:**

- Ser criativo, organizado, comunicativo e amar o que faz
- Gostar de trabalhar em equipe
- Gostar de estudar e aprender sempre
- Conhecimento em HTML (semântica e micro-data), CSS3 (animações e performance), jQuery (AJAX)
- Responsividade (Mobile First)
- Grande vivência em tecnologias e ferramentas voltadas ao front-end
- Trabalhar em conjunto com um time multidisciplinar (Design, Conteúdo, Back-end, e outros)
- Saber como desenvolver um site com boas práticas de SEO
- Experiência com Wordpress 4
- Preocupação com performance
- Noções de UX e Designer

**Desejáveis:**

- Ter trabalho com práticas Agile (Scrum, Kanban, XP)
- Background como Designer Gráfico
- Inglês
- Deve entregar uma página fiel ao layout e semanticamente correta
- Noções de testes A/B
- Noções de testes de Usabilidade
- Noções de PHP (para customização de temas e plugins)
- Noções de algum pré-processador CSS (SASS, LESS, Stylus)

**Diferenciais:**

- Conhecer a arquitetura das APIs RESTFull
- Inglês avançado
- Contribuição em projetos opensource
- Participação e colaboração em comunidades
- Formação em Marketing ou Design

## Contratação

A combinar

## Nossa empresa

Olá! Tudo bem?

Gostaríamos de nos apresentar. Somos uma solução que integra os mais diversos canais de comunicação de sua empresa a fim de tornar o relacionamento entre sua marca e seus clientes mais eficiente e prazeroso.

Mas por que isso é importante?

Essa é uma ótima pergunta! A diversidade de ferramentas de comunicação pode contrariar a continuidade no atendimento aos clientes e, ao mesmo tempo, impossibilitar um controle integrado das estratégias de comunicação. É por isso que acreditamos que a comunicação deve ser mais inteligente, humana e envolvente.

E é aí que a gente entra!

Nós utilizamos o que há de mais inovador em tecnologias cognitivas para tornar o atendimento a cada um de seus clientes sempre eficiente e personalizado, seja qual o meio de contato por ele escolhido. Nós, da Huggy, sabemos que as tecnologias, quando bem aplicadas, podem potencializar 
 excepcionalmente a proximidade, a naturalidade e a eficiência dos meios por onde pessoas se relacionam.

E então, vamos conversar melhor?

## Como se candidatar

Por favor envie um email para miqueias.gomes@huggy.io com seu CV, github, linkedin e o que mais achar interessante - enviar no assunto: Vaga Frontend e com a resposta as seguintes perguntas:

1. Descreva a sua equipe atual (ou anterior, se não estiver empregado no momento). O que você gosta e não gosta?
1. Qual foi seu maior fracasso até o momento?
1. Nos conte sobre o momento em que você mais trabalhou em sua vida. Fique à vontade para contar experiências profissionais, pessoais e na vida acadêmica.
1. Como você descreve a sua personalidade?

**Comment by renanlara** [comment]
Bahia <3

**Comment by lailsoncv** [comment]
Que massa!!

**Comment by joaoantoniogomes** [comment]
Eu gostaria de trabalhar e já enviei pro seu e-mail
[CV_Joao_Antonio.docx](https://github.com/frontendbr/vagas/files/2217545/CV_Joao_Antonio.docx)

**Comment by joaoantoniogomes** [comment]
Eu gostaria de trabalhar e já enviei pro seu e-mail. Sou de Feira de Santana

**Comment by joaoantoniogomes** [comment]
Como assim?

Em Qui, 9 de ago de 2018 15:22, Israel Oliveira <notifications@github.com>
escreveu:

**Comment by joaoantoniogomes** [comment]
Compreendi

Em 9 de agosto de 2018 19:38, João Antonio Gomes <joaoantoniogomes@gmail.com
