### ISSUE TITLE
[Home Office] Front-end Developer Sênior na Ed Dev

### ISSUE THREAD

**Issue by RHSomosEd** [frontendbr/vagas#7401]
> Vaga Remota

## Nossa empresa

Criamos softwares. Impulsionamos pessoas/negócios/o mundo_

Se você topa o desafio, venha fazer parte do nosso time. Estamos focados em qualidade e resultado, com tecnologias de ponta, em um ambiente colaborativo. Pensamos e agimos como um time, desde o problema até a solução. Aqui somos um só, onde o problema de um é um problema de todos.

## Descrição da vaga

Atuar diretamente com a área de interação de um sistema com os usuários; 
Codificar novas funções do sistema ou alterar funções já existentes de acordo com o projeto; 
Criar testes unitários para testar o sistema após a codificação; 
Estimar tempo de desenvolvimento para cronograma de soluções; 
Documentar aplicação, indicando as alterações realizadas; 
Analisar e corrigir bugs que são encontrados no sistema; 
Apoiar e dar suporte a áreas envolvidas; 
Entendimento dos princípios de UX e as melhores práticas; 
Analisar a arquitetura atual das soluções, mapear os gaps e propor melhorias na arquitetura.

## Local

Remoto

## Requisitos

Sólida experiência em desenvolvimento Frontend (Angular);
Experiência com desenvolvimento Backend (.net core); 
Experiência com MS Azure Devops (automação, criação de pipelines); 
Conhecimento em banco de dados SQL Server e/ou Oracle; 
Experiência de arquitetura de aplicações; 
Experiência em Clean Architecture; 
Experiência em Entity Framework; 
Conhecimento em testes de unidade automatizados; 
Conhecimento em testes de integração automatizados; 
Experiência em metodologia Ágil (Scrum ou Kanban); 
Experiência com integração entre serviços por meio de API REST; 
Experiência com integração contínua CI/CD; 
Experiência com versionamento de código utilizando GIT. 

## Benefícios

Trabalhe de onde você estiver
Assistência Médica Amil 750
Assistência Odontológica Amil
Vale Refeição/Alimentação R$31,00 p/dia
Auxílio home office
Seguro de vida
Assistência funeral
Acesso ilimitado aos cursos da plataforma Alura
PLR

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para rafaela.oliveira@ed.dev.br seu CV anexado - enviar no assunto: Vaga Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
