### ISSUE TITLE
[Remoto] Front-end Developer React na Gamefica

### ISSUE THREAD

**Issue by rberts** [frontendbr/vagas#7404]
## Nossa empresa

Startup fundada em Brasília/DF, desenvolvemos uma plataforma de promoções voltada para o mercado de varejo, utilizando técnicas de gamificação, trabalhamos a fidelidade, recorrência nas vendas e promoções em shoppings.

## Descrição da vaga

Desenvolver e expandir nossa plataforma adicionando novas funcionalidades e melhorando constantemente a eficiência de nossas aplicações.

## Local

100% Remoto

## Requisitos

**Obrigatórios:**
- Mínimo de 2 anos de experiência com React.js
- Redux
- Redux Saga (Redux side effect middleware)
- APIs REST
- Sass
- Experiência na criação de novos projetos

**Diferenciais:**
- Docker
- NextJS
- Testes de integração com Cypress
- Construção de templates com handlebars
- Experiência com desenvolvimento em Typescript

## Contratação

PJ a combinar

## Como se candidatar

Envie um email para vagas@gamefica.me com seu CV anexado - enviar no assunto: Vaga Front-end
Desejável que seja enviado pelo menos 2 links de projetos

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
