### ISSUE TITLE
[Hibrido / Campinas] Front-end Developer na Coodesh

### ISSUE THREAD

**Issue by blankapf** [frontendbr/vagas#7405]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-frontend-185121962?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>Techplus</strong> está buscando <strong><ins>Frontend Developer</ins></strong> para compor seu time!<br><br>Estamos procurando pessoas altamente motivadas para enfrentar grandes desafios técnicos e trabalhar dentro de uma equipe sensacional.</p>
<p><strong>Responsabilidades:</strong></p>
<ul>
<li>O profissional trabalhará em todo o ciclo de desenvolvimento de um projeto.</li>
</ul>
<p></p>

## Techplus: 
 <p>Somos uma empresa líder em fornecer soluções em automação industrial e integração de sistemas de informação. A Techplus integra produtos e conhecimento para atingir soluções que ajudam os nossos clientes a reduzir os custos operacionais e aumentar a qualidade, segurança, produtividade e competitividade.</p>
<p>A Techplus ajuda empresaS no desafio da Transformação Digital!</p><a href='https://coodesh.com/empresas/techplus'>Veja mais no site</a>

 ## Habilidades: 
 - Angular 
-  UX/UI 
- CSS 
- UI para Mobile Apps
## Local: 
 Campinas
## Requisitos: 
 - Conhecimento em metodologias ágeis;  
- Arquitetura web; 
- Bons conhecimentos em UX; 
- Programação em javascript; 
- Desenvolvimento front-end em react ou angular 4.0 ou superior; 
- Formação em Ciência da Computação; Engenharia da Computação; Análise e Desenvolvimento de Sistemas; Sistemas de Informação, ou áreas afins.
## Diferenciais: 
 - Experiência profissional com desenvolvimento de sistemas web e mobile; 
- Conhecimentos em nosql (bancos não-relacionais); 
- Conhecimentos em arquitetura REST; 
- Inglês intermediário ou avançado; 
- Experiência profissional com desenvolvimento de sistemas web; 
- Documentação de API com Swagger.
## Benefícios: 
 - Horários Flexível; 
- Assistência médica; 
- Vale Refeição; 
- Alura; 
- Gympass.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Front-end Developer na Techplus](https://coodesh.com/vagas/desenvolvedor-frontend-185121962?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
