### ISSUE TITLE
[REMOTO] Front-end Developer Angular na Ed Dev

### ISSUE THREAD

**Issue by RHSomosEd** [frontendbr/vagas#7407]
> Vaga Remota durante a pandemia

## Nossa empresa

Se você topa o desafio, venha fazer parte do nosso time. Estamos focados em qualidade e resultado, com tecnologias de ponta, em um ambiente colaborativo. Pensamos e agimos como um time, desde o problema até a solução. Aqui somos um só, onde o problema de um é um problema de todos.

Criamos softwares. Impulsionamos pessoas/negócios/o mundo_

## Descrição da vaga

Atuar diretamente com a área de interação de um sistema com os usuários; 
Codificar novas funções do sistema ou alterar funções já existentes de acordo com o projeto; 
Criar testes unitários para testar o sistema após a codificação; 
Estimar tempo de desenvolvimento para cronograma de soluções; 
Documentar aplicação, indicando as alterações realizadas; 
Analisar e corrigir bugs que são encontrados no sistema; 
Apoiar e dar suporte a áreas envolvidas; 
Entendimento dos princípios de UX e as melhores práticas; 
Analisar a arquitetura atual das soluções, mapear os gaps e propor melhorias na arquitetura.

## Local

HOME OFFICE

## Requisitos

**Obrigatórios:**
Sólida experiência em desenvolvimento Frontend (Angular);
Experiência com desenvolvimento Backend (.net core).

**Desejáveis:**
Experiência com MS Azure Devops (automação, criação de pipelines); 
Conhecimento em banco de dados SQL Server e/ou Oracle; 
Experiência de arquitetura de aplicações; 
Experiência em Clean Architecture; 
Experiência em Entity Framework; 
Conhecimento em testes de unidade automatizados; 
Conhecimento em testes de integração automatizados; 
Experiência em metodologia Ágil (Scrum ou Kanban); 
Experiência com integração entre serviços por meio de API REST; 
Experiência com integração contínua CI/CD; 
Experiência com versionamento de código utilizando GIT. 

## Benefícios

Trabalhe de onde você estiver
Assistência Médica Amil 750
Assistência Odontológica Amil
Vale Refeição/Alimentação R$31,00 p/dia
Auxílio home office
Seguro de vida
Assistência funeral
Acesso ilimitado aos cursos da plataforma Alura
PLR

## Contratação

PJ ou CLT

## Como se candidatar

Por favor envie um email para rafaela.oliveira@ed.dev.br com seu CV anexado - enviar no assunto: Vaga Front End

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
