### ISSUE TITLE
[Remoto] Estágio Front-end Dev na Whats

### ISSUE THREAD

**Issue by gabrielalmeida** [frontendbr/vagas#7408]
## Nossa empresa

**Nós desbloqueamos super-poderes do WhatsApp para empresas**

Acreditamos que exista um gap quando se trata da utilização do WhatsApp nos celulares dos colaboradores de empresas. Faltam funcionalidades, falta visibilidade, falta inteligência. Nós mudamos isso.

Desbloqueamos a caixa preta que é o WhatsApp e fornecemos ferramentas para otimizar a utilização e gerar insights valiosos.

Conectando mensagens, conectamos tudo.

## Descrição da vaga

Buscamos um(a) estudante da área de tecnologia com interesse em evoluir seus conhecimentos e fazer a diferença em uma empresa. Por sermos uma empresa pequena e com time enxuto, acreditamos que trabalhar por aqui proporcione uma experiência diferenciada e enriquecedora, seu aprendizado e trabalho será extremamente relevante para a empresa e você terá voz ativa e participação em diversas etapas e decisões do dia a dia da empresa.

## Local

Remoto

## Requisitos

**Obrigatórios:**

Muita vontade de aprender, interesse em interfaces web e em tecnologia.
Se sentir confortável com HTML/CSS, Javascript, React & Git

**Desejáveis:**

* JS ES6 (Promises, Async/await, etc)
* PostgreSQL, Prisma
* Hasura, GraphQL
* NextJS

**Diferenciais:**

* FP
* CI/CD & Linux
* Se sentir confortável em usar CLIs

> Be a worker… and be prepared to show it! Everyone is responsible for making awe-something, building products, owning decisions, selling something, and hustling. You can’t just show up at the meetings.

## Benefícios

* 30 dias de férias

## Contratação

Estágio 6h
Flexibilidade de horário
Bolsa R$1500

## Como se candidatar

https://whats.ws/jobs – Selecionar a vaga – Ler descrição completa e preencher o formulário

#### Alocação
- Remoto

#### Regime
- Estágio

**Comment by tascintra** [comment]
Boa noite! Está vaga é a que está como estágio full stack no Notion?

**Comment by gabrielalmeida** [comment]
> Boa noite! Está vaga é a que está como estágio full stack no Notion?

Correto, está mesmo!

**Comment by antoniodamous** [comment]
Bom dia! Parabéns pela proposta e muito obrigado pela oportunidade que vocês estão oferecendo. Já efetuei a minha inscrição.
Desejo sucesso a todos!

**Comment by EdiJunior88** [comment]
Apliquei para a vaga de estágio, seja o que Deus quiser e boa sorte a todos

**Comment by matheusSandrin** [comment]
Apliquei! Espero poder ter a oportunidade de trabalhar e aprender com essa equipe!

**Comment by allbertuu** [comment]
Aplicado haha 🚀🥰

**Comment by ZaikoXander** [comment]
Aplicadíssimo e aguardando a resposta 😎

**Comment by gabriellfernandes** [comment]
Aplicado 😎

**Comment by DouglasTrindade** [comment]
Aplicado!

**Comment by MarcosASL** [comment]
Aplicado, obrigado pela oportunidade.

**Comment by matheuslei** [comment]
Enviado! ;) ✅

**Comment by suamirocha** [comment]
Não sei se é tarde mas enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
