### ISSUE TITLE
[ ☆☆ R E M O T O ☆☆ ] Front-end Developer no iCasei

### ISSUE THREAD

**Issue by gustaum** [frontendbr/vagas#7413]
## Nossa empresa

O Portal iCasei reúne a emoção de criar um site único e exclusivo para o seu casamento, as dicas diárias com notícias que inspiram e ajudam os noivos a decidirem os preparativos finais do Grande Dia, e os melhores parceiros em serviços, os quais confiamos e indicamos como fornecedores. E mais do que um fornecedor do seu casamento, somos a emoção de compartilhar cada passo deste dia tão especial com seus familiares e amigos em um site personalizado por vocês, com todo o carinho que este momento merece, além de oferecer um conteúdo de qualidade e as melhores empresas do mercado de casamento em um só lugar.

Tida como uma das startups mais "quentes"​, em 2007 o iCasei inovou o mercado de casamentos criando uma plataforma onde os noivos abrem um canal bi-direcional com seus convidados sobre tudo que se refere ao evento com RSVP, mapas, dicas, e muito mais.  Em 2009, inovou mais um vez e inventou o "jeito iCasei de presentear"​, onde os presentes são revertidos em dinheiro para os noivos. Nascia  a primeira FINTECH do mercado de casamentos, a iCasei Presentes. 

Em 2017, 15 anos após a criação da empresa, inova mais uma vez e lança um aplicativo para que os convidados possam interagir ainda mais com o evento. 

## Descrição da vaga

Estamos buscando uma pessoa que seja proativa e que tenha interesse em trabalhar em ambiente de desenvolvimento de produtos, com autonomia e mudanças constantes.

## Local

REMOTO

## Requisitos

**Os nossos requisitos técnicos são:**
- Sólidos conhecimentos em HTML5, CSS3 (SASS, SCSS e LESS) e Javascript (ES6).
- Escrever código limpo e legível.
- Ter profunda preocupação com qualidade.
- Experiência em integração com REST APIs.
- Experiência em desenvolvimento de layout responsivo.
- Conhecimento com boas praticas para performance WEB (Javascript, CSS, HTML).
- Experiência desenvolvendo aplicação em frameworks front-end atuais e legados (Ex. AngularJS, React ou outros atuais)
- Conhecimento básico em ferramenta de versionamento (GIT).
- Inglês (técnico).

**Diferenciais:**
- Conhecimentos básicos de back-end (Ruby, Go ou outros)
- Conhecimentos básicos de bancos de dados relacionais (DML)
- Conhecimento de boas práticas de UX.

## Benefícios
- 20 dias descanso remunerados 
- Plano de Saúde OMINT
- Gympass
- Auxílio de custo para cursos, livros e palestras (até R$500,00 mês);

**Diferenciais:**
- Macbook Pro
- Horário Flexível

## Contratação

PJ a combinar

## Como se candidatar

Antes de marcarmos a entrevista online, nós precisamos que você responda algumas perguntas:
https://forms.gle/LoXrsXEtFXxFw9uZ9

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
