### ISSUE TITLE
[Itaperuna-RJ] Front-end  Developer com foco em WordPress na Inova

### ISSUE THREAD

**Issue by carlosmoliv** [frontendbr/vagas#7417]
> Vaga Remota durante a pandemia

## Nossa empresa

Somos uma agência de Marketing Digital com bastante experiência de mercado

## Descrição da vaga

Estamos com vaga aberta com foco em WordPress. As principais funções serão: atuar em projetos de sites institucionais, lojas WooCommerce e páginas.

## Local

Remoto, RJ, Itaperuna

## Requisitos

**Obrigatórios:**
- experiência com WordPress
- experiência com WooCommerce

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para contato@inovany.com.br com seu CV anexado - enviar no assunto: Vaga Dev WordPress na Inova

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
