### ISSUE TITLE
[Hibrido / São Paulo, São Paulo, Brazil] Frontend Developer (Híbrido em São Paulo/SP) na Coodesh

### ISSUE THREAD

**Issue by blankapf** [frontendbr/vagas#7418]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/vaga-desenvolvedor-frontend-hibrido-sao-paulosp-131829273?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>KLB GROUP BRASIL</strong> está buscando <strong><ins>Frontend Developer</ins></strong><strong> (Híbrido - São Paulo)</strong> para compor seu time!</p>
<p></p>
<p><strong>Escopo:</strong></p>
<p>Será detalhado em entrevista técnica.</p>

## KLB GROUP BRASIL : 
 <p>A KLB Group é especializada na implementação de projetos em empresas públicas e privadas. Seja em projetos de desenvolvimento, produção ou transformação, a KLB Group assegura a implementação eficaz, mobilizando rapidamente uma equipe de especialistas de várias funções (compras, cadeia de suprimentos, qualidade, engenharia, TI, finanças, etc.), com uma combinação única de experiência em design, implementação e operação. A KLB Group tem mais de 500 funcionários na Europa, América e Ásia.</p>
</p>

 ## Habilidades: 
 - Design de Front-End 
- Java 
- Vue.js 
- Angular 9 
- Javascript
## Local: 
 São Paulo, São Paulo, Brazil
## Requisitos: 
 - Vue Js; 
- Angular; 
- Javacript; 
- Wildfly.
## Diferenciais: 
 - Conhecimento em Sistemas de Seguros; 
- Java 8; 
- Spring Booot, Spring MVC.

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Developer (Híbrido em São Paulo/SP) na KLB GROUP BRASIL ](https://coodesh.com/vagas/vaga-desenvolvedor-frontend-hibrido-sao-paulosp-131829273?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Regime
CLT
#### Categoria
Front-End

**Comment by kellysondias** [comment]
Olá! Esta vaga é para profissional Júnior, Pleno ou Sênior?

**Comment by blankapf** [comment]
Pleno/Sênior

**Comment by blankapf** [comment]
Olá! Essa vaga é para Pleno/Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
