### ISSUE TITLE
[Remoto] Front-end Developer na M3 ecommerce

### ISSUE THREAD

**Issue by heraldo663** [frontendbr/vagas#7419]
## Nossa empresa

A M3 é uma empresa de pessoas, especializada em implantação e evolução de e-commerce B2C, B2B, Marketplace, Omnichannel e Cross Border na VTEX.

Somos certificados pelo Great Place to Work® e estamos há mais de oito anos no mercado, revolucionando negócios através do comércio digital e transformando a experiência dos lojistas e dos consumidores.

O nosso time é composto por profissionais apaixonados por desafios e pelo dinamismo do setor de tecnologia. Além disso, estamos presentes no Brasil, Argentina, Colômbia e México, conferindo grande diversidade à equipe.

Venha fazer parte do time M3 e crescer junto conosco!

#LetsGoTogether

## Descrição da vaga

Somo uma das maiores agencias de e-commerce especializados na plataforma VTEX. Nosso time trabalha com o desenvolvimento de lojas virtuais em cima da plataforma VTEX, onde no dia a dia trabalhamos usando o store framework fornecido pela VTEX, que em sua base usa o a biblioteca React em conjunto da linguagem Typescript e GraphQL para sua camada de dados.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- JavaScript/Typescript;
- HTML/HTML5 e CSS
- React;
- Performance WEB;
- Desenvolvimento web responsivo;

**Desejáveis:**
- Superior completo ou Cursando;
- Conhecimento da plataformas de e-commerce;
- Nodejs;
- Conhecimentos sobre SEO;
- GraphQL;
- VTEX;

## Benefícios

- Plano de saúde + Odontológico +V.A
- Day Off
- Aulas de Espanhol
- Bônus de Indicação
- Licença PETernidade
- Desenvolvimento Contínuo 

## Contratação

CLT

## Como se candidatar

Link de inscrição da vaga: https://app.pipefy.com/public/form/cjJmu6-g

#### Alocação
- Remoto

#### Regime
- CLT
#### Nível
- Júnior
- Pleno
- Sênior

**Comment by MatheusdeSouzaSilva70** [comment]
Olá, tudo bem?
Está vaga, ainda está disponível?

**Comment by heraldo663** [comment]
Olá, tudo bem.
Sim ainda tgemos vagas.

**Comment by matheuslei** [comment]
Aplicado! 👩‍💻

**Comment by santos-vinicius** [comment]
Aplicado!!

**Comment by eng-Bruno** [comment]
Enviado!

**Comment by luam0oliveira** [comment]
Aplicado 🚀

**Comment by WelllWas** [comment]
Enviado

**Comment by DanRodriguezdev** [comment]
Obrigado pela oportunidade!

**Comment by guimevn** [comment]
Enviado.

**Comment by sucodelarangela** [comment]
Eviado!

**Comment by joaov1ct0r** [comment]
Enviado

**Comment by FeRiffo** [comment]
Enviado!

**Comment by josephmatheus** [comment]
Enviado.

**Comment by Virkkunen** [comment]
Enviado

**Comment by hignicao** [comment]
Enviado

**Comment by evertondsvieira** [comment]
Enviado

**Comment by DouglasMelo-Dev** [comment]
Aplicado para as vagas.

Estou à disposição. 👨‍💻🙋‍♂️

**Comment by ThyagoHolanda** [comment]
Aplicado!

**Comment by JailsonSantos** [comment]
send

**Comment by EdiJunior88** [comment]
Enviado

**Comment by kvnol** [comment]
Enviado!

**Comment by gvao** [comment]
Enviado!

**Comment by andykallian** [comment]
Aplicado!

**Comment by natamartins** [comment]
Olá,  não está enviando as informasções! a vaga ainda está aberta?
caso sim deixarei meu linkedin: https://www.linkedin.com/in/nat%C3%A3martins/

**Comment by felipefialho** [comment]
Vou fechar até resposta do @heraldo663
