### ISSUE TITLE
[Remoto] Front-end Developer na SHIFT

### ISSUE THREAD

**Issue by dudarcass** [frontendbr/vagas#7420]
> Vaga Remota durante a pandemia

## Nossa empresa

Temos um jeito muito especial de trabalhar e fazemos muito mais do que desenvolver e comercializar sistemas, nossa rotina é movida por uma cultura de gestão do conhecimento, desenvolvimento de pessoas e um ambiente de trabalho que cultiva as relações de respeito, diversidade e a essência dos nossos valores:

- Agimos com senso de dono
- Construímos vínculos profundos de compromisso e relacionamento
- Agimos com respeito
- Buscamos a superação
- Somos assertivos
- Somos protagonistas
- Sentimos orgulho em pertencer

VENHA SER **FELIZ** AQUI TAMBÉM \o/, dê uma olhadinha em alguns desafios da vaga:

Atuar em time ágil para desenvolver requisitos para aplicações web, escrevendo código e testes unitários seguindo as boas práticas de programação e padrões de projeto; Participar da elaboração de soluções técnicas, interagindo com as áreas de operações e produtos.

## Descrição da vaga

RESPONSABILIDADES E ATRIBUIÇÕES

**Produto**

- Compreender os requisitos funcionais e não funcionais a serem incluídos, alterados ou removidos nos softwares Shift;
- Realizar análise dos requisitos de software a serem implementados nos produtos Shift, construindo artefatos técnicos de engenharia de software que suportem a codificação nos padrões estabelecidos pela Shift;
- Contribuir com o desenho técnico das soluções em conjunto com a liderança e arquitetos de software;
- Realizar a estimativa de tamanho de software a ser desenvolvido ou mantido e o planejamento dos entregáveis, sendo esse último em conjunto com o Agilista;
- Codificar os requisitos de software nos produtos Shift, através do uso de ferramentas de desenvolvimento oficiais e homologadas, considerando seus impactos nas regras de negócios inerentes ao sistema e aplicação;
- Realizar manutenção na documentação técnica dos softwares, mantendo-a sempre atualizada;
- Pesquisar, sugerir, desenvolver e garantir soluções para o desempenho dos produtos Shift, definidos pelo time de arquitetura, prevendo taxas de crescimento e alternativas físicas de implantação;
- Orientar as áreas de apoio, nas consultas a documentações técnicas e fontes alternativas de informações, simulando problemas em ambiente controlado quando necessário ou acionando a área de suporte;
- Depurar código fonte com objetivo de encontrar e sanar defeitos nas soluções Shift;
- Realizar testes unitários, de componentes e de integração com a finalidade de entregar produtos e soluções de software com índices de defeitos dentro dos limites estabelecidos pela Shift;
- Propor melhorias de produto e soluções de problemas emergenciais nos clientes;
- Responder consultas técnicas dos times internos, propondo mudanças de processos, negociando alternativas de solução, propondo adoção de novos métodos e técnicas, com o objetivo de assegurar a entrega de soluções para as necessidades dos mesmos.

## Local

Remoto, com viagens esporádicas (e pagas pela empresa) para eventos e treinamentos no nosso escritório em São José do Rio Preto [SP]

## Requisitos

**Obrigatórios:**

- Graduação completa em áreas de Tecnologia da Informação;
- Experiência em desenvolvimento ou manutenção de software;
- Conhecimentos intermediários em ferramentas de produtividade desktop (planilhas, editores de textos, apresentações);
Sólidos conhecimentos em:
  - Lógica de programação;
  - Linguagens de programação orientada a objetos;
  - HTML5;
  - CSS;
  - JavaScript;
  - TypeScript;
  - JSON;
  - REST;
  - API's REST;
  - Angular;
  - Versionamento de código em GIT;
  - Padrões de projeto e conceito SOLID;
  - Análise de sistemas;
  - Teste Unitário.

**Desejáveis:**

- OAuth 2.0
- Métodos ágeis
- Docker.
- 

**Diferenciais:**

- Especialização em desenvolvimento de software e inglês intermediário

## Benefícios

- Assistência Médica Unimed
- Plano Odontológico Odontoprev
- Seguro de vida
- Benefício Flexível Swile de R$ 715,00/mês
- Subsídio educacional para estudos
- Programa de qualidade de vida (psicoterapia e terapia de floral)
- Bônus nascimento filho
- Bônus casamento
- Bônus por indicar talentos
- Auxílio creche
- PLR
- Home office ou Híbrido se residente em São José do Rio Preto/SP
- Auxílio Tecnologia em Casa de R$ 180,00/mês para você usar da forma que desejar, seja para trabalho, estudos, entretenimento!
- Horário flexível (podendo trabalhar entre as 06h e 21h)
- Short Friday para aproveitar parte das sextas-feiras da forma que quiser!

## Contratação

CLT

## Como se candidatar

Por favor envie um email para eduarda.cassiano@shift.com.br com seu CV anexado - enviar no assunto: Vaga Front (Angular)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: eduarda.cassiano@shift.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
