### ISSUE TITLE
Remoto - Desenvolvedor Fullstack Pleno (WA Project) 

### ISSUE THREAD

**Issue by Claudiaantunesdelima** [frontendbr/vagas#7425]
📌Desenvolvedor FULLSTACK PLENO 
 

🔷Conhecimento e Linguagens: C# e Typescript
 Frameworks: .NET e React
 Banco de dados: Postgresql

🔷Back-end:
 .NET
 Criação e consumo de API’s
 EntityFramework
 Conhecimento básico de REDIS
 Postgresql

🔷Front-end:
 Javascript/Typescript
 React
 Framework UMI baseado em React (diferencial)
 Consumo de API’s em .NET

➡️Ensino Superior Completo ou em andamento em Ciência da Computação ou afins (Desejável) 

Informações Adicionais 
💠100% Remoto;
💠 Contratação PJ;
💠Férias (15 dias);
💠Presentes em datas comemorativas;
💠 Licenças para o trabalho;
💠Nós pensamos na sua carreira, aqui na WA você contará com nosso Plano de Carreira, o que isso significa? que terá avaliação semestral, rotinas de feedbacks e acompanhamento do seu plano de desenvolvimento. Todo o nosso apoio para chegar no cargo que mais almeja!
💠Grupo no Discord para curtir e jogar fora do horário do trampo (interação é tudo);
💠Bate papo de 30 minutos e conhecer uma pessoa da empresa (não vale falar do job);
💠Bate-papo toda quarta-feira durante 30 minutos com a empresa toda para falar sobre TUDO menos trabalho!

💻Se interessou? Envie seu currículo para claudia.lima@waproject.com.br, informe sua pretensão salarial como PJ.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
