### ISSUE TITLE
Pessoa Desenvolvedora Fullstack Pleno – PHP e JS (Exclusiva para Mulheres Cis ou Trans) | Remoto

### ISSUE THREAD

**Issue by larissaaguiar** [frontendbr/vagas#7426]
🚀 A FEEDZ:
Somos uma HRTech e nosso propósito é criar ambientes de trabalho mais felizes, tudo isso através de um software SaaS completo de gestão de pessoas humanizado! Por isso, começar pelo nosso próprio ninho é tão importante! Somos Parrots determinados e que se importam uns com os outros, a sede de resultado é latente e o feedback sincero é rotina.

Estamos conquistando coisas incríveis! Crescemos mais de 400% em 2021 e continuamos evoluindo em 2022, tudo isso através de um clima animado, com muito desenvolvimento e respeito para todos! (Se quiser conhecer melhor nosso ninho, voa pra cá: https://www.feedz.com.br/vagas/) 💙 Quer mais? Estamos no modelo totalmente remoto, então você pode fazer parte do nosso ninho no conforto da sua casa!!

Estamos buscando uma pessoa para o cargo de Pessoa Desenvolvedora Fullstack Pleno(PHP e JS) que irá atuar no nosso time de Produto, em uma squad multidisciplinar(5 a 8 membros), desenvolvendo sistemas que impactam mais de 100 mil usuários diretamente.

No dia a dia você vai ter bastante contato com SlimPHP, Eloquent, PHPUnit, Twig, Vue.js, MySQL, Docker, entre outras. Trabalhamos com projetos ágeis, sempre prezando a comunicação e a colaboração entre os membros do time.

Aqui na Feedz valorizamos muito a diversidade e queremos Parrots que queiram voar conosco, independente da etnia, gênero, sexualidade, nacionalidade, idade ou deficiência! Quer crescer com a gente? Vem pro ninho 💛

📚 RESPONSABILIDADES E ATIVIDADES:
Desenvolvimento backend com PHP;
Desenvolvimento de frontend com CSS, HTML e JavaScript;
Implementar códigos coerentes, coesos, claros e alinhados ao Clean Code;
Aplicar boas práticas alinhadas com o time no desenvolvimento (desenvolvimento seguro, patterns, automação, etc);
Trabalhar com o desenvolvimento de módulos dentro da plataforma;
Desenvolvimento e aplicação de testes automatizados;
Desenvolvimento de API sob demanda;
Fazer a gestão da informação das demandas atualizando o status dos projetos.
🥇 PRÉ-REQUISITOS:
Mínimo de 3 anos de experiência em desenvolvimento web com PHP e Javascript em produtos digitais;
Vivência com testes automatizados;
Experiência com API;
Estar trabalhando atualmente com as tecnologias de nossa stack;
Experiência com banco de dados relacional;
Vivência com times ágeis de tecnologia.
🎯DIFERENCIAIS:
Ter trabalhado em empresas SaaS;
Experiência com Vue.JS;
Ter trabalhado com empresas com mais de 10 mil usuários.
✨ BENEFÍCIOS:
100% Home Office ( Não vamos voltar presencial)
Vale Comida (R$700)
Plano de Saúde Unimed(subsidiado pela Feedz)
Plano odontológico Nacional da Bradesco Dental(subsidiado pela Feedz)
Auxílio Parrot Feliz (R$100/mês de investimento no desenvolvimento pessoal, saúde física ou mental do Parrot)
Auxílio Contas (R$160/mês)
Auxílio Parrot Casamenteiro(R$250 quando Parrots casam)
Auxílio Ninhada(R$250 no nascimento ou adoção de pequenos Parrots)
Happy Bird(day) (um dia de folga no mês de aniversário)
Licença paternidade estendida(21 dias)
Licença maternidade estendida(6 meses)
Ifood Office (voucher para usar dentro do app em alguns eventos internos)
Para você ter um voo com conforto, na Feedz oferecemos um auxílio de R$1.000 para materiais, como mesa e cadeira, para seu home office e enviamos todos os equipamentos eletrônicos necessários!

💰 SALÁRIO R$5.300 A 7.000* (CLT)
*a depender do tempo de experiência | 40h semanais

 Candidate-se em: https://enliztjob.app.link/hz0q0dtMPtb

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by Santoszoi** [comment]
Está fechado?
