### ISSUE TITLE
[Remoto] Fullstack Developer na @Nutcache Brasil

### ISSUE THREAD

**Issue by raissaime** [frontendbr/vagas#7428]
## Nossa empresa

A Nutcache oferece soluções all-in-one inteligente & simples de gerenciamento de projetos para a sua empresa.

## Descrição da vaga

Estamos à procura de um programador apaixonado pelo que faz para produzir soluções de software escalável que fará parte do nosso núcleo de desenvolvimento ágil que é responsável por todo o ciclo de vida do software, desde a concepção até à implementação. Como Programador FullStack, deverá estar à vontade tanto nas linguagens de codificação front-end como back-end, frameworks de desenvolvimento e bibliotecas de terceiros. 

Além disso, você tem familiaridade com as metodologias ágeis? Então, essa vaga pode ser sua!

## Local

Remoto ou Híbrido em Recife - PE, Pina.

## Requisitos
- 5+ Anos de experiência como Full Stack;
- Formação em Ciência da Computação ou cursos relacionados;
- Amplo conhecimento de React Js e Redux; HTML, CSS e Javascript;
- Experiência no desenvolvimento de aplicações web usando React com o núcleo .NET 6.0,
- GraphQL, SQL Server como diferencial;
- Desenvolver e construir microsserviços alavancando ASP .NET, C#, Core 6.0;
- Fortes conhecimentos de registro, monitorização, depuração e testes de microsserviços;
- Trabalhar com QA para assegurar que sejam produzidas soluções coesas, de qualidade e utilizáveis;
- Teste de unidade e assumir a responsabilidade pela qualidade do seu próprio código;
- Excelentes capacidades de diagnóstico, resolução de problemas e uma capacidade de aprender rapidamente;
- Aberto a novas ideias e formas de fazer as coisas com a mentalidade Lean Agile;
- Automotivado com uma atitude "pode fazer" positiva;
- Inglês avançado ou fluente;
- Conhecimentos de alto nível de Agile, Scrum e Kanban.

## Habilidades técnicas

- Experiência com ferramentas como Git e Visual Studio Code;
- Noções básicas de UI/UX;
- Experiência com React Hooks;
- Design orientado para o domínio, padrões de design de microserviços;
- Linguagens e Frameworks - React, jquery, jss, .NET Core 6.0, GraphQL, SQL Server;
- A experiência prática em DevOps e CI/CD será uma vantagem adicional;
- Saber trabalhar em equipe;
- Curiosidade para aprender;
- Atento aos detalhes.

## Benefícios
- Plano de Saúde - Bradesco Saúde Top Nacional (100% custeado para o colaborador e 50% para filhos até 18 anos);
- Plano Odontológico - Bradesco Odonto (100% custeado para o colaborador e 50% para filhos até 18 anos);
- Seguro de vida - Prudential;
- Benefício de bem-estar físico e mental - Gympass;
- Vale refeição/alimentação - Flash benefícios;
- Gratificação por indicação de novos colaboradores;
- Material de trabalho completo;
- Day off no mês de aniversário;
- Horário e formato flexível;
- Auxílio idiomas;
- Auxílios de capacitação técnica;
- Programa de curta temporada;
- Auxílio creche ou escola;
- Auxílio lente;
- Clima colaborativo e flexível.

## Contratação

CLT.

## Como se candidatar

Enviar currículos em **Inglês** para : raissaime@outlook.com ou pelo Linkedin: https://www.linkedin.com/in/raissa-aime/ 
### Nível

- Pleno
- Sênior

### Regime
- CLT

### Alocação

- Remoto
- Híbrido

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
