### ISSUE TITLE
[Vitória] Front-end Developer na Code´n App

### ISSUE THREAD

**Issue by PedroITRecruiter** [frontendbr/vagas#7429]
## Nossa empresa

Somos uma empresa que é a-pai-xo-na-da por tecnologia, que através do desenvolvimento de software e processos, buscamos soluções inovadoras e totalmente customizadas para cada um dos nossos clientes a fim de alcançar o melhor resultado, independente da tecnologia utilizada.

## Descrição da vaga

A pessoa desenvolvedora Front End participará de um projeto que desenvolverá jogos utilizando HTML5, javaScript ou Typescript.

Terá a oportunidade de atuar internamente ou em clientes parceiros, contribuindo em todo o ciclo de vida, desde a concepção até a implantação, atuando com metodologias ágeis para entregar uma solução eficiente.

## Local

Escritório, [Espírito Santo], [Vitória], [Barro Vermelho]

## Requisitos

**Obrigatórios:**
Cursando ensino superior na área de tecnologia da informação;

**Desejáveis:**
- HTML5, JavaScript/Typescript e CSS
- Desenvolvimento de jogos ou aplicações da Web, de preferência usando Typescript ou JavaScript; 
- Desenvolvimento orientado a objeto; 
- Inglês avançado (conversação).

**Diferenciais:**
- Padrões de projeto e arquitetura; 
- Testes unitários para garantir a qualidade do software desenvolvido; 
- Ferramentas de depuração de código; 
- A importância de manter um relacionamento colaborativo para desenvolvimento e apoio da equipe. 

## Benefícios

- Horário flexível e possibilidade de home office ou modelo híbrido;
- No dress-code;
- Gympass;
- Celebração de datas importantes (Seu aniversário, aniversário Code n’ App, etc.)

**Diferenciais:**
- Cesta recém-nascido;
- Cafézinho e biscoitinhos à vontade, além de puffs para cochilar nos intervalos;
- Empréstimo consignado;
- Assessoria e educação financeira;
- Oportunidade de fazer parte de um time de feras e com muitas experiências para compartilhar.

## Contratação

PJ 

## Como se candidatar

Através da nossa página de carreiras da plataforma Gupy. Link: https://codenapp.gupy.io/jobs/2918985

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: pedro.oliveira@codenapp.com

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível

- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
