### ISSUE TITLE
[REMOTO] Front-end Developer na @TRUSTLY

### ISSUE THREAD

**Issue by Trustly-br** [frontendbr/vagas#7430]
## Você conhece a Trustly?

Fundada em 2008, a Trustly é líder global em Open Banking Payments, e estamos em rápida expansão no mercado dos EUA! Hoje atendemos 10.000 comerciantes, conectando-os com mais de 650 milhões de consumidores e 7.600 bancos em mais de 30 países. Em 2021, processamos mais de US$ 20 bilhões em volume de transações em nossa rede global.

Nossa plataforma digital conta a conta redefine a velocidade, simplicidade e segurança dos pagamentos. Os consumidores pagam pelas compras simplesmente entrando em suas contas bancárias, ignorando as redes de cartões e nunca saindo do site ou aplicativo de um comerciante - sem necessidade de números de cartão de crédito ou configuração de conta separada.

Com escritórios em Vitória, Brasil, Vale do Silício nos EUA e sede global em Estocolmo, Suécia, somos uma equipe culturalmente diversificada. Em todo o Brasil, adotamos a política de trabalho remoto em casa.

É um ótimo momento para ingressar na Trustly, pois a equipe das Américas está crescendo rapidamente. Se você prospera em um ambiente de trabalho com espírito empreendedor, ritmo acelerado, casual, profissional, positivo e gratificante, esse é o seu lugar!

## Sobre o time que você trabalhará:

A equipe de Customer Experience é responsável por toda a camada de apresentação da Trustly para nossos clientes. Nosso foco é oferecer a melhor experiência com uma plataforma simples, eficiente e acessível.

## No seu dia a dia, você irá:

- Você trabalhará no desenvolvimento e manutenção de código do lado do cliente para produtos baseados na web usando tecnologias como JavaScript e React.
- Otimizar aplicativos da Web para maximizar a velocidade e a escala.
- Atuação ativa no planejamento de sprints e reuniões de scrum com equipes em Vitória, São Francisco (sede e demais localidades.

## O que esperamos de você:

- Experiência em desenvolvimento/projeto de sistemas de software.
- Compreensão da estética do layout e um impulso para criar experiências de UX pensadas e páginas da Web perfeitas em pixels.
- Excelentes habilidades de codificação em Javascript (ES6), HTML e CSS.
- Especialista em React Framework.
- Excelente habilidade de codificação e compreensão dos conceitos OO.
- Experiência anterior com controle de origem.
- Fortes habilidades escritas e verbais em inglês.

## Local:
Remoto

## Contratação:
CLT

## Como se candidatar:
https://app.careerpuck.com/job-board/trustly/job/a873d32c-0d51-4da2-8a5d-2ac08c4d4316

#### Alocação
Remoto

#### Regime
CLT

#### Nível
Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
