### ISSUE TITLE
[Remoto - Manchester, UK] Front-end Developer na Beit Overseas

### ISSUE THREAD

**Issue by LilianeBeiT** [frontendbr/vagas#7431]
## Nossa empresa

Empresa transformadora de entretenimento, localizada em Londres e com escritório em Nova Iorque, que apoia os produtores da indústria de eventos a venderem diretamente para seus clientes.
Atuando com grandes nomes do mundo do entretenimento, com uma plataforma totalmente personalizável, para cada marca, objetivos e exigências individuais de cada parceiro!
Buscamos um profissional que ajudará a construir a plataforma, as características e as ferramentas necessárias em uma plataforma SaaS.

## Descrição da vaga

**RESPONSABILIDADES E ATRIBUIÇÕES**
- Desenvolver características e melhorias para a plataforma.
- Criação de um código de alta qualidade e desempenho que atenda às melhores práticas para um ambiente web moderno de alta escala.
- Identificar melhorias na base de código e contribuir ativamente para torná-la melhor.
- Colaborar com a equipe em projetos.
- Apoiar os colegas na solução de problemas técnicos de alto escopo e complexidade.
- Implementar experimentos CRO (Testes A/B) em todos os nossos fluxos de compra.

## Local

100% Remoto. Escritório localizado em Londres (Manchester), com eventuais oportunidades de participar de eventos no exterior. 

## Requisitos

**Obrigatórios:**
- Inglês Fluente
- Node (NestJS, Express)
- React
- Typescript

**Desejáveis:**
- State management (Redux & Recoil)
- CSS, & CSS-in-JS (SASS, Emotion, Styled JSX)
- Unit testing (Jest, React Testing Library, Enzyme)
- End-to-end testing (Cypress)
- CI (Github Actions)
- Storybook
- Build tools (Webpack, Babel etc.)
- GraphQL

**Diferenciais:**
- Programação OO
- pixi.js/canvas/webgl

**EXPERIÊNCIAS QUE ACHAMOS PARTICULARMENTE INTERESSANTES:**
- Experiência com grandes bases de códigos complexos
- Manter um projeto de software pessoal e / ou é um contribuinte ativo para o código aberto
- Construir e / ou manter áreas administrativas para colegas não técnicos

**## Benefícios**

- 22 dias de Férias remuneradas 
- Feriados Locais (UK)

**Diferenciais:**

- Atuação em modelo de trabalho flexível, mas seguirá por padrão a jornada de trabalho de Londres: (7h às 15h / 6h às 14h (Horário de verão))
- Remuneração competitiva em Libras
- Bônus - Sobreaviso
- Oportunidade de ir para Londres em eventos exporádicos com tudo pago

## **Contratação**

PJ a combinar

## Como se candidatar

Através deste formulário: https://forms.clickup.com/31110733/f/xndjd-5143/NLVXOQ104XVCSS9ZV1

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: liliane.lima@beitoverseas.com

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

### Stacks
- Typescript
- React
- Node

**Comment by talls2** [comment]
Enviado!

**Comment by celorg** [comment]
Sou desenvolvedor no início de carreira, tive o primeiro contato com programação na faculdade, e criei uma paixão grande pela a área. Estou a procura de se tornar um desenvolvedor full-stack, aprendendo cada dia mais, minhas habilidades são: html, css, figma, wordpress, php e mySql. Meu próximo passo é aprender sobre Laravel e VueJS .

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
