### ISSUE TITLE
[Remoto] Front-end Developer(Angular) na TestGorilla

### ISSUE THREAD

**Issue by eduardo704** [frontendbr/vagas#7434]
## Testgorilla

Na TestGorilla, vislumbramos um mundo onde todos tenham o emprego dos seus sonhos. Para conseguir isso, empregadores e empregados precisam ter as informações corretas uns sobre os outros.

Começamos em 2020 construindo uma plataforma de triagem que permite que os empregadores avaliem os candidatos nas habilidades mais importantes para o sucesso em uma função. Nosso produto substitui CVs subjetivos, incompletos e muitas vezes inflados por resultados de testes objetivos, confiáveis ​​e justos que medem aptidão, habilidades práticas de trabalho, motivação e cultura agregada.

Melhorar e expandir esta plataforma é atualmente nosso foco principal, mas é apenas o começo de nossa jornada para que todos tenham o emprego dos seus sonhos. Com o tempo, lançaremos mais produtos que apoiam essa missão.

Adquirimos US$ 70 milhões em financiamento da Série A das empresas de capital de risco Atomico e Balderton Capital, e nosso crescimento deve continuar exponencialmente. Provavelmente, você conhece alguns de nossos maiores clientes, como Sony, PepsiCo, H&M, Deloitte, Bain & Company, Oracle, Revolut e o Serviço Nacional de Saúde do Reino Unido.

Trabalhamos remotamente, espalhados pelas Américas, Europa, Ásia e África

Exemplo: Projeto bazinga em NodeJS, etc.

## Requisitos

**Obrigatórios:**
- 2 a 5 anos de experiência com Angular2+
Experiência em projetar, implementar, executar e manter código front-end de produção usando estruturas modernas de desenvolvimento do lado do cliente baseadas em JS/TS, como Angular

**Desejáveis:**
você tem experiência em uma empresa baseada em produtos SaaS
você se sente confortável com métodos ágeis, como Extreme Programming (XP), Scrum e/ou Kanban
você tem um conhecimento prático da tecnologia de nuvem, como AWS, Azure, Kubernetes e Docker

**Diferenciais:**
Salário competitivo incl. bônus e opções de ações
Horários flexíveis e férias
licença parental remunerada
Orçamento de trabalho remoto de € 1000 por ano
3,5% do orçamento de aprendizagem e desenvolvimento do salário base
## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para eduardo@testgorilla.com com seu CV anexado - enviar no assunto: Vaga Angular ou Vaga Angular Sr depedendo da sua experiencia.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias uteis após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ - gringo

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
