### ISSUE TITLE
[Remoto] Front-end Developer na uCondo

### ISSUE THREAD

**Issue by akarenaline** [frontendbr/vagas#7436]
## uCondo
Somos uma startup com um sonho grande: o de tornar todos os condomínios inteligentes! A uCondo existe porque a comunicação dos condomínios é precária e desorganizada, administradoras de condomínios possuem processos burocráticos, caros e demorados. Nosso propósito é proporcionar economia e comodidade para administradoras, pessoas síndicas e moradoras, nos tornando assim, o melhor e maior App de condomínios das Américas! 💜

## Descrição da vaga
● Desenvolver funcionalidades no ambiente web e mobile;
● Corrigir pequenos bugs;
● Fazer code review das entregas realizadas pelos demais desenvolvedores;
● Prestar suporte do produto aos demais times da empresa;
● Desenvolver códigos limpos, de fácil entendimento e manutenção;
● Criar e manter testes automatizados e de integração;
● Colaborar com a prototipação de novas funcionalidades junto ao Product Owner e ao Product
Designer da sua Squad.

100% Remoto 

## Requisitos
● Sólidos conhecimentos em Javascript;
● Sólida habilidade em desenvolvimento mobile (Android e iOS);
● Conhecimentos avançados em React Native e React Js;
● Sólidos conhecimentos em Git;
● Habilidade em métodos ágeis (SCRUM);
● Conhecimento em testes automatizados (Detox e Cypress);
● Conhecimento em GraphQL client e server (Apollo);
● Conhecimento total dos ciclos de um app (concepção, desenvolvimento e publicação nas
stores).

**Diferenciais:**
● Gestão de ambientes em nuvem AWS;
● Experiência em Startup SaaS ou empresas de tecnologia;
● Experiência profissional no ramo de condomínios, ERPs ou fintechs;
● Conhecimentos em outras tecnologias como C#, Java, etc.

## Benefícios
💰 Salário Base inicial de R$ 8.000 a R$ 10.000 CLT
🍔 VA da Flash de R$ 480,00 por mês sem descontos!
💻 Equipamentos e auxílio Home Office de R$50,00 por mês
🩺 Plano de Saúde Bradesco Nacional sem coparticipação!
😁 Plano Odontológico Bradesco sem coparticipação!
💜 Seguro de Vida sem coparticipação!
🚀 Treinamento e plano de carreira
🕑 Horário de trabalho: segunda à sexta das 09:00h às 18:00h - 100% remoto

## Contratação
CLT

## Como se candidatar
https://www.ucondo.com.br/vagas

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até no máximo 7 dias úteis após cada processo.
E-mail para contato em caso de não haver resposta: karen.souza@ucondo.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by cpt-westphalen** [comment]
Que interessante foco da startup! Estarei de olho para quando houver vaga júnior.

**Comment by lucasferreiralimax** [comment]
Muito legal a entrevista com a @akarenaline uma pessoa super gentil e acolheradora, acredito que conversando pode ter oportunidades para ti @cpt-westphalen

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
