### ISSUE TITLE
Front-end Developer EstrelaBet

### ISSUE THREAD

**Issue by RhEstrelaBet** [frontendbr/vagas#7437]
Nossa Empresa:

Somos uma empresa de apostas esportivas e entretenimento. Acreditamos nas pessoas e trabalhamos para impulsionar nosso negócio. Estamos à procura de um(a) Desenvolvedor Front-End para completar o nosso time de Estrelas! 🚀

Descrição da vaga:

Participar ativamente na concepção da solução técnica para as necessidades de negócio junto ao time;construir soluções com integração contínua, desenvolvimento orientado a testes, técnicas de modelagem, pair programming, mob programming e afins;

Local de Trabalho:
Homeoffice

Requisitos:
-Proficiência em React e/ou Vue
-Fortes conhecimentos em HTML, CSS e principalmente JavaScript.
-Amplo conhecimento de integração do Front com APIs / microserviços;
-Implementação de layout Web/Mobile Responsivo;
-Conhecimento consolidado com implementação de testes;
-Conhecimento de Gitflow

Contratação: PJ
Como se candidatar: Candidata-se através do link https://estrelabet.solides.jobs/ ou se preferir pode nos enviar um e-mail [rhestrelabet@gmail.com](mailto:rhestrelabet@gmail.com) com o assunto " Desenvolvedor Front-End" com o link do seu  Git 😉

Nível:
Pleno
Sênior
Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
