### ISSUE TITLE
[Remoto] Full Stack Sênior Developer - Growth Tech

### ISSUE THREAD

**Issue by workstein** [frontendbr/vagas#7442]
## Nossa empresa

Somos uma Startup que desenvolve soluções para automação inteligente e desintermediação de processos, através de Smart Contracts e da tecnologia Blockchain. Contribuímos com diversas empresas na otimização de processos, aumento de produtividade, eliminação de intermediários, agilizando seus negócios e criando iniciativas e parcerias mais eficientes.

## Descrição da vaga

Desenvolvedor Full-stack Sênior/Especialista. 
Você irá trabalhar com bases de dados existentes e também construir novas soluções.

## Local

100% remoto, trabalhe de qualquer lugar.

## Requisitos

Requeridos:
    •  Mínimo de 5+ anos de experiência em desenvolvimento de software;
    •  Ter desenvolvido RESTful APIs, fluxos de server-side e client side;
    •  Conhecimento avançado em Javascript, Typescript, Node.JS, React.JS, SQL (PostgreSQL);
    •  Desenvolvimento voltado a teste (Unit tests, integration tests e e2e);
    •  Capacidade de arquitetar e projetar sistemas modulares (microsserviços, arquiteturas orientadas a eventos, padrões de resiliência)
    •  Familiaridade com Containers, Virtualização e Kubernetes.
    •  Mensageria com RabbitMQ;
    •  Familiaridade com CI/CD;
    •  Gerenciamento da infraestrutura no serviços AWS
    •  Proatividade, organização e boa comunicação.

Desejáveis:
    •  Blockchain Ethereum, Polygon e Hyperledger (ou vontade de aprender)
    •  Next.JS
    •  Nest.JS

## Contratação

Contrato PJ (40h/semana) – Longo prazo
Férias remuneradas

## Remuneração
R$ 15.000 - R$ 19.000

## Como se candidatar

Envie um email para hugopierre@growthtech.com.br com seu CV anexado - enviar no assunto: Vaga Full-Stack Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
