### ISSUE TITLE
[Remoto] Frontend UX Designer na Coodesh

### ISSUE THREAD

**Issue by blankapf** [frontendbr/vagas#7443]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/ux-user-experience-front-end-201129797?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>O <strong>Grupo Fácil</strong> busca <strong><ins>Frontend UX Designer</ins></strong> para compor seu time de desenvolvimento do NOVO PRODUTO!</p>
<p>Terá como missão se unir ao nosso time do NOVO PRODUTO, atuando desde a concepção e coleta de requisitos, até o projeto em desenvolvimento. A pessoa UX Designer será responsável por levantar definições com área cliente, mapear a User Jorney e propor o design das aplicações com as melhores práticas UX.&nbsp;</p>
<p><strong>RESPONSABILIDADES E ATRIBUIÇÕES:</strong></p>
<ul>
<li>Conduzir atividades de ideação de produtos digitais, como Lean Inception, Ux Research, entrevistas com usuários e stakeholders, levantamento de funcionalidades, desenho de roadmaps, dentre outros;</li>
<li>Criar protótipos navegáveis complexos, com vários fluxos e interações;</li>
<li>Conduzir, moderar e observar testes de usabilidade com usuários, dentre outros estudos para compreender suas necessidades;</li>
<li>Coletar dados e métricas de produto e usabilidade para os projetos que desenvolvemos;</li>
<li>Ajudar a aprimorar e manter nosso sistema de design, reforçando o bom uso do NOVO PRODUTO;</li>
<li>Documentar as decisões, regras de negócio e fluxos dos produtos;</li>
<li>Repassar aos desenvolvedores o que deve ser implementado fornecendo as informações sobre o fluxo, demanda, produto etc.</li>
</ul>

## Grupo Fácil: 
 <p>Ao longo de 27 anos de história, o Grupo Fácil se tornou referência nacional em sistemas, softwares e serviços para a gestão de negócios nas áreas financeira e de crédito, da saúde e no setor imobiliário.</p>
<p>O Grupo Fácil é formado por um conjunto de empresas que se destacam pela solidez e ousadia em projetos que otimizam processos e oferecem mais segurança e rentabilidade para seus clientes.&nbsp;</p><a href='https://coodesh.com/empresas/grupo-facil'>Veja mais no site</a>

 ## Habilidades: 
 - Design de Front-End 
- Front-end System Design 
- Core Java
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência com um desses softwares: Sketch, Figma, Invision Studio, Illustrator, Photoshop (ou outro relevante); 
- Capacidade de empatia e compreensão dos desafios do usuário para projetar soluções centradas no usuário; 
- Experiência em produtos digitais, plataformas, web/mobile; 
- Bom entendimento de Experiência do Usuário, design centrado no usuário e Web Design responsivo; 
- Capacidade de criar simples, eficazes e envolventes web gráficos; 
- Boa compreensão de Brand Guidelines e princípios de design; 
- Conhecimento de um Framework Javascript; 
- Sólida experiência na atuação em frontend; 
- Ter grande domínio das ferramentas de criação e prototipação de interfaces; 
- Possuir boa didática para ensinar conceitos e oferecer direcionamentos técnicos para a equipe.
## Diferenciais: 
 - Experiência em operadoras de saúde; 
- Inglês avançado ou fluente; 
- Experiência em metodologias ágeis.
## Benefícios: 
 - Assistência Médica e odontológica; 
- Convênio com farmácia; 
- Participação nos lucros; 
- Vale refeição; 
- Vale transporte; 
- Parcerias e convênios; 
- Programas de saúde e bem-estar.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend UX Designer na Grupo Fácil](https://coodesh.com/vagas/ux-user-experience-front-end-201129797?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Categoria
Design/UX

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
