### ISSUE TITLE
[Remoto] Full Stack Developer React/Node na TRACTIAN

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#7446]
## Nossa empresa

A Tractian está reinventando os sistemas industriais para que cada trabalhador da linha de frente possa realizar todo o seu potencial. Como o sistema operacional industrial, estamos construindo software e hardware em um só lugar, interrompendo instituições há muito enraizadas com produtos e experiências que atendem melhor às ambições de nossos clientes.

## Descrição da vaga

Como Full Stack Developer React/Node, você será responsável pela entrega completa do desenvolvimento e manutenção de sistemas de ponta a ponta em plataformas de tecnologia médias de toda a empresa. Seu desafio será cruzar constantemente nossa pilha, Frente e Verso, ao longo do desenvolvimento do produto. O candidato certo será um indivíduo altamente motivado com a capacidade de trabalhar de forma autônoma. Responsabilidades:

- Responsável por codificar e desenvolver aplicativos usando React JS e Node JS
- Responsável pela programação em subconjuntos de aplicativos do portfólio de aplicativos da empresa, participando de todas as fases dos ciclos de vida de desenvolvimento e manutenção
- Arquitetar, construir e mantenha excelente React JS
- Traduzir requisitos funcionais em especificações técnicas e realizar desenvolvimento prático e testes de unidade
- Realizar o design técnico e as revisões de código para manter o software seguro e de alta qualidade
- Preparar a documentação técnica do projeto

## Local

Remoto

## Requisitos

- Mais de 2 anos de experiência com desenvolvimento Full-Stack
- Mais de 2 anos participando de desenvolvimento de API e Web Services (REST)
- Integrar APIs de terceiros
- Proximidade prévia a bancos de dados relacionais e não relacionais

## Benefícios

- Salário competitivo e opções de ações
- R$ 800/mês para uso em diversos locais que aceitam bandeira Visa
- GymPass para não ficar sentado/trabalhando o dia todo
- Curso de inglês/espanhol 100% financiado
- 30 dias de férias anuais remuneradas
- Bolsa de estudos e cursos
- A cada 3 anos, ganhe uma viagem para qualquer lugar do mundo
- Dia de folga na semana do seu aniversário
- A partir de R$ 2.400/ano subsídio de trabalho remoto
- Apoio à saúde mental: cobrimos 40% do custo da sua terapia
- Plano de saúde com cobertura nacional e sem coparticipação.
- Seguro Odontológico: ajudamos você no tratamento odontológico para uma melhor qualidade de vida.
- Incentivo ao Esporte: R$ 300/mês extra se você praticar atividades

## Contratação

CLT

## Como se candidatar

Clique [aqui](https://remotar.com.br/job/3171/tractian/full-stack-developer-reactnode?utm_source=github) para saber mais

OBS: a TRACTIAN é cliente da Remotar. Ao clicar no link acima você será redirecionado para nosso site, mas todo o processo seletivo ficará sob responsabilidade da TRACTIAN. 

### Nível

- Pleno
- Sênior

### Regime

- CLT

### Alocação

- Remoto

**Comment by deyvisonborges** [comment]
Opa, gostei da oportunidade.
Pode analisar meu github por aqui mesmo.
Meu linkedin: https://www.linkedin.com/in/deyvisonborges/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
