### ISSUE TITLE
[Brasília] Front-end/Full-stack Developer no IPAM Amazônia

### ISSUE THREAD

**Issue by gamoridev** [frontendbr/vagas#745]
## Descrição da vaga

Apoiar no desenvolvimento de plataformas de mapas na Web para disponibilizar informações espaciais, relatórios e gráficos e, resolver questões relacionadas ao WordPress. Além de desenvolver formulários para coleta de dados (tanto online, quanto offline) para estudo e uso nas plataformas.

## Local

Escritório, Lago norte - Brasília, DF

## Benefícios
- Seguro de vida
- Auxílio transporte
- Recesso no fim do ano

#### Diferenciais

- Horário flexível
- Aulas e cursos de novas tecnologias envolvendo toda a equipe

## Requisitos

**Obrigatórios:**
- Experiência em JavaScript, PHP, HTML5, CSS3 e SQL – PostgreSQL/PostGIS
- Experiência com Git
- Facilidade de aprendizado de novas ferramentas de desenvolvimento e outras tecnologias

**Desejáveis:**
- Metodologias ágeis
- Conhecimento em desenvolvimento de aplicativos
- Conhecimento das bibliotecas (OpenLayers, Google Maps, Bootstrap, Material, JQuery, d3.js e Chart.js)
 
**Diferenciais:**
- Conhecimento de React, React Native, MapServer, Angular 2/4 e CodeIgniter
- Participação na comunidade Open-Source

## Contratação

Estágio - 30h Semanais, VT.

## Nossa empresa

O Instituto de Pesquisa Ambiental da Amazônia (IPAM – www.ipam.org.br) é uma organização científica, não governamental, e sem fins lucrativos, que há mais de 20 anos trabalha pelo desenvolvimento sustentável da Amazônia, de modo a gerar prosperidade econômica e justiça social, ao mesmo tempo conservar a integridade dos ecossistemas.

## Como se candidatar

Por favor, envie um e-mail para curriculo@ipam.org.br com seu CV anexado até 30/01/2018, com o Assunto “Estágio-GT-BSB”.

**Comment by fejaum** [comment]
Estágio...

Se o cara souber do que está em Obrigatório e Desejável ele não é estagiário faz um tempo já...

**Comment by LFeh** [comment]
Concordo @fejaum

**Comment by gamoridev** [comment]
@fejaum, demonstrando conhecimento básico e interesse em aprender o que foi citado já é válido.
