### ISSUE TITLE
[remoto] Front-end Developer na Beesweb - Sistema para provedores

### ISSUE THREAD

**Issue by Estaeloliveira** [frontendbr/vagas#7452]
> Vaga Remota durante a pandemia

## Nossa empresa

Somos uma empresa já consolidada no mercado e em constante desenvolvimento. 

## Descrição da vaga

Trabalhar em resolução de bug's e desenvolvimento de recursos junto a equipe.

## Local

Trabalho remoto no conforto de sua casa.

## Requisitos

**Obrigatórios:**

Fator eliminatório se não souber desenvolver nestas línguagens.
 
- PHP ( laravel ) , 
- MySQL, 
- HTML, 
- CSS, 
- Javascript,
- Bootstrap

**Desejáveis:**
- conhecimentos em ruby on rails
- conhecimentos em C#

**Diferenciais:**
- Ter feitos projetos de desenvolvimento de software.

## Benefícios

- A combinar

**Diferenciais:**
- Trabalhar durante 8 horas e sob demanda.

## Contratação

A combinar

## Como se candidatar

Por favor envie um email para estael@beesweb.com.br com seu CV anexado - enviar no assunto: Vaga Developer.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após o envio do CV.
E-mail para contato em caso de não haver resposta: estaeloliveira@live.com

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by kallebenunes** [comment]
PHP não é front-end

**Comment by cauemustafa** [comment]
vaga full stack

**Comment by ionansantos** [comment]
Enviado

**Comment by AlissonSampaio** [comment]
Como um framework Back-end é eliminatório para uma vaga de Front-end?

**Comment by RicarGit** [comment]
Famosa vaga FullStack disfarçada de Front pra pagar menos kk

**Comment by papelgold** [comment]
Enviado!

**Comment by DarlanSantosCarvalho** [comment]
[Darlan Carvalho.pdf](https://github.com/frontendbr/vagas/files/10495017/Darlan.Carvalho.pdf)
Currículo enviado

**Comment by evertton** [comment]
> PHP não é front-end

Os caras podem fazer aqueles códigos PHTML para o Front-end. Hahha

**Comment by PedroRavaglia** [comment]
Enviado

**Comment by FeRiffo** [comment]
Enviado!

**Comment by Virkkunen** [comment]
Enviado

**Comment by Rafaeldfb** [comment]
Laravel é framework 'Fullstack', já que tem o Blade template eng.

**Comment by BLACKOUTxy** [comment]
POV: A empresa tenta desfarçar a vaga fullstack de Frontend pra pagar menos😂

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by eudevedu** [comment]
Enviado!

**Comment by gitsena** [comment]
Enviado 😁
