### ISSUE TITLE
[100% Remoto] Front-end Developer na Hypesoft

### ISSUE THREAD

**Issue by Gabihype** [frontendbr/vagas#7453]
> 

## Descrição da vaga

A vaga é para atuar em uma das maiores corretoras de criptoativos do Brasil, atuando como Desenvolvedor Front End para projetos relacionados ao mercado de criptoativos com as seguintes experiências

## Local

100% Remoto

## Requisitos

Experiência de no mínimo 5 anos como desenvolvedor/engenheiro de software frontend;
Princípios básicos de segurança da informação no desenvolvimento de software;
Sólidos conhecimentos em Design Patterns, metodologias e boas práticas, tais como:
         Desenvolvimento de interfaces web;
         Interfaces responsivas;
         Javascript/ Typescript
         HTML, Semântica e Acessibilidade
         CSS, CSS Modules
          Reactjs, Vuejs ou bibliotecas similares
          Nextjs ou frameworks similares
          Testes unitários/integração e end-to-end
          Bundlers webpack, rollup, vite e similares
          Programação assíncrona;
          Processos automatizados de CI/CD;

**Desejáveis:**
   Otimizações de performance e carregamento
         Banco de Dados Relacionais/Não relacionais, Redis;
         Capacidade de gerar código de alta qualidade, bem testado e seguindo boas práticas de desenvolvimento e segurança;
         Sólidos conhecimentos em Design Patterns, metodologias e boas práticas, tais como:
         SOLID Principle;
         Code Review;
         Desenvolvimento Agile (Scrum / Kanban);
         Código legível e claro;
         Desenvolvimento com foco voltado ao produto e cliente;

**Diferenciais:**
Experiência com Reactjs + Styled Components + Storybook;
Experiência com Design Systems;
Nextjs;
Jest + Cypress;
Google Analytics/Métricas;
APIs REST, GraphqQL e Web Sockets;
Outras linguagens como Python, Ruby ou Elixir;
Linux (terminal)
Experiência com Mercado financeiro e/ou criptomoedas; Blockchain e/ou Smart Contracts

## Benefícios

Plano de saúde SulAmérica ou Unimed com dependentes (desconto no salário somente em caso de upgrade) 
Plano odontológico SulAmérica com dependentes (desconto no salário somente em caso de upgrade); 
Seguro de vida Prudential (sem desconto no salário); 
Cartão VEE - R$800,00 (R$700,00 VR/VA e R$100,00 
flexível na divisão e sem desconto); Auxílio HomeOffice - R$250,00; 
Incentivo aprendizado (workshops, cursos, idioma, entre outros) com análise prévia e somente após 3 meses de empresa; 
Crédito consignado somente após 3 meses de empresa (limite de acordo com o salário e o valor da parcela não pode ultrapassar 25% do salário); 
1 Day Off na semana do seu aniversário; 
Descontos na taxa de trade. Yay!; 
Crédito de R$ 200,00 para testar a plataforma; 
Programa de indicação de colaboradores.

## Contratação

CLT + Benefícios

## Como se candidatar

Por favor envie um email para Gabriella.araujo@hypesoft.com.br com seu CV anexado - enviar no assunto: Vaga FRONTEND

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível

- Pleno/Sênior

**Comment by iamrosada** [comment]
Está vazio

**Comment by Gabihype** [comment]
> #### Alocação
> * Remoto
> 
> #### Regime
> * CLT
> 
> #### Nível
> * Pleno/Sênior



> Está vazio

**Comment by Gabihype** [comment]
> Está vazio

Obrigada Iam, alterei aqui

**Comment by iamrosada** [comment]
@Gabihype  uma pergunta, o Pleno também deve ser 5 anos de experiencia?

**Comment by Gabihype** [comment]
> @Gabihype uma pergunta, o Pleno também deve ser 5 anos de experiencia?

Iam, a posição é para um nivel PL/SR. 
O Cliente nos pediu um perfil que tenha 5 anos +

**Comment by iamrosada** [comment]
tenho 2 anos, e a unica coisa que não tenho conhecimento e experiencia é ``Experiência com Mercado financeiro e/ou criptomoedas; Blockchain e/ou Smart Contracts``

**Comment by iamrosada** [comment]
Muito obrigado pela resposta.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
