### ISSUE TITLE
[São Paulo] Front-end Developer na Alana.ai

### ISSUE THREAD

**Issue by guilherme-cscordeiro** [frontendbr/vagas#7455]
> Vaga Remota

## Nossa empresa

We are a global startup focused on AI applied to Marketing and CX. We currently have operations in the US, Brazil, and Europe. Even in beta, we worked with major brands, such as Netflix, Coke, Spotify, Oreo, Philips, Lenovo, and many others. Our main product is the ALANA platform, the best AI platform made exclusively for the marketing industry. In the past, we were accelerated by Oracle globally and still are Intel AI Builders partners. ALANA's cognition engine leverages start-of-the-art Natural Language Processing and prediction models. ALANA can map vast amounts of consumers throughout online channels and autonomously interact using advanced natural language algorithms. Lastly, we received two rounds of investments from global venture capital funds to further expand our operations.

## Descrição da vaga

- Write well-designed, testable code
- Create reusable and modularized components
- Integrate web components into a fully functional web system
- Document and maintain software functionality
- Troubleshoot, debug and upgrade existing systems
- Work alongside other engineers on the team to elevate technology and consistently apply best practices
- Work alongside the Interface team

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Node
- 2 anos de experiência com mongodb e express

**Desejáveis:**
- You are fluent in JavaScript and TypeScript
- You have experience with Vue.js 2 and 3
- You have experience with component-oriented programming
- You have experience with Cucumber or other BDD Tests tools
- You are in the habit of documenting and testing
- You are familiar with version control
- You are organized, focused and results-oriented

**Diferenciais:**
- Familiarity with creating components libraries
- Familiarity with CSS preprocessors (SASS preferentially)

## Benefícios

- Competitive salary
- Multicultural teams with engaged leaders
- Access to courses and books paid for by the company
- Eligible to earn stock options

**Diferenciais:**
- Work alongside world-class machine learning and AI
- Flexible & remote work

## Contratação

PJ

## Como se candidatar

Por favor, aplique pelo linkedin: https://www.linkedin.com/jobs/view/3315950823/?refId=R1IrnlqnS0eVzAKLZAd6Dg%3D%3D

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 14 dias após cada processo.
E-mail para contato em caso de não haver resposta: guilherme.cordeiro@alana.ai

#### Alocação

- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
