### ISSUE TITLE
[Desenvolvedor Frontend ReactJS Sênior] - Remoto na Hunter Hunter

### ISSUE THREAD

**Issue by ErickaMB** [frontendbr/vagas#7458]
[Desenvolvedor Frontend ReactJS Sênior] - Remoto. PJ entre 15 mil a 20 mil negociável. Empresa Canadense. Inglês avançado.

Mandatório:

- Mais de 5 anos de desenvolvimento e 3 com ReactJS.
- Inglês avançado e para conversação.

Se tiver com https://strapi.io/ é um plus.

Se tem interesse e com requisitos da oportunidade entre em contato pelo Linkedin informando qual é a oportunidade. [https://www.linkedin.com/in/erickamarquesb/]

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
