### ISSUE TITLE
[100% REMOTO] OutSystems Analyst Safety na TRUPPE!

### ISSUE THREAD

**Issue by Camila-Goms** [frontendbr/vagas#7459]
**A empresa:**

A [Trupppe!](https://truppe.team/) é uma empresa de consultoria de tecnologia com foco em desenvolver e aprimorar talentos referência em recrutamento, seleção e alocação de profissionais de TI. Criada há 3 anos, está em fase de desenvolvimento e crescimento, expandindo seu portfólio de produtos e serviços, trabalhando também com transformação e aceleração digital. 

**Descrição da vaga:**

Buscamos uma pessoa para atuar como ANALISTA OUTSYSTEMS (SEGURANÇA) para Projeto Agile de Outsystems no time de uma consultoria reconhecida como referência de excelência em desenvolvimento de software.
 

**Responsabilidades e Atribuições:**

• Prover especialidade em Desenvolvimento de Código Seguro sendo, portanto, responsável por impedir que riscos sejam transportados para ambiente produtivo. Para tanto deverá interagir com os demais membros do system team incluindo os portões de avaliação de segurança estática e dinâmica;

• Este especialista deverá interagir com a área de Segurança da Informação do Cliente alinhando as políticas e práticas, solicitando aprovação de falsos positivos e corrigindo os riscos identificados;

• Deverá, em conjunto com a Segurança da Informação ajudar a desenvolver a estrutura de Security Champions dentro dos ARTs;

• Deverá, auxiliar os times ágeis do ART implementando segurança desde o design, auxiliando no entendimento das vulnerabilidades e divulgando as técnicas necessárias pela execução;

• Poderá assumir tasks do time ágil para implementações especializadas;

• Deverá estar disponível para atuar em sala de crise para tratamento de incidentes de segurança.

**Nível**

PLENO

**Local:**

100% Remoto.

**Requisitos:**

• Deve apresentar certificação técnica OutSystems;

• Experiência profissional mínima comprovada de 1 (um) ano de atuação no mercado de trabalho, especificamente com plataforma OutSystems;

• Experiência comprovada em gestão da Qualidade ou Segurança do ambiente OutSystems;

• Ter um bom relacionamento interpessoal, comunicação verbal e escrita, capacidade analítica e criativa na solução de problemas;

• Graduação completa em curso de nível superior na área de Tecnologia da Informação, ou conclusão de qualquer curso de nível superior acompanhado de certificado de pós-graduação (especialização, mestrado ou doutorado) na área de Tecnologia da Informação de, no mínimo, 360 horas.

**Contratação**

CLT - Pretensão Salarial a combinar.

**Como se candidatar**

Por favor, envie um email para *camila.gomes@truppe.team* com seu CV atualizado anexado, link do perfil do Linkedin (se utilizar) e pretensão salarial CLT no corpo do email.

Enviar no assunto: **Vaga OutSystems Analyst**

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
