### ISSUE TITLE
[Remoto] Frontend Developer (ReactJS/TypeScript) na Coodesh

### ISSUE THREAD

**Issue by blankapf** [frontendbr/vagas#7462]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-frontend-214750828?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>Blank</strong> está buscando <strong><ins>Frontend Developer</ins></strong> (ReactJS/TypeScript) para fazer parte do seu time!</p>
<p>Procuramos alguém com propósito forte e que esteja disposta a trabalhar em ambiente colaborativo e dinâmico, pronto para crescer profissionalmente junto com a empresa! A Blank gosta de entregar grandes projetos e fazer a diferença.</p>
<p></p>
<p><strong>Responsabilidades:</strong></p>
<ul>
<li>Desenvolver códigos seguindo recomendações;</li>
<li>Realizar correção de bugs;</li>
<li>Prezar pela qualidade dos códigos;</li>
<li>Code review.</li>
</ul>

## Blank: 
 <p>Nós somos a Blank Internet Studio, uma produtora web especializada em soluções digitais utilizando os métodos e tecnologias mais recentes do mercado.</p>
<p>Trabalhamos com Desenvolvimento Web e produção web de alto valor agregado, Branding e criação de estratégias para dar forma à sua marca, criação de Aplicativos e desenvolvimento de novas interfaces digitais e interações móveis e design, proporcionando a melhor experiência de navegação para o usuário, através do design funcional.</p><a href='https://coodesh.com/empresas/blank'>Veja mais no site</a>

 ## Habilidades: 
 - Javascript 
- Typescript 
- React.js 
- React Native
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência sólida no desenvolvimento web; 
- Experiência em aplicações de alta disponibilidade.
## Diferenciais: 
 - Conhecimentos em React Native.

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Developer (ReactJS/TypeScript) na Blank](https://coodesh.com/vagas/desenvolvedor-frontend-214750828?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
