### ISSUE TITLE
[Remoto] Front-end Angular na MasterTax

### ISSUE THREAD

**Issue by curruwilla** [frontendbr/vagas#7463]
## Descrição da vaga
Buscamos um Programador (a) FRONTEND - ANGULAR, para atuar em projetos de desenvolvimento com a missão de projetar, construir e otimizar interfaces do sistema utilizando metodologias de mercado. 
Deverá ter Perfil Analítico, sendo Proativo e Focado. Facilidade de comunicação e bom relacionamento com vários times de trabalho. 

## Requisitos
**Obrigatórios:**
• Conhecimentos profundos em ANGULAR 
• Geradores de CSS (SASS)
• Conceitos de API, HTML 
• Metodologia em MVC, GIT 
• JQuery / Bootstrap / JavaSript 
• Banco de dados MySQL 

**Desejável:**
• Bacharel em ciências da computação ou áreas afins
• 3 anos ou mais de experiência em desenvolvimento web
• Proficiência com Angular é uma qualidade primordial
• Vasto conhecimento de ferramentas de desenvolvimento web para sistemas modelo SaaS e linguagens de programação entre elas PHP

**Principais atividades:** 
• Desejável habilidade com regras de negócios Fiscais / Tributárias ou ERP´s da área Contábil ou Financeira
• Analisar e diagnosticar problemas nos programas existentes 
• Manutenção das bases de dados 
• Realizar testes em ambientes simulados através de testes manuais e/ou automatizados de forma a garantir o correto funcionamento do software com base nos requisitos.

## Contratação
PJ a combinar

## Como se candidatar
Para mais informações entre em contato via **linkedin:** https://www.linkedin.com/in/vivian-luna/

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 1 dias após cada processo.
E-mail para contato em caso de não haver resposta: vagas@mastertax.com.br

## Labels
- Horário comercial
- Remoto
- Pleno e Sênior
- Angular

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by curruwilla** [comment]
> Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

Ainda está aberta sim.. inclusive faltou adicionar algumas labels na issue.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
