### ISSUE TITLE
[Híbrido - São Paulo] Front-end Developer Júnior - React Native na Icon It

### ISSUE THREAD

**Issue by Thamme1** [frontendbr/vagas#7465]
## Descrição da vaga

**Atividades a Serem Desempenhadas:**
• Análise e desenvolvimento de Sistemas em React Native com SQL Lite;
• Interação com analistas de requisitos para definição de escopo / análise.
• Realização de Testes dos Recursos Desenvolvidos;

## Local

Exemplo: Híbrido em Pinheiros-SP

## Requisitos

**Obrigatórios:**
• Experiência na aplicação dos conceitos de POO (programação orientada o objetos);
• Conhecimentos na linguagem JavaScript com React Native;
• Conhecimentos para consumo de WebServices e APIs (SOAP e REST);
• Conhecimentos nas bibliotecas das ferramentas GoogleMaps;
• Conhecimentos no uso do banco de dados SQL Lite;

## Benefícios

- Plano de saúde
- VR de R$ 30/dia
- VT

## Contratação

CLT

## Como se candidatar

Por favor envie um email para thamires.camacho@iconit.com.br com seu CV anexado - enviar no assunto: Vaga REACT NATIVE JR

#### Alocação
-Híbrido

#### Regime
- CLT

#### Nível
- Júnior

**Comment by melegao** [comment]
Enviado

**Comment by leandro-carlos** [comment]
Enviado!

**Comment by reita009** [comment]
Enviado!

**Comment by reita009** [comment]
Enviado

**Comment by ionansantos** [comment]
Enviado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
