### ISSUE TITLE
[Remoto] Cloud Developer (Frontend) Sênior na Coodesh

### ISSUE THREAD

**Issue by blankapf** [frontendbr/vagas#7469]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/vaga-desenvolvedor-cloud-frontend-senior-141746651?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>KLB GROUP BRASIL</strong> está buscando <strong><ins>Cloud Developer (frontend) Sênior</ins></strong> para compor sua equipe</p>
<p></p>
<p>A KLB Group é especializada na implementação de projetos em empresas públicas e privadas. Seja em projetos de desenvolvimento, produção ou transformação, a KLB Group assegura a implementação eficaz, mobilizando rapidamente uma equipe de especialistas de várias funções (compras, cadeia de suprimentos, qualidade, engenharia, TI, finanças, etc.), com uma combinação única de experiência em design, implementação e operação. A KLB Group tem mais de 500 funcionários na Europa, América e Ásia.</p>
<p></p>
<p><strong>Escopo</strong>: será detalhado em entrevista técnica.</p>

## KLB GROUP BRASIL : 
 <p>A KLB Group é especializada na implementação de projetos em empresas públicas e privadas. Seja em projetos de desenvolvimento, produção ou transformação, a KLB Group assegura a implementação eficaz, mobilizando rapidamente uma equipe de especialistas de várias funções (compras, cadeia de suprimentos, qualidade, engenharia, TI, finanças, etc.), com uma combinação única de experiência em design, implementação e operação. A KLB Group tem mais de 500 funcionários na Europa, América e Ásia.</p>
</p>

 ## Habilidades: 
 - Design de Front-End 
- AWS CloudFront 
- Cloud Functions
## Local: 
 100% Remoto
## Requisitos: 
 - Front End – obrigatório; 
- Base em orientação a objetos e algoritmos; 
- Bancos de dados: MySql, Postgres, Oracle, Db2, NoSql (Dynamo / Mongo); 
- Conhecimento em sistema operacional Linux; 
- Linguagens e frameworks: Typescript, NodeJS, NestJS, React, ReactNative, Java, Spring; 
- Experiência Modelagem, Documentação e implementação de APIs REST; 
- Facilidade em integração de APIs REST e SOAP; 
- Conhecimento de mercado em fintech: meios de pagamento, análise de fraude, sistemas de conciliação; 
- Experiência em Cloud Computing, principalmente AWS; 
- Versionamento de código (Github).
## Diferenciais: 
 - Conhecimentos avançados em AWS: EC2, S3, VPC, RDS, Route53, Domains, SES, SNS; 
- ELK stack; 
- NGINX; 
- Conhecimentos em CI/CD; 
- Construção de pipelines; 
- Github actions; 
- Conhecimento em Keycloak; 
- Conhecimento em Docker, Docker-swarm e Kubernet.

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Cloud Developer (Frontend) Sênior na KLB GROUP BRASIL ](https://coodesh.com/vagas/vaga-desenvolvedor-cloud-frontend-senior-141746651?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
