### ISSUE TITLE
[Engenheiro de Software Front-end (React/Tailwind)]  - Remoto - Inglês avançado - Hunter Hunter

### ISSUE THREAD

**Issue by ErickaMB** [frontendbr/vagas#7470]
[Engenheiro de Software Front-end (React/Tailwind)] - Remoto - Inglês avançado - Salário USD.

Requisitos:
Mais de 5 anos de experiência na construção de pilhas de front-end
Mais de 5 anos de experiência com JavaScript
Mais de 3 anos de experiência com React
Mais de 3 anos de experiência com deploying applications
Mais de 3 anos de experiência com API
Mais de 2 anos de experiência Git
Bom entendimento dos princípios de Arquiteturas Web
Experiência com Tailwind CSS e ReactJS
Sólidos conhecimentos de HTML, CSS, JS, TS (Java, PHP, SQL bom ter)
Capacidade de trabalhar com UX/UI Designer e implementar designs de alta fidelidade
Familiarizado com princípios de teste e execução de teste (manual e automatizado)
Familiarizado com o Jira para gerenciar o trabalho
Licenciatura/Mestrado na área de estudo apropriada (Ciência da Computação, Engenharia de Software).

O que você vai fazer:
Produza, mantenha e modifique aplicativos da web com interfaces de usuário de modem
Incorpore aplicativos, gráficos e mídia moderna
Garanta que os aplicativos da web sejam acessíveis em muitos navegadores e plataformas, incluindo laptops e smartphones
Teste rotineiramente o aplicativo da web para facilidade de uso, velocidade e outros fatores de qualidade
Corrija quaisquer problemas ou bugs do site que surgirem
Suporte ao PM e Desenvolvedor Sênior durante a definição e execução de testes de sistema e usuário.

Nosso Processo de Recrutamento:
Cheque Inglês (4min)
Entrevista de Triagem (40min) - Apresentação em trio e perguntas gerais sobre sua carreira.
Validação técnica - submissão do projeto
Team Interview (1hr) - Entrevista estruturada relacionada com a cultura da nossa empresa. Algumas questões técnicas relacionadas ao seu projeto.

Benefícios:
Oportunidades de crescimento (carreira de empresa e cursos educacionais)
Mergulhe em projetos desafiadores
Horário de trabalho flexível (dentro do fuso horário do leste) Estados Unidos
Trabalho totalmente remoto
5 feriados nacionais pagos à sua escolha
3 semanas de folga remunerada
Estabilidade
Salário em USD
Cursos educacionais pagos de sua escolha
Bom ambiente de trabalho.

Se tem interesse e com requisitos da oportunidade entre em contato pelo Linkedin informando qual é a oportunidade. [https://www.linkedin.com/in/erickamarquesb/]

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
