### ISSUE TITLE
[Remoto] Front-end Developer na Dacxi

### ISSUE THREAD

**Issue by Soonas** [frontendbr/vagas#7477]
## Nossa empresa

A [Dacxi](https://dacxi.com/) é uma empresa que atua no mercado de cripto-economia e tokenização de ativos.
Estamos com todas as posições em aberto: Junior, pleno e senior.

## Local
-Remoto

## Requisitos

**Obrigatórios:**
- Javascript
- Vue
- Experiência com ferramentas de versionamento de código (GIT,...);

**Desejáveis:**
-  Conhecimento em blockchain e hyperledger;
- Docker

**Diferenciais:**
- Tailwind
- Inglês Intermediário;

## Benefícios
- Participar do mercado de tecnologia mais promissor: cripto-economia.
- Aulas de inglês.

## Contratação
Contratação PJ: (Dependendo exclusivamente do conhecimento do desenvolvedor)
Junior: Começa em > R$3.500,00...
Pleno: Começa em > R$5.000,00...
Sênior: Começa em > R$8.000,00...

## Como se candidatar
**Preencher o formulário:** [Clique aqui](https://forms.gle/JE9FZM79q2rcsYcf6)

## Tempo médio de feedbacks
Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato caso precise tirar dúvidas: luana@dacxi.com

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Junior
- Pleno
- Sênior

**Comment by FabricioMSilva** [comment]
Investe em mim aposta tudo em mim que eu prometo te fazer feliz !
