### ISSUE TITLE
[Remoro] Fullstack Javascript Developer na Jovens Gênios

### ISSUE THREAD

**Issue by marisaldanha** [frontendbr/vagas#7478]
## Nossa empresa
A Jovens Gênios é uma empresa Educacional e Tecnológica em crescimento, então aqui o aprendizado é constante, você terá pista livre para decolar e, claro, muitos desafios! Além disso, você trabalhará ao lado de pessoas diversas e talentosas que irão te auxiliar a maximizar todo o seu potencial de gerar o maior impacto positivo possível!

Sonhamos alto e apostamos no potencial das nossas pessoas. Acreditamos que cada pessoa que compõe a Jovens Gênios tem papel fundamental na nossa missão de transformar a experiência de aprendizado dentro das escolas e no alcance dos nossos objetivos atrelados à transformação da Educação. 

Temos o compromisso de ser uma empresa onde todos(as) tenham a oportunidade de exercer desenvolvimento pessoal e profissional. Nosso dia a dia é movido por uma cultura inspiradora e inclusiva, que busca a equidade e valoriza as diferenças, não aceitando qualquer tipo de discriminação sobre classe, etnia, gênero ou qualquer coisa do tipo. Por isso, buscamos pessoas cada vez mais diversas e inovadoras para fazer parte desse propósito!

## Descrição da vaga
Usará as habilidades em programação pra realização das demandas;
Irá engajar com o time diariamente para uma troca de informações e soluções;
Desenvolver novas funcionalidades ou corrigir problemas nos produtos da Jovens Gênios utilizando suas habilidades em Programação e Engenharia de Software.

## Local

Remoto ou Escritório no Centro do Rio de Janeiro

## Requisitos

*Desejáveis*
3 anos de experiência com desenvolvimento JavaScript
2 anos de experiência com desenvolvimento Vue.js
2 anos de experiência com desenvolvimento Node.js
Boas práticas de programação (Clean Code);
Conhecimentos de versionamento de software (Git);

*Diferenciais:*
Ter trabalhado na área de Educação;
Conhecimento em Docker e microserviços.

## Benefícios
Remuneração: R$ 5k - 8k (Pleno ou Sênior)
Vale Alimentação e Vale Refeição em um único cartão - Como diz o ditado: “saco vazio não pára em pé!”.
Plano de Saúde - Pra você cuidar da sua saúde e ficar sempre novinho(a) em folha!
Plano Odontológico - Nós estamos sempre rindo de algo! Sendo assim, nada mais justo do que proporcionarmos aquele sorrisão bonito pra você!
Gympass: Não tem mais desculpas para ficar fitness, ein?
Day Off no seu aniversário - Você escolhe como comemorar o seu grande dia!
Curso de Inglês 100% Gratuito com professora - Pra deixar seu inglês afiadíssimo!

## Contratação
PJ

## Como se candidatar

Por favor, envie um e-mail para vagas@jovensgenios.com com seu CV anexado.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.
E-mail para contato em caso de não haver resposta:  vagas@jovensgenios.com

#### Alocação
- Remoto

#### Nível
- Pleno e Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
