### ISSUE TITLE
[Remoto] Front-End Developer - Angular - na SOIRTEC

### ISSUE THREAD

**Issue by marciojustino** [frontendbr/vagas#748]
## Descrição da vaga

Atuará em projetos diversos como desenvolvedor front-end utilizando angular.

## Local

100% Remoto

## Requisitos

**Obrigatórios:**
- Git
- npm
- CSS
- HTML
- Angular

**Desejáveis:**
- TDD

## Contratação

PJ a combinar

## Nossa empresa

A SOIRTEC é uma empresa de desenvolvimento de software com grande abrangência em tecnologias atuando sempre com o que há de melhor no mercado para nossos clientes.

## Como se candidatar

Por favor envie um email para marciojustino@gmail.com com seu CV anexado - enviar no assunto: Vaga Angular

**Comment by IgorVieira** [comment]
Enviado!

**Comment by vinyguedess** [comment]
Enviado

**Comment by marciojustino** [comment]
Processo finalizado. Obrigado a todos.
