### ISSUE TITLE
[Rio do Sul-SC] Front-end Developer na Magazord

### ISSUE THREAD

**Issue by Andre-Magazord** [frontendbr/vagas#7482]
## Nossa empresa

O Magazord é uma empresa que surgiu como uma necessidade e mais tarde, acabou sendo uma solução para o E-commerce. A plataforma é completa em todos os sentidos. Apresenta as melhores soluções para que a sua loja virtual cresça de forma exponencial e apresente resultados em tempo recorde.

## Descrição da vaga

Descrição
O desenvolvedor Front-end focado é o responsável pelo desenvolvimento de nossas interfaces utilizando a tecnologia ReactJS.
Se você possui vivência com desenvolvimento de software em React venha fazer parte desse time que está fazendo história no ramo de Tecnologia e Inovação.
 
Atividades
-Desenvolver layout/interface, a partir das definições da equipe de designers
-Desenvolvimento de layouts responsivos
-Garantir a usabilidade do sistema e boa experiência de navegação
-Garantir a qualidade das entregas, automatizar o processo de construção e publicação
-Executar as atividades do cronograma de Sprint
-Implementar testes de Front-end
-Projetar e desenvolver componentes e aplicações visando simplicidade, eficiência, manutenibilidade e reaproveitamento de código
-Ativamente analisar e melhorar a escalabilidade, estabilidade e segurança das aplicações;
-Auxiliar a equipe Backend na definição de estruturas necessárias para o frontend.

## Local

Presencial, Santa Catarina, Rio do Sul

## Requisitos

**Obrigatórios:**
Ter vivência com desenvolvimento de software em React.

## Benefícios

- Plano de saúde
- Plano Odontológico
- Vale alimentação

**Diferenciais:**
- Horário flexível
- Comunicação horizontal
- GPTW

## Contratação

CLT

## Como se candidatar

Por favor envie seu currículo para (47) 9 9777-7791, informando que viu a vaga no GitHub e gostaria de participar do processo seletivo.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.
E-mail para contato em caso de não haver resposta: andre.albertani@magazord.com.br

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
