### ISSUE TITLE
[RJ - remoto] Front-end Developer na Material Agora

### ISSUE THREAD

**Issue by arxdsilva** [frontendbr/vagas#7483]
## Nossa empresa

A Material Agora está revolucionando como pequenas e médias empresas de construção se relacionam com seus fornecedores. Através de tecnologia estamos conectando os melhores fornecedores com seus clientes no melhor tempo possível, já tivemos mais de 7 mil pedidos enquanto operamos somente no estado do Rio de Janeiro.

Somos uma startup do ramo ConstruTech onde voce terá bastante autonomia e oportunidade de crescimento. O trabalho é totalmente remoto com eventuais encontros de todo o time, aqui nós valorizamos a diversidade e a inovação no nosso dia a dia.
## Local

Remoto ou Escritório (se quiser) em botafogo, Rio de Janeiro, RJ

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com Node/React

**Diferenciais:**
- projetos opensource
- conhecimento em golang

## Benefícios

- VR de R$ 30/dia

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para arthursilva@materialagora.com.br com seu CV anexado - enviar no assunto: Vaga Front-end e faça o desafio em: https://github.com/materialagora/carreiras

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após o desafio.
E-mail para contato em caso de não haver resposta: arthursilva@materialagora.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by evertonProgramadorCriativo** [comment]
[arxdsilva](https://github.com/arxdsilva) estou Me Preparando  para   trabalha remoto  como programador ,   eu estava vendo no youtube  ,vou te mais chance de trabalha remotamente se me especializa em uma aréa técnica , então eu escolhi React Js . Pergunta para  Você como Programador , eu já entendo  a logica do react js  e native .   eu tenho que saber  Toda a sintaxe  de React js , javascript  , Typescript , Redux  e Teste (unit testing , integration testing , functional testing  e2e)  ter conhecimento  bem Sólido para me destaca e a sintaxe  na ponta  dos dedos ??? para eu consegui Trabalha Remotamente como Programodor ??? , Observação :: Não tenho experiência de trabalho ainda

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by arxdsilva** [comment]
Oi @felipefialho continua aberta a vaga

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
