### ISSUE TITLE
[Remoto] Front-end Developer na Coodesh

### ISSUE THREAD

**Issue by blankapf** [frontendbr/vagas#7485]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-developer-senior-171815922?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>&nbsp;A <strong>MobiPlus </strong>está em busca de <strong><ins>Front-end Developer</ins></strong><strong> </strong>para compor seu time!</p>
<p><strong>O contexto do projeto na Moiplus:</strong></p>
<p>Este contexto é estratégico para a Mobiplus por ser parte de um cliente de longa relação e que está demandando cada vez mais auxílio. Nosso sucesso nessa iniciativa representará a abertura de várias novas oportunidades, tanto pelo case, quanto pela possibilidade de termos novas portas abertas dentro do cliente. Será também mais um importante passo na nossa busca por excelência na prestação de serviços, na montagem de times de desenvolvimento de produtos e no quanto conseguimos transformar a alocação de desenvolvimento em algo maior em cada um dos clientes.</p>
<p></p>
<p><strong>Responsabilidades:</strong></p>
<ul>
<li>Atuar no time de desenvolvimento Frontend de nosso cliente, auxiliando na evolução do produto e sempre que possível atuando como um orientador de boas práticas de desenvolvimento de software e de produto (mesmo não sendo um líder nomeado);</li>
<li>Ajudar o time cada vez mais a ter proximidade com a área de negócios/produto e ter mentalidade de Product Developers.</li>
</ul>
<p>&nbsp;</p>
<p>Nosso critério de sucesso é gerarmos mais oportunidades neste contexto em função do trabalho excepcional que fazemos, além é claro de receber feedbacks surpreendentes.</p>
<p>Perfil que buscamos:</p>
<ul>
<li>Curioso;</li>
<li>Tenha mais conhecimento do que apenas o uso de bibliotecas;</li>
<li>Análise crítica, sem criar ciência de foguete;</li>
<li>Entenda sobre como testar o front e sua importância;</li>
<li>Saiba se adaptar ao processo;</li>
<li>Saiba trabalhar em equipe, ser agnóstico a tecnologia;</li>
<li>Olhar para longo prazo;</li>
<li>Tenha uma boa comunicação.</li>
</ul>

## Mobiplus: 
 <p>A Mobiplus nasce em 2017 com uma ideia bem clara: prestar serviço de alta qualidade para viabilizar a montagem de um TIME de alta performance e, em um segundo momento, gerar resultados importantes para todos os envolvidos na empreitada, com produtização de serviços e desenvolvimento de produtos (SaaS).</p><p>Nosso caminho passa por: Pessoas, Felicidade e Satisfação pessoal e profissional, Excelência, Ética, Transparência e Negócios. Respeitando esta ordem.</p><a href='https://coodesh.com/empresas/mobiplus'>Veja mais no site</a>

 ## Habilidades: 
 - React.js 
- Javascript 
- Typescript 
- Redux
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência significativa em colocação igual ou similar; 
- Experiência em React e testes unitários; 
- Sólidos conhecimentos em JavaScript, Typescript e Redux.

## Benefícios: 
 - Trabalho 100% remoto (nascemos 100% remotos já em 2017); 
- Ambiente descontraído, colaborativo e extremamente desafiador; 
- Ambiente 100% propício para aprendizado constante e inovação; 
- Horário flexível (limitações de janela de horário dependendo do contexto/cliente); 
- Possibilidade de trabalhar com um time de capacidade acima da média; 
- Possibilidade de trafegar entre diferentes tecnologias e stacks; 
- Possibilidade de recesso de final de ano remunerado; 
- 1 vez por mês onde fazemos nossa reunião mensal, trazemos convidados de fora para compartilharem suas experiências conosco, batemos papo sobre assuntos diversos no clube do podcast e brincamos também no final do dia; 
- Descanso remunerado de 30 dias.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Front-end Developer na Mobiplus](https://coodesh.com/vagas/frontend-developer-senior-171815922?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by nunesdotpy** [comment]
enviado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
