### ISSUE TITLE
[Remoto] Front-end Developer Pleno - Proft

### ISSUE THREAD

**Issue by tarikbc** [frontendbr/vagas#7491]
Site: https://proft.sale

# Descrição da Empresa
Aqui na Proft você vai poder revolucionar o varejo com a gente em um dos ambientes mais inovadores do Brasil, com mentorias constantes que possibilitam uma grande experiência para sua carreira. Atualmente precisamos de alguém com conhecimento em React p/ contribuir na aceleração de nosso produto e fazer parte de nossa história!

# Atividades e Responsabilidades
Estamos resolvendo uma treta que os vendedores do varejo passam diariamente. Para isso será fundamental:
- Desenvolver apps React.JS e React Native
- Fazer um código top
- Estar disposto a aprender e partilhar
- Cuidar do filhote quando algum bug surgir em produção

# Requisitos
- Experiência em CSS3 e HTML5 responsivo
- Erros acontecem, mas você deve saber errar rápido e jogar limpo
- Comprar a briga com a gente nas demandas
- Manjar dos paranauês do git
- Ter tido experiência prévia com desenvolvimento em React e trabalhado em equipe
- Ter bom raciocínio lógico
- Preocupação com a qualidade e clareza do código (Lidamos com muito cálculo, por isso é importante ter em foco um código otimizado)
- Enviar "capivara" no conteúdo do e-mail para que possamos identificar que você leu o anúncio até o final
- Ter trabalhado com Redux
- Conhecimentos básicos em matemática (Rola muita regra de 3, porcentagem, projeções, etc)

# Desejável
- Entendimento de complexidade de algoritmos (Big O Notation) e estruturas de dados (Dicionário, tabela hash, árvore, etc.)
- Experiência em frameworks de testes (Jest, Cypress, etc)
- Experiência em Electron
- Typescript
- Pelo menos 1 ano de experiência profissional
- Noção de UI Design

# Etapas do nosso processo seletivo: 
1. Análise de portifólio, currículo e projetos pessoais
2. Entrevista técnica
3. Teste prático
4. Entrevista com o time

# Remuneração
- Salário: a combinar (precisamos antes avaliar seu nível de experiência)
- PJ
- Vaga 100% remota
- Interessados enviar email com CV, pretensão salarial e algum projeto que você queira que a gente veja para cleiton@neopro.com.br

# Labels
- 🏢 Remoto
- 👨 Pleno
- ⚖️ PJ

**Comment by evertonProgramadorCriativo** [comment]
[tarikbc](https://github.com/tarikbc) estou Me Preparando  para   trabalha remoto  como programador ,   eu estava vendo no youtube  ,vou te mais chance de trabalha remotamente se me especializa em uma aréa técnica , então eu escolhi React Js . Pergunta para  Você como Programador , eu já entendo  a logica do react js  e native .   eu tenho que saber  Toda a sintaxe  de React js , javascript  , Typescript , Redux  e Teste (unit testing , integration testing , functional testing  e2e)  ter conhecimento  bem Sólido para me destaca e a sintaxe  na ponta  dos dedos ??? para eu consegui Trabalha Remotamente como Programodor ??? , Observação :: Não tenho experiência de trabalho ainda

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
