### ISSUE TITLE
[São Paulo] Front-end Developer na KLB Group

### ISSUE THREAD

**Issue by DavidKLBG** [frontendbr/vagas#7492]
**[São Paulo] Front-End Developer na KLB Group**

**Nossa empresa**
A KLB Group é uma empresa multinacional francesa presente em mais de 15 países com mais de 25 anos de experiência no mercado global. Somos especialistas em Implementação de Projetos, Outsourcing e Recrutamento e Seleção (Hunting), com forte atuação nas áreas de TI, Engenharia e áreas administrativas. Atuamos desde projetos mais simples e operacionais até projetos mais complexos com níveis de entrega bem definidos.

**Descrição da vaga**
Contratação CLT = Benefícios

**Local**
Híbrido, [SÃO PAULO], [SÃO PAULO], [AV. PAULISTA]

**Requisitos**
**Obrigatórios:**
- Vue Js
- Angular
- Javacript
- Wildfly

**Desejáveis:**
- Java 8
- Spring Booot, Spring MVC

**Diferenciais:**
- projetos opensource

**Benefícios**
Será detalhado com o recrutador.

**Diferenciais:**
Conhecimento em Sistemas de Seguros

**Contratação**
CLT

**Como se candidatar**
Por favor envie um email para anogueira@klbgroup.com com seu CV anexado - enviar no assunto: Vaga Desenvolvedor Front-End

**Tempo médio de feedbacks**
Costumamos enviar feedbacks em até 07 dias após cada processo.
E-mail para contato em caso de não haver resposta: anogueira@klbgroup.com

**Alocação**
- Alocado
- Híbrido em São Paulo

**Regime**
- CLT

**Nível**
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
