### ISSUE TITLE
[BRASIL] Cloud Front-end Developer Sênior na KLB Group 

### ISSUE THREAD

**Issue by DavidKLBG** [frontendbr/vagas#7493]
**[São Paulo] Cloud Front-End Developer Sênior na KLB GROUP**

**Nossa empresa**
A KLB Group é uma empresa multinacional francesa presente em mais de 15 países com mais de 25 anos de experiência no mercado global. Somos especialistas em Implementação de Projetos, Outsourcing e Recrutamento e Seleção (Hunting), com forte atuação nas áreas de TI, Engenharia e áreas administrativas. Atuamos desde projetos mais simples e operacionais até projetos mais complexos com níveis de entrega bem definidos. 

**Descrição da vaga**
**Local**
100% Remoto, [BRASIL]

**Requisitos**
**Obrigatórios:**
- Front End – obrigatório;
- Base em orientação a objetos e algoritmos;
- Bancos de dados: MySql, Postgres, Oracle, Db2, NoSql (Dynamo / Mongo);
- Conhecimento em sistema operacional Linux;
- Linguagens e frameworks: Typescript, NodeJS, NestJS, React, ReactNative, Java, Spring;
- Experiência Modelagem, Documentação e implementação de APIs REST;
- Facilidade em integração de APIs REST e SOAP;
- Conhecimento de mercado em fintech: meios de pagamento, análise de fraude, sistemas de conciliação;
- Experiência em Cloud Computing, principalmente AWS;
- Versionamento de código (Github);

**Desejáveis:**
- Conhecimentos avançados em AWS: EC2, S3, VPC, RDS, Route53, Domains, SES, SNS;
- ELK stack;
- NGINX;
- Conhecimentos em CI/CD;
- Construção de pipelines;
- Github actions;
- Conhecimento em Keycloak;
- Conhecimento em Docker, Docker-swarm e Kubernet.

**Benefícios**
Será detalhado pelo recrutador.

**Contratação**
PJ

**Como se candidatar**
Por favor envie um email para msantana@klbgroup.com com seu CV anexado - enviar no assunto: Desenvolvedor Cloud (Front-end)

**Tempo médio de feedbacks**
Costumamos enviar feedbacks em até 07 dias após cada processo.
E-mail para contato em caso de não haver resposta: msantana@klbgroup.com

**Alocação**
- Alocado
- Remoto

**Regime**
- PJ

**Nível**
- Pleno
- Sênior
- Especialista

**Comment by victorbiasibetti** [comment]
Parece ser uma vaga full-stack

**Comment by DavidKLBG** [comment]
O foco da vaga é as ferramentas de Angular e Vue.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
