### ISSUE TITLE
[Remoto] Angular Developer | Vem pra @Datum💜

### ISSUE THREAD

**Issue by julianakraemer** [frontendbr/vagas#7497]
## Nossa empresa

Activate your protagonism in a changing world 🌎💜

## Descrição da vaga

Que tal fazer parte de um projeto global? Estamos com oportunidades para atuar alocado no projeto de uma multinacional de produtos financeiros e seguros. Importante ter ingles avançado para comunicação. 

## Local

100% remoto!

## Requisitos

**Obrigatórios:**
Angular 14;
Reactive Forms;
Used to work with different component libraries (Angular Material, Twitter Bootstrap, Aposin, etc);
Model oriented development;
Used to Front-end architecture;
NGRX (Reactive State);
Fluently in English;

**Desejáveis:**
Backend knowledge (.net, nodejs);
Serverless framework;
Used to designing Front-end architecture

## Benefícios

Gympass
Seguro de vida
Zenklub com 2 sessões gratuitas por mês
Assessoria financeira e psicológica para funcionários

Aqui na Datum, você também vai ter:

Protagonistas (game de incentivo à carreira do colaborador)
Datum Academy (programa de treinamento e treinamentos)
Parceria com a escola CCAA para aulas e espanhol com desconto para funcionários e familiar

## Contratação

PJ/Cooperado a combinar

## Como se candidatar

Por favor envie um email para juliana.kraemer@datum.inf.br com seu CV anexado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
