### ISSUE TITLE
[São Paulo] Desenvolvedor Front-End Pleno

### ISSUE THREAD

**Issue by andreloureiro** [frontendbr/vagas#75]
## Descrição da vaga

A oportunidade é para desenvolvedores Front-End que também gostem de fazer um pouco de criação.

## Local

Alocado, Pinheiros - São Paulo (ao lado da Estação Hebraica-Rebouças)

## Benefícios

- Ambiente de trabalho informal
- Horário flexível
- Salário compatível com o mercado
- Vale Refeição
- Vale Transporte
- Assistência Médica
- Assistência Odontológica
- Previdência Privada.

## Requisitos

**Obrigatórios:**
- Criação de layouts, wireframes de baixa e alta resolução
- Conhecimento de softwares gráficos (Illustrator, Photoshop)
- HTML5, CSS, JavaScript
- Design Responsivo
- Técnicas de desenvolvimento cross browser
- Conhecimento básico em Angular e/ou React

**Diferenciais:**
- Sass, Less
- Conhecimento sobre Mobile UI

## Contratação

CLT

## Nossa empresa

A [Opus Software](http://www.opus-software.com.br) é uma empresa de desenvolvimento de software localizada no bairro de Pinheiros, em São Paulo, com mais de 29 anos de mercado e que atua nas áreas de automação bancária e desenvolvimento de projetos específicos. Foi eleita em 2015, pelo quinto ano consecutivo, pelo Great Place to Work, uma das melhores empresas para se trabalhar em TI e Telecom. Valorizamos profissionais com boa formação e com capacidade de aprendizado acima da média. Além disso, acreditamos que talento faz diferença!

## Como se candidatar

Enviar currículo para elisangela@opus-software.com.br informando, no assunto da mensagem, o nome da vaga.

**Comment by LFeh** [comment]
Boa vaga :)

**Comment by andreloureiro** [comment]
Eu já trabalhei na empresa, e ainda tenho amizade com todo mundo lá mesmo já tendo saído há mais de um ano. Ótimo ambiente, com zero concorrência entre os devs. Todo mundo se ajuda, e todo mundo tá sempre querendo aprender mais.

**Comment by LFeh** [comment]
Pela vaga da pra perceber. Skills muito justas e totalmente de acordo.

**Comment by renanrider** [comment]
A vaga parece ser boa, pena que só posso fazer estágio por enquanto.

**Comment by andreloureiro** [comment]
@renanrider eles contratam estagiários frequentemente. Posso checar com meu amigo lá. Você teria interesse em estagiar como Front-End?

**Comment by renanrider** [comment]
@andreloureiro, tenho interesse e ainda conheço bastante alunos do mesmo curso que tem interesse em fazer estágio. Muito obrigado :)

**Comment by andreloureiro** [comment]
@renanrider falei com meu amigo lá, manda seu CV pro murilo@opus-software.com.br, e diz que vc falou comigo, só pra ele saber. Se quiser pode passar pros seus amigos do curso, boa sorte!!

**Comment by renanrider** [comment]
Muito obrigado @andreloureiro, vou enviar o CV. Valeu mesmo :{)

**Comment by olegon** [comment]
Vaga interessante, mas sou mais do mundo back-end .NET  :construction_worker:

**Comment by andreloureiro** [comment]
@olegon falei com meu amigo, ele disse que estão com vagas pra .NET também, manda CV pro murilo@opus-software.com.br, boa sorte!

**Comment by LFeh** [comment]
O @andreloureiro é tipo o Paulinho da Força :smiley_cat:

**Comment by andreloureiro** [comment]
@LFeh eu tento ajudar o máximo que consigo, tanto é que nem trabalho mais na empresa mas tô tentando ajudá-los pq estão com dificuldades para encontrar fronts :)

**Comment by carmona** [comment]
@andreloureiro estou mandando meu CV :+1:

**Comment by andreloureiro** [comment]
@LFeh voltando depois de um bom tempo pra avisar que o pessoal conseguiu fazer a contratação através dessa issue :)

valeu!!

**Comment by LFeh** [comment]
Aeee, sensacional 💃

**Comment by Patrick-Isidoro** [comment]
@andreloureiro desculpa reviver o tópico, mas sabe se eles ainda contratam estagiário ou Jr?!
Valeu, abraços!
