### ISSUE TITLE
[REMOTO] Front-end Developer Flutter na Bioverselabs

### ISSUE THREAD

**Issue by wolfgio** [frontendbr/vagas#7500]
## Nossa empresa

A Bioverse foi fundada em 2019 com a missão de mudar a forma como as indústrias valorizam a Biodiversidade. Desde então, a Bioverse desenvolveu soluções de ponta em sensoriamento remoto, levantamento aéreo e aprendizado de máquina para fornecer inventário florestal como um serviço para fortalecer a cadeia de fornecimento de produtos florestais não relacionados à madeira e aumentar e beneficiar indústrias que apoiam uma bioeconomia sustentável em florestas tropicais.

## Descrição da vaga

Temos dois projetos em Flutter disponíveis nas seguintes plataformas: Android, iOS e Web e com isso esperamos que você:

- Desenvolva novas funcionalidades aplicando os padrões do Framework com um código limpo e testável
- Participe de code review
- Realize deploy de novas versões nas lojas (Play Store e App Store) e deploy web utilizando Firebase Hosting
- Conheça o ecossistema do Firebase, assim como suas principais ferramentas (Firestore, Authentication, Storage etc...)
- Consiga trabalhar no desenvolvimento de plugins de comunicação com funcionalidades nativas (Android, iOS)

## Local

REMOTO

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com desenvolvimento mobile
- Vivencia com desenvolvimento de aplicações em Flutter
- Conhecimento com  POO
- Capacidade de trabalhar utilizando Clean Code, SOLID e TDD.
- Escrita de testes automatizados

**Desejáveis:**
- Conhecimentos em Dart
- Experiência com Firebase

**Diferenciais:**
- Experiência com desenvolvimento de Flutter Plugins 
- Experiência com utilização de Tensorflow Lite para detecção de objetos
- Inglês Fluente ou Avançado

## Contratação

PJ  Part-Time com possibilidade de efetivação após 6 meses

## Como se candidatar

Por favor envie um email para info@bioverselabs.com com seu CV anexado - enviar no assunto: Vaga Flutter

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: info@bioverselabs.com

#### Alocação
- Remoto

#### Regime
- PJ
- Freela
- Part-Time

#### Nível
- Pleno

**Comment by wolfgio** [comment]
Opa a vaga é remota permanentemente, se puder remover essa label [🦠 Remoto durante pandemia]

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
