### ISSUE TITLE
[Remoto] Frontend Developer (Júnior) na Coodesh

### ISSUE THREAD

**Issue by blankapf** [frontendbr/vagas#7504]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedora-react-194010631?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>Easy Live Entretenimento</strong> está em busca de <strong><ins>Frontend developer Jr</ins></strong> para compor seu time!</p>
<p>Uma empresa especializada no segmento de fidelidade e com diversas opções de conteúdo e entretenimento, a Easy Live é uma plataforma digital que conecta seus clientes aos melhores eventos, serviços e produtos. A empresa o faz por meio dos principais programas de fidelidade, benefícios e incentivos do Brasil, oferecendo infinitas possibilidades em um só lugar.<br><br></p>
<p><strong>Responsabilidades</strong></p>
<ul>
<li>Atuar em diversos projetos sugerindo as melhores soluções como desenvolvedor;</li>
<li>Gestão de prioridades e interface com equipe de TI.</li>
</ul>
<p></p>

## Easy Live Entretenimento: 
 <p>Muito prazer, somos a Easy Live!</p>
<p>Somos uma empresa especializada no segmento de fidelidade e com diversas opções de conteúdo e entretenimento, a Easy Live é uma plataforma digital que conecta seus clientes aos melhores eventos, serviços e produtos. A empresa o faz por meio dos principais programas de fidelidade, benefícios e incentivos do Brasil, oferecendo infinitas possibilidades em um só lugar.</p><a href='https://coodesh.com/empresas/easy-live-entretenimento'>Veja mais no site</a>

 ## Habilidades: 
 - React.js 
- Next.js 
- Typescript 
- REST APIs 
- GIT 
-  UX/UI 
- Banco de dados relacionais (SQL)
## Local: 
 100% Remoto
## Requisitos: 
 - Conhecimento com React.JS; 
- Conhecimento com Next JS; 
- Conhecimento com TypeScript; 
- Conhecimento com consumo de APIs REST; 
- Clean Code; 
- Git; 
- Noções de UX/UI; 
- SQL Server.
## Diferenciais: 
 - Conectado em inovações e senso crítico; 
- Boa comunicação.
## Benefícios: 
 - Vale Refeição; 
- Férias; 
- Bônus anual por desempenho.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Developer (Júnior) na Easy Live Entretenimento](https://coodesh.com/vagas/desenvolvedora-react-194010631?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by Danielcsxx** [comment]
Olá, não consigo realizar a candidatura a esta vaga, teria algum email que eu possa utilizar para encaminhar meu curriculo? grato

**Comment by RafaelRRhocha** [comment]
Boa Tarde, não consigo me candidatar a vaga... existe alguma outra forma de se candidatar?

**Comment by DevCleverton** [comment]
> Boa Tarde, não consigo me candidatar a vaga... existe alguma outra forma de se candidatar?



entra no site e selecione  o botão interesse!

**Comment by tascintra** [comment]
> Boa Tarde, não consigo me candidatar a vaga... existe alguma outra forma de se candidatar?

Eu entrei em contato com o suporte da Coodesh e eles me informaram que não é mais possível se candidatar a essa vaga porque o limite de inscrições foi atingido. Essa vaga atingiu 400 inscrições em 24 horas segundo o que me passaram.

**Comment by pscarano1103** [comment]
Boa noite, não consigo me candidatar também, teria algum email para poder enviar meu VC?

**Comment by blankapf** [comment]
Bom dia, Paulo!
A vaga encontra-se fechada para novas candidaturas.
Fique de olho em nossa plataforma para novas oportunidades!
Abraços,

Blanka Finoketti - Talent Sourcer

2022, Coodesh

(55) 996662726

https://coodesh.com

***@***.*** ***@***.***>



Em sáb., 19 de nov. de 2022 às 22:56, Paulo Scarano <
***@***.***> escreveu:
