### ISSUE TITLE
[São Paulo] Front-End Developer  na Avantti

### ISSUE THREAD

**Issue by EsterTechRH** [frontendbr/vagas#7506]
> Vaga Remota 100%

## Nossa empresa

AVANTTI

## Descrição da vaga

Solidos conhecimentos em HTML 5
CSS/ SCSS/ JAVA SCRIPT/ NODE.JS/ VUE/ REACT

## Requisitos
Experiência em Redis, MONGO DB, RDBMS

**Obrigatórios:**
- INGLÊS MANDATÁRIO

**Desejáveis:**
- Conhecimentos em (AWS, MS, AZURE, ALI, CLOUD, ETC)
- Conhecimentos e tudo serviço como (IAAS, PAAS, SAAS, DAAS, ETC)

## Benefícios

- VR, 
- Day off niver,
- Férias
- Inglês Corporativo
- Auxílio Home Office

## Contratação

PJ ou Clt a combinar

## Como se candidatar

Por favor envie um email para ester.ferreira@avantti-br.com.br com seu CV anexado - enviar no assunto: Vaga Front-End Developer 

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@avantti-br.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

**Comment by pscarano1103** [comment]
Enviado!
