### ISSUE TITLE
[Remoto] Front-end Developer na Yampi

### ISSUE THREAD

**Issue by isahbelanascimento** [frontendbr/vagas#7507]
> Vaga 100% remota.

## Nossa empresa

A Yampi não para de crescer e inovar, e você pode embarcar nessa conosco, sendo uma Pessoa Desenvolvedora Front-end!

Se você tem paixão pelo processo de construção e evolução de produtos, e está em busca de uma oportunidade onde te valorizam e se preocupam com você, vem pra Yampi! 💜

## Descrição da vaga

Estamos com oportunidades para pessoas desenvolvedoras front-end em nível pleno e sênior, para atuar em nossas squads Checkout e Analytics. 

## Local

Remoto

## Requisitos

**Obrigatórios:**
Conhecimento avançado em frameworks JavaScript como Vue.js ou React.js
Experiência com Git;
Noções de UI/UX;
Experiência com testes automatizados em JavaScript;
Conhecimento em ferramentas de build;
Conhecimento teórico e prático em micro serviços e APIs;
Conhecimento em Webpack, NPM, Yarn;

## Benefícios

Aulas de Inglês Gratuitas.
Convênio Médico Unimed Seguros, sem co-participação, com custeio de 30% pela empresa.
Convenio Odontológico da Unimed Seguros.
Vale refeição no cartão Caju, um cartão de crédito bandeira VISA, para proporcionar maior flexibilidade.
Acesso gratuito a Alura, uma plataforma de cursos online para várias áreas de conhecimento.
Auxílio para realização de cursos, participação em eventos e workshops e compra de livros.
Seguro de Vida.
Gympass.
Day-off no dia do seu aniversário.

## Contratação

CLT

## Como se candidatar

Por favor, cadastre-se em https://yampi.gupy.io/ ou envie um e-mail para pessoas@yampi.com.br com o título Front-end Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: isabela.nascimento@yampi.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by glsvitoria** [comment]
Enviado

**Comment by pscarano1103** [comment]
E-mail enviado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
