### ISSUE TITLE
[Desenvolvedor FrontEnd Pleno] - 100% presencial Centro Cívico, Curitiba - PR na HunterHunter

### ISSUE THREAD

**Issue by ErickaMB** [frontendbr/vagas#7509]
[Desenvolvedor FrontEnd Pleno] - 100% presencial Centro Cívico, Curitiba - PR - CLT R$ 7 mil.

Requisitos e Qualificações:

Ensino Superior Completo na área de TI

2+ Experiência de trabalho comprovada como desenvolvedor front-end

Domínio completo das seguintes tecnologias: Bootstrap, Angular, Angular Material e TypeScript

Compreensão profunda de todo o processo de desenvolvimento (design, desenvolvimento e implantação)

Familiaridade com GIT

Experiência comprovada com UX/UI

Conhecimento e experiência com ferramentas de modelagem/prototipagem (Figma, XD Adobe, etc).

Empresa:

Somos um sólido grupo com mais de 33 anos, que atende empresas de crédito, fomento comercial, bancos, fundos de investimento e instituições financeiras com sistemas e serviços.

Se você tem o Ensino Superior completo, disponibilidade para trabalhar presencialmente, e tem os conhecimentos acima, essa vaga é para você!

O que oferecemos:

Vale Alimentação R$30,00 por dia trabalhado;

Vale Transporte;

Plano de Saúde (Após período de experiência);

Plano Odontológico (Após período de experiência);

Seguro de Vida;

Gympass;

Convênio Ótica.

Tipo de vaga: Tempo Integral, Efetivo - CLT Pleno R$ 8 K e Sênior R$ 10 K.

Horário: De segunda a sexta feira.

Início 08:30 as 12:00.

intervalo para almoço: 1h30 / Das 12:00 h as 13:30 h.

Retorno 13:30 as 18:00 h.

Se tem interesse e com requisitos da oportunidade entre em contato pelo Linkedin informando qual é a oportunidade. [[https://www.linkedin.com/in/erickamarquesb/]](https://www.linkedin.com/in/erickamarquesb/%5D)

**Comment by Brayozin** [comment]
tem estágio? sou pleno e estou na faculdade,mas só trabalho 6h/dia por causa da faculdade

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
