### ISSUE TITLE
[Belo Horizonte - MG] Front-End Developer

### ISSUE THREAD

**Issue by andre0799** [frontendbr/vagas#751]
## Descrição da vaga

ROBOS.im is San Pedro Valley based company with amazing investors whom is fastly becoming the most well known platform/solution for chatbots. And we need your skills, experience and passion for tech to take this a step further!

We are looking for a front-end developer with strong knowledge of UI/UX. You'll be developing the most amazing interfaces ever!

What will you do?

- Take the lead on the conversations about the client-side in our web platforms;
- Develop the most amazing interfaces ever;
- Thrive to provide at daily bases THE BEST UX functionality ON THE PLANET for our costumers in a responsive and elegant manner;
- Have fun and make friends at the office.

What you will get?

 - Contract based (PJ). Less bureaucracy and more freedom for you with a fair compensation for you contributions; 

- FULLY flexible work hours & once a week home office;

- Work with a product that has complex and challenging  architecture based on Microservices. As the product learns and grown so will you;

- Work with SCRUM on a truly Agile environment;

- We take learning very serious, so... Udemy account with ANY course available at company expense;

- Opportunity to grow fast. Robos.im is working to implement a equity strategy for our first employees in the near future;

- Generation Y friendly environment (Total respect for your decisions, experiment and individuality. Informal dress code, constant feedback, learning as a priority, SUPER cool office and SUPER cool partys, all you can eat snacks);

- BYOD. If you do not like to carry you lap top around we offer a Starter Pack (Laptop with a i5 and 8G DDR3 running Ubuntu)

- Opportunity to shape the company's culture.

- Give it back to the community: ROBOS.im works towards making 70% of it's technologies open source

If you love new challenges, have passion about tech and has an eager to be part of something revolutionary, join our way of working, join us! We are ROBOS.im!

## Local

Escritório na Savassi, Belo Horizonte - MG (San Pedro Valley)

## Requisitos

**Obrigatórios:**
We are looking for a developer passionate about tech and who has an eager to be part of something revolutionary. In order to be considered for this position you also must present:

- Ownership;
- Clean code and detail oriented documentation. We value quality;
- Degree (2y-5y courses) at the I.T field or proven equivalent experience;
- Minimum of 2 years of proven experience as a Front-end Developer;
- Demonstrated skills with Javascript, UI/UX Design, HTML5 & CSS3, Angular/React;
- Advanced english skills is a must; 

**Diferenciais:**
- Knowledge of SaaS, Machine Learning, Natural Language Processing e Bots are a plus;
- Experience with SCRUM or other Agile methodologies is also a plus;
- If you know your way around the server-side of the force that is a huge bonus!

## Contratação

PJ - R$4000 - R$9000

## Nossa empresa

ROBOS.im is a Brazilian company focused in delivering "state-of-art" products to solve Natural Processing Language (NLP) and Machine Learning (ML) issues. Stablished in 2016, ROBOS.im aims to it's worldwide expansion, offering it's products globally.

## Como se candidatar

**Acesse:** [https://www.recrutasimples.com.br/vaga/-L3Fn3fnI5FYQABSrILk?referrer=githubfrontendvagas](https://www.recrutasimples.com.br/vaga/-L3Fn3fnI5FYQABSrILk?referrer=githubfrontendvagas)

**Comment by andre0799** [comment]
Salário atualizado! ;)

**Comment by fabiosilvaacs** [comment]
Remote work?

**Comment by andre0799** [comment]
Não @fabiosilvaacs 
![image](https://user-images.githubusercontent.com/5369270/36388206-de1f1d4e-1579-11e8-934f-db2eced4c12d.png)

**Comment by GustavoRPS** [comment]
Muita interessante a vaga fica meu [LinkedIn](https://www.linkedin.com/in/gustavorps/)
Acabei enviado o PDF do linked no sistema de recrutamento pedi um arquivo de CV, mas acredito que um link do LinkedIn resolve muita coisa hoje em dia.

**Comment by andre0799** [comment]
Sem dúvida @GustavoRPS
