### ISSUE TITLE
[REMOTE] React Developer @ Onesight

### ISSUE THREAD

**Issue by kamiarc** [frontendbr/vagas#7515]
## Nossa empresa

A Onesight é uma multi-nacional com foco em desenvolvimento de tecnologias disruptivas e bleeding edge, atuamos com diversos clientes em múltiplos mercados e tecnologias.
No Brasil nossas atividades se concentram em outsourcing, e-commerces e plataformas customizadas.

## Descrição da vaga
A vaga é para trabalhar no lado FE de React e React-native na criação de uma plataforma de suporte remoto via webrtc (Livekit)
Quem entrar ira complementar o time atual, o projeto está praticamente no início ainda

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Frameworks/libs: React, Express
- Web (HTML5/CSS3)
- Git

**Desejáveis:**
- Conhecimentos em Node.JS
- AWS
- Ter ao menos um projeto desenvolvido em React
- Ter ao menos um projeto desenvolvido em Node
- Idioma Italiano ( é totalmente opcional, mas interessante para a vaga :) )

**Diferenciais:**
Férias "livres" (2.5 dias acumulados por mês trabalhado, não precisando completar um ano de trabalho)
Horário flexível
Curso de Italiano
25% do horário (para contratações full time) para self-improvement ou open team projects

## Contratação
Estágio
PJ

## Como se candidatar
Por favor, envie um e-mail para trampos@onesight.com.br com seu CV anexado - enviar no assunto: Vaga React

## Tempo médio de feedbacks
A posição é para início em 2 semanas, então será um processo rápido :)

#### Alocação
- Remoto

#### Regime
- Estágio
- PJ

#### Nível
- Junior
- Pleno

**Comment by DanielSiilva** [comment]
Enviado!

**Comment by DanielSiilva** [comment]
Gostei bastante da proposta do projeto!

**Comment by tascintra** [comment]
Enviado!

**Comment by raphaelalmeidamartins** [comment]
Enviado :white_check_mark:

**Comment by AndersonAngelo** [comment]
Enviado, fico a disposição!

**Comment by YtaloGabriel** [comment]
Gostei da divulgação da vaga, bem direto ao ponto, apenas o essencial. Enviado!

**Comment by lucasfelipedonascimento** [comment]
Enviado!!

**Comment by Matheus0351996** [comment]
Enviado!

**Comment by zeekias** [comment]
Enviado!

**Comment by jonatasvaz** [comment]
Eviado

**Comment by ItaloRAmaral** [comment]
Enviado!

**Comment by gabriellfernandes** [comment]
Enviado!

**Comment by TaylorNAlbarnaz** [comment]
Enviado!

**Comment by CayoNakasato** [comment]
Enviado!

**Comment by aragornbp** [comment]
Enviado!

**Comment by matheuslei** [comment]
Enviado! ✅

**Comment by waltodd** [comment]
Done!

**Comment by MatheusdeSouzaSilva70** [comment]
Enviado!

**Comment by devsantosbruno** [comment]
Enviadoo!

**Comment by gabrielcarlossl** [comment]
Enviado.

**Comment by rafaelsilva81** [comment]
Enviado

**Comment by marcusmartinss** [comment]
Enviado!

**Comment by FeRiffo** [comment]
Enviado!

**Comment by evertondsvieira** [comment]
Enviado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
