### ISSUE TITLE
[Remoto] Front-end Angular Developer na ITeam

### ISSUE THREAD

**Issue by VivianeRHTI** [frontendbr/vagas#7517]
## Local

100% Remoto - Full time em horário comercial

## Requisitos obrigatórios 

Domínio no desenvolvimento de aplicações em JavaScript
Domínio em HTML, CSS e SASS
Experiência com framework Angular
Domínio em aplicações SPA e PWA
Experiência em Chrome DevTools
Experiência em APIS REST
Experiência em padrões de arquitetura de Microfrontends.

## Requisitos desejáveis/ diferencial

Formação superior na área de tecnologia;
Domínio em frameworks como React ou Vue;
Experiência na criação de testes automatizados (unitários e integrados);
Domínio no manuseio de repositórios Git e semantic versioning;
Domínio no levantamento de requisitos funcionais e não funcionais;
Experiência no suporte e sustentação de ambientes críticos;
Experiência com comunicações sincronas e assíncronas.

## Contratação

6 meses - com grande possibilidade de renovação

## Nossa empresa

Há mais de 15 anos presente no mercado, a ITeam oferece o comprometimento com o cliente.
Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 
O relacionamento da ITeam é baseado no amplo comprometimento com os valores e objetivos dos nossos Clientes, fornecendo soluções e serviços de TI que contribuam para a realização de seus objetivos.

## Como se candidatar

Envie um e-mail para viviane.pereira@iteam.inf.br com seu currículo atualizado e pretensão de taxa/hora - enviar no assunto: Vaga no GITHUB - FrontEnd Angular - Remoto

## Labels

- Horário comercial
- Remoto
- Sênior
- PJ ou a combinar

**Comment by ITeam-oportunidades** [comment]
Vaga encerrada.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
