### ISSUE TITLE
[Remoto] Front-end Developer Senior no Justiça 4.0 (PNUD/ONU e CNJ)

### ISSUE THREAD

**Issue by ericageo** [frontendbr/vagas#7519]
## Sobre o projeto

**Justiça 4.0 é um dos maiores programas do mundo de transformação digital do Poder Judiciário.** Iniciado em 2020, fruto de um acordo de cooperação firmado entre o **Conselho Nacional de Justiça (CNJ)** e o **Programa das Nações Unidas para o Desenvolvimento (PNUD/ONU)**, o projeto visa desenvolver e aprimorar soluções tecnológicas para tornar os serviços oferecidos pela Justiça brasileira mais eficientes, eficazes e acessíveis à população, além de otimizar a gestão processual para magistrados, servidores, advogados e outros atores do sistema de Justiça. A iniciativa também dialoga com os Objetivos de Desenvolvimento Sustentável e com a Agenda 2030 da ONU.

**No momento, há 8 vagas abertas para nível pleno e 10 vagas para sênior.**

## Descrição da vaga

A Pessoa Desenvolvedora Front-End Sênior será responsável, sob supervisão dos Gerentes de Projeto, pelo desenvolvimento da interface gráfica de usuário das soluções previstas no Eixo 1 do Projeto. O(a) profissional selecionado(a) atuará em estreita articulação com os pontos focais no CNJ e no PNUD, codificando os artefatos necessários ao atendimento dos requisitos funcionais e não funcionais da solução, empregando processo de desenvolvimento, arquitetura de software, padrões de projeto, linguagens de programação e ferramentas previamente definidas. Para o alcance desse objetivo, estão previstas as seguintes atividades indicativas:

- Desenvolver os artefatos de software para implementação da interface gráfica dos usuários;
- Empregar o framework Angular, o framework de referência UIKit, da PDPJ-Br, e a linguagem de programação TypeScript no desenvolvimento de artefatos de frontend;
- Desenvolver artefatos de testes automatizados;
- Subsidiar o Gerente de Projeto e demais integrantes do time nas ações de planejamento e implementação do projeto, contribuindo para a definição e priorização do backlog do produto, do cronograma de projeto, dos backlogs de sprints e na realização de cerimônias e outros artefatos que venham a ser necessários;
- Atuar nas atividades de implantação, monitoramento da execução e suporte técnico e das soluções desenvolvidas;
- Aplicar conhecimentos, informações e melhores práticas em acordo com as metodologias estabelecidas pelo CNJ e o PNUD;
- Apoiar o(a) Desenvolvedor(a) Frontend Pleno(a) sempre que solicitado pelo Gerente de Projeto e/ou Arquiteto de Software;
- Desenvolver soluções estruturantes da PDPJ-Br;
- Desenvolver soluções técnicas para suportar outros serviços a serem desenvolvidos no contexto do projeto;
- Realizar outras tarefas, conforme demanda do supervisor designado.

## Local

Remoto

## Requisitos

**Obrigatórios:**

- Diploma universitário, preferencialmente nas áreas de Tecnologia da Informação, Ciência da Computação, Sistemas de Informação, Engenharia de Software, Análise de Sistemas, Engenharia da Computação e áreas correlatas ou diploma de pós-graduação lato ou stricto sensu,  preferencialmente nas áreas de Tecnologia da Informação, Ciência da Computação, Sistemas de Informação, Engenharia de Software, Análise de Sistemas, Engenharia da Computação e áreas correlatas.
- Para diploma universitário, é requerido o mínimo de 2 anos de experiência com desenvolvimento de softwares ou de atuação profissional ou acadêmica na área de tecnologia; para diploma de pós-graduação, não é requerido anos de experiência.

**Desejáveis:**

- Experiência no framework Angular;
- Experiência no desenvolvimento de interfaces gráficas de usuários conectadas a APIs REST;
- Experiência no desenvolvimento de artefatos de software para implementação da interface gráfica dos usuários;
- Experiência no desenvolvimento de componentes visuais;
- Experiência na utilização de bibliotecas de componentes visuais: Angular Material, Prime NG e congêneres;
- Experiência em métodos ágeis;
- Experiência no desenvolvimento de soluções baseadas em computação na nuvem, Virtual Machines (VMs), containers Docker e Kubernetes;
- Experiência na utilização de ferramentas de gerência do ciclo de vida de projetos, como Jira, Bugzilla, Rubicon, e congêneres;
- Experiência no uso de ferramentas de gestão de código fonte: Git, GitLab, GitHub e congêneres; e
- Experiência anterior no desenvolvimento de soluções para o Poder Judiciário também será considerada.

**Diferenciais:**
- Proficiência em Inglês;
- Certificação no framework Angular.

## Contratação

- A modalidade de contratação é NPSA (National Personnel Services Agreement), que representa um instrumento próprio do PNUD utilizado internacionalmente para padronizar e viabilizar a admissão de profissionais especializados, por tempo determinado. Essa modalidade assegura benefícios como seguro saúde, seguro de vida e férias.

## Como se candidatar

**No momento, há 10 vagas abertas para nível sênior e 8 vagas abertas para nível pleno.**
- O detalhamento completo da vaga de nível sênior e o formulário de inscrição estão disponíveis na plataforma de oportunidades do PNUD/ONU: https://bit.ly/pnud-devfrontendsenior 
- Para mais informações sobre a vaga de nível pleno, por favor acesse: https://bit.ly/pnud-devfrontendpleno
- Candidaturas até 22/11

#### Alocação
- Remoto

#### Nível
- Sênior
- Especialista

**Comment by mauriciolsilva** [comment]
Gostaria de uma oportunidade como aprendiz ou Junior

Em sex., 11 de nov. de 2022 14:31, ericageo ***@***.***>
escreveu:
