### ISSUE TITLE
[Santa Barbara D'Oeste] Front-End Developer na Acruxx

### ISSUE THREAD

**Issue by santoja** [frontendbr/vagas#752]
**Descrição da vaga**
Criar aplicativos front-end de web;
Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas;
Participar do processo criativo e auxiliar na construção dos sistemas;
Nos deixar impressionados com sua capacidade criativa.

**Local**
Remoto ou Escritório, Santa Barbara D'Oeste

**Benefícios**
VA
Reembolso de viagens caso seja remoto e venha para a empresa esporadicamente.
No caso de home office, ou caso o profissional deseje trabalhar com seu próprio equipamento, há um reembolso mensal pelo uso.

**Diferenciais**
Area de descanso
Frutas no escritório
Café expresso ou coado
Chá
Cachorro no ambiente de trabalho

**Requisitos**
**Obrigatórios:**

Experiência relevante em front-end
Bons conhecimento em JavaScript/CSS frameworks
Boa experiência em HTML5/CSS e na construção de websites responsivos/adaptáveis para mobile

**Desejáveis:**

Conhecimento em React.JS
Conhecimento em Semantic-UI

**Diferenciais:**
Contratação
CLT presencial ou remoto

Como se candidatar
Por favor envie um email para kaue@acruxx.com.br com seu CV anexado - enviar no assunto: Vaga Front-End

**Comment by LFeh** [comment]
Bacana!

**Comment by danielswater** [comment]
Enviado

**Comment by TailoMateus** [comment]
Olá @santoja, a empresa possui quantos funcionários?

**Comment by HaluDeCassia** [comment]
Excelente vaga. Me candidatei :smile:

**Comment by santoja** [comment]
@TailoMateus 30 entre presenciais e remotos. 
Mas por curiosidade, porque isso é importante?
Agradeço o feedback que posso colocar nas próximas vagas

**Comment by TailoMateus** [comment]
@santoja, apenas por curiosidade mesmo. Não encontrei na internet.

Obrigado.

**Comment by netstart** [comment]
Já vi um projeto se (^*%^&$#@! por causa da escolha desse semantic ui, cuidado!

**Comment by yuritoledo** [comment]
Currículo enviado! Veja assim que puder :)

**Comment by santoja** [comment]
@netstart Ele funciona até que bem, mas não vamos colocar nos próximos projeto porque falta algumas funcionalidades na versão do React. No projeto atual é ele e não está nos planos mudar.

**Comment by danielswater** [comment]
@santoja como está esse processo seletivo?

**Comment by danielsidev** [comment]
Olá @santoja !
A vaga é muito boa!
Me candidatei! :)

**Comment by allbarbos** [comment]
Participei de um processo seletivo pra web a alguns meses atrás e hoje não me retornaram nenhum feedback :grimacing:

**Comment by santoja** [comment]
Tudo bem @allbarbos?

Estranho, respondi todos os candidatos por email quando fechamos a vaga no final do ano passado, talvez o e-mail de agradecimento não tenha chego.

Esse é outro processo seletivo para 2 vagas, se quiser pode participar novamente :)

**Comment by renanlara** [comment]
@santoja, eu me candidatei a outra vaga e a essa também e eu não recebi nenhum tipo de e-mail.

**Comment by santoja** [comment]
Recebi seu CV no dia 23/01 @renanlara, sou gerente de desenvolvimento aqui e estou rodando o processo junto com todas as outras atividades aqui da empresa. Tenha um pouco de paciência e empatia =).

**Comment by renanlara** [comment]
Puxa vida, desculpa a arrogância @santoja.
Mas me refiro a data de 27/10/2017 especificamente :)

**Comment by santoja** [comment]
Pessoal, estou fechando a vaga para novos CVs, mas estou no processo seletivo ainda está acontecendo, se você não recebeu um e-mail até agora, ainda está nele =).
