### ISSUE TITLE
[REMOTO] Estágio para front-end developer na Razzo.tech

### ISSUE THREAD

**Issue by neomarbassani** [frontendbr/vagas#7520]
## Descrição da vaga

Novas vagas de estagio aqui na Razzo. O nosso ambiente é 100% remoto e priorizamos sempre a cooperação entre todos os membros do time, além da abertura para trazer novas ideias aos projetos. Caso selecionado, você terá um líder técnico e de projeto, que irá lhe ajudar no seu desenvolvimento e qualificação profissional.

Nosso modelo permite que você se desenvolva rapidamente, atuando em um dos nossos projetos, provendo um ambiente de aprendizado contínuo.

**Requisitos Obrigatórios:**
- Bom relacionamento interpessoal
- Muita vontade de aprender

**Stacks trabalhadas**
- React / React native
- React hooks
- Styled components
- Redux Saga / Duck pattern
- NodeJS
- MongoDB

### Nossa empresa

A Razzo é uma Software House gaúcha focada no desenvolvimento de softwares e soluções inovadoras, sempre buscando encarar novos desafios. Nosso time é composto por gerentes de negócio, designers e um seleto time de desenvolvedores, que atuam em conjunto com seus lideres em diversos projetos.

## Como se candidatar

Por favor envie um email para jobs@razzo.tech

#### Regime
- De 20 à 30h semanais / 100% Remoto

### Valor
- R$ 600,00 à R$ 1.200,00

#### Nível
- Estagio

**Comment by DanielSiilva** [comment]
Enviado!

**Comment by MarcosBastosSilva** [comment]
Enviado!

**Comment by Higor-Emanuel-Ribeiro** [comment]
Enviado

**Comment by nashEm8** [comment]
Enviado, gostaria muito de uma oportunidade :')

**Comment by dniemeryers** [comment]
Enviado!

**Comment by Veko0** [comment]
Enviado, agradeço a atenção

**Comment by BiAniTy-AML** [comment]
Enviado!

**Comment by Kaiqueliira** [comment]
Enviado.

**Comment by helderdsa** [comment]
Enviado!

**Comment by igormath** [comment]
Enviado!

**Comment by GelsonMatias** [comment]
Enviado

**Comment by jonatasvaz** [comment]
Enviado

**Comment by mariyzx** [comment]
Enviado!

**Comment by joaomarcossb** [comment]
Enviado :)

**Comment by AndersonAngelo** [comment]
Sended!

**Comment by jonatassx96** [comment]
Sended :)
