### ISSUE TITLE
[Remoto] Tech Lead Frontend na Coodesh

### ISSUE THREAD

**Issue by blankapf** [frontendbr/vagas#7523]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/techlead-frontend-134154822?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>SolarZ</strong> está em busca de <strong><ins>Tech Lead Frontend</ins></strong><strong> </strong>para compor seu time!</p>
<p></p>
<p><strong>Responsabilidades:</strong></p>
<ul>
<li>Liderar pequenos squads nas nossas demandas de frontend;</li>
<li>Receber e analisar requisitos;</li>
<li>Distribuir tarefas para o time, acompanhando as entregas das tarefas;</li>
<li>Fazer code review, remover impedimentos dos desenvolvedores e também desenvolver.&nbsp;</li>
</ul>
<p>Somos uma startup em crescimento e estamos atrás de profissionais maduros que tragam boas práticas de mercado para nossa empresa. Se acredita que pode nos ajudar, aplica para a vaga que gostaríamos de bater um papo!</p>

## SolarZ: 
 <p>A SolarZ é uma startup que desenvolve soluções para o mercado de energia solar. Já somos a maior plataforma de monitoramento para sistemas de energia solar do Brasil, monitorando mais de 200 mil usinas de mais de 2.300 empresas. Lançamos recentemente nossa solução de crédito para financiamento de sistemas de energia solar e nossa solução de CRM.</p>
<p>Estamos crescendo em ritmo acelerado e recentemente fomos investidos pela Bossa Nova e Domo Invest, dois dos principais fundos de Venture Capital que atuam no Brasil, isso insere a SolarZ no principal ecossistema de crescimento de crescimento acelerado para empresas de tecnologia.</p><a href='https://coodesh.com/empresas/solarz'>Veja mais no site</a>

 ## Habilidades: 
 - React.js 
- React Native 
- Análise de requisitos 
- Gestão de times de tecnologia 
- Code Review
## Local: 
 100% Remoto
## Requisitos: 
 - Ser capaz de líderar um squad pequeno; 
- Treinar o time; 
- Introduzir boas práticas de desenvolvimento de software; 
- Pensamento crítico e proatividade; 
- Experiência sólida no desenvolvimento de projetos de software.
## Diferenciais: 
 - Java; 
- AWS; 
- UI/UX.
## Benefícios: 
 - Plano de Saúde; 
- Férias; 
- 13º Salário.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Tech Lead Frontend na SolarZ](https://coodesh.com/vagas/techlead-frontend-134154822?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
