### ISSUE TITLE
[Remoto] Front-end Developer na Life Software Development

### ISSUE THREAD

**Issue by mdiniz007** [frontendbr/vagas#7524]
Life Software Development

## Descrição da vaga

Projetar e implementar recursos e aplicativos voltados para usurário.
Implementar código testáveis de frontend focado em desempenho e manutenção em mente.
Participar de code review, manter a mente aberta em relação a feedback e compartilhando seus conhecimentos com outros membros da equipe

## Local

Remoto

## Requisitos

**Obrigatórios:**
3+ anos de experiencia na área em frontend
1+ anos de experiencia em React
Forte compreensão das estruturas React/JavaScript
Experiencia em desenvolvimento e integração em APIs
inglês intermediário

## Como se candidatar

lifesoftwaredevelopment@gmail.com
telefone/whatsapp: (83) 99849-9750

## Salário:

A partir de 10 mil por mês

#### Alocação

- Remoto

#### Regime

- CLT

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by ItaloRAmaral** [comment]
Enviado!

**Comment by paulomonezi** [comment]
Enviado!  :)

**Comment by clowdcap** [comment]
Encaminhado

**Comment by isbeli** [comment]
Enviado.!

**Comment by GabrielVinhas** [comment]
Curriculo enviado

**Comment by sucodev** [comment]
Enviado!

**Comment by eng-Bruno** [comment]
Enviado.

**Comment by gmartpad** [comment]
Enviado!

**Comment by Jp-bruno** [comment]
Enviado 😎

**Comment by DevCleverton** [comment]
### 

- [ ] **Up**

**Comment by aspeddro** [comment]
Enviado

**Comment by Rendrikson98** [comment]
Enviado

**Comment by juliabergman** [comment]
enviado!

**Comment by GefersonLopes** [comment]
Enviado ;)

**Comment by CayoNakasato** [comment]
Enviado :))
