### ISSUE TITLE
100% REMOTE - Lead Frontend Architect/Engineer - React - EMPRESA VIGIL

### ISSUE THREAD

**Issue by anezkahonke** [frontendbr/vagas#7526]
**VAGA 100% REMOTO
Lead Frontend Architect/Engineer - React
EMPRESA VIGIL
CONTRATO PJ**
SALARIO em euros 

**WHAT WILL YOU BE DOING:**

You will be joining our engineering team and be a valued member working closely in a collaborative, autonomous, cross-functional team. You will help with:

Review of current frontend architecture with the goal of providing suggested improvements and updates.
Architect a multi-product, multi-platform frontend that meets all functional and non-functional requirements.
Lead, manage, and mentor other members of the frontend team, providing on-the-job training and guidance.
Design, develop and deploy user experiences with a focus on usability, high availability, low-latency, and scalability.
Operational responsibility for the services that are owned by your team in a DevOps culture.
Assist in story grooming and estimation.
Write performant and thoroughly tested code (unit and/or functional tests as appropriate).
Propose technical decisions and contribute to the project using software development best practices and tools.

**WHAT WE ARE LOOKING FOR:**

7+ years of web UI development experience
2+ frontend leadership experience
3+ years frontend architecture experience
3+ years of ReactJS
Large experience with Typescript
Expert with Redux, Hooks and Context
Experience with Styled Components or other CSS frameworks
Experience developing enterprise web applications
Experience developing multi-product, multi-platform frontends
Experience in frontend automated tests
CI/CD pipeline

**AWESOME BUT NOT REQUIRED:**

OpenAPI (swagger)
Cypress
React Testing Library
React-Query
Any software architecture methodology (SEI, C4, UML, etc.)

**WHAT’S IN IT FOR YOU?**

Be part of our collegial environment where responsibility and authority is shared equally amongst colleagues and help create our company culture
A culture in which we don’t criticize failure but ensure we learn from our mistakes
An Agile environment where your ideas are welcome
The possibility to grow and experience different projects
Fully remote
Ongoing Training & Mentoring
The possibility to travel (when we are allowed)

**HOW TO APPLY:** send cv to anezka.honke@vigil.global or LinkedIn https://www.linkedin.com/in/anezkahonke/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
