### ISSUE TITLE
[Remoto | Berlim | Viena | Barcelona] Senior Vue.js Engineer @ Friday Finance

### ISSUE THREAD

**Issue by ErickPetru** [frontendbr/vagas#7528]
## Nossa empresa

Olá, sou Erick, alguns talvez me conheçam como [community partner do Vue.js](https://vuejs.org/about/team.html), e sou o Head of Engineering na [Friday Finance](https://www.fridayfinance.com/).

Nós somos uma _fintech_ sediada em Berlin/Alemanha, mas com time multinacionalmente distribuído em vários fusos horários. Fundada no início de 2021 como Airbank, acaba de passar por rebranding para melhor ilustrar seu foco expandido, originalmente de solução multi-banking para uma plataforma completa de operações financeiras para SMBs europeias.

Com franco crescimento em pouco tempo, já levantou três rodadas de investimento, sendo o último de $20 milhões. Contando atualmente com cerca de 60 pessoas (e subindo), mais de 20 pessoas incríveis estão na área de engenharia (cá entre nós, vários brasileiros). Até o [Techcrunch](https://techcrunch.com/2021/06/22/airbank-centralizes-all-your-business-bank-accounts-and-financial-data/) já falou sobre nós, dentre vários outros canais de comunicação!

## Descrição das vagas

Estamos com **2 vagas** abertas para **Senior Vue.js Engineer**. Aqui na Friday Finance trabalhamos com a ideologia de que todos podem (e deveriam) ser engenheiros(as) _full-stack_, mas reconhecemos a importância do Vue.js na nossa _stack_ e estamos priorizando encontrar profissionais com elevadas habilidades neste ecossistema, com a certeza de que engenheiros(as) realmente seniores podem se adaptar rapidamente ao restante das tecnologias.

Nossa aplicação principal permanece em constante evolução, sendo que para tal trabalho, um misto de manutenção e evolução contínua (e com novas _features_ interessantes e desafiadoras entrando frequentemente), nos organizamos em múltiplos esquadrões temáticos, compostos por um líder técnico, um _developer_ sênior, e de três a quatro _developers_ júnior/pleno.

Para ler mais sobre as atribuições e responsabilidades desta posição, dê uma olhada neste [descritivo](https://fridayfinance.factorialhr.com/job_posting/senior-full-stack-developer-20271).

## Local

**Remoto**, ou híbrido em escritórios em Berlin/Alemanha, Viena/Austria ou Barcelona/Espanha.

## Requisitos

**Obrigatórios:**
- Inglês avançado.
- Ao menos 5 anos de experiência com desenvolvimento Web moderno (HTML, CSS, ECMAScript).
- Ao menos 3 anos de experiência com Vue 2.
- Ao menos 1 ano de experiência com Tailwind.

**Desejáveis:**
- Experiência com Vue 2.7 ou Vue 3 (Composition API).
- Experiência em Nuxt 2.
- Conhecimentos em Vuex.
- Conhecimentos em GraphQL.

**Diferenciais:**
- Ter projetos _open-source_ com Vue e/ou Nuxt para exibição.
- Já ter criado alguma biblioteca de components/_design system_ com Vue.
- Experiência em desenvolvimento _back-end_ com GraphQL.
- Experiência com bancos de dados relacionais e escrita de comandos SQL.

## Benefícios

- Salário competitivo em Euro! 💶🤑
- Contratação _**full-time**_, não é projeto temporário.
- Trabalho _**remote-only**_ ou _**remote-first**_, como preferir, o que significa:
  - A visibilidade de atuar em uma empresa europeia, mas sem ter de se mudar de onde você gosta;
  - Ou trabalho híbrido em Berlin/Alemanha, Viena/Austria, ou Barcelona/Espanha, se quiser residir na Europa.

**Diferenciais:**

- _Startup_ de alto crescimento e potencial.
- Time muito competente e motivado, diferentes _expertises_ e muita troca de conhecimento.
- Ambiente positivo de trabalho, com respeito ao _work-life balance_.
- Eventuais encontros presenciais coletivos, organizados pela empresa (o último foi no Rio de Janeiro).

## Contratação

PJ a combinar.

## Como se candidatar

[Aplique-se para a vaga](https://fridayfinance.factorialhr.com/apply/senior-full-stack-developer-20271), seguindo o processo do formulário de inscrição e destacando que encontrou a oportunidade através da comunidade Front-end Brasil.

## Tempo médio de feedbacks

Costumamos enviar _feedbacks_ agendando a primeira etapa (entrevista em inglês com nossa Head of Talent) em até 5 dias úteis após a inscrição. E-mail para contato em caso de acontecer algum problema e não haver resposta: jobs@fridayfinance.com.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by ErickPetru** [comment]
@felipefialho, agradeço a organização com os _labels_, mas destaco que as vagas são restritas para Sênior/Especialista, não estamos contratando Júnior e Pleno neste momento. Além disso, não temos escritório no Rio de Janeiro, pode manter somente o _label_ Remoto caso não hajam _labels_ para cidades do exterior.

**Comment by K-Schaeffer** [comment]
Ficou muito bom o descritivo da vaga, parabéns.

Irei me aplicar.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by lucastllima** [comment]
@ErickPetru enviei uma mensagem para ti no Linkedin

**Comment by ErickPetru** [comment]
Sim, há uma posição sênior restante aberta para um novo esquadrão formado.
Aproveito para reforçar que é uma posição _full-time_.

**Comment by lucastllima** [comment]
@ErickPetru será que posso me candidatar para esse novo esquadrao? Eu me candidatei anteriormente para o outro, mas recebi um decline, via site nao consigo :/

**Comment by vcpablo** [comment]
@ErickPetru também me candidatei anteriormente e a aplicação não foi em frente.
Houve uma falha na comunicação quanto à disponibilidade _full-time_.

Eu teria interesse de me candidatar de novo.

**Comment by ErickPetru** [comment]
@lucastllima, @vcpablo, podem sim. Entendemos que as situações mudam, tanto para a empresa quanto para o profissional, então os motivos que fizeram aquele _fit_ não acontecer anteriormente, podem ser diferentes agora.

Enviem e-mail diretamente para [jobs@fridayfinance.com](mailto:jobs@fridayfinance.com) explicando que já tiveram uma aplicação no passado, e por isso não conseguem se cadastrar novamente no sistema de vagas, mas que desejam participar novamente do processo para a nova vaga de desenvolvedor sênior _full-stack_ disponível atualmente.

**Comment by ErickPetru** [comment]
Todas as vagas preenchidas no momento. Nova postagem será publicada em ocasião futura, quando novas posições forem abertas.
