### ISSUE TITLE
[Alocação Internacional - 100% Remoto] Front-end Angular Developer na @SevenApps

### ISSUE THREAD

**Issue by rhSevenApps** [frontendbr/vagas#7530]
**Job description**
Are you looking for new challenges?! What if you could work on an incredible international project, receive in dollar and still receive all the support from high-performing Brazilian colleagues?

At SevenApps, you will be close to the best technologies on the market, work on challenging projects and in a rich learning environment. We are looking for proactive, experienced devs who are in search of experiencing this immersion in the culture of the North American market.

In this position, you will work allocated to an international project for a large Florida company, and you will have the autonomy and freedom to work 100% remotely, with flexible hours. Your challenges will involve front-end web (Angular) development: 

- Design, development, enhancement, triage, and debugging of Angular applications.
- Ensuring that all key technical requirements are identified, estimated, designed, documented, implemented and integration tested.
- Producing detailed technical specifications based on business requirements documents.
- Ensuring that consistent design patterns, methodologies, and design documentation are maintained across all of your development projects.
- Performing and supporting technical & design reviews of your own and other projects.
- Working closely with the Business Analysts, Testing, and Support teams to ensure all technical requirements for new projects are captured, designed and developed according to those requirements.
- Ensuring urgent customer issues are resolved through triaging, troubleshooting and quickly applying solutions to any identified problems

 
You will have a highly skilled team to implement these solutions with you.

We believe that technology has the power to transform, improve the way we live and face challenges. If you believe that too, come be part of our team!

**Location**
100% remote alocated for SevenApps Company at an internacional project 

**Requirements**

- 5+ years of experience working on Front End development
- Must have 3+ years of experience with Angular
- 5+ years of working knowledge with: - HTML5, CSS3, SASS, JavaScript, TypeScript, REST Web Services, Data Binding
- React, Angular, Git, Jenkins and CI/CD server
- Experience using Agile methodologies for developing application
- Strong communication and organizational skills with an ability to thrive in a fast-paced production deadline-driven environment both internal and client facing
- English Advanced

 **Benefits**

- **PJ Contract (R**ange S**alarial : 3,5-4 k usd)
- ‍**Periodic salary review:** review every 6 months;
- **15 Days Free:** paid rest for 15 days a year;
- **Flexible Hours:** Work when you feel most productive
- **Periodic workshops:** moments with the entire team, generating a community of knowledge exchange and development among professionals;
- **Weekly monitoring:** weekly meetings with the other managers of the team, generating a community of knowledge and mutual exchange between professionals;
- **International Immersion:** international culture with projects outside Brazil;
- **Referral Bonus:** Help us bring the best devs to our team

**How to apply**
Send an email to: [rh@sevenapps.com.br](mailto:rh@sevenapps.com.br) with the subject "Front-end Position | Angular" or contact us in Whatapp **(31) 99619-2078**!

Learn more about our SevenApps code: **https://www.sevenapps.tech/us/for-devs**

**Start your journey with SevenApps!
Come be a Thunder!**

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
