### ISSUE TITLE
[Remoto] Developer na Multinacional ESSS

### ISSUE THREAD

**Issue by Esss0102** [frontendbr/vagas#7531]
> Vaga Remota durante a pandemia

## Nossa empresa

A ESSS é uma multinacional brasileira sediada na cidade de Florianópolis/SC. Disponibilizamos ao mercado as mais avançadas ferramentas de CAE na área de fluidodinâmica, análise estrutural, eletromagnetismo e multifísica, além de customização e desenvolvimento de softwares sob medida de acordo com a necessidade de cada cliente. Estamos presentes no Brasil e no exterior, incluindo Argentina, Chile, Colômbia, Peru, Portugal, Espanha, México e Estados Unidos.

Se você acredita que suas habilidades, talento e experiências são diferenciados para trabalhar em um time de alta performance, responsável pela resolução de problemas por meio da tecnologia e desenvolvimento de softwares, faça sua inscrição.

## Descrição da vaga

Se você é um entusiasta por inovação e tecnologia e busca uma empresa onde possa compartilhar ideias, conquistas e trabalhar em um ambiente saudável, onde possa se desenvolver pessoal e profissionalmente, estamos com oportunidades em aberto para Desenvolvedor de Software. 

Para essa posição seus principais desafios serão: 

Desenvolver softwares de simulação computacional para engenharia.
Desenvolver aplicações Web com testes automatizados (testes unitários e de aceitação).
Integrar as bibliotecas desenvolvidas pelo nosso time de desenvolvimento numérico e científico em aplicações gráficas para o usuário final.

Tecnologias que Utilizamos:

TypeScript e Python 3.
Aplicações Web em Angular.
Back-end utilizando Tornado, SQLAlchemy, Redis.
Banco de dados Postgres.
Infraestrutura com Docker.
Testes automatizados (unitários, integração e end-to-end).
Metodologias Ágeis (Integração Contínua, Revisão de Código, SCRUM).

## Local

 Remoto ou Florianópolis/SC

## Requisitos

Requisitos Exigidos:

Experiência com algum framework web (de preferência Angular).
Não é necessário conhecimento em todas tecnologias listadas acima, entretanto experiência prévia será considerada para definição do nível do cargo (júnior, pleno).
Inglês intermediário.

Requisitos Desejados:

Familiaridade com UX/UI (conhecimentos de CSS, Flexbox).
Conhecimento de RxJS.
Experiência com APIs REST.
Experiência básica com Python.

## Benefícios

Plano de saúde nacional com subsídio integral sem coparticipação (melhor operadora da região).
Cartão de benefícios flexíveis.
Licença maternidade e paternidade estendidas.
Oportunidade para contribuição em projetos open source.
Incentivo a educação continuada através de cursos, treinamentos e especializações e auxílio idiomas.
Incentivo a publicações, participações em eventos de tecnologia relevantes para seu trabalho.
Mais de 20 outros benefícios.

## Contratação
 
CLT

## Como se candidatar

Envie um e-mail para selection@esss.co com seu CV anexado, ou se inscreva no link: https://esss.gupy.io/jobs/3242317

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by Andrei-hub11** [comment]
O que colocar no assunto do e-mail?

**Comment by ValdineiJunior** [comment]
Interessante a vaga, mas uma dúvida nas labels foi adcionado Júnior. Mas na descrição da vaga consta somente. 
Nível
Pleno
Sênior
Especialista

**Comment by tascintra** [comment]
> Interessante a vaga, mas uma dúvida nas labels foi adcionado Júnior. Mas na descrição da vaga consta somente. Nível Pleno Sênior Especialista

No gupy deles tá como dev full stack sr.

**Comment by guimevn** [comment]
Enviado.

**Comment by GabrielFray** [comment]
Enviado!

**Comment by joaov1ct0r** [comment]
Enviado

**Comment by FeRiffo** [comment]
Enviado!

**Comment by josephmatheus** [comment]
Currículo enviado.

**Comment by Virkkunen** [comment]
Enviado

**Comment by hignicao** [comment]
Enviado!

**Comment by MatheusFilg** [comment]
enviado!

**Comment by MateusGutierrez** [comment]
Enviado!

**Comment by thiagofm2** [comment]
Currículo enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
