### ISSUE TITLE
[Remoto] Front-end Developer na Yever

### ISSUE THREAD

**Issue by andretrevas** [frontendbr/vagas#7533]
## Descrição da vaga

Como desenvolvedor front-end, você irá trabalhar na criação e desenvolvimento de um novo gateway de pagamento, interagindo com o time de designer para criar/melhoras as telas e as funcionalidades da aplicação. Utilizamos métodos ágeis, principalmente Scrum.
Ambiente descontraído, equipe enxuta, time focado em entregar valor para empresa e que se preocupa com o cliente.

## Local

100% Remoto

## Requisitos

**Obrigatórios:**
- Conhecimentos em Javascript e biblioteca React (principal foco de trabalho)
- Experiência com desenvolvimento web
- Experiência com o framework Next
- Experiência com SPA
- Conhecimento em pré-processadores CSS (Sass, Less)

**Desejáveis:**
- Experiência com Server-Side Rendering (SSR), Static Site Generation (SSG), Incremental Static Regeneration (ISR)
- Experiência com Redux ou React Context API
- Experiência com componentes funcionais

## Benefícios

- Possibilidade de contratação PF (mantendo o valor do PJ) após 6 meses de contrato
- Flexibilidade de horários
- Home office

**Diferenciais:**
- Horário 100% flexível
- Interação com equipe multi disciplinar -> Aumentar o conhecimento em todas as áreas (CI/CD, back-end, infraestrutura, banco de dados)
- Contato direto com os sócios (grandes nomes do mercado no nosso nicho)
- Possibilidade de participação societária na empresa

## Contratação

PJ

## Como se candidatar

Por favor envie um email para andre@yever.com.br com seu CV anexado - enviar no assunto: Vaga React

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by ItaloRAmaral** [comment]
Enviado!

**Comment by herbertamaro2** [comment]
Enviado! Obrigado!!
