### ISSUE TITLE
[Híbrido/ Remoto ou Presencial em Florianópolis-SC]-  Front-end Developer na  J&A Holding / Fontes Promotora

### ISSUE THREAD

**Issue by jeavagas** [frontendbr/vagas#7535]
## Nossa empresa

Não conhece a Fontes Promotora?

Nós somos a Maior do Mercado! Estamos pelo Brasil todo e contamos com mais de 30 filiais! A Fontes Promotora faz parte da J&A Holding, que conta com 12 empresas em três ramos diferentes: financeiro, tecnologia e varejo!

Buscamos pessoas com muita vontade de crescimento e ambição!

Se esse também é o seu desejo, venha trabalhar em uma das empresas que mais cuida e engaja seus colaboradores.
Confira um pouquinho do nosso dia-a-dia pelo nosso perfil do instagram: https://www.instagram.com/fontespromotora/!

## Descrição da vaga

Atuar na manutenção das atuais páginas, sejam fronts de sistemas ou landing page, etc
Contribuir no desenvolvimento de novas telas, de acordo com as regras de negócios e integrando com backend da aplicação
Saber comentar o código pensando que outras pessoas irão atuar em algum outro momento nesse seu desenvolvimento.
Contribuir com a squad no qual estará inserido, seja codando, seja configurando um plugin, seja instalando algum serviço, etc, atividades que vão tirar você especificamente do código, mas vão contribuir para o seu crescimento, e consequentemente para as entregas da equipe como um todo.

## Local

 Remoto, Híbrido ou Presencial em Florianópolis - SC. 

## Requisitos

**Obrigatórios:**

Experiência com HTML5, CSS3, Javascript e Typescript
Experiência em frameworks frontend como React, VITE, Vue, no caso da stack do Javascript ou Django no caso da stack Python
Experiências nas bibliotecas Redux, Flux e Hooks
Aplicação de testes unitários, Clean Code e Clean Architecture

**Desejáveis:**

Atuar na manutenção das atuais páginas, sejam fronts de sistemas ou landing page, etc
Contribuir no desenvolvimento de novas telas, de acordo com as regras de negócios e integrando com backend da aplicação
Saber comentar o código pensando que outras pessoas irão atuar em algum outro momento nesse seu desenvolvimento.
Contribuir com a squad no qual estará inserido, seja codando, seja configurando um plugin, seja instalando algum serviço, etc, atividades que vão tirar você especificamente do código, mas vão contribuir para o seu crescimento, e consequentemente para as entregas da equipe como um todo.

## Benefícios

Oferecemos oportunidade de crescimento interno, ações do nosso endomarketing como: Dia do doce, day off no aniversário, premiação por tempo de casa e rodas de conversa focado na saúde mental.

## Contratação

PJ por tempo indeterminado. 

## Como se candidatar

Via plataforma indeed: https://employers.indeed.com/jobs/view?id=e6d17ac353f4
Via plataforma sólides: https://fontesvagas.solides.jobs/vacancies/197763?__hstc=127459538.925b85e07b89519038504fed6a5ef1b4.1666278162381.1669149290760.1669232298430.73&__hssc=127459538.3.1669232298430&__hsfp=3185375410
Via telefone do recrutamento e seleção: +55 48 9164-0011
Via e-mail: talentos@jeaholding.com.br

#### Alocação

- Se presencial em Florianópolis-SC. 

#### Regime

- PJ

#### Nível

- Pleno

**Comment by matheuslei** [comment]
Enviado 😉

**Comment by raphaelalmeidamartins** [comment]
Enviado :white_check_mark:
