### ISSUE TITLE
[Remoto] Desenvolvedor FullStack Mid - Spring Boot, Flutter

### ISSUE THREAD

**Issue by Renatatsi** [frontendbr/vagas#7536]
## Nossa empresa

Empresa Americana no segmento de saúde.

## Descrição da vaga

Inglês avançado (verbal e escrito)
+3 anos trabalhando e desenvolvendo com Flutter e Spring Boot. (não conta estágio, autônomo e freelancer)

## Local

Remoto

## Requisitos

**Obrigatórios:**
Spring boot, Flutter
Inglês avançado (verbal e escrito)

## Contratação

PJ

## Como se candidatar

Por favor envie um email para renata@travessiasolucoes.com.br com seu CV anexado - enviar no assunto: Desenvolvedor FullStack Mid.
LinkedIn: https://www.linkedin.com/in/renata-oliveira-77395898/

#### Alocação
- Remoto

#### Regime
- PJ

**Comment by icaroamb** [comment]
Então porquê foi colocado a label de estágio? hahahaha
