### ISSUE TITLE
[Remoto] Pessoa desenvolvedora front-end na FTD Educação

### ISSUE THREAD

**Issue by garboso** [frontendbr/vagas#7541]
## Nossa empresa

A FTD Educação tem como missão levar uma educação transformadora até as escolas, apoiada em valores que ajudam crianças e jovens na formação como cidadãos protagonistas e ativos em sociedade. Assim foi conquistada não só a sua consolidação no mercado editorial, mas também o seu reconhecimento como uma empresa que pensa além. 

## Descrição da vaga

Oportunidade de participar do desenvolvimento de objetos educacionais digitais para diversos editoriais e selos da editora, do ensino infantil ao ensino médio. É uma ótima oportunidade para quem está começando a lidar com ferramentas que constroem a web.

## Local

Remoto, mas o prédio da sede Matriz da empresa (em São Paulo, SP) fica disponível para ser utilizado quando necessário, levando o seu próprio equipamento. 

## Requisitos

**Obrigatórios:**
- HTML semântico e adequado aos princípios de acessibilidade web
- Fluidez ao criar estilos com CSS
- Fundações do Javascript, principalmente manipulação do DOM
- Familiaridade com Git e SVN
- Interesse em criar rotinas de testes automatizados

**Desejáveis:**
- Interesse na área educacional e desenvovlimento de jogos
- Conhecimento de conceitos de UX e CX
- Facilidade em se comunicar e participar de reuniões
- Familiaridade com ferramentas de produtividade (Teams, Sharepoint e Planner)
- Disposição para participar de um momento de transformação digital

**Diferenciais:**
- Conhecer um tanto de nodejs e algum de seus frameworks (hapi, express, koa)
- Saber configurar bem o webpack
- Ter alguma experiência com Azure Web Apps
- Ser capaz de criar scripts de manipulação de arquivos que executem no PowerShell

## Contratação

PJ, com salário a combinar, início imediato

## Como se candidatar

Por favor, envie um email para christopher.silva@ftdse.com.br com seu CV e link para portfólio - enviar no assunto: Vaga Front-End - Produção Digital

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após cada processo.
E-mail para contato em caso de não haver resposta: christopher.silva@ftdse.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior

**Comment by matheuslei** [comment]
Enviado 😉

**Comment by MarcosBastosSilva** [comment]
Enviado!
