### ISSUE TITLE
[Remoto] Front-end React (Júnior/Pleno) Developer na Trevio

### ISSUE THREAD

**Issue by matheusmoretti1** [frontendbr/vagas#7542]
## Nossa empresa
A Trevio é uma empresa com foco em desenvolvimento de sistemas de tracking e acompanhamento de pedidos e processos, atualmente focamos na área de desenvolvimento web e desktop. Atuamos com diversos clientes em diferentes ramos do mercado nacional, desde automóveis, até mercados e hospitais.

## Descrição da vaga
A vaga é para trabalhar no Front End, atuando com React na criação de layouts, autenticação de usuário e gerenciamento de estado global usando Redux, e o candidato também receberá acompanhamento e treinamento dos devs de maior sênioridade nas tecnologias que surgirem necessidade.

## Local
Remoto

## Requisitos
**Obrigatórios:**

* React, Next.js, Redux
* HTML
* CSS/SASS
* Git

**Desejáveis (Opcionais, mas são um bônus caso tenha):**
* Confortável com scrum e entregas ágeis
* Material UI/Tailwind/Bootstrap
* Projetos utilizando padrões de design e estrutura de arquivos modernos.
* Testes de software

**Benefícios:** 
* Horário Flexível 
* Gym pass
* Acesso a alura e udemy
* Contribuição em projetos open-source da empresa.

## Contratação
- CLT 
- PJ

## Como se candidatar
Entre em contato por e-mail enviando seu currículo para [trevio.vagas@gmail.com](mailto:trevio.vagas@gmail.com), assunto: Vaga Front-End/React

## Disponibilidade
Vaga para ser preenchida com urgência, disponibilidade para início imediato.

#### Alocação
* Remoto

#### Regime
* CLT
* PJ

#### Nível
* Junior
* Pleno

**Comment by raphaelalmeidamartins** [comment]
Enviado :rocket:

**Comment by reita009** [comment]
Enviado

**Comment by ItaloRAmaral** [comment]
Enviado

**Comment by GabrielGomesFer** [comment]
Enviado

**Comment by maycondouglas1** [comment]
Enviado

**Comment by LilithGouveia** [comment]
Enviado

**Comment by Henry001-prog** [comment]
Enviado!

**Comment by Rendrikson98** [comment]
Enviado

**Comment by gabriellfernandes** [comment]
Enviado

**Comment by MatheusdeSouzaSilva70** [comment]
Enviado

**Comment by aragornbp** [comment]
Enviado!

**Comment by SamGCM** [comment]
Enviado

**Comment by anacleto616** [comment]
Enviado

**Comment by jukerah** [comment]
Enviado

**Comment by nittts** [comment]
Enviado ^^

**Comment by lnabesima** [comment]
Currículo enviado!

**Comment by waltodd** [comment]
Done!

**Comment by eddotbarbosa** [comment]
Enviado

**Comment by mathsudre** [comment]
Enviado

**Comment by natamartins** [comment]
Enviado!!

**Comment by devsantosbruno** [comment]
Enviadoo!

**Comment by iamrosada** [comment]
Enviado! ;)

**Comment by mauriciolsilva** [comment]
Enviado

Em qui., 22 de dez. de 2022 10:53, LUÍS DE ÁGUA-ROSADA <
***@***.***> escreveu:

**Comment by Gabrielperes12** [comment]
Enviado!

**Comment by jeffersondrs** [comment]
Está vaga continua em aberto?

**Comment by matheuszarpellon** [comment]
Enviado!

**Comment by m4yk3ldev** [comment]
Enviado!

**Comment by arlisson314** [comment]
enviado

**Comment by soloalex1** [comment]
enviado!

**Comment by DarcioCarvalho** [comment]
Olá. Tudo bem?

Enviei no e-mail indicado o meu currículo e informações adicionais.

Abraços!!!

**Comment by Jmaraguiar** [comment]
Enviado 🚀

**Comment by M4Y50N** [comment]
Enviado💯

**Comment by ronansalvador** [comment]
Enviado :rocket:

**Comment by sucodelarangela** [comment]
Enviado!

**Comment by DarlanSantosCarvalho** [comment]
Enviado

**Comment by AllanCunhaDev** [comment]
Enviei por email.
Abraço !

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by MatheusFilg** [comment]
Enviado

**Comment by ygg-m** [comment]
Enviado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by Hoffmann-Ferreira** [comment]
Currículo enviado! Obrigado.

**Comment by lucasbss2** [comment]
Currículo enviado. Obrigado!

**Comment by gvao** [comment]
Enviado o currículo para o e-mail.

Desde já agradeço pela oportunidade.

**Comment by lucasrip** [comment]
Currículo enviado. Obrigado!

**Comment by monsor3s** [comment]
Enviado 🚀🚀

**Comment by Fecef** [comment]
Enviado. Obrigado.

**Comment by JuliaRamos01** [comment]
Enviado!

**Comment by natamartins** [comment]
Curriculo enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by marcosHenrique-developer** [comment]
Enviado

**Comment by vanessawin** [comment]
Enviado
