### ISSUE TITLE
[Curitiba] Líder Técnico Front-End Angular - Gestran Software para Transportes

### ISSUE THREAD

**Issue by StephanieTafnes** [frontendbr/vagas#7543]
## Nossa empresa
A Gestran é uma empresa especializada em sistemas de gestão para transportes e logística. Se você deseja trabalhar em uma empresa dinâmica, ágil e com ambiente de trabalho super descolado e feliz, aqui é o lugar!

## Descrição da vaga

**Responsabilidades:**
Programar e fazer a manutenção e correções necessárias nos programas web e aplicações;
Desenvolve em HTML, CSS e JavaScript;
Produzir layout do produto digital e criando interatividade entre os elementos do aplicativo;
Estar atento à performance, semântica, pixel perfection (perfeição entre o layout e o código produzido) e cross-browser;
Monitorar o desempenho dos desenvolvimentos, assim como observar os possíveis problemas de usabilidade dos programas;
Colaborar com os desenvolvedores back-end e web designers para otimizar essa usabilidade;
Responsável por escrever documentos e guias de requisitos funcionais, conforme os projetos que participa.
 

**Requisitos:**
Mínimo de 2 anos na função;
HTML;
Scss;
JavaScript;
Formulários reativos;
Angular material;
C#;
banco de dados MySQL.

**Habilidades:**
Typescript;
RxJs;
GitHub;
OO.

**Habilidades Comportamentais:** 
Liderança técnica 
Gestão de equipe
Adaptabilidade
Proativo e atualizado com novas tendências na área
Análise de Problemas
Inovação
Dinamismo
Flexibilidade
Pro atividade
Resolução de problemas
Trabalho em Equipe
Olhar analítico
Cumprimento de prazos
Raciocínio Lógico

## Local
Água Verde, Curitiba - PR

## Benefícios
Vale refeição;
Vale transporte;
Treinamentos e workshops (internos);
Clube da fruta;
Seguro de Vida em Grupo;
Plano de saúde;
Convênio com instituições de ensino;
Clube de descontos;
Café da Manhã;
Ambiente descolado (puffs, free coffee, fruit at will);
Quick Massage;

## Como se candidatar
Realize sua candidatura em:  https://gestran.abler.com.br/vagas/desenvolvedor-front-end-angular-851531

#### Regime
- CLT

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
