### ISSUE TITLE
[Florianópolis] Front-end Developer na Viajar Faz Bem

### ISSUE THREAD

**Issue by rafaelnogueira1** [frontendbr/vagas#7544]
## Nossa empresa

Nós amamos viajar e trabalhamos por um mundo em que todo Brasileiro possa viajar também. Queremos que as pessoas conheçam novos lugares, interajam com diferentes culturas e vivam grandes experiências.
Trabalhamos com muita descontração, em um ambiente que vive a diversidade e promove a colaboração e a amizade. Não acreditamos que a roupa impacte no trabalho de cada um, gostamos da transparência, dos feedbacks, das falas olho-no-olho.
Acreditamos na constante troca de conhecimento. Gostamos de escutar suas opiniões e, sempre que possível, colocá-las em prática e, por isso, fomos consideradas umas das 10 melhores empresas para se trabalhar de Santa Catarina por 2 anos consecutivos.

## Descrição da vaga

Atuar na criação e manutenção de páginas e componentes utilizando ReactJS e NextJS.
Procuramos uma pessoa com perfil colaborativo, proativo, inovador, que se preocupa com a qualidade das entregas e que busca fazer o seu melhor todos os dias.
Trabalhamos em um ambiente de construção, leve e descontraído.

## Local

Remoto. Mas sempre que quiser fazer uma visita no escritório em Florianópolis será muito bem recebido.

## Requisitos

**Obrigatórios:**
- Proficiência em JavaScript
- Compreensão de React.js e seus princípios fundamentais
- Familiaridade com APIs RESTful
- Compreensão do uso da biblioteca Next.js
- Conhecimento sobre código limpo (clean code) e padrões de projeto
- Familiaridade com testes de navegador e depuração

**Desejáveis:**
- Compreensão dos conceitos de server side render
- Compreensão da criação/uso do Storybook
- Testes

**Diferenciais:**
- Conhecimento de acessibilidade
- Familiaridade com Design Systems
- Métodos de desenvolvimento ágeis
- Compreensão da criação de testes
- Inglês técnico

## Contratação

PJ a combinar

## Como se candidatar

Envie um  e-mail para rh@viajarfazbem.com, com o assunto: Vaga Front-end Developer.
Se possível com currículo/linkedin e repositório.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

**Comment by tascintra** [comment]
Enviado!

**Comment by GabrielGuedess** [comment]
Enviado 🚀

**Comment by MiroBenicio** [comment]
Enviado!

**Comment by danyelica** [comment]
Enviado!!

**Comment by ItaloRAmaral** [comment]
Enviado!

**Comment by TheHumphrey** [comment]
Enviado!

**Comment by Henry001-prog** [comment]
Enviado!

**Comment by Leonardoozx** [comment]
Já enviei meu currículo! :)

**Comment by JhowRodrigues2** [comment]
Enviado!

**Comment by LucianoNeo** [comment]
Enviado 😉

**Comment by Henry001-prog** [comment]
Enviado!

**Comment by Cientista-Avogadro** [comment]
Enviado

**Comment by Christian-mf25** [comment]
Enviado!

**Comment by ionansantos** [comment]
Enviado!

**Comment by DayanMonteiro** [comment]
Enviado!

**Comment by gabriellfernandes** [comment]
Enviado!

**Comment by JoaoPedroAC** [comment]
Enviado!
