### ISSUE TITLE
[REMOTO] Front-end Developer Júnior na Capreolus

### ISSUE THREAD

**Issue by AndreLefon** [frontendbr/vagas#7547]
## Nossa empresa

Somos uma empresa fundada em 2012 na Noruega e atualmente estamos  em mais de 160 países.

Aqui na Capreolus somos líderes em Machine Learning, BigData e Data Analytics. Trabalhamos com as Big Techs de todo o mundo, IBM, Google, Visa...

## Descrição da vaga

Aqui você irá trabalhar com a elite no desenvolvimento de software, utilizamos a metodologia Lean e MSF Agile.

Você será responsável por elaborar e contribuir no desenvolvimento do front-end de nossas aplicações diariamente colocando em prática seus conhecimentos em React e Angular.

## Local

Remoto 

## Requisitos

**Obrigatórios:**
- Conhecimento intermediário/avançado em React
- Conhecimento intermediário/avançado em Angular
- Experiência com produção enxuta e desenvolvimento ágil

**Desejáveis:**
- Conhecimento básico/intermediário Python
- Conhecimentos básico em C#
- Inglês intermediário/avançado (B1 a C2)

**Diferenciais:**
- Disponibilidade para trabalhar presencial na Europa
- Proficiência em alemão
- Proficiência em francês

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ 32/dia
- Auxílio creche

**Diferenciais:**
- Não trabalhamos com horário, entregou sua demanda do dia pode ir descansar
- Férias de 45 dias

## Contratação

PJ: R$4820,00 + Benefícios 

## Como se candidatar

Por favor responda este forms: https://forms.gle/vi9rkMSQBouAsVxB6

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: feedbacks@capreolus.cf

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior

**Comment by Gabriel-Malafaia** [comment]
Deixo o aviso aqui que essa vaga  é super suspeita, " estamos em mais de 160 países. " e em uma pesquisa rápida no google, a empresa não existe. O perfil de quem postou no linkedin é um perfil fantasma, sem nenhuma informação, apenas que ele é estudante de uma faculdade de ti iniciada em JULHO, salário muito acima do mercado pra júnior etc...

**Comment by AndreLefon** [comment]
> Deixo o aviso aqui que essa vaga  é super suspeita, " estamos em mais de 160 países. " e em uma pesquisa rápida no google, a empresa não existe. O perfil de quem postou no linkedin é um perfil fantasma, sem nenhuma informação, apenas que ele é estudante de uma faculdade de ti iniciada em JULHO, salário muito acima do mercado pra júnior etc... 

Opa, a vaga não é minha e nem trabalho na empresa, só decidi respostar aqui porque achei que ajudaria o pessoal.
