### ISSUE TITLE
[REMOTE] Front-end Developer na Totvs

### ISSUE THREAD

**Issue by Felipepirova** [frontendbr/vagas#7552]
## Nossa empresa

Que tal deixar a sua marca, com muita autonomia, em um ritmo acelerado, na maior empresa de tecnologia do Brasil?

Somos apaixonados(as) em apoiar e impulsionar o trabalho dos(as) TOTVERS, clientes e fornecedores. Aqui as áreas corporativas são parte indispensável para que mais de 40 mil empresas no Brasil e no mundo sejam transformadas pela tecnologia da TOTVS.

Se você quer aprender muito, em um ambiente dinâmico e com muita gente boa, vem pra TOTVS!

#ouseetransforme

#sejaTOTVER

## DESCRIÇÂO DA VAGA

Desenvolver soluções para Logística baseadas em microsserviços/cloud, utilizando técnicas como TDD e DDD e a metodologia Ágil.

Atuar em time para construir soluções modernas, com alto grau de qualidade, para fazer nossos clientes terem sucesso em suas jornadas.

REQUISITOS:
- Escolaridade mínima
- Indiferente

O QUE ESPERAMOS DE VOCÊ:
- Instrução: formação técnica, superior completo ou cursando em áreas ligadas a TI.

Qualificações técnicas desejadas:
- Raciocínio lógico apurado;
- Angular;
- HTML/CSS;
- Typescript/Javascript.
- Diferenciais:
- Ionic;
- Java;
- PO-UI (Biblioteca de componentes);
- Spring.

## Local

Exemplo: Remoto 

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Angular e Typescript

**Desejáveis:**
- Experiência com Ionic

## Contratação

CLT 

## Como se candidatar

Por favor envie um email para beatriz.bezerra@totvs.com.br com seu CV ou pelo link l1nq.com/zSdic

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dia após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by saviocunha2** [comment]
enviado !

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
