### ISSUE TITLE
[Rio de Janeiro] React native Developer na Monkey Lab

### ISSUE THREAD

**Issue by carlosmoliv** [frontendbr/vagas#7553]
## Descrição da vaga

Desenvolver um componente de um app em RN, sem consumo a API, apenas o front.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- CSS
- React Native

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para dev@monkeylab.com.br - enviar no assunto: Vaga React Native

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- Freela

**Comment by matheuslei** [comment]
Enviado ✅🚀
