### ISSUE TITLE
[REMOTE] Front-end Developer na Q.uinino Tecnologia

### ISSUE THREAD

**Issue by fquinino** [frontendbr/vagas#7555]
## Our Company
The company Q.uinino Tecnologia Ltda is a startup that is receiving investment to do a Research & Development project to develop a protection system for corporate environments against current cyber threats - data leakage and kidnapping.

## Description

We're creating a big data platform to integrate security, compliance, and analysis tools.

## Place

Homeoffice

### Hard skills:
- Language/Frameworks: JavaScript, TypeScript, React, Axios, Jest, Cypress, Styled Components, Redux, MobX
- Base: HTML/CSS/SASS/SCSS/CSS3
- Tools: NPM, Yarn, NVM
- Concepts: Unit Tests, Integration Tests, Dependency Injection, Semantic Versioning, Clean Architecture, DDD, TDD, Distributed Packages, Design System, Atomic Design, State Management
- Environment: Docker, CI/CD

**Desired:**
- Language/Frameworks:
	* 5+ years of hands-on with JS/TS + React
	* Very deep understanding of React Hooks and State Management (Redux/MobX)
- Tools: Figma, Miro, Confluence, Jira
- Environment: Azure DevOps

**Differential:**
- Knowledge of UI/UX
- Knowledge of how to draw concepts and mockups using Figma
- Knowledge about easy-understanding interfaces (creating friendly interfaces for users)
- A very good ability to produce screens and intuitive designs with a meeting of requirements gathering
- Knowing how to create a very good linter configuration from scratch

### Soft skills:
- You must know how to work with CodeReview.
- Working with a severe pipeline is not an issue for you.
- Your ability to speak in English is enough to communicate.
- Working with a small team needs to have very open communication, and you like that.

## Benefits

Competitive salary, up to 14,000 BRL.**

## Hiring

You must have a CNPJ.

## How to apply?

Fill form <https://bit.ly/vaga-devfrontend>.

## Feedback time

We answer you at least 2 weeks after the first contact.
If you didn't receive any answer, please send an e-mail to the same email as above.

## Labels
- Frontend
- JavaScript
- React
- Security

#### Allocation
- Homeoffice

#### Regimen
- PJ

#### Level
- Senior
- Specialist

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
