### ISSUE TITLE
[Remoto] Front-end Developer na O2 Filmes - PJ Modo de Pagamento

### ISSUE THREAD

**Issue by Roger-Siqueira** [frontendbr/vagas#7558]
## Nossa empresa

Nós somos um braço da O2 Filmes que desenvolve um projeto de um dos donos da produtora.
Mantemos um dia a dia de trabalho leve e comunicativo para podermos manter a qualidade do trabalho e a agilidade nas entregas.

## Descrição da vaga

A escopo da vaga é implementar o modo de pagamento de cobrança de assinatura para um aplicativo web feito com React JS no front-end e Rails no back-end.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Boa experiência com Javascript;
- Experiência básica em Rails.
- Git;
- Experiência com TDD;
- Valorizamos a realização de testes automatizados.
- Inglês para leitura e escrita.

**Desejáveis:**
- Experiência com React, Angular ou Vue;
- Rspec;
- Docker;
- Experiência com AWS.

## Contratação

PJ

## Como se candidatar

Por favor envie um email com seu CV anexado e pretensão salarial para roger@o2filmes.com.
Enviar no assunto: Vaga Dev - Modo de Pagamento

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by IagoMota** [comment]
Enviado ;D
