### ISSUE TITLE
[Remoto] Angular Front-end Developer Pleno na Revelo Network

### ISSUE THREAD

**Issue by anacarolbittencourt** [frontendbr/vagas#7561]
## Descrição do cliente

As soluções de negócios são pensadas com pragmatismo, pensamento progressivo e uso equitativo da tecnologia.
Nossa experiência em dados como gerenciamento de ciclos é admissível em vários domínios. E nos ajuda na transição do gerenciamento de fluxos de informações em larga escala para a formação de um estuário de micro pods de fluxos de dados de dispositivos IOT.

## Descrição da vaga
A vaga é para trabalhar no Front End, atuando com Angular 2 e Javascript na produção de layouts modernos e responsivos.

## Local
Remoto Internacional

## Requisitos
**Obrigatórios:**

* Inglês avançado (verbal e escrito)
* 3+ anos de experiência com Angular 2 e Javascript - precisa estar trabalhando atualmente com as skills

## Salário 
* Salário acima da média do mercado

## Contratação
- PJ

## Como se candidatar
Entre em contato por e-mail, contendo no assunto: "Angular Front-end Developer Revelo Network", e enviando as seguintes informações para [anacarolina.revelorecruiter@gmail.com](mailto:anacarolina.revelorecruiter@gmail.com):
* Currículo 
* Linkedin
* Nível de Inglês
* Github
* Portfolio (Se possuir)

## Disponibilidade
Vaga para ser preenchida com urgência, disponibilidade para início imediato.

#### Alocação
* Remoto

#### Regime
* PJ

#### Nível
* Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
