### ISSUE TITLE
[REMOTO] Sr Front-end Developer (ReactJS) na Invillia

### ISSUE THREAD

**Issue by gihhlazaro** [frontendbr/vagas#7563]
**INVILLIA**
Aproxime-se. A Invillia não apenas transformou a forma como as empresas mais revolucionárias do mundo criam e desenvolvem estratégias, negócios e produtos digitais.
Inovou também a maneira como pessoas apaixonadas por tecnologia, de qualquer lugar do planeta, podem interagir, evoluir, mais conectados do que nunca.
Para a Invillia, não importa onde você está. Se é um país grande. Ou uma cidade pequena. E sim a sua vontade. As suas ideias. O seu potencial.

O tamanho do seu talento_

**REQUISITOS**
> Experiência AVANÇADA em desenho de soluções para Front-end 
> Experiência AVANÇADA em linguagem Typescript
> Experiência AVANÇADA em CCS3
> Experiência AVANÇADA em HTML
> Experiência AVANÇADA em Styled-Component
> Experiência AVANÇADA em front-end React e Redux
> Experiência AVANÇADA em padrões de projeto e principios de design de código (SOLID, Clean Code, Design Pattens)
> Experiência AVANÇADA em consumo de com APIs RESTFul
> Experiência AVANÇADA em arquitetura de aplicações web
> Experiência INTERMEDIÁRIA em testes de unidade e cobertura de teste 
> Experiência INTERMEDIÁRIA em Git
> Experiência INTERMEDIÁRIA com container (Docker)
> Experiência INTERMEDIÁRIA em Desenvolvimento Seguro (HSTS, X-Frame-options, Xss-Protection, Content-Security-Policy, Chaves Criptograficas)
> Experiência BÁSICA em micro-frontends
> Experiência BÁSICA em Kubernetes
> Experiência BÁSICA em AWS

**Desejáveis:**
CONHECIMENTO em User Experience
CONHECIMENTO em Kubernetes
CONHECIMENTO em IAAC (Terraform)
CONHECIMENTO em CI/CD (Azure DevOps, Jenkins, Gitlab) 

**RESPONSABILIDADES**
Será responsável em prover soluções técnicas para novas features e dar o suporte necessário as features já existentes, afinal, nem tudo são flores.
Esperamos também que essa pessoa auxilie os outros membros do time em questões técnicas não esquecendo de fornecer a melhor solução para o negócio.
Algo que prezamos bastante é qualidade, isso inclui um código limpo e legível (clean code).
Também é desejável que o mesmo tenha um perfil intra-empreendedor, onde seus objetivos estejam alinhados com os objetivos da empresa, afinal, temos muito orgulho do que fazemos aqui!

**LOCAL**
Full remoto

**REGIME**
CLT + benefícios

**COMO SE CANDIDATAR**
Enviar o currículo atualizado para: [selecao@invillia.com](mailto:selecao@invillia.com)

**Comment by joaoromeira** [comment]
Candidatura enviada!

**Comment by andreferreiradaweb** [comment]
Candidatura enviada!

**Comment by Hugovarellaa** [comment]
Enviado !

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
