### ISSUE TITLE
[Remoto] Front-End Developer na Coodesh

### ISSUE THREAD

**Issue by blankapf** [frontendbr/vagas#7564]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-developer-160255034?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>IBC</strong> is looking for <strong><ins>Frontend Developer</ins></strong> to join its team!<br><br>We are looking for a Front-End Developer to work remotely on an international project for a European-based organization.</p>
<p></p>

## IBC: 
 <p>Na IBC desenvolvemos soluções simples e criativas para melhorar a gestão de Pessoas... em qualquer parte do Mundo!</p>
<p>A International Business Consulting é uma empresa constituída por um grupo de consultores experientes e com percursos consolidados, a nível nacional e internacional. Atualmente, possuímos escritórios em Lisboa e em Luanda.&nbsp;</p><a href='https://coodesh.com/empresas/international-business-consulting'>Veja mais no site</a>

 ## Habilidades: 
 - .NET 
- Asp.Net 
- HTML 
- CSS 
- DevOps 
- Agile 
- Sitecore
## Local: 
 100% Remoto
## Requisitos: 
 - Residence in Europe; 
- Experience in development projects; 
- Experience with .NET, ASP.NET, HTML and CSS; 
- Experience in frontend frameworks; 
- Experience in Agile methodologies; 
- Knowledge in DevOps tools; 
- Project experience or knowledge in Sitecore as well as Sitecore certification (plus); 
- Knowledge of the English language in spoken and written - B2; 
- Results oriented; 
- Communication, interpersonal relationship, teamwork, and collaboration; 
- Problem solving, analytical and critical thinking skills; 
- Organization, planning and quality orientation of projects.

## Benefícios: 
 - Competitve Salary; 
- Competitive Benefits; 
- Learning and development support; 
- Welcoming and friendly culture; 
- Remote Job.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Front-End Developer na IBC](https://coodesh.com/vagas/frontend-developer-160255034?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
