### ISSUE TITLE
[Remote] Desenvolvedor React @uCondo

### ISSUE THREAD

**Issue by NatachaNarimatsu** [frontendbr/vagas#7566]
### *uCondo*
Somos uma startup com um sonho grande: tornar todos os condomínios inteligentes! A uCondo existe porque a comunicação dos condomínios é precária e desorganizada, administradoras de condomínios possuem processos burocráticos, caros e demorados. Nosso propósito é proporcionar economia e comodidade para administradoras, pessoas síndicas e moradoras, nos tornando assim, o melhor App de condomínios das Américas!

### *Resumindo, sua missão no dia a dia é:*
- Definir junto ao time técnico os melhores caminhos para a construção da solução;
- Puxar todas as rotinas do SCRUM da sua Squad;
- Ser especialista do negócio e interagir com o Product Owner na definição dos requisitos trazendo sempre uma visão técnica de viabilidade e tempo estimado de desenvolvimento;
- Quando necessário, participar da criação ou correção das funcionalidades;
- Prestar suporte do produto aos demais times da empresa;
- Apoiar a definição, gestão do Roadmap e das sprints;
- Testar funcionalidades implementadas antes do lançamento (feature review);
- Aprovar junto com o Product Owner da squad a liberação dos itens desenvolvidos para o ambiente de produção;
- Gerenciar o time de Devs da sua squad, conduzindo agendas de 1:1s, feedbacks e apoiando no desenvolvimento da carreira dos programadores;
- Trabalhar com o time de Pessoas para realizar recrutamento, seleção, integração e treinamento dos novos Devs das squads;
- Validar documentações técnicas de itens desenvolvidos e orientar o time nessa construção.

### *Local*
Curitiba-PR;

### *Requisitos*
- Sólida experiência em desenvolvimento de aplicações .NET C# (nível sênior é obrigatório);
- Experiência em gestão de pessoas;
- Sólidos conhecimento em métodos ágeis (SCRUM);
- Sólida experiência em arquitetura de aplicações;
- Excelente capacidade de comunicação e escrita;
- Vivência em boas práticas de software como Clean Code, Clean Architecture, etc
- Transmitir as necessidades da equipe aos líderes da empresa;

*Diferencial:*
- Configuração de ambientes em nuvem AWS;
- Experiência em CloudFlare;
- Vivência no ramo condominial, e/ou empresas de tecnologia, ERPs, fintechs ou startups SaaS;
- Vivência em implantação de esteiras CI/CD com o AWS CodeBuild, ECR, ECS;
- Conhecimentos em Git, SQL Server, Redis, SQS e S3;
- Conhecimentos em outras tecnologias como Swift, Kotlin, C#, Java, etc.

### *Benefícios*
- Equipamentos fornecidos pela uCondo;
- Ajuda de custo home office: R$50,00/mês - (Cartão flash mastercard);
- Vale Refeição/Alimentação: R$480,00/mês - (Cartão flash mastercard);
- Plano de Saúde Bradesco (Sem mensalidade e com coparticipação);
- Plano Odontológico Bradesco (Sem mensalidade e com coparticipação);
- Seguro de Vida Bradesco (Sem mensalidade e com coparticipação);
- Treinamentos e plano de carreira;

### *Contratação*
*Tipo de vaga:* Tempo integral. Contratação CLT + benefícios.
*Budget de negociação:* Entre R$ 10.000,00 à R$ 13.000,00

### *Como se candidatar*
Por favor envie um e-mail para [talentos@ucondo.com.br](talentos@ucondo.com.br) com seu CV anexado - enviar no assunto: *Vaga - Desenvolvedor React*
Ou, se candidate através do link: https://www.ucondo.com.br/vagas

### *Tempo médio de feedbacks*
Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: [talentos@ucondo.com.br](mailto:talentos@ucondo.com.br)

*Alocação*
100% remoto.

*Regime*
CLT;
Jornada de trabalho: segunda à sexta das 09:00h às 18:00h.

*Nível*
Sênior.

**Comment by deMGoncalves** [comment]
🤔 Está vaga não é para um profissional Front-end, acredito que a descrição esteja errado....

**Comment by jeffersondrs** [comment]
Desenvolvedor React que pede senior em C#?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
