### ISSUE TITLE
[Hibrido / Caieiras, São Paulo, Brazil] Front-end Developer (Júnior) (Híbrido) na Coodesh

### ISSUE THREAD

**Issue by blankapf** [frontendbr/vagas#7568]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/fullstack-developer-netangular-hibrido-142048389?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>TRIFORSYS</strong> está em busca de <strong><ins>Front-end Developer (Júnior)</ins></strong> para integrar seu time!</p>
<p>Fábrica Softwares e soluções em TI de forma personalizada, atendendo a necessidade do nosso cliente com foco na automação de processos.</p>
<p><strong>Sobre a empresa</strong></p>
<p>Somos sua melhor experiência com softwares inteligentes e descomplicados que resolvem sua necessidade, apostamos na forma simples e prática de falar e tratar dos teus processos, considerando e respeitando as particularidades e características que fazem a diferença no seu negócio.</p>
<p>Cuidamos de seus objetivos e metas para melhores soluções de seu negócio. Construindo desde um software completo até ferramentas acessórias totalmente integradas ao seu sistema atual, tudo isso para que você tenha controle total sobre a gestão de sua empresa e de sua operação. Tratamos cada cliente como único e especial, considerando o tamanho da empresa, ramo de atividade no mercado, produto, serviço e principalmente sua história, que faz sua empresa ser o que realmente é.</p>
<p></p>
<p>Venha com a gente fazer seu negócio!</p>

## Triforsys: 
 <p>Somos sua melhor experiencia com softwares inteligentes e descomplicados que resolvem sua necessidade, apostamos na forma simples e prática de falar e tratar dos teus processos, considerando e respeitando as particularidades e características que fazem a diferença no seu negócio.</p>
<p>Cuidamos de seus objetivos e metas para melhores soluções de seu negócio. Construindo desde um software completo até ferramentas acessórias totalmente integradas ao seu sistema atual, tudo isso para que você tenha controle total sobre a gestão de sua empresa e de sua operação. Tratamos cada cliente como único e especial, considerando o tamanho da empresa, ramo de atividade no mercado, produto, serviço e principalmente sua história, que faz sua empresa ser o que realmente é.</p><a href='https://coodesh.com/empresas/triforsys-desenvolvimento-de-softwares-e-aplicativos'>Veja mais no site</a>

 ## Habilidades: 
 - Angular 
- HTML 
- CSS 
- React.js 
- Banco de dados relacionais (SQL)
## Local: 
 Caieiras, São Paulo, Brazil
## Requisitos: 
 - Residir em Caieiras ou proximidades (Formato híbrido); 
- Conhecimentos em Front-end (HTML, CSS, Javascript).
## Diferenciais: 
 - Conhecimentos em Banco de dados(SqlServer); 
- Conhecimentos em React/Angular/Vue.

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Front-end Developer (Júnior) (Híbrido) na Triforsys](https://coodesh.com/vagas/fullstack-developer-netangular-hibrido-142048389?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Regime
PJ
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
