### ISSUE TITLE
[REMOTO] Front-end Developer na Truppe!

### ISSUE THREAD

**Issue by Franciane-Andrade** [frontendbr/vagas#7569]
## Nossa empresa

Nós somos uma empresa de consultoria com foco em recrutamento e Seleção principalmente de Profissionais de tecnologia, e estamos nos reposicionando no mercado com transformação e aceleração digital junto com nossos clientes.

## Descrição da vaga

- Buscamos uma pessoa Desenvolvedora Frontend Pleno para atuar em uma grande empresa de tecnologia e e-commerce.
- Evoluir  plataforma de LiveCommerce; 
- Criar novas ferramentas e funcionalidades baseadas nas demandas dos clientes; 
- Criar e evoluir o sistema de onboarding e administrativo; 
- Garantir a qualidade do desenvolvimento, com padrões de código e processos.

## Local

100% Remoto

## Requisitos

**Obrigatórios:**

- Conhecimentos em Angular, HTML e CSS; 
- Ter experiência com Angular Material é um diferencial; 

**Diferenciais:**

- Experiência em desenvolvimento ou manutenção de plataformas de ecommerce; 
- Experiência em Marketing Digital. 
- Pessoa voltada a trabalho em equipe; 
- Vontade de crescer e evoluir. 

#### Conhecimentos

- Angular
- CSS
- HTML
- Angular Material
- E-commerce

## Contratação

CLT a combinar

## Como se candidatar

Por favor envie um e-mail para: franciane.andrade@truppe.team com seu CV anexado, junto com sua pretensão salarial no corpo do e-mail - enviar no assunto: Dev Frontend - Pleno

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

#### Alocação

- Remoto

#### Regime

- CLT

#### Nível

- Pleno

**Comment by gxmxntx** [comment]
Enviado!
Att Gabriel Gemente

**Comment by Franciane-Andrade** [comment]
c
