### ISSUE TITLE
[Remoto] Tech Lead (React) na Coodesh

### ISSUE THREAD

**Issue by blankapf** [frontendbr/vagas#7571]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/tech-lead-174106386?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>Onysis </strong>está em<strong> </strong>busca de <strong><ins>Tech Lead</ins></strong> para compor seu time!</p>
<p>Plataforma de gestão de Segurança no Transporte. Cuidando da segurança, o maior ativo da sua transportadora: o MOTORISTA.</p>
<p><span style="font-size: 16px;"><strong>Atividades e responsabilidades:</strong></span></p>
<ul>
<li>Orientar todo o time com as boas práticas técnicas, acompanhar e ser o braço técnico mais forte da área;</li>
<li>Desenvolvimento, teste, deploy e manutenção do software;</li>
<li>Pesquisa em aplicações de software para melhorar a oferta do produto;</li>
<li>Realizar 1-1 com os desenvolvedores;</li>
<li>Colaborar em questões relacionadas a escalabilidade e acesso de dados;</li>
<li>Gerenciar prioridades, prazos, entregas e indicadores do time e dos indivíduos;</li>
<li>Participar do processo de contratação de novos talentos.</li>
</ul>

## Onisys: 
 <p>Plataforma de gestão de Segurança no Transporte. Cuidando da segurança do maior ativo da sua transportadora: o MOTORISTA</p>

<p>A plataforma Onisys possui dois planos que conseguem atender a todos os tipos de empresas de transporte, ou empresas que tenham o transporte como parte de sua operação: Onisys Básico e Onisys Safe.</p><a href='https://coodesh.com/empresas/onisys'>Veja mais no site</a>

 ## Habilidades: 
 - React.js 
- Node.js 
- MySQL 
- SCRUM
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência em React; 
- Disponibilidade para 1 encontro mensal na sede em Belo Horizonte/MG; 
- Experiência com trabalho em equipe no formato remoto; 
- Experiência computação em nuvem (AWS, GCP ou outro ambiente relacionado).
## Diferenciais: 
 - Curso superior em TI.
## Benefícios: 
 - Horários Flexíveis; 
- Vale alimentação; 
- Plano de saúde integral; 
- Plano Odontológico.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Tech Lead (React) na Onisys](https://coodesh.com/vagas/tech-lead-174106386?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
