### ISSUE TITLE
[Remoto/Híbrido] Angular Front-end Developer DQR Tech

### ISSUE THREAD

**Issue by Vic-DQR** [frontendbr/vagas#7578]
#  Pessoa Desenvolvedora Front-end Angular Pl/Sr

### Sobre a DQR TECH | Qualidade do começo ao fim
Nascemos de uma parceria de mais de 10 anos entre seus sócios, somando a paixão por tecnologia à vontade de construir uma empresa diferente, investindo na proximidade com nossos parceiros e clientes. Somos uma consultoria especializada em Arquitetura de TI, Outsourcing de Profissionais e Hunting.

## DE ONDE VOCÊ VAI TRABALHAR?
Você pode atuar de onde você preferir e caso você seja de SP, pode ir no cliente 2x  na semana!

## O QUE NOS MOVE?
Tecnologia e vontade de evoluir! E é por isso que buscamos os melhores profissionais para atender ao nosso cliente da área financeira.

## SUAS ATIVIDADES SERÃO?
Desenvolver projetos na área de crédito e risco.

# O QUE ESPERAMOS QUE VOCÊ TENHA?
- Angular 2+
- CSS; HTML; GIT

# O QUE SERIA LEGAL SE VOCÊ TIVESSE?
- Ferramentas de Design; OOP; Node ou C#; SQL; AWS;
- Arquitetura de Software; Metodologia Ágil.

## SOFT-KILLS ESPERADAS?
- Comprometimento; Foco no cliente;
- Perfil proativo, colaborativo, comunicativo e autonomia.

# O QUE OFERECEMOS PARA VOCÊ?
- Contrato CLT, com propostas salariais de de 8 a 10 mil. 
- Vale Refeição/Alimentação (Cartão CAJU);
- Assistência Médica e Odontológica sem coparticipação para o colaborador;
- Seguro de Vida;
- Auxílio creche;
- Aqui a sua indicação vale premiação;
- No mês do seu aniversário tem mimos;
- Oferecemos notebook para desempenhar suas atividades;

# PROCESSO SELETIVO
- O processo é feito em duas etapas, a entrevista técnica e comportamental com o RH e posteriormente uma entrevista com o cliente, onde será aplicado um teste técnico focado em Angular. Após estas etapas, entramos em contato para lhe estender uma proposta! 

# [Candidatar-se] (https://dqrtech.com.br/formulario-oportunidades/) ou entrar em contato pelos seguintes canais: (11) 95393-2021, victoria.krutli@dqrtech.com.br ou vagas@dqrtech.com.br.

**Comment by gsabreudev** [comment]
vem ser dqr tech!!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
