### ISSUE TITLE
[São Paulo] Front-end Developer/Pleno na nexmuv

### ISSUE THREAD

**Issue by HelenNexmuv** [frontendbr/vagas#7579]
##Nexmuv
Somos uma empresa de tecnologia que aplica inovação em tudo aquilo que entrega. Existimos para ajudar nossos clientes a se adaptarem a um mundo em constante transformação.

## Desenvolvedor Front end - Pleno 

Projeto de inovação e desenvolvimento de novas frentes. 

## Paulista - SP 
Modelo hibrido - 1 Vez por semana ou 1 vez a cada 15 dias 

## Requisitos
Requisitos: Foco em Front-end Angular 6+, TypeScript, JavaScript, HTML5 e CSS3, Figma Jira, confluence, Scrum, GitHub Desejável: conhecimento em Java, DevOps, Docker.

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para helen.matos@nexmuv.com.br com seu CV anexado - enviar no assunto: Vaga Front end 

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
