### ISSUE TITLE
[Remoto/Rio de Janeiro] Front-end Developer Pleno - inChurch

### ISSUE THREAD

**Issue by 1nChurch** [frontendbr/vagas#7581]
## Stealth Mode

Somos uma startup atualmente em Stealth-Mode que já possui um MVP funcional. Já validamos nosso produto e assinamos nossos primeiros clientes pagantes. Criamos uma plataforma digital que utiliza tecnologia e trabalho em equipe das pessoas mais incríveis que encontramos, para facilitar a vida do Infoprodutor moderno, gerando mais engajamento e consequentemente aumentando as suas vendas. 
O background da equipe tem uma vasta experiência no crescimento de startups até unicórnio e com boas relações no mercado. 

## Descrição da vaga

Estamos em busca de um engenheiro de **front-end** com conhecimentos em **AngularJS** para se juntar ao nosso time de startup em crescimento acelerada! Como membro valioso da equipe, você terá a oportunidade única de trabalhar em projetos inovadores e desafiadores enquanto colabora com uma equipe talentosa e apaixonada pelo que faz.
Como engenheiro de front-end, você será responsável por criar interfaces de usuário incríveis para nossos aplicativos da web e principalmente móveis. Isso inclui a criação de protótipos de ponta, a implementação de designs deslumbrantes e a manutenção de código de alta qualidade. Além disso, você trabalhará em estreita colaboração com os engenheiros de back-end para garantir a integração perfeita entre o front-end e o back-end.

## RJ 

Vaga Remoto ou Híbrido

## Requisitos

Graduação em Ciência da Computação, Sistemas de Informação ou áreas relacionadas (desejável)
Conhecimento sólido em Angular e frameworks de Front 
Conhecimento inglês é um diferencial
Conhecimento com a biblioteca angulo e testes

Experiência mínima de 2 anos na área 
Experiência em HTML, CSS e Java, Type Script (intermediário) 
Experiência com ângulo (desejável) ou algum framework de frontend  
Experiência em versionamento de projetos com Git 
Experiência com Bootstrap e pré-processador de CSS (preferencialmente SASS 

## Benefícios

Freedom Living at Work (FLOW) (Opções de trabalho - escolhido junto à liderança)
Full remote - 1x a 2x por ano presencialmente
Flex - 1x a 2x por semana presencialmente
Office based - 3x ou mais por semana presencialmente
Possibilidade de stock options/equity plan
Birthday-off
Férias flexíveis;
Amplas oportunidades de avanço na carreira

## Contratação

PJ

## Como se candidatar

Por favor envie um email para rh@inchurch.com.br com o seu CV anexado - enviar no assunto: Vaga Frontend Pl.

### Nível

- Pleno

### Regime

- PJ

### Alocação

- Remoto
- Híbrido

**Comment by otaviordc** [comment]
Confere 
esse trecho da anuncio de vaga: "Por favor envie um email para [rh@inchurch.com.br](mailto:rh@inchurch.com.br) com o seu CV anexado - enviar no assunto: **Vaga Backend Sr.**", o assunto seria esse mesmo ? pois no anuncio da vaga diz ser front end.

**Comment by 1nChurch** [comment]
> Backend



> Confere esse trecho da anuncio de vaga: "Por favor envie um email para [rh@inchurch.com.br](mailto:rh@inchurch.com.br) com o seu CV anexado - enviar no assunto: **Vaga Backend Sr.**", o assunto seria esse mesmo ? pois no anuncio da vaga diz ser front end.

Oi Otávio! Obrigada pela sua consideração. Alterei no descritivo da vaga. Obrigada!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
