### ISSUE TITLE
[Desenvolvedor Frontend Xamarin] - Santos - SP (Bairro Marapé)  na HunterHunter

### ISSUE THREAD

**Issue by ErickaMB** [frontendbr/vagas#7584]
[Desenvolvedor Frontend Xamarin] - Santos - SP (Bairro Marapé) - Os primeiros 6 meses aproximadamente serão presenciais após poderá ficar remoto. Salário pode ser CLT ou PJ (CLT tem VT/VR e Plano de Saúde).

Condições Gerais:

Mais de 3 anos de experiência

Contrato a termo certo por 12 meses

Possibilidades de implementação na Argentina, Brasil ou Colômbia

Preferencialmente conhecimento de inglês e/ou português NÃO exclusivo

Local de trabalho Santos, Brasil

A empresa oferece alojamento e outros benefícios.

Desenvolvedor Frontend Xamarin
Desenho de telas em XAML;
Modelo de dados do conversor de comportamento do renderizador personalizado e DataTemplateSelector;
Tipos de vinculação (One Way, Two Way, OneTime, One Way To Source);
Controles (Data Trigger, Multi Trigger) MVVM; Notificação push .NET.

Conhecimentos necessários:
Programação: C#
Front End: WPF ou Xamarin.

Conhecimentos desejáveis:
Núcleo .NET;
DDD, SOLID, injeção de dependência;
TDD, BDD,
scrum, kanban.

Empresa dedicada há mais de 30 anos a importação de produtos oleohidráulicos e agregando valor criando projetos de acordo a necessidade do cliente.
Fábrica maquinarias agrícolas, soluções eletrônicas entre outras atividades.
Presente em Argentina, Brasil, Panamá, Colombia, Uruguay e Malasia.

Se tem interesse e com requisitos da oportunidade entre em contato pelo Linkedin informando qual é a oportunidade. [[https://www.linkedin.com/in/erickamarquesb/]](https://www.linkedin.com/in/erickamarquesb/%5D)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
