### ISSUE TITLE
[Remote] Vue.JS Developer na UpStack

### ISSUE THREAD

**Issue by nagavi90** [frontendbr/vagas#7588]
> Vaga Remota durante a pandemia

## Nossa empresa

Upstack is a friendly team of the world’s most talented freelance developers working remotely for some of the coolest start-ups. It’s fun and challenging to join the top 1% of the world’s developers.
We have a strong focus on quality clients and developers and try to work on software that we love! Upstack is officially based in New York City, and we have offices in NYC and LA. We also have development hubs opening up all around the place, with our first in Brasov, Romania.
Our developers work from home, co-working spaces, and sometimes even on the beach!

## Descrição da vaga

**About the client:** The company provides a healthcare consultancy and software development services firm that creates modern software applications for healthcare practitioners worldwide.

**The work**

- Work with a small team of top-tier developers.
- Participate in scrums consisting of cross-functional teams, both software, and hardware.
- Ensure that features are being delivered efficiently and on time.
- In addition to code contribution, you will also participate in architectural review and design.

## Local

Remoto

## Requisitos

**Obrigatórios:**

- **5+ years of experience** in software development.
- **3+ years** of proven work experience in **Vue.JS**.
- Strong and confident communicator in **English**.
- Strong problem solver.
- Comfortable with collaboration and open communication across
- distributed teams.

**Desejáveis:**

- Proven track record of shipping software and successfully released apps (please include names and links on your resume).
- Proven work experience inside of a distributed team in a remote environment.
- Part of at least one project developed for a small/start-up company, preferably from the USA.
- Strong attention to detail on every line of code, every unit test, and every commit message.
- Comfortable with rapid development cycles and tight schedules.

## Benefícios

- **USD compensation: 40-50 USD/hr.**
- Flexible working hours.
- Remote first - you can work from anywhere you choose.
- Ability to choose the project and the team!
- Work set-up: laptop or device as needed based on the project's
- requirements.
- Support for personal and professional growth.
- Bonus structure for special events in your life (marriage, having a baby).

## Contratação

Freelance contractor

## Como se candidatar

Please, send your resume to nahuel@upstackhq.com

#### Alocação
- Remoto

#### Regime
- Freela

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
