### ISSUE TITLE
[Remoto] Front-End Developer Junior na Ingage Digital

### ISSUE THREAD

**Issue by kennvpaula** [frontendbr/vagas#7590]
**QUEM SOMOS?**

A Ingage Digital é uma agência de Marketing Digital e inovação em vendas, com escritório situado em Belo Horizonte. Planejamos e operamos táticas e estratégias digitais, utilizando de tecnologia e dados para tomadas de decisões. Resolvemos desafios de empresas em crescimento, que buscam competir e vencer com o Marketing Digital.
Somos uma agência de marketing digital com foco em performance, portanto, prezamos por códigos limpos e plataformas ágeis.

Estamos procurando por um profissional para compor nosso time de desenvolvimento.

**DESCRIÇÃO DA VAGA**

- Desenvolver landing pages integradas com CRM (majoritariamente RD station);

- Implementar e auditar tags em sites existentes, construídos em diferentes plataformas e linguagens;

- Realizar o desenvolvimento dos ativos (sites, blogs e landing pages) utilizando as melhores práticas de Page Speed e Web Core Vitals;

- Aprimorar velocidade de carregamento de ativos (sites, blogs e landing pages) através de ferramentas e plugins;

- Conhecimentos sobre SEO on page e suas aplicações;

- Noção para criação de ambientes e infra em servidores cloud (Digital Ocean, AWS).

- O dia-a-dia também envolve a auditoria de tags, ajustes diversos em ativos de nossos clientes e ativos próprios da INGAGE.

**LOCAL**

100% Remoto.

**REQUISITOS**

- Conhecimentos WordPress: criação de temas, plugins e códigos customizados que complementam temas existentes;
- Conhecimentos em HTML, CSS e Javascript.

**BENEFÍCIOS**

- Cartão Flexível

**CONTRATAÇÃO**

- PJ com valor à combinar.

**COMO SE CANDIDATAR**

Por favor envie um e-mail para kennedy.psic@gmail.com com seu currículo anexado - enviar no assunto: Vaga Front-End Junior

**Comment by tascintra** [comment]
Enviado!

**Comment by helderdsa** [comment]
Enviado!

**Comment by MarcioTanan** [comment]
Enviado!

**Comment by luizguilherme4** [comment]
Enviado ✅

**Comment by MarcioBADias** [comment]
Enviado!

**Comment by edulongodevgeo** [comment]
Enviado! 🚀

**Comment by BarbaraTito** [comment]
Enviado.

**Comment by jorgekimura2001** [comment]
Enviado, aguardo retorno :).

**Comment by SammuDev** [comment]
done

**Comment by LucasHbarros** [comment]
Enviado!

**Comment by antoniornneto** [comment]
Enviado!

**Comment by JoaoCairesDev** [comment]
Enviado!

**Comment by GabrielM-afk** [comment]
Enviado!

**Comment by Matheus7Ribeiro** [comment]
Enviado!!!

**Comment by rafaelsilva81** [comment]
Enviado!

**Comment by rafaelsiqeira** [comment]
Enviado!
