### ISSUE TITLE
[REMOTO] Front-End Mobile Developer em NTH WORK

### ISSUE THREAD

**Issue by fduchewski** [frontendbr/vagas#7592]
Nth combina design, tecnologia de ponta e excelência de produto para levá-lo ao maior nível. 

Somos um grupo internacional de apaixonados por inovação, criatividade e tecnologia. Da idealização ao desenvolvimento e lançamento de produtos exclusivos, passamos pelos processos de consultoria, descobrimento e desenvolvimento.  

Como estúdio de desenvolvimento, reunimos os profissionais e as ideias certas para solucionar problemas com tecnologia de ponta.
 Estamos ativos em frentes da web3+, descentralização, blockchain​ ecriptoativos. 

Construímos o futuro aqui.
The solutions of tomorrow, today.

Confira também nosso blog: [nth.work/blog](http://nth.work/blog) 

 —— - 

A Nth hoje busca profissionais de perfis diversos para seu banco de atuações, todos em caráter on-demand - com um processo hands on de onboarding, integramos novos recursos para atender demandas em escala, planejadas por prioridade, complexidade e perfil. 

 —— -  

 Buscamos agora: 

 **FrontEnd Mobile Developer Sênior** 

- React Native
- React JS
- Native Base
- Css
- Prototipagem com Figma (Desajável)
- Firebase tools (Firestore, Functions, Auth, e etc)
- Bom entendimento de Web
- Experiência com publicações Apple Store e Google Play

Disponibilidade imediata para fluxo de até 80h/mês por 3 meses

Se interessou?  

Envia pra gente por [e-mail](http://info@nth.work/) ou pelo [Telegram](https://telegram.me/nthwork) seu GIT, LinkedIn e/ou CV para batermos um papo.

**Comment by abraaoreis** [comment]
Queria saber qual o email para enviar o currículo, o link vai direto pro site

**Comment by fduchewski** [comment]
@abraaoreis boa tarde! 

Pode encaminhar para o info@nth.work.

Obrigada!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
