### ISSUE TITLE
[Florianópolis] Pessoa Engenheira de Software na Franq Openbank 🚀💙

### ISSUE THREAD

**Issue by samarafurlanetto** [frontendbr/vagas#7594]
## Nossa empresa

Somos um time de especialistas focados na **inovação de produtos e serviços financeiros**. Oferecemos uma solução pioneira: **uma one-stop-shop para profissionais bancários independentes e escritórios de investimentos**.

Juntos, transformamos o mercado financeiro por meio da tecnologia. Temos como propósito, com muita franqueza, garantir a autonomia, a liberdade e a transparência para os consumidores.

Por isso, buscamos maneiras transformadoras de melhorar a forma como nossos clientes se relacionam com o mercado.

**Somos a Franq - Finance is Personal 💵**

## Descrição da vaga

- Desenvolvimento de códigos elegantes, estáveis, confiáveis e fáceis de manter;
- Desenvolvimento de soluções sempre pensando em eficiência, escalabilidade e estabilidade;
- Prática de code reviews pois queremos sempre garantir a máxima qualidade e segurança das nossas entregas.

## Local

Trabalho híbrido - Florianópolis (SC) 

## Requisitos

**Obrigatórios:**

- Conhecimento em programação Javascript;
- Conhecimento de Clean Code e Design Patterns;
- Ter boa comunicação, saber trabalhar com times multidisciplinares em um ambiente dinâmico, com entregas rápidas e metodologias ágeis.

**Diferenciais:**

- Conhecimento em VueJS/React;
- Conhecimento em Vuetify;
- Conhecimento em AWS;
- Conhecimento em testes automatizados;
- Conhecimento com Git.

## Benefícios

- Contrato CLT;
- Ambiente leve e descontraído;
- Cartão de benefícios flexíveis Caju de R$ 816,89; 
- Assistência médica e odontológica, sem coparticipação, totalmente subsidiada pela empresa.
- Seguro de vida;
- No dress code;
- Day off no mês de aniversário;
- Mesa de frutas para os Franqers em modelo presencial.

## Contratação

CLT

## Como se candidatar

Para se candidatar, acesse o link: https://franq.gupy.io/jobs/3714952

#### Regime

- CLT

#### Nível

- Pleno
- Sênior
- Especialista

**Comment by djalmajr** [comment]
A tag "Freela" foi adicionada, mas o vínculo é CLT... Foi engano ou tem algum outro link onde o freela se aplique?

**Comment by samarafurlanetto** [comment]
> 

Olá! A vaga seria CLT mesmo :)

**Comment by joaov1ct0r** [comment]
Enviado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
