### ISSUE TITLE
[Remoto] Globo - Desenvolvedor iOS Sênior

### ISSUE THREAD

**Issue by lauramarquesitrecruiter** [frontendbr/vagas#7595]
**Empresa**
O Grupo Globo é o maior conglomerado de mídia e comunicação de todo o país. Formado por diversas empresas das áreas de Jornalismo, Esporte e Entretenimento. Eles têm aproximadamente 15000 colaboradores e o grupo atinge 99,6% da população brasileira e tem uma atuação ampla em todas as plataformas que se encontra.

**Posição**
Sênior

**Tipo de contratação**
Remoto, CLT.

**Requisitos**
_Obrigatórios_
Amplo conhecimento em iOS e Swift;
APis de integração e componentes;
Arquitetura MVVM;
Ter conhecimento de práticas de XP (TDD, pair programming, refactoring, continuous integration, etc).

_Diferenciais_
Conhecimento em KMM.

**Benefícios**
PLR de até 1.5 salários;
Assistência Médica e Odontológica;
Seguro de vida;
VA e VR 35/dia;
Prev. Privada;
2 anos de globoplay + telecine grátis.

**Como aplicar**
Encaminhar e-mail para [julia.saraiva@landtech.net.br](mailto:julia.saraiva@landtech.net.br) com seu CV anexado e assunto "Desenvolvedor iOS" .

**Contato**
Whatsapp (+55 11 94283-0912).

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
