### ISSUE TITLE
[PORTUGAL] Front-end Developer na INTEGER Consulting

### ISSUE THREAD

**Issue by FilipeGM** [frontendbr/vagas#7598]
[PORTUGAL] Front-End Developer na INTEGER Consulting!

## Nossa empresa

O meu nome é Filipe Marques e faço parte da INTEGER! A INTEGER é uma empresa de consultoria com foco em consultoria de IT (Outsourcing) e desenvolvimento de Software e Produto (internamente).
Somos conhecidos no mercado, por darmos um ótimo acompanhamento aos nossos consultores, pela experiência que temos e pela ajuda que damos a profissionais de outros países que querem vir para Portugal!

## Descrição da vaga

As principais vagas Frontend, que temos em aberto atualmente são:
👉 Senior Angular Developer/Architect;
👉 React.JS Developer;

Descobre estas e mais oportunidades e os seus requisitos, no nosso site: https://lnkd.in/gE4c_bB

## Local

Inicialmente remoto, mas o objetivo é que o candidato tenha real interesse de vir para [PORTUGAL] 

## Benefícios

- Plano de saúde (para o candidato e família);
- Alojamento nas primeiras duas semanas em PT;
- Acesso gratuito à Udemy;
- Acesso gratuito a plataformas para o desenvolvimento da língua inglesa;
- Acesso à nossa rede de parcerias - Descontos em serviços, academia, cosmética, restauração, etc...;

## Como se candidatar

Envia o teu CV para filipe.marques@integer.pt !
OU entra em contacto comigo, por aqui, através do mail, Linkedin, ou Whatsapp (+351 910 385 109), com o teu currículo em anexo, de preferência em inglês.

## Tempo médio de feedbacks 
Costumamos enviar feedbacks (negativos) em até 7/15 dias após cada processo.
E-mail para contato em caso de não haver resposta: ana.verissmo@integer.pt

#### Alocação
Inicio Remoto, mas terá de existir real interesse em vir para Portugal 💯

**Comment by FueledByRage** [comment]
Enviado

**Comment by PhilipeF** [comment]
Olá currículo enviado, se preferir pode acessar o meu [site portifólio](https://philipef-dev.vercel.app/) que la também é possível fazer download do currículo e conferir um pouco da minha tragetória até aqui.

**Comment by guibranco** [comment]
@FilipeGM publique aqui também: https://github.com/frontend-pt/vagas

**Comment by joaoromeira** [comment]
Enviei, mas não obtive nenhum retorno ainda
