### ISSUE TITLE
[Recife] Desenvolvedor Front-End

### ISSUE THREAD

**Issue by teoria** [frontendbr/vagas#76]
## Descrição da vaga

VAGA Front em RECIFE !
‪#‎html5‬ ‪#‎css‬ ‪#‎JS‬ ‪#‎angular‬
## Local

Escritório, Recife - Pernambuco
## Benefícios
- Auxílio alimentação
- Auxílio saúde
## Requisitos

**Obrigatórios:**
- html5 e css
- 1 ano de Angular

**Desejáveis:**
- Angular 2
- NodeJS

**Diferenciais:**
- projetos opensource
## Contratação

CLT
## Nossa empresa

A Mídias Educativas é uma empresa especializada no desenvolvimento de soluções educacionais em formato digital. Computadores, internet, CD ROM, DVD, televisão, dispositivos móveis (smartphones e tablets) e simuladores são usados como ferramentas de aprendizado no processo de formação presencial e a distância.

Através de projetos de design instrucional, a empresa usa fundamentos em teorias da aprendizagem humana para criar recursos didáticos por meio de tecnologia. Toda a metodologia é construída com práticas de design da interação (usabilidade), engenharia de software e princípios de blended learning (mistura de soluções tecnológicas com métodos tradicionais).

A empresa utiliza ferramentas como: Flash, Flex, HTML5, PHP, .NET, Java e Unity3D no desenvolvimento de projetos, com interfaces adequadas para cada usuário. Todos os recursos multimídia e motivacionais disponíveis no mercado são usados nos produtos, como: animações 2D e 3D, imagens, fotos, vídeos, jogos on-line, jogos multiusuários, simuladores, avatares, tutoriais. Com isso, os produtos da Mídias conseguem ser mais eficazes que os meios tradicionais, além permitir a independência da plataforma podendo ser utilizado em diversos sistemas operacionais como Windows, MAC OS e Linux, além de dispositivos móveis Android e IOS.

Equipe é composta com profissionais certificados em ferramentas e processos, e conta com a experiência em diversas tecnologias educacionais há mais de 10 anos de atuação nesta área.
## Como se candidatar

Por favor envie um email para rodrigo@midiaseducativas.com.br com seu CV anexado - enviar no assunto: Vaga FRONT

**Comment by LFeh** [comment]
Coloquei Pleno e Senior, está certo?
