### ISSUE TITLE
[Rio de Janeiro] Front-End Developer Jr na Webedia

### ISSUE THREAD

**Issue by diegoos** [frontendbr/vagas#760]
## Descrição da vaga

Estamos em busca de pessoas com interesse em assumir grandes projetos e grandes responsabilidades, capazes de solucionar problemas e vencer desafios, sempre prezando pela escalabilidade, performance e qualidade do sistema. Valorizamos pessoas que tem paixão pelo que fazem, com perfil dinâmico, capazes de se adaptarem a diversas situações de projeto, dedicadas e que estejam em constante processo de evolução e aprendizado.

A vaga se destina a profissionais de nível júnior, com perfil proativo, e esperamos que o candidato seja capaz de lidar com questões além do desenvolvimento.

## Local

Escritório em Botafogo, Rio de Janeiro - RJ

## Benefícios

- Café da manhã e da tarde
- Vale refeição
- Vale transporte
- Plano de saúde
- Plano odontológico

## Responsabilidades

- Desenvolver o frontend de projetos comerciais como landing pages, hotsites, native stories para diversas marcas da empresa;
- Entender as necessidades comerciais, as soluções propostas pelos designers e propor soluções técnicas para o trabalho final;
- Escrever códigos limpos, documentar e comentar;

## Requisitos

**Obrigatórios:**
- Experiência com Front-end e responsividade (HTML5, CSS e JavaScript);
- Experiência com sistemas de versionamento, preferencialmente Git;
- Experiência com pré-processadores de CSS;
- Inglês intermediário (leitura e escrita);

**Diferenciais:**
- Conhecimento em desenvolvimento com biblioteca React.js;
- Conhecimento em PHP/Wordpress;
- Conhecimento Linux / UNIX;
- Conhecimento com ferramenta Google Tag Manager e Google Analytics;
- Conhecimento em APIs sociais (Facebook, Google, Twitter, etc);

## Contratação

CLT

## Nossa empresa

A Webedia é um grupo de mídia digital de origem francesa presente em mais de dez países, com verticais que totalizam 177 milhões de usuários únicos por mês, dos quais 47,3 milhões estão no Brasil, a maior audiência do grupo. Na América Latina, ocupa a 8ª colocação entre as maiores audiências digitais na área de entretenimento, segundo o ComScore.

O sucesso se deve ao controle de sites líderes em segmentos estratégicos: TudoGostoso (foods), AdoroCinema (entretenimento), IGN (games), PurePeople e Purebreak (glamour), Minha Vida (saúde e bem-estar) e Hypeness (Inovação e Criatividade). Por meio da divisão de Brand Publishing, a Webedia oferece ainda conhecimento em audiência para marcas, atuando com produtos de big data que alcançam as melhores performances.

## Como se candidatar

Por favor envie um email para diego.oliveira@webedia-group.com com seu CV anexado - enviar no assunto: Vaga Front-end Jr

**Comment by mtAlves** [comment]
Existe a possibilidade de Estágio ?

**Comment by diegoos** [comment]
@mtAlves no momento não temos vaga para estágio.

**Comment by webmalta** [comment]
Possibilidade de remoto?

**Comment by diegoos** [comment]
@webmalta não tem. :\

**Comment by ldrbraga** [comment]
Diego, enviei meu CV. Já preencheram a vaga?

**Comment by diegoos** [comment]
@ldrbraga blz? Ainda não preenchemos. 
Os currículos que eu recebi estão com o pessoal responsável pela seleção, o seu vai pra eles também. :)

**Comment by ldrbraga** [comment]
Obrigado, Diego!

**Comment by RenatoAreas** [comment]
@ldrbraga Tudo bem. Não tenho tanta experiencia na área de desenvolvimento, porém tenho superior em analise e desenvolvimento de sistemas e cursos de extensão.

**Comment by andrevvalle** [comment]
Que incoerente essa vaga, front end Jr com experiencia de 1 a 3 anos.. WFT? ensino superior completo? WTF?

**Comment by thiagoverly** [comment]
@andrevvalle , primeiro você precisa ler e entender melhor o anúncio, e respeito é sempre bem-vindo! Ensino superior completo OU cursando. Tempo de experiência vale como estágio também, então de 1 a 3 anos é super coerente para a vaga de Jr. Discorda? Gostaria de ouvir sua opinião com embasamento e sem xingamentos ;)

**Comment by ReactGirl** [comment]
Ou seja, querem alguem que tem experiencia de 3 anos (Mid-level) pra pagar um salario de Junior.

**Comment by thiagoverly** [comment]
Interessante a discussão @ReactGirl , obrigado por compartilhar o link

Pergunta: 

Se a pessoa tem 1 ano de experiência, e (como exemplo do seu texto): "_Have become competent and independent with tasks_", ela é jr ou pleno?

Ou se ela possui 3 anos de experiência e: "_Generally need a lot of hand-holding_", ela é jr ou pleno?

Gostaria de entender melhor seus critérios de avaliação :)

PS: o tempo de experiência anunciado é para não limitar tanto o tempo de experiência dos candidatos, e isso não quer dizer que seja incoerente com a vaga.

**Comment by diegoos** [comment]
@RenatoAreas nada te impede de tentar. :)

**Comment by ReactGirl** [comment]
@thiagoverly Sobre a pergunta:

> Se a pessoa tem 1 ano de experiência, e (como exemplo do seu texto): "Have become competent and independent with tasks", ela é jr ou pleno?

Se uma pessoa com experiência de apenas 1 ano, e conseguiu atingir o nível da mesma forma de alguém que está a 3 anos, por qualquer que seja o motivo (estudar bastante, side projects, etc) e estiver consciente de suas habilidades, com certeza não aceitaria trabalhar recebendo o mesmo salário de um Junior. (Da mesma forma como alguém que ja tem 3 anos de experiencia e o mesmo nível citado na referencia.)

**Comment by andrevvalle** [comment]
@thiagoverly blz, boa sorte!! e desculpe se meu WTF.. ofendeu
