### ISSUE TITLE
[Remoto] Frontend Developer (Vaga Afirmativa Para Mulheres) na Coodesh

### ISSUE THREAD

**Issue by blankapf** [frontendbr/vagas#7600]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-front-end-vaga-afirmativa-para-mulheres-152004406?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>Qred Brasil</strong> está em busca de <strong><ins>Frontend Developer (Vaga Afirmativa Para Mulheres)</ins></strong> para compor seu time!</p>
<p>Sabe quando você conhece uma nova pessoa ou começa um novo emprego que te dá aquela sensação boa? É assim que gostaríamos que você se sentisse ao ingressar na <strong>Qred</strong>.</p>
<p>A Qred nasceu na Suécia e é uma fintech multinacional especializada em soluções de financiamento digital para pequenas e médias empresas. Somos apaixonados por ajudar empresas a prosperar e crescer, fornecendo-lhes soluções financeiras. No momento, estamos em uma fase emocionante de nossa jornada de expansão internacional que se concentra no crescimento por meio do uso de tecnologia e desenvolvimento de produtos financeiros inteligentes.</p>
<p>Somos suspeitos, mas podemos pensar em um milhão de razões pelas quais a Qred é o melhor lugar para se trabalhar, aqui estão apenas algumas delas:</p>
<p>🌍Somos uma fintech multinacional especializada em soluções de financiamento digital para pequenas e médias empresas, com operações na Suécia, Dinamarca, Finlândia, Holanda, Noruega, Bélgica e Brasil.</p>
<p>💚Aqui tem espaço para todo mundo! Somos uma equipe diversa e aprendemos muito, uns com os outros. Não importa quem você seja, acreditamos que fará coisas incríveis por aqui.</p>
<p>🚀 Temos muito orgulho de estar no top 10 da lista das 1.000 empresas que mais crescem na Europa, de acordo com o Financial Times.</p>
<p>👾Nosso escritório está localizado em São Paulo-SP (ao lado do metrô Pinheiros).</p>
<p>O objetivo da <strong>Qred </strong>é ajudar as pequenas empresas a crescerem rapidamente – queremos ser a melhor alternativa de empréstimo empresarial online. Rápido, prático e seguro.</p>
<p>Buscamos uma pessoa desenvolvedora de software, com a cabeça aberta para o aprendizado constante de novas tecnologias.</p>
<p><strong>Como vai ser o seu dia a dia:</strong></p>
<p>Nossa rotina é baseada no conceito ágil para desenvolver as necessidades do nosso produto, escrevendo código com testes unitários, seguindo as boas práticas em desenvolvimento de software utilizando princípios de clean code, clean architecture e SOLID.</p>

## Qred Brasil: 
 <p>A Qred é uma fintech que oferece crédito com a missão de contribuir pelo crescimento e desenvolvimento das pequenas e médias empresas do país.</p>
<p>Nascemos da união entre a empresa sueca Qred e a sueco brasileiro Webrock Ventures, resultando em um modelo de negócio inovador e flexível, voltado para os diferentes negócios do Brasil.</p><a href='https://coodesh.com/empresas/qred-brasil'>Veja mais no site</a>

 ## Habilidades: 
 - Angular 
- HTML 
- CSS 
- Typescript 
- Javascript 
- SCRUM 
- API 
- Figma 
- Spring Framework 
- Spring Boot
## Local: 
 100% Remoto
## Requisitos: 
 - Graduação/Tecnologo na área de exatas (computação, sistemas, engenharia etc); 
- Raciocínio lógico e de lógica de programação; 
- Habilidade em arquitetar aplicações Angular (template, rotas, segurança, boas práticas); 
- Habilidade comprovada para stack de desenvolvimento em Angular 12+, HTML, SCSS, CSS, typescript e javascript; 
- Experiência em desenvolvimento com testes unitários; 
- Ser um resolvedor de problemas; 
- Ser autodidata e buscar sempre aprender coisas novas; 
- Preocupação com qualidade de código; 
- Contato com metodologia Scrum e métodos ágeis; 
- Experiência com desenvolvimento e uso de APIs.
## Diferenciais: 
 - Inglês Intermediário; 
- Experiência em prototipagem com Figma; 
- Experiência com ambiente AWS; 
- Experiência com desenvolvimento em plataforma lowcode (Webflow); 
- Experiência com a linguagem Java e frameworks Spring (boot, web, rest, data).
## Benefícios: 
 - Férias remuneradas; 
- 13º salário.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Developer (Vaga Afirmativa Para Mulheres) na Qred Brasil](https://coodesh.com/vagas/desenvolvedor-front-end-vaga-afirmativa-para-mulheres-152004406?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
