### ISSUE TITLE
[REMOTO] Estagiário/a - Front-end Dev apaixonado/a por educação na TutorMundi

### ISSUE THREAD

**Issue by namenotrequired** [frontendbr/vagas#7603]
## Nossa empresa

Educação é a base do futuro da sociedade. Você sabia que tutoria é de longe o método mais efetivo de ensino? (Não acredita? Pesquise: "Bloom two sigma")

Somos uma pequena startup com grandes ambições. Todos na empresa trabalhamos com paixão pela missão de trazer um tutor excelente para cada um na América Latina.

O TutorMundi é um aplicativo [web](https://app.tutormundi.com/), [iOS](https://apps.apple.com/br/app/tutormundi/id1171236598#?platform=iphone) e [Android](https://play.google.com/store/apps/details?id=app.tutormundi.com&hl=pt_BR) de reforço escolar onde alunos de ensino fundamental e médio têm acesso a tutores das melhores universidades na hora, online e sem agendar.

Dê uma olhada: https://www.tutormundi.com/

Já foram dadas mais de 5 milhões de minutos de aula na plataforma.

Recebemos investimento no vale do silício. Depois de um rápido crescimento de receita, hoje não dependemos mais de investimento externo. 

A empresa realmente investe nas pessoas. Por exemplo, ela apoiou um dev e um designer a passar 6 meses estudando em Stanford, e um estagiário a fazer mestrado no ITA. Alguns estagiários crescem tanto na empresa que dentro de um ano já passam a liderar equipes.

## Descrição da vaga

Você vai usar tecnologias web (HTML, CSS, JavaScript) para melhorar o nosso aplicativo em todas plataformas (web, Android, iOS).

Correções, melhorias, novas funcionalidades, se tiver interesse pode chegar a trabalhar com análise de dados, escalabilidade, inteligência artificial...

Você vai trabalhar remotamente com bastante apoio e (adivinhe?) tutoria do time. E ainda temos eventos informais para nos divertir.

## Local

Remoto

## Requisitos

Ser estudante (estar matriculado/a em uma faculdade)

Conhecimento de Git, HTML, CSS, JavaScript.

Paixão por educação.

Aprender rápido.

Atitude proativa.

## Benefícios

- Remoto
- Horário flexível
- Remuneração competitiva
- Equipe pequena e empolgada
- Empresa que realmente investe nas pessoas

## Contratação

estágio (a princípio 30h, 12 meses)

## Como se candidatar

Você pode se candidatar aqui: https://tutormundi.typeform.com/to/gMpcjar7

Qualquer dúvida, escreva para bart@tutormundi.com.

#### Alocação
- Remoto

#### Regime
- Estágio

#### Nível
- Júnior

**Comment by luizguilherme4** [comment]
Currículo enviado ✅

Pesquisei um pouco e achei a TutorMundi incrível e sua missão muito bela. Muito empolgado com essa oportunidade!

**Comment by jeffersondrs** [comment]
Enviado.

**Comment by sergiohdljr** [comment]
Estudo na Faculdade Senac Pernambuco, infelizmente não consta nas opções, como faço ?

**Comment by Riicky-hub** [comment]
> Estudo na Faculdade Senac Pernambuco, infelizmente não consta nas opções, como faço ?

Procure nas opções "outro", selecione ela se você não achar sua faculdade

**Comment by sergiohdljr** [comment]
obrigado pela resposta amigo, tenha um bom dia

**Comment by ocoiel** [comment]
Muitíssimo obrigado pela oportunidade! Seria incrível poder estagiar no TutorMundi!

**Comment by CiroGomess** [comment]
Enviado

**Comment by belloLucas** [comment]
CV enviado! A proposta da plataforma é muito interessante e me chamou muito a atenção, obrigado por compartilhar a oportunidade!

**Comment by GabrielGuedess** [comment]
Enviado 🚀

**Comment by OtavioCanedo** [comment]
Me candidatei aqui

**Comment by erikbernard** [comment]
Enviado, boa sorte a todos.

**Comment by PauloAbrahao** [comment]
Obrigado pela oportunidade! 
Amei a proposta da empresa, seria muito incrível participar e contribuir para esse objetivo!

Att, 
Paulo Abrahão

**Comment by FranciscoAraujo95** [comment]
Parece ser um ótimo lugar para se trabalhar, mesmo de forma remota. Espero ao menos participar do processo seletivo, qualquer experiência vale.

Currículo enviado. ✅

**Comment by BrunaaSoare** [comment]
Enviado✅✅

**Comment by talls2** [comment]
Enviado

**Comment by BrunaaSoare** [comment]
Vocês receberam alguma coisa depois que enviaram o currículo? Só pra confirmar mesmo

**Comment by FranciscoAraujo95** [comment]
> Vocês receberam alguma coisa depois que enviaram o currículo? Só pra confirmar mesmo

Não, apensa na ultima etapa tem um aviso sobre chegar algo no e-mail que cadastramos, acredito que só chegue caso você seja selecionado pra participar do processo.

**Comment by felipe-np** [comment]
Enviado! ✅

**Comment by lleo132** [comment]
Ótima oportunidade, com certeza irei participar!!

**Comment by lleo132** [comment]
Ótima oportunidade, enviado!!✅

**Comment by GustavoLOliveira** [comment]
Incrível oportunidade! currículo enviado ✅️

**Comment by aziulll** [comment]
Enviado!

**Comment by wellyntonsouza** [comment]
Enviei!! ✅️

**Comment by henrique-luc** [comment]
Que Oportunidade incrívil! enviado!

**Comment by nunesdotpy** [comment]
Enviado!

**Comment by kingjotaro** [comment]
Done!

**Comment by Mornieur** [comment]
Ótima oportunidade para trabalhar com educação!

Currículo enviado!

**Comment by FrBreno** [comment]
Enviado ✅️

**Comment by DanRodriguezdev** [comment]
Obrigado pela oportunidade!

Achei interessando a proposta da empresa, espero poder estar perto para fazermos coisas grandes.

**Comment by bluewemes** [comment]
Qual diferença entre 

**Comportamento e lógica** 
e
**Visual e layout**

na questão 09 do formulário?

Comportamento e lógica seria usando um framework tipo React, Angular ou Vue para fazer todo o frontend e 
Visual / layout sendo Figma, UI/UX?

Ou o comportamento e lógica envolve nodejs?

**Comment by maiaroberto** [comment]
Currículo Enviado ✅️
Otimista, como sempre, por acreditar que a vaga tem match certinho comigo ✅️

**Comment by namenotrequired** [comment]
@bluewemes Mais ou menos isso! Visual / layout sendo mais HTML/CSS e comportamento e lógica sendo mais JS no caso. Acaba evolvendo nodejs tb dependendo do interesse da(s) pessoa(s) contratada(s)

**Comment by GilAlvez** [comment]
Pronto me cadastrei!
Inclusive sobre essa questão de "logica x visual", acabei não sabendo qual ficou marcado, porque achei que podia marcar mais de uma (os dois acho interessante) e passou para o step seguinte, mas não tem problema não porque os dois acho compativeis comigo. Fico no aguardo de um feedback, obrigado e um abraço.

**Comment by gustavoalvim41** [comment]
Enviado!

**Comment by rafaelmarquesRM** [comment]
Enviado!

**Comment by marciolenes** [comment]
Vou começar meu primeiro semestre em fevereiro ainda. Haveria algum problema para concorrer a vaga de estágio?
Gostei demais do que vi e senti da empresa e gostaria demais em fazer parte dela.

**Comment by namenotrequired** [comment]
@marciolenes Não tem problema não!

**Comment by TonnCarvalho** [comment]
Currículo Enviado ✅️
Marquei Visual / layout pois sinto que venho dominando bem o HTML e CSS porem já comecei a estudar pesado o JS.

**Comment by Gabriel5748** [comment]
Enviado!
Quando saberemos se fomos aceitos ou não ?

**Comment by francisco-pedro** [comment]
A recepção do vosso email merece atenção especial, estou me questionando o seguinte: Como será a lista dos candidatos apurados? Porque no vosso email só tem especificações de comentários de usuários candidatos (Github)

**Comment by namenotrequired** [comment]
Pretendemos fechar o formulário na segunda-feira dia 6 de fevereiro, e dar uma resposta para todos candidatos até dia 10.

**Comment by rafaelsilva81** [comment]
Enviado! 🚀

**Comment by viviandemitry** [comment]
Feliz de ter visto a tempo! Acabei de me cadastrar. Obrigada!

**Comment by RCysne** [comment]
Bom dia, é necessário estar cursando uma faculdade? No meu caso, estou fazendo transição de carreira, já sou formado, mas estou buscando uma vaga Júnior para aprender cada vez mais, e acrescentar no que puder a empresa.

**Comment by eriknegreiros** [comment]
Acabei de me inscrever, obrigado pela oportunidade!

**Comment by namenotrequired** [comment]
Bom dia @RCysne, nessa vaga particularmente, é um requisito sim!

**Comment by namenotrequired** [comment]
Muito obrigado a todo mundo que se inscreveu! Pretendemos responder todos candidatos ainda essa semana.

**Comment by RCysne** [comment]
Bom dia @namenotrequired. Como o prazo era até ontem, eu enviei antes de receber sua resposta. Obrigado pelo retorno, e peço que desconsidere a minha inscrição. Espero uma próxima oportunidade. Até mais.

**Comment by Miicchhel** [comment]
Olá, @namenotrequired, tudo bem? Eu fiz a inscrição agora, mas pelo visto o prazo já se encerrou não é mesmo? Bom, de qualquer forma, foi um prazer conhecer o trabalho de vocês, a iniciativa é realmente muito boa. Esperarei por uma nova oportunidade, abraço.
