### ISSUE TITLE
[Remoto] Front-end Developer SR na Synvia

### ISSUE THREAD

**Issue by jsantosrh** [frontendbr/vagas#7605]
## Nossa empresa

Nosso cliente/parceiro é uma holding dos segmentos de saúde e tecnologia de indústrias farmacêuticas e de diagnósticos. Possuem uma visão voltada para inovação e investindo continuamente em infraestrutura de alta tecnologia. São referência em estudos de equivalência e bioequivalência farmacêutica e em biologia molecular. Quer fazer parte desta história? Vem com a gente!

## Descrição da vaga

- Atuar no desenvolvimento de novos projetos e propor novas tecnologias;
- Auxiliar na avaliação de requisitos propostos e desenvolver interfaces e funcionalidades;
- Produzir o layout do produto digital e criar interatividade entre os elementos da página ou do aplicativo;
- Utilizar frameworks e pré-processadores;
- Controle de versão do código utilizando GIT;
- Mentorear pessoas da equipe no desenvolvimento das ferramentas e atividades.

## Local

Remoto ou Híbrido, [São Paulo]

## Requisitos

**Obrigatórios:**
- Superior completo em: Sistema de Informação, Ciência da computação, Análise de Sistemas ou Engenharia da Computação;
- Sólida experiência nas linguagens de JavaScript, TypeScript, HTML e CSS utilizando os frameworks como Angular 7+ ou React;
- Sólida experiência como Desenvolvedor Front-End;
- Desejável: conhecimento em integração de dados Front-end > Back-end;
- Desejável: conhecimento em React Native;
- Desejável : ter trabalhado com desenvolvimento e layout de sites.

**Desejáveis:**
- Autonomia e Liderança para Trabalhar em Equipe;
- Capacidade Analítica e visão estratégia;
- Relacionamento Interpessoal;
- Capacidade para Resolver Problemas.

## Benefícios

_ Plano de Saúde;
- Plano Odontológico;
- Seguro de Vida;
- Convênio Farmácia;
- VR;
- VT;
- Estacionamento;
- Day Off de Aniversário.

## Contratação

CLT ou PJ

## Como se candidatar

Por favor envie um email para ksouza@acelerarh.com.br com seu CV anexado - enviar no assunto: Vaga Front-End 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: ksouza@acelerarh.com.br

#### Nível
- Sênior

**Comment by joaoromeira** [comment]
@jsantosrh experiência equivalente pode ser considerada ao invés do curso superior? Tenho pouco mais de 5 anos na área e curso técnico

**Comment by reinaldocicarone** [comment]
Enviado
