### ISSUE TITLE
[PORTUGAL] Front-End Developer na INTEGER Consulting!

### ISSUE THREAD

**Issue by FilipeGM** [frontendbr/vagas#7606]
Oi! 👋

O fim de semana está aí! Não existe melhor ocasião para avaliar novos desafios! 😜

O meu nome é Filipe Marques e faço parte da INTEGER! A INTEGER é uma empresa de consultoria, portuguesa, com foco em consultoria de IT (Outsourcing) e desenvolvimento de Software e Produto (internamente).
Somos conhecidos no mercado, por darmos um ótimo acompanhamento aos nossos consultores, pela experiência que temos e pela ajuda que damos a profissionais de outros países que querem vir para Portugal!
Tens interesse em vir para Portugal? Então, somos a melhor opção!

As vagas que tenho em aberto atualmente são:
👉 Gestor de Projeto
👉 Java Developer
👉 iOS Developer
👉 Salesforce Developer
👉 QA – Test Automation
👉 Frontend Developer (React.JS ou Angular)

Benefícios base:

- Plano de saúde (para o candidato e família);
- Alojamento nas primeiras duas semanas em PT;
- Acompanhamento durante todo o processo de vinda para PT;
- Acesso gratuito à Udemy;
- Acesso gratuito a plataformas para o desenvolvimento da língua inglesa;
- Acesso à nossa rede de parcerias - Descontos em serviços, academia, cosmética, restauração, etc...;

Descobre estas e mais oportunidades e os seus requisitos, no nosso site: https://lnkd.in/gE4c_bB

Envia o teu CV, atualizado e em inglês, para filipe.marques@integer.pt !
OU entra em contacto comigo, por aqui - Whatsapp (+351 910 385 109), com o teu currículo em anexo, de preferência em inglês.

**Comment by leoopl** [comment]
Jr, Pl ou Sr?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
