### ISSUE TITLE
[REMOTO] Front-end Developer Senior na Totvs

### ISSUE THREAD

**Issue by Felipepirova** [frontendbr/vagas#7608]
## Nossa empresa

Você sabia que as tecnologias da TOTVS impactam o dia a dia de milhões de pessoas e contribuem para o crescimento de mais de 40 mil empresas no Brasil e no mundo?

Se você é focado(a) em resultados e gosta de um ambiente colaborativo, dinâmico e de aprendizado diário, venha fazer parte do nosso time!

Venha ser TOTVER!

Venha ousar e transformar na maior empresa de tecnologia do Brasil.

#ouseetransforme
#sejaTOTVER

## Descrição da vaga

- Desenvolver soluções técnicas de média e alta complexidade, com baixo nível de supervisão e pouco apoio, através do desenvolvimento de requisitos de softwares utilizando-se das tecnologias envolvidas no projeto;
- Conhecer a fundo a arquitetura do software e ser capaz de atuar nela através da análise de seus componentes, organização e funcionalidades;
- Criar testes de alta complexidade, sejam estes manuais ou automatizados, que cubram o comportamento desejado dos componentes técnicos desenvolvidos utilizando os requisitos e ferramentas de testes;
- Documentar as etapas de desenvolvimento realizando o registro do desenvolvimento nas ferramentas de versionamento e documentação;
- Orientar e trabalhar com o time de desenvolvimento para encontrar soluções de negócio, arquitetura e desenho através da comunicação e trocas de conhecimento;
- Manter a qualidade do software verificando os processos, ferramentas e boas práticas disponíveis para o produto e tecnologia utilizados;
- Orientar desenvolvedores de menor senioridade apoiando suas dúvidas, disseminando seu conhecimento, desenhando e arquitetando soluções ou indicando documentação de apoio;
- Revisar o código dos colegas e atuar no desenvolvimento coletivo do time;
- Detalhar requisitos de média e alta complexidade através do contato com clientes e áreas envolvidas no projeto/atendimento;
- Utilizar frameworks já definidos para o desenvolvimento de soluções;
- Apoiar na prospecção, adoção e capacitação de novas tecnologias.

## Local

Remoto 

## Requisitos

- Angular (framework Totvs / PO UI);
- HTML 5, CSS3, JavaScript (TypeScript);
- Experiência com a metodologia Ágil (Scrum/Kanban);
- Conhecimento em boas práticas de programação (Clean code, SOLID e etc).

## Benefícios

- Universidade em Rede TOTVS, uma universidade Corporativa com conteúdos e certificações gratuitos para os nossos TOTVERS;
- Programa +Saudáveis, que cuidamos dos nossos TOTVERS com assessoria e ações voltadas para o bem estar em corpo, mente e finanças pessoais;
- Programa +Vantagens, a maior rede de descontos da América Latina, exclusivos para nossos TOTVERS;
- Plano de saúde e odontológico;
- Vale refeição;
- Vale transporte e fretados em algumas estações do metrô;
- Licença maternidade e paternidade estendida;
- Espaço de lactário;
- Bicicletário;
- Vestiário;
- Seguro de vida;
- Auxílio creche;
- Previdência privada;
- Escritório que estimula a criatividade e produtividade com ambientes para lanches, salas de jogos, mesas de bilhar e poltronas para relaxar;
- Gympass;

## Contratação

CLT 

## Como se candidatar

Por favor envie seu linkedin ou cv para gustavo.valandro@totvs.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
