### ISSUE TITLE
[REMOTO] Front-end Lead na Lemon Energy 

### ISSUE THREAD

**Issue by lucastori** [frontendbr/vagas#7609]
> Vaga Remota durante a pandemia

## Nossa empresa

Por anos o mercado de energia foi dominado por grandes fornecedores que colocam o lucro antes e o cliente depois. Os consumidores de energia eram apenas pagadores de contas e não eram tratados como clientes de fato. Agora nós estamos usando tecnologia de ponta e fontes sustentáveis para transformar a experiência de consumo de energia no Brasil, tornando-a mais limpa, mais simples e mais barata.

A Lemon é uma das primeiras climate techs brasileiras. Nossa missão é melhorar a vida das pessoas através da energia sustentável. Combatemos o aquecimento global ajudando nossos clientes a escolherem fontes limpas de energia e criando o mercado para que mais usinas verdes sejam construídas no nosso planeta.

Para causar um grande impacto precisamos de grandes profissionais com pensamento diverso. Estamos construindo um time com gente de diferentes formações, backgrounds, indústrias e experiências. Queremos conhecer pessoas extremamente competentes e que tenham paixão pelo nosso propósito, vontade de fazer diferença e energia para encarar grandes desafios. Não contratamos apenas quem está alinhado com com a nossa cultura, procuramos quem também vai acrescentar a ela.

## Descrição da vaga

**QUEM ESTAMOS BUSCANDO**

Estamos à procura de alguém para o nosso time de Front End. Somos uma startup jovem e por um lado temos muitas coisas novas para construir do zero, mas por outro também temos milhares de clientes que contam com que o nosso produto continue simples, transparente e de alta qualidade. Procuramos alguém que esteja com interesse em trabalhar com novas tecnologias em domínios multidisciplinares, mas sem abrir mão de um elevado rigor técnico. Nessa posição você vai poder ter um grande impacto individual e possibilidade de influenciar como os nossos sistemas são construídos. Esperamos que você cresça rápido e que contribua para o desenvolvimento das pessoas ao seu redor.

**O QUE VOCÊ VAI ENCONTRAR NA LEMON**

- Você entrará em contato com muitos problemas desafiadores de design de sistemas. O setor de energia é altamente regulado, defasado tecnologicamente e com muita complexidade intrínseca. Temos muitos modelamentos de domínio para fazer e por isso é essencial ter atenção aos detalhes e aos casos de borda.

- Você terá que resolver problemas complexos trabalhando com um time multidisciplinar. Trabalhar no mesmo time com pessoas de produto, design, engenharia, operações, vendas, atendimento e jurídico vai te exigir pensar de forma mais ampla e a se comunicar melhor.

- Trabalhar em um time pequeno significa que o seu trabalho será muito relevante e visível para todas as pessoas da empresa. Você terá muitas oportunidades de causar grandes impactos e suas tarefas serão de extrema relevância para o negócio.

- Somos uma empresa 100% remota e trabalhamos de forma assíncrona. Acreditamos que esse formato de trabalho nos dá liberdade e flexibilidade para atingirmos nosso melhor potencial, mas ele também traz a responsabilidade de termos que nos organizar e nos comunicar de forma muito eficiente.

- Construir sistemas do zero exige que você tenha tolerância para lidar com incertezas, mas que também tenha o rigor técnico para que nosso ecossistema tecnológico continue saudável.

- Você vai encontrar um time incrível e esperamos que você se desenvolva tecnicamente mas que também contribua para a formação da nossa cultura.

**RESPONSABILIDADES DA POSIÇÃO DE FRONT END NA LEMON**

- Trabalhar com o time de design e backend para desenvolver aplicações SPAs ou SSR no ambiente da AWS, que serão utilizadas por clientes internos e externos, e com os mais diferentes fins. Sempre visando a melhor experiência para eles!
- Desenvolver, manter e documentar pacotes que são a base de nossas aplicações e de diferentes utilidades: componentes UI, ferramentas de analytics, state management, roteamento e outros.
- Participar e auxiliar no crescimento individual e coletivo dos colegas de time, através da disseminação de conhecimento, talks, treinamentos e outros.

## Local

Remoto

## Requisitos

**Obrigatórios:**

- Apresenta uma base sólida de conhecimento em HTML, CSS, Javascript;
- Possua experiência com frameworks SPAs (React, Angular, Vue) e noções básicas de frameworks SSR (Remix, Next);
- Que goste de trabalhar na melhoria contínua para um código mais limpo, testado, documentado e organizado;
- Goste de trabalhar em equipes multidisciplinares, com bastante autonomia e participação em todas as etapas do desenvolvimento de um produto, desde a concepção até ao monitoramento após a entrega.

**Desejáveis:**

Não esperamos que você já conheça tudo isso, procuramos pessoas curiosas e que estejam dispostas a aprender

React
Styled-components
git / Github
Experiência com aplicações SSR
Remix
AWS

**Diferenciais:**

- Tem interesse pelo mercado de energia e de sustentabilidade;
- Se empolga com problemas difíceis, não só técnicos como de negócio também;
- Fica confortável em um ambiente de muitas mudanças;
- Tem comunicação fluída, frequente e assertiva, tanto escrita como falada;
- Gosta de trabalhar de forma colaborativa;
- Extra: teve experiências anteriores relevantes e desafiadoras que te deixam confiante de encarar nossos desafios.

## Benefícios

- Chance de ganhar equity numa empresa de crescimento exponencial
- Horário flexível e home office
- Coworking em todo o país
- Benefício flexível - CAJU (pode ser usado nas categorias alimentação, refeição, mobilidade, educação, saúde e cultura)
- Plano de saúde
- Plano odontológico
- Programa de saúde mental e bem-estar
Gympass
- Lemon Feriados (além dos feriados nacionais, você tem alguns dias no ano à sua escolha para curtir uma folguinha ou emendar o descanso antes ou depois de um feriado)

**Diferenciais:**

Nosso modelo de contração é PJ, mas temos benefícios, como: 13º terceiro e férias remuneradas. 

## Contratação

PJ a combinar

## Como se candidatar

Basta se candidatas através desse link: https://lemon-energy.breezy.hr/p/906e36433ec8-frontend-lead

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

#### Alocação

- Remoto

#### Regime

- PJ

#### Nível

- Especialista

**Comment by matheusmcz** [comment]
Enviado! 💯

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
