### ISSUE TITLE
[Rio de Janeiro] Front-end Developer Jr na WEBEDIA

### ISSUE THREAD

**Issue by thiagopsnfg** [frontendbr/vagas#761]
## Descrição da vaga

- Trabalhará como desenvolvedor em um projeto novo e ambicioso
- Contribuirá no planejamento e evolução do projeto
- Atuará com toda a equipe, auxiliando na compreensão da necessidade do cliente, como nas estratégias de desenvolvimento, levantamento de requisitos e demais necessidades técnicas
- Auxiliará na padronização do código e na documentação de projetos

## Benefícios

- Café da manhã e da tarde
- Vale refeição
- Vale transporte
- Plano de saúde
- Plano odontológico
- Festinhas

## Requisitos

**Obrigatórios:**
- Sólido conhecimento em Javascript
- Sólido conhecimento em desenvolvimento com a biblioteca React
- Habilidade de desenvolvimento em NodeJS
- Sólido conhecimento em tecnologias front-end e responsividade (HTML5, CSS)
- Conhecimento com sistemas de versionamento Git
- Conhecimento em consumir APIs RESTful
- Inglês intermediário (leitura e escrita);

**Diferenciais:**
- Conhecimento em bancos de dados (MySQL)
- Conhecimentos em outras linguagens
- Conhecimento com pré-processadores de CSS (preferencialmente SASS)
- Testes (Unitários, Snapshot, integração...)

## Contratação

CLT

## Nossa empresa
A Webedia é um grupo de mídia digital de origem francesa presente em mais de dez países, com verticais que totalizam 177 milhões de usuários únicos por mês, dos quais 47,3 milhões estão no Brasil, a maior audiência do grupo. Na América Latina, ocupa a 8ª colocação entre as maiores audiências digitais na área de entretenimento, segundo o ComScore.

O sucesso se deve ao controle de sites líderes em segmentos estratégicos: TudoGostoso (foods), AdoroCinema (entretenimento), IGN (games), PurePeople e Purebreak (glamour), Minha Vida (saúde e bem-estar), Hypeness (Inovação e Criatividade) e Versus (e-sports). Por meio da divisão de Brand Publishing, a Webedia oferece ainda conhecimento em audiência para marcas, atuando com produtos de big data que alcançam as melhores performances.

## Como se candidatar

Por favor envie um email para thiago.santos@webedia-group.com e thiago.verly@webedia-group.com com seu CV anexado - enviar no assunto: Vaga FrontEnd Developer

**Comment by RenatoAreas** [comment]
@thiagopsnfg Tudo bem ?! Já preencheram a vaga ?

**Comment by thiagopsnfg** [comment]
@RenatoAreas ainda não, estamos no processo seletivo ainda.

**Comment by nandosangenetto** [comment]
Podem adicionar a tag de Júnior, por favor?

@LFeh

**Comment by RenatoAreas** [comment]
Currículo enviado. Estou na torcida.

**Comment by nandosangenetto** [comment]
Vaga preenchida já, @LFeh. 

Pode fechar. 👍
