### ISSUE TITLE
[Remoto] Front-end Developer na Empreender

### ISSUE THREAD

**Issue by serenarhempreender** [frontendbr/vagas#7610]
> Vaga Remota durante a pandemia

## Nossa empresa

Somos um grupo focado em tecnologia e educação. A Empreender tem como missão criar ferramentas inovadoras, afim de contribuir com o mercado de Dropshipping e educação!

## Descrição da vaga
Estamos em busca de profissionais capacitados para completar nosso time de desenvolvedores FrontEnd.

## Local

Remoto 

## Requisitos

• Experiência com HTML, CSS e Javascript;
• Agilidade com SASS/Bootstrap;
• Experiência com Apis Rest;
• Experiência com ReactJS

## Benefícios
-Bônus de natal;
-Bônus de aniversário;
-Bônus de três meses;
-Aulas de Idiomas (Inglês e espanhol);
-Participação programa férias;
-Participação de Lucros(PL);
-Acesso a uma plataforma de cursos;

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para serena@empreender.com.br com seu CV anexado e o links do linkedin e GitHub (ou outro portfólio) enviar no assunto: Vaga FrontEnd

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

**Comment by sucodelarangela** [comment]
Enviado!

**Comment by RuanHeleno** [comment]
Enviado!

**Comment by wuzue** [comment]
Enviado  :)

**Comment by herlanderbento** [comment]
Enviado!

**Comment by manudeveloper82** [comment]
Enviado!🥰❤️

**Comment by eusouomanoel** [comment]
Enviado !

**Comment by PauloAbrahao** [comment]
Boa noite! Currículo enviado!

**Comment by gustavoalvim41** [comment]
Enviado!

**Comment by DarlanSantosCarvalho** [comment]
Enviado

**Comment by savio-2-lopes** [comment]
Enviado

**Comment by Henry001-prog** [comment]
Enviado

**Comment by GabrielGuedess** [comment]
Enviado 🚀

**Comment by artenlf** [comment]
Enviado

**Comment by danmatuoka** [comment]
enviado!

**Comment by JoaoEduardo10** [comment]
Enviado!

**Comment by PedroRavaglia** [comment]
Enviado

**Comment by matheusmcz** [comment]
Enviado! 💯

**Comment by heymendezz** [comment]
Enviado.

**Comment by brunomourabastos** [comment]
Enviado.

**Comment by sabrinapratafernandes** [comment]
Enviado!

**Comment by WelllWas** [comment]
Enviado!

**Comment by RubenFontes** [comment]
Enviado!

**Comment by felipysantos** [comment]
Enviado

**Comment by antoniornneto** [comment]
Enviado

**Comment by JoneBulande** [comment]
Saudações, Email enviado.

**Comment by RamosTailon** [comment]
Enviado!

**Comment by byron-smith-nobrega** [comment]
Enviado

**Comment by LucasCalabria7** [comment]
Enviado !

**Comment by LucasMarks8** [comment]
> [serena@empreender.com.br](mailto:serena@empreender.com.br)

Enviado!

**Comment by marcelocsn** [comment]
I sent my resume to the above email address. 👍

**Comment by erica-l-s** [comment]
Enviado!!!

**Comment by ellen-ls** [comment]
Enviado!

**Comment by avilacarol-bit** [comment]
Enviado.

**Comment by guimevn** [comment]
Enviado.

**Comment by CleytonW** [comment]
Enviado

**Comment by andressadarze** [comment]
Enviado!

**Comment by Jmaraguiar** [comment]
Enviado!

**Comment by Gabriellopes232** [comment]
Enviado!

**Comment by AlexMarquesAlves** [comment]
Enviado

**Comment by antonioalexandre1984** [comment]
Enviado

**Comment by TiagoPSouza** [comment]
> > Vaga Remota durante a pandemia
> 
> ## nossa empresa
> Somos um grupo focado em tecnologia e educação. A Empreender tem como missão criar ferramentas inovadoras, afim de contribuir com o mercado de Dropshipping e educação!
> 
> ## Descrição da vaga
> Estamos em busca de profissionais capacitados para completar nosso time de desenvolvedores FrontEnd.
> 
> ## Local
> remoto
> 
> ## Requisitos
> • Experiência com HTML, CSS e Javascript; • Agilidade com SASS/Bootstrap; • Experiência com Apis Rest; • Experiência com ReactJS
> 
> ## benefícios
> -Bônus de natal; -Bônus de aniversário; -Bônus de três meses; -Aulas de Idiomas (Inglês e Espanhol); -Participação do programa de férias; -Participação de Lucros(PL); -Acesso a uma plataforma de cursos;
> 
> ## Contratação
> PJ a combinar
> 
> ## Como se candidatar
> Por favor envie um email para [serena@empreender.com.br](mailto:serena@empreender.com.br) com seu CV anexado e links do linkedin e GitHub (ou outro portfólio) envie no assunto: Vaga FrontEnd
> 
> ## Tempo médio de feedbacks
> Costumamos enviar feedbacks em até 10 dias após cada processo.
> 
> ## Labels
> #### Alocação
> * Remoto
> 
> #### Regime
> * PJ
> 
> #### Nível
> * Júnior
> * Pleno

**Comment by samirdourado** [comment]
Enviei !

**Comment by Ikarosv** [comment]
Enviado!
Espero ansiosamente pela resposta 😄

**Comment by GabrielFray** [comment]
Enviado

**Comment by jeffersondrs** [comment]
Enviei dia 30 de Jan e nenhum feedback.

**Comment by joaov1ct0r** [comment]
Enviado

**Comment by reinaldocicarone** [comment]
enviado

**Comment by JailsonSantos** [comment]
Enviado com sucesso.

**Comment by FeRiffo** [comment]
Enviado!

**Comment by Virkkunen** [comment]
Enviado

**Comment by matheus1994santos** [comment]
Enviado

**Comment by srenessa** [comment]
Enviado!

**Comment by Miicchhel** [comment]
Enviado!

**Comment by evertondsvieira** [comment]
Enviado

**Comment by MatheusFilg** [comment]
enviado!

**Comment by FilipeTenedini** [comment]
Enviado!

**Comment by francisco-pedro** [comment]
Enviado com sucesso

**Comment by EdiJunior88** [comment]
Enviado 😎

**Comment by adhmattheus** [comment]
Enviado

**Comment by gvao** [comment]
Caros, acabei de enviar o e-mail com meu currículo e agradeço pela oportunidade!

**Comment by nathansodre** [comment]
Enviado!

**Comment by lucasrip** [comment]
enviado

**Comment by GabrielZolk** [comment]
Enviado

**Comment by GabrielZolk** [comment]
Enviado!

**Comment by gitsena** [comment]
Enviado 😁

**Comment by vanessawin** [comment]
Enviado
