### ISSUE TITLE
[Remoto] Front-End Developer na FreeCast

### ISSUE THREAD

**Issue by mediumhotcoffee** [frontendbr/vagas#7612]
## Nossa empresa

- FreeCast, Inc. is a content discovery and management engine operating the world's largest freely available Video On-Demand (VOD) & Pay-per-view (PPV) library online
- The FreeCast Network is delivered in the form of a eMedia guide on all devices through FreeCast, a co-branded service for bandwidth distributors and device manufacturers

## Descrição da vaga

- Important stuff:
    - Compensation: US$25.00/h
    - Schedule: Full-time (~40–45h/week, min. 40h)
    - Work hours: Monday–Friday, 8:30–9 AM to 5–5:30 PM EST
    - Type: Contract (NDA required)
- Description:
    - We're looking for a React Developer for our Tizen/webOS Development Team
    - You'll be responsible for improvements, new features, and bug fixes on the FreeCast Tizen and WebOS React apps
    - The ideal candidate has great communication skills, can multitask, is self-motivated, and works well in a remote team environment
    - This person must have a passion for what they do, can organize responsibilities to identify and handle potential gaps and blockers to ensure that the tasks they and the team own can be completed on schedule

## Local

Remote

## Requisitos

**Obrigatórios:**
- 3+ years of experience with React
- Knowledgeable in working with REST APIs
- Familiar with the Git VCS
- Experience with writing unit tests
- Experience with functional programming

**Desejáveis:**
- Experience working in a remote team environment
- Familiar with the Kanban Agile framework
- Knowledgeable in Object-Oriented Design
- Ability to multitask, organize, and prioritize work
- Ability to communicate effectively
- Ability to work effectively under time constraints
- Ability to quickly identify gaps, risks, and blockers
- Attention to detail
- Intermediate spoken English (you might be required to participate in calls with the Development Department)

**Diferenciais:**
- Familiar with developing TV apps on Tizen (Samsung) and/or on webOS (LG)
- Familiar with [Firebase](https://firebase.google.com)
- Familiar with [Bugsnag](https://www.bugsnag.com)
- Familiar with [Axios](https://github.com/axios/axios)
- Familiar with [React Query](https://react-query-v3.tanstack.com)
- Familiar with [zustand](https://github.com/pmndrs/zustand)
- Familiar with [React Router](https://reactrouter.com/en/main)
- Advanced or fluent written and/or spoken English

## Benefícios

- N/A

## Contratação

- PJ or freelancer. Payments made via Payoneer.

## Como se candidatar

- Email your résumé to marcos@freecast.com
    - Subject: React Developer position, <your_full_name>
    - Attach your résumé as a PDF file (résumé _must be in English_)
    - Your résumé and personal information will _not_ be retained and will be deleted at the end of the selection process

## Tempo médio de feedbacks

- We'll review your résumé and contact you within 7 days of receiving your application
- If your résumé is selected for an interview, we'll schedule a 1h phone interview with you
- If you pass the phone interview, you'll be required to complete a take home coding test
- After you submit the test, we'll review your code and get back to you in 2-3 business days
- If you pass the coding test and accept an offer, you'll be required to sign a contract and a NDA to begin employment on the following week
- E-mail in case you don't receive a reply in a timely manner or have any questions about your application, please email marcos@freecast.com

#### Alocação

- Remoto

#### Regime

- Freela
- PJ

#### Nível

- Pleno
- Sênior

## Some of the people you will work with

- Marcos Silva
    - Mobile & TV Development Manager at FreeCast, Inc.
    - [LinkedIn](https://www.linkedin.com/in/marcossilva7/)
    - marcos@freecast.com
- Macgyver Martins
    - React Developer at FreeCast, Inc.
    - [LinkedIn](https://www.linkedin.com/in/macgyver-martins/)
- Patrick Januário
    - React Developer at FreeCast, Inc.
    - [LinkedIn](https://www.linkedin.com/in/patrick-brison-januario-02871912a/)

**Comment by RenanLucenaDeveloper** [comment]
Submitted!

**Comment by mediumhotcoffee** [comment]
Hello,

due to the large interest in this position we're closing down applications for now. If you've applied, you will receive your results shortly.

We appreciate the time and effort of everyone who applied. Should you have any questions about the status of your application, please contact me at [marcos@freecast.com](mailto:marcos@freecast.com).
