### ISSUE TITLE
[Desenvolvedor Front End Pleno React.js] - Remoto -  HunterHunter

### ISSUE THREAD

**Issue by ErickaMB** [frontendbr/vagas#7614]
[Desenvolvedor Front End Pleno React.js] - Remoto. R$ 5.000.00 CLT a R$ 6.000,00 CLT.

obs: encontros trimestrais em SP (região da Paulista) - não pagamos o transporte do colaborador para estes encontros, o colaborador deve custear.

Benefícios:

Plano de saúde do colaborador pago pela empresa sem coparticipação

Vale alimentação de R$20/dia.

100% home office com encontros trimestrais em SP (região da Paulista) - não pagamos o transporte do colaborador para estes encontros, o colaborador deve custear.

Disponibilizamos o computador para trabalho ou pagamos um valor mensal de ajuda de custo caso o colaborador prefira utilizar o dele.

Estamos procuramos desenvolvedor React nível pleno que irá atuar com o desenvolvimento de novo aplicativo e manutenção do mesmo.

Requisitos:

Experiência sólida em desenvolvimento de interfaces complexas em React

Familiaridade com Git e Git Flow.

Familiaridade com TDD, BDD, Testes unitários.

Boas práticas referente a acessibilidade.

Algum conhecimento com ferramentas de métricas (Google Analytics, Firebase e outros).

Algum conhecimento referente a testes de performance da aplicação

Ficamos localizados em São Paulo, mas nosso formato de trabalho é Home Office com encontros trimestrais.

Se tem interesse e com requisitos da oportunidade entre em contato pelo Linkedin informando qual é a oportunidade. [[https://www.linkedin.com/in/erickamarquesb/]](https://www.linkedin.com/in/erickamarquesb/%5D)

**Comment by RamosTailon** [comment]
Enviado a mensagem.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
