### ISSUE TITLE
[Desenvolvedor Front End Sênior React] - Remoto -  HunterHunter

### ISSUE THREAD

**Issue by ErickaMB** [frontendbr/vagas#7615]
[Desenvolvedor Front End Sênior React] - Remoto. R$ 6.500,00 a R$ 7.500,00 negociável CLT.

obs: encontros trimestrais em SP (região da Paulista) - não pagamos o transporte do colaborador para estes encontros, o colaborador deve custear.

Benefícios:

Plano de saúde do colaborador pago pela empresa sem coparticipação

Vale alimentação de R$20/dia.

100% home office com encontros trimestrais em SP (região da Paulista) - não pagamos o transporte do colaborador para estes encontros, o colaborador deve custear.

Disponibilizamos o computador para trabalho ou pagamos um valor mensal de ajuda de custo caso o colaborador prefira utilizar o dele.

Estamos procuramos desenvolvedor React nível sênior que irá atuar com o desenvolvimento de novo aplicativo e manutenção do mesmo.

Requisitos:- Experiência de mais de 5 anos em desenvolvimento de interfaces complexas em React- Familiaridade com Git e Git Flow.- Familiaridade com TDD, BDD, Testes unitários.- Boas práticas referente a acessibilidade.- Conhecimento e experiência com ferramentas de métricas (Google Analytics, Firebase e outros).- Conhecimento referente a testes de performance da aplicação- Conhecimento e experiência em clean code e react query- Experiência com repasse de conhecimento em React para outras pessoas da equipeFicamos localizados em São Paulo, mas nosso formato de trabalho é Home Office com encontros trimestrais.

Se tem interesse e com requisitos da oportunidade entre em contato pelo Linkedin informando qual é a oportunidade. [[https://www.linkedin.com/in/erickamarquesb/]](https://www.linkedin.com/in/erickamarquesb/%5D)

**Comment by deyvisonborges** [comment]
Salário muito baixo e muita exigência de requisitos.

**Comment by jonatasbueno** [comment]
TAG [Remoto] entretando a vaga é de Híbrido

Salário muito abaixo do mercado. Sênior CLT está recebendo acima disso, PJ no mínimo deveria ser maior que a média CLT

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
