### ISSUE TITLE
[Remoto] Staff/Sr Frontend Engineer na Latitud

### ISSUE THREAD

**Issue by teles** [frontendbr/vagas#7617]
## Nossa empresa

Você pode pensar no Latitud como o sistema operacional para startups na América Latina. Os fundadores de startup nos amam. [Aqui está o que eles têm a dizer](https://www.youtube.com/watch?v=5i5GoHvkLm8).

<a href="https://www.youtube.com/watch?v=5i5GoHvkLm8" target="_blank"><img width="680" alt="Screen Shot 2023-02-01 at 13 43 37" src="https://user-images.githubusercontent.com/762639/216106746-5c3c6af1-e92d-413a-af8c-6ce0bcae911e.png"></a>

O Latitud foi criado por Brian Requarth, que fundou, escalou e vendeu o Viva Real por US$ 600 milhões, Gina Gotthilf, que liderou o crescimento do Duolingo de 3 milhões para 200 milhões de usuários, e Yuri Danilchenko, que escalou produtos e engenharia na Escale, apoiada por Kaszek.

Latitud está em um momento muito emocionante, acabamos de arrecadar $ 11,5 milhões lideradas por a16z e NfX e outros $ 1,5 milhões da comunidade. Isso significa que estamos crescendo e você terá a oportunidade de contribuir com a estratégia e a cultura que construímos juntos.

## Descrição da vaga

TLDR, você se juntará à Latitud como um de nossos primeiros engenheiros e nos ajudará a criar produtos para fundadores na América Latina desde o início.

**Você irá:**

* Definir nossa arquitetura de front-end e práticas de codificação
* Gerenciar outros desenvolvedores de front-end e oferecer suporte a desenvolvedores no front-end
* Design para internacionalização (i18n) para nos permitir lançar para o resto da América Latina rapidamente
* Trabalhar em estreita colaboração com o produto para colaborar em nossa visão e estratégia
* Ajude a orientar e integrar novos membros da equipe à medida que crescemos
* Ajude a definir e moldar nossa cultura e princípios de engenharia

**😎 Você é:**

* Um(a) engenheiro(a) de software experiente. Você tem vários anos de experiência na criação de aplicativos da Web ou móveis. Você liderou grandes iniciativas de engenharia de software no nível de produto ou empresa e gosta de orientar engenheiros(as) juniores.

* Um(a) aprendiz rápido. Não esperamos que você saiba tudo sobre nosso domínio e stack, mas precisamos que você se atualize rapidamente.

* Pragmático(a). Você se apaixona por problemas, não por soluções. Sua tendência para obter feedback rapidamente enviando coisas para produção para usuários reais e medindo o impacto de suas alterações. Você prioriza os resultados sobre o processo.

* Apaixonado(a) por acessibilidade, diversidade e inclusão. Latitud não é uma boa opção para você se você se sentir desconfortável ou irritado com esses tópicos.

* Interessado(a) em se envolver com a comunidade de startups. Os fundadores de startups na LATAM são nossa persona principal e você está interessado em trabalhar com eles ou deseja ingressar em suas fileiras em alguns anos.

## Local

100% Remoto

## Requisitos

**Obrigatórios:**

- Forte em linguagens de front-end modernas (JavaScript, TypeScript e CSS)
- Experiente na construção de um aplicativo da Web completo usando uma estrutura JavaScript (React, Vue, etc.)
- Familiarizado(a) com teste unitários de front-end e teste de navegador automatizado
- Familiarizado(a) com rastreamento de erros e rastreamento de comportamento do usuário

**Desejáveis:**

- Experiência com fintech ou produtos regulamentados
- Experiência com internacionalização (i18n)
- Experiência com bibliotecas de gráficos e criação de produtos ricos em dados
- Anteriormente trabalhou em startups em fase inicial

## Benefícios

- Trabalhe de qualquer lugar (100% remoto)
- Equity generoso
- Seguro saúde 100% coberto (incluindo dependentes)
- Subsídio anual de coworking ou bônus anual de home office
- Apólice PTO Ilimitada com orientações justas para licenças (paternidade, maternidade, doença, etc)
- Viagem de equipe por nossa conta!

## Contratação

CLT ou PJ a combinar

## Como se candidatar

Por favor acesse nossa página no [Ashby’s e clique em Apply for this job](https://jobs.ashbyhq.com/latitud/e1441821-b08f-4cb6-9cb3-29dbb889ed69) on clique no botão abaixo:

<a href="https://jobs.ashbyhq.com/latitud/e1441821-b08f-4cb6-9cb3-29dbb889ed69/application" target="_blank"><img width="438" alt="Screen Shot 2023-02-01 at 16 25 35" src="https://user-images.githubusercontent.com/762639/216142982-a10c4ce5-681e-48d4-9772-74ffb0afff39.png"></a>

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo
E-mail para contato em caso de não haver resposta: jose@latitud.com

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by teles** [comment]
Obrigado, @felipefialho 
A vaga ainda está em aberto, podemos manter essa issue aberta?

Abraço

**Comment by teles** [comment]
Oi, @victorbiasibetti. Descobri hoje que a vaga acabou de ser fechada, por isso o Page not found. Obrigado por avisar
Obrigado pelo interesse, pessoal.
Quem quiser me [adicionar no linkedin](https://www.linkedin.com/in/jotateles/) posso atualizar caso apareça algo novo ou ajudar de outras formas

Obrigado, @felipefialho
