### ISSUE TITLE
[Remoto] Fullstack Node/React Developer na Coodesh

### ISSUE THREAD

**Issue by isabelacsantiago** [frontendbr/vagas#7619]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/fullstack-nodereact-developer-133357698?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>Nickelpay</strong> está em busca de <strong><ins>Fullstack Developer</ins></strong> para compor seu time!</p>
<p>Somos uma fintech focada em fazer diferente. Trazer facilidade, conforto e confiança no processo de gestão de contas é nosso dever. A Nickelpay tem uma proposta forte que atrela Contas Digitais, Gestão Centralizada e BPO Financeiro.&nbsp;</p>

## Nickelpay: 
 <p>Somos uma fintech focada em fazer diferente. Trazer facilidade, conforto e confiança no processo de gestão de contas é nosso dever. A Nickelpay tem uma proposta forte que atrela Contas Digitais, Gestão Centralizada e BPO Financeiro.&nbsp;</p>
<p>Código próprio, em constante desenvolvimento, queremos pessoas que queiram fazer a diferença, pois temos liberdade para criar, desenvolver e implementar.</p><a href='https://coodesh.com/empresas/nickelpay'>Veja mais no site</a>

 ## Habilidades: 
 - React.js 
- Node.js 
- MySQL 
- CI/CD 
- MongoDB 
- Docker
## Local: 
 100% Remoto
## Requisitos: 
 - Conhecimento e experiência em FINTECH e ou Bancos Digitais; 
- Experiência com aplicação de Testes unitários, end-to-end e em APIs; 
- Conhecimento Suite AWS (EC2, RDS, S3, Cognito); 
- Ambiente de desenvolvimento, homologação e deploy com Docker; 
- Utilização do DockerHub; 
- CI/CD para homologação dos códigos gerados; 
- Automatização de tarefas relacionados a disponibilidade da aplicação relacionados a arquitetura; 
- Desenvolvimento com banco de dados MySQL; 
- Desenvolvimento com banco de dados MongoDB; 
- Experiência Sólida com React e Node.
## Diferenciais: 
 - Conhecimento/Experiência em PHP Laravel.
## Benefícios: 
 - 20 dias de recesso remunerado (após 12 meses); 
- 5 dias entre natal e ano novo; 
- Day off aniversário; 
- Ajuda de custo com cursos na área e de Inglês; 
- Incentivo à liderança e desenvolvimento de carreira.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack Node/React Developer na Nickelpay](https://coodesh.com/vagas/fullstack-nodereact-developer-133357698?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Full-Stack

**Comment by rafaelsilva81** [comment]
Enviado 🚀

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
