### ISSUE TITLE
[São Paulo] Front-End Developer na Netlolo Incubadora

### ISSUE THREAD

**Issue by flavioesio** [frontendbr/vagas#762]
## Descrição da vaga

Estamos contratando Front-End Developer (Pleno e Sênior) com uma boa pegada na visão de backend no regime PJ, para atuar em nossa empresa que é uma incubadora de produtos e serviços. A idéia é que esse colaborador atue em nossos produtos, de acordo com o skill técnico que possui.
Temos projetos desafiadores que nos permitem ter profissionais com todos os skills, porém no momento focamos em stack em Node.js, mas não é a bala de prata para todas as soluções, então procuramos pessoas que venham contribuir com a evolução de arquitetura e desenvolvimento do software.

## Local

Escritório, São Paulo - Avenida Paulista - Ao lado do metrô Consolação

## Benefícios

- Ambiente descontraído (com área de lazer e pessoas bem humoradas)
- Ambiente tranquilo (com área para relaxar, cuidados pessoais e sem pressão)
- Ambiente colaborativo (com área para pessoas compartilharem conhecimentos)
- Pessoas com paixão pelo aquilo fazem e respeitando o próximo
- Crescimento intelectual (Momento onde pessoas poderão fazer techtalks, dojos, palestras para o crescimento do próximo)
- entre outros com Happy hours para confraternização

## Requisitos comportamentais

- Seja muito mão na massa e pró-ativa, disposta inicialmente a realizar os primeiros atendimentos até que o time esteja maduro
- Seja uma pessoa tranquila, saiba trabalhar em equipe e demostre espirito de liderança de forma que as pessoas se sintam motivadas a segui-la e de forma que não tenha que demostrar poder ou pressão para conseguir seus resultados.
- Esteja disposta a aprender e ensinar
- Pessoas dispostas a vestir a camisa e acreditar no ideal da empresa
- Tenha uma paixão intensa por construir software e orientar seus times

## Requisitos técnicos

- Conhecimento de ferramentas de monitoramento (NewRelic, Monkey, Performance Co-Pilot, Nagios)
- Conhecimento de metodologia GitFlow
- Forte conhecimento de princípios SOLID de desenvolvimento orientado a objetos
- 5-7 anos de experiência com JavaScript, HTML, CSS e AJAX
- Forte compreensão e experiência com Node.js e o ecossistema NPM
- Experiência com frameworks de aplicações web modernas (Ex. Angular, Ember, React, ...)
- Compreensão sólida de AWS e métodos de continuous integration
- Entendimento e vivência de mais de 5 anos com bancos de dados relacionais e NoSQL
- Interesse ​​e capacidade de aprender outras linguagens de programação, conforme necessário.
- Inglês conversação, leitura e escrita intermediários

## Desejável

- Conhecimento de Frameworks( Express.js, Loopback.io )
- Entendimento de Blockchain e moedas criptografas
- Conhecimento de Lógica aplicada em arquitetura hexagonal e algorítimos
- Inglês conversação, leitura e escrita intermediários
- Conhecimento de API FB, FB Graph API, FB Insights API.
- Conhecimento avançado de google adwords, google adsense

## Contratação

PJ

## Como se candidatar

Por favor envie um email para flavio.esio@netlolo.com seu CV anexado - enviar no assunto: Front-End Developer

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
