### ISSUE TITLE
[Remoto] Front-end Developer na Devellop Labs

### ISSUE THREAD

**Issue by devellop-labs** [frontendbr/vagas#7620]
## Nossa empresa

A Devellop Labs é uma empresa que conecta os melhores profissionais na área de tecnologia as melhores empresas do mercado.

O candidato(a) fará parte de uma equipe multidisciplinar, onde todos colaboram com postura entusiasta, paixão por tecnologia e inovação, e ampla experiência em desenvolvimento web.

## Descrição da vaga

A Devellop Labs está procurando uma pessoa com perfil de nível júnior a pleno, que tenha experiência na área de desenvolvimento Front-End, com clientes e projetos. Essa experiência pode ser através de projetos frellas ou trabalho empresarial.

É importante que você goste de se comunicar e trabalhar em equipe, já que aqui temos um ambiente super colaborativo. Ao mesmo tempo, valorizamos que cada membro do time seja autônomo para gerir suas demandas.

## Requisitos

**Obrigatórios:**
- Conhecimento prático em HTML5 e CSS3 Responsivo
- Conhecimento avançado de JavaScript
- Desenvolvimento cross-plataforma e testes cross-browser
- Confortável trabalhando com o controle de versão (Git)
- Capacidade de trabalhar de forma independente com uma supervisão mínima
- Experiência de trabalho com APIs, ou integrar uma API de terceiros ou criar o seu próprio, quando necessário.
- Conhecer pré-processadores CSS como Less, Sass e Stylus;
- Conhecer os frameworks JS como React, React Native, ou VueJS;
- Atenção à detalhes na implementação de layouts;

**Desejáveis:**
- Experiência com sistemas de build (Bash, Grunt, Make, Ant)
- Conhecimento básico de pelo menos uma linguagem server side (Python, PHP, Node.js, Ruby, Go, etc)
- Experiência com UI e UX;

**Diferenciais:**
- Experiência com Magento M1 ou M2;

## Contratação

PJ a combinar

## Como se candidatar

Pelo link: [https://devellop.com.br/trabalhe-conosco](https://devellop.com.br/trabalhe-conosco)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by GabrielGuedess** [comment]
Enviado 🚀

**Comment by laugustofrontend** [comment]
Enviado

**Comment by marcosHenrique-developer** [comment]
ENVIADO !

**Comment by Helena-Rodrigues-Figueiredo** [comment]
Enviado!

**Comment by AlexMarquesAlves** [comment]
Enviado!

**Comment by sucodelarangela** [comment]
Enviado!

**Comment by AntonioMDSantos** [comment]
Enviado!

**Comment by claudiocassimiro** [comment]
Enviado

**Comment by WelllWas** [comment]
Enviado

**Comment by EnriqueSantos-dev** [comment]
Enviado

**Comment by artenlf** [comment]
Enviado

**Comment by Phregenes** [comment]
Bom dia! Muita task boa por ai?
Acadei de enviar meu CV para vocês!
Espero ansioso aqui para poder bater um papo e descobrir os desafios que viram pela frente.

**Comment by rafaelsilva81** [comment]
Enviado!

**Comment by RenanLucenaDeveloper** [comment]
Currículo enviado!

**Comment by RamosTailon** [comment]
Enviado!

**Comment by OliverioJunior** [comment]
Enviado

**Comment by Wesley-Fernandes** [comment]
Enviado.

**Comment by TiagoBarbosa88** [comment]
Enviado

**Comment by joaov1ct0r** [comment]
Enviado

**Comment by Rogjesus** [comment]
enviado

**Comment by GomidesTs** [comment]
Enviei um e-mail com meu CV para a vaga, juntamente a uma breve descrição das minhas habilidades e experiência em relação aos requisitos listados para a vaga.

**Comment by DarlanSantosCarvalho** [comment]
Enviado

**Comment by gabrielcaamargo** [comment]
Enviado 🚀

**Comment by manudeveloper82** [comment]
Enviado!🙌🏻🙌🏻🙌🏻

**Comment by Toineto** [comment]
enviado

**Comment by ViniciusDuarte17** [comment]
Enviado

**Comment by PedroPaivaDev** [comment]
Enviei o meu currículo. Aguardo um retorno. Obrigado.

**Comment by FeRiffo** [comment]
Enviado!

**Comment by Virkkunen** [comment]
Enviado

**Comment by rafaelsiqeira** [comment]
Enviado!

**Comment by rafaelsiqeira** [comment]
Enviado!

**Comment by Miicchhel** [comment]
Enviado.

**Comment by MatheusFilg** [comment]
Enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by EduuCarvalho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by gvao** [comment]
Prezados, acabei de enviar o currículo. 

Obrigado pela oportunidade!

**Comment by Rakodashi** [comment]
Enviado!

**Comment by AnaCosta29** [comment]
Currículo enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
