### ISSUE TITLE
[Remoto] Fullstack Developer na Coodesh

### ISSUE THREAD

**Issue by isabelacsantiago** [frontendbr/vagas#7621]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/fullstack-developer-172251633?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A<strong> Namu</strong> está em busca de <strong><ins>Fullstack Developer </ins></strong>para compor seu time.</p>
<p>Começamos nossa trajetória em 2013 com o Portal Namu e desde então nos tornamos uma referência na produção de conteúdo multimídia de bem-estar. Temos a yoga, o pilates e a gastronomia como as principais vertentes da empresa, e mais de 8 milhões de páginas visualizadas compartilhamos ensinamentos em aulas, entrevistas e palestras com as maiores referências nacionais e internacionais. O grande sucesso das aulas de yoga, pilates e gastronomia, com mais de 10 milhões de visualizações no YouTube nos inspirou a criar o Namu Cursos, a primeira plataforma brasileira de cursos online completamente focada em uma vida equilibrada.</p>
<p><strong>Responsabilidades e Atribuições:</strong></p>
<ul>
<li>Atuar em metodologias ágeis e organizar e manter o backlog;</li>
<li>Executar programação e integração de módulos e o banco de dados;</li>
<li>Realizar o planejamento de tarefas e entregas;</li>
<li>Gerenciar documentação dos códigos desenvolvidos;</li>
<li>Integração com APIs externas e internas;</li>
<li>Modelagem de dados e manutenção de DB;</li>
<li>Desenvolvimento e manutenção de aplicações/funcionalidades;</li>
<li>Efetivar a implantação dos aplicativos/sistemas.</li>
<li>Execução de testes manuais nos aplicativos e APIs;</li>
</ul>

## Namu: 
 <p>Começamos nossa trajetória em 2013 com o Portal Namu e desde então nos tornamos uma referência na produção de conteúdo multimídia de bem-estar. Temos a yoga, o pilates e a gastronomia como as principais vertentes da empresa, e mais de 8 milhões de páginas visualizadas compartilhamos ensinamentos em aulas, entrevistas e palestras com as maiores referências nacionais e internacionais. O grande sucesso das aulas de yoga, pilates e gastronomia, com mais de 10 milhões de visualizações no YouTube nos inspirou a criar o Namu Cursos, a primeira plataforma brasileira de cursos online completamente focada em uma vida equilibrada.</p>
<p>Em pouco mais de um ano construímos um portfólio que oferece a oportunidade e comodidade de praticar yoga onde e quando você quiser, com mais de 87 horas de aulas divididas entre 35 cursos. Os cursos são ministrados por professores de referência no Brasil que, em vários anos de estudos e experiência nas melhores escolas ou com os Gurus ao redor do mundo, se capacitaram para ensinar de forma didática e com preço acessível.</p><a href='https://coodesh.com/empresas/namu'>Veja mais no site</a>

 ## Habilidades: 
 - React.js 
- React Native 
- Typescript 
- Node.js 
- PHP 
- Laravel 
- Nest.JS 
- Wordpress 
- HTML 
- CSS
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência em desenvolvimento Frontend, Backend e Banco de Dados; 
- Forte conhecimento em Node.JS, Typescript e PHP; 
- Experiência com React, React Native; 
- Forte conhecimento em Git e BitBucket; 
- Experiência em desenvolvimento, testes e integração de APIs REST/RESTful; 
- Conhecimento Front End de Javascript, HTML, CSS; 
- Conhecimento de bancos de dados relacionais (MySQL).
## Diferenciais: 
 - Experiência com tecnologias AWS para gestão da infraestrutura (EC2, RDS, CloudWatch, S3, Lambda, ECR, Fargate, QuickSight, Global Accelerator, Route53, Code Pipeline); 
- Conhecimento em conteinerização (Docker); 
- Manter comunicação das atividades (Remote First); 
- Experiência em Laravel, Nest.js e Wordpress.

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack Developer na Namu](https://coodesh.com/vagas/fullstack-developer-172251633?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
