### ISSUE TITLE
[Remoto] Frontend Javascript Developer na Coodesh

### ISSUE THREAD

**Issue by isabelacsantiago** [frontendbr/vagas#7622]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-javascript-developer-172914646?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A<strong> Namu</strong> está em busca de <strong><ins>Frontend Developer </ins></strong>para compor seu time.</p>
<p>Começamos nossa trajetória em 2013 com o Portal Namu e desde então nos tornamos uma referência na produção de conteúdo multimídia de bem-estar. Temos a yoga, o pilates e a gastronomia como as principais vertentes da empresa, e mais de 8 milhões de páginas visualizadas compartilhamos ensinamentos em aulas, entrevistas e palestras com as maiores referências nacionais e internacionais. O grande sucesso das aulas de yoga, pilates e gastronomia, com mais de 10 milhões de visualizações no YouTube nos inspirou a criar o Namu Cursos, a primeira plataforma brasileira de cursos online completamente focada em uma vida equilibrada.</p>
<p><strong>Responsabilidades e Atribuições:</strong></p>
<ul>
<li>Atuar em metodologias ágeis e organizar e manter o backlog;</li>
<li>Criar soluções para Apps;</li>
<li>Implementar os protótipos desenvolvidos pelo UI/UX;</li>
<li>Criar elementos e componentes responsivos;</li>
<li>Implementar consultas na base de dados com utilização de API 's;</li>
<li>Desenvolver novas interfaces web responsivas;</li>
<li>Realizar o planejamento de tarefas e entregas;</li>
<li>Gerenciar documentação dos códigos desenvolvidos;</li>
<li>Integração com APIs externas e internas;</li>
<li>Desenvolvimento e manutenção de aplicações/funcionalidades;</li>
<li>Efetivar a implantação dos aplicativos.</li>
<li>Execução de testes manuais nos Apps;</li>
</ul>

## Namu: 
 <p>Começamos nossa trajetória em 2013 com o Portal Namu e desde então nos tornamos uma referência na produção de conteúdo multimídia de bem-estar. Temos a yoga, o pilates e a gastronomia como as principais vertentes da empresa, e mais de 8 milhões de páginas visualizadas compartilhamos ensinamentos em aulas, entrevistas e palestras com as maiores referências nacionais e internacionais. O grande sucesso das aulas de yoga, pilates e gastronomia, com mais de 10 milhões de visualizações no YouTube nos inspirou a criar o Namu Cursos, a primeira plataforma brasileira de cursos online completamente focada em uma vida equilibrada.</p>
<p>Em pouco mais de um ano construímos um portfólio que oferece a oportunidade e comodidade de praticar yoga onde e quando você quiser, com mais de 87 horas de aulas divididas entre 35 cursos. Os cursos são ministrados por professores de referência no Brasil que, em vários anos de estudos e experiência nas melhores escolas ou com os Gurus ao redor do mundo, se capacitaram para ensinar de forma didática e com preço acessível.</p><a href='https://coodesh.com/empresas/namu'>Veja mais no site</a>

 ## Habilidades: 
 - React.js 
- React Native 
- HTML 
- CSS 
- Typescript 
- Figma
## Local: 
 100% Remoto
## Requisitos: 
 - Desenvolvimento Mobile e Web; 
- Conhecimento de Javascript, Typescript, HTML, CSS; 
- Construção de aplicativos em React e  React Native 
- Forte conhecimento em Firebase e princípios de design para dispositivos móveis; 
- Grande atenção aos detalhes de UI/UX e interações (Figma); 
- Experiência em integração de APIs REST; 
- Experiência com bibliotecas e APIs de terceiros; 
- Realizar o desenvolvimento do SDLC completo;
## Diferenciais: 
 - Experiência anterior com tecnologias AWS 
- Conhecimento em design de APIs e Node.js

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Javascript Developer na Namu](https://coodesh.com/vagas/frontend-javascript-developer-172914646?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by sucodelarangela** [comment]
Enviado!

**Comment by GabrielGuedess** [comment]
Enviado 🚀

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
