### ISSUE TITLE
[Remote] Mid-level Front-end Developer na ezyCollect

### ISSUE THREAD

**Issue by ezykaioazevedo** [frontendbr/vagas#7623]
## Nossa empresa

ezyCollect is an Australian-founded B2B start-up/scale-up on a mission to eliminate late payments! We put smart technology in the hands of ambitious businesses, so they have the cash and confidence to manifest their dreams. Our invoice-to-payments subscription software complements accounting/ERP software (MYOB, Xero, NetSuite, SAP etc.) to automate the process of getting paid. We are expanding our products and services as well as our team! We are a team of over 85 across Australia, Brazil, and the Philippines and are looking to hire those with curiosity and grit who get excited about having a big impact on a growing company. We have some exciting plans for the future, with an IPO and international expansion expected in early 2023.

## Descrição da vaga

As a Mid-level Frontend Engineer at ezyCollect, you would build products and services that are inspiring, meaningful, and have a direct impact on business outcomes.

Working within one of our delivery teams, you’ll build and improve our products and enjoy seeing how they change the lives of their users. Our customers love our product and we always keep them in our mind when making decisions.

## Local

Remote

## Requisitos

**Must Have**
4+ years of software development or equivalent experience.
2+ Professional experience with React JS or another modern JavaScript web framework (Vue, Angular, Ember, etc)
Self-motivated and self-managed, with great organizational skills.
Strong competency across
Microservices
Rest APIs
Writing automated tests (eg. Jest, Karma, Jasmine, Mocha, AVA, tape)
Using Git in a professional/workplace environment
Core web and browser concepts (eg. how the browser parses and constructs a web page)
Understanding of semantic HTML, CSS, and core JavaScript concepts.
Fluent/Native English
**Desirable**
Ideally have relevant experience in a fast-paced FinTech or SaaS business.
Experience working with a remote team
Experience working with a global or otherwise multicultural team
Traits
A knack for creating well-crafted, readable, maintainable code.
Ability and eagerness to share your ideas while being open to those of others.
Comfortable managing and driving multiple competing priorities at any given time.
Ability to communicate effectively.
You are analytical and data-driven in your decision-making.

## Benefícios

- Férias: 20 dias úteis
- Doença: 10 dias úteis
- Convênio médico: Reembolso até R$637,50
- Budget para cursos
- Employee Share Options

## Contratação

PJ

## Como se candidatar

[Pelo Lever](https://jobs.lever.co/ezycollect/6a7cfb0f-bc84-4164-8898-43bc7b14720f?lever-via=rTInuwuETX)
[Para dúvidas me manda msg no Linkedin](https://www.linkedin.com/in/kaioazevedo/)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by sucodelarangela** [comment]
Application submitted
