### ISSUE TITLE
[Curitiba / PR] Front-End Developer Pleno na Servipar

### ISSUE THREAD

**Issue by grupoallcross** [frontendbr/vagas#7624]
## Nossa empresa

Na Servipar oferecemos softwares personalizados para gestão de clientes.

## Descrição da vaga

Estamos desenvolvendo um software para gestão de clientes, que consome uma API proprietária. Faixa de 8k a 10k

## Local

Escritório: Paraná, Curitiba, Centro.

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com React - TypeScript
- Consumo de API
- Autenticação JWT
- CSS
- Responsividade
- Design Patterns
- Renderização Server Side
- Já ter atuado em outros projetos

**Desejáveis:**
- Conhecimento em Orientação a Objetos
- Algum framework CSS

## Contratação

PJ 8k a 10k

## Como se candidatar

Duas vagas disponíveis. Por favor envie um email para algeu16@gmail.com com seu CV anexado - enviar no assunto: Vaga Front End Pleno. Após análise do CV, caso adequado, será encaminhado um teste técnico

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: algeu16@gmail.com

#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by marcos-jesus** [comment]
@rafaelfgyn é meio bizarro mesmo.

**Comment by pdrch** [comment]
5k para Pleno/Senior kkkkjj Isso não paga nem um bom JR hoje em dia.

**Comment by grupoallcross** [comment]
Faixa salarial corrigida.
