### ISSUE TITLE
[São Paulo | Remoto] Pessoa Desenvolvedora de Software Front End @ {Voxy}

### ISSUE THREAD

**Issue by iswarya-voxy** [frontendbr/vagas#7628]
## Descrição da vaga
Nós acreditamos que aprender uma língua deveria ser divertido, gratificante e uma porta de entrada para as melhores experiências que a vida tem para oferecer. **Se você concorda conosco, nós gostaríamos de conversar.**
Se você é uma pessoa engenheira de software procurando usar seu talento para o ensino de inglês ao mundo, então preste atenção na Voxy. O time de engenharia da Voxy está mudando a maneira como milhões de pessoas ao redor do mundo aprendem inglês usando ciência sólida combinada com tecnologia inovadora (e patenteada!). Estamos implementando atividades de aprendizado impulsionadas por pesquisas científicas juntamente com aulas ao vivo usando algoritmos avançados para construir uma experiência personalizada com "conteúdo autêntico" a partir de fontes  que você conhece (Bloomberg, AP, Financial Times e muitos outros). O objetivo da Voxy é se tornar a primeira opção no mercado de ensino de Inglês que é avaliado em US$80 bilhões. Dessa forma, o nosso time de engenharia é crucial para alcançar esse objetivo.
**A missão da Voxy é romper as barreiras linguísticas no mundo todo para permitir que as pessoas conquistem seus objetivos.**

## Local
São Paulo | Remoto

## Benefícios
**Trabalhando aqui, você terá:**
- Salário competitivo e opção de compra de ações;
- Excelentes benefícios: plano de saúde, reembolso de fatura de celular e wifi, orçamento para gastos com home office e bem-estar, eventos de equipe;
- Política de trabalho remoto;
- Bolsa de desenvolvimento profissional;
- Aulas de inglês na plataforma da Voxy;
- Experiência de trabalho com uma equipe internacional incrível, composta por indivíduos brilhantes, criativos, talentosos e apaixonados, baseados nos EUA e em todo o mundo.

## Requisitos
**O que você vai fazer:**
- Você será responsável pela reestruturação da nossa Front End Application para torná-la mais reativa, acessível e responsiva.
- Construir um framework inovador de jogos/atividades para engajar os alunos de uma maneira cientificamente validada que aprimore a aprendizagem.
- Criar códigos bem estruturados que possam ser testados e implantados, incluindo A/B testing de novos recursos para eficácia e usabilidade.
- Nós somos globais! Por isso, nossa interface também precisa ser global. O front end é internacionalizado para estudantes com diferentes culturas, pontos de vista e métodos de aprendizagem de idiomas.
- Não ter medo de enfrentar um desafio ocasional de back end. 
- Colaborar com pessoas responsáveis pelo design de produto,pessoas engenheiras de software e gerentes de produto para construir códigos bem estruturados, testáveis e que possam ser feitos deploy sem downtime. 
- Participar ativamente de code reviews, discussões e decisões de tecnologia e arquitetura de front end.
- Construir sistemas e componentes de front end de forma eficiente e reutilizável que permita aplicações complexas de front end.
- Compartilhar conhecimentos, difundir as melhores práticas e colaborar com pessoas desenvolvedoras incríveis.

**O que nós estamos procurando:**
- 3+ de experiência construindo serviços front end para a produção de aplicação web.
- Conhecimento das tecnologias e práticas de front end mais recentes, como: Vue, React e Angular.
- Curiosidade e conhecimento sobre tecnologias e padrões de arquitetura de engenharia de software em toda a stack com foco em front end (por exemplo: CSS, javascript, html5, etc.).
- Conhecimento e experiência na criação de testes unitários de acordo com as melhores práticas de desenho, implementação e manutenção de testes. 
- Experiência de trabalho com REST APIs para criar Single Page Application em larga escala.
- Pragmatismo no entendimento de quando construir uma solução que escala para 1 milhão de usuários ou que funciona para 100 usuários.

**O que seria ótimo ter:**
- Vue.js é o framework principal para o desenvolvimento de aplicações front end na Voxy e algumas aplicações legadas com outros frameworks.
- Experiência em Python seria ótima para ler e entender códigos de back end.
- Conhecimento sobre uso de serviços da AWS também seria legal, mas sem problemas se você não possuir familiaridade.
- Graduação no ensino superior ou pós em Ciência da Computação, Engenharias, ou alguma formação equivalente.

## Contratação
CLT

## Nossa empresa
Aqui na Voxy somos líderes em educação de línguas

**Aqui usamos:**
- Vue.js
- Python
- AWS

## Como se candidatar
[Aplicar através do link da Empresa](https://jobs.lever.co/voxy/3deca549-2f43-428d-a2ec-4a642f7ca8fa?lever-origin=applied&lever-source%5B%5D=GitHub)

#### Alocação
- Remoto

#### Experiência
- Pleno
- Sênior

#### Regime
- CLT

**Comment by PandaZIM** [comment]
Candidatei!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by iswarya-voxy** [comment]
Esta posição está preenchida. Obrigada por verificar.
