### ISSUE TITLE
[Remoto] Frontend React Developer na Coodesh

### ISSUE THREAD

**Issue by isabelacsantiago** [frontendbr/vagas#7629]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/desenvolvedor-frontend-react-plsr-215948162?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p style="text-align:justify;">&nbsp;A <strong>Mutual </strong>está buscando <strong>Frontend React Developer</strong> para compor o seu time!</p>
<p style="text-align:justify;"></p>
<p style="text-align:justify;"><strong><ins>Sobre a Mutual:</ins></strong></p>
<p style="text-align:justify;">Somos uma fintech voltada ao mercado de crédito. Queremos democratizar o acesso ao crédito, provendo plataformas e sistemas que permitem pessoas ou empresas solicitarem crédito de forma fácil e rápida. Além de prover plataformas para que pessoas ou empresas possam realizar investimentos em pedidos de crédito dentro da plataforma.</p>
<p style="text-align:justify;">Dentro da Mutual, atuará dentro do projeto "Scora" (https://www.scora.com.br/). Aproveitando as vantagens do Open Banking, te ajudamos a renegociar os custos das suas dívidas sem que você vá de banco em banco. O Scora encontra para você a melhor solução de crédito com garantia do mercado, com um parcelamento mais barato e prazo de pagamento flexível.</p>
<p style="text-align:justify;"></p>
<p style="text-align:justify;"><strong><ins>Sobre a posição:</ins></strong></p>
<p style="text-align:justify;">Como engenheiro de software frontend você terá a oportunidade de trabalhar com um frontend moderno usando tecnologias como React, React Native, Next.JS, Redux, Typescript. Inserido em uma equipe ágil, comprometida com qualidade nas entregas, e sempre buscando excelência técnica.</p>
<p style="text-align:justify;">Trabalhamos em utilizando metodologias ágeis dentro das Squads, e dentro dessas squads terá contato com equipes interdiciplinares: Backend, Frontend, Devops, Product Design e Product Owner.</p>

## Mutual: 
 <p>Estamos entre as principais empresas de tecnologia do mercado financeiro nacional, desenvolvendo soluções que democratizam o acesso ao crédito e oferecem modelos de investimento nos setores mais promissores da economia brasileira.</p>
<p>Somos evolução do crédito digital no Brasil, permitindo que mais pessoas melhorem suas vidas financeiras de forma simples e justa. Aqui a gente entende e resolve o problema financeiro das pessoas de forma rápida e descomplicada. Ajudamos a tornar sonhos e objetivos financeiros em ações reais.</p><a href='https://coodesh.com/empresas/mutual'>Veja mais no site</a>

 ## Habilidades: 
 - React.js 
- React Hooks 
- Typescript 
- React Native 
- Next.js 
- Cypress 
- HTML 
- CSS 
- Redux
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência profissional em React ou React Native; 
- HTML / CSS; 
- Experiência sólida com Typescript; 
-  Redux; 
- Noção de performance (code splitting, cacheamento, lazy loading); 
- React Hooks; 
- Cypress.
## Diferenciais: 
 - Já ter trabalhado com React Query, Storybook; 
- Conhecimentos em Node.
## Benefícios: 
 - Trabalho 100% Remoto; 
- Férias remuneradas; 
- Plano de saúde e odontológico (cobertura nacional); 
- Beneficio Flexível (Alimentação, refeição e home office); 
- Flexibilidade de horário; 
- Seguro de Vida; 
- Gympass.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend React Developer na Mutual](https://coodesh.com/vagas/desenvolvedor-frontend-react-plsr-215948162?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
