### ISSUE TITLE
[São Paulo] Front-End Developer na RecrutaSimples

### ISSUE THREAD

**Issue by andre0799** [frontendbr/vagas#763]
## Descrição da vaga

Se você é apaixonado por desenvolvimento (e por JavaScript rs), se mantém sempre atualizado e quer ter impacto direto em um software que alcança milhões de usuários, essa é a oportunidade certa para você!

No Recruta Simples, quando um cliente anuncia uma vaga de emprego, ela é divulgada (automaticamente) em +60 sites de emprego. 
Para isso, estamos desenvolvendo os mais diversos tipos de integrações e um algoritmo que aprende a otimizar a publicação de vagas e a captação dos candidatos.

Somos aficionados em dar a melhor experiência para os nossos clientes. Através  de vendas consultivas, suporte dedicado, interfaces simples e algoritmos eficientes!

Buscamos um/uma Front-End Developer com sede de aprendizado e apaixonado pelo que faz.

Além de trabalhar com tecnologia de ponta e nos ajudar a construir uma plataforma ainda mais robusta, você estará em contato com o que há de melhor no ecossistema de startups dentro do espaço do CUBO (cubo.network/).

O que te damos em troca?

Além de um salário, você terá:
- Horários flexíveis
- Ambiente de trabalho divertido e inspirador no CUBO
- Um time que preza pelo respeito e companheirismo!
- Crescimento acelerado
- Comemorações de conquistas com bebidas importadas (rs)
- Uma empresa aberta a sugestões, críticas, melhorias e que respeita suas decisões e experimentos
- Oportunidade para ser sócio da empresa!
- Possibilidade de trabalhar parte da semana de casa!

## Local

Escritório (Remoto parcial), São Paulo - Vila Olímpia

## Requisitos

**Obrigatórios:**
Estamos em busca de um dev JÚNIOR ou PLENO, com os seguintes domínios
mínimos:

- React
- Redux
- Integração com RESTful APIs
- Webpack
- Git
- Boa noção de UI/UX
- SEO

**Diferenciais:**
- Ser Full-stack

## Contratação

PJ de R$3000,00 a R$5000,00

## Nossa empresa

Recruta Simples é uma Startup que simplifica o processo de recrutamento ao permitir que empresas postem uma vaga em +60 sites de emprego com 1 click, e gerenciem todos os candidatos através de uma interface simples.

Ao proporcionar um local central para divulgação e triagem, o Recruta Simples ajuda empregadores a tomarem rapidamente as melhores decisões com um custo que cabe no orçamento.

## Como se candidatar

[https://www.recrutasimples.com.br/vaga/-L2v3Ps5uB5szaVCDQ9Q](Por favor se candidate através do link: https://www.recrutasimples.com.br/vaga/-L2v3Ps5uB5szaVCDQ9Q?referrer=githubFrontEnd)

**Comment by vinyguedess** [comment]
Como funciona esse "remoto parcial" ?

**Comment by rubenmarcus** [comment]
Como se avalia essa faixa entre 3 a 5?

**Comment by brunobc182** [comment]
@vinyguedess Creio que, o Remoto Parcial é quanto se trabalha alguns da semana em casa e os outros na empresa.
