### ISSUE TITLE
[Remoto] FullStack.NET (React) Developer na ITeam

### ISSUE THREAD

**Issue by ITeam-oportunidades** [frontendbr/vagas#7630]
> Vaga Remota 

## ITeam

Há mais de 15 anos presente no mercado, a ITeam oferece o comprometimento com o cliente.
Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 
Com uma equipe multidisciplinar, a ITeam proporciona uma área de Serviços Gerenciáveis como Projetos SAP, Fábrica de Software, Fábrica de Soluções e Sustentação. Neste modelo proporcionamos Sustentação, Melhorias e Desenvolvimentos de aplicação de forma integrada.

## Local

100% Remoto

## Requisitos

**Obrigatórios:**

Experiência em desenvolvimentos com .Net C#, Net Core e FrontEnd (React).
Necessário conhecimento em SQL.
Testes unitários.

## Atividades

Irá atuar no desenvolvimento e correção de funcionalidades de uma aplicação web .NET C#, Net Core e FrontEnd (React).
Necessário conhecimento em SQL.

## Contratação

CLT + benefícios 
2 meses, com possibilidade de efetivação pelo cliente.

## Como se candidatar

Por favor, envie um e-mail para viviane.pereira@iteam.inf.br com seu CV anexado com pretensão salarial CLT - enviar no assunto: Vaga GITHub - .NET/React CLT

## Labels
Remoto
.NET Core
React

## Regime
PJ ou a combinar

## Nível
Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
