### ISSUE TITLE
[Remoto] Front-End Developer Flutter na Software Bistrô

### ISSUE THREAD

**Issue by giacomoquinalia** [frontendbr/vagas#7631]
## Software Bistrô

A Software Bistrô é uma solução totalmente focada no segmento da alimentação. [Software Bistrô](https://softwarebistro.com.br/)

## Descrição da vaga

Nosso time utiliza a stack Javascript, com Node.js, React e React Native. Recebemos um aporte e estamos aumentando a equipe. Precisamos de um desenvolvedor **Flutter** que possua experiência ou já tenha feito uma entrega de software com essa tecnologia.

## Local

100% Remoto

## Requisitos

**Obrigatórios:**
- Flutter

**Desejáveis:**
- React
- TypeScript

## Contratação

PJ
- Entre R$30,00 e R$40,00 a hora | R$4.800 a R$6.400 ao mês
- Abertos à negociação para valores maiores

Tempo integral com horário flexível, dias úteis da semana.

## Como se candidatar

Por favor envie um email para desenvolvimento@softwarebistro.com.br com seu CV anexado e se possível, sua disponibilidade de horários para uma conversa - enviar no assunto: Vaga Flutter Front-End.
Dentro de 1 dia entraremos em contato.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Júnior

**Comment by DarlanSantosCarvalho** [comment]
Enviei
