### ISSUE TITLE
[Remoto] Front-end Developer na Yungas

### ISSUE THREAD

**Issue by ghedin** [frontendbr/vagas#7633]
## Nossa empresa

A Yungas é uma empresa de tecnologia líder em transformação digital no mercado de franquias brasileiro. Estamos em busca de pessoas com vontade de crescer e de fazer parte desse time referência!

- Somos protagonistas, temos iniciativa e agimos de forma construtiva, nos adaptando aos diferentes cenários e entregando grandes resultados. Vivemos a partir de uma cultura de experimentação e aprendizado acelerado.

- Nos preocupamos muito com a qualidade e em gerar valor e retorno aos nossos clientes.

- Trabalhamos em time para atingir nossos objetivos, de forma solícita e colaborativa.

- Gostamos de nos divertir: um clima de descontração e integração faz parte do nosso dia-a-dia.

Se você se identificou com os pontos acima e não quer ser só mais um na organização, na Yungas você encontrará um lugar onde poderá fazer a diferença!

## Descrição da vaga

Estamos em busca de novos engenheiros de software (+6 anos de experiência) que possam agregar o nosso time com sua experiência em programação web. Implementação de melhorias e novas funcionalidades no front-end, além de evoluir a arquitetura e qualidade de código.

Você irá trabalhar no dia-a-dia principalmente com Javascript (Svelte) no front-end.

## Local

Remoto ou no SC401 Square Corporate em Florianópolis-SC.

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com React ou Angular

**Desejáveis:**
- conhecimentos em Docker
- conhecimentos em Python

**Diferenciais:**
- Horário Flexível
- Oportunidade de Crescimento

## Contratação

CLT ou PJ a combinar

## Como se candidatar

Por favor envie seu CV através [deste formulário](https://jobs.quickin.io/yungas/jobs/63e2924c7b52d6001352a483?src=Github).

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior

**Comment by diogoneves07** [comment]
Porquê essa vaga não tem a descrição?

**Comment by srsouzaj** [comment]
vaga congelada

**Comment by robinndev** [comment]
Está fora do ar a página de form.

**Comment by HenriqueMotton** [comment]
Já encontraram um pleno front? O Form esta fora do ar, mas meu linkedin é este, caso a vaga ainda esteja aberta: https://www.linkedin.com/in/park-henri/

**Comment by ghedin** [comment]
Olá pessoal. Vaga encerrada- mas deveremos abrir mais nos próximos meses. Todos que se candidataram já estão no radar. Obrigado.
