### ISSUE TITLE
[Remoto] Frontend Developer na Coodesh

### ISSUE THREAD

**Issue by isabelacsantiago** [frontendbr/vagas#7634]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/frontend-developer-192451189?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>5i </strong>busca <strong>Frontend Developer</strong> para desenvolvimento de seu App!</p>
<p>A 5i é uma empresa dinâmica e especializada, que conta com a expertise de diversos profissionais, com vasta experiência no setor. Nosso foco de atuação engloba todo o mercado de refrigeração, desde a venda e locação de equipamentos de ar-condicionado à prestação de serviços de Manutenção, PMOC e Instalação.</p>
<p>Nosso grande diferencial é a excelência e eficiência na prestação de serviços, resultado de uma equipe de técnicos especializados e com longa experiência em fábricas do segmento.</p>
<p>Nosso foco é estar em constante desenvolvimento, para conferir agilidade, prover confiança e, acima de tudo, garantir a aprovação e satisfação de nossos clientes, fornecedores e parceiros.</p>

## 5i : 
 <p>A 5i é uma empresa dinâmica e especializada, que conta com a expertise de diversos profissionais, com vasta experiência no setor. Nosso foco de atuação engloba todo o mercado de refrigeração, desde a venda e locação de equipamentos de ar-condicionado à prestação de serviços de Manutenção, PMOC e Instalação.</p>
<p>Nosso grande diferencial é a excelência e eficiência na prestação de serviços, resultado de uma equipe de técnicos especializados e com longa experiência em fábricas do segmento.</p><a href='https://coodesh.com/empresas/5i'>Veja mais no site</a>

 ## Habilidades: 
 - React.js 
- CSS 
- HTML 
- React Native 
- Flutter
## Local: 
 100% Remoto
## Requisitos: 
 - Conhecimento com integrações de APIs (RESTFul); 
- Proativo, com ótimo raciocínio lógico e alto nível de comprometimento; 
- Apaixonado por tecnologia, querendo aprender coisas novas todos os dias; 
- Conhecimento em HTML, CSS, Javascript e React 
- Conhecimento no desenvolvimento mobile em React Native ou Flutter

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Developer na 5i ](https://coodesh.com/vagas/frontend-developer-192451189?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by sucodelarangela** [comment]
Candidadura efetuada!

**Comment by allbertuu** [comment]
Vaga arquivada @felipefialho

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
