### ISSUE TITLE
[REMOTE] React Developer na NT Consult 

### ISSUE THREAD

**Issue by apaulacosta** [frontendbr/vagas#7637]
## Nossa empresa

International project with a company based in the US that develops software and hardware platforms for the management of connected devices. Through an applied combination of artificial intelligence, advanced analytics, and sophisticated automation, their platforms help manage the world of devices for all supply chain stakeholders by injecting intelligence and transparency throughout the entire device lifecycle: from design, development, and certification to forward and reverse logistics. By balancing device velocity, quality, and precision across all supply chain processes, their platforms optimize device experiences and value.

This is a remote project where you will work from home.

## Descrição da vaga

In this full-stack web app position, you will help lead the development of our next-generation customer experience portal and be responsible for creating a configurable web portal that will be deployed to multiple clients. You will develop our front-end customer experience including the administration configuration portal and UX tracking, as well as the back-end integration with our platforms and third-party systems. Besides regular individual contributions, our Senior Software Engineers are expected to be deep technical experts in our tech stack and have a breadth of knowledge & experience on frontend technology trends in the industry. In addition to significant experience developing products and platforms from concept to production, we seek highly motivated individuals with high standards of quality and integrity and a flexible, entrepreneurial spirit. Apply today if this sounds like you!

## Local

Remoto

## Requisitos

·         BA/BS and/or MS in Computer Science, Engineering, or Information Technology, Relevant experience may substitute degrees
·         8+ years of progressive software engineering experience with a proven track record of successful productivity
·         3+ years of experience leading small development teams of three to five
·         5+ years of experience with and proficient in HTML, CSS, and JavaScript (React)
·         2+ years of experience in Python
·         Familiarity with software development methodology and release processes
·         Ability to document requirements and specifications
·         Ability to work in a cross-functional distributed team environment
·         Excellent problem-solving skills

Nice to have knowledge

·         UI/UX design experience, E-Commerce is a plus.
·         SQL (Postgres) is a plus.

## Contratação

PJ a combinar 

##Budget

Até 6K USD

## Como se candidatar

Por favor envie um email para ANA.RUSSO@NTCONSULT.COM.BR com seu CV anexado - enviar no assunto: Vaga React

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
