### ISSUE TITLE
[Remoto] Javascript Software Engineer na Coodesh

### ISSUE THREAD

**Issue by blankapf** [frontendbr/vagas#7638]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/senior-javascript-software-engineer-190903564?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Intellective is an Elite ServiceNow partner specializing in developing applications that extend the ServiceNow platform.  Additionally, we help customers implement solutions using our apps centered around the Employee Experience space. Our clients span multi-national companies that deploy innovative solutions to manage their employee experiences.</p>
<p>We are experiencing great demand for our products and services.  As part of our growth strategy, we are looking for a Senior Software Engineer to extend the team capabilities and evolve our product set and implement innovative solutions for various clients.</p>

## Intellective: 
 <p>Intellective is a 100% ServiceNow focused development studio. We help our clients make the most of your ServiceNow investment!  We develop tools that provide new capabilities for the ServiceNow platform and specialize in Employee Experience strategy and execution.</p>
<p>For more information visit <a href="https://intellective.co" target="_blank">https://intellective.co</a>&nbsp;</p><a href='https://coodesh.com/empresas/intellective'>Veja mais no site</a>

 ## Habilidades: 
 - Javascript 
- Typescript 
- Angular.js 
- Backbone.js
## Local: 
 100% Remoto
## Requisitos: 
 - Basic Working knowledge of English; 
- Advanced experience in Javascript; 
- State flow management experience; 
- Frontend development using HTML5, Tailwind, and SASS framework.
## Diferenciais: 
 - Fluent in English; 
- ServiceNow Knowledge CSA or Developer certification; 
- Experience coding with Typescript; 
- Experience with AngularJS, NodeJS, React.

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Javascript Software Engineer na Intellective](https://coodesh.com/vagas/senior-javascript-software-engineer-190903564?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
