### ISSUE TITLE
[ Remoto / Jacareí - SP ] Front-end Developer na Boostech

### ISSUE THREAD

**Issue by bolodissenoura** [frontendbr/vagas#7643]
## Nossa empresa

 Atuante no mercado nacional de aplicações de software empresarial para o segmento logístico, a Boostech é uma empresa focada em implementar soluções inteligentes e flexíveis para gestão de armazenagem e transporte.

## Descrição da vaga

 Software House com VUE3 

## Local

 Remoto ou Escritório, [SP], [JACAREI / SAO JOSE DOS CAMPOS]
 - Se for Júnior : Desejavel que tenha disponibilidade de ir até o escritorio em Jacareí - SP e São José dos Campos - SP
-  Se for Pleno : 100% REMOTO

## Requisitos

**Obrigatórios:**
- Experiencia com VUE3
- Experiencia com HTML, CSS ,JS

**Desejáveis:**
- conhecimentos Laravel / Symfony
- conhecimentos em PHP

**Diferenciais:**
- conhecimentos em MySql / Postgresql

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para Marcelo.takahama@boostech.com.br com seu CV anexado - enviar no assunto: Vaga Vue3

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: Marcelo.takahama@boostech.com.br 

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Júnior : Desejavel que tenha disponibilidade de ir até o escritorio em Jacareí - SP e São José dos Campos - SP
- Pleno : 100% REMOTO

**Comment by devRukasu** [comment]
Enviei

**Comment by anna-braga-jesus** [comment]
Enviei

**Comment by rayanmarcus** [comment]
Enviado! ✅

**Comment by JaoConquista** [comment]
Enviado ✔️

**Comment by Gabriel5748** [comment]
É remoto ou presencial ? Estou em dúvida

**Comment by sucodelarangela** [comment]
100% remoto, está na descrição da vaga

**Comment by Rogjesus** [comment]
enviado

**Comment by bolodissenoura** [comment]
Opa, fala ae turma ! 
 
Eu só divulguei a vaga pra uma empresa amiga minha e nao sou tech recruiter nem nada, mas me senti na obrigação de dar um parecer pra quem se candidatou: 

Estão analisando o cv de cada um, alguns ja receberam respostas e outros ainda nao. Os que mais se encaixarem com a vaga vao pra uma entrevista .  E espero que mandem um feedback pra vcs por e-mail. 

Mas se nao foi chamado / foi ignorado por e-mail, nao desista e continue aplicando para outras vagas. 
E to aqui se precisar de alguma ajuda, seja tecnica ou pra arrumar um trampo !

Essa mensagem foi mais generica, mas de verdade, o que precisar contem cmg, minha dm do twitter ta aberta ! Boa sorte
