### ISSUE TITLE
[Remoto] Front-end Developer na nav9

### ISSUE THREAD

**Issue by RenataRamiress** [frontendbr/vagas#7648]
> Vaga Remota

## Empresa nav9

A nav9 preza por um ambiente com grande autonomia para o time. Trabalhamos em squads multidisciplinares, seguindo os princípios de desenvolvimento de software ágil, buscando realizar pequenas entregas incrementais que geram valor de forma constantes nos produtos que desenvolvemos.

Buscamos um Tech Lead com experiência em construção de produtos digitais utilizando metodologias ágeis para atuar em um produto inovador dentro do mercado financeiro. Pela complexidade do produto e tamanho do desafio técnico, precisamos de alguém com no mínimo 5 anos de experiência comprovada no desenvolvimento de produtos digitais.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência no mínimo de 5 anos na área de desenvolvimento web: frontend e/ou backend;
- Experiência trabalhando em squads que seguem os princípios do desenvolvimento ágil de software;
- Conhecimento avançado em javascript;
- Conhecimento em NodeJS e React;
- Bancos de dados SQL/NoSQL;
- Conhecimento em ambientes em nuvem (AWS);
- Arquiteturas baseadas em APIs, microsserviços e micro frontends;
- Processamento assíncrono e mensageria (RabbitMQ, Kafka, Google PubSub);
- Containers com Docker e Kubernetes;
- Controle de versão com Git (Gitlab, Github, Gitflow).

**Diferenciais:**

- Atuação em produtos do mercado financeiro;
- Conhecimento solido em desenvolvimento back-end.

## Benefícios

- Assistências médica e odontológica;
- Auxilio psicológico;
- Auxilio atividade física;
- Vale Refeição e/ou Vale Alimentação;
- Auxilio Educação (acesso a plataformas de cursos);
- Horário flexível e home office.

**Diferenciais:**
- Hierarquia horizontal; 
- Plano de carreira. 

## Contratação
CLT + beneficios. 

## Como se candidatar

Por favor entrar nesse site https://nave-team.gupy.io/jobs/4235037 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até sete dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by RenanBrenio** [comment]
A vaga foi encerrada?

**Comment by victorbiasibetti** [comment]
@RenanBrenio no gupy consta como encerrada

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
