### ISSUE TITLE
[Remoto e Internacional] Full-stack Developer (React/Node) - Lemon.io

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#7649]
**We’re Lemon.io — a marketplace where we match you with hand-picked startups from the US and Europe.** 

## Why work with us:

- We’ll find you a team that respects you. No time-trackers or any micromanagement stuff
- Our engineers earn $5k - $9k / month. We’ve already paid out over $10M.
- Choose your schedule. We have both full- and part-time projects.
- No project managers in the middle — only direct communications with clients, most of whom have a technical background
- Our customer success team provides life support to help you resolve anything.
- You don’t have to look for clients and or negotiate anymore: just do what you do best and leave us the rest.

## Requisitos

- 5+ years of software development experience
- Strong knowledge of JavaScript (Core, DOM APIs)
- 3+ years of experience with Node.js and React.js
- 2+ years of experience with Typescript
- Understanding of and practical experience with AWS
- Understanding of and practical experience with SOLID principles and GOF patterns
- Understanding of CI principles
- Experience with React Native and Next would be a plus

## Salário

U$ 5.000 - U$ 9.000

**Apply today, and our team will get back to you within 2 business days!** 

## Nossa empresa

We’re Lemon.io — a marketplace where we match you with hand-picked startups from the US and Europe. 

## Como se candidatar

Click [here](http://bit.ly/3xUOVXw) to see full description and apply

# Recruitment process:

- First step: VideoAsk (about 10 minutes)
- Second step: 30 minutes Screening call with our Recruiters
- Third step: Technical Interview with our Developers
- Feedback
- Magic Box (we are looking for best project for you) 

Obs: esta vaga está sendo anunciada pela Remotar em nome da Lemon.io, cliente de nossa empresa

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by pdrch** [comment]
@tatidirienzo Speaking fluent English is a mandatory requirement. Correct?

**Comment by victorbiasibetti** [comment]
@tatidirienzo 
<img width="936" alt="image" src="https://user-images.githubusercontent.com/25385783/222131238-0a1fb14a-37d0-41fb-b0ac-cf7e62ac73e2.png">

**Comment by tatidirienzo** [comment]
> @tatidirienzo Speaking fluent English is a mandatory requirement. Correct?

Yes!

**Comment by tatidirienzo** [comment]
@pdrch yes

@victorbiasibetti isso ocorre em que momento?

**Comment by victorbiasibetti** [comment]
@tatidirienzo depois que preenche todo o cadastro e loga na conta

**Comment by tatidirienzo** [comment]
@victorbiasibetti estou entrando em contato com a responsável da vaga para entender melhor o ocorrido

**Comment by tatidirienzo** [comment]
@victorbiasibetti pode me mandar seu email? Se não quiser fazer isso por aqui, pode ser para o email tatiana@remotar.com.br

**Comment by eber404** [comment]
@tatidirienzo a vaga ainda está aberta?
![image](https://user-images.githubusercontent.com/7109795/222511735-51924cea-4d13-4517-9f34-0c4671423d67.png

**Comment by devRukasu** [comment]
Tem vaga pra Jr?

**Comment by tatidirienzo** [comment]
@eber404 pelo que apurei com a empresa, esta mensagem é passada para quem não atende todos os requisitos da vaga, ok?

@devRukasu infelizmente estão contratando só perfis mais seniores. No site da Remotar temos algumas: https://remotar.com.br/search/jobs?q=&c=13&t=17
