### ISSUE TITLE
[HOME OFFICE] Full-Stack Developer Jr III na Going2

### ISSUE THREAD

**Issue by gabrielabenite** [frontendbr/vagas#7650]
## Nossa empresa

A Going2 é uma startup que nasceu em 2012, com o propósito de levar tecnologia de ponta para todo o Brasil, focada em criar produtos que tenham como premissa, facilitar a vida das pessoas e empresas, através do desenvolvimento de Aplicativos, Sistemas e dos princípios de IOT (internet das coisas). Hoje, além de atender clientes nacionais também oferecemos nossos serviços para clientes internacionais, como por exemplo no Canada, Suiça e Estados Unidos.

Curiosidade: Além do mais, somos também uma das empresas patrocinadoras do projeto de Imersão Dev.(https://imersaodevpts.com.br/), sendo responsável pela educação de dezenas de jovens e na formação de soft e hard skills de desenvolvedores juniores para o mercado de trabalho.

## Descrição da vaga

VAGA AFIRMATIVA PARA MULHERES

## Local

Remoto

## Requisitos

**Obrigatórios:**

- Média de 1 a 2 anos de experiência como programador
- Conhecimento teórico “fresco” de TI de forma geral
- Interesse e conhecimentos sobre tecnologias mais recentes
- Tem domínio dos recursos básicos da linguagem
- Cursando Ensino Superior em áreas de Tecnologia (diferencial)
- Conhecimento e breve experiência com as tecnologias: **Node.Js, React.Js e React Native**
- Bibliotecas: Nest.Js, TypeORM 
- Banco de dados: MySQL
- Energia para aprender coisas novas
- Comprometimento pelo trabalho 

## Benefícios

- Plano de saúde (sem custo para titular)
- Plano Odontológico (sem custo para titular)
- Gympass
- Convênio com plataforma de Idiomas (Fluency Academy)
- Férias de 15 dias (sem descontos)
- Day-off de aniversário
- Plano de carreira

## Contratação

PJ

## Como se candidatar

Por favor envie um email para gabriela.benite@going2.com.br com seu CV anexado **E PRETENSÃO SALARIAL PJ** - enviar no assunto: Vaga Full-Stack Jr. 

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior

#### Gênero

- Feminino

**Comment by arthuresc** [comment]
Junior 1 a 2 anos de experiência HAHAHAHHAAHAHAH

Em ter., 28 de fev. de 2023 11:33, Gabriela Benite ***@***.***>
escreveu:

**Comment by italofelipe** [comment]
> Junior 1 a 2 anos de experiência HAHAHAHHAAHAHAH Em ter., 28 de fev. de 2023 11:33, Gabriela Benite ***@***.***> escreveu:
E errou onde? Junior teoricamente vem dps de trainee/estagiário

**Comment by censuradho** [comment]
Vcs são muito chato MDS, fiscal de vaga agora

**Comment by mateusdegobi** [comment]
Deviam colocar no título que é afirmativo para mulheres.

**Comment by gabrielabenite** [comment]
> Deviam colocar no título que é afirmativo para mulheres.

Não pode pelas regras da página.
