### ISSUE TITLE
[HOME OFFICE] Front-end Mobile Developer Jr. na Going2

### ISSUE THREAD

**Issue by gabrielabenite** [frontendbr/vagas#7652]
## Nossa empresa

A Going2 é uma startup que nasceu em 2012, com o propósito de levar tecnologia de ponta para todo o Brasil, focada em criar produtos que tenham como premissa, facilitar a vida das pessoas e empresas, através do desenvolvimento de Aplicativos, Sistemas e dos princípios de IOT (internet das coisas). Hoje, além de atender clientes nacionais também oferecemos nossos serviços para clientes internacionais, como por exemplo no Canada, Suiça e Estados Unidos.

Curiosidade: Além do mais, somos também uma das empresas patrocinadoras do projeto de Imersão Dev.(https://imersaodevpts.com.br/), sendo responsável pela educação de dezenas de jovens e na formação de soft e hard skills de desenvolvedores juniores para o mercado de trabalho.

## Descrição da vaga

VAGA AFIRMATIVA PARA MULHERES

## Local

Remoto

## Requisitos

- Média de 1 a 2 anos de experiência como programador
- Conhecimento teórico “fresco” de TI de forma geral
- Conhecimento e breve experiência com a tecnologia: React Native
- Banco de dados: MySQL
- Experiência com Git (Workflows)
- Experiência com consumo de API (ex: REST)
- Capacidade de escrever código eficiente e sustentável
- Capacidade de criar componentes reutilizáveis
- Energia para aprender coisas novas
- Comprometimento pelo trabalho

## Benefícios

- Plano de saúde (sem custo para titular)
- Plano Odontológico (sem custo para titular)
- Gympass
- Convênio com plataforma de Idiomas (Fluency Academy)
- Férias de 15 dias (sem descontos)
- Day-off de aniversário
- Plano de carreira

## Contratação

PJ

## Como se candidatar

Por favor envie um email para gabriela.benite@going2.com.br com seu CV anexado **E PRETENSÃO SALARIAL PJ** - enviar no assunto: Vaga Mobile Jr.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior

**Comment by rafael-jordao** [comment]
Currículo enviado!

**Comment by GabrielGuedess** [comment]
Enviado 🚀

**Comment by otomacedo** [comment]
Enviado !

**Comment by BeatrixFox** [comment]
Enviado
