### ISSUE TITLE
[REMOTO] Pessoa Desenvolvedora Front End Sênior| DEAL TECHNOLOGIES

### ISSUE THREAD

**Issue by ThauanySilva7** [frontendbr/vagas#7653]
**Sobre Nós**
Somos a Deal, estamos no mercado desde 2004 e somos referência em Inteligência de Dados e Transformação Digital, desde a estratégia até a execução (end-to-end).
Aqui, cada Dealmaker tem liberdade para:
• Ser quem é, numa cultura que valoriza as pessoas pela sua essência;
• Trabalhar de onde quiser, porque o Anywhere Office é uma realidade por aqui;
• Ser protagonista da sua carreira e escolher aonde quer chegar profissionalmente!

**Experiência e Conhecimentos em:**
• Experiência em padronização de sistemas front-end
• Experiência React (JSX)
• Experiência com typescript
• Experiência em melhores práticas front-end
• Experiência com next.js
• Experiência em clean arch
• Conhecimentos de UX
• Conhecimento em Redux
• Conhecimento em Flux
• Experiência em testes unitários
• Experiência em Postman/Swagger
• Experiência em metodologias ágeis
• Conhecimento em bibliotecas de gerenciamento de estado em react
• Experiência em GIT
• Experiência em construção de interfaces
• Experiência em implementação de design
• Conhecimento em Sass, Less

**Local**
Remoto, trabalhe de qualquer lugar da galáxia. 

**O que oferecemos:**
•	Anywhere office
•	Gympass
•	Plano saúde e odontológico
•	Vale Refeição/Alimentação
•	Seguro de vida
•	Day Off no aniversário
•	Plano de Desenvolvimento Individual
•	Reembolso de certificação
•	Programas internos de incentivo a educação
•	Trilha de desenvolvimento e carreira
•	E muito mais!

**Como se candidatar**
Por favor, envie um e-mail para [vemser@deal.com.br](mailto:vemser@deal.com.br)
Com seu CV anexado – enviar no assunto: Pessoa Desenvolvedora Front End Sênior

**Labels**

Alocação
•	Remoto

Regime
•	CLT
 
Nível
•  Sênior

**Comment by joaoromeira** [comment]
Enviado!
