### ISSUE TITLE
[SÃO PAULO] Front-end Developer JR na GRB SERVICES DO BRASIL

### ISSUE THREAD

**Issue by therecruiterr** [frontendbr/vagas#7657]
-->
> Vaga PRESENCIAL

## Nossa empresa

Exemplo: HÁ MAIS DE 10 ANOS, A GRB É ESPECIALIZADA EM MEDIAÇÃO DE DÍVIDAS E TERCEIRIZAÇÃO DE SERVIÇOS

## Descrição da vaga

- Desenvolvimento e manutenção de sistemas utilizando Java, Java script e MySQL;
- Implementação de APIs e integração com serviços em nuvem, como Google Cloud, Facebook e AWS;
- Desenvolvimento de aplicações utilizando frameworks como Spring Boot e Angular;
- Colaboração com outros membros da equipe de desenvolvimento para garantir a qualidade do software produzido;
- Pesquisa e experimentação de novas tecnologias e ferramentas.

## Local

Escritório, [SÃO PAULO], [SP], [REPUBLICA]

## Requisitos

**Desejáveis:**
- Experiência de no mínimo 2  Anos;
- Ensino superior cursando ou completo;
- Experiência em desenvolvimento Java, Javascript e MySQL;
- Conhecimento em frameworks como Spring Boot e Angular;
- Familiaridade com integração de serviços em nuvem, como Google Cloud, Facebook e AWS;
- Experiência em integração de APIs em nuvem, como OpenAI;
- Conhecimento em outras linguagens de programação e frameworks;
- Experiência em desenvolvimento ágil e metodologias de trabalho em equipe.

**Diferenciais:**
- DISPONIBILIDADE PARA ATUAR PRESENCIALMENTE EM SÃO PAULO, REPÚBLICA - CENTRO.

## Benefícios

- Salário – 7K;
- VR de 24,23 ao dia; 
- CM (Intermédica);  
- CO (Porto Seguros) ambos após 3 meses; 
- Convênio com faculdades;  
- Convênio com escola de idiomas;
- Parceria com boticário (Desconto em folha); 
- Convênio com SESC e outros;
- Parceria com restaurante Pampas;
- Plano de carreira.

## Contratação

CLT
## Como se candidatar

Por favor envie um e-mail para lucas.barbosa@grbsf.com.br com seu CV anexado - enviar no assunto: Vaga DEV JAVA PL

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- PLENO

**Comment by danricardo88** [comment]
currículo enviado com sucesso !

**Comment by VitorVeector** [comment]
Enviado!

**Comment by GabrielFray** [comment]
Enviado!

**Comment by gabrielmarqso** [comment]
Enviado!

**Comment by gabilu0** [comment]
Enviado!

**Comment by Toineto** [comment]
enviado

**Comment by therecruiterr** [comment]
Galera! Leiam com atenção, a vaga é PRESENCIAL portanto currículos fora de SP não temos como entrevistar;

**Comment by deleit** [comment]
Enviado!

**Comment by LucianaChamma** [comment]
CV enviado!

**Comment by rafaelsiqeira** [comment]
Enviado!

**Comment by luizlhrodrigues** [comment]
Enviado!

**Comment by joaov1ct0r** [comment]
enviado

**Comment by Hericke** [comment]
enviado!!!

**Comment by kosminsky** [comment]
@therecruiterr Fecha a issue, amigo.

**Comment by felipefialho** [comment]
@kosminsky feito
