### ISSUE TITLE
[Remoto] Front-end Developer na InforCFC

### ISSUE THREAD

**Issue by MarceloSantanaCodigo** [frontendbr/vagas#7658]
## InforCFC
Somos uma empresa líder em segmento de autoescola, a mais de 20 anos no segmento
## Descrição da vaga
 Você será responsável pela parte design e front-end da empresa, trabalhando sempre com UX, 
dar manutenção em aplicações angular, tanto web quanto (híbrida-Ionic), e criação de novos projetos em react.

## Local

Remoto (diferencial São Paulo)

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Front-End
- 2 anos de experiência com React (NEXTJS)
 
**Desejáveis:**
- conhecimentos em **REACT** (**PWA** e **NEXTJS**)
- conhecimentos em **ANGULAR**
- conhecimentos em **UI/UX**
-  conhecimentos em **docker**

**Diferenciais:**
- conhecer o básico de **asp.net core** (para debug)
- conhecer **Sql Server**
- figma
- **TRPC**

**Diferenciais:**
- Remoto

## Contratação

A combinar

## Como se candidatar

Por favor envie um email para juniorsantanamarcelo@gmail.com com seu CV anexado - enviar no assunto: **Vaga Front**

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dias após cada processo.
 

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Sênior
- Especialista

**Comment by sucodelarangela** [comment]
CV enviado!

**Comment by joaoromeira** [comment]
Enviado!

**Comment by censuradho** [comment]
CV enviado!
