### ISSUE TITLE
[Remoto ou Híbrido] Developer Javascript Sênior@ ITeam

### ISSUE THREAD

**Issue by VivianeRHTI** [frontendbr/vagas#7659]
## Local

São Paulo/SP (Zona Sul) - Híbrido ou 100% remoto
Full time em horário comercial

## Requisitos obrigatórios 

Experiência em desenvolvimento JavaScript, HTML, CSS e Node.js
Criação de Web Services (REST/SOAP)
Versionamentos GitHub
Gerenciamento de pacotes Pipelines JWT.

## Requisitos desejáveis/ diferencial

Experiências com linguagens Backend com Angular.js React.js
Conhecimento com Docker e Kubernetes.

## Contratação

Tempo indeterminado 

## Nossa empresa

Há mais de 15 anos presente no mercado, a ITeam oferece o comprometimento com o cliente.
Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 
O relacionamento da ITeam é baseado no amplo comprometimento com os valores e objetivos dos nossos Clientes, fornecendo soluções e serviços de TI que contribuam para a realização de seus objetivos.

## Como se candidatar

Envie um e-mail para viviane.pereira@iteam.inf.br com seu currículo atualizado e pretensão de valor PJ - enviar no assunto: Vaga no GITHUB - JavaScript SR

## Labels

- Horário comercial
- Híbrido e 100% Remoto
- Sênior
- PJ ou a combinar

**Comment by ovitormacel** [comment]
Enviado, obrigado.

**Comment by ovitormacel** [comment]
CV enviado, obrigado.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by ITeam-oportunidades** [comment]
Vaga encerrada.
