### ISSUE TITLE
[Curitiba] Desenvolvedor FullStack na Leads2b

### ISSUE THREAD

**Issue by debonaleonardo** [frontendbr/vagas#766]
## Descrição da vaga

A Leads2b está a procura de desenvolvedores com vontade de fazer diferente e inovar, contando com o que há de mais espetacular em termos de tecnologia

## Local

Vaga presencial, escritório em CURITIBA - PR, Bairro Bigorrilho

#### Diferenciais

- 1 hora e meia de almoço
- Trabalhar com Macbook
- Stack muito atual 

## Requisitos

**Obrigatórios:**
- Conhecimento em PHP (CodeIgniter, Laravel)
- Conhecimento em VueJS
- Conhecimento em Node (Loopback, GraphQL)
- MYSQL

**Desejáveis:**
- MongoDB
- Python
- Google BigQuery
- Ionic / Quasar

## Contratação

PJ ou CLT

## Como se candidatar

Por favor envie um email para leonardo@langowski.com.br com seu CV anexado - enviar no assunto: Vaga FullStack

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
