### ISSUE TITLE
[ Remoto / São Paulo ] Shopify Front-end Developer na Bars Over Bottles

### ISSUE THREAD

**Issue by robsonss** [frontendbr/vagas#7660]
## Nossa empresa

​Somos uma empresa de cosméticos sólidos que visa reduzir o uso de embalagens, zerar o uso de plástico e acabar com a contaminação de nossas águas.

Bars Over Bottles É assim, com produtos ZERO PLÁSTICO, desenvolvidos com muito carinho e esperança, que a B.O.B. quer fazer sua parte e ajudar o planeta a ser um lugar bem mais legal no futuro. A gente não sabe quais atitudes você tem tomado para colaborar, mas sejam quais forem, o convite que fazemos é o mesmo: vamos juntos? ☺

## Descrição da vaga

Buscamos um **desenvolvedor(a) front-end Shopify** para atuar no time de Desenvolvimento, que irá atuar em conjunto com o time de UX/UI transformando protótipos em códigos precisos e rápidos para garantir a melhor experiência de nossos clientes com o uso do nosso Site.

## Local

Remoto

## Benefícios
- Convenio Médico
- Vale Transporte ou Combustível
- Vale Alimentação
- Gympass 100%
- Jornada Flexível
- Kit B.O.B uma vez por mês
- Dayoff de Aniversário

## Requisitos

**Obrigatórios:**
- HTML, CSS, Java Script, Jquery
- Pré-processadores Sass, Less ou outros
- Shopify
- Liquid
- Não utilizar framworks bootstrap, foundation, ou afins

**Diferenciais:**
- Boas práticas de SEO
- Experiência com alguma plataforma de ecommerce
- React
- Vue.js
- APIs Rest

## Contratação

CLT

**Observações:
- Adotamos o modelo 100% home office para algumas áreas da empresa antes mesmo da pandemia. Inclusive a nossa área.

## Como se candidatar

Por favor envie um email para robson@usebob.com.br com seu CV anexado e portfolio se possuir - enviar no assunto: Vaga Shopify Front-end Developer

## Labels

- Alocado
- CLT
- Junior
- Pleno
- Shopify

**Comment by Jislanes** [comment]
Currículo enviado!

**Comment by sucodelarangela** [comment]
CV enviado!

**Comment by CarolMaiaP** [comment]
Currículo enviado!

**Comment by GabrielGuedess** [comment]
Enviado 🚀

**Comment by beasou** [comment]
Enviado!

**Comment by joaoromeira** [comment]
Enviado!

**Comment by lucianobarauna** [comment]
Enviado !

**Comment by Oaluiser** [comment]
Currículo enviado, obrigado!

**Comment by habakukc22** [comment]
Enviado.

**Comment by ovitormacel** [comment]
Enviado. <3
