### ISSUE TITLE
Fortaleza-CE Front-end Developer Pleno na Confidencial

### ISSUE THREAD

**Issue by Livia-Tech** [frontendbr/vagas#7662]
Desenvolvedor Front End Pleno 

Híbrido - Fortaleza

PJ 8.400 ou CLT 5.200 

PJ – 20 dias de licença, após 1 ano de contrato + Cursos de Desenvolvimento e possibilidade de participação em projetos extras.

CLT – Alimentação (500,00) + Auxilio H.O (200,00) Plano de saúde 100% Titular (Unimed) + Cursos de Desenvolvimento e possibilidade de participação em projetos extras.

REQUISITOS:

-Angular 8+;

-Conhecimento em Docker;

-JavaScript;

-NodeJs (Express/NestJS/REST API);

-GIT (Familiarização com Git Flow).

ATIVIDADES:

Desenvolverá APIs utilizando as melhorias práticas do mercado;

Desenvolverá no backend utilizando o NodeJS;

Desenvolverá no front utilizando o Angular 8+ com PrimeNG;

Utilizará metodologias ágeis, integração continua;

Integrará sistemas;

Apoiará as equipes no desenvolvimento das soluções.

ME CHAMA NO WHATSAPP (32) 98442-6808!

#docker #desenvolvimento #javascript #nodejs #frontend #angular #git

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
