### ISSUE TITLE
[Internacional e Remoto] Full-stack Developer (Python/React) na Lemon.io (U$ 5k - U$ 9k)

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#7663]
Are you a talented developer looking for a remote job that lets you showcase your skills while also enjoying better compensation and career growth? Look no further than Lemon.io, the marketplace that connects you with startups in the US and Europe.

## Sobre

Here are some reasons why you'll love working with us:

- We understand that respecting your time is key to your success, which is why we match you with teams that won't micromanage or require time trackers.
- You can earn a monthly salary of $5k - $9k, and we've already paid out over $10M to our engineers.
- With flexible working hours and the ability to work asynchronously, you can choose a schedule that works best for you.
- Say goodbye to project managers, and hello to direct communication with clients. Most of them have technical backgrounds. Sounds good, yeah?
- We support you throughout the entire recruitment process.
- No more hunting for clients or negotiating rates - let us handle the business side of things so you can focus on what you do best.
- Enjoy the fast-paced startup environment that will keep you motivated and engaged.
- Pass the recruitment process now and start working when you're ready - even if that's a few months down the line.
- We'll manually find you the best project to match your skills and preferences.
- Connect with the best developers in the world through our community.

## Requirements:

- Fluent with Python (5+ years of exp)
- Fluent with Django (similar python based web frameworks would be a plus)
- Strong knowledge and hands-on experience with React (2+ years)
- Strong experience with AWS
- Strong knowledge of OOP and design patterns
- Solid understanding of relational databases and NoSQL databases
- Experience with Flask and FastAPI would be a plus
- Ability to work all the way from high-level architecture design down to efficient code
- Good command of English, both written and spoken, as you’ll be communicating with clients directly
- Strong organizational skills — ability to work full-time remotely with no supervision
- Responsibility — we want to trust you
- Soft skills — we don’t ask you find a topic for a small talk, but being just polite is OK

### Recruitment process:

1. First step: VideoAsk (about 10 minutes)
2. Second step: 30 minutes Screening call with our Recruiters
3. Third step: Technical Interview with our Developers
4. Feedback
5. Magic Box (we are looking for best project for you) 

## Remuneração
$5,000.00 a $9,000.00 USD / Mensal

## Como se candidatar

Clique [aqui](http://bit.ly/3LaiFr1) para aplicar

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by nltncsr** [comment]
Oi @tatidirienzo, muito atraente a oportunidade, porém algo não ficou claro. O ponto `5` "Magic Box" indica que não existe uma vaga específica, que na verdade é um banco de talentos ao invés de uma posição aberta esperando pra ser preenchida. Consegue confirmar?
