### ISSUE TITLE
[REMOTO] Front-end Developer Pleno na OPIKODE

### ISSUE THREAD

**Issue by cmaiarenata** [frontendbr/vagas#7665]
**Nossa empresa**

A Opikode é uma empresa de desenvolvimento de software que está construindo sua marca no mercado brasileiro, produzindo soluções de alto valor para os negócios de nossos clientes e parceiros.

Temos clientes em 22 estados, representando quase todo o território nacional, com um excelente nível de satisfação com a qualidade dos serviços prestados.

Nossa equipe é composta por especialistas, que criam soluções corporativas de enterprise-ready que proporcionam entregas rápidas de alto valor para as empresas, impulsionando o crescimento e o alcance de seus objetivos estratégicos mais rapidamente.

**Principais Atividades e Responsabilidades**

-Desenvolver componentes modulares usando HTML, JS, CSS, SaSS, LESS e Freemarker, os componentes irão chamar serviços do Liferay DXP ou serviços externos;
-Desenvolver interfaces a partir de protótipos desenvolvidos no Figma e no Adobe XD;
-Aplicar boas práticas de SEO;

**É necessário você ter conhecimento em**

-Experiência consistente com Desenvolvimento de Software;
-Domínio Técnico no Front-End (html, js, css);
código não-obstrusivo e modular;
-JSON API, REST e experiência com integração de APIs;
-Metodologias ágeis ( Scrum ou Kanban);
-Continuous integration/delivery/deployment;
-Usamos o GitLab para versionamento, GitLab CI e Jenkins para integração e entrega contínuas;
-Experiência com SEO;

**Diferencial**

-Conhecimento em Angular, React.JS ou Svelte serão considerados diferenciais;
-Conhecimento em Liferay DXP e DXP Cloud e certificações na plataforma;
-Conhecimento em E-Commerce;
-Conhecimento em UI/UX;
-Conhecimento em Apache Freemarker;

**Local**

Remoto.

**Contratação**

CLT
Plano de Saúde
Ajuda de Custo
VR

**Como se candidatar**

Para se candidatar pode enviar um e-mail para [renata.maia@opikode.com](mailto:renata.maia@opikode.com) com seu currículo, indicando a vaga de interesse.

**Nível**

Pleno

**Comment by sucodelarangela** [comment]
Currículo enviado!

**Comment by habakukc22** [comment]
Enviado!

**Comment by juliemoura** [comment]
Enviado :)

**Comment by gabrielcaamargo** [comment]
Enviado!

**Comment by uildez** [comment]
Email enviado!

**Comment by wsasouza** [comment]
CV enviado...

**Comment by PandaZIM** [comment]
Enviado!

**Comment by Pedrohamoura-Git** [comment]
Enviado.

**Comment by cmaiarenata** [comment]
Vaga fechada, pessoa contratada através do grupo.

**Comment by cmaiarenata** [comment]
Vaga fechada, pessoa contratada através do grupo.
