### ISSUE TITLE
[REMOTO] [Sócio] Full-stack Developer na Winconcursos.com.br

### ISSUE THREAD

**Issue by WinConcursos** [frontendbr/vagas#7666]
**Nossa empresa**
Criada em 2018, a Winconcursos é **Startup** voltada para Concurso Público. 
Oferecemos uma plataforma de Controle e Organização de Estudos, para ajudar os concurseiros no dia a dia dos estudos, com relatórios e gráficos. Além da plataforma de Controle de estudos, temos um marketplace integrado, com algumas empresas parcerias, onde elas podem divulgar suas apostilas e materiais de estudo, como: apostilas simulados, Vídeo Aulas, entre outros. Esses materiais são vendidos dentro da plataforma, onde a Win fica com uma comissão da venda.

A Win tem um potência de crescimento muito grande. Precisamos de um programador comprometido para desenvolver novos módulos, além de ajustes de melhorias e correção de bugs.

Temos uma base com mais de 2k de alunos que usam a nossa plataforma, além de outros alunos que apenas compram os produtos disponíveis em nosso marketplace.

**Nossa Missão:**
Ajudar o aluno a alcançar seu objetivo pessoal e profissional através de concursos. Facilitar o aprendizado e a organização, além de trazer segurança e tranquilidade aos estudantes ao longo de sua preparação até sua aprovação.

Além disso, nossa maior missão é ser a maior **Edtech** do Brasil. 

-> Atualmente estamos abrindo vaga no quadro societário da nossa empresa buscando um programador que esteja disposto a se juntar à equipe.

**Descrição da vaga**
-> ser Sócio Programador - com percentual a combinar.
-> Você não precisará contribuir com nenhum valor para ser sócio.
-> Não há salário, por enquanto. Mas para ajudar, este sócio programador receberá uma parte da receita, como forma de renda.

**Local**
Remoto

**Requisitos**
- 2+ anos de experiência com PHP, MySQL, JS, CSS, HTML, 
- Experiência com LINUX, VPS, AWS S3, Nginx, API de pagamento

**Diferenciais:**
- Ser criativo(a) e Proativo(a)
- Ter espírito empreendedor

**Como se candidatar**
Por favor, envie currículo para nosso Whatsapp: https://wa.me/552232613850

Labels
Alocação
- Remoto

Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by DiogoJorge1401** [comment]
mandei mensagem!
