### ISSUE TITLE
Pessoa desenvolvedora Front End/ Pleno - Code n'App

### ISSUE THREAD

**Issue by Inglidbarbosa** [frontendbr/vagas#7668]
## Nossa empresa

Somos uma empresa que é a-pai-xo-na-da por tecnologia, que através do desenvolvimento de software e processos, buscamos soluções inovadoras e totalmente customizadas para cada um dos nossos clientes a fim de alcançar o melhor resultado, independente da tecnologia utilizada.

Além disso, estamos em um ritmo de crescimento a-ce-le-ra-do, então se você curte desafios, busca evoluir e ama tecnologia, temos aqui um time para chamar de seu! Pois adoramos reconhecer e potencializar o desenvolvimento dos nossos Codenappers.

#VemPraCode ♥

## Descrição da vaga
Etapas do processo seletivo:
Inscrição e avaliação inicial (Dica: mantenha seu currículo atualizado na plataforma);
Triagem (Para essa etapa, vão as pessoas com mais aderência à descrição da vaga)
Entrevista comportamental e técnica (Com o time de pessoas e cultura e o Gestor da área);
Feedback e/ou formalização da proposta.

RESPONSABILIDADES E ATRIBUIÇÕES
A pessoa desenvolvedora pleno será responsável pela criação e evolução do front-end de sistemas web, utilizando de frameworks JS, HTML e CSS, assim como técnicas de responsividade, fidelidade ao protótipo, apoio à equipe de devs, mapeamento de tasks e atividades das implementações a serem desempenhadas pela equipe e por si próprio. Tendo a oportunidade de atuar internamente ou em clientes parceiros, contribuindo em todo o ciclo de vida, desde a concepção até a implantação, atuando com metodologias ágeis para entregar uma solução eficiente. Esperamos que essa pessoa possa:

Contribuir para o sucesso do projeto e o crescimento da equipe;
Conhecer as boas práticas de programação das tecnologias utilizadas;
Apoiar a equipe no desempenho de suas atividades;
Propor melhorias ao sistema projetado;
Possuir visão sistêmica do projeto, avaliando riscos do desenvolvimento e impactos que envolvem a atuação da equipe;
Escrever código limpo, de qualidade e de fácil manutenção.
REQUISITOS E QUALIFICAÇÕES
Graduação ou Tecnólogo completo em áreas de tecnologias da informação;

Experiência no desenvolvimento de interfaces web, utilizando React JS e/ou Vue JS;

Sólidos conhecimentos em:
HTML/CSS/Javascript;
Typescript;
React JS;
Context API;
Git e GitFlow;
Experiência em metodologias ágeis como Scrum.
## Local

Presencial - Vitória-ES
## Benefícios

Nosso ambiente foi preparado para que você que gosta de compartilhar experiências, ama resultados e adora se divertir com os desafios do dia a dia. E mais, pensamos em como melhorar tudo isso com um pacote de benefícios:
⏰ Possibilidade de horário flexível e de modelo híbrido; 
👕 No dress-code; 
🏋🏽‍♀️ Gympass; 
🧘‍♂️ Apoio a saúde mental (Em parceria com a plataforma Psymeet);
🩺 Assistência médica (você + parceiro(a) + filhos até 18 anos é por nossa conta); 
🦷 Assistência odontológica; 
🥗 Alimentação: Pra que escolher entre alimentação ou refeição se você pode ter os dois em um só? Além de um saldo livre para utilização nas categorias de mobilidade, cultura, saúde e home office; 
🚍 Vale transporte; 
🎉 Celebração de datas importantes (Seu aniversário, aniversário Code n’ App, etc.); 
🛏️ Day off (folga no aniversário);
📚 Acesso gratuito à plataforma Udemy; 
💸 Um clube de vantagens incrível onde você pode desfrutar de vários descontos em diversas categorias como alimentação, turismo, instituições de ensino e etc.
E tem mais: 

🤑 Programa Indica Code - (Indicando um amigo você ganha um bônus de R$500,00 por talento contratado); 
🤱🏽 Cesta recém-nascido; 
🍪 Cafézinho e biscoitinhos à vontade, além de puffs para cochilar nos intervalos; 
💰 Assessoria e educação financeira; 
💵 Empréstimo consignado; 
👨🏽‍💻 Oportunidade de fazer parte de um time de feras e com muitas experiências para compartilhar. 
🦽 Todas as nossas vagas estão disponíveis para pessoas com deficiência! 
## Contratação

CLT ou PJ

## Como se candidatar
https://codenapp.gupy.io/jobs/4448266
### Nível

- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
