### ISSUE TITLE
[Goiânia] React Native developer na Mudano (Londres)

### ISSUE THREAD

**Issue by ralves00123** [frontendbr/vagas#767]
## Descrição da vaga

Procuramos desenvolvedor React Native para uma empresa de Londres.

## Local

Escritório, Goiânia - GO

## Benefícios

- Mac, Ultrabook Windows ou Linux dual boot
- 25 dias de férias
- Feriados normais mesmo sendo trabalho para uma empresa estrangeira

#### Diferenciais

- Horário flexível
- Lanches saudáveis pagos pela empresa
- £1500,00 por ano para gastar com qualquer curso
- £10 por mes para comprar livros
- Stock options depois de 6 meses contratado
- Possibilidade de viagem a Londres uma vez por ano com estadia paga pela empresa

## Requisitos

**Obrigatórios:**
- 1 ano de experiencia com React Native
- Inglês intermediário (Fala e escrita)

**Desejáveis:**
- React
- ES2016
- REST APIs e GraphQL
- TDD

## Contratação

- PF ou PJ
- Salario em torno de £2000,00 (Vai depender da experiencia e conhecimento)

## Nossa empresa

https://mudano.com/about

Maiores detalhes em: https://mudano.com/careers/product/react-native-engineer-1-1

## Como se candidatar

Por favor envie um email para ricardo.alves@mudano.com com conteúdo e seu CV em inglês anexado - enviar no assunto: Vaga React Native

**Comment by diogomoretti** [comment]
@ralves00123 quais as labels?

**Comment by bonejah** [comment]
Pode ser feito algum trabalho tipo freelance?

**Comment by ralves00123** [comment]
@diogomoretti Nao tenho permissao para colocar labels. Nao consigo nem saber as opcoes que existem.

@bonejah Por enquanto sem freelance.

**Comment by diogomoretti** [comment]
@ralves00123 por isso perguntei hehehe para eu colocar =]

**Comment by rubenmarcus** [comment]
putz só pode aplicar de Goiania? Essa vaga é muito boa

**Comment by ralves00123** [comment]
@diogomoretti hehehe entendi.
Poderia colocar junior, pleno e senior também por favor?

**Comment by HaluDeCassia** [comment]
@ralves00123 essas vaga não pode ser full remoto?

**Comment by ralves00123** [comment]
@HaluDeCassia Não, o candidato tem que morar ou se mudar para Goiânia.

Precisamos também de um full stack e um tester.

**Comment by HaluDeCassia** [comment]
@ralves00123 Que pena. Muito obrigada, boa sorte na busca

**Comment by victorhtc** [comment]
Estamos possibilitando trabalho remoto para esta vaga agora, desde que o candidato tenha inglês fluente. Podemos mudar as labels @diogomoretti. @ralves00123 pode confirmar por favor.

**Comment by ralves00123** [comment]
Confirmado @victorhtc @diogomoretti

**Comment by DawTaylor** [comment]
Veja isso @HaluDeCassia, agora estão aceitando remoto full. ;)

**Comment by matheushf** [comment]
Olá! React Native é a única vaga em que disponibilizam Remoto Completo?

**Comment by HaluDeCassia** [comment]
@DawTaylor Acabei perdendo sua marcação no meio das notificações. Valeu :blush:

**Comment by Pedro-Souza** [comment]
@ralves00123 te mandei um email.

**Comment by scarpelini** [comment]
hey @HaluDeCassia entrei no seu perfil do GitHub mas não encontrei um e-mail pra contato. Por favor me envie um e-mail para julio@santa.io estamos a procura de desenvolvedores remotos.

**Comment by vititu** [comment]
@scarpelini Esta vaga para remoto, qual seria? Tem alguma descrição?

**Comment by scarpelini** [comment]
@vititu é para desenvolvimento em React Native. Basicamente trabalhar com Webpack, Redux e Redux Saga além de o básico de boas práticas para ter um código limpo, compreensível, manutenível e escalável.

**PLUS**
- Custom Components & Custom Animations
- Utilizar TDD

Vou criar uma vaga específica para esse caso em breve.

**Comment by eliasmelgaco** [comment]
A Vaga ainda esta aberta ?

**Comment by eliasmelgaco** [comment]
@ralves00123 boa noite ! A vaga ainda esta aberta ?

**Comment by Nbioni** [comment]
Sou de Goiânia e possui experiência em React Native. Me candidato a vaga. Entrem em contato comigo se ainda precisarem: 62 98139-0950. Nahaliel Bioni
