### ISSUE TITLE
[Joinville - SC] Front-end Developer Pleno na Weknow Healthtech

### ISSUE THREAD

**Issue by Emmelimp** [frontendbr/vagas#7673]
## Nossa empresa

Somos a primeira empresa do Brasil a criar soluções de inteligência de dados para o mercado da saúde (hospitais, clínicas, operadoras e laboratórios).

## Descrição da vaga

Quer fazer parte da Healthtech TOP 1 selecionada pela 100 Open Starups?
Temos uma vaga para você no nosso time de Desenvolvimento.

**No dia a dia você irá:**

Analisar novos projetos e implementações;
Desenvolver novas funcionalidades;
Corrigir bugs;
Revisar o código de outros profissionais;
Auxiliar no treinamento de profissionais juniors e estagiários.

## Local

Remote First

## Requisitos

**Obrigatórios:**
Experiência com desenvolvimento JavaScript e com Angular 2+

**Desejáveis:**
Será um diferencial se você tiver experiência com Angular JS.

## Benefícios

Principais Benefícios:

·       Férias remuneradas 30 dias / Ano.
.       Vale Alimentação
·       INSS + IR + TAXAS – Retidos mensalmente pela cooperativa (incluso no líquido).
·       Décimo terceiro salário – pago anualmente como Bônus produtividade.
·       Programa weGoals (PLR – Bônus pago anualmente baseado em metas globais de vendas).
·       Programa weGrow (incentivo ao desenvolvimento profissional, válido após 6 meses de casa).

## Contratação

Cooperativa/Cooperado

## Como se candidatar

Por favor envie um email para rh@weknowhealthtech.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: emeli.pavanello@weknowhealthtech.com.br

#### Alocação
- Remoto

#### Regime
- Cooperativa

#### Nível
- Pleno

**Comment by PandaZIM** [comment]
Enviei!

**Comment by Toineto** [comment]
enviado

**Comment by eltonfreitasx** [comment]
enviado!!

**Comment by censuradho** [comment]
Enviado!!  😄

**Comment by jonatasbueno** [comment]
O que é Remote First ? Isso por ventura quer dizer que deixará de ser remoto ?

**Comment by thaylorcs** [comment]
Remote first significa que eles contratam prioritariamente de forma remota e em outros casos híbrido/presencial

**Comment by DevCleverton** [comment]
> O que é Remote First ? Isso por ventura quer dizer que deixará de ser remoto ?

tem empresas que  trabalha remoto  e em algum momento  pedem para  o funcionário  ir ate o escritório fazer  trabalhos treinamentos  etc...

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
