### ISSUE TITLE
[São Paulo] Front-end Developer na Sebratec

### ISSUE THREAD

**Issue by CarolineBotan29** [frontendbr/vagas#7674]
#### Alocação
- Alocado

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by filipefpaulo** [comment]
Olá bom dia Caroline, tenho bastante interesse na vaga, como faço para me candidatar?

**Comment by joaoromeira** [comment]
@CarolineBotan29, tudo bem? Quais os requisitos?

**Comment by Leonardo-Selegar** [comment]
Olá Caroline, tudo bem? Quais seriam os requisitos? tenho bastante interesse na vaga

**Comment by victorbiasibetti** [comment]
@felipefialho @joaoromeira @Leonardo-Selegar só olhar no histórico do post
a @CarolineBotan29 editou depois de postar

**Comment by rafatrinity** [comment]
requisitos..? candidatura..?

**Comment by joao160197** [comment]
Quais os requisitos?

**Comment by CarolineBotan29** [comment]
> Quais os requisitos?

Hey, segue o link https://www.careers.sebratec.com/position/detail/225
Acredito que como houve edição os detalhes da posição ficaram no historico!
Obrigada!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
