### ISSUE TITLE
[Remoto] Front-end Developer na Nexmuv

### ISSUE THREAD

**Issue by HelenNexmuv** [frontendbr/vagas#7675]
## Descrição da vaga
Desenvolvimento para projetos web 

## Local

Remoto 

## Requisitos
Experiência com Angular; 
Bacharel em área de tecnologia 
Git flow 
Metodologia Scrum 
Arquitetura de micro serviços 
Docker 
Testes unitários.

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para helen.matos@nexmuv.com.br  com seu CV anexado - enviar no assunto: Vaga angular

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
