### ISSUE TITLE
[100% Remote] Senior Frontend Developer (React.js) at SevenApps

### ISSUE THREAD

**Issue by rhSevenApps** [frontendbr/vagas#7677]
**Our company**
We are more than a company, we are a lifestyle based on the passion to solve problems using design, usability and technology. Our purpose is to unite the best professionals in the market in international projects, with career growth and high-speed internal exchange. Our team learns, evolves and shares.

With an administrative office in Belo Horizonte and a headquarters in Miami, we have already grown more than 300% in the last year and we have helped our clients to grow more than 120% with the allocation of our senior professionals and/or the development of high-performance applications and software.

**Job Description**
Are you looking for new challenges?! What if you could work on an incredible international project, and still receive all the support from high-performing Brazilian colleagues?

At SevenApps, you will be close to the best technologies on the market, work on challenging projects and in a rich learning environment. We are looking for proactive, experienced devs who are in search of experiencing this immersion in the culture of the North American market.

In this position, you will work to an international project for a large Florida company (payment in dollars), and you will have the autonomy and freedom to work 100% remotely, with flexible hours. Your challenges will involve frontend web (React.js) development . You will have a highly skilled team to implement these solutions with you.
We believe that technology has the power to transform, improve the way we live and face challenges. If you believe that too, come be part of our team!

**Requirements**
5+ years of UI development using Javascript based frameworks;
3+ years of experience with React / React Native;
Fluency in English is a must;
Expert level with Typescript
Firm grasp of the JavaScript language and its nuances, including ES6+ syntax;
Ability to write well-documented, clean Javascript code;
Rock-solid at working with third-party dependencies and debugging dependency conflicts;
Familiarity with building pipeline and automated deployment.
Understanding of REST APIs, the document request model, and offline storage;
Experience with automated testing suites;

**Benefits**
Budget: 4k-4,3k USD
**PJ**

**How to apply**
Send an email to: [[rh@sevenapps.com.br](mailto:rh@sevenapps.com.br)] with the subject "Frontend position | React.js"

**Learn more about our SevenApps code:** https://www.sevenapps.tech/

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
