### ISSUE TITLE
[Florianópolis] React Developer pleno na Botdesigner

### ISSUE THREAD

**Issue by guilhermegehres** [frontendbr/vagas#7680]
# Nossa empresa

A Botdesigner é uma empresa de Chatbot especializada na área da saúde que surgiu com o propósito de ajudar instituições de saúde a melhorar o relacionamento com seus pacientes, otimizando processos relacionados aos agendamentos de consultas e exames.

# Sobre a vaga

- Criar as interfaces da aplicação de acordo com especificações do produto.
- Alterações na plataforma visando a alta performance.
- Corrigir bugs e eventualmente alteração de código legado(temos bem pouco código legado).
- Modalidade de contratação: PJ.

# Local
Florianópolis/SC
Vaga híbrida, a empresa trabalha presencial nas segundas feiras e eventualmente outros dias.
Favor enviar currículo apenas se for de Florianópolis e região. Envios de outras regiões não serão respondidos!

# Requisitos

- 3 anos de experiencia com React + typescript.
- Saber consumir APIs REST.
- Ter conhecimentos básicos sobre WEBSOCKETs
- Metodologias ágeis como Scrum e Kanban

## O requisito mais importante é:
- Ter perfil startup, as coisas mudam muito rápido aqui e não temos medo da mudança.

# Como se candidatar

Enviar email com linkedin e assunto 'Vaga frontend' para guilherme@botdesigner.io Com cópia para daniel@botdesigner.io

# Tecnologias utilizadas aqui

- MongoDB
- Framework NestJS + typescript
- Apache Kafka/RabbitMQ
- Redis
- Postgres
- Reactjs + typescript

# O que oferecemos para você
- Cartão multibenefícios
- Coffee break nas segundas-feiras
- Day Off no mês de aniversário
- Recesso remunerado
- PPR (Programa de Participação nos Resultados)
- No dress code
- Ambiente colaborativo: você pode ensinar e aprender muito

# Range salarial
- R$6k a R$9k dependendo da experiência

**Comment by sucodelarangela** [comment]
CV Enviado

**Comment by GabrielGuedess** [comment]
Enviado 🚀

**Comment by matheusmcz** [comment]
Enviado :D

**Comment by soaresrodrigo** [comment]
Enviado!

**Comment by natamartins** [comment]
Enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
