### ISSUE TITLE
[Remoto] Frontend Developer Pleno (React, React Native) - Vem pra @Datum

### ISSUE THREAD

**Issue by julianakraemer** [frontendbr/vagas#7684]
## Nossa empresa

A Datum é uma empresa GPTW (Great Place to Work) pelo terceiro ano seguido. Nossa sede fica em Porto Alegre/RS e recentemente chegamos no Canadá

## Descrição da vaga

Desenvolvedor Web Sênior, com foco em React Native e experiência com React JS para atuar na criação de novas features, manutenção das funcionalidades e correções de bugs do site de um cliente da área de varejo.
O profissional deve ser capaz de propor novas soluções e tecnologias que visem a melhoria e otimização dos sistemas web mantidos pela tribo. Participação ativa nos ritos do modelo de trabalho, Code-reviews, Pair Programmings e elaboração de documentações.
 
## Local

Remoto

## Requisitos

**Obrigatórios:**
Mandatória sólida experiência com desenvolvimento Web, React Native, React JS.,
Experiência com HTML5, CSS3/SCSS, Java Script(ES5/6/7), Type Script,
Mandatória experiência com APIs Rest e GraphQL,
Vivência com testes unitários,
Experiência com versionamento de código em Git e fluxo de desenvolvimento utilizando pipeline (esteira),
Desenvolvimento limpo, organizado, sempre aplicando boas práticas, conceitos de performance e segurança em primeiro lugar,

**Desejáveis:**
Experiência em Next.js é um diferencial,
Experiência em Node.js é um diferencial,

## Benefícios
Aqui na Datum, nossos datunianos usufruem de benefícios e programas que atendem diversas áreas da vida.

Para sua saúde, oferecemos assistência médica e odontológica sem coparticipação em exames e consultas.
Seguro de vida
Quer mais bem-estar? Oferecemos Gympass, Zenklub (com duas sessões gratuitas por mês) e ginástica laboral para dar aquela alongada durante o expediente.
Quando bater aquela fome, utilize nosso benefício de alimentação Caju para fazer compras em qualquer supermercado ou restaurante.
Ama viajar? Aqui temos o Férias & Co, um benefício que te ajuda a viabilizar aquela viagem dos sonhos.
Tem filhos? Temos auxílio creche.
Quer aprender um novo idioma? Temos parceria com a escola CCAA, com descontos de até 40% nos cursos, e também o English Live que oferece 30% de desconto na mensalidade.
Para deixar seu ambiente de trabalho com a sua cara, conte com o nosso auxílio home office.
Quer protagonizar? Participe do Protagonistas, nosso game da vida real, e ganhe prêmios incríveis!

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para juliana.kraemer@datum.inf.br

#### Alocação

- Remoto

#### Regime
- CLT
- PJ

#### Nível

- Pleno

**Comment by sucodelarangela** [comment]
CV enviado

**Comment by wsasouza** [comment]
Enviado...

**Comment by puegue1999** [comment]
Enviado

**Comment by luanargolodev** [comment]
CV enviado! :)

**Comment by censuradho** [comment]
CV Enviado!

**Comment by ribeiroevandro** [comment]
@julianakraemer currículo enviado!

**Comment by julianakraemer** [comment]
Obrigada a todos que enviaram o cv, recebi bastante demanda! Vamos avaliar e retornaremos por e-mail ao longo da semana :)
