### ISSUE TITLE
[Portugal] Frontend Developer @Integer Consulting Portugal

### ISSUE THREAD

**Issue by brunoalexandrecarvalho** [frontendbr/vagas#7685]
# Integer Consulting Portugal

A Integer Consulting é uma empresa portuguesa de consultoria em tecnologias de informação. Somos especialistas em serviços de TI outsourcing, software, projetos de Nearshore e desenvolvimento à medida. Somos parceiros dos principais players tecnológicos a nível mundial e trabalhamos com empresas nacionais e multinacionais de diversos setores de atividade. Temos diversas oportunidades em aberto, entre as quais:

## Frontend Developer
- Licenciatura e/ou Mestrado em Engenharia Informática ou similar;
- +5 anos de experiência profissional em desenvolvimento Frontend;
- Experiência com Angular e/ou React (obrigatório);
- Experiência em HTML, CSS, JavaScript e TypeScript;
- Familiaridade com metodologias Agile;
- Inglês fluente (obrigatório).

Benefícios:
- Suporte no processo de visto e reagrupamento familiar;
- Plano de saúde (para o candidato e família);
- Alojamento nas primeiras semanas em Portugal;
- Acompanhamento logístico, administrativo e legal durante todo o processo de vinda para Portugal;
- Acesso a plataformas de formação;
- Acesso a plataformas para o desenvolvimento de línguas estrangeiras; 
- Acesso à nossa rede de parcerias (descontos em serviços, academia, cosmética, restauração, etc...);
- Prémios por recomendação de outros consultores;

Todas as oportunidades pressupõem uma mudança para Portugal. Para todas elas, é necessário +4 anos de experiência comprovada na área. O salário irá sempre variar consoante o tempo de experiência, competências técnicas e nível de inglês. É fundamental fazer um estudo sobre o custo de vida em Portugal para perceber a viabilidade desta mudança.

Aos interessados, podem enviar o CV atualizado para bruno.carvalho@integer.pt

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
