### ISSUE TITLE
[Remoto] Front-end Developer na Globo

### ISSUE THREAD

**Issue by juulander** [frontendbr/vagas#7686]
## Nossa empresa

Originalmente fundado em 1925, O Grupo Globo é o maior conglomerado de mídia e comunicação do Brasil. Suas produções nas áreas de Jornalismo, Esporte e Entretenimento atingem mais de 90% da população e a programação de seus canais televisivos falam com mais de 100 milhões de brasileiros todos os dias.

## Local

Remoto.

## Requisitos

**Obrigatórios:**
- Conhecimento em Javascript Vanilla;
- Conhecimento em Testes.

## Benefícios

PLR de até 1,5 salários
Assistência Médica e Odontológica
Seguro de vida
VA e VR 35/dia
Prev. Privada
2 anos de globoplay + telecine grátis

## Contratação

CLT.

## Como se candidatar

Enviar um e-mail para [julia.saraiva@landtech.net.br] com o assunto "Desenvolvedor Front-end Globo".

#### Regime
- CLT

#### Nível
Buscamos pleno e sênior.

**Comment by ismaelcostarc** [comment]
Enviei.

**Comment by sucodelarangela** [comment]
Enviado.
