### ISSUE TITLE
[São Paulo] Full Stack Software Engineer PL (C#, Node ou Java) | Pacifica Continental 

### ISSUE THREAD

**Issue by leticiaamf7** [frontendbr/vagas#7687]
## Nossa empresa 🌎

Pacifica Continental é uma empresa de recrutamento global especializada em cargos estratégicos, tais como membros da diretoria, c-suites, gerentes superiores e intermediários. Nossas soluções personalizadas e abordagem consultiva garantem a seleção dos melhores talentos do mercado.

Nossas operações alcançaram mais de 50 países, incluindo mais de 250 cidades ao redor do mundo. Orgulhamo-nos de trabalhar com precisão e conhecimento em uma ampla gama de indústrias. Sempre comprometidos com a obtenção de uma visão industrial contínua, fazemos parcerias com um grande número de empresas multinacionais e locais.

## Descrição da vaga📢
Nosso cliente, uma uma fintech em ascensão, líder no mercado que atua, busca um Full Stack Software Engineer PL para fazer parte de seu time.
O principal desafio é ajudar na sustentação da squad bem como desenvolvimento de novas features. Contribuirá diretamente com as metas de receita e escala.

## Responsabilidades ✅

- Desenvolver novas aplicações e sustentação/refactor de serviços da plataforma de depósitos de ativos (IMF);
- Atuar como full stack, desde a criação de microsserviços no backend até a integração de funcionalidades no frontend;
- Criar novos recursos, escrita de testes unitários.

## Hard Skills ✔

- Possua sólida experiência com linguagens orientadas a objeto (preferencialmente ,  ou );
- 4 anos de experiência prévia como desenvolvedor. 
- Possuir experiências com algum framework SPA moderno,  e Vue Js, Angular;
- Possuir experiência com Typescript/script, HTML, CSS;
- Tenha experiência com testes de software automatizados;
- Conhecimento básico em pelo menos uma das seguintes nuvens (, Google Cloud ou Azure); 
- Desenvolver novas aplicações e sustentação/refactor de serviços da plataforma de depósitos de ativos (IMF);
- Formação em TI ou correlatas.

## Soft Skills ✔

Goste de atuar com Pair Programming - Aprender e compartilhar;
Tenha trabalhado com Pull Requests e code review;
Possua atitude positiva e se expresse com facilidade e empatia;
Valorize o trabalho colaborativo e aceite bem feedbacks e contribuições das pessoas do seu time;

## Desejável ✨
- Conhecimento em mercado financeiro, Linux, JS, Go,  ou Angular, Conhecimento em nuvem ( ou Cloud)

- Formação em TI ou correlatas

## Local 📍

- São Paulo | Remoto

## Contratação 💸

CLT.

## Como se candidatar 💻

Se inscreva pelo site: https://pacificacontinental.applytojob.com/apply/X9hYdrOfKV/Full-Stack-Software-Engineer

*Observação: caso você tenha experiência com tecnologias cujo escopo seja semelhante, não deixe de aplicar!*

**Comment by sucodelarangela** [comment]
Inscrição efetuada!

**Comment by soaresrodrigo** [comment]
Enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
