### ISSUE TITLE
[REMOTO] Fullstack Developer (Sênior) na VSM Informática ❤💙

### ISSUE THREAD

**Issue by Jooaoferreira** [frontendbr/vagas#7688]
## Nossa empresa 🌎

Há mais de 30 anos a VSM desenvolve softwares especializados no gerenciamento de drogarias e farmácias de manipulação. Nestes anos, vivenciamos todos os avanços do mercado, aprimorando nossas soluções, com sistemas robustos e confiáveis, implantados em milhares de clientes espalhados por todo o território nacional.

## Descrição da vaga 📢

Utilizar as tecnologias afim de criar facilidades para os clientes, trazer inovações tecnológicas, contribuir com o time afim de facilitar os processos de desenvolvimento; Compreender as regras de negócio sobre sistemas de gestão de vendas ECM, financeiro e fiscal; Aplicar conceitos de Clean Code, padrões de projeto.

## Responsabilidades ✅

- Conhecimento em desenvolvimento para Web (BackEnd: Java Sping / FrontEnd: Angular); 
- Arquitetura MVC e padrões de projeto; 
- Prática com frameworks Sping JPA e Hibernate; 
- Vivência com Banco de Dados relacional MySQL e modelagem, construção de Querys e rotinas em PL/SQL e banco de Dados não relacionais; 
- Programação orientada a objetos e conceitos de UML; 
- Prática com Micro serviços.

## Desejáveis ✨

- Experiência em coordenação de projetos; 
- Know-how em metodologias ágeis; 
- Sistemas de automação comercial; 
- Conhecimento em e-commerce.

## Contratação 💸

CLT.

## Local 📍

Remoto

## Como se candidatar 💻

Envie seu #currículo pelo site https://lnkd.in/dRQgMW85 ou através do e-mail recrutamento@vsm.com.br com o título Vaga Fullstack e venha inovar com a gente! 🚀

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
