### ISSUE TITLE
[REMOTO] Pleno e senior Back-end Developer na igma

### ISSUE THREAD

**Issue by mcfo-contato** [frontendbr/vagas#7689]
## Nossa empresa

Queremos cocriar um mundo onde experiências incríveis se tornem essenciais. Com coragem, entusiasmo e excelência, resolvemos desafios reais e aceleramos mudanças criando produtos digitais que geram impacto significativo para empresas e pessoas.

## Descrição da vaga

Procuramos Desenvolvedores/as Back-end para criarem produtos digitais para as maiores empresas do Brasil com o intuito de descomplicar o complicado.

O/A Back-end é responsável por desenvolver soluções robustas, escaláveis, de fácil manutenção e de alta performance. É essencial que essa pessoa tenha aptidão para trabalhar em equipe com profissionais de diferentes áreas, saiba se comunicar com clareza e tenha adaptabilidade para lidar com mudanças constantes.

É essencial que essa pessoa tenha aptidão para trabalhar em equipe com profissionais de diferentes áreas, saiba se comunicar com clareza e tenha adaptabilidade para lidar com mudanças constantes.

## Local

Remoto

## Requisitos

**Ferramentas e tecnologias que utilizamos, mas não delimitam nosso trabalho**

Python / Django
Ruby on Rails
C#
Docker
AWS / Google Cloud / Azure
Linux

**Premissas para a posição**

Noções de Arquitetura / Infra-estrutura
Conceitos de Micro-serviços
Cloud
Containerização
API
Versionamento
Testes automatizados
CI / CD

## Benefícios

- Ambiente de trabalho remoto

- Compensação e benefícios alinhados com o padrão de mercado para esta posição

- Bônus de participação proporcional a partir dos resultados

## Contratação

PJ

## Como se candidatar

Candidate-se no [link](https://jobs.polymer.co/igma-digital-product-company/26913).

### Nível

- Pleno

### Regime

- PJ

### Alocação

- Remoto

**Comment by rayanmarcus** [comment]
Essa vaga é de back-end, recomendo postar no repositório de vagas para back.
https://github.com/backend-br/vagas/issues

**Comment by luanargolodev** [comment]
Oi. Sabe de alguma vaga de desenvolvedor front-end?
Estou em busca de recolocação no mercado e à disposição.

Vamos bater um papo?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
