### ISSUE TITLE
[São Paulo] Front-End Developer na [Sysopen]

### ISSUE THREAD

**Issue by emerenda** [frontendbr/vagas#769]
## Descrição da vaga

A Sysopen é parceira das maiores fornecedoras de tecnologia do mundo e líder em soluções para 
Cobrança utilizando a plataforma Microsoft. Procuramos profissionais com experiência em desenvolvimento Front-end Angular que se interessem verdadeiramente em atender seus clientes, para início imediato. 

## Local

São Paulo - Itaim Bibi

## Requisitos

**Obrigatórios:**
Conhecimentos sólidos em Angular 2+, Typescript, Javascript, jQuery, Bootstrap, HTML5, CSS3, API 
Rest, Json 

**Desejáveis:**
Conhecimento em tecnologia de Backend .Net (ASP.NET MVC, Web Forms, C#, VB.NET, WCF) 
Testes unitários e conhecimentos em metodologia ágil serão considerados diferenciais.

## Contratação

PJ

## Nossa empresa

Sysopen, soluções tecnológicas em recuperação de créditos.
Fundada em 1996, a Sysopen é uma empresa de tecnologia, 100% brasileira, altamente especializada em soluções de TI para recuperação de créditos.
Organização, velocidade, eficiência, segurança e resultados concretos:
isso é a inteligência Sysopen.

## Como se candidatar

Por favor envie um email para erik.merenda@sysopen.com.br com seu CV anexado com remuneração pretendida - enviar no assunto: Vaga Angular Github

## Label
- Alocado
- PJ
- Pleno
- Sênior

**Comment by emerenda** [comment]
Vaga aberta.

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
