### ISSUE TITLE
[HOME OFFICE] Full-Stack Developer Especialista na Going2

### ISSUE THREAD

**Issue by gabrielabenite** [frontendbr/vagas#7690]
## Nossa empresa

A Going2 é uma startup que nasceu em 2012, com o propósito de levar tecnologia de ponta para todo o Brasil, focada em criar produtos que tenham como premissa, facilitar a vida das pessoas e empresas, através do desenvolvimento de Aplicativos, Sistemas e dos princípios de IOT (internet das coisas). Hoje, além de atender clientes nacionais também oferecemos nossos serviços para clientes internacionais, como por exemplo no Canada, Suíça e Estados Unidos.

## Descrição da vaga

Buscamos um desenvolvedor Full-Stack especialista que será responsável por auxiliar os projetos em geral da empresa, orientar e ensinar desenvolvedores e atender demandas urgentes. 

## Local

100% Remoto

## Requisitos

- Conhecimento em técnicas de refatoração de código
- Experiência com escrita de documentação de projetos
- Conhecimento em testes automatizados
- Conhecimento em padrões de projeto, componentizacão, modularização e arquitetura em camadas
- Experiência com definições de arquitetura de soluções
- Conhecimento em ambientes Cloud (Google Cloud de preferência)
- Experiência com técnicas e tecnologias de observabilidade de sistemas em ambientes de produção
- Experiência com liderança de equipes de desenvolvimento
- Alto nível de autoconhecimento e autodesenvolvimento (deve ser uma referência dentro da empresa)
- Experiência na resolução de problemas e tarefas de alta complexidade
- Conhecimento e experiência em todos os aspectos da engenharia de software
- Capacidade de justificar processos e valores usando dados e bom poder de convencimento
- Experiência avançada com projetos com as tecnologias: Typescript, Node.Js, React.Js e React Native
- Bibliotecas: Nest.Js, TypeORM
- Banco de dados: MySQL, Stored Procedures e Functions, MongoDB, Redis
- Docker
- Redux
- Funções do Google Cloud, Google Maps

## Benefícios

- Convênio Médico Sul-América (sem custo para titular)
- Convênio Odontológico Sul-América (sem custo para titular)
- Gympass
- Convênio com plataforma de idiomas (Fluency Academy)
- Day-Off de aniversário
- 15 dias de descanso remunerado
- Plano de carreira

## Contratação

PJ

## Como se candidatar

Por favor envie um email para gabriela.benite@going2.com.br com seu CV anexado **E PRETENSÃO SALARIAL PJ** - enviar no assunto: Vaga Full-Stack Especialista

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Especialista

**Comment by censuradho** [comment]
📨 Enviado!!
