### ISSUE TITLE
[REMOTO] Front-end Developer na LevoAPP

### ISSUE THREAD

**Issue by WillianSugiyama** [frontendbr/vagas#7691]
## Nossa empresa

A LEVO é uma empresa de Software as a Service (SaaS) e Banking as a Service (BaaS) para operadores logísticos e entregadores de delivery que movimenta mais de R$ 137 milhões em mais de 300 cidades brasileiras.

## Descrição da vaga

Atuar como Front-End Developer no desenvolvimento de novas plataformas com NextJS e ChackraUI.

## Local

REMOTO

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com NodeJS
- 3 anos de experiência com ReactJS
- Experiência com Typescript
- Experiência com ChackraUI

**Desejáveis:**
- Conhecimentos com NextJS
- Conhecimentos de Boas Práticas, Performance e Testes.

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para willian@levoapp.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dias após cada processo.
E-mail para contato em caso de não haver resposta: willian@levoapp.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by brnms** [comment]
Enviado!

**Comment by censuradho** [comment]
Enviado, espero que possamos marcar uma conversa para que eu possa conhecer um pouco melhor sobre a empresa e vice-versa.

**Comment by pablolucio97** [comment]
Enviado!
