### ISSUE TITLE
[100% REMOTA] FrontEnd - React com Inglês (Sênior) @FDTE

### ISSUE THREAD

**Issue by VanessaBruno3** [frontendbr/vagas#7692]
**Nossa empresa**

Dê uma olhada no nosso Site: http://www.fdte.org.br/
a Fundação é com foco em engenharia - ligada a Poli-USP
o nosso escritório tem o foco em engenharia de software, com modelo de fabrica de software

**Descrição** 
React (CRA/Vite) / NextJS
Redux / Redux Toolkit / ContextAPI
Typescript
Styled-Components
Storybook
Jest / Cypress
WebSocket / MQTT
**Inglês (Intermediário/Avançado)**

**Diferencial:**
Já ter trabalhado com módulo de eventos do javascript
Ter trabalhado com conexão mqtt no front (websocket)
Ter trabalhado com integração com cognito (autenticação)

**Contrato**
PJ + Vantagens:
● 80hs em banco de horas, como descanso, após 1 ano de contrato
● Possibilidade de bônus ate 2x o valor de prestação de serviços (pois, depende de metas)
● Possibilidade de Bolsa MBA (parceria com a FIAP) - sorteio entre a equipe interessado no curso.
● Programa de terapia
● Incentivo financeiro mensal (em cartão de crédito corporativo) para desenvolvimento profissional em compra de livros, cursos, certificações e participação de eventos da área de tecnologia.
● Incentivo financeiro mensal (para home office)

Como se candidatar
Por favor, envie um e mail para [vanessa.bruno@fdte.io](mailto:vanessa.bruno@fdte.io) - com seu CV anexado - enviar no assunto: Vaga Frontend Sênior

Costumamos enviar feedbacks em até 7 dias após cada processo.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
