### ISSUE TITLE
[PORTUGAL] Front-end Developer na INTEGER

### ISSUE THREAD

**Issue by FilipeGM** [frontendbr/vagas#7697]
Oi! 👋

Trabalhar em IT em Portugal é uma das tuas motivações? A INTEGER é a empresa ideal, então!

O meu nome é Filipe Marques e faço parte da INTEGER! A INTEGER é uma empresa de consultoria, portuguesa, com foco em consultoria de IT (Outsourcing) e desenvolvimento de Software e Produto (internamente).

Somos conhecidos no mercado, por darmos um ótimo acompanhamento aos nossos consultores, pela experiência que temos e pela ajuda que damos a profissionais de outros países que querem vir para Portugal!

## Descrição da vaga

As vagas que tenho em aberto atualmente são:

👉 .NET Developer (+5 anos de exp);

👉 Java Developer (+5 anos de exp);

👉 iOS Developer (+5 anos de exp);

👉 QA de Automação (+5 anos de exp);

👉 GoLang Developer (+3 anos de exp);

👉 DevOps Engineer (+3 anos de exp).

Candidatos com menos experiência do que aquela que está especificada, não serão considerados.

## Local

Deverá haver real interesse em vir para PORTUGAL 👍 

Contudo, o começo poderá ser remoto (+ou- 6 meses) 💯 

## Benefícios

- Plano de saúde (para o candidato e família);

- Alojamento nas primeiras duas semanas em PT;

- Acompanhamento durante todo o processo de vinda para PT;

- Acesso gratuito à Udemy;

- Acesso gratuito a plataformas para o desenvolvimento da língua inglesa (e outras);

- Acesso à nossa rede de parcerias - Descontos em serviços, academia, cosmética, restauração, etc...;

## Como se candidatar

Descobre estas e mais oportunidades e os seus requisitos, no nosso site: https://integerconsulting.pt/opportunity/
Envia o teu CV, atualizado e em inglês, para filipe.marques@integer.pt !

Falamos em breve :)

**Comment by pdrch** [comment]
@FilipeGM Todas as vagas apresentadas são para back-end. Está correto?

**Comment by FilipeGM** [comment]
Olá, Pedro,

Sim, apenas uma é para FE, mas achei relevante partilhar as principais vagas que temos atualmente.

Espero que não cause transtorno.

Abraço,
Filipe Marques



Sent from Outlook for Android<https://aka.ms/AAb9ysg>

Filipe Marques
Talent Acquisition Specialist
+351 910385109
***@***.***
R. Julieta Ferrão 10, 8º dto, 1600-131 Lisboa
-Confidential and protected by legal professional privilege-
________________________________

**Comment by paulo70** [comment]
@FilipeGM Qual seria a vaga para Front? Esse espaço seria exclusivo para vagas de Front. Entendo seu papel para a divulgação das demais vagas, mas não faz sentido para esta comunidade

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
