### ISSUE TITLE
[Recife] Desenvolvedor Front-end

### ISSUE THREAD

**Issue by mikejavier** [frontendbr/vagas#77]
## Descrição da vaga

Agile Ecommerce, esta a procura de desenvolvedor Front-End. 

## Local

Escritório, Recife - Pernambuco

## Requisitos

**Obrigatórios:**
HTML5
CSS3
Javascript

**Desejáveis:**
Algum pré-processador
Algum task runner
Versionar seu código (usamos GIT)

## Como se candidatar

Interessados devem enviar c.v. e portfólio para o 
michael@agileecommerce.com.br com o assunto "Vaga de Front-end".

**Comment by LFeh** [comment]
Opa @mikejavier 

CLT? Pleno?

**Comment by mikejavier** [comment]
Fala @LFeh,
junior/pleno
CLT ou PJ

valeu!

**Comment by LFeh** [comment]
;)

**Comment by LFeh** [comment]
Já?

**Comment by mikejavier** [comment]
Já Sim 😁

**Comment by camilatigre** [comment]
@mikejavier 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by mikejavier** [comment]
Não
