### ISSUE TITLE
[São Paulo] Front-End Developer na Streamtel

### ISSUE THREAD

**Issue by rodrigowbazevedo** [frontendbr/vagas#770]
## Descrição da vaga

Atuar no desenvolvimento front-end dos serviços oferecidos pela empresa: Audioconferência, Webconferência e Webcasting.

## Local

Próximo ao metrô Sacomã no Ipiranga.

## Benefícios

- Assistência Média e Odontológica
- Seguro de vida
- Vale refeição
- Vale alimentação
- Vale transporte
- Bônus por resultado

## Requisitos

**Obrigatórios:**
- 1 ano de experiência em desenvolvimento Front-end
- Conhecimentos sólidos em HTML5, CSS3 e JavaScript (ES6)
- experiência em desenvolvimento web responsivo com a metodologia mobile-first

**Desejáveis:**
- Experiência com controle de versão GIT.
- Conhecimento em pré-processadores como SASS ou LESS.
- Conhecimento em Webpack e Babel.

**Diferenciais:**
- Experiência com ReactJs.
- Conhecimento para consumo de APIs Rest.
- Conhecimento em automatizadores de tarefas como Gulp ou Grunt.

## Contratação

Contratação CLT com salário incial de R$ 3.000,00.

## Nossa empresa

[conferenciacorp.com.br](http://conferenciacorp.com.br)

## Como se candidatar
Acesse [https://sites.google.com/view/desenvolvedor-front-end/](https://sites.google.com/view/desenvolvedor-front-end/)

**Comment by ReactGirl** [comment]
Parabens por informar a faixa salarial.

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
