### ISSUE TITLE
[100% 🌎 REMOTO] React / Next – Frontend Developer Sênior na Dog and Pony Studios (🇨🇦 Toronto)

### ISSUE THREAD

**Issue by billaddison** [frontendbr/vagas#7703]
[Dog and Pony Studios](https://www.dogandponystudios.com "Dog and Pony Studios") is a hybrid remote agency headquartered in Toronto, Canada. Our teams work at the cutting edge of technology and design, collaborating with some of the highest-impact organizations on the planet.

We’re looking for a seasoned **Senior Frontend Developer**, experienced in the planning, execution and delivery of exceptional interactive experiences for high-stakes projects and world-renowned organizations. You will thrive in a team of highly intelligent A-players who are experienced and friendly, and who will challenge you to produce your best. When faced with new challenges, you will be expected to proactively seek solutions and to actively pursue a leadership role in the team. 

## What you offer

This role requires a sustained, highly productive person. You will be expected to help lead the team by example, serving as a facilitator between developers, designers, project managers and product owners. You will help mentor junior developers while actively contributing ideas and improvements to our solutions architecture and workflows. As a senior developer, you seek to understand our clients’ business objectives and are able to translate that understanding into suitable technical solutions. You will be working in a highly functional agile environment, interoperating between product owners, project managers, designers and developers within both scrum and kanban workflow methodologies. You will be expected to have mastered the following:

- Advanced React/Next and/or Vue/Nuxt
- Responsive Web Applications (SSR, SSG, SPA)
- Advanced Vanilla JS, ECMAScript and Typescript
- Advanced CSS, DOM, Animations and TailwindCSS Framework
- Knowledge of Utility Styling Frameworks and Atomic Design Structure
- HTML, Web Standards (W3C) and Accessibility (WCAG)
- Web application performance, profiling and testing
- Node and NPM package management
- Build and code-quality tools, test automation
- Architecting modularised, reusable code
- Advanced knowledge of APIs (Rest and GraphQL)
- Understanding of Cloud Platforms (AWS, Azure, Platform.sh, Serverless)
- Headless WordPress (ACF, Rest API), Contentful, DatoCMS
- Understanding of Content Modeling

## What we offer

- **Global Team:** We hire the best professionals from all over the world. Be part of a highly motivated, multidisciplinary team working on cutting-edge digital experiences. 
- **Global Clients:** Work on interesting and complex projects for some of the biggest companies in the world.
- **No Diva Policy:** This is a friendly, collegial, client-centric team focused on delivering world-class products.
- **Remote Office:** Work from home. We’re a hybrid remote agency, and have been since 2008. If you’re in Toronto, you can drop into our headquarters to work as you’d like. And meet your global teammates face-to-face a few times a year when we bring people together.
- **Structured Career Plan:** We recognize great work and reward you accordingly. We provide a structured career path with regular evaluation-based promotions.
- **Paid Vacation:** 3 weeks per year, plus an additional 6-10 days off between Christmas and New Year depending on calendar).
- **Paid Benefits:** Health coverage, without co-pay, with our benefits package.
- **Paid Sick Leave:** Generous yearly allowance for paid sick days.

## Local

Vaga 100% REMOTO 🌎 – Sede da empresa em Toronto, Canada 🇨🇦

## About [Dog and Pony Studios](https://www.dogandponystudios.com "Dog and Pony Studios")

We’re a creative agency based in Toronto, Canada with 20+ years experience serving global corporate clients. Our sector expertise is largely focused on financial institutions. We’re a rapidly growing distributed team of 30+ people spanning Canada, Brazil and Europe. We work across multiple creative disciplines, including digital marketing, design and development, motion graphics, video production and content creation.

## Labels
- React.js
- Next.js
- Wordpress
- Rest API
- TailwindCSS

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
