### ISSUE TITLE
[Hibrido / Belo Horizonte, Minas Gerais, Brazil] Frontend Developer Vue.js (Pleno) (Híbrido - BH) na Coodesh

### ISSUE THREAD

**Issue by blankapf** [frontendbr/vagas#7704]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/desenvolvedora-pleno-or-vuejs-mobile-hibrido-bh-163404056?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A Onfly está em busca de Frontend Developer Vue.js (Pleno)  para compor seu time!</p>
<p>A Onfly é uma startup focada em ajudar as empresas a viajarem melhor! Democratizar a gestão de viagens, reembolsos, descontos em passagens, hotéis e locação de carros em uma experiência completa e simples é foco do nosso negócio. Somos um dos melhores lugares para se trabalhar no Brasil (inclusive somos uma das empresas do Great Place to work)!</p>
<p>Para que alcancemos a meta de crescer exponencialmente, buscamos pessoas que sejam apaixonadas por tecnologia, que desejam estar em um time de alta performance e que queiram crescer muuuuito.</p>
<p>Para a vaga de Desenvolvedor(a) Pleno | Vue.js, buscamos uma pessoa desenvolvedora com foco em front-end (Mobile). Além disso, buscamos alguém que também seja dinâmico(a), que saiba trabalhar em equipe e que se conecte com nossa cultura e valores.</p>
## Onfly: 
 <p>A Onfly oferece uma solução "all-in-one" com gestão de viagens (aéreo, hotel e carros), despesas e cartão corporativo em uma única plataforma digital. Com intensivo uso de tecnologia e uma boa dose de calor humano, elevamos ao máximo a gestão de viagens das empresas, trazendo conforto e produtividade para os colaboradores e segurança e economia para as empresas.  Simplifique, vá de Onfly!</p></p>

 ## Habilidades: 
 - Vue.js 
- Orientação a Objetos 
- Flutter 
- Quasar 
- Vuetify 
- REST APIs 
- SCRUM
## Local: 
 Belo Horizonte, Minas Gerais, Brazil
## Requisitos: 
 - Experiência com Vue.js; 
- Conhecimento em orientação à objetos; 
- Experiência com desenvolvimento mobile (em especial, WebView); 
- Experiência em publicações na Apple Store e Play Store; 
- Conhecimento em bibliotecas de estilização (Quasar, Vuetify, BootstrapVue, etc); 
- Vivência com testes unitários, widgets e integração; 
- Experiência em repositórios Git; 
- Experiência em consumo de API rest; 
- Experiência com metodologias de desenvolvimento ágil (Scrum ou Kanban).

## Benefícios: 
 - Regime Híbrido de trabalho (2 dias na semana presenciais e o restante remoto); 
- Horário de trabalho flexível; 
- Vale refeição em cartão flexível R$28 (sem desconto de 6%); 
- Vale transporte em cartão flexível (sem desconto de 6%); 
- Plano de Saúde Unimed, sem coparticipação e sem mensalidade para o Onflyer (por nossa conta :D); 
- Plano Odontológico (desconto na mensalidade) 
- Desconto Farmácia; 
- No dress code; 
- Benefício de Psicoterapia on-line (Zenklub e Vittude); 
- Pagamos metade da sua academia (TotalPass); 
- Bolsa de 50% para estudos de idiomas; 
- Descontos em Graduações e Pós-graduações (UNA e UNIBH); 
- Pacote de descontos Clube Certo sem valor de mensalidade; 
- Seguro de vida.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Developer Vue.js (Pleno) (Híbrido - BH) na Onfly](https://coodesh.com/jobs/desenvolvedora-pleno-or-vuejs-mobile-hibrido-bh-163404056?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Categoria
Mobile

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
