### ISSUE TITLE
REMOTO - Front-end Developer na Hepta

### ISSUE THREAD

**Issue by GitMateusBruno** [frontendbr/vagas#7705]
## Nossa empresa

Estamos buscando um(a) profissional para se juntar à nossa equipe na Hepta tecnologia. Se você é apaixonado(a) por criar soluções e possui habilidades excepcionais em JavaScript e desenvolvimento  Ionic, com experiência em sistemas legaddos/não responsivos e está procurando por uma oportunidade para desenvolver suas habilidades e crescer em uma empresa em expansão, então deu match 😍

Como parte da nossa equipe, você terá a oportunidade de trabalhar em um projeto desafiador, porém muito interessante, que possibilitará autonomia e experiências incríveis. Ah irá atuar em conjunto com um time multidisciplinar e bastante colaborativo 🚀

## Descrição da vaga

desenvolvimento de aplicativos móveis em Ionic (JavaScript)
HTML 5 e CSS3

## Local

Remoto 

## Requisitos

**Obrigatórios:**
- 05 anos de experiência como Dev;
- Formação superior completa;
- Uma ou duas das seguinte certificações:

 Para atuar como Desenvolvedor:
CSD – Certified Scrum Developer;
PSD – Professional Scrum Developer;

Para atuar como Scrum Master no time, além de desenvolvedor:
a) Scrum.Org: Professional Scrum Master – PSM:
PSM I; PSM II ou PSM III;
b) Scrum Alliance: Certified Scrum Master – CSM;
c) Scrum Study: Scrum Master Certified – SMC
d) EXIN: Agile Scrum Master - ASM

*Caso não possua não há problemas, nós damos um prazo de 30 dias, após efetivação para tirar. Atenção a empresa não custeia, apenas dar o prazo*

## Benefícios

- Plano de saúde parcialmente custeado pela empresa.
- VR ou VA
- Auxílio Home Office

## Contratação

CLT

## Como se candidatar

Por favor se cadastre através do link: https://www.hepta.com.br/carreiras/oportunidades/1764

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 24hs após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
