### ISSUE TITLE
[Belo Horizonte] Frontend Developer na Coodesh

### ISSUE THREAD

**Issue by blankapf** [frontendbr/vagas#7706]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/desenvolvedor-front-114507663?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A For People Software Ltda está em busca de Frontend Developer para compor seu time!</p>
<p>Somos uma fábrica de softwares com um objetivo muito claro: queremos tornar a experiência de trabalho das pessoas o mais simples, orgânica e agradável possível para que elas possam ser o melhor que puderem quando estiverem trabalhando. Para isso, desenvolvemos sistemas inclusivos, responsivos e com alta tecnologia embarcada para transformar a vida de pessoas e empresas de maneira sustentável e lucrativa. Nós da Ortep, oferecemos aos nossos clientes e parceiros tecnologia de ponta para operacionalizar estratégias focadas nos colaboradores e uma parceria que vai além dos contratos. Afinal, o que nos motiva são as pessoas.</p>
<p>O papel do nosso(a) jovem jedi Frontend Developer (Pleno) será:</p>
<ul>
<li>Desenvolver sistemas web junto ao nosso time utilizando React e API Rest;</li>
<li>Escrever códigos limpos, de alta qualidade e fácil manutenção;</li>
<li>Criar componentes reutilizáveis e funcionalidades visando a melhor experiência possível para o usuário;</li>
<li>Utilização de metodologia Scrum em projetos;</li>
<li>Correção de bugs;</li>
<li>Apoiar equipe de desenvolvimento e testes no dia-a-dia.</li>
</ul>
## For People Software Ltda: 
 <p>Somos uma fábrica de softwares com um objetivo muito claro: queremos tornar a experiência de trabalho das pessoas o mais simples, orgânica e agradável possível para que elas possam ser o melhor que puderem quando estiverem trabalhando.</p>
<p>Para isso, desenvolvemos sistemas inclusivos, responsivos e com alta tecnologia embarcada para transformar a vida de pessoas e empresas de maneira sustentável e lucrativa.</p><a href='https://coodesh.com/companies/for-people-software-ltda'>Veja mais no site</a>

 ## Habilidades: 
 - HTML 5 
- GIT 
- Typescript
## Local: 
 Belo Horizonte
## Requisitos: 
 - Conhecimento avançado em front-end, utilizando React; 
- Conhecimento em componetização de objetos; 
- Conhecimento avançado de Typescript; 
- Arquitetura Front-end; 
- Versionamento de código (Git); 
- Integração do front-end em React com a API (REST); 
- CSS; 
- HTML 5; 
- Dominar controle de versão usando GIT; 
- Orientação à objetos.

## Benefícios: 
 - Vale transporte ou combustível (para te ajudar no deslocamento); 
- Parceria com 4 restaurantes (comidinha bem feita para alegrar seu dia); 
- Plano de Saúde Unimed (Co participativo apartamento, porque saúde em 1º lugar!); 
- Plano odontológico Unimed (para o sorrisão ficar ainda mais bonito!) 
- Parceria com universidades e escola técnicas (Uniube, Cotemig e Faculdade Batista, para você se aprimorar ainda mais.); 
- Gympass (bora dar manutenção na disposição?); 
- Day Off (para você comemorar seu aniversário do seu jeito!); 
- No Dress Code (melhor coisa, principalmente no calor); 
- Convenio com Sesc (hora de pegar um bronze no clube, chalés e ainda poder fazer cursos.); 
- Convenio com Farmácia Araújo (comprinhas consignadas, check!).
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Developer na For People Software Ltda](https://coodesh.com/jobs/desenvolvedor-front-114507663?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Regime
CLT
#### Categoria
Front-End

**Comment by pablolucio97** [comment]
Enviado!

**Comment by soaresrodrigo** [comment]
Enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
