### ISSUE TITLE
[Internacional e Remoto] Desenvolvedor(a) Fullstack com foco em Frontend - Turing.com

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#7707]
## Sobre
Uma empresa crescendo rapidamente, que está desenvolvendo uma plataforma baseada em inteligência artificial para que empresas terceirizadas que cuidam de telhados consigam trabalhos maiores, aprovações de seguradoras mais rápido e sejam pagos de uma só vez.

O desenvolvedor deverá construir novos recursos para o dashboard web da plataforma de uso interno e para o aplicativo mobile usado em campo. A empresa ajuda trabalhadores e empresas de serviços terceirizados a lidar com estimativas e orçamentos, suplementação, documentação de permissão para execução de trabalho, fechamentos e gerenciamento financeiro de maneira simplificada e tranquila. Essa é uma vaga de trabalho online de longo prazo e tempo integral, que requer ao menos 3 horas de sobreposição com o fuso horário PST, sendo ideal para desenvolvedores brasileiros que querem mudar sua rotina e trabalhar com profissionais de outros países.

## Responsabilidades:

- Trabalhar junto com os outros desenvolvedores da equipe para melhorar a qualidade das suas soluções
- Construir stacks escaláveis, responsivas e bem documentadas
- Colaborar com outros para modelar e aprimorar o stream de dados rumo à aplicação front-end
- Ajudar a criar um front-end eficiente e amigável para a aplicação

##Requisitos:

- Bacharelado ou Mestrado em Engenharia ou Ciência da Computação (ou experiência equivalente)
- Ao menos 3 anos de experiência relevante como desenvolvedor full stack ou front-end
- Experiência comprovável trabalhando com React, React Native e JavaScript
- Familiaridade com Firebase e Next.js será visto como um diferencial
- Será vantajoso possuir alguma experiência com TailwindCSS e Node.js
- Boa comunicação oral e escrita em inglês

## Como se candidatar

Clique [aqui](https://bit.ly/443o2zn) para acessar a vaga completa no site da Turing e se candidatar

#### Alocação
- Remoto

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
