### ISSUE TITLE
[Remoto e internacional] Engenheiro de Software Sênior - Turing.com 

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#7708]
## Sobre
Uma empresa sediada nos EUA, que está desenvolvendo uma incrível plataforma de mudanças sociais voltada para uma audiência multinacional, está procurando contratar um Engenheiro de Software Sênior.
O engenheiro será responsável pelo gerenciamento do projeto técnico e por sua refatoração. A empresa está determinada a fomentar mudanças sociais positivas e de longo impacto por todo o mundo, de maneira a ajudar seus usuários a se informarem sobre campanhas sociais acontecendo em diversos países e regiões. Ela conseguiu arrecadar mais de US$70 milhões durante sua rodada de investimentos da Série D. Essa vaga de trabalho online e de período integral requer uma sobreposição significativa com o fuso horário PST, sendo uma ótima oportunidade para engenheiros de software brasileiros que querem investir em construir uma carreira internacional enquanto recebem em dólar. 

## Responsabilidades:

- Manter o website e realizar atualizações básicas
- Apoiar a equipe existente e trabalhar lado a lado com seus colegas
- Criar e oferecer novas funcionalidades aos usuários
- Escalar as funcionalidades atuais para adequá-las ao aumento em seu uso
- Trabalhar em todas as camadas da stack, incluindo front-end, back-end e infraestrutura
- Participar de processos de otimização em andamento
- Trabalhar em um ambiente de desenvolvimento Agile
- Encorajar a partilha de conhecimento através de coaching e mentoria
- Trabalhar diariamente com gerentes de produto, engenheiros e designers UX

## Requisitos:

- Pelo menos 4 anos de experiência relevante como engenheiro de software
- Vasta experiência trabalhando com React, Agile, Elixir e GraphQL
- Será vantajoso possuir experiência com unit tests
- Proficiência com diferentes ferramentas e metodologias de teste
- Experiência comprovável com Git ou outros sistemas distribuídos de controle de versão de código
- Vasto conhecimento sobre APM ou ferramentas de desenvolvimento de browser
- Experiência elaborando o design e criando sistemas de alta performance
- Familiaridade trabalhando com SQL e bancos de dados, preferencialmente com MySQL, Redis e Redshift
- É recomendável possuir experiência com práticas de programação extrema e desenvolvimento orientado por testes
- Experiência trabalhando ou realizando integrações com portais de pagamento online (Braintree, Stripe) será um diferencial
- Experiência testando bibliotecas Mocha, GraphQL, React Testing Library, Jest, Sinon.js e RSpec será vantajoso
- Experiência com JavaScript, TypeScript, Ruby on Rails e Ruby é desejável
- Experiência trabalhando com a metodologia Agile será vista como um diferencial
- É recomendável possuir experiência liderando uma equipe, partilhando conhecimento e oferecendo mentoria
- Será vantajoso possuir alguma experiência com a suite AWS
- Ótima comunicação em inglês, tanto falado quanto escrito

## Como se candidatar

Clique [aqui](https://bit.ly/3LutZx1) para visualizar a vaga completa no site da Turing e iniciar o processo

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
