### ISSUE TITLE
[Remoto e Internacional] Desenvolvedor Web Front-end Júnior / Pleno na Turing

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#7709]
## Sobre
Uma empresa sediada nos Estados Unidos, que está desenvolvendo uma plataforma de remessa funcional para auxiliar as empresas de e-commerce no gerenciamento de suas operações de entrega, está procurando contratar um Desenvolvedor Web Front-end Júnior.

O desenvolvedor será responsável por garantir a alta produtividade, confiabilidade, escalabilidade e desempenho da plataforma. A empresa está fornecendo às empresas de e-commerce um software de remessa multi transportador bem equipado que lhes permitirá expandir seus negócios. Esta posição requer mais de 6 horas de sobreposição com o fuso horário PST, sendo uma vaga de trabalho online ideal para desenvolvedores brasileiros que almejam construir uma carreira internacional. A empresa conseguiu arrecadar mais de US$150 milhões durante a rodada de investimentos da Série E.

## Responsabilidades:

- Ajudar na implementação do desenvolvimento de novas páginas end-to-end
- Desenvolver sites impressionantes, dinâmicos e responsivos trabalhando juntamente com a equipe de design
- Identificar, fazer sugestões e liderar ou ajudar outras pessoas na criação da consistência e aparência do site enquanto trabalha com design
- Participar de revisões de design e fornecer feedback antecipado à equipe de design para ajudá-los a simplificar seus projetos e obter uma melhor execução
- Juntamente com a equipe de design, desenvolver uma ferramenta para criar interfaces interativas, protótipos rápidos de ideias de design e designs responsivos e acessíveis
- Atualizar seu conhecimento sobre práticas recomendadas de alto desempenho e executar testes de desempenho com frequência, além de promover consistentemente o uso dos desenvolvimentos mais recentes em HTML, CSS e JavaScript

## Requisitos:

- Pelo menos 3 anos de experiência relevante como desenvolvedor front-end
- Ampla experiência trabalhando com React e WordPress
- Amplo conhecimento sobre tecnologias web e desenvolvimentos mais recentes nos ecossistemas HTML, CSS e Javascript
- Construir e manter uma codebase utilizando o framework React do client-side
- Experiência no desenvolvimento de sites sofisticados baseados em WordPress 
- Experiência no desenvolvimento de uma solução baseada em CMS
- Experiência bem sucedida criando uma biblioteca de estilo extensível e organizando o código para manutenção e reutilização
- Conhecimento abrangente sobre as práticas recomendadas para sites de alto desempenho
- Familiaridade com a utilização dos recursos do navegador e do dispositivo para criar experiências responsivas na Web, bem como com o uso de tecnologias avançadas e práticas recomendadas 
- Demonstrar interesse e compreensão sobre automação de teste e procedimentos de segurança
- Estar profundamente ciente das demandas do cliente, além de demonstrar paixão pelo sucesso do cliente e capacidade de interagir com membros não técnicos da equipe
- É recomendável ter alguma experiência com fluxo web, manipulação de solicitações assíncronas, atualizações parciais de página e AJAX
- É desejável ter alguma familiaridade ou experiência com SEO nas seguintes ferramentas: Gerenciador de tags do Google, Google Analytics, Segment, Optimizely e Gatsby
- Boa comunicação em inglês escrito e falado 

## Como se candidatar

Clique [neste link](https://bit.ly/3LziOnP) para ser redirecionado para o site da Turing, conferir o descritivo completo e iniciar o processo de candidatura.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
