### ISSUE TITLE
[Curitiba - PR] Analista Desenvolvedor Full Stack na Topdata

### ISSUE THREAD

**Issue by NovareRH** [frontendbr/vagas#7713]
## Nosso cliente:

A Topdata é uma empresa brasileira que há 30 anos se dedica a fornecer soluções inovadoras para os mercados de controle de ponto e de controle de acesso. A empresa é reconhecida pela qualidade dos seus produtos, que incluem catracas, equipamentos para registro de ponto de funcionários e software de tratamento de ponto em nuvem. 

A Topdata está em constante evolução, trabalhando com uma equipe motivada e acompanhando os avanços da tecnologia para oferecer as melhores soluções para os seus clientes.

## Descrição da vaga:

‍✔️ TAREFAS:

- Desenvolver sistemas de software para as soluções da Topdata.
- Escrever código de qualidade, bem documentado, utilizando boas práticas de programação.
- Identificar e atuar em oportunidades de evolução das soluções.
- Analisar, documentar, implementar e testar requisitos funcionais e não funcionais.

﻿👊🏽RESPONSABILIDADES:

- Entregar soluções de alta disponibilidade, escalabilidade e segurança,
- Multiplicar o conhecimento com o time de desenvolvimento de forma ativa e colaborativa,
- Contribuir ativamente com ideias para o negócio.

Cargo:Analista Desenvolvedor Full Stack
Tipo de Contrato:CLT (Efetivo)
Área profissional:Informática/T.I.
Jornada:De seg a qui das 8 as 18:09h e sex das 8 as 17h
Número de vagas:1
Salário:A partir de R$ 7.000,00
Benefícios:- Participação nos lucros;
- Vale refeição de R$ 550,00/mês;
- Viagem por tempo de casa;
- Ginástica Laboral;
- Kit maternidade/paternidade;
- Estacionamento próprio;
- Convênio com instituições de ensino, cultural e social.

Após o período de experiência: 
- Assistência médica Unimed 100% custeado pela empresa;
- Assistência odontológica; 
- Convênio farmácia;

Requisitos
Escolaridade mínima:
Graduação - Cursando - Obrigatório

Experiências e qualificações:
⏱️ EXPERIÊNCIAS, COMPETÊNCIAS E CONHECIMENTOS:

- Experiência:
Desenvolvimento com Java EE,
Aplicações Front-End: AngularJS, JavaScript, Bootstrap, HTML 5/CSS 3;
Aplicações Back-End: Spring Boot/Spring Data/Spring Security, API RestFull;
Mensageria: Kafka ou RabbitMQ ou SQS;
Metodologia Agile,
Banco de dados relacionais: SQL Server. 

- Conhecimento em Programação Orientada a Objetos.

Diferencial:
- Experiência:
Ambiente Cloud (Azure Services);

- Conhecimento:
Containers Docker e de comandos Linux e Shell Script
Banco de dados não-relacionais: Firebase ou MongoDB ou outro,
Jasper Reports, Angular v.2+, Ionic, Redis Cache, ORM/Hibernate, protocolo HTTP.

😀 DESAFIOS:

Desenvolver soluções, contribuindo colaborativamente com o time de desenvolvimento e com os projetos e tecnologias atuais da empresa. 

🚀O QUE BUSCAMOS:

- Comunicação fluida e clara
- Gostar de colaborar
- Perfil analítico
- Gostar e usar a inovação
- Maturidade profissional
- Gostar de trabalhar em equipe e de forma presencial
- Buscar constante aprendizado e novos conhecimentos
- Ter prazer em programar

🚀 Para mais informações ou inscrição:
https://novarerh.selecty.com.br/vaga/65/vaga-para-analista-desenvolvedor-fullstack-curitiba-em-curitiba-pr 
Ou entre em contato pelo WhatsApp através do link: https://api.whatsapp.com/send?l=pt_BR&phone=551598302947

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
