### ISSUE TITLE
[REMOTO] React.js e Angular Front-end Developer @ Dataseed

### ISSUE THREAD

**Issue by alvarogomes** [frontendbr/vagas#7714]
## VAGA

Estamos contratando desenvolvedores Frontend Angular e React.Js.

Buscamos desenvolvedores com um perfil pleno/sênior para integrar o nosso time de desenvolvimento, e esperamos que você:

* Desenvolver código limpo, testável e de fácil manutenção.
* Contribuir com todo o processo de desenvolvimento de software.
* Implementar features novas e investigar problemas existentes.
* Contribuir nas discussões técnicas sobre os desafios encontrados.
* Ser agíl para demandas emergenciais.

## Requisitos

Obrigatórios:

* 3 anos de experiência com React JS, Angular (Obrigatório), TypeScript.
* Experiência com Frameworks React.js: Next.js, Taillwind, Redux ou Redux-toolkit, axios
* Experiência com testes unitários e de integração.
* Experiência em pegar prototipos Figma e converter em componentes React.js/Angular
* Conhecimento em Design Patterns;

* Início imediato

Com possibilidade de integrar o time para mais projetos Nacionais e Internacionais.

## Contratação
100% REMOTO

Horário: 6 horas por dia 
Modo de contratação = PJ

## Como se candidatar

Envie um e-mail com o CV para se candidatar: recrutamento@dataseed.de
Obs: Coloque no titulo -> React.js e Angular Front-end Developer

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
