### ISSUE TITLE
[Internacional e Remoto] Front-End Engineer na Turing

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#7715]
## Sobre
A fast-growing company that focuses on offering exceptional delivery experiences to people is looking to hire a Front-End Engineer. The engineer will utilize solid expertise in building enterprise-grade web applications to implement the web components of the platform. The company is revolutionizing delivery operations and is used by some of the world’s largest food, beverage, courier, energy, and field service brands. The selected candidate will have the opportunity to join a team of smart, committed, driven, and solutions-oriented individuals to build robust, simplified products.

## Job Responsibilities:

- Work on implementing the web components of the platform
- Encourage existing users relying on the web application to conduct business-critical functions
- Work with the back-end engineering and design team to scale the system for optimal performance 
- Create automated tests to validate critical application features 
- Create efficient user-facing features for the web application     
- Analyze big data and present it in a highly responsive and visually appealing format
- Ensure the technical feasibility of UI/UX designs
- Optimize application for maximum performance and scalability
- Work closely with the product and designers to deliver an enhanced user experience 

## Job Requirements:

- Bachelor’s/Master’s degree in Engineering, Computer Science (or equivalent experience)
- At least 3+ years of relevant experience as a front-end engineer
- Expertise in building enterprise-grade web applications
- Professional experience in front-end development
- Proficiency with JavaScript, HTML, and CSS
- Solid understanding of modern JavaScript libraries and frameworks
- Strong design and UX sensibilities
- Expert skills in interacting with REST API to query/present data
- Vast knowledge of React, Polymer, Linux, and shell scripting is a plus

## Como se candidatar

Acesse o site da [Turing](https://bit.ly/3AXtR49) para conferir o descritivo completo e aplicar para a vaga.

**Obs:** esta vaga está sendo publicada pela [Remotar](https://remotar.com.br/?utm_source=github) em nome da Turing. A Remotar é uma plataforma de vagas remotas que ajuda seus clientes com a divulgação das posições abertas. No entanto, não somos responsáveis pelo processo seletivo das mesmas. 

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
