### ISSUE TITLE
[Belo Horizonte] Web Developer na viajar.tur

### ISSUE THREAD

**Issue by saulolaranjeira** [frontendbr/vagas#772]

**Comment by ReactGirl** [comment]
Requer 1 ano de experiência pra ganhar mil reais?

**Comment by LFeh** [comment]
Poisé...

**Comment by lucasfernandes** [comment]
Este valor está muito abaixo do aceitável.

**Comment by NataliaAvila** [comment]
Praticamente um salário para estagio.

**Comment by fejaum** [comment]
Dá uma tristeza ver vagas assim...
