### ISSUE TITLE
[Internacional e Remoto] Desenvolvedor(a) Front-end React na turing.com

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#7720]
## Sobre
Uma empresa, sediada nos EUA, que está construindo uma plataforma baseada na web que ajuda negócios a encurtarem suas tarefas administrativas, poupar dinheiro, eliminar erros e evitar perder prazos está procurando contratar um Desenvolvedor React Front-end. O desenvolvedor será encarregado de levar rapidamente os produtos ao mercado e terá papel fundamental no desenvolvimento dos sistemas. A avançada tecnologia da empresa ajuda negócios e escritórios de advocacia a assimilar relatórios, gerenciar e organizar arquivos (internos e externos) e manter tudo em ordem. Durante sua rodada de investimentos Semente, a empresa conseguiu levantar mais de U$5 milhões em financiamento.

## Responsabilidades:

- Construir UX e UI com bom design para melhorar a vida dos usuários
- Entender um dado problema, criar um plano para solucioná-lo e então agir de acordo
- Oferecer aos usuários as soluções que eles precisam
- Implementar avanços significativos em processos que, de outro forma, poderiam ser problemáticos

## Requerimentos:

- Bacharelado ou Mestrado em Engenharia ou Ciência da Computação (ou experiência equivalente)
- Pelo menos 6 anos de experiência relevante como desenvolvedor de software
- Vasta experiência trabalhando com React, Redux e Typescript
- Ao menos 3 anos de experiência com HTML, CSS, Less e JavaScript
- Ao menos 2 anos usando frameworks e tecnologias de código aberto para criar produtos impactantes
- Possuir uma mentalidade voltada para design
- Capacidade de escrever e implementar código no mesmo dia, além de conhecer os sistemas e práticas que possibilitam isso
- Será um diferencial possuir experiência com Python
- Fluência em inglês, verbal e escrito

## Como se candidatar

Acesse o site da [Turing](https://bit.ly/44Lscfu) para conferir o descritivo completo e aplicar para a vaga.

Obs: esta vaga está sendo publicada pela [Remotar](https://remotar.com.br/?utm_source=github) em nome da Turing. A Remotar é uma plataforma de vagas remotas que ajuda seus clientes com a divulgação das posições abertas. No entanto, não somos responsáveis pelo processo seletivo das mesmas.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
