### ISSUE TITLE
(REMOTO) Dev. Mobile Kotlin e Swift 

### ISSUE THREAD

**Issue by MariaJuliaRicostiG2** [frontendbr/vagas#7722]
(REMOTO) Front-End Developer Mobile Kotlin e Swift - GOING2

## Nossa empresa

A Going2 é uma startup que nasceu em 2012, com o propósito de levar tecnologia de ponta para todo o Brasil, focada em criar produtos que tenham como premissa, facilitar a vida das pessoas e empresas, através do desenvolvimento de Aplicativos, Sistemas e dos princípios de IOT (internet das coisas). Hoje, além de atender clientes nacionais também oferecemos nossos serviços para clientes internacionais, como por exemplo no Canada, Suíça e Estados Unidos.

## Descrição da vaga

O desenvolvedor contratado atuará em um projeto alocado em um cliente, de prazo determinado (2 meses), full-time, realizando correções e novas features.

## Local

REMOTO

## Requisitos

**Obrigatórios:**
- Experiência com Desenvolvimento nativo em Kotlin e Swift;

## Contratação

PJ (contrato de 2 meses)

## Como se candidatar

Por favor envie um e-mail para mariajulia.ricosti@going2.com.br  com seu CV anexado E PRETENSÃO SALARIAL PJ - enviar no assunto: Vaga Front-End Kotlin e Swift

#### Alocação

- Remoto

#### Regime

- Freela
- PJ

#### Nível

- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
