### ISSUE TITLE
[Remoto e Internacional] React & React Native Developer na Lemon.io (entre U$S 5k e U$D 9k)

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#7723]
## About
Are you a talented developer looking for a remote job that lets you showcase your skills while enjoying better compensation and career growth? Look no further than Lemon.io, the marketplace that connects you with hand-picked startups in the US and Europe.

**You'll love working with us, because:**

- We understand that respecting your time is key to your success, which is why we connect you with teams that won't micromanage or require time trackers.
- You can earn $5k - $9k monthly (the rate may differ due to skill and/or level of experience), and we've already paid out over $10M to our engineers.
- With flexible working hours and the ability to work asynchronously, you can choose a schedule that works best for you.
- Say goodbye to project managers, and hello to direct communication with clients. Most of them have technical backgrounds. Sounds good, yeah?
- No more hunting for clients or negotiating rates - let us handle the business side of things so you can focus on what you do best.
- Enjoy the fast-paced startup environment that will keep you motivated and engaged.
- Pass the interviews now and start working when you're ready - even if that's a few months down the line.
- We'll manually find you the best project to match your skills and preferences.
- Connect with the best developers in the world through our community.

## Requirements:

- 4+ years of commercial work experience in software development
- Expert-level knowledge of React & React Native
- Hands-on experience with REST APIs and ES6
- Experience in React Native application deployment to App Store and Google
- Good command of English, both written and spoken, as you’ll be communicating with clients directly
- Strong organizational skills — ability to work full-time remotely with no supervision
- Responsibility — we want to trust you
- Soft skills — we don’t ask you find a topic for a small talk, but being just polite is OK

## Salário
$5,000.00 a $9,000.00 USD / Mensal

## Como se candidatar

Clique no [link](https://remotar.com.br/job/15289/lemon.io/react-and-react-native-developer?utm_source=github) para conferir o descritivo completo e aplicar.

Importante: esta vaga está sendo anunciada pela Remotar em nome da Lemon.io. No entanto, vale destacar que não somos responsáveis pelo processo seletivo. 

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by Joaopdev** [comment]
O link está fora do ar.

![image](https://github.com/frontendbr/vagas/assets/79816024/b4efd802-46fa-4b89-963c-6de8d5c74042)

**Comment by tatidirienzo** [comment]
> O link está fora do ar.
> 
> ![image](https://user-images.githubusercontent.com/79816024/239233190-b4efd802-46fa-4b89-963c-6de8d5c74042.png)

ajustado. Obrigada por avisar :)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
