### ISSUE TITLE
[Remoto e Internacional] Fulls-stack (React/Node) Developer na Lemon.io (entre U$D 5k e U$D 9k)

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#7724]
## About
Are you a talented developer looking for a remote job that lets you showcase your skills while enjoying better compensation and career growth? Look no further than Lemon.io, the marketplace that connects you with hand-picked startups in the US and Europe.

**You'll love working with us, because:**

- We understand that respecting your time is key to your success, which is why we connect you with teams that won't micromanage or require time trackers.
- You can earn $5k - $9k monthly (the rate may differ due to skill and/or level of experience), and we've already paid out over $10M to our engineers.
- With flexible working hours and the ability to work asynchronously, you can choose a schedule that works best for you.
- Say goodbye to project managers, and hello to direct communication with clients. Most of them have technical backgrounds. Sounds good, yeah?
- No more hunting for clients or negotiating rates - let us handle the business side of things so you can focus on what you do best.
- Enjoy the fast-paced startup environment that will keep you motivated and engaged.
- Pass the interviews now and start working when you're ready - even if that's a few months down the line.
- We'll manually find you the best project to match your skills and preferences.
- Connect with the best developers in the world through our community.

## Requirements:

- 5+ years of software development experience
- Strong knowledge of JavaScript (Core, DOM APIs)
- 3+ years of experience with Node.js and React.js
- 2+ years of experience with Typescript
- Understanding of and practical experience with AWS
- Understanding of and practical experience with SOLID principles and GOF patterns
- Understanding of CI principles
- Experience with React Native and Next would be a plus
- Good command of English, both written and spoken, as you’ll be communicating with clients directly

## Salário
$5,000.00 a $9,000.00 USD / Mensal

## Como se candidatar

Clique no [link](https://remotar.com.br/job/16076/lemon.io/fulls-stack-(reactnode)-developer?utm_source=github) para conferir o descritivo completo e aplicar.

Importante: esta vaga está sendo anunciada pela Remotar em nome da Lemon.io. No entanto, vale destacar que não somos responsáveis pelo processo seletivo. 

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
