### ISSUE TITLE
[Remoto e Internacional] Desenvolvedor WordPress na Turing.com

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#7725]
## Sobre
Uma empresa crescendo rapidamente, que atende tanto indivíduos quanto empresas ao parear consumidores com uma ampla rede de prestadores de serviços na área de remoção de lixo e bugigangas, está procurando contratar um Desenvolvedor WordPress. O desenvolvedor será responsável por identificar a dívida técnica e fazer recomendações para sua redução futura. A empresa se colocou como líder da indústria em termos de remoção de lixo e bugigangas, logística reversa de devolução, excelentes serviços de montagem e muito mais. Essa é uma oportunidade empolgante para desenvolvedores que querem mostrar do que são capazes enquanto trabalham junto com outros bons profissionais. 

## Responsabilidades:

- Criar, elaborar e otimizar segundo as melhores práticas de SEO para websites WordPress com foco em promover uma experiência do usuário escalável, altas taxas de conversão, velocidade e performance
- Ajudar a atualizar e manter o website e os blogs
- Realizar brainstorms para criação de novas e criativas estratégias de crescimento para os produtos da empresa
- Planejar, executar e mensurar os experimentos e testes de conversão
- Colaborar com equipes internas para criar landing pages e otimizar a experiência do usuário
- Instrumentar pontos de conversão e otimizar o funil do usuário incluindo landing pages

## Requerimentos:

- Bacharelado ou Mestrado em Engenharia ou Ciência da Computação (ou experiência equivalente)
- Ao menos 3 anos de experiência relevante como desenvolvedor de software
- Vasta experiência com desenvolvimento WordPress
- Proficiência com WordPress e redação de conteúdo com foco no SEO e design
- Experiência comprovável em integração, formatação e implementação de analytics e anúncios
- Experiência com integrações e instalação de soluções de terceiros (mailchimp, hubspot, etc.)
- Vasta experiência com CSS/HTML/PHP/JavaScript
- Experiência com a suíte da Adobe e design gráfico
- Inglês fluente, oral e escrito

## Como se candidatar

Acesse o site da [Turing](https://bit.ly/3Bcjp94) para conferir o descritivo completo e aplicar para a vaga.

Obs: esta vaga está sendo publicada pela [Remotar](https://remotar.com.br/?utm_source=github) em nome da Turing. A Remotar é uma plataforma de vagas remotas que ajuda seus clientes com a divulgação das posições abertas. No entanto, não somos responsáveis pelo processo seletivo das mesmas.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
