### ISSUE TITLE
[Remoto e Internacional] Desenvolvedor(a) Web Front-end na Turing.com

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#7726]
## Sobre
Uma empresa bem estabelecida, que está desenvolvendo uma plataforma de trading de primeira classe para ajudar os usuários a investirem de forma inteligente, está procurando contratar um Desenvolvedor Web Front-end. O candidato selecionado será responsável pelo perfil de desempenho, bem como por encontrar gargalos e resolvê-los. A plataforma de última geração da empresa fornece aos usuários acesso às ferramentas de gráficos mais sofisticadas, que contam com indicadores personalizáveis e outras tecnologias. Esta é uma boa vaga de trabalho online para desenvolvedores brasileiros que desejam mostrar seus talentos enquanto criam soluções escaláveis e impactantes.

## Responsabilidades:

- Utilizar as tecnologias e técnicas mais recentes para defender internamente e apoiar a adoção das mesmas em uma equipe global de desenvolvimento de software
- Certificar-se de que os resultados sejam fáceis de usar e visualmente atraentes
- Ajudar a criar soluções para o cliente e fornecer uma interface de usuário moderna e altamente responsiva baseada na Web
- Colaborar com equipes da área de produtos e profissionais de engenharia

## Requisitos:

- Bacharelado ou Mestrado em Engenharia ou Ciência da Computação (ou experiência equivalente)
- 5 anos de experiência relevante como desenvolvedor front-end ou desenvolvedor web
- Experiência trabalhando com React 17+ e TypeScript
- Vasta experiência e compreensão profunda sobre programação do React
- Ampla experiência com RxJS para construir o estado do aplicativo
- Experiência trabalhando na criação de interface do usuário com componentes estilizados
- Conhecimento prático sobre Git para controle de código-fonte
- É recomendável ter alguma experiência escrevendo integration tests com Cypress ou tecnologias semelhantes
- É desejável ter uma profunda compreensão do Jira para gerenciamento de histórias e defeitos
- Boas habilidades de comunicação verbal e escrita em inglês

## Como se candidatar

Acesse o site da [Turing](https://bit.ly/3VWsITT) para conferir o descritivo completo e aplicar para a vaga.

Obs: esta vaga está sendo publicada pela [Remotar](https://remotar.com.br/?utm_source=github) em nome da Turing. A Remotar é uma plataforma de vagas remotas que ajuda seus clientes com a divulgação das posições abertas. No entanto, não somos responsáveis pelo processo seletivo das mesmas.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
