### ISSUE TITLE
[Remoto e Internacional] Node.js Developer na Turing.com

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#7727]
## Sobre
A well-established company that offers performance-enhancing and fitness equipments, is looking for a Node.js Developer. The developer will be responsible for the entire web development process to deliver highly scalable, customer-centric, and performant web applications. The company is leading the industry providing the most innovative technology in accelerating recovery time, preventing injury, and enhancing the body’s ability to move more efficiently. It has raised a funding of over $47.8mn so far. This is an exciting opportunity as the selected candidate will join a team of experts in developing unique and innovative products. It requires at least 4 hours of time overlap with EST.

## Job Responsibilities:

- Identify, brainstorm and resolve large and small product issues
- Own major application features and take responsibility for their maintenance and improvement over time
- Collaborate with cross functional teams for technical design discussions, pair programming sessions, and code reviews
- Write pragmatic, performant, clean, and testable code that works consistently 
- Work to improve the quality of the codebase on a regular basis

## Job Requirements:

- Bachelor’s/Master’s degree in Engineering, Computer Science (or equivalent experience)
- 3+ years of relevant software development experience
- Prior experience in Node.js 
- Strong knowledge of Next.js, E-commerce tools, Contentful, API payment and AWS Lambda is nice to have
- Excellent interpersonal and collaborative skills
- Must be fluent in English communication

## Como se candidatar

Acesse o site da [Turing](https://bit.ly/3nURWpq) para conferir o descritivo completo e aplicar para a vaga.

Obs: esta vaga está sendo publicada pela [Remotar](https://remotar.com.br/?utm_source=github) em nome da Turing. A Remotar é uma plataforma de vagas remotas que ajuda seus clientes com a divulgação das posições abertas. No entanto, não somos responsáveis pelo processo seletivo das mesmas.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
