### ISSUE TITLE
[REMOTO] Full Stack PL  - Going2

### ISSUE THREAD

**Issue by MariaJuliaRicostiG2** [frontendbr/vagas#7728]
## Nossa Empresa

A Going2 é uma startup que nasceu em 2012, com o propósito de levar tecnologia de ponta para todo o Brasil, focada em criar produtos que tenham como premissa, facilitar a vida das pessoas e empresas, através do desenvolvimento de Aplicativos, Sistemas e dos princípios de IOT (internet das coisas). Hoje, além de atender clientes nacionais também oferecemos nossos serviços para clientes internacionais, como por exemplo no Canada, Suíça e Estados Unidos.

## Local

Remoto 

## Requisitos

**Atividades**

- Participar do processo de criação e evolução dos produtos e sistemas;
- Analisar problemas e propor soluções;
- Implementar provas de conceito e protótipos;
- Especificar sistemas, processos e APIs;
- Modelagem de dados;
- Planejamento e estimativa de desenvolvimento;
- Versionamento organizado no Git;
- Participar dos rituais do time (SCRUM);
- Manutenção dos produtos e sistemas;
- Trabalhar em um ambiente ágil, altamente colaborativo e versátil;
- Cumprir entregas no prazo e com alta qualidade;
- Pode trabalhar sozinho ou em equipe como um líder;
- Pode configurar o ambiente de desenvolvimento sozinho;
- Tem iniciativa e busca maneiras diferentes de resolver problemas;
- Aplicar boas práticas de desenvolvimento de software em conjunto com o time;
- Levantar riscos e atuar na mitigação, aceite ou resolução dos problemas.

**Requisitos**

- Criação de código legível para outros desenvolvedores;
- Habilidades de otimização de código para torná-lo mais eficiente;
- Capacidade de quebrar as tarefas em tarefas menores;
- Revisar o código em detalhes;
- Encontrar bugs e propor plano de ação para correção;
- Executar várias tarefas em vários projetos de forma simultânea;
- Linguagens: Node.Js, React.Js e React Native (diferencial);
- Bibliotecas: Nest.Js, TypeORM;
- Banco de dados: MySQL
- Diferenciais: banco de dados MongoDB, experiência com APIs do Google Maps e Docker;
- Diferenciais: GoogleCloud, Google Maps e Redux.

## Contratação

PJ 

## Como se candidatar

Por favor se inscreva no link: https://going2.solides.jobs/

#### Alocação

- Remoto

#### Regime

- Freela
- PJ

#### Nível

- Pleno

**Comment by soaresrodrigo** [comment]
Enviado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
