### ISSUE TITLE
[REMOTO] Front-end PL Developer (React.Js) na GOING2

### ISSUE THREAD

**Issue by MariaJuliaRicostiG2** [frontendbr/vagas#7729]
## Nossa empresa

A Going2 é uma startup que nasceu em 2012, com o propósito de levar tecnologia de ponta para todo o Brasil, focada em criar produtos que tenham como premissa, facilitar a vida das pessoas e empresas, através do desenvolvimento de Aplicativos, Sistemas e dos princípios de IOT (internet das coisas). Hoje, além de atender clientes nacionais também oferecemos nossos serviços para clientes internacionais, como por exemplo no Canada, Suíça e Estados Unidos.

## Descrição da vaga

**Atividades**

- Participar do processo de criação e evolução dos produtos e sistemas
- Implementar provas de conceito e protótipos
- Especificar sistemas, processos e APIs
- Modelagem de dados
- Desenvolvimento e Testes 
- Versionamento organizado no Git
- Participar dos rituais do time (SCRUM)
- Manutenção dos produtos e sistemas
- Cumprir entregas no prazo, junto com o restante da equipe, ajudar a manter a qualidade, organização e automação de toda a aplicação
- Pode trabalhar sozinho ou em equipe como um líder
- Pode configurar o ambiente de desenvolvimento sozinho
- Tem iniciativa e busca maneiras diferentes de resolver problemas
- Revisar e refatorar os códigos existentes em códigos de alta qualidade.
- Projetar e desenhar códigos que sejam confiáveis e reutilizáveis.
- Garantir a melhor performance e usabilidade das aplicações.
- Saber identificar e corrigir gargalos, realizar debugs e fixes.

**Requisitos:**
- ReactJs;
- NextJs.

**Desejável:**
- Styled-components;
- Tailwindcss;
- Material Ui;
- Redux Toolkit;
- React Hook Form.

## Local

REMOTO

## Benefícios

- Convênio Médico Sul-América (sem custo para titular)
- Convênio Odontológico Sul-América (sem custo para titular)
- Gympass
- Convênio com plataforma de idiomas (Fluency Academy)
- Day-Off de aniversário
- 15 dias de descanso remunerado
- Plano de carreira

## Outras informações

Horário: 09h às 18h
Contrato de prazo indeterminado
PJ

## Contratação

PJ

## Como se candidatar

Por favor, se cadastre no link: https://going2.solides.jobs/

#### Alocação

- Remoto

#### Regime

- PJ

#### Nível

- Pleno

**Comment by soaresrodrigo** [comment]
Enviado!

**Comment by matheusmcz** [comment]
Enviado! 🌴

**Comment by CleberLopess** [comment]
Enviado!

**Comment by gabriellfernandes** [comment]
Enviado!

**Comment by hnrqsss** [comment]
Ainda disponível?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
