### ISSUE TITLE
[Remoto ou São Paulo] Programador Front-End na Agência Novi 

### ISSUE THREAD

**Issue by eduardohprado** [frontendbr/vagas#773]
## Descrição da vaga

Buscamos programador front-end para trabalho com interfaces de websites, sistemas e aplicativos. 

## Local

Remoto ou Escritório, São Paulo - Vila sônia

## Benefícios

- VR
- VT
- Seguro de vida

#### Diferenciais

- Horário flexível a combinar 
- Cursos

## Requisitos

**Obrigatórios:**

-  Experiência com HTML, CSS, Javascript
-  Bootstrap
- JS (intermediário) 
- GIT

**Desejáveis:**
- Noções de UX
- Bom gosto com interfaces

## Contratação

CLT/PJ a combinar 

## Como se candidatar

Por favor envie um email para contato@agencianovi.com.br com seu **CV anexado e pretensão salarial**  - enviar no assunto: Vaga Front-end 

## Labels

- Júnior
- Alocado
- Remoto - Parcial
- Remoto - Total

**Comment by yuritoledo** [comment]
Qual tecnologia JS vocês usam?

**Comment by danielswater** [comment]
Enviado

**Comment by renanlara** [comment]
O site está fora do ar.

**Comment by danielswater** [comment]
Puts, não ví que era Junior :(
