### ISSUE TITLE
[HOMEOFFICE] Front-end Developer na kARHUB

### ISSUE THREAD

**Issue by marinanlima** [frontendbr/vagas#7731]
## Nossa empresa

A KarHub nasceu em 2022 com uma forte paixão por tecnologia e com o propósito de tornar a compra online de Autopeças muito mais fácil e intuitiva. Para isso, criamos e unimos um time de Code, Design, Strategy, People e Ops em uma jornada que ocorre de forma ágil e colaborativa.
Na nossa cultura, valorizamos a transparência, espírito de dono e a meritocracia. Aprendemos muito com as nossas pessoas e incentivamos que todos os nossos times contribuam com o que tem de melhor para a nossa comunidade.

## Descrição da vaga

Como Dev Full Stack / FRONTEND você terá como desafio participar do processo de construção do zero do nosso canal próprio de e-commerce, interagir com outras pessoas Dev para buscar sempre a melhor solução para a resolução de problemas e no desenvolvimento de produtos inovadores.

## Local

Remoto ou Escritório na Vila Olimpia-SP

## Requisitos

**Obrigatórios:**
- 3 anos ou mais de experiência com React

**Desejáveis:**
- Node

**Diferenciais:**
Experiência em trabalhar com plataformas de e-commerce;
Conhecimento em SQL (nós utilizamos PostgreSQL);
Conhecimento em Kubernetes;
Conhecimento em AWS;
Conhecimento em mensageria (RabbitMQ, Kafka, ActiveMQ);
Conhecimento em cache (Redis ou Memcached).
Experiência trabalhando com NODEJS.

## Benefícios

- Plano de saúde

**Diferenciais:**
- Stock options
- ...

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para marina@techrecruiterbrazil.app com seu CV anexado ou Linkedin e link do Github - enviar no assunto: Vaga Frontend

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.
E-mail para contato em caso de não haver resposta: contato@techrecruiterbrazil.app

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by censuradho** [comment]
Curriculo enviado 😎

**Comment by natamartins** [comment]
Curriculo enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
