### ISSUE TITLE
[Rio do Sul-SC] Front-end Developer na Databox Sistemas

### ISSUE THREAD

**Issue by gaiveknopf** [frontendbr/vagas#7732]
## Nossa empresa

A Databox Sistemas é uma empresa com mais de 20 anos de mercado, atuando no setor de reparação automotiva.
Nosso objetivo é tornar pratico o uso diário de um sistema que recebe e fornece informações com rapidez e agilidade.
Possuímos clientes no Brasil inteiro e já estamos visando clientes internacionais.

## Descrição da vaga

# Atividades

* Participar do processo de criação e evolução dos produtos e sistemas
* Implementar provas de conceito e protótipos
* Especificar sistemas, processos e APIs
* Modelagem de dados
* Desenvolvimento e Testes
* Versionamento organizado no Git
* Participar dos rituais do time (SCRUM)
* Manutenção dos produtos e sistemas
* Cumprir entregas no prazo, junto com o restante da equipe, ajudar a manter a qualidade, organização e automação de toda a * aplicação
* Pode trabalhar sozinho ou em equipe como um líder
* Pode configurar o ambiente de desenvolvimento sozinho
* Tem iniciativa e busca maneiras diferentes de resolver problemas
* Revisar e refatorar os códigos existentes em códigos de alta qualidade.
* Projetar e desenhar códigos que sejam confiáveis e reutilizáveis.
* Garantir a melhor performance e usabilidade das aplicações.
* Saber identificar e corrigir gargalos, realizar debugs e fixes.

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Angular
- 5 anos de experiência desenvolvimento web

**Desejáveis:**
- conhecimento avançado em Angular
- conhecimento avançado em Typescript
- conhecimento avançado em HTML
- conhecimento avançado em CSS
- TDD
- Clean architecture
- Clean code

**Diferenciais:**
- Material Components;
- Tailwindcss;
- Signals

## Contratação

CLT

## Como se candidatar

Por favor envie um email para gaive@databoxsitemas.com.br com seu CV anexado - enviar no assunto: Vaga Angular

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: databox@databoxsistemas.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
