### ISSUE TITLE
[REMOTO] Front-end Developer na Franq Openbank 💙

### ISSUE THREAD

**Issue by samarafurlanetto** [frontendbr/vagas#7736]
## Nossa empresa

Somos um time de especialistas focados na inovação de produtos e serviços financeiros. Oferecemos uma solução pioneira: uma one-stop-shop para profissionais bancários independentes e escritórios de investimentos 🚀

Juntos, transformamos o mercado financeiro por meio da tecnologia. Temos como propósito, com muita franqueza, garantir a autonomia, a liberdade e a transparência para os consumidores.

Por isso, buscamos maneiras transformadoras de melhorar a forma como nossos clientes se relacionam com o mercado.

**Somos a Franq - Finance is Personal 💵**

## Descrição da vaga

- Desenvolvimento de soluções sempre pensando em eficiência, escalabilidade e estabilidade;
- Prática de code reviews, pois queremos sempre garantir a máxima qualidade e segurança das nossas entregas;
- Desenvolvimento de novas features no frontend da plataforma, de forma a produzir códigos confiáveis e fáceis de se manter; 
- Desenvolver provas de conceito para validar ideias de novos produtos;
- Atuar na resolução de problemas e gestão de incidentes.

## Local

Remoto 

## Requisitos

**Obrigatórios:**

- Conhecimento em programação Javascript;
- Conhecimento em VueJS;
- Conhecimento de Clean Code e Design Patterns.

**Desejáveis:**

- Conhecimento em Vuetify;
- Conhecimento em AWS;
- Conhecimento em testes automatizados;
- Experiência com Git.

## Benefícios

- Cartão de benefícios flexíveis Caju de R$ 816,89; 
- Assistência médica e odontológica, sem coparticipação, totalmente subsidiada pela empresa;
- Seguro de vida;
- Day off no mês de aniversário.

## Contratação

CLT

## Como se candidatar

Para se candidatar na vaga, acessar o link: https://franq.gupy.io/jobs/4768245

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
