### ISSUE TITLE
[Remoto e Internacional] Programador Front-end (react/node) na Turing.com

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#7737]
## Descrição do trabalho
Uma empresa sediada nos EUA,  que está desenvolvendo uma plataforma global que conecta parceiros de todos os setores com o intuito de criar uma economia mais justa, sustentável e inclusiva, está procurando contratar um Programador Front-end. O programador irá colaborar com as equipes comerciais e de produto de maneira interfuncional para desenvolver soluções de software. Ao oferecer a profissionais da área social a informação, experiência e conexões que eles precisam para escalar ideias revolucionárias, a empresa busca ajudar na criação de uma economia mais justa e sustentável. A organização conseguiu arrecadar mais de US$400 mil durante sua rodada de investimentos Semente. Essa é uma vaga de trabalho online de longo prazo e tempo integral, ideal para programadores brasileiros que querem sentir o impacto positivo do seu trabalho sobre o mundo.

## Responsabilidades:

- Apoiar a execução imediata das tarefas de engenharia voltadas para o front-end
- Desenvolver aplicativos online e aplicar seus conhecimentos para avançar o desenvolvimento da empresa e, eventualmente, melhorá-lo
- Ajudar a equipe a fazer a transição do framework front-end do Jade para o React.js
- Colaborar diretamente com a equipe de engenharia para aprimorar a plataforma

## Requisitos:

- Bacharelado ou Mestrado em Engenharia ou Ciência da Computação (ou experiência equivalente)
- Ao menos 3 anos de experiência relevante como programador front-end
- Experiência comprovável trabalhando com React, Node.js e PostgreSQL
- Vasta experiência com HTML/CSS/JavaScript
- Profundos conhecimentos sobre Redux, React Router, React Toolkit e Storybook
- Conhecimento sobre conversão de designs de códigos do Zeplin para o Figma
- Sólido conhecimento sobre sistemas de controle de versão de código, como Git
- Sólido entendimento sobre as ideias e práticas do desenvolvimento web, especialmente design responsivo, interoperabilidade cross-browser e acessibilidade
- Compreensão sobre APIs RESTful e sobre como elas funcionam junto a aplicativos web
- Capacidade de interagir com stakeholders e trabalhar bem em equipe
- Ótimas habilidades analíticas e uma grande atenção para detalhes
- Vastos conhecimentos sobre frameworks de teste, como Mocha, Jest ou Enzyme 
- Boa compreensão sobre técnicas e software de desenvolvimento Agile, como JIRA ou Trello
- Familiaridade com AWS será um diferencial
- Boa comunicação em inglês

## Como se candidatar

Acesse o site da [Turing](https://bit.ly/3MfzFuT) para conferir o descritivo completo e aplicar para a vaga.

Obs: esta vaga está sendo publicada pela [Remotar](https://remotar.com.br/?utm_source=github) em nome da Turing. A Remotar é uma plataforma de vagas remotas que ajuda seus clientes com a divulgação das posições abertas. No entanto, não somos responsáveis pelo processo seletivo das mesmas.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
