### ISSUE TITLE
[Internacional e Remoto] Desenvolvedor Front-end (TypeScript e React)

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#7739]
## Descrição do trabalho
Uma empresa em rápido crescimento, que está determinada a desenvolver um mercado online para ajudar esportes e negócios digitais a crescerem rapidamente, está procurando contratar um Desenvolvedor Front-end. O candidato selecionado será responsável por garantir que os produtos da empresa sejam altamente resilientes, tenham latência extremamente baixa e sejam escaláveis para um grande volume. A empresa usa tecnologia avançada para conectar fãs e comunidades com os esportes e jogos que eles adoram por meio de plataformas online e de agências. Esta é uma ótima vaga de trabalho online para desenvolvedores brasileiros determinados a aprimorar suas habilidades enquanto constroem uma carreira lucrativa.

##vResponsabilidades:

- Compreender os objetivos e especificações do domínio KYC/Compliance, bem como as características técnicas da implementação
- Elaborar e desenvolver o site mobile responsivo em colaboração com a equipe de desenvolvimento
- Testar a versão mobile do site para garantir que ele atenda às funcionalidades e aos critérios de segurança desejados, além de oferecer assistência com quaisquer problemas que surjam ao usá-lo
- Escrever unit tests e criar códigos e bibliotecas reutilizáveis para uso futuro

## Requisitos:

- Bacharelado ou Mestrado em Engenharia ou Ciência da Computação (ou experiência equivalente)
- Pelo menos 3 anos de experiência relevante como desenvolvedor front-end
- Experiência trabalhando com TypeScript, JavaScript e React.js
- Vasta experiência com Redux, GraphQL, Cloudflare e Google Analytics
- Conhecimento sobre os regulamentos de KYC/Compliance e leis de privacidade de dados
- Familiaridade com as melhores práticas e ferramentas de segurança de aplicações web
- Excelentes habilidades de colaboração e interpessoais
- Boa comunicação verbal e escrita em inglês

## Como se candidatar

Acesse o site da [Turing](https://bit.ly/3WlGa4f) para conferir o descritivo completo e aplicar para a vaga.

Obs: esta vaga está sendo publicada pela [Remotar](https://remotar.com.br/?utm_source=github) em nome da Turing. A Remotar é uma plataforma de vagas remotas que ajuda seus clientes com a divulgação das posições abertas. No entanto, não somos responsáveis pelo processo seletivo das mesmas.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by matheusmcz** [comment]
Sended 🚀

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
