### ISSUE TITLE
[São Paulo] Front-End Developer na OPT2FLOW 

### ISSUE THREAD

**Issue by rogeriorioli** [frontendbr/vagas#774]
Front-End Developer na OPT2FLOW 
==================================================

## Descrição da vaga

Front-end developer para atuar em jobs que envolvam bons conhecimentos em programação.

-HTML
-CSS
-JAVASCRIPT
-JQUERY
-CONSUMIR APIS

## São Paulo / Zona Sul

Escritório, São Paulo - Chácara Santo Antônio

## Benefícios

- VR de R$ 20,00 dia 
- monte a sua máquina como desejar
- sala de jogos

#### Diferenciais
-WORDPRESS
- PRÉ PROCESSADORES

## Contratação

PJ ou CLT

## Nossa empresa

Software House e desenvolvedora de projetos digitais com clientes de médio e grande porte.

## Como se candidatar

Por favor envie um email para gustavo.rocha@opt2flow.com.br com seu CV anexado - enviar no assunto: Vaga Front-End Developer

## Labels

- Alocado
- CLT
- Júnior

**Comment by richmanzoli** [comment]
Trabalhar em que linguagem? Qual os requisitos obrigatórios e diferencias?

**Comment by rogeriorioli** [comment]
@richmanzoli , obrigado pela pergunta , estou ajudando meu amigo que precisa preencher essa vaga e ele me esqueceu de passar o job description . 
acabei de atualizar

**Comment by laugustofrontend** [comment]
@rogeriorioli, mandei email. Abraço!

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
