### ISSUE TITLE
[Remoto] Tech Lead (JCal Consultoria) 

### ISSUE THREAD

**Issue by Claudiaantunesdelima** [frontendbr/vagas#7740]
⏭️𝙏𝙀𝘾𝙃 𝙇𝙀𝘼𝘿 𝙍𝙀𝘼𝘾𝙏/𝙉𝙊𝘿𝙀

🔅𝗥𝗲𝘀𝗽𝗼𝗻𝘀𝗮𝗯𝗶𝗹𝗶𝗱𝗮𝗱𝗲𝘀 

Estamos procurando por um Tech Lead com habilidades em JavaScript, Node.JS, React, React.JS, cloud, NoSql e SQL. O candidato ideal deve ser um conhecedor das metodologias ágeis e colocar a mão na massa.

Trabalhar com a equipe para desenvolver soluções de software escaláveis e sustentáveis.
Fornecer liderança técnica para a equipe, incluindo orientação no desenvolvimento de software e na definição da arquitetura do produto.
Gerenciar e liderar projetos técnicos.

🔅𝗥𝗲𝗾𝘂𝗶𝘀𝗶𝘁𝗼𝘀

🔸 +7 anos de experiência em desenvolvimento de software
🔸Experiência com linguagens de programação em Back-end e Front-End Exemplo ( JavaScript, Node.JS, React e React.JS)
🔸Conhecedor de Nuvem (AWS e/ou GCP e/ou Azure)
🔸Banco de dados estruturados e não estruturados

🔅 𝗕𝗲𝗻𝗲𝗳í𝗰𝗶𝗼𝘀

🔸Férias de 15 dias depois de 1 ano
🔸Seguro de vida
🔸Bônus

🔅𝗦𝗮𝗹á𝗿𝗶𝗼

💸R$15.000 - PJ
🏘️Remoto

📲Favor enviar o currículo para o WhatsApp 19 97816-4262 

Me segue para mais oportunidades 👇🏻
https://www.linkedin.com/in/thisclaudia

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
