### ISSUE TITLE
[Remoto] Front-end Developer na Bonidev

### ISSUE THREAD

**Issue by danielbonifacio** [frontendbr/vagas#7741]
## Nossa empresa

A Bonidev é uma empresa dedicada ao desenvolvimento de software personalizado, comprometida em fornecer soluções de alta qualidade e entrega ágil. Nossa missão é ajudar nossos clientes a alcançar o sucesso por meio de tecnologia inovadora e eficiente.

Valorizamos a qualidade em tudo o que fazemos. Desde a concepção até a entrega final, dedicamos atenção aos detalhes, garantindo que nossos produtos e serviços atendam às expectativas mais exigentes. Acreditamos que a excelência é alcançada através de processos robustos de desenvolvimento, testes rigorosos e uma abordagem orientada à qualidade.

Além disso, somos impulsionados pela entrega ágil. Reconhecemos a importância de prazos e entendemos que o mundo dos negócios é dinâmico e acelerado. Por isso, adotamos metodologias ágeis que nos permitem ser flexíveis, iterativos e responsivos às necessidades dos nossos clientes. Nosso compromisso é entregar soluções de maneira eficiente e dentro dos prazos estabelecidos.

Na Bonidev, acreditamos que a combinação de qualidade e entrega ágil é a chave para o sucesso. Trabalhamos em estreita colaboração com nossos clientes para entender suas necessidades e superar suas expectativas. Estamos constantemente aprimorando nossas habilidades e conhecimentos para estar na vanguarda da tecnologia e proporcionar resultados excepcionais.

## Descrição da vaga

A Bonidev está em busca de um talentoso e **responsável** Front-end Developer para se juntar à nossa equipe em um projeto interno voltado para a área de planejamento de negócios com grande potencial de crescimento. Se você é apaixonado por desenvolvimento web, possui sólidos conhecimentos em front-end e está em busca de uma oportunidade desafiadora, essa vaga é para você!

* Horas por semana: 15~20
* Calls de alinhamento que levam 20~40 minutos por semana
* Projeto já em andamento
  * React.js com TypeScript e MUI5
* Teremos 4 membros no squad desse projeto

Como freelancer, você terá flexibilidade em relação aos horários e poderá trabalhar remotamente.

Nós **não somos o tipo de empresa que vai te encher o saco todo dia**, e esperamos responsabilidade por parte do profissional, para que tudo seja entregue sem muita cobrança.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 4 anos de experiência com Desenvolvimento Front-end no geral
- 3 anos de experiência com React.js
  - Context API
  - Hooks
  - Gerenciamento de token
- 3 anos de experiência com TypeScript
- Versionamento de código com GIT
- Habilidades de resolução de problemas e atenção aos detalhes
- Capacidade de trabalhar de forma independente e entregar resultados dentro dos prazos estabelecidos
- Excelentes habilidades de comunicação e capacidade de trabalhar em equipe

**Desejáveis:**
- Inglês intermediário (o código do projeto, incluso banco de dados, está todo em inglês)
- Experiência prévia com MUI 5

## Contratação

PJ - R$56,81/hora (10k / 22 dias úteis / 8 horas)

## Como se candidatar

Por favor envie um email para tecnologia@bonidev.com.br com seu CV anexado e disponibilidade para conversar entre hoje e amanhã (pode ser fora do horário comercial também) - enviar no assunto: Vaga Front-end

## Tempo médio de feedbacks

~~Esse projeto tem certa urgência. Vamos dar os feedbacks entre terça e quarta.~~

Edit: Devido à um problema de saúde que gerou minha ausência, o processo se estendeu até sexta-feira dia 26/05.

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Pleno

**Comment by bernalvinicius** [comment]
Olá, qual a previsão de duração do projeto?

**Comment by YuriBrunetto** [comment]
Enviado!

**Comment by matheusmcz** [comment]
Enviado! 🌴

**Comment by jhefflg** [comment]
Up.

**Comment by Leorrc** [comment]
Enviei o e-mail!

**Comment by nltncsr** [comment]
@danielbonifacio, mandei o email no mesmo dia poucas horas depois da publicação aqui e não tive nenhuma devolutiva. A oportunidade ainda está de pé?

**Comment by joakweb** [comment]
> Olá, qual a previsão de duração do projeto?

Também gostaria de saber.

**Comment by danielbonifacio** [comment]
Oportuinidade pausada. Voltaremos com o processo nas próximas semanas.
