### ISSUE TITLE
[Remoto] Front-end Developer na @AMcom

### ISSUE THREAD

**Issue by maluconzatti** [frontendbr/vagas#7743]
## Nossa empresa

Há 26 anos, nosso propósito é o de conectar pessoas à tecnologia para transformar vidas!

Na mesma medida em que somos apaixonados por tecnologia, somos apaixonados por gente. Tudo o que fazemos é pensado nas nossas pessoas, e consequentemente, nos nossos clientes e nos clientes dos nossos clientes.

A cultura organizacional forte e dinâmica rege todas as nossas práticas, e visa proporcionar uma experiência singular e diferenciada para cada um dos nossos makers. A camaradagem, o respeito e a credibilidade são valorizados e percebidos nas ações e interações diárias com os líderes, colegas de trabalho e clientes. Reflexo disso foi o recebimento, em 2022, da certificação GPTW pelo terceiro ano consecutivo, e da entrada para o ranking das 150 Melhores Empresas para Trabalhar em TI e das 150 Melhores Empresas do Brasil, ocupando a 26ª posição. Além disso, o nosso time de R&S está entre os 100 RHs mais inspiradores do Brasil, com destaque na categoria encantamento.

Você também quer iniciar a sua Jornada Maker e fazer a transformação acontecer? _#vemsermaker_!

## Descrição da vaga

Estamos expandindo nossos horizontes e por isso procuramos pessoas que amem tecnologia, que sejam fascinadas por aprender coisas novas e que queiram fazer parte do nosso time!

Nesta vaga o profissional irá participar de Squad de desenvolvimento de sistemas para empresa de grande porte no setor de energia que possui projetos com muitos desafios e possibilidade de desenvolvimento e crescimento.

## Local

Remoto

## Requisitos

**Obrigatórios:**
Experiência em tecnologias de desenvolvimento front-end (Javascript ES5+, TypeScript, HTML5 e CSS);
Experiência com Angular 14+ e pré-processadores CSS (Sass, Less, etc);
Conhecimento de arquitetura de projetos front-end;
Vivência com ferramentas de versionamento (preferencialmente Git).
 
**Desejáveis:**
Experiência com PrimeNg;
Vivência em projetos em metodologias ágeis (Scrum, Kanban);
Conhecimento básico de UI/UX Designer;
Conhecimento nos gerenciadores de tarefas (WebPack);
Vivência com publicação e gerenciamento de pacotes NPM.

## Benefícios

💳 R$ 2.000,00 em VR/VA em cartão flexível (cartão Flash)
🏥 Plano de saúde de sua escolha: Unimed ou Notre Dame
🦷 Plano odontológico
💬 Curso de inglês gratuito
🎓 Incentivo aos estudos (Graduação/Pós/MBA) – reembolso de 50% do valor da mensalidade
🎯 Incentivo ao desenvolvimento profissional – certificações, reembolso de 100%
🏖️ Day-off no mês de aniversário
🕦 Horário flexível
🏡 Modalidade de trabalho da sua escolha!
💰 Programa de indicação premiada
🎉 Premiação por tempo de casa – aqui celebramos sua trajetória conosco 1, 3, 5, 7, 10, 15 e 20 anos
📈 Plano de cargos e salários
💰 PPLR anual
💸 Auxílio Home Office (R$ 70,00)

E quando nossos makers vêm nos visitar na sede:
☕ Café, muito café!
😌 Cadeira de massagem
🎱 Sinuca
🎮 Vídeo game
😴 Nap room
🚧 Estacionamento gratuito
🚲 Bicicletário

## Contratação

CLT a combinar

## Como se candidatar

Você pode enviar seu currículo para [maria.conzatti@amcom.com.br](mailto:maria.conzatti@amcom.com.br) com o assunto "Vaga de Front-end" ou se candidatar através da Gupy [aqui](https://amcom.gupy.io/jobs/4830181) (pode ficar tranquilo que damos feedback por lá!)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: maria.conzatti@amcom.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by kvnol** [comment]
CV enviado!

**Comment by soaresrodrigo** [comment]
Enviado!

**Comment by maluconzatti** [comment]
Vaga fechada! 👯
