### ISSUE TITLE
[REMOTO] Full Stack Sênior na Going2

### ISSUE THREAD

**Issue by MariaJuliaRicostiG2** [frontendbr/vagas#7746]
## Nossa empresa

A Going2 é uma startup que nasceu em 2012, com o propósito de levar tecnologia de ponta para todo o Brasil, focada em criar produtos que tenham como premissa, facilitar a vida das pessoas e empresas, através do desenvolvimento de Aplicativos, Sistemas e dos princípios de IOT (internet das coisas). Hoje, além de atender clientes nacionais também oferecemos nossos serviços para clientes internacionais, como por exemplo no Canada, Suíça e Estados Unidos.

## Descrição da vaga

**Atividades**

- Pode assumir processo completos, desde o início do desenvolvimento até o lançamento;
- Habilidade analítica de encontrar brechas em grandes projetos;
- Levantar riscos e atuar na mitigação, aceite ou resolução dos problemas;
- Fazer revisões regulares do código;
- Pode resolver problemas diferentes e de forma independente devido sua experiência;
- Extenso conhecimento teórico e prático sobre os mais diversos assuntos de tecnologia;
- Participar do processo de criação e evolução dos produtos e sistemas;
- Analisar problemas e propor soluções;
- Implementar provas de conceito e protótipos;
- Especificar sistemas, processos e APIs;
- Modelagem de dados;
- Planejamento e estimativa de desenvolvimento;
- Desenvolvimento e Testes;
- Versionamento organizado no Git;
- Participar dos rituais do time (SCRUM);
- Trabalhar em um ambiente ágil, altamente colaborativo e versátil;
- Cumprir entregas no prazo e com alta qualidade;
- Liderar e ajudar desenvolvedores do time;
- Ajudar com resoluções e melhorias em débitos técnicos;
- Ser referência em relação a boas práticas durante a construção de nossos sistemas e aplicações.

**Requisitos**

- (Geralmente mais de 6 anos de experiência com desenvolvimento de software);
- Alto nível de autoconhecimento e autodesenvolvimento;
- Experiência na resolução de problemas e tarefas de alta complexidade;
- Mentoria e desenvolvimento de novos talentos;
- Conhecimento e experiência em todos os aspectos da engenharia de software;
- Capacidade em delegar tarefas com assertividade;
- Capacidade de justificar processos e valores usando dados e bom poder de convencimento;
- Tem uma visão do bigpicture e, ao mesmo tempo, profunda do negócio;
- Experiência avançada com projetos com as tecnologias: Node.Js (BACK-END) React.Js (FRONT-END WEB) e React Native (FRONT-END MOBILE);
- Bibliotecas: Nest.Js, TypeORM;
- Banco de dados: MySQL, Stored Procedures e Functions;
- Docker;
- Redux;
- Funções do Google Cloud, Google Maps.

## Local

REMOTO

## Benefícios

- Convênio Médico Sul-América (sem custo para titular);
- Convênio Odontológico Sul-América (sem custo para titular);
- Gympass;
- Convênio com plataforma de idiomas (Fluency Academy);
- Day-Off de aniversário;
- 15 dias de descanso remunerado;
- Plataforma de treinamento Udemy;
- Plano de carreira.

## Contratação

PJ

## Como se candidatar

Por gentileza, se candidatar no link: https://going2.solides.jobs/

#### Alocação

- Remoto

#### Regime

- PJ

#### Nível

- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
