### ISSUE TITLE
[REMOTO] Full-Stack Developer na UPIK

### ISSUE THREAD

**Issue by vbupik** [frontendbr/vagas#7747]
## Nossa empresa

**Sobre a Upik** 💜💛

Já pensou em utilizar seu conhecimento para transformar a vida das pessoas?

É exatamente o que acontece aqui, na UPIK.

**Seja bem vindo(a), entre e faça parte.**

Somos o player online da América Latina no mercado em que atuamos, uma startup com incrível tração e mais de 5 prêmios nacionais/internacionais.

Nascemos com um propósito incrível: **transformar a vida das pessoas democratizando a Arquitetura e o Design de Interiores no Brasil e no Mundo.**

Passamos 90% do nosso tempo de vida dentro de ambientes fechados, entre 4 paredes. Esses espaços influenciam nosso dia a dia, o ciclo circadiano (ciclo de 24h), nosso organismo, até a produção de hormônios e neurotransmissores, por isso, Arquitetura e Design de Interiores não são uma questão estética, mas sim de qualidade de vida e bem estar.

A UPIK desenvolve tecnologia para democratizar a Arquitetura e o Design de Interiores e hoje, nosso principal produto é o Arquiteto de Bolso, ([www.arquitetodebolso.com.br](http://www.arquitetodebolso.com.br/)), o jeito mais rápido, prático e acessível para reformar ou decorar.

Resolvemos o ambiente em no máximo 2 horas, 100% online, com planta 2D (para o cliente entender a distribuição do espaço) + Perspectivas 3D (visualizar cores, acabamentos e revestimentos) + Lista de Compras com produtos, quantidades e preços, respeitando o orçamento do cliente.

E assim já transformamos mais de 45.000 ambientes em 12 países. Incrível, né?!

Além de tudo isso, já passamos por rodadas de investimento, com os players mais renomados do mercado. Já ouviu falar de ACE Startups, GV Angels, BossaNova e até o Grupo Primo, criado pelo Thiago Nigro? Sim, pois é, o maior influenciador de finanças do mundo acreditou em nós!

Se você chegou até aqui, agradecemos o seu tempo.

**Se você é realmente um talento naquilo que faz, estamos te esperando para embarcar nessa jornada conosco.**

## Descrição da vaga

Desenvolvedor Fullstack Pleno que irá colaborar na construção e manutenção dos projetos atuais, junto aos demais desenvolvedores do time de Tecnologia e Produto. 

## Local

Exemplo: Remoto

## Requisitos

**Obrigatórios:**
- Experiência com .NET/.NET Core com C#;
- Experiência com React e TypeScript/JavaScript;
- Experiência com CSS, HTML;
- Experiência em construir e documentar APIs;
- Experiência com UX (tracking, acessibilidade e otimizações de desempenho);
- Experiência com abordagem de qualidade (testes de unidade, integração, testes de perfomance);
- Experiência com arquitetura de software (Clean Architecture, MVC, Design Patterns);
- Experiência com arquitetura web (modelo cliente-servidor, cache, DNS, containers);
- Experiência com ferramentas de prototipação: Figma e/ou Adobe XD;
- Experiência na metodologia SCRUM;
- Habilidades interpessoais, de escrita e de comunicação verbal;
- Formação em ensino superior ou técnico;

**Desejáveis:**
- Experiência prévia (mínimo 2 anos) nas linguagens informadas;
- Conhecimentos em TypeScript ou Flow

**Outras Informações:**
- Startup tracionada e reconhecida no mercado
- 100% remoto
- Plano de Saúde 100% pago pela empresa
- Cartão Caju
- Dois períodos de descanso remunerados por ano
- Modelo de contrato PJ

## Como se candidatar

Por favor envie um e-mail para fabiola@upik.com.br com seu CV anexado - enviar no assunto: Vaga Full Stack GitHub

**Comment by soaresrodrigo** [comment]
Enviado!
