### ISSUE TITLE
[Remoto] Front-End Developer na Vektor

### ISSUE THREAD

**Issue by akramhussein** [frontendbr/vagas#7748]
## Nossa empresa

A Vektor é uma ferramenta de gerenciamento de portfolio DeFi rápida e poderosa criada para profissionais e instituições.

Usando uma linguagem similar a de planilhas (VXL) e um espaço de trabalho customizável, os usuários podem consultar, automatizar e executar com velocidade e trabalhar em várias blockchains, protocolos e categorias DeFi, sem custódia.

A Vektor é 100% remota e apoiada por fundos de investimento do Vale do Silício e investidores-anjo em todo o mundo que investiram em outras empresas e protocolos de criptografia de referência, bem como Stripe, Square e Pinterest.

## Descrição da vaga

Seu cargo envolverá:

- Construir novas features de forma eficiente e confiável usando ferramentas modernas como Typescript, React, React Native, Redux e Redux Saga.
- Escrever testes unitários e end-to-end.
- Alguns dos projetos incluirão:
    - Implementação de novas features, como novos componentes UI
    - Nosso SDK Javascript/Typescript
    - Adicionar suporte para novos dispositivos de assinatura criptográfica
    - Correções gerais de bugs e análise de performance

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com Typescript
- 2 anos de experiência com React em Redux
- Fluente em inglês

**Desejáveis:**
- conhecimentos em Redux Saga
- conhecimentos em React Native

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para jobs@vektor.finance com seu CV anexado - enviar no assunto: Front-end Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 1 dias após cada processo.

E-mail para contato em caso de não haver resposta: jobs@vektor.finance

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Pleno
- Sênior

**Comment by soaresrodrigo** [comment]
Enviado!

**Comment by lspenha** [comment]
Enviado!

**Comment by Remato** [comment]
enviei :)

**Comment by jhefflg** [comment]
Up!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
