### ISSUE TITLE
[Remoto] Líder Técnico FullStack na ITeam

### ISSUE THREAD

**Issue by ITeam-oportunidades** [frontendbr/vagas#7749]
> Vaga Remota 

## ITeam

Há mais de 15 anos presente no mercado, a ITeam oferece o comprometimento com o cliente.
Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 
Com uma equipe multidisciplinar, a ITeam proporciona uma área de Serviços Gerenciáveis como Projetos SAP, Fábrica de Software, Fábrica de Soluções e Sustentação. Neste modelo proporcionamos Sustentação, Melhorias e Desenvolvimentos de aplicação de forma integrada.

## Local

100% Remoto

## Requisitos

Experiência como Líder de times de desenvolvimento ágil e arquitetura de soluções. 
Imprescindível o conhecimento técnico BackEnd Node.js, FrontEnd Angular, banco de dados PostgreSQL e Cloud AWS. 

## Desejáveis 

Conhecimentos em framework Nest.js; Design Patterns; Boas práticas (como clean code, clean architecture, Solid, DDD), ciclo de vida de uma aplicação (design, test, build, deploy), conceitos de CI/CD.

## Atividades

Conduzir um time de desenvolvimento ágil responsável por uma solução desenvolvida em cloud AWS composta por Backend Node.js, FrontEnd Angular e banco PostgreSQL.

## Contratação

12 meses, podendo renovar

## Como se candidatar

Por favor, envie um e-mail para viviane.pereira@iteam.inf.br com seu CV anexado e pretensão de taxa/hora PJ ou pretensão salarial CLT - enviar no assunto: Líder Técnico FullStack

## Labels

Node.Js
Angular
PostgreSQL
Cloud
AWS
Agile

## Regime
PJ (ter empresa aberta)
CLT 

## Nível
Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
