### ISSUE TITLE
[Curitiba-PR] Front-End Developer na Moments.Surf

### ISSUE THREAD

**Issue by fernandoamorim** [frontendbr/vagas#775]
## Descrição da vaga

Atuar no desenvolvimento front e, se possível, back das novas funcionalidades do app e do sistema.

## Local

Escritório no bairro Ahú em Curitiba/PR, próximo a OAB

## Requisitos

**Obrigatórios:**
- Conhecimentos sólidos em HTML5, CSS3 e JavaScript (ES6), GIT
- Conhecimentos em NodeJS, AngularJS, React

**Desejáveis:**
- Conhecimentos em PHP e Banco de Dados MySQL
- Conhecimentos em React-Native
- Conhecimentos em ambiente AWS (Amazon)
- Conhecimentos em Google Firebase (Real Database)

## Contratação

PJ a combinar

## Nossa empresa

Startup com pouco mais de dois anos de vida, com registros em mais de 28 países.

## Como se candidatar

Por favor envie um email para fernando.amorim@moments.surf com seu CV anexado - enviar no assunto: [Vaga Front-End] + Seu nome

## Labels

- Alocado
- PJ
- Pleno

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
