### ISSUE TITLE
[Remote] Front End Developer Angular 2+ PL

### ISSUE THREAD

**Issue by NovareRH** [frontendbr/vagas#7751]
**✔️ TAREFAS:**
-Desenvolver novas funcionalidades;
-Fazer manutenções e eventuais correções necessárias;
-Elaborar documentação ﻿e guias de requisitos funcionais, conforme os projetos.
-Verificar os códigos através de testes unitários.

**Cargo:** Desenvolvedor Front End Angular 2+ PL- Remote Work
**Tipo de Contrato:** Prestador de serviço (PJ)
**Área profissional:** Informática/T.I.
**Jornada:** Segunda a sexta
**Número de vagas:** 1
**Salário:** R$ 6.000,00 - R$ 8.000,00
**Benefícios:** GoGood
**BYOD:** R$ 50,00
**PLR**
**Bolsa Estudos**: R$200,00 por mês mediante utilização.
**Acesso a plataformas de cursos compartilhados (Alura, Udemy, ...)**

Requisitos
**Idiomas:**
- Inglês - Desejável
- Compreensão: Intermediário
- Leitura: Intermediário

⏱️ **EXPERIÊNCIAS, COMPETÊNCIAS E CONHECIMENTOS:**

*Experiência:
- Angular 2+;
- 3 anos nas tecnologias da vaga.

*Conhecimentos:
- Angular 2+
- Javascript
- TypeScript;
- Angular Material; 
- RXJS;
- SCSS/CSS;
- Metodologias ágeis;
- Testes Unitários;
- Noções de UX/UI;
- Inglês intermediário (necessário para leitura de documentação). 

🚀** DIFERENCIAL: **
- Material Design;
- NGRX;
- React Native;
- Espanhol básico.

💻 ﻿**Tecnologias que você vai trabalhar:**
- Angular +14;
- Tailwind CSS;
- NgRx;
- RXJS;
- Web Components;
- NX
- Jest

🚀**O QUE BUSCAMOS:**
- Comunicação fluida e clara;
- Perfil analítico e executor;
- Maturidade profissional;
- Facilidade de trabalhar em equipe de forma remota;
- Buscar constante aprendizado e novos conhecimentos;
- Autogestão.

*🚀* Para mais informações ou inscrição: *https://novarerh.selecty.com.br/vaga/75/vaga-para-desenvolvedor-front-end-angular-2-pl-remote-work

Ou entre em contato pelo *WhatsApp* através do link: https://api.whatsapp.com/send?l=pt_BR&phone=554398660658

**Sobre a empresa**
Keeps Desenvolvimento de Sistemas LTDA,
A Keeps é uma EdTech focada em trazer ao mercado de educação corporativa soluções disruptivas e de alto impacto nos negócios. Suas soluções utilizam inteligência artificial, colaboração e mobilidade para potencializar o conhecimento dos colaboradores.
Nos últimos três anos foram premiados entre as 6 melhores EdTechs no Brasil.
Possuem o propósito de Desenvolver e Impulsionar o conhecimento, sendo referência em inovação, tecnologia e serviços para área de educação. Para fazer parte do time da Keeps ﻿precisa gostar muito de aprender. Estudar e manter um conhecimento contínuo é um dos valores da Keeps

**Comment by pedrolima4** [comment]
Inglês, Espanhol, 35 ferramentas... 6k hahahah

**Comment by NovareRH** [comment]
Boa tarde Pedro, tudo bem?

Conforme descrição da vaga, a remuneração é *a partir de 6k. *

Em qua., 31 de mai. de 2023 às 15:22, Pedro Lima ***@***.***>
escreveu:

**Comment by ruslanpascoal2** [comment]
Bom dia, mandei mensagem no Whatsapp.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
