### ISSUE TITLE
[SP] Front-end Developer na Minthouse

### ISSUE THREAD

**Issue by Lucca-C** [frontendbr/vagas#7752]
## Minthouse

Somos uma pequena empresa de software sediada em Singapura. Criamos aplicativos móveis, web, nativos e de desktop para várias empresas.

[Minthouse.dev](https://github.com/backend-br/vagas/issues/Minthouse.dev)

Estamos procurando um desenvolvedor em qualquer fuso horário, mas Portugal e Brasil têm preferência.

## Descrição da vaga

- Estamos procurando um desenvolvedor front-end para trabalhar em conjunto com nosso membro da equipe e desenvolvedor back-end.
- Se o projeto for bem-sucedido, estamos procurando alguém para ficar e assumir mais trabalho a longo prazo.
- Como o trabalho é remoto, o candidato ideal deve ser muito comunicativo e independent

## Local

Exemplo: Remoto

## Requisitos

**Obrigatórios:**

- Inglês fluente
- 3 anos ReactJS
- Conhecimento de REST APIs
- Typescript, HTML, CSS
- Conhecimento de Git/Github
- Conhecimento de MERN stack

**Desejáveis:**
- Otimização da eficiência do front-end

**Diferenciais:**
- Exemplos de design front-end

## Benefícios

- Salário mensal de US$ 1.800 a US$ 2.000 para o primeiro projeto, oportunidade de aumento para os projetos seguintes.
- 13º Salário.
- Oportunidade de trabalhar diretamente com start-ups de todo o mundo e ampliar sua rede de contatos.
- Independência no trabalho, nas escolhas técnicas e nos horários. Desde que o trabalho seja bom, nos não importamos com a forma como você o realiza.

## Como se candidatar

Por favor envie um email para luccaocamargo@gmail.com com seu CV anexado - enviar no assunto: Vaga ReactJS

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: joao@minthouse.dev 

#### Alocação
- Remoto

#### Regime
- Freelance

#### Nível
- Pleno
- Sênior

**Comment by lspenha** [comment]
Enviado !

**Comment by GabrielGuedess** [comment]
Enviado 🚀

**Comment by rafaelteodosio** [comment]
Enviado!

**Comment by lmdvlpr** [comment]
Enviado!
