### ISSUE TITLE
[São Paulo] Front-end Developer Pleno/Sênior na FieldPRO

### ISSUE THREAD

**Issue by danilo-augusto** [frontendbr/vagas#7754]
## Nossa empresa

FieldPRO é única do Brasil a utilizar novas modelagens meteorológicas combinando dados exclusivos sobre as condições do tempo e a saúde do solo, vindo da nossa rede de estações autônomas, para fornecer relatórios ambientais personalizados e previsões do tempo incomparáveis.

## Descrição da vaga

Front-end Developer Pleno/Sênior que irá colaborar na construção e manutenção dos projetos atuais, junto aos times de Produto, Back-end e Dados. Você será responsável por implementar interfaces de usuário fluidas e responsivas para várias plataformas e dispositivos.

## Local

Escritório: SP, São Paulo, Vila Nova Conceição

## Requisitos

**Obrigatórios:**
- Experiência (pelo menos 3 anos) com React e TypeScript/JavaScript;
- Experiência com CSS, HTML;
- Experiência em construir e documentar APIs;
- Experiência com UI/UX (tracking, acessibilidade e otimizações de desempenho);
- Experiência com ferramentas de prototipação: Figma e/ou Adobe XD;
- Experência em metodologias ágeis como Scrum e Kanban;
- Habilidades interpessoais, de escrita e de comunicação verbal;
- Formação em ensino superior ou técnico

**Desejáveis:**
- Experiência com Ionic
- Experiência com abordagem de qualidade (testes de unidade, integração, testes de perfomance);
- Experiência com arquitetura de software (Clean Architecture, MVC, Design Patterns);
- Experiência com arquitetura web (modelo cliente-servidor, cache, DNS, containers);
- Experiência com ferramentas de desenvolvimento web (module bundlers e linters);
- Uso de pré/pós-processadores CSS como PostCSS, Styled Components, LESS, SASS e/ou outros;

**Diferenciais:**
- Projetos opensource

## Benefícios

**Diferenciais:**
- Salário competitivo
- Startup tracionada e reconhecida no mercado
- Aprendizado garantido: equipe talentosa com engenheiros das melhores universidades do Brasil e do mundo
- Localização privilegiada, ao lado do Ibirapuera
- Happy Hours frequentes
- Mesa de ping-pong
- Lanche da tarde com pão de queijo
- Atividades físicas em equipe

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para danilo.augusto@fieldpro.com.br com seu CV anexado - enviar no assunto: Vaga Front GitHub

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias úteis após cada processo.
E-mail para contato em caso de não haver resposta: danilo.augusto@fieldpro.com.br

#### Alocação
- Alocado, **100% presencial**

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by 0xFernandoDias** [comment]
Enviado

**Comment by Phregenes** [comment]
Enviado!

**Comment by GabrielGuedess** [comment]
Enviado 🚀

**Comment by danilo-augusto** [comment]
Boa tarde, pessoal! Só lembrando que a vaga é 100% presencial na cidade de São Paulo. Estamos recebendo candidaturas de outros estados. Nesse caso seria interessante a pessoa indicar no email que ela está disposta a se mudar para São Paulo. Muitos postularam sem ler atentamente. 😅

**Comment by danilo-augusto** [comment]
Recebemos um grande número de candidaturas e agradecemos o interesse pela vaga. :)
Estamos revisando cuidadosamente cada candidatura. Faremos o possível para analisar no menor tempo possível e entraremos em contato caso o perfil seja selecionado para a próxima etapa do processo de seleção.
