### ISSUE TITLE
[Homeoffice] Front-end Software Engineer @ iSecurity

### ISSUE THREAD

**Issue by rios0rios0** [frontendbr/vagas#7755]
## Our Company

Look at [our Linkedin page](https://www.linkedin.com/company/isecurity-inc./mycompany/), please.

## Description

We're creating a big platform to integrate security, compliance, and analysis tools across more than 100 huge customers. We receive and analyze around 5TB each day in our SOC team. And we're responsible to do more than 3 thousand pentests each year.

We are seeking a skilled and experienced Software Engineer to join our team. The successful candidate will be responsible for designing, developing, testing, and maintaining software applications. They will also be responsible for ensuring the software meets the highest quality, performance, and security standards. The Software Engineer will work closely with other members of the development team, including project managers, architects, and quality assurance professionals. They will report to the Head of Engineering.

**Key Responsibilities**

- Develop high-quality software using best practices such as DDD, SOLID, Unit Testing, Clean Code, and Clean Architecture
- Collaborate with other members of the development team to design and implement software solutions that meet customer needs
- Write and maintain technical documentation, including design specifications, user manuals, and test plans
- Participate in code reviews to ensure the software meets the highest standards of quality and performance
- Continuously improve software development processes, tools, and techniques
- Implement and maintain CI/CD pipelines to ensure rapid and reliable software delivery
- Develop and maintain database migration scripts to ensure smooth database upgrades and schema changes
- Stay up-to-date with emerging trends and technologies in software development

## Place

Home office

### Hard skills:

- At least 2 years of experience in software development
- Strong proficiency in JavaScript and TypeScript, especially with React (Redux or other)
- Good understanding of software development best practices, including DDD, SOLID, Unit Testing, Clean Code, and Clean Architecture
- Familiarity with agile software development methodologies and tools, such as Jira and Confluence
- Experience with CI/CD tools, such as GitLab
- Desired to have experience with NoSQL databases, like ElasticSearch
- Excellent communication skills, including the ability to speak and write in English fluently
- Strong analytical and problem-solving skills, with attention to detail and the ability to work independently or in a team environment

**Differential:**
- OSS contributions

### Soft skills:
- You must know how to work with CodeReview.
- Working with a severe pipeline is not an issue for you.
- Your ability to speak in English is enough to communicate.
- Working with a small team requires very open communication, and you like that.

## Benefits

International experience.
Competitive salary, from **1,500 CAD to 4,000 CAD** (example of wage at the company).

## Hiring

You must have a CNPJ.

## How to apply?

Please, send an e-mail to: `felipe.rios at isecurityconsulting dot com` with your Linkedin and GitHub links. Set the "Frontend Software Engineer Position" as the subject.

## Feedback time

We answer you at least 2 weeks after the first contact.
If you didn't receive any answer, please send an e-mail to the same email as above.

If you meet the above requirements and are passionate about software development, we encourage you to apply for this exciting opportunity to work with our team of talented professionals.

## Labels
- Frontend
- JavaScript
- OpenSearch
- Security

#### Allocation
- Home office

#### Regimen
- PJ

#### Level
- Mid-level
- Senior
- Specialist

**Comment by rmc3408** [comment]
@rios0rios0 Eu tenho todos os requesitos e moro no Canada.

**Comment by marcosaurelioo** [comment]
Applied!

**Comment by marcosaurelioo** [comment]
@rios0rios0 Applied!

**Comment by iamrosada** [comment]
This position still open ?

**Comment by iamrosada** [comment]
That email doesnt work, please try to change
