### ISSUE TITLE
[REMOTO] Sr Frontend Developer (Angular) na Invillia

### ISSUE THREAD

**Issue by gihhlazaro** [frontendbr/vagas#7757]
**INVILLIA**
Aproxime-se. A Invillia não apenas transformou a forma como as empresas mais revolucionárias do mundo criam e desenvolvem estratégias, negócios e produtos digitais.
Inovou também a maneira como pessoas apaixonadas por tecnologia, de qualquer lugar do planeta, podem interagir, evoluir, mais conectados do que nunca.
Para a Invillia, não importa onde você está. Se é um país grande. Ou uma cidade pequena. E sim a sua vontade. As suas ideias. O seu potencial.

O tamanho do seu talento_

**RESPONSABILIDADES E ATRIBUIÇÕES**
● Construir soluções com padrões de qualidade de código;
● Criar funcionalidades pensando na performance, escalabilidade e segurança;
● Implementar testes unitários e de integração;
● Manter e criar documentações dos serviços;
● Realizar correções de bugs;
● Participar das reuniões da equipe.

**REQUISITOS E QUALIFICAÇÕES**
● Conhecimento em Typescript e Angular versão 14 ou superior;
● Conhecimento em Layout Responsivo;
● Conhecimento em testes unitários;
● Conhecimento em versionamento de código utilizando Git.
● Boas práticas na escrita de código (Clean Code, linters);
● Conhecimentos em Arquitetura de Software;
● Gerenciamento de dependências com NPM e/ou YARN;
● Conhecimento em Github;
● Uso do padrão “feature flag”;
● Experiência na implementação de ferramentas de “tracking”, ou “tagueamento” (por exemplo: Google Analytics, Google Tag Manager);

Será um **diferencial** se tiver experiência com:
● Conhecimento dos riscos comuns de segurança (OWASP);
● Nest.js.

**LOCAL**
Full remoto

**REGIME**
CLT + benefícios

**COMO SE CANDIDATAR**
Enviar o currículo atualizado para: [selecao@invillia.com](mailto:selecao@invillia.com)

**Comment by davicruzgympass** [comment]
Angular ou React, angular não consta como requisito

**Comment by filipefpaulo** [comment]
Enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
