### ISSUE TITLE
[Remoto] Front-end Tech Lead na SambaTech

### ISSUE THREAD

**Issue by daiaoli** [frontendbr/vagas#7758]
## Nossa empresa

A Samba está buscando uma **pessoa Tech Lead** para agregar ao nosso time! Para essa oportunidade buscamos uma pessoa para atuar em **regime CLT e 100% remoto**. Procuramos alguém com propósito forte e que esteja disposta a trabalhar em ambiente colaborativo e dinâmico, pronto para crescer profissionalmente junto com a nossa equipe fora da curva! A Samba gosta de fazer a diferença sempre e nosso time é o responsável para que isto aconteça! Por isso, a gente espera que você seja uma pessoa apaixonada por tecnologia, assim com a gente! Todas as nossas vagas também se aplicam a pessoas com deficiência, então fique à vontade para se candidatar!

## Descrição da vaga

- Liderar tecnicamente o time de desenvolvimento auxiliando a execução das tarefas para entrega do produto;
- Analisar e definir os requisitos técnicos para atender às necessidades de negócio;
- Conduzir reuniões com o cliente para discutir questões técnicas dos requisitos, visando a assertividade da entrega;
- Desenvolver os novos módulos (front-end) para evolução do produto;
- Revisar o código e artefatos entregues para garantia da qualidade;
- Gerar documentação técnica sobre o produto.

## Local

Remoto, Brasil.

## Requisitos

**Obrigatórios:**

- Expertise de desenvolvimento em alguma linguagem: Javascript com React;
- Arquitetura baseada em Microserviços;
- Padrões de projeto;
- Conhecimento em cloud computing e orquestração de containers(Docker, Kubernetes...)
- Conhecimento e experiência com web vitals.
- Experiência com CI/CD. (github actions, dangerjs, linting, chromatic)
- Conhecimento em Testes unitários e testes de Integração;

**Desejáveis:**

- Conhecimento em métricas aplicadas ao desenvolvimento software;
- Desenvolvimento de Produto.

## Benefícios

- Ambiente criativo e inovador;
- Clima leve e descontraído;
- Horário flexível;
- Home office
- Auxílio home office
- Plano de Saúde;
- Plano Odontológico;
- Vale refeição/alimentação;
- Gympass; 
- Day off no dia do aniversário
- Seguro de vida;
- Ways Education - Atividades extracurriculares para os filhos;

## Contratação

CLT.

## Como se candidatar

Se inscreva pelo link: https://sambatech.compleo.com.br/Visualizar/153331

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.
E-mail para contato em caso de não haver resposta: daiana.oliveira@sambatech.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by kvnol** [comment]
Enviado!
