### ISSUE TITLE
[Belo Horizonte ou remoto] Front-End Developer na Melhor Plano

### ISSUE THREAD

**Issue by felipembyrro** [frontendbr/vagas#776]
## Sobre o Melhor Plano
Melhor Plano é uma solução que ajuda os consumidores a tomarem a melhor decisão na contratação de serviços. Nossa visão é ser a principal referência para consumidores encontrarem economias em sua conta, em diversos serviços. Para isso, precisamos de tecnologia de ponta, utilizando crawlers e inteligência artificial para comparar e monitorar as contas de nossos usuários. Queremos ser uma das referências de tecnologia no país!

Atualmente, somos os líderes em comparação de telefonia no Brasil e já ajudamos quase 2 milhões de brasileiros a economizar com planos de celular, banda-larga, fixo, tv e combos!

## Vaga Desenvolvedor Front-End
Buscamos um talento para compor o time de desenvolvimento do Melhor Plano. Candidato além de ser dinâmico, deverá ser pró-ativo e saber trabalhar em equipe.

O stack do Melhor Plano hoje é composto por:

- Front-end com React e AMP
- Node
- Typescript
- MongoDB

Tem interesse em trabalhar em uma startup em crescimento acelerado e que tem como objetivo ajudar milhões de pessoas a economizar?

## Desafios e responsabilidades
Aqui são algumas coisas que você irá se envolver:

- Desenvolvimento de páginas otimizadas para SEO e responsivas
- Desenvolvimento de páginas utilizando AMP, HTML e CSS
- Desenvolvimento de páginas em React
- Integração do front-end com o back-end
- Participar de testes de usuário
- Realizar testes A/B para otimizar conversões
- Desenvolvimento de testes automáticos

## Sobre você
O que precisamos

- Experiência com desenvolvimento páginas web responsivas
- Experiência com páginas Web responsivas
- Confortável com desenvolvimento no Mac ou Linux
- Inglês
- Experiência trabalhando com profissionais de design e UX, sendo capaz de transformar designs apresentados em Photoshop em soluções web funcionais
- Excelente capacidade organizacional e pró-atividade para trabalhar de forma independente.
- Capacidade de analisar números e tomar decisões baseada em dados
- Foco em objetivos e resultados. Somos muito orientados a resultado, você e todo o time será cobrado por isso!
- Gostar de aprender. Não sabemos fazer tudo, mas somos apaixonados por aprender a fazer algo novo.
- Gosta de fazer seu trabalho de forma eficiente. Precisamos criar processos e sistemas que nos permitam criar algo maior que nós mesmos.
- Acredita que mais importante do que suas credenciais acadêmicas é o que você faz bem e gosta de fazer.

## Bônus

- Experiência com React, AMP ou Typescript
- Experiência com criação de interfaces com foco UX
- Experiência com design de interfaces
- Experiência com testes de usabilidade

## Mais sobre o Melhor Plano
O comparador do Melhor Plano foi lançado em março de 2016 e desde lá tivemos um crescimento acelerado, chegando a impactar quase 2 milhões de pessoas com nosso site.

Fomos uma das startups selecionadas, dentre mais de 3000 empresas do mundo, para participar do programa de aceleração Startup Chile, em Santiago - Chile.

Atualmente fazemos parte do [SEED](http://seed.mg.gov.br/), aceleradora com 40 startups de diferentes partes do Brasil e do Mundo. Oportunidade única de se envolver em uma comunidade incrível de startups. Recentemente fomos destaques em eventos internacionais de startups como o [SeedStars](https://www.seedstarsworld.com/summit/) e o [Startup Games](https://ioasys.com.br/startupgames/).

- Acreditamos que todo mundo poderia fazer mais do seu dinheiro se tomar uma decisão mais informada.
- Colocamos nossos usuários em primeiro lugar. Ajudamos nossos usuários de forma imparcial, mesmo que isso signifique não ganhar dinheiro.
- Acreditamos que a transparência é bom negócio. Ela ajuda os consumidores a tomarem decisões com mais segurança e, ao mesmo tempo, torna o fluxo de venda de nossos parceiros mais eficiente.
- 

Faça parte do time!
Estamos em crescimento acelerado e precisamos de um bom time para entregar economia e tecnologia de ponta para nosso usuários.

## Benefícios

- Salário baseado na experiência (R$3.000 - R$6.000 - você pode preencher expectativa salarial na aplicação);
- Flexibilidade de horário;
- Trabalhe parte do tempo de onde quiser - seu computador e boa internet é o suficiente 😉; A única obrigação de estar presente fisicamente são as reuniões criativas, a maior parte do tempo de execução pode ser feito remoto, ou no nosso escritório. Mas isso não significa que deixamos de comunicar constantemente.
- Oportunidade de trabalhar diretamente com fundadores de uma startup que cresce rapidamente.

## Como aplicar: melhorplano.net/vagas

- [Acesse esse link para aplicar (respostas em inglês ou português)](https://airtable.com/shrotro0R03iL8UU7)
- Preencha o formulário do link.
- Aguarde que entraremos em contato. Pode demorar algum tempo, mas damos retorno mesmo para quem não passou para a próxima fase.
- A segunda fase será uma atividade prática de desenvolvimento para entender como você programa.
- A última fase será uma entrevista com o time do Melhor Plano. Parte da entrevista será técnica e outra parte de alinhamento cultural.

Boa sorte!

## Labels

- CLT

**Comment by HaluDeCassia** [comment]
Que vaga bacana. Vou me candidatar 👍

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
