### ISSUE TITLE
[Remoto] Front-End Developer Next.JS Pleno na Andra Sistemas

### ISSUE THREAD

**Issue by andrasistemaserp** [frontendbr/vagas#7762]
## Nossa empresa

A Andra Sistemas está a 28 anos no mercado, sendo uma empresa movida pela paixão por programação, inovação, tecnologia e atendimento de excelência que atua exclusivamente no desenvolvimento de sistemas ERP e aplicações de integração voltadas para micro e pequenas empresas de diferentes ramos de atividade.

Somos comprometidos com os desafios da TI dos nossos clientes, trabalhando em ambiente horizontal e colaborativo, com autonomia e foco no cliente.

## Descrição da vaga

Buscamos um profissional Front-End Pleno que seja apaixonado por desenvolvimento, inovação e novas tecnologias, para integrar nosso time em projetos baseados em Next.JS

Atividades e Responsabilidades:
- Desenvolvimento, manutenção e revisão de sistema ERP
- Desenvolvimento de novas funcionalidades e melhorias
- Atuará na análise, desenvolvimento e manutenção de projetos novos e existentes, testando, corrigindo, utilizando códigos limpos (clean code), visando a manutenibilidade, escalabilidade, performance, disponibilidade e segurança

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Formação superior completa ou cursando em Ciências da Computação, Engenharia da Computação, Tecnologia da Informação, Análise de Sistemas ou áreas afins
- Experiência em desenvolvimento de aplicações Web em HTML 5, CSS 3, JavaScript, React.JS, Next.JS, Material UI
- Experiência de 3 anos ou mais com React.JS ou Next.JS
- Experiência em desenvolvimento de sites responsivos
- Experiência em consumo de APIs RESTful (usando JSON e/ou XML)
- Experiência em JWT para autenticação
- Experiência em ferramentas de versionamento de código (Git, GitHub, GitLab)
- Experiência em integração contínua (CI/CD)
- Conhecimento em metodologias ágeis (Scrum, Kanban, OKR\'S)
- Possuir compromisso com prazos, senso de responsabilidade com a equipe, capacidade de auto-gestão no trabalho em home-office
- Ser organizado, colaborativo, criativo, questionador, comunicativo, opinar em soluções e gostar compartilhar experiências e absorver conhecimento
- Se preocupar com o cliente que está utilizando aquilo que desenvolvemos
- Manter-se atualizado e sempre estar por dentro de novas tecnologias
- Imune a stress
- Sentimento de dono no que atua

**Desejáveis:**
- Conhecimento em integração para emissão de documentos fiscais eletrônicos (NF-e, NFC-e, NFS-e, SAT CF-e, etc.)
- Conhecimento em sistemas ERP
- Conhecimento em Typescript
- Conhecimento em bancos de dados (MySQL, SQL, MongoDB, Oracle, etc.)
- Conhecimento em Node.JS
- Conhecimento em UI e UX (Figma, Photoshop, etc.)
- Conhecimento em desenvolvimento para versão mobile (Android e/ou iOS)
- Conhecimento em serviços Cloud (AWS, GCP, Azure, etc.)
- Conhecimento em Delphi/Pascal

**Diferenciais:**
- Experiência em TDD (Test Driven Development)
- Experiência em algum projeto, seja opensource ou não, criado do zero no GitHub/GitLab com contribuições relevantes
- Experiência em desenvolvimento de aplicação completa (Front + Back + DB)

## Contratação

PJ

## Como se candidatar

Interessad@s favor preencher o formulário no link abaixo:
https://www.andrasistemas.com.br/contato-colaborador/

## Labels
- 🏢 Flexível
- 🏢 Remoto
- 👨 Pleno
- ⚖️ PJ
- 💰 4k-6k

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by pedrolima4** [comment]
Pleno, PJ, 4k... digo mais nada.

**Comment by andrasistemaserp** [comment]
@pedrolima4, pesquisamos a média salarial e o que estamos oferecendo está dentro da faixa.

**Comment by rafaelst2000** [comment]
> PJ 4-6k Pleno
> Imune a stress

virge

**Comment by rafaelst2000** [comment]
> Pleno, PJ, 4k... digo mais nada.

"Imune a stress" imagina a bomba kkkkk

**Comment by andrasistemaserp** [comment]
@devFelipeFranca, recebemos sua candidatura. Obrigado!

**Comment by pedrolima4** [comment]
@andrasistemaserp Me manda o link do site que você pesquisou, por favor, pq essa média tá uns 10 anos atrasada 😄

**Comment by pedrolima4** [comment]
Sem falar que uma empresa que precisa pesquisar a média salarial de um cargo, não que vai saber o real valor que esse profissional vai agregar.

**Comment by pedrolima4** [comment]
Sem falar que uma empresa que precisa pesquisar a média salarial de um cargo, nunca que vai saber o real valor desse profissional para sua empresa.

**Comment by devFelipeFranca** [comment]
@pedrolima4 , dado a natureza da empresa junto a vaga, acredito que este valor o próprio developer terá liberdade de construir, com sua estima e resultados, isto que me fez gerar interesse na vaga, onde o crescimento seja meritocrático, ja atuei em empresas com salários maiores, que 3 anos depois, não obtive valorização nem reconhecimento, acredito que nem todo "passo para tŕas" deva ser visto como negativas.

**Comment by devFelipeFranca** [comment]
@andrasistemaserp  Aguardo o contato.

**Comment by StoicDev01** [comment]
CV Enviado!

**Comment by andrasistemaserp** [comment]
@pedrolima4, acho importante a pesquisa da média salarial para se ter um parâmetro de modo a empresa saiba se poderá ou não fazer a contratação. 

Seguem nossas pesquisas, essa é a realidade no Brasil:
https://programathor.com.br/salario-programador-react
https://br.talent.com/salary?job=front+end+pleno
https://www.glassdoor.com.br/Sal%C3%A1rios/brasil-react-developer-sal%C3%A1rio-SRCH_IL.0,6_IN36_KO7,22.htm?clickSource=searchBtn
https://chat.openai.com/share/18a7d15f-d4cd-4dc7-be01-fcc7f825083d

**Comment by michelwene** [comment]
@andrasistemaserp currículo enviado!
