### ISSUE TITLE
[Remoto e Internacional] Senior Front-End Engineer na Turing (salário até U$D 150.000 / ano)

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#7766]
## About

A fast-growing company that is determined to help businesses drastically improve their services and experience with the help of modern technologies, is looking for a Senior Front-End Engineer.

The engineer will be tasked with creating user interface components for the product and maintaining them throughout the whole product lifecycle. The company is integrating modern and cutting-edge solutions while enabling industrialists, engineers, and coworkers to experience digital transformation in a real production environment. This is a great opportunity for developers to prove themselves while working in a challenging environment. 

**Job Responsibilities:**

Work with the product team to implement fresh concepts and contribute to the delivery of software that revolutionizes the industry
Write bug-free programs that follow best practices and coding standards while meeting the functional requirements at scale
Develop new product features with a focus on front-end development and architecture
Create applications that are fast, effective, and slick, going above and beyond user expectations

**Job Requirements:**

- Bachelor’s/Master’s degree in Engineering, Computer Science (or equivalent experience)
- At least 3+ years of relevant experience as a front-end engineer
- Extensive experience working with Node.js, TypeScript, and JavaScript
- Fluent in conversational and written English communication

## Candidatura
Para se candidatar, você deverá acessar a[ url da vaga](https://bit.ly/3qRqTMB) diretamente no site da Turing e avançar no processo seletivo. 

Obs: esta vaga está sendo publicada pela [Remotar](https://remotar.com.br/?utm_source=github) em nome da Turing. A Remotar é uma plataforma de vagas remotas que ajuda seus clientes com a divulgação das posições abertas. No entanto, não somos responsáveis pelo processo seletivo das mesmas.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
