### ISSUE TITLE
[Florianópolis] Fullstack Developer na GEW Tecnologia

### ISSUE THREAD

**Issue by pcfmello** [frontendbr/vagas#7768]
## Nossa empresa

A GEW esta no mercado desde 2006, localizada no município de Pato Branco, Paraná, um do maiores polos tecnológicos do Brasil, atuando no desenvolvimento de sistemas que gerenciam e automatizam pequenas e médias empresas, em todos os processos no ramo de cada ramo de atuação, sendo: Comercio em Geral; Industrias; Madeireiras; Panificadoras; Materiais de Construção; Lojas de Vestuários; Auto Center, Auto Peças e Oficinas Mecânicas.
Nosso foco é oferecer um produto que garanta excelência em todas as funcionalidades, com o máximo de agilidade e principalmente segurança.
É dedicada ao desenvolvimento de produtos e serviços, software e hardware para o gerenciamento do cliente. Seus sistemas são completos, atende desde controle de estoque, financeiro, contabilidade básica e funcionários, também com todos relatórios gerencias para tomada rápida de decisões.

## Descrição da vaga

A GEW Tecnologia está procurando um Desenvolvedor Fullstack altamente qualificado e motivado para se juntar à nossa equipe na filial em Florianópolis. 
Se você tem experiência com algumas destas tecnologias, essa oportunidade pode ser ideal para você. 

Responsabilidades:
Desenvolver aplicativos web e móveis usando as linguagens descritas acima.
Criar e manter bancos de dados MySQL, escrever consultas SQL eficientes.
Colaborar com a equipe de desenvolvimento para projetar e implementar recursos novos e existentes.
Participar de reuniões para discutir requisitos, progresso do projeto e solução de problemas.

## Local

Escritório, Florianópolis, bairro à definir

## Requisitos

**Obrigatórios:**
- Experiência comprovada como desenvolvedor Fullstack.
- Conhecimento sólido de PHP, JavaScript, CSS, HTML, MySQL e SQL.
- Capacidade de trabalhar em equipe e se comunicar efetivamente.
- Forte atenção aos detalhes e habilidades de resolução de problemas.
- Capacidade de lidar com prazos e projetos simultâneos.

## Benefícios

CLT
- Ambiente de trabalho colaborativo e profissional.
- Oportunidade de crescimento e aprendizado contínuos.
- Flexibilidade de horários.
- Auxílio alimentação
- Vale transporte
- Birthday off
- No dress code

## Contratação

CLT ou PJ

## Como se candidatar

Se você está pronto para enfrentar novos desafios em uma empresa inovadora e em constante crescimento, envie seu currículo para contato@gew.com.br com o assunto "Desenvolvedor Fullstack". 
Aguardamos ansiosamente o seu interesse em fazer parte da nossa equipe.

## Tempo médio de feedbacks

Agradecemos a todos os candidatos pelo interesse, mas apenas os selecionados para entrevista serão contatados.

#### Alocação
- Alocado

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
