### ISSUE TITLE
[REMOTO - PJ] Front-end Developer Pleno - Jusfy

### ISSUE THREAD

**Issue by guilhermepiza** [frontendbr/vagas#7770]
## Nossa empresa
A [[Jusfy](https://www.linkedin.com/company/jusfy/)](https://www.linkedin.com/company/jusfy/) está em busca de um **Front End Developer Pleno** para compor o time! Somos uma startup jurídica que busca constantemente soluções para facilitar a vida dos advogados e advogadas brasileiros. Atuamos na área de tecnologia, desenvolvendo produtos e ferramentas que auxiliam na produtividade diária dos nossos clientes.

Somos uma empresa jovem, mas muito promissora. Alcançamos resultados expressivos de crescimento nos últimos anos e sabemos que temos ainda muito mais para conquistar. Buscamos profissionais que queiram fazer parte dessa trajetória junto conosco!

## Descrição da vaga
Responsabilidades:

- Desenvolver novas funcionalidades utilizando ReactJS e API REST;
- Escrever códigos limpos, de alta qualidade e fácil manutenção seguindo as boas práticas de desenvolvimento;
- Colaboração com a equipe de desenvolvimento e testes para o sucesso dos projetos;
- Colaborar com os times de UX/UI e Produtos para garantir a melhor experiência do usuário e resultados de negócio;
- Realizar code reviews, ajudando outros desenvolvedores a melhorar a qualidade do código;
- Corrigir bugs.

## Local
100% Remoto!

## Requisitos
Requisitos técnicos:

- Experiência em desenvolvimento de frontend utilizando ReactJS;
- Experiência em Typescript e API REST;
- Conhecimento de Styled Components e Context API;
- Experiência com controle de versão utilizando Git;
- Familiaridade com ferramentas de design e prototipação, como Figma e Sketch.

Desejável:

- Experiência com metodologias ágeis;
- Experiência em times de desenvolvimento de software ou empresas de tecnologia;
- Conhecimento em testes automatizados e ferramentas de integração contínua;
- Capacidade de contribuir com especificações técnicas para propostas de solução.
- Habilidade para trabalhar em equipe e boa comunicação;
- Boa habilidade de resolução de problemas e pensamento crítico;
- Capacidade de se adaptar a mudanças e aprender rapidamente.

## Benefícios
Oferecemos:

- 100% Remoto;
- Flexibilidade de horário;
- Ambiente de trabalho descontraído e inovador;
- Oportunidade de trabalhar em projetos desafiadores e com grande impacto.

## Contratação
Modelo de Contratação: PJ

## Como se candidatar
Se você é um Desenvolvedor Front End com boa experiência em desenvolvimento de software está buscando uma oportunidade desafiadora em uma empresa inovadora, envie seu currículo ou perfil do LinkedIn para [guilherme@jusfy.com.br](mailto:guilherme@jusfy.com.br)

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by hnrqsss** [comment]
Enviado
