### ISSUE TITLE
[REMOTO] Front-end Developer na Dvora Life

### ISSUE THREAD

**Issue by mariliatech** [frontendbr/vagas#7771]
## Nossa empresa

Dvora is a tech-first real estate development company providing a flexible backend system for residents that allow them to book events, spaces, and services, pay rent, live chat with customer care, and much more.

## Descrição da vaga

We are looking for a strong Frontend Software Engineer with Angular knowledge to join the team and help build and evolve our products. The initial project the candidate will be tasked with is to maintain Dvora's current corporate website which is developed using Angular at the FE, it has a middleware written in NestJS (NodeJS framework) that communicates with an API called Yardi, from which some data is being pulled from to render different elements on the website. In addition, the website also loads information from a headless WordPress CMS. There's also the possibility to rewrite the application from scratch to resolve potential issues that currently plague the SEO of the current website.

Over time, the candidate could also be part of the main development team and be assigned tasks for the core web application which is written in Angular.

## Local

Remoto

## Requisitos

**Obrigatórios:**
4y of professional work experience with Angular
Experience working with NestJS / NodeJs framework
Experience with e-commerce platforms, SEO, CMS and corporate websites
Proficiency in written and spoken English (B2, upper-intermediate)

## Contratação

PJ (contractor)
Salário: 2000-3000 USD (mensal)

## Como se candidatar

Se aplique aqui: https://link.olby.com/dvoralife178em

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: marilia@olby.com

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

**Comment by rafael-jordao** [comment]
Aplicação enviada

**Comment by viralatron** [comment]
@mariliatech 4y contrator é mesmo Júnior/Pleno??

**Comment by mariliatech** [comment]
É uma posição Pleno.

**Comment by VitorVeector** [comment]
Does these 4 years of experience have to be professional experience or can they include study and project creation as well?

**Comment by mariliatech** [comment]
Vaga preenchida.
