### ISSUE TITLE
Remoto - JCal Consultoria - Dev Full-Stack Flutter Pleno 

### ISSUE THREAD

**Issue by Claudiaantunesdelima** [frontendbr/vagas#7775]
PESSOA DEV. FULL-STACK FLUTTER PLENO 

🔆 Requisitos

🔸Comunicação com o time, cliente e usuário é essencial para a posição
🔸Mais de 3-4 anos com experiência em mobile
🔸 Terr 2-3 anos experiência em desenvolvimento nativo (ideal)
🔸É  imprescíndivel ter conhecimento em Flutter com Dart, experiência em GetX, ObjectBox para banco de dados e biblioteca padrão Dio para requisições
🔸Autogerenciamento e autodidatismo são requisitos importantes já que o trabalho é 100% remoto

🔆Diferencial

🔸Ter conhecimento em docker e containers e familiaridade com GitHub e conceitos de git são importantes
🔸O banco de dados utilizado é PostgreSQL; o sistema é modularizado e multitenant.

🔆Responsabilidades

🔸Execução de código, revisão de código e aprovação de códigos
🔸Refatoração de códigos
🔸Diferencial: conhecimento em UI/UX

SALÁRIO 
R$8k PJ
🏘️REMOTO 

📲Favor enviar o currículo para o WhatsApp 19 97816-4262 (Claudia) 

Me segue no LinkedIn e fique por dentro das oportunidades disponíveis👇🏻
https://www.linkedin.com/in/thisclaudia

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
