### ISSUE TITLE
[Internacional e Remoto] React Web Developer na Turing.com (até U$D 150k / ano)

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#7776]
## About
A U.S.-based company that is developing an innovative product to help businesses disrupt their industries and enter new markets, is looking for a React Web Developer. The selected candidate will be working closely with the CEO to make realistic projections with the team and make wise product management decisions. The company assists businesses in prioritizing insights and focusing more attention on issues and problem areas that actually mattered. This is a great opportunity for developers who are eager to learn and proactively seek clarification of the requirements.

## Job Responsibilities:

- Assist with business decisions by assisting in the technical evaluation of potential solutions and assisting in the decision to build or buy
- To validate the use cases, create robust, testable code, and conduct unit, functional, acceptability, and/or user tests
- When necessary, participate in quality assurance, and create test-driven code
- Work with and help manage a junior front-end developer to help complete this project
- Controlling technical debt
- Set clear, well-commented code that is effective so that other developers may use it
- Assess the trade-offs with the product manager
- Instead of just meeting the technical requirements, consider the requirements from the perspective of the user and develop solutions.

## Job Requirements:

- Bachelor’s/Master’s degree in Engineering, Computer Science (or equivalent experience)
- At least 3+ years of relevant experience as a software developer
- Extensive experience working with React and Web technologies
- Prolific experience with JavaScript Frameworks
- Extensive experience with Figma for prototyping
- Demonstrable experience working with TypeScript, HTML, CSS, and Relational databases
- In-depth knowledge of REST APIs, Docker, and Heroku for continuous deployment
- Strong understanding of Jest for testing and oAuth for authentication
- Extensive experience with Role Based Access Control (RBAC), Material UI components, and Web Accessibility (AA standards)
- Demonstrable experience working with Agile technologies
- Fluent in spoken and written English

## Candidatura
Para se candidatar, você deverá acessar a[ url da vaga](https://bit.ly/3pIuw7k) diretamente no site da Turing e avançar no processo seletivo.

Obs: esta vaga está sendo publicada pela [Remotar](https://remotar.com.br/?utm_source=github) em nome da Turing. A Remotar é uma plataforma de vagas remotas que ajuda seus clientes com a divulgação das posições abertas. No entanto, não somos responsáveis pelo processo seletivo das mesmas.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
