### ISSUE TITLE
[Internacional e Remoto] Sr Frontend React/Typescript Engineer na Turing.com (salário até U$D 150k / ano)

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#7777]
## Job description
A US-based start-up building an integration platform to create synergies among applications is looking for a Senior Front-end React/Typescript Engineer. The developer will work on delivering new projects and be responsible for extending the front-end codebases to support the new integration feature including expanding the functionality of the UI kit to support more interaction modes and adding new flows to the portal. The platform offers features such as encrypted token storage, cross-site request forgery (CSRF) mitigation, and an API that enables connections to different applications while obtaining access tokens in a few lines of code. The selected candidate will join the team and play a critical part in building the foundation for the future of the Front-end engineering team.

**Job Responsibilities:**

- Help developers build integrations more easily
- Contribute to the data engineering effort as well as building out a serverless computer platform
- Extend the front-end codebases to support new integration features. 
- Expand the functionality of the UI kit to support more interaction modes, and add brand new flows in the developer portal to enable low-code and no-code builds of integrations
- Writes clean, easy to understand code
- Manage a majority of the app's visual appearance, primarily by relying on Evergreen components
- Think through features from the customers perspective and delivers with the customer in mind

**Job Requirements:**

- Bachelor’s/Master’s degree in Computer Science(or equivalent experience)
- 6+ years as a professional software developer
- Significant professional experience with React
- Good command over front-end stack like Typescript and React while using the evergreen component library
- Knowledge of back-end stacks, such as Elixir and Phoenix frameworks and a PostgreSQL database
- Strong written and spoken communication skills
- Highly productive: able to ship new features and refactors quickly
- Must have a good eye for design and must be customer-oriented
- Must be a team player but capable of working independently  

## Candidatura
Para se candidatar, você deverá acessar a[ url da vaga](https://bit.ly/3NH7nduetamente no site da Turing e avançar no processo seletivo.

Obs: esta vaga está sendo publicada pela [Remotar](https://remotar.com.br/?utm_source=github) em nome da Turing. A Remotar é uma plataforma de vagas remotas que ajuda seus clientes com a divulgação das posições abertas. No entanto, não somos responsáveis pelo processo seletivo das mesmas.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
