### ISSUE TITLE
REMOTO: Front-end Pleno Web (React js) - GOING 2

### ISSUE THREAD

**Issue by MariaJuliaRicostiG2** [frontendbr/vagas#7779]
## Nossa empresa
A Going2 é uma startup que nasceu em 2012, com o propósito de levar tecnologia de ponta para todo o Brasil, focada em criar produtos que tenham como premissa, facilitar a vida das pessoas e empresas, através do desenvolvimento de Aplicativos, Sistemas e dos princípios de IOT (internet das coisas). Hoje, além de atender clientes nacionais também oferecemos nossos serviços para clientes internacionais, como por exemplo no Canada, Suíça e Estados Unidos.

## Descrição da vaga

**Atividades**

- Participar do processo de criação e evolução dos produtos e sistemas;
- Analisar problemas e propor soluções;
- Implementar provas de conceito e protótipos;
- Especificar sistemas, processos e APIs;
- Modelagem de dados;
- Planejamento e estimativa de desenvolvimento;
- Desenvolvimento e Testes;
- Versionamento organizado no Git;
- Participar dos rituais do time (SCRUM);
- Manutenção dos produtos e sistemas;
- Alinhamento com pares;
- Participar de comitês e grupos de acordo com suas especialidades;
- Cumprir entregas no prazo e com alta qualidade;
- Pode trabalhar sozinho ou em equipe como um líder;
- Pode configurar o ambiente de desenvolvimento sozinho;
- Tem iniciativa e busca maneiras diferentes de resolver problemas.

**Requisitos**

- Criação de código legível para outros desenvolvedores;
- Habilidades de otimização de código para torná-lo mais eficiente;
- Capacidade de quebrar as tarefas em tarefas menores;
- Revisar o código em detalhes;
- Encontrar bugs e propor plano de ação para correção;
- Executar várias tarefas em vários projetos de forma simultânea;
- Domínio das principais linguagens da stack;
- Orientar os desenvolvedores juniores;
- Capacidade de entender os requisitos de negócios e traduzi-los em requisitos técnicos;
- Conhecimento sólido de Javascript (Rect.Js);
- Conhecimento em integração com Node Js;
- Conhecimento em Postgres e Firebase;
- Conhecimento de Arquitetura em Camadas.

**Diferencial**

- Desenvolvimento em front-end Mobile;
- Conhecimento em Styled-components, Tailwindcss, Material Ui, Redux Toolkit, React Hook Form e Next Js.

**Benefícios**

- Convênio Médico Sul-América (sem custo para titular);
- Convênio Odontológico Sul-América (sem custo para titular);
- Gympass;
- Convênio com plataforma de idiomas (Fluency Academy);
- Plataforma de treinamento Udemy Business;
- Day-Off de aniversário;
- 15 dias de descanso remunerado;
- Plano de carreira.

**Outras informações**

- Horário: 09h às 18h;
- 100% Remoto;
- Contrato de prazo indeterminado;
- PJ.

## Como se candidatar

Por favor se inscreva no link: https://solides.jobs/vacancies/269290?__hstc=127459538.9e64525841c7891275c96cc45466cfc0.1688386959480.1689108912665.1689156552619.30&__hssc=127459538.2.1689156552619&__hsfp=3074800436

#### Alocação

- Remoto

#### Regime

- PJ

#### Nível

- Pleno

**Comment by gvao** [comment]
Enviado currículo, espero que gostem.

**Comment by rodrigolb01** [comment]
Currículo enviado.

**Comment by MariaJuliaRicostiG2** [comment]
Olá, obrigada por mandar seu CV.

Por gentileza, se cadastrar na nossa vaga. Acesse aqui.
<https://solides.jobs/vacancies/269290?__hstc=127459538.9e64525841c7891275c96cc45466cfc0.1688386959480.1688594631241.1688744424993.9&__hssc=127459538.61.1688744424993&__hsfp=3074800436>

OBS: As inscrições que não forem feitas pelo link, serão automaticamente
desconsideradas.

Obrigada.

Em qui., 6 de jul. de 2023 às 15:35, rodrigolb01 ***@***.***>
escreveu:

**Comment by natamartins** [comment]
Currículo enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
