### ISSUE TITLE
[Remoto / Freela] Front End Developer na IUOFF

### ISSUE THREAD

**Issue by Adihelen** [frontendbr/vagas#778]
## Descrição da vaga

Projeto Plataforma de Viagens

## Local

Remoto

## Requisitos
- Conhecimento avançado de CSS3, HTML5 e Javascript;
- Experiência com gulp;
- Conhecimento básico de node js;
- Boa experiência na construção de websites responsivos/adaptáveis para mobile;
- Versionamento de código usando git.

## Diferenciais
- Conhecimento do framework VUE Js (SPA);
- Conhecimento de Restful api;		
- Conhecimento de razor .net 
- Experiência na codificação do frontend em projetos .net core MVC	;

## Contratação

Por favor envie um email para contato@iuoff.com com seu CV anexado - enviar no assunto: Vaga Front-End. Se possível incluir portfólio.

## Labels

- Freela
- Remoto - Total
- Sênior

**Comment by vinyguedess** [comment]
Mandei

**Comment by laugustofrontend** [comment]
@Adihelen, mandei
