### ISSUE TITLE
[Remote] Senior Front-end Developer na Bitrefill

### ISSUE THREAD

**Issue by SharonLabel** [frontendbr/vagas#7781]
This is a fully-remote opportunity
**Please apply directly at: [*our careers site*](https://careers.bitrefill.com/jobs/1783534-frontend-developer)**

Bitrefill is the biggest and best crypto e-commerce site in the world. We are creating a circular economy, enabling people to opt out from the traditional banking system and choose freedom... We make it easy for people to live on crypto around the world.

Does this sound like something for you? Then keep reading :)

**Why are we awesome?**
Bitrefill believes in the freedom to work remotely and flexibly and we are built around this. But don’t fear, you will never feel lonely as you will have the opportunity to meet your coworkers in person at our team retreats every year. Some reasons people choose us are:

- Freedom to work from anywhere
- We pay and compensate well
- 25 days of paid annual leave
- Paid parental leave
- Health and remote workspace allowances
- Our team retreats consist of two get-togethers every year. (Stockholm in the summer and a warmer location in the winter)
- Curious about the Bitcoin country? We offer company-paid business trips to El Salvador.
- Central office in Stockholm
- We welcome the crypto curious and expert and are happy to help you learn and grow
- We have a super-talented and passionate team who believe in our mission

**Your Mission:**
As our Frontend Developer, you will work with the team to implement and improve the UI / UX of our web platform, enabling millions of people to take full advantage of the cryptocurrency financial revolution for the first time. The task is challenging - users from over 170 countries have different expectations, trust is an important issue, and there are plenty of UX challenges with everything involving Bitcoin.

**Your Responsibilities:**

- Responsibility for the UX, functionality and speed of our app and commercial platform
- Building and deploying new code, features and products, as well as maintaining and improving old code
- Working closely with our Communications and Management Teams to ensure optimal prioritization and streamlined deployment
- Be hungry to learn, fast to execute, do a lot with little, and care strongly about your product and users
- Be a team player and a good friend who will contribute to our unpretentious culture

**You bring with you:**

- You have a minimum of 3+ years’ of Frontend experience and 5+ years of general programming experience
- You have frontend development skills with a focus on React, JavaScript or preferably TypeScript
- Experienced in building mobile-focused responsive applications
- Experienced in on-page SEO, HTML5
- Experienced in working with HTTP protocol (especially HTTP/2) and CDN:s
- Skilled optimal usage of CSS
- A strong digital portfolio that demonstrates the above
- Strong written and verbal communication skills

It's a plus if you have:
A big influence on the product, so a good sense for UX / design is a strong advantage
Bitcoin experience is not a requirement - we’ll teach you what you need to know, but you need to have a passion for the movement

**We offer**
To become part of a passionate and talented team with high ambitions for a world where bitcoin is money for everyday use
A challenging workplace and a great education when it comes to everything involving cryptocurrency
Besides the salary thing ;-), awesome perks and benefits 
 

**Our Process**
Disclaimer
Please be aware of potential recruitment scams, Bitrefill will never ask you for money during the recruitment process.
All our communication happens via our official email addresses (@bitrefill.com) and only after applying via this Careers site.
Please watch out and stay safe!

We know, we know, the boring part...but it's really important and we highly suggest you don't turn your back on this opportunity because sometimes the train of the future only passes in our station once!

We are happy that you kept reading!!
Does it sound like you so far? Get your boarding pass and apply!

**Dear future colleague, high five for good life choices! We can’t wait to hear from you!**

1 - We’ll start with an online assessment that will take you only a little more than an hour to do it.

2 - Then we’ll get to know you a bit better in an interview with our HR Team! On this one, you don’t need to prepare anything, you just need to be yourself !

3 - Next up is a technical interview with our product team! It would be like a live coding session with our Devs while you can chat about all the techy parts of things.
 

4 - You are doing great and that leads you to the practical challenge that should take no more than a few days to a week to complete!

5 - Finally, the closing interview stage is where we might ask you for references contacts. This is also where we're gonna discuss your practical challenge, and all practicalities and hopefully make you an offer we also hope you can’t refuse.

You’re in!

**Comment by Remato** [comment]
applied!

**Comment by VitorVeector** [comment]
Does these 3 years of experience have to be professional experience or can they include study and project creation as well?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
