### ISSUE TITLE
[Remoto] Senior WordPress Developer (Part-time) [Internacional]

### ISSUE THREAD

**Issue by johanguse** [frontendbr/vagas#7786]
Job Title: WordPress Developer (WP Engine Experience)

## Job Description:
We are seeking a talented and experienced WordPress Developer who has a strong proficiency in working with WP Engine. As a WordPress Developer, you will be responsible for developing and maintaining WordPress websites for our clients, utilizing your expertise in WP Engine to ensure optimal performance and reliability.

## Responsibilities:
- Develop and customize WordPress websites using WP Engine as the hosting platform.
- Collaborate with designers and stakeholders to implement website designs and functionalities.
- Optimize websites for performance, speed, and responsiveness, leveraging WP Engine’s features and tools.
- Ensure the security and stability of websites hosted on WP Engine, implementing best practices and monitoring for any potential issues.
- Troubleshoot and resolve technical issues related to WordPress and WP Engine, such as plugin conflicts, theme compatibility, or performance bottlenecks.
- Stay up to date with the latest WordPress and WP Engine developments, trends, and best practices, and apply them to enhance the website development process.
- Assist in website migration and deployment projects, ensuring seamless transitions and minimal downtime.
- Collaborate with cross-functional teams, including designers, content creators, and project managers, to deliver high-quality WordPress solutions.

## Requirements:
- Proven work experience as a WordPress Developer with a focus on WP Engine.
- In-depth knowledge of WordPress architecture, themes, plugins, and customization techniques.
- Strong expertise in utilizing WP Engine’s hosting environment, including managing domains, SSL certificates, and backups.
- Proficient in PHP, HTML, CSS, and JavaScript, with the ability to write clean, efficient, and scalable code.
- Familiarity with version control systems, such as Git.
- Solid understanding of web standards, SEO principles, and responsive design.
- Ability to diagnose and resolve technical issues efficiently.
- Excellent communication and collaboration skills, with the ability to work effectively in a team-oriented environment.
- Attention to detail and a commitment to delivering high-quality work on time.
### Preferred Qualifications:
- Experience with other content management systems (CMS) and e-commerce platforms.
- Knowledge of website performance optimization techniques.
- Familiarity with UX/UI principles and usability best practices.
- Experience with website migration and deployment processes.

If you are a motivated and skilled WordPress Developer with hands-on experience using WP Engine, we invite you to join our team. Apply today and be part of an exciting environment where your expertise will contribute to the success of our client’s online presence.

## Benefits of the Role Opportunity:
- Global Exposure: Engage in diverse projects worldwide, providing a unique opportunity to broaden your professional horizon.
- Flexibility: Enjoy the convenience of flexible working hours, enabling a healthy work-life balance.
- Paid Time Off: Depending on the type of contract, avail the benefit of Paid Time Off (PTO).
- Part-time 10-20 hours per week
- Payment in US Dollars

## Contract
- PJ - Part-time (10-20 hours per week)

## Requisitos

**Obrigatórios:**
- Ingles intermediário
- 5 anos de experiência com desenvolvimento web
- 3 anos de experiência com WordPress

## Como se candidatar

Por favor envie um email para johanguse@gmail.com com seu CV e/ou portofolio - enviar no assunto: Vaga WordPress - Internacional

## Labels
- Senior
- Part-time
- WordPress

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by mvbarrios** [comment]
Hi, i just send my CV!

**Comment by Taleshs** [comment]
Sent!
