### ISSUE TITLE
[Curitiba] Front-end Developer na Rookau

### ISSUE THREAD

**Issue by nayaranichelle** [frontendbr/vagas#7788]
## Nossa empresa

A [Rookau ](http://www.rookau.com)é uma Plataforma de Gestão de Desempenho e Gestão Estratégica que contempla várias ferramentas em um só lugar. Tudo o que uma organização e um RH Estratégico precisam para planejar e gerenciar o desempenho da estratégia, processos, projetos e pessoas.

## Descrição da vaga

Buscamos uma pessoa com interesse em desenvolver suas competências relativas ao desenvolvimento de sistemas web, usando tecnologias modernas e de amplo uso no mercado.

## Local

Escritório, Presencial PR, CURITIBA, CENTRO

## Requisitos

**Obrigatórios:**
- Residir em Curitiba/PR
- Conhecimento em JavaScript
- ECMA Script 6
- CSS3
- HTML5
- SASS
- Ter boas noções de web design
- Domínio em Git

**Desejáveis:**
- Conhecimento em React, Webpack, NodeJS, NPM ou Yarn
- Conhecimento da metodologia Scrum

**Diferenciais:**
- Oportunidade de aprendizado
- Metodologias de planejamento estratégico
- Desenvolvimento ágil de sistemas com Scrum

## Benefícios

- Vale Refeição 
- Vale Transporte
- Ambiente descontraído em um dos melhores hubs de inovação do Brasil

## Contratação

PJ ou CLT, a combinar

## Como se candidatar

Por favor envie um email para rh@rookau.com com seu CV anexado - enviar no assunto: Vaga Front-end JR ou PLENO

#### Alocação
- Presencial, Curitiba PR

#### Regime
- CLT
- PJ

#### Nível
- Júnior e  Pleno

![JR - DEV VAGA](https://github.com/frontendbr/vagas/assets/137827237/8bd2b778-ab9f-41f7-8bf1-b2f16c1eade5)
![PLENO - DEV VAGA](https://github.com/frontendbr/vagas/assets/137827237/82e2b3e9-843a-45aa-b9a3-f68c9ab593fe)

**Comment by tascintra** [comment]
Boa tarde! Ficou meio confuso. A vaga inicialmente vai ser remota ou presencial?

**Comment by SaMatheus** [comment]
Ta com as tags de `remoto` e `São Paulo` , mas com obrigatoriedade de residencia em Curitiba? É o remoto com pequenos encontros 3x por semana no office?

**Comment by rafaelranery** [comment]
Enviado!

**Comment by joao160197** [comment]
é so presencial a vaga ?

**Comment by Jaumz** [comment]
Alguma possibilidade de atuação remota?

**Comment by owesleymauricio** [comment]
Boa tarde João, muito obrigado pela oportunidade,  mas atualmente estou
trabalhando.

Em ter., 8 de ago. de 2023 15:47, João Viana ***@***.***>
escreveu:

**Comment by Quelvinmp** [comment]
Enviado!!

**Comment by eng-gabrielscardoso** [comment]
Please update labels

**Comment by dev-pedro** [comment]
Enviado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
