### ISSUE TITLE
[Remoto ou Hibrido] Angular Developer Sr @RhitmoTech 💙

### ISSUE THREAD

**Issue by gabirecruiter** [frontendbr/vagas#7789]
## Rhitmo Tech

Somos a **RHITMO Tech** e aqui desenvolvemos tecnologia para pessoas! 💙

Um time que está sempre pronto para decolar e é capaz de criar e desenvolver projetos que mudam positivamente a vida das pessoas, solucionando problemas e transpondo obstáculos. Essa é a nossa missão e procuramos por talentos para compor o nosso time de tecnologia e nos apoiar nessa jornada, atuando com Desenvolvimento front-end Angular💻

Quer conhecer um pouco mais sobre nós? Nossas redes sociais: 📱

https://rhitmotech.com.br/
https://www.instagram.com/rhitmotech/
https://br.linkedin.com/company/rhitmotech

## Descrição da vaga:

- Desenvolver aplicações web de alta qualidade usando Angular, Angular Material com TypeScript.
- Criar componentes e módulos reutilizáveis para garantir um desenvolvimento eficiente e escalável.
- Implementar recursos interativos e responsivos, garantindo uma ótima experiência do usuário.
- Colaborar com a equipe de design para transformar requisitos em interfaces atraentes e funcionais.
- Trabalhar em conjunto com a equipe de desenvolvimento para garantir a integração perfeita com o back-end.
- Escrever código limpo e legível, seguindo as melhores práticas de desenvolvimento.

## Local

Estamos em **Belo Horizonte - MG**!

## Requisitos

- Experiência no desenolvimento de aplicações web usando Angular, Angular Material e TypeScript.
- Expertise em HTML, CSS e JavaScript.
- Capacidade de traduzir requisitos de negócio em soluções técnicas eficientes.
- Experiência com design responsivo e desenvolvimento cross-browser.
- Conhecimento sólido de padrões de design e arquitetura de software.
- Habilidade de resolução de problemas e depuração.
- Capacidade de trabalhar de forma independente e em equipe.
- Habilidade de comunicação verbal e escrita.

Será considerado um diferencial:

- Experiência com testes unitários e integração.
- Conhecimento de ferramentas de controle de versão, como Git.
- Familiaridade com metodologias ágeis de desenvolvimento, como Scrum ou Kanban.
- Experiência com outras tecnologias front-end, como React ou Vue.js.
- Conhecimento em UX/UI e design de interfaces amigáveis.

## Benefícios

_PJ:_
- Interrupção remunerada de 15 dias;
- Bonificação por indicação de Desenvolvedores;
- Revisões por ano na remuneração;

## Como se candidatar

Envie o seu currículo + pretensão para o e-mail: rh@rhitmo.com.br 📧

Pode se conectar comigo no LinkedIn também:
https://www.linkedin.com/in/mariagabrielacs/ 👩‍💻

### Nível

- Sênior

### Regime

- PJ

### Alocação

- Remoto
- Híbrido em Belo Horizonte

## Informações Adicionais

- Aqui na Rhitmo, temos nosso canal no Discord, onde podemos trocar informações e ter apoio na resolução de demandas.
- Em nossa sede, temos vídeo game para descontrairmos.
- Na Rhitmo, temos o LabSession! Um momento de compartilhar conhecimento. Profissionais da Tecnologia, Design, RH e outras áreas sempre trazem um pouco do seu dia a dia, facilitando a troca de informações e compartilhando novas tendências.
- Gostamos de nos encontrar! Uma vez por ano, reunimos toda a equipe aqui em Belo Horizonte-MG para comemorar as entregas do ano e planejar o próximo ano! Além de poder conhecer o restante do time, você vai conhecer a sede e comer aquele pão de queijo!

Essa vaga não faz sentido para você? Que tal compartilhar com alguém que possa se interessar?? 💡

**#VEMPRARHITMO!** 🚀👩‍🚀

**Comment by gabirecruiter** [comment]
⚠VAGA AINDA EM ABERTO!

**Comment by alessandrobferreira** [comment]
CV enviado 👍
