### ISSUE TITLE
[São Paulo] Front-End Developer Pleno na UP e-commerce solutions

### ISSUE THREAD

**Issue by isabellegalvao** [frontendbr/vagas#779]
## Descrição da vaga

Desenvolvimento e manutenção de aplicações de front end, sendo responsável pelo desenvolvimento e ajustes de telas em conjunto com outros desenvolvedores.

## Local

Alocado, próximo ao metrô Vila Prudente

## Benefícios

- Vale Refeição;
- Vale Transporte.

## Requisitos

**Obrigatórios:**
- Portfólio/Experiência como Front-End
- Ter bom conhecimento em HTML, CSS, JavaScript e Jquery
- Dominar Web Animation
- Otimizar Performance
- Pré processadores CSS
- Ter conhecimento de Git

**Desejáveis:**
- Boa comunicação com a equipe de Back-End
- SEO
- Sabe criar ambiente de desenvolvimento ou um Boilerplate para iniciar seus projetos facilmente

## Contratação

PJ a combinar

## Horário

9h30 às 18h30 (Flexível)

## A empresa

UP e-commerce solutions

## Se interessou?
Envie um e-mail para isabelle@upecommerce.com.br com CV, portfólio e assunto: Vaga Front-End Pleno

## Labels

- Alocado
- CLT
- PJ
- Pleno

**Comment by renanlara** [comment]
A vaga é até legal, mas esse horário aí é zuadin.
