### ISSUE TITLE
[Remoto e Internacional] Sr Frontend Developer Vue.js/React na Turing.com

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#7790]
## Nossa empresa

A rapidly growing platform offering a digital marketplace where logistics, retail, and hospitality companies can connect with freelancers, is looking to hire a Senior Frontend Developer. The candidate will join the skilled team of engineers and contribute to shipping high-quality software while initiating interesting and decent discussions. The developer will work closely with the design and backend teams to further improve the code quality, standards, and rapid production while maintaining the business goals. The company has worked with thousands of firms as well as over 100,000 registered workers and raised up to $4.7 mn so far. Candidates who can actively contribute to the growth of others while making an impact are well suited for this position.

## Descrição da vaga

- Build, identify and refactor quality features
- Ship high-quality software and initiate meaningful, decent discussions 
- Work productively with the team to deliver architectural decisions
- Establish priorities, set objectives, and provide guidance and feedback as required
- Align properly with the product owners and managers
- Contribute to developing an amazing team with the readiness for international adventures
- Collaborate with the design and back-end teams to further improve code quality, standards, and rapid production

## Requisitos

- Bachelor’s/Master’s degree in Computer Science (or equivalent experience)
- 5+ years of professional experience as a frontend developer and a JavaScript engineer
- Familiarity with both back-end and front-end technologies as well as a passion for front-end and JavaScript development
- Solid understanding of web application development including HTML, CSS, SASS/SCSS, Typescript, React, React Native and GraphQL
- Prior experience with multiple modern JS frameworks (Vue, Angular, React / React Native) with a framework-agnostic approach
- Strong communication skills and experience in stakeholder management
- Experience in (preferably international) marketplaces and working in a startup
- Track record of open-source contributions/projects on GitHub is preferred

## Contratação

PJ / Contrato

## Como se candidatar

Para se candidatar, você deverá acessar a [url da vaga](https://bit.ly/3XNBMLL) diretamente no site da Turing e avançar no processo seletivo.

Obs: esta vaga está sendo publicada pela [Remotar](https://remotar.com.br/?utm_source=github) em nome da Turing. A Remotar é uma plataforma de vagas remotas que ajuda seus clientes com a divulgação das posições abertas. No entanto, não somos responsáveis pelo processo seletivo das mesmas.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
