### ISSUE TITLE
OPORTUNIDADE REMOTA: FULL STACK PLENO GOING2

### ISSUE THREAD

**Issue by MariaJuliaRicostiG2** [frontendbr/vagas#7792]
## Nossa empresa

A Going2 é uma startup que nasceu em 2012, com o propósito de levar tecnologia de ponta para todo o Brasil, focada em criar produtos que tenham como premissa, facilitar a vida das pessoas e empresas, através do desenvolvimento de Aplicativos, Sistemas e dos princípios de IOT (internet das coisas). Hoje, além de atender clientes nacionais também oferecemos nossos serviços para clientes internacionais, como por exemplo no Canada, Suíça e Estados Unidos.

## Descrição da vaga

**Atividades**

- Participar do processo de criação e evolução dos produtos e sistemas;
- Analisar problemas e propor soluções;
- Implementar provas de conceito e protótipos;
- Especificar sistemas, processos e APIs;
- Modelagem de dados;
- Planejamento e estimativa de desenvolvimento;
- Versionamento organizado no Git;
- Participar dos rituais do time (SCRUM);
- Manutenção dos produtos e sistemas;
- Trabalhar em um ambiente ágil, altamente colaborativo e versátil;
- Cumprir entregas no prazo e com alta qualidade;
- Pode trabalhar sozinho ou em equipe como um líder;
- Pode configurar o ambiente de desenvolvimento sozinho;
- Tem iniciativa e busca maneiras diferentes de resolver problemas;
- Aplicar boas práticas de desenvolvimento de software em conjunto com o time;
- Levantar riscos e atuar na mitigação, aceite ou resolução dos problemas.

**Requisitos**

- Criação de código legível para outros desenvolvedores;
- Habilidades de otimização de código para torná-lo mais eficiente;
- Capacidade de quebrar as tarefas em tarefas menores;
- Executar várias tarefas em vários projetos de forma simultânea;ção para correção;;
- Executar várias tarefas em vários projetos de forma simultânea
- Orientar os desenvolvedores juniores;
- Capacidade de entender os requisitos de negócios e traduzi-los em requisitos técnicos;
- Linguagens: Node.Js, React.Js e React Native;
- Bibliotecas: Nest.Js, TypeORM;
- Banco de dados: MySQL, Stored Procedures e Functions;
- Diferenciais: banco de dados MongoDB, experiência com APIs do Google Maps e Docker;
- Diferenciais: GoogleCloud, Google Maps e Redux.

**Benefícios**

- Convênio Médico Sul-América (sem custo para titular);
- Convênio Odontológico Sul-América (sem custo para titular);
- Gympass;
- Convênio com plataforma de idiomas (Fluency Academy);
- Plataforma de treinamento Udemy Business;
- Day-Off de aniversário;
- 15 dias de descanso remunerado;
- Plano de carreira.

**Outras informações**

- Horário: 09h às 18h;
- Remoto;
- Contrato de prazo indeterminado;
- PJ.

## Contratação

PJ 

## Como se candidatar

Por favor cadastrar através do link: https://solides.jobs/vacancies/271665?__hstc=127459538.9e64525841c7891275c96cc45466cfc0.1688386959480.1689089942565.1689095502810.27&__hssc=127459538.12.1689095502810&__hsfp=3074800436

#### Alocação

- Remoto

#### Regime

- PJ

#### Nível

- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
