### ISSUE TITLE
[Remoto e Internacional] Tech Lead na Turing.com (salário anual de até U$D 150 mil)

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#7794]
## Nossa empresa

An emerging company that is creating financial tools to simplify investments and offer the most expansive investment opportunities to users, is looking for a Tech Lead. The selected candidate will be leading and contributing to the initiatives aimed at scaling the infrastructure, processes, systems, and automation. The platform consolidates all the funds from the domestic and foreign markets in one place, allowing users to concentrate on their alternative asset investment strategies. They have managed to raise $45K+ during their Pre-Seed round of funding. 

## Job Responsibilities:

- Create new features to improve the experience
- Participate in the process optimization
- Work with the product team to get better solutions
- Identify areas of improvement in the platform development

##Job Requirements:

- Bachelor’s/Master’s degree in Engineering, Computer Science (or equivalent experience)
- At least 3+ years of relevant experience as a Tech Lead
- Demonstrable experience with JavaScript, React, and Node.js
- Extensive Database experience with SQL
- Experience in building and supporting mission-critical user-facing systems
- Some knowledge of investment, strategy, and markets
- Highly motivated and eager to learn
- Fluent in written and spoken English

## Contratação

Contractor

## Como se candidatar

Para se candidatar, você deverá acessar a [url da vaga](https://bit.ly/3DgdvVc) diretamente no site da Turing e avançar no processo seletivo.

Obs: esta vaga está sendo publicada pela [Remotar](https://remotar.com.br/?utm_source=github) em nome da Turing. A Remotar é uma plataforma de vagas remotas que ajuda seus clientes com a divulgação das posições abertas. No entanto, não somos responsáveis pelo processo seletivo das mesmas.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
