### ISSUE TITLE
[Remoto e Internacional] Web Front-End Developer na Turing.com

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#7795]
## Nossa empresa

A VC-backed cybersecurity company supported by top-tier investors is looking for a Front-End Web Developer to be part of the founding team. The developer will be responsible for the front-end web development and collaborate with a group of highly skilled professionals to solve challenging problems and break through barriers. The company has developed solid principles centered around transparency, continuous learning, and customer obsession, with a dedication to transforming the identity and access management marketplace. This is a great opportunity for those who want to thrive in a startup environment and rise quickly through the ranks. 

## Job Responsibilities:

- Design and build efficient, intuitive front-end applications
- Collaborate with product managers, designers, & engineers to deliver quality products
- Assist and communicate with clients’ technical leadership, understand the requirements & execute them
- Work with a wide range of systems & technologies to solve end-to-end problems

## Job Requirements:

- Bachelor’s/Master’s degree in Engineering, Computer Science (or equivalent experience)
- At least 3+ years of relevant experience as a front-end developer
- Hands-on experience with modern UI frameworks such as Angular, React, and HTML5
- Experience working on CSS preprocessors
- Front-end web development experience with ReactJS or similar frameworks + NodeJS
- Portfolio of building visually appealing modern web apps.
- Understand architectural principles such as cloud-native micro-services, API first development, multi-tenancy, etc.
- Good problem solver, communicator, fluent in English, team player, and customer focussed mindset
- Hands-on experience with cloud providers, Docker, Kubernetes, Go, Python, etc. is nice to have
- UI design experience, CI/CD, as well as building infrastructure as code, databases (SQL, NoSQL, etc), and full-stack apps is a plus

## Como se candidatar

Para se candidatar, você deverá acessar a [url da vaga](https://bit.ly/3Og5ENU) diretamente no site da Turing e avançar no processo seletivo.

Obs: esta vaga está sendo publicada pela [Remotar](https://remotar.com.br/?utm_source=github) em nome da Turing. A Remotar é uma plataforma de vagas remotas que ajuda seus clientes com a divulgação das posições abertas. No entanto, não somos responsáveis pelo processo seletivo das mesmas.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
