### ISSUE TITLE
[Remoto e Internacional] JavaScript Engineer na turing.com

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#7796]
## Nossa empresa

A U.S.-based company that is redefining media intelligence and social listening solutions for gauging, maintaining, and enhancing brand reputation is looking for a JavaScript Engineer. The engineer will be responsible for developing solutions that are easy to manage, high-performing, dependable, secure, and cost-effective. The company is determined to provide customers with tangible solutions that will help businesses to make informed business decisions. The company has managed to secure $200mn+ in funding so far. 

## Job Responsibilities:

- Create a new website with a focus on server-side and user-facing features
- Develop reusable, high-quality code that can be used in multiple projects 
- Build a scalable, highly responsive user interface
- Accept responsibility for tasks and sub-features

## Job Requirements:

- Bachelor’s/Master’s degree in Engineering, Computer Science (or equivalent experience)
- At least 3+ years of relevant experience as a software engineer
- Extensive experience in JavaScript
- Prolific experience in React, Vue.js, and Angular.js
- Prior experience in Stencil and TSX files
- Fluent in verbal and written English

## Como se candidatar

Para se candidatar, você deverá acessar a [url da vaga](https://bit.ly/3NOTEl2) diretamente no site da Turing e avançar no processo seletivo.

Obs: esta vaga está sendo publicada pela [Remotar](https://remotar.com.br/?utm_source=github) em nome da Turing. A Remotar é uma plataforma de vagas remotas que ajuda seus clientes com a divulgação das posições abertas. No entanto, não somos responsáveis pelo processo seletivo das mesmas.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
