### ISSUE TITLE
[São Paulo] Desenvolvedor Front End - Estágio

### ISSUE THREAD

**Issue by SeuZeRicardo** [frontendbr/vagas#78]
## Descrição da vaga

A Agência Navigators (www.navigators.com.br) procura estudante de área digital para estágio.

## Local

Proximo ao metro Paraiso, São Paulo - SP

## Requisitos

Conhecimento em:
- HTML
- CSS
- Wordpress 
- Photoshop e Illustrator basico

Desejável
- Frameworks como Bootstrap, Foundation
- Drupal

## Contratação

Estágio

## Como se candidatar

Enviar curriculo e algum projeto já feito para ibsen@navigators.com.br

**Comment by SeuZeRicardo** [comment]
@LFeh Desculpe por não ter colocado a label.

**Comment by LFeh** [comment]
Relaxa @SeuZeRicardo, é eu que coloco! haha

Boa sorte.

**Comment by ytalobessa** [comment]
Legal, pena que é em SP.

**Comment by brunooomelo** [comment]
Vou me candidatar , SP é aqui perto kk

**Comment by SeuZeRicardo** [comment]
Vaga já preencida!

**Comment by LFeh** [comment]
Boa!

**Comment by camilatigre** [comment]
@SeuZeRicardo 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by SeuZeRicardo** [comment]
desculpe pela demora Camila!


A vaga foi preenchida, mas não pelo github.


att,.

Ricardo Carvalho


Enviado do Outlook<http://aka.ms/weboutlook>


________________________________
De: Camila Tigre <notifications@github.com>
Enviado: quinta-feira, 24 de novembro de 2016 07:24
Para: frontendbr/vagas
Cc: Ricardo Carvalho; Mention
Assunto: Re: [frontendbr/vagas] [São Paulo] Desenvolvedor Front End - Estágio (#78)


@SeuZeRicardo<https://github.com/SeuZeRicardo>

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

-
