### ISSUE TITLE
[CAMPINAS] Front-End Developer Sênior CONFIDENCIAL

### ISSUE THREAD

**Issue by alyssonadler** [frontendbr/vagas#780]
## Descrição da vaga
Responsabilidades
•	Gerenciar prioridades, prazos e entregas de projetos individuais.
•	Projetar, desenvolver, testar, implantar, mantém e aprimorar soluções de software.
Requisitos
•	Graduação (ou cursando) em Ciência da Computação, Engenharia de Software ou Sistemas de Informação (desejável)
•	Inglês intermediário ou avançado.
•	Experiência com HTML5, JavaScript (ES6) e CSS3.
•	Experiência em desenvolvimento com Polymer ou Vue
•	Experiência em automatização utilizando Gulp ou WebPack.
•	Experiência em desenvolvimento com Java ou Python.
•	Experiência com versionamento de código utilizando GIT.
•	Experiência com NodeJS.
•	Conhecimento em infraestrutura (HTTP2, CDN e AWS).
•	Conhecimento de PWA e Web Components.

## Local

Alocado no escritório em Campinas.

## Benefícios

- Padrão de CLT
- Assistência Médica, Vale Refeição e Vale Transporte.

## Requisitos

**Obrigatórios:**
- De 2 a 3 anos de experiência com Vue ou Polymer.

## Contratação

CLT

## Como se candidatar

Por favor envie um email para alyssonacn@hotmail.com com seu CV anexado - enviar no assunto: Vaga Dev Senior

## Labels

- Alocado
- CLT
- Sênior

**Comment by LFeh** [comment]
O nome da empresa não pode ser confidencial. Vocês podem informar?

**Comment by alyssonadler** [comment]
Bom dia Felipe!
Obrigado pelo alerta.
Infelizmente eu só posso falar a empresa para os candidatos que manifestarem interesse. Se for necessário retirar o anúncio, pode falar que eu retiro.

Vocês possuem algum banco de currículos que eu possa consultar?

Obrigado!

Em 1 de fev de 2018 10:28 PM, Felipe Fialho <notifications@github.com> escreveu:

O nome da empresa não pode ser confidencial. Vocês podem informar?

**Comment by LFeh** [comment]
Infelizmente vou precisar retirar. Fica pra próxima ;)
