### ISSUE TITLE
[Remoto] Front-end Developer React | Sênior na VAGAS.COM

### ISSUE THREAD

**Issue by gabrielleleitej** [frontendbr/vagas#7801]
## Nossa empresa
Vagas.com

Apresentação da empresa

Promover encontros de valor entre profissionais e empresas. É isso que nos move!

E é em busca do cumprimento desse propósito que somos os pioneiros na criação de uma tecnologia para R&S, criada há mais de 22 anos para otimizar os processos de contratação. E com isso, conquistamos mais de 23 milhões de currículos cadastrados em nossa base e mais de 2 mil clientes, de diferentes segmentos e tamanhos.

Na Vagas vivenciamos um modelo de gestão horizontal, onde você encontra a autonomia e o estímulo que precisa para se desenvolver na sua profissão e se sentir uma pessoa verdadeiramente realizada em sua vida.

Nós enxergamos valor na diversidade e temos a intencionalidade de ampliar a pluralidade em nossa empresa, seja por raça, identidade de gênero, orientação sexual, religião, deficiência, idade, nacionalidade, entre outros recortes.

Nosso objetivo é ter uma empresa composta por opiniões e visões de mundo diferentes, pois acreditamos que esse é o caminho para um futuro ainda mais justo para nós e para tantas outras organizações do Brasil.

Portanto, todas as pessoas são bem-vindas a se candidatarem às nossas vagas.

**#vidanaVagas**

## Descrição da vaga
DIA A DIA: 
- Desenvolverá interfaces responsivas e acessíveis utilizando React;

- Garantirá a melhor usabilidade e fidelidade do layout em parceria com Designers e UXs, entregando valor para o usuário;

- Definirá em conjunto com back-end os contratos de APIs;

- Participará de equipes multifuncionais e interdisciplinares, interagindo com profissionais de outras áreas da empresa;

- Participará de todo o ciclo de desenvolvimento do produto, passando, inclusive, pelas fases de concepção e análise de mercado;

- Fará a criação e evolução à Arquitetura de projetos;

- Fará a gestão compartilhada de sua equipe e do negócio;

- Atuará tanto com sistemas legados como com novas tecnologias;

- Compartilhará conhecimento e apoiará no desenvolvimento dos seus pares, fazendo mentoria dos membros mais juniores da equipe.
## Local
Remoto 

## Requisitos

**Obrigatórios:**
- Experiência comprovada com aplicações front-end em projetos complexos de mercado;

- Experiência sólida em HTML, CSS e Javascript;

- Sólidos conhecimentos de React;

- Boas práticas de desenvolvimento, com foco em qualidade, melhorias de performance, acessibilidade e escalabilidade;

- Vivência em projetos que implementem acessibilidade de forma ativa;

- Experiência com protocolo HTTP e APIs REST;

- Analisar e implementar interfaces de produto considerando UI e UX;

- Experiência com testes automatizados de unidade e de integração;

- Integração contínua: Entender de DevOps, saber escrever, modificar, aprimorar pipelines e afins;

- Docker: Entender o conceito e benefícios em usar conteinerização e ter capacidade de criar, manipular e escalar na prática;

- Bom relacionamento interpessoal e proatividade;

- Experiência com mentoria de membros da equipe.

**Desejáveis:**
- Experiência com diferentes padrões de projeto;

- Experiência com reutilização de recursos (componentização);

- Experiência com documentação;

- Experiência em TDD;

- Vivência com metodologias ágeis.
**Diferenciais:**
- projetos opensource

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ 34/dia
- Auxílio creche
- Auxílio Educação

**Diferenciais:**
- 2 horas de almoço
- monte a sua máquina como desejar
- frigobar sempre cheio :P
- sala de jogos
- ...

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para gabrielle.leite@vagas.com.br com seu Linkedin e Github - enviar no assunto: Vaga Front React

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: gabrielle.leite@vagas.com

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível

- Sênior

**Comment by victorbiasibetti** [comment]
a vaga é PJ ou CLT?

um dos diferenciais é `sala de jogos e frigobar sempre cheio` sendo que a vaga é remota?

**Comment by Ronicley** [comment]
> a vaga é PJ ou CLT?
> 
> um dos diferenciais é `sala de jogos e frigobar sempre cheio` sendo que a vaga é remota?

Fiquei na duvida tbm

**Comment by danieladuarteng** [comment]
Enviado

**Comment by AugustoMachado01** [comment]
Enviado
