### ISSUE TITLE
[Remoto] Front-end Developer Pleno na VAGAS.COM

### ISSUE THREAD

**Issue by gabrielleleitej** [frontendbr/vagas#7802]
## Nossa empresa
Promover encontros de valor entre profissionais e empresas. É isso que nos move!

E é em busca do cumprimento desse propósito que somos os pioneiros na criação de uma tecnologia para R&S, criada há mais de 22 anos para otimizar os processos de contratação. E com isso, conquistamos mais de 23 milhões de currículos cadastrados em nossa base e mais de 2 mil clientes, de diferentes segmentos e tamanhos.

Na Vagas vivenciamos um modelo de gestão horizontal, onde você encontra a autonomia e o estímulo que precisa para se desenvolver na sua profissão e se sentir uma pessoa verdadeiramente realizada em sua vida.

Nós enxergamos valor na diversidade e temos a intencionalidade de ampliar a pluralidade em nossa empresa, seja por raça, identidade de gênero, orientação sexual, religião, deficiência, idade, nacionalidade, entre outros recortes.

Nosso objetivo é ter uma empresa composta por opiniões e visões de mundo diferentes, pois acreditamos que esse é o caminho para um futuro ainda mais justo para nós e para tantas outras organizações do Brasil.

Portanto, todas as pessoas são bem-vindas a se candidatarem às nossas vagas.

#vidanaVagas

## Descrição da vaga
Como será seu dia a dia:

Desenvolvimento e manutenção de UIs: Com base em protótipos fornecidos por Product Designers, você será responsável por traduzir esse material em código, criando interfaces de usuário atraentes e funcionais para quem utiliza o Vagas.com e Vagas For Business.

Trabalho colaborativo com equipes multidisciplinares: você trabalhará em estreita colaboração com designers, pessoas desenvolvedoras back-end, Product Managers e stakeholders para garantir que nossos produtos atendam às necessidades das pessoas que usam Vagas.com e Vagas For Business, alinhadas com nossos objetivos de negócios.

Teste e depuração de aplicativos front-end: você realizará testes em diferentes navegadores e plataformas para garantir que nossas interfaces de usuário funcionem corretamente em todos os contextos. Além disso, você será responsável por identificar e corrigir bugs e problemas de desempenho.

Implementação de acompanhamento e melhorias de desempenho: Com foco na experiência do usuário, você trabalhará para otimizar a velocidade de carregamento e a eficiência de nossas interfaces de usuário.

Garantir a acessibilidade: Um aspecto fundamental do seu trabalho será garantir que nossos produtos sejam acessíveis às pessoas, independentemente de serem Pessoas com Deficiência ou não.

Em relação ao seu dia-a-dia, ele pode variar bastante dependendo da natureza do projeto em que você está trabalhando. No entanto, um dia típico na Vagas inclui:

Reunião frequente de status (stand-up): você provavelmente terá uma reunião com sua equipe para discutir o progresso do projeto, identificar obstáculos e definir prioridades.

Desenvolvimento: codificação de novas funcionalidades, refatoração de código existente ou correção de bugs. Você também poderá passar algum tempo revisando o código de colegas de equipe e fornecendo feedback construtivo.

Testes e depuração: esperamos que você dedique parte do seu desenvolvimento com escrita de testes do seu código. Além disso, ao criar ou alterar funcionalidades, é importante que você as teste em diferentes navegadores e plataformas, identificando bugs e trabalhando para resolvê-los.

Aprendizado e desenvolvimento profissional: como desenvolvimento front-end está sempre evoluindo, é importante reservar algum tempo para se dedicar à nossa Expedição, um incentivo para aprender sobre novas tecnologias, melhores práticas e nossa cultura.

Comunicação: você passará algum tempo se comunicando com o Círculo de Front-end, a equipe do seu projeto e stakeholders, principalmente por Slack, reuniões via Google Meet e, em alguns momentos, e-mail.

## Local
Remoto

## Requisitos

**Obrigatórios:**
Proficiência em HTML, CSS, JavaScript e React, as quatro tecnologias fundamentais do desenvolvimento web dentro da Vagas;

Compreensão de design responsivo: com a variedade de dispositivos e tamanhos de tela disponíveis hoje, é crucial que você seja proficientes em design responsivo, para garantir que as interfaces do usuário da Vagas funcionem bem em todos os contextos;

Experiência com controle de versão Git: trabalho colaborativo e o gerenciamento eficiente de diferentes versões do código;

Abertura para aprender sobre testes e os princípios de acessibilidade web: nossas UIs precisam ser acessíveis e confiáveis a todas as pessoas. Mesmo que você não tenha domínio das áreas de testes e acessibilidade, é fundamental que você tenha abertura para aprender a respeito;

Compreensão dos conceitos de UX/UI: mesmo que você não seja responsável pelo design de experiência e interface, é importante que você entenda esses conceitos para poder entender, implementar corretamente e validar o design e garantir, junto a Pessoas Designers, uma experiência positiva para quem usa nossos produtos.

**Diferenciais:**

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ X/dia
- Auxílio creche
- ...

**Diferenciais:**
 Conhecimento de TypeScript: estamos evoluindo nossos projetos para utilizarem TypeScript. Essa adoção tem nos ajudado a prevenir muitos erros comuns.

Familiaridade com bibliotecas e frameworks estado-da-arte: além de ser essencial ter experiência com React, ter trabalhado com Next.js ou Vite pode ser um grande diferencial;

Familiaridade com bibliotecas e frameworks legados: se você já trabalhou com Create React App (CRA), Esbuild e Webpack, pode ser útil para nos apoiar na evolução de nosso legado;

Experiência com Tailwind CSS: utilizamos Tailwind CSS na vagas para tornar o código CSS mais eficiente e fácil de manter. Porém, se você já trabalhou com SASS, LESS ou Styled Components, sua experiência também será util.

Conhecimento de SEO e Web Semântica: a compreensão das melhores práticas de SEO e Web Semântica (incluindo tags semânticas e rich data) pode ajudar a garantir que nossos sites sejam facilmente descobertos por motores de busca.

## Contratação

CLT

## Como se candidatar

Por favor envie um email para gabrielle.leite@vagas.com.br com seu LinkedIn e Github - enviar no assunto: Vaga Front Pleno

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: gabrielle.leite@vagas.com.br

#### Regime
- CLT

#### Nível

- Pleno

**Comment by Samuel-Amaro** [comment]
Enviado!

**Comment by Mraimundo** [comment]
Enviado!

**Comment by brunoliimas** [comment]
Enviado ☺️

Em qui., 20 de jul. de 2023 13:56, Mouzinho Raimundo <
***@***.***> escreveu:

**Comment by brunoliimas** [comment]
Enviado ☺️

**Comment by matheuslei** [comment]
Enviado ☺️

**Comment by YuriMont** [comment]
Enviado

**Comment by victoradler** [comment]
enviado

**Comment by matheusmcz** [comment]
Enviado! 💯

**Comment by carlos-morais1507** [comment]
Enviado! 👋

**Comment by matheusmcz** [comment]
Enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
