### ISSUE TITLE
[Remoto] Front-end Developer III (React) na SambaTech

### ISSUE THREAD

**Issue by daiaoli** [frontendbr/vagas#7803]
## Nossa empresa

A Samba está buscando uma pessoa **Frontend Engineer III (React)** para agregar ao nosso time! Para essa oportunidade buscamos uma pessoa para atuar em **Regime CLT e 100% remoto**. Procuramos alguém com propósito forte,  apaixonado(a) e altamente qualificado(a) para se juntar à nossa equipe. Você estará na linha de frente de um ambiente de produção acelerado e inovador, aplicando suas habilidades e experiência na construção de soluções de alta qualidade para nossos usuários. e que esteja disposta a trabalhar em ambiente colaborativo e dinâmico, pronto para crescer profissionalmente junto com a nossa equipe fora da curva! A Samba gosta de fazer a diferença sempre e nosso time é o responsável para que isto aconteça! Por isso, a gente espera que você seja uma pessoa apaixonada por tecnologia, assim com a gente! Todas as nossas vagas também se aplicam a pessoas com deficiência, então fique à vontade para se candidatar!

## Descrição da vaga

- Desenvolver e manter componentes da aplicação usando React.js;
- Construir e conectar APIs RESTful para integração com outros serviços;
- Implementar autenticação e segurança usando OAuth;
- Colaborar na arquitetura e implementação de micro frontends;
- Participar de revisões de código e fornecer feedbacks construtivos aos colegas;
- Trabalhar em conjunto com designers e desenvolvedores back-end para garantir uma experiência de usuário coesa e de alta qualidade.

## Local

Remoto, Brasil. 

## Requisitos

**Obrigatórios:**

- Proficiência em JavaScript moderno (ES6+), HTML e CSS;
- Experiência com OAuth e APIs RESTful;
- Experiência prática com arquitetura de micro frontends;
- Familiaridade com as melhores práticas de codificação, padrões de design e testes automatizados;
- Excelentes habilidades de resolução de problemas e atenção aos detalhes;
- Experiência com ferramentas de controle de versão, como Git.

**Desejáveis:**

- Conhecimento em TypeScript;
- Experiência com frameworks de teste como Jest ou Mocha;
- Experiência com bibliotecas de gerenciamento de estado como Redux ou MobX;
- Familiaridade com métodos ágeis de desenvolvimento (Scrum, Kanban).

## Benefícios

- Ambiente criativo e inovador;
- Clima leve e descontraído;
- Horário flexível;
- Home office;
- Auxílio home office;
- Plano de Saúde;
- Plano Odontológico;
- Vale refeição/alimentação;
- Gym Pass; 
- Day off no dia do aniversário;
- Auxílio Creche;
- Seguro de vida;
- Universidade Corporativa;
- Ways Education - Atividades extracurriculares para os filhos.

## Contratação

CLT + benefícios. 

## Como se candidatar

Pelo link: https://sambatech.compleo.com.br/Visualizar/157771

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.
E-mail para contato em caso de não haver resposta: daiana.oliveira@sambatech.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by matheusmcz** [comment]
Enviado! 💯

**Comment by Bruno-Goudric** [comment]
Issue precisa ser trocada para fechada segundo o link https://sambatech.compleo.com.br/Visualizar/157771 que se encontra com as vagas encerradas

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
