### ISSUE TITLE
[Florianópolis/REMOTO] Desenvolvedor(a) Full Stack | Flutter e Python na CondoConta

### ISSUE THREAD

**Issue by AmandaElena** [frontendbr/vagas#7805]
## Nossa empresa

**O Condoconta**
O CondoConta nasceu com uma proposta de ser o banco dos condomínios brasileiros. Fundada em 2019, a empresa se propõe a ajudar síndicos e administradoras com a gestão financeira de condomínios residenciais.

O negócio foi gestado durante um ano e começou a operar em abril de 2020. O Condoconta já soma 2000 condomínios clientes espalhados por todo Brasil.

Assim como nossos clientes, nosso time é diverso e conta com pessoas no país inteiro, trabalhando com autonomia, responsabilidade e transparência para mudar a vida de quem vive em condomínios através da gestão financeira e da tecnologia.

## Descrição da vaga

**Como será seu dia-a-dia**
Junte-se a esta equipe que está revolucionando tudo o que se conhece por gestão de condomínios no Brasil!
Você irá trabalhar com uma equipe de desenvolvimento experiente e colaborativa para construir aplicações e soluções de alta qualidade. 
Suas principais responsabilidades serão escrever código em Flutter e Python (dentre outras tecnologias), testar e depurar sistemas, além de colaborar com outros membros da equipe para melhorar os produtos.

**Seus desafios serão inúmeros, entre eles:**
 Desenvolver e manter aplicações em Flutter e Python
Colaborar e apoiar outros membros da equipe para desenvolver soluções inovadoras e manter o parque de aplicações existentes
Escrever código limpo, reutilizável e bem documentado
Realizar testes e depurar o código
Aprender novas tecnologias e ferramentas para aprimorar suas habilidades e conhecimentos.

**O que esperamos de você?**
5+ anos de experiência em desenvolvimento de sistemas;
Conhecimento Intermediário/avançado em Flutter/Dart:
3+ Anos de experiência;
Clean architecture, MVC, MVVM...;
Monorepo e Multirepo (packages);
Flavors;
Gerência de estado (GetX, MobX, Provider, Bloc...);
Consumo de APIs e secrets (SSM AWS);
SOLID, CLEAN, escalabilidade...;
Design patterns, Design system, Figma…
Experiência com deploys para web, desktop e mobile.
Conhecimento Intermediário/avançado em Python:
Frameworks FastApi, Flask, entre outros;
Uso (ou não) de ORM (SQLAlchemy);
Utilização de logs, incluindo o Sentry;
Conceito de Sessão de conexão com BD, commits, rollbacks...;
Conceito de login via token;
API’s REST;
AWS (SSM, S3, Elastic...).
Tratamento de Exceções;
Conhecer ferramentas: VS Code/Android Studio, Slack, Jira, Postman, Miro, Confluence, Git (incluindo CI/CD), DBeaver, MySql Workbench, VPNs;
Habilidade para escrever código limpo e reutilizável, sabendo dosar eficácia x eficiência x efetividade;
Conhecimento (incluindo modelagem de dados) em bancos de dados relacionais (MySql, MS SQL, Postgres...), SQL e PL/SQL;
Conhecimentos de HTML, CSS, JavaScript e alguma linguagem de desenvolvimento web;
Experiência com metodologias ágeis de desenvolvimento de software;

**O que é essencial você trazer?**
Organização e gerenciamento de tempo;
Capacidade de trabalhar em equipe e comunicar-se efetivamente com outros membros da equipe, prezando sempre pelo bom ambiente e visando as entregas;
Proatividade, team player e ter um desejo contínuo de aprender e crescer como desenvolvedor(a);
Colaboração e Respeito;
Flexibilidade e adaptabilidade.
 

**Você fará brilhar nossos olhos se tiver:**
Conhecimento de SalesForce;
Conhecimentos de DEVOps (Docker, Pipelines, Terraform, Kubernets...);
Conhecimento de Serveless (lambda);
Familiaridade com outras linguagens de programação, como Java, VB...
Boa escrita e documentação.

## Local
O modelo de trabalho é remoto. 
Caso você seja de Florianópolis e região, não é necessário nenhum tipo de alinhamento para ir ao escritório. Caso seja de fora, é necessário conversar com sua liderança sobre o real objetivo de ir à cidade, dado que a empresa arca com os custos de deslocamento e hospedagem.
O escritório do Condoconta possui 3 salas dentro da ACATE – Associação Catarinense de Tecnologia, na Rod. SC 401, Km4, Saco Grande, Florianópolis, SC.

## Contratação
Nova Cooperativa (Similar ao PJ)

## Como se candidatar
Temos dois meios de candidatura: 
1º me mandar seu CV/LKD junto com **sua pretensão salarial** por e-mail para amanda.almeida@condoconta.com.br
2º Se candidatar através do Link: https://condoconta.hire.trakstar.com/jobs/fk0x4o3/

### Nível
- Pleno

### Regime
- Nova Cooperativa

### Alocação
- Remoto
- Híbrido

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
