### ISSUE TITLE
[Internacional e Remoto] Front-End Engineer na Turing (3+ anos de xp)

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#7808]
## Job description

A U.S.-based company providing direct marketing, brand development, and media mix modeling services is looking for a Front-End Engineer. The engineer will contribute to building the landing page and providing mentorship and guidance to other members of the team. The company balances the ever-changing needs within the people, data, and media aspects to help clients meet their business goals. This full-time position will require some overlap with the PST time zone. 

## Job Responsibilities:

- Create new user-facing features for the company’s platform 
- Develop reusable, high-quality code and libraries that can be used in multiple projects
- Build a modern, highly responsive web-based UI that is in line with the company’s objectives 
- Accept responsibility for tasks and sub-features

## Job Requirements:

- Bachelor’s/Master’s degree in Engineering, Computer Science (or equivalent experience)
- At least 3+ years of relevant experience as a front-end engineer
- Extensive experience in HTML, CSS, and SASS/LESS
- Prolific experience in JavaScript and React/Vue
- Nice to have experience in Node.js
- Experience in PHP/WordPress is a plus 
- Prior experience in Adobe Target is nice to have 
- Experience with Google Optimize is preferred
- Fluent in verbal and written English

## Como se candidatar

Para se candidatar, você deverá acessar a [url da vaga](https://bit.ly/44R7lXN) diretamente no site da Turing e avançar no processo seletivo.

Obs: esta vaga está sendo publicada pela [Remotar](https://remotar.com.br/?utm_source=github) em nome da Turing. A Remotar é uma plataforma de vagas remotas que ajuda seus clientes com a divulgação das posições abertas. No entanto, não somos responsáveis pelo processo seletivo das mesmas.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
