### ISSUE TITLE
[Remoto] Front-end Developer Specialist  II na Grupo Boticário

### ISSUE THREAD

**Issue by Mcelinaa** [frontendbr/vagas#7809]
> Vaga Remota 

#Grupo Boticario#

O que é o gb.tech?

Somos o time de tecnologia do GB e nosso espírito inquieto nos faz estar sempre de olho nas tendências futuras. A tecnologia é fundamental para revolucionar toda a nossa jornada, da pesquisa e desenvolvimento de produtos até a venda final para nossos consumidores - e é através dela que estamos construindo o melhor e maior ecossistema de beleza para o mundo.

Cada novo processo, lançamento e solução exigem eficiência, habilidade e inovação. Só assim é possível manter a velocidade e o dinamismo do nosso crescimento e entregar beleza em cada canto do Brasil e em mais de 15 países. E é isso que o time do gb.tech está fazendo no Grupo Boticário.

Temos o compromisso de construir um ambiente cada vez mais diverso e inclusivo. Valorizamos a Diversidade e estamos comprometidos com a promoção da inclusão e equidade em nossos times.

Essa ação faz parte de uma estratégia ligada aos nossos compromissos e fortalecimento de nossa cultura equânime.

Conheça mais sobre nossos compromissos em: https://www.umabelezadefuturo.com.br

## Descrição da vaga

Desenvolver interfaces de usuário altamente interativas, responsivas e eficientes;
Colaborar com a equipe de design para traduzir os requisitos visuais em código funcional;
Trabalhar em estreita colaboração com a equipe de desenvolvimento back-end para integrar o front-end com o servidor, aplicações e outros componentes do sistema.
Criar componentes reutilizáveis e modularizados que possam ser facilmente integrados em vários projetos;
Melhorar o desempenho das aplicações para garantir tempos de carregamento rápidos e uma experiência do usuário leve e otimizada;
Realizar testes e depuração de código para garantir a qualidade e a estabilidade das aplicações;
Estabelecer vínculos com outras áreas de negócios em diversos níveis da organização;
Ser responsável por implementar as melhores soluções de front-end para nossos clientes de forma colaborativa, visando sempre a melhor experiência de uso para nossos produtos;
Ser responsável por codar, realizar testes unitários, implantar e monitorar, além de garantir a qualidade e boas práticas de programação;
Manter documentação atualizada e atuar como mentor técnico com os outros desenvolvedores, compartilhando melhores práticas de programação com o time;
Buscar atualização sobre as tendências e tecnologias mais recentes no desenvolvimento front-end e propor melhorias técnicas para os projetos.
Aprimorar aplicações identificando oportunidades de melhoria;
Ter o sentimento de dono participando das decisões na implementação dos produtos;
Apoiar no desenvolvimento das soluções através de Code Review e Pair Programming.

#Remoto# 

## Requisitos

**Obrigatórios:**
Conhecimento aprofundado em Javascript (es6+);
Conhecimento aprofundado em React e seu ecossistema;
Conhecimento em testes automatizados (Unitários, Integração e e2e);
Conhecimento geral em Arquitetura de Software;
Conhecimento em Typescript;
Técnicas de otimização do tempo de carregamentos das páginas, performance e conversão;
Experiência com GraphQL, Design System, micro front-ends, NextJS;
Observabilidade: New Relic, Data Dog ou semelhante;
Conhecimento geral de Cloud Computing (AWS, GCP ou outros);
Conhecimento em CI/CD (Jenkins, Github Actions ou semelhante);
Versionamento de código com Git;
Técnicas de otimização de segurança em aplicações front-end;
Integração via APIs Rest;
Familiaridade com metodologias de desenvolvimento ágil, como Scrum ou Kanban;
Capacidade de traduzir requisitos visuais em código de alta qualidade e atenção aos detalhes estéticos;
Experiência em otimização de desempenho e conhecimento de técnicas para melhorar a tempo de carregamento, eficiência do front-end e a taxa de conversão;
Capacidade de trabalhar em equipe e colaborar com outros desenvolvedores, designers e stakeholders.

**Desejáveis:**
Node.js;
Conhecimentos avançado em SEO e acessibilidade;
Serverless: Lambda Function;
Cultura devops e ferramentas: Sonar, Fortify, Docker, Kubernetes;
Documentação de projetos: Jira, Miro, Figma.

**Diferenciais:**
- Experiência com projetos ecommerce e/ou Marketplace

## Benefícios
E ainda tem mais, olha só os nossos benefícios: 
Jornada de Trabalho com carga horária flexível e sustentável;
Para quem gosta de cozinhar a própria comida? Oferecemos Vale Alimentação, com um bônus no Natal;
Prefere pedir a comida em casa mesmo? Temos Vale Refeição;
Tem aquele Pet super fofo e quer ajuda? Temos a opção do Auxílio Pet;
Tá, mas e a sua saúde? Oferecemos Plano de Saúde (extensível aos dependentes legais), Plano Odontológico, Seguro de Vida e Previdência;
Sabe a vida fitness? Deixa com o Gympass;
E as crianças pequenas? Você pode optar pelo Auxílio Babá ou Auxílio Creche. Crianças de 04 meses a 02 anos, possuem Nutrição Infantil Complementar;
Acreditamos que todos possuem o direito de uma Licença Parental Universal igualitária de 120 dias para mulheres e homens (cis e trans);
PLR: Bônus anual conforme metas.
 Além do Desconto de até 40% em nossos produtos. Agora sim viu vantagem, né?

## Contratação

CLT

## Como se candidatar

Se inscreva na publicação: https://lnkd.in/eBY357Ba 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Especialista

**Comment by matheusmcz** [comment]
Enviado!

**Comment by MathMendesReis** [comment]
enviado

**Comment by mrsants** [comment]
Pela gupy não adianta, pior site de recrutamento

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
