### ISSUE TITLE
[Berlin - Germany] Senior Frontend Developer - E-Commerce - Eurobase

### ISSUE THREAD

**Issue by letanure** [frontendbr/vagas#781]
## Descrição da vaga

What you will do:

- [ ] You will be responsible for the development of the web front-ends of our customer area;
- [ ] You will work closely with **UX** and **UI** experts as well as with **backend** developers in a cross-functional team;
- [ ] Translate / code **responsive** designs into high quality templates;
- [ ] With your expertise, you can evaluate new technologies and give our UX an UI experts an assessment of the possible leeway;
- [ ] You understand common security risks in web front-ends and take them into account when developing solutions;
- [ ] You work to ensure the quality of the front-ends through **automation with test** frameworks;

## Local

Berlin - Germay

## Benefícios

- [x] Plano de saúde
- [x] Visa sponsorship
- Seguro de vida
- VR de R$ X/dia
- Auxílio creche

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Node
- 2 anos de experiência com mongodb e express

**Desejáveis:**
You have **at least 5 years** of professional experience in web development, especially in handling scalable high-performance front-end architectures

- You can master **JavaScript** (**ES6**), **HTML5**, **CSS3** and **SASS**;
- You already have relevant experience working with template technologies (such as **Thymeleaf**);
- You have a good knowledge of client-side frameworks such as Angular2 +, React or Vue.js;
- You feel confident in using web front-end build tools;
- You know how to write **JavaScript unit test**;
- You have already gained initial experience in **A/B** and/or **layout** testing;
- Ideally, **Typescript** and/ or *+Java** are not foreign languages to you;
## Como se candidatar

Send your CV in **english** to [jonathan.blaber+luiz_tanure@eurobase.com](mailto:jonathan.blaber+luiz_tanure@eurobase.com) 

## Labels

- Europa
- Alemanha
- Berlin
- Sênior

**Comment by DawTaylor** [comment]
Hi @letanure there's an error with the provided email address.

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
