### ISSUE TITLE
[Remoto] FullStack Developer na ITeam (com inglês)

### ISSUE THREAD

**Issue by ITeam-oportunidades** [frontendbr/vagas#7811]
> Vaga Remota
> Necessário residir na região de São Paulo

## ITeam

Há mais de 15 anos presente no mercado, a ITeam oferece o comprometimento com o cliente.
Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 
Com uma equipe multidisciplinar, a ITeam proporciona uma área de Serviços Gerenciáveis como Projetos SAP, Fábrica de Software, Fábrica de Soluções e Sustentação. Neste modelo proporcionamos Sustentação, Melhorias e Desenvolvimentos de aplicação de forma integrada.

## Local

Remoto, com possibilidade de atuar eventualmente presencial caso o cliente solicite em São Paulo/SP - Chácara Santo Antônio. 

## Requisitos

Experiência em desenvolvimentos Javascript Node.js / Express.js (backEnd), React.js (FrontEnd).
React Native (aplicações mobile);
Docker, Cloud Services (AWS / Azure / GCP);
Bancos de Dados (PostgresSQL, MySQL, SQLlite);
Continuous Learning (facilidade em aprender novas tecnologias).

## Necessário

Inglês avançado para conversação

## Contratação

5 meses - com possibilidade de ser efetivado posteriormente como CLT.

## Como se candidatar

Por favor, envie um e-mail para viviane.pereira@iteam.inf.br com seu CV anexado e pretensão de taxa/hora - enviar no assunto: FullStack Node com inglês

## Labels

React.js
Node.js
Express.js
Docker
Cloud

## Regime
PJ ou a combinar

## Nível
Sênior

**Comment by ITeam-oportunidades** [comment]
Vaga ativa - Enviar currículo em inglês e português.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
