### ISSUE TITLE
[remoto] Fullstack Developer na teceo

### ISSUE THREAD

**Issue by andersoneureka22** [frontendbr/vagas#7812]
## Nossa empresa
A teceo é um B2B do ramo de moda, focada em conectar marcas e lojistas de alto nível.
## Descrição da vaga
Estamos em busca de uma pessoa desenvolvedora fullstack com mais de 4 anos de experiência e com conhecimento amplo em react e node.

🤔 Como vai ser seu dia-a-dia na teceo?
- Projetar e/ou desenvolver soluções escaláveis de alta disponibilidade e qualidade;
- Desenvolver testes automatizados para as principais features implementadas;
- Participar das cerimônias de desenvolvimento de um projeto ágil;
- Participar de discussões a respeito das tecnologias adotadas no projeto com os demais membros;
- Participar de um ambiente aberto a novas ideias em relação ao produto e caminhos estratégicos;
- Atuar ativamente na evolução técnica do time, trazendo novas tecnologias e pontos de evolução para os membros;
- Auxiliar a equipe de suporte em eventuais dúvidas sobre o sistema.
## Local
Remoto
## Requisitos
**Obrigatórios:**
- Sólida experiência com projetos com regras e requisitos complexos;
- Sólida experiência demonstrável de atuação em uma solução de médio/grande porte;
- Sólida experiência em nodejs, preferencialmente utilizando o framework NestJS;
- Sólida experiência com elaboração de arquiteturas de sistema (modelagem de banco, micro-serviços, filas, etc);
- Sólida experiência com banco de dados relacionais;
- Sólida experiência com arquitetura REST;
- Sólida experiência com projetos de integrações entre diferentes sistemas;
- Sólida experiência e aplicação dos conceitos do SOLID e Clean Code;
- Experiência com desenvolvimento web em ReactJS;
- Experiência em liderar, formal ou informalmente, iniciativas de desenvolvimento;
- Experiência com CI/CD;
- Experiência com configuração de Docker;
- Experiência com testes unitários, funcionais e de integração;
- Boa comunicação verbal e escrita;
- Comprometimento;
- Capacidade de transmitir seus conhecimentos aos demais membros do time e alavancar as entregas dos demais.

**Desejáveis:**
- Experiência com AWS;
- Experiência com kubernetes.

**Diferenciais:**
- Ter atuado ou ter conhecimento sobre o mercado de moda;
- Ter atuado como líder ou líder técnico.

## Benefícios
- Formato 100% home-office;
- Horário flexível;
- 21 dias úteis de descanso remunerados.

**Diferenciais:**
- Time multidisciplinar;
- Bônus anual;
- Partnership;
- Bootcamp-teceo ~ imersão presencial anual com o time;
- Hands-on-week ~ semana em campo para ver o produto em ação;
- Fio-da-meada ~ rumos & números do negócio em uma reunião trimestral;
- Eventos diversos ~ happy hours, learning days, torneios de jogos etc.
## Contratação

PJ

## Como se candidatar

Por favor envie um email para rh@eurekalabs.com.br com seu CV e/ou linkedin anexado - enviar no assunto: Vaga dev senior fullstack

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias úteis após cada processo.
E-mail para contato em caso de não haver resposta: ligia.nogueira@eurekalabs.com.br

#### Alocação
- Remoto
#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by JefersonLucas** [comment]
Enviado! 🚀
