### ISSUE TITLE
[Remoto] Front-end Developer Na Empreender

### ISSUE THREAD

**Issue by serenarhempreender** [frontendbr/vagas#7814]
> Vaga Remota durante a pandemia

## Nossa empresa

 Somos uma empresa de tecnologia e educação, criamos softwares inovadores para facilitar a vida de empreendedores no universo do Dropshipping. 

Estamos em busca de desenvolvedores para completar nosso time de Dev's, venha trabalhar conosco!

## Descrição da vaga

-Criar aplicativos em versão Web.
-Prestar suporte e manutenção aos nossos produtos.
-Participar de Interações com todo time e plataformas parceiras.

## Local

Vaga 100% Remoto (Home office).

## Requisitos

**Obrigatórios:**

• Experiência com HTML, CSS e Javascript;
• Agilidade com SASS/Bootstrap;
• Experiência com Apis Rest;
• Experiência com ReactJS

**Desejáveis:**
- 2 anos de experiência.

**Diferenciais:**
- projetos de portfólio para nossa avaliação. 

## Benefícios

-Bônus de natal (13°);
-Bônus de aniversário;
-Bônus de três meses;
-Aulas de Idiomas (Inglês e espanhol);
-Participação programa de férias;
-Participação de Lucros (PL);

**Diferenciais:**
-Horário flexível.
- ...

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um e-mail para serena@empreender.com.br com seu CV anexado, LinkedIn e portfólio- enviar no assunto: Vaga Front End.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.

#### Alocação
- Remoto 100%

#### Regime

- PJ
-Contrato

#### Nível

- Pleno
- Especialista

**Comment by jhefflg** [comment]
Up!

**Comment by Samuel-Amaro** [comment]
Enviado!

**Comment by joao160197** [comment]
Currículo enviado

**Comment by natamartins** [comment]
Enviado!!!

**Comment by Icegreeen** [comment]
Up!

**Comment by alessandrobferreira** [comment]
CV enviado

**Comment by joaovictorfd1** [comment]
Enviado!!

**Comment by pedrobadm7** [comment]
Currículo enviado!

**Comment by renatoknot** [comment]
Enviado

**Comment by JefersonLucas** [comment]
Enviado! 🚀

**Comment by cjfswd** [comment]
Enviado.

**Comment by leandromds** [comment]
Cv Enviado.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
