### ISSUE TITLE
[São Paulo] Senior Front-end Developer na Doris

### ISSUE THREAD

**Issue by rafaelcavalcante** [frontendbr/vagas#7816]
## Sobre a Doris

E-commerce no mundo já é uma realidade, assim como experimentar roupas. E-commerce veio facilitar muitos aspectos do processo de compra, inclusive, deixar de ir às lojas. A loja não tem a tecnologia do E-commerce. E-commerce não tem a experiência da loja. Novos players buscam soluções apenas para aumentar a facilidade do E-commerce. Doris propõe um novo patamar para o E-commerce. Facilidade do E-commerce com a experiência da loja. Doris tornou realidade aquilo que muita gente já sonhou: Experimentar roupas sem precisar ir à loja ou ficar colocando e tirando peças.

Agora, a experiência de compra é muito mais humana. Criando uma nova categoria. 

‍Adeus, e-commerce.
Chegou o experience-commerce.

## Descrição da vaga

Estamos em busca de uma pessoa desenvolvedora sênior, com excelente comunicação, organização e bom relacionamento interpessoal. Buscamos alguém que consiga trabalhar em conjunto com todo o time de tecnologia e design revisando o trabalho de colegas, e participando de decisões importantes de produto e tecnologia, garantindo a qualidade dos nossos produtos.

## O que procuramos?

- Possuam experiência com desenvolvimento e de novas features e manutenção de aplicações em React em produção.
- Tenham experiência com a aplicação a manutenção de design system.
- Entendam o impacto e a importância de implementar testes, sejam unitários, de integração ou end-to-end.
- Entendam a importância de participar não só da etapa de front-end, mas também na parte de design e back-end.
- Escrevam código limpo, legível e de fácil manutenção;
- Enriqueçam as discussões sobre soluções, tanto para melhorias quando na concepção de novas funcionalidades ou projetos.
- Gostem de compartilhar conhecimento e dêem valor a autonomia de cada pessoa da equipe.

## Requisitos

- React.
- Typescript.
- Testes Unitários.
- Metodologias ágeis: Scrum e Kanban.
- ContextAPI.
- React Hooks.
- Styled Components – e CSS-in-JS no geral.
- Testes end-to-end.
- SOLID principles.
- Conhecimento em padrões de projeto criacionais, estruturais e comportamentais.

## Desejáveis

- React Native
- GraphQL
- NEXTJS.
- Test-driven development.
- Storybook.
- Proficiência em inglês.
- Clean Code.
- Ter colocado um projeto em produção.

## Diferenciais

- Outras libraries e frameworks, como Vue e Svelte.
- Micro frontends.
- Conhecimento em entrega e integração contínua.
- AWS: S3, CloudFront, Route53, Amplify

## O que você vai encontrar aqui

- Compartilhamos conhecimento o tempo todo. Praticamos pair-programming com frequência e temos discussões técnicas sobre como, o quê e por quê de cada decisão que tomamos.
- Preocupação com sua vida fora do trabalho. Entendemos a importância de estar fisicamente e mentalmente bem. Trabalhamos somente durante o expediente.
- Crescemos e cresceremos juntos. Além de mentoria (dependendo do seu nível) uma pessoa gestora vai te ajudar a crescer profissionalmente.
- Cultura que preza por entregar software de qualidade e não por entregas rápidas.
- Temos um plano para cada membro da equipe de acordo com suas aspirações profissionais, do estágio ao C-Level.

## Quais são as etapas do nosso processo?

- A primeira etapa do processo é um teste técnico. Toda sua interação (e não interação) com o teste será parte do processo de avaliação;
- Uma entrevista técnica com o Engineering Manager ou Tech Lead;
- Uma entrevista técnica com o Tech Lead ou Engineering Manager;
- Uma entrevista com o CTO;

E um _feedback_ garantido sobre seu teste técnico, independente do resultado.

## Como se candidatar

Se inscreva em nossa [vaga no Linkedin](https://www.linkedin.com/jobs/view/3659211135/).

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo. Caso não tenha resposta após esse período, entre em contato com o [recrutador responsável](https://www.linkedin.com/in/rafaelcavalcante) :)

## Labels

**Alocação:** Remoto
**Regime:** PJ
**Nível:** Sênior / Especialista

**Comment by rafaelcavalcante** [comment]
@felipefialho pegou um label de estágio aqui, rs.

**Comment by jhefflg** [comment]
Up!

**Comment by rafaelcavalcante** [comment]
> Up!

Obrigado, @jhefflg

**Comment by pedrolima4** [comment]
Olá @rafaelcavalcante. Não tenho Linkedin, teria algum e-mail no qual eu pudesse me candidatar? Obrigado!

**Comment by brunooomelo** [comment]
Enviado!!

**Comment by rodrigozegobia** [comment]
Estágio não tem então?  Heh

**Comment by eric218110** [comment]
Parabéns pela ótima descrição ❤️❤️

**Comment by rafaelcavalcante** [comment]
> Parabéns pela ótima descrição ❤️❤️

Fala, @eric218110! Muito obrigado!
