### ISSUE TITLE
Remover label

### ISSUE THREAD

**Issue by guibranco** [frontendbr/vagas#7817]
Remover a label [🦠 Remoto durante pandemia](https://github.com/frontendbr/vagas/labels/%F0%9F%A6%A0%20Remoto%20durante%20pandemia), visto que não estamos mais na pandemia e essa label não faz mais sentido e está sendo atribuida de forma errada para algumas vagas...

**Comment by guibranco** [comment]
@felipefialho

**Comment by felipefialho** [comment]
Bem lembrado, removido!
