### ISSUE TITLE
[Remoto] [Engenheiro(a) de Software Front End Node.js com Angular com inglês avançado para conversação obrigatório]  - HunterHunter

### ISSUE THREAD

**Issue by ErickaMB** [frontendbr/vagas#7821]
[Engenheiro(a) de Software Front End Node.js com Angular com inglês avançado para conversação obrigatório] - Remoto. R$ 11 mil a 13 mil.

Requisitos:

O que é preciso para que você faça parte do processo:
Formação em Análise e Desenvolvimento de Sistemas, Ciências da Computação ou afins.
Forte habilidade para se comunicar em Inglês e participar ativamente de um squad global.

Sólida experiência com:
Typescript e Node.js 3+ anos de experiência.
Angular 3+ anos de experiência.
Banco de Dados NoSQL (DynamoDB, Elasticsearch) e RDBMS (Mysql, Postgress, MS SQL Server) 
Queue (Kafka, ActiveMQ)
Infraestrutura (Kubernetes, Docker Container, Helm chat, Ansible, AWS)
CI/CD (Github actions, Jenkins, Octopus).

Benefícios:

PARCERIA COM INSTITUIÇÕES DE ENSINO PARA DESCONTO EM CURSOS PORTAIS DE DESCONTO PLATAFORMA DE TREINAMENTOS VOLTADOS À SOFT SKILLS BENEFÍCIO FLEXÍVEL ASSISTÊNCIA ODONTOLÓGICA PROGRAMA DE ASSISTÊNCIA AO COLABORADOR (PAE) ASSISTÊNCIA MÉDICA TOTAL PASS VALE ALIMENTAÇÃO / REFEIÇÃO AUXÍLIO CRECHE SEGURO DE VIDA PARTICIPAÇÃO NOS LUCROS DAY OFF NO MÊS DO ANIVERSÁRIO AUXÍLIO HOME OFFICE SHORT FRIDAY NO VERÃO.

Sobre:
Somos a plataforma em nuvem para integração de dados entre sistemas e APIs (iPaaS) líder da América Latina. Ajudamos empresas de todos os tamanhos e de todos os segmentos a tornarem-se digitais de verdade com uma operação 100% conectada. A partir de uma única interface, nossa plataforma automatiza fluxos de integração de dados entre sistemas, processos, departamentos e organizações, eliminando a necessidade de processos manuais.

Se tem interesse e com requisitos da oportunidade entre em contato pelo Linkedin informando qual é a oportunidade. [https://www.linkedin.com/in/erickamarquesb/]

**Comment by Marilzon** [comment]
nice!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
