### ISSUE TITLE
[REMOTO] Front-end Developer na Hepta Tecnologia e Informática

### ISSUE THREAD

**Issue by GitMateusBruno** [frontendbr/vagas#7823]
## Nossa empresa

A empresa contratante é a Hepta tecnologia, sediada em Brasília com 31 anos de atuação no mercado. Temos contratos com empresas privadas e órgãos públicos, em virtude disso aqui é um espaço amplo de crescimento e desenvolvimento profissional. O time é bastante colaborativo, na verdade colaboração faz parte do nosso valor 🚀

## Descrição da vaga

React,  Next.js, Node.js, TDD,  JavaScript ou TypeScript 

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Comprovação de 05 anos de experiência como Dev. (Pode ser via CLT ou Declaração de empresa)
- Formação superior na área de tecnologia ou pós graduação
- Jornada de Trabalho no horário comercial
- Outro ponto é que o cliente solicita que o profissional tenha uma das seguintes certificações:

P/ Atuar como Dev.
Professional Scrum Developer (PSD) OU Certified Scrum Developer (CSD) 

Alguns profissionais atuaram no time como Scrum Master: Se este for o seu interesse, necessário também uma das:
a) Scrum.Org: Professional Scrum Master – PSM:
PSM I; PSM II ou PSM III;
b) Scrum Alliance: Certified Scrum Master – CSM;
c) Scrum Study: Scrum Master Certified – SMC
d) EXIN: Agile Scrum Master - ASM

Caso você ñ possua nenhuma certificação, não há problemas nós damos um prazo de 30 dias, após efetivação para nos apresentar. Sendo tudo subsidiado por um termo de compromisso e assinado. Atenção, a empresa não custeia, apenas dar o prazo.

## Benefícios

- Plano de saúde ambulatorial parcialmente custeado pela empresa
- VA ou VR de R$ 22,59/dia
- Auxílio Home Office

## Contratação

CLT 

## Como se candidatar

Por favor envie um email para mateus.sousa@hepta.com.br com seu CV anexado - enviar no assunto: Vaga React Sr. | Ou 71 993127798

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até cinco dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by JIFerreira01** [comment]
Qual o valor da vaga?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by GitMateusBruno** [comment]
Olá, time! Essa vaga estava congelada, mas retomamos os trabalhos; Estamos com algumas oportunidade a nível Pleno Sênior.  Caso desejem participar do processo me envia uma mensagem: 71993127798

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
