### ISSUE TITLE
[Remoto e Internacional] React.js Front-End Web Developer) na turing.com

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#7825]
## Job description
A well-established IT firm that specializes in building high-quality, feature-rich native mobile and web applications, is looking for a React.js Front-End Web Developer. As a developer, you will be responsible for developing user interface components and implementing them using React.js workflows (such as Flux or Redux). The selected candidate will coordinate with the rest of the team working on different layers of the infrastructure and will ensure the scalability of the applications. The company is leading the industry by providing high-quality software solutions. This is an exciting opportunity as the selected candidate will join a team of experts in developing unique innovative solutions.

## Job Responsibilities:

- Develop and implement UI components
- Design and build intuitive front-end applications
- Work with managers, engineers and designers to deliver desired outcomes
- Interact with clients’ technical leadership, understand the requirements & execute them
- Utilize a wide range of systems & technologies to solve potential problems

## Job Requirements:

- Bachelor’s/Master’s degree in Engineering, Computer Science (or equivalent experience)
- 3+ years of front-end web development experience
- Proficiency in React Native, React.js, and Redux
- Experience in app development
- Working knowledge of CSS and Bootstrap
- Experience in Flexbox would be an added advantage
- Fluency in English communication

## Como se candidatar
Acesse o site da [Turing](https://bit.ly/3qJaLwW) para conferir o descritivo completo e aplicar para a vaga.

Obs: esta vaga está sendo publicada pela [Remotar](https://remotar.com.br/?utm_source=github) em nome da Turing. A Remotar é uma plataforma de vagas remotas que ajuda seus clientes com a divulgação das posições abertas. No entanto, não somos responsáveis pelo processo seletivo das mesmas.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
