### ISSUE TITLE
[Internacional e Remoto] Senior Full-stack Developer na Lemon.io ($5k - $9k/month)

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#7827]
## About
Are you a talented developer looking for a remote job that lets you showcase your skills while enjoying better compensation and career growth? Look no further than Lemon.io, the marketplace that connects you with hand-picked startups in the US and Europe.

## What do we offer:

- We respect your time: here is no micromanagement or time trackers.
- You can earn with us $5k - $9k monthly - the rate depends on your skills and experience. We've already paid out over $10M to our engineers.
- You will enjoy your work - it’s possible to communicate async and choose a schedule that works best for you.
- You will communicate directly with the clients. Most of them have technical backgrounds. Sounds good, yeah?
- We will support you from the time when the application will be started during all our cooperation.
- No more hunting for clients or negotiating rates - let us handle the business side of things so you can focus on what you do best.
- We'll manually find you the best project according to your skills and preferences.
- You will work in a fast-paced startup environment that will keep you motivated and engaged.
- We will connect you with the best developers in the world through our community. Also every month we have two online events - you can join them as a Member or a Speaker.

## Requirements:

- 4+ years of software development experience
- 3+ years of experience with React.js
- 3+ years of experience with Python OR with Ruby
- Experience with AWS is a must
- Experience with  Node, Next, React Native, Docker, Kubernetes would be a plus but not mandatory
- Good command of English, both written and spoken, as you’ll be communicating with clients directly
- Strong organizational skills — ability to work full-time remotely with no supervision
- Responsibility — we want to trust you
- Soft skills — we value clear and effective communication, at the same time don't force you becoming a public speaker

## Important
- Please note that due to the overwhelming number of applications, only suitable candidates will be contacted for an interview.
- We strongly ask you to send your CVs in ENGLISH. Application in English will be considered first. Good luck to everyone!
- At the moment, we don’t have a legal basis to accept applicants from Monaco, Belarus, Russia, Serbia, Denmark, Norway, Luxemburg, Iceland, Liechtenstein, San Marino, Belize, Cuba, Nicaragua, Saint Lucia, so we don’t work with applicants from these countries.

We also collaborate with other companies through staff augmentation. More details are[ here](https://lemon.io/partnership-with-lemonio/).

Ready to take your career to the next level? Apply now and join the Lemon.io community!

P.S. We work with developers from LATAM, Canada, UK, Europe BUT we have some exceptions.

 **If your experience matches with our requirements be ready for the next steps:**

- VideoAsk (about 10 minutes)
- Completing your me.lemon profile
- 30 minutes Screening call with our Recruiters
- Technical Interview with our Developers
- Feedback
- Magic Box (we are looking for best project for you)

## Como se candidatar

Acesse o site da [Lemon](https://bit.ly/3YGJgkm) para aplicar para a vaga.

Obs: esta vaga está sendo publicada pela [Remotar](https://remotar.com.br/?utm_source=github) em nome da Turing. A Remotar é uma plataforma de vagas remotas que ajuda seus clientes com a divulgação das posições abertas. No entanto, não somos responsáveis pelo processo seletivo das mesmas.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
