### ISSUE TITLE
[Remoto] [PJ] Full Stack Sênior (Elixir/Scala/React.JS) JUST TRAVEL 

### ISSUE THREAD

**Issue by Lusaniabarbosa** [frontendbr/vagas#7828]
A JUST TRAVEL é uma TRAVEL TECH referência na distribuição de produtos turísticos de alta qualidade e excelência em atendimento ao cliente em qualquer lugar do mundo. Somos uma combinação de experiência da indústria do turismo, tecnologia e marketing digital. Estamos crescendo de forma exponencial e investindo na expansão do nosso time. Se você é uma pessoa proativa, organizada, flexível, gosta de trabalhar em equipe e sabe lidar bem com pressão, esta vaga pode ser para você!

**É importante destacar que o profissional realizará as seguintes atividades:**

- Desenvolver e manter serviços backend robustos e escaláveis utilizando Elixir e ReactJS
- Criar testes que garantam qualidade e confiabilidade ao desenvolvimento
- Colaborar com designers para traduzir protótipos em experiências ricas de usuário
- Construir soluções utilizando bancos de dados relacionais (SQL) e não relacionais (No-SQL)
- Colaborar na construção da arquitetura das soluções
- Implementar melhores práticas de desenvolvimento web com o objetivo de garantir a melhor performance e experiência para o usuário
- Ser mentor de colegas de menor senioridade
- Ajudar o time de produto a digitalizar o turismo no mundo

**Segue algumas informações importantes:**

- Modelo de trabalho: Remoto ou Presencial em Salvador
- Modelo de contratação: PJ

**Requisitos/Qualificações:**

- Experiência sólida em desenvolvimento back-end utilizando programação funcional. Preferencialmente Elixir mas também Scala, Kotlin, Clojure, Erlang ou NodeJS
- Conhecimento em metodologias ágeis
- Desenvolvimento e implementação de APIs REST e GraphQL
- Habilidade de aprender rapidamente, resolver diferentes tipos de problemas e se adaptar a mudanças constantes
- Conhecimento de boas práticas de desenvolvimento de software
- Conhecimento com serviços AWS como EC2, Amplify, S3, Lambda
- Habilidades sólidas em HTML, CSS e JavaScript
- Familiaridade com o ciclo de vida de componentes React e o gerenciamento de estado
- Experiência com Typescript

**Será um bônus se você se:**

- Possuir experiência com desenvolvimento de software na área de turismo
- Possuir experiência liderando pequenas equipes
- Possuir experiência na construção de produtos
- Você residir em Salvador-BA

**Link para inscrições: https://x.gd/IResK**

Vem ser Justtravel! 🌎

**Comment by jhserodio** [comment]
@Lusaniabarbosa, o Link do Linkedin encerrou já as proposições a vaga " No longer accepting applications "

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
