### ISSUE TITLE
[São Paulo] Front-End Developer na DÁLE ideiaZ

### ISSUE THREAD

**Issue by raffaeldantass** [frontendbr/vagas#783]
## Descrição da vaga

- Desenvolvimento de Landing Pages;
- Desenvolvimento de sites em Wordpress;
- Desenvolvimento de emails marketing; 
- Administração de e-commerce (atualização de plugins, inserção de novas páginas, atualização de produtos, manutenção etc);
- Desenvolvimento de aplicações para clientes ou para a própria DÁLE em projetos paralelos.

## Local

Presencial na Vila Madalena em São Paulo

## Benefícios
- Salário compatível;
- Vale Transporte;
- Refeição no local;

#### Diferenciais

- Folga no dia do aniversário; 
- Ótimo ambiente de trabalho; 
- Ambiente aberto para sugestões e conversas.

## Requisitos

- Conhecimentos intermediarios em HTML, CSS e JS;
- Conhecimentos minimos em emails marketing;
- Conhecimentos básicos em Wordpress.

**Obrigatórios:**
- 1 ano de experiência trabalhando diretamente com essas tecnologias. 

**Desejáveis:**
- Saber utilizar o framework MJML

## Contratação

CLT

## Nossa empresa

Na DÁLE trabalhamos com diversos clientes dos mais diferentes tamanhos, então as atividades podem variar, desde coisas simples como administração de um site em Wordpress até o desenvolvimento de uma aplicação completa. Aqui o lema é trabalhar se divertindo, então sinta-se a vontade pra sugerir melhorias e propor coisas novas, somos muito abertos a novas ideias, até porque essa é a nossa cara, né? 

## Como se candidatar

Por favor envie um email para marcelo@dale.ag com seu CV anexado, linkedin e Github - enviar no assunto: Vaga Desenvolvedor Frond-End

## Labels

- Alocado
- CLT
- Júnior

**Comment by X-X-Xavito** [comment]
enviado.

**Comment by renanlara** [comment]
Interessante essa vaga, mas é só para Júnior mesmo?

**Comment by raffaeldantass** [comment]
Fala Renan, tudo certo? 

Sim, nesse momento a gente tá em busca de um perfil mais Júnior mesmo, porém se tiver interesse manda suas informações que a gente dá uma olhada! 

Valeu! :)

**Comment by renanlara** [comment]
@raffaeldantass, enviei o e-mail. Abraços!

**Comment by laugustofrontend** [comment]
@raffaeldantass, enviei o email. Abraços!

**Comment by raffaeldantass** [comment]
Ainda estamos analisando os currículos, mas a vaga ainda continua aberta :)

**Comment by danieladuarteng** [comment]
enviei
