### ISSUE TITLE
FREELA REMOTO: Front-end Developer na GOING2

### ISSUE THREAD

**Issue by MariaJuliaRicostiG2** [frontendbr/vagas#7831]
## Nossa empresa

A Going2 é uma startup que nasceu em 2012, com o propósito de levar tecnologia de ponta para todo o Brasil, focada em criar produtos que tenham como premissa, facilitar a vida das pessoas e empresas, através do desenvolvimento de Aplicativos, Sistemas e dos princípios de IOT (internet das coisas). Hoje, além de atender clientes nacionais também oferecemos nossos serviços para clientes internacionais, como por exemplo no Canada, Suíça e Estados Unidos.

## Descrição da vaga

Profissional que tenha atuado com Feed de Vídeo, usando protocolo HLS (HTTP live streaming), com experiência na otimização (predictive, buffer, cache) de transmissão e exibição em App React Native.

## Local

REMOTO

## Contratação

Freelancer (Previsão de 20 a 30 hrs, pode se estender se necessário)

## Como se candidatar

Por favor envie um email para mariajulia.ricosti@going2.com.br com seu CV anexado - enviar no assunto: Freela front-end. Com a sua pretensão salarial

#### Alocação
- Remoto

#### Regime
- Freela

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by MaykNunes** [comment]
Enviado

**Comment by joao160197** [comment]
Enviado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
