### ISSUE TITLE
[REMOTA] Front-end Developer na HEPTA TECNOLOGIA E INFORMÁTICA

### ISSUE THREAD

**Issue by GitMateusBruno** [frontendbr/vagas#7832]
## Nossa empresa

A empresa contratante é a Hepta tecnologia, sediada em Brasília com 31 anos de atuação no mercado. Temos contratos com empresas privadas e órgãos públicos, em virtude disso aqui é um espaço amplo de crescimento e desenvolvimento profissional. O time é bastante colaborativo, na verdade colaboração faz parte do nosso valor 🚀

## Descrição da vaga

Projeto em React,  Next.js, Node.js, TDD,  JavaScript ou TypeScript

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Comprovação de 05 anos de experiência como Dev.
- Formação superior na área de tecnologia ou pós graduação
- Certificação em: 
Professional Scrum Developer (PSD) ou Certified Scrum Developer (CSD)

Caso você não possua nenhuma certificação, não há problemas nós damos um prazo de 30 dias, após efetivação para nos apresentar. Sendo tudo respaldado por um termo de compromisso e assinado. Atenção, a empresa não custeia, apenas dar o prazo.

## Benefícios

- Plano de saúde ambulatorial parcialmente custeado pela empresa, sem coparticipação.
- VR ou VR
- Auxílio Home Office

## Contratação

CLT

## Como se candidatar

Por favor envie um email para mateus.sousa@hepta.com.br com seu CV anexado - enviar no assunto: Vaga REACT PL OU https://www.hepta.com.br/carreiras/oportunidades/1872

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até cinco dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by paulo70** [comment]
@GitMateusBruno Esse repositório é referente a Frontend Developers. Para Scrum Master ainda não temos a opção.

**Comment by lucasalmeida92** [comment]
Tenho interesse mas o formulário está com problema. Posso enviar meu currículo por algum email?

**Comment by GitMateusBruno** [comment]
Olá, Lucas, tudo bem?

Infelizmente esse processo encontra-se congelado. No entanto, se desejar
manter seu currículo em nosso banco, pode encaminhar para esse e-mail:
***@***.***; em assunto: Vaga React Pleno.

Atenciosamente,

Em dom., 10 de set. de 2023 às 18:08, Lucas Almeida Siqueira <
***@***.***> escreveu:

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
