### ISSUE TITLE
[Remoto e Internacional] Vue.js Engineer na turing.com

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#7836]
## Job description
A fast-emerging company operating a payment-enabled marketplace to facilitate easy donation transactions is looking to hire a Vue.js Engineer. The engineer will be responsible for translating designs into scalable, responsive front-end applications. The platform enables a hassle-free donation from clients to any non-profit organization or religious institution. It has raised over $300K in funding so far. This is an excellent position for those who want to impact and contribute to building lasting financial solutions.

## Job Responsibilities:

- Dive into complex problems and successfully deliver results on schedule
- Establish best-in-class software engineer best practices
- Work on implementing different front-end components with the Vue.js framework
- Maintain high standards for code quality and other application deliverables

## Job Requirements:

- Bachelor’s/Master’s degree in Computer Science (or equivalent experience)
- Proficiency with Vue.js and Vuetify
- Experience with one or more major web frameworks
- Experience with PHP / Laravel is nice to have
- Self-motivated with sound problem-solving skills

## Como se candidatar

Acesse o site da [Turing](https://bit.ly/45FvKQ2) para conferir o descritivo completo e aplicar para a vaga.

Obs: esta vaga está sendo publicada pela [Remotar](https://remotar.com.br/?utm_source=github) em nome da Turing. A Remotar é uma plataforma de vagas remotas que ajuda seus clientes com a divulgação das posições abertas. No entanto, não somos responsáveis pelo processo seletivo das mesmas.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
