### ISSUE TITLE
[REMOTO] Front-end Developer (MOBILE) Sênior na Going2

### ISSUE THREAD

**Issue by MariaJuliaRicostiG2** [frontendbr/vagas#7837]
## Nossa empresa

A Going2 é uma startup que nasceu em 2012, com o propósito de levar tecnologia de ponta para todo o Brasil, focada em criar produtos que tenham como premissa, facilitar a vida das pessoas e empresas, através do desenvolvimento de Aplicativos, Sistemas e dos princípios de IOT (internet das coisas). Hoje, além de atender clientes nacionais também oferecemos nossos serviços para clientes internacionais, como por exemplo no Canada, Suíça e Estados Unidos.

## Descrição da vaga

**Atividades**

- Versionamento organizado no Git;
- Participar dos rituais do time (SCRUM);
- Alinhamento com pares;
- Cumprir entregas no prazo e com alta qualidade;
- Liderar e ajudar desenvolvedores do time;
- Participar ativamente de todo o ciclo de desenvolvimento de aplicações mobile, desde a concepção até a entrega final;
- Desenvolver soluções mobile focadas em boas práticas, otimização de performance e com testes automatizados robustos;
- Colaborar com a equipe para garantir a entrega de produtos de alta qualidade;
- Resolver bugs, implementar novas features e participar de revisões de código.

**Requisitos**

- Profundo conhecimento e experiência em desenvolvimento com TypeScript;
- Sólida experiência no desenvolvimento de aplicações usando React Native;
- Capacidade de escrever documentação técnica clara e concisa;
- Experiência em técnicas avançadas de refatoração, componentização e modularização;
- Familiaridade com design patterns e boas práticas de desenvolvimento mobile;
- Experiência em integração e monitoramento de aplicativos em produção;
- Proficiência em testes automatizados, ferramentas de profilling para aplicações Android e iOS, e técnicas de code review;
- Conhecimento das normas e práticas de publicação nas lojas AppStore e Google Play;
- Familiaridade com metodologias ágeis, refinamento e quebra de tarefas;
- Técnologias utilizadas: React Native, Redux, Styled Components, Firebase, Reanimated AppCenter, React Query, Socket.io, Jest, Testing Library e Detox;
- Diferencial: Desenvolvimento de bibliotecas nativas com bridge para o React Native;
- Diferencial: Experiência com aplicativos de redes sociais e/ou streaming de vídeo.

**Benefícios**

- Ajuda de custo exclusivo para convenio médico e odontológico;

- Convênio com plataforma de idiomas (Fluency Academy);
- Plataforma de treinamento Udemy Business;
- Day-Off de aniversário;
- 15 dias de descanso remunerado;
- Plano de carreira.

**Outras informações**

- Horário: 09h às 18h;
- Remoto;
- Contrato de prazo indeterminado;
- PJ.

## Contratação

PJ 

## Como se candidatar

Por favor cadastrar através do link: https://going2.vagas.solides.com.br/

#### Alocação

- Remoto

#### Regime

- PJ

#### Nível

- Sênior/Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
