### ISSUE TITLE
[Florianópolis-SC] Front-End Developer na SocialBase

### ISSUE THREAD

**Issue by Strapazzon** [frontendbr/vagas#784]
## Local

Escritório, Florianópolis-SC - Itacorubi

## Descrição da vaga
SocialBase é uma empresa jovem, com espírito cooperativo e nossa plataforma destina-se a mudar a forma como as empresas se comunicam, criando conexões positivas entre os colaboradores internos. Nosso produto contribui para construção de uma Cultura mais Colaborativa, armazenamos arquivos, mensagens e conversas entre colaboradores em uma única ferramenta. Nossa meta é proporcionar a melhor experiência em comunicação interna para as empresas!

## Principais Atividades

- Codificação de novas funcionalidades usando AngularJS, CSS, HTML5 e frameworks para Frontend;
- Participar do estabelecimento e manutenção de padrões de qualidade;
- Garantir que as novas funcionalidades de frontend sejam documentadas e testadas de acordo com os padrões estabelecidos pela liderança técnica;
- Compartilhar experiências, sugerir melhorias, e revisar os códigos de outros desenvolvedores;
- Produção de documentos de arquitetura em cooperação com a equipe de arquitetura, PMs (Product Managers), UX, UI, e equipe técnica;
- Análise e resolução de bugs;
- Interface com a equipe de infraestrutura para suporte no processo de implantação, na estimativa e redução de custos, e na manutenção da produção;
- Pesquisa e desenvolvimento de novas soluções em cooperação com a equipe de arquitetura, de infraestrutura, PMs (Product Managers), UX, UI, e equipe técnica;
- Acompanhar e mentorar a evolução técnica de desenvolvedores plenos.

# Requisitos
- Sólido conhecimento em **Angular 4 e Typescript**;
- Ter padrões de desenvolvimento e projetos (SOLID, Design Patterns, CleanCode, etc.);
- Conhecimento em HTML5, CSS3, Web standards;
- Dominar Javascript (JQuery não conta);
- Experiência em testes (Karma, Protractor);
- Interesse e facilidade em aprender novas tecnologias e linguagens de programação;
- Conhecimento em Cultura Ágil, Lean e de entrega contínua.

## Desejáveis
- Experiência como Full-Stack;
- Fluência com frameworks de css (SaSS, Less);
- Fluência em convenções e padrões de experiência de usuário (UX);
- Formação completa ou cursando (Ciência da computação, Sistemas de informação e áreas afins)
- Ter algum projeto ou contribuição no Github;

## O que oferecemos
- Oportunidade para experimentar novos desafios;
- Vale-refeição ou alimentação;
- Horário Flexível
- Plano de saúde sem coparticipação;
- Café pra manter níveis adequados de cafeína;
- Frutas, lanchinhos e laboral pra manter a mente sã;
- Happy Hour toda semana;
- Muito teamwork!

# [candidatar-se](https://socialbase.workable.com/j/A149875C9E)

**Comment by joaocarvalhowd** [comment]
@Strapazzon Possibilidade de remoto?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
