### ISSUE TITLE
[Remote Work] Front End Developer React JR/PL  na Verum Digital

### ISSUE THREAD

**Issue by NovareRH** [frontendbr/vagas#7840]
**[Remote Work] Front-End Developer React na Verum Digital**

﻿﻿‍**TAREFAS:**
- Desenvolver e dar manutenção no sistema atuando no front end;
- Criar testes de componentes e telas;
- Contribuir com a prototipação de telas;
- Colaborar com desenvolvedores back-end para melhorar a usabilidade do produto;
- Auxiliar na comunicação do front com o back-end PHP/Laravel;
- Manter a qualidade dos códigos através de testes;
- Utilizar ferramentas de versionamento (Git);
- Aplicar os padrões de clen code no desenvolvimento;
- Realizar a documentação do projeto;
- Participar de reuniões técnicas/operacionais.

﻿**RESPONSABILIDADES:**
- Desenvolver aplicação web responsiva para o setor da construção industrial com base em metodologias inovadoras de planejamento de projetos e medição de progresso das atividades executadas pelos stakeholders;
- Desenvolver o frontend do produto digital (Fluit).

**DESAFIOS:**
- Compreender a lógica do sistema, diante da sua complexidade, em prol de desenvolver o front-end das soluções para proporcionar ótima experiência aos usuários;
- Aprofundar-se na regra de negócio com base na metodologia Advanced Work Packaging (AWP)

Cargo: Desenvolvedor Front End React JR/PL | Remote Work
Tipo de Contrato: Prestador de serviço (PJ)
Área profissional: Informática/T.I.
Carga-horária: 8h
Jornada: Horário Comercial
Salário: De R$ 2.500,00 a 3.500,00
Benefícios: Férias remuneradas

***Requisitos***
 EXPERIÊNCIAS, CONHECIMENTOS E COMPETÊNCIAS:
- Experiência mínima de 1 ano com React (em cursos, projetos ou experiências prévias);
- Conhecimentos em CSS, HTML e Javascript;
- Experiência com Lógica de programação;
- Conhecimento em banco de dados (PostgreSQL);
- Noções de boas práticas de codificação, design patterns, código limpo e testes;
- Familiaridade com design de interfaces de usuário (prototipação);
- Conhecimento em webservice;
- Noções de back-end (Laravel/PHP)

**FORMAÇÃO:**
- Ensino Médio Completo;
- Ensino Superior e/ou cursos na área de desenvolvimento.

**DIFERENCIAL:**
- ﻿Conhecimento na regra de negócio (construção industrial ou civil);
- Conhecimento em Laravel e PHP;
- Domínio do desenvolvimento front-end (React)
- Interesse em estudo e desenvolvimento constante;
- Vontade de se desenvolver com o time da Verum;

**O QUE BUSCAMOS:**
- Foco em entregas;
- Autonomia para buscar conhecimento;
- Habilidades de comunicação e trabalho em equipe;
- Expertise com tecnologias e programação;
- Raciocínio Lógico;
- Senso de urgência e agilidade;
- Proatividade e Persistência;
- Visão Sistêmica;
- Foco em resultados;
- Autogestão e Organização;

***A VERUM DIGITAL trabalha com as seguintes tecnologias:***
(Ter vivência será um diferencial!)
- Javascript/React e Typescript;
- Laravel/PHP;
- ECS/ECR;
- NGINX;
- Metodologia Ágil ( ferramenta Jira);
- Banco de Dados Postegre SQL;
- Amazon AWS.

**Sobre a empresa**
A Verum Digital nasceu para facilitar a vida dos projetos industriais, com soluções criativas e eficientes.
O Fluit, plataforma desenvolvida para promover a transformação digital, concentra todas as informações em um só lugar, oferecendo uma visão integrada e estratégica para execução dos projetos. Oferece uma interface amigável e extremamente eficiente para implementar a metodologia AWP, com diversas funcionalidades para gestão da construção com atualização de dados em tempo real do canteiro de obras.
O objetivo da Verum Digital é transformar projetos e impulsionar o futuro por meio da inovação digital. Buscam a excelência e trazem soluções inovadoras e estratégicas para impulsionar o sucesso dos projetos e crescimento do negócio, com metodologias eficazes e uma visão abrangente e completa, com o intuito de otimizar projetos.

#### Para mais informações ou inscrição: https://novarerh.selecty.com.br/vaga/106/vaga-para-desenvolvedor-front-end-react-jr-pl-remote-work
**Ou entre em contato pelo WhatsApp através do link:** https://api.whatsapp.com/send?l=pt_BR&phone=554398660658
![WhatsApp Image 2023-08-24 at 16 42 52](https://github.com/frontendbr/vagas/assets/67028461/aa4dbdd8-66a8-4fda-ba85-4e51663f638d)

**Comment by pedrolima4** [comment]
Pleno 3.5k... Virou bagunça.

**Comment by MathMendesReis** [comment]
Curriculo enviado!

**Comment by phvm** [comment]
Currículo enviado!

**Comment by joao160197** [comment]
Currículo Enviado

**Comment by velrino** [comment]
> Pleno 3.5k... Virou bagunça.

"Em pleno 2023..."

**Comment by reidnerjr** [comment]
Ja se encerrrou a candidatura?

**Comment by NovareRH** [comment]
Bom dia, 

Fechamos 2 vagas. 

Ainda temos vagas.

__
￼

**Comment by phvm** [comment]
O link para inscrição está expirado, há outra forma de candidatura?

**Comment by NovareRH** [comment]
Vou te passar o link de whats da recruiter da vaga e podes falar direto com ela. 
Julia Batili - https://api.whatsapp.com/send?l=pt_BR&phone=554398660658


__
￼
