### ISSUE TITLE
[Remoto] Front-end Developer

### ISSUE THREAD

**Issue by elisafonseca** [frontendbr/vagas#7842]
Aqui na Firehub, estamos focados em oferecer serviços de consultoria estratégica para empresas de logística e cadeia de suprimentos. Nossa equipe é composta por profissionais apaixonados por eficiência operacional e tecnologia, comprometidos em fornecer orientações inovadoras que otimizem as operações de nossos clientes e impulsionem o crescimento de seus negócios.

## Descrição da vaga

Temos vagas abertas para Front-End Developers em nossa equipe de desenvolvimento. Procuramos profissionais motivados, com sólidos conhecimentos em HTML, CSS e JavaScript, e uma forte vontade de aprimorar suas habilidades. Além disso, valorizamos o interesse em adquirir conhecimento ou experiência prévia em pelo menos um dos seguintes frameworks: React, Angular ou Vue.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Html
- Css
- Javascript

**Desejáveis:**
- conhecimentos em Git
- desenvolvimento ágil
- boa comunicação

## Benefícios

- Plano de saúde
- Seguro de vida
- Plano de carreira
- VR de R$ 85/dia
- Auxílio home office
- Macbook Pro
- Equipamentos auxiliares
- Brindes (camisetas, caneca, mochila e suporte p/ notebook)

## Contratação

- Horário flexível
- Férias remuneradas
- Day-Off no dia do aniversário

## Como se candidatar

Por favor envie um email para `sup@firehub.dev`  com seu CV anexado - enviar no assunto: `Vaga Front-end`

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- Estágio
- CLT
- PJ

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by Ruan-Init** [comment]
Feito.

**Comment by ViniciusGularte** [comment]
Está vaga me puxou uns alertas, e descobri vários fatos interessantes (**Bom ler**), só pro pessoal ficar atento pra onde manda seus dados, já dizia o ditado ' quando a esmola é demais, o santo desconfia' ... (  @felipefialho  entrei em contato com ela nunca postou esta vaga, bom fechar esta issue)

Primeiro foi os requisitos para a remuneração, todos requisitos são bem vagos, bem simples mesmo, e tipo 15 vagas frontend? está é uma empresa com grande investimento, porém não tem absolutamente nada na internet sobre

Fazendo uma pesquisa no WHOIS descobri que foi um dominio criado **25/05/2023** (bem recente) e tá com privacidade ativa, então não tem mais informações sobre

A pessoa que postou a vaga, primeiro ponto, a conta foi criada ontem exatamente para postar a vaga aqui ( até aqui ok, já vi isso acontecer com vagas verifidicas) agora o perfil, eu fiz uma busca texto/imagem e descobri isto..

**Elisa fonseca** é uma apostolá, não recruiter, **e eu falei com ela, e ela não postou nenhuma vaga** 😵, ou seja é um perfil falso para uma empresa que não tem nada na internet para um dominio recem criado

Abaixo o perfil dela do insta para quem quer tirar dúvida
[https://www.instagram.com/ap.elisafonseca/](https://www.instagram.com/ap.elisafonseca/)

é isto, eu sei, estamos num momento díficil, é uma vaga assim seria perfeita para todos nós, mas pessoal, cuidado, ainda mais com empresas que não tem  absolutamente nada na internet




Lugar de onde a imagem do perfil foi retirada provavelmente https://www.comunidadealiancados.com.br/agenda/491063/conferencia-jesus-at-the-center-23

**Comment by lucasgarciadev** [comment]
> **Alerta Vaga falsa**
> 
> Está vaga me puxou uns alertas, e descobri vários fatos interessantes (**Bom ler**), só pro pessoal ficar atento pra onde manda seus dados, já dizia o ditado ' quando a esmola é demais, o santo desconfia' ... ( @felipefialho entrei em contato com ela nunca postou esta vaga, bom fechar esta issue)
> 
> Primeiro foi os requisitos para a remuneração, todos requisitos são bem vagos, bem simples mesmo, e tipo 15 vagas frontend? está é uma empresa com grande investimento, porém não tem absolutamente nada na internet sobre
> 
> Fazendo uma pesquisa no WHOIS descobri que foi um dominio criado **25/05/2023** (bem recente) e tá com privacidade ativa, então não tem mais informações sobre
> 
> A pessoa que postou a vaga, primeiro ponto, a conta foi criada ontem exatamente para postar a vaga aqui ( até aqui ok, já vi isso acontecer com vagas verifidicas) agora o perfil, eu fiz uma busca texto/imagem e descobri isto..
> 
> **Elisa fonseca** é uma apostolá, não recruiter, **e eu falei com ela, e ela não postou nenhuma vaga** 😵, ou seja é um perfil falso para uma empresa que não tem nada na internet para um dominio recem criado
> 
> Abaixo o perfil dela do insta para quem quer tirar dúvida https://www.instagram.com/ap.elisafonseca/
> 
> é isto, eu sei, estamos num momento díficil, é uma vaga assim seria perfeita para todos nós, mas pessoal, cuidado, ainda mais com empresas que não tem absolutamente nada na internet
> 
> Lugar de onde a imagem do perfil foi retirada provavelmente https://www.comunidadealiancados.com.br/agenda/491063/conferencia-jesus-at-the-center-23

Poxa. Acabei de enviar o fomulário :/. Realmente pesquisei sobre a empresa e não encontrei nada a respeito. Está bem esquisito, não tanto pelo salário, mas me chamou atenção os R$85 de VR por dia. Lá no fomulário tem provas de certificação para atender a vaga. Creio pode ser esse o golpe. A pessoa paga, dependendo da prova de 55 a 355 reais e seria esse o prejuizo :/

**Comment by Ruan-Init** [comment]
Existem pessoas vagabundas em todos os lugares mesmo.

**Comment by jaaymes** [comment]
Parabéns @lucasgarciadev, Obrigado por alertar a todos

**Comment by GabrielZolk** [comment]
Como o @ViniciusGularte disse, essa coisa tá esquisita. Fora tudo que ele mencionou, chegou uma cobrança pra mim no email pra uma tal certificação 'Ranteed' (nunca nem ouvi falar) que eu tenho que fazer antes de qualquer coisa no processo seletivo. Ainda bem que eu sou desconfiado, perder dinheiro que já falta por estar desempregado ia ser muito ruim. Fiquem atentos
