### ISSUE TITLE
[Remoto] Front-end Vue.Js Dev na Omie

### ISSUE THREAD

**Issue by Luizeoliveira** [frontendbr/vagas#7844]
## Nossa empresa
A Omie tem como propósito trazer prosperidade para o ecossistema empreendedor brasileiro. Por isso, buscamos por pessoas com mentalidade de crescimento, valorizando perfis que tenham capacidade de adaptação, senso colaborativo e sejam motivadas pela inovação e pelo aprendizado contínuo.
Faça parte da história de uma das empresas de tecnologia que mais cresce no país! 🚀

#VempraOmie
## Descrição da vaga
- Trabalhar no desenvolvimento de novas interfaces de usuário, traduzindo os requisitos do produto e os designs gráficos em código funcional e responsivo.
- Manter e aprimorar nossas ferramentas internas, garantindo que estejam atualizadas, sejam escaláveis e funcionem bem em todas as plataformas e dispositivos.
- Colaborar com a equipe de back-end para integrar as APIs e os serviços de back-end e garantir uma experiência do usuário final sem interrupções.
- Auxiliar na criação de bibliotecas e frameworks reutilizáveis para futuros usos.
- Identificar e solucionar problemas de performance e gargalos para melhorar a experiência do usuário.
- Participar em reuniões de revisão de código, compartilhar conhecimentos e aprender com colegas de equipe.
- Realizar testes de unidade e de interface do usuário para garantir a funcionalidade do produto

## Local
Remoto

## Requisitos
**Obrigatórios:**
- Profundo conhecimento de HTML, CSS, e JavaScript.
- Experiência prática com o framework [Vue.js](http://vue.js/) e [Nuxt.js.](http://nuxt.js./)
- Familiaridade com a ferramenta de versionamento de código GitHub e com metodologias de desenvolvimento Ágil.
- Habilidade para desenvolver soluções para navegadores em várias plataformas e dispositivos.
- Flexibilidade para atuar em um ambiente dinâmico e capacidade de se adaptar a mudanças de prioridades.
- Atenção aos detalhes, habilidade para gerenciar vários projetos simultaneamente e cumprir prazos.
- Excelentes habilidades de comunicação verbal e escrita (o conhecimento de inglês é um plus).
- Atitude proativa e colaborativa, com forte foco em resultados.

**Desejáveis:**
- Formação em Ciência da Computação ou relacionado

**Diferenciais:**
- Experiência prévia em desenvolvimento de CRM será considerada um diferencial.

## Benefícios
- Aqui na Omie, não nos apegamos mais às nomenclaturas VR, VA e VT. Utilizamos os benefícios flexíveis, que podem ser usados em categorias de educação, saúde, vestuário, seguros, equipamentos e moradia.
- Auxílio-escritório e Auxílio Home office para você melhorar o seu ambiente de trabalho remoto e torná-lo ainda mais confortável.
- Precisa trabalhar presencialmente? Nós temos vale-transporte.
- Para manter a saúde e o bem-estar físico em dia, contamos com Apps parceiros de academias credenciadas.
- Para relaxar e cuidar da saúde mental, temos parcerias com plataformas de terapia e meditação online.
- Auxílio-creche.  
- Descontos exclusivos nas melhores faculdades e instituições de ensino, voltados para cursos de graduação, pós-graduação e MBA.
- Programa de descontos em seguros.
- Parceria com cursos de English in Company.
- Day off de aniversário, para você comemorar como quiser!
- Plano de saúde Amil.
- Plano odontológico Amil Dental.
- Empréstimo consignado via Ali Crédito.
- Seguro de vida.

## Contratação
CLT

## Como se candidatar
Candidatura via Gupy em https://carreirasomie.gupy.io/jobs/5195647. 

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by iannak** [comment]
Tem algum e-mail? Pq pra mim aparece que esse link está fechado!

**Comment by Luizeoliveira** [comment]
Vaga já foi preenchida @iannak

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
