### ISSUE TITLE
[São Paulo] Front-end Developer na Turim MFO

### ISSUE THREAD

**Issue by evandro-turim** [frontendbr/vagas#7845]
> Vaga 100% Remota 

## Nossa empresa
Fundada em 2001, a Turim é pioneira e uma das maiores gestoras de patrimônio independentes do país, atendendo demandas relativas ao patrimônio de instituições e famílias ao redor do mundo. 
Buscamos atrair os melhores talentos do mercado e promover um ambiente meritocrático e de trabalho em equipe, onde todos se sintam respeitados, desafiados e motivados a se desenvolverem profissionalmente.

#### Principais atividades
- Colaborar na criação de soluções inovadoras em front-end e back-end
- Desenvolver e manter aplicações eficientes e escaláveis
- Garantir a usabilidade e a experiência do usuário
- Traduzir requisitos de negócios em recursos técnicos em colaboração com designers e outros membros da equipe
- Realizar testes e depurar aplicativos para garantir a qualidade do software
- Participar em revisões de código para assegurar boas práticas de programação
- Manter-se atualizado sobre as últimas tendências e tecnologias em desenvolvimento front-end e back-end

## Local
Remoto

## Requisitos

**Obrigatórios:**
- Experiência com React, React Native
- Conhecimento em bancos dedados relacionais e APIs
- Familiaridade com padrões de projeto e arquitetura de software
- Capacidade para trabalhar em ambiente ágil
- Habilidades de resolução de problemas, comunicação e trabalho em equipe

**Diferenciais:**
- Experiência com metodologias DevOps e outras tecnologias mobile
- Conhecimentos em C# e Node.js
- Conhecimento em Git
- Participação em projetos  opensource

## Benefícios
- Plano de Saúde e Plano Odontológico
- Seguro de Vida
- Vale Refeição
- Participação nos Resultados

**Diferenciais:**
- Ambiente colaborativo e meritocrático que incentiva nossos colaboradores a desenvolverem todo seu potencial profissional

## Contratação
CLT

## Como se candidatar
LINK PARA AS INSCRIÇÕES
https://app.pipefy.com/public/form/twk9vKgt

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by augusto-f-rodrigues** [comment]
Enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
