### ISSUE TITLE
[Remoto] Desenvolvedor(a) Web Pl no Estadão

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#7848]
## Nossa empresa

O Estadão é uma das maiores, mais importantes e sólidas empresas de informação e comunicação do Brasil. Acreditamos que a informação é uma poderosa ferramenta de transformação social e que empodera e prepara as pessoas para os desafios do futuro.

## Descrição da vaga

Responsabilidades:

1. Trabalhar com o time de sustentação e melhorias, visando a evolução contínua de nossas aplicações; 
2. Comunicação com outros times de tecnologia, área de negócios e redação;  
3. Acompanhamento e resolução de chamados. 

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Node.Js
- React
- PHP
- Rest API
- SQL
- GIT

**Desejáveis:**

- Next.js
- Laravel
- Google Cloud

## Benefícios

- Assistência médica Bradesco, para voce e seus dependentes sem desconto mensal somente a coparticipação de 30%.
- Day off de aniversário;
- Seguro de Vida;
- Acesso ao conteúdo digital completo do Estadão;
- Descontos exclusivos em instituições de ensino;
- Plano Odontológico;
- Auxilio Psicológico.

## Contratação e Salário

- CLT
- R$ 5,000.00 a R$ 6,000.00

## Como se candidatar

A aplicação para esta vaga está ocorrendo através do site da Remotar [neste link](https://remotar.com.br/job/24115/estadao/desenvolvedor(a)-web-pl?utm_source=github). Os candidatos deverão preencher seu perfil (em torno de 5min) e o mesmo será enviado para a recrutadora do Estadão responsável pela vaga. 

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by LLucX** [comment]
Is this position still avaible?

**Comment by tatidirienzo** [comment]
> Is this position still avaible?

tá sim, manda bala :)

**Comment by LLucX** [comment]
Cool, posso falar portuguese? tenho experiência em Git , javascript , React
e obviamente css- bootstrap. já trabalho com essas linguagem a quase 3
anos, uso Linux

**Comment by LLucX** [comment]
thanks!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
