### ISSUE TITLE
[Remoto] Front-end Developer (Angular) Pleno/Sênior na @SambaTech

### ISSUE THREAD

**Issue by daiaoli** [frontendbr/vagas#7849]
## Nossa empresa

A Samba está buscando uma pessoa **Frontend Developer (Angular) Pleno/Sênior** para agregar ao nosso time! Para essa oportunidade buscamos uma pessoa para atuar em regime **CLT e 100% Remoto**. Procuramos alguém com propósito forte e que esteja disposta a trabalhar em ambiente colaborativo e dinâmico, pronto para crescer profissionalmente junto com a nossa equipe fora da curva! A Samba gosta de fazer a diferença sempre e nosso time é o responsável para que isto aconteça! Por isso, a gente espera que você seja uma pessoa apaixonada por tecnologia, assim com a gente! Todas as nossas vagas também se aplicam a pessoas com deficiência, então fique à vontade para se candidatar!

## Descrição da vaga

-Angular, Bootstrap, CSS e Typescript;
-Javascript, HTML5 e CSS3 (Bootstrap, Sass e Less);
-Ter conhecimento em versionamento de código (GIT);
-Angular, Bootstrap, CSS e Typescript;
-Ter boa comunicação e capacidade de trabalho em equipe;
-Seguir as tendências do mercado e que ser capaz de se adaptar rapidamente a novas tecnologias;
-Ter senso de organização, atenção a detalhes e foco.

Diferenciais:
-Tiver noções de docker e linux;
-Tiver noções de cloud AWS e bancos NoSQL;
-Já tenha trabalhado em uma equipe ágil.

## Local

Remoto, Brasil.

## Benefícios
-Ambiente criativo e inovador;
-Clima leve e descontraído;
-Horário flexível;
-Home office
-Auxílio home office
-Plano de Saúde;
-Plano Odontológico;
-Vale refeição/alimentação;
-Gympass;
-Day off no dia do aniversário
-Seguro de vida;
-Ways Education - Atividades extracurriculares para os filhos;

## Contratação

CLT.

## Como se candidatar

Pelo link: https://sambatech.compleo.com.br/Visualizar/160383

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by Lftho** [comment]
Bom dia @daiaoli , tudo bem ?
Agradeço pela oportunidade e já me inscrevi.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
