### ISSUE TITLE
[São Paulo-SP] Front-End Developer na Oi S/A

### ISSUE THREAD

**Issue by wrenzi** [frontendbr/vagas#785]
## Descrição da vaga
A Oi Internet está à procura de um desenvolvedor JavaScript que tenha um ótimo conhecimento de React.js e que esteja motivado para combinar a arte do design com a arte da programação. Você fará parte de um talentoso time de desenvolvimento de software que possui uma forte cultura de empresa ponto com, o que inclui trabalhar com as tecnologias mais recentes do mercado, promover eventos de Coding Dojo, Tech Talks, Hackathons, entre outros, e atuar fortemente com a filosofia Ágil.  

## Responsabilidades

- Desenvolver novos recursos voltados para o usuário (algumas aplicações em React.js)
- Otimizar aplicações para velocidade e escalabilidade máxima
- Colaborar com outros membros da equipe e partes interessadas
- Criar componentes reutilizáveis ​​e bibliotecas front-end para uso futuro
- Traduzir projetos e wireframes em código de alta qualidade
- Otimizar componentes para o máximo desempenho em uma vasta gama de dispositivos e navegadores compatíveis com a web

## Habilidades

- Forte proficiência em JavaScript, incluindo manipulação de DOM e o modelo de objeto JavaScript
- Compreensão de React.js e seus princípios fundamentais
- Experiência com fluxos de trabalho populares do React.js (como Flux ou Redux)
- Familiaridade com novas especificações do EcmaScript
- Experiência com bibliotecas de estrutura de dados (por exemplo, Immutable.js)
- Familiaridade com as APIs RESTful
- Conhecimento de mecanismos de autorização modernos, como JSON Web Token
- Familiaridade com as ferramentas modernas de front-end 
- Experiência com ferramentas comuns de desenvolvimento de front-end como Babel, Webpack, NPM, etc.
- Capacidade de entender os requisitos de negócios e traduzi-los em requisitos técnicos
- Familiaridade com as ferramentas de controle de código Git
- Conhecimento de problemas de compatibilidade cross-browser e formas de contornar esses problemas
- Familiaridade com as ferramentas de compilação front-end, como Grunt e Gulp.js
- Boa compreensão do comportamento e desempenho do renderização do navegador

## Contratação
CLT

## Local
Chácara Santo Antonio (Próx ao Shop.Morumbi)

## Como se candidatar
Por favor envie um email para wagner.renzi@oi.net.br com seu CV anexado e conta do Github - enviar no assunto: Vaga Front-End Developer

## Labels
- CLT
- Sênior

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
