### ISSUE TITLE
[Remoto] Mobile Developer na Going2 

### ISSUE THREAD

**Issue by MariaJuliaRicostiG2** [frontendbr/vagas#7852]
## Nossa empresa

A Going2 é uma startup que nasceu em 2012, com o propósito de levar tecnologia de ponta para todo o Brasil, focada em criar produtos que tenham como premissa, facilitar a vida das pessoas e empresas, através do desenvolvimento de Aplicativos, Sistemas e dos princípios de IOT (internet das coisas). Hoje, além de atender clientes nacionais também oferecemos nossos serviços para clientes internacionais, como por exemplo no Canada, Suíça e Estados Unidos.

## Descrição da vaga

**Atividades**

- Participar do processo de criação e evolução dos produtos e sistemas;
- Implementar provas de conceito e protótipos;
- Especificar sistemas, processos e APIs;
- Modelagem de dados;
- Desenvolvimento e Testes;
- Versionamento organizado no Git;
- Participar dos rituais do time (SCRUM);
- Manutenção dos produtos e sistemas com alta qualidade;
- Cumprir entregas no prazo, junto com o restante da equipe, ajudar a manter a qualidade, organização e automação de toda a aplicação;
- Pode trabalhar sozinho ou em equipe como um líder;
- Pode configurar o ambiente de desenvolvimento sozinho;
- Tem iniciativa e busca maneiras diferentes de resolver problemas;
- Revisar e refatorar os códigos existentes em códigos de alta qualidade;
- Projetar e desenhar códigos que sejam confiáveis e reutilizáveis;
- Garantir a melhor performance e usabilidade das aplicações;
- Saber identificar e corrigir gargalos, realizar debugs e fixes.

**Requisitos**

- Conhecimento em banco de dados offline;
- Conhecimento em gerenciamento de estados;
- CI/CD (AppCenter);
- Firebase;
- Notificações por push;
- Conhecimento em animações (React Native);
- Sólido conhecimento em React e React Native, Next.js, experiência com Strapi e no desenvolvimento de construtores de websites;
- Analise e resolução de problemas, trabalho em equipe, visão global do projeto;
- Conhecimento em desenvolvimento nativo com Swift e Kotlin (diferencial);
- Experiência com desenvolvimento de websites estilo onepage, experiência com desenvolvimento de construtores de websites (diferencial).

**Benefícios**

- Ajuda de custo exclusivo para convenio médico e odontológico;
- Convênio com plataforma de idiomas (Fluency Academy);
- Plataforma de treinamento Udemy Business;
- Day-Off de aniversário;
- 15 dias de descanso remunerado;
- Plano de carreira.

**Outras informações**

- Horário: 09h às 18h;
- Remoto;
- Contrato de prazo indeterminado;
- PJ.

## Contratação

PJ 

## Como se candidatar

Por favor cadastrar através do link: https://going2.vagas.solides.com.br/

#### Alocação

- Remoto

#### Regime

- PJ

#### Nível

- Pleno

**Comment by YuryRegis** [comment]
Parece que a vaga foi encerrada...

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
