### ISSUE TITLE
[FULLY REMOTE] Fullstack Developer (Java+React) - Jobsity

### ISSUE THREAD

**Issue by AngelaBarboza** [frontendbr/vagas#7853]
## About Jobsity💡
We’ve been around for about 10 years. We are a NY based staffing company that works with lots of different clients in the US, Canada and Europe.
Most of our developers, data engineers, and Quality Assurance engineers are located in Latin America, although we have a presence in more than 15 countries.
We have connected more than 400 people with international employment. We focus more on quality and long-term partnerships, between Jobsity, our candidates (you), and our clients. In fact, we only work with the top 3% of talents in LATAM.
As a member of the Jobsity Recruitment team, we are going to work to find you the right position depending on what is important to you.

## Requirements✔
It's mandatory to have at least 3 years of experience with the following skillset: 

🚨 Back-end Programming language: Java 
🚨 Framework: Spring MVC 
🚨 Front end with Typescript and React.
🚨 Solid in SQL, testing and API management.

PS: position available only for engineers located in LATAM 🗺

## Modality
👨‍💻 Fully remote

## Perks that Jobsity offers!💎

🔹15 business days of paid vacation yearly.
🔹3 extra off days per year.
🔹Paid local holidays.
🔹Unlimited PTOs.
🔹Learning budget.
🔹Financing program for equipment and home office supplies.
🔹Betterfly app (wellness).
🔹Bonuses for referrals and more!

## Type of contract📜

This is a full-time position as contractor🕘
....with USD payment 💰
....long-term relationship 🤝
...within an international team 👩‍💻 👨‍💻
...and working on international client projects! 🌎

## How to apply🤔

- Send an email to [angela.barboza@jobsity.com](mailto:angela.barboza@jobsity.com) with your CV attached - Send in the subject:  Fullstack Java+React Developer
- Or Contact me through LinkedIn: https://www.linkedin.com/in/angela-barboza/
- Or write a comment on my [post](https://www.linkedin.com/posts/angela-barboza_fulltime-fullyremote-usd-activity-7105175996806369280-Vypo?utm_source=share&utm_medium=member_desktop)!

Whatever works best for you!

**Comment by C-Nubela** [comment]
Hey Angela,

I came across your post and checked out Jobsity. I thought I'd share a tool that might be super helpful for your staffing firm. 

It's called [Proxycurl](https://nubela.co/proxycurl?utm_campaign=content_amplification&utm_source=github&utm_medium=social&utm_content=article_link), and it's a fantastic way to source candidates automatically. It provides you with several API Endpoints to do this with, specifically the [Person Search Endpoint](https://nubela.co/proxycurl/docs#search-api-person-search-endpoint?utm_campaign=content_amplification&utm_source=github&utm_medium=social&utm_content=article_link).

The Proxycurl API taps into a vast dataset of people profiles, allowing you to search for potential candidates based on specific criteria. For instance, if you're looking for a Fullstack Developer with skills in Java, React, Spring MVC, Typescript, SQL, or API management in Argentina, you can use the API to find them.

Here's a Python example to give you an idea:

```python
Copy code
import requests, json

api_key = 'YOUR_API_KEY'  # Replace with your actual API key
headers = {'Authorization': 'Bearer ' + api_key}
api_endpoint = 'https://nubela.co/proxycurl/api/search/person/'
params = {
    'skills': '(?i)Java|React|Spring MVC|Typescript|SQL|API management',
    'current_role_title': '(?i)Fullstack Developer',
    'country': 'AR',
}
response = requests.get(api_endpoint, params=params, headers=headers)
result = response.json()
print(json.dumps(result, indent=2))```

Just replace 'YOUR_API_KEY' with your actual API key, and you're good to go. [You can create your API key here](https://nubela.co/proxycurl?utm_campaign=content_amplification&utm_source=github&utm_medium=social&utm_content=article_link).

This will give you a list of potential candidates that match your criteria. For example that specific code with those parameters above returned 327 LinkedIn profiles with candidates like the following:
https://www.linkedin.com/in/martin-carniello-56b3b773

I hope this helps! If you have any questions or need further assistance, feel free to reach out at "[hello@nubela.co](mailto:hello@nubela.co)". 

Best of luck with your hiring process!

**Comment by AngelaBarboza** [comment]
The search is closed!⛔ Thank you for your messages! 😉
