### ISSUE TITLE
[REMOTO] Front-end Developer Freelancer na O2 Filmes

### ISSUE THREAD

**Issue by Roger-Siqueira** [frontendbr/vagas#7857]
## **Sobre Nós**

Imagine fazer parte de uma equipe que é o braço inovador da renomada O2 Filmes, desenvolvendo um aplicativo web para um dos sócios da produtora. Na nossa empresa mantemos um ambiente de trabalho leve e altamente comunicativo para garantir qualidade no trabalho e agilidade nas entregas.

## **Descrição da Vaga**

Estamos à procura de um talentoso desenvolvedor front-end para se juntar à nossa equipe. A vaga oferece a oportunidade de executar duas tarefas, com possibilidade de expandir para outras tarefas se necessário, são elas:

1. Implementação de funcionalidade "drag and drop" na interface já existente.
2. Integração de um sistema de login com google e apple.

Nosso projeto é predominantemente em Javascript, e estamos avançando na adoção do Typescript. No front-end, utilizamos principalmente ReactJS, enquanto nosso back-end é construído com Rails.

## **Requisitos Necessários**

- Sólida experiência em Javascript.
- Proficiência em Git.
- Experiência com Test-Driven Development (TDD).
- Habilidade para leitura e escrita em inglês.

## **Requisitos Desejáveis**

- Experiência com ReactJS.
- Conhecimento de Typescript.
- Familiaridade com Rails e Rspec.
- Experiência em Docker.

## **Responsabilidades Principais**

- Desenvolver e manter o sistema, focando no front-end.
- Garantir a qualidade do código por meio de testes de componentes e telas.
- Colaborar com colegas desenvolvedores para melhorar a usabilidade do produto.
- Utilizar o Git como ferramenta de versionamento.
- Aplicar os princípios do "clean code" em suas soluções.
- Contribuir para a documentação do projeto.
- Participar das dailies e demais reuniões técnicas.

## Como se candidatar

Se você é um desenvolvedor apaixonado por desafios junte-se a nós nesta jornada. Envie o seu currículo, portfolio e pretensão salarial para [roger@o2filmes.com](mailto:roger@o2filmes.com). Com o assunto `Vaga Front-end Developer`.
Costumamos enviar feedbacks em até 15 dias após cada processo.
Estamos ansiosos para conhecê-lo e ter você como parte da nossa equipe!

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by MathMendesReis** [comment]
curriculo enviado!

**Comment by jhefflg** [comment]
UP!!

**Comment by christinogabriel** [comment]
**Currículo Enviado **

**Comment by christinogabriel** [comment]
Currículo Enviado !!!!``
