### ISSUE TITLE
[Remoto] Front-end Developer na Going2

### ISSUE THREAD

**Issue by MariaJuliaRicostiG2** [frontendbr/vagas#7862]
## Nossa empresa

A Going2 é uma startup que nasceu em 2012, com o propósito de levar tecnologia de ponta para todo o Brasil, focada em criar produtos que tenham como premissa, facilitar a vida das pessoas e empresas, através do desenvolvimento de Aplicativos, Sistemas e dos princípios de IOT (internet das coisas). Hoje, além de atender clientes nacionais também oferecemos nossos serviços para clientes internacionais, como por exemplo no Canada, Suíça e Estados Unidos.

## Descrição da vaga

**Atividades**

- Criação de novas funcionalidades;
- Manutenção de funcionalidades já existentes;
- Aplicação de documentação;
- Gerenciamento de prazos Participação em reuniões de ritos Atualização de evolução de trabalho (Jira);
- Participação de reuniões técnicas (Internamente/Stakeholder);
- Especificar sistemas, processos e APIs;
- Modelagem de dados;
- Planejamento e estimativa de desenvolvimento;
- Desenvolvimento e Testes;
- Versionamento organizado no Git;
- Alinhamento com pares;
- Participar de comitês e grupos de acordo com suas especialidades;
- Cumprir entregas no prazo e com alta qualidade;
- Pode trabalhar sozinho ou em equipe como um líder;
- Pode configurar o ambiente de desenvolvimento sozinho;
- Tem iniciativa e busca maneiras diferentes de resolver problemas.

**Requisitos**

- Criação de código legível para outros desenvolvedores;
- Habilidades de otimização de código para torná-lo mais eficiente;
- Capacidade de quebrar as tarefas em tarefas menores;
- Revisar o código em detalhes;
- Encontrar bugs e propor plano de ação para correção;
- Orientar os desenvolvedores juniores;
- Capacidade de entender os requisitos de negócios e traduzi-los em requisitos técnicos;
- Conhecimento sólido de Javascript (Rect.Js);
- Conhecimento de Arquitetura em Camadas;
- Git (Github, bitbucket);
- NextJS Integração (API RESTful);
- Bibliotecas de design (Material UI, Styled Component);
- Conhecimento em Hooks (React Hooks);
- Typescript;
- **Diferencial:** Firebase, Docker, Google Cloud Platform, conhecimentos em Devops, conhecimentos em CI/CD e Testes (unitários, integração).

**Benefícios**

- Ajuda de custo exclusivo para convenio médico e odontológico;
- Convênio com plataforma de idiomas (Fluency Academy);
- Plataforma de treinamento Udemy Business;
- Day-Off de aniversário;
- 15 dias de descanso remunerado;
- Plano de carreira.

**Outras informações**

- Horário: 09h às 18h;
- Remoto;
- Contrato de prazo indeterminado;
- PJ.
- Contratação
- PJ

**Como se candidatar**

Por favor cadastrar através do link: https://going2.vagas.solides.com.br/

#Labels 

**Alocação**

- Remoto

**Regime**

- PJ

**Nível**

- Pleno

**Comment by lspenha** [comment]
Enviado!

**Comment by CatianoNorberto** [comment]
![image](https://github.com/frontendbr/vagas/assets/47697118/95d870fb-52d9-40d9-adb9-cd4d86758c27)
Não da para se candidatar

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
