### ISSUE TITLE
[REMOTO] Full-Stack Developer Sênior na Going2

### ISSUE THREAD

**Issue by gabrielabenite** [frontendbr/vagas#7863]
## Nossa empresa

A Going2 é uma startup que nasceu em 2012, com o propósito de levar tecnologia de ponta para todo o Brasil, focada em criar produtos que tenham como premissa, facilitar a vida das pessoas e empresas, através do desenvolvimento de Aplicativos, Sistemas e dos princípios de IOT (internet das coisas). Hoje, além de atender clientes nacionais também oferecemos nossos serviços para clientes internacionais, como por exemplo no Canada, Suíça e Estados Unidos.

## Descrição da vaga

Desenvolvedor Full-Stack Sênior que tenha conhecimento e experiência avançada com React.Js, React Native e Node.Js.

## Local

REMOTO

## Requisitos

**Obrigatórios:**

- Profundo conhecimento e experiência em desenvolvimento com TypeScript;
- Experiência sólida no desenvolvimento de aplicações utilizando NodeJS, React e React Native;
- Domínio de padrões de design de software e boas práticas de programação;
- Conhecimento em testes automatizados e frameworks associados;
- Habilidade com metodologias ágeis de desenvolvimento;
- Conhecimento em banco de dados relacionais, preferencialmente MySQL;
- Capacidade de identificar e otimizar gargalos de desempenho em aplicações;
- Familiaridade com sistemas de controle de versão, principalmente Git;
- Experiência com infraestrutura em cloud, preferencialmente GCP;
- Tecnologias Utilizadas: NestJS, TypeORM, MySQL, Firebase, Elastic Stack, Jest, React Js, React Native e Docker;

**Diferenciais:**
- Experiência ou familiaridade com Neo4j;
- Conhecimento em outras tecnologias e práticas modernas de desenvolvimento.

## Benefícios

- Ajuda de custo exclusivo para convenio médico e odontológico;
- Convênio com plataforma de idiomas (Fluency Academy e Yowza);
- Plataforma de treinamento Udemy Business;
- Day-Off de aniversário;
- Folga em feriados nacionais;
- 15 dias de descanso remunerado;
- Plano de carreira.

## Contratação

PJ

## Como se candidatar

Por favor cadastre seu currículo através do link:  https://going2.vagas.solides.com.br/

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
