### ISSUE TITLE
[Remoto] Front-end Developer na Mission Brasil

### ISSUE THREAD

**Issue by paruckerr** [frontendbr/vagas#7864]
## Mission Brasil

Aqui na [Mission Brasil](https://www.missionbrasil.com.br) estamos construindo algo disruptivo, inovador e gostaríamos que você fizesse parte desse grande desafio que temos pela frente.

## Descrição da vaga

Buscamos pessoas desenvolvedoras que curtam novos desafios, que busquem resolver problemas, entregar tarefas com qualidade, auto-gerenciamento e que tenham boa comunicação.

## Requisitos

**Obrigatórios:**
- Reactjs;
- NextJs ~13;
- Vercel;
- Hooks;
- Tailwind;
- Noções de UX;
- Restful API oriented design;

**Diferenciais:**
- Flexibilidade de horário;

## Como se candidatar

Por favor envie um [e-mail](mailto:eduardo.parucker@missionbrasil.com.br) para  com seu CV anexado - enviar no assunto: Vaga Front-End Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

E-mail para contato em caso de não haver resposta: eduardo.parucker@missionbrasil.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by Mraimundo** [comment]
Olha queria relatar que ao submeter o email está sendo rejeitado. Será que esse é e-mail certo que está na descrição da vaga?

![email](https://github.com/frontendbr/vagas/assets/53385345/b9d833e9-b70c-4658-bbb9-833f190b453d)

**Comment by paruckerr** [comment]
Vou trocar lá, obrigado!

Pode já manda por aqui, Abs!

**Comment by rickdouglas** [comment]
Enviado !

**Comment by joao160197** [comment]
Enviado

**Comment by ribeiroevandro** [comment]
Enviado!

**Comment by ZeVit0r** [comment]
Enviado!

**Comment by guim0** [comment]
Enviado!!!

**Comment by Dirosaki** [comment]
Enviado!

**Comment by LucasAnselmoSilva12345** [comment]
Enviado!!

**Comment by EnriqueSantos-dev** [comment]
Enviado
