### ISSUE TITLE
[São Paulo/SP] FullStack Developer na ITeam (Foco em FrontEnd)

### ISSUE THREAD

**Issue by VivianeRHTI** [frontendbr/vagas#7868]
> Atendimento presencial

## ITeam

Há mais de 15 anos presente no mercado, a ITeam oferece o comprometimento com o cliente.
Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 
Com uma equipe multidisciplinar, a ITeam proporciona uma área de Serviços Gerenciáveis como Projetos SAP, Fábrica de Software, Fábrica de Soluções e Sustentação. Neste modelo proporcionamos Sustentação, Melhorias e Desenvolvimentos de aplicação de forma integrada.

## Local

São Paulo/SP - Chácara Santo Antônio (Z/S)
Horário de trabalho: Segunda-feira à quinta-feira das 7h30m às 17h30m. 
Sexta-feira das 7h30m às 16h30m 

## Requisitos

Experiência em HTML 5; CSS 3; Javascript; TypeScript; Angular; MicroFrontend (desejável).
Metodologias ágeis Scrum/Kanban; Git e GitFlow;
Algoritmos e estruturas de dados;
Consumo de APIs (Rest, SOAP, GraphQL e GRPC);
Comunicação em tempo real (WebSocket, SignalR e WebHooks).

## Diferencial
Conhecimento em .NET Framework 4; .NET Core; 
WPF, Xamarin e/ou MAUI;
Blazor; Web Assembly; MVC.

## Atividades

Desenvolvimento dos clientes que permitem o acesso aos processos de negócio disponíveis por meio do sistema;
Elaborar os testes unitários conforme os cenários especificados pelo QA. 
Ferramentas: Visual Studio; Postman, SoapUI e Insomnia.

## Contratação

Tempo indeterminado - Longo prazo

## Como se candidatar

Por favor, envie um e-mail para viviane.pereira@iteam.inf.br com seu currículo anexado e pretensão de taxa/hora - enviar no assunto: FrontEnd presencial.

## Labels

HTML
CSS
Javascript
TypeScript
Angular
MicroFrontend 
SCRUM
GIT

# Alocação
Presencial

## Regime
PJ ou a combinar

## Nível
Sênior

**Comment by cosmo-rodrigues** [comment]
@felipefialho

**Comment by ITeam-oportunidades** [comment]
Sim, a vaga presencial.

**Comment by MrS4w** [comment]
> Frontend Presencial com a tag remoto??????

Removido

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
