### ISSUE TITLE
[Remoto] Front-end Developer na Micromed

### ISSUE THREAD

**Issue by feliperbroering** [frontendbr/vagas#7871]
## Nossa empresa

A Micromed é uma empresa brasileira que desenvolve, produz e vende equipamentos médicos e sistemas com foco na cardiologia, telemedicina e controle da hipertensão. Atua no Brasil e na América Latina por 30 anos.

Saiba mais sobre a empresa no nosso site [micromed.health](https://micromed.health).

## Descrição da vaga

Estamos em busca de 1 front-ender para compor nosso time de web / plataforma de saúde digital. 

Nos últimos dois anos construindo uma plataforma de saúde digital nova, do zero. Já temos um [produto novo desenvolvido](https://news.micromed.health/kardia) e lançado no mercado em cima dessa nova plataforma. Nossos produtos digitais/web estão se tornando o hub principal de soluções da empresa, recebendo todos os fluxos de trabalho dos médicos cardiologistas e integrando os hardwares que fabricamos com a web.

Um pouco da nossa stack de front: React, NextJS, Typescript, React Testing Library, Storybook, [React Styleguidist](https://herz-ui.micromed.io/), [gRPC-Web](https://grpc.io/docs/platforms/web/basics/). 

Utilizamos nosso próprio Design System e lib de front-end open-source, a [Herz-UI](https://github.com/micromedio/herz-ui) ❤️  (PRs são bem vindos!).

Ferramentas que usamos no dia a dia da engenharia: Designs no [Figma](https://figma.com/), Issues e documentações no [Linear](https://linear.app/), Código no [Github](https://github.com/), Hosting do FE na [Vercel](https://vercel.com), Cloud no [Google Cloud](https://cloud.google.com/), comunicação do time no [Discord](https://discord.com).

## Local

* Remoto

## Requisitos

**Obrigatórios:**
- Domínio profundo de HTML e CSS;
- Domínio profundo de Javascript;
- Projetos passados reais com ReactJS;
- Typescript;
- Nextjs;

**Desejáveis:**
- Testes com React Testing Library
- GraphQL;
- Noções de backend / NodeJS;
- Vivência com Cloud Provider: Vercel

**Diferenciais:**
- Renderização de elementos gráficos e sinais em SVG ou Canvas

## Benefícios

- Plano de Saúde;
- Vale Refeição ou Alimentação;
- Seguro de Vida;
- Plano de Saúde;
- Plano Odontológico;
- Apoio a saúde mental e desenvolvimento emocional – Zenklub;

## Contratação

- Regime CLT

## Como se candidatar

- Responder nosso [Questionário Inicial](https://forms.gle/gdtniEFVFfEdkXyt5) que entraremos em contato pelo linkedin.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 48h após cada oi.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by lucasaugustodeveloper** [comment]
Não teria outro meio de comunicação? Pois esse perfil só premium poder mandar mensagem

**Comment by danrleyney2210** [comment]
Este perfil é privado, aguardando aceitar minha solicitação

**Comment by felipemimoura** [comment]
Mensagem enviada.

**Comment by joao160197** [comment]
Mandei solicitação lá

**Comment by brunoliimas** [comment]
Mensagem enviada

**Comment by claudiocassimiro** [comment]
Mandei solicitação

**Comment by joao160197** [comment]
Mensagem enviada

**Comment by lucasrip** [comment]
solicitação de amizade enviada

**Comment by BernardoSemiOficial** [comment]
Relatório enviado

**Comment by DiegoRodrigues007** [comment]
oi

**Comment by DiegoRodrigues007** [comment]
Enviado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
