### ISSUE TITLE
[Remoto] React Front-End Developer na MaisTODOS

### ISSUE THREAD

**Issue by anabeatrizzz** [frontendbr/vagas#7876]
## Nossa empresa

A MaisTODOS nasceu de uma vontade genuína de fazer a diferença na vida das pessoas com dificuldades em acessar o sistema financeiro complexo e burocrático do Brasil.

Nosso propósito é levar soluções financeiras simples e transparentes para mais de 12 milhões de pessoas, que já são clientes do Cartão de Todos, e expandir ainda mais nossas soluções para fora do grupo.

Há mais de 20 anos, o Cartão de Todos é referência para clientes que possuem renda familiar de até 10 salários mínimos. É o principal instrumento de acesso à saúde de qualidade, disponibilizada pelas clínicas AmorSaúde, que oferecem consultas médicas e odontológicas a um preço justo.

E queremos ainda mais: A MaisTODOS quer ser o que o Cartão de Todos representa quando o assunto é o acesso à saúde: democrático, simples e transparente.

## Descrição da vaga

**Responsabilidades**:
- Irá desenvolver aplicações mobile e web, utilizando ferramentas e tecnologias adequadas ao projeto;
- Ser referência técnica para o time;
- Lidar com versões para clientes, correção e manutenção no projeto;
- Planejamento de tarefas.

## Local

Remoto

## Requisitos

**Técnicos:**
- Conhecer sobre React, React-Native, boas práticas de desenvolvedor front-end, técnicas de gerenciamento de projetos como Git, boa comunicação, ter mais de 5 anos de experiência com Front-end;
- GitHub;
- Stitches/Styled components;
- React/React Native/Javascript;
- XCode;
- Gerar versões de aplicativos;
- MySql.

**Comportamentais**:
- Boa comunicação;
- Espírito de liderança;
- Protagonismo;
- Resolução de problemas.

**Desejáveis:**
- Vercel/Aws/Google Cloud;
- Docker.

## Benefícios

- Assistência Médica
- Acadêmia / Práticas Esportivas
- Universidade Corporativa
- Curso de Línguas
- Desconto em Produtos

Além de todos estes benefícios, a MaisTODOS também oferece PLR anual!

## Contratação

PJ

## Como se candidatar

- 99jobs: https://99jobs.com/maistodos/jobs/320687
- LinkedIn: https://www.linkedin.com/jobs/view/3649851297

## Para mais informações:

Entrar em contato com Lucas Torres via [LinkedIn](https://www.linkedin.com/feed/update/urn:li:ugcPost:7109958499115130881?commentUrn=urn%3Ali%3Acomment%3A%28ugcPost%3A7109958499115130881%2C7109958567452893185%29&dashCommentUrn=urn%3Ali%3Afsd_comment%3A%287109958567452893185%2Curn%3Ali%3AugcPost%3A7109958499115130881%29)

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by guim0** [comment]
vcs tem email? a plataforma 99 está estranha, outra duvida, pq o XCode? o dev precisa ter macbook?

**Comment by anabeatrizzz** [comment]
Editei a descrição e acrescentei o link para a vaga no LinkedIn também, só tem esses dois meios para se candidatar.

Não tenho essa informação de obrigatoriedade de MacBook, porém, a empresa ajuda com os equipamentos necessários.

@guim0

**Comment by GuScarpim** [comment]
Enviado!

**Comment by lucasrip** [comment]
boa tarde eu tenho 1 ano de experiencia profissional como desenvolvedor front end mas tenho experiencia a acadêmica e de projetos de mais de 5 anos , teria algum problema eu me candidatar para vaga?

**Comment by anabeatrizzz** [comment]
Acredito que não tem problema nenhum. A vaga cita experiência com front-end, então sua experiência, mesmo que acadêmica, te ajude na candidatura

@lucasrip

**Comment by lucasrip** [comment]
@anabeatrizzz ok obrigado

**Comment by anabeatrizzz** [comment]
Apenas tenho detalhes sobre o que está escrito na issue. Se precisar de mais alguma informação, acrescentei o contato da pessoa responsável pela vaga na descrição

@emirdeliz

**Comment by anabeatrizzz** [comment]
Esta vaga não aceita mais candidaturas
