### ISSUE TITLE
[Remoto] Front-end Junior Developer na SEVN

### ISSUE THREAD

**Issue by kazzkiq** [frontendbr/vagas#7878]
## SEVN

<br>
<br>
<p align="center">Prazer, somos a <a href="https://sevn.technology/">SEVN</a>.</p>
<br>
<br>

<p align="center">
<img width="800" alt="Frame 2@2x" src="https://user-images.githubusercontent.com/1953194/151902767-d2961d40-05f0-44bd-978c-dc7f14f76736.png">
</p>

<br>
<br>

Olá, somos a SEVN! Uma empresa jovem, versátil, que não tem medo de adotar novas tecnologias para entregar o melhor produto a clientes exigentes!

Atuamos na criação de apps mobile, sites, PWAs, sistemas web e serviços backend para clientes de pequeno, médio e grande porte em todo o Brasil.

## Descrição da vaga

Seu trabalho será criar, alterar e corrigir componentes utilizados em grandes portais de notícias que impactam milhões de usuários mensais por todo Brasil, utilizando principalmente as tecnologias: Handlebars, HTML e CSS.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Conhecimento em HTML
- Conhecimento em CSS (CSS mesmo, não Tailwind)

**Desejáveis (é legal se souber, mas não atrapalha o processo seletivo):**
- LESS e/ou SASS
- Handlebars
- Git
- JavaScript
- WebComponents
- Node.js

## Benefícios

- 100% remoto, pra sempre.

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para vagas@sevn.technology com seu CV anexado - enviar no assunto: `Vaga  Front-end Junior`

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até **48 horas** após cada processo.
E-mail para contato em caso de não haver resposta: contato@sevn.technology

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior

**Comment by davisantanan** [comment]
Olá, e-mail enviado.

**Comment by VictorMFL** [comment]
Bom dia, e-mail enviado.

**Comment by gustavros** [comment]
Enviado!

**Comment by Mutzzz** [comment]
Bom dia, currículo enviado.

**Comment by robertosouzajr7** [comment]
enviado

**Comment by MarcosBastosSilva** [comment]
Email enviado.

**Comment by lucasrip** [comment]
boa tarde , email enviado estou no aguardo do seu retorno

**Comment by RafaelAndradeVitorio** [comment]
Boa tarde!
Enviado. :D

**Comment by vanessawin** [comment]
Boa tarde para qual email envio, estava atualizando meu curriculo

**Comment by RafaelAndradeVitorio** [comment]
Boa noite!
Não sei se entendi muito bem o seu email, mas meu email é
***@***.*** e enviei meu currículo para a vaga de dev Jr Frontend
para  ***@***.***

Em seg., 2 de out. de 2023 às 18:01, Vanessa Gerbelli <
***@***.***> escreveu:

**Comment by tercioo-gabriel** [comment]
Se ainda disponível gostaria de enviar meu currículo.

**Comment by deniseschirmer** [comment]
Qual email posso enviar meu curriculo?

**Comment by ViniciusDuarte17** [comment]
Não encontrei o e-mail para enviar o currículo

**Comment by siuburu** [comment]
Já tá fechada a issue galera.

**Comment by luizrl** [comment]
Alguém recebeu alguma resposta? Enviei o e-mail na segunda, e até agora não recebi nenhum tipo de confirmação.
