### ISSUE TITLE
[Recife] Front-end na <bold>

### ISSUE THREAD

**Issue by jsvini** [frontendbr/vagas#788]
## Como se candidatar

Enviar email com portfólio para: **selecao.frontend@boldcomunicacao.com.br**

## Descrição da vaga

Procuramos um desenvolvedor que goste de aprender coisas novas e ame o que faz. O objetivo é garantir uma experiência de uso mais consistente e agradável para nossos usuários.

Você irá trabalhar em conjunto com a equipe de UX e irá participar da construção de uma nova geração de aplicações e serviços para o mercado de e-commerce.

Na **&lt;bold&gt;** você irá trabalhar em um ambiente que valoriza as boas práticas de programação e um método de trabalho realmente ágil. Todos desenvolvedores contam com um ambiente onde a autonomia e a coragem são bastante estimulada e valores como confiança, companheirismo e crescimento são colocados em prática no dia-a-dia.

Procuramos programadores que gostem de aprender coisas novas, e que amam o que fazem. Para mais informações sobre o que estamos criando visite nosso site https://boldcomunicacao.com.br.

## Requisitos

**Obrigatórios:**

Conhecimentos em HTML5, CSS3;
Experiência com design responsivo;
Ter conhecimento avançado de Javascript;
Ter conhecimento de criação de SPA's, preferencialmente em React;
Consumo de API's RESTful;
Git para versionamento de código;

**Desejáveis:**

Pré processadores (SASS, LESS)
Task runners (Gulp, Grunt etc)

**Diferencias:**

Conhecimento na plataforma VTEX

## Local

Nosso escritório fica em [Recife - Boa viagem](https://www.google.com.br/maps/place/Bold/@-8.1227826,-34.9056677,15z/data=!4m2!3m1!1s0x0:0x101dcdfdbad474a9?sa=X&ved=0ahUKEwjWqdGOuZHZAhWLF5AKHbOEDsMQ_BIIfjAK)

## Labels

- Alocado
- CLT

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
