### ISSUE TITLE
[São Paulo] Front-end Developer na Veste S.A

### ISSUE THREAD

**Issue by gtotti2** [frontendbr/vagas#7882]
Veste
Somos uma das maiores varejistas de moda alto padrão do Brasil. 

Mas não somos apenas uma marca de roupas ou lojas. Muito mais que isso, somos um estilo de vida, uma experiência única, um sentimento de bem-estar, realização, felicidade, inspiração, beleza; um sonho bom.

Nosso grupo tem cinco marcas (Le Lis , Bo.Bô, John John, Dudalina e Individual), duas indústrias, dois centros logísticos, corporativo em SP, cerca de 210 lojas, presença em mais de mil multimarcas pelo Brasil e completa experiência digital.

É através de nossos produtos, lojas e equipe que atingimos nosso objetivo. Somos um time de realizadores que concretizam o sonho dos nossos clientes.

Somos moda. Somos sonhos. Somos um #TimeDeApaixonados

VESTE | www.veste.com
Le Lis Blanc | www.lelis.com.br
Bo.Bô | www.bobo.com.br
John John | www.johnjohndenim.com
Dudalina | www.dudalina.com.br
Individual | www.individual.com.br

Local
São Paulo/SP - Vila Leopoldina (Z/O)
Horário de trabalho: Segunda-feira à Sexta-feira (Flexível - Preferencia horário comercial).

Requisitos
Experiência em HTML 5; CSS 3; Javascript; TypeScript; React; .
Metodologias ágeis Scrum/Kanban; Git e GitFlow;
Consumo de APIs (Rest, GraphQL );

Diferencial
Conhecimento em Vtex.IO;

Projetos que você vai participar:
E-commerce;
Aplicativos mobile;

Desafios que você terá aqui:
Aplicações escaláveis, performáticos e resilientes;
Envolvimento na evolução de produtos digitais de grande impacto;
Performance frontend;

Atividades do dia-a-dia:
Interação com os stakeholders dos projetos;
Atuar em produtos de grande impacto;
Participar do fluxo do time;
Tratar qualidade de forma contínua;
Análise técnica e levantamento de riscos;
Trabalhar em grupo para o bem do grupo;
Autogestão.

Contratação
CLT - Tempo indeterminado - Longo prazo

Como se candidatar
Por favor, envie um e-mail para gian.santos@veste.com com seu currículo anexado e enviar no assunto: Desenvolvedor Front-end.

Labels
HTML
CSS
Javascript
TypeScript
React
Vtex.IO
GIT

Alocação
Híbrido

Regime
CLT

Nível
Pleno
Sênior

**Comment by felipemimoura** [comment]
Enviado Gian..

**Comment by GuScarpim** [comment]
Enviado!

**Comment by volicar** [comment]
Enviado.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
