### ISSUE TITLE
[SP - são paulo] Desenvolvedor Front-end Vue.js Pleno - 

### ISSUE THREAD

**Issue by ecossistemadev** [frontendbr/vagas#7883]
## Descrição da vaga

Estamos buscando um desenvolvedor Frontend pleno para se juntar à nossa equipe. O candidato será responsável pelo desenvolvimento de sites promocionais responsivos, bem como por melhorias e ajustes em nossa plataforma já consolidada. É essencial possuir experiência em desenvolvimento frontend, utilizando HTML e CSS3, Bootstrap , Vue.js, incluindo conceitos avançados como Display flex e Grid.

## Local

SP - são paulo

## Requisitos

-Ensino Superior Completo ou Cursando.
-Residir em São Paulo (Faria Lima) ou regiões próximas.

**Atividades e responsabilidade:**

-Atuar no desenvolvimento Frontend;
- Atuar no desenvolvimento de sites promocionais responsivos;
- Atuar no desenvolvimento de melhorias e ajustes em uma plataforma já consolidada.
- Experiência em desenvolvimento frontend utilizando HTML e CSS3 (Display flex, Grid, etc...);
- Experiência em HTML, CSS responsivo, Layout;
- Experiência com Bootstrap 4, Github, Vue.js e Vuex;
- Background de designer;
- Boas práticas de programação.
- Conhecimento consolidado

**Mais Informações:**

Horário: Segunda a Sexta – das 10:00 as 19:00h

## Benefícios

-Vale Transporte
-Vale Refeição

## Contratação

clt

## Como se candidatar

# [🔗 Clique aqui para se candidatar](https://empregos.dev/vaga/desenvolvedor-front-end-vuejs-pleno-6683)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 60 dias após cada processo.
E-mail para contato em caso de não haver resposta: 

#### Regime

clt

#### Nível

pleno

**Comment by felipefialho** [comment]
@ecossistemadev Titulo tá fora do padrão e não tem o nome da empresa

Essa vaga é pra contratação em qual empresa?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
