### ISSUE TITLE
[Remoto] Frontend Developer - React na Coodesh

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#7885]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/frontend-developer-react-154707337?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A Truckpag busca um Frontend Developer - React para compor seu time!</p>
<p>A Truckpag, startup de Meios de Pagamento está em busca de profissionais que queiram causar impacto relevante no mundo, solucionar grandes problemas e tornar operações logísticas mais efetivas, mais assertivas e mais competitivas. Entendemos que grandes ideias nascem de vivências, formações e pessoas únicas, que gostam de trabalhar em um ambiente de colaboração, alta performance e descontraído, para agregar à nossa equipe.</p>
<p>Na Truckpag,  são desenvolvidos diferentes projetos no ramo da gestão de frotas. Como Frontend Developer, o seu trabalho nesses projetos incluirá:</p>
<ul>
<li>Desenvolvimento e manutenção de funcionalidades de sistemas de gestão para atender ao negócio da empresa;</li>
<li>Migração dos sistemas de gestão legados utilizando novas tecnologias e boas práticas de projetos em React;</li>
<li>Testes do sistema para garantir a responsividade e eficiência do sistema.</li>
</ul>
## Truckpag: 
 <p>Somos uma empresa de meios de pagamento especializada em gestão de frotas, com nosso cartão TruckPag, o cliente abastece com economia, facilidade e total controle. Com a CIOTPag, o cliente tem soluções completas para a sua gestão de frete a partir da emissão de CIOT e pagamento eletrônico de frete (PEF) . Além disso, a PagPedágio possibilita que as viagens sejam bem mais rápidas, sem precisar enfrentar filas de pedágios, em todo território nacional.</p>
<p>Somos 100% TruckPag: sem bancos, sem fundos, sem intermediadores e sem burocracia.</p><a href='https://coodesh.com/companies/truckpag-meios-de-pagamento'>Veja mais no site</a>

 ## Habilidades: 
 - React.js 
- Javascript 
- HTML 5 
- CSS 3 
- GIT 
- Typescript
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência na criação de SPA's utilizando os principais conceitos do React 
- Conhecimento em gerenciamento de estados globais (Redux/Redux Toolkit ou Context API ou outra ferramenta equivalente) 
- Conhecimento em integração com API REST 
- Conhecimento em testes utilizando jest 
- Conhecimento em versionamento de código utilizando git
## Diferenciais: 
 - Conhecimento/experiência com Typescript 
- Conhecimento/experiência com algum framework css (Material UI, etc.) 
- Conhecimento/experiência com UI e UX
## Benefícios: 
 - Horário Flexível 
- Parceria Alura
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Developer - React na Truckpag](https://coodesh.com/jobs/frontend-developer-react-154707337?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by joao160197** [comment]
Tá dizendo que tá congelada a vaga

**Comment by FrancieleGhizzoni** [comment]
Vaga em validação de currículos
