### ISSUE TITLE
[PR - curitiba] Desenvolvedor(a) Front End Trainee - 

### ISSUE THREAD

**Issue by ecossistemadev** [frontendbr/vagas#7886]
## Descrição da vaga

Estamos em busca de um Desenvolvedor Front End Trainee altamente talentoso e motivado para se juntar à nossa equipe. Você será responsável por criar interfaces de usuário incríveis para nossos aplicativos web e móveis, utilizando suas habilidades em Ruby, React, Vue, Javascript, HTML e CSS.

## Local

PR - curitiba

## Requisitos

- Experiência com as seguintes linguagens: Ruby, React, Vue, Javascript, HTML, CSS;
- Desenvolver interfaces para aplicativos;
- Trabalhar com desenvolvimento de aplicativos novos (Web e Mobile).

**Mais Informações:**

Segunda à Sexta - 08h30 às 17h30min / 1 h de intervalo

## Benefícios

- Vale Transporte.
- Vale Refeição de R$ 21,50 por dia.

## Contratação

clt

## Como se candidatar

# [🔗 Clique aqui para se candidatar](https://empregos.dev/vaga/desenvolvedora-front-end-trainee-8943)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 60 dias após cada processo.
E-mail para contato em caso de não haver resposta: 

#### Regime

clt

#### Nível

trainee

**Comment by ecossistemadev** [comment]
Bom dia, tudo bem?

Definição de trainee: Trainee é alguém que está em treinamento, ou seja, a
ideia é que a pessoa seja preparada e tenha potencial para assumir cargos
futuramente. Embora o trainee seja uma pessoa com pouca experiência no
mercado, ele está em busca de oportunidade de desenvolvimento ,
principalmente após se graduar na faculdade.

Tipo de contrato: CLT

Portanto está sujeito as regras da CLT, e precisam trabalhar 40 horas
semanais, o que pode contabilizar 8 horas por dia.

Espero que tenha sido esclarecido suas dúvidas

Em seg., 9 de out. de 2023 09:18, Pedro Limma ***@***.***>
escreveu:

**Comment by devIgor1** [comment]
Bom dia! Não estou conseguindo me cadastrar na plataforma, acredito que seja por conta do formato pedido do celular..

**Comment by ecossistemadev** [comment]
@devIgor1 poderia tentar, novamente a gente fez alguns ajustes, relacionado a isso agorinha..
Se continuar o problema entre em contato pelo e-mail: contato@empregos.dev

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
