### ISSUE TITLE
[Híbrido em Belo Horizonte] Angular Developer Pleno @Rhitmo Tech 💙

### ISSUE THREAD

**Issue by gabirecruiter** [frontendbr/vagas#7887]
**[VAGA TEMPORÁRIA]**

Somos a **RHITMO Tech** e aqui desenvolvemos tecnologia para pessoas! 💙

Um time que está sempre pronto para decolar e é capaz de criar e desenvolver projetos que mudam positivamente a vida das pessoas, solucionando problemas e transpondo obstáculos. Essa é a nossa missão e procuramos por talentos para compor o nosso time de tecnologia e nos apoiar nessa jornada, atuando com Desenvolvimento front-end Angular💻

Quer conhecer um pouco mais sobre nós? Nossas redes sociais: 📱

https://rhitmotech.com.br/
https://www.instagram.com/rhitmotech/
https://br.linkedin.com/company/rhitmotech

## Descrição da vaga:

- Desenvolver aplicações web de alta qualidade usando Angular, Angular Material com TypeScript.
- Criar componentes e módulos reutilizáveis para garantir um desenvolvimento eficiente e escalável.
- Implementar recursos interativos e responsivos, garantindo uma ótima experiência do usuário.
- Colaborar com a equipe de design para transformar requisitos em interfaces atraentes e funcionais.
- Trabalhar em conjunto com a equipe de desenvolvimento para garantir a integração perfeita com o back-end.
- Escrever código limpo e legível, seguindo as melhores práticas de desenvolvimento.

## Local

Estamos em **Belo Horizonte - MG**!

## Requisitos

- Experiência no desenolvimento de aplicações web usando Angular, Angular Material e TypeScript.
- Expertise em HTML, CSS e JavaScript.
- Capacidade de traduzir requisitos de negócio em soluções técnicas eficientes.
- Experiência com design responsivo e desenvolvimento cross-browser.
- Conhecimento sólido de padrões de design e arquitetura de software.
- Habilidade de resolução de problemas e depuração.
- Capacidade de trabalhar de forma independente e em equipe.
- Habilidade de comunicação verbal e escrita.

Será considerado um diferencial:

- Experiência com testes unitários e integração.
- Conhecimento de ferramentas de controle de versão, como Git.
- Familiaridade com metodologias ágeis de desenvolvimento, como Scrum ou Kanban.
- Experiência com outras tecnologias front-end, como React ou Vue.js.
- Conhecimento em UX/UI e design de interfaces amigáveis.

## Benefícios

- Modelo de contratação: PJ (full time)
- **Contrato de 3 meses com possível internalização do cliente.**
- Interrupção remunerada de 15 dias;
- Bonificação por indicação de Desenvolvedores;
- Revisões por ano na remuneração;

## Como se candidatar:

Envie o seu currículo + pretensão para o e-mail: rh@rhitmo.com.br 📧

Pode se conectar comigo no LinkedIn também:
https://www.linkedin.com/in/mariagabrielacs/ 👩‍💻

**#VEMPRARHITMO!** 🚀👩‍🚀

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
