### ISSUE TITLE
[Remoto] Front-end Developer na D2W

### ISSUE THREAD

**Issue by gabrielleleitej** [frontendbr/vagas#7888]
## Nossa empresa

A Data2Win é uma consultoria que possibilita os clientes alocação de profissionais de TI no mercado. 

## Descrição da vaga

Estamos em busca de uma pessoa desenvolvedora Front End Pleno, com foco em Vue.js.

## Local

Remoto 

## Requisitos

**Obrigatórios:**
Vue.js  

HTML, CSS e SASS 

Javascript e ES6+ 

Git 

Design Responsivo  

Requisições HTTP 

  
 
**Diferenciais:**
Vuex (Gerenciamento de estado) 

Testes Unitários e E2E (jest, Cypress e outros) 

Ferramentas de build e empacotamento 

React / React Native 

## Benefícios

- Clube de descontos 

## Contratação

Cooperado (Salário é informado na primeira conversa)

## Como se candidatar

Por favor se candidate pelo link: https://d2w.pandape.infojobs.com.br/Detail/677068

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@data2win.com.br

#### Alocação
- Alocado
- Remoto

#### Regime
-Cooperado 

#### Nível
- Pleno

**Comment by reinaldocicarone** [comment]
Enviado

**Comment by felipemimoura** [comment]
Enviado

**Comment by joao160197** [comment]
Enviado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
