### ISSUE TITLE
[REMOTO] Fullstack Developer C# e Angular PLENO - Truppe

### ISSUE THREAD

**Issue by Camila-Goms** [frontendbr/vagas#7889]
## Nossa empresa

A [Trupppe!](https://truppe.team/) é uma empresa de consultoria de tecnologia com foco em desenvolver e aprimorar talentos referência em recrutamento, seleção e alocação de profissionais de TI. Criada há 4 anos, está em fase de desenvolvimento e crescimento, expandindo seu portfólio de produtos e serviços, trabalhando também com transformação e aceleração digital. 

Nossa missão é conectar os melhores profissionais às melhores oportunidades, proporcionando seu crescimento na carreira.

## Descrição da vaga

Buscamos uma pessoa Desenvolvedora Fullstack C# e Angular para atuar em um dos nossos clientes.

## Local

Remoto ou híbrido no estado de SP (combinar).

## Requisitos

• Ensino Superior Completo em Sistemas da Informação, Ciências da Computação, Redes de Computador ou áreas afins;
• Mínimo de 3 anos de experiência como desenvolvedor;
• Conhecimentos em Angular;
• Experiência com desenvolvimento de aplicações Web em .NET C#;
• Conhecimentos em Java Script, CSS e tecnologias associadas ao desenvolvimento web;
• Conhecimentos de desenvolvimento de aplicações com uso de banco de dados SQL;
• Experiência com o uso de metodologias ágeis;
• Facilidade de relacionamento com clientes internos para entendimento das necessidades e transformação das expectativas em soluções sistêmicas;
• Interesse em aprender sobre o negócio e curiosidade para investigar possíveis soluções;
• Perfil colaborativo.

## Contratação

- CLT (pretensão salarial de pleno)

## Nível

- PLENO

## Como se candidatar

Envie um email para camila.gomes@truppe.team com seu *Currículo em português atualizado* anexado, link do perfil do Linkedin (se tiver) e pretensão salarial CLT no corpo do email.

Enviar no assunto: *Vaga Desenvolvedor Fullstack C# e Angular*

**Comment by devlcgomes** [comment]
Enviado!

**Comment by Camila-Goms** [comment]
VAGA ENCERRADA! 24/10/2023
