### ISSUE TITLE
[Florianópolis] Estágio em UI na McFadyen Digital 

### ISSUE THREAD

**Issue by phameister** [frontendbr/vagas#789]
## Descrição da vaga

As a Front-end Developer Intern, you will learn to implement eCommerce solutions for our clients using the Oracle Commerce (ATG) and Oracle Commerce Cloud platforms. 

You will develop yourself to be responsible for the user experience development, which is an important component of eCommerce solutions. You will work with related technologies such as JavaScript, CSS, HTML and JSON. 

We will help you develop expertise in all phases of a project's life-cycle from analysis to development using agile methodologies. 

We will help you continue to build and deliver world class systems.Exciting projects will continue to broaden your industry experience and continuously enhance your skills with new challenges. McFadyen has a very open culture where every individual is given an opportunity to highlight their expertise and best practices in a team environment. 

## Local

Bairro Itacorubi, Florianópolis/SC

## Benefícios

Vale Transporte

## Bolsa
R$ 1,100.00

## Requisitos

**Obrigatórios:**

• Knowledge in front-end development and JavaScript
• Must have great Portuguese and English communication skills (speaking, reading, and writing)
• Excellent technical problem solving skills
• Attending to Computer Science, Software Development, System Analysis, Information Technology Graduation or related areas.

## Contratação

Estágio

## Nossa empresa

McFadyen Solutions has completed more than 300 large-scale IT implementations for a prestigious client list, including dozens of the Fortune 500. Our proficiencies include eCommerce, web content management, online relationship management (B2C, B2B, B2E), and ERP integration. Our unique approach of focusing on select software partnerships allows McFadyen’s consultants to immerse themselves in specific technologies, thus providing the deep expertise that can propel business forward

McFadyen Solutions is headquartered in Vienna Virginia, with offices in Dallas Texas and Florianopolis Brazil. We have offshore Development Centers located in Trivandrum, Bangalore, and Cochin India. 

## Como se candidatar

Por favor cadastre o seu currículo no link: 
http://smrtr.io/rXZJKA

## Labels

- Estágio
- Júnior
- PJ

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
