### ISSUE TITLE
[100% REMOTO] Front-end Developer React na FDTE

### ISSUE THREAD

**Issue by VanessaBruno3** [frontendbr/vagas#7892]
Nossa empresa

Dê uma olhada no nosso Site: http://www.fdte.org.br/
a Fundação é com foco em engenharia - ligada a Poli-USP
o nosso escritório tem o foco em engenharia de software, com modelo de fabrica de software

**Desenvolver código de qualidade usando React.JS
Necessário ter idioma Inglês fluente (TODO O PROCESSO SERÁ NO IDIOMA INGLÊS)**

Contratação
PJ +

Vantagens
● 80hs em banco de horas, como descanso, após 1 ano de contrato
● Possibilidade de bônus ate 2x o valor de prestação de serviços (pois, depende de metas)
● Possibilidade de Bolsa MBA (parceria com a FIAP) - sorteio entre a equipe interessado no curso.
● Programa de terapia
● Incentivo financeiro mensal (em cartão de crédito corporativo) para desenvolvimento pessoal
compra de livros, cursos, certificações e participação de eventos da área de tecnologia.

Como se candidatar
Por favor, envie um e mail para [vanessa.bruno@fdte.io](mailto:vanessa.bruno@fdte.io) - com seu CV anexado - enviar no assunto: Vaga Frontend com inglês

Costumamos enviar feedbacks em até 7 dias após cada processo.

**Comment by guim0** [comment]
Enviado!

**Comment by shirator** [comment]
Junior?

**Comment by Felipe-Tomazetti** [comment]
Enviado!
