### ISSUE TITLE
[Remoto] Front-end Developer Angular +3XP @Mollica IT

### ISSUE THREAD

**Issue by raissaime** [frontendbr/vagas#7893]
## Nossa empresa

Vem com a Mollica IT e encontre a oportunidade certa pra dar match!

Estamos em busca de profissionais inovadores e criativos, que tenham paixão em crescer, evoluir e  aprender para cliente que é uma plataforma de marketing e vendas digitais que reúne estratégias, fluxos, recomendações e ações de interatividade com o consumidor final e tem como objetivo principal transformar o tráfego em conversões.

## Descrição da vaga

- Desenvolver e otimizar componentes da plataforma;
- Construir landing pages com automações de estratégias digitais;
- Aprimorar a experiência do usuário sobre o uso do produto e componentes de interação.

## Requisitos

**Obrigatórios:**
- Mínimo de 3 anos de experiência comprovada na área;
- Vivência com desenvolvimento utilizando Angular e JavaScript;
- Experiência em JQuery, HTML, CSS;
- Experiência em RESTful API.

**Desejáveis:**

- Ferramentas de Charts;
- Web Push Notification;
- E-mail marketing.

## Benefícios

✔️ Férias remuneradas
✔️ PLR

## Local

Remoto

## Contratação

PJ 

## Remuneração
R$ 45/h

## Como se candidatar
https://tally.so/r/3NXJ4G

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: raissaime@outlook.com

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipemimoura** [comment]
Enviado

**Comment by joao160197** [comment]
Enviado

**Comment by Eduardopereira11967484018** [comment]
https://eduardopereira11967484018.github.io/portifolio0-1/

**Comment by raissaime** [comment]
valeu @
