### ISSUE TITLE
[REMOTO] React Native Developer na Spatio

### ISSUE THREAD

**Issue by viniciusz42** [frontendbr/vagas#7894]
## Empresa

A Spatio é uma startup em estágio inicial mas com foco global no setor produtividade/saúde. Estamos à procura de um desenvolvedor pleno ou sênior para se juntar à nossa equipe em um papel de meio período. Valorizamos a excelência e, por isso, estamos interessados apenas em candidatos que demonstram um alto nível de execução ou que acreditam possuir essa capacidade. Disponibilidade para meio período de +-3 horas (manhã ou noite).

## Descrição da vaga

Estamos em busca de um desenvolvedor front-end com experiência em React Native. O candidato selecionado trabalhará em estreita colaboração para desenvolver um produto de alto nível.

## Requisitos

**Desejáveis:**
- Capacidade de pensamento crítico
- Código React sempre tipado
- Habilidade de trabalhar bem em equipe

**Diferenciais:**
- Experiência em projeto de healthtech
- Conhecimento backend NestJS

## Candidatar-se

Enviar email para vinicius@tryspatio.com

**Comment by guim0** [comment]
Seria todos os dias? tenho disponibilidade terça, quinta e sexta e os finais de semana.

**Comment by NTN1789** [comment]
não faz sentido um estágio pedindo nível de pleno é senior , seria bom abir essa oportunidade para júnior

**Comment by guim0** [comment]
> não faz sentido um estágio pedindo nível de pleno é senior , seria bom abir essa oportunidade para júnior , até iria candidatar , só que não to nível de pleno para sênior.

Concordo acima, faz sentido ser um dev Jr/Estagio, pra essa carga horária acho que achar um pleno/senior part-time é bem dificil, vai ser mais uma consultoria do que desenvolvimento.

**Comment by tascintra** [comment]
> não faz sentido um estágio pedindo nível de pleno é senior , seria bom abir essa oportunidade para júnior , até iria candidatar , só que não to nível de pleno para sênior.

Mas a vaga não é pra estágio. É trampo meio período.

**Comment by viniciusz42** [comment]
O label estágio foi adicionado automaticamente. Desculpe pela confusão. A vaga é meio período para pleno/senior.

**Comment by deyvisonborges** [comment]
Me chama no linkendin mano
https://www.linkedin.com/in/deyvisonborges/

**Comment by viniciusz42** [comment]
Vou fechar a postagem para poder atenção as pessoas que já enviaram cv (mas as posições ainda não foram fechadas)
