### ISSUE TITLE
[remoto] Desenvolvedor Fullstack PHP Pleno/Sênior - 

### ISSUE THREAD

**Issue by ecossistemadev** [frontendbr/vagas#7895]
## Descrição da vaga

Estamos em busca de um Desenvolvedor Fullstack PHP para se juntar à nossa equipe de talentos. Se você é um profissional apaixonado por programação, com vasta experiência em Laravel e um toque extra de criatividade, você pode ser o candidato ideal para essa oportunidade.

## Local

remoto

## Requisitos

- Experiência sólida em Laravel com Blade
- Desejável conhecimento em uma tech adicional de Front-end, como React.js, Angular, Wordpress.

**Atividades e responsabilidade:**

- Desenvolver aplicações web completas, tanto no lado do servidor (back-end) quanto no lado do cliente (front-end).
- Colaborar com a equipe de design e garantir a integração perfeita do design com o código.
- Otimizar o desempenho das aplicações e garantir a escalabilidade.
Manter-se atualizado com as melhores práticas de desenvolvimento web e tendências de tecnologia.
- Incentivar a criatividade e abordagens inovadoras na resolução de problemas.

## Benefícios

- Remuneração competitiva.
- Ambiente de trabalho dinâmico e desafiador.
- Oportunidades de aprendizado e desenvolvimento contínuo.
- Trabalho home office.

## Contratação

pj

## Como se candidatar

# [🔗 Clique aqui para se candidatar](https://empregos.dev/vaga/desenvolvedor-fullstack-php-pleno-senior-7479)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 60 dias após cada processo.
E-mail para contato em caso de não haver resposta: 

#### Regime

pj

#### Nível

pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
