### ISSUE TITLE
[Remoto] Front-end Javascript Developer na Coodesh

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#7897]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/desenvolvedor-frontend-stack-js-214052034?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Estamos  buscando Frontend Developer! Uma pessoa altamente habilidosa e apaixonada para integrar nossa equipe inovadora e ambiciosa.&nbsp;</p>
<p>Nesse papel, você será essencial para a criação de interfaces atraentes e funcionais que proporcionem a melhor experiência possível aos usuários. Além disso, terá a oportunidade de contribuir para futuras expansões, incluindo o desenvolvimento mobile.</p>
<p><strong>Responsabilidades:</strong></p>
<p>•	Colaborar com a equipe de design na implementação de interfaces de usuário atraentes e responsivas.</p>
<p>•	Desenvolver e otimizar componentes de front-end para garantir um desempenho excelente e uma experiência de usuário suave.</p>
<p>•	Utilizar a Stack JS (JavaScript, React, Redux) para construir interfaces interativas e dinâmicas.</p>
<p>•	Trabalhar em estreita colaboração com a equipe de back-end para integrar APIs e garantir a funcionalidade perfeita.</p>
<p>•	Participar da discussão e implementação de soluções técnicas para desafios complexos de front-end.</p>
<p>•	Contribuir para a evolução contínua da arquitetura de front-end, mantendo-se atualizado sobre as melhores práticas e tendências.</p>
<p>•	Colaborar com outros membros da equipe multidisciplinar para garantir uma abordagem coesa e integrada do desenvolvimento.</p>
<p></p>
## Cypher Financial IA: 
 <p>A Cypher Financial IA é uma empresa inovadora no campo das finanças e tecnologia. Nossa missão é capacitar investidores com soluções avançadas baseadas em Inteligência Artificial (IA) para otimizar decisões de investimento em mercados financeiros complexos. Combinamos a experiência em trading de criptomoedas com a inteligência de máquinas para criar estratégias eficazes que se adaptam dinamicamente às mudanças do mercado.</p>
<p>Nossa equipe multidisciplinar de desenvolvedores, traders quantitativos, cientistas de dados e especialistas em IA colabora para oferecer uma plataforma de negociação de alto desempenho. Utilizamos algoritmos de ponta e aprendizado de máquina para identificar oportunidades, avaliar riscos e executar transações com precisão, visando maximizar os retornos de nossos clientes.</p><a href='https://coodesh.com/companies/cypher-financial-ia'>Veja mais no site</a>

 ## Habilidades: 
 - Javascript 
- React.js 
- Node.js 
- Redux 
- HTML 5 
- CSS 3 
- GIT
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência sólida em desenvolvimento front-end, com foco em tecnologias da Stack JS (JavaScript, React, Redux). 
- Portfólio que demonstre a capacidade de criar interfaces atraentes e interativas. 
- Conhecimento de HTML5, CSS3 e práticas modernas de design responsivo. 
- Familiaridade com controle de versionamento Git. 
- Familiaridade com metodologias ágeis de desenvolvimento. 
- Desejo de aprender e se manter atualizado sobre as últimas tendências em desenvolvimento front-end.
## Diferenciais: 
 - Experiência em Outros Frameworks Front-end 
- Experiência em Testes Automatizados 
- Desenvolvimento Mobile Avançado 
- Experiência em Design de Interfaces

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Front-end Javascript Developer na Cypher Financial IA](https://coodesh.com/jobs/desenvolvedor-frontend-stack-js-214052034?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by Felipe-Tomazetti** [comment]
Aplicado, @FrancieleGhizzoni !

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
