### ISSUE TITLE
[REMOTO] Front-end Developer Senior na Zallpy Digital

### ISSUE THREAD

**Issue by Simineia** [frontendbr/vagas#7898]
## Nossa empresa

Transformar o futuro de pessoas e empresas com inovação e soluções digitais: esse é o nosso propósito.

Suprimos as necessidades de desenvolvimento de produtos digitais customizados e com alto valor agregado, inovando em processos, ferramentas e conceitos.

Aliamos tecnologias de alto desempenho e atuais no mercado com a expertise de uma equipe multidisciplinar formada por especialistas no segmento.

Com inovação, a Zallpy Digital traz pra o mercado um espaço de trabalho único onde os times sentem-se à vontade para entregar o seu melhor.

Você realizará constantemente a construção e melhoria de um produto, portanto viverá na prática todas as etapas do ciclo de desenvolvimento de um novo produto. Para isso é necessário que você tenha muita iniciativa, vontade de aprender e ensinar.

Valorizamos o trabalho em equipe, as interações humanas e prezamos pela nossa autonomia como time e como produto. 

Se identificou? Queremos te conhecer!

Aproveite para conhecer melhor a Zallpy Digital clicando aqui 👉 https://zallpy.com/ 😉

## Descrição da vaga

Projeto em core financeiro FRONT END SENIOR

## Local

[REMOTO]

## Requisitos

**Obrigatórios:** +  de 4 anos
•	Experiência com HTML5, CSS3, TypeScript: 
•	Ter atua no desenvolvimento Web:
•	Experiência com ReacJS:
•	Experiência com Redux:
•	Experiência com Redux Saga:
•	Experiência com Styled Components:

**Desejáveis:**
•	Conhecimento em testes unitários com Jest:
•	Conhecimentos em git flow:

## Contratação

PJ ou Cooperado a combinar

## Como se candidatar

Por favor envie um email para simeia.borba@zallpy.com com seu CV anexado - enviar no assunto: Vaga Front End GIT

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.
E-mail para contato em caso de não haver resposta: simeia.borba@zallpy.com

#### Alocação

- Remoto

#### Regime
- Cooperado
- PJ

#### Nível
- Sênior

**Comment by guim0** [comment]
Não me considero Sênior, mas tenho uma boa experiência para as stacks pedidas.

**Comment by sanvouza** [comment]
@guim0 Isso é relativo Gui, aplica assim mesmo!

**Comment by Dirosaki** [comment]
CV Enviado!

**Comment by devsnaked** [comment]
Enviado!

**Comment by Simineia** [comment]
Recebido CVs, vou encerrar aqui a vaga, mas na segunda sera feito a analise de todos!!! Obrigadaaa!
