### ISSUE TITLE
[REMOTO / PJ]  Full Stack Developer na SXPEL (Web Scraping) 

### ISSUE THREAD

**Issue by caiosalim** [frontendbr/vagas#7899]
## Nossa empresa

A Sxpel é uma consultoria de tecnologia e dados especializada em soluções para o setor de retail e eretail. Nosso compromisso é oferecer aos nossos clientes as informações e insights de que precisam para tomar decisões estratégicas baseadas em dados. Nossa equipe está em constante crescimento, e estamos em busca de um desenvolvedor full stack talentoso e apaixonado por web scraping para se juntar a nós. Se você é uma pessoa motivada, apaixonada por tecnologia e deseja trabalhar remotamente em projetos desafiadores, esta é a oportunidade perfeita para você!

## Descrição da vaga

Responsabilidades:

- Desenvolver e manter aplicações de web scraping para coleta de dados de diversas fontes na web, com foco em informações relevantes para o setor de retail e eretail.

- Projetar, implementar e otimizar APIs e serviços web para processar os dados coletados.

- Colaborar com a equipe para definir os requisitos e especificações dos projetos, adaptando as soluções de web scraping às necessidades específicas de nossos clientes.

- Solucionar problemas e otimizar os processos de web scraping, garantindo a qualidade e precisão dos dados coletados.

- Manter-se atualizado com as melhores práticas e tendências em desenvolvimento web e web scraping no contexto do varejo.

## Local

Exemplo: Full Remoto

## Requisitos

**Obrigatórios:**
- Experiência com web scraping

**Desejáveis:**
- Experiência em e-commerce

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para cs@sxpel.com.br com seu CV anexado - enviar no assunto: Vaga Web Scraping

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 01 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by tawsbob** [comment]
Sou especialista e scraping, podemos conversar?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
