### ISSUE TITLE
[Remoto] Desenvolvedor JavaScript (Node, Node+Angular, React ou JS puro)

### ISSUE THREAD

**Issue by talitapagani** [frontendbr/vagas#79]
## Descrição da vaga

A BairesDev me solicitou indicações de desenvolvedores JavaScript para trabalho remoto para clientes dos EUA. Eles estão buscando devs para as seguintes funções:
- Node Developer
- Node + Angular Developer
- React Developer
- HTML5 + Javascript Developer (no frameworks)

Em todos os casos, é necessário ter nível avançado de Inglês e ter pelo menos 4 anos de experiência com Javascript.

## Local

Trabalho Remoto.

## Benefícios

- Trabalho 100% remoto
- Ao fazer parte do banco da BairesDev, você poderá receber outras ofertas de trabalho, sempre remoto
- Ganhar em dólar

## Requisitos

**Obrigatórios:**
- Nível avançado de inglês
- Pelo menos 4 anos de experiência com JavaScript

**Diferenciais:**
- Ter projetos no Github

## Contratação

Contrato freelancer ou PJ, acredito.

## Nossa empresa

A BairesDev é uma empresa de serviços de tecnologia inovadora, que é especializada em Software Outsourcing, desenvolvimento de novos produtos, testes, projetos de manutenção e TI aumento de pessoal. Com equipes compostas pelos engenheiros mais talentosos do mercado, BairesDev auxilia as empresas em todo o mundo com soluções inovadoras de tecnologia.

## Como se candidatar

Envie um e-mail com currículo atualizado ou Github + sua disponibilidade para contato@talitapagani.com com o assunto: Vaga JS Developer - BairesDev

**Comment by gkal19** [comment]
Poxa vida! só faltava os 4 anos de experiência com JS e o conhecimento em React

**Comment by olegon** [comment]
Hehe! Vaga super interessante, mas como eu nunca trabalhei freela/remoto, fico com um pé atrás.

**Comment by lai32290** [comment]
SUPER interessante!
Preciso melhorar meu inglês, e 4 anos de experiencia

**Comment by LFeh** [comment]
Trabalho remoto :heart:

**Comment by diegoarcega** [comment]
Pedem pelo menos 6 meses com React.

**Comment by eduardojmatos** [comment]
@talitapagani sabe se já preencheu a vaga? Nos avise pra mantermos ou removermos da lista :)

**Comment by talitapagani** [comment]
@eduardojmatos Olha, o pessoal da BairesDev não me deu retorno se eles contrataram as indicações que encaminhei, mas como eles estão sempre procurando devs e me mandaram e-mails sobre novos projetos, pode fechar esse. Se precisar, abro issue nova :)

**Comment by LFeh** [comment]
Fechou!

**Comment by eduardojmatos** [comment]
@talitapagani 👍

**Comment by camilatigre** [comment]
@talitapagani 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
