### ISSUE TITLE
[Florianópolis] Junior UI Developer na McFadyen Digital

### ISSUE THREAD

**Issue by phameister** [frontendbr/vagas#790]
## Descrição da vaga

**About You**

Are you an innovative person who can accelerate the growth of our nationally acclaimed project? Do you have a passion for technology and a flexible, creative approach to problem solving? Are you self-directed, confident, and able to work without requiring a great deal of structure or supervision? Are you highly self-motivated and having head full of ideas? If you answered yes to these questions, we want to talk to you.

**Position Summary**

We are looking for creative and dependable self-motivated professionals to join our team as a Junior UI Developer.

**Responsibilities**

• Create reusable and clean UI pattern framework that Application Developers can plug and play
• Handle customer expectations on challenging projects
• Adhere to code standards and ensure consistency
• Quickly convert wireframes into HTML front-end with optimal quality
• Team with our Application Developers to bridge the client side with server side code
• Ensure quality assurance on front-end code including HTML, CSS, and JavaScript
• Deliver consistency of the user interfaces across multiple platforms
• Provide production support for all implemented changes
• Work in a small, fast-paced, team-oriented environment
• Liaise closely with onsite counterparts in order to continue to drive product forward

## Local

Itacorubi, Florianópolis/SC

## Benefícios

- Plano de saúde
- Plano odontológico
- VR de R$ 20,00

## Requisitos

**Obrigatórios:**
• Proven experience in UI development and integration for web and mobile applications with at least 1 delivered project
• Applied experience of UI development principles
• Have a good understanding of the three pillars of front end development which are HTML, CSS and JavaScript
• Generate clean, semantic HTML and CSS
• Have exceptional proficiency in writing Vanilla JavaScript (no jQuery!) from scratch, understand MVC coding model and object oriented concepts
• Know the Responsive web and have a little bit of knowledge about current UX trends.
• Have practical exposure on frameworks and APIs such as jQuery, Backbone, Handlebar, AngularJS, LESS, and Bootstrap
• Ensure cross-browser and cross-device compatibility
• Believe take actions so that disabled and visually challenged users have a right to use the web as easily as everyone else
• Exposure on e-commerce platforms is preferred and strong experience in agile methodology is a plus

INGLÊS AVANÇADO É IMPRESCINDIVEL

## Contratação

CLT

## Nossa empresa

McFadyen Solutions has completed more than 300 large-scale IT implementations for a prestigious client list, including dozens of the Fortune 500. Our proficiencies include eCommerce, web content management, online relationship management (B2C, B2B, B2E), and ERP integration. Our unique approach of focusing on select software partnerships allows McFadyen’s consultants to immerse themselves in specific technologies, thus providing the deep expertise that can propel business forward

McFadyen Solutions is headquartered in Vienna Virginia, with offices in Dallas Texas and Florianopolis Brazil. We have offshore Development Centers located in Trivandrum, Bangalore, and Cochin India

## Como se candidatar

Por favor cadastre seu currículo no link: 
http://smrtr.io/ynTLJw

## Labels

- CLT
- Júnior
- Pleno

**Comment by ReactGirl** [comment]
Hi. 
I have a question.
You say you are looking for a Junior developer with proficient skills in Javascript without using of framework with Advanced English and then you list the following skills as needed: (jQuery, Backbone, Handlebar, AngularJS).

Are you sure this is a Junior level position? How much is the salary range for this?

**Comment by phameister** [comment]
100% sure it’s a Junior position ☺
We need someone who has at least one project delivered with Javascript. You do not need to have worked with all the frameworks, but at least one of them.
Advanced English is a requirement since our UI Lead is a foreign.

Let me know if you have any additional questions!












[MCFADYEN DIGITAL]<http://www.mcfadyen.com/>

PAULA  HAMEISTER
Global Staffing Manager
+55 48 3209 0792
phameister@mcfadyen.com<mailto:phameister@mcfadyen.com>
Rua Patricio Farias, No 55, Sala 702, Itacorubi, Florianopolis Santa Catarina
CEP: 88.034-132

[Facebook] <https://www.facebook.com/McFadyenDigital>   [LinkedIn] <https://www.linkedin.com/company/mcfadyen-solutions>   [Twitter] <https://twitter.com/mcfadyendigital>






www.mcfadyen.com<http://www.mcfadyen.com/>

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
