### ISSUE TITLE
[REMOTO / PJ] Full Stack Developer VTEX - SXPEL

### ISSUE THREAD

**Issue by caiosalim** [frontendbr/vagas#7900]
## Nossa empresa

A Sxpel é uma consultoria de tecnologia especializada em soluções para o setor de retail e eretail. Nossa missão é fornecer soluções tecnológicas de ponta para impulsionar o sucesso de nossos clientes. Nossa equipe está em constante crescimento, e estamos procurando um desenvolvedor full stack talentoso e dedicado, com experiência na plataforma VTEX, para se juntar a nós. Se você é apaixonado por tecnologia, deseja trabalhar remotamente e está pronto para enfrentar desafios emocionantes, esta é a oportunidade perfeita para você!

## Descrição da vaga

Responsabilidades:

- Desenvolver, manter e aprimorar aplicações e sistemas na plataforma VTEX, garantindo alto desempenho, escalabilidade e confiabilidade.

- Colaborar com nossa equipe para definir os requisitos e especificações dos projetos, adaptando soluções VTEX às necessidades específicas de nossos clientes.

- Integrar sistemas e aplicativos de terceiros com a plataforma VTEX.

- Solucionar problemas técnicos, otimizar a experiência do cliente e garantir a conformidade com as melhores práticas da plataforma.

- Manter-se atualizado com as últimas atualizações e recursos da VTEX, além de compartilhar conhecimentos com a equipe.

## Local

Exemplo: Full Remoto

## Requisitos

**Obrigatórios:**
- Experiência com VTEX
- Uso de APIs VTEX

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para cs@sxpel.com.br com seu CV anexado - enviar no assunto: Vaga Web Scraping

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 01 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
