### ISSUE TITLE
[Remoto] Front-end Developer na CredAluga

### ISSUE THREAD

**Issue by andretrevas** [frontendbr/vagas#7904]
## Descrição da vaga

https://www.linkedin.com/jobs/view/3740472346

Buscamos uma pessoa Desenvolvedora Front-End pleno para compor nosso time de Tecnologia, motivada por resolver problemas complexos, e apaixonada pela construção e desenvolvimentos de produtos digitais, com 3 anos experiência em ambiente de desenvolvimento de software moderno.

Valorizamos a experiência prévia na modernização de interfaces, componentes e evolução da arquitetura de software para microsserviços. Seu papel será fundamental na evolução da interface dos produtos, uso de frameworks modernos e garantir melhor experiência de interface para nossos produtos.

## Local

100% Remoto
Diferencial para região de Belo Horizonte

## Requisitos

**Obrigatórios:**
- Experiência em HTML, CSS, Javascript, biblioteca React e framework Next.js.
- Experiência prévia em projetos de migração para arquitetura de microsserviços ou arquitetura de API RESTful, onde o Front-End interage com microsserviços por meio de APIs.
- Familiaridade com ferramentas de automação de desenvolvimento e gerenciamento de dependências, como Webpack, npm ou Yarn.
- Forte compreensão de design responsivo e princípios de usabilidade.
- Capacidade de trabalhar de forma colaborativa em equipes multidisciplinares e comunicar de maneira eficaz.
- Atitude proativa e paixão por enfrentar desafios em projetos de modernização.
- Experiência em práticas ágeis de desenvolvimento de software.
- Experiência com Redux ou Context API
- Experiência com styled components ou frameworks como tailwind.
- 
**Desejáveis:**
- Experiência com Server-Side Rendering (SSR), Static Site Generation (SSG), Incremental Static Regeneration (ISR)
- Experiência com Redux ou React Context API
- Experiência com componentes funcionais

## Benefícios

- Conhecimento como desenvolvedor Front-End, em ambiente com ênfase em C# e .NET.
- Conhecimento em Azure boards, XD ou Figma.
- Conhecimento em React Native
- Certificações relevantes em desenvolvimento são bem-vindas.

**Beneficios:**
- Modelo de trabalho: Remoto
- Salário competitivo CLT ou PJ
- Plano de benefícios (seguro de saúde, VR, VA e VT)
- Oportunidades de crescimento e desenvolvimento profissional
- Ambiente de trabalho colaborativo e inovador
- Flexibilidade de horário
- Outros benefícios adicionais

## Contratação

Preferencialmente PJ com opção de PF

## Como se candidatar

https://www.linkedin.com/jobs/view/3740472346

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by gabriel-brunetti** [comment]
candidatura enviada!

**Comment by ANDREHORMAN1994** [comment]
Candidatura feita ✅

**Comment by joao160197** [comment]
Enviado

**Comment by davialcantaraa** [comment]
Enviado!
