### ISSUE TITLE
[Remote] Front-end Developer na Transfeera

### ISSUE THREAD

**Issue by MartinaCarvalho** [frontendbr/vagas#7906]
## Nossa empresa

A Transfeera nasceu em 2017 com o objetivo de simplificar a relação das empresas com a rotina de pagamentos, que por muitos anos foi complicada. Através da escuta ativa dos nossos clientes e acompanhamento dos avanços tecnológicos do setor, trabalhamos para ser a melhor e mais segura ponte entre as empresas e a infraestrutura de pagamentos.

Desde então, participamos de diversos programas de capacitação e aceleração. Em 2020, recebemos um aporte de R$3 milhões liderado pelo Goodz Capital, com a participação da Bossanova Investimentos, Honey Island e Curitiba Angels. Recentemente, anunciamos uma nova captação de R$7 milhões liderada pela Honey Island e 4UM Investimentos.

Fomos eleitos startup revelação pelo Startup Awards da ABStartups, principal premiação do setor no Brasil. Isso é um pouco da nossa história e mostra que nosso sonho é grande e vem sendo construído com o apoio de muitas mãos.

Se você acredita que construir pontes entre os que precisam de uma solução e os que oferecem o melhor produto é o caminho para revolucionar o mercado financeiro e construir um futuro sem burocracias e letras miúdas, então você também é Transfeera. Vem com a gente? 🚀

## Descrição da vaga

- Participar ativamente na criação de novas interfaces junto com o time de Engenharia, Produto, Design e dar vida a elas;
- Participar ativamente na criação de novos componentes e manutenção do Design System;
- Defender e promover práticas de desenvolvimento de software modernas e ágeis e ajudar a desenvolver e divulgar boas práticas organizacionais e de engenharia;
- Colaborar com uma cultura de engenharia saudável em linha com os valores e propósitos da Transfeera;
- Interagir diariamente com seus colegas de trabalho para avaliar as melhores soluções com ótica no negócio e na tecnologia;
- Desenvolver códigos: estáveis, confiáveis, elegantes e, não menos importante, fáceis de manter;
- Desenvolver soluções sempre pensando em segurança, eficiência, escalabilidade, disponibilidade, performance e estabilidade. Queremos garantir nosso crescimento super acelerado com um software escalável de maneira econômica (do more with less);
- "Be Accountable", ser responsável pela entrega, garantir cobertura de testes automatizados.

## Local

Remoto ou presencial (Joinville)

## Requisitos

- Experiência consolidada como desenvolvedor front-end;
- Experiência de trabalho comprovada em ambientes de desenvolvimento ágil;
- Bons conhecimentos em JavaScript, CSS e HTML. Conhecimento geral de design patterns, testes integrados e noções de arquiteturas back-end e API's;
- Perfil hands on, que esteja ativamente codificando e que gosta de problemas complexos;
- Compreender que entender do negócio é igualmente importante quanto entender de tecnologia e que grandes resultados vêm por meio de pessoas e excelente tecnologia;
- Construir recursos que proporcionem uma experiência excelente, segura e confiável, para os seus parceiros internos e para os clientes da Transfeera.
- Uma pessoa apaixonada por interfaces e experiência do usuário, com domínio das tecnologias web e frameworks.

## Benefícios
🍽️Cartão flex CAJU (refeição ou alimentação): R$ 40,00 por dia útil;
👩🏻‍⚕️Plano de saúde Bradesco Top Nacional Enfermaria sem coparticipação e sem desconto¹ em folha;
🌻Zenklub para atendimento com psicólogos, psicanalistas, terapeutas, coaches e nutricionais com duas sessões mensais subsidiadas pela empresa;
🦷Plano dental Bradesco sem desconto² em folha;
💚Seguro de vida pessoal e familiar sem desconto em folha;
🤸‍♂️Gympass;
🎮Bonificação baseada nos objetivos da empresa alcançados;
🏡Auxílio Home Office: R$ 100,00;
🎊Day off de aniversário;
🌎Flexibilidade para trabalhar em home office ou no escritório que fica em Joinville, no Ágora Tech Park;
🔆Horário de trabalho flexível;
🏙️WOBA – nossos parceiros para que você possa trabalhar uma vez por semana em um espaço diferente. São mais de 1600 espaços de trabalho em 240 cidades diferentes; e
🎒Subsídio de incentivo aos estudos e desenvolvimento:
Até 50% da mensalidade da pós ou graduação: com teto de reembolso em R$ 350,00
Até 70% da mensalidade de idioma: com teto de reembolso em R$ 250,00.
🧸Auxílio creche: Elegível para pai ou mãe com filhos de até 6 anos, regularmente matriculados em escola ou creche particular, no valor de R$500,00.

## Contratação

CLT

## Como se candidatar

https://bit.ly/TransfeeraFrontEndPleno

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by rafaelst2000** [comment]
Enviado!

**Comment by SilasRodrigues19** [comment]
Enviado

**Comment by juliovt-07** [comment]
Enviado!

**Comment by ANDREHORMAN1994** [comment]
Candidatura feita ✅

**Comment by joao160197** [comment]
Enviado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
