### ISSUE TITLE
[Remoto ou Híbrido em BH] Angular Developer Sr @Rhitmo Tech

### ISSUE THREAD

**Issue by gabirecruiter** [frontendbr/vagas#7907]
Somos a **RHITMO TECH** e aqui conectamos criatividade e tecnologia, gerando soluções seguras e exponenciais. Um time que está sempre pronto para decolar e é capaz de criar e desenvolver projetos que mudam positivamente a vida das pessoas, solucionando problemas e transpondo obstáculos. 💙

Estamos em busca de um(a) Desenvolvedor(a) Angular Sênior para se juntar à nossa equipe de Tecnologia. Se você possui experiência sólida em desenvolvimento ANGULAR e está ansioso(a) para contribuir em projetos desafiadores, esta oportunidade pode ser perfeita para você.

## Responsabilidades: 

- Buscar novas ferramentas e técnicas para a melhoria contínua de nossas soluções;
- Desenvolver e sustentar integrações;
- Realizar a manutenção e criação de novas funcionalidades;
- Aplicar melhores práticas no código desenvolvido.

## Requisitos:

- Experiência sólida no desenvolvimento com Angular;
- Conhecimento avançado em HTML, CSS e JavaScript;
- Experiência com sistemas de controle de versão, como Git;
- Capacidade de escrever código limpo, legível e escalável;
- **Será considerado um diferencial ter atuado com outras tecnologias**. 

## Sobre a vaga: 

- Modelo de contratação: PJ
- Senioridade: Sênior
- Remoto ou Híbrido em Belo Horizonte
- Interrupção remunerada de 15 dias (férias)
- Bonificação por indicação de desenvolvedor.

## Como se candidatar? 

Envie o seu currículo + pretensão salarial para o e-mail: rh@rhitmo.com.br 📧 

Pode se conectar comigo no LinkedIn também: https://www.linkedin.com/in/mariagabrielacs/ 👩‍💻

**#VEMPRARHITMO!** 🚀👩‍🚀

**Comment by Scohati** [comment]
Boa tarde! Candidatura enviada.
