### ISSUE TITLE
Chapecó/SC -  Developer Front-end/Back-end na Mhnet Telecom

### ISSUE THREAD

**Issue by mhnet-rh** [frontendbr/vagas#7908]
## Nossa empresa

Somos uma das maiores empresas de telecomunicações no Sul do país, presente em 5 estados brasileiros, atendemos a + de 300 cidades e 320 mil clientes. Se você também é apaixonado por tecnologia e inovação essa é sua chance para ser Front-end Developer em Chapecó/SC.

## Descrição da vaga
- Desenvolver e manter aplicações usando as tecnologias e linguagens: PostgreSQL, JavaScript, HTML e CSS, React.js, Next.js e Node.js, PHP;
- Colaborar com a equipe de desenvolvimento para criar soluções eficazes e eficientes;
- Garantir a qualidade do código, incluindo testes e revisões de código;
- Solucionar problemas e otimizar o desempenho das aplicações;
- Fornecer suporte técnico quando necessário.

## Local

- Chapecó/SC

## Requisitos

- Ensino superior completo em Tecnologia da Informação ou áreas afins;
- Familiaridade com o uso do npm (Node Package Manager) para gerenciamento de pacotes JavaScript.
- Conhecimento em WebSockets;
- Experiência em lidar com requisições GET e POST;
- Habilidade para trabalhar com APIs externas;
- Experiência em desenvolvimento Frontend responsivo;
- Competência em Docker para a criação e gerenciamento de containers.
- Habilidade em scripting com Bash e/ou Python3.
- Domínio do terminal para uso diário.

## Benefícios

- Seguro de vida
- VA de R$ 23,00/dia
- Auxílio estudo
- Sala de jogos

## Outras informações

- Horário: 08:00 as 12:00 das 13:12 as 18:00

## Contratação

- CLT

## Como se candidatar

Por favor encaminhe um e-mail para vagas@mhnet.com.br com seu CV anexado - enviar no assunto: Front-end Developer ou cadastre-se pelo nosso site: https://www.mhnet.com.br/trabalhe-conosco 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

## Labels

- Alocado
- CLT
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
