### ISSUE TITLE
[SC - florianópolis] Desenvolvedor Front End JR - 

### ISSUE THREAD

**Issue by ecossistemadev** [frontendbr/vagas#7909]
## Descrição da vaga

Você é um entusiasta da programação, apaixonado por criar interfaces incríveis? Esta oportunidade é para você! 👨‍💻

Sobre Nós:
- Somos uma empresa inovadora, comprometida em oferecer um ambiente de trabalho dinâmico e oportunidades reais de crescimento. Aqui, você terá a chance de aprimorar suas habilidades e fazer parte de projetos desafiadores.

## Local

SC - florianópolis

## Requisitos

- Experiência prática em desenvolvimento com Flutter e a criação de interfaces de usuário nativas para aplicativos móveis.
- Habilidade comprovada na criação de layouts atraentes e componentes interativos usando os widgets do Flutter.
- Familiaridade com boas práticas de codificação, incluindo modularização e organização do código.
- Capacidade de trabalhar eficazmente em equipe e comunicar ideias de forma clara.
- Disposição para aprender e se manter atualizado com as últimas tendências em desenvolvimento Flutter.
- Foco em resolução de problemas e abordagens criativas para desafios técnicos.

**Mais Informações:**

Presencial - Bairro Trindade - Florianópolis/SC;

## Benefícios

💳 Cartão CAJU (benefício flexível) R$500,00 mensal
🏥 Plano de saúde Bradesco (copart 50%) e odontológico
💪 Convênio GoGood (desconto em academias)
🎉 DayOff no mês de aniversário e premiação no CAJU de R$50,00
📈 Plano de cargos e salários com possibilidade de crescimento

## Contratação

clt

## Como se candidatar

# [🔗 Clique aqui para se candidatar](https://empregos.dev/vaga/desenvolvedor-front-end-jr-em-florianopolis-sc-4018)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 60 dias após cada processo.
E-mail para contato em caso de não haver resposta: 

#### Regime

clt

#### Nível

junior

**Comment by joao160197** [comment]
Candidatura realizada

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
