### ISSUE TITLE
[Remoto] React Developer Pleno - Projeto no UK na Coodesh

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#7911]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/react-developer-pleno-projeto-no-uk-214017033?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A Criasol está buscando  <strong>React Developer</strong>  Plenos para atuar em um de nossos projetos no Reino Unido.</p>
<p></p>
<p><strong>INGLÊS FLUENTE É REQUISITO</strong></p>
<p>Tipo de contratação: PJ internacional via nosso escritório Europeu</p>
<p>Valor: <strong>€2.000,00 a €2.500,00</strong></p>
<p>Dedicação: Integral</p>
<p>Timezone: GMT-0 (UK)</p>
<p></p>
<p><strong>Etapas do Processo:</strong></p>
<ol>
<li>Avaliação de perfis&nbsp;</li>
<li>Teste técnico</li>
<li>Entrevista técnica em inglês</li>
<li>Teste técnico em inglês</li>
</ol>
<p></p>
<p><strong>Requisitos:</strong></p>
<ul>
<li><br></li>
</ul>
<p><strong>Qualificações:</strong></p>
<ul>
<li></li>
</ul>
## Criasol: 
 <p>Desde 2006, temos impulsionado produtos digitais com base no nosso profundo conhecimento em tecnologias e recursos online, auxiliando as empresas a navegar e implementar iniciativas de transformação digital de maneira altamente eficaz.&nbsp;</p>
<p>Trabalhamos em estreita parceria com as organizações para compreender suas metas empresariais específicas, desafios e oportunidades. Através do desenvolvimento de aplicações web e mobile, desenvolvemos e executamos estratégias personalizadas de transformação digital, empregando uma variedade de tecnologias, ferramentas e metodologias ágeis para estimular a mudança e a inovação organizacional.</p>

 ## Habilidades: 
 - React.js 
- Typescript 
- CSS 3 
- HTML
## Local: 
 100% Remoto
## Requisitos: 
 - Inglês fluente 
- Ter idade superior a 25 anos 
- Estar trabalhando com React.js nos últimos 3 anos 
- React.js e seu Ecossistema: Profundo conhecimento da biblioteca React.js, incluindo componentização, ciclo de vida dos componentes, uso de props e state, manipulação de eventos, uso de hooks, context API, entre outros. Além disso, familiaridade com ferramentas e bibliotecas associadas, como React Router para navegação e Redux ou Context API para gerenciamento de estado global. 
- TypeScript e ES6+: Domínio sólido de TypeScript é essencial, incluindo conceitos avançados da versão ES6 e posteriores, como arrow functions, classes, destructuring, async/await, e outras funcionalidades modernas da linguagem. 
- CSSFrameworks: Competência em HTML e CSS para criação de interfaces e layout responsivo. Compreensão dos princípios de design responsivo e práticas para garantir uma boa experiência do usuário em diferentes dispositivos e tamanhos de tela. 
- APIs e Requisições Assíncronas: Experiência em integração com APIs, compreensão de requisições assíncronas e gestão de dados obtidos de servidores externos usando ferramentas como Fetch API ou Axios. 
- Testes e Depuração: Conhecimento em testes unitários, utilizando frameworks como Jest, testes end 2 end e ferramentas de depuração para identificar e solucionar problemas. 
- Deploy de aplicações 
- Graduação em ciência da computação ou afins
## Diferenciais: 
 - Desejável conhecimento em Next.js 
- Desejável certificação em inglês.
## Benefícios: 
 - Férias
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [React Developer Pleno - Projeto no UK na Criasol](https://coodesh.com/jobs/react-developer-pleno-projeto-no-uk-214017033?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by FrancieleGhizzoni** [comment]
Bom dia Guilherme, tudo bem?

Para essa vaga é a própria empresa que está conduzindo o processo, mas eu
vou pontuar esses pontos com o pessoal.

Desejo boa sorte

Abraço


Franciele Ghizzoni - Head de Recrutamento e Retenção Tech
2023, Coodesh
+55 (49) 99995-2308
https://coodesh.com
***@***.*** <http://coodesh.com/>


Em qua., 1 de nov. de 2023 às 10:00, Guilherme Moraes <
***@***.***> escreveu:

**Comment by ANDREHORMAN1994** [comment]
Candidatura feita ✅

**Comment by LuizHAP** [comment]
Vaga se encontra em Hold no link informado @moderacaofrontendbr

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
