### ISSUE TITLE
[Remoto] Frontend Mobile Developer na Coodesh

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#7912]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/analista-de-sistemas-mobile-front-113516621?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Somos pioneiros no setor da tecnologia em Florianópolis e nos orgulhamos muito disso. Há 45 anos transformamos o mundo por meio da tecnologia, inovando e valorizando os verdadeiros protagonistas: o colaborador. Quer fazer parte de uma equipe engajada e que faz a diferença? Vem para a Dígitro!</p>
<p>Você integrará o time de Comunicação Corporativa, atuando no desenvolvimento dos produtos de Comunicação Unificada, utilizando as tecnologias mais atuais no desenvolvimento de sistemas, combinadas às metodologias ágeis. O UNA é uma ferramenta de comunicação unificada em nuvem que possibilita que as equipes troquem informações por meio de voz, vídeo e mensagens de texto!</p>
<p><strong>Responsabilidades:</strong></p>
<ul>
<li>Analisar, especificar e desenvolver novas funcionalidades de software para o produto;</li>
<li>Pesquisar e definir novas tecnologias para atender aos requisitos de projeto;</li>
<li>Liderar tecnicamente desenvolvedores menos experientes;</li>
<li>Utilizar boas práticas de desenvolvimento;</li>
<li>Garantir a qualidade das entregas através de testes automatizados, entre outras práticas.</li>
</ul>
<p></p>
<p><strong>O que esperamos de você:</strong></p>
<p></p>
## Dígitro Tecnologia: 
 <p>Há mais de quatro décadas contribuímos para a construção de uma sociedade mais segura, transparente e conectada. E nos orgulhamos muito disso. Transformamos o mundo por meio da tecnologia. Um mundo melhor. Um mundo conectado, mais seguro e transparente. Somos pioneiros no cenário da tecnologia em Florianópolis, uma capital com muitos encantos naturais, em constante crescimento e reconhecida nacionalmente como polo tecnológico. A Dígitro nasceu como uma startup e hoje é uma empresa com mais de 300 colaboradores, 1.200 clientes e com atuação em todo o Brasil e América Latina.</p>
<p>Ao longo da nossa história, inovamos, crescemos e evoluímos. Nosso portfólio de soluções sempre foi adequado e atualizado para atender o mercado em suas necessidades atuais e futuras. Para empresas da administração pública, somos especializados em segurança e defesa, com um amplo portfólio de soluções de monitoramento, gestão e inteligência investigativa. Em virtude do nosso know-how e qualidade da entrega de soluções, somos reconhecidos pelo Ministério Brasileiro de Defesa como Empresa Estratégica de Defesa (EED). Para o mercado corporativo, entregamos soluções de comunicação corporativa, sejam elas para uso interno ou para atendimento a clientes. Empresas de tecnologia há muitas. Mas o que nos diferencia é o nosso porquê.</p><a href='https://coodesh.com/companies/digitro-tecnologia'>Veja mais no site</a>

 ## Habilidades: 
 - Android 
- Javascript 
- HTML 
- CSS 
- Node.js 
- React Native 
- Automação de Testes
## Local: 
 100% Remoto
## Requisitos: 
 - Javascript 
- HTML 
- CSS 
- React Native 
- Node.js 
- Trabalho em equipe; 
- Estar sempre se atualizando tecnicamente; 
- Formação superior em Ciências da Computação, Sistemas de Informação, ou áreas afins; 
- Experiência com desenvolvimento mobile iOS e/ou Android; 
- Experiência com desenvolvimento em Javascript, HTML, CSS, node.js, React-native e testes automatizados.

## Benefícios: 
 - Vale alimentação 
- Vale refeição 
- Plano de saúde 
- Plano odontológico 
- Convênio com instituições de ensino 
- Programa de indicação de talentosau 
- Auxílio home office
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Mobile Developer na Dígitro Tecnologia](https://coodesh.com/jobs/analista-de-sistemas-mobile-front-113516621?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
