### ISSUE TITLE
[Remoto] Mobile Javascript Frontend na Coodesh

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#7913]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/analista-de-sistemas-mobile-front-javascript-112714746?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Somos pioneiros no setor da tecnologia em Florianópolis e nos orgulhamos muito disso. Há 45 anos transformamos o mundo por meio da tecnologia, inovando e valorizando os verdadeiros protagonistas: o colaborador. Quer fazer parte de uma equipe engajada e que faz a diferença? Vem para a Dígitro!</p>
<p>Você atuará no time time de Comunicação Corporativa, integrando a equipe do NEO, uma solução que auxilia o cliente no gerenciamento dos contatos que recebe. O NeoInteract foi pensado como uma plataforma de Contact Center prática, simples e humanizada, funcionando diretamente no navegador.</p>
<p><strong>Reponsabilidades:</strong></p>
<ul>
<li>Analisar, especificar e desenvolver novas funcionalidades de software para o produto;</li>
<li>Pesquisar e definir novas tecnologias para atender aos requisitos de projeto;</li>
<li>Utilizar boas práticas de desenvolvimento;</li>
<li>Garantir a qualidade das entregas através de testes automatizados, entre outras práticas.</li>
</ul>
<p></p>
<p><strong>O que esperamos de você:</strong></p>
<p></p>
## Dígitro Tecnologia: 
 <p>Há mais de quatro décadas contribuímos para a construção de uma sociedade mais segura, transparente e conectada. E nos orgulhamos muito disso. Transformamos o mundo por meio da tecnologia. Um mundo melhor. Um mundo conectado, mais seguro e transparente. Somos pioneiros no cenário da tecnologia em Florianópolis, uma capital com muitos encantos naturais, em constante crescimento e reconhecida nacionalmente como polo tecnológico. A Dígitro nasceu como uma startup e hoje é uma empresa com mais de 300 colaboradores, 1.200 clientes e com atuação em todo o Brasil e América Latina.</p>
<p>Ao longo da nossa história, inovamos, crescemos e evoluímos. Nosso portfólio de soluções sempre foi adequado e atualizado para atender o mercado em suas necessidades atuais e futuras. Para empresas da administração pública, somos especializados em segurança e defesa, com um amplo portfólio de soluções de monitoramento, gestão e inteligência investigativa. Em virtude do nosso know-how e qualidade da entrega de soluções, somos reconhecidos pelo Ministério Brasileiro de Defesa como Empresa Estratégica de Defesa (EED). Para o mercado corporativo, entregamos soluções de comunicação corporativa, sejam elas para uso interno ou para atendimento a clientes. Empresas de tecnologia há muitas. Mas o que nos diferencia é o nosso porquê.</p><a href='https://coodesh.com/companies/digitro-tecnologia'>Veja mais no site</a>

 ## Habilidades: 
 - Javascript 
- HTML 
- CSS 
- Node.js
## Local: 
 100% Remoto
## Requisitos: 
 - Javascrpt 
- HTML 
- CSS 
- Node.js 
- React.js 
- Trabalho em equipe; 
- Estar sempre se atualizando tecnicamente; 
- Formação superior em Ciências da Computação, Sistemas de Informação, ou áreas afins; 
- Desenvolvimento mobile iOS e/ou Android 
- Experiência com desenvolvimento em Javascript, HTML, CSS, node.js, REACT e testes automatizados.

## Benefícios: 
 - Vale alimentação 
- Vale refeição 
- Auxilio Home office 
- Day-off de aniversário 
- Programa de educação continuada 
- Programa de indicação de talentos
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Mobile Javascript Frontend na Dígitro Tecnologia](https://coodesh.com/jobs/analista-de-sistemas-mobile-front-javascript-112714746?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
