### ISSUE TITLE
[Remoto] Front-End Developer Pleno na Agência Shakers

### ISSUE THREAD

**Issue by shakers-agencia** [frontendbr/vagas#7914]
> Vaga Remota durante a pandemia

## Nossa empresa

Somos uma agência com grande experiência no comércio varejista e indústria e trabalhamos no desenvolvimento de novas lojas ou na migração e sustentação de lojas já existentes para a plataforma **Shopify**. Seguimos padrões de usabilidade e extraímos o melhor que a plataforma nos oferece para atender todas as necessidades do cliente.

## Descrição da vaga

Estamos em busca de um talentoso e apaixonado Front-End  Developer para se juntar à nossa equipe, impulsionando o sucesso de nossos clientes através de experiências digitais excepcionais com aspirações para ser referência técnica no time de engenharia.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência comprovada de pelo menos 2 anos em desenvolvimento Front-End, demonstrando profundo conhecimento em HTML, CSS e JavaScript.
- Conhecimento de frameworks e bibliotecas Front-End, como React, Vue.js, Angular, etc.
- Familiaridade com práticas de design responsivo e mobile-first.
- Habilidade para transformar layouts em designs interativos, utilizando técnicas modernas e criativas.
- Capacidade de otimizar o desempenho das páginas para uma experiência de usuário excepcional.
- Experiência com Github.

**Desejáveis:**
- Conhecimento de SEO técnico e práticas de otimização.
- - Familiaridade com ferramentas de gestão de projetos como clickup, Jira, etc.
- Habilidades básicas de design para colaboração mais próxima com a equipe de design.

**Diferenciais:**
- Experiência prévia com a plataforma Shopify, incluindo a criação e customização de temas.
- Experiência com outras plataformas de e-commerce, além da Shopify.

## Benefícios

- Plano de saúde

**Diferenciais:**
- Agência em pleno crescimento com muitas oportunidades reais de crescimento e liderença (técnica ou de gestão).

## Contratação

CLT - R$ 7k

## Como se candidatar

Por favor envie um email para [rh@shakersagencia.com.br](mailto:rh@shakersagencia.com.br) com seu CV anexado - enviar no assunto: _[Remoto] Front-End Developer Pleno na Agência Shakers - Front-end Brasil_

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 4 dias úteis após cada processo.
E-mail para contato em caso de não haver resposta: evandro.guedes@shakersagencia.com.br

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by rafael-14** [comment]
Boa noite, provedor de e-mail está recusando o envio.

**Comment by rafael-14** [comment]
Boa noite, provedor está recusando o recebimento do e-mail. Tentei em ambos e-mails listados, há alguma outra forma de candidatura?

**Comment by Dirosaki** [comment]
CV Enviado!

**Comment by Mraimundo** [comment]
Currículo encaminhado!

**Comment by Felipe-Tomazetti** [comment]
Currículo enviado!

**Comment by MateusCapitanio** [comment]
Currículo encaminhado!

**Comment by Yagasaki7K** [comment]
Currículo enviado!

**Comment by davialcantaraa** [comment]
Enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
