### ISSUE TITLE
[PRESENCIAL] Application Support Analyst - Truppe

### ISSUE THREAD

**Issue by Camila-Goms** [frontendbr/vagas#7916]
## Nossa empresa

A [Truppe](https://truppe.team/) é uma empresa de consultoria de tecnologia com foco em desenvolver e aprimorar talentos referência em recrutamento, seleção e alocação de profissionais de TI. Criada há 4 anos, está em fase de desenvolvimento e crescimento, expandindo seu portfólio de produtos e serviços, trabalhando também com transformação e aceleração digital.

Sua missão é conectar os melhores profissionais às melhores oportunidades, proporcionando seu crescimento na carreira.

## Descrição da vaga

Buscamos uma pessoa para atuar como Application Support Analyst em uma empresa multinacional!

## Local

_Atuação:_ 100% Presencial (Vila Olímpia - SP).
_Horário:_ das 13h às 22h (horário de Brasília).

## Requisitos

_**Responsabilidades:**_
• Trabalhar ativamente com os membros da equipe para analisar e resolver problemas de aplicação;
• Identifique defeitos, discrepâncias e tendências por meio de depuração de código ou análise de log;
• Gerencie incidentes e comunique-se de forma eficaz com usuários, proprietários de aplicativos e partes interessadas seniores em todas as áreas;
• Melhorar a estabilidade e o desempenho dos aplicativos observando padrões, falhas e/ou problemas recorrentes e aconselhar os proprietários dos aplicativos sobre correções permanentes adequadas;
• Adotar diversas ferramentas desenvolvidas pela equipe de Engenharia do App Bank para automatizar falhas utilizando técnicas de aprendizado de máquina e notificar discrepâncias na saúde da produção e automação da restauração da saúde, com foco na medição contínua de riscos e custos;
• Identificar alertas/processos que podem ser automatizados e depois trabalhar com a equipe de Engenharia do App Bank para automatizá-los;
• Desafie a configuração de aplicativos existentes. processamento e sugerir diferentes maneiras de resolver problemas ou melhorar a estabilidade;
• Participar ativamente do processo de gerenciamento de mudanças com o objetivo de gerenciar riscos no ambiente de produção;
• Construir e melhorar run books para generalistas para minimizar erros operacionais e ganhar fungibilidade/eficiência;
• Desenvolver relatórios que forneçam estatísticas de tendências para rastrear e gerenciar a integridade do aplicativo e dar suporte ao desempenho do serviço;
• Disposto a aprender e solucionar problemas/apoiar tecnologias proprietárias não disponíveis no mercado. Nenhum conhecimento de tecnologias proprietárias é necessário antes da contratação.

_**Requisitos Obrigatórios:**_
**• Necessário inglês fluente para conversação com a equipe norte americana;
• Uma das seguintes linguagens de programação estruturada ou orientada a objetos: Java, C. C++, VB, .NET, ASP ou Angular etc;
• Uma das seguintes linguagens de script: Shell script, Peri, Java5cript ou Python etc;
• Um dos seguintes ambientes RDBMS: Sybase ASE/K), Oracle ou DB2.**
• Conceito de Ciência da Computação de Estruturas de Dados em casos de uso prático;
• Resolução de problemas em ambiente de desenvolvimento ou produção. incluindo experiência em observação de padrões, análise de causa raiz e sugestão de ideias para resolver problemas;
• Boas habilidades de comunicação com capacidade de articular os aspectos técnicos e funcionais de um problema de desenvolvimento/produção para ajudar a impulsionar soluções com equipes de desenvolvimento de aplicativos e partes interessadas seniores.

_**Diferencais:**_
• Experiência no setor de serviços financeiros;
• Experiência em soluções de Cluster Computing e Big Data: Spark, Hacloop, HDSF, XRS utilizando nuvem pública;
• Graduação em Ciência da Computação.

### Nível

- Pleno

## Contratação

- CLT, tempo indeterminado.
- Pretensão salarial.

## Como se candidatar

Envie um email para **camila.gomes@truppe.team** com seu **CV em inglês atualizado** anexado, link do **perfil do Linkedin (se tiver) e pretensão salarial CLT** no corpo do email.

_Enviar no assunto:_ **Vaga Application Support Analyst**

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
