### ISSUE TITLE
[SP/ Híbrido] FullStack .NET Developer na ITeam

### ISSUE THREAD

**Issue by ITeam-oportunidades** [frontendbr/vagas#7917]
> Atendimento Híbrido

## ITeam

Há mais de 15 anos presente no mercado, a ITeam oferece o comprometimento com o cliente.
Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 
Com uma equipe multidisciplinar, a ITeam proporciona uma área de Serviços Gerenciáveis como Projetos SAP, Fábrica de Software, Fábrica de Soluções e Sustentação. Neste modelo proporcionamos Sustentação, Melhorias e Desenvolvimentos de aplicação de forma integrada.

## Local

4 dias remoto, sendo 1x por semana presencial na Vila Olimpia – São Paulo/SP
Horário de trabalho: 8h00 ás 18h00 - Segunda a Sexta-feira.

## Requisitos

Experiência em projetos com .Net Framework, C#, ASP NET, .NET Core, WebForms, Web Services, Web API;
Versionamento TFS, GIT;
Conhecimento em FrontEnd: HTML, CSS, jQuery, Javascript, entre outros.
Experiência em sistemas monolíticos legados e arquitetura de microsserviços.
Conhecimento em Dapper ORM, e outros.
Vivência com metodologias ágeis. 
Banco de dados SQL Server.
Conhecimento desejável: Sistemas de varejo

## Atividades

O profissional vai atuar em projetos e demandas corretivas, evolutivas e migração de tecnologias. 

## Contratação

Tempo indeterminado - Longo prazo

## Como se candidatar

Por favor, envie um e-mail para viviane.pereira@iteam.inf.br com seu currículo anexado e pretensão de taxa/hora - enviar no assunto: FullStack.NET - Híbrido

## Labels

.NET
Scrum
GIT
TFS
Webforms
NETCore
Dapper
FrontEnd
SQL Server
Microsserviços

## Regime
PJ ou a combinar

## Nível
Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
