### ISSUE TITLE
[Porto Alegre] PRESENCIAL Front-end Developer Júnior ou Pleno na Ável Investimentos

### ISSUE THREAD

**Issue by thynBlaze** [frontendbr/vagas#7918]
## Nossa empresa

Fundada por 3 ex-sócios da XP, a Ável atingiu em seus primeiros 2 anos o selo de melhor escritório da região Sul, além de estar entre os 3 melhores escritórios de toda a rede XP. Com mais de R$10 Bilhões sob custódia, a Ável Investimentos é hoje o maior escritório digital da XP, assessorando remotamente investidores de qualquer lugar do mundo.

## Descrição da vaga

Você terá um papel fundamental em nossa equipe de desenvolvimento, contribuindo para a evolução do nosso software interno de acordo com as estratégias da empresa. Trabalhando em estreita colaboração com o time, você terá a oportunidade de criar ferramentas inovadoras, leaderboards, e uma variedade de soluções para aprimorar a experiência do usuário, eliminando inconsistências e elevando a qualidade do código.

## Local

Escritório localizado no bairro Moinhos de Vento em Porto Alegre, RS.

## Requisitos

**Obrigatórios:**
- Experiência comprovada como desenvolvedor Front-End;
- Sólida experiência com JavaScript (Vanilla e frameworks), HTML, CSS e frameworks modernos, principalmente React;
- Compreensão de controle de versão de código (GIT);
- Experiência com integração com APIs REST;
- Habilidade em integração de APIs e serviços de terceiros.

**Desejáveis:**
- Inglês
- Experiência com Node JS, MySQL, Python
- Conhecimento e/ou interesse no mercado financeiro

**Diferenciais:**
- Ensino técnico ou superior cursando/concluído dentro das áreas correlacionadas.
- Disponibilidade para trabalhar em tempo integral.
- Residir em Porto Alegre e Região ou ter disponibilidade para residir na cidade.

**Diferenciais:**
- Partnership
- Estrutura horizontal
- Crescimento rápido meritocrático
- Bonificação por metas

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para matheus.balke@avel.me com seu CV anexado - enviar no assunto: Vaga Front End Developer na Ável

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 4 dias após cada processo.
E-mail para contato em caso de não haver resposta: luca.zilio@avel.me

#### Alocação
- Presencial.

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

**Comment by MathMendesReis** [comment]
curriculo enviado.

**Comment by guilhermedinardi** [comment]
curriculo enviado!

**Comment by joao160197** [comment]
Enviei o currículo
