### ISSUE TITLE
[REMOTO] Front-end Developer na EliteCoders

### ISSUE THREAD

**Issue by railima** [frontendbr/vagas#7921]
## A empresa

Na Elite Coders Co., estamos dedicados a transformar ideias inovadoras em realidade por meio de soluções de software excepcionais. Nossa equipe, liderada por profissionais experientes, está comprometida com a excelência e inovação no setor de tecnologia.

## Descrição da vaga

Vaga para quem tem inglês avançado/fluente.

Estamos em busca de um Desenvolvedor Frontend talentoso e atento aos detalhes para se juntar à nossa equip. O candidato ideal deve ser capaz de transformar designs do Figma em sites responsivos, "pixel-perfect". Você trabalhará em estreita colaboração com nossas equipes de design e desenvolvimento para criar interfaces de usuário de alta qualidade que proporcionem experiências de usuário fluidas.

## Local

Remoto.

## Principais Responsabilidades

1. Converter designs do Figma em sites responsivos e funcionais, com foco na precisão pixel-perfect.
2. Garantir a compatibilidade entre navegadores e implementar princípios de design responsivo para dispositivos móveis.
3. Colaborar com a equipe de design para compreender e implementar a experiência de usuário desejada.
4. Otimizar aplicações para obter máxima velocidade e escalabilidade.
5. Manter e aprimorar a estética e funcionalidade do site.
6. Manter-se atualizado com as tendências emergentes em desenvolvimento frontend e ferramentas de design.

## Requisitos

1. APENAS CONTRATAÇÕES DIRETAS (ou seja, estamos contratando você, não quem você coloca para trabalhar).
2. **Excelentes habilidades de comunicação em inglês, tanto escritas quanto verbais.**
3. Experiência comprovada como Desenvolvedor Frontend ou função semelhante.
4. Proficiência sólida em HTML, CSS, JavaScript e frameworks modernos como React ou Vue.js.
5. Experiência com princípios de design responsivo e adaptativo.
6. Familiaridade com testes e depuração em navegadores.
7. Compreensão de todo o processo de desenvolvimento web (design, desenvolvimento e implementação).
8. Capacidade de trabalhar de forma independente e como parte de uma equipe.
9. Habilidades sólidas de resolução de problemas e atenção aos detalhes.

## Contratação

PJ a combinar, **salário em dólar**.

## Como se candidatar

Para se candidatar a esta posição, você deve ser uma CONTRATAÇÃO DIRETA. Por favor, envie seu currículo e uma breve apresentação destacando sua experiência relevante para [resumes@elitecoders.co](mailto:resumes@elitecoders.co). Inclua exemplos de sites que você desenvolveu, de preferência com links para seu trabalho. Apenas candidatos selecionados serão contatados para uma entrevista.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by guim0** [comment]
Não sou Sênior mas tenho vivência nas stacks pedidas, acabei de enviar minha candidatura.

**Comment by obrenoco** [comment]
Enviei agora minha candidatura em inglês, tudo bem @railima ?

**Comment by joao160197** [comment]
Enviado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
