### ISSUE TITLE
[Internacional e Remoto] Front-End Developer (React.js) na Turing

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#7923]
## Job description
A rapidly-growing company, leading the way in its industry, is seeking a Web Front-End Developer with a focus on React. The developer will be responsible for creating and implementing user interface components using React concepts. This company is at the forefront of its industry, leveraging technology to drive innovation and growth. This is an exceptional opportunity to join a dynamic team and contribute to the company's success.

 

## Job Responsibilities:

- Develop new user-facing features using React.js
- Build reusable components and front-end libraries for future use
- Translate designs and wireframes into high-quality code
- Optimize components for maximum performance across a vast array of web-capable devices and browsers
- Collaborate with the product team to design and launch new features
- Maintain up-to-date knowledge of the latest industry trends and advancements

## Job Requirements:

- 3 - 5 years of overall experience in the field
- Minimum of 4 years of experience in React
- Strong proficiency in JavaScript, including DOM manipulation and the JavaScript object model
- Familiarity with newer specifications of EcmaScript
- Experience with data structure libraries (e.g., Immutable.js)
- Knowledge of isomorphic React is a plus
- Must be fluent in English and have excellent communication skills

## Como se candidatar

[Clique aqui](https://bit.ly/3SC6O8Y) para se candidatar

**Importante:** Esta vaga está sendo publicada pela [Remotar](https://remotar.com.br/?utm_source=github) em nome da Turing, nosso cliente. Ao acessar, você será redireciona(a) para a plataforma da Turing, e todo o processo seletivo será diretamente com eles.

#### Alocação
- Remoto

#### Regime

- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
