### ISSUE TITLE
[Remoto] Front-end Engineer na Conecta Capital Humano

### ISSUE THREAD

**Issue by raissaime** [frontendbr/vagas#7924]
## Nossa empresa

A Conecta busca os melhores talentos para fit com o cliente.

## Descrição da vaga

Front-Engineer  Typescript e React;

## Responsabilidades
- Trabalhar diariamente em um time multifuncional com Engenheiros de Software, Designers e Product Owner para desenvolver e evoluir produtos UOL Host utilizando metodologias ágeis;
- Construir painéis administrativos responsivos, seguindo fielmente os layouts e especificações determinados pelo time de Designers;
- Evoluir nossa biblioteca de componentes baseada em React e documentada com Storybook;
- Integrar o front-end com serviços back-end;
- Desenvolver aplicações visando simplicidade, eficiência, manutenibilidade e reaproveitamento de código;
- Atuar em tecnologias designadas dentro do time, independente da linguagem de programação.
- Realizar review de código de outros desenvolvedores e dar feedback.
- Ser responsável pela qualidade dos sistemas definindo e executando testes (inclusive manuais) com uma visão de usuário final;
- Atuar em soluções de problemas e manutenção de sistemas existentes
- Participar da definição e implantação dos sistemas;
- Gerar documentação técnica.

## Local

Exemplo: Remoto ou Híbrido em São Paulo - Pinheiros.

## Requisitos

**Obrigatórios:**
- Desenvolvimento de aplicações front-end (React, Typescript, HTML, CSS);
- Desenvolvimento de testes automatizados (Jest, Cypress);
- Versionamento de código (GIT);
- Integração e evolução de APIs REST;

## Contratação

PJ a combinar

## Como se candidatar
[https://tally.so/r/nGR6LO](url)

#### Alocação
- Alocado
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by lucasaugustodeveloper** [comment]
@raissaime tem algum outra maneira de se candidata , o link aqui não está funcionando

**Comment by YuryRegis** [comment]
> @raissaime tem algum outra maneira de se candidata , o link aqui não está funcionando

Copia o link e cola no navegador, por algum motivo o redirecionamento está quebrando. Acabei de fazer minha inscrição aqui.

**Comment by Mraimundo** [comment]
Parece que o link não está funcionando, tentei copiar e colar em um outro navegador do  mesmo jeito não funciona.

**Comment by joao160197** [comment]
Link não funciona

**Comment by guim0** [comment]
# Copiem o link e cole em outra aba!

**Comment by joao160197** [comment]
Enviado
