### ISSUE TITLE
[Remoto] Front-end Developer - React +3XP @ Mollica IT

### ISSUE THREAD

**Issue by raissaime** [frontendbr/vagas#7925]
## Nossa empresa

Buscando projetos internacionais?

Então vem com a Mollica IT e encontre a oportunidade certa pra dar match!

Estamos em busca de profissionais inovadores e criativos, que tenham paixão em crescer, evoluir e  aprender.

## Descrição da vaga

- Atuar na correção de bugs e desenvolvimento de melhorias;

## Local

- Remoto ⛺ 

## Requisitos

**Obrigatórios:**
- Experiência em desenvolvimento frontend utilizando ReactJS;
- Experiência em JS (Typescript), HTML;
- CSS (SASS | Tailwind | StyledC. | Stitches)
- Conhecimentos em versionamento de código;
- Design Patterns;
- NextJS (Redux / Redux Saga);
- Banco de dados MongoDB;
- Node.js (Express);
- Git;
- **Obrigatório Ensino superior completo em áreas de tecnologia** 

🌎Idioma:
**- Inglês Avançado para conversação (Haverá etapa de entrevista no idioma).**

**Desejáveis:**
- Experiência em suporte a aplicações.

## Benefícios

✔️Assistência Médica para colaboradores e dependentes com abrangência nacional da Bradesco ou Unimed

✔️Assistência Odontológica com abrangência nacional

✔️Vale Refeição ou Vale Alimentação (a escolha do colaborador)

✔️Auxílio creche

✔️Seguro de Vida para associados e dependentes

✔️Gympass para associados e dependentes

✔️EAP (Employee Assistance Program) com os seguintes serviços: Assistência Financeira, Assistência Jurídica, Assistência Social, Assistência Psicológica (24 horas – 7 dias por semana).

✔️Descontos e tarifas diferenciadas junto a Universidades (Mackenzie, SENAC, FIA, FIAP e BBS Business School) e escola de idiomas (CNA, Cultura Inglesa, Wizard, CCAA, Indeed).

✔️Descontos em pacotes de tarifas e taxas diferenciadas para Bancos Itaú e Bradesco

✔️Opção de crédito consignado, com desconto diretamente no salário do colaborador

✔️Programa de reembolso de algumas certificações externas

✔️Treinamento: A TCS oferece plataforma de treinamento e desenvolvimento a distância e presencias, em soft skills, tecnologias e domínios em mais de 15.000 temas.

✔️Premiação por tempo de casa: A TCS premia associados por seu comprometimento e lealdade durante o período em que trabalhar na empresa (3, 5 e 10 anos e cada 5 anos posteriormente).

✔️Prêmio de indicação de novos colaboradores - recebendo um bônus para cada nova contratação.

✔️TCS Fit4life - Programa para incentivar a prática de exercício físico junto a seus associados, com agenda de treinamentos funcionais online.

✔️Experiência internacional: Dependendo de seus conhecimentos e das demandas do negócio você pode se candidatar a vagas no exterior (dentro e fora da América Latina).

✔️Entre outros;

## Contratação

- CLT 🤝 

## Como se candidatar
https://tally.so/r/wz7MV0

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.

## Sobre a empresa
A TCS combina experiência em tecnologia e inteligência de negócios para catalisar mudanças e entregar resultados.

O que nós fazemos? Como líderes globais em serviços de TI, soluções digitais e negócios, fazemos parcerias com clientes para simplificar, fortalecer e transformar, ajudando clientes a criar o futuro!

Somos uma das 5 principais empresas de tecnologia na Top 100 do mundo da Forbes, o maior grupo multinacional de negócios da Índia, com instalações de fabricação em mais de 40 países com presença operacional em 180 países. Suas operações são apoiadas por uma pilha de mais de 80 aplicativos SAP e mais de 1900 Aplicativos não SAP.

Oferecemos perspectiva de crescimento, e oportunidade de aprendizado e certificações. Desejamos construir a próxima geração de sistemas e fábricas que envolvem as mais recentes Tecnologias e migrando para a Nuvem nos próximos 2 anos. Possuímos desenvolvimento Agile, Devops e oportunidades em 60 países.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno

#### Remuneração
- R$ 5K - R$9K

**Comment by MathMendesReis** [comment]
Não sei se a vaga ta aberta ainda, mas mandei meu cv la no linkdlin.
