### ISSUE TITLE
[Remoto] Estágio Front-End com ReactJs/NextJs na Coodesh

### ISSUE THREAD

**Issue by MateusCoodesh** [frontendbr/vagas#7926]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/estagio-frontend-193643235?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Auxiliar na implementação de interfaces em ambiente front-end com ReactJs/NextJs;</p>
<p>Auxiliar na melhoria de conceitos visuais existentes;</p>
## Jet Soluções Web: 
 
</p>undefined</p>

 ## Habilidades: 
 - Tailwind CSS 
- React.js 
- Next.js 
- HTML 
- CSS 
- Javascript 
- Typescript
## Local: 
 100% Remoto
## Requisitos: 
 - Ser habituado com metodologias ágeis
## Diferenciais: 
 - Ui kit(MUI, Antd ...) 
- Capacidade de entender requisitos de negocio e traduzir em requisitos técnico 
- Clean code 
- Noções básicas de integração com api rest 
- Noções básicas de teste 
- Noções básicas de SOLID
## Benefícios: 
 - Horários Flexíveis
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Estágio Front-End com ReactJs/NextJs na Jet Soluções Web](https://coodesh.com/jobs/estagio-frontend-193643235?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
Estágio
#### Categoria
Front-End

**Comment by thalys93** [comment]
enviei minha candidatura lá no site!!

**Comment by fabiopdiogo** [comment]
Mandei minha candidatura!

**Comment by Eduardopereira11967484018** [comment]
me candidatado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
