### ISSUE TITLE
[Remota] Front-end Developer na Hepta Tecnologia

### ISSUE THREAD

**Issue by GitMateusBruno** [frontendbr/vagas#7927]
## Nossa empresa

A empresa contratante é a Hepta tecnologia, sediada em Brasília com 31 anos de atuação no mercado. Temos contratos com empresas privadas e órgãos públicos, em virtude disso aqui é um espaço amplo de crescimento e desenvolvimento profissional. O time é bastante colaborativo, na verdade colaboração faz parte do nosso valor 🚀

## Descrição da vaga

React, Next.js, Node.js, TDD, JavaScript ou TypeScript. 

## Local
Remoto

## Requisitos

**Obrigatórios:**
- 5 anos de experiência como DEV. (Necessário comprovar)
- Formação Superior completa em TI (Necessário comprovar)
- Certificação em: Professional Scrum Developer (PSD) ou Certified Scrum Developer (CSD) 

Para o perfil Sênior desejável mais uma em: PSM I, II ou III. Ou CSM; Ou SMC; Ou ASM. (P/ atuar como Scrum Master)

Caso você não possua, concedemos um prazo para adquirir. É importante ressaltar que a empresa não cobre os custos, apenas oferece a oportunidade de estender o prazo.

IMPORTANTE: 
A Hepta presta serviço p/ instituições federais, as exigências que você leu sobre comprovação de experiência, formação superior em TI e certificação são exigências do edital e nós precisamos cumprir.

## Benefícios

- Plano de saúde
- Plano odontologico
- VR ou VA R$ 22.59/dia
- Auxílio Home Office
- ...

## Contratação

CLT

## Como se candidatar

Por favor envie um e-mail para mateus.sousa@hepta.com.br com seu CV anexado - enviar no assunto: Vaga React

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até três dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by guim0** [comment]
Mandei minha candidatura com o Pleno.

**Comment by joao160197** [comment]
Enviado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
