### ISSUE TITLE
[Remoto] Frontend Developer Senior (Angular) - Vem pra @Datum

### ISSUE THREAD

**Issue by julianakraemer** [frontendbr/vagas#7928]
## Nossa empresa

A Datum é uma empresa GPTW (Great Place to Work) pelo terceiro ano seguido. Nossa sede fica em Porto Alegre/RS e recentemente chegamos no Canadá

## Descrição da vaga

Desenvolvedor front-end com foco em Angular, para atuar na criação de novas features, manutenção das funcionalidades e correções de bugs do site de um cliente da área financeira
O profissional deve ser capaz de propor novas soluções e tecnologias que visem a melhoria e otimização dos sistemas web mantidos pela tribo. 
Diferencial experiência fullstack;

## Local

 Remoto

## Requisitos

Experiência com desenvolvimento front-end utilizando Angular, Vanilla Javascript (ES5, 6, 7, Design Patterns), Typescript; HTML5, CSS e outros pré-processadores;
Experiência com testes unitários e arquitetura de microsserviços;
Experiência com Java para desenvolvimento backend é um diferencial;

**Diferenciais:**
- projetos no segmento financeiro;
- Experiência com desenvolvimento fullstack utilizando Java no backend;

## Benefícios

Aqui na Datum, nossos datunianos usufruem de benefícios e programas que atendem diversas áreas da vida.

Para sua saúde, oferecemos assistência médica e odontológica sem coparticipação em exames e consultas.
Seguro de vida
Quer mais bem-estar? Oferecemos Gympass, Zenklub (com duas sessões gratuitas por mês) e ginástica laboral para dar aquela alongada durante o expediente.
Quando bater aquela fome, utilize nosso benefício de alimentação Caju para fazer compras em qualquer supermercado ou restaurante.
Ama viajar? Aqui temos o Férias & Co, um benefício que te ajuda a viabilizar aquela viagem dos sonhos.
Tem filhos? Temos auxílio creche.
Quer aprender um novo idioma? Temos parceria com a escola CCAA, com descontos de até 40% nos cursos, e também o English Live que oferece 30% de desconto na mensalidade.
Para deixar seu ambiente de trabalho com a sua cara, conte com o nosso auxílio home office.
Quer protagonizar? Participe do Protagonistas, nosso game da vida real, e ganhe prêmios incríveis!

## Contratação

PJ ou CLT

## Como se candidatar

Por favor envie um email para juliana.kraemer@datum.inf.br.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível

- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
