### ISSUE TITLE
[Remoto] DevOps (GCP) Sênior na Going2

### ISSUE THREAD

**Issue by gabrielabenite** [frontendbr/vagas#7929]
## Nossa empresa

A Going2 é uma software House que atua no mercado desde 2012, hoje com projetos tanto a nível nacional e internacional buscamos oferecer a melhor solução tecnológica para todos nossos clientes. Seja proporcionando a inocação através do desenvolvimento de softwares. Venha nos conhecer melhor! https://going2.com.br/ 

## Descrição da vaga

Hoje buscamos um profissional de DevOps que atuará em um projeto específico dentro da empresa na qual o tema é futebol. O projeto é um aplicativo já lançado nas apps stores, uma rede social voltado ao mundo do futebol. 

## Local

Remoto

## Requisitos

- Experiência em Cloud GCP: Conhecimento intermediário em Google Cloud Platform.
- Conhecimento em DevOps: Sólida compreensão dos conceitos e práticas de DevOps, incluindo CI/CD.
- Arquitetura de Micro serviços: Experiência em projetar e integrar serviços distribuídos baseados em nuvem.
- Tecnologias de Big Data: Conexão com as últimas tecnologias de Big Data.
- Metodologias Ágeis: Experiência em metodologias ágeis de desenvolvimento de software.
- Mentoria e Colaboração: Habilidade para disseminar melhores práticas e colaborar com a equipe.
- Lógica de Programação: Domínio em lógica de programação e orientação a objetos.
- Micro serviços: Experiência em arquitetura de micro serviços.
- Técnicas de DevOps: Conhecimento em técnicas de DevOps.
- Banco de Dados: Experiência com bancos de dados relacionais e não relacionais.
- Computação em Nuvem: Experiência em computação massivamente paralela na nuvem, preferencialmente no GCP.
- Experiência como DevOps: Histórico comprovado de atuação como DevOps.
- RNFs (Requisitos Não Funcionais): Compreensão de requisitos como disponibilidade, escalabilidade, manutenibilidade, interoperabilidade, autenticação, autorização, etc.
- Infraestrutura em Nuvem: Experiência em infraestrutura em ambiente de nuvem com operações de entregas diárias.
- DevOps (CI/CD): Familiaridade com práticas de CI/CD.
- Containers e Orquestração: Familiaridade com Docker, Kubernetes, ECS, entre outros.
- Provisionamento e Configuração: Conhecimento em ferramentas como Vagrant, Ansible, Puppet, Terraform, etc.
- Segurança da Informação: Noções em Segurança da Informação.

**Diferenciais:**

- Linguagens de Programação: Domínio das linguagens Node.js e React.

## Benefícios

- Ajuda de custo exclusivo para convenio médico e odontológico;
- Convênio com plataforma de idiomas (Fluency Academy e Yowza);
- Plataforma de treinamento Udemy Business;
- Day-Off de aniversário;
- 15 dias de descanso remunerado;
- Folga em feriados nacionais;
- Plano de carreira.

## Contratação

PJ 

## Como se candidatar

Por favor, acesse o link abaixo e se inscreva na oportunidade: https://going2.vagas.solides.com.br/vaga/323440 

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
