### ISSUE TITLE
[Santana de Parnaíba - SP] Analista Front-End [Buscapé Company]

### ISSUE THREAD

**Issue by pablosoares** [frontendbr/vagas#793]
## Descrição da vaga

Desenvolve páginas fazendo uso de linguagens, frameworks e metodologias de programação específicas, produzindo o layout de um produto digital e criando interatividade entre os elementos da página ou do aplicativo.

## Local

Santana de Parnaíba - SP

## Benefícios

VT + Fretado + VR + VA + AM + AO + SV + PLR (anual, de acordo com o cumprimento das metas). 

#### Diferenciais

Frutas todos os dias, Ginástica Laboral 2x na semana, Massagem 1x por semana, Short Friday + Day off na semana do aniversário + Parceria com Gym Pass e Reembolso de maratonas e corridas + Inglês in Company

## Requisitos

- Node.js
- Angular.js
- React
- Javascript
- CSS
- Agile

## Contratação

Não informado.

## Nossa empresa

Nosso cliente é uma das melhores empresas para se trabalhar segundo a Great Place to Work!!!
 
Líder global em comparação de preços, presente no Brasil, México, Argentina, Chile, Colômbia e em 17 países da América Latina.
 
A empresa é integrante do Buscapé Company, uma plataforma digital completa que reúne marcas envolvidas nas diversas etapas de uma compra digital com um único objetivo: potencializar as relações de consumo de maneira sustentável, proporcionando a melhor experiência de compra.

## Como se candidatar

Por favor envie um email para fabiana.vilar@brtalent.com.br com seu CV anexado - enviar no assunto: Vaga Analista Front-End

## Labels

- Alocado

**Comment by laugustofrontend** [comment]
enviado

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
