### ISSUE TITLE
[Híbrido - Porto Alegre - RS] Flutter Developer no Tribunal de Justiça do Rio Grande do Sul [TJRS]

### ISSUE THREAD

**Issue by JoseCastellaniNeto** [frontendbr/vagas#7934]
## Descrição da vaga

**Desenvolvedor (a) Flutter Sênior (CLT) em Porto Alegre - RS**

Já pensou em trabalhar em uma das maiores empresas de Tecnologia do Brasil?
Então a Cast Group é o lugar certo para você! 😉

**🔎 O QUE BUSCAMOS:**
Profissional para atuação híbrida em Porto Alegre, com ensino superior completo em TI ou áreas afins e/ou curso técnico em áreas de TI.

**💡 CONTAMOS COM VOCÊ PARA**
Atuar com levantamento de requisitos, análise e planejamento de soluções para os requisitos levantados e prototipagem de sistemas;
Prestar apoio aos desenvolvedores e testadores através do detalhamento, especificação e diagramação de requisitos;
Conduzir projetos de desenvolvimento de novas soluções;
Realizar teste dos aplicativos e integrações;
Realizar a análise e correção de bugs;
Gerenciar o ciclo de vida do app;
Replicar telas de protótipos e implementar regras de negócio;
Realizar deploy/publicação em Google e Apple.

## Local

Modelo de Trabalho: 🧑‍💻 Híbrido (2x por semana presencial e 3x Home Office)
Porto Alegre - Rio Grande do Sul

## Benefícios Fixos

🍲 Vale-Refeição ou Vale-Alimentação
🚘 Auxílio transporte
🚑 Plano de saúde e seguro de vida

## Benefícios Flexíveis 

👩🏻‍💳 Cartão FLASH
🚴🏼‍♀️ Gympass
🦷Plano Odontológico
👨‍👩‍👦Reembolso dos custos da Educação de seus filhos, medicamentos, procedimentos estéticos, óculos e lente de contato
🏠Home Office – pague suas contas de telefone, internet e luz

#### Diferenciais

👩🏻‍🎓Aqui na Cast Group, temos Desenvolvimento para você! O Cast Inside é nossa plataforma está recheada de cursos on-line. E parceria com escola de Inglês com super desconto para colaboradores e seus familiares.

## Requisitos

**Obrigatórios**
Análise de sistemas (mínimo 3 anos com qualquer linguagem de programação);
Desenvolvimento de aplicativos móveis usando Flutter/Dart (mínimo 1 ano de experiência).

## Contratação

CLT

## Como se candidatar

Por favor envie um email para jose.castellani@castgroup.com.br com seu CV anexado - enviar no assunto: Vaga Flutter
Ou no celular 41 3513-9112

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.

## Labels
- CLT
- Pleno
- Híbrido
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
