### ISSUE TITLE
[Remoto] Vaga: Front-end Desenvolvedor(a) Pleno/Sênior Node.js and React - Freelancer - Guató Digital

### ISSUE THREAD

**Issue by gonzagajaque** [frontendbr/vagas#7937]
> Vaga Remota durante a pandemia

## Nossa empresa

Guató Digital é uma software house nova e em crescimento, buscando um(a) desenvolvedor(a) qualificado(a) para participar de um projeto desafiador de construção de um site e-commerce, com integração na plataforma Shopify.

## Descrição da vaga

Responsabilidades:

Implementar soluções a partir das definições de negócio do site.
Contribuir nas definições do time para as melhores soluções arquiteturais, tanto para o Front-End quanto para o Back-End.
Apresentar ideias de melhorias para o produto durante as reuniões.
Corrigir problemas identificados no produto.

## Local

Remoto, [MT], [Cuiabá], [Coophema]

## Requisitos

**Obrigatórios:**
- 3+ anos de experiência com Node.js.
- 3+ anos de experiência com React.
- 2+ anos de experiência em times Ágeis: Scrum ou Kanban.
- 3+ anos de experiência com Git ou GitLab.

**Desejáveis:**
- conhecimentos em reactjs
- conhecimentos em nodejs

**Diferenciais:**
- Experiência com DDD, Clean Architecture, Event Driven Architecture.
- Ambientes cloud: AWS, Google ou Azure.
- Criação de testes automatizados: Postman, XUnit, Moq.
- Criação ou manutenção de pipelines: Github Actions, Jenkins, Azure, etc.

## Benefícios

- Pagamento semanal
- Possibilidade de contratação

**Diferenciais:**
- faça seu horário

## Contratação

PJ
Remuneração total dividida em pagamentos semanais de acordo com as entregas e horas realizadas.
Possibilidade de novos projetos ou contrato fixo após o término do projeto.
Tempo de trabalho estimado em média 8 horas semanais durante um período de 45 dias.

## Como se candidatar

Por favor envie seu currículo e portfólio para para rh@guatodigital.com com seu CV anexado - enviar no assunto: Vaga Front-End Fullstack

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 4 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by guim0** [comment]
A vaga então é FullStack, não Front-end.
