### ISSUE TITLE
[Internacional e Remoto] Front-End Developer (Angular / Typescript) na Turing

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#7938]
## Job description
A rapidly-growing company, leveraging the power of cutting-edge technologies, is seeking a Web Front-End Developer. The developer will be responsible for creating and implementing user interface components using Angular, GraphQL, and TypeScript. This company is at the forefront of technological innovation, striving to provide solutions that revolutionize the way we interact with the digital world. This is a fantastic opportunity to be part of a team that is shaping the future of technology.

## Job Responsibilities:

- Develop user interface components and implement them following well-known Angular, GraphQL, and TypeScript workflows
- Coordinate with the rest of the team working on different layers of the infrastructure, ensuring a seamless integration of new features
- Translate designs and wireframes into high-quality code, optimizing components for maximum performance across a vast array of web-capable devices and browsers
- Understand business requirements and translate them into technical requirements
- Predict potential problems and provide proactive solutions to ensure smooth software operation
- Stay up-to-date with the latest industry trends and technologies to keep the company at the cutting edge

## Job Requirements:

- Bachelor’s/Master’s degree in Engineering, Computer Science (or equivalent experience)
- A minimum of 6-7 years of overall experience in the field, with at least 5 years of experience in Angular, GraphQL, and TypeScript
- Understanding of RESTful APIs, asynchronous request handling, and partial page updates
- Excellent communication skills and fluency in English are essential

## Como se candidatar

[Clique aqui](https://bit.ly/46OtvdL) para se candidatar

Importante: Esta vaga está sendo publicada pela [Remotar](https://remotar.com.br/?utm_source=github) em nome da Turing, nosso cliente. Ao acessar, você será redireciona(a) para a plataforma da Turing, e todo o processo seletivo será diretamente com eles.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
