### ISSUE TITLE
[Remoto e Internacional] React.js Developer na Turing (3+ anos exp)

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#7939]
## Job description
A US-based company on a mission to build a revolutionary AI enabled review software is looking for a React.js Developer. The selected candidate will collaborate with a cross-functional team to ensure the application conforms to user specifications. The company's game-changing product is highly customizable and adaptable to individual cases and taps into the power of advanced technology to make it easier for human reviewers to get the job done. The company has managed to raise more than $2.8mn during their Seed round.

## Job Responsibilities:

- Use the contemporary React Material UI technology to create the front-end interface
- Refine user stories with the help of back-end developers
- Use REST APIs to connect to an existing back-end
- Produce code that is both efficient and secure
- Provide assistance after the release

## Job Requirements:

- Bachelor’s/Master’s degree in Engineering, Computer Science (or equivalent experience)
- At least 3+ years of relevant experience as a software developer
- Must have experience in JavaScript
- 2+ years of experience in HTML5 and CSS3
- 1+ years of experience in creating apps with popular front-end frameworks and JavaScript libraries
- Knowledge of development tools like Git, ESLint, and Prettier
- Experience working with Rest APIs, responsive web design, and Material UI
- Familiarity with developing enterprise dashboards and implementing CI/CD
- Experience with Figma files, writing secure production, and testing code 

## Como se candidatar

[Clique aqui](https://bit.ly/47JgRh2) para se candidatar

Importante: Esta vaga está sendo publicada pela [Remotar](https://remotar.com.br/?utm_source=github) em nome da Turing, nosso cliente. Ao acessar, você será redireciona(a) para a plataforma da Turing, e todo o processo seletivo será diretamente com eles.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
