### ISSUE TITLE
[São Paulo] Software Engineer na Cotabox

### ISSUE THREAD

**Issue by kavalcante** [frontendbr/vagas#794]
## Descrição da vaga

Estamos em busca de um Software Engineer para trabalhar principalmente com Node.js e Vue.js (com SRR via Nuxt). Que tenha muita vontade de aprender, pouco medo de errar e que tenha tesão em fazer um produto crescer e ambição de se tornar líder de mercado =)

## Local  

Ficamos na incubadora de negócios da Fatec Sebrae, na Alameda Nothmann, 598 - Campos Elíseos, São Paulo - SP, 01216-000.

Mas também usamos espaços de coworking, como Google Campus, porém tudo previamente combinado. Além de remoto algumas vezes na semana.
		
## Benefícios  
- VR
- VT

## Requisitos  
**Obrigatórios:**
- Conhecimentos em Javascript moderno (ES6).
- Conhecimentos em NodeJS.
- Conhecimentos em Vuejs/Nuxt ou equivalentes como Angular2, Ember e React.
- Conhecimentos em MongoDB ou outros bancos orientados a documento.
- Inglês (leitura avançada).

**Desejáveis:**
 *Utilizamos todas essas tecnologias, mesmo que não as domine  podemos aprender juntos!*
- Elasticsearch + Kibana.
- Azure + Azure Functions.
- GraphQL.
- Apollo Server Express + Apollo Client.
- Git/Github.
- Buddy CI (Continuous Integration).
- Mocha + Chai + Cypress

**Diferenciais**
- Projetos OpenSource, talks, artigos ou tutoriais publicados.
## Regime de contratação 
PJ
## Nossa empresa 
A Cotabox é uma plataforma de cotação e compras, ajudamos compradores a achar fornecedores para suas demandas com qualidade, rapidez e a custo zero. Enquanto que para os fornecedores entregamos vendas concretas e sem taxas fixas.
## Como se candidatar? 
Eaí, curtiu? Então aplique-se através desse form e aguarde nosso contato =) https://goo.gl/forms/AcX63ZNAkBOi47LX2

## Labels

- Alocado
- Júnior
- Pleno
- PJ
- Remoto - Parcial

**Comment by viniciusoliveira01** [comment]
Não existe possibilidade de ser somente remoto com possibilidade de visitas durante 2018? (Questão de faculdade presencial e morar a 200km de SP)

**Comment by kavalcante** [comment]
@viniciusoliveira01 Qual seria a sua disponibilidade para visitas? Com qual frequência?

**Comment by viniciusoliveira01** [comment]
Creio que a cada 15 dias seria tranquilo.

**Comment by kavalcante** [comment]
@viniciusoliveira01 Sem problemas :), só se candidatar!

**Comment by viniciusoliveira01** [comment]
Obrigado!

**Comment by laugustofrontend** [comment]
@viniciusoliveira01 curriculum enviado

**Comment by kavalcante** [comment]
Pessoal, peço desculpas aos candidatos que se candidataram e acabaram não recebendo feedbacks. Na época da candidatura, acabamos mudando de cidade com a empresa (estamos em Botucatu). E na correria, eu acabei esquecendo de avisar e de fechar a issue aqui.

Sei que isso é bem chato, por isso vim aqui me retratar, pois só lembrei da issue agora. Espero que possamos abrir uma vaga, porém dessa vez aqui em Botucatu, o mais breve possível.
