### ISSUE TITLE
[Internacional e Remoto] React/TypeScript Developer na Turing (3+ anos exp)

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#7940]
## Job description
A rapidly-growing company that specializes in GIS applications and places a strong emphasis on open-source location technology, is looking for a React/TypeScript Developer. The selected candidate will be responsible for creating scalable, high-performing, secure, and robust software through appropriate architecture, design, and delivery. The company is leveraging the power of modern technology, open-source, and free software to help businesses across the world efficiently fulfill their geospatial requirements. This is an amazing opportunity for developers who are eager to work with a team of industry professionals while rapidly enhancing their careers. 

 

## Job Responsibilities:

- Create and keep up with all server-side network elements.
- Make sure the main database runs as efficiently as possible and that the front-end responds quickly
- Work together on the integration of the components with cross-functional teams
- Create UIs for customers and back-end services for different business processes

## Job Requirements:

- Bachelor’s/Master’s degree in Engineering, Computer Science (or equivalent experience)
- At least 3+ years of relevant experience as a software developer
- Prolific experience working with React and TypeScript
- Detailed knowledge of component and e2e testing, a component of software quality assurance
- Solid understanding of geospatial ideas, including using mapping libraries
- Great time management and interpersonal skills
- Ability to meet deadlines and deliver stunning results
- Fluent in spoken and written English communication

## Como se candidatar

[Clique aqui](https://bit.ly/3uFE6tM) para se candidatar

Importante: Esta vaga está sendo publicada pela [Remotar](https://remotar.com.br/?utm_source=github) em nome da Turing, nosso cliente. Ao acessar, você será redireciona(a) para a plataforma da Turing, e todo o processo seletivo será diretamente com eles.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
