### ISSUE TITLE
[REMOTO] Pessoa Desenvolvedora FrontEnd React Sênior @DQR Tech

### ISSUE THREAD

**Issue by gsabreudev** [frontendbr/vagas#7941]
## Sobre a DQR TECH | Qualidade do começo ao fim
Nascemos de uma parceria de mais de 10 anos entre seus sócios, somando a paixão por tecnologia à vontade de construir uma empresa diferente, investindo na proximidade com nossos parceiros e clientes. Somos uma consultoria especializada em Arquitetura de TI, Outsourcing de Profissionais e Hunting.

## DE ONDE VOCÊ VAI TRABALHAR?
De onde você se sentir melhor. Esta vaga é anywhere.

## O QUE NOS MOVE:
Tecnologia & Pessoas! E é por isso que estamos buscando os melhores profissionais para atuar em nosso cliente da área de Inteligência de Dados (Data Tech).

## O SEU DESAFIO SERÁ:
Você participara do desenvolvimento do produto na área de Antifraude.

## Atividades:
Desenvolver soluções técnicas que atendam os requisitos de negócio, buscando a criação de aplicações escaláveis e performáticas; 

Desenvolver sistemas batch e condumir APIs Rest em React, baseado na documentação fornecida, criando aplicação que atendam às exigências do usuário; 

Identificar, corrigir incidentes e realizar manutenção em sistemas, de acordo com a descrição do problema e a análise de logs; 

Elaboração de documentação técnica da solução implementada; 

Elaboração de testes com Jest e testing library; 

Capacidade de interação com área de negócios com objetivo de elucidar requisitos de negócios, homologar sistemas desenvolvidos e contribuir com informações técnicas em reuniões de alinhamento da demanda; 

Desejável ter atuado com metodologias ágeis.

## O QUE ESPERAMOS QUE VOCÊ TENHA:
Sólido conhecimento em desenvolvimento REACT (06 anos) e desenvolvimento de API’s Rest;

Bootstrap; CSS3; HTML5; Javascript;

Docker; GIT;

Banco de Dados (MySQL; PostgreSQL);

Testes unitários.

## O QUE SERIA LEGAL SE VOCÊ SOUBESSE:
Elastic Stack 
Javascript

 NoSql 

Ansible 

Express 

JQuery 

TypeScript 

## QUAIS AS SOFT SKILLS SÃO IMPORTANTES VOCÊ TER:
Autogestão; Gestão do tempo; Pensamento crítico; Comprometimento; Facilidade de envolvimento com a regra de negócio.

## O QUE OFERECEMOS PARA VOCÊ?
Contratação PJ de 13k PJ;
Disponibilização de notebook feita pelo cliente.

Pode enviar seu material em vagas@dqrtech.com.br

Obs nossos feedbacks sao cedidos de 7 a 14 dias via e-mail.

**Comment by gsabreudev** [comment]
> Faltou adicionar link ou e-mail para se candidatar

Olá Erik, inseri ali, Obrigada pela sinalização.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
