### ISSUE TITLE
[Remoto] Fullstack Developer +3XP @ Mollica IT

### ISSUE THREAD

**Issue by raissaime** [frontendbr/vagas#7942]
## Nossa empresa

Buscando projetos internacionais?

Então vem com a Mollica IT e encontre a oportunidade certa pra dar match!

Estamos buscando uma pessoa desenvolvedora que procure sempre entregar o código com qualidade. Temos um time extremamente focado 😎 e muito mais para você conhecer/contribuir.

## Requisitos Obrigatórios:

- Experiência em projetar e desenvolver aplicativos da Web utilizando Express, Node.Js, Angular 8+, CSS3, HTML5, banco de dados e Javascript;
- Experiência no desenvolvimento de middleware, integração e sistemas de mensagens usando APIs REST e plataformas populares de barramento de mensagens (por exemplo, RabbitMQ, Barramento de Serviço do Azure);
- Forte compreensão dos conceitos de programação assíncrona orientada a eventos e princípios de design de aplicativos de melhores práticas;
- Forte compreensão do design e consulta de banco de dados não relacional usando MongoDB, Cassandra, Redis ou outro;
- Compreensão da integração contínua e implantação contínua, idealmente usando o Azure DevOps (anteriormente Visual Studio Team Services).
- Obrigatório Ensino superior completo em áreas de tecnologia.

🌎 **Idioma:**
**Inglês avançado para conversação (Haverá etapa de entrevista nesse idioma).**

## Local

Remoto ou Escritório - São Paulo ou Londrina.

## Benefícios

✔️Assistência Médica para colaboradores e dependentes com abrangência nacional da Bradesco ou Unimed

✔️Assistência Odontológica com abrangência nacional

✔️Vale Refeição ou Vale Alimentação (a escolha do colaborador)

✔️Auxílio creche

✔️Seguro de Vida para associados e dependentes

✔️Gympass para associados e dependentes

✔️EAP (Employee Assistance Program) com os seguintes serviços: Assistência Financeira, Assistência Jurídica, Assistência Social, Assistência Psicológica (24 horas – 7 dias por semana).

✔️Descontos e tarifas diferenciadas junto a Universidades (Mackenzie, SENAC, FIA, FIAP e BBS Business School) e escola de idiomas (CNA, Cultura Inglesa, Wizard, CCAA, Indeed).

✔️Descontos em pacotes de tarifas e taxas diferenciadas para Bancos Itaú e Bradesco

✔️Opção de crédito consignado, com desconto diretamente no salário do colaborador

✔️Programa de reembolso de algumas certificações externas

✔️Treinamento: A TCS oferece plataforma de treinamento e desenvolvimento a distância e presencias, em soft skills, tecnologias e domínios em mais de 15.000 temas.

✔️Premiação por tempo de casa: A TCS premia associados por seu comprometimento e lealdade durante o período em que trabalhar na empresa (3, 5 e 10 anos e cada 5 anos posteriormente).

✔️Prêmio de indicação de novos colaboradores - recebendo um bônus para cada nova contratação.

✔️TCS Fit4life - Programa para incentivar a prática de exercício físico junto a seus associados, com agenda de treinamentos funcionais online.

✔️Experiência internacional: Dependendo de seus conhecimentos e das demandas do negócio você pode se candidatar a vagas no exterior (dentro e fora da América Latina).

✔️Entre outros;

## Contratação

- CLT;

## Como se candidatar
https://tally.so/r/mO7rkA

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.

#### Alocação
- Híbrido
- Remoto

#### Regime
- CLT

#### Nível

- Pleno
- Sênior

**Comment by AlvaroDavi5** [comment]
Candidatura realizada 😀
