### ISSUE TITLE
[Hibrido - Alphaville] Front-end Developer no Grupo Primo

### ISSUE THREAD

**Issue by brenooliveira** [frontendbr/vagas#7943]
### Responsabilidades:
Desenvolver e manter interfaces de usuário eficientes utilizando Vue.js com JavaScript.
Otimizar aplicações para garantir alta performance e experiência do usuário.
Colaborar estreitamente com a equipe de design para implementar soluções visuais eficazes.
Participar ativamente do ciclo de vida completo de desenvolvimento, desde o design até a implementação.
Identificar e resolver problemas de forma proativa, colaborando com outras equipes conforme necessário.
Manter-se atualizado com as melhores práticas de desenvolvimento front-end e as tendências do setor.
 
### Requisitos:
Experiência comprovada como desenvolvedor front-end, com foco específico em Vue.js(Options API, Composition API, Vuex).
Sólido entendimento de HTML, CSS e JavaScript/TypeScript.
Familiaridade com bibliotecas e frameworks front-end modernos.
Boa comunicação e habilidades de trabalho em equipe.
Comprometimento com a entrega de produtos de alta qualidade.
 
### Diferenciais:
Conhecimento em testes automatizados para aplicações Vue.js.
Conhecimento em CI/CD
Experiência com integração de APIs RESTful.
Familiaridade com metodologias ágeis de desenvolvimento.
Participação ativa em comunidades de desenvolvedores ou contribuições para projetos de código aberto.

### O que oferecemos:
🍛Vale Refeição e Vale Alimentação disponível no Cartão flexível Swile
🚑 Plano de saúde Amil
🦷 Plano odontológico Bradesco
🏋🏾‍♂️Total Pass
⚠️ Seguro de vida
🚌 Vale Transporte
👶🏽Auxilio creche
📝Acesso as plataformas

Para se candidatar [https://www.linkedin.com/jobs/view/3774776880/?capColoOverride=true](https://www.linkedin.com/jobs/view/3774776880/?capColoOverride=true)

**Comment by laerciodev** [comment]
A vaga é CLT ou PJ?

**Comment by brenooliveira** [comment]
A vaga é **CLT**

**Comment by Felipe-Tomazetti** [comment]
Breno, existe a possibilidade de conversa para remoto?

**Comment by brenooliveira** [comment]
> Breno, existe a possibilidade de conversa para remoto?

Existe sim

**Comment by Felipe-Tomazetti** [comment]
Breno, apliquei, eu to prontíssimo pra entrar nesse foguete to Nigro, sou fã demais, seria um sonho! Eu tentei mandar msg para a responsável pela vaga, mas não tenho ela no LinkedIn rs

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
