### ISSUE TITLE
 [Remoto] Front-end Developer Vue3 na Dietsystem

### ISSUE THREAD

**Issue by thiagoferreira123** [frontendbr/vagas#7945]
> Vaga Remota durante a pandemia

## Nossa empresa

Somos um software web em fase de desenvolvimento.

## Descrição da vaga

Estamos migrando nosso frontend para vue3, e precisamos de reforços.

## Local 

- Remoto 

## Requisitos

**Obrigatórios:**
- Experiência em software web com Vue3, axios, componentes, boas práticas 

**Desejáveis:**
- conhecimento em nestjs, typeorm

## Como se candidatar

Por favor envie um email para contato@dietsystem.com.br com seu CV anexado - enviar no assunto: Vue3

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- Freela

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by jhefflg** [comment]
Up.

**Comment by joelpmonteiro** [comment]
enviado

**Comment by thiagoferreira123** [comment]
Obrigado! Candidato encontrado.
