### ISSUE TITLE
[Remoto] Front-end Developer na Hepta Tecnologia

### ISSUE THREAD

**Issue by sarahcorrea16** [frontendbr/vagas#7946]
> 

## Nossa empresa

A empresa contratante é a Hepta tecnologia, sediada em Brasília com 31 anos de atuação no mercado. Temos contratos com empresas privadas e órgãos públicos, em virtude disso aqui é um espaço amplo de crescimento e desenvolvimento profissional. O time é bastante colaborativo, na verdade colaboração faz parte do nosso valor 🚀

## Descrição da vaga

React, Next.js, Node.js, TDD, JavaScript ou TypeScript.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 5 anos de experiência como DEV. (Necessário comprovar)
- Formação Superior completa em TI (Necessário comprovar)

Certificação em: Professional Scrum Developer (PSD) ou Certified Scrum Developer (CSD)

Para o perfil Sênior desejável mais uma em: PSM I, II ou III. Ou CSM; Ou SMC; Ou ASM. (P/ atuar como Scrum Master)

Caso você não possua, concedemos um prazo para adquirir. É importante ressaltar que a empresa não cobre os custos, apenas oferece a oportunidade de estender o prazo.

IMPORTANTE:
A Hepta presta serviço p/ instituições federais, as exigências que você leu sobre comprovação de experiência, formação superior em TI e certificação são exigências do edital e nós precisamos cumprir.

## Benefícios

- Plano de saúde
- VR ou VA
- Plano Odontológico
- Auxílio Home Office

## Contratação

CLT

## Como se candidatar

Por favor envie um email para sarah.vieira@hepta.com.br com seu CV anexado - enviar no assunto: Vaga Git

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by willhalen** [comment]
Curriculo, enviado. Grato.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by willhalen** [comment]
Bomdia Felipe!!!

Tenho interesse sim.

Grato,

William.S
(11)97692-4464

Em sex, 16 de fev de 2024 21:36, Felipe Fialho ***@***.***>
escreveu:

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
