### ISSUE TITLE
[Remoto] Front-end Developer na Artemis Corporation

### ISSUE THREAD

**Issue by mwseraphim0** [frontendbr/vagas#7947]
## Nossa empresa

Na Artemis Corporation, somos especialistas na fusão de marketing digital e desenvolvimento de softwares. Com uma equipe de profissionais dedicados e apaixonados, oferecemos soluções inovadoras que aliam estratégias de marketing de ponta a tecnologias de software avançadas. Nossa missão é conectar marcas ao seu público-alvo de maneira significativa, usando as mais recentes ferramentas e abordagens digitais. Nós nos orgulhamos de transformar ideias em realidade, garantindo que nossos clientes alcancem resultados excepcionais e uma presença online notável.

## Descrição da vaga

Exemplo: Projeto em desenvolvimento utilizando Angular como tecnologia principal.

## Local

Exemplo: Remoto

## Requisitos

**Obrigatórios:**
-  Desenvolver aplicativos da Web utilizando Angular 14+, CSS3, HTML5, Typescript
- Conhecimento de integração de API's Rest

**Diferenciais:**
- Conhecimento em NodeJS

## Contratação

Freela

## Como se candidatar

michael@artemiscorporation.com.br

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Júnior

**Comment by RaulFerreiraSilva** [comment]
Envie meu currículo, obrigado pela oportunidade.

**Comment by vanessawin** [comment]
Currículo enviado

**Comment by jmgrd98** [comment]
enviado!

**Comment by demohenry** [comment]
Currículo enviado!

**Comment by Pauloo2003** [comment]
Enviado

**Comment by leo-holanda** [comment]
Currículo enviado! Obrigado!

**Comment by willhalen** [comment]
Enviado!!!

**Comment by mwseraphim0** [comment]
Vaga preenchida
