### ISSUE TITLE
[Florianópolis] Flutter / React Native Developer na Conecta Capital Humano

### ISSUE THREAD

**Issue by raissaime** [frontendbr/vagas#7949]
>

## Nossa empresa

Vaga para cliente Conecta Capital Humano.

## Descrição da vaga

**Requisitos Obrigatórios:**
- Formação completa ou incompleta em Sistemas de informação, Ciências da computação, Engenharia de software ou algum curso na área de desenvolvimento de software;
- Experiência como desenvolvedor Flutter (mobile) ou React Native; 

## Local

Presencial - Bairro Trindade - Florianópolis/SC;

## Benefícios

- Cartão CAJU (benefício flexível) R$500,00 mensal;

- Plano de saúde Bradesco (copart 50%) e odontológico;
- Convênio GoGood benefício de bem-estar (desconto em academias);
- DayOff no mês de aniversário, e premiação no CAJU de R$50,00;

## Nossa empresa

Empresa brasileira referência em documentação técnica online para diagnóstico e reparação automotiva profissional.
Conheça as soluções para sua oficina!

## Contratação

CLT

## Como se candidatar

https://tally.so/r/wd9JlA

#### Alocação
- Presencial

#### Regime
- CLT

#### Nível
- Júnior

**Comment by ChrisSerello** [comment]
Candidatura feita com sucesso!

**Comment by ricardoraposo** [comment]
Candidatura feita!!!
Obrigado pela oportunidade.

**Comment by marcelo-de-santana** [comment]
Cadidatura realizada com sucesso.
