### ISSUE TITLE
[São Paulo] Front-End Developer Jr/PL na EcommIT

### ISSUE THREAD

**Issue by engaugusto** [frontendbr/vagas#795]
## Descrição da vaga

Se você é um desenvolvedor, que gosta de desafios e resolver problemas.
Gostaríamos muito de falar com você!

Procuramos desenvolvedores com alta capacidade de aprendizagem, motivado, que seja organizado no código, nos testes e na vida. 

Seu desafio será ajudar a criar a melhor solução para o cliente de acordo com o que ele pedir, e isso nunca é tão simples :)

* Você trabalhará principalmente:
* Na parte de backend (Node.js/Express) apoiando no desenvolvimento na REST API.
* Também será necessário ter conhecimentos de Java e Webservices (SOAP)
* Ajustar códigos feitos em Java

## Local

Escritório, São Paulo - COPAN

## Benefícios

- Salário compatível com mercado, regime PJ/CLT/Cooperado.

- Ambiente de Startup.

- Possuímos um programa de mentoria que irá te ajudar a desenvolver seu potencial. 

#### Diferenciais

- Profissionais de alta capacidade do mercado
- Aprendizagem com certeza
- Mentoria

## Requisitos

**Obrigatórios:**
- Node.js
- Express.js
- React
- RESTful API
- Ajax
- SOAP
- Webservices
- Java

**Desejáveis:**
- Git
- MongoDb
- Excel

**Diferenciais:**
- projetos opensource
- portfólio no github 

## Contratação

PJ a combinar / CLT / Cooperado

# Nossa empresa

![Image of EcommIt](https://github.com/ecomm-it/brand/blob/master/IT-small.png?raw=true)

A Ecomm-IT é uma empresa madura no mercado de consultoria de tecnologia da informação principalmente no segmento financeiro, atualmente estamos expandindo nossas operações para diversos setores.

##Como se candidatar

Por favor envie um email para vagas@ecommit.com.br com seu CV anexado / portfolio e sua pretensão salarial 

## Labels

- Alocado
- CLT
- Júnior ou Pleno
- PJ / CLT / Cooperado
- Node
- Javascript
- Java

**Comment by MatheusWTF** [comment]
Então essa vaga seria para Backend?

**Comment by kvnol** [comment]
Essa vaga é back-end, posta lá no repo de back! ;)

**Comment by LFeh** [comment]
Nossa, pode crê. Posta lá @engaugusto, vou fechar aqui.
