### ISSUE TITLE
[remoto] Front-end Developer na M3, a Cadastra Company

### ISSUE THREAD

**Issue by MarlonPassos-git** [frontendbr/vagas#7950]
## Empresa: **M3, a Cadastra Company**

- site https://m3ecommerce.com/
- linkedin: https://www.linkedin.com/company/m3ecommerce/ 

## Atividades diárias 
Desenvolver projetos de lojas virtuais na plataforma VTEX.

## Requisitos para Júnior
- Ter domínio em programação JavaScript/Typescript, HTML/HTML5, CSS e React;
- Performance WEB e Desenvolvimento web responsivo.

## Requisitos para Pleno
- Ter experiência em VTEX;
- Ter domínio em programação JavaScript/Typescript, HTML/HTML5, CSS, React e Next.JS;
- Performance WEB e Desenvolvimento web responsivo;
- Ter conhecimento em TypeScript e React.

## Como se candidatar
Acesse https://app.pipefy.com/public/form/cjJmu6-g 

## Alocação
- Remoto

## Regime
- CLT

## Nível
- Júnior
- Pleno

**Comment by joao160197** [comment]
Enviado

**Comment by gabrielmajeski** [comment]
Enviado

**Comment by vanessawin** [comment]
Enviado

**Comment by KaianDev** [comment]
Enviado, que Deus abençoe 🙌

**Comment by netto0** [comment]
Enviado!

**Comment by wsasouza** [comment]
Enviado..

**Comment by Soaressluiss** [comment]
Consta no site da empresa que essa vaga é exclusiva para PcD.

**Comment by SilasRodrigues19** [comment]
Enviado

**Comment by lucas-wa** [comment]
Enviado

**Comment by FelipeRTognetta** [comment]
Enviado!!

**Comment by gvao** [comment]
Enviado currículo

**Comment by marcus6n** [comment]
Currículo Enviado!

**Comment by Wallison-Greg** [comment]
Enviado!

**Comment by felipopm** [comment]
Boa tarde Marlon, me chamo Felipe e tenho interesse na vaga.

Estou fazendo transição de profissão.

Trabalho a mais de 10 anos no setor de engenharia, estou praticando
Desenvolvimento Web front-end há algum tempo com o auxílio de uma amigo que
já trabalha como desenvolvedor.

Segue em anexo meu currículo.

Em qua., 13 de dez. de 2023 às 21:18, Marlon Passos <
***@***.***> escreveu:

**Comment by Andrei-Oliveira** [comment]
Currículo enviado...🙏🏻👏🏻🙏🏻

**Comment by GilsonJrr** [comment]
Currículo Enviado!!

**Comment by Apolinar1o** [comment]
enviado

**Comment by leonardosfilho** [comment]
Enviado, aguardando o feedback.

**Comment by LukinhaGabriel** [comment]
Curriculo Enviado

**Comment by Riquecelo** [comment]
Currículo enviado!

**Comment by micheledarosa** [comment]
Currículo enviado •᎑•

**Comment by brunonoatto** [comment]
E-mail enviado, obrigado por compartilhar a vaga.

**Comment by OOliverjj** [comment]
Enviado 👨‍💻😁

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by lucianowribeiro** [comment]
Enviado
