### ISSUE TITLE
[Remoto] Front-end Developer na Gênesis PUC-Rio

### ISSUE THREAD

**Issue by glauberm** [frontendbr/vagas#7952]
## Nossa empresa

Somos um ambiente de inovação que impulsiona ideias inovadoras e startups. Somos a incubadora de empresas da PUC-Rio: apoiamos projetos, startups e empreendedores em todo o Brasil.

## Descrição da vaga

A Pluriverso está de vagas abertas para Webdesigner, preferencialmente para Front-end ou Full Stack!

É desejado habilidades avançadas em: Wordpress, PHP, CSS, Html5, e conhecimento prático em JS.

A vaga conta com uma oportunidade flexível, com aproximadamente 40 horas por mês, que pode ser tanto de estágio, quanto uma contratação permanente, dependendo da preferência do candidato.

Os interessados deverão enviar um e-mail para kangen@pluriverso.online , com o título "Webdesign Pluriverso".

A remuneração oferecida é de R$ 45 por hora e o prazo para candidaturas é até 22/12.

## Local

Remoto

## Requisitos

- Wordpress
- PHP
- JS
- CSS
- HTML

## Contratação

A vaga conta com uma oportunidade flexível, com aproximadamente 40 horas por mês, que pode ser tanto de estágio, quanto uma contratação permanente, dependendo da preferência do candidato.

## Como se candidatar

Os interessados deverão enviar um e-mail para kangen@pluriverso.online , com o título "Webdesign Pluriverso".

#### Alocação
- Remoto

#### Regime
- CLT
- Estágio
- Freela
- PJ

#### Nível
- Júnior
- Pleno

**Comment by vanessawin** [comment]
Curriculo enviado

**Comment by NTN1789** [comment]
Currículo enviando, será um prazer participar da equipe

**Comment by leonunesweb** [comment]
Portfólio enviado!

**Comment by guilhermebsantiago** [comment]
Currículo e portfólio enviado!

**Comment by geraldotech** [comment]
Enviado grato.

**Comment by nashEm8** [comment]
Enviado, agradeço a oportunidade

**Comment by MrRosario** [comment]
Querem um estagiário com habilidades avançadas em: Wordpress, PHP, CSS, Html5 ?

**Comment by luam0oliveira** [comment]
Currículo enviado. Grato!

**Comment by Gilbertoans** [comment]
Currículo enviado!
