### ISSUE TITLE
[Híbrido - Niterói - RJ] Front-end Developer na Internit

### ISSUE THREAD

**Issue by Fredpeixoto** [frontendbr/vagas#7953]
## Nossa empresa

Com 25 anos de mercado, a Internit é uma empresa consolidada com um ótimo ambiente de trabalho somado a desafios constantes. Temos projetos com empresas como Gafisa, Cyrela, PDG, Brasil Brokers, Accor, Best Western, Anhanguera Educacional, Stefanini, Sankhya, Riocard, Climario, dentre outros.
Estamos situados em uma rua tranquila em Santa Rosa - Niterói com facilidade de estacionamento, além de termos um bicicletário na empresa.

## Descrição da vaga

Desenvolvimento e manutenção de sistemas, sites e lojas virtuais.

## Local

Híbrido, [RJ], [NITERÓI], [SANTA ROSA]

## Requisitos

**Obrigatórios:**
Vivência em Html, CSS, Java Script, GIT, docker. 
O candidato deve estar na faculdade e ter seu currículo cadastrado em nosso site. 

## Como se candidatar

Por favor se cadastrar em https://internit.com.br/curriculo

#### Alocação
- Alocado / Híbrido
- Remoto

#### Regime
- Trainee 
- Estágio

#### Nível
- Júnior

**Comment by tkoch97** [comment]
Currículo enviado!

Em seg., 18 de dez. de 2023 às 16:18, Frederico Peixoto <
***@***.***> escreveu:

**Comment by Eu-Pedro0ficial** [comment]
Curriculo enviado!

**Comment by Fredpeixoto** [comment]
Obrigado. Iremos analisar e qualquer coisa, entraremos em contato.

[image: Internit]
*www.internit.com.br
<https://mailtrack.io/link/59ad2c0f27cb2fe22e80f9053730013a3680e96e?url=http%3A%2F%2Fwww.internit.com.br%2F&userId=393368&signature=5fd922017f60159b>**www.incenadigital.com.br
<https://mailtrack.io/link/b4e56f0b2d3626d11ec7b3622b3f67012e6b580e?url=http%3A%2F%2Fwww.incenadigital.com.br%2F&userId=393368&signature=7771e4c3a4dc4f12>*
 RJ
<https://mailtrack.io/link/a6a7fb9c0b6f5c7135361dd0bb00fd6ac9665ae1?url=https%3A%2F%2Fwww.google.com%2Fmaps%2Fplace%2FR.%2BItaperuna%2C%2B100%2B-%2BP%25C3%25A9%2BPequeno%2C%2BNiter%25C3%25B3i%2B-%2BRJ%2C%2B24240-070%2F%40-22.8961089%2C-43.1073818%2C17z%2Fdata%3D!3m1!4b1!4m5!3m4!1s0x9983f238c0e803%3A0x36d8501864605205!8m2!3d-22.8961089!4d-43.1051931&userId=393368&signature=9844fef295313f7e>
  SP
<https://mailtrack.io/link/0af40641ab681774101b5df7df5ee8abe0fa4edc?url=https%3A%2F%2Fwww.google.com%2Fmaps%2Fplace%2FRua%2BNorma%2BPieruccini%2BGiannotti%2C%2B141%2B-%2BV%25C3%25A1rzea%2Bda%2BBarra%2BFunda%2C%2BS%25C3%25A3o%2BPaulo%2B-%2BSP%2C%2B01137-010%2Fdata%3D!4m2!3m1!1s0x94ce580ebf4681b1%3A0xbc9940a345bbe3e6%3Fsa%3DX%26ved%3D2ahUKEwjm9rTIpdvkAhUcK7kGHZ-bDkEQ8gEwAHoECAoQAQ&userId=393368&signature=e44dbfb8f42c84dd>
*Frederico
Peixoto*
Diretor Comercial
***@***.***
(21) 2621-7788 <+55212621-7788> | (21) 98123-2303 <+552198123-2303>
[image: Acompanhe a Incena no Facebook]
<https://mailtrack.io/link/5b6a1543e7159d4f908c80b89887b44b3c9fd82c?url=https%3A%2F%2Fwww.facebook.com%2Fincenadigital&userId=393368&signature=02684e96f8b0305e>
[image:
Acompanhe a Incena no Facebook]
<https://mailtrack.io/link/d179e3c9a34f2f4397221f47131a9d98f4621d6d?url=https%3A%2F%2Fwww.instagram.com%2Fincenadigital%2F&userId=393368&signature=276d60ae589de3ad>
[image:
Siga-me no Linkedin]
<https://mailtrack.io/link/b3f1027e374307fd117b45a419480d82c5f6bdd2?url=https%3A%2F%2Fwww.linkedin.com%2Fin%2Ffredericopeixoto%2F&userId=393368&signature=3fdd0abd71905df3>


Em seg., 18 de dez. de 2023 às 17:22, 'Thiago Koch Martins' via Vagas <
***@***.***> escreveu:

**Comment by Fredpeixoto** [comment]
Obrigado. Iremos analisar e qualquer coisa, entraremos em contato.

[image: Internit]
*www.internit.com.br
<https://mailtrack.io/link/56fcc9fb79f1d38f9594d6fe45b54de17e7a39e5?url=http%3A%2F%2Fwww.internit.com.br%2F&userId=393368&signature=1f3200fd61a7f81d>**www.incenadigital.com.br
<https://mailtrack.io/link/dc2cf8ce7d7f12fc83ad6f4b2414dc862ed6b274?url=http%3A%2F%2Fwww.incenadigital.com.br%2F&userId=393368&signature=418f39e97039f3ee>*
 RJ
<https://mailtrack.io/link/4543b83756e13a2ea6c970ef52ff164083ea6354?url=https%3A%2F%2Fwww.google.com%2Fmaps%2Fplace%2FR.%2BItaperuna%2C%2B100%2B-%2BP%25C3%25A9%2BPequeno%2C%2BNiter%25C3%25B3i%2B-%2BRJ%2C%2B24240-070%2F%40-22.8961089%2C-43.1073818%2C17z%2Fdata%3D!3m1!4b1!4m5!3m4!1s0x9983f238c0e803%3A0x36d8501864605205!8m2!3d-22.8961089!4d-43.1051931&userId=393368&signature=882517d6c09d3faa>
  SP
<https://mailtrack.io/link/9353631275f449d6381b623b0a1617b3c931049f?url=https%3A%2F%2Fwww.google.com%2Fmaps%2Fplace%2FRua%2BNorma%2BPieruccini%2BGiannotti%2C%2B141%2B-%2BV%25C3%25A1rzea%2Bda%2BBarra%2BFunda%2C%2BS%25C3%25A3o%2BPaulo%2B-%2BSP%2C%2B01137-010%2Fdata%3D!4m2!3m1!1s0x94ce580ebf4681b1%3A0xbc9940a345bbe3e6%3Fsa%3DX%26ved%3D2ahUKEwjm9rTIpdvkAhUcK7kGHZ-bDkEQ8gEwAHoECAoQAQ&userId=393368&signature=fa8fdad9bab335e0>
*Frederico
Peixoto*
Diretor Comercial
***@***.***
(21) 2621-7788 <+55212621-7788> | (21) 98123-2303 <+552198123-2303>
[image: Acompanhe a Incena no Facebook]
<https://mailtrack.io/link/8847141c56cb44ef5c856ee85b486b796f9020dc?url=https%3A%2F%2Fwww.facebook.com%2Fincenadigital&userId=393368&signature=40d1329da8619eeb>
[image:
Acompanhe a Incena no Facebook]
<https://mailtrack.io/link/ef8478f8c220ee1225a40904e3175d1b0c12953a?url=https%3A%2F%2Fwww.instagram.com%2Fincenadigital%2F&userId=393368&signature=135986f8e165744b>
[image:
Siga-me no Linkedin]
<https://mailtrack.io/link/1a83336cf29b62cd43caa21b1bcc1c986de0e7a5?url=https%3A%2F%2Fwww.linkedin.com%2Fin%2Ffredericopeixoto%2F&userId=393368&signature=9d503b476ca1e07f>


Em ter., 19 de dez. de 2023 às 09:57, 'Pedro Cardoso' via Vagas <
***@***.***> escreveu:

**Comment by KaianDev** [comment]
Currículo enviado.

**Comment by ggualbertosouza** [comment]
Currículo enviado! Aguardo resposta

**Comment by PedroHenriqueMG** [comment]
Currículo enviado, Aguardo retorno

**Comment by RenatoCDev** [comment]
Currículo enviado. Estou à disposição.

**Comment by NTN1789** [comment]
currículo enviado

**Comment by joao160197** [comment]
Currículo enviado

**Comment by gvao** [comment]
Currículo enviado!

**Comment by edsonaraujoneto** [comment]
Currículo enviado!

**Comment by Apolinar1o** [comment]
curriculo enviado

**Comment by JoseCarlosBarbosa** [comment]
currículo enviado !

**Comment by edukleber100** [comment]
Currículo enviado!

**Comment by MarcioBADias** [comment]
Currículo enviado!

**Comment by joao160197** [comment]
Enviado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
