### ISSUE TITLE
[Remoto] Front-end / Full Stack Node Sênior na JCal Consultoria

### ISSUE THREAD

**Issue by Claudiaantunesdelima** [frontendbr/vagas#7954]
Oportunidades 👇🏻

Desenvolvedor Full-stack Sênior 
Desenvolvedor Backend Sênior 
Desenvolvedor Front-End Sênior 

Estamos em busca de um(a) profissional, para realizar as seguintes atividades:

🔸Atuar como Desenvolvedor Full Stack  em produtos digitais;
🔸Criar documentações técnicas para mapeamento de processos do produto;
🔸Auxiliar o restante do time no desenvolvimento de novas features

Requisitos:

🔸Ensino Superior Completo em Ciência da Computação, Análise e Desenvolvimento de Sistemas, Tecnologia da Informação ou áreas correlatas;
🔸 Conhecimento em Frameworks de Front End, Node.JS, TypeScript e Banco de Dados;
🔸Desejável conhecimento em CI/CD e Arquitetura em nuvem;
🔸Desejável no mínimo 4 anos de experiência na área de Desenvolvimento de Software;
🔸Inglês será um diferencial;
🔸Habilidades de comunicação verbal e interpessoal;
🔸 Planejamento e Organização para trabalhar remoto;

Outras informações:

✨Modelo de Contrato: CLT e/ou PJ
✨Horário: de segunda a sexta-feira no horário comercial

✨ O que te oferecemos de benefícios como PJ:

Trabalho Remoto, com idas esporádicas ao escritório;
Estacionamento (conforme disponibilidade);
Refeitório no local.
✨O que te oferecemos de benefícios como CLT:

▶️Vale-transporte
▶️Estacionamento (conforme disponibilidade)
▶️Plano de Saúde sem custo da mensalidade ao colaborador, com coparticipação de exames e consultas
▶️Plano Odontológico com coparticipação de mensalidade
▶️Seguro de vida sem custo para ao colaborador
▶️Vale alimentação/refeição flexível
Convênio Farmácia
▶️Remuneração compatível ao mercado
Parceria SESC
▶️Banco de Horas Flexível – feriados e datas comemorativas (conforme política interna)
▶️Day Off – Profissional da saúde
Programa saúde física - TotalPass
Auxílio Creche (conforme política interna)
▶️ Faixa Salarial: será avaliado conforme modelo contratual (CLT ou PJ), vide faixa anunciada.

Salário para Full-Stack 👇🏻
Tipo de vaga: Tempo integral, Efetivo CLT ou PJ

📌Salário CLT : R$8.000,00 - R$10.000,00 por mês mais benefícios
Remuneração PJ: até R$ 15.000,00 (vide considerações no modelo PJ)

Benefícios:

▶️Assistência médica
▶️Assistência odontológica
Auxílio-creche
▶️Convênios e descontos comerciais
▶️Estacionamento gratuito
▶️Seguro de vida
▶️Trabalho remoto
▶️Vale-alimentação
▶️Vale-refeição
▶️Vale-transporte

Horário de trabalho:👇🏻

De segunda à sexta-feira
Turno de 8 horas
Tipos de pagamento adicional:

▶️13º salário

#backend 
#fullstack 
#frontend 
#devs
#dev 
#senior
#tecnologia 
#ti
#nodejs 
#javascript 
#typescript
#linkedinbrasil 

Se inscreva no formulário abaixo

https://lnkd.in/dNf3gtTR

**Comment by guim0** [comment]
Mandei minha candidatura!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
