### ISSUE TITLE
[REMOTO] Dev. Mobile Sr. na Going2

### ISSUE THREAD

**Issue by MariaJuliaRicostiG2** [frontendbr/vagas#7955]
## Nossa empresa

A Going2 é uma startup que nasceu em 2012, com o propósito de levar tecnologia de ponta para todo o Brasil, focada em criar produtos que tenham como premissa, facilitar a vida das pessoas e empresas, através do desenvolvimento de Aplicativos, Sistemas e dos princípios de IOT (internet das coisas). Hoje, além de atender clientes nacionais também oferecemos nossos serviços para clientes internacionais, como por exemplo no Canada, Suíça e Estados Unidos.

## Descrição da vaga

**Atividades**

- Desenvolvimento em React Native, iOS e Android: Proficiência no desenvolvimento de aplicativos móveis utilizando React Native, abrangendo tanto o desenvolvimento para iOS quanto para Android dentro deste framework;
- Design de Arquitetura: Capacidade de arquitetar aplicativos móveis complexos, considerando escalabilidade, desempenho e segurança;
- Colaboração: Trabalhar em estreita colaboração com equipes multifuncionais, incluindo designers de UI/UX, gerentes de produto e outros desenvolvedores para entregar aplicativos móveis de alta qualidade;
- Resolução de Problemas: Identificar e solucionar problemas, otimizar o desempenho e propor soluções inovadoras para desafios técnicos;
- Testes e Implantação: Realizar testes abrangentes de aplicativos para garantir funcionalidade e qualidade antes da implantação nas lojas de aplicativos.

**Requisitos**

- Desenvolvimento em React Native (iOS e Android): Experiência prática sólida no desenvolvimento de recursos para as plataformas iOS e Android utilizando React Native;
- Conhecimento Específico da Plataforma: Familiaridade com diretrizes de desenvolvimento do iOS e Android, APIs e recursos específicos da plataforma relevantes para o React Native;
- JavaScript e TypeScript: Proficiência em JavaScript e familiaridade com TypeScript para um desenvolvimento eficiente em React Native;
- Redux e Context API: Conhecimento e uso de bibliotecas de gerenciamento de estado como Redux e Context API em aplicativos React Native;
- Ferramentas de Depuração: Proficiência no uso de ferramentas de depuração e técnicas específicas de depuração do React Native;
- Aplicações modularizadas: Conhecimento e experiência em projetar e desenvolver aplicações móveis modularizadas com foco em manutenção, escalabilidade e reutilização.
- Firebase: Proficiência nos serviços do Firebase para Autenticação, Analytics e Storage. (Desejável)
- Conhecimento em Desenvolvimento Nativo: Compreensão e experiência em desenvolvimento nativo para dispositivos móveis (iOS ou Android) utilizando Swift, Kotlin, Objective-C ou Java, com foco em funcionalidades e otimizações específicas da plataforma (Desejável)

**Benefícios**

- Ajuda de custo exclusivo para convenio médico e odontológico;
- Convênio com plataforma de idiomas (Fluency Academy);
- Plataforma de treinamento Udemy Business;
- Day-Off de aniversário;
- 15 dias de descanso remunerado;
- Plano de carreira.

**Outras informações**

- Horário: 09h às 18h;
- Remoto;
- Contrato de prazo indeterminado;
- PJ.
- Contratação
- PJ

**Como se candidatar**

Por favor cadastrar através do link: https://going2.vagas.solides.com.br/vaga/334056

#Labels 

**Alocação**

- Remoto

**Regime**

- PJ

**Nível**

- Senior

**Comment by vineckb** [comment]
vaga descontinuada(link quebrado)

**Comment by vineckb** [comment]
Link para candidatura quebrado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
