### ISSUE TITLE
[Cidade] Front-end Developer React/TypeScript.

### ISSUE THREAD

**Issue by thiagoferreira123** [frontendbr/vagas#7957]
**Descrição da Vaga:**

Buscamos um Desenvolvedor Frontend Freelancer com sólida experiência em React, TypeScript, React Query e Zustand para se juntar à nossa equipe em um projeto de 5 meses. Esta é uma oportunidade remota para trabalhar em um projeto inovador, com flexibilidade de horários.

**Responsabilidades:**

1. Desenvolver interfaces de usuário eficientes e reutilizáveis usando React.
2. Implementar funcionalidades complexas com TypeScript, garantindo a tipagem correta e eficiente.
3. Gerenciar estados globais com Zustand e otimizar consultas de dados com React Query.
4. Colaborar com outros membros da equipe para planejar, revisar e melhorar o código.
5. Participar de reuniões de planejamento e retrospectivas.

**Requisitos:**

1. Experiência comprovada em React e TypeScript.
2. Profundo conhecimento em gerenciamento de estados com Zustand.
3. Experiência com otimização de consultas de dados usando React Query.
4. Habilidade para escrever código limpo e documentado.
5. Capacidade de trabalhar de forma independente e colaborar remotamente.
6. Bom entendimento de princípios de design de interface e experiência do usuário.

**Contratação:**

Modalidade: Freelancer
Duração: 5 meses
Localização: Remoto
Como se candidatar:

Envie seu currículo, portfólio e/ou GitHub para contato@dietsystem.com.br. Inclua uma breve descrição de sua experiência com React, TypeScript, React Query e Zustand.

**Comment by gvao** [comment]
Enviado e-mail!

desde já agradeço!

**Comment by thiagoferreira123** [comment]
Obrigado! Candidato encontrado.
