### ISSUE TITLE
[Remoto] Senior FullStack Javascript Developer - idwall

### ISSUE THREAD

**Issue by beaperesp** [frontendbr/vagas#7958]
Faça parte do #dreamteam Idwall.

Nossa missão é construir relações de confiança por meio da tecnologia!

Respiramos inovação, incentivamos um ambiente seguro para compartilhamento de ideias onde todes têm autonomia e sabemos que diferentes pontos de vista enriquecem os nossos produtos.

Se você procura um lugar para crescer exponencialmente e deseja ajudar a construir conexões mais transparentes entre pessoas e empresas #VemSERidwaller

Como será meu dia a dia?

- Essa pessoa é responsável por contribuir no desenvolvimento e evolução tecnológica do nosso backoffice.
- Prezar pela codificação segura e seguindo as melhores práticas de mercado;
- Contribuir com o desenvolvimento de pessoas menos experientes no time e no desenvolvimento de tarefas de backtend e manutenção de aplicações Javascript no time;
- Participar ativamente das cerimônias do time contribuindo com ideias e sugestões;
- Identificar oportunidades de melhorias e propor soluções;
- Entender, compartilhar e documentar processos, fluxos e contribuir para descentralização de conhecimento;
- Garantir a qualidade do código e na excelente experiência dos usuários antes do release produtivo;
- Promover uma cultura de trabalho colaborativo e em equipe.

O que é importante eu dominar?

- Sólida experiência com desenvolvimento Typescript e NodeJS;
- Experiência com banco de dados não relacionais;
- Experiência com ferramentas de versionamento de código;
- Experiência no desenvolvimento de APIs com arquitetura REST;
- Experiência com testes automatizados (unitários, integrações e end-to-end) utilizando frameworks como Jest entre outros;
- Experiência com refactoring de aplicações e pagamentos de débitos técnicos fast pace;
- Conhecimento sobre boas práticas de desenvolvimento de software, ciclo de desenvolvimento de software;
- Experiência em ambientes dinâmicos e digitais, especialmente em startups;
- Vivência com metodologias ágeis de desenvolvimento.

Não é imprescindível, mas vamos curtir se você tiver:

- Experiência com MongoDB;
- Experiência com protocolo de autenticação (OAuth);
- Experiência no desenvolvimento de arquiteturas utilizando Filas como comunicação (RabbitMQ, Kafka, etc);
- Experiência em desenvolvimento utilizando padrões de projetos;
- Experiência com ferramentas de monitoração (Grafana, Datadog, LogRocket);
- Experiência no desenvolvimento de sistemas com alto volume de informações.

Se candidate neste [link](https://idwall.inhire.app/vagas/e66ceb4e-84aa-4150-bfb6-2908a0576649/senior-javascript-developer).

**Comment by MCiappina** [comment]
@beaperesp me inscrevi na vaga!

**Comment by vineckb** [comment]
Link para candidatura quebrado
