### ISSUE TITLE
[Santos - SP] Desenvolvedor Front End Sênior  - Hunter Hunter

### ISSUE THREAD

**Issue by ErickaMB** [frontendbr/vagas#7959]
[Desenvolvedor Front End Sênior] - 100% presencial em Santos, SP.

R$ 10 mil a 17 mil PJ.

Requisitos OBRIGATÓRIOS:
Experiencia de mais de 3 anos em WPF, XAMARI, MAUI ou AVALONIA Sênior ou especialista.
DDD, SOLID, injeção de dependências. Implementar regras de negócios usando conceitos DDD.
Obrigatório ter conhecimento em desenvolvimento de software.
Indispensáveis para o suporte e desenvolvimento de modernos sistemas eletro hidráulicos e para a fabricação de usinas, bem como no posterior atendimento e desenvolvimento de sistemas para agricultura de precisão.
Manutenção da arquitetura do sistema.

Conhecimentos desejáveis:
TDD, BDD, scrum, kanban.

Se tem interesse e com requisitos da oportunidade entre em contato pelo Linkedin informando qual é a oportunidade. [[https://www.linkedin.com/in/erickamarquesb/]](https://www.linkedin.com/in/erickamarquesb/%5D)

**Comment by gvao** [comment]
Enviei uma mensagem pelo LinkedIn!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
