### ISSUE TITLE
[Alemanha] Front-End Developer na Nintendo of Europe

### ISSUE THREAD

**Issue by erickpatrick** [frontendbr/vagas#796]
## Descrição da vaga

- Desenvolver, manter e dar suporte a tecnologias e serviços usados no departamento Online & eCommerce
- Desenvolver e aprimorar o Site da Nintendo e todos os microsites; integração com Contas da nintendo; Compras off-device entre outros
- Manter e dar suporte à implementação de tags e rastreadores do Google Analytics, refletindo a Jornada do Consumidor/Usuário
- Dar suporte aos times de Design e do Projeto de eCommerce

## Local

Frankfurt, Alemanha (apenas presencial)

## Benefícios

- Ticket alimentação (60 euros/mês)
- Auxílio Creche

#### Diferenciais

- Horário flexível (único requisito é estar entre 10h e 15h por ser um horário que todas as subsidiárias Nintendo podem se comunicar)

## Requisitos

**Obrigatórios:**
- Nível superior em Ciências da Computação ou qualificação comparável
- Nível profissional em todos os aspectos da tecnologia, padrões e desenvolvimento web
- Conhecimento profundo em HTML, CSS, JavaScript (Node, jQuery e Vue.js), Bootstrap e design responsivo
- Experiência muito boa em Sistemas de Administração de Conteúdo (CMS) e Sistemas de Rede de Entrega de Conteúdo (CDN)
- Habilidades em inglês obrigatória 
- Habilidades analíticas

**Desejáveis:**
- PatternLab
- Webpack
- Google Analytics
- Google Tag Manager

**Diferenciais:**
- Pelo menos um outro idioma europeu (vocês já sabem português, mas se souberem outro ganha mais pontos ainda)

## Contratação
Equivalente a CLT mas daqui da Alemanha

## Nossa empresa

Graças aos nossos produtos Nintendo Switch™ e Nintendo 3DS™, somos um dos líderes entre os fabricantes de vídeo games e consoles no campo de entretenimento interativo. Nosso intuito é alcançar todos com nossos produtos – independente de idade, gênero ou experiência com jogos. Uma equipe forte e motivada, qualidade superior, novos conceitos, desenvolvimento criativo e implementação de ideias únicas, combinadas com sofisticada estratégia de vendas, permitem-nos surpreender jogadores constantemente com produtos novos e inovativos.

## Como se candidatar

<s>Se estiver interessado nessa posição, por favor, envie email para contato@erickpatrick.net **EM INGLÊS e CV-Carta de apresentação em PDF** (por enquanto é para meu e-mail. A vaga está em seus últimos dias de obrigatoriedade para funcionários da empresa que queiram mudar de setor e pediram para eu divulgar onde eu soubesse/pudesse, mas sem passar emails da empresa ainda)</s>
Use o [formulário nessa página](https://www.nintendo.co.uk/jobportal/pages/en_GB/corporate/career/application/application.jsp?jpt=Web%20Developer%20Frontend&adv=00000012) para se candidatar.

## Labels

- Europa
- Alocado
- Pleno

**Comment by LFeh** [comment]
Muito foda! 😄

**Comment by tfalbo** [comment]
Muito maneiro!!! 

![Mario](https://media.giphy.com/media/3otPoptHYvXtDAqwxO/giphy.gif)

**Comment by erickpatrick** [comment]
Olá pessoal,

A vaga ainda não foi preenchida (embora tenhamos contatado algumas pessoas) e, agora, tem um página própria para aplicação à vaga. Interessados, por favor, inscrevam-se através dela.

https://www.nintendo.co.uk/jobportal/pages/en_GB/corporate/career/application/application.jsp?jpt=Web%20Developer%20Frontend&adv=00000012

**Comment by erickpatrick** [comment]
A vaga já foi preenchida. Desculpem a demora em fechar o tópico.
