### ISSUE TITLE
[Remoto] Front-end Developer Sênior React/TypeScript

### ISSUE THREAD

**Issue by thiagoferreira123** [frontendbr/vagas#7960]
**Descrição da Vaga:**

Buscamos um Desenvolvedor Frontend Freelancer com sólida experiência em React, TypeScript, React Query e Zustand para se juntar à nossa equipe em um projeto de 5 meses. Esta é uma oportunidade remota para trabalhar em um projeto inovador, com flexibilidade de horários.

**Responsabilidades:**

Desenvolver interfaces de usuário eficientes e reutilizáveis usando React.
Implementar funcionalidades complexas com TypeScript, garantindo a tipagem correta e eficiente.
Gerenciar estados globais com Zustand e otimizar consultas de dados com React Query.
Colaborar com outros membros da equipe para planejar, revisar e melhorar o código.
Participar de reuniões de planejamento e retrospectivas.

**Requisitos:**

Experiência comprovada em React e TypeScript.
Profundo conhecimento em gerenciamento de estados com Zustand.
Experiência com otimização de consultas de dados usando React Query.
Habilidade para escrever código limpo e documentado.
Capacidade de trabalhar de forma independente e colaborar remotamente.
Bom entendimento de princípios de design de interface e experiência do usuário.

**Contratação:**

Modalidade: Freelancer

Localização: Remoto
Como se candidatar:

Envie seu currículo, portfólio e/ou GitHub para contato@dietsystem.com.br Inclua uma breve descrição de sua experiência com React, TypeScript, React Query e Zustand.

**Comment by lucianolopezz** [comment]
@thiagoferreira123 mandei meu cv no email.

**Comment by lucasdu4rte** [comment]
@thiagoferreira123 Enviei e-mail! Obrigado.

**Comment by alexandrebekor** [comment]
@thiagoferreira123 Enviado.

**Comment by thiagoferreira123** [comment]
Obrigado! Candidato encontrado.
