### ISSUE TITLE
[Remoto] Front-end Developer na Mission Brasil

### ISSUE THREAD

**Issue by paruckerr** [frontendbr/vagas#7961]
## Mission Brasil

Aqui na [Mission Brasil](https://www.missionbrasil.com.br) estamos construindo algo disruptivo, inovador e gostaríamos que você fizesse parte desse grande desafio que temos pela frente.

## Descrição da vaga

Buscamos pessoas desenvolvedoras que curtam novos desafios, que busquem resolver problemas, entregar tarefas com qualidade, auto-gerenciamento e que tenham boa comunicação.

## Requisitos

**Obrigatórios:**
- Reactjs;
- NextJs ~13;
- Next Auth;
- Vercel;
- Hooks;
- Tailwind;
- Noções de UX;
- Restful API oriented design;

## Como se candidatar

Por favor envie um [e-mail](mailto:eduardo.parucker@missionbrasil.com.br) para  com seu CV anexado - enviar no assunto: Vaga Front-End Developer

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

E-mail para contato em caso de não haver resposta: eduardo.parucker@missionbrasil.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by nittosantos** [comment]
Currículo enviado.

**Comment by guim0** [comment]
Enviado!

**Comment by gabyrodrigues** [comment]
Enviado!

**Comment by gvao** [comment]
Enviado currículo!

**Comment by marcus6n** [comment]
Currículo Enviado! 💻☕

**Comment by guinhotmofc** [comment]
Enviado !

**Comment by BrenoFlaubert** [comment]
Enviado!

**Comment by jotace-br** [comment]
Enviei o currículo, qualquer coisa pode ir no meu LinkedIn (linkado no meu perfil) e podemos conversar mais sobre :)
