### ISSUE TITLE
[REMOTE] Senior React and React Native Developer for OTT SmartTV Project at fuze.cc

### ISSUE THREAD

**Issue by davidsonsimoes** [frontendbr/vagas#7962]
# Senior React and React Native Developer for OTT SmartTV Project

## Position Details
- **Location:** International, Remote, João Pessoa
- **Job Type:** Full-time
- **Model:** Hybrid (with occasional visits to our office in João Pessoa; all travel and accommodation expenses covered by the company)

## About the Role
We are looking for a skilled and experienced Senior React and React Native Developer to join our team on an exciting international OTT project for SmartTV platforms. This role is perfect for those passionate about creating high-quality, scalable, and innovative applications in the TV platform space, with a strong background in React and React Native.

## Key Responsibilities
- Develop and maintain applications for OTT platforms, with a focus on SmartTV.
- Work with cross-functional teams to define, design, and launch new features.
- Ensure applications are performant, high-quality, and responsive.
- Identify and rectify bottlenecks and bugs.
- Contribute to code quality, organization, and automation efforts.

## Requirements
- At least 4 years of professional experience with React Native.
- At least 4 years of professional experience with TypeScript.
- Some experience with React.js.
- Advanced English proficiency for effective communication with American clients.
- Solid understanding of the full mobile development lifecycle.

## Optional Skills
- Experience with video streaming technologies (HLS/Dash).
- Familiarity with shaka-player.
- Experience in developing applications for TV platforms.

## Differentials
- Experience with LG WebOS.
- Experience with Samsung Tizen.

## What We Offer
- Work on international projects using cutting-edge technologies.
- Dynamic, multicultural work environment.
- Competitive salary and benefits package.
- Remote work flexibility.

## Benefits
- 30 days of paid vacation annually.
- Health plan assistance.
- Performance-based year-end bonus.
- English language classes.
- Flexible working hours.
- Company-sponsored bi-monthly trips for team meetings.

## How to Apply
Interested candidates should submit their resume, cover letter, relevant project samples or portfolio links, and salary expectations to davidson.simoes@fuze.cc.

#### Allocation
- Remote

#### Type of contract
- PJ

#### Level
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
