### ISSUE TITLE
[Remoto US] UI/UX Designer na McFadyen Digital

### ISSUE THREAD

**Issue by cesarcardoso-mcfadyen** [frontendbr/vagas#7963]
## About us

McFadyen Digital is the leading advisor and implementer of eCommerce Marketplace solutions. During 15 years of implementing marketplaces, we’ve built dozens of platforms that cumulatively generate billions of dollars of gross merchandise value (GMV). We’re honored to have supported 10% of the Fortune 500 with their digital marketplace initiatives. Over 250 global brands like ABB, AB InBev, ACCO, Albertsons, American Red Cross, American Eagle Outfitters, US Army, US Agriculture Dept, (and many more) have entrusted their digital transformations to McFadyen. We operate global offices across the US, Brazil, and India. McFadyen Digital has been a trusted employer for 35 years and believes that people are the most important part of our company. We’re proud of our Great Place to Work certification.

Learn more about us at our website: www.mcfadyen.com

## Job Description

We are seeking a highly skilled and experienced UI/UX designer with a strong passion for crafting exceptional user experiences. As a Senior UI/UX Designer, you will play a critical role in shaping the visual and interactive aspects of our digital commerce platform. You will work collaboratively with cross-functional teams, including developers, product managers, and other stakeholders, to create intuitive and visually stunning user interfaces that meet the needs of our users and business objectives.

The ideal candidate should possess a deep understanding of the latest design trends and technologies in the world of ecommerce and marketplace. They should have a proven track record of delivering high-quality designs that are both aesthetically pleasing and user-friendly. Additionally, they should be able to work effectively in a fast-paced environment, manage multiple projects simultaneously, and communicate effectively with team members and stakeholders.

This is an exciting opportunity for an experienced UI/UX designer to shape our digital commerce platform. If you're passionate about creating exceptional user experiences and possess the necessary skills, we encourage you to apply and contribute to our business's growth and success.

### Top five Responsibilities
• Conducting user research and gathering insights to inform design decisions.
• Creating wireframes, prototypes, and high-fidelity designs that meet user needs and business goals.
• Collaborating with cross-functional teams, including product managers, developers, and other designers
• Presenting designs and design rationale to stakeholders and incorporating feedback into iterations
• Communicating effectively with team members and stakeholders throughout the design process, including providing regular updates on progress and timelines.

### Additional Responsibilities
• Design wireframes, interactive prototypes, and visual designs for e-commerce and digital marketplace interfaces.
• Participate in workshops, interviews, and design sessions to gather and document business requirements, wireframe UI, and improve work products for clients' applications.
• Collaborate with senior developers to ensure high-quality website responsiveness.
• Create Design systems for UX rich project.

## Qualifications
• Good experience with highly scalable applications.
• Strong knowledge and hands-on experience in Adobe Creative Suite programs (e.g., Figma, XD, Photoshop, Illustrator) to mock-up UI elements.
• Understanding and hands-on experience in responsive design concepts.
• Proficiency in designing and implementing microinteractions in UX.
• Ability to manage time effectively and exceed project delivery commitments.
• Leadership skills for ideation sessions and fostering creative problem-solving.
• Familiarity with user research, usability testing, and integrating social actions through APIs.
• Experience in designing visual aids (wireframes, storyboards, UI flow charts) and staying up-to-date with UI/UX design trends.
• Knowledge of product development design, website designing, SEO for single-page apps.
• Practical knowledge of HTML5, CSS3, and familiarity with JavaScript.
• Proficient in Adobe XD, Figma, InVision serving as the primary design tool, and adept with other design/prototyping tools of choice.

## Expected ecommerce and digital marketplace interface designing skills:
• Experience in designing complex user interfaces for B2B and/or B2C e-commerce platforms, including mobile and native applications.
• Strong understanding of user-centered design principles and best practices in the e-commerce and digital marketplace domains.
• Knowledge of information architecture and interaction design specific to e-commerce platforms, including product catalogs, search functionality, shopping carts, checkout processes, and payment gateways.
• Ability to conduct user research, analyze data, and translate insights into actionable design improvements for e-commerce experiences.
• Familiarity with usability testing methodologies and the ability to gather user feedback to iterate and optimize e-commerce experiences.
• Knowledge of accessibility standards and guidelines to ensure inclusive design for users with disabilities.

## Desired Characteristics in Candidates:
• Effective communication skills for technical and non-technical audiences.
• Analytical and proven problem-solving skills.
• High emotional intelligence (EQ).
• Embraces challenges.
• Team-oriented mindset.

## Basic Qualifications
• Minimum 8-10 years of professional experience in UX roles, with a preference for senior-level positions.
• Demonstrated proficiency in designing and elevating design systems.
• Exceptional system thinking capabilities.
• High standards for visual craft and UI design.
• Effective written and verbal communication skills.
• Proven leadership in designing end-to-end product experiences, from concept to launch.
• Ability to thrive in a highly agile and rapidly iterative environment.

## What we can offer you
• A career with thought leaders who literally wrote the book on Marketplace Best Practices.
• A career in the fast-paced world of retail eCommerce, digital marketplaces and platform businesses.
• A career with first movers who are deploying new business models and strategies worldwide.
• A career in a flat management structure without a rigid hierarchy and bureaucracy.
• A career in a culture that rewards creativity and innovation, risk-taking and teamwork.

## Additional information

Building a great company culture is a top priority for McFadyen Digital. We try to provide the best environment possible for team members - one that treats people the way they want to be treated. Culture Index is one of our tools for enhancing our enjoyable and productive people-focused environment. In order to be considered for this position, please follow this link to fill out a short Culture Index survey https://go.apply.ci/s/UGSEoxjTNs . Please use as many descriptors as possible that pertain to you. There are no right or wrong answers.

### Our Core Values: Client Focus, Owning the Outcome, Adaptable, Caring

Keywords: Technical-lead, frontend-tech-lead, frontend-developer, JavaScript, HTML, CSS, microservices, ui-development, web-development, full-stack, software-architecture, Vue-js, angular-js, react-js, next-js, user-interface-development, performance tuning, front-end-web-design,ux-designer, ui-ux-designer, figma, adobe-xd,Figma-Specialist, Responsive-UI-Designer.

McFadyen’s goal is to ensure that our clients are able to maximize the return on their technology investment by providing better service to their clients, partners and internal teams. At McFadyen we truly believe our employees are our most valuable asset. Across our locations in the US, Brazil and India, we offer a world class work culture that enables top notch delivery for some of the world’s most influential companies.

McFadyen Digital is an Equal Opportunity Employer. All qualified applicants will receive consideration for employment without regard to race, color, age, religion, sex, sexual orientation, gender identity / expression, national origin, disability, protected veteran status, or any other characteristic protected under federal, state or local law, where applicable

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para ccardoso@mcfadyen.com com seu CV anexado - enviar no assunto: Vaga UX/UI

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ
- CLT

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
