### ISSUE TITLE
[São Paulo] Front-end Developer na Guasti tecnologia da informação

### ISSUE THREAD

**Issue by ClovisReis21** [frontendbr/vagas#7965]
> Vaga Semi-presencial

## Guasti

Atuamos no segmento Banking e estamos revolucionando o mercado com nossas soluções.

## Descrição da vaga

Pessoa desenvolvedora Front-End

## Local

Escritório, [São Paulo], [São Paulo], [Vila Olímpia]

## Requisitos

**Obrigatórios:**

- HTML5
- CSS3
- Boa comunicação

**Desejáveis:**

- UI
- Boa Lógica de programação
- Angular

**Diferenciais:**

- SQL

## Benefícios

- VR

**Diferenciais:**
Oportunidade desenvolver seus conhecimentos chegando a full cycle developer, atuando no desenvolvimento front-end com melhores práticas de UI, novos projetos voltados para auxiliar time de backoffice e sustentação de projetos legados.

#### Regime
- CLT

#### Alocação
- Alocado no Santander 3 dias presenciais
- Presencial

#### Nível
- Júnior

## Como se candidatar

Por favor envie um email para bins@guasti.com.br com seu CV anexo e pretensão salarial - enviar no assunto: Vaga Front-end.

### Tempo médio de feedbacks

5 dias

**Comment by gabrielmajeski** [comment]
CV Enviado.

**Comment by peres07** [comment]
enviado!

**Comment by ChrisSerello** [comment]
Currículo enviado!

**Comment by gasech** [comment]
Enviado

**Comment by ClovisReis21** [comment]
Atualizado para issue #7967
Alocado Presencial
