### ISSUE TITLE
[São Paulo] Front-end Developer na Guasti Tecnologia e Informação

### ISSUE THREAD

**Issue by ClovisReis21** [frontendbr/vagas#7967]
## Guasti

Atuamos no segmento Banking e estamos revolucionando o mercado com nossas soluções.

## Descrição da vaga

Pessoa desenvolvedora Front-End

## Local

Escritório, [São Paulo], [São Paulo], [Vila Olímpia]

## Requisitos

**Obrigatórios:**

- HTML5
- CSS3
- Boa comunicação

**Desejáveis:**

- UI
- Boa Lógica de programação
- Angular

**Diferenciais:**

- SQL

## Benefícios

- VR

**Diferenciais:**
Oportunidade desenvolver seus conhecimentos chegando a full cycle developer, atuando no desenvolvimento front-end com melhores práticas de UI, novos projetos voltados para auxiliar time de backoffice e sustentação de projetos legados.

#### Regime
- CLT

#### Alocação
- Alocado no Santander 3 dias presenciais
- Presencial

#### Nível
- Júnior

## Como se candidatar

Por favor envie um email para bins@guasti.com.br com seu CV anexo e pretensão salarial - enviar no assunto: Vaga Front-end.

**Comment by gomes-leonardo** [comment]
Possuo interesse e disponibilidade encaminhei meu cv

**Comment by andd38** [comment]
Infelizmente,não posso participar por conta localização 😕

**Comment by nathaliacp** [comment]
já enviei um email 😄
