### ISSUE TITLE
[São Paulo] Front-End Developer Eicon

### ISSUE THREAD

**Issue by Carlosxell** [frontendbr/vagas#797]
## Descrição da vaga

Procuramos desenvolvedor front-end Pleno/Sênior com força de vontade e pró ativo.

Irá trabalhar no dia a dia com Angular(versões 1.x e 2+), metodologias de projeto e desenvolvimento para desenvolver novas versões de aplicações que estão a muito tempo no mercado e estão sendo revistas. Necessário ser alguém que tenha ótimo desenvolvimento em equipe.

## Local

Trabalho Presencial em horário comercial na Zona Sul de SP. Próximo ao metrô sacomã
[**Endereço**](https://goo.gl/cAQZES)

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ X/dia
- Auxílio creche

## Requisitos

**Obrigatórios:**

- Domínio de HTML5 e CSS3 semânticos;
- Pré processadores CSS (SASS / LESS / Stylus);
- Metodologia BEM para uso do CSS
- Conhecimentos Sólidos em Javascript
- Conhecimentos Sólidos em AngularJS
- Experiência em consumo de API's
- Lógica de Programação
- Experiência em desenvolvimento responsivo e cross-browser;
- Experiência com versionador de código Git;
- Experiência com Gulp / Webpack / NPM
- Frameworks CSS (Bootstrap);
- Scrum

#### Diferenciais

- Conhecimentos em frameworks SPA atuais como: **Angular 2+** , **Vue**
- ES6 / Typescript
- UI /UX
- Testes Unitários
- Node Js

## Contratação

CLT

## Nossa empresa

[Saiba mais](http://www.eicon.com.br)

## Como se candidatar

Entrar em contato através do [Linkedin](https://www.linkedin.com/jobs/cap/view/550946983/?pathWildcard=550946983&trk=job_capjs) ou enviar e-mail para rh@tecnogroup.com.br com assunto 'Cv Front-end'.

## Labels

- Alocado
- CLT
- Vue
- Angular
- Pleno
- Sênior
- Sênior

**Comment by Carlosxell** [comment]
@LFeh , vaga finalizada e desenvolvedores contratados.

**Comment by LFeh** [comment]
Sensacional @Carlosxell !
