### ISSUE TITLE
[SC - joinville] Front-End Developer Pleno na ecossistemadev

### ISSUE THREAD

**Issue by ecossistemadev** [frontendbr/vagas#7971]
## Descrição da vaga

Estamos à procura de um Desenvolvedor Front-End Pleno. Este papel oferece a oportunidade de trabalhar em um ambiente colaborativo, onde a inovação e a excelência técnica são valorizadas. Se você possui habilidades sólidas em React, Typescript e tem experiência com ContextAPI e React Query, esta é uma oportunidade para você contribuir ativamente para o desenvolvimento e aprimoramento contínuo de nossas soluções.

## Local

SC - joinville

## Requisitos

- Experiência sólida com React funcional (utilizando hooks) e domínio do ContextAPI.

- Proficiência com Typescript para desenvolvimento Front-End.
Experiência com React Query para gerenciamento de estado.

- Familiaridade com Git e Github para controle de versão e colaboração em equipe.

- Habilidades comprovadas na resolução de problemas técnicos e otimização de performance.

**Atividades e responsabilidade:**

- Desenvolver, testar e manter código Front-End eficiente, limpo e reutilizável, utilizando React funcional com ênfase em hooks.

- Colaborar ativamente com outros membros da equipe no design e implementação de soluções inovadoras.

- Participar de revisões de código para garantir a qualidade e a adesão aos padrões estabelecidos.

- Contribuir para testes de software, garantindo a robustez e confiabilidade do sistema.

- Identificar e resolver problemas técnicos, além de otimizar continuamente a performance do sistema.

**Mais Informações:**

Observação: Trabalho presencial em Joinville

## Contratação

pj

## Como se candidatar

# [🔗 Clique aqui para se candidatar](https://empregos.dev/vaga/desenvolvedor-front-end-pleno-3769)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 60 dias após cada processo.
E-mail para contato em caso de não haver resposta: 

#### Regime

pj

#### Nível

pleno

**Comment by NicolasOliveira861** [comment]
Olá, vocês não pegam devs pra trabalhar de forma remota?

**Comment by Brenosalv** [comment]
Olá, tenho interesse pois bate bem com minha experiência. Vocês consideram a modalidade remota?

**Comment by felipefialho** [comment]
@ecossistemadev titulo estava fora do padrão, alterei aqui mas nas próximas mantenha no formato correto :)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
