### ISSUE TITLE
[100% Remoto] Front-end Developer na Food To Save

### ISSUE THREAD

**Issue by franriedo** [frontendbr/vagas#7972]
## Sobre a Food To Save

Somos uma startup que nasceu do #inconformismo sobre o desperdício de alimentos no Brasil. Hoje, desperdiçamos 30% de toda a comida produzida, em torno de 15 milhões de toneladas de alimentos por ano, o que nos faz estar presente na lista dos 10 países que mais desperdiçam alimentos no mundo. 

Pensando nisso, juntamos propósito e tecnologia, e então, nasceu a Food To Save, com o sonho de revolucionar o desperdício de alimentos no Brasil e na América Latina, gerando uma reflexão sobre a forma como consumimos alimentos e repensando hábitos que contribuam para um futuro mais sustentável e humano. Criamos uma solução simples e funcional, que conecta os estabelecimentos aos Foodsavers, engajados em combater o desperdício de alimentos. E seu papel é fundamental para seguirmos juntos nessa causa tão urgente e necessária.

É bom para você, é bom para o seu bolso e é bom para o mundo! 🌎

Nossa missão é eliminar o desperdício revolucionando a forma de consumir alimentos. E temos a visão de ser O MOVIMENTO referência na luta contra o desperdício de alimentos, promovendo consumo consciente e sustentável.

## Descrição da vaga

- Criar e manter aplicações mobile em Flutter e aplicações web em React;
- Analisar e corrigir problemas em ambiente de testes e produção;
- Autogerenciar suas próprias atividades e tarefas de acordo com os projetos do time;
- Se comunicar e participar ativamente das discussões e atividades do time;
- Capacidade de discutir em alto nível sobre diversos tipos de problemas do dia-a-dia e da equipe;
- Cuidar da monitoração e logs das aplicações e criar ações para garantir a qualidade;
- Desenvolver e escalar o produto junto com o time de Engenharia;
- Auxiliar e sugerir melhorias.

## Local

100% Remoto

## Requisitos

- Conhecimento em Flutter e React;
- Conhecimento em boas práticas e padrões de projetos (SOLID, DRY, YAGNI, KISS);
- Conhecimento em APIs REST;
- Conhecimento em testes automatizados (unitários e integração);
- Conhecimento em ambiente Web, Android e iOS;
- Proatividade, bom relacionamento interpessoal e comunicação ativa.

## Benefícios

- Assistência Médica SulAmérica Nacional;
- Vale Refeição no cartão Cajú;
- No mês do seu aniversário tem crédito extra no cartão Cajú para ajudar na comemoração;
- Seguro de Vida da Prudential para seu conforto e de quem você ama;
- Auxílio Creche para crianças até 1 ano de idade;
- Convênio com SESC;
- Day off de aniversário;
- 100% Remoto.

## Contratação

Oferecemos CLT como principal estilo de contratação, mas podemos abrir exceção para quem opte por PJ.

## Como se candidatar

Enviar o link do LinkedIn para: rh@foodtosave.com **(Caso o perfil do LinkedIn não esteja completo com as descrições das atividades, pode ser enviado o currículo no lugar)**.

### Nível

- Pleno
- Sênior

### Regime

- PJ
- CLT
- Você escolhe

### Alocação

- Remoto

**Comment by marcus6n** [comment]
Enviei o Linkedin no e-mail! Aguardo seu retorno

**Comment by MathMendesReis** [comment]
Curriculo enviado!

**Comment by gabyrodrigues** [comment]
Enviado!

**Comment by franriedo** [comment]
11/01 - Encerrando a vaga, pois já recebemos bastante perfis (+30).

**Comment by franriedo** [comment]
11/01 - Encerrando a vaga, pois já recebemos bastante perfis (+30).
