### ISSUE TITLE
[São Paulo / Remoto] Front-end Developer na Hepta tecnologia

### ISSUE THREAD

**Issue by GitMateusBruno** [frontendbr/vagas#7973]
> 

## Nossa empresa
Somos a Hepta tecnologia; empresa sediada em Brasília com 31 anos de atuação. Temos contratos com empresas privadas e órgãos públicos, em virtude disso aqui é um espaço amplo de crescimento e desenvolvimento profissional. O time é bastante colaborativo, na verdade colaboração faz parte do nosso valor 🚀

## Descrição da vaga

React (JavaScript or TypeScript) OU  .NET (C#)

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Necessário comprovar experiência como DEV.
- Formação Superior completa em TI (Necessário comprovar)
- Certificação em: Professional Scrum Developer (PSD) ou Certified Scrum Developer (CSD)
- Para o perfil Sênior desejável mais uma em: PSM I, II ou III. Ou CSM; Ou SMC; Ou ASM. (P/ atuar como Scrum Master)
Caso você não possua, concedemos um prazo para adquirir. É importante ressaltar que a empresa não cobre os custos, apenas oferece a oportunidade de estender o prazo.

- IMPORTANTE:
A Hepta presta serviço p/ instituições federais, as exigências que você leu sobre comprovação de experiência, formação superior em TI e certificação são exigências do edital e nós precisamos cumprir.

## Benefícios

- Plano de saúde
- Plano odontológico
- VR ou VA de R$ 21.59/Dia
- Auxílio Home Office

## Contratação

CLT

## Como se candidatar

Por favor envie um email para mateus.sousa@hepta.com.br com seu CV anexado - enviar no assunto: Vaga GIT

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até três dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior

**Comment by SaMatheus** [comment]
Só toma cuidado com essa vaga exigindo N tempo de XP, lei 442-a da CLT fala que não pode fazer isso ;)

**Comment by GitMateusBruno** [comment]
Verdade amigo, obrigado pela sinalização :)

Em seg., 15 de jan. de 2024 às 22:40, Matheus Fernandes de Sá <
***@***.***> escreveu:

**Comment by joao160197** [comment]
Email enviado

**Comment by afabricioa** [comment]
Deviam colocar na descrição da vaga que vocês exigem 5 anos de experiência, ainda mais pra pleno, tá cada vez mais difícil arranjar algo com empresas pedindo 5 anos de experiência pra pleno pagando salário baixissimo.

**Comment by SaMatheus** [comment]
@afabricioa é contra lei exigir mais que 6 meses de XP prévia em uma área.

**Comment by nellysbr** [comment]
Entrei para ver qual era, mas parece que a vaga é um meme pronto, né ?

- Pedindo tempo de experiência prévia, sendo que é contra as normas da CLT.
- Pedindo certificação para atuar como Scrum Master para um dev (totalmente desvio de função, entretanto, a PSD  é um certificação bem bacana de um dev ter).
- Experiência prévia de 5 anos como pleno (Oi ? voltamos para 2010-2015 e eu não estava sabendo).

Gente, vocês precisam para com essas coisas, sério.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
