### ISSUE TITLE
[REMOTO] Full Stack Developer (Full-time) na RBOOH 

### ISSUE THREAD

**Issue by fixarmarketing** [frontendbr/vagas#7975]
## Nossa empresa

A RBOOH.COM.BR conecta de forma rápida e eficiente anunciantes às melhores opções de mídia out-of-home (OOH).

Somos a solução que consolida o sistema comercial dos melhores veículos de mídia OOH, em um só lugar, no menor tempo possível, Oferecendo uma experiência de compra única, com informações ricas e padronizadas dos pontos de exibição.

## Descrição da vaga

. Full Stack Developer na plataforma.RBOOH.com.br
. Spring Boot, React, Node.js
. Nivel Pleno - Sênior
. Atuação remota, Full-time

## Local
REMOTO
A sede da RBOOH fica em Goiás

## Requisitos

**Obrigatórios:**
- Experiência com Java 8 e Spring Boot
- Experiência com React, TypeScript e Node.js
- Experiência em banco de dados relacional e não relacional

**Desejáveis:**
-  Experiência com arquitetura em microsserviços
- Conhecimento em PostgreSQL, MongoDB e RabbitMQ
- Boas práticas de desenvolvimento, OOP e design patterns
- Habilidade em containers (Docker)
- Cloud Servers: Heroku, AWS, CI/CD, etc.
- Controle de Versão (Git)
- Vivência com metodologias ágeis
- Testes unitários, de aceitação e integração
- Conhecimento em boas práticas de UX/UI

**Diferenciais do candidato:**
- Material-UI e Styled Components
- Boa experiência com hooks
- Mobile First
- React Native
- Testes (Jest e Cypress)
- Conhecimento de boas práticas de UI e UX

## Benefícios
- Oportunidades de promoção dentro da equipe com aumento de ganhos

## Contratação
- PJ (com emissão de NF)

## Como se candidatar
- Por favor envie um email para [tamara@rbooh.com.br](mailto:tamara@rbooh.com.br) com seu CV anexado - enviar no assunto: Developer Full Stack Remoto Full-time

## Tempo médio de feedbacks
- Costumamos enviar feedbacks SOMENTE PARA OS SELECIONADOS em até 7 dias após cada candidatura.
E-mail para contato: [tamara@rbooh.com.br](mailto:tamara@rbooh.com.br)

#### Alocação
- Remoto
- Full-time

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

#### Remuneração
- De 7k a 9k

**Comment by guilhermedinardi** [comment]
enviado!

**Comment by MCiappina** [comment]
@fixarmarketing cv enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
