### ISSUE TITLE
[REMOTO] Web Developer na Almaz 

### ISSUE THREAD

**Issue by agencia-almaz** [frontendbr/vagas#7976]
## Nossa Empresa
A Almaz é uma assessoria de marketing e vendas, dedicada a ajudar empresas a prosperar no cenário digital. Com uma abordagem centrada no cliente e uma ampla gama de serviços, nos especializamos em transformar objetivos de negócios em resultados tangíveis. Na Almaz, acreditamos no poder de uma parceria colaborativa, trabalhando de perto com nossos clientes a cada passo do caminho.

## Descrição da vaga
Estamos buscando um Desenvolvedor Web talentoso e entusiasmado para se juntar à nossa equipe. O candidato ideal precisa ter conhecimento técnico em WordPress, HTML e CSS, e será responsável por desenvolver e manter sites e aplicações web de alto nível.

## Local
Remoto

## Requisitos

**Obrigatórios:**
- Proficiência em WordPress, HTML e CSS.
- Experiência com desenvolvimento front-end e back-end.

**Desejáveis:**
- Excelente capacidade de trabalho em equipe.
- Habilidades de comunicação eficazes.

**Diferenciais:**
- Desenvolver e manter sites e aplicações utilizando WordPress, HTML e CSS.
- Trabalhar em colaboração com as equipes de design e desenvolvimento para criar soluções inovadoras e de alta qualidade.
- Garantir a otimização do desempenho e a responsividade dos sites.
- Contribuir para todas as fases do ciclo de desenvolvimento.
- Resolver problemas técnicos e fornecer suporte quando necessário.

## Benefícios
- Contrato de 12 meses com possibilidade de renovação.
- Flexibilidade para gerenciar sua própria agenda, com a expectativa de manter as entregas e participar de reuniões essenciais.
- Trabalho colaborativo e de apoio, com oportunidades de crescimento profissional.

## Contratação
Pessoa Jurídica (PJ), duração de 12 meses com possibilidade de renovação.

## Como se candidatar
Para se candidatar à vaga de Desenvolvedor Web, por favor preencha nosso formulário de inscrição online e compartilhe o link do seu portfólio. Queremos conhecer suas habilidades e experiências!

🔗 https://forms.gle/x3f1SUFE4ofdLdk97

**Comment by andd38** [comment]
Enviado

**Comment by Eu-Pedro0ficial** [comment]
Enviado, aguardo o retorno, Abraços.

**Comment by vanessawin** [comment]
Enviado

**Comment by jp-xaxa** [comment]
Enviado!

**Comment by joyzinhw** [comment]
Boa Noite! mandei.

**Comment by andd38** [comment]
> @agencia-almaz , tem previsão de feedback?

Tbm gostaria de saber, já faz dias que me candidatei pra essa vaga.

**Comment by felipefialho** [comment]
@agencia-almaz Titulo estava fora do padrão, alterei aqui mas nas próximas mantenha no formato correto :)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
