### ISSUE TITLE
[Lisboa/Remoto] Front-End React Developer na JCal Consultoria

### ISSUE THREAD

**Issue by Claudiaantunesdelima** [frontendbr/vagas#7977]
Position:
Front-End React Developer (Trabalhar Remoto em Lisboa) 

Responsibilities:
- We are looking for a profile with strong knowledge and experience working with React.

Requirements:
1. Must have:
- Degree in Technology or Computer Engineering (or similar);
- Experience with React, Typescript, Unit testing (writing and configuration), Gitlab or Github.

2. Nice to have:
- Knowledge in agile methodologies and tools (Scrum/Kanban, Jira);
- Frameworks: Next and Gatsby are a plus

3. Availability:
- Immediate

4. Seniority:
- Advanced or Senior

5. Languages & Soft Skills:
- Fluent in English (minimum B2: Speaking, Writing and Listening)
- Good communication skills
- Team spirit and flexibility to work together with consultants in a different timeline.

6. Location:
- Everywhere.

Location:
- Lisboa / Portugal
- Patrocínio do Visto

Se inscreva no formulário abaixo.👇🏻

https://app.pipefy.com/public/form/X76neJHT

**Comment by rickdouglas** [comment]
no titulo da vaga diz que é remoto mas na localizaçao fala que é em lisboa e que tem patrocinio de visto, minha duvida é: a vaga é realmente remota ou presencial ?

**Comment by rickdouglas** [comment]
Curriculo enviado !

**Comment by marcus6n** [comment]
Curriculo enviado!

**Comment by joao160197** [comment]
Currículo enviado

**Comment by mrangel-jr** [comment]
A vaga é full remoto em Portugal ou pode mudar para 'híbrido' ?

**Comment by Claudiaantunesdelima** [comment]
É Remoto.


________________________________

**Comment by lucasrip** [comment]
sabe dizer se a empresa da vaga tem linkedin ?

**Comment by starlove54** [comment]
Hello I wanted to apply for the front end react developer role. My portfolio is here https://starlovedev.vercel.app/

**Comment by astriel-git** [comment]
Is the position filled? I`m interested.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by devgrunge** [comment]
Currículo enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
