### ISSUE TITLE
[São Paulo)   Front-End Developer Pleno e Sênior   na empresa Verx COnsulting

### ISSUE THREAD

**Issue by Deborag12** [frontendbr/vagas#798]
## Descrição da vaga

Sera alocado por tempo indeterminado nos celites da Verx

## Local

no escritório São Paulo -  regiões da Zona Sul e Alphaville- SP 

## Benefícios

- não possui 

#### Diferenciais

não possui 

**Obrigatórios:**
Conhecimentos necessários:
HTML5, JS, CSS3, VUE.js, Sass, Mocha.
VUE.js por ser um framework novo pode ser complicado encontrar no mercado, porém caso tenha experiencia em AngularJS já ajudaria nessa transição.

## Contratação
PJ 

Por favor envie um e-mail para debora.lima@verx.com.br seu CV anexado - enviar no assunto: Front-End Developer Pleno e Sênior 

## Labels
- Alocado
- PJ
- Pleno
- Sênior

**Comment by kivervinicius** [comment]
Vixi

**Comment by LFeh** [comment]
A contratação vai ser feita pela Verx?

**Comment by Deborag12** [comment]
sim, contratação pela Verx.

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
