### ISSUE TITLE
[REMOTO] Desenvolvedor Front-End Pleno - 1ncrivel Sistemas

### ISSUE THREAD

**Issue by thomasgan** [frontendbr/vagas#7980]
**Nossa Empresa**

Na 1ncrivel Sistemas, uma software house inovadora, valorizamos a criatividade, a colaboração e o compromisso com a excelência. Nosso foco é sempre oferecer as melhores soluções tecnológicas para os desafios de nossos clientes. Procuramos talentos dedicados que possam contribuir para nosso crescimento e sucesso.
 
**Descrição da Vaga**
Buscamos um Desenvolvedor Front-End Pleno, com sólidos conhecimentos em React, TypeScript e Javascript, para se unir à nossa equipe. O candidato ideal terá a responsabilidade de:

**Responsabilidades**
* Codificar layouts responsivos e criar componentes reutilizáveis.
* Manter um alto padrão de qualidade no código e aderir às melhores práticas de desenvolvimento.
* Trabalhar de perto com React, TypeScript e Next.js.
* Implementar projetos responsivos com foco em design adaptativo.
* Colaborar com designers e desenvolvedores para implementar recursos e melhorias.
* Garantir a segurança e eficiência das aplicações.
* Identificar e resolver problemas de desempenho e escalabilidade.
* Participar de revisões de código e testes.

 **Requisitos**
* Proficiência em React e TypeScript.
* Sólidos conhecimentos em Javascript.
* Experiência com Next.js e Tailwind CSS.
* Conhecimento em design responsivo, CSS3 e HTML5.
* Noções básicas de UI/UX.
* Experiência com ferramentas de controle de versões, como GIT.

 **Diferenciais**
* Experiência com Docker.
* Conhecimento em práticas de segurança web.
* Familiaridade com metodologias ágeis, como Scrum ou Kanban.
* Experiência com GCP.

 **Local**
* Remoto

 **Benefícios**
* Bônus por contratação.

 **Regime**
* PJ
 
 **Como se Candidatar**
Os interessados devem enviar seu currículo e carta de apresentação para thomas@nptunnel.com, com o assunto "Candidatura - Desenvolvedor Front-End Pleno".

**Comment by guilhermedinardi** [comment]
enviado!

**Comment by erikbrito** [comment]
enviado!

**Comment by gabyrodrigues** [comment]
enviado!

**Comment by NicolasOliveira861** [comment]
@thomasgan Currículo enviado!

**Comment by Dirosaki** [comment]
Currículo enviado!

**Comment by MathMendesReis** [comment]
Curriculo enviado!

**Comment by guim0** [comment]
Bom dia @thomasgan ! Enviei junto de um link caso não queira baixar, pra acessar no notion 😁
