### ISSUE TITLE
[Remoto] Front-end Developer no Instituto Recôncavo

### ISSUE THREAD

**Issue by antonioscn** [frontendbr/vagas#7983]
## Nossa empresa

Somos um dos principais institutos de Pesquisa, Desenvolvimento e Inovação (PD&I), na área de Tecnologia da Informação e Comunicação (TIC). Especialistas em soluções criativas que impulsionam e interagem com os negócios dos nossos clientes e parceiros.

Atuamos com expertise em diversas áreas, incluindo Inteligência Artificial, Visão Computacional, Indústria 4.0, Internet das Coisas, Projetos Eletrônicos, Soluções Mobile, Cloud Computing, Data Intelligence, Design, Testes e Usabilidade, entre outras vertentes.
Se interessou por nossa cultura e tem vontade de crescer em uma organização com muitos espaços para aprender e contribuir? Então você tem tudo a ver conosco! 

#VemProIRT 🚀💙

## Descrição da vaga

Exemplo: Projeto bazinga em NodeJS, etc.

## Local

- Remoto

## Requisitos
- Experiência em desenvolvimento de aplicações Frontend com Angular;
- Implementação de componentes em Angular;
- Conhecimento desenvolvimento com Javascript, HTML5 e CSS;
- Conhecimentos em integração com web service REST à interfaces gráficas;
- Conhecimentos em segurança de aplicações web;
- Versionamento de software (Git).

**Desejáveis:**
- Conhecimentos em testes unitários;
- Conhecimento Docker.

## Benefícios

- Plano de saúde
- Seguro de vida
- VR e/ou VA

**Diferenciais:**
- Horários flexíveis.

## Contratação

CLT ou PJ (a combinar)

## Como se candidatar

Por favor envie um email para vagas@reconcavo.org.br com seu CV anexado - enviar no assunto: Vaga Front-End

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: vagas@reconcavo.org.br

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior

### Para mais informações e demais vagas acesse www.reconcavo.org.br

**Comment by marcus6n** [comment]
Currículo enviado! Aguardo o Feedback

**Comment by RobsonMT** [comment]
Currículo enviado!
