### ISSUE TITLE
[São Paulo] Front-end Developer Junior na Culttivo Tecnologia

### ISSUE THREAD

**Issue by MilaEstrelinha** [frontendbr/vagas#7984]
## Descrição da vaga
Entender necessidades de negócio e traduzi-las em boas experiências para os clientes e parceiros;
Desenvolver e evoluir sites, interfaces e aplicativos mobile firts para navegadores e aplicativos que se integram com microserviços e APIs;
Implantar e atualizar sites e aplicativos na Microsoft Azure e marketplaces Apple, Androi e Windows;
Criar e manter bibliotecas e componentes reutilizáveis;
Construir sites para campanhas sazonais e eventos. 

## Local

Exemplo: Remoto

## Requisitos

Experiência em React Js, JavaScript, HTML5, CSS3, componentização, design responsivo, modularização e reuso de código, JWT (Jason Web Tokens), Git e consumo de APIs internas e externas. 
Experiência com tecnologias de nuvem em especial Azure
Conhecimento com metodologias ágeis e DevOps
Será um diferencial ter conhecimento de NextJs, Typescript, BFF (Backend For Front-end) WordPress.

**Obrigatórios:**
Vivência experimental em empresas (industrias, consultorias, startups, distribuidoras, serviços, etc)

**Desejáveis:**
- conhecimentos em Typescript e NextJs

**Diferenciais:**
- Nuvem Azure

## Benefícios

- Ajuda de Custo

## Contratação

Cooperado (PJ)

## Como se candidatar

Por favor envie um email para natache@culttivo.com com seu CV anexado - enviar no assunto: Vaga Front-Ent

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 14 dias após cada processo.
E-mail para contato em caso de não haver resposta: natache@culttivo.com

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior

**Comment by antonioln00** [comment]
Boa noite!

Acabei de enviar o meu currículo por e-mail.

**Comment by mendex94** [comment]
Olá, enviei o meu currículo por e-mail.

**Comment by marcus6n** [comment]
Currículo Enviado! Aguardo seu feedback!!

**Comment by Dirosaki** [comment]
Currículo enviado!

**Comment by Wagnerffadm** [comment]
Currículo Enviado! _thanks_

**Comment by mdmath15** [comment]
Currículo enviado!

**Comment by YuriMont** [comment]
Currículo enviado

**Comment by othongonzaga** [comment]
Olá, currículo enviado!

**Comment by HermesonSena** [comment]
Olá ! Currículo enviado !

**Comment by lluismarcello333** [comment]
Olá! Enviei meu currículo por email.

**Comment by MathMendesReis** [comment]
Curriculo enviado!

**Comment by astriel-git** [comment]
Ainda esta aberto?

**Comment by lluismarcello333** [comment]
Boa tarde. Estou sim!

Em ter., 30 de jan. de 2024 às 12:44, Lucas Patricio <
***@***.***> escreveu:

**Comment by joao160197** [comment]
Enviado

**Comment by jhonyfreitasdev** [comment]
Currículo enviado 👌

**Comment by ruanosena** [comment]
Enviei meu currículo, aguardo ansiosamente uma resposta, obrigado

**Comment by Jhaysavi** [comment]
Enviei meu curriculo.

**Comment by miguel-henrique** [comment]
Currículo enviado, obg

**Comment by cesarscfilho** [comment]
Currículo enviado!

**Comment by mwilliamssa** [comment]
Currículo enviadoo

**Comment by Pheph** [comment]
Boa tarde, currículo enviado.

**Comment by leonardosfilho** [comment]
Olá. Currículo Enviado! Aguardo seu feedback!!

**Comment by JoseCarlosBarbosa** [comment]
Boa Tarde, currículo Enviado.
Desde já, agradeço a oportunidade.

**Comment by LukinhaGabriel** [comment]
Currículo Enviado

**Comment by guusfelix2015** [comment]
Enviado

**Comment by Eduardopereira11967484018** [comment]
Enviado

**Comment by GuiiizeeraSouza** [comment]
Currículo enviado.

**Comment by joaoAlves77** [comment]
Currículo enviado.

**Comment by loidpadre** [comment]
Enviado!

**Comment by gustavo-marcialis** [comment]
Currículo enviado! Possuo experiência com Next, React, Typescript, HTML, CSS, WordPress, JavaScript, Bootstrap e Angular.

[Portifólio](https://github.com/gustavo-marcialis)

[LinkedIn](https://www.linkedin.com/in/gustavomarcialis)

[WhatsApp](https://wa.me/+5513982219273)

**Comment by ricardolimaa29** [comment]
Currículo Enviado! Aguardo seu feedback!!

**Comment by Leydilson-Silva** [comment]
Currículo Enviado! Aguardo seu feedback!!

**Comment by axelrammon** [comment]
Currículo enviado
