### ISSUE TITLE
[Remoto] Estágio em React Native na Prodemge

### ISSUE THREAD

**Issue by prodemge-mg** [frontendbr/vagas#7985]
## Nossa empresa

A Prodemge é a empresa de tecnologia da informação do governo de Minas Gerais, com uma trajetória na modernização do setor público.

## Descrição da vaga

Projeto React Native
- Testar a aplicação: Manualmente e com casos de testes
- Realizar manutenções e novas implementações
- Apoiar a equipe quando necessário

## Local

- Remoto [Belo Horizonte]

## Requisitos

**Obrigatórios:**
- Conhecimento em Lógica de Programação
- Conhecimento em Git
- Conhecimento em React Native
- Conhecimento em JS/TS
- Estar cursando faculdade na área de TI 
- Possibilidade de estagiar por até 2 anos 🔴🔴

**Desejáveis:**
- Conhecimento em Java
- Conhecimento em requisições HTTPS

## Benefícios

- A verificar

## Contratação

- Estágio

## Como se candidatar

Por favor envie um e-mail para `prodemge.recrutamento@gmail.com` com seu CV anexado - enviar no assunto: `Vaga Estágio - React Native`

#### Alocação
- 🏢 Remoto

#### Regime
- ⚖️ Estágio

#### Nível
- 👶 Estágio

**Comment by NTN1789** [comment]
currículo enviado , aguardo o feedback !

**Comment by netto0** [comment]
Currículo enviado!

**Comment by EllieKonuma** [comment]
Enviei o meu currículo!✨

**Comment by prodemge-mg** [comment]
Limite de candidaturas atingido.

**Comment by arturxdking** [comment]
[Curriculo Artur Vieira.pdf](https://github.com/frontendbr/vagas/files/14548275/Curriculo.Artur.Vieira.pdf)

**Comment by Wislysantos** [comment]
[Wisly Santos Sousa.pdf](https://github.com/frontendbr/vagas/files/14884458/Wisly.Santos.Sousa.pdf)
