### ISSUE TITLE
[Remoto/LATAM] Junior Full Stack Developer (Part-Time/Internship) - Holly HR

### ISSUE THREAD

**Issue by paulgould** [frontendbr/vagas#7986]
# Junior Full Stack Developer - Part-Time / Internship
## About [Holly HR](https://www.hollyhr.com/) 🌟

Meet Holly HR. We're a vibrant startup from the UK, dedicated to simplifying HR tasks for small and medium-sized businesses. Our philosophy is simple: cut through the jargon and complex features to deliver straightforward, user-friendly solutions. We aim to free up business owners to focus on what they truly love, rather than getting bogged down in HR tasks.

At Holly HR, collaboration takes precedence over hierarchy. We're a close-knit team of professionals from various backgrounds, all united by a shared vision. Our founders are seasoned entrepreneurs with a track record of innovation and success, guiding us towards excellence in all our endeavors.

We're on the lookout for a **Junior Full Stack Developer** based in **LATAM** to join us, initially, on a **part-time/paid internship** basis. This role is perfect for someone passionate using cutting edge technologies to contribute to a web application renowned for its outstanding user experience (UX). It's an opportunity to be part of a team, early on in our story, where your work genuinely makes a difference.
## Tech Stack 🛠

- React
- Next.js (App Router)
- Typescript
- PostgreSQL/MySQL
- Drizzle ORM
- Tailwind CSS/UI
- Vercel/Serverless
## Requirements ✔

- 🌐 Basic English skills (willingness to improve is key!)
- 💻 Solid Typescript/React knowledge
- 🎓 CS background, bootcamp completion, or self-taught (e.g., Odin Project, freeCodeCamp)
- 🚀 No prior work experience needed; we value personal projects and open-source contributions
- 🧠 Curiosity, a passion for learning, and the drive for self-improvement
- 🌱 Self-motivated, capable of independent work and thriving in a team
## Modality 🌍

- Remote work, exclusive to LATAM engineers
## Contract Type 📄

- Part-time contractor role, 10-20 hours/week
- Compensation in BRL 💸
- Aimed at a long-term collaboration 🤝
- Within a global team 👩‍💻👨‍💻
- Flexible hours to accommodate your study schedule and personal commitments

## How to Apply 🚀

- Email [jobs@hollyhr.com](mailto:jobs@hollyhr.com) with your GitHub/CV/LinkedIn/X/Blog
- In the subject, please write: "Junior Full Stack Developer - GitHub"
- Share why you're a great fit for this role and any personal projects or contributions that showcase your skills

For any questions about the role, the team, or the application process, feel free to reach out to [paul@hollyhr.com](mailto:paul@hollyhr.com). We're excited to hear from you and look forward to potentially having you join our team!

**Comment by Jhaysavi** [comment]
I sent my resume.

**Comment by GeisielMelo** [comment]
Application submitted!

**Comment by MathMendesReis** [comment]
Curriculo enviado

**Comment by joaosmendess** [comment]
Application sent!

**Comment by victorborges97** [comment]
Application sent!

**Comment by GeanFilho** [comment]
Application submitted!

**Comment by b4hia** [comment]
application sent!
