### ISSUE TITLE
[Remote] Front-End Developer na Minthouse

### ISSUE THREAD

**Issue by Lucca-C** [frontendbr/vagas#7987]
## Nossa empresa

Somos uma pequena empresa de software sediada em Singapura. Criamos aplicativos móveis, web, nativos e de desktop para várias empresas.

## Descrição da vaga

Estamos buscando um front-end developer talentoso e experiente com conhecimento em React e React Native para se juntar à nossa equipe. O candidato ideal deve ter paixão por criar experiências de usuário excepcionais e possuir habilidades sólidas na criação de aplicativos da Web e aplicativos móveis responsivos.

## Local

Remoto

## Requisitos

**Obrigatórios:**

- Inglês fluente
- 3+ anos de experiência profissional em desenvolvimento frontend
- 3+ anos de experiência em React e React Native
- Forte entendimento de JavaScript/TypeScript e arquitetura frontend
- Experiência com Next.js ou frameworks similares
- Bacharelado em Ciência da Computação ou experiência equivalente
- Disposição para aprender

**Diferenciais:**
- Portfolio
- Otimização da eficiência do front-end

**Diferenciais:**
- Horário de trabalho autogerenciado flexível e trabalho remoto
- Equipe lea, com um ambiente altamente colaborativo

## Como se candidatar

Por favor envie um email para [luccaocamargo@gmail.com](mailto:luccaocamargo@gmail.com) com seu CV anexado - enviar no assunto: Vaga ReactJS

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- Freelance

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by gabyrodrigues** [comment]
Olá. Enviado!

**Comment by joao160197** [comment]
Enviado

**Comment by ChrisFrontDev** [comment]
Enviado. Possuo 8 anos de exp.

**Comment by miguel-henrique** [comment]
Enviado, obg

**Comment by dukex** [comment]
Por favor remover as labels que não se aplicam nessa vaga, exemplo: Junior, Estâgio e Alocado

**Comment by victorbiasibetti** [comment]
Essa vaga é Pj ou Clt?
Nao tem budget definido ou oa beneficios diferente do template padrão?
