### ISSUE TITLE
[Remoto] Frontend Developer Sênior na Coodesh

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#7989]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/desenvolvedor-frontend-senior-181511809?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Nossa startup está na vanguarda da inovação, utilizando Inteligência Artificial para revolucionar a indústria do turismo. Estamos em busca de um Desenvolvedor Frontend Sênior talentoso e apaixonado para se juntar à nossa equipe de especialistas em tecnologia. Se você tem experiência com React e Next.js e está pronto para enfrentar desafios estimulantes, queremos você no nosso time!&nbsp;</p>
<p>Buscamos um profissional que tenha a visão empreendedor, podendo entrar como sócio da startup (Equity), sendo também dono do produto, da empresa e da participação dos lucros.</p>
<p><strong>Responsabilidades:</strong></p>
<ul>
<li>Desenvolver e aprimorar interfaces de usuário altamente responsivas utilizando React e Next.js.</li>
<li>Colaborar estreitamente com designers e outros membros da equipe para converter requisitos de negócios em soluções técnicas viáveis e inovadoras.</li>
<li>Criar e manter componentes reutilizáveis e eficientes para agilizar o desenvolvimento.</li>
<li>Aplicar as melhores práticas de desenvolvimento web, incluindo SEO, acessibilidade e otimização de desempenho.</li>
<li>Integrar APIs externas e serviços web para enriquecer nossas aplicações.</li>
<li>Utilizar Redux para um gerenciamento de estado eficaz e escalável.</li>
<li>Escrever código claro, legível e bem documentado, mantendo um alto padrão de qualidade.</li>
<li>Otimizar o desempenho do aplicativo para garantir uma experiência de usuário excepcional.</li>
<li>Contribuir para revisões de código, promovendo uma cultura de colaboração e aprendizado contínuo.</li>
</ul>
## JJJ Air Software: 
 <p>Em um ambiente tecnológico altamente competitivo é necessário “fazer a diferença”. Para isso, as empresas precisam se reinventar o tempo todo e de forma contínua. Nós atuamos com o  desenvolvimento de soluções em software sob demanda e de elevado grau tecnológico.</p>
<p>A JJJ AIR SOFTWARE é uma empresa que foi incubada dentro do Instituto Tecnológico da Aeronáutica (ITA), fundada no final de 2008 na cidade de São José dos Campos, Estado de São Paulo, Brasil. A Empresa busca oferecer aos Clientes e Parceiros soluções em Tecnologia da Informação (TI) com elevado teor tecnológico.</p><a href='https://coodesh.com/companies/jjj-air-software'>Veja mais no site</a>

 ## Habilidades: 
 - React.js 
- React Native 
- Next.js 
- CSS 
- Javascript
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência sólida em desenvolvimento web com React e Next.js. 
- Profundo conhecimento de HTML5, CSS3 (SCSS preferencial), e JavaScript. 
- Experiência com testes TDD e testes de interface. 
- Domínio de Redux para gerenciamento de estado. 
- Habilidade para criar componentes reutilizáveis e escaláveis. 
- Conhecimento das melhores práticas de SEO, acessibilidade e desempenho web. 
- Experiência com testes TDD e  de interface 
- Capacidade de trabalhar de forma autônoma e em equipe, com excelentes habilidades de comunicação. 
- Compromisso com a qualidade do código, práticas de testes e entrega dentro dos prazos estabelecidos.
## Diferenciais: 
 - Experiência com integração de APIs RESTful e GraphQL. 
- Familiaridade com metodologias ágeis, como Scrum ou Kanban. 
- Experiência com ferramentas de CI/CD. 
- Entusiasmo para aprender e trabalhar com novas tecnologias e frameworks.

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Developer Sênior na JJJ Air Software](https://coodesh.com/jobs/desenvolvedor-frontend-senior-181511809?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
