### ISSUE TITLE
[São Paulo] Front-End Developer na Vex Consulting 

### ISSUE THREAD

**Issue by Deborag12** [frontendbr/vagas#799]
NodeJS + express Framework
 (bonus) experiência com serverless
 MySql / bancos relacionais
 (bônus) banco grafos

Vivência em ambiente agile / scrum
 Autodidata e com alta capacidade de aprendizado
 Inglês internediario

## Local

Escritório, São Paulo - Vila Olímpia

## Benefícios
não possui 

#### Diferenciais

horário flexível, ambiente descontraído

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Node
- 1 ano de experiência com mongodb e express

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um e-mail para:  debora.lima@verx.com.br com seu CV anexado - enviar no assunto: Vaga NodeJS

## Labels

- PJ - Pleno -contratado  pelo cliente

**Comment by Mendrone** [comment]
@Deborag12 Esse email é valido?

**Comment by Deborag12** [comment]
debora.lima@verx.com.br

**Comment by LFeh** [comment]
A contratação vai ser feita pela propria Verx?

**Comment by MatheusWTF** [comment]
Me parece uma vaga de Backend

**Comment by fejaum** [comment]
Benefícios: não possui, dá até um animação em mandar o currículo, era mais fácil omitir o item de Benefícios.

**Comment by paulo-campos** [comment]
@MatheusWTF
Achei o mesmo...

**Comment by LFeh** [comment]
@MatheusWTF Puts, backend total, vou fechar
