### ISSUE TITLE
[REMOTO] - Tech Lead Python na Omie

### ISSUE THREAD

**Issue by Luizeoliveira** [frontendbr/vagas#7991]
## Nossa empresa
A Omie tem como propósito trazer prosperidade para o ecossistema empreendedor brasileiro. Por isso, buscamos por pessoas com mentalidade de crescimento, valorizando perfis que tenham capacidade de adaptação, senso colaborativo e sejam motivadas pela inovação e pelo aprendizado contínuo.
Faça parte da história de uma das empresas de tecnologia que mais cresce no país! 🚀#VempraOmie

## Descrição da vaga

Como Tech Lead, você será responsável por liderar e orientar uma equipe de desenvolvedores para alcançar os objetivos de tecnologia e negócios da empresa. Suas principais responsabilidades incluem:

- Revisão de Código: Garantir a qualidade do código produzido pela equipe, realizando revisões detalhadas e fornecendo feedback construtivo.
- Desenvolvimento e Treinamento: Participar ativamente do desenvolvimento de projetos e prover treinamento e mentoria para os membros da equipe, especialmente em Python, FastAPI, SQLAlchemy, e tecnologias front-end como HTML, CSS, e JavaScript.
- Arquitetura de Sistemas: Desenvolver e manter a arquitetura dos sistemas, garantindo eficiência, escalabilidade e segurança.
- Entendimento de Negócios: Colaborar com outros departamentos para entender as necessidades do negócio e traduzi-las em requisitos técnicos claros e executáveis.

## Local
Remoto (Sem Golpes, 100% Remoto - Contratando nivel Brasil) 

## Requisitos
**Obrigatórios:**

- Formação: Graduação em Ciência da Computação, Engenharia de Software, ou áreas relacionadas.
- Conhecimentos em Backend: Python, FastAPI, SQLAlchemy, AWS (Lambda, CloudWatch, DynamoDB, SQS), API, REST, SQL;
- Conhecimentos em Frontend: HTML, CSS, JavaScript e Vue.js;
- Conhecimento em ferramentas de versionamento de código (GitHub);
- Capacidade de projetar e implementar arquiteturas de sistemas complexos, habilidades avançadas de programação e um bom entendimento de práticas de desenvolvimento ágil;
- Excelente habilidade de comunicação, liderança, e capacidade de trabalhar em equipe. Capacidade de mentorar desenvolvedores e liderar por exemplo;

**Desejáveis:**
- Idiomas: Proficiência em inglês é desejável.
- Certificações em tecnologias relevantes são valorizadas, assim como cursos de liderança e gestão de equipes;

**Diferenciais:**
- Experiência prévia em desenvolvimento de CRM será considerada um diferencial.

## Benefícios
- Aqui na Omie, não nos apegamos mais às nomenclaturas VR, VA e VT. Utilizamos os benefícios flexíveis, que podem ser usados em categorias de educação, saúde, vestuário, seguros, equipamentos e moradia.
- Auxílio-escritório e Auxílio Home office para você melhorar o seu ambiente de trabalho remoto e torná-lo ainda mais confortável.
- Precisa trabalhar presencialmente? Nós temos vale-transporte.
- Para manter a saúde e o bem-estar físico em dia, contamos com Apps parceiros de academias credenciadas.
- Para relaxar e cuidar da saúde mental, temos parcerias com plataformas de terapia e meditação online.
- Auxílio-creche.  
- Descontos exclusivos nas melhores faculdades e instituições de ensino, voltados para cursos de graduação, pós-graduação e MBA.
- Programa de descontos em seguros.
- Parceria com cursos de English in Company.
- Day off de aniversário, para você comemorar como quiser!
- Plano de saúde Amil.
- Plano odontológico Amil Dental.
- Empréstimo consignado via Ali Crédito.
- Seguro de vida.

## Contratação
CLT

## Como se candidatar
Candidatura via Gupy em https://carreirasomie.gupy.io/jobs/6413319. 

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by lucasmonstrox** [comment]
Se lhe interessar, tenho muita experiência com python e segue o link de um projeto https://github.com/lucasmonstrox/PyTibia

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
