### ISSUE TITLE
[Remoto] Front-End Developer na Troupe Tecnologia

### ISSUE THREAD

**Issue by victor-pilotto** [frontendbr/vagas#7992]
## Descrição da vaga

- Criação e manutenção de apps web e mobile;
- Integração do frontend com APIs e microsserviços internos;
- Escrever testes para garantir as funcionalidades já existentes, em conjunto com as novas;
- Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas;
- Construir componentes reutilizáveis - internamente e entre sistemas;
- Participar do processo criativo e auxiliar na construção/elaboração dos sistemas;
- Ajudar a enriquecer a cultura na empresa :)
 
## Local

 - Remoto ou Escritório, Santa Barbara D'Oeste / SP;

## Requisitos

**Obrigatórios:**

- Experiência relevante em front-end
- Experiência com React
  - Hooks
  - ContextAPI
  - Redux
  - Router
  - testing-library
- Bons conhecimento em JavaScript puro e CSS
- Clean code
- Comunicação interpessoal
- Iniciativa
- Autonomia

**Desejáveis:**

- Conhecimento em Typescript
- Conhecimento em bibliotecas Ui
- Conhecimento em styled-components
- Conhecimento em TDD ou testes automatizados
- Performance
- Boas práticas desenvolvimento React
- CI/CD

**Diferenciais:**

- Conhecimento em React Native
- Conhecimento em GraphQL
- Conhecimento em bibliotecas de formulário
- Experiência com Angular (Ionic)
 
## Horário de trabalho

 - Segunda a Quinta das 8h às 17:15 e Sexta das 8h às 16h;
 
## Benefícios

 - Vale alimentação;
 - Plano médico e odontológico;
 - Auxilio home office;
 - Day off no seu aniversário
 - Horário dedicado ao estudo durante expediente;

## Contratação

 - CLT

## Nossa empresa

Uma empresa forte e moderna. Pronta para os grandes desafios!
A Troupe Brasil é reconhecida pela sua capacidade de entregar soluções para problemas dos mais diversos portes. Já são 30 anos oferecendo ao mercado o que há de melhor, sempre trabalhando com foco na viabilidade e retorno ao seu cliente.
Pelo Brasil e pelo mundo, a Troupe tem deixado o legado de grandes parcerias e bons relacionamentos, acumulando testemunhos positivos que lhe garantem seguir investindo para se manter como uma das principais empresas de seu setor.

## Como se candidatar

Por favor envie um email para victor.tecnologia@troupebrasil.com.br com o seu CV anexado 
Enviar no assunto: **Vaga Front-End** e com a pretensão salarial, se possível

**Comment by gabrielmajeski** [comment]
Enviado.

**Comment by VictorGabriel021** [comment]
Enviado

**Comment by isgabriel** [comment]
Boa tarde, CV enviado!!

**Comment by RobsonMT** [comment]
Enviado!

**Comment by netto0** [comment]
Enviado

**Comment by tamires-manhaes** [comment]
enviado!

**Comment by evertonbzr** [comment]
enviado!

**Comment by Jhaysavi** [comment]
Currículo enviado.

**Comment by pedrops244** [comment]
Enviado!

**Comment by edukleber100** [comment]
Enviado!

**Comment by Eduardopereira11967484018** [comment]
Enviado

**Comment by KaikySantos** [comment]
Enviado ✔️

**Comment by Torelli** [comment]
Enviado

**Comment by lucasportella** [comment]
Enviado

**Comment by glealnunes** [comment]
Enviado!

**Comment by joao160197** [comment]
Enviado

**Comment by lucasoliv21** [comment]
Currículo enviado

**Comment by oliveiratullio** [comment]
Currículo enviado!

**Comment by devCaiquedePaula** [comment]
Enviado

**Comment by mynameiskayky** [comment]
Enviado!

**Comment by thais-falbo** [comment]
Enviado!

**Comment by RodrigoSerrasqueiro** [comment]
Currículo enviado

**Comment by joaopaul167** [comment]
Enviado

**Comment by victor-pilotto** [comment]
Obrigado a todos que enviaram o curriculo
