### ISSUE TITLE
[SP - Bela Vista] Front-end Developer na 200DEV

### ISSUE THREAD

**Issue by 151209** [frontendbr/vagas#7993]
> Vaga Remota durante a pandemia

## Nossa empresa

Somos uma consultoria de TI focada em Inovação e Transformação Digital, certificada como “Great Place to Work” atendemos clientes de todos os segmentos e temos parcerias relevantes com fabricantes como IBM, RedHat, Microsoft, Veritas e Pipefy, nosso foco é estabelecer uma parceria forte com o cliente e principalmente com nosso profissional e através de cursos e capacitações promover a carreira. Temos acompanhamento próximo com todos os profissionais. 

## Descrição da vaga

Atuação no desenvolvimento de novas features Front End Angular de novos produtos em times ágeis.
Utilização do Jira para controle dos processos de priorização do backlog e Sprints.
Otimizar aplicações para garantir usabilidade
Atuar no desenvolvelvimento Front-End no código e solução de problemas
garantir que as aplicações funcionem bem em diferentes navegadores e dispositivos com qualidade e consistência

## Local

Híbrido - SP Bela Vista 

## Requisitos

**Obrigatórios:**

Experiência em Angular JS - Desenvolvimento WEB superior a 4 anos, sendo pelo menos 2 anos atunado com ANGULAR.
Desenvolvimento Mobile preferencialmente em FLUTTER. Angular JS e Angular 8+ (RxJS, Componentização, Requests)
Participação das definições de APIs;
Implementação testes para garantir manutenção;
Manter documentação para compartilhamento com o time;
Avaliação, levantamento e discussão de requisitos junto ao time de produtos.

**Desejáveis:**
Conhecimento em GCP

**Diferenciais:**
- projetos opensource

## Benefícios

- Plano de saúde
- Plataforma de curso de inglês 
- ...

**Diferenciais:**

## Contratação

CLT

## Como se candidatar

Por favor envie um email para paloma.oliveira@200dev.com com seu CV anexado - enviar no assunto: Vaga ANGULAR

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até XX dias após cada processo.
E-mail para contato em caso de não haver resposta: feedbacks@empresasuperlegal.com.br

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível

- Pleno
- Sênior

**Comment by vinidotruan** [comment]
Enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
