### ISSUE TITLE
[Remoto] Front-end Vue.js Developer @DefSafe

### ISSUE THREAD

**Issue by Soonas** [frontendbr/vagas#7994]
## Nossa empresa
A DefSafe (defsafe.com) é uma empresa inovadora que atua no segmento de Cibersegurança. Nossa abordagem integra tecnologias de I.A. para proporcionar uma defesa robusta contra as crescentes ameaças cibernéticas enfrentadas pelas organizações. Estamos em um estágio crucial de expansão e estamos à procura de indivíduos talentosos para se juntarem à nossa equipe. Os indivíduos selecionados terão a oportunidade de colaborar com uma equipe de desenvolvedores utilizando uma stack moderna e tecnologia de ponta, trabalhando sob o regime de contratação como pessoa jurídica, com total flexibilidade e liberdade em um ambiente 100% remoto, conectando-se com nossa base operacional no Brasil.

## Local
Remoto

## Requisito necessários:
Javascript, Vuejs, Nuxt, Tailwind e CSS;
Git;
Conhecimento de requisição e consumo de APIs;
Desenvolvimento responsivo;

## Conhecimento desejável:
Prisma ORM, Supabase, AWS;
Desenvolvimento Ágil;

## Diferenciais:
Inglês;
GenIA;
Integração e entrega contínua (CI/CD);

## Contratação
PJ a combinar;

## Como se candidatar
Apenas preencha o formulário: https://forms.gle/dK9rU47FszawvoWH6

## Labels
frontend, vue, nuxt, tailwind, CSS;

#### Alocação
- Remoto;

#### Experiência
- Júnior;
- Pleno;
- Sênior;

#### Regime
- PJ;

**Comment by FelipeG-Almeida** [comment]
Enviado! 🫡

**Comment by andd38** [comment]
Lá em requisitos necessários,está escrito "nuxt" não era pra ser "next" não ???

**Comment by GeisielMelo** [comment]
> Lá em requisitos necessários,está escrito "nuxt" não era pra ser "next" não ???

Nuxt é uma outra lib

**Comment by netto0** [comment]
Enviado!

**Comment by mateus-lanuce** [comment]
Enviado 😊

**Comment by guilhermeSDB** [comment]
> Lá em requisitos necessários,está escrito "nuxt" não era pra ser "next" não ???

NextJS é o framework do ReactJS.
NuxtJS é o framework do VueJS.

A vaga é pra VueJS então esta correto.

**Comment by linspw** [comment]
Enviado ✔️

**Comment by RafaelBerg** [comment]
Enviado

**Comment by danieltinois** [comment]
**Enviado**  😊

**Comment by euotiniel** [comment]
Enviado

**Comment by joaoAlves77** [comment]
Enviado!

**Comment by MathMendesReis** [comment]
> Lá em requisitos necessários,está escrito "nuxt" não era pra ser "next" não ???

podemos dizer que nuxt e o next js do vue, e muito similimar, so que ao invês de usar react, usa o vue como base
