### ISSUE TITLE
[REMOTO] Front-end React na [TQI]

### ISSUE THREAD

**Issue by alvaropsc** [frontendbr/vagas#7995]
## Descrição da vaga
Escrever código limpo, de fácil manutenção, utilizando as melhores práticas de desenvolvimento de software;
Apresentar melhorias nos sistemas existentes e garantir a qualidade nas entregas;
Ajudar e compartilhar sua experiência com os membros da equipe.

## Local
⏰ Horário comercial, 8h diárias, Segunda a Sexta;
🎒 Trabalho 100% remoto.

## Benefícios
**Lista de Benefícios:**
- VA/VR: R$1012 /mês no cartão Flash
- Auxilio Home Office e bônus para melhoria do seu espaço de trabalho;
- Convênio Médico Apartamento e Odontológico sem coparticipação e integralmente custeado pela empresa para o Titular;
- PLR.
- Gympass para você e mais 3 dependentes;
- Seguro de Vida
- Acesso ilimitado a plataforma Udemy para cursos e capacitação;
- Parceria com descontos em faculdades e escolas de idiomas.
- Agenda de eventos internos e externos voltados para o seu Desenvolvimento Profissional e Pessoal.

#### Obrigatórios:
JavaScript, CSS e HTML;
ReactJs, React Router, ContextApi e Hooks;
Jest, Testing Library, Enzyme ou Cypress;
Webpack, Rollup ou parcel;
Criar páginas web responsivas;
Usar e conhecer o que são pré-processadores e padrões de CSS;
O que é Styled Components e seu uso;
Git e como é o Git flow.

## Contratação
- CLT

## Nossa empresa
Que incrível que você está aqui e tem interesse em fazer parte dos nossos times. A TQI é feita para você, sim você que quer ousar sem receio e vivenciar grandes desafios. Você fará parte de times multidisciplinares e de alta performance, em um ambiente descontraído, dinâmico e colaborativo que te proporcionará constantes aprendizados e desenvolvimento.

Aqui, você encontrará liberdade e autonomia, atuando com metodologias ágeis em projetos inspiradores. Sua voz e sua contribuição são muito importantes para nós, para a construção dos nossos produtos e também para nossas tomadas de decisões.

Não tenha receio em pedir ajuda e compartilhar novas ideias, é assim que conseguimos transformar insights em soluções extraordinárias, somos um time e juntos respiramos inovação.

E ainda vamos além do código, aqui você aprende e também tem a oportunidade de ensinar, construir e evoluir, na TQI você será protagonista da sua carreira.

Conheça mais sobre nossa empresa: https://www.tqi.com.br/

## Como se candidatar
Por favor envie um email para **talentos@tqi.com.br** com seu CV anexado - enviar no assunto: "Front - GitHub" ou pelo Whatsapp no link **https://contate.me/monica_tqi**

## Tempo médio de feedbacks
Temos um fluxo de contratação contínua, e TODOS candidatos recebem feedback de forma contínua durante o processo seletivo.

#### Alocação

- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Senior

**Comment by NTN1789** [comment]
Currículo enviado

**Comment by KaikySantos** [comment]
Currículo enviado ✔️

**Comment by JuniorAlvess** [comment]
Currículo enviado.

**Comment by dominguetigs** [comment]
Currículo enviado.

**Comment by devguga87** [comment]
Currículo enviado!!

**Comment by netosouza22** [comment]
Currículo enviado!

**Comment by guim0** [comment]
Boa noite! Enviado!

**Comment by Dirosaki** [comment]
Currículo enviado!

**Comment by lucasportella** [comment]
Currículo enviado!

**Comment by thais-falbo** [comment]
Currículo enviado!

**Comment by RodrigoSerrasqueiro** [comment]
Currículo enviado pelo whatsapp. Aguardo contato.

**Comment by joao160197** [comment]
Enviado

**Comment by Thirki** [comment]
Currículo enviado!

**Comment by jotace-br** [comment]
Enviado 🙏

**Comment by eduardomrigo** [comment]
Currículo enviado 🚀

**Comment by matheussilvacydevs** [comment]
![Currículo enviado] 🚀

**Comment by guilhermeborim** [comment]
Currículo enviado!

**Comment by devgrunge** [comment]
Currículo enviado!

**Comment by gabrielmoofc** [comment]
Enviado!

**Comment by Hoshibi** [comment]
Currículo enviado!

**Comment by felipelssilva** [comment]
Currículo enviado!
