### ISSUE TITLE
[Remoto] Frontend Developer (Júnior) na Coodesh

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#7998]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/junior-frontend-developer-172513604?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Está pronto para iniciar sua carreira em desenvolvimento frontend? Junte-se à nossa equipe como Desenvolvedor Frontend Júnior e faça parte de um projeto sobre medicina e psiquiatria que um cliente nosso, Vitality Medicine, dos Estados Unidos está desenvolvendo.</p>
<p>Detalhes da vaga (2 posições full time):</p>
<ul>
<li>Colabore com nossa experiente equipe de frontend para desenvolver soluções robustas.</li>
<li>Utilize suas habilidades em TypeScript e React.js</li>
<li>Oferecemos treinamento em todas as tecnologias que o candidato irá desenvolver</li>
</ul>
## Green Bay Software Solutions: 
 <p>Somos uma empresa dinâmica de desenvolvimento de software, com um olhar global e clientes espalhados pelo Reino Unido, Europa e América do Norte. Somos uma equipe compacta, mas altamente focada, especializada em entregar soluções de software sob medida com eficiência e precisão. Inspirados por uma mentalidade esportiva, enfatizamos a agilidade, o trabalho em equipe e a superação contínua em nossos projetos. Nossa missão é transformar ideias em realidade tecnológica, atendendo às necessidades específicas de cada cliente com um serviço personalizado e de alta qualidade.</p></p>

 ## Habilidades: 
 - React.js 
- Node.js 
- Typescript
## Local: 
 100% Remoto
## Requisitos: 
 - Paixão pelo desenvolvimento web. 
- Espírito colaborativo de equipe. 
- Conhecimento sobre TypeScript e NextJS ideal mas não obrigatório

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Developer (Júnior) na Green Bay Software Solutions](https://coodesh.com/jobs/junior-frontend-developer-172513604?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by Ruan-Init** [comment]
Candidatura enviada.

**Comment by douglas-yokomizo** [comment]
Feito!

**Comment by netto0** [comment]
Enviado!

**Comment by ruancostacampos** [comment]
Acabei de enviar, olhem com carinho.

**Comment by matheusnff85** [comment]
Aplicado!

**Comment by MathMendesReis** [comment]
candidatura enviada
