### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor Frontend Sr.

### ISSUE THREAD

**Issue by willianjusten** [frontendbr/vagas#8]
## Descrição da vaga

Vaga de desenvolvedor front-end sênior para desenvolvimento de sites e sistemas.
## Local

Alocado: Jardim Botânico, Rio de Janeiro - RJ
## Mais info

Todas as informações e como se candidatar nesse [link](http://www.hugeinc.com/careers/technology/rio-de-janeiro/senior-web-engineer?gh_jid=165536)

**Ps.:** para trabalhar comigo =p - Se falar que conheceu a vaga por mim, ganha 10 pontos o/

**Comment by charlescarrari** [comment]
Já tinha me candidatado. Posso voltar e dizer que foi por você? 👍🏻😄

**Comment by willianjusten** [comment]
ahuahuahuaua acho que sim =)

**Comment by LFeh** [comment]
@willianjusten, fechou essa vaga?

**Comment by willianjusten** [comment]
Cara, essa vaga é cativa, eles sempre estão precisando de gente boa lá. 
Como eu não estou mais lá, deixo a cargo do @caiovaccaro =)
