### ISSUE TITLE
[Florianópolis] Desenvolvedor Full Stack Sênior

### ISSUE THREAD

**Issue by fernandoguedes** [frontendbr/vagas#80]
## Descrição da vaga

Nossa equipe de Produto e Tecnologia está crescendo, estamos em busca de um Desenvolvedor Fullstack Sênior! =D

## Local

Escritório, Florianópolis - Santa Catarina

## Benefícios

- Uma cultura que valoriza o compromisso com a excelência e a persistência para que o ótimo seja ainda melhor;
- Um ambiente de trabalho leve e estimulante, com equipes altamente engajadas pela busca da qualidade e satisfação dos nossos clientes;
- Apoio no seu crescimento e aprendizado, com bolsas de graduação, pós-graduação, curso de inglês in-company e verba para cursos e eventos de aprendizado externos;
- Uma biblioteca corporativa, com a aquisição ilimitada de livros, baseada nas sugestões dos colaboradores;
- Uma área de convivência com puffs para relaxar e instrumentos musicais para fazer aquele som;
- Frutas frescas todos os dias e ginástica laboral;
- Remuneração compatível com mercado e com suas atribuições;
- Além dos benefícios básicos como Vale Alimentação/Refeição, Auxílio Transporte e Assistência Médica.

## Requisitos

**Obrigatórios:**
- Graduação em Análise e Desenvolvimento de Software, Ciências da Computação, Sistemas de Informação ou Desenvolvimento de Sistemas;
- Domínio em arquitetura de APIs RESTFul;
- Experiência backend em NodeJS e disposição para desenvolver em outras linguagens;
- Conhecimento frontend em AngularJS, Grunt, Bower e Jquery, HTML5, CSS (Bootstrap, Material Design, Sass/Less);
- Conhecimento em PHP;
- Experiência com MySQL e banco de dados não relacional;
- Vivência sobre a cultura do desenvolvimento de software ágil (Scrum, Kanban ou XP);
- Conhecimento sobre integração contínua e os conceitos do Git(Hub) como branching, pull-requests, etc;
- Gosto por atuar em um ambiente com foco no cliente, valorização pela comunicação e feedback, auto disciplina, empreendedorismo, autopercepção e autodesenvolvimento, etc.;
- Inglês intermediário.

**Diferenciais:**
- Conhecimentos avançados sobre os serviços da AWS;
- Conhecimentos avançados em NodeJS;
- Conhecimentos avançados em PHP, ORMs e gerenciadores de dependências com Composer;
- Experiência com desenvolvimento de APIs RESTful estáveis, confiáveis e escaláveis;
- Gosto pelo desenvolvimento utilizando técnicas de TDD/BDD;
- Desenvolvimento mobile nativo e/ou híbrido;
- Experiência com integração de meios de pagamento.

## Contratação

CLT

## Nossa empresa

Nosso mundo são as experiências ao vivo e coletivas, e em qualquer atividade que realizamos está o objetivo de entregar mais confiança e mais conveniência. Nosso trabalho é intenso, rápido e envolve muita responsabilidade. Não é fácil, mas nossas conquistas ficam muito mais emocionantes. 

## Como se candidatar

https://blueticket.recruiterbox.com/jobs/fk067a9/

**Comment by fernandoguedes** [comment]
Ajudando a divulgar a vaga de uma empresa que eu deixei! :)

**Comment by LFeh** [comment]
Show!

**Comment by eduardojmatos** [comment]
@fernandoguedes sabe se já preencheu a vaga? Nos avise pra mantermos ou removermos da lista :)

**Comment by fernandoguedes** [comment]
A vaga foi fechada, @eduardojmatos.

**Comment by eduardojmatos** [comment]
@fernandoguedes blz!

**Comment by camilatigre** [comment]
@fernandoguedes 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by fernandoguedes** [comment]
@camilatigre não sei te responder, a vaga que eu divulguei aqui era de uma empresa que eu tinha trabalhado anteriormente.

c) Não tenho certeza
