### ISSUE TITLE
[São Paulo] Front-End Developer Sênior na XP Investimentos

### ISSUE THREAD

**Issue by AcePetrucci** [frontendbr/vagas#800]
## Descrição da vaga

Atuar com desenvolvimento de sites responsivos com foco na experiência dos usuários. Atuar com coleta e análise de requisitos junto aos clientes, aplicação de pesquisas e entrevistas com usuários para entender as suas necessidades, planejamento e aplicação de testes de usabilidade com usuários, elaboração de mockups e protótipos de baixa, média e alta fidelidade, elaboração de documentação técnica e manuais de usuários. Atuar com execução dos projetos com metodologias ágeis. Facilidade de codificar baseado em artefatos de UX/UI como wireframes, refletindo a fidelidade dos elementos.

## Local

Presencial, São Paulo - Itaim Bibi

## Benefícios

- Plano de saúde
- Plano dentário
- R$ 500,00 VR

## Requisitos

**Obrigatórios:**
- Angular 4+ ou React (exp sênior em apenas uma delas)
- Cypress / Jest / Karma e Jasmine
- Redux
- SASS
- Exp com WebSocket

**Desejáveis:**
- Conhecimento de UX e ferramentas de UI
- Ember (para suporte a projeto legado)
- VSTS
- React Native caso se candidate como React
- Ionic 3 caso se candidate como Angular

## Contratação

CLT - R$ 8.500,00

## Como se candidatar

Por favor envie um email para rh@imaginebeyond.com.br com CV ou Portfolio, Linkedin e Git.
Enviar no assunto: Vaga Front-End Sênior [Angular] ou Vaga Front-End Sênior [React].
Por gentileza, citar que a vaga foi indicação de André Petrucci.

## Labels

- Alocado
- CLT
- Sênior

**Comment by renanlara** [comment]
Irada hein!

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
