### ISSUE TITLE
[Belo Horizonte - Presencial] Angular Front-end Developer Pleno - 7.5k a 11k PJ - Minds Digital

### ISSUE THREAD

**Issue by Vitor-TI** [frontendbr/vagas#8001]
> Vaga Remota durante a pandemia

## Nossa empresa

A Minds Digital é uma IDTech especializada em biometria de voz, por meio da nossa inteligência artificial conseguimos autenticar e identificar a sua voz. Com ela as pessoas se tornam únicas, exclusivas e insubstituíveis. Além dessa tecnologia inovadora, trabalhamos também como Outsourcing com a responsabilidade de ajudar desenvolver toda área de TI, com soluções em nuvem para o nosso cliente.

## Descrição da vaga

Como Front-end Developer, você irá atuar em nossa frente de Outsourcing, formado por um time de desenvolvimento que tem o objetivo de trazer soluções para um de nossos principais clientes que possui um sistema de empréstimos. O time atua no modelo presencial no Bairro Savassi em Belo Horizonte/MG no escritório do cliente, desenvolvendo uma relação próxima e colaborativa de oportunidades de criação e resolução de problemas.

Você se dará muito bem se for uma pessoa que procura resolver problemas independente da tecnologia que for utilizar, comunicativa, analítica e que busca aprender e crescer profissionalmente! 

## Local

Atuação no modelo presencial no escritório do cliente no bairro da Savassi/Belo Horizonte.

## Requisitos

**Obrigatórios:**
- Desenvolvimento Front-end Angular 12
- Integrações via Web API
- Javascript, HTML e CSS
- Conhecimento com GIT
- Clean Architecture, SOLID
- Metodologias ágeis, Scrum e Kanban

**Desejáveis:**
- Conhecimento com React
- Inglês Avançado

## Benefícios

- Horários flexíveis;

## Contratação

Proposta inicial entre **R$ 7.500,00 e R$ 11.000,00** (A proposta vai depender da experiência e conhecimentos demonstrados durante o processo seletivo. Desta forma, conseguiremos entender melhor como poderá ser sua contribuição aqui. Procure compartilhar o máximo de informações com a gente e, também, nos perguntar tudo o que for importante para você);

## Como se candidatar

Por favor faça o cadastro por este link: https://rh.minds.digital/jobs/detail/front-end-developer-pleno-30

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

#### Linguagem
- Angular

#### Regime

- PJ

#### Nível

- Pleno

**Comment by lucasramon** [comment]
O link para cadastro colocado na postagem não está funcionando.

**Comment by Vitor-TI** [comment]
> O link para cadastro colocado na postagem não está funcionando.

Opa Lucas, acabei de corrigir o erro, obrigado por avisar!

**Comment by Poeiras** [comment]
Me inscrevi @Vitor-TI  💯

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
