### ISSUE TITLE
[Remote] Mid Front-end Developer - JavaScript- Strider

### ISSUE THREAD

**Issue by Claudiaantunesdelima** [frontendbr/vagas#8002]
USD 3.5k / month
Minimum: 3 years
English: B2

JavaScript
React.js
Angular
Vue.js

Secondary stack
SEO
HTML
CSS
React Native

app.onstrider.com/r/claudiaantunes?job=bWlkLWZyb250LWVuZC1kZXZlbG9wZXItamF2YXNjcmlwdC04YjE0ZTFkZT9yZWZlcnJhbD1jbGF1ZGlhYW50dW5lcw==

**Comment by eduardomrigo** [comment]
Enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
