### ISSUE TITLE
[São Paulo] Front-end Developer na WiserXP

### ISSUE THREAD

**Issue by AGBENITEpers** [frontendbr/vagas#8003]
---

## Nossa empresa

Somos uma worktech que fornece soluções de software para gestão do workplace, pessoas e facilities. Ajudamos clientes globais a otimizarem seus espaços corporativos no dia-a-dia, bem como, a criar ótimas experiências para as pessoas, aplicando tecnologias inovadoras que promovam ambientes produtivos, saudáveis e colaborativos. Ajudamos as maiores empresas do mundo com clientes como Bain Company, Disney, Rabobank, Ingenico, Sicredi, Axa, Europ, dentre outros.

## Descrição da vaga

Desenvolvedor Pleno - Desenvolvimento de Aplicativos Móveis e Web, altamente qualificado e flexível e que busque crescimento profissional e estabilidade em ambiente de trabalho dinâmico e colaborativo

## Local

Flexibilidade de trabalho 100% remoto ou híbrido, com base em São Paulo.

## Requisitos

**Obrigatórios:**
- Excelentes habilidades de comunicação.
- Capacidade de trabalhar de forma independente e em equipe.
- Habilidade para interagir com sócios da empresa, fornecedores internacionais e outros stakeholders
- Experiência comprovada em desenvolvimento de aplicativos móveis e web
- Profundo conhecimento em tecnologias Azure e Microsoft Exchange
- Experiência em integração de APIs, especialmente GraphQL
- Domínio de Flutter e Dart
- Fortes habilidades em C# e Azure Functions
- Nível intermediário de inglês e espanhol é um diferencial.

**Desejáveis:**
- Experiência com desenvolvimento de aplicativos usando SDKs para Microsoft Teams
- Nível avançado de inglês e espanhol é um diferencial.

## Benefícios

- Plano de saúde
- Flexibilidade de horário

## Contratação

- PJ a combinar

## Como se candidatar

Por favor envie um email para vagas@wiserxp.com com seu CV anexado - enviar no assunto: Vaga Desenvolvedor

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: vagas@wiserxp.com

#### Alocação
- Alocado ou Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by AGBENITEpers** [comment]
Obrigado por fechar a vaga. Concluímos o processo na ultima 6ª feira. Desculpe pela demorar em responder
Anderson Benite


De: Felipe Fialho ***@***.***>
Data: quarta-feira, 1 de maio de 2024 às 21:38
Para: frontendbr/vagas ***@***.***>
Cc: agb ***@***.***>, Author ***@***.***>
Assunto: Re: [frontendbr/vagas] [São Paulo] Front-end Developer na WiserXP (Issue #8003)

Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
