### ISSUE TITLE
[Híbrido] Front-End Developer na CTGI.

### ISSUE THREAD

**Issue by rh-ctgi** [frontendbr/vagas#8004]
**Nossa Empresa – CTGI Tecnologia e Gestão** 

A CTGI é uma empresa de Sistemas e Tecnologia de Informação aplicados à produtividade e competitividade das organizações clientes. Atua por meio de competências em tecnologias, sistemas, gestão de projetos, metodologias e processos de negócios. Executa atividades que vão desde a modelagem de uma solução até sua completa implantação e operação transformando as necessidades e planos dos clientes em resultados efetivos. Fundada em 2001, tem sede em São Paulo de onde atende o Brasil todo e projetos no exterior. Veja mais em www.ctgi.com.br. 
A CTGI oferece a seus colaboradores um ótimo ambiente de trabalho e colaboração, com flexibilidade de horário, atividades híbridas (home-office, coworking e escritório), supervisão feita diretamente por profissionais experientes; intenso ambiente de inovação e aprendizado prático.  

**Descrição da vaga.**  

A vaga oferecida é para Desenvolvedor-Analista Front End, com conhecimentos de Angular e  familiaridade com mapas e georreferenciamento.  Trata-se de desenvolvimento de plataformas tecnológicas que formam a base de algumas startups que estão sendo criadas. E, por isso, proporcionará boas oportunidades de crescimento técnico e profissional.   

O profissional deve ter conhecimentos em aplicações front-end e Angular, gostar de desenvolvimento, possuir prática em aplicativos web e mobile, APIs e Git. Preferência a candidatos que tenham noções de front-end com mapas e bibliotecas de geoposicionamento. Desejável de 2 a 5 anos de experiência no tema. 

 O desenvolvedor-analista participará de equipe que desenvolve aplicações multicamadas. Aplicará conceitos atuais de arquitetura e desenvolvimento de software. Participará em projeto de inovação em uma plataforma que integra mapas - posicionamento geográfico - com informações cadastrais e analíticas. Contará com orientação direta de profissionais experientes criando oportunidade de aprendizado e consolidação de conhecimentos. 

**Local e horário.** 

Trabalho 75% remoto, 25% presencial (estimado). 
Atividades presenciais no escritório, à Rua Marconi, 34, República, São Paulo – SP.] 
Horário comercial, segunda a sexta, jornada CLT (44hrs semanal). 

**Benefícios:** 

- VA Alelo. 
- VT para os dias de trabalho presencial. 
- Auxílio Home Office para manutenção e melhoria do seu espaço de trabalho. 
- Programa ProEduc da CTGI, de aprimoramento contínuo do profissional, que inclui acesso a plataformas de treinamentos como Alura, Learn (da Microsoft) e outros. Gratuitos para o funcionário. 
- Convênio Médico sem coparticipação e integralmente custeado pela empresa para o Titular.  
- Seguro de Vida 
- Programa de ‘stock options’ (participação em cotas nas startups sendo criadas), para funcionários elegíveis e após alguns anos de atividade na empresa. 

**Requisitos obrigatórios:** 

- JavaScript, CSS, HTML, Angular, Angular Material, Bootstrap, Webpack.  
- Criar páginas web responsivas, conhecer pré-processadores e padrões de CSS. 
- Consumo/uso de APIs em diferentes backends. 
- Git e Git flow (controle de versões). 
- 

**Requisitos desejados.** 

São diferenciais (não obrigatórios), conhecimentos em: 
   - Bibliotecas de geoposicionamento como Leaflet e OpenLayers. 
   - Azure Devops (controle de backlogs, pipeline, etc.). 
   - Tecnologias backend para APIs. 

**Contratação e remuneração.** 

CLT.  
O valor da remuneração será definida em função do perfil e experiência do profissional, seguindo política da empresa que é de remunerar bem seus colaboradores.  

**Como se candidatar** 

Para candidatar-se, envie um e-mail para rh@ctgi.com.br anexando seu CV atual, e responda à pesquisa no link: https://forms.microsoft.com/r/9XGLEukZ4m. 

**Tempo médio de feedbacks** 

Nossa equipe de RH lhe dará um retorno em até uma semana a partir da resposta ao formulário e envio do CV.

**Comment by Eduardopereira11967484018** [comment]
Enviado

**Comment by guilhermeborim** [comment]
Enviado!

**Comment by gustavoocosta** [comment]
Enviado!

**Comment by joaozanqui** [comment]
Enviado!!

**Comment by Lucas-TA** [comment]
Enviado!

**Comment by rh-ctgi** [comment]
Recebimento de CVs encerrado. Em fase de análise de candidatos que enviaram seu CV e preencheram a pesquisa online.
