### ISSUE TITLE
[Remoto] Frontend Angular Developer na Coodesh

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#8005]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/frontend-angular-developer-113144123?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Estamos buscando Frontend Angular para compor nosso time!</p>
<p>O maior e mais divertido curso de inglês do Brasil! Com aulas online ao vivo, o nosso curso de inglês é inteiramente pensado para que sua criança aprenda inglês de verdade. O Kidsa nasce da vontade de contribuir com o desenvolvimento educacional de crianças no Brasil e no mundo, através de aulas de inglês divertidas acessíveis para todas as famílias.&nbsp;</p>
## Kidsa English: 
 <p>O maior e mais divertido curso de inglês do Brasil! Com aulas online ao vivo, o nosso curso de inglês é inteiramente pensado para que sua criança aprenda inglês de verdade. O Kidsa nasce da vontade de contribuir com o desenvolvimento educacional de crianças no Brasil e no mundo, através de aulas de inglês divertidas acessíveis para todas as famílias. A empresa foi fundada em 2014 e teve que se reformular rapidamente em 2020 com o cenário pandêmico. Através de ideais sólidos, criatividade e muita resiliência, foi nesse período que o Kidsa tomou sua forma atual e hoje conta com mais de 10.000 alunos matriculados em sua rede. O nome Kidsa vem da palavra Kids (“Crianças”) com a letra a de alpha, nome da geração nascida entre 2010 e 2020, conhecida por ser a primeira geração 100% nativa digital da história. São essas crianças e suas famílias, alinhadas com o mundo digital, que fazem parte da nossa comunidade propagadora de conhecimento.</p>
</p>

 ## Habilidades: 
 - Javascript 
- Angular 
- HTML 
- CSS
## Local: 
 100% Remoto
## Requisitos: 
 - Conhecimento em HTML, CSS, Javascript 
- Conhecimento e/ou experiência em Angular
## Diferenciais: 
 - Conhecimento e/ou experiência em typescript e node.js
## Benefícios: 
 - Férias remuneradas 
- Décimo terceiro
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Angular Developer na Kidsa English](https://coodesh.com/jobs/frontend-angular-developer-113144123?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by HerbertCJ** [comment]
Boa tarde, ainda esta rolando a vaga? Ta congelada no link

**Comment by FrancieleGhizzoni** [comment]
Boa tarde

**Comment by FrancieleGhizzoni** [comment]
Boa tarde pessoal, vaga temporariamente congelada, eu reabro assim que a empresa avaliar algumas questões.
