### ISSUE TITLE
[Sorocaba e região] Dev. Full Stack Pleno (C#/Angular) 

### ISSUE THREAD

**Issue by MariaJuliaRicostiG2** [frontendbr/vagas#8006]
## Nossa empresa

A Going2 é uma startup que nasceu em 2012, com o propósito de levar tecnologia de ponta para todo o Brasil, focada em criar produtos que tenham como premissa, facilitar a vida das pessoas e empresas, através do desenvolvimento de Aplicativos, Sistemas e dos princípios de IOT (internet das coisas). Hoje, além de atender clientes nacionais também oferecemos nossos serviços para clientes internacionais, como por exemplo no Canada, Suíça e Estados Unidos.

## Descrição da vaga

- Estudo e Validação dos pontos de conexão do backend com as máquinas e equipamentos da fábrica;
- Integração com o frontend da aplicação;
- Liberação dos primeiros módulos para teste/uso do cliente;
- Documentação da aplicação;
- Organização e padronização do código fonte Integração com ERP Datasul (com suporte do consultor do cliente);
- Desenvolvimento de novas funcionalidades e módulos.

## Local
híbrido.

## Requisitos

- Conhecimento em Javascript, Angular, C#, Dotnet Entity, Dotnet Core, Framework Linq e SQL Server.
- Boa comunicação para trabalhar próximo ao cliente;
- Pensamento analítico;
- Experiencia prévia com projetos de integração industrial;
- Vivência em ambiente fabril Integração com ERP Datasul.
- Presencial ao escritório na região de Sorocaba.

## Benefícios

- Ajuda de custo exclusivo para convenio médico e odontológico;  
- Convênio com plataforma de idiomas (Fluency Academy)  
- Day-Off de aniversário;  
- 15 dias de descanso remunerado; 
- Plano de carreira. 

## Contratação

PJ 

## Como se candidatar

Se candidatar no seguinte link: https://going2.vagas.solides.com.br/

## Outras informações:

-  Horário: 09h às 18h;
- Hibrido;
- Contrato de prazo indeterminado;  PJ.

### Nível

- Pleno

### Regime

- PJ

### Alocação

- Híbrido

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
