### ISSUE TITLE
[Remoto] Desenvolvimento Front-End Sênior (React.js e React Native)

### ISSUE THREAD

**Issue by TherecruiterJu** [frontendbr/vagas#8007]
Esta é uma vaga de uma empresa parceira ao qual presto consultoria, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Estamos em busca de Desenvolvimento Front-End Sênior (React.js e React Native)  para compor o time!

Quais serão suas responsabilidades?
Atuar no Desenvolvimento Front-End React.js e Native, em cliente da área financeira.

O que é necessário para participar desse processo seletivo?
Experiência com React Native;
Experiência com ReactJS;
Experiência com Javascript/Typescript, HTML, CSS;
Experiência com Redux (State Management);
Experiência com API Integration (Integraciones con Restful APIs);
Experiência com Testing (Jest);
Conhecimento no idioma espanhol - avançado.

Local:
100% Remoto

Labels
Alocação
Remoto

Regime
CLT
PJ

Envio de CV para [techrecruiterju@gmail.com](mailto:techrecruiterju@gmail.com)

**Comment by erikbrito** [comment]
Poxa, se não fosse o espanhol

**Comment by elrafa-sg** [comment]
enviado :)

**Comment by eduardomrigo** [comment]
Enviado!

**Comment by gustafsilva** [comment]
Enviado
