### ISSUE TITLE
[Remoto] Full Stack Developer + 4XP (Java + Angular) @ Conecta Capital Humano

### ISSUE THREAD

**Issue by raissaime** [frontendbr/vagas#8008]
## Nossa empresa

A Conecta + Recrutamento busca para cliente: Desenvolvedor Fullstack - Java + Angular

## Descrição da vaga

- Atuar no desenvolvimento de soluções corporativas e na criação de componentes compartilhados entre as equipes de desenvolvimento.
- Construir, evoluir e escalar arquiteturas distribuídas e micro-serviços para solucionar problemas específicos;
- Criar e manter soluções de APIs e micro-serviços;
- Realizar atividades inerentes ao desenvolvimento, implantação e monitoramento de sistemas, avaliando os requisitos funcionais e não funcionais recebidos, para desenvolver ou manter funcionalidades dos sistemas, acompanhando e monitorando a implantação e desempenho e utilizando as boas práticas de desenvolvimento.
- Garantir o desenvolvimento do produto de software, mantendo a arquitetura do software, assegurando que o produto seja desenvolvido de acordo com os padrões e estratégias definidos pela empresa, identificando e atuando em problemas e oportunidades de melhoria;
- Buscar a otimização contínua da performance dos sistemas;
- Desenvolver novas funcionalidades seguindo as especificações das histórias e os requisitos de negócio;
- Dar suporte aos softwares já existentes;
- Mensurar e opinar no esforço das tarefas propostas;
- Propor melhorias técnicas das especificações ou softwares;

## Local

Remoto

## Requisitos

- BackEnd: Java 8 ao 17, Quarkus, Maven, Micro Service - Legado: Struts e Thorntail;
- Desejável: Spring Boot Docker e Kubernetes;
- Banco de Dados: Redis, Postgres - Desejável: SQL Server, DB Migration Flyway;
- Mensageria: ActiveMQ/ArtemisMQ -Desejável: Service Bus;
- FrontEnd: Web - Angular 2 - Desejável - React / Moble - Ionic - Desejável - React native, Flutter;
- Ferramentas: GitLab - Desejável (Docker Swarm e Portainer);

## Benefícios

- Vale Alimentação e/ou Refeição R$1.900,00
- Seguro de Vida
- Plano de Saúde Unimed
- Plano odontológico Unidonto
- Previdência Privada 
- PPR (Programa de Participação nos Resultados) 
- Cartão Natal 
- Auxílio Creche 

## Contratação

CLT

## Como se candidatar

Currículos devem ser enviados pra : raissaime@outlook.com com pretensão salarial e CPF.

### Nível

- Pleno

### Regime
- CLT

### Alocação

- Remoto

**Comment by Darkisda** [comment]
Enviado!
