### ISSUE TITLE
[Florianópolis ou Remoto] Front-end Developer na Omega Sistemas

### ISSUE THREAD

**Issue by omegaeducacional** [frontendbr/vagas#8009]
## Nossa empresa

Fundada e mantida por pessoas apaixonadas por tecnologia e educação, a OMEGA é especialista em soluções para gestão educacional.

Nascida em uma época de carência de soluções no setor, a OMEGA desde sua criação vem cultivando um histórico positivo com seus casos de sucesso. [omegasistemas.net.br](omegasistemas.net.br)

## Descrição da vaga

Desenvolver, testar e manter programas de computador com a linguagem definida, baseando-se nas definições fornecidas na fase de análise de sistemas e valendo-se de métodos e técnicas adequados aos equipamentos e aplicações a que se destinam para manutenção e criação de sistemas que atendam os clientes foco, mantendo a competitividade técnica nos nossos sistemas e serviços.

## Local

Nós estamos situados no CIA primavera em Florianópolis. Temos preferência pelo presencial, mas também temos disponibilidade para remoto e semipresencial.

## Requisitos

**Obrigatórios:**
Obrigatório possuir superior completo e no mínimo 4 anos de experiência na função.

## Conhecimentos necessários:

- Conhecimento intermediário/avançado em HTML; CSS e Javascript;
- Conhecimento intermediário/avançado de orientação a objetos;
- Conhecimento intermediário/avançado em React e suas principais bibliotecas e conceitos (react-router-dom, redux, contextApi);
- Conhecimento nos principais design patterns utilizados em javascript;
- Conhecimento intermediaria em UX/UI;
- Conhecimento em ES6 intermediário;
- Conhecimento intermediário/avançado para telas responsivas;
- Nível avançado em conhecimento na stack front-end;
- Conhecimento avançado em análise de requisitos e gerenciamento de projetos;
- Conhecimento avançado em programação funcional;
- Conhecimento intermediário em devops;
- Nodejs avançado;
- Experiência com off line-first

## Benefícios

- Unimed
- Vale Alimentação
- Plano odontologico
- Day Off Aniversario
- Descontos exclusivos com Instituições
- Gympass

## Contratação

CLT/PJ a combinar

## Como se candidatar

https://vagasomegasistemas.vagas.solides.com.br/vaga/365148

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@omegasistemas.net.br

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by YuriBrunetto** [comment]
Enviado!

**Comment by MathMendesReis** [comment]
enviado

**Comment by eduardomrigo** [comment]
Enviado!

**Comment by brunonoatto** [comment]
E-mail enviado, obrigado por compartilhar a vaga.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
