### ISSUE TITLE
[São Paulo] Front-End Developer Jr. na Omnize

### ISSUE THREAD

**Issue by brunobra** [frontendbr/vagas#801]
## Descrição da vaga

Será responsável por transformar a relação dos nossos clientes com seus usuários. É o cara que dará a “vida “ aos Sketchs/layouts, tornando a ferramenta intuitiva e interativa. Nós não estamos procurando apenas um bom programador, mas alguém responsável para o cultivo de uma cultura técnica de excelência, qualidade no código e velocidade. Queremos alguém que consiga trabalhar em equipe, que seja curioso e crítico, que possa refletir, validar projeto e ajudar-nos a avançar para encantar nossos clientes e sermos a melhor plataforma de atendimento do mercado.

## Local

Rua casa do ator, 919 - Vila Olímpia

## Benefícios

- Home Office 1 vez por semana
- Vale refeição
- Vale transporte
- Plano de saúde
- Plano odontológico

#### Diferenciais

- Trabalhar no Cubo (Prédio de Coworking do Itaú)
- Festa Junina e de final de ano
- Jogos (Retropie, dardo, truco, Nerf)
- Traje casual

## Requisitos

**Obrigatórios:**
- Experiência e sólidos conhecimentos em CSS3, HTML5, JavaScript (ES6);
- Pré Processadores CSS (SASS/Less/Stylus)
- Experiência ou conhecimento de Libs de javascript (Jquery, lodash, moment)
- Bons conhecimentos em Git
- Experiência ou conhecimento em metodologias ágeis

**Desejáveis:**
- ReactJS e Redux (ou outras bibliotecas relacionadas a Flux);
- Ferramentas de testes (Jasmine, Karma, PhantomJS, Jest);
- Conhecimento e/ou experiência com Webpack
- Animações em CSS
- Design Patterns

**Diferenciais:**
- React Native
- Conhecer serviços da AWS (EC2, API Gateway, Lambda, CloudFront)
- Conhecimento em Backend;
- Experiência com Teste A/B
- Conhecimentos em TDD e BDD
- Programação funcional

## Contratação

Modelo negociável de contratação (CLT / PJ)

## Nossa empresa

A Omnize é uma plataforma inteligente de atendimento que ajuda empresas a conhecerem seus clientes independente do canal de comunicação. Através de nossa plataforma a empresa pode atender clientes por múltiplos canais (chat, voz, vídeo, mensageiros, redes sociais; em breve, email e PABX), com gestão e histórico unificados - ou seja, mantendo uma identidade única do cliente, independente do canal utilizado. Isso resolve o problema do cliente (satisfaz suas expectativas), do atendente (passa a ter mais conhecimento para atender) e do gestor (tem acesso a inteligência para melhorar seus processos).

## Como se candidatar

Linkedin - https://www.linkedin.com/jobs/view/550979616/
Email - vagas@omnize.com.br

**Comment by laugustofrontend** [comment]
@brunobra  curriculum enviado
