### ISSUE TITLE
[Remoto] Frontend Developer (Sênior) na Coodesh

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#8010]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/frontend-developer-senior-185306101?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>LinkCel </strong>busca <strong>Frontend React</strong> para atuar no time!</p>
<p>Buscamos uma pessoa Frontend Sênior com Sólida experiência desenvolvendo aplicações web majoritariamente com React. Esperamos que tenha conhecimento sobre acessibilidade, semântica, e SEO, e se preocupe com a qualidade e segurança da aplicação, garantindo a excelência em tudo que entregar.&nbsp;</p>
<p>É preciso que a pessoa contratada seja independente, consiga se adaptar rápido, se comunicar com eficiência e entregar com velocidade, além de contribuir com o desenvolvimento de outros integrantes do time. A pessoa terá apoio da liderança técnica para metrificar suas tarefas de forma independente e sem pressões externas, sendo responsável por apresentar as entregas ao time de produto ao final de cada sprint.</p>
<p><strong>Responsabilidades:</strong></p>
<ul>
<li>Você terá autonomia para tomada de decisões técnicas ao desenvolver novas funcionalidades e manter uma aplicação web construída com Next.js que consome uma API REST em Node.&nbsp;</li>
<li>A revisão de código de outros colegas também serão de sua responsabilidade.</li>
<li>Você será responsável por testar sua entrega e garantir o funcionamento correto de acordo com o design e especificação.&nbsp;</li>
<li>Você terá um papel fundamental no crescimento dos negócios de uma start-up, ajudando a desenvolver um produto promissor para os usuários finais, que irá impactar diretamente a vida de inúmeras pessoas no Brasil.</li>
<li>Buscamos um líder com disposição e vontade de aprender em um ambiente ágil, e entregar soluções que sejam motivo de orgulho para qualquer desenvolvedor.</li>
</ul>
<p></p>
## Linkcel Classificados: 
 <p>A Linkcel é  um plataforma de Marketplace,  que nasceu com o ideal de inovar em um mercado já bastante competitivo e com grandes marcas já consagradas. No entanto o seu principal objetivo é propiciar a seus clientes uma experiência diferenciada, com foco nas necessidades de seus usuários, principalmente na segurança, valorização dos produtos e agilidade  de compra ou venda. A Linkcel irá atuar de forma segmentada e sua missão é se tornar referencia em seu segmento para seus potenciais clientes, mas principalmente ajudar pequenos empreendedores que enxergam no comércio de produtos novos e usados uma oportunidade de ter um bom retorno financeiro, oferecendo uma ferramenta especializada que ira potencializar seus negócios.</p></p>

 ## Habilidades: 
 - React.js 
- HTML 5 
- CSS 3 
- Javascript 
- Styled Components 
- Next.js 
- Jest
## Local: 
 100% Remoto
## Requisitos: 
 - Vasta experiência no desenvolvimento de aplicações web responsivas; 
- Domínio em HTML5 e CSS3; 
- Conhecimento sólido em Javascript (ES6) e programação funcional; 
- Domínio em React, incluindo a utilização de Hooks, Context e Styled components; 
- Experiência e habilidade em desenvolver aplicações web com alta fidelidade ao design; 
- Conhecimento em SSR com Next.js; 
- Habilidade de medir a performance e desenvolver soluções de melhoria; 
- Domínio em Git e Git Flow; 
- Entender o protocolo HTTP, o conceito de REST e seus métodos; 
- Conhecimento de boas práticas de desenvolvimento web, padrões de arquitetura e convenções; 
- Conhecimento em teste unitário (React Testing Library, Jest) e de integração; 
- Experiência liderando times e/ou projetos; 
- Capacidade de negociar escopos para garantir qualidade das entregas em tempo; 
- Conhecimento básico em Node e Express.
## Diferenciais: 
 - Conhecimento em Typescript 
- Implementação de ferramentas de automação para medir Web Vitals 
- Experiência com ferramentas como Storybook ou Styleguidist 
- Experiência implementando integrações com GitHub Actions 
- Conhecimento em ferramentas e processos de CI/CD (Jenkins, AWS, Vercel, etc)

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Developer (Sênior) na Linkcel Classificados](https://coodesh.com/jobs/frontend-developer-senior-185306101?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by victorhcosta** [comment]
Mandei um convite no seu Linkedin, como o limite de caracteres é curto não pude enviar as perguntas que tenho para fazer.

**Comment by eduardomrigo** [comment]
Enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
