### ISSUE TITLE
[Remoto - São Paulo/SP] Fullstack PHP Developer na Avantto

### ISSUE THREAD

**Issue by Piulres** [frontendbr/vagas#8012]
## Descrição da vaga

Você irá atuar no desenvolvimento e evolução de projetos em Laravel e Javascript já em andamento, bem como colaborar na concepção de novos a fim de atender as necessidades da organização.

## Local

Remoto / SP

## Requisitos

- Estar a fim de trabalhar com o segmento da aviação;
- Ser curioso e agente de mudança;
- Estar habituado em colocar o cliente no centro de nossas decisões;
- Ser comunicativo e didático;
- Ser resiliente e focado na solução de problemas;
- Vontade de aprender e paixão pelo melhoria contínua;
- Vivência com metodologia e agenda Scrum;

## Requisitos - Tecnologia

- Laravel & Vue
- HTML, CSS, Javascript
- API/REST
- GitHub

Diferenciais:

- UX/UI
- DevOps

## Contratação

PJ a combinar

## Nossa empresa

A Avantto é empresa líder no segmento de compartilhamento de aeronaves executivas. Com mais de onze anos no mercado, a companhia já se tornou uma das maiores do setor na aviação privada. Com um portfólio de mais de 450 usuários ativos, fazemos cerca de 1.400 decolagens mensais (jatos e helicópteros) e alcançamos a média de 6.000 horas de voo anuais.

Nosso propósito é ajudar as pessoas a aproveitar melhor o seu tempo, sempre que precisarem, sem nenhuma preocupação e por uma fração do custo.

Quer fazer parte dessa empreitada?

Temos um sonho em construção, então aqui o aprendizado é constante e você terá pista livre para criar e muitos (muitos mesmo!) desafios. Você trabalhará ao lado de pessoas diversas e talentosas que irão te ajudar a usar todo o seu potencial e gerar o maior impacto positivo possível.

Com espírito empreendedor, cada um de nós protagoniza a sua própria história. Apesar de todos terem autonomia para assumir as rédeas da própria vida, a nossa rotina é intensa por sonharmos grande.

Buscamos profissionais inovadores que sejam movidos por desafios, com senso de dono, comprometidos com o sucesso do projeto e focados em fazer acontecer. Você atuará no nosso time de tecnologia em um projeto estratégico e será um pilar fundamental para o sucesso do mesmo.

Você irá atuar no desenvolvimento e evolução de projetos em PHP e Javascript já em andamento, bem como colaborar na concepção de novos a fim de atender as necessidades da organização.

## Como se candidatar

Por favor envie um email para remigdio@partneravantto.com.br com seu CV anexado - enviar no assunto: Vaga PHP
Portfólio será um grande diferencial. 

### Alocação:
- Remoto

### Contratação:
- PJ

### Experiência
- Pleno
- Sênior
- Especialista

**Comment by pablokaue2004** [comment]
Enviado!

**Comment by Oliveira-Renato** [comment]
Enviado! 👍🏼

**Comment by gustafsilva** [comment]
Enviado 👍

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
