### ISSUE TITLE
[São Carlos] [HIBRÍDO] [PJ] Fullstack Developer Senior (Node.js React) na Tech Recruiter Brazil

### ISSUE THREAD

**Issue by marinanlima** [frontendbr/vagas#8016]
## Nossa empresa

Estamos buscando pessoas incríveis para nossa área de tecnologia. Essa posição irá trabalhar em toda a nossa stack de tecnologia lidando com o time de negócios e operação, conjunto com o time de tecnologia para a resolução de desafios da empresa. 
A pessoa ideal para esta vaga deve estar orientada a construção de um Produto, sendo obcecada pela experiência do cliente, obcecada pela resolução de problemas e que se apaixone pela nossa missão: conectar as marcas e pessoas trazendo a melhor experiência através da tecnologia e nossos produtos e serviços! 
Nós somos uma empresa de alto crescimento com vários processos em criação, ambiente este perfeito para quem almeja ser responsável por fazer parte da estruturação inicial de algo que se tornará gigante no futuro.

## Descrição da vaga

Objetivos e Responsabilidades
Suas atividades incluem:
	•	Desenvolver nossos produtos de tecnologia, atuando com nossa stack em Javascript para resolução dos desafios do negócio.
	•	Atuar conjunto o time de negócios, operações e experiência do cliente para análise do desenvolvimento da tecnologia
	•	Trabalhar em equipe colaborando com os colegas para resolução de problemas.
	•	Planejamento do roadmap da área tecnológica da empresa, aplicando metodologias de projeto, criação de diagramas, interpretação e documentação do sistema desenvolvido durante todo o período de trabalho e acompanhamento do plano definido.
	•	Buscar novas tendências dentro do mercado de tecnologia, e do mercado.

Com o que você irá trabalhar
	•	Algumas de nossas ferramentas para você se interessar:
	•	Next.js, Strapi.js, Prisma.js; MongoDB, Redis, Postgres; Docker; RabbitMQ; GraphQL
	•	GitLab, GitHub Copilot

## Local

[SÃO CARLOS] modelo presencial ou hibrído.

## Requisitos

	•	Conhecimento prévio na stack de JavaScript, em especial Node.js e Next.js.
	•	Se sua especialidade for Backend é requisito conhecimento em arquiteturas de software;
	•	Se sua especialidade for Frontend é requisito conhecimento de Design de UI e UX;
	•	Paixão por trabalhar com Produto, entendendo as necessidades dos nossos clientes;
	•	Desenvolver e trabalhar com integração entre diferentes sistemas de fornecedores;
	•	Pró-atividade e vontade de crescer.

**Desejáveis:**
- conhecimentos em ruby on rails
- conhecimentos em C#

**Diferenciais:**
	•	Experiência em implementação, otimização e condução de processos;
	•	Experiência com ERP (Bling, Omie, Tiny, por exemplo);
	•	Experiência prévia nas áreas de logística e e-commerce.

**Diferenciais:**

	•	Ambiente dinâmico de startup em crescimento acelerado; 
	•	Mentoria e Capacitação continua (1x1) 
	•	Bonificação por resultado de metas 	•	Plano de saúde e odontológico (após 3 meses de contratação)
	•	Ajuda de custo para você e a sua parceira(o) para atividade física 
	•	Acesso a todos os produtos que vendemos para uso individual a preço de custo (bolsas, squeeze, malas de viagem, moletom, caderno, caneta, etc) 
	•	Ambiente de trabalho descontraído e colaborativo. 

## Contratação

PJ 

## Como se candidatar

Por favor envie um email para marina@techrecruiterbrazil.app com seu linkedin e Github - enviar no assunto: Vaga Fullstack-SC

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.
E-mail para contato em caso de não haver resposta: contato@techrecruiterbrazil.app

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
