### ISSUE TITLE
[REMOTO] Fullstack Developer na Eureka Software

### ISSUE THREAD

**Issue by andersoneureka22** [frontendbr/vagas#8019]
## Descrição da vaga

🤔 Qual vai ser seu desafio como desenvolvedor na Eureka Software?
- Programar e dar manutenção no back-end e front-end para aplicações web usando node.js, express.js e react.js;
- Participar ativamente do dia-a-dia de um time ágil, contribuindo para sprints, reuniões de planejamento e entregas contínuas;
- Eventualmente fazer a ponte com stakeholders para esclarecimentos técnicos;
- Colaborar no design e construção de bancos de dados relacionais e NoSQL.

## Local
Remoto.

## Requisitos

🖥 Nossos requisitos técnicos:
- Experiência sólida em Node.Js e React.js;
- Sólidos conhecimentos de JavaScript, HTML e CSS;
- Experiência com WebServices SOAP e REST;
- Experiência com plataformas cloud;
- Experiência em desenvolvimento de soluções escaláveis e de alta performance.

👥 Nossos requisitos comportamentais:
- Bom relacionamento interpessoal e boa comunicação para trabalhar em equipes multidisciplinares;
- Agilidade, ter adaptação rápida em um ambiente dinâmico e adorar pensar nas possíveis soluções de forma criativa;
- Excelentes habilidades de análise e resolução de problemas;
- Ter um perfil flexível, aberto às diversas possibilidades de atuação de uma Software House.

🔎 Desejável:
- Experiência em metodologias ágeis e Git;
- Experiência com docker;
- Experiência com AWS.

💭 Será um diferencial se você tiver:
- Experiência em projetos do segmento de seguros;
- Participado de viradas de grandes projetos para produção.

## Benefícios

- Atuação 100% home-office com horário flexível;
- Day Off no seu aniversário;
- Eureka Sharpen - auxílio educação;
- Recharge - 21 dias úteis para recarregar as energias!;
- Thanks - moeda interna com loja de produtos próprios.

## Contratação

- Nosso processo seletivo é feito em nas seguintes etapas:
 - Triagem de currículos;
 - Entrevista com o time de Pessoas e Cultura e com uma referência técnica;
 - Entrevista final com o gestor do projeto e com o gerente da conta.

## Como se candidatar

Por favor envie um email para **rh@eurekalabs.com.br** com seu currículo anexado.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by MCiappina** [comment]
enviado!

**Comment by tarciosillva** [comment]
Enviado @felipefialho

**Comment by andersoneureka22** [comment]
Agradeço todos que enviaram currículo. Para termos uma avaliação de maior qualidade, estamos encerrando o recebimento de currículos.
