### ISSUE TITLE
[Remoto - Nova Zelândia] Pessoa desenvolvedora: React Front-end/Full Stack Developer na DuskyDots

### ISSUE THREAD

**Issue by lucashfreitas** [frontendbr/vagas#8020]
## Nossa empresa

A [DuskyDots](https://www.duskydots.com) é um creative studio que foi criado por [mim](https://www.linkedin.com/in/lucas-freitas-santos/) e pelo [danillocastilho](https://www.linkedin.com/in/danillocastilhocavalcante/) aqui na Nova Zelândia. Estamos crescendo e procurando uma pessoa desenvolvedora pra fazer parte do nosso time. 

A DuskyDots oferece serviços de consultoria para empresas da Nova Zelandia e Australia e tambem temos produtos internos que estamos desenvolvendo com a meta de lançamento para este ano (_No momento são apenas dois, mas ja tem mais no roadmap._ 

Para saber um pouco mais sobre os tipos de serviços e tecnologias que utilizamos, acesse: https://www.duskydots.com/ e https://www.linkedin.com/company/duskydots (_inclusive um dos projetos que você ira trabalhar será na atualização do nosso site, que é feito em NextJS, Tailwind, SanityCMS, etc_ ).

As principais vertentes de serviço da nossa empresa atualmente é: 

- Produtos criativos: Websites/Campanha publicitárias em 3D, utilizando WebGL, ThreeJS, animações, etc.
- Prestamos consultoria e desenvolvemos projetos/produtos web para resolver demandas de clientes.
- Produtos Web e Mobile: Temos nossos próprio produtos e estamos desenvolvendo dois novos produtos no momento.

## Descrição da vaga

A nova pessoa que fizer parte do time trabalhará diretamente comigo e o Danillo ajudando no desenvolvimento dos novos produtos e tambem em demandas internas.

O nosso time é remoto: Temos um designer que trabalha com a gente no Brasil, temos um escritorio na ilha norte da Nova Zelandia onde eu estou e o Danillo trabalha da Ilha Sul. 

A nossa empresa utiliza uma stack bem moderna e buscamos uma pessoa que tenha experiência ou vontade de aprender. (_Nao deixe de aplicar se nāo souber uma tecnologia em especifico, sabemos que é bastante coisa pra uma pessoa só saber e ser especialista, entao encorajamos a aplicar se não tiver conhecimento em todas)_

Temos testes automatizados (a maoria integração e E2E utilizando playwright, AWS, etc) e utilizamos typescript, react e node. Abaixo os principais componentes da nossa stack:

**- Mobile:** React Native, Expo, Native Wind, React Query
**- Frontend:** ReactJS, NextJS, Tailwind, Zustand, Zod, Shadcn UI, Trpc, etc.
**- Backend:** Usamos Vercel, AWS (_serverless, AWS CDK, dynamo DB, api gateway, etc_), NodeJS (honoJS), TRPC, mySQL
**Databases**: Usamos bastante headless CMS (Sanity), mySQL (planetscale, AWS RDS)
**- CI/CD**: Github Actions
**- Tools:** Figma, Github, Trello for project management, Slack for collaboration

## Ingles

Nossos clientes são internacionais e usam inglês, então valorizamos essa comunicação. Mas relaxa, você pode falar português nas reuniões internas caso se sentir mais confortável, ou podemos manter em inglês caso desejar. Para documentação e comunicação externa, usamos inglês. Lembre-se: não existe inglês perfeito, e estamos aqui para ajudar.

## Como é o dia a dia de trabalho.

Oferecemos modelo de trabalho 100% flexivel. Esperamos que você trabalhe 40h por semana , mas damos autonomia e confiamos nas pessoas do nosso time para que elas mesmos façam o horario e trabalhrem da forma que sao mais produtivas e mais felizes pra conciliar a vida pessoal com trabalho.

Um pouco mais sobre o modelo de trabalho:

1. Utilizamos principalmente trunk based development/gitflow: crie sua branch, crie a PR, CI/CD executa os testes, time revisa e faz o merge e simbora pra proxima. 
2. Somos ageis mas nao utilizamos scrum ou kanban e nao temos meetings e rituais longos para planejamento. Toda semana analisamos todas as prioridades , objetivos e prazos dos projetos e planejamos a semana de trabalho de cada pessoa juntos.
3. Utilizamos slack para comunicação, trello para project management e temos pequenos daily catchups quando necessario caso para re-avaliar as prioridades, responder dúvidas e tambem pra vefificar como estamos progredindo. 
4. Utilizamos um tool interno para fazer track do time e tarefas.
5. Estamos available no slack caso tenha duvidas e tambem estamos sempre disponiveis para fazer uma call quando necessário. (_A nossa timezone é bem diferente, então geralmente nao estamos disponíveis durante certos horarios_)

Valorizamos muito o conceito de ownership. Focamos em estabeler objetivos claros de forma transparente, para que todos do time tenham todas as informacoes que precisam para trabalhar de maneira independente e eficiente. Mesmo estando em um ambiente remoto, essa clareza nos ajuda a trabalhar juntos e alcançar nossas metas com um espírito de colaboração e comprometimento. 

Aqui acreditamos que não existem perguntas idiotas; as únicas perguntas que consideramos assim são as que não são feitas. Então, nunca tenha receio de se comunicar.

## Local

O trabalho será 100% remoto com horário flexivel. A Nova Zelândia está 16 horas a frente do Brasil, serão feitas daily calls com duraçao de 15 minutos diarias e uma vez por semana o time faz um catchup mais longo para planejar as proximas tarefas pra semana. 

## Requisitos

**Obrigatórios:**

- Experiência em dev Typescript, React, Tailwind.

**Desejáveis:**
- Experência com React Native.
- Experiencia com headless CMSs

**Diferenciais:**
- Experiência com React Native.
- Experiência com AWS (cdk, serverless, api gateway, lambda, sqs, etc)

## Benefícios

A nossa empresa é nova e nao está localizada no Brasil, entao infezlimente nao oferecemos nenhum beneficio no momento.

**Diferenciais:**
- Horário 100% flexivel.

## Contratação

PJ

## Como se candidatar

Por favor envie um email para [hello@duskydots.com](mailto:hello@duskydots.com) seu CV anexado - enviar no assunto: Vaga DuskyDots.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by YuriBrunetto** [comment]
Enviado!

**Comment by lucasyule2212** [comment]
Enviado 😄!

**Comment by tarciosillva** [comment]
Enviado

**Comment by MCiappina** [comment]
enviado!

**Comment by denisluft8** [comment]
Enviado

**Comment by netto0** [comment]
Enviado!

**Comment by jotace-br** [comment]
enviado

**Comment by dominguetigs** [comment]
Enviado! 🙏🏻

**Comment by RenanSui** [comment]
Enviado 🎉!

**Comment by lucashfreitas** [comment]
Olá pessoal, obrigado a todos que candidataram. Estamos analisando os curriculos recebidos e entraremos em contato nos proximos dois dias.

Muito obrigado!
