### ISSUE TITLE
[Alphaville/Remote] Front-end Engineer Pleno

### ISSUE THREAD

**Issue by brenooliveira** [frontendbr/vagas#8023]
# Vem ser desenvolvedor aqui no Grupo Primo 🍎

Você terá como responsabilidades desenvolver e manter interfaces de usuário eficientes utilizando Vue.js com JavaScript.
Otimizar aplicações para garantir alta performance e experiência do usuário.
Colaborar estreitamente com a equipe de design para implementar soluções visuais eficazes.
Participar ativamente do ciclo de vida completo de desenvolvimento, desde o design até a implementação.
Identificar e resolver problemas de forma proativa, colaborando com outras equipes conforme necessário.
Manter-se atualizado com as melhores práticas de desenvolvimento front-end e as tendências do setor.

## Requisitos:

 - Experiência comprovada como desenvolvedor front-end, com foco específico em Vue.js(Options API, Composition API, Vuex).
 - Sólido entendimento de HTML, CSS e JavaScript/TypeScript.
 - Familiaridade com bibliotecas e frameworks front-end modernos.
 - Boa comunicação e habilidades de trabalho em equipe.
 - Comprometimento com a entrega de produtos de alta qualidade.

## Diferenciais:
 - Conhecimento em testes automatizados para aplicações Vue.js.
 - Conhecimento em CI/CD
 - Experiência com integração de APIs RESTful.
 - Familiaridade com metodologias ágeis de desenvolvimento.
 - Participação ativa em comunidades de desenvolvedores ou contribuições para projetos de código aberto.

## O que oferecemos:
🍛Vale Refeição e Vale Alimentação disponível no Cartão flexível Swile
🚑 Plano de saúde Amil
🦷 Plano odontológico Bradesco
🏋🏾‍♂️Total Pass
⚠️ Seguro de vida
🚌 Vale Transporte
👶🏽Auxilio creche
📝Acesso as plataformas

## Como se candidatar

[https://www.linkedin.com/jobs/view/3865196373/?capColoOverride=true](https://www.linkedin.com/jobs/view/3865196373/?capColoOverride=true)

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Pleno

**Comment by gtoborges** [comment]
é remoto mesmo @brenooliveira? Lá na descrição da vaga no linkedin tá como presencial

**Comment by pablokaue2004** [comment]
Enviado!

**Comment by KaianDev** [comment]
Curriculo enviado

**Comment by Matheuscara** [comment]
Opa @brenooliveira 
tudo bom?

Vou enviar minha candidatura

**Comment by HenriqueACF** [comment]
@brenooliveira, cv enviado, tem previsao de feedback?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
