### ISSUE TITLE
[Porto Alegre, Rio Grande do Sul, Brazil] Javascript Developer Jr na Coodesh

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#8025]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/javascript-developer-jr-182149210?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>RESPONSABILIDADES</strong></p>
<ul>
<li>Desenvolver em JavaScript;</li>
<li>Solucionar problemas de forma simples e prática;</li>
<li>Contribuir com o time na tomada de decisões técnicas e de fluxo;</li>
<li>Participar ativamente no desenvolvimento de ferramentas com pensamento lógico e crítico;</li>
<li>Criar APIs para integrações entre sistemas.</li>
</ul>
## CyberSec Hunter: 
 <p>Selecionamos os melhores profissionais através de um processo humanizado, com expertise também na área de TI e em recrutamento multilíngue.</p></p>

 ## Habilidades: 
 - Javascript 
- HTML 
- CSS
## Local: 
 Porto Alegre, Rio Grande do Sul, Brazil
## Requisitos: 
 - Conhecimentos sólidos de HTML, CSS e JavaScript; 
- Experiência em JavaScript; 
- Conhecimentos básicos de UX/UI; 
- Familiaridade com metodologias ágeis de desenvolvimento, como Scrum ou Kanban.

## Benefícios: 
 - Vale-alimentação no Cartão VR ou VA, R$ 27,60 por dia útil. O desconto em folha de pagamento é de 20% . 
- Vale-transporte conforme necessidade do deslocamento, com desconto de 6% em folha de pagamento. 
- Assistência Médica Unimed Unipart Hospitalar. Mensalidade 100% subsídiada pela empresa, com coparticipação nas consultas. Concedido após 03 meses de experiência. 
- Auxílio Educação – Graduação no Grupo Ânima com até 90% de desconto. Válido aos colaboradores e dependentes.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Javascript Developer Jr na CyberSec Hunter](https://coodesh.com/jobs/javascript-developer-jr-182149210?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Regime
CLT
#### Categoria
Full-Stack

**Comment by netosts** [comment]
Fiz minha candidatura!

**Comment by Nathanabrahao** [comment]
Fiz minha candidatura!

**Comment by micheledarosa** [comment]
Curti muito a vaga, mas infelizmente moro no interior do RS 🥺

**Comment by DevCleverton** [comment]
Vaga parece estar congelada!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
