### ISSUE TITLE
[Remoto] Frontend Developer React Web

### ISSUE THREAD

**Issue by thiagoferreira123** [frontendbr/vagas#8028]
**Vaga: Desenvolvedor(a) React Freelancer Remoto**

Buscamos um(a) Desenvolvedor(a) Freelancer com experiência em React Web, React Query, Zustand, Next.js, TypeORM e MySQL. O projeto envolve implementar novas features em uma aplicação existente.

**Requisitos:**

Experiência com React, React Query e Zustand.
Conhecimento em NestJS/TypeORM e MySQL.

**Atividades:**

Implementar novas funcionalidades.
Otimizar o gerenciamento de estado e dados.
Integrar com APIs NestJS/TypeORM e MySQL.

**Candidatura:**

Envie seu CV e portfólio para contato@dietsystem.com.br com o assunto "Vaga React Freelancer".

**Comment by Luis-Paulo-Silva-Reis** [comment]
enviado

Em sáb., 23 de mar. de 2024 às 02:57, Thiago Ferreira <
***@***.***> escreveu:

**Comment by thiagoferreira123** [comment]
Contratado.
