### ISSUE TITLE
[Remote] Mid Fullstack Developer at Scratch Financial

### ISSUE THREAD

**Issue by lucas-barbosa** [frontendbr/vagas#8029]
**TL-DR**
Pessoal, a empresa que trabalho está com essa posição aberta.
Trabalho há 7 meses lá (fullstack Node + React) e tem sido minha melhor experiência.
Ambiente organizado, produto com bastantes clientes, oportunidades de crescimento, flexibilidade de horário, enfim, caso tenham dúvidas é só perguntar!

## Nossa empresa

Scratch Financial ("Scratchpay") is a financial technology startup based in Los Angeles, California. Our goal is to make difficult financial decisions simple and increase accessibility to fair, affordable, and transparent medical financing. Driven by our award-winning technology, Scratchpay has become the fastest growing financing provider in veterinary care, with our payment plans now offered in over 10,000 practices across the U.S. and Canada–ranging from dental offices to optometry clinics. We’re rapidly launching a new Point-of-Sale payment processing suite to help our providers create a better payments experience for their patients.

## Descrição da vaga

We’re looking for a Full Stack Developer to join our Practice Integrations team. The ideal candidate will be well experienced in Software Development and have a passion for creating new and innovative products that meet the client’s needs. The ideal candidate will also be someone that is innovative, open to change and that strives to deliver high quality code in collaboration with their team.

You will be responsible for designing and developing front end and back end applications running on different environments, as well as testing your solutions, and ensuring their ongoing responsiveness.

Traits that you can expect from us:
- At Scratchpay, the work you do will have a big impact on the business. We believe in systems and processes that let us scale our impact to be larger than ourselves. 
- We believe in a safe, welcoming, and inclusive environment, and we care most about getting it right rather than being right. 

Regardless of how well you feel you fit our description, we encourage you to apply if you meet the criteria above and below.

## Local

Remote Anywhere

## Requisitos

**Obrigatórios:**
- At least 3 years of hands-on experience with JavaScript frontend frameworks such as React.
- Strong Experience with NodeJS and Electron.
- Strong knowledge of Relational Database Servers such as MySQL or PostgreSQL.
- Proficiency with fundamental front end languages such as HTML, CSS and JavaScript.
- Fluent in English.

**Desejáveis:**
- Some experience with C#.
- Experience with microservice based architecture.
- Strong coding skills, ability to use BDD and TDD where needed.
- Experience and confidence developing RESTful APIs and high-load apps.
- Ability to switch between languages and frameworks.
- Knowledge of Agile and Scrum.

**Diferenciais:**
- Nice to have: Google Cloud, CI/CD, Kubernetes, and Docker.
- Nice to have: experience in building payment solutions.
- Nice to have: experience in the medical business.

## Benefícios
- Range Salarial: $75,000 - $140,000 a year
- PTO

## Contratação

US Contractor

## Como se candidatar
https://jobs.lever.co/scratchfinancial/1e4d2c34-1a0c-4731-b336-17bdafe30b09?lever-via=ht8JnGs6pz&lever-social=job_site

## Tempo médio de feedbacks
I'm not sure, I'm just a developer sharing an opened position in our company.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by fabriciofrontarolli** [comment]
Applied ✅

**Comment by mtluiz** [comment]
Applied, hoping for the best!

**Comment by ICarlosJuniorI** [comment]
Just applied!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
