### ISSUE TITLE
[Remoto] Frontend Developer at Scrapinghub

### ISSUE THREAD

**Issue by rennerocha** [frontendbr/vagas#803]
## About the job

You’ll be working on the Platform team, building and maintaining tools to make the world a better place for web crawler developers. We’re a data driven team that defines success by business result rather than completion of a task.

As a frontend developer, you will join us in designing and developing our customer facing application. We have established products that already have product-market fit where you’ll help to grow the business and stay up to date with market demands. At the same time, you’ll be working to iterate quickly on testing new opportunities to help determine which are worth continued investment.
Finally, being a completely remote company with team members in many different time zones, you’ll excel in this role as an independent thinker that can always find a way to move projects forward, even if you might be the only team member online at that time.

## Location

Remote

## Job Responsibilities

- Take ownership of projects, and independently drive them from prototype to completion
- Build composable, reusable components for our complex SPA
- Relentlessly strive to build easy to maintain systems via refactoring
- Be proactive in bringing forth new ideas and solutions to problems
- Be a strong team player and share knowledge freely and easily with your co-workers

## Required Skills

- Love continuous learning
- Strong knowledge of HTML, CSS and Javascript
- In depth experience with a modern client-side framework such as Angular, React, Ember, or Vue
- Familiarity with reactive programming using RxJS
- Excellent communication skills, both written and verbal, in English

## Desired skills

- Angular (2+)
- Layout using modern CSS features like flexbox and grid
- Familiarity with CSS pre-processors (SCSS preferred)
- Familiarity with the redux paradigm
- Knowledge about browser performance optimization
- Developing web applications with browser performance in mind
- Websockets and service worker experience
- Experience developing large and complex SPA

## Bonus Skills
- Experience with UX in a data-driven application
- Python experience

## How to apply

- https://jobs.lever.co/scrapinghub/64e788e6-f4f4-461b-9001-4044c2ee79a6

## Labels

- Remoto - Total

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
