### ISSUE TITLE
[Florianópolis/SC] Especialista de Arquitetura de Front End (React) na Desbravador Software

### ISSUE THREAD

**Issue by acelant** [frontendbr/vagas#8031]
## Nossa empresa

Trabalhe em uma das 50 maiores empresas de TI do Brasil e que atua em toda América Latina e Europa. Venha fazer parte de uma empresa inovadora! Somos Desbravadores movidos por conhecimento e tecnologia, e buscamos sempre o melhor para nossas soluções em software de gestão. 

## Descrição da vaga

Estamos à procura de um desenvolvedor front-end sênior em ReactJs, interessado em trabalhar na criação de sistemas web de alto desempenho e que tenha pelo menos 2 anos de experiência nesse framework e pelo 5 anos de experiência em desenvolvimento de software.

- Aprimorar a compreensão da arquitetura Front-End do software, incluindo a análise de seus componentes, organização, funcionalidades e tecnologias subjacentes;
- Colaborar ativamente na definição das diretrizes de arquitetura de software em conjunto com a equipe de arquitetura, bem como transmitir essas orientações para as equipes de desenvolvimento;
- Participar ativamente de discussões estratégicas e operacionais, estabelecendo metas anuais relacionadas a aspectos técnicos e conduzindo estudos de viabilidade e demonstrações de conceito;
- Criar documentação abrangente e promover boas práticas, definições e sugestões relacionadas à arquitetura Front-End; Elevar o nível da equipe por meio da partilha de conhecimentos e pela capacitação dos desenvolvedores.

 

👨‍💻  **RESPONSABILIDADES**

- Determinar a estrutura e o design das páginas da web.
- Garantir a experiência do usuário determina as escolhas de design.
- Desenvolvimento de recursos para melhorar a experiência do usuário, atingindo um equilíbrio entre design funcional e estético.
- Garantir que o design da web seja otimizado para smartphones.
- Construindo código reutilizável para uso futuro.
- Otimização de páginas da web para velocidade e escalabilidade máximas.
- Mantendo a consistência da marca em todo o design.
- Garantir a implementação das melhores práticas de codificação

## Local

Florianópolis, Santa Catarina, Brasil

## Requisitos

**Obrigatórios:**

- Dominio de JavaScript
- Experiência mínima de 3 anos com React, Nodejs,Typescript;
- Conhecimentos em redux, redis, jest;
- Conhecimento em Rest/Restful;
- Conhecimento em Hooks, TDD, Clean Architecture, SOLID
- Design Responsivo Web
- Controle de Versionamento (Git);
- Experiência em HTML, CSS, JavaScript e jQuery.
- Compreensão dos principais princípios de design.
- Experiência com design responsivo e adaptável.
- Conhecimentos de Arquitetura Web distribuída (12 factor applications etc);
- Design Patterns e Refactor Patterns;
- TypeScript e funcionamento do browser (DOM, HTTP);
- Métodos Ágeis (Kanban, Scrum);
- CI/CD voltado para FrontEnd;
- Softwares de colaboração e prototipação de UI (Figma, Adobe XD, Sketch);
- Webpack 5;
- Práticas de segurança no browser (CSP, prevenção de XSS);
- Organização, clareza e foco na experiência do usuário.

**Desejáveis:**
* Conhecimentos em Micro Front-End ou Module Federation;
* Conhecimentos em OAuth;

## Oferecemos

- Remuneração compatível com o seu nível de conhecimento;
- Ferramentas de apoio que facilitam o seu trabalho e a comunicação no dia-a-dia da empresa como Redmine, Teams, Git, AWS.
- No Dress Code;
- Plano de saúde Unimed;
- VR/VA
- Excelente ambiente de trabalho;
- Treinamentos de desenvolvimento profissional;
- Home Office;

## Contratação

a combinar

## Como se candidatar

Por favor envie um email para andressa.celant@desbravador.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: rh@desbravador.com.br

**Comment by MCiappina** [comment]
enviado

**Comment by brunonoatto** [comment]
Curriculo enviado, obrigado por compartilhar a vaga.

**Comment by sasgustav** [comment]
**Curriculo enviado, obrigado por compartilhar a vaga.**

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
