### ISSUE TITLE
[Remoto] Front-end Developer na Signifyd

### ISSUE THREAD

**Issue by wsrzx** [frontendbr/vagas#8033]
> Vaga Remota durante a pandemia

## Nossa empresa

Signifyd is a company that provides ecommerce fraud protection and prevention services to help other companies power fearless commerce. Our platform uses machine learning to protect businesses from fraud while also protecting customers from false declines. We aim to give merchants ultimate control and transparency over fraud decisions while also optimizing conversion rates and payments.

## Descrição da vaga

This is an opportunity to join our dedicated front-end team, where you'll have the chance to work on various UI applications and browser plugins. As part of the team, you’ll have the chance to drive the future of our front-end architecture, tools, standards and practices. This exciting opening allows you to be at the forefront of our ever-growing front-end team and contribute to an already extensive range of cutting-edge customer and internal applications.

## Local

Remoto

## Requisitos

This is an opportunity to join our dedicated front-end team, where you'll have the chance to work on various UI applications and browser plugins. As part of the team, you’ll have the chance to drive the future of our front-end architecture, tools, standards and practices. This exciting opening allows you to be at the forefront of our ever-growing front-end team and contribute to an already extensive range of cutting-edge customer and internal applications.

**Obrigatórios:**

- 3+ years of hands-on experience with front-end technologies e.g. React, Angular, JavaScript, JQuery, CSS, HTML
- Excellent programming skills in Javascript (ES6+)
- Professionally proficient in English
- Experience with enterprise-ready React applications (or other modern frameworks)
- A solid understanding of HTML and CSS
- Experience with unit testing in Javascript with React
- Comfortable moving between libraries/patterns/technologies
- Experience using Git in a collaborative environment
- Strong understanding of testing (unit, integration, manual, end-to-end)
- Enthusiastic engagement with the code review process
- Willingness to be on-call

## Benefícios

- Refeição/Alimentação
- Seguro de vida
- Plano de saúde
- Plano odontologico
- Notebook ou Macbook

**Diferenciais:**
- Semana de 4 dias de trabalho

## Contratação

CLT

## Como se candidatar

Apply [https://boards.greenhouse.io/signifyd95/jobs/5555840](https://boards.greenhouse.io/signifyd95/jobs/5555840)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior

**Comment by renatorib** [comment]
Aplicado!

**Comment by guim0** [comment]
Done

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
