### ISSUE TITLE
[Remote] IT Jobs (Strider)

### ISSUE THREAD

**Issue by Claudiaantunesdelima** [frontendbr/vagas#8034]
We are accepting applicants from the following countries: #Argentina, #Brazil, #Colombia   and  #Mexico.

Lead Back-end/Data Engineer - Python (C1/C2)
💰USD 7k / month
app.onstrider.com/r/claudiaantunes?job=bGVhZC1iYWNrLWVuZC1kYXRhLWVuZ2luZWVyLXB5dGhvbi1zdHJpZGVyLTJiNjI0MzYzP3JlZmVycmFsPWNsYXVkaWFhbnR1bmVz

Lead Architect  (C1/C2)
💰USD 7k / month
app.onstrider.com/r/claudiaantunes?job=bGVhZC1hcmNoaXRlY3QtYjA3YzgzNTE/cmVmZXJyYWw9Y2xhdWRpYWFudHVuZXM=

Senior Full-stack/Back-end Engineer - Node.js, TypeScript (C1/C2)
💰USD 7k / month
app.onstrider.com/r/claudiaantunes?job=c2VuaW9yLWZ1bGwtc3RhY2stZW5naW5lZXItcmVhY3QuanMtbm9kZS5qcy10eXBlc2NyaXB0LXN0cmlkZXItZWIwMGY5ZjE/cmVmZXJyYWw9Y2xhdWRpYWFudHVuZXM=

Senior Full-stack Engineer - Magento (C1/C2)
💰USD 7k / month
app.onstrider.com/r/claudiaantunes?job=c2VuaW9yLWZ1bGwtc3RhY2stZW5naW5lZXItcmVhY3QuanMtbm9kZS5qcy10eXBlc2NyaXB0LXN0cmlkZXItZWIwMGY5ZjE/cmVmZXJyYWw9Y2xhdWRpYWFudHVuZXM=

Senior Full-stack Engineer - Magento (B2)
💰USD 6k / month
app.onstrider.com/r/claudiaantunes?job=c2VuaW9yLWZ1bGwtc3RhY2stZW5naW5lZXItbWFnZW50by0zYzMyMDdiZj9yZWZlcnJhbD1jbGF1ZGlhYW50dW5lcw==

Senior Front-end Developer - JavaScript (B2)
💰USD 5k / month
app.onstrider.com/r/claudiaantunes?job=c2VuaW9yLWZyb250LWVuZC1kZXZlbG9wZXItamF2YXNjcmlwdC00ZDA2ZDY1Nj9yZWZlcnJhbD1jbGF1ZGlhYW50dW5lcw==

Mid Machine Learning Engineer - LLM-Python- (B2)
💰USD 4k / month (3 years min)
app.onstrider.com/r/claudiaantunes?job=bWlkLW1hY2hpbmUtbGVhcm5pbmctZW5naW5lZXItbGxtLTQyZmRhNGZkP3JlZmVycmFsPWNsYXVkaWFhbnR1bmVz

Mid-senior Full-stack Engineer - React.js, Golang  (C1/C2)
💰USD 4k / month
app.onstrider.com/r/claudiaantunes?job=bWlkLXNlbmlvci1mdWxsLXN0YWNrLWVuZ2luZWVyLXJlYWN0LmpzLWdvbGFuZy03NTAyMzA3MT9yZWZlcnJhbD1jbGF1ZGlhYW50dW5lcw==

Senior Front-end Engineer - React.js, Redux (B2)
💰USD 5k / month
app.onstrider.com/r/claudiaantunes?job=c2VuaW9yLWZyb250LWVuZC1lbmdpbmVlci1yZWFjdC5qcy1yZWR1eC1iMTBhZTNiMz9yZWZlcnJhbD1jbGF1ZGlhYW50dW5lcw==

Mid Back-end Engineer - Node (B2)
💰USD 4k / month
app.onstrider.com/r/claudiaantunes?job=bWlkLWJhY2stZW5kLWVuZ2luZWVyLW5vZGUuanMtMzFlNGMxNTk/cmVmZXJyYWw9Y2xhdWRpYWFudHVuZXM

Senior Data Engineer (B2)
💰USD 4k / month
app.onstrider.com/r/claudiaantunes?job=c2VuaW9yLWRhdGEtZW5naW5lZXItMmNiYzlkMTI/cmVmZXJyYWw9Y2xhdWRpYWFudHVuZXM=

Senior Data Scientist - Python, SQL (B2)
💰USD 6k /month
app.onstrider.com/r/claudiaantunes?job=c2VuaW9yLWRhdGEtc2NpZW50aXN0LXB5dGhvbi1zcWwtMTJmNzczYmM/cmVmZXJyYWw9Y2xhdWRpYWFudHVuZXM

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
