### ISSUE TITLE
[Remote] Mid/Senior Frontend Developer @Wealth99

### ISSUE THREAD

**Issue by Soonas** [frontendbr/vagas#8037]
**Our Company:** [Wealth99 ](https://www.wealth99.com/)is a company that acts on the CryptoCurrency and Tokenization of assets market.

We are searching for someone to fulfil a role that entails frontend development. The ideal candidate is someone who highly regards the user experience and already had previous roles as a Software Developer. Keen interest in evolving and developing great products with ease of use is a must.

**Essential Duties:**
- Work with agile methodologies helping to organize and maintain the backlog;
- Collaborate with the development and design team to translate business requirements into robust and scalable technical solutions;
- Architect and develop highly interactive and responsive user interfaces using Vue.js, applying best design and development practices;
- Contribute to continuous improvement of development processes, including code reviews, test automation, and continuous integration.
- Stay updated with the latest trends and technologies in front-end development, sharing knowledge and insights with the team.
- Create responsive elements and components.
- Implement database queries using APIs.
- Document developed code.
- Integration with external and internal APIs.

**Required Skills:** 
- Mid level english (B1 at least)
- Proven Experience with Typescript & Vue.JS.
- Experience with Web Design.
- Experience with code control (GIT)
- Proven experience with Tailwind CSS.
- Experience with developing automated tests for frontend. Including, integration and unit testing.

**Preferred Skills:**
- Knowledge on the Capacitor.JS framework.
- Experience with Docker.

**What would make you stand-out?**
- Knowledge of Blockchain and Web3 applications.

**Place of Employment:** Remote

**Benefits:**
- Flexible working hours
- 100% Remote Work - Work from anywhere in the world
- Paid Time Off (PTO)
- Birthday Time-Off 
- Global projects and multicultural teams with international colleagues.

**Working Regime:** Full-Time or Part-time
**Hiring Contract:** PJ

**Salary:**
Mid: R$5,000 - R$7,000
Senior: +R$7,000

**How to Apply:** You can apply by filling out this [Form](https://forms.gle/dXsy1y9PYWUtyPJy7).

Usual Lead Time: We usually provide feedback within 14 days after each process.
Contact email if you have any questions: luana@dacxi.com

**Comment by eduardo-nedel** [comment]
Sent my apply in the form.

**Comment by LuanaDac** [comment]
> Sent my application in the form

We will soon be pre-filtering all the candidates, keep an eye on the email. Tks Eduardo!

**Comment by Soonas** [comment]
> Sent my application in the form

We will soon be pre-filtering all the candidates, keep an eye on the email. Tks Eduardo!

**Comment by arthuresc** [comment]
Form is already answered, thank you.

Em seg., 8 de abr. de 2024 às 17:21, Soonas ***@***.***>
escreveu:

**Comment by jordan-ae** [comment]
@Soonas Hello, Came across this listing tried applying through the form but it seems to be closed. Is the time to apply over?
