### ISSUE TITLE
[Híbrido - Caxias do Sul] Front-end Developer na Luminator

### ISSUE THREAD

**Issue by juliamoraes1** [frontendbr/vagas#8039]
Estamos em busca de uma Pessoa Desenvolvedora Front End SR (Angular/React) para atuar em uma empresa desenvolvedora e fornecedora de tecnologia com benefícios tangíveis para o transporte público.

➡️ Hibrido (1x ao mês em Caxias do Sul/RS)

🎯Sobre as responsabilidades deste profissional:

✅ Arquitetar, projetar e desenvolver aplicativos da web responsivos e de alto desempenho;

✅ Colaborar estreitamente com designers e engenheiros de back-end para implementar interfaces de usuário;

✅ Otimizar o desempenho do aplicativo e garantir a compatibilidade entre navegadores;

✅ Orientar engenheiros front-end juniores e contribuir para seu crescimento;

✅ Mantenha-se atualizado com as últimas tendências e práticas recomendadas de front-end.

[📌](https://emojipedia.org/pt/tacha/) É necessário que você possua:

✅ Inglês avançado/fluente;

✅ Ensino superior completo em ciência da computação/engenharia ou equivalente;

✅ Experiência profissional avançada em desenvolvimento front-end;

✅ Proficiência em JavaScript (ES6+), HTML5, CSS3 e estruturas de front-end como React, Angular ou Vue.js;

✅ Design responsivo e desenvolvimento mobile-first;

✅ APIs RESTful e programação assíncrona;

✅ Princípios de design UI/UX;

✅ Experiência com bibliotecas de gerenciamento de estado (por exemplo, Redux, MobX);

✅ Testes unitários e desenvolvimento orientado a testes;

✅ Perfil e otimização de desempenho de front-end;

✅ Experiência com Aplicativos Web Progressivos (PWAs) e service workers (diferencial);

✅ Melhores práticas de internacionalização (i18n) e acessibilidade (a11y) (diferencial);

✅ GraphQL ou outras linguagens de consulta de API (diferencial);

Como se candidatar

• Por favor envie um email para julia.feelrh@gmail.com, para o número (44) 99862-3322 ou comente aqui com seu perfil do linkedin!

**Comment by yansilva89** [comment]
https://www.linkedin.com/in/yansilva89/

**Comment by PatrickLzt** [comment]
https://www.linkedin.com/in/patrick-lorenzeti-9647bb211

**Comment by EdilsonBaggio** [comment]
https://edilsonsantos.website/

**Comment by jakkajan1** [comment]
https://jakkajan1.github.io/

**Comment by Mauricio2025** [comment]
https://www.linkedin.com/in/developer-mauricio-souza/

**Comment by jakkajan1** [comment]
?

Em qui., 23 de mai. de 2024 às 11:31, Mauricio Souza <
***@***.***> escreveu:

**Comment by samuel4oliveira** [comment]
https://www.linkedin.com/in/samuel4oliveira/
