### ISSUE TITLE
[Barueri] Front-end Developer

### ISSUE THREAD

**Issue by AnieliFernanda** [frontendbr/vagas#804]
A Wtime Business Intelligence It, consultoria especialista em serviços de tecnologia da informação, está contratando para atuar no cliente;  

**Desenvolvedor Front-end Pleno/Sênior** 
Conhecimentos em 
HTML5;
JS;
CSS3;
VUE.js;
Sass;
Mocha.

Desejável:  Angular JS;
Experiência na área da saúde.

Local de trabalho: Alphaville/SP  
Modalidade: PJ
Projeto por tempo indeterminado

Interessados enviar currículo com a pretensão salarial no e-mail: Joyce.carvalho@wtime.com.br

**Comment by LFeh** [comment]
A contratação é feita pela Wtime Business?

**Comment by AnieliFernanda** [comment]
Olá, Felipe. 
Isso mesmo!

**Comment by Finacio** [comment]
Enviado!

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
