### ISSUE TITLE
[SP/MG] Front-end Developer na VipCommerce

### ISSUE THREAD

**Issue by BarbaraAncieto** [frontendbr/vagas#8042]
## Nossa empresa
Integrando o ecossistema MagaLu e presente em mais de vinte estados do Brasil, a VipCommerce atende os maiores supermercadistas do país com o propósito de liderar a transformação digital no setor de varejo alimentar!

Da tecnologia ao conhecimento especializado, a VipCommece fornece tudo o que o cliente precisa para digitalizar a sua rede supermercadista e proporcionar uma experiência omnicanal aos consumidores! Modelo logístico especializado, loja virtual, aplicativo, ferramentas de marketing, integrações com os seus sistemas, multilojas, suporte total, treinamento da sua equipe e muito mais.

## Local
Preferência por SP/MG

## Requisitos
Conhecimento e experiência em **Angular 8+ (AngularJS não atende);**
Conhecimento em Ionic;
Experiência com Teste Unitário;
Vivência em Microfrontend;
Experiência com SEO;

**Experiência com Ambiente Linux é essencial.**

**Experiências e conhecimentos desejáveis:**
Desejável experiência em Desenvolvimento orientado a objetos;
Consumir API Rest;
Experiência com PHP com LUMEN;
Experiência NodeJs com NESTJS.
**Diferenciais:**
- projetos opensource

## Benefícios

- Vale Alimentação/Refeição
- Auxílio Home Office
- Gympass
- Convênio Médico e Odontológico SulAmérica
- PLR
- Auxilio Educação
- Programa Indicação
- Equipamento de Trabalho

## Contratação
Modelo **CLT**

## Como se candidatar
Link para candidatura: [https://tecer.inhire.app/vagas/3d463af5-2a74-40d6-9171-0a721cd851a4/desenvolvedora-frontend](url)

**Comment by VictorG1002** [comment]
o link da vaga me joga pro github

**Comment by BarbaraAncieto** [comment]
Candidatura: https://tecer.inhire.app/vagas/3d463af5-2a74-40d6-9171-0a721cd851a4/desenvolvedora-frontend
