### ISSUE TITLE
[São Paulo/SP] Full Stack Developer (Pleno) - Node.js + Angular [Aprova]

### ISSUE THREAD

**Issue by lisia-matos** [frontendbr/vagas#8043]
**Sobre a vaga:**
O Software Engineer colabora com equipes multidisciplinares para projetar e entregar um software funcional, com liberdade para garantir que as aplicações desenvolvidas estejam em conformidade com os padrões de codificação e design técnico. O Software Engineer trabalha em estreita colaboração com o Engineering Manager (Scrum Master), CTO e Product Managers para atingir esses objetivos.

> [https://aprovadigital.gupy.io/jobs/7001992]

**_Como trabalhamos_**
1. Os Product Managers realizam entrevistas, coletando dados da aplicação de uso e ouvindo stakeholders diversos e constroem a visão das features, que é uma documentação que norteará o desenvolvimento nos próximos 3-6 meses daquele problema/solução;
2. Em seguida o Product Manager quebra em pequenas entregas, e após input do Software Engineer em refinamentos a User Story entra em sprint, as sprints tem 15 dias e o Software Engineer estima em story points o que reflete esforço e complexidade;
3. O Software Engineer inicia a implementação seguindo requisitos técnicos amplos que garantem liberdade da abordagem a qual sempre pode ser validada com o Tech lead e CTO;
4. Possuímos um time de QA com uma suite de testes automatizados (end to end) o que ajuda o Software Engineer a garantir a qualidade da entrega;
5. Após isso a Pull Request sobe numa branch main (só possuímos uma branch) que depois é mergeada com o Jenkins. Estamos trabalhando para que esse processo seja cada vez mais automatizado via Terraform.
6. Realizamos releases diárias, entre 1-6 releases em horários fora de pico (18h). Todo o deploy leva em torno de 30 min.

**RESPONSABILIDADES E ATRIBUIÇÕES**
**Primárias:**
- Projetar, desenvolver e manter aplicações desenvolvidas pela companhia de maneira full stack, incluindo backend RESTful em TypeScript, NodeJS e Python, e frontend em TypeScript + Angular.
- Esperamos que o Desenvolvedor seja owner de todo o ciclo de vida do desenvolvimento de software, escrevendo códigos bem estruturados, eficientes e testáveis, participando de revisões de código produzidos pelos colegas, garantindo nosso atual padrão de qualidade e sugerindo melhorias em todo o processos.

**Secundárias:**
- Colaborar com outros membros da equipe de engenharia, auxiliando em dúvidas técnicas e configurações de cenários complexos.
- Elaborar testes unitários seguindo as guidelines que serão estabelecidas e mantendo-se atualizado com as tendências tecnológicas.
- Disseminar conhecimento para o time, criando documentação técnica das tarefas entregues.

**REQUISITOS E QUALIFICAÇÕES**
- Graduação completa em Analista de Sistemas, Ciência da Computação, Engenharia da Computação ou áreas afins.
- Experiência com: NodeJS, Typescript, Angular ou Vue ou React, MongoDB, e ferramentas da AWS.
- Habilidades de comunicação para explicar conceitos técnicos de forma clara e compreensível para o cliente e informar as ações de forma objetiva e coesa ao time.
- Residir em São Paulo/SP ou região metropolitana e ter disponibilidade para trabalho no modelo híbrido. Temos como objetivo a abertura de um escritório com boa infra estrutura em região bem conectada em São Paulo (Paulista-Itaim) em 2025.

**Diferenciais**
Esses diferenciais são características que estaremos observando, mas não são critérios eliminatórios. São pontos que contribuem para a análise do candidato, portanto, se você possuir alguma dessas experiências, compartilhe conosco durante o processo :)
- Experiência em construção de aplicações em paradigma DDD (Design Driven Domain)
- Experiência em construção de features de integrações (REST e SOAP)
- Experiência em implementação de tecnologias de filas como RabbitMQ
- Já ter trabalhado em empresas que crescem seu faturamento 2-3x ao ano (Startups)
- Experiência construindo produtos que são distribuídas no modelo SaaS - Software as a Service

**Nossa Stack**
Estamos baseados em uma arquitetura de microsserviços em ambiente serverless, totalmente suportada pelos recursos da AWS.

**Backend:**
Implementamos um backend RESTful utilizando microsserviços serverless em TypeScript, NodeJS e Python. Isso nos permite criar uma base sólida para nossas operações, mantendo uma flexibilidade essencial.

**Frontend:**
Em nosso frontend, usamos tecnologias como Angular, Vue e React para criar interfaces interativas e dinâmicas, proporcionando aos usuários uma experiência atraente e amigável.

**Práticas e Ferramentas:**
- Utilizamos Domain Driven Design, RxJS e programação reativa para novas implementações.
- Mantemos 100% de nossa infraestrutura como código, seguindo as melhores práticas cloud native, facilitando a escalabilidade e a manutenção contínua.
- Utilizamos MongoDB e PostgreSQL como nossos sistemas de gerenciamento de banco de dados, proporcionando confiabilidade e flexibilidade para nossas necessidades variadas.

**Serviços AWS:**
Para suportar nossa arquitetura, confiamos em uma variedade de serviços da AWS, incluindo S3, SQS, RDS, Lambda, CloudFront, CloudFormation, entre outros. Isso nos permite oferecer aos nossos clientes serviços confiáveis e de alta performance.

**Automação e Gerenciamento:**
- Implementamos integração contínua/desdobramento contínuo (CI/CD) usando Jenkins para garantir uma entrega rápida e confiável de nossos produtos.
- Para organização e gerenciamento eficazes de nossas tarefas de desenvolvimento, contamos com o Jira.
- Estamos continuamente refinando nossa Stack para enfrentar os desafios de escala e para garantir que possamos atender às crescentes demandas de nossos clientes de maneira eficaz e inovadora.
- 

OFERECEMOS:
- Plano de Saúde Bradesco 100% pago pela empresa;
- Convênio Odontológico;
- Vale Refeição Swile;
- Seguro de Vida;
- TotalPass;
- Desconto para Psicoterapia em parceria com a Vittude;
- Licença paternidade de 20 dias;
- Day off para o seu aniversário;
- Equipamentos fornecidos pela empresa;
- Ambiente informal, descontraído e com pessoas incríveis;
- Aprendizados e desafios diários.

🔹Qualquer dúvida me chama no linkedIn [https://www.linkedin.com/in/lisia-matos-46162518b/] :]

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
