### ISSUE TITLE
[REMOTO] FULL STACK PLENO - WEB - GOING2

### ISSUE THREAD

**Issue by MariaJuliaRicostiG2** [frontendbr/vagas#8044]
## Nossa empresa

A Going2 é uma startup que nasceu em 2012, com o propósito de levar tecnologia de ponta para todo o Brasil, focada em criar produtos que tenham como premissa, facilitar a vida das pessoas e empresas, através do desenvolvimento de Aplicativos, Sistemas e dos princípios de IOT (internet das coisas). Hoje, além de atender clientes nacionais também oferecemos nossos serviços para clientes internacionais, como por exemplo no Canada, Suíça e Estados Unidos.

## Descrição da vaga

Atividades:

- Desenvolver interfaces de usuário responsivas e interativas, garantindo uma excelente experiência do usuário.
- Criar e manter a lógica de back-end, APIs e serviços web, assegurando a funcionalidade, segurança e escalabilidade.
- Gerenciar e otimizar bancos de dados, garantindo a integridade e performance dos dados.
- Produzir documentação técnica e especificações claras para APIs.
- Utilizar tecnologias de conteinerização e orquestração para deploy e gestão de aplicações.
- Desenvolver funcionalidades de mensageria e comunicação em tempo real.
- Configurar servidores web, para entregar uma aplicação de ponta a ponta.
- Aplicar práticas de Clean Code, Refatoração de Código e Automação de Testes.
- Adotar práticas DevOps para automação de infraestrutura, implantação e monitoramento.

## Local

Remoto

## Requisitos

**Frontend**

- HTML, JQuery, Bootstrap
- NextJS (Typescript e React)
- Redux e Redux Toolkit
- TailwindCSS

**Backend**

- Django e Django REST Framework
- NestJS
- Sistemas de mensageria (Kafka)
- Tecnologias de real-time (MQTT, Socket.io)

**Banco de dados:**

- PostgreSQL
- MongoDB e Mongoose
- Armazenamento de arquivos na nuvem (S3)
- Containerização (Docker)
- Jest (desejável)
- Configuração de servidores web (Nginx) (desejável)
- Kubernetes(desejável)
- Skaffold(desejável)
- Google Cloud(desejável)
- Experiência com Inteligência Artificial (desejável)

## Benefícios

- Ajuda de custo exclusivo para convenio médico e odontológico;
- Convênio com plataforma de idiomas (Fluency Academy)
- Day-Off de aniversário;
- 15 dias de descanso remunerado;
- Plano de carreira.

**Outras informações:**

- Horário: 09h às 18h;
- 100% remoto;
- Contrato de prazo indeterminado; PJ.

## Contratação

PJ

## Como se candidatar

Enviar um e-mail para recrutamento@going2.com.br contendo currículo e quantos anos trabalho com as tecnologias pedidas na vaga e pretensão salarial. Com o assunto: Vaga Full Stack Pleno Web.

### Nível

- Pleno

### Regime

- PJ

### Alocação

- Remoto

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
