### ISSUE TITLE
[Brasil] Front-end   TECH LEAD  ( REACT.JS)  na  HUNT IT 

### ISSUE THREAD

**Issue by jokapoa** [frontendbr/vagas#8045]
### Tech Lead Frontend - Inovação em Projetos Globais

Estamos representando uma empresa líder em tecnologia e inovação  sediada nos EUA e base no Brasil, especializada em projetos inovadores com impacto global.

Nossa equipe está atualmente recrutando um Tech Lead com foco em front end  ( react .js)  para se juntar a um time altamente qualificado da empresa. 
Se você é um profissional apaixonado por desenvolvimento front-end, arquitetura, inovação e liderança de equipe, esta pode ser a oportunidade ideal para você!

### Responsabilidades:

Liderar e inspirar uma equipe sênior de desenvolvimento frontend, atualmente composta por 3 membros no Brasil.
Desenvolver arquiteturas de frontend inovadoras e eficientes para os projetos da empresa  nos EUA.
Colaborar de forma próxima com o time nos EUA para alinhar estratégias e objetivos de cada projeto, em contato com os clientes .
Contribuir ativamente para o desenvolvimento de projetos que impactam usuários  de forma diferenciada
Fomentar uma cultura de inovação e excelência técnica dentro da equipe.

### Requisitos:

**Experiência sólida como desenvolvedor frontend, com expertise em ReactJS.**
Familiaridade com Typescript , ferramentas de SEO, pacote Adobe.
Senioridade no desenvolvimento de projetos frontend inovadores.
Capacidade  de liderar e motivar equipes, promovendo um ambiente de colaboração e aprendizado.
**Excelentes habilidades de comunicação e capacidade de trabalhar eficazmente em equipes distribuídas globalmente.
Experiência em construção de animações 3D  usando frameworks como  Three.js ou WebGL**

### Oferecemos:

Oportunidade de fazer parte de uma empresa inovadora, reconhecida por seus clientes e em franca expansão.
Contrato flexível, podendo ser PJ ou CLT, com remuneração compatível com o perfil e experiência do candidato e exigência da vaga.
Ambiente de trabalho dinâmico e colaborativo, onde a inovação e a excelência técnica são valorizadas.
Interessados podem enviar currículo para  eua@huntit.com.br  com exemplos de projetos de grande porte que você participou em posições similares.

#### Nível
TECH LEAD REACT.JS

Mais informações ou candidaturas , no whatsapp (11) 5199-5000  ou  diretamente no site da HUNT TECH [ https://vagas.huntit.com.br/jobdetail/KR00412F ](https://vagas.huntit.com.br/jobdetail/KR00412F)

**Comment by MCiappina** [comment]
@jokapoa enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
