### ISSUE TITLE
[Remote] Desenvolvedor Full-stack JavaScript Sênior 

### ISSUE THREAD

**Issue by Claudiaantunesdelima** [frontendbr/vagas#8046]
Oportunidade👇🏻🇧🇷🌍

#Desenvolvedor #JavaScript #Fullstack #Sênior precisa ter o Inglês Avançado para um projeto Internacional. 👇🏻

💠Você é um desenvolvedor JavaScript habilidoso com paixão por criar aplicativos de ponta? Você gosta de trabalhar em um ambiente dinâmico e colaborativo, onde você pode ensinar e aprender? Se isso soa como você, estamos ansiosos para conhecê-lo!

💠Sobre a Função:
Estamos à procura de um talentoso e experiente desenvolvedor JavaScript Fullstack para se tornar parte de nossa vibrante equipe. Nessa função, você terá uma parte crucial em todo o ciclo de vida de desenvolvimento de aplicativos, desde a concepção e o design até a implantação e a manutenção. Trabalhando ao lado de um grupo diversificado de colegas, você garantirá a entrega de soluções centradas em #JavaScript de alta qualidade que se alinham com nossos objetivos de negócios.

Habilidades e Experiência:

🔹Mínimo 7 anos de experiências
Histórico comprovado como desenvolvedor JavaScript Fullstack, com um portfólio de projetos de sucesso em seu nome.
Proficiente em #JavaScript e #TypeScript, com vasta experiência em #Node.js e React.js para construção de aplicações web responsivas e de alto desempenho.
🔹Familiaridade com serviços e infraestrutura da #AWS, incluindo implantação e gerenciamento de aplicativos escaláveis.
🔹Sólida compreensão dos princípios de desenvolvimento de aplicações web, incluindo design e desenvolvimento de #API #RESTful.
🔹Experiência com ferramentas e práticas modernas de desenvolvimento, como Git, pipelines de CI/CD e frameworks de testes automatizados.
Conhecimento de bancos de dados SQL e NoSQL, com a capacidade de projetar estruturas de dados e consultas eficientes.
🔹Um solucionador de problemas no coração, com uma abordagem estruturada para enfrentar os desafios e um olhar atento para os detalhes.
🔹Excelentes habilidades de comunicação e colaboração, com a capacidade de trabalhar efetivamente em um ambiente orientado para a equipe.
🔹Um aprendiz ao longo da vida, aberto a compartilhar conhecimentos e habilidades com colegas e receptivo a novas ideias e tecnologias.

✅ 3 vagas
🏠Remoto
PJ 

#oportunidadesti 
#vagasdeti 
#vagati
#tecnologia 
#programacao 

Faça parte do nosso time!

Se inscreva no formulário abaixo 👇🏻

https://lnkd.in/dNf3gtTR

**Comment by MCiappina** [comment]
@Claudiaantunesdelima enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
