### ISSUE TITLE
[Remoto] Front-end Angular Developer na Coodesh

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#8047]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/desenvolvedora-front-end-angular-143427368?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>🎯 O seu papel nesta história:</strong></p>
<ul>
<li>Colaborar com os times de engenharia, produto e negócio no projeto e construção dos produtos seguros e escaláveis;</li>
<li>Atuar no desenvolvimento de novas features e na manutenção dos produtos;</li>
<li>Capacidade de construir soluções a partir de um protótipo de alta fidelidade (Figma)</li>
<li>Implementar e acompanhar em produção, por meio do monitoramento, os resultados e oportunidades de melhoria nos produtos entregues;</li>
<li>Escrever código limpo, testável e de fácil manutenção;</li>
<li>Buscar oportunidades de inovação em diferentes cenários e realizar análises de acordo com a necessidade apontada;</li>
<li>Debugar aplicações para identificar a causa dos erros;</li>
<li>Atuar como mentor e disseminar conhecimento para outros membros do time.</li>
</ul>
<p></p>
<p><strong>🚀 O que esperamos de você enquanto requisitos comportamentais:</strong></p>
<p><strong>Ter senso de organização, atenção a detalhes e foco;</strong></p>
<p><strong>Capacidade de seguir as tendências do mercado e de se adaptar rapidamente a novas tecnologias;</strong></p>
<p><strong>Ter boa comunicação oral e escrita;</strong></p>
<p><strong>Saber trabalhar em equipe.</strong></p>
<p></p>
<p></p>
<p></p>
## Lastlink: 
 <p>Somos uma startup mineira que ajuda criadores de conteúdo a estarem cada vez mais próximos dos seu público alvo, gerenciando suas comunidades e vivendo daquilo que sabem fazer de melhor. Desenvolvemos um sistema que aproxima e conecta o criador de conteúdo aos seus membros, possibilitando a monetização do conteúdo. Contamos com um time de especialistas em tecnologia, design, marketing, vendas, suporte, que estão transformando o mercado de vendas online e construindo soluções que potencializam o trabalho dos pequenos empreendedores.&nbsp;&nbsp;</p>

<p>Nosso público é formado por criadores digitais, empreendedores e profissionais liberais de diversas áreas. Somos uma empresa pioneira em monetização e gestão de conteúdos exclusivos e construímos o primeiro marketplace de conteúdo exclusivo em redes sociais no mundo.</p><a href='https://coodesh.com/companies/lastlink'>Veja mais no site</a>

 ## Habilidades: 
 - Angular 
- Figma 
- CSS
## Local: 
 100% Remoto
## Requisitos: 
 - Ter domínio em Javascript, HTML5 e CSS3 (Bootstrap, Sass e Less); 
- Ter conhecimento em versionamento de código (GIT); 
- Ter experiência com Angular 13, Bootstrap, CSS e Typescript; 
- Inglês intermediário (capaz de ler e escrever, será utilizado principalmente para estudo e leitura de documentações).
## Diferenciais: 
 - Experiência em empresas de tecnologia/startup; 
- Inglês avançado;

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Front-end Angular Developer na Lastlink](https://coodesh.com/jobs/desenvolvedora-front-end-angular-143427368?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by LeoSoaresO** [comment]
Enviado!

**Comment by MCiappina** [comment]
@FrancieleGhizzoni enviado!

**Comment by FabianaTavares** [comment]
ao clicar no link diz que a vaga já foi finalizada pela empresa.
