### ISSUE TITLE
[Belo Horizonte] Front-End Engineer na Dito

### ISSUE THREAD

**Issue by mari-dito** [frontendbr/vagas#805]
![logo-dito-black](https://user-images.githubusercontent.com/36310835/36048197-8d24742c-0dc5-11e8-87ed-ef58b98e6550.png)

## Estamos em busca de mais um FERA para o nosso time! 

Como é ser um **FERA**?
- Nós somos uma das Melhores Empresas para se Trabalhar em Minas Gerais, de acordo com o Great Place to Work®
- No nosso time, todo mundo é **FERA**: pega e **F**az, com foco; age com **É**tica e transparência; se preocupa com o **R**esultado dos clientes (internos e externos); trabalha com **A**legria e tem sede por **A**prender;
- Do Inside Sales ao Dev, do Customer Success ao RH, todos nós somos especialistas em retenção. Por isso, nunca nos cansamos de estudar e aplicamos as melhores estratégias para encantar nossos clientes;
- Seja no horário de almoço ou depois do expediente, o Fifinha é sagrado. Mas tem que aguentar a zoação se seu time perder, tá?
- Nós somos obcecados por metas e sempre queremos atingir a excelência em tudo o que fazemos. Por isso, planejamos e apresentamos nossas entregas de forma transparente;
- Não acreditamos em hierarquia ou divisões rígidas. As áreas se comunicam o tempo todo e o nosso trabalho é sempre em conjunto;
- Nós respeitamos e incorporamos as diferenças, por isso temos uma equipe tão foda. Você é #TeamJunkFood ou #TeamMaromba? Atleticano ou Cruzeirense? Ou Corintiano, São Paulino, Flamenguista…? É vegetariano/vegano ou adora churrasco? Curte rock ou sertanejo? Aqui tem espaço pra todo mundo :)
- Sempre temos cerveja na geladeira, fazemos happy hour todo trimestre (mas às vezes não resistimos e acabamos fazendo mais de um) e promovemos eventos espontâneos para surpreender a equipe;
- Sabemos que a Dito nasceu para revolucionar a experiência de engajamento entre pessoas e marcas. Queremos vê-la crescer e somos incansáveis em divulgar nosso trabalho para o mundo!

## Responsabilidades:
- Manutenção e evolução do front-end do produto da Dito;
- Automatizar a integração da SDK da Dito nos sites dos clientes;
- Propor e desenvolver soluções front-end para novas funcionalidades;
- Aprimoramento da performance do nosso front-end.

## Requisitos:
- Experiência em Javascript ES2015; 
- Conhecimento em SPA e AngularJS;
- Experiência com integrações utilizando API REST;
- Domínio de métricas de performance do front-end;
- Entender a fundo (real oficial!) o funcionamento de um navegador;
- Domínio na leitura e escrita em inglês (todas as nossas referências são gringas).

## Diferenciais (ganhe pontos extra aqui):
- Conhecimentos em React / Redux;
- Conhecimentos no task runner Gulp;
- Conhecimentos em Webpack;
- Conhecimentos em programação funcional;
- Experiência com controle de versão, preferencialmente Git e uso do GitHub;
- Experiência com metodologias ágeis;
- Experiência anterior em plataformas SaaS.

## O que oferecemos:
- Salário: avaliaremos a pretensão salarial x expertise e background
- Vale transporte
- Vale­ refeição ou alimentação (R$20,60 por dia)
- Assistência médica (Unimed)
- Lanche na empresa
- Horários flexíveis
- Sem dress code por aqui :)
- Contato com novas tecnologias e tendências de mercado
- Um ambiente incrível <3

Se você tem esse perfil, inscreva-se no link: https://dito.recruiterbox.com/jobs/fk0fdx3/

**Comment by LFeh** [comment]
Bacana :)

**Comment by rodrigonehring** [comment]
olá :)

o banner do site de vocês está muito rápido, não tá dando tempo de terminar de lê ele 😞

**Comment by allansp9** [comment]
A empresa auxilia na realocação se o candidato for de outro estado?

**Comment by mari-dito** [comment]
@allansp9 Oi Allan, tudo bem? Candidatos de outro estado são bem vindos! Nós podemos auxiliar com a operação, mas hoje não oferecemos nenhuma ajuda de custo adicional para a mudança.

**Comment by HaluDeCassia** [comment]
@mari-dito então não existe chance de trabalhar remotamente?

**Comment by mari-dito** [comment]
Oi @HaluDeCassia, infelizmente não :/

**Comment by HaluDeCassia** [comment]
Ahhhh, que pena. Mas muito obrigada 😺

**Comment by marimeireles** [comment]
Alôu
O que quer dizer horários flexíveis?
Sou graduanda da UFMG e pra mim é difícil conciliar um trabalho de 8h/dia em um lugar longe da minha casa com a faculdade. Contudo, tenho disposição para estar com vocês alguns dias por semana.
É possível que o trabalho seja semi presencial?
Agradeço

**Comment by lucazweb** [comment]
Enviado!

**Comment by mari-dito** [comment]
Oi @marimeireles, é possível fazer uma carga horária menor em alguns dias e compensar em outros, se for interessante para ambas as partes, podemos negociar algo nesse sentido :)

**Comment by ReactGirl** [comment]
Sobre:

> Nós respeitamos e incorporamos as diferenças, por isso temos uma equipe tão **foda.**

O que a palavra em negrito se refere exatamente?

**Comment by mikaelhadler** [comment]
@mari-dito A vaga não está mais disponível? :/

**Comment by EduardoPaoli** [comment]
Oi! Tudo bem? 
Não foi possível candidatar na vaga, a página está com erro 404. 
Teria outro link? 
Obrigado.

**Comment by mari-dito** [comment]
@EduardoPaoli @mikaelhadler pessoal, a vaga já foi finalizada! Obrigada pelo interesse!
