### ISSUE TITLE
[Remoto] Front-end Developer na O2 Filmes

### ISSUE THREAD

**Issue by Roger-Siqueira** [frontendbr/vagas#8050]
## **Sobre Nós**

Imagine fazer parte de uma equipe que é um braço inovador da O2 Filmes, desenvolvendo um aplicativo web para um dos sócios da produtora. Na nossa empresa mantemos um ambiente de trabalho leve e altamente comunicativo para garantir qualidade no trabalho e agilidade nas entregas.

## **Descrição da Vaga**

Estamos à procura de uma pessoa desenvolvedora de front-end para se juntar à nossa equipe. A vaga é sem limite pré-definido, nosso projeto é predominantemente em Javascript, e estamos avançando na adoção do Typescript. No front-end, utilizamos principalmente ReactJS, enquanto nosso back-end é construído com Rails.

## **Requisitos Necessários**

- Sólida experiência em Javascript.
- Conhecimento de Typescript.
- Proficiência em Git.
- Experiência com Test-Driven Development (TDD).
- Habilidade para leitura e escrita em inglês.

## **Requisitos Desejáveis**

- Experiência com React.
- Familiaridade com Rails e Rspec.
- Experiência em Docker.

## **Responsabilidades Principais**

- Desenvolver e manter novas funcionalidades;
- Integrar com APIs externas e internas
- Criar elementos e componentes responsivos;
- Debugar as aplicações para identificar erros;
- Garantir a qualidade do código por meio de testes de componentes e telas, unitários e E2E.
- Colaborar com colegas para melhorar a usabilidade do produto.
- Utilizar o Git como ferramenta de versionamento.
- Aplicar os princípios do "clean code" em suas soluções.
- Contribuir com a documentação do projeto.
- Participar das dailies e demais reuniões técnicas.

#### Alocação

- Remoto

#### Regime

- PJ

#### Nível

- Sênior
- Especialista

Se você é um desenvolvedor apaixonado por desafios junte-se a nós nesta jornada. 
Envie o seu currículo e pretensão salarial, assim como portfolio se tiver, para [roger@o2filmes.com](mailto:roger@o2filmes.com). 

Estamos ansiosos para conhecê-lo!

**Comment by HenriqueGSena** [comment]
Enviado !!
