### ISSUE TITLE
[Florianópolis/SC] Front-end Developer na Yungas

### ISSUE THREAD

**Issue by ghedin** [frontendbr/vagas#8053]
## Nossa empresa

A Yungas é uma empresa de tecnologia líder em transformação digital no mercado de franquias brasileiro. Estamos em busca de pessoas com vontade de crescer e de fazer parte desse time referência!

- Somos protagonistas, temos iniciativa e agimos de forma construtiva, nos adaptando aos diferentes cenários e entregando grandes resultados. Vivemos a partir de uma cultura de experimentação e aprendizado acelerado.

- Nos preocupamos muito com a qualidade e em gerar valor e retorno aos nossos clientes.

- Trabalhamos em time para atingir nossos objetivos, de forma solícita e colaborativa.

- Gostamos de nos divertir: um clima de descontração e integração faz parte do nosso dia-a-dia.

Se você se identificou com os pontos acima e não quer ser só mais um na organização, na Yungas você encontrará um lugar onde poderá fazer a diferença!

## Descrição da vaga

Estamos em busca de novos engenheiros de software (+6 anos de experiência) que possam agregar o nosso time com sua experiência em programação web. Implementação de melhorias e novas funcionalidades no front-end, além de evoluir a arquitetura e qualidade de código.

Sua missão é capturar e compreender os problemas subjacentes do negócio de nossos clientes, esboçar possíveis soluções e transformar isso na entrega de valor de forma contínua e incremental.

Isso acontece através da manutenção de produtos existentes e da concepção de nova soluções, atuando lado a lado com equipes de Negócios, Customer Success, Produto e UX. Você fará parte de um time multi-disciplinar e altamente focado em gerar uma grande contribuição para o sucesso de diversos negócios no Brasil.

Espere encontrar tarefas que envolvem evolução e criação de novas funcionalidades, evolução da arquitetura e qualidade do código através de inclusão de testes automatizados e refactorings alinhados à estratégias de evolução do produto.

Você irá trabalhar no dia-a-dia principalmente com com TypeScript/Javascript no front-end, com uso do framework Svelte.

## Local

- Aceitamos candidatos com interesse em uma posição remota, mas daremos preferência para pessoas que possam atuar no modelo híbrido, onde será necessário estar 3x por semana em nosso escritório no **SC 401 Square Corporate** em Florianópolis-SC.

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com React ou Angular

**Desejáveis:**
- Conhecimentos em Docker
- Conhecimentos em Python

**Diferenciais:**
- Horário Flexível
- Oportunidade de Crescimento

## Contratação

CLT ou PJ a combinar

## Como se candidatar

Por favor envie seu CV através [deste formulário](https://jobs.quickin.io/yungas/jobs/65e601dd38f3a70013573979?src=Github).

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Remoto
- Híbrido

#### Regime
- CLT
- PJ

#### Nível
- Pleno
- Sênior

**Comment by joao160197** [comment]
Enviado

**Comment by joao160197** [comment]
Boa noite, respondi o formulário mas os dois últimos campos não estão permitindo escrever mais de 60 caracteres então não está dando para colocar a resposta Inteira da pergunta

**Comment by souzasmatheus** [comment]
Tive o mesmo problema em relação à limitação de caracteres

**Comment by ghedin** [comment]
Processo concluído.
