### ISSUE TITLE
[Remoto] Front-end React (plataforma Liferay) na ITeam 

### ISSUE THREAD

**Issue by ITeam-oportunidades** [frontendbr/vagas#8057]
> Atendimento remoto

## ITeam

Vinte anos presente no mercado, a ITeam oferece o comprometimento com o cliente.
Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 
Com uma equipe multidisciplinar, a ITeam proporciona uma área de Serviços Gerenciáveis como Projetos SAP, Fábrica de Software, Fábrica de Soluções e Sustentação. Neste modelo proporcionamos Sustentação, Melhorias e Desenvolvimentos de aplicação de forma integrada.

## Local

- Remoto (atendimento em horário comercial) 

## Requisitos

- Necessário ter experiência em desenvolvimentos na plataforma Liferay.
- Experiência com APIs, desenvolver portlets e implementar soluções utilizando JavaScript, CSS, HTML e React em ambientes Liferay.

## Atividades

- Desenvolver e consumir APIs na plataforma Liferay.
- Criar e implementar portlets na plataforma Liferay.
- Desenvolver interfaces de usuário utilizando JavaScript, CSS, HTML e React.
- Aplicar conhecimentos em Diretórios LDAP e AD dentro do ambiente Liferay.
- Colaborar na arquitetura de sistemas baseados em microserviços.
- Gerenciar e manipular dados em bancos de dados MySQL, Oracle e DB2.
- Utilizar ferramentas como Eclipse - Liferay Developer Studio, IntelliJ Community com Plugin Liferay e Visual Studio Code para desenvolvimento.
- Testar APIs utilizando ferramentas como Postman ou Insomnia.
- Gerenciar projetos utilizando Maven e Git.
- Implementar práticas de CI/CD e versionamento de código.

## Contratação

- 6 meses (renovável a cada 6 meses) 

## Como se candidatar

Por favor, envie um e-mail para viviane.pereira@iteam.inf.br com seu currículo anexado e pretensão salarial ou de taxa/hora PJ - enviar no assunto: Front react (Liferay)

## Labels

- React
- GIT
- CSS
- HTML
- JavaScript

## Regime
- PJ 

## Nível
- Pleno
- Sênior

**Comment by joao160197** [comment]
Enviado

**Comment by luizlopes12** [comment]
Enviado

**Comment by smithereens1998** [comment]
enviado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
