### ISSUE TITLE
[Remoto] Front-end Developer na Cadastra (antiga M3 Ecommerce)

### ISSUE THREAD

**Issue by andresatechrecruiter** [frontendbr/vagas#8058]
## Empresa: **Cadastra**

- site: https://cadastra.gupy.io/jobs/7082086?jobBoardSource=gupy_public_page
- linkedin: https://www.linkedin.com/company/cadastra/

## Descricao 
Quer fazer a diferença na nova economia e transformar pessoas e negócios para prosperarem? Vem pra Cadastra!

Como Front End Developer você irá desenvolver projetos de lojas virtuais na plataforma VTEX e Wordpress. Contribuindo para o desenvolvimento de aplicações que sejam acessíveis e ofereçam uma experiência de usuário consistente em diferentes dispositivos e tamanhos de tela.

## Atividades diárias 
- Suporte no Desenvolvimento de Lojas VTEX IO;  
- Participação em Projetos de Otimização de Performance;  
- Desenvolvimento Responsivo;  
- Colaboração e Comunicação Continuo com a equipe;  
- Desenvolvimentos de temas no VTEX IO e Wordpress;

## Requisitos e qualificações
- Ter experiência em Vtex;  
- Ter domínio em programação Javascript/Typescript, HTML, CSS e React, Next.Js.  
- Otimização de paginas web;  
- Desenvolvimento responsivo;  
- Conhecimento em Nodejs;  
- Conhecimentos de Wordpress;  
- Participar das estimativas do projeto.

## Benefios
- Vale alimentação e refeição no cartão FLASH🥗
- Auxílio Home Office no cartão FLASH 💳
- Plano de saúde de acordo com a sua localidade 🩺
- Plano odontológico de acordo com a sua localidade 🦷
- Day off de aniversário + valor depositado no cartão FLASH🎉
- Licença-maternidade e paternidade estendida 🍼
- Participação nos lucros (PLR) 💰
- Seguro de vida 🧡
- Auxílio creche 👶
- Bônus por indicação 💰
- Vale-transporte 🚍
- Clude | Plataforma de Saúde 🩺
- Total Pass 🏋🏽‍♀️
- CRM Bônus 💸

## Como se candidatar
Acesse https://cadastra.gupy.io/jobs/7082086?jobBoardSource=gupy_public_page

## Alocação
- Remoto

## Regime
- CLT

## Nível
- Pleno

## Sobre Nos 

Somos uma empresa global de serviços de tecnologia, estratégia, marketing e dados, com a missão de liderar transformações e estratégias digitais que trazem crescimento de canais digitais e físicos.

De maneira híbrida, estamos espalhados pelos nossos escritórios no Brasil e Reino Unido, além de vários outros Cadastrers (como nos chamamos por aqui) 100% remotos.

Na Cadastra, trabalhamos pelo mesmo objetivo: transformar pessoas e negócios para prosperarem.

Atuamos em divisões que aplicam soluções como next-gen company

Business & Strategy  
Commerce  
Media Services  
CRM & Customer Experience  
Digital Performance  
Data, Analytics & AI  
Design & Creativity  
Transformative Engineering  
Influence & Content Marketing  
Cloud Services

Somos especialistas no que fazemos e já fomos premiados pela excelência do nosso trabalho. Em 2022, fomos líderes no ISG Provider Lens Martech, vencedores do Salesforce - Partner Innovation Awards 2022, na categoria Consultoria na Área de Marketing, fomos indicados ao Prêmio Caboré, entramos na lista das empresas que mais crescem nas Américas, da Financial Times 2023, além de muitos outros reconhecimentos.

Não é só na parte técnica que mandamos bem, também valorizamos as nossas pessoas e vivemos a nossa cultura no dia a dia. Fomos rankeados 15 vezes como Great Place to Work, além das certificações GPTW Mulher e Rio Grande do Sul.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
