### ISSUE TITLE
[São Paulo] Angular Front-end Developer na Kanamobi

### ISSUE THREAD

**Issue by rubenmarcus** [frontendbr/vagas#806]
## Descrição da vaga

Trabalhar em um ambiente informal de organização horizontal, desenvolvendo aplicações Nativas, web, APIs, UX, participando desde a concepção da ideia até a entrega final, publicação e manutenção dos apps e web. Buscamos pessoas com foco em crescimento profissional e que tenha engajamento, queira aprender e discriminar seus conhecimentos com o demais colaboradores, dedicados e responsáveis.

## Local

Av. Marques de São Vicente 576 Cj 708 – Barra Funda - SP

Próximo ao Metrô Barra Funda (Linha Vermelha do Metrô)

## Benefícios

- Plano de saúde
- 13º
- PLR – Meta realizada 100% do salario
- Férias remuneradas
- Day off (aniversario) + vale presente R$ 50,00
- Flexibilidade de horários e vestuário a gosto.

## Requisitos

**Obrigatórios:**
- Lógica de programação, arquitetura e OOP
- HTML5/CSS3 (BEM , OOCSS)
- JavaScript 
- ANGULAR 
- Sass/Less
- GIT/GITFLOW
- NOÇÕES DE UX/UI 

**Desejáveis:**
- Conhecimento do Git Flow
- Familiaridade com o ambiente Linux e Mac
- Experiência com desenvolvimento para outras plataformas/linguagens
- Graduação em Design, Desenvolvimento de Software ou cursos afins
- Webpack

**Diferenciais:**
- projetos opensource

## Contratação

PJ a combinar

## Como se candidatar

Interessados enviar e-mail para [douglas@kanamobi.com.br](mailto:douglas@kanamobi.com.br) , com o assunto Vaga Desenvolvedor Front-End Kanamobi

## Labels

- Alocado
- PJ
- Pleno
- Remoto - Parcial
- Sênior

**Comment by victorhcosta** [comment]
Angular é a versão 1.x ou 2/4?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
