### ISSUE TITLE
[Remoto/LATAM] Full Stack Developer Internship - Holly HR

### ISSUE THREAD

**Issue by paulgould** [frontendbr/vagas#8060]
# Full Stack Developer Internship
## About [Holly HR](https://www.hollyhr.com/) 🌟

Meet Holly HR, a ambitious UK startup that simplifies HR tasks for small and medium-sized UK businesses.  Our philosophy is simple: cut through the jargon and complex features to deliver straightforward, user-friendly solutions. We aim to free up business owners to focus on what they truly love, rather than getting bogged down in HR tasks.

At Holly HR, collaboration takes precedence over hierarchy. We're a close-knit team of professionals from various backgrounds, all united by a shared vision. Our founders are seasoned entrepreneurs with a track record of innovation and success, guiding us towards excellence in all our endeavours.

We're on the lookout for **Full Stack Developers** based in **LATAM** for a **part-time, unpaid internship** lasting up to three months. 

This role is a fantastic opportunity:
- experienced front-end or back-end developers aiming to become full stack
- for those skilled in other programming languages who wish to transition to Typescript and Next.js/React
- to get real-world experience working for an international, english-speaking startup with cutting edge technologies
- **to be part of a team, early on in our story, where your work genuinely makes a difference**.

## Tech Stack 🛠

- React
- Next.js (App Router)
- Typescript
- PostgreSQL/Neon
- Drizzle ORM
- Tailwind CSS/UI
- Vercel/Serverless

## What We Offer 🚀

- **Professional Development**: Transition into full stack development or pivot into using Typescript and React, enhancing your technical skillset.
- **English Proficiency**: Work in an English-speaking environment to improve your language skills and gain confidence in international settings.
- **Commercial Experience**: Add valuable commercial project experience to your resume, working with cutting-edge technologies.
- **Potential Job Opportunities**: High performers may receive a job offer at the end of the internship, with potential for further collaboration.

## Requirements ✔

- 🌐 Good command of English, with eagerness to improve
- 💻 Strong foundational knowledge in any programming language with an interest in learning Typescript and React
- 🎓 Robust technical background, whether from a CS degree, bootcamps, or self-taught avenues like the Odin Project or freeCodeCamp
- 🚀 Experience in either front-end or back-end development, with a desire to expand into full stack roles
- 🧠 A curiosity-driven approach, passionate about learning and self-improvement
- 🌱 Self-motivation and capability to work independently and as part of a team

## Modality 🌍

- Fully remote, exclusively for LATAM engineers

## Contract Type 📄

- Internship, minimum 10 hours per week
- 1 to 3 months, stipend paid to cover costs, with potential for subsequent paid employment based on performance

## How to Apply 🚀

- Email [jobs@hollyhr.com](mailto:jobs@hollyhr.com) 
- Subject: "Mid to Senior Full Stack Developer - frontendbr/vagas"
- Describe why you believe you are an ideal candidate for this role, highlighting your career objectives and any relevant projects. Please provide a link to your professional profile or any relevant social media platforms such as GitHub, CV, LinkedIn, X, or your blog. Additionally, specify your available days and hours for contributing to the project.

For further questions about the role, team, or application process, please contact [jobs@hollyhr.com](mailto:jobs@hollyhr.com). We're excited to hear from you and potentially welcome you to our team!

**Comment by rafaelassumpcao** [comment]
This is pure joke, isn't it?

**Comment by eduardocappellotto** [comment]
Earns in GBP and cant afford to pay LATAM interns? OMG

**Comment by gabrielmendanha** [comment]
O golpe taí, caí quem quer KKKKKKKK

**Comment by fabriciofrontarolli** [comment]
If the company can't pay for internship, what garantees the company will be able to offer a paid job after 3 months?

**Comment by paulgould** [comment]
We're pre-launch and bootstrapped, and this opportunity is a stepping stone for someone who wants to improve their english, particularly conversational, move into a full-stack role or wants some real-world experience on their resume working for an international team. It's clearly not suited to everyone; and that's why it's an internship, but to the right person(s) could be hugely beneficial for their career. There's no guarantee for a paid job at the end, but equally if someone is amazing to work with, then there's a very strong possibility of an offer.

**Comment by gabrielmendanha** [comment]
Pra quem estiver seriamente considerando isso, aqui vai uma outra opção: existem projetos de código aberto em basicamente qualquer tecnologia, nacional e internacional, precisando de mão de obra pra ajudar a manter. É uma mão na roda pra quem quer mudar de stack, a comunidade irá lhe agradecer e fica mais bonito no teu currículo do que dizer que trabalhou apenas 3 meses em uma empresa gringa (os recrutadores vão ficar intrigados).

**Comment by paulgould** [comment]
> Pra quem estiver seriamente considerando isso, aqui vai uma outra opção: existem projetos de código aberto em basicamente qualquer tecnologia, nacional e internacional, precisando de mão de obra pra ajudar a manter. É uma mão na roda pra quem quer mudar de stack, a comunidade irá lhe agradecer e fica mais bonito no teu currículo do que dizer que trabalhou apenas 3 meses em uma empresa gringa (os recrutadores vão ficar intrigados).

I agree with this 100%. I've read 100s if not 1000s of resumes over the past 20 years, and if someone can demonstrate their actively involved in an open source project that definitely grabs my attention and would most probably get you shortlisted for the next recruitment stage. If you find a project that suits you then happy days.

> 3 months is a long time, in Brazil it is common to have a 3-month contract paying part of the salary and, if hired, full payment. But 3 months is a long time, people have bills to pay.

3 months is the maximum I had in mind, hence 'up to 3 months', within a month I think both parties have a good sense of whether there's enough in it for them to be worthwhile. I would strongly discourage any existing mid to senior full stack developer from applying who simply wanted a paid job at the end of it; there's no guarantee of that and you'd be better served applying for paid roles. If however you want to transition into full-stack, or your english isn't at a level that's getting you through the recruitment process; or you just want some real-world experience with an international company working 1-to-1 with successful founders (with successful exits) where you had the freedom to play a significant role in the development process; then maybe it's worth considering.

**Comment by fferreira12** [comment]
Esse post é um desrespeito não só com os profissionais de programação, mas também com todos os brasileiros. O cara do Reino Unido querer vir aqui fazer uma proposta dessas é inaceitável. Não tem dinheiro? Não contrate.

**Comment by cfdavidpetter** [comment]
After all, what is the value?

**Comment by fferreira12** [comment]
Unpaid = sem pagamento (famoso 0800)

**Comment by paulgould** [comment]
Given the strength of opinion of the comments, the value of this proposition was clearly not communicated well enough and I apologise for that, so I've updated the listing to better reflect our intentions; we'll also pay a monthly stipend to cover costs for the duration of the internship.

**Comment by guim0** [comment]
> Given the strength of opinion of the comments, the value of this proposition was clearly not communicated well enough and I apologise for that, so I've updated the listing to better reflect our intentions; we'll also pay a monthly stipend to cover costs for the duration of the internship.

Thanks Paul! good luck everyone!

**Comment by victorbiasibetti** [comment]
> In Brazil, we have an expression that goes something like this: "Only a clock works for free". Thanks!

kkkk, watch need battery for works, not even watch works free xD

**Comment by paulgould** [comment]
> @paulgould why you don't try recruit UK/EU/US guys for this role?

I love Brazil and Brazilian people, I’ve lived in São Paulo for a number of years and travelled all around Brazil, I speak pretty good Portuguese and worked with some great Brazilian and international developers who’s English isn’t their native language over the years. To me it seems like the obvious place to hire from.

**Comment by gustavros** [comment]
What a disrespect.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
