### ISSUE TITLE
[Home Office] Front-end Developer na Pasquali Solution

### ISSUE THREAD

**Issue by ecossistemadev** [frontendbr/vagas#8061]
## Descrição da vaga

Atuar no desenvolvimento front-end do sistema.

## Local

Home Office

## Requisitos

- Experiência comprovada de no mínimo 06 anos como Front-End e 03 anos com VueJS.
- Sólidos conhecimentos em Vue (versões 2 e 3), NuxtJS, Template Engine Blade (do Framework Laravel), Typescript, State Management (VueX ou Pinia), SCSS / SASS, TailwindCSS, testes automatizados utilizando Jest, nomenclatura BEM - Block Element Modifier, Git, Git Flow e Conventional Commits, HTML5/CSS3, JavaScript.
- Experiência com metodologias Scrum ou Kanban, Mobile First, Pixel Perfect, desenvolvimento front-end utilizando as melhores práticas de SEO e otimização de desempenho, desenvolvimento de Design System (Storybook), compreensão de todo o processo de desenvolvimento web (requisitos, design, desenvolvimento, controle de qualidade, implantação e manutenção) e consumo de APIs.

**Mais Informações:**

- Diferenciais incluem experiência com outras frameworks e bibliotecas JavaScript em geral (JQuery, React, Angular), conhecimento prático de PHP e Docker (utilização do dia a dia).

## Benefícios

- 20k

## Contratação

pj

## Como se candidatar

# [🔗 Clique aqui para se candidatar](https://empregos.dev/vaga/desenvolvedor-front-end-senior-6403)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 60 dias após cada processo.
E-mail para contato em caso de não haver resposta: 

#### Regime

pj

#### Nível

sênior

**Comment by matheusnpenna** [comment]
Enviado

**Comment by victorbiasibetti** [comment]
Alguem conseguiu se candidatar?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.

**Comment by felipelssilva** [comment]
Esta vaga foi encerrada já =/
