### ISSUE TITLE
[Remoto] Junior Front-end Developer

### ISSUE THREAD

**Issue by henryzybs** [frontendbr/vagas#8062]
## Nossa empresa

Workday é uma plataforma de software de gestão empresarial na nuvem que oferece uma ampla gama de soluções para gerenciamento de recursos humanos, finanças, planejamento e análise. É projetado para empresas de todos os tamanhos, desde pequenas empresas até grandes corporações, e visa simplificar e otimizar processos de negócios complexos.

## Descrição da vaga

Auxiliar no desenvolvimento e implementação de interfaces de usuário responsivas e intuitivas.
Colaborar com designers e desenvolvedores para traduzir designs em código HTML, CSS e JavaScript.
Garantir a compatibilidade entre navegadores e dispositivos.
Manter-se atualizado com as melhores práticas de desenvolvimento frontend e padrões de design.
Participar ativamente de revisões de código e sessões de brainstorming.

## Local

Remoto 

## Requisitos

**Obrigatórios:**
Conhecimento básico de HTML, CSS e JavaScript.
Familiaridade com frameworks frontend, como Bootstrap, React ou Vue.js (ou disposição para aprender).
Habilidade para trabalhar em equipe e comunicar-se de forma eficaz.
Capacidade de resolver problemas de forma criativa e eficiente.

**Desejáveis:**
- conhecimentos em reactJS ou Vue

## Benefícios

Aulas de Inglês
Auxilio estudo

## Contratação

 combinar

## Como se candidatar

Por favor envie um mensagem no Whatsapp wa.me/5548996356187
Aos cuidados de Fernando da BCI Consultoria

#### Alocação

- Remoto

#### Regime
- CLT
- Estágio
- Freela
- PJ

#### Nível
- Júnior

**Comment by netto0** [comment]
Enviado

**Comment by teixeira-alexandre** [comment]
Enviado.

**Comment by Nathanabrahao** [comment]
Enviado

**Comment by roger4yan** [comment]
Enviado

**Comment by petrucc1** [comment]
Enviado!

**Comment by mrzinofc** [comment]
Enviado!!!

**Comment by RobsonMT** [comment]
Enviado!

**Comment by teixeira-alexandre** [comment]
É górpi!

**Comment by gustavros** [comment]
> É górpi!

É, talvez seja golpe mesmo.

**Comment by teixeira-alexandre** [comment]
> > É górpi!
> 
> É, talvez seja golpe mesmo.

Talvez não, com toda a certeza. Que tipo de empresa recebe aplicações por WhatsApp, marca entrevistas instantaneamente e faz a entrevista técnica por escrito pelo Signal? Dica: nenhuma.

**Comment by gustavros** [comment]
> > > É górpi!
> > 
> > 
> > É, talvez seja golpe mesmo.
> 
> Talvez não, com toda a certeza. Que tipo de empresa recebe aplicações por WhatsApp, marca entrevistas instantaneamente e faz a entrevista técnica por escrito pelo Signal? Dica: nenhuma.

Estou discutindo com duas pessoas agora mesmo pelo Meet, e talvez seja golpe mesmo. 
(https://meet.google.com/qww-qcrk-mqb?pli=1

**Comment by jonathankarlinski** [comment]
ta muito estranho essa historia ai

**Comment by gustavros** [comment]
E esse Andrew nem existe. KKKKK

**Comment by andd38** [comment]
Se é golpe ou não , eu não sei  mas falei  com ele lá no signal

**Comment by andd38** [comment]
> E esse Andrew nem existe. KKKKK

Se é golpe ou não ,eu não sei mas falei com ele lá no signal

**Comment by jonathankarlinski** [comment]
o que ele te respondeu?

**Comment by teixeira-alexandre** [comment]
> > E esse Andrew nem existe. KKKKK
> 
> Se é golpe ou não ,eu não sei mas falei com ele lá no signal

Qual foi o papo do golpista? Te ofereceu dinheiro pra comprar equipamento? Signal é mundialmente conhecido por ser utilizado por scammers pois tem a funcionalidade de apagar todas as mensagens.

**Comment by andd38** [comment]
> o que ele te respondeu?

Ele é americano , ele disse que o tá correira pra entregar um projeto freelancer e que tá pagando em dol o serviço ,se dê tudo certo a gnt poderia fechar contrato, pelo o inglês dele me pareceu ser verídico.

**Comment by jonathankarlinski** [comment]
ele pediu seu numero tbm?

> > o que ele te respondeu?
> 
> Ele é americano , ele disse que o tá correira pra entregar um projeto freelancer e que tá pagando em dol o serviço ,se dê tudo certo a gnt poderia fechar contrato, pelo o inglês dele me pareceu ser verídico.

ele pediu seu numero tbm?

**Comment by andd38** [comment]
> > > E esse Andrew nem existe. KKKKK
> > 
> > Se é golpe ou não ,eu não sei mas falei com ele lá no signal
> 
> Qual foi o papo do golpista? Te ofereceu dinheiro pra comprar equipamento? Signal é mundialmente conhecido por ser utilizado por scammers pois tem a funcionalidade de apagar todas as mensagens.

Não, não sabia dessa sobre o signal

**Comment by teixeira-alexandre** [comment]
> > o que ele te respondeu?
> 
> Ele é americano , ele disse que o tá correira pra entregar um projeto freelancer e que tá pagando em dol o serviço ,se dê tudo certo a gnt poderia fechar contrato, pelo o inglês dele me pareceu ser verídico.

Bem, não custa alertar, não enviar dinheiro e nem divulgar dados pessoais. Pesquisei no LinkedIn da Workday e eles não possuem vagas abertas condizentes com essa issue, atualmente eles só estão contratando em regime híbrido.

**Comment by andd38** [comment]
> > > É górpi!
> > 
> > É, talvez seja golpe mesmo.
> 
> Talvez não, com toda a certeza. Que tipo de empresa recebe aplicações por WhatsApp, marca entrevistas instantaneamente e faz a entrevista técnica por escrito pelo Signal? Dica: nenhuma.

Se for por esse lado faz sentido

**Comment by lucasmachiner** [comment]
Galera pq estao dizendo que é golpe? qual o motivo? to falando com o cara mano e ele falou que a oportunidade é para um freela e se futuramente tiver disponibilidade haverá um contrato de trabalho. Agora a pouco pediu meu numero e eu passei para ele

**Comment by gustavros** [comment]
> Galera pq estao dizendo que é golpe? qual o motivo? to falando com o cara mano e ele falou que a oportunidade é para um freela e se futuramente tiver disponibilidade haverá um contrato de trabalho. Agora a pouco pediu meu numero e eu passei para ele

O problema é que nem o Fernando nem o Andrew existem no LinkedIn

**Comment by teixeira-alexandre** [comment]
> Galera pq estao dizendo que é golpe? qual o motivo? to falando com o cara mano e ele falou que a oportunidade é para um freela e se futuramente tiver disponibilidade haverá um contrato de trabalho. Agora a pouco pediu meu numero e eu passei para ele

Só olhar a conversa toda. Tudo muito suspeito. Não divulgue dados pessoais ou envie dinheiro. Nenhuma empresa pede essas informações fora do processo de onboarding.

**Comment by lucasmachiner** [comment]
> > Galera pq estao dizendo que é golpe? qual o motivo? to falando com o cara mano e ele falou que a oportunidade é para um freela e se futuramente tiver disponibilidade haverá um contrato de trabalho. Agora a pouco pediu meu numero e eu passei para ele
> 
> Só olhar a conversa toda. Tudo muito suspeito. Não divulgue dados pessoais ou envie dinheiro. Nenhuma empresa pede essas informações fora do processo de onboarding.

não pedir dinheiro nao irei passar mesmo, e nem dados pessoais como CPF, forneci somente o numero por enquanto, se ele pedir para enviar algum codigo q chegar por sms ai eu ja largo na banguela kkkk 
Mas como ja passei o numero vou ver o q dá mano

**Comment by teixeira-alexandre** [comment]
> > > Galera pq estao dizendo que é golpe? qual o motivo? to falando com o cara mano e ele falou que a oportunidade é para um freela e se futuramente tiver disponibilidade haverá um contrato de trabalho. Agora a pouco pediu meu numero e eu passei para ele
> > 
> > 
> > Só olhar a conversa toda. Tudo muito suspeito. Não divulgue dados pessoais ou envie dinheiro. Nenhuma empresa pede essas informações fora do processo de onboarding.
> 
> não pedir dinheiro nao irei passar mesmo, e nem dados pessoais como CPF, forneci somente o numero por enquanto, se ele pedir para enviar algum codigo q chegar por sms ai eu ja largo na banguela kkkk Mas como ja passei o numero vou ver o q dá mano

Se puder te pedir um favor, divulga pra gente o procedimento dele, depois que ele tentar te passar o golpe de fato, pra deixar a galera alerta.
Quer eliminar a dúvida de ser golpe? Pede o LinkedIn dele ou pede para ele te enviar um email usando o email oficial da empresa, Workday é uma gigante dos Estados Unidos com mais de 10k funcionários, eles não iriam fazer contratações desse jeito.

**Comment by lucasmachiner** [comment]
> > > > Galera pq estao dizendo que é golpe? qual o motivo? to falando com o cara mano e ele falou que a oportunidade é para um freela e se futuramente tiver disponibilidade haverá um contrato de trabalho. Agora a pouco pediu meu numero e eu passei para ele
> > > 
> > > 
> > > Só olhar a conversa toda. Tudo muito suspeito. Não divulgue dados pessoais ou envie dinheiro. Nenhuma empresa pede essas informações fora do processo de onboarding.
> > 
> > 
> > não pedir dinheiro nao irei passar mesmo, e nem dados pessoais como CPF, forneci somente o numero por enquanto, se ele pedir para enviar algum codigo q chegar por sms ai eu ja largo na banguela kkkk Mas como ja passei o numero vou ver o q dá mano
> 
> Se puder te pedir um favor, divulga pra gente o procedimento dele, depois que ele tentar te passar o golpe de fato, pra deixar a galera alerta. Quer eliminar a dúvida de ser golpe? Pede o LinkedIn dele ou pede para ele te enviar um email usando o email oficial da empresa, Workday é uma gigante dos Estados Unidos com mais de 10k funcionários, eles não iriam fazer contratações desse jeito.

faz sentido mano. Entao foda q o cara ta demorando dms para responder

**Comment by teixeira-alexandre** [comment]
Ele está fechando as issues nesse momento

**Comment by teixeira-alexandre** [comment]
> > > > > Galera pq estao dizendo que é golpe? qual o motivo? to falando com o cara mano e ele falou que a oportunidade é para um freela e se futuramente tiver disponibilidade haverá um contrato de trabalho. Agora a pouco pediu meu numero e eu passei para ele
> > > > 
> > > > 
> > > > Só olhar a conversa toda. Tudo muito suspeito. Não divulgue dados pessoais ou envie dinheiro. Nenhuma empresa pede essas informações fora do processo de onboarding.
> > > 
> > > 
> > > não pedir dinheiro nao irei passar mesmo, e nem dados pessoais como CPF, forneci somente o numero por enquanto, se ele pedir para enviar algum codigo q chegar por sms ai eu ja largo na banguela kkkk Mas como ja passei o numero vou ver o q dá mano
> > 
> > 
> > Se puder te pedir um favor, divulga pra gente o procedimento dele, depois que ele tentar te passar o golpe de fato, pra deixar a galera alerta. Quer eliminar a dúvida de ser golpe? Pede o LinkedIn dele ou pede para ele te enviar um email usando o email oficial da empresa, Workday é uma gigante dos Estados Unidos com mais de 10k funcionários, eles não iriam fazer contratações desse jeito.
> 
> faz sentido mano. Entao foda q o cara ta demorando dms para responder

https://github.com/backend-br/vagas/issues/11465

Presta atenção, ele agora está mudando o título das issues, tirando o nome da empresa Workday e marcando como completas. Fiquem de olhos abertos.

**Comment by MarcusVNT** [comment]
Eu conversei com ele também, a mesma situação que vcs disseram, aconteceu comigo. Ele me pediu o número, mas ainda não o respondi.

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by teixeira-alexandre** [comment]
Olha o mano ai, desistiu de recrutar pra Workday? Kkkkkkkkkk

**Comment by netto0** [comment]
Daqui a pouco fecha a issue kkk

**Comment by petrucc1** [comment]
Opa! To aqui pra saber os próximos capítulos também, a partir do momento que falei que não tenho inglês fluente e pediu meu número pra me ligar mesmo assim, não respondi mais

**Comment by teixeira-alexandre** [comment]
> > > > > Galera pq estao dizendo que é golpe? qual o motivo? to falando com o cara mano e ele falou que a oportunidade é para um freela e se futuramente tiver disponibilidade haverá um contrato de trabalho. Agora a pouco pediu meu numero e eu passei para ele
> > > > 
> > > > 
> > > > Só olhar a conversa toda. Tudo muito suspeito. Não divulgue dados pessoais ou envie dinheiro. Nenhuma empresa pede essas informações fora do processo de onboarding.
> > > 
> > > 
> > > não pedir dinheiro nao irei passar mesmo, e nem dados pessoais como CPF, forneci somente o numero por enquanto, se ele pedir para enviar algum codigo q chegar por sms ai eu ja largo na banguela kkkk Mas como ja passei o numero vou ver o q dá mano
> > 
> > 
> > Se puder te pedir um favor, divulga pra gente o procedimento dele, depois que ele tentar te passar o golpe de fato, pra deixar a galera alerta. Quer eliminar a dúvida de ser golpe? Pede o LinkedIn dele ou pede para ele te enviar um email usando o email oficial da empresa, Workday é uma gigante dos Estados Unidos com mais de 10k funcionários, eles não iriam fazer contratações desse jeito.
> 
> faz sentido mano. Entao foda q o cara ta demorando dms para responder

Atualiza a gente meu nobre! Qual o papo que esse cara te mandou?

**Comment by lucasmachiner** [comment]
> > > > > > Galera pq estao dizendo que é golpe? qual o motivo? to falando com o cara mano e ele falou que a oportunidade é para um freela e se futuramente tiver disponibilidade haverá um contrato de trabalho. Agora a pouco pediu meu numero e eu passei para ele
> > > > > 
> > > > > 
> > > > > Só olhar a conversa toda. Tudo muito suspeito. Não divulgue dados pessoais ou envie dinheiro. Nenhuma empresa pede essas informações fora do processo de onboarding.
> > > > 
> > > > 
> > > > não pedir dinheiro nao irei passar mesmo, e nem dados pessoais como CPF, forneci somente o numero por enquanto, se ele pedir para enviar algum codigo q chegar por sms ai eu ja largo na banguela kkkk Mas como ja passei o numero vou ver o q dá mano
> > > 
> > > 
> > > Se puder te pedir um favor, divulga pra gente o procedimento dele, depois que ele tentar te passar o golpe de fato, pra deixar a galera alerta. Quer eliminar a dúvida de ser golpe? Pede o LinkedIn dele ou pede para ele te enviar um email usando o email oficial da empresa, Workday é uma gigante dos Estados Unidos com mais de 10k funcionários, eles não iriam fazer contratações desse jeito.
> > 
> > 
> > faz sentido mano. Entao foda q o cara ta demorando dms para responder
> 
> Atualiza a gente meu nobre! Qual o papo que esse cara te mandou?

entao mano no momento eu so passei meu numero e até agora ngm falou mais nada, mas vcs sabem me dizem quem é esse mano do wpp?

**Comment by teixeira-alexandre** [comment]
> > > > > > > Galera pq estao dizendo que é golpe? qual o motivo? to falando com o cara mano e ele falou que a oportunidade é para um freela e se futuramente tiver disponibilidade haverá um contrato de trabalho. Agora a pouco pediu meu numero e eu passei para ele
> > > > > > 
> > > > > > 
> > > > > > Só olhar a conversa toda. Tudo muito suspeito. Não divulgue dados pessoais ou envie dinheiro. Nenhuma empresa pede essas informações fora do processo de onboarding.
> > > > > 
> > > > > 
> > > > > não pedir dinheiro nao irei passar mesmo, e nem dados pessoais como CPF, forneci somente o numero por enquanto, se ele pedir para enviar algum codigo q chegar por sms ai eu ja largo na banguela kkkk Mas como ja passei o numero vou ver o q dá mano
> > > > 
> > > > 
> > > > Se puder te pedir um favor, divulga pra gente o procedimento dele, depois que ele tentar te passar o golpe de fato, pra deixar a galera alerta. Quer eliminar a dúvida de ser golpe? Pede o LinkedIn dele ou pede para ele te enviar um email usando o email oficial da empresa, Workday é uma gigante dos Estados Unidos com mais de 10k funcionários, eles não iriam fazer contratações desse jeito.
> > > 
> > > 
> > > faz sentido mano. Entao foda q o cara ta demorando dms para responder
> > 
> > 
> > Atualiza a gente meu nobre! Qual o papo que esse cara te mandou?
> 
> entao mano no momento eu so passei meu numero e até agora ngm falou mais nada, mas vcs sabem me dizem quem é esse mano do wpp?

Provavelmente são todos a mesma pessoa

**Comment by petrucc1** [comment]
Só denunciar o criador do issue, já fiz isso.

**Comment by vitoropereira** [comment]
Tive a mesma experiência que vocês! Fiquei só na parte de dar meu número de telefone. Fiz isso porque teoricamente eles já tem. Se todo mundo tá com a mesma história, é golpe na certa, né? 🤷‍♂️😂

**Comment by victorbiasibetti** [comment]
carai, fechou a issue mesmo
certo que vai meter os numeros da galera num discador automatica pra vender consorcio ou hinode
