### ISSUE TITLE
[REMOTO]Front-end Developer @Weath99

### ISSUE THREAD

**Issue by Soonas** [frontendbr/vagas#8066]
**Our Company:** [Wealth99 ](https://wealth99.com/) is a company that acts on the CryptoCurrency and Tokenization of assets market.

We are searching for someone to fulfil a role that entails front-end development. The ideal candidate is someone who highly regards the user experience and has had previous roles as a Software Developer. A keen interest in evolving and developing great products with ease of use is a must.

**Essential Duties:**
- Work with agile methodologies helping to organise and maintain the backlog;
- Collaborate with the development and design team to translate business requirements into robust and scalable technical solutions;
- Architect and develop highly interactive and responsive user interfaces using Vue.js, applying best design and development practices;
- Contribute to continuous improvement of development processes, including code reviews, automated testing, and continuous integration;
- Stay updated with the latest trends and technologies in front-end development, sharing knowledge and insights with the team;
- Create responsive elements and components;
- Document developed code;
- Integration with external and internal APIs.

**Required Skills:**
- Mid-level English (B1 or higher);
- Proven Experience with Typescript;
- Proven Experience with  Vue.JS v 2.7 & Vue.Js v3.0;
- Experience with Web Design;
- Experience with version control systems (GIT);
- Proven experience with Tailwind CSS;
- Experience with developing automated tests for the front end. Including integration and unit testing.

**Preferred Skills:**
- Knowledge of the Capacitor.JS framework;
- Experience with Docker.

**What would make you stand out?**
Knowledge of Blockchain and Web3 applications.

**Benefits:**
- Flexible working hours;
- 100% Remote - Work from anywhere in the world;
- Paid Time Off (PTO);
- Birthday Day-Off;
- Global projects and multicultural teams with international colleagues.

**Working Regime:** Full-Time.
**Place of Employment:** Remote.
**Hiring Contract:** PJ.
**Salary:** **Mid:** R$5,000 - R$8,000 / **Senior:** +R$8.000.

**How to Apply:** You can apply by filling out this [Form](https://forms.gle/R2wiJGPNzX26DNmz7).

Contact email if you have any questions: luana@dacxi.com

**Comment by lucasvnborges** [comment]
Mil dolar 😂

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
