### ISSUE TITLE
[São Paulo] Treinamento Angular 2 na Grande Porte Treinamentos

### ISSUE THREAD

**Issue by ffborelli** [frontendbr/vagas#807]
## Descrição da vaga

Dar treinamento de Angular 2 em uma empresa na Zona Sul de SP, no período de 6/3 a 27/3, em horário comercial, das 9h as 18h.

## Local
Zona Sul, São Paulo, SP

## Requisitos

**Obrigatórios:**
- Ter boa didática
- Possuir conhecimentos sólidos em Angular 2.

## Contratação

PJ a combinar. Pagamento após o término do treinamento.

## Nossa empresa

A Grande Porte é um Centro de Treinamentos focado na formação de profissionais de TI que atendam as mais altas exigências do mercado de trabalho. Há 10 anos no mercado, já treinamos milhares de profissionais do mais alto-nível do mercado.

## Como se candidatar

Por favor envie um email para fabrizio@grandeporte.com.br com seu CV anexado - enviar no assunto: Treinamento Angular 2.

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
