### ISSUE TITLE
[Remoto] Igma | Front-end Developer - React e React Native 

### ISSUE THREAD

**Issue by mcfo-contato** [frontendbr/vagas#8070]
## Nossa empresa

Queremos cocriar um mundo onde experiências incríveis se tornem essenciais. Com coragem, entusiasmo e excelência, resolvemos desafios reais e aceleramos mudanças criando produtos digitais que geram impacto significativo para empresas e pessoas.

## Descrição da vaga

Estamos em busca de uma pessoa desenvolvedora Front-end para se juntar ao nosso Chapter de desenvolvimento e fortalecer **nosso time de pessoas alocadas em uma das maiores instituições de saúde da América Latina.**

Unimos tecnologia e design para resolver problemas complexos de empresas. Criamos produtos digitais que revolucionam o relacionamento entre empresas e consumidores.

## Local

Remoto

## Modelo de trabalho

- Regime: 100% remoto
- Modelo de contratação: PJ
- Escopo de trabalho: Alocação no cliente

## Requisitos Essenciais (nível pleno):

- React
- React Native
- Javascript & Typescript
- Styled-components
- Docker
- Trunk Based Development

## Responsabilidades e premissas para a posição

Na Igma Front-end é responsável por desenvolver soluções robustas, extremamente refinadas, escaláveis, de fácil manutenção e de alta performance. É essencial que tenha aptidão para trabalhar em equipe com profissionais de diferentes áreas, saiba se comunicar com clareza e tenha adaptabilidade para lidar com mudanças constantes.

Para isso é necessário fazer parte de sua rotina:

- Testes
- Consumo de API
- Versionamento
- Compiladores e pré-processadores
- Modularização de código
- Responsividade
- conhecimentos em ruby on rails
- conhecimentos em C#

**Premissas culturais**

- Coragem para realizar o que acredita
- Excelência na busca constante por superação
- Disposição genuína para se conectar com pessoas, sejam colegas, clientes ou parceiros
- Transparência para trabalhar em um ambiente de confiança
- Energia para realizar

## Etapas do processo

1. Cadastro
2. Entrevista inicial
3. Fit Cultural
4. Entrevista técnica
5. Entrevista no cliente
6. Proposta
7. Contratação

## Benefícios

:v: Trabalho 100% remoto
:blue_heart: Plano de Saúde individual
:lotus_position: Auxílio Cuidado e Desenvolvimento
:running: Incentivo à prática de esportes
:sparkles: Seguro de vida através do Betterfly
:credit_card: Cartão multi-benefício através do Caju
:computer: Auxílio Remoto para investimento em equipamentos (R$2.000 anual)
![beach](https://a.slack-edge.com/production-standard-emoji-assets/14.0/google-medium/1f3d6-fe0f.png) PJ - 30 dias de férias remuneradas

## Como se candidatar

Candidate-se no [link](https://jobs.polymer.co/igma-digital-product-company/30514?src=github#apply).

**Comment by RobsonMT** [comment]
Enviado!

**Comment by tiagolauer** [comment]
Feito!

**Comment by Mauricio2025** [comment]
enviado com sucesso.

**Comment by thiagopbraga** [comment]
Está vaga é 100% presencial porém está com label de Remoto.

**Comment by Mauricio2025** [comment]
Seria para qual cidade ?

Em qui., 23 de mai. de 2024 16:27, Thiago Pinto Braga <
***@***.***> escreveu:

**Comment by luizreboucas** [comment]
Enviado
