### ISSUE TITLE
[Hibrido / Joinville] Senior Frontend Software Engineer - React na LogisticTech  💶

### ISSUE THREAD

**Issue by logistictechrecruiter** [frontendbr/vagas#8071]
## Nossa empresa

We are a Logistics and Freight Technology Startup transforming road freight shipping. As a spinoff from a leading technology company in the logistics and transportation industry, we combine deep sector expertise with cutting-edge technology to innovate and push the logistics market forward. Our international team, based in the Netherlands and Brazil, is dedicated to entering and expanding new markets.

We are looking for talented senior software engineers passionate about radically transforming the logistics sector. Join us to build a groundbreaking product and collaborate with some of the biggest international logistics and transport companies.

## Descrição da vaga

As a Senior Frontend Software Engineer or Full Stack Developer, you will be responsible for building new features on our platform, delivering complete end-to-end solutions. From concept to implementation, you will be involved in every stage of feature development.

Frontend Focused Developer: Primarily work on backend development using React.

Roles require versatility, and you should be comfortable working across the full stack when necessary.

## Local

Híbrido em Joinville

### Responsibilities:
- Develop and implement new features for our platform.
- Work closely with the tech lead, other developers, and the Product Manager.
- Participate in Agile team activities, including daily stand-ups and weekly sprints.
- Ensure high code quality through code reviews and collaborative development practices.
- Contribute to a steep learning curve by sharing knowledge and best practices with team members.

### Requirements:
- 6+ years of experience in software development.
- Proficiency in frontend development with React.
- Proficiency in backend development with Node.js and TypeScript.
- Experience with automation and infrastructure in AWS.
- Experience in building SaaS products.
- English speaker

### Preferred Experience:
- Familiarity with logistics and transportation industry
- Experience working remotely and exceptional organizational skills.
- Motivation and enthusiasm for tackling new project challenges from start to production.

## Benefícios

- Competitive salary in Euros as a contractor (PJ).
- The opportunity to work with an international team.
- A dynamic and innovative environment where your ideas and contributions will make a real impact.
- Work with senior software engineers
- The chance to be part of a revolutionary startup in the logistics sector.
- The opportunity to grow in a international career
- Flexibility to work remotely. Hybrid in Joinville, SC, Brazil.
- ESOP (Employee Stock Ownership Plan) - 1 year cliff and Three years vesting 

## Contratação

PJ

## Como se candidatar

If you are passionate about technology and eager to revolutionize the logistics industry, we would love to hear from you!

Apply here: https://forms.gle/V1w15Djhg3oDoP7v8 

## Tempo médio de feedbacks

We are accepting application until 30/05. Steps of the Hiring Process 

- You apply using application form
- Screening and selection
- 1st Round
- 2nd Round
- Final Round 
- Offer

#### Alocação
- Hibrido
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by brcaua** [comment]
I'm not managing to upload my CV via the form. Do you have any email where I can send it?

**Comment by logistictechrecruiter** [comment]
> I'm not managing to upload my CV via the form. Do you have any email where I can send it?

Hi @brcaua , you can send me an e-mail at recruiter.logistictech@outlook.com. 

It is important to have all the application from the form. Could you send me the problem you are having by e-mail, then I can help you with the application.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
