### ISSUE TITLE
[Remoto] Frontend Developer Júnior/pleno (Angular) - Vem pra @Datum

### ISSUE THREAD

**Issue by julianakraemer** [frontendbr/vagas#8072]
## Nossa empresa

Somos uma consultoria de tecnologia que, há 24 anos, desenvolve soluções digitais que promovem crescimento para pessoas e negócios.
Nossos clientes se veem desafiados a implementar projetos inovadores, enquanto exercem o papel de liderança, engajando pessoas em um mundo cada vez mais não-linear e complexo.
Por isso, contratamos e retemos profissionais de alta performance para entregar soluções digitais com a agilidade que o negócio precisa.

## Descrição da vaga

Oportunidade Remota nível Júnior/pleno!

Se você é um entusiasta da tecnologia em busca de uma oportunidade para impulsionar sua carreira na área de TI, a Datum é o lugar perfeito para você!

Estamos em busca de talentos responsáveis, comprometidos e prontos para mergulhar em um ambiente dinâmico e desafiador.

Aqui você terá:

Acompanhamento especializado para auxiliar no desenvolvimento de soft skills;
Oportunidade de atuar em projetos de grandes empresas nacionais, nos mais diversos ramos;
Oportunidades de networking com profissionais experientes do setor de tecnologia.

## Local

 Remoto 

## Requisitos

**Obrigatórios:**
- Conhecimento em tecnologias front-end incluindo Angular, HTML5, CSS3 e JavaScript.
- Conhecimento em metodologias ágeis
- Experiência como estagiário ou cases completos de estudo

**Desejáveis:**
- Experiência prévia como estagiário em projetos de desenvolvimento

## Benefícios

INFORMAÇÕES ADICIONAIS
Nossos datunianos usufruem de benefícios e programas que atendem diversas áreas da vida.

Para sua saúde, oferecemos assistência médica e odontológica sem coparticipação em exames e consultas.
Seguro de vida
Quer mais bem-estar? Oferecemos Gympass, Zenklub (com duas sessões gratuitas por mês) e ginástica laboral para dar aquela alongada durante o expediente.
Quando bater aquela fome, utilize nosso benefício de alimentação Caju para fazer compras em qualquer supermercado ou restaurante.
Ama viajar? Aqui temos o Férias & Co, um benefício que te ajuda a viabilizar aquela viagem dos sonhos.
Tem filhos? Temos auxílio creche.
Quer aprender um novo idioma? Temos parceria com a escola CCAA, com descontos de até 40% nos cursos, e também o English Live que oferece 30% de desconto na mensalidade.
Para deixar seu ambiente de trabalho com a sua cara, conte com o nosso auxílio home office.
Quer protagonizar? Participe do Protagonistas, nosso game da vida real, e ganhe prêmios incríveis!

## Contratação

CLT

## Como se candidatar

Por favor envie um email para juliana.kraemer@datum.inf.br

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 semanas

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Júnior

**Comment by FelipeG-Almeida** [comment]
CV Enviado 🫡

**Comment by vanessawin** [comment]
Enviado!

**Comment by Mauricio2025** [comment]
Enviado com sucesso.

**Comment by MatheusZamo** [comment]
Enviado !

**Comment by jottaveDev** [comment]
Enviado!
