### ISSUE TITLE
[REMOTO] Front-end Developer JR na SolarMarket

### ISSUE THREAD

**Issue by solarmarket-dev** [frontendbr/vagas#8074]
## Nossa empresa

Somos uma empresa inovadora na área de energia solar, comprometida com a sustentabilidade e o crescimento contínuo. Estamos em busca de profissionais talentosos para se juntarem ao nosso time e crescer junto com a empresa.

## Descrição da vaga

O front-end atuará a frente de alguns sistemas desenvolvidos pela empresa, que são destinados a outras empresas do setor de energia fotovoltaica.

## Local

100% Remoto

## Requisitos

- Sólidos conhecimentos em HTML / CSS;
- Conhecimentos em Vue, React ou Angular;
- Experiência com controle de versão Git;
- Experiência com Typescript;

## Diferenciais (Opcional)
- Sólidos conhecimentos em Vue;
- Testes automatizados;
- Graphql
- Conhecimento e experiência com práticas de uma cultura DevOps;
- Experiência em times com metodologias ágeis

## Como se candidatar

indisponível

### Nível

- Júnior

### Regime

- PJ

### Alocação

- Remoto

**Comment by BrunaMaciel03** [comment]
enviado!

**Comment by BrunaEduarda03** [comment]
Enviado!

**Comment by marcusvictorpessoa** [comment]
Enviado!

**Comment by NTN1789** [comment]
candidatura enviada !

**Comment by jottaveDev** [comment]
Enviado!

**Comment by kazin-dev** [comment]
Enviado

**Comment by netto0** [comment]
Enviado!

**Comment by teixeira-alexandre** [comment]
Enviado.

**Comment by NTN1789** [comment]
> [CURRÍCULO DEV ATUALIZADO.pdf](https://github.com/user-attachments/files/15873314/CURRICULO.DEV.ATUALIZADO.pdf)
> 

Acho que essa vaga já foi finalizada

**Comment by highlsilva** [comment]
> > [CURRÍCULO DEV ATUALIZADO.pdf](https://github.com/user-attachments/files/15873314/CURRICULO.DEV.ATUALIZADO.pdf)
> 
> Acho que essa vaga já foi finalizada  

custa nada tentar

**Comment by NTN1789** [comment]
a vaga já tinha finalizado algum tempo e não adiantar tentar não . até pq atrapalhar a pessoa que divulgou a vaga
