### ISSUE TITLE
[Remoto] React.js Developer - Interaxa (Grupo Mutant) - [PL|SR]

### ISSUE THREAD

**Issue by jpventura** [frontendbr/vagas#8075]
## Nossa empresa

[Interaxa (Grupo Mutante)](https://interaxa.com/) é a  maior integradora de soluções de atendimento do Brasil, e o primeiro BSP em WhatsApp da America Latina.

Animado com a construção integrações de ponta para capacitar milhões de empresas latino-americanas?  Junte-se à equipe!
 
A [Interaxa (Grupo Mutante)](https://interaxa.com/) já está contratando para o cargo React.js Developer.

## Descrição da vaga

Você fará parte do time de Tecnologia, que é a área responsável por desenvolver, monitorar, melhorar e criar soluções referentes aos nossos produtos e sistemas.

Como desenvolvedor, você fará parte do time por trás do time que garantirá a estrutura, eficácia e sucesso de todas as plataformas e produtos da Interaxa.

Algumas das principais atividades dessa oportunidade são:

  - Detalhar junto ao time de Produtos as prioridades de desenvolvimento;
  - Desenvolvimento de novas funcionalidades;
  - Manutenção e evolução de sistemas existentes;
  - Garantir a qualidade de desenvolvimento;
  - vAutomação de testes;
  - Implantar as soluções desenvolvidas em ambiente produtivo.

## Local

 - Remoto
 
### Conhecimentos necessários

  - Mais de 4 anos de experiência em frontend em JavaScript e/ou TypeScript.
  - Criação de APIs RESTful
  - MVC padrão, MVP, MVVM, arquitetura limpa e derivados
  - React.js e Redux, MobX, ou XState
  - Padrões avançados de componentes React
  - Renderização do lado do servidor com Next.js
  - Desenvolvimento React Native
  - Promessa, Async/Await ou RxJS
  - Teste de unidade de jasmim, mocha ou karma

### Conhecimento desejável

  - MERN stack (Mongo, Express, React e Node.js)
  - 6+ anos de experiência de front-end
  - Firebase Analytics
  - Padrões de componentes do Advanced React
  - Renderização do lado do servidor com Next.js
  - Controle de estados com Redux ou Mobx
  - Teste de componentes com Enzyme ou Jest

### Conhecimento especializado

  - Criação e consumo de APIs RESTful
  - Amazon EC2, Amazon S3 e Amazon Lambda

## Contratação
  - PJ

## Como se candidatar

Por favor envie um email para jpventura@interaxa.com com seu CV anexado.
 Ao enviar, coloque como assunot **[Remoto] React.js Developer - Interaxa (Grupo Mutante) - [PL|SR]**

### Regime

- PJ
- Contrato

## Local

  - Remoto

## Labels

- 👨 Pleno
- 👴 Sênior
- ⚖️ PJ

**Comment by guim0** [comment]
Bom dia, enviado!

**Comment by joao160197** [comment]
Enviado, aguardando retorno

**Comment by jpventura** [comment]
Temporariamente encerrada devido excesso de candidadtos

**Comment by luanrv00** [comment]
fala @felipefialho! me intrometendo aqui pra tentar ajudar um pouquinho :D
Acho que esta issue já pode ser fechada de acordo com o comentário acima.

abs!
