### ISSUE TITLE
[Remoto] Vue.js Front-end Developer na Defsafe

### ISSUE THREAD

**Issue by Soonas** [frontendbr/vagas#8077]
### Nossa Empresa:
[Defsafe ](https://www.defsafe.com)é um sistema de cibersegurança com soluções impulsionadas por IA. Nosso produto oferece treinamento e teste de equipe, varredura abrangente do sistema e ferramentas de conformidade para manter você seguro. Possuímos três assistentes de IA, três pilares da cibersegurança. "Nova" treina sua equipe, "Iris" verifica seus sistemas e "Xen" mantém você em conformidade.

### O que buscamos:
Estamos em busca de um desenvolvedor frontend que se destaque na experiência do usuário e tenha um sólido histórico em desenvolvimento de software. O candidato ideal deve ter capacidade de criar produtos intuitivos e de alta qualidade, com ênfase na usabilidade e eficiência. Você trabalhará em estreita colaboração com nossas equipes de desenvolvimento e design para traduzir requisitos de negócios em soluções técnicas robustas e melhorar continuamente nossos processos de desenvolvimento.

### Tarefas Essenciais:
- Trabalhar com metodologias ágeis ajudando a organizar e manter o backlog;
- Arquitetar e desenvolver interfaces de usuário altamente interativas e responsivas aplicando as melhores práticas de design e desenvolvimento;
- Contribuir para a melhoria contínua dos processos de desenvolvimento, incluindo revisões de código e integração contínua;
- Manter-se atualizado com as últimas tendências e tecnologias em desenvolvimento frontend, compartilhando conhecimentos e insights com a equipe;
- Criar elementos e componentes responsivos;
- Implementar consultas de banco de dados usando APIs;

### Habilidades Requeridas:
- Inglês nível intermediário (pelo menos B1);
- Experiência comprovada com VueJS, Typescript, TailwindCSS, Prisma ORM e Git;
- Experiência com controle de código (GIT);

### Habilidades Desejáveis:
- Conhecimento do framework Supabase;
- NuxtJS + módulos NuxtJS (principalmente UI);
- Experiência com AWS (Cognito, Lambda, CloudWatch, API Gateway);

### O Que Faz Você Se Destacar?
- Inglês avançado;
- Conhecimento em CI/CD;
- Conhecimento em GenAI;

### Benefícios:
- Trabalho 100% remoto - Trabalhe de qualquer lugar do mundo;
- Projetos globais e equipes multiculturais;

### Contratação:
**Regime de Trabalho:** Full-Time;
**Local de Trabalho:** Remoto;
**Regime de contratação:** PJ;
 **Salário:**
- Júnior: R$3.500 - 4.500;
- Pleno: R$4.500 - 6.500;

### Como se Candidatar: Você pode se candidatar preenchendo este [Formulário](https://forms.gle/gUMq8L8dYaTSP4579).

**Tempo Médio de Resposta e retorno:** Geralmente fornecemos retorno dentro de 14 dias. Sendo selecionado(a) na peneira receberá um email especificando os próximos passos.

**Comment by HenriqueGSena** [comment]
Curriculo enviado

**Comment by RaphaelSchefflerF** [comment]
Currículo Enviado.

**Comment by lucopdev** [comment]
Currículo Enviado.
