### ISSUE TITLE
[Remoto] Frontend Developer na Coodesh

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#8078]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/desenvolvedor-front-end-151616747?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Olá,</p>
<p>Estamos em busca de <strong>Frontende Devloper,</strong> uma pessoa talentosa e motivada para se juntar à nossa equipe. O candidato ideal será responsável pelo desenvolvimento e manutenção de interfaces de usuário, utilizando as mais recentes tecnologias e melhores práticas em desenvolvimento web.</p>
<p><strong>Responsabilidades:</strong></p>
<ul>
<li>Desenvolver interfaces de usuário utilizando Angular, HTML, CSS.</li>
<li>Colaborar com a equipe de design para transformar wireframes e mockups em páginas web funcionais.</li>
<li>Garantir a performance, usabilidade e acessibilidade das interfaces desenvolvidas.</li>
<li>Integrar com APIs RESTful e colaborar com a equipe de backend para definir e implementar os requisitos técnicos.</li>
<li>Participar ativamente em revisões de código, garantindo a qualidade e a manutenção do código.</li>
</ul>
<p>Se você é apaixonado por desenvolvimento web e está procurando uma oportunidade para crescer e se desenvolver em uma empresa inovadora, fique À vontade para se candidatar.</p>
<p>Estamos ansiosos para conhecer você!</p>
## Otus7: 
 <p>Atendemos a empresas de grande porte que precisam potencializar a visibilidade e o entendimento do negócio e da jornada completa dos seus clientes, e querem aprimorar a capacidade de capturar, analisar e extrair valor dos dados para melhorar seus resultados operacionais e financeiros.</p>
<p>A Otus7 é uma empresa de serviços e soluções de análise e inteligência de dados, que habilita a geração de insights valiosos de forma automatizada, rápida e confiável, permitindo compreender e atuar sobre as perspectivas do que aconteceu, do porque aconteceu e sobre aquilo que pode acontecer, diferentemente de abordagens manuais, amostrais ou esporádicas, que geram alto esforço de extração, ruído na interpretação dos dados e análises limitadas.</p><a href='https://coodesh.com/companies/otus7'>Veja mais no site</a>

 ## Habilidades: 
 - Angular 
- Javascript 
- Typescript 
- HTML 
- CSS
## Local: 
 100% Remoto
## Requisitos: 
 - Sólida experiência com Angular, HTML, CSS e TypeScript. 
- Familiaridade com ferramentas como github, figma, Sonar Cube. 
- Capacidade de trabalhar de forma colaborativa em um ambiente de equipe ágil. 
- Boa comunicação e habilidades interpessoais. 
- Capacidade de resolver problemas de forma criativa e eficiente. 
- Forte atenção aos detalhes e compromisso com a qualidade. 
- Capacidade de aprender e se adaptar rapidamente a novas tecnologias e ferramentas.
## Diferenciais: 
 - Experiência com microserviços, Node.js, MongoDB e Redis. 
- Experiência em desenvolvimento backend com .NET Web API. 
- Experiência com ambientes linux, docker e conceitos de devops. 
- Interesse em atuar como desenvolvedor full stack, criando e mantendo endpoints de API quando necessário.
## Benefícios: 
 - Horários Flexíveis, Férias, Day Off 
- Salário competitivo. 
- Oportunidades de desenvolvimento profissional e crescimento na carreira. 
- Ambiente de trabalho colaborativo e dinâmico. 
- Flexibilidade de jornada.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Developer na Otus7](https://coodesh.com/jobs/desenvolvedor-front-end-151616747?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by HenriqueGSena** [comment]
Curriculo enviado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
