### ISSUE TITLE
[PARANÁ] Dev React/NextJS na DB1 Group

### ISSUE THREAD

**Issue by talentos-db1** [frontendbr/vagas#8080]
## Nossa empresa

Exemplo: Aqui na Corporação ACME somos líderes em...

## Descrição da vaga

Estamos em busca de uma Pessoa Desenvolvedora Sênior com experiência sólida em React, utilizando o framework NextJs com foco em e-commerce e marketplaces. Você irá impulsionar a inovação em nossa equipe de desenvolvimento, atuando em uma equipe dinâmica com muita autonomia. 
Nesta posição, você será responsável por arquitetar e desenvolver soluções técnicas avançadas, garantindo a entrega de produtos de alta qualidade e alto desempenho.

## Local

Preferencialmente com disponibilidade para atuar presencial ou híbrido nas cidades: Maringá, Londrina ou Campo Mourão.

## Requisitos

**Obrigatórios:**

- Experiência extensiva em desenvolvimento front-end com React;
- Profundo conhecimento em arquitetura de software e design patterns;
- Experiência com framework NextJS;
- Conhecimento em boas práticas de programação como Clean Code e SOLID;
- Experiência em abertura e inicio de novos projetos;
- Habilidades de resolução de problemas;
- Excelentes habilidades de comunicação e capacidade de influenciar decisões técnicas.

**Diferenciais:**

- Experiência com React Native;
- Experiência com metodologias ágeis.

## Benefícios

- Cartão de benefícios flexíveis (Alimentação, Mobilidade, Qualidade de Vida, entre outras categorias);
- Plano de Saúde Unimed - Com mensalidade 100% paga pela DB1;
- Plano odontológico (opcional);
- Seguro de Vida (opcional);
- Gift Aniversário;
- Bem-estar: parceria com plataforma de acesso a academias e outras atividades físicas, parceria para atendimento psicológico;
- Evolução de carreira: Parceria com plataformas e instituições de ensino, tanto para idiomas quanto para graduação, pós-graduação e cursos livres, Plano de Desenvolvimento Individual (PDI), feedbacks constantes, Programa de Mentoria, eventos internos, subsídio para treinamentos, universidade corporativa e muito mais;
- Programas de recompensa: bônus para indicação de novos colaboradores e bônus anual atrelado a metas;
- Espaço para assumir desafios e se desenvolver.

## Contratação

CLT

## Como se candidatar

- [Clique aqui e candidate-se](https://db1group.pinpointhq.com/pt-BR/postings/49301105-d105-49e6-a4b4-28bb84cb0833)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.

#### Alocação

- Híbrido

#### Regime
- CLT

#### Nível

- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
