### ISSUE TITLE
São Paulo | Minas Gerais] Front-end Developer Vip Commerce | Angular 8+

### ISSUE THREAD

**Issue by BarbaraAncieto** [frontendbr/vagas#8081]
## Nossa empresa
**Para qual empresa estamos trabalhando?** 

Integrando o ecossistema MagaLu e presente em mais de vinte estados do Brasil, a **VipCommerce** atende os maiores supermercadistas do país com o propósito de liderar a transformação digital no setor de varejo alimentar! 

Da tecnologia ao conhecimento especializado, a **VipCommece** fornece tudo o que o cliente precisa para digitalizar a sua rede supermercadista e proporcionar uma experiência omnicanal aos consumidores! Modelo logístico especializado, loja virtual, aplicativo, ferramentas de marketing, integrações com os seus sistemas, multilojas, suporte total, treinamento da sua equipe e muito mais. 

## Local

Escritório, [São Paulo], [São Paulo]
[Minas Gerais], [MG]

## Requisitos

**Obrigatórios:**

- Conhecimento e experiência em **Angular 8+** (AngularJS não atende);
- Conhecimento em Ionic;
- Experiência com Teste Unitário;
- Vivência em Microfrontend;
- Experiência com SEO;
- Experiência com Ambiente Linux é essencial.

**Desejáveis:**
Desejável experiência em Desenvolvimento orientado a objetos;
Consumir API Rest;
Experiência com PHP com LUMEN;
Experiência NodeJs com NESTJS.

**Diferenciais:**
- Conhecimento em metodologia Ágil: Scrum

## Benefícios

- – Vale Alimentação/Refeição
- – Auxílio Home Office
- – Gympass
- – Convênio Médico e Odontológico SulAmérica
- – PLR 
- – Auxilio Educação
- – Programa Indicação
- – Equipamento de Trabalho

**Diferenciais:**
- Oportunidade de crescimento
- ...

## Contratação
CLT

## Como se candidatar

Por favor envie uma mensagem para o telefone: **(11) 98081-1542** com seu CV anexado - enviar no assunto: Vaga Front End - Angular

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

#### Ferramentas
Angular 8
Ionic
Teste Unitário
Linux

#### Alocação
- Remoto
- Híbrido

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by HenriqueGSena** [comment]
Curriculo enviado

**Comment by BarbaraAncieto** [comment]
vaga fechada!!!!
