### ISSUE TITLE
[Remoto] Front-end Developer (React Native) na Apoia

### ISSUE THREAD

**Issue by fiuzagr** [frontendbr/vagas#8082]
## Nossa empresa

Somos a Apoia, uma empresa que acredita que a educação pode ser reinventada. 

Aqui, tecnologia e IA caminham juntas para transformar a forma como as pessoas aprendem e se desenvolvem.

Somos uma startup na fase de seed (validação). Contamos com um time super sênior com 9 pessoas, sendo 6 especialistas. 

[https://www.apoia.com.br/](https://www.apoia.com.br/)

## Descrição da vaga

(É OBRIGATÓRIO experiência comprovada de 2 anos com React Native entregando em produção. Sem essa exp. não iremos seguir com o processo.)

Precisamos de uma pessoa Front-End Developer com foco em React Native para nos ajudar a desenvolver nosso ambiente de estudos (LMS), onde os alunos irão consumir os cursos criados por IA.

Esse LMS é feito em React Native e entregue para Android, iOS e Web. Ele é altamente inspirado em grandes players de educação e a experiência é completamente gamificada.

O projeto está no início, próximo do lançamento da primeira versão "Minimum Marketable Product (MMP)". Foi iniciado utilizando o Expo SDK 51 + Nativewind v4 (Tailwind para React Native).

A pessoa que procuramos irá trabalhar diretamente com esse projeto, implementando novas funcionalidades e dando manutenção e suporte para as existente. Irá trabalhar diretamente comigo, especialista em Front-End na Apoia, onde darei todo apoio, suporte e direcionamento.

Procuramos pessoas que tem muito interesse em se desenvolver como profissional Front-End, que sejam responsáveis e engajadas para fazer sempre o seu melhor.

Somos um time muito unido, algumas pessoas aqui já se conhecem a bastante tempo. Confiamos na qualidade e responsabilidade das entregas de cada um. Somos sérios e damos feedbacks sinceros uns para os outros sempre com o máximo de respeito, visando o desenvolvimento de nossos colegas. Seguimos os valores da empresa e o desvio de valores é considerado grave, sendo motivo de demissão, não importando o cargo.

## Local

Remoto, apenas em território nacional. Fazemos encontros trimestrais para alinhamento, pagos pela empresa.

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Front-end
- 2 anos de experiência com React Native

**Desejáveis:**
- 

**Diferenciais:**
- 

## Benefícios

- Equity (você receberá um percentual da empresa)
- Plano de saúde
- VR de R$ 35/dia (~R$ 770/mês)

**Diferenciais:**
- Você será sócio e ganhará um bom valor caso a empresa seja vendida

## Contratação

Somente CLT

## Como se candidatar

Entre em contato comigo pelo LinkedIn [https://www.linkedin.com/in/fiuzagr/](https://www.linkedin.com/in/fiuzagr/)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior
- Pleno
- Sênior

**Comment by RaphaelSchefflerF** [comment]
Mensagem enviada👍🏻

**Comment by joaoprferreira** [comment]
Essa vaga está alinhada com minhas habilidades e experiências. Mensagem enviada!

**Comment by Jo4o20** [comment]
sou engenheiro da computação e estou buscando iniciar minha carreira como desenvolvedor, e adoraria fazer parte do time, mas não consigo mandar mensagem pelo linkedin, o que posso fazer?

**Comment by jp-xaxa** [comment]
Olá Guilherme, enviei mensagem como pedido, aguardo retorno!

**Comment by erikbrito** [comment]
Oi Guilherme, enviei o pedido de conexão. Essa vaga tá bem alinhado com a minha experiência. Fico no aguardo do retorno

**Comment by LinsThi** [comment]
Olá Guilherme, enviei o pedido de conexão. Olhando a descrição da vaga, fiquei bastante interessado! Fico no aguardo de um retorno.

**Comment by Ghabriel-elias** [comment]
Boa tarde Guilherme, mensagem enviada ;)

**Comment by marcelosoa** [comment]
Boa noite, pedido de conexão enviado.

**Comment by whalterduarte** [comment]
**Boa noite, pedido de conexão enviado.**

**Comment by ffernandescs** [comment]
Olá Guilherme, tenho interesse na vaga,gostaria de participar da seleção.

**Comment by fiuzagr** [comment]
A vaga foi preenchida, com ajuda do Front-end BR. Agradeço a todos os candidatos e peço desculpas aos candidatos que não pude atender. Foram muitos ao mesmo tempo e tomou bastante tempo na triagem.
