### ISSUE TITLE
[São Paulo] Full Stack Developer - Node.js + Angular

### ISSUE THREAD

**Issue by lisia-matos** [frontendbr/vagas#8083]
**DESCRIÇÃO DA VAGA**
A Aprova e a missão do time de Engenharia

A Aprova é Govtech líder em crescimento no Brasil. Nosso objetivo é utilizar o potencial da tecnologia para ajudar o governo a melhorar a vida das pessoas, impactando de forma positiva na redução do gasto com papel, no meio ambiente, na burocracia, evitando o deslocamento e reduzindo o tempo necessário para aprovações.

Em 2022, recebemos o nosso segundo aporte, no valor de R$ 22,5 milhões, liderado pela Astella e Vox Capital, passando a ser o maior investimento feito em uma Govtech da América Latina. Esses recursos vieram para impulsionar ainda mais os nossos produtos e alcançar nosso maior objetivo, tornar as prefeituras e câmaras 100% eficientes, menos burocráticas e digitais pra todos.

Nosso time de tech está em constante crescimento e estamos em busca de Software Engineers que queiram resolver grandes desafios, construir sua carreira com a gente e, juntos, desburocratizar este Brasilzão!

**Sobre a vaga:**
O Software Engineer colabora com equipes multidisciplinares para projetar e entregar um software funcional, com liberdade para garantir que as aplicações desenvolvidas estejam em conformidade com os padrões de codificação e design técnico. O Software Engineer trabalha em estreita colaboração com o Engineering Manager (Scrum Master), CTO e Product Managers para atingir esses objetivos.

> https://aprovadigital.gupy.io/jobs/7223618

**Como trabalhamos**

1. Os Product Managers realizam entrevistas, coletando dados da aplicação de uso e ouvindo stakeholders diversos e constroem a visão das features, que é uma documentação que norteará o desenvolvimento nos próximos 3-6 meses daquele problema/solução;
2. Em seguida o Product Manager quebra em pequenas entregas, e após input do Software Engineer em refinamentos a User Story entra em sprint, as sprints tem 15 dias e o Software Engineer estima em story points o que reflete esforço e complexidade;
3. O Software Engineer inicia a implementação seguindo requisitos técnicos amplos que garantem liberdade da abordagem a qual sempre pode ser validada com o Tech lead e CTO;
4. Possuímos um time de QA com uma suite de testes automatizados (end to end) o que ajuda o Software Engineer a garantir a qualidade da entrega;
5. Após isso a Pull Request sobe numa branch main (só possuímos uma branch) que depois é mergeada com o Jenkins. Estamos trabalhando para que esse processo seja cada vez mais automatizado via Terraform.
6. Realizamos releases diárias, entre 1-6 releases em horários fora de pico (18h). Todo o deploy leva em torno de 30 min.

**RESPONSABILIDADES E ATRIBUIÇÕES**

- Projetar, desenvolver e manter aplicações desenvolvidas pela companhia de maneira full stack, incluindo backend RESTful em TypeScript, NodeJS e Python, e frontend em TypeScript + Angular.
- Acompanhar a idealização de soluções de features a partir da necessidade desenhada e garantir uma comunicação/fluxo eficaz com o time de Produto, e partes interessadas, incentivando o time a compreender as entregas e as soluções propostas, com o olhar para o negócio e foco na entrega de valor para o cliente;
- Ser owner de todo o ciclo de vida do desenvolvimento de software, escrevendo códigos bem estruturados, eficientes e testáveis, participando de revisões de código produzidos pelos colegas, garantindo nosso atual padrão de qualidade e sugerindo melhorias em todos os processos.
- Compor a elaboração e execução de planos estratégicos conforme objetivos de negócio da empresa, em busca de entregas de impacto na escalabilidade da aplicação.
- Pesquisar novas tecnologias e ser o precursor da cultura da inovação, desenvolvendo e implementando boas práticas de software e disseminando estas práticas no time;
- Impulsionar melhorias significativas para um crescimento sustentável da aplicação, contribuindo com o design, arquitetura e na otimização das estruturas de dados de forma eficaz e inovadora.
- Elaborar testes unitários seguindo as guidelines que serão estabelecidas e mantendo-se atualizado com as tendências tecnológicas.
- Estabelecer comunicação eficaz com o time de Produto, e partes interessadas, para compreender as entregas e as soluções propostas.
- Disseminar conhecimento para o time, criando documentação técnica das tarefas entregues;
- Ser investigativo e atento aos incidentes: identificar gargalos e intensificar esforços no desenvolvimento do time para elevar a barra na qualidade nas entregas, propondo uma solução mais adequada e rápida;

**REQUISITOS E QUALIFICAÇÕES**

- Graduação completa em Analista de Sistemas, Ciência da Computação, Engenharia da Computação ou áreas afins.
- Experiência na elaboração e execução de projetos complexos de forma estratégica.
- Ser referência técnica, especialista em arquitetura da informação e ter cases de construção de aplicações escaláveis.
- Ser referência técnica nas nossas stacks:
- NodeJS, Typescript, Angular ou Vue ou React, MongoDB, e ferramentas da AWS.
- Experiência construindo produtos que são distribuídas no modelo SaaS - Software as a Service
- Habilidades de comunicação para explicar conceitos técnicos de forma clara e compreensível para o cliente e informar as ações de forma objetiva e coesa ao time.
- Residir na grande São Paulo/SP e ter disponibilidade para trabalho híbrido (ir no office 1 vez por semana).

**Diferenciais**
Esses diferenciais são características que estaremos observando, mas não são critérios eliminatórios. São pontos que contribuem para a análise do candidato, portanto, se você possuir alguma dessas experiências, compartilhe conosco durante o processo :)

- Experiência em construção de aplicações em paradigma DDD (Design Driven Domain)
- Experiência em construção de features de integrações (REST e SOAP)
- Experiência em implementação de tecnologias de filas como RabbitMQ
- Já ter trabalhado em empresas que crescem seu faturamento 2-3x ao ano (Startups)
- Experiência construindo produtos que são distribuídas no modelo SaaS - Software as a Service
- Ter vivência em aplicações com regras de negócio similares a da Aprova

**Nossa Stack**
Estamos baseados em uma arquitetura de microsserviços em ambiente serverless, totalmente suportada pelos recursos da AWS.

Backend:

- Implementamos um backend RESTful utilizando microsserviços serverless em TypeScript, NodeJS e Python. Isso nos permite criar uma base sólida para nossas operações, mantendo uma flexibilidade essencial.

Frontend:

- Em nosso frontend, usamos tecnologias como Angular, Vue e React para criar interfaces interativas e dinâmicas, proporcionando aos usuários uma experiência atraente e amigável.
- Práticas e Ferramentas:

- Utilizamos Domain Driven Design, RxJS e programação reativa para novas implementações.
- Mantemos 100% de nossa infraestrutura como código, seguindo as melhores práticas cloud native, facilitando a escalabilidade e a manutenção contínua.
- Utilizamos MongoDB e PostgreSQL como nossos sistemas de gerenciamento de banco de dados, proporcionando confiabilidade e flexibilidade para nossas necessidades variadas.
- Serviços AWS:

- Para suportar nossa arquitetura, confiamos em uma variedade de serviços da AWS, incluindo S3, SQS, RDS, Lambda, CloudFront, CloudFormation, entre outros. Isso nos permite oferecer aos nossos clientes serviços confiáveis e de alta performance.
- Automação e Gerenciamento:

- Implementamos integração contínua/desdobramento contínuo (CI/CD) usando Jenkins para garantir uma entrega rápida e confiável de nossos produtos.
- Para organização e gerenciamento eficazes de nossas tarefas de desenvolvimento, contamos com o Jira.
- Estamos continuamente refinando nossa Stack para enfrentar os desafios de escala e para garantir que possamos atender às crescentes demandas de nossos clientes de maneira eficaz e inovadora.

**BENEFÍCIOS:**
- Plano de Saúde Bradesco 100% pago pela empresa;
- Convênio Odontológico;
- Vale Refeição Swile;
- Seguro de Vida;
- TotalPass;
- Desconto para Psicoterapia em parceria com a Vittude;
- Licença paternidade de 20 dias;
- Day off para o seu aniversário;
- Equipamentos fornecidos pela empresa;

🔹Qualquer dúvida me chama no linkedIn [https://www.linkedin.com/in/lisia-matos-46162518b/] :]

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
