### ISSUE TITLE
[Brasil] Front-end Developer no Pagbank

### ISSUE THREAD

**Issue by Rmoreau21** [frontendbr/vagas#8089]
## Pagbank
Nascemos para democratizar os serviços bancários e de pagamentos!
Pioneirismo, tecnologia, inovação e resultados sustentáveis são constantes da nossa trajetória. Lançamos a primeira maquininha de cartão sem aluguel do Brasil e ao longo dos anos seguimos evoluindo para ampliar nosso ecossistema de soluções financeiras.
Somos o 2º maior banco digital do país e a fintech mais rentável do segmento, resultado do trabalho de um time formado por pessoas talentosas e criativas, que atuam com dedicação, paixão e vontade de fazer acontecer.
Se você ama tecnologia, curte um bom desafio e acredita no poder da colaboração para fazer grandes entregas, o Pags é pra você! Então, confira essa oportunidade e vem pintar o Brasil de amarelo com a gente💛!
No PagBank todas as pessoas são bem-vindas 😊, sem distinção de gênero, orientação sexual, etnia, cultura, religião, deficiência etc. O importante é você gostar de desafios, trabalhar bem em equipe, vivenciar nossa cultura e nossa missão de transformar e democratizar os serviços bancários e de pagamentos no Brasil.

#VemProPags

## Descrição da vaga

- Garantir que a experiência dos usuários seja a melhor possível, e aderente ao nosso design system e à nossa identidade visual.  
- Ser um agente integrador, com comunicação eficiente para unir as ideias de desenvolvedores de back-end, POs, UI e UX, entre outros envolvidos nos projetos.  
- Avaliar, discutir e definir arquiteturas de novos sistemas e propor melhorias para os atuais, promovendo a coesão técnica e a consistência dos processos do negócio, como base para solucionar os desafios.  
- Contribuir na evolução do design system.  
- Cuidar da monitoração do ambiente e criar ações proativas que garantam a sua estabilidade.  
- Manter contato com a equipe de segurança da informação para garantir a confiabilidade dos sistemas.  
- Trabalhar de forma colaborativa.  
- Atuar com métodos de gestão ágil e com melhoria contínua. 
- Compartilhar conhecimento e apoiar o crescimento dos outros membros da equipe. 

## Local

- [São Paulo] [Brasil] -  Vaga Hibrida para quem mora em um raio de 90km do Pagbank em São Paulo (4 Home Office X 1 Presencial). 
- Para quem mora em outros estados, o modelo é Full Home.

## Requisitos
**Obrigatórios:**
- Superior (completo ou cursando) em Tecnologia da Informação ou áreas correlatas. 
- Conhecimento em testes unitários utilizando Jest, Enzyme e React Testing Library.  
- Experiência com desenvolvimento de aplicações web utilizando JavaScript e ES6+.  
- Experiência com React + e Redux.  
- Experiência com pré-processadores CSS (Sass e LESS). 
- Experiência com integração com APIs RESTful.  
- Experiência com a aplicação de versionamento com Git.  

**Desejáveis:**

- Conhecimento em design patterns.  
- Conhecimento em DevOps (CI,CD, Cloud AWS, Jenkins, Docker e Kubernetes).  
- Conhecimento em boas práticas de usabilidade.  
- Conhecimento em tendências de tecnologias e engajamento na comunidade.  
- Experiência com programação funcional e mindset reativo. 
- Experiência com [Next.js](http://next.js/) e Server Side Rendering (SSR).  
- Experiência com arquitetura de integração com microsserviços (API Gateway, servidores web, BFF e [Express.js](http://express.js/)).  
- Experiência com formatação avançada BEM, JSS e Styled Components.  
- Inglês intermediário.

## Benefícios

- Vale-refeição/alimentação 
- Plano de Saúde e Odontológico
- Seguro de Vida 
- Auxilio Creche
- Cartão Farmácia
- TotalPass 
- Zenklub 
- No Dress Code
- Day off no aniversário 
- PagCare: orientação psicológica, nutricional, fisioterapêutica e educação física
- Inúmeras parcerias de Cursos e Certificados
- Vale-transporte (Hibrido)
- Outros

## Contratação

CLT

## Como se candidatar

Por favor envie um email para https://pagseguro.gupy.io/jobs/6507290 com seu CV anexado - enviar no assunto: Vaga Front End

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: https://pagseguro.gupy.io/jobs/6507290

#### Modelo de trabalho
- Remoto
- Híbrido

#### Regime
- CLT

#### Nível

- Pleno
- Sênior
- Especialista

**Comment by guim0** [comment]
Bom dia, fiz a candidatura no gupy, seria um email para reforçar minha candidatura?

**Comment by KaikySantos** [comment]
Na gupy, está como vaga híbrida.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
