### ISSUE TITLE
[São Paulo/SP] Front-End Developer na Leroy Merlin

### ISSUE THREAD

**Issue by ravanscafi** [frontendbr/vagas#809]
<p align="center">
    <br/>
    <a href="https://www.leroymerlin.com.br" title="Leroy Merlin">
        <img src="https://cdn.leroymerlin.com.br/assets/lizard/images/logo-leroy.svg" alt="Leroy Merlin"/>
    </a>
</p>

## Descrição da vaga
Estamos procurando novos integrantes para nossos times aqui na Leroy Merlin Brasil!

Crescemos de forma ordenada, sendo atualmente responsáveis pelo Site/E-commerce/Plataforma de Vendas das Lojas, além de outros projetos que estão surgindo e que você poderá ajudar a construir :smile:

Priorizamos qualidade e valor de negócio. Adotamos boas práticas de desenvolvimento como Testes Automatizados, Pair Programming, Code Review, entre outros, nos embasando em Metodologias Ágeis para o sucesso de nossos projetos e equipes. Estamos constantamente nos atualizando e buscando novas tecnologias que façam sentido para os nossos desafios. 

Valorizamos e contribuímos para o _open source_, tendo vários projetos publicados em @leroy-merlin-br.

Nossas stacks são basicamente `JavaScript (ES6)` com nosso [styleguide](http://styleguide.leroymerlin.com.br/). No e-commerce utilizamos `jQuery`, `PostCSS`, `Webpack` e um pouco de `React`.

## Local

**Presencial**, Chácara Santo Antônio - Zona Sul, São Paulo/SP

## Benefícios

- PPLR e outras bonificações
- Assistência Médica
- Assistência Odontológica
- Vale Refeição
- Vale Transporte
- Cesta Básica
- Seguro de Vida
... entre outros.

## Requisitos

Estamos buscando devs que tenham os seguintes conhecimentos:
- `HTML`
- `CSS`
- `JavaScript (ES6)` (se souber `React` é legal)
- `Testes automatizados`*

\* Caso você não possua conhecimentos em testes automatizados, haverá oportunidade de demonstrar sua capacidade de aprendizado em nosso teste prático.

## Contratação

CLT - Presencial

## Nossa empresa

A [Leroy Merlin](https://www.leroymerlin.com.br/) é líder em Home Center no Brasil.
Trabalhamos em projetos de transformação digital, atuando como e-commerce para nossos Clientes e plataforma de venda para nossos Assessores das Lojas no Brasil. Além disso, possuímos outros projetos em fase de desenvolvimento.

## Como se candidatar

Ficou interessado? Envie um e-mail para `rgomes@leroymerlin.com.br` com o assunto _”[Vaga-frontend]”_, informando seu GitHub/LinkedIn/Portfólio junto com o seu CV e bora bater um papo, que explicamos mais e nos conhecemos! :wink:

## Labels
- Alocado
- CLT
- Pleno
- Sênior

---
Também estamos com vagas de backend em aberto, confira em: [Desenvolvedor(a) Backend na Leroy Merlin](https://github.com/phpdevbr/vagas/issues/137)

**Comment by ravanscafi** [comment]
### Notas: 
1. Vagas de desenvolvimento são somente para São Paulo/SP, no momento não temos equipes de desenvolvimento em outras cidades onde possuímos lojas.
1. Vagas somente presenciais.
1. Se você já participou do processo seletivo antes, pode se aplicar novamente.

**Comment by LFeh** [comment]
Bela vaga ;)

**Comment by jamesodas** [comment]
@ravanscafi , você aconselha a participação de candidato que não mora em SP, mas que possui disposição para mudar de cidade?

**Comment by ravanscafi** [comment]
@jamesodas claro, James! temos muitas contratações nesse estilo, eu incluso! hahaha

**Comment by jamesodas** [comment]
Ótimo vaga! Enviarei e-mail ainda hoje.

**Comment by rands0n** [comment]
recomendo... <3

**Comment by iagocavalcante** [comment]
Para quem mora em outro estado, qual seria o prazo para mudança ?

**Comment by ravanscafi** [comment]
Fala @iagocavalcante, a ideia é que os novos integrantes comecem em breve.

Estamos abrindo processo seletivo algumas vezes ao ano, então caso você tenha alguma limitação por conta de conclusão de curso/etc, talvez possa esperar até que esse prazo fique mais curto e se aplique mais pra frente :)

**Comment by iagocavalcante** [comment]
Entendi, obrigado, minha limitação no caso é o casamento kkkkk, após maio se tiver outra vaga, aplicarei, grato pela atenção @ravanscafi !

**Comment by hjdesigner** [comment]
Enviado

**Comment by wensch** [comment]
Enviado

**Comment by ravanscafi** [comment]
Boa tarde pessoal!
Informo que ainda temos vagas :wink:

**Comment by eduardojmatos** [comment]
@ravanscafi ainda aberta? Só pra manter ou não aqui nas issues

**Comment by ravanscafi** [comment]
sim @eduardojmatos :wink:

**Comment by MrS4w** [comment]
@carusogabriel o limite para dar manutenção á issue era de até 14 dias, estamos em transição para 3 meses, como pode ver em #1931  
Todavia você pode abrir outra issue :smile:
