### ISSUE TITLE
[Híbrido - SP] Front-end Developer na VolttaFitness.

### ISSUE THREAD

**Issue by Vfitness** [frontendbr/vagas#8090]
## Nossa empresa

VOLTTAFITNESS Somos uma start-up fitness com apoio da USP.

## Descrição da vaga

Somos uma start-up fitness com apoio da USP e precisamos de Front-End Developer.
- Não precisa de experiencia
- Residir em SP
- Poucas horas: 10 horas semanais
- Bolsa GARANTIDA da FAPESP: R$ 1900/mês sem imposto
- Possibilidade de negociar complementação da bolsa a depender das demandas do projeto
- Bolsa de treinamento técnico
- Conta no CV da pessoa
- Precisa de diploma
- Duração 5 meses, podendo ser expandido por mais 24meses e com aumento no valor da bolsa de acordo com o andamento do projeto

## Local

Híbrido residente em SP

## Requisitos

**Obrigatórios:**
- Linguagem react native

## Contratação

EX: Freelancer

## Como se candidatar

Por favor envie um email para contato@volttafitness.com com seu CV anexado - enviar no assunto: Vaga Front Voltta

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
#### Regime
- Freela

#### Nível
- Júnior
- Pleno

**Comment by JP3015** [comment]
Currículo enviado :)

**Comment by VitorVeector** [comment]
Enviado!
