### ISSUE TITLE
[REMOTO] Video Web Developer JavaScript

### ISSUE THREAD

**Issue by SebastianStifler** [frontendbr/vagas#8091]
## Sobre a empresa
Somos uma empresa de tecnologia em publicidade (AdTech) reconhecida como parceira do Google Publishing, dedicada à otimização de inventários de anúncios para editoras profissionais. Através de um modelo inovador de compartilhamento de receitas, impulsionamos a monetização de anúncios para sites conectados à nossa conta AdX. Como uma startup em crescimento, valorizamos uma cultura de responsabilidade, desenvolvimento pessoal contínuo e abordagem proativa aos desafios tecnológicos e de negócios.

## Descrição da vaga
Manutenção e otimização de scripts de anúncios em vídeo nos sites dos clientes. Responsável por analisar desempenho, corrigir bugs, implementar melhorias, garantir compatibilidade com IMA SDK, realizar testes de qualidade e fornecer suporte técnico. Colaboração com equipes internas para alinhar objetivos técnicos e de negócios, assegurando uma experiência de usuário eficiente e sem interrupções.

## Local
Remoto

## Benefícios
Salário competitivo
Oportunidades de desenvolvimento profissional em uma startup em crescimento rápido
Ambiente colaborativo e inovador de trabalho remoto
Horário flexível e liberdade de localização
Contrato PJ

## Requisitos
- Experiência Obrigatória nível Senior ou equivalente: JS, HTML, CSS
- Experiência com web video players e IMA SDK é um plus
- Conhecimento em Ruby on Rails e NodeJs desejável também.

## Contratação
- PJ 

## Como se candidatar

Por favor envie um email para [stiflerandballer@gmail.com](mailto:stiflerandballer@gmail.com) com seu CV anexado - enviar no assunto: Video Web Developer JavaScript

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by jhefflg** [comment]
Up!!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
