### ISSUE TITLE
[Remote] Wordpress Developer Senior with Fluent English - Brazil residents only na HunterHunter

### ISSUE THREAD

**Issue by ErickaMB** [frontendbr/vagas#8092]
Wordpress Developer Senior with Fluent English - Brazil residents only

Company is a branding & web design studio Saudi Arabia based in London.

Hours - Full time, 37.5 hours per week to work KSA timezone - 6 horas a mais de Brasília.

THERE'S A TEST TO BE TAKEN OF A CERTAIN COMPLEXITY AND LENGTH AND THE COMPANY REQUIRES 4 DAYS TO COMPLETE IT, SO ONLY APPLY IF YOU ARE AVAILABLE TO TAKE THE TEST AT THE REQUIRED TIME.

Salary will be paying in SAR - which is Saudi Arabia currency - (between R$8 a R$12 mil reais).

Remote. All communications and interviews will be in English.

Requirements:
● Over 4 years experience as an Wordpress Developer.
● A sophisticated understanding of HTML semantics and ARIA roles, and knowing their correct application.
● Proficient in writing maintainable CSS / SCSS with a strong understanding of Flexbox & experience working with responsive web design CSS frameworks, such as Bootstrap / Semantic UI e.t.c.
● Entry level knowledge of Vanilla JavaScript, ES6, jQuery.
● Familiar with npm, yarn and build tools such as Parcel, WebPack and Gulp.
● Knowledge of WordPress custom theme development, template hierarchies, hooks and filters.
● Good problem solving and communication skills.
● Experience with implementing blocks using Gutenberg in WordPress would be a bonus
● Good knowledge in PHP as a programming language.
● Understanding of a relational database like MySQL/MariaDB.
● Experience with version control, ideally Git
● Able to take user feedback and work on self improvements.

Preferred:
● Strong programming base and computer engineering background.
● Knowledge of open-source WordPress theme boilerplates and differences between them
● Familiar working with tools like Figma
● Familiarity with cloud providers, such as Cloudways, WP Engine, AWS, Google Cloud Platform and Digital Ocean.

Responsibilities:
● Convert designs from Figma into pixel-perfect responsive web pages.
● Work on existing projects and make changes as required.
● Develop custom Gutenberg blocks using Carbon fields.
● Maintain sites built with Gutenberg, Piklist or bespoke solutions.
● Participate in sprint planning discussions.
● Work closely with designers on implementing designs into code.
● Measure and optimize overall web page performances.
● Work closely with senior developers, project managers to ensure projects are delivered in a timely fashion.
● Provide timely and accurate estimates for project deliverables.
● Hands-on troubleshooting, debugging and fixing of issues during development and post-release for customer support.
● Write and maintain detailed technical documentation.

Se tem interesse e os requisitos da oportunidade entre em contato pelo Linkedin abaixo, informando qual é a oportunidade:[https://www.linkedin.com/in/erickamarquesb/]

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
