### ISSUE TITLE
[Remoto] Pessoa Engenheira de Software Frontend Sênior - React/VueJS - RD Station 

### ISSUE THREAD

**Issue by TARDStation** [frontendbr/vagas#8093]
## Nossa empresa
Somos a [RD Station](https://bit.ly/3RyakzX), líder em soluções de tecnologia no Brasil. Nossa plataforma de automação de marketing e vendas é líder no Brasil e soma mais de 50.000 clientes, em mais de 40 países. Como alcançamos tudo isso? Através do nosso [A-team](https://bit.ly/3ZUPopc), composto por mais de 1.500 pessoas colaboradoras em nosso grupo, capaz de oferecer soluções, produtos, e educar o mercado, impactando o ecossistema e empoderando heróis e heroínas que fazem a economia crescer.

 ## Descrição da vaga
A partir da nossa visão sistêmica nos conectamos com pessoas, times e clientes facilitando o uso das ferramentas de forma integrada para pequenas e médias empresas, porque queremos democratizar e potencializar o processo de vendas e marketing, revolucionando a experiência multiproduto.

Você estará no time de Engenharia do produto RD Station Conversas responsável pela evolução do chatbot, implementando Inteligência Artificial dentro do produto RD Conversas.
Você contará com o apoio de pessoas na posição de Team Leader, Product Manager, Designer e Fullstack Developers, além de toda a galera dos chapters, guildas e tribos pra te ajudar a tracionar suas entregas como Senior Software Engineer.

## Local
Remoto

## Requisitos

- Experiência com desenvolvimento frontend, na linguagem React e/ou VueJS;
- Experiência com testes, como TDD ou testes automatizados;
- Experiência sólida na construção de arquiteturas sustentáveis e escaláveis;
- Estar habituado com Operação (incidentes e bugs);
- Experiência com ferramentas de observabilidade, como Datadog e Grafana;
- Vivência com boas práticas de desenvolvimento, como Clean Architectures e entre outras.

**Características que somam pontos…**

- Interesse em trabalhar na linguagem VueJS;
- Experiência com metodologias ágeis de entrega, Scrum ou Kanban;
- Experiência com integração de banco de dados como Postgree, Elastic Search;
- Ser (ou querer se tornar) uma pessoa ativa na comunidade, que compartilha conhecimento dentro e fora da empresa através de eventos, artigos, mentorias, iniciativas voluntárias, projetos open source, etc.

## Benefícios
Link dos nossos benefícios [aqui](https://talent.rdstation-tm.com/beneficios-rdstation).

## Contratação
CLT

#### Nível
- Sênior/Especialista

## Como se candidatar
Para se candidatar é só clicar [aqui](https://grnh.se/47b03a6b2us).

**Comment by erikbrito** [comment]
Vaga com titulo de frontend e descrição de backend. Tá errado isso ai

**Comment by MCiappina** [comment]
Me inscrevi!
