### ISSUE TITLE
[São Paulo] Front-end Developer na Happmobi

### ISSUE THREAD

**Issue by Diegoa83** [frontendbr/vagas#8094]
**Nossa empresa**
Somos a Happmobi: uma startup com soluções de Edtech que nasceu para transformar a educação corporativa online. Utilizamos de muita tecnologia e métodos para oferecer experiências de aprendizagem impactantes que não partem de achismos, mas, sim, de dados reais. Esses dados trazem insumos detalhados que são coletados nos treinamentos online, fornecendo informações valiosas sobre os conhecimentos técnicos e também sobre os comportamentos dos colaboradores. É assim que planejamos, juntos, ações educacionais mais assertivas, que proporcionam maior engajamento e favorecem o crescimento das empresas. É desta forma que estamos transformando a educação corporativa online.

**Descrição da vaga**
A Happmobi está selecionando novos profissionais para o time de tecnologia. Precisamos de desenvolvedores Front-end com nível técnico pleno.

Quer fazer parte da nossa seleção? Conhece alguém que está procurando um time pra jogar?

**Local**
Hibrido - São Paulo

**Requisitos**
Atividades e responsabilidades - Realizar manutenções, melhorias e atualizações em códigos legados, bem como desenvolver novas funcionalidades;
- Escrever códigos claros e eficientes, utilizando boas práticas de desenvolvimento;
- Auxiliar a equipe na concepção e planejamento de novas funcionalidades; - Documentar o desenvolvimento no decorrer das sprints;

O que você precisa saber pra concorrer a vaga: - Experiência mínima de um ano e meio com desenvolvimento front-end utilizando frameworks em Typescript; - Noções de UI/UX; - Conhecimentos sólidos em HTML - Conhecimentos sólidos em CSS (SCSS, SASS ou LESS); - Conhecimentos em bancos de dados SQL/NoSQL; - Experiência na integração com REST API; - Vivência com metodologias ágeis;

O que te faria se destacar? Vamos lá: - Experiência em desenvolvimento utilizando Angular - Experiência em desenvolvimento mobile - Boas práticas de desenvolvimento (SOLID e Design Patterns)

**Detalhes da contratação:**
😏 Contrato de PJ
😎 Férias remunerada
🤑 13º Pagamento

**Como se candidatar**
Mande um e-mail com currículo anexo para
👍 [selecao@happmobi.com.br](mailto:selecao@happmobi.com.br) No campo assunto coloque
👍 [ Seleção Tecnologia ] – Vaga Front-end Developer

#### Alocação
- Híbrido

#### Regime
- PJ

#### Nível
- Pleno

#### Conhecimento
- CSS
- HTML
- TypeScript
- JavaScript
- Angular

**Comment by pablokaue2004** [comment]
Enviado!

**Comment by Gabrieldebritobasilio** [comment]
Enviado!
[Gabriel Curriculo (1).pdf](https://github.com/user-attachments/files/16059962/Gabriel.Curriculo.1.pdf)

**Comment by joao160197** [comment]
Enviado

**Comment by odntht** [comment]
@felipefialho a tag Remote tá errada, é só Híbrido mesmo XD

**Comment by joao160197** [comment]
Enviei o teste semana passada e gostaria de saber em quanto tempo mais ou menos vocês respondem se passou ou não pra próxima etapa?

**Comment by GabrieIIeaI** [comment]
@Diegoa83 Enviado.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
