### ISSUE TITLE
[Internacional e Remoto] Senior React & React Native Developer na Lemon.io

### ISSUE THREAD

**Issue by tatidirienzo** [frontendbr/vagas#8097]
## About
Are you a talented senior developer looking for a remote job that lets you show your skills and get better compensation and career growth? Look no further than Lemon.io - the marketplace that connects you with hand-picked startups in the US and Europe.

## What do we offer:

- We respect your time: here is no micromanagement or screen trackers.
- You can earn with us $5k - $8,5k monthly - the rate depends on your skills and experience. We've already paid out over $10M to our engineers.
- You will enjoy your work - it’s possible to communicate async and choose a schedule that works best for you.
- You will communicate directly with the clients. Most of them have technical backgrounds. Sounds good, yeah?
- We will support you from the time when the application will be started during all our cooperation.
- No more hunting for clients or negotiating rates - let us handle the business side of things so you can focus on what you do best.
- We'll manually find you the best project according to your skills and preferences.
- You will work in a fast-paced startup environment that will keep you motivated and engaged.
- We will connect you with the best developers in the world through our community.
- We also collaborate with other companies through staff augmentation. 

## Who we are looking for:

- Senior Software Developer
- Senior+ Software Developer

**Requirements:**

- 4+ years of commercial work experience in software development
- Expert-level knowledge of React & React Native
- Knowledge of Next is a must
- Hands-on experience with Node, Typescript, AWS is a huge plus
- Hands-on experience with REST APIs and
- Experience in React Native application deployment to App Store and Google
- Good command of English, both written and spoken, as you’ll be communicating with clients directly
- Strong organizational skills — ability to work full-time remotely with no supervision
- Responsibility — we want to trust you
- Soft skills — we don’t ask you find a topic for a small talk, but being just polite is OK

ALSO, we have a large number of different projects for Senior Full-Stack Developers, so if you have 4+ years of commercial experience in software development you are fluent with Android & iOS, React & Ruby, React & Python, React & PHP, DevOps Engineering, UI/UX Design - we would be happy to communicate and provide you a project which matches with your experience. Just apply, and we will share with you more details.

Ready to take your career to the next level? Apply now and join the[ Lemon.io](https://lemon.io/escape-the-matrix/?utm_source=remotar&utm_medium=job_ad&utm_campaign=supply_en_fullstack_react/reactnative_jun_2024_job_ad) community!

If your experience matches with our requirements be ready for the next steps:

1. VideoAsk - you need to watch a short video about our startup, it takes up to 10 minutes
2. Completing your me.lemon profile
3. 30 minutes Screening call with our Recruiters
4. Technical Interview with our Developers
5. Feedback
6. Magic Box (we are looking for best project for you)

## Como se candidatar

Acesse o site da [Lemon](https://me.lemon.io/escape-the-matrix?utm_source=remotar&utm_medium=job_ad&utm_campaign=supply_en_fullstack_react%2Freactnative_jun_2024_job_ad) para aplicar para a vaga.

Obs: esta vaga está sendo publicada pela [Remotar](https://remotar.com.br/?utm_source=github) em nome da Lemon.io. A Remotar é uma plataforma de vagas remotas que ajuda seus clientes com a divulgação das posições abertas. No entanto, não somos responsáveis pelo processo seletivo das mesmas.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
