### ISSUE TITLE
[São Paulo] Front-end Developer Angular na Nexmuv

### ISSUE THREAD

**Issue by HelenNexmuv** [frontendbr/vagas#8099]
## Nexmuv

A NEXMUV viabiliza a jornada digital de médias e grandes empresas. Aportamos nosso expertise de inovação, construção de produtos digitais, criação de startups e desenvolvimento de software para evoluir processos e gerar impacto positivo nos negócios e na experiência de consumo.

## Descrição da vaga

Desenvolvedor Front end, focado em Angular. 
Desenvolver e implementar interfaces de usuário responsivas utilizando Angular.
Colaborar com designers e desenvolvedores back-end para melhorar a usabilidade.
Integrar APIs RESTful e outras interfaces de serviços web.
Otimizar aplicações para máxima velocidade e escalabilidade.

## Local

Hibrido  - São Paulo na região da Berrini. 

## Requisitos
Desenvolvedor Front end, focado em Angular. 
Experiência comprovada com Angular (preferencialmente Angular 2+).
experiencia sólida de HTML5, CSS3 e JavaScript; Familiaridade com controle de versão utilizando Git.
Experiência em desenvolvimento de aplicações web responsivas.
Capacidade de resolver problemas de forma eficiente e criativa.
Excelentes habilidades de comunicação e trabalho em equipe.

## Contratação

PJ 

## Como se candidatar

Por favor envie um email para helen.matos@nexmuv.com.br com seu CV anexado - enviar no assunto: Vaga Front end

#### Alocação
- Híbrido

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by fabiomirandaa** [comment]
Alguma possibilidade de remoto?

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
