### ISSUE TITLE
[Remoto] Desenvolvedor Front-End (AngularJS)

### ISSUE THREAD

**Issue by rafaelcunha123** [frontendbr/vagas#81]
## Descrição da vaga

Estamos buscando um freela (com possibilidade de se juntar ao nosso time!) para desenvolvimento do front-end do nosso MVP - uma plataforma no estilo admin para clínicas médicas.
Queremos transformar a saúde brasileira com o nosso produto e estamos buscando devs que tenham empreendedorismo na veia, assim como a gente. A dinâmica de trabalho é a seguinte:
- Passaremos requisitos, layout e design do front. Enviaremos também a documentação da nossa API.
- O dev deverá utilizar elementos do template que adquirimos para adequar o front ao novo design e fazer a integração com a nossa API.
- Combinaremos preço e prazo para a entrega inicial (deveria ser pequena e rápida) e depois avaliaremos como seguir em frente (podemos continuar como freela, ou fazer oferta para se juntar ao nosso time com participação da empresa). Como estamos começando, a melhor hora para se juntar a nós é agora (=

## Local

Remoto ou Alocado (Metro Santa Cruz)

## Benefícios

- Freela: a combinar orçamento e tempo de entrega. Possibilidade de se juntar ao time com equity.

## Requisitos

**Obrigatórios:**

- Experiência com Javascript, AngularJS e integração de REST APIs.

**Desejáveis:**

- NodeJS 
- Meteor, Cordova e Electron.

## Contratação

PF ou PJ a combinar

## Nossa empresa

Somos uma startup montando o seu primeiro MVP com o objetivo de transformar a saúde no Brasil.

## Como se candidatar

Envie um e-mail direto para rafael.cunha@edocsaude.com com CV anexado e assunto 'Dev Front'. Marcaremos um call com detalhes via Skype.

Abraços,

**Comment by rafaelcunha123** [comment]
Valeu @eduardojmatos .

**Comment by paulitolinhares** [comment]
Enviado!

**Comment by camilatigre** [comment]
@rafaelcunha123 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
