### ISSUE TITLE
[São Paulo] Front-End Developer na Ventron

### ISSUE THREAD

**Issue by Dani-Ventron** [frontendbr/vagas#810]
## Descrição da vaga

Vaga programador Front End, com foco em Angular 1

## Local

Alphaville

## Benefícios

VR, VT, SV, Plano de saúde

#### Diferenciais

tempo indeterminado de projeto

## Requisitos

**Obrigatórios:**
Conhecimento avançado em HTML5/CSS3/JavaScript
Experiência com pré-processadores CSS: SASS
Frameworks: Angular 1, Bootstrap
Experiência com serviços RESTful e API's
Conhecimento em conceitos de responsividade e design mobile
Desenvolvimento cross-browser
Controle de versionamento GIT
Práticas em testes de UI

## Contratação

CLT ou PJ

## Nossa empresa

A ventron é uma empresa de consultoria, especializada em projetos. Temos uma fábrica de software w 22 anos no mercado

## Como se candidatar

Por favor envie um email para daniele.silva@ventron.com.br com seu CV anexado - enviar no assunto: Vaga Front End

## Labels

- Alocado
- Sênior

**Comment by Finacio** [comment]
Qual seria a localidade?

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
