### ISSUE TITLE
[Hibrido / Belo Horizonte] Frontend Developer na Coodesh

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#8104]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/frontend-developer-194111161?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Estamos buscando <strong>Frontend Developer</strong> para compor nosso time!</p>
<p>A especialização das Unidades de Negócio do TSX Group constitui o cerne do diferencial competitivo de suas atribuições empresariais com a geração de valor para clientes, parceiros e sociedade a partir de uma atuação multidisciplinar e integrada.</p>
<p>30 anos de experiência orientam processos lógicos e maduros para soluções e performance de resultados com alto grau de maturidade no tratamento sistêmico de projetos.</p>
## TSX Group: 
 <p>A especialização das Unidades de Negócio do TSX Group constitui o cerne do diferencial competitivo de suas atribuições empresariais com a geração de valor para clientes, parceiros e sociedade a partir de uma atuação multidisciplinar e integrada.</p>
<p>30 anos de experiência orientam processos lógicos e maduros para soluções e performance de resultados com alto grau de maturidade no tratamento sistêmico de projetos.</p><a href='https://coodesh.com/companies/tsx-group'>Veja mais no site</a>

 ## Habilidades: 
 - Javascript 
- Next.js 
- Tailwind CSS 
- HTML 
- CSS 
- API 
- Figma
## Local: 
 Belo Horizonte
## Requisitos: 
 - Sólido conhecimento em JavaScript moderno. 
- Experiência com o framework Next.js. 
- Conhecimento prático em TailwindCSS para estilização de interfaces. 
- Domínio de HTML e CSS, incluindo práticas modernas de design responsivo. 
- Habilidade para criar e consumir APIs Restful. 
- Capacidade de traduzir designs de Figma em código funcional. 
- Conhecimento em bibliotecas para transformar código em PDF, como pdf.js, pdfKit ou semelhantes.
## Diferenciais: 
 - Familiaridade com Git e plataformas como GitHub ou GitLab. 
- Conhecimento em práticas ágeis de desenvolvimento, como Scrum ou Kanban. 
- Experiência com testes automatizados para interfaces de usuário (ex.: Jest, Cypress). 
- Conhecimento em otimização de SEO e performance para aplicações web.

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Developer na TSX Group](https://coodesh.com/jobs/frontend-developer-194111161?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipelssilva** [comment]
esta oportunidade já foi preenchida.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
