### ISSUE TITLE
[100% Remoto] 2 vagas para Fullstacker (Vue.JS + Python)  JR/PL Alocado em projetos de produtos com Gen IA - Omie

### ISSUE THREAD

**Issue by Luizeoliveira** [frontendbr/vagas#8105]
## Nossa empresa
A Omie tem como propósito trazer prosperidade para o ecossistema empreendedor brasileiro. Por isso, buscamos por pessoas com mentalidade de crescimento, valorizando perfis que tenham capacidade de adaptação, senso colaborativo e sejam motivadas pela inovação e pelo aprendizado contínuo.

Faça parte da história de uma das empresas de tecnologia que mais cresce no país! 🚀 #VempraOmie

## RESPONSABILIDADES E ATRIBUIÇÕES
- Gerenciamento e Infraestrutura: Criar e gerenciar a infraestrutura de projetos GenAI, garantindo um ambiente robusto, escalável e seguro, e implementar padrões e melhorias visando desempenho, escalabilidade, custo e segurança.
- Desenvolvimento: Desenvolver em conjunto com o time de devs recursos e funções voltados a IAs dentro de nosso CRM.
- Monitoramento e Avaliação: Monitorar e avaliar a estrutura técnica das soluções quanto a riscos de segurança e disponibilidade, além de monitorar desempenho, integridade e disponibilidade de informações, bem como logs de dados e análise de eventos.
- Ações Preventivas e Corretivas: Realizar ações preventivas e corretivas nos ambientes em nuvem, assegurando a continuidade e confiabilidade das operações.
- Inovação e Melhoria: Estudar e criar padrões de boas práticas para a utilização de IAs dentro do time, desenvolver soluções de negócio utilizando IAs, e avaliar e melhorar ferramentas internas, identificando oportunidades de aprimoramento com o uso de IAs.

## Local
Remoto (Sem Golpes, 100% Remoto - Contratando nivel Brasil) 

## Requisitos
**Obrigatórios:**
- Conhecimentos em Backend: Python, FastAPI, SQLAlchemy, AWS (Lambda, CloudWatch, DynamoDB, SQS), API, REST, SQL;
- Conhecimentos em Frontend: HTML, CSS, JavaScript e [Vue.js](http://vue.js/);
- Conhecimentos em uso de APIs REST.
- Conhecimentos em redes.
- Familiaridade com DevOps e SRE.
- Experiência com conteinerização e ferramentas de orquestração (Kubernetes).

**Desejáveis:**
- Formação: Graduação em Ciência da Computação, Engenharia de Software, ou áreas relacionadas.
- Experiência em versionamento de código (GitHub).
- Conhecimento/experiência com a API Gateway.
- Conhecimento em bancos de dados SQL e NoSQL.
- Conhecimento em serviços AWS, especificamente Bedrock, SageMaker e Amazon Q.
- Experiência com infraestrutura como código (IaC).
- Experiência com monitoramento de aplicações.
- Experiência com ferramentas de integração e deploy contínuos (CI/CD).

**Diferenciais:**
- Certificações AWS

## Benefícios
- Benefício Flexível/VR: R$ 40,00/dia útil.
- Auxílio-escritório e Auxílio Home office para você melhorar o seu ambiente de trabalho remoto e torná-lo ainda mais confortável.
- ônibus_vindo: Precisa trabalhar presencialmente? Nós temos vale-transporte. E para você que vem de trem/metrô disponibilizamos um fretado na estação para deslocamento até o escritório.
- Plano de saúde Bradesco.
- Plano odontológico Amil Dental.
- Auxílio Farmácia.
- Auxílio-creche.
- Day off de aniversário, para você comemorar como quiser!
- Para manter a saúde e o bem-estar físico em dia, contamos com Apps parceiros de academias credenciadas.
- Para relaxar e cuidar da saúde mental, temos parcerias com plataformas de terapia e meditação online.
- Parceria com o SESC - Credencial Plena
- Descontos exclusivos nas melhores faculdades e instituições de ensino, voltados para cursos de graduação, pós-graduação e MBA. Além de disponibilizarmos o Omie Academy gratuito para colaboradores.
- Parceria com cursos de English in Company.
- Programa de descontos em seguros.
- Empréstimo consignado via Ali Crédito.
- Swile Shop: plataforma de descontos exclusivos.
- Parceria com a Dell: cupons de até R$ 2.000,00.
- PPRL.
- Global Pass: benefício de viagens.
- Seguro de vida.

## Como se candidatar
Candidatura via Gupy em https://carreirasomie.gupy.io/jobs/7463067
Esta e outras vagas em https://carreirasomie.gupy.io

#### Regime
- CLT

#### Nível
- Junior
- Pleno

**Comment by gabebuenu** [comment]
Oi, eu mandei meu currículo!!

**Comment by Luizeoliveira** [comment]
boa 👍

**Comment by Mariaduda92** [comment]
Como envia currículo

**Comment by Luizeoliveira** [comment]
Duda, as inscrições são pelo link da gupy neste caso.

**Comment by Mariaduda92** [comment]
Vc pode mandar o link do  gur

Em seg., 29 de jul. de 2024 19:11, Luizeoliveira ***@***.***>
escreveu:

**Comment by Mariaduda92** [comment]
Vc tem com envia o link do  gupy ? Por favor

Em seg., 29 de jul. de 2024 19:25, Maria Eduarda Araujo De Carvalho <
***@***.***> escreveu:

**Comment by gabebuenu** [comment]
https://carreirasomie.gupy.io/jobs/7463067

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
