### ISSUE TITLE
[Remoto/híbrido] Desenvolvedor Angular Pleno e Sênior no Grupo Otimiza

### ISSUE THREAD

**Issue by grupootimiza** [frontendbr/vagas#8106]
<!-- 
==================================================

[Remoto] Desenvolvedor Angular Sênior no Grupo Otimiza

## Grupo Otimiza

Somos especialistas em sistemas para o segmento de inspeção e vistoria veicular, e nossas soluções são as mais completas e modernas

## Descrição da vaga

Atividades: 

Desenvolver e manter aplicações web de alta qualidade utilizando Angular, garantindo um código limpo, eficiente e de fácil manutenção.
Liderar equipes como Líder de Squad, coordenando esforços para alcançar objetivos e metas estabelecidas.
 Colaborar com outras equipes, incluindo design e gestão de projetos, para garantir a entrega de soluções integradas e alinhadas com as necessidades do negócio.
Realizar análise crítica e resolução de problemas, identificando e implementando soluções inovadoras para desafios técnicos complexos.
Extrair o máximo do Figma para traduzir designs de UI/UX em interfaces web altamente funcionais e visualmente atraentes.
Atuar com Angular Material para implementação de componentes UI consistentes e de alto desempenho.
Capacidade de auto gerenciamento, priorizando tarefas e recursos de forma eficiente para garantir a entrega de projetos dentro do prazo e do orçamento.

Remoto ou híbrido [Minas Gerais], [Belo Horizonte], [Lourdes]

## Requisitos

**Obrigatórios:**
Ensino Superior Completo em Ciência da Computação, Sistemas de Informação, ou áreas afins.
Experiência comprovada como Desenvolvedor Full Stack, com especialização em Angular.
Experiência anterior em funções de liderança, como Líder de Squad, é altamente desejável.
Profundo conhecimento em programação e boas práticas de desenvolvimento.
Excelentes habilidades de comunicação e trabalho em equipe.
Capacidade de análise crítica e resolução de problemas.
Experiência sólida no uso do Figma para colaboração e implementação eficiente de designs de UI/UX.
Experiência em Git e SVN para controle de versionamento.
Conhecimento avançado em frameworks de CSS, como Tailwind CSS e Bootstrap, para desenvolvimento de interfaces responsivas e modernas  e Angular Material.

**Diferenciais:**
Experiência prévia com Dev Express.

## Benefícios

Plano de Saúde SulAmérica para colaborador e dependentes (cônjuge e filhos) cobertura nacional.
Assistência Odontológica
Swile Food no valor de R$ 42,00/dia
Auxílio Home Office
Day off + presente personalizado de aniversário
Participação nos Lucros e Resultados (equivalente a um salário do colaborador)
Convênio farmácia
Horário: 40 horas semanais , incluindo sábados por escala.

## Contratação
CLT

## Como se candidatar

Por favor envie um email para michelle.guedes@grupootimiza.com.br com seu CV anexado - enviar no assunto: Vaga Des. Angular Sr

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após cada processo.

- Remoto
- Híbrido

#### Regime
- CLT

#### Nível

- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
