### ISSUE TITLE
[Rio de Janeiro/RJ] Front-end Developer na ITeam

### ISSUE THREAD

**Issue by ITeam-oportunidades** [frontendbr/vagas#8107]
> Atendimento Híbrido - Possuir base no RJ.

## ITeam

Vinte anos presente no mercado, a ITeam oferece o comprometimento com o cliente.
Reunimos capital intelectual especializado por profissionais experientes e capacitados a prestar os melhores serviços nas diferentes áreas de atuação, submetidos a treinamentos constantes para estarem sempre atualizados com as melhores práticas de mercado. 
Com uma equipe multidisciplinar, a ITeam proporciona uma área de Serviços Gerenciáveis como Projetos SAP, Fábrica de Software, Fábrica de Soluções e Sustentação. Neste modelo proporcionamos Sustentação, Melhorias e Desenvolvimentos de aplicação de forma integrada.

## Local

Rio de Janeiro/RJ – Centro - Híbrido 2x por semana no cliente.
Horário de trabalho: Comercial

## Requisitos

Graduação completa em Tecnologia da Informação (ou em área correlata à de atuação do perfil).
Linguagens de programação: HTML, CSS, JavaScript, PHP
Frameworks e bibliotecas: React, Angular, Vue.js, Wordpress
Ferramentas de controle de versão: Git, SVN
Pré-processadores CSS: Sass, Less
Gerenciadores de pacotes: npm, Yarn
Design responsivo e desenvolvimento mobile-first
Testes de interface do usuário (UI) e testes de integração

## Objetivos do projeto

Desenvolver recursos e capacidades para usuários finais através de plataformas e ferramentas de desenvolvimento ou aprendizado de máquina.
Configurar e personalizar software. 
Experiência em projetos com desenvolvimento web e design responsivo, investigando e propondo soluções para problemas de desenvolvimento e design.
Conduzir análises para determinar necessidades de integração, projetar e planejar integrações.
Melhorar o desempenho do software existente, diagnosticando e resolvendo problemas críticos.
Configurar e personalizar software. 

## Contratação

6 meses

## Como se candidatar

Por favor, envie um e-mail para viviane.pereira@iteam.inf.br com seu currículo anexado e pretensão de taxa/hora PJ - enviar no assunto: FrontEnd Pleno - Híbrido 

## Labels

HTML
CSS
JavaScript
PHP
React
Angular
Vue.js
Wordpress

## Regime
PJ 

## Nível
Pleno

**Comment by odntht** [comment]
@felipefialho a vaga é Híbrido e apenas no RJ.

**Comment by Mariaduda92** [comment]
Como envia currículo

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
