### ISSUE TITLE
[presencial, Alphaville São Paulo] Desenvolvedor Fullstack Javascript Pleno - 

### ISSUE THREAD

**Issue by ecossistemadev** [frontendbr/vagas#8109]
## Descrição da vaga

#Por que ser um #Desenvolvedor Fullstack na FidelizarMais:
A FidelizarMais nasceu para transformar clientes comuns, em compradores leais. 
Solução 100% whitelabel nativo para o cliente, customizada e personalizada, direto no front-end do cliente e via integrações com APIs
O negócio está crescendo e aumentando o número de contratações das aplicações whitelabel 
Como Fullstack, você atuará na sustentação, desenvolvimento de melhorias das aplicações da FidelizarMais em atuais clientes e  construção de painel administrativo, desenvolvimento de aplicações whitelabel dentro da loja do cliente

## Local

presencial, Alphaville São Paulo

## Requisitos

#Estamos atraindo vivências e experiências em:
 Desenvolvimento front-end com JavaScript, HTML5, CSS3 e frameworks modernos como React, Vue.js.
Ferramentas de controle de versão, como Git.
Melhores práticas de UX/UI.
Trabalhar em um ambiente ágil e colaborativo.
Resolução de problemas e atenção aos detalhes.
#Se você conhecer e souber fazer também… vai acerar sua curva de aprendizado:
Desenvolvimento em .NET e C#
Criação e consumo de APIs
TypeScript, Vue.js 
Ferramentas de build e automação como Visual Studio Code, Webpack, Gulp ou Grunt.

**Atividades e responsabilidade:**

#O que você vai fazer todos os dias:
Desenvolver e manter aplicações web responsivas e de alta performance.
Implementar interfaces de usuário utilizando frameworks e bibliotecas modernas de JavaScript.
Colaborar com a equipe de design para criar interfaces de usuário intuitivas e visualmente atraentes.
Escrever código limpo, eficiente e bem documentado.
Realizar testes e depuração de aplicações para garantir a qualidade do código.
Participar de revisões de código e contribuir para a melhoria contínua do processo de desenvolvimento. 
Trabalhar em estreita colaboração com desenvolvedores back-end para integrar serviços e APIs.
Manter-se atualizado com as novas tendências e tecnologias de front-end.

## Benefícios

Não possui

## Contratação

pj

## Como se candidatar

# [🔗 Clique aqui para se candidatar](https://empregos.dev/vaga/desenvolvedor-fullstack-javascript-pleno-8418)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 60 dias após cada processo.
E-mail para contato em caso de não haver resposta: 

#### Regime

pj

#### Nível

pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
