### ISSUE TITLE
[Rio de Janeiro] Front-end Designer

### ISSUE THREAD

**Issue by pedro-rivera** [frontendbr/vagas#811]
## Descrição da vaga

Estamos buscando uma pessoa front-end designer, que tenha o pensamento projetual do design para resolver os problemas no código.
Não é UI, não é Front-end puro, não é Back-end puro, [Brad Frost nos ajuda a entender](http://bradfrost.com/blog/post/frontend-design). Nossos trabalhos são em sua maioria sites, mas temos experimentado bastante com JavaScript, openFrameworks, Processing e arte generativa, então não espere programar sites todos os dias.

## Local e Horário

**Apenas presencial.**
Gávea, Rio de Janeiro.

## Requisitos
- Se sentir totalmente confortável em HTML, CSS e JavaScript;
- Ah, vai trabalhar com WordPress? Vai sim;
- Pensamento voltado à sistematização e componentização das estruturas do projeto, da arquitetura de informação até o código escrito, tudo precisa ser pensado como um sistema escalável.
- Saber o que é CSS Grid (saber a relação dele com Flexbox é fundamental);
- Tender a fugir de frameworks tipo Bootstrap, Bulma, Foundation, etc;

**Diferenciais**
- React e/ou Vue;
- Trabalhar com REST APIs;

## O ESTUDIO CRU

Através do design, desenvolvemos soluções visuais e criamos engajamento com pessoas, marcas e projetos. Nossa filosofia de trabalho é baseada em simplicidade, clareza e solução inteligente de problemas. Enxergamos o cliente como um parceiro e acreditamos que um trabalho bem sucedido é fruto desta colaboração. Buscamos sempre novos desafios e estamos sempre abertos a novos projetos.

## Como se candidatar
Envie email com assunto _[Front-End] Seu Nome_ com portfólio, links de trabalhos recentes, GitHub ou o que achar que vai ser útil pra gente conhecer você e seu trabalho para contato@estudiocru.com

.
labels: emprego

**Comment by pedro-rivera** [comment]
MEI. Vamos avaliar a faixa de acordo com a pessoa, mas a princípio na faixa dos R$2.000~3.000

**Comment by ldrbraga** [comment]
Fala, Pedro. Boa tarde!

Currículo enviado!

**Comment by jeffersondesouza** [comment]
Vaga bastante interessante. Se fosse remoto me candidataria...

**Comment by antoniotex** [comment]
Opa Pedro!

Vocês contratam estagiário?

**Comment by pedro-rivera** [comment]
@antoniotex manda pra gente, quem sabe o que pode rolar né?

**Comment by lucianobarauna** [comment]
Vaga legal ;-)

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
