### ISSUE TITLE
[São Paulo] Sales Force Developer no Grupo Euro17

### ISSUE THREAD

**Issue by Patybenda** [frontendbr/vagas#8110]
O Grupo Euro17 é uma empresa líder em sua área e está buscando um Desenvolvedor Sales Force para se juntar à nossa equipe. Para essa posição, estamos procurando alguém com uma formação na área de Tecnologia da Informação e especializada no desenvolvimento de aplicativos na plataforma Salesforce.

## Descrição da vaga

**Responsabilidades:**
Elaborar soluções de desenvolvimento dentro do software Salesforce, visando melhorias no sistema. Incluindo, Integrações com outras plataformas, mudanças de fluxos de aprovação, alterações de regras de negócio e outras melhorias dentro de Salesforce, que exijam desenvolvimento Pro Code (APEX).

**Requisitos:**

Ensino superior concluído ou em andamento em Análise e Desenvolvimento de Sistemas ou correlatas;
Experiência com Sales Force e condução de projetos;
Inglês técnico;

## Local

Disponibilidade para atuar de forma 100% presencial na Faria Lima;

## Benefícios

- ASSISTÊNCIA MÉDICA E ODONTOLÓGICA (APÓS 3 MESES DE CONTRATO)
- SEGURO DE VIDA
- PARCERIAS DE DESCONTOS PARA CURSOS SUPERIORES E CURSOS DE EXTENSÃO EM QUALQUER UNIDADE FGV
- AUXÍLIO CRECHE
- PARCERIA COM ESCOLAS DE IDIOMAS COM DESCONTOS: CNA E OPEN ENGLISH
- DAY OFF NO DIA DO ANIVERSÁRIO
- VALE TRANSPORTE
- VALE REFEIÇÃO R$38,00 AO DIAVALE ALIMENTAÇÃO R$ 200,00
- TOTAL PASS

## Contratação

Regime CLT. 

## Como se candidatar

Interessados devem encaminhar seu currículo atualizado para selecao@grupoeuro17.com.br com o título - Desenvolvedor Sales Force Sênior.

#### Alocação
- Alocado

#### Regime
- CLT

#### Nível
- Sênior

![Captura de tela 2024-07-30 122810](https://github.com/user-attachments/assets/1826871a-197f-443b-90ba-1bd6df8d44ca)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
