### ISSUE TITLE
[REMOTO] Front-end Developer na Hepta Tecnologia 

### ISSUE THREAD

**Issue by GitMateusBruno** [frontendbr/vagas#8113]
## Nossa empresa

Somos a Hepta tecnologia empresa sediada em Brasília com 33 anos de atuação. Temos contratos com empresas privadas e órgãos públicos, em virtude disso aqui é um espaço amplo de crescimento e desenvolvimento profissional. O time é bastante colaborativo, na verdade colaboração faz parte do nosso valor 🚀

## Descrição da vaga

Projeto em Angular (Diferencial se possuir conhecimento em React)

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Necessário comprovação de experiência
- Necessário comprovação de formação superior em TI
- Necessário certificação em Professional Scrum Developer ou Certified Scrum Developer
- Para o Perfil SÊNIOR necessário certificação em: 
a) Scrum.Org: Professional Scrum Master – PSM: PSM I; PSM II ou PSM III; 
b) Scrum Alliance: Certified Scrum Master – CSM; 
c) Scrum Study: Scrum Master Certified – SMC 
d) EXIN: Agile Scrum Master - ASM.

**Caso NÃO possua certificação oferecemos um prazo para obtê-la. Atenção a empresa não custeia, apenas oferece um prazo.** 

**Desejáveis:**
- conhecimentos em React
- conhecimentos em .NET e C#

## Benefícios

- Plano de saúde com coparticipação
- VA ou VR
- Auxílio Home Office

**Diferenciais:**
- Parceria com a Google Cloud Partner Training

## Contratação

PJ ou CLT 

## Como se candidatar

Por favor envie um email para mateus.sousa@hepta.com.br  CV anexado - enviar no assunto: Vaga Angular

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até cinco dias após cada processo.

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT
- PJ

#### Nível
- Sênior

**Comment by victorbiasibetti** [comment]
Não entendi o que certificação em SCRUM tem a ver com Frontend?

Att. Victor Assmann Biasibetti



Em qua., 7 de ago. de 2024 às 13:36, Mateus Bruno ***@***.***>
escreveu:

**Comment by GitMateusBruno** [comment]
Oi Victor, no nosso cliente o DEV SR assume a função de SM :)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
