### ISSUE TITLE
[Híbrido] Coordenador(a) de TI - Going2 Tech - Soorcaba e região

### ISSUE THREAD

**Issue by MariaJuliaRicostiG2** [frontendbr/vagas#8114]
## Nossa empresa

Fundada em 2012, a Going2 Corporation S/A é uma empresa de tecnologia da informação, focada em criar produtos que tenham como premissa, facilitar a vida das pessoas e empresas, através do desenvolvimento de Aplicativos, Sistemas e dos princípios de IOT (internet das coisas). Hoje é imprescindível que as empresas tenham soluções que possam aliar tecnologia ao que existe de mais atual em mobilidade, para facilitar o entendimento e produtividade entre todos.

## Descrição da vaga

**Atividades:**

- Liderar e coordenar a equipe de engenharia de software, garantindo a entrega de projetos com alta qualidade.
- Estruturar, implementar e garantir a adesão a processos de engenharia de software, promovendo a melhoria contínua e a eficiência operacional.
- Planejar, organizar e gerenciar todas as fases do ciclo de desenvolvimento de software, incluindo análise de requisitos, design, desenvolvimento, testes e implementação.
- Colaborar ativamente com outros departamentos para alinhar objetivos, garantir a integração eficaz e atender às demandas da empresa.
- Fornecer orientação técnica e suporte à equipe, promovendo um ambiente de aprendizado contínuo e desenvolvimento profissional.
- Gerenciar a alocação de recursos, prazos e orçamentos dos projetos.
- Garantir a conformidade com as melhores práticas de segurança e proteção de dados.

**Requisitos**

- Formação superior em Ciência da Computação, Engenharia de Software ou área relacionada.
- Sólidos conhecimentos em metodologias ágeis (Scrum, Kanban) e práticas de desenvolvimento de software.
- Excelente habilidade de resolução de problemas e tomada de decisões.
- Capacidade de comunicação eficaz, tanto escrita quanto verbal.
- Experiência em trabalhar em um ambiente dinâmico e de ritmo acelerado.
- Experiência em gestão de projetos e liderança de equipes multidisciplinares.
- Forte experiência em estruturação de processos e definição de indicadores.
- Inglês intermediário.
- Experiência em empresas de tecnologia ou startups. **(Desejável)**
- Experiência como líder de equipe em engenharia de software. **(Desejável)**
- Conhecimento em linguagens de programação. **(Desejável)**
- Conhecimento em DevOps e ferramentas de automação. **(Desejável)**
- Experiência com serviços de nuvem (AWS, Azure, Google Cloud). **(Desejável)**

## Local

Híbrido - Atividades presenciais no escritório em Sorocaba.

## Incentivo

- Ajuda de custo exclusivo para convenio médico e odontológico;
- Day-Off de aniversário;
- 15 dias de descanso remunerado;
- Plano de carreira;
-  Ajuda de custo para locomoção.

## Contratação

PJ 

## Como se candidatar

Enviar um e-mail para recrutamento@going2.com.br contendo currículo, linkedin e pretensão salarial. Com o assunto: Coordenador(a) de Projetos.

### Nível
- Sênior
- Especialista

### Regime

- PJ

### Alocação

- Híbrido

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
