### ISSUE TITLE
[Belo Horizonte] Full Stack Developer Sênior na @Rhitmo Tech

### ISSUE THREAD

**Issue by gabirecruiter** [frontendbr/vagas#8115]
**[FULL STACK COM FOCO EM FRONT END ANGULAR]** 

Somos a RHITMO Tech e aqui conectamos criatividade e tecnologia, gerando soluções seguras e exponenciais. Um time que está sempre pronto para decolar e é capaz de criar e desenvolver projetos que mudam positivamente a vida das pessoas, solucionando problemas e transpondo obstáculos.💙

Quer conhecer um pouco mais sobre nós? Siga-nos nossas redes sociais:
https://rhitmotech.com.br/
https://www.instagram.com/rhitmotech/

Estamos em busca de um **Desenvolvedor(a) Full Stack (.NET + Angular)** Sênior altamente qualificado para se juntar à nossa equipe de Tecnologia.

## Responsabilidades:

- Desenvolver e manter aplicações web robustas e escaláveis utilizando .NET e Angular.
- Colaborar com equipes multifuncionais para definir, projetar e entregar novas funcionalidades.
- Participar ativamente de reuniões diárias (dailys) e contribuir para a resolução de problemas e aprimoramento contínuo.
- Garantir a qualidade do código através de boas práticas de desenvolvimento, testes unitários e revisão de código.
- Manter-se atualizado com as novas tendências e tecnologias, propondo melhorias e inovações.

## É necessário que você tenha: 

- Experiência comprovada como Desenvolvedor Full Stack, com forte conhecimento em .NET e Angular.
- Habilidade para trabalhar em um ambiente ágil, com metodologias Scrum ou Kanban.
- Sólida compreensão de HTML, CSS, JavaScript e TypeScript.
- Experiência com bancos de dados relacionais, como SQL Server.
- Conhecimento em práticas de DevOps e experiência com CI/CD.
- Capacidade de resolver problemas de maneira eficiente e comunicar soluções técnicas de forma clara.

## Informações sobre a vaga:

Modelo de contratação: Pessoa Jurídica
Complemento: Interrupção remunerada de 15 dias;
Senioridade: Sênior
Bonificação por indicação de Desenvolvedor.

## Etapas do processo:

- Triagem de currículos
- Análise do teste DISC
- Bate Papo RH 
- Análise técnica (GitHub ou teste técnico)
- Bate Papo Técnico
- Bate Papo com liderença
- Envio da Proposta.

## Como se candidatar? 
Se inscreva através do nosso portal de [[vagas]](https://rhitmotech.inhire.app/vagas/b6085810-afb1-43cd-aaac-7656f752948f/desenvolvedor-full-stack-senior). Estamos ansiosos para recebê-lo em nossa equipe! #VEMPRARHITMO!🚀👩‍🚀

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
