### ISSUE TITLE
[Remoto] Full-Stack Developer na Nirvana Labs

### ISSUE THREAD

**Issue by akramhussein** [frontendbr/vagas#8117]
## Nossa empresa

Nirvana Labs é a primeira plataforma de nuvem full-stack projetada por nativos do mundo cripto e especialistas em nuvem para atender às demandas únicas das empresas web3. Nossas ofertas incluem uma poderosa plataforma de computação em nuvem bare metal, nós RPC altamente confiáveis com balanceamento de carga e nós dedicados de nível empresarial.

Por que isso importa:

Abordando as limitações dos provedores de nuvem tradicionais:

- Provedores de nuvem tradicionais como AWS, GCP e Azure não conseguem lidar com a natureza intensiva em recursos das cargas de trabalho de blockchain, deixando as empresas web3 em busca de alternativas à medida que os custos disparam.
- Nossa abordagem centrada em web3 visa solucionar essas limitações combinando infraestrutura bare metal com um sistema operacional especializado.

Impulsionando a inovação na infraestrutura de nuvem web3:

- Os nós da Nirvana são os mais rápidos da indústria web3, com uma latência global média de 28 milissegundos, em comparação com 175 milissegundos da Alchemy, 300 milissegundos da QuickNode e 400 milissegundos da Infura.
- Ao reduzir as contas de nuvem em até 85%, estamos ajudando as empresas web3 a otimizar seus custos de infraestrutura e se concentrar em impulsionar seus negócios principais.

O panorama geral: a equipe da Nirvana inclui operadores de blockchain da BitGo, especialistas em nuvem e data center da AWS, especialistas em redes da AT&T e especialistas em hardware da Apple e Google. Essa diversidade de expertise permite a criação de uma plataforma de nuvem de ponta, adaptada às necessidades únicas do ecossistema web3.

Nossos clientes incluem: Chainlink, BitGo, Goldsky, Thirdweb e Pairpoint.

## Descrição da vaga

O que você fará:

- Escrever código frontend e backend modular, testável e de alta qualidade.
- Estabelecer e manter as melhores práticas de engenharia de ponta.
- Desenvolver novas funcionalidades essenciais e fluxos de trabalho, bem como aprimorar as experiências existentes no console de gerenciamento da Nirvana.
- Implementar e manter componentes de UI baseados em um sistema de design que você implementará.
- Colaborar de perto com outras equipes de engenharia, produto e design para entregar uma experiência de usuário incrível.

Mais informações podem ser encontradas [aqui](https://nirvanalabs.notion.site/Full-Stack-Engineer-Full-Time-REMOTE-f3c008e04f8b475798058e75f619d10d?pvs=74).

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com Typescript
- 2 anos de experiência com React em Next.js
- Fluente em inglês

**Desejáveis:**
- conhecimentos em PostgreSQL
- conhecimentos em Puppeteer
- conhecimentos em GitHub Actions

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para `akram [at] nirvanalabs [dot] ai` seu CV anexado - enviar no assunto: `Full-Stack Engineer [frontend-br]`

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- Freela
- PJ

#### Nível
- Pleno
- Sênior

**Comment by HenryKun55** [comment]
Acabei de enviar!

**Comment by akramhussein** [comment]
> Acabei de enviar!

Obrigado! Acho que houve um erro no meu e-mail 🤦‍♂️, por favor você pode enviar novamente.

**Comment by HenryKun55** [comment]
> akram [at] nirvanalabs [dot] ai

Prontinho, enviei novamente, acho que agora foi correto! te mandei mensagem no linkedin também qualquer coisa, brigadão!

**Comment by gabsnery** [comment]
Boa tarde
A vaga se mantem aberta?
Acabei de enviar o meu curriculo

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
