### ISSUE TITLE
[Híbrido: São Paulo - SP] Frontend Android Developer (PL/SR) na TRUPPE!

### ISSUE THREAD

**Issue by Camila-Goms** [frontendbr/vagas#8118]
## TRUPPE

A [Truppe](https://truppe.team/) é uma empresa de consultoria de tecnologia com foco em desenvolver e aprimorar talentos referência em recrutamento, seleção e alocação de profissionais de TI. Criada há 4 anos, está em fase de desenvolvimento e crescimento, expandindo seu portfólio de produtos e serviços, trabalhando também com transformação e aceleração digital.

Sua missão é conectar os melhores profissionais às melhores oportunidades, proporcionando seu crescimento na carreira.

## Descrição da vaga

Estamos buscando um Desenvolvedor Frontend Android talentoso para integrar nossa equipe inovadora na área de tecnologia da informação. Você terá a oportunidade de trabalhar com tecnologias avançadas, contribuindo para o desenvolvimento de soluções que impactam diretamente nossos produtos e serviços.

## Local

Atuação: Híbrida em São Paulo -SP, Itaim Bibi (3x presenciais e 2x home office).

## Requisitos

**Obrigatórios:**

- +3 anos de experiência sólida com desenvolvimento Android utilizando Kotlin.
- Conhecimento em SDUI.
- Experiência com testes automatizados para Android.
- Forte compreensão de práticas modernas de desenvolvimento ágil, incluindo CI/CD.
- Excelentes habilidades de comunicação e capacidade de trabalhar eficazmente em equipes multidisciplinares.
- Formação acadêmica em Ciência da Computação, Engenharia de Software ou área relacionada.

**Desejáveis:**

- Familiaridade com Kafka, Redis, MongoDB e MySQL.
- Experiência com a infraestrutura AWS Cloud Stack.
- Certificações relevantes em tecnologias Android.

## Benefícios

- Vale Refeição (R$ 858,65 /mensal);
- Vale Alimentação (R$ 663,48 /mensal);
- Assistência Média e Odontológica;
- Seguro de Vida em Grupo;
- Day off de aniversário.

## Contratação

CLT a combinar.

## Como se candidatar

Envie um email para [camila.recruiter@outlook.com] com seu currículo atualizado, link do perfil do Linkedin (se tiver) e pretensão salarial CLT.

Enviar no assunto: Frontend Android Kotlin Developer (PL/SR).

#### Nível

- Pleno a Sênior

**Comment by Evanjr73** [comment]
mandei o meu curriulo , mas caso queira é só entrar em contato comigo pelo gmail evsioljr@gmail.com

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
