### ISSUE TITLE
[Híbrido: São Paulo - SP] Desenvolvedor Frontend iOS (PL/SR) na TRUPPE!

### ISSUE THREAD

**Issue by Camila-Goms** [frontendbr/vagas#8119]
## Empresa

A [Truppe](https://truppe.team/) é uma empresa de consultoria de tecnologia com foco em desenvolver e aprimorar talentos referência em recrutamento, seleção e alocação de profissionais de TI. Criada há 4 anos, está em fase de desenvolvimento e crescimento, expandindo seu portfólio de produtos e serviços, trabalhando também com transformação e aceleração digital.

Sua missão é conectar os melhores profissionais às melhores oportunidades, proporcionando seu crescimento na carreira.

## Descrição da vaga

Estamos buscando um Desenvolvedor Frontend iOS dedicado para integrar nossa equipe inovadora na área de tecnologia da informação. Você terá a oportunidade de trabalhar com tecnologias avançadas, contribuindo para o desenvolvimento de soluções que impactam diretamente nossos produtos e serviços.

## Tipo de contratação

CLT a combinar

## Nível

Pleno a Sênior

## Local

Híbrido em São Paulo -SP, Itaim Bibi (3x presenciais e 2x home office). **SEM POSSIBILIDADE DE REMOTO!**

## Responsabilidades

• Desenvolver e manter aplicativos móveis iOS utilizando Swift
• Implementar interfaces de usuário utilizando SDUI
• Colaborar com designers e outros desenvolvedores para criar experiências de usuário excepcionais
• Escrever testes automatizados para garantir a qualidade do código
• Trabalhar em conjunto com equipes de backend para garantir a integração perfeita dos serviços
• Documentar processos, arquiteturas e designs de software para referência futura e treinamento

###### Obrigatórios

• Experiência sólida com desenvolvimento iOS utilizando Swift
• Conhecimento em SDUI
• Experiência com testes automatizados para iOS
• Forte compreensão de práticas modernas de desenvolvimento ágil, incluindo CI/CD
• Excelentes habilidades de comunicação e capacidade de trabalhar de forma colaborativa
• Formação acadêmica em Ciência da Computação, Engenharia de Software ou área relacionada

###### Desejáveis

• Familiaridade com Kafka, Redis, MongoDB e MySQL
• Experiência com a infraestrutura AWS Cloud Stack
• Certificações relevantes em tecnologias iOS

## Benefícios

• Vale Refeição (R$ 858,65 /mensal) 
• Vale Alimentação (R$ 663,48 /mensal)
• Assistência Média e Odontológica
• Seguro de Vida em Grupo
• Day off de aniversário

## Como aplicar

Envie um email para [ [camila.recruiter@outlook.com](mailto:camila.recruiter@outlook.com) ] com seu currículo atualizado, link do perfil do Linkedin (se tiver) e pretensão salarial CLT.

Enviar no assunto: Desenvolvedor Frontend iOS (PL/SR).

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
