### ISSUE TITLE
[São Paulo/SP] Front-end developer na Blu365

### ISSUE THREAD

**Issue by raphaguasta** [frontendbr/vagas#812]
## Descrição da vaga

Buscamos um desenvolvedor front end que goste de crescer com desafios profissionais, disposto a codar em todos os projetos da empresa (inclusive novos) independente do Framework utilizado!

Não procuramos alguém que sabe todos os frameworks da última semana, precisamos de alguém que entenda HTML, CSS e JS, e saiba que são as linguagens (sim, HTML também) fundamentais pra conseguirmos utilizar outras diversas ferramentas, e desenvolver projetos sensacionais!

Temos projetos SPAs com o core JS em: Backbone, Angular, jQuery, ReactJS (a maioria). Nos estilos: CSS puro, SASS, Stylus ou StyledComponents(React). HTML ou PUG(Jade).

Temos um blog e alguns projetos em Wordpress (Já desenvolveu um tema alguma vez? Aqui podemos :) ).

## Local

Escritório, São Paulo - Vila Olímpia

#### Diferenciais

- Refeitório com microondas e geladeira
- Pebolim (ou tótó)
- Violão disponível
- Todos trabalham com notebook, não temos lugar fixo
- Traje casual
- Área de descanso com sofá confortável

## Requisitos

**Obrigatórios:**
- Conhecer os fundamentos de HTML5, CSS3, Javascript (ES6+)
- Experiência com algum framework Javascript
- Experiência com algum pré processador (SASS/Less/Stylus))
- Git
- Disposição e boa vontade para aprender e ensinar, errar e acertar, discutir tecnologias e abordagens, pró atividade no dia a dia.

**Desejáveis:**
- Entender HTTP e saber consumir uma API
- Wordpress
- Entendimento básico do ambiente Node
- Noção básica de UI/UX (Não queremos um designer, mas ter uma noção sempre ajuda! :) )

**Diferenciais:**
- Conhecimento avançado em algum framework JS (Preferência ReactJS + Redux) 
- Saber configurar/editar Gulp e/ou Webpack
- SEO
- Entender a importância de detalhes como velocidade de carregamento, perfomance, organização e clareza de código, tratamento de erros, otimização da experiência do usuário (Não deixá-lo preso no loading....)
- Curiosidade, prazer e empenho no desenvolvimento

## Contratação

CLT ou PJ a combinar

## Nossa empresa

[Blu365.com.br](https://blu365.com.br)

Somos a BLU365, uma empresa criada em 2014 com o nome de Kitado. Oferecemos soluções que irão ajudar você, sua família e milhões de brasileiros a se manterem no azul nos 365 dias do ano :)

Trabalhamos para grandes clientes: Itaú, Santander, Casas Bahia, Ponto Frio, Gafisa, Banco Pan, e mais alguns...

## Como se candidatar

Email para raphael.guastaferro@blu365.com.br com seu CV anexado, link do Github e Linkedin - enviar no assunto: Vaga Front End Developer

## Labels

- Alocado
- CLT
- PJ
- Júnior
- Pleno

**Comment by phsantiago** [comment]
Trabalhei por um bom tempo na Blu e recomendo. Melhor lugar que já trabalhei até hoje! Pode ter a certeza que lá você vai aprender muito mesmo e construir coisas incríveis.

O workflow é bom e a parte humana é sensacional, saudades de cada colaborador de lá!

**Comment by phsantiago** [comment]
Trabalhei por um bom tempo na Blu e recomendo. Melhor lugar que já trabalhei até hoje! 
Pode ter certeza que lá você vai aprender muito mesmo e construir coisas incríveis.

O workflow é bom e a parte humana é sensacional, saudades de cada colaborador de lá!

**Comment by HaluDeCassia** [comment]
Boa tarde, não há chance de trabalhar totalmente remoto?

**Comment by raphaguasta** [comment]
Pra essa vaga, não. @HaluDeCassia =(

**Comment by LeticiaLCavalcanti** [comment]
Boa tarde! 
Sou estudante de engenharia de computação, ainda estou no 7 semestre. Me apaixonei muito por desenvolvimento e faço estágio na área, sendo que no momento possuo melhor conhecimento em front-end, porém ainda básicos. Existe a possibilidade de eu me candidatar para um nível júnior?

**Comment by raphaguasta** [comment]
Todos os cvs serão avaliados, pode enviar! :) @LeticiaLCavalcanti

**Comment by EdipoNascimento** [comment]
E se o cara for de testes? Alguma possibilidade?

Em 16 de fev de 2018 16:08, "Raphael Guastaferro" <notifications@github.com>
escreveu:

**Comment by raphaguasta** [comment]
@EdipoNascimento Conhecimento em testes são muito bem vindos! Mas além disso, precisamos de alguém pra codar front mesmo! Se for seu perfil vale enviar sim! :)

**Comment by EdipoNascimento** [comment]
Sim, é isso que procuro... Mas quando envio meu VC não recebi respostas.

Em 16 de fev de 2018 16:13, "Raphael Guastaferro" <notifications@github.com>
escreveu:

**Comment by Finacio** [comment]
Aceita parcial remoto? 2 vezes na semana remoto!

**Comment by raphaguasta** [comment]
@Finacio De início provavelmente não, mas com algum tempo isso pode ser combinado.

**Comment by gadielkalleb** [comment]
Enviado :)
