### ISSUE TITLE
[Remoto] Front-end Developer React Native na Kiddo | Digital Product Company

### ISSUE THREAD

**Issue by adrianoribeiro14** [frontendbr/vagas#8120]
## Nossa empresa

A Kiddo é uma consultoria especializada em desenhar, desenvolver, lançar e escalar Produtos Digitais.
Há 10 anos desenvolvemos produtos para algumas das maiores empresas do planeta, com foco em aplicações web e mobile, criadas com base em sólido trabalho de pesquisa, estratégia e design.

Acreditamos em um dia a dia de trabalho calmo. Para isso, investimos muito no desenho de processos e artefatos que organizem e tragam maior visibilidade para o dia a dia dos grupos de trabalho. Nossos grupos enxutos e multidisciplinares também garantem que todos estejam a par dos porquês de cada decisão e mantenham a visão no todo, na estratégia do negócio.

Entendemos que o mundo de produtos digitais e está cada vez mais complexo e estamos indo pelo lado oposto. Menos frameworks, menos buzzwords, menos nomes chiques de cargos. Acreditamos no simples: o produto digital é um canal para a entrega de valor de um negócio e um time multidisciplinar enxuto, bem organizado, é capaz de construir as melhores estratégias para que isso aconteça.

## Descrição da vaga

Estamos à procura de uma pessoa experiente para integrar nossa equipe de tecnologia que será responsável por desenvolver e manter aplicativos móveis e web de alta qualidade, colaborando com a equipe para aprimorar as funcionalidades e a experiência do usuário.

A pessoa desenvolvedora de Front-end na Kiddo tem um papel chave na concepção dos produtos, contribuindo durante a etapa de design e especificação para que o produto seja melhor envelopado.

## Local

Remoto (visita ao escritório de São Paulo até 4 vezes por ano, custeada pela Kiddo para colaboradores em território nacional)

## Requisitos

**Obrigatórios:**
- Sólida experiência em desenvolvimento com React e React Native
- Sólidos conhecimentos em JavaScript, ES6+ e TypeScript
- Experiência em consumir APIs RESTful e/ou GraphQL
- Conhecimento de práticas de design responsivo e adaptativo
- Experiência e interesse em atuar com microinterações
- Experiência com ferramentas de versionamento de código, como Git
- Experiência em testes de unidade e testes automatizados
- Experiência em publicar e gerenciar aplicativos na App Store e Google Play

**Desejáveis:**
- experiência em Swift
- experiência em Flutter
- experiência em Kotlin
- experiência com Node.js
- experiência com MongoDB e Express
- experiência com gerenciamento de estado (Redux, Context API, etc.)
- Familiaridade com CI/CD e DevOps

**Diferenciais:**
- olhar pixel perfect
- experiência em design
- interesse por artes (pintura, graffiti, fotografia, artes plásticas e etc)

## Benefícios

- VR R$ 30/dia
- Home office R$ 150,00/mês
- Conexa Saúde
- Short-Friday (às sextas-feiras trabalhamos até 13h)
- Folga no mês do aniversário
- Folga por ano de casa
- Licença pet
- Licença paternidade estendida

## Contratação

PJ, com 13o salário

## Como se candidatar

Por favor envie um email para adriano@kiddo.is, com o assunto Vaga Front-End Developer React Native, contando um pouco da sua experiência e como você se relaciona com a vaga, além de - se possível - referências de projetos que você já entregou.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: adriano@kiddo.is

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior

**Comment by victorbiasibetti** [comment]
a visita ao escritório é custeada pela empresa?

**Comment by adrianoribeiro14** [comment]
Oi, Victor. Tudo bem?

É sim, desde que o colaborador esteja no território brasileiro.
Ajustarei lá na vaga para que não gere dúvidas.

Abraços!




-- 




Em qui., 15 de ago. de 2024 às 12:46, Victor Biasibetti <
***@***.***> escreveu:
