### ISSUE TITLE
[Remoto] Front-end Developer na nav9 

### ISSUE THREAD

**Issue by RenataRamiress** [frontendbr/vagas#8121]
## Nossa empresa

Nós somos a nav9, somos Tech Solving Partners. Isso significa que desde 2017 entendemos os desafios do cliente e entregamos, por meio de gestão ágil, design e engenharia de software, soluções digitais efetivas que aceleram o crescimento do negócio dos nossos clientes!

A nav9 não para de crescer e por isso buscamos profissionais que nos ajudem a continuar voando cada vez mais alto rumo à novos desafios! Quer ser um tech solver? Se inscreve logo na nossa orpotunidade para pessoa desenvolvedora front-end Jr.!🌟

Me inscrevi, o que acontece agora?👀 Cada pessoa inscrita terá sua candidatura vista por um de nossos recrutadores. Nesse momento analisaremos seu cadastro, caso o seu perfil dê match com os requisitos, nosso time entrará em contato para alinhar os próximos passos da tua jornada com a gente, através do seu e-mail. Mas caso não possua os requisitos, também retornamos para agradecer sua inscrição. 

E aí, tá preparado para fazer parte de tudo isso?! 🚀

## Descrição da vaga

Nossos tech solvers atuam de forma autônoma dentro de um squad multidisciplinar que segue os princípios de desenvolvimento de software ágil. Procuramos uma pessoa que tenha experiência na área de desenvolvimento web Front-end React, além de possuir experiência com clientes e projetos. Como pessoa desenvolvedora para a área de Front-end, você utilizará principalmente React. Na empresa ganhou utilizando metodologias ágeis, logo sua rotina de trabalho será pautada por meio de cerimônias como planejamento, diário e retro. O seu dia-a-dia de trabalho se baseará nas cerimônias e no projeto que você irá entrar.

## Local

Remoto 

## Requisitos

Para você avançar para primeira etapa você precisa desses requisitos e qualificações:

Experiência profissional na área de front-end a partir de 1 ano;
Experiência com clientes;
Conhecimento em HTML, CSS e JavaScript;
Experiência Profissional com ReactJS.

**Desejáveis:**
Desejável conhecimento com CMS hygraph; 
Desejável conhecimento básico de ferramentas de gestão de tarefas;
Desejável conhecimento básico de Git e Gitflow.

## Benefícios

🩺Assistências médica e odontológica

🫂Auxilio psicológico

🏋️‍♀️Auxilio atividade física

🍔Vale Refeição e/ou Vale Alimentação

📚Auxilio Educação 

⏰Horário flexível

👩‍💻Home office

## Contratação

CLT

## Como se candidatar

Por favor envie sua candidatura por [aqui ](https://forms.gle/RCUdb5Av7Uqfd9zU9)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07dias após cada processo.
E-mail para contato em caso de não haver resposta: renata.silva@nav9.tech 

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Júnior

**Comment by vanessawin** [comment]
Enviado

**Comment by fernandohali** [comment]
Formulário preenchido!

**Comment by jonathasborges1** [comment]
![image](https://github.com/user-attachments/assets/91b1c6b8-0ef2-4b4d-8c4e-41dd600fd5a2)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
