### ISSUE TITLE
[REMOTO] Jr Front-end Developer na Devvo

### ISSUE THREAD

**Issue by LeonardoCHb** [frontendbr/vagas#8125]
## Nossa empresa

Aqui na Devvo Tecnologia, estamos em busca de mentes inovadoras e apaixonadas por tecnologia que desejam trilhar um caminho de crescimento profissional e pessoal. Se você anseia por um ambiente dinâmico e repleto de oportunidades de crescimento, sua busca termina aqui! Sediados em Brasília, nossa missão é impulsionar a sociedade por meio de soluções de ponta, conduzindo a transformação digital de empresas de todos os portes.

## Descrição da vaga

Junte-se a nós e colabore ativamente no fortalecimento e aprimoramento da nossa equipe de tecnologia. Você terá a oportunidade de participar do desenvolvimento e manutenção de soluções de software de alto desempenho, trabalhando lado a lado com equipes multidisciplinares que garantem a excelência na execução e entrega de projetos ambiciosos.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Mais de 1 ano de experiência no desenvolvimento de aplicações Web e Mobile;
- Graduado em Engenharia da Computação, Ciência da Computação ou áreas similares
- Habilidade comprovada em React, React Native
- Familiaridade com Git.
- Boas habilidades de comunicação e trabalho em equipe
- Contribuição no desenvolvimento de projetos web e mobile;
- Auxílio na realização de testes de qualidade para assegurar a boa performance dos sistemas;
- Colaboração na melhoria contínua dos processos internos de gestão e desenvolvimento de projetos.

**Desejáveis:**
- Experiência no desenvolvimento com Next, Kotlin, Swift ou Strapi.
- Experiência com Bancos de Dados: Proficiência em SQL e NoSQL (por exemplo, MySQL, PostgreSQL, MongoDB).
- Proficiência em metodologias ágeis para um fluxo de trabalho otimizado;

## Contratação

PJ

## Como se candidatar

Envie seu Currículo atualizado e sua Carta de Apresentação para contato@devvo.com.br . 
Por favor, inclua no assunto do e-mail "[Nome] - Vaga de Desenvolvedor [Front-end Júnior]". Aguardamos ansiosamente para conhecer você e discutir mais sobre essa oportunidade de trabalho

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: contato@devvo.com.br

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior

**Comment by Jo4o20** [comment]
já me candidatei

**Comment by leonardomoussallem** [comment]
Mandei ai tambem

**Comment by emvictor** [comment]
Enviado!

**Comment by RuanTorress** [comment]
Enviado

**Comment by p1padev** [comment]
Enviado

**Comment by amandaeugenia** [comment]
CV Enviado!

**Comment by joao20233** [comment]
ENVIADO!

**Comment by devjpedro** [comment]
CV enviado!

**Comment by roberiof** [comment]
Mandei 😃

**Comment by Jeffsantos3002** [comment]
CV enviado!

**Comment by LuisFelipeMod** [comment]
Enviado :)

**Comment by mozart-maia** [comment]
Enviado ✅

**Comment by Evanjr73** [comment]
ENVIADO

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
