### ISSUE TITLE
[Remoto] Front-end Developer Senior na V8.TECH

### ISSUE THREAD

**Issue by Anarib2921** [frontendbr/vagas#8126]
**Nossa empresa**

Apoiamos os clientes a reinventarem seus negócios por meio da construção e transformação de seu core business, com otimização de operações, TI, transformação digital e aceleração do crescimento, resultado do abrangente portfólio construído ao longo dos anos, originário da combinação estratégica de três grandes empresas: V8 Consulting, Devires & Experior.

Oferecemos uma ampla gama de soluções aos nossos clientes, incluindo desenvolvimento e migração de aplicações, projetos DevOps, Big Data e Analytics, além de soluções de Inteligência Artificial.

Atualmente a V8.TECH possui mais de 100 clientes entre as 1000 maiores empresas do Brasil, atendendo diversos setores, incluindo Serviços Financeiros, Indústria, Saúde, Seguros, Mídia e Comunicação, Utilities, Educação, Telecom, Varejo, Agronegócio e Transporte.

A partir de São Paulo, a V8 atua regionalmente, prestando serviços em outros países da América Latina, como Chile, Argentina, Colômbia, Peru e México.

**Local**

Remoto :)

**Responsabilidades e atribuições**

Projetar, desenvolver e manter aplicativos móveis híbridos utilizando Ionic;
Colaborar com equipes de design para criar interfaces intuitivas e responsivas;
Implementar novas funcionalidades e corrigir bugs;
Garantir a integração entre o frontend e os serviços backend;
Definir e implementar a arquitetura das soluções móveis;

**Requisitos e qualificações**

Experiência avançada com Ionic, incluindo Angular ou React;
Conhecimento em HTML5, CSS3 e ES6+;
Familiaridade com ferramentas de versionamento como Git.
Conhecimento em práticas de UX/UI e design responsivo.
Conhecimento em práticas de segurança para aplicativos móveis.
Testes Unitarios.
Conhecimento em Esteira de Desenvolvimento 
Experiência com metodologias ágeis (Scrum, Kanban).

**Contratação**
Cooperado

**Como se candidatar**
Por favor envie um email para [ana.ribeiro@v8.tech ] CV anexado - enviar no assunto: Vaga Angular

**Tempo médio de feedbacks**
Costumamos enviar feedbacks em até cinco dias após cada processo.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
