### ISSUE TITLE
[Belém] FullStack Developer na Proesc

### ISSUE THREAD

**Issue by MarhinaLima** [frontendbr/vagas#8127]
## Proesc
O Proesc.com é o mais moderno sistema de gestão escolar online para instituições de ensino. É especialista em captação de alunos e gestão financeira educacional.

Desenvolvido em 2008 como um software especializado na gestão acadêmica e pedagógica de instituições de ensino, com o passar dos anos, ele foi aperfeiçoado, inovou suas ferramentas de gestão para a educação e se consolidou nas áreas pública e privada.

Todos nós estamos dispostos a inovar a educação e unidos no mesmo propósito: Fazer com que instituições de ensino sejam um SUCESSO!

Vamos juntos inovar a educação?

## Descrição da vaga

Estamos em busca de uma pessoa altamente qualificada para integrar nosso time Tech como Pessoa Desenvolvedora Fullstack Pleno em Belém/PA! Se você é apaixonado(a) por tecnologia, possui experiência com Laravel, PHP e React, está comprometido com a entrega de soluções inovadoras e com alta qualidade e deseja inovar a educação brasileira, queremos conhecer você! 

**Suas principais atividades serão:**

-     Desenvolver e manter aplicações utilizando Laravel e PHP;
-     Projetar e implementar APIs REST para integração com outras partes do sistema;
-     Promover boas práticas de desenvolvimento;
-     Desenvolver e executar testes automatizados;
-     Demonstrar habilidades de comunicação, facilitando a resolução de problemas de forma eficaz;
-     Colaborar eventualmente na revisão de pull requests e na prática de pair programming.

## Local
Híbrido em Belém

## Requisitos

**Obrigatórios:**

-     Experiência com Laravel, PHP, SQL e Docker;
-     Experiência com Reactjs;
-     Conhecimento em Rest API;
-     Conhecimento de boas práticas de desenvolvimento
-     Expertise em testes automatizados;
-     Familiaridade com em controle de versão e métodos ágeis;
-     Boa comunicação e facilidade em resolução de problemas;

**Desejáveis:**

-     Conhecimento em tecnologias como React Native;
-     Participação ativa em comunidades de tecnologia/troca de conhecimento por meio de artigos técnicos e palestras.
-     Ter participação em grandes projetos.

## Benefícios de ser Proescker:

-     Cartão de benefícios Caju;
-     Parceiros para Saúde do Proescker: Conexa Saúde, Wellhub (Gympass) e Clínicas de Saúde de Macapá;
-     Atendimento psicológico interno;
-     Plano de Saúde e Odontológico Amil; 
-     Plataforma de Cursos Alura; 
-     Day-off de aniversário;
-     Plano de carreira Proesc com trilhas Técnica e Liderança.
-     Participação em eventos de Tecnologia.  

Tipo de contratação: Contrato Prestação de Serviços (PJ);

Regime de trabalho: Híbrido [Belém - PA]

Conheça mais sobre a Proesc:

https://www.proesc.com/

**Etapas**

- Candidatura
- Triagem
- Entrevista com a equipe de DEVs
- Desafio técnico
- Entevista com o Gestor

## Como se candidatar
[https://jobs.quickin.io/proesc/jobs/66ba097e2d84b5001372365e](url)

#### Alocação

- Híbrido em Belém

#### Regime
- PJ

#### Nível
- Pleno

**Comment by emvictor** [comment]
Enviado

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
