### ISSUE TITLE
[Remote /Hybrid] IT jobs - Strider 

### ISSUE THREAD

**Issue by Claudiaantunesdelima** [frontendbr/vagas#8128]
Remote and Hybrid IT Jobs 

Only candidates residing in the countries of #Argentina, #Brazil, #Colombia and #Mexico

Senior QA Analyst
React💰USD 5.5k /m) (B2)
app.onstrider.com/r/claudiaantunes?job=c2VuaW9yLXFhLWFuYWx5c3QtNjRmNWVhZDA/cmVmZXJyYWw9Y2xhdWRpYWFudHVuZXM=

Founding Product Engineer - Python, React💰USD 4k /m) (B2)
app.onstrider.com/r/claudiaantunes?job=Zm91bmRpbmctcHJvZHVjdC1lbmdpbmVlci1weXRob24tcmVhY3QtYWFhZWQ1YWQ/cmVmZXJyYWw9Y2xhdWRpYWFudHVuZXM=

Engineering Manager (Hybrid - São Paulo) 💰USD 8k /m) (B2) 
app.onstrider.com/r/claudiaantunes?job=ZW5naW5lZXJpbmctbWFuYWdlci1oeWJyaWQtc2FvLXBhdWxvLTQzNzkzY2Q4P3JlZmVycmFsPWNsYXVkaWFhbnR1bmVz

#Engineering Manager (Hybrid - Bogota)💰USD 8k /m) (C1 /C2) 
app.onstrider.com/r/claudiaantunes?job=ZW5naW5lZXJpbmctbWFuYWdlci1oeWJyaWQtYm9nb3RhLWI0NTU1N2JkP3JlZmVycmFsPWNsYXVkaWFhbnR1bmVz

#Mid Full-stack Engineer - .NET, React.js) 💰USD 3.5k /m(B2) 
app.onstrider.com/r/claudiaantunes?job=bWlkLWZ1bGwtc3RhY2stZW5naW5lZXItLm5ldC03ZDM1ODBiND9yZWZlcnJhbD1jbGF1ZGlhYW50dW5lcw==

#Senior Full-stack Engineer - Typescript, PostgreSQL
💰USD 5k/m(B2)
app.onstrider.com/r/claudiaantunes?job=c2VuaW9yLWZ1bGwtc3RhY2stZW5naW5lZXItdHlwZXNjcmlwdC1wb3N0Z3Jlc3FsLTc4ZmNhNWFhP3JlZmVycmFsPWNsYXVkaWFhbnR1bmVz

#Engineering Manager (Hybrid - Buenos Aires)
💰USD 4k/ month (C1/C2)
app.onstrider.com/r/claudiaantunes?job=ZW5naW5lZXJpbmctbWFuYWdlci1oeWJyaWQtYnVlbm9zLWFpcmVzLTMyMjBkZmE5P3JlZmVycmFsPWNsYXVkaWFhbnR1bmVz

**Comment by Rogjesus** [comment]
hi

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
