### ISSUE TITLE
[São Paulo] Front-End Developer na Estudar com Você

### ISSUE THREAD

**Issue by paulodante** [frontendbr/vagas#813]
### Sobre a Estudar com Você 

**Por que existimos?**  
A [Estudar com Você](https://www.estudar.com.vc) começou por causa de uma dor muito forte e real que existe nas universidades brasileiras: a dor de estudar. Estudar é sinônimo daquela coisa que ninguém quer fazer. É chato, difícil e consome muito do nosso tempo. Nascemos com a ideia de que estudar não precisa ser assim. Estudar pode ser algo legal e eficiente.    

**Como resolvemos essa dor?**
Criamos a melhor experiência de estudo possível. Ensinamos de uma forma personalizada, objetiva e divertida!    

**Quem somos e o que fazemos?** 
Somos uma startup de tecnologia e educação que ajuda alunos universitários a estudarem para suas matérias com videoaulas.    

Hoje ajudamos 17 mil alunos no Brasil, temos como cliente o Insper, uma das melhores faculdades da América Latina, e estamos crescendo rapidamente. Dobramos no último semestre, vamos dobrar de novo esse semestre e nosso sonho é ser a maior e melhor plataforma de estudos do ensino superior no Brasil. Queremos transformar como alunos estudam, tornando o estudo algo legal e eficiente.       

Nossa equipe é composta por cinco pessoas extremamente talentosas. Agora buscamos pessoas para entrarem no time e atingirem esse sonho conosco.    

### Sobre a vaga

- Front-End  
- Presencial ou remota. No caso de presencial, nosso escritório fica em São Paulo no Itaim Bibi    
- Compensação compatível com o mercado  

### Benefícios

- Possibilidade de se tornar sócio  
- Horários flexíveis, ambiente informal e muita autonomia  
- Ter um papel crucial na história da startup e do produto  
- Estar trabalhando com uma equipe excelente
- Gerar um impacto enorme positivo na educação de alunos de todo o Brasil   
- Trabalho dinâmico e com muito aprendizado

### Por que desenvolvimento é importante para a Estudar com Você?

Somos uma empresa de tecnologia. A experiência de aprendizado dos alunos que ajudamos acontece em um site. Esse site e as funcionalidades nele é o que nos permite a gerar valor para os alunos. Isso faz com que o desenvolvimento seja uma parte essencial da empresa.    

### Quais serão as missões do desenvolvedor? 

- Criar funcionalidades novas para o produto  
- Melhorar funcionalidades existentes  
- Testar funcionalidades e criar rotinas de teste  
- Introduzir novas tecnologias no produto que melhoram a experiência dos usuários e dos administradores  

### Como é um dia típico na empresa? 

Trabalhamos com a metodologia de desenvolvimento ágil, usando sprints. Você vai estar cercado de gente muito boa em um ambiente informal. Pode vir de shortes e havaiana se quiser. Nossa hierarquia é horizontal e somos muito abertos a ideias novas. Nossos horários também são flexíveis. O escritório está localizado em um área cheia de restaurantes e lugares para passear também.  

### Requisitos

- Ser proficiente em HTML, CSS e Javascript. Ter pelo menos um nível pleno nessas linguagens  
- Já ter desenvolvido projetos que usam essas linguagens  

### Como funciona nossa processo seletivo? 

- Primeiro, você envia seu currículo e projetos passados para vempra@estudar.com.vc   
- Depois, você preenche um formulário de recrutamento  
- Após analisarmos as respostas no formulário, podemos te chamar para uma entrevista por telefone, em que te perguntaremos sobre suas experiências, o que você gosta, etc  
- Passando na etapa do telefone, podemos enviar um desafio de programação para você se for necessário  
- A última etapa é uma visita ao escritório, em que faremos uma entrevista pessoal e passaremos um desafio de programação. Você também poderá ver como é nosso ambiente de trabalho   

Você pode mandar qualquer dúvida para a gente durante esse processo e temos como objetivo te dar uma resposta sobre as etapas o mais cedo possível   

### Você vai se encaixar bem conosco se você 

- Gosta de desenvolver novas funcionalidades e entregar resultado em um ritmo acelerado  
- Testa todo aspecto de funcionalidades novas minuciosamente   
- Aprende rapidamente e se adapta a situações e prioridades novas  
- Quer construir produtos incríveis com um padrão de qualidade internacional  
- Se identifica com o propósito da empresa e quer melhorar a educação no Brasil  
- Tem sede para aprender  
- Gosta de ser desafiado  
- Traz uma energia boa para o escritório e têm uma atitude humilde  
- Tem espírito de dono sobre o que você está desenvolvendo, assumindo responsabilidade pelo que faz  
- Gosta de desafiar o que é convencional e discutir ideias novas, mesmo que você não concorde com elas  

### Próximos passos

Mande seu currículo e projetos passados para vempra@estudar.com.vc  
O seus projetos passados podem estar organizados em um repositório online (como no Github) ou podem ser links de projetos que você fez ou já trabalhou. Caso tenha sido algo que foi feito por outras pessoas também, descreva em detalhe qual parte foi feita por você.

**Comment by HaluDeCassia** [comment]
Enviado :blush:
