### ISSUE TITLE
[REMOTO] Arquiteto Front-end SR na Nexti

### ISSUE THREAD

**Issue by Camila-Goms** [frontendbr/vagas#8131]
## Nossa empresa

Somos uma empresa de base tecnológica inovadora. Desenvolvemos o NEXTI (http://www.nexti.com/) a Solução Integrada de Gestão de Pessoal e Gestão Operacional no conceito HCM (Human Capital Management), reduzindo custos, principalmente em Empresas com aplicação intensiva de mão de obra descentralizada como Segurança Privada, Facilities (Asseio e Conservação), Franquias e Redes em Geral: Hotéis, Farmácias, Lojas.

Fornecendo a solução completa desde o Hardware local (Terminal Biométrico Inteligente), passando pelo Aplicativo Móvel  e Portal WEB totalmente configurável e intuitivo, estamos revolucionando as relações de trabalho, acompanhando EM TEMPO REAL as atividades dos Colaboradores, identificando e corrigindo inconsistências, eliminando custos e ociosidade, garantindo a  qualidade dos serviços, valorizando os Colaboradores e gerando diferencial competitivo para nossos clientes.

## Local

- 100% Remoto (Brasil).

#### Nível

- Sênior

## Responsabilidades

Será responsável por projetar e implementar a estrutura de aplicações web focadas na interface do usuário (UI) e na experiência do usuário (UX). Esse profissional garante que as aplicações sejam eficientes, escaláveis e de fácil manutenção, utilizando as melhores práticas e tecnologias modernas.

- Planejamento e Design:
Definir a arquitetura das aplicações frontend.
Escolher frameworks, bibliotecas e ferramentas apropriadas.
Criar wireframes e protótipos para guiar o desenvolvimento.
Garantir a integração harmoniosa entre frontend e backend.

- Desenvolvimento:
Escrever código de alta qualidade, modular e reutilizável.
Utilizar tecnologias como HTML, CSS, JavaScript e frameworks como React, Angular ou Vue.js.
Implementar padrões de design e melhores práticas de codificação.
Garantir que a aplicação seja responsiva e compatível com diversos dispositivos e navegadores.

- Colaboração:
Trabalhar em estreita colaboração com designers, desenvolvedores backend e outros stakeholders.
Participar de reuniões de planejamento e revisões de código.
Garantir que a visão do produto seja traduzida efetivamente na interface do usuário.

- Performance e Otimização:
Otimizar a performance do frontend para melhorar a velocidade de carregamento e a responsividade.
Implementar técnicas de otimização como lazy loading, minificação e compressão.
Monitorar e solucionar problemas de performance.

- Manutenção e Atualização:
Manter o código atualizado com as últimas tendências e tecnologias.
Refatorar código existente para melhorar a qualidade e a performance.
Garantir a manutenção de um código limpo e bem documentado.

- Documentação e Treinamento:
Documentar a arquitetura e os padrões de desenvolvimento.
Fornecer orientação e treinamento para a equipe de desenvolvimento sobre as melhores práticas e novas tecnologias.
Conduzir revisões de código e mentorias para outros desenvolvedores.

## Requisitos

**Obrigatórios**

- Bacharelado em Ciência da Computação, Engenharia de Software ou área relacionada;.
- Experiência comprovada como desenvolvedor frontend;
- Experiência com metodologias ágeis;
- Proficiência em HTML, CSS, JavaScript e frameworks modernos como React, Angular ou Vue.js;
- Conhecimento em ferramentas de build e automação (Webpack, Gulp, etc.);
- Experiência com controle de versão (Git);
- Compreensão de princípios de design de UI/UX;
- Habilidades de resolução de problemas e atenção aos detalhes;
- Excelentes habilidades de comunicação e colaboração.

**Requisitos diferenciais**

- Conhecimento em backend (Node.js, APIs RESTful).
- Experiência em desenvolvimento mobile.
- Familiaridade com testes automatizados (Jest, Cypress).

## Benefícios

- Vale Alimentação Swile Food de R$29,14 por dia útil (sem desconto);
- Plano de saúde Unimed Nacional (20% mensalidade (Titulares) ; 50% mensalidade (Dependentes) e 50% de coparticipação);
- Plano odontológico Sulamerica (sem descontos para titulares)
- Vale Transporte para modelo presencial/híbrido (6% descontado em folha);
- Convênio com escola de idiomas e faculdades;
- Acesso a Gympass com Planos a partir de R$29,90;
- Cartão Farmácia ECX - com desconto em folha;
- Empréstimo Consignado Via SomaPay;
- Guapeco - Plano de saúde para pets com valores de R$ 39,90 (Desconto em folha)

**Diferenciais**
- Day Off no dia do seu aniversário + R$100,00 no Swile para você comemorar;
- Happy Hour presencial e encontros online;
- Ambiente e cultura organizacional descontraída;
- Cultura de feedback;
- No dress code.

## Contratação

- CLT

## Como se candidatar

- Se inscreva (de forma super prática) através do link: https://vagasbyintera.inhire.app/nexti/vagas/16816259-1d8c-44d2-8659-94ba771b38f5/arquiteto-front-end-nexti

Espero você lá!

**Comment by SidneyDaniel** [comment]
Enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
