### ISSUE TITLE
[Remoto] Full Stack Senior | Afirmativa para Mulheres e Pessoas Não-Binárias na Gupy

### ISSUE THREAD

**Issue by Karolynnenogueira** [frontendbr/vagas#8132]
## Nossa empresa

A Gupy é uma empresa de tecnologia que une um grupo de pessoas apaixonadas por gerar inovação e impactar o mercado. Somos movidos por grandes desafios e temos um sonho maior ainda: transformar a empregabilidade do país por meio de contratações mais ágeis, justas e encantadoras. 💙

Por isso, estamos sempre em busca de profissionais que amem tecnologia, aprendizado constante e que topem embarcar nessa jornada com a gente. Buscamos pessoas engajadas, com muita garra e, claro, que se identifiquem com nosso propósito e a nossa maior missão.

Estamos crescendo muito rápido e criando produtos ainda mais poderosos a cada dia. O segredo disso? As pessoas incríveis que fazem parte dessa construção diária aqui dentro da Gupy.

Ah, e as vagas são para todo o Brasil, tá bem? Nosso formato de trabalho é 100% remoto, ou seja, você trabalha de onde quiser!

Você é uma pessoa com deficiência e tem dúvidas se pode se candidatar? Saiba que todas as nossas vagas também são para você.

E aí, curtiu? Venha fazer parte do time de uma das HRTechs que mais cresce no Brasil!

## Descrição da vaga

**Como pessoa Full Stack Senior, você vai:**

Desenvolvimento de API’s utilizando [Node.js](http://node.js/), JavaScript/TypeScript;
Desenvolvimento de novas telas utilizando HTML, CSS, JavaScript, Vue e SASS;
Monitorar a saúde das nossas aplicações;
Contribuir com evoluções arquiteturais;
Ajudar com resoluções e melhorias em débitos técnicos;
Propor novas ideias e soluções arquiteturais reutilizáveis;
Identificar melhorias no design de nossos códigos e sistemas;
Identificar gargalos e melhorias de performance em nossas arquiteturas e processos;
Garantir que nossos componentes estejam com um bom design de código;

## Local

Local de trabalho: Remoto

## Requisitos

Experiência como profissional de tecnologia;
Experiência com desenvolvimento de API’s REST;
Experiência com banco de dados relacional;
Experiência com arquitetura e design de sistemas;
Experiência com testes;
Experiência com Git e CI/CD;
Desenvolvimento em aplicações [Node.js](http://node.js/);
Desenvolvimento em aplicações Vue.

**Você se destaca, se tiver:**
Experiência com ferramentas de monitoramento;
Experiência com processos ágeis;
Experiência com práticas DevOps;
Experiência com serviços da GCP.

## Benefícios
Flexibilidade nos seus horários (sim, mesmo no home office);
Vale-refeição no cartão Caju;
Plano médico 100% custeado pela Gupy para você e seus dependentes;
Plano odontológico;
Auxílio home office;
Apoio à saúde mental por meio de nossos benefícios como o Zenklub;
Apoio à saúde física por meio de nossos benefícios como o Gympass;
Licença-maternidade de 6 meses;
Licença-paternidade;
*Nossa política de licença parental é igualmente aplicável a casais homoafetivos, a mães não gestantes e aos casos de adoção, independentemente da idade;
Licença-casamento de 5 dias;
Reconhecimento interno com as nossas Gupy Coins, que você pode resgatar em forma de crédito no seu cartão Caju (prêmios como Vale Netflix, Vale Spotify, Vale Pizza, Vale Gamer, Vale Jantar Romântico);
Dia de folga no seu aniversário;
Às sextas-feiras trabalhamos normalmente até as 15 horas e usamos as outras horas para investir no que nos deixa bem;
Crédito Consignado Creditas, com parcelas descontadas direto na folha de pagamento e juros mais baixos;
Educação Financeira Creditas, com conteúdos exclusivos para você focar na sua educação financeira;
Creditas Store, uma loja para você comprar produtos ou adquirir serviços efetuando o pagamento direto na sua folha de pagamento;  
Férias&Co, que são créditos anuais para você organizar viagens de férias comprando hospedagens e passagens pelo Brasil e pelo mundo via assinatura! Subsidiamos uma parte da mensalidade e é você quem decide se quer contratar o serviço, tá bem?
Oportunidade de se tornar sócio da Gupy.

## Contratação

CLT

## Como se candidatar

Se candidate através desse link: https://tech-career.gupy.io/jobs/7671181?jobBoardSource=gupy_public_page

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
