### ISSUE TITLE
[CURITIBA - PRESENCIAL] Front-end Developer ReactJs Sênior na Brick Seguros

### ISSUE THREAD

**Issue by marihumanaz** [frontendbr/vagas#8133]
A Brick está re-imaginando o seguro de frota na América Latina para que cada frotista tenha acesso a um programa de seguro mais simples e justo
Com acesso à exposição de cada um dos veículos e ao perfil de risco de cada um dos condutores envolvidos na frota, a Brick desenvolveu um algoritmo de inteligência artificial capaz de analisar os dados, identificar potenciais fraudes e fazer a subscrição em tempo real.
O produto da Brick existe para fazer cada gestor de frota dormir tranquilo e software é o coração do nosso negócio
Assim, precificam o seguro frota de acordo com o uso, como uma soma de pequenos episódios de risco, mesclando dados históricos, dados em tempo real e modelos preditivos, ajudando seus clientes a reduzirem o risco da operação e evitarem fraudes, consequentemente reduzindo a sinistralidade e tornando o seguro de frota mais acessível.
Desde o seu lançamento, a Brick vem crescendo 13% ao mês, e já conta com mais de 500 frotas em sua base de clientes, somando aproximadamente 120.000 veículos.
Você vai liderar a construção do módulo de self-onboarding da plataforma de gestão de risco da Brick, atuando diretamente no desenvolvimento front-end, pensando nosso produto para o onboarding de nossos clientes. A construção do módulo tem impacto diretamente no crescimento da empresa.

#O seu desafio na Brick Seguros será:
Você vai liderar a construção do módulo de self-onboarding da plataforma de gestão de risco da Brick, atuando diretamente no desenvolvimento front-end, pensando nosso produto para o onboarding de nossos clientes.
A construção do módulo tem impacto diretamente no crescimento da empresa.
O seu papel inclui trabalhar com times multidisciplinares (designers, engenheiros e outras áreas do negócio) ⁠⁠para desenvolver interfaces elegantes e intuitivas usando React e Tailwind, com altíssima performance através de Zustand e React Query.
Sua expertise em tecnologias front-end e experiência do usuário terá um papel essencial em garantir que nossos clientes consigam selecionar os melhores condutores para sua frota

#O que você vai fazer todos os dias:
Desenvolver e melhorar plataforma web usando TypeScript e React.
Trabalhar em conjunto dom UX/UI Designers para criar telas intuitivas e experiências encantadoras.
Usar tecnologias como Zustand, React Query e Styled-Components para garantir a melhor entrega de valor para o usuário
Integrar componentes front-end com diversos tipos de APIs – GraphQL, Rest, WebSockets, etc – garantindo a melhor captura dos dados e apresentação das informações.
Priorizar a responsividade e performance da aplicação
Colaborar com times de produto para definir requisitos, novas funcionalidades e iterações nas funcionalidades do produto
Prover suporte técnico e ajudar outros desenvolvedores compartilhando insights e conhecimento.

#Estamos atraindo vivências e experiências em:
Aplicações complexas em React
GraphQL como linguagem de consulta, estilo de arquitetura e conjunto de ferramentas para criar e manipular APIs
Styled-Components ou Tailwind
Hooks para interceptação de chamadas de funções, mensagens ou eventos passados entre componentes de software
Frameworks de testes como Jest
Componentização e desenho de arquiteturas escaláveis
Desenvolvimento front-end em React Query e gerenciadores de estado como Zustand/Redux

Oportunidade PJ
Presencial em Curitiba

**Comment by rafaelsevla** [comment]
como candidatar?

**Comment by marihumanaz** [comment]
Pode encaminhar o seu CV para ***@***.***, por favor!

Em sex., 6 de set. de 2024 às 17:25, Rafael Costa ***@***.***>
escreveu:

**Comment by rbjunior000** [comment]
Qual email para enviar o CV?

**Comment by marihumanaz** [comment]
***@***.***

Em seg., 9 de set. de 2024 às 10:32, rbjunior000 ***@***.***>
escreveu:

**Comment by rbjunior000** [comment]
Segue meu CV em anexo.
Vi que trata-se de uma vaga presencial.
Gostaria de adiantar que me mudar para Curitiba não é um problema, após um
tempo de adaptação remoto.

Em seg., 9 de set. de 2024 às 10:40, marihumanaz ***@***.***>
escreveu:

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
