### ISSUE TITLE
[São Paulo] Desenvolvedor PH na Auditto

### ISSUE THREAD

**Issue by RecruiterPaulinha** [frontendbr/vagas#8134]
Estamos a procura de um Programador PHP Pleno com conhecimento em Lógica de Programação; Noção em Arquitetura de Desenvolvimento Web; Conhecimento em pelo menos um banco de dados relacional (MySQL, SQL Server, PostgreSQL (preferencialmente)); Métodos ágeis de desenvolvimento de software – desejável nível básico; Conhecimento em Git; Conhecimentos básicos em HTML, JavaScript e CSS,; Conhecimentos básicos em PHP; Conhecimentos básicos em Jquery, BootStrap; Conhecimentos básicos em API Rest/SOAP;

## Como se candidatar

Por favor envie um email para paula.oliveira@solutta.com com seu CV anexado - enviar no assunto: Vaga PHP

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
Posição PJ 100% Home Office - Nível Pleno

**Comment by pablokaue2004** [comment]
Currículo Enviado

**Comment by Rodricx** [comment]
Aguardando o tal feedback.

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
