### ISSUE TITLE
[Remote] Front-end Developer - React na @YellowIpe

### ISSUE THREAD

**Issue by YellowIpe** [frontendbr/vagas#8135]
## Nossa empresa

Temos a missão de inspirar a conexão da tecnologia com as pessoas, fomentamos o melhor de nossos profissionais através de nossa expertise em encontrar e atrair os melhores talentos para os melhores projetos. O Foco nas Pessoas, Colaboração e Comprometimento são os pilares que nos guiam nessa trajetória.

## Descrição da vaga

- Colaborar com designers, desenvolvedores back end e gerentes de produto para transformar requisitos de negócios em experiências de usuário dinâmicas e responsivas.
- Desenvolver e manter aplicações web utilizando React, garantindo a melhor performance, escalabilidade e usabilidade.
- Implementar componentes reutilizáveis e padrões de design, seguindo as melhores práticas de desenvolvimento frontend.
- Realizar testes de usabilidade e otimizar a experiência do usuário com base em feedback e análises de desempenho.
- Participar de revisões de código e fornecer feedback construtivo para garantir a qualidade e consistência do código.
- Manter-se atualizado com as últimas tendências e tecnologias do frontend, propondo inovações para os projetos em que trabalha.

## Local

Remoto 

## Requisitos

- 6+ anos de experiência profissional em desenvolvimento front end, com foco em React.
- Forte conhecimento em JavaScript, HTML5 e CSS3.
- Experiência com bibliotecas e ferramentas do ecossistema React, como Redux, Hooks, e ferramentas de build.
- Familiaridade com integração de APIs RESTful e design responsivo.
- Habilidade para trabalhar em ambientes colaborativos e dinâmicos.

## Contratação

EX: PJ a combinar

## Como se candidatar

Por favor envie um email para recrutamento@yellowipe.io com seu CV anexado - enviar no assunto: Vaga FrontEnd React

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: recrutamento@yellowipe.io

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by tchiinhemba** [comment]
Acabei de aplicar! 😉

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
