### ISSUE TITLE
[Remoto] Front-End Developer na RioSlum Studio

### ISSUE THREAD

**Issue by robanquieri** [frontendbr/vagas#8140]
## Nossa empresa

RioSlum Studio offers branding, graphic & web design, messaging, strategy services, and video production to daring companies with bold vision. We build compelling brands that evoke emotion, demand attention, and attract business.

We launched RioSlum Studio to ensure all companies, from one-person startups to global corporations, have access to the high-quality, branding and communications services they need to command global attention.

“RioSlum” represents the beauty of innovation and the grit of growing a business.

## Descrição da vaga

RioSlum Studio is looking for a talented Front-End developer to join our distributed (remote) engineering team for a full-time, remote position. Front-End developers liaise between cross-functional teams to understand requirements and recommend and implement solutions that follow best practices. Dedicated to translating wireframes into semantically correct web templates.

This is a Frontend development position. You will be responsible for front-end development on a wide range of projects. The complexity of these projects can vary from small brochure sites to product catalogs, sites, and gated company portals.

Have proven in-depth knowledge of popular JavaScript frameworks such as React, NodeJS, etc., and can articulate JavaScript design patterns. You will be able to work in a variety of client settings and platforms and collaborate in a smart environment where you can bring in your ideas. If you are the type of person who thrives on creating solutions that are both functionally sound and easy for a non-technical person, this role will be a perfect fit for you. 

## Local

Remote 

### Responsibilities
- React-based development.
- Integrate API with Ul.
- Be able to slice XD's to pixel perfection, including margins, paddings, line heights and font sizes.
- Convert design assets (Adobe XD, Sketch, Photoshop, Invision) into component-based
- Stay up-to-date on emerging technologies and frameworks.
- Work with the development team on internal projects that create efficiencies for our client work
- Assist in the scoping of project requirements
- Meet agreed-upon deadlines as defined by you and a Project Manager
- Communicate the status of your work to the Project Manager and relevant project team members
- Participate in internal and client project meetings
- Track time within our company-defined time-tracking tool

### Skills and qualifications
- 5+ years of client-side development experience, preferably in an agency environment.
- Experience using Create React App, Gatsby, and NextJS with SSR.
- Able to manage your own time and never miss a deadline.
- The ability to present the architectural design of a system to project team members and other stakeholders in clear, simple terms.
- Demonstrated ability with HTML, CSS, JavaScript, PHP, and NodeJS.
- Excellent verbal/written communication skills in English and Portuguese.
- A strong appreciation for design and user experience.
- Skilled in front-end development with a focus on cross-browser support
- Experience integrating HTML-based content with other 3rd party environments (i.e. Content Management Systems).
- Experience using CSS preprocessors like Sass, CSS-in-JS, Styled Components
- Experience utilizing the WordPress REST API
- Experience using Git and GitHub
- Experience using NPM
- Uncanny ability (and desire) to dive in and learn unfamiliar systems and tools

## Benefícios

- Opportunity to collaboratively work with top-tier talent
- Competitive salary (Paid in USD)
- Vacation Package
- Health Insurance Stipend
- End-of-year holiday season vacation
- Yearly paid vacation.
- Paid local holidays

## Contratação

PJ a combinar

## Como se candidatar

Please send an email to rogerio@rioslumstudio.com with:

- Subject: Front-End Developer Position
- Attached CV
- Salary expectation in USD
- Most recent React projects you have worked on
- What is your level of proficiency in English?
- How many years of work experience do you have with JavaScript?
- How many years of work experience do you have with React.js?
- How many years of work experience do you have with GitHub?

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by BrenoSapucaia** [comment]
[Profile (1).pdf](https://github.com/user-attachments/files/17516868/Profile.1.pdf)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
