### ISSUE TITLE
[Remote] Senior Full-stack Engineer (Typescript /PostgreSQL) Strider 

### ISSUE THREAD

**Issue by Claudiaantunesdelima** [frontendbr/vagas#8142]
🚀 Let's apply for this incredible opportunity? Senior Full-stack Engineer (Typescript, PostgreSQL) vacancy for a remote team in the USA!** 🚀

🌎 **Exclusive** for candidates from Brazil, Argentina, Colombia and Mexico! 🇧🇷 🇦🇷 🇨🇴 🇲🇽

**Job:** Senior Full-stack Engineer
💻 **Main Tech Stack:** Typescript, PostgreSQL (8+ years of experience)
🔧 **Secondary Tech Stack:** Typescript, PostgreSQL
💼 **Job Title:** Full-stack Development
💰 **Salary:** USD 5K/month
🗣 **English Requirement:** Level B2+
⏳ **Work Hours:** Full-time (40 hours/week), long-term contract

✨ **Benefits:**
✔️ Work with a global team and innovative projects
✔️ Flexibility and continuous career development
✔️ Payment in US dollars!

🔗 **Apply now** and take an important step towards the future of your career: [Apply here](https://app.onstrider.com/r/claudiaantunes?job=c2VuaW9yLWZ1bGwtc3RhY2stZW5naW5lZXItdHlwZXNjcmlwdC1wb3N0Z3Jlc3FsLTc4ZmNhNWFhP3JlZmVycmFsPWNsYXVkaWFhbnR1bmVz)

💼 **Check out other opportunities** and register on our website: [See more vacancies](https://app.onstrider.com/r/claudiaantunes)

🚀 Let's apply for this incredible opportunity? 
Tech Lead - TypeScript, Python, vacancy for a remote team in the USA!** 🚀

🌎 **Exclusive** for candidates from Brazil, Argentina, Colombia and Mexico! 🇧🇷 🇦🇷 🇨🇴 🇲🇽

**Job:** Senior Full-stack Engineer
💻 **Main Tech Stack:** Typescript, Python (8+ years of experience)
🔧 **Secondary Tech Stack:** JavaScript, SQL
💼 **Job Title:** Tech Lead 
💰 **Salary:** USD 5K/month
🗣 **English Requirement:** Level B2+
⏳ **Work Hours:** Full-time (40 hours/week), long-term contract

✨ **Benefits:**
✔️ Work with a global team and innovative projects
✔️ Flexibility and continuous career development
✔️ Payment in US dollars!

🔗 **Apply now** and take an important step towards the future of your career: [Apply here]
app.onstrider.com/r/claudiaantunes?job=dGVjaC1sZWFkLXR5cGVzY3JpcHQtcHl0aG9uLWY4N2YyZjE2P3JlZmVycmFsPWNsYXVkaWFhbnR1bmVz 

💼 **Check out other opportunities** and register on our website: [See more vacancies](https://app.onstrider.com/r/claudiaantunes)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
