### ISSUE TITLE
[Remoto] Frontend Angular Developer na Coodesh

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#8144]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/desenvolvedor-frontend-angular-183537317?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Você fará parte de uma equipe em crescimento, em um ambiente colaborativo e desafiador. Sua missão será atuar na arquitetura e desenvolvimento de interfaces focadas na experiência do cliente, utilizando tecnologias de ponta. Procuramos alguém que goste de inovação e tenha atenção aos detalhes para entregar produtos que encantem os usuários.</p>
<p><strong>O seu papel nessa história:</strong></p>
<ul>
<li>Desenvolver novas funcionalidades e manter produtos existentes em Angular 15+, sempre buscando melhorias e inovação;</li>
<li>Monitorar aplicações utilizando OpenTelemetry e RUM para garantir a performance e a identificação de problemas em produção;</li>
<li>Escrever código de alta qualidade, limpo, testável e fácil de manter;</li>
<li>Definir as APIs necessárias para o front-end e criar mocks para desenvolvimento quando necessário;</li>
<li>Gerenciar o versionamento de código e realizar merges no GIT de maneira eficiente e com boas práticas;</li>
<li>Identificar e resolver bugs de forma proativa e eficaz.</li>
</ul>
<p></p>
## Lastlink: 
 <p>Somos uma startup mineira que ajuda criadores de conteúdo a estarem cada vez mais próximos dos seu público alvo, gerenciando suas comunidades e vivendo daquilo que sabem fazer de melhor. Desenvolvemos um sistema que aproxima e conecta o criador de conteúdo aos seus membros, possibilitando a monetização do conteúdo. Contamos com um time de especialistas em tecnologia, design, marketing, vendas, suporte, que estão transformando o mercado de vendas online e construindo soluções que potencializam o trabalho dos pequenos empreendedores.&nbsp;&nbsp;</p>

<p>Nosso público é formado por criadores digitais, empreendedores e profissionais liberais de diversas áreas. Somos uma empresa pioneira em monetização e gestão de conteúdos exclusivos e construímos o primeiro marketplace de conteúdo exclusivo em redes sociais no mundo.</p><a href='https://coodesh.com/companies/lastlink'>Veja mais no site</a>

 ## Habilidades: 
 - Angular 
- HTML 
- Typescript
## Local: 
 Remota
## Requisitos: 
 - Sólido conhecimento e experiência em JavaScript, HTML5, CSS3, Angular 15+, TypeScript (incluindo Bootstrap, Sass ou Less); 
- Experiência em utilizar layouts do Figma para implementação de interfaces; 
- Proficiência em GIT, com capacidade de realizar merges complexos; 
- Inglês intermediário para leitura e escrita técnica;
## Diferenciais: 
 - Experiência em startups ou empresas de tecnologia; 
- Experiência em Azure DevOps e metodologias de desenvolvimento ágeis; 
- Experiência em sistemas de pagamento; 
- Experiência em sistemas de entrega de conteúdo; 
- Experiência em desenvolvimento mobile com Flutter; 
- Inglês avançado;

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend Angular Developer na Lastlink](https://coodesh.com/jobs/desenvolvedor-frontend-angular-183537317?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
