### ISSUE TITLE
[Remoto] Sênior Frontend Developer na Coodesh

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#8146]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/senior-frontend-developer-193530795?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Estamos em busca de <strong>Sênior Frontend Developer</strong> para compor nossos times!</p>
<p>O time de Engenharia da netLex tem a responsabilidade de lidar com a escalabilidade, manutenção e principalmente implantação de novas features ao nosso produto, atuando de ponta a ponta e propondo soluções para os desafios da empresa.</p>
<p>O netLex surgiu para revolucionar o mercado de Contract Lifecycle Management (CLM), fazendo fluir o trabalho de todos que lidam com documentos. Acreditamos que a experiência deve ser a mais agradável possível e, por que não, divertida?!</p>
<p>Estamos crescendo os nossos times buscando novos talentos que queiram transformar o mundo da gestão do ciclo de vida de documentos com soluções inovadoras. Aqui na netLex temos uma cultura bem forte, que se baseia em um ambiente colaborativo e descontraído para nossos netLecos e netLecas!</p>
<p>Valorizamos a diversidade e são muito bem-vindas candidaturas de pessoas pretas, mulheres, PCD, indígenas, LGBTQIA+ ou outros grupos minorizados 🧡</p>
<p><strong>Responsabilidades:</strong></p>
<ul>
<li>Implementar novas features para facilitar a rotina de trabalho de nossos clientes: as maiores empresas do Brasil e do mundo;</li>
<li>Desenvolver código limpo e escalável;</li>
<li>Compartilhar conhecimento e aprender rápido;</li>
<li>Ser participativo na evolução da arquitetura e infraestrutura das soluções;</li>
<li>Criar novos serviços robustos e escaláveis;</li>
</ul>
<p></p>
## netLex: 
 <p>Os documentos regem todas as relações entre uma empresa e seus stakeholders e têm um grande impacto sobre o sucesso da empresa.&nbsp;</p>
<p>Nós queremos motivar nossos clientes a transformar a maneira como lidam com documentos, para que consigam explorar todo o potencial destes ativos.</p><a href='https://coodesh.com/companies/netlex'>Veja mais no site</a>

 ## Habilidades: 
 - Javascript 
- Typescript 
- SCRUM 
- Angular 
- HTML 
- CSS
## Local: 
 Remota
## Requisitos: 
 - Curso superior completo ou em andamento em Ciência da Computação, Engenharia de Computação, Sistemas de Informação e afins; 
- Experiência com Javascript (ES6+) e seus frameworks; 
- Experiência com arquitetura de sistema web e bancos de dados relacionais; 
- Conhecimentos de Scrum, Kanban e práticas de desenvolvimento ágil; 
- Capacidade de avaliar e se adaptar rapidamente a novas tecnologias; 
- Conhecimento e aplicação das boas práticas de desenvolvimento. 
- Experiência no desenvolvimento de frontend, com linguagens de programação modernas, react, vue e angular.
## Diferenciais: 
 - Demonstrar conhecimento em práticas devOps; 
- Tiver experiência com boas práticas relacionadas à segurança da informação; 
- Abertura para aprender e desenvolver em nossa stack!
## Benefícios: 
 - Modelo Remote First: trabalhe de onde quiser de forma remota, mas caso queira, poderá visitar nossa sede localizada no coração de Belo Horizonte; 
- Equipamentos de trabalho: disponibilizamos o principal que você precisa para poder trabalhar com tranquilidade; 
- Jornada de trabalho flexível: aqui priorizamos entregas de qualidade, e não tempo desprendido; 
- Cartão de benefício flexível Caju: valores mensais para você usar da forma que quiser (Refeição, alimentação, home office, mobilidade e cultura); 
- Plano de saúde e odontológico Sulamerica; 
- Day off de aniversário: tire um dia para curtir e relaxar em até 90 dias após seu aniversário; 
- Licença maternidade e paternidade estendida: para as mamães, licença de 6 meses. Para os papais, licença de 30 dias para curtir o filhote! 
- Gamificação em nossa plataforma de engajamento: compute netcoins que serão revertidos em prêmios a cada trimestre; 
- Educalex: benefício de incentivo à educação para a realização de cursos, workshops, palestras, aquisição de livros e mais! 
- Stock Options: possibilidade de adquirir ações da netLex de acordo com seu desenvolvimento em nosso plano de carreiras.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Sênior Frontend Developer na netLex](https://coodesh.com/jobs/senior-frontend-developer-193530795?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
