### ISSUE TITLE
[Remote] Senior Front-end Engineer - Strider 

### ISSUE THREAD

**Issue by Claudiaantunesdelima** [frontendbr/vagas#8147]
🚀 Let's apply for this incredible opportunity? 
Senior Front-end Engineer - React.js, vacancy for a remote team in the USA!** 🚀

🌎 **Exclusive** for candidates from Brazil, Argentina, Colombia and Mexico! 🇧🇷 🇦🇷 🇨🇴 🇲🇽

**Job:** Sênior Front-end Engineer 
💻 **Main Tech Stack:** React.js (8+ years of experience)
💼 **Job Title:** Senior
💰 **Salary:** USD 5.5K/month
🗣 **English Requirement:** Level B2+
⏳ **Work Hours:** Full-time (40 hours/week), long-term contract

✨ **Benefits:**
✔️ Work with a global team and innovative projects
✔️ Flexibility and continuous career development
✔️ Payment in US dollars!

🔗 **Apply now** and take an important step towards the future of your career: [Apply here]
app.onstrider.com/r/claudiaantunes?job=c2VuaW9yLWZyb250LWVuZC1lbmdpbmVlci1yZWFjdC5qcy05YjJlOWE2OD9yZWZlcnJhbD1jbGF1ZGlhYW50dW5lcw==

💼 **Check out other opportunities** and register on our website: [See more vacancies](https://app.onstrider.com/r/claudiaantunes)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
