### ISSUE TITLE
[Remoto] Desenvolvedor Web Fullstack Pleno 💻 - 

### ISSUE THREAD

**Issue by ecossistemadev** [frontendbr/vagas#8148]
## Descrição da vaga

Estamos buscando um Desenvolvedor Web Fullstack Pleno 👨‍💻 para se juntar ao nosso time! 🚀

Trabalhe remotamente de qualquer lugar do Brasil! 🌎

Se você é apaixonado por tecnologia e busca um ambiente dinâmico e desafiador, essa oportunidade é para você! 😉

## Local

Remoto

## Requisitos

• Experiência comprovada como desenvolvedor web Fullstack, com histórico de participação em projetos significativos. 💼

• Sólido conhecimento em linguagens e frameworks front-end, como JavaScript, React, HTML e CSS. 💻

• Experiência em linguagens e frameworks back-end, especialmente Ruby on Rails. ⚙️

• Familiaridade com bancos de dados SQL e NoSQL, com capacidade de modelagem e otimização de queries. 🗃️

• Experiência na integração de APIs RESTful, com compreensão profunda dos padrões de comunicação entre serviços. 🌐

**Atividades e responsabilidade:**

• Desenvolver e implementar soluções web robustas, eficientes e escaláveis, com foco em qualidade e performance. 💪

• Colaborar com equipes multifuncionais para projetar, desenvolver e implementar novos recursos, bem como aprimorar funcionalidades existentes. 🤝

• Manter e otimizar a performance e a confiabilidade das aplicações, garantindo uma experiência de usuário superior. ✨

• Diagnosticar e solucionar problemas técnicos, propondo soluções inovadoras que agreguem valor ao produto. 💡

• Criar e manter testes unitários e realizar testes de integração para assegurar a qualidade do código. ✅

**Mais Informações:**

É indispensável ter notebook para uso no trabalho. 💻

## Benefícios

• 15 dias úteis de férias - sem desconto na NF 🥳

• Bolsa de Estudos depois de 3 meses de empresa 📚

• Dayoff em aniversário de tempo de empresa 🎉

## Contratação

pj

## Como se candidatar

# [🔗 Clique aqui para se candidatar](https://empregos.dev/vaga/desenvolvedor-web-fullstack-pleno-5724)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 60 dias após cada processo.
E-mail para contato em caso de não haver resposta: 

#### Regime

pj

#### Nível

pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
