### ISSUE TITLE
[São Paulo] Front-end Developer na Kolab

### ISSUE THREAD

**Issue by Kolab-24** [frontendbr/vagas#8149]
## Nossa empresa

Somos uma startup de RH com foco na criação e desenvolvimento de produtos interativos. Criamos experiências únicas e engajadoras para empresa e candidato, buscando sempre a melhor tecnologia e o que há de mais novo!
Fomos certificados pela Great Places to Work como uma das 10 melhores empresas de São Paulo para trabalhar e estamos em expansão e em busca de pessoas que queiram crescer e construir nossos produtos junto a uma equipe criativa e inovadora.

## Descrição da vaga 
- Auxiliar pessoas desenvolvedoras, antecipar, detectar e solucionar erros no produto;
- Ajudar a equipe a revisar PRs e ser uma referência de frontend;
- Oferecer direcionamentos técnicos;
- Assumir a responsabilidade técnica do projeto;
- Estabelecer boas práticas de qualidade;
- Mapear riscos e ajudar a equipe a mitigá-los;
- Traduzir as demandas da gestão estratégica para o time técnico;
- Propor o uso de novas tecnologias capazes de facilitar o trabalho do time;
- Desenvolver e manter interfaces de usuário eficientes utilizando React;
- Desenvolver códigos limpos e bem documentados, garantindo a qualidade e a robustez do software entregue;
- Otimizar aplicações para garantir alta performance e experiência do usuário;
- Participar do ciclo de vida completo de desenvolvimento, desde o design até a implementação;
- Colaborar com diferentes times para garantir uma integração de todos os componentes do projeto;
- Contribuir na definição da arquitetura de projetos/produtos.

## Local

Híbrido, [São Paulo], [São Paulo], [Lapa]

## Requisitos

**Obrigatórios:**
- Ter atuado como Tech Lead;
- Experiência em desenvolvimento web;
- Domínio avançado de linguagens de programação;
- Uso de frameworks e bibliotecas front-end, como React, MobX, GraphQL, Chakra;
- Conhecimento de ferramentas de build (Webpack, Rollup, Nx);
- Familiaridade com arquitetura de micro-frontends;
- Capacidade de escrever código limpo, eficiente e reutilizável;
- Experiência no ciclo de vida de produtos/arquitetura de projetos;
- Excelentes habilidades de comunicação e trabalho em equipe;
- Capacidade de compartilhar conhecimento e tarefas de maneira colaborativa;
- Curiosidade e desejo contínuo de aprendizado.

**Desejáveis:**
- Conhecimento de inglês avançado;
- Experiência trabalhando com IA generativa e APIs relacionadas
- Conhecimento de diferentes tecnologias atuais;
- Conceitos de Design System, Design e UX.

## Benefícios
- Férias;
- Bônus anual no valor da remuneração acordada.

## Contratação
- PJ

## Como se candidatar
Envia seu cv e pretensão salarial para o e-mail [jobs@kolab.com.br](mailto:jobs@kolab.com.br), com o assunto DEV

#### Alocação
- Híbrido (1x por semana presencial);

#### Regime
- PJ

#### Nível
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
