### ISSUE TITLE
[Ribeirão Preto] Front-End Developer Júnior na Cohros

### ISSUE THREAD

**Issue by Soufraz** [frontendbr/vagas#815]
## Descrição da vaga
Precisamos de um(a) dev Front-End que saiba estilizar elementos melhor que MacGyver!

Temos alguns sistemas que precisam ter uma identidade visual bem elegante, intuitiva e principalmente, queremos que os usuários entrem nos sistemas e percebam que os sistemas fazem parte da mesma família. Porém, cada um com sua peculiaridade.    ;)

## Local
Remoto ou Escritório, Ribeirão Preto.
Obs p/ Remoto: manhã da segunda-feira e tarde da sexta-feira, presencial.

## Benefícios
- Alimentação (sem descontos)
- Plano de saúde (sem descontos)
- Plano odontológico (sem descontos)

#### Diferenciais
- Bolsa MC Donalds (2 vezes no mês com a equipe)
- Remuneração variável anual
- Sala com puffs para descanso
- Cozinha bem estruturada
- Ambiente de muito aprendizado e crescimento profissional

## Requisitos
**Obrigatórios:**
- Amar o que faz
- Saber pesquisar like a boss
- Ter um olhar carinhoso para o css

**Desejáveis:**
- Mais de um ano de experiência

**Diferenciais:**
- Já ter refeito a estilização de algum sistema legado

## Contratação
CLT

## Nossa empresa
Para a empresa alcançar resultados, se desenvolver e se perenizar, a responsabilidade pela execução do que foi planejado deve ser compartilhada por todos os colaboradores. Cada um aplicando suas competências na realização de sua parte para o alcance dos resultados organizacionais.

As competências humanas são os principais recursos para promover os desempenhos necessários para viabilizar o alcance dos resultados das organizações.

O trabalho da Cohros é ajudar seus clientes a viabilizar seus objetivos e sua visão de futuro, por meio de práticas eficazes de Gestão de Pessoas, alinhadas à Gestão da Empresa, baseadas na conexão entre o desempenho humano e o desempenho organizacional e do alinhamento de todos os subsistemas para estimular a produtividade das equipes, a qualidade do trabalho e a otimização dos custos com pessoas.

## Como se candidatar
Por favor envie um email para rafael.soufraz@cohros.com.br com seu CV anexado - enviar no assunto: Vaga Front-End Developer Júnior. No corpo do e-mail, enviar sua pretensão salarial e seu portfólio, caso tenha.

## Labels
- Alocado
- CLT
- Cohros
- Front-End
- Júnior
- PJ
- Remoto - Parcial
- Ribeirão Preto
- Vagas

**Comment by fejaum** [comment]
Bolsa MC Donalds é nova huahuahua

**Comment by hugocarreiracosta** [comment]
Oi @Soufraz, tudo bem?   A vaga ainda está disponível ?  Obrigadão

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
