### ISSUE TITLE
[Vila Velha] Front-end Developer na Globalsys

### ISSUE THREAD

**Issue by vansamp** [frontendbr/vagas#8151]
## Nossa empresa
A GLOBALSYS💻 entrega soluções e buscamos pessoas que sejam apaixonadas por construir aplicações distribuídas e de alta performance, escaláveis para milhões de novos usuários em todo Brasil e que suportem a melhor experiência...💙

## Descrição da vaga
Descrição da oportunidade: Estamos buscando um Profissional de frontend com experiência rem react.JS/typescript.

## Local
Vila Velha , Espírito Santo

## Requisitos

**Obrigatórios:**
Proficiência em React e TypeScript.
Experiência comprovada em desenvolvimento de aplicações utilizando React Hooks.
Forte conhecimento em Next.js.
Experiência com estruturação e deploy de aplicações web.
Capacidade de escrever código limpo, eficiente e documentado.
Habilidades de comunicação e trabalho em equipe.

**Diferenciais:**
-Experiência com React Native.
Conhecimento em GraphQL.
Familiaridade com React Hook Form.
Experiência com TanStack Query.
Proficiência em Tailwind CSS.

## Contratação
Contrato por cooperativa

## Como se candidatar
Por favor inscreva-se aqui: https://app.pipefy.com/public/form/bjRnZvU3

- Híbrido
#### Nível
- Pleno

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
