### ISSUE TITLE
[Remoto] Front-end Developer na Diet System

### ISSUE THREAD

**Issue by thiagoferreira123** [frontendbr/vagas#8157]
Estamos em busca de um desenvolvedor frontend com experiência em React e TypeScript para integrar nosso time.

**Atribuições:**
Resolução de pequenos bugs reportados pelos usuários.
Refatoração de trechos de código para melhorar a performance e legibilidade.
Implementação de novas features conforme demanda.

**Requisitos:**
Sólido conhecimento em **React** e **TypeScript**
Experiência com React Native
Familiaridade com MySQL
Experiência com **NestJS** (backend) será um diferencial

**Detalhes da vaga:**
Regime de contratação: PJ
Carga horária: 5 horas diárias
Remuneração: R$ 2.500,00

**Como se candidatar:**
Envie suas experiências anteriores (projetos ou empresas em que trabalhou).
Inclua o contato de pelo menos 1 cliente para referência.
Experiência comprovada nas tecnologias exigidas.

Interessados, favor enviar o currículo e informações para avaliação **vagadietsystem@gmail.com**

**Comment by rodrigosuelli** [comment]
Enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
