### ISSUE TITLE
[Hibrido / São Paulo] Mobile Frontend Sênior na Coodesh

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#8161]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/desenvolvedor-mobile-senior-flutter-e-nativo-android-kotlin-154148635?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Mobile Front-End será responsável por criar e implementar interfaces de usuário em aplicativos móveis, garantindo que os usuários tenham uma experiência fluida, intuitiva e responsiva. Ele trabalha com tecnologias específicas para desenvolvimento mobile, como Flutter (multiplataforma), Kotlin (Android) e Swift (iOS), e se preocupa em garantir que a aplicação rode em diferentes dispositivos móveis.</p>
<p><strong>Responsabilidades:</strong></p>
<p>• Liderar a equipe de desenvolvimento frontend;</p>
<p>• Definir padrões de desenvolvimento e melhores práticas de frontend;</p>
<p>• Coordenar a integração de sistemas complexos de frontend;</p>
<p>• Realizar revisões técnicas e auditorias de código;</p>
<p>• Colaborar com a liderança para alinhar as estratégias técnicas com os</p>
<p>objetivos de negócios;</p>
<p>• Mentorar desenvolvedores juniores e plenos.</p>
<p></p>
<p><strong>Requisitos:</strong></p>
<p>• Inglês Avançado</p>
<p>• Experiência avançada com arquiteturas de sistemas de frontend;</p>
<p>• Conhecimento avançado de segurança em aplicações web;</p>
<p>• Experiência com escalabilidade e alta disponibilidade;</p>
<p>• Habilidade de liderança e gestão de projetos complexos;</p>
<p>• Conhecimento de design web, ux e ui.</p>
<p>• Experiência com fastlane</p>
## JJJ Air Software: 
 <p>Use a Tecnologia para apoiar o seu Negócio. Soluções customizadas com alto teor tecnológico</p></p>

 ## Habilidades: 
 - Kotlin 
- Design UI 
- Design de Front-End 
- Inglês 
- Flutter 
- Swift
## Local: 
 São Paulo
## Requisitos: 
 - Inglês Avançado 
- Experiência avançada com arquiteturas de sistemas de frontend; 
- Conhecimento avançado de segurança em aplicações web; 
- Experiência com escalabilidade e alta disponibilidade; 
- Habilidade de liderança e gestão de projetos complexos; 
- Conhecimento de design web, ux e ui. 
- Experiência com fastlane

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Mobile Frontend Sênior na JJJ Air Software](https://coodesh.com/jobs/desenvolvedor-mobile-senior-flutter-e-nativo-android-kotlin-154148635?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Categoria
Mobile

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
