### ISSUE TITLE
[Remoto] Fullstack VueJs + NodeJS Developer (Pleno) na Coodesh

### ISSUE THREAD

**Issue by gabrielhws** [frontendbr/vagas#8162]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/desenvolvedor-web-pleno-fullstack-141924737?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Somos uma Edtech em crescimento, então aqui o aprendizado é constante e você terá pista livre para decolar e, claro, MUITOS desafios! Além disso, você trabalhará ao lado de pessoas diversas e talentosas que irão te auxiliar a maximizar todo o seu potencial de gerar o maior impacto positivo possível!</p>
<p>Sonhamos alto e apostamos no potencial das nossas pessoas, acreditando que cada um tem um papel fundamental na nossa jornada e no alcance dos nossos objetivos. Temos o compromisso de ser uma empresa onde todos tenham a oportunidade de exercer desenvolvimento pessoal e profissional.</p>
<p>Nosso dia a dia é movido por uma cultura inspiradora e inclusiva, que busca a equidade e valoriza as diferenças. Por isso, buscamos pessoas cada vez mais diversas e inovadoras para fazer parte desse propósito!</p>
<p>❗ Quais são as suas principais responsabilidades:</p>
<ul>
<li>Você participará do desenvolvimento de aplicativos Web, usando sua experiência para garantir alta qualidade, desempenho e usabilidade.</li>
<li>Você irá colaborar com designers de interface do usuário e outros desenvolvedores para traduzir requisitos de negócios em soluções técnicas eficazes.</li>
<li>Implementar melhores práticas de desenvolvimento de software e garantir a conformidade com os padrões de codificação estabelecidos.</li>
<li>Você participará ativamente dos fluxos de code-review e fornecerá feedback construtivo para outros membros da equipe.</li>
<li>O acompanhamento das métricas das plataforma fará parte de seu dia-a-dia, visando compreender e participar eficientemente da resolução de  problemas de desempenho e otimizar a funcionalidade dos aplicativos.</li>
</ul>
<p>❗Não pode faltar:</p>
<ul>
<li>Formação em Ciência da Computação, Sistemas de Informação ou áreas afins ou experiência técnica comprovada;</li>
<li>Experiência em desenvolvimento Web de pelo menos 3 anos;</li>
<li>Experiência sólida em desenvolver e manter uma aplicação mobile utilizando o framework Vue;</li>
<li>Experiência no desenvolvimento de Testes de componentes e Testes de Integração em Vue;  </li>
<li>Experiência sólida em Node.JS;</li>
<li>Experiência em GraphQL;</li>
<li>Excelente capacidade de seguir arquiteturas limpas;</li>
<li>Excelente capacidade em seguir princípios de código limpo;</li>
<li>Excelente capacidade em aplicar os princípios SOLID em seu cotidiano.</li>
</ul>
<p>❗Vamos amar se tiver também:</p>
<ul>
<li>Desejável conhecimentos em Neo4j.</li>
</ul>
<p>Se você também sonha alto (ao infinito e além!), tem paixão no que faz, tem garra (cai mas levanta!), trabalha com transparência, e quer um ambiente de trabalho onde você tenha a oportunidade de evoluir constantemente, a Jovens Gênios é o seu lugar!</p>
<p>Aqui, temos as melhores pessoas e todas se unem pelo mesmo propósito: transformar a educação mundial através da tecnologia e democratização de acesso.</p>
## Jovens Gênios: 
 <p>Se o seu propósito é revolucionar a educação brasileira através de inovação e tecnologia numa startup com vários desafios, a Jovens Gênios é o lugar certo para você! 😍</p>
<p>As plataformas digitais adaptativas de aprendizagem e avaliação gamificada da Jovens Gênios tornam o aprendizado dos alunos do 1° ao 9°ano muito mais divertido e individualizado. 🥳</p>

 ## Habilidades: 
 - GraphQL 
- Node.js 
- Vue.js 
- Neo4j
## Local: 
 Remota
## Requisitos: 
 - Formação em Ciência da Computação, Sistemas de Informação ou áreas afins ou experiência técnica comprovada
## Diferenciais: 
 - Desejável conhecimentos em Neo4j
## Benefícios: 
 - Vale alimentação 
- Vale refeiçãoA 
- Auxílio Home Office 
- Plano de saúde 
- Plano odontológico 
- Totalpass 
- Day off de aniversário 
- Seguro de vida e assistência funeral 
- Descontos em cursos e universidades com os parceiros da Jovens Gênios 
- Universidade Corporativa
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Fullstack Developer (Pleno) na Jovens Gênios](https://coodesh.com/jobs/desenvolvedor-web-pleno-fullstack-141924737?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Categoria
Full-Stack

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
