### ISSUE TITLE
[Remoto] Fullstack Developer - Ruby on Rails na Conecta Capital Humano

### ISSUE THREAD

**Issue by raissaime** [frontendbr/vagas#8163]
## Nossa empresa

A Conecta Capital Humano está buscando Desenvolvedor Fullstack para um de seus clientes:
Twygo - plataforma LMS que reúne as funcionalidades essenciais para que empresas possam criar e desenvolver, de maneira efetiva, seus treinamentos. Proporcionamos um ambiente que facilita a execução das capacitações e gera insights para que líderes desenvolvam pessoas.

Através da nossa comunidade de conteúdos sobre gestão de aprendizagem, ajudamos as empresas a concretizar trilhas de aprendizagem, desenvolver as competências de seus colaboradores, e acompanhar facilmente a educação empresarial. Acreditamos que a aprendizagem transforma as pessoas. Nós transformamos a aprendizagem. 

## Descrição da vaga

- Desenvolver e implementar soluções web robustas, eficientes e escaláveis, com foco em qualidade e performance.
- Colaborar com equipes multifuncionais para projetar, desenvolver e implementar novos recursos, bem como aprimorar funcionalidades existentes.
- Manter e otimizar a performance e a confiabilidade das aplicações, garantindo uma experiência de usuário superior.
- Diagnosticar e solucionar problemas técnicos, propondo soluções inovadoras que agreguem valor ao produto.
- Criar e manter testes unitários e realizar testes de integração para assegurar a qualidade do código.

## Local

Remoto em SP/SC/PR.

## Requisitos

- Experiência comprovada como desenvolvedor web Fullstack, com histórico de participação em projetos significativos.
- Sólido conhecimento em linguagens e frameworks front-end, como JavaScript, React, HTML, e CSS.
- Experiência em linguagens e frameworks back-end, especialmente Ruby on Rails.
- Familiaridade com bancos de dados SQL e NoSQL, com capacidade de modelagem e otimização de queries.
- Experiência na integração de APIs RESTful, com compreensão profunda dos padrões de comunicação entre serviços.

## Diferenciais

- Experiência prévia em projetos utilizando Ruby, com contribuições significativas para o código.
- Participação em projetos de larga escala implementados com React.
- Conhecimento avançado em ferramentas de controle de versão, como Git, com boas práticas de branching e versionamento.
- Certificações ou cursos relevantes na área de desenvolvimento web.
- Experiência com TypeScript, com aplicação prática em projetos de médio ou grande porte.

## Benefícios

- 15 dias úteis de férias - sem desconto na NF
- Bolsa de Estudos depois e 3 meses de empresa
- Dayoff em aniversário de tempo de empresa

## Contratação

PJ

## Como se candidatar

Envie currículo para raissaime@outlook.com
### Nível

- Pleno

### Regime

- PJ
- Contrato

### Alocação

- Remoto

**Comment by netosts** [comment]
Enviado!

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
