### ISSUE TITLE
[São Paulo] Front-end Developer na XBRI

### ISSUE THREAD

**Issue by giovaneRamosSunset** [frontendbr/vagas#8164]
## Nossa empresa

A XBRI Pneus é uma marca privada que pertence à Sunset Tires Corporation, empresa que atua desde 1988 com foco em importação, exportação e distribuição de pneus, sendo a maior destes segmentos na América Latina. Seus produtos são produzidos em fábricas de primeira linha no Vietnã, Malásia, Tailândia e China.

## Descrição da vaga

Como Front-end Developer, você atuará em nossa frente de Outsourcing, composta por um time de desenvolvimento que tem o objetivo de trazer soluções para o nosso e-commerce. O time trabalha no modelo presencial e home office, desenvolvendo uma relação próxima e colaborativa, com oportunidades de criação e resolução de problemas.
Você se dará muito bem se for uma pessoa que procura resolver problemas, independentemente da tecnologia que utilizar, que seja comunicativo(a), analítico(a)a e que busque aprender e crescer profissionalmente!

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com angular 2+

**Desejáveis:**

- Integrações via Web API
- Javascript, HTML e CSS
- Conhecimento com GIT
- Clean Architecture, SOLID
- Metodologias ágeis, Scrum e Kanban

**Diferenciais:**

- Implementar conceitos de programação reativa para gerenciar estados e eventos na aplicação utilizando Rxjs e Signals.
- Garantir a performance, qualidade e responsividade das aplicações.
- Colaborar com equipes de back-end e design para integrar soluções front-end.
- Participar na revisão de código, garantindo as melhores práticas de desenvolvimento.
- Contribuir para a arquitetura da aplicação, com foco em usabilidade, performance e escalabilidade.
- Gerenciar aplicações rodando em ambiente de containers, garantindo sua eficiência e segurança.

## Contratação

- Contratação PJ

## Como se candidatar

Favor enviar um e-mail para ulysses@xbri.com.br com o assunto "Front-end Developer na XBRI"

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Sênior
- Especialista

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
