### ISSUE TITLE
[Hibrido / São Paulo] Front-end Pleno (React + Typescript) Híbrido (3 vezes por semana) na Coodesh

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [frontendbr/vagas#8165]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/front-end-pleno-react-typescript-hibrido-3-vezes-por-semana-204307746?utm_source=github&utm_medium=frontendbr-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>Desenvolvedor Front-end Pleno </strong>- atuação híbrida (3 vezes na semana)</p>
<p></p>
<p>Buscamos um profissional com sólidos conhecimentos de React, Next, Typescript, Redux, Hooks, HTML, CSS e JavaScript. Experiência com desenvolvimento Web responsivo. Procuramos uma pessoa que: Goste de trabalhar em equipe e seja colaborativa em suas atribuições. Tenha coragem para se desafiar e ir além, abraçando novas oportunidades de crescimento.</p>
<p></p>
<p><em>Habilidades Obrigatórias</em></p>
<p>&gt;REACT</p>
<p>&gt;Typescript</p>
<p>&gt;Axios</p>
<p></p>
<p><em>Habilidades Desejáveis</em></p>
<p>&gt;JAVA</p>
<p></p>
<p>Modelo de Contratação: PJ</p>
<p>Local: Av. Faria Lima, São Paulo, Capital</p>
<p>Inicio Imediato</p>
## Triforce IT - Consultoria de TI: 
 <p>A TriforceIT é uma consultoria especializada em TI.</p>
<p>Estamos desde 2022 atuando em algumas frentes: DevOps, Desenvolvimento, Mobile, Database e Cybersegurança.</p><a href='https://coodesh.com/companies/triforce-it-consultoria-de-ti'>Veja mais no site</a>

 ## Habilidades: 
 - React.js 
- Typescript 
- Java 
- Redux 
- HTML 
- Rest API
## Local: 
 São Paulo

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Front-end Pleno (React + Typescript) Híbrido (3 vezes por semana) na Triforce IT - Consultoria de TI](https://coodesh.com/jobs/front-end-pleno-react-typescript-hibrido-3-vezes-por-semana-204307746?utm_source=github&utm_medium=frontendbr-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Regime
PJ
#### Categoria
Front-End

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
