### ISSUE TITLE
[Remote] Founding Software Engineer (Tech Lead) - Ruby on Rails - Strider 

### ISSUE THREAD

**Issue by Claudiaantunesdelima** [frontendbr/vagas#8166]
🚀 Let's apply for this incredible opportunity?  vacancy for a remote team in the USA!** 🚀

🌎 Exclusive for candidates from Brazil, Argentina, Colombia and) Mexico! 🇧🇷 🇦🇷 🇨🇴 🇲🇽

💼Founding Software Engineer (Tech Lead) - Ruby on Rails
💻 Main Tech Stack: Ruby on Rails, AWS and Stripe (9+ years of experience)
💰 Salary: USD 6K/month
🗣 English Requirement: Level B2+
app.onstrider.com/r/claudiaantunes?job=Zm91bmRpbmctc29mdHdhcmUtZW5naW5lZXItdGVjaC1sZWFkLXJ1Ynktb24tcmFpbHMtY2UxNWE4NTY/cmVmZXJyYWw9Y2xhdWRpYWFudHVuZXM=

💼Job: Web Designer
💻 Main Tech Stack: Wordpress, Figma and Adobe (3+ years of experience)
🔧 Secondary Tech Stack: JavaScript, HTML and CSS 
💰 Salary: 🚀 Let's apply for this incredible opportunity?  vacancy for a remote team in the USA!** 🚀

🌎 Exclusive for candidates from Brazil, Argentina, Colombia and) Mexico! 🇧🇷 🇦🇷 🇨🇴 🇲🇽

💼Founding Software Engineer (Tech Lead) - Ruby on Rails
💻 Main Tech Stack: Ruby on Rails, AWS and Stripe (9+ years of experience)
💰 Salary: USD 6K/month
🗣 English Requirement: Level B2+
app.onstrider.com/r/claudiaantunes?job=Zm91bmRpbmctc29mdHdhcmUtZW5naW5lZXItdGVjaC1sZWFkLXJ1Ynktb24tcmFpbHMtY2UxNWE4NTY/cmVmZXJyYWw9Y2xhdWRpYWFudHVuZXM=

💼Job: Web Designer
💻 Main Tech Stack: Wordpress, Figma and Adobe (3+ years of experience)
🔧 Secondary Tech Stack: JavaScript, HTML and CSS 
💰 Salary: USD 3.5K/month 
🗣 English Requirement: Level B2+
⏳ Work Hours: Full-time ( 40 hours/week), long-term contract
app.onstrider.com/r/claudiaantunes?job=d2ViLWRldmVsb3Blci1kZXNpZ25lci1kZjY4Yjg5Yz9yZWZlcnJhbD1jbGF1ZGlhYW50dW5lcw==

💼Check out other opportunities and register on our website: [See more vacancies](https://app.onstrider.com/r/claudiaantunes)/month 
🗣 English Requirement: Level B2+
⏳ Work Hours: Full-time ( 40 hours/week), long-term contract
app.onstrider.com/r/claudiaantunes?job=d2ViLWRldmVsb3Blci1kZXNpZ25lci1kZjY4Yjg5Yz9yZWZlcnJhbD1jbGF1ZGlhYW50dW5lcw==

💼Check out other opportunities and register on our website: [See more vacancies](https://app.onstrider.com/r/claudiaantunes)

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
