### ISSUE TITLE
[Recife] Front-end Developer na Nutcache

### ISSUE THREAD

**Issue by raissaime** [frontendbr/vagas#8167]
## Nossa empresa

Foi em 2013 que a Nutcache iniciou as suas atividades como um simples aplicativo de faturamento, transformando-se em um dos melhores aplicativos de gerenciamento de projetos colaborativos completos. A Nutcache nasceu graças a dois empresários que têm muitos anos de experiência comprovada no desenvolvimento de aplicações de faturamento, contabilidade e gerenciamento, aplicações usadas por milhares de usuários em todo o mundo. A Nutcache é uma empresa do grupo [Dynacom Technologies] (https://www.dynacom.com/).

Apoiada por um grupo de indivíduos altamente talentosos e apaixonados por criar um produto que oferece uma experiência de usuário excecional, o objetivo da Nutcache é melhorar a qualidade de vida para empresas de todos os tamanhos e trabalhadores independentes dominados pelos imperativos empresariais de gestão de uma empresa. Esperamos que ao usar o Nutcache, essas empresas tenham maiores resultados para garantir seu sucesso através de um crescimento sustentado.

## Descrição da vaga

**Desenvolvedor - Frontend**

Responsabilidades:
- Análise, planejamento e desenvolvimento das funcionalidades;
- Colaborar ativamente com o SCRUM Master e o Product Owner nas entregas;
- Participar da análise da arquitetura necessária para desenvolvimento;
- Seguir o método Scrum, utilizada pelos times para gestão das atividades diárias;

## Local

Híbrido 2x na região de Pina, Recife-Pe.

## Requisitos

**Obrigatórios:**
- Formação em Ciência da Computação e cursos relacionados;
- Ampla experiência em desenvolvimento frontend;
- Experiência com React e Redux;
- HTML, CSS e Javascript;
- Inglês Avançado (entrevista técnica com nativos - Canadá);
- Desenvolvimento usando metodologias ágeis e ferramentas Scrum e Kanban.

**Desejáveis:**
- Git e Visual Studio Code;
- Noções de UI/UX e habilidades básicas de Design;
- React Hooks;
- Typescript;
- Redux Toolkit; 
- API Rest;
- Testes Unitários.

## Benefícios

- Plano de saúde - Bradesco Saúde Top Nacional - 100% custeado pela Nutcache;
- Plano Odontológico - Bradesco Odonto - - 100% custeado pela Nutcache;
- Seguro de vida;
- Gympass;
- Flash Benefícios (Alimentação, refeição e mobilidade);
- Gratificação por indicação;
- Dayoff mês aniversário;
- Auxílio creche /Idiomas/ Lente
- Entre outros.

## Contratação

 CLT

## Como se candidatar

Por favor envie um email para raissaime@outlook.com com seu CV anexado e pretensão salarial- enviar no assunto: Vaga Frontend @ Nutcache

#### Alocação
- Híbrido
- Recife

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
