### ISSUE TITLE
[Remoto-SP] Front-end Angular Developer na Achievemore

### ISSUE THREAD

**Issue by gisellerocha** [frontendbr/vagas#8168]
## Nossa empresa

A AchieveMore está em busca de um Desenvolvedor Frontend, para se juntar ao nosso time. Procuramos pessoas que auxiliem no desenvolvimento de novos produtos, capazes de resolver problemas e que estejam em constante aprendizado, onde a pró-atividade em propor soluções e melhorias é muito bem vista. Como desenvolvedor você se juntará ao time responsável pela análise e desenvolvimento de um sistemas web, mobile, automação de processos, ETL, integração de sistemas e APIs.

## Descrição da vaga

O profissional será responsável em prover soluções técnicas para novas features e dar o suporte necessário as features já existentes.

Esperamos também que essa pessoa auxilie os outros membros do time em questões técnicas não esquecendo de fornecer a melhor solução para o negócio.

Algo que prezamos bastante é qualidade, isso inclui um código limpo e legível (clean code).

Nossa stack atualmente é composta por **AngularJS**, **Angular** na versão 18 e o backend em Ruby on Rails.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência em Angular;
- RxJs
- CSS3 (SCSS)
- HTML5
- Bootstrap/Material Design;
- TypeScript
- JavaScript
- Git

**Desejáveis:**
- Graphql
- JWT, RestFull, oAuth2.0;
- Docker, Gulp, Gerenciamento de Pacotes (ex: NPM, Yarn) e TDD;
- Banco de Dados Relacional

## Contratação
 PJ com prazo indeterminado

## Como se candidatar

Por favor envie um email para fabiana.ribeiro@achievemore.com.br com seu CV anexado - enviar no assunto: Vaga Front-end

#### Alocação
- Remoto 

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by yurinicoliche** [comment]
CV enviado!
