### ISSUE TITLE
[Remoto] Front-end Developer na Epikerdis.ai

### ISSUE THREAD

**Issue by Joaovsa7** [frontendbr/vagas#8169]
## Nossa empresa

Você está pronto para liderar a próxima geração de colaboração entre humanos e IA?

O mundo do trabalho está prestes a passar por uma transformação dramática. A IA Generativa está prestes a impactar 80% da força de trabalho mundial, mudando a maneira como trabalhamos, aprendemos e interagimos. Isso não é uma ameaça; é uma oportunidade.

Na Epikerdis.ai, não estamos apenas construindo parceiros de negócios impulsionados por IA; estamos moldando o futuro do trabalho. Nossa missão é ampliar o potencial humano criando parceiros de IA que oferecem insights, habilidades e adaptabilidade necessárias para prosperar em uma economia movida pela IA.

## Descrição da vaga

Estamos em busca de um  Desenvolvedor Full-Stack com foco em Front-End para se juntar à nossa equipe e participar do desenvolvimento de projetos incríveis para nossos parceiros de negócios. Você será fundamental na criação de como os humanos interagem e se beneficiam de nossa tecnologia de IA de ponta.

## Local

Remoto

## Requisitos

**Obrigatórios:**

- Experiência sólida com tecnologias voltadas para a web, como NextJS, Typescript e Tailwind.
- Experiência na ideação de telas e protótipos junto ao time de UI/UX;
- Conhecimento de boas práticas de código;
- Sólido conhecimento em mobile-first css (design responsivo);
- Bom conhecimento de UX/UI;
- Experiência em testes unitários e modelo TDD;
- Experiência em integração e suporte de API's REST/GraphQL
- Experiência com banco de dados relacional e não relacional (NoSQL);
- Versionamento de código (Git);
- Entendimento sobre Arquitetura de projetos em Front-end;
- Familiaridade com aplicativos e contêineres e uso de Docker.

**Desejáveis:**
- Experiência em computação na nuvem (Google Cloud Platform);
- Experiência com desenvolvimento de SaaS;

## Contratação

PJ com 4 meses de contrato; com possibilidade de extensão;

## Como se candidatar

Por favor envie um email para join@epikerdis.ai com seu CV anexado - enviar no assunto: Vaga Fullstack - Foco Front-end

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: joao@epikerdis.ai

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno

**Comment by YuriBrunetto** [comment]
Enviado!

**Comment by PedroLimass** [comment]
Enviado

**Comment by LarissaCalmeida** [comment]
Enviado.
