### ISSUE TITLE
[Remoto] Front-End Developer na [inDecks]

### ISSUE THREAD

**Issue by Ricardoaugustovt** [frontendbr/vagas#817]
## Descrição da vaga

Desenvolver interfaces na maioria dos casos de Intranets.
Nós trabalhamos bastante com a plataforma SharePoint (se já conhecer é um diferencial).

## Local

Remoto

## Requisitos

**Obrigatórios:**
- HTML5
- JavaScript
- Angular JS
- Bootstrap
- Responsibidade
- CrossBrowser

**Desejáveis:**
- Ter trabalhado com SharePoint

**Diferenciais:**
- Experiência prévias com intranets

## Contratação

PJ a combinar

## Nossa empresa

inDecks. Trabalhamos no mercado de Softwares Corporativos há alguns anos e temos algumas intranets internacionais para clientes grandes.

## Como se candidatar

Por favor envie um email para contato@indecks.pro com seu CV anexado - enviar no assunto: Vaga Front End

## Labels

- Remoto
- PJ

**Comment by allisonsampaio** [comment]
Enviado!

**Comment by danielswater** [comment]
Enviado

**Comment by amarcelaxs** [comment]
enviado

**Comment by eduardolops** [comment]
Enviado

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
