### ISSUE TITLE
[Remoto] Front-end Developer na Gendoc

### ISSUE THREAD

**Issue by g-freire** [frontendbr/vagas#8170]
## Nossa empresa

Utilize a IA generativa para trabalhar de forma mais rápida, criativa e precisa.
Um produto desenvolvido para maximizar a produtividade das empresas e valorizar o que há de mais precioso: seu tempo

## Descrição da vaga

Buscamos desenvolvedores para o frontend de nosso app web (Desktop). Atualmente o app está em fase de MVP (pre-launch). Esta sendo desenvolvido com React e Next.js, seguindo as melhores práticas do mercado.

## Local

Remoto 

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com React e Javascript
- Experiência com Next.js

**Desejáveis:**
- 2 anos de experiência com Agile
- conhecimentos em tailwind

**Diferenciais:**
- Projetos opensource
- Habilidade de trabalhar async

## Benefícios
- Estágio com remuneração de RS3600
- ou
- R$ 35 por hora para desenvolvedores juniors/plenos
- R$ 45 por hora para desenvolvedores seniors
- Oportunidade de trabalhar com arquitetos de software seniors e na área de IA

- Salário negociavel dependendo de experiencia

## Contratação

EX: Estágio ou  PJ a combinar

## Como se candidatar

Por favor envie um email para leogs0204@gmail.com com seu CV anexado - enviar no assunto: Vaga Gendoc

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- Estágio
- PJ

#### Nível
- Júnior
- Pleno
- Sênior
- Especialista

**Comment by ViniciusBussolo1** [comment]
Enviado!

**Comment by PedroLimass** [comment]
Enviado!

**Comment by dominguetigs** [comment]
Enviado!

**Comment by CodeDeivid** [comment]
Enviado!

**Comment by vanessawin** [comment]
Enviado

**Comment by HenriqueTMD** [comment]
Enviado

**Comment by Thyago-Josef** [comment]
Enviado!

**Comment by apenasumuser** [comment]
estagio com 2 anos de experiencia em react?

**Comment by LarissaCalmeida** [comment]
Enviado.

**Comment by vinidiias** [comment]
Enviado.

**Comment by Dirosaki** [comment]
CV Enviado!

**Comment by MarcioBADias** [comment]
Enviado

**Comment by RafaelAF** [comment]
Enviado!

**Comment by Nicker2** [comment]
Enviado

**Comment by a-ndreFerreira** [comment]
Enviado
