### ISSUE TITLE
[Squizoland] Front-end Developer na *yo-lara*

### ISSUE THREAD

**Issue by akemi-bit** [frontendbr/vagas#8173]
## Procuramos:

-  Jr / Pleno Frontend;
- Foto de anime tem prioridade;
- Disposição a aprender nossas tecnologias;
- Conhecimento prévio em HTML, CSS e JS/TS;

**Diferenciais do contratado:**
- Projetos em portfólio;

**Diferenciais:**

- Faça seu horário de trabalho, apenas entregar o que é demandado.

## Contratação

PJ;

## Como se candidatar

Me chame no discord: datapanthom
Ou entre na nossa comunidade: https://discord.gg/jnsWGBsW

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

![image](https://github.com/user-attachments/assets/3159f1f2-bb31-4c9b-a0e0-063155e4b8d9)

**Comment by nythrox** [comment]
gostamos de type theory, PL theory, compiladores, criar frameworks, tecnologias experimentais e mais

**Comment by erikbrito** [comment]
da como convite invalido
