### ISSUE TITLE
[Remoto] Front-end Developer na Hepta Tecnologia [.NET C#]

### ISSUE THREAD

**Issue by GitMateusBruno** [frontendbr/vagas#8176]
## Nossa empresa

Somos a Hepta tecnologia; empresa sediada em Brasília com 33 anos de atuação. Temos contratos com empresas privadas e órgãos públicos, em virtude disso aqui é um espaço amplo de crescimento e desenvolvimento profissional. O time é bastante colaborativo, na verdade colaboração faz parte do nosso valor 🚀

## Descrição da vaga

Projeto em .NET 8; Metodologia Ágil Scrum; Teste Unitário; SonarQube

## Local

Remoto

## Requisitos

**Obrigatórios:**
- 5 anos de experiência com .NET
- Experiência: Comprovação de experiência na área.
Formação: Formação em Tecnologia da Informação (TI) devidamente comprovada.
Certificações: Certificação obrigatória em Professional Scrum Developer (PSD) ou Certified Scrum Developer (CSD).

**Caso você não possua, concedemos um prazo para adquirir. É importante ressaltar que a empresa não cobre os custos, apenas oferece a oportunidade de estender o prazo.**

**Desejáveis:**
- conhecimentos em Scrum
- conhecimentos em Azure DevOps

## Benefícios

- Plano de saúde
- Plano Odontológico
- VR ou VA valor fixado em convenção coletiva
- Auxílio Home Office
- ...

**Diferenciais:**
- Parceria com Google e AWS 

## Contratação

CLT

## Como se candidatar

Por favor envie um email para mateus.sousa@hepta.com.br seu CV anexado - enviar no assunto: Vaga .NET

#### Alocação
- Alocado
- Remoto

#### Regime
- CLT

#### Nível
- Pleno
- Sênior

**Comment by felipefialho** [comment]
Esta vaga encontra-se há um bom tempo sem novas interações. Se ainda estiver aberta, faça um comentário, caso contrario, a fecharemos automaticamente em 5 dias.
