### ISSUE TITLE
[REMOTO] Full-stack Developer na yo-lara

### ISSUE THREAD

**Issue by akemi-bit** [frontendbr/vagas#8177]
## [yo-lara](https://yo-lara.com/)

THE FUTURE,
TODAY.

## Descrição da vaga

Precisamos de um(a) desenvolvedor(a) fullstack pleno para atuar no seguinte projeto:

- Plataforma para venda de cursos
  - O criador de conteúdo deve poder ter uma página própria onde exibe todos os cursos que possuí a venda;
  - (Possibilidade) Uma área de upload de podcasts;
  - Deve ter um saque rápido;
  - Uma área de membros personalizada para quem comprou os cursos;
- Parte técnica
  - Uma hospedagem para os vídeos (podemos fazer isso self-hosted com o próprio supabase);
  - Um intermediário de pagamentos (possibilidade: stripe);

## Requisitos

**Obrigatórios:**
- Experiência com implementação de pagamentos;
- Experiência com hospedagem de arquivos;
- Typescript, React;

**Desejáveis:**
- Saber se virar com encaixe de componentes (next.ui);
- Ser proeficiente;

**Diferenciais:**
- Projetos ou trabalhos que referencie o pedido acima;

## Benefícios

- Salário: 7 Mil reais, dependendo do nível do desenvolvedor, a negociar para cima;

**Diferenciais:**
- Faça seu horário de trabalho, desde que esteja disponível e entregue o que for pedido.

## Contratação

PJ;

## Como se candidatar

Por favor envie um email para contact@yo-lara.com com seu CV anexado - enviar no assunto: Desenvolvimento plataforma de cursos - Pleno;
Temos também uma comunidade: https://discord.gg/jnsWGBsW
Favor, anexar o currículo no canal **owo** caso entre na comunidade.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior
- Especialista

**Comment by nythrox** [comment]
gostamos de type theory, PL theory, compiladores, criar frameworks, programação funcional e lógica, tecnologias experimentais e mais
