### ISSUE TITLE
[São Paulo e Campinas] Front-end Developer na Movile, iFood, PlayKids e outras

### ISSUE THREAD

**Issue by MovileGente** [frontendbr/vagas#818]
## Descrição da vaga
Vagas para Front-end Developers que queiram nos ajudar a construir produtos globais, que impactam a vida das pessoas e estão presentes no dia a dia delas. Mas dessa vez queremos propor uma abordagem diferente. Após a inscrição, você passará por uma qualificação inicial e, sendo aprovado, você **ficará em destaque frente aos recrutadores de mais de 8 empresas do Grupo Movile, dentre elas iFood, Sympla, Rapiddo, PlayKids, MapLink e Wavy.**

**RESPONSABILIDADES E ATRIBUIÇÕES**
- Desenvolvimento de aplicações Frontend;
- Elaboração de arquiteturas de sistemas e evolução de plataformas atuais;
- Responsável por desenhar especificações técnicas e documentação;
- Monitorar a evolução dos produtos no mercado;
- Consultas de banco de dados e correções de bugs;
- Implementação de novos recursos nas plataformas.

[[Vídeo] Entrevista do nosso CTO](https://youtu.be/DNfLpKNoN7c)
[[Vídeo] Tech Case de como construímos o ChatClub](https://www.youtube.com/watch?v=bOepGMUR1-E)

## Local

Presencial. 
Local do escritório dependerá da empresa, mas estamos presentes em São Paulo, Campinas e Belo Horizonte.

## Benefícios

- Plano de saúde
- Seguro de vida
- VR compatível com o local do escritório
- VT
- Férias
- Possibilidade de home office
- Investimento em capacitação
- E outros diversos que são específicos de algumas empresa do Grupo (ex: GymPass, Plano odontológico, vale cultura)

#### Diferenciais

- Horário flexível
- Ambiente amigável e descontraído
- Times talentosos
- Produtos e tecnologia de ponta
- Espaço para inovação e tentativas
- Oportunidade para desenvolvimento e crescimento profissional
- Snacks liberados no escritório
- Cerveja sempre à disposição
- Muito café (máquina e coador)

## Requisitos

**Obrigatórios:**
- No mínimo 4 anos de experiência profissional;
- Experiência prática em frontend, utilizando HTML5, JavaScript (ES6/ECMAScript 6) e CSS;
- Conhecimentos de frameworks como: Angular, React, Vue e Polymer;
- Experiência com Banco de dados relacionais e não-relacionais (ex: PostgreSQL, Cassandra, MongoDB);

**Desejáveis:**

- Conhecimentos em desenvolvimento frontend utilizando Ruby on Rails;
- Conhecimento em Elixir e/ou linguagens funcionais;

**Diferenciais:**
- Implementação constante de novas linguagens e tecnologia
- Produtos novos surgem sempre
- Desafios presentes no dia a dia da empresa
- Tecnologia está presente em nossos objetivos

## Contratação

CLT

## Nossa empresa
A Movile é líder em marketplaces móveis, e tem como grande sonho tornar a vida de 1 bilhão de pessoas melhor através de seus aplicativos. Atualmente trabalhamos com negócios e empresas em 4 pilares, que são: Food (iFood), Tickets (Sympla), Education & Care (PlayKids, SuperPlayer e Wavy) e Rapiddo (Marketplace, Payments e Entregas). Já estamos presentes no Brasil, Estados Unidos, França, México, Colômbia, Peru e Argentina, e somamos mais de 100 milhões de usuários ativos mensalmente. Com 1600 funcionários apaixonados pelo mesmo sonho, empoderados a construir novos negócios com potencial global e motivados a tomarem riscos.

A tecnologia é o nosso core, estamos formando times que criem e desenvolvam produtos incríveis para impactar e melhorar diretamente a vida das pessoas. Nossa stack é totalmente diversificada, contamos com tecnologias e linguagens diversas para termos a liberdade de sempre aplicar o que fizer mais sentido para determinado projetos. Gostamos de inovar, de aplicar ideias diferenciadas, de mudar produtos e de criar coisas realmente grandes e escaláveis.

## Como se candidatar

Basta [clicar aqui](https://movile.gupy.io/jobs/5389) e preencher a inscrição.

## Labels
- Alocado
- CLT
- Pleno
- Sênior
- Presencial

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
