### ISSUE TITLE
[Remote] React Developer at GC Labs.

### ISSUE THREAD

**Issue by CodeBeater** [frontendbr/vagas#8183]
## Nossa empresa

Empresa Australiana 100% remota trabalhando em ferramentas para o mercado financeiro e inteligência artificial.

## Descrição da vaga

Procuramos um desenvolvedor entre pleno e senior para atuar no front-end de toda a gama de produtos, cuja stack atual é React (Typescript), com Vite.

## Local

100% remoto.

## Requisitos

**Obrigatórios:**
- 2 anos de experieriência com desenvolvimento React
- boa interpretação de Inglês escrito

**Desejáveis:**
- conhecimentos em Vercel
- conhecimentos em Pipelines CI/CD (AWS/GitHub)
- fluência em Inglês
- disponibilidade para trabalhar no horário comercial de Sydney

**Diferenciais:**
- conhecimentos em conteinerização via Docker
- boa capacidade para web design é um **grande** diferencial 

## Benefícios

- trabalho totalmente remoto
- se desejar, trabalhe de Domingo a Quinta

## Contratação

PJ. Salário mensal na faixa de U$ 2000 mensais, mas totalmente negociável.

## Como se candidatar

Por favor envie um email para raphael.antonio.oliveira@gmail.com com seu CV anexado - enviar no assunto: Vaga React

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by Dirosaki** [comment]
Currículo enviado!!!

**Comment by jmgrd98** [comment]
Enviado!
