### ISSUE TITLE
[Remoto] Desenvolvedor(a) Front-end Vue.js 💻✨ - 

### ISSUE THREAD

**Issue by ecossistemadev** [frontendbr/vagas#8193]
## Descrição da vaga

Estamos buscando um(a) Desenvolvedor(a) Front-end Vue.js talentoso(a) e apaixonado(a) para se juntar ao nosso time! 🚀

Se você é apaixonado(a) por criar interfaces incríveis e experiências digitais excepcionais, essa oportunidade é para você! 🤩

## Local

Remoto

## Requisitos

**Obrigatórios:**

- Experiência com desenvolvimento Front-end utilizando Vue.js, Vuex e Nuxt.js
- Conhecimento em integração com APIs Restful
- Familiaridade com o ecossistema JavaScript
- Experiência com metodologias ágeis (Scrum, Kanban)
- Capacidade de realizar testes unitários e de integração
- Formação Superior em Ciências da Computação, Engenharia da Computação, Sistemas de Informação ou áreas afins

**Desejáveis:**

- Conhecimento em infraestrutura na nuvem (AWS)
- Familiaridade com ferramentas de segurança e gestão de identidades (Keycloak)
- Experiência com desenvolvimento de aplicações com dados espaciais e geometrias (GIS)
- Conhecimento em Java e Spring Boot

**Atividades e responsabilidade:**

Você será responsável por:

- Desenvolver interfaces utilizando Vue.js, Vuex e Nuxt.js
- Integrar com APIs RESTful
- Trabalhar com metodologias ágeis
- Escrever código limpo, testável e de fácil manutenção
- Garantir a qualidade do código através de testes unitários e de integração

**Mais Informações:**

Inicio imediato após aprovação. 🚀

## Benefícios

🏠 Home Office

## Contratação

pj

## Como se candidatar

# [🔗 Clique aqui para se candidatar](https://empregos.dev/vaga/desenvolvedora-front-end-vuejs-3630)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 60 dias após cada processo.
E-mail para contato em caso de não haver resposta: 

#### Regime

pj

#### Nível

pleno

**Comment by mbalves1** [comment]
Bom dia!
Vaga inativada

**Comment by yurikomuta** [comment]
@mbalves1 não seria melhor fechar nesse caso, se reativar, ai reabre ?

**Comment by mbalves1** [comment]
@yurikomuta concordo também
