### ISSUE TITLE
[São Paulo] Estágio Full Stack (Nodejs / Angular)

### ISSUE THREAD

**Issue by alanleite** [frontendbr/vagas#82]
## Descrição da vaga

Irá aprender e participar do desenvolvimento de sistemas de diversas áreas de atuação, utilizando principalmente tecnologias como: Nodejs, Angular, JS, CSS, HTML, Docker, Microservices, Rest, Hapi, Sequelize, Mongoose, React etc...

## Local

- Alocado
- Vila Mariana - São Paulo, SP

## Benefícios

- Vale Refeição
- Vale Transporte
- Expediente de 6 horas diárias (segunda ~ sexta)

## Requisitos

**Obrigatórios:**

- Primeiro ou segundo ano da faculdade
- Não há requisitos de conhecimento, apenas desejamos que o profissional tenha a paixão de aprender e o objetivo de ser um excelente desenvolvedor.

**Diferenciais:**
- Inglês
- Javascript
- Nodejs
- Angular
- Git
- Docker
- Linux
- Conceitos básicos em Rest API e SPA.  

## Contratação

- Estágio
- Auxílio: R$ 1.100,00

## Nossa empresa

http://www.interativaengenharia.com.br/

## Como se candidatar

Por favor envie um e-mail para alan@interativaengenharia.com.br com seu CV anexado - enviar no assunto: Vaga NodeJS

**Comment by brunopulis** [comment]
Poxa parabéns, ai tá uma vaga de estágio super interessante! :)

**Comment by marciogurka** [comment]
Mandei E-mail! :)

**Comment by brunooomelo** [comment]
Enviei meu CV.

**Comment by Carlosxell** [comment]
Uma vaga super bacana, queria estudar ainda só pra concorrer no processo seletivo ....rsrs

**Comment by eduardojmatos** [comment]
@alanleite já preencheu a vaga? Nos avise pra mantermos ou removermos da lista :)

**Comment by alanleite** [comment]
@eduardojmatos ja preenchemos está sim, e abriremos outra essa semana! Obrigado por avisar, vou fechar esta daqui.

**Comment by eduardojmatos** [comment]
@alanleite show de bola!! :)

**Comment by camilatigre** [comment]
@alanleite 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by devBrunoLins** [comment]
Ótima Vaga! Enviando CV.

**Comment by alanleite** [comment]
@camilatigre 
opção (b)
