### ISSUE TITLE
[São Paulo] Front-end na [Udacity]

### ISSUE THREAD

**Issue by ottonascarella** [frontendbr/vagas#820]
<img src="https://d20vrrgs8k4bvw.cloudfront.net/images/open-graph/udacity.png" alt="Udacity Logo" />

## Descrição da vaga

A Udacity é uma plataforma de ensino online cuja maior missão é a democratização do conhecimento.

Venha fazer parte do nosso time internacional de desenvolvedores! (Mountain View, São Paulo, Berlin, Cairo, Mumbai, Xangai, and counting)  😉

Não conhece a gente? => https://br.udacity.com

**Responsabilidades:**
- Criar e lançar interfaces para nossos estudantes
-  Desenvolver as bibliotecas que dão base ao nosso _front-end stack_
- Trabalhar em conjunto com nosso time internacional de desenvolvedores, marketing e design para melhorar nossos produtos e experiencias
- Ter iniciativa para realizar projetos desde sua concepção até o _deploy_

## Local

Escritório, São Paulo - Vila Olímpia

## Benefícios

- Plano de saúde e dental
- Seguro de vida
- VR de R$880
- Salário bastante competitivo

## Diferenciais
- horário flexível 🕚
- macbook pro 💻
- temos uma máquina de Nespresso ☕️
- podemos cursar os [Nanodegrees](https://br.udacity.com/nanodegree) de graça!
- Acesso a descontos na Gympass

## Requisitos

**Obrigatórios:**
- **Absolutamente necessário** Inglês avançado (escrito e falado)
- 3 anos de experiência de desenvolvimento de software
- **Profundo conhecimento** de HTML, CSS, e _vanilla_ Javascript.
- Paixão por trabalho em equipe

**Desejáveis mas não obrigatórios:**
- TypeScript
- Angular 5
- React
- SASS e Bourbon

## Contratação

CLT

## Como se candidatar

https://boards.greenhouse.io/udacity/jobs/4002072002#.Wox0lRPwaAw

## Labels

- CLT
- Júnior
- Pleno
- Sênior
- Presencial

**Comment by camillodev** [comment]
Apliquei para a vaga ontem. Cruzando os dedos.

**Comment by pedroSoaresll** [comment]
Vou melhorar meu inglês só para poder trabalhar na Udacity e adquirir ainda mais conhecimentos <3

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
