### ISSUE TITLE
[REMOTO] Front-end React Native

### ISSUE THREAD

**Issue by faustoct** [frontendbr/vagas#821]
## Descrição da vaga

Temos 3 tasks para finalizar em 2dias e pagaremos hora fechada.

**Responsabilidades**
- Configuração de splash.
- Implementar progress bar.
- Follow user / assunto

## Local

Remoto

## Benefícios
- R$350,00 por 2 dias

## Requisitos

**Obrigatórios:**
- React native
- Expo
- Javascript

## Contratação

Freela

## Labels
email: hello@vibyapp.com

## Labels
- Freela
- Remoto - Total
- Sênior

**Comment by nicholasess** [comment]
@faustoct qual o email de contato?

**Comment by jilvanx** [comment]
Qual o contato @faustoct ?

**Comment by faustoct** [comment]
@nicholasess @jilvanx @DEXTERNATAN add email de contato
email: hello@vibyapp.com
