### ISSUE TITLE
[São Paulo+Remoto] Front-end AngularJs 

### ISSUE THREAD

**Issue by phixies** [frontendbr/vagas#822]
Vaga para frontend em startup focada em Cryptocurrence & Marketplace
Venha nos ajudar a construir o futuro em uma startup de nível global. A Bitshopp está prestes a mudar a maneira como as pessoas negociam produtos online.
Fomos uma das 5 startups selecionadas para o programa de internacionalização de Startups de uma das maiores aceleradoras do país em parceria com a maior aceleradora do Texas.
Precisamos agora encontrar um front para nos ajudar a concluir nosso MVP.

Local
Escritório, São Paulo - Consolação

Benefícios
Participação % (co-founder)
Plano de saúde e dental
VR
horário flexível
Trabalho remoto

Requisitos
Obrigatórios:

Disponibilidade para reuniões presenciais semanais
Inglês em nívelintermediário (falado e escrito)
3 anos de experiência de desenvolvimento de software
Profundo conhecimento de HTML, CSS (sass less), e JS.
Domínio de AngularJs
Paixão por trabalho em equipe

Desejáveis mas não obrigatórios:
Angular 5
TypeScript
React
SASS
Manjar de cryptomoedas e blockchain

Contratação
Participação como socio / cofounder

Como se candidatar
enviar email para admin@bitshopp.com

Labels
CLT
Júnior
Pleno
Sênior
Presencial

**Comment by caiquevallim** [comment]
Enviado!

**Comment by vinculuzX** [comment]
enviado!

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
