### ISSUE TITLE
[Belo Horizonte] Front-End Developer na MMSI

### ISSUE THREAD

**Issue by fellipecouto96** [frontendbr/vagas#823]
## Descrição da vaga

The Systems Architecture team collaborates with Application and Hardware Teams, supporting and evolving the platform that is base for all our products. Our team's main challenge is to produce high performance and robust software components to handle a very demanding 24/7 mine environment, as well as to research and develop Mobile HW Platforms, such as IoT-like devices and mobile computers. Our team focus on integrating solutions that are aligned with industry trends such as lambda architectures and modern data storage & processing technologies.

As a Web Developer in the Systems Architecture team, you will be responsible for the following tasks:

- Implement pixel-perfect concepts and designs in HTML, CSS and other design languages;
- Implement and test client-side logic in JavaScript/TypeScript for complex UI's such as multi-layer maps and diagrams;
- Troubleshoot and fix logic, communication, performance and other nonfunctional problems related to browser-server interaction;
- Collaborate with UX Architects using design definition tools such as Zeplin;
- Collaborate with Software Architects and Senior Software Engineers to produce high quality, testable and efficient code, according to industry standards;
- Understand Modular applications domain and proactively interact with product teams to improve functional and nonfunctional aspects of User Interfaces;
- Research, evaluate and select 3rd party Web frameworks, libraries and technologies;
- Provide technical oversight to development teams and contractors in subject area;
- Collaborate with the Documentation team providing basic documentation about the products being developed;

## Local

Escritório, Belo Horizonte - Minas Gerais

## Requisitos

**Obrigatórios:**
- BSc in Computer Science or equivalent;
- 3+ years of proven experience in Web Development;
- Proficiency and proven experience with HTML, CSS and other common design languages;
- Proficiency in HTML5 and responsive mobile-first web applications;
- Proficiency and proven experience with JavaScript and/or TypeScript;
- Experience with JavaScript Web UI frameworks, such as Angular, React, Vue, etc.;
- Demonstrated problem-solving ability and an attention to detail;
- Fluent English for verbal and written collaboration with international teams.

**Desejáveis:**

- Experience with GIS Frameworks, such as ThinkGeo, MapBox, etc.;
- Experience implementing and maintaning Selenium (or similar) test cases;
- Experience designing and implementing Android, iOS or Qt front-end applications;
- Knowledge of one or more modern object oriented programming languages (Java, C#, etc.) ;
- Knowledge on computer networking and the TCP/IP stack;
- Familiarity with at least one of the cloud providers, such as Azure, AWS, Google Cloud, etc.;
- Strong Communication Skills

## Contratação

CLT

## Nossa empresa

Modular revolutionized the mining industry with the first DISPATCH Fleet Management system more than 30 years ago. Today, with more than 700 employees and 10 offices worldwide, we offer the most complete lineup of mine management solutions on the market.

## Como se candidatar

Acessar: https://app.vulpi.com.br/modular-mining-systems-do-brasil-ltda/585

## Labels

- Alocado
- CLT
- Pleno
- Sênior

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
