### ISSUE TITLE
[Ribeirão Preto] Desenvolvedor Front-End na iClinic

### ISSUE THREAD

**Issue by danielangelo98** [frontendbr/vagas#824]
## Descrição da vaga

Como um desenvolvedor Front-end Pleno, você tem que manter o equilíbrio entre criatividade e produtividade em projetos inovadores.

## Local

Necessário residir em Ribeirão Preto
## Benefícios

-Plano de saúde
-Vale alimentação
-Ambiente jovem, descontraído, escritório confortável, videogame, puffs para descanso
-Sem dress code. Trabalhe de calça, bermuda, chinelo, pantufa ou de qualquer outro jeito que achar confortável
-Flexibilidade de horário
-O sagrado cafezinho, além de capuccino, mocaccino, chocolate quente e chás, todos FREE
-Rango open: café da manhã, frutas ao longo do dia e copa para refeições
-Relacionamento próximo aos fundadores e diretores da empresa
-Possibilidade de rápido crescimento na carreira

## Requisitos

**Obrigatórios:**
-Pelo menos 3 anos de experiência em JavaScript
-Saber fazer manipulação do DOM sem jQuery
-Conhecer as APIs dos objetos JavaScript: Object, String, Number, Array, Regex, etc...
-Saber o básico das principais APIs do HTML5
-Conhecimento das principais features do ES6
-Orientação a Objetos, Design Patterns e boas práticas
-Ter tido contato com React, Flux e Redux (e seu ecossistema)
-HTML5 e semântica das tags
-CSS3 e conhecimentos de algum pré-processador (usamos Sass)
-Task Runners (Grunt, Gulp e NPM Scripts)
-Alguma experiência com Webpack ou similares

**Diferenciais:**
-Trabalhar com testes em JavaScript (Enzyme, Jest)
-Conhecimentos básicos de NodeJS
-Conhecimentos de Programação Funcional
-TDD, Docker e CI
-Metodologias ágeis

## Contratação

CLT 
Faixa salarial: R$5000.00 - R$6000.00

## Nossa empresa

A iClinic é uma das startups de tecnologia em saúde que mais crescem no país.
 
 Nossa missão é Descomplicar a Saúde no Brasil levando mais gestão a clínicas e consultórios através da tecnologia e, com isso, possibilitar que médicos e outros profissionais promovam mais saúde aos seus pacientes.
 
 Queremos ser a melhor e mais inovadora empresa de tecnologia em saúde, revolucionando a gestão de clínicas e consultórios médicos, aprimorando a maneira que lidam com suas informações e atendem seus pacientes.

## Como se candidatar

https://app.vulpi.com.br/iclinic/573?invited_by=9433

## Labels

- Alocado
- CLT
- Pleno
- Sênior

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
