### ISSUE TITLE
[São Paulo] Front-End Developer na Cargobr

### ISSUE THREAD

**Issue by viniciusdiaz** [frontendbr/vagas#826]
## Descrição da vaga

A Cargobr busca Desenvolvedor Front-end (Pleno). É necessário um expert em HTML, CSS e Javascript (Vanilla), para transformar layouts em experiências incríveis.

## Local
Av: Paulista - São Paulo

## Benefícios

- Vale transporte;
- Vale refeição;
- Plano de saúde parcialmente custeado.

## Requisitos

**Obrigatórios:**
- HTML5;
- CSS3;
- Javascript - (React, Webpack e Node);
- Bootstrap 4;
- Entender os conceitos de User Experience (UX);
- Boas práticas de SEO;
- Programação fiel ao layout e semanticamente correta;
- Ótimo conhecimento em pré processadores (SAS - LESS);
- Conhecimento em Git
- Google analytics (integração técnica e configuração de reports)
- Doubleclick for publishers (integração técnica e configuração de ADspaces)
- Google Tag Manager (integração técnica e configuração de tags, eventos e variáveis)
- Experiência em processos ágeis (Scrum)

**Desejáveis:**
- Conhecer o framework Django;

## Contratação
CLT

## Nossa empresa

Somos uma startup pioneira em cotação e contratação de frete online no Brasil! Nossa grande paixão é tecnologia e nossa vocação é unir embarcadores com transportadoras, desburocratizar o processo e facilitando a comunicação entre eles. Nós vamos digitalizar todo o processo logístico! Sabemos disso porque acordamos e vamos dormir pensando em como vamos melhorar a vida dos nossos parceiros, não por obrigação, mas porque realmente gostamos disso. Aliás, fazemos sempre o que gostamos, afinal, a coisa mais importante é ser feliz e acreditamos que ninguém é feliz fazendo algo que não gosta.

## Como se candidatar

Por favor envie um email para vinicius.diaz@cargobr.com seu CV anexado - enviar no assunto: Vaga FRONT-END

## Labels

- Alocado
- CLT
- PJ
- Pleno

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
