### ISSUE TITLE
[São Paulo] React Native Developer na UseBike

### ISSUE THREAD

**Issue by mstrcnvs** [frontendbr/vagas#827]
## Descrição da vaga

Desenvolvimento de aplicativo utilizando React Native.

## Local

Escritório em São Paulo - Jardim América

## Benefícios

- Horário flexível e negociável

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com JavaScript/ECMAScript 6
- 1 ano de experiência com React Native
- Conhecimento em comunicação com REST APIs
- PJ/MEI

**Desejáveis:**
- GIT
- Desenvolvimento iOS

**Diferenciais:**
- Python
- HTML5/CSS3
- Animações SVG

## Contratação

PJ/MEI

## Nossa empresa

UseBike é o aplicativo do ciclista urbano. Incentivamos pessoas a adotarem a bicicleta como meio de transporte, sempre indicando rotas seguras para bike através de ciclovias e ruas adequadas para ciclista. Queremos promover a interação entre ciclista e cidade, transformando estabelecimentos em locais bike friendly e trazendo a experiência de vivenciar o que a bicicleta tem de melhor dentro dos centros urbanos. São 26 mil pontos bike-friendly nas maiores capitais e mais de 1500 rotas traçadas diariamente.

[Saiba mais no nosso site](http://usebikeapp.com)

## Como se candidatar

Por favor envie um email para contact@usebikeapp.com com seu portfólio anexado.
Enviar no assunto: Vaga React Native

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
