### ISSUE TITLE
[São Paulo] Full-stack Engineer (NodeJS, ReactJS) na Liv Up

### ISSUE THREAD

**Issue by rstraat** [frontendbr/vagas#828]
## Descrição da vaga

Fala pessoal!

Estamos com vagas para devs Node.js na Liv Up, uma food tech de alimentação saudável que tá tirando a complexidade de comer bem no dia a dia.

A gente tem crescido exponencialmente (+20% ao mês!) nos últimos dois anos e parte fundamental da nossa estratégia é ter um time forte de tecnologia, responsável por otimizar a experiência do usuário em nosso site e desenvolver sistemas com tecnologia de ponta visando automatizar e acelerar todos os processos da empresa, desde a produção até a logística e envio dos produtos (é um baita desafio crescer dessa forma tendo toda uma cadeia produtiva por trás!).

Para isso buscamos pessoas que tenham muita iniciativa e aprendam rápido para se desenvolver junto com a gente. Aqui você vai ter muita voz e responsabilidade logo de cara! Nossos desafios crescem no ritmo do nosso crescimento e isso faz com que a gente seja um time muito unido e cooperativo, sempre aprendendo e crescendo em conjunto! Ah, e nosso ambiente de trabalho é bem informal e descontraído =)

## Local

Escritório a duas quadras do metrô Faria Lima em São Paulo

## Benefícios

- Vale-Transporte
- Vale-Refeição
- Comida à vontade

#### Diferenciais

- Crescimento pessoal rápido (responsabilidade + livros + cursos + troca de conhecimentos)
- Ambiente descontraído e informal
- Perto do metrô
- Eventos e happy hours
- Flexibilidade de horário

## Requisitos

Ter trabalhado com Node.js, MongoDB ou React.js é um diferencial, mas não requisito.

## Contratação

CLT

## Como se candidatar

Para mais detalhes e aplicar para a vaga, basta entrar em https://stowhire.com/liv-up

## Labels

- Alocado
- CLT
- Pleno

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
