### ISSUE TITLE
[São Paulo/SP] Frontend Developer na 18digital

### ISSUE THREAD

**Issue by samir-jorge-araujo** [frontendbr/vagas#829]
## Descrição da vaga

Estamos buscando Front-end Developer Sênior para integrar nossa equipe. 
Ambiente agradável com equipe completa para trabalhar, e horário flexível.

Metodologia ágil levada a sério, com mensuração feita junto com os profissionais que irão executar o trabalho. O candidato precisa estar atento as novas tecnologias e em constante evolução.

## Local

Escritório na Rua Itambé, 341 - Higienópolis

## Benefícios

- Férias remuneradas
- Política de cursos
- Bônus por performance/produtividade

#### Diferenciais

- Monte a sua máquina como desejar
- Cerveja liberada na sexta-feira

## Requisitos

**Obrigatórios:**
- Experiência significativa com desenvolvimento web
- Proficiência em webpack
- Conhecimento em design patterns para css
- Saber usar sistema de controle de versões (git)
- Conhecimento em photoshop / sketch (básico - corte de imagens)
- Proficiência em pré-processadores css (sass / stylus / less)
- Se sentir confortável com a linha de comando
- Integração com apis rest (redes sociais, etc.)
- Essencial ter código limpo, organizado, reutilizável e testável

**Desejáveis:**
- Desenvolvimento mobile (híbrido)
- Angularjs / react / vuejs
- Conhecimento de metodologias ágeis

## Contratação

PJ a combinar

## Nossa empresa

Conectamos a realidade dos negócios com a melhor experiência digital para todos, da maneira mais orgânica possível.
Nenhum projeto é igual e cada desenvolvimento da 18digital tem sua própria assinatura. Com a sua ideia ou desafio vamos mergulhar, planejar e executar com o espirito de quem respira e se realiza no ambiente virtual e não consegue deixar de lado uma boa história!

## Como se candidatar

Por favor envie um email para trampo@18digital.com.br com seu CV anexado - enviar no assunto: Vaga Frontend Developer

## Labels

- Alocado
- PJ
- Pleno/Sênior

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
