### ISSUE TITLE
[São Paulo] Desenvolvedor .NET Sênior - Viajanet

### ISSUE THREAD

**Issue by victorgsouto** [frontendbr/vagas#83]
## Descrição da vaga
Nosso time está crescendo e estamos buscando um desenvolvedor  .NET Sênior.

## Local
Alocado, São Caetano do Sul- SP 

## Benefícios
- Horário Flexível

## Requisitos

**Obrigatórios:**
- Visual Studio 2013/2015
- C#
- ASP.Net MVC
- Banco de dados relacional (SQL Server)
- Domínio em arquitetura de APIs RESTFul;
- JavaScript (AngularJS)
- Experiência com Controle de Versão 
- Utilizar padrões e boas práticas para desenvolvimento
- Experiência mínima de 4 anos com desenvolvimento em C# em plataforma Web.

**Desejáveis:**
- AngularJS 2.0 ou ReactJS
- Node.JS
- Bancos NoSql (Couchbase, MongoDB)
- Cache (Redis)

## Contratação
PJ

## Como se candidatar

Por favor envie um e-mail para vqsouto@viajanet.com.br com seu CV anexado - enviar no assunto: Desenvolvedor .NET Sênior

**Comment by willianjusten** [comment]
Opa anotei aqui as labels, boa sorte =D

**Comment by victorgsouto** [comment]
@willianjusten só muda por favor de CLT para PJ?

**Comment by willianjusten** [comment]
Opa, perdão.

**Comment by camilatigre** [comment]
@victorgsouto 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by meugamer** [comment]
Olá eu gostaria de ter acesso ao api para implementar em um site que estou criando. Não consegui email nem o contato de telefone.
