### ISSUE TITLE
[Salvador] [Alocado] Fullstack Developer no Senai CIMATEC

### ISSUE THREAD

**Issue by thiagoleitedev** [frontendbr/vagas#830]
## Descrição da vaga

Developer com experiência com WordPress e conhecimento de Front end para atuação no Portal Cimatec (www.senaicimatec.com.br)

## Local

Salvador - Av. Orlando Gomes, 1845 - Piatã

## Requisitos

**Obrigatórios:**
- Conhecimentos em PHP
- Experiência com Wordpress (Advanced Custom Fields, Internacionalização..)
- Experiência com Javascript ES6/7
- Alguma vivência com React/Vuejs, Webpack
- Experiência com CSS3 e pre-processadores
- Alguma vivência com Linux

**Desejáveis:**
- Desenvolvimento mobile (React Native/Xamarim...)
- UX

**Diferenciais:**
- projetos opensource

## Contratação

A combinar

## Como se candidatar

Por favor envie um email para thiago.nascimento@fieb.org.br com seu CV anexado - enviar no assunto: Vaga Fullstack

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
