### ISSUE TITLE
[São Paulo/SP] Dev. Front-end Junior/Pleno no SuperAgendador

### ISSUE THREAD

**Issue by jbaladao** [frontendbr/vagas#831]
#  Descrição da vaga

A startup SuperAgendador.com é um SaaS para prestadores de serviços. Procuramos um profissional com pelo menos 1 ano de experiência com Angular, qualquer versão!

## Local

Próximo ao metro Jabaquara, São Paulo - SP

## Benefícios

- VR
- café da manhã, bebidas no frigobar
- PS4 liberado com vários jogos para descontrair

## Obrigatórios:

1 ano de experiência com Angular, qualquer versão!
2 anos de experiência com programação JavaScript.
Conhecimentos avançados em HTML e CSS.

## Desejáveis:

ter trabalhado em alguma startup
ter trabalhado com algum sistema online no modelo SaaS
alguma experiência com aplicativos mobile
alguma experiência com metodologias ágeis de desenvolvimento

## Contratação

PJ a combinar

# Nossa empresa

O SuperAgendador.com é um dos maiores sistemas de gestão para Prestadores de Serviços do Brasil, nossos clientes movimentaram juntos aproximadamente 25 milhões de reais em dezembro de 2016. A empresa já foi acelerada em 2016 no evento InvestorsDay da CampusParty (anjos via Broota) e agora em 2017 recebeu um novo investimento do grupo Bossa Nova (pré-seed).
Estamos naquela fase incrível onde uma pequena startup pode evoluir rapidamente para uma empresa de grande porte. Este é o nosso sonho, se quiser participar dele venha trabalhar conosco. Vivenciar o nascimento e transformação de uma Startup é incrível e as oportunidades de crescimento e aprendizado são muitas!

# Como se candidatar

Por favor envie um email para jbaladao@superagendador.com com seu CV anexado - enviar no assunto: "Vaga Dev Front-end"

# Outras vagas

Também estamos procurando por um Dev. NodeJS. Toda indicação será super bem vinda...

Muito obrigado!

**Comment by clluiz** [comment]
É alocado ou pode ser remoto?

**Comment by Finacio** [comment]
DevNodeJS, pode ser junior?

**Comment by jbaladao** [comment]
Alocado. E podemos avaliar profissional Node sim, para backend, vaga diferente.

**Comment by renanlara** [comment]
CARACAS, Jabaquara ficaria perto pra mim! Mas ainda estou me aprofundando em JS. :(

**Comment by Finacio** [comment]
@jbaladao posso colocar no titulo do e-mail como dev nodejs?

**Comment by jbaladao** [comment]
Temos oportunidade para Estagiário ou Júnior Renan, não deixe de enviar seu currículo!

**Comment by renanlara** [comment]
Legal, bom saber @jbaladao, obrigado!

**Comment by jbaladao** [comment]
As duas vagas de Dev. Front-end Junior já foram preenchidas.
