### ISSUE TITLE
[Belo Horizonte] Desenvolvedor front-end na lett insights

### ISSUE THREAD

**Issue by danielangelo98** [frontendbr/vagas#833]
## Descrição da vaga

Estamos buscando uma mente criativa para fazer parte do time de desenvolvimento front-end da Lett. Precisamos de alguém que tenha experiência no desenvolvimento de sistemas WEB e que goste de usar sempre as tecnologias mais recentes.
Buscamos alguém que, além de qualificado tecnicamente, se encaixe na cultura da empresa, ajudando a construir um ambiente de trabalho leve e informal.
## Local

Belo Horizonte

## Requisitos

**Obrigatórios:**
- Javascript (avançado)

- HTML5

- CSS3

**Desejáveis:**
- Backbone.js

- SASS

- LESS

- Bower

- Grunt

- Node.js (diferencial)

## Contratação

CLT
## Nossa empresa

A Lett ajuda marcas e e-commerces a criar uma experiência de compra que atrai, inspira e retêm consumidores. Através de um dashboard, oferecemos um monitoramento em tempo real da performance dos fornecedores online. Além disso, atuamos como um hub entre os fornecedores e as lojas online, facilitando e automatizando a correção dos problemas encontrados. Tudo isso é obtido através de algoritmos de inteligência artificial, estatística e analytics. Somos uma startup sólida e em crescimento exponencial. Estamos em 3 cidades: Belo Horizonte, onde participamos do SEED (programa de aceleração do governo), São Paulo, onde fica nosso time comercial e Santiago, onde somos participantes da atual rodada de aceleração do Startup Chile. Nosso time é jovem, empolgado e muito animado!
## Como se candidatar
https://app.vulpi.com.br/lett-insights/522

## Labels

- Alocado
- CLT
- Pleno

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
