### ISSUE TITLE
[Curitiba e Região] Estágio Front-End na LojasKD

### ISSUE THREAD

**Issue by marcelabomfim** [frontendbr/vagas#834]
## Descrição da vaga

Ajudar o time com o desenvolvimento e manutenção de nosso e-commerce bem como outras aplicações que envolvem front end.

## Requisitos

**Obrigatórios:**
- Conhecimento prático de HTML5 e CSS3;
- Conhecimento de Javascript;
- Conhecimento básico de PHP;
- Experiência com controle de versão Git;

**Desejáveis:**
- Design Responsivo e Cross Browser;
- Familiaridade com NPM / Yarn;
- Pré-processadores(SASS) e Task Runners(Gulp);
- Conhecimento para consumo de API's;

**Diferenciais:**
- Se preocupar com segurança e performance;
- Noções de Testes A/B;
- Noções de UX e SEO;

## Contratação

Estágio

## Benefícios

- Vale Refeição
- Vale Transporte/Combustível

## Local

Presencial, Pinhais - Região Metropolitana de Curitiba

## Nossa empresa

A LojasKD é um dos principais E-Commerces de móveis do país. Uma enorme variedade de produtos inspiradas para decorar cada momento da vida do cliente. Fundada em 1997, começou com lojas físicas, mas hoje está 100% online. Somos 150 profissionais apaixonados pelo que fazemos! Cada vez mais querendo se posicionar como uma empresa de tecnologia.

## Como se candidatar

Envie seu currículo para marcela.bomfim@lojaskd.com.br com o assunto: **Quero a vaga de Estágio Front-End na LojasKD**.

## Labels

- Alocado
- Estágio

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
