### ISSUE TITLE
[Rio de Janeiro] Front-End Developer na Avantare

### ISSUE THREAD

**Issue by RaphaAmericano** [frontendbr/vagas#835]
## Descrição da vaga

Você tem habilidades de desenvolvimento PHP e Wordpress, experiência em Java Script  e procura a oportunidade de crescer criando trabalhos relevantes? Seu lugar é na Avantare!

**ATIVIDADES:**
- Desenvolvimento de temas em Wordpress e PHP para sites e landing pages, HTML5, CSS/CSS 3, JavaScript / JQuery, utilizando boas práticas W3C e design responsivo, através do Bootstrap;
- Codificação JavaScript para tagueamento de sites e landing pages;
- Especificação de sites e validação de wireframes.

## Local

- (Centro | Rio de Janeiro)

## Requisitos

- Conhecimento em Wordpress, PHP, HTML5, CSS/CSS3, JavaScript / JQuery e Bootstrap;
- Experiência mínima de 2 anos na área;
- Perfil lógico e analítico;
- Inglês avançado para leitura.

**CARACTERÍSTICAS COMPORTAMENTAIS:** 
- Organização, comprometimento, proatividade e aprendizado constante.

**Desejáveis:**
- Conhecimento sobre SEO, Google Analytics ou Google Tag Manager.

## Como se candidatar

Gostou? Envie seu currículo, pretensão salarial e portfolio para recursoshumanos@avantare.com.br, com projetos que possam ser navegados.

**Comment by didiraja** [comment]
currículo enviado :)

**Comment by RaphaAmericano** [comment]
Obrigado aos interessados enviaram o currículo. 
A vaga foi preenchida.
