### ISSUE TITLE
[São Paulo] Front-End Developer Pleno na eokoe/AppCívico

### ISSUE THREAD

**Issue by robsonsobral** [frontendbr/vagas#836]
## Descrição da vaga

Procuramos front-end developer que programe bem, seja organizada, se importe com a legibilidade de seu código e com a colaboração de seus colegas e se expresse com clareza. Queremos alguém inquieta com seu próprio conhecimento não só para aprender, mas também para nos ensinar.

Não somos uma fábrica de software. Oferecemos o produto completo, desde o projeto. Aqui, quem desenvolve também colabora no processo criativo: discutindo, rabiscando, antecipando dificuldades e sugerindo soluções, **antes** de colocar o código no repositório. Trimestralmente, revisamos todos juntos o que a empresa melhorou e ainda pode melhorar no período seguinte.

Além de trabalhar nos produtos da [eokoe](https://www.eokoe.com/), você terá a oportunidade de atuar em projetos com impacto social positivo no [AppCívico](https://appcivico.com/).

## Local

(geralmente) no escritório, no bairro do Paraíso, em São Paulo

### Diferenciais

- no dress code;
- flexibilidade de horários e home office;
- ambiente aberto e acessível, em que todos somos iguais;
- boa localização: transporte público, restaurantes, serviços;
- clima e ambiente alegre e confortável;
- aprendizado pela convivência com profissionais seniores;
- empresa em crescimento com oportunidade de progressão de carreira;
- trabalho em projetos de impacto positivo.

### Obrigatórios

- CSS puro
- Javascript puro
- atenção à performance
- controle de versão
- inglês para leitura
- integração com APIs
- noção de segurança em navegadores
- _responsive web_

### Desejáveis

- automatização utilizando o NPM
- familiaridade com Linux ou MacOS
- Git
- inglês para conversação
- integração contínua

### Diferenciais

- **paz de espírito**
- compulsão por testes
- noções sobre acessibilidade
- saber o que é DNS, HTTP e TLS
- Static Site Generators
- VueJS
- (something) Native

## Contratação

PJ por valor a combinar e por prazo indeterminado

## Nossa empresa

Aqui na **eokoe** acreditamos que ótimos softwares saem das mentes de bons times, não apenas por ótimos desenvolvedores. Precisamos de um time variado. Queremos que você traga suas cores, formas e ideias para encontrarmos soluções inovadoras, de um jeito que não somos capazes sozinhos.

## Como se candidatar

Por favor envie um email para trampos(at)eokoe.com com seu CV anexado - enviar no assunto: Vaga Front-End

**Comment by ReactGirl** [comment]
no dress code é um diferencial?

**Comment by robsonsobral** [comment]
@ReactGirl , minha colega que ajudou a redigir esse texto acha que sim.

**Comment by robsonsobral** [comment]
@ReactGirl , vou melhorar isso. A empresa é legal. Melhor lugar em que muitos de nós trabalhou.

**Comment by laistomazz** [comment]
Passando para endossar o comentário do @robsonsobral sobre ser o melhor lugar que muitos de nós já trabalhou. Abril vai fazer um ano que estou aqui e tem sido uma experiência incrível!
Além de aprender muito, me sinto respeitada.

Venham! :)

**Comment by LFeh** [comment]
Bacana os elogios para a empresa ;)

**Comment by laistomazz** [comment]
Fala galera! A vaga esta aberta novamente! Só vem :D

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
