### ISSUE TITLE
[São Paulo/SP] Dev. Backend Node Pleno no SuperAgendador

### ISSUE THREAD

**Issue by jbaladao** [frontendbr/vagas#837]
#  Descrição da vaga

A startup SuperAgendador.com é um SaaS para prestadores de serviços. Procuramos um profissional com pelo menos 1 ano de experiência com Node.JS e MongoDB. Alguma experiência com PHP e MySQL também são desejados!

## Local

Próximo ao metro Jabaquara, São Paulo - SP

## Benefícios

- VR
- café da manhã, bebidas no frigobar
- PS4 liberado com vários jogos para descontrair

## Obrigatórios:

1 ano de experiência com NodeJS e MongoDB pelo menos!
2 anos de experiência com programação JavaScript.
mais de 1 ano de experiência com qualquer outra linguagem de programação back end.

## Desejáveis:

ter trabalhado em alguma startup
ter trabalhado com algum sistema online no modelo SaaS
alguma experiência com Cloud Computing
alguma experiência com metodologias ágeis de desenvolvimento

## Contratação

PJ ou CLT a combinar

# Nossa empresa

O SuperAgendador.com é um dos maiores sistemas de gestão para Prestadores de Serviços do Brasil, nossos clientes movimentaram juntos aproximadamente 25 milhões de reais em dezembro de 2016. A empresa já foi acelerada em 2016 no evento InvestorsDay da CampusParty (anjos via Broota) e agora em 2017 recebeu um novo investimento do grupo Bossa Nova (pré-seed).
Estamos naquela fase incrível onde uma pequena startup pode evoluir rapidamente para uma grande empresa. Este é o nosso sonho, se quiser participar dele venha trabalhar conosco. Vivenciar o nascimento e transformação de uma Startup é incrível e as oportunidades de crescimento e aprendizado são muitas!

# Como se candidatar

Por favor envie um email para jbaladao@superagendador.com com seu CV anexado - enviar no assunto: Vaga NodeJS/MongoDB

# Outras vagas

Também estamos procurando por um Front-end AngularJS. Toda indicação será super bem vinda...

Muito obrigado!

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
