### ISSUE TITLE
[São Paulo] Front-End Developer na MadGO

### ISSUE THREAD

**Issue by joelsantosbr** [frontendbr/vagas#838]
## Descrição da vaga

**Onde você está?** 
Você tem habilidade em desenvolvimento de sites do zero e em WordPress utilizando HTML5, CSS3, PHP (básico) e jQuery essa vaga é pra você! 
Se você gosta e quer trabalhar com essas tecnologias, vamos pra cima!

Quer sair na frente dos concorrentes? Ligue na empresa e peça para agendar sua entrevista.

## Local

Presencial, Av Paulista - Bela Vista

## Benefícios

- VR e VT

## Requisitos

**Obrigatórios:**

- PHP (Uso do wordpress)
- HTML
- CSS (design responsivo)
- JS/JQUERY
- Photoshop recortes
- Git
- Pelo menos 1 site de portfólio

**Desejáveis:**

- Organização e padronização de componentes web

**Diferenciais:**

- Gulp
- Stylus

## Contratação

PJ a combinar

## Nossa empresa

Uma agência focada em Design, Webdesign & Marketing Digital

## Como se candidatar

Preencher o formulário https://docs.google.com/forms/d/e/1FAIpQLSfsQ3uTScyW4pix5t0Jmq4PoZDWk800diYf5IVQTf_xaPMmvQ/viewform?usp=sf_link

## Labels

- Alocado
- PJ
- Júnior

**Comment by EdipoNascimento** [comment]
@joelsantosbr , tudo bem?
Tenho apenas um game em Javascript no momento. Posso fazer um teste?

**Comment by joelsantosbr** [comment]
@EdipoNascimento  Pode sim, me manda seu CV por e-mail.

Abs

**Comment by EdipoNascimento** [comment]
Vou enviar, mas serei eliminado. Só têm testes no meu CV. Isso sempre
acontece. :(

Em 26 de fev de 2018 13:16, "Joel Santos" <notifications@github.com>
escreveu:

**Comment by RuanPissinati** [comment]
Olá, vaga ainda disponível?

**Comment by joelsantosbr** [comment]
@RuanPissinati Sim

**Comment by RuanPissinati** [comment]
@joelsantosbr Ok, enviei o e-mail com meu currículo. :D

**Comment by devcastrojunin** [comment]
Segue indicação @joelsantosbr :-)
[lucas-nascimento.docx](https://github.com/frontendbr/vagas/files/1786706/lucas-nascimento.docx)

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
