### ISSUE TITLE
[Remoto] Front-End Developer na Agência Novi

### ISSUE THREAD

**Issue by eduardohprado** [frontendbr/vagas#839]
## Descrição da vaga

Trabalhará com projetos em React e React Native. 

## Local

São paulo - Remoto Total. 

## Benefícios

- Ajuda de custo para Home office 

#### Diferenciais

- Faça seu horário 
- Cursos

## Requisitos

**Obrigatórios:**
- Experiência com React + React native comprovada
- Organização 
- Comprometimento

**Desejáveis:**
- Conhecimento em outras plataformas para mobile. 

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para contato@agencianovi.com.br com seu CV anexado , **Pretensão salarial** e **Trabalhos feitos** - enviar no assunto: Vaga React 

## Labels

- PJ
- Pleno
- Remoto - Total

**Comment by PauloRobertoM** [comment]
Ótima empresa para se trabalhar remotamente! Recomendo muito!

**Comment by bonejah** [comment]
Cv enviado!

**Comment by HaluDeCassia** [comment]
Enviado :)

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
