### ISSUE TITLE
[São Paulo] Desenvolvedor Front-End Pleno - Viajanet

### ISSUE THREAD

**Issue by victorgsouto** [frontendbr/vagas#84]
## Descrição da vaga

Nosso time está crescendo e estamos buscando um desenvolvedor Front-End afim de encarar alguns desafios e vontade de aprender.

## Local

Alocado, São Caetano do Sul- SP 

## Benefícios

- Horário Flexível

## Requisitos

**Obrigatórios:**
- HTML
- CSS (LESS/SASS)
- JavaScript
- Utilizar padrões e boas práticas para desenvolvimento
- Experiência com Controle de Versão 

**Desejáveis:**
- Angular 1
- Automatizadores

**Diferenciais:**
- Angular 2.0 ou ReactJS
- conhecimentos em C#
- Perfil Dinâmico

## Contratação

PJ

## Como se candidatar

Por favor envie um email para vqsouto@viajanet.com.br com seu CV anexado - enviar no assunto: Desenvolvedor Front-End

**Comment by willianjusten** [comment]
Boa sorte =)

**Comment by victorgsouto** [comment]
@willianjusten só muda por favor de CLT para PJ? Valeuu =)

**Comment by Mendrone** [comment]
@victorgsouto a vaga ainda está aberta?

**Comment by gkal19** [comment]
Tem chances de remoto?

**Comment by victorgsouto** [comment]
@Mendrone fechamos hoje.

**Comment by camilatigre** [comment]
@victorgsouto 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
