### ISSUE TITLE
[São Paulo] Front-End Developer Junior/Pleno na Lab123

### ISSUE THREAD

**Issue by felipeds2** [frontendbr/vagas#840]
A Lab123 busca de um dev Front-end JR e PL. É necessário ter bons conhecimentos em HTML, CSS, Javascript e saber programar em Angular 2/4.

## Local
Av. Paulista - São Paulo

## Requisitos
- HTML5;
- CSS3;
- JavaScript (Angular 2/4)
- Bootstrap 3/4;
- Programação fiel ao layout e semanticamente correta;
- Conhecimento em Git
- Experiência em processos ágeis (Scrum)

## Diferenciais
- Entender os conceitos de User Experience (UX);

## Contratação
PJ

## Nossa empresa
A Lab é uma software house com 4 anos no mercado que nasceu com o intuito de construir soluções de qualidade e dar vida às ideias através da união das melhores práticas de mercado, agilidade e profissionais apaixonados pelo que fazem.

## Como se candidatar
Por favor envie um email para felipe.santos@lab123.com.br seu CV anexado e pretensão salarial - enviar no assunto: [Vaga FRONT-END] - 

## Labels
- Alocado
- PJ
- Pleno
- Junior

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
