### ISSUE TITLE
[São Paulo] Front-End Developer na [Lamego MKT Digital]

### ISSUE THREAD

**Issue by LamegoMKTDigital** [frontendbr/vagas#841]
## Descrição da vaga

A Lamego MKT Digital, abre seu Programa de Contratações de 2018, em busca de profissionais na área de programação e design, que conheçam PHP, Wordpress e servidores linux.

## Local

Remoto - Trabalhe diretamente de casa

#### Diferenciais

- Seja seu próprio chefe

## Requisitos

**Obrigatórios:**
- CNPJ

**Desejáveis:**
- conhecimentos PHP
- conhecimentos HTML 5 e CSS3
- conhecimentos Wordpress
- conhecimentos Woocommerce

**Diferenciais:**
- projetos todo o tempo

## Contratação

PJ - Prestação de Serviços

## Nossa empresa

Empresa de Marketing Digital, que atende o pequeno e médio empresário.

## Como se candidatar

Por favor acesse o link http://mktdigital.com.vc/contratacao/ e preencha os seus dados e as habilidades que você possui.

## Labels

- Freela
- Remoto - Total

**Comment by renanlara** [comment]
Enviado :)

**Comment by jamestwin** [comment]
Enviado!
=)


Grato.

*Robson César Matoso Hennes - (19) 99365 3983*
*Desenvolvedor Front End na **Unkas Design.*
*Especializado em Wordpress, HTML, CSS e PHP.*
*http://www.unkasdesign.com.br <http://www.unkasdesign.com.br>*


2018-02-27 9:43 GMT-03:00 Renan Lara <notifications@github.com>:

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
