### ISSUE TITLE
[Barueri] Front-End Developer na Ornito

### ISSUE THREAD

**Issue by dafny** [frontendbr/vagas#842]
## Descrição da vaga

Procuramos front end developer pra integrar nosso time que fica alocado dentro de cliente (Dasa). 

## Local

Presencial, Alphaville 

## Benefícios

- VR (17,50 ao dia) 
- AM (Bradesco Enfermaria com desconto fixo de 149,00 +Coparticipação) 
- AO (Bradesco com desconto fixo de 13.54 ao mês) 
- Seguro de vida 
- Auxílio Creche

## Requisitos

**Obrigatórios:**
- HTML5
- CSS3
- React
- Git
- Interação com APIs REST

**Desejáveis:**
- Vue js
- Angular
- Gulp
- OAuth2
- Conceitos de Responsividade

## Contratação

CLT Full

## Nossa empresa

Somos uma empresa de desenvolvimento de produtos digitais orientada a geração de resultados.

Impactar a vida das pessoas faz parte de nosso propósito de valor e prover a qualidade de vida das pessoas relacionadas a Ornito é um objetivo diário.

Buscamos pessoas apaixonadas por inovação e tecnologia, profissionais que enfrentam desafios de frente de maneira adulta e responsável.

A Ornito possui 4 anos de mercado com constante crescimento a todo vapor, agora incorporada por uma das maiores empresas de tecnologias da América Latina os nossos desafios que já eram emocionantes tomaram novas proporções.

Para você que quer trabalhar em um lugar disruptivo com agilidade na veia, trabalhar com tecnologias de ponta, ter a oportunidade de criar produtos digitais incríveis e participar de um ciclo de aprendizado constante, seja bem vindo.

## Como se candidatar

Por favor entre no link https://ornito.breezy.hr/p/656def44647e-frontend-alphaville-e-s-o-paulo e clique em Aplicar para posição

## Labels

- Alocado
- CLT

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
