### ISSUE TITLE
[Sorocaba/SP] Fullstack Developer na Goomer

### ISSUE THREAD

**Issue by rafalag** [frontendbr/vagas#843]
## Descrição da vaga

A Goomer é uma start-up de Sorocaba que trabalha com tecnologias de auto atendimento para restaurantes. Temos 3 anos de vida e já ajudamos os restaurantes no atendimento de 6,5 milhões de pedidos. Temos a missão de melhorar a experiência de consumo dos restaurantes do Brasil.

A vaga é para desenvolvedor full stack com foco em PHP (Laravel), programação web (html, css e javascript) e Node.js

## Local

Sorocaba/SP

## Benefícios

- Vale Refeição
- Vale Transporte
- Cursos
- Horário flexível
- Stock Option (participação na empresa)

## Requisitos

**Obrigatórios:**
- PHP
- Javascript
- HTML e CSS

**Desejáveis:**
- Conhecimentos em Laravel
- Conhecimentos de Node.js

**Diferenciais:**
- AngularJS, Ractive.js ou Vue.js

## Contratação

CLT ou PJ (a combinar)

## Como se candidatar

Inscreva-se pelo link: https://goo.gl/forms/wsY6rjZ1re4IVGZY2

## Labels

- CLT
- Pleno
- Presencial (possibilidade de home office alguns dias da semana)

**Comment by HaluDeCassia** [comment]
Boa tarde. Existe chance de remoto total?

**Comment by rafalag** [comment]
Boa tarde @HaluDeCassia infelizmente para essa vaga ainda não. Nós gostamos de envolver todos (desde designers, desenvolvedores, galera de vendas, customer success) no negócio. Todos participam das decisões, por isso a necessidade de estar presente pelo menos em alguns dias da semana.

**Comment by HaluDeCassia** [comment]
Que pena. Obrigada :smile:

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
