### ISSUE TITLE
[São Paulo - SP] Front-end Developer (AngularJS) na NOALVO

### ISSUE THREAD

**Issue by ggondim** [frontendbr/vagas#844]
## Sobre a NOALVO
* Somos uma startup de mídia off-line com pouco mais de um ano de vida.
* Fomos acelerados pela ACE, melhor aceleradora de startups da América Latina e já recebemos dois grandes aportes de investimento.
* Temos 12 pessoas no nosso escritório aqui na Av. Paulista, dentro do coworking do ACE Campus, junto a dezenas de outras startups, todos os dias. É um ambiente onde você respira conhecimento e inovação.
* Conheça mais sobre nós no nosso BLOG DE ENGENHARIA em http://engenharia.midianoalvo.com.br
* Conheça mais sobre nossa STACK DE DESENVOLVIMENTO em http://stackshare.io/noalvo/noalvo

## Descrição da vaga
Desenvolvedor/a front-end com experiência em tecnologias JavaScript para desenvolvimento de plataforma web com AngularJS.

# COMO SE CANDIDATAR
http://bit.ly/noalvo-frontend-gh

## Local
Av. Paulista, São Paulo, SP.

## Conhecimentos obrigatórios
* HTML5, CSS3 e Javascript (ES2015+)
* AngularJS
* Webpack
* Git
* Bootstrap 3
* LESS

## Proposta
PJ (valor a combinar)
Full-time
In-loco

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
