### ISSUE TITLE
[Votorantim - SP] Front-End Developer na Ventron

### ISSUE THREAD

**Issue by Dani-Ventron** [frontendbr/vagas#845]
## Descrição da vaga

Vaga para atuação na nossa fábrica de Software

## Local

em Votorantim - SP

## Benefícios

- Plano de saúde
- Seguro de vida
- VR 
- VT

#### Diferenciais

- oportunidade para crescimento e careira
- ambiente inovador

## Requisitos

Angular 1, CSS, HTML, Jquery, Javascript
Swift e/ou objective C, Ionic 1, 

## Contratação

CLT ou PJ - a combinar

## Nossa empresa

Nos somos uma empresa do grupo Cadmus, temos mais de 20 anos no mercado. Nossa fábrica de software fica localizada em Votorantim.

## Como se candidatar

Por favor envie um email para daniele.silva@ventron.com.br com seu CV anexado - enviar no assunto: Vaga Votorantim

## Labels

- CLT
- PJ
- Pleno
- Sênior

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
