### ISSUE TITLE
[Remoto] Front-End Developer ReactJs na Previdenciarista

### ISSUE THREAD

**Issue by renanno** [frontendbr/vagas#846]
## Descrição da vaga
Projeto em ReactJS. Remodelação completa de SaaS de pesquisa de conteúdo, gestão de usuários e cálculos.

Grosso modo: projeto para refação completa de site, do zero. Não há nada feito em Front ainda.

Integração via API Rest no backend. Designer vai entregar as telas prontas para serem seguidas. Portanto o Front deve ter as telas no Zeplin para seguir e as endpoints da API para integrar (_há documentação completa da API_)

Previsão para começar em meados/final de março e deadline em 30/06.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Git
- Consumo de API Rest
- HTML5, CSS3, Javascript (**ReactJS**), Responsividade, Crossbrowser
- Organização

**Desejáveis:**
- Uso do [Docker](https://www.docker.com/)
- Autenticação com OAuth2
- Bom relacionamento com o dev backend e facilidade de comunicação (disponibilidade).

**Diferenciais:**
- Com foco no deadline, faça seu próprio horário

## Contratação

PJ a combinar

## Nossa empresa

Somos uma lawtech e trabalhamos disponibilizando petições para advogados especialistas em Direito Previdenciário há 5 anos. Agora estamos rodando um projeto novo e mais completo para atender a rotina diária do advogado.

## Como se candidatar

Por favor envie um email para contato@previdenciarista.com **com portfolio** - enviar no assunto: Vaga FrontEnd

Se possível, peço que aponte no email os projetos feitos em React constantes no portfolio.

## Labels

- PJ
- Remoto - Total
- Pleno

**Comment by DEXTERNATAN** [comment]
Ainda está recebendo candidaturas?

**Comment by renanno** [comment]
@DEXTERNATAN desculpe a demora. Sim, ainda estamos (y)
