### ISSUE TITLE
São Paulo - Desenvolvedor JAVA - na WTIME 

### ISSUE THREAD

**Issue by AnieliFernanda** [frontendbr/vagas#849]
**WTIME** contrata urgente **DESENVOLVEDOR JAVA**! 

Projeto pontual. 
Modalidade PJ 
Irá atuar a primeira semana no cliente e depois será home office.
Cliente fica localizado na Paulista.
Inicio imediato

Interessados enviar currículo para anieli.fernanda@wtime.com.br

**Comment by kivervinicius** [comment]
Olá @AnieliFernanda poste a vaga em https://github.com/backend-br/vagas aqui somente vagas front-end.

**Comment by AnieliFernanda** [comment]
Obrigada!
