### ISSUE TITLE
[Campinas] Desenvolvedor Front-end - Pleno/Senior

### ISSUE THREAD

**Issue by luisfmsouza** [frontendbr/vagas#85]
## Descrição da vaga

Atuar como desenvolvedor front-end do OnMaps, plataforma Web de geomarketing desenvolvida pela Geofusion, que utiliza tecnologias  e ferramentas para soluções Web e GIS: Java EE, JSF, JPA, Backbone.js, REST e Oracle Spatial.

## Local

Campinas

## Requisitos

- Experiencia com desenvolvimento de aplicações Web em JavaScript, HTML e CSS 
- Conhecimento de framework MV* em JavaScript: Backbone.js, AngularJS, etc. 
- Conhecimento de pré-processador de CSS 
- Experiência com REST ou WS-* 
- Conhecimento de jQuery, Underscore.js e Handlebars.js 
- Java básico

## Nossa empresa

Criada há mais de 20 anos, a Geofusion é uma empresa de tecnologia focada em Inteligência Geográfica de Mercado e referência no segmento de Geomarketing no Brasil.

Nosso objetivo é facilitar a tomada de decisão de nossos clientes, utilizando tecnologia e informações de mercado para gerar inteligência e apoiá-los nas áreas de planejamento estratégico, expansão, marketing, vendas e gestão do negócio.

Por meio do OnMaps, plataforma tecnológica líder no segmento, nossos clientes desenvolvem análises geográficas,

acompanhando as mudanças nos mercados e traçando ações e estratégias mais assertivas.

A Geofusion é uma das empresas investidas pelos Fundos de Investimentos Intel Capital e DGF.

Atualmente contamos com mais de 100 colaboradores e atendemos empresas de diversos portes e setores, como varejo, franquias, shopping centers, indústria, mercado imobiliário, ensino, entre outros.

## Contratação

CLT

## Como se candidatar

[Para se candidatar clique aqui e acesse a vaga no LinkedIn](https://www.linkedin.com/jobs2/view/175404393).

**Comment by willianjusten** [comment]
Opa @luisfmsouza, só fiquei com dúvida, qual seria o modelo PJ ou CLT?

**Comment by luisfmsouza** [comment]
@willianjusten 99% de chance de ser CLT, vou atualizar ali.

**Comment by willianjusten** [comment]
Prontinho, coloquei a label =)

**Comment by eduardojmatos** [comment]
Ae @luisfmsouza  já preencheu a vaga? Nos avise pra mantermos ou removermos da lista :)

**Comment by luisfmsouza** [comment]
Pode remover @eduardojmatos

**Comment by eduardojmatos** [comment]
@luisfmsouza valeu mano! 

@LFeh tbm, por fechar heheh

**Comment by camilatigre** [comment]
@luisfmsouza 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by luisfmsouza** [comment]
@camilatigre alternativa C.
