### ISSUE TITLE
[ Barueri ]- Desenvolvedor C# .NET JR- Home Office PJ 

### ISSUE THREAD

**Issue by AnieliFernanda** [frontendbr/vagas#850]
Wtime Business Intelligence IT, contrata para atuar em cliente :

Desenvolvedor C# .NET Junior 

Experiência em: Visual Studio .NET, REST,Database(SQL Server e PostGre) 
Web API, WCF, WF, MVC, and ASP.NET, Angular JS, HTML5 e CSS, Message Queues(AWS SQS, 
RabbitMQ, MSMQ). 

Desejável Design patterns, NoSQL 
 
Local de trabalho Alphaville/ Jundiaí (1 vez na semana) e Home Office (4 dias na semana). 
Modalidade PJ		

Interessados enviar currículo no e-mail anieli.fernanda@wtime.com.br

**Comment by danielGalvao** [comment]
backend

**Comment by grippado** [comment]
Bom dia @AnieliFernanda, esse canal é exclusivo pra vagas de Front-End, poste sua vaga no https://github.com/backend-br/vagas que é mais direcionado a esse perfil que está procurando.
