### ISSUE TITLE
[São Paulo] Senior Frontend Engineer (React) at SumUp

### ISSUE THREAD

**Issue by mlent** [frontendbr/vagas#851]
![logo-sumup-rgb](https://user-images.githubusercontent.com/1771845/36901359-29fb192e-1e27-11e8-9575-4fee7f0f1b57.png)

## Descrição da vaga

In this role, you'll work with a cross-functional team to build tools that help hundreds of thousands of small businesses thrive. By shipping code early and often, you'll see the impact of your work on merchant's daily lives right away. You'll collaborate with experts in product, design, and operations to deliver mission-critical internal and external features that power the SumUp ecosystem.

We work on a number of different projects that span technologies, systems, and processes. A few of the technologies we're leveraging on the web at SumUp include **React, Webpack, Jest, Enzyme, Storybook, Next.js, Gatsby, Emotion, Node, and Docker**.

Learn more about SumUp here 👉https://sumup.com.br

## Local

This position is located in our gorgeous office in São Paulo in the heart of **Pinheiros**, near the Pinheiros Subway 🚊

![img_8006](https://user-images.githubusercontent.com/1771845/36901754-87d2b9b6-1e28-11e8-94f4-789b240ef9ca.JPG)
![img_8200](https://user-images.githubusercontent.com/1771845/36901839-c8153f3a-1e28-11e8-94d8-b2a20d2e131f.JPG)
![img_8205](https://user-images.githubusercontent.com/1771845/36901880-f6262f6a-1e28-11e8-8b74-75a8ea6f1cca.JPG)

## Benefícios

- **Budget for attending conferences** and advancing your career. We encourage you to speak at conferences and give talks!
- Weekly Lunch and Learn session, where the local engineering team exchanges ideas over **company-sponsored lunch**.
- Dedicated time every week for **side-projects and open source initiatives**.
- **Opportunity to travel to Europe** ✈️ for semi-annual off-sites, where the tech teams from Berlin, Sofia, and São Paulo gather together.
- All the startup swag you expect: modern office, unlimited coffee, and a shiny MacBook Pro.

#### Diferenciais

- International company with offices in Berlin and Sofia
- Opportunity to travel to Europe for semi-annual off-sites and hackathons
- Super modern React-based tech stack
- Choose your hardware, MacBook or PC
- English classes 📚
- Competitive salary and opportunity to grow
- Gympass, VT, medical care 🏃🏻

## Requisitos

**Obrigatórios**

- Strong programming foundation and experience in Javascript
- Linux fundamentals (git, ssh, editing a file on a remote server, reading logs, etc.)
- Experience building a non-trivial Single Page Application (SPA), ideally in React
- Ability to implement design specs precisely
- Ability to communicate fluently about technical topics in English
- 4+ years professional experience

**Desejáveis**

We would love if you've shipped code in programming languages besides Javascript or have experience with Node, but it's not a requirement. This is fundamentally a fullstack role!

## Contratação

CLT

## Nossa empresa

![sumup_2](https://user-images.githubusercontent.com/1771845/36901387-44bc5f7a-1e27-11e8-876f-f39394686892.jpg)

We are the leading global mobile point-of-sale (mPOS) company, with major offices in Berlin, Sofia, and São Paulo. We started out five years ago and built our payment service from scratch to shake up the industry and wake up the entrepreneur within everyone.

## Como se candidatar

Please apply on our website 👉 https://sumup.com/careers/positions/6455E0C3F5/

## Labels

- Alocado
- CLT
- Pleno
- Sênior

**Comment by kivervinicius** [comment]
Bela vaga! Infelizmente só me falta o inglês fluente :(

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
