### ISSUE TITLE
[Rio de Janeiro] Front-End Developer Pleno/Sênior na SuperUber

### ISSUE THREAD

**Issue by Vamoss** [frontendbr/vagas#853]
## Descrição da vaga

São 3 vagas para trabalhar em projetos multimedia com interfaces interativas (TouchScreen, Mobile, Jogos, VR etc).
O importante aqui é mandar bem de front, os outros skills da vaga a gente compartilha internamente ou aprende junto.
![3vagas](https://user-images.githubusercontent.com/245841/36912830-c82b0e8e-1e26-11e8-9069-d1c3726f6b9b.png)

## Local

Escritório: Rio de Janeiro - Gamboa

#### Diferenciais da empresa

- Projetos desafiadores/inovadores
- Equipe multidisciplinar
- Temos todos os equipamentos de VR a dispor (Oculus, Vive, PS4 etc)

## Requisitos

**Obrigatórios:**
- conhecimentos sólidos com JS, HTML, CSS;
- ser responsável com entregas/prazos;

**Desejáveis:**
- WebGL, ThreeJS, AFrame;
- VueJS ou ReactJS;
- Conhecimentos e experiência com Git e Task-runner (Webpack);
- Conhecimento de técnicas de otimização de performance;
- Conhecimentos com UX, design de aplicativos.

**Diferenciais:**
- Conhecimento de integração contínua;
- Node WebKit;
- PhoneGap, Cordova, Ionic ou ReactNative;

## Contratação

PJ a combinar

## Nossa empresa

Os projetos da SuperUber são conhecidos por abordarem áreas como Interfaces Interativas, Realidade Virtual, Aplicação Mobile, Projeção Mapeada, Jogos etc:
http://www.superuber.com/projects/all/

## Como se candidatar

Por favor envie um email para carlos@superuber.com com seu CV anexado e projetos que gostaria de destacar.

**Comment by HaluDeCassia** [comment]
Boa tarde. A vaga é alocada ou remota?

**Comment by Vamoss** [comment]
Oi @HaluDeCassia, a vaga é alocado.
Se souber ThreeJS e Aframe podemos considerar.

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
