### ISSUE TITLE
[Rio de Janeiro] Front-End Developer na Webedia

### ISSUE THREAD

**Issue by nandosangenetto** [frontendbr/vagas#855]
![alt text](http://jobs.webedia.group/webedia-companies.png "Webedia")

## 🎉🎉 Sobre a vaga 🎉🎉
Você vai trabalhar na equipe que desenvolve projetos internos como Versus, projetos de concursos que servem para sites como Adoro Cinema, PurePeople e Tudo Gostoso, assim como sites para clientes externos. Nosso time gosta de muito aprendizado e oportunidades para usar novas tecnologias e gerar melhores resultados, assim como possuímos uma dinâmica horizontal, ou seja, todos tem voz ativa nas decisões internas.

## Local
🔥 Botafogo, RJ (pertíssimo do metrô)

## Benefícios

- 🥗🍲 VR de R$ 25/dia
- 🚌🚊 Vale Transporte
- 🏥🚑 Plano de saúde e odontológico
- 🥖☕️ Café da manhã e da tarde
- 👕👚 Ambiente descontraído: nada de formalismos desnecessários e roupa social
- 📈📊 Oportunidade de crescimento. Você será acompanhado através de programas de desenvolvimento de carreira.
- 🎉🎊 Festinhas da empresa com frequência: Promovemos integrações com outras equipes na empresa com festinhas e outras atividades. Olha o último festão com nossa sede de SP e RJ juntas neste [vídeo](https://vimeo.com/257192408).

## Requisitos

**Obrigatórios:**
- 🎓 Gostar de aprender coisas novas: estamos sempre em busca de melhorias em nossos produtos;
- 👤 Ser analítico e detalhista: ​Prezamos pela melhor experiência possível para nossos usuários (usuário sempre acima);
- 💻 Já ter tocado algum projeto web: ​se sente seguro com  HTML, CSS e JavaScript?
- 📱 Conhecimento em design responsivo (mobile-first) 
- ✅ Conhecimento em sistemas de versionamento, preferencialmente Git;
- 🇺🇸🇬🇧 Inglês intermediário (leitura e escrita);

**Desejável:**
- Experiência com ⚛️ React

**Diferenciais:**
- Experiência com back-end: ​Node e(ou) PHP

## Contratação
CLT com horário parcialmente flexível (com banco de horas)

## Nossa empresa
A Webedia é um grupo de mídia digital de origem francesa presente em mais de dez países, com verticais que totalizam 177 milhões de usuários únicos por mês, dos quais 47,3 milhões estão no Brasil, a maior audiência do grupo. O sucesso se deve ao controle de sites líderes em segmentos estratégicos: TudoGostoso (comida), AdoroCinema (entretenimento), IGN (jogos), Versus (e-sports), PurePeople e Purebreak (glamour/celebridades), Minha Vida (saúde e bem-estar), Hypeness (inovação e criatividade), entre outros. Por meio da divisão de Brand Publishing, a Webedia oferece ainda expertise em audiência para clientes como Niely, Johnson & Johnson, Oral-B, Gillette, L'Oréal, Maybelline, La Roche Posay, Leroy Merlin, entre outros.

## Como se candidatar
- Mande seu CV por e-mail com o assunto "[Vaga Front Júnior]" em cópia para ambos: 
✉️ fernanda.cavalcanti@webedia-group.com
✉️ fernando.sangenetto@webedia-group.com
- Se quiser, sinta-se livre pra mandar algo que você se orgulhe de ter feito, sua história de vida, GitHub, LinkedIn, portfólio ou qualquer outra coisa que ache interessante compartilhar com a gente 🙃

## Labels
- Alocado
- CLT
- Júnior

**Comment by RenatoAreas** [comment]
Enviado !!! ;)

**Comment by adeonir** [comment]
Bela vaga... pena que não é remoto.

**Comment by antoniotex** [comment]
Muito legal a vaga, ótima oportunidade!
Currículo enviado.

**Comment by danilogila** [comment]
Estão aceitando estagiário?

**Comment by danilogila** [comment]
Gostaria muito de uma oportunidade.

**Comment by nandosangenetto** [comment]
@danilogila não é o nosso foco agora, mas gostaria que enviasse seu CV para conseguir analisar e ver o que é possível fazer.

**Comment by webmalta** [comment]
Aceitaria pleno/sênior?

**Comment by nandosangenetto** [comment]
@webmalta infelizmente não no momento. Tínhamos está vaga há uns meses.

**Comment by rodrigoleite89** [comment]
Olá, vocês não tem interesse em Home Office? Eu sou de outro estado.

**Comment by ednaldobritowk** [comment]
Enviado :)

**Comment by nandosangenetto** [comment]
@rodrigoleite89 não estamos trabalhando com home office para estas vagas.

**Comment by marlon86** [comment]
Enviado. Muito boa a vaga

**Comment by nandosangenetto** [comment]
@marlon86 boa sorte!

**Comment by cassianomon** [comment]
Que bela vaga!

**Comment by ArieltonPires** [comment]
Sent!

**Comment by nandosangenetto** [comment]
@cassianomon Obrigado! 🤗

@ArieltonPires boa sorte!

**Comment by Thiagorrrr** [comment]
Enviado ! :)

**Comment by nandosangenetto** [comment]
@Thiagorrrr boa sorte! 👍

**Comment by thallesmarchetti** [comment]
### enviado!

**Comment by lzhudson** [comment]
Enviei duas cópias do CV, a primeira estava desatualizada se puder olhar, acabei de enviar a segunda.

**Comment by nandosangenetto** [comment]
Pode deixar @lzhudsonm, boa sorte!

**Comment by ArieltonPires** [comment]
abriu a vaga novamente @nandosangenetto?

**Comment by nandosangenetto** [comment]
Não @ArieltonPires, é o mesmo processo seletivo.

**Comment by nandosangenetto** [comment]
Depois de mais de 70 candidatos, conseguimos contratar 3 excelentes pessoas vindas daqui 🎉 🎉 🎉
