### ISSUE TITLE
[Belo Horizonte] Fullstack Developer na SEEDZ

### ISSUE THREAD

**Issue by eluizbr** [frontendbr/vagas#856]
## Descrição da vaga

A vaga é para desenvolvedor full stack com foco em NodeJS, MongoDB, Angular, React, VueJS

## Local
Alocado / Remoto parcial, Belo Horizonte - MG

## Requisitos

**Obrigatórios:**
- Sólidos conhecimentos em JavaScript
- NodeJS
- MongoDB
- Angular
- Proativo

**Desejáveis:**
- React
- VueJS
- HTML
- CSS
- Experiência em integrações REST / SOAP

**Diferenciais:**
- Python
- MySQL
- PostgreSQL

## Contratação
CLT

## Benefícios
Vale transporte
Ticket refeição R$ 20,50 / dia
Plano de saúde

# Nossa empresa
A Seedz é o primeiro programa de fidelidade de coalizão com foco nas pessoas e empresas do agronegócio.
Temos o propósito de fazer com que as pessoas e empresas do agro conquistem o sucesso com maior emoção e menor esforço.

# Como se canditatar
Por favor envie um email para emerson@ecobonuz.com com seu CV em PDF em anexo. 
O assunto do email: Vaga Fullstack

## Labels

- Alocado
- CLT
- Pleno
- Remoto - Parcial

**Comment by netstart** [comment]
;)
