### ISSUE TITLE
[São Paulo] Senior Front-End Developer na Farfetch

### ISSUE THREAD

**Issue by bchagas** [frontendbr/vagas#857]
## Descrição da vaga

Já pensou em construir o produto que vai revolucionar a forma como as pessoas compram e integrar a vida online e offline de uma forma que o mundo nunca viu?
A Farfetch está a procura de um Front-End Developer para integrar o nosso crescente time de tecnologia!

## Local

Escritório, São Paulo - Av. Paulista

## Benefícios

- Assistência médica 
- Assistência odontológica
- Vale transporte
- Vale refeição R$ 23,00 por dia 
- Seguro de vida
- Auxílio creche

#### Diferenciais

- Bônus anual de até 3 salários
- Stock options
- Ambiente descontraído
- Horário Flexível

## Requisitos

**Obrigatórios:**
- Sólidos conhecimentos em Javascript, HTML e CSS;
- Experiência em diferentes stacks e Frameworks e.x.: ReactJS, Angular.JS (1x e 2x), Node.JS, Backbone.JS, Webpack, Grunt, Gulp, Jasmine, Mocha, Handlebars, SASS
- Experiência em times Agile / Scrum ou Kanban;
- Conhecimentos de Clean Code.
- Conhecimentos de sistemas de controle de versão(GIT);
- Experiência com APIs REST;
- Conhecimentos em Responsive Web Design;
- Vontade de aprender constantemente;

**Desejáveis:**
- Experiência no desenvolvimento de APIs Rest;
- Compreensão sólida de Back-end e sua interação com Front-end;
- Programação Funcional;

## Contratação

CLT

## Nossa empresa

A Farfetch é diferente de qualquer coisa no mundo da moda e da tecnologia. Nossa missão: revolucionar a maneira como o mundo faz compras.
Para fazer isso, precisamos de inovadores, pessoas que desafiam convenções e ousam sonhar. 
Nós passamos de um negócio de start-up a bilhões de dólares. 
Mas ainda não terminamos. Longe disso.
Seja ousado.
Seja brilhante.
Juntos, podemos ser extraordinários.

## Como se candidatar

Por favor envie um email para carreiras@farfetch.com com seu CV anexado - enviar no assunto: Vaga Front-end Senior

## Labels

- Alocado
- CLT

**Comment by DawTaylor** [comment]
@bchagas esse email está retornando como inexistente.

**Comment by bchagas** [comment]
@DawTaylor vou verificar, obrigado!

**Comment by bchagas** [comment]
@DawTaylor acabei de enviar um teste para este email e está OK, você já conseguiu enviar? Obrigado!

**Comment by DawTaylor** [comment]
@bchagas testei novamente e recebi a mesma mensagem de erro.

<img width="1184" alt="captura de tela 2018-03-05 as 14 42 42" src="https://user-images.githubusercontent.com/5186842/36990476-971c3a66-2083-11e8-8fe8-c02aec0af94f.png">

**Comment by bchagas** [comment]
@DawTaylor o seu email é @gmail?

**Comment by bchagas** [comment]
@DawTaylor acabei de ver com o pessoal responsável, eles me disseram que agora está tudo certo, obrigado pelo report!!

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
