### ISSUE TITLE
[São Paulo] Javascript Developer na Wtime 

### ISSUE THREAD

**Issue by AnieliFernanda** [frontendbr/vagas#858]
Wtime contrata para atuar em cliente: 

**Programador Javascript** 

Conhecimentos em JAVA e Javascript, irá utilizar uma linguagem similar. 
É uma empresa de turismo. 

Inicialmente o profissional ficará alocado no cliente, de uma a duas semanas, após irá atuar HOME OFFICE. 

Projeto de 700h, podendo ser prorrogado para 10.000h.

Disponibilidade para Inicio imediato.
Contratação na modalidade PJ.

Interessados enviar currículo com pretensão salarial no e-mail anieli.fernanda@wtime.com.br 
Obrigada!

**Comment by LFeh** [comment]
A contratação vai ser feita pela própria wtime?

**Comment by AnieliFernanda** [comment]
Isso mesmo!

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
