### ISSUE TITLE
[São Paulo] Front-End Developer na ClickBus

### ISSUE THREAD

**Issue by davidtavares** [frontendbr/vagas#859]
## Descrição da vaga

Estamos em busca de um desenvolvedor front-end com excelentes habilidades analíticas e uma boa atitude de resolução de problemas para nos ajudar no crescimento da nossa plataforma de vendas de passagens rodoviárias. Para crescer junto com a gente, esperamos mais um grande talento apaixonado por gerar soluções que tornem a vida das pessoas mais fácil.
Nossas equipes compõem times ágeis multifuncionais compostos por um P.O., desenvolvedores frontend e backend, desenvolvedores de testes e devops. As equipes são altamente autônomas com a propriedade e capacidade para atuar em nome do nosso melhor interesse.

## Cotidiano

- Participar em todas as fases do desenvolvimento de várias soluções web (arquitetura, design, prototipação, desenvolvimento, teste, implantação e lançamento);
- Trabalhar com o time para esclarecer fluxos funcionais e fornecer informações técnicas sobre performance e otimização;
- Participar de brainstorm e sessões de feedback dos usuários para coletar informações para aplicar mudanças rápidas para iterações de protótipos;
- Conduzir as melhores práticas produzindo códigos de alta qualidade, documentados e testáveis, que atendam aos padrões de qualidade;
- Manter-se atualizado com as novas tendências tecnológicas; Pesquisar e sugerir novos produtos, aplicações e frameworks;

## Local

São Paulo - Vila Olímpia.

## Benefícios

- Vale Refeição de R$29,00/dia;
- Vale Transporte;
- Horário flexível;
- GymPass;
- Assistência médica / odontológica / Seguro de vida.

#### Diferenciais

- Ambiente de trabalho descontraído, com espírito de equipe e pessoas talentosas;
- Autonomia para trabalhar, desenvolver e implementar ideias;
- Monte a sua máquina como desejar
- Playstation! Playstation!

## Requisitos

**Obrigatórios:**
- Formação superior completa;
- Experiência na utilização de serviços (API) RESTFul;
- Experiência com JavaScript, jQuery e HTML5/CSS;
- Conhecimento prático de sistemas de compilação para automatizar tarefas, como CI/CD (usamos Travis e Gulp);
- Gerenciamento de código-fonte (usamos Git).

**Desejáveis:**
- Experiência em PHP (POO, familiaridade com frameworks de mercado, usamos Symfony);
- Conhecimento em ReactJS;
- Conhecimento em LESS/SASS;
- Conhecimento em metodologias de ágil;
- Experiência com integração contínua.

**Diferenciais:**
- Solid;
- Angular, Vue.JS;
- TDD, BDD.

## Contratação

CLT.

## Nossa empresa

Não vamos inventar a roda, mas queremos mostrar para os brasileiros que viajar sobre elas está muito mais fácil. Nascemos com a missão de evoluir a experiência de viagem do brasileiro e trazer o melhor do e-commerce e do turismo para um setor que ainda está começando a migrar para o mundo online.

A ClickBus é o principal agente da mudança de comportamento no mercado rodoviário: trabalhamos para que os viajantes tenham uma jornada muito mais leve e simples e isso inclui a compra de suas passagens com mais conveniência e agilidade. Também queremos que as empresas de ônibus e as rodoviárias sejam catalisadoras das inovações e que o setor rodoviário como um todo seja reinserido no turismo, permitindo assim que mais brasileiros, sem nenhuma distinção, viajem e participem do que hoje é uma declaração de felicidade moderna.

Somos parte de uma das mais famosas incubadoras no mundo, o Grupo Rocket Internet e somos a líder de mercado em todas as unidades de negócio. Estamos em todas as pontas do ecossistema digital do setor rodoviário: como um GDS (agregador), OTA (plataforma online) e Gestor de Whitelabels (sites de empresas de ônibus e de rodoviárias).

Trabalhamos todos os dias ajudando viajantes a encontrarem suas passagens de ônibus com a máxima conveniência; pelo site ou aplicativo iOS e Android; e ajudamos as empresas de ônibus a aumentarem suas vendas online.

A plataforma online permite que viajantes pesquisem, comparem e comprem passagem de ônibus rodoviário de mais de 100 empresas de ônibus para mais de 4.000 destinos em todo o Brasil, e até o final de 2016 vendeu online mais de 5 milhões de passagens rodoviárias.

E tudo isso só é possível porque nós temos um time extremamente qualificado e orientado a resultados, mas mais do que isso, feliz e unido!

## Como se candidatar

Está afim de embarcar nessa? Mostre a sua bagagem pra gente aplicando para esta vaga! :) Envie seu CV para recrutamento@clickbus.com.br com o assunto: "Front-End Developer"

## Labels

- Alocado
- CLT
- Júnior
- Pleno
- Sênior

**Comment by angelilton** [comment]
a vaga para júnior ainda está aberta?

**Comment by davidtavares** [comment]
@angelilton sim, vagas para os 3 níveis
