### ISSUE TITLE
[São Paulo] Front-end developer pleno thinkseg.com (5K CLT)

### ISSUE THREAD

**Issue by carnivash** [frontendbr/vagas#86]
![thinkseg-busca-front](https://cloud.githubusercontent.com/assets/2055014/17311738/f4a0a21e-5823-11e6-88d3-0a1046fb8b50.png)
## Descrição da vaga

Necesitamos front-end developer para integrar nosso time numa startup do ramo de seguros: thinkseg.com
## Local

Escritório, São Paulo - Pinheiros
## Benefícios
- Possibilidade de participar de nascimento da startup mais quente de 2016.
## Requisitos

**Obrigatórios:**
- 1 a 3 anos de experiência com javascript (AngularJS, Ionic Framework, UI/UX, CSS3 animations)

**Desejáveis:**
- design gráfico

**Diferenciais:**
- conseguir seguir a risca o direcionamento de um diretor de arte
## Contratação

PJ a combinar
## Nossa empresa

A Primeira comunidade de seguros do mundo integrada à uma plataforma mobile, seguradora e programas de pontos/fidelidade, onde o usuário terá a oportunidade de obter vantagens ao contratar o seu seguro.

Modelo exclusivo thinkseg®
Pague apenas:
• Onde você usa;
• Como você usa;
• Quando você usa;
• Quanto você usa;
• Por quem está usando - multiusuário.
Muito mais barato! Por quê?
A inteligência da thinkseg® permite que o valor a ser pago pelo seguro seja calculado pelo perfil individual e pelo seu comportamento no trânsito e não por um perfil genérico como as seguradoras convencionais. A nossa tecnologia elimina redundâncias de coberturas e o pagamento é feito apenas pelo o que é utilizado, pelas coberturas escolhidas e quando for utilizado. Fácil assim!
## Como se candidatar

Por favor envie um email para alexander.melo@grgcapital.com com seu CV anexado - enviar no assunto: Vaga Front-end Developer

**Comment by willianjusten** [comment]
Boa sorte =)

**Comment by Mendrone** [comment]
@carnivash a vaga foi preenchida?

**Comment by carnivash** [comment]
Ainda está aberta.

**Comment by eduardojmatos** [comment]
@carnivash já acharam alguém ou ainda na procura? Nos avise pra mantermos ou removermos da lista :)

**Comment by carnivash** [comment]
A vaga continua aberta.

**Comment by jvcjunior** [comment]
Nenhuma possibilidade de remoto at all?

**Comment by carnivash** [comment]
Não amigo, o cliente exige ser presencial.

**Comment by eduardojmatos** [comment]
@carnivash ok! :)

**Comment by carnivash** [comment]
Ainda temos vagas.

**Comment by LFeh** [comment]
Show
