### ISSUE TITLE
[Remoto] Front-End Developer na Dife Panel

### ISSUE THREAD

**Issue by vaneves** [frontendbr/vagas#860]
## Descrição da vaga

Procuramos um front-end developer que seja experiente (comprovando por meio do git), que tenha comprometimento, se importe com a legibilidade de seu código e que mexa em código de outros programadores seguindo o padrão. Queremos alguém que goste de novas tecnologias e de inovar.

## Local

Remoto - Palmas, Tocantins

## Requisitos

- Git
- Sass
- Javascript puro
- jQuery
- Responsive web
- Integração com APIs
- Trello
- Dar continuidade em código de outros

**Desejáveis:**

- Atenção à performance
- Automatização utilizando o Gulp
- Testes automatizados
- Organização e padronização

**Diferenciais:**

- UX Design
- PHP
- Laravel

## Contratação

PJ por valor a combinar e por prazo indeterminado.

## Nossa empresa

[Dife](https://dife.com.br/) é uma startup que contém a plataforma Dife Panel, para criação de painéis de gerenciamento de sites estáticos. Nós buscamos criar ferramentas que facilitem o desenvolvimento de aplicações web. 

## Como se candidatar

Por favor, envie-nos um e-mail para vagas@dife.com.br com seu GitHub/LinkedIn/Portfólio e CV anexado - enviar no assunto: **[vaga-frontend]**

## Labels

- PJ
- Pleno
- Remoto - Total

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
