### ISSUE TITLE
[Rio de Janeiro] Front-End Developer [AG Marketing Digital]

### ISSUE THREAD

**Issue by AGMarketingDigital** [frontendbr/vagas#861]
## Descrição da vaga

Desenvolvedor com experiência em marketplace para projetos simples. Alguns me wordpress com wc marketplace

## Local

Remoto (Morar no RJ será um diferencial para outros trabalhos)

## Requisitos

ExperiÊncia em construção de Market Place

**Desejáveis:**
Conhecimento HTML, PHP, JAVA, CSS...

**Diferenciais:**

## Contratação

PJ a combinar

## Nossa empresa

Somos uma agência de marketing digital focada na  produção de conteúdo, criando estratégias de Inbound otimizando o posicionamento do site da sua empresa nos motores de busca.

## Como se candidatar

Por favor envie um email para agencia@agmarketing.digital com seu CV anexado - enviar no assunto:  FrontEnd ou em nosso site no link https://agmarketing.digital/trabalhe-conosco/

## Labels

- Freela
- Remoto - Total

**Comment by fsilvaco** [comment]
CV Enviado!

**Comment by fsilvaco** [comment]
CV Enviado! :)

**Comment by hevertonsb** [comment]
Java? PHP?

Em 6 de mar de 2018 12:22, "Flávio Silva" <notifications@github.com>
escreveu:

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
