### ISSUE TITLE
[São Paulo] Front-End Developer na [123 carros]

### ISSUE THREAD

**Issue by paulocastellano** [frontendbr/vagas#862]
## Descrição da vaga

Estamos construindo um SPA em VueJS, consumindo apis feitas em laravel. Estamos procurando um profissional que entenda de VueJS para nos ajudar na construção desse novo projeto.

## Local
Presencial, São Paulo - Itaim bibi

## Benefícios
- Horário flexível

## Requisitos

**Obrigatórios:**
- 1 ano de experiência com VueJS
- Yarn
- Webpack
- Axios
- CSS3

**Desejáveis:**
- Sass
- ionic/quasar
- Gitlab
- Unit test

## Contratação
PJ a combinar

## Nossa empresa
123 carros é uma plataforma que ajuda pessoas físicas a venderem seus carros para outras pessoas físicas. Facilitamos todo este processo.

## Como se candidatar

Por favor envie um email para ana.moura@123carros.com.br com seu CV ou LinkedIn - enviar no assunto: Vaga Desenvolvedor Front-end

## Labels
- Alocado
- PJ
- Pleno
- Sênior

**Comment by brunokunace** [comment]
Uma pena ser alocado

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
