### ISSUE TITLE
[São Paulo] Front-End Developer na IDwall

### ISSUE THREAD

**Issue by gcleite** [frontendbr/vagas#863]
![Image of IDwall](https://dashboard.idwall.co/assets/images/logo-idwall.svg)

# Front-end Developer

### What you’ll be doing here:
- Maintaining our website and other landing pages
- Using React to develop our internal and external dashboards
- Use our API to create more stuff

### You need to have...
- Experience with React, Angular and/or Vue.js
- Experience with JavaScript ES6+
- Experience on unit tests and automatized tests
- Familiarity with Cloud Computing. More specifically, AWS
- Possibility to work in Sao Paulo, SP, Brazil.

### It would be nice if you had...
- Experience with Docker
- Experience with TypeScript

### If you’re willing to be part of our team...
Apply at https://www.99jobs.com/idwall/jobs/15319-front-end-developer or send your CV/LikedIn to jobs@idwall.co with the subject line titled “CV [Your Name] - Dev Front-end”, your portfolio and your GitHub profile!

This opening is not available for remote work. Please, apply only if you’re able to reside in Sao Paulo.

We’re looking forward to hearing from you. Good luck!	

## About us
IDwall was founded in 2016 by three geeks and was one of the first brazilian startups to be selected by Google to enroll in the Campus Residency Program, which takes place in many cosmopolitan cities all around the world and is now also in São Paulo, Brazil. 

Our mission is to solve the lack of trust and credibility in the digital age by building reliability between people and companies with our leading solutions, including: 
- Document validation
- Identity verification
- Background check

Since its establishment, IDwall has called the attention of many investors* standing among the hottest startups in Brazil. 

We’re growing fast and now we’re looking for another awesome person to be part of our Dev Team! If you love coding, overcoming challenges and learning new stuff everyday, we want you with us! (:

#### Yes, of course you can find us in the news!
- http://conexaofintech.com.br/en/idwall-raises-more-600k/
- http://exame.abril.com.br/pme/fundadores-do-peixe-urbano-investem-em-startup-que-revela-fraudes/
- https://pagamento.me/idwall-a-startup-de-dados-que-bancos-fintechs-e-empresas-de-pagamento-estao-de-olho/

## Labels

- Alocado
- CLT
- Junior
- Pleno
- Sênior

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
