### ISSUE TITLE
[Chapecó] Front-End Developer na Desbravador

### ISSUE THREAD

**Issue by acelant** [frontendbr/vagas#864]
# Descrição da vaga

A Desbravador Software é a maior empresa na área de hotelaria do Brasil, com mais de 3500 clientes, gerenciando 130k+ de quartos. Venha fazer parte do nosso time de desenvolvedores! (Chapecó ou Floripa)

Não conhece a gente? [Desbravador.com](https://desbravador.com)

## Responsabilidades:

* Trabalhar em conjunto com nosso time de desenvolvedores e analistas de projeto para melhorar nossos produtos e experiencias.
* Desenvolver novos software ou manter os já existentes;
* Ter iniciativa para realizar projetos e features desde sua concepção até o deploy.

## Local

Escritório, Chapecó - Jardim Itália

## Benefícios

* Plano de saúde
* Auxílio alimentação
* Salário competitivo

## Diferenciais

* Plataforma Alura
* Hora tecnica (momento de estudo e compartilhamento de conhecimento)

# Requisitos

## Obrigatórios:

* Inglês técnico;
* Profundo conhecimento em Vanila Javascript
* Bom relacionamento e comunicação;
* Conhecimento em consumo de WebAPI's REST.;
* Conhecimento intermediário em HTML5, CSS Bootstrap;
* Testes em JS (Jest, Mocha, Chai, Sinon, etc);
* Conhecimento basico em Scrum.

## Desejáveis mas não obrigatórios:

* Conhecer ao menos um dos frameworks React, Angular ou Vue
* Noções de programação backend.

# Contratação

CLT

## Como se candidatar

[Desenvolvedor FrontEnd](https://www.desbravador.com.br/trabalheconosco/desenvolvedor-front-end)

# Labels

* CLT
* Júnior
* Pleno
* Sênior
* Presencial

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
