### ISSUE TITLE
[Belo Horizonte] Full-Stack/Front-End Developer na CTC Franquias (Constance)

### ISSUE THREAD

**Issue by ALMMa** [frontendbr/vagas#866]
## Descrição da vaga

Estamos à procura de um dev full-stack que já possua foco maior em front-end ou que queira direcionar sua carreira nessa direção.
Alguém que consiga prototipar mudanças e melhorias, validá-las com a alta gestão e implementar mudanças que farão a diferença em dezenas de empresas por todo o Brasil. Trabalhando com grande responsabilidade e rimo rápido, os desafios serão uma constante no seu dia a dia por aqui.

## Local

Escritório (presencial), em Belo Horizonte, na Avenida do Contorno, 6081, ao lado do shopping Pátio Savassi.

## Benefícios

- Plano de saúde
- Plano odontológico
- Vale Refeição
- Vale Transporte

## Requisitos

**Obrigatórios:**
- Experiência com HTML5 e CSS3
- Experiência com Javascript (ES6) e/ou TypeScript
- Experiência GIT (Gitflow)

**Desejáveis:**
- Experiência com Bootstrap
- Conhecimentos em Angular (AngularJS e Angular 5)
- Conhecimentos em SPA e PWA
- Conhecimentos em API RESTful
- Conhecimentos em C# e .NET Core

**Diferenciais:**
- Conhecimentos em Yarn e Node
- Conhecimentos em TFS
- Facilidade de locomoção na região da Savassi

## Contratação

CLT em horário integral (44h). Faixa salarial: R$ 2.000,00 a R$ 3.000,00.

## Nossa empresa

Eleita a melhor franquia de calçados do Brasil em 2017, a Constance possui lojas em todo o Brasil.
Inovação e mudança são constantes aqui e você terá oportunidade de lidar com diversas tecnologias.

## Como se candidatar

Por favor envie um email para paulo@constance.com.br com seu CV anexado - enviar no assunto: "Vaga Full-stack 201803"

## Labels

- Alocado
- CLT
- Júnior
- Pleno
- Front-End
- Full-Stack

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
