### ISSUE TITLE
[São Paulo] Front-End Developer na Onebox

### ISSUE THREAD

**Issue by jumrsouza** [frontendbr/vagas#867]
## Descrição da vaga

Buscamos profissionais apaixonados por desenvolvimento Front-end para integrar nosso time!! 

A Onebox é uma startup de tecnologia focada em produtos para o público jovem e estudantil.
Nós estamos com um super desafio em 2018 para o Documento Nacional do Estudante e queremos reforços para o nosso Squad.

Você se identifica com equipes ageis e tem foco em resultado? 
Dá uma olhada no resto da vaga e vamos tomar um café ;)

## Local

Escritório, São Paulo - Itaim Bibi

## Benefícios

- Escritório legal e em ótima localização
- Seguro de vida
- Assistência Médica Amil
- Vale Refeição
- Vale Transporte
- PLR e Bônus

#### Diferenciais

- Horário flexível
- Video game e mesa oficial de poker
- Monte sua máquina como desejar

## Requisitos

**Obrigatórios:**
- Experiência com Javascript (ES6), CSS e HTML

**Desejáveis:**
- Experiência com pré-processador de CSS, SCSS
- Experiência com React

## Contratação

Negociável CLT ou PJ 

## Como se candidatar

Por favor envie um email para julia.souza@brodda.com.br com seu CV e "Vaga Front-End" no assunto. 

## Labels

- Alocado
- CLT
- PJ
- Junior
- Pleno

**Comment by matheusnascgomes** [comment]
Sou de pernambuco, mas estou indo passar uma temporada em SP no próximo mês em busca de oportunidade, posso me candidatar?
