### ISSUE TITLE
[São Paulo] Javascript Developer na Evnts

### ISSUE THREAD

**Issue by oneoffjs** [frontendbr/vagas#868]
## Descrição da vaga
Estamos em uma transição enorme, deixando de ser uma pequena startup para se transformar em uma grande empresa, todo a nossa plataforma está rodando em cima do que era nosso MVP que foi escrito às pressas, por isso, decidimos começar a reescrever partes do nosso sistema.
Estamos em busca de desenvolvedores para entrar de cabeça nesse projeto, além de desenvolver, você vai contribuir na escolha de quais tecnologias vamos utilizar e vai ajudar a recrutar novos membros para o nosso time.

## Local
Alameda Santos, São Paulo - Jardim Paulista (5 minutos da estação Trianon - Masp)

#### Obrigatórios:
 - Experiência com desenvolvimento Web;
 - HTML, CSS e JavaScript;
 - Gostar muito de aprender e compartilhar;

#### Desejáveis:
 - Experiência com grandes aplicações;
 - Conhecimento em testes de JavaScript (TDD / BDD);
 - Ter trabalhado com metodologia ágil;

## Benefícios
 - Horário flexível
 - Home office
 - No dress code (pode trabalhar de chinelo, bermuda, regata, etc)
 - Time com uma vontade absurda de querer ser sempre o melhor

## Contratação
CLT

## Nossa empresa
A Evnts é uma startup que em menos de 1 ano já passou por dois dos maiores processos de aceleração do Brasil (Seed e Oxigênio) e estamos em um crescimento absurdo.

Nós somos a maior plataforma de hospedagem para eventos do Brasil, com a nossa plataforma o organizador do evento consegue selecionar hotéis e oferecer para os visitantes com a menor tarifa do mercado, em pouco tempo no mercado já nos tornamos a plataforma oficial dos principais eventos do Brasil como CASE, Campus Party, Brasil Games Show, Shows da Livepass, Eventos da Porto Seguro, Eventos da Mitsubishi, QCon SP, FIRE e Rock in Rio. Temos um time pequeno, porém, muito apaixonado pelo que faz e em constante evolução.

## Como se candidatar
Envie um email para cleber@evnts.com.br, colocar no assunto: Vaga Javascript Developer

Caso você tenha se interessado pela vaga, mas, acha que não tem o conhecimento técnico necessário, também pode se candidatar, estamos em um crescimento absurdo, pode ter certeza que vamos analisar com carinho (:

## Labels
- CLT
- Estágio
- Júnior
- Pleno
- Remoto - Parcial

**Comment by lzhudson** [comment]
CV enviado !

**Comment by fcbento** [comment]
Enviado!

**Comment by javaprojetox** [comment]
Enviado!

**Comment by rafaelangical** [comment]
Enviado !

**Comment by lailsoncv** [comment]
A vaga de estágio pode ser home office?

**Comment by oneoffjs** [comment]
Home office (parcial) para estagiário não...

**Comment by danieladuarteng** [comment]
enviado

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
