### ISSUE TITLE
[REMOTO][ALOCADO] Front-End Sr na MATERA Systems

### ISSUE THREAD

**Issue by gss-patricia** [frontendbr/vagas#869]
## Descrição da vaga

Precisamos de front-end developers  Pl / Sr para a <a href="http://www.matera.com/br/" target="_blank">MATERA Systems</a>, para atuar com análise e desenvolvimento de Front-end em projetos para clientes internos e externos.

## Local

Remoto ou Escritório, São Paulo, Campinas ou Maringá.

## Benefícios

- Horário de trabalho flexível (40 h semanais);
- Pacote de Benefícios Flexíveis + PLR (Plano de participação nos lucros e resultados).

## Formação
Superior completo em Análise de Sistemas, Ciência da Computação, Engenharia da Computação, Sistemas de Informação ou cursos afins.

## Requisitos

**Obrigatórios:**
- Experiência com Node
- Especialista em CSS(incluindo flexbox, CSS, entre outros)
- Totalmente confortável com HTML, CSS e Javascript para implementação de UIs complexas;
- ES6
- React + Flux ou Redux
- Praticas com teste unitário e UI
- Inglês avançado

**Desejáveis:**
- conhecimentos em GraphQL
- conhecimentos D3
- Canvas
- Disponibilidade para eventuais viagens (nacionais e internacionais)

**Diferenciais:**
- projetos opensource

## Contratação

CLT
Presencial ou Remoto

## Nossa empresa

A MATERA Systems, desde 1987, atua como fornecedora de soluções e serviços de TI para o mercado financeiro e corporativo, além de realizar o desenvolvimento de aplicativos e projetos. São marcas registradas da empresa investir constantemente em inovação e capacitação de seus profissionais e aliar a excelência técnica ao conhecimento de negócios. Possui mais de 400 profissionais e desde 2008 está no ranking da GPTW. Sedes: Campinas­ - SP, São Paulo - ­SP, Niterói - ­RJ e Maringá­ - PR

## Como se candidatar

Por favor envie um email para recrutamento@matera.com com seu CV anexado - enviar no assunto: Vaga Front-End Sr.

## Labels

- Alocado
- CLT
- Pleno
- Remoto - Parcial
- Remoto - Total
- Sênior

**Comment by clluiz** [comment]
Não existe possibilidade de contratação PJ?

**Comment by gss-patricia** [comment]
@luizhenriquesoares é CLT tbm

@clluiz PJ não =/

**Comment by luizhenriquesoares** [comment]
@diogenesjcs

**Comment by paulo101977** [comment]
Que pena que não é pro Rio. Eu me enquadro em todas os requisitos e mais um pouco :(

**Comment by kivervinicius** [comment]
@paulo101977 É remoto....

**Comment by villander** [comment]
Vaga bem massa, a empresa parece te ter uma cultura bem irada também. Mas esse lance de será obrigatório dominar um framework X, tira muita gente boa do páreo.


https://twitter.com/_ericelliott/status/972850936195543040?s=20

**Comment by alinebastos** [comment]
Pena eu não ter curso superior completo..
