### ISSUE TITLE
[São Paulo] Front-End Junior

### ISSUE THREAD

**Issue by iuato** [frontendbr/vagas#87]
## Descrição da vaga

A Editora Três é a terceira maior editora de revistas do país, publica as revistas ISTOÉ, ISTOÉ DINHEIRO, ISTOÉ GENTE, PLANETA, MOTOR SHOW entre outros.
http://editora3.com.br/sobrenos.php

Buscamos profissional com experiência em desenvolvimento frontend.
## Local

Rua William Spears 1088 , São Paulo -  Lapa de Baixo
## Requisitos

**Obrigatórios:**
HTML
CSS
JavaScript
jQuery

**Desejáveis:**
Task Runners (Stylus / Gulp)
Responsive Web Design

**Diferenciais:**
- Wordpress
## Contratação

PJ
R$4000,00
## Benefícios
- Décimo terceiro salário
- Férias remuneradas
- Adicional de férias (1/3 do salário)
- Refeitório no local com badeijão
## Como se candidatar

Por favor envie um email para iuato@editora3.com.br com seu CV anexado - enviar no assunto: Vaga Frontend Jr

**Comment by simaodeveloper** [comment]
Oi gastaria de saber se é PJ como informa na descrição ou CLT como na label?

**Comment by LFeh** [comment]
Errei ;)

**Comment by paulo101977** [comment]
Boa tarde. É home office?

**Comment by iuato** [comment]
A vaga é presencial.

**Comment by ribeiroevandro** [comment]
Gostei dessa vaga hein, vou mandar email ❤️

**Comment by Marcelosilva10** [comment]
vou mandar opa

**Comment by eduardojmatos** [comment]
@iuato fala mano! Já preencheu a vaga? Nos avise pra mantermos ou removermos da lista :)
