### ISSUE TITLE
[Barueri] Front-end Developer SR at Wtime 

### ISSUE THREAD

**Issue by AnieliFernanda** [frontendbr/vagas#870]
# **# Front-end Sênior** 

**Local:**
Alphaville - Barueri /SP 
Irá atuar no cliente.

**Experiência em:** 
-  HTML5;
-  JS;
-  CSS3;
-  VUE.js;
-  Sass;
-  Mocha.

**Desejável:** 
Conhecimento em Angular JS;
Experiência na área da saúde.

**Modalidade de contratação:**
PJ ou CLT - à combinar

**Nossa empresa:**
A Wtime Business Intelligence It, uma consultoria que oferece serviços em tecnologia da informação.
www.wtime.com.br

**Como se candidatar**
Favor enviar um e-mail para anieli.fernanda@wtime.com.br com seu CV anexado - enviar no assunto: Vaga Front-end Sênior

## Labels

- Alocado
- CLT
- PJ
- Sênior

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
