### ISSUE TITLE
[São Paulo] Front-End Developer Ruby on Rails Sr na [CAPITANI]

### ISSUE THREAD

**Issue by CAPITANIVAGAS** [frontendbr/vagas#871]
## Descrição da vaga

Atividades: Atuar no desenvolvimento de novos projetos, manutenção e evolução de sistemas utilizando Ruby on Rails, analisar, prospectar e desenvolver sistemas baseados em metodologias ágeis e arquiteturas. Desenvolver interfaces para browser usando HTML5, CSS3, Bootstrap e jQuery. Flexibilidade para integrar ou adequar sistemas desenvolvidos em outras linguagens. Requisitos Necessários/Desejável - Ruby on Rails utilizando MySQL, Linux - Conhecimento de arquitetura orientada a objeto, Service-Oriented Architecture (SOA), API Development, HTML/HTML5/CSS. - Inglês intermediário

## Local

São Paulo - Sacomã - Zona Sul

## Benefícios

Seguro de Vida Porto Seguro , – Auxílio Creche: Disponível para filhos de 0 à 5. 
Assistência Médica Assist. Odontológica ,Vale Refeição, Vale alimentação, Vale Transporte 

## Contratação

CLT

## Como se candidatar

Por favor envie um email para adriana.pollezi@capitani.com.br com seu CV anexado - enviar no assunto: Vaga RUBY

## Labels

- CLT
- Pleno
- Sênior

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
