### ISSUE TITLE
[São Paulo] Dev JavaScript (Redux, React.JS, Node.js) na Celebryts

### ISSUE THREAD

**Issue by stavarengo** [frontendbr/vagas#872]
_`Sugestão de labels: Alocado, CLT, PJ, Sênior`_
## Descrição da vaga

Estamos em busca de desenvolvedores com experiência para trabalhar em nossa startup. Não importa a formação, o que importa é o talento e a vontade de fazer parte de um time cujo intuito é desenvolver uma plataforma inovadora para o mercado. Hoje, a Celebryts desenvolve uma plataforma completa para agências e grandes anunciantes encontrarem e contratarem influenciadores. Entre os nossos leads estão as principais agências do Brasil, além de publicações em veículos relevantes, como Meio & Mensagem, Mundo do Marketing, Globo News, e outros.

Conheça a Celebryts: www.celebryts.com.

## Local
Nosso escritório localiza-se no coworking Developer E-Commerce HUB, ao lado do metrô Sumaré. Como estamos no mesmo prédio da iMasters e outras empresas, temos acesso a todos os eventos, sem contar o network com o pessoal que passa pelo espaço.

[Rua Oscar Freire, 2379 - Pinheiros](https://goo.gl/maps/3pW1PXokRP72)

## Benefícios
- Vale refeição;
- Vale transporte;
- Em alguns casos, você pode entrar no modelo de stock options da empresa.

#### Diferenciais
- Você faz o seu horário;
- Máquinas de fliperama e mesa de snooker espalhadas pelo prédio \o/;
- Linux, PC ou MAC, é só escolher. Se preferir, você pode usar o seu :);
- Todos os nossos robôs de busca têm nomes de personagens do Tolkien - hahaha; 
- Nosso office é muito legal :), com direito a biscoitinhos, frigobar, máquinas de expresso, etc., etc., etc.!

## Requisitos

**Obrigatórios:**
- Experiência com ReactJS e ES6:

**Desejáveis:**
- Experiência com NodeJS e/ou Redux e/ou ExpressJS;
- Que já tenha feito projetos bacanas. Queremos ver seu portfólio, projetos e afins. 

## Contratação
CLT ou PJ (você escolhe)

## Nossa empresa

A Celebryts é uma plataforma que auxilia empresas e agências a encontrarem influenciadores (YouTubers, Instagrammers, etc.) ideais para suas campanhas de marketing. Tudo é "self service": o cliente conduz as buscas, os planos e as contratações. Nossos robôs de busca analisam constantemente grande quantidade de informação de perfis impactantes para encontrar os influenciadores, e entregam relatórios completos acerca de onde os influenciadores atuam. O mais legal é que todas essas informações são coletadas organicamente pelo nosso algoritmo. Trate-se de projeto instigante e desafiador. 

## Como se candidatar

Envie um email com o assunto `Job JS - frontendbr` para rafael@celebryts.com.

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
