### ISSUE TITLE
[Belo Horizonte] Front-end Developer na DialHost

### ISSUE THREAD

**Issue by flaviohcardoso** [frontendbr/vagas#874]
## Descrição da vaga

Se você é um desenvolvedor faminto por desenvolver e otimizar produtos em um processo de ciclo contínuo e evolutivo, esta pode ser sua equipe.

Nós somos uma empresa que presa a evolução dos nossos produtos juntamente com um atendimento eficaz a todos os nossos clientes oferecendo soluções de datacenter que atendam suas necessidades de forma simples e transparente. Por isto estamos buscando um desenvolvedor que possua empatia e comprometimento para auxiliar nossos colaboradores e clientes discutindo e buscando as melhores opções para garantir uma experiência excepcional no atendimento ao cliente. 

Acreditamos que em nosso time, você não trabalhará sozinho e que um problema nunca é somente de um colaborador, ele é de todos da empresa.

## Local

Escritorio em Belo Horizonte, bairro California

## Benefícios

Não ter chefe :)
Uma equipe de alto nível, comprometidas e colaborativa.
Salário compatível com o mercado.
Plano de Saúde.
Vale Refeição.
Vale Transporte.
Lanche na empresa.
Ambiente agradável.
Horário Flexível.
Estilo próprio para trabalhar.
Auxilio para pagar sua faculdade.
Diversos cursos online disponibilizados pela empresa.

## Requisitos

- HTML5, CSS3 (SASS) e JavaScript Intermediário para Avançado;
- Frameworks frontend (VueJS, Bootstrap e jQuery);
- Experiência com utilização do Git;
- Conhecimento basico em PHP;
- Ser focado em objetivos e resultados.
- Proatividade e dinamismo ;)
- Ter carinho e ser apaixonado pelo seu trabalho.

**Para esta vaga iremos aplicar um teste simples e prático para que você possa demonstrar suas qualidades.**

## Contratação

CLT

## Como se candidatar

http://jobs.dialhost.com.br/o/frontend-developer

## Labels

- CLT
- Estágio
- Júnior
- Pleno
- Sênior

**Comment by felipecesr** [comment]
Remoto?

**Comment by flaviohcardoso** [comment]
@felipecesr a vaga é somente presencial em Belo Horizonte

**Comment by DanielLCintra** [comment]
@flaviohcardoso Mandei o currículo, sou de BH.

**Comment by flaviohcardoso** [comment]
Show @DanielLCintra ... Iremos lhe dar um feedback lá pela vaga.

**Comment by GiulianoMartins** [comment]
Currículo enviado !
