### ISSUE TITLE
[São Paulo] Front-End Developer na eComanda

### ISSUE THREAD

**Issue by alexandrereyes** [frontendbr/vagas#875]
## Descrição da vaga
Oportunidade para trabalhar na reformulação de todo nosso front-end, já temos design e um pouquinho de código react/redux, mas ainda tem muito trabalho pela frente :) O objetivo é aumentar a taxa de conversão dos leads que testam nossa plataforma. Você será premiado por cada progresso na taxa trial/cliente.

## Local
Remoto ou Escritório, São Paulo - Tatuapé

## Benefícios
- VR
- VT (quando alocado)
- Prêmios por progressos

#### Diferenciais
- Horário flexível
- Café da manhã no escritório
- Ambiente descontraído
- Grande oportunidade de crescimento
- Video game (alguns campeonatos de Fifa rsrsrsrs)
- No dress code
- Home Office sempre que quiser

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento web
- HTML, CSS e JS
- React
- Redux
- Inglês (leitura)

**Desejáveis:**
- Boa noção de UX

**Diferenciais:**
- .Net/c#

## Contratação
PJ

## Nossa empresa
A [eComanda](http://www.ecomanda.com.br) é uma solução para bares, restaurantes, pizzarias, etc. que em menos de 3 anos cresceu mais 500%. Estamos revolucionando o mercado com soluções criativas e acessíveis para todos do mercado food.

## Como se candidatar
Por favor envie um email para frontenddev@ecomanda.com.br com seu CV anexado e pretensão salarial.
Texto de apresentação é um grande diferencial :)

## Labels

- Alocado
- PJ
- Pleno
- Remoto - Parcial
- Remoto - Total
- Sênior

**Comment by danlaurent** [comment]
Enviado. :)

**Comment by renanlara** [comment]
Curtir!

**Comment by willycamargo** [comment]
Ainda aberta?

**Comment by mcrisostomo** [comment]
Enviado!

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
