### ISSUE TITLE
[São Paulo] Front-End Developer SR na MANDAÊ

### ISSUE THREAD

**Issue by dgsweb7** [frontendbr/vagas#879]
**About Mandaê:**

Think "UPS without the trucks": Mandaê is reinventing parcel logistics through a digital platform that organizes the entirety of the parcel supply chain to deliver a seamless, high-quality and efficient parcel shipment service for SMBs in Brazil. We’re the first startup in the world taking this approach to logistics.

Our model is asset-light, working with players across each of the principal steps of the parcel supply chain: pickups, cross-docking, and last-mile transport. In a country where the national postal service is effectively the only shipping option for SMBs, Mandaê’s platform is the only one that allows them to use private transporters, helping SMBs save up to 35% on their shipping costs.

Our mission is to “Connect Stories” through logistics. We’ve shipped over 1 million packages and grown over 300% in each year of our existence. In 2018, we’re going to start expanding aggressively throughout Brazil, with a broader vision of expanding our model to other developing countries.

We're well funded with backing from some of Latin America’s top investors, including Monashees, Qualcomm Ventures, Performa, Valor Capital, Hans Hickler (former CEO of DHL Express-USA) and others.

Mandaê was selected to the 2015 Endeavor Startup Network, was winner of the ABComm Innovation in E-commerce Logistics Award in 2017, and winner of the São Paulo “Smart Cities” category of the 1776 Challenge Cup.

**About the role:**
We are looking for someone passionate about Front End engineering who likes to develop hybrid applications, using new web standards and who is pixel-detail oriented.

You will need to show a great deal of responsibility and have full autonomy in building the solutions. Your critical sense and determination are key factors you will bring into our development team where you will work on high-impact projects that affect millions of people's lives.

**Responsibilities:**
• Build and ship amazing customer experiences;
• Front-end and the back-end optimized integrations;
• You'll help plan the architecture of our frontend;
• Develop new user-facing products and optimize existing ones using both client-side as well as server-side languages and technologies;
• Take full ownership of projects from design to implementation and deployment;
• Propose new solutions to the team that improve processes and users experience within our products.

**Requirements:**
• 3+ years of experience in a web-developer role with AngularJS;
• Mastery of HTML, CSS, and Javascript;
• Experience with Node.JS, TypeScript;
• Experience in CSS preprocessors (eg SASS, SCSS, LESS);
• Strong web design aesthetic and solid understanding of the fundamentals of user experience, cross-browser and performance issues, and front-end frameworks;
• Able to rapidly execute mockups/wireframes with strong attention to pixel-level details;
• Experience with creating interfaces with UX focus;
• You love making things beautiful — polishing and refining the UI is important to you;
• A passion for emerging web standards, design systems and a desire to build well-engineered reusable front-end components for our living style guide;
• Experience with Agile/Lean (Kanban, SCRUM, RUP, XP);
• Experience debugging cross-browser compatibility issues;
• You promote best practices, great usability, and persistently push the limits of what browsers can do;
• Knowledge in Sketch, Illustrator, Photoshop, Invision are a plus.

**We Provide:**
• Opportunity to play a key role in building a fast-growing startup;
• Work with an incredible team that never settles, and have the opportunity to shape the organization;
• Competitive salary and a generous stock option package;
• Health insurance;
• Standard Brazilian transportation and meal allowances.

**Apply for this job:**
To apply for this position send an e-mail to vagas-ti@mandae.com.br with subject "Front-End Developer", along with your resume and a brief explanation as to why you’re right for this role at Mandaê.

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
