### ISSUE TITLE
[Sao Paulo] Desenvolvedor FrontEnd Sênior

### ISSUE THREAD

**Issue by joaovarandas** [frontendbr/vagas#88]
## Descrição da vaga

Se você é apaixonado por tecnologia e quer trabalhar em uma empresa inovadora, o momento é esse. A Plusoft, pioneira no desenvolvimento de soluções multicanais para a Gestão de Relacionamento com Clientes no Brasil, está ampliando o seu quadro de funcionários e buscando profissionais de frontend.  

## Local

Escritório, São Paulo - Brooklin

## Requisitos

**Obrigatórios:**
- Um perfil inovador, comprometido e focado na identificação e resolução de problemas. Irá atuar como arquiteto de soluções em frontend, prevendo melhores práticas, performance, reutilização, testes e escalabilidade;
- 6 anos de experiência com desenvolvimento Web;
- 2 anos de experiência com frameworks MVVM;
- Sólidos conhecimentos em JavaScript e arquitetura de serviços RESTful;
- Conhecimentos de pre-compiladores de CSS;
- Experiência com bancos de dados relacionais/não relacionais;
- Experiência de backend e disposição para desenvolver em outras linguagens;
- Conhecimento sobre integração contínua e os conceitos do Git;

**Diferenciais:**
- Conhecimentos avançados sobre os serviços da AWS;
- Conhecimentos avançados em Java;
- Certificações ou experiência relevante em outras áreas de tecnologia;
- Desenvolvimento mobile nativo e/ou híbrido;

## Contratação

CLT Cotas

## Nossa empresa

A Plusoft desenvolve soluções de atendimento e CRM, dentro do conceito de multicanalidade, proporcionando a melhor experiência ao cliente em todos os pontos de contato e, ao mesmo tempo, promovendo a redução dos custos operacionais.

http://www.plusoft.com.br

## Como se candidatar

Por favor envie um email para joaovarandas@plusoft.com.br com seu CV anexado - enviar no assunto: 
[frontendbr] FrontEnd Sênior

**Comment by LFeh** [comment]
Boa sorte ;)

**Comment by joaovarandas** [comment]
Vaga preenchida!

Obrigado pela ajuda.

**Comment by LFeh** [comment]
\o

**Comment by camilatigre** [comment]
@joaovarandas 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by joaovarandas** [comment]
Sim!


---
João Paulo Varandas
jpvarandas@gmail.com
+55 11 99889-2321
