### ISSUE TITLE
[Campinas] Front-End Developer na GoMakers

### ISSUE THREAD

**Issue by alexdiotto** [frontendbr/vagas#880]
## Descrição da vaga

Buscamos um Dev para nos ajudar na construção e sustentação de nosso produto (SaaS).
Sendo responsável por desenvolver interfaces e automatizar testes.

## Local

A vaga é full-time na empresa (negociável alguns dias em home-office). 
Estamos localizados na região de Campinas - SP.

#### Diferenciais

Horário flexível
Negociável alguns dias em home-office
Time com uma vontade absurda de evoluir

## Requisitos

**Obrigatórios:**
Experiência com ReactJS e ES6:

**Desejáveis:**
Experiência em escrita de testes unitários em javascript
Que já tenha feito projetos bacanas. Queremos ver seu portfólio, projetos e afins.

**Diferenciais:**
Produto da empresa, iniciando do zero e com tecnologia de ponta.

## Contratação

Salário R$ 7.000,00 PJ

## Nossa empresa

A GoMakers é uma Startup que em pouco mais de 1 ano atingiu a marca de 4000 clientes e estamos em um crescimento absurdo. 

Estamos muito empolgados com os resultados e vislumbrando ser a maior e melhor plataforma de Marketing Digital do Brasil, para isso precisamos montar um time de pessoas apaixonadas pelo que faz.

O profissional dessa vaga irá ser head e com grande potencial de crescimento junto conosco.

## Como se candidatar

Por favor envie um email para alex@gomakers.com.br com seu CV anexado

## Labels

- Alocado
- CLT
- PJ
- Pleno
- Remoto - Parcial
- Sênior

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
