### ISSUE TITLE
[São Paulo] Front-End Mobile Mobile na MANDAÊ

### ISSUE THREAD

**Issue by dgsweb7** [frontendbr/vagas#881]
**About Mandaê:**
Think "UPS without the trucks": Mandaê is reinventing parcel logistics through a digital platform that organizes the entirety of the parcel supply chain to deliver a seamless, high-quality and efficient parcel shipment service for SMBs in Brazil. We’re the first startup in the world taking this approach to logistics.

Our model is asset-light, working with players across each of the principal steps of the parcel supply chain: pickups, cross-docking, and last-mile transport. In a country where the national postal service is effectively the only shipping option for SMBs, Mandaê’s platform is the only one that allows them to use private transporters, helping SMBs save up to 35% on their shipping costs.

Our mission is to “Connect Stories” through logistics. We’ve shipped over 1 million packages and grown over 300% in each year of our existence. In 2018, we’re going to start expanding aggressively throughout Brazil, with a broader vision of expanding our model to other developing countries.

We're well funded with backing from some of Latin America’s top investors, including Monashees, Qualcomm Ventures, Performa, Valor Capital, Hans Hickler (former CEO of DHL Express-USA) and others.

Mandaê was selected to the 2015 Endeavor Startup Network, was winner of the ABComm Innovation in E-commerce Logistics Award in 2017, and winner of the São Paulo “Smart Cities” category of the 1776 Challenge Cup.

**About the role:**
Mandaê's mobile strategy is changing. We understand that in the current scenario we no longer need native applications. Native applications are complex to maintain and need to be installed locally and this affects how our customers relate to Mandaê and so we understand that PWA (Progressive Web App) are the best way forward.

This position is for Front-end Engineers who fully understand both the mobile app world (and how to interact with users on mobile) and the Web world (and how to connect to web-based software infrastructure). You will work on high-impact projects that affect millions of people's lives.

**Responsibilities:**
• Develop beautiful, responsive, ultra-fast, mobile-first web interfaces that are optimized for SEO;
• Interact closely with our designers, back-end, and mobile engineers to ensure flawless and fast implementation of complex applications;
• Work with new technologies (and multi-platform) web: Progressive Web Applications.

**Requirements:**
• 3+ years of experience in a web-developer role with AngularJS;
• Mastery of HTML, CSS, and Javascript;
• Experience with Google's Material Design, REST APIs;
• You are familiar with Progressive Web App and offline storage;
• Experience with Node.JS, TypeScript;
• Strong web design aesthetic and an understanding of the fundamentals of user experience, cross-browser and performance issues, and front-end frameworks;
• Experience with Agile/Lean (Kanban, SCRUM, RUP, XP).

**We Provide:**
• Opportunity to play a key role in building a fast-growing startup;
• Work with an incredible team that never settles, and have the opportunity to shape the organization;
• Competitive salary and a generous stock option package;
• Health insurance;
• Standard Brazilian transportation and meal allowances.

**Apply for this job:**
To apply for this position send an e-mail to vagas-ti@mandae.com.br with subject "Mobile Developer", along with your resume and a brief explanation as to why you’re right for this role at Mandaê.

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
