### ISSUE TITLE
[London or Barcelona] Front-End Developer na Deliverymates Europe

### ISSUE THREAD

**Issue by eduardo-romanino** [frontendbr/vagas#884]
# **Job Description**

Deliverymates is a solid startup in the field of the last mile logistics, with a passionate team of engineers. Our mission is to develop the perfect software for the final mile delivery, including all the related functionalities for fleet and schedule management, and intelligent route calculation.

Our tech office is based in Barcelona while the head office is based in London UK. Our current open positions are to work either in our offices or remotely.

We are currently looking for engineers for both backend and frontend, no matter if you are fullstack or you prefer pure backend.

DeliveryMates is part of OTL Group, a logistics company with an impressive portfolio of clients and employs over 1000 passionate and dedicated staff in the UK, Spain, Italy, Germany, Brazil and expanding.

We need you :-D

# **Place**

Remote or Presential

# **Requirements**

_Mandatory Requirements:_

- At least 2 years of experience with JavaScript
- Experience with React, React Native, Redux
- Experience with ES6, ES7
- Fluent English

_Nice to have:_

- Self-improvement potential
- Ability to quickly learn new technology
- Problem-solving skills
- Teamwork experience

# **Apply**

Apply here https://goo.gl/NURzyw

**Comment by danielGalvao** [comment]
@LFeh acho que é remoto também não?

**Comment by eduardo-romanino** [comment]
@LFeh Sim é remoto também

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
