### ISSUE TITLE
[São Paulo] Front-End Developer na [F.biz]

### ISSUE THREAD

**Issue by hankpillow** [frontendbr/vagas#885]
## Descrição da vaga

[Link da Vaga](http://www.fbiz.com.br/vagas#op-242031-desenvolvedor-frontend)

Estamos à procura de um desenvolvedor Front-end que seja talentoso, criativo e apaixonado por pesquisa, tecnologia e design. Que enxergue o valor dos detalhes seja em um projeto "eye-candy" experimental ou um portal / e-commerce.

Somos um time multi-disciplinar composto por UX, Front e Back-end que acreditam no melhor que cada tecnologia tem a oferecer. Não só viabilizamos os projetos mas temos papel ativo e decisivo na concepção criativa dos trabalhos. Para completar, cada membro da equipe tem a opção de trabalhar com MAC ou PC.

A F.biz é uma agência com mais de 17 anos e DNA 100% digital. Trabalhamos com grandes clientes como Unilever, Rico, Honda, entre outras.

Também somos organizados! Todas as contratações são CLT com benefícios de transporte, alimentação, refeição e um belo plano de saúde com cobertura odontológica. Temos plano de carreira de longo prazo e trabalhamos com processos flexíveis que nos ajudam a organizar o dia-a-dia com mais eficiência, colaboração e menos burocracia.

Além dos conhecimentos técnicos e trabalhos, queremos saber *quem* é você pois acreditamos que cada nova pessoa adiciona algo único ao time.

Se você acha que tem o perfil para a vaga, preencha o [formulário](http://www.fbiz.com.br/vagas#op-242031-desenvolvedor-frontend) com seu currículo e portfólio (ou 3 melhores trabalhos) e venha tomar um café com a gente!

## Local

Rua João Moura, 1144 São Paulo - SP

## Benefícios

- Plano de saúde
- Plano odontológico
- VR 

## Requisitos

• Experiência com HTML5, CSS;
• Pré-processadores de CSS como LESS, SASS, Stylus, PostCSS, etc;
• Conhecimento íntimo entre os browsers;
• Javascript;
• Bom acabamento;
• GIT;
• Inglês (escrita e conversação);
• Automatizadores como Grunt, Gulp, Webpack etc.

**Diferenciais:**

• Iniciativa, criatividade, colaboração;
• Debug;
• OOP, design patterns;
• Command-line;
• Automatização de processos;
• Projetos pessoais.

## Como se candidatar

Preenchendo [esse formulário](https://fbiz.recruiterbox.com/jobs/fk0f5zg?cjb_hash=O_qNYA87&apply_now=true)

## Labels

- Alocado
- CLT

**Comment by hankpillow** [comment]
vaga fechada. obrigado a todos que participaram do processo.

**Comment by LFeh** [comment]
Boa @hankpillow
