### ISSUE TITLE
[São Paulo] Front-end Creative na Red Ventures

### ISSUE THREAD

**Issue by elvisdetona** [frontendbr/vagas#887]
## Descrição da vaga

Nós procuramos por desenvolvedores(as) front-end que irão trabalhar criando aplicações complexas que funcionam em vários dispositivos e palavras como performance e mobile-first serão parte de sua rotina. Você trabalhará com designers, analistas, engenheiros e outros desenvolvedores em um ambiente onde você pode ver o impacto de suas idéias.
A Red Ventures lhe dará a oportunidade de inovar e tomar decisões significativas à medida que você continua a desenvolver suas habilidades.

## O que você irá fazer

- Planejar, desenhar e construir soluções para algumas das maiores marcas do mundo.
- Trabalhar junto com desenvolvedores, designers e analistas diariamente.
- Colaborar com todo o time não só criando aplicativos simples e eficientes, mas também dando idéias e identificando melhorias nas soluções desenvolvidas.
- Capacidade de articular conceitos técnicos e soluções para partes interessadas não-técnicas.
- Criar e evangelizar padrões de código, bibliotecas e componentes de UI para uso interno (incluindo facilitar code review, documentar padrões e exemplos de código e ajudar novos desenvolvedores a crescerem profissionalmente).

## Requisitos

- Demonstrar compromisso para aprendizado e melhoria continua.
- Ter Sólidos conhecimentos com design responsivo, sempre procurando por breakpoints que sua UI necessite, para chegar em uma ótima experiência do usuário final.
- Animações e interações UI são fundamentais em qualquer parte do projeto.
- Considerar qualquer detalhe da interface importante e terá o desafio de construir interfaces complexas.
- Ter familiaridade com arquiteturas CSS populares, como BEM <3, rscss.
- Entender a importância e amar ouvir o termo: style guide.
- Profundos conhecimentos e experiência com estrutura CSS: você está sempre pensando como melhorar seu codigo e manter um CSS modular e escalável.
- Saber o quão divertido e incrível é manipular um SVG.
- Conhecer a base fundamental de Javascript.
- Tem experiência em formatar e manipular o DOM com dados retornados de uma API.
- Se sentir confortável em se comunicar em inglês, já que irá trabalhar com designers e desenvolvedores de todos os lugares do mundo.

**Plus**

- Familiaridade com Canvas ou WebGL.
- Experiencia com React.

## O que mais você precisa saber

- Plano de carreira estruturado com sessões de feedback recorrentes.
- Ambiente de trabalho informal, transparente e que preza pela colaboração e respeito às pessoas de diversas origens, escolhas e culturas.
- Incentivo educação: valor semestral pra você utilizar da maneira que quiser e buscar mais conhecimentos.
- Exposição direta ao time de engenharia global da Red Ventures em Charlotte
- Incentivo à prática de atividade física: organizamos caminhadas/corridas entre os times e também temos uma parceria com o Gympass
- Red Adventure - de tempos em tempos, reunimos todo o time da RV em uma atividade fora do escritório (já teve Kart, Arco e Flecha, Escape 60)
- Liberdade para ajudar a construir uma cultura de desenvolvimento cada vez melhor.
- Convênio de saúde acima do mercado.
- Bônus financeiro anual por performance.

## Sobre a Red Ventures

A Red Ventures é a maior plataforma habilitada para tecnologia do mundo para aumentar as vendas e otimizar o ciclo de vida completo do cliente. Possuímos todo o funil de marketing direto para nossos parceiros da marca Fortune 500 - desde a geração de demanda até o fechamento da venda. Nossa experiência abrange várias indústrias, incluindo serviços domésticos, energia, serviços financeiros, seguros e software.
O time de Front-end faz parte do time de Tecnologia, que é responsavel por desenvolver e manter aplicações complexas, robustas e com alta performance com outros times de engenharia da Red Ventures. Esta posição tem alta visibilidade e potencial para impactar a organização, participando diretamente para contruir e entregar soluções para nossos parceiros.
Nossa cultura é baseada em liberdade, você será livre para executar, testar e aprender e você terá a responsabilidade de se auto gerenciar num ambiente colaborativo e ágil. 
Você terá a oportunidade de se desafiar e crescer. Você poderia pensar no melhor dos dois mundos: trabalhar em um ambiente de start-up dinâmico no Brasil e, ao mesmo tempo, ser apoiado por uma empresa de tecnologia global líder em um ambiente de carreira disruptivo, empreendedor e acelerado.

## Como se candidatar

Candidate-se: https://grnh.se/vcarwhec1

**Comment by thebarry** [comment]
@elvisdetona É necessário ter uma formação superior?

**Comment by elvisdetona** [comment]
@thebarry Não precisa ter formação superior 🗽

**Comment by arthurfigueiredo** [comment]
Aceita remoto?

**Comment by elvisdetona** [comment]
@arthurfigueiredo Não.
