### ISSUE TITLE
[Rio de Janeiro] Front-End Developer na Profite - 2 Vagas

### ISSUE THREAD

**Issue by bruunas** [frontendbr/vagas#888]
## Descrição da vaga

Você conhece a Profite? Nós somos a maior agência implantadora de e-commerce do Brasil. Temos como clientes grandes nomes, tais como: O Boticário, Tim, C&A, Shopfácil, Electrolux, Havaianas, Mizuno entre outros.

Estamos procurando um(a) Desenvolvedor(a) Front-end Pleno, com sólidos conhecimentos em HTML, CSS e Javascript para projetar interfaces e entregar a melhor experiência para os consumidores visando sempre a otimização do código e agilidade no desenvolvimento.

O perfil que procuramos é de uma pessoa que seja atenta aos detalhes e capaz de desenvolver soluções escaláveis. De fácil relacionamento, organizado(a) e comprometido(a) com prazos e qualidade das entregas. Confira abaixo mais informações da vaga.

## Local

Escritório, Rio de Janeiro - Centro

## Benefícios

- Vale-transporte;
- Vale-refeição;
- Vale-alimentação;
- Plano de saúde e odontológico;

#### Diferenciais

- Folga de aniversário
- Chopp grátis
- Estrutura irada do WeWork com vista para a Marina da Glória
- Plano de Carreira
- Cursos (Alura, Udemy ..)

## Requisitos

**Obrigatórios:**
- Html5, css3;
- Javascript, jquery;
- Git;
- Grunt;
- Sass;
- Sites responsivos;
- Cross-browser (IE10+);
- Iniciativa, criatividade e colaboração;
- Boas práticas: reutilização de código, semântica, organização, performance.

**Desejáveis:**
- Experiência com CMS
- Conhecimento/Experiência em Vtex
- React

## Contratação

CLT a combinar

## Como se candidatar

Para se candidatar a vaga, mande um email para dp@profite.com.br com o seu currículo e o link do seu portfólio e com o assunto “Vaga Front-End”.

## Labels

- Alocado
- CLT
- Pleno
- Sênior

**Comment by antoniotex** [comment]
Vaga irada!

**Comment by NataliaAvila** [comment]
Que vaga sensacional!

**Comment by renanroberto** [comment]
Vaga maneira!

**Comment by ingridtartaglia** [comment]
Tive o prazer de trabalhar na Profite em 2016 e super recomendo :)

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
