### ISSUE TITLE
[Porto Alegre] Front-End Developer na ilegra

### ISSUE THREAD

**Issue by jtrivelin** [frontendbr/vagas#889]
## Descrição da vaga

Uma dos maiores grupos de empresas do país está executando uma ação social de abrangência nacional! Venha fazer parte deste projeto que terá enorme visibilidade e venha fazer a diferença no Brasil!

Você é um DEV Front End com experiência em React e tem muita proatividade? Vem nos ajudar a conduzir este trabalho!

O profissional deve conhecer não apenas código, como React e bibliotecas, MySQL e linguagens relacionadas, mas também deve possuir experiência de aplicação e utilização na prática. Deve conhecer padrões de arquitetura de código, e disponibilidade para algumas viagens.

Área: Desenvolvimento

Perfil: Pleno

Qualificações: Conhecimentos em React e bibliotecas relacionadas. Banco de dados relacional (pelo menos um: MySQL, Oracle, Postgres, etc).

## Local

Porto Alegre- RS

## Benefícios

- Plano de saúde
- VR 
- VA
- VT

#### Diferenciais

- sala de jogos
- possibilidade de trabalhar com novas tecnologias 

## Contratação

CLT 

## Nossa empresa
 uma empresa global de TI e negócios que tem uma abordagem baseada em pensar antes e além do software e que ajuda seus clientes a inovar e a crescer.

Está há mais de 15 anos no mercado, atendendo empresas líderes de segmento e construindo parcerias estratégicas como a Oracle, a Google. A ilegra se considera uma empresa sem fronteiras que atende clientes globais. Hoje conta com quatro escritórios: a sede em Porto Alegre , São Paulo , Toledo, no Estado de Ohio, e em Miami no Estado da Flórida (EUA).

A ilegra se identifica com empresas que pensam grande, que querem projetar novos produtos, serviços e novas formas de ofertá-los. Além de idear e conceber soluções inovadoras, é movida por desafios tecnológicos tanto na área de desenvolvimento de software quanto na área de sustentação de ambientes.

Pensando além, a ilegra traz para a TI e os negócios a criatividade, transparência e o espírito empreendedor. A companhia acredita no potencial das pessoas e em fazer para as pessoas, sempre buscando o novo. Por isso, também está entre os melhores lugares para se trabalhar no Brasil, pelo Instituto Great Place to Work.

## Como se candidatar

Por favor envie um email para curriculos@ilegra.com com seu CV anexado - enviar no assunto: Vaga Front-End React

## Labels

- CLT
- Pleno
- Remoto - Parcial

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
