### ISSUE TITLE
[Sao Paulo - Freela] Desenvolvedor Fullstack Java

### ISSUE THREAD

**Issue by highlabs** [frontendbr/vagas#89]
## Descrição da vaga

Concluir projeto em Java até o final de Agosto (2016). Com entregas semanais via git.

## Local

Remoto ou Escritório em SP (próximo ao metrô Paraíso)

## Benefícios [caso alocado]

- Horário flexível
- Café
- Ambiente divertido e grande

## Requisitos

**Obrigatórios:**

- Pleno+ em Java e HTML/CSS
- Criação de REST Api
- API Google Maps
- Git (orly? XD)

**Desejáveis:**

- Conhecimento em frameworks Javascript (Angular, React, VueJS)
- SASS/PostCSS
- ESLint
- Webpack
- Scrum
- Push notification

## Contratação

Freelancer, necessário emitir nota.

## Nossa empresa

A 5 ERA é um grupo que nasceu com base nos pilares da 5ª era da tecnologia, a era da computação cognitiva, oferecendo inovação para contar histórias e proporcionar experiências para marcas e pessoas, trazendo resultados com base no que há de mais moderno neste período de constante mudança e evolução tecnológica em que vivemos.

## Como se candidatar

Enviar email para rh@5era.com, com o assunto: [Github - Freela] + SeuNome

**Comment by willianjusten** [comment]
@highlabs Qual seria o nível requerido?

**Comment by highlabs** [comment]
@willianjusten Pleno + :)

**Comment by willianjusten** [comment]
Prontinho, marquei Alocado também.

**Comment by highlabs** [comment]
Pode fechar essa, galera! :)

**Comment by LFeh** [comment]
\o

**Comment by camilatigre** [comment]
@highlabs 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
