### ISSUE TITLE
[Porto Alegre] Front- End Developer na ilegra 

### ISSUE THREAD

**Issue by jtrivelin** [frontendbr/vagas#890]
## Descrição da vaga

Área: Desenvolvimento

Perfil: Pleno/Sênior

Local de Trabalho: Porto Alegre (RS)

Descrição: Você quer trabalhar com uma empresa internacional com um projeto de blockchain?! Venha fazer parte deste projeto super importante!

Você é um DEV front end com experiência em Magento e Angular ou React?! Tem muita proatividade e já trabalhou como DevOps? Vem nos ajudar a conduzir este trabalho repleto de desafios técnicos!

O profissional deve conhecer não apenas o Magento, mas também código nestas linguagens. Ter noções de metodologias ágeis, banco relacional e linguagens relacionadas, mas também deve possuir experiência de aplicação e utilização na prática. Deve conhecer padrões de arquitetura de código, e ser muito pró ativo e estudioso!

Qualificações: Conhecimento em React ou Angular; Magento ; Inglês é obrigatório!!!

## Local

Porto Alegre- RS

## Benefícios

- Plano de saúde
- VR 
- VA
-VT

## Contratação

CLT

## Nossa empresa
A ilegra é uma empresa global de TI e negócios que tem uma abordagem baseada em pensar antes e além do software e que ajuda seus clientes a inovar e a crescer.

Está há mais de 15 anos no mercado, atendendo empresas líderes de segmento e construindo parcerias estratégicas como a Oracle, a Google. A ilegra se considera uma empresa sem fronteiras que atende clientes globais. Hoje conta com quatro escritórios: a sede em Porto Alegre , São Paulo , Toledo, no Estado de Ohio, e em Miami no Estado da Flórida (EUA).

A ilegra se identifica com empresas que pensam grande, que querem projetar novos produtos, serviços e novas formas de ofertá-los. Além de idear e conceber soluções inovadoras, é movida por desafios tecnológicos tanto na área de desenvolvimento de software quanto na área de sustentação de ambientes.

Pensando além, a ilegra traz para a TI e os negócios a criatividade, transparência e o espírito empreendedor. A companhia acredita no potencial das pessoas e em fazer para as pessoas, sempre buscando o novo. Por isso, também está entre os melhores lugares para se trabalhar no Brasil, pelo Instituto Great Place to Work.

## Como se candidatar

Por favor envie um email para curriculos@ilegra.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor Front-End Blockchain

## Labels

- Alocado
- CLT
- Pleno
- Sênior

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
