### ISSUE TITLE
[São Paulo] Front-End Developer na [Stoodi]

### ISSUE THREAD

**Issue by vsoaresbruno** [frontendbr/vagas#895]
## Descrição da vaga

Estamos à procura de um desenvolvedor(a) Front-end que seja talentoso(a), criativo(a) e apaixonado(a) por pesquisa, tecnologia e design.

Somos um time multi-disciplinar composto por UX, Front e Back-end que acreditam no melhor que cada tecnologia tem a oferecer.

Nessa função, você será responsável por planejar, construir e manter o site, sempre pensando em performance (web e mobile);

## Local

Escritório, São Paulo - Butantã (Ao lado do metrô)
• Presencial

## Benefícios

• Plano de saúde
• Plano de odontologico
• VR
• VT

## Diferenciais
• Prezamos pela qualidade de vida
• Não trabalhamos com pessoas chatas
• Aux. educacional (cursos, palestras, etc).

## Requisitos
• Ter trabalhado em projetos escaláveis;
• Experiência com HTML5, CSS;
• Pré-processadores de CSS como LESS, SASS, Stylus, PostCSS, etc;
• Conhecimento íntimo entre os browsers;
• GIT,
• JavaScript vanilla, JQuery
• Integração com API;
• Automatizadores como Grunt, Gulp, Webpack etc.

**Obrigatórios:**
- 3 a 4 anos de experiência com CSS/JS

**Diferenciais:**
• noções de UX;
• conhecimentos em Django
• conhecimentos ES6
• React, AngularJS e Angular;

## Nossa empresa

O [Stoodi](http://www.stoodi.com.br) nasceu com o propósito de democratizar o acesso à educação de qualidade a todo e qualquer estudante brasileiro.

Recentemente, nos juntamos ao [Grupo Somos Educação](http://www.somoseducacao.com.br), maior companhia de educação básica do Brasil, para maximizar o alcance do nosso propósito e, juntos, construir nossa visão transformacional para a educação do país.

Nossos próximos anos serão bastante ambiciosos diante de tudo que queremos construir. Temos muitas hipóteses que precisamos validar e algumas certezas já estão claras: somente com gente extremamente comprometida, talentosa, transparente, e que trabalhe duro e seja preocupada em deixar um legado para o país, é que vamos ter êxito nessa jornada.

Por isso gostaria de te convidar para nos conhecermos melhor e quem sabe podermos construir isso juntos.

## Como se candidatar

Por favor envie um email para bruno@stoodi.com.br com seu CV anexado ou LinkedIn + Bitbucket/Github -  
Assunto: Front-end

## Labels

- CLT
- Pleno
- Sênior
- Presencial

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
