### ISSUE TITLE
[BERLIN] Sr. Software Engineer (Frontend) na Careship GmbH

### ISSUE THREAD

**Issue by klederson** [frontendbr/vagas#896]
## Descrição da vaga

Along with other inspiring/inspired developers, you’ ll help us to build a scalable company by developing an amazing platform using the latest technologies as well with a great architecture, following good practices such as SOLID and in an truly agile environment. By practicing agile and Test-Driven Development practices, as well as Functional and Behavioural Testing, your implementation of new technologies will help us to grow and prepare it for new exciting markets.

In an motivating environment you’ll have the chance to see your daily work impacting the business development and you’ll be a important part in this transformation process.

We’re not looking for solo rock stars, we’re looking for great and promising talent and team player to also inspire us back, to learn and teach, to aggregate.

# Dia-a-Dia

- Help to implement our new platform, as well as influence and design new projects
- Build next-generation web applications with a user-centric approach
- Support designing and implementing APIs
- Support designing and implementing PWA’s and SPA’s
- Constant learning process and changing/adapting to new challenges
- Develop engaging tools for customers using the power of the modern technologies for client-side apps
- Working closely with a team focused on quality code and standard practice
- Ensuring high-quality output that is efficient and delivered on time
- Helping us innovate by contributing new ideas and knowledge
- Ensure good level of code quality and good practices
- Architecture and Design new solutions for our ecosystem, tools, business

# Requisitos

- An expert in Javascript/Css with 6+ years of relevant experience in front-end development
- Experienced in VueJS and NodeJS development and good practices (SOLID, KISS, etc)
- Having a deep understanding of Javascript, EcmaScript 6+, Sass, Object Orientation, Clean Code and Design Patterns
- Having good knowledge in data modeling, design patterns
- Experienced in agile development ( Scrum and Kanban )
- Experienced with RESTful Applications
- Having great analytic vision and software architecture capabilities
- Fluent in English
- Team-oriented
- Nice to know but not required:
	- Typescript
	- WebSockets
	- Push Notifications
	- Javascript Workers
	- DDD
	- BDD
	- VueJS
	- NodeJS
	- Message Queue Systems/Development

## Local

Careship GmbH
Berlin
Germany

REMOTE IS NOT POSSIBLE :(

**Diferenciais:**

Damos todo o suporte para visto e mudança além claro de toda a ajuda logística para se virar num novo país, estamos contratando ASAP então esteja preparado, sem bullshit, se você é bom a vaga vai ser sua ;)

Além disse o ambiente e cultura são excepcionais, pessoas motivadas e fantásticas além de muito amigáveis e engajadas no produto da empresa ( que tem um viés social bacana ).

## Contratação

Contrato Permanente
Visto de Trabalho / Blue Card ( ou se você tem passaporte europeu ... é isso aí só vir )

## Nossa empresa

At Careship, we help families find the right caregiver for their loved ones so that they can age at home with joy. Fueled by convenience, quality and best-in-class user experience, we are combining technology with a human touch to increase the quality of life of our parents and grandparents.

## Como se candidatar

Se candidata aqui pelo link:

https://careship-jobs.personio.de/job/56327?language=en#

ou se está com preguiça manda um email com seu CV para: 

jobs@careship.de.

## Labels

- Alocado
- CLT
- Sênior
- VueJS
- ReactJS
- Arquiteto
- Hackathons
- Germany
- Berlin

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
