### ISSUE TITLE
[São Paulo] Front-End Developer na Liv Up

### ISSUE THREAD

**Issue by luizarakaki** [frontendbr/vagas#898]
## Descrição da vaga

Participar da equipe de otimização de conversão da Liv Up, trabalhando numa equipe multidisciplinar com designers, engenheiros, desenvolvedores e analistas. Nosso front é em React e back em Node.js.
Você trabalhará desenvolvendo soluções para problemas identificados por clientes e implementação de features.

## Local

Rua Amaro Cavalheiro, 158, São Paulo - Pinheiros

## Benefícios

- Seguro de vida
- VT de R$ 175/mês
- VR de R$ 20/dia
- Gympass

## Requisitos

**Obrigatórios:**
- Experiência em desenvolvimento front-end com framewords modernas de JS.
- Fit cultural em ambiente de startups

**Desejáveis:**
- conhecimentos em React

**Diferenciais:**
- conhecimentos em Node.js
- conhecimentos em MongoDB

## Liv Up

A Liv Up tem crescido exponencialmente há dois anos, mudando o jeito com que as pessoas se relacionam com a comida. Parte fundamental da nossa estratégia é ter times fortes de tecnologia e de produto, responsáveis por conhecer e encantar o nosso usuário, garantindo sempre uma experiência incrível em nosso site, detectando e removendo barreiras.

Nosso sistema é em Node.js com o front em React. Captamos investimento do principal fundo da América Latina (Kaszek Ventures) para expandir ainda mais, temos crescido muito como equipe e o trabalho envolve contato direto com todas as áreas e participação direta nas tomadas de decisão.

## Contratação

CLT ou Estágio

## Como se candidatar

Aplicar em https://stowhire.com/liv-up/sp-front-end-developer-de9b

## Labels

- CLT
- Estágio
- Júnior

**Comment by LucasCastelo** [comment]
413 quando enviei minha inscrição com pdf de 5mb =/

**Comment by allancarlos123** [comment]
Há possibilidade de ser remoto @luizarakaki?
