### ISSUE TITLE
[Rio de Janeiro] Front-End Developer na Qconcursos.com

### ISSUE THREAD

**Issue by caioreis** [frontendbr/vagas#899]
## Descrição da vaga

Frontend, a Qconcursos te quer!

Tem de tudo um pouco! Quer trabalhar com um dos top `#170` sites mais acessados do Brasil, fazer interface e experiência para sistemas de IA e algoritmos bizarros de busca? Aqui você pode!

Buscamos pessoas que amam desafios e que buscam aprender sempre! Independente da sua experiência, se você se identifica com essa vaga, vem pra cá! Temos um ambiente totalmente diferenciado e estamos refazendo vários sistemas com foco máximo em uma experiência diferencial para o usuário.

Fazer isso pensando em 110 milhões de pageviews não é uma tarefa fácil e, na verdade, é bem desafiante. Por isso buscamos apaixonados por tecnologia para estarem a cada dia buscando novas soluções para implementar as propostas da nossa equipe de produto e resolver os casos de usuários que aparecem.

## Local

Escritório, Rio de Janeiro - Ao lado do metrô Presidente Vargas

## Benefícios

- Plano de saúde
- VR de R$ 28/dia
- Auxílio creche
- Bolsa parcial para graduação/pós/especialização depois de 1 ano de empresa
- Vale transporte
- Plano dentário

#### Diferenciais

- 2 horas de almoço
- monte a sua máquina como desejar
- ambiente de trabalho muito descontraído
- equipe de frontend de alto desempenho para trocar / aprender
- sala de jogos / video game
- horários flexíveis
- *ter milhões de pessoas acessando seu trabalho a um commit de distância*
- dia de pizza / bolo / salgadinhos
- proximidade da equipe de produto com foco em experiência do usuário
- plano de carreira

## Requisitos

**Obrigatórios:**

- HTML5
- CSS3
- LESS ou SASS
- Bootstrap
- JAVASCRIPT
- JQUERY
- GIT

**Desejável:**

- Ter experiência com Rails ou outra linguagem backend que utilize MVC
- Conceitos de como o Webpack funciona (usamos bastante)
- Gostar de design - Ser detalhista e preocupado com a experiência e interface que desenvolve para o usuário
- Ter trabalhado com Single Page Application (Angular, Vue ou React)
- Ter experiência com Gulp ou Grunt

**Diferenciais:**
- projetos opensource
- ser comunicativo
- gostar de aprender/ensinar
- construir códigos organizados que facilitam escala

## Contratação

CLT a combinar - Temos planos de carreira

## Nossa empresa

Somos a maior plataforma online de resolução de questões de concursos e cursos, voltada para apoiar os estudantes a alcançarem a aprovação em concursos públicos e a evoluírem na sua vida profissional por meio da educação.

Fizemos 10 anos em janeiro, temos mais de 800 mil questões de provas anteriores cadastradas em nossa base e mais de 6 milhões de usuários. Somos uma das marcas mais conhecidas e lembradas do mercado e temos o aval de grandes instituições.

## Como se candidatar

Por favor envie um email para vem@qcx.com.br com seu CV/Linkedin/Carta de Apresentação - enviar no assunto: Vaga Frontend. 

## Labels

- Alocado
- CLT
- Júnior
- Pleno

**Comment by salestayna** [comment]
Esse e-mail está voltando :/

Tem outro?

**Comment by ArieltonPires** [comment]
e-mail inválido!

**Comment by caioreis** [comment]
Resolvido pessoal, me desculpem!

**Comment by ArieltonPires** [comment]
sent!

**Comment by lgdevlop** [comment]
@caioreis esta vaga me chamou atenção, como o canto das sereias aos navegantes neste quesito: "...Buscamos pessoas que amam desafios e que buscam aprender sempre!..."
Venho da época que linux ainda era instalado no modo texto e quem trabalhava com TI, não tinha divisão de DevOps, Front, Back etc... O cara tinha que ser meio que um "Severino"...
Me afastei ta TI, mas nunca deixei de fazer meus scripts ou programas.
Posso estar enganado, mas o futuro tende a ser WebApps com AI...
Já programei desde Assembly 32bits, C, Java, VBA, entre outras.  Na época das famosas tabelas para o desenvolvimento web.
Costumo programar em qualquer linguagem que tenha um manual de referência =)
Estou focando meus estudos com cursos voltados a WebApps(HTML, Javascript, CSS, Vue, React, Gulp, Webpack,..) e Data Science.
SPA para mim parece poesia para quem viu o calvário que era programar para Web no passado.
Como supracitei acima, desafios e aprendizado é um binômio que se resume a minha pessoa e que me motiva!
Vou preparar um currículo, vai que de repente tem uma vaga aí para mim...
Forte abraço e sucesso para todos nós!
