### ISSUE TITLE
[Home Office] Desenvolvedor Front-End

### ISSUE THREAD

**Issue by priscillapimenta** [frontendbr/vagas#9]
## Descrição da vaga

Vaga de Desenvolvedor Front-End para desenvolvimento em vários projetos : sites, sistemas internos e externos.
Procuramos alguém que : 
- Tenha conhecimento em frameworks JavaScript ( jQuery, Angular, NodeJS , etc)
- Tenha experiência com controle de versão , como Git
- Produza código eficiente , escalável e reutilizável

## Local

Remoto

## Benefícios

- Plano de Saúde Nacional
- CLT

## Requisitos

1) Executar um teste técnico
2) Passar por um teste de DISC, que é a forma de identificarmos o seu perfil
3) Uma entrevista online comigo

## Contratação

CLT a combinar 

## Nossa empresa

 Somos uma empresa com pessoas jovens e de sócios jovens, 8 anos de mercado trabalhando com
 Cursos ( Formula de Lançamento) e Ferramentas para empreendedores digitais. 

Nossa estrutura é linear, caso  você venha trabalhar conosco, terá acesso a todos da empresa, inclusive aos sócios da IGD. 

Nosso time possui 30 pessoas trabalhando remotamente e nos encontramos 2 vezes por ano em Brasilia :).

## Como se candidatar

Como toda a nossa equipe trabalha online, precisamos avaliar o seu código e por isso temos o teste prático.
Nós temos 2 etapas para contratação, e são elas:

1) Executar um teste técnico
2) Uma entrevista online comigo
Então como primeiro passo segue o teste : 

https://bitbucket.org/klicksite/js-test  

Assim que finalizar, por favor envie um email para priscilla.pimenta@ignicaodigital.com.br - enviar no assunto: [Vaga Front-End] <seu nome>

**Comment by Mendrone** [comment]
Jr, Pleno, Sr?

**Comment by priscillapimenta** [comment]
Oi Vitor, tudo bem?

Vou te responder já te incluindo no nosso teste :)

O valor da vaga está de 2.300 - 4.500(CLT + Plano de saúde nacional), dependendo do seu código e entrega :D.

Somos uma empresa com pessoas jovens e de sócios jovens, 8 anos de mercado trabalhando com Cursos ( Formula de Lançamento) e Ferramentas para empreendedores digitais. 

Nossa estrutura é linear, caso  você venha trabalhar conosco, terá acesso a todos da empresa, inclusive aos sócios da IGD. 

Valorizamos o talento pessoal e é isso que cria as oportunidades de promoção :).

Acreditamos que o empreendedorismo pode mudar o Brasil e as pessoas,  essa é a nossa paixão.

O importante não é fazer 100% do teste e sim fazer bem o que vc sabe fazer  e mostrar no que é bom :)

Como toda a nossa equipe trabalha online nós temos 3 etapas para contratação, e são elas:

1) Executar um teste técnico
2) Passar por um teste de DISC, que é a forma de identificarmos o seu perfil
3) Uma entrevista online comigo

Então como primeiro passo segue o teste : 

Escolha entre : https://bitbucket.org/klicksite/js-test <https://bitbucket.org/klicksite/js-test>  

Prazo para entrega :  19/02

Ps. favor enviar um email quando o teste estiver ok.

Abs. Pri

**Comment by priscillapimenta** [comment]
oi @Mendrone, te mandei um email.. mas tudo depende do resultado do seu teste, com ele nós classificamos o seu nivel :).
Temos vagas para os 3.

**Comment by LFeh** [comment]
@diogomoretti :)

**Comment by ribeiroevandro** [comment]
@priscillapimenta email enviado...

**Comment by jaffarc** [comment]
@priscillapimenta  a vaga ainda esta aberta?

**Comment by vaniarosa** [comment]
Olá!  Ainda há vagas disponíveis?  :)

**Comment by urameshibr** [comment]
Oi @priscillapimenta , tudo bem? Eu sou dev back-end, trabalho com Laravel, Angular, Gulp, Twitter Bootstrap e sei me virar bem no front-end, full-time aqui, caso queira fazer um teste comigo, ou precisar de ajuda com php pode me contatar, jajá envio email pra você, ok?
Xau, abraço.

**Comment by vaniarosa** [comment]
Obrigada!
Em 11/03/2016 22:31, "urameshibr" <notifications@github.com> escreveu:

**Comment by priscillapimenta** [comment]
@vaniarosa e @urameshibr tudo bem ?
Por favor envie um email para priscilla.pimenta@ignicaodigital.com.br com seu CV anexado - enviar no assunto: [Vaga Front-End]
Nos falamos por la :D

**Comment by urameshibr** [comment]
Ok Priscilla, acabei de enviar meu currículo, espero nos vermos online.

**Comment by guigaoliveira** [comment]
Ainda há vagas disponíveis?

**Comment by vitornogueira** [comment]
Tem sim @guigaoliveira :wink:

**Comment by diegocandido** [comment]
Como anda o processo?

**Comment by DenysonSoares** [comment]
As vagas já foram preenchidas?

**Comment by LFeh** [comment]
A vaga foi preenchida? @priscillapimenta

**Comment by priscillapimenta** [comment]
Oi @LFeh me perdoe a demora, ainda temos vagas, porém agora vão ser para Brasilia. Podemos fechar esse :).

**Comment by LFeh** [comment]
Beleza! Pode abrir outra se quiser ;)

**Comment by camilatigre** [comment]
@priscillapimenta 

o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

**A pessoa que preencheu a vaga foi encontrada através desta issue?**
a) Sim
b) Não
c) Não tenho certeza
