### ISSUE TITLE
[São Paulo] Vaga Desenvolvedor Ruby on Rails Zona Leste Tatuapé

### ISSUE THREAD

**Issue by unixsistemas** [frontendbr/vagas#90]
## Descrição da vaga

Estamos contratando Programador(a) Ruby on Rails com experiência para integrar nosso time de trabalho.
## Local

Escritório, São Paulo - Tatuapé
## Benefícios

Vale Transporte + Vale Refeiçao
## Requisitos

 Ruby on Rails
- MySQL
- Heroku
- Git e Github
- Tdd/bdd
- Rspec e Capybara
- HTML, CSS e JavaScript
- Boostrap
- Garantir a qualidade do código entregue
- Comprometimento com os prazos combinados
  **Desejáveis:**
- conhecimentos em ruby on rails
- conhecimentos em C#

**Diferenciais:**
- Experiência no desenvolvimento APIs
- Experiência Elasticsearch (diferencial)
- Experiência Ember (diferencial)
## Contratação

PJ a combinar ou CLT a combinar 
## Nossa empresa

Empresa desenvolvimento ERP
## Como se candidatar

Por favor envie um email para desenvolvimento@unixsistemas.com.br com seu CV anexado - enviar no assunto: Vaga NodeJS

**Comment by willianjusten** [comment]
Opa @unixsistemas , coloquei algumas labels, se puder dizer melhor qual vai ser o nível, se é pleno mesmo...

**Comment by eduardojmatos** [comment]
@unixsistemas já preencheu a vaga? Nos avise pra mantermos ou removermos da lista :)

**Comment by dvmrabelo** [comment]
@unixsistemas, enfim posso fazer um contato com vocês, participei de uma seleção com vocês, fiz tudo que pediram, até os pontos que seriam diferenciais e não tive uma resposta, nem negativa, não precisava ser uma explicação, só uma msg no whatsapp ou no email dizendo "Não queremos você." já estaria bom.
