### ISSUE TITLE
Front-End Developer Sênior

### ISSUE THREAD

**Issue by GuilhermeAlvesLins** [frontendbr/vagas#900]
Front-End Developer

São Paulo Front-End Developer na (empresa de e-commerce do ramo automotivo)

- HTML, CSS3, Javascript, JQuery e Ajax, Json, BootStrap
- CSS Pre-Processors (LESS / Sass)
- ReactJS (JS framework) 
- Responsive / Adaptative Web Design 
- Sistemas de controle de versão Git
- Lógica de programação
- Ter atuado também com PHP, pois irá trabalhar junto à equipe de back-end.

Local: Vila Olímpia
Alocado no cliente.

Contratação PJ - Projeto por tempo indeterminado

Terceirização de Mão de Obra em Desenvolvimento de Software 
Projetos complexos exigem profissionais experientes e com competências específicas, o que torna a sua seleção um grande desafio. Há mais de uma década trabalhando com os principais players do mercado, a 5A Attiva é especialista em montar equipes de alta performance. Baseada na filosofia de todo o grupo 5A, de que pessoas fazem a diferença nas organizações, a 5A Attiva trabalha em três principais frentes: recrutamento, gestão e retenção de talentos.
Com agilidade e eficiência, seu objetivo é conectar os profissionais mais preparados do mercado às necessidades dos seus clientes nas áreas de Tecnologia da Informação. Em linha com aquilo que o cliente busca para os seus projetos, a 5A Attiva cuida também da sua gestão e inserção na sua cultura organizacional. Neste modelo, a equipe de RH da 5A Attiva trabalha em paralelo com o gerente de contas, auxiliando na capacitação dos profissionais e oferecendo ferramentas para a sua retenção. Também realiza avaliações e pesquisas de clima nas duas pontas, cliente e colaborador, de modo a obter o máximo de satisfação e produtividade.

Por favor envie um e-mail para guilherme.lins@5aattiva.com.br com seu CV anexado com pretensão salarial - enviar no assunto: Vaga de Front-end na Vila Olímpia

**Comment by LFeh** [comment]
Qual o nome da empresa que vai fazer a contratação?
