### ISSUE TITLE
[Munich - Alemanha] Frontend React JavaScript Developer at Personio

### ISSUE THREAD

**Issue by diegofaria** [frontendbr/vagas#901]
## Description

We seek for a creative problem solver with strong experience in latest frontend technologies and UX/UI design.
- Profound experience with React.js or similar frameworks
- Experience with task runners (Grunt/Gulp) and bundlers like Webpack
- Experience implementing RESTful clients
- Knowledge and understanding of best practices in SASS
- Understanding of distributed version control systems such as Git
- Strong written and spoken English
- Willing to relocate to Munich permanently

Nice to have:
- Ideally experience with PHP, SQL and templating engines
- Strong design and UI/UX skills
- Knowledge of package managers like NPM, Yarn, Bower

## Local

Munich - Germany.

## Benefits:

- Direct impact on the daily work of several thousand users
- A creative environment with talented and ambitious team members
- Relocation support to Munich
- Unu electric scooter of your choice as "company car" (see www.unumotors.com) or an additional payment for a yearly public transportation ticket
- Regular team events, including office dinners, skiing trips, and parties
- 1.500 EUR of development budget per year for attending conferences, courses, buying books
- High-end hardware, noise-canceling headphones
- 26 paid vacation days, and 2 days of home office per month
- Weekly German language courses
- Office in the heart of Munich (near Gärtnerplatz)

## Our company

Personio is a Market-proven, well-funded and fast growing company ($14.3M funding acquired to the date). Join our ambitious product and engineering team and take an active role in shaping the future of our product. You will be responsible for leveling up our UX by improving existing features as well as participating in the specification and implementation of new ones.
- Frontend development is driven by customer feedback
- Help us with the migration of existing application features to React.js

## Labels

- Relocation
- Germany

mail me: diego.faria@personio.de
or apply at our [career site](https://personio-jobs.personio.de/job/1725?language=en#).

**Comment by tunnes** [comment]
Oh gosh 💔

**Comment by vinyguedess** [comment]
Hi Diego, job is still available ?

**Comment by diegofaria** [comment]
yes, it is :)

**Comment by rduster** [comment]
Diego, mandei mensagem para você no LinkedIn. Abraço!

**Comment by zikelir** [comment]
wow! 😍

**Comment by diegofaria** [comment]
We are still hiring devs for this position :)

**Comment by diegofaria** [comment]
We are still hiring devs for this position!

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
