### ISSUE TITLE
[Remoto] Vaga Dev JS/Vue/Django/Python

### ISSUE THREAD

**Issue by matheus2740** [frontendbr/vagas#903]
Startup de consultoria política que se baseia na análise de dados legislativos, procura Front-End Developer para integrar equipe.

Requisitos:

- Front-end web development (Vue.js, Javascript, HTML5, CSS)
- Conhecimento em Bootstrap
- Conhecimentos de UX/UI
- Habilidades de comunicação verbal e escrita excelentes
- Disponibilidade de 40 horas semanais
- Experiência no desenvolvimento de front com consumindo backend em Django.

Habilidades desejáveis:
- Experiência em Python e Django
- Desenvolvimento de layout responsivo
- Desenvolvimento limpo/fluído e comentado

Sobre a equipe de trabalho:
- um time de profissionais com altíssima qualificação, entusiastas e com foco na inovação e pesquisa
- consultoria estratégica com vínculo a grupos de pesquisa da USP
- rigor acadêmico na construção das análises e indicadores.
- não fazemos lobby, nem indicamos quem faça.
- os resultados gerados têm fundamentos científico, ou seja, não arredondamos análises nem dados para satisfazer clientes.

Oferecemos:

- possibilidade de trabalhar remotamente, uma vez comprovado o comprometimento com o projeto. Estamos sediados em São Paulo.
- contamos com apoio de estatístico (acadêmico) para auxiliar na construção de partes do sistema.
- Salário a combinar.

Interessados, favor encaminhar currículo com pretensão salarial e portfólio para selecao@ellopolitico.com.br com o título: [Front-End PyDev]

**Comment by fabiomirandaa** [comment]
Parece ser muito boa

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
