### ISSUE TITLE
[ Alphaville ] 	Front-End Developer - 2 Vagas [ Compasso Tecnologia Ltda ] 

### ISSUE THREAD

**Issue by RudineiCosta** [frontendbr/vagas#904]
# **Sobre nós**

A Compasso é uma organização brasileira de serviços profissionais na área de TI, fundada em 1995, e especializada em desenvolvimento de software personalizado, manutenção, integração, teste e implementação.

Nosso principal objetivo é permitir a nossos clientes obter vantagens competitivas através aplicações de tecnologia de confiança, e de alto desempenho.

A partir de nossos escritórios em Porto Alegre, São Paulo e dos nossos Centros de Desenvolvimento de Software, a Compasso atende clientes líderes em seus setores de atuação, em diferentes segmentos da economia. Empresas nacionais e multinacionais tem confiado a gerência de seus projetos de TI voltados ao desenvolvimento de suas organizações para nossa equipe altamente qualificada.

As tecnologias utilizadas pela Compasso são reconhecidas mundialmente na implementação de projetos juntamente com as estratégias e diretrizes dos negócios de seus clientes, visando o atendimento das necessidades das mais diversas áreas de uma organização. Nesta visão, os resultados e benefícios dos clientes são viabilizados de uma estrutura organizacional montada pela empresa para cada necessidade.

Como fazemos:
Agile: Adotamos metodologias Agile de desenvolvimento de Software visando agilidade em suas entregas, transparência e comunicação facilitadas com os clientes e alta adaptabilidade à mudanças, desta forma minimizando os riscos de impactos nos negócios em seus projetos.

Digital Experience: Os clientes têm uma expectativa muito alta com a qualidade dos serviços, e isto exige que as empresas evoluam de forma constate para elevar a experiência digital ao topo.

Test Automation: A automação de testes possibilita garantimos maior agilidade e segurança nas entregas. Além da possibilidade de ser executada a qualquer hora do dia ou da noite.

DevOps: Acreditamos que resultados espetaculares surgem do uso das melhores práticas e ferramentas existentes e de um ambiente de confiança e colaboração em que todos perseguem objetivos comuns.

## **Nossas especializações**

Outsourcing, Integração, Implementação, Desenvolvimento, Consultoria, E-Commerce, Cloud, DevOps, Desenvolvimento Ágil, Gestão de Ambientes e Testes Automatizados

## **Local**
	
Escritório, Alphaville - SP

## **Benefícios**

- 	Vale-transporte;
- 	Vale-refeição;
- 	Plano de saúde e odontológico;

## **Requisitos**

Obrigatórios:

- HTML5, JavaScript, JQuery, CSS, Bootstrap, etc)
- Bootstrap 4
- Sass
- Vue JS 2
- Foundation for e-mails
- Webpack 3+
- ES6+
- Iniciativa, criatividade e colaboração;
- Boas práticas: reutilização de código, semântica, organização, performance.

Desejáveis:

- Desenvolvimento Android
- Desenvolvimento iOS
- Mobile First/Optmization
- SEO
- Progressive Web Apps

	
## **Contratação**
	
- CLT a combinar
	
## **Como se candidatar**
	
Para se candidatar a vaga, mande um email para rudinei.costa@compasso.com.br com o seu currículo e pretensão salarial - enviar no assunto: Vaga Front-End
	
## **Labels**

- CLT
- Pleno
- Alocado

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
