### ISSUE TITLE
[São Paulo] Fron-End Developer na SysMap Solutions

### ISSUE THREAD

**Issue by neidesouza** [frontendbr/vagas#905]
# Descrição da vaga:
Estamos contratando novos talentos interessados em atuar com soluções inovadoras e criativas para  desenvolver aplicações de TI para FrontEnd e Server para Desktop e Mobile. Desenvolvimento Single Page Application criando componentes reutilizáveis. 

## Local
São Paulo - Chácara Santo Antonio.

## Diferenciais
Horário flexível
Time versátil e com grande expertise

## Requisitos

**Obrigatórios:**
- React-React Native
- Angular, bootstrap 
- HTML5, JavaScript e CSS
- Axure-CSS3.0 

**Desejáveis:**
- conhecimentos em UML-XML-JSP (W).
- Design Pattern MVC, MVP, MVVM e Flux

**Diferenciais:**
Projeto em missão critica - Harmonização.

##Contratação
PJ a combinar

## Nossa empresa
A SysMap Solutions é uma Consultoria em tecnologia da Informação especializada em oferecer ao mercado, soluções de alta de performance, estratégias personalizadas de negócios, transformação digital, serviços de terceirização e implementação de diversos conceitos. 

## Como se candidatar
Por favor, envie um e-mail para rh3@sysmap.com.br com seu CV anexado - enviar no assunto: Vaga 

## Labels
- PJ
- Pleno

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
