### ISSUE TITLE
[São Paulo] Front-End Developer na Startup Colaboradores

### ISSUE THREAD

**Issue by WeltsColab** [frontendbr/vagas#906]
Blz pessoal? A Colaboradores é uma Startup que cresce de forma acelerada. Crescemos rápido porque temos em nosso time pessoas que pensam e atuam de forma estratégica, inovadora e são realizadoras. Se você tem o sonho e desejo de explorar seus limites, adquirir novos conhecimentos e ainda ganhar dinheiro, você vai se apaixonar em trabalhar conosco.

Necessário: 
- HTML5/CSS3/Bootstrap/ReactJS 
- Buscar sempre a melhor user experience do usuário e ter atenção a responsividade. 

Diferencial: - Node.JS/AngularJS/Python/Flask/SQLAlchemy/Backbone.JS 
-Ter trabalhado em projetos que envolvem a API de Mapas mais avançadas. 
- Familiaridade com metodologias ágeis (SCRUM)

CONTRATO
Prestador de Serviços (PJ)

REMUNERAÇÃO
R$ 5.000,00

BENEFÍCIOS
	Trabalho: Presencial ou Remoto, 
	Colaboradores: desconto em +17K endereços no Brasil inteiro 
	UseColab: +R$ 200,00 de reembolso para usar em parceiros Colaboradores
	ColabSaúde: + R$ 200,00 de reembolso para Plano de Saúde, Academias, Farmácia 
	13º salário 
	Férias.

Curtiu? Manda um email para: 

rh@colaboradores.com.br com assunto:  [VAGA] DEV FRONT END.

Abs, e tudo de bom para vcs!

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
