### ISSUE TITLE
[São Paulo] Full Stack Developer na Startup Colaboradores

### ISSUE THREAD

**Issue by WeltsColab** [frontendbr/vagas#907]
Blz pessoal? A Colaboradores é uma Startup que cresce de forma acelerada. Crescemos rápido porque temos em nosso time pessoas que pensam e atuam de forma estratégica, inovadora e são realizadoras. Se você tem o sonho e desejo de explorar seus limites, adquirir novos conhecimentos 
e ainda ganhar dinheiro, você vai se apaixonar em trabalhar conosco.

Necessário: 
- Conhecimento intermediário em HTML, CSS e Javascript/ TypeScript; 
- Experiência com framework responsivo (bootstrap, materialize, etc.). 
- Experiência com Angular 2/4, 
- Experiência Avançada com NodeJS 

Diferencial: 
– Conhecimento em MongoDB; 
– Experiência com Flexbox; 
– Pré processador ( LESS ou SASS ) 
– Conhecimentos com WebPack 
– Conhecimentos com Loopback 
– HTML avançando ( conseguir a partir de um layout fazer o HTML completo ) 
– Conhecimento em REST API 
– ReactJS e Python 
– Servidor Azure+AWS; 
– Propor melhorias ao produto e aos processos da Colaboradores 
– Implementação de rotinas para consultas e extração de dados; 
– Vontade de aprender e hábito de melhoria constante. 
– Proatividade e ser MUITO organizado

CONTRATO
Prestador de Serviços (PJ)

REMUNERAÇÃO
R$ 5.000,00

BENEFÍCIOS
	Trabalho: Presencial ou Remoto,
	Colaboradores: desconto em +17K endereços no Brasil inteiro
	UseColab: +R$ 200,00 de reembolso para usar em parceiros Colaboradores
	ColabSaúde: + R$ 200,00 de reembolso para Plano de Saúde, Academias, Farmácia
	13º salário
	Férias.

Curtiu? Manda um email para:

rh@colaboradores.com.br com assunto: [VAGA] DEV FULL STACK.

Abs, e tudo de bom para vcs!

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
