### ISSUE TITLE
[Alphaville] Desenvolvedor Front-End

### ISSUE THREAD

**Issue by beamillap** [frontendbr/vagas#91]
## Descrição da vaga

A FCamara busca profissionais apaixonados por tecnologia, movidos por desafios para atuar em um time interdisciplinar e disruptivo.
## OPORTUNIDADE DE DESENVOLVEDOR FRONT-END

**Requisitos:**

Possuir experiência com: Javascript, Angular, React, CSS, SASS, LESS, STYLUS.

Diferencial: XSL
## Local

Santana de Parnaíba - Alphaville
## Benefícios
- Ajuda de custo com transporte.
- Ambiente criativo e descontraído. 
## Requisitos

**Obrigatórios:**
Javascript
Angular
Reac
CSS
SASS
LESS
STYLUS.

**Diferenciais:**
XSL
## Nossa empresa

FCamara Consultoria. 

Se você busca crescimento profissional, desenvolvimento e autonomia, venha fazer parte do nosso time.

Conheça nosso Culture Code:

http://pt.slideshare.net/FCamara_Consultoria/culture-code-60932552
## Como se candidatar

Cadastre seu currículo http://jobs.kenoby.com/fcamara ou envie seu CV para beatriz.mila@fcamara.com.br.

**Comment by beamillap** [comment]
A oportunidade é Pleno/SÊNIOR, Alocação, e modelo contratação a definir.

**Comment by LFeh** [comment]
Boa sorte @beamillap ;)

**Comment by eduardojmatos** [comment]
@beamillap já preencheu a vaga? Nos avise pra mantermos ou removermos da lista :)
