### ISSUE TITLE
[São Paulo] Front-End Developer na Ambev

### ISSUE THREAD

**Issue by andre0799** [frontendbr/vagas#910]
## Descrição da vaga

We are developing a global platform where customers from many countries will be waiting for their cold beers! You will work with people with multidisciplinary skills (PO, UX / UI, Developers and QAs) in order to deliver the best experience for our users.
You will join a team where everyone share a common interest in distributed backend systems, their scalability and continued development. If you are passionate about working with high scalable backend infrastructure, and are motivated to make an impact in creating a robust and scalable software

## Local

Escritório, São Paulo - Itaim Bibi

## Benefícios

- Vale Refeição
- Vale Transporte
- Assistência Médica
- Assistência Odontológica
- Seguro de Vida

## Requisitos

**Obrigatórios:**
- SPA (Angular, React, BackBone)
- HTML5, CSS3
- Modern JavaScript ES6+
- Webpack/Browserify
- GIT
- Responsive Layout
- Good practices and front-end pattern knowledge
- B.S., M.S., or PhD. in Computer Science/Engineering or equivalent

## Contratação

CLT (Efetivo) - Salário de R$7000,00 a R$9000,00

## Nossa empresa

Empresa atua no ramo de bebidas ha mais de 20 anos, com foco em expandir o mercado levando boas experiência com as nossas marcas para os nosso clientes.

## Como se candidatar

Para se candidatar, acesse: [https://www.recrutasimples.com.br/vaga/-L7PPtvOeuEEq6_b4iWe?referrer=githubFrontendVagas](https://www.recrutasimples.com.br/vaga/-L7PPtvOeuEEq6_b4iWe?referrer=githubFrontendVagas)

## Labels

- CLT

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
