### ISSUE TITLE
[Curitiba] Front-End Developer no Grupo Inlog

### ISSUE THREAD

**Issue by lidia-freitas** [frontendbr/vagas#911]
### Descrição da vaga
> Buscamos um desenvolvedor que goste de novos desafios usando as linguagens HTML, CSS, Javascript.
O profissional irá atuar com metodologias ágeis e equipes autogerenciáveis.

__Necessário:__     
Boa lógica de programação e algoritmos, além de padrões e boas práticas de desenvolvimento, performance em aplicações web.

__Desejável:__  
frameworks Angular ou AngularJS, preprocessadores CSS.

__O que oferecemos?__
- CLT, VT, VR, Plano de saúde e odontológico
- Salário a combinar
- Empresa com ambiente descontraído
- Escritório bem no centro de Curitiba
- Frutas e snacks o dia todo
- Parcerias de desconto para graduação e pós-graduação
- Seguro de vida em grupo

__Quem somos?__  
Somos um grupo que tem a inovação como um dos nossos valores essenciais, sendo o primeiro e o maior no país a oferecer soluções completas ao mercado de controle, otimização e automação de empresas com operações de campo, nas áreas de coleta de resíduos e transporte coletivo.

__Tem o perfil que procuramos?__   
Currículos para: beinlog@inlog.com.br   
Realize um de nossos testes em [github.com/weareinlog](http://github.com/weareinlog)
e venha fazer parte do nosso time

**Comment by rhenanteix** [comment]
Página dando erro 404

**Comment by diogomoretti** [comment]
Arrumei o link @rhenanteix =]

**Comment by lidia-freitas** [comment]
Obrigada @diogomoretti ;)
