### ISSUE TITLE
[São Paulo/SP ou Campinas/SP] Front-End Developer Pleno na Geofusion

### ISSUE THREAD

**Issue by elielmiller** [frontendbr/vagas#912]
## Geofusion
Uma empresa focada na criação de tecnologia, a qual permite aos usuários cruzarem dados geográficos online. Com clientes em diversos setores, como o varejo, a indústria e o imobiliário, que se utilizam dessa tecnologia diariamente para tomar decisões estratégicas para o seu negócio.

A inovação é o combustível que move a Geofusion.

As tecnologias e metodologias mais avançadas na área de TI são usadas como recursos na construção do OnMaps.  O OnMaps manipula milhões de informações de forma muito rápida e escalável, para o cliente tenha uma resposta precisa, no menor tempo possível.

Com um ambiente de trabalho leve e descontraído, o time recebe grandes desafios técnicos e tem a liberdade para solucioná-los.
## Front-End Developer Pleno (São Paulo ou Campinas)
O profissional atuará no projeto, construção e otimização da interface Web do OnMaps. Nossa stack de front-end é quase toda implementada em React + MobX e utilizamos o que há de mais moderno em desenvolvimento JavaScript sempre que possível.

Além disso, o profissional terá algum contato com tecnologias para desenvolvimento de serviços RESTful (utilizamos principalmente Java + Spring) que serão consumidos pelas interfaces.

## Requisitos necessários:
* Formação superior em Ciência  da Computação, Engenharia de Computação, Análise de Sistemas, * * * Sistemas de Informação ou área relacionada
* Experiência com criação de layouts em HTML e CSS
* Forte conhecimento em modularização e pré-processamento de CSS (Less, Sass)
* Experiência com bibliotecas para criação de componentes reusáveis, preferencialmente React
* Conhecimento em frameworks de manutenção de estados (Redux, MobX)
* Conhecimento em ferramentas de modularização de código JavaScript, preferencialmente Webpack
* Experiência com ferramentas de versionamento de código, preferencialmente Git
* Vivência e conhecimento em cultura de desenvolvimento ágil, bem como metodologias associadas (i.e. Kanban, Scrum).

## Requisitos desejáveis:
* Experiência com desenvolvimento de SPA usando React + MobX/Redux
* Experiência com desenvolvimento de backend em Java e/ou Node.js
* Experiência com Backbone.js, Handlebars.js, jQuery e/ou Underscore.js
* Experiência com UX design
* Conhecimento em Responsive Web Design
* Conhecimentos em API de mapas: Leaflet, OpenLayers e/ou Google Maps API
* Conhecimentos em bibliotecas de visualização de dados (D3.js)

**Link para candidatura:** https://goo.gl/9noMBu

**Labels:** CLT, Pleno

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
