### ISSUE TITLE
[São Paulo] Front-End Developer na E3 COMÉRCIO DE ARTIGOS ÓPTICOS

### ISSUE THREAD

**Issue by joaocarvalhowd** [frontendbr/vagas#913]
## Descrição da vaga

Criação de páginas com foco em responsividade utilizando tecnologias como JAVASCRIPT, HMTL 5, CSS (SASS, Stylus), GIT e task-runners (gulp/grunt), testes cross-browsing e Photoshop.

## Local

Escritório, São Paulo - Jaguaré

## Benefícios

- Plano de saúde
- VR de R$ 20/dia
- VT ou Vale combustível de R$ 200/mês
- Estacionamento grátis
- Folga no dia do aniversário

#### Diferenciais

- sem controle no horário de almoço
- mesa de ping-pong
- permitido bermuda e chinelo

## Requisitos

**Obrigatórios:**
- Conhecimento em JAVASCRIPT, HMTL 5, CSS (SASS, Stylus)

**Desejáveis:**
- experiência em outros e-commerce

**Diferenciais:**
- experiência com Magento, Vue.js, react ou outro framework MVC

## Contratação

CLT Full

## Nossa empresa

E3 é uma empresa do grupo Essilor que é respońsável atualmente por 2 e-commerces do ramo óptico: [eÓtica](https://www.eotica.com.br) e [e-lens](https://www.e-lens.com.br)

## Como se candidatar

Por favor envie um email para andressa.rocha@eotica.com.br com seu CV anexado e pretensão salarial - enviar no assunto: Vaga Front-End Developer Junior

## Labels

- Alocado
- CLT
- Júnior

**Comment by joaocarvalhowd** [comment]
@LFeh poderia colocar os label, por favor?!

**Comment by danieladuarteng** [comment]
enviado

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
