### ISSUE TITLE
[São Paulo] Front-End Developer no [Cel.Lep Ensino de Idiomas S.A]

### ISSUE THREAD

**Issue by rhcellep** [frontendbr/vagas#914]

**Comment by rhcellep** [comment]
**Nossa empresa**
Cel.Lep é uma conceituada escola de inglês e espanhol que atua no segmento de idiomas há 50 anos tradicionalmente em São Paulo e algumas cidades do interior de SP, e em 2017 adquiriu a escola de programação MadCode que desenvolve suas atividades com os públicos teens e kids. 

Acreditamos que um novo idioma é fundamental para abrir muitas portas na vida e que nas próximas décadas aprender a programar será tão importante como é hoje o conhecimento de uma segunda língua.

**Descrição da vaga**
Atuação como Front End Developer no ramo Educacional.

**Local**
Morumbi - São Paulo.

**Requisitos**
- GIT
- JavaScript ECMA 6 / TypeScript
- Angular 4 / Angular CLI
- WebPack
- NodeJs
- HTML 5
- SASS / CSS
- Bootstrap / Materialize

**Formação** 
Ensino superior (cursando ou concluído) em uma das áreas abaixo:
- Sistema de Informação
- Gestão em Tecnologia da Informação
- Análise e Desenvolvimento de Sistemas
- Ciência da Computação
- Engenharia da Computação

**Contratação**
CLT, 40h semanais.

**Como se candidatar**
Enviar email para hana.chiarelli@cellep.com com CV anexo e assunto: Vaga Front End.

Labels
Alocado
Sênior

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
