### ISSUE TITLE
[São Paulo] Professor de Programação para Kids e Teens [MadCode - Cel.Lep]

### ISSUE THREAD

**Issue by rhcellep** [frontendbr/vagas#915]
**Descrição da empresa**

A MadCode é uma rede de Escolas de Programação para crianças e adolescentes. Acreditamos que nas próximas décadas a alfabetização digital será tão importante para os jovens como é hoje o conhecimento de uma segunda língua como o inglês. Adicionalmente, o seu aprendizado desenvolve habilidades cognitivas que vão além da tecnicidade, tais como raciocínio lógico, foco e capacidade resolver problemas. Nossa missão é empoderar jovens através da tecnologia, dando-lhes recursos para que deixem de ser meros consumidores de tecnologia e passem a ser produtores de soluções tecnológicas que possam oferecer novas possibilidades às situações reais de suas vidas.

**Descrição da vaga:**

> Atividades: Aulas de Programação
> Regime de contratação: Prestador de Serviços (PJ)
> Remuneração: R$ 25,00 hora aula

**Pré-requisitos:**

> Ensino superior em áreas de Tecnologia (cursando ou completo);
> Relacionar-se bem com crianças e adolescente
> Desejável o domínio das ferramentas Scratch, Snap e Stencyl
> Boa didática

**Benefícios:**

> Bolsa de estudo para si, filhos e cônjuge (inglês ou espanhol) e curso de programação para filhos de 5 a 17 anos.
> Vale Transporte

**Salário:** 

> R$25,00 /hora

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
