### ISSUE TITLE
[Barueri] Front-End Developer Deal Technologies

### ISSUE THREAD

**Issue by GabrielaNapoli** [frontendbr/vagas#916]
## Descrição da vaga

Atuação como Front End Developer pleno e sênior

## Local

Alphaville - Barueri (SP)

## Requisitos

Consumo API
HTML 5
CSS3
React
NodeJs
ECMA Scripts 5 e 6
Media Queries
Otimização de websites para mecanismos de busca (SEO)

## Contratação

PJ a combinar

## Nossa empresa

A Deal é uma das empresas do ramo de TI que mais cresce atualmente.

## Como se candidatar

Por favor envie um email para gabriela.napoli@deal.com.br com seu CV anexado - enviar no assunto: Vaga Front End

## Labels

- Alocado
- PJ
- Pleno
- Sênior

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
