### ISSUE TITLE
[São Paulo] Desenvolvedor Front-End Sr

### ISSUE THREAD

**Issue by fabiowitt** [frontendbr/vagas#92]
### **Afim de desafios novos?**

Estamos em busca de um desenvolvedor front-end engineer senior que, assim como nós, tenha um perfil ousado e empreendedor: gente ligada em tecnologia, com brilho nos olhos e que goste de evoluir com novas experiências, que queira construir produtos e soluções incríveis, sempre antenado nos últimos frameworks e padrões. Você será responsável por liderar a área de front-end dentro da equipe, buscando novas tecnologias e fazendo com que nos tornemos referência para outras empresas.

### **Requisitos**

- Domínio em lógica de programação, orientação a objetos e design patterns
- Ter trabalhado com algum framework Javascript MVC (Angular, Backbone, KnockoutJS, EmberJS, etc..)
- Sólidos conhecimentos em HTML/CSS/Javascript
- Experiência com pré-processadores (less, sass, stylus…)
- Experiência com ferramentas automação de tarefas (Gulp, Grunt, Webpack…)
- Ter conhecimento como funciona um fluxo de teste e os tipos de testes existentes, de preferência já ter experiência com implementação dos mesmos.

### **F(x)**

A F(x) é uma empresa jovem, fundada em 2015 para resolver o problema de crédito de  empresas médias e grandes no Brasil. Usamos a experiência de 10+ anos no setor financeiro e de mais 10+ em desenvolvimentos de produtos e de construção de empresas baseadas em internet e marketplaces.

Oferecemos às empresas clientes o acesso diferenciado a uma rede de financiadores alternativos para busca de crédito estruturado, além de ferramentas que otimizam as condições dos créditos liberados, trazendo benefício imediato tanto às empresas quanto aos financiadores.

Queremos encontrar um desenvolvedor que, assim como a gente, tenha um perfil ousado e empreendedor: gente ligada em tecnologia, com brilho nos olhos e que goste de evoluir com novas experiências, que queira construir produtos e soluções incríveis. Uma pessoa que seja antenada no mercado de fintechs.

Para isso temos um nível de exigência alto com qualidade e buscamos um front-end que tenha atenção aos mínimos detalhes, que se preocupa com o pixel que está no lugar errado, com a animação que não está tão smooth, enfim, que ama o que faz. 

### O que oferecemos?

- Espaço, estímulo e suporte para se desenvolver e crescer de forma meteórica
- Interação com outras startups (BeeCâmbio, Singu, Easy Carros, Choppup) da venture builder eGenius (grupo do qual fazemos parte)
- Oportunidade de contribuir efetivamente para a evolução de uma startup em crescimento acelerado (aqui, suas ações e opiniões podem causar grandes impactos)
- Ambiente descontraído e dinâmico

### Contratação & Local

PJ presencial (São Paulo, Pinheiros)

### Se interessou pela vaga?

Mande seu CV/LinkedIn para [ti@fdex.com.br](ti@fdex.com.br) com o título “Vaga para Front-end na F(x) - SEUNOME”.

**Comment by eduardojmatos** [comment]
@fabiowitt fala mano, já preencheu a vaga? Nos avise pra mantermos ou removermos da lista :)

**Comment by fabiowitt** [comment]
@eduardojmatos estamos prestes a finalizar, caso tudo ocorra tranquilo finalizamos essa semana.

**Comment by LFeh** [comment]
Show

**Comment by eduardojmatos** [comment]
@fabiowitt boa! :)

**Comment by fabiowitt** [comment]
Fechamos a vaga!

**Comment by fdaciuk** [comment]
@fabiowitt \o/

**Comment by camilatigre** [comment]
@fabiowitt 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by fabiowitt** [comment]
@camilatigre sem problemas :)

b) Não
