### ISSUE TITLE
[Americana - SP] Front-End Developer na Thutor

### ISSUE THREAD

**Issue by felipedefarias** [frontendbr/vagas#920]
## Descrição da vaga

Terá como responsabilidade o desenvolvimento e manutenção dos sites de nossos produtos, aplicações web, apps, melhorias e outras atividades de rotina.

## Local

Presencial, Americana - São Paulo

## Benefícios

- Salário compatível com o mercado
- Vale Transporte
- Vale refeição ou Vale Alimentação de R$ 19,10/dia
- Seguro de vida

## Requisitos

**Obrigatórios:**
- HTML
- CSS
- Js
- Wordpress
- Git

**Diferenciais:**
- Conhecimento de UX e Design
- Ionic
- Angular/React/Vue

## Contratação

- CLT

## Nossa empresa

Somos uma organização com interesse genuíno em pessoas. Queremos transformar o mundo dos negócios e a sociedade por meio de uma nova forma de fazer gestão de pessoas e organizações.

[thutor.com](http://thutor.com)

## Como se candidatar

Por favor envie um email para cristina@thutor.com até **25/03/2018** 

- Currículo
- Pretenção salarial
- Assunto: Front-end Thutor
- Perfil no Git ou Bitbucket

## Labels

- Alocado
- CLT

**Comment by renanlara** [comment]
Enviado! Americana <3

**Comment by LFeh** [comment]
Gosto de ver vagas em Americana, hehe
