### ISSUE TITLE
[São Paulo] Front-End Developer] na RESOURCE IT

### ISSUE THREAD

**Issue by Vi181185** [frontendbr/vagas#921]
## Descrição da vaga

Projeto em grande instituição de investimentos localizada na Faria Lima

## Local

Escritório, São Paulo - Faria Lima 

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ 440,00/mês
- Auxílio creche
- Plano Odontológico

## Requisitos

**Obrigatórios:**
- No mínimo 5 anos de experiência profissional com HTML, CSS e Javascript
- Vivência e conhecimento em SPA com React ou Angular 2  ou Vue.Js.

**Desejáveis:**
- conhecimentos em Angular 2, React ou Vue.JS
- ter atuado em instituições financeiras

## Contratação

CLT a combinar

## Nossa empresa

A Resource IT é a empresa de TI que mais cresceu nos últimos tempos, é uma empresa multinacional brasileira que oferece soluções em TI para grandes empresas.

## Como se candidatar

Por favor envie um email para viviane.sampaio@resourceit.com com seu CV anexado - enviar no assunto: Vaga Dev Front End Sênior

## Labels

- Alocado
- CLT
- Sênior

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
