### ISSUE TITLE
[São Paulo] Front-End Developer - Medcel

### ISSUE THREAD

**Issue by TalentosMedcel** [frontendbr/vagas#922]
## Principais atividades da posição:
•	Codificação do novo aplicativo mobile;
•	Analise e reconstrução do front-end da área do aluno no site;
•	Análise e construção das peças do site;
•	Auxílio nos materiais de Marketing.
 
## Qualificações que é preciso ter para se inscrever:
•	Preferência por formação em Designer, ciência da computação ou engenharia da computação;
•	Ter trabalhado como front-end em outras empresas;
•	Sólidos conhecimento em HTML, CSS, Javascript, Jquery, Bootstrap;
•	Desejável conhecimento em Saas, Less, React, Vue, Invision, Ilustration, Photoshop, Sketch, Material design;
•	Capacidade analítica;
•	Proativo, interessado e antenado;
•	Resiliente, esforçado, disciplinado;
•	Bastante atenção aos detalhes e cuidado estético.

## Local

Escritório, São Paulo - Avenida Paulista

## Benefícios

- Plano de saúde
- Seguro de vida
- Auxílio Odontológico
- Vale Refeição
- Vale Alimentação (supermercado)
- Vale Transporte
- Parceria com academias

## Requisitos

**Obrigatórios:**
- HTML, CSS, Javascript, Jquery, Bootstrap;

**Desejáveis:**
- Saas, Less, React, Vue, Invision, Ilustration, Photoshop, Sketch, Material design;

## Contratação

CLT

## Nossa empresa

A Medcel é líder no segmento de educação mediada por tecnologia na área médica, gerenciando e comercializando conteúdo. Possuímos uma plataforma personalizada para que nosso aluno tenha a melhor experiencia educacional. Aqui, qualidade e inovação andam lado a lado, pois acreditamos que nada é impossível e entendemos que gente é tudo pra gente.

## Como se candidatar

Por favor envie um email para talentos@medcel.com.br com seu CV anexado - enviar no assunto: Vaga Front-End

## Labels

- CLT
- Pleno

**Comment by nandosangenetto** [comment]
@LFeh faltou o [São Paulo]

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
