### ISSUE TITLE
[São Paulo] FullStack Developer

### ISSUE THREAD

**Issue by sibelius** [frontendbr/vagas#93]
## Descrição da vaga

Estamos buscando um desenvolvedor para início imediato. Esperamos:
- Conhecimentos sobre desenvolvimento JAVA - Android
- Conhecimentos sobre desenvolvimento Javascript (AngularJS, React)
- Vontade de programar como gente grande e conhecer o funcionamento de uma startup
desde o começo
 - Consciência que deve-se fazer de tudo (sem “prima-donnismos” ou braço curto)
Se você não tiver conhecimentos dos primeiros pontos, mesmo assim pode entrar em contato conosco: somos super flexíveis e, quem sabe, podemos acertar algo que funcione para ambas as partes. 

[VenhaTrabalharLar21.pdf](https://github.com/frontendbr/vagas/files/409172/VenhaTrabalharLar21.pdf)

## Local

Escritório Anhangabau - São Paulo

## Contratação

Estágio ou CLT/PJ

## Como se candidatar

Por favor envie um email para dev@pontotel.com.br com seu CV anexado - enviar no assunto: [Vaga FullStack]

**Comment by heliomsolivas** [comment]
Maneiro, fiz um freela de front pra alguém daí mês passado. Pena que é presencial :(

**Comment by sibelius** [comment]
@heliomsolivas muda pra sp :smile:

**Comment by eduardojmatos** [comment]
@sibelius manolo, já preencheu a vaga? Nos avise pra mantermos ou removermos da lista :)

**Comment by sibelius** [comment]
preenchida

**Comment by eduardojmatos** [comment]
@sibelius valeu!

**Comment by camilatigre** [comment]
@sibelius 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by sibelius** [comment]
Não
