### ISSUE TITLE
[São Paulo / SP] - Front-end Developer na Superare

### ISSUE THREAD

**Issue by superarelucas** [frontendbr/vagas#930]
## Descrição da vaga

O desenvolvedor será responsável (dependendo de seu nível de proficiência) por criar e dar manutenção em Landing Pages, Web Apps e projetos específicos de diversos clientes, alguns deles sendo Claro / NET / Embratel.

## Local

Rua Eugênio de Medeiros, 303 - Pinheiros / SP (Próximo ao metrô Pinheiros - Linha 4)

## Benefícios

- VT
- VR

## Requisitos

**Obrigatórios:**
- Mínimo de 6 (seis) meses de experiência com desenvolvimento front-end.
- Conhecimento em HTML5
- Conhecimento em CSS3
- Conhecimento em JS (Básico - Eventos, integrações de libs, etc.)
- Conhecimento em Bootstrap 3 (A versão 4 é legal também)
- Conhecimento de GIT (Errou um commit, paga 2 reais haha)

**Desejáveis:**
- Conhecimento em Wordpress
- Conhecimento em Task-Runners como Grunt ou Gulp
- Conhecimento em Pré-processadores como SASS/SCSS, LESS ou Stylus
- Conhecimento em Pré-processadores HTML como Haml ou Jade/Pug
- Ter portfólio :)

**Diferenciais:**
- Conhecimento em JS Frameworks como Angular, Vuejs ou React
- Conhecimento em NodeJS + MongoDB (Ou pode ser um relacional como MySQL / PostgreSQL)
- Conhecimento em PHP (Não só aquele do Wordpress)
- Entende conceitos com facilidade e faz uso de design patterns em suas aplicações
- Entende o conceito de metodologia CSS (OOCSS, RSCSS, BEM) e consegue aplicá-las da melhor maneira

## Contratação

PJ ou CLT.
Salário a combinar.

## Nossa empresa

Nossa equipe de especialistas em criação, programação e novas tecnologias é responsável por projetos inteligentes que têm como caracteristicas a criatividade e a inovação. Buscamos sempre experiências inéditas, isto é a chave para parcerias de sucesso com grandes marcas e agências do mundo.

Visite nosso site: https://superaremedia.com.br/

## Como se candidatar

Por favor envie um email para lucas@superaremedia.com.br com seu CV anexado (ou pode ser URL do linkedin, portfólio, etc.) com o assunto: Vaga Desenvolvedor Front-End - Superare

## Labels

- Alocado
- CLT
- PJ
- Júnior
- Pleno

**Comment by richmanzoli** [comment]
Enviado :+1:

**Comment by fcbento** [comment]
Enviado.

**Comment by danieladuarteng** [comment]
enviado
