### ISSUE TITLE
[Barueri] Front-End Developer na BizSys

### ISSUE THREAD

**Issue by chingling123** [frontendbr/vagas#934]
## Descrição da vaga

Projetos especiais para front-end.

## Local

Escritório, Barueri - Alphaville

## Benefícios

- Estacionamento ou transporte

#### Diferenciais

- projetos especiais deferentes de tudo que já trabalhou

## Requisitos

**Obrigatórios:**
- experiencia com CSS
- experiencia com UX

**Desejáveis:**
- conhecimentos em WordPress
- conhecimentos em Asp.Net

## Contratação

PJ

## Nossa empresa

www.bizsys.com.br

## Como se candidatar

Por favor envie um email para vagas@bizsys.com.br com seu CV anexado - enviar no assunto: Vaga Front-End

## Labels

- Alocado
- PJ

**Comment by ArieltonPires** [comment]
sent!

**Comment by chingling123** [comment]
@ArieltonPires blz? pode reenviar no vagas@bizsys.com.br
