### ISSUE TITLE
[Rio de Janeiro] Full Stack Developer na X3M Sports Business

### ISSUE THREAD

**Issue by ricardo-mello** [frontendbr/vagas#936]
## Descrição da vaga

Estamos iniciando um time de desenvolvimento e procuramos devs full-stack acima da média para fazer parte dele. Temos um ambiente descontraído, informal e dinâmico, mas também oferecemos a possibilidade de trabalho remoto.

## Local

Remoto ou Escritório, Rio de Janeiro - Botafogo

## Requisitos

**Esperamos que você tenha:**

-   Experiência mínima de 2 anos com meios digitais (sites, aplicativos, sistemas)
-   Domínio de HTML, CSS e JavaScript
-   Experiência com sites responsivos/grids fluidos
-   Experiência com bibliotecas/frameworks Javascript (React, Angular, etc)
-   Experiência com PHP, frameworks e CMS populares(Yii, Wordpress)
-   Código eficiente, escalável, acessível e reutilizável
-   Facilidade para trabalhar em equipe e contribuir com seus pares
-   Boa comunicação verbal e escrita

**Desejamos que você possua:**

-   Conhecimentos de ES6
-   Familiaridade com Pug
-   Familiaridade com controle de versão (preferencialmente Git)
-   Familiaridade com linha de comando (Terminal)
-   Conhecimento de SEO no front-end
-   Conhecimento de acessibilidade para web

**Diferenciais:**

-   Participação em projetos opensource

## Contratação

CLT ou PJ

## Nossa empresa

[www.x3mbrasil.com](http://www.x3mbrasil.com/)

## Como se candidatar

Por favor, envie um email para [gestaodepessoas@x3mbrasil.com](mailto:gestaodepessoas@x3mbrasil.com) com seu CV anexado - enviar no assunto: Vaga Full-Stack Developer

## Labels

- Alocado
- Remoto - Parcial
- CLT
- PJ
- Pleno

**Comment by paulo101977** [comment]
Mandei o e-mail.

**Comment by ArieltonPires** [comment]
sent!

**Comment by ricardo-mello** [comment]
Vaga fechada! Obrigado a todos que participaram!

P.S.: O Dev que nós contratamos viu a vaga aqui no frontendbr mesmo
