### ISSUE TITLE
[Remoto] Front-End & UX (min 3hr/dia)

### ISSUE THREAD

**Issue by nei** [frontendbr/vagas#94]
## Freelancer Frontend & UX (min 3hr/dia)

Estamos em busca de um desenvolvedor frontend & UX ninja para integrar em nosso time de 2 desenvolvedores. Procuramos um linchpin! Alguém que entre na equipe para agregar, goste de autonomia, contribua com idéias e tenha senso crítico. Mínimo de 5 anos de experiência com desenvolvimento ou que tenha uma experiência invejável.

Somos uma startup, ainda em fase de validação do produto mas com um rítimo acelerado.

Nossa stack:
- Microservices em Nodejs
- Vuejs & Express frontend
- Postgresql & Redis
- Tools: Github / TravisCI / AWS

## Requisitos (obrigatórios):

- Inglês intermediário (commits, manual, bd, all english )
- Sólidos conhecimentos com Javascript 
- Angular, Vue ou similar
- Domínio em HTML5,CSS
- Domínio com pré-processadores ( LESS, SASS )
- Terminal ninja.
- Perfil GitHub 
- Experiência com testes automatizados e unitários

## Diferencial:

- Utilize Mac ou Linux
- Tenha experiência com práticas XP, Scrum, Lean
- Bom gosto para design
- Nodejs

## Contratação 

Freelancer min 3hrs/dia podendo aumentar.

## Como se candidatar

Acha que se encaixa no perfil? envie um email para nei@herocar.io

**Comment by LFeh** [comment]
Cara, só tirei essa parada de Ninja do titulo, rs.

É alocado?

**Comment by klarkc** [comment]
Mandei currículo ;)

**Comment by nei** [comment]
Não é alocado, é remoto mesmo.

**Comment by nvrossett** [comment]
Mandei ai!!! Meu perfil do github é modesto pois uso mais o bitbucket =)

**Comment by eduardojmatos** [comment]
@nei  já preencheu a vaga? Nos avise pra mantermos ou removermos da lista :)

**Comment by nei** [comment]
@eduardojmatos sim já preenchemos. Obrigado Eduardo.

**Comment by camilatigre** [comment]
@nei 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
