### ISSUE TITLE
[Florianóspolis] UI Developer na MCFADYEN DIGITAL

### ISSUE THREAD

**Issue by phameister** [frontendbr/vagas#940]
## Descrição da vaga
Company Description

MCFADYEN DIGITAL (Previously McFadyen Solutions) is a leading digital agency with 20 years of experience helping global brands shape the future of Omni-channel commerce, marketing and service delivery. Hundreds of MCFADYEN clients achieved digital success with MCFADYEN’s advisory, creative, and technical services which often leverage Oracle software.

Our consultants work with clients to reinvent their digital strategy with collaborative interactions that forms the core of our philosophy of creating happier relationships with customers. Be it Technology Consulting or Systems Integration or Omni-Channel commerce solutions or Digital Marketing Advisory or User Experience Services, MCFADYEN DIGITAL offers 360 degree services to customers to help them win big in the market.

Headquartered in the US with offices in India and Brazil, MCFADYEN DIGITAL has several hundred professionals serving clients round the clock.
Job Description

About You

Are you an innovative person who can accelerate the growth of our nationally acclaimed project? Do you have a passion for technology and a flexible, creative approach to problem solving? Are you self-directed, confident, and able to work without requiring a great deal of structure or supervision? Are you highly self-motivated and having head full of ideas? If you answered yes to these questions, we want to talk to you.

 

Position Summary

We are looking for creative and dependable self-motivated professionals to join our team as a Junior UI Developer.

 

Responsibilities

• Create reusable and clean UI pattern framework that Application Developers can plug and play

• Handle customer expectations on challenging projects

• Adhere to code standards and ensure consistency

• Quickly convert wireframes into HTML front-end with optimal quality

• Team with our Application Developers to bridge the client side with server side code

• Ensure quality assurance on front-end code including HTML, CSS, and JavaScript

• Deliver consistency of the user interfaces across multiple platforms

• Provide production support for all implemented changes

• Work in a small, fast-paced, team-oriented environment

• Liaise closely with onsite counterparts in order to continue to drive product forward
Qualifications

• Proven experience in UI development and integration for web and mobile applications with  delivered projects

• Applied experience of UI development principles

• Have a good understanding of the three pillars of front end development which are HTML, CSS and JavaScript

• Generate clean, semantic HTML and CSS

• Have exceptional proficiency in writing Vanilla JavaScript (no jQuery!) from scratch, understand MVC coding model and object oriented concepts

• Know the Responsive web and have a little bit of knowledge about current UX trends.

• Have practical exposure on frameworks and APIs such as jQuery, Backbone, Handlebar, AngularJS, LESS, and Bootstrap

• Ensure cross-browser and cross-device compatibility

• Believe take actions so that disabled and visually challenged users have a right to use the web as easily as everyone else

• Exposure on e-commerce platforms is preferred and strong experience in agile methodology is a plus

 

ADVANCED ENGLISH SKILLS AND AVAILABILITY TO MOVE TO FLORIANOPOLIS/SC IS MANDATORY 
Additional information

Your Core Values: Integrity, Motivation, Leadership, Proactive, Team-Player

 

To Apply: We value smart, creative individuals who are multi-dimensional thinkers and thrive on professional development. Superb competence and continual improvement are key goals for everyone at McFadyen Solutions. This is an exciting opportunity with tremendous growth potential for someone who is focused on excellence. Your portfolio should impress us with great skills and conceptual problem-solving. We seek people who can demonstrate both compelling form and technical accuracy. Tell us why you would be a great addition to our team.

McFadyen Solutions is an Equal Opportunity Employer. All qualified applicants will receive consideration for employment without regard to race, color, age, religion, sex, sexual orientation, gender identity / expression, national origin, disability, protected veteran status, or any other characteristic protected under federal, state or local law, where applicable.

## Local

Rua Patricio Farias 55, SALA 701 - Itacorubi, Florianopolis

## Benefícios

- Plano de saúde Odontologico
- VR de R$ 20/dia
- VT

## Requisitos

**Obrigatórios:**
- Imprescindível Inglês Avançado
- Não há possibilidade de trabalho remoto

## Contratação

CLT

## Como se candidatar

Por favor se aplicar no link: http://smrtr.io/8ozDoQ

## Labels

- Alocado
- CLT
- Freela
- Júnior
- PJ
- Pleno
- Sênior
- UI

**Comment by MatheusWTF** [comment]
Seria bom alterar o titulo para colocar a localização da empresa (Florianópolis)
