### ISSUE TITLE
[Belo Horizonte] Front-End Developer PHP Pleno [Sapiens] 

### ISSUE THREAD

**Issue by sapiensbh** [frontendbr/vagas#943]
## Descrição da vaga

Participará do desenvolvimento de novos projetos, aplicações web, aplicações mobile, webservices e blockchain. 

## Local

    Belo Horizonte - (Bairro Santa Efigênia)
    Escritório (Presencial) ou Remoto

## Benefícios

    VT + VR
    1 hora de almoço
    40 horas semanais

## Requisitos

Obrigatórios:

    - Estar confortável para trabalhar com demandas e datas pré-definidas com metas de produtividade;
    - Ser proficiente com as ferramentas ágeis mais comuns;
    - Experiência de pelo menos 2 anos com desenvolvimento frontend em PHP;
    - Ser proficiente com PHP, HTML & CSS;
    - Ser proficiente com temas de Wordpress;
    - Saber o essencial de JavaScript, para por exemplo, lidar com a exibição dos dados advindos do backend através de 'templates engines';
    - Ter como pontos fortes, ter plena posse de suas ideias e resolver problemas desafiadores;
    - Ter o desejo de trabalhar de forma colaborativa com uma equipe.
    - Git (Command Line)
    - Inglês Técnico para leitura
    - Conhecimentos de pré-compiladores de CSS

## Diferenciais:

    - Wordpress
    - Desenvolvimento de Plugins
    - Desenvolvimento de Temas
    - Woocommerce

## Contratação

    PJ Entre R$1.600,00 à R$ 2.500,00 + Bônus de Produtividade

## Nossa empresa

Somos a Sapiens, estamos há 09 anos no mercado e esse ano estamos fazendo uma fusão com outras empresas e buscando expansão no mercado nacional e internacional. Aqui você terá possibilidade de trabalhar em diversos projetos no Brasil e no exterior.

## Como se candidatar

Por favor envie um email para rh@sapiensolutions.com.br com seu CV anexado - enviar no assunto: Vaga Front-End Desenvolvedor Junior/Pleno

## Labels

- Alocado
- PJ
- Pleno
- Sênior

**Comment by wandesoncunha** [comment]
Comparando exigência e retorno, só é vantajoso para o contratado se for ao menos remoto.

**Comment by brunokunace** [comment]
1300 PJ, nem estagiário (sei que é o valor mínimo), poderiam revisar sobre este valor e os requerimentos pedidos.

**Comment by rubemalmeida** [comment]
Foca nos labels: Pleno e Senior..

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
