### ISSUE TITLE
[São Paulo] Front-End Developer na [inDecks]

### ISSUE THREAD

**Issue by Ricardoaugustovt** [frontendbr/vagas#945]
## Descrição da vaga

Projeto em .net e Angular JS.
Precisamos de alguém para adaptar um Tema HTML para o estilo que temos desenhado e depois estilize todas as telas do projeto, também de acordo com os desenhos.

O projeto está sendo desenvolvido em paralelo e as telas serão entregue com Adobe XD.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Ter experiências anteriores
- Mostrar portfólio com projetos que desenvolveu.
- Disponibilidade para trabalhar e garantir evoluções no máximo a cada 3 dias.

**Desejáveis:**
- HTML 5
- CSS 3
- JavaScript
- Angular JS
- CrossBrowser
- Responsividade
- Less

**Diferenciais:**
- Conhecer Material Design
- Já ter trabalhado com o efeito Frosted Glass em css
- Disponibilidade em horário comercial

## Contratação

Freelancer a combinar

## Nossa empresa

A inDecks é tem mais de dez anos de experiência em desenvolvimento de softwares customizados com foco em Portais de Intranet.

## Como se candidatar

Por favor envie um email para contato@indecks.pro com seu CV anexado - enviar no assunto: Vaga inDecksPro

## Labels

- Remoto
- Freelancer
- Freela
- Angular
- .Net
- Material Design

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
