### ISSUE TITLE
[Remoto] Front-End Developer na Upnid

### ISSUE THREAD

**Issue by lucasupnid** [frontendbr/vagas#946]
# ## Descrição da vaga

Você será responsável por desenvolver os recursos mais complexos dos projetos. Para isso é necessário ter um altíssimo conhecimento em padrões de desenvolvimento e qualidade de código.

## **Você vai se encaixar se:**

- Tiver perfil driven e gostar de entregar novas funcionalidades

- Você gosta de sempre ser desafiado a prender mais

- Você abraça novos desafios e questiona o status quo

- Aprende rápido e se adapta facilmente a mudanças

- Você se dedica a criar um produto incrível em padrões internacionais

- Busca ter uma visão macro do projeto que entra para poder contribuir em diversas áreas.

## Local

Remoto - (Caso opte por trabalhar em escritório, possuímos frente em SP, BH e RJ)

## Benefícios

Possibilidade de PL

#### Diferenciais

- Bonificação extra para alto desempenho 
- Incentivo a educação (cursos, livros, eventos, etc)
- Trabalho Remoto
- Horários flexíveis (você define a sua rotina)

## Requisitos

**Obrigatórios:**
- Experiência comprovada em  React
- Conhecimentos em JavaScript, HTML, CSS
- Testes automatizados
- Foco em qualidade de código

**Desejáveis:**
- Conhecimento em Node.JS

## Contratação

PJ/CLT a combinar

## Nossa empresa

Somos um marketplace para venda de produtos físicos e digitais. Estamos a dois anos no mercado crescendo a cada mês. Temos Executivos de grandes empresas do ecommerce brasileiro como sócios.

## Como se candidatar

Por favor envie um email para lucas@upnid.com com seu CV e link do perfil no Github - enviar no assunto: "Vaga Desenvolvedor Pleno - GitHub" 
## Labels

- CLT
- PJ
- Pleno
- Remoto - Total
- Sênior

**Comment by vititu** [comment]
Não estou conseguindo enviar e-mail, está retornando. 😕

**Comment by Annatsu** [comment]
Mesma coisa comigo :(

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
