### ISSUE TITLE
[Recife] Front-End Developer (React Native) na Biuri

### ISSUE THREAD

**Issue by ytalokaio** [frontendbr/vagas#947]
## Descrição da vaga

Manutenção contínua de dois aplicativos na Biuri.

## Local

Presencial , Recife - Boa viagem

## Benefícios

- Flexibilidade de horário

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento Mobile (React Native)
- Sólido conhecimento em Javascript
- JSX
- Axios/Fetch
- Controle de estado com Redux
- Integração com serviços RESTFul

**Desejáveis:**
- conhecimentos em python/Django

**Diferenciais:**
- projetos opensource
- Portfólio (apps mobile)

## Contratação

PJ a combinar

## Nossa empresa

Somos uma plataforma que aproxima profissionais liberais de beleza com seus clientes.

## Como se candidatar

Por favor envie um email para ytalo@clubtodo.com com seu CV anexado - enviar no assunto: Vaga React-Native

## Labels

- Alocado
- Freela
- Júnior
- PJ
- Pleno
- Sênior

**Comment by ytalokaio** [comment]
Ainda estamos em processo de captação de currículos.

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
