### ISSUE TITLE
[Rio de Janeiro] Front-End Developer

### ISSUE THREAD

**Issue by richardrx** [frontendbr/vagas#95]
## Descrição da vaga

Busca-se front-end developer para vaga full time alocado, para desenvolver projeto de transformação digital na Oi.

## Local

Alocado, Rio de Janeiro

## Benefícios

- Ambiente descontraído
- Projeto desafiador e time experiente
- Otima remuneração 👍 

## Requisitos

- HTML, CSS3, JS e React

**Desejáveis:**
- AngularJs
- Firebase

**Diferenciais:**
- React

## Contratação / Salário

a combinar

## Como se candidatar

Por favor envie o email para asaprichard@gmail.com e haverá um pequeno teste, este deverá ser enviado diretamente para a responsável do projeto Leandra.Muniz@vmlbrasil.com com seu CV anexado - enviar no assunto: "Vaga: Front-end".

**Comment by paulo101977** [comment]
Boa tarde. Enviei meu curriculum para os e-mails informados.

**Comment by eduardojmatos** [comment]
@richardrx sabe se já preencheu a vaga? Nos avise pra mantermos ou removermos da lista :)

**Comment by richardrx** [comment]
Opa beleza?

Já preencheu sim, pode remover, me desculpa, na correria me esqueci disso.

Muito obrigado!

**Comment by eduardojmatos** [comment]
@richardrx sem crise! =D

**Comment by camilatigre** [comment]
@richardrx 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
