### ISSUE TITLE
[São Paulo] Front End Developer  na 5A Attiva

### ISSUE THREAD

**Issue by Ketllin** [frontendbr/vagas#950]
**Descrição da vaga**

## Alphaville

 Escritório, São Paulo - Alphaville

## Benefícios

- Vale Refeição R$ 26,00 dia
- Assistência Médica SulAmerica Saúde
- Convenio Farmácia (Desconto em Folha
- Parceria Sesc
- Convenio Odonto
-  Aux.Creche p/filhos até 6 anos.
- ...

## Requisitos

**Obrigatórios:**
- Consumo API
- HTML5
- CSS3
- React
- NodeJs
- ECMA Script 5 e 6
- Media Queries (Responsive Web Design)
- Otimização de Websites para mecanismos de busca (SEO)

## Contratação

CLT 

## 5A Attiva

Há quase quinze anos trabalhando com os principais players do mercado, a 5A Attiva é especialista em identificar profissionais de alta performance em Tecnologia da Informação, especialmente na área de desenvolvimento de software.

## Como se candidatar

Por favor envie um email para ketlin.pereira@5aattiva.com.br com seu CV anexado - enviar no assunto: Front End Developer

## Labels

- Alocado
- CLT
- Pleno

**Comment by eduardojmatos** [comment]
Essa vaga já está inativa por mais dias do que o permitido. Caso ainda tenha a vaga, reabra uma nova issue.

Mais informações: https://github.com/frontendbr/vagas#importante
