### ISSUE TITLE
[Remoto] - Front-End Pleno

### ISSUE THREAD

**Issue by highlabs** [frontendbr/vagas#952]
## Descrição da vaga

Precisamos de front-end para dois projetos, com duração de 30 dias no total:

**Criar site utilizando Nuxt.js**
O site receberá conteúdo via API. O front-end precisará apenas criar o HTML/CSS e receber os dados da API.

**Admin feito em Vue.js e Firebase**
Projeto já esta em andamentos, seria necessário adicionar alguns recursos e fazer debug. O admin é todo escrito em VueJS e todas as consultas vem do Firebase.

Projeto para 30 dias, iniciando na segunda semana de Abril (9 ~ 13).
O profissional deverá estar disponível de segunda a sexta, em horário comercial (negociável), utilizando o Discord da empresa.

## Local

Remoto Total

## Requisitos

**Obrigatórios:**
- Conhecimento intermediário em HTML/CSS/Javascript
- Conhecimento em Vue.js (desejável Nuxt.js também)
- Firebase

**Diferenciais:**
- React-native (para futuros projetos)
- Sentry
- Sass
- Eslint - Standard

## Contratação
R$ 3.500,00 - PJ 

## Nossa empresa

Somos uma pequena produtora precisando de ajuda em alguns projetos. :)

## Como se candidatar

Enviar email para: vagas@polya.pro com o assunto: **[Vaga] - Frontend**

## Labels

- Freela
- PJ
- Pleno
- Remoto - Total

**Comment by highlabs** [comment]
Vaga fechada, valeu! :)

**Comment by luga97** [comment]
still do you need a Vue JS developer? i have worked with this framework and the firebase APIs before.I don't know nuxt.js but i can learn it. Sorry for writing in english but i don't speak portuguese. I only speak English and Spanish (native lenguage), greetings!
