### ISSUE TITLE
[Rio de Janeiro] Front-End Developer Pleno na Original.io

### ISSUE THREAD

**Issue by guilhermemarconi** [frontendbr/vagas#953]
![.Original+GTX Expandindo experiências](http://originalmedia.vteximg.com.br/arquivos/original-io-recrutamento.png)

## Descrição da vaga

Estamos em busca de um Desenvolvedor Front-End Pleno com vontade de fazer a diferença no mercado de e-commerce, atuando na empresa que tem atuado com grandes marcas como Uber, Grupo Boticário, Grupo Technos, Sky, Renner e Nestlé, entre outros. Se você tem fome de aprendizado e se encaixa com o perfil da empresa, sinta-se à vontade para fazer o teste e vir trabalhar com a gente!

## Local

Centro, Rio de Janeiro

## Benefícios

- Plano de saúde
- VR de R$ 30,00/dia
- VT
- Folga de aniversário

#### Diferenciais

- Equipe multidisciplinar
- Ambiente descontraído
- Pingue-Pongue
- Video Game

## Requisitos

**Obrigatórios:**
- Conhecimento moderado em JavaScript
- Conhecimento moderado em Sass (SCSS)
- APIs REST
- Organização (afinal, HTML é organização :wink:)

**Desejáveis:**
- Vue.js
- Testes Unitários

**Diferenciais:**
- Webpack
- Interesse em aprender linguagens back-end (tornar-se fullstack)
- Projetos open source
- Experiência com a plataforma VTEX

## Contratação

- Presencial
- CLT
- Pleno

## Salário

R$ 3.500,00 inicial

## Nossa empresa

Transformamos sonhos e desejos em experiências digitais apaixonantes. Com soluções inteligentes e foco nas necessidades dos nossos clientes e na conversão, atuamos em diversas divisões de negócio, como B2C, B2B, marketplace, entre outras.

## Como se candidatar

- Fazer [esse teste](https://github.com/original-io/join-us).
- Enviar currículo para [cv@original.io](mailto:cv@original.io) com o assunto **Vaga Front-End Pleno** e, também, informar seu usuário daqui do Github, para que possamos mapear o seu teste no repositório. :wink:

## Labels

- Alocado
- CLT
- Pleno

**Comment by vititu** [comment]
O salário está correto?

**Comment by rodrigo-fonseca** [comment]
Se for esse salário mesmo, o que eles querem não é alguém com fome de aprendizado, mas fome no sentido literal

**Comment by guilhermemarconi** [comment]
@vititu e @rodrigo-fonseca de fato, o valor não estava correto. Recebi a descrição da vaga já feita e só colei aqui. Agora que vi os comentários e me atentei. Perdão.

Atualizei o valor aqui. Obrigado pelo feedback :)

**Comment by guilhermemarconi** [comment]
Abrimos mais uma vaga para este perfil!
Não quis criar uma nova já que a mesma continua em aberto, no mesmo formato.
