### ISSUE TITLE
[Remoto] Developer Front-End React na ADOPETS

### ISSUE THREAD

**Issue by lucasacw05** [frontendbr/vagas#955]
## Descrição da vaga

Como ReactJS e Native developer na adopets, você será responsável pelo desenvolvimento do melhor sistema de adoção de animais no mundo, atualmente presente em todo o território dos Estados Unidos pelas plataformas iOS e Web. Você trabalhará ao lado de um time multicultural e também *remoto*, com o objetivo de salvar os mais de 2.3 milhões de pets sendo eutanasiados todos os anos nos EUA pela ineficiência dos abrigos e sistemas de adoção. Para isso, você vai precisar ter muita paixão e dedicação, sem medo de errar, aprender e fazer cada vez melhor.

## Local

Remoto 

#### Diferenciais

- Horário flexível

## Requisitos

**Obrigatórios:**
- Ser apaixonado pelo que faz e querer melhorar o mundo através disso.
- Desejar criar disrupção no mercado através de propostas inovadoras.
- Domínio de HTML5 | CSS3 | LESS ou SASS
- Experiência com ReacjJS
- Experiência com ECMAScript 6
- Experiência com Git para versionamento de código
- Experiência com POO
- Experiência em SEO
- Conhecimento aprofundado em sólidos princípios de programação
- Conhecimentos em otimização para performance de Front-end
- Nível de Inglês intermediário

**Diferenciais:**
- Experiência com React Native
- Experiência com UI e UX
- Atenção a detalhes 
- Experiência com Interfaces customizadas e animações
- Nível de inglês avançado

## Contratação

PJ a combinar

## Nossa empresa

A adopets é uma startup Estadunidense fundada por Brasileiros, em Boston, MA, que tem o objetivo de transformar/salvar a vida de milhões de animais e pessoas através da adoção eficiente e consciente. Somos ambiciosos e determinados a resolver um problema global através de uma tecnologia simples de usar e acessível, tanto para abrigos de animais quanto para adotantes. Atualmente estamos presentes apenas nos Estados Unidos, mas já planejamos estar no Brasil até o final de 2018.

Somos atualmente um time multicultural de 7 pessoas, entre brasileiros e estadunidenses, portanto, um domínio intermediário de comunicação em inglês (leitura/escrita/conversação) é fundamental. Não buscamos ninguém perfeito, ou com o inglês perfeito, pois todos no time sempre temos muito a melhorar, mas é ideal que um boa comunicação seja possível de ser estabelecida para uma equipe forte e integrada.

## Como se candidatar

Por favor envie um email para lucas@adopets.org com seu CV anexado - enviar no assunto: Vaga React Native

## Labels

- alocação/Remoto
- experiência/Júnior
- experiência/Pleno
- experiência/Sênior

## Labels

- PJ
- Júnior
- Pleno
- Sênior
- Remoto - Total

**Comment by lucasacw05** [comment]
Opa Sylas, tudo bom?

Você pode me enviar seu cv e conversamos melhor amanhã pela parte da tarde?

Abraço!











Em 4 de abril de 2018 21:20, Sylas Eckart Macena <notifications@github.com>
escreveu:

**Comment by camilatigre** [comment]
@lucasacw05 essa vaga ainda está aberta?

**Comment by wchad** [comment]
Boa tarde!

Segue meu curriculo online: http://walacesilva.com.br
Perfil linkedin: https://www.linkedin.com/in/walacesilva

Att,
