### ISSUE TITLE
[Joinville/SC] Front-End Developer @ Fesc

### ISSUE THREAD

**Issue by gamichalski** [frontendbr/vagas#958]
## Descrição da vaga
Buscamos desenvolvedores que respirem tecnologia, busquem sempre inovar e propor novas soluções, pessoas que gostem muito de desafios.

Utilizando VueJS, você será responsável pelo desenvolvimento do e manutenção do nosso Framework. Para isso, você vai precisar ter muita paixão e dedicação, sem medo de errar, aprender e fazer cada vez melhor.

### Benefícios
- Salario compatível com o cargo e sua experiência
- Plano de Saúde
- Vale Alimentação
- Vale Transporte

### Requisitos
- Experiência em desenvolvimento web
- Conhecimento sólido em JavaScript

### Diferenciais:
- Vuejs
- Git
- Node.js
- Webpack

Enviar um email para gmichalski@fesctecnologia.com.br

**Comment by Murillofilho86** [comment]
Qual é o grau de experiência?

**Comment by brunokunace** [comment]
Estou em busca de um trabalho com VueJs,  mas como a distância é grande,  necessito que seja Remoto ou que tenha opção de trabalhar remoto após um tempo. 

Existe esta opção?  Qual valor do rendimento mensal?

**Comment by johanguse** [comment]
Viva ao VUE!!! É Unimed? Legal....

**Comment by jotavejv** [comment]
Ganhou like so pelo VueJS 👍
