### ISSUE TITLE
[São Paulo] Analista de UX / Designer de Interface

### ISSUE THREAD

**Issue by joaovarandas** [frontendbr/vagas#96]
## Descrição da vaga

O profissional irá atuar como designer de interfaces de soluções de CRM para Web e Mobile, prevendo melhores práticas e a melhor experiência do usuário;

## Local

Escritório, São Paulo - Brooklin

## Requisitos

**Obrigatórios:**
- Um perfil inovador, comprometido e focado na identificação e resolução de problemas. 
- Criatividade e um senso estético semelhante ao nosso;
- 3 anos de experiência com desenvolvimento de interfaces de aplicações / análise de UX;
- Sólidos conhecimentos em HTML e CSS;
- Sólidos conhecimentos e utilização de pre-compiladores de CSS;
- Experiência com Photoshop ou ferramenta semelhante;

**Diferenciais:**
- Um portifólio bem montado;
- Conhecimentos em Linguagens de Programação (Java, JavaScript);
- Certificações ou experiência relevante em áreas de tecnologia;
- Desenvolvimento mobile nativo e/ou híbrido;

## Contratação

CLT Cotas 

## Nossa empresa

Se você é apaixonado por tecnologia e quer trabalhar em uma empresa inovadora, o momento é esse. A Plusoft, pioneira no desenvolvimento de soluções multicanais para a Gestão de Relacionamento com Clientes no Brasil, está ampliando o seu quadro de funcionários e buscando profissionais de frontend.  

A Plusoft desenvolve soluções de atendimento e CRM, dentro do conceito de multicanalidade, proporcionando a melhor experiência ao cliente em todos os pontos de contato e, ao mesmo tempo, promovendo a redução dos custos operacionais.

http://www.plusoft.com.br

## Como se candidatar

Por favor envie um email para joaovarandas@plusoft.com.br com seu CV anexado - enviar no assunto: 
[frontendbr] Analista de UX / Designer de Interfaces

**Comment by joaovarandas** [comment]
Vaga preenchida!

Valeu pessoal ...

**Comment by LFeh** [comment]
Aee \o

**Comment by camilatigre** [comment]
@joaovarandas 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by joaovarandas** [comment]
Sim!

---
João Paulo Varandas
jpvarandas@gmail.com
+55 11 99889-2321
