### ISSUE TITLE
[Barueri] Front-End Developer na English Live

### ISSUE THREAD

**Issue by AnaBaldoino** [frontendbr/vagas#960]
##Descrição da empresa:
A maior escola de inglês online do mundo!
Fomos criada com um intuito de ajudar alunos ocupados a aprender inglês. Evoluímos muito, estamos ao vivo 24 horas por dia. Ensino online fácil, prático e flexível, para os alunos aprenderem onde e quando quiserem.
Somos empreendedores pioneiros, temos paixão pelo que fazemos, e queremos inovar ainda mais.
Se você se identifica com esses valores nós queremos você conosco.

##Atividades:
Desenvolver o novo site da empresa junto ao desenvolvedor Backend.
Pensar em otimização através de código para a melhor experiência do usuário e melhor desempenho do site e landing pages.
Apoio e suporte ao Diretor de Arte e Gerente de Marketing com foco em otimizar os resultados de vendas

Barueri - Alphaville
Salário a combinar

## Benefícios

Assistência médica, Assistência odontológica, Auxílio creche, Auxílio Educação, Auxílio farmácia, Seguro de Vida, Vale-refeição, Vale-transporte e curso de idiomas.

## Requisitos

**Obrigatórios:**
- Ensino superior cursando ou completo em áreas correlatas
- 3 anos de experiência em desenvolvimento front end
- Domínio - HTML5 e CSS3, Javascript, Angular, AngularJS, Ember.js, ReactJS, JQuery, Bootstrap, Foundation, LESS e SASS, Tableless e webstandards validável no W3C,  

**Desejáveis:**
- Photoshop, Axure, UX, XD ou Sketch, PHP, CMS CQ5, C#, Java e Asp.net
- Inglês intermediário

## Como se candidatar

Por favor envie um e-mail para ana.baldoino@englishlive.com com seu CV anexado - enviar no assunto: Vaga Front end

**Comment by Annatsu** [comment]
Tem certeza que os requisitos obrigatórios estão corretos?

**Comment by AnaBaldoino** [comment]
Sim, por qual motivo?




Ana Carolina Baldoino

Organization Human Development, EF English Live


Tel: +55 11 2870-3957

Skype: ana.baldoino.ef


Al. Rio Negro, 500 – Torre B, 11º andar, Conj.1114

CEP: 06454-000, Barueri, SP, Brasil

www.englishlive.com.br<http://www.englishlive.com.br/>


[http://englishtownbrasil.com.br/mail/2016/10-oct/419-assinatura-nova/assinatura-2016-escolhida.jpg]<http://www.englishtown.com.br/>

**Comment by AnaBaldoino** [comment]
Pessoal,

Corrigimos alguns detalhes na vaga, mas de qualquer forma todos os currículos recebidos serão avaliados de acordo com os requisitos.

Obrigada.
