### ISSUE TITLE
[São Paulo] Front-End Developer na Centauro

### ISSUE THREAD

**Issue by leitao-bcc** [frontendbr/vagas#965]
## Descrição da vaga

A maneira como as pessoas compram produtos mudou muito nos últimos anos e essa revolução está apenas começando!
 
Á área de inovação da Centauro está olhando para o amanhã para entender como, através de tecnologia, podemos auxiliar nossos consumidores em sua jornada do esporte.
 
Se você gosta de construir novos produtos digitais, é apaixonado pelo consumidor, se sente bem em trabalhar em um ambiente de constantes mudanças e já trabalhou em uma equipe ágil rodando Scrum, essa vaga é pra você.

## Local

Escritório, São Paulo - Lapa

## Requisitos

**Técnicos**
- Lógica de Programação
- Conhecimentos básicos em HTML/CSS
- Conhecimento em JavaScript
- Conhecimento em alguma ferramenta de versionamento (Git, SVN, etc)

**Desejáveis:**
- Atitude pró ativa frente a mudanças
- Paixão pelo consumidor
- Foco no resultado
- Alguma experiência com startups

## Contratação

PJ a combinar

## Nossa empresa

Inovação na Centauro

## Como se candidatar

Gostou da vaga e acha que se encaixa? Para começar temos uma provinha bem simples apenas conhecer mais sobre você.  Faça a prova no link https://is.gd/PDusRs

Lembrando que essa prova não é eliminatória.

Boa sorte!

## Labels

- Presencial
- Estágio
- Júnior
- PJ
- Pleno
- Sênior

**Comment by LucasCastelo** [comment]
Respondido rs, adote um junior.
