### ISSUE TITLE
[Remoto] React-Native developer (iOS e Android)

### ISSUE THREAD

**Issue by DragonGlobe** [frontendbr/vagas#967]
## Descrição da vaga

Procuramos desenvolvedor com experiência em REACT-NATIVE para desenvolver aplicativos em iOS e Android.
A vaga é PJ pois estamos em fase seed captando investimentos, pretendemos formar equipe fixa, inclusive com possibilidade de migração para o país onde fica nossa matriz, nosso objetivo é crescer junto com o funcionário.

## Local

- Totalmente remoto

## Benefícios

- Remuneração acima da média e em euro
- Horários extremamente flexíveis

#### Diferenciais

- Possibilidade de efetivação (inclusive em outro país)
- Muita liberdade, poucas reuniões e você praticamente faz todo o seu horário
- 100% remoto
- Utilizamos uma gestão onde discutimos as fases do projeto em conjunto, chegando a prazos realistas
- Possibilidade de bônus por produtividade (em dinheiro, nada de videogame e outras coisas só pra fazer gracinha)
- Somos adeptos da @startupdareal e @vagastnc, sendo transparentes e falando a real, aqui não enfeitamos nada e não somos “highstakes de palco”

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento Mobile (React Native) em iOS e Android
- Experiência com Redux
- Conhecimento em html, css, javascript e JSON avançados
- Experiência no uso de Slack, Aptana (desejável) e Skype
- Excelente lógica de programação
- Possuir Mac
- Inglês básico

**Desejáveis:**

- Experiência em Node.js (desejável)

**Diferenciais:**

- Ser comunicativo

## Contratação

- PJ a combinar (com possibilidade de efetivação, inclusive em outro país)

## Nossa empresa

Somos uma startup localizada no exterior que atua na área médica e de serviços, estamos em estágio seed (sem produto lançado ainda) e pretendemos nos expandir rapidamente para outros países

## Como se candidatar

- Por favor, envie e-mail com portfólio e falando sobre suas experiências e sobre você para reactnative@dragonglobe.pt

## Labels

- PJ
- Remoto - Total

**Comment by juanmagalhaes** [comment]
Muito interessante!!! 🤔

**Comment by thiagolavor** [comment]
Para quem esta começando pode se candidatar ?

**Comment by paulo101977** [comment]
Se fosse CLT, eu estaria dentro.
