### ISSUE TITLE
[São Paulo] Front-End Developer no Moip

### ISSUE THREAD

**Issue by caioincau** [frontendbr/vagas#969]
Freela Front end

O Moip está em busca de um desenvolvedor front end  experiente para atuar como freelancer alocado por até 2 meses. É uma ótima oportunidade de trabalhar com uma equipe de alta performance e participar da próxima geração de produtos financeiros do Brasil. 

## A empresa

O Moip
O Moip é uma das maiores e mais inovadoras Fintechs do Brasil. Desde 2009 estamos usando a tecnologia para oferecer a próxima geração dos serviços de pagamento online. Atualmente ampliamos nosso escopo, introduzindo novos produtos, e estamos redefinindo a forma que nossos clientes lidam com a vida financeira.

O papel do Front end no time de interface
O desenvolvedor deve ter autonomia para implementação de features novas e investigação de problemas em produção. Espera-se que consiga contribuir nas discussões técnicas sobre problemas e arquitetura.

Participar ativamente de todo o processo de desenvolvimento de software;
Desenvolver código limpo, testável e de fácil manutenção;
Compartilhar conhecimento com o time, com a comunidade e com a empresa; 

Requisitos 
Aplicar apenas se você dominar:
HTML/CSS
LESS
JavaScript
Vue.js
Experiência com integração de APIs Rest
Git

Desejável
Node.js
Experiência com testes
GRAPHQL

## Contratação

PJ a combinar, por dois meses.

## Como se candidatar

Por favor envie um email para filipe.santos@moip.com com seu CV anexado - enviar no assunto: Vaga Front-End

Se possuir, enviar projetos no github e afins.

## Labels

- Alocado
- PJ
- Freela
- Pleno

**Comment by ednilsonamaral** [comment]
Está retornando o e-mail, **Mail Delivery Subsystem**..

**Comment by caioincau** [comment]
Opa, pode fechar por favor, a vaga foi finalizada há algum tempo. @LFeh
