### ISSUE TITLE
[Curitiba] Front-End Developer Freela

### ISSUE THREAD

**Issue by jamirmachado** [frontendbr/vagas#975]
## Descrição da vaga

Estamos com uma posição temporária para desenvolvedor front-end freela para trabalhar com WordPress! O desenvolvedor não precisa ter grande experiência com lógica e PHP, mas precisa ter experiência com a estrutura de templates de WordPress e suas tags.

## Local

*Curitiba*
_Existe a possibilidade de ser remoto! Mas vamos dar sempre preferência aos candidatos presenciais.
No caso de trabalho remoto, vamos fazer checkpoints diários via conferência com o restante do time participante do projeto. O desenvolvedor vai trabalhar em dos nossos projetos mais estratégicos._

#### Diferenciais

- Mac, Windows ou Linux, você escolhe
- Ambiente descontraído com dress code informal (você pode vir trabalhar de bermuda se quiser)
- Sala de jogos com PS4 e um fliperama para tirar uns contras
- Máquina de expresso livre
- Happy hours, festas e churrascos estão no nosso dia-dia

## Requisitos

**Obrigatórios:**
- Sólidos conhecimentos de HTML 5
- Você domina CSS e não o contrário
- Você se vira muito bem com pré processadores como SASS, LESS, POSTCSS
- Você consegue se virar bem com Javascript
- Experiência com Git
- Boa comunicação e gostar de trabalhar em equipe

**Diferenciais:**
- Experiência com Agile
- Experiência com API's
- Experiência com lógica, php e MySQL

## Contratação

Freela alocado ou remoto.

## Como se candidatar

Por favor envie um email para dev@bluefoot.com.br com seu CV anexado, seu perfil no Github e pelo menos 3 trabalhos seus com WordPress explicando sua participação neles.
*Não vamos considerar jobs com templates prontos*.

Enviar no assunto: Vaga Front-end Developer Freela

**Comment by jamirmachado** [comment]
Tags: Alocado, Remoto, Pleno, Sênior, PJ

**Comment by renanlara** [comment]
Existe possibilidade de algum tipo de contratação sem ser freela?

> _Não vamos considerar jobs com templates prontos._

Pra mim pode ser o ideal, pois todos os projetos que desenvolvo em WordPress são do zero.

**Comment by jamirmachado** [comment]
@renanlara Temos duas vagas CLT aberto para desenvolvedor front-end rolando aqui também =)
Mas pra esse job específico de WP, é freela mesmo. Se tiver interesse nas outras vagas, você pode conferir aqui: https://www.linkedin.com/jobs/cap/view/620026139/

**Comment by degaus** [comment]
Enviei 👍

**Comment by clmadrazo** [comment]
Têm alguma outra vaga de trabalho remoto mas que não seja temporário?

**Comment by andrebrandaoo** [comment]
Enviado

**Comment by jamirmachado** [comment]
@clmadrazo remoto não, somente alocado.

Aproveitando o espaço, recebemos muitos profissionais nos último dias, não se preocupem que todos serão respondidos beleza? Valeu gente!
