### ISSUE TITLE
[Porto Alegre] Front-End Developer na Lighthouse

### ISSUE THREAD

**Issue by donnes** [frontendbr/vagas#977]
## Descrição da vaga

O foco da empresa é o desenvolvimento de aplicativos em React Native, porém as vezes ainda surgem trabalhos que exigem conhecimentos em desenvolvimento web. O candidato que ingressar na equipe, será alocado inicialmente para algum projeto web enquanto busca aprender (caso ainda não saiba) as tecnologias usadas pela equipe para desenvolvimento mobile.

Estamos buscando pessoas que queiram crescer profissionalmente e que sejam autossuficientes para buscarem diariamente as melhores práticas em desenvolvimento de software.

## Local

Escritório - Porto Alegre - Av. Carlos Gomes

## Requisitos

**Obrigatórios:**
- Ótimo entendimento de Javascript
- HTML5/CSS3
- Sass
- Mobile-first
- Node package managers (NPM e YARN)
- Ter vontade de aprender ReactJS, React Native e outras tecnologias
- Ser autossuficiente e aprender rapidamente

**Desejáveis:**
- Conhecimentos em Java, Swift e Object-C
- Conhecimentos com ReactJS e React Native
- Conhecimentos com VueJS
- Conhecimentos com JSX
- Conhecimentos com PWA

**Diferenciais:**
- GraphQL

## Contratação

PJ a combinar

## Nossa empresa

A @LighthouseIT é uma start-up em constante crescimento e com uma base de clientes de grandes nomes em diversos tipos de seguimentos. Nosso maior foco é criar aplicativos incríveis e realmente relevantes para os usuários.

## Como se candidatar

Por favor envie um email para andre.romero@lighthouseit.com.br com seu CV anexado - enviar no assunto: Vaga Front-End Developer

**Comment by alinebastos** [comment]
Oi, @donnes, como seria o remoto parcial?

**Comment by donnes** [comment]
Oi @alinebastos, remoto parcial se resume a você poder, quando necessário, trabalhar de casa ou do lugar que preferir. Seria algo como 80% no office e 20% home. Ex.: Dias chuvosos, não estar se sentido legal, etc.

**Comment by lbighetti** [comment]
@donnes Então a vaga é presencial, né?
Sugiro remover `remoto` do local da vaga.

**Comment by alinebastos** [comment]
Isso seria mais um home-office ocasional, poderia estar entre os benefícios da empresa :)

**Comment by donnes** [comment]
@LFeh Pode remover o label `remoto - parcial` pois acredito estar confundindo os candidatos.

Apenas para deixar claro, permitimos trabalhar remotamente mais frequentemente, mas é importante entenderem que alguém recém chegado na empresa, precisa se adaptar ao modo de trabalho e ganhar confiança para tal. Mas sim, somos bem liberais com home-office.

Outras dúvidas estou a disposição. :D

**Comment by pacheco7** [comment]
Prezado @donnes, boa tarde!

Não creio que nós, candidatos, estamos confusos com sua vaga. Uma vez que está fora descrita como “Remoto” tanto em seu texto principal quanto por label. Encerro
por sugir o cuidado ao retratar maiores detalhes quanto a descrição da vaga para que estes erros não ocorram. 

Abs,

**Comment by donnes** [comment]
@pacheco7 Concordo, admito não ter percebido o `Remoto` no texto. Ajustei a descrição para ficar mais clara nossa visão. 👍
