### ISSUE TITLE
Vagas Front-end Developer

### ISSUE THREAD

**Issue by mmarinaamaral** [frontendbr/vagas#978]
==================================================
Oi Pessoal! 

Fizemos uma lista de vagas para desenvolvedores front-end, filtrada por experiência necessária, cidade, empresa e nota na Love Mondays!
Queremos que você gaste seu tempo procurando impressionar o contratante ao invés de desperdiçá-lo buscando oportunidades de trabalho em diversos sites diferentes.

https://goo.gl/UXWMWW

Front-End Developer = ContrateDevs
==================================================

**Comment by renanlara** [comment]
Ué...
Por isso temos o repositório de vagas aqui.

**Comment by LFeh** [comment]
as ideia
