### ISSUE TITLE
[Curitiba] Front-End Developer no Grupo Polvo

### ISSUE THREAD

**Issue by aline-matos** [frontendbr/vagas#979]
## Descrição da vaga

Se para você programar é muito mais do que conhecer linguagens de programação, essa vaga pode ser o que procura! Procuramos um desenvolvedor front-end entusiasta e apaixonado por novas tecnologias, com espírito de equipe e pró atividade. 

## Local

Shopping Itália - Curitiba

## Requisitos

**Obrigatórios:**
- Profundo conhecimento em HTML, CSS e JS
- React/Redux
- Bom conhecimento em qualquer outra linguagem de programação;
- Saber utilizar bem Node/NPM, Composer, Git e JIRA;
- Inglês básico

**Desejáveis:**
- React Native
- PHP
- Blade (Laravel)

## Contratação

CLT

## Nossa empresa

Somos uma agência full service que mergulha no negócio do cliente para elaborar e executar estratégias personalizadas e comprometidas com resultados.

## Como se candidatar

Efetuar o teste 
https://www.figma.com/file/E9nCB9jXkJKBLH71ljdnZ80k/Desafio-Desenvolvedor-Front-End---Grupo-Polvo, enviar um e-mail com o seu CV anexado para rh@polvo.com.br e no assunto mencionar "Vaga Front-End Developer"

**Comment by aline-matos** [comment]
Olá @maugravena aceitamos sim! :)

**Comment by Annatsu** [comment]
Boa tarde, @aline-matos .

A vaga é somente alocado ou vocês aceitam remoto?
Moro em Rio Grande :)

**Comment by aline-matos** [comment]
Obrigada @Annatsu , mas preferimos presencialmente!

**Comment by matheusmazeto** [comment]
A vaga ainda esta aberta?

**Comment by gsantiago** [comment]
@matheusmazeto sim
