### ISSUE TITLE
[São Paulo] Desenvolvedor FrontEnd

### ISSUE THREAD

**Issue by robinae** [frontendbr/vagas#98]
## A DBR.ag precisa de você!

Quer trabalhar em projetos desafiadores? Vem fazer parte de um time que respira inovação.
## Local

Escritório, São Paulo - Lapa
## Requisitos
- HTML5
- Sass
- Javascript
- Git
- Gulp / Grunt

**Desejáveis:**
- Experiência em e-commerce (OpenCart)
## Contratação

PJ a combinar
## DBR.ag

Evoluindo há 14 anos, trabalhamos com um modelo híbrido de consultoria e de agência de inteligência digital, ajudando empresas a gerar impacto em pessoas através do bom uso da tecnologia.
## Como se candidatar

Inscreva-se no link e nos mande o seu desafio: http://vagas.dbr.ag/front.
Dúvidas? Envie um e-mail: vagas@dbr.ag.

**Comment by eduardojmatos** [comment]
@robinae já preencheu a vaga? Nos avise pra mantermos ou removermos da lista :)

**Comment by camilatigre** [comment]
@robinae 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza
