### ISSUE TITLE
[Belo Horizonte] Front-End Developer na Sympla

### ISSUE THREAD

**Issue by marinapraca** [frontendbr/vagas#980]
## Descrição da vaga
Porque o Desenvolvedor Frontend é importante para nós? Como membro da equipe de Produto, você será responsável pela elaboração de novas ferramentas, manutenção das ferramentas existentes e pela tomada de decisões relacionadas à arquitetura das aplicações e dos microsserviços que compõem o ecossistema da Sympla.

Seus desafios serão:

- Contribuir com tomada de decisões de todos os processos de desenvolvimento, passando desde a escolha das tecnologias utilizadas até os processos de build/deploy;
- Auxiliar a manter um "espírito" ágil;
- Se orgulhar de colocar em produção código que é usado por milhões de pessoas Brasil afora. :)
- Assegurar a melhor qualidade de experiência para nossos usuários.
- Garantir a qualidade de funcionamento de cada entrega com foco na UI.

## Local

Escritório, Belo Horizonte - Savassi

## Oferecemos:
-Ambiente criativo, inovador e estimulante;
-Salário compatível com o mercado, VT e VR;
-Plano de Saúde e Odontológico;
-No dress code (pode trabalhar de bermuda, chinelo, etc);
-Clima descontraído;
-Café, bebidas variadas e snacks.
-Horário flexível :)
-40h semanais, de segunda a sexta.  

##O que buscamos?

Procuramos pessoas que buscam ser protagonistas de sua carreira e que queiram construir junto novos processos e contribuir para soluções inspiradoras. Além disso:

-Experiência de atuação como Frontend;
-Ter atuado com alguns frameworks modernos: AngularJS, ReactJS, Vue.JS etc;
-Conhecimento e prática com arquitetura Restful;
-Ter um amplo conhecimento das ferramentas do ecossistema de front-end, em geral: Webpack, Gulp, Grunt, npm, etc;
-Conhecimentos avançados em Javascript, HTML5 e CSS3;
-Ter senso crítico e se preocupar com UI;
-Conciliar demandas e prazos comerciais com qualidade de engenharia;
-Boa comunicação e trabalho em equipe;
-Ser proativo trazendo sempre novas ideias para resolvermos nossos desafios;
-Seguir as tendências do mercado e que seja capaz de se adaptar rapidamente a novas tecnologias;
-Ter senso de organização, atenção a detalhes e foco;
-Must rock!

Alguns diferenciais para a função:

-Profunda compreensão do DOM e suas propriedades;
-Experiência com NodeJS;
-Experiência com ferramentas de testes (TDD, Testes unitários, etc);
-Inglês e/ou espanhol intermediário;
-Conhecer os conceitos de startup.

## Contratação

CLT

## Nossa empresa

Simplicidade é nosso nome e sobrenome. Somos a maior plataforma de venda de ingressos e gestão de eventos do Brasil e temos orgulho de ter tecnologia e design no nosso DNA. Acreditamos em experiências acessíveis, agradáveis e inspiradoras, que simplifiquem a vida das pessoas. Para acompanhar o crescimento da Sympla estamos escalando nosso time de Produto e Desenvolvimento e para isso buscamos pessoas incríveis!
Nosso time atua sempre com foco nos melhores resultados, construímos juntos, somos analíticos e pensamos em todo o contexto para entregar com qualidade a melhor experiência para nossos clientes, entendendo seus dilemas.

## Como se candidatar

Se o seu perfil corresponde ao que acreditamos, venha fazer parte do nosso time!!!
Link para se candidatar: https://sympla.recruitee.com/o/desenvolvedor-frontend-senior-belo-horizonte

## Labels

- CLT
- Sênior
- Pleno
- Júnior

**Comment by wesley1710** [comment]
Olá, a vaga é somente para alocado no escritório ou existe possibilidade de trabalho remoto?
