### ISSUE TITLE
[Remoto] React / React Native Dev na EmCasa

### ISSUE THREAD

**Issue by gusaiani** [frontendbr/vagas#983]
## Descrição da vaga

Procuramos 2 desenvolvedores(as) excepcionais para a [EmCasa](https://www.emcasa.com).

React e/ou React Native. 

Remuneração competitiva e possibilidade de equity.

## Local

Remoto

## Requisitos

- Domínio do React e/ou React Native
- Saber trabalhar em equipes distribuídas
- Escrever bem
- Bom Inglês

## Nossa empresa

Nossa missão é transformar a experiência de compra e venda de imóveis residenciais, desde a primeira visita (todos nossos imóveis hoje têm tour 3D) ao financiamento e compra do apartamento (atendimento individualizado e processos que permitem um foco da nossa equipe nos pontos mais cruciais do processo). 

Começamos em novembro de 2017 e hoje somos uma equipe de 10 pessoas (4 devs), acelerada pela Harvard University, com bom funding e crescimento acelerado.

Seu trabalho vai impactar a empresa imensamente desde o início. Você vai fazer parte de um time que já criou e trabalhou em empresas de relevância nacional e internacional, com espaço e incentivo para seu desenvolvimento e crescimento profissional.

## Como se candidatar

Preencha 4 campos simples em https://docs.google.com/forms/d/1FIoJIqPfMLbh9qVj8ODJUNK08_yX_DbfhrRtF9oOWwA/edit

## Labels

- Remoto
- CLT
- PJ
- Sênior

**Comment by tunnes** [comment]
Caramba, bacana o conceito utilizado, parabéns pelo app!

**Comment by gusaiani** [comment]
Obrigado @tunnes :)
