### ISSUE TITLE
[São Paulo] Front-End Developer na Atech

### ISSUE THREAD

**Issue by adrianobisca** [frontendbr/vagas#984]
## Descrição da vaga

Desenvolvimento, implementação e concepção de novas features, alteração/criação de arquitetura da camada de front-end dos projetos.

​Atividades:
- Atuar com time de design na criação de soluções junto do time de desenvolvimento;
- Melhoria dos processos/metodologia aplicada ao trabalho de desenvolvimento front-end;
- Desenvolvimento de protótipos/mockups;
- Criação e manutenção de softwares/sistemas internos e externos.

## Local

Escritório, São Paulo - Vila Olímpia

## Benefícios

- Plano de saúde
- Plano dental
- Seguro de vida
- VR, VT
- Auxílio creche
- Gympass
- PLR
- Previdência Privada - EmbraerPrev
- Cooperemb

## Requisitos

**Obrigatórios:**
- HTML, CSS, JavaScript avançados;
- Conhecimento de Frameworks responsivos (Bootstrap, Material, etc);
- Conhecimento de Frameworks front-end (Angular, Meteor, React, etc);
- Experiência com pré-processadores de css (Sass ou Less);
- Desenvolvimento de interfaces, tanto no planejamento quanto na codificação.

**Desejáveis:**
- Experiência com automatizadores de pacotes (NPM, Gulp, Grunt, etc);
- Experiência em controle de versão (Git ou Svn);
- Conhecimentos básicos de design com foco em interfaces (tipografia, layout);
- Noções de usabilidade, acessibilidade e conceitos de UX;
- Noções de arquitetura de informação/design de interação;
- Familiaridade com guidelines de UI.

## Contratação

CLT

## Nossa empresa

A [Atech ](https://www.atech.com.br/)é uma empresa do Grupo Embraer especializada no desenvolvimento de soluções para missões críticas e tecnologias para apoio à tomada de decisão. Líder em concepção, desenvolvimento, integração, manutenção e gestão de soluções para problemas complexos e que, ao longo dos anos, construiu forte domínio tecnológico em segmentos que demandam alta sofisticação, atuando em todo o ciclo de vida da engenharia de sistemas.

## Como se candidatar

Por favor envie um email para uxui@atech.com.br com seu CV anexado.

## Labels

- Alocado
- CLT
- Pleno

**Comment by wensch** [comment]
Enviado 👍

**Comment by adrianobisca** [comment]
Caso tenham qualquer duvida, estou a disposição.
Obrigado.

**Comment by wensch** [comment]
@adrianobisca Enviei meu currículo e ainda não recebi nenhum feedback sobre a vaga

**Comment by adrianobisca** [comment]
@wensch Desculpa a demora no retorno. Acabamos de enviar uma resposta. Obrigado.

**Comment by charleslcsantos** [comment]
Oi @adrianobisca a vaga ainda está aberta?
