### ISSUE TITLE
[São Paulo] Front-End Developer - Wordpress na MadGO

### ISSUE THREAD

**Issue by joelsantosbr** [frontendbr/vagas#986]
## Descrição da vaga

Estamos procurando pessoas que gostem de trabalhar com Wordpress.
**Presencial sem disponibilidade para remoto.**

## Local

Escritório na Rua Adolfo Araujo, 89 - Jardim Sao Paulo

## Benefícios

- VR e VT

#### Diferenciais

- Equipe descolada
- Experiência com diversas áreas

## Requisitos

**Obrigatórios:**
- Desenvolver sites recebendo um PSD (photoshop p/recortes)
- Domínio de HTML, CSS e responsivo
- Conhecimento básico de JS (JQuery)
- Conhecimento básico Wordpress (vontade de aprender)

**Desejáveis:**
- Git
- Conhecimento em Hospedagens/Cpanel

**Diferenciais:**
- Projetos em Wordpress
- Gulp
- Stylus/Sass/Less
- ACF - Advanced custom fields

## Contratação

PJ a combinar

## Nossa empresa

Mad Good Ones é a alma, nossa essência, o que nos inspira, nosso slogan, nosso espírito.

MadGO é a Agência de Design, Webdesign e Marketing Digital, que leva nas costas o espírito Mad Good Ones, aplicando o conceito aos negócios, visando a geração de leads e negócios na internet.

É isso! Go! Sempre em frente. 
Evoluindo. Sonhando. Criando. Crescendo.

## Como se candidatar

Por favor envie um e-mail para joel.santos@madgo.com.br com seu CV anexado/carta de apresentação/portfólio e pretensão salarial - enviar no assunto: **Vaga Front-end Wordpress**

## Labels

- Alocado
- Júnior
- Estagiário
- PJ

**Comment by ribeiroevandro** [comment]
Existe a possiblidade de freelas remoto?

**Comment by adeonir** [comment]
Também gostaria de saber se existe a possiblidade de freelas remoto?

**Comment by renanlara** [comment]
Curtir a vaga, preencho todos os requisitos, mas pena que é para Júnior e não é remoto.

**Comment by MatCunha** [comment]
Gostei muitíssimo da vaga, já enviei as informações.

**Comment by danieladuarteng** [comment]
enviado

**Comment by vinirossi** [comment]
vaga em aberto ainda? @joelsantosbr
