### ISSUE TITLE
[São Paulo] Dev. JS Sênior na EvolutionIT

### ISSUE THREAD

**Issue by igor9silva** [frontendbr/vagas#987]
### EvolutionIT

Somos uma consultoria de TI jovem, porém madura, que combina em seu time profissionais com larga vivência em projetos de TI de elevada complexidade a uma equipe de desenvolvedores e especialistas nas mais recentes tecnologias para as áreas de Business Intelligence e Mobilidade Corporativa.

## Local

São Paulo - Barra Funda (1 quadra do metrô)

#### Diferenciais

- Participar do desenvolvimento de soluções de mobilidade corporativa para diversos clientes
- Oportunidade de trabalhar em empresa 100% nacional com tecnologias de ponta
- Liberdade para propor novas atividades, processos e metodologias
- Horário flexível, ambiente descontraído, escritório a menos de 5 minutos do metrô Barra Funda

## Requisitos

**Obrigatórios:**
- JavaScript avançado
- Versionamento com GIT
- Inglês avançado
- Boas práticas
- REST
- Pelo menos um framework (Angular, React, ...)
- LocalStorage
- Habilidade para trabalhar em equipe.

**Desejáveis:**
- Cordova
- OData
- Bootstrap
- jQuery
- IndexedDB
- SQL (SQLite)

## Contratação

PJ, a combinar

## Como se candidatar

Por favor envie um email para igor.silva@evolutionit.com.br com seu CV anexado - enviar no assunto: Vaga JS Sênior

## Labels

- Alocado
- PJ
- Sênior

**Comment by nandosangenetto** [comment]
Faltou o nome da empresa no título 😄
