### ISSUE TITLE
[Rio de Janeiro] Full-Strack Developer Pleno na Sensorial Comunicação

### ISSUE THREAD

**Issue by didiraja** [frontendbr/vagas#988]
## Descrição da vaga

Imagine só você aqui no nosso time Sensorial? Estamos procurando alguém para **Full Stack Developer - Pleno**. 

**O que você vai fazer?**
- Desenvolvimento de Landing Page.
- Ajustes e correções em Landing Page.
- Desenvolvimento e Manutenção de sites Wordpress
- Instalação e ajustes de ferramentas em Landing Page.
- Otimizações em sistema interno de CRM (gerenciamento de contato e envio de e-mails com roleta).
- Correção de Bugs em sistema interno de CRM.

## Local

Ilha da Coroa, 3 - Barra da Tijuca (próximo ao Metrô Jardim Oceânico)

## Benefícios

- Passagem
- Alimentação

#### Diferenciais

- 2 horas de almoço
- Quarto do descanso
- Casa grande com piscina e vista/saída pro mar

## Requisitos

**Obrigatórios:**
- Conhecimento intermediário em HTML/CSS/JS
- Conhecimentos intermediários em PHP e MySQL.
- Noções de GIT e task runners (Gulp, é preferencial)
- Experiência com integrações de Google Analytics, Google Tag Manager e Facebook.

**DEsejáveis:**
- Familiaridade com o framework Laravel.
- Familiaridade com bancos de dados relacionais.

## Contratação

CLT ou PJ a combinar

## Nossa empresa

A Sensorial Comunicação é uma agência digital plena, e conta com uma equipe de profissionais altamente qualificados. Somos uma equipe de criativos, planners de mídia, atendimento, social media, analistas de métricas e estrategistas de mercado. Temos completa estrutura e expertise para desenvolver planejamento de comunicação e de marketing digital adequados à demanda de cada cliente.

## Como se candidatar

Se você acha que essa vaga tem a sua cara, mande seu c.v. para atendimento@sensorialbr.com com o assunto "[Github] Vaga Full-Stack"

## Labels

- Alocado
- CLT
- Pleno

**Comment by ArieltonPires** [comment]
vaga ainda aberta?

**Comment by didiraja** [comment]
Sim. Essa aí só fecha quando contratarem mesmo. Daí aviso aqui.
