### ISSUE TITLE
[São Paulo] Desenvolvedor JavaScript (MEAN Stack) JR/PL

### ISSUE THREAD

**Issue by williamknn** [frontendbr/vagas#99]
## Descrição da vaga

Se você é motivado por desafios técnicos, mais especificamente sobre desenvolvimento de aplicações de alto impacto no cotidiano das empresas, gostaríamos muito de falar com você!

Procuramos desenvolvedores com alta capacidade analítica, automotivados, que se preocupem com a qualidade e organização do código e que seja bom no FIFA 2013. Sim, gostamos dessa versão do FIFA :) 

Seu desafio será ajudar a criar a melhor solução de otimização logística para ajudar empresas a reduzirem custos e crescerem de forma sustentável!

Nós utilizamos MEAN Stack em toda a nossa solução. Você trabalhará principalmente na parte de backend (Node.js/Express) apoiando no desenvolvimento de novas funcionalidades na nossa REST API.
## Local

Escritório, São Paulo - Próximo ao metrô Saúde
## Benefícios
- Salário compatível com mercado, regime PJ.
- Ambiente de Startup: convivência com pessoas automotivadas em aprender e se desenvolver mais.
- Todos os dias temos uma competição para ver quem é o Rei do FIFA!
- Participar da fase de expansão de uma das empresas de tecnologia mais promissoras do Brasil!
## Requisitos

**Obrigatórios:**
- Node.js
- Express.js
- MongoDB
- AngularJS
- GIT
- RESTful API
- Ajax
- HTML5

**Desejáveis:**
- CSS3
- Sass
- AWS
- Twitter Bootstrap

**Diferenciais:**
- Alta capacidade analítica e raciocínio lógico;
- Conhecimentos na escrita de códigos de qualidade;
- Disposição para aprender muito e escrever muitas linhas de código;
## Contratação

PJ a combinar
## Nossa empresa

![routeasy-horizontal_180](https://cloud.githubusercontent.com/assets/3988151/17674989/32f6b60e-62fe-11e6-8f63-6bbed84a1025.png)

A RoutEasy é uma startup na área de logística. Nossa solução ajuda empresas no trabalho diário de planejamento da distribuição, otimizando a construção das cargas e o roteiro dos veículos. Nosso algoritmo de otimização é proprietário, desenvolvido pelos fundadores e o nosso histórico é de 10% à 40% do custo de transporte.
## Como se candidatar

Por favor envie um email para william.kennedy@routeasy.com.br com seu CV anexado / portfolio **e sua pretensão salarial** - enviar no assunto: Vaga JavaScript [Seu nível, entre JR e PL]

**Comment by ribeiroevandro** [comment]
Massa a vaga, pena que meu nível de JS ainda não é satisfatório e não posso me mudar agora... Mas uma dica, veja o site da empresa, sem o www ele não carregou pra mim... 😄

**Comment by williamknn** [comment]
@ribeiroevandro Estranho, testei aqui e ele tá redirecionando pro www. Vou dar uma olhada nisso mais tarde, obrigado! :)

**Comment by ribeiroevandro** [comment]
Deve ser cache na sua máquina, porque ao tentar no Chrome onde já tinha carregado ele redirecionou, mas abri no Firefox ele não redirecionou... Olha o print 

![screenshot 2016-08-15 19 07 25](https://cloud.githubusercontent.com/assets/943553/17681364/ad6fb4e0-631b-11e6-9f38-47a75aa5f47f.png)

**Comment by Carlosxell** [comment]
Vaga animal, um dia quando crescer e souber JS quero trabalhar com MEAN stack...rs

**Comment by williamknn** [comment]
Obrigado @ribeiroevandro !! Esse é o motivo pelo qual precisamos de um dev backend aqui hahahaha vou verificar isso :)

**Comment by williamknn** [comment]
@Carlosxell Opa, espero que consiga realizar suas ambições :)

**Comment by Marcelosilva10** [comment]
Vou me candidatar

**Comment by eduardojmatos** [comment]
@williamknn manolo! Já preencheu a vaga? Nos avise pra mantermos ou removermos da lista :)

**Comment by williamknn** [comment]
@eduardojmatos Ainda não, estou esperando uma resposta. Caso seja aceita, eu dou um feedback aqui :)

**Comment by eduardojmatos** [comment]
@williamknn blz! Boa sorte mano! =D

**Comment by williamknn** [comment]
@eduardojmatos Vaga fechada! :D

**Comment by eduardojmatos** [comment]
@williamknn  aeee! :)

**Comment by camilatigre** [comment]
@williamknn 
o FrontEndBR está tentando fazer uma métrica das pessoas que conseguiram fechar vagas por aqui, se você puder ajudar é só responder:

A pessoa que preencheu a vaga foi encontrada através desta issue?
a) Sim
b) Não
c) Não tenho certeza

**Comment by williamknn** [comment]
PESSOAL, VAGA REABERTA! :D

**Comment by williamknn** [comment]
@camilatigre Desculpe, só vi seu comentário agora quando fui reabrir a issue. Infelizmente não me lembro se a vaga havia sido preenchida através desta issue, mas assim que a preenchermos novamente, te dou um feedback!

**Comment by renanlara** [comment]
Poxa, pertinho de casa :D
