### ISSUE TITLE
[Belo Horizonte/MG] Front-End Developer na Aduana Web

### ISSUE THREAD

**Issue by avssouza** [frontendbr/vagas#990]
![logo-capa](https://user-images.githubusercontent.com/38570320/39070705-bdcf2e92-44ba-11e8-9ba5-66e4018f4144.png)

## Nossa empresa

A Aduana Web é uma startup que busca solucionar os problemas do mercado aduaneiro e tem como principal objetivo aumentar a produtividade e agilizar o atendimento ao cliente. 
O produto é uma plataforma web, acessível a partir de dispositivos diversos, desenvolvida com tecnologias modernas para aplicações em nuvem, planejada com foco no usuário e nos processos envolvidos nas atividades do despachante aduaneiro.
A nossa solução integra informações e documentos a fim de potencializar o mercado de comércio exterior brasileiro, aumentando o desempenho e eficiência do trabalho no setor.

Conheça mais sobre nossa empresa: www.aduanaweb.com.br/

## Descrição da vaga

Desenvolvimento Frontend da Plataforma Aduana Web, com ênfase na utilização do framework Angular 5 do Google. 

**Início imediato.**

**Obs.:** daremos preferência a mulheres desenvolvedoras.

## Local

Remoto ou Escritório, Bairro Santa Efigênia - Belo Horizonte

## Benefícios

- VR e VT
- Regime de contratação CLT ou PJ
- 8h diárias flexíveis
- Possibilidade de trabalho remoto

## Requisitos

**Obrigatórios:**
- Formação Acadêmica: graduando/graduado em algum curso na área de ciências da computação.
- Ter no mínimo 1 ano de experiência com desenvolvimento Javascript, necessário que já tenha atuado com o Framework Angular.

**Desejáveis:**
- Formação Acadêmica: Graduação em Ciências da Computação, Sistemas de informação ou Matemática Computacional
- Ter 1 ou 2 anos de experiência com desenvolvimento no framework Angular do Google.
- Conhecimentos em Scaffold.

**Diferenciais:**
- Pessoa focada, rápida no desenvolvimento, afim de aprender e desenvolver novas estratégias de organização do tempo.

## Contratação

- CLT ou PJ

## Como se candidatar

Favor cadastrar currículo através de < http://renataalves.rf.gd/ >

## Labels

- Alocado
- Remoto - Total
- CLT
- PJ
- Júnior
- Pleno

**Comment by NandoSantana** [comment]
olá, enviei meu currículo em anexo, e recebi um email de volta com o seguinte titulo: Atenção! Seu currículo não foi recebido! Parece que foi enviado é isto mesmo? Obrigado.

**Comment by cotts** [comment]
A vaga é para Angular 2+  ou AngularJS?

**Comment by avssouza** [comment]
Olá, @cotts, a vaga preferencialmente é para Angular 2+

**Comment by Gabriel10Velloso** [comment]
tem como enviar o curriculum por e-mail ao invés de cadastrar tudo no endereço indicado http://renataalves.rf.gd ?
