### ISSUE TITLE
[São Paulo/SP] Front-End Developer ReactJs no Hubster

### ISSUE THREAD

**Issue by KenjiKogake** [frontendbr/vagas#992]
## Descrição da vaga
Procuramos 2 desenvolvedores(as) Front-End para o [Hubster](https://www.hubster.com.br).

## Local

Berrini, São Paulo/SP

Alocado

## Requisitos

- Scrum
- Conhecimentos de UI e UX
- Boas práticas de desenvolvimento
- HTML5, CSS3, Javascript (**ReactJS**), Redux.

## Diferenciais
- Horários flexíveis.
- Possibilidade de home office.

## Contratação

PJ a combinar

## Nossa empresa

Queremos oferecer uma plataforma que possibilite que o estabelecimento faça a gestão completa do seu negócio.

## Como se candidatar

Por favor envie um email para kenji.kogake@hubster.com.br - enviar no assunto: Vaga FrontEnd

## Labels

- PJ
- Alocado
- Junior
- Pleno
- Senior

**Comment by RodzHC** [comment]
E-mail está voltando como domínio caixaleve.com.br não encontrado ...

**Comment by KenjiKogake** [comment]
Opa, corrigido, não tem o .br, foi no automático. Obrigado pelo aviso.
